### ISSUE TITLE
The getter 'window' was called on null while initialising Intercom 

### ISSUE THREAD

**Issue by nikhil-francium** [flutter/flutter#27541]
```
[VERBOSE-2:ui_dart_state.cc(148)] Unhandled Exception: NoSuchMethodError: The getter 'window' was called on null.
Receiver: null                                                          
Tried calling: window                                                   
#0      Object.noSuchMethod (dart:core/runtime/libobject_patch.dart:50:5)
#1      BinaryMessages._sendPlatformMessage (package:flutter/src/services/platform_messages.dart:40:30)
#2      BinaryMessages.send (package:flutter/src/services/platform_messages.dart:88:12)
#3      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:295:50)
<asynchronous suspension>                                               
#4      Intercom.initialize (package:intercom_flutter/intercom_flutter.dart:15:21)
#5      main (package:agents_app/main.dart:7:18)                        
<asynchronous suspension>                                               
#6      _runMainZoned.<anonymous closure>.<anonymous closure> (dart:ui/hooks.dart:170:23)
#7      _rootRun (dart:async/zone.dart:1124:13)                         
#8      _CustomZone.run (dart:async/zone.dart:1021:19)                  
#9      _runZoned (dart:async/zone.dart:1516:10)                        
#10     runZoned (dart:async/zone.dart:1500:12)                         
#11     _runMainZoned.<anonym<…>                                        
        [C1.1 9CD307DD-B8CA-4DAA-B59B-4F97606BFCF3 192.168.68.105:65238<->173.194.219.95:443]
        Connected Path: satisfied (Path is satisfied), interface: en0   
        Duration: 1.487s, DNS @0.002s took 0.229s, TCP @0.234s took 0.258s, TLS took 0.712s
        bytes in/out: 4758/1033, packets in/out: 10/9, rtt: 0.261s, retransmitted packets: 0, out-of-order packets: 0
 5,800ms (!)                                 
```

**Comment by nikhil-francium** [comment]
My code:
```
import 'package:flutter/material.dart';
import 'package:intercom_flutter/intercom_flutter.dart';

void main() async{
await Intercom.initialize(intercomAppId,
      iosApiKey: intercomiOSAPIkey, androidApiKey: intercomAndroidAPIkey);
  runApp(MaterialApp(home: MyApp()));
}

class MyApp extends StatefulWidget {
  @override
  _MyAppState createState() => _MyAppState();
}

class _MyAppState extends State<MyApp> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text("Intercom Issue"),
      ),
      body: Container(),
    );
  }
}

```
Flutter doctor output:

```
[✓] Flutter (Channel master, v1.2.1-pre.89, on Mac OS X 10.14 18A391, locale en-GB)
    • Flutter version 1.2.1-pre.89 at /Users/franciumtech/OfficeWorks/flutter_setup/flutter
    • Framework revision 32b9c2f07e (4 hours ago), 2019-02-05 00:54:54 -0800
    • Engine revision 93aa035dd4
    • Dart version 2.1.2 (build 2.1.2-dev.0.0 b53dceadaa)

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/franciumtech/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Library/Java/JavaVirtualMachines/jdk1.8.0_201.jdk/Contents/Home/bin/java
    • Java version Java(TM) SE Runtime Environment (build 1.8.0_201-b09)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.1, Build version 10B61
    • ios-deploy 1.9.4
    • CocoaPods version 1.5.3

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.io/setup/#android-setup for detailed instructions).

[✓] IntelliJ IDEA Community Edition (version 2018.3.4)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 32.0.3
    • Dart plugin version 183.5429.25

[✓] Connected device (1 available)
    • iPhone X • 0EAF67EC-CA81-4142-900A-364FA0977D2D • ios • iOS 12.1 (simulator)


```

**Comment by wouterhardeman** [comment]
This is related to a plugin that is not supported by the Flutter team.

Please file your issue in the GitHub repository of [intercom_flutter](https://github.com/v3rm0n/intercom_flutter).

**Comment by tlueder** [comment]
Hi, this is probably related to issue #27538 and I get the same error when using the plugin path_provider: ^0.5.0 when calling getApplicationDocumentsDirectory()

**Comment by wouterhardeman** [comment]
@tlueder I just noticed the same pattern. Seems like a regression issue coming somewhere from a change in the app initialization.

**Comment by wouterhardeman** [comment]
Here's the pull request: https://github.com/flutter/flutter/pull/27389

@Hixie commented on it that it's a breaking change 7 hours ago so the team is aware. [Here](https://github.com/flutter/flutter/pull/27389#issuecomment-460537469) he points out this is also an issue for people using plugins before `runApp()`.

**Comment by nikhil-francium** [comment]
@wouterhardeman In `stable` channel it is working fine.

**Comment by matthew-carroll** [comment]
PR for a fix is here:
https://github.com/flutter/flutter/pull/27564

**Comment by Hixie** [comment]
This has been resolved. Apologies for anyone who was affected.
