### ISSUE TITLE
CupertinoTimerPicker breaks if minuteInterval > 1

### ISSUE THREAD

**Issue by aryzhov** [flutter/flutter#27621]
## Steps to Reproduce

1. Create a new Flutter application from the template.

2. change class `_MyHomePageState` as follows:

```dart
class _MyHomePageState extends State<MyHomePage> {
  var duration = Duration(hours: 1);

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            Text(
              'The duration is:',
            ),
            Text(
              '$duration',
              style: Theme.of(context).textTheme.display1,
             ),
          ],
        ),
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: () => _showTimePicker(context),
        tooltip: 'Change',
        child: Icon(Icons.av_timer),
      ),
    );
  }

  _showTimePicker(BuildContext context) {
    showModalBottomSheet(
      context: context,
      builder: (context) {
        return CupertinoTimerPicker(
          mode: CupertinoTimerPickerMode.hm,
          initialTimerDuration: duration,
          minuteInterval: 15,
          onTimerDurationChanged: (value) {
            setState(() {
              duration = value;
            });
          },
        );
      });
  }

}
```
3. Run the project on Android or iOS. You will see the following text: "The duration is: 1:00:00.000000"
4. Press the button. A popup with hour an minute selectors will appear. 
5. Choose "1 hour 15 minutes". Dismiss the popup. 

Expected result: "The duration is: 1:15:00.000000"
Actual result:  "The duration is: 1:01:00.000000"

In addition, an error is printed to the console:

```
flutter: 'initialTimerDuration.inMinutes % minuteInterval == 0': is not true.
```

## Logs

```
Launching lib/main.dart on Android SDK built for x86 in debug mode...
Initializing gradle...
Resolving dependencies...
Gradle task 'assembleDebug'...
Built build/app/outputs/apk/debug/app-debug.apk.
Installing build/app/outputs/apk/app.apk...
Syncing files to device Android SDK built for x86...
D/        (23616): HostConnection::get() New Host Connection established 0xe3efab80, tid 23642
D/EGL_emulation(23616): eglMakeCurrent: 0xe3edc860: ver 3 0 (tinfo 0xe2591ed0)
I/flutter (23616): ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
I/flutter (23616): The following assertion was thrown building BottomSheet(dirty, state: _BottomSheetState#43ce5):
I/flutter (23616): 'package:flutter/src/cupertino/date_picker.dart': Failed assertion: line 971 pos 15:
I/flutter (23616): 'initialTimerDuration.inMinutes % minuteInterval == 0': is not true.
I/flutter (23616): 
I/flutter (23616): Either the assertion indicates an error in the framework itself, or we should provide substantially
I/flutter (23616): more information in this error message to help you determine and fix the underlying cause.
I/flutter (23616): In either case, please report this assertion by filing a bug on GitHub:
I/flutter (23616):   https://github.com/flutter/flutter/issues/new?template=BUG.md
I/flutter (23616): 
I/flutter (23616): When the exception was thrown, this was the stack:
I/flutter (23616): #2      new CupertinoTimerPicker (package:flutter/src/cupertino/date_picker.dart:971:15)
I/flutter (23616): #3      _MyHomePageState._showTimePicker.<anonymous closure> (package:flutter_time_picker_bug/main.dart:82:16)
I/flutter (23616): #4      _BottomSheetState.build (package:flutter/src/material/bottom_sheet.dart:152:21)
I/flutter (23616): #5      StatefulElement.build (package:flutter/src/widgets/framework.dart:3809:27)
I/flutter (23616): #6      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3721:15)
I/flutter (23616): #7      Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
I/flutter (23616): #8      StatefulElement.update (package:flutter/src/widgets/framework.dart:3878:5)
I/flutter (23616): #9      Element.updateChild (package:flutter/src/widgets/framework.dart:2742:15)
I/flutter (23616): #10     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4867:14)
I/flutter (23616): #11     Element.updateChild (package:flutter/src/widgets/framework.dart:2742:15)
I/flutter (23616): #12     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4867:14)
I/flutter (23616): #13     Element.updateChild (package:flutter/src/widgets/framework.dart:2742:15)
I/flutter (23616): #14     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4867:14)
I/flutter (23616): #15     Element.updateChild (package:flutter/src/widgets/framework.dart:2742:15)
I/flutter (23616): #16     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3732:16)
I/flutter (23616): #17     Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
I/flutter (23616): #18     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2286:33)
I/flutter (23616): #19     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding&WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:685:20)
I/flutter (23616): #20     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:219:5)
I/flutter (23616): #21     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:990:15)
I/flutter (23616): #22     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:930:9)
I/flutter (23616): #23     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:842:5)
I/flutter (23616): #24     _invoke (dart:ui/hooks.dart:159:13)
I/flutter (23616): #25     _drawFrame (dart:ui/hooks.dart:148:3)
I/flutter (23616): (elided 2 frames from class _AssertionError)
I/flutter (23616): ════════════════════════════════════════════════════════════════════════════════════════════════════
I/flutter (23616): Another exception was thrown: 'package:flutter/src/cupertino/date_picker.dart': Failed assertion: line 971 pos 15: 'initialTimerDuration.inMinutes % minuteInterval == 0': is not true.
I/chatty  (23616): uid=10089(us.ryzhov.fluttertimepickerbug) 1.ui identical 3 lines
I/flutter (23616): Another exception was thrown: 'package:flutter/src/cupertino/date_picker.dart': Failed assertion: line 971 pos 15: 'initialTimerDuration.inMinutes % minuteInterval == 0': is not true.
```

## flutter analyze

```
Analyzing flutter_time_picker_bug...
No issues found! (ran in 2.2s)
```

## flutter doctor -v
```
[✓] Flutter (Channel beta, v1.1.8, on Mac OS X 10.13.6 17G3025, locale en-US)
    • Flutter version 1.1.8 at /Users/alex/flutter
    • Framework revision 985ccb6d14 (4 weeks ago), 2019-01-08 13:45:55 -0800
    • Engine revision 7112b72cc2
    • Dart version 2.1.1 (build 2.1.1-dev.0.1 ec86471ccc)

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/alex/Library/Android/sdk
    • Android NDK at /Users/alex/Library/Android/sdk/ndk-bundle
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.1, Build version 10B61
    • ios-deploy 2.0.0
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 31.3.1
    • Dart plugin version 181.5656
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)

[✓] VS Code (version 1.30.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 2.22.3

[✓] Connected device (2 available)
    • Android SDK built for x86 • emulator-5554                        • android-x86   • Android 9 (API 28)
      (emulator)
    • iPhone XS Max             • 45436B63-2D03-45B7-8C91-296C4B8339B6 • ios           • iOS 12.1 (simulator)

• No issues found!
```

**Comment by zoechi** [comment]
Can you please make the reproduction code runnable so that copy/paste into `lib/main.dart` allows to execute (incl `main() {...}`.

**Comment by wouterhardeman** [comment]
This seems to be caused by [this line](https://github.com/flutter/flutter/blob/2aad59314fb98f29a4dcdcacda77c0926418ea95/packages/flutter/lib/src/cupertino/date_picker.dart#L1153) where the index is used and is not multiplied by the `minuteInterval`. This results in 1:01:00 when selecting 15 min or 1:02:00 when selecting 30 min etc..

**Comment by aryzhov** [comment]
@wouterhardeman Thank you for your help, I was able to make this change and submitted  a pull request.
