### ISSUE TITLE
Camera error on photo capture [Android]

### ISSUE THREAD

**Issue by xperiafan13-rom** [flutter/flutter#27657]
Hi, I get error when I capture image on Android, im use current version `camera: ^0.3.0+2`

## Steps to Reproduce

I follow camera sample, this is my code:
 
```dart
void onCameraSelected(CameraDescription cameraDescription) async {
    if (controller != null) await controller.dispose();
    controller = CameraController(cameraDescription, ResolutionPreset.medium);

    controller.addListener(() {
      if (mounted) setState(() {});
      if (controller.value.hasError) {
        showMessage('Camera Error: ${controller.value.errorDescription}');
      }
    });

    try {
      await controller.initialize().then((_) {
        controller.startImageStream((CameraImage image) {
          if (!isDetecting) {
            isDetecting = true;
            runDetection(image);
          }
        });
      });
    } on CameraException catch (e) {
      showException(e);
    }
  }

  String timestamp() => new DateTime.now().millisecondsSinceEpoch.toString();

  void _captureImage() {
    takePicture().then((String filePath) {
      if (mounted) {
        setState(() {
          imagePath = filePath;
        });
        if (filePath != null) {
          showMessage('Picture saved to $filePath');
          
        }
      }
    });
  }
```

## Logs

```
java.lang.IllegalArgumentException: submitRequestList:221: Request targets Surface that is not part of current capture session
E/MethodChannel#plugins.flutter.io/camera(13652): 	at android.hardware.camera2.CameraManager.throwAsPublicException(CameraManager.java:651)
E/MethodChannel#plugins.flutter.io/camera(13652): 	at android.hardware.camera2.impl.ICameraDeviceUserWrapper.submitRequestList(ICameraDeviceUserWrapper.java:86)
E/MethodChannel#plugins.flutter.io/camera(13652): 	at android.hardware.camera2.impl.CameraDeviceImpl.submitCaptureRequest(CameraDeviceImpl.java:935)
E/MethodChannel#plugins.flutter.io/camera(13652): 	at android.hardware.camera2.impl.CameraDeviceImpl.capture(CameraDeviceImpl.java:824)
E/MethodChannel#plugins.flutter.io/camera(13652): 	at android.hardware.camera2.impl.CameraCaptureSessionImpl.capture(CameraCaptureSessionImpl.java:181)
E/MethodChannel#plugins.flutter.io/camera(13652): 	at io.flutter.plugins.camera.CameraPlugin$Camera.takePicture(CameraPlugin.java:601)
E/MethodChannel#plugins.flutter.io/camera(13652): 	at io.flutter.plugins.camera.CameraPlugin$Camera.access$800(CameraPlugin.java:270)
E/MethodChannel#plugins.flutter.io/camera(13652): 	at io.flutter.plugins.camera.CameraPlugin.onMethodCall(CameraPlugin.java:196)
E/MethodChannel#plugins.flutter.io/camera(13652): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:200)
E/MethodChannel#plugins.flutter.io/camera(13652): 	at io.flutter.view.FlutterNativeView.handlePlatformMessage(FlutterNativeView.java:163)
E/MethodChannel#plugins.flutter.io/camera(13652): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/MethodChannel#plugins.flutter.io/camera(13652): 	at android.os.MessageQueue.next(MessageQueue.java:379)
E/MethodChannel#plugins.flutter.io/camera(13652): 	at android.os.Looper.loop(Looper.java:144)
E/MethodChannel#plugins.flutter.io/camera(13652): 	at android.app.ActivityThread.main(ActivityThread.java:7425)
E/MethodChannel#plugins.flutter.io/camera(13652): 	at java.lang.reflect.Method.invoke(Native Method)
E/MethodChannel#plugins.flutter.io/camera(13652): 	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:245)
E/MethodChannel#plugins.flutter.io/camera(13652): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:921)
E/MethodChannel#plugins.flutter.io/camera(13652): Caused by: android.os.ServiceSpecificException: submitRequestList:221: Request targets Surface that is not part of current capture session (code 3)
E/MethodChannel#plugins.flutter.io/camera(13652): 	at android.os.Parcel.readException(Parcel.java:1960)
E/MethodChannel#plugins.flutter.io/camera(13652): 	at android.os.Parcel.readException(Parcel.java:1892)
E/MethodChannel#plugins.flutter.io/camera(13652): 	at android.hardware.camera2.ICameraDeviceUser$Stub$Proxy.submitRequestList(ICameraDeviceUser.java:334)
E/MethodChannel#plugins.flutter.io/camera(13652): 	at android.hardware.camera2.impl.ICameraDeviceUserWrapper.submitRequestList(ICameraDeviceUserWrapper.java:84)
E/MethodChannel#plugins.flutter.io/camera(13652): 	... 15 more
```

Please help me!

**Comment by zoechi** [comment]
To investigate we would need a minimal runnable reproduction
as a single file so that we can just copy your code into `lib/main.dart` of a new project and run to reproduce.

**Comment by zoechi** [comment]
I only found https://stackoverflow.com/questions/51745137/camera-preview-and-camera-capture-use-camera2-api-but-occur-request-targets-su with a similar error message.
