### ISSUE TITLE
When using the webview_flutter I get the issue: Bad state: Future already completed.

### ISSUE THREAD

**Issue by desire** [flutter/flutter#27676]
## Steps to Reproduce

1. Use webview_flutter example
2. Use this example in a PageView
3. Test out the app

When I do this the WebView works fine for the first time I swipe onto it however when I go to the next page and go back I get this error.

## Logs

```
[VERBOSE-2:shell.cc(184)] Dart Error: Unhandled exception:
Bad state: Future already completed
#0      _AsyncCompleter.complete (dart:async/future_impl.dart:39:31)
#1      WebViewExample.build.<anonymous closure>.<anonymous closure> (package:CyberAIO/embeded_webview.dart:27:25)
#2      _WebViewState._onPlatformViewCreated (package:webview_flutter/webview_flutter.dart:209:14)
#3      _UiKitViewState._createNewUiKitView (package:flutter/src/widgets/platform_view.dart:459:14)
<asynchronous suspension>
#4      _UiKitViewState._initializeOnce (package:flutter/src/widgets/platform_view.dart:397:5)
#5      _UiKitViewState.didChangeDependencies (package:flutter/src/widgets/platform_view.dart:407:5)
#6      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3846:12)
#7      ComponentElement.mount (package:flutter/src/widgets/framework.dart:3696:5)
#8      Element.inflateWidget (package:flutter/src/widgets/framework.dart:2950:14)
#9      Element.updateChild (package:flutter/src/widgets/fra<…>
```

```
   info • Cancel instances of dart.async.StreamSubscription • lib/main.dart:32:22 • cancel_subscriptions
   info • The value of the field '_sub' isn't used • lib/main.dart:32:22 • unused_field
   info • This function has a return type of 'Future<String>', but doesn't end with a return statement •
          lib/main.dart:44:3 • missing_return
   info • The value of the local variable 'height' isn't used • lib/quick_task.dart:12:12 • unused_local_variable
   info • The value of the local variable 'height' isn't used • lib/settings.dart:12:12 • unused_local_variable
   info • The value of the local variable 'height' isn't used • lib/widgets/card_table.dart:22:12 •
          unused_local_variable
   info • Unused import: '../main.dart' • lib/widgets/header.dart:3:8 • unused_import

```

```
[✓] Flutter (Channel stable, v1.0.0, on Mac OS X 10.14.2 18C54, locale en-US)
[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.io/setup/#android-setup for detailed instructions).
      If Android SDK has been installed to a custom location, set $ANDROID_HOME to that location.
      You may also want to add it to your PATH environment variable.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.1)
[!] Android Studio (not installed)
[✓] VS Code (version 1.30.2)
[✓] Connected device (2 available)
```
I am only building for iOS thus android is not setup.

**Comment by desire** [comment]
Problem was fixed by removing future completion after webview load
