### ISSUE TITLE
Disposing a (nested) Scrollable while holding in overscroll (iOS) may crash

### ISSUE THREAD

**Issue by goderbauer** [flutter/flutter#27707]
```dart
void main() {
  runApp(new MaterialApp(
    home: Foo(),
  ));
}

class Foo extends StatefulWidget {
  @override
  FooState createState() => FooState();
}


class FooState extends State<Foo> {

  bool show = true;

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: show ? Demo() : Container(),
      floatingActionButton: FloatingActionButton(
        onPressed: () {
          setState(() {
            show = !show;
          });
        },
      ),
    );
  }
}

class Demo extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return SingleChildScrollView(
      scrollDirection: Axis.horizontal,
      child: Container(
        width: 500.0,
        child: ListView.builder(
          itemBuilder: (BuildContext context, int index) {
            return Container(
              color: index % 2 == 0 ? Colors.red : Colors.green,
              height: 200.0,
              child: Text('Hello $index'),
            );
          },
        ),
      ),
    );
  }
}
```

Execute this code on iOS (!) and drag the first tile down all the way to the bottom of the screen (this will cause "overscroll"). Let go of the finger that scrolled the tile down. Before the tile can bounce all they way back, press and hold another finger on the screen to prevent the tile from bouncing back to the top. With the finger still down, press the FAB to dispose the scroll view ==> 🔥 🔥 🔥 

```
flutter: ══╡ EXCEPTION CAUGHT BY GESTURE ╞═══════════════════════════════════════════════════════════════════
flutter: The following assertion was thrown while handling a gesture:
flutter: 'package:flutter/src/widgets/notification_listener.dart': Failed assertion: line 58 pos 12: 'target
flutter: != null': is not true.
flutter:
flutter: Either the assertion indicates an error in the framework itself, or we should provide substantially
flutter: more information in this error message to help you determine and fix the underlying cause.
flutter: In either case, please report this assertion by filing a bug on GitHub:
flutter:   https://github.com/flutter/flutter/issues/new?template=BUG.md
flutter:
flutter: When the exception was thrown, this was the stack:
flutter: #2      Notification.dispatch (package:flutter/src/widgets/notification_listener.dart:58:12)
flutter: #3      ScrollActivity.dispatchScrollStartNotification (package:flutter/src/widgets/scroll_activity.dart:91:65)
flutter: #4      ScrollPosition.didStartScroll (package:flutter/src/widgets/scroll_position.dart:650:14)
flutter: #5      ScrollPosition.beginActivity (package:flutter/src/widgets/scroll_position.dart:642:7)
flutter: #6      ScrollPositionWithSingleContext.beginActivity (package:flutter/src/widgets/scroll_position_with_single_context.dart:117:11)
flutter: #7      ScrollPositionWithSingleContext.goBallistic (package:flutter/src/widgets/scroll_position_with_single_context.dart:149:7)
flutter: #8      HoldScrollActivity.cancel (package:flutter/src/widgets/scroll_activity.dart:204:14)
flutter: #9      ScrollableState._handleDragCancel (package:flutter/src/widgets/scrollable.dart:508:12)
flutter: #10     GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:120:24)
flutter: #11     DragGestureRecognizer.didStopTrackingLastPointer (package:flutter/src/gestures/monodrag.dart:242:9)
flutter: #12     OneSequenceGestureRecognizer.stopTrackingPointer (package:flutter/src/gestures/recognizer.dart:249:9)
flutter: #13     DragGestureRecognizer.rejectGesture (package:flutter/src/gestures/monodrag.dart:233:5)
flutter: #14     GestureArenaManager._resolve (package:flutter/src/gestures/arena.dart:213:14)
flutter: #15     GestureArenaEntry.resolve (package:flutter/src/gestures/arena.dart:52:12)
flutter: #16     OneSequenceGestureRecognizer.resolve (package:flutter/src/gestures/recognizer.dart:184:13)
flutter: #17     OneSequenceGestureRecognizer.dispose (package:flutter/src/gestures/recognizer.dart:189:5)
flutter: #18     DragGestureRecognizer.dispose (package:flutter/src/gestures/monodrag.dart:278:11)
flutter: #19     RawGestureDetectorState.dispose (package:flutter/src/widgets/gesture_detector.dart:705:18)
flutter: #20     StatefulElement.unmount (package:flutter/src/widgets/framework.dart:3910:12)
flutter: #21     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1696:13)
flutter: #22     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1694:7)
flutter: #23     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3764:14)
flutter: #24     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1692:13)
flutter: #25     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1694:7)
flutter: #26     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:4858:14)
flutter: #27     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1692:13)
flutter: #28     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1694:7)
flutter: #29     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3764:14)
flutter: #30     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1692:13)
flutter: #31     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1694:7)
flutter: #32     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3764:14)
flutter: #33     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1692:13)
flutter: #34     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1694:7)
flutter: #35     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3764:14)
flutter: #36     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1692:13)
flutter: #37     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1694:7)
flutter: #38     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:4858:14)
flutter: #39     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1692:13)
flutter: #40     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1694:7)
flutter: #41     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3764:14)
flutter: #42     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1692:13)
flutter: #43     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1694:7)
flutter: #44     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:4858:14)
flutter: #45     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1692:13)
flutter: #46     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1694:7)
flutter: #47     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:4858:14)
flutter: #48     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1692:13)
flutter: #49     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1694:7)
flutter: #50     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:4858:14)
flutter: #51     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1692:13)
flutter: #52     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1694:7)
flutter: #53     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:4858:14)
flutter: #54     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1692:13)
flutter: #55     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1694:7)
flutter: #56     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:4858:14)
flutter: #57     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1692:13)
flutter: #58     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1694:7)
flutter: #59     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3764:14)
flutter: #60     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1692:13)
flutter: #61     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1694:7)
flutter: #62     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3764:14)
flutter: #63     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1692:13)
flutter: #64     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1694:7)
flutter: #65     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:4858:14)
flutter: #66     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1692:13)
flutter: #67     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1694:7)
flutter: #68     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3764:14)
flutter: #69     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1692:13)
flutter: #70     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1694:7)
flutter: #71     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3764:14)
flutter: #72     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1692:13)
flutter: #73     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1694:7)
flutter: #74     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3764:14)
flutter: #75     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1692:13)
flutter: #76     ListIterable.forEach (dart:_internal/iterable.dart:39:13)
flutter: #77     _InactiveElements._unmountAll (package:flutter/src/widgets/framework.dart:1705:25)
flutter: #78     BuildOwner.finalizeTree.<anonymous closure> (package:flutter/src/widgets/framework.dart:2359:27)
flutter: #79     BuildOwner.lockState (package:flutter/src/widgets/framework.dart:2191:15)
flutter: #80     BuildOwner.finalizeTree (package:flutter/src/widgets/framework.dart:2358:7)
flutter: #81     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding&WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:702:18)
flutter: #82     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:268:5)
flutter: #83     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:988:15)
flutter: #84     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:928:9)
flutter: #85     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:840:5)
flutter: #89     _invoke (dart:ui/hooks.dart:195:10)
flutter: #90     _drawFrame (dart:ui/hooks.dart:168:3)
flutter: (elided 5 frames from class _AssertionError and package dart:async)
flutter:
flutter: Handler: onCancel
flutter: Recognizer:
flutter:   VerticalDragGestureRecognizer#6ce8a(start behavior: down)
flutter: ════════════════════════════════════════════════════════════════════════════════════════════════════

```

**Comment by goderbauer** [comment]
What's happening here: When the second finger hits the screen to prevent the bounce back it is unclear if that down event is going to be a horizontal drag (makes the gesture detector of the SingleChildScrollView) or a vertical swipe (the gesture detector of the ListView wins). Both Gesture detectors have received the down event and are waiting in the gesture arena to decide who will one. However, before that can happen, the view is disposed and as a result both gesture detectors are told that the down event has been cancelled:

https://github.com/flutter/flutter/blob/ef276ffea501a9f9ea4d627f9d069e52a31b75be/packages/flutter/lib/src/widgets/scrollable.dart#L504-L512

There's an ongoing hold activity in the ListView scrollable, which is responsible for keeping Tile 1 from bouncing back to the top. That activity is canceled. As a result of the cancellation the scrollable realizes that it is not in a stable position (`position.outOfRange` is true) and goes ballistic to fix that:

https://github.com/flutter/flutter/blob/ef276ffea501a9f9ea4d627f9d069e52a31b75be/packages/flutter/lib/src/widgets/scroll_activity.dart#L202-L205

https://github.com/flutter/flutter/blob/ef276ffea501a9f9ea4d627f9d069e52a31b75be/packages/flutter/lib/src/widgets/scroll_physics.dart#L317-L330

Unfortunately, at this point some elements (TBD what exactly) have already been disposed in anticipation of the whole Scrollable to be disposed. The BallisticScrollActivity can't really be executed in this half-dead environment ==> Crash.

**Comment by goderbauer** [comment]
More details: When the Scrollables are disposed, their `RawGestureDetectorState` is the first one to go. This causes the drag event to be cancelled, which ultimately triggers the ballistic scroll activity. To notify any intersted party of the new scroll activity, a `ScrollStartNotification` is dispatched in the context of the already disposed `RawGestureDetectorState`:

https://github.com/flutter/flutter/blob/6d20ff244650ffc94761eefb3a4f93a6186c3e65/packages/flutter/lib/src/widgets/scroll_position.dart#L649-L651

`context.notificationContext` is taken from the (global) key of the already disposed `RawGestureDetectorState`:

https://github.com/flutter/flutter/blob/6d20ff244650ffc94761eefb3a4f93a6186c3e65/packages/flutter/lib/src/widgets/scrollable.dart#L465

In our crash case, `context.notificationContext` (= `target` in the code below) is already null and we crash when dispatching the notification:

https://github.com/flutter/flutter/blob/6d20ff244650ffc94761eefb3a4f93a6186c3e65/packages/flutter/lib/src/widgets/notification_listener.dart#L57-L60

**Comment by goderbauer** [comment]
`_gestureDetectorKey.currentContext` is null because when the RawGestureDetector is disposed, its state is unregistered from the attached GlobalKey before `RawGestureDetectorState.dispose()` is called in `StatefulElement.unmount`.
