### ISSUE TITLE
NoSuchMethodError: The method 'validate' was called on null.

### ISSUE THREAD

**Issue by Yogita75** [flutter/flutter#27714]
Here is my dart file:
```dart
import 'package:arluchat3/home_screen.dart';
import 'package:firebase_auth/firebase_auth.dart';
import 'package:firebase_database/firebase_database.dart';
import 'package:flutter/material.dart';
import 'package:fluttertoast/fluttertoast.dart';

class NextChannel extends StatefulWidget {

  NextChannel({
    Key key,
  }) : super(key:key);


  @override
  _NextChannelState createState() => _NextChannelState();

}
enum values {one, two}

class _NextChannelState extends State<NextChannel> {

  values character = values.one;

  GlobalKey<FormState> _key = new GlobalKey();
  bool _autovalidate = false;

  String channeltype, link;
  TextEditingController chlink = new TextEditingController();


  @override
  void initState() {

    super.initState();
  }
    @override
    Widget build(BuildContext context) {

      return Scaffold(
          appBar: AppBar(
            backgroundColor: Colors.lightBlue,
            leading: new IconButton(
                icon: Icon(Icons.arrow_back, color: Colors.white,),
                onPressed: () {
                  Navigator.of(context).pop();
                  Navigator.push(context,
                      new MaterialPageRoute(
                          builder: (BuildContext context) => new HomeScreen()));
                }
            ),
            title: Text("Settings"),
            actions: <Widget>[

              new IconButton(icon: Icon(Icons.done, color: Colors.white,),
                onPressed:  savechannels(),
              )
            ],
          ),
          body:
          SafeArea(
            child: SingleChildScrollView(
              child: new Container(
                padding: EdgeInsets.only(top: 16.0),
                child: Form(
                  key: _key,
                  autovalidate: _autovalidate,

                  child: Column(
                      children: <Widget>[

                        RadioListTile<values>(
                          title: const Text('Public Channel'),
                          subtitle: Text(
                              "Public channels can be found in search, anyone can join them."),
                          value: values.one,
                          groupValue: character,
                          //key: UniqueKey(),
                          onChanged: (values value) {
                            setState(() {
                              character = value;
                            });
                          },
                        ),


                        RadioListTile<values>(
                          title: const Text('Private Channel'),
                          subtitle: const Text(
                              "Private channels can only be join via an invite link."),
                          value: values.two,
                          groupValue: character,
                          //key: UniqueKey(),
                          onChanged: (values value) {
                            setState(() {
                              character = value;
                            });
                          },
                        ),




                      Divider(height: 30.0, color: Colors.white,),
                      Container(
                          height: 10.0,
                          color: Colors.blueGrey[50],
                        ),

                        Container(
                          child: getCustomContainer(),
                        ),

                        //new Container(child: child,),
                      ])

                  ),
                ),
              ),
            ),
          );
    }

  Widget publicchannel() {
     return Container(
      child: new Column(
        children: <Widget>[
      Divider(height: 5.0, color: Colors.white,),

      ListTile(
       leading: Text("Permanent link",
         style: TextStyle(color: Colors.lightBlue,
         fontWeight: FontWeight.bold),),
      ),

      Padding(
        padding: const EdgeInsets.symmetric(horizontal: 11.0),
          child: TextFormField(
            initialValue: '/t.me',
            //controller: chlink,
            key: _key,
            //autovalidate: _autovalidate,
            validator: validateLink,
            onSaved: (value) {
            link = value;
            //chlink.clear();
            },
        ),
      ),
      Divider(height: 30.0, color: Colors.white,),
      Container(
        height: 10.0,
        color: Colors.blueGrey[50],
      ),
      Divider(height: 6.0, color: Colors.white,),

      ListTile(
        leading: Text(
          "If you set a permanent link, other people will be able to find and join your channel.",
            style: TextStyle(color: Colors.grey),),
      ),
      Divider(height: 0.0, color: Colors.white,),
      ListTile(
        leading:
      Text(
        " You can use a-z, 0-9 and underscores."
            "Minimum length is 5 characters.",
        style: TextStyle(color: Colors.grey)),

      ),

      ]),
    );

  }

  Widget privatechannel() {
    return Container(
      child: new Column(
        children: <Widget>[
          Divider(height: 5.0, color: Colors.white,),

          ListTile(
            leading: Text("Invite link",
              style: TextStyle(color: Colors.lightBlue,
                  fontWeight: FontWeight.bold),),
          ),
          Padding(
            padding: const EdgeInsets.symmetric(horizontal: 11.0),
            child: TextFormField(
              //controller: chlink,
              key: _key,
              //autovalidate: _autovalidate,
              validator: validateLink,
              onSaved: (value) {
                link = value;
                //chlink.clear();
              },

            ),
          ),
          Divider(height: 30.0, color: Colors.white,),
          Container(
            height: 10.0,
            color: Colors.blueGrey[50],
          ),
          Divider(height: 6.0, color: Colors.white,),

          ListTile(
            leading: Text(
              "People can join your channel by following this link."
                  "You can revoke the link any time.",
              style: TextStyle(color: Colors.grey),),
          ),

        ],
      ),
    );

  }

  Widget getCustomContainer() {
    switch (character) {
      case values.one:
        return publicchannel();
      case values.two:
        return privatechannel();

    }

    return publicchannel();
  }

  savechannels() {
    if (_key.currentState.validate()) {
      _key.currentState.save();
      DatabaseReference ref = FirebaseDatabase.instance.reference();

      var data = {

        "character": character,
        "link": link,

      };
      ref.child('NewChannels/').push().update(data).then((v) {
        _key.currentState.reset();

      });
    } else {
      setState(() {
        _autovalidate = true;
      });
    }
  }


  String validateLink(String value) {
    String patttern = r'(^[a-zA-Z ]*$)';
    RegExp regExp = new RegExp(patttern);
    if (value.length == 0) {
      return "Name is Required";
    } else if (!regExp.hasMatch(value)) {
      return "Name must be a-z and A-Z";
    }
    return null;
  }
}
```

This is my console log:

```
E/flutter ( 5384): [ERROR:flutter/shell/common/shell.cc(184)] Dart Error: Unhandled exception:
E/flutter ( 5384): NoSuchMethodError: The getter 'absolute' was called on null.
E/flutter ( 5384): Receiver: null
E/flutter ( 5384): Tried calling: absolute
E/flutter ( 5384): #0      Object.noSuchMethod (dart:core/runtime/libobject_patch.dart:50:5)
E/flutter ( 5384): #1      _StorageFileUploadTask._platformStart (file:///home/yogita/Documents/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_storage-1.0.4/lib/src/upload_task.dart:136:27)
E/flutter ( 5384): #2      StorageUploadTask._start (file:///home/yogita/Documents/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_storage-1.0.4/lib/src/upload_task.dart:35:21)
E/flutter ( 5384): <asynchronous suspension>
E/flutter ( 5384): #3      StorageReference.putFile (file:///home/yogita/Documents/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_storage-1.0.4/lib/src/storage_reference.dart:64:10)
E/flutter ( 5384): #4      NewChannelState.uploadImage (package:arluchat3/drawer/new_channel_page.dart:244:24)
E/flutter ( 5384): <asynchronous suspension>
E/flutter ( 5384): #5      NewChannelState.build.<anonymous closure> (package:arluchat3/drawer/new_channel_page.dart:88:15)
E/flutter ( 5384): #6      _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:507:14)
E/flutter ( 5384): #7      _InkResponseState.build.<anonymous closure> (package:flutter/src/material/ink_well.dart:562:30)
E/flutter ( 5384): #8      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:102:24)
E/flutter ( 5384): #9      TapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:242:9)
E/flutter ( 5384): #10     TapGestureRecognizer.handlePrimaryPointer (package:flutter/src/gestures/tap.dart:175:7)
E/flutter ( 5384): #11     PrimaryPointerGestureRecognizer.handleEvent (package:flutter/src/gestures/recognizer.dart:315:9)
E/flutter ( 5384): #12     PointerRouter._dispatch (package:flutter/src/gestures/pointer_router.dart:73:12)
E/flutter ( 5384): #13     PointerRouter.route (package:flutter/src/gestures/pointer_router.dart:101:11)
E/flutter ( 5384): #14     _WidgetsFlutterBinding&BindingBase&GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:180:19)
E/flutter ( 5384): #15     _WidgetsFlutterBinding&BindingBase&GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:158:22)
E/flutter ( 5384): #16     _WidgetsFlutterBinding&BindingBase&GestureBinding._handlePointerEvent (package:flutter/src/gestures/binding.dart:138:7)
E/flutter ( 5384): #17     _WidgetsFlutterBinding&BindingBase&GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:101:7)
E/flutter ( 5384): #18     _WidgetsFlutterBinding&BindingBase&GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:85:7)
E/flutter ( 5384): #19     _invoke1 (dart:ui/hooks.dart:168:13)
E/flutter ( 5384): #20     _dispatchPointerDataPacket (dart:ui/hooks.dart:122:5)
I/flutter ( 5384): ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
I/flutter ( 5384): The following NoSuchMethodError was thrown building NextChannel(dirty, state:
I/flutter ( 5384): _NextChannelState#a9abc):
I/flutter ( 5384): The method 'validate' was called on null.
I/flutter ( 5384): Receiver: null
I/flutter ( 5384): Tried calling: validate()
I/flutter ( 5384): When the exception was thrown, this was the stack:
I/flutter ( 5384): #0      Object.noSuchMethod (dart:core/runtime/libobject_patch.dart:50:5)
I/flutter ( 5384): #1      _NextChannelState.savechannels (package:arluchat3/drawer/nextchannel.dart:234:27)
I/flutter ( 5384): #2      _NextChannelState.build (package:arluchat3/drawer/nextchannel.dart:55:29)
I/flutter ( 5384): #3      StatefulElement.build (package:flutter/src/widgets/framework.dart:3809:27)
I/flutter ( 5384): #4      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3721:15)
I/flutter ( 5384): #5      Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
I/flutter ( 5384): #6      ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3701:5)
I/flutter ( 5384): #7      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3848:11)
I/flutter ( 5384): #8      ComponentElement.mount (package:flutter/src/widgets/framework.dart:3696:5)
I/flutter ( 5384): #9      Element.inflateWidget (package:flutter/src/widgets/framework.dart:2950:14)
I/flutter ( 5384): #10     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:12)
I/flutter ( 5384): #11     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4860:14)
I/flutter ( 5384): #12     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2950:14)
I/flutter ( 5384): #13     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:12)
I/flutter ( 5384): #14     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3732:16)
I/flutter ( 5384): #15     Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
I/flutter ( 5384): #16     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3701:5)
I/flutter ( 5384): #17     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3696:5)
I/flutter ( 5384): #18     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2950:14)
I/flutter ( 5384): #19     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:12)
I/flutter ( 5384): #20     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4860:14)
I/flutter ( 5384): #21     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2950:14)
I/flutter ( 5384): #22     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:12)
I/flutter ( 5384): #23     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4860:14)
I/flutter ( 5384): #24     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2950:14)
I/flutter ( 5384): #25     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:12)
I/flutter ( 5384): #26     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4860:14)
I/flutter ( 5384): #27     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2950:14)
I/flutter ( 5384): #28     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:12)
I/flutter ( 5384): #29     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4860:14)
I/flutter ( 5384): #30     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2950:14)
I/flutter ( 5384): #31     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:12)
I/flutter ( 5384): #32     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3732:16)
I/flutter ( 5384): #33     Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
I/flutter ( 5384): #34     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3701:5)
I/flutter ( 5384): #35     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3848:11)
I/flutter ( 5384): #36     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3696:5)
I/flutter ( 5384): #37     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2950:14)
I/flutter ( 5384): #38     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:12)
I/flutter ( 5384): #39     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3732:16)
I/flutter ( 5384): #40     Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
I/flutter ( 5384): #41     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3701:5)
I/flutter ( 5384): #42     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3696:5)
I/flutter ( 5384): #43     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2950:14)
I/flutter ( 5384): #44     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:12)
I/flutter ( 5384): #45     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3732:16)
I/flutter ( 5384): #46     Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
I/flutter ( 5384): #47     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3701:5)
I/flutter ( 5384): #48     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3848:11)
I/flutter ( 5384): #49     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3696:5)
I/flutter ( 5384): #50     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2950:14)
I/flutter ( 5384): #51     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:12)
I/flutter ( 5384): #52     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4860:14)
I/flutter ( 5384): #53     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2950:14)
I/flutter ( 5384): #54     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:12)
I/flutter ( 5384): #55     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3732:16)
I/flutter ( 5384): #56     Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
I/flutter ( 5384): #57     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3701:5)
I/flutter ( 5384): #58     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3696:5)
I/flutter ( 5384): #59     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2950:14)
I/flutter ( 5384): #60     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:12)
I/flutter ( 5384): #61     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4860:14)
I/flutter ( 5384): #62     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2950:14)
I/flutter ( 5384): #63     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:12)
I/flutter ( 5384): #64     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3732:16)
I/flutter ( 5384): #65     Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
I/flutter ( 5384): #66     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3701:5)
I/flutter ( 5384): #67     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3848:11)
I/flutter ( 5384): #68     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3696:5)
I/flutter ( 5384): #69     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2950:14)
I/flutter ( 5384): #70     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:12)
I/flutter ( 5384): #71     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3732:16)
I/flutter ( 5384): #72     Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
I/flutter ( 5384): #73     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3701:5)
I/flutter ( 5384): #74     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3696:5)
I/flutter ( 5384): #75     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2950:14)
I/flutter ( 5384): #76     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:12)
I/flutter ( 5384): #77     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4860:14)
I/flutter ( 5384): #78     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2950:14)
I/flutter ( 5384): #79     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:12)
I/flutter ( 5384): #80     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3732:16)
I/flutter ( 5384): #81     Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
I/flutter ( 5384): #82     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3701:5)
I/flutter ( 5384): #83     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3696:5)
I/flutter ( 5384): #84     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2950:14)
I/flutter ( 5384): #85     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:12)
I/flutter ( 5384): #86     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3732:16)
I/flutter ( 5384): #87     Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
I/flutter ( 5384): #88     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3701:5)
I/flutter ( 5384): #89     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3848:11)
I/flutter ( 5384): #90     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3696:5)
I/flutter ( 5384): #91     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2950:14)
I/flutter ( 5384): #92     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:12)
I/flutter ( 5384): #93     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3732:16)
I/flutter ( 5384): #94     Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
I/flutter ( 5384): #95     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3701:5)
I/flutter ( 5384): #96     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3848:11)
I/flutter ( 5384): #97     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3696:5)
I/flutter ( 5384): #98     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2950:14)
I/flutter ( 5384): #99     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:12)
I/flutter ( 5384): #100    RenderObjectElement.updateChildren (package:flutter/src/widgets/framework.dart:4643:32)
I/flutter ( 5384): #101    MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4975:17)
I/flutter ( 5384): #102    Element.updateChild (package:flutter/src/widgets/framework.dart:2742:15)
I/flutter ( 5384): #103    _TheatreElement.update (package:flutter/src/widgets/overlay.dart:507:16)
I/flutter ( 5384): #104    Element.updateChild (package:flutter/src/widgets/framework.dart:2742:15)
I/flutter ( 5384): #105    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3732:16)
I/flutter ( 5384): #106    Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
I/flutter ( 5384): #107    StatefulElement.update (package:flutter/src/widgets/framework.dart:3878:5)
I/flutter ( 5384): #108    Element.updateChild (package:flutter/src/widgets/framework.dart:2742:15)
I/flutter ( 5384): #109    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3732:16)
I/flutter ( 5384): #110    Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
I/flutter ( 5384): #111    ProxyElement.update (package:flutter/src/widgets/framework.dart:3990:5)
I/flutter ( 5384): #112    Element.updateChild (package:flutter/src/widgets/framework.dart:2742:15)
I/flutter ( 5384): #113    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4867:14)
I/flutter ( 5384): #114    Element.updateChild (package:flutter/src/widgets/framework.dart:2742:15)
I/flutter ( 5384): #115    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3732:16)
I/flutter ( 5384): #116    Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
I/flutter ( 5384): #117    StatefulElement.update (package:flutter/src/widgets/framework.dart:3878:5)
I/flutter ( 5384): #118    Element.updateChild (package:flutter/src/widgets/framework.dart:2742:15)
I/flutter ( 5384): #119    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4867:14)
I/flutter ( 5384): #120    Element.updateChild (package:flutter/src/widgets/framework.dart:2742:15)
I/flutter ( 5384): #121    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4867:14)
I/flutter ( 5384): #122    Element.updateChild (package:flutter/src/widgets/framework.dart:2742:15)
I/flutter ( 5384): #123    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3732:16)
I/flutter ( 5384): #124    Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
I/flutter ( 5384): #125    BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2286:33)
I/flutter ( 5384): #126    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding&WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:676:20)
I/flutter ( 5384): #127    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:219:5)
I/flutter ( 5384): #128    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:990:15)
I/flutter ( 5384): #129    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:930:9)
I/flutter ( 5384): #130    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:842:5)
I/flutter ( 5384): #131    _invoke (dart:ui/hooks.dart:154:13)
I/flutter ( 5384): #132    _drawFrame (dart:ui/hooks.dart:143:3)
```

**Comment by akash554** [comment]
do you get any solution?

**Comment by kroikie** [comment]
@Yogita75

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/1078. Any further collaboration will be done there.

**Comment by CM-Talha** [comment]
just add form key inside form()..
form(
key:form key (or any other key you defined)
)
