### ISSUE TITLE
ListView scroll up so TextField is above keyboard not working when TextField in PageView

### ISSUE THREAD

**Issue by JonasJW** [flutter/flutter#27734]
I have a ListView wich items contain a PageView (that scrolls vertical). The items of the PageView contain TextFields. When I select a TextField, the ListView won't scroll up, so the TextField is above the Keyboard. Instead I get a Exception. However, when I change my nested PageView to ListView (so I have a ListView which items have another ListView, that contains the TextFields), the scroll up feature works just fine. When I place the TextField outside the PageView it works as well. 

The Exception I get:
```
I/flutter (15228): ══╡ EXCEPTION CAUGHT BY SCHEDULER LIBRARY ╞═════════════════════════════════════════════════════════
I/flutter (15228): The following assertion was thrown during a scheduler callback:
I/flutter (15228): 'package:flutter/src/rendering/viewport.dart': Failed assertion: line 662 pos 12: 'child.parent ==
I/flutter (15228): this': is not true.
I/flutter (15228):
I/flutter (15228): Either the assertion indicates an error in the framework itself, or we should provide substantially
I/flutter (15228): more information in this error message to help you determine and fix the underlying cause.
I/flutter (15228): In either case, please report this assertion by filing a bug on GitHub:
I/flutter (15228):   https://github.com/flutter/flutter/issues/new?template=BUG.md
I/flutter (15228):
I/flutter (15228): When the exception was thrown, this was the stack:
I/flutter (15228): #2      RenderViewportBase.getOffsetToReveal (package:flutter/src/rendering/viewport.dart:662:12)
I/flutter (15228): #3      RenderViewportBase.showInViewport (package:flutter/src/rendering/viewport.dart:938:55)
I/flutter (15228): #4      RenderViewportBase.showOnScreen (package:flutter/src/rendering/viewport.dart:889:45)
I/flutter (15228): #5      RenderObject.showOnScreen (package:flutter/src/rendering/object.dart:2664:20)
I/flutter (15228): #6      RenderObject.showOnScreen (package:flutter/src/rendering/object.dart:2664:20)
I/flutter (15228): #7      RenderObject.showOnScreen (package:flutter/src/rendering/object.dart:2664:20)
I/flutter (15228): #8      RenderObject.showOnScreen (package:flutter/src/rendering/object.dart:2664:20)
I/flutter (15228): #9      RenderObject.showOnScreen (package:flutter/src/rendering/object.dart:2664:20)
I/flutter (15228): #10     RenderObject.showOnScreen (package:flutter/src/rendering/object.dart:2664:20)
I/flutter (15228): #11     RenderObject.showOnScreen (package:flutter/src/rendering/object.dart:2664:20)
I/flutter (15228): #12     RenderObject.showOnScreen (package:flutter/src/rendering/object.dart:2664:20)
I/flutter (15228): #13     RenderObject.showOnScreen (package:flutter/src/rendering/object.dart:2664:20)
I/flutter (15228): #14     RenderObject.showOnScreen (package:flutter/src/rendering/object.dart:2664:20)
I/flutter (15228): #15     RenderObject.showOnScreen (package:flutter/src/rendering/object.dart:2664:20)
I/flutter (15228): #16     RenderObject.showOnScreen (package:flutter/src/rendering/object.dart:2664:20)
I/flutter (15228): #17     RenderObject.showOnScreen (package:flutter/src/rendering/object.dart:2664:20)
I/flutter (15228): #18     RenderObject.showOnScreen (package:flutter/src/rendering/object.dart:2664:20)
I/flutter (15228): #19     RenderObject.showOnScreen (package:flutter/src/rendering/object.dart:2664:20)
I/flutter (15228): #20     RenderObject.showOnScreen (package:flutter/src/rendering/object.dart:2664:20)
I/flutter (15228): #21     RenderObject.showOnScreen (package:flutter/src/rendering/object.dart:2664:20)
I/flutter (15228): #22     RenderObject.showOnScreen (package:flutter/src/rendering/object.dart:2664:20)
I/flutter (15228): #23     RenderObject.showOnScreen (package:flutter/src/rendering/object.dart:2664:20)
I/flutter (15228): #24     RenderObject.showOnScreen (package:flutter/src/rendering/object.dart:2664:20)
I/flutter (15228): #25     RenderObject.showOnScreen (package:flutter/src/rendering/object.dart:2664:20)
I/flutter (15228): #26     RenderObject.showOnScreen (package:flutter/src/rendering/object.dart:2664:20)
I/flutter (15228): #27     RenderObject.showOnScreen (package:flutter/src/rendering/object.dart:2664:20)
I/flutter (15228): #28     RenderViewportBase.showOnScreen (package:flutter/src/rendering/viewport.dart:881:20)
I/flutter (15228): #29     RenderObject.showOnScreen (package:flutter/src/rendering/object.dart:2664:20)
I/flutter (15228): #30     RenderObject.showOnScreen (package:flutter/src/rendering/object.dart:2664:20)
I/flutter (15228): #31     RenderObject.showOnScreen (package:flutter/src/rendering/object.dart:2664:20)
I/flutter (15228): #32     RenderObject.showOnScreen (package:flutter/src/rendering/object.dart:2664:20)
I/flutter (15228): #33     RenderObject.showOnScreen (package:flutter/src/rendering/object.dart:2664:20)
I/flutter (15228): #34     RenderObject.showOnScreen (package:flutter/src/rendering/object.dart:2664:20)
I/flutter (15228): #35     RenderObject.showOnScreen (package:flutter/src/rendering/object.dart:2664:20)
I/flutter (15228): #36     RenderObject.showOnScreen (package:flutter/src/rendering/object.dart:2664:20)
I/flutter (15228): #37     RenderObject.showOnScreen (package:flutter/src/rendering/object.dart:2664:20)
I/flutter (15228): #38     RenderObject.showOnScreen (package:flutter/src/rendering/object.dart:2664:20)
I/flutter (15228): #39     RenderObject.showOnScreen (package:flutter/src/rendering/object.dart:2664:20)
I/flutter (15228): #40     RenderObject.showOnScreen (package:flutter/src/rendering/object.dart:2664:20)
I/flutter (15228): #41     RenderObject.showOnScreen (package:flutter/src/rendering/object.dart:2664:20)
I/flutter (15228): #42     RenderObject.showOnScreen (package:flutter/src/rendering/object.dart:2664:20)
I/flutter (15228): #43     RenderObject.showOnScreen (package:flutter/src/rendering/object.dart:2664:20)
I/flutter (15228): #44     RenderObject.showOnScreen (package:flutter/src/rendering/object.dart:2664:20)
I/flutter (15228): #45     RenderObject.showOnScreen (package:flutter/src/rendering/object.dart:2664:20)
I/flutter (15228): #46     RenderObject.showOnScreen (package:flutter/src/rendering/object.dart:2664:20)
I/flutter (15228): #47     RenderObject.showOnScreen (package:flutter/src/rendering/object.dart:2664:20)
I/flutter (15228): #48     RenderObject.showOnScreen (package:flutter/src/rendering/object.dart:2664:20)
I/flutter (15228): #49     RenderObject.showOnScreen (package:flutter/src/rendering/object.dart:2664:20)
I/flutter (15228): #50     RenderObject.showOnScreen (package:flutter/src/rendering/object.dart:2664:20)
I/flutter (15228): #51     RenderObject.showOnScreen (package:flutter/src/rendering/object.dart:2664:20)
I/flutter (15228): #52     RenderObject.showOnScreen (package:flutter/src/rendering/object.dart:2664:20)
I/flutter (15228): #53     EditableTextState._showCaretOnScreen.<anonymous closure> (package:flutter/src/widgets/editable_text.dart:793:54)
I/flutter (15228): #54     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:990:15)
I/flutter (15228): #55     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:938:9)
I/flutter (15228): #56     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:842:5)
I/flutter (15228): #57     _invoke (dart:ui/hooks.dart:154:13)
I/flutter (15228): #58     _drawFrame (dart:ui/hooks.dart:143:3)
I/flutter (15228): (elided 2 frames from class _AssertionError)
I/flutter (15228): ════════════════════════════════════════════════════════════════════════════════════════════════════
```

flutter doctor -v:

```
[✓] Flutter (Channel stable, v1.0.0, on Mac OS X 10.14 18A391, locale de-DE)
    • Flutter version 1.0.0 at /Users/jonas/flutter
    • Framework revision 5391447fae (2 months ago), 2018-11-29 19:41:26 -0800
    • Engine revision 7375a0f414
    • Dart version 2.1.0 (build 2.1.0-dev.9.4 f9ebf21297)

[!] Android toolchain - develop for Android devices (Android SDK 28.0.3)
    • Android SDK at /Users/jonas/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = /Users/jonas/Library/Android/sdk
    • Java binary at: /Library/Java/JavaVirtualMachines/jdk1.8.0_192.jdk/Contents/Home/bin/java
    • Java version Java(TM) SE Runtime Environment (build 1.8.0_192-b12)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses

[✓] iOS toolchain - develop for iOS devices (Xcode 10.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.0, Build version 10A255
    • ios-deploy 1.9.4
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 31.3.1
    • Dart plugin version 181.5656
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)

[!] Android Studio
    • Android Studio at /Applications/Android/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    ✗ Android Studio not found at /Applications/Android/Contents
    • Try updating or re-installing Android Studio.

[!] IntelliJ IDEA Community Edition (version 2018.1.2)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.io/intellij-setup/#installing-the-plugins

[✓] Connected device (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 8.1.0 (API 27) (emulator)

! Doctor found issues in 3 categories.
```

**Comment by zoechi** [comment]
Sounds like #20893 which should be fixed in `dev` channel.
https://github.com/flutter/flutter/issues/20893#issuecomment-452601099
