### ISSUE TITLE
FittedBox render exception: 'width > 0.0': is not true; which goes away with hot-reload

### ISSUE THREAD

**Issue by ztl8702** [flutter/flutter#27732]
## Overview

I have an `Image` inside a `FittedBox` inside a `ListView` inside a `Container`. 

When cold-starting the app, the FittedBox along with its content will fail to render with an exception refering to `'package:flutter/src/rendering/box.dart'`; 

_however when immediately hot reloading the app, it will then render normally_.

## Steps to Reproduce

1. The full codebase for reproducing the issue is available at: [repro.zip](https://github.com/flutter/flutter/files/2848078/repro.zip)
    Basically, it involves the following widget tree:
   ```dart
   Container(
            height: 140,
            child: ListView(
              shrinkWrap: true,
              scrollDirection: Axis.horizontal,
              children: <Widget>[
                Card(
                  margin: EdgeInsets.all(5.5),
                  child: ClipRRect(
                      borderRadius: BorderRadius.circular(8.0),
                      child: FittedBox(
                          child: Image.asset('assets/banner3.png'),
                          fit: BoxFit.cover)),
                  shape: RoundedRectangleBorder(
                      borderRadius: BorderRadius.circular(8.0)),
                  color: Colors.red,
                  elevation: 2,
                )
              ],
            ),
          ),
   ```
2. Unzip `repro.zip`, run `flutter packages get`, then start the app with `flutter run --verbose`, the app shows up but is not rendered properly. An exception message (detailed in the next section) is shown in the console.

    <img width="362" alt="screen shot" src="https://user-images.githubusercontent.com/2714446/52524034-45a9fa80-2cd3-11e9-9c80-8d6869c1c41f.png">

3. Now press `r` in the console to hot reload the app, then the `Image` renders properly:
    
   
   <img width="361" alt="screen shot" src="https://user-images.githubusercontent.com/2714446/52524038-59edf780-2cd3-11e9-94fd-b745caf8cf0f.png">

## Logs

The exception: 
```
[ +655 ms] I/flutter ( 3360): ══╡ EXCEPTION CAUGHT BY RENDERING LIBRARY ╞═════════════════════════════════════════════════════════
[  +11 ms] I/flutter ( 3360): The following assertion was thrown during performLayout():
[        ] I/flutter ( 3360): 'package:flutter/src/rendering/box.dart': Failed assertion: line 307 pos 12: 'width > 0.0': is not
[        ] I/flutter ( 3360): true.
[   +3 ms] I/flutter ( 3360): 
[        ] I/flutter ( 3360): Either the assertion indicates an error in the framework itself, or we should provide substantially
[        ] I/flutter ( 3360): more information in this error message to help you determine and fix the underlying cause.
[        ] I/flutter ( 3360): In either case, please report this assertion by filing a bug on GitHub:
[        ] I/flutter ( 3360):   https://github.com/flutter/flutter/issues/new?template=BUG.md
[        ] I/flutter ( 3360): 
[        ] I/flutter ( 3360): When the exception was thrown, this was the stack:
[  +21 ms] I/flutter ( 3360): #2      BoxConstraints.constrainSizeAndAttemptToPreserveAspectRatio (package:flutter/src/rendering/box.dart:307:12)
[        ] I/flutter ( 3360): #3      RenderFittedBox.performLayout (package:flutter/src/rendering/proxy_box.dart:2256:26)
[        ] I/flutter ( 3360): #4      RenderObject.layout (package:flutter/src/rendering/object.dart:1634:7)
[        ] I/flutter ( 3360): #5      _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104:13)
[        ] I/flutter ( 3360): #6      _RenderCustomClip.performLayout (package:flutter/src/rendering/proxy_box.dart:1188:11)
[        ] I/flutter ( 3360): #7      RenderObject.layout (package:flutter/src/rendering/object.dart:1634:7)
[        ] I/flutter ( 3360): #8      _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104:13)
[        ] I/flutter ( 3360): #9      RenderObject.layout (package:flutter/src/rendering/object.dart:1634:7)
[        ] I/flutter ( 3360): #10     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104:13)
[        ] I/flutter ( 3360): #11     RenderObject.layout (package:flutter/src/rendering/object.dart:1634:7)
[        ] I/flutter ( 3360): #12     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104:13)
[        ] I/flutter ( 3360): #13     _RenderCustomClip.performLayout (package:flutter/src/rendering/proxy_box.dart:1188:11)
[        ] I/flutter ( 3360): #14     RenderObject.layout (package:flutter/src/rendering/object.dart:1634:7)
[        ] I/flutter ( 3360): #15     RenderPadding.performLayout (package:flutter/src/rendering/shifted_box.dart:199:11)
[        ] I/flutter ( 3360): #16     RenderObject.layout (package:flutter/src/rendering/object.dart:1634:7)
[        ] I/flutter ( 3360): #17     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104:13)
[        ] I/flutter ( 3360): #18     RenderObject.layout (package:flutter/src/rendering/object.dart:1634:7)
[        ] I/flutter ( 3360): #19     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104:13)
[        ] I/flutter ( 3360): #20     RenderObject.layout (package:flutter/src/rendering/object.dart:1634:7)
[        ] I/flutter ( 3360): #21     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104:13)
[        ] I/flutter ( 3360): #22     RenderObject.layout (package:flutter/src/rendering/object.dart:1634:7)
[        ] I/flutter ( 3360): #23     RenderSliverList.performLayout (package:flutter/src/rendering/sliver_list.dart:164:27)
[        ] I/flutter ( 3360): #24     RenderObject.layout (package:flutter/src/rendering/object.dart:1634:7)
[        ] I/flutter ( 3360): #25     RenderSliverPadding.performLayout (package:flutter/src/rendering/sliver_padding.dart:182:11)
[        ] I/flutter ( 3360): #26     RenderObject.layout (package:flutter/src/rendering/object.dart:1634:7)
[        ] I/flutter ( 3360): #27     RenderViewportBase.layoutChildSequence (package:flutter/src/rendering/viewport.dart:405:13)
[        ] I/flutter ( 3360): #28     RenderShrinkWrappingViewport._attemptLayout (package:flutter/src/rendering/viewport.dart:1645:12)
[        ] I/flutter ( 3360): #29     RenderShrinkWrappingViewport.performLayout (package:flutter/src/rendering/viewport.dart:1608:20)
[        ] I/flutter ( 3360): #30     RenderObject.layout (package:flutter/src/rendering/object.dart:1634:7)
[        ] I/flutter ( 3360): #31     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104:13)
[        ] I/flutter ( 3360): #32     RenderObject.layout (package:flutter/src/rendering/object.dart:1634:7)
[        ] I/flutter ( 3360): #33     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104:13)
[        ] I/flutter ( 3360): #34     RenderObject.layout (package:flutter/src/rendering/object.dart:1634:7)
[        ] I/flutter ( 3360): #35     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104:13)
[        ] I/flutter ( 3360): #36     RenderObject.layout (package:flutter/src/rendering/object.dart:1634:7)
[        ] I/flutter ( 3360): #37     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104:13)
[        ] I/flutter ( 3360): #38     RenderObject.layout (package:flutter/src/rendering/object.dart:1634:7)
[        ] I/flutter ( 3360): #39     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104:13)
[        ] I/flutter ( 3360): #40     RenderObject.layout (package:flutter/src/rendering/object.dart:1634:7)
[        ] I/flutter ( 3360): #41     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104:13)
[        ] I/flutter ( 3360): #42     RenderObject.layout (package:flutter/src/rendering/object.dart:1634:7)
[        ] I/flutter ( 3360): #43     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104:13)
[        ] I/flutter ( 3360): #44     RenderObject.layout (package:flutter/src/rendering/object.dart:1634:7)
[        ] I/flutter ( 3360): #45     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104:13)
[        ] I/flutter ( 3360): #46     RenderObject.layout (package:flutter/src/rendering/object.dart:1634:7)
[        ] I/flutter ( 3360): #47     RenderConstrainedBox.performLayout (package:flutter/src/rendering/proxy_box.dart:258:13)
[        ] I/flutter ( 3360): #48     RenderObject.layout (package:flutter/src/rendering/object.dart:1634:7)
[        ] I/flutter ( 3360): #49     RenderFlex.performLayout (package:flutter/src/rendering/flex.dart:738:15)
[        ] I/flutter ( 3360): #50     RenderObject.layout (package:flutter/src/rendering/object.dart:1634:7)
[        ] I/flutter ( 3360): #51     MultiChildLayoutDelegate.layoutChild (package:flutter/src/rendering/custom_layout.dart:142:11)
[        ] I/flutter ( 3360): #52     _ScaffoldLayout.performLayout (package:flutter/src/material/scaffold.dart:339:7)
[        ] I/flutter ( 3360): #53     MultiChildLayoutDelegate._callPerformLayout (package:flutter/src/rendering/custom_layout.dart:212:7)
[        ] I/flutter ( 3360): #54     RenderCustomMultiChildLayoutBox.performLayout (package:flutter/src/rendering/custom_layout.dart:356:14)
[        ] I/flutter ( 3360): #55     RenderObject.layout (package:flutter/src/rendering/object.dart:1634:7)
[        ] I/flutter ( 3360): #56     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104:13)
[        ] I/flutter ( 3360): #57     RenderObject.layout (package:flutter/src/rendering/object.dart:1634:7)
[        ] I/flutter ( 3360): #58     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104:13)
[        ] I/flutter ( 3360): #59     _RenderCustomClip.performLayout (package:flutter/src/rendering/proxy_box.dart:1188:11)
[        ] I/flutter ( 3360): #60     RenderObject.layout (package:flutter/src/rendering/object.dart:1634:7)
[        ] I/flutter ( 3360): #61     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104:13)
[        ] I/flutter ( 3360): #62     RenderObject.layout (package:flutter/src/rendering/object.dart:1634:7)
[        ] I/flutter ( 3360): #63     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104:13)
[        ] I/flutter ( 3360): #64     RenderObject.layout (package:flutter/src/rendering/object.dart:1634:7)
[        ] I/flutter ( 3360): #65     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104:13)
[        ] I/flutter ( 3360): #66     RenderObject.layout (package:flutter/src/rendering/object.dart:1634:7)
[        ] I/flutter ( 3360): #67     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104:13)
[        ] I/flutter ( 3360): #68     RenderObject.layout (package:flutter/src/rendering/object.dart:1634:7)
[        ] I/flutter ( 3360): #69     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104:13)
[        ] I/flutter ( 3360): #70     RenderObject.layout (package:flutter/src/rendering/object.dart:1634:7)
[        ] I/flutter ( 3360): #71     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104:13)
[        ] I/flutter ( 3360): #72     RenderObject.layout (package:flutter/src/rendering/object.dart:1634:7)
[        ] I/flutter ( 3360): #73     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104:13)
[        ] I/flutter ( 3360): #74     RenderObject.layout (package:flutter/src/rendering/object.dart:1634:7)
[        ] I/flutter ( 3360): #75     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104:13)
[        ] I/flutter ( 3360): #76     RenderOffstage.performLayout (package:flutter/src/rendering/proxy_box.dart:2881:13)
[        ] I/flutter ( 3360): #77     RenderObject.layout (package:flutter/src/rendering/object.dart:1634:7)
[        ] I/flutter ( 3360): #78     RenderStack.performLayout (package:flutter/src/rendering/stack.dart:510:15)
[        ] I/flutter ( 3360): #79     RenderObject.layout (package:flutter/src/rendering/object.dart:1634:7)
[        ] I/flutter ( 3360): #80     __RenderTheatre&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104:13)
[        ] I/flutter ( 3360): #81     RenderObject.layout (package:flutter/src/rendering/object.dart:1634:7)
[        ] I/flutter ( 3360): #82     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104:13)
[        ] I/flutter ( 3360): #83     RenderObject.layout (package:flutter/src/rendering/object.dart:1634:7)
[        ] I/flutter ( 3360): #84     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104:13)
[        ] I/flutter ( 3360): #85     RenderObject.layout (package:flutter/src/rendering/object.dart:1634:7)
[        ] I/flutter ( 3360): #86     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104:13)
[        ] I/flutter ( 3360): #87     RenderObject.layout (package:flutter/src/rendering/object.dart:1634:7)
[        ] I/flutter ( 3360): #88     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104:13)
[        ] I/flutter ( 3360): #89     RenderObject.layout (package:flutter/src/rendering/object.dart:1634:7)
[        ] I/flutter ( 3360): #90     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104:13)
[        ] I/flutter ( 3360): #91     RenderObject.layout (package:flutter/src/rendering/object.dart:1634:7)
[        ] I/flutter ( 3360): #92     RenderView.performLayout (package:flutter/src/rendering/view.dart:147:13)
[        ] I/flutter ( 3360): #93     RenderObject._layoutWithoutResize (package:flutter/src/rendering/object.dart:1509:7)
[        ] I/flutter ( 3360): #94     PipelineOwner.flushLayout (package:flutter/src/rendering/object.dart:768:18)
[        ] I/flutter ( 3360): #95     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding.drawFrame (package:flutter/src/rendering/binding.dart:281:19)
[        ] I/flutter ( 3360): #96     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding&WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:677:13)
[        ] I/flutter ( 3360): #97     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:219:5)
[        ] I/flutter ( 3360): #98     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:990:15)
[        ] I/flutter ( 3360): #99     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:930:9)
[        ] I/flutter ( 3360): #100    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.scheduleWarmUpFrame.<anonymous closure> (package:flutter/src/scheduler/binding.dart:751:7)
[        ] I/flutter ( 3360): #102    _Timer._runTimers (dart:isolate/runtime/libtimer_impl.dart:382:19)
[        ] I/flutter ( 3360): #103    _Timer._handleMessage (dart:isolate/runtime/libtimer_impl.dart:416:5)
[        ] I/flutter ( 3360): #104    _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:171:12)
[        ] I/flutter ( 3360): (elided 3 frames from class _AssertionError and package dart:async)
[   +1 ms] I/flutter ( 3360): 
[        ] I/flutter ( 3360): The following RenderObject was being processed when the exception was fired:
[        ] I/flutter ( 3360):   RenderFittedBox#8e0ce relayoutBoundary=up11 NEEDS-LAYOUT NEEDS-PAINT
[        ] I/flutter ( 3360):   creator: FittedBox ← ClipRRect ← DefaultTextStyle ← AnimatedDefaultTextStyle ←
[        ] I/flutter ( 3360):   _InkFeatures-[GlobalKey#660d2 ink renderer] ← NotificationListener<LayoutChangedNotification> ←
[        ] I/flutter ( 3360):   CustomPaint ← _ShapeBorderPaint ← PhysicalShape ← _MaterialInterior ← Material ← Padding ← ⋯

```

The full output of `flutter run --verbose` is available at [logs.txt](https://github.com/flutter/flutter/files/2848048/logs.txt)

`flutter analyze`:
```
Analyzing repo...                                                
No issues found! (ran in 1.6s)
```

`flutter doctor -v`:
```
[✓] Flutter (Channel stable, v1.0.0, on Mac OS X 10.14.2 18C54, locale en-AU)
    • Flutter version 1.0.0 at /Users/ztl8702/flutter-sdk/flutter
    • Framework revision 5391447fae (2 months ago), 2018-11-29 19:41:26 -0800
    • Engine revision 7375a0f414
    • Dart version 2.1.0 (build 2.1.0-dev.9.4 f9ebf21297)

[✓] Android toolchain - develop for Android devices (Android SDK 28.0.3)
    • Android SDK at /Users/ztl8702/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)
    • All Android licenses accepted.

[✗] iOS toolchain - develop for iOS devices
    ✗ Xcode installation is incomplete; a full installation is necessary for iOS development.
      Download at: https://developer.apple.com/xcode/download/
      Or install Xcode via the App Store.
      Once installed, run:
        sudo xcode-select --switch /Applications/Xcode.app/Contents/Developer
    ✗ libimobiledevice and ideviceinstaller are not installed. To install with Brew, run:
        brew update
        brew install --HEAD usbmuxd
        brew link usbmuxd
        brew install --HEAD libimobiledevice
        brew install ideviceinstaller
    ✗ ios-deploy not installed. To install with Brew:
        brew install ios-deploy
    ✗ CocoaPods not installed.
        CocoaPods is used to retrieve the iOS platform side's plugin code that responds to your plugin usage
        on the Dart side.
        Without resolving iOS dependencies with CocoaPods, plugins will not work on iOS.
        For more info, see https://flutter.io/platform-plugins
      To install:
        brew install cocoapods
        pod setup

[✓] Android Studio (version 3.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)

[!] IntelliJ IDEA Ultimate Edition (version 2018.2.2)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.io/intellij-setup/#installing-the-plugins

[✓] VS Code (version 1.31.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 2.22.3

[✓] Connected device (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 9 (API 28) (emulator)

! Doctor found issues in 2 categories.
```

**Comment by ztl8702** [comment]
Possibly related: https://stackoverflow.com/questions/54340675/failed-assertion-width-0-0-is-not-true-when-placing-single-image-in-containe

**Comment by kangwang1988** [comment]
Please consider asking support questions in one of the other channels listed at http://flutter.io/support .

**Comment by ztl8702** [comment]
@kangwang1988 I thought this was possibly a bug in Flutter.  That's why I included a reproduction example.

**Comment by kangwang1988** [comment]
cc @zoechi

**Comment by zoechi** [comment]
Thanks for the reproduction!

With a cold start the image is not yet available when the view is built and the size of `Image.asset()` is 0x0. When you hot-reload the image is available and `Image.asset()` sized accordingly and therefore no exception. 

Passing a size also prevents the exception:

```dart
                          child: Image.asset('assets/banner3.png',
                              width: 100, height: 100),
```
So I think this is working as intended.

**Comment by ztl8702** [comment]
@zoechi Thanks for the clarification.

**Comment by twistedinferno** [comment]
I have a scenario where adding a width and a height is not possible.  Is there another way to get this error to go away the first time the component is loaded?  Is there a way to force the image asset to be available before the view is first built perhaps?  This is happening after a cold install but also after a hot restart of the app (I would have thought the assets would be available by then, no?)

**Comment by twistedinferno** [comment]
What I ended up doing was hardcoding all my images with a height and width taken from the file dimensions themselves (where they were inside a fittedBox).

I assume that the assets are retrieved from the assets directory only when they are required for performance reasons (ie, it would cause a lag at phone startup time if you had many images) but I think the dimensions only could be retrieved at compile time and stored against the image which could then be used for this processing.  I can do this manually I guess but it does seem to be a bit of a gotcha!

Let me know if I've misunderstood something though.  Thank you!

```
            Expanded(
              child: Column(
                children: [
                  FittedBox(
                    fit: BoxFit.scaleDown,
                    child: Image.asset("assets/foot.png", width: 134, height: 293,),
                  ),
                ],
              ),
            ),
```

**Comment by xyzbilal** [comment]
SizedBox.expand solved my problem..

```
Stack(children: [
                                    SizedBox.expand(
                                        child: Container(
                                       width: 50,
                                       height: 50,
                                            decoration: BoxDecoration(
                                                border: Border.all(
                                                    color: Colors.grey),
                                                borderRadius: BorderRadius.circular(3),
                                            child: FittedBox(child:Image.file(File(path)),fit: BoxFit.fill),
                                    InkWell(onLongPress: () {
                                     //do something
                                    }, onTap: () {
                                        //do something
                                    },)
                                  ])
```

**Comment by ravenblackx** [comment]
This seems like a bizarre constraint of FittedBox - what's wrong with a child of size 0 or size "no constraints yet"? It seems like a pretty common situation, especially while loading an image. I don't think anything would go *wrong* if the aspect ratio just had a special case for size 0 that said the aspect ratio is 1, to prevent the division by zero that probably caused the asserts to be added.

My team has been burned by this weird constraint twice.
