### ISSUE TITLE
Flutter not able to deploy to physical iOS device

### ISSUE THREAD

**Issue by gi097** [flutter/flutter#27759]
## Steps to Reproduce
- Create a Flutter application in either Visual Studio code or Android Studio;
- Uninstalled `python@2` from `brew`;
- Chosen signing certificate/provisioning profile in Xcode;
- Debug application;

## Logs
```
Launching lib/main.dart on iPhone van Giovanni in debug mode...
Automatically signing iOS for device deployment using specified development team in Xcode project: WP64VFXQNU
Xcode build done.                                           48,8s
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Applications/Xcode.app/Contents/SharedFrameworks/LLDB.framework/Resources/Python/lldb/__init__.py", line 98, in <module>
    import six
ImportError: No module named six
Traceback (most recent call last):
  File "<string>", line 1, in <module>
... KEEPS REPEATING...
NameError: name 'run_one_line' is not defined
error: python failed attempting to evaluate 'fruitstrap_device_app="/private/var/containers/Bundle/Application/38C118AA-81D5-40F7-A098-77710DA1BFDE/Runner.app"'
```
## Flutter doctor output
```
[✓] Flutter (Channel stable, v1.0.0, on Mac OS X 10.14.3 18D109, locale nl-NL)
    • Flutter version 1.0.0 at /Users/gi097/flutter
    • Framework revision 5391447fae (2 months ago), 2018-11-29 19:41:26 -0800
    • Engine revision 7375a0f414
    • Dart version 2.1.0 (build 2.1.0-dev.9.4 f9ebf21297)

[✓] Android toolchain - develop for Android devices (Android SDK 28.0.3)
    • Android SDK at /Users/gi097/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling
      support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_152-release-1248-b01)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.1, Build version 10B61
    • ios-deploy 1.9.4
    • CocoaPods version 1.6.0.beta.2

[✓] Android Studio (version 3.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 32.0.1
    • Dart plugin version 182.5215
    • Java version OpenJDK Runtime Environment (build
      1.8.0_152-release-1248-b01)

[✓] VS Code (version 1.31.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 2.22.3

[✓] Connected device (1 available)
    • iPhone van Giovanni • e7a87790b7e904499a0e1860fece7e7b10568aa2 • ios • iOS
      12.1.1
```

**Comment by jonahwilliams** [comment]
@gi097 have you tried any of the suggestions at https://stackoverflow.com/questions/13967428/importerror-no-module-named-six ?

**Comment by gi097** [comment]
@jonahwilliams, yes :) however this gives the following output. I think my `python` installation is quite messed up.
```
sudo easy_install pip
Traceback (most recent call last):
  File "/usr/bin/easy_install-2.7", line 7, in <module>
    from pkg_resources import load_entry_point
ImportError: No module named pkg_resources
m4m-macbook-003:~ gi097$ pip install --upgrade setuptools
-bash: pip: command not found
m4m-macbook-003:~ gi097$ sudo chown gi097 easy-install.pth
chown: easy-install.pth: No such file or directory
m4m-macbook-003:~ gi097$ yum install python-setuptools
-bash: yum: command not found
m4m-macbook-003:~ gi097$ easy_install six
Traceback (most recent call last):
  File "/usr/bin/easy_install-2.7", line 7, in <module>
    from pkg_resources import load_entry_point
ImportError: No module named pkg_resources
```

**Comment by gi097** [comment]
The problem was that I was using a corrupt version of `python` and `pip`. Fixed by uninstalling the `brew python@2` version, and running the following commands:

```bash
$ wget https://bootstrap.pypa.io/get-pip.py && sudo python get-pip.py
$ sudo pip install six
```
