### ISSUE TITLE
Stateless widgets list throws `Multiple widgets used the same GlobalKey` and `_inkFeature != null is not true`

### ISSUE THREAD

**Issue by vanlooverenkoen** [flutter/flutter#27750]
I'm having an issue where I go from 1 screen with a list to another create item screen. When I add an item I get this error `_inkFeature != null is not true` it only happens when an extra item is added to the list. Around the same time I get an error.
```
I/flutter (13800): Another exception was thrown: Multiple widgets used the same GlobalKey.
I/flutter (13800): Another exception was thrown: Duplicate GlobalKey detected in widget tree.
```

I'm not having stateful widgets only stateless widgets in the list. so no keys required I guess?

## Logs
```
I/flutter (13800): ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
I/flutter (13800): The following assertion was thrown building Overlay-[LabeledGlobalKey<OverlayState>#359c1](state:
I/flutter (13800): OverlayState#ef229(tickers: tracking 2 tickers, entries: [OverlayEntry#67dc4(opaque: false;
I/flutter (13800): maintainState: false), OverlayEntry#53872(opaque: false; maintainState: true)])):
I/flutter (13800): 'package:flutter/src/material/material.dart': Failed assertion: line 467 pos 12: '_inkFeatures !=
I/flutter (13800): null': is not true.
I/flutter (13800): 
I/flutter (13800): Either the assertion indicates an error in the framework itself, or we should provide substantially
I/flutter (13800): more information in this error message to help you determine and fix the underlying cause.
I/flutter (13800): In either case, please report this assertion by filing a bug on GitHub:
I/flutter (13800):   https://github.com/flutter/flutter/issues/new?template=BUG.md
I/flutter (13800): 
I/flutter (13800): When the exception was thrown, this was the stack:
I/flutter (13800): #2      _RenderInkFeatures._removeFeature (package:flutter/src/material/material.dart:467:12)
I/flutter (13800): #3      InkFeature.dispose (package:flutter/src/material/material.dart:560:17)
I/flutter (13800): #4      _TextFieldState.deactivate (package:flutter/src/material/text_field.dart:691:16)
I/flutter (13800): #5      StatefulElement.deactivate (package:flutter/src/widgets/framework.dart:3893:12)
I/flutter (13800): #6      _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:1727:13)
I/flutter (13800): #7      ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3755:14)
I/flutter (13800): #8      _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:1729:13)
I/flutter (13800): #9      ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3755:14)
I/flutter (13800): #10     _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:1729:13)
I/flutter (13800): #11     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3755:14)
I/flutter (13800): #12     _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:1729:13)
I/flutter (13800): #13     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3755:14)
I/flutter (13800): #14     _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:1729:13)
I/flutter (13800): #15     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3755:14)
I/flutter (13800): #16     _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:1729:13)
I/flutter (13800): #17     MultiChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:4948:16)
I/flutter (13800): #18     _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:1729:13)
I/flutter (13800): #19     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:4848:14)
I/flutter (13800): #20     _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:1729:13)
I/flutter (13800): #21     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:4848:14)
I/flutter (13800): #22     _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:1729:13)
I/flutter (13800): #23     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3755:14)
I/flutter (13800): #24     _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:1729:13)
I/flutter (13800): #25     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:4848:14)
I/flutter (13800): #26     _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:1729:13)
I/flutter (13800): #27     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:4848:14)
I/flutter (13800): #28     _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:1729:13)
I/flutter (13800): #29     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3755:14)
I/flutter (13800): #30     _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:1729:13)
I/flutter (13800): #31     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3755:14)
I/flutter (13800): #32     _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:1729:13)
I/flutter (13800): #33     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3755:14)
I/flutter (13800): #34     _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:1729:13)
I/flutter (13800): #35     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3755:14)
I/flutter (13800): #36     _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:1729:13)
I/flutter (13800): #37     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3755:14)
I/flutter (13800): #38     _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:1729:13)
I/flutter (13800): #39     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:4848:14)
I/flutter (13800): #40     _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:1729:13)
I/flutter (13800): #41     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3755:14)
I/flutter (13800): #42     _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:1729:13)
I/flutter (13800): #43     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:4848:14)
I/flutter (13800): #44     _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:1729:13)
I/flutter (13800): #45     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3755:14)
I/flutter (13800): #46     _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:1729:13)
I/flutter (13800): #47     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3755:14)
I/flutter (13800): #48     _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:1729:13)
I/flutter (13800): #49     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3755:14)
I/flutter (13800): #50     _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:1729:13)
I/flutter (13800): #51     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:4848:14)
I/flutter (13800): #52     _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:1729:13)
I/flutter (13800): #53     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:4848:14)
I/flutter (13800): #54     _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:1729:13)
I/flutter (13800): #55     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3755:14)
I/flutter (13800): #56     _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:1729:13)
I/flutter (13800): #57     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:4848:14)
I/flutter (13800): #58     _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:1729:13)
I/flutter (13800): #59     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3755:14)
I/flutter (13800): #60     _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:1729:13)
I/flutter (13800): #61     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3755:14)
I/flutter (13800): #62     _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:1729:13)
I/flutter (13800): #63     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:4848:14)
I/flutter (13800): #64     _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:1729:13)
I/flutter (13800): #65     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:4848:14)
I/flutter (13800): #66     _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:1729:13)
I/flutter (13800): #67     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3755:14)
I/flutter (13800): #68     _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:1729:13)
I/flutter (13800): #69     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3755:14)
I/flutter (13800): #70     _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:1729:13)
I/flutter (13800): #71     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3755:14)
I/flutter (13800): #72     _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:1729:13)
I/flutter (13800): #73     List.forEach (dart:core/runtime/libgrowable_array.dart:277:8)
I/flutter (13800): #74     SliverMultiBoxAdaptorElement.visitChildren (package:flutter/src/widgets/sliver.dart:1177:36)
I/flutter (13800): #75     _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:1729:13)
I/flutter (13800): #76     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3755:14)
I/flutter (13800): #77     _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:1729:13)
I/flutter (13800): #78     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:4848:14)
I/flutter (13800): #79     _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:1729:13)
I/flutter (13800): #80     MultiChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:4948:16)
I/flutter (13800): #81     _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:1729:13)
I/flutter (13800): #82     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:4848:14)
I/flutter (13800): #83     _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:1729:13)
I/flutter (13800): #84     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:4848:14)
I/flutter (13800): #85     _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:1729:13)
I/flutter (13800): #86     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:4848:14)
I/flutter (13800): #87     _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:1729:13)
I/flutter (13800): #88     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:4848:14)
I/flutter (13800): #89     _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:1729:13)
I/flutter (13800): #90     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3755:14)
I/flutter (13800): #91     _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:1729:13)
I/flutter (13800): #92     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3755:14)
I/flutter (13800): #93     _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:1729:13)
I/flutter (13800): #94     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:4848:14)
I/flutter (13800): #95     _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:1729:13)
I/flutter (13800): #96     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:4848:14)
I/flutter (13800): #97     _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:1729:13)
I/flutter (13800): #98     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:4848:14)
I/flutter (13800): #99     _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:1729:13)
I/flutter (13800): #100    SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:4848:14)
I/flutter (13800): #101    _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:1729:13)
I/flutter (13800): #102    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3755:14)
I/flutter (13800): #103    _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:1729:13)
I/flutter (13800): #104    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3755:14)
I/flutter (13800): #105    _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:1729:13)
I/flutter (13800): #106    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3755:14)
I/flutter (13800): #107    _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:1729:13)
I/flutter (13800): #108    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3755:14)
I/flutter (13800): #109    _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:1729:13)
I/flutter (13800): #110    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3755:14)
I/flutter (13800): #111    _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:1729:13)
I/flutter (13800): #112    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3755:14)
I/flutter (13800): #113    _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:1729:13)
I/flutter (13800): #114    MultiChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:4948:16)
I/flutter (13800): #115    _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:1729:13)
I/flutter (13800): #116    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3755:14)
I/flutter (13800): #117    _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:1729:13)
I/flutter (13800): #118    MultiChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:4948:16)
I/flutter (13800): #119    _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:1729:13)
I/flutter (13800): #120    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3755:14)
I/flutter (13800): #121    _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:1729:13)
I/flutter (13800): #122    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3755:14)
I/flutter (13800): #123    _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:1729:13)
I/flutter (13800): #124    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3755:14)
I/flutter (13800): #125    _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:1729:13)
I/flutter (13800): #126    MultiChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:4948:16)
I/flutter (13800): #127    _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:1729:13)
I/flutter (13800): #128    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3755:14)
I/flutter (13800): #129    _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:1729:13)
I/flutter (13800): #130    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3755:14)
I/flutter (13800): #131    _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:1729:13)
I/flutter (13800): #132    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3755:14)
I/flutter (13800): #133    _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:1729:13)
I/flutter (13800): #134    SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:4848:14)
I/flutter (13800): #135    _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:1729:13)
I/flutter (13800): #136    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3755:14)
I/flutter (13800): #137    _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:1729:13)
I/flutter (13800): #138    SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:4848:14)
I/flutter (13800): #139    _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:1729:13)
I/flutter (13800): #140    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3755:14)
I/flutter (13800): #141    _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:1729:13)
I/flutter (13800): #142    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3755:14)
I/flutter (13800): #143    _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:1729:13)
I/flutter (13800): #144    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3755:14)
I/flutter (13800): #145    _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:1729:13)
I/flutter (13800): #146    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3755:14)
I/flutter (13800): #147    _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:1729:13)
I/flutter (13800): #148    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3755:14)
I/flutter (13800): #149    _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:1729:13)
I/flutter (13800): #150    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3755:14)
I/flutter (13800): #151    _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:1729:13)
I/flutter (13800): #152    SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:4848:14)
I/flutter (13800): #153    _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:1729:13)
I/flutter (13800): #154    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3755:14)
I/flutter (13800): #155    _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:1729:13)
I/flutter (13800): #156    SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:4848:14)
I/flutter (13800): #157    _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:1729:13)
I/flutter (13800): #158    SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:4848:14)
I/flutter (13800): #159    _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:1729:13)
I/flutter (13800): #160    SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:4848:14)
I/flutter (13800): #161    _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:1729:13)
I/flutter (13800): #162    SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:4848:14)
I/flutter (13800): #163    _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:1729:13)
I/flutter (13800): #164    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3755:14)
I/flutter (13800): #165    _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:1729:13)
I/flutter (13800): #166    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3755:14)
I/flutter (13800): #167    _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:1729:13)
I/flutter (13800): #168    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3755:14)
I/flutter (13800): #169    _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:1729:13)
I/flutter (13800): #170    SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:4848:14)
I/flutter (13800): #171    _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:1729:13)
I/flutter (13800): #172    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3755:14)
I/flutter (13800): #173    _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:1729:13)
I/flutter (13800): #174    SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:4848:14)
I/flutter (13800): #175    _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:1729:13)
I/flutter (13800): #176    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3755:14)
I/flutter (13800): #177    _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:1729:13)
I/flutter (13800): #178    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3755:14)
I/flutter (13800): #179    _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:1729:13)
I/flutter (13800): #180    SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:4848:14)
I/flutter (13800): #181    _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:1729:13)
I/flutter (13800): #182    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3755:14)
I/flutter (13800): #183    _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:1729:13)
I/flutter (13800): #184    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3755:14)
I/flutter (13800): #185    _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:1729:13)
I/flutter (13800): #186    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3755:14)
I/flutter (13800): #187    _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:1729:13)
I/flutter (13800): #188    _InactiveElements.add (package:flutter/src/widgets/framework.dart:1738:7)
I/flutter (13800): #189    Element.deactivateChild (package:flutter/src/widgets/framework.dart:2986:29)
I/flutter (13800): #190    RenderObjectElement.updateChildren (package:flutter/src/widgets/framework.dart:4678:11)
I/flutter (13800): #191    MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4975:17)
I/flutter (13800): #192    Element.updateChild (package:flutter/src/widgets/framework.dart:2742:15)
I/flutter (13800): #193    _TheatreElement.update (package:flutter/src/widgets/overlay.dart:507:16)
I/flutter (13800): #194    Element.updateChild (package:flutter/src/widgets/framework.dart:2742:15)
I/flutter (13800): #195    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3732:16)
I/flutter (13800): #196    Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
I/flutter (13800): #197    BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2286:33)
I/flutter (13800): #198    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding&WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:691:20)
I/flutter (13800): #199    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:219:5)
I/flutter (13800): #200    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:990:15)
I/flutter (13800): #201    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:930:9)
I/flutter (13800): #202    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:842:5)
I/flutter (13800): #206    _invoke (dart:ui/hooks.dart:189:10)
I/flutter (13800): #207    _drawFrame (dart:ui/hooks.dart:162:3)
I/flutter (13800): (elided 5 frames from class _AssertionError and package dart:async)
I/flutter (13800): ════════════════════════════════════════════════════════════════════════════════════════════════════
```

**Comment by vanlooverenkoen** [comment]
Found out that is was still an issue on the create screen. Not the list screen.

I was using a NoSplashFactory as recommended here (#16336). This caused the inputfield to crash.

Related issues:
* #20874
* [#16336](https://github.com/flutter/flutter/pull/16336#issuecomment-398632720)
* [#16336](https://github.com/flutter/flutter/pull/16336#issuecomment-414580168)

Sollution:
It is related to an input field where we want to remove the splash (ripple) effect.
#20874
https://gist.github.com/HansMuller/721b827a6c0300e2d57e86a65f599377/revisions#diff-39859e34161f0cb6f5f50974282a2593

**Comment by vanlooverenkoen** [comment]
Duplicate of #20874

**Comment by vanlooverenkoen** [comment]
Duplicate of #20874

**Comment by patelkrunal78** [comment]
Very Similar To [Iterating through a list to render multiple widgets in Flutter?](https://icetutor.com/question/iterating-through-a-list-to-render-multiple-widgets-in-flutter)
