### ISSUE TITLE
NoSuchMethodError: The method 'split' was called on null.

### ISSUE THREAD

**Issue by trevburley** [flutter/flutter#27762]
IDE: Intellij IDEA Ultimate
Android Studio Version: 3.3.1 (SDK 26, 27, 28)
Flutter Version (Latest as of 11/02/2019)

Running Flutter Doctor after a flutter upgrade results in the following error:

```
Flutter crash report; please file at https://github.com/flutter/flutter/issues.

## command

flutter doctor

## exception

NoSuchMethodError: NoSuchMethodError: The method 'split' was called on null.
Receiver: null
Tried calling: split("=")

#0      Object.noSuchMethod (dart:core/runtime/libobject_patch.dart:50:5)
#1      new AndroidStudio.fromMacOSBundle (package:flutter_tools/src/android/android_studio.dart:57:85)
#2      AndroidStudio._allMacOS.<anonymous closure> (package:flutter_tools/src/android/android_studio.dart:200:67)
#3      MappedListIterable.elementAt (dart:_internal/iterable.dart:414:29)
#4      ListIterator.moveNext (dart:_internal/iterable.dart:343:26)
#5      WhereIterator.moveNext (dart:_internal/iterable.dart:438:22)
#6      new List.from (dart:core/runtime/libarray_patch.dart:45:19)
#7      Iterable.toList (dart:core/iterable.dart:398:16)
#8      AndroidStudio._allMacOS (package:flutter_tools/src/android/android_studio.dart:202:10)
#9      AndroidStudio.allInstalled (package:flutter_tools/src/android/android_studio.dart:157:26)
#10     AndroidStudioValidator.allValidators (package:flutter_tools/src/android/android_studio_validator.dart:21:55)
#11     _DefaultDoctorValidatorsProvider.validators (package:flutter_tools/src/doctor.dart:62:51)
#12     Doctor.validators (package:flutter_tools/src/doctor.dart:108:46)
#13     Doctor.startValidatorTasks (package:flutter_tools/src/doctor.dart:115:39)
#14     Doctor.diagnose (package:flutter_tools/src/doctor.dart:189:41)
<asynchronous suspension>
#15     DoctorCommand.runCommand (package:flutter_tools/src/commands/doctor.dart:48:39)
<asynchronous suspension>
#16     FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:551:18)
#17     _asyncThenWrapperHelper.<anonymous closure> (dart:async/runtime/libasync_patch.dart:77:64)
#18     _rootRunUnary (dart:async/zone.dart:1132:38)
#19     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#20     _FutureListener.handleValue (dart:async/future_impl.dart:126:18)
#21     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:639:45)
#22     Future._propagateToListeners (dart:async/future_impl.dart:668:32)
#23     Future._complete (dart:async/future_impl.dart:473:7)
#24     _SyncCompleter.complete (dart:async/future_impl.dart:51:12)
#25     _AsyncAwaitCompleter.complete.<anonymous closure> (dart:async/runtime/libasync_patch.dart:33:20)
#26     _rootRun (dart:async/zone.dart:1124:13)
#27     _CustomZone.run (dart:async/zone.dart:1021:19)
#28     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:947:23)
#29     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#30     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#31     _runPendingImmediateCallback (dart:isolate/runtime/libisolate_patch.dart:115:13)
#32     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:172:5)

## flutter doctor

encountered exception: NoSuchMethodError: The method 'split' was called on null.
Receiver: null
Tried calling: split("=")

#0      Object.noSuchMethod (dart:core/runtime/libobject_patch.dart:50:5)
#1      new AndroidStudio.fromMacOSBundle (package:flutter_tools/src/android/android_studio.dart:57:85)
#2      AndroidStudio._allMacOS.<anonymous closure> (package:flutter_tools/src/android/android_studio.dart:200:67)
#3      MappedListIterable.elementAt (dart:_internal/iterable.dart:414:29)
#4      ListIterator.moveNext (dart:_internal/iterable.dart:343:26)
#5      WhereIterator.moveNext (dart:_internal/iterable.dart:438:22)
#6      new List.from (dart:core/runtime/libarray_patch.dart:45:19)
#7      Iterable.toList (dart:core/iterable.dart:398:16)
#8      AndroidStudio._allMacOS (package:flutter_tools/src/android/android_studio.dart:202:10)
#9      AndroidStudio.allInstalled (package:flutter_tools/src/android/android_studio.dart:157:26)
#10     AndroidStudio.latestValid (package:flutter_tools/src/android/android_studio.dart:147:41)
#11     AppContext._generateIfNecessary.<anonymous closure> (package:flutter_tools/src/base/context.dart:99:41)
#12     __InternalLinkedHashMap&_HashVMBase&MapMixin&_LinkedHashMapMixin.putIfAbsent (dart:collection/runtime/libcompact_hash.dart:281:23)
#13     AppContext._generateIfNecessary (package:flutter_tools/src/base/context.dart:87:20)
#14     AppContext.[] (package:flutter_tools/src/base/context.dart:114:32)
#15     AppContext.[] (package:flutter_tools/src/base/context.dart:113:22)
#16     androidStudio (package:flutter_tools/src/android/android_studio.dart:16:43)
#17     javaPath (package:flutter_tools/src/android/android_studio.dart:32:24)
#18     AndroidSdk.findJavaBinary (package:flutter_tools/src/android/android_sdk.dart:493:24)
#19     AndroidLicenseValidator._checkJavaVersionNoOutput (package:flutter_tools/src/android/android_workflow.dart:207:42)
<asynchronous suspension>
#20     AndroidLicenseValidator.validate (package:flutter_tools/src/android/android_workflow.dart:182:17)
<asynchronous suspension>
#21     GroupedValidator.validate (package:flutter_tools/src/doctor.dart:318:52)
#22     _AsyncAwaitCompleter.start (dart:async/runtime/libasync_patch.dart:49:6)
#23     GroupedValidator.validate (package:flutter_tools/src/doctor.dart:315:36)
#24     Doctor.startValidatorTasks (package:flutter_tools/src/doctor.dart:116:52)
#25     Doctor.diagnose (package:flutter_tools/src/doctor.dart:189:41)
#26     _AsyncAwaitCompleter.start (dart:async/runtime/libasync_patch.dart:49:6)
#27     Doctor.diagnose (package:flutter_tools/src/doctor.dart:179:24)
#28     _doctorText.<anonymous closure> (package:flutter_tools/runner.dart:188:26)
#29     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:142:29)
#30     _AsyncAwaitCompleter.start (dart:async/runtime/libasync_patch.dart:49:6)
#31     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:142:7)
#32     _rootRun (dart:async/zone.dart:1124:13)
#33     _CustomZone.run (dart:async/zone.dart:1021:19)
#34     _runZoned (dart:async/zone.dart:1516:10)
#35     runZoned (dart:async/zone.dart:1463:12)
#36     AppContext.run (package:flutter_tools/src/base/context.dart:141:18)
#37     _AsyncAwaitCompleter.start (dart:async/runtime/libasync_patch.dart:49:6)
#38     AppContext.run (package:flutter_tools/src/base/context.dart:129:19)
#39     _doctorText (package:flutter_tools/runner.dart:187:19)
#40     _AsyncAwaitCompleter.start (dart:async/runtime/libasync_patch.dart:49:6)
#41     _doctorText (package:flutter_tools/runner.dart:183:27)
#42     _createLocalCrashReport (package:flutter_tools/runner.dart:165:32)
#43     _AsyncAwaitCompleter.start (dart:async/runtime/libasync_patch.dart:49:6)
#44     _createLocalCrashReport (package:flutter_tools/runner.dart:150:37)
#45     _handleToolError (package:flutter_tools/runner.dart:120:33)
#46     _asyncThenWrapperHelper.<anonymous closure> (dart:async/runtime/libasync_patch.dart:77:64)
#47     _rootRunUnary (dart:async/zone.dart:1132:38)
#48     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#49     _FutureListener.handleValue (dart:async/future_impl.dart:126:18)
#50     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:639:45)
#51     Future._propagateToListeners (dart:async/future_impl.dart:668:32)
#52     Future._complete (dart:async/future_impl.dart:473:7)
#53     _SyncCompleter.complete (dart:async/future_impl.dart:51:12)
#54     _AsyncAwaitCompleter.complete (dart:async/runtime/libasync_patch.dart:28:18)
#55     _completeOnAsyncReturn (dart:async/runtime/libasync_patch.dart:294:13)
#56     CrashReportSender.sendReport (package:flutter_tools/src/crash_reporting.dart)
#57     _asyncThenWrapperHelper.<anonymous closure> (dart:async/runtime/libasync_patch.dart:77:64)
#58     _rootRunUnary (dart:async/zone.dart:1132:38)
#59     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#60     _FutureListener.handleValue (dart:async/future_impl.dart:126:18)
#61     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:639:45)
#62     Future._propagateToListeners (dart:async/future_impl.dart:668:32)
#63     Future._complete (dart:async/future_impl.dart:473:7)
#64     Stream.fold.<anonymous closure> (dart:async/stream.dart:724:18)
#65     _rootRun (dart:async/zone.dart:1120:38)
#66     _CustomZone.run (dart:async/zone.dart:1021:19)
#67     _CustomZone.runGuarded (dart:async/zone.dart:923:7)
#68     _BufferingStreamSubscription._sendDone.sendDone (dart:async/stream_impl.dart:389:13)
#69     _BufferingStreamSubscription._sendDone (dart:async/stream_impl.dart:399:15)
#70     _BufferingStreamSubscription._close (dart:async/stream_impl.dart:283:7)
#71     _SinkTransformerStreamSubscription._close (dart:async/stream_transformers.dart:96:11)
#72     _EventSinkWrapper.close (dart:async/stream_transformers.dart:23:11)
#73     _StringAdapterSink.close (dart:convert/string_conversion.dart:251:11)
#74     _Utf8ConversionSink.close (dart:convert/string_conversion.dart:302:20)
#75     _ConverterStreamEventSink.close (dart:convert/chunked_conversion.dart:82:18)
#76     _SinkTransformerStreamSubscription._handleDone (dart:async/stream_transformers.dart:141:24)
#77     _rootRun (dart:async/zone.dart:1120:38)
#78     _CustomZone.run (dart:async/zone.dart:1021:19)
#79     _CustomZone.runGuarded (dart:async/zone.dart:923:7)
#80     _BufferingStreamSubscription._sendDone.sendDone (dart:async/stream_impl.dart:389:13)
#81     _BufferingStreamSubscription._sendDone (dart:async/stream_impl.dart:399:15)
#82     _BufferingStreamSubscription._close (dart:async/stream_impl.dart:283:7)
#83     _ForwardingStream._handleDone (dart:async/stream_pipe.dart:106:10)
#84     _ForwardingStreamSubscription._handleDone (dart:async/stream_pipe.dart:172:13)
#85     _rootRun (dart:async/zone.dart:1120:38)
#86     _CustomZone.run (dart:async/zone.dart:1021:19)
#87     _CustomZone.runGuarded (dart:async/zone.dart:923:7)
#88     _BufferingStreamSubscription._sendDone.sendDone (dart:async/stream_impl.dart:389:13)
#89     _BufferingStreamSubscription._sendDone (dart:async/stream_impl.dart:399:15)
#90     _BufferingStreamSubscription._close (dart:async/stream_impl.dart:283:7)
#91     _SinkTransformerStreamSubscription._close (dart:async/stream_transformers.dart:96:11)
#92     _EventSinkWrapper.close (dart:async/stream_transformers.dart:23:11)
#93     _ByteAdapterSink.close (dart:convert/byte_conversion.dart:62:11)
#94     _FilterSink.close (dart:io/data_transformer.dart:637:11)
#95     _ConverterStreamEventSink.close (dart:convert/chunked_conversion.dart:82:18)
#96     _SinkTransformerStreamSubscription._handleDone (dart:async/stream_transformers.dart:141:24)
#97     _rootRun (dart:async/zone.dart:1120:38)
#98     _CustomZone.run (dart:async/zone.dart:1021:19)
#99     _CustomZone.runGuarded (dart:async/zone.dart:923:7)
#100    _BufferingStreamSubscription._sendDone.sendDone (dart:async/stream_impl.dart:389:13)
#101    _BufferingStreamSubscription._sendDone (dart:async/stream_impl.dart:399:15)
#102    _BufferingStreamSubscription._close (dart:async/stream_impl.dart:283:7)
#103    _ForwardingStream._handleDone (dart:async/stream_pipe.dart:106:10)
#104    _ForwardingStreamSubscription._handleDone (dart:async/stream_pipe.dart:172:13)
#105    _rootRun (dart:async/zone.dart:1120:38)
#106    _CustomZone.run (dart:async/zone.dart:1021:19)
#107    _CustomZone.runGuarded (dart:async/zone.dart:923:7)
#108    _BufferingStreamSubscription._sendDone.sendDone (dart:async/stream_impl.dart:389:13)
#109    _BufferingStreamSubscription._sendDone (dart:async/stream_impl.dart:399:15)
#110    _BufferingStreamSubscription._close (dart:async/stream_impl.dart:283:7)
#111    _SyncStreamController._sendDone (dart:async/stream_controller.dart:772:19)
#112    _StreamController._closeUnchecked (dart:async/stream_controller.dart:629:7)
#113    _StreamController.close (dart:async/stream_controller.dart:622:5)
#114    _HttpParser._closeIncoming (dart:_http/http_parser.dart:1037:23)
#115    _HttpParser._doParse (dart:_http/http_parser.dart:752:11)
#116    _HttpParser._parse (dart:_http/http_parser.dart:318:7)
#117    _HttpParser._onData (dart:_http/http_parser.dart:810:5)
#118    _rootRunUnary (dart:async/zone.dart:1132:38)
#119    _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#120    _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
#121    _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#122    _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#123    _SyncStreamController._sendData (dart:async/stream_controller.dart:764:19)
#124    _StreamController._add (dart:async/stream_controller.dart:640:7)
#125    _StreamController.add (dart:async/stream_controller.dart:586:5)
#126    _Socket._onData (dart:io/runtime/binsocket_patch.dart:1774:41)
#127    _rootRunUnary (dart:async/zone.dart:1132:38)
#128    _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#129    _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
#130    _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#131    _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#132    _SyncStreamController._sendData (dart:async/stream_controller.dart:764:19)
#133    _StreamController._add (dart:async/stream_controller.dart:640:7)
#134    _StreamController.add (dart:async/stream_controller.dart:586:5)
#135    _RawSecureSocket._sendReadEvent (dart:io/secure_socket.dart:1004:19)
#136    _rootRun (dart:async/zone.dart:1120:38)
#137    _CustomZone.run (dart:async/zone.dart:1021:19)
#138    _CustomZone.runGuarded (dart:async/zone.dart:923:7)
#139    _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:963:23)
#140    _rootRun (dart:async/zone.dart:1124:13)
#141    _CustomZone.run (dart:async/zone.dart:1021:19)
#142    _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:947:23)
#143    Timer._createTimer.<anonymous closure> (dart:async/runtime/libtimer_patch.dart:21:15)
#144    _Timer._runTimers (dart:isolate/runtime/libtimer_impl.dart:382:19)
#145    _Timer._handleMessage (dart:isolate/runtime/libtimer_impl.dart:416:5)
#146    _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:171:12)

```

**Comment by zoechi** [comment]
Please run these commands to ensure the Flutter installation is in a correct state
https://github.com/flutter/flutter/wiki/Workarounds-for-common-issues#flutter-installation-corrupted

**Comment by trevburley** [comment]
Thanks, running the below commands in the flutter SDK directory results in identical output to my original post

```
git clean -xfd
git stash save --keep-index
git stash drop
git pull
flutter doctor
```

**Comment by zoechi** [comment]
Tentatively added `TODAY`. I can not reproduce though.

**Comment by zoechi** [comment]
@trevburley what OS are you using and what Flutter channel?

**Comment by trevburley** [comment]
OSX Mojave (10.14.2) and the channel is master - I could try stable but I moved to master a while ago to avoid a bug which may now be fixed?

**Comment by kangwang1988** [comment]
@trevburley 
Maybe a duple of: https://github.com/flutter/flutter/issues/27670 ?

**Comment by trevburley** [comment]
> @trevburley
> Maybe a duple of: #27670 ?
> There is an known bug: #27670 and a fix at: #27687
> 
> Are you using JetBrainsToolbox?

That'll be the one - I'll try the fix and see if that does the trick - will respond here shortly

**Comment by kangwang1988** [comment]
@trevburley 
I'm closing this issue as it's a duple.
Let's track it over: https://github.com/flutter/flutter/issues/27670
As a workaround now, you can use directly installed Android Studio instead of by JetBrainsToolbox.
Thanks for your feedback.

**Comment by tvolkert** [comment]
@kangwang1988 this issue was labeled as "TODAY", which means it blocks releases. Should #27670 now be labeled as "TODAY"?
