### ISSUE TITLE
Flutter Crashed after installing URL launcher report ID: c79a4b4c45e8e99e

### ISSUE THREAD

**Issue by solanm3** [flutter/flutter#27779]
```
Oops; flutter has exited unexpectedly.
Crash report sent (report ID: c79a4b4c45e8e99e)
Crash report written to C:\src\nfc_tickettapper\flutter_06.log;
please let us know at https://github.com/flutter/flutter/issues.
Process finished with exit code 1
```
I removed everything for the URL launcher and it restarted Android Studio and it's still not working

**Comment by zoechi** [comment]
Please add the output of `flutter doctor -v`
and the content of C:\src\nfc_tickettapper\flutter_06.log;

**Comment by solanm3** [comment]
Flutter crash report; please file at https://github.com/flutter/flutter/issues.

## command

flutter --no-color packages get

## exception

FileSystemException: FileSystemException: Deletion failed, path = 'C:\src\nfc_tickettapper\.android' (OS Error: The process cannot access the file because it is being used by another process.
, errno = 32)

```
#0      _Directory._deleteSync (dart:io/directory_impl.dart:207:7)
#1      FileSystemEntity.deleteSync (dart:io/file_system_entity.dart:466:47)
#2      ForwardingFileSystemEntity.deleteSync (package:file/src/forwarding/forwarding_file_system_entity.dart:72:16)
#3      _deleteIfExistsSync (package:flutter_tools/src/project.dart:439:15)
#4      AndroidProject._regenerateLibrary (package:flutter_tools/src/project.dart:416:5)
#5      AndroidProject.ensureReadyForPlatformSpecificTooling (package:flutter_tools/src/project.dart:380:7)
<asynchronous suspension>
#6      FlutterProject.ensureReadyForPlatformSpecificTooling (package:flutter_tools/src/project.dart:140:19)
<asynchronous suspension>
#7      PackagesGetCommand.runCommand (package:flutter_tools/src/commands/packages.dart:84:23)
<asynchronous suspension>
#8      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:401:18)
#9      _asyncThenWrapperHelper.<anonymous closure> (dart:async/runtime/libasync_patch.dart:77:64)
#10     _rootRunUnary (dart:async/zone.dart:1132:38)
#11     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#12     _FutureListener.handleValue (dart:async/future_impl.dart:129:18)
#13     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:642:45)
#14     Future._propagateToListeners (dart:async/future_impl.dart:671:32)
#15     Future._complete (dart:async/future_impl.dart:476:7)
#16     _SyncCompleter.complete (dart:async/future_impl.dart:51:12)
#17     _AsyncAwaitCompleter.complete.<anonymous closure> (dart:async/runtime/libasync_patch.dart:33:20)
#18     _rootRun (dart:async/zone.dart:1124:13)
#19     _CustomZone.run (dart:async/zone.dart:1021:19)
#20     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:947:23)
#21     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#22     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#23     _runPendingImmediateCallback (dart:isolate/runtime/libisolate_patch.dart:115:13)
#24     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:172:5)
```

## flutter doctor

```
[✓] Flutter (Channel stable, v1.0.0, on Microsoft Windows [Version 10.0.17134.523], locale en-GB)
    • Flutter version 1.0.0 at C:\src\flutter_windows_v1.0.0-stable\flutter
    • Framework revision 5391447fae (2 months ago), 2018-11-29 19:41:26 -0800
    • Engine revision 7375a0f414
    • Dart version 2.1.0 (build 2.1.0-dev.9.4 f9ebf21297)

[✓] Android toolchain - develop for Android devices (Android SDK 28.0.3)
    • Android SDK at C:\Users\Michael\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)
    • All Android licenses accepted.

[✓] Android Studio (version 3.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 32.0.1
    • Dart plugin version 182.5215
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)

[✓] IntelliJ IDEA Community Edition (version 2018.1)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2018.1.4
    • Flutter plugin version 31.3.1
    • Dart plugin version 181.5656

[✓] Connected device (1 available)
    • Mi MIX 2S • 1cbc8b98 • android-arm64 • Android 9 (API 28)

• No issues found!
```

**Comment by zoechi** [comment]
> OS Error: The process cannot access the file

Have you tried restarting the machine
and checked that no antivirus accesses/locks this file?

**Comment by solanm3** [comment]
Restarting it worked, thanks!
