### ISSUE TITLE
flutter even at 1.0, can't detect android SDK automatically

### ISSUE THREAD

**Issue by sivang** [flutter/flutter#27843]
1. Install a brand new Kubuntu 18.10
2. Install Flutter
3. Follow Android Studio installation
4. enable KVM (not relevant but part of steps)
5. run flutter doctor

```
sivan@titan:~/Flutter$ flutter -v doctor
[✓] Flutter (Channel stable, v1.0.0, on Linux, locale en_IL)
    • Flutter version 1.0.0 at /home/sivan/Flutter/flutter
    • Framework revision 5391447fae (3 months ago), 2018-11-29 19:41:26 -0800
    • Engine revision 7375a0f414
    • Dart version 2.1.0 (build 2.1.0-dev.9.4 f9ebf21297)

[✗] Android toolchain - develop for Android devices
    ✗ ANDROID_HOME = /home/sivan/Android/Sdk
      but Android SDK not found at this location.

[✓] Android Studio (version 3.3)
    • Android Studio at /home/sivan/Flutter/studio/android-studio
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)

[✓] VS Code (version 1.31.0)
    • VS Code at /usr/share/code
    • Flutter extension version 2.22.3

[!] Connected device
    ! No devices available

! Doctor found issues in 2 categories.
````
```
sivan@titan:~/Flutter/studio/android-studio$ echo $PATH 
/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/home/sivan/bin:/home/sivan/VueJS/jots/node_modules/.bin:/home/sivan/AWSTutotrials/amplify/node_modules/@aws-amplify/cli/bin:/home/sivan/Flutter/flutter/bin

sivan@titan:~/Android/Sdk$ ls -lah
total 52K
drwxrwxr-x 12 sivan sivan 4.0K Feb 12 17:18 .
drwxrwxr-x  3 sivan sivan 4.0K Feb 12 17:13 ..
drwxrwxr-x  3 sivan sivan 4.0K Feb 12 17:16 build-tools
drwxrwxr-x  7 sivan sivan 4.0K Feb 12 17:15 emulator
drwxrwxr-x  4 sivan sivan 4.0K Feb 12 17:16 extras
-rw-rw-r--  1 sivan sivan   16 Feb 12 17:20 .knownPackages
drwxrwxr-x  3 sivan sivan 4.0K Feb 12 17:15 patcher
drwxrwxr-x  3 sivan sivan 4.0K Feb 12 17:16 platforms
drwxrwxr-x  5 sivan sivan 4.0K Feb 12 17:15 platform-tools
drwxrwxr-x 24 sivan sivan 4.0K Feb 12 17:17 skins
drwxrwxr-x  3 sivan sivan 4.0K Feb 12 17:15 sources
drwxrwxr-x  3 sivan sivan 4.0K Feb 12 17:18 system-images
drwxrwxr-x  6 sivan sivan 4.0K Feb 12 17:15 tools
```

**Comment by zoechi** [comment]
Is `ANDROID_HOME` or `ANDROID_SDK_HOME` set?
https://developer.android.com/studio/command-line/variables

**Comment by sivang** [comment]
from what I pasted at the issue report:
```
[✗] Android toolchain - develop for Android devices
    ✗ ANDROID_HOME = /home/sivan/Android/Sdk
      but Android SDK not found at this location.
```

**Comment by zoechi** [comment]
What does `sdkmanager --version` print?

**Comment by sivang** [comment]
'''
sivan@titan:~$ Android/Sdk/tools/bin/sdkmanager --version
26.1.1
'''

**Comment by zoechi** [comment]
https://github.com/flutter/flutter/issues/19805#issuecomment-407990430 might help

**Comment by sivang** [comment]
thanks, only req'd to add the platform-tools path. Is this an Android Studio bug not adding the path statements to the .bashrc file?

**Comment by zoechi** [comment]
@sivang sorry, I don't know.

**Comment by zoechi** [comment]
I leave the issue open for `flutter doctor` to improve the error output.

**Comment by sivang** [comment]
But if this is fixed at the studio installer level, then we wouldn't have to deal with that, or maybe AS doesn't do that as it 'knows' where it installed the SDK , as per options/jdk.table.xml ?

Happy to contribute PR if it's not too involved..

**Comment by zoechi** [comment]
@sivang there are so many ways to install these components which makes any assumption unreliable. Ideally `flutter doctor` would check and print helpful messages.

**Comment by sivang** [comment]
+1, I emailed -dev to see if I can get some guidance to either fix the messages or make it smarter. Thanks for your help!

**Comment by christopherfujino** [comment]
I'm consolidating this issue with https://github.com/flutter/flutter/issues/18593. Please follow there for discussion & updates.

**Comment by thaifani** [comment]
Launching lib\main.dart on SM G935R4 in debug mode...
Running Gradle task 'assembleDebug'...
Exception in thread "main" java.net.UnknownHostException: downloads.gradle-dn.com
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:184)
	at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:172)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:666)
	at sun.security.ssl.BaseSSLSocketImpl.connect(BaseSSLSocketImpl.java:173)
	at sun.net.NetworkClient.doConnect(NetworkClient.java:180)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:463)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:558)
	at sun.net.www.protocol.https.HttpsClient.<init>(HttpsClient.java:264)
	at sun.net.www.protocol.https.HttpsClient.New(HttpsClient.java:367)
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(AbstractDelegateHttpsURLConnection.java:191)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1156)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1050)
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:177)
	at sun.net.www.protocol.http.HttpURLConnection.followRedirect0(HttpURLConnection.java:2729)
	at sun.net.www.protocol.http.HttpURLConnection.followRedirect(HttpURLConnection.java:2641)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1824)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1492)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:263)
	at org.gradle.wrapper.Download.downloadInternal(Download.java:58)
	at org.gradle.wrapper.Download.download(Download.java:44)
	at org.gradle.wrapper.Install$1.call(Install.java:61)
	at org.gradle.wrapper.Install$1.call(Install.java:48)
	at org.gradle.wrapper.ExclusiveFileAccessManager.access(ExclusiveFileAccessManager.java:65)
	at org.gradle.wrapper.Install.createDist(Install.java:48)
	at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:128)
	at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:61)
Finished with error: Gradle task assembleDebug failed with exit code 1
