### ISSUE TITLE
Cloud Firestore transaction error

### ISSUE THREAD

**Issue by baeharam** [flutter/flutter#27840]
I'm implementing random chat program with cloud firestore, but transaction function is not working.

```dart
Future<void> setRandomUser() async {
    CollectionReference col = sl.get<FirebaseAPI>().firestore.collection(firestoreRandomChatCollection);
    DocumentReference doc = col.document(sl.get<CurrentUser>().uid);
    Random random = Random();
    int randomValue = random.nextInt(pow(2,32));

    await sl.get<FirebaseAPI>().firestore.runTransaction((transaction) async{
      await transaction.update(doc, {
        firestoreRandom: randomValue,
        uidCol: sl.get<CurrentUser>().uid
      });
    });
  }
```

Error message

```
E/AndroidRuntime(12573): java.lang.RuntimeException: An error occurred while executing doInBackground()
E/AndroidRuntime(12573): 	at android.os.AsyncTask$3.done(AsyncTask.java:353)
E/AndroidRuntime(12573): 	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383)
E/AndroidRuntime(12573): 	at java.util.concurrent.FutureTask.setException(FutureTask.java:252)
E/AndroidRuntime(12573): 	at java.util.concurrent.FutureTask.run(FutureTask.java:271)
E/AndroidRuntime(12573): 	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:245)
E/AndroidRuntime(12573): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
E/AndroidRuntime(12573): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
E/AndroidRuntime(12573): 	at java.lang.Thread.run(Thread.java:764)
E/AndroidRuntime(12573): Caused by: java.lang.IllegalArgumentException: Provided document reference is from a different Firestore instance.
E/AndroidRuntime(12573): 	at com.google.firebase.firestore.FirebaseFirestore.zza(com.google.firebase:firebase-firestore@@17.1.1:384)
E/AndroidRuntime(12573): 	at com.google.firebase.firestore.Transaction.zza(com.google.firebase:firebase-firestore@@17.1.1:203)
E/AndroidRuntime(12573): 	at com.google.firebase.firestore.Transaction.update(com.google.firebase:firebase-firestore@@17.1.1:145)
E/AndroidRuntime(12573): 	at io.flutter.plugins.firebase.cloudfirestore.CloudFirestorePlugin$5.doInBackground(CloudFirestorePlugin.java:360)
E/AndroidRuntime(12573): 	at io.flutter.plugins.firebase.cloudfirestore.CloudFirestorePlugin$5.doInBackground(CloudFirestorePlugin.java:354)
E/AndroidRuntime(12573): 	at android.os.AsyncTask$2.call(AsyncTask.java:333)
E/AndroidRuntime(12573): 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
E/AndroidRuntime(12573): 	... 4 more
```

Flutter doctor

```
[√] Flutter (Channel beta, v1.1.8, on Microsoft Windows [Version 10.0.17134.523], locale ko-KR)
    • Flutter version 1.1.8 at C:\flutter
    • Framework revision 985ccb6d14 (5 weeks ago), 2019-01-08 13:45:55 -0800
    • Engine revision 7112b72cc2
    • Dart version 2.1.1 (build 2.1.1-dev.0.1 ec86471ccc)

[!] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at C:\AndroidSDK
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = C:\AndroidSDK
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses

[√] Android Studio (version 3.2)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 31.3.1
    • Dart plugin version 181.5656
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)

[!] IntelliJ IDEA Community Edition (version 2018.2)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2018.2
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.io/intellij-setup/#installing-the-plugins

[√] VS Code, 64-bit edition (version 1.30.2)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Flutter extension version 2.22.3

[√] Connected device (1 available)
    • SM G955N • ce0617162b7a010d01 • android-arm64 • Android 8.0.0 (API 26)
```

**Comment by zoechi** [comment]
Looks like this is because of `sl.get<FirebaseAPI>()`

**Comment by zoechi** [comment]
Looks like this is because `sl.get<FirebaseAPI>()` returns a different instance every time, but it's unclear because the source is not included.

Please consider asking support questions in one of the other channels listed at http://flutter.io/support .

**Comment by baeharam** [comment]
@zeochi

I used `getIt` package, so it always returns same instance.

```
GetIt sl = GetIt();

void setup() {
  .....
  sl.registerLazySingleton<FirebaseAPI>(() => FirebaseAPI());
  ....
}
```
I think it is the problem of cloud firestore transaction, how do you think?

**Comment by zoechi** [comment]
Doesn't look like that to me, even though firebase transactions are known to have some issues.

The code you posted doesn't provide more insight because all it does is forward to other code that you did not post.

**Comment by baeharam** [comment]
I reproduced simple example without any customized codes but It occurs same error.

```
Future<void> setRandomUser() async {
    CollectionReference col = sl.get<FirebaseAPI>().firestore.collection('test');
    DocumentReference doc = col.document('test');

    await sl.get<FirebaseAPI>().firestore.runTransaction((transaction) async{
      DocumentSnapshot snapshot = await transaction.get(doc);
      if(snapshot.exists){
        await transaction.update(snapshot.reference, {
          'test': 'test'
        });
      }
    });
  }
```
I searched google and found [SO](https://stackoverflow.com/questions/50280256/flutter-cloud-firestore-plugin-transactions-on-android) question. I think this problem is unsolved, right?

**Comment by zoechi** [comment]
I think the error comes from `sl.get<FirebaseAPI>()` which is completely opaque because you didn't post any related code.

**Comment by baeharam** [comment]
Its just simple code...

import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:firebase_auth/firebase_auth.dart';
import 'package:privacy_of_animal/resources/strings.dart';


```
class FirebaseAPI {
  FirebaseAuth auth = FirebaseAuth.instance;
  Firestore firestore = Firestore.instance;

  Future<String> get user async {
    String result = await auth.currentUser().then((user) => user.uid).catchError((error)=>error);
    return result;
  }

  Future<void> deleteUserAccount(String uid) async {
    CollectionReference col = firestore.collection(firestoreDeletedUserListCollection);
    DocumentReference doc = col.document(uid);
    await firestore.runTransaction((tx) async{
      await doc.delete();
    });
  }
}
```

**Comment by zoechi** [comment]
> Its just simple code... 

only when it's available to look at it ;-)

**Comment by baeharam** [comment]
> > Its just simple code...
> 
> only when it's available to look at it ;-)

Sorry, need more code on this?

**Comment by zoechi** [comment]
I haven't used Firestore myself yet but I think the issue is that 

```dart
    await firestore.runTransaction((tx) async{
      await doc.delete();
    });
```

should be something like

```dart
    await firestore.runTransaction((tx) async{
      await tx.delete(); // use `tx` here instead of `doc`
    });
```

I assume that your real code looks different, because there is no point in wrapping such a single atomic action with a transaction (mentioned just to be sure).

**Comment by baeharam** [comment]
Firstly, I used ur suggestion, but it didn't work so I used my solution. Then, I think it is related to #17663 Isn't it?

**Comment by zoechi** [comment]
> but it didn't work

What does that mean exactly?

See also https://github.com/flutter/flutter/issues/14655#issuecomment-440540922

There is also https://stackoverflow.com/questions/50280256/flutter-cloud-firestore-plugin-transactions-on-android

Perhaps trying like explained in https://pub.dartlang.org/packages/cloud_firestore is worth a try where you in the transaction read the item again and then use `delete` (instead of `update` used in the example)

**Comment by baeharam** [comment]
When I run transaction, it abruptly terminate app.

**Comment by baeharam** [comment]
It was related to configuration of firebase, solved

**Comment by Saifallak** [comment]
@baeharam how did you solve it ?

**Comment by baeharam** [comment]
> @baeharam how did you solve it ?

Check ur firebase configuration

**Comment by Saifallak** [comment]
Check what exactly?!

**Comment by baeharam** [comment]
Like this
```
  Future<void> appInitialize() async {
    await FirebaseApp.configure(
      name: 'PrivacyofAnimal',
      options: const FirebaseOptions(
        googleAppID: androidAppID,
        apiKey: appAPIKey,
        projectID: projectID
      )
    );
    await Firestore.instance.settings(timestampsInSnapshotsEnabled: true);
  }
```

**Comment by pojoba02** [comment]
@baeharam how did you resolved your issue cos am also facing the same problem with firestore

**Comment by thevzurd** [comment]
I had the same problem. Try this. Hope it Helps 
[FIrestore Transaction Handler](https://github.com/thevzurd/Firestore-Transaction-Handler)

**Comment by kroikie** [comment]
@baeharam

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/449. Any further collaboration will be done there.
