### ISSUE TITLE
Android - SystemNavigator.pop() doesn't seem to quit the app like a Swipe Up on the Recent App List

### ISSUE THREAD

**Issue by sjmcdowall** [flutter/flutter#27856]
## Problem Statement

I have noticed 2 things when trying to end my app on Android using `SystemNavigation.pop()` in `flutter run` debug mode.. 

a.  In the output window, unlike when you swipe up -- there is no "Application Ended." message and connection is not lost to whatever magic thing is running for debug stuff.  When you swipe up you do get the message and "flutter run" quits.

b.  About 50% of the time, on the next innovation of  "flutter run" we see an exception thrown (see logs) about Keystore errors.  This doesn't seem to affect the running of the app (?) but it's a bit nerve wracking... 

## Steps to Reproduce

1. From a `WillPopScope _onWillPop` .. call `SystemNavigator.pop()` to end the app.
2. do a "flutter run -d" on an Android emulator device (I don't have a physical device) 
3. Hit the Back-button (or whatever to invoke the `SystemNavigator.pop()` .. 

Notice that in the debug window the flutter run is still running and no "Application Finished" message is presented.

## Logs

```
Using hardware rendering with device Android SDK built for x86. If you get graphics artifacts, consider enabling software rendering with "--enable-software-rendering".
Launching lib/main_staging1.dart on Android SDK built for x86 in debug mode...
Initializing gradle...                                       0.9s
Resolving dependencies...                                    1.9s
Gradle task 'assembleDebug'...
Gradle task 'assembleDebug'... Done                          8.1s
Built build/app/outputs/apk/debug/app-debug.apk.
Installing build/app/outputs/apk/app.apk...                  2.7s
W/KeyStore(24576): KeyStore exception
W/KeyStore(24576): android.os.ServiceSpecificException:  (code 7)
W/KeyStore(24576):      at android.os.Parcel.createException(Parcel.java:1956)
W/KeyStore(24576):      at android.os.Parcel.readException(Parcel.java:1910)
W/KeyStore(24576):      at android.os.Parcel.readException(Parcel.java:1860)
W/KeyStore(24576):      at android.security.IKeystoreService$Stub$Proxy.get(IKeystoreService.java:786)
W/KeyStore(24576):      at android.security.KeyStore.get(KeyStore.java:195)
W/KeyStore(24576):      at android.security.keystore.AndroidKeyStoreSpi.engineGetCertificateChain(AndroidKeyStoreSpi.java:118)
W/KeyStore(24576):      at java.security.KeyStoreSpi.engineGetEntry(KeyStoreSpi.java:484)
W/KeyStore(24576):      at java.security.KeyStore.getEntry(KeyStore.java:1560)
W/KeyStore(24576):      at com.it_nomads.fluttersecurestorage.ciphers.RSACipher18Implementation.createRSAKeysIfNeeded(RSACipher18Implementation.java:111)
W/KeyStore(24576):      at com.it_nomads.fluttersecurestorage.ciphers.RSACipher18Implementation.<init>(RSACipher18Implementation.java:31)
W/KeyStore(24576):      at com.it_nomads.fluttersecurestorage.ciphers.StorageCipher18Implementation.<init>(StorageCipher18Implementation.java:31)
W/KeyStore(24576):      at com.it_nomads.fluttersecurestorage.FlutterSecureStoragePlugin.<init>(FlutterSecureStoragePlugin.java:46)
W/KeyStore(24576):      at com.it_nomads.fluttersecurestorage.FlutterSecureStoragePlugin.registerWith(FlutterSecureStoragePlugin.java:33)
W/KeyStore(24576):      at io.flutter.plugins.GeneratedPluginRegistrant.registerWith(GeneratedPluginRegistrant.java:25)
W/KeyStore(24576):      at com.missionmode.mobile.MainActivity.onCreate(MainActivity.java:11)
W/KeyStore(24576):      at android.app.Activity.performCreate(Activity.java:7136)
W/KeyStore(24576):      at android.app.Activity.performCreate(Activity.java:7127)
W/KeyStore(24576):      at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1271)
W/KeyStore(24576):      at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2893)
W/KeyStore(24576):      at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3048)
W/KeyStore(24576):      at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
W/KeyStore(24576):      at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
W/KeyStore(24576):      at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
W/KeyStore(24576):      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1808)
W/KeyStore(24576):      at android.os.Handler.dispatchMessage(Handler.java:106)
W/KeyStore(24576):      at android.os.Looper.loop(Looper.java:193)
W/KeyStore(24576):      at android.app.ActivityThread.main(ActivityThread.java:6669)
W/KeyStore(24576):      at java.lang.reflect.Method.invoke(Native Method)
W/KeyStore(24576):      at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
W/KeyStore(24576):      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
Syncing files to device Android SDK built for x86...
I/OpenGLRenderer(24576): Initialized EGL, version 1.4
D/OpenGLRenderer(24576): Swap behavior 1

...

🔥  To hot reload changes while running, press "r". To hot restart (and rebuild state), press "R".
An Observatory debugger and profiler on Android SDK built for x86 is available at: http://127.0.0.1:53545/
For a more detailed help message, press "h". To detach, press "d"; to quit, press "q".
D/EGL_emulation(25163): eglMakeCurrent: 0xe2e42e00: ver 3 0 (tinfo 0xe2e5f360)
D/EGL_emulation(25163): eglMakeCurrent: 0xe2e42e00: ver 3 0 (tinfo 0xe2e5f360)
I/flutter (25163): FINE: 2019-02-12 14:23:29.853633: WelcomeScreen - [_buildBiometricOption] - return from _tryBio with true
I/flutter (25163): FINE: 2019-02-12 14:23:29.865786: _MainScaffoldState - initState()
I/flutter (25163): FINE: 2019-02-12 14:23:29.866554: _MainScaffoldState - [initState()] - starting tab is 0
I/flutter (25163): FINE: 2019-02-12 14:23:29.867390: NotificationService - [registerDeviceToken()] - calling backend  with memberId 297946
I/flutter (25163): FINE: 2019-02-12 14:23:29.869935: _MainScaffoldState - [build()]
I/flutter (25163): FINE: 2019-02-12 14:23:29.939004: AlertListScreen - [didChangeDependencies()]
I/flutter (25163): FINE: 2019-02-12 14:23:29.940023: AlertListScreen - [_getAlerts()
I/flutter (25163): FINE: 2019-02-12 14:23:29.942472: AlertListScreen - [build()]
I/flutter (25163): FINE: 2019-02-12 14:23:30.003376: WelcomeScreen - [_buildBiometricOption] - useBio is true and hasStoredLogin is true and hasStoredAPI is false
I/flutter (25163): FINE: 2019-02-12 14:23:30.030352: NotificationService - [registerDeviceToken()] - invoking backend for 297946 with deviceToken [3e85152c-4b9d-44c8-9c78-6996f8cbc266] and state of [true]
I/flutter (25163): FINER: 2019-02-12 14:23:30.031372: MobileService - pushNotificationToken - sending to https://staging1.missionmode.com/cgi-bin/WebObjects/MobileServer.woa/wa/registerDevice
I/flutter (25163): FINE: 2019-02-12 14:23:30.155220: WelcomeScreen - [dispose()
I/flutter (25163): FINE: 2019-02-12 14:23:30.260951: MobileService - status code from call is 200
I/flutter (25163): FINE: 2019-02-12 14:23:30.261296: NotificationService - [registerDeviceToken()] - result from sendToken is 200
I/flutter (25163): FINE: 2019-02-12 14:23:30.262267: _MainScaffoldState - [initState()] - registerDeviceToken returned true
I/flutter (25163): FINE: 2019-02-12 14:23:33.582044: _MainScaffoldState - [_canExitApp]
I/flutter (25163): FINER: 2019-02-12 14:23:35.095762: _MainScaffoldState - [_canExitApp] - Exit confirmed.. see ya!

```

```
Analyzing mobile...

   info • Prefer const with constant constructors • lib/screens/utilities/show_image.dart:56:32 • prefer_const_constructors
   info • Prefer const with constant constructors • lib/screens/utilities/show_image.dart:67:21 • prefer_const_constructors

2 issues found. (ran in 15.1s)
```

```
[✓] Flutter (Channel beta, v1.1.8, on Mac OS X 10.14.3 18D42, locale en)
    • Flutter version 1.1.8 at /Users/sjm/Development/flutter
    • Framework revision 985ccb6d14 (5 weeks ago), 2019-01-08 13:45:55 -0800
    • Engine revision 7112b72cc2
    • Dart version 2.1.1 (build 2.1.1-dev.0.1 ec86471ccc)

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/sjm/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.1, Build version 10B61
    • ios-deploy 1.9.4
    • CocoaPods version 1.6.0

[✓] Android Studio (version 3.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 31.3.1
    • Dart plugin version 181.5656
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)

[✓] IntelliJ IDEA Ultimate Edition (version 2018.1.3)
    • IntelliJ at /Users/sjm/Applications/JetBrains Toolbox/IntelliJ IDEA Ultimate.app
    • Flutter plugin version 29.1.1
    • Dart plugin version 181.4892.1

[✓] VS Code (version 1.30.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 2.22.3

[✓] Connected device (3 available)
    • Android SDK built for x86 • emulator-5554                            • android-x86 • Android 9 (API 28) (emulator)
    • SJM iPad Pro              • 026945135686a30604aca9996a8fc8df3554b726 • ios         • iOS 12.1.4
    • iPhone XR                 • 4491738F-0E7C-4813-B6CA-4733F89678CB     • ios         • iOS 12.1 (simulator)

• No issues found!
```

**Comment by jt100xu** [comment]
SystemNavigator.pop() do finish() the Activity. And in Android, finish() will not actually kill the application process, but swipe up from Recent Apps does.

**Comment by sjmcdowall** [comment]
@jt100xu -- Ok, fair enough but what is the EXPECTED behavior.  I would think, as an app engineer, that the application would end and we'd see the "Application Quit" message as this is the preferred way to "exit" the application as per the docs.   Everyone says do not use "exit(0)" but if one does, the application does quit. 

And of course -- the keystone exception is a bit disconcerting -- but maybe it's not a big deal but still -- seems like there must be some problem in the start up logic on some condition (yes, that's vague) if it can throw that exception .. Although I suspect it's only in Debug (and maybe only in a simulator) .

**Comment by tvolkert** [comment]
This is working as intended inasmuch as there's no way for apps to gracefully quit themselves - a `System.exit(0)` in Java or an `exit(0)` in Dart will look like an app crash.

@sjmcdowall is there a good place in the docs you think such a clarification would be best added?
