### ISSUE TITLE
Flutter crash when start "flutter run"

### ISSUE THREAD

**Issue by MadaiA** [flutter/flutter#27863]
## command

flutter --no-color run --machine --track-widget-creation --device-id=d47adab8 lib/main.dart

## exception

FileSystemException: FileSystemException: Cannot open file, path = '[/path...../].flutter-plugins' (OS Error: Permission denied, errno = 13)

```
#0      _File.throwIfError (dart:io/file_impl.dart:647:7)
#1      _File.openSync (dart:io/file_impl.dart:491:5)
#2      _File.writeAsBytesSync (dart:io/file_impl.dart:616:31)
#3      _File.writeAsStringSync (dart:io/file_impl.dart:640:5)
#4      _LocalFile&LocalFileSystemEntity&ForwardingFile.writeAsStringSync (package:file/src/forwarding/forwarding_file.dart:147:16)
#5      _writeFlutterPluginsList (package:flutter_tools/src/plugins.dart:99:17)
#6      refreshPluginsList (package:flutter_tools/src/plugins.dart:288:24)
#7      FlutterProject.ensureReadyForPlatformSpecificTooling (package:flutter_tools/src/project.dart:139:5)
<asynchronous suspension>
#8      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:389:21)
<asynchronous suspension>
#9      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:335:33)
<asynchronous suspension>
#10     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:142:29)
<asynchronous suspension>
#11     _rootRun (dart:async/zone.dart:1124:13)
#12     _CustomZone.run (dart:async/zone.dart:1021:19)
#13     _runZoned (dart:async/zone.dart:1516:10)
#14     runZoned (dart:async/zone.dart:1463:12)
#15     AppContext.run (package:flutter_tools/src/base/context.dart:141:18)
<asynchronous suspension>
#16     FlutterCommand.run (package:flutter_tools/src/runner/flutter_command.dart:326:20)
#17     CommandRunner.runCommand (package:args/command_runner.dart:196:27)
<asynchronous suspension>
#18     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:401:21)
<asynchronous suspension>
#19     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:142:29)
<asynchronous suspension>
#20     _rootRun (dart:async/zone.dart:1124:13)
#21     _CustomZone.run (dart:async/zone.dart:1021:19)
#22     _runZoned (dart:async/zone.dart:1516:10)
#23     runZoned (dart:async/zone.dart:1463:12)
#24     AppContext.run (package:flutter_tools/src/base/context.dart:141:18)
<asynchronous suspension>
#25     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:361:19)
<asynchronous suspension>
#26     CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:111:29)
#27     new Future.sync (dart:async/future.dart:224:31)
#28     CommandRunner.run (package:args/command_runner.dart:111:11)
#29     FlutterCommandRunner.run (package:flutter_tools/src/runner/flutter_command_runner.dart:241:18)
#30     run.<anonymous closure> (package:flutter_tools/runner.dart:60:20)
<asynchronous suspension>
#31     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:142:29)
<asynchronous suspension>
#32     _rootRun (dart:async/zone.dart:1124:13)
#33     _CustomZone.run (dart:async/zone.dart:1021:19)
#34     _runZoned (dart:async/zone.dart:1516:10)
#35     runZoned (dart:async/zone.dart:1463:12)
#36     AppContext.run (package:flutter_tools/src/base/context.dart:141:18)
<asynchronous suspension>
#37     runInContext (package:flutter_tools/src/context_runner.dart:43:24)
<asynchronous suspension>
#38     run (package:flutter_tools/runner.dart:51:10)
#39     main (package:flutter_tools/executable.dart:51:9)
<asynchronous suspension>
#40     main (file:///b/build/slave/Linux_Flutter_Packaging/build/archive/flutter/packages/flutter_tools/bin/flutter_tools.dart:8:3)
#41     _startIsolate.<anonymous closure> (dart:isolate/runtime/libisolate_patch.dart:287:32)
#42     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:171:12)
```

## flutter doctor

```
[✓] Flutter (Channel stable, v1.0.0, on Linux, locale C)
    • Flutter version 1.0.0 at /opt/flutter
    • Framework revision 5391447fae (3 months ago), 2018-11-29 19:41:26 -0800
    • Engine revision 7375a0f414
    • Dart version 2.1.0 (build 2.1.0-dev.9.4 f9ebf21297)

[✓] Android toolchain - develop for Android devices (Android SDK 28.0.3)
    • Android SDK at /home/user/Android/Sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /opt/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)
    • All Android licenses accepted.

[✓] Android Studio (version 3.2)
    • Android Studio at /opt/android-studio
    • Flutter plugin version 31.3.1
    • Dart plugin version 181.5656
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)

[✓] Connected device (1 available)
    • OS105 • d47adab8 • android-arm64 • Android 7.1.1 (API 25)

• No issues found!
```

**Comment by zoechi** [comment]
> `Cannot open file, path = '[/path...../].flutter-plugins'`

There seems to be the most relevant information missing?
What directory is it pointing to? You can of course remove information like the name of the user directory or similar but there is no information left in this path.

**Comment by MadaiA** [comment]
@zoechi The information [/path..../] is correct. I only hide the original path..

**Comment by MadaiA** [comment]
I found the problem. 
The dependencies: local_auth: ^0.4.0+1 [https://pub.dartlang.org/packages/local_auth#-versions-tab-](url) causes flutter crash. Y downgrade the dependency to ^0.4.0 and now , the project works!
