### ISSUE TITLE
error if tap on left edge of page with TargetPlatform.iOS

### ISSUE THREAD

**Issue by pepegich** [flutter/flutter#27874]
![feb-13-2019 12-35-28](https://user-images.githubusercontent.com/11444783/52698138-4de08f00-2f8c-11e9-8f41-954cdea09bf9.gif)

## example code
```dart
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        platform: TargetPlatform.iOS,
        primarySwatch: Colors.blue,
      ),
      home: MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key key, this.title}) : super(key: key);
  final String title;

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: () {
          var route = MaterialPageRoute(
              builder: (BuildContext context) {
                return MyHomePage(title: 'second',);
              });

          Navigator.push(context, route);
        },
        child: Icon(Icons.add),
      ),
    );
  }
}

```

## Steps to Reproduce

1) run example code:
2) tap floating button
3) tap on left edge

## Exception
```
I/flutter (16359): ══╡ EXCEPTION CAUGHT BY GESTURE ╞═══════════════════════════════════════════════════════════════════
I/flutter (16359): The following assertion was thrown while handling a gesture:
I/flutter (16359): 'package:flutter/src/cupertino/route.dart': Failed assertion: line 637 pos 12:
I/flutter (16359): 'controller.isAnimating': is not true.
I/flutter (16359): 
I/flutter (16359): Either the assertion indicates an error in the framework itself, or we should provide substantially
I/flutter (16359): more information in this error message to help you determine and fix the underlying cause.
I/flutter (16359): In either case, please report this assertion by filing a bug on GitHub:
I/flutter (16359):   https://github.com/flutter/flutter/issues/new?template=BUG.md
I/flutter (16359): 
I/flutter (16359): When the exception was thrown, this was the stack:
I/flutter (16359): #2      _CupertinoBackGestureController.dragEnd (package:flutter/src/cupertino/route.dart:637:12)
I/flutter (16359): #3      _CupertinoBackGestureDetectorState._handleDragEnd (package:flutter/src/cupertino/route.dart:507:28)
I/flutter (16359): #4      DragGestureRecognizer.didStopTrackingLastPointer.<anonymous closure> (package:flutter/src/gestures/monodrag.dart:262:45)
I/flutter (16359): #5      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:120:24)
I/flutter (16359): #6      DragGestureRecognizer.didStopTrackingLastPointer (package:flutter/src/gestures/monodrag.dart:262:9)
I/flutter (16359): #7      OneSequenceGestureRecognizer.stopTrackingPointer (package:flutter/src/gestures/recognizer.dart:249:9)
I/flutter (16359): #8      OneSequenceGestureRecognizer.stopTrackingIfPointerNoLongerDown (package:flutter/src/gestures/recognizer.dart:258:7)
I/flutter (16359): #9      DragGestureRecognizer.handleEvent (package:flutter/src/gestures/monodrag.dart:193:5)
I/flutter (16359): #10     PointerRouter._dispatch (package:flutter/src/gestures/pointer_router.dart:73:12)
I/flutter (16359): #11     PointerRouter.route (package:flutter/src/gestures/pointer_router.dart:101:11)
I/flutter (16359): #12     _WidgetsFlutterBinding&BindingBase&GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:214:19)
I/flutter (16359): #13     _WidgetsFlutterBinding&BindingBase&GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:192:22)
I/flutter (16359): #14     _WidgetsFlutterBinding&BindingBase&GestureBinding._handlePointerEvent (package:flutter/src/gestures/binding.dart:149:7)
I/flutter (16359): #15     _WidgetsFlutterBinding&BindingBase&GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:101:7)
I/flutter (16359): #16     _WidgetsFlutterBinding&BindingBase&GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:85:7)
I/flutter (16359): #20     _invoke1 (dart:ui/hooks.dart:223:10)
I/flutter (16359): #21     _dispatchPointerDataPacket (dart:ui/hooks.dart:144:5)
I/flutter (16359): (elided 5 frames from class _AssertionError and package dart:async)
I/flutter (16359): 
I/flutter (16359): Handler: onEnd
I/flutter (16359): Recognizer:
I/flutter (16359):   HorizontalDragGestureRecognizer#5b68e(debugOwner:
I/flutter (16359):   _CupertinoBackGestureDetectorState<dynamic>#bb6c2, start behavior: down)
I/flutter (16359): ════════════════════════════════════════════════════════════════════════════════════════════════════
```

## Doctor
```
[✓] Flutter (Channel dev, v1.2.0, on Mac OS X 10.14 18A391, locale ru-RU)
    • Flutter version 1.2.0 at /Users/ik/Repositories/flutter
    • Framework revision 06b979c4d5 (3 weeks ago), 2019-01-25 14:27:35 -0500
    • Engine revision 36acd02c94
    • Dart version 2.1.1 (build 2.1.1-dev.3.2 f4afaee422)

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/ik/Library/Android/sdk
    • Android NDK at /Users/ik/Library/Android/sdk/ndk-bundle
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_152-release-1024-b01)
    • All Android licenses accepted.

[!] iOS toolchain - develop for iOS devices (Xcode 10.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.1, Build version 10B61
    ✗ Verify that all connected devices have been paired with this computer in
      Xcode.
      If all devices have been paired, libimobiledevice and ideviceinstaller may
      require updating.
      To update with Brew, run:
        brew update
        brew uninstall --ignore-dependencies libimobiledevice
        brew uninstall --ignore-dependencies usbmuxd
        brew install --HEAD usbmuxd
        brew unlink usbmuxd
        brew link usbmuxd
        brew install --HEAD libimobiledevice
        brew install ideviceinstaller
    • ios-deploy 1.9.4
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 28.0.1
    • Dart plugin version 173.4700
    • Java version OpenJDK Runtime Environment (build
      1.8.0_152-release-1024-b01)

[✓] IntelliJ IDEA Community Edition (version 2018.3.4)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 32.0.3
    • Dart plugin version 183.5429.25

[✓] Connected device (1 available)
    • iPhone 6 • 29DE068D-47AA-4EE7-9CE2-5E8BD1BC0052 • ios • iOS 12.1
      (simulator)
```

**Comment by zoechi** [comment]
The most essential part from the beginning of the error log seems to be missing.
Can you please add it?

**Comment by pepegich** [comment]
seems similar https://github.com/flutter/flutter/issues/27333
it is fixed on master
