### ISSUE TITLE
when run flutter doctor, it always crashes

### ISSUE THREAD

**Issue by mark420524** [flutter/flutter#27927]
version: flutter-1.2.0.zip 

flutter doctor

## exception
```
VersionCheckError: VersionCheckError: Command exited with code 128: git log -n 1 --pretty=format:%ad --date=iso
Standard error: fatal: bad default revision 'HEAD'
```

```
#0      _runSync (package:flutter_tools/src/version.dart:506:5)
#1      FlutterVersion._latestGitCommitDate (package:flutter_tools/src/version.dart:130:12)
#2      FlutterVersion.frameworkCommitDate (package:flutter_tools/src/version.dart:121:37)
#3      FlutterVersion.frameworkDate (package:flutter_tools/src/version.dart:83:31)
#4      _FlutterValidator.validate (package:flutter_tools/src/doctor.dart:452:127)
<asynchronous suspension>
#5      Doctor.startValidatorTasks (package:flutter_tools/src/doctor.dart:116:52)
#6      Doctor.diagnose (package:flutter_tools/src/doctor.dart:189:41)
<asynchronous suspension>
#7      DoctorCommand.runCommand (package:flutter_tools/src/commands/doctor.dart:48:39)
<asynchronous suspension>
#8      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:551:18)
#9      _asyncThenWrapperHelper.<anonymous closure> (dart:async/runtime/libasync_patch.dart:77:64)
#10     _rootRunUnary (dart:async/zone.dart:1132:38)
#11     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#12     _FutureListener.handleValue (dart:async/future_impl.dart:126:18)
#13     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:639:45)
#14     Future._propagateToListeners (dart:async/future_impl.dart:668:32)
#15     Future._complete (dart:async/future_impl.dart:473:7)
#16     _SyncCompleter.complete (dart:async/future_impl.dart:51:12)
#17     _AsyncAwaitCompleter.complete.<anonymous closure> (dart:async/runtime/libasync_patch.dart:33:20)
#18     _rootRun (dart:async/zone.dart:1124:13)
#19     _CustomZone.run (dart:async/zone.dart:1021:19)
#20     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:947:23)
#21     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#22     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#23     _runPendingImmediateCallback (dart:isolate/runtime/libisolate_patch.dart:115:13)
#24     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:172:5)


[flutter_02.log](https://github.com/flutter/flutter/files/2863950/flutter_02.log)

**Comment by zoechi** [comment]
What does `git --version` print?
https://github.com/flutter/flutter/wiki/Workarounds-for-common-issues#flutter-installation-corrupted might help

**Comment by mark420524** [comment]
@zoechi 
it print `git version 2.5.0.windows.1`

**Comment by zoechi** [comment]
Did you try to commands from the link I posted?

**Comment by mark420524** [comment]
@zoechi 
it works
