### ISSUE TITLE
Document references must have an even number of segments

### ISSUE THREAD

**Issue by baeharam** [flutter/flutter#27931]
I'm suffering horrible error of cloud firestore in whole day.... I don't know what is the problem, I asked for stackoverflow, but there was no answer, how to deal with???

```dart
Future<String> test() async {
  CollectionReference col = Firestore.instance.collection('messages');
  QuerySnapshot querySnapshot = await col.where('begin',isEqualTo: false).getDocuments();
}
```

What is wrong with my code??

Error

```
E/MethodChannel#plugins.flutter.io/cloud_firestore(12549): Failed to handle method call
E/MethodChannel#plugins.flutter.io/cloud_firestore(12549): java.lang.IllegalArgumentException: Invalid document reference. Document references must have an even number of segments, but messages has 1
E/MethodChannel#plugins.flutter.io/cloud_firestore(12549): 	at com.google.firebase.firestore.DocumentReference.zza(com.google.firebase:firebase-firestore@@17.1.1:81)
E/MethodChannel#plugins.flutter.io/cloud_firestore(12549): 	at com.google.firebase.firestore.FirebaseFirestore.document(com.google.firebase:firebase-firestore@@17.1.1:259)
E/MethodChannel#plugins.flutter.io/cloud_firestore(12549): 	at io.flutter.plugins.firebase.cloudfirestore.CloudFirestorePlugin.getDocumentReference(CloudFirestorePlugin.java:92)
E/MethodChannel#plugins.flutter.io/cloud_firestore(12549): 	at io.flutter.plugins.firebase.cloudfirestore.CloudFirestorePlugin.onMethodCall(CloudFirestorePlugin.java:474)
E/MethodChannel#plugins.flutter.io/cloud_firestore(12549): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:200)
E/MethodChannel#plugins.flutter.io/cloud_firestore(12549): 	at io.flutter.view.FlutterNativeView$PlatformMessageHandlerImpl.handlePlatformMessage(FlutterNativeView.java:188)
E/MethodChannel#plugins.flutter.io/cloud_firestore(12549): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:202)
E/MethodChannel#plugins.flutter.io/cloud_firestore(12549): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/MethodChannel#plugins.flutter.io/cloud_firestore(12549): 	at android.os.MessageQueue.next(MessageQueue.java:325)
E/MethodChannel#plugins.flutter.io/cloud_firestore(12549): 	at android.os.Looper.loop(Looper.java:142)
E/MethodChannel#plugins.flutter.io/cloud_firestore(12549): 	at android.app.ActivityThread.main(ActivityThread.java:6938)
E/MethodChannel#plugins.flutter.io/cloud_firestore(12549): 	at java.lang.reflect.Method.invoke(Native Method)
E/MethodChannel#plugins.flutter.io/cloud_firestore(12549): 	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
E/MethodChannel#plugins.flutter.io/cloud_firestore(12549): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)
```

**Comment by zoechi** [comment]
Perhaps https://stackoverflow.com/questions/54561787/how-to-fix-platform-exception-invalid-document-reference-document-references-m

**Comment by zoechi** [comment]
Please post the link to the StackOverflow question you posted.

**Comment by baeharam** [comment]
https://stackoverflow.com/q/54685662/11054387

Your link is not my issue because my collections is constant string, so it cannot be null

**Comment by zoechi** [comment]
Perhaps https://stackoverflow.com/questions/50653608/firebase-invalid-document-reference-document-references-must-have-an-even-numbe/50653691

This error doesn't look Flutter related.

**Comment by zoechi** [comment]
https://stackoverflow.com/q/54685662/11054387 got an answer.
I think we can close here.

**Comment by baeharam** [comment]
@zoechi It is not solved
