### ISSUE TITLE
Same package name occured twice

### ISSUE THREAD

**Issue by felangga** [flutter/flutter#27984]
## command

flutter packages get

## exception

FormatException: FormatException: Same package name occured twice. (at offset 2834)

```
#0      parse (package:package_config/packages_file.dart:67:7)
#1      _parse (package:flutter_tools/src/dart/package_map.dart:14:10)
#2      PackageMap.load (package:flutter_tools/src/dart/package_map.dart:35:14)
#3      PackageMap.map (package:flutter_tools/src/dart/package_map.dart:39:5)
#4      FlutterCommandRunner._checkFlutterCopy (package:flutter_tools/src/runner/flutter_command_runner.dart:543:41)
#5      FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:374:9)
<asynchronous suspension>
#6      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:142:29)
<asynchronous suspension>
#7      _rootRun (dart:async/zone.dart:1124:13)
#8      _CustomZone.run (dart:async/zone.dart:1021:19)
#9      _runZoned (dart:async/zone.dart:1516:10)
#10     runZoned (dart:async/zone.dart:1463:12)
#11     AppContext.run (package:flutter_tools/src/base/context.dart:141:18)
<asynchronous suspension>
#12     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:361:19)
<asynchronous suspension>
#13     CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:111:29)
#14     new Future.sync (dart:async/future.dart:224:31)
#15     CommandRunner.run (package:args/command_runner.dart:111:11)
#16     FlutterCommandRunner.run (package:flutter_tools/src/runner/flutter_command_runner.dart:241:18)
#17     run.<anonymous closure> (package:flutter_tools/runner.dart:60:20)
<asynchronous suspension>
#18     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:142:29)
<asynchronous suspension>
#19     _rootRun (dart:async/zone.dart:1124:13)
#20     _CustomZone.run (dart:async/zone.dart:1021:19)
#21     _runZoned (dart:async/zone.dart:1516:10)
#22     runZoned (dart:async/zone.dart:1463:12)
#23     AppContext.run (package:flutter_tools/src/base/context.dart:141:18)
<asynchronous suspension>
#24     runInContext (package:flutter_tools/src/context_runner.dart:43:24)
<asynchronous suspension>
#25     run (package:flutter_tools/runner.dart:51:10)
#26     main (package:flutter_tools/executable.dart:51:9)
<asynchronous suspension>
#27     main (file:///b/build/slave/Linux_Flutter_Packaging/build/archive/flutter/packages/flutter_tools/bin/flutter_tools.dart:8:3)
#28     _startIsolate.<anonymous closure> (dart:isolate/runtime/libisolate_patch.dart:287:32)
#29     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:171:12)
```

## flutter doctor

```
[✓] Flutter (Channel stable, v1.0.0, on Linux, locale en_US.UTF-8)
    • Flutter version 1.0.0 at /home/felangga/Documents/flutter
    • Framework revision 5391447fae (3 months ago), 2018-11-29 19:41:26 -0800
    • Engine revision 7375a0f414
    • Dart version 2.1.0 (build 2.1.0-dev.9.4 f9ebf21297)

[✓] Android toolchain - develop for Android devices (Android SDK 28.0.3)
    • Android SDK at /home/felangga/Android/Sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /home/felangga/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)
    • All Android licenses accepted.

[✓] Android Studio (version 3.3)
    • Android Studio at /home/felangga/android-studio
    • Flutter plugin version 32.0.1
    • Dart plugin version 182.5124
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)

[✓] VS Code (version 1.31.0)
    • VS Code at /usr/share/code
    • Flutter extension version 2.22.3

[✓] Connected device (1 available)
    • ONEPLUS A5010 • 3e2177c • android-arm64 • Android 9 (API 28)

• No issues found!
```

**Comment by felangga** [comment]
This is my pubspec.yaml

`version: 1.0.0+1

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  http: ^0.12.0+1
  intl: ^0.15.7
  keyboard_visibility: any
  flutter_spinkit: "^3.1.0"
  flushbar: ^1.2.1
  firebase_auth: ^0.6.6
  firebase_core: ^0.2.5 
  shared_preferences: ^0.4.2
  dio: 2.0.0
  device_info: ^0.4.0+1


dev_dependencies:
  flutter_test:
    sdk: flutter`

**Comment by kangwang1988** [comment]
Fail to reproduce this issue using the latest master and your pubspec.yaml
```dart
KyleWongdeMacBook-Pro:hello_flutter kylewong$ flutter run -d xxx
Launching lib/main.dart on KyleWong's iPhone in debug mode...
Found saved certificate choice "iPhone Developer: Kang Wang (xxx)". To clear, use "flutter config".
Signing iOS app for device deployment using developer identity: "iPhone Developer: Kang Wang (39S29P74A8)"
Running Xcode build...                                                  
 ├─Assembling Flutter resources...                           1.6s
 └─Compiling, linking and signing...                         3.3s
Xcode build done.                                            6.8s
5.16.0 - [Firebase/Core][I-COR000003] The default Firebase app has not yet been configured. Add `[FIRApp configure];` (`FirebaseApp.configure()` in Swift) to your application initialization. Read more: https://goo.gl/ctyzm8.
5.16.0 - [Firebase/Core][I-COR000012] Could not locate configuration file: 'GoogleService-Info.plist'.
5.16.0 - [Firebase/Core][I-COR000005] No app has been configured yet.   
Installing and launching...                                            ⣷^Z
[1]+  Stopped                 flutter run -d 1c8e085cf2ff6fa27643ab4afec4bf4a077688af
KyleWongdeMacBook-Pro:hello_flutter kylewong$ cat pubspec.yaml 
name: hello_flutter
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  http: ^0.12.0+1
  intl: ^0.15.7
  keyboard_visibility: any
  flutter_spinkit: "^3.1.0"
  flushbar: ^1.2.1
  firebase_auth: ^0.6.6
  firebase_core: ^0.2.5 
  shared_preferences: ^0.4.2
  dio: 2.0.0
  device_info: ^0.4.0+1


dev_dependencies:
  flutter_test:
    sdk: flutter
KyleWongdeMacBook-Pro:hello_flutter kylewong$ flutter doctor -v
[✓] Flutter (Channel master, v1.2.2-pre.3, on Mac OS X 10.14.4 18E184e, locale en-CN)
    • Flutter version 1.2.2-pre.3 at /Users/kylewong/Codes/Flutter/alibaba-flutter/flutter
    • Framework revision 67cf21577f (67 minutes ago), 2019-02-14 23:17:16 -0800
    • Engine revision 3757390fa4
    • Dart version 2.1.2 (build 2.1.2-dev.0.0 0a7dcf17eb)
```

**Comment by felangga** [comment]
This problem occurred when I working with the Android and my friend working with the iOS device merged together on git. I don't know if some file must not be commited, I'm using default dart .gitignore. 
I resolved this issue by going back to previous branch and only merge the lib/ directory.

**Comment by kangwang1988** [comment]
I see, maybe the .packages is broken.
`flutter clean & flutter packages get` is likely to resolve this issue too.
