### ISSUE TITLE
FutureBuilder: Failed assertion: boolean expression must not be null

### ISSUE THREAD

**Issue by neiljaywarner** [flutter/flutter#28029]
2019-02-15 17:30:09.100 32478-32684/com.replacedmypackagename I/flutter: The following assertion was thrown building FutureBuilder<NetworkHeadersManager>(dirty, state:
2019-02-15 17:30:09.100 32478-32684/com.replacedmypackagename I/flutter: _FutureBuilderState<NetworkHeadersManager>#9e4cb):
2019-02-15 17:30:09.100 32478-32684/com.replacedmypackagename I/flutter: Failed assertion: boolean expression must not be null
2019-02-15 17:30:09.103 32478-32684/com.replacedmypackagename I/flutter: Either the assertion indicates an error in the framework itself, or we should provide substantially
2019-02-15 17:30:09.103 32478-32684/com.replacedmypackagename I/flutter: more information in this error message to help you determine and fix the underlying cause.
2019-02-15 17:30:09.103 32478-32684/com.replacedmypackagename I/flutter: In either case, please report this assertion by filing a bug on GitHub:
2019-02-15 17:30:09.103 32478-32684/com.replacedmypackagename I/flutter:   https://github.com/flutter/flutter/issues/new?template=BUG.md
2019-02-15 17:30:09.103 32478-32684/com.replacedmypackagename I/flutter: When the exception was thrown, this was the stack:
2019-02-15 17:30:09.113 32478-32684/com.replacedmypackagename I/flutter: #0      MyApp.build.<anonymous closure> (package:blah/main.dart:28:22)
2019-02-15 17:30:09.113 32478-32684/com.replacedmypackagename I/flutter: #1      _FutureBuilderState.build (package:flutter/src/widgets/async.dart)
2019-02-15 17:30:09.113 32478-32684/com.replacedmypackagename I/flutter: #2      StatefulElement.build (package:flutter/src/widgets/framework.dart:3809:27)
2019-02-15 17:30:09.113 32478-32684/com.replacedmypackagename I/flutter: #3      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3721:15)
2019-02-15 17:30:09.113 32478-32684/com.replacedmypackagename I/flutter: #4      Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
2019-02-15 17:30:09.113 32478-32684/com.replacedmypackagename I/flutter: #5      ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3701:5)
2019-02-15 17:30:09.113 32478-32684/com.replacedmypackagename I/flutter: #6      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3848:11)
2019-02-15 17:30:09.113 32478-32684/com.replacedmypackagename I/flutter: #7      ComponentElement.mount (package:flutter/src/widgets/framework.dart:3696:5)
2019-02-15 17:30:09.113 32478-32684/com.replacedmypackagename I/flutter: #8      Element.inflateWidget (package:flutter/src/widgets/framework.dart:2950:14)
2019-02-15 17:30:09.113 32478-32684/com.replacedmypackagename I/flutter: #9      Element.updateChild (package:flutter/src/widgets/framework.dart:2753:12)
2019-02-15 17:30:09.113 32478-32684/com.replacedmypackagename I/flutter: #10     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3732:16)
2019-02-15 17:30:09.113 32478-32684/com.replacedmypackagename I/flutter: #11     Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
2019-02-15 17:30:09.113 32478-32684/com.replacedmypackagename I/flutter: #12     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3701:5)
2019-02-15 17:30:09.113 32478-32684/com.replacedmypackagename I/flutter: #13     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3696:5)
2019-02-15 17:30:09.113 32478-32684/com.replacedmypackagename I/flutter: #14     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2950:14)
2019-02-15 17:30:09.113 32478-32684/com.replacedmypackagename I/flutter: #15     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:12)
2019-02-15 17:30:09.113 32478-32684/com.replacedmypackagename I/flutter: #16     RenderObjectToWidgetElement._rebuild (package:flutter/src/widgets/binding.dart:918:16)
2019-02-15 17:30:09.113 32478-32684/com.replacedmypackagename I/flutter: #17     RenderObjectToWidgetElement.mount (package:flutter/src/widgets/binding.dart:889:5)
2019-02-15 17:30:09.114 32478-32684/com.replacedmypackagename I/flutter: #18     RenderObjectToWidgetAdapter.attachToRenderTree.<anonymous closure> (package:flutter/src/widgets/binding.dart:835:17)
2019-02-15 17:30:09.114 32478-32684/com.replacedmypackagename I/flutter: #19     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2266:19)
2019-02-15 17:30:09.114 32478-32684/com.replacedmypackagename I/flutter: #20     RenderObjectToWidgetAdapter.attachToRenderTree (package:flutter/src/widgets/binding.dart:834:13)
2019-02-15 17:30:09.114 32478-32684/com.replacedmypackagename I/flutter: #21     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding&WidgetsBinding.attachRootWidget (package:flutter/src/widgets/binding.dart:721:7)
2019-02-15 17:30:09.114 32478-32684/com.replacedmypackagename I/flutter: #22     runApp (package:flutter/src/widgets/binding.dart:765:7)
2019-02-15 17:30:09.114 32478-32684/com.replacedmypackagename I/flutter: #23     main (package:blah/main.dart:9:24)
2019-02-15 17:30:09.114 32478-32684/com.replacedmypackagename I/flutter: #25     main (package:blah/main.dart:9:12)
2019-02-15 17:30:09.114 32478-32684/com.replacedmypackagename I/flutter: #26     _startIsolate.<anonymous closure> (dart:isolate/runtime/libisolate_patch.dart:289:19)
2019-02-15 17:30:09.114 32478-32684/com.replacedmypackagename I/flutter: #27     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:171:12)
2019-02-15 17:30:09.114 32478-32684/com.replacedmypackagename I/flutter: (elided one frame from package dart:async)
2019-02-15 17:30:09.114 32478-32684/com.replacedmypackagename I/flutter: ════════════════════════════════════════════════════════════════════════════════════════════════════
2019-02-15 17:30:09.170 32478-32684/com.replacedmypackagename I/flutter: Another exception was thrown: type '_TypeError' is not a subtype of type 'bool'

**Comment by neiljaywarner** [comment]
I think this was because I used if (snapshot.error( instead of if (snapshot.hasError)

**Comment by kangwang1988** [comment]
@neiljaywarner 
How this issue is reproduced ?
Besides, `flutter doctor -v` please.

**Comment by neiljaywarner** [comment]
I made the report because the log said to make it.

You can get reproduce by using if (snapshot.error) Text(snapshot.error) instead of if snapshot.hasError.  

You don't focus on what to actually do in case of error at first.. but still.. oops! My fault
