### ISSUE TITLE
The problems when run 'flutter build apk --debug'

### ISSUE THREAD

**Issue by AweiLoveAndroid** [flutter/flutter#28044]
Flutter crash report; please file at https://github.com/flutter/flutter/issues.

## command

flutter build apk --debug

## exception

FormatException: FormatException: Bad UTF-8 encoding 0xb4 (at offset 130)

```
#0      _Utf8Decoder.convert (dart:convert/utf.dart:568:13)
#1      _Utf8ConversionSink.addSlice (dart:convert/string_conversion.dart:345:14)
#2      _Utf8ConversionSink.add (dart:convert/string_conversion.dart:341:5)
#3      _ConverterStreamEventSink.add (dart:convert/chunked_conversion.dart:86:18)
#4      _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:120:24)
#5      _rootRunUnary (dart:async/zone.dart:1132:38)
#6      _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#7      _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
#8      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#9      _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#10     _SyncStreamController._sendData (dart:async/stream_controller.dart:763:19)
#11     _StreamController._add (dart:async/stream_controller.dart:639:7)
#12     _StreamController.add (dart:async/stream_controller.dart:585:5)
#13     _Socket._onData (dart:io/runtime/binsocket_patch.dart:1721:41)
#14     _rootRunUnary (dart:async/zone.dart:1136:13)
#15     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#16     _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
#17     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#18     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#19     _SyncStreamController._sendData (dart:async/stream_controller.dart:763:19)
#20     _StreamController._add (dart:async/stream_controller.dart:639:7)
#21     _StreamController.add (dart:async/stream_controller.dart:585:5)
#22     new _RawSocket.<anonymous closure> (dart:io/runtime/binsocket_patch.dart:1283:33)
#23     _NativeSocket.issueReadEvent.issue (dart:io/runtime/binsocket_patch.dart:826:14)
#24     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#25     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#26     _runPendingImmediateCallback (dart:isolate/runtime/libisolate_patch.dart:115:13)
#27     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:172:5)
```

## flutter doctor

```
[✓] Flutter (Channel master, v1.0.1-pre.3, on Microsoft Windows [Version 6.1.7601], locale zh-CN)
    • Flutter version 1.0.1-pre.3 at E:\develop\flutter
    • Framework revision d74b1c2051 (2 months ago), 2018-12-07 14:19:09 -0800
    • Engine revision 7375a0f414
    • Dart version 2.1.0 (build 2.1.0-dev.9.4 f9ebf21297)

[!] Android toolchain - develop for Android devices (Android SDK 28.0.3)
    • Android SDK at E:\develop\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = E:\develop\sdk
    • Java binary at: E:\develop\android-studio-ide-173.4819257-windows\android-studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b02)

[✓] Android Studio (version 3.1)
    • Android Studio at E:\develop\android-studio-ide-173.4819257-windows\android-studio
    • Flutter plugin version 29.0.1
    • Dart plugin version 173.4700
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b02)

[✓] IntelliJ IDEA Community Edition (version 2018.2)
    • IntelliJ at E:\develop\IntelliJ IDEA Community Edition 2018.2
    • Flutter plugin version 29.1.2
    • Dart plugin version 182.3569.4

[!] Connected device
    ! No devices available

! Doctor found issues in 1 categories.
```

**Comment by kangwang1988** [comment]
Duple of: https://github.com/flutter/flutter/issues/15646
