### ISSUE TITLE
firebase_ml_vision: 0.5.1+1 does not work

### ISSUE THREAD

**Issue by jonathangizmo** [flutter/flutter#28054]
## Steps to Reproduce

1. Add `firebase_ml_vision: 0.5.1+1` to `pubspec.yaml` along with `firebase_core: ^0.3.0+2`, `firebase_auth: ^0.8.1+1` and `firebase_messaging: 3.0.1`
2. Run App `flutter clean`, `flutter packages get`, `flutter run ..`
3. I also tried `cd ios && pod update`, `pod install` and `pod update GoogleAppMeasurement`

## Logs

`flutter run` output : 
```
Launching lib/main.dart on iPhone X in debug mode...
Running pod install...
CocoaPods' output:
↳
      Preparing

    Analyzing dependencies

    Inspecting targets to integrate
      Using `ARCHS` setting to build architectures of target `Pods-Runner`: (``)

    Finding Podfile changes
      A firebase_ml_vision
      - FBSDKLoginKit
      - Firebase
      - Flutter
      - GoogleAnalytics
      - camera
      - device_info
      - firebase_auth
      - firebase_core
      - firebase_messaging
      - flutter_facebook_login
      - google_sign_in
      - image_picker
      - multi_image_picker
      - path_provider
      - shared_preferences

    Fetching external sources
    -> Fetching podspec for `Flutter` from `.symlinks/flutter/ios`
    -> Fetching podspec for `camera` from `.symlinks/plugins/camera/ios`
    -> Fetching podspec for `device_info` from `.symlinks/plugins/device_info/ios`
    -> Fetching podspec for `firebase_auth` from `.symlinks/plugins/firebase_auth/ios`
    -> Fetching podspec for `firebase_core` from `.symlinks/plugins/firebase_core/ios`
    -> Fetching podspec for `firebase_messaging` from `.symlinks/plugins/firebase_messaging/ios`
    -> Fetching podspec for `firebase_ml_vision` from `.symlinks/plugins/firebase_ml_vision/ios`
    -> Fetching podspec for `flutter_facebook_login` from `.symlinks/plugins/flutter_facebook_login/ios`
    -> Fetching podspec for `google_sign_in` from `.symlinks/plugins/google_sign_in/ios`
    -> Fetching podspec for `image_picker` from `.symlinks/plugins/image_picker/ios`
    -> Fetching podspec for `multi_image_picker` from `.symlinks/plugins/multi_image_picker/ios`
    -> Fetching podspec for `path_provider` from `.symlinks/plugins/path_provider/ios`
    -> Fetching podspec for `shared_preferences` from `.symlinks/plugins/shared_preferences/ios`

    Resolving dependencies of `Podfile`
    [!] CocoaPods could not find compatible versions for pod "GoogleAppMeasurement":
      In snapshot (Podfile.lock):
        GoogleAppMeasurement (= 5.5.0)

      In Podfile:
        firebase_ml_vision (from `.symlinks/plugins/firebase_ml_vision/ios`) was resolved to 0.1.1, which depends on
          GoogleAppMeasurement (~> 5.3.0)

    It seems like you've changed the constraints of dependency `GoogleAppMeasurement` inside your development pod `firebase_ml_vision`.
    You should run `pod update GoogleAppMeasurement` to apply changes you've made.

    /usr/local/Cellar/cocoapods/1.5.3/libexec/gems/molinillo-0.6.5/lib/molinillo/resolution.rb:328:in `raise_error_unless_state'
    /usr/local/Cellar/cocoapods/1.5.3/libexec/gems/molinillo-0.6.5/lib/molinillo/resolution.rb:310:in `block in unwind_for_conflict'
    /usr/local/Cellar/cocoapods/1.5.3/libexec/gems/molinillo-0.6.5/lib/molinillo/resolution.rb:308:in `tap'
    /usr/local/Cellar/cocoapods/1.5.3/libexec/gems/molinillo-0.6.5/lib/molinillo/resolution.rb:308:in `unwind_for_conflict'
    /usr/local/Cellar/cocoapods/1.5.3/libexec/gems/molinillo-0.6.5/lib/molinillo/resolution.rb:257:in `process_topmost_state'
    /usr/local/Cellar/cocoapods/1.5.3/libexec/gems/molinillo-0.6.5/lib/molinillo/resolution.rb:182:in `resolve'
    /usr/local/Cellar/cocoapods/1.5.3/libexec/gems/molinillo-0.6.5/lib/molinillo/resolver.rb:43:in `resolve'
    /usr/local/Cellar/cocoapods/1.5.3/libexec/gems/cocoapods-1.5.3/lib/cocoapods/resolver.rb:123:in `resolve'
    /usr/local/Cellar/cocoapods/1.5.3/libexec/gems/cocoapods-1.5.3/lib/cocoapods/installer/analyzer.rb:781:in `block in resolve_dependencies'
    /usr/local/Cellar/cocoapods/1.5.3/libexec/gems/cocoapods-1.5.3/lib/cocoapods/user_interface.rb:64:in `section'
    /usr/local/Cellar/cocoapods/1.5.3/libexec/gems/cocoapods-1.5.3/lib/cocoapods/installer/analyzer.rb:779:in `resolve_dependencies'
    /usr/local/Cellar/cocoapods/1.5.3/libexec/gems/cocoapods-1.5.3/lib/cocoapods/installer/analyzer.rb:88:in `analyze'
    /usr/local/Cellar/cocoapods/1.5.3/libexec/gems/cocoapods-1.5.3/lib/cocoapods/installer.rb:243:in `analyze'
    /usr/local/Cellar/cocoapods/1.5.3/libexec/gems/cocoapods-1.5.3/lib/cocoapods/installer.rb:154:in `block in resolve_dependencies'
    /usr/local/Cellar/cocoapods/1.5.3/libexec/gems/cocoapods-1.5.3/lib/cocoapods/user_interface.rb:64:in `section'
    /usr/local/Cellar/cocoapods/1.5.3/libexec/gems/cocoapods-1.5.3/lib/cocoapods/installer.rb:153:in `resolve_dependencies'
    /usr/local/Cellar/cocoapods/1.5.3/libexec/gems/cocoapods-1.5.3/lib/cocoapods/installer.rb:116:in `install!'
    /usr/local/Cellar/cocoapods/1.5.3/libexec/gems/cocoapods-1.5.3/lib/cocoapods/command/install.rb:41:in `run'
    /usr/local/Cellar/cocoapods/1.5.3/libexec/gems/claide-1.0.2/lib/claide/command.rb:334:in `run'
    /usr/local/Cellar/cocoapods/1.5.3/libexec/gems/cocoapods-1.5.3/lib/cocoapods/command.rb:52:in `run'
    /usr/local/Cellar/cocoapods/1.5.3/libexec/gems/cocoapods-1.5.3/bin/pod:55:in `<top (required)>'
    /usr/local/Cellar/cocoapods/1.5.3/libexec/bin/pod:22:in `load'
    /usr/local/Cellar/cocoapods/1.5.3/libexec/bin/pod:22:in `<main>'

Error running pod install
Error launching application on iPhone X.
```

`pod update GoogleAppMeasurement` and `pod update` output:

```
Analyzing dependencies
Fetching podspec for `Flutter` from `.symlinks/flutter/ios`
Fetching podspec for `camera` from `.symlinks/plugins/camera/ios`
Fetching podspec for `device_info` from `.symlinks/plugins/device_info/ios`
Fetching podspec for `firebase_auth` from `.symlinks/plugins/firebase_auth/ios`
Fetching podspec for `firebase_core` from `.symlinks/plugins/firebase_core/ios`
Fetching podspec for `firebase_messaging` from `.symlinks/plugins/firebase_messaging/ios`
Fetching podspec for `firebase_ml_vision` from `.symlinks/plugins/firebase_ml_vision/ios`
Fetching podspec for `flutter_facebook_login` from `.symlinks/plugins/flutter_facebook_login/ios`
Fetching podspec for `google_sign_in` from `.symlinks/plugins/google_sign_in/ios`
Fetching podspec for `image_picker` from `.symlinks/plugins/image_picker/ios`
Fetching podspec for `multi_image_picker` from `.symlinks/plugins/multi_image_picker/ios`
Fetching podspec for `path_provider` from `.symlinks/plugins/path_provider/ios`
Fetching podspec for `shared_preferences` from `.symlinks/plugins/shared_preferences/ios`
[!] CocoaPods could not find compatible versions for pod "GoogleAppMeasurement":
  In Podfile:
    firebase_auth (from `.symlinks/plugins/firebase_auth/ios`) was resolved to 0.0.1, which depends on
      Firebase/Core was resolved to 5.16.0, which depends on
        FirebaseAnalytics (= 5.5.0) was resolved to 5.5.0, which depends on
          GoogleAppMeasurement (= 5.5.0)

    firebase_ml_vision (from `.symlinks/plugins/firebase_ml_vision/ios`) was resolved to 0.1.1, which depends on
      GoogleAppMeasurement (~> 5.3.0)
```

`pod install` output:
```
Analyzing dependencies
Fetching podspec for `Flutter` from `.symlinks/flutter/ios`
Fetching podspec for `camera` from `.symlinks/plugins/camera/ios`
Fetching podspec for `device_info` from `.symlinks/plugins/device_info/ios`
Fetching podspec for `firebase_auth` from `.symlinks/plugins/firebase_auth/ios`
Fetching podspec for `firebase_core` from `.symlinks/plugins/firebase_core/ios`
Fetching podspec for `firebase_messaging` from `.symlinks/plugins/firebase_messaging/ios`
Fetching podspec for `firebase_ml_vision` from `.symlinks/plugins/firebase_ml_vision/ios`
Fetching podspec for `flutter_facebook_login` from `.symlinks/plugins/flutter_facebook_login/ios`
Fetching podspec for `google_sign_in` from `.symlinks/plugins/google_sign_in/ios`
Fetching podspec for `image_picker` from `.symlinks/plugins/image_picker/ios`
Fetching podspec for `multi_image_picker` from `.symlinks/plugins/multi_image_picker/ios`
Fetching podspec for `path_provider` from `.symlinks/plugins/path_provider/ios`
Fetching podspec for `shared_preferences` from `.symlinks/plugins/shared_preferences/ios`
[!] CocoaPods could not find compatible versions for pod "GoogleAppMeasurement":
  In snapshot (Podfile.lock):
    GoogleAppMeasurement (= 5.5.0)

  In Podfile:
    firebase_ml_vision (from `.symlinks/plugins/firebase_ml_vision/ios`) was resolved to 0.1.1, which depends on
      GoogleAppMeasurement (~> 5.3.0)

It seems like you've changed the constraints of dependency `GoogleAppMeasurement` inside your development pod `firebase_ml_vision`.
You should run `pod update GoogleAppMeasurement` to apply changes you've made.
```

```
flutter doctor -v

[✓] Flutter (Channel master, v1.2.1-pre.10, on Mac OS X 10.14.1 18B75, locale en-US)
    • Flutter version 1.2.1-pre.10 at /Users/jonathansudhakar/projects/flutter
    • Framework revision bb5663d2d8 (3 weeks ago), 2019-01-27 09:43:09 -0800
    • Engine revision 9b6d5031a3
    • Dart version 2.1.1 (build 2.1.1-dev.3.2 a5030ed92f)

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/jonathansudhakar/Library/Android/sdk
    • Android NDK at /Users/jonathansudhakar/Library/Android/sdk/ndk-bundle
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.1, Build version 10B61
    • ios-deploy 1.9.4
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 27.1.1
    • Dart plugin version 173.4700
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)

[✓] VS Code (version 1.31.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 2.22.3

[✓] Connected device (1 available)
    • iPhone X • 27940593-9086-4C39-BE4B-CDF2E880B41F • ios • iOS 12.1 (simulator)

• No issues found!

```

pubspec.yaml

```
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  scoped_model: 1.0.1
  image_picker: 0.5.0
  multi_image_picker: ^3.0.11
  shared_preferences: 0.5.0
  flutter_facebook_login: 1.2.0
  google_sign_in: ^4.0.0
  font_awesome_flutter: ^8.2.0
  device_info: ^0.4.0
  http: ^0.12.0+1
  camera: ^0.3.0
  path_provider: 0.5.0+1
  uuid: 2.0.0
  autocomplete_textfield: 1.6.4
  flutter_rating: ^0.0.2

  firebase_core: ^0.3.0+2
  firebase_auth: ^0.8.1+1
  firebase_messaging: 3.0.1
  firebase_ml_vision: 0.5.1+1

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true
```

**Comment by jonathangizmo** [comment]
Issue persists with `firebase_ml_vision: 0.6.0`

**Comment by bgetsug** [comment]
I'm getting the same error with `firebase_ml_vision` 0.6.0. Workaround I'm trying:

In `ios/.symlinks/plugins/firebase_ml_vision/ios/firebase_ml_vision.podspec`, I manually changed
`s.dependency 'GoogleAppMeasurement', '~> 5.3.0'` to `...'~> 5.5.0'` and was able to get `pod install` to run.

**Comment by jonathangizmo** [comment]
When I manually change `s.dependency 'GoogleAppMeasurement', '~> 5.3.0'` to `...'~> 5.5.0'`, I get: 


```
Launching lib/main.dart on iPhone X in debug mode...
Running Xcode build...
Xcode build done.                                            2.1s
Failed to build iOS app
Error output from Xcode build:
↳
    ** BUILD FAILED **


Xcode's output:
↳
    /Users/.../projects/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_ml_vision-0.6.0+1/ios/Classes/CloudLabelDetector.m:4:8: error: unknown type name 'FIRVisionCloudLabelDetector'; did you mean 'FIRVisionCloudLandmarkDetector'?
    static FIRVisionCloudLabelDetector *detector;
           ^~~~~~~~~~~~~~~~~~~~~~~~~~~
           FIRVisionCloudLandmarkDetector
    In module 'FirebaseMLVision' imported from /Users/.../projects/project/projecta/ios/Pods/Headers/Public/Firebase/Firebase.h:70:
    /Users/.../projects/project/projecta/ios/Pods/FirebaseMLVision/Frameworks/FirebaseMLVision.framework/Headers/FIRVisionCloudLandmarkDetector.h:22:12: note: 'FIRVisionCloudLandmarkDetector' declared here
    @interface FIRVisionCloudLandmarkDetector : NSObject
               ^
    /Users/.../projects/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_ml_vision-0.6.0+1/ios/Classes/CloudLabelDetector.m:10:22: error: no visible @interface for 'FIRVision' declares the selector 'cloudLabelDetectorWithOptions:'
      detector = [vision cloudLabelDetectorWithOptions:[CloudLabelDetector parseOptions:options]];
                  ~~~~~~ ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    /Users/.../projects/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_ml_vision-0.6.0+1/ios/Classes/CloudLabelDetector.m:14:31: error: unknown type name 'FIRVisionCloudLabel'; did you mean 'FIRVisionImageLabel'?
             completion:^(NSArray<FIRVisionCloudLabel *> *_Nullable labels, NSError *_Nullable error) {
                                  ^~~~~~~~~~~~~~~~~~~
                                  FIRVisionImageLabel
    In module 'FirebaseMLVision' imported from /Users/.../projects/project/projecta/ios/Pods/Headers/Public/Firebase/Firebase.h:70:
    /Users/.../projects/project/projecta/ios/Pods/FirebaseMLVision/Frameworks/FirebaseMLVision.framework/Headers/FIRVisionImageLabeler.h:3:8: note: 'FIRVisionImageLabel' declared here
    @class FIRVisionImageLabel;
           ^
    /Users/.../projects/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_ml_vision-0.6.0+1/ios/Classes/CloudLabelDetector.m:23:17: error: use of undeclared identifier 'FIRVisionCloudLabel'
               for (FIRVisionCloudLabel *label in labels) {
                    ^
    /Users/.../projects/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_ml_vision-0.6.0+1/ios/Classes/CloudLabelDetector.m:23:38: error: use of undeclared identifier 'label'; did you mean 'labels'?
               for (FIRVisionCloudLabel *label in labels) {
                                         ^~~~~
                                         labels
    /Users/.../projects/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_ml_vision-0.6.0+1/ios/Classes/CloudLabelDetector.m:14:65: note: 'labels' declared here
             completion:^(NSArray<FIRVisionCloudLabel *> *_Nullable labels, NSError *_Nullable error) {
                                                                    ^
    /Users/.../projects/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_ml_vision-0.6.0+1/ios/Classes/CloudLabelDetector.m:25:32: error: use of undeclared identifier 'label'
                   @"confidence" : label.confidence,
                                   ^
    /Users/.../projects/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_ml_vision-0.6.0+1/ios/Classes/CloudLabelDetector.m:26:30: error: use of undeclared identifier 'label'
                   @"entityId" : label.entityId,
                                 ^
    /Users/.../projects/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_ml_vision-0.6.0+1/ios/Classes/CloudLabelDetector.m:27:27: error: use of undeclared identifier 'label'
                   @"label" : label.label
                              ^
    8 errors generated.
    /Users/.../projects/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_ml_vision-0.6.0+1/ios/Classes/LabelDetector.m:4:8: error: unknown type name 'FIRVisionLabelDetector'; did you mean 'FIRVisionFaceDetector'?
    static FIRVisionLabelDetector *detector;
           ^~~~~~~~~~~~~~~~~~~~~~
           FIRVisionFaceDetector
    In module 'FirebaseMLVision' imported from /Users/.../projects/project/projecta/ios/Pods/Headers/Public/Firebase/Firebase.h:70:
    /Users/.../projects/project/projecta/ios/Pods/FirebaseMLVision/Frameworks/FirebaseMLVision.framework/Headers/FIRVisionFaceDetector.h:22:12: note: 'FIRVisionFaceDetector' declared here
    @interface FIRVisionFaceDetector : NSObject
               ^
    /Users/.../projects/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_ml_vision-0.6.0+1/ios/Classes/LabelDetector.m:35:4: error: expected a type
    + (FIRVisionLabelDetectorOptions *)parseOptions:(NSDictionary *)optionsData {
       ^
    /Users/.../projects/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_ml_vision-0.6.0+1/ios/Classes/LabelDetector.m:10:22: error: no visible @interface for 'FIRVision' declares the selector 'labelDetectorWithOptions:'
      detector = [vision labelDetectorWithOptions:[LabelDetector parseOptions:options]];
                  ~~~~~~ ^~~~~~~~~~~~~~~~~~~~~~~~
    /Users/.../projects/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_ml_vision-0.6.0+1/ios/Classes/LabelDetector.m:13:37: error: unknown type name 'FIRVisionLabel'; did you mean 'FIRVisionFace'?
                   completion:^(NSArray<FIRVisionLabel *> *_Nullable labels, NSError *_Nullable error) {
                                        ^~~~~~~~~~~~~~
                                        FIRVisionFace
    In module 'FirebaseMLVision' imported from /Users/.../projects/project/projecta/ios/Pods/Headers/Public/Firebase/Firebase.h:70:
    /Users/.../projects/project/projecta/ios/Pods/FirebaseMLVision/Frameworks/FirebaseMLVision.framework/Headers/FIRVisionFaceDetector.h:3:8: note: 'FIRVisionFace' declared here
    @class FIRVisionFace;
           ^
    /Users/.../projects/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_ml_vision-0.6.0+1/ios/Classes/LabelDetector.m:22:23: error: use of undeclared identifier 'FIRVisionLabel'
                     for (FIRVisionLabel *label in labels) {
                          ^
    /Users/.../projects/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_ml_vision-0.6.0+1/ios/Classes/LabelDetector.m:22:39: error: use of undeclared identifier 'label'; did you mean 'labels'?
                     for (FIRVisionLabel *label in labels) {
                                          ^~~~~
                                          labels
    /Users/.../projects/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_ml_vision-0.6.0+1/ios/Classes/LabelDetector.m:13:66: note: 'labels' declared here
                   completion:^(NSArray<FIRVisionLabel *> *_Nullable labels, NSError *_Nullable error) {
                                                                     ^
    /Users/.../projects/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_ml_vision-0.6.0+1/ios/Classes/LabelDetector.m:24:40: error: use of undeclared identifier 'label'
                         @"confidence" : @(label.confidence),
                                           ^
    /Users/.../projects/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_ml_vision-0.6.0+1/ios/Classes/LabelDetector.m:25:36: error: use of undeclared identifier 'label'
                         @"entityID" : label.entityID,
                                       ^
    /Users/.../projects/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_ml_vision-0.6.0+1/ios/Classes/LabelDetector.m:26:33: error: use of undeclared identifier 'label'
                         @"label" : label.label
                                    ^
    /Users/.../projects/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_ml_vision-0.6.0+1/ios/Classes/LabelDetector.m:12:13: error: no visible @interface for 'FIRVisionFaceDetector' declares the selector 'detectInImage:completion:'
      [detector detectInImage:image
       ~~~~~~~~ ^~~~~~~~~~~~~~~~~~~
    /Users/.../projects/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_ml_vision-0.6.0+1/ios/Classes/LabelDetector.m:37:12: error: unknown receiver 'FIRVisionLabelDetectorOptions'; did you mean 'FIRVisionFaceDetectorOptions'?
      return [[FIRVisionLabelDetectorOptions alloc] initWithConfidenceThreshold:[conf floatValue]];
               ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
               FIRVisionFaceDetectorOptions
    In module 'FirebaseMLVision' imported from /Users/.../projects/project/projecta/ios/Pods/Headers/Public/Firebase/Firebase.h:70:
    /Users/.../projects/project/projecta/ios/Pods/FirebaseMLVision/Frameworks/FirebaseMLVision.framework/Headers/FIRVisionFaceDetectorOptions.h:72:12: note: 'FIRVisionFaceDetectorOptions' declared here
    @interface FIRVisionFaceDetectorOptions : NSObject
               ^
    /Users/.../projects/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_ml_vision-0.6.0+1/ios/Classes/LabelDetector.m:37:49: error: no visible @interface for 'FIRVisionFaceDetectorOptions' declares the selector 'initWithConfidenceThreshold:'
      return [[FIRVisionLabelDetectorOptions alloc] initWithConfidenceThreshold:[conf floatValue]];
              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ ^~~~~~~~~~~~~~~~~~~~~~~~~~~
    12 errors generated.
```

**Comment by zoechi** [comment]
@bgetsug @jonathangizmo please try running `pod install` in `ios/` and if it does not help https://github.com/flutter/flutter/wiki/Workarounds-for-common-issues#generated-project-files-outdated

**Comment by bgetsug** [comment]
@zoechi this works:

`pubspec.yaml` excerpt:
```yaml
## Firebase
firebase_core: ^0.3.1
cloud_firestore: 0.9.5+1
firebase_auth: ^0.8.1+2
firebase_messaging: ^4.0.0+1
firebase_analytics: ^2.0.2+1
firebase_ml_vision: ^0.6.0+1

## Google
google_sign_in: ^4.0.1+1
googleapis: 0.53.0
googleapis_beta: 0.48.0
googleapis_auth: ^0.2.6
```
- Tried the above in a fresh project, `flutter packages get && cd ios && pod install` ✅
- Blew away the `ios` directory for my app, `flutter create .` ... `pod install` ✅
- Re-applied my customizations ... `pod install` ✅
- `flutter build ios` ✅ 

However, when I downgrade `cloud_firestore` to `0.9.0+1` to workaround #28103 and run `pod update`, that's when this happens:
```
[!] CocoaPods could not find compatible versions for pod "Firebase/Core":
  In Podfile:
    cloud_firestore (from `.symlinks/plugins/cloud_firestore/ios`) was resolved to 0.0.1, which depends on
      Firebase/Core

Specs satisfying the `Firebase/Core` dependency were found, but they required a higher minimum deployment target.
CocoaPods could not find compatible versions for pod "GoogleAppMeasurement":
  In Podfile:
    cloud_firestore (from `.symlinks/plugins/cloud_firestore/ios`) was resolved to 0.0.1, which depends on
      Firebase/Core was resolved to 5.17.0, which depends on
        FirebaseAnalytics (= 5.6.0) was resolved to 5.6.0, which depends on
          GoogleAppMeasurement (= 5.6.0)

    firebase_ml_vision (from `.symlinks/plugins/firebase_ml_vision/ios`) was resolved to 0.1.1, which depends on
      GoogleAppMeasurement (~> 5.3.0)
```
😢

**Comment by bgetsug** [comment]
...and now when I try to upgrade `cloud_firestore` back to `0.9.5+1`, run `flutter packages upgrade` and `cd ios && pod update`, I get the same error. Are there steps to clear out Cocoapods cache beyond running `pod cache clear --all` and/or removing `~/.cocoapods`? I feel like something else isn't getting cleaned up now...?

**Comment by bgetsug** [comment]
back in `pubspec.yaml`, commented out `firebase_ml_vision`:
```yaml
  firebase_core: ^0.3.1
  cloud_firestore: 0.9.5+1
  firebase_auth: ^0.8.1+2
  firebase_messaging: ^4.0.0+1
  firebase_analytics: ^2.0.2+1
#  firebase_ml_vision: ^0.6.0+1
```
Then:
```bash
flutter packages upgrade
cd ios && pod update
```
👌

**Comment by bgetsug** [comment]
restored `firebase_ml_vision: ^0.6.0+1` in my `pubspec.yaml`

then:
```bash
mv ios ios-bak
flutter create -i swift -a kotlin .
cd ios && pod install
```
👌 

Free blog post title: _To Dependency Hell and Back_

**Comment by zbarbuto** [comment]
https://github.com/flutter/plugins/blob/d136958665e7b943a76c617916987b34672dae98/packages/firebase_ml_vision/ios/firebase_ml_vision.podspec#L21

This appears to be the offending line - if I change that to 5.7.0 (to avoid conflict with the analytics package) it installs fine.

**Comment by jonathangizmo** [comment]
@zbarbuto When I change the version I get this:

```
Running pod install...
Running Xcode build...
Xcode build done.                                            2.6s
Failed to build iOS app
Error output from Xcode build:
↳
    ** BUILD FAILED **


Xcode's output:
↳
    /Users/.../projects/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_ml_vision-0.6.0+2/ios/Classes/CloudLabelDetector.m:4:8: error: unknown type name 'FIRVisionCloudLabelDetector'; did you mean 'FIRVisionCloudLandmarkDetector'?
    static FIRVisionCloudLabelDetector *detector;
           ^~~~~~~~~~~~~~~~~~~~~~~~~~~
           FIRVisionCloudLandmarkDetector
    In module 'FirebaseMLVision' imported from /Users/.../projects/project/projectname/ios/Pods/Headers/Public/Firebase/Firebase.h:70:
    /Users/.../projects/tasty/projectname/ios/Pods/FirebaseMLVision/Frameworks/FirebaseMLVision.framework/Headers/FIRVisionCloudLandmarkDetector.h:22:12: note: 'FIRVisionCloudLandmarkDetector' declared here
    @interface FIRVisionCloudLandmarkDetector : NSObject
               ^
    /Users/.../projects/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_ml_vision-0.6.0+2/ios/Classes/CloudLabelDetector.m:10:22: error: no visible @interface for 'FIRVision' declares the selector 'cloudLabelDetectorWithOptions:'
      detector = [vision cloudLabelDetectorWithOptions:[CloudLabelDetector parseOptions:options]];
                  ~~~~~~ ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    /Users/.../projects/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_ml_vision-0.6.0+2/ios/Classes/CloudLabelDetector.m:14:31: error: unknown type name 'FIRVisionCloudLabel'; did you mean 'FIRVisionImageLabel'?
             completion:^(NSArray<FIRVisionCloudLabel *> *_Nullable labels, NSError *_Nullable error) {
                                  ^~~~~~~~~~~~~~~~~~~
                                  FIRVisionImageLabel
    In module 'FirebaseMLVision' imported from /Users/.../projects/tasty/projectname/ios/Pods/Headers/Public/Firebase/Firebase.h:70:
    /Users/.../projects/tasty/projectname/ios/Pods/FirebaseMLVision/Frameworks/FirebaseMLVision.framework/Headers/FIRVisionImageLabeler.h:3:8: note: 'FIRVisionImageLabel' declared here
    @class FIRVisionImageLabel;
           ^
    /Users/.../projects/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_ml_vision-0.6.0+2/ios/Classes/CloudLabelDetector.m:23:17: error: use of undeclared identifier 'FIRVisionCloudLabel'
               for (FIRVisionCloudLabel *label in labels) {
                    ^
    /Users/.../projects/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_ml_vision-0.6.0+2/ios/Classes/CloudLabelDetector.m:23:38: error: use of undeclared identifier 'label'; did you mean 'labels'?
               for (FIRVisionCloudLabel *label in labels) {
                                         ^~~~~
                                         labels
    /Users/.../projects/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_ml_vision-0.6.0+2/ios/Classes/CloudLabelDetector.m:14:65: note: 'labels' declared here
             completion:^(NSArray<FIRVisionCloudLabel *> *_Nullable labels, NSError *_Nullable error) {
                                                                    ^
    /Users/.../projects/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_ml_vision-0.6.0+2/ios/Classes/CloudLabelDetector.m:25:32: error: use of undeclared identifier 'label'
                   @"confidence" : label.confidence,
                                   ^
    /Users/.../projects/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_ml_vision-0.6.0+2/ios/Classes/CloudLabelDetector.m:26:30: error: use of undeclared identifier 'label'
                   @"entityId" : label.entityId,
                                 ^
    /Users/.../projects/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_ml_vision-0.6.0+2/ios/Classes/CloudLabelDetector.m:27:27: error: use of undeclared identifier 'label'
                   @"label" : label.label
                              ^
    8 errors generated.
```

**Comment by hjonathan** [comment]
I have the same error? some idea?

**Comment by zbarbuto** [comment]
Update your podfile to specify versions for any of the ML Vision models you use - it seems the plugin needs to be updated to support the newer versions (see [here](https://stackoverflow.com/questions/54421151/add-firebase-ml-vision-to-flutter-raise-an-error-unknown-type-name-firvisioncl)).

```
  # Firebase ML Vision
  pod 'Firebase/MLVisionLabelModel', '5.15.0'
  pod 'Firebase/MLVisionTextModel', '5.15.0'
```

Also, the edit to the file was not necessary - just delete your `Podfile.lock` and `pod install` again.

**Comment by jonathangizmo** [comment]
@zbarbuto 
This works thanks!

**Comment by pushangupta** [comment]
Try uncommenting  `platform :ios, '9.0'` in podfile

**Comment by kroikie** [comment]
@jonathansudhakar1

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/437. Any further collaboration will be done there.

**Comment by leafs1** [comment]
How would I fix this issue on a Windows machine?
