### ISSUE TITLE
pub get failed (1)

### ISSUE THREAD

**Issue by IvanTerrito** [flutter/flutter#28078]
I'm trying to run Flutter app but I can't. I can't neither get packages.

## Logs

```
D:\Programmazione\Flutter\flutter_app>flutter run -v

[  +31 ms] executing: [D:\Programmazione\Flutter\flutter\] git rev-parse --abbrev-ref --symbolic @{u}
[  +98 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/master
[        ] executing: [D:\Programmazione\Flutter\flutter\] git rev-parse --abbrev-ref HEAD
[  +66 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] master
[        ] executing: [D:\Programmazione\Flutter\flutter\] git ls-remote --get-url origin
[  +62 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[        ] executing: [D:\Programmazione\Flutter\flutter\] git log -n 1 --pretty=format:%H
[  +63 ms] Exit code 0 from: git log -n 1 --pretty=format:%H
[        ] e99c881f8d0e63042af6e2a3f6182c3ca6967442
[        ] executing: [D:\Programmazione\Flutter\flutter\] git log -n 1 --pretty=format:%ar
[  +64 ms] Exit code 0 from: git log -n 1 --pretty=format:%ar
[   +1 ms] 3 days ago
[   +1 ms] executing: [D:\Programmazione\Flutter\flutter\] git describe --match v*.*.* --first-parent --long --tags
[  +84 ms] Exit code 0 from: git describe --match v*.*.* --first-parent --long --tags
[        ] v1.2.0-197-ge99c881
[ +193 ms] executing: D:\Local\Android\Sdk\platform-tools\adb devices -l
[  +37 ms] Exit code 0 from: D:\Local\Android\Sdk\platform-tools\adb devices -l
[        ] List of devices attached
           ce12160cdb9eac0f05     device product:hero2ltexx model:SM_G935F device:hero2lte transport_id:1
[ +255 ms] D:\Local\Android\Sdk\platform-tools\adb -s ce12160cdb9eac0f05 shell getprop
[ +128 ms] ro.hardware = samsungexynos8890
[ +839 ms] Launching lib/main.dart on SM G935F in debug mode...
[  +27 ms] Initializing gradle...
[   +2 ms] Using gradle from D:\Programmazione\Flutter\flutter_app\android\gradlew.bat.
[ +164 ms] executing: D:\Programmazione\Flutter\flutter_app\android\gradlew.bat -v
[ +968 ms]
                    ------------------------------------------------------------
                    Gradle 4.10.2
                    ------------------------------------------------------------

                    Build time:   2018-09-19 18:10:15 UTC
                    Revision:     b4d8d5d170bb4ba516e88d7fe5647e2323d791dd

                    Kotlin DSL:   1.0-rc-6
                    Kotlin:       1.2.61
                    Groovy:       2.4.15
                    Ant:          Apache Ant(TM) version 1.9.11 compiled on March 23 2018
                    JVM:          1.8.0_152-release (JetBrains s.r.o 25.152-b01)
                    OS:           Windows 10 10.0 amd64


[  +12 ms] "flutter run" took 2.489ms.
[        ] "flutter run" took 2.489ms.

Oops; flutter has exited unexpectedly.
Sending crash report to Google.
Crash report sent (report ID: d6ac79dde905bda6)
Crash report written to D:\Programmazione\Flutter\flutter_app\flutter_07.log;
please let us know at https://github.com/flutter/flutter/issues.
```

```
D:\Programmazione\Flutter\flutter_app>flutter doctor -v

[√] Flutter (Channel master, v1.2.1-pre.197, on Windows, locale it-IT)
    • Flutter version 1.2.1-pre.197 at D:\Programmazione\Flutter\flutter
    • Framework revision e99c881f8d (3 days ago), 2019-02-14 16:08:26 +0800
    • Engine revision 3757390fa4
    • Dart version 2.1.2 (build 2.1.2-dev.0.0 0a7dcf17eb)

[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at D:\Local\Android\Sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = D:\Local\Android\Sdk
    • Java binary at: D:\Programmi\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)
    • All Android licenses accepted.

[√] Android Studio (version 3.3)
    • Android Studio at D:\Programmi\Android\Android Studio
    • Flutter plugin version 33.0.1
    • Dart plugin version 182.5215
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)

[√] Connected device (1 available)
    • SM G935F • ce12160cdb9eac0f05 • android-arm64 • Android 8.0.0 (API 26)

• No issues found!
```

```
D:\Programmazione\Flutter\flutter_app>flutter packages get -v

[  +21 ms] executing: [D:\Programmazione\Flutter\flutter\] git rev-parse --abbrev-ref --symbolic @{u}
[  +66 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/master
[        ] executing: [D:\Programmazione\Flutter\flutter\] git rev-parse --abbrev-ref HEAD
[  +47 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[   +1 ms] master
[        ] executing: [D:\Programmazione\Flutter\flutter\] git ls-remote --get-url origin
[  +42 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[        ] executing: [D:\Programmazione\Flutter\flutter\] git log -n 1 --pretty=format:%H
[  +44 ms] Exit code 0 from: git log -n 1 --pretty=format:%H
[        ] e99c881f8d0e63042af6e2a3f6182c3ca6967442
[        ] executing: [D:\Programmazione\Flutter\flutter\] git log -n 1 --pretty=format:%ar
[  +45 ms] Exit code 0 from: git log -n 1 --pretty=format:%ar
[        ] 3 days ago
[        ] executing: [D:\Programmazione\Flutter\flutter\] git describe --match v*.*.* --first-parent --long --tags
[  +54 ms] Exit code 0 from: git describe --match v*.*.* --first-parent --long --tags
[        ] v1.2.0-197-ge99c881
[ +126 ms] Running "flutter packages get" in flutter_app...
[   +4 ms] Using D:\Programmazione\Flutter\flutter\.pub-cache for the pub cache.
[   +1 ms] executing: [D:\Programmazione\Flutter\flutter_app\] D:\Programmazione\Flutter\flutter\bin\cache\dart-sdk\bin\pub.bat --verbosity=warning --verbose get --no-precompile
[ +389 ms] Running "flutter packages get" in flutter_app... (completed in 0,4s)
[   +1 ms] "flutter get" took 493ms.
[        ] "flutter get" took 493ms.
pub get failed (1)

#0      throwToolExit (package:flutter_tools/src/base/common.dart:24:3)
#1      pub (package:flutter_tools/src/dart/pub.dart:170:5)
<asynchronous suspension>
#2      pubGet (package:flutter_tools/src/dart/pub.dart:104:13)
<asynchronous suspension>
#3      PackagesGetCommand._runPubGet (package:flutter_tools/src/commands/packages.dart:59:11)
<asynchronous suspension>
#4      PackagesGetCommand.runCommand (package:flutter_tools/src/commands/packages.dart:82:11)
<asynchronous suspension>
#5      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:545:18)
#6      _asyncThenWrapperHelper.<anonymous closure> (dart:async/runtime/libasync_patch.dart:77:64)
#7      _rootRunUnary (dart:async/zone.dart:1132:38)
#8      _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#9      _FutureListener.handleValue (dart:async/future_impl.dart:126:18)
#10     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:639:45)
#11     Future._propagateToListeners (dart:async/future_impl.dart:668:32)
#12     Future._complete (dart:async/future_impl.dart:473:7)
#13     _SyncCompleter.complete (dart:async/future_impl.dart:51:12)
#14     _AsyncAwaitCompleter.complete.<anonymous closure> (dart:async/runtime/libasync_patch.dart:33:20)
#15     _rootRun (dart:async/zone.dart:1124:13)
#16     _CustomZone.run (dart:async/zone.dart:1021:19)
#17     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:947:23)
#18     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#19     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#20     _runPendingImmediateCallback (dart:isolate/runtime/libisolate_patch.dart:115:13)
#21     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:172:5)
```

**Comment by kangwang1988** [comment]
Paste content for:
D:\Programmazione\Flutter\flutter_app\flutter_07.log

**Comment by kangwang1988** [comment]
Run commands below to get more details(get the packages)
```
cd D:\Programmazione\Flutter\flutter_app\
flutter packages get -v
```

**Comment by IvanTerrito** [comment]
D:\Programmazione\Flutter\flutter_app\flutter_07.log:

Flutter crash report; please file at https://github.com/flutter/flutter/issues.

## command

flutter run -v

## exception

ProcessException: ProcessException: Process "D:\Programmazione\Flutter\flutter_app\android\gradlew.bat" exited abnormally:

------------------------------------------------------------
Gradle 4.10.2
------------------------------------------------------------

Build time:   2018-09-19 18:10:15 UTC
Revision:     b4d8d5d170bb4ba516e88d7fe5647e2323d791dd

Kotlin DSL:   1.0-rc-6
Kotlin:       1.2.61
Groovy:       2.4.15
Ant:          Apache Ant(TM) version 1.9.11 compiled on March 23 2018
JVM:          1.8.0_152-release (JetBrains s.r.o 25.152-b01)
OS:           Windows 10 10.0 amd64


  Command: D:\Programmazione\Flutter\flutter_app\android\gradlew.bat -v

```
#0      runCheckedAsync (package:flutter_tools/src/base/process.dart:250:5)
<asynchronous suspension>
#1      _initializeGradle (package:flutter_tools/src/android/gradle.dart:210:9)
<asynchronous suspension>
#2      _ensureGradle (package:flutter_tools/src/android/gradle.dart:191:37)
<asynchronous suspension>
#3      _readGradleProject (package:flutter_tools/src/android/gradle.dart:119:31)
<asynchronous suspension>
#4      _gradleProject (package:flutter_tools/src/android/gradle.dart:111:34)
<asynchronous suspension>
#5      getGradleAppOut (package:flutter_tools/src/android/gradle.dart:105:29)
<asynchronous suspension>
#6      AndroidApk.fromAndroidProject (package:flutter_tools/src/application_package.dart:137:23)
<asynchronous suspension>
#7      ApplicationPackageFactory.getPackageForPlatform (package:flutter_tools/src/application_package.dart:37:32)
<asynchronous suspension>
#8      FlutterDevice.runHot (package:flutter_tools/src/resident_runner.dart:288:56)
<asynchronous suspension>
#9      HotRunner.run (package:flutter_tools/src/run_hot.dart:295:39)
<asynchronous suspension>
#10     RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:405:37)
<asynchronous suspension>
#11     FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:545:18)
#12     _asyncThenWrapperHelper.<anonymous closure> (dart:async/runtime/libasync_patch.dart:77:64)
#13     _rootRunUnary (dart:async/zone.dart:1132:38)
#14     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#15     _FutureListener.handleValue (dart:async/future_impl.dart:126:18)
#16     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:639:45)
#17     Future._propagateToListeners (dart:async/future_impl.dart:668:32)
#18     Future._complete (dart:async/future_impl.dart:473:7)
#19     _SyncCompleter.complete (dart:async/future_impl.dart:51:12)
#20     _AsyncAwaitCompleter.complete (dart:async/runtime/libasync_patch.dart:28:18)
#21     _completeOnAsyncReturn (dart:async/runtime/libasync_patch.dart:294:13)
#22     RunCommand.usageValues (package:flutter_tools/src/commands/run.dart)
#23     _asyncThenWrapperHelper.<anonymous closure> (dart:async/runtime/libasync_patch.dart:77:64)
#24     _rootRunUnary (dart:async/zone.dart:1132:38)
#25     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#26     _FutureListener.handleValue (dart:async/future_impl.dart:126:18)
#27     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:639:45)
#28     Future._propagateToListeners (dart:async/future_impl.dart:668:32)
#29     Future._complete (dart:async/future_impl.dart:473:7)
#30     _SyncCompleter.complete (dart:async/future_impl.dart:51:12)
#31     _AsyncAwaitCompleter.complete (dart:async/runtime/libasync_patch.dart:28:18)
#32     _completeOnAsyncReturn (dart:async/runtime/libasync_patch.dart:294:13)
#33     AndroidDevice.targetPlatform (package:flutter_tools/src/android/android_device.dart)
#34     _asyncThenWrapperHelper.<anonymous closure> (dart:async/runtime/libasync_patch.dart:77:64)
#35     _rootRunUnary (dart:async/zone.dart:1132:38)
#36     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#37     _FutureListener.handleValue (dart:async/future_impl.dart:126:18)
#38     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:639:45)
#39     Future._propagateToListeners (dart:async/future_impl.dart:668:32)
#40     Future._complete (dart:async/future_impl.dart:473:7)
#41     _SyncCompleter.complete (dart:async/future_impl.dart:51:12)
#42     _AsyncAwaitCompleter.complete.<anonymous closure> (dart:async/runtime/libasync_patch.dart:33:20)
#43     _rootRun (dart:async/zone.dart:1124:13)
#44     _CustomZone.run (dart:async/zone.dart:1021:19)
#45     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:947:23)
#46     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#47     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#48     _runPendingImmediateCallback (dart:isolate/runtime/libisolate_patch.dart:115:13)
#49     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:172:5)
```

## flutter doctor

```
[32m[✓][39m Flutter (Channel master, v1.2.1-pre.197, on Windows, locale it-IT)
    [32m•[39m Flutter version 1.2.1-pre.197 at D:\Programmazione\Flutter\flutter
    [32m•[39m Framework revision e99c881f8d (3 days ago), 2019-02-14 16:08:26 +0800
    [32m•[39m Engine revision 3757390fa4
    [32m•[39m Dart version 2.1.2 (build 2.1.2-dev.0.0 0a7dcf17eb)

[32m[✓][39m Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    [32m•[39m Android SDK at D:\Local\Android\Sdk
    [32m•[39m Android NDK location not configured (optional; useful for native profiling support)
    [32m•[39m Platform android-28, build-tools 28.0.3
    [32m•[39m ANDROID_HOME = D:\Local\Android\Sdk
    [32m•[39m Java binary at: D:\Programmi\Android\Android Studio\jre\bin\java
    [32m•[39m Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)
    [32m•[39m All Android licenses accepted.

[32m[✓][39m Android Studio (version 3.3)
    [32m•[39m Android Studio at D:\Programmi\Android\Android Studio
    [32m•[39m Flutter plugin version 33.0.1
    [32m•[39m Dart plugin version 182.5215
    [32m•[39m Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)

[32m[✓][39m Connected device (1 available)
    [32m•[39m SM G935F • ce12160cdb9eac0f05 • android-arm64 • Android 8.0.0 (API 26)

[32m•[39m No issues found!
```

Result for: cd D:\Programmazione\Flutter\flutter_app\
flutter packages get -v:

```
D:\Programmazione\Flutter\flutter_app>flutter packages get -v
[  +20 ms] executing: [D:\Programmazione\Flutter\flutter\] git rev-parse --abbrev-ref --symbolic @{u}
[  +76 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/master
[        ] executing: [D:\Programmazione\Flutter\flutter\] git rev-parse --abbrev-ref HEAD
[  +46 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] master
[        ] executing: [D:\Programmazione\Flutter\flutter\] git ls-remote --get-url origin
[  +45 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[        ] executing: [D:\Programmazione\Flutter\flutter\] git log -n 1 --pretty=format:%H
[  +45 ms] Exit code 0 from: git log -n 1 --pretty=format:%H
[        ] e99c881f8d0e63042af6e2a3f6182c3ca6967442
[        ] executing: [D:\Programmazione\Flutter\flutter\] git log -n 1 --pretty=format:%ar
[  +48 ms] Exit code 0 from: git log -n 1 --pretty=format:%ar
[        ] 3 days ago
[        ] executing: [D:\Programmazione\Flutter\flutter\] git describe --match v*.*.* --first-parent --long --tags
[  +58 ms] Exit code 0 from: git describe --match v*.*.* --first-parent --long --tags
[        ] v1.2.0-197-ge99c881
[ +134 ms] Running "flutter packages get" in flutter_app...
[   +4 ms] Using D:\Programmazione\Flutter\flutter\.pub-cache for the pub cache.
[   +1 ms] executing: [D:\Programmazione\Flutter\flutter_app\] D:\Programmazione\Flutter\flutter\bin\cache\dart-sdk\bin\pub.bat --verbosity=warning --verbose get --no-precompile
[ +294 ms] Running "flutter packages get" in flutter_app... (completed in 0,3s)
[   +1 ms] "flutter get" took 401ms.
[        ] "flutter get" took 401ms.
pub get failed (1)

#0      throwToolExit (package:flutter_tools/src/base/common.dart:24:3)
#1      pub (package:flutter_tools/src/dart/pub.dart:170:5)
<asynchronous suspension>
#2      pubGet (package:flutter_tools/src/dart/pub.dart:104:13)
<asynchronous suspension>
#3      PackagesGetCommand._runPubGet (package:flutter_tools/src/commands/packages.dart:59:11)
<asynchronous suspension>
#4      PackagesGetCommand.runCommand (package:flutter_tools/src/commands/packages.dart:82:11)
<asynchronous suspension>
#5      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:545:18)
#6      _asyncThenWrapperHelper.<anonymous closure> (dart:async/runtime/libasync_patch.dart:77:64)
#7      _rootRunUnary (dart:async/zone.dart:1132:38)
#8      _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#9      _FutureListener.handleValue (dart:async/future_impl.dart:126:18)
#10     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:639:45)
#11     Future._propagateToListeners (dart:async/future_impl.dart:668:32)
#12     Future._complete (dart:async/future_impl.dart:473:7)
#13     _SyncCompleter.complete (dart:async/future_impl.dart:51:12)
#14     _AsyncAwaitCompleter.complete.<anonymous closure> (dart:async/runtime/libasync_patch.dart:33:20)
#15     _rootRun (dart:async/zone.dart:1124:13)
#16     _CustomZone.run (dart:async/zone.dart:1021:19)
#17     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:947:23)
#18     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#19     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#20     _runPendingImmediateCallback (dart:isolate/runtime/libisolate_patch.dart:115:13)
#21     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:172:5)
```

**Comment by zoechi** [comment]
This is a follow up from #27905

**Comment by zoechi** [comment]
Please post again the output of `pub get -v` as explained in #27905

**Comment by IvanTerrito** [comment]
```
D:\Programmazione\Flutter\flutter_app>set FLUTTER_ROOT=D:\Programmazione\Flutter\flutter

D:\Programmazione\Flutter\flutter_app>pub get -v

FINE: Pub 2.1.0
IO  : Spawning "cmd /c ver" in D:\Programmazione\Flutter\flutter_app\.
IO  : Finished ver. Exit code 1.
    | stdout:
    | |
    | | Microsoft Windows [Versione 10.0.17134.590]
    | stderr:
MSG : Resolving dependencies...
SLVR: fact: flutter_app is 1.0.0+1
SLVR: derived: flutter_app
SLVR: fact: flutter_app depends on flutter any from sdk
SLVR:   selecting flutter_app
SLVR:   derived: flutter any from sdk
SLVR:   fact: flutter 0.0.0 from sdk depends on sky_engine any from sdk
SLVR:   fact: flutter 0.0.0 from sdk depends on vector_math 2.0.8
SLVR:   fact: flutter 0.0.0 from sdk depends on collection 1.14.11
SLVR:   fact: flutter 0.0.0 from sdk depends on typed_data 1.1.6
SLVR:   fact: flutter 0.0.0 from sdk depends on meta 1.1.6
SLVR:     selecting flutter 0.0.0 from sdk
SLVR:     derived: meta 1.1.6
SLVR:     derived: typed_data 1.1.6
SLVR:     derived: collection 1.14.11
SLVR:     derived: vector_math 2.0.8
SLVR:     derived: sky_engine any from sdk
SLVR:       selecting meta 1.1.6
SLVR:         selecting typed_data 1.1.6
SLVR:           selecting collection 1.14.11
SLVR:             selecting vector_math 2.0.8
SLVR:               selecting sky_engine 0.0.99 from sdk
SLVR: Version solving took 0:00:00.135564 seconds.
    | Tried 1 solutions.
FINE: Resolving dependencies finished (0.150s).
IO  : Writing 954 characters to text file .\pubspec.lock.
FINE: Contents:
    | # Generated by pub
    | # See https://www.dartlang.org/tools/pub/glossary#lockfile
    | packages:
    |   collection:
    |     dependency: transitive
    |     description:
    |       name: collection
    |       url: "https://pub.dartlang.org"
    |     source: hosted
    |     version: "1.14.11"
    |   flutter:
    |     dependency: "direct main"
    |     description: flutter
    |     source: sdk
    |     version: "0.0.0"
    |   meta:
    |     dependency: transitive
    |     description:
    |       name: meta
    |       url: "https://pub.dartlang.org"
    |     source: hosted
    |     version: "1.1.6"
    |   sky_engine:
    |     dependency: transitive
    |     description: flutter
    |     source: sdk
    |     version: "0.0.99"
    |   typed_data:
    |     dependency: transitive
    |     description:
    |       name: typed_data
    |       url: "https://pub.dartlang.org"
    |     source: hosted
    |     version: "1.1.6"
    |   vector_math:
    |     dependency: transitive
    |     description:
    |       name: vector_math
    |       url: "https://pub.dartlang.org"
    |     source: hosted
    |     version: "2.0.8"
    | sdks:
    |   dart: ">=2.1.0 <3.0.0"
MSG : Got dependencies!
IO  : Writing 638 characters to text file .\.packages.
FINE: Contents:
    | # Generated by pub on 2019-02-17 23:25:59.281137.
    | collection:file:///C:/Users/IvanT/AppData/Roaming/Pub/Cache/hosted/pub.dartlang.org/collection-1.14.11/lib/
    | flutter:file:///D:/Programmazione/Flutter/flutter/packages/flutter/lib/
    | meta:file:///C:/Users/IvanT/AppData/Roaming/Pub/Cache/hosted/pub.dartlang.org/meta-1.1.6/lib/
    | sky_engine:file:///D:/Programmazione/Flutter/flutter/bin/cache/pkg/sky_engine/lib/
    | typed_data:file:///C:/Users/IvanT/AppData/Roaming/Pub/Cache/hosted/pub.dartlang.org/typed_data-1.1.6/lib/
    | vector_math:file:///C:/Users/IvanT/AppData/Roaming/Pub/Cache/hosted/pub.dartlang.org/vector_math-2.0.8/lib/
    | flutter_app:lib/
```

From what I can understand it seems good, but still getting `pub get failed (1)` from Android Studio

**Comment by kangwang1988** [comment]
@IvanTerrito 
How about `D:\Programmazione\Flutter\flutter_app\android\gradlew.bat -v`
You can call it directly from the CMD and check the result.

**Comment by IvanTerrito** [comment]
here's the result:

```
------------------------------------------------------------
Gradle 4.10.2
------------------------------------------------------------

Build time:   2018-09-19 18:10:15 UTC
Revision:     b4d8d5d170bb4ba516e88d7fe5647e2323d791dd

Kotlin DSL:   1.0-rc-6
Kotlin:       1.2.61
Groovy:       2.4.15
Ant:          Apache Ant(TM) version 1.9.11 compiled on March 23 2018
JVM:          1.8.0_201 (Oracle Corporation 25.201-b09)
OS:           Windows 10 10.0 x86
```

**Comment by IvanTerrito** [comment]
No more help.. thank you very much.....
