### ISSUE TITLE
Provide a better error message when `builder == null` for MaterialPageRoute

### ISSUE THREAD

**Issue by ssb0** [flutter/flutter#28092]
## Steps to Reproduce

Navigating to a namedRoute using onGenerateRoute. parts[1] should not be null
```dart
      onGenerateRoute: (RouteSettings settings) {
        WidgetBuilder _builder;
        List<String> parts = settings.name.split("/");
        if (parts[0] == 'tallydetails') {
          _builder = (context) => TallySheet(title: parts[1]);
        }
        return new MaterialPageRoute(builder: _builder, settings: settings);
      },
```

## Logs
Here is the dump in vsCode
```
Launching lib\main.dart on Android SDK built for x86 in debug mode...
Built build\app\outputs\apk\debug\app-debug.apk.
I/flutter (20260): == snapshot
D/        (20260): HostConnection::get() New Host Connection established 0x9f317980, tid 20304
D/EGL_emulation(20260): eglMakeCurrent: 0x9c8134e0: ver 3 0 (tinfo 0x9f3032e0)
I/flutter (20260): ══╡ EXCEPTION CAUGHT BY GESTURE ╞═══════════════════════════════════════════════════════════════════
I/flutter (20260): The following assertion was thrown while handling a gesture:
I/flutter (20260): 'package:flutter/src/material/page.dart': Failed assertion: line 49 pos 15: 'builder != null': is
I/flutter (20260): not true.
I/flutter (20260): 
I/flutter (20260): Either the assertion indicates an error in the framework itself, or we should provide substantially
I/flutter (20260): more information in this error message to help you determine and fix the underlying cause.
I/flutter (20260): In either case, please report this assertion by filing a bug on GitHub:
I/flutter (20260):   https://github.com/flutter/flutter/issues/new?template=BUG.md
I/flutter (20260): 
I/flutter (20260): When the exception was thrown, this was the stack:
I/flutter (20260): #2      new MaterialPageRoute 
I/flutter (20260): #3      MyApp.build.<anonymous closure> 
I/flutter (20260): #4      _WidgetsAppState._onGenerateRoute 
I/flutter (20260): #5      NavigatorState._routeNamed 
I/flutter (20260): #6      NavigatorState.pushNamed 
I/flutter (20260): #7      new TallyView.<anonymous closure> 
I/flutter (20260): #8      _InkResponseState._handleTap 
I/flutter (20260): #9      _InkResponseState.build.<anonymous closure> 
I/flutter (20260): #10     GestureRecognizer.invokeCallback 
I/flutter (20260): #11     TapGestureRecognizer._checkUp 
I/flutter (20260): #12     TapGestureRecognizer.handlePrimaryPointer 
I/flutter (20260): #13     PrimaryPointerGestureRecognizer.handleEvent 
I/flutter (20260): #14     PointerRouter._dispatch 
I/flutter (20260): #15     PointerRouter.route 
I/flutter (20260): #16     _WidgetsFlutterBinding&BindingBase&GestureBinding.handleEvent 
I/flutter (20260): #17     _WidgetsFlutterBinding&BindingBase&GestureBinding.dispatchEvent 
I/flutter (20260): #18     _WidgetsFlutterBinding&BindingBase&GestureBinding._handlePointerEvent 
I/flutter (20260): #19     _WidgetsFlutterBinding&BindingBase&GestureBinding._flushPointerEventQueue 
I/flutter (20260): #20     _WidgetsFlutterBinding&BindingBase&GestureBinding._handlePointerDataPacket 
I/flutter (20260): #21     _invoke1 (dart:ui/hooks.dart:168:13)
I/flutter (20260): #22     _dispatchPointerDataPacket (dart:ui/hooks.dart:122:5)
I/flutter (20260): (elided 2 frames from class _AssertionError)
I/flutter (20260): 
I/flutter (20260): Handler: onTap
I/flutter (20260): Recognizer:
I/flutter (20260):   TapGestureRecognizer#55f95(debugOwner: GestureDetector, state: possible, won arena, finalPosition:
I/flutter (20260):   Offset(368.3, 637.6), sent tap down)
I/flutter (20260): ════════════════════════════════════════════════════════════════════════════════════════════════════
```

```
```

```
```

```
```

**Comment by ssb0** [comment]
Find the issue, not a bug. The builder was being set to null. You can close the bug or as you indicate provide more diagnostics.

**Comment by zoechi** [comment]
I'm going to close. I think the error message is pretty clear.
