### ISSUE TITLE
shared_preferences 安卓下无法使用

### ISSUE THREAD

**Issue by lijunen2009** [flutter/flutter#28106]
```
E/flutter ( 6822): [ERROR:flutter/shell/common/shell.cc(186)] Dart Error: Unhandled exception:
E/flutter ( 6822): MissingPluginException(No implementation found for method getAll on channel plugins.flutter.io/shared_preferences)
E/flutter ( 6822): #0      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:291:7)
E/flutter ( 6822): <asynchronous suspension>
E/flutter ( 6822): #1      SharedPreferences.getInstance (package:shared_preferences/shared_preferences.dart:28:27)
E/flutter ( 6822): <asynchronous suspension>
E/flutter ( 6822): #2      HomeState._init (package:fitness_app/views/home.dart:69:55)
E/flutter ( 6822): #3      _AsyncAwaitCompleter.start (dart:async/runtime/libasync_patch.dart:49:6)
E/flutter ( 6822): #4      HomeState._init (package:fitness_app/views/home.dart:57:8)
E/flutter ( 6822): #5      HomeState.initState (package:fitness_app/views/home.dart:41:5)
E/flutter ( 6822): #6      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3830:58)
E/flutter ( 6822): #7      ComponentElement.mount (package:flutter/src/widgets/framework.dart:3696:5)
E/flutter ( 6822): #8      Element.inflateWidget (package:flutter/src/widgets/framework.dart:2950:14)
E/flutter ( 6822): #9      Element.updateChild (package:flutter/src/widgets/framework.dart:2753:12)
E/flutter ( 6822): #10     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4860:14)
E/flutter ( 6822): #11     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2950:14)
E/flutter ( 6822): #12     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:12)
E/flutter ( 6822): #13     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3732:16)
E/flutter ( 6822): #14     Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
E/flutter ( 6822): #15     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3701:5)
E/flutter ( 6822): #16     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3696:5)
E/flutter ( 6822): #17     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2950:14)
E/flutter ( 6822): #18     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:12)
E/flutter ( 6822): #19     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4860:14)
E/flutter ( 6822): #20     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2950:14)
E/flutter ( 6822): #21     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:12)
E/flutter ( 6822): #22     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4860:14)
E/flutter ( 6822): #23     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2950:14)
E/flutter ( 6822): #24     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:12)
E/flutter ( 6822): #25     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4860:14)
E/flutter ( 6822): #26     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2950:14)
E/flutter ( 6822): #27     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:12)
E/flutter ( 6822): #28     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4860:14)
E/flutter ( 6822): #29     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2950:14)
E/flutter ( 6822): #30     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:12)
E/flutter ( 6822): #31     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3732:16)
E/flutter ( 6822): #32     Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
E/flutter ( 6822): #33     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3701:5)
E/flutter ( 6822): #34     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3848:11)
E/flutter ( 6822): #35     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3696:5)
E/flutter ( 6822): #36     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2950:14)
E/flutter ( 6822): #37     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:12)
E/flutter ( 6822): #38     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3732:16)
E/flutter ( 6822): #39     Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
E/flutter ( 6822): #40     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3701:5)
E/flutter ( 6822): #41     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3696:5)
E/flutter ( 6822): #42     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2950:14)
E/flutter ( 6822): #43     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:12)
E/flutter ( 6822): #44     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:373
```

**Comment by zoechi** [comment]
This looks like #24097 where it was used in a test. 

Please add the output of `flutter doctor -v`.

To investigate we would need a minimal runnable reproduction
as a single file so that we can just copy your code into `lib/main.dart` of a new project and run to reproduce.

**Comment by dnfield** [comment]
If you're getting this in a test or from a background isolate, this is expected.  As zoechi requested, can you add some details about how to reproduce this?
