### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by krutivijaysingh** [flutter/flutter#28111]
[flutter_10.log](https://github.com/flutter/flutter/files/2876985/flutter_10.log)

## Logs

Flutter crash report; please file at https://github.com/flutter/flutter/issues.

## command
```
flutter --no-color create --template app --description A new Flutter application. --org com.example flutter_appz
```
## exception
```
FileSystemException: FileSystemException: Cannot open file, path = 'C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2018.3.4\plugins\flutter\bin\cache\lockfile' (OS Error: Access is denied.
, errno = 5)
```
```
#0      _File.open.<anonymous closure> (dart:io/file_impl.dart:364:9)
#1      _rootRunUnary (dart:async/zone.dart:1132:38)
#2      _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#3      _FutureListener.handleValue (dart:async/future_impl.dart:126:18)
#4      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:639:45)
#5      Future._propagateToListeners (dart:async/future_impl.dart:668:32)
#6      Future._completeWithValue (dart:async/future_impl.dart:483:5)
#7      Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:513:7)
#8      _rootRun (dart:async/zone.dart:1124:13)
#9      _CustomZone.run (dart:async/zone.dart:1021:19)
#10     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:947:23)
#11     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#12     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#13     _runPendingImmediateCallback (dart:isolate/runtime/libisolate_patch.dart:115:13)
#14     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:172:5)
```

## flutter doctor

```
[✓] Flutter (Channel master, v1.2.2-pre.6, on Microsoft Windows [Version 6.3.9600], locale en-IN)
    • Flutter version 1.2.2-pre.6 at C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2018.3.4\plugins\flutter
    • Framework revision cb1c7a3664 (3 days ago), 2019-02-15 11:03:57 -0500
    • Engine revision 3757390fa4
    • Dart version 2.1.2 (build 2.1.2-dev.0.0 0a7dcf17eb)

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at C:\Users\kruti\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)
    • All Android licenses accepted.

[✓] Android Studio (version 3.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 33.0.1
    • Dart plugin version 182.5215
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)

[!] VS Code
    • VS Code at C:\Users\kruti\AppData\Local\Programs\Microsoft VS Code
    ✗ Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (1 available)
    • Lenovo A7020a48 • ? • android-arm64 • Android 6.0 (API 23)

! Doctor found issues in 1 category.
```

**Comment by dnfield** [comment]
It looks like you have something preventing you from accessing an IDE file.  Are you able to reproduce this consistently?

I'm not sure about how IntelliJ works with this, but I suspect you want your plugin stored somewhere __outside__ of %PROGRAMFILES%, as I believe that requires administrative access.  Otherwise, try running IntelliJ as admin.

**Comment by dnfield** [comment]
Also - I edited the log into your issue, but in the future please paste the actual log test rather than uplaoding the log file.  It makes it easier to address and triage your issue.  Thanks!

**Comment by zoechi** [comment]
This sounds like you installed **Flutter** into `C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2018.3.4\plugins\flutter` which is not supported because `C:\Program Files` requires elevated privileges as mentioned above. Also installing Flutter into the IDE install directory doesn't seem like a good idea.

See also https://flutter.io/docs/get-started/install/windows#get-the-flutter-sdk

> do not install Flutter in a directory like C:\Program Files\ that requires elevated privileges
