### ISSUE TITLE
iOS app crash after updating to latest version of flutterFire plugins

### ISSUE THREAD

**Issue by Theunodb** [flutter/flutter#28199]
## Steps to Reproduce
1. Create new flutter project 

2. Add flutterFire plugings:
```yml
  firebase_core: ^0.3.0+2
  firebase_auth: ^0.8.1+1
  firebase_messaging: ^3.0.1
  firebase_analytics: ^2.0.1
  firebase_storage: ^2.0.1+1
  firebase_performance: ^0.1.0+2
  cloud_firestore: ^0.9.0+2
```

3. Initialise firebase

```dart
initFirebase() async {
    final FirebaseApp app = await FirebaseApp.configure(
      name: fb_app_name,
      options: new FirebaseOptions(
        googleAppID: Platform.isIOS ? fb_googleAppID_ios : fb_googleAppID_android,
        gcmSenderID: fb_gcmSenderID,
        apiKey: fb_apiKey,
        projectID: fb_projectID,
        bundleID: fb_bundleID,
      ),
    );
    firestore = new Firestore(app: app);
    firestore.settings(
      persistenceEnabled: true,
      timestampsInSnapshotsEnabled: true,
    );
  }
```
4. Run the app

## Logs
```
*** First throw call stack:
(
        0   CoreFoundation                      0x00000001088341bb __exceptionPreprocess + 331
        1   libobjc.A.dylib                     0x0000000107dd2735 objc_exception_throw + 48
        2   CoreFoundation                      0x00000001087804ec _CFThrowFormattedException + 194
        3   CoreFoundation                      0x00000001088a3541 -[__NSPlaceholderDictionary initWithObjects:forKeys:count:] + 321
        4   CoreFoundation                      0x000000010882fc9b +[NSDictionary dictionaryWithObjects:forKeys:count:] + 59
        5   Runner                              0x0000000103becb69 getDictionaryFromFIRApp + 217
        6   Runner                              0x0000000103bec9b1 -[FLTFirebaseCorePlugin handleMethodCall:result:] + 4225
        7   Flutter                             0x0000000105a845fa __45-[Flutt<…>
Lost connection to device.    

```
```

[✓] Flutter (Channel beta, v1.1.8, on Mac OS X 10.14.2 18C54, locale en-ZA)
    • Flutter version 1.1.8 at /Users/td0810/flutter
    • Framework revision 985ccb6d14 (6 weeks ago), 2019-01-08 13:45:55 -0800
    • Engine revision 7112b72cc2
    • Dart version 2.1.1 (build 2.1.1-dev.0.1 ec86471ccc)

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/td0810/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Library/Java/JavaVirtualMachines/jdk1.8.0_121.jdk/Contents/Home/bin/java
    • Java version Java(TM) SE Runtime Environment (build 1.8.0_121-b13)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.1, Build version 10B61
    • ios-deploy 1.9.4
    • CocoaPods version 1.6.0

[✓] Android Studio (version 3.3.1)
    • Android Studio at /Users/td0810/Applications/JetBrains Toolbox/Android Studio.app/Contents
    • Flutter plugin version 33.0.1
    • Dart plugin version 182.5215
    • Try updating or re-installing Android Studio.

[✓] IntelliJ IDEA Ultimate Edition (version 2018.3.4)
    • IntelliJ at /Users/td0810/Applications/JetBrains Toolbox/IntelliJ IDEA Ultimate.app
    • Flutter plugin version 33.0.6
    • Dart plugin version 183.5901

[✓] VS Code (version 1.31.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 2.19.0

[✓] Connected device (1 available)
    • iPhone Xs Max • F162F6BE-6800-47E6-B704-7EE1C61045C5 • ios • iOS 12.1 (simulator)
```

## Files
[main.dart.zip](https://github.com/flutter/flutter/files/2883916/main.dart.zip)
[pubspec.yaml.zip](https://github.com/flutter/flutter/files/2883920/pubspec.yaml.zip)

**Comment by zoechi** [comment]
Have you tried if it still reproduces in `master` channel?

**Comment by Theunodb** [comment]
Yes this also occurs in the master channel.

## doctor
[✓] Flutter (Channel master, v1.2.2-pre.22, on Mac OS X 10.14.2 18C54, locale en-ZA)
    • Flutter version 1.2.2-pre.22 at /Users/td0810/flutter
    • Framework revision dd23be3936 (4 hours ago), 2019-02-19 21:35:31 -0800
    • Engine revision f45572e95f
    • Dart version 2.1.2 (build 2.1.2-dev.0.0 c92d5ca288)

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/td0810/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Users/td0810/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/182.5264788/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.1, Build version 10B61
    • ios-deploy 1.9.4
    • CocoaPods version 1.6.0

[✓] Android Studio (version 3.3)
    • Android Studio at /Users/td0810/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/182.5264788/Android Studio.app/Contents
    • Flutter plugin version 33.0.1
    • Dart plugin version 182.5215
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)

[✓] IntelliJ IDEA Ultimate Edition (version 2018.3.4)
    • IntelliJ at /Users/td0810/Applications/JetBrains Toolbox/IntelliJ IDEA Ultimate.app
    • Flutter plugin version 33.0.6
    • Dart plugin version 183.5901

[✓] VS Code (version 1.31.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 2.19.0

[✓] Connected device (1 available)
    • iPhone Xs Max • F162F6BE-6800-47E6-B704-7EE1C61045C5 • ios • iOS 12.1 (simulator)


## logs
```
[  +31 ms] *** First throw call stack:
[        ] (
[        ]      0   CoreFoundation                      0x000000010ff5c1bb __exceptionPreprocess + 331
[        ]      1   libobjc.A.dylib                     0x000000010f4fa735 objc_exception_throw + 48
[        ]      2   CoreFoundation                      0x000000010fea84ec _CFThrowFormattedException + 194
[        ]      3   CoreFoundation                      0x000000010ffcb541 -[__NSPlaceholderDictionary initWithObjects:forKeys:count:] + 321
[        ]      4   CoreFoundation                      0x000000010ff57c9b +[NSDictionary dictionaryWithObjects:forKeys:count:] + 59
[        ]      5   Runner                              0x000000010c7bbf59 getDictionaryFromFIRApp + 217
[        ]      6   Runner                              0x000000010c7bbda1 -[FLTFirebaseCorePlugin handleMethodCall:result:] + 4225
[        ]      7   Flutter                             0x000000010d1693ba __45-[Flutt<…>

```
```
#0      throwToolExit (package:flutter_tools/src/base/common.dart:24:3)
#1      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:418:7)
<asynchronous suspension>
#2      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:545:18)
#3      _asyncThenWrapperHelper.<anonymous closure> (dart:async/runtime/libasync_patch.dart:77:64)
#4      _rootRunUnary (dart:async/zone.dart:1132:38)
#5      _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#6      _FutureListener.handleValue (dart:async/future_impl.dart:126:18)
#7      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:639:45)
#8      Future._propagateToListeners (dart:async/future_impl.dart:668:32)
#9      Future._complete (dart:async/future_impl.dart:473:7)
#10     _SyncCompleter.complete (dart:async/future_impl.dart:51:12)
#11     _AsyncAwaitCompleter.complete (dart:async/runtime/libasync_patch.dart:28:18)
#12     _completeOnAsyncReturn (dart:async/runtime/libasync_patch.dart:294:13)
#13     RunCommand.usageValues (package:flutter_tools/src/commands/run.dart)
#14     _asyncThenWrapperHelper.<anonymous closure> (dart:async/runtime/libasync_patch.dart:77:64)
#15     _rootRunUnary (dart:async/zone.dart:1132:38)
#16     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#17     _FutureListener.handleValue (dart:async/future_impl.dart:126:18)
#18     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:639:45)
#19     Future._propagateToListeners (dart:async/future_impl.dart:668:32)
#20     Future._complete (dart:async/future_impl.dart:473:7)
#21     _SyncCompleter.complete (dart:async/future_impl.dart:51:12)
#22     _AsyncAwaitCompleter.complete.<anonymous closure> (dart:async/runtime/libasync_patch.dart:33:20)
#23     _rootRun (dart:async/zone.dart:1124:13)
#24     _CustomZone.run (dart:async/zone.dart:1021:19)
#25     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:947:23)
#26     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#27     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#28     _runPendingImmediateCallback (dart:isolate/runtime/libisolate_patch.dart:115:13)
#29     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:172:5)
```

**Comment by AleciaVermeulen** [comment]
I am also having the same problem. 
When running this in xcode it breaks at: 

```
static NSDictionary *getDictionaryFromFIRApp(FIRApp *app) {
  return @{@"name" : app.name, @"options" : getDictionaryFromFIROptions(app.options)};
} 
```

##logs
```
*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '*** -[__NSPlaceholderDictionary initWithObjects:forKeys:count:]: attempt to insert nil object from objects[0]'

```

**Comment by joshuaferguson** [comment]
I'm experiencing the same crash. Any workarounds?

**Comment by trey-rosius** [comment]
This piece of code works well on android, but crashes on ios.
```
 onTap:(){
              Navigator.push(
                    context,
                    new MaterialPageRoute(
                      builder: (context) => new AddBasicInformation(),
                    ));
                    
              },
```

```
static NSDictionary *getDictionaryFromFIRApp(FIRApp *app) {
  return @{@"name" : app.name, @"options" : getDictionaryFromFIROptions(app.options)};
}
```

```
 *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '*** -[__NSPlaceholderDictionary initWithObjects:forKeys:count:]: attempt to insert nil object from objects[0]'
*** First throw call stack:
```
Since i updated my app plugins and ability to use AndroidX, i've been getting an endless number of issues to deal with

**Comment by joshuaferguson** [comment]
Looks like this crash was caused by https://github.com/flutter/plugins/pull/1226

If you revert FirebaseCorePlugin.m to the previous version it no longer crashes. I can't speak to any other issues it may cause but it appears to be running fine?

**Comment by ffeu** [comment]
This issue is solved by this [PR](https://github.com/flutter/plugins/pull/1279) and `firebase_core` version `0.3.1+1`. It may be closed now.

**Comment by zoechi** [comment]
@Theunodb the issue should be fixed. Please let us know if you are still seeing this.

**Comment by Theunodb** [comment]
I can confirm that its working without any issues! Thank you for the prompt action to get this resolved!

**Comment by kroikie** [comment]
@Theunodb

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/426. Any further collaboration will be done there.
