### ISSUE TITLE
Problem with Image Picker

### ISSUE THREAD

**Issue by samycodes** [flutter/flutter#28203]
I am using image_picker: 0.4.12+1 in my app, when I click on the upload Image button this code triggers

```
selectImage() async {
    try {
      galleryImage = await ImagePicker.pickImage(source: ImageSource.gallery);
      setState(() {
        imageSelected = true;
      });
    } catch (e) {
      print(e.message);
    }
  }
```
When I click on the button is show the screen to choose image and when I press back button without choosing image it shows error.
A Red screen prompt with error.

Here is error from console

```
I/flutter ( 8986): ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
I/flutter ( 8986): The following assertion was thrown building UpdateProfile(dirty, state: _UpdateProfile#39206):
I/flutter ( 8986): 'package:flutter/src/painting/image_provider.dart': Failed assertion: line 528 pos 16: 'file !=
I/flutter ( 8986): null': is not true.
I/flutter ( 8986): Either the assertion indicates an error in the framework itself, or we should provide substantially
I/flutter ( 8986): more information in this error message to help you determine and fix the underlying cause.
I/flutter ( 8986): In either case, please report this assertion by filing a bug on GitHub:
I/flutter ( 8986):   https://github.com/flutter/flutter/issues/new?template=BUG.md
I/flutter ( 8986): When the exception was thrown, this was the stack:
I/flutter ( 8986): #2      new FileImage (package:flutter/src/painting/image_provider.dart:528:16)
I/flutter ( 8986): #3      _UpdateProfile.build (package:tripmate/pages/update_profile.dart:53:29)
I/flutter ( 8986): #4      StatefulElement.build (package:flutter/src/widgets/framework.dart:3809:27)
I/flutter ( 8986): #5      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3721:15)
I/flutter ( 8986): #6      Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
I/flutter ( 8986): #7      BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2286:33)
I/flutter ( 8986): #8      _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding&WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:676:20)
I/flutter ( 8986): #9      _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:219:5)
I/flutter ( 8986): #10     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:990:15)
I/flutter ( 8986): #11     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:930:9)
I/flutter ( 8986): #12     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:842:5)
I/flutter ( 8986): #13     _invoke (dart:ui/hooks.dart:159:13)
I/flutter ( 8986): #14     _drawFrame (dart:ui/hooks.dart:148:3)
I/flutter ( 8986): (elided 2 frames from class _AssertionError)
I/flutter ( 8986): ════════════════════════════════════════════════════════════════════════════════════════════════════

```
Please help me with this.

**Comment by msal4** [comment]
If you don't select an image `galleryImage` will be `null`, in that case you have to check if it's null.
```dart
if (galleryImage != null) setState(() => imageSelected = true);
```

**Comment by samycodes** [comment]
> If you don't select an image `galleryImage` will be `null`, in that case you have to check if it's null.
> 
> ```dart
> if (galleryImage != null) setState(() => imageSelected = true);
> ```

Wow Thanks bro,
The problem is solved.

**Comment by msal4** [comment]
@samycodes you're welcome!
