### ISSUE TITLE
Firebase Auth crashes asking for AndroidManifest.xml metadata

### ISSUE THREAD

**Issue by feinstein** [flutter/flutter#28219]
I am running the following code in an Android Emulator with Google Play services (Pixel 5X):

```dart
  Future<FirebaseUser> _signInWithGoogle() async {
    final GoogleSignInAccount googleUser = await _googleSignIn.signIn();
    final GoogleSignInAuthentication googleAuth = await googleUser.authentication;
    final AuthCredential credential = GoogleAuthProvider.getCredential(
      accessToken: googleAuth.accessToken,
      idToken: googleAuth.idToken,
    );
    final FirebaseUser user = await _auth.signInWithCredential(credential);

    return user;
  }
```

And then I get the following error:
```
E/AndroidRuntime( 6592): FATAL EXCEPTION: GoogleApiHandler
E/AndroidRuntime( 6592): java.lang.IllegalStateException: 
```

```
A required meta-data tag in your app's AndroidManifest.xml does not exist.  You must have the following declaration within the <application> element:     <meta-data android:name="com.google.android.gms.version" android:value="@integer/google_play_services_version" />
````

```
E/AndroidRuntime( 6592): 	at com.google.android.gms.common.GooglePlayServicesUtilLight.isGooglePlayServicesAvailable(Unknown Source)
E/AndroidRuntime( 6592): 	at com.google.android.gms.common.GoogleApiAvailabilityLight.isGooglePlayServicesAvailable(Unknown Source)
E/AndroidRuntime( 6592): 	at com.google.android.gms.common.GoogleApiAvailability.isGooglePlayServicesAvailable(Unknown Source)
E/AndroidRuntime( 6592): 	at com.google.android.gms.common.internal.GoogleApiAvailabilityCache.getClientAvailability(Unknown Source)
E/AndroidRuntime( 6592): 	at com.google.android.gms.common.api.internal.GoogleApiManager$zaa.connect(Unknown Source)
E/AndroidRuntime( 6592): 	at com.google.android.gms.common.api.internal.GoogleApiManager.zab(Unknown Source)
E/AndroidRuntime( 6592): 	at com.google.android.gms.common.api.internal.GoogleApiManager.handleMessage(Unknown Source)
E/AndroidRuntime( 6592): 	at android.os.Handler.dispatchMessage(Handler.java:98)
E/AndroidRuntime( 6592): 	at android.os.Looper.loop(Looper.java:135)
E/AndroidRuntime( 6592): 	at android.os.HandlerThread.run(HandlerThread.java:61)
E/MethodChannel#plugins.flutter.io/google_sign_in( 6592): Failed to handle method call
E/MethodChannel#plugins.flutter.io/google_sign_in( 6592)`: java.lang.IllegalStateException: A required meta-data tag in your app's AndroidManifest.xml does not exist.  You must have the following declaration within the <application> element:     <meta-data android:name="com.google.android.gms.version" android:value="@integer/google_play_services_version" />`
E/MethodChannel#plugins.flutter.io/google_sign_in( 6592): 	at com.google.android.gms.common.GooglePlayServicesUtilLight.isGooglePlayServicesAvailable(Unknown Source)
E/MethodChannel#plugins.flutter.io/google_sign_in( 6592): 	at com.google.android.gms.common.GoogleApiAvailabilityLight.isGooglePlayServicesAvailable(Unknown Source)
```

This only appears when I run my app using the Flutter tools under IntelliJ IDEA, but if I open the Android project itself under Android Studio, I can run the app normally and the Sign-In screen appears.

**Are there any `Manifest.xml` configurations missing from the [Firebase Auth plugin instructions](https://pub.dartlang.org/packages/firebase_auth#-readme-tab-)?**

**Comment by zoechi** [comment]
> Are there any `Manifest.xml` configurations missing from the [Firebase Auth plugin instructions](https://pub.dartlang.org/packages/firebase_auth#-readme-tab-)?

I don't think so. Sounds more you `Manifest.xml` has some syntax error.
Can you please post the content?

**Comment by feinstein** [comment]
As you can see I added `<meta-data android:name="com.google.android.gms.version" android:value="@integer/google_play_services_version" />` in order for it to work.

```
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    package="com.myapp">

    <!-- The INTERNET permission is required for development. Specifically,
         flutter needs it to communicate with the running application
         to allow setting breakpoints, to provide hot reload, etc.
    -->
    <uses-permission android:name="android.permission.INTERNET"/>

    <!-- io.flutter.app.FlutterApplication is an android.app.Application that
         calls FlutterMain.startInitialization(this); in its onCreate method.
         In most cases you can leave this as-is, but you if you want to provide
         additional functionality it is fine to subclass or reimplement
         FlutterApplication and put your custom class here. -->
    <application
        android:name="io.flutter.app.FlutterApplication"
        android:label="my_app"
        android:icon="@mipmap/ic_launcher">
        <activity
            android:name=".MainActivity"
            android:launchMode="singleTop"
            android:theme="@style/LaunchTheme"
            android:configChanges="orientation|keyboardHidden|keyboard|screenSize|locale|layoutDirection|fontScale|screenLayout|density"
            android:hardwareAccelerated="true"
            android:windowSoftInputMode="adjustResize">
            <!-- This keeps the window background of the activity showing
                 until Flutter renders its first frame. It can be removed if
                 there is no splash screen (such as the default splash screen
                 defined in @style/LaunchTheme). -->
            <meta-data
                android:name="io.flutter.app.android.SplashScreenUntilFirstFrame"
                android:value="true" />
            <intent-filter>
                <action android:name="android.intent.action.MAIN"/>
                <category android:name="android.intent.category.LAUNCHER"/>
            </intent-filter>
        </activity>

        <meta-data android:name="com.google.android.gms.version" android:value="@integer/google_play_services_version" />

        <meta-data android:name="com.facebook.sdk.ApplicationId"
                   android:value="@string/facebook_app_id"/>

        <activity android:name="com.facebook.FacebookActivity"
                  android:configChanges=
                          "keyboard|keyboardHidden|screenLayout|screenSize|orientation"
                  android:label="@string/app_name" />
        <activity
                android:name="com.facebook.CustomTabActivity"
                android:exported="true">
            <intent-filter>
                <action android:name="android.intent.action.VIEW" />
                <category android:name="android.intent.category.DEFAULT" />
                <category android:name="android.intent.category.BROWSABLE" />
                <data android:scheme="@string/fb_login_protocol_scheme" />
            </intent-filter>
        </activity>
    </application>
</manifest>
```

**Comment by zoechi** [comment]
Have you tried `flutter clean`?

**Comment by feinstein** [comment]
I will

**Comment by nilsmagnus** [comment]
`flutter clean` solved it for me as well

**Comment by eozbaysar** [comment]
> Have you tried `flutter clean`?
it solved my problem.

**Comment by minhvuongrbs** [comment]
`flutter clean` is amazing command for me
