### ISSUE TITLE
flutter run with missing Runner.xcodeproj/project.pbxproj file results in flutter crash...

### ISSUE THREAD

**Issue by kf6gpe** [flutter/flutter#28231]
I'd expect an error of some sort, but instead `flutter run` just fails:
```
Running "flutter packages get" in zapmap...                         1.6s
Launching lib/main.dart on iPhone XS Max in debug mode...

Oops; flutter has exited unexpectedly.
Sending crash report to Google.
Crash report sent (report ID: a3f75c0cb8ff36a2)
Crash report written to /Users/rischpater/Downloads/zapmap/zapmap/flutter_01.log;
please let us know at https://github.com/flutter/flutter/issues.
rischpater-macbookair:~/Downloads/zapmap/zapmap
```

Here's the crash report:

Flutter crash report; please file at https://github.com/flutter/flutter/issues.

## command

flutter run

## exception
```
FileSystemException: FileSystemException: Cannot open file, path = '/Users/rischpater/Downloads/zapmap/zapmap/ios/Runner.xcodeproj/project.pbxproj' (OS Error: No such file or directory, errno = 2)
```

```
#0      _File.open.<anonymous closure> (dart:io/file_impl.dart:364:9)
#1      _rootRunUnary (dart:async/zone.dart:1132:38)
#2      _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#3      _FutureListener.handleValue (dart:async/future_impl.dart:126:18)
#4      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:639:45)
#5      Future._propagateToListeners (dart:async/future_impl.dart:668:32)
#6      Future._completeWithValue (dart:async/future_impl.dart:483:5)
#7      Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:513:7)
#8      _rootRun (dart:async/zone.dart:1124:13)
#9      _CustomZone.run (dart:async/zone.dart:1021:19)
#10     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:947:23)
#11     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#12     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#13     _runPendingImmediateCallback (dart:isolate/runtime/libisolate_patch.dart:115:13)
#14     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:172:5)
```

**Comment by boylenssen** [comment]
I fixed this by running `flutter create .` in the projects directory

**Comment by QOFOL** [comment]
use
Flutter run

**Comment by vtrikoupis** [comment]
This is fundamental, it should be allowed, whether through pubspec.yaml, or info.plist/manifest to edit Runner so that flutter run knows the project name has changed.

**Comment by Sagarsappic** [comment]
> I fixed this by running `flutter create .` in the projects directory. This seems to repair it.

I was frusted by this error but it helps me ........thank you very much for this answer
