### ISSUE TITLE
How to fix this error?

### ISSUE THREAD

**Issue by bhanuka96** [flutter/flutter#28244]
Flutter crash report; please file at https://github.com/flutter/flutter/issues.

## command
```
flutter build bundle --suppress-analytics --target C:\Users\Bhanuka.Q2SOFT\AndroidStudioProjects\reborn_next_job02-19-2-home-Login_not_working-master-master\reborn_next_job02-19-2-home-Login_not_working-master-master\lib\main.dart --track-widget-creation --target-platform android-arm64 --depfile C:\Users\Bhanuka.Q2SOFT\AndroidStudioProjects\reborn_next_job02-19-2-home-Login_not_working-master-master\reborn_next_job02-19-2-home-Login_not_working-master-master\build\app\intermediates\flutter\debug/snapshot_blob.bin.d --asset-dir C:\Users\Bhanuka.Q2SOFT\AndroidStudioProjects\reborn_next_job02-19-2-home-Login_not_working-master-master\reborn_next_job02-19-2-home-Login_not_working-master-master\build\app\intermediates\flutter\debug/flutter_assets --debug
```
## exception
```
FileSystemException: FileSystemException: Creation failed, path = 'C:\Users\Bhanuka.Q2SOFT\AndroidStudioProjects\reborn_next_job02-19-2-home-Login_not_working-master-master\reborn_next_job02-19-2-home-Login_not_working-master-master\build\app\intermediates\flutter\debug/flutter_assets\packages/cupertino_icons/assets' (OS Error: The filename or extension is too long.
, errno = 206)
```
```
#0      _Directory.createSync (dart:io/directory_impl.dart:140:7)
#1      _LocalDirectory&LocalFileSystemEntity&ForwardingDirectory.createSync (package:file/src/forwarding/forwarding_directory.dart:22:16)
#2      writeBundle.<anonymous closure> (package:flutter_tools/src/bundle.dart:208:17)
<asynchronous suspension>
#3      MappedIterator.moveNext (dart:_internal/iterable.dart:392:18)
#4      Future.wait (dart:async/future.dart:392:26)
#5      writeBundle (package:flutter_tools/src/bundle.dart:205:16)
#6      _AsyncAwaitCompleter.start (dart:async/runtime/libasync_patch.dart:49:6)
#7      writeBundle (package:flutter_tools/src/bundle.dart:199:25)
#8      assemble (package:flutter_tools/src/bundle.dart:195:9)
#9      _AsyncAwaitCompleter.start (dart:async/runtime/libasync_patch.dart:49:6)
#10     assemble (package:flutter_tools/src/bundle.dart:163:22)
#11     build (package:flutter_tools/src/bundle.dart:128:9)
#12     _asyncThenWrapperHelper.<anonymous closure> (dart:async/runtime/libasync_patch.dart:77:64)
#13     _rootRunUnary (dart:async/zone.dart:1132:38)
#14     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#15     _FutureListener.handleValue (dart:async/future_impl.dart:129:18)
#16     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:642:45)
#17     Future._propagateToListeners (dart:async/future_impl.dart:671:32)
#18     Future._complete (dart:async/future_impl.dart:476:7)
#19     _SyncCompleter.complete (dart:async/future_impl.dart:51:12)
#20     _AsyncAwaitCompleter.complete (dart:async/runtime/libasync_patch.dart:28:18)
#21     _completeOnAsyncReturn (dart:async/runtime/libasync_patch.dart:295:13)
#22     buildAssets (package:flutter_tools/src/bundle.dart)
#23     _asyncThenWrapperHelper.<anonymous closure> (dart:async/runtime/libasync_patch.dart:77:64)
#24     _rootRunUnary (dart:async/zone.dart:1132:38)
#25     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#26     _FutureListener.handleValue (dart:async/future_impl.dart:129:18)
#27     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:642:45)
#28     Future._propagateToListeners (dart:async/future_impl.dart:671:32)
#29     Future._complete (dart:async/future_impl.dart:476:7)
#30     _SyncCompleter.complete (dart:async/future_impl.dart:51:12)
#31     _AsyncAwaitCompleter.complete (dart:async/runtime/libasync_patch.dart:28:18)
#32     _completeOnAsyncReturn (dart:async/runtime/libasync_patch.dart:295:13)
#33     _ManifestAssetBundle.build (package:flutter_tools/src/asset.dart)
#34     _asyncThenWrapperHelper.<anonymous closure> (dart:async/runtime/libasync_patch.dart:77:64)
#35     _rootRunUnary (dart:async/zone.dart:1132:38)
#36     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#37     _FutureListener.handleValue (dart:async/future_impl.dart:129:18)
#38     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:642:45)
#39     Future._propagateToListeners (dart:async/future_impl.dart:671:32)
#40     Future._complete (dart:async/future_impl.dart:476:7)
#41     _SyncCompleter.complete (dart:async/future_impl.dart:51:12)
#42     _AsyncAwaitCompleter.complete (dart:async/runtime/libasync_patch.dart:28:18)
#43     _completeOnAsyncReturn (dart:async/runtime/libasync_patch.dart:295:13)
#44     _obtainLicenses (package:flutter_tools/src/asset.dart)
#45     _asyncThenWrapperHelper.<anonymous closure> (dart:async/runtime/libasync_patch.dart:77:64)
#46     _rootRunUnary (dart:async/zone.dart:1132:38)
#47     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#48     _FutureListener.handleValue (dart:async/future_impl.dart:129:18)
#49     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:642:45)
#50     Future._propagateToListeners (dart:async/future_impl.dart:671:32)
#51     Future._completeWithValue (dart:async/future_impl.dart:486:5)
#52     Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:516:7)
#53     _rootRun (dart:async/zone.dart:1124:13)
#54     _CustomZone.run (dart:async/zone.dart:1021:19)
#55     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:947:23)
#56     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#57     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#58     _runPendingImmediateCallback (dart:isolate/runtime/libisolate_patch.dart:115:13)
#59     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:172:5)
```

## flutter doctor

```
[✓] Flutter (Channel stable, v1.0.0, on Microsoft Windows [Version 10.0.17134.556], locale en-US)
    • Flutter version 1.0.0 at C:\src\flutter
    • Framework revision 5391447fae (3 months ago), 2018-11-29 19:41:26 -0800
    • Engine revision 7375a0f414
    • Dart version 2.1.0 (build 2.1.0-dev.9.4 f9ebf21297)

[✓] Android toolchain - develop for Android devices (Android SDK 28.0.3)
    • Android SDK at C:/Users/Bhanuka.Q2SOFT/AppData/Local/Android/Sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = C:/Users/Bhanuka.Q2SOFT/AppData/Local/Android/Sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)
    • All Android licenses accepted.

[✓] Android Studio (version 3.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 33.1.1
    • Dart plugin version 182.5215
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)

[✓] VS Code (version 1.30.2)
    • VS Code at C:\Users\Bhanuka.Q2SOFT\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 2.23.0

[✓] Connected device (1 available)
    • PRA LX2 • 6MU7N17A12000618 • android-arm64 • Android 8.0.0 (API 26)

• No issues found!
```
```
Oops; flutter has exited unexpectedly.
Crash report written to C:\Users\Bhanuka.Q2SOFT\AndroidStudioProjects\reborn_next_job02-19-2-home-Login_not_working-master-master\reborn_next_job02-19-2-home-Login_not_working-master-master\flutter_14.log;
please let us know at https://github.com/flutter/flutter/issues.
         *********************************************************
WARNING: This version of share will break your Android build if it or its dependencies aren't compatible with AndroidX.
         See https://goo.gl/CP92wY for more information on the problem and how to fix it.
         This warning prints for all Android build failures. The real root cause of the error may be unrelated.
         *********************************************************
Finished with error: Gradle task assembleDebug failed with exit code 1
```

**Comment by zoechi** [comment]
> FileSystemException: FileSystemException: Creation failed, path = 'C:\Users\Bhanuka.Q2SOFT\AndroidStudioProjects\reborn_next_job02-19-2-home-Login_not_working-master-master\reborn_next_job02-19-2-home-Login_not_working-master-master\build\app\intermediates\flutter\debug/flutter_assets\packages/cupertino_icons/assets' (OS Error: The filename or extension is too long.
, errno = 206)

Says it all. Rename `reborn_next_job02-19-2-home-Login_not_working-master-master\reborn_next_job02-19-2-home-Login_not_working-master-master` to a shorter name.
