### ISSUE TITLE
Unable to Create new projects through command line

### ISSUE THREAD

**Issue by Anooppakki** [flutter/flutter#28246]
## command

flutter create myapp

## exception
```
FileSystemException: FileSystemException: Creation failed, path = '/myapp' (OS Error: Permission denied, errno = 13)
```
```
#0      _Directory.createSync (dart:io/directory_impl.dart:140:7)
#1      _LocalDirectory&LocalFileSystemEntity&ForwardingDirectory.createSync (package:file/src/forwarding/forwarding_directory.dart:22:16)
#2      Template.render (package:flutter_tools/src/template.dart:71:17)
#3      CreateCommand._renderTemplate (package:flutter_tools/src/commands/create.dart:541:21)
#4      CreateCommand._generateApp (package:flutter_tools/src/commands/create.dart:468:23)
<asynchronous suspension>
#5      CreateCommand.runCommand (package:flutter_tools/src/commands/create.dart:319:37)
<asynchronous suspension>
#6      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:401:18)
#7      _asyncThenWrapperHelper.<anonymous closure> (dart:async/runtime/libasync_patch.dart:77:64)
#8      _rootRunUnary (dart:async/zone.dart:1132:38)
#9      _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#10     _FutureListener.handleValue (dart:async/future_impl.dart:129:18)
#11     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:642:45)
#12     Future._propagateToListeners (dart:async/future_impl.dart:671:32)
#13     Future._complete (dart:async/future_impl.dart:476:7)
#14     _SyncCompleter.complete (dart:async/future_impl.dart:51:12)
#15     _AsyncAwaitCompleter.complete.<anonymous closure> (dart:async/runtime/libasync_patch.dart:33:20)
#16     _rootRun (dart:async/zone.dart:1124:13)
#17     _CustomZone.run (dart:async/zone.dart:1021:19)
#18     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:947:23)
#19     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#20     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#21     _runPendingImmediateCallback (dart:isolate/runtime/libisolate_patch.dart:115:13)
#22     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:172:5)
```

## flutter doctor

```
[32m[✓] [39m Flutter (Channel stable, v1.0.0, on Linux, locale en_IN)
    [32m• [39m Flutter version 1.0.0 at /home/sudhakar/flutter
    [32m• [39m Framework revision 5391447fae (3 months ago), 2018-11-29 19:41:26 -0800
    [32m• [39m Engine revision 7375a0f414
    [32m• [39m Dart version 2.1.0 (build 2.1.0-dev.9.4 f9ebf21297)

[32m[✓] [39m Android toolchain - develop for Android devices (Android SDK 28.0.3)
    [32m• [39m Android SDK at /home/sudhakar/Android/Sdk
    [32m• [39m Android NDK location not configured (optional; useful for native profiling
      support)
    [32m• [39m Platform android-28, build-tools 28.0.3
    [32m• [39m Java binary at: /usr/local/android-studio/jre/bin/java
    [32m• [39m Java version OpenJDK Runtime Environment (build
      1.8.0_152-release-1248-b01)
    [32m• [39m All Android licenses accepted.

[32m[✓] [39m Android Studio (version 3.3)
    [32m• [39m Android Studio at /usr/local/android-studio
    [32m• [39m Flutter plugin version 32.0.1
    [32m• [39m Dart plugin version 182.5124
    [32m• [39m Java version OpenJDK Runtime Environment (build
      1.8.0_152-release-1248-b01)

[32m[✓] [39m VS Code (version 1.30.2)
    [32m• [39m VS Code at /usr/share/code
    [32m• [39m Flutter extension version 2.21.1

[33m[!] [39m Connected device
    [33m! [39m No devices available

[33m! [39m Doctor found issues in 1 category.
```

**Comment by zoechi** [comment]
What command exactly causes this error?

**Comment by jagdishjadeja** [comment]
i have faced this error when app is stopped from my side but for some reason app is not exited from emulator.
