### ISSUE TITLE
CustomScrollView in Column cause infinite call to the SliverChildBuilderDelegate’s builder

### ISSUE THREAD

**Issue by luoqiao6** [flutter/flutter#28254]
## Steps to Reproduce

Enter the code below and hot reload.

This code will cause the call to the `SliverChildBuilderDelegate`‘s builder  to be in an infinite loop, the page will not display anything, and it may cause subsequent hot overloads(or hot restart) to throw an 
"Request to Dart VM Service timed out" exception.

Should the Flutter framework force the infinite loop to stop and throw a "Rendering failed" exception in this case?

Of course, if assign a value to `childCount`, won't have this problem.

```dart
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key key, this.title}) : super(key: key);

  final String title;

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {

  @override
  Widget build(BuildContext context) {

    return  Column(
      children: <Widget>[

        CustomScrollView(
          shrinkWrap: true,
          slivers: <Widget>[
            SliverList(
              delegate: SliverChildBuilderDelegate(
                (BuildContext context, int index) {

                  print('index:  $index');

                  return Container(
                    child: Text('TEST  $index'),
                  );
                  
                },
                //childCount: 10,
              ),
            ),
          ],
        ),

      ],
    );

  }

}
```

## Logs

```
Performing hot restart...
flutter: index:  12565
Syncing files to device iPhone 8...
flutter: index:  12566
flutter: index:  12567
flutter: index:  12568
flutter: index:  12569
flutter: index:  12570
flutter: index:  12571

................

flutter: index:  18030
flutter: index:  18031
flutter: index:  18032
flutter: index:  18033
flutter: index:  18034
Unhandled exception:
TimeoutException: Request to Dart VM Service timed out: _flutter.runInView({viewId: _flutterView/0x7fefe1c16eb8, mainScript: file:///Users/luoqiao/Library/Developer/CoreSimulator/Devices/5C67A7A9-9057-464C-87A5-49AD897A2407/data/Containers/Data/Application/25B877DD-EDA4-42D2-B6ED-A2843662A727/tmp/hot_reload_exceptiony2EeBR/hot_reload_exception/lib/main.dart.dill, packagesFile: file:///Users/luoqiao/Library/Developer/CoreSimulator/Devices/5C67A7A9-9057-464C-87A5-49AD897A2407/data/Containers/Data/Application/25B877DD-EDA4-42D2-B6ED-A2843662A727/tmp/hot_reload_exceptiony2EeBR/hot_reload_exception/.packages, assetDirectory: file:///Users/luoqiao/Library/Developer/CoreSimulator/Devices/5C67A7A9-9057-464C-87A5-49AD897A2407/data/Containers/Data/Application/25B877DD-EDA4-42D2-B6ED-A2843662A727/tmp/hot_reload_exceptiony2EeBR/hot_reload_exception/build/flutter_assets})
#0      VM.invokeRpcRaw (package:flutter_tools/src/vmservice.dart:834:9)
<asynchronous suspension>
#1      VM.invokeRpc (package:flutter_tools/src/vmservice.dart:851:49)
<asynchronous suspension>
#2      VM.runInView (package:flutter_tools/src/vmservice.dart:917:12)
#3      FlutterView.runFromSource (package:flutter_tools/src/vmservice.dart:1432:20)
<asynchronous suspension>
#4      HotRunner._launchInView (package:flutter_tools/src/run_hot.dart:416:24)
#5      HotRunner._launchFromDevFS (package:flutter_tools/src/run_hot.dart:431:19)
<asynchronous suspension>
#6      HotRunner._restartFromSources (package:flutter_tools/src/run_hot.dart:497:11)
<asynchronous suspension>
#7      HotRunner.restart (package:flutter_tools/src/run_hot.dart:563:46)
<asynchronous suspension>
#8      AppInstance.restart (package:flutter_tools/src/commands/daemon.dart:807:19)
#9      AppDomain.restart.<anonymous closure> (package:flutter_tools/src/commands/daemon.dart:474:18)
#10     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:142:29)
<asynchronous suspension>
#11     _rootRun (dart:async/zone.dart:1124:13)
#12     _CustomZone.run (dart:async/zone.dart:1021:19)
#13     _runZoned (dart:async/zone.dart:1516:10)
#14     runZoned (dart:async/zone.dart:1463:12)
#15     AppContext.run (package:flutter_tools/src/base/context.dart:141:18)
<asynchronous suspension>
#16     AppInstance._runInZone (package:flutter_tools/src/commands/daemon.dart:820:20)
#17     AppDomain.restart (package:flutter_tools/src/commands/daemon.dart:473:32)
<asynchronous suspension>
#18     Domain.handleCommand.<anonymous closure> (package:flutter_tools/src/commands/daemon.dart:193:34)
#19     new Future.sync (dart:async/future.dart:224:31)
#20     Domain.handleCommand (package:flutter_tools/src/commands/daemon.dart:191:9)
#21     Daemon._handleRequest (package:flutter_tools/src/commands/daemon.dart:147:26)
#22     _rootRunUnary (dart:async/zone.dart:1132:38)
#23     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#24     _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
#25     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#26     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#27     _ForwardingStreamSubscription._add (dart:async/stream_pipe.dart:132:11)
#28     _MapStream._handleData (dart:async/stream_pipe.dart:232:10)
#29     _ForwardingStreamSubscription._handleData (dart:async/stream_pipe.dart:164:13)
#30     _rootRunUnary (dart:async/zone.dart:1132:38)
#31     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#32     _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
#33     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#34     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#35     _ForwardingStreamSubscription._add (dart:async/stream_pipe.dart:132:11)
#36     _WhereStream._handleData (dart:async/stream_pipe.dart:207:12)
#37     _ForwardingStreamSubscription._handleData (dart:async/stream_pipe.dart:164:13)
#38     _rootRunUnary (dart:async/zone.dart:1132:38)
#39     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#40     _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
#41     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#42     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#43     _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:68:11)
#44     _EventSinkWrapper.add (dart:async/stream_transformers.dart:15:11)
#45     _StringAdapterSink.add (dart:convert/string_conversion.dart:268:11)
#46     _LineSplitterSink._addLines (dart:convert/line_splitter.dart:154:13)
#47     _LineSplitterSink.addSlice (dart:convert/line_splitter.dart:129:5)
#48     StringConversionSinkMixin.add (dart:convert/string_conversion.dart:189:5)
#49     _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:120:24)
#50     _rootRunUnary (dart:async/zone.dart:1132:38)
#51     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#52     _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
#53     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#54     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#55     _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:68:11)
#56     _EventSinkWrapper.add (dart:async/stream_transformers.dart:15:11)
#57     _StringAdapterSink.add (dart:convert/string_conversion.dart:268:11)
#58     _StringAdapterSink.addSlice (dart:convert/string_conversion.dart:273:7)
#59     _Utf8ConversionSink.addSlice (dart:convert/string_conversion.dart:348:20)
#60     _Utf8ConversionSink.add (dart:convert/string_conversion.dart:341:5)
#61     _ConverterStreamEventSink.add (dart:convert/chunked_conversion.dart:86:18)
#62     _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:120:24)
#63     _rootRunUnary (dart:async/zone.dart:1132:38)
#64     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#65     _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
#66     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#67     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#68     _SyncStreamController._sendData (dart:async/stream_controller.dart:763:19)
#69     _StreamController._add (dart:async/stream_controller.dart:639:7)
#70     _StreamController.add (dart:async/stream_controller.dart:585:5)
#71     _Socket._onData (dart:io/runtime/binsocket_patch.dart:1721:41)
#72     _rootRunUnary (dart:async/zone.dart:1136:13)
#73     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#74     _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
#75     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#76     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#77     _SyncStreamController._sendData (dart:async/stream_controller.dart:763:19)
#78     _StreamController._add (dart:async/stream_controller.dart:639:7)
#79     _StreamController.add (dart:async/stream_controller.dart:585:5)
#80     new _RawSocket.<anonymous closure> (dart:io/runtime/binsocket_patch.dart:1283:33)
#81     _NativeSocket.issueReadEvent.issue (dart:io/runtime/binsocket_patch.dart:826:14)
#82     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#83     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#84     _runPendingImmediateCallback (dart:isolate/runtime/libisolate_patch.dart:115:13)
#85     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:172:5)


```

## flutter analyze
```
localhost:hot_reload_exception luoqiao$ flutter analyze
Analyzing hot_reload_exception...                                
No issues found! (ran in 2.9s)
localhost:hot_reload_exception luoqiao$ 
```

## flutter doctor -v
```
localhost:hot_reload_exception luoqiao$ flutter doctor -v
[✓] Flutter (Channel stable, v1.0.0, on Mac OS X 10.14.3 18D109, locale zh-Hans-CN)
    • Flutter version 1.0.0 at /Users/luoqiao/flutter/flutter_v1.0.0-stable
    • Framework revision 5391447fae (3 months ago), 2018-11-29 19:41:26 -0800
    • Engine revision 7375a0f414
    • Dart version 2.1.0 (build 2.1.0-dev.9.4 f9ebf21297)

[✓] Android toolchain - develop for Android devices (Android SDK 28.0.3)
    • Android SDK at /Users/luoqiao/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = /Users/luoqiao/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.1, Build version 10B61
    • ios-deploy 2.0.0
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 29.0.1
    • Dart plugin version 173.4700
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)

[✓] IntelliJ IDEA Ultimate Edition (version 2018.1.5)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 29.0.2
    • Dart plugin version 181.4892.1

[!] VS Code (version 1.31.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (1 available)
    • iPhone 8 • 5C67A7A9-9057-464C-87A5-49AD897A2407 • ios • iOS 12.1 (simulator)

! Doctor found issues in 1 category.
localhost:hot_reload_exception luoqiao$ 
localhost:hot_reload_exception luoqiao$ 
```

**Comment by zoechi** [comment]
Wrap `CustomScrollView` with `Expanded` to limit its size. Otherwise it's infinite and the list has to render infinite items to fill the list.
With `Expanded` it only renders until the screen is full or the builder returns `null`

```dart
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key key, this.title}) : super(key: key);

  final String title;

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  @override
  Widget build(BuildContext context) {
    return Column(
      children: <Widget>[
        Expanded(
          child: CustomScrollView(
            shrinkWrap: true,
            slivers: <Widget>[
              SliverList(
                delegate: SliverChildBuilderDelegate(
                  (BuildContext context, int index) {
                    print('index:  $index');

                    return Container(
                      child: Text('TEST  $index'),
                    );
                  },
//                childCount: 10,
                ),
              ),
            ],
          ),
        ),
      ],
    );
  }
}
```

**Comment by zoechi** [comment]
Please consider asking support questions in one of the other channels listed at http://flutter.io/support .

**Comment by luoqiao6** [comment]
I see,  thank you
