### ISSUE TITLE
Firebase Dynamic Links with deep link Whitelist enabled crashes app 

### ISSUE THREAD

**Issue by ninnepinne** [flutter/flutter#28262]
If I add anything to the deep link whitelist in Firebase console - both iOS and Android abruptly crash to native home screen (the app is stopped and force closed). 

Reproducible on simulators and devices. 

If I clear the whitelist everything works again...

Console output Android simulator:
```
D/AndroidRuntime(24675): Shutting down VM
E/AndroidRuntime(24675): FATAL EXCEPTION: main
E/AndroidRuntime(24675): Process: grit.xxx.stories.app, PID: 24675
E/AndroidRuntime(24675): java.lang.NullPointerException: Attempt to invoke interface method 'java.util.Iterator java.util.List.iterator()' on a null object reference
E/AndroidRuntime(24675): 	at io.flutter.plugins.firebasedynamiclinks.FirebaseDynamicLinksPlugin$2.onComplete(FirebaseDynamicLinksPlugin.java:99)
E/AndroidRuntime(24675): 	at com.google.android.gms.tasks.zzj.run(Unknown Source:4)
E/AndroidRuntime(24675): 	at android.os.Handler.handleCallback(Handler.java:790)
E/AndroidRuntime(24675): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/AndroidRuntime(24675): 	at android.os.Looper.loop(Looper.java:164)
E/AndroidRuntime(24675): 	at android.app.ActivityThread.main(ActivityThread.java:6494)
E/AndroidRuntime(24675): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(24675): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
E/AndroidRuntime(24675): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
```

Console output iOS simulator:
```
*** First throw call stack:
(
	0   CoreFoundation                      0x0000000106c341bb __exceptionPreprocess + 331
	1   libobjc.A.dylib                     0x0000000105d5e735 objc_exception_throw + 48
	2   CoreFoundation                      0x0000000106b804ec _CFThrowFormattedException + 194
	3   CoreFoundation                      0x0000000106ca3541 -[__NSPlaceholderDictionary initWithObjects:forKeys:count:] + 321
	4   CoreFoundation                      0x0000000106c2fc9b +[NSDictionary dictionaryWithObjects:forKeys:count:] + 59
	5   Runner                              0x00000001027a0106 __59-[FLTFirebaseDynamicLinksPlugin createShortLinkCompletion:]_block_invoke + 374
	6   Runner                              0x000000010276fb54 __58+[FIRDynamicLinkComponents shortenURL:options:completion:]_block_invoke<…>
Lost connection to device.
```

Xcode Console output iOS device:
```
2019-02-21 15:58:11.493569+0100 Runner[486:39201] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '*** -[__NSPlaceholderDictionary initWithObjects:forKeys:count:]: attempt to insert nil object from objects[1]'
*** First throw call stack:
(0x22332fea0 0x222501a40 0x2232a7470 0x22322da60 0x22321e5a4 0x100cd6048 0x100ca6fb8 0x101167824 0x101168dc8 0x101176a78 0x2232bfdd0 0x2232bac98 0x2232ba1cc 0x225531584 0x2503b5054 0x100c843cc 0x222d7abb4)
libc++abi.dylib: terminating with uncaught exception of type NSException
```

Package versions:
```yml
  firebase_core: ^0.3.0+2
  firebase_analytics: 2.0.1
  firebase_dynamic_links: ^0.2.0+2
```
Android gradle config google services version:
```gradle
dependencies {
        classpath 'com.android.tools.build:gradle:3.3.1'
        classpath 'com.google.gms:google-services:4.2.0'  // Google Services plugin
}
```
Flutter doctor response:

```
[✓] Flutter (Channel beta, v1.1.8, on Mac OS X 10.14.3 18D109, locale en-SE)
    • Flutter version 1.1.8 at /Users/fredrik.dahlen/DEV/flutter
    • Framework revision 985ccb6d14 (6 weeks ago), 2019-01-08 13:45:55 -0800
    • Engine revision 7112b72cc2
    • Dart version 2.1.1 (build 2.1.1-dev.0.1 ec86471ccc)

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/fredrik.dahlen/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = /Users/fredrik.dahlen/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.1, Build version 10B61
    • ios-deploy 2.0.0
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 33.1.1
    • Dart plugin version 182.5215
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)

[✓] VS Code (version 1.31.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 2.23.0

[✓] Connected device (3 available)
    • Android SDK built for x86 • emulator-5554                            • android-x86 • Android 8.1.0 (API 27) (emulator)
    • Fredrik’s iPhone          • f6414d51c92a4d1e13c55cc0b2b04547651d022b • ios         • iOS 12.1
    • iPhone 5s                 • 554AB6F9-6D92-4590-B1BA-C9B95A9E1BCC     • ios         • iOS 12.1 (simulator)

• No issues found!
```

**Comment by ninnepinne** [comment]
@zoechi Sorry for bothering you. But could you please get things rolling...

[https://github.com/flutter/plugins/pull/1142](https://github.com/flutter/plugins/pull/1142)

This is a merged fix for this issue (beginning of march).
But it is not released...

The cause was that the firebase plugin code could only handle links WITH warnings (the whitelist not configured).

If the short links were correctly configured with a whitelist as you strongly recommend there were no more warnings and the both iOS and Android fatally crash.

This means that any active usage of this plugin is without whitelist.
Which makes all your customers susceptible to PHISHING attacks.

Doesn't sound right.

This currently a blocker for me.
And the organisation I am doing the app for is a big Google customer.
I suspect I could get one of those fancy customer tags...
Should I?

Thank you very much!

**Comment by ninnepinne** [comment]
Fixed by https://github.com/flutter/plugins/pull/1142.
Which is now also released...
Closing this issue.

**Comment by kroikie** [comment]
@ninnepinne

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/423. Any further collaboration will be done there.
