### ISSUE TITLE
replaceSemanticsActions getting called during build

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#28313]
No idea what caused it, but I got this in my logs:

```
I/flutter (17692): ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
I/flutter (17692): The following assertion was thrown building TickerMode(mode: disabled):
I/flutter (17692): Unexpected call to replaceSemanticsActions() method of RawGestureDetectorState.
I/flutter (17692): The replaceSemanticsActions() method can only be called outside of the build phase.
I/flutter (17692): 
I/flutter (17692): When the exception was thrown, this was the stack:
I/flutter (17692): #0      RawGestureDetectorState.replaceSemanticsActions.<anonymous closure> (package:flutter/src/widgets/gesture_detector.dart:689:9)
I/flutter (17692): #1      RawGestureDetectorState.replaceSemanticsActions (package:flutter/src/widgets/gesture_detector.dart:695:6)
I/flutter (17692): #2      ScrollableState.setSemanticsActions (package:flutter/src/widgets/scrollable.dart:379:40)
I/flutter (17692): #3      ScrollPosition._updateSemanticActions (package:flutter/src/widgets/scroll_position.dart:445:13)
I/flutter (17692): #4      ScrollPosition.notifyListeners (package:flutter/src/widgets/scroll_position.dart:695:5)
I/flutter (17692): #5      ScrollPosition.forcePixels (package:flutter/src/widgets/scroll_position.dart:318:5)
I/flutter (17692): #6      ScrollPositionWithSingleContext.jumpTo (package:flutter/src/widgets/scroll_position_with_single_context.dart:201:7)
I/flutter (17692): #7      ScrollController.jumpTo (package:flutter/src/widgets/scroll_controller.dart:172:16)
I/flutter (17692): #8      _TweetStreamViewState.didChangeDependencies (package:cruisemonkey/src/views/stream.dart:104:27)
I/flutter (17692): #9      StatefulElement.didChangeDependencies (package:flutter/src/widgets/framework.dart:3976:12)
I/flutter (17692): #10     Element.activate (package:flutter/src/widgets/framework.dart:3060:7)
I/flutter (17692): #11     StatefulElement.activate (package:flutter/src/widgets/framework.dart:3899:11)
I/flutter (17692): #12     Element._activateRecursively (package:flutter/src/widgets/framework.dart:3029:13)
I/flutter (17692): #13     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:4864:14)
I/flutter (17692): #14     Element._activateRecursively (package:flutter/src/widgets/framework.dart:3031:13)
I/flutter (17692): #15     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3770:14)
I/flutter (17692): #16     Element._activateRecursively (package:flutter/src/widgets/framework.dart:3031:13)
I/flutter (17692): #17     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:4864:14)
I/flutter (17692): #18     Element._activateRecursively (package:flutter/src/widgets/framework.dart:3031:13)
I/flutter (17692): #19     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:4864:14)
I/flutter (17692): #20     Element._activateRecursively (package:flutter/src/widgets/framework.dart:3031:13)
I/flutter (17692): #21     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:4864:14)
I/flutter (17692): #22     Element._activateRecursively (package:flutter/src/widgets/framework.dart:3031:13)
I/flutter (17692): #23     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:4864:14)
I/flutter (17692): #24     Element._activateRecursively (package:flutter/src/widgets/framework.dart:3031:13)
I/flutter (17692): #25     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3770:14)
I/flutter (17692): #26     Element._activateRecursively (package:flutter/src/widgets/framework.dart:3031:13)
I/flutter (17692): #27     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3770:14)
I/flutter (17692): #28     Element._activateRecursively (package:flutter/src/widgets/framework.dart:3031:13)
I/flutter (17692): #29     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3770:14)
I/flutter (17692): #30     Element._activateRecursively (package:flutter/src/widgets/framework.dart:3031:13)
I/flutter (17692): #31     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:4864:14)
I/flutter (17692): #32     Element._activateRecursively (package:flutter/src/widgets/framework.dart:3031:13)
I/flutter (17692): #33     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3770:14)
I/flutter (17692): #34     Element._activateRecursively (package:flutter/src/widgets/framework.dart:3031:13)
I/flutter (17692): #35     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:4864:14)
I/flutter (17692): #36     Element._activateRecursively (package:flutter/src/widgets/framework.dart:3031:13)
I/flutter (17692): #37     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3770:14)
I/flutter (17692): #38     Element._activateRecursively (package:flutter/src/widgets/framework.dart:3031:13)
I/flutter (17692): #39     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3770:14)
I/flutter (17692): #40     Element._activateRecursively (package:flutter/src/widgets/framework.dart:3031:13)
I/flutter (17692): #41     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:4864:14)
I/flutter (17692): #42     Element._activateRecursively (package:flutter/src/widgets/framework.dart:3031:13)
I/flutter (17692): #43     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3770:14)
I/flutter (17692): #44     Element._activateRecursively (package:flutter/src/widgets/framework.dart:3031:13)
I/flutter (17692): #45     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3770:14)
I/flutter (17692): #46     Element._activateRecursively (package:flutter/src/widgets/framework.dart:3031:13)
I/flutter (17692): #47     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3770:14)
I/flutter (17692): #48     Element._activateRecursively (package:flutter/src/widgets/framework.dart:3031:13)
I/flutter (17692): #49     Element._activateWithParent (package:flutter/src/widgets/framework.dart:3022:5)
I/flutter (17692): #50     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2948:18)
I/flutter (17692): #51     Element.updateChild (package:flutter/src/widgets/framework.dart:2759:12)
I/flutter (17692): #52     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3747:16)
I/flutter (17692): #53     Element.rebuild (package:flutter/src/widgets/framework.dart:3559:5)
I/flutter (17692): #54     ProxyElement.update (package:flutter/src/widgets/framework.dart:4006:5)
I/flutter (17692): #55     Element.updateChild (package:flutter/src/widgets/framework.dart:2748:15)
I/flutter (17692): #56     RenderObjectElement.updateChildren (package:flutter/src/widgets/framework.dart:4601:32)
I/flutter (17692): #57     _TheatreElement.update (package:flutter/src/widgets/overlay.dart:509:17)
I/flutter (17692): #58     Element.updateChild (package:flutter/src/widgets/framework.dart:2748:15)
I/flutter (17692): #59     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3747:16)
I/flutter (17692): #60     Element.rebuild (package:flutter/src/widgets/framework.dart:3559:5)
I/flutter (17692): #61     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2273:33)
I/flutter (17692): #62     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding&WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:700:20)
I/flutter (17692): #63     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:275:5)
I/flutter (17692): #64     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:990:15)
I/flutter (17692): #65     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:930:9)
I/flutter (17692): #66     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:842:5)
I/flutter (17692): #70     _invoke (dart:ui/hooks.dart:209:10)
I/flutter (17692): #71     _drawFrame (dart:ui/hooks.dart:168:3)
I/flutter (17692): (elided 3 frames from package dart:async)
I/flutter (17692): ════════════════════════════════════════════════════════════════════════════════════════════════════
```

**Comment by Hixie** [comment]
Oh never mind, I didn't notice the `_TweetStreamViewState` in the stack. This is probably my bug.

**Comment by Hixie** [comment]
Yup, I was trying to call jumpTo(0.0) during didChangeDependencies.
The solution in my case was to create a new scroll controller entirely and give the ListView a key that was based on the object that I generated during didChangeDependencies.

**Comment by acebeing** [comment]
I encounter this problem too. Could you explain the implement that how to resolve this problem in your way? Thanks a lot. @Hixie
