### ISSUE TITLE
[Firebase Database] DatabaseReference.set() causes an exception on iOS

### ISSUE THREAD

**Issue by madtocc** [flutter/flutter#28344]
## Steps to Reproduce

After updating `firebase_database` plugin to to `2.0.1+1` `DatabaseReference.set()` causes an exception on iOS, on Android it works fine... Before the update I was using an older version of the plugin (`firebase_database: ^1.0.5`). Now I have downgraded to this version and it works fine on iOS.

## Logs
```
[VERBOSE-2:ui_dart_state.cc(148)] Unhandled Exception: PlatformException(Error 0, null, null)
#0      StandardMethodCodec.decodeEnvelope 
#1      MethodChannel.invokeMethod 
<asynchronous suspension>
#2      DatabaseReference.set 
#3      LoginPageState._saveUserToDatabase.<anonymous closure>.<anonymous closure> 
#4      _asyncThenWrapperHelper.<anonymous closure> (dart:async/runtime/libasync_patch.dart:77:64)
#5      _rootRunUnary (dart:async/zone.dart:1132:38)
#6      _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#7      _FutureListener.handleValue (dart:async/future_impl.dart:126:18)
#8      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:639:45)
#9      Future._propagateToListeners (dart:async/future_impl.dart:668:32)
#10     Future._complete (dart:async/future_impl.dart:473:7)
#11     _SyncCompleter.complete (dart:async/future_impl.dart:51:12)
#12     _rootRunUnary (dart:async/zone.dart:1132:38)
#13     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#14     _FutureListener.handleValue (dart:async/future_impl.dart:126:18)
#15     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:639:45)
#16     Future._propagateToListeners (dart:async/future_impl.dart:668:32)
#17     Future._completeWithValue (dart:async/future_impl.dart:483:5)
#18     Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:513:7)
#19     _rootRun (dart:async/zone.dart:1124:13)
#20     _CustomZone.run (dart:async/zone.dart:1021:19)
#21     _CustomZone.runGuarded (dart:async/zone.dart:923:7)
#22     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:963:23)
#23     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#24     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)

```

```
[✓] Flutter (Channel master, v1.2.3-pre.6, on Mac OS X 10.14.2 18C54, locale en-US)
    • Flutter version 1.2.3-pre.6 at /Users/mt/Documents/flutter
    • Framework revision ea4cffde60 (2 hours ago), 2019-02-22 08:38:02 -0800
    • Engine revision cb0f7ece1f
    • Dart version 2.2.0 (build 2.2.0-dev.2.1 c92d5ca288)

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/mt/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = /Users/mt/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.1, Build version 10B61
    • ios-deploy 1.9.4
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 32.0.1
    • Dart plugin version 182.5124
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)

[✓] VS Code (version 1.31.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 2.23.1

[✓] Connected device (1 available)
    • iPhone de M • bcdfc8d068fb4c41827d8a741f2134c31447cab6 • ios • iOS 12.1.2
```

**Comment by cyanglaz** [comment]
This issue was fixed by https://github.com/flutter/plugins/pull/1274. If any related issue is found, please feel free to reopen the issue ticket with more details.

**Comment by kroikie** [comment]
@madtocc

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/421. Any further collaboration will be done there.
