### ISSUE TITLE
List rebuild leads to creating new Stream with Stream has already been listened to Exception

### ISSUE THREAD

**Issue by JonasJW** [flutter/flutter#28361]
I have a `ListView` that looks like this:
```dart
    ListView(
      children: <Widget>[
        _buildStream(),
        // Other Childs
      ],
    ),

    _buildStreamn() {
      return StreamBuilder(
        stream: Stream.periodic(Duration(seconds: 1)),
        builder: (BuildContext context, AsyncSnapshot snapshot) {
          return Text('some Text that updates every second!');
        }
      );
    }
```

The problem is, when I scroll to the end of my List I get a `Bad state: Stream has already been listened to`. I think the List rebuilds at some point but the it should just call `_buildStream()` again, which would create a new Stream, so there shouldn't be a already listend to Stream.

Full Exception:
````
I/flutter (  844): ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
I/flutter (  844): The following StateError was thrown building NotificationListener<KeepAliveNotification>:
I/flutter (  844): Bad state: Stream has already been listened to.
I/flutter (  844):
I/flutter (  844): When the exception was thrown, this was the stack:
I/flutter (  844): #3      _StreamBuilderBaseState._subscribe (package:flutter/src/widgets/async.dart:135:37)
I/flutter (  844): #4      _StreamBuilderBaseState.initState (package:flutter/src/widgets/async.dart:109:5)
I/flutter (  844): #5      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3830:58)
I/flutter (  844): #6      ComponentElement.mount (package:flutter/src/widgets/framework.dart:3696:5)
I/flutter (  844): #7      Element.inflateWidget (package:flutter/src/widgets/framework.dart:2950:14)
I/flutter (  844): #8      Element.updateChild (package:flutter/src/widgets/framework.dart:2753:12)
I/flutter (  844): #9      SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4860:14)
I/flutter (  844): #10     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2950:14)
I/flutter (  844): #11     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:12)
I/flutter (  844): #12     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4860:14)
I/flutter (  844): #13     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2950:14)
I/flutter (  844): #14     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:12)
I/flutter (  844): #15     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3732:16)
I/flutter (  844): #16     Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
I/flutter (  844): #17     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3701:5)
I/flutter (  844): #18     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3696:5)
I/flutter (  844): #19     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2950:14)
I/flutter (  844): #20     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:12)
I/flutter (  844): #21     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3732:16)
I/flutter (  844): #22     Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
I/flutter (  844): #23     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3701:5)
I/flutter (  844): #24     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3696:5)
I/flutter (  844): #25     ParentDataElement.mount (package:flutter/src/widgets/framework.dart:4047:11)
I/flutter (  844): #26     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2950:14)
I/flutter (  844): #27     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:12)
I/flutter (  844): #28     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3732:16)
I/flutter (  844): #29     Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
I/flutter (  844): #30     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3701:5)
I/flutter (  844): #31     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3848:11)
I/flutter (  844): #32     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3696:5)
I/flutter (  844): #33     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2950:14)
I/flutter (  844): #34     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:12)
I/flutter (  844): #35     SliverMultiBoxAdaptorElement.updateChild (package:flutter/src/widgets/sliver.dart:1028:36)
I/flutter (  844): #36     SliverMultiBoxAdaptorElement.createChild.<anonymous closure> (package:flutter/src/widgets/sliver.dart:1013:20)
I/flutter (  844): #37     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2266:19)
I/flutter (  844): #38     SliverMultiBoxAdaptorElement.createChild (package:flutter/src/widgets/sliver.dart:1006:11)
I/flutter (  844): #38     SliverMultiBoxAdaptorElement.createChild (package:flutter/src/widgets/sliver.dart:1006:11)
I/flutter (  844): #39     RenderSliverMultiBoxAdaptor._createOrObtainChild.<anonymous closure> (package:flutter/src/rendering/sliver_multi_box_adaptor.dart:274:23)
I/flutter (  844): #40     RenderObject.invokeLayoutCallback.<anonymous closure> (package:flutter/src/rendering/object.dart:1730:58)
I/flutter (  844): #41     PipelineOwner._enableMutationsToDirtySubtrees (package:flutter/src/rendering/object.dart:799:15)
I/flutter (  844): #42     RenderObject.invokeLayoutCallback (package:flutter/src/rendering/object.dart:1730:13)
I/flutter (  844): #43     RenderSliverMultiBoxAdaptor._createOrObtainChild (package:flutter/src/rendering/sliver_multi_box_adaptor.dart:263:5)
I/flutter (  844): #44     RenderSliverMultiBoxAdaptor.insertAndLayoutLeadingChild (package:flutter/src/rendering/sliver_multi_box_adaptor.dart:372:5)
I/flutter (  844): #45     RenderSliverList.performLayout (package:flutter/src/rendering/sliver_list.dart:99:29)
I/flutter (  844): #46     RenderObject.layout (package:flutter/src/rendering/object.dart:1634:7)
I/flutter (  844): #47     RenderSliverPadding.performLayout (package:flutter/src/rendering/sliver_padding.dart:182:11)
I/flutter (  844): #48     RenderObject.layout (package:flutter/src/rendering/object.dart:1634:7)
I/flutter (  844): #49     RenderViewportBase.layoutChildSequence (package:flutter/src/rendering/viewport.dart:405:13)
I/flutter (  844): #50     RenderViewport._attemptLayout (package:flutter/src/rendering/viewport.dart:1316:12)
I/flutter (  844): #51     RenderViewport.performLayout (package:flutter/src/rendering/viewport.dart:1234:20)
I/flutter (  844): #52     RenderObject._layoutWithoutResize (package:flutter/src/rendering/object.dart:1509:7)
I/flutter (  844): #53     PipelineOwner.flushLayout (package:flutter/src/rendering/object.dart:768:18)
I/flutter (  844): #54     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding.drawFrame (package:flutter/src/rendering/binding.dart:281:19)
I/flutter (  844): #55     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding&WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:677:13)
I/flutter (  844): #56     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:219:5)
I/flutter (  844): #57     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:990:15)
I/flutter (  844): #58     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:930:9)
I/flutter (  844): #59     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:842:5)
I/flutter (  844): #60     _invoke (dart:ui/hooks.dart:154:13)
I/flutter (  844): #61     _drawFrame (dart:ui/hooks.dart:143:3)
I/flutter (  844): (elided 3 frames from package dart:async)
I/flutter (  844): ════════════════════════════════════════════════════════════════════════════════════════════════════
````

```
[✓] Flutter (Channel stable, v1.0.0, on Mac OS X 10.14.3 18D109, locale de-DE)
    • Flutter version 1.0.0 at /Users/jonas/flutter
    • Framework revision 5391447fae (3 months ago), 2018-11-29 19:41:26 -0800
    • Engine revision 7375a0f414
    • Dart version 2.1.0 (build 2.1.0-dev.9.4 f9ebf21297)

[✓] Android toolchain - develop for Android devices (Android SDK 28.0.3)
    • Android SDK at /Users/jonas/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = /Users/jonas/Library/Android/sdk
    • Java binary at: /Library/Java/JavaVirtualMachines/jdk1.8.0_192.jdk/Contents/Home/bin/java
    • Java version Java(TM) SE Runtime Environment (build 1.8.0_192-b12)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.1, Build version 10B61
    • ios-deploy 1.9.4
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 31.3.1
    • Dart plugin version 181.5656
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)

[!] Android Studio
    • Android Studio at /Applications/Android/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    ✗ Android Studio not found at /Applications/Android/Contents
    • Try updating or re-installing Android Studio.

[!] IntelliJ IDEA Community Edition (version 2018.1.2)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.io/intellij-setup/#installing-the-plugins

[✓] Connected device (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 8.1.0 (API 27) (emulator)

! Doctor found issues in 2 categories.
```

**Comment by felipekruhs** [comment]
There is a workaround for this issue?

**Comment by jonahwilliams** [comment]
[`Stream.periodic`](https://api.dartlang.org/stable/2.2.0/dart-async/Stream/Stream.periodic.html) will create a single subscription stream, which can't be subscribed to more than once. In this case, a ListView child may be getting offloaded when you scroll to the end, and scrolling back causes it to try to resubscribe without re-creating the stream.

I would recommend only using broadcast streams, for example to convert the period stream into one:

`Stream.periodic(Duration(seconds: 1)). asBroadcastStream()`

**Comment by miroslave-ivan** [comment]
hi jonahwilliams
thanks for your recommendation.
I have solved that according to your recommended method

**Comment by SirBepy** [comment]
Just wanted to say, another way of fixing this issue is by taking out the streambuilder, making a stateless widget, and putting that streambuilder in there. That fixed it for me :).
