### ISSUE TITLE
Failed assertion:  '_dependents.isEmpty': is not true.

### ISSUE THREAD

**Issue by nickolas-pohilets** [flutter/flutter#28366]
```
flutter: ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
flutter: The following assertion was thrown building Overlay-[LabeledGlobalKey<OverlayState>#62910](state:
flutter: OverlayState#03264(tickers: tracking 22 tickers, entries: [OverlayEntry#14619(opaque: false;
flutter: maintainState: false), OverlayEntry#b16f9(opaque: false; maintainState: true)])):
flutter: 'package:flutter/src/widgets/framework.dart': Failed assertion: line 4131 pos 14:
flutter: '_dependents.isEmpty': is not true.
flutter:
flutter: Either the assertion indicates an error in the framework itself, or we should provide substantially
flutter: more information in this error message to help you determine and fix the underlying cause.
flutter: In either case, please report this assertion by filing a bug on GitHub:
flutter:   https://github.com/flutter/flutter/issues/new?template=BUG.md
flutter:
flutter: When the exception was thrown, this was the stack:
flutter: #2      InheritedElement.debugDeactivated.<anonymous closure> (package:flutter/src/widgets/framework.dart:4131:14)
flutter: #3      InheritedElement.debugDeactivated (package:flutter/src/widgets/framework.dart:4133:6)
flutter: #4      _InactiveElements._deactivateRecursively.<anonymous closure> (package:flutter/src/widgets/framework.dart:1730:25)
flutter: #5      _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:1730:59)
flutter: #6      SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:4848:14)
flutter: #7      _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:1729:13)
flutter: #8      ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3755:14)
flutter: #9      _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:1729:13)
flutter: #10     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3755:14)
flutter: #11     _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:1729:13)
flutter: #12     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3755:14)
flutter: #13     _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:1729:13)
flutter: #14     MultiChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:4948:16)
flutter: #15     _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:1729:13)
flutter: #16     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3755:14)
flutter: #17     _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:1729:13)
flutter: #18     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3755:14)
flutter: #19     _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:1729:13)
flutter: #20     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3755:14)
flutter: #21     _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:1729:13)
flutter: #22     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:4848:14)
flutter: #23     _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:1729:13)
flutter: #24     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3755:14)
flutter: #25     _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:1729:13)
flutter: #26     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:4848:14)
flutter: #27     _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:1729:13)
flutter: #28     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3755:14)
flutter: #29     _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:1729:13)
flutter: #30     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3755:14)
flutter: #31     _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:1729:13)
flutter: #32     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3755:14)
flutter: #33     _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:1729:13)
flutter: #34     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3755:14)
flutter: #35     _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:1729:13)
flutter: #36     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3755:14)
flutter: #37     _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:1729:13)
flutter: #38     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3755:14)
flutter: #39     _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:1729:13)
flutter: #40     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3755:14)
flutter: #41     _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:1729:13)
flutter: #42     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:4848:14)
flutter: #43     _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:1729:13)
flutter: #44     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3755:14)
flutter: #45     _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:1729:13)
flutter: #46     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:4848:14)
flutter: #47     _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:1729:13)
flutter: #48     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:4848:14)
flutter: #49     _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:1729:13)
flutter: #50     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:4848:14)
flutter: #51     _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:1729:13)
flutter: #52     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3755:14)
flutter: #53     _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:1729:13)
flutter: #54     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3755:14)
flutter: #55     _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:1729:13)
flutter: #56     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3755:14)
flutter: #57     _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:1729:13)
flutter: #58     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:4848:14)
flutter: #59     _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:1729:13)
flutter: #60     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3755:14)
flutter: #61     _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:1729:13)
flutter: #62     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:4848:14)
flutter: #63     _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:1729:13)
flutter: #64     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3755:14)
flutter: #65     _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:1729:13)
flutter: #66     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3755:14)
flutter: #67     _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:1729:13)
flutter: #68     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:4848:14)
flutter: #69     _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:1729:13)
flutter: #70     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3755:14)
flutter: #71     _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:1729:13)
flutter: #72     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3755:14)
flutter: #73     _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:1729:13)
flutter: #74     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3755:14)
flutter: #75     _InactiveElements._deactivateRecursively (package:flutter/src/widgets/framework.dart:1729:13)
flutter: #76     _InactiveElements.add (package:flutter/src/widgets/framework.dart:1738:7)
flutter: #77     Element.deactivateChild (package:flutter/src/widgets/framework.dart:2986:29)
flutter: #78     RenderObjectElement.updateChildren (package:flutter/src/widgets/framework.dart:4678:11)
flutter: #79     MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4975:17)
flutter: #80     Element.updateChild (package:flutter/src/widgets/framework.dart:2742:15)
flutter: #81     _TheatreElement.update (package:flutter/src/widgets/overlay.dart:507:16)
flutter: #82     Element.updateChild (package:flutter/src/widgets/framework.dart:2742:15)
flutter: #83     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3732:16)
flutter: #84     Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
flutter: #85     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2286:33)
flutter: #86     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding&WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:676:20)
flutter: #87     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:219:5)
flutter: #88     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:990:15)
flutter: #89     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:930:9)
flutter: #90     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:842:5)
flutter: #91     _invoke (dart:ui/hooks.dart:154:13)
flutter: #92     _drawFrame (dart:ui/hooks.dart:143:3)
flutter: (elided 2 frames from class _AssertionError)
flutter: ════════════════════════════════════════════════════════════════════════════════════════════════════
```

**Comment by zoechi** [comment]
Please add the output of `flutter doctor -v`.

To investigate we would need a minimal runnable reproduction
as a single file so that we can just copy your code into `lib/main.dart` of a new project and run to reproduce.

**Comment by efikalti** [comment]
I recently had the same exception when I was trying to navigate to another router from a Stateful Widget. Turns out I had forgotten to add the line `super.initState();` at the start of my wodget's `initState()`

Once I change it to this it worked perfectly

` @override
  void initState() {
    super.initState();
    ....
    );
  }
`

**Comment by zoechi** [comment]
@efikalti how can you forget that. The IDE warns about a missing `super.initState()`. Are you not using an IDE that supports Dart/Flutter?

**Comment by efikalti** [comment]
> 
> 
> @efikalti how can you forget that. The IDE warns about a missing `super.initState()`. Are you not using an IDE that supports Dart/Flutter?

I am using Android Studio with Flutter/Dart but I had not enabled the linter for the project at that point, hence the issue

**Comment by danielgchap** [comment]
> @efikalti how can you forget that. The IDE warns about a missing `super.initState()`. Are you not using an IDE that supports Dart/Flutter?

wow. Rude.

**Comment by OsamaxD1** [comment]
Checked flutter doctor and using super.initState() but still having same issue

**Comment by gilescm** [comment]
For anyone who may find this helpful, I recently had this issue too and it was caused by incorrectly setting a number of `key` parameters in a list of widgets. I was setting the key based on an id:
```flutter
key: Key(item.id.toString())
```
However due to some other logic `item.id` can sometimes be null and because there are a number of these widgets I ended up with multiple widgets with the key: `Key("null")`. Updating my key to ensure it was unique solved my problem:
```flutter
key: Key(items.indexOf(item).toString())
```
