### ISSUE TITLE
ScrollController not attached to any scroll views.

### ISSUE THREAD

**Issue by krisai** [flutter/flutter#28380]
`flutter: #15     GestureArenaManager.sweep 
package:flutter/…/gestures/arena.dart:156
flutter: #16     _WidgetsFlutterBinding&BindingBase&GestureBinding.handleEvent 
package:flutter/…/gestures/binding.dart:184
flutter: #17     _WidgetsFlutterBinding&BindingBase&GestureBinding.dispatchEvent 
package:flutter/…/gestures/binding.dart:158
flutter: #18     _WidgetsFlutterBinding&BindingBase&GestureBinding._handlePointerEvent 
package:flutter/…/gestures/binding.dart:138
flutter: #19     _WidgetsFlutterBinding&BindingBase&GestureBinding._flushPointerEventQueue 
package:flutter/…/gestures/binding.dart:101
flutter: #20     _WidgetsFlutterBinding&BindingBase&GestureBinding._handlePointerDataPacket 
package:flutter/…/gestures/binding.dart:85
flutter: #21     _invoke1 (dart:ui/hooks.dart:173:13)
flutter: #22     _dispatchPointerDataPacket (dart:ui/hooks.dart:127:5)
flutter: (elided 2 frames from class _AssertionError)
flutter:
flutter: The TabController sending notification was:
flutter:   Instance of 'TabController'
flutter: ════════════════════════════════════════════════════════════════════════════════════════════════════`

**Comment by zoechi** [comment]
Please add the output of `flutter doctor -v`.

To investigate we would need a minimal runnable reproduction
as a single file so that we can just copy your code into `lib/main.dart` of a new project and run to reproduce.

(Similar to #21683, #13367)

**Comment by zoechi** [comment]
Also please add the full error output instead of only a part of it.

**Comment by basnetjiten** [comment]
Another exception was thrown: ScrollController not attached to any scroll views.
I/flutter (18969): Another exception was thrown: ScrollController not attached to any scroll views.
E/flutter (18969): [ERROR:flutter/lib/ui/ui_dart_state.cc(148)] Unhandled Exception: 'package:flutter/src/widgets/scroll_controller.dart': Failed assertion: line 110 pos 12: '_positions.isNotEmpty': ScrollController not attached to any scroll views.
E/flutter (18969): #0      _AssertionError._doThrowNew (dart:core-patch/errors_patch.dart:40:39)
E/flutter (18969): #1      _AssertionError._throwNew (dart:core-patch/errors_patch.dart:36:5)
E/flutter (18969): #2      ScrollController.position (package:flutter/src/widgets/scroll_controller.dart:110:12)
E/flutter (18969): #3      _ExplorePageState._handleScrollNotification (package:ainflutter/views/tab_views/explore_tab_container.dart:115:27)
E/flutter (18969): #4      NotificationListener._dispatch (package:flutter/src/widgets/notification_listener.dart:127:27)
E/flutter (18969): #5      Notification.visitAncestor (package:flutter/src/widgets/notification_listener.dart:45:20)
E/flutter (18969): #6      _ScrollNotification&LayoutChangedNotification&ViewportNotificationMixin.visitAncestor (package:flutter/src/widgets/scroll_notification.dart:31:18)
E/flutter (18969): #7      Element.visitAncestorElements (package:flutter/src/widgets/framework.dart:3355:39)
E/flutter (18969): #8      Notification.dispatch (package:flutter/src/widgets/notification_listener.dart:61:13)
E/flutter (18969): #9      ScrollActivity.dispatchScrollEndNotification (package:flutter/src/widgets/scroll_activity.dart:106:63)
E/flutter (18969): #10     ScrollPosition.didEndScroll (package:flutter/src/widgets/scroll_position.dart:665:14)
E/flutter (18969): #11     ScrollPosition.beginActivity (package:flutter/src/widgets/scroll_position.dart:634:9)
E/flutter (18969): #12     ScrollPositionWithSingleContext.beginActivity (package:flutter/src/widgets/scroll_position_with_single_context.dart:117:11)
E/flutter (18969): #13     ScrollPositionWithSingleContext.goIdle (package:flutter/src/widgets/scroll_position_with_single_context.dart:132:5)
E/flutter (18969): #14     ScrollPositionWithSingleContext.goBallistic (package:flutter/src/widgets/scroll_position_with_single_context.dart:151:7)
E/flutter (18969): #15     BallisticScrollActivity._end (package:flutter/src/widgets/scroll_activity.dart:551:15)
E/flutter (18969): #16     _rootRun (dart:async/zone.dart:1120:38)
E/flutter (18969): #17     _CustomZone.run (dart:async/zone.dart:1021:19)
E/flutter (18969): #18     _FutureListener.handleWhenComplete (dart:async/future_impl.dart:150:18)
E/flutter (18969): #19     Future._propagateToListeners.handleWhenCompleteCallback (dart:async/future_impl.dart:609:39)
E/flutter (18969): #20     Future._propagateToListeners (dart:async/future_impl.dart:665:37)
E/flutter (18969): #21     Future._completeWithValue (dart:async/future_impl.dart:483:5)
E/flutter (18969): #22     Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:513:7)
E/flutter (18969): #23     _rootRun (dart:async/zone.dart:1124:13)
E/flutter (18969): #24     _CustomZone.run (dart:async/zone.dart:1021:19)
E/flutter (18969): #25     _CustomZone.runGuarded (dart:async/zone.dart:923:7)
E/flutter (18969): #26     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:963:23)
E/flutter (18969): #27     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
E/flutter (18969): #28     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
E/flutter (18969): 
I/flutter (18969): Another exception was thrown: ScrollController not attached to any scroll views.

**Comment by lukepighetti** [comment]
Ran into this today and the situation appears to stem from the following:

Create a PageController
StreamController with child PageView with controller
Conditionally hide PageView if there aren't any pages
Then try to build PageView again and it fails with the error

```
flutter: ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
flutter: The following assertion was thrown building StreamBuilder<List<String>>(dirty, state:
flutter: _StreamBuilderBaseState<List<String>, AsyncSnapshot<List<String>>>#17623):
flutter: ScrollController not attached to any scroll views.
flutter: 'package:flutter/src/widgets/scroll_controller.dart':
flutter: Failed assertion: line 110 pos 12: '_positions.isNotEmpty'
```

**Comment by rookie-12** [comment]
did you found the solution @lukepighetti ?
