### ISSUE TITLE
Crash when turning on Debug Painting

### ISSUE THREAD

**Issue by Nairou** [flutter/flutter#28406]
App error when toggling debug painting on. When toggled back off, page is cleared of content (not redrawn).

## Steps to Reproduce

I was able to reproduce it with a tiny sample app. No action required other than debugging it and toggling debug paint.

See: https://gist.github.com/Nairou/06309af47e5d9af951be7aa53bcc1220

On my real app (more complex layout) where I originally found this issue, the error is accompanied by the app crashing on the emulator (keeps running on a real device).

## Logs

When turning on Debug Painting:
```
Launching lib\main.dart on Pixel 2 XL in debug mode...
Built build\app\outputs\apk\debug\app-debug.apk.
I/flutter ( 7891): ══╡ EXCEPTION CAUGHT BY RENDERING LIBRARY ╞═════════════════════════════════════════════════════════
I/flutter ( 7891): The following assertion was thrown during paint():
I/flutter ( 7891): 'package:flutter/src/rendering/sliver_padding.dart': Failed assertion: line 334 pos 18:
I/flutter ( 7891): 'innerRect.bottom <= outerRect.bottom': is not true.
I/flutter ( 7891): 
I/flutter ( 7891): Either the assertion indicates an error in the framework itself, or we should provide substantially
I/flutter ( 7891): more information in this error message to help you determine and fix the underlying cause.
I/flutter ( 7891): In either case, please report this assertion by filing a bug on GitHub:
I/flutter ( 7891):   https://github.com/flutter/flutter/issues/new?template=BUG.md
I/flutter ( 7891): 
I/flutter ( 7891): When the exception was thrown, this was the stack:
I/flutter ( 7891): #2      RenderSliverPadding.debugPaint.<anonymous closure> 
I/flutter ( 7891): #3      RenderSliverPadding.debugPaint 
I/flutter ( 7891): #4      RenderObject._paintWithContext.<anonymous closure> 
I/flutter ( 7891): #5      RenderObject._paintWithContext 
I/flutter ( 7891): #6      PaintingContext.paintChild 
I/flutter ( 7891): #7      RenderViewportBase._paintContents 
I/flutter ( 7891): #8      RenderViewportBase.paint 
I/flutter ( 7891): #9      RenderObject._paintWithContext 
I/flutter ( 7891): #10     PaintingContext._repaintCompositedChild 
I/flutter ( 7891): #11     PaintingContext.repaintCompositedChild 
I/flutter ( 7891): #12     PipelineOwner.flushPaint 
I/flutter ( 7891): #13     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding.drawFrame 
I/flutter ( 7891): #14     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding&WidgetsBinding.drawFrame 
I/flutter ( 7891): #15     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding._handlePersistentFrameCallback 
I/flutter ( 7891): #16     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._invokeFrameCallback 
I/flutter ( 7891): #17     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.handleDrawFrame 
I/flutter ( 7891): #18     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._handleDrawFrame 
I/flutter ( 7891): #19     _invoke (dart:ui/hooks.dart:154:13)
I/flutter ( 7891): #20     _drawFrame (dart:ui/hooks.dart:143:3)
I/flutter ( 7891): (elided 2 frames from class _AssertionError)
I/flutter ( 7891): 
I/flutter ( 7891): The following RenderObject was being processed when the exception was fired:
I/flutter ( 7891):   RenderViewport#7c06a
I/flutter ( 7891):   creator: Viewport ← _ScrollableScope ← IgnorePointer-[GlobalKey#a1291] ← Semantics ← Listener ←
I/flutter ( 7891):   _GestureSemantics ← RawGestureDetector-[LabeledGlobalKey<RawGestureDetectorState>#e4952] ←
I/flutter ( 7891):   _ScrollSemantics-[GlobalKey#20cb8] ← RepaintBoundary ← CustomPaint ← RepaintBoundary ←
I/flutter ( 7891):   NotificationListener<ScrollNotification> ← ⋯
I/flutter ( 7891):   parentData: <none> (can use size)
I/flutter ( 7891):   constraints: BoxConstraints(0.0<=w<=411.4, h=774.9)
I/flutter ( 7891):   layer: OffsetLayer#3d181
I/flutter ( 7891):   size: Size(411.4, 774.9)
I/flutter ( 7891):   axisDirection: up
I/flutter ( 7891):   crossAxisDirection: right
I/flutter ( 7891):   offset: ScrollPositionWithSingleContext#f524c(offset: 0.0, range: 0.0..0.0, viewport: 774.9,
I/flutter ( 7891):   ScrollableState, AlwaysScrollableScrollPhysics -> ClampingScrollPhysics, IdleScrollActivity#3eefa,
I/flutter ( 7891):   ScrollDirection.idle)
I/flutter ( 7891):   anchor: 0.0
I/flutter ( 7891): This RenderObject had the following descendants (showing up to depth 5):
I/flutter ( 7891):   RenderSliverPadding#36e2d relayoutBoundary=up1
I/flutter ( 7891):     RenderSliverList#95eaf relayoutBoundary=up2
I/flutter ( 7891):       RenderIndexedSemantics#914c1 relayoutBoundary=up3
I/flutter ( 7891):         RenderRepaintBoundary#b92af relayoutBoundary=up4
I/flutter ( 7891):           RenderParagraph#39392 relayoutBoundary=up5
I/flutter ( 7891): ════════════════════════════════════════════════════════════════════════════════════════════════════
```

When turning Debug Painting back off:
```
I/flutter ( 7891): Another exception was thrown: Tried to paint a RenderObject reentrantly.
```

## Flutter Analyze
```
PS D:\dev\projects\crash_test> flutter analyze
Analyzing crash_test...
No issues found! (ran in 1.3s)
```

## Flutter Doctor
```
PS D:\dev\projects\crash_test> flutter doctor -v
[√] Flutter (Channel stable, v1.0.0, on Microsoft Windows [Version 10.0.17763.316], locale en-US)
    • Flutter version 1.0.0 at D:\dev\tools\flutter
    • Framework revision 5391447fae (3 months ago), 2018-11-29 19:41:26 -0800
    • Engine revision 7375a0f414
    • Dart version 2.1.0 (build 2.1.0-dev.9.4 f9ebf21297)

[√] Android toolchain - develop for Android devices (Android SDK 28.0.3)
    • Android SDK at C:\Users\nairou\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)
    • All Android licenses accepted.

[√] Android Studio (version 3.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)

[√] VS Code (version 1.31.1)
    • VS Code at C:\Users\nairou\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 2.23.0

[√] Connected device (2 available)
    • Pixel 2 XL                • 710KPAE0206352 • android-arm64 • Android 9 (API 28)
    • Android SDK built for x86 • emulator-5554  • android-x86   • Android 9 (API 28) (emulator)

• No issues found!
```

**Comment by zoechi** [comment]
I can reproduce with
```
[✓] Flutter (Channel master, v1.2.3-pre.31, on Mac OS X 10.14.3 18D42, locale en-AT)
```

**Comment by kevinespaldon** [comment]
Weird but it's only happening on VSCode, not on the Android Studio

**Comment by mkiisoft** [comment]
Happening on Android Studio:

`Flutter (Channel master, v1.6.2-pre.29, on Mac OS X 10.14.5 18F132, locale en-US)`

Both on Android and iOS.

**Comment by miquelbeltran** [comment]
Happening to me with: 
```
[✓] Flutter (Channel beta, v1.7.8+hotfix.3, on Mac OS X 10.14.5 18F132, locale en-DE)
    • Flutter version 1.7.8+hotfix.3 at /Users/miquel/dev/tools/flutter
    • Framework revision b712a172f9 (9 days ago), 2019-07-09 13:14:38 -0700
    • Engine revision 54ad777fd2
    • Dart version 2.4.0

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/miquel/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 10.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.2.1, Build version 10E1001
    • CocoaPods version 1.7.0

[✓] iOS tools - develop for iOS devices
    • ios-deploy 1.9.4

[✓] IntelliJ IDEA Ultimate Edition (version 2019.1.3)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 37.0.3
    • Dart plugin version 191.7830

[✓] Connected device (1 available)
    • iPhone X • 118AF3BE-C730-4748-8F48-58E04E9CA921 • ios • com.apple.CoreSimulator.SimRuntime.iOS-12-2 (simulator)

• No issues found!
```

Only with iOS devices.

**Comment by chunhtai** [comment]
This should only happens when you have AxisDirection.up of vertical scroll view( in this case the reverse = true), or AxisDirection.left of horizontal scroll view.

It throws exception because the code does not calculate innerRect and outerRect correctly.

**Comment by miquelbeltran** [comment]
that's my case indeed, as as I have an inverted ListView
