### ISSUE TITLE
flutter crash help

### ISSUE THREAD

**Issue by larademirjian** [flutter/flutter#28401]
```
I/flutter (24314): #133    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.scheduleWarmUpFrame.<anonymous closure> 
package:flutter/…/scheduler/binding.dart:751
I/flutter (24314): #135    _Timer._runTimers (dart:isolate/runtime/libtimer_impl.dart:382:19)
Reloaded 3 of 422 libraries in 1,769ms.
I/flutter (24314): #136    _Timer._handleMessage (dart:isolate/runtime/libtimer_impl.dart:416:5)
I/flutter (24314): #137    _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:171:12)
I/flutter (24314): (elided 3 frames from class _AssertionError and package dart:async)
I/flutter (24314): ════════════════════════════════════════════════════════════════════════════════════════════════════
I/flutter (24314): Another exception was thrown: 'package:flutter/src/painting/image_resolution.dart': Failed assertion: line 134 pos 15: 'assetName != null': is not true.
I/flutter (24314): Another exception was thrown: A RenderFlex overflowed by 199629 pixels on the right.
I/flutter (24314): Another exception was thrown: A RenderFlex overflowed by 99317 pixels on the bottom.
```

**Comment by jonahwilliams** [comment]
It looks like you've cut off the top of the stack trace, that is where the actual error is located and we can't help you without it. Please also include the output of `flutter doctor -v` and a sample which can reproduce the exception.
