### ISSUE TITLE
A error was thrown when leave animated widget

### ISSUE THREAD

**Issue by alphamikle** [flutter/flutter#28403]
## Steps to Reproduce
I have this widget, wich is animated all time. When i leave page, wich has this animated widget - flutter throw a error. If i come to page, wich have a animated widget - it's okay working next and i dont have any problem with this, but i write this issue, maybe it's a really bug.
```
import 'dart:math';

import 'package:flutter/material.dart';
import 'package:wave/config.dart';
import 'package:wave/wave.dart';

class Wave extends StatefulWidget {
  final Duration duration;
  Wave({this.duration});
  @override
  _WaveState createState() => _WaveState(duration: duration);
}

class _WaveState extends State<Wave> with TickerProviderStateMixin {
  Duration duration;
  _WaveState({this.duration});
  AnimationController _aController;
  List<Animation> _waveTweens = [];
  List<Color> _waveColors = [
    Colors.white,
    Colors.white,
    Colors.white,
    Colors.white,
    Colors.white,
    Colors.white,
    Colors.white,
    Colors.white,
  ];

  int getRandomHex({int max = 4294967295}) {
    return Random().nextInt(max);
  }

  void initAnimationController() {
    _aController = AnimationController(vsync: this, duration: duration);
  }

  void initTweens(List<Color> colors, List<Color> oldColors) {
    int index = 0;
    _waveTweens = oldColors.map((Color oldColor) {
      var tween = ColorTween(begin: oldColor, end: colors[index]).animate(_aController);
      index++;
      return tween;
    }).toList();
    _waveColors = colors;
  }

  List<Color> getRandomColors() {
    var colors = _waveColors.map((Color color) {
      var colorValue = getRandomHex();
      var opacity = getRandomHex(max: 100) / 100;
      var color = Color(colorValue).withOpacity(opacity);
      return color;
    }).toList();
    return colors;
  }

  @override
  void initState() {
    _waveColors = getRandomColors();
    if (duration == null) {
      duration = Duration(seconds: 2);
    }
    initAnimationController();
    super.initState();
    animateWave();
  }

  @override
  void dispose() {
    _aController.value = 1;
    _aController.stop();
    _aController.dispose();
    _aController = null;
    super.dispose();
  }

  void animateWave() async {
    initTweens(getRandomColors(), _waveColors);
    if (_aController != null) {
      _aController.forward(from: 0);
    }
    await Future.delayed(duration);
    animateWave();
  }

  @override
  Widget build(BuildContext context) {
    return AnimatedBuilder(
      animation: _waveTweens[0],
      builder: (context, child) {
        return WaveWidget(
            config: CustomConfig(
              gradients: [
                [_waveTweens[0].value, _waveTweens[1].value],
                [_waveTweens[2].value, _waveTweens[3].value],
                [_waveTweens[4].value, _waveTweens[5].value],
                [_waveTweens[6].value, _waveTweens[7].value],
              ],
              durations: [48000, 24000, 12000, 6000],
              heightPercentages: [0, 0.1, 0.2, 0.6],
              blur: MaskFilter.blur(BlurStyle.solid, 15),
              gradientBegin: Alignment.bottomLeft,
              gradientEnd: Alignment.topRight,
            ),
            size: Size(double.infinity, 300));
      },
    );
  }
}
```
## Logs

```
Performing hot restart...
Syncing files to device Android SDK built for x86...
Restarted application in 1 592ms.
I/flutter ( 4991): null
I/flutter ( 4991): ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
I/flutter ( 4991): The following assertion was thrown while finalizing the widget tree:
I/flutter ( 4991): 'package:flutter/src/widgets/framework.dart': Failed assertion: line 3485 pos 12:
I/flutter ( 4991): '_debugLifecycleState != _ElementLifecycle.defunct': is not true.
I/flutter ( 4991): 
I/flutter ( 4991): Either the assertion indicates an error in the framework itself, or we should provide substantially
I/flutter ( 4991): more information in this error message to help you determine and fix the underlying cause.
I/flutter ( 4991): In either case, please report this assertion by filing a bug on GitHub:
I/flutter ( 4991):   https://github.com/flutter/flutter/issues/new?template=BUG.md
I/flutter ( 4991): 
I/flutter ( 4991): When the exception was thrown, this was the stack:
I/flutter ( 4991): #2      Element.markNeedsBuild (package:flutter/src/widgets/framework.dart:3485:12)
I/flutter ( 4991): #3      State.setState (package:flutter/src/widgets/framework.dart:1138:14)
I/flutter ( 4991): #4      _ScannerState.dispose (package:quich/screens/scanner.dart:20:5)
I/flutter ( 4991): #5      StatefulElement.unmount (package:flutter/src/widgets/framework.dart:3916:12)
I/flutter ( 4991): #6      _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1696:13)
I/flutter ( 4991): #7      ListIterable.forEach (dart:_internal/iterable.dart:39:13)
I/flutter ( 4991): #8      _InactiveElements._unmountAll (package:flutter/src/widgets/framework.dart:1705:25)
I/flutter ( 4991): #9      BuildOwner.finalizeTree.<anonymous closure> (package:flutter/src/widgets/framework.dart:2359:27)
I/flutter ( 4991): #10     BuildOwner.lockState (package:flutter/src/widgets/framework.dart:2191:15)
I/flutter ( 4991): #11     BuildOwner.finalizeTree (package:flutter/src/widgets/framework.dart:2358:7)
I/flutter ( 4991): #12     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding&WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:702:18)
I/flutter ( 4991): #13     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:275:5)
I/flutter ( 4991): #14     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:990:15)
I/flutter ( 4991): #15     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:930:9)
I/flutter ( 4991): #16     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:842:5)
I/flutter ( 4991): #20     _invoke (dart:ui/hooks.dart:209:10)
I/flutter ( 4991): #21     _drawFrame (dart:ui/hooks.dart:168:3)
I/flutter ( 4991): (elided 5 frames from class _AssertionError and package dart:async)
I/flutter ( 4991): ════════════════════════════════════════════════════════════════════════════════════════════════════

```

```
No issues found! (ran in 2.8s)
```

```
[√] Flutter (Channel dev, v1.2.2, on Microsoft Windows [Version 10.0.17763.316], locale ru-RU)
    • Flutter version 1.2.2 at C:\flutter
    • Framework revision 007a415c2a (2 days ago), 2019-02-21 20:22:47 -0800
    • Engine revision f1f19bba8f
    • Dart version 2.2.0 (build 2.2.0-dev.2.1 c92d5ca288)

[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at C:\Users\alpha\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)
    • All Android licenses accepted.

[√] Android Studio (version 3.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 33.1.1
    • Dart plugin version 182.5215
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)

[√] VS Code, 64-bit edition (version 1.30.2)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Flutter extension version 2.22.1

[√] Connected device (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 9 (API 28) (emulator)

• No issues found!
```

**Comment by YDJSZY** [comment]
I have the same problem。I wrote a animation,when I leave the page that flutter throw a error:
'_debugLifecycleState != _ElementLifecycle.defunct': is not true.

**Comment by deadsoul44** [comment]
What is the solution?

**Comment by Xgamefactory** [comment]
i guess solutions was  to just closing issue
