### ISSUE TITLE
FileSystemException

### ISSUE THREAD

**Issue by lx36301766** [flutter/flutter#28427]
Flutter crash report; please file at https://github.com/flutter/flutter/issues.

## command

flutter packages upgrade

## exception
```
FileSystemException: FileSystemException: Cannot open file, path = 'G:\flutter\sdk\bin\cache\artifacts\engine\android-arm-release/windows-x64\gen_snapshot.exe' (OS Error: 拒绝访问（access denied）。
, errno = 5)
```
```
#0      _File.throwIfError (dart:io/file_impl.dart:643:7)
#1      _File.openSync (dart:io/file_impl.dart:487:5)
#2      _File.writeAsBytesSync (dart:io/file_impl.dart:612:31)
#3      _LocalFile&LocalFileSystemEntity&ForwardingFile.writeAsBytesSync (package:file/src/forwarding/forwarding_file.dart:124:16)
#4      _WindowsUtils._unpackArchive (package:flutter_tools/src/base/os.dart:235:16)
#5      _WindowsUtils.unzip (package:flutter_tools/src/base/os.dart:191:5)
#6      CachedArtifact._downloadArchive.<anonymous closure> (package:flutter_tools/src/cache.dart:314:16)
<asynchronous suspension>
#7      CachedArtifact._withDownloadFile (package:flutter_tools/src/cache.dart:333:26)
<asynchronous suspension>
#8      CachedArtifact._downloadArchive (package:flutter_tools/src/cache.dart:300:12)
#9      CachedArtifact._downloadZipArchive (package:flutter_tools/src/cache.dart:320:12)
#10     FlutterEngine.updateInner (package:flutter_tools/src/cache.dart:508:13)
<asynchronous suspension>
#11     CachedArtifact.update (package:flutter_tools/src/cache.dart:263:11)
<asynchronous suspension>
#12     Cache.updateAll (package:flutter_tools/src/cache.dart:219:26)
<asynchronous suspension>
#13     FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:534:19)
<asynchronous suspension>
#14     FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:486:33)
<asynchronous suspension>
#15     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:142:29)
<asynchronous suspension>
#16     _rootRun (dart:async/zone.dart:1124:13)
#17     _CustomZone.run (dart:async/zone.dart:1021:19)
#18     _runZoned (dart:async/zone.dart:1516:10)
#19     runZoned (dart:async/zone.dart:1463:12)
#20     AppContext.run (package:flutter_tools/src/base/context.dart:141:18)
<asynchronous suspension>
#21     FlutterCommand.run (package:flutter_tools/src/runner/flutter_command.dart:477:20)
#22     CommandRunner.runCommand (package:args/command_runner.dart:196:27)
<asynchronous suspension>
#23     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:396:21)
<asynchronous suspension>
#24     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:142:29)
<asynchronous suspension>
#25     _rootRun (dart:async/zone.dart:1124:13)
#26     _CustomZone.run (dart:async/zone.dart:1021:19)
#27     _runZoned (dart:async/zone.dart:1516:10)
#28     runZoned (dart:async/zone.dart:1463:12)
#29     AppContext.run (package:flutter_tools/src/base/context.dart:141:18)
<asynchronous suspension>
#30     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:356:19)
<asynchronous suspension>
#31     CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:111:29)
#32     new Future.sync (dart:async/future.dart:224:31)
#33     CommandRunner.run (package:args/command_runner.dart:111:11)
#34     FlutterCommandRunner.run (package:flutter_tools/src/runner/flutter_command_runner.dart:242:18)
#35     run.<anonymous closure> (package:flutter_tools/runner.dart:60:20)
<asynchronous suspension>
#36     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:142:29)
<asynchronous suspension>
#37     _rootRun (dart:async/zone.dart:1124:13)
#38     _CustomZone.run (dart:async/zone.dart:1021:19)
#39     _runZoned (dart:async/zone.dart:1516:10)
#40     runZoned (dart:async/zone.dart:1463:12)
#41     AppContext.run (package:flutter_tools/src/base/context.dart:141:18)
<asynchronous suspension>
#42     runInContext (package:flutter_tools/src/context_runner.dart:50:24)
<asynchronous suspension>
#43     run (package:flutter_tools/runner.dart:51:10)
#44     main (package:flutter_tools/executable.dart:59:9)
<asynchronous suspension>
#45     main (file:///G:/flutter/sdk/packages/flutter_tools/bin/flutter_tools.dart:8:3)
#46     _startIsolate.<anonymous closure> (dart:isolate/runtime/libisolate_patch.dart:298:32)
#47     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:171:12)
```

## flutter doctor

```
[32m[✓][39m Flutter (Channel master, v1.2.3-pre.29, on Microsoft Windows [Version 10.0.16299.15], locale zh-CN)
    [32m•[39m Flutter version 1.2.3-pre.29 at G:\flutter\sdk
    [32m•[39m Framework revision 57a8b03c5e (6 hours ago), 2019-02-24 11:53:43 +0100
    [32m•[39m Engine revision 90fcaff900
    [32m•[39m Dart version 2.2.0 (build 2.2.0-dev.2.1 c92d5ca288)

[32m[✓][39m Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    [32m•[39m Android SDK at G:\Android\sdk
    [32m•[39m Android NDK location not configured (optional; useful for native profiling support)
    [32m•[39m Platform android-28, build-tools 28.0.3
    [32m•[39m ANDROID_HOME = G:\Android\sdk
    [32m•[39m Java binary at: G:\Android\Android Studio\jre\bin\java
    [32m•[39m Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)
    [32m•[39m All Android licenses accepted.

[32m[✓][39m Android Studio (version 3.3)
    [32m•[39m Android Studio at G:\Android\Android Studio
    [32m•[39m Flutter plugin version 33.0.1
    [32m•[39m Dart plugin version 182.5215
    [32m•[39m Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)

[32m[✓][39m IntelliJ IDEA Community Edition (version 2018.3)
    [32m•[39m IntelliJ at G:\Android\IntelliJ IDEA
    [32m•[39m Flutter plugin version 31.3.4
    [32m•[39m Dart plugin version 183.5153.38

[33m[!][39m Connected device
    [33m![39m No devices available

[33m![39m Doctor found issues in 1 category.
```

**Comment by zoechi** [comment]
Looks like a permission issue on your machine. Perhaps an anti-virus app interfering?
