### ISSUE TITLE
'_debugCanPerformMutations': is not true.

### ISSUE THREAD

**Issue by homerosbart2** [flutter/flutter#28434]
## Description

Hello, I'm trying to use ```AnimatedCrossFade``` to change between two forms (the login form and the register form). The app works fine, it does how I want to, but i get the following exception when the hot reload is make or when I press the register button (REGISTRAR). 

```

I/flutter (18467): ══╡ EXCEPTION CAUGHT BY ANIMATION LIBRARY ╞═════════════════════════════════════════════════════════
I/flutter (18467): The following assertion was thrown while notifying listeners for AnimationController:
I/flutter (18467): 'package:flutter/src/rendering/object.dart': Failed assertion: line 1409 pos 12:
I/flutter (18467): '_debugCanPerformMutations': is not true.
I/flutter (18467): 
I/flutter (18467): Either the assertion indicates an error in the framework itself, or we should provide substantially
I/flutter (18467): more information in this error message to help you determine and fix the underlying cause.
I/flutter (18467): In either case, please report this assertion by filing a bug on GitHub:
I/flutter (18467):   https://github.com/flutter/flutter/issues/new?template=BUG.md
I/flutter (18467): 
I/flutter (18467): When the exception was thrown, this was the stack:
I/flutter (18467): #2      RenderObject.markNeedsLayout 
package:flutter/…/rendering/object.dart:1409
I/flutter (18467): #3      RenderBox.markNeedsLayout 
package:flutter/…/rendering/box.dart:1842
I/flutter (18467): #4      new RenderAnimatedSize.<anonymous closure> 
package:flutter/…/rendering/animated_size.dart:93
I/flutter (18467): #5      _AnimationController&Animation&AnimationEagerListenerMixin&AnimationLocalListenersMixin.notifyListeners 
package:flutter/…/animation/listener_helpers.dart:124
I/flutter (18467): #6      AnimationController._animateToInternal 
package:flutter/…/animation/animation_controller.dart:529
I/flutter (18467): #7      AnimationController.forward 
package:flutter/…/animation/animation_controller.dart:442
I/flutter (18467): #8      RenderAnimatedSize._layoutStable 
package:flutter/…/rendering/animated_size.dart:227
I/flutter (18467): #9      RenderAnimatedSize.performLayout 
package:flutter/…/rendering/animated_size.dart:180
I/flutter (18467): #10     RenderObject.layout 
package:flutter/…/rendering/object.dart:1634
I/flutter (18467): #11     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout 
package:flutter/…/rendering/proxy_box.dart:104
I/flutter (18467): #12     _RenderCustomClip.performLayout 
package:flutter/…/rendering/proxy_box.dart:1188
I/flutter (18467): #13     RenderObject.layout 
package:flutter/…/rendering/object.dart:1634
I/flutter (18467): #14     RenderFlex.performLayout 
package:flutter/…/rendering/flex.dart:798
I/flutter (18467): #15     RenderObject.layout 
package:flutter/…/rendering/object.dart:1634
I/flutter (18467): #16     RenderPositionedBox.performLayout 
package:flutter/…/rendering/shifted_box.dart:385
I/flutter (18467): #17     RenderObject._layoutWithoutResize 
package:flutter/…/rendering/object.dart:1509
I/flutter (18467): #18     PipelineOwner.flushLayout 
package:flutter/…/rendering/object.dart:768
I/flutter (18467): #19     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding.drawFrame 
package:flutter/…/rendering/binding.dart:281
I/flutter (18467): #20     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding&WidgetsBinding.drawFrame 
package:flutter/…/widgets/binding.dart:677
I/flutter (18467): #21     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding._handlePersistentFrameCallback 
package:flutter/…/rendering/binding.dart:219
I/flutter (18467): #22     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._invokeFrameCallback 
package:flutter/…/scheduler/binding.dart:990
I/flutter (18467): #23     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.handleDrawFrame 
package:flutter/…/scheduler/binding.dart:930
I/flutter (18467): #24     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._handleDrawFrame 
package:flutter/…/scheduler/binding.dart:842
I/flutter (18467): #25     _invoke (dart:ui/hooks.dart:154:13)
I/flutter (18467): #26     _drawFrame (dart:ui/hooks.dart:143:3)
I/flutter (18467): (elided 2 frames from class _AssertionError)
I/flutter (18467): 
I/flutter (18467): The AnimationController notifying listeners was:
I/flutter (18467):   AnimationController#a0715(⏮ 1.000; paused)
I/flutter (18467): ════════════════════════════════════════════════════════════════════════════════════════════════════

```

## Code

```dart
Widget _loginForm(){
    return Column(
      mainAxisAlignment: MainAxisAlignment.center,
      children: <Widget>[
        Container(
          margin: EdgeInsets.only(bottom: 12.0),
          child: RichText(
            text: TextSpan(
              text: 'Classroom',
              style: TextStyle(
                fontFamily: 'Vampiro One',
                color: Colors.white,
                fontSize: 50.0,
                //fontWeight: FontWeight.bold,
                shadows: <Shadow>[
                  Shadow(
                    offset: Offset(0, 2),
                    blurRadius: 12.0,
                    color: Color.fromARGB(20, 0, 0, 0),
                  ),
                ],
              ),
            ),
          ),
        ),
        StatefulTextfield(
          suffix: '',
          color: Colors.white,
          helper: 'Nombre de usuario.',
          label: 'Usuario',
          type: TextInputType.text,
          onChangedFunction: (String value){
            this.setState(() {   
            });
          },
        ),
        //ELEMENT: Campo para la CONTRASEÑA.
        StatefulTextfield(
          suffix: '',
          color: Colors.white,
          helper: 'Contraseña del usuario.',
          label: 'Contraseña',
          type: TextInputType.text,
          isObscure: true,
          onChangedFunction: (String value){
            this.setState(() {   
            });
          },
        ),
        Container(
          margin: EdgeInsets.only(top: 12),
          child: Row(
            mainAxisAlignment: MainAxisAlignment.spaceBetween,
            children: <Widget>[
              StatefulButton(
                text: 'REGISTRARSE',
                color: Theme.of(context).primaryColor,
                onTap: (){
                  setState(() {
                    _register = true;
                  });
                },
                type: 'a',
                weight: FontWeight.bold,
              ),
              StatefulButton(
                text: 'INICIAR',
                color: Colors.white,
                borderColor: Theme.of(context).primaryColor,
                fillColor: Theme.of(context).primaryColor,
                onTap: (){
                  //TODO: Hay que verificar que el usuario tenga cuenta en la base de datos y verificar el hash.
                },
              ),
            ],
          ),
        ),
      ],
    );
  }

Widget build(BuildContext context) {
    final loginWidget = FractionallySizedBox(
      widthFactor: 1,
      heightFactor: 1,
      child: GestureDetector(
        onTap: (){
          print('TAAAAP');
          FocusScope.of(context).requestFocus(new FocusNode());
        },
        child: Container(
          decoration: BoxDecoration(
            image: DecorationImage(
              image: AssetImage('lib/assets/images/bg.jpg'),
              fit: BoxFit.cover,
            ),
          ),
          padding: EdgeInsets.all(25.0),
          alignment: Alignment(0, 0),
          child: Column(
            mainAxisAlignment: MainAxisAlignment.center,
            children: <Widget>[
              Expanded(
                child: AnimatedCrossFade(
                  firstChild: _loginForm(),
                  secondChild: _registerForm(),
                  duration: Duration(milliseconds: 0),
                  crossFadeState: _register ? CrossFadeState.showSecond : CrossFadeState.showFirst,
                ),
              ),
              RichText(
                text: TextSpan(
                  text: 'Copyright © Diego Alay & Henry Campos',
                  style: TextStyle(
                    fontFamily: 'Roboto Condensed',
                    color: Colors.white,
                    fontSize: 12.0,
                    //fontWeight: FontWeight.bold,
                    shadows: <Shadow>[
                      Shadow(
                        offset: Offset(0, 2),
                        blurRadius: 12.0,
                        color: Color.fromARGB(20, 0, 0, 0),
                      ),
                    ],
                  ),
                ),
              ),
            ],
          ),
        ),
      ),
    );

    return Scaffold(
      body: loginWidget,
    );
  }
```

## Flutter Diagnostics
```
[√] Flutter (Channel stable, v1.0.0, on Microsoft Windows [Version 10.0.17134.523], locale en-US)
    • Flutter version 1.0.0 at C:\src\flutter
    • Framework revision 5391447fae (3 months ago), 2018-11-29 19:41:26 -0800
    • Engine revision 7375a0f414
    • Dart version 2.1.0 (build 2.1.0-dev.9.4 f9ebf21297)

[√] Android toolchain - develop for Android devices (Android SDK 28.0.3)
    • Android SDK at C:\Users\hcamp\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)
    • All Android licenses accepted.

[√] Android Studio (version 3.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 31.3.3
    • Dart plugin version 182.5124
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)

[√] VS Code (version 1.31.1)
    • VS Code at C:\Users\hcamp\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 2.23.1

[√] VS Code, 64-bit edition (version 1.27.2)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Flutter extension version 2.23.1

[√] Connected device (1 available)
    • LYA L09 • F3R7N18B16003214 • android-arm64 • Android 9 (API 28)
```

**Comment by zoechi** [comment]
Similar error in #9663
Can you please complete the code to make a running example (incl. `main() {...}`, imports, ...)

**Comment by homerosbart2** [comment]
# Files
The following sections are the files in my project, but I can't attach the fonts that I'm using, so I will paste the link to my repository:
[https://github.com/homerosbart2/classroom](url)
## main.dart
```
import 'package:flutter/material.dart';
import 'package:classroom/login.dart';

void main() {
  runApp(Classroom());
}

class Classroom extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      debugShowCheckedModeBanner: false,
      title: 'Classroom',
      theme: ThemeData(fontFamily: 'Roboto Condensed', primaryColor: Color.fromARGB(255, 255, 96, 64)),
      home: Login(),
    );
  }
}
```
## login.dart
```
import 'package:flutter/material.dart';
import 'package:classroom/stateful_textfield.dart';
import 'package:classroom/stateful_button.dart';

class Login extends StatefulWidget {
  const Login();

  @override
  _LoginState createState() => _LoginState();
}

class _LoginState extends State<Login> {
  FocusNode myFocusNode;
  bool _register;
  TextEditingController _usernameController;
  TextEditingController _passwordController;

  @override
  void initState() {
    super.initState();
    _register = false;
    myFocusNode = FocusNode();
    _usernameController = new TextEditingController();
    _passwordController = new TextEditingController();
  }

  Widget _registerForm(){
    return Column(
      mainAxisAlignment: MainAxisAlignment.center,
      children: <Widget>[
        StatefulTextfield(
          suffix: '',
          color: Colors.white,
          helper: 'Nombre de usuario.',
          label: 'Usuario',
          type: TextInputType.text,
          onChangedFunction: (String value){
            this.setState(() {   
            });
          },
          controller: _usernameController,
        ),
        //ELEMENT: Campo para la CONTRASEÑA.
        StatefulTextfield(
          suffix: '',
          color: Colors.white,
          helper: 'Contraseña del usuario.',
          label: 'Contraseña',
          type: TextInputType.text,
          isObscure: true,
          onChangedFunction: (String value){
            this.setState(() {   
            });
          },
          controller: _passwordController,
        ),
        StatefulTextfield(
          suffix: '',
          color: Colors.white,
          helper: 'Contraseña del usuario.',
          label: 'Contraseña',
          type: TextInputType.text,
          isObscure: true,
          onChangedFunction: (String value){
            this.setState(() {   
            });
          },
        ),
        Container(
          margin: EdgeInsets.only(top: 12),
          child: Row(
            mainAxisAlignment: MainAxisAlignment.spaceBetween,
            children: <Widget>[
              StatefulButton(
                text: 'CANCELAR',
                color: Theme.of(context).primaryColor,
                onTap: (){
                  setState(() {
                    _register = false;
                  });
                },
                type: 'a',
                weight: FontWeight.bold,
              ),
              StatefulButton(
                text: 'ACEPTAR',
                color: Colors.white,
                borderColor: Theme.of(context).primaryColor,
                fillColor: Theme.of(context).primaryColor,
                onTap: (){
                  //TODO: Hay que verificar que el usuario tenga cuenta en la base de datos y verificar el hash.
                },
              ),
            ],
          ),
        ),
      ],
    );
  }

  Widget _loginForm(){
    return Column(
      mainAxisAlignment: MainAxisAlignment.center,
      children: <Widget>[
        Container(
          margin: EdgeInsets.only(bottom: 12.0),
          child: RichText(
            text: TextSpan(
              text: 'Classroom',
              style: TextStyle(
                fontFamily: 'Vampiro One',
                color: Colors.white,
                fontSize: 50.0,
                //fontWeight: FontWeight.bold,
                shadows: <Shadow>[
                  Shadow(
                    offset: Offset(0, 2),
                    blurRadius: 12.0,
                    color: Color.fromARGB(20, 0, 0, 0),
                  ),
                ],
              ),
            ),
            
          ),
        ),
        StatefulTextfield(
          suffix: '',
          color: Colors.white,
          helper: 'Nombre de usuario.',
          label: 'Usuario',
          type: TextInputType.text,
          onChangedFunction: (String value){
            this.setState(() {   
            });
          },
          controller: _usernameController,
        ),
        //ELEMENT: Campo para la CONTRASEÑA.
        StatefulTextfield(
          suffix: '',
          color: Colors.white,
          helper: 'Contraseña del usuario.',
          label: 'Contraseña',
          type: TextInputType.text,
          isObscure: true,
          onChangedFunction: (String value){
            this.setState(() {   
            });
          },
          controller: _passwordController,
        ),
        Container(
          margin: EdgeInsets.only(top: 12),
          child: Row(
            mainAxisAlignment: MainAxisAlignment.spaceBetween,
            children: <Widget>[
              StatefulButton(
                text: 'REGISTRARSE',
                color: Theme.of(context).primaryColor,
                onTap: (){
                  setState(() {
                    _register = true;
                  });
                },
                type: 'a',
                weight: FontWeight.bold,
              ),
              StatefulButton(
                text: 'INICIAR',
                color: Colors.white,
                borderColor: Theme.of(context).primaryColor,
                fillColor: Theme.of(context).primaryColor,
                onTap: (){
                  //TODO: Hay que verificar que el usuario tenga cuenta en la base de datos y verificar el hash.
                },
              ),
            ],
          ),
        )
      ],
    );
  }

  @override
  Widget build(BuildContext context) {
    final loginWidget = FractionallySizedBox(
      widthFactor: 1,
      heightFactor: 1,
      child: GestureDetector(
        onTap: (){
          print('TAAAAP');
          FocusScope.of(context).requestFocus(new FocusNode());
        },
        child: Container(
          decoration: BoxDecoration(
            image: DecorationImage(
              image: AssetImage('lib/assets/images/bg.jpg'),
              fit: BoxFit.cover,
            ),
          ),
          padding: EdgeInsets.all(25.0),
          alignment: Alignment(0, 0),
          child: Column(
            mainAxisAlignment: MainAxisAlignment.center,
            children: <Widget>[
              Expanded(
                child: AnimatedCrossFade(
                  firstChild: _loginForm(),
                  secondChild: _registerForm(),
                  duration: Duration(milliseconds: 0),
                  crossFadeState: _register ? CrossFadeState.showSecond : CrossFadeState.showFirst,
                ),
              ),
              RichText(
                text: TextSpan(
                  text: 'Copyright © Diego Alay & Henry Campos',
                  style: TextStyle(
                    fontFamily: 'Roboto Condensed',
                    color: Colors.white,
                    fontSize: 12.0,
                    //fontWeight: FontWeight.bold,
                    shadows: <Shadow>[
                      Shadow(
                        offset: Offset(0, 2),
                        blurRadius: 12.0,
                        color: Color.fromARGB(20, 0, 0, 0),
                      ),
                    ],
                  ),
                ),
              ),
            ],
          ),
        ),
      ),
    );

    return Scaffold(
      body: loginWidget,
    );
  }
}
```
## stateful_textfield.dart
```
import 'package:flutter/material.dart';
import 'package:classroom/textfield_bloc.dart';

class StatefulTextfield extends StatefulWidget {
  final String suffix;
  final Color color;
  final String helper;
  final String label;
  final TextInputType type;
  final TextfieldBloc channel;
  final Function onChangedFunction;
  final bool isObscure;
  final TextEditingController controller;

  const StatefulTextfield({
    @required this.suffix,
    @required this.color,
    @required this.helper,
    @required this.label,
    this.controller,
    this.type,
    this.channel,
    this.onChangedFunction,
    this.isObscure,
  });

  @override
  _StatefulTextfieldState createState() => _StatefulTextfieldState();
}

class _StatefulTextfieldState extends State<StatefulTextfield> {
  String _actualSuffixSelected;
  bool _obscured;

  @override
  void initState() {
    super.initState();
    this._actualSuffixSelected = widget.suffix;
    if(widget.isObscure != null){
      this._obscured = widget.isObscure;
    }else{
      this._obscured = false;
    }
  }

  Widget baseTextfield(String suffix){
    return Container(
      margin: EdgeInsets.fromLTRB(0.0, 10.0, 0.0, 10.0),
      child: TextField(
          onChanged: (String value){
            if(widget.onChangedFunction != null){
              widget.onChangedFunction(value);
            }
          },
          controller: widget.controller,
          obscureText: this._obscured,
          //textAlign: TextAlign.center,
          keyboardType: widget.type,
          decoration: InputDecoration(
            //fillColor: Colors.white,
            //filled: true,
            suffixText: suffix,
            suffixStyle: TextStyle(
              color: widget.color,
            ),
            labelText: widget.label,
            hintStyle: TextStyle(
              color: Colors.grey,
            ),
            //hintText: 'Insert an input.',
            helperText: widget.helper,
            helperStyle: TextStyle(
              color: Colors.white,
            ),
            labelStyle: TextStyle(
              color: Colors.white,
              fontWeight: FontWeight.normal,
            ),
            focusedBorder: OutlineInputBorder(
              borderSide: BorderSide(
                color: widget.color,
                width: 3.0,
              ),
              borderRadius: BorderRadius.circular(4.0),
            ),
            hasFloatingPlaceholder: true,
            enabledBorder: OutlineInputBorder(
              borderSide: BorderSide(
                color: Colors.white,
                width: 1.0,
              ),
              borderRadius: BorderRadius.circular(4.0),
            ),
            border: OutlineInputBorder(
              borderSide: BorderSide(
                style: BorderStyle.solid,
              ),
            ),
          ),
          style: TextStyle(
            fontFamily: 'Roboto Condensed',
            fontSize: 24.0,
            //color: Color.fromARGB(255, 0, 11, 43),
            color: Colors.redAccent[100],
            fontWeight: FontWeight.w700,
          ),
          cursorColor: Colors.redAccent[100],
        ),
    );
  }

  Widget build(BuildContext context) {
    if(widget.channel == null){
      return baseTextfield(this._actualSuffixSelected);
    }else{
      return StreamBuilder(
        stream: widget.channel.updateSuffixOut,
        initialData: _actualSuffixSelected,
        builder: (context, snapshot) => baseTextfield(snapshot.data),
      );
    }
  }
}
```
## stateful_button.dart
```
import 'package:flutter/material.dart';

class StatefulButton extends StatefulWidget{
  final Function onTap;
  final String type, text;
  final Color borderColor, fillColor, color;
  final FontWeight weight;

  const StatefulButton({
    @required this.onTap,
    @required this.text,
    @required this.color,
    this.type,
    this.borderColor,
    this.fillColor,
    this.weight,
  });

  @override
  _StatefulButtonState createState() => _StatefulButtonState();
}

class _StatefulButtonState extends State<StatefulButton>{
  EdgeInsetsGeometry _padding;
  FontWeight _weight;
  Color _fillColor, _borderColor;
  BorderStyle _borderStyle;

  @override
  void initState() {
    super.initState();
    if(widget.type == 'a'){
      _padding = EdgeInsets.fromLTRB(0, 0, 0, 0);
      _borderStyle = BorderStyle.none;
      _fillColor = Colors.transparent;
      _borderColor = Colors.transparent;
    }else{
      _padding = EdgeInsets.fromLTRB(25, 0, 25, 0);
      _borderStyle = BorderStyle.solid;
      if(widget.borderColor != null){
        _borderColor = widget.borderColor;
      }else{
        _borderColor = Colors.white;
      }

      if(widget.fillColor != null){
        _fillColor = widget.fillColor;
      }else{
        _fillColor = Colors.transparent;
      }
    }

    if(widget.weight == null){
      _weight = FontWeight.normal;
    }else{
      _weight = widget.weight;
    }
  }

  Widget build(BuildContext context){
    return GestureDetector(
      onTap: (){
        widget.onTap();
      },
      child: Container(
        alignment: Alignment(0, 0),
        padding: _padding,
        height: 50,
        decoration: ShapeDecoration(
          color: _fillColor,
          shape: RoundedRectangleBorder(
            side: BorderSide(
              width: 1.0, 
              style: _borderStyle,
              color: _borderColor,
            ),
            borderRadius: BorderRadius.all(Radius.circular(5.0)),
          ),
        ),
        child: RichText(
          text: TextSpan(
            text: widget.text,
            style: TextStyle(
              fontSize: 18,
              fontFamily: 'Roboto Condensed',
              fontWeight: _weight,
              color: widget.color,
            ),
          ),
        ),
      ),
    );
  }
}
```
## pubspec.yaml
```
name: classroom
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# Read more about versioning at semver.org.
version: 1.0.0+1

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  rxdart: ^0.20.0
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_launcher_icons: "^0.7.0"
  flutter_test:
    sdk: flutter

flutter_icons:
  android: "launcher_icon" 
  ios: true
  image_path: "C:/Users/hcamp/Documents/Flutter/classroom/lib/assets/icon/icon3.png"
  # flutter packages pub run flutter_launcher_icons:main

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - lib/assets/images/bg.jpg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Vampiro One
      fonts:
        - asset: lib/assets/fonts/VampiroOne-Regular.ttf
    - family: Roboto Condensed
      fonts:
        - asset: lib/assets/fonts/RobotoCondensed-Regular.ttf
        - asset: lib/assets/fonts/RobotoCondensed-Bold.ttf
          weight: 700
        - asset: lib/assets/fonts/RobotoCondensed-Light.ttf
          weight: 100
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages

```

**Comment by zoechi** [comment]
@homerosbart2 can you please strip the code that is not absolutely necessary to reproduce?

**Comment by zoechi** [comment]
Also please check if you can still reproduce with Flutter `dev` channel
```
flutter channel dev
flutter doctor
```

**Comment by Sh1d0w** [comment]
@zoechi I have the same problem. It seems it is caused if the duration for `AnimatedCrossFade` is set to 0. If I set it to 1 second it does not throw that exception.

**Comment by Sh1d0w** [comment]
Well, I just provided more info...

**Comment by BondarenkoStas** [comment]
Is the issue still relevant?

**Comment by zanecidan** [comment]
I'm also facing this issue but I noticed some behaviors:
1. It only happened on my Honor 9 Lite and during Debug mode. When it happens the whole app hang and became not responsive.
2. My Xiaomi A1 didn't have this problem.
3. The problem also only happened so far on pages that require internet.

Hope the above info helps.

**Comment by iapicca** [comment]
Hi @homerosbart2 
could you please provide your updated  `flutter doctor -v`, 
your `flutter run --verbose` and  a minimal code sample to reproduce the problem?
Thank you

**Comment by iapicca** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact descriptions what happens, logs and the output of 'flutter doctor -v'  please.
All system setups can be slightly different so its always better to open new issues and reference related issues.
