### ISSUE TITLE
Flutter Build issue AndroidStudio 3.3.1 stuck

### ISSUE THREAD

**Issue by niravrmc28** [flutter/flutter#28444]
When I try to run flutter project android studio stuck and whole system hang. Cant' event shutdown desktop. 
```
PC configuration:
Host Name:                 DESKTOP-UGVE7E1
OS Name:                   Microsoft Windows 10 Pro
OS Version:                10.0.17134 N/A Build 17134
OS Manufacturer:       Microsoft Corporation
OS Configuration:       Standalone Workstation
RAM:                           8 GB
Processor:	           Intel(R) Core(TM) i5-7400 CPU @ 3.00GHz, 3000 Mhz, 4 Core(s), 4 Logical Processor(s)
```

Log File:
```
Caused by: java.lang.IllegalArgumentException: Argument for @NotNull parameter 'launchMode' of io/flutter/run/daemon/FlutterApp.setLaunchMode must not be null
	at io.flutter.run.daemon.FlutterApp.$$$reportNull$$$0(FlutterApp.java)
	at io.flutter.run.daemon.FlutterApp.setLaunchMode(FlutterApp.java)
	at io.flutter.run.daemon.FlutterAppDaemonEventListener.onAppStarting(FlutterApp.java:726)
	at io.flutter.run.daemon.DaemonEvent$AppStarting.accept(DaemonEvent.java:190)
	at io.flutter.run.daemon.DaemonEvent.dispatch(DaemonEvent.java:52)
	at io.flutter.run.daemon.DaemonApi.dispatch(DaemonApi.java:171)
	at io.flutter.run.daemon.DaemonApi$1.onTextAvailable(DaemonApi.java:142)
	... 20 more
2019-02-25 11:09:48,678 [lutter.bat]  ERROR - ecution.process.ProcessHandler - Android Studio 3.3.1  Build #AI-182.5107.16.33.5264788 
2019-02-25 11:09:48,678 [lutter.bat]  ERROR - ecution.process.ProcessHandler - JDK: 1.8.0_152-release 
2019-02-25 11:09:48,678 [lutter.bat]  ERROR - ecution.process.ProcessHandler - VM: OpenJDK 64-Bit Server VM 
2019-02-25 11:09:48,678 [lutter.bat]  ERROR - ecution.process.ProcessHandler - Vendor: JetBrains s.r.o 
2019-02-25 11:09:48,678 [lutter.bat]  ERROR - ecution.process.ProcessHandler - OS: Windows 10 
2019-02-25 11:09:48,678 [lutter.bat]  ERROR - ecution.process.ProcessHandler - Last Action: Run 
2019-02-25 11:17:18,127 [ain Thread]   INFO -        #com.intellij.idea.Main - ------------------------------------------------------ IDE STARTED ------------------------------------------------------ 
2019-02-25 11:17:18,159 [e-1248-b01]   INFO -        #com.intellij.idea.Main - IDE: Android Studio (build #AI-182.5107.16.33.5264788, 29 Jan 2019 05:18) 
2019-02-25 11:17:18,159 [e-1248-b01]   INFO -        #com.intellij.idea.Main - OS: Windows 10 (10.0, amd64) 
2019-02-25 11:17:18,159 [e-1248-b01]   INFO -        #com.intellij.idea.Main - JRE: 1.8.0_152-release-1248-b01 (JetBrains s.r.o) 
2019-02-25 11:17:18,159 [e-1248-b01]   INFO -        #com.intellij.idea.Main - JVM: 25.152-b01 (OpenJDK 64-Bit Server VM) 
2019-02-25 11:17:18,160 [e-1248-b01]   INFO -        #com.intellij.idea.Main - JVM Args: -Xms256m -Xmx1280m -XX:ReservedCodeCacheSize=240m -XX:+UseConcMarkSweepGC -XX:SoftRefLRUPolicyMSPerMB=50 -Dsun.io.useCanonCaches=false -Djava.net.preferIPv4Stack=true -Djdk.http.auth.tunneling.disabledSchemes="" -Djna.nosys=true -Djna.boot.library.path= -da -Djb.vmOptionsFile=F:\android-studio-ide-182.5199772-windows\android-studio\bin\studio64.exe.vmoptions -Didea.platform.prefix=AndroidStudio -Didea.jre.check=true -Dide.native.launcher=true -Didea.paths.selector=AndroidStudio3.3 -XX:ErrorFile=C:\Users\Admin\java_error_in_studio_%p.log -XX:HeapDumpPath=C:\Users\Admin\java_error_in_studio.hprof 
2019-02-25 11:17:18,160 [e-1248-b01]   INFO -        #com.intellij.idea.Main - ext: F:\android-studio-ide-182.5199772-windows\android-studio\jre\jre\lib\ext: [access-bridge-64.jar, cldrdata.jar, dnsns.jar, jaccess.jar, localedata.jar, meta-index, nashorn.jar, sunec.jar, sunjce_provider.jar, sunmscapi.jar, sunpkcs11.jar, zipfs.jar] 
2019-02-25 11:17:18,160 [e-1248-b01]   INFO -        #com.intellij.idea.Main - charsets: JNU=Cp1252 file=Cp1252 
2019-02-25 11:17:18,255 [e-1248-b01]   INFO -        #com.intellij.idea.Main - JNA library (64-bit) loaded in 95 ms 
2019-02-25 11:17:18,275 [e-1248-b01]   INFO - penapi.util.io.win32.IdeaWin32 - Native filesystem for Windows is operational 
2019-02-25 11:17:18,817 [e-1248-b01]   INFO -     #com.intellij.util.ui.JBUI - User scale factor: 1.0 
2019-02-25 11:17:19,518 [entQueue-0]   INFO - .intellij.idea.IdeaApplication - CPU cores: 4; ForkJoinPool.commonPool: java.util.concurrent.ForkJoinPool@63ddec13[Running, parallelism = 3, size = 0, active = 0, running = 0, steals = 0, tasks = 0, submissions = 0]; factory: com.intellij.concurrency.IdeaForkJoinWorkerThreadFactory@21180b6d 
2019-02-25 11:17:19,832 [entQueue-0]   INFO -     #com.intellij.util.ui.JBUI - System scale factor: 1.0 (JRE-managed HiDPI) 
2019-02-25 11:17:23,312 [entQueue-0]   INFO - llij.ide.plugins.PluginManager - Cannot find optional descriptor duplicates-groovy.xml 
2019-02-25 11:17:25,982 [entQueue-0]   INFO - llij.ide.plugins.PluginManager - 40 plugins initialized in 5424 ms 
2019-02-25 11:17:25,983 [entQueue-0]   INFO - llij.ide.plugins.PluginManager - Loaded bundled plugins: Android APK Support (1.0), Android Games (1.0), Android NDK Support (1.0), Android Support (10.3.3.1), App Links Assistant (0.1), CVS Integration (11), Copyright (8.1), Coverage (182.5107.16.33.5264788), EditorConfig (182.5107.16.33.5264788), Firebase App Indexing (0.1), Firebase Services (0.1), Firebase Testing (1.0), Git Integration (8.1), GitHub (182.5107.16.33.5264788), Google Cloud Tools Core (0.2.8), Google Cloud Tools For Android Studio (0.2.8), Google Developers Samples (0.3.1), Google Login (1.0), Google Services (0.1), Gradle (182.5107.16.33.5264788), Groovy (9.0), I18n for Java (182.5107.16.33.5264788), IDEA CORE (182.5107.16.33.5264788), IntelliLang (8.0), JUnit (1.0), Java Bytecode Decompiler (182.5107.16.33.5264788), Java Stream Debugger (182.5107.16.33.5264788), Kotlin (1.3.20-release-Studio3.3-1), Mercurial Integration (10.0), Properties Support (182.5107.16.33.5264788), Settings Repository (182.5107.16.33.5264788), Smali Support (1.0), Subversion Integration (1.1), Task Management (1.0), Terminal (0.1), Test Recorder (1.0), TestNG-J (8.0), YAML (182.5107.16.33.5264788) 
2019-02-25 11:17:25,983 [entQueue-0]   INFO - llij.ide.plugins.PluginManager - Loaded custom plugins: Dart (182.5215), Flutter (33.1.1) 
2019-02-25 11:17:36,285 [entQueue-0]   INFO - ellij.util.io.PagedFileStorage - lower=100; upper=500; buffer=10; max=1226 
2019-02-25 11:17:36,618 [entQueue-0]   INFO - pl.local.NativeFileWatcherImpl - Starting file watcher: F:\android-studio-ide-182.5199772-windows\android-studio\bin\fsnotifier64.exe 
2019-02-25 11:17:36,734 [entQueue-0]   INFO - pl.local.NativeFileWatcherImpl - Native file watcher is operational. 
2019-02-25 11:17:37,654 [entQueue-0]   INFO - tellij.openapi.util.IconLoader - replace '/nodes/newFolder.png' with 'AllIcons.Nodes.Folder' 
2019-02-25 11:17:50,929 [entQueue-0]   WARN - nSystem.impl.ActionManagerImpl - keymap "Xcode" not found [Plugin: com.android.tools.ndk] 
2019-02-25 11:17:50,931 [entQueue-0]   WARN - nSystem.impl.ActionManagerImpl - keymap "Xcode" not found [Plugin: com.android.tools.ndk] 
2019-02-25 11:17:50,932 [entQueue-0]   WARN - nSystem.impl.ActionManagerImpl - keymap "Xcode" not found [Plugin: com.android.tools.ndk] 
2019-02-25 11:17:58,954 [entQueue-0]   INFO - til.net.ssl.CertificateManager - Default SSL context initialized 
2019-02-25 11:17:59,303 [d thread 5]   INFO - rains.ide.BuiltInServerManager - built-in server started, port 63342 
2019-02-25 11:17:59,983 [e-1248-b01]   INFO - j.ide.ui.OptionsTopHitProvider - 3435 ms spent to cache options in application 
2019-02-25 11:17:59,983 [e-1248-b01]   INFO - .openapi.application.Preloader - com.intellij.ide.ui.OptionsTopHitProvider$Activity took 3435 ms 
2019-02-25 11:18:00,009 [entQueue-0]   INFO - gs.impl.UpdateCheckerComponent - channel: release 
2019-02-25 11:18:03,478 [entQueue-0]   INFO - il.indexing.FileBasedIndexImpl - Index exts enumerated:2825, number of extensions:46 
2019-02-25 11:18:04,297 [entQueue-0]   INFO - il.indexing.FileBasedIndexImpl - Index scheduled:819 
2019-02-25 11:18:04,478 [entQueue-0]   INFO - tellij.psi.stubs.StubIndexImpl - All stub exts enumerated:76, number of extensions:50 
2019-02-25 11:18:04,478 [entQueue-0]   INFO - tellij.psi.stubs.StubIndexImpl - stub exts update scheduled:0 
2019-02-25 11:18:21,363 [entQueue-0]   INFO - ellij.project.impl.ProjectImpl - 19 project components initialized in 14048 ms 
```

**Comment by zoechi** [comment]
Issue moved to [flutter/flutter-intellij #3228](https://github.com/flutter/flutter-intellij/issues/3228) via [**ZenHub**](https://www.zenhub.com/)
