### ISSUE TITLE
App crashes when calling GoogleMap() widget

### ISSUE THREAD

**Issue by sdresche17** [flutter/flutter#28445]
Steps to Reproduce
     1. get google_maps_flutter: `google_maps_flutter: ^0.2.0+5`
     2. add API key to manifest.xml
     3. import plugin: `import 'package:google_maps_flutter/google_maps_flutter.dart';`
     4. Call the widget:

```dart
Container(
                         child: _mapToggle?
                         GoogleMap(
                           onMapCreated: _onMapCreated,
                               initialCameraPosition: CameraPosition(
                                target: LatLng(_currentLocation.latitude,
                                     _currentLocation.longitude),
                                 zoom: 14.0,
                               )
                         ) :
                         Center(
                             child: Column(
                                 mainAxisAlignment: MainAxisAlignment.center,
                                 crossAxisAlignment: CrossAxisAlignment.center,
                                 children: <Widget>[
                                   CircularProgressIndicator(),
                                   Padding(
                                     padding: EdgeInsets.all(12.0),
                                     child: Text('Loading please wait...',
                                       style: TextStyle(
                                           color: Colors.white, fontSize: 16.0),),
                                   )
                                 ]
                             )
                         ),
                       ),
```
 ```dart
void _onMapCreated(GoogleMapController controller) {
     setState(() {
       mapController = controller;
     });
   }
```

 I run my app and get the following:

```
Launching lib\main.dart on Android SDK built for x86 in debug mode...
Initializing gradle...
Resolving dependencies...
Gradle task 'assembleDebug'...
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
Built build\app\outputs\apk\debug\app-debug.apk.
Installing build\app\outputs\apk\app.apk...
Syncing files to device Android SDK built for x86...
I/Choreographer(17765): Skipped 120 frames!  The application may be doing too much work on its main thread.
D/EGL_emulation(17765): eglMakeCurrent: 0xe9dce100: ver 3 0 (tinfo 0xe666dfd0)
I/OpenGLRenderer(17765): Davey! duration=2182ms; Flags=1, IntendedVsync=16244241998858, Vsync=16246241998778, OldestInputEvent=9223372036854775807, NewestInputEvent=0, HandleInputStart=16246255546060, AnimationStart=16246256411760, PerformTraversalsStart=16246258007160, DrawStart=16246276637360, SyncQueued=16246278792360, SyncStart=16246285170060, IssueDrawCommandsStart=16246287155060, SwapBuffers=16246359328160, FrameCompleted=16246430391460, DequeueBufferDuration=29705000, QueueBufferDuration=2169000, 
I/flutter (17765): Starting
I/flutter (17765): DATA READ
W/Firestore(17765): (0.6.6-dev) [Firestore]: The behavior for java.util.Date objects stored in Firestore is going to change AND YOUR APP MAY BREAK.
W/Firestore(17765): To hide this warning and ensure your app does not break, you need to add the following code to your app before calling any other Cloud Firestore methods:
W/Firestore(17765): 
W/Firestore(17765): FirebaseFirestore firestore = FirebaseFirestore.getInstance();
W/Firestore(17765): FirebaseFirestoreSettings settings = new FirebaseFirestoreSettings.Builder()
W/Firestore(17765):     .setTimestampsInSnapshotsEnabled(true)
W/Firestore(17765):     .build();
W/Firestore(17765): firestore.setFirestoreSettings(settings);
W/Firestore(17765): 
W/Firestore(17765): With this change, timestamps stored in Cloud Firestore will be read back as com.google.firebase.Timestamp objects instead of as system java.util.Date objects. So you will also need to update code expecting a java.util.Date to instead expect a Timestamp. For example:
W/Firestore(17765): 
W/Firestore(17765): // Old:
W/Firestore(17765): java.util.Date date = snapshot.getDate("created_at");
W/Firestore(17765): // New:
W/Firestore(17765): Timestamp timestamp = snapshot.getTimestamp("created_at");
W/Firestore(17765): java.util.Date date = timestamp.toDate();
W/Firestore(17765): 
W/Firestore(17765): Please audit all existing usages of java.util.Date when you enable the new behavior. In a future release, the behavior will be changed to the new behavior, so if you do not follow these steps, YOUR APP MAY BREAK.
W/DynamiteModule(17765): Local module descriptor class for providerinstaller not found.
I/DynamiteModule(17765): Considering local module providerinstaller:0 and remote module providerinstaller:0
W/ProviderInstaller(17765): Failed to load providerinstaller module: No acceptable module found. Local version is 0 and remote version is 0.
I/com.rtw.rtw(17765): The ClassLoaderContext is a special shared library.
I/chatty  (17765): uid=10086(com.rtw.rtw) FirestoreWorker identical 1 line
I/com.rtw.rtw(17765): The ClassLoaderContext is a special shared library.
V/NativeCrypto(17765): Registering com/google/android/gms/org/conscrypt/NativeCrypto's 287 native methods...
W/com.rtw.rtw(17765): Accessing hidden method Ljava/security/spec/ECParameterSpec;->getCurveName()Ljava/lang/String; (light greylist, reflection)
D/NetworkSecurityConfig(17765): No Network Security Config specified, using platform default
W/com.rtw.rtw(17765): Accessing hidden field Ljavax/net/ssl/SSLSocketFactory;->defaultSocketFactory:Ljavax/net/ssl/SSLSocketFactory; (light greylist, reflection)
W/com.rtw.rtw(17765): Accessing hidden field Ljavax/net/ssl/SSLServerSocketFactory;->defaultServerSocketFactory:Ljavax/net/ssl/SSLServerSocketFactory; (light greylist, reflection)
I/ProviderInstaller(17765): Installed default security provider GmsCore_OpenSSL
I/com.rtw.rtw(17765): Background concurrent copying GC freed 16605(1995KB) AllocSpace objects, 7(140KB) LOS objects, 49% free, 1821KB/3MB, paused 4.997ms total 461.823ms
D/        (17765): HostConnection::get() New Host Connection established 0xe8012c80, tid 17805
D/EGL_emulation(17765): eglMakeCurrent: 0xe9dcde60: ver 3 0 (tinfo 0xe8003d70)
I/zzbz    (17765): Making Creator dynamically
W/com.rtw.rtw(17765): Unsupported class loader
W/com.rtw.rtw(17765): Skipping duplicate class check due to unsupported classloader
I/DynamiteModule(17765): Considering local module com.google.android.gms.maps_dynamite:0 and remote module com.google.android.gms.maps_dynamite:221
I/DynamiteModule(17765): Selected remote version of com.google.android.gms.maps_dynamite, version >= 221
V/DynamiteModule(17765): Dynamite loader version >= 2, using loadModule2NoCrashUtils
D/        (17765): HostConnection::get() New Host Connection established 0xcf71f6c0, tid 17784
D/        (17765): HostConnection::get() New Host Connection established 0xd26fd000, tid 17783
W/com.rtw.rtw(17765): Accessing hidden field Ljava/nio/Buffer;->address:J (light greylist, reflection)
W/com.rtw.rtw(17765): Unsupported class loader
W/com.rtw.rtw(17765): Skipping duplicate class check due to unsupported classloader
I/Google Maps Android API(17765): Google Play services client version: 12451000
I/Google Maps Android API(17765): Google Play services package version: 15090040
W/com.rtw.rtw(17765): Accessing hidden field Ljava/net/Socket;->impl:Ljava/net/SocketImpl; (light greylist, reflection)
W/com.rtw.rtw(17765): Accessing hidden method Ldalvik/system/CloseGuard;->get()Ldalvik/system/CloseGuard; (light greylist, linking)
W/com.rtw.rtw(17765): Accessing hidden method Ldalvik/system/CloseGuard;->open(Ljava/lang/String;)V (light greylist, linking)
W/com.rtw.rtw(17765): Accessing hidden method Ljava/net/InetAddress;->isNumeric(Ljava/lang/String;)Z (light greylist, reflection)
W/com.rtw.rtw(17765): Accessing hidden field Ljava/io/FileDescriptor;->descriptor:I (light greylist, JNI)
W/com.rtw.rtw(17765): Accessing hidden method Ljava/security/spec/ECParameterSpec;->setCurveName(Ljava/lang/String;)V (light greylist, reflection)
W/com.rtw.rtw(17765): Accessing hidden method Ldalvik/system/BlockGuard;->getThreadPolicy()Ldalvik/system/BlockGuard$Policy; (light greylist, linking)
W/com.rtw.rtw(17765): Accessing hidden method Ldalvik/system/BlockGuard$Policy;->onNetwork()V (light greylist, linking)
I/com.rtw.rtw(17765): Background concurrent copying GC freed 21385(1867KB) AllocSpace objects, 0(0B) LOS objects, 49% free, 2MB/5MB, paused 17.620ms total 324.173ms
E/AndroidRuntime(17765): FATAL EXCEPTION: Thread-4
E/AndroidRuntime(17765): Process: com.rtw.rtw, PID: 17765
E/AndroidRuntime(17765): java.lang.NoClassDefFoundError: Failed resolution of: Lorg/apache/http/ProtocolVersion;
E/AndroidRuntime(17765): 	at fb.b(:com.google.android.gms.dynamite_mapsdynamite@15090084@15.0.90 (100700-231259764):3)
E/AndroidRuntime(17765): 	at fa.a(:com.google.android.gms.dynamite_mapsdynamite@15090084@15.0.90 (100700-231259764):3)
E/AndroidRuntime(17765): 	at fc.a(:com.google.android.gms.dynamite_mapsdynamite@15090084@15.0.90 (100700-231259764):15)
E/AndroidRuntime(17765): 	at com.google.maps.api.android.lib6.drd.al.a(:com.google.android.gms.dynamite_mapsdynamite@15090084@15.0.90 (100700-231259764):6)
E/AndroidRuntime(17765): 	at ee.a(:com.google.android.gms.dynamite_mapsdynamite@15090084@15.0.90 (100700-231259764):23)
E/AndroidRuntime(17765): 	at ee.run(:com.google.android.gms.dynamite_mapsdynamite@15090084@15.0.90 (100700-231259764):8)
E/AndroidRuntime(17765): Caused by: java.lang.ClassNotFoundException: Didn't find class "org.apache.http.ProtocolVersion" on path: DexPathList[[zip file "/data/user_de/0/com.google.android.gms/app_chimera/m/0000000d/MapsDynamite.apk"],nativeLibraryDirectories=[/data/user_de/0/com.google.android.gms/app_chimera/m/0000000d/MapsDynamite.apk!/lib/x86, /system/lib]]
E/AndroidRuntime(17765): 	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:134)
E/AndroidRuntime(17765): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
E/AndroidRuntime(17765): 	at ad.loadClass(:com.google.android.gms.dynamite_dynamiteloader@15090084@15.0.90 (100700-231259764):4)
E/AndroidRuntime(17765): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
E/AndroidRuntime(17765): 	... 6 more
I/Process (17765): Sending signal. PID: 17765 SIG: 9
Lost connection to device.
```

Flutter Doctor:

```
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, v1.0.0, on Microsoft Windows [Version 10.0.17134.590], locale en-US)
[√] Android toolchain - develop for Android devices (Android SDK 28.0.3)
[√] Android Studio (version 3.3)
[√] VS Code (version 1.31.1)
[√] Connected device (1 available)

• No issues found!
```

**Comment by zoechi** [comment]
> FirebaseFirestore firestore = FirebaseFirestore.getInstance();

Doesn't look related to google maps

**Comment by sdresche17** [comment]
Isn't that a generic warning? I've seen that before, the app this code is running in doesn't pull any timestamps from firestore. Everything runs fine when I comment out the GoogleMaps widget.

**Comment by zoechi** [comment]
So meant 

>     java.lang.NoClassDefFoundError: Failed resolution of: Lorg/apache/http/ProtocolVersion;

Didn't read that far.

**Comment by sdresche17** [comment]
Is there a workaround, or what do I need to do/do you need more info?

**Comment by sdresche17** [comment]
I added: `<uses-library android:name="org.apache.http.legacy" android:required="false"/>` to my manifest.xml and it worked.

**Comment by DeepStyles** [comment]
I had same issue with Firestore added to my app. I checked my manifest.xml above line exist already.

**Comment by sam-toon** [comment]
This looks to be the same as issue #28630

**Comment by iskakaushik** [comment]
Let me know if this is still an issue.

**Comment by kroikie** [comment]
@sdresche17

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/416. Any further collaboration will be done there.
