### ISSUE TITLE
NullPointerException: Attempt to invoke virtual method 'float android.view.InputDevice$MotionRange.getMin()' on a null object reference

### ISSUE THREAD

**Issue by hartmannj** [flutter/flutter#28490]
Google Pre-Launch report gave me a bunch of errors. One of them is following error which seems to be somewhere inside the Flutter framework. I have a strong feeling it has to do with the TextFormField since it crashes right at the Login screen.

Device: Huawei Mate 9, Android 7.0
```
java.lang.NullPointerException: Attempt to invoke virtual method 'float android.view.InputDevice$MotionRange.getMin()' on a null object reference
	at io.flutter.view.FlutterView.addPointerForIndex(FlutterView.java:468)
	at io.flutter.view.FlutterView.onTouchEvent(FlutterView.java:530)
	at android.view.View.dispatchTouchEvent(View.java:10011)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2671)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2301)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2671)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2301)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2671)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2301)
	at com.android.internal.policy.DecorView.superDispatchTouchEvent(DecorView.java:447)
	at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1871)
	at android.app.Activity.dispatchTouchEvent(Activity.java:3213)
	at com.android.internal.policy.DecorView.dispatchTouchEvent(DecorView.java:409)
	at android.view.View.dispatchPointerEvent(View.java:10231)
	at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:4851)
	at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4711)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4244)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4297)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4263)
	at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:4390)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4271)
	at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:4447)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4244)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4297)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4263)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4271)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4244)
	at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:6671)
	at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:6645)
	at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:6606)
	at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:6798)
	at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:192)
	at android.os.MessageQueue.nativePollOnce(Native Method)
	at android.os.MessageQueue.next(MessageQueue.java:330)
	at android.os.Looper.loop(Looper.java:138)
	at android.app.ActivityThread.main(ActivityThread.java:6524)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:941)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:831)
```
Doctor output:

```
Flutter version 1.2.3-pre.45
Framework revision d7b0aab634 (3 hours ago), 2019-02-26 10:34:03 +0800
Engine revision f7306394e3
Dart version 2.2.0 (build 2.2.0-dev.2.1 c92d5ca288)
```

**Comment by paozhuanyinyu** [comment]
the same problem to Android  device, try ios Simulator

**Comment by Altevir** [comment]
the same problem in Android device, Motorola Moto G6/Android 8.0.0

**Comment by AmSn6** [comment]
Im getting that error when I Click on AppBar. I got popupmenuButton and search Icon Button in my app bar. when i click on popupButton my app crashes and returns the same error... How to clear that error?

**Comment by gdxz123** [comment]
how to fix this bug?

**Comment by gdxz123** [comment]
the same problem in Android device, Redmi/Android 8.0.0
Flutter version v1.2.1

What should I do to fix this crash ?
