### ISSUE TITLE
flutter upgrade crashed 

### ISSUE THREAD

**Issue by feinstein** [flutter/flutter#28525]
I runned `flutter upgrade` at the same time as IntelliJ IDEA was compiling my app to `run` it into an Android emulator. Then IntelliJ IDEA told me there were upgrades to IntelliJ IDEA and the Flutter and Dart plugins, so I decided to select them to upgrade at the same time.

This way the `cmd` instance running `flutter upgrade` crashed after a while, the report it generated is below.

I understand this is a stress test scenario, but still I thought it would be nice to share.

PS: I would like to know why `flutter doctor` sees *IntelliJ IDEA Ultimate Edition (version 2018.2* if I don't have this version anymore.

## Logs

Flutter crash report; please file at https://github.com/flutter/flutter/issues.

## command

flutter --no-color --no-version-check precache

## exception
```
FileSystemException: FileSystemException: Cannot delete file, path = 'C:\Programacao\Flutter\sdk\flutter\bin\cache\downloads\storage.googleapis.com\flutter_infra\flutter\3757390fa4b00d2d261bfdf5182d2e87c9113ff9\sky_engine.zip' (OS Error: The system cannot find the path specified.
, errno = 3)
```
```
#0      _File.throwIfError (dart:io/file_impl.dart:643:7)
#1      _File._deleteSync (dart:io/file_impl.dart:306:5)
#2      FileSystemEntity.deleteSync (dart:io/file_system_entity.dart:466:47)
#3      ForwardingFileSystemEntity.deleteSync (package:file/src/forwarding/forwarding_file_system_entity.dart:72:16)
#4      CachedArtifact._removeDownloadedFiles (package:flutter_tools/src/cache.dart:271:9)
#5      CachedArtifact.update (package:flutter_tools/src/cache.dart:265:5)
<asynchronous suspension>
#6      Cache.updateAll (package:flutter_tools/src/cache.dart:219:26)
<asynchronous suspension>
#7      PrecacheCommand.runCommand (package:flutter_tools/src/commands/precache.dart:33:19)
<asynchronous suspension>
#8      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:545:18)
#9      _asyncThenWrapperHelper.<anonymous closure> (dart:async/runtime/libasync_patch.dart:77:64)
#10     _rootRunUnary (dart:async/zone.dart:1132:38)
#11     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#12     _FutureListener.handleValue (dart:async/future_impl.dart:126:18)
#13     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:639:45)
#14     Future._propagateToListeners (dart:async/future_impl.dart:668:32)
#15     Future._complete (dart:async/future_impl.dart:473:7)
#16     _SyncCompleter.complete (dart:async/future_impl.dart:51:12)
#17     _AsyncAwaitCompleter.complete.<anonymous closure> (dart:async/runtime/libasync_patch.dart:33:20)
#18     _rootRun (dart:async/zone.dart:1124:13)
#19     _CustomZone.run (dart:async/zone.dart:1021:19)
#20     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:947:23)
#21     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#22     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#23     _runPendingImmediateCallback (dart:isolate/runtime/libisolate_patch.dart:115:13)
#24     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:172:5)
```

## flutter doctor

```
[✓] Flutter (Channel stable, v1.2.1, on Microsoft Windows [Version 10.0.17763.316], locale en-US)
    • Flutter version 1.2.1 at C:\Programacao\Flutter\sdk\flutter
    • Framework revision 8661d8aecd (12 days ago), 2019-02-14 19:19:53 -0800
    • Engine revision 3757390fa4
    • Dart version 2.1.2 (build 2.1.2-dev.0.0 0a7dcf17eb)

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at C:\Programacao\Android\Sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)
    • All Android licenses accepted.

[✓] Android Studio (version 3.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 33.0.1
    • Dart plugin version 182.5215
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)

[!] IntelliJ IDEA Ultimate Edition (version 2018.2)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA 2018.1.5
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.io/intellij-setup/#installing-the-plugins

[✓] IntelliJ IDEA Ultimate Edition (version 2018.3)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA 2018.3
    • Flutter plugin version 33.0.6
    • Dart plugin version 183.5901

[✓] VS Code (version 1.30.2)
    • VS Code at C:\Users\Michel Feinstein\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 2.21.1

[✓] Connected device (1 available)
    • Android SDK built for x86 64 • emulator-5554 • android-x64 • Android 5.0.2 (API 21) (emulator)

! Doctor found issues in 1 category.
```

**Comment by feinstein** [comment]
Apparently, besides the error, `flutter upgrade` worked fine because now I have version 1.2.1

**Comment by zoechi** [comment]
Seems to be a permission issue in.
Is `C:\Programacao` the equivalent of `C:\Program Files`? Flutter is not supposed to be installed into this directory because it requires elevated privileges for write access.

Please consider asking support questions in one of the other channels listed at http://flutter.io/support .

**Comment by feinstein** [comment]
No, it's not, `Programacao` means `Programming` in Portuguese, it's just a folder I use to hold SDKs.

`'C:\Programacao\Flutter\sdk\flutter\bin\cache\downloads\` was empty, so I think it tried to delete something that was already deleted before, does it makes sense?

**Comment by zoechi** [comment]
I see.
