### ISSUE TITLE
Setting up the Engine development environment error

### ISSUE THREAD

**Issue by wangqianjun** [flutter/flutter#28561]
when i Setting up the Engine development environment, run `gclient sync` get the error

Traceback (most recent call last):
  File "/Users/arthur/work/coding/depot_tools/gclient.py", line 99, in <module>
    import urlparse
ModuleNotFoundError: No module named 'urlparse'

Python 3.6.5
macOS High Sierra 10.13.4

**Comment by wangqianjun** [comment]
I solved this problem by lowering the python version.
Bug get another error:

gclient sync
Syncing projects: 100% (85/85), done.

________ running '/anaconda3/bin/python src/tools/dart/update.py' in '/Users/arthur/work/study/engine'
Traceback (most recent call last):
  File "src/tools/dart/update.py", line 92, in <module>
    sys.exit(main())
  File "src/tools/dart/update.py", line 82, in main
    urllib.urlretrieve(sdk_url, output_file)
  File "/anaconda3/lib/python2.7/urllib.py", line 94, in urlretrieve
    return _urlopener.retrieve(url, filename, reporthook, data)
  File "/anaconda3/lib/python2.7/urllib.py", line 240, in retrieve
    fp = self.open(url, data)
  File "/anaconda3/lib/python2.7/urllib.py", line 208, in open
    return getattr(self, name)(url)
  File "/anaconda3/lib/python2.7/urllib.py", line 345, in open_http
    h.endheaders(data)
  File "/anaconda3/lib/python2.7/httplib.py", line 991, in endheaders
    self._send_output(message_body)
  File "/anaconda3/lib/python2.7/httplib.py", line 844, in _send_output
    self.send(msg)
  File "/anaconda3/lib/python2.7/httplib.py", line 806, in send
    self.connect()
  File "/anaconda3/lib/python2.7/httplib.py", line 787, in connect
    self.timeout, self.source_address)
  File "/anaconda3/lib/python2.7/socket.py", line 571, in create_connection
    raise err
IOError: [Errno socket error] [Errno 60] Operation timed out
Error: Command '/anaconda3/bin/python src/tools/dart/update.py' returned non-zero exit status 1 in /Users/arthur/work/study/engine
Hook '/anaconda3/bin/python src/tools/dart/update.py' took 75.81 secs

**Comment by jaelintu** [comment]
@wangqianjun have you solved?

**Comment by wangqianjun** [comment]
@jaelintu Add a proxy to the terminal to solve the problem

**Comment by darshankawar** [comment]
@wangqianjun 
Is this still a valid issue or per your last message, this is resolved ?
Can this issue be closed ?
Thanks.

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
