### ISSUE TITLE
CupertinoTextField throwing force_press related exceptions

### ISSUE THREAD

**Issue by kerberjg** [flutter/flutter#28579]
## Steps to Reproduce

I'm running Flutter 1.2.2

Having a CupertinoTextField somewhere inside a CupertinoPageScaffold seems to trigger this. I have no otherGestureDetector in my view.

This is how I build my CupertinoTextField widget:
```dart
CupertinoTextField(
            textCapitalization: TextCapitalization.sentences,
            placeholder: 'Name',
            maxLines: 1,
            maxLength: 32,
            maxLengthEnforced: true,
            keyboardType: TextInputType.text,
            prefix: const Padding(padding: EdgeInsets.symmetric(horizontal: 4.0)),
            autofocus: true,
            controller: TextEditingController(
              text: bikeName
            ),
            onChanged: (content) {
              bikeName = content;
            },
          ),
```

## Logs

The exception thrown is:

```
flutter: ══╡ EXCEPTION CAUGHT BY GESTURE LIBRARY ╞═══════════════════════════════════════════════════════════
flutter: The following assertion was thrown while dispatching a pointer event:
flutter: 'package:flutter/src/gestures/force_press.dart': Failed assertion: line 209 pos 12:
flutter: 'event.pressureMax >= 1.0': is not true.
flutter:
flutter: Either the assertion indicates an error in the framework itself, or we should provide substantially
flutter: more information in this error message to help you determine and fix the underlying cause.
flutter: In either case, please report this assertion by filing a bug on GitHub:
flutter:   https://github.com/flutter/flutter/issues/new?template=BUG.md
flutter:
flutter: When the exception was thrown, this was the stack:
flutter: #2      ForcePressGestureRecognizer.addPointer 
package:flutter/…/gestures/force_press.dart:209
flutter: #3      RawGestureDetectorState._handlePointerDown 
package:flutter/…/widgets/gesture_detector.dart:731
flutter: #4      RenderPointerListener.handleEvent 
package:flutter/…/rendering/proxy_box.dart:2643
flutter: #5      _WidgetsFlutterBinding&BindingBase&GestureBinding.dispatchEvent 
package:flutter/…/gestures/binding.dart:192
flutter: #6      _WidgetsFlutterBinding&BindingBase&GestureBinding._handlePointerEvent 
package:flutter/…/gestures/binding.dart:149
flutter: #7      _WidgetsFlutterBinding&BindingBase&GestureBinding._flushPointerEventQueue 
package:flutter/…/gestures/binding.dart:101
flutter: #8      _WidgetsFlutterBinding&BindingBase&GestureBinding._handlePointerDataPacket 
package:flutter/…/gestures/binding.dart:85
flutter: #12     _invoke1 (dart:ui/hooks.dart:223:10)
flutter: #13     _dispatchPointerDataPacket (dart:ui/hooks.dart:144:5)
flutter: (elided 5 frames from class _AssertionError and package dart:async)
flutter:
flutter: Event:
flutter:   PointerDownEvent(Offset(224.0, 147.5))
flutter: Target:
flutter:   RenderPointerListener#96b96 relayoutBoundary=up15
flutter: ════════════════════════════════════════════════════════════════════════════════════════════════════
```

Flutter doctor output:
```
[✓] Flutter (Channel dev, v1.2.2, on Mac OS X 10.14.3 18D109, locale en-IT)
    • Flutter version 1.2.2 at /Users/<username>/devtools/flutter
    • Framework revision 007a415c2a (5 days ago), 2019-02-21 20:22:47 -0800
    • Engine revision f1f19bba8f
    • Dart version 2.2.0 (build 2.2.0-dev.2.1 c92d5ca288)

[!] Android toolchain - develop for Android devices
    • Android SDK at /usr/local/Caskroom/android-platform-tools/28.0.0
    • Android NDK location not configured (optional; useful for native profiling support)
    ✗ Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.io/setup/#android-setup for detailed instructions).
      If Android SDK has been installed to a custom location, set ANDROID_HOME to that location.
      You may also want to add it to your PATH environment variable.

    ✗ No valid Android SDK platforms found in /usr/local/Caskroom/android-platform-tools/28.0.0/platforms. Directory was empty.
    • Try re-installing or updating your Android SDK,
      visit https://flutter.io/setup/#android-setup for detailed instructions.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.1, Build version 10B61
    • ios-deploy 1.9.4
    • CocoaPods version 1.5.3

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.io/setup/#android-setup for detailed instructions).

[✓] VS Code (version 1.31.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 2.23.1

[✓] Connected device (1 available)
    • iPhone XR • <device id> • ios • iOS 12.1 (simulator)

! Doctor found issues in 2 categories.
```

**Comment by zoechi** [comment]
Please check if you can reproduce in `master` channel. I think this was fixed very recently.

**Comment by HansMuller** [comment]
Right - the fix only landed yesterday: https://github.com/flutter/flutter/pull/28478

**Comment by kerberjg** [comment]
Confirmed, latest `master` release fixes it 👍
