### ISSUE TITLE
can't install dev apk on android device

### ISSUE THREAD

**Issue by luvletterldl** [flutter/flutter#28575]
```
Failed to send crash report due to a network error: SocketException: OS Error: 信号灯超时时间已到
, errno = 121, address = clients2.google.com, port = 54091
```

**Comment by luvletterldl** [comment]
E:\codes\flutterpros\flter>flutter run
Launching lib/main.dart on Redmi 5 Plus in debug mode...
Initializing gradle...                                                 |
Oops; flutter has exited unexpectedly.
Sending crash report to Google.
Failed to send crash report due to a network error: SocketException: OS Error: 信号灯超时时间已到
, errno = 121, address = clients2.google.com, port = 54091
Initializing gradle...                                                  Crash report written to E:\codes\flutter
pros\flter\flutter_04.log;
please let us know at https://github.com/flutter/flutter/issues.

**Comment by luvletterldl** [comment]
Flutter crash report; please file at https://github.com/flutter/flutter/issues.

## command

flutter run

## exception

ProcessException: ProcessException: Process "E:\codes\flutterpros\flter\android\gradlew.bat" exited abnormally:
Downloading https://services.gradle.org/distributions/gradle-4.10.2-all.zip


Exception in thread "main" java.io.IOException: Unable to tunnel through proxy. Proxy returns "HTTP/1.1 405 Method Not Allowed"
	at sun.net.www.protocol.http.HttpURLConnection.doTunneling(HttpURLConnection.java:2124)
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:183)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1546)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1474)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:254)
	at org.gradle.wrapper.Download.downloadInternal(Download.java:58)
	at org.gradle.wrapper.Download.download(Download.java:44)
	at org.gradle.wrapper.Install$1.call(Install.java:61)
	at org.gradle.wrapper.Install$1.call(Install.java:48)
	at org.gradle.wrapper.ExclusiveFileAccessManager.access(ExclusiveFileAccessManager.java:65)
	at org.gradle.wrapper.Install.createDist(Install.java:48)
	at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:128)
	at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:61)
  Command: E:\codes\flutterpros\flter\android\gradlew.bat -v

```
#0      runCheckedAsync (package:flutter_tools/src/base/process.dart:250:5)
<asynchronous suspension>
#1      _initializeGradle (package:flutter_tools/src/android/gradle.dart:210:9)
<asynchronous suspension>
#2      _ensureGradle (package:flutter_tools/src/android/gradle.dart:191:37)
<asynchronous suspension>
#3      _readGradleProject (package:flutter_tools/src/android/gradle.dart:119:31)
<asynchronous suspension>
#4      _gradleProject (package:flutter_tools/src/android/gradle.dart:111:34)
<asynchronous suspension>
#5      getGradleAppOut (package:flutter_tools/src/android/gradle.dart:105:29)
<asynchronous suspension>
#6      AndroidApk.fromAndroidProject (package:flutter_tools/src/application_package.dart:137:23)
<asynchronous suspension>
#7      ApplicationPackageFactory.getPackageForPlatform (package:flutter_tools/src/application_package.dart:37:32)
<asynchronous suspension>
#8      FlutterDevice.runHot (package:flutter_tools/src/resident_runner.dart:288:56)
<asynchronous suspension>
#9      HotRunner.run (package:flutter_tools/src/run_hot.dart:295:39)
<asynchronous suspension>
#10     RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:405:37)
<asynchronous suspension>
#11     FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:545:18)
#12     _asyncThenWrapperHelper.<anonymous closure> (dart:async/runtime/libasync_patch.dart:77:64)
#13     _rootRunUnary (dart:async/zone.dart:1132:38)
#14     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#15     _FutureListener.handleValue (dart:async/future_impl.dart:126:18)
#16     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:639:45)
#17     Future._propagateToListeners (dart:async/future_impl.dart:668:32)
#18     Future._complete (dart:async/future_impl.dart:473:7)
#19     _SyncCompleter.complete (dart:async/future_impl.dart:51:12)
#20     _AsyncAwaitCompleter.complete (dart:async/runtime/libasync_patch.dart:28:18)
#21     _completeOnAsyncReturn (dart:async/runtime/libasync_patch.dart:294:13)
#22     RunCommand.usageValues (package:flutter_tools/src/commands/run.dart)
#23     _asyncThenWrapperHelper.<anonymous closure> (dart:async/runtime/libasync_patch.dart:77:64)
#24     _rootRunUnary (dart:async/zone.dart:1132:38)
#25     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#26     _FutureListener.handleValue (dart:async/future_impl.dart:126:18)
#27     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:639:45)
#28     Future._propagateToListeners (dart:async/future_impl.dart:668:32)
#29     Future._complete (dart:async/future_impl.dart:473:7)
#30     _SyncCompleter.complete (dart:async/future_impl.dart:51:12)
#31     _AsyncAwaitCompleter.complete (dart:async/runtime/libasync_patch.dart:28:18)
#32     _completeOnAsyncReturn (dart:async/runtime/libasync_patch.dart:294:13)
#33     AndroidDevice.targetPlatform (package:flutter_tools/src/android/android_device.dart)
#34     _asyncThenWrapperHelper.<anonymous closure> (dart:async/runtime/libasync_patch.dart:77:64)
#35     _rootRunUnary (dart:async/zone.dart:1132:38)
#36     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#37     _FutureListener.handleValue (dart:async/future_impl.dart:126:18)
#38     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:639:45)
#39     Future._propagateToListeners (dart:async/future_impl.dart:668:32)
#40     Future._complete (dart:async/future_impl.dart:473:7)
#41     _SyncCompleter.complete (dart:async/future_impl.dart:51:12)
#42     _AsyncAwaitCompleter.complete.<anonymous closure> (dart:async/runtime/libasync_patch.dart:33:20)
#43     _rootRun (dart:async/zone.dart:1124:13)
#44     _CustomZone.run (dart:async/zone.dart:1021:19)
#45     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:947:23)
#46     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#47     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#48     _runPendingImmediateCallback (dart:isolate/runtime/libisolate_patch.dart:115:13)
#49     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:172:5)
```

## flutter doctor

```
[32m[✓][39m Flutter (Channel stable, v1.2.1, on Microsoft Windows [Version 10.0.17763.316], locale zh-CN)
    [32m•[39m Flutter version 1.2.1 at F:\ProgramData\flutter
    [32m•[39m Framework revision 8661d8aecd (12 days ago), 2019-02-14 19:19:53 -0800
    [32m•[39m Engine revision 3757390fa4
    [32m•[39m Dart version 2.1.2 (build 2.1.2-dev.0.0 0a7dcf17eb)

[32m[✓][39m Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    [32m•[39m Android SDK at G:\sdk
    [32m•[39m Android NDK location not configured (optional; useful for native profiling support)
    [32m•[39m Platform android-28, build-tools 28.0.3
    [32m•[39m ANDROID_HOME = G:\sdk
    [32m•[39m Java binary at: G:\Program Files\Android\android-studio\jre\bin\java
    [32m•[39m Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)
    [32m•[39m All Android licenses accepted.

[32m[✓][39m Android Studio (version 3.3)
    [32m•[39m Android Studio at G:\Program Files\Android\android-studio
    [32m•[39m Flutter plugin version 33.3.1
    [32m•[39m Dart plugin version 182.5215
    [32m•[39m Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)

[33m[!][39m IntelliJ IDEA Ultimate Edition (version 2017.2)
    [32m•[39m IntelliJ at F:\Program Files\apps\IDEA-U\ch-0\172.4574.19
    [31m✗[39m Flutter plugin not installed; this adds Flutter specific functionality.
    [31m✗[39m Dart plugin not installed; this adds Dart specific functionality.
    [32m•[39m For information about installing plugins, see
      https://flutter.io/intellij-setup/#installing-the-plugins

[32m[✓][39m VS Code, 64-bit edition (version 1.31.1)
    [32m•[39m VS Code at C:\Program Files\Microsoft VS Code
    [32m•[39m Flutter extension version 2.24.0

[32m[✓][39m Connected device (1 available)
    [32m•[39m Redmi 5 Plus • 32a285170804 • android-arm64 • Android 8.1.0 (API 27)

[33m![39m Doctor found issues in 1 category.
```

**Comment by zoechi** [comment]
> Exception in thread "main" java.io.IOException: Unable to tunnel through proxy. Proxy returns "HTTP/1.1 405 Method Not Allowed"

I guess you need to configure the proxy for Gradle.
