### ISSUE TITLE
I can't use firebase_auth plugin

### ISSUE THREAD

**Issue by akkk33** [flutter/flutter#28582]
## Steps to Reproduce

1. Add `firebase_auth: ^0.8.1+4` to `pubspec.yaml`
2. Run `flutter packages get` and `flutter packages upgrade`
3. Run `main.dart` 

## Logs

**`flutter run --verbose`**
```
[  +34 ms] executing: [/opt/flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[  +37 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/stable
[        ] executing: [/opt/flutter/] git rev-parse --abbrev-ref HEAD
[  +11 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] stable
[   +1 ms] executing: [/opt/flutter/] git ls-remote --get-url origin
[  +10 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[        ] executing: [/opt/flutter/] git log -n 1 --pretty=format:%H
[  +12 ms] Exit code 0 from: git log -n 1 --pretty=format:%H
[        ] 8661d8aecd626f7f57ccbcb735553edc05a2e713
[        ] executing: [/opt/flutter/] git log -n 1 --pretty=format:%ar
[  +10 ms] Exit code 0 from: git log -n 1 --pretty=format:%ar
[        ] 12 days ago
[        ] executing: [/opt/flutter/] git describe --match v*.*.* --first-parent --long --tags
[  +10 ms] Exit code 0 from: git describe --match v*.*.* --first-parent --long --tags
[        ] v1.2.1-0-g8661d8aec
[ +115 ms] executing: /home/amr/Android/android-sdk/platform-tools/adb devices -l
[  +20 ms] Exit code 0 from: /home/amr/Android/android-sdk/platform-tools/adb devices -l
[        ] List of devices attached
           ZX1G429G2D             no permissions; see [http://developer.android.com/tools/device.html] usb:2-4 transport_id:2
           emulator-5554          device product:sdk_gphone_x86 model:Android_SDK_built_for_x86 device:generic_x86 transport_id:1
[  +22 ms] More than one device connected; please specify a device with the '-d <deviceId>' flag, or use '-d all' to act on all devices.
[   +7 ms] /home/amr/Android/android-sdk/platform-tools/adb -s ZX1G429G2D shell getprop
[  +41 ms] Error retrieving device properties for ro.product.cpu.abi:
[   +2 ms] error: insufficient permissions for device
           See [http://developer.android.com/tools/device.html] for more information
           
[   +5 ms] ro.hardware = null
[        ] ro.build.characteristics = null
[   +3 ms] /home/amr/Android/android-sdk/platform-tools/adb -s emulator-5554 shell getprop
[  +44 ms] ro.hardware = ranchu
[   +2 ms] ZX1G429G2D                • ZX1G429G2D    • android-arm • Android null (API null)
[   +1 ms] Android SDK built for x86 • emulator-5554 • android-x86 • Android 9 (API 28) (emulator)
[  +14 ms] "flutter run" took 208ms.
[        ] "flutter run" took 208ms.

#0      throwToolExit (package:flutter_tools/src/base/common.dart:24:3)
#1      RunCommand.validateCommand (package:flutter_tools/src/commands/run.dart:240:7)
<asynchronous suspension>
#2      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:525:11)
<asynchronous suspension>
#3      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:482:33)
<asynchronous suspension>
#4      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:142:29)
<asynchronous suspension>
#5      _rootRun (dart:async/zone.dart:1124:13)
#6      _CustomZone.run (dart:async/zone.dart:1021:19)
#7      _runZoned (dart:async/zone.dart:1516:10)
#8      runZoned (dart:async/zone.dart:1463:12)
#9      AppContext.run (package:flutter_tools/src/base/context.dart:141:18)
<asynchronous suspension>
#10     FlutterCommand.run (package:flutter_tools/src/runner/flutter_command.dart:473:20)
#11     CommandRunner.runCommand (package:args/command_runner.dart:196:27)
<asynchronous suspension>
#12     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:396:21)
<asynchronous suspension>
#13     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:142:29)
<asynchronous suspension>
#14     _rootRun (dart:async/zone.dart:1124:13)
#15     _CustomZone.run (dart:async/zone.dart:1021:19)
#16     _runZoned (dart:async/zone.dart:1516:10)
#17     runZoned (dart:async/zone.dart:1463:12)
#18     AppContext.run (package:flutter_tools/src/base/context.dart:141:18)
<asynchronous suspension>
#19     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:356:19)
<asynchronous suspension>
#20     CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:111:29)
#21     new Future.sync (dart:async/future.dart:224:31)
#22     CommandRunner.run (package:args/command_runner.dart:111:11)
#23     FlutterCommandRunner.run (package:flutter_tools/src/runner/flutter_command_runner.dart:242:18)
#24     run.<anonymous closure> (package:flutter_tools/runner.dart:60:20)
<asynchronous suspension>
#25     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:142:29)
<asynchronous suspension>
#26     _rootRun (dart:async/zone.dart:1124:13)
#27     _CustomZone.run (dart:async/zone.dart:1021:19)
#28     _runZoned (dart:async/zone.dart:1516:10)
#29     runZoned (dart:async/zone.dart:1463:12)
#30     AppContext.run (package:flutter_tools/src/base/context.dart:141:18)
<asynchronous suspension>
#31     runInContext (package:flutter_tools/src/context_runner.dart:48:24)
<asynchronous suspension>
#32     run (package:flutter_tools/runner.dart:51:10)
#33     main (package:flutter_tools/executable.dart:52:9)
<asynchronous suspension>
#34     main (file:///opt/flutter/packages/flutter_tools/bin/flutter_tools.dart:8:3)
#35     _startIsolate.<anonymous closure> (dart:isolate/runtime/libisolate_patch.dart:298:32)
#36     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:171:12)


```

**`flutter analyze`**
```
   info • The class 'Future' was not exported from 'dart:core' until version 2.1, but this code is required to be able to run on earlier versions
          • lib/screens/history.dart:36:3 • sdk_version_async_exported_from_core
   info • The class 'Future' was not exported from 'dart:core' until version 2.1, but this code is required to be able to run on earlier versions
          • lib/screens/history.dart:38:11 • sdk_version_async_exported_from_core
   info • The class 'Stream' was not exported from 'dart:core' until version 2.1, but this code is required to be able to run on earlier versions
          • lib/screens/index.dart:19:3 • sdk_version_async_exported_from_core

3 issues found. (ran in 27.1s)
```

```
[✓] Flutter (Channel stable, v1.2.1, on Linux, locale en_GB.utf8)
    • Flutter version 1.2.1 at /opt/flutter
    • Framework revision 8661d8aecd (12 days ago), 2019-02-14 19:19:53 -0800
    • Engine revision 3757390fa4
    • Dart version 2.1.2 (build 2.1.2-dev.0.0 0a7dcf17eb)

⣽Error retrieving device properties for ro.product.cpu.abi:
error: insufficient permissions for device
See [http://developer.android.com/tools/device.html] for more information

                                                                                                                                                 [✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /home/amr/Android/android-sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = /home/amr/Android/android-sdk
    • Java binary at: /home/amr/Android/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)
    • All Android licenses accepted.

[✓] Android Studio (version 3.3)
    • Android Studio at /home/amr/Android/android-studio
    • Flutter plugin version 33.3.1
    • Dart plugin version 182.5215
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)

[✓] Connected device (2 available)
    • ZX1G429G2D                • ZX1G429G2D    • android-arm • Android null (API null)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 9 (API 28) (emulator)

• No issues found!
```
**Also when selecting `Migrate to AndroidX` from `Refactor` menu it returns this:**
```
No Usages Found in the Project
```

**Comment by akkk33** [comment]
Update:
I removed all `NotNull` and `@Nullable` from `/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_auth-0.8.1+4/android/src/main/java/io/flutter/plugins/firebaseauth/FirebaseAuthPlugin.java`
And it works for now.
But I believe this workaround will break after any upgrade

**Comment by zoechi** [comment]
> Error retrieving device properties for ro.product.cpu.abi:
[   +2 ms] error: insufficient permissions for device

The error output looks more like a problem with the connection to your device
and not related to `firebase_auth`.

**Comment by zoechi** [comment]
> info • The class 'Future' was not exported from 'dart:core' until version 2.1, but this code is required to be able to run on earlier versions

means you should update the `SDK` constraint in `pubspec.yaml` to `>= 2.1.0 < 3.0.0`

**Comment by akkk33** [comment]
> > Error retrieving device properties for ro.product.cpu.abi:
> > [   +2 ms] error: insufficient permissions for device
> 
> The error output looks more like a problem with the connection to your device
> and not related to `firebase_auth`.

I use Android virtual machine provided by Android studio


> > info • The class 'Future' was not exported from 'dart:core' until version 2.1, but this code is required to be able to run on earlier versions
> 
> means you should update the `SDK` constraint in `pubspec.yaml` to `>= 2.1.0 < 3.0.0`

Already have that still the problem exists.

**Comment by iqbalmineraltown** [comment]
you should specify which device you want to debug with `-d` arguments
or just plug 1 device at a time, either emulator or physical device

but it seems like it's trying to run in your `arm` device, which has insufficient permission to run as debug target device. You might want to tweak developer options on that device

**Comment by cpboyd** [comment]
I'm also having a similar issue with a new project created in Android Studio (latest stable flutter).  There's also #27982 which is probably related.

After making the modifications to remove AndroidX references, as @akkk33 mentioned, I was able to successfully load the app.

**Comment by kroikie** [comment]
@akkk33

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/409. Any further collaboration will be done there.
