### ISSUE TITLE
asynchronous suspension

### ISSUE THREAD

**Issue by daniellim922** [flutter/flutter#28588]
**_The Issue_**
```
flutter: ══╡ EXCEPTION CAUGHT BY IMAGE RESOURCE SERVICE ╞════════════════════════════════════════════════════
flutter: The following assertion was thrown resolving an image codec:
flutter: Unable to load asset: images/m1.jpeg
flutter:
flutter: When the exception was thrown, this was the stack:
flutter: #0      PlatformAssetBundle.load (package:flutter/src/services/asset_bundle.dart:221:7)
flutter: <asynchronous suspension>
flutter: #1      AssetBundleImageProvider._loadAsync (package:flutter/src/painting/image_provider.dart:429:44)
flutter: <asynchronous suspension>
flutter: #2      AssetBundleImageProvider.load (package:flutter/src/painting/image_provider.dart:414:14)
flutter: #3      ImageProvider.resolve.<anonymous closure>.<anonymous closure> (package:flutter/src/painting/image_provider.dart:267:86)
flutter: #4      ImageCache.putIfAbsent (package:flutter/src/painting/image_cache.dart:143:20)
flutter: #5      ImageProvider.resolve.<anonymous closure> (package:flutter/src/painting/image_provider.dart:267:63)
flutter: (elided 8 frames from package dart:async)
flutter:
flutter: Image provider: AssetImage(bundle: null, name: "images/m1.jpeg")
flutter: Image key: AssetBundleImageKey(bundle: PlatformAssetBundle#28601(), name: "images/m1.jpeg", scale:
flutter: 1.0)
```
**My Code**
```dart
class _HomePageState extends State<HomePage> {
  @override
  Widget build(BuildContext context) {
  Widget image_carousel = new Container(
    height: 200.0,
    child: new Carousel(
      boxFit: BoxFit.cover,
      images:[
        AssetImage('images/c1.jpg'),
        AssetImage('images/m1.jpeg'),
        AssetImage('images/w3.jpeg'),
        AssetImage('images/w4.jpeg'),
        AssetImage('images/m2.jpg'),
      ],
      autoplay:false, 
      animationCurve: Curves.fastOutSlowIn,
      animationDuration: Duration(milliseconds: 1000),
    ),
  );
```

**my `pubspec.yaml`**
```yml
flutter:
  uses-material-design: true
  assets:
    - asset/images/c1.jpg
    - asset/images/m1.jpeg
    - asset/images/w3.jpeg
    - asset/images/w4.jpeg
    - asset/images/m2.jpg
```
**Flutter Doctor**
```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, v1.0.0, on Mac OS X 10.13.6 17G4015, locale en-SG)
[✓] Android toolchain - develop for Android devices (Android SDK 28.0.3)
[✓] iOS toolchain - develop for iOS devices (Xcode 10.1)
[✓] Android Studio (version 3.3)
[✓] VS Code (version 1.31.1)
[✓] Connected device (1 available)

• No issues found!
```

**Comment by daniellim922** [comment]
I am new to flutter and I dont know how to go about this. Any help will be appreciated! Already ran my pubspec through yamil.lint and there havent been any problems with it

**Comment by lukef** [comment]
When loading an image asset you will need to use the same path that you defined in the `pubspec.yaml`. So: `asset/images/c1.jpg` and not `images/c1.jpg`.

**Comment by zoechi** [comment]
Because of the issue title.

`<asynchronous suspension>` is not an indication of a problem, it just indicates that code execution is not synchronous code executed line-by-line, but instead a callback from a completed `Future` started at this position in the callstack.

Please consider asking support questions in one of the other channels listed at http://flutter.io/support .

**Comment by oxenprogrammer** [comment]
> Because of the issue title.
> 
> `<asynchronous suspension>` is not an indication of a problem, it just indicates that code execution is not synchronous code executed line-by-line, but instead a callback from a completed `Future` started at this position in the callstack.
> 
> Please consider asking support questions in one of the other channels listed at http://flutter.io/support .

exactly, meaning that in your root you have an image directory inside an asset directory. the path has to be absolute

**Comment by ahammamlho** [comment]
I have same issus plz help

**Comment by ahammamlho** [comment]
I have same issus plz help
