### ISSUE TITLE
flutter doctor throwing Unhandled exception on Mac OS X 10.14.3

### ISSUE THREAD

**Issue by victoraldir** [flutter/flutter#28622]
Everything works fine except the `flutter doctor` command

## Command 

` flutter doctor`

## Exception

```
Victors-MacBook-Pro:police_videos victoraldir$ flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel beta, v1.2.1, on Mac OS X 10.14.3 18D109, locale en-IE)
⣽Unhandled exception:
RangeError (index): Invalid value: Only valid value is 0: 1
#0      List.[] (dart:core/runtime/libgrowable_array.dart:145:60)
#1      IntelliJValidatorOnMac.pluginsPath (package:flutter_tools/src/doctor.dart:681:31)
#2      IntelliJValidator.validate (package:flutter_tools/src/doctor.dart:524:53)
<asynchronous suspension>
#3      Doctor.startValidatorTasks (package:flutter_tools/src/doctor.dart:116:52)
#4      Doctor.diagnose (package:flutter_tools/src/doctor.dart:189:41)
#5      _AsyncAwaitCompleter.start (dart:async/runtime/libasync_patch.dart:49:6)
#6      Doctor.diagnose (package:flutter_tools/src/doctor.dart:179:24)
#7      DoctorCommand.runCommand (package:flutter_tools/src/commands/doctor.dart:48:39)
#8      _AsyncAwaitCompleter.start (dart:async/runtime/libasync_patch.dart:49:6)
#9      DoctorCommand.runCommand (package:flutter_tools/src/commands/doctor.dart:34:42)
#10     FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:545:18)
#11     _asyncThenWrapperHelper.<anonymous closure> (dart:async/runtime/libasync_patch.dart:77:64)
#12     _rootRunUnary (dart:async/zone.dart:1132:38)
#13     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#14     _FutureListener.handleValue (dart:async/future_impl.dart:126:18)
#15     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:639:45)
#16     Future._propagateToListeners (dart:async/future_impl.dart:668:32)
#17     Future._complete (dart:async/future_impl.dart:473:7)
#18     _SyncCompleter.complete (dart:async/future_impl.dart:51:12)
#19     _AsyncAwaitCompleter.complete.<anonymous closure> (dart:async/runtime/libasync_patch.dart:33:20)
#20     _rootRun (dart:async/zone.dart:1124:13)
#21     _CustomZone.run (dart:async/zone.dart:1021:19)
#22     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:947:23)
#23     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#24     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#25     _runPendingImmediateCallback (dart:isolate/runtime/libisolate_patch.dart:115:13)
#26     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:172:5)

```

**Comment by jonahwilliams** [comment]
The exception comes from the following line which attempts to split a "major.minor" version string into a list of [major, minor].

https://github.com/flutter/flutter/blob/7634a0ecbe0b5d7d0a75c90be619ff25bdeefa72/packages/flutter_tools/lib/src/doctor.dart#L665

If you update the version in you Info.plist to conform to that pattern, maybe by adding a ".0" does that unblock you?

**Comment by victoraldir** [comment]
Thanks for getting back to me @jonahwilliams I'll give it a try when I get home

**Comment by victoraldir** [comment]
@jonahwilliams turns out that I had a corrupted installation of IntelliJ (not Android Studio) hanging in my environment. Removed it completely and the problem has gone
