### ISSUE TITLE
Text throwing error

### ISSUE THREAD

**Issue by EliasDeuss** [flutter/flutter#28707]
```
flutter: ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
flutter: The following assertion was thrown building HomePage(dirty, dependencies:
flutter: [_LocalizationsScope-[GlobalKey#f2b5e]], state: HomePageState#8b279):
flutter: 'package:flutter/src/widgets/text.dart': Failed assertion: line 237 pos 15: 'data != null': is not
flutter: true.
flutter:
flutter: Either the assertion indicates an error in the framework itself, or we should provide substantially
flutter: more information in this error message to help you determine and fix the underlying cause.
flutter: In either case, please report this assertion by filing a bug on GitHub:
flutter:   https://github.com/flutter/flutter/issues/new?template=BUG.md
flutter:
flutter: When the exception was thrown, this was the stack:
flutter: #2      new Text (package:flutter/src/widgets/text.dart:237:15)
flutter: #3      HomePageState.build (package:redwood/more/more.dart:568:39)
flutter: #4      StatefulElement.build (package:flutter/src/widgets/framework.dart:3825:27)
flutter: #5      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3736:15)
flutter: #6      Element.rebuild (package:flutter/src/widgets/framework.dart:3559:5)
flutter: #7      StatefulElement.update (package:flutter/src/widgets/framework.dart:3894:5)
flutter: #8      Element.updateChild (package:flutter/src/widgets/framework.dart:2748:15)
flutter: #9      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3747:16)
flutter: #10     Element.rebuild (package:flutter/src/widgets/framework.dart:3559:5)
flutter: #11     StatelessElement.update (package:flutter/src/widgets/framework.dart:3796:5)
flutter: #12     Element.updateChild (package:flutter/src/widgets/framework.dart:2748:15)
flutter: #13     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3747:16)
flutter: #14     Element.rebuild (package:flutter/src/widgets/framework.dart:3559:5)
flutter: #15     StatelessElement.update (package:flutter/src/widgets/framework.dart:3796:5)
flutter: #16     Element.updateChild (package:flutter/src/widgets/framework.dart:2748:15)
flutter: #17     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4883:14)
flutter: #18     Element.updateChild (package:flutter/src/widgets/framework.dart:2748:15)
flutter: #19     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4883:14)
flutter: #20     Element.updateChild (package:flutter/src/widgets/framework.dart:2748:15)
flutter: #21     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3747:16)
flutter: #22     Element.rebuild (package:flutter/src/widgets/framework.dart:3559:5)
flutter: #23     StatelessElement.update (package:flutter/src/widgets/framework.dart:3796:5)
flutter: #24     Element.updateChild (package:flutter/src/widgets/framework.dart:2748:15)
flutter: #25     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3747:16)
flutter: #26     Element.rebuild (package:flutter/src/widgets/framework.dart:3559:5)
flutter: #27     ProxyElement.update (package:flutter/src/widgets/framework.dart:4006:5)
flutter: #28     Element.updateChild (package:flutter/src/widgets/framework.dart:2748:15)
flutter: #29     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3747:16)
flutter: #30     Element.rebuild (package:flutter/src/widgets/framework.dart:3559:5)
flutter: #31     StatefulElement.update (package:flutter/src/widgets/framework.dart:3894:5)
flutter: #32     Element.updateChild (package:flutter/src/widgets/framework.dart:2748:15)
flutter: #33     SliverMultiBoxAdaptorElement.updateChild (package:flutter/src/widgets/sliver.dart:1030:36)
flutter: #34     SliverMultiBoxAdaptorElement.performRebuild.processElement (package:flutter/src/widgets/sliver.dart:980:34)
flutter: #35     List.forEach (dart:core/runtime/libgrowable_array.dart:278:8)
flutter: #36     SliverMultiBoxAdaptorElement.performRebuild (package:flutter/src/widgets/sliver.dart:991:36)
flutter: #37     SliverMultiBoxAdaptorElement.update (package:flutter/src/widgets/sliver.dart:957:7)
flutter: #38     Element.updateChild (package:flutter/src/widgets/framework.dart:2748:15)
flutter: #39     RenderObjectElement.updateChildren (package:flutter/src/widgets/framework.dart:4601:32)
flutter: #40     MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4992:17)
flutter: #41     _ViewportElement.update (package:flutter/src/widgets/viewport.dart:192:11)
flutter: #42     Element.updateChild (package:flutter/src/widgets/framework.dart:2748:15)
flutter: #43     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4883:14)
flutter: #44     Element.updateChild (package:flutter/src/widgets/framework.dart:2748:15)
flutter: #45     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4883:14)
flutter: #46     Element.updateChild (package:flutter/src/widgets/framework.dart:2748:15)
flutter: #47     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4883:14)
flutter: #48     Element.updateChild (package:flutter/src/widgets/framework.dart:2748:15)
flutter: #49     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4883:14)
flutter: #50     Element.updateChild (package:flutter/src/widgets/framework.dart:2748:15)
flutter: #51     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3747:16)
flutter: #52     Element.rebuild (package:flutter/src/widgets/framework.dart:3559:5)
flutter: #53     StatefulElement.update (package:flutter/src/widgets/framework.dart:3894:5)
flutter: #54     Element.updateChild (package:flutter/src/widgets/framework.dart:2748:15)
flutter: #55     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3747:16)
flutter: #56     Element.rebuild (package:flutter/src/widgets/framework.dart:3559:5)
flutter: #57     ProxyElement.update (package:flutter/src/widgets/framework.dart:4006:5)
flutter: #58     Element.updateChild (package:flutter/src/widgets/framework.dart:2748:15)
flutter: #59     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4883:14)
flutter: #60     Element.updateChild (package:flutter/src/widgets/framework.dart:2748:15)
flutter: #61     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3747:16)
flutter: #62     Element.rebuild (package:flutter/src/widgets/framework.dart:3559:5)
flutter: #63     StatefulElement.update (package:flutter/src/widgets/framework.dart:3894:5)
flutter: #64     Element.updateChild (package:flutter/src/widgets/framework.dart:2748:15)
flutter: #65     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3747:16)
flutter: #66     Element.rebuild (package:flutter/src/widgets/framework.dart:3559:5)
flutter: #67     StatelessElement.update (package:flutter/src/widgets/framework.dart:3796:5)
flutter: #68     Element.updateChild (package:flutter/src/widgets/framework.dart:2748:15)
flutter: #69     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3747:16)
flutter: #70     Element.rebuild (package:flutter/src/widgets/framework.dart:3559:5)
flutter: #71     StatefulElement.update (package:flutter/src/widgets/framework.dart:3894:5)
flutter: #72     Element.updateChild (package:flutter/src/widgets/framework.dart:2748:15)
flutter: #73     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3747:16)
flutter: #74     Element.rebuild (package:flutter/src/widgets/framework.dart:3559:5)
flutter: #75     ProxyElement.update (package:flutter/src/widgets/framework.dart:4006:5)
flutter: #76     Element.updateChild (package:flutter/src/widgets/framework.dart:2748:15)
flutter: #77     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3747:16)
flutter: #78     Element.rebuild (package:flutter/src/widgets/framework.dart:3559:5)
flutter: #79     ProxyElement.update (package:flutter/src/widgets/framework.dart:4006:5)
flutter: #80     Element.updateChild (package:flutter/src/widgets/framework.dart:2748:15)
flutter: #81     RenderObjectElement.updateChildren (package:flutter/src/widgets/framework.dart:4601:32)
flutter: #82     MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4992:17)
flutter: #83     Element.updateChild (package:flutter/src/widgets/framework.dart:2748:15)
flutter: #84     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3747:16)
flutter: #85     Element.rebuild (package:flutter/src/widgets/framework.dart:3559:5)
flutter: #86     StatefulElement.update (package:flutter/src/widgets/framework.dart:3894:5)
flutter: #87     Element.updateChild (package:flutter/src/widgets/framework.dart:2748:15)
flutter: #88     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3747:16)
flutter: #89     Element.rebuild (package:flutter/src/widgets/framework.dart:3559:5)
flutter: #90     ProxyElement.update (package:flutter/src/widgets/framework.dart:4006:5)
flutter: #91     Element.updateChild (package:flutter/src/widgets/framework.dart:2748:15)
flutter: #92     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3747:16)
flutter: #93     Element.rebuild (package:flutter/src/widgets/framework.dart:3559:5)
flutter: #94     StatefulElement.update (package:flutter/src/widgets/framework.dart:3894:5)
flutter: #95     Element.updateChild (package:flutter/src/widgets/framework.dart:2748:15)
flutter: #96     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4883:14)
flutter: #97     Element.updateChild (package:flutter/src/widgets/framework.dart:2748:15)
flutter: #98     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3747:16)
flutter: #99     Element.rebuild (package:flutter/src/widgets/framework.dart:3559:5)
flutter: #100    StatelessElement.update (package:flutter/src/widgets/framework.dart:3796:5)
flutter: #101    Element.updateChild (package:flutter/src/widgets/framework.dart:2748:15)
flutter: #102    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4883:14)
flutter: #103    Element.updateChild (package:flutter/src/widgets/framework.dart:2748:15)
flutter: #104    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3747:16)
flutter: #105    Element.rebuild (package:flutter/src/widgets/framework.dart:3559:5)
flutter: #106    StatefulElement.update (package:flutter/src/widgets/framework.dart:3894:5)
flutter: #107    Element.updateChild (package:flutter/src/widgets/framework.dart:2748:15)
flutter: #108    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3747:16)
flutter: #109    Element.rebuild (package:flutter/src/widgets/framework.dart:3559:5)
flutter: #110    StatefulElement.update (package:flutter/src/widgets/framework.dart:3894:5)
flutter: #111    Element.updateChild (package:flutter/src/widgets/framework.dart:2748:15)
flutter: #112    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3747:16)
flutter: #113    Element.rebuild (package:flutter/src/widgets/framework.dart:3559:5)
flutter: #114    ProxyElement.update (package:flutter/src/widgets/framework.dart:4006:5)
flutter: #115    Element.updateChild (package:flutter/src/widgets/framework.dart:2748:15)
flutter: #116    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3747:16)
flutter: #117    Element.rebuild (package:flutter/src/widgets/framework.dart:3559:5)
flutter: #118    ProxyElement.update (package:flutter/src/widgets/framework.dart:4006:5)
flutter: #119    Element.updateChild (package:flutter/src/widgets/framework.dart:2748:15)
flutter: #120    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3747:16)
flutter: #121    Element.rebuild (package:flutter/src/widgets/framework.dart:3559:5)
flutter: #122    StatefulElement.update (package:flutter/src/widgets/framework.dart:3894:5)
flutter: #123    Element.updateChild (package:flutter/src/widgets/framework.dart:2748:15)
flutter: #124    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3747:16)
flutter: #125    Element.rebuild (package:flutter/src/widgets/framework.dart:3559:5)
flutter: #126    StatefulElement.update (package:flutter/src/widgets/framework.dart:3894:5)
flutter: #127    Element.updateChild (package:flutter/src/widgets/framework.dart:2748:15)
flutter: #128    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3747:16)
flutter: #129    Element.rebuild (package:flutter/src/widgets/framework.dart:3559:5)
flutter: #130    StatefulElement.update (package:flutter/src/widgets/framework.dart:3894:5)
flutter: #131    Element.updateChild (package:flutter/src/widgets/framework.dart:2748:15)
flutter: #132    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3747:16)
flutter: #133    Element.rebuild (package:flutter/src/widgets/framework.dart:3559:5)
flutter: #134    BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2273:33)
flutter: #135    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding&WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:700:20)
flutter: #136    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:268:5)
flutter: #137    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:988:15)
Reloaded 7 of 819 libraries in 2,451ms.
flutter: #138    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:928:9)
flutter: #139    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.scheduleWarmUpFrame.<anonymous closure> (package:flutter/src/scheduler/binding.dart:749:7)
flutter: #141    _Timer._runTimers (dart:isolate/runtime/libtimer_impl.dart:382:19)
flutter: #142    _Timer._handleMessage (dart:isolate/runtime/libtimer_impl.dart:416:5)
flutter: #143    _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:171:12)
flutter: (elided 3 frames from class _AssertionError and package dart:async)
flutter: ════════════════════════════════════════════════════════════════════════════════════════════════════
```

**Comment by EliasDeuss** [comment]
Before anyone asks

`Flutter 1.2.1 • channel beta • https://github.com/flutter/flutter.git
Framework • revision 8661d8aecd (2 weeks ago) • 2019-02-14 19:19:53 -0800
Engine • revision 3757390fa4
Tools • Dart 2.1.2 (build 2.1.2-dev.0.0 0a7dcf17eb)

Running "flutter packages upgrade" in Redwood...                    9.4s

Running flutter doctor...
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel beta, v1.2.1, on Mac OS X 10.14.3 18D109, locale en-US)
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[✓] iOS toolchain - develop for iOS devices (Xcode 10.1)
[✓] Android Studio (version 3.3)
[✓] Connected device (1 available)

• No issues found!
Eliass-MBP:Redwood elias$ 
`

**Comment by dnfield** [comment]
`Text(null)` or any variant thereof (e.g. `var x; Text(x);`) is invalid.

We could update the message though.
