### ISSUE TITLE
IllegalStateException: UiAutomation not connected! on Pixel 2, Android 8.1

### ISSUE THREAD

**Issue by hartmannj** [flutter/flutter#28764]
Another Google Pre-Launch report with a crash on Pixel 2, Android 8.1:
```
java.lang.IllegalStateException: UiAutomation not connected!
	at android.app.UiAutomation.throwIfNotConnectedLocked(UiAutomation.java:1096)
	at android.app.UiAutomation.waitForIdle(UiAutomation.java:647)
	at android.support.test.uiautomator.r.a(QueryController.java:36)
	at android.support.test.uiautomator.r.c(QueryController.java:32)
	at android.support.test.uiautomator.r.a(QueryController.java:9)
	at android.support.test.uiautomator.y.g(UiDevice.java:91)
	at com.google.android.apps.mtaas.crawler.platform.uiautomator.UiAutomatorScreenStateBuilder.getCurrentActivity(UiAutomatorScreenStateBuilder.java:50)
	at com.google.android.apps.mtaas.crawler.platform.uiautomator.UiAutomatorStateExtractor.getCurrentActivity(UiAutomatorStateExtractor.java:23)
	at com.google.android.apps.mtaas.crawler.platform.hybrid.HybridStateExtractor.getCurrentActivity(HybridStateExtractor.java:30)
	at com.google.android.apps.mtaas.crawler.controller.remote.RemotePlatform.handlePerformActionMessage(RemotePlatform.java:25)
	at com.google.android.apps.mtaas.crawler.controller.remote.RemotePlatform.access$300(RemotePlatform.java:88)
	at com.google.android.apps.mtaas.crawler.controller.remote.RemotePlatform$ControllerMessageHandler.handleMessage(RemotePlatform.java:8)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:164)
	at android.os.HandlerThread.run(HandlerThread.java:65)
```
With version:
```
Flutter 1.3.0 • channel dev • https://github.com/flutter/flutter.git
Framework • revision 3054a93579 • 2019-02-27 20:22:28 -0500
Engine • revision 3e4e6f5c54
Tools • Dart 2.2.0 (build 2.2.0-dev.2.1 0f9a5198bd)
```

**Comment by jonahwilliams** [comment]
This stack doesn't look related to flutter at all. It looks like you've left UI Automator code in your application?

**Comment by hartmannj** [comment]
I don't have any UI testing inside the code but it seems to be a known bug in Google Pre-Launch tests:
[https://github.com/googlesamples/android-testing/issues/89](url)
