### ISSUE TITLE
flutter crash report

### ISSUE THREAD

**Issue by DineshTamang** [flutter/flutter#28795]
Flutter crash report; please file at https://github.com/flutter/flutter/issues.

## command

flutter build bundle --suppress-analytics --target lib/main.dart --target-platform android-arm --precompiled --asset-dir C:\Users\ENiX\Desktop\quartha\flutter_quartha\android\app\build\intermediates\flutter\release/flutter_assets --release

## exception

FileSystemException: FileSystemException: Cannot open file, path = 'C:\Users\ENiX\Desktop\quartha\flutter_quartha\android\app\build\intermediates\flutter\release\flutter_assets\images\quartha_tutorial.png' (OS Error: The system cannot find the file specified.
, errno = 2)

```
#0      _File.open.<anonymous closure> (dart:io/file_impl.dart:368:9)
#1      _rootRunUnary (dart:async/zone.dart:1132:38)
#2      _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#3      _FutureListener.handleValue (dart:async/future_impl.dart:129:18)
#4      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:642:45)
#5      Future._propagateToListeners (dart:async/future_impl.dart:671:32)
#6      Future._completeWithValue (dart:async/future_impl.dart:486:5)
#7      Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:516:7)
#8      _rootRun (dart:async/zone.dart:1124:13)
#9      _CustomZone.run (dart:async/zone.dart:1021:19)
#10     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:947:23)
#11     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#12     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#13     _runPendingImmediateCallback (dart:isolate/runtime/libisolate_patch.dart:115:13)
#14     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:172:5)
```

## flutter doctor

```
[✓] Flutter (Channel beta, v1.0.0, on Microsoft Windows [Version 10.0.17134.523], locale en-GB)
    • Flutter version 1.0.0 at C:\Users\ENiX\flutter
    • Framework revision 5391447fae (3 months ago), 2018-11-29 19:41:26 -0800
    • Engine revision 7375a0f414
    • Dart version 2.1.0 (build 2.1.0-dev.9.4 f9ebf21297)

[✓] Android toolchain - develop for Android devices (Android SDK 28.0.3)
    • Android SDK at C:\Users\ENiX\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b02)
    • All Android licenses accepted.

[✓] Android Studio (version 3.1)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 29.0.1
    • Dart plugin version 173.4700
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b02)

[!] Connected device
    ! No devices available

! Doctor found issues in 1 category.
```

**Comment by TheHemantKaushik** [comment]
Could you please try deleting android\app\build directory once? Or update to Flutter version 1.2 if possible? There are so many changes done in the build system in newer versions of Flutter.

**Comment by jonahwilliams** [comment]
I would try running `flutter clean` and see if the issue persists

**Comment by DineshTamang** [comment]
> I would try running `flutter clean` and see if the issue persists

I ran `flutter clean` but the issue is still there

**Comment by DineshTamang** [comment]
Flutter crash report; please file at https://github.com/flutter/flutter/issues.

## command

flutter build bundle --suppress-analytics --target C:\Users\ENiX\Desktop\quartha\flutter_quartha\lib\main.dart --filesystem-scheme org-dartlang-root --depfile C:\Users\ENiX\Desktop\quartha\flutter_quartha\android\app\build\intermediates\flutter\debug/snapshot_blob.bin.d --asset-dir C:\Users\ENiX\Desktop\quartha\flutter_quartha\android\app\build\intermediates\flutter\debug/flutter_assets --debug

## exception

FileSystemException: FileSystemException: Creation failed, path = 'C:\Users\ENiX\Desktop\quartha\flutter_quartha\android\app\build\intermediates\flutter\debug/flutter_assets\android/app/build/intermediates/flutter/debug/flutter_assets/android/app/build/intermediates/flutter/release/flutter_assets/android/app/build' (OS Error: The filename or extension is too long.
, errno = 206)

```
#0      _Directory.createSync (dart:io/directory_impl.dart:140:7)
#1      _Directory.createSync (dart:io/directory_impl.dart:135:16)
#2      _Directory.createSync (dart:io/directory_impl.dart:135:16)
#3      _Directory.createSync (dart:io/directory_impl.dart:135:16)
#4      _Directory.createSync (dart:io/directory_impl.dart:135:16)
#5      _Directory.createSync (dart:io/directory_impl.dart:135:16)
#6      _LocalDirectory&LocalFileSystemEntity&ForwardingDirectory.createSync (package:file/src/forwarding/forwarding_directory.dart:22:16)
#7      writeBundle.<anonymous closure> (package:flutter_tools/src/bundle.dart:208:17)
<asynchronous suspension>
#8      MappedIterator.moveNext (dart:_internal/iterable.dart:392:18)
#9      Future.wait (dart:async/future.dart:392:26)
#10     writeBundle (package:flutter_tools/src/bundle.dart:205:16)
#11     _AsyncAwaitCompleter.start (dart:async/runtime/libasync_patch.dart:49:6)
#12     writeBundle (package:flutter_tools/src/bundle.dart:199:25)
#13     assemble (package:flutter_tools/src/bundle.dart:195:9)
#14     _AsyncAwaitCompleter.start (dart:async/runtime/libasync_patch.dart:49:6)
#15     assemble (package:flutter_tools/src/bundle.dart:163:22)
#16     build (package:flutter_tools/src/bundle.dart:128:9)
#17     _asyncThenWrapperHelper.<anonymous closure> (dart:async/runtime/libasync_patch.dart:77:64)
#18     _rootRunUnary (dart:async/zone.dart:1132:38)
#19     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#20     _FutureListener.handleValue (dart:async/future_impl.dart:129:18)
#21     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:642:45)
#22     Future._propagateToListeners (dart:async/future_impl.dart:671:32)
#23     Future._complete (dart:async/future_impl.dart:476:7)
#24     _SyncCompleter.complete (dart:async/future_impl.dart:51:12)
#25     _AsyncAwaitCompleter.complete (dart:async/runtime/libasync_patch.dart:28:18)
#26     _completeOnAsyncReturn (dart:async/runtime/libasync_patch.dart:295:13)
#27     buildAssets (package:flutter_tools/src/bundle.dart)
#28     _asyncThenWrapperHelper.<anonymous closure> (dart:async/runtime/libasync_patch.dart:77:64)
#29     _rootRunUnary (dart:async/zone.dart:1132:38)
#30     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#31     _FutureListener.handleValue (dart:async/future_impl.dart:129:18)
#32     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:642:45)
#33     Future._propagateToListeners (dart:async/future_impl.dart:671:32)
#34     Future._complete (dart:async/future_impl.dart:476:7)
#35     _SyncCompleter.complete (dart:async/future_impl.dart:51:12)
#36     _AsyncAwaitCompleter.complete (dart:async/runtime/libasync_patch.dart:28:18)
#37     _completeOnAsyncReturn (dart:async/runtime/libasync_patch.dart:295:13)
#38     _ManifestAssetBundle.build (package:flutter_tools/src/asset.dart)
#39     _asyncThenWrapperHelper.<anonymous closure> (dart:async/runtime/libasync_patch.dart:77:64)
#40     _rootRunUnary (dart:async/zone.dart:1132:38)
#41     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#42     _FutureListener.handleValue (dart:async/future_impl.dart:129:18)
#43     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:642:45)
#44     Future._propagateToListeners (dart:async/future_impl.dart:671:32)
#45     Future._complete (dart:async/future_impl.dart:476:7)
#46     _SyncCompleter.complete (dart:async/future_impl.dart:51:12)
#47     _AsyncAwaitCompleter.complete (dart:async/runtime/libasync_patch.dart:28:18)
#48     _completeOnAsyncReturn (dart:async/runtime/libasync_patch.dart:295:13)
#49     _obtainLicenses (package:flutter_tools/src/asset.dart)
#50     _asyncThenWrapperHelper.<anonymous closure> (dart:async/runtime/libasync_patch.dart:77:64)
#51     _rootRunUnary (dart:async/zone.dart:1132:38)
#52     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#53     _FutureListener.handleValue (dart:async/future_impl.dart:129:18)
#54     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:642:45)
#55     Future._propagateToListeners (dart:async/future_impl.dart:671:32)
#56     Future._completeWithValue (dart:async/future_impl.dart:486:5)
#57     Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:516:7)
#58     _rootRun (dart:async/zone.dart:1124:13)
#59     _CustomZone.run (dart:async/zone.dart:1021:19)
#60     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:947:23)
#61     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#62     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#63     _runPendingImmediateCallback (dart:isolate/runtime/libisolate_patch.dart:115:13)
#64     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:172:5)
```

## flutter doctor

```
[✓] Flutter (Channel beta, v1.0.0, on Microsoft Windows [Version 10.0.17134.523], locale en-GB)
    • Flutter version 1.0.0 at C:\Users\ENiX\flutter
    • Framework revision 5391447fae (3 months ago), 2018-11-29 19:41:26 -0800
    • Engine revision 7375a0f414
    • Dart version 2.1.0 (build 2.1.0-dev.9.4 f9ebf21297)

[✓] Android toolchain - develop for Android devices (Android SDK 28.0.3)
    • Android SDK at C:\Users\ENiX\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b02)
    • All Android licenses accepted.

[✓] Android Studio (version 3.1)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 29.0.1
    • Dart plugin version 173.4700
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b02)

[✓] Connected device (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 9 (API 28) (emulator)

• No issues found!
```

**Comment by jonahwilliams** [comment]
Looks like something has gone really wrong here, note the switch to `/` and repetition of the file structure.

`C:\Users\ENiX\Desktop\quartha\flutter_quartha\android\app\build\intermediates\flutter\debug/flutter_assets\android/app/build/intermediates/flutter/debug/flutter_assets/android/app/build/intermediates/flutter/release/flutter_assets/android/app/build`

Can you post your pubspec yaml?

**Comment by DineshTamang** [comment]
> Looks like something has gone really wrong here, note the switch to `/` and repetition of the file structure.
> 
> `C:\Users\ENiX\Desktop\quartha\flutter_quartha\android\app\build\intermediates\flutter\debug/flutter_assets\android/app/build/intermediates/flutter/debug/flutter_assets/android/app/build/intermediates/flutter/release/flutter_assets/android/app/build`
> 
> Can you post your pubspec yaml?

Thank you sir,
I found the problem in my pubspec.yaml file and solved the problem.

Thank you again.
