### ISSUE TITLE
Input doesn't unregister from keyboard when deactivated

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#2880]
1. Run stocks in checked mode
2. Click the FAB
3. Start typing on the keyboard with one hand. Don't stop as you perform the next step.
4. With the other hand, tap the list to dismiss the bottom sheet.

```
03-24 13:13:06.122 21801 21833 E flutter : setState() called after dipose(): _CreateCompanySheetState(922438396; _StateLifecycle.defunct; not mounted)
03-24 13:13:06.122 21801 21833 E flutter : This error happens if you call setState() on State object for a widget that
03-24 13:13:06.122 21801 21833 E flutter : no longer appears in the widget tree (e.g., whose parent widget no longer
03-24 13:13:06.122 21801 21833 E flutter : includes the widget in its build). This error can occur when code calls
03-24 13:13:06.122 21801 21833 E flutter : setState() from a timer or an animation callback. The preferred solution is
03-24 13:13:06.122 21801 21833 E flutter : to cancel the timer or stop listening to the animation in the dispose()
03-24 13:13:06.122 21801 21833 E flutter : callback. Another solution is to check the "mounted" property of this
03-24 13:13:06.122 21801 21833 E flutter : object before calling setState() to ensure the object is still in the tree.
03-24 13:13:06.122 21801 21833 E flutter : #0      State.setState.<anonymous closure> (packages/flutter/src/widgets/framework.dart:386)
03-24 13:13:06.122 21801 21833 E flutter : #1      State.setState (packages/flutter/src/widgets/framework.dart:384)
03-24 13:13:06.122 21801 21833 E flutter : #2      _CreateCompanySheetState._handleCompanyNameChanged (/usr/local/google/home/ianh/dev/flutter/examples/stocks/lib/stock_home.dart:370)
03-24 13:13:06.122 21801 21833 E flutter : #3      RawInputLineState._handleTextUpdated (packages/flutter/src/widgets/editable.dart:276)
03-24 13:13:06.122 21801 21833 E flutter : #4      _KeyboardClientImpl.updateEditingState (packages/flutter/src/widgets/editable.dart:73)
03-24 13:13:06.122 21801 21833 E flutter : #5      KeyboardClientStub.handleMessage (packages/sky_services/editing/editing.mojom.dart:1018)
03-24 13:13:06.122 21801 21833 E flutter : #6      Stub.handleRead (packages/mojo/src/stub.dart:33)
03-24 13:13:06.122 21801 21833 E flutter : #7      MojoEventHandler._handleEvent (packages/mojo/src/event_stream.dart:284)
03-24 13:13:06.122 21801 21833 E flutter : #8      MojoEventHandler._tryHandleEvent (packages/mojo/src/event_stream.dart:260)
03-24 13:13:06.122 21801 21833 E flutter : #9      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:148)
```

**Comment by zoechi** [comment]
I can't reproduce.

```
[✓] Flutter (Channel dev, v1.1.9, on Mac OS X 10.14.1 18B75, locale en-AT)
```
