### ISSUE TITLE
Running flutter test gives a Unhandled 'error' event

### ISSUE THREAD

**Issue by a-deeb** [flutter/flutter#28815]
Flutter currently has an unhandled error event in the events.js file ,
Is this the reason why flutter build is currently down?

## Logs

```
flutter run --verbose
events.js:167
      throw er; // Unhandled 'error' event
      ^

Error: spawn C:\Users\princ\AppData\Roaming\npm\node_modules\flutter-cli\bin/../flutter/bin/flutter ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:232:19)
    at onErrorNT (internal/child_process.js:407:16)
    at process._tickCallback (internal/process/next_tick.js:63:19)
    at Function.Module.runMain (internal/modules/cjs/loader.js:745:11)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:743:3)
Emitted 'error' event at:
    at Process.ChildProcess._handle.onexit (internal/child_process.js:238:12)
    at onErrorNT (internal/child_process.js:407:16)
    [... lines matching original stack trace ...]
    at bootstrapNodeJSCore (internal/bootstrap/node.js:743:3)

```

```
events.js:167
      throw er; // Unhandled 'error' event
      ^

Error: spawn C:\Users\princ\AppData\Roaming\npm\node_modules\flutter-cli\bin/../flutter/bin/flutter ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:232:19)
    at onErrorNT (internal/child_process.js:407:16)
    at process._tickCallback (internal/process/next_tick.js:63:19)
    at Function.Module.runMain (internal/modules/cjs/loader.js:745:11)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:743:3)
Emitted 'error' event at:
    at Process.ChildProcess._handle.onexit (internal/child_process.js:238:12)
    at onErrorNT (internal/child_process.js:407:16)
    [... lines matching original stack trace ...]
    at bootstrapNodeJSCore (internal/bootstrap/node.js:743:3)

```

```
 flutter analyze -v
events.js:167
      throw er; // Unhandled 'error' event
      ^

Error: spawn C:\Users\princ\AppData\Roaming\npm\node_modules\flutter-cli\bin/../flutter/bin/flutter ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:232:19)
    at onErrorNT (internal/child_process.js:407:16)
    at process._tickCallback (internal/process/next_tick.js:63:19)
    at Function.Module.runMain (internal/modules/cjs/loader.js:745:11)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:743:3)
Emitted 'error' event at:
    at Process.ChildProcess._handle.onexit (internal/child_process.js:238:12)
    at onErrorNT (internal/child_process.js:407:16)
    [... lines matching original stack trace ...]
    at bootstrapNodeJSCore (internal/bootstrap/node.js:743:3)

```

**Comment by jonahwilliams** [comment]
flutter-cli is not an official flutter tool.  Flutter ships with a cli, I would recommend using that instead.
