### ISSUE TITLE
Unable to pumpwidget for empty ListView widget

### ISSUE THREAD

**Issue by sridhartw** [flutter/flutter#28826]
## Steps to Reproduce

1. ... Create a file

`import 'package:flutter/material.dart';

class Menu extends StatelessWidget{

  @override
  Widget build(BuildContext context) {
    return new ListView();
  }
}`

2. Create a Test for the file

`import 'package:flutter_test/flutter_test.dart';
import 'package:tw_cafeteria/widget/menu.dart';

void main(){
  testWidgets("Should populate ListView", (WidgetTester tester){
    tester.pumpWidget(Menu());
  });
}`

3. Run the test

## Logs
══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
The following assertion was thrown building _ScrollableScope:
'package:flutter/src/painting/basic_types.dart': Failed assertion: line 222 pos 10: 'textDirection
!= null': is not true.

Either the assertion indicates an error in the framework itself, or we should provide substantially
more information in this error message to help you determine and fix the underlying cause.

When the exception was thrown, this was the stack:
#2      textDirectionToAxisDirection (package:flutter/src/painting/basic_types.dart:222:10)
#3      Viewport.getDefaultCrossAxisDirection (package:flutter/src/widgets/viewport.dart:128:16)
#4      Viewport.createRenderObject (package:flutter/src/widgets/viewport.dart:139:58)
#5      RenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4482:28)
#6      MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4961:11)
#7      _ViewportElement.mount (package:flutter/src/widgets/viewport.dart:186:11)
#8      Element.inflateWidget (package:flutter/src/widgets/framework.dart:2950:14)
#9      Element.updateChild (package:flutter/src/widgets/framework.dart:2753:12)
#10     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3732:16)
#11     Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
#12     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3701:5)
#13     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3696:5)
#14     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2950:14)
#15     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:12)
#16     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4860:14)
#17     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2950:14)
#18     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:12)
#19     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4860:14)
#20     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2950:14)
#21     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:12)
#22     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4860:14)
#23     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2950:14)
#24     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:12)
#25     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4860:14)
#26     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2950:14)
#27     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:12)
#28     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3732:16)
#29     Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
#30     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3701:5)
#31     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3848:11)
#32     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3696:5)
#33     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2950:14)
#34     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:12)
#35     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4860:14)
#36     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2950:14)
#37     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:12)
#38     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4860:14)
#39     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2950:14)
#40     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:12)
#41     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4860:14)
#42     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2950:14)
#43     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:12)
#44     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4860:14)
#45     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2950:14)
#46     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:12)
#47     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3732:16)
#48     Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
#49     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3701:5)
#50     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3696:5)
#51     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2950:14)
#52     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:12)
#53     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3732:16)
#54     Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
#55     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3701:5)
#56     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3848:11)
#57     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3696:5)
#58     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2950:14)
#59     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:12)
#60     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3732:16)
#61     Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
#62     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3701:5)
#63     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3848:11)
#64     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3696:5)
#65     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2950:14)
#66     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:12)
#67     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3732:16)
#68     Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
#69     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3701:5)
#70     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3696:5)
#71     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2950:14)
#72     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:12)
#73     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3732:16)
#74     Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
#75     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3701:5)
#76     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3696:5)
#77     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2950:14)
#78     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:12)
#79     RenderObjectToWidgetElement._rebuild (package:flutter/src/widgets/binding.dart:909:16)
#80     RenderObjectToWidgetElement.update (package:flutter/src/widgets/binding.dart:887:5)
#81     RenderObjectToWidgetElement.performRebuild (package:flutter/src/widgets/binding.dart:901:7)
#82     Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
#83     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2286:33)
#84     AutomatedTestWidgetsFlutterBinding.drawFrame (package:flutter_test/src/binding.dart:800:18)
#85     _TestWidgetsFlutterBinding&BindingBase&ServicesBinding&SchedulerBinding&GestureBinding&SemanticsBinding&RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:219:5)
#86     _TestWidgetsFlutterBinding&BindingBase&ServicesBinding&SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:990:15)
#87     _TestWidgetsFlutterBinding&BindingBase&ServicesBinding&SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:930:9)
#88     AutomatedTestWidgetsFlutterBinding.pump.<anonymous closure> (package:flutter_test/src/binding.dart:714:9)
#91     TestAsyncUtils.guard (package:flutter_test/src/test_async_utils.dart:69:41)
#92     AutomatedTestWidgetsFlutterBinding.pump (package:flutter_test/src/binding.dart:701:27)
#93     WidgetTester.pumpWidget.<anonymous closure> (package:flutter_test/src/widget_tester.dart:227:22)
#96     TestAsyncUtils.guard (package:flutter_test/src/test_async_utils.dart:69:41)
#97     WidgetTester.pumpWidget (package:flutter_test/src/widget_tester.dart:224:27)
#98     main.<anonymous closure> (file:///Users/sridharmudra/Developement/pet/tw_cafeteria/test/menu_widget_test.dart:12:12)
#99     testWidgets.<anonymous closure>.<anonymous closure> (package:flutter_test/src/widget_tester.dart:72:23)
#100    TestWidgetsFlutterBinding._runTestBody (package:flutter_test/src/binding.dart:566:19)
<asynchronous suspension>
#103    TestWidgetsFlutterBinding._runTest (package:flutter_test/src/binding.dart:550:14)
#104    AutomatedTestWidgetsFlutterBinding.runTest.<anonymous closure> (package:flutter_test/src/binding.dart:893:24)
#110    AutomatedTestWidgetsFlutterBinding.runTest (package:flutter_test/src/binding.dart:890:15)
#111    testWidgets.<anonymous closure> (package:flutter_test/src/widget_tester.dart:71:22)
#112    Declarer.test.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:test_api/src/backend/declarer.dart:168:27)
<asynchronous suspension>
#113    Invoker.waitForOutstandingCallbacks.<anonymous closure> (package:test_api/src/backend/invoker.dart:249:15)
<asynchronous suspension>
#118    Invoker.waitForOutstandingCallbacks (package:test_api/src/backend/invoker.dart:246:5)
#119    Declarer.test.<anonymous closure>.<anonymous closure> (package:test_api/src/backend/declarer.dart:166:33)
#124    Declarer.test.<anonymous closure> (package:test_api/src/backend/declarer.dart:165:13)
<asynchronous suspension>
#125    Invoker._onRun.<anonymous closure>.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:test_api/src/backend/invoker.dart:399:25)
<asynchronous suspension>
#139    _Timer._runTimers (dart:isolate/runtime/libtimer_impl.dart:382:19)
#140    _Timer._handleMessage (dart:isolate/runtime/libtimer_impl.dart:416:5)
#141    _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:171:12)
(elided 34 frames from class _AssertionError, class _FakeAsync, package dart:async, and package
stack_trace)

```
```

```
```

```
```

**Comment by sridhartw** [comment]
https://github.com/flutter/flutter/issues/22523

The issue was already raised earlier. The problem was using material related classes without wrapping them with MaterialApp. Sorry.
