### ISSUE TITLE
Stable_1.0.0 IOS running crash

### ISSUE THREAD

**Issue by LebenNNA** [flutter/flutter#28830]
## Log Info

[log.txt](https://github.com/flutter/flutter/files/2926198/log.txt)

## Logs

```
bogon:x5_shequ h3d-nna$ flutter run --verbose
[  +22 ms] executing: [/Users/h3d-nna/Documents/stable/flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[  +26 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/stable
[        ] executing: [/Users/h3d-nna/Documents/stable/flutter/] git rev-parse --abbrev-ref HEAD
[   +8 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] stable
[        ] executing: [/Users/h3d-nna/Documents/stable/flutter/] git ls-remote --get-url origin
[   +9 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[   +2 ms] executing: [/Users/h3d-nna/Documents/stable/flutter/] git log -n 1 --pretty=format:%H
[   +8 ms] Exit code 0 from: git log -n 1 --pretty=format:%H
[        ] 5391447fae6209bb21a89e6a5a6583cac1af9b4b
[        ] executing: [/Users/h3d-nna/Documents/stable/flutter/] git log -n 1 --pretty=format:%ar
[   +9 ms] Exit code 0 from: git log -n 1 --pretty=format:%ar
[        ] 3 months ago
[        ] executing: [/Users/h3d-nna/Documents/stable/flutter/] git describe --match v*.*.* --first-parent --long --tags
[  +10 ms] Exit code 0 from: git describe --match v*.*.* --first-parent --long --tags
[        ] v1.0.0-0-g5391447fa
[ +180 ms] executing: /Users/h3d-nna/Library/Android/sdk/platform-tools/adb devices -l
[   +6 ms] Exit code 0 from: /Users/h3d-nna/Library/Android/sdk/platform-tools/adb devices -l
[        ] List of devices attached
[   +3 ms] executing: idevice_id -h
[ +318 ms] executing: which ideviceinstaller
[   +4 ms] Exit code 0 from: which ideviceinstaller
[        ] /usr/local/bin/ideviceinstaller
[        ] executing: which iproxy
[   +3 ms] Exit code 0 from: which iproxy
[        ] /usr/local/bin/iproxy
[   +3 ms] /usr/bin/xcrun simctl list --json devices
[ +154 ms] More than one device connected; please specify a device with the '-d <deviceId>' flag, or use '-d all' to act on all devices.
[   +4 ms] dongxiaoiPhone • e90da41de945b9d8d5320facfb087b4027d0d7a2 • ios • iOS 10.3.3
[        ] iPhone 8 Plus  • 7F484401-C0C2-4A08-93D5-0F737E0758F2     • ios • iOS 12.1 (simulator)
[   +7 ms] "flutter run" took 646ms.

#0      throwToolExit (package:flutter_tools/src/base/common.dart:26:3)
#1      RunCommand.validateCommand (package:flutter_tools/src/commands/run.dart:249:7)
<asynchronous suspension>
#2      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:379:11)
<asynchronous suspension>
#3      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:335:33)
<asynchronous suspension>
#4      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:142:29)
<asynchronous suspension>
#5      _rootRun (dart:async/zone.dart:1124:13)
#6      _CustomZone.run (dart:async/zone.dart:1021:19)
#7      _runZoned (dart:async/zone.dart:1516:10)
#8      runZoned (dart:async/zone.dart:1463:12)
#9      AppContext.run (package:flutter_tools/src/base/context.dart:141:18)
<asynchronous suspension>
#10     FlutterCommand.run (package:flutter_tools/src/runner/flutter_command.dart:326:20)
#11     CommandRunner.runCommand (package:args/command_runner.dart:196:27)
<asynchronous suspension>
#12     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:401:21)
<asynchronous suspension>
#13     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:142:29)
<asynchronous suspension>
#14     _rootRun (dart:async/zone.dart:1124:13)
#15     _CustomZone.run (dart:async/zone.dart:1021:19)
#16     _runZoned (dart:async/zone.dart:1516:10)
#17     runZoned (dart:async/zone.dart:1463:12)
#18     AppContext.run (package:flutter_tools/src/base/context.dart:141:18)
<asynchronous suspension>
#19     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:361:19)
<asynchronous suspension>
#20     CommandRunner.run.<anony
```

```
bogon:x5_shequ h3d-nna$ flutter doctor -v
[✓] Flutter (Channel stable, v1.0.0, on Mac OS X 10.14.2 18C54, locale zh-Hans-CN)
    • Flutter version 1.0.0 at /Users/h3d-nna/Documents/stable/flutter
    • Framework revision 5391447fae (3 months ago), 2018-11-29 19:41:26 -0800
    • Engine revision 7375a0f414
    • Dart version 2.1.0 (build 2.1.0-dev.9.4 f9ebf21297)

[✓] Android toolchain - develop for Android devices (Android SDK 28.0.3)
    • Android SDK at /Users/h3d-nna/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.1, Build version 10B61
    • ios-deploy 1.9.4
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 31.3.3
    • Dart plugin version 182.5124
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)

[✓] VS Code (version 1.31.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 2.24.0

[✓] Connected device (2 available)
    • dongxiaoiPhone • e90da41de945b9d8d5320facfb087b4027d0d7a2 • ios • iOS 10.3.3
    • iPhone 8 Plus  • 7F484401-C0C2-4A08-93D5-0F737E0758F2     • ios • iOS 12.1 (simulator)

• No issues found!
bogon:x5_shequ h3d-nna$
```

**Comment by jonahwilliams** [comment]
> More than one device connected; please specify a device with the '-d <deviceId>' flag, or use '-d all' to act on all devices.

Hi @LebenNNA , if you have more than one device connected you need to specify which one.

**Comment by LebenNNA** [comment]
When I only install one device, it will
@jonahwilliams
