### ISSUE TITLE
Flutter crash report

### ISSUE THREAD

**Issue by SudharsanKrishnamoorthy** [flutter/flutter#28850]
Flutter crash report; please file at https://github.com/flutter/flutter/issues.

## command

flutter doctor

## exception

ProcessException: ProcessException: %1 is not a valid Win32 application.

  Command: C:\Program Files\Android\Android Studio\jre\bin\java.EXE -version

```
#0      _ProcessImpl._runAndWait (dart:io/runtime/bin/process_patch.dart:489:7)
#1      _runNonInteractiveProcessSync (dart:io/runtime/bin/process_patch.dart:634:18)
#2      Process.runSync (dart:io/runtime/bin/process_patch.dart:66:12)
#3      LocalProcessManager.runSync (package:process/src/interface/local_process_manager.dart:83:20)
#4      AndroidStudio._init (package:flutter_tools/src/android/android_studio.dart:294:51)
#5      new AndroidStudio (package:flutter_tools/src/android/android_studio.dart:36:5)
#6      new AndroidStudio.fromHomeDot (package:flutter_tools/src/android/android_studio.dart:96:14)
#7      AndroidStudio._allLinuxOrWindows (package:flutter_tools/src/android/android_studio.dart:238:54)
#8      AndroidStudio.allInstalled (package:flutter_tools/src/android/android_studio.dart:171:40)
#9      AndroidStudioValidator.allValidators (package:flutter_tools/src/android/android_studio_validator.dart:21:55)
#10     _DefaultDoctorValidatorsProvider.validators (package:flutter_tools/src/doctor.dart:62:51)
#11     Doctor.validators (package:flutter_tools/src/doctor.dart:108:46)
#12     Doctor.startValidatorTasks (package:flutter_tools/src/doctor.dart:115:39)
#13     Doctor.diagnose (package:flutter_tools/src/doctor.dart:189:41)
<asynchronous suspension>
#14     DoctorCommand.runCommand (package:flutter_tools/src/commands/doctor.dart:48:39)
<asynchronous suspension>
#15     FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:549:18)
#16     _asyncThenWrapperHelper.<anonymous closure> (dart:async/runtime/lib/async_patch.dart:77:64)
#17     _rootRunUnary (dart:async/zone.dart:1132:38)
#18     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#19     _FutureListener.handleValue (dart:async/future_impl.dart:126:18)
#20     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:639:45)
#21     Future._propagateToListeners (dart:async/future_impl.dart:668:32)
#22     Future._complete (dart:async/future_impl.dart:473:7)
#23     _SyncCompleter.complete (dart:async/future_impl.dart:51:12)
#24     _AsyncAwaitCompleter.complete.<anonymous closure> (dart:async/runtime/lib/async_patch.dart:33:20)
#25     _rootRun (dart:async/zone.dart:1124:13)
#26     _CustomZone.run (dart:async/zone.dart:1021:19)
#27     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:947:23)
#28     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#29     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#30     _runPendingImmediateCallback (dart:isolate/runtime/lib/isolate_patch.dart:115:13)
#31     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/lib/isolate_patch.dart:172:5)
```

## flutter doctor

```
encountered exception: ProcessException: %1 is not a valid Win32 application.

  Command: C:\Program Files\Android\Android Studio\jre\bin\java.EXE -version

#0      _ProcessImpl._runAndWait (dart:io/runtime/bin/process_patch.dart:489:7)
#1      _runNonInteractiveProcessSync (dart:io/runtime/bin/process_patch.dart:634:18)
#2      Process.runSync (dart:io/runtime/bin/process_patch.dart:66:12)
#3      LocalProcessManager.runSync (package:process/src/interface/local_process_manager.dart:83:20)
#4      AndroidStudio._init (package:flutter_tools/src/android/android_studio.dart:294:51)
#5      new AndroidStudio (package:flutter_tools/src/android/android_studio.dart:36:5)
#6      new AndroidStudio.fromHomeDot (package:flutter_tools/src/android/android_studio.dart:96:14)
#7      AndroidStudio._allLinuxOrWindows (package:flutter_tools/src/android/android_studio.dart:238:54)
#8      AndroidStudio.allInstalled (package:flutter_tools/src/android/android_studio.dart:171:40)
#9      AndroidStudio.latestValid (package:flutter_tools/src/android/android_studio.dart:161:41)
#10     AppContext._generateIfNecessary.<anonymous closure> (package:flutter_tools/src/base/context.dart:99:41)
#11     __InternalLinkedHashMap&_HashVMBase&MapMixin&_LinkedHashMapMixin.putIfAbsent (dart:collection/runtime/lib/compact_hash.dart:281:23)
#12     AppContext._generateIfNecessary (package:flutter_tools/src/base/context.dart:87:20)
#13     AppContext.[] (package:flutter_tools/src/base/context.dart:114:32)
#14     AppContext.[] (package:flutter_tools/src/base/context.dart:113:22)
#15     androidStudio (package:flutter_tools/src/android/android_studio.dart:16:43)
#16     javaPath (package:flutter_tools/src/android/android_studio.dart:30:24)
#17     AndroidSdk.findJavaBinary (package:flutter_tools/src/android/android_sdk.dart:517:24)
#18     AndroidLicenseValidator._checkJavaVersionNoOutput (package:flutter_tools/src/android/android_workflow.dart:212:42)
<asynchronous suspension>
#19     AndroidLicenseValidator.validate (package:flutter_tools/src/android/android_workflow.dart:187:17)
<asynchronous suspension>
#20     GroupedValidator.validate (package:flutter_tools/src/doctor.dart:318:52)
#21     _AsyncAwaitCompleter.start (dart:async/runtime/lib/async_patch.dart:49:6)
#22     GroupedValidator.validate (package:flutter_tools/src/doctor.dart:315:36)
#23     Doctor.startValidatorTasks (package:flutter_tools/src/doctor.dart:116:52)
#24     Doctor.diagnose (package:flutter_tools/src/doctor.dart:189:41)
#25     _AsyncAwaitCompleter.start (dart:async/runtime/lib/async_patch.dart:49:6)
#26     Doctor.diagnose (package:flutter_tools/src/doctor.dart:179:24)
#27     _doctorText.<anonymous closure> (package:flutter_tools/runner.dart:188:26)
#28     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:142:29)
#29     _AsyncAwaitCompleter.start (dart:async/runtime/lib/async_patch.dart:49:6)
#30     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:142:7)
#31     _rootRun (dart:async/zone.dart:1124:13)
#32     _CustomZone.run (dart:async/zone.dart:1021:19)
#33     _runZoned (dart:async/zone.dart:1516:10)
#34     runZoned (dart:async/zone.dart:1463:12)
#35     AppContext.run (package:flutter_tools/src/base/context.dart:141:18)
#36     _AsyncAwaitCompleter.start (dart:async/runtime/lib/async_patch.dart:49:6)
#37     AppContext.run (package:flutter_tools/src/base/context.dart:129:19)
#38     _doctorText (package:flutter_tools/runner.dart:187:19)
#39     _AsyncAwaitCompleter.start (dart:async/runtime/lib/async_patch.dart:49:6)
#40     _doctorText (package:flutter_tools/runner.dart:183:27)
#41     _createLocalCrashReport (package:flutter_tools/runner.dart:165:32)
#42     _AsyncAwaitCompleter.start (dart:async/runtime/lib/async_patch.dart:49:6)
#43     _createLocalCrashReport (package:flutter_tools/runner.dart:150:37)
#44     _handleToolError (package:flutter_tools/runner.dart:120:33)
#45     _asyncThenWrapperHelper.<anonymous closure> (dart:async/runtime/lib/async_patch.dart:77:64)
#46     _rootRunUnary (dart:async/zone.dart:1132:38)
#47     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#48     _FutureListener.handleValue (dart:async/future_impl.dart:126:18)
#49     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:639:45)
#50     Future._propagateToListeners (dart:async/future_impl.dart:668:32)
#51     Future._complete (dart:async/future_impl.dart:473:7)
#52     _SyncCompleter.complete (dart:async/future_impl.dart:51:12)
#53     _AsyncAwaitCompleter.complete (dart:async/runtime/lib/async_patch.dart:28:18)
#54     _completeOnAsyncReturn (dart:async/runtime/lib/async_patch.dart:294:13)
#55     CrashReportSender.sendReport (package:flutter_tools/src/crash_reporting.dart)
#56     _asyncThenWrapperHelper.<anonymous closure> (dart:async/runtime/lib/async_patch.dart:77:64)
#57     _rootRunUnary (dart:async/zone.dart:1132:38)
#58     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#59     _FutureListener.handleValue (dart:async/future_impl.dart:126:18)
#60     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:639:45)
#61     Future._propagateToListeners (dart:async/future_impl.dart:668:32)
#62     Future._complete (dart:async/future_impl.dart:473:7)
#63     Stream.fold.<anonymous closure> (dart:async/stream.dart:724:18)
#64     _rootRun (dart:async/zone.dart:1120:38)
#65     _CustomZone.run (dart:async/zone.dart:1021:19)
#66     _CustomZone.runGuarded (dart:async/zone.dart:923:7)
#67     _BufferingStreamSubscription._sendDone.sendDone (dart:async/stream_impl.dart:389:13)
#68     _BufferingStreamSubscription._sendDone (dart:async/stream_impl.dart:399:15)
#69     _BufferingStreamSubscription._close (dart:async/stream_impl.dart:283:7)
#70     _SinkTransformerStreamSubscription._close (dart:async/stream_transformers.dart:96:11)
#71     _EventSinkWrapper.close (dart:async/stream_transformers.dart:23:11)
#72     _StringAdapterSink.close (dart:convert/string_conversion.dart:251:11)
#73     _Utf8ConversionSink.close (dart:convert/string_conversion.dart:302:20)
#74     _ConverterStreamEventSink.close (dart:convert/chunked_conversion.dart:82:18)
#75     _SinkTransformerStreamSubscription._handleDone (dart:async/stream_transformers.dart:141:24)
#76     _rootRun (dart:async/zone.dart:1120:38)
#77     _CustomZone.run (dart:async/zone.dart:1021:19)
#78     _CustomZone.runGuarded (dart:async/zone.dart:923:7)
#79     _BufferingStreamSubscription._sendDone.sendDone (dart:async/stream_impl.dart:389:13)
#80     _BufferingStreamSubscription._sendDone (dart:async/stream_impl.dart:399:15)
#81     _BufferingStreamSubscription._close (dart:async/stream_impl.dart:283:7)
#82     _ForwardingStream._handleDone (dart:async/stream_pipe.dart:106:10)
#83     _ForwardingStreamSubscription._handleDone (dart:async/stream_pipe.dart:172:13)
#84     _rootRun (dart:async/zone.dart:1120:38)
#85     _CustomZone.run (dart:async/zone.dart:1021:19)
#86     _CustomZone.runGuarded (dart:async/zone.dart:923:7)
#87     _BufferingStreamSubscription._sendDone.sendDone (dart:async/stream_impl.dart:389:13)
#88     _BufferingStreamSubscription._sendDone (dart:async/stream_impl.dart:399:15)
#89     _BufferingStreamSubscription._close (dart:async/stream_impl.dart:283:7)
#90     _SinkTransformerStreamSubscription._close (dart:async/stream_transformers.dart:96:11)
#91     _EventSinkWrapper.close (dart:async/stream_transformers.dart:23:11)
#92     _ByteAdapterSink.close (dart:convert/byte_conversion.dart:62:11)
#93     _FilterSink.close (dart:io/data_transformer.dart:637:11)
#94     _ConverterStreamEventSink.close (dart:convert/chunked_conversion.dart:82:18)
#95     _SinkTransformerStreamSubscription._handleDone (dart:async/stream_transformers.dart:141:24)
#96     _rootRun (dart:async/zone.dart:1120:38)
#97     _CustomZone.run (dart:async/zone.dart:1021:19)
#98     _CustomZone.runGuarded (dart:async/zone.dart:923:7)
#99     _BufferingStreamSubscription._sendDone.sendDone (dart:async/stream_impl.dart:389:13)
#100    _BufferingStreamSubscription._sendDone (dart:async/stream_impl.dart:399:15)
#101    _BufferingStreamSubscription._close (dart:async/stream_impl.dart:283:7)
#102    _ForwardingStream._handleDone (dart:async/stream_pipe.dart:106:10)
#103    _ForwardingStreamSubscription._handleDone (dart:async/stream_pipe.dart:172:13)
#104    _rootRun (dart:async/zone.dart:1120:38)
#105    _CustomZone.run (dart:async/zone.dart:1021:19)
#106    _CustomZone.runGuarded (dart:async/zone.dart:923:7)
#107    _BufferingStreamSubscription._sendDone.sendDone (dart:async/stream_impl.dart:389:13)
#108    _BufferingStreamSubscription._sendDone (dart:async/stream_impl.dart:399:15)
#109    _BufferingStreamSubscription._close (dart:async/stream_impl.dart:283:7)
#110    _SyncStreamController._sendDone (dart:async/stream_controller.dart:772:19)
#111    _StreamController._closeUnchecked (dart:async/stream_controller.dart:629:7)
#112    _StreamController.close (dart:async/stream_controller.dart:622:5)
#113    _HttpParser._closeIncoming (dart:_http/http_parser.dart:1037:23)
#114    _HttpParser._doParse (dart:_http/http_parser.dart:752:11)
#115    _HttpParser._parse (dart:_http/http_parser.dart:318:7)
#116    _HttpParser._onData (dart:_http/http_parser.dart:810:5)
#117    _rootRunUnary (dart:async/zone.dart:1132:38)
#118    _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#119    _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
#120    _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#121    _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#122    _SyncStreamController._sendData (dart:async/stream_controller.dart:764:19)
#123    _StreamController._add (dart:async/stream_controller.dart:640:7)
#124    _StreamController.add (dart:async/stream_controller.dart:586:5)
#125    _Socket._onData (dart:io/runtime/bin/socket_patch.dart:1774:41)
#126    _rootRunUnary (dart:async/zone.dart:1132:38)
#127    _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#128    _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
#129    _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#130    _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#131    _SyncStreamController._sendData (dart:async/stream_controller.dart:764:19)
#132    _StreamController._add (dart:async/stream_controller.dart:640:7)
#133    _StreamController.add (dart:async/stream_controller.dart:586:5)
#134    _RawSecureSocket._sendReadEvent (dart:io/secure_socket.dart:1004:19)
#135    _rootRun (dart:async/zone.dart:1120:38)
#136    _CustomZone.run (dart:async/zone.dart:1021:19)
#137    _CustomZone.runGuarded (dart:async/zone.dart:923:7)
#138    _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:963:23)
#139    _rootRun (dart:async/zone.dart:1124:13)
#140    _CustomZone.run (dart:async/zone.dart:1021:19)
#141    _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:947:23)
#142    Timer._createTimer.<anonymous closure> (dart:async/runtime/lib/timer_patch.dart:21:15)
#143    _Timer._runTimers (dart:isolate/runtime/lib/timer_impl.dart:382:19)
#144    _Timer._handleMessage (dart:isolate/runtime/lib/timer_impl.dart:416:5)
#145    _RawReceivePortImpl._handleMessage (dart:isolate/runtime/lib/isolate_patch.dart:171:12)
```

**Comment by kangwang1988** [comment]
@SudharsanKrishnamoorthy 
What's the result for ` C:\Program Files\Android\Android Studio\jre\bin\java.EXE -version` when calling from the cmd window?
