### ISSUE TITLE
google_sign_in

### ISSUE THREAD

**Issue by horgag1** [flutter/flutter#28882]

**Comment by horgag1** [comment]
![stack](https://user-images.githubusercontent.com/22146754/53803898-feafcd80-3f3d-11e9-8239-2379728c9992.gif)

**Comment by nvma** [comment]
The same animation applies when the user is signing in for the first time as well. Is there a way to disable it entirely?

**Comment by ratherNotB** [comment]
Wondering if there's a solution for this issue? I'm seeing it with the latest stable channel and google_sign_in v4.1.1. I suspected an issue with my Firebase project certificates, but I've doubled checked them and have regenerated the google-services.json file, however the problem persists. I should note that I'm able to login using Google without any issues despite the black band running down the screen.

Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, v1.12.13+hotfix.8, on Mac OS X 10.15.2 19C57, locale en-CA)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 11.3.1)
[✓] Android Studio (version 3.5)
[✓] VS Code (version 1.41.1)
[✓] Connected device (1 available)

• No issues found!

Logcat shows the following error:

W/ActivityThread: handleWindowVisibility: no activity for token android.os.BinderProxy@6593d13
I/AppCompatDelegate: Failed to instantiate custom view inflater android.support.v7.app.AppCompatViewInflater. Falling back to default.
    java.lang.ClassNotFoundException: android.support.v7.app.AppCompatViewInflater
        at java.lang.Class.classForName(Native Method)
        at java.lang.Class.forName(Class.java:454)
        at java.lang.Class.forName(Class.java:379)
        at tb.a(:com.google.android.gms@20104037@20.1.04 (120400-288960190):47)
        at tb.onCreateView(:com.google.android.gms@20104037@20.1.04 (120400-288960190):1)
        at android.view.LayoutInflater.tryCreateView(LayoutInflater.java:1061)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:997)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:961)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:659)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:534)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:481)
        at com.android.internal.policy.DecorView.onResourcesLoaded(DecorView.java:2086)
        at com.android.internal.policy.PhoneWindow.generateLayout(PhoneWindow.java:2627)
        at com.android.internal.policy.PhoneWindow.installDecor(PhoneWindow.java:2694)
        at com.android.internal.policy.PhoneWindow.getDecorView(PhoneWindow.java:2094)
        at android.app.ActivityTransitionState.setEnterActivityOptions(ActivityTransitionState.java:171)
        at android.app.Activity.performCreate(Activity.java:7833)
        at android.app.Activity.performCreate(Activity.java:7814)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1306)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3245)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3409)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2016)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7356)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
     Caused by: java.lang.ClassNotFoundException: android.support.v7.app.AppCompatViewInflater
        at java.lang.Class.classForName(Native Method) 
        at java.lang.Class.forName(Class.java:454) 
        at java.lang.Class.forName(Class.java:379) 
        at tb.a(:com.google.android.gms@20104037@20.1.04 (120400-288960190):47) 
        at tb.onCreateView(:com.google.android.gms@20104037@20.1.04 (120400-288960190):1) 
        at android.view.LayoutInflater.tryCreateView(LayoutInflater.java:1061) 
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:997) 
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:961) 
        at android.view.LayoutInflater.inflate(LayoutInflater.java:659) 
        at android.view.LayoutInflater.inflate(LayoutInflater.java:534) 
        at android.view.LayoutInflater.inflate(LayoutInflater.java:481) 
        at com.android.internal.policy.DecorView.onResourcesLoaded(DecorView.java:2086) 
        at com.android.internal.policy.PhoneWindow.generateLayout(PhoneWindow.java:2627) 
        at com.android.internal.policy.PhoneWindow.installDecor(PhoneWindow.java:2694) 
        at com.android.internal.policy.PhoneWindow.getDecorView(PhoneWindow.java:2094) 
        at android.app.ActivityTransitionState.setEnterActivityOptions(ActivityTransitionState.java:171) 
        at android.app.Activity.performCreate(Activity.java:7833) 
        at android.app.Activity.performCreate(Activity.java:7814) 
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1306) 
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3245) 
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3409) 
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83) 
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2016) 
        at android.os.Handler.dispatchMessage(Handler.java:107) 
        at android.os.Looper.loop(Looper.java:214) 
        at android.app.ActivityThread.main(ActivityThread.java:7356) 

I have AndroidX configured in gradle.properties as follows:

org.gradle.jvmargs=-Xmx1536M
android.useAndroidX=true
android.enableJetifier=true
android.enableR8=true

Any ideas on how to resolve? I'm guessing the majority of users do not observe this running black band?

**Comment by jesper372** [comment]
I'm seeing this as well.

**Comment by archelnokov** [comment]
Same issue.

**Comment by stuartmorgan** [comment]
See https://github.com/flutter/flutter/issues/48371 for discussion of possible workarounds

**Comment by romaklym** [comment]
> The same animation applies when the user is signing in for the first time as well. Is there a way to disable it entirely?

https://github.com/flutter/flutter/issues/48371#issuecomment-1003618619

**Comment by stuartmorgan-g** [comment]
Closing as obsolete; the latest version of `google_sign_in` uses a different SDK on Android, and it has different UI flows.
