### ISSUE TITLE
FileSystemException: FileSystemException: Cannot copy file, errno = 32

### ISSUE THREAD

**Issue by Adrianogba** [flutter/flutter#28905]
## command

flutter build appbundle --release

## exception

FileSystemException: FileSystemException: Cannot copy file to 'C:\FlutterProjects\my-awesome-app\build\app\outputs\bundle\app.aab', path = 'C:\FlutterProjects\my-awesome-app\build\app\outputs\bundle\app.aab' (OS Error: The process cannot access the file because it is being used by another process.
, errno = 32)

```
#0      _File.throwIfError (dart:io/file_impl.dart:643:7)
#1      _File.copySync (dart:io/file_impl.dart:348:5)
#2      _LocalFile&LocalFileSystemEntity&ForwardingFile.copySync (package:file/src/forwarding/forwarding_file.dart:29:50)
#3      _buildGradleProjectV2 (package:flutter_tools/src/android/gradle.dart:604:16)
<asynchronous suspension>
#4      buildGradleProject (package:flutter_tools/src/android/gradle.dart:346:14)
<asynchronous suspension>
#5      buildAppBundle (package:flutter_tools/src/android/app_bundle.dart:43:10)
<asynchronous suspension>
#6      BuildAppBundleCommand.runCommand (package:flutter_tools/src/commands/build_appbundle.dart:43:11)
<asynchronous suspension>
#7      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:549:18)
#8      _asyncThenWrapperHelper.<anonymous closure> (dart:async/runtime/lib/async_patch.dart:77:64)
#9      _rootRunUnary (dart:async/zone.dart:1132:38)
#10     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#11     _FutureListener.handleValue (dart:async/future_impl.dart:126:18)
#12     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:639:45)
#13     Future._propagateToListeners (dart:async/future_impl.dart:668:32)
#14     Future._complete (dart:async/future_impl.dart:473:7)
#15     _SyncCompleter.complete (dart:async/future_impl.dart:51:12)
#16     _AsyncAwaitCompleter.complete.<anonymous closure> (dart:async/runtime/lib/async_patch.dart:33:20)
#17     _rootRun (dart:async/zone.dart:1124:13)
#18     _CustomZone.run (dart:async/zone.dart:1021:19)
#19     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:947:23)
#20     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#21     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#22     _runPendingImmediateCallback (dart:isolate/runtime/lib/isolate_patch.dart:115:13)
#23     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/lib/isolate_patch.dart:172:5)
```

## flutter doctor

```
[32m[✓][39m Flutter (Channel dev, v1.3.4, on Microsoft Windows [Version 10.0.18342.8], locale en-US)
    [32m•[39m Flutter version 1.3.4 at C:\flutter
    [32m•[39m Framework revision 7fc14a55af (27 hours ago), 2019-03-04 11:43:28 -0500
    [32m•[39m Engine revision e9eae9a1af
    [32m•[39m Dart version 2.2.1 (build 2.2.1-dev.0.0 7c70ab1817)

[33m[!][39m Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    [32m•[39m Android SDK at C:\Android\android-sdk
    [32m•[39m Android NDK location not configured (optional; useful for native profiling support)
    [32m•[39m Platform android-28, build-tools 28.0.3
    [32m•[39m ANDROID_HOME = C:\Android\android-sdk
    [32m•[39m Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    [32m•[39m Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)
    [31m✗[39m Android license status unknown.
      Try re-installing or updating your Android SDK Manager.
      See https://developer.android.com/studio/#downloads or visit https://flutter.io/setup/#android-setup for detailed instructions.

[32m[✓][39m Android Studio (version 3.3)
    [32m•[39m Android Studio at C:\Program Files\Android\Android Studio
    [32m•[39m Flutter plugin version 33.3.1
    [32m•[39m Dart plugin version 182.5215
    [32m•[39m Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)

[32m[✓][39m Connected device (1 available)
    [32m•[39m Custom Phone 1 • 192.168.165.101:5555 • android-x86 • Android 9 (API 28)

[33m![39m Doctor found issues in 1 category.
```

**Comment by Hait3ch** [comment]
I have the same problem

**Comment by tboyce021** [comment]
Same problem here. I can even delete the file and run the build again but it will still fail with the same error.

**Comment by tboyce021** [comment]
Just FYI, rebooting and doing `flutter clean` before trying to build again worked.

**Comment by DanielPayet** [comment]
In my case it's VSCode who block the file...

**Comment by iapicca** [comment]
Hi @Adrianogba 
I'm closing this issue as it refer to an older version of Flutter.
If the proposed [solution ](https://github.com/flutter/flutter/issues/28905#issuecomment-485053723) doesn't work and 
you are you still experiencing this issue with the latest version of Flutter,
you may want to open a new issue or comment below;
either way please provide your updated `flutter doctor -v`.
It would be helpful to have also your` flutter run --verbose`
and a self contained app on github (or the steps to reproduce it).
Thank you

**Comment by Adrianogba** [comment]
It's not happening since the update 1.9 since I've checked.

**Comment by majiar15** [comment]
a mi se me presento el mismo problema, aun no lo han solucionado

**Comment by iapicca** [comment]
Could everyone who still has this problem please file a new issue with the exact descriptions what happens, logs and the output of 'flutter doctor -v'  please.
All system setups can be slightly different so it's always better to open new issues and reference related issues.
