### ISSUE TITLE
Flutter tool crashes when running flutter-update packages

### ISSUE THREAD

**Issue by cbracken** [flutter/flutter#28915]
Flutter crash report; please file at https://github.com/flutter/flutter/issues.

## command

flutter update-packages

## exception

NonZeroExitCode: Exit code 128: error: Pulling is not possible because you have unmerged files.
hint: Fix them up in the work tree, and then use 'git add/rm <file>'
hint: as appropriate to mark resolution and make a commit.
fatal: Exiting because of an unresolved conflict.

```
#0      GoldensClient._runCommands (package:flutter_goldens_client/client.dart:142:9)
<asynchronous suspension>
#1      GoldensClient._syncTo (package:flutter_goldens_client/client.dart:121:11)
<asynchronous suspension>
#2      GoldensClient.prepare (package:flutter_goldens_client/client.dart:83:17)
<asynchronous suspension>
#3      UpdatePackagesCommand.runCommand (package:flutter_tools/src/commands/update_packages.dart:136:25)
<asynchronous suspension>
#4      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:549:18)
#5      _asyncThenWrapperHelper.<anonymous closure> (dart:async/runtime/lib/async_patch.dart:77:64)
#6      _rootRunUnary (dart:async/zone.dart:1132:38)
#7      _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#8      _FutureListener.handleValue (dart:async/future_impl.dart:126:18)
#9      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:639:45)
#10     Future._propagateToListeners (dart:async/future_impl.dart:668:32)
#11     Future._complete (dart:async/future_impl.dart:473:7)
#12     _SyncCompleter.complete (dart:async/future_impl.dart:51:12)
#13     _AsyncAwaitCompleter.complete.<anonymous closure> (dart:async/runtime/lib/async_patch.dart:33:20)
#14     _rootRun (dart:async/zone.dart:1124:13)
#15     _CustomZone.run (dart:async/zone.dart:1021:19)
#16     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:947:23)
#17     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#18     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#19     _runPendingImmediateCallback (dart:isolate/runtime/lib/isolate_patch.dart:115:13)
#20     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/lib/isolate_patch.dart:172:5)
```

## flutter doctor

```
ESC[32m[✓]ESC[39m Flutter (Channel unknown, v1.3.5-pre.8, on Linux, locale en_GB.UTF-8)
    ESC[32m•ESC[39m Flutter version 1.3.5-pre.8 at /usr/local/google/home/cbracken/src/flutter/flutter
    ESC[32m•ESC[39m Framework revision 32c85a9474 (5 hours ago), 2019-03-05 10:09:51 -0800
    ESC[32m•ESC[39m Engine revision f4951df193
    ESC[32m•ESC[39m Dart version 2.2.1 (build 2.2.1-dev.0.0 571ea80e11)

ESC[33m[!]ESC[39m Android toolchain - develop for Android devices (Android SDK version 27.0.3)
    ESC[32m•ESC[39m Android SDK at /usr/local/google/home/cbracken/Android/Sdk
    ESC[32m•ESC[39m Android NDK location not configured (optional; useful for native profiling support)
    ESC[31m✗ESC[39m Flutter requires Android SDK 28 and the Android BuildTools 28.0.3
      To update using sdkmanager, run:
        /usr/local/google/home/cbracken/Android/Sdk/tools/bin/sdkmanager "platforms;android-28" "build-tools;28.0.3"
      or visit https://flutter.io/setup/#android-setup for detailed instructions.
    ESC[33m!ESC[39m Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses

ESC[33m[!]ESC[39m Android Studio (version 3.1)
    ESC[32m•ESC[39m Android Studio at /opt/android-studio-3.1
    ESC[31m✗ESC[39m Flutter plugin not installed; this adds Flutter specific functionality.
    ESC[31m✗ESC[39m Dart plugin not installed; this adds Dart specific functionality.
    ESC[32m•ESC[39m Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)

ESC[33m[!]ESC[39m Connected device
    ESC[33m!ESC[39m No devices available

ESC[33m!ESC[39m Doctor found issues in 3 categories.
```

Interestingly the claim is I have unmerged files. That seems suspicious:
```
% git status
On branch roll-engine
nothing to commit, working tree clean
```

**Comment by Hixie** [comment]
check your golden repo

**Comment by cbracken** [comment]
Flutter, goldens, and engine repos all have the same git status reported at the bottom of the bug. :(
```
% git status
On branch master
Your branch is up to date with 'origin/master'.

nothing to commit, working tree clean
```

**Comment by cbracken** [comment]
FYI - the answer was that I *did* have local changes in the goldens repo under `bin/cache/pkg/flutter_goldens`, I just hadn't written golden tests in a long time... since before the advent of flutter_goldens_client apparently, so was looking in the wrong place.

Sent #28922 which fixes the crash.
