### ISSUE TITLE
flutter doctor crashes: Agreeing to the Xcode/iOS license requires admin privileges

### ISSUE THREAD

**Issue by vargavince91** [flutter/flutter#28939]
## Steps to Reproduce

1. Follow installation steps on [MacOS install](https://flutter.dev/docs/get-started/install/macos#android-setup)
2. I successfully [get the Flutter SDK](https://flutter.dev/docs/get-started/install/macos#get-the-flutter-sdk)
3. `flutter doctor` command works and produces meaningful help messages
4. Install Xcode
5. `flutter doctor` crashes

```
$ flutter doctor
Agreeing to the Xcode/iOS license requires admin privileges, please run “sudo xcodebuild -license” and then retry this command.
Doctor summary (to see all details, run flutter doctor -v):
Oops; flutter has exited unexpectedly.
Sending crash report to Google.
Error executing simctl: 69
Agreeing to the Xcode/iOS license requires admin privileges, please run “sudo xcodebuild -license” and then retry this command.
Failed to send crash report. Server responded with HTTP status code 400
```

## Expectation 👶 

The error message is meaningful and actionable ("run `sudo xcodebuild -license`"), but it still crashed the application. As `flutter doctor` already provides meaningful hints for achieving proper setup, I'd expect the error message ("`sudo xcodebuild -license`") to show up normally in the results
After I accepted the licence, flutter doctor runs successfully and provides messages for the missing steps for completing the installation

```
[✓] Flutter (Channel stable, v1.2.1, on Mac OS X 10.14.3 18D109, locale en-GB)
[!] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    ✗ Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses
[!] iOS toolchain - develop for iOS devices (Xcode 10.1)
/***** EXPECTED THE ERROR TO SHOW UP HERE *****/
    ✗ Xcode/iOS license is not accepted. Accepting requires admin privileges. To accept licence:
        sudo xcodebuild -license
```

### Crash report

Flutter crash report; please file at https://github.com/flutter/flutter/issues.

## command

flutter doctor

## exception

VersionCheckError: VersionCheckError: Command exited with code 69: git log -n 1 --pretty=format:%ad --date=iso
Standard error: 

Agreeing to the Xcode/iOS license requires admin privileges, please run “sudo xcodebuild -license” and then retry this command.

```
#0      _runSync (package:flutter_tools/src/version.dart:506:5)
#1      FlutterVersion._latestGitCommitDate (package:flutter_tools/src/version.dart:130:12)
#2      FlutterVersion.frameworkCommitDate (package:flutter_tools/src/version.dart:121:37)
#3      FlutterVersion.frameworkDate (package:flutter_tools/src/version.dart:83:31)
#4      FlutterValidator.validate (package:flutter_tools/src/doctor.dart:452:127)
<asynchronous suspension>
#5      Doctor.startValidatorTasks (package:flutter_tools/src/doctor.dart:116:52)
#6      Doctor.diagnose (package:flutter_tools/src/doctor.dart:189:41)
<asynchronous suspension>
#7      DoctorCommand.runCommand (package:flutter_tools/src/commands/doctor.dart:48:39)
<asynchronous suspension>
#8      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:545:18)
#9      _asyncThenWrapperHelper.<anonymous closure> (dart:async/runtime/libasync_patch.dart:77:64)
#10     _rootRunUnary (dart:async/zone.dart:1132:38)
#11     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#12     _FutureListener.handleValue (dart:async/future_impl.dart:126:18)
#13     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:639:45)
#14     Future._propagateToListeners (dart:async/future_impl.dart:668:32)
#15     Future._complete (dart:async/future_impl.dart:473:7)
#16     _SyncCompleter.complete (dart:async/future_impl.dart:51:12)
#17     _AsyncAwaitCompleter.complete.<anonymous closure> (dart:async/runtime/libasync_patch.dart:33:20)
#18     _rootRun (dart:async/zone.dart:1124:13)
#19     _CustomZone.run (dart:async/zone.dart:1021:19)
#20     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:947:23)
#21     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#22     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#23     _runPendingImmediateCallback (dart:isolate/runtime/libisolate_patch.dart:115:13)
#24     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:172:5)
```

## flutter doctor

```
encountered exception: VersionCheckError: Command exited with code 69: git log -n 1 --pretty=format:%ad --date=iso
Standard error: 

Agreeing to the Xcode/iOS license requires admin privileges, please run “sudo xcodebuild -license” and then retry this command.




#0      _runSync (package:flutter_tools/src/version.dart:506:5)
#1      FlutterVersion._latestGitCommitDate (package:flutter_tools/src/version.dart:130:12)
#2      FlutterVersion.frameworkCommitDate (package:flutter_tools/src/version.dart:121:37)
#3      FlutterVersion.frameworkDate (package:flutter_tools/src/version.dart:83:31)
#4      FlutterValidator.validate (package:flutter_tools/src/doctor.dart:452:127)
<asynchronous suspension>
#5      Doctor.startValidatorTasks (package:flutter_tools/src/doctor.dart:116:52)
#6      Doctor.diagnose (package:flutter_tools/src/doctor.dart:189:41)
<asynchronous suspension>
#7      _doctorText.<anonymous closure> (package:flutter_tools/runner.dart:188:26)
#8      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:142:29)
<asynchronous suspension>
#9      _rootRun (dart:async/zone.dart:1124:13)
#10     _CustomZone.run (dart:async/zone.dart:1021:19)
#11     _runZoned (dart:async/zone.dart:1516:10)
#12     runZoned (dart:async/zone.dart:1463:12)
#13     AppContext.run (package:flutter_tools/src/base/context.dart:141:18)
<asynchronous suspension>
#14     _doctorText (package:flutter_tools/runner.dart:187:19)
<asynchronous suspension>
#15     _createLocalCrashReport (package:flutter_tools/runner.dart:165:32)
<asynchronous suspension>
#16     _handleToolError (package:flutter_tools/runner.dart:120:33)
<asynchronous suspension>
#17     run.<anonymous closure> (package:flutter_tools/runner.dart:64:20)
<asynchronous suspension>
#18     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:142:29)
<asynchronous suspension>
#19     _rootRun (dart:async/zone.dart:1124:13)
#20     _CustomZone.run (dart:async/zone.dart:1021:19)
#21     _runZoned (dart:async/zone.dart:1516:10)
#22     runZoned (dart:async/zone.dart:1463:12)
#23     AppContext.run (package:flutter_tools/src/base/context.dart:141:18)
<asynchronous suspension>
#24     runInContext (package:flutter_tools/src/context_runner.dart:48:24)
<asynchronous suspension>
#25     run (package:flutter_tools/runner.dart:51:10)
#26     main (package:flutter_tools/executable.dart:52:9)
<asynchronous suspension>
#27     main (file:///Users/vince/development/flutter/packages/flutter_tools/bin/flutter_tools.dart:8:3)
#28     _startIsolate.<anonymous closure> (dart:isolate/runtime/libisolate_patch.dart:298:32)
#29     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:171:12)
```

**Comment by muhammad-usman-anwar** [comment]
Same issue, works fine running from android studio. But does not work through terminal.
Mine terminal just hangs after any flutter command.
log shows the same issue
