### ISSUE TITLE
Flutter crashes  when creating new project

### ISSUE THREAD

**Issue by VNAPNIC** [flutter/flutter#28941]
## exception

FileSystemException: FileSystemException: Cannot open file, path = 'D:\Flutter\SDK\flutter\bin\cache\downloads\storage.googleapis.com\flutter_infra\flutter\fonts\13ac995daa9dda0a6ba0a45f1fccc541e616a74c\fonts.zip' (OS Error: Access is denied.
, errno = 5)

```
#0      _File.throwIfError (dart:io/file_impl.dart:643:7)
#1      _File.openSync (dart:io/file_impl.dart:487:5)
#2      _File.readAsBytesSync (dart:io/file_impl.dart:547:18)
#3      _LocalFile&LocalFileSystemEntity&ForwardingFile.readAsBytesSync (package:file/src/forwarding/forwarding_file.dart:88:43)
#4      _WindowsUtils.unzip (package:flutter_tools/src/base/os.dart:190:59)
#5      CachedArtifact._downloadArchive.<anonymous closure> (package:flutter_tools/src/cache.dart:314:16)
<asynchronous suspension>
#6      CachedArtifact._withDownloadFile (package:flutter_tools/src/cache.dart:333:26)
<asynchronous suspension>
#7      CachedArtifact._downloadArchive (package:flutter_tools/src/cache.dart:300:12)
#8      CachedArtifact._downloadZipArchive (package:flutter_tools/src/cache.dart:320:12)
#9      MaterialFonts.updateInner (package:flutter_tools/src/cache.dart:356:12)
#10     CachedArtifact.update (package:flutter_tools/src/cache.dart:263:11)
<asynchronous suspension>
#11     Cache.updateAll (package:flutter_tools/src/cache.dart:219:26)
<asynchronous suspension>
#12     FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:534:19)
<asynchronous suspension>
#13     FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:486:33)
<asynchronous suspension>
#14     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:142:29)
<asynchronous suspension>
#15     _rootRun (dart:async/zone.dart:1124:13)
#16     _CustomZone.run (dart:async/zone.dart:1021:19)
#17     _runZoned (dart:async/zone.dart:1516:10)
#18     runZoned (dart:async/zone.dart:1463:12)
#19     AppContext.run (package:flutter_tools/src/base/context.dart:141:18)
<asynchronous suspension>
#20     FlutterCommand.run (package:flutter_tools/src/runner/flutter_command.dart:477:20)
#21     CommandRunner.runCommand (package:args/command_runner.dart:196:27)
<asynchronous suspension>
#22     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:396:21)
<asynchronous suspension>
#23     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:142:29)
<asynchronous suspension>
#24     _rootRun (dart:async/zone.dart:1124:13)
#25     _CustomZone.run (dart:async/zone.dart:1021:19)
#26     _runZoned (dart:async/zone.dart:1516:10)
#27     runZoned (dart:async/zone.dart:1463:12)
#28     AppContext.run (package:flutter_tools/src/base/context.dart:141:18)
<asynchronous suspension>
#29     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:356:19)
<asynchronous suspension>
#30     CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:111:29)
#31     new Future.sync (dart:async/future.dart:224:31)
#32     CommandRunner.run (package:args/command_runner.dart:111:11)
#33     FlutterCommandRunner.run (package:flutter_tools/src/runner/flutter_command_runner.dart:242:18)
#34     run.<anonymous closure> (package:flutter_tools/runner.dart:60:20)
<asynchronous suspension>
#35     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:142:29)
<asynchronous suspension>
#36     _rootRun (dart:async/zone.dart:1124:13)
#37     _CustomZone.run (dart:async/zone.dart:1021:19)
#38     _runZoned (dart:async/zone.dart:1516:10)
#39     runZoned (dart:async/zone.dart:1463:12)
#40     AppContext.run (package:flutter_tools/src/base/context.dart:141:18)
<asynchronous suspension>
#41     runInContext (package:flutter_tools/src/context_runner.dart:51:24)
<asynchronous suspension>
#42     run (package:flutter_tools/runner.dart:51:10)
#43     main (package:flutter_tools/executable.dart:59:9)
<asynchronous suspension>
#44     main (file:///D:/Flutter/SDK/flutter/packages/flutter_tools/bin/flutter_tools.dart:8:3)
#45     _startIsolate.<anonymous closure> (dart:isolate/runtime/lib/isolate_patch.dart:298:32)
#46     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/lib/isolate_patch.dart:171:12)
```

## flutter doctor

```
[!] Flutter (Channel master, v1.3.5-pre.9, on Microsoft Windows [Version 10.0.17763.348], locale en-US)
    • Flutter version 1.3.5-pre.9 at D:\Flutter\SDK\flutter
    • Framework revision 4c1f4d14e1 (4 hours ago), 2019-03-06 09:37:32 +0100
    • Engine revision f4951df193
    • Dart version 2.2.1 (build 2.2.1-dev.0.0 571ea80e11)
    ✗ Downloaded executables cannot execute on host.
      See https://github.com/flutter/flutter/issues/6207 for more information


[!] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at D:/Android/SDK
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform Android-28, build-tools 28.0.3
    • ANDROID_HOME = D:/Android/SDK
    • Java binary at: C:\Program Files\Java\jdk1.8.0_201\bin\java
    • Java version Java(TM) SE Runtime Environment (build 1.8.0_201-b09)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses

[!] Android Studio (version 3.3)
    • Android Studio at D:\Android\Android Studio
    • Flutter plugin installed
    • Dart plugin installed
    ✗ Unable to determine the bundled Java version.
    • Try updating or re-installing Android Studio.

[!] Connected device
    ! No devices available

! Doctor found issues in 4 categories.
```

**Comment by GaryQian** [comment]
Are you on an administrator account? It looks like you dont have permission to access one of the files.
