### ISSUE TITLE
Material click not work

### ISSUE THREAD

**Issue by jintian93** [flutter/flutter#28947]
```
 [ERROR:flutter/lib/ui/ui_dart_state.cc(148)] Unhandled Exception: 'package:flutter/src/widgets/navigator.dart': Failed assertion: line 1666 pos 12: '!_debugLocked': is not true.
E/flutter (32614): #0      _AssertionError._doThrowNew (dart:core/runtime/liberrors_patch.dart:40:39)
E/flutter (32614): #1      _AssertionError._throwNew (dart:core/runtime/liberrors_patch.dart:36:5)
E/flutter (32614): #2      NavigatorState.push (package:flutter/src/widgets/navigator.dart:1666:12)
E/flutter (32614): #3      _TabPage1State._navigateToChatDetail (package:tunnel/tab_page/tab1_page.dart:599:69)
E/flutter (32614): <asynchronous suspension>
E/flutter (32614): #4      _TabPage1State._buildSessionList.<anonymous closure> (package:tunnel/tab_page/tab1_page.dart:342:28)
E/flutter (32614): #5      _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:513:14)
E/flutter (32614): #6      _InkResponseState.build.<anonymous closure> (package:flutter/src/material/ink_well.dart:568:30)
E/flutter (32614): #7      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:120:24)
E/flutter (32614): #8      TapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:242:9)
E/flutter (32614): #9      TapGestureRecognizer.acceptGesture (package:flutter/src/gestures/tap.dart:204:7)
E/flutter (32614): #10     GestureArenaManager.sweep (package:flutter/src/gestures/arena.dart:156:27)
E/flutter (32614): #11     _WidgetsFlutterBinding&BindingBase&GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:218:20)
E/flutter (32614): #12     _WidgetsFlutterBinding&BindingBase&GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:192:22)
E/flutter (32614): #13     _WidgetsFlutterBinding&BindingBase&GestureBinding._handlePointerEvent (package:flutter/src/gestures/binding.dart:149:7)
E/flutter (32614): #14     _WidgetsFlutterBinding&BindingBase&GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:101:7)
E/flutter (32614): #15     _WidgetsFlutterBinding&BindingBase&GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:85:7)
E/flutter (32614): #16     _rootRunUnary (dart:async/zone.dart:1136:13)
E/flutter (32614): #17     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
E/flutter (32614): #18     _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
E/flutter (32614): #19     _invoke1 (dart:ui/hooks.dart:223:10)
E/flutter (32614): #20     _dispatchPointerDataPacket (dart:ui/hooks.dart:144:5)

```

It throws this bug

**Comment by HansMuller** [comment]
Please provide a simple self-contained test case that demonstrates this bug. We'll be happy to look into it.
