### ISSUE TITLE
InputEventReceiver exception dispatching input event with Flutter 1.2.1 and Android JellyBean 4.1.2

### ISSUE THREAD

**Issue by sarah-fernandez** [flutter/flutter#28984]
## Steps to Reproduce

Using Android Studio. I have two different applications (one is a game, and the other is a set of widgets to better manage the space in tablets).

1. They were running smoothly in flutter 1.1.2 beta for devices from API 16 up to API 27, and emulators from API 21 up to API 28.

2. After flutter upgrade to flutter 1.2.1 beta, both applications in my device with API 16 fails at the moment of touching anything inside the application with the same error.

3. Then the application dies and a dialog that reads Unfortunately, <application_name> has stopped and an exception is thrown through the log file.

4. Both applications works fine in a Samsung Galaxy Nexus API 17 Jelly Bean MR1 and up to a Moto G5 Plus API 27, so this is a problem only in Jelly Bean API 16.

## Logs

Both applications start fine. But touching anything in the screen we get the following log error:

```
[+445864 ms] E/InputEventReceiver( 3225): Exception dispatching input event.
[   +4 ms] E/MessageQueue-JNI( 3225): Exception in MessageQueue callback: handleReceiveCallback
[  +22 ms] E/MessageQueue-JNI( 3225): java.lang.NoSuchMethodError: android.view.MotionEvent.isFromSource
[        ] E/MessageQueue-JNI( 3225):   at io.flutter.view.FlutterView.onGenericMotionEvent(FlutterView.java:590)
[        ] E/MessageQueue-JNI( 3225):   at android.view.View.dispatchGenericMotionEventInternal(View.java:7238)
[        ] E/MessageQueue-JNI( 3225):   at android.view.View.dispatchGenericMotionEvent(View.java:7219)
[        ] E/MessageQueue-JNI( 3225):   at android.view.ViewGroup.dispatchTransformedGenericPointerEvent(ViewGroup.java:1787)
[        ] E/MessageQueue-JNI( 3225):   at android.view.ViewGroup.dispatchHoverEvent(ViewGroup.java:1478)
[        ] E/MessageQueue-JNI( 3225):   at android.view.View.dispatchGenericMotionEvent(View.java:7209)
[        ] E/MessageQueue-JNI( 3225):   at android.view.ViewGroup.dispatchTransformedGenericPointerEvent(ViewGroup.java:1787)
[        ] E/MessageQueue-JNI( 3225):   at android.view.ViewGroup.dispatchHoverEvent(ViewGroup.java:1478)
[        ] E/MessageQueue-JNI( 3225):   at android.view.View.dispatchGenericMotionEvent(View.java:7209)
[        ] E/MessageQueue-JNI( 3225):   at android.view.ViewGroup.dispatchTransformedGenericPointerEvent(ViewGroup.java:1787)
[        ] E/MessageQueue-JNI( 3225):   at android.view.ViewGroup.dispatchHoverEvent(ViewGroup.java:1478)
[        ] E/MessageQueue-JNI( 3225):   at android.view.View.dispatchGenericMotionEvent(View.java:7209)
[        ] E/MessageQueue-JNI( 3225):   at
com.android.internal.policy.impl.PhoneWindow$DecorView.superDispatchGenericMotionEvent(PhoneWindow.java:1950)
[   +1 ms] E/MessageQueue-JNI( 3225):   at
com.android.internal.policy.impl.PhoneWindow.superDispatchGenericMotionEvent(PhoneWindow.java:1406)
[        ] E/MessageQueue-JNI( 3225):   at android.app.Activity.dispatchGenericMotionEvent(Activity.java:2446)
[        ] E/MessageQueue-JNI( 3225):   at
com.android.internal.policy.impl.PhoneWindow$DecorView.dispatchGenericMotionEvent(PhoneWindow.java:1904)
[        ] E/MessageQueue-JNI( 3225):   at android.view.View.dispatchPointerEvent(View.java:7325)
[        ] E/MessageQueue-JNI( 3225):   at android.view.ViewRootImpl.deliverPointerEvent(ViewRootImpl.java:3350)
[        ] E/MessageQueue-JNI( 3225):   at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:3295)
[        ] E/MessageQueue-JNI( 3225):   at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:4331)
[        ] E/MessageQueue-JNI( 3225):   at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:4310)
[        ] E/MessageQueue-JNI( 3225):   at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:4402)
[        ] E/MessageQueue-JNI( 3225):   at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:171)
[        ] E/MessageQueue-JNI( 3225):   at android.os.MessageQueue.nativePollOnce(Native Method)
[        ] E/MessageQueue-JNI( 3225):   at android.os.MessageQueue.next(MessageQueue.java:125)
[        ] E/MessageQueue-JNI( 3225):   at android.os.Looper.loop(Looper.java:124)
[        ] E/MessageQueue-JNI( 3225):   at android.app.ActivityThread.main(ActivityThread.java:4842)
[        ] E/MessageQueue-JNI( 3225):   at java.lang.reflect.Method.invokeNative(Native Method)
[        ] E/MessageQueue-JNI( 3225):   at java.lang.reflect.Method.invoke(Method.java:511)
[        ] E/MessageQueue-JNI( 3225):   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:890)
[        ] E/MessageQueue-JNI( 3225):   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:657)
[        ] E/MessageQueue-JNI( 3225):   at dalvik.system.NativeStart.main(Native Method)
[        ] W/dalvikvm( 3225): threadid=1: thread exiting with uncaught exception (group=0x427e2438)

After touching the OK in the termination dialog the log is:

[+88378 ms] Service protocol connection closed.
[   +1 ms] Lost connection to device.
[   +3 ms] DevFS: Deleting filesystem on the device
(file:///data/data/games.appsu.minessweeper/cache/mines_sweeperSWJIMS/mines_sweeper/)
[   +1 ms] Sending to VM service: _deleteDevFS({fsName: mines_sweeper})
[ +258 ms] Ignored error while cleaning up DevFS: TimeoutException after 0:00:00.250000: Future not completed
[   +6 ms] "flutter run" took 593,477ms.
[        ] "flutter run" took 593,477ms.
```

flutter analyze results:

```
Analyzing mines_sweeper...                                              
No issues found! (ran in 13.5s)
```

flutter doctor -v:

```
[✓] Flutter (Channel beta, v1.2.1, on Linux, locale en_US.UTF-8)
    • Flutter version 1.2.1 at /home/sarah/flutter
    • Framework revision 8661d8aecd (3 weeks ago), 2019-02-14 19:19:53 -0800
    • Engine revision 3757390fa4
    • Dart version 2.1.2 (build 2.1.2-dev.0.0 0a7dcf17eb)

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /home/sarah/Android/Sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /opt/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)
    • All Android licenses accepted.

[✓] Android Studio (version 3.4)
    • Android Studio at /opt/android-studio
    • Flutter plugin version 33.3.2
    • Dart plugin version 183.5901
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)

[✓] IntelliJ IDEA Community Edition (version 2018.3)
    • IntelliJ at /opt/idea-IC-183.4588.61
    • Flutter plugin version 31.1.4
    • Dart plugin version 183.4588.61

[✓] Connected device (1 available)
    • d07ab5034db7 • d07ab5034db7 • android-arm • Android 4.1.2 (API 16)

• No issues found!
```

**Comment by jason-simmons** [comment]
This should be fixed by https://github.com/flutter/engine/commit/293cfcaa54.  Try upgrading to the Flutter master branch.

**Comment by sarah-fernandez** [comment]
Thanks a lot!
Sarah
