### ISSUE TITLE
Assertion Error package:flutter/src/rendering/box.dart

### ISSUE THREAD

**Issue by jasperamorgan** [flutter/flutter#29047]
## Steps to Reproduce

Flutter error reported during development. Relates to the following commit for this Flutter app:

https://github.com/jasperamorgan/fast_fly_intro/commit/71e893928479a0d1c189e234eb15d43ee2b4c00a

## Logs

```
I/flutter ( 5783): ══╡ EXCEPTION CAUGHT BY RENDERING LIBRARY ╞═════════════════════════════════════════════════════════
I/flutter ( 5783): The following assertion was thrown during performLayout():
I/flutter ( 5783): 'package:flutter/src/rendering/box.dart': Failed assertion: line 307 pos 12: 'width > 0.0': is not
I/flutter ( 5783): true.
I/flutter ( 5783): 
I/flutter ( 5783): Either the assertion indicates an error in the framework itself, or we should provide substantially
I/flutter ( 5783): more information in this error message to help you determine and fix the underlying cause.
I/flutter ( 5783): In either case, please report this assertion by filing a bug on GitHub:
I/flutter ( 5783):   https://github.com/flutter/flutter/issues/new?template=BUG.md
I/flutter ( 5783): 
I/flutter ( 5783): When the exception was thrown, this was the stack:
I/flutter ( 5783): #2      BoxConstraints.constrainSizeAndAttemptToPreserveAspectRatio (package:flutter/src/rendering/box.dart:307:12)
I/flutter ( 5783): #3      RenderFittedBox.performLayout (package:flutter/src/rendering/proxy_box.dart:2288:26)
I/flutter ( 5783): #4      RenderObject.layout (package:flutter/src/rendering/object.dart:1632:7)
I/flutter ( 5783): #5      RenderPadding.performLayout (package:flutter/src/rendering/shifted_box.dart:199:11)
I/flutter ( 5783): #6      RenderObject.layout (package:flutter/src/rendering/object.dart:1632:7)
I/flutter ( 5783): #7      RenderFlex.performLayout (package:flutter/src/rendering/flex.dart:798:17)
I/flutter ( 5783): #8      RenderObject.layout (package:flutter/src/rendering/object.dart:1632:7)
I/flutter ( 5783): #9      RenderPositionedBox.performLayout (package:flutter/src/rendering/shifted_box.dart:385:13)
I/flutter ( 5783): #10     RenderObject.layout (package:flutter/src/rendering/object.dart:1632:7)
I/flutter ( 5783): #11     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter ( 5783): #12     RenderObject.layout (package:flutter/src/rendering/object.dart:1632:7)
I/flutter ( 5783): #13     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter ( 5783): #14     RenderObject.layout (package:flutter/src/rendering/object.dart:1632:7)
I/flutter ( 5783): #15     RenderSliverMultiBoxAdaptor.insertAndLayoutChild (package:flutter/src/rendering/sliver_multi_box_adaptor.dart:410:13)
I/flutter ( 5783): #16     RenderSliverFixedExtentBoxAdaptor.performLayout (package:flutter/src/rendering/sliver_fixed_extent_list.dart:208:17)
I/flutter ( 5783): #17     RenderObject.layout (package:flutter/src/rendering/object.dart:1632:7)
I/flutter ( 5783): #18     RenderViewportBase.layoutChildSequence (package:flutter/src/rendering/viewport.dart:407:13)
I/flutter ( 5783): #19     RenderViewport._attemptLayout (package:flutter/src/rendering/viewport.dart:1322:12)
I/flutter ( 5783): #20     RenderViewport.performLayout (package:flutter/src/rendering/viewport.dart:1240:20)
I/flutter ( 5783): #21     RenderObject._layoutWithoutResize (package:flutter/src/rendering/object.dart:1507:7)
I/flutter ( 5783): #22     PipelineOwner.flushLayout (package:flutter/src/rendering/object.dart:766:18)
I/flutter ( 5783): #23     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding.drawFrame (package:flutter/src/rendering/binding.dart:329:19)
I/flutter ( 5783): #24     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding&WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:701:13)
I/flutter ( 5783): #25     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:268:5)
I/flutter ( 5783): #26     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:988:15)
I/flutter ( 5783): #27     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:928:9)
I/flutter ( 5783): #28     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:840:5)
I/flutter ( 5783): #32     _invoke (dart:ui/hooks.dart:209:10)
I/flutter ( 5783): #33     _drawFrame (dart:ui/hooks.dart:168:3)
I/flutter ( 5783): (elided 5 frames from class _AssertionError and package dart:async)
I/flutter ( 5783): 
I/flutter ( 5783): The following RenderObject was being processed when the exception was fired:
I/flutter ( 5783):   RenderFittedBox#afa33 relayoutBoundary=up3 NEEDS-LAYOUT NEEDS-PAINT
I/flutter ( 5783):   creator: FittedBox ← Container ← SetBudgetAnimation ← Padding ← Expanded ← Column ← Center ← Panel
I/flutter ( 5783):   ← RepaintBoundary-[<1>] ← IndexedSemantics ← NotificationListener<KeepAliveNotification> ←
I/flutter ( 5783):   KeepAlive ← ⋯
I/flutter ( 5783):   parentData: offset=Offset(0.0, 0.0) (can use size)
I/flutter ( 5783):   constraints: BoxConstraints(0.0<=w<=404.0, h=351.1)
I/flutter ( 5783):   size: MISSING
I/flutter ( 5783):   fit: contain
I/flutter ( 5783):   alignment: center
I/flutter ( 5783):   textDirection: ltr
I/flutter ( 5783): This RenderObject had the following descendants (showing up to depth 5):
I/flutter ( 5783):   RenderSemanticsAnnotations#70352 relayoutBoundary=up4 NEEDS-PAINT
I/flutter ( 5783):     RenderImage#0a5b5 relayoutBoundary=up5 NEEDS-PAINT
I/flutter ( 5783): ════════════════════════════════════════════════════════════════════════════════════════════════════
I/flutter ( 5783): Another exception was thrown: RenderBox was not laid out: RenderFittedBox#afa33 relayoutBoundary=up3 NEEDS-PAINT
I/flutter ( 5783): Another exception was thrown: RenderBox was not laid out: RenderPadding#e0d0c relayoutBoundary=up2 NEEDS-PAINT
I/flutter ( 5783): Another exception was thrown: 'package:flutter/src/rendering/shifted_box.dart': Failed assertion: line 314 pos 12: 'child.hasSize': is not true.
I/flutter ( 5783): Another exception was thrown: NoSuchMethodError: The method '<=' was called on null.

```

```
[✓] Flutter (Channel stable, v1.2.1, on Linux, locale en_GB.UTF-8)
    • Flutter version 1.2.1 at /home/jasperamorgan/Development/Tools/flutter
    • Framework revision 8661d8aecd (3 weeks ago), 2019-02-14 19:19:53 -0800
    • Engine revision 3757390fa4
    • Dart version 2.1.2 (build 2.1.2-dev.0.0 0a7dcf17eb)

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /home/jasperamorgan/Android/Sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /opt/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)
    • All Android licenses accepted.

[✓] Android Studio (version 3.3)
    • Android Studio at /opt/android-studio
    • Flutter plugin version 33.0.1
    • Dart plugin version 182.5215
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)

[✓] IntelliJ IDEA Community Edition (version 2018.3)
    • IntelliJ at /opt/idea-IC-183.5912.21
    • Flutter plugin version 33.3.2
    • Dart plugin version 183.5912.23

[!] VS Code (version 1.31.1)
    • VS Code at /usr/share/code
    ✗ Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (3 available)
    • GT I9300                  • 4df140fa2dd05f57 • android-arm   • Android 4.3 (API 18)
    • Nexus 6P                  • CVH7N15A15001841 • android-arm64 • Android 8.1.0 (API 27)
    • Android SDK built for x86 • emulator-5554    • android-x86   • Android 9 (API 28) (emulator)

```

**Comment by HansMuller** [comment]
Thanks for the report!

It would help if you could provide a small self-contained app that demonstrates the problem you've run into.
