### ISSUE TITLE
Unable to load workspace '._Runner.xcworkspace'.

### ISSUE THREAD

**Issue by Tom-De-Backer** [flutter/flutter#29052]
My app works in Android and when I start it in my simulator on a Mac it works.
When I want to validate the app, the **following error** is shown: 

> xcodebuild: error: Unable to load workspace '._Runner.xcworkspace'.
> 	Reason: Unknown.
> 

**Log file:**

`Flutter crash report; please file at https://github.com/flutter/flutter/issues.

## command

flutter build ios

## exception

String: Exit code 74 from: /usr/bin/env xcrun xcodebuild -configuration Release -quiet -workspace ._Runner.xcworkspace -scheme Runner BUILD_DIR=/Users/*/Documents/Flutter/*/build/ios -sdk iphoneos SCRIPT_OUTPUT_STREAM_FILE=/var/folders/p7/kz6k2ys17gv3rh8qpgfrddyr0000gn/T/flutter_build_log_pipe.iybtHz/pipe_to_stdout -showBuildSettings

```
#0      _runWithLoggingSync (package:flutter_tools/src/base/process.dart:353:7)
#1      runCheckedSync (package:flutter_tools/src/base/process.dart:284:10)
#2      buildXcodeProject (package:flutter_tools/src/ios/mac.dart:505:69)
<asynchronous suspension>
#3      BuildIOSCommand.runCommand (package:flutter_tools/src/commands/build_ios.dart:79:43)
<asynchronous suspension>
#4      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:527:18)
#5      _asyncThenWrapperHelper.<anonymous closure> (dart:async/runtime/libasync_patch.dart:77:64)
#6      _rootRunUnary (dart:async/zone.dart:1132:38)
#7      _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#8      _FutureListener.handleValue (dart:async/future_impl.dart:126:18)
#9      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:639:45)
#10     Future._propagateToListeners (dart:async/future_impl.dart:668:32)
#11     Future._complete (dart:async/future_impl.dart:473:7)
#12     _SyncCompleter.complete (dart:async/future_impl.dart:51:12)
#13     _AsyncAwaitCompleter.complete.<anonymous closure> (dart:async/runtime/libasync_patch.dart:33:20)
#14     _rootRun (dart:async/zone.dart:1124:13)
#15     _CustomZone.run (dart:async/zone.dart:1021:19)
#16     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:947:23)
#17     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#18     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#19     _runPendingImmediateCallback (dart:isolate/runtime/libisolate_patch.dart:115:13)
#20     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:172:5)
```

## flutter doctor

```
[32m[✓][39m Flutter (Channel dev, v1.1.6, on Mac OS X 10.13.6 17G4015, locale nl-BE)
    [32m•[39m Flutter version 1.1.6 at /Users/*/Flutter/flutter
    [32m•[39m Framework revision d8b57c2ab2 (9 weeks ago), 2019-01-07 09:42:35 -0800
    [32m•[39m Engine revision 7112b72cc2
    [32m•[39m Dart version 2.1.1 (build 2.1.1-dev.0.1 ec86471ccc)

[31m[✗][39m Android toolchain - develop for Android devices
    [31m✗[39m Unable to locate Android SDK.
      Install Android Studio from:
      https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK
      components.
      (or visit https://flutter.io/setup/#android-setup for detailed
      instructions).
      If Android SDK has been installed to a custom location, set ANDROID_HOME
      to that location.
      You may also want to add it to your PATH environment variable.


[32m[✓][39m iOS toolchain - develop for iOS devices (Xcode 10.1)
    [32m•[39m Xcode at /Applications/Xcode.app/Contents/Developer
    [32m•[39m Xcode 10.1, Build version 10B61
    [32m•[39m ios-deploy 2.0.0
    [32m•[39m CocoaPods version 1.6.1

[33m[!][39m Android Studio (not installed)
    [32m•[39m Android Studio not found; download from
      https://developer.android.com/studio/index.html
      (or visit https://flutter.io/setup/#android-setup for detailed
      instructions).

[33m[!][39m Connected device
    [33m![39m No devices available

[33m![39m Doctor found issues in 3 categories.
```
`

What can I do about it?

**Comment by johannestroeger** [comment]
for me it was just deleting these files: 
- ._Runner.xcworkspace
- ._Runner.xcodeproj

**Comment by jmagman** [comment]
._ added, were you on a non-HFS or APFS volume?
https://www.swiftforensics.com/2018/11/the-dot-underscore-file-format.html
https://apple.stackexchange.com/a/14981

The tool is preferring the first `.xcworkspace` file in the directory, but it's not ignoring hidden files.

**Comment by jmagman** [comment]
Created https://github.com/dart-lang/sdk/issues/40303, it would be nice for `Directory.list()` to help us out instead of doing platform-specific string parsing everywhere.
