### ISSUE TITLE
No implementation found for long io.flutter.embedding.engine.FlutterJNI.nativeAttach

### ISSUE THREAD

**Issue by luoyushouchai** [flutter/flutter#29095]
I add flutter project to my existed app! 
[https://github.com/flutter/flutter/wiki/Add-Flutter-to-existing-apps](url)

```
  @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);

        FlutterEngine flutterEngine = new FlutterEngine(this);
        MethodChannel channel = new MethodChannel(flutterEngine.getDartExecutor(), "TestChannel");

    }
```
Using FlutterEngine getDartExecutor() to create a MethodChannel!

The error comes: 

```
java.lang.UnsatisfiedLinkError: No implementation found for long io.flutter.embedding.engine.FlutterJNI.nativeAttach(io.flutter.embedding.engine.FlutterJNI, boolean) (tried Java_io_flutter_embedding_engine_FlutterJNI_nativeAttach and Java_io_flutter_embedding_engine_FlutterJNI_nativeAttach__Lio_flutter_embedding_engine_FlutterJNI_2Z)
        at io.flutter.embedding.engine.FlutterJNI.nativeAttach(Native Method)
        at io.flutter.embedding.engine.FlutterJNI.attachToNative(FlutterJNI.java:408)
        at io.flutter.embedding.engine.FlutterEngine.attachToJni(FlutterEngine.java:128)
        at io.flutter.embedding.engine.FlutterEngine.<init>(FlutterEngine.java:105)
        at com.example.myapplication.MainActivity.onCreate(MainActivity.java:16)
        at android.app.Activity.performCreate(Activity.java:7149)
        at android.app.Activity.performCreate(Activity.java:7140)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1288)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3017)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3172)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1906)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6863)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:537)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
```

The java file: FlutterJnt
```
 private native long nativeAttach(FlutterJNI var1, boolean var2);
```
Can not found implementation!
Some Help?

**Comment by luoyushouchai** [comment]
Result of flutter doctor:  

Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel master, v1.3.9-pre.41, on Linux, locale en_US.UTF-8)
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[✓] Android Studio (version 3.1)
[!] IntelliJ IDEA Ultimate Edition (version 2018.1)
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
[✓] Connected device (1 available)

! Doctor found issues in 1 category.

**Comment by matthew-carroll** [comment]
@luoyushouchai The `FlutterEngine` class on Android is experimental and should not be used at this time.  Can you point me to the part of the doc that instructs you to use that?  I didn't see it.

**Comment by luoyushouchai** [comment]
@matthew-carroll  For ios, Flutter engine can run without view attached to native view.  I execute flutter upgrade, seeing flutter.jar for android has Flutter.class. I just test it. Thanks!

**Comment by matthew-carroll** [comment]
Ok, so it sounds like this issue was just a misunderstanding about FlutterEngine on Android.  I'm going to close it.  Once FlutterEngine is stable, issues like this should be gone.

**Comment by luoyushouchai** [comment]
@matthew-carroll   
How can i create MethodChannel without FlutterView for now for android platform?

**Comment by matthew-carroll** [comment]
@luoyushouchai it depends a bit on what you are specifically trying to do.  `FlutterView`, itself, is a BinaryMessenger so you should be able to send messages through `FlutterView` and register a channel handles with `FlutterView`.  

https://docs.flutter.io/javadoc/io/flutter/view/FlutterView.html

Another option is that you could define your method channels within your own Flutter plugin and then add that plugin to your pubspec file like any other.

**Comment by luoyushouchai** [comment]
@matthew-carroll  Thanks!

**Comment by luoyushouchai** [comment]
@matthew-carroll I create a new Android project.  Add flutter module as [https://github.com/flutter/flutter/wiki/Add-Flutter-to-existing-apps](url), it works well.

**But** I  create a new **react native** project, and add flutter module to my rn project. The error comes:

```
    Process: com.myrnpro, PID: 16840
    java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/system/framework/org.apache.http.legacy.boot.jar", zip file "/data/app/com.myrnpro-YPiA9BSYDdsLSNAFNi48zA==/base.apk"],nativeLibraryDirectories=[/data/app/com.myrnpro-YPiA9BSYDdsLSNAFNi48zA==/lib/arm64, /data/app/com.myrnpro-YPiA9BSYDdsLSNAFNi48zA==/base.apk!/lib/arm64-v8a, /system/lib64]]] couldn't find "libflutter.so"
        at java.lang.Runtime.loadLibrary0(Runtime.java:1012)
        at java.lang.System.loadLibrary(System.java:1669)
        at io.flutter.view.FlutterMain.startInitialization(FlutterMain.java:159)
        at io.flutter.view.FlutterMain.startInitialization(FlutterMain.java:134)
        at io.flutter.facade.Flutter.createView(Flutter.java:71)
        at com.myrnpro.MainActivity$1.run(MainActivity.java:32)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6863)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:537)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
``` 

MainActivity code is: 
```
public class MainActivity extends ReactFragmentActivity {

    /**
     * Returns the name of the main component registered from JavaScript.
     * This is used to schedule rendering of the component.
     */
    @Override
    protected String getMainComponentName() {
        return "MyRnPro";
    }

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);

        FlutterView flutterView = Flutter.createView(this, getLifecycle(), "1");

        addContentView(flutterView, new FrameLayout.LayoutParams(200, 200));
    }
}
```
Can you give me some help?
