### ISSUE TITLE
Bad State: Stream has already been listened to.

### ISSUE THREAD

**Issue by felipekruhs** [flutter/flutter#29105]
## Steps to Reproduce

1. Edit screen while scrolling

<a href="https://imgur.com/JLMzSxU"><img src="https://i.imgur.com/JLMzSxU.gif" title="source: imgur.com" /></a>

## Full code

```
import 'dart:async';

import 'package:flutter/material.dart';
import 'package:rxdart/rxdart.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'TextField Test',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: HomePage(),
    );
  }
}

class HomePage extends StatefulWidget {
  @override
  createState() => _HomePageState();
}

class _HomePageState extends State<HomePage> {
  TextEditingController _nameController = TextEditingController();
  TextEditingController _emailController = TextEditingController();
  ApplicationBloc _bloc;

  @override
  void initState() {
    super.initState();
    _bloc = new ApplicationBloc();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('TextField Test'),
      ),
      body: ListView(
        shrinkWrap: true,
        children: <Widget>[
          _buildText(),
          _buildText(),
          _buildText(),
          _buildText(),
          _buildText(),
          _buildName(),
          _buildEmail(),
          _buildSubmit()
        ],
      ),
    );
  }

  Widget _buildName() {
    return StreamBuilder(
      stream: _bloc.name,
      builder: (context, snapshot) {
        return TextField(
          controller: _nameController,
          onChanged: _bloc.changeName,
          keyboardType: TextInputType.text,
          decoration: InputDecoration(
            labelText: "Name",
            errorText: snapshot.error,
          ),
        );
      },
    );
  }

  Widget _buildText() {
    return SizedBox(height: 100, child: Text('Text\nbla\nbla\nbla'));
  }

  Widget _buildEmail() {
    return StreamBuilder(
      stream: _bloc.email,
      builder: (context, snapshot) {
        return TextField(
          controller: _emailController,
          onChanged: _bloc.changeEmail,
          keyboardType: TextInputType.emailAddress,
          decoration: InputDecoration(
            labelText: "Email",
            errorText: snapshot.error,
          ),
        );
      },
    );
  }

  Widget _buildSubmit() {
    return StreamBuilder(
      stream: _bloc.submit,
      builder: (context, snapshot) {
        return RaisedButton(
          onPressed: (!snapshot.hasData || !snapshot.data)
              ? null
              : () {
                  _bloc.submitForm();
                  _nameController.text = '';
                  _emailController.text = '';
                },
          child: Text('Submit!'),
        );
      },
    );
  }
}

class ApplicationBloc {
  BehaviorSubject<String> _nameController =
      BehaviorSubject<String>(seedValue: '');
  Observable<String> get name => _nameController.stream.transform(validateName);
  Function(String) get changeName => _nameController.sink.add;

  BehaviorSubject<String> _emailController =
      BehaviorSubject<String>(seedValue: '');
  Observable<String> get email =>
      _emailController.stream.transform(validateEmail);
  Function(String) get changeEmail => _emailController.sink.add;

  Observable<bool> get submit => Observable.combineLatest2(
      name, email, (e, e1) => e.isNotEmpty && e1.isNotEmpty);

  submitForm() {
    //Send to api and wait
    //Reset values
    Future.delayed(const Duration(seconds: 1));
    _nameController.sink.add('');
    _emailController.sink.add('');
  }

  final validateName =
      StreamTransformer<String, String>.fromHandlers(handleData: (name, sink) {
    if (name.isEmpty || name.length > 4) {
      sink.add(name);
    } else if (name.isNotEmpty) {
      sink.addError('Invalid Name!');
    }
  });

  final validateEmail =
      StreamTransformer<String, String>.fromHandlers(handleData: (email, sink) {
    String p =
        r'^(([^<>()[\]\\.,;:\s@\"]+(\.[^<>()[\]\\.,;:\s@\"]+)*)|(\".+\"))@((\[[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\])|(([a-zA-Z\-0-9]+\.)+[a-zA-Z]{2,}))$';

    RegExp regExp = new RegExp(p);
    if (email.isEmpty || (email.length > 4 && regExp.hasMatch(email))) {
      sink.add(email);
    } else {
      sink.addError('Invalid email!');
    }
  });

  //dispose/close all the streams when we call dispose() method
  void dispose() {
    _nameController.close();
    _emailController.close();
  }
}

```

## Logs

```
$ flutter doctor -v
[√] Flutter (Channel stable, v1.2.1, on Microsoft Windows [versÃ£o 10.0.17134.590], locale pt-BR)
    • Flutter version 1.2.1 at D:\programas\flutter
    • Framework revision 8661d8aecd (3 weeks ago), 2019-02-14 19:19:53 -0800
    • Engine revision 3757390fa4
    • Dart version 2.1.2 (build 2.1.2-dev.0.0 0a7dcf17eb)

[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at C:\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = C:\Android\sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)
    • All Android licenses accepted.

[√] Android Studio (version 3.2)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 33.3.1
    • Dart plugin version 182.5215
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)

[√] VS Code (version 1.29.1)
    • VS Code at C:\Users\FelipeK\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 2.24.0

[√] VS Code, 64-bit edition (version 1.31.1)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Flutter extension version 2.24.0

[√] Connected device (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 8.1.0 (API 27) (emulator)

• No issues found!

```

```
I/flutter (17436): ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
I/flutter (17436): The following StateError was thrown building NotificationListener<KeepAliveNotification>:
I/flutter (17436): Bad state: Stream has already been listened to.
I/flutter (17436): 
I/flutter (17436): When the exception was thrown, this was the stack:
I/flutter (17436): #4      Observable.listen 
package:rxdart/…/observables/observable.dart:1729
I/flutter (17436): #5      _StreamBuilderBaseState._subscribe 
package:flutter/…/widgets/async.dart:135
I/flutter (17436): #6      _StreamBuilderBaseState.initState 
package:flutter/…/widgets/async.dart:109
I/flutter (17436): #7      StatefulElement._firstBuild 
package:flutter/…/widgets/framework.dart:3846
I/flutter (17436): #8      ComponentElement.mount 
package:flutter/…/widgets/framework.dart:3711
I/flutter (17436): #9      Element.inflateWidget 
package:flutter/…/widgets/framework.dart:2956
I/flutter (17436): #10     Element.updateChild 
package:flutter/…/widgets/framework.dart:2759
I/flutter (17436): #11     SingleChildRenderObjectElement.mount 
package:flutter/…/widgets/framework.dart:4876
I/flutter (17436): #12     Element.inflateWidget 
package:flutter/…/widgets/framework.dart:2956
I/flutter (17436): #13     Element.updateChild 
package:flutter/…/widgets/framework.dart:2759
I/flutter (17436): #14     SingleChildRenderObjectElement.mount 
package:flutter/…/widgets/framework.dart:4876
I/flutter (17436): #15     Element.inflateWidget 
package:flutter/…/widgets/framework.dart:2956
I/flutter (17436): #16     Element.updateChild 
package:flutter/…/widgets/framework.dart:2759
I/flutter (17436): #17     ComponentElement.performRebuild 
package:flutter/…/widgets/framework.dart:3747
I/flutter (17436): #18     Element.rebuild 
package:flutter/…/widgets/framework.dart:3559
I/flutter (17436): #19     ComponentElement._firstBuild 
package:flutter/…/widgets/framework.dart:3716
I/flutter (17436): #20     ComponentElement.mount 
package:flutter/…/widgets/framework.dart:3711
I/flutter (17436): #21     Element.inflateWidget 
package:flutter/…/widgets/framework.dart:2956
I/flutter (17436): #22     Element.updateChild 
package:flutter/…/widgets/framework.dart:2759
I/flutter (17436): #23     ComponentElement.performRebuild 
package:flutter/…/widgets/framework.dart:3747
I/flutter (17436): #24     Element.rebuild 
package:flutter/…/widgets/framework.dart:3559
I/flutter (17436): #25     ComponentElement._firstBuild 
package:flutter/…/widgets/framework.dart:3716
I/flutter (17436): #26     ComponentElement.mount 
package:flutter/…/widgets/framework.dart:3711
I/flutter (17436): #27     ParentDataElement.mount 
package:flutter/…/widgets/framework.dart:4063
I/flutter (17436): #28     Element.inflateWidget 
package:flutter/…/widgets/framework.dart:2956
I/flutter (17436): #29     Element.updateChild 
package:flutter/…/widgets/framework.dart:2759
I/flutter (17436): #30     ComponentElement.performRebuild 
package:flutter/…/widgets/framework.dart:3747
I/flutter (17436): #31     Element.rebuild 
package:flutter/…/widgets/framework.dart:3559
I/flutter (17436): #32     ComponentElement._firstBuild 
package:flutter/…/widgets/framework.dart:3716
I/flutter (17436): #33     StatefulElement._firstBuild 
package:flutter/…/widgets/framework.dart:3864
I/flutter (17436): #34     ComponentElement.mount 
package:flutter/…/widgets/framework.dart:3711
I/flutter (17436): #35     Element.inflateWidget 
package:flutter/…/widgets/framework.dart:2956
I/flutter (17436): #36     Element.updateChild 
package:flutter/…/widgets/framework.dart:2759
I/flutter (17436): #37     SliverMultiBoxAdaptorElement.updateChild 
package:flutter/…/widgets/sliver.dart:1030
I/flutter (17436): #38     SliverMultiBoxAdaptorElement.createChild.<anonymous closure> 
package:flutter/…/widgets/sliver.dart:1015
I/flutter (17436): #39     BuildOwner.buildScope 
package:flutter/…/widgets/framework.dart:2253
I/flutter (17436): #40     SliverMultiBoxAdaptorElement.createChild 
package:flutter/…/widgets/sliver.dart:1008
I/flutter (17436): #41     RenderSliverMultiBoxAdaptor._createOrObtainChild.<anonymous closure> 
package:flutter/…/rendering/sliver_multi_box_adaptor.dart:274
I/flutter (17436): #42     RenderObject.invokeLayoutCallback.<anonymous closure> 
package:flutter/…/rendering/object.dart:1728
I/flutter (17436): #43     PipelineOwner._enableMutationsToDirtySubtrees 
package:flutter/…/rendering/object.dart:797
I/flutter (17436): #44     RenderObject.invokeLayoutCallback 
package:flutter/…/rendering/object.dart:1728
I/flutter (17436): #45     RenderSliverMultiBoxAdaptor._createOrObtainChild 
package:flutter/…/rendering/sliver_multi_box_adaptor.dart:263
I/flutter (17436): #46     RenderSliverMultiBoxAdaptor.insertAndLayoutChild 
package:flutter/…/rendering/sliver_multi_box_adaptor.dart:407
I/flutter (17436): #47     RenderSliverList.performLayout.advance 
package:flutter/…/rendering/sliver_list.dart:190
I/flutter (17436): #48     RenderSliverList.performLayout 
package:flutter/…/rendering/sliver_list.dart:233
I/flutter (17436): #49     RenderObject.layout 
package:flutter/…/rendering/object.dart:1632
I/flutter (17436): #50     RenderSliverPadding.performLayout 
package:flutter/…/rendering/sliver_padding.dart:182
I/flutter (17436): #51     RenderObject.layout 
package:flutter/…/rendering/object.dart:1632
I/flutter (17436): #52     RenderViewportBase.layoutChildSequence 
package:flutter/…/rendering/viewport.dart:407
I/flutter (17436): #53     RenderShrinkWrappingViewport._attemptLayout 
package:flutter/…/rendering/viewport.dart:1651
I/flutter (17436): #54     RenderShrinkWrappingViewport.performLayout 
package:flutter/…/rendering/viewport.dart:1614
I/flutter (17436): #55     RenderObject.layout 
package:flutter/…/rendering/object.dart:1632
I/flutter (17436): #56     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout 
package:flutter/…/rendering/proxy_box.dart:105
I/flutter (17436): #57     RenderObject.layout 
package:flutter/…/rendering/object.dart:1632
I/flutter (17436): #58     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout 
package:flutter/…/rendering/proxy_box.dart:105
I/flutter (17436): #59     RenderObject.layout 
package:flutter/…/rendering/object.dart:1632
I/flutter (17436): #60     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout 
package:flutter/…/rendering/proxy_box.dart:105
I/flutter (17436): #61     RenderObject.layout 
package:flutter/…/rendering/object.dart:1632
I/flutter (17436): #62     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout 
package:flutter/…/rendering/proxy_box.dart:105
I/flutter (17436): #63     RenderObject.layout 
package:flutter/…/rendering/object.dart:1632
I/flutter (17436): #64     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout 
package:flutter/…/rendering/proxy_box.dart:105
I/flutter (17436): #65     RenderObject.layout 
package:flutter/…/rendering/object.dart:1632
I/flutter (17436): #66     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout 
package:flutter/…/rendering/proxy_box.dart:105
I/flutter (17436): #67     RenderObject.layout 
package:flutter/…/rendering/object.dart:1632
I/flutter (17436): #68     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout 
package:flutter/…/rendering/proxy_box.dart:105
I/flutter (17436): #69     RenderObject.layout 
package:flutter/…/rendering/object.dart:1632
I/flutter (17436): #70     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout 
package:flutter/…/rendering/proxy_box.dart:105
I/flutter (17436): #71     RenderObject.layout 
package:flutter/…/rendering/object.dart:1632
I/flutter (17436): #72     MultiChildLayoutDelegate.layoutChild 
package:flutter/…/rendering/custom_layout.dart:142
I/flutter (17436): #73     _ScaffoldLayout.performLayout 
package:flutter/…/material/scaffold.dart:350
I/flutter (17436): #74     MultiChildLayoutDelegate._callPerformLayout 
package:flutter/…/rendering/custom_layout.dart:212
I/flutter (17436): #75     RenderCustomMultiChildLayoutBox.performLayout 
package:flutter/…/rendering/custom_layout.dart:356
I/flutter (17436): #76     RenderObject._layoutWithoutResize 
package:flutter/…/rendering/object.dart:1507
I/flutter (17436): #77     PipelineOwner.flushLayout 
package:flutter/…/rendering/object.dart:766
I/flutter (17436): #78     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding.drawFrame 
package:flutter/…/rendering/binding.dart:329
I/flutter (17436): #79     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding&WidgetsBinding.drawFrame 
package:flutter/…/widgets/binding.dart:701
I/flutter (17436): #80     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding._handlePersistentFrameCallback 
package:flutter/…/rendering/binding.dart:268
I/flutter (17436): #81     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._invokeFrameCallback 
package:flutter/…/scheduler/binding.dart:988
I/flutter (17436): #82     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.handleDrawFrame 
package:flutter/…/scheduler/binding.dart:928
I/flutter (17436): #83     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._handleDrawFrame 
package:flutter/…/scheduler/binding.dart:840
I/flutter (17436): #87     _invoke (dart:ui/hooks.dart:209:10)
I/flutter (17436): #88     _drawFrame (dart:ui/hooks.dart:168:3)
I/flutter (17436): (elided 7 frames from package dart:async)
I/flutter (17436): ════════════════════════════════════════════════════════════════════════════════════════════════════
```

```
I/flutter (17436): Another exception was thrown: 'package:flutter/src/rendering/sliver_multi_box_adaptor.dart': Failed assertion: line 235 pos 16: 'indexOf(child) > index': is not true.
I/flutter (17436): Another exception was thrown: 'package:flutter/src/rendering/sliver_multi_box_adaptor.dart': Failed assertion: line 235 pos 16: 'indexOf(child) > index': is not true.
I/flutter (17436): Another exception was thrown: 'package:flutter/src/widgets/framework.dart': Failed assertion: line 2257 pos 20: '_debugCurrentBuildTarget == context': is not true.
I/flutter (17436): Another exception was thrown: 'package:flutter/src/rendering/sliver_multi_box_adaptor.dart': Failed assertion: line 467 pos 12: 'child.hasSize': is not true.
I/flutter (17436): Another exception was thrown: 'package:flutter/src/widgets/sliver.dart': Failed assertion: line 1055 pos 14: '_childElements.containsKey(index)': is not true.
I/flutter (17436): Another exception was thrown: 'package:flutter/src/rendering/sliver_multi_box_adaptor.dart': Failed assertion: line 467 pos 12: 'child.hasSize': is not true.
I/flutter (17436): Another exception was thrown: 'package:flutter/src/widgets/sliver.dart': Failed assertion: line 1055 pos 14: '_childElements.containsKey(index)': is not true.
I/flutter (17436): Another exception was thrown: 'package:flutter/src/rendering/sliver_multi_box_adaptor.dart': Failed assertion: line 467 pos 12: 'child.hasSize': is not true.
I/flutter (17436): Another exception was thrown: 'package:flutter/src/widgets/sliver.dart': Failed assertion: line 1055 pos 14: '_childElements.containsKey(index)': is not true.
I/flutter (17436): Another exception was thrown: 'package:flutter/src/rendering/sliver_multi_box_adaptor.dart': Failed assertion: line 467 pos 12: 'child.hasSize': is not true.
I/flutter (17436): Another exception was thrown: 'package:flutter/src/widgets/sliver.dart': Failed assertion: line 1055 pos 14: '_childElements.containsKey(index)': is not true.
I/flutter (17436): Another exception was thrown: 'package:flutter/src/rendering/sliver_multi_box_adaptor.dart': Failed assertion: line 467 pos 12: 'child.hasSize': is not true.
I/flutter (17436): Another exception was thrown: 'package:flutter/src/widgets/sliver.dart': Failed assertion: line 1055 pos 14: '_childElements.containsKey(index)': is not true.
I/flutter (17436): Another exception was thrown: 'package:flutter/src/rendering/sliver_multi_box_adaptor.dart': Failed assertion: line 467 pos 12: 'child.hasSize': is not true.
I/flutter (17436): Another exception was thrown: 'package:flutter/src/widgets/sliver.dart': Failed assertion: line 1055 pos 14: '_childElements.containsKey(index)': is not true.
I/flutter (17436): Another exception was thrown: 'package:flutter/src/rendering/sliver_multi_box_adaptor.dart': Failed assertion: line 467 pos 12: 'child.hasSize': is not true.
I/flutter (17436): Another exception was thrown: 'package:flutter/src/widgets/sliver.dart': Failed assertion: line 1055 pos 14: '_childElements.containsKey(index)': is not true.
I/flutter (17436): Another exception was thrown: 'package:flutter/src/rendering/sliver_multi_box_adaptor.dart': Failed assertion: line 467 pos 12: 'child.hasSize': is not true.
```

```
```

```
```

**Comment by jonahwilliams** [comment]
I have no idea what the bloc code is doing, but it seems likely that you are creating single subcription streams. These will almost always break in a real UI, because widgets that are off screen might be offloaded, et cetera.

All of the rx classes you are using should be able to expose broadcast versions which will fix this issue.

**Comment by dnfield** [comment]
You should be able to just add `.asBroadcastStream`

**Comment by felipekruhs** [comment]
That´s worked!

Thank you.

**Comment by dnfield** [comment]
https://stackoverflow.com/questions/51396769/flutter-bad-state-stream-has-already-been-listened-to

**Comment by kilegalloway** [comment]
The most common form of Stream can be listened only once at a time. If you try to add multiple listeners, it will throw

Bad state: Stream has already been listened to

To prevent this error, expose a broadcast Stream. You can convert your stream to a broadcast using myStream.asBroadcastStream

This needs to be done inside your class that expose Stream. Not as parameter of StreamBuilder. Since asBroadcastStream internally listen to the original stream to generate the broadcast one, this imply you can’t call this method twice on the same stream.

Full Source Code At [Here](https://icetutor.com/question/flutter-bad-state-stream-has-already-been-listened-to/)

**Comment by 9745108736** [comment]
This is a problem for the provider, I solved it by change provider initialization

Eg

`locator.registerSingleton<LoginProvider>(LoginProvider());
`

TO

`locator.registerFactory(() => TaskProvider());
`

Where locator is

`GetIt locator = GetIt.instance;
`
