### ISSUE TITLE
[Bloc] focus on textfield keyboard appears and immediately disappears

### ISSUE THREAD

**Issue by orazz** [flutter/flutter#29122]
## Steps to Reproduce
Focusing to textfield keyboard appears and immediately disappears, i tried to use focusnode didn't help GlobalKey also. I think problem in tabview when I'm using tabview I get this problem 

main.dart

```
import 'package:flutter/material.dart';
import 'package:bloc/bloc.dart';
import 'package:flutter_getir/widgets/root_page.dart';

class SimpleBlocDelegate extends BlocDelegate {
  @override
  void onTransition(Transition transition) {
    print(transition);
  }
}

void main() {
  assert(() {
    BlocSupervisor().delegate = SimpleBlocDelegate();
    return true;
  }());

  runApp(Root());
}
```

root.dart

```
import 'package:flutter/material.dart';
import 'package:flutter_getir/widgets/home_page.dart';
import 'package:flutter_getir/widgets/search_page.dart';
import 'package:flutter_getir/common/utils/colors.dart';
import 'package:flutter/cupertino.dart';
import 'package:flutter_bloc/flutter_bloc.dart';
import 'package:flutter_getir/bloc/authentication/authentication.dart';

class Root extends StatefulWidget {
  @override
  _RootState createState() => _RootState();
}

class _RootState extends State<Root> {

  AuthenticationBloc _authenticationBloc;

  @override
  void initState() {
    _authenticationBloc = AuthenticationBloc();
    _authenticationBloc.dispatch(AppStarted());
    super.initState();
  }

  @override
  void dispose() {
    _authenticationBloc.dispose();
    super.dispose();
  }

  List<BottomNavigationBarItem> _buildNavigationItems() {
    return [
      BottomNavigationBarItem(
        icon: Icon(Icons.category),
      ),
      BottomNavigationBarItem(
        icon: Icon(Icons.search),
      ),
    ];
  }

  _buildScreen(int index) {
    switch (index) {
      case 0:
        return HomePage();
      case 1:
        return SearchPage();
    }
  }

  @override
  Widget build(BuildContext context) {
    return
      BlocProvider<AuthenticationBloc>(
          bloc: _authenticationBloc,
    child: CupertinoApp(
          localizationsDelegates: const <LocalizationsDelegate<dynamic>>[
            DefaultMaterialLocalizations.delegate,
            DefaultWidgetsLocalizations.delegate,
          ],
          home: CupertinoTheme(
            data: CupertinoThemeData(
                brightness: Brightness.light,
                barBackgroundColor: AppColors.MAIN,
                textTheme: CupertinoTextThemeData(navActionTextStyle: TextStyle(inherit:false, color: Colors.white), navTitleTextStyle: TextStyle(inherit: false, color: Colors.white, fontSize: 20.0))
            ),
            child: CupertinoTabScaffold(
              tabBar: CupertinoTabBar(
                backgroundColor: Colors.white,
                  activeColor: AppColors.MAIN, items: _buildNavigationItems()),
              tabBuilder: (context, index) {
                return CupertinoTabView(builder: (context) {
                  return _buildScreen(index);
                });
              },
            ),
          ),
        )
    );
  }
}
```

search_page.dart

```
class SearchPage extends StatefulWidget {

  SearchPage({Key key}) : super(key: key);

  @override
  _SearchPageState createState() => _SearchPageState();
}

class _SearchPageState extends State<SearchPage> {

  final GlobalKey<FormState> _scaffoldKey = GlobalKey<FormState>();

  final SearchBloc _searchBloc = SearchBloc();

  final myController = TextEditingController();

  _SearchPageState() {
    _searchBloc.dispatch(FetchSearch());
  }

  @override
  void initState() {
    super.initState();
  }

  @override
  Widget build(BuildContext context) {
    return
        _buildInput();
  }

  Widget _buildInput() {
    return new Padding(
      padding: new EdgeInsets.all(50.0),
      child: Card(
        child: new TextFormField(
          key: _scaffoldKey,
            decoration: new InputDecoration(labelText: 'E-Mail'),
          ),
      ),
    );
  }

  @override
  void dispose() {
    _searchBloc.dispose();
    super.dispose();
  }
}

```

## Logs

```
17:05:15.962 41 info flutter.tools  Transition { currentState: SearchUninitialized, event: FetchSearch, nextState: SearchLoaded { products: 12, hasReachedMax: false } }
17:05:15.985 42 info flutter.tools [VERBOSE-2:ui_dart_state.cc(148)] Unhandled Exception: Bad state: Cannot add new events after calling close
17:05:15.987 43 info flutter.tools #0      _BroadcastStreamController.add (dart:async/broadcast_stream_controller.dart:249:24)
17:05:15.988 44 info flutter.tools #1      Subject._add (package:rxdart/src/subjects/subject.dart:124:16)
17:05:15.988 45 info flutter.tools #2      Subject.add (package:rxdart/src/subjects/subject.dart:118:5)
17:05:15.988 46 info flutter.tools #3      Bloc._bindStateSubject.<anonymous closure> (package:bloc/src/bloc.dart:90:23)
17:05:15.988 47 info flutter.tools #4      Stream.forEach.<anonymous closure>.<anonymous closure> (dart:async/stream.dart:814:45)
17:05:15.989 48 info flutter.tools #5      _runUserCode (dart:async/stream_pipe.dart:11:23)
17:05:15.989 49 info flutter.tools #6      Stream.forEach.<anonymous closure> (dart:async/stream.dart:814:11)
17:05:15.989 50 info flutter.tools #7      _rootRunUnary (dart:async/zone.dart:1132:38)
17:05:15.989 51 info flutter.tools #8      _CustomZone.runUnary (dart:async/zone.dart:1029:19)
17:05:15.989 52 info flutter.tools #9      _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
17:05:15.989 53 info flutter.tools #10     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
17:05:15.989 54 info flutter.tools #11     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
17:05:15.989 55 info flutter.tools #12     _SyncStreamCon<…>
17:05:16.448 56 info flutter.tools  Transition { currentState: SearchUninitialized, event: FetchSearch, nextState: SearchLoaded { products: 12, hasReachedMax: false } }

```

```
```

```
[✓] Flutter (Channel dev, v1.3.8, on Mac OS X 10.14.1 18B75, locale en-TM)
    • Flutter version 1.3.8 at /Users/atakishiyev/Documents/tools/flutter
    • Framework revision e5b1ed7a7f (4 days ago), 2019-03-06 14:23:37 -0800
    • Engine revision f4951df193
    • Dart version 2.2.1 (build 2.2.1-dev.0.0 571ea80e11)

[!] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/atakishiyev/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses

[✓] iOS toolchain - develop for iOS devices (Xcode 10.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.1, Build version 10B61
    • ios-deploy 2.0.0
    • CocoaPods version 1.6.0

[✓] Android Studio (version 3.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 33.1.1
    • Dart plugin version 182.5215
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)

[!] IntelliJ IDEA Community Edition (version 2018.1.5)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.io/intellij-setup/#installing-the-plugins

[✓] VS Code (version 1.31.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 2.24.0

[✓] Connected device (2 available)
    • iPad      • a0d9d2c09ca87a0df1d1d9b212061f8e9d307061 • ios • iOS 9.3.5
    • iPhone XR • 10220D68-1CB8-4AB7-8EB0-0FE9EFDAB791     • ios • iOS 12.1 (simulator)

! Doctor found issues in 2 categories.

```

**Comment by orazz** [comment]
![ddd](https://user-images.githubusercontent.com/8214953/54084834-9c990300-4357-11e9-84e7-b98d73309ab7.gif)

**Comment by dnfield** [comment]
Is this the same as https://github.com/flutter/flutter/issues/28457?

Can you try the master channel and see if it works now?

**Comment by orazz** [comment]
> Is this the same as #28457?
> 
> Can you try the master channel and see if it works now?

some changes and it works fine.

```
class SearchPage extends StatefulWidget {
  @override
  _SearchPageState createState() => _SearchPageState();
}

class _SearchPageState extends State<SearchPage> {
  final SearchBloc _searchBloc = SearchBloc();

  final myController = TextEditingController();
  static final _inputKey = new GlobalKey<FormState>();

  _SearchPageState() {
    _searchBloc.dispatch(FetchSearch());
  }

  @override
  Widget build(BuildContext context) {
    return CupertinoPageScaffold(
      navigationBar: CupertinoNavigationBar(
        middle: Text("Getir"),
      ),
      child: Column(
        children: [
          _buildInput(),
          
        ],
      ),
    );
  }

  Widget _buildInput() {
    return CupertinoTextField(
      padding: EdgeInsets.all(10),
      key: _inputKey,
      placeholder: 'Type to search',
      controller: myController,
      //clearButtonMode: OverlayVisibilityMode.editing,
      //onSubmitted: _onSubmitted,
    );
  }

  @override
  void dispose() {
    myController.dispose();
    _searchBloc.dispose();
    super.dispose();
  }
}
```
