### ISSUE TITLE
error formatting objective-c files by pub global run flutter_plugin_tools format

### ISSUE THREAD

**Issue by ivk1800** [flutter/flutter#29124]
## Steps to Reproduce

1. fork plugins repo
2. run command pub global activate flutter_plugin_tools && pub global run flutter_plugin_tools format
3. error

## Logs
```
Formatting all .dart files...

Unchanged /Users/ivan/plugins_fork/packages/android_alarm_manager/example/lib/main.dart
Unchanged /Users/ivan/plugins_fork/packages/webview_flutter/lib/webview_flutter.dart
Formatting all .java files...
Formatting all .m and .h files...
Unhandled exception:
ProcessException: No such file or directory
  Command: clang-format -i --style=Google /Users/ivan/plugins_fork/packages/android_alarm_manager/example/ios/Runner/AppDelegate.h 
....
/Users/ivan/plugins_fork/packages/webview_flutter/ios/Classes/FlutterWebView.m
#0      runAndStream (package:flutter_plugin_tools/src/common.dart:193:7)
<asynchronous suspension>
#1      FormatCommand._formatObjectiveC (package:flutter_plugin_tools/src/format_command.dart:82:11)
<asynchronous suspension>
#2      FormatCommand.run (package:flutter_plugin_tools/src/format_command.dart:41:11)
<asynchronous suspension>
#3      CommandRunner.runCommand (package:args/command_runner.dart:196:27)
<asynchronous suspension>
#4      CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:111:29)
#5      new Future.sync (dart:async/future.dart:224:31)
#6      CommandRunner.run (package:args/command_runner.dart:111:11)
#7      main (package:flutter_plugin_tools/src/main.dart:41:17)
#8      _startIsolate.<anonymous closure> (dart:isolate/runtime/libisolate_patch.dart:298:32)
#9      _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:171:12)
```

##  flutter doctor -v
```
[✓] Flutter (Channel master, v1.2.3-pre.29, on Mac OS X 10.13.6 17G65, locale ru-RU)
    • Flutter version 1.2.3-pre.29 at /Users/Ivan/flutter
    • Framework revision 57a8b03c5e (2 weeks ago), 2019-02-24 11:53:43 +0100
    • Engine revision 90fcaff900
    • Dart version 2.2.0 (build 2.2.0-dev.2.1 c92d5ca288)

[!] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/ivan/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = /Users/ivan/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses

[!] iOS toolchain - develop for iOS devices (Xcode 10.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.1, Build version 10B61
    ✗ Verify that all connected devices have been paired with this computer in Xcode.
      If all devices have been paired, libimobiledevice and ideviceinstaller may require updating.
      To update with Brew, run:
        brew update
        brew uninstall --ignore-dependencies libimobiledevice
        brew uninstall --ignore-dependencies usbmuxd
        brew install --HEAD usbmuxd
        brew unlink usbmuxd
        brew link usbmuxd
        brew install --HEAD libimobiledevice
        brew install ideviceinstaller
    • ios-deploy 1.9.4
    • CocoaPods version 1.6.1

[!] Android Studio (version 3.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)

[✓] IntelliJ IDEA Community Edition (version 2018.3.4)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 33.2.2
    • Dart plugin version 183.5901

[✓] Connected device (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 9 (API 28) (emulator)

! Doctor found issues in 3 categories.
```

**Comment by dnfield** [comment]
You need to have `clang-format` available on your path to run this tool.

You could try `brew install clang-format`.

**Comment by PiN73** [comment]
[video_player/CONTRIBUTING.md](https://github.com/flutter/plugins/blob/2007446e834e7e0013aa571e61af6693c487d300/packages/video_player/video_player/CONTRIBUTING.md) (https://github.com/flutter/plugins/pull/3281) stays that we should use `clang-format-7`:
```
./script/incremental_build.sh format --travis --clang-format=clang-format-7
```

But running this causes exception for me:
```
Unhandled exception:
ProcessException: No such file or directory
  Command: clang-format-7 -i --style=Google <...>
```

<details>
<summary>Logs / reproduction</summary>

```
pavel@Pavel ~ % cd tmp
pavel@Pavel tmp % git clone https://github.com/flutter/plugins.git      
Cloning into 'plugins'...
remote: Enumerating objects: 7, done.
remote: Counting objects: 100% (7/7), done.
remote: Compressing objects: 100% (2/2), done.
remote: Total 49187 (delta 5), reused 5 (delta 5), pack-reused 49180
Receiving objects: 100% (49187/49187), 19.28 MiB | 2.87 MiB/s, done.
Resolving deltas: 100% (28605/28605), done.
pavel@Pavel tmp % cd plugins 
pavel@Pavel plugins % git fetch
pavel@Pavel plugins % git checkout -b hello
Switched to a new branch 'hello'
pavel@Pavel plugins % touch packages/video_player/video_player/hello.txt
pavel@Pavel plugins % git add .
pavel@Pavel plugins % git commit -m "hello"
[hello 4a75080e] hello
 1 file changed, 0 insertions(+), 0 deletions(-)
 create mode 100644 packages/video_player/video_player/hello.txt
pavel@Pavel plugins % ./script/incremental_build.sh format --travis --clang-format=clang-format-7
Checking for changed packages from a0fe2225e2550d4a1a4214c7582dad90feff5d3b
Detected changes in the following 1 package(s):
video_player

running format --travis --clang-format=clang-format-7
script/tool/lib/src/main.dart: Warning: Interpreting this as package URI, 'package:flutter_plugin_tools/src/main.dart'.
Downloading Google Java Format...
Formatting all .dart files...
Running command: "flutter format /Users/pavel/tmp/plugins/packages/video_player/video_player/test/video_player_test.dart /Users/pavel/tmp/plugins/packages/video_player/video_player/test/sub_rip_file_test.dart /Users/pavel/tmp/plugins/packages/video_player/video_player/test/video_player_initialization_test.dart /Users/pavel/tmp/plugins/packages/video_player/video_player/test/closed_caption_file_test.dart /Users/pavel/tmp/plugins/packages/video_player/video_player/example/test_driver/video_player.dart /Users/pavel/tmp/plugins/packages/video_player/video_player/example/test_driver/video_player_test.dart /Users/pavel/tmp/plugins/packages/video_player/video_player/example/test_driver/integration_test.dart /Users/pavel/tmp/plugins/packages/video_player/video_player/example/integration_test/video_player_test.dart /Users/pavel/tmp/plugins/packages/video_player/video_player/example/lib/main.dart /Users/pavel/tmp/plugins/packages/video_player/video_player/pigeons/messages.dart /Users/pavel/tmp/plugins/packages/video_player/video_player/lib/video_player.dart /Users/pavel/tmp/plugins/packages/video_player/video_player/lib/src/sub_rip.dart /Users/pavel/tmp/plugins/packages/video_player/video_player/lib/src/closed_caption_file.dart /Users/pavel/tmp/plugins/packages/video_player/video_player_platform_interface/test/method_channel_video_player_test.dart /Users/pavel/tmp/plugins/packages/video_player/video_player_platform_interface/lib/video_player_platform_interface.dart /Users/pavel/tmp/plugins/packages/video_player/video_player_platform_interface/lib/messages.dart /Users/pavel/tmp/plugins/packages/video_player/video_player_platform_interface/lib/method_channel_video_player.dart /Users/pavel/tmp/plugins/packages/video_player/video_player_platform_interface/lib/test.dart /Users/pavel/tmp/plugins/packages/video_player/video_player_web/test/video_player_web_test.dart /Users/pavel/tmp/plugins/packages/video_player/video_player_web/lib/video_player_web.dart /Users/pavel/tmp/plugins/packages/video_player/video_player_web/lib/src/shims/dart_ui.dart /Users/pavel/tmp/plugins/packages/video_player/video_player_web/lib/src/shims/dart_ui_fake.dart /Users/pavel/tmp/plugins/packages/video_player/video_player_web/lib/src/shims/dart_ui_real.dart" in /Users/pavel/tmp/plugins/packages
Unchanged /Users/pavel/tmp/plugins/packages/video_player/video_player/test/video_player_test.dart
Unchanged /Users/pavel/tmp/plugins/packages/video_player/video_player/test/sub_rip_file_test.dart
Unchanged /Users/pavel/tmp/plugins/packages/video_player/video_player/test/video_player_initialization_test.dart
Unchanged /Users/pavel/tmp/plugins/packages/video_player/video_player/test/closed_caption_file_test.dart
Unchanged /Users/pavel/tmp/plugins/packages/video_player/video_player/example/test_driver/video_player.dart
Unchanged /Users/pavel/tmp/plugins/packages/video_player/video_player/example/test_driver/video_player_test.dart
Unchanged /Users/pavel/tmp/plugins/packages/video_player/video_player/example/test_driver/integration_test.dart
Unchanged /Users/pavel/tmp/plugins/packages/video_player/video_player/example/integration_test/video_player_test.dart
Unchanged /Users/pavel/tmp/plugins/packages/video_player/video_player/example/lib/main.dart
Unchanged /Users/pavel/tmp/plugins/packages/video_player/video_player/pigeons/messages.dart
Unchanged /Users/pavel/tmp/plugins/packages/video_player/video_player/lib/video_player.dart
Unchanged /Users/pavel/tmp/plugins/packages/video_player/video_player/lib/src/sub_rip.dart
Unchanged /Users/pavel/tmp/plugins/packages/video_player/video_player/lib/src/closed_caption_file.dart
Unchanged /Users/pavel/tmp/plugins/packages/video_player/video_player_platform_interface/test/method_channel_video_player_test.dart
Unchanged /Users/pavel/tmp/plugins/packages/video_player/video_player_platform_interface/lib/video_player_platform_interface.dart
Unchanged /Users/pavel/tmp/plugins/packages/video_player/video_player_platform_interface/lib/messages.dart
Unchanged /Users/pavel/tmp/plugins/packages/video_player/video_player_platform_interface/lib/method_channel_video_player.dart
Unchanged /Users/pavel/tmp/plugins/packages/video_player/video_player_platform_interface/lib/test.dart
Unchanged /Users/pavel/tmp/plugins/packages/video_player/video_player_web/test/video_player_web_test.dart
Unchanged /Users/pavel/tmp/plugins/packages/video_player/video_player_web/lib/video_player_web.dart
Unchanged /Users/pavel/tmp/plugins/packages/video_player/video_player_web/lib/src/shims/dart_ui.dart
Unchanged /Users/pavel/tmp/plugins/packages/video_player/video_player_web/lib/src/shims/dart_ui_fake.dart
Unchanged /Users/pavel/tmp/plugins/packages/video_player/video_player_web/lib/src/shims/dart_ui_real.dart
Formatting all .java files...
Running command: "java -jar /Users/pavel/tmp/plugins/script/tool/lib/src/google-java-format-1.3-all-deps.jar --replace /Users/pavel/tmp/plugins/packages/video_player/video_player/example/android/app/src/test/java/io/flutter/plugins/videoplayerexample/FlutterActivityTest.java /Users/pavel/tmp/plugins/packages/video_player/video_player/example/android/app/src/main/java/io/flutter/plugins/videoplayerexample/EmbeddingV1Activity.java /Users/pavel/tmp/plugins/packages/video_player/video_player/android/src/main/java/io/flutter/plugins/videoplayer/VideoPlayerPlugin.java /Users/pavel/tmp/plugins/packages/video_player/video_player/android/src/main/java/io/flutter/plugins/videoplayer/CustomSSLSocketFactory.java /Users/pavel/tmp/plugins/packages/video_player/video_player/android/src/main/java/io/flutter/plugins/videoplayer/VideoPlayerOptions.java /Users/pavel/tmp/plugins/packages/video_player/video_player/android/src/main/java/io/flutter/plugins/videoplayer/Messages.java /Users/pavel/tmp/plugins/packages/video_player/video_player/android/src/main/java/io/flutter/plugins/videoplayer/QueuingEventSink.java /Users/pavel/tmp/plugins/packages/video_player/video_player/android/src/main/java/io/flutter/plugins/videoplayer/VideoPlayer.java" in /Users/pavel/tmp/plugins/packages
Formatting all .cc, .cpp, .mm, .m, and .h files...
Running command: "clang-format-7 -i --style=Google /Users/pavel/tmp/plugins/packages/video_player/video_player/example/ios/Runner/AppDelegate.h /Users/pavel/tmp/plugins/packages/video_player/video_player/ios/Classes/messages.h /Users/pavel/tmp/plugins/packages/video_player/video_player/ios/Classes/FLTVideoPlayerPlugin.h /Users/pavel/tmp/plugins/packages/video_player/video_player/example/ios/Runner/main.m /Users/pavel/tmp/plugins/packages/video_player/video_player/example/ios/Runner/AppDelegate.m /Users/pavel/tmp/plugins/packages/video_player/video_player/ios/Classes/FLTVideoPlayerPlugin.m /Users/pavel/tmp/plugins/packages/video_player/video_player/ios/Classes/messages.m" in /Users/pavel/tmp/plugins/packages
Unhandled exception:
ProcessException: No such file or directory
  Command: clang-format-7 -i --style=Google /Users/pavel/tmp/plugins/packages/video_player/video_player/example/ios/Runner/AppDelegate.h /Users/pavel/tmp/plugins/packages/video_player/video_player/ios/Classes/messages.h /Users/pavel/tmp/plugins/packages/video_player/video_player/ios/Classes/FLTVideoPlayerPlugin.h /Users/pavel/tmp/plugins/packages/video_player/video_player/example/ios/Runner/main.m /Users/pavel/tmp/plugins/packages/video_player/video_player/example/ios/Runner/AppDelegate.m /Users/pavel/tmp/plugins/packages/video_player/video_player/ios/Classes/FLTVideoPlayerPlugin.m /Users/pavel/tmp/plugins/packages/video_player/video_player/ios/Classes/messages.m
#0      _ProcessImpl._start (dart:io-patch/process_patch.dart:390:33)
#1      Process.start (dart:io-patch/process_patch.dart:36:20)
#2      ProcessRunner.runAndStream (package:flutter_plugin_tools/src/common.dart:392:49)
#3      FormatCommand._formatCppAndObjectiveC (package:flutter_plugin_tools/src/format_command.dart:98:27)
<asynchronous suspension>
#4      FormatCommand.run (package:flutter_plugin_tools/src/format_command.dart:47:5)
<asynchronous suspension>
#5      CommandRunner.runCommand (package:args/command_runner.dart:197:13)
<asynchronous suspension>
#6      main.<anonymous closure> (package:flutter_plugin_tools/src/main.dart)
<asynchronous suspension>
pavel@Pavel plugins %                                                                            
```
</details>

It seems that brew only intalls `clang-format` but not `clang-format-7`

<details>

```
pavel@Pavel ~ % brew install clang-format
Warning: clang-format 11.1.0 is already installed and up-to-date.
To reinstall 11.1.0, run:
  brew reinstall clang-format
pavel@Pavel ~ % clang-format-7     
zsh: command not found: clang-format-7
pavel@Pavel ~ % where clang-format-7     
clang-format-7 not found
pavel@Pavel ~ % where clang-format  
/usr/local/bin/clang-format
pavel@Pavel ~ % brew install clang-format-7
==> Searching for similarly named formulae...
Error: No similarly named formulae found.
Error: No available formula or cask with the name "clang-format-7".
==> Searching for a previously deleted formula (in the last month)...
Error: No previously deleted formula found.
==> Searching taps on GitHub...
Error: No formulae found in taps.
pavel@Pavel ~ % 
```
</details>

So the questions are:
- Should we use `clang-format-7` or `clang-format` is OK?
- May we add some message saying to install `clang-format` if it's missing? The current message `ProcessException: No such file or directory` makes think that some plugin's source files are missing

**Comment by stuartmorgan** [comment]
This is now addressed in both the docs and the error message.
