### ISSUE TITLE
Doing gestures while hot reloading app with NestedScrollView throws an exception.

### ISSUE THREAD

**Issue by mauricedoepke** [flutter/flutter#29157]
## Steps to Reproduce

Swiping with the finger on the screen while simultaneously hot reloading this code:
https://gist.github.com/mauricedoepke/f185e8762f39658f78f18d4e854b49c1

produces the error below. If you take the finger off the screen after hot reloading is done and do some gestures again everything works as expected.

## Logs
```
E/flutter (21598): [ERROR:flutter/lib/ui/ui_dart_state.cc(148)] Unhandled Exception: 'package:flutter/src/gestures/converter.dart': Failed assertion: line 230 pos 18: '_pointers.containsKey(datum.device)': is not true.
E/flutter (21598): #0      _AssertionError._doThrowNew (dart:core/runtime/liberrors_patch.dart:40:39)
E/flutter (21598): #1      _AssertionError._throwNew (dart:core/runtime/liberrors_patch.dart:36:5)
E/flutter (21598): #2      PointerEventConverter.expand (package:flutter/src/gestures/converter.dart:230:18)
E/flutter (21598): #3      _SyncIterator.moveNext (dart:core/runtime/libcore_patch.dart:152:12)
E/flutter (21598): #4      ListQueue.addAll (dart:collection/queue.dart:715:25)
E/flutter (21598): #5      _WidgetsFlutterBinding&BindingBase&GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:83:27)
E/flutter (21598): #6      _rootRunUnary (dart:async/zone.dart:1136:13)
E/flutter (21598): #7      _CustomZone.runUnary (dart:async/zone.dart:1029:19)
E/flutter (21598): #8      _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
E/flutter (21598): #9      _invoke1 (dart:ui/hooks.dart:223:10)
E/flutter (21598): #10     _dispatchPointerDataPacket (dart:ui/hooks.dart:144:5)
```

```
Analyzing flutter_app...
No issues found! (ran in 2.6s)
```

```
[√] Flutter (Channel stable, v1.2.1, on Microsoft Windows [Version 10.0.17134.590], locale en-US)
[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[√] Android Studio (version 3.3)
[√] VS Code (version 1.31.1)
[√] Connected device (1 available)
```

**Comment by iapicca** [comment]
Hi @mauricedoepke 
I tested a similar code with the latest master and the issue doesn't seem to occur

```dart
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) => MaterialApp(
    theme: ThemeData(primarySwatch: Colors.green, textTheme: TextTheme()),
    home: HomePage(),
  );
}

class HomePage extends StatefulWidget {
  @override
  _HomePageState createState() => _HomePageState();
}

class _HomePageState extends State<HomePage> {
  PageController _pageController;

  @override
  void initState() { 
    super.initState();
    _pageController = PageController()
      ..addListener(() => print(_pageController.position),);
  }

  @override
  void dispose() {
    _pageController?.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) => Scaffold(
    body: NestedScrollView(
      headerSliverBuilder: (BuildContext context, bool innerBoxIsScrolled) => 
      <Widget>[
        SliverAppBar(
        title: Text('title'),
        pinned: false,
        floating: true,
        forceElevated: innerBoxIsScrolled,
        ),
      ],
      body: Column(
        children: <Widget>[
          SizedBox(height: 100),
          Expanded(
            child: PageView(
              controller: _pageController,
              children: <Widget>[
                SingleChildScrollView(
                  child: Container(
                    color: Colors.red,
                    height: MediaQuery.of(context).size.height*2,
                    width:  MediaQuery.of(context).size.width,
                  ),
                ),
                SingleChildScrollView(
                  child: Container(
                    color: Colors.blue,
                    height: MediaQuery.of(context).size.height*2,
                    width:  MediaQuery.of(context).size.width,
                  ),
                ),
              ],
            ),
          ),
        ],
      ),
    ),
  );
}
```

I'm closing this issue as solved if you disagree please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact descriptions what happens, logs and the output of 'flutter doctor -v'  please.
All system setups can be slightly different so it's always better to open new issues and reference related issues.
