### ISSUE TITLE
Changing pubspec.yaml and triggering a hot reload crashes application

### ISSUE THREAD

**Issue by jonahwilliams** [flutter/flutter#29186]
It's not clear if this was ever intended to be supported. Currently we either hang on a hot reload or crash. This can be reproduced on master by running the flutter gallery, then adding a new dependency to pubspec.yaml and triggering a hot reload.

Dependencies can be removed from the pubspec, or added with a hot restart.

Its not clear how this could be supported with a build_runner workflow.

```
Performing hot reload...                                                
Reloaded 0 of 578 libraries in 662ms.

Performing hot reload...                                               ⣻ (This is taking an unexpectedly long time.)[VERBOSE-2:shell.cc(178)] Dart Error: Unhandled exception:
'dart:isolate/runtime/lib/timer_impl.dart': Failed assertion: line 433: '<optimized out>': is not true.
#0      _AssertionError._doThrowNew (dart:core/runtime/lib/errors_patch.dart:40:39)
#1      _AssertionError._throwNew (dart:core/runtime/lib/errors_patch.dart:36:5)
#2      _Timer._cancelWakeup (dart:isolate/runtime/lib/timer_impl.dart:433:12)
#3      _Timer._notifyEventHandler (dart:isolate/runtime/lib/timer_impl.dart:299:7)
#4      _Timer._handleMessage (dart:isolate/runtime/lib/timer_impl.dart:419:5)
#5      _RawReceivePortImpl._handleMessage (dart:isolate/runtime/lib/isolate_patch.dart:171:12)
       ⣾ (This is taking an unexpectedly long time.)Application finished.
jonahwilliams-macbookpro2:flutter_gallery jonahwilliams$ flutter clean
```

**Comment by jonahwilliams** [comment]
This only happens once the application is a non-trivial size. On hello_world I am able to add and remove libraries easily. On flutter gallery this almost always crashes.

**Comment by jonahwilliams** [comment]
A clue on the gallery: we might be generating a _huge_ kernel file. When adding a `rxdart: any` to the pubspec yaml and triggering a hot reload we claim to be syncing 34.7MB of data.

```
[ +303 ms] Warning: updated dependencies detected. Flutter will require a restart to be use them.
[  +13 ms] Syncing files to device iPhone XS Max...
[        ] Scanning asset files
[  +12 ms] Compiling dart to kernel with 0 updated files
[   +9 ms] Updating files
[+1196 ms] DevFS: Sync finished
[        ] Syncing files to device iPhone XS Max... (completed in 1,219ms)
[        ] Synced 34.7MB.
[        ] Sending to VM service
```
