### ISSUE TITLE
Determine whether it is possible to update asset manifest during hot reload

### ISSUE THREAD

**Issue by jonahwilliams** [flutter/flutter#29184]
Currently we require adding and removing assets to be done in a hot restart, while only existing assets can be updated in a hot reload. It's not clear if this is a limitation in how assets are handled or a bug/oversight in hot reload.

**Comment by jonahwilliams** [comment]
Example:

Removing asset and triggering a hot reload causes a failure. This is because we never evict files from _entires in the devfs.

```

Unable to get status of file "/Users/jonahwilliams/Documents/flutter/examples/hello_world/assets/bar.png": file not found.
Performing hot reload...       
```

Adding a text or image file which is defined in the same package works

**Comment by jonahwilliams** [comment]
Example:

Commenting out an asset from a package in flutter gallery triggers a crash:

```
Performing hot reload...                                               ⡿ (This is taking an unexpectedly long time.)[VERBOSE-2:shell.cc(178)] Dart Error: Unhandled exception:
'dart:isolate/runtime/lib/timer_impl.dart': Failed assertion: line 433: '<optimized out>': is not true.
#0      _AssertionError._doThrowNew (dart:core/runtime/lib/errors_patch.dart:40:39)
#1      _AssertionError._throwNew (dart:core/runtime/lib/errors_patch.dart:36:5)
#2      _Timer._cancelWakeup (dart:isolate/runtime/lib/timer_impl.dart:433:12)
#3      _Timer._notifyEventHandler (dart:isolate/runtime/lib/timer_impl.dart:299:7)
#4      _Timer._handleMessage (dart:isolate/runtime/lib/timer_impl.dart:419:5)
#5      _RawReceivePortImpl._handleMessage (dart:isolate/runtime/lib/isolate_patch.dart:171:12)
       ⣷ (This is taking an unexpectedly long time.)
```

**Comment by jonahwilliams** [comment]
Example:

Adding that asset back in a separate run command also triggers a crash:

```
Performing hot reload...                                                
Reloaded 0 of 578 libraries in 718ms.

Performing hot reload...                                               ⣽ (This is taking an unexpectedly long time.)[VERBOSE-2:shell.cc(178)] Dart Error: Unhandled exception:
'dart:isolate/runtime/lib/timer_impl.dart': Failed assertion: line 433: '<optimized out>': is not true.
#0      _AssertionError._doThrowNew (dart:core/runtime/lib/errors_patch.dart:40:39)
#1      _AssertionError._throwNew (dart:core/runtime/lib/errors_patch.dart:36:5)
#2      _Timer._cancelWakeup (dart:isolate/runtime/lib/timer_impl.dart:433:12)
#3      _Timer._notifyEventHandler (dart:isolate/runtime/lib/timer_impl.dart:299:7)
#4      _Timer._handleMessage (dart:isolate/runtime/lib/timer_impl.dart:419:5)
#5      _RawReceivePortImpl._handleMessage (dart:isolate/runtime/lib/isolate_patch.dart:171:12)
       ⣟ (This is taking an unexpectedly long time.)
```

**Comment by jonahwilliams** [comment]
On a trivial application like hello_world, this does indeed work though...

**Comment by SSolheim2000** [comment]
Was a solution found for this?

I eventually was able to resolve by wiping the data on my virtual device.

Close virtual device.
In Andriod Studio, click Tools, AVD Manager.
On the right side of your selected device, click the drop down arrow and "Wipe Data".
Confirm you want to wipe all personal data.
Click on the play button to restart device.
