### ISSUE TITLE
invoke virtual method 'isAccessibilityEnabled()' on a null object reference

### ISSUE THREAD

**Issue by eoinfogarty** [flutter/flutter#29203]
## Steps to Reproduce

1. Using branch `Channel dev, v1.3.9` with a Samsung s7 (SM G950F)
2. Application will start and crash straight away with the below exception
3. Seems to be since this pr https://github.com/flutter/engine/pull/8061 the error has started to occur

I have only been able to test across a small range of devices and galaxy s7 is the only one where this error occured

## Logs

```
13:31:06.591 70 info flutter.tools E/AndroidRuntime(27245): FATAL EXCEPTION: main
13:31:06.591 71 info flutter.tools E/AndroidRuntime(27245): Process: jp.co.example.app, PID: 27245
13:31:06.591 72 info flutter.tools E/AndroidRuntime(27245): java.lang.NullPointerException: Attempt to invoke virtual method 'boolean io.flutter.view.AccessibilityBridge.isAccessibilityEnabled()' on a null object reference
13:31:06.591 73 info flutter.tools E/AndroidRuntime(27245): 	at io.flutter.view.FlutterView.getAccessibilityNodeProvider(FlutterView.java:887)
13:31:06.591 74 info flutter.tools E/AndroidRuntime(27245): 	at android.view.View.createAccessibilityNodeInfoInternal(View.java:7907)
13:31:06.591 75 info flutter.tools E/AndroidRuntime(27245): 	at android.view.View.createAccessibilityNodeInfo(View.java:7897)
13:31:06.591 76 info flutter.tools E/AndroidRuntime(27245): 	at android.view.accessibility.AccessibilityRecord.setSource(AccessibilityRecord.java:146)
13:31:06.591 77 info flutter.tools E/AndroidRuntime(27245): 	at android.view.accessibility.AccessibilityRecord.setSource(AccessibilityRecord.java:119)
13:31:06.591 78 info flutter.tools E/AndroidRuntime(27245): 	at android.view.View.onInitializeAccessibilityEventInternal(View.java:7849)
13:31:06.591 79 info flutter.tools E/AndroidRuntime(27245): 	at android.view.View.onInitializeAccessibilityEvent(View.java:7837)
13:31:06.591 80 info flutter.tools E/AndroidRuntime(27245): 	at android.view.View.sendAccessibilityEventUncheckedInternal(View.java:7699)
13:31:06.591 81 info flutter.tools E/AndroidRuntime(27245): 	at android.view.View.sendAccessibilityEventUnchecked(View.java:7684)
13:31:06.591 82 info flutter.tools E/AndroidRuntime(27245): 	at android.view.View.sendAccessibilityEventInternal(View.java:7661)
13:31:06.591 83 info flutter.tools E/AndroidRuntime(27245): 	at android.view.View.sendAccessibilityEvent(View.java:7628)
13:31:06.591 84 info flutter.tools E/AndroidRuntime(27245): 	at android.view.View.onFocusChanged(View.java:7542)
13:31:06.591 85 info flutter.tools E/AndroidRuntime(27245): 	at android.view.View.handleFocusGainInternal(View.java:7239)
13:31:06.591 86 info flutter.tools E/AndroidRuntime(27245): 	at android.view.View.requestFocusNoSearch(View.java:11514)
13:31:06.591 87 info flutter.tools E/AndroidRuntime(27245): 	at android.view.View.requestFocus(View.java:11493)
13:31:06.591 88 info flutter.tools E/AndroidRuntime(27245): 	at android.view.ViewGroup.onRequestFocusInDescendants(ViewGroup.java:3405)
13:31:06.591 89 info flutter.tools E/AndroidRuntime(27245): 	at android.view.ViewGroup.requestFocus(ViewGroup.java:3361)
13:31:06.591 90 info flutter.tools E/AndroidRuntime(27245): 	at android.view.ViewGroup.onRequestFocusInDescendants(ViewGroup.java:3405)
13:31:06.591 91 info flutter.tools E/AndroidRuntime(27245): 	at android.view.ViewGroup.requestFocus(ViewGroup.java:3361)
13:31:06.591 92 info flutter.tools E/AndroidRuntime(27245): 	at android.view.ViewGroup.onRequestFocusInDescendants(ViewGroup.java:3405)
13:31:06.591 93 info flutter.tools E/AndroidRuntime(27245): 	at android.view.ViewGroup.requestFocus(ViewGroup.java:3364)
13:31:06.591 94 info flutter.tools E/AndroidRuntime(27245): 	at android.view.View.requestFocus(View.java:11460)
13:31:06.591 95 info flutter.tools E/AndroidRuntime(27245): 	at android.view.View.requestFocus(View.java:11402)
13:31:06.591 96 info flutter.tools E/AndroidRuntime(27245): 	at android.view.ViewRootImpl.focusableViewAvailable(ViewRootImpl.java:4010)
13:31:06.591 97 info flutter.tools E/AndroidRuntime(27245): 	at android.view.View.setFlags(View.java:14424)
13:31:06.591 98 info flutter.tools E/AndroidRuntime(27245): 	at android.view.View.setVisibility(View.java:10024)
13:31:06.591 99 info flutter.tools E/AndroidRuntime(27245): 	at android.app.Activity.makeVisible(Activity.java:5504)
13:31:06.591 100 info flutter.tools E/AndroidRuntime(27245): 	at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3933)
13:31:06.591 101 info flutter.tools E/AndroidRuntime(27245): 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3036)
13:31:06.591 102 info flutter.tools E/AndroidRuntime(27245): 	at android.app.ActivityThread.-wrap11(Unknown Source:0)
13:31:06.591 103 info flutter.tools E/AndroidRuntime(27245): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1696)
13:31:06.591 104 info flutter.tools E/AndroidRuntime(27245): 	at android.os.Handler.dispatchMessage(Handler.java:105)
13:31:06.591 105 info flutter.tools E/AndroidRuntime(27245): 	at android.os.Looper.loop(Looper.java:164)
13:31:06.591 106 info flutter.tools E/AndroidRuntime(27245): 	at android.app.ActivityThread.main(ActivityThread.java:6938)
13:31:06.592 107 info flutter.tools E/AndroidRuntime(27245): 	at java.lang.reflect.Method.invoke(Native Method)
13:31:06.592 108 info flutter.tools E/AndroidRuntime(27245): 	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
13:31:06.592 109 info flutter.tools E/AndroidRuntime(27245): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)

```

`flutter doctor -v`

```
[✓] Flutter (Channel dev, v1.3.9, on Mac OS X 10.14 18A391, locale en-JP)
    • Flutter version 1.3.9 at /Users/a14000/Projects/Flutter/flutter
    • Framework revision f91df4abe1 (2 days ago), 2019-03-09 21:19:28 -0500
    • Engine revision 4e54bc93ca
    • Dart version 2.2.1 (build 2.2.1-dev.1.0 2fb6cd9f5f)

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/a14000/Library/Android/sdk
    • Android NDK at /Users/a14000/Library/Android/sdk/ndk-bundle
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio 2.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.1, Build version 10B61
    • ios-deploy 1.9.4
    • CocoaPods version 1.6.1

[✓] Android Studio (version 3.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 29.0.2
    • Dart plugin version 181.5540.11
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)

[✓] Android Studio (version 3.3)
    • Android Studio at /Applications/Android Studio 2.app/Contents
    • Flutter plugin version 33.0.1
    • Dart plugin version 182.5215
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)

[✓] Android Studio (version 3.1)
    • Android Studio at /Applications/Android Studio 3.app/Contents
    • Flutter plugin version 29.0.2
    • Dart plugin version 181.5540.11
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)

[✓] Connected device (1 available)
    • SM G950F • 9889d535585945365a • android-arm64 • Android 8.0.0 (API 26)

```

**Comment by jonahwilliams** [comment]
cc @matthew-carroll

**Comment by matthew-carroll** [comment]
@jonahwilliams I just put up a PR fix and tagged you for review.

**Comment by ZE0TRON** [comment]
Having the same issue

**Comment by matthew-carroll** [comment]
@eoinfogarty thanks for reporting the bug.

A fix has been merged in here:
https://github.com/flutter/engine/pull/8126

Build 1.3.9 has been marked bad here:
https://github.com/flutter/flutter/wiki/Bad-Builds

The fix should be picked up in the next engine roll to master, and then the next roll from master to dev.
