### ISSUE TITLE
textDirection != null': is not true

### ISSUE THREAD

**Issue by JakieTang** [flutter/flutter#29218]
Hi,My program canot be runned ， i thought this is a bug.

import 'package:flutter/material.dart';

void main() => runApp(CustomScrollViewTestRoute());

class CustomScrollViewTestRoute extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
   
    return Material(
      child: CustomScrollView(
        slivers: <Widget>[
          //AppBar，包含一个导航栏
          SliverAppBar(
            pinned: true,
            expandedHeight: 250.0,
            flexibleSpace: FlexibleSpaceBar(
              title: const Text('Demo'),
              background: Image.asset(
                "./images/avatar.png", fit: BoxFit.cover,),
            ),
          ),

          SliverPadding(
            padding: const EdgeInsets.all(8.0),
            sliver: new SliverGrid( //Grid
              gridDelegate: new SliverGridDelegateWithFixedCrossAxisCount(
                crossAxisCount: 2, //Grid按两列显示
                mainAxisSpacing: 10.0,
                crossAxisSpacing: 10.0,
                childAspectRatio: 4.0,
              ),
              delegate: new SliverChildBuilderDelegate(
                    (BuildContext context, int index) {
                  //创建子widget
                  return new Container(
                    alignment: Alignment.center,
                    color: Colors.cyan[100 * (index % 9)],
                    child: new Text('grid item $index'),
                  );
                },
                childCount: 20,
              ),
            ),
          ),
          //List
          new SliverFixedExtentList(
            itemExtent: 50.0,
            delegate: new SliverChildBuilderDelegate(
                    (BuildContext context, int index) {
                  //创建列表项
                  return new Container(
                    alignment: Alignment.center,
                    color: Colors.lightBlue[100 * (index % 9)],
                    child: new Text('list item $index'),
                  );
                },
                childCount: 50 //
            ),
          ),
        ],
      ),
    );
  }
}

***************************************Logs**************************************
Launching lib/CustomScrollViewWidget.dart on HMA AL00 in debug mode...
Initializing gradle...
Resolving dependencies...
Running Gradle task 'assembleDebug'...
Built build/app/outputs/apk/debug/app-debug.apk.
Installing build/app/outputs/apk/app.apk...
I/flutter (24307): ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
I/flutter (24307): The following assertion was thrown building
I/flutter (24307): RawGestureDetector-[LabeledGlobalKey<RawGestureDetectorState>#fc3c9](state:
I/flutter (24307): RawGestureDetectorState#e2c33(gestures: <none>, behavior: opaque)):
I/flutter (24307): 'package:flutter/src/painting/basic_types.dart': Failed assertion: line 222 pos 10: 'textDirection
I/flutter (24307): != null': is not true.
I/flutter (24307): 
I/flutter (24307): Either the assertion indicates an error in the framework itself, or we should provide substantially
I/flutter (24307): more information in this error message to help you determine and fix the underlying cause.
I/flutter (24307): In either case, please report this assertion by filing a bug on GitHub:
I/flutter (24307):   https://github.com/flutter/flutter/issues/new?template=BUG.md
I/flutter (24307): 
I/flutter (24307): When the exception was thrown, this was the stack:
I/flutter (24307): #2      textDirectionToAxisDirection (package:flutter/src/painting/basic_types.dart:222:10)
I/flutter (24307): #3      Viewport.getDefaultCrossAxisDirection (package:flutter/src/widgets/viewport.dart:128:16)
I/flutter (24307): #4      Viewport.createRenderObject (package:flutter/src/widgets/viewport.dart:139:58)
I/flutter (24307): #5      RenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4503:28)
I/flutter (24307): #6      MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4983:11)
I/flutter (24307): #7      _ViewportElement.mount (package:flutter/src/widgets/viewport.dart:186:11)
I/flutter (24307): #8      Element.inflateWidget (package:flutter/src/widgets/framework.dart:2960:14)
I/flutter (24307): #9      Element.updateChild (package:flutter/src/widgets/framework.dart:2763:12)
I/flutter (24307): #10     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4881:14)
I/flutter (24307): #11     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2960:14)
I/flutter (24307): #12     Element.updateChild (package:flutter/src/widgets/framework.dart:2763:12)
I/flutter (24307): #13     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4881:14)
I/flutter (24307): #14     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2960:14)
I/flutter (24307): #15     Element.updateChild (package:flutter/src/widgets/framework.dart:2763:12)
I/flutter (24307): #16     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4881:14)
I/flutter (24307): #17     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2960:14)
I/flutter (24307): #18     Element.updateChild (package:flutter/src/widgets/framework.dart:2763:12)
I/flutter (24307): #19     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4881:14)
I/flutter (24307): #20     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2960:14)
I/flutter (24307): #21     Element.updateChild (package:flutter/src/widgets/framework.dart:2763:12)
I/flutter (24307): #22     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3752:16)
I/flutter (24307): #23     Element.rebuild (package:flutter/src/widgets/framework.dart:3564:5)
I/flutter (24307): #24     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3721:5)
I/flutter (24307): #25     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3869:11)
I/flutter (24307): #26     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3716:5)
I/flutter (24307): #27     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2960:14)
I/flutter (24307): #28     Element.updateChild (package:flutter/src/widgets/framework.dart:2763:12)
I/flutter (24307): #29     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3752:16)
I/flutter (24307): #30     Element.rebuild (package:flutter/src/widgets/framework.dart:3564:5)
I/flutter (24307): #31     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3721:5)
I/flutter (24307): #32     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3716:5)
I/flutter (24307): #33     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2960:14)
I/flutter (24307): #34     Element.updateChild (package:flutter/src/widgets/framework.dart:2763:12)
I/flutter (24307): #35     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4881:14)
I/flutter (24307): #36     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2960:14)
I/flutter (24307): #37     Element.updateChild (package:flutter/src/widgets/framework.dart:2763:12)
I/flutter (24307): #38     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4881:14)
I/flutter (24307): #39     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2960:14)
I/flutter (24307): #40     Element.updateChild (package:flutter/src/widgets/framework.dart:2763:12)
I/flutter (24307): #41     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4881:14)
I/flutter (24307): #42     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2960:14)
I/flutter (24307): #43     Element.updateChild (package:flutter/src/widgets/framework.dart:2763:12)
I/flutter (24307): #44     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4881:14)
I/flutter (24307): #45     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2960:14)
I/flutter (24307): #46     Element.updateChild (package:flutter/src/widgets/framework.dart:2763:12)
I/flutter (24307): #47     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3752:16)
I/flutter (24307): #48     Element.rebuild (package:flutter/src/widgets/framework.dart:3564:5)
I/flutter (24307): #49     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3721:5)
I/flutter (24307): #50     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3716:5)
I/flutter (24307): #51     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2960:14)
I/flutter (24307): #52     Element.updateChild (package:flutter/src/widgets/framework.dart:2763:12)
I/flutter (24307): #53     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3752:16)
I/flutter (24307): #54     Element.rebuild (package:flutter/src/widgets/framework.dart:3564:5)
I/flutter (24307): #55     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3721:5)
I/flutter (24307): #56     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3869:11)
I/flutter (24307): #57     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3716:5)
I/flutter (24307): #58     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2960:14)
I/flutter (24307): #59     Element.updateChild (package:flutter/src/widgets/framework.dart:2763:12)
I/flutter (24307): #60     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3752:16)
I/flutter (24307): #61     Element.rebuild (package:flutter/src/widgets/framework.dart:3564:5)
I/flutter (24307): #62     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3721:5)
I/flutter (24307): #63     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3869:11)
I/flutter (24307): #64     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3716:5)
I/flutter (24307): #65     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2960:14)
I/flutter (24307): #66     Element.updateChild (package:flutter/src/widgets/framework.dart:2763:12)
I/flutter (24307): #67     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3752:16)
I/flutter (24307): #68     Element.rebuild (package:flutter/src/widgets/framework.dart:3564:5)
I/flutter (24307): #69     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3721:5)
I/flutter (24307): #70     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3716:5)
I/flutter (24307): #71     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2960:14)
I/flutter (24307): #72     Element.updateChild (package:flutter/src/widgets/framework.dart:2763:12)
I/flutter (24307): #73     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3752:16)
I/flutter (24307): #74     Element.rebuild (package:flutter/src/widgets/framework.dart:3564:5)
I/flutter (24307): #75     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3721:5)
I/flutter (24307): #76     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3716:5)
I/flutter (24307): #77     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2960:14)
I/flutter (24307): #78     Element.updateChild (package:flutter/src/widgets/framework.dart:2763:12)
I/flutter (24307): #79     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3752:16)
I/flutter (24307): #80     Element.rebuild (package:flutter/src/widgets/framework.dart:3564:5)
I/flutter (24307): #81     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3721:5)
I/flutter (24307): #82     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3869:11)
I/flutter (24307): #83     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3716:5)
I/flutter (24307): #84     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2960:14)
I/flutter (24307): #85     Element.updateChild (package:flutter/src/widgets/framework.dart:2763:12)
I/flutter (24307): #86     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4881:14)
I/flutter (24307): #87     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2960:14)
I/flutter (24307): #88     Element.updateChild (package:flutter/src/widgets/framework.dart:2763:12)
I/flutter (24307): #89     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3752:16)
I/flutter (24307): #90     Element.rebuild (package:flutter/src/widgets/framework.dart:3564:5)
I/flutter (24307): #91     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3721:5)
I/flutter (24307): #92     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3716:5)
I/flutter (24307): #93     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2960:14)
I/flutter (24307): #94     Element.updateChild (package:flutter/src/widgets/framework.dart:2763:12)
I/flutter (24307): #95     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4881:14)
I/flutter (24307): #96     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2960:14)
I/flutter (24307): #97     Element.updateChild (package:flutter/src/widgets/framework.dart:2763:12)
I/flutter (24307): #98     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3752:16)
I/flutter (24307): #99     Element.rebuild (package:flutter/src/widgets/framework.dart:3564:5)
I/flutter (24307): #100    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3721:5)
I/flutter (24307): #101    StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3869:11)
I/flutter (24307): #102    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3716:5)
I/flutter (24307): #103    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2960:14)
I/flutter (24307): #104    Element.updateChild (package:flutter/src/widgets/framework.dart:2763:12)
I/flutter (24307): #105    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3752:16)
I/flutter (24307): #106    Element.rebuild (package:flutter/src/widgets/framework.dart:3564:5)
I/flutter (24307): #107    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3721:5)
I/flutter (24307): #108    StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3869:11)
I/flutter (24307): #109    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3716:5)
I/flutter (24307): #110    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2960:14)
I/flutter (24307): #111    Element.updateChild (package:flutter/src/widgets/framework.dart:2763:12)
I/flutter (24307): #112    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3752:16)
I/flutter (24307): #113    Element.rebuild (package:flutter/src/widgets/framework.dart:3564:5)
I/flutter (24307): #114    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3721:5)
I/flutter (24307): #115    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3716:5)
I/flutter (24307): #116    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2960:14)
I/flutter (24307): #117    Element.updateChild (package:flutter/src/widgets/framework.dart:2763:12)
I/flutter (24307): #118    RenderObjectToWidgetElement._rebuild (package:flutter/src/widgets/binding.dart:933:16)
I/flutter (24307): #119    RenderObjectToWidgetElement.mount (package:flutter/src/widgets/binding.dart:904:5)
I/flutter (24307): #120    RenderObjectToWidgetAdapter.attachToRenderTree.<anonymous closure> (package:flutter/src/widgets/binding.dart:850:17)
I/flutter (24307): #121    BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2257:19)
I/flutter (24307): #122    RenderObjectToWidgetAdapter.attachToRenderTree (package:flutter/src/widgets/binding.dart:849:13)
I/flutter (24307): #123    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding&WidgetsBinding.attachRootWidget (package:flutter/src/widgets/binding.dart:736:7)
I/flutter (24307): #124    runApp (package:flutter/src/widgets/binding.dart:780:7)
I/flutter (24307): #125    main (package:first_demo/CustomScrollViewWidget.dart:3:16)
I/flutter (24307): #126    _runMainZoned.<anonymous closure>.<anonymous closure> (dart:ui/hooks.dart:196:25)
I/flutter (24307): #131    _runMainZoned.<anonymous closure> (dart:ui/hooks.dart:187:5)
I/flutter (24307): #132    _startIsolate.<anonymous closure> (dart:isolate/runtime/lib/isolate_patch.dart:300:19)
I/flutter (24307): #133    _RawReceivePortImpl._handleMessage (dart:isolate/runtime/lib/isolate_patch.dart:171:12)
I/flutter (24307): (elided 6 frames from class _AssertionError and package dart:async)
I/flutter (24307): ════════════════════════════════════════════════════════════════════════════════════════════════════
D/OpenGLRenderer(24307):   HWUI Binary is  enabled

**Comment by Kartik1607** [comment]
TextDirection is provided  by a *MaterialApp* or a *CupertinoApp*. You need to wrap your widget with a MaterialApp widget.

**Comment by tvolkert** [comment]
Ideally, we'd provide a more meaningful structured error message in this case, since this is a fairly common mistake.

**Comment by TahaTesser** [comment]
<details> 
<summary>flutter doctor -v</summary> 

```
[✓] Flutter (Channel dev, 1.20.0-7.1.pre, on Mac OS X 10.15.6 19G73, locale
    en-GB)
    • Flutter version 1.20.0-7.1.pre at /Users/taha/Code/flutter_dev
    • Framework revision 7736f3bc90 (6 days ago), 2020-07-10 16:33:05 -0700
    • Engine revision d48085141c
    • Dart version 2.9.0 (build 2.9.0-21.2.beta)

 
[✓] Android toolchain - develop for Android devices (Android SDK version
    30.0.0)
    • Android SDK at /Users/taha/Code/sdk
    • Platform android-30, build-tools 30.0.0
    • ANDROID_HOME = /Users/taha/Code/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.6)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.6, Build version 11E708
    • CocoaPods version 1.9.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google
      Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 47.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.47.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.12.2

[✓] Connected device (5 available)
    • SM M305F (mobile)      • 32003c30dc19668f          • android-arm64  •
      Android 10 (API 29)
    • Taha’s iPhone (mobile) • 00008020-001059882212002E • ios            •
      iOS 13.6
    • macOS (desktop)        • macos                     • darwin-x64     •
      Mac OS X 10.15.6 19G73
    • Web Server (web)       • web-server                • web-javascript •
      Flutter Tools
    • Chrome (web)           • chrome                    • web-javascript •
      Google Chrome 83.0.4103.116

• No issues found!
```

</details>
