### ISSUE TITLE
Timer.periodic returns a Timer, but its callback not executed

### ISSUE THREAD

**Issue by GregoryConrad** [flutter/flutter#29254]
Here's the output to the console (which repeats every second, which was my set Duration):

```
E/flutter (12790): [ERROR:flutter/lib/ui/ui_dart_state.cc(148)] Unhandled Exception: NoSuchMethodError: The method 'call' was called on null.
E/flutter (12790): Receiver: null
E/flutter (12790): Tried calling: call()
E/flutter (12790): #0      _rootRunUnary (dart:async/zone.dart:1132:38)
E/flutter (12790): #1      _CustomZone.runUnary (dart:async/zone.dart:1029:19)
E/flutter (12790): #2      _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
E/flutter (12790): #3      _CustomZone.bindUnaryCallbackGuarded.<anonymous closure> (dart:async/zone.dart:968:26)
E/flutter (12790): #4      _rootRunUnary (dart:async/zone.dart:1136:13)
E/flutter (12790): #5      _CustomZone.runUnary (dart:async/zone.dart:1029:19)
E/flutter (12790): #6      _CustomZone.bindUnaryCallback.<anonymous closure> (dart:async/zone.dart:952:26)
E/flutter (12790): #7      _Timer._runTimers (dart:isolate/runtime/libtimer_impl.dart:382:19)
E/flutter (12790): #8      _Timer._handleMessage (dart:isolate/runtime/libtimer_impl.dart:416:5)
E/flutter (12790): #9      _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:171:12)
E/flutter (12790):
```

Here's my `flutter doctor`:
```
[gconrad@gconrad-fedora bin]$ ./flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel beta, v1.2.1, on Linux, locale en_US.UTF-8)
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[✓] Android Studio (version 3.3)
[!] IntelliJ IDEA Community Edition (version 2018.3)
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
[✓] Connected device (1 available)

! Doctor found issues in 1 category.
```
Here is the relevant code:
```
class GameRouteViewModel {
  final Stopwatch stopwatch = Stopwatch();
  final Board _board;
  Timer timer;
  Function rebuildUI;

  GameRouteViewModel(int rows, int columns, int mines)
      : _board = Board(rows, columns, mines);

  void setCallbacks(Function rebuildUI, Function win, Function lose) {
    this.rebuildUI = rebuildUI;
    _board.onWin = () => win(calcElapsedTime());
    _board.onLose = () => lose(calcElapsedTime());
  }

  String calcElapsedTime() {
    stopwatch.stop();
    timer?.cancel();
    return stopwatch.elapsed.toString();
  }

  void onTilePress(GameTileViewModel tileModel) {
    if (_board.gameState != GameState.ongoing) return;
    if (!_board.initialized) {
      stopwatch.start();
      timer = Timer.periodic(Duration(seconds: 1), rebuildUI(() {}));
    }
    rebuildUI(() {
      _board.revealTile(tileModel.row, tileModel.col);
    });
  }

// Other functions omitted
}
```

**Comment by GregoryConrad** [comment]
Just realized I created the timer wrong. Sorry about the post.

**Comment by sotoyjuan** [comment]
@GregoryConrad Would be nice to post solution though.

**Comment by GregoryConrad** [comment]
@sotoyjuan 
Didn't realize this would be a common issue! The line in which I created the timer is incorrect. In my case, `timer = Timer.periodic(Duration(seconds: 1), rebuildUI(() {}));` should've been `timer = Timer.periodic(Duration(seconds: 1), (timer) => rebuildUI(() {}));`. Just a mismatch of arguments to the `Timer.periodic` constructor (I was passing the return value of `rebuildUI` instead of an actual function that can be executed). The docs describing the correct parameters are [here](https://api.flutter.dev/flutter/dart-async/Timer/Timer.periodic.html).
