### ISSUE TITLE
Cirrus tasks crashing with Unhandled exception: Bad state: StreamSink is bound to a stream

### ISSUE THREAD

**Issue by jonahwilliams** [flutter/flutter#29262]
This is happening in our test formatter.
```
0:11:40.475490 +3686 ~63 -0: loading C:\Windows\Temp\flutter sdk\packages\flutter\test\widgets\wrap_test.dartProcessing...
Processing...
Processing...
Processing...
Processing...
Processing...
Processing...
Processing...
Processing...
Processing...
Processing...
Processing...
Processing...
Processing...
Unhandled exception:
Bad state: StreamSink is bound to a stream
#0      _StreamSinkImpl._controller (dart:io/io_sink.dart:236:7)
#1      _StreamSinkImpl.add (dart:io/io_sink.dart:156:5)
#2      _IOSinkImpl.write (dart:io/io_sink.dart:289:5)
#3      _IOSinkImpl.writeln (dart:io/io_sink.dart:309:5)
#4      _StdSink.writeln (dart:io/stdio.dart:341:11)
#5      FlutterCompactFormatter.processRawOutput (file:///C:/Windows/Temp/flutter%20sdk/dev/bots/flutter_compact_formatter.dart:139:20)
#6      Stream.forEach.<anonymous closure>.<anonymous closure> (dart:async/stream.dart:816:45)
#7      _runUserCode (dart:async/stream_pipe.dart:11:23)
#8      Stream.forEach.<anonymous closure> (dart:async/stream.dart:816:11)
#9      _RootZone.runUnaryGuarded (dart:async/zone.dart:1314:10)
#10     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#11     _DelayedData.perform (dart:async/stream_impl.dart:591:14)
#12     _StreamImplEvents.handleNext (dart:async/stream_impl.dart:707:11)
#13     _PendingEvents.schedule.<anonymous closure> (dart:async/stream_impl.dart:667:7)
#14     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#15     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#16     _runPendingImmediateCallback (dart:isolate/runtime/lib/isolate_patch.dart:115:13)
#17     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/lib/isolate_patch.dart:172:5)

C:\Windows\Temp\flutter sdk>if 255 NEQ 0 exit /b 255 
```

**Comment by jonahwilliams** [comment]
cc @dnfield

**Comment by dnfield** [comment]
Has this happened recently or are these from before the changes this weekend?

**Comment by jonahwilliams** [comment]
This is from today

**Comment by jonahwilliams** [comment]
Another case:

https://cirrus-ci.com/task/5422404821057536

There is a real failure here but I can't see the logs. We need to revert back to the previous formatter until this is fixed.

**Comment by dnfield** [comment]
I'll open something for this shortly.  What I'd like to do for now is guard it behind an env variable that we won't set for now.  Work for you?

**Comment by jonahwilliams** [comment]
Sounds good

**Comment by zoeyfan** [comment]
@dnfield I am triaging our issue database, and noticed this bug from earlier this year. Is this still relevant? Can we close it now?

**Comment by dnfield** [comment]
Not needed
