### ISSUE TITLE
Apk is not installing in honour 7x

### ISSUE THREAD

**Issue by fazil-augr** [flutter/flutter#29288]
I have successfully build a signed apk. It is working fine in some devices. But in honour 7x. The apk is not installing. when I debug the app in honour 7x. It showing error as

```
Error: ADB exited with exit code 1
adb: failed to install
/Users/user/Documents/myapp/build/app/outputs/apk/app.apk:
Exception occurred while executing:
android.os.ParcelableException: java.io.IOException: Requested internal only,
but not enough space
	at android.util.ExceptionUtils.wrap(ExceptionUtils.java:34)
	at
	com.android.server.pm.PackageInstallerService.createSession(PackageInstallerSer
	vice.java:596)
	at
	com.android.server.pm.PackageManagerShellCommand.doCreateSession(PackageManager
	ShellCommand.java:1362)
	at
	com.android.server.pm.PackageManagerShellCommand.runInstall(PackageManagerShell
	Command.java:201)
	at
	com.android.server.pm.PackageManagerShellCommand.onCommand(PackageManagerShellC
	ommand.java:111)
	at android.os.ShellCommand.exec(ShellCommand.java:96)
	at
	com.android.server.pm.PackageManagerService.onShellCommand(PackageManagerServic
	e.java:23691)
	at android.os.Binder.shellCommand(Binder.java:574)
	at android.os.Binder.onTransact(Binder.java:474)
	at
	android.content.pm.IPackageManager$Stub.onTransact(IPackageManager.java:2652)
	at
	com.android.server.pm.PackageManagerService.onTransact(PackageManagerService.ja
	v
Error launching application on BND AL10. 

```

why it showing error?

**Comment by fazil-augr** [comment]
The problem of insufficient internal memory. The phone have only free space 350 MB. After making the free space it successfully installed.

**Comment by mxolisizondi** [comment]
Its the issue of space try to have enough space it worked for me

**Comment by t0nyak** [comment]
This is kind of weird for me. I'm working on an app with an APK smaller than 30mb. I'm trying to install the app in my phone with more than 400mb free and gets same error. How much free space needs flutter to install this APK on my phone?? It's crazy.
