### ISSUE TITLE
Flutter is crashing

### ISSUE THREAD

**Issue by AlaaEdAouimeur** [flutter/flutter#29299]
## Steps to Reproduce

1. ... I have Downloaded everything right
2. ...and whn i run Flutter Its crash
3. ...

## Logs

```
C:\Windows\System32>flutter --verbose
Manage your Flutter app development.

Common commands:

  flutter create <output directory>
    Create a new Flutter project in the specified directory.

  flutter run [options]
    Run your Flutter application on an attached device or in an emulator.

Usage: flutter <command> [arguments]

Global options:
-h, --help                     Print this usage information.
-v, --verbose                  Noisy logging, including all shell commands executed.
                               If used with --help, shows hidden options.

    --quiet                    Reduce the amount of output from some commands.
    --[no-]wrap                Toggles output word wrapping, regardless of whether or not the output is a terminal.
                               (defaults to on)

    --wrap-column              Sets the output wrap column. If not set, uses the width of the terminal. No wrapping
                               occurs if not writing to a terminal. Use --no-wrap to turn off wrapping when connected to
                               a terminal.

-d, --device-id                Target device id or name (prefixes allowed).
    --version                  Reports the version of this tool.
    --machine                  When used with the --version flag, outputs the information using JSON.
    --[no-]color               Whether to use terminal colors (requires support for ANSI escape sequences).
                               (defaults to on)

    --[no-]version-check       Allow Flutter to check for updates when this command runs.
                               (defaults to on)

    --suppress-analytics       Suppress analytics reporting when this command runs.
    --bug-report               Captures a bug report file to submit to the Flutter team.
                               Contains local paths, device identifiers, and log snippets.

    --packages                 Path to your ".packages" file.
                               (required, since the current directory does not contain a ".packages" file)

    --flutter-root             The root directory of the Flutter repository.
                               Defaults to $FLUTTER_ROOT if set, otherwise uses the parent of the directory that the
                               "flutter" script itself is in.

Local build selection options (not normally required):
    --local-engine-src-path    Path to your engine src directory, if you are building Flutter locally.
                               Defaults to $FLUTTER_ENGINE if set, otherwise defaults to the path given in your
                               pubspec.yaml dependency_overrides for sky_engine, if any, or, failing that, tries to
                               guess at the location based on the value of the --flutter-root option.

    --local-engine             Name of a build output within the engine out directory, if you are building Flutter
                               locally.
                               Use this to select a specific version of the engine if you have built multiple engine
                               targets.
                               This path is relative to --local-engine-src-path/out.

Options for testing the "flutter" tool itself:
    --record-to                Enables recording of process invocations (including stdout and stderr of all such
                               invocations), and file system access (reads and writes).
                               Serializes that recording to a directory with the path specified in this flag. If the
                               directory does not already exist, it will be created.

    --replay-from              Enables mocking of process invocations by replaying their stdout, stderr, and exit code
                               from the specified recording (obtained via --record-to). The path specified in this flag
                               must refer to a directory that holds serialized process invocations structured according
                               to the output of --record-to.

    --show-test-device         List the special 'flutter-tester' device in device listings. This headless device is used
                               to
                               test Flutter tooling.

Available commands:
  analyze                  Analyze the project's Dart code.
  attach                   Attach to a running application.
  bash-completion          Output command line shell completion setup scripts.
  build                    Flutter build commands.
  channel                  List or switch flutter channels.
  clean                    Delete the build/ and .dart_tool/ directories.
  config                   Configure Flutter settings.
  create                   Create a new Flutter project.
  daemon                   Run a persistent, JSON-RPC based server to communicate with devices.
  devices                  List all connected devices.
  doctor                   Show information about the installed tooling.
  drive                    Runs Flutter Driver tests for the current project.
  emulators                List, launch and create emulators.
  format                   Format one or more dart files.
  help                     Display help information for flutter.
  ide-config               Configure the IDE for use in the Flutter tree.
  inject-plugins           Re-generates the GeneratedPluginRegistrants.
  install                  Install a Flutter app on an attached device.
  logs                     Show log output for running Flutter apps.
  make-host-app-editable   Moves host apps from generated directories to non-generated directories so that they can be
                           edited by developers.
  packages                 Commands for managing Flutter packages.
  precache                 Populates the Flutter tool's cache of binary artifacts.
  run                      Run your Flutter app on an attached device.
  screenshot               Take a screenshot from a connected device.
  stop                     Stop your Flutter app on an attached device.
  test                     Run Flutter unit tests for the current project.
  trace                    Start and stop tracing for a running Flutter app.
  update-packages          Update the packages inside the Flutter repo.
  upgrade                  Upgrade your copy of Flutter.
  version                  List or switch flutter versions.

Run "flutter help <command>" for more information about a command.
Run "flutter help -v" for verbose help output, including less commonly used options.
```

```
C:\Windows\System32>flutter doctor -v

Oops; flutter has exited unexpectedly.
Sending crash report to Google.
Crash report sent (report ID: c7525d54b7300a17)
Unhandled exception:
Invalid argument(s): Cannot find executable for where.
#0      _getExecutable (package:process/src/interface/local_process_manager.dart:113:5)
#1      LocalProcessManager.runSync (package:process/src/interface/local_process_manager.dart:84:7)
#2      _WindowsUtils._which (package:flutter_tools/src/base/os.dart:164:49)
#3      OperatingSystemUtils.whichAll (package:flutter_tools/src/base/os.dart:41:43)
#4      AndroidSdk.locateAndroidSdk.findAndroidHomeDir (package:flutter_tools/src/android/android_sdk.dart:309:38)
#5      AndroidSdk.locateAndroidSdk (package:flutter_tools/src/android/android_sdk.dart:331:53)
#6      AppContext._generateIfNecessary.<anonymous closure> (package:flutter_tools/src/base/context.dart:99:41)
#7      __InternalLinkedHashMap&_HashVMBase&MapMixin&_LinkedHashMapMixin.putIfAbsent (dart:collection/runtime/libcompact_hash.dart:281:23)
#8      AppContext._generateIfNecessary (package:flutter_tools/src/base/context.dart:87:20)
#9      AppContext.[] (package:flutter_tools/src/base/context.dart:114:32)
#10     AppContext.[] (package:flutter_tools/src/base/context.dart:113:22)
#11     androidSdk (package:flutter_tools/src/android/android_sdk.dart:20:37)
#12     AndroidLicenseValidator.validate (package:flutter_tools/src/android/android_workflow.dart:180:9)
<asynchronous suspension>
#13     GroupedValidator.validate (package:flutter_tools/src/doctor.dart:318:52)
#14     _AsyncAwaitCompleter.start (dart:async/runtime/libasync_patch.dart:49:6)
#15     GroupedValidator.validate (package:flutter_tools/src/doctor.dart:315:36)
#16     Doctor.startValidatorTasks (package:flutter_tools/src/doctor.dart:116:52)
#17     Doctor.diagnose (package:flutter_tools/src/doctor.dart:189:41)
#18     _AsyncAwaitCompleter.start (dart:async/runtime/libasync_patch.dart:49:6)
#19     Doctor.diagnose (package:flutter_tools/src/doctor.dart:179:24)
#20     _doctorText.<anonymous closure> (package:flutter_tools/runner.dart:188:26)
#21     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:142:29)
#22     _AsyncAwaitCompleter.start (dart:async/runtime/libasync_patch.dart:49:6)
#23     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:142:7)
#24     _rootRun (dart:async/zone.dart:1124:13)
#25     _CustomZone.run (dart:async/zone.dart:1021:19)
#26     _runZoned (dart:async/zone.dart:1516:10)
#27     runZoned (dart:async/zone.dart:1463:12)
#28     AppContext.run (package:flutter_tools/src/base/context.dart:141:18)
#29     _AsyncAwaitCompleter.start (dart:async/runtime/libasync_patch.dart:49:6)
#30     AppContext.run (package:flutter_tools/src/base/context.dart:129:19)
#31     _doctorText (package:flutter_tools/runner.dart:187:19)
#32     _AsyncAwaitCompleter.start (dart:async/runtime/libasync_patch.dart:49:6)
#33     _doctorText (package:flutter_tools/runner.dart:183:27)
#34     _createLocalCrashReport (package:flutter_tools/runner.dart:165:32)
#35     _AsyncAwaitCompleter.start (dart:async/runtime/libasync_patch.dart:49:6)
#36     _createLocalCrashReport (package:flutter_tools/runner.dart:150:37)
#37     _handleToolError (package:flutter_tools/runner.dart:120:33)
#38     _asyncThenWrapperHelper.<anonymous closure> (dart:async/runtime/libasync_patch.dart:77:64)
#39     _rootRunUnary (dart:async/zone.dart:1132:38)
#40     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#41     _FutureListener.handleValue (dart:async/future_impl.dart:126:18)
#42     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:639:45)
#43     Future._propagateToListeners (dart:async/future_impl.dart:668:32)
#44     Future._complete (dart:async/future_impl.dart:473:7)
#45     _SyncCompleter.complete (dart:async/future_impl.dart:51:12)
#46     _AsyncAwaitCompleter.complete (dart:async/runtime/libasync_patch.dart:28:18)
#47     _completeOnAsyncReturn (dart:async/runtime/libasync_patch.dart:294:13)
#48     CrashReportSender.sendReport (package:flutter_tools/src/crash_reporting.dart)
#49     _asyncThenWrapperHelper.<anonymous closure> (dart:async/runtime/libasync_patch.dart:77:64)
#50     _rootRunUnary (dart:async/zone.dart:1132:38)
#51     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#52     _FutureListener.handleValue (dart:async/future_impl.dart:126:18)
#53     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:639:45)
#54     Future._propagateToListeners (dart:async/future_impl.dart:668:32)
#55     Future._complete (dart:async/future_impl.dart:473:7)
#56     Stream.fold.<anonymous closure> (dart:async/stream.dart:724:18)
#57     _rootRun (dart:async/zone.dart:1120:38)
#58     _CustomZone.run (dart:async/zone.dart:1021:19)
#59     _CustomZone.runGuarded (dart:async/zone.dart:923:7)
#60     _BufferingStreamSubscription._sendDone.sendDone (dart:async/stream_impl.dart:389:13)
#61     _BufferingStreamSubscription._sendDone (dart:async/stream_impl.dart:399:15)
#62     _BufferingStreamSubscription._close (dart:async/stream_impl.dart:283:7)
#63     _SinkTransformerStreamSubscription._close (dart:async/stream_transformers.dart:96:11)
#64     _EventSinkWrapper.close (dart:async/stream_transformers.dart:23:11)
#65     _StringAdapterSink.close (dart:convert/string_conversion.dart:251:11)
#66     _Utf8ConversionSink.close (dart:convert/string_conversion.dart:302:20)
#67     _ConverterStreamEventSink.close (dart:convert/chunked_conversion.dart:82:18)
#68     _SinkTransformerStreamSubscription._handleDone (dart:async/stream_transformers.dart:141:24)
#69     _rootRun (dart:async/zone.dart:1120:38)
#70     _CustomZone.run (dart:async/zone.dart:1021:19)
#71     _CustomZone.runGuarded (dart:async/zone.dart:923:7)
#72     _BufferingStreamSubscription._sendDone.sendDone (dart:async/stream_impl.dart:389:13)
#73     _BufferingStreamSubscription._sendDone (dart:async/stream_impl.dart:399:15)
#74     _BufferingStreamSubscription._close (dart:async/stream_impl.dart:283:7)
#75     _ForwardingStream._handleDone (dart:async/stream_pipe.dart:106:10)
#76     _ForwardingStreamSubscription._handleDone (dart:async/stream_pipe.dart:172:13)
#77     _rootRun (dart:async/zone.dart:1120:38)
#78     _CustomZone.run (dart:async/zone.dart:1021:19)
#79     _CustomZone.runGuarded (dart:async/zone.dart:923:7)
#80     _BufferingStreamSubscription._sendDone.sendDone (dart:async/stream_impl.dart:389:13)
#81     _BufferingStreamSubscription._sendDone (dart:async/stream_impl.dart:399:15)
#82     _BufferingStreamSubscription._close (dart:async/stream_impl.dart:283:7)
#83     _SinkTransformerStreamSubscription._close (dart:async/stream_transformers.dart:96:11)
#84     _EventSinkWrapper.close (dart:async/stream_transformers.dart:23:11)
#85     _ByteAdapterSink.close (dart:convert/byte_conversion.dart:62:11)
#86     _FilterSink.close (dart:io/data_transformer.dart:637:11)
#87     _ConverterStreamEventSink.close (dart:convert/chunked_conversion.dart:82:18)
#88     _SinkTransformerStreamSubscription._handleDone (dart:async/stream_transformers.dart:141:24)
#89     _rootRun (dart:async/zone.dart:1120:38)
#90     _CustomZone.run (dart:async/zone.dart:1021:19)
#91     _CustomZone.runGuarded (dart:async/zone.dart:923:7)
#92     _BufferingStreamSubscription._sendDone.sendDone (dart:async/stream_impl.dart:389:13)
#93     _BufferingStreamSubscription._sendDone (dart:async/stream_impl.dart:399:15)
#94     _BufferingStreamSubscription._close (dart:async/stream_impl.dart:283:7)
#95     _ForwardingStream._handleDone (dart:async/stream_pipe.dart:106:10)
#96     _ForwardingStreamSubscription._handleDone (dart:async/stream_pipe.dart:172:13)
#97     _rootRun (dart:async/zone.dart:1120:38)
#98     _CustomZone.run (dart:async/zone.dart:1021:19)
#99     _CustomZone.runGuarded (dart:async/zone.dart:923:7)
#100    _BufferingStreamSubscription._sendDone.sendDone (dart:async/stream_impl.dart:389:13)
#101    _BufferingStreamSubscription._sendDone (dart:async/stream_impl.dart:399:15)
#102    _BufferingStreamSubscription._close (dart:async/stream_impl.dart:283:7)
#103    _SyncStreamController._sendDone (dart:async/stream_controller.dart:772:19)
#104    _StreamController._closeUnchecked (dart:async/stream_controller.dart:629:7)
#105    _StreamController.close (dart:async/stream_controller.dart:622:5)
#106    _HttpParser._closeIncoming (dart:_http/http_parser.dart:1037:23)
#107    _HttpParser._doParse (dart:_http/http_parser.dart:752:11)
#108    _HttpParser._parse (dart:_http/http_parser.dart:318:7)
#109    _HttpParser._onData (dart:_http/http_parser.dart:810:5)
#110    _rootRunUnary (dart:async/zone.dart:1132:38)
#111    _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#112    _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
#113    _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#114    _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#115    _SyncStreamController._sendData (dart:async/stream_controller.dart:764:19)
#116    _StreamController._add (dart:async/stream_controller.dart:640:7)
#117    _StreamController.add (dart:async/stream_controller.dart:586:5)
#118    _Socket._onData (dart:io/runtime/binsocket_patch.dart:1774:41)
#119    _rootRunUnary (dart:async/zone.dart:1132:38)
#120    _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#121    _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
#122    _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#123    _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#124    _SyncStreamController._sendData (dart:async/stream_controller.dart:764:19)
#125    _StreamController._add (dart:async/stream_controller.dart:640:7)
#126    _StreamController.add (dart:async/stream_controller.dart:586:5)
#127    _RawSecureSocket._sendReadEvent (dart:io/secure_socket.dart:1004:19)
#128    _rootRun (dart:async/zone.dart:1120:38)
#129    _CustomZone.run (dart:async/zone.dart:1021:19)
#130    _CustomZone.runGuarded (dart:async/zone.dart:923:7)
#131    _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:963:23)
#132    _rootRun (dart:async/zone.dart:1124:13)
#133    _CustomZone.run (dart:async/zone.dart:1021:19)
#134    _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:947:23)
#135    Timer._createTimer.<anonymous closure> (dart:async/runtime/libtimer_patch.dart:21:15)
#136    _Timer._runTimers (dart:isolate/runtime/libtimer_impl.dart:382:19)
#137    _Timer._handleMessage (dart:isolate/runtime/libtimer_impl.dart:416:5)
#138    _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:171:12)
```

**Comment by kf6gpe** [comment]
Does `flutter doctor --verbose` also crash for you? That may give us more insight.

**Comment by AlaaEdAouimeur** [comment]
Try To Add System32 To Your Path
