### ISSUE TITLE
TextField "Failed assertion: line 238 pos 12: 'overlay != null': is not true"

### ISSUE THREAD

**Issue by MrCreeper1008** [flutter/flutter#29298]
## Steps to Reproduce

1. Create a new Flutter app
2. Use the following code in `main.dart`:
```
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return WidgetsApp(
      color: Colors.green,
      builder: (context, child) => Scaffold(
        body: TextField(),
      ),
    );
  }
}
```
3. Run the app

## Logs
```
2019-03-13 22:49:30.575 5324-5362/com.anticus.text I/flutter: Another exception was thrown: 'package:flutter/src/widgets/text_selection.dart': Failed assertion: line 238 pos 12: 'overlay != null': is not true.
2019-03-13 22:49:31.612 1353-1375/? W/audio_hw_generic: Not supplying enough data to HAL, expected position 2324240 , only wrote 2324160
2019-03-13 22:49:31.624 1725-1966/? D/EGL_emulation: eglMakeCurrent: 0x97d5b020: ver 3 0 (tinfo 0x97d36690)
2019-03-13 22:49:31.697 1719-1719/? W/InputMethodService: Window size has been changed. This may cause jankiness of resizing window: -1 -> -2
2019-03-13 22:49:31.712 1719-3860/? D/EGL_emulation: eglMakeCurrent: 0xa74053c0: ver 3 0 (tinfo 0xa7403850)
2019-03-13 22:49:33.069 5324-5362/com.anticus.text I/flutter: Another exception was thrown: 'package:flutter/src/widgets/text_selection.dart': Failed assertion: line 238 pos 12: 'overlay != null': is not true.
2019-03-13 22:49:33.069 1719-1719/? W/InputMethodService: Window size has been changed. This may cause jankiness of resizing window: -1 -> -2
2019-03-13 22:49:33.075 1719-1719/? I/LatinIME: Starting input. Cursor position = 0,0
2019-03-13 22:49:33.108 1719-3860/? D/EGL_emulation: eglMakeCurrent: 0xa74053c0: ver 3 0 (tinfo 0xa7403850)
2019-03-13 22:49:34.838 1353-1376/? W/audio_hw_generic: Not supplying enough data to HAL, expected position 2631844 , only wrote 2478960
2019-03-13 22:49:37.240 5324-5362/com.anticus.text I/flutter: ══╡ EXCEPTION CAUGHT BY GESTURE ╞═══════════════════════════════════════════════════════════════════
2019-03-13 22:49:37.243 5324-5362/com.anticus.text I/flutter: The following assertion was thrown while handling a gesture:
2019-03-13 22:49:37.243 5324-5362/com.anticus.text I/flutter: 'package:flutter/src/widgets/text_selection.dart': Failed assertion: line 238 pos 12: 'overlay !=
2019-03-13 22:49:37.243 5324-5362/com.anticus.text I/flutter: null': is not true.
2019-03-13 22:49:37.246 5324-5362/com.anticus.text I/flutter: Either the assertion indicates an error in the framework itself, or we should provide substantially
2019-03-13 22:49:37.246 5324-5362/com.anticus.text I/flutter: more information in this error message to help you determine and fix the underlying cause.
2019-03-13 22:49:37.246 5324-5362/com.anticus.text I/flutter: In either case, please report this assertion by filing a bug on GitHub:
2019-03-13 22:49:37.246 5324-5362/com.anticus.text I/flutter:   https://github.com/flutter/flutter/issues/new?template=BUG.md
2019-03-13 22:49:37.246 5324-5362/com.anticus.text I/flutter: When the exception was thrown, this was the stack:
2019-03-13 22:49:37.253 5324-5362/com.anticus.text I/flutter: #2      new TextSelectionOverlay (package:flutter/src/widgets/text_selection.dart:238:12)
2019-03-13 22:49:37.253 5324-5362/com.anticus.text I/flutter: #3      EditableTextState._handleSelectionChanged (package:flutter/src/widgets/editable_text.dart:913:27)
2019-03-13 22:49:37.253 5324-5362/com.anticus.text I/flutter: #4      RenderEditable.selectPositionAt (package:flutter/src/rendering/editable.dart:1262:7)
2019-03-13 22:49:37.253 5324-5362/com.anticus.text I/flutter: #5      RenderEditable.selectPosition (package:flutter/src/rendering/editable.dart:1250:5)
2019-03-13 22:49:37.253 5324-5362/com.anticus.text I/flutter: #6      _TextFieldState._handleSingleTapUp (package:flutter/src/material/text_field.dart:637:27)
2019-03-13 22:49:37.253 5324-5362/com.anticus.text I/flutter: #7      _TextSelectionGestureDetectorState._handleTapUp (package:flutter/src/widgets/text_selection.dart:720:16)
2019-03-13 22:49:37.253 5324-5362/com.anticus.text I/flutter: #8      TapGestureRecognizer._checkUp.<anonymous closure> (package:flutter/src/gestures/tap.dart:240:46)
2019-03-13 22:49:37.253 5324-5362/com.anticus.text I/flutter: #9      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:120:24)
2019-03-13 22:49:37.253 5324-5362/com.anticus.text I/flutter: #10     TapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:240:9)
2019-03-13 22:49:37.253 5324-5362/com.anticus.text I/flutter: #11     TapGestureRecognizer.acceptGesture (package:flutter/src/gestures/tap.dart:204:7)
2019-03-13 22:49:37.253 5324-5362/com.anticus.text I/flutter: #12     GestureArenaManager.sweep (package:flutter/src/gestures/arena.dart:156:27)
2019-03-13 22:49:37.254 5324-5362/com.anticus.text I/flutter: #13     _WidgetsFlutterBinding&BindingBase&GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:218:20)
2019-03-13 22:49:37.254 5324-5362/com.anticus.text I/flutter: #14     _WidgetsFlutterBinding&BindingBase&GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:192:22)
2019-03-13 22:49:37.254 5324-5362/com.anticus.text I/flutter: #15     _WidgetsFlutterBinding&BindingBase&GestureBinding._handlePointerEvent (package:flutter/src/gestures/binding.dart:149:7)
2019-03-13 22:49:37.254 5324-5362/com.anticus.text I/flutter: #16     _WidgetsFlutterBinding&BindingBase&GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:101:7)
2019-03-13 22:49:37.254 5324-5362/com.anticus.text I/flutter: #17     _WidgetsFlutterBinding&BindingBase&GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:85:7)
2019-03-13 22:49:37.254 5324-5362/com.anticus.text I/flutter: #21     _invoke1 (dart:ui/hooks.dart:223:10)
2019-03-13 22:49:37.254 5324-5362/com.anticus.text I/flutter: #22     _dispatchPointerDataPacket (dart:ui/hooks.dart:144:5)
2019-03-13 22:49:37.254 5324-5362/com.anticus.text I/flutter: (elided 5 frames from class _AssertionError and package dart:async)
2019-03-13 22:49:37.254 5324-5362/com.anticus.text I/flutter: Handler: onTapUp
2019-03-13 22:49:37.254 5324-5362/com.anticus.text I/flutter: Recognizer:
2019-03-13 22:49:37.254 5324-5362/com.anticus.text I/flutter:   TapGestureRecognizer#1ef77(debugOwner: GestureDetector, state: ready, won arena, finalPosition:
2019-03-13 22:49:37.254 5324-5362/com.anticus.text I/flutter:   Offset(140.6, 32.7), sent tap down)
2019-03-13 22:49:37.254 5324-5362/com.anticus.text I/flutter: ════════════════════════════════════════════════════════════════════════════════════════════════════
2019-03-13 22:49:37.272 1719-1719/? I/LatinIME: Starting input. Cursor position = 0,0
```

`flutter analyze` reports zero issue.

`flutter doctor -v`:
```
[✓] Flutter (Channel stable, v1.2.1, on Mac OS X 10.13.4 17E199, locale en-US)
    • Flutter version 1.2.1 at /Users/mrcreeper1008/flutter
    • Framework revision 8661d8aecd (4 weeks ago), 2019-02-14 19:19:53 -0800
    • Engine revision 3757390fa4
    • Dart version 2.1.2 (build 2.1.2-dev.0.0 0a7dcf17eb)

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/mrcreeper1008/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling
      support)
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = /Users/mrcreeper1008/Library/Android/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_152-release-1248-b01)
    • All Android licenses accepted.

[✗] iOS toolchain - develop for iOS devices
    ✗ Xcode installation is incomplete; a full installation is necessary for iOS
      development.
      Download at: https://developer.apple.com/xcode/download/
      Or install Xcode via the App Store.
      Once installed, run:
        sudo xcode-select --switch /Applications/Xcode.app/Contents/Developer
    ✗ libimobiledevice and ideviceinstaller are not installed. To install with
      Brew, run:
        brew update
        brew install --HEAD usbmuxd
        brew link usbmuxd
        brew install --HEAD libimobiledevice
        brew install ideviceinstaller
    ✗ ios-deploy not installed. To install:
        brew install ios-deploy
    ✗ CocoaPods not installed.
        CocoaPods is used to retrieve the iOS platform side's plugin code that
        responds to your plugin usage on the Dart side.
        Without resolving iOS dependencies with CocoaPods, plugins will not work
        on iOS.
        For more info, see https://flutter.io/platform-plugins
      To install:
        brew install cocoapods
        pod setup

[✓] Android Studio (version 3.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 33.3.1
    • Dart plugin version 182.5215
    • Java version OpenJDK Runtime Environment (build
      1.8.0_152-release-1248-b01)

[!] VS Code (version 1.32.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    ✗ Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (2 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 7.1.1
      (API 25) (emulator)
    • Android SDK built for x86 • emulator-5556 • android-x86 • Android 6.0 (API
      23) (emulator)
```

I did not install the iOS tool chain, but it should be irrelevant to this issue. Any help is appreciated!

**Comment by HansMuller** [comment]
TextField is a material widget and is typically used with `MaterialApp` rather than `WidgetsApp`. Was using WidgetsApp intentional?

**Comment by MrCreeper1008** [comment]
The MaterialApp widget requires me to provide some routing parameters for routing which I already have implemented myself; plus I need to use a custom design rather than Material design, so I used the more basic WidgetsApp instead. Is it related to the issue I am facing?

**Comment by HansMuller** [comment]
It is related. A MaterialApp version doesn't fail:
```
class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(home: Scaffold(body: TextField()));
  }
}
```

The Material TextField includes support for a (platform-specific) cut/copy/paste menu and other features that can depend on the material library and MaterialApp. That said, the app shouldn't fail with such an obscure error. 

Using custom widgets and a custom router etc with MaterialApp should work out well; then you will not have to worry about incorporating the occasional material widget, like TextField.

**Comment by MrCreeper1008** [comment]
I have also suspected that it has something to do with the copy paste menu because when I tried to select content inside the text field nothing would show up. I'll try if that fixes my issue, though I wish the error would be a bit more descriptive.

**Comment by HansMuller** [comment]
The error is definitely inadequate. This issue should stay open until (at least) the failure mode in this is more informative.

**Comment by rubensdemelo** [comment]
TextField is a "child" of Material. Based on docs : https://docs.flutter.io/flutter/material/TextField-class.html

> If decoration is non-null (which is the default), the text field requires one of its ancestors to be a Material widget.

**Comment by HansMuller** [comment]
This error occurs because the app's TextField is created above its Navigator and the Navigator provides the Overlay that the TextField focus handling code is looking for. The TextField is created _above_ the navigator because the `WidgetsApp builder` parameter is being used. Despite the unassuming name, it's really only intended for a [rather special purpose](https://docs.flutter.io/flutter/widgets/WidgetsApp/builder.html).

The `onGenerateRoute` method is used to build a route in its usual place, below the app's Navigator.
```
class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return WidgetsApp(
      color: Colors.green,
      onGenerateRoute: (RouteSettings settings) {
        return PageRouteBuilder<void>(
          pageBuilder: (BuildContext context, Animation<double> _, Animation<double> __) {
            return Scaffold(body: Center(child: TextField()));
          }
        );
      },
    );
  }
}
```

It's still true that we could provide a slightly more helpful assert message in this case.

**Comment by MrCreeper1008** [comment]
Hi @HansMuller, I used MaterialApp instead of WidgetsApp and the exception went away. Thanks!
