### ISSUE TITLE
Attempt to invoke interface method 'void io.flutter.plugin.common.MethodChannel$Result.error(java.lang.String, java.lang.String, java.lang.Object)' on a null object reference

### ISSUE THREAD

**Issue by zaralockheart** [flutter/flutter#29334]
I face this issue when running `image_picker: ^0.5.0+6`, even when I changed to `file_picker: ^1.2.0`, a similar issue found at `image_cropper: ^1.0.0`. On android.

at `image_picker`, the app crash after I select image from gallery.

## Logs

```
E/AndroidRuntime( 6971): FATAL EXCEPTION: main
E/AndroidRuntime( 6971): Process: my.com.etiqa.smile, PID: 6971
E/AndroidRuntime( 6971): java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=2342, result=-1, data=Intent { dat=content://com.android.providers.media.documents/document/image:158 flg=0x1 }} to activity {my.com.etiqa.smile/my.com.etiqa.smilefluter.MainActivity}: java.lang.NullPointerException: Attempt to invoke interface method 'void io.flutter.plugin.common.MethodChannel$Result.error(java.lang.String, java.lang.String, java.lang.Object)' on a null object reference
E/AndroidRuntime( 6971): 	at android.app.ActivityThread.deliverResults(ActivityThread.java:4363)
E/AndroidRuntime( 6971): 	at android.app.ActivityThread.handleSendResult(ActivityThread.java:4405)
E/AndroidRuntime( 6971): 	at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:49)
E/AndroidRuntime( 6971): 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
E/AndroidRuntime( 6971): 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
E/AndroidRuntime( 6971): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1811)
E/AndroidRuntime( 6971): 	at android.os.Handler.dispatchMessage(Handler.java:106)
E/AndroidRuntime( 6971): 	at android.os.Looper.loop(Looper.java:193)
E/AndroidRuntime( 6971): 	at android.app.ActivityThread.main(ActivityThread.java:6694)
E/AndroidRuntime( 6971): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime( 6971): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
E/AndroidRuntime( 6971): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
E/AndroidRuntime( 6971): Caused by: java.lang.NullPointerException: Attempt to invoke interface method 'void io.flutter.plugin.common.MethodChannel$Result.error(java.lang.String, java.lang.String, java.lang.Object)' on a null object reference
E/AndroidRuntime( 6971): 	at com.mr.flutter.plugin.filepicker.FilePickerPlugin$1.onActivityResult(FilePickerPlugin.java:85)
E/AndroidRuntime( 6971): 	at io.flutter.app.FlutterPluginRegistry.onActivityResult(FlutterPluginRegistry.java:218)
E/AndroidRuntime( 6971): 	at io.flutter.app.FlutterActivityDelegate.onActivityResult(FlutterActivityDelegate.java:143)
E/AndroidRuntime( 6971): 	at io.flutter.app.FlutterActivity.onActivityResult(FlutterActivity.java:142)
E/AndroidRuntime( 6971): 	at my.com.etiqa.smilefluter.MainActivity.onActivityResult(MainActivity.kt:62)
E/AndroidRuntime( 6971): 	at android.app.Activity.dispatchActivityResult(Activity.java:7454)
E/AndroidRuntime( 6971): 	at android.app.ActivityThread.deliverResults(ActivityThread.java:4356)
E/AndroidRuntime( 6971): 	... 11 more
```

```
rt plugin version 182.5215
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)

[!] IntelliJ IDEA Ultimate Edition (version 2018.2.6)
    • IntelliJ at /Users/yusuf/Applications/JetBrains Toolbox/IntelliJ IDEA Ultimate.app
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.io/intellij-setup/#installing-the-plugins

[✓] VS Code (version 1.31.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 2.24.0

[✓] Connected device (1 available)
    • Mi A2 Lite • 678af4780305 • android-arm64 • Android 9 (API 28)

! Doctor found issues in 1 category.
```
I tried to reproduce the error with new project, but seems like it works fine in the new project.

**Comment by zaralockheart** [comment]
Seems like if I reclone my project, it works just fine.

**Comment by zaralockheart** [comment]
now I got this error
```
E/AndroidRuntime(19120): java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=2342, result=0, data=null} to activity {my.com.etiqa.smile.partner/my.com.etiqa.smile.partner.MainActivity}: java.lang.IllegalArgumentException: Parameter specified as non-null is null: method kotlin.jvm.internal.Intrinsics.checkParameterIsNotNull, parameter data
E/AndroidRuntime(19120): 	at android.app.ActivityThread.deliverResults(ActivityThread.java:4363)
E/AndroidRuntime(19120): 	at android.app.ActivityThread.handleSendResult(ActivityThread.java:4405)
E/AndroidRuntime(19120): 	at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:49)
E/AndroidRuntime(19120): 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
E/AndroidRuntime(19120): 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
E/AndroidRuntime(19120): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1811)
E/AndroidRuntime(19120): 	at android.os.Handler.dispatchMessage(Handler.java:106)
E/AndroidRuntime(19120): 	at android.os.Looper.loop(Looper.java:193)
E/AndroidRuntime(19120): 	at android.app.ActivityThread.main(ActivityThread.java:6694)
E/AndroidRuntime(19120): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(19120): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
E/AndroidRuntime(19120): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
E/AndroidRuntime(19120): Caused by: java.lang.IllegalArgumentException: Parameter specified as non-null is null: method kotlin.jvm.internal.Intrinsics.checkParameterIsNotNull, parameter data
E/AndroidRuntime(19120): 	at my.com.etiqa.smile.partner.MainActivity.onActivityResult(Unknown Source:2)
E/AndroidRuntime(19120): 	at android.app.Activity.dispatchActivityResult(Activity.java:7454)
E/AndroidRuntime(19120): 	at android.app.ActivityThread.deliverResults(ActivityThread.java:4356)
E/AndroidRuntime(19120): 	... 11 more
```
it happens when I open the image_picker, and press back instead of click on image.

**Comment by DK15** [comment]
I am getting exactly same exception when I take a picture and click confirm button that leads to app crash.  I commented in [this](https://github.com/flutter/flutter/issues/27920) thread.

My doubt is the exception points to a function in kotlin file which somehow is returning a null parameter and I am not sure how is that related to image_picker plugin. 

@zoechi It would be great if could you help us in resolving this issue.

**Comment by DK15** [comment]
@zaralockheart Can you show the `smilefluter.MainActivity` file and method signature where it's pointing the error at ? I think I've fix for the issue I was facing which was very similar to the one you posted.

**Comment by zaralockheart** [comment]
Seems like problem at here
```
override fun onActivityResult(requestCode: Int, resultCode: Int, data: Intent?) {
        super.onActivityResult(requestCode, resultCode, data)
        mOpenAuthorize?.onActivityResult(requestCode, resultCode, data)
        if (resultCode == Activity.RESULT_OK) {
            if (requestCode == REQUEST_OAUTH_REQUEST_CODE) {
                subscribe(this.result)
            }
        }
    }
```

when call `super`

**Comment by DK15** [comment]
Check [this](https://stackoverflow.com/questions/55686816/parameter-specified-as-non-null-is-null-caused-by-java-lang-illegalargumentexcep/55687346#55687346) answer. Hope this resolves your issue.

**Comment by zaralockheart** [comment]
@DK15 seems like things are working now... thanks!

**Comment by kukuandroid** [comment]
@zaralockheart  how did you solve the issue ?

**Comment by doodatales** [comment]
Same problem but using image_cropper.  On exiting the image cropper or on saving the cropped image, app crashes for me with the same console printout.  How did that answer resolve your issue?

**Comment by zaralockheart** [comment]
@kukuandroid can't really remember how, this was a  year ago. But if you have onActivityResult in your own MainActivity. The issue is actually there. I think I remove that part of code and re-implement it with `override members` auto complete.
