### ISSUE TITLE
'package:flutter/src/rendering/box.dart': Failed assertion: line 307 pos 12: 'width > 0.0': is not true.

### ISSUE THREAD

**Issue by Pherne** [flutter/flutter#29359]
```
Widget build(BuildContext context) {
    PackageInfo.fromPlatform().then((PackageInfo packageInfo) {
      version = packageInfo.version;
      buildNumber = packageInfo.buildNumber;
    });

    return Scaffold(
      appBar: AppBar(
          iconTheme: IconThemeData(
            color: petrol,
          ),
          elevation: 0,
          backgroundColor: Colors.transparent,
          title: Text('', style: TextStyle(color: petrol))),
      body: StaggeredGridView.count(
        crossAxisCount: 2,
        crossAxisSpacing: 12.0,
        mainAxisSpacing: 12.0,
        padding: EdgeInsets.symmetric(horizontal: 16.0, vertical: 8.0),
        children: <Widget>[
          DecoratedBox(
            decoration: BoxDecoration(
              image: DecorationImage(
                image: AssetImage('assets/logoWide.png'),
                // ...
              ),
              // ...
            ),
          ),
          _openNewRoute(
              'Events',
              _myItems(AssetImage('assets/_event.jpg'), 'Veranstaltungen',
                  orangeTranslucent)),
          _openNewRoute(
              'PARTNER',
              _myItems(AssetImage('assets/_partners.jpg'), 'Partner',
                  turquoisTranslucent)),
          _openNewRoute(
              getEnumName(categoryEnum.SHOPPING),
              _myItems(AssetImage('assets/_shopping.jpg'), 'Shopping',
                  turquoisTranslucent)),
          _openNewRoute(
              'NEWS',
              _myItems(
                  AssetImage('assets/_news.png'), 'News', orangeTranslucent)),
          _openNewRoute(
              getEnumName(categoryEnum.HEALTH),
              _myItems(AssetImage('assets/_gesundheit.jpg'), 'Gesundheit',
                  orangeTranslucent)),
          _openNewRoute(
              getEnumName(categoryEnum.EATDRINK),
              _myItems(AssetImage('assets/_essentrinken.jpg'),
                  'Essen & Trinken', turquoisTranslucent)),
          _openNewRoute(
              getEnumName(categoryEnum.OVERNIGHT),
              _myItems(AssetImage('assets/_uebernachtung.jpg'),
                  'Übernachtungen', turquoisTranslucent)),
          _openNewRoute(
              getEnumName(categoryEnum.SPORTS),
              _myItems(AssetImage('assets/_sport_und_freizeit.jpg'),
                  'Sport & Freizeit', orangeTranslucent)),
          _openNewRoute(
              'NIGHTLIFE',
              _myItems(AssetImage('assets/_nightlife.png'), 'Nightlife',
                  orangeTranslucent)),
          _openNewRoute(
              'TAXIS',
              _myItems(
                  AssetImage('assets/_taxi.png'),
                  'Taxis',
                  turquoisTranslucent)),
          _openNewRoute(
              'RADIO',
              _myItems(AssetImage('assets/_radio.png'), '',
                  Colors.transparent)),
          _openNewRoute(
              'Vier-Tore-Fest',
              _myItems(AssetImage('assets/_festival.jpg'), 'Festival',
                  orangeTranslucent)),
          _versionItem()
        ],
        staggeredTiles: [
          StaggeredTile.extent(2, 140.0),
          StaggeredTile.extent(1, 140.0),
          StaggeredTile.extent(1, 140.0),
          StaggeredTile.extent(1, 140.0),
          StaggeredTile.extent(1, 140.0),
          StaggeredTile.extent(1, 140.0),
          StaggeredTile.extent(1, 140.0),
          StaggeredTile.extent(1, 140.0),
          StaggeredTile.extent(1, 140.0),
          StaggeredTile.extent(1, 140.0),
          StaggeredTile.extent(1, 140.0),
          StaggeredTile.extent(2, 140.0),
          StaggeredTile.extent(2, 140.0),
          StaggeredTile.extent(2, 140.0),
        ],
      ),
      drawer: new drawer(),
    );
  }
```

I have created a Dashboard using the StaggeredGridView in Android in which I need to scroll in. As soon as the top borders of the first to panels in my StaggeredGridView aren't visible anymore I get this Error:

```
I/flutter (24741): ══╡ EXCEPTION CAUGHT BY RENDERING LIBRARY ╞═════════════════════════════════════════════════════════
I/flutter (24741): The following assertion was thrown during performLayout():
I/flutter (24741): 'package:flutter/src/rendering/box.dart': Failed assertion: line 307 pos 12: 'width > 0.0': is not
I/flutter (24741): true.
I/flutter (24741): Either the assertion indicates an error in the framework itself, or we should provide substantially
I/flutter (24741): more information in this error message to help you determine and fix the underlying cause.
I/flutter (24741): In either case, please report this assertion by filing a bug on GitHub:
I/flutter (24741):   https://github.com/flutter/flutter/issues/new?template=BUG.md
I/flutter (24741): When the exception was thrown, this was the stack:
I/flutter (24741): #2      BoxConstraints.constrainSizeAndAttemptToPreserveAspectRatio (package:flutter/src/rendering/box.dart:307:12)
I/flutter (24741): #3      RenderFittedBox.performLayout (package:flutter/src/rendering/proxy_box.dart:2288:26)
I/flutter (24741): #4      RenderObject.layout (package:flutter/src/rendering/object.dart:1632:7)
I/flutter (24741): #5      RenderPadding.performLayout (package:flutter/src/rendering/shifted_box.dart:199:11)
I/flutter (24741): #6      RenderObject.layout (package:flutter/src/rendering/object.dart:1632:7)
I/flutter (24741): #7      RenderPositionedBox.performLayout (package:flutter/src/rendering/shifted_box.dart:385:13)
I/flutter (24741): #8      RenderObject.layout (package:flutter/src/rendering/object.dart:1632:7)
I/flutter (24741): #9      _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter (24741): #10     RenderObject.layout (package:flutter/src/rendering/object.dart:1632:7)
I/flutter (24741): #11     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter (24741): #12     RenderObject.layout (package:flutter/src/rendering/object.dart:1632:7)
I/flutter (24741): #13     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter (24741): #14     RenderObject.layout (package:flutter/src/rendering/object.dart:1632:7)
I/flutter (24741): #15     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter (24741): #16     RenderObject.layout (package:flutter/src/rendering/object.dart:1632:7)
I/flutter (24741): #17     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter (24741): #18     RenderObject.layout (package:flutter/src/rendering/object.dart:1632:7)
I/flutter (24741): #19     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter (24741): #20     _RenderCustomClip.performLayout (package:flutter/src/rendering/proxy_box.dart:1206:11)
I/flutter (24741): #21     RenderObject.layout (package:flutter/src/rendering/object.dart:1632:7)
I/flutter (24741): #22     RenderPadding.performLayout (package:flutter/src/rendering/shifted_box.dart:199:11)
I/flutter (24741): #23     RenderObject.layout (package:flutter/src/rendering/object.dart:1632:7)
I/flutter (24741): #24     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter (24741): #25     RenderObject.layout (package:flutter/src/rendering/object.dart:1632:7)
I/flutter (24741): #26     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter (24741): #27     RenderObject.layout (package:flutter/src/rendering/object.dart:1632:7)
I/flutter (24741): #28     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter (24741): #29     RenderObject.layout (package:flutter/src/rendering/object.dart:1632:7)
I/flutter (24741): #30     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter (24741): #31     RenderObject.layout (package:flutter/src/rendering/object.dart:1632:7)
I/flutter (24741): #32     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter (24741): #33     RenderObject.layout (package:flutter/src/rendering/object.dart:1632:7)
I/flutter (24741): #34     RenderSliverVariableSizeBoxAdaptor.addAndLayoutChild (package:flutter_staggered_grid_view/src/rendering/sliver_variable_size_box_adaptor.dart:308:13)
I/flutter (24741): #35     RenderSliverStaggeredGrid.performLayout (package:flutter_staggered_grid_view/src/rendering/sliver_staggered_grid.dart:330:13)
I/flutter (24741): #36     RenderObject.layout (package:flutter/src/rendering/object.dart:1632:7)
I/flutter (24741): #37     RenderSliverPadding.performLayout (package:flutter/src/rendering/sliver_padding.dart:182:11)
I/flutter (24741): #38     RenderObject.layout (package:flutter/src/rendering/object.dart:1632:7)
I/flutter (24741): #39     RenderViewportBase.layoutChildSequence (package:flutter/src/rendering/viewport.dart:407:13)
I/flutter (24741): #40     RenderViewport._attemptLayout (package:flutter/src/rendering/viewport.dart:1322:12)
I/flutter (24741): #41     RenderViewport.performLayout (package:flutter/src/rendering/viewport.dart:1240:20)
I/flutter (24741): #42     RenderObject.layout (package:flutter/src/rendering/object.dart:1632:7)
I/flutter (24741): #43     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter (24741): #44     RenderObject.layout (package:flutter/src/rendering/object.dart:1632:7)
I/flutter (24741): #45     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter (24741): #46     RenderObject.layout (package:flutter/src/rendering/object.dart:1632:7)
I/flutter (24741): #47     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter (24741): #48     RenderObject.layout (package:flutter/src/rendering/object.dart:1632:7)
I/flutter (24741): #49     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter (24741): #50     RenderObject.layout (package:flutter/src/rendering/object.dart:1632:7)
I/flutter (24741): #51     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter (24741): #52     RenderObject.layout (package:flutter/src/rendering/object.dart:1632:7)
I/flutter (24741): #53     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter (24741): #54     RenderObject.layout (package:flutter/src/rendering/object.dart:1632:7)
I/flutter (24741): #55     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter (24741): #56     RenderObject.layout (package:flutter/src/rendering/object.dart:1632:7)
I/flutter (24741): #57     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter (24741): #58     RenderObject.layout (package:flutter/src/rendering/object.dart:1632:7)
I/flutter (24741): #59     MultiChildLayoutDelegate.layoutChild (package:flutter/src/rendering/custom_layout.dart:142:11)
I/flutter (24741): #60     _ScaffoldLayout.performLayout (package:flutter/src/material/scaffold.dart:350:7)
I/flutter (24741): #61     MultiChildLayoutDelegate._callPerformLayout (package:flutter/src/rendering/custom_layout.dart:212:7)
I/flutter (24741): #62     RenderCustomMultiChildLayoutBox.performLayout (package:flutter/src/rendering/custom_layout.dart:356:14)
I/flutter (24741): #63     RenderObject.layout (package:flutter/src/rendering/object.dart:1632:7)
I/flutter (24741): #64     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter (24741): #65     RenderObject.layout (package:flutter/src/rendering/object.dart:1632:7)
I/flutter (24741): #66     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter (24741): #67     _RenderCustomClip.performLayout (package:flutter/src/rendering/proxy_box.dart:1206:11)
I/flutter (24741): #68     RenderObject.layout (package:flutter/src/rendering/object.dart:1632:7)
I/flutter (24741): #69     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter (24741): #70     RenderObject.layout (package:flutter/src/rendering/object.dart:1632:7)
I/flutter (24741): #71     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter (24741): #72     RenderObject.layout (package:flutter/src/rendering/object.dart:1632:7)
I/flutter (24741): #73     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter (24741): #74     RenderObject.layout (package:flutter/src/rendering/object.dart:1632:7)
I/flutter (24741): #75     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter (24741): #76     RenderObject.layout (package:flutter/src/rendering/object.dart:1632:7)
I/flutter (24741): #77     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter (24741): #78     RenderObject.layout (package:flutter/src/rendering/object.dart:1632:7)
I/flutter (24741): #79     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter (24741): #80     RenderObject.layout (package:flutter/src/rendering/object.dart:1632:7)
I/flutter (24741): #81     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter (24741): #82     RenderObject.layout (package:flutter/src/rendering/object.dart:1632:7)
I/flutter (24741): #83     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter (24741): #84     RenderOffstage.performLayout (package:flutter/src/rendering/proxy_box.dart:3032:13)
I/flutter (24741): #85     RenderObject.layout (package:flutter/src/rendering/object.dart:1632:7)
I/flutter (24741): #86     RenderStack.performLayout (package:flutter/src/rendering/stack.dart:510:15)
I/flutter (24741): #87     RenderObject.layout (package:flutter/src/rendering/object.dart:1632:7)
I/flutter (24741): #88     __RenderTheatre&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter (24741): #89     RenderObject.layout (package:flutter/src/rendering/object.dart:1632:7)
I/flutter (24741): #90     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter (24741): #91     RenderObject.layout (package:flutter/src/rendering/object.dart:1632:7)
I/flutter (24741): #92     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter (24741): #93     RenderObject.layout (package:flutter/src/rendering/object.dart:1632:7)
I/flutter (24741): #94     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter (24741): #95     RenderObject.layout (package:flutter/src/rendering/object.dart:1632:7)
I/flutter (24741): #96     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter (24741): #97     RenderObject.layout (package:flutter/src/rendering/object.dart:1632:7)
I/flutter (24741): #98     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter (24741): #99     RenderObject.layout (package:flutter/src/rendering/object.dart:1632:7)
I/flutter (24741): #100    RenderView.performLayout (package:flutter/src/rendering/view.dart:151:13)
I/flutter (24741): #101    RenderObject._layoutWithoutResize (package:flutter/src/rendering/object.dart:1507:7)
I/flutter (24741): #102    PipelineOwner.flushLayout (package:flutter/src/rendering/object.dart:766:18)
I/flutter (24741): #103    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding.drawFrame (package:flutter/src/rendering/binding.dart:329:19)
I/flutter (24741): #104    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding&WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:701:13)
I/flutter (24741): #105    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:268:5)
I/flutter (24741): #106    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:988:15)
I/flutter (24741): #107    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:928:9)
Reloaded 2 of 667 libraries in 1.418ms.
I/flutter (24741): #108    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.scheduleWarmUpFrame.<anonymous closure> (package:flutter/src/scheduler/binding.dart:749:7)
I/flutter (24741): #110    _Timer._runTimers (dart:isolate/runtime/libtimer_impl.dart:382:19)
I/flutter (24741): #111    _Timer._handleMessage (dart:isolate/runtime/libtimer_impl.dart:416:5)
I/flutter (24741): #112    _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:171:12)
I/flutter (24741): (elided 3 frames from class _AssertionError and package dart:async)
I/flutter (24741): The following RenderObject was being processed when the exception was fired:
I/flutter (24741):   RenderFittedBox#8ef67 relayoutBoundary=up2 NEEDS-LAYOUT NEEDS-PAINT
I/flutter (24741):   creator: FittedBox ← Padding ← Center ← DecoratedBox ← Container ← DecoratedBox ← Container ←
I/flutter (24741):   Semantics ← DefaultTextStyle ← AnimatedDefaultTextStyle ← _InkFeatures-[GlobalKey#817fe ink
I/flutter (24741):   renderer] ← NotificationListener<LayoutChangedNotification> ← ⋯
I/flutter (24741):   parentData: offset=Offset(0.0, 0.0) (can use size)
I/flutter (24741):   constraints: BoxConstraints(0.0<=w<=320.0, 0.0<=h<=108.0)
I/flutter (24741):   size: MISSING
I/flutter (24741):   fit: contain
I/flutter (24741):   alignment: center
I/flutter (24741):   textDirection: ltr
I/flutter (24741): This RenderObject had the following child:
I/flutter (24741):   RenderParagraph#56f99 relayoutBoundary=up3 NEEDS-PAINT
I/flutter (24741): ════════════════════════════════════════════════════════════════════════════════════════════════════
I/flutter (24741): Another exception was thrown: RenderBox was not laid out: RenderFittedBox#8ef67 relayoutBoundary=up2 NEEDS-PAINT
I/flutter (24741): Another exception was thrown: RenderBox was not laid out: RenderFittedBox#8ef67 relayoutBoundary=up2
I/flutter (24741): Another exception was thrown: 'package:flutter/src/rendering/box.dart': Failed assertion: line 307 pos 12: 'width > 0.0': is not true.
I/flutter (24741): Another exception was thrown: RenderBox was not laid out: RenderFittedBox#39d3b relayoutBoundary=up2 NEEDS-PAINT
I/flutter (24741): Another exception was thrown: 'package:flutter/src/rendering/shifted_box.dart': Failed assertion: line 314 pos 12: 'child.hasSize': is not true.
I/flutter (24741): Another exception was thrown: RenderBox was not laid out: RenderFittedBox#39d3b relayoutBoundary=up2
```

I'm still able to scroll, but I get this exception every time I scroll down. When I scroll down to the bottom of my page and try to scroll back up I get the following error:

```
E/flutter (24741): [ERROR:flutter/lib/ui/ui_dart_state.cc(148)] Unhandled Exception: Cannot hit test a render box with no size.
E/flutter (24741): The hitTest() method was called on this RenderBox:
E/flutter (24741):   RenderPadding#ee31e relayoutBoundary=up1
E/flutter (24741): Although this node is not marked as needing layout, its size is not set. A RenderBox object must have an explicit size before it can be hit-tested. Make sure that the RenderBox in question sets its size during layout.
E/flutter (24741): #0      RenderBox.hitTest.<anonymous closure> (package:flutter/src/rendering/box.dart:1901:9)
E/flutter (24741): #1      RenderBox.hitTest (package:flutter/src/rendering/box.dart:1912:6)
E/flutter (24741): #2      RenderShiftedBox.hitTestChildren (package:flutter/src/rendering/shifted_box.dart:78:20)
E/flutter (24741): #3      RenderBox.hitTest (package:flutter/src/rendering/box.dart:1914:11)
E/flutter (24741): #4      _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:114:19)
E/flutter (24741): #5      RenderBox.hitTest (package:flutter/src/rendering/box.dart:1914:11)
E/flutter (24741): #6      _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:114:19)
E/flutter (24741): #7      RenderBox.hitTest (package:flutter/src/rendering/box.dart:1914:11)
E/flutter (24741): #8      _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:114:19)
E/flutter (24741): #9      RenderBox.hitTest (package:flutter/src/rendering/box.dart:1914:11)
E/flutter (24741): #10     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:114:19)
E/flutter (24741): #11     RenderBox.hitTest (package:flutter/src/rendering/box.dart:1914:11)
E/flutter (24741): #12     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:114:19)
E/flutter (24741): #13     RenderCustomPaint.hitTestChildren (package:flutter/src/rendering/custom_paint.dart:501:18)
E/flutter (24741): #14     RenderBox.hitTest (package:flutter/src/rendering/box.dart:1914:11)
E/flutter (24741): #15     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:114:19)
E/flutter (24741): #16     RenderBox.hitTest (package:flutter/src/rendering/box.dart:1914:11)
E/flutter (24741): #17     RenderPhysicalShape.hitTest (package:flutter/src/rendering/proxy_box.dart:1797:18)
E/flutter (24741): #18     RenderShiftedBox.hitTestChildren (package:flutter/src/rendering/shifted_box.dart:78:20)
E/flutter (24741): #19     RenderBox.hitTest (package:flutter/src/rendering/box.dart:1914:11)
E/flutter (24741): #20     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:114:19)
E/flutter (24741): #21     RenderBox.hitTest (package:flutter/src/rendering/box.dart:1914:11)
E/flutter (24741): #22     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:114:19)
E/flutter (24741): #23     RenderProxyBoxWithHitTestBehavior.hitTest (package:flutter/src/rendering/proxy_box.dart:161:19)
E/flutter (24741): #24     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:114:19)
E/flutter (24741): #25     RenderBox.hitTest (package:flutter/src/rendering/box.dart:1914:11)
E/flutter (24741): #26     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:114:19)
E/flutter (24741): #27     RenderBox.hitTest (package:flutter/src/rendering/box.dart:1914:11)
E/flutter (24741): #28     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:114:19)
E/flutter (24741): #29     RenderBox.hitTest (package:flutter/src/rendering/box.dart:1914:11)
E/flutter (24741): #30     _RenderSliverVariableSizeBoxAdaptor&RenderSliver&TileContainerRenderObjectMixin&RenderSliverWithKeepAliveMixin&RenderSliverHelpers.hitTestBoxChild (package:flutter/src/rendering/sliver.dart:1509:22)
E/flutter (24741): #31     RenderSliverVariableSizeBoxAdaptor.hitTestChildren (package:flutter_staggered_grid_view/src/rendering/sliver_variable_size_box_adaptor.dart:380:11)
E/flutter (24741): #32     RenderSliver.hitTest (package:flutter/src/rendering/sliver.
```

When this happens I'm no longer able to scroll back up for a while. The App doesn't really freeze, though, since I'm still able to press buttons.

No issues are found when I run 'flutter doctor -v'.

**Comment by SergioSanchezMontesUAM** [comment]
Did you get to fix it?

**Comment by Pherne** [comment]
In a way it was my own fault. I used FittedBoxes without giving them a size. This is a known issue and can usually be solved by wrapping the FittedBoxes in Expanded or Flexible widgets. It's just that the error message wasn't very helpful.

**Comment by niugengyun** [comment]
```
FittedBox(
              fit: BoxFit.fill,
              child: Column(
                children: <Widget>[
                  SizedBox(height: 5, width: getWidth()),  //加一个默认宽高的组件就好了， 不谢！看不懂中文就翻译去吧
                  Image.asset("assets/images/china.png")
                ],
              ),
            )
```
