### ISSUE TITLE
Crash scrolling gallery app home page with second item opened

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#2935]
1. Open gallery app.
2. Tap "Components" drop-down.
3. Scroll up and down. Usually I get a crash after five or six flings.

The logs contain the following exception:
```
-- EXCEPTION CAUGHT BY SERVICES LIBRARY --------------------------------
Failed to load image:
'packages/flutter/src/services/image_resource.dart': Failed assertion: line 19: 'image != null' is not true.
Stack trace:
#0      _AssertionError._throwNew (dart:core-patch/errors_patch.dart:27)
#1      ImageInfo.ImageInfo (packages/flutter/src/services/image_resource.dart:19)
#2      _ResolutionAwareAssetBundle.fetchImage.<fetchImage_async_body> (packages/flutter/src/widgets/asset_vendor.dart:72)
#3      _RootZone.runUnary (dart:async/zone.dart:1137)
#4      _Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:553)
#5      _Future._propagateToListeners (dart:async/future_impl.dart:639)
#6      _Future._completeWithValue (dart:async/future_impl.dart:426)
#7      _Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:481)
#8      _microtaskLoop (dart:async/schedule_microtask.dart:41)
#9      _startMicrotaskLoop (dart:async/schedule_microtask.dart:50)
------------------------------------------------------------------------
[ERROR:dart_error.cc(17)] Unhandled exception: (same)
../../third_party/skia/src/gpu/batches/GrAtlasTextBatch.cpp:169: fatal error: ""fBounds.contains(rect)""
```
This is followed by this crash:
```
  00110475  sk_abort_no_print()                                      //skia/ext/SkMemory_new_handler.cpp:27
  0023d2ab  GrAtlasTextBatch::onPrepareDraws const                   //third_party/skia/src/gpu/batches/GrAtlasTextBatch.cpp:169
  002467d9  GrVertexBatch::onPrepare                                 //third_party/skia/src/gpu/batches/GrVertexBatch.cpp:16
  v------>  GrBatch::prepare                                         //third_party/skia/src/gpu/batches/GrBatch.h:109
  00210c07  GrDrawTarget::prepareBatches                             //third_party/skia/src/gpu/GrDrawTarget.cpp:204
  0020fde7  GrDrawingManager::flush()                                //third_party/skia/src/gpu/GrDrawingManager.cpp:77
  0020ae35  GrContext::flush                                         //third_party/skia/src/gpu/GrContext.cpp:218
  0020aedb  GrContext::prepareSurfaceForExternalIO                   //third_party/skia/src/gpu/GrContext.cpp:514
  00296761  SkGpuDevice::flush()                                     //third_party/skia/src/gpu/SkGpuDevice.cpp:1764
  000db36f  sky::shell::RasterizerDirect::Draw                       //sky/shell/gpu/direct/rasterizer_direct.cc:95
  0037a1ff  rasterizer::RasterizerStub::AcceptWithResponder          //out/android_Debug/gen/sky/services/rasterizer/rasterizer.mojom.cc:164
  0030e213  mojo::internal::Router::HandleIncomingMessage            //mojo/public/cpp/bindings/lib/router.cc:140
  0030db87  mojo::ReadAndDispatchMessage                             //mojo/public/cpp/bindings/lib/message.cc:108
  0030d235  mojo::internal::Connector::ReadSingleMessage             //mojo/public/cpp/bindings/lib/connector.cc:153
  0030d417  mojo::internal::Connector::ReadAllAvailableMessages()    //mojo/public/cpp/bindings/lib/connector.cc:180
  0030d467  mojo::internal::Connector::OnHandleReady                 //mojo/public/cpp/bindings/lib/connector.cc:130
  v------>  base::Callback<void  const                               //base/callback.h:396
  0010cdb7  mojo::common::HandleWatcher::StateBase::NotifyAndDestroy //mojo/message_pump/handle_watcher.cc:347
  0010d9cf  ...::SameThreadWatchingState::StopWatchingAndNotifyReady //mojo/message_pump/handle_watcher.cc:396
  0010e8e5  mojo::common::MessagePumpMojo::DoInternalWork            //mojo/message_pump/message_pump_mojo.cc:203
  0010ebcd  mojo::common::MessagePumpMojo::DoRunLoop                 //mojo/message_pump/message_pump_mojo.cc:157
  0010ecbf  mojo::common::MessagePumpMojo::Run                       //mojo/message_pump/message_pump_mojo.cc:126
  000e9a45  base::MessageLoop::RunHandler()                          //base/message_loop/message_loop.cc:445
  000eccd5  base::RunLoop::Run()                                     //base/run_loop.cc:55
  000e8463  base::MessageLoop::Run()                                 //base/message_loop/message_loop.cc:288
  000f4b21  base::Thread::ThreadMain()                               //base/threading/thread.cc:248
  000f3f0b  ThreadFunc                                               //base/threading/platform_thread_posix.cc:74
```

There's probably two separate issues here:
- [ ] Framework is doing something bad.
- [ ] Engine is not handling it well.

cc @HansMuller for gallery, @vlidholt for new gallery home page, @jason-simmons for engine crash, @abarth since skia is implicated in the stack.

**Comment by Hixie** [comment]
I've also seen it happen without the exception first.

It seems to happen specifically just after the new animated toolbar graphics go off-screen.

**Comment by eseidelGoogle** [comment]
Crash point: https://github.com/google/skia/blob/master/src/gpu/batches/GrAtlasTextBatch.cpp#L169

**Comment by Hixie** [comment]
Dupe of https://github.com/flutter/flutter/issues/2449
