### ISSUE TITLE
Unclear error message if MaterialApp's home field isn't set

### ISSUE THREAD

**Issue by CiriousJoker** [flutter/flutter#29381]
## Steps to Reproduce

Write something like this:

```
return new MaterialApp(
        theme: new ThemeData(
          primaryColor: Color.fromRGBO(58, 66, 86, 1.0),
        ),
        home: (() {
          // Missing return statement
        })()
```

## Logs

```
I/flutter (11096): ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
I/flutter (11096): The following assertion was thrown building MaterialApp(dirty, state: _MaterialAppState#aafce):
I/flutter (11096): 'package:flutter/src/widgets/app.dart': Failed assertion: line 165 pos 15: 'navigatorObservers !=
I/flutter (11096): null': is not true.
I/flutter (11096): 
I/flutter (11096): Either the assertion indicates an error in the framework itself, or we should provide substantially
I/flutter (11096): more information in this error message to help you determine and fix the underlying cause.
I/flutter (11096): In either case, please report this assertion by filing a bug on GitHub:
I/flutter (11096):   https://github.com/flutter/flutter/issues/new?template=BUG.md
I/flutter (11096): 
I/flutter (11096): When the exception was thrown, this was the stack:
I/flutter (11096): #2      new WidgetsApp 
package:flutter/…/widgets/app.dart:165
I/flutter (11096): #3      _MaterialAppState.build 
package:flutter/…/material/app.dart:444
I/flutter (11096): #4      StatefulElement.build 
package:flutter/…/widgets/framework.dart:3825
I/flutter (11096): #5      ComponentElement.performRebuild 
package:flutter/…/widgets/framework.dart:3736
I/flutter (11096): #6      Element.rebuild 
package:flutter/…/widgets/framework.dart:3559
I/flutter (11096): #7      StatefulElement.update 
package:flutter/…/widgets/framework.dart:3894
I/flutter (11096): #8      Element.updateChild 
package:flutter/…/widgets/framework.dart:2748
I/flutter (11096): #9      ComponentElement.performRebuild 
package:flutter/…/widgets/framework.dart:3747
I/flutter (11096): #10     Element.rebuild 
package:flutter/…/widgets/framework.dart:3559
I/flutter (11096): #11     BuildOwner.buildScope 
package:flutter/…/widgets/framework.dart:2273
I/flutter (11096): #12     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding&WidgetsBinding.drawFrame 
package:flutter/…/widgets/binding.dart:700
I/flutter (11096): #13     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding._handlePersistentFrameCallback 
package:flutter/…/rendering/binding.dart:268
I/flutter (11096): #14     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._invokeFrameCallback 
package:flutter/…/scheduler/binding.dart:988
I/flutter (11096): #15     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.handleDrawFrame 
package:flutter/…/scheduler/binding.dart:928
I/flutter (11096): #16     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._handleDrawFrame 
package:flutter/…/scheduler/binding.dart:840
I/flutter (11096): #20     _invoke (dart:ui/hooks.dart:209:10)
I/flutter (11096): #21     _drawFrame (dart:ui/hooks.dart:168:3)
I/flutter (11096): (elided 5 frames from class _AssertionError and package dart:async)
I/flutter (11096): ════════════════════════════════════════════════════════════════════════════════════════════════════
```

`flutter analyze` took forever and i don't think it matters since I already solved it.

```
[√] Flutter (Channel stable, v1.2.1, on Microsoft Windows [Version 10.0.17134.648], locale en-DE)
    • Flutter version 1.2.1 at G:\FlutterSDK
    • Framework revision 8661d8aecd (4 weeks ago), 2019-02-14 19:19:53 -0800
    • Engine revision 3757390fa4
    • Dart version 2.1.2 (build 2.1.2-dev.0.0 0a7dcf17eb)

[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at G:\AndroidSDK
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = G:\AndroidSDK
    • Java binary at: G:\Program Files\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)
    • All Android licenses accepted.

[√] Android Studio (version 3.3)
    • Android Studio at G:\Program Files\Android Studio
    • Flutter plugin version 33.3.1
    • Dart plugin version 182.5215
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)

[√] Connected device (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 9 (API 28) (emulator)

• No issues found!
```

**Comment by TahaTesser** [comment]
Hi @CiriousJoker 
After testing your code on 
```

### Error message seems more clear than before 
```
/flutter ( 6390): ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
I/flutter ( 6390): The following assertion was thrown building IconTheme(color: Color(0xdd000000)):
I/flutter ( 6390): Could not find a generator for route RouteSettings("/", null) in the _WidgetsAppState.
I/flutter ( 6390): Generators for routes are searched for in the following order:
I/flutter ( 6390):  1. For the "/" route, the "home" property, if non-null, is used.
I/flutter ( 6390):  2. Otherwise, the "routes" table is used, if it has an entry for the route.
I/flutter ( 6390):  3. Otherwise, onGenerateRoute is called. It should return a non-null value for any valid route not
I/flutter ( 6390): handled by "home" and "routes".
I/flutter ( 6390):  4. Finally if all else fails onUnknownRoute is called.
I/flutter ( 6390): Unfortunately, onUnknownRoute was not set.
```
