### ISSUE TITLE
App using camera crashes on start when in profile mode

### ISSUE THREAD

**Issue by MohiuddinM** [flutter/flutter#29419]
```
E/AndroidRuntime( 2615): FATAL EXCEPTION: main
E/AndroidRuntime( 2615): Process: com.x.x, PID: 2615
E/AndroidRuntime( 2615): java.lang.IllegalStateException: Session has been closed; further changes are illegal.
E/AndroidRuntime( 2615):        at android.hardware.camera2.impl.CameraCaptureSessionImpl.checkNotClosed(CameraCaptureSessionIm
pl.java:834)
E/AndroidRuntime( 2615):        at android.hardware.camera2.impl.CameraCaptureSessionImpl.setRepeatingRequest(CameraCaptureSess
ionImpl.java:288)
E/AndroidRuntime( 2615):        at io.flutter.plugins.camera.CameraPlugin$Camera$7.onConfigured(CameraPlugin.java:748)
E/AndroidRuntime( 2615):        at android.hardware.camera2.impl.CallbackProxies$SessionStateCallbackProxy.lambda$onConfigured$
0(CallbackProxies.java:53)
E/AndroidRuntime( 2615):        at android.hardware.camera2.impl.-$$Lambda$CallbackProxies$SessionStateCallbackProxy$soW0qC12Os
ypoky6AfL3P2-TeDw.run(Unknown Source:4)
E/AndroidRuntime( 2615):        at android.os.Handler.handleCallback(Handler.java:873)
E/AndroidRuntime( 2615):        at android.os.Handler.dispatchMessage(Handler.java:99)
E/AndroidRuntime( 2615):        at android.os.Looper.loop(Looper.java:214)
E/AndroidRuntime( 2615):        at android.app.ActivityThread.main(ActivityThread.java:7045)
E/AndroidRuntime( 2615):        at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime( 2615):        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
E/AndroidRuntime( 2615):        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:964)

```

**Comment by TahaTesser** [comment]
Issue isn't reproduced on 
```
Flutter 1.12.13+hotfix.8 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 0b8abb4724 (4 weeks ago) • 2020-02-11 11:44:36 -0800
Engine • revision e1e6ced81d
Tools • Dart 2.7.0
```

<details>
 <summary>Code Sample</summary>

```
import 'package:flutter/material.dart';
import 'package:camera/camera.dart';

List<CameraDescription> cameras;

Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized();
  cameras = await availableCameras();
  runApp(CameraApp());
}

class CameraApp extends StatefulWidget {
  @override
  _CameraAppState createState() => _CameraAppState();
}

class _CameraAppState extends State<CameraApp> {
  CameraController controller;

  @override
  void initState() {
    super.initState();
    controller = CameraController(cameras[0], ResolutionPreset.medium);
    controller.initialize().then((_) {
      if (!mounted) {
        return;
      }
      setState(() {});
    });
  }

  @override
  void dispose() {
    controller?.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    if (!controller.value.isInitialized) {
      return Container();
    }
    return AspectRatio(
        aspectRatio: controller.value.aspectRatio,
        child: CameraPreview(controller));
  }
}

```

if you're still experiencing this problem, please create a new issue and provide the information required in the template.
Thank you

</details>
