### ISSUE TITLE
Flutter has exited unexpectedly on flutter run -d <simulator id> command in Mac

### ISSUE THREAD

**Issue by MBhatt01** [flutter/flutter#29430]
## command

flutter run -d <simulator id>

## exception

ProcessException: ProcessException: Permission denied
  Command: /Users/m/development/flutter/bin/cache/dart-sdk/bin/pub --verbosity=warning get --no-precompile

```
#0      runCommandAndStreamOutput (package:flutter_tools/src/base/process.dart:140:27)
<asynchronous suspension>
#1      pub (package:flutter_tools/src/dart/pub.dart:155:18)
<asynchronous suspension>
#2      pubGet (package:flutter_tools/src/dart/pub.dart:104:13)
<asynchronous suspension>
#3      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:533:13)
<asynchronous suspension>
#4      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:482:33)
<asynchronous suspension>
#5      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:142:29)
<asynchronous suspension>
#6      _rootRun (dart:async/zone.dart:1124:13)
#7      _CustomZone.run (dart:async/zone.dart:1021:19)
#8      _runZoned (dart:async/zone.dart:1516:10)
#9      runZoned (dart:async/zone.dart:1463:12)
#10     AppContext.run (package:flutter_tools/src/base/context.dart:141:18)
<asynchronous suspension>
#11     FlutterCommand.run (package:flutter_tools/src/runner/flutter_command.dart:473:20)
#12     CommandRunner.runCommand (package:args/command_runner.dart:196:27)
<asynchronous suspension>
#13     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:396:21)
<asynchronous suspension>
#14     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:142:29)
<asynchronous suspension>
#15     _rootRun (dart:async/zone.dart:1124:13)
#16     _CustomZone.run (dart:async/zone.dart:1021:19)
#17     _runZoned (dart:async/zone.dart:1516:10)
#18     runZoned (dart:async/zone.dart:1463:12)
#19     AppContext.run (package:flutter_tools/src/base/context.dart:141:18)
<asynchronous suspension>
#20     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:356:19)
<asynchronous suspension>
#21     CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:111:29)
#22     new Future.sync (dart:async/future.dart:224:31)
#23     CommandRunner.run (package:args/command_runner.dart:111:11)
#24     FlutterCommandRunner.run (package:flutter_tools/src/runner/flutter_command_runner.dart:242:18)
#25     run.<anonymous closure> (package:flutter_tools/runner.dart:60:20)
<asynchronous suspension>
#26     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:142:29)
<asynchronous suspension>
#27     _rootRun (dart:async/zone.dart:1124:13)
#28     _CustomZone.run (dart:async/zone.dart:1021:19)
#29     _runZoned (dart:async/zone.dart:1516:10)
#30     runZoned (dart:async/zone.dart:1463:12)
#31     AppContext.run (package:flutter_tools/src/base/context.dart:141:18)
<asynchronous suspension>
#32     runInContext (package:flutter_tools/src/context_runner.dart:48:24)
<asynchronous suspension>
#33     run (package:flutter_tools/runner.dart:51:10)
#34     main (package:flutter_tools/executable.dart:52:9)
<asynchronous suspension>
#35     main (file:///b/rr/tmp6N7O2E/w/archive/flutter/packages/flutter_tools/bin/flutter_tools.dart:8:3)
#36     _startIsolate.<anonymous closure> (dart:isolate/runtime/libisolate_patch.dart:298:32)
#37     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:171:12)
```

## flutter doctor

```
[33m[!][39m Flutter (Channel stable, v1.2.1, on Mac OS X 10.14.3 18D109, locale en-US)
    [32m•[39m Flutter version 1.2.1 at /Users/m/development/flutter
    [32m•[39m Framework revision 8661d8aecd (4 weeks ago), 2019-02-14 19:19:53 -0800
    [32m•[39m Engine revision 3757390fa4
    [32m•[39m Dart version 2.1.2 (build 2.1.2-dev.0.0 0a7dcf17eb)
    [31m✗[39m Downloaded executables cannot execute on host.
      See https://github.com/flutter/flutter/issues/6207 for more information


[32m[✓][39m Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    [32m•[39m Android SDK at /Users/m/Library/Android/sdk
    [32m•[39m Android NDK location not configured (optional; useful for native profiling
      support)
    [32m•[39m Platform android-28, build-tools 28.0.3
    [32m•[39m ANDROID_HOME = /Users/m/Library/Android/sdk
    [32m•[39m Java binary at:
      /Library/Java/JavaVirtualMachines/jdk1.8.0_131.jdk/Contents/Home/bin/java
    [32m•[39m Java version Java(TM) SE Runtime Environment (build 1.8.0_131-b11)
    [32m•[39m All Android licenses accepted.

[32m[✓][39m iOS toolchain - develop for iOS devices (Xcode 10.1)
    [32m•[39m Xcode at /Applications/Xcode.app/Contents/Developer
    [32m•[39m Xcode 10.1, Build version 10B61
    [32m•[39m ios-deploy 1.9.4
    [32m•[39m CocoaPods version 1.6.1

[33m[!][39m Android Studio (not installed)
    [32m•[39m Android Studio not found; download from
      https://developer.android.com/studio/index.html
      (or visit https://flutter.io/setup/#android-setup for detailed
      instructions).

[32m[✓][39m Connected device (2 available)
    [32m•[39m iPhone       • <device id> • ios • iOS
      12.0.1
    [32m•[39m iPad Pro (9.7-inch) • < simulator id>     • ios • iOS
      11.1 (simulator)

[33m![39m Doctor found issues in 2 categories.
```

**Comment by iapicca** [comment]
Hi @MBhatt01 
are you still experiencing this issue with the latest version of Flutter?
If so can you please provide your `flutter doctor -v`?
Also, to better address the issue, would be helpful
if you could post a self contained app on github
or the steps to reproduce it.
Thank you

**Comment by iapicca** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact descriptions what happens, logs and the output of 'flutter doctor -v'  please.
All system setups can be slightly different so its always better to open new issues and reference related issues.
