### ISSUE TITLE
Strange Focus null context exception.  It should probably have more info.

### ISSUE THREAD

**Issue by apwilson** [flutter/flutter#2946]
```
E/flutter : [ERROR:dart_error.cc(17)] Unhandled exception:
E/flutter : 'packages/flutter/src/widgets/focus.dart': Failed assertion: line 142: 'context != null' is not true.
E/flutter : #0      _AssertionError._throwNew (dart:core-patch/errors_patch.dart:27)
E/flutter : #1      Focus._atScope (packages/flutter/src/widgets/focus.dart:142)
E/flutter : #2      _FocusState._ensureVisibleIfFocused (packages/flutter/src/widgets/focus.dart:292)
E/flutter : #3      _microtaskLoop (dart:async/schedule_microtask.dart:41)
E/flutter : #4      _startMicrotaskLoop (dart:async/schedule_microtask.dart:50)
```

**Comment by apwilson** [comment]
Still seeing this.  Any ideas for workaround?  Not sure how it can happen tbh.

**Comment by apwilson** [comment]
Full exception trace:

```
11:46:39.667: E/flutter : NoSuchMethodError: method not found: 'inheritFromWidgetOfExactType'
11:46:39.670: E/flutter : Receiver: null
11:46:39.671: E/flutter : Arguments: [Type: class '_FocusScope@17699407']
11:46:39.674: E/flutter : #0      Object._noSuchMethod (dart:core-patch/object_patch.dart:42)
11:46:39.677: E/flutter : #1      Object.noSuchMethod (dart:core-patch/object_patch.dart:45)
11:46:39.680: E/flutter : #2      Focus._atScope (/usr/local/google/home/anwilson/sysui/src/third_party/flutter/packages/flutter/lib/src/widgets/focus.dart:146)
11:46:39.683: E/flutter : #3      _FocusState._ensureVisibleIfFocused (/usr/local/google/home/anwilson/sysui/src/third_party/flutter/packages/flutter/lib/src/widgets/focus.dart:292)
11:46:39.686: E/flutter : #4      _microtaskLoop (dart:async/schedule_microtask.dart:41)
11:46:39.689: E/flutter : #5      _startMicrotaskLoop (dart:async/schedule_microtask.dart:50)
```

**Comment by abarth** [comment]
I'm not sure how to test given that there aren't repro instructions, but I'm going to guess that this is fixed by the new focus system now that we've decoupled querying the focus from these BuildContext objects that are turning up null.
