### ISSUE TITLE
using Column inside SliverList causes error

### ISSUE THREAD

**Issue by SahandAkbarzadeh** [flutter/flutter#29475]
## Steps to Reproduce

```dart
class CategoryScreen extends StatefulWidget {
  @override
  _CategoryScreenState createState() => _CategoryScreenState();
}

class _CategoryScreenState extends State<CategoryScreen> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: Colors.white,
      body: CustomScrollView(
        slivers: <Widget>[
          SliverAppBar(
            backgroundColor: Colors.white,
            actionsIconTheme: IconThemeData(color: Colors.black),
            primary: true,
          ),
          SliverList(
            delegate: SliverChildListDelegate([
              Column(
                mainAxisSize: MainAxisSize.max,
              )
            ]),
          )
        ],
      ),
    );
  }
}
```

## Logs

```
I/flutter (22750): ══╡ EXCEPTION CAUGHT BY RENDERING LIBRARY ╞═════════════════════════════════════════════════════════
I/flutter (22750): The following assertion was thrown during performLayout():
I/flutter (22750): 'package:flutter/src/rendering/object.dart': Failed assertion: line 1576 pos 12:
I/flutter (22750): '!_debugDoingThisLayout': is not true.
I/flutter (22750): 
I/flutter (22750): Either the assertion indicates an error in the framework itself, or we should provide substantially
I/flutter (22750): more information in this error message to help you determine and fix the underlying cause.
I/flutter (22750): In either case, please report this assertion by filing a bug on GitHub:
I/flutter (22750):   https://github.com/flutter/flutter/issues/new?template=BUG.md
I/flutter (22750): 
I/flutter (22750): When the exception was thrown, this was the stack:
I/flutter (22750): #2      RenderObject.layout (package:flutter/src/rendering/object.dart:1576:12)
I/flutter (22750): #3      RenderSliverList.performLayout (package:flutter/src/rendering/sliver_list.dart:164:27)
I/flutter (22750): #4      RenderObject.layout (package:flutter/src/rendering/object.dart:1632:7)
I/flutter (22750): #5      RenderViewportBase.layoutChildSequence (package:flutter/src/rendering/viewport.dart:407:13)
I/flutter (22750): #6      RenderViewport._attemptLayout (package:flutter/src/rendering/viewport.dart:1322:12)
I/flutter (22750): #7      RenderViewport.performLayout (package:flutter/src/rendering/viewport.dart:1240:20)
I/flutter (22750): #8      RenderObject.layout (package:flutter/src/rendering/object.dart:1632:7)
I/flutter (22750): #9      _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter (22750): #10     RenderObject.layout (package:flutter/src/rendering/object.dart:1632:7)
I/flutter (22750): #11     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter (22750): #12     RenderObject.layout (package:flutter/src/rendering/object.dart:1632:7)
I/flutter (22750): #13     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter (22750): #14     RenderObject.layout (package:flutter/src/rendering/object.dart:1632:7)
I/flutter (22750): #15     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter (22750): #16     RenderObject.layout (package:flutter/src/rendering/object.dart:1632:7)
I/flutter (22750): #17     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter (22750): #18     RenderObject.layout (package:flutter/src/rendering/object.dart:1632:7)
I/flutter (22750): #19     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter (22750): #20     RenderObject.layout (package:flutter/src/rendering/object.dart:1632:7)
I/flutter (22750): #21     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter (22750): #22     RenderObject.layout (package:flutter/src/rendering/object.dart:1632:7)
I/flutter (22750): #23     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter (22750): #24     RenderObject.layout (package:flutter/src/rendering/object.dart:1632:7)
I/flutter (22750): #25     MultiChildLayoutDelegate.layoutChild (package:flutter/src/rendering/custom_layout.dart:142:11)
I/flutter (22750): #26     _ScaffoldLayout.performLayout (package:flutter/src/material/scaffold.dart:431:7)
I/flutter (22750): #27     MultiChildLayoutDelegate._callPerformLayout (package:flutter/src/rendering/custom_layout.dart:212:7)
I/flutter (22750): #28     RenderCustomMultiChildLayoutBox.performLayout (package:flutter/src/rendering/custom_layout.dart:356:14)
I/flutter (22750): #29     RenderObject.layout (package:flutter/src/rendering/object.dart:1632:7)
I/flutter (22750): #30     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter (22750): #31     RenderObject.layout (package:flutter/src/rendering/object.dart:1632:7)
I/flutter (22750): #32     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter (22750): #33     _RenderCustomClip.performLayout (package:flutter/src/rendering/proxy_box.dart:1206:11)
I/flutter (22750): #34     RenderObject.layout (package:flutter/src/rendering/object.dart:1632:7)
I/flutter (22750): #35     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter (22750): #36     RenderObject.layout (package:flutter/src/rendering/object.dart:1632:7)
I/flutter (22750): #37     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter (22750): #38     RenderObject.layout (package:flutter/src/rendering/object.dart:1632:7)
I/flutter (22750): #39     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter (22750): #40     RenderObject.layout (package:flutter/src/rendering/object.dart:1632:7)
I/flutter (22750): #41     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter (22750): #42     RenderObject.layout (package:flutter/src/rendering/object.dart:1632:7)
I/flutter (22750): #43     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter (22750): #44     RenderObject.layout (package:flutter/src/rendering/object.dart:1632:7)
I/flutter (22750): #45     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter (22750): #46     RenderObject.layout (package:flutter/src/rendering/object.dart:1632:7)
I/flutter (22750): #47     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter (22750): #48     RenderObject.layout (package:flutter/src/rendering/object.dart:1632:7)
I/flutter (22750): #49     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter (22750): #50     RenderOffstage.performLayout (package:flutter/src/rendering/proxy_box.dart:3032:13)
I/flutter (22750): #51     RenderObject.layout (package:flutter/src/rendering/object.dart:1632:7)
I/flutter (22750): #52     RenderStack.performLayout (package:flutter/src/rendering/stack.dart:510:15)
I/flutter (22750): #53     RenderObject.layout (package:flutter/src/rendering/object.dart:1632:7)
I/flutter (22750): #54     __RenderTheatre&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter (22750): #55     RenderObject.layout (package:flutter/src/rendering/object.dart:1632:7)
I/flutter (22750): #56     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter (22750): #57     RenderObject.layout (package:flutter/src/rendering/object.dart:1632:7)
I/flutter (22750): #58     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter (22750): #59     RenderObject.layout (package:flutter/src/rendering/object.dart:1632:7)
I/flutter (22750): #60     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter (22750): #61     RenderObject.layout (package:flutter/src/rendering/object.dart:1632:7)
I/flutter (22750): #62     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter (22750): #63     RenderObject.layout (package:flutter/src/rendering/object.dart:1632:7)
I/flutter (22750): #64     RenderView.performLayout (package:flutter/src/rendering/view.dart:151:13)
I/flutter (22750): #65     RenderObject._layoutWithoutResize (package:flutter/src/rendering/object.dart:1507:7)
I/flutter (22750): #66     PipelineOwner.flushLayout (package:flutter/src/rendering/object.dart:766:18)
I/flutter (22750): #67     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding.drawFrame (package:flutter/src/rendering/binding.dart:336:19)
I/flutter (22750): #68     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding&WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:701:13)
I/flutter (22750): #69     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:275:5)
I/flutter (22750): #70     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:990:15)
I/flutter (22750): #71     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:930:9)
I/flutter (22750): #72     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.scheduleWarmUpFrame.<anonymous closure> (package:flutter/src/scheduler/binding.dart:751:7)
I/flutter (22750): #74     _Timer._runTimers (dart:isolate/runtime/lib/timer_impl.dart:382:19)
I/flutter (22750): #75     _Timer._handleMessage (dart:isolate/runtime/lib/timer_impl.dart:416:5)
I/flutter (22750): #76     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/lib/isolate_patch.dart:171:12)
I/flutter (22750): (elided 3 frames from class _AssertionError and package dart:async)
I/flutter (22750): 
I/flutter (22750): The following RenderObject was being processed when the exception was fired:
I/flutter (22750):   RenderSliverList#9dfd7 relayoutBoundary=up1 NEEDS-LAYOUT NEEDS-PAINT
I/flutter (22750):   creator: SliverList ← Viewport ← IgnorePointer-[GlobalKey#20ac1] ← Semantics ← Listener ←
I/flutter (22750):   _GestureSemantics ← RawGestureDetector-[LabeledGlobalKey<RawGestureDetectorState>#33cc1] ←
I/flutter (22750):   _ScrollableScope ← _ScrollSemantics-[GlobalKey#69e54] ← RepaintBoundary ← CustomPaint ←
I/flutter (22750):   RepaintBoundary ← ⋯
I/flutter (22750):   parentData: paintOffset=Offset(0.0, 80.0) (can use size)
I/flutter (22750):   constraints: SliverConstraints(AxisDirection.down, GrowthDirection.forward, ScrollDirection.idle,
I/flutter (22750):   scrollOffset: 0.0, remainingPaintExtent: 600.0, crossAxisExtent: 360.0, crossAxisDirection:
I/flutter (22750):   AxisDirection.right, viewportMainAxisExtent: 680.0, remainingCacheExtent: 850.0 cacheOrigin: 0.0 )
I/flutter (22750):   geometry: SliverGeometry(scrollExtent: Infinity, paintExtent: 600.0, maxPaintExtent: Infinity,
I/flutter (22750):   hasVisualOverflow: true, cacheExtent: 850.0)
I/flutter (22750):   currently live children: 0 to 0
I/flutter (22750): This RenderObject had the following descendants (showing up to depth 5):
I/flutter (22750):   RenderIndexedSemantics#284c8 relayoutBoundary=up2 NEEDS-LAYOUT NEEDS-PAINT
I/flutter (22750):     RenderRepaintBoundary#f40cc relayoutBoundary=up3 NEEDS-LAYOUT NEEDS-PAINT
I/flutter (22750):       RenderFlex#487f7 NEEDS-LAYOUT NEEDS-PAINT
I/flutter (22750): ════════════════════════════════════════════════════════════════════════════════════════════════════
Reloaded 2 of 470 libraries in 961ms.
```

```
[√] Flutter (Channel master, v1.3.3-pre.16, on Microsoft Windows [Version 10.0.17763.107], locale en-US)
    • Flutter version 1.3.3-pre.16 at C:\flutter
    • Framework revision d91cfffa50 (2 weeks ago), 2019-03-01 19:18:38 -0800
    • Engine revision 39c46dea4b
    • Dart version 2.2.1 (build 2.2.1-dev.0.0 7c70ab1817)

[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at *******\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = *******\sdk
    • Java binary at: *******\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)
    • All Android licenses accepted.

[√] Android Studio (version 3.3)
    • Android Studio at *****Android\Android Studio
    • Flutter plugin version 33.1.1
    • Dart plugin version 182.5215
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)

[√] VS Code (version 1.31.1)
    • VS Code at *****\Microsoft VS Code
    • Flutter extension version 2.24.0

[√] Connected device (1 available)
    • RNE L21 • F****1810********36 • android-arm64 • Android 8.0.0 (API 26)

• No issues found!
```

**Comment by AiHMin** [comment]
You should not use `Column` directly in `SliverList`.
`Column` is an expanded widget. That will make its children expand to fill the available space in the main axis (vertically for a Column). When you put a `Column` in `SliverList` or `ListView` without specified height, it will be crashed by infinity height. `SliverList` or `ListView` could not get the right scroll extent like the log showed.
You could put column's children out of it or you can wrap `Column` with `Container` and specified the height.
Hope that could help you.

**Comment by SahandAkbarzadeh** [comment]
@AiHMin thanks for the answer
I created the issue because of this:
```
I/flutter (22750): Either the assertion indicates an error in the framework itself, or we should provide substantially
I/flutter (22750): more information in this error message to help you determine and fix the underlying cause.
I/flutter (22750): In either case, please report this assertion by filing a bug on GitHub:
I/flutter (22750):   https://github.com/flutter/flutter/issues/new?template=BUG.md
```

**Comment by AiHMin** [comment]
Oh, I see. 😄

**Comment by Tevvek** [comment]
What about if we don't the height of the container, e.g. a `SliverList` with a `Stack` widget so the `Positioned` items are slightly over-posed. Same issue, no box constraints. Thanks!
