### ISSUE TITLE
Can't run flutter app on iphone using IntelliJ nor flutter run on command line but works using Xcode build

### ISSUE THREAD

**Issue by iankhou** [flutter/flutter#29495]
## Steps to Reproduce

1. Create flutter project
2. Try to debug using IntelliJ (fails with "could not install")
3. Navigate to project directory and run `flutter run` (fails)
4. Navigate to Xcode workspace and press run (succeeds)

## Logs

`IntelliJ Debug`
```
Launching lib/main.dart on Ian’s iPhone in debug mode...
Automatically signing iOS for device deployment using specified development team in Xcode project: 375NJ2YTYG
Running Xcode build...
Xcode build done.                                            6.7s
Installing and launching...
Could not install build/ios/iphoneos/Runner.app on eef0369132c053d82eccbf0d1c34fb26b65724fa.
Try launching Xcode and selecting "Product > Run" to fix the problem:
  open ios/Runner.xcworkspace

Error launching application on Ian’s iPhone.
```

`flutter -v run`
```
[  +31 ms] executing: [/Users/iankhou/development/flutter/] git rev-parse --abbrev-ref
--symbolic @{u}
[  +41 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/stable
[        ] executing: [/Users/iankhou/development/flutter/] git rev-parse --abbrev-ref
HEAD
[  +12 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] stable
[        ] executing: [/Users/iankhou/development/flutter/] git ls-remote --get-url
origin
[  +14 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[        ] executing: [/Users/iankhou/development/flutter/] git log -n 1
--pretty=format:%H
[  +15 ms] Exit code 0 from: git log -n 1 --pretty=format:%H
[        ] 8661d8aecd626f7f57ccbcb735553edc05a2e713
[        ] executing: [/Users/iankhou/development/flutter/] git log -n 1
--pretty=format:%ar
[  +13 ms] Exit code 0 from: git log -n 1 --pretty=format:%ar
[        ] 4 weeks ago
[        ] executing: [/Users/iankhou/development/flutter/] git describe --match v*.*.*
--first-parent --long --tags
[  +13 ms] Exit code 0 from: git describe --match v*.*.* --first-parent --long --tags
[        ] v1.2.1-0-g8661d8aec
[ +289 ms] executing: /Users/iankhou/Library/Android/sdk/platform-tools/adb devices -l
[   +8 ms] Exit code 0 from: /Users/iankhou/Library/Android/sdk/platform-tools/adb
devices -l
[   +1 ms] List of devices attached
[   +5 ms] executing: idevice_id -h
[  +61 ms] Error getting attached iOS device: ideviceinfo could not find device:
           No device found with udid eef0369132c053d82eccbf0d1c34fb26b65724fa, is it
           plugged in?

[   +3 ms] /usr/bin/xcrun simctl list --json devices
[ +269 ms] No connected devices.
[        ] Run 'flutter emulators' to list and start any available device emulators.
[        ] If you expected your device to be detected, please run "flutter doctor" to
diagnose
[   +1 ms] potential issues, or visit https://flutter.io/setup/ for troubleshooting tips.
[  +14 ms] "flutter run" took 580ms.
[        ] "flutter run" took 580ms.

#0      throwToolExit (package:flutter_tools/src/base/common.dart:24:3)
#1      RunCommand.validateCommand (package:flutter_tools/src/commands/run.dart:240:7)
<asynchronous suspension>
#2      FlutterCommand.verifyThenRunCommand
(package:flutter_tools/src/runner/flutter_command.dart:525:11)
<asynchronous suspension>
#3      FlutterCommand.run.<anonymous closure>
(package:flutter_tools/src/runner/flutter_command.dart:482:33)
<asynchronous suspension>
#4      AppContext.run.<anonymous closure>
(package:flutter_tools/src/base/context.dart:142:29)
<asynchronous suspension>
#5      _rootRun (dart:async/zone.dart:1124:13)
#6      _CustomZone.run (dart:async/zone.dart:1021:19)
#7      _runZoned (dart:async/zone.dart:1516:10)
#8      runZoned (dart:async/zone.dart:1463:12)
#9      AppContext.run (package:flutter_tools/src/base/context.dart:141:18)
<asynchronous suspension>
#10     FlutterCommand.run (package:flutter_tools/src/runner/flutter_command.dart:473:20)
#11     CommandRunner.runCommand (package:args/command_runner.dart:196:27)
<asynchronous suspension>
#12     FlutterCommandRunner.runCommand.<anonymous closure>
(package:flutter_tools/src/runner/flutter_command_runner.dart:396:21)
<asynchronous suspension>
#13     AppContext.run.<anonymous closure>
(package:flutter_tools/src/base/context.dart:142:29)
<asynchronous suspension>
#14     _rootRun (dart:async/zone.dart:1124:13)
#15     _CustomZone.run (dart:async/zone.dart:1021:19)
#16     _runZoned (dart:async/zone.dart:1516:10)
#17     runZoned (dart:async/zone.dart:1463:12)
#18     AppContext.run (package:flutter_tools/src/base/context.dart:141:18)
<asynchronous suspension>
#19     FlutterCommandRunner.runCommand
(package:flutter_tools/src/runner/flutter_command_runner.dart:356:19)
<asynchronous suspension>
#20     CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:111:29)
#21     new Future.sync (dart:async/future.dart:224:31)
#22     CommandRunner.run (package:args/command_runner.dart:111:11)
#23     FlutterCommandRunner.run
(package:flutter_tools/src/runner/flutter_command_runner.dart:242:18)
#24     run.<anonymous closure> (package:flutter_tools/runner.dart:60:20)
<asynchronous suspension>
#25     AppContext.run.<anonymous closure>
(package:flutter_tools/src/base/context.dart:142:29)
<asynchronous suspension>
#26     _rootRun (dart:async/zone.dart:1124:13)
#27     _CustomZone.run (dart:async/zone.dart:1021:19)
#28     _runZoned (dart:async/zone.dart:1516:10)
#29     runZoned (dart:async/zone.dart:1463:12)
#30     AppContext.run (package:flutter_tools/src/base/context.dart:141:18)
<asynchronous suspension>
#31     runInContext (package:flutter_tools/src/context_runner.dart:48:24)
<asynchronous suspension>
#32     run (package:flutter_tools/runner.dart:51:10)
#33     main (package:flutter_tools/executable.dart:52:9)
<asynchronous suspension>
#34     main
(file:///Users/iankhou/development/flutter/packages/flutter_tools/bin/flutter_tools.dart:
8:3)
#35     _startIsolate.<anonymous closure>
(dart:isolate/runtime/libisolate_patch.dart:298:32)
#36     _RawReceivePortImpl._handleMessage
(dart:isolate/runtime/libisolate_patch.dart:171:12)
```

`flutter doctor -v`
```
[✓] Flutter (Channel stable, v1.2.1, on Mac OS X 10.14.3
    18D109, locale en-US)
    • Flutter version 1.2.1 at
      /Users/iankhou/development/flutter
    • Framework revision 8661d8aecd (4 weeks ago),
      2019-02-14 19:19:53 -0800
    • Engine revision 3757390fa4
    • Dart version 2.1.2 (build 2.1.2-dev.0.0 0a7dcf17eb)

[✓] Android toolchain - develop for Android devices            (Android SDK version 28.0.3)
    • Android SDK at /Users/iankhou/Library/Android/sdk
    • Android NDK location not configured (optional; useful
      for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_152-release-1248-b01)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.1, Build version 10B61
    • ios-deploy 1.9.4
    • CocoaPods version 1.6.1

[✓] Android Studio (version 3.3)
    • Android Studio at /Applications/Android
      Studio.app/Contents
    • Flutter plugin version 33.4.1
    • Dart plugin version 182.5215
    • Java version OpenJDK Runtime Environment (build
      1.8.0_152-release-1248-b01)

[✓] IntelliJ IDEA Community Edition (version 2018.3.3)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 33.4.2
    • Dart plugin version 183.5901

[✓] Connected device (1 available)
    • Ian’s iPhone •
      eef0369132c053d82eccbf0d1c34fb26b65724fa • ios • iOS
      12.1.4

• No issues found!
```

**Comment by fireteam99** [comment]
I have the same problem.

**Comment by Banerus** [comment]
https://github.com/flutter/flutter/issues/29437

**Comment by keitoro** [comment]
same problem!

**Comment by jmagman** [comment]
```
[  +61 ms] Error getting attached iOS device: ideviceinfo could not find device:
           No device found with udid eef0369132c053d82eccbf0d1c34fb26b65724fa, is it
           plugged in?
```
Probably resolved with https://github.com/flutter/flutter/pull/49854.
