### ISSUE TITLE
Flutter no longer gives nice blue widget when using ChildViewConnections in skyshell

### ISSUE THREAD

**Issue by apwilson** [flutter/flutter#2949]
```
I/flutter : -- EXCEPTION CAUGHT BY WIDGETS LIBRARY ---------------------------------
I/flutter : Exception caught while building ChildView
I/flutter : The null object does not have a method 'getContainer'.
I/flutter : NoSuchMethodError: method not found: 'getContainer'
I/flutter : Receiver: null
I/flutter : Arguments: [Instance of 'ViewContainerProxy']
I/flutter : Stack trace:
I/flutter : #0      Object._noSuchMethod (dart:core-patch/object_patch.dart:42)
I/flutter : #1      Object.noSuchMethod (dart:core-patch/object_patch.dart:45)
I/flutter : #2      _initViewContainer (packages/flutter/src/rendering/child_view.dart:40)
I/flutter : #3      _viewContainer (packages/flutter/src/rendering/child_view.dart:45)
I/flutter : #4      _viewContainer (packages/flutter/src/rendering/child_view.dart:45)
I/flutter : #5      ChildViewConnection._addChildToViewHost (packages/flutter/src/rendering/child_view.dart:123)
I/flutter : #6      ChildViewConnection._attach (packages/flutter/src/rendering/child_view.dart:152)
I/flutter : #7      RenderChildView.attach (packages/flutter/src/rendering/child_view.dart:235)
I/flutter : #8      AbstractNode.adoptChild (packages/flutter/src/rendering/node.dart:108)
I/flutter : #9      RenderObject.adoptChild (packages/flutter/src/rendering/object.dart:847)
I/flutter : #10     RenderBox&ContainerRenderObjectMixin.insert (packages/flutter/src/rendering/object.dart:1969)
```

**Comment by abarth** [comment]
Will fix.
