### ISSUE TITLE
Have problems with Navigator.popUntil() function

### ISSUE THREAD

**Issue by AndreiNikitin** [flutter/flutter#29506]
## Steps to Reproduce

code example
https://gist.github.com/AndreiNikitin/f496bc3fecf1c97f347d7259e1a3106e

1. I have several routes. The initial one is Routes.HOME
2. From initial route I navigate to Routes.ADD_DEVICE_STEP_ONE => Routes.ADD_DEVICE_STEP_TWO => Routes.ADD_DEVICE_STEP_THREE
3. On step three I show a dialog to user (cancel confirmation) when he presses cancel button
4. If user pressed "OK" button in dialog I execute funtion 
```
Navigator.of(context).popUntil(ModalRoute.withName(Routes.HOME))
```
5. And every time I get an exception "Bad state: Future already completed" and "Failed assertion: line 2106 pos 12: '!_debugLocked': is not true."

What is the problem with this function. Is it a bug or does this error happens because of inappropriate use of function?

P.S. This only happened if "onGenerateRoute" table used. If "routes" is used - everything works fine
## Logs

```
I/flutter (16589): ══╡ EXCEPTION CAUGHT BY GESTURE ╞═══════════════════════════════════════════════════════════════════
I/flutter (16589): The following StateError was thrown while handling a gesture:
I/flutter (16589): Bad state: Future already completed
I/flutter (16589): 
I/flutter (16589): When the exception was thrown, this was the stack:
I/flutter (16589): #1      Route.didComplete (package:flutter/src/widgets/navigator.dart:187:19)
I/flutter (16589): #2      Route.didPop (package:flutter/src/widgets/navigator.dart:175:5)
I/flutter (16589): #3      OverlayRoute.didPop (package:flutter/src/widgets/routes.dart:61:36)
I/flutter (16589): #4      TransitionRoute.didPop (package:flutter/src/widgets/routes.dart:211:18)
I/flutter (16589): #5      _ModalRoute&TransitionRoute&LocalHistoryRoute.didPop (package:flutter/src/widgets/routes.dart:527:18)
I/flutter (16589): #6      NavigatorState.pop (package:flutter/src/widgets/navigator.dart:1935:15)
I/flutter (16589): #7      NavigatorState.popUntil (package:flutter/src/widgets/navigator.dart:1975:7)
I/flutter (16589): #8      BodyWidgetState._showCancelDialog.<anonymous closure>.<anonymous closure> (package:SmartLED/src/presentation/main/device_add/step_3/body_widget.dart:188:37)
I/flutter (16589): #9      AppDialog.build.<anonymous closure> (package:SmartLED/src/presentation/common/dialogs.dart:44:34)
I/flutter (16589): #10     _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:513:14)
I/flutter (16589): #11     _InkResponseState.build.<anonymous closure> (package:flutter/src/material/ink_well.dart:568:30)
I/flutter (16589): #12     GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:120:24)
I/flutter (16589): #13     TapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:242:9)
I/flutter (16589): #14     TapGestureRecognizer.handlePrimaryPointer (package:flutter/src/gestures/tap.dart:175:7)
I/flutter (16589): #15     PrimaryPointerGestureRecognizer.handleEvent (package:flutter/src/gestures/recognizer.dart:369:9)
I/flutter (16589): #16     PointerRouter._dispatch (package:flutter/src/gestures/pointer_router.dart:73:12)
I/flutter (16589): #17     PointerRouter.route (package:flutter/src/gestures/pointer_router.dart:101:11)
I/flutter (16589): #18     _WidgetsFlutterBinding&BindingBase&GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:214:19)
I/flutter (16589): #19     _WidgetsFlutterBinding&BindingBase&GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:192:22)
I/flutter (16589): #20     _WidgetsFlutterBinding&BindingBase&GestureBinding._handlePointerEvent (package:flutter/src/gestures/binding.dart:149:7)
I/flutter (16589): #21     _WidgetsFlutterBinding&BindingBase&GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:101:7)
I/flutter (16589): #22     _WidgetsFlutterBinding&BindingBase&GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:85:7)
I/flutter (16589): #26     _invoke1 (dart:ui/hooks.dart:223:10)
I/flutter (16589): #27     _dispatchPointerDataPacket (dart:ui/hooks.dart:144:5)
I/flutter (16589): (elided 4 frames from package dart:async)
I/flutter (16589): 
I/flutter (16589): Handler: onTap
I/flutter (16589): Recognizer:
I/flutter (16589):   TapGestureRecognizer#e61f2(debugOwner: GestureDetector, state: accepted, won arena, finalPosition:
I/flutter (16589):   Offset(277.1, 399.1), sent tap down)
I/flutter (16589): ════════════════════════════════════════════════════════════════════════════════════════════════════
I/flutter (16589): Another exception was thrown: 'package:flutter/src/widgets/navigator.dart': Failed assertion: line 2106 pos 12: '!_debugLocked': is not true.

```

## flutter analyze

```

   info - The class 'Future' was not exported from 'dart:core' until version 2.1, but this code is required to be able
          to run on earlier versions - lib\src\data\database\database.dart:16:3 - sdk_version_async_exported_from_core
   info - The class 'Future' was not exported from 'dart:core' until version 2.1, but this code is required to be able
          to run on earlier versions - lib\src\data\database\migration.dart:3:1 - sdk_version_async_exported_from_core
  

2 issues found. (ran in 10.9s)

```

## flutter doctor
```
[√] Flutter (Channel stable, v1.2.1, on Microsoft Windows [Version 10.0.17134.648], locale ru-RU)
    • Flutter version 1.2.1 at E:\flutter
    • Framework revision 8661d8aecd (4 weeks ago), 2019-02-14 19:19:53 -0800
    • Engine revision 3757390fa4
    • Dart version 2.1.2 (build 2.1.2-dev.0.0 0a7dcf17eb)

[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at E:\AndroidSDK
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = E:\AndroidSDK
    • Java binary at: E:\AndroidStudio_3_3_canary_10\android-studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)
    • All Android licenses accepted.

[√] Android Studio (version 3.3)
    • Android Studio at E:\AndroidStudio_3_3_canary_10\android-studio
    • Flutter plugin version 31.1.3
    • Dart plugin version 182.5124
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)

[!] VS Code (version 1.27.1)
    • VS Code at C:\Users\ANDRE\AppData\Local\Programs\Microsoft VS Code
    X Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[√] Connected device (1 available)
    • Redmi Note 4 • 4937c6e19904 • android-arm64 • Android 7.0 (API 24)

! Doctor found issues in 1 category.

```

**Comment by AndreiNikitin** [comment]
Just figured it out. If you use custom PageRouteBuilder and named routes you have to pass RouteSettings to constructor. And it works!
