### ISSUE TITLE
Android: finger down when minimizing app (press square) results in exceptions with no recovery

### ISSUE THREAD

**Issue by apwilson** [flutter/flutter#2951]
Test app:

```
void main() {
  runApp(new Block(children:[new NetworkImage(src:'https://i.ytimg.com/vi/tntOCGkgt98/maxresdefault.jpg'), new NetworkImage(src:'https://i.ytimg.com/vi/tntOCGkgt98/maxresdefault.jpg')]));
}

```

Initial exception when lifting finger after minimize:

```
E/flutter : [ERROR:dart_error.cc(17)] Unhandled exception:
E/flutter : 'packages/flutter/src/gestures/binding.dart': Failed assertion: line 67: 'event.down == _hitTests.containsKey(event.pointer)' is not true.
E/flutter : #0      _AssertionError._throwNew (dart:core-patch/errors_patch.dart:27)
E/flutter : #1      BindingBase&Scheduler&Gesturer._handlePointerEvent (packages/flutter/src/gestures/binding.dart:67)
E/flutter : #2      BindingBase&Scheduler&Gesturer._handlePointerPacket (packages/flutter/src/gestures/binding.dart:44)
E/flutter : #3      _dispatchPointerPacket 
```

Exception when you try touching screen after maximizing again:

```
(file:///b/build/slave/Linux_Engine/build/src/out/android_Release/gen/sky/bindings/hooks.dart:43)
E/flutter : [ERROR:dart_error.cc(17)] Unhandled exception:
E/flutter : 'packages/flutter/src/gestures/converter.dart': Failed assertion: line 48: '!_pointers.containsKey(datum.pointer)' is not true.
E/flutter : #0      _AssertionError._throwNew (dart:core-patch/errors_patch.dart:27)
E/flutter : #1      PointerEventConverter.expand.<expand_sync_body> (packages/flutter/src/gestures/converter.dart:48)
E/flutter : #2      _SyncIterator.moveNext (dart:core-patch/core_patch.dart:65)
E/flutter : #3      BindingBase&Scheduler&Gesturer._handlePointerPacket (packages/flutter/src/gestures/binding.dart:43)
E/flutter : #4      _dispatchPointerPacket (file:///b/build/slave/Linux_Engine/build/src/out/android_Release/gen/sky/bindings/hooks.dart:43)

```

And:

```
E/flutter : [ERROR:dart_error.cc(17)] Unhandled exception:
E/flutter : 'packages/flutter/src/gestures/converter.dart': Failed assertion: line 95: 'state.down' is not true.
E/flutter : #0      _AssertionError._throwNew (dart:core-patch/errors_patch.dart:27)
E/flutter : #1      PointerEventConverter.expand.<expand_sync_body> (packages/flutter/src/gestures/converter.dart:95)
E/flutter : #2      _SyncIterator.moveNext (dart:core-patch/core_patch.dart:65)
E/flutter : #3      BindingBase&Scheduler&Gesturer._handlePointerPacket (packages/flutter/src/gestures/binding.dart:43)
E/flutter : #4      _dispatchPointerPacket (file:///b/build/slave/Linux_Engine/build/src/out/android_Release/gen/sky/bindings/hooks.dart:43)
```

**Comment by apwilson** [comment]
In checked mode it'll shut any touch events down.  In non-checked mode it'll actually cause scrolling behaviour to change (scrolls don't have inertia, they just stop immediately on finger up).

**Comment by eseidelGoogle** [comment]
It's not clear to me how to repro this?  Is this still an issue?

**Comment by apwilson** [comment]
I think this was fixed.
