### ISSUE TITLE
 flutter run --release crash with flutter 1.2

### ISSUE THREAD

**Issue by zhileiliu** [flutter/flutter#29526]
Unhandled exception:
Assertion failed.
#0      assertx (package:vm/transformations/type_flow/utils.dart:34:5)
#1      _ClassHierarchyCache.addAllocatedClass (package:vm/transformations/type_flow/analysis.dart:1019:5)
#2      TypeFlowAnalysis.addAllocatedClass (package:vm/transformations/type_flow/analysis.dart:1514:27)
#3      PragmaEntryPointsVisitor.visitConstructor (package:vm/transformations/type_flow/native_code.dart:101:19)
#4      Constructor.accept (package:kernel/ast.dart:1401:32)
#5      visitList (package:kernel/ast.dart:5696:14)
#6      Class.visitChildren (package:kernel/ast.dart:1053:5)
#7      PragmaEntryPointsVisitor.visitClass (package:vm/transformations/type_flow/native_code.dart:69:11)
#8      Class.accept (package:kernel/ast.dart:1006:30)
#9      visitList (package:kernel/ast.dart:5696:14)
#10     Library.visitChildren (package:kernel/ast.dart:442:5)
#11     RecursiveVisitor.defaultNode (package:kernel/visitor.dart:407:10)
#12     Visitor.defaultTreeNode (package:kernel/visitor.dart:324:39)
#13     TreeVisitor.visitLibrary (package:kernel/visitor.dart:238:35)
#14     Library.accept (package:kernel/ast.dart:435:30)
#15     visitList (package:kernel/ast.dart:5696:14)
#16     Component.visitChildren (package:kernel/ast.dart:5563:5)
#17     RecursiveVisitor.defaultNode (package:kernel/visitor.dart:407:10)
#18     Visitor.defaultTreeNode (package:kernel/visitor.dart:324:39)
#19     TreeVisitor.visitComponent (package:kernel/visitor.dart:250:39)
#20     Component.accept (package:kernel/ast.dart:5560:30)
#21     new TypeFlowAnalysis (package:vm/transformations/type_flow/analysis.dart:1368:15)
#22     transformComponent (package:vm/transformations/type_flow/transformer.dart:58:32)
#23     _runGlobalTransformations (package:vm/kernel_front_end.dart:357:5)
<asynchronous suspension>
#24     compileToKernel (package:vm/kernel_front_end.dart:297:11)
<asynchronous suspension>
#25     FrontendCompiler.compile.<anonymous closure> (package:vm/frontend_server.dart:348:56)
#26     new Future.<anonymous closure> (dart:async/future.dart:176:37)
#27     _rootRun (dart:async/zone.dart:1120:38)
#28     _CustomZone.run (dart:async/zone.dart:1021:19)
#29     _CustomZone.runGuarded (dart:async/zone.dart:923:7)
#30     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:963:23)
#31     _rootRun (dart:async/zone.dart:1124:13)
#32     _CustomZone.run (dart:async/zone.dart:1021:19)
#33     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:947:23)
#34     Timer._createTimer.<anonymous closure> (dart:async/runtime/libtimer_patch.dart:21:15)
#35     _Timer._runTimers (dart:isolate/runtime/libtimer_impl.dart:382:19)
#36     _Timer._handleMessage (dart:isolate/runtime/libtimer_impl.dart:416:5)
#37     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:171:12)

**Comment by zhileiliu** [comment]
solution:
remove the entry-point from abstract class constructor
