### ISSUE TITLE
crash occurs in FlutterView AccessibilityBridge

### ISSUE THREAD

**Issue by tylorvan** [flutter/flutter#29535]
## Logs

java.lang.NullPointerException: Attempt to invoke virtual method 'void io.flutter.view.FlutterNativeView.setMessageHandler(java.lang.String, io.flutter.plugin.common.BinaryMessenger$BinaryMessageHandler)' on a null object reference
	at io.flutter.view.FlutterView.setMessageHandler(FlutterView.java:1059)
	at io.flutter.plugin.common.BasicMessageChannel.setMessageHandler(BasicMessageChannel.java:84)
	at io.flutter.view.AccessibilityBridge.setAccessibilityEnabled(AccessibilityBridge.java:124)
	at io.flutter.view.FlutterView.onAccessibilityStateChanged(FlutterView.java:934)
	at android.view.accessibility.AccessibilityManager.lambda$notifyAccessibilityStateChanged$0(AccessibilityManager.java:1152)
	at android.view.accessibility.-$$Lambda$AccessibilityManager$yzw5NYY7_MfAQ9gLy3mVllchaXo.run(Unknown Source:4)
	at android.os.Handler.handleCallback(Handler.java:891)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:207)
	at android.app.ActivityThread.main(ActivityThread.java:7539)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:958)
Back traces end.

**Comment by valterh4ck3r** [comment]
Same error.

**Comment by jekinchen** [comment]
Same error

**Comment by xster** [comment]
Merging into #33173
