### ISSUE TITLE
ImageSource.camera not able to return image. App get crash.

### ISSUE THREAD

**Issue by SameerDonga** [flutter/flutter#29590]
Here I'm not able to get captured an image using Camera.
Android Version: Pai.

**Comment by jonahwilliams** [comment]
@SameerDonga in order to help you out we'll need more information. Please include the output of `flutter doctor -v` as well as the version of the image picker plugin you are using. If there are any stack traces those would also be helpful, as well as a small sample that reproduces the problem.

**Comment by janfryauf** [comment]
I'm having the same issue
App has always camera permissions off

I tried to add
<uses-permission android:name="android.permission.CAMERA" />
and also
<uses-feature android:name="android.hardware.camera" android:required="true" />
but still getting the same crash

```
E/MethodChannel#plugins.flutter.io/image_picker(31290): Failed to handle method call
E/MethodChannel#plugins.flutter.io/image_picker(31290): java.lang.SecurityException: Permission Denial: starting Intent { act=android.media.action.IMAGE_CAPTURE flg=0x3 cmp=com.google.android.GoogleCamera/com.android.camera.activity.CaptureActivity clip={text/uri-list U:content://com.testapp.app.flutter.image_provider/external_files/Android/data/com.testapp.app/files/Pictures/eb824705-a4bf-4e0b-926b-ee774992a0ef4977433902347943292.jpg} (has extras) } from ProcessRecord{1a5bfe4 31290:com.testapp.app/u0a265} (pid=31290, uid=10265) with revoked permission android.permission.CAMERA
E/MethodChannel#plugins.flutter.io/image_picker(31290): 	at android.os.Parcel.createException(Parcel.java:1950)
E/MethodChannel#plugins.flutter.io/image_picker(31290): 	at android.os.Parcel.readException(Parcel.java:1918)
E/MethodChannel#plugins.flutter.io/image_picker(31290): 	at android.os.Parcel.readException(Parcel.java:1868)
E/MethodChannel#plugins.flutter.io/image_picker(31290): 	at android.app.IActivityManager$Stub$Proxy.startActivity(IActivityManager.java:3756)
E/MethodChannel#plugins.flutter.io/image_picker(31290): 	at android.app.Instrumentation.execStartActivity(Instrumentation.java:1669)
E/MethodChannel#plugins.flutter.io/image_picker(31290): 	at android.app.Activity.startActivityForResult(Activity.java:4587)
E/MethodChannel#plugins.flutter.io/image_picker(31290): 	at android.app.Activity.startActivityForResult(Activity.java:4545)
E/MethodChannel#plugins.flutter.io/image_picker(31290): 	at io.flutter.plugins.imagepicker.ImagePickerDelegate.launchTakeImageWithCameraIntent(ImagePickerDelegate.java:282)
E/MethodChannel#plugins.flutter.io/image_picker(31290): 	at io.flutter.plugins.imagepicker.ImagePickerDelegate.takeImageWithCamera(ImagePickerDelegate.java:263)
E/MethodChannel#plugins.flutter.io/image_picker(31290): 	at io.flutter.plugins.imagepicker.ImagePickerPlugin.onMethodCall(ImagePickerPlugin.java:64)
E/MethodChannel#plugins.flutter.io/image_picker(31290): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:201)
E/MethodChannel#plugins.flutter.io/image_picker(31290): 	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:88)
E/MethodChannel#plugins.flutter.io/image_picker(31290): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:219)
E/MethodChannel#plugins.flutter.io/image_picker(31290): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/MethodChannel#plugins.flutter.io/image_picker(31290): 	at android.os.MessageQueue.next(MessageQueue.java:326)
E/MethodChannel#plugins.flutter.io/image_picker(31290): 	at android.os.Looper.loop(Looper.java:160)
E/MethodChannel#plugins.flutter.io/image_picker(31290): 	at android.app.ActivityThread.main(ActivityThread.java:6718)
E/MethodChannel#plugins.flutter.io/image_picker(31290): 	at java.lang.reflect.Method.invoke(Native Method)
E/MethodChannel#plugins.flutter.io/image_picker(31290): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
E/MethodChannel#plugins.flutter.io/image_picker(31290): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
E/MethodChannel#plugins.flutter.io/image_picker(31290): Caused by: android.os.RemoteException: Remote stack trace:
E/MethodChannel#plugins.flutter.io/image_picker(31290): 	at com.android.server.am.ActivityStackSupervisor.checkStartAnyActivityPermission(ActivityStackSupervisor.java:1779)
E/MethodChannel#plugins.flutter.io/image_picker(31290): 	at com.android.server.am.ActivityStarter.startActivity(ActivityStarter.java:725)
E/MethodChannel#plugins.flutter.io/image_picker(31290): 	at com.android.server.am.ActivityStarter.startActivity(ActivityStarter.java:551)
E/MethodChannel#plugins.flutter.io/image_picker(31290): 	at com.android.server.am.ActivityStarter.startActivityMayWait(ActivityStarter.java:1156)
E/MethodChannel#plugins.flutter.io/image_picker(31290): 	at com.android.server.am.ActivityStarter.execute(ActivityStarter.java:490)
E/MethodChannel#plugins.flutter.io/image_picker(31290): 
D/AndroidRuntime(31290): Shutting down VM
E/AndroidRuntime(31290): FATAL EXCEPTION: main
E/AndroidRuntime(31290): Process: com.testapp.app, PID: 31290
E/AndroidRuntime(31290): java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=2343, result=0, data=null} to activity {com.testapp.app/com.testapp.app.MainActivity}: java.lang.IllegalStateException: Reply already submitted
E/AndroidRuntime(31290): 	at android.app.ActivityThread.deliverResults(ActivityThread.java:4398)
E/AndroidRuntime(31290): 	at android.app.ActivityThread.handleSendResult(ActivityThread.java:4440)
E/AndroidRuntime(31290): 	at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:49)
E/AndroidRuntime(31290): 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
E/AndroidRuntime(31290): 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
E/AndroidRuntime(31290): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1816)
E/AndroidRuntime(31290): 	at android.os.Handler.dispatchMessage(Handler.java:106)
E/AndroidRuntime(31290): 	at android.os.Looper.loop(Looper.java:193)
E/AndroidRuntime(31290): 	at android.app.ActivityThread.main(ActivityThread.java:6718)
E/AndroidRuntime(31290): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(31290): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
E/AndroidRuntime(31290): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
E/AndroidRuntime(31290): Caused by: java.lang.IllegalStateException: Reply already submitted
E/AndroidRuntime(31290): 	at io.flutter.embedding.engine.dart.DartMessenger$Reply.reply(DartMessenger.java:124)
E/AndroidRuntime(31290): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler$1.success(MethodChannel.java:204)
E/AndroidRuntime(31290): 	at io.flutter.plugins.imagepicker.ImagePickerDelegate.finishWithSuccess(ImagePickerDelegate.java:462)
E/AndroidRuntime(31290): 	at io.flutter.plugins.imagepicker.ImagePickerDelegate.handleCaptureImageResult(ImagePickerDelegate.java:405)
E/AndroidRuntime(31290): 	at io.flutter.plugins.imagepicker.ImagePickerDelegate.onActivityResult(ImagePickerDelegate.java:354)
E/AndroidRuntime(31290): 	at io.flutter.app.FlutterPluginRegistry.onActivityResult(FlutterPluginRegistry.java:222)
E/AndroidRuntime(31290): 	at io.flutter.app.FlutterActivityDelegate.onActivityResult(FlutterActivityDelegate.java:143)
E/AndroidRuntime(31290): 	at io.flutter.app.FlutterActivity.onActivityResult(FlutterActivity.java:142)
E/AndroidRuntime(31290): 	at android.app.Activity.dispatchActivityResult(Activity.java:7462)
E/AndroidRuntime(31290): 	at android.app.ActivityThread.deliverResults(ActivityThread.java:4391)
E/AndroidRuntime(31290): 	... 11 more
I/Process (31290): Sending signal. PID: 31290 SIG: 9
Lost connection to device.
```

```
Flutter 1.4.9-hotfix.1 • channel beta • https://github.com/flutter/flutter.git
Framework • revision 88fa7ea403 (6 days ago) • 2019-04-11 14:01:46 -0700
Engine • revision 4737fc5cd8
Tools • Dart 2.2.1 (build 2.2.1-dev.4.0 None)

Running flutter doctor...
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel beta, v1.4.9-hotfix.1, on Mac OS X 10.14.4 18E226, locale en-CZ)
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[✓] iOS toolchain - develop for iOS devices (Xcode 10.1)
[✓] Android Studio (version 3.3)
[!] VS Code (version 1.30.2)
[✓] Connected device (2 available)
```
