### ISSUE TITLE
My apps crashes while opening up the webview, it works fine with flutter_webview_plugin but crashes with webview_flutter

### ISSUE THREAD

**Issue by Sarthaktydy** [flutter/flutter#29660]
```
`W/cr_media(16946): Requires BLUETOOTH permission
W/VideoCapabilities(16946): Unsupported mime video/divx
W/VideoCapabilities(16946): Unsupported mime video/divx311
W/VideoCapabilities(16946): Unsupported mime video/divx4
W/VideoCapabilities(16946): Unrecognized profile 4 for video/hevc
W/VideoCapabilities(16946): Unrecognized profile/level 0/3 for video/mpeg2
W/VideoCapabilities(16946): Unrecognized profile/level 0/3 for video/mpeg2
W/VideoCapabilities(16946): Unsupported mime video/x-ms-wmv
W/VideoCapabilities(16946): Unsupported mime video/x-ms-wmv
I/VideoCapabilities(16946): Unsupported profile 4 for video/mp4v-es
W/cr_CrashFileManager(16946): /data/user/0/**********/cache/WebView/Crash Reports does not exist or is not a directory
D/NetworkSecurityConfig(16946): No Network Security Config specified, using platform default
D/AndroidRuntime(16946): Shutting down VM
E/AndroidRuntime(16946): FATAL EXCEPTION: main
E/AndroidRuntime(16946): Process: ***********, PID: *****
E/AndroidRuntime(16946): java.lang.IllegalArgumentException: reasonPhrase can't be empty.
E/AndroidRuntime(16946): 	at android.webkit.WebResourceResponse.setStatusCodeAndReasonPhrase(WebResourceResponse.java:139)
E/AndroidRuntime(16946): 	at android.webkit.WebResourceResponse.<init>(WebResourceResponse.java:77)
E/AndroidRuntime(16946): 	at xH.a(SourceFile:286)
E/AndroidRuntime(16946): 	at ayK.handleMessage(SourceFile:67)
E/AndroidRuntime(16946): 	at android.os.Handler.dispatchMessage(Handler.java:106)
E/AndroidRuntime(16946): 	at android.os.Looper.loop(Looper.java:193)
E/AndroidRuntime(16946): 	at android.app.ActivityThread.main(ActivityThread.java:6912)
E/AndroidRuntime(16946): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(16946): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:537)
E/AndroidRuntime(16946): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
W/OPDiagnose(16946): getService:OPDiagnoseService NULL
D/OSTracker(16946): OS Event: crash
I/Process (16946): Sending signal. PID: 16946 SIG: 9
`
```

**Comment by tudorcodarnai** [comment]
How did you solve this?
