### ISSUE TITLE
Appbundle version crashing on start for some devices

### ISSUE THREAD

**Issue by benadrasni** [flutter/flutter#29740]
Flutter v1.3.13
I am creating releases with "flutter build appbundle". Since two days ago it was creating apks only for armeabi-v7a. After update to the latest on flutter version on DEV channel it starts generating apks for other platforms too. The problem is that on some platforms e.g. Nexus 6P Android 8.1 application starts crashing during start. When I tried "flutter run --release" on mentioned Nexus 6P Android 8.1, it runs without problems.

 So I've created a release with "flutter build apk"

After uploading it to the Play Store, several devices from Pre-launch report can't start application. Also some of my testers report that they were unable to start the application.

FATAL EXCEPTION: main
Process: sk.ab.herbs, PID: 8455
java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/sk.ab.herbs-1/base.apk"],nativeLibraryDirectories=[/data/app/sk.ab.herbs-1/lib/arm64, /data/app/sk.ab.herbs-1/base.apk!/lib/arm64-v8a, /system/lib64, /vendor/lib64, /system/vendor/lib64, /product/lib64]]] couldn't find "libflutter.so"
	at java.lang.Runtime.loadLibrary0(Runtime.java:989)
	at java.lang.System.loadLibrary(System.java:1533)
	at io.flutter.view.FlutterMain.startInitialization(FlutterMain.java:160)
	at io.flutter.view.FlutterMain.startInitialization(FlutterMain.java:135)
	at io.flutter.app.FlutterApplication.onCreate(FlutterApplication.java:22)
	at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1028)
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5659)
	at android.app.ActivityThread.-wrap2(ActivityThread.java)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1637)
	at android.os.Handler.dispatchMessage(Handler.java:105)
	at android.os.Looper.loop(Looper.java:156)
	at android.app.ActivityThread.main(ActivityThread.java:6524)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:941)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:831)

**Comment by DevonteDC** [comment]
Also simply added the plugin and now the app is crashing on every device, so I had to remove the plugin for now.

**Comment by kf6gpe** [comment]
I'm tentatively applying the `t: gradle` issue to this because I'm wondering if something isn't being built correctly in the bundle.

**Comment by benadrasni** [comment]
"flutter build appbundle" in flutter 1.8.0 now works for armeabi-v7a and 'arm64-v8a. For other platforms libflutter.so is still missing.

**Comment by blasten** [comment]
As mentioned in our docs, Flutter only supports `armeabi-v7a`, `arm64-v8a` and `x86_64`.
