### ISSUE TITLE
Hot reload can freeze when syncing many assets

### ISSUE THREAD

**Issue by jonahwilliams** [flutter/flutter#29748]
Its possible that we have an aggressive timeout here, or a race condition because we do/don't pause the isolate correctly.

```
Performing hot reload...                                               ⣽[VERBOSE-2:shell.cc(178)] Dart Error: Unhandled exception:
'dart:isolate/runtime/lib/timer_impl.dart': Failed assertion: line 433: '<optimized out>': is not true.
#0      _AssertionError._doThrowNew (dart:core/runtime/lib/errors_patch.dart:40:39)
#1      _AssertionError._throwNew (dart:core/runtime/lib/errors_patch.dart:36:5)
#2      _Timer._cancelWakeup (dart:isolate/runtime/lib/timer_impl.dart:433:12)
#3      _Timer._notifyEventHandler (dart:isolate/runtime/lib/timer_impl.dart:299:7)
#4      _Timer._handleMessage (dart:isolate/runtime/lib/timer_impl.dart:419:5)
#5      _RawReceivePortImpl._handleMessage (dart:isolate/runtime/lib/isolate_patch.dart:171:12)
       ⢿ (This is taking an unexpectedly long time.)Application finished.
jonahwilliams-macbookpro2:flutter_gallery jonahwilliams$ flutter run
Launching lib/main.dart on iPhone XS Max in debug mode...
```

**Comment by jonahwilliams** [comment]
Should be fixed by https://github.com/dart-lang/sdk/commit/ec27b09e68eb78482217217d6031495ab1a70082

**Comment by jonahwilliams** [comment]
The upstream bug fix has landed
