### ISSUE TITLE
Error building app with Scaffold

### ISSUE THREAD

**Issue by khanhnt748** [flutter/flutter#29800]
Hi all, thanks for take a time reading my issue: I writing some code to test Flutter Route follow the Flutter homepage instruction [Navigate to a new screen and back](https://flutter.dev/docs/cookbook/navigation/navigation-basics) 
```dart
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext buildContext) {
    return Scaffold(
      appBar: AppBar(
        title: Text("The main route"),
      ),
      body: Center(
          child: RaisedButton(
            child: Text("Open next route"),
            onPressed: () {
              Navigator.push(
                buildContext,
                MaterialPageRoute(
                  builder: (buildContext) => AnotherScreen(),
                ),
              );
            },
          )
      ),
    );
  }
}

class AnotherScreen extends StatelessWidget {
  @override
  Widget build(BuildContext buildContext) {
    return Scaffold(
      appBar: AppBar(
        title: Text("The next route"),
      ),
      body: Center(
        child: RaisedButton(
          child: Text("Back to the main route"),
          onPressed: () {

          },
        ),
      ),
    );
  }
}
```
And it fail with errors:
```
Launching lib/main.dart on iPhone XR in debug mode...
Running Xcode build...
Xcode build done.                                            5.3s
flutter: ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
flutter: The following assertion was thrown building MyApp:
flutter: MediaQuery.of() called with a context that does not contain a MediaQuery.
flutter: No MediaQuery ancestor could be found starting from the context that was passed to MediaQuery.of().
flutter: This can happen because you do not have a WidgetsApp or MaterialApp widget (those widgets introduce
flutter: a MediaQuery), or it can happen if the context you use comes from a widget above those widgets.
flutter: The context used was:
flutter:   Scaffold(dirty, state: ScaffoldState#60726(lifecycle state: initialized, tickers: tracking 1
flutter:   ticker))
flutter:
flutter: When the exception was thrown, this was the stack:
flutter: #0      MediaQuery.of (package:flutter/src/widgets/media_query.dart:528:5)
flutter: #1      ScaffoldState.didChangeDependencies (package:flutter/src/material/scaffold.dart:1529:50)
flutter: #2      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3862:12)
flutter: #3      ComponentElement.mount (package:flutter/src/widgets/framework.dart:3711:5)
flutter: #4      Element.inflateWidget (package:flutter/src/widgets/framework.dart:2956:14)
flutter: #5      Element.updateChild (package:flutter/src/widgets/framework.dart:2759:12)
flutter: #6      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3747:16)
flutter: #7      Element.rebuild (package:flutter/src/widgets/framework.dart:3559:5)
flutter: #8      ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3716:5)
flutter: #9      ComponentElement.mount (package:flutter/src/widgets/framework.dart:3711:5)
flutter: #10     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2956:14)
flutter: #11     Element.updateChild (package:flutter/src/widgets/framework.dart:2759:12)
flutter: #12     RenderObjectToWidgetElement._rebuild (package:flutter/src/widgets/binding.dart:933:16)
flutter: #13     RenderObjectToWidgetElement.mount (package:flutter/src/widgets/binding.dart:904:5)
flutter: #14     RenderObjectToWidgetAdapter.attachToRenderTree.<anonymous closure> (package:flutter/src/widgets/binding.dart:850:17)
flutter: #15     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2253:19)
flutter: #16     RenderObjectToWidgetAdapter.attachToRenderTree (package:flutter/src/widgets/binding.dart:849:13)
flutter: #17     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding&WidgetsBinding.attachRootWidget (package:flutter/src/widgets/binding.dart:736:7)
flutter: #18     runApp (package:flutter/src/widgets/binding.dart:780:7)
flutter: #19     main (package:flutter_navigation_sample/main.dart:3:16)
flutter: #20     _runMainZoned.<anonymous closure>.<anonymous closure> (dart:ui/hooks.dart:189:25)
flutter: #25     _runMainZoned.<anonymous closure> (dart:ui/hooks.dart:180:5)
flutter: #26     _startIsolate.<anonymous closure> (dart:isolate/runtime/libisolate_patch.dart:300:19)
flutter: #27     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:171:12)
flutter: (elided 4 frames from package dart:async)
flutter: ════════════════════════════════════════════════════════════════════════════════════════════════════
Syncing files to device iPhone XR...
flutter: ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
flutter: The following assertion was thrown building MyApp:
flutter: MediaQuery.of() called with a context that does not contain a MediaQuery.
flutter: No MediaQuery ancestor could be found starting from the context that was passed to MediaQuery.of().
flutter: This can happen because you do not have a WidgetsApp or MaterialApp widget (those widgets introduce
flutter: a MediaQuery), or it can happen if the context you use comes from a widget above those widgets.
flutter: The context used was:
flutter:   Scaffold(dirty, state: ScaffoldState#18e76(lifecycle state: initialized, tickers: tracking 1
flutter:   ticker))
flutter:
flutter: When the exception was thrown, this was the stack:
flutter: #0      MediaQuery.of (package:flutter/src/widgets/media_query.dart:528:5)
flutter: #1      ScaffoldState.didChangeDependencies (package:flutter/src/material/scaffold.dart:1529:50)
flutter: #2      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3862:12)
flutter: #3      ComponentElement.mount (package:flutter/src/widgets/framework.dart:3711:5)
flutter: #4      Element.inflateWidget (package:flutter/src/widgets/framework.dart:2956:14)
flutter: #5      Element.updateChild (package:flutter/src/widgets/framework.dart:2759:12)
flutter: #6      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3747:16)
flutter: #7      Element.rebuild (package:flutter/src/widgets/framework.dart:3559:5)
flutter: #8      BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2273:33)
flutter: #9      _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding&WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:700:20)
flutter: #10     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:268:5)
flutter: #11     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:988:15)
flutter: #12     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:928:9)
flutter: #13     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.scheduleWarmUpFrame.<anonymous closure> (package:flutter/src/scheduler/binding.dart:749:7)
flutter: #15     _Timer._runTimers (dart:isolate/runtime/libtimer_impl.dart:382:19)
flutter: #16     _Timer._handleMessage (dart:isolate/runtime/libtimer_impl.dart:416:5)
flutter: #17     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:171:12)
flutter: (elided one frame from package dart:async)
```
Then I retry wrapper **Scaffold** in **MaterialApp**:
```dart
class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext buildContext) {
    return MaterialApp(
      home: Scaffold(
        appBar: AppBar(
          title: Text("The main route"),
        ),
        body: Center(
            child: RaisedButton(
              child: Text("Open next route"),
              onPressed: () {
                Navigator.push(
                  buildContext,
                  MaterialPageRoute(
                    builder: (buildContext) => AnotherScreen(),
                  ),
                );
              },
            )
        ),
      )
    );
  }
}
```
then I can build app but something wrong when I hit the **RaisedButton**:
```
Performing hot restart...
Syncing files to device iPhone XR...
Restarted application in 1,565ms.
flutter: ══╡ EXCEPTION CAUGHT BY GESTURE ╞═══════════════════════════════════════════════════════════════════
flutter: The following assertion was thrown while handling a gesture:
flutter: Navigator operation requested with a context that does not include a Navigator.
flutter: The context used to push or pop routes from the Navigator must be that of a widget that is a
flutter: descendant of a Navigator widget.
flutter:
flutter: When the exception was thrown, this was the stack:
flutter: #0      Navigator.of.<anonymous closure> (package:flutter/src/widgets/navigator.dart:1379:9)
flutter: #1      Navigator.of (package:flutter/src/widgets/navigator.dart:1386:6)
flutter: #2      Navigator.push (package:flutter/src/widgets/navigator.dart:1011:22)
flutter: #3      MyApp.build.<anonymous closure> (package:flutter_navigation_sample/main.dart:17:27)
flutter: #4      _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:513:14)
flutter: #5      _InkResponseState.build.<anonymous closure> (package:flutter/src/material/ink_well.dart:568:30)
flutter: #6      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:120:24)
flutter: #7      TapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:242:9)
flutter: #8      TapGestureRecognizer.handlePrimaryPointer (package:flutter/src/gestures/tap.dart:175:7)
flutter: #9      PrimaryPointerGestureRecognizer.handleEvent (package:flutter/src/gestures/recognizer.dart:369:9)
flutter: #10     PointerRouter._dispatch (package:flutter/src/gestures/pointer_router.dart:73:12)
flutter: #11     PointerRouter.route (package:flutter/src/gestures/pointer_router.dart:101:11)
flutter: #12     _WidgetsFlutterBinding&BindingBase&GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:214:19)
flutter: #13     _WidgetsFlutterBinding&BindingBase&GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:192:22)
flutter: #14     _WidgetsFlutterBinding&BindingBase&GestureBinding._handlePointerEvent (package:flutter/src/gestures/binding.dart:149:7)
flutter: #15     _WidgetsFlutterBinding&BindingBase&GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:101:7)
flutter: #16     _WidgetsFlutterBinding&BindingBase&GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:85:7)
flutter: #20     _invoke1 (dart:ui/hooks.dart:223:10)
flutter: #21     _dispatchPointerDataPacket (dart:ui/hooks.dart:144:5)
flutter: (elided 3 frames from package dart:async)
flutter:
flutter: Handler: onTap
flutter: Recognizer:
flutter:   TapGestureRecognizer#dc452(debugOwner: GestureDetector, state: accepted, won arena, finalPosition:
flutter:   Offset(185.5, 502.5), sent tap down)
```
Could someone can help me please?

**Comment by lgArlequin** [comment]
I think your problem is related to this topic #15919

https://github.com/flutter/flutter/issues/15919

**Comment by khanhnt748** [comment]
> I think your problem is related to this topic #15919
> 
> #15919

Thank you, #2 issue is solved by that solution.
Are there some change that affect to [Flutter instruction](https://flutter.dev/docs/cookbook/navigation/navigation-basics)?

**Comment by patelkrunal78** [comment]
This exception happens because you are using the context of the widget that instantiated Scaffold. Not the context of a child of Scaffold.

You can solve this by just using a different context :
Find more At Here https://icetutor.com/question/scaffold-of-called-with-a-context-that-does-not-contain-a-scaffold

**Comment by Balakumaran18** [comment]
import 'package:flutter/material.dart';


void main() => runApp(
  MaterialApp(
    home: MyApp(),
  )
);

class MyApp extends StatefulWidget {
  @override
  _MyAppState createState() => _MyAppState();
}

class _MyAppState extends State<MyApp> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text("The main route"),
      ),
      body: Center(
          child: RaisedButton(
            child: Text("Open next route"),
            onPressed: () {
              Navigator.push(
                context,
                MaterialPageRoute(
                  builder: (context) => AnotherScreen(),
                ),
              );
            },
          )
      ),
    );
  }
}



class AnotherScreen extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    
    return Center(
        child: RaisedButton(
          child: Text("Back to the main route"),
          onPressed: () {

          },
        ),
      );
  
  }
}

it's working friend

**Comment by kf6gpe** [comment]
Per comment from @Balakumaran18, I think this is no longer an issue. Closing. @khanhnt748 please feel free to reopen if I'm wrong. Thanks!
