### ISSUE TITLE
Listview.builder with cached network image causes application hang / exception when scrolling

### ISSUE THREAD

**Issue by JRR-OSU** [flutter/flutter#29852]
## Steps to Reproduce

Currently this is only reproducible on my Pixel XL. On the iOS simulator it appears to run normally. This behavior is exhibited in both release and debug modes.

1. Push the attached code via a material route
2. Scroll to the bottom of the list and scroll to the top of the list quickly
3. Repeat until error is exhibited

**Note:** If shrinkwrap property is set to false on the list builder the exception below is logged, however if shrinkwrap is set to "true" the application freezes and no logs are output. 

## Relevant Code
Note: To run just copy this into a blank dart file and push this via a material route.

```
import 'package:flutter/material.dart';
import 'package:cached_network_image/cached_network_image.dart';


class BuildingsViewWidget extends StatefulWidget {
   BuildingsViewWidget({Key key, this.title}) : super(key: key);

  final String title;

  @override
  _BuildingsViewWidgetState createState() => _BuildingsViewWidgetState();
}

class _BuildingsViewWidgetState extends State<BuildingsViewWidget> {
  List buildings;

  @override
  void initState() {
    buildings = getBuildings();
    super.initState();
  }

  @override
  Widget build(BuildContext context) {
    ListTile makeListTile(Building building) => ListTile(
          // contentPadding:
          //     EdgeInsets.symmetric(horizontal: 20.0, vertical: 10.0),

          title: Row(
                children: <Widget>[
                  Padding(
                    padding: const EdgeInsets.fromLTRB(0,10,0,0),
                    child: Text(
                      building.title,
                      style: TextStyle(fontWeight: FontWeight.bold, fontSize: 22.0),
                    ),
                  ),
                
                ],
              ),
          // subtitle: Text("Intermediate", style: TextStyle(color: Colors.white)),

          subtitle:      
               Row(
                children: <Widget>[                   
                    Text(
                      building.description,
                      style: TextStyle(fontWeight: FontWeight.bold, fontSize: 18.0),
                    ),
                ],
          ),
          
          onTap: () {
              // Push building detail page
          },
        );

    Card makeCard(Building building) => Card(
          elevation: 5.0,
          margin: EdgeInsets.all(10),
          clipBehavior: Clip.antiAliasWithSaveLayer,

          shape: RoundedRectangleBorder(
            borderRadius: BorderRadius.circular(10.0),
          ),
          semanticContainer: true,
         // margin: new EdgeInsets.symmetric(horizontal: 10.0, vertical: 6.0),
          child: Stack(
            children: <Widget>[
              Column(
                children: <Widget>[
                  Container(
                    child: new CachedNetworkImage(
                          imageUrl: building.image,
                          fit: BoxFit.fill,
                          placeholder: (context, url) => new CircularProgressIndicator(),
                          errorWidget: (context, url, error) => new Icon(Icons.error),
                        ),
                  ),

                  Column(
                children: <Widget>[
                  Row(
                    children: <Widget>[
                      Padding(
                        padding: const EdgeInsets.fromLTRB(10,10,0,0),
                        child: Text(
                          building.title,
                          style: TextStyle(fontWeight: FontWeight.bold, fontSize: 22.0),
                        ),
                      ),
                    
                    ],
                  ),
                   Row(
                    children: <Widget>[                   
                        Padding(
                          padding: const EdgeInsets.fromLTRB(10,0,0,10),
                          child: Text(
                            building.description,
                            style: TextStyle(fontWeight: FontWeight.bold, fontSize: 18.0),
                          ),
                        ),
                    ],
                  ),
                ],
              ),
                ],
              ),
              new Positioned.fill(
            child: new Material(
                color: Colors.transparent,
                elevation: 0.0,
                child: new InkWell(
                  onTap: () { },
                ))),
            ],
            
          ),

         
        );

    final makeList = Container(
      // decoration: BoxDecoration(color: Color.fromRGBO(58, 66, 86, 1.0)),
      child: Scrollbar(
          child: ListView.builder(
          scrollDirection: Axis.vertical,
          shrinkWrap: true,
          itemCount: buildings.length,
          itemBuilder: (BuildContext context, int index) {
            return makeCard(buildings[index]);
          },
        ),
      ),
    );

    final makeBottom = Container(
      height: 55.0,
      child: BottomAppBar(
        color: Color.fromRGBO(58, 66, 86, 1.0),
        child: Row(
          mainAxisAlignment: MainAxisAlignment.spaceEvenly,
          children: <Widget>[
            IconButton(
              icon: Icon(Icons.home, color: Colors.white),
              onPressed: () {},
            ),
            IconButton(
              icon: Icon(Icons.blur_on, color: Colors.white),
              onPressed: () {},
            ),
            IconButton(
              icon: Icon(Icons.hotel, color: Colors.white),
              onPressed: () {},
            ),
            IconButton(
              icon: Icon(Icons.account_box, color: Colors.white),
              onPressed: () {},
            )
          ],
        ),
      ),
    );
    final topAppBar = AppBar(
      elevation: 0.1,
      backgroundColor: Colors.red[900],
      title: Text("Buildings"),
      // actions: <Widget>[
      //   IconButton(
      //     icon: Icon(Icons.list),
      //     onPressed: () {},
      //   )
      // ],
    );

    return Scaffold(
      // backgroundColor: Color.fromRGBO(58, 66, 86, 1.0),
      appBar: topAppBar,
      body: makeList,
      // bottomNavigationBar: makeBottom,
    );
  }
}
  

List getBuildings() {
  return [
    Building(
        title: "Dreese Laboratory",
        description: "2015 Neil Ave, Columbus, OH 43210",
        image: "https://firebasestorage.googleapis.com/v0/b/accessatosu.appspot.com/o/dreese.jpg?alt=media&token=5dcb28ef-fbc0-4a8a-8e06-70574fb8e672",
    ),
    Building(
        title: "Caldwell Laboratory",
        description: "234 W 18th Ave, Columbus, OH 43210",
        image: "https://www.osu.edu/map/buildingImg.php?id=026&size=campusmap",
    ),
        Building(
        title: "Caldwell Laboratory",
        description: "234 W 18th Ave, Columbus, OH 43210",
        image: "https://www.osu.edu/map/buildingImg.php?id=026&size=campusmap",
    ),
        Building(
        title: "Caldwell Laboratory",
        description: "234 W 18th Ave, Columbus, OH 43210",
        image: "https://www.osu.edu/map/buildingImg.php?id=026&size=campusmap",
    ),
        Building(
        title: "Caldwell Laboratory",
        description: "234 W 18th Ave, Columbus, OH 43210",
        image: "https://www.osu.edu/map/buildingImg.php?id=026&size=campusmap",
    ),
        Building(
        title: "Caldwell Laboratory",
        description: "234 W 18th Ave, Columbus, OH 43210",
        image: "https://www.osu.edu/map/buildingImg.php?id=026&size=campusmap",
    ),
        Building(
        title: "Caldwell Laboratory",
        description: "234 W 18th Ave, Columbus, OH 43210",
        image: "https://www.osu.edu/map/buildingImg.php?id=026&size=campusmap",
    ),
        Building(
        title: "Caldwell Laboratory",
        description: "234 W 18th Ave, Columbus, OH 43210",
        image: "https://www.osu.edu/map/buildingImg.php?id=026&size=campusmap",
    ),
        Building(
        title: "Caldwell Laboratory",
        description: "234 W 18th Ave, Columbus, OH 43210",
        image: "https://www.osu.edu/map/buildingImg.php?id=026&size=campusmap",
    ),
    
  ];
}

class Building {
  String title;
  String description;
  String image;
  
  Building(
      {this.title, this.description, this.image});
}
```

## Logs

```
[+14021 ms] I/flutter (16201): ══╡ EXCEPTION CAUGHT BY RENDERING LIBRARY ╞═════════════════════════════════════════════════════════
[  +15 ms] I/flutter (16201): The following assertion was thrown during performLayout():
[   +1 ms] I/flutter (16201): A RenderViewport exceeded its maximum number of layout cycles.
[        ] I/flutter (16201): RenderViewport render objects, during layout, can retry if either their slivers or their
[        ] I/flutter (16201): ViewportOffset decide that the offset should be corrected to take into account information collected
[        ] I/flutter (16201): during that layout.
[   +1 ms] I/flutter (16201): In the case of this RenderViewport object, however, this happened 10 times and still there was no
[        ] I/flutter (16201): consensus on the scroll offset. This usually indicates a bug. Specifically, it means that one of the
[        ] I/flutter (16201): following three problems is being experienced by the RenderViewport object:
[        ] I/flutter (16201):  * One of the RenderSliver children or the ViewportOffset have a bug such that they always think
[   +1 ms] I/flutter (16201):    that they need to correct the offset regardless.
[        ] I/flutter (16201):  * Some combination of the RenderSliver children and the ViewportOffset have a bad interaction such
[        ] I/flutter (16201):    that one applies a correction then another applies a reverse correction, leading to an infinite
[        ] I/flutter (16201):    loop of corrections.
[        ] I/flutter (16201):  * There is a pathological case that would eventually resolve, but it is so complicated that it
[        ] I/flutter (16201):    cannot be resolved in any reasonable number of layout passes.
[        ] I/flutter (16201): 
[        ] I/flutter (16201): When the exception was thrown, this was the stack:
[   +1 ms] I/flutter (16201): #0      RenderViewport.performLayout.<anonymous closure> (package:flutter/src/rendering/viewport.dart:1255:9)
[        ] I/flutter (16201): #1      RenderViewport.performLayout (package:flutter/src/rendering/viewport.dart:1275:6)
[   +1 ms] I/flutter (16201): #2      RenderObject._layoutWithoutResize (package:flutter/src/rendering/object.dart:1507:7)
[        ] I/flutter (16201): #3      PipelineOwner.flushLayout (package:flutter/src/rendering/object.dart:766:18)
[        ] I/flutter (16201): #4      _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding.drawFrame
(package:flutter/src/rendering/binding.dart:329:19)
[   +1 ms] I/flutter (16201): #5
_WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding&WidgetsBinding.drawFrame
(package:flutter/src/widgets/binding.dart:701:13)
[   +1 ms] I/flutter (16201): #6
_WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding._handlePersistentFrameCallback
(package:flutter/src/rendering/binding.dart:268:5)
[   +1 ms] I/flutter (16201): #7      _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._invokeFrameCallback
(package:flutter/src/scheduler/binding.dart:988:15)
[        ] I/flutter (16201): #8      _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:928:9)
[        ] I/flutter (16201): #9      _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:840:5)
[        ] I/flutter (16201): #13     _invoke (dart:ui/hooks.dart:209:10)
[        ] I/flutter (16201): #14     _drawFrame (dart:ui/hooks.dart:168:3)
[        ] I/flutter (16201): (elided 3 frames from package dart:async)
[   +8 ms] I/flutter (16201): 
[   +1 ms] I/flutter (16201): The following RenderObject was being processed when the exception was fired:
[   +1 ms] I/flutter (16201):   RenderViewport#cd82d NEEDS-LAYOUT NEEDS-PAINT
[   +1 ms] I/flutter (16201):   creator: Viewport ← IgnorePointer-[GlobalKey#3fc7b] ← Semantics ← Listener ← _GestureSemantics ←
[   +1 ms] I/flutter (16201):   RawGestureDetector-[LabeledGlobalKey<RawGestureDetectorState>#70be1] ← _ScrollableScope ←
[   +1 ms] I/flutter (16201):   _ScrollSemantics-[GlobalKey#2e558] ← RepaintBoundary ← CustomPaint ← RepaintBoundary ←
[  +13 ms] I/flutter (16201):   NotificationListener<ScrollNotification> ← ⋯
[   +1 ms] I/flutter (16201):   parentData: <none> (can use size)
[        ] I/flutter (16201):   constraints: BoxConstraints(0.0<=w<=411.4, 0.0<=h<=603.4)
[        ] I/flutter (16201):   layer: OffsetLayer#c8fcc
[        ] I/flutter (16201):   size: Size(411.4, 603.4)
[        ] I/flutter (16201):   axisDirection: down
[   +1 ms] I/flutter (16201):   crossAxisDirection: right
[        ] I/flutter (16201):   offset: ScrollPositionWithSingleContext#059c5(offset: 555.6, range: 0.0..2068.6, viewport: 603.4,
[        ] I/flutter (16201):   ScrollableState, AlwaysScrollableScrollPhysics -> ClampingScrollPhysics,
[   +1 ms] I/flutter (16201):   BallisticScrollActivity#31529(AnimationController#1dd47(▶ 555.574; for BallisticScrollActivity)),
[        ] I/flutter (16201):   ScrollDirection.forward)
[        ] I/flutter (16201):   anchor: 0.0
[        ] I/flutter (16201): This RenderObject had the following descendants (showing up to depth 5):
[        ] I/flutter (16201):   RenderSliverPadding#b1ebd relayoutBoundary=up1 NEEDS-PAINT
[        ] I/flutter (16201):     RenderSliverList#3457a relayoutBoundary=up2 NEEDS-PAINT
[   +1 ms] I/flutter (16201):       RenderIndexedSemantics#bc28b relayoutBoundary=up3 NEEDS-PAINT
[   +1 ms] I/flutter (16201):         RenderRepaintBoundary#9e0df relayoutBoundary=up4 NEEDS-PAINT
[   +1 ms] I/flutter (16201):           RenderSemanticsAnnotations#f4c31 relayoutBoundary=up5 NEEDS-PAINT
[   +1 ms] I/flutter (16201):       RenderIndexedSemantics#6425e relayoutBoundary=up3 NEEDS-PAINT
[   +1 ms] I/flutter (16201):         RenderRepaintBoundary#46531 relayoutBoundary=up4 NEEDS-PAINT
[   +1 ms] I/flutter (16201):           RenderSemanticsAnnotations#86b73 relayoutBoundary=up5 NEEDS-PAINT
[        ] I/flutter (16201):       RenderIndexedSemantics#2dacc relayoutBoundary=up3
[        ] I/flutter (16201):         RenderRepaintBoundary#d2e25 relayoutBoundary=up4
[        ] I/flutter (16201):           RenderSemanticsAnnotations#65d70 relayoutBoundary=up5
[        ] I/flutter (16201):       RenderIndexedSemantics#baa6e relayoutBoundary=up3
[        ] I/flutter (16201):         RenderRepaintBoundary#7e616 relayoutBoundary=up4
[        ] I/flutter (16201):           RenderSemanticsAnnotations#d4169 relayoutBoundary=up5
[        ] I/flutter (16201):       RenderIndexedSemantics#97b45 relayoutBoundary=up3
[        ] I/flutter (16201):         RenderRepaintBoundary#85c4f relayoutBoundary=up4
[        ] I/flutter (16201):           RenderSemanticsAnnotations#75575 relayoutBoundary=up5
[        ] I/flutter (16201): ════════════════════════════════════════════════════════════════════════════════════════════════════
```

Flutter analysis elicits no issues.

## Flutter Doctor Output

```
[√] Flutter (Channel stable, v1.2.1, on Microsoft Windows [Version 10.0.17763.379], locale en-US)
    • Flutter version 1.2.1 at C:\Users\SgtJo\Documents\flutter_dev\flutter
    • Framework revision 8661d8aecd (5 weeks ago), 2019-02-14 19:19:53 -0800
    • Engine revision 3757390fa4
    • Dart version 2.1.2 (build 2.1.2-dev.0.0 0a7dcf17eb)

[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at C:\Users\SgtJo\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)
    • All Android licenses accepted.

[√] Android Studio (version 3.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 33.3.1
    • Dart plugin version 182.5215
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)

[√] VS Code (version 1.32.3)
    • VS Code at C:\Users\SgtJo\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 2.24.0

[√] Connected device (1 available)
    • Pixel XL • HT71D0202823 • android-arm64 • Android 9 (API 28)

• No issues found!
```

**Comment by jason-simmons** [comment]
Fixed by https://github.com/flutter/flutter/commit/fbeb5e0cf5c0659aa767544cfac33e9cb46f0e56

**Comment by JRR-OSU** [comment]
@jason-simmons @chunhtai Thanks to both of you.
