### ISSUE TITLE
Unable to load asset: Image provider: AssetImage(bundle: null, name: "")

### ISSUE THREAD

**Issue by tiholic** [flutter/flutter#29865]
## Steps to Reproduce

Dependencies from pubspec.yaml
```
dependencies:

  flutter:
    sdk: flutter
  adhara: ^0.3.2
  fluttertoast: ^3.0.1
  firebase_messaging: ^3.0.1
  flutter_local_notifications: ^0.5.1+2
  flutter_svg: ^0.12.0
```

## Logs

```
[   +3 ms] DevFS: Starting sync from LocalDirectory: '/Users/rohit/workspace/os-projects/coromandel/gromor-store/app/gromor_shakti'
[        ] Scanning project files
[  +39 ms] Scanning package files
[ +249 ms] Scanning asset files
[   +5 ms] Scanning for deleted files
[  +33 ms] Compiling dart to kernel with 918 updated files
[  +17 ms] /Users/rohit/flutter/bin/cache/dart-sdk/bin/dart /Users/rohit/flutter/bin/cache/artifacts/engine/darwin-x64/frontend_server.dart.snapshot
--sdk-root /Users/rohit/flutter/bin/cache/artifacts/engine/common/flutter_patched_sdk/ --incremental --strong --target=flutter --output-dill
build/app.dill --packages /Users/rohit/workspace/os-projects/coromandel/gromor-store/app/gromor_shakti/.packages --filesystem-scheme org-dartlang-root
[  +30 ms] I/flutter (10314): ══╡ EXCEPTION CAUGHT BY IMAGE RESOURCE SERVICE ╞════════════════════════════════════════════════════
[   +1 ms] I/flutter (10314): The following assertion was thrown resolving an image codec:
[        ] I/flutter (10314): Unable to load asset:
[   +8 ms] I/flutter (10314): 
[        ] I/flutter (10314): When the exception was thrown, this was the stack:
[        ] I/flutter (10314): #0      PlatformAssetBundle.load (package:flutter/src/services/asset_bundle.dart:221:7)
[        ] I/flutter (10314): <asynchronous suspension>
[        ] I/flutter (10314): #1      AssetBundleImageProvider._loadAsync (package:flutter/src/painting/image_provider.dart:433:44)
[        ] I/flutter (10314): <asynchronous suspension>
[        ] I/flutter (10314): #2      AssetBundleImageProvider.load (package:flutter/src/painting/image_provider.dart:418:14)
[        ] I/flutter (10314): #3      ImageProvider.resolve.<anonymous closure>.<anonymous closure>
(package:flutter/src/painting/image_provider.dart:285:105)
[   +1 ms] I/flutter (10314): #4      ImageCache.putIfAbsent (package:flutter/src/painting/image_cache.dart:157:22)
[   +1 ms] I/flutter (10314): #5      ImageProvider.resolve.<anonymous closure> (package:flutter/src/painting/image_provider.dart:285:82)
[   +1 ms] I/flutter (10314): (elided 13 frames from package dart:async)
[   +1 ms] I/flutter (10314): 
[        ] I/flutter (10314): Image provider: AssetImage(bundle: null, name: "")
[        ] I/flutter (10314): Image key: AssetBundleImageKey(bundle: PlatformAssetBundle#7cc99(), name: "", scale: 1.0)
[        ] I/flutter (10314): ════════════════════════════════════════════════════════════════════════════════════════════════════
[ +690 ms] I/flutter (10314): Syncing data...
[  +60 ms] I/flutter (10314): NoSuchMethodError: The method '[]' was called on null.
[        ] I/flutter (10314): Receiver: null
[        ] I/flutter (10314): Tried calling: []("role")
[+3851 ms] Updating files
[+4713 ms] DevFS: Sync finished
[   +4 ms] Syncing files to device ONEPLUS A5010... (completed in 9,715ms, longer than expected)
[        ] Synced 7.2MB.
[   +2 ms] Sending to VM service: _flutter.listViews({})
[  +36 ms] Result: {type: FlutterViewList, views: [{type: FlutterView, id: _flutterView/0x7592b94318, isolate: {type: @Isolate, fixedId: true, id:
isolates/933176188, name: main.dart$main-933176188, number: 933176188}}]}
[   +3 ms] Connected to _flutterView/0x7592b94318.
[   +5 ms] 🔥  To hot reload changes while running, press "r". To hot restart (and rebuild state), press "R".
[   +2 ms] An Observatory debugger and profiler on ONEPLUS A5010 is available at: http://127.0.0.1:51805/
[   +3 ms] For a more detailed help message, press "h". To detach, press "d"; to quit, press "q".
```

flutter analyze
```
Analyzing gromor_shakti...                                              

   info • Unused import: 'package:gromor_shakti/screens/account/HomePage.dart' • lib/GromorStoreApp.dart:6:8 • unused_import
   info • Unused import: 'package:gromor_shakti/widgets.dart' • lib/Routes.dart:24:8 • unused_import
   info • Don't explicitly initialize variables to null • lib/datainterface/AppDataInterface.dart:345:53 • avoid_init_to_null
   info • Unused import: 'package:gromor_shakti/utils.dart' • lib/screens/ScreenTransitionHandler.dart:4:8 • unused_import
   info • The exception variable 'e' isn't used, so the 'catch' clause can be removed • lib/screens/account/ChangePassword.dart:75:29 •
          unused_catch_clause
   info • The exception variable 'e' isn't used, so the 'catch' clause can be removed • lib/screens/account/EnterOTP.dart:71:25 • unused_catch_clause
   info • Unused import: 'package:gromor_shakti/datainterface/bean/User.dart' • lib/screens/account/ForgotPassword.dart:5:8 • unused_import
   info • The exception variable 'e' isn't used, so the 'catch' clause can be removed • lib/screens/account/ForgotPassword.dart:31:29 •
          unused_catch_clause
   info • Unused import: 'package:flutter/services.dart' • lib/screens/account/HomePage.dart:3:8 • unused_import
   info • The method '_buildSliverList' isn't used • lib/screens/account/HomePage.dart:249:14 • unused_element
   info • The exception variable 'e' isn't used, so the 'catch' clause can be removed • lib/screens/account/MobileVerification.dart:28:25 •
          unused_catch_clause
   info • Unused import: 'package:gromor_shakti/datainterface/bean/Zone.dart' • lib/screens/account/RegistrationForm.dart:8:8 • unused_import
   info • Unused import: 'package:gromor_shakti/datainterface/bean/Area.dart' • lib/screens/account/RegistrationForm.dart:9:8 • unused_import
   info • Unused import: 'package:gromor_shakti/datainterface/bean/State.dart' • lib/screens/account/RegistrationForm.dart:10:8 • unused_import
   info • Unused import: 'package:flutter/services.dart' • lib/screens/account/ResetPassword.dart:3:8 • unused_import
   info • The exception variable 'e' isn't used, so the 'catch' clause can be removed • lib/screens/account/ResetPassword.dart:50:29 •
          unused_catch_clause
   info • Unused import: 'package:gromor_shakti/res/res.dart' • lib/screens/orders/OrdersList.dart:6:8 • unused_import

17 issues found. (ran in 10.4s)

```

flutter doctor -v
```
[✓] Flutter (Channel stable, v1.2.1, on Mac OS X 10.14.3 18D109, locale en-US)
    • Flutter version 1.2.1 at /Users/rohit/flutter
    • Framework revision 8661d8aecd (5 weeks ago), 2019-02-14 19:19:53 -0800
    • Engine revision 3757390fa4
    • Dart version 2.1.2 (build 2.1.2-dev.0.0 0a7dcf17eb)

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/rohit/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = /Users/rohit/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.1, Build version 10B61
    • ios-deploy 2.0.0
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 29.0.1
    • Dart plugin version 173.4700
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)

[✓] Connected device (1 available)
    • ONEPLUS A5010 • 192.168.1.206:5555 • android-arm64 • Android 9 (API 28)

• No issues found!
```

**Comment by tiholic** [comment]
I found the issue after some more digging.
It would be helpful to see the elided frames `(elided 13 frames from package dart:async)`

**Comment by escamoteur** [comment]
Is this still of interest?
If yes could you elaborate what you mean?

**Comment by tiholic** [comment]
I assume that few lines are not printed by logger (ex: 13 frames are omitted in current context)
If we can have a run parameter which would not omit any logs, it would help resolve any issues faster. It took a long time to figure out the issue when the above log was printed.

**Comment by jonahwilliams** [comment]
The frame elision actually happens in the framework stack trace processing
