### ISSUE TITLE
Change viewportFraction dynamically in PageController

### ISSUE THREAD

**Issue by markzero** [flutter/flutter#29871]
I have searched everywhere and posted on SO but no luck.
I have a PageView and want to zoom on double tap.
Here's the code:
```dart
@override
Widget build(BuildContext context) {
  this.controller = PageController(
    initialPage: 0,
    viewportFraction: _viewportScale,
  );
  return PageView(
    controller: controller,
    onPageChanged: (int pageIndex) {
      setState(() {
        _viewportScale = 1.0;
      });
    },
    children: this.urls.map((String url) {
        return Container(
          child: GestureDetector(
            child: Image.network(url),
            onTap: () => Navigator.pop(context),
            onDoubleTap: () {
              setState(() {
                _viewportScale = _viewportScale == 1.0 ? 2.0 : 1.0;
              });
            },
          ),
        );
      }).toList(),
  );
}
```

And when I double tap get this error:

```
I/flutter ( 6492): ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
I/flutter ( 6492): The following assertion was thrown building NotificationListener<ScrollNotification>:
I/flutter ( 6492): Unexpected call to replaceSemanticsActions() method of RawGestureDetectorState.
I/flutter ( 6492): The replaceSemanticsActions() method can only be called outside of the build phase.
I/flutter ( 6492): 
I/flutter ( 6492): When the exception was thrown, this was the stack:
I/flutter ( 6492): #0      RawGestureDetectorState.replaceSemanticsActions.<anonymous closure> (package:flutter/src/widgets/gesture_detector.dart:737:9)
I/flutter ( 6492): #1      RawGestureDetectorState.replaceSemanticsActions (package:flutter/src/widgets/gesture_detector.dart:743:6)
I/flutter ( 6492): #2      ScrollableState.setSemanticsActions (package:flutter/src/widgets/scrollable.dart:379:40)
I/flutter ( 6492): #3      ScrollPosition._updateSemanticActions (package:flutter/src/widgets/scroll_position.dart:445:13)
I/flutter ( 6492): #4      ScrollPosition.notifyListeners (package:flutter/src/widgets/scroll_position.dart:695:5)
I/flutter ( 6492): #5      ScrollPosition.forcePixels (package:flutter/src/widgets/scroll_position.dart:318:5)
I/flutter ( 6492): #6      _PagePosition.viewportFraction= (package:flutter/src/widgets/page_view.dart:263:7)
I/flutter ( 6492): #7      PageController.attach (package:flutter/src/widgets/page_view.dart:173:18)
I/flutter ( 6492): #8      ScrollableState.didUpdateWidget (package:flutter/src/widgets/scrollable.dart:356:26)
I/flutter ( 6492): #9      StatefulElement.update (package:flutter/src/widgets/framework.dart:3884:58)
I/flutter ( 6492): #10     Element.updateChild (package:flutter/src/widgets/framework.dart:2752:15)
I/flutter ( 6492): #11     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3752:16)
I/flutter ( 6492): #12     Element.rebuild (package:flutter/src/widgets/framework.dart:3564:5)
I/flutter ( 6492): #13     StatelessElement.update (package:flutter/src/widgets/framework.dart:3801:5)
I/flutter ( 6492): #14     Element.updateChild (package:flutter/src/widgets/framework.dart:2752:15)
I/flutter ( 6492): #15     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3752:16)
I/flutter ( 6492): #16     Element.rebuild (package:flutter/src/widgets/framework.dart:3564:5)
I/flutter ( 6492): #17     StatefulElement.update (package:flutter/src/widgets/framework.dart:3899:5)
I/flutter ( 6492): #18     Element.updateChild (package:flutter/src/widgets/framework.dart:2752:15)
I/flutter ( 6492): #19     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3752:16)
I/flutter ( 6492): #20     Element.rebuild (package:flutter/src/widgets/framework.dart:3564:5)
I/flutter ( 6492): #21     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2277:33)
I/flutter ( 6492): #22     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding&WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:700:20)
I/flutter ( 6492): #23     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:275:5)
I/flutter ( 6492): #24     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:990:15)
I/flutter ( 6492): #25     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:930:9)
I/flutter ( 6492): #26     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:842:5)
I/flutter ( 6492): #30     _invoke (dart:ui/hooks.dart:209:10)
I/flutter ( 6492): #31     _drawFrame (dart:ui/hooks.dart:168:3)
I/flutter ( 6492): (elided 3 frames from package dart:async)
I/flutter ( 6492): ════════════════════════════════════════════════════════════════════════════════════════════════════
```

As you can see `viewportFraction` is changed onDoubleTap. It's set to 1.0 initially in class props declaration.
I found something similar https://github.com/flutter/flutter/issues/23873 but this is not about if it's smaller that 1.0, it's when changing `viewportFraction` dynamically.
Usually I solve these kind of issues by trials and errors but here have no clue what's going on.

**Comment by markzero** [comment]
It works on first PageView index, second one fails with the message above.

**Comment by YLoveX** [comment]
> It works on first PageView index, second one fails with the message above.

I have the same issue....i'm using the animation to dynamic change the view fraction of PageView, the last page got this error.

Maybe we don't need to change the view fraction. I think there is another way like customize the PageView or PageViewController... But i'm a new to Flutter. Have no idear how to do it.

**Comment by RenanBatista** [comment]
In 'pageview.dart' I removed the "final" single-assignment from ` final double viewportFraction;
`, and within a button 
```
GestureDetector(
   onTap: () {
      setState(() {
         if (sliderNotifier.storeActivate)
            controller.viewportFraction = 1.0;
        else
           controller.viewportFraction = 0.65;
}
```
Which worked, but had some side effects.

**Comment by wdavies973** [comment]
Spent quite a while on this and couldn't quite get anything smooth working.

I believe the issue occurs in `_PagePosition`:
```
set viewportFraction(double value) {
    if (_viewportFraction == value)
      return;
    final double oldPage = page;
    _viewportFraction = value;

    if (oldPage != null)
      forcePixels(getPixelsFromPage(oldPage));
  }
```

This function is called when the `viewportFunction` is updated. The error case happens precisely when viewing the last page at `viewportFraction < 1.0` and animating to `viewportFraction = 1` (0.85 to 1 in my case). In this case, the `maxScrollExtent` is rapidly changing, as `viewportFraction` affects the total width of all pages together (the `maxScrollExtent`) as they begin to scale. Essentially, when calling `forcePixels()` on the last page, I think one of two things is happening, 1) `maxScrollExtent` is not computed accurately enough or before `forcePixels`. 2) `forcePixels()` is flooding the widget with too many notifications rather than choosing a few accurate, smooth interpolation points.

Ideas for an actual fix:
- I tried `jumpTo()` instead of `forcePixels()` and found this to help quite a bit
- Add a bit of padding to the maxScrollExtent when scaling down?
- Smoothly interpolate adjusting the pixel positions. Maybe call "jumpTo" less, or at more optimized times?

Hack fix:
- A really easy hack is prior to an `viewportFraction` animation change, simply call `animateTo` to the first page (or you could call animateTo the second to last page).

**Comment by rishikesh1419** [comment]
> > It works on first PageView index, second one fails with the message above.
> 
> I have the same issue....i'm using the animation to dynamic change the view fraction of PageView, the last page got this error.
> 
> Maybe we don't need to change the view fraction. I think there is another way like customize the PageView or PageViewController... But i'm a new to Flutter. Have no idear how to do it.

Hey! How did you animate the dynamic change? I am trying to do the same thing- on tapping on the container inside the page, the viewport fraction goes from 0.8 to 0.95.
Could you share the code snippet or anything? @YLoveX

**Comment by edwinmrb** [comment]
Any Solutions..???

**Comment by bugrevealingbme** [comment]
any update?
