### ISSUE TITLE
FirebaseAuth: Phone Auth exception - linkWithCredentials

### ISSUE THREAD

**Issue by Lebogang95** [flutter/flutter#29872]
In my app I have already setup authentication using Email & Password. As a secondary means of authentication I am trying to add Phone Auth which I want to link to Email & Auth using linkWithCredentials.

### I can successfully send an sms to a number using the below code

```
Future<void> _sendCodeToPhoneNumber() async {

    String phoneNumber = '+27'+_phoneNumberController.text.substring(1);

    final PhoneVerificationFailed verificationFailed = (AuthException authException) {
      setState(() {
        print('Phone number verification failed. Code: ${authException.code}. Message: ${authException.message}');}
      );
    };

    final PhoneCodeSent codeSent =
        (String verificationId, [int forceResendingToken]) async {
      this.verificationId = verificationId;
      print("code sent to " + phoneNumber);
    };

    final PhoneCodeAutoRetrievalTimeout codeAutoRetrievalTimeout =
        (String verificationId) {
      this.verificationId = verificationId;
      print("time out");
    };

    await FirebaseAuth.instance.verifyPhoneNumber(
        phoneNumber: phoneNumber,
        timeout: const Duration(minutes: 1),
        verificationCompleted: null,
        verificationFailed: verificationFailed,
        codeSent: codeSent,
        codeAutoRetrievalTimeout: codeAutoRetrievalTimeout);
  }
```

### But when I use the code below to link the phone auth & email-password it gives me an exception

```
void _linkCredentials(String smsCode) async {
    final FirebaseAuth _firebaseAuth = FirebaseAuth.instance;

    print(verificationId);
    print(smsCode);

    final AuthCredential credential = PhoneAuthProvider.getCredential(
      verificationId: verificationId,
      smsCode: smsCode,
    );

    await FirebaseAuth.instance.linkWithCredential(credential).then((FirebaseUser user)async{
      final FirebaseUser currentUser = await _firebaseAuth.currentUser();
      print(currentUser.email);
      print(currentUser.phoneNumber);
      print(currentUser.uid);
    }).catchError((e){
      print(e.toString());
    });

  }
```

### Below is the exception

```
Performing hot reload...
Syncing files to device SM G965F...
Reloaded 16 of 462 libraries in 1 283ms.
D/ViewRootImpl@1d4d42c[MainActivity](13018): ViewPostIme pointer 0
D/ViewRootImpl@1d4d42c[MainActivity](13018): ViewPostIme pointer 1
I/flutter (13018): AM5PThC1RZWxsSRbwlI-sq4Gq0NMX9X5eqoD1Mk4HfowUszfY6RfeYTbNSOXHWKs0W41UqoX_N9HLmcZQc0nhbGdNApG85IGBb2HQj9zKE10x8BDbBgTkNoyvhq90SdPnlTsgAFtNTWShTKJsooptk0EWGe7u7TiADYOjOd52nQkRtX5WIH6i87T82wXbPNEixeYRJHqWkXdidJwN2Uk-E8si7NcZJS3Nw
I/flutter (13018): 604664
E/MethodChannel#plugins.flutter.io/firebase_auth(13018): Failed to handle method call
E/MethodChannel#plugins.flutter.io/firebase_auth(13018): java.lang.IllegalArgumentException: Given String is empty or null
E/MethodChannel#plugins.flutter.io/firebase_auth(13018): 	at com.google.android.gms.common.internal.Preconditions.checkNotEmpty(Unknown Source:5)
E/MethodChannel#plugins.flutter.io/firebase_auth(13018): 	at com.google.firebase.auth.EmailAuthProvider.getCredential(Unknown Source:2)
E/MethodChannel#plugins.flutter.io/firebase_auth(13018): 	at io.flutter.plugins.firebaseauth.FirebaseAuthPlugin.handleLinkWithEmailAndPassword(FirebaseAuthPlugin.java:279)
E/MethodChannel#plugins.flutter.io/firebase_auth(13018): 	at io.flutter.plugins.firebaseauth.FirebaseAuthPlugin.onMethodCall(FirebaseAuthPlugin.java:123)
E/MethodChannel#plugins.flutter.io/firebase_auth(13018): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:200)
E/MethodChannel#plugins.flutter.io/firebase_auth(13018): 	at io.flutter.view.FlutterNativeView$PlatformMessageHandlerImpl.handlePlatformMessage(FlutterNativeView.java:188)
E/MethodChannel#plugins.flutter.io/firebase_auth(13018): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:202)
E/MethodChannel#plugins.flutter.io/firebase_auth(13018): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/MethodChannel#plugins.flutter.io/firebase_auth(13018): 	at android.os.MessageQueue.next(MessageQueue.java:326)
E/MethodChannel#plugins.flutter.io/firebase_auth(13018): 	at android.os.Looper.loop(Looper.java:181)
E/MethodChannel#plugins.flutter.io/firebase_auth(13018): 	at android.app.ActivityThread.main(ActivityThread.java:6981)
E/MethodChannel#plugins.flutter.io/firebase_auth(13018): 	at java.lang.reflect.Method.invoke(Native Method)
E/MethodChannel#plugins.flutter.io/firebase_auth(13018): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
E/MethodChannel#plugins.flutter.io/firebase_auth(13018): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1445)
I/flutter (13018): PlatformException(error, Given String is empty or null, null)
D/ViewRootImpl@1d4d42c[MainActivity](13018): ViewPostIme pointer 0
D/ViewRootImpl@1d4d42c[MainActivity](13018): ViewPostIme pointer 1
```

**Comment by escamoteur** [comment]
Please ask questions like that on stackoverflow. We cannot provide personal support here. Thanks!
