### ISSUE TITLE
Camera Plugin Crash - when the session doesn't end properly ... maybe

### ISSUE THREAD

**Issue by p30arena** [flutter/flutter#29925]
App Crashes in Release Mode

1- Installed the release apk
2- Camera was BLACK
3- Tried to restart it multiple times
4- At last the error below appers
5- I close the app from task manager
6- Now error is gone

camera: ^0.4.2

```
03-25 22:02:35.850 18924-18924/? E/AndroidRuntime: FATAL EXCEPTION: main
                                                   Process: ir.yabco.flutter.goggles, PID: 18924
                                                   java.lang.IllegalStateException: Session has been closed; further changes are illegal.
                                                       at android.hardware.camera2.impl.CameraCaptureSessionImpl.checkNotClosed(CameraCaptureSessionImpl.java:606)
                                                       at android.hardware.camera2.impl.CameraCaptureSessionImpl.setRepeatingRequest(CameraCaptureSessionImpl.java:227)
                                                       at io.flutter.plugins.camera.CameraPlugin$Camera$7.onConfigured(CameraPlugin.java:748)
                                                       at java.lang.reflect.Method.invoke(Native Method)
                                                       at android.hardware.camera2.dispatch.InvokeDispatcher.dispatch(InvokeDispatcher.java:39)
                                                       at android.hardware.camera2.dispatch.HandlerDispatcher$1.run(HandlerDispatcher.java:65)
                                                       at android.os.Handler.handleCallback(Handler.java:751)
                                                       at android.os.Handler.dispatchMessage(Handler.java:95)
                                                       at android.os.Looper.loop(Looper.java:154)
                                                       at android.app.ActivityThread.main(ActivityThread.java:6776)
                                                       at java.lang.reflect.Method.invoke(Native Method)
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1496)
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1386)
```

```
[√] Flutter (Channel master, v1.3.14-pre.69, on Microsoft Windows [Version 6.3.9600], locale en-US)
    • Flutter version 1.3.14-pre.69 at M:\flutter
    • Framework revision 9bc85d7e54 (53 minutes ago), 2019-03-25 09:42:57 -0700
    • Engine revision dcc72c7176
    • Dart version 2.2.1 (build 2.2.1-dev.2.0 None)
```

**Comment by p30arena** [comment]
https://github.com/google/cameraview/issues/11

**Comment by p30arena** [comment]
@bparrishMines 
https://github.com/google/cameraview/issues/11
https://github.com/ewolfox/cameraview/commit/dbc58af51097262ba0329a323a37555280d0990d
https://stackoverflow.com/questions/42749056/camera2-api-and-java-lang-illegalstateexception

**Comment by p30arena** [comment]
now even if I close the app from the task manager,
the same error appears.

**Comment by p30arena** [comment]
another case:
1- Force Close App
2- The next time App Crashes


this is the line no. 748

`cameraCaptureSession.setRepeatingRequest(captureRequestBuilder.build(), null, null);`

**Comment by p30arena** [comment]
I had no more crashes after the https://github.com/flutter/plugins/pull/1393 fix and other testers (my team) agree too.
