### ISSUE TITLE
DragTarget exception:

### ISSUE THREAD

**Issue by apwilson** [flutter/flutter#2993]
```
I/flutter : -- EXCEPTION CAUGHT BY GESTURE LIBRARY ---------------------------------
I/flutter : The following exception was raised while routing a pointer event:
I/flutter : '<redacted>/third_party/flutter/packages/flutter/lib/src/widgets/drag_target.dart': Failed assertion: line 321: '!_rejectedData.contains(data)' is not true.
I/flutter : Event:
I/flutter : PointerMoveEvent(Point(364.6, 113.9))
I/flutter : Stack trace:
I/flutter : #0      _AssertionError._throwNew (dart:core-patch/errors_patch.dart:27)
I/flutter : #1      _DragTargetState.didEnter (<redacted>/third_party/flutter/packages/flutter/lib/src/widgets/drag_target.dart:321)
I/flutter : #2      _DragAvatar.update.<anonymous closure> (<redacted>/third_party/flutter/packages/flutter/lib/src/widgets/drag_target.dart:449)
I/flutter : #3      Object&ListMixin.firstWhere (dart:collection/list.dart:127)
I/flutter : #4      _DragAvatar.update (<redacted>/third_party/flutter/packages/flutter/lib/src/widgets/drag_target.dart:447)
I/flutter : #5      _DragAvatar.move (<redacted>/third_party/flutter/packages/flutter/lib/src/widgets/drag_target.dart:403)
I/flutter : #6      MultiDragPointerState._move (<redacted>/third_party/flutter/packages/flutter/lib/src/gestures/multidrag.dart:51)
I/flutter : #7      MultiDragGestureRecognizer.handleEvent (<redacted>/third_party/flutter/packages/flutter/lib/src/gestures/multidrag.dart:150)
I/flutter : #8      PointerRouter.route (<redacted>/third_party/flutter/packages/flutter/lib/src/gestures/pointer_router.dart:65)
I/flutter : #9      BindingBase&Scheduler&Gesturer.handleEvent (<redacted>/third_party/flutter/packages/flutter/lib/src/gestures/binding.dart:120)
I/flutter : #10     BindingBase&Scheduler&Gesturer.dispatchEvent (<redacted>/third_party/flutter/packages/flutter/lib/src/gestures/binding.dart:98)
I/flutter : #11     BindingBase&Scheduler&Gesturer._handlePointerEvent (<redacted>/third_party/flutter/packages/flutter/lib/src/gestures/binding.dart:72)
I/flutter : #12     BindingBase&Scheduler&Gesturer._handlePointerPacket (<redacted>/third_party/flutter/packages/flutter/lib/src/gestures/binding.dart:44)
I/flutter : #13     _dispatchPointerPacket (file:///b/build/slave/Linux_Engine/build/src/out/android_Release/gen/sky/bindings/hooks.dart:43)
I/flutter : ------------------------------------------------------------------------
```

**Comment by apwilson** [comment]
@Hixie You think this is related to the change I just made

**Comment by Hixie** [comment]
seems likely

**Comment by apwilson** [comment]
I think I see the issue, when we drop we only didLeave the _activeTarget instead of all the targets we entered.  I'll post a fix in a bit.
