### ISSUE TITLE
Image_Picker (v 0.4.12+1) - App Crashes when launching the camera (only after uploading in PlayStore)

### ISSUE THREAD

**Issue by ArielFerreiro** [flutter/flutter#29982]
I have this very strange issue when I upload the app in beta testing at the playstore. Before in debug mode or even in release mode (signed) it works. The result is when I try to open the camera to take a photo the app hangs showing any error to the user. Then in the logcat I got this:

03-25 13:58:34.599 21645-21645/? E/MethodChannel#plugins.flutter.io/image_picker: Failed to handle method call
    java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.res.XmlResourceParser android.content.pm.ProviderInfo.loadXmlMetaData(android.content.pm.PackageManager, java.lang.String)' on a null object reference
        at android.support.v4.content.FileProvider.parsePathStrategy(FileProvider.java:604)
        at android.support.v4.content.FileProvider.getPathStrategy(FileProvider.java:578)
        at android.support.v4.content.FileProvider.getUriForFile(FileProvider.java:416)
        at io.flutter.plugins.imagepicker.ImagePickerDelegate$3.resolveFileProviderUriForFile(ImagePickerDelegate.java:140)
        at io.flutter.plugins.imagepicker.ImagePickerDelegate.launchTakeImageWithCameraIntent(ImagePickerDelegate.java:292)
        at io.flutter.plugins.imagepicker.ImagePickerDelegate.takeImageWithCamera(ImagePickerDelegate.java:277)
        at io.flutter.plugins.imagepicker.ImagePickerPlugin.onMethodCall(ImagePickerPlugin.java:59)
        at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:201)
        at io.flutter.view.FlutterNativeView$PlatformMessageHandlerImpl.handleMessageFromDart(FlutterNativeView.java:188)
        at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:202)
        at android.os.MessageQueue.nativePollOnce(Native Method)
        at android.os.MessageQueue.next(MessageQueue.java:323)
        at android.os.Looper.loop(Looper.java:135)
        at android.app.ActivityThread.main(ActivityThread.java:5417)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
03-25 13:58:34.601 21645-21680/? E/flutter: [ERROR:flutter/lib/ui/ui_dart_state.cc(148)] Unhandled Exception: PlatformException(error, Attempt to invoke virtual method 'android.content.res.XmlResourceParser android.content.pm.ProviderInfo.loadXmlMetaData(android.content.pm.PackageManager, java.lang.String)' on a null object reference, null)
    #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:564)
    #1      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:302)
    <asynchronous suspension>
    #2      ImagePicker.pickImage (package:image_picker/image_picker.dart:50)

**Comment by benadrasni** [comment]
Check "Camera" permissions.

**Comment by kf6gpe** [comment]
@ArielFerreiro Did checking camera permissions lead you to any conclusions or a fix?

**Comment by ArielFerreiro** [comment]
Hi Ray, it seems the people creating the bundle in my company were touching the manifest somehow and creating this mistake. We can close this.
