### ISSUE TITLE
[firebase_crashlytics] incompatible with other firebase plugins

### ISSUE THREAD

**Issue by ninnepinne** [flutter/flutter#30037]
Starting a fresh project and following plugin instructions will work - as long as no other firebase plugins are added.

As soon as another firebase plugin (latest version) is added to the project the android project fails.

It seems like the google services version differs between the firebase plugins.

```dependencies:
  flutter:
    sdk: flutter
  firebase_crashlytics: ^0.0.2
  firebase_core: ^0.3.1+1
  firebase_analytics: ^2.0.3
```
Above will result in:
```FAILURE: Build failed with an exception.
* What went wrong:
Execution failed for task ':app:preDebugBuild'.
> Android dependency 'com.google.firebase:firebase-core' has different version for the compile (16.0.4) and runtime (16.0.8) classpath. You should manually set the same version via DependencyResolution
```

And in a project with androidX activated it gets worse:
```
D8: Interface `com.google.android.gms.internal.measurement.zzq(classpath class)` used as super class of `com.google.android.gms.internal.measurement.zztr`.
D8: Interface `com.google.android.gms.internal.measurement.zzq(classpath class)` used as super class of `com.google.android.gms.internal.measurement.zzw`.
D8: Type com.google.android.gms.measurement.internal.zzdy is referenced as an interface from `com.google.firebase.analytics.zzb`.
D8: Interface `com.google.android.gms.internal.measurement.zzq(classpath class)` used as super class of `com.google.android.gms.measurement.internal.zzai`.
D8: Type com.google.android.gms.measurement.internal.zzdb is referenced as an interface from `com.google.android.gms.measurement.internal.AppMeasurementDynamiteService$zzb`.
D8: Type com.google.android.gms.measurement.internal.zzda is referenced as an interface from `com.google.android.gms.measurement.internal.AppMeasurementDynamiteService$zza`.
D8: Type com.google.android.gms.measurement.internal.zzfi is referenced as an interface from `com.google.android.gms.measurement.AppMeasurementService`.
D8: Type com.google.android.gms.internal.measurement.zzw is referenced as an interface from `com.google.android.gms.internal.measurement.zzx`.
D8: Type com.google.android.gms.measurement.internal.zzv is referenced as an interface from `com.google.android.gms.measurement.internal.zzbs`.
D8: Interface `com.google.android.gms.internal.measurement.zzu(classpath class)` used as super class of `com.google.android.gms.internal.measurement.zzaa$zzb`.
D8: Type com.google.android.gms.measurement.internal.zzam is referenced as an interface from `com.google.android.gms.measurement.internal.zzan`.
D8: Type com.google.android.gms.measurement.internal.zzbr is referenced as an interface from `com.google.android.gms.measurement.AppMeasurementInstallReferrerReceiver`.
D8: Type com.google.android.gms.measurement.internal.zzba is referenced as an interface from `com.google.android.gms.measurement.internal.zzfv`.
D8: Type com.google.android.gms.measurement.internal.zzv is referenced as an interface from `com.google.android.gms.measurement.internal.zzu`.
com.android.builder.dexing.DexArchiveBuilderException: com.android.builder.dexing.DexArchiveBuilderException: Failed to process /Users/fredrik.dahlen/.gradle/caches/transforms-1/files-1.1/jetified-play-services-measurement-16.4.0.aar/598ba4a91b2eb70e339100a889aff447/jars/classes.jar
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at java.util.concurrent.ForkJoinTask.getThrowableException(ForkJoinTask.java:593)
	at java.util.concurrent.ForkJoinTask.reportException(ForkJoinTask.java:677)
	at java.util.concurrent.ForkJoinTask.join(ForkJoinTask.java:720)
	at com.android.ide.common.internal.WaitableExecutor.waitForTasksWithQuickFail(WaitableExecutor.java:146)
	at com.android.build.gradle.internal.transforms.DexArchiveBuilderTransform.transform(DexArchiveBuilderTransform.java:420)
	at com.android.build.gradle.internal.pipeline.TransformTask$2.call(TransformTask.java:239)
	at com.android.build.gradle.internal.pipeline.TransformTask$2.call(TransformTask.java:235)
	at com.android.builder.profile.ThreadRecorder.record(ThreadRecorder.java:102)
	at com.android.build.gradle.internal.pipeline.TransformTask.transform(TransformTask.java:230)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:73)
	at org.gradle.api.internal.project.taskfactory.IncrementalTaskAction.doExecute(IncrementalTaskAction.java:50)
	at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:39)
	at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:26)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$1.run(ExecuteActionsTaskExecuter.java:131)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:300)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:292)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:174)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:90)
	at org.gradle.internal.operations.DelegatingBuildOperationExecutor.run(DelegatingBuildOperationExecutor.java:31)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:120)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:99)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:77)
	at org.gradle.api.internal.tasks.execution.OutputDirectoryCreatingTaskExecuter.execute(OutputDirectoryCreatingTaskExecuter.java:51)
	at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:59)
	at org.gradle.api.internal.tasks.execution.ResolveTaskOutputCachingStateExecuter.execute(ResolveTaskOutputCachingStateExecuter.java:54)
	at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:59)
	at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:101)
	at org.gradle.api.internal.tasks.execution.FinalizeInputFilePropertiesTaskExecuter.execute(FinalizeInputFilePropertiesTaskExecuter.java:44)
	at org.gradle.api.internal.tasks.execution.CleanupStaleOutputsExecuter.execute(CleanupStaleOutputsExecuter.java:91)
	at org.gradle.api.internal.tasks.execution.ResolveTaskArtifactStateTaskExecuter.execute(ResolveTaskArtifactStateTaskExecuter.java:62)
	at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:59)
	at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:54)
	at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)
	at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:34)
	at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.run(EventFiringTaskExecuter.java:51)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:300)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:292)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:174)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:90)
	at org.gradle.internal.operations.DelegatingBuildOperationExecutor.run(DelegatingBuildOperationExecutor.java:31)
	at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter.execute(EventFiringTaskExecuter.java:46)
	at org.gradle.execution.taskgraph.LocalTaskInfoExecutor.execute(LocalTaskInfoExecutor.java:42)
	at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareWorkItemExecutor.execute(DefaultTaskExecutionGraph.java:277)
	at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareWorkItemExecutor.execute(DefaultTaskExecutionGraph.java:262)
	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$ExecutorWorker$1.execute(DefaultTaskPlanExecutor.java:135)
	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$ExecutorWorker$1.execute(DefaultTaskPlanExecutor.java:130)
	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$ExecutorWorker.execute(DefaultTaskPlanExecutor.java:200)
	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$ExecutorWorker.executeWithWork(DefaultTaskPlanExecutor.java:191)
	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$ExecutorWorker.run(DefaultTaskPlanExecutor.java:130)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
	at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:46)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)
	at java.lang.Thread.run(Thread.java:745)
Caused by: com.android.builder.dexing.DexArchiveBuilderException: Failed to process /Users/fredrik.dahlen/.gradle/caches/transforms-1/files-1.1/jetified-play-services-measurement-16.4.0.aar/598ba4a91b2eb70e339100a889aff447/jars/classes.jar
	at com.android.build.gradle.internal.transforms.DexArchiveBuilderTransform.launchProcessing(DexArchiveBuilderTransform.java:909)
	at com.android.build.gradle.internal.transforms.DexArchiveBuilderTransform.lambda$convertToDexArchive$6(DexArchiveBuilderTransform.java:834)
	at java.util.concurrent.ForkJoinTask$AdaptedCallable.exec(ForkJoinTask.java:1424)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
Caused by: com.android.builder.dexing.DexArchiveBuilderException: Error while dexing.
	at com.android.builder.dexing.D8DexArchiveBuilder.getExceptionToRethrow(D8DexArchiveBuilder.java:124)
	at com.android.builder.dexing.D8DexArchiveBuilder.convert(D8DexArchiveBuilder.java:101)
	at com.android.build.gradle.internal.transforms.DexArchiveBuilderTransform.launchProcessing(DexArchiveBuilderTransform.java:904)
	... 6 more
Caused by: com.android.tools.r8.CompilationFailedException: Compilation failed to complete
	at com.android.tools.r8.utils.ExceptionUtils.withCompilationHandler(ExceptionUtils.java:70)
	at com.android.tools.r8.utils.ExceptionUtils.withD8CompilationHandler(ExceptionUtils.java:43)
	at com.android.tools.r8.D8.run(D8.java:94)
	at com.android.builder.dexing.D8DexArchiveBuilder.convert(D8DexArchiveBuilder.java:99)
	... 7 more
Caused by: com.android.tools.r8.utils.AbortException: Error: Type com.google.android.gms.measurement.internal.zzv is referenced as an interface from `com.google.android.gms.measurement.internal.zzbs`.
	at com.android.tools.r8.utils.Reporter.failIfPendingErrors(Reporter.java:89)
	at com.android.tools.r8.utils.Reporter.fatalError(Reporter.java:60)
	at com.android.tools.r8.utils.ExceptionUtils.withCompilationHandler(ExceptionUtils.java:64)
	... 10 more


FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:transformClassesWithDexBuilderForDebug'.
> com.android.build.api.transform.TransformException: com.android.builder.dexing.DexArchiveBuilderException: com.android.builder.dexing.DexArchiveBuilderException: Failed to process /Users/fredrik.dahlen/.gradle/caches/transforms-1/files-1.1/jetified-play-services-measurement-16.4.0.aar/598ba4a91b2eb70e339100a889aff447/jars/classes.jar
```

Flutter Doctor output:
```
[✓] Flutter (Channel master, v1.4.2-pre.3, on Mac OS X 10.14.3 18D109, locale en-SE)
    • Flutter version 1.4.2-pre.3 at /Users/fredrik.dahlen/DEV/flutter
    • Framework revision bafe7cbbb4 (9 hours ago), 2019-03-26 21:40:53 -0700
    • Engine revision 0d83a2ecd1
    • Dart version 2.2.1 (build 2.2.1-dev.2.0 None)

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/fredrik.dahlen/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = /Users/fredrik.dahlen/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.1, Build version 10B61
    • ios-deploy 2.0.0
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 33.4.1
    • Dart plugin version 182.5215
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)

[✓] VS Code (version 1.32.3)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 2.23.1

[✓] Connected device (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 9 (API 28) (emulator)

• No issues found!
```

Please give feedback or fix as soon as possible.
/Thanks

**Comment by ninnepinne** [comment]
@zoechi Please have a look at this.
A blocking issue.
/Thanks

**Comment by ninnepinne** [comment]
Ok, dug deeper and forked the plugin.

In the crashlytics repository's Android/build.gradle file the dependencies are:
```
dependencies {
    implementation 'com.google.firebase:firebase-core:16.0.8' <------ culprit
    implementation 'com.crashlytics.sdk.android:crashlytics:2.9.9'
}
```
Removing that line while having the flutter firebase_core plugin in project does the trick...
Changed to a local version without that line and everything is working OK.

None of the other flutter firebase plugins have this dependency.

A bit confused about why that line is there...
Should this plugin work without the core package?
That version is higher than the latest flutter firebase_core package.
The example and documentation does indeed NOT use the firebase_core package.

I think you have to whip this plugin int line with the other firebase plugins and inline your documentation.

See your firebase instructions: [https://firebase.google.com/docs/flutter/setup](https://firebase.google.com/docs/flutter/setup)

It states that the firebase_core plugin should always be added...

Also I think you should set up integration tests for your plugins so that they will work together...

Thanks!

**Comment by volkangurol** [comment]
Thank you @ninnepinne, i can confirm that removing that firebase:firebase-core:16.0.8 dependency fixes issue. Release this version please. (i dont like editing library : ) )

**Comment by g3rrydanc3** [comment]
+1 same problem

**Comment by caroline171** [comment]
+1 same problem
please release it

**Comment by gritYCDA** [comment]
> Ok, dug deeper and forked the plugin.
> 
> In the crashlytics repository's Android/build.gradle file the dependencies are:
> 
> ```
> dependencies {
>     implementation 'com.google.firebase:firebase-core:16.0.8' <------ culprit
>     implementation 'com.crashlytics.sdk.android:crashlytics:2.9.9'
> }
> ```
> 
> Removing that line while having the flutter firebase_core plugin in project does the trick...
> Changed to a local version without that line and everything is working OK.
> 
> None of the other flutter firebase plugins have this dependency.
> 
> A bit confused about why that line is there...
> Should this plugin work without the core package?
> That version is higher than the latest flutter firebase_core package.
> The example and documentation does indeed NOT use the firebase_core package.
> 
> I think you have to whip this plugin int line with the other firebase plugins and inline your documentation.
> 
> See your firebase instructions: https://firebase.google.com/docs/flutter/setup
> 
> It states that the firebase_core plugin should always be added...
> 
> Also I think you should set up integration tests for your plugins so that they will work together...
> 
> Thanks!

catch it !!!!!!! i love you

**Comment by kroikie** [comment]
@ninnepinne

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/390. Any further collaboration will be done there.
