### ISSUE TITLE
flutter aar into android project Error converting bytecode to dex

### ISSUE THREAD

**Issue by PingShen** [flutter/flutter#30033]
I build my flutter module into my project.
and use the retrolambda plugin,as below is the config:
        classpath 'com.android.tools.build:gradle:2.3.1'
        classpath 'me.tatarka:gradle-retrolambda:3.3.1'
apply plugin: 'me.tatarka.retrolambda'
 compileOptions {
        targetCompatibility JavaVersion.VERSION_1_8
        sourceCompatibility JavaVersion.VERSION_1_8
    }
but when build,meet a exception:
Error converting bytecode to dex:
Cause: Dex cannot parse version 52 byte code.
This is caused by library dependencies that have been compiled using Java 8 or above.
If you are using the 'java' gradle plugin in a library submodule add 
targetCompatibility = '1.7'
sourceCompatibility = '1.7'
to that submodule's build.gradle file.
Message{kind=ERROR, text=Error converting bytecode to dex:
Cause: Dex cannot parse version 52 byte code.
This is caused by library dependencies that have been compiled using Java 8 or above.
If you are using the 'java' gradle plugin in a library submodule add 
targetCompatibility = '1.7'
sourceCompatibility = '1.7'
to that submodule's build.gradle file., sources=[Unknown source file], original message=UNEXPECTED TOP-LEVEL EXCEPTION:
java.lang.RuntimeException: Exception parsing classes
	at com.android.dx.command.dexer.Main.processClass(Main.java:781)
	at com.android.dx.command.dexer.Main.processFileBytes(Main.java:747)
	at com.android.dx.command.dexer.Main.access$1200(Main.java:88)
	at com.android.dx.command.dexer.Main$FileBytesConsumer.processFileBytes(Main.java:1689)
	at com.android.dx.cf.direct.ClassPathOpener.processArchive(ClassPathOpener.java:284)
	at com.android.dx.cf.direct.ClassPathOpener.processOne(ClassPathOpener.java:166)
	at com.android.dx.cf.direct.ClassPathOpener.process(ClassPathOpener.java:144)
	at com.android.dx.command.dexer.Main.processOne(Main.java:695)
	at com.android.dx.command.dexer.Main.processAllFiles(Main.java:592)
	at com.android.dx.command.dexer.Main.runMultiDex(Main.java:376)
	at com.android.dx.command.dexer.Main.run(Main.java:290)
	at com.android.builder.internal.compiler.DexWrapper.run(DexWrapper.java:54)
	at com.android.builder.core.DexByteCodeConverter.lambda$dexInProcess$0(DexByteCodeConverter.java:174)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: com.android.dx.cf.iface.ParseException: bad class file magic (cafebabe) or version (0034.0000)
	at com.android.dx.cf.direct.DirectClassFile.parse0(DirectClassFile.java:476)
	at com.android.dx.cf.direct.DirectClassFile.parse(DirectClassFile.java:406)
	at com.android.dx.cf.direct.DirectClassFile.parseToInterfacesIfNecessary(DirectClassFile.java:388)
	at com.android.dx.cf.direct.DirectClassFile.getMagic(DirectClassFile.java:251)
	at com.android.dx.command.dexer.Main.parseClass(Main.java:793)
	at com.android.dx.command.dexer.Main.access$1600(Main.java:88)
	at com.android.dx.command.dexer.Main$ClassParserTask.call(Main.java:1728)
	at com.android.dx.command.dexer.Main.processClass(Main.java:779)
	... 16 more
, tool name=Optional.of(Dex)}

**Comment by xster** [comment]
Seems like a Java 7 vs 8 issue. Can you share some repro steps?

**Comment by Hixie** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
  
Thanks for your contribution.
