### ISSUE TITLE
CupertinoPageScaffold throws a gesture error

### ISSUE THREAD

**Issue by AndreHaueisen** [flutter/flutter#30067]
## Steps to Reproduce

1. Install Flushbar `flushbar: ^1.3.0`
2. Run this code
```
class MyApp extends StatelessWidget {
  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return CupertinoApp(
      title: 'Flutter Demo',
      home: BugExample(),
    );
  }
}

class BugExample extends StatelessWidget{

  void _showFlushbar(BuildContext buildContext) {
    Flushbar(
      borderRadius: 8,
      message: "Lorem Ipsum is simply dummy text of the printing and typesetting industry",
    )..show(buildContext);
  }

  @override
  Widget build(BuildContext context) {
    return CupertinoPageScaffold(
      child: Center(
        child: CupertinoButton(
          onPressed: () {
            _showFlushbar(context);
          },
          child: Text("Create first"),
        ),
      ),
    );
  }
}
```
3. Click the button and an error will show
4. Comment out `borderRadius: 8` and everything works nice

The problem here is that the borderRadius issue only happens when working with `CupertinoPageScaffold`. If we use material's `Scaffold` everything works nice.

## Error

```
flutter: ══╡ EXCEPTION CAUGHT BY GESTURE ╞═══════════════════════════════════════════════════════════════════
flutter: The following assertion was thrown while handling a gesture:
flutter: type 'int' is not a subtype of type 'double'
flutter:
flutter: Either the assertion indicates an error in the framework itself, or we should provide substantially
flutter: more information in this error message to help you determine and fix the underlying cause.
flutter: In either case, please report this assertion by filing a bug on GitHub:
flutter:   https://github.com/flutter/flutter/issues/new?template=BUG.md
flutter:
flutter: When the exception was thrown, this was the stack:
flutter: #0      new Flushbar (package:flushbar/flushbar.dart:375:27)
flutter: #1      BugExample._showFlushbar (package:flush_tester/main.dart:21:5)
flutter: #2      BugExample.build.<anonymous closure> (package:flush_tester/main.dart:33:13)
flutter: #3      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:166:24)
flutter: #4      TapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:246:9)
flutter: #5      TapGestureRecognizer.handlePrimaryPointer (package:flutter/src/gestures/tap.dart:175:7)
flutter: #6      PrimaryPointerGestureRecognizer.handleEvent (package:flutter/src/gestures/recognizer.dart:436:9)
flutter: #7      PointerRouter._dispatch (package:flutter/src/gestures/pointer_router.dart:73:12)
flutter: #8      PointerRouter.route (package:flutter/src/gestures/pointer_router.dart:101:11)
flutter: #9      _WidgetsFlutterBinding&BindingBase&GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:214:19)
flutter: #10     _WidgetsFlutterBinding&BindingBase&GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:192:22)
flutter: #11     _WidgetsFlutterBinding&BindingBase&GestureBinding._handlePointerEvent (package:flutter/src/gestures/binding.dart:149:7)
flutter: #12     _WidgetsFlutterBinding&BindingBase&GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:101:7)
flutter: #13     _WidgetsFlutterBinding&BindingBase&GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:85:7)
flutter: #17     _invoke1 (dart:ui/hooks.dart:223:10)
flutter: #18     _dispatchPointerDataPacket (dart:ui/hooks.dart:144:5)
flutter: (elided 3 frames from package dart:async)
flutter:
flutter: Handler: onTap
flutter: Recognizer:
flutter:   TapGestureRecognizer#50f84(debugOwner: GestureDetector, state: possible, won arena, finalPosition:
flutter:   Offset(227.0, 450.5), sent tap down)
flutter: ════════════════════════════════════════════════════════════════════════════════════════════════════
```

## Flutter Doctor

```
[✓] Flutter (Channel beta, v1.3.8, on Mac OS X 10.14.4 18E226, locale en-BR)
    • Flutter version 1.3.8 at /Users/andrehaueisen/Development/flutter
    • Framework revision e5b1ed7a7f (3 weeks ago), 2019-03-06 14:23:37 -0800
    • Engine revision f4951df193
    • Dart version 2.2.1 (build 2.2.1-dev.0.0 571ea80e11)

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/andrehaueisen/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.2, Build version 10E125
    • ios-deploy 1.9.4
    • CocoaPods version 1.6.0

[✓] Android Studio (version 3.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 33.4.1
    • Dart plugin version 182.5215
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)

[✓] Connected device (2 available)
    • XT1058    • 0425187216                           • android-arm • Android 5.1 (API 22)
    • iPhone Xʀ • 2092F85D-2A4B-41FB-8948-7920B3448797 • ios         • com.apple.CoreSimulator.SimRuntime.iOS-12-2 (simulator)

• No issues found!

```
## Extra Info
Flushbar works by pushing a new route to be able show the notification.

**Comment by AndreHaueisen** [comment]
Forgot the link to [Flushbar](https://pub.dartlang.org/packages/flushbar#-installing-tab-)

**Comment by xster** [comment]
I'm not seeing anything relating to the framework. If your code expects a double, pass it a double (e.g. 8.0).

**Comment by AndreHaueisen** [comment]
Ok. That is embarrassing. Sorry about wasting your time. I did not realize I was testing with two different values.
