### ISSUE TITLE
/Pods/!ProtoCompiler/protoc: No such file or directory

### ISSUE THREAD

**Issue by baoolong** [flutter/flutter#30086]
## Steps to Reproduce:

I bridged the c code in the ios（swift） module, and then my program can not be compiled, the log is 

```
Launching lib/main.dart on iPhone 6s in debug mode...
Running pod install...
CocoaPods' output:
↳
      Preparing

    Analyzing dependencies

    Inspecting targets to integrate
      Using `ARCHS` setting to build architectures of target `Pods-Runner`: (``)

    Finding Podfile changes
      A Flutter
      A flutter_blue
      A google_maps_flutter

    Fetching external sources
    -> Fetching podspec for `Flutter` from `.symlinks/flutter/ios`
    -> Fetching podspec for `flutter_blue` from `.symlinks/plugins/flutter_blue/ios`
    -> Fetching podspec for `google_maps_flutter` from `.symlinks/plugins/google_maps_flutter/ios`

    Resolving dependencies of `Podfile`

    Comparing resolved specification to the sandbox manifest
      A !ProtoCompiler
      A Flutter
      A GoogleMaps
      A Protobuf
      A flutter_blue
      A google_maps_flutter

    Downloading dependencies

    -> Installing !ProtoCompiler (3.6.1)
      > Copying !ProtoCompiler from `/Users/baolong/Library/Caches/CocoaPods/Pods/Release/!ProtoCompiler/3.6.1-5d6b6` to `Pods/!ProtoCompiler`

    -> Installing Flutter (1.0.0)

    -> Installing GoogleMaps (2.7.0)
      > Copying GoogleMaps from `/Users/baolong/Library/Caches/CocoaPods/Pods/Release/GoogleMaps/2.7.0-f79af` to `Pods/GoogleMaps`

    -> Installing Protobuf (3.7.0)
      > Copying Protobuf from `/Users/baolong/Library/Caches/CocoaPods/Pods/Release/Protobuf/3.7.0-7a877` to `Pods/Protobuf`

    -> Installing flutter_blue (0.0.1)
     > Running prepare command
       $ /bin/bash -c  set -e mkdir -p gen /Users/baolong/AndroidStudioProjects/swagger_flutter/Pods/!ProtoCompiler/protoc         --objc_out=gen         --proto_path=../protos         ../protos/*.proto
    [!] /bin/bash -c 
    set -e
    mkdir -p gen
    /Users/baolong/AndroidStudioProjects/swagger_flutter/Pods/!ProtoCompiler/protoc         --objc_out=gen         --proto_path=../protos         ../protos/*.proto

    /bin/bash: line 3: /Users/baolong/AndroidStudioProjects/swagger_flutter/Pods/!ProtoCompiler/protoc: No such file or directory

    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.6.1/lib/cocoapods/executable.rb:69:in `execute_command'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.6.1/lib/cocoapods/executable.rb:27:in `block in executable'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.6.1/lib/cocoapods/installer/pod_source_preparer.rb:66:in `block (2 levels) in run_prepare_command'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.6.1/lib/cocoapods/installer/pod_source_preparer.rb:60:in `chdir'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.6.1/lib/cocoapods/installer/pod_source_preparer.rb:60:in `block in run_prepare_command'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.6.1/lib/cocoapods/user_interface.rb:64:in `section'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.6.1/lib/cocoapods/installer/pod_source_preparer.rb:59:in `run_prepare_command'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.6.1/lib/cocoapods/installer/pod_source_preparer.rb:37:in `prepare!'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.6.1/lib/cocoapods/installer/pod_source_installer.rb:63:in `install!'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.6.1/lib/cocoapods/installer.rb:426:in `install_source_of_pod'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.6.1/lib/cocoapods/installer.rb:377:in `block (2 levels) in install_pod_sources'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.6.1/lib/cocoapods/user_interface.rb:86:in `titled_section'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.6.1/lib/cocoapods/installer.rb:376:in `block in install_pod_sources'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.6.1/lib/cocoapods/installer.rb:359:in `each'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.6.1/lib/cocoapods/installer.rb:359:in `install_pod_sources'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.6.1/lib/cocoapods/installer.rb:189:in `block in download_dependencies'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.6.1/lib/cocoapods/user_interface.rb:64:in `section'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.6.1/lib/cocoapods/installer.rb:188:in `download_dependencies'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.6.1/lib/cocoapods/installer.rb:137:in `install!'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.6.1/lib/cocoapods/command/install.rb:48:in `run'
    /Library/Ruby/Gems/2.3.0/gems/claide-1.0.2/lib/claide/command.rb:334:in `run'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.6.1/lib/cocoapods/command.rb:52:in `run'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.6.1/bin/pod:55:in `<top (required)>'
    /usr/local/bin/pod:22:in `load'
    /usr/local/bin/pod:22:in `<main>'

Error output from CocoaPods:
↳
       /bin/bash: line 3: /Users/baolong/AndroidStudioProjects/swagger_flutter/Pods/!ProtoCompiler/protoc: No such file or directory

    [!] Automatically assigning platform `ios` with version `8.0` on target `Runner` because no platform was specified. Please specify a platform for this target in your Podfile. See `https://guides.cocoapods.org/syntax/podfile.html#platform`.

Error running pod install
Error launching application on iPhone 6s.
```

I found that  “/ios/”  is missing from the path.
```
Error output from CocoaPods:
↳
       /bin/bash: line 3: /Users/baolong/AndroidStudioProjects/swagger_flutter/Pods/!ProtoCompiler/protoc: No such file or directory
```

## Logs

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel beta, v1.3.8, on Mac OS X 10.14.3 18D109, locale zh-Hans-CN)
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[✓] iOS toolchain - develop for iOS devices (Xcode 10.1)
[✓] Android Studio (version 3.3)
[✓] Connected device (1 available)

• No issues found!

```

**Comment by asrinagesh** [comment]
Did you find the solution that fixed this issue? @baoolong

**Comment by ferryirawan** [comment]
same bug, any solution for this?

**Comment by ferdiamg** [comment]
Got the same issues, still there, no fix?

**Comment by Sunbreak** [comment]
Seems related to https://github.com/pauldemarco/flutter_blue/issues/292
