### ISSUE TITLE
gclient sync fail for 'Could not find package matching arguments: Instance of 'OptionsRevision', OSType.mac, null'

### ISSUE THREAD

**Issue by zhouyuanbin** [flutter/flutter#30151]
## Steps to Reproduce

I have successful built the flutter engine early this month.  But recently when I updated my android studio and build tools, I got error when execute `gclient sync` as follow. i have check the isses: [27963](https://github.com/flutter/flutter/issues/27963).  How can i solve the error?

## Logs

```
HERBERTZHOU-MC0:engine herbertzhou$ gclient sync
Syncing projects: 100% (86/86), done.                                                      

________ running '../../../third_party/dart/tools/sdks/dart-sdk/bin/pub get' in '/Users/herbertzhou/develop/flutter/engine/src/tools/android/android_sdk_downloader'
Resolving dependencies...
Got dependencies!

________ running 'src/third_party/dart/tools/sdks/dart-sdk/bin/dart --enable-asserts src/tools/android/android_sdk_downloader/lib/main.dart -y --out=src/third_party/android_tools --platform=28 --platform-revision=6 --build-tools-version=28.0.3 --platform-tools-version=28.0.1 --tools-version=26.1.1 --ndk-version=19.1.5304403' in '/Users/herbertzhou/develop/flutter/engine'
src/tools/android/android_sdk_downloader/lib/main.dart:1: Warning: Interpreting this as package URI, 'package:android_sdk_downloader/main.dart'.
Downloading Android SDK and NDK artifacts...
Skipping Android SDK Platform 28, checksum matches current asset.
Skipping Android SDK Build-Tools 28.0.3, checksum matches current asset.
Skipping Android SDK Tools, checksum matches current asset.
Unhandled exception:
Bad state: Could not find package matching arguments: Instance of 'OptionsRevision', OSType.mac, null
#0      downloadArchive (package:android_sdk_downloader/src/http.dart:94:5)
<asynchronous suspension>
#1      main (package:android_sdk_downloader/main.dart:159:15)
#2      _RootZone.runUnary (dart:async/zone.dart:1379:54)
#3      _FutureListener.handleValue (dart:async/future_impl.dart:129:18)
#4      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:642:45)
#5      Future._propagateToListeners (dart:async/future_impl.dart:671:32)
#6      Future._complete (dart:async/future_impl.dart:476:7)
#7      _SyncCompleter.complete (dart:async/future_impl.dart:51:12)
#8      _AsyncAwaitCompleter.complete (dart:async/runtime/libasync_patch.dart:28:18)
#9      _completeOnAsyncReturn (dart:async/runtime/libasync_patch.dart:295:13)
#10     loadChecksums (package:android_sdk_downloader/src/checksums.dart)
#11     _RootZone.runUnary (dart:async/zone.dart:1379:54)
#12     _FutureListener.handleValue (dart:async/future_impl.dart:129:18)
#13     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:642:45)
#14     Future._propagateToListeners (dart:async/future_impl.dart:671:32)
#15     Future._completeWithValue (dart:async/future_impl.dart:486:5)
#16     Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:516:7)
#17     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#18     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#19     _runPendingImmediateCallback (dart:isolate/runtime/libisolate_patch.dart:115:13)
#20     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:172:5)
Error: Command 'src/third_party/dart/tools/sdks/dart-sdk/bin/dart --enable-asserts src/tools/android/android_sdk_downloader/lib/main.dart -y --out=src/third_party/android_tools --platform=28 --platform-revision=6 --build-tools-version=28.0.3 --platform-tools-version=28.0.1 --tools-version=26.1.1 --ndk-version=19.1.5304403' returned non-zero exit status 255 in /Users/herbertzhou/develop/flutter/engine
```

```
HERBERTZHOU-MC0:engine herbertzhou$ flutter doctor -v
[✓] Flutter (Channel dev, v1.4.4, on Mac OS X 10.14 18A391, locale zh-Hans-CN)
    • Flutter version 1.4.4 at /Users/herbertzhou/develop/flutter/flutter
    • Framework revision 3b3f6c7a04 (30 hours ago), 2019-03-27 13:56:23 -0700
    • Engine revision 0d83a2ecd1
    • Dart version 2.2.1 (build 2.2.1-dev.2.0 None)

[✓] Android toolchain - develop for Android devices (Android SDK version
    29.0.0-rc1)
    • Android SDK at /Users/herbertzhou/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling
      support)
    • Platform android-28, build-tools 29.0.0-rc1
    • ANDROID_HOME = /Users/herbertzhou/Library/Android/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_152-release-1248-b01)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.1, Build version 10B61
    • ios-deploy 1.9.4
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 33.4.1
    • Dart plugin version 182.5215
    • Java version OpenJDK Runtime Environment (build
      1.8.0_152-release-1248-b01)

[✓] VS Code (version 1.32.3)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 2.24.0

[✓] Connected device (1 available)
    • iPhone XR • A6ABD33A-78F5-4837-ADEE-7E9474E53A14 • ios • iOS 12.1
      (simulator)

• No issues found!

```

**Comment by ryansong** [comment]
Have the same problem, it seems something wrong about Android NDK.

**Comment by zhouyuanbin** [comment]
> Have the same problem, it seems something wrong about Android NDK.

@ryansong did you solved this problem?

**Comment by escamoteur** [comment]
Hi, just want to check if this is still a problem for you.

**Comment by iapicca** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
  
Thanks for your contribution.

**Comment by AidenCang** [comment]
The android development tool version configured in the flutter DEPS file could not be found.
Modify the src/flutter/DEPS file
  {
    'name': 'download_android_tools',
    'pattern': '.',
    'condition': 'host_os == "mac" or host_os == "linux"',
    'action': [
        'src/third_party/dart/tools/sdks/dart-sdk/bin/dart', # this hook _must_ be run _after_ the dart hook.
        '--enable-asserts',
        'src/tools/android/android_sdk_downloader/lib/main.dart',
        '-y', # Accept licenses
        '--out=src/third_party/android_tools',
        '--platform=28',
        '--platform-revision=6',
        '--build-tools-version=28.0.3',
        '--platform-tools-version=29.0.5',
        '--tools-version=25.2.5',
        '--ndk-version=21.0.5935234'
    ],
  },

Android:  https://dl.google.com/android/repository/repository2-1.xml
gclient sync is ok?

**Comment by zhouyuanbin** [comment]
@escamoteur @iapicca Finally,I solved this problem. The main reseason is the version of ndk. In other project i use standalone ndk version. so I add the path in  ~/.bash_profile. When I remove this standalone ndk path form ~/.bash_profile, gclient sync finally make success.

**Comment by iapicca** [comment]
I'm glad you solved the problem @zhouyuanbin 
thank you for letting me know
