### ISSUE TITLE
Dart DevTools: Toggling debug banner while Select Widget Mode is enabled crashes the app

### ISSUE THREAD

**Issue by Poup2804** [flutter/flutter#30251]
## Steps to Reproduce

1. Run the app in debug mode
2. Run Dart DevTools and connect to the flutter app
3. Enable Select Widget Mode
4. Click on Hide Debug Banner

## Code

https://gist.github.com/Poup2804/a433e45e813453094b1614e4cb6c9788

## Logs

```
[+204379 ms] I/flutter (10150): ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
[  +39 ms] I/flutter (10150): The following assertion was thrown building Title(color: MaterialColor(primary value:
[   +2 ms] I/flutter (10150): Color(0xff2196f3))):
[   +3 ms] I/flutter (10150): 'package:flutter/src/widgets/widget_inspector.dart': Failed assertion: line 2184 pos 12:
[   +4 ms] I/flutter (10150): 'WidgetInspectorService.instance.selectionChangedCallback == null': is not true.
[  +20 ms] I/flutter (10150):
[   +5 ms] I/flutter (10150): Either the assertion indicates an error in the framework itself, or we should provide substantially
[   +3 ms] I/flutter (10150): more information in this error message to help you determine and fix the underlying cause.
[   +5 ms] I/flutter (10150): In either case, please report this assertion by filing a bug on GitHub:
[   +5 ms] I/flutter (10150):   https://github.com/flutter/flutter/issues/new?template=BUG.md
[   +5 ms] I/flutter (10150):
[   +4 ms] I/flutter (10150): When the exception was thrown, this was the stack:
[  +50 ms] I/flutter (10150): #2      _WidgetInspectorState.initState (package:flutter/src/widgets/widget_inspector.dart:2184:12)
[   +1 ms] I/flutter (10150): #3      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3846:58)
[   +3 ms] I/flutter (10150): #4      ComponentElement.mount (package:flutter/src/widgets/framework.dart:3711:5)
[   +1 ms] I/flutter (10150): #5      Element.inflateWidget (package:flutter/src/widgets/framework.dart:2956:14)
[   +2 ms] I/flutter (10150): #6      Element.updateChild (package:flutter/src/widgets/framework.dart:2759:12)
[   +1 ms] I/flutter (10150): #7      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3747:16)
[   +1 ms] I/flutter (10150): #8      Element.rebuild (package:flutter/src/widgets/framework.dart:3559:5)
[   +1 ms] I/flutter (10150): #9      StatelessElement.update (package:flutter/src/widgets/framework.dart:3796:5)
[   +1 ms] I/flutter (10150): #10     Element.updateChild (package:flutter/src/widgets/framework.dart:2748:15)
[   +1 ms] I/flutter (10150): #11     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3747:16)
[   +1 ms] I/flutter (10150): #12     Element.rebuild (package:flutter/src/widgets/framework.dart:3559:5)
[   +1 ms] I/flutter (10150): #13     ProxyElement.update (package:flutter/src/widgets/framework.dart:4006:5)
[   +2 ms] I/flutter (10150): #14     Element.updateChild (package:flutter/src/widgets/framework.dart:2748:15)
[   +3 ms] I/flutter (10150): #15     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3747:16)
[   +4 ms] I/flutter (10150): #16     Element.rebuild (package:flutter/src/widgets/framework.dart:3559:5)
[   +1 ms] I/flutter (10150): #17     ProxyElement.update (package:flutter/src/widgets/framework.dart:4006:5)
[   +1 ms] I/flutter (10150): #18     Element.updateChild (package:flutter/src/widgets/framework.dart:2748:15)
[   +1 ms] I/flutter (10150): #19     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4883:14)
[   +1 ms] I/flutter (10150): #20     Element.updateChild (package:flutter/src/widgets/framework.dart:2748:15)
[   +1 ms] I/flutter (10150): #21     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3747:16)
[   +2 ms] I/flutter (10150): #22     Element.rebuild (package:flutter/src/widgets/framework.dart:3559:5)
[   +1 ms] I/flutter (10150): #23     StatefulElement.update (package:flutter/src/widgets/framework.dart:3894:5)
[   +1 ms] I/flutter (10150): #24     Element.updateChild (package:flutter/src/widgets/framework.dart:2748:15)
[   +1 ms] I/flutter (10150): #25     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3747:16)
[   +2 ms] I/flutter (10150): #26     Element.rebuild (package:flutter/src/widgets/framework.dart:3559:5)
[   +1 ms] I/flutter (10150): #27     ProxyElement.update (package:flutter/src/widgets/framework.dart:4006:5)
[   +1 ms] I/flutter (10150): #28     Element.updateChild (package:flutter/src/widgets/framework.dart:2748:15)
[   +2 ms] I/flutter (10150): #29     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3747:16)
[   +5 ms] I/flutter (10150): #30     Element.rebuild (package:flutter/src/widgets/framework.dart:3559:5)
[   +1 ms] I/flutter (10150): #31     StatefulElement.update (package:flutter/src/widgets/framework.dart:3894:5)
[   +1 ms] I/flutter (10150): #32     Element.updateChild (package:flutter/src/widgets/framework.dart:2748:15)
[   +2 ms] I/flutter (10150): #33     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3747:16)
[   +1 ms] I/flutter (10150): #34     Element.rebuild (package:flutter/src/widgets/framework.dart:3559:5)
[   +2 ms] I/flutter (10150): #35     ProxyElement.update (package:flutter/src/widgets/framework.dart:4006:5)
[   +1 ms] I/flutter (10150): #36     Element.updateChild (package:flutter/src/widgets/framework.dart:2748:15)
[   +2 ms] I/flutter (10150): #37     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3747:16)
[   +1 ms] I/flutter (10150): #38     Element.rebuild (package:flutter/src/widgets/framework.dart:3559:5)
[   +1 ms] I/flutter (10150): #39     StatefulElement.update (package:flutter/src/widgets/framework.dart:3894:5)
[   +1 ms] I/flutter (10150): #40     Element.updateChild (package:flutter/src/widgets/framework.dart:2748:15)
[   +1 ms] I/flutter (10150): #41     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3747:16)
[   +1 ms] I/flutter (10150): #42     Element.rebuild (package:flutter/src/widgets/framework.dart:3559:5)
[   +1 ms] I/flutter (10150): #43     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2273:33)
[   +1 ms] I/flutter (10150): #44
_WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding&WidgetsBinding.drawFrame
(package:flutter/src/widgets/binding.dart:700:20)
[   +3 ms] I/flutter (10150): #45
_WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding._handlePersistentFrameCallback
(package:flutter/src/rendering/binding.dart:268:5)
[   +3 ms] I/flutter (10150): #46     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._invokeFrameCallback
(package:flutter/src/scheduler/binding.dart:988:15)
[   +3 ms] I/flutter (10150): #47     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.handleDrawFrame
(package:flutter/src/scheduler/binding.dart:928:9)
[   +2 ms] I/flutter (10150): #48     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._handleDrawFrame
(package:flutter/src/scheduler/binding.dart:840:5)
[   +3 ms] I/flutter (10150): #52     _invoke (dart:ui/hooks.dart:209:10)
[   +1 ms] I/flutter (10150): #53     _drawFrame (dart:ui/hooks.dart:168:3)
[   +1 ms] I/flutter (10150): (elided 5 frames from class _AssertionError and package dart:async)
[   +1 ms] I/flutter (10150): ════════════════════════════════════════════════════════════════════════════════════════════════════
```
## flutter analyze

```
Analyzing test_app...
No issues found! (ran in 23.5s)
```
## flutter doctor -v

```
[√] Flutter (Channel stable, v1.2.1, on Microsoft Windows [Versione 10.0.17763.379], locale it-IT)
    • Flutter version 1.2.1 at C:\flutter
    • Framework revision 8661d8aecd (6 weeks ago), 2019-02-14 19:19:53 -0800
    • Engine revision 3757390fa4
    • Dart version 2.1.2 (build 2.1.2-dev.0.0 0a7dcf17eb)

[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at C:\Users\Patrick\AppData\Local\Android\Sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = C:\Users\Patrick\AppData\Local\Android\Sdk\;C:\Program Files\Android\Android Studio\
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)
    • All Android licenses accepted.

[!] Android Studio (version 3.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)

[√] VS Code (version 1.32.3)
    • VS Code at C:\Users\Patrick\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 2.25.0

[√] Connected device (1 available)
    • Fever • 192.168.1.4:5555 • android-arm64 • Android 8.1.0 (API 27)

! Doctor found issues in 1 category.
```

**Comment by devoncarew** [comment]
I no longer see an `assert(WidgetInspectorService.instance.selectionChangedCallback == null)` in `widget_inspector.dart`, so suspect that this issue is obsolete (it looks like this occurred when running Flutter `1.2.1`). Thanks for the report!
