### ISSUE TITLE
Flutter App in Profile mode cannot install on Samsung J7 Prime #19751 #20062

### ISSUE THREAD

**Issue by kyawswa** [flutter/flutter#30318]
I create this issue again because this two issues are already closed.
#19751 #20062

I also facing that issue when I run flutter app in profile mode. I cannot install flutter app exported with profile mode in Samsung J7 Prime.

Here is log file.

Flutter crash report; please file at https://github.com/flutter/flutter/issues.

command
flutter build aot --suppress-analytics --quiet --target /home/kyawswaraung/Projects/Project/lib/main.dart --target-platform android-arm --output-dir /home/kyawswaraung/Projects/Project/build/app/intermediates/flutter/profile --profile

exception
ProcessException: ProcessException: No such file or directory
Command: /home/kyawswaraung/flutter/bin/cache/artifacts/engine/android-arm-profile/linux-x64/gen_snapshot --causal_async_stacks --packages=.packages --deterministic --snapshot_kind=app-aot-blobs --vm_snapshot_data=/home/kyawswaraung/Projects/Project/build/app/intermediates/flutter/profile/vm_snapshot_data --isolate_snapshot_data=/home/kyawswaraung/Projects/Project/build/app/intermediates/flutter/profile/isolate_snapshot_data --vm_snapshot_instructions=/home/kyawswaraung/Projects/Project/build/app/intermediates/flutter/profile/vm_snapshot_instr --isolate_snapshot_instructions=/home/kyawswaraung/Projects/Project/build/app/intermediates/flutter/profile/isolate_snapshot_instr --no-sim-use-hardfp --no-use-integer-division /home/kyawswaraung/Projects/Project/build/app/intermediates/flutter/profile/app.dill

#0      runCommandAndStreamOutput (package:flutter_tools/src/base/process.dart:140:27)
<asynchronous suspension>
#1      GenSnapshot.run (package:flutter_tools/src/base/build.dart:68:12)
#2      AOTSnapshotter.build (package:flutter_tools/src/base/build.dart:194:55)
<asynchronous suspension>
#3      BuildAotCommand.runCommand (package:flutter_tools/src/commands/build_aot.dart:137:56)
<asynchronous suspension>
#4      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:545:18)
<asynchronous suspension>
#5      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:482:33)
<asynchronous suspension>
#6      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:142:29)
<asynchronous suspension>
#7      _rootRun (dart:async/zone.dart:1124:13)
#8      _CustomZone.run (dart:async/zone.dart:1021:19)
#9      _runZoned (dart:async/zone.dart:1516:10)
#10     runZoned (dart:async/zone.dart:1463:12)
#11     AppContext.run (package:flutter_tools/src/base/context.dart:141:18)
<asynchronous suspension>
#12     FlutterCommand.run (package:flutter_tools/src/runner/flutter_command.dart:473:20)
#13     CommandRunner.runCommand (package:args/command_runner.dart:196:27)
<asynchronous suspension>
#14     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:396:21)
<asynchronous suspension>
#15     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:142:29)
<asynchronous suspension>
#16     _rootRun (dart:async/zone.dart:1124:13)
#17     _CustomZone.run (dart:async/zone.dart:1021:19)
#18     _runZoned (dart:async/zone.dart:1516:10)
#19     runZoned (dart:async/zone.dart:1463:12)
#20     AppContext.run (package:flutter_tools/src/base/context.dart:141:18)
<asynchronous suspension>
#21     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:356:19)
<asynchronous suspension>
#22     CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:111:29)
#23     new Future.sync (dart:async/future.dart:224:31)
#24     CommandRunner.run (package:args/command_runner.dart:111:11)
#25     FlutterCommandRunner.run (package:flutter_tools/src/runner/flutter_command_runner.dart:242:18)
#26     run.<anonymous closure> (package:flutter_tools/runner.dart:60:20)
<asynchronous suspension>
#27     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:142:29)
<asynchronous suspension>
#28     _rootRun (dart:async/zone.dart:1124:13)
#29     _CustomZone.run (dart:async/zone.dart:1021:19)
#30     _runZoned (dart:async/zone.dart:1516:10)
#31     runZoned (dart:async/zone.dart:1463:12)
#32     AppContext.run (package:flutter_tools/src/base/context.dart:141:18)
<asynchronous suspension>
#33     runInContext (package:flutter_tools/src/context_runner.dart:48:24)
<asynchronous suspension>
#34     run (package:flutter_tools/runner.dart:51:10)
#35     main (package:flutter_tools/executable.dart:52:9)
<asynchronous suspension>
#36     main (file:///home/kyawswaraung/flutter/packages/flutter_tools/bin/flutter_tools.dart:8:3)
#37     _startIsolate.<anonymous closure> (dart:isolate/runtime/libisolate_patch.dart:298:32)
#38     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:171:12)
flutter doctor
[!] Flutter (Channel beta, v1.2.1, on Linux, locale en_US.UTF-8)
    • Flutter version 1.2.1 at /home/kyawswaraung/flutter
    • Framework revision 8661d8aecd (6 weeks ago), 2019-02-14 19:19:53 -0800
    • Engine revision 3757390fa4
    • Dart version 2.1.2 (build 2.1.2-dev.0.0 0a7dcf17eb)
    ✗ Downloaded executables cannot execute on host.
      See https://github.com/flutter/flutter/issues/6207 for more information
      On Debian/Ubuntu/Mint: sudo apt-get install lib32stdc++6
      On Fedora: dnf install libstdc++.i686
      On Arch: pacman -S lib32-libstdc++5 (you need to enable multilib: https://wiki.archlinux.org/index.php/Official_repositories#multilib)

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /home/kyawswaraung/Android/Sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /snap/android-studio/73/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)
    • All Android licenses accepted.

[✓] Android Studio (version 3.3)
    • Android Studio at /snap/android-studio/73/android-studio
    • Flutter plugin version 33.3.1
    • Dart plugin version 182.5215
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)

[!] IntelliJ IDEA Community Edition (version 2018.3)
    • IntelliJ at /snap/intellij-idea-community/126
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.io/intellij-setup/#installing-the-plugins

[!] IntelliJ IDEA Ultimate Edition (version 2018.3)
    • IntelliJ at /home/kyawswaraung/software/idea-IU-183.4588.61
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.io/intellij-setup/#installing-the-plugins

[✓] Connected device (1 available)
    • SM J700H • 3300a7bd1e49725f • android-arm • Android 6.0.1 (API 23)

! Doctor found issues in 3 categories.

**Comment by kyawswa** [comment]
Debug mode App is perfectly run on Samsung J7 Prime.

**Comment by ThitSarNL** [comment]
yeah but unable to install by apk file

**Comment by ThitSarNL** [comment]
I can pass this error now. 
1. Let it installable, (Setting->BIOMETRICS AND SECURITY->Installl unknown apps->My Files->Allow from this source)
2. Clear internal storage (good if u also clear sd card storage) more than ur app size.
3.  Android Studio->Terminal->Type "flutter build apk" and wait for a while and find the file in folder of YourAppFolder\build\app\outputs\apk\release\app-release.apk
4. (Delete previously installed app if u have and ) Try to install that apk file

**Comment by sameh-khemira** [comment]
And what about installing the app from play store ?

**Comment by BasanthVerma** [comment]
A user complained today that they couldn't install our Flutter App (uploaded as an appBundle) from the play store on Samsung J7 Prime. So I guess this issue still persists. This is what they see:
![fa34fa45-70f3-4877-8d78-12a052f66839](https://user-images.githubusercontent.com/8429864/102642615-ff9e0780-4183-11eb-9514-4ec027efab3f.jpg)
