### ISSUE TITLE
Getting error when trying to run may App

### ISSUE THREAD

**Issue by Kogumelo** [flutter/flutter#30389]
I'm using https://pub.dartlang.org/packages/location and https://pub.dartlang.org/packages/firebase_messaging on my project and i think one of them is getting me in trouble... I have google-service.json file on Android\app directory.

C:\Flutter\WebPCM\versao1.01>flutter run -v
==
`
[  +49 ms] executing: [C:\Flutter\sdk\] git rev-parse --abbrev-ref --symbolic @{u}
[ +175 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[   +3 ms] origin/beta
[   +1 ms] executing: [C:\Flutter\sdk\] git rev-parse --abbrev-ref HEAD
[ +140 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[   +1 ms] beta
[   +1 ms] executing: [C:\Flutter\sdk\] git ls-remote --get-url origin
[ +134 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[        ] executing: [C:\Flutter\sdk\] git log -n 1 --pretty=format:%H
[ +134 ms] Exit code 0 from: git log -n 1 --pretty=format:%H
[        ] e5b1ed7a7f7b85c1877e09a9495681f719be5578
[        ] executing: [C:\Flutter\sdk\] git log -n 1 --pretty=format:%ar
[ +128 ms] Exit code 0 from: git log -n 1 --pretty=format:%ar
[        ] 4 weeks ago
[   +1 ms] executing: [C:\Flutter\sdk\] git describe --match v*.*.* --first-parent --long --tags
[ +183 ms] Exit code 0 from: git describe --match v*.*.* --first-parent --long --tags
[        ] v1.3.8-0-ge5b1ed7a7
[ +679 ms] executing: C:\Users\akogut\AppData\Local\Android\android-sdk\platform-tools\adb.exe devices -l
[  +57 ms] Exit code 0 from: C:\Users\akogut\AppData\Local\Android\android-sdk\platform-tools\adb.exe devices -l
[        ] List of devices attached
           emulator-5554          device product:sdk_gphone_x86 model:Android_SDK_built_for_x86 device:generic_x86 transport_id:1
[ +116 ms] Found plugin barcode_scan at C:\Flutter\sdk\.pub-cache\hosted\pub.dartlang.org\barcode_scan-0.0.8\
[  +26 ms] Found plugin firebase_messaging at C:\Flutter\sdk\.pub-cache\hosted\pub.dartlang.org\firebase_messaging-4.0.0+1\
[  +29 ms] Found plugin location at C:\Flutter\sdk\.pub-cache\hosted\pub.dartlang.org\location-2.3.3\
[  +21 ms] Found plugin shared_preferences at C:\Flutter\sdk\.pub-cache\hosted\pub.dartlang.org\shared_preferences-0.4.3\
[  +57 ms] Found plugin barcode_scan at C:\Flutter\sdk\.pub-cache\hosted\pub.dartlang.org\barcode_scan-0.0.8\
[  +15 ms] Found plugin firebase_messaging at C:\Flutter\sdk\.pub-cache\hosted\pub.dartlang.org\firebase_messaging-4.0.0+1\
[  +12 ms] Found plugin location at C:\Flutter\sdk\.pub-cache\hosted\pub.dartlang.org\location-2.3.3\
[  +11 ms] Found plugin shared_preferences at C:\Flutter\sdk\.pub-cache\hosted\pub.dartlang.org\shared_preferences-0.4.3\
[  +71 ms] C:\Users\akogut\AppData\Local\Android\android-sdk\platform-tools\adb.exe -s emulator-5554 shell getprop
[ +131 ms] ro.hardware = ranchu
[  +49 ms] Using hardware rendering with device Android SDK built for x86. If you get graphics artifacts, consider enabling software renderingwith
           "--enable-software-rendering".
[+1354 ms] Launching lib/main.dart on Android SDK built for x86 in debug mode...
[  +82 ms] Initializing gradle...
[   +1 ms] Using gradle from C:\Flutter\WebPCM\versao1.01\android\gradlew.bat.
[ +302 ms] executing: C:\Flutter\WebPCM\versao1.01\android\gradlew.bat -v
[+1448 ms]
                    ------------------------------------------------------------
                    Gradle 5.2
                    ------------------------------------------------------------

                    Build time:   2019-02-04 11:16:48 UTC
                    Revision:     840644a429c8b8b9ae399867eb1660e3109bc7a3

                    Kotlin DSL:   1.1.3
                    Kotlin:       1.3.20
                    Groovy:       2.5.4
                    Ant:          Apache Ant(TM) version 1.9.13 compiled on July 10 2018
                    JVM:          1.8.0_152-release (JetBrains s.r.o 25.152-b01)
                    OS:           Windows 10 10.0 amd64
[  +14 ms] Initializing gradle... (completed in 1,8s)
[   +3 ms] Resolving dependencies...
[   +1 ms] executing: [C:\Flutter\WebPCM\versao1.01\android\] C:\Flutter\WebPCM\versao1.01\android\gradlew.bat app:properties
[+4544 ms] Resolving dependencies... (completed in 4,5s)
[   +9 ms] * Error running Gradle:
           ProcessException: Process "C:\Flutter\WebPCM\versao1.01\android\gradlew.bat" exited abnormally:
           
             Command: C:\Flutter\WebPCM\versao1.01\android\gradlew.bat app:properties
           
[   +5 ms] "flutter run" took 8.879ms.
[        ] "flutter run" took 8.879ms.
Please review your Gradle project setup in the android/ folder.

#0      throwToolExit (package:flutter_tools/src/base/common.dart:24:3)
#1      _readGradleProject (package:flutter_tools/src/android/gradle.dart:158:7)
<asynchronous suspension>
#2      _gradleProject (package:flutter_tools/src/android/gradle.dart:111:34)
<asynchronous suspension>
#3      getGradleAppOut (package:flutter_tools/src/android/gradle.dart:105:29)
<asynchronous suspension>
#4      AndroidApk.fromAndroidProject (package:flutter_tools/src/application_package.dart:144:23)
<asynchronous suspension>
#5      ApplicationPackageFactory.getPackageForPlatform (package:flutter_tools/src/application_package.dart:42:32)
<asynchronous suspension>
#6      FlutterDevice.runHot (package:flutter_tools/src/resident_runner.dart:290:56)
<asynchronous suspension>
#7      HotRunner.run (package:flutter_tools/src/run_hot.dart:308:39)
<asynchronous suspension>
#8      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:412:37)
<asynchronous suspension>
#9      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:549:18)
#10     _asyncThenWrapperHelper.<anonymous closure> (dart:async/runtime/lib/async_patch.dart:77:64)
#11     _rootRunUnary (dart:async/zone.dart:1132:38)
#12     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#13     _FutureListener.handleValue (dart:async/future_impl.dart:126:18)
#14     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:639:45)
#15     Future._propagateToListeners (dart:async/future_impl.dart:668:32)
#16     Future._complete (dart:async/future_impl.dart:473:7)
#17     _SyncCompleter.complete (dart:async/future_impl.dart:51:12)
#18     _AsyncAwaitCompleter.complete (dart:async/runtime/lib/async_patch.dart:28:18)
#19     _completeOnAsyncReturn (dart:async/runtime/lib/async_patch.dart:294:13)
#20     RunCommand.usageValues (package:flutter_tools/src/commands/run.dart)
#21     _asyncThenWrapperHelper.<anonymous closure> (dart:async/runtime/lib/async_patch.dart:77:64)
#22     _rootRunUnary (dart:async/zone.dart:1132:38)
#23     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#24     _FutureListener.handleValue (dart:async/future_impl.dart:126:18)
#25     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:639:45)
#26     Future._propagateToListeners (dart:async/future_impl.dart:668:32)
#27     Future._complete (dart:async/future_impl.dart:473:7)
#28     _SyncCompleter.complete (dart:async/future_impl.dart:51:12)
#29     _AsyncAwaitCompleter.complete (dart:async/runtime/lib/async_patch.dart:28:18)
#30     _completeOnAsyncReturn (dart:async/runtime/lib/async_patch.dart:294:13)
#31     AndroidDevice.targetPlatform (package:flutter_tools/src/android/android_device.dart)
#32     _asyncThenWrapperHelper.<anonymous closure> (dart:async/runtime/lib/async_patch.dart:77:64)
#33     _rootRunUnary (dart:async/zone.dart:1132:38)
#34     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#35     _FutureListener.handleValue (dart:async/future_impl.dart:126:18)
#36     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:639:45)
#37     Future._propagateToListeners (dart:async/future_impl.dart:668:32)
#38     Future._complete (dart:async/future_impl.dart:473:7)
#39     _SyncCompleter.complete (dart:async/future_impl.dart:51:12)
#40     _AsyncAwaitCompleter.complete.<anonymous closure> (dart:async/runtime/lib/async_patch.dart:33:20)
#41     _rootRun (dart:async/zone.dart:1124:13)
#42     _CustomZone.run (dart:async/zone.dart:1021:19)
#43     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:947:23)
#44     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#45     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#46     _runPendingImmediateCallback (dart:isolate/runtime/lib/isolate_patch.dart:115:13)
#47     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/lib/isolate_patch.dart:172:5)

C:\Flutter\WebPCM\versao1.01>flutter doctor -v
==

[√] Flutter (Channel beta, v1.3.8, on Microsoft Windows [versÃ£o 10.0.17134.648], locale pt-BR)
    • Flutter version 1.3.8 at C:\Flutter\sdk
    • Framework revision e5b1ed7a7f (4 weeks ago), 2019-03-06 14:23:37 -0800
    • Engine revision f4951df193
    • Dart version 2.2.1 (build 2.2.1-dev.0.0 571ea80e11)

[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at C:\Users\akogut\AppData\Local\Android\android-sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = C:\Users\akogut\AppData\Local\Android\android-sdk
    • Java binary at: C:\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)
    • All Android licenses accepted.

[√] Android Studio (version 3.3)
    • Android Studio at C:\Android\Android Studio
    • Flutter plugin version 33.3.1
    • Dart plugin version 182.5215
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)

[√] IntelliJ IDEA Community Edition (version 2017.3)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2017.3.2
    • Flutter plugin version 21.2.3
    • Dart plugin version 173.4548.30

[√] VS Code, 32-bit edition (version 1.32.3)
    • VS Code at C:\Program Files (x86)\Microsoft VS Code
    • Flutter extension version 2.25.0

[√] Connected device (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 8.1.0 (API 27) (emulator)

• No issues found!

android\Build.Gradle:
==

    buildscript {
     ext.kotlin_version = '1.2.51'

     repositories {
        google()
        jcenter()
     }

     dependencies {
        classpath 'com.android.tools.build:gradle:3.3.0'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
        classpath 'com.google.gms:google-services:4.2.0'
     }
    }

    allprojects {
     repositories {
        google()
        jcenter()
     }
    }

    rootProject.buildDir = '../build'
    subprojects {
     project.buildDir = "${rootProject.buildDir}/${project.name}"
    }
    subprojects {
     project.evaluationDependsOn(':app')
    }

    task clean(type: Delete) {
     delete rootProject.buildDir
    }

android\app\Build.Gradle:
==

    def localProperties = new Properties()
    def localPropertiesFile = rootProject.file('local.properties')
    if (localPropertiesFile.exists()) {
        localPropertiesFile.withReader('UTF-8') { reader ->
            localProperties.load(reader)
        }
    }

    def flutterRoot = localProperties.getProperty('flutter.sdk')
    if (flutterRoot == null) {
        throw new GradleException("Flutter SDK not found. Define location with flutter.sdk in the local.properties file.")
    }

    def flutterVersionCode = localProperties.getProperty('flutter.versionCode')
    if (flutterVersionCode == null) {
        flutterVersionCode = '1'
    }

    def flutterVersionName = localProperties.getProperty('flutter.versionName')
    if (flutterVersionName == null) {
        flutterVersionName = '1.0'
    }

    apply plugin: 'com.android.application'
    apply plugin: 'kotlin-android'
    apply from: "$flutterRoot/packages/flutter_tools/gradle/flutter.gradle"

    def keystoreProperties = new Properties()
    def keystorePropertiesFile = rootProject.file('key.properties')
    if (keystorePropertiesFile.exists()) {
        keystoreProperties.load(new FileInputStream(keystorePropertiesFile))
    }

    android {
        compileSdkVersion 28
        buildToolsVersion 28

        lintOptions {
            disable 'InvalidPackage'
        }

        defaultConfig {
            // TODO: Specify your own unique Application ID             (https://developer.android.com/studio/build/application-id.html).
            applicationId "com.kogumelo.Webpcm"
            minSdkVersion 16
            targetSdkVersion 27
            versionCode flutterVersionCode.toInteger()
            versionName flutterVersionName
            testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"
        }

        signingConfigs {
            release {
                keyAlias keystoreProperties['keyAlias']
                keyPassword keystoreProperties['keyPassword']
                storeFile file(keystoreProperties['storeFile'])
                storePassword keystoreProperties['storePassword']
            }
        }
        buildTypes {
            release {
                // signingConfig signingConfigs.debug
                signingConfig signingConfigs.release

                minifyEnabled true
                useProguard true

                proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
            }
        }
    }

    flutter {
        source '../..'
    }

    dependencies {
        testImplementation 'junit:junit:4.12'
        androidTestImplementation 'com.android.support.test:runner:1.0.2'
        androidTestImplementation 'com.android.support.test.espresso:espresso-core:3.0.2'
        implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk7:$kotlin_version"
        implementation 'com.google.firebase:firebase-core:16.0.1'
    }

    apply plugin: 'com.google.gms.google-services'

android\gradle.properties
==

    android.enableJetifier=true
    android.useAndroidX=true
    org.gradle.jvmargs=-Xmx1536M

androidManifest.xml
==
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    package="com.example.flutteros">

    
    <uses-permission android:name="android.permission.INTERNET"/>
    <uses-permission android:name="android.permission.ACCESS_FINE_LOCATION" />
    
    
    <application
        android:name="io.flutter.app.FlutterApplication"
        android:label="WebPCM"
        android:icon="@mipmap/ic_launcher">
        <activity
            android:name=".MainActivity"
            android:launchMode="singleTop"
            android:theme="@style/LaunchTheme"
            android:configChanges="orientation|keyboardHidden|keyboard|screenSize|locale|layoutDirection|fontScale|screenLayout|density"
            android:hardwareAccelerated="true"
            android:windowSoftInputMode="adjustResize">
            
            <meta-data
                android:name="io.flutter.app.android.SplashScreenUntilFirstFrame"
                android:value="true" />
            <intent-filter>
                <action android:name="android.intent.action.MAIN"/>
                <category android:name="android.intent.category.LAUNCHER"/>
            </intent-filter>
            <intent-filter>
                <action android:name="FLUTTER_NOTIFICATION_CLICK" />
                <category android:name="android.intent.category.DEFAULT" />
            </intent-filter>
        </activity>
    </application>
</manifest>

**Comment by Kogumelo** [comment]
Let it be, it was probably because of incompatibilty between Android versions for those Libraries. I've changed "location" to "geo_location_finder" package, recreated my app and now it's working. Unfortunattly, besides Flutter's incredible power, those idiosyncrasies makes us spend 1 hour actually working on our project and 10 hours trying to configure Android-Manifest, Gradle and those other files.
