### ISSUE TITLE
The app  is stuck when i use webview_flutter at IOS

### ISSUE THREAD

**Issue by YouCii** [flutter/flutter#30417]
## Steps to Reproduce

1. A->B->C, B and C are both webview pages.
2. while sliding right slowly at the C page running on ios, the app is stuck.
3. And then the app will always be stuck on this page
![IMG_0103](https://user-images.githubusercontent.com/17899073/55447601-edb6b280-55f6-11e9-99b0-ccb6fca48401.png)

## Logs

```
[+9636 ms] [VERBOSE-2:ui_dart_state.cc(148)] Unhandled Exception: 'package:flutter/src/gestures/converter.dart': Failed assertion: line 155 pos 18: '!state.down': is not true.
[        ] #0      _AssertionError._doThrowNew (dart:core/runtime/lib/errors_patch.dart:40:39)
[        ] #1      _AssertionError._throwNew (dart:core/runtime/lib/errors_patch.dart:36:5)
[        ] #2      PointerEventConverter.expand (package:flutter/src/gestures/converter.dart:155:18)
[        ] #3      _SyncIterator.moveNext (dart:core/runtime/lib/core_patch.dart:152:12)
[        ] #4      ListQueue.addAll (dart:collection/queue.dart:715:25)
[        ] #5      _WidgetsFlutterBinding&BindingBase&GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:83:27)
[        ] #6      _rootRunUnary (dart:async/zone.dart:1136:13)
[        ] #7      _CustomZone.runUnary (dart:async/zone.dart:1029:19)
[        ] #8      _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
[        ] #9      _invoke1 (dart:ui/hooks.dart:223:10)
[        ] #10     _dispatchPointerDataPacket (dart:ui/hooks.dart:144:5)

```

```
No errors.
```

```
[✓] Flutter (Channel beta, v1.3.8, on Mac OS X 10.14.3 18D109, locale zh-Hans-CN)
    • Flutter version 1.3.8 at /Users/YouCii/Library/flutter
    • Framework revision e5b1ed7a7f (4 weeks ago), 2019-03-06 14:23:37 -0800
    • Engine revision f4951df193
    • Dart version 2.2.1 (build 2.2.1-dev.0.0 571ea80e11)

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/YouCii/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.1, Build version 10B61
    • ios-deploy 1.9.4
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 32.0.1
    • Dart plugin version 182.5215
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)

[✓] Connected device (2 available)
    • MI 6       • 69841c30                                 • android-arm64 • Android 8.0.0 (API 26)
    • 宋玉的 iPhone • 68bbf9cff03a77b60ff1005918fc2460c9b49c79 • ios           • iOS 11.4.1

• No issues found!

```

**Comment by YouCii** [comment]
Any one can help me?

**Comment by YouCii** [comment]
```
flutter: ══╡ EXCEPTION CAUGHT BY SCHEDULER LIBRARY ╞═════════════════════════════════════════════════════════
flutter: The following assertion was thrown during a scheduler callback:
flutter: 'package:flutter/src/widgets/heroes.dart': Failed assertion: line 424 pos 12: '() {
flutter:       final Animation<double> initial = initialManifest.animation;
flutter:       assert(initial != null);
flutter:       final HeroFlightDirection type = initialManifest.type;
flutter:       assert(type != null);
flutter:       switch (type) {
flutter:         case HeroFlightDirection.pop:
flutter:           return initial.value == 1.0 && initialManifest.isUserGestureTransition
flutter:               // During user gesture transitions, the animation controller isn't
flutter:               // driving the reverse transition, but should still be in a previously
flutter:               // completed stage with the initial value at 1.0.
flutter:               ? initial.status == AnimationStatus.completed
flutter:               : initial.status == AnimationStatus.reverse;
flutter:         case HeroFlightDirection.push:
flutter:           return initial.value == 0.0 && initial.status == AnimationStatus.forward;
flutter:       }
flutter:       return null;
flutter:     }()': is not true.
flutter:
flutter: Either the assertion indicates an error in the framework itself, or we should provide substantially
flutter: more information in this error message to help you determine and fix the underlying cause.
flutter: In either case, please report this assertion by filing a bug on GitHub:
flutter:   https://github.com/flutter/flutter/issues/new?template=BUG.md
flutter:
flutter: When the exception was thrown, this was the stack:
flutter: #2      _HeroFlight.start (package:flutter/src/widgets/heroes.dart:424:12)
flutter: #3      HeroController._startHeroTransition (package:flutter/src/widgets/heroes.dart:684:60)
flutter: #4      HeroController._maybeStartHeroTransition.<anonymous closure> (package:flutter/src/widgets/heroes.dart:630:11)
flutter: #5      _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:990:15)
flutter: #6      _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:938:9)
flutter: #7      _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:842:5)
flutter: #11     _invoke (dart:ui/hooks.dart:209:10)
flutter: #12     _drawFrame (dart:ui/hooks.dart:168:3)
flutter: (elided 5 frames from class _AssertionError and package dart:async)
flutter: ════════════════════════════════════════════════════════════════════════════════════════════════════
```

**Comment by YouCii** [comment]
[VERBOSE-2:ui_dart_state.cc(148)] Unhandled Exception: 'package:flutter/src/gestures/converter.dart': Failed assertion: line 155 pos 18: '!state.down': is not true.
#0      _AssertionError._doThrowNew (dart:core/runtime/lib/errors_patch.dart:40:39)
#1      _AssertionError._throwNew (dart:core/runtime/lib/errors_patch.dart:36:5)
#2      PointerEventConverter.expand (package:flutter/src/gestures/converter.dart:155:18)
#3      _SyncIterator.moveNext (dart:core/runtime/lib/core_patch.dart:152:12)
#4      ListQueue.addAll (dart:collection/queue.dart:715:25)
#5      _WidgetsFlutterBinding&BindingBase&GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:83:27)
#6      _rootRunUnary (dart:async/zone.dart:1136:13)
#7      _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#8      _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
#9      _invoke1 (dart:ui/hooks.dart:223:10)
#10     _dispatchPointerDataPacket (dart:ui/hooks.dart:144:5)

**Comment by YouCii** [comment]
Feeling helpless...

**Comment by btbj** [comment]
`[VERBOSE-2:ui_dart_state.cc(148)] Unhandled Exception: 'package:flutter/src/gestures/converter.dart': Failed assertion: line 155 pos 18: '!state.down': is not true.
#0      _AssertionError._doThrowNew (dart:core/runtime/liberrors_patch.dart:40:39)
#1      _AssertionError._throwNew (dart:core/runtime/liberrors_patch.dart:36:5)
#2      PointerEventConverter.expand 
package:flutter/…/gestures/converter.dart:155
#3      _SyncIterator.moveNext (dart:core/runtime/libcore_patch.dart:152:12)
#4      ListQueue.addAll (dart:collection/queue.dart:715:25)
#5      _WidgetsFlutterBinding&BindingBase&GestureBinding._handlePointerDataPacket 
package:flutter/…/gestures/binding.dart:83
#6      _rootRunUnary (dart:async/zone.dart:1136:13)
#7      _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#8      _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
#9      _invoke1 (dart:ui/hooks.dart:223:10)
`


facing the same issue with webview_flutter
when scrolling the webview page horizontally, this Exception will triggered occasionally

**Comment by escamoteur** [comment]
Hi, just want to check if this is still a problem for you.

**Comment by YouCii** [comment]
Amazing, the problem disappears. But why? What has been modified in the new version of Flutter?
