### ISSUE TITLE
progress indicator issue in video_player package

### ISSUE THREAD

**Issue by egodefroy** [flutter/flutter#30443]
Here the stack trace. This seems to happen in conditions where there's a problem with the video file, not in standard situations...
```
2019-04-03 14:58:552 FlutterError details stack #0      _Double.toInt (dart:core/runtime/lib/double.dart:183)
#1      _Double.round (dart:core/runtime/lib/double.dart:151)
#2      ProgressIndicator._buildSemanticsWrapper (package:flutter/src/material/progress_indicator.dart:145)
#3      _LinearProgressIndicatorState._buildIndicator (package:flutter/src/material/progress_indicator.dart:284)
#4      _LinearProgressIndicatorState.build (package:flutter/src/material/progress_indicator.dart:309)
#5      StatefulElement.build (package:flutter/src/widgets/framework.dart:3824)
#6      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3735)
#7      Element.rebuild (package:flutter/src/widgets/framework.dart:3558)
#8      ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3715)
#9      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3863)
#10     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3710)
#11     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2954)
#12     MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4981)
#13     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2954)
#14     Element.updateChild (package:flutter/src/widgets/framework.dart:2757)
#15     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4875)
#16     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2954)
#17     Element.updateChild (package:flutter/src/widgets/framework.dart:2757)
#18     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4875)
#19     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2954)
#20     Element.updateChild (package:flutter/src/widgets/framework.dart:2757)
#21     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4875)
#22     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2954)
#23     Element.updateChild (package:flutter/src/widgets/framework.dart:2757)
#24     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3746)
#25     Element.rebuild (package:flutter/src/widgets/framework.dart:3558)
#26     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3715)
#27     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3863)
#28     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3710)
#29     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2954)
#30     Element.updateChild (package:flutter/src/widgets/framework.dart:2757)
#31     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3746)
#32     Element.rebuild (package:flutter/src/widgets/framework.dart:3558)
#33     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3715)
#34     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3710)
#35     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2954)
#36     Element.updateChild (package:flutter/src/widgets/framework.dart:2757)
#37     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3746)
#38     Element.rebuild (package:flutter/src/widgets/framework.dart:3558)
#39     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3715)
#40     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3863)
#41     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3710)
#42     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2954)
#43     Element.updateChild (package:flutter/src/widgets/framework.dart:2757)
#44     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3746)
#45     Element.rebuild (package:flutter/src/widgets/framework.dart:3558)
#46     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3715)
#47     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3863)
#48     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3710)
#49     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2954)
#50     Element.updateChild (package:flutter/src/widgets/framework.dart:2757)
#51     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4875)
#52     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2954)
#53     MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4981)
#54     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2954)
#55     Element.updateChild (package:flutter/src/widgets/framework.dart:2757)
#56     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3746)
#57     Element.rebuild (package:flutter/src/widgets/framework.dart:3558)
#58     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3715)
#59     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3863)
#60     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3710)
#61     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2954)
#62     Element.updateChild (package:flutter/src/widgets/framework.dart:2757)
#63     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4875)
#64     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2954)
#65     Element.updateChild (package:flutter/src/widgets/framework.dart:2757)
#66     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4875)
#67     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2954)
#68     Element.updateChild (package:flutter/src/widgets/framework.dart:2757)
#69     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4882)
#70     Element.updateChild (package:flutter/src/widgets/framework.dart:2746)
#71     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4882)
#72     Element.updateChild (package:flutter/src/widgets/framework.dart:2746)
#73     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3746)
#74     Element.rebuild (package:flutter/src/widgets/framework.dart:3558)
#75     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2271)
```

flutter doctor
```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel master, v1.4.9-pre.21, on Mac OS X 10.13.6 17G6029, locale fr-FR)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[✓] iOS toolchain - develop for iOS devices (Xcode 10.1)
[✓] Android Studio (version 3.3)
[✓] VS Code (version 1.32.3)
[✓] Connected device (1 available)

• No issues found!
```

**Comment by escamoteur** [comment]
Hi, just want to check if this is still a problem for you.

**Comment by iapicca** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
  
Thanks for your contribution.
