### ISSUE TITLE
Flutter crashes on a simple package typo

### ISSUE THREAD

**Issue by hemanta212** [flutter/flutter#30496]
## Steps to Reproduce

1. Create a regular flutter app
2. In the import statement misspell package 
3. Run the command 'flutter run'

## Logs

F:\my_projects\flutter_dev\flutter_udemy>flutter run -v
[  +84 ms] executing: [F:\programs\flutter\] git rev-parse --abbrev-ref --symbolic @{u}
[ +374 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[  +67 ms] origin/stable
[   +1 ms] executing: [F:\programs\flutter\] git rev-parse --abbrev-ref HEAD
[ +176 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[   +1 ms] stable
[   +1 ms] executing: [F:\programs\flutter\] git ls-remote --get-url origin
[ +941 ms] Exit code 0 from: git ls-remote --get-url origin
[   +1 ms] https://github.com/flutter/flutter.git
[   +1 ms] executing: [F:\programs\flutter\] git log -n 1 --pretty=format:%H
[+1840 ms] Exit code 0 from: git log -n 1 --pretty=format:%H
[   +1 ms] 8661d8aecd626f7f57ccbcb735553edc05a2e713
[        ] executing: [F:\programs\flutter\] git log -n 1 --pretty=format:%ar
[ +241 ms] Exit code 0 from: git log -n 1 --pretty=format:%ar
[   +1 ms] 7 weeks ago
[   +1 ms] executing: [F:\programs\flutter\] git describe --match v*.*.* --first-parent --long --tags
[ +161 ms] Exit code 0 from: git describe --match v*.*.* --first-parent --long --tags
[        ] v1.2.1-0-g8661d8aec
[ +330 ms] executing: C:\Users\Hp\AppData\Local\Android\sdk\platform-tools\adb devices -l
[ +458 ms] Exit code 0 from: C:\Users\Hp\AppData\Local\Android\sdk\platform-tools\adb devices -l
[        ] List of devices attached
           60D15B12D13697L1511    device product:Y541-U02 model:HUAWEI_Y541_U02 device:HWY541-U transport_id:1
[ +531 ms] C:\Users\Hp\AppData\Local\Android\sdk\platform-tools\adb -s 60D15B12D13697L1511 shell getprop
[ +131 ms] ro.hardware = sc8830
[   +1 ms] ro.build.characteristics = default
[ +227 ms] "flutter run" took 1,435ms.
[        ] "flutter run" took 1,435ms.

Oops; flutter has exited unexpectedly.
Sending crash report to Google.
Crash report sent (report ID: 612046df20868e19)
Crash report written to F:\my_projects\flutter_dev\flutter_udemy\flutter_05.log;
please let us know at https://github.com/flutter/flutter/issues.

# Logs At F:\my_projects\flutter_dev\flutter_udemy\flutter_05.log
Flutter crash report; please file at https://github.com/flutter/flutter/issues.

## command

flutter run

## exception

UnsupportedError: Unsupported operation: Cannot extract a file path from a packgae URI

```
#0      _SimpleUri.toFilePath (dart:core/uri.dart:4587:7)
#1      DartDependencySetBuilder.build (package:flutter_tools/src/dart/dependencies.dart:93:58)
#2      HotRunner._refreshDartDependencies (package:flutter_tools/src/run_hot.dart:128:69)
<asynchronous suspension>
#3      HotRunner.run (package:flutter_tools/src/run_hot.dart:287:16)
<asynchronous suspension>
#4      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:405:37)
<asynchronous suspension>
#5      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:545:18)
#6      _asyncThenWrapperHelper.<anonymous closure> (dart:async/runtime/libasync_patch.dart:77:64)
#7      _rootRunUnary (dart:async/zone.dart:1132:38)
#8      _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#9      _FutureListener.handleValue (dart:async/future_impl.dart:126:18)
#10     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:639:45)
#11     Future._propagateToListeners (dart:async/future_impl.dart:668:32)
#12     Future._complete (dart:async/future_impl.dart:473:7)
#13     _SyncCompleter.complete (dart:async/future_impl.dart:51:12)
#14     _AsyncAwaitCompleter.complete (dart:async/runtime/libasync_patch.dart:28:18)
#15     _completeOnAsyncReturn (dart:async/runtime/libasync_patch.dart:294:13)
#16     RunCommand.usageValues (package:flutter_tools/src/commands/run.dart)
#17     _asyncThenWrapperHelper.<anonymous closure> (dart:async/runtime/libasync_patch.dart:77:64)
#18     _rootRunUnary (dart:async/zone.dart:1132:38)
#19     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#20     _FutureListener.handleValue (dart:async/future_impl.dart:126:18)
#21     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:639:45)
#22     Future._propagateToListeners (dart:async/future_impl.dart:668:32)
#23     Future._complete (dart:async/future_impl.dart:473:7)
#24     _SyncCompleter.complete (dart:async/future_impl.dart:51:12)
#25     _AsyncAwaitCompleter.complete (dart:async/runtime/libasync_patch.dart:28:18)
#26     _completeOnAsyncReturn (dart:async/runtime/libasync_patch.dart:294:13)
#27     AndroidDevice.targetPlatform (package:flutter_tools/src/android/android_device.dart)
#28     _asyncThenWrapperHelper.<anonymous closure> (dart:async/runtime/libasync_patch.dart:77:64)
#29     _rootRunUnary (dart:async/zone.dart:1132:38)
#30     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#31     _FutureListener.handleValue (dart:async/future_impl.dart:126:18)
#32     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:639:45)
#33     Future._propagateToListeners (dart:async/future_impl.dart:668:32)
#34     Future._complete (dart:async/future_impl.dart:473:7)
#35     _SyncCompleter.complete (dart:async/future_impl.dart:51:12)
#36     _AsyncAwaitCompleter.complete.<anonymous closure> (dart:async/runtime/libasync_patch.dart:33:20)
#37     _rootRun (dart:async/zone.dart:1124:13)
#38     _CustomZone.run (dart:async/zone.dart:1021:19)
#39     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:947:23)
#40     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#41     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#42     _runPendingImmediateCallback (dart:isolate/runtime/libisolate_patch.dart:115:13)
#43     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:172:5)
```

## flutter doctor

```
[32m[✓][39m Flutter (Channel stable, v1.2.1, on Microsoft Windows
    [Version 10.0.17134.648], locale en-US)
    [32m•[39m Flutter version 1.2.1 at F:\programs\flutter
    [32m•[39m Framework revision 8661d8aecd (7 weeks ago), 2019-02-14
      19:19:53 -0800
    [32m•[39m Engine revision 3757390fa4
    [32m•[39m Dart version 2.1.2 (build 2.1.2-dev.0.0 0a7dcf17eb)

[32m[✓][39m Android toolchain - develop for Android devices (Android
    SDK version 28.0.3)
    [32m•[39m Android SDK at C:\Users\Hp\AppData\Local\Android\sdk
    [32m•[39m Android NDK location not configured (optional; useful
      for native profiling support)
    [32m•[39m Platform android-28, build-tools 28.0.3
    [32m•[39m Java binary at: F:\programs\androidstudio\jre\bin\java
    [32m•[39m Java version OpenJDK Runtime Environment (build
      1.8.0_152-release-1248-b01)
    [32m•[39m All Android licenses accepted.

[33m[!][39m Android Studio (version 3.3)
    [32m•[39m Android Studio at F:\programs\androidstudio
    [31m✗[39m Flutter plugin not installed; this adds Flutter
      specific functionality.
    [31m✗[39m Dart plugin not installed; this adds Dart specific
      functionality.
    [32m•[39m Java version OpenJDK Runtime Environment (build
      1.8.0_152-release-1248-b01)

[32m[✓][39m VS Code, 64-bit edition (version 1.32.3)
    [32m•[39m VS Code at C:\Program Files\Microsoft VS Code
    [32m•[39m Flutter extension version 2.24.0

[32m[✓][39m Connected device (1 available)
    [32m•[39m HUAWEI Y541 U02 • 60D15B12D13697L1511 • android-arm •
      Android 4.4.2 (API 19)

[33m![39m Doctor found issues in 1 category.
```

```
```

```
```

```
```

**Comment by jonahwilliams** [comment]
This was fixed indirectly by hot reload improvements I made, including the removal of _refreshDartDependencies
