### ISSUE TITLE
VS Code debug is not working. Gets stuck with white screen on the ios Simulator. Does not hit any breakpoint.

### ISSUE THREAD

**Issue by vijayredme** [flutter/flutter#30515]
VS Code debug is not working. Gets stuck with white screen on the ios Simulator. Does not hit any breakpoint.

## Steps to Reproduce

VS Code -> Debug -> Start Debugging -> Select iOS simulator . It launches app with white screen and does nothing. 
 
## Logs

```
flutter run --verbose
[  +35 ms] executing: [/Users/zkdl1eh/Setups/flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[  +45 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/stable
[        ] executing: [/Users/zkdl1eh/Setups/flutter/] git rev-parse --abbrev-ref HEAD
[  +10 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] stable
[        ] executing: [/Users/zkdl1eh/Setups/flutter/] git ls-remote --get-url origin
[  +11 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[        ] executing: [/Users/zkdl1eh/Setups/flutter/] git log -n 1 --pretty=format:%H
[  +13 ms] Exit code 0 from: git log -n 1 --pretty=format:%H
[        ] 8661d8aecd626f7f57ccbcb735553edc05a2e713
[        ] executing: [/Users/zkdl1eh/Setups/flutter/] git log -n 1 --pretty=format:%ar
[  +15 ms] Exit code 0 from: git log -n 1 --pretty=format:%ar
[        ] 7 weeks ago
[        ] executing: [/Users/zkdl1eh/Setups/flutter/] git describe --match v*.*.* --first-parent --long --tags
[  +15 ms] Exit code 0 from: git describe --match v*.*.* --first-parent --long --tags
[        ] v1.2.1-0-g8661d8aec
[ +320 ms] executing: /Users/zkdl1eh/Library/Android/sdk/platform-tools/adb devices -l
[  +13 ms] Exit code 0 from: /Users/zkdl1eh/Library/Android/sdk/platform-tools/adb devices -l
[        ] List of devices attached
[   +7 ms] executing: idevice_id -h
[   +3 ms] /usr/bin/xcrun simctl list --json devices
[ +359 ms] More than one device connected; please specify a device with the '-d <deviceId>' flag, or use '-d all' to act on all devices.
[  +11 ms] iPhone XS Max • 28DCE8EA-D0D8-4FE6-BEB8-8CE0D53A04B7 • ios • iOS 12.1 (simulator)
[   +1 ms] iPhone XR     • 5E9F2DBB-D0C1-4308-B31B-BC496D020682 • ios • iOS 12.1 (simulator)
[  +17 ms] "flutter run" took 656ms.
[        ] "flutter run" took 656ms.

#0      throwToolExit (package:flutter_tools/src/base/common.dart:24:3)
#1      RunCommand.validateCommand (package:flutter_tools/src/commands/run.dart:240:7)
<asynchronous suspension>
#2      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:525:11)
<asynchronous suspension>
#3      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:482:33)
<asynchronous suspension>
#4      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:142:29)
<asynchronous suspension>
#5      _rootRun (dart:async/zone.dart:1124:13)
#6      _CustomZone.run (dart:async/zone.dart:1021:19)
#7      _runZoned (dart:async/zone.dart:1516:10)
#8      runZoned (dart:async/zone.dart:1463:12)
#9      AppContext.run (package:flutter_tools/src/base/context.dart:141:18)
<asynchronous suspension>
#10     FlutterCommand.run (package:flutter_tools/src/runner/flutter_command.dart:473:20)
#11     CommandRunner.runCommand (package:args/command_runner.dart:196:27)
<asynchronous suspension>
#12     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:396:21)
<asynchronous suspension>
#13     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:142:29)
<asynchronous suspension>
#14     _rootRun (dart:async/zone.dart:1124:13)
#15     _CustomZone.run (dart:async/zone.dart:1021:19)
#16     _runZoned (dart:async/zone.dart:1516:10)
#17     runZoned (dart:async/zone.dart:1463:12)
#18     AppContext.run (package:flutter_tools/src/base/context.dart:141:18)
<asynchronous suspension>
#19     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:356:19)
<asynchronous suspension>
#20     CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:111:29)
#21     new Future.sync (dart:async/future.dart:224:31)
#22     CommandRunner.run (package:args/command_runner.dart:111:11)
#23     FlutterCommandRunner.run (package:flutter_tools/src/runner/flutter_command_runner.dart:242:18)
#24     run.<anonymous closure> (package:flutter_tools/runner.dart:60:20)
<asynchronous suspension>
#25     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:142:29)
<asynchronous suspension>
#26     _rootRun (dart:async/zone.dart:1124:13)
#27     _CustomZone.run (dart:async/zone.dart:1021:19)
#28     _runZoned (dart:async/zone.dart:1516:10)
#29     runZoned (dart:async/zone.dart:1463:12)
#30     AppContext.run (package:flutter_tools/src/base/context.dart:141:18)
<asynchronous suspension>
#31     runInContext (package:flutter_tools/src/context_runner.dart:48:24)
<asynchronous suspension>
#32     run (package:flutter_tools/runner.dart:51:10)
#33     main (package:flutter_tools/executable.dart:52:9)
<asynchronous suspension>
#34     main (file:///Users/zkdl1eh/Setups/flutter/packages/flutter_tools/bin/flutter_tools.dart:8:3)
#35     _startIsolate.<anonymous closure> (dart:isolate/runtime/libisolate_patch.dart:298:32)
#36     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:171:12)

```

```
flutter analyze
Analyzing layouttutorial...                                             

   info • The function '_getJsonData' isn't used • lib/CPMUtilities.dart:4:1 • unused_element
   info • The value of the local variable 'jsonData' isn't used • lib/CPMUtilities.dart:7:9 • unused_local_variable
   info • Name types using UpperCamelCase • lib/main.dart:49:7 • camel_case_types
   info • This class (or a class which this class inherits from) is marked as '@immutable', but one or more of its instance fields are not
          final: MainScreen.jsonData • lib/main.dart:93:7 • must_be_immutable
   info • The method '_buildScrollView' isn't used • lib/main.dart:115:2 • unused_element
   info • The method '_buildCustomerCell' isn't used • lib/main.dart:268:8 • unused_element
   info • The method '_buildLists' isn't used • lib/main.dart:420:16 • unused_element
   info • The method '_buildGrids' isn't used • lib/main.dart:442:16 • unused_element
   info • The method '_buildSideHeaderGrids' isn't used • lib/main.dart:479:16 • unused_element
   info • The method '_buildExample' isn't used • lib/main.dart:563:10 • unused_element
   info • The method '_buildBuilderExample' isn't used • lib/main.dart:589:10 • unused_element
   info • The value of the field '_offsetClose' isn't used • lib/obligationPopover.dart:53:21 • unused_field
   info • Unused import: 'package:layouttutorial/main.dart' • test/widget_test.dart:11:8 • unused_import
  error • The function 'MyApp' isn't defined • test/widget_test.dart:16:29 • undefined_function
```

```
```

**Comment by vijayredme** [comment]
flutter doctor -v
[✓] Flutter (Channel stable, v1.2.1, on Mac OS X 10.13.6 17G5019, locale en-US)
    • Flutter version 1.2.1 at /Users/zkdl1eh/Setups/flutter
    • Framework revision 8661d8aecd (7 weeks ago), 2019-02-14 19:19:53 -0800
    • Engine revision 3757390fa4
    • Dart version 2.1.2 (build 2.1.2-dev.0.0 0a7dcf17eb)

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/zkdl1eh/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)
    • All Android licenses accepted.

[!] iOS toolchain - develop for iOS devices (Xcode 10.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.1, Build version 10B61
    ✗ libimobiledevice and ideviceinstaller are not installed. To install with Brew, run:
        brew update
        brew install --HEAD usbmuxd
        brew link usbmuxd
        brew install --HEAD libimobiledevice
        brew install ideviceinstaller
    • ios-deploy 2.0.0
    ✗ Brew can be used to install tools for iOS device development.
      Download brew at https://brew.sh/.

[!] Android Studio (version 3.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)

[✓] VS Code (version 1.31.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 2.25.0

[!] Proxy Configuration
    • HTTP_PROXY is set
    ! NO_PROXY is not set

[✓] Connected device (2 available)
    • iPhone XS Max • 28DCE8EA-D0D8-4FE6-BEB8-8CE0D53A04B7 • ios • iOS 12.1 (simulator)
    • iPhone XR     • 5E9F2DBB-D0C1-4308-B31B-BC496D020682 • ios • iOS 12.1 (simulator)

**Comment by DanTup** [comment]
In the error above, it has:

```
[ +359 ms] More than one device connected; please specify a device with the '-d <deviceId>' flag, or use '-d all' to act on all devices.
[  +11 ms] iPhone XS Max • 28DCE8EA-D0D8-4FE6-BEB8-8CE0D53A04B7 • ios • iOS 12.1 (simulator)
[   +1 ms] iPhone XR     • 5E9F2DBB-D0C1-4308-B31B-BC496D020682 • ios • iOS 12.1 (simulator)
```

If you close one of the simulator devices, does this solve the issue?
