### ISSUE TITLE
[image_picker] Example not compatible with ios armv7

### ISSUE THREAD

**Issue by boskokg** [flutter/flutter#30551]
## Steps to Reproduce

1. Open plugin in Android Studio (mac)
2. Run example on iPhone 4s
Application cannot be installed
Note: I also opened Sample in the Xcode and I still have the same issue.
Note2: I noticed that info.plist of the example has:
<key>UIRequiredDeviceCapabilities</key><array><string>arm64</string></array>

## Logs

```
[ +245 ms] Installing and launching...
[        ] Debugging is enabled, connecting to observatory
[   +8 ms] executing: /usr/bin/env ios-deploy --id 38e73f2676723efb3bc8a7094dd3fd5494c345e8 --bundle build/ios/iphoneos/Runner.app --no-wifi --justlaunch --args --enable-dart-profiling --enable-checked-mode
--verify-entry-points
[  +41 ms] [....] Waiting for iOS device to be connected
[  +20 ms] [....] Using 38e73f2676723efb3bc8a7094dd3fd5494c345e8 (N94AP, iPhone 4S, iphoneos, armv7) a.k.a. 'Bosko's iPhone'.
[        ] ------ Install phase ------
[        ] [  0%] Found 38e73f2676723efb3bc8a7094dd3fd5494c345e8 (N94AP, iPhone 4S, iphoneos, armv7) a.k.a. 'Bosko's iPhone' connected through USB, beginning install
[ +984 ms] [  5%] Copying /Users/boskopopovic/Desktop/plugins-master 2/packages/image_picker/example/build/ios/iphoneos/Runner.app/META-INF/ to device
[        ] [  5%] Copying /Users/boskopopovic/Desktop/plugins-master 2/packages/image_picker/example/build/ios/iphoneos/Runner.app/META-INF/com.apple.ZipMetadata.plist to device
[        ] [  5%] Copying /Users/boskopopovic/Desktop/plugins-master 2/packages/image_picker/example/build/ios/iphoneos/Runner.app/_CodeSignature/ to device
[        ] [  6%] Copying /Users/boskopopovic/Desktop/plugins-master 2/packages/image_picker/example/build/ios/iphoneos/Runner.app/_CodeSignature/CodeResources to device
[        ] [  6%] Copying /Users/boskopopovic/Desktop/plugins-master 2/packages/image_picker/example/build/ios/iphoneos/Runner.app/AppIcon20x20@2x.png to device
[        ] [  6%] Copying /Users/boskopopovic/Desktop/plugins-master 2/packages/image_picker/example/build/ios/iphoneos/Runner.app/AppIcon20x20@3x.png to device
[        ] [  7%] Copying /Users/boskopopovic/Desktop/plugins-master 2/packages/image_picker/example/build/ios/iphoneos/Runner.app/AppIcon29x29.png to device
[        ] [  7%] Copying /Users/boskopopovic/Desktop/plugins-master 2/packages/image_picker/example/build/ios/iphoneos/Runner.app/AppIcon60x60@2x.png to device
[        ] [  8%] Copying /Users/boskopopovic/Desktop/plugins-master 2/packages/image_picker/example/build/ios/iphoneos/Runner.app/Runner to device
[        ] [  8%] Copying /Users/boskopopovic/Desktop/plugins-master 2/packages/image_picker/example/build/ios/iphoneos/Runner.app/AppIcon29x29@2x.png to device
[        ] [  8%] Copying /Users/boskopopovic/Desktop/plugins-master 2/packages/image_picker/example/build/ios/iphoneos/Runner.app/AppIcon40x40@3x.png to device
[        ] [  9%] Copying /Users/boskopopovic/Desktop/plugins-master 2/packages/image_picker/example/build/ios/iphoneos/Runner.app/Debug.xcconfig to device
[        ] [  9%] Copying /Users/boskopopovic/Desktop/plugins-master 2/packages/image_picker/example/build/ios/iphoneos/Runner.app/AppIcon29x29~ipad.png to device
[        ] [  9%] Copying /Users/boskopopovic/Desktop/plugins-master 2/packages/image_picker/example/build/ios/iphoneos/Runner.app/AppIcon40x40@2x.png to device
[        ] [ 10%] Copying /Users/boskopopovic/Desktop/plugins-master 2/packages/image_picker/example/build/ios/iphoneos/Runner.app/AppIcon29x29@3x.png to device
[        ] [ 10%] Copying /Users/boskopopovic/Desktop/plugins-master 2/packages/image_picker/example/build/ios/iphoneos/Runner.app/AppIcon60x60@3x.png to device
[        ] [ 11%] Copying /Users/boskopopovic/Desktop/plugins-master 2/packages/image_picker/example/build/ios/iphoneos/Runner.app/Base.lproj/ to device
[        ] [ 11%] Copying /Users/boskopopovic/Desktop/plugins-master 2/packages/image_picker/example/build/ios/iphoneos/Runner.app/Base.lproj/Main.storyboardc/ to device
[        ] [ 11%] Copying /Users/boskopopovic/Desktop/plugins-master 2/packages/image_picker/example/build/ios/iphoneos/Runner.app/Base.lproj/Main.storyboardc/UIViewController-BYZ-38-t0r.nib to device
[        ] [ 12%] Copying /Users/boskopopovic/Desktop/plugins-master 2/packages/image_picker/example/build/ios/iphoneos/Runner.app/Base.lproj/Main.storyboardc/BYZ-38-t0r-view-8bC-Xf-vdC.nib to device
[        ] [ 12%] Copying /Users/boskopopovic/Desktop/plugins-master 2/packages/image_picker/example/build/ios/iphoneos/Runner.app/Base.lproj/Main.storyboardc/Info.plist to device
[        ] [ 12%] Copying /Users/boskopopovic/Desktop/plugins-master 2/packages/image_picker/example/build/ios/iphoneos/Runner.app/Base.lproj/LaunchScreen.storyboardc/ to device
[        ] [ 13%] Copying /Users/boskopopovic/Desktop/plugins-master 2/packages/image_picker/example/build/ios/iphoneos/Runner.app/Base.lproj/LaunchScreen.storyboardc/01J-lp-oVM-view-Ze5-6b-2t3.nib to device
[        ] [ 13%] Copying /Users/boskopopovic/Desktop/plugins-master 2/packages/image_picker/example/build/ios/iphoneos/Runner.app/Base.lproj/LaunchScreen.storyboardc/UIViewController-01J-lp-oVM.nib to device
[        ] [ 14%] Copying /Users/boskopopovic/Desktop/plugins-master 2/packages/image_picker/example/build/ios/iphoneos/Runner.app/Base.lproj/LaunchScreen.storyboardc/Info.plist to device
[        ] [ 14%] Copying /Users/boskopopovic/Desktop/plugins-master 2/packages/image_picker/example/build/ios/iphoneos/Runner.app/Assets.car to device
[        ] [ 14%] Copying /Users/boskopopovic/Desktop/plugins-master 2/packages/image_picker/example/build/ios/iphoneos/Runner.app/AppFrameworkInfo.plist to device
[        ] [ 15%] Copying /Users/boskopopovic/Desktop/plugins-master 2/packages/image_picker/example/build/ios/iphoneos/Runner.app/AppIcon40x40@2x~ipad.png to device
[        ] [ 15%] Copying /Users/boskopopovic/Desktop/plugins-master 2/packages/image_picker/example/build/ios/iphoneos/Runner.app/AppIcon76x76@2x~ipad.png to device
[        ] [ 15%] Copying /Users/boskopopovic/Desktop/plugins-master 2/packages/image_picker/example/build/ios/iphoneos/Runner.app/AppIcon83.5x83.5@2x~ipad.png to device
[        ] [ 16%] Copying /Users/boskopopovic/Desktop/plugins-master 2/packages/image_picker/example/build/ios/iphoneos/Runner.app/Generated.xcconfig to device
[        ] [ 16%] Copying /Users/boskopopovic/Desktop/plugins-master 2/packages/image_picker/example/build/ios/iphoneos/Runner.app/AppIcon29x29@2x~ipad.png to device
[        ] [ 17%] Copying /Users/boskopopovic/Desktop/plugins-master 2/packages/image_picker/example/build/ios/iphoneos/Runner.app/AppIcon40x40~ipad.png to device
[        ] [ 17%] Copying /Users/boskopopovic/Desktop/plugins-master 2/packages/image_picker/example/build/ios/iphoneos/Runner.app/Frameworks/ to device
[        ] [ 17%] Copying /Users/boskopopovic/Desktop/plugins-master 2/packages/image_picker/example/build/ios/iphoneos/Runner.app/Frameworks/Flutter.framework/ to device
[        ] [ 18%] Copying /Users/boskopopovic/Desktop/plugins-master 2/packages/image_picker/example/build/ios/iphoneos/Runner.app/Frameworks/Flutter.framework/_CodeSignature/ to device
[        ] [ 18%] Copying /Users/boskopopovic/Desktop/plugins-master 2/packages/image_picker/example/build/ios/iphoneos/Runner.app/Frameworks/Flutter.framework/_CodeSignature/CodeResources to device
[        ] [ 18%] Copying /Users/boskopopovic/Desktop/plugins-master 2/packages/image_picker/example/build/ios/iphoneos/Runner.app/Frameworks/Flutter.framework/icudtl.dat to device
[ +338 ms] [ 19%] Copying /Users/boskopopovic/Desktop/plugins-master 2/packages/image_picker/example/build/ios/iphoneos/Runner.app/Frameworks/Flutter.framework/Flutter to device
[ +969 ms] [ 33%] Copying /Users/boskopopovic/Desktop/plugins-master 2/packages/image_picker/example/build/ios/iphoneos/Runner.app/Frameworks/Flutter.framework/Info.plist to device
[        ] [ 33%] Copying /Users/boskopopovic/Desktop/plugins-master 2/packages/image_picker/example/build/ios/iphoneos/Runner.app/Frameworks/App.framework/ to device
[        ] [ 34%] Copying /Users/boskopopovic/Desktop/plugins-master 2/packages/image_picker/example/build/ios/iphoneos/Runner.app/Frameworks/App.framework/_CodeSignature/ to device
[        ] [ 34%] Copying /Users/boskopopovic/Desktop/plugins-master 2/packages/image_picker/example/build/ios/iphoneos/Runner.app/Frameworks/App.framework/_CodeSignature/CodeResources to device
[   +3 ms] [ 34%] Copying /Users/boskopopovic/Desktop/plugins-master 2/packages/image_picker/example/build/ios/iphoneos/Runner.app/Frameworks/App.framework/App to device
[        ] [ 35%] Copying /Users/boskopopovic/Desktop/plugins-master 2/packages/image_picker/example/build/ios/iphoneos/Runner.app/Frameworks/App.framework/flutter_assets/ to device
[        ] [ 35%] Copying /Users/boskopopovic/Desktop/plugins-master 2/packages/image_picker/example/build/ios/iphoneos/Runner.app/Frameworks/App.framework/flutter_assets/LICENSE to device
[  +18 ms] [ 36%] Copying /Users/boskopopovic/Desktop/plugins-master 2/packages/image_picker/example/build/ios/iphoneos/Runner.app/Frameworks/App.framework/flutter_assets/vm_snapshot_data to device
[        ] [ 36%] Copying /Users/boskopopovic/Desktop/plugins-master 2/packages/image_picker/example/build/ios/iphoneos/Runner.app/Frameworks/App.framework/flutter_assets/isolate_snapshot_data to device
[ +291 ms] [ 38%] Copying /Users/boskopopovic/Desktop/plugins-master 2/packages/image_picker/example/build/ios/iphoneos/Runner.app/Frameworks/App.framework/flutter_assets/AssetManifest.json to device
[        ] [ 38%] Copying /Users/boskopopovic/Desktop/plugins-master 2/packages/image_picker/example/build/ios/iphoneos/Runner.app/Frameworks/App.framework/flutter_assets/kernel_blob.bin to device
[ +582 ms] [ 46%] Copying /Users/boskopopovic/Desktop/plugins-master 2/packages/image_picker/example/build/ios/iphoneos/Runner.app/Frameworks/App.framework/flutter_assets/FontManifest.json to device
[        ] [ 46%] Copying /Users/boskopopovic/Desktop/plugins-master 2/packages/image_picker/example/build/ios/iphoneos/Runner.app/Frameworks/App.framework/flutter_assets/fonts/ to device
[        ] [ 46%] Copying /Users/boskopopovic/Desktop/plugins-master 2/packages/image_picker/example/build/ios/iphoneos/Runner.app/Frameworks/App.framework/flutter_assets/fonts/MaterialIcons-Regular.ttf to device
[   +4 ms] [ 47%] Copying /Users/boskopopovic/Desktop/plugins-master 2/packages/image_picker/example/build/ios/iphoneos/Runner.app/Frameworks/App.framework/Info.plist to device
[        ] [ 47%] Copying /Users/boskopopovic/Desktop/plugins-master 2/packages/image_picker/example/build/ios/iphoneos/Runner.app/AppIcon20x20~ipad.png to device
[        ] [ 48%] Copying /Users/boskopopovic/Desktop/plugins-master 2/packages/image_picker/example/build/ios/iphoneos/Runner.app/embedded.mobileprovision to device
[   +2 ms] [ 48%] Copying /Users/boskopopovic/Desktop/plugins-master 2/packages/image_picker/example/build/ios/iphoneos/Runner.app/AppIcon20x20@2x~ipad.png to device
[        ] [ 48%] Copying /Users/boskopopovic/Desktop/plugins-master 2/packages/image_picker/example/build/ios/iphoneos/Runner.app/Info.plist to device
[        ] [ 49%] Copying /Users/boskopopovic/Desktop/plugins-master 2/packages/image_picker/example/build/ios/iphoneos/Runner.app/PkgInfo to device
[        ] [ 49%] Copying /Users/boskopopovic/Desktop/plugins-master 2/packages/image_picker/example/build/ios/iphoneos/Runner.app/AppIcon76x76~ipad.png to device
[+1019 ms] [ 52%] CreatingStagingDirectory
[        ] [ 57%] ExtractingPackage
[   +1 ms] [ 60%] InspectingPackage
[  +23 ms] [ 60%] TakingInstallLock
[ +103 ms] [ 65%] PreflightingApplication
[  +29 ms] [ 65%] InstallingEmbeddedProfile
[  +13 ms] [ 70%] VerifyingApplication
[ +269 ms] 2019-04-05 14:16:27.358 ios-deploy[44877:6196182] [ !! ] Error 0xe8000087: This application does not support this device's CPU type. AMDeviceSecureInstallApplication(0, device, url, options, install_callback,
0)
[   +3 ms] Failed to launch the application on device.
[   +1 ms] Installing and launching... (completed in 4.7s)
[        ] Could not install build/ios/iphoneos/Runner.app on 38e73f2676723efb3bc8a7094dd3fd5494c345e8.
[        ] Try launching Xcode and selecting "Product > Run" to fix the problem:
[        ]   open ios/Runner.xcworkspace
[        ] Error launching application on Bosko's iPhone.
[   +5 ms] "flutter run" took 27,621ms.
[        ] "flutter run" took 27,621ms.

#0      throwToolExit (package:flutter_tools/src/base/common.dart:24:3)
#1      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:426:7)
<asynchronous suspension>
#2      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:553:18)
#3      _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:77:64)
#4      _rootRunUnary (dart:async/zone.dart:1132:38)
#5      _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#6      _FutureListener.handleValue (dart:async/future_impl.dart:126:18)
#7      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:639:45)
#8      Future._propagateToListeners (dart:async/future_impl.dart:668:32)
#9      Future._complete (dart:async/future_impl.dart:473:7)
#10     _SyncCompleter.complete (dart:async/future_impl.dart:51:12)
#11     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:28:18)
#12     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:294:13)
#13     RunCommand.usageValues (package:flutter_tools/src/commands/run.dart)
#14     _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:77:64)
#15     _rootRunUnary (dart:async/zone.dart:1132:38)
#16     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#17     _FutureListener.handleValue (dart:async/future_impl.dart:126:18)
#18     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:639:45)
#19     Future._propagateToListeners (dart:async/future_impl.dart:668:32)
#20     Future._complete (dart:async/future_impl.dart:473:7)
#21     _SyncCompleter.complete (dart:async/future_impl.dart:51:12)
#22     _AsyncAwaitCompleter.complete.<anonymous closure> (dart:async-patch/async_patch.dart:33:20)
#23     _rootRun (dart:async/zone.dart:1124:13)
#24     _CustomZone.run (dart:async/zone.dart:1021:19)
#25     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:947:23)
#26     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#27     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#28     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:115:13)
#29     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:5)
```

```
Analyzing example...                                                    
No issues found! (ran in 5.9s)
```

```
[✓] Flutter (Channel dev, v1.4.8, on Mac OS X 10.14.4 18E226, locale en-RS)
    • Flutter version 1.4.8 at /Users/boskopopovic/Desktop/work/Flutter/flutter
    • Framework revision fbefd6b816 (4 days ago), 2019-04-01 10:58:30 -0700
    • Engine revision a850016454
    • Dart version 2.2.1 (build 2.2.1-dev.2.1 None)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/boskopopovic/Library/Developer/Xamarin/android-sdk-macosx
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = /Users/boskopopovic/Library/Developer/Xamarin/android-sdk-macosx
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.2, Build version 10E125
    • ios-deploy 1.9.4
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 34.0.1
    • Dart plugin version 182.5215
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)

[✓] VS Code (version 1.32.3)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 2.22.1

[✓] Connected device (1 available)
    • Bosko's iPhone • 38e73f2676723efb3bc8a7094dd3fd5494c345e8 • ios • iOS 9.3.5

• No issues found!
```

**Comment by escamoteur** [comment]
Hi, just want to check if this is still a problem for you.

**Comment by iapicca** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
  
Thanks for your contribution.
