### ISSUE TITLE
Flutter application crashes when clicking with Reachability Cursor

### ISSUE THREAD

**Issue by MichaelPriebe** [flutter/flutter#30560]
When clicking anywhere with [Reachability Cursor](https://play.google.com/store/apps/details?id=com.niftyui.reachability) crashes all my flutter applications with the error:
```
java.lang.NullPointerException: Attempt to invoke virtual method 'float android.view.InputDevice$MotionRange.getMin()' on a null object reference
       at io.flutter.view.FlutterView.addPointerForIndex(FlutterView.java:480)
       at io.flutter.view.FlutterView.onTouchEvent(FlutterView.java:542)
       at android.view.View.dispatchTouchEvent(View.java:12533)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3032)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2662)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3032)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2662)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3032)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2662)
       at com.android.internal.policy.DecorView.superDispatchTouchEvent(DecorView.java:461)
       at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1830)
       at android.app.Activity.dispatchTouchEvent(Activity.java:3453)
       at com.android.internal.policy.DecorView.dispatchTouchEvent(DecorView.java:419)
       at android.view.View.dispatchPointerEvent(View.java:12774)
       at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:5263)
       at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:5063)
       at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4578)
       at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4631)
       at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4597)
       at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:4737)
       at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4605)
       at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:4794)
       at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4578)
       at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4631)
       at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4597)
       at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4605)
       at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4578)
       at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:7304)
       at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:7273)
       at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:7234)
       at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:7410)
       at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:247)
       at android.os.MessageQueue.nativePollOnce(Native Method)
       at android.os.MessageQueue.next(MessageQueue.java:326)
       at android.os.Looper.loop(Looper.java:165)
       at android.app.ActivityThread.main(ActivityThread.java:6806)
       at java.lang.reflect.Method.invoke(Native Method)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:873)
```

It also crashes if you normally click anywhere within the swipe pads.

**Comment by jason-simmons** [comment]
What version of Flutter are you running?  This should be fixed on the Flutter master branch

**Comment by MichaelPriebe** [comment]
It was stable, did not try master.

**Comment by MichaelPriebe** [comment]
This is fixed.
