### ISSUE TITLE
Can't use TextPainter in isolate

### ISSUE THREAD

**Issue by windrunner414** [flutter/flutter#30604]
if use TextPainter.layout in isolate will get a compiler error `native function not found`
I need layout many words and it takes a long time (100ms+), it will block UI thread
What should I do?

**Comment by dnfield** [comment]
Can you provide the code that causes this error?

**Comment by windrunner414** [comment]
void test(String str){
TextPainter(textDirection: TextDirection.ltr, text: TextSpan(text: str)).layout();
}
compute(test, '1');

**Comment by jason-simmons** [comment]
The Flutter engine native APIs for the UI package are only available in the primary isolate.

See https://github.com/flutter/engine/blob/master/lib/ui/dart_ui.cc#L102

**Comment by dnfield** [comment]
I'm not sure we could even make sense of doing this async.

If layout isn't finished, we can't paint anyway.

If we block until layout is finished, we can't paint until layout is finished anyway, and we potentially introduce deadlocks.

That said, it seems like it would be nice to be able to pre-layout text - or, alternatively, let the user paint text without specifying layout, which I think should still be possible today.

@windrunner414 - what happens if you run your `compute` call to do your own line breaking logic, and then just instantiate single `TextPainter`s for each line, and position/paint them yourself?

**Comment by windrunner414** [comment]
@dnfield how to get character's size to layout?we can't use TextPainter

**Comment by windrunner414** [comment]
I find it interesting that textpainter seems to cache the size of each character. Caching is ineffective if you use compute

**Comment by windrunner414** [comment]
I layout 5000 characters, including 2500 different characters.The first time took 1500ms!After that it only takes 15msafter layout we need to split it in many page, like this

**Comment by lwlizhe** [comment]
same question，so if we need to perform an expensive computation use textPainter，how to do it？

**Comment by dnfield** [comment]
right now you would have to write your own line-breaking logic - perhaps as a plugin. We don't currently have any API for doing text layout in a separate isolate. @GaryQian might have some other idea about this too.

**Comment by javanli** [comment]
same question.

**Comment by ControlAdad** [comment]
I have same question! Measuring Arabic text takes long time.

**Comment by windrunner414** [comment]
does someone have a solution?

**Comment by ovaldi** [comment]
+1

**Comment by kokocooler2020** [comment]
I have same issue, I am developing an app, it requires a lot of drawing to get a ui.Image (take 10 seconds or more).
When I move the drawing_function to isolate, I got : [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: Exception: error: native function 'PictureRecorder_constructor' (1 arguments) cannot be found.

**Comment by ahsanalidev** [comment]
I have same problem my google map marker takes few seconds to load

**Comment by leetomlee123** [comment]
same question,layout too slow,

**Comment by leetomlee123** [comment]
``

**Comment by fassel** [comment]
the same problem for me

**Comment by dnfield** [comment]
I have hidden a bunch of comments in this thread that were mainly "any updates/me too" comments.

Please avoid commenting "same here", "+1", or "any updates" - it makes it harder to find relevant content in the issue, pings all subscribers, and does not help surface to the team the priority of the issue.

Instead, thumbs up the original comment. If you wish to subscribe to updates, click the subscribe button in the right hand column of the issue. Comments should be reserved for information pertinent to the issue such as what progress you're making on finishing the feature, request for design review, updates in platform API docs to consider, blockers that need to be resolved, etc.

**Comment by leetomlee123** [comment]
Add this new feture has plan

**Comment by leetomlee123** [comment]
When will this problem be solved? It is very important to me. Thanks

**Comment by danielgomezrico** [comment]
This is very useful for building map markers too, I mean, not only for building text but for map markers.

In my app we have a lot of markers and building them every time is causing some UI freezes, but we use `PictureRecorder` to build them and they result in:

```dart
Exception: UI actions are only available on root isolate.
	#0      PictureRecorder._constructor (dart:ui/painting.dart:4458:59)
	#1      new PictureRecorder (dart:ui/painting.dart:4457:23)
	#2      IconGenerator._drawCircle (package:client/src/common/utils/map/icon_generator.dart:87:32)
	#3      IconGenerator.buildCircle (package:client/src/common/utils/map/icon_generator.dart:51:26)
	#4      MarkerGenerator._buildDots.<anonymous closure> (package:client/src/common/utils/map/marker_generator.dart:62:37)
	#5      MappedListIterable.elementAt (dart:_internal/iterable.dart:417:31)
	#6      ListIterator.moveNext (dart:_internal/iterable.dart:343:26)
	#7      Future.wait (dart:async/future.dart:406:26)
	#8      MarkerGenerator._buildDots (package:client/src/common/utils/map/marker_generator.dart:68:19)
	#9      MarkerGenerator.build (package:client/src/common/utils/map/marker_generator.dart:30:22)
	#10     buildMarkers (package:client/src/widget
```

**Comment by dnfield** [comment]
That's a different problem and would be a bit more complicated to manage due to how these operations can access graphics contexts that can only be safely used on specific threads. Text layout on the other hand shoul dbe possible to do on any thread.

**Comment by danielgomezrico** [comment]
😢 Got it, thanks for answering

**Comment by maxim-saplin** [comment]
Thumbs up, also can see performance when displaying not small (±20kb) strings as Rich text compised of a numebr of nested text spans. 70% of CPU time spent on layout

**Comment by zohar-soul** [comment]
Can anyone update about the status of this issue ? this issue is open before 3 years.

**Comment by lpongetti** [comment]
+1

**Comment by dnfield** [comment]
Another option for this would be to expose a lower-level text drawing API and just let people do layout/shaping via whatever aPI they in some other isolate/plugin and then send the glyph IDs/positions back to the UI isolate for drawing.

**Comment by zohar-soul** [comment]
> Another option for this would be to expose a lower-level text drawing API and just let people do layout/shaping via whatever aPI they in some other isolate/plugin and then send the glyph IDs/positions back to the UI isolate for drawing.

Sounds like a great idea, like android StaticLayout.

**Comment by Liloupar** [comment]
Can anyone update about the status of this issue ? this issue is open before 5 years.
