### ISSUE TITLE
Flutter is incompatible with Android Monkey Tests

### ISSUE THREAD

**Issue by MaterialTime** [flutter/flutter#30617]
I've tested the same command with a standard Android app and it works as it should.

## Steps to Reproduce

1. Run the following
```sh
adb shell monkey -p your.package.name --pct-touch 100 -throttle 500 -v 300
```

## Logs

<details><summary>Output</summary>
<p>
:Monkey: seed=1554731839200 count=300
:AllowPackage: dev.materialtime.livelab.mes
:IncludeCategory: android.intent.category.LAUNCHER
:IncludeCategory: android.intent.category.MONKEY
// Event percentages:
//   0: 100.0%
//   1: 0.0%
//   2: 0.0%
//   3: 0.0%
//   4: -0.0%
//   5: -0.0%
//   6: 0.0%
//   7: 0.0%
//   8: 0.0%
//   9: 0.0%
//   10: 0.0%
//   11: 0.0%
:Switch: #Intent;action=android.intent.action.MAIN;category=android.intent.category.LAUNCHER;launchFlags=0x10200000;component=dev.materialtime.livelab.mes/.MainActivity;end
    // Allowing start of Intent { act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] cmp=dev.materialtime.livelab.mes/.MainActivity } in package dev.materialtime.livelab.mes
:Sending Touch (ACTION_DOWN): 0:(759.0,1709.0)
:Sending Touch (ACTION_UP): 0:(762.0156,1710.8438)
// CRASH: dev.materialtime.livelab.mes (pid 9656)
// Short Msg: java.lang.NullPointerException
// Long Msg: java.lang.NullPointerException: Attempt to invoke virtual method 'float android.view.InputDevice$MotionRange.getMin()' on a null object reference
// Build Label: HUAWEI/CPN/HWCPN-Q:7.0/HUAWEICPN-W09/C128B006:user/release-keys
// Build Changelist: C128B006
// Build Time: 1527839833000
// java.lang.NullPointerException: Attempt to invoke virtual method 'float android.view.InputDevice$MotionRange.getMin()' on a null object reference
// 	at io.flutter.view.FlutterView.addPointerForIndex(Unknown Source)
// 	at io.flutter.view.FlutterView.onTouchEvent(Unknown Source)
// 	at android.view.View.dispatchTouchEvent(View.java:10013)
// 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2671)
// 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2301)
// 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2671)
// 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2301)
// 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2671)
// 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2301)
// 	at com.android.internal.policy.DecorView.superDispatchTouchEvent(DecorView.java:447)
// 	at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1871)
// 	at android.app.Activity.dispatchTouchEvent(Activity.java:3213)
// 	at com.android.internal.policy.DecorView.dispatchTouchEvent(DecorView.java:409)
// 	at android.view.View.dispatchPointerEvent(View.java:10233)
// 	at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:4865)
// 	at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4726)
// 	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4258)
// 	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4311)
// 	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4277)
// 	at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:4404)
// 	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4285)
// 	at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:4461)
// 	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4258)
// 	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4311)
// 	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4277)
// 	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4285)
// 	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4258)
// 	at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:6690)
// 	at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:6664)
// 	at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:6625)
// 	at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:6819)
// 	at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:192)
// 	at android.os.MessageQueue.nativePollOnce(Native Method)
// 	at android.os.MessageQueue.next(MessageQueue.java:356)
// 	at android.os.Looper.loop(Looper.java:138)
// 	at android.app.ActivityThread.main(ActivityThread.java:6623)
// 	at java.lang.reflect.Method.invoke(Native Method)
// 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:942)
// 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:832)
// 
** Monkey aborted due to error.
Events injected: 3
:Sending rotation degree=0, persist=false
:Dropped: keys=0 pointers=0 trackballs=0 flips=0 rotations=0
## Network stats: elapsed time=1045ms (0ms mobile, 0ms wifi, 1045ms not connected)
** System appears to have crashed at event 3 of 300 using seed 1554731839200

</p>
</details>

**Comment by andretietz** [comment]
Of course not, flutter is drawing it's own UI. So there's no android view hierarchy.

**Comment by MaterialTime** [comment]
I was under the impression that monkey testing would simulated random taps on the screen, hence it wouldn't matter that Flutter was drawing it itself.

**Comment by MaterialTime** [comment]
I was under the impression that monkey testing simulates random taps on the screen, so it wouldn't matter that Flutter was drawing the UI itself because the touch events were being sent to the system, just like real touch events.

Edit: double checked the description of the monkey test tool and it states that "When the Monkey runs, it generates events and sends them to the system.", NOT the app, hence the tool should not be dependent on the Android view hierarchy.

**Comment by andretietz** [comment]
True, my bad.

[Here a link to the docs](https://developer.android.com/studio/test/monkey)

**Comment by MaterialTime** [comment]
I've already been to the docs. That's how I know how to use it. The quote from my previous reply is also from the docs.

**Comment by MaterialTime** [comment]
Anyone else had this issue?

**Comment by mneira10** [comment]
Has anyone found a workaround yet?

**Comment by MaterialTime** [comment]
Nope. Still waiting.

**Comment by MaterialTime** [comment]
@kf6gpe I'm not sure if you added the platform-ios label by mistake, but please remove it. This issue is only about Android, and it doesn't even have the platform-android label.

**Comment by kf6gpe** [comment]
@MaterialTime Good catch, thank you. Slip of the fingers. Fixed!

**Comment by mas17kaworu** [comment]
Meet the same issue on 

Flutter 1.7.8+hotfix.4 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 20e59316b8 (4 weeks ago) • 2019-07-18 20:04:33 -0700
Engine • revision fee001c93f
Tools • Dart 2.4.0

The problem occurred on a specific app. https://github.com/kaina404/FlutterDouBan

And manual click won't trigger the crash. Only "adb shell input tap xxx xxx"  will trigger it.

Logs:
08-13 17:53:54.163  5368  5368 E InputEventReceiver: Exception dispatching input event.

08-13 17:53:54.163  5368  5368 E MessageQueue-JNI: Exception in MessageQueue callback: handleReceiveCallback

08-13 17:53:54.164  5368  5368 E MessageQueue-JNI: java.lang.NullPointerException: Attempt to invoke virtual method 'float android.view.InputDevice$MotionRange.getMin()' on a null object reference

08-13 17:53:54.164  5368  5368 E MessageQueue-JNI: 	at io.flutter.view.FlutterView.addPointerForIndex(FlutterView.java:480)

08-13 17:53:54.164  5368  5368 E MessageQueue-JNI: 	at io.flutter.view.FlutterView.onTouchEvent(FlutterView.java:542)

08-13 17:53:54.164  5368  5368 E MessageQueue-JNI: 	at android.view.View.dispatchTouchEvent(View.java:9399)

08-13 17:53:54.164  5368  5368 E MessageQueue-JNI: 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2555)

08-13 17:53:54.164  5368  5368 E MessageQueue-JNI: 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2197)

08-13 17:53:54.164  5368  5368 E MessageQueue-JNI: 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2555)

08-13 17:53:54.164  5368  5368 E MessageQueue-JNI: 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2197)

08-13 17:53:54.164  5368  5368 E MessageQueue-JNI: 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2555)

08-13 17:53:54.164  5368  5368 E MessageQueue-JNI: 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2197)

08-13 17:53:54.164  5368  5368 E MessageQueue-JNI: 	at com.android.internal.policy.PhoneWindow$DecorView.superDispatchTouchEvent(PhoneWindow.java:2469)

08-13 17:53:54.164  5368  5368 E MessageQueue-JNI: 	at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1785)

08-13 17:53:54.164  5368  5368 E MessageQueue-JNI: 	at android.app.Activity.dispatchTouchEvent(Activity.java:2867)

08-13 17:53:54.164  5368  5368 E MessageQueue-JNI: 	at com.android.internal.policy.PhoneWindow$DecorView.dispatchTouchEvent(PhoneWindow.java:2430)

08-13 17:53:54.164  5368  5368 E MessageQueue-JNI: 	at android.view.View.dispatchPointerEvent(View.java:9619)

08-13 17:53:54.164  5368  5368 E MessageQueue-JNI: 	at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:4465)

08-13 17:53:54.164  5368  5368 E MessageQueue-JNI: 	at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4331)

08-13 17:53:54.164  5368  5368 E MessageQueue-JNI: 	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3865)

08-13 17:53:54.164  5368  5368 E MessageQueue-JNI: 	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3918)

08-13 17:53:54.164  5368  5368 E MessageQueue-JNI: 	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3884)

08-13 17:53:54.164  5368  5368 E MessageQueue-JNI: 	at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:4010)

08-13 17:53:54.164  5368  5368 E MessageQueue-JNI: 	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3892)

08-13 17:53:54.164  5368  5368 E MessageQueue-JNI: 	at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:4067)

08-13 17:53:54.164  5368  5368 E MessageQueue-JNI: 	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3865)

08-13 17:53:54.164  5368  5368 E MessageQueue-JNI: 	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3918)

08-13 17:53:54.164  5368  5368 E MessageQueue-JNI: 	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3884)

08-13 17:53:54.164  5368  5368 E MessageQueue-JNI: 	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3892)

08-13 17:53:54.164  5368  5368 E MessageQueue-JNI: 	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3865)

08-13 17:53:54.164  5368  5368 E MessageQueue-JNI: 	at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:6164)

08-13 17:53:54.164  5368  5368 E MessageQueue-JNI: 	at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:6138)

08-13 17:53:54.164  5368  5368 E MessageQueue-JNI: 	at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:6099)

08-13 17:53:54.164  5368  5368 E MessageQueue-JNI: 	at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:6280)

08-13 17:53:54.164  5368  5368 E MessageQueue-JNI: 	at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:192)

08-13 17:53:54.164  5368  5368 E MessageQueue-JNI: 	at android.os.MessageQueue.nativePollOnce(Native Method)

08-13 17:53:54.164  5368  5368 E MessageQueue-JNI: 	at android.os.MessageQueue.next(MessageQueue.java:330)

08-13 17:53:54.164  5368  5368 E MessageQueue-JNI: 	at android.os.Looper.loop(Looper.java:137)

08-13 17:53:54.164  5368  5368 E MessageQueue-JNI: 	at android.app.ActivityThread.main(ActivityThread.java:5665)

08-13 17:53:54.164  5368  5368 E MessageQueue-JNI: 	at java.lang.reflect.Method.invoke(Native Method)

08-13 17:53:54.164  5368  5368 E MessageQueue-JNI: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:799)

08-13 17:53:54.164  5368  5368 E MessageQueue-JNI: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:689)

08-13 17:53:54.165  5368  5368 D AndroidRuntime: Shutting down VM

--------- beginning of crash

08-13 17:53:54.165  5368  5368 E AndroidRuntime: FATAL EXCEPTION: main

08-13 17:53:54.165  5368  5368 E AndroidRuntime: Process: com.example.doubanapp, PID: 5368

08-13 17:53:54.165  5368  5368 E AndroidRuntime: java.lang.NullPointerException: Attempt to invoke virtual method 'float android.view.InputDevice$MotionRange.getMin()' on a null object reference

08-13 17:53:54.165  5368  5368 E AndroidRuntime: 	at io.flutter.view.FlutterView.addPointerForIndex(FlutterView.java:480)

08-13 17:53:54.165  5368  5368 E AndroidRuntime: 	at io.flutter.view.FlutterView.onTouchEvent(FlutterView.java:542)

08-13 17:53:54.165  5368  5368 E AndroidRuntime: 	at android.view.View.dispatchTouchEvent(View.java:9399)

08-13 17:53:54.165  5368  5368 E AndroidRuntime: 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2555)

08-13 17:53:54.165  5368  5368 E AndroidRuntime: 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2197)

08-13 17:53:54.165  5368  5368 E AndroidRuntime: 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2555)

08-13 17:53:54.165  5368  5368 E AndroidRuntime: 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2197)

08-13 17:53:54.165  5368  5368 E AndroidRuntime: 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2555)

08-13 17:53:54.165  5368  5368 E AndroidRuntime: 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2197)

08-13 17:53:54.165  5368  5368 E AndroidRuntime: 	at com.android.internal.policy.PhoneWindow$DecorView.superDispatchTouchEvent(PhoneWindow.java:2469)

08-13 17:53:54.165  5368  5368 E AndroidRuntime: 	at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1785)

08-13 17:53:54.165  5368  5368 E AndroidRuntime: 	at android.app.Activity.dispatchTouchEvent(Activity.java:2867)

08-13 17:53:54.165  5368  5368 E AndroidRuntime: 	at com.android.internal.policy.PhoneWindow$DecorView.dispatchTouchEvent(PhoneWindow.java:2430)

08-13 17:53:54.165  5368  5368 E AndroidRuntime: 	at android.view.View.dispatchPointerEvent(View.java:9619)

08-13 17:53:54.165  5368  5368 E AndroidRuntime: 	at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:4465)

08-13 17:53:54.165  5368  5368 E AndroidRuntime: 	at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4331)

08-13 17:53:54.165  5368  5368 E AndroidRuntime: 	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3865)

08-13 17:53:54.165  5368  5368 E AndroidRuntime: 	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3918)

08-13 17:53:54.165  5368  5368 E AndroidRuntime: 	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3884)

08-13 17:53:54.165  5368  5368 E AndroidRuntime: 	at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:4010)

08-13 17:53:54.165  5368  5368 E AndroidRuntime: 	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3892)

08-13 17:53:54.165  5368  5368 E AndroidRuntime: 	at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:4067)

08-13 17:53:54.165  5368  5368 E AndroidRuntime: 	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3865)

08-13 17:53:54.165  5368  5368 E AndroidRuntime: 	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3918)

08-13 17:53:54.165  5368  5368 E AndroidRuntime: 	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3884)

08-13 17:53:54.165  5368  5368 E AndroidRuntime: 	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3892)

08-13 17:53:54.165  5368  5368 E AndroidRuntime: 	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3865)

08-13 17:53:54.165  5368  5368 E AndroidRuntime: 	at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:6164)

08-13 17:53:54.165  5368  5368 E AndroidRuntime: 	at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:6138)

08-13 17:53:54.165  5368  5368 E AndroidRuntime: 	at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:6099)

08-13 17:53:54.165  5368  5368 E AndroidRuntime: 	at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:6280)

08-13 17:53:54.165  5368  5368 E AndroidRuntime: 	at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:192)

08-13 17:53:54.165  5368  5368 E AndroidRuntime: 	at android.os.MessageQueue.nativePollOnce(Native Method)

08-13 17:53:54.165  5368  5368 E AndroidRuntime: 	at android.os.MessageQueue.next(MessageQueue.java:330)

08-13 17:53:54.165  5368  5368 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:137)

08-13 17:53:54.165  5368  5368 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:5665)

08-13 17:53:54.165  5368  5368 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)

08-13 17:53:54.165  5368  5368 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:799)

08-13 17:53:54.165  5368  5368 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:689)

08-13 17:53:54.173  1055  2241 W ActivityManager:   Force finishing activity com.example.doubanapp/.MainActivity

**Comment by fzyzcjy** [comment]
Hi, any updates after 4 yr?
