### ISSUE TITLE
camera plugin - configureFailed - Failed to configure camera session

### ISSUE THREAD

**Issue by snoofer** [flutter/flutter#30637]
Depending of the SDK version, when trying to record a video, an exception "configureFailed" is thrown.

Exception is thrown on Emulator with SDK 22, but it works fine with version  28. Some real devices with SDK 23 will also generate the exception.
Tried different versions of camera plugin from 0.4.0 until 0.4.3+2

# Steps to Reproduce

Downloaded camera plugin example and run it on an emulator with sdk 22. 

AVD settings
```
CPU/ABI: Google APIs Intel Atom (x86)
Target: google_apis [Google APIs] (API level 22)
Skin: 720x1280
SD Card: 512M
fastboot.chosenSnapshotFile: 
runtime.network.speed: full
hw.accelerometer: yes
hw.device.name: 4.65in 720p (Galaxy Nexus)
hw.lcd.width: 720
hw.initialOrientation: Portrait
image.androidVersion.api: 22
tag.id: google_apis
hw.mainKeys: no
hw.camera.front: emulated
avd.ini.displayname: 4.65  720p (Galaxy Nexus) API 22
hw.gpu.mode: host
hw.ramSize: 1024
PlayStore.enabled: false
fastboot.forceColdBoot: no
hw.cpu.ncore: 4
hw.keyboard: yes
hw.sensors.proximity: yes
hw.dPad: no
hw.lcd.height: 1280
vm.heapSize: 80
skin.dynamic: yes
hw.device.manufacturer: Generic
hw.gps: yes
hw.audioInput: yes
image.sysdir.1: system-images\android-22\google_apis\x86\
showDeviceFrame: yes
hw.camera.back: virtualscene
AvdId: 4.65_720p_Galaxy_Nexus_API_22
hw.lcd.density: 320
hw.arc: false
hw.device.hash2: MD5:fcb1c44f60d9172bb27b44fdd821eed1
fastboot.forceChosenSnapshotBoot: no
fastboot.forceFastBoot: yes
hw.trackBall: no
hw.battery: yes
hw.sdCard: yes
tag.display: Google APIs
runtime.network.latency: none
disk.dataPartition.size: 800M
hw.sensors.orientation: yes
avd.ini.encoding: UTF-8
hw.gpu.enabled: yes
```

# Logs
```
Launching lib\main.dart on Android SDK built for x86 in debug mode...
Built build\app\outputs\apk\debug\app-debug.apk.
I/CameraManagerGlobal( 5720): getCameraService: Reconnecting to camera service
D/        ( 5720): HostConnection::get() New Host Connection established 0xaf05a330, tid 5740
D/EGL_emulation( 5720): eglMakeCurrent: 0xb4358ac0: ver 2 0
I/CameraManager( 5720): Using legacy camera HAL.
I/CameraDeviceState( 5720): Legacy camera service transitioning to state CONFIGURING
I/RequestThread-0( 5720): Configure outputs: 2 surfaces configured.
D/Camera  ( 5720): app passed NULL surface
I/RequestThread-0( 5720): configureOutputs - set take picture size to 1280x960
D/        ( 5720): HostConnection::get() New Host Connection established 0xaf05a830, tid 5763
D/EGL_emulation( 5720): eglCreateContext: 0x9c7fed00: maj 2 min 0 rcv 2
D/EGL_emulation( 5720): eglMakeCurrent: 0x9c7fed00: ver 2 0
I/CameraDeviceState( 5720): Legacy camera service transitioning to state IDLE
I/RequestQueue( 5720): Repeating capture request set.
W/LegacyRequestMapper( 5720): convertRequestMetadata - control.awbRegions setting is not supported, ignoring value
W/LegacyRequestMapper( 5720): convertRequestToMetadata - Ignoring android.lens.focusDistance false, only 0.0f is supported
D/        ( 5720): HostConnection::get() New Host Connection established 0xaf05a1f0, tid 5736
I/CameraDeviceState( 5720): Legacy camera service transitioning to state CAPTURING
D/        ( 5720): HostConnection::get() New Host Connection established 0xb40f14c0, tid 5737
I/RequestQueue( 5720): Repeating capture request cancelled.
I/CameraDeviceState( 5720): Legacy camera service transitioning to state IDLE
E/Legacy-CameraDevice-JNI( 5720): LegacyCameraDevice_nativeDetectSurfaceDimens: Error while querying surface width No such device (-19).
E/CameraDevice-0-LE( 5720): Surface bufferqueue is abandoned, cannot configure as output:
E/CameraDevice-0-LE( 5720): android.hardware.camera2.legacy.LegacyExceptionUtils$BufferQueueAbandonedException
E/CameraDevice-0-LE( 5720): 	at android.hardware.camera2.legacy.LegacyExceptionUtils.throwOnError(LegacyExceptionUtils.java:64)
E/CameraDevice-0-LE( 5720): 	at android.hardware.camera2.legacy.LegacyCameraDevice.getSurfaceSize(LegacyCameraDevice.java:531)
E/CameraDevice-0-LE( 5720): 	at android.hardware.camera2.legacy.LegacyCameraDevice.configureOutputs(LegacyCameraDevice.java:300)
E/CameraDevice-0-LE( 5720): 	at android.hardware.camera2.legacy.CameraDeviceUserShim.endConfigure(CameraDeviceUserShim.java:478)
E/CameraDevice-0-LE( 5720): 	at java.lang.reflect.Method.invoke(Native Method)
E/CameraDevice-0-LE( 5720): 	at java.lang.reflect.Method.invoke(Method.java:372)
E/CameraDevice-0-LE( 5720): 	at android.hardware.camera2.utils.Decorator.invoke(Decorator.java:80)
E/CameraDevice-0-LE( 5720): 	at java.lang.reflect.Proxy.invoke(Proxy.java:397)
E/CameraDevice-0-LE( 5720): 	at $Proxy1.endConfigure(Unknown Source)
E/CameraDevice-0-LE( 5720): 	at android.hardware.camera2.impl.CameraDeviceImpl.configureOutputsChecked(CameraDeviceImpl.java:383)
E/CameraDevice-0-LE( 5720): 	at android.hardware.camera2.impl.CameraDeviceImpl.createCaptureSession(CameraDeviceImpl.java:437)
E/CameraDevice-0-LE( 5720): 	at io.flutter.plugins.camera.CameraPlugin$Camera.startVideoRecording(CameraPlugin.java:675)
E/CameraDevice-0-LE( 5720): 	at io.flutter.plugins.camera.CameraPlugin$Camera.access$900(CameraPlugin.java:285)
E/CameraDevice-0-LE( 5720): 	at io.flutter.plugins.camera.CameraPlugin.onMethodCall(CameraPlugin.java:217)
E/CameraDevice-0-LE( 5720): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:201)
E/CameraDevice-0-LE( 5720): 	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:88)
E/CameraDevice-0-LE( 5720): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:202)
E/CameraDevice-0-LE( 5720): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/CameraDevice-0-LE( 5720): 	at android.os.MessageQueue.next(MessageQueue.java:143)
E/CameraDevice-0-LE( 5720): 	at android.os.Looper.loop(Looper.java:122)
E/CameraDevice-0-LE( 5720): 	at android.app.ActivityThread.main(ActivityThread.java:5254)
E/CameraDevice-0-LE( 5720): 	at java.lang.reflect.Method.invoke(Native Method)
E/CameraDevice-0-LE( 5720): 	at java.lang.reflect.Method.invoke(Method.java:372)
E/CameraDevice-0-LE( 5720): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
E/CameraDevice-0-LE( 5720): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
W/CameraDevice-JV-0( 5720): Stream configuration failed
E/CameraCaptureSession( 5720): Session 1: Failed to create capture session; configuration failed
I/flutter ( 5720): Error: configureFailed
I/flutter ( 5720): Error Message: Failed to configure camera session
```

# flutter doctor -v
```
[√] Flutter (Channel beta, v1.3.8, on Microsoft Windows [Version 10.0.17134.648], locale de-DE)
    • Flutter version 1.3.8 at E:\development\dart\sdk\flutter
    • Framework revision e5b1ed7a7f (5 weeks ago), 2019-03-06 14:23:37 -0800
    • Engine revision f4951df193
    • Dart version 2.2.1 (build 2.2.1-dev.0.0 571ea80e11)

[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at C:\Users\rs\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)
    • All Android licenses accepted.

[√] Android Studio (version 3.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 33.0.1
    • Dart plugin version 182.5215
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)

[√] VS Code (version 1.33.0)
    • VS Code at C:\Users\rs\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 2.25.0

[√] Connected device (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 5.1.1 (API 22) (emulator)

• No issues found!
```

**Comment by escamoteur** [comment]
Hi, sorry for the delay, I just want to check if you could solve this problem.

**Comment by iapicca** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
  
Thanks for your contribution.
