### ISSUE TITLE
GoogleSignIn: the getter 'authentication' called on null

### ISSUE THREAD

**Issue by MaterialTime** [flutter/flutter#30651]
## Steps to Reproduce

1. Follow instructions to setup google_sign_in with firebase_auth
2. Run app
3. Close and Run app again

## Logs

```
19:04:57.956 13 info flutter.tools I/flutter (23638): INFO: 2019-04-07 19:04:56.914231: signInQuiet: Start
19:04:57.983 14 info flutter.tools I/flutter (23638): INFO: 2019-04-07 19:04:56.968791: signIn: Are we logged in? true
19:04:57.983 15 info flutter.tools I/flutter (23638): INFO: 2019-04-07 19:04:56.969311: signIn: googleUser is null
19:04:58.000 16 info flutter.tools E/flutter (23638): [ERROR:flutter/lib/ui/ui_dart_state.cc(148)] Unhandled Exception: NoSuchMethodError: The getter 'authentication' was called on null.
19:04:58.000 17 info flutter.tools E/flutter (23638): Receiver: null
19:04:58.000 18 info flutter.tools E/flutter (23638): Tried calling: authentication
19:04:58.000 19 info flutter.tools E/flutter (23638): #0      Object.noSuchMethod (dart:core/runtime/libobject_patch.dart:50:5)
19:04:58.000 20 info flutter.tools E/flutter (23638): #1      FirebaseModel._firebaseSignIn (package:nitrogen/models/firebase_model.dart:122:41)
19:04:58.000 21 info flutter.tools E/flutter (23638): <asynchronous suspension>
19:04:58.000 22 info flutter.tools E/flutter (23638): #2      FirebaseModel.signInQuiet (package:nitrogen/models/firebase_model.dart:76:19)
19:04:58.000 23 info flutter.tools E/flutter (23638): <asynchronous suspension>
19:04:58.000 24 info flutter.tools E/flutter (23638): #3      main (package:nitrogen/main.dart:27:30)
19:04:58.000 25 info flutter.tools E/flutter (23638): <asynchronous suspension>
19:04:58.001 26 info flutter.tools E/flutter (23638): #4      _runMainZoned.<anonymous closure>.<anonymous closure> (dart:ui/hooks.dart:189:25)
19:04:58.001 27 info flutter.tools E/flutter (23638): #5      _rootRun (dart:async/zone.dart:1124:13)
19:04:58.001 28 info flutter.tools E/flutter (23638): #6      _CustomZone.run (dart:async/zone.dart:1021:19)
19:04:58.001 29 info flutter.tools E/flutter (23638): #7      _runZoned (dart:async/zone.dart:1516:10)
19:04:58.001 30 info flutter.tools E/flutter (23638): #8      runZoned (dart:async/zone.dart:1500:12)
19:04:58.001 31 info flutter.tools E/flutter (23638): #9      _runMainZoned.<anonymous closure> (dart:ui/hooks.dart:180:5)
19:04:58.001 32 info flutter.tools E/flutter (23638): #10     _startIsolate.<anonymous closure> (dart:isolate/runtime/libisolate_patch.dart:300:19)
19:04:58.001 33 info flutter.tools E/flutter (23638): #11     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:171:12)
```

## Output of Flutter Analyze

```
[!] Flutter (Channel stable, v1.2.1, on Linux, locale en_CA.UTF-8)
    • Flutter version 1.2.1 at /home/michael/sdk/flutter
    • Framework revision 8661d8aecd (7 weeks ago), 2019-02-14 19:19:53 -0800
    • Engine revision 3757390fa4
    • Dart version 2.1.2 (build 2.1.2-dev.0.0 0a7dcf17eb)
    ✗ Downloaded executables cannot execute on host.
      See https://github.com/flutter/flutter/issues/6207 for more information
      On Debian/Ubuntu/Mint: sudo apt-get install lib32stdc++6
      On Fedora: dnf install libstdc++.i686
      On Arch: pacman -S lib32-libstdc++5 (you need to enable multilib:
      https://wiki.archlinux.org/index.php/Official_repositories#multilib)


[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /home/michael/sdk/android
    • Android NDK location not configured (optional; useful for native profiling
      support)
    • Platform android-Q, build-tools 28.0.3
    • ANDROID_HOME = /home/michael/sdk/android
    • Java binary at: /snap/android-studio/73/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_152-release-1248-b01)
    • All Android licenses accepted.

[✓] Android Studio (version 3.3)
    • Android Studio at /snap/android-studio/73/android-studio
    • Flutter plugin version 34.0.1
    • Dart plugin version 182.5215
    • Java version OpenJDK Runtime Environment (build
      1.8.0_152-release-1248-b01)

[✓] Connected device (1 available)
    • Pixel 2 XL • 192.168.0.71:7755 • android-arm64 • Android Q (API 28)

! Doctor found issues in 1 category.
```

**Comment by MaterialTime** [comment]
I still need a solution to this problem to move forward with my app.

**Comment by MaterialTime** [comment]
Turns out, even though it says I'm logged in when I open the app, and thus bypasses my app's google sign in method, I still needed to run `googleSignIn.signInSilently()`. Closing as this is now solved.

**Comment by elhadjaoui** [comment]
Hi I facing the same problem, if you solved please help me

**Comment by mpfaff** [comment]
@elhadjaoui don't be useless. Read my last comment before I closed the issue. I explain what I did to solve it. If you still need more help after that, explain your issue in more detail.

**Comment by elhadjaoui** [comment]
@mpfaff thanks man I already solved I just forgot to configure the fingerprint certificate in firebase

**Comment by tharindu** [comment]
You can get around the exception with following code, where it checks specifically null value for google user. This happened when user cancels google account selection dialog for me.
```dart
      final GoogleSignInAccount googleUser = await _googleSignIn.signIn();
      if (googleUser == null) {
        // cancelled login
        print('Google Signin ERROR! googleUser: null!');
        return null;
      }
      final GoogleSignInAuthentication googleAuth = await googleUser
          .authentication;
     // continue google sign-in
```
