### ISSUE TITLE
Crash with TextField

### ISSUE THREAD

**Issue by AtixD** [flutter/flutter#30742]
```
flutter: ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
flutter: The following assertion was thrown building Overlay-[LabeledGlobalKey<OverlayState>#f8a96](state:
flutter: OverlayState#85ffd(tickers: tracking 0 tickers, entries: [OverlayEntry#96e75(opaque: false;
flutter: maintainState: false), OverlayEntry#0c4a5(opaque: false; maintainState: true),
flutter: OverlayEntry#2aeb9(opaque: true; maintainState: false), OverlayEntry#97d49(opaque: false;
flutter: maintainState: true), OverlayEntry#2704e(opaque: true; maintainState: false),
flutter: OverlayEntry#4fbdd(opaque: false; maintainState: true), OverlayEntry#c845d(opaque: true;
flutter: maintainState: false), OverlayEntry#7abaf(opaque: false; maintainState: true)])):
flutter: 'package:flutter/src/material/material.dart': Failed assertion: line 480 pos 12: '_inkFeatures !=
flutter: null': is not true.
flutter:
flutter: Either the assertion indicates an error in the framework itself, or we should provide substantially
flutter: more information in this error message to help you determine and fix the underlying cause.
flutter: In either case, please report this assertion by filing a bug on GitHub:
flutter:   https://github.com/flutter/flutter/issues/new?template=BUG.md
flutter:
flutter: When the exception was thrown, this was the stack:
flutter: #2      _RenderInkFeatures._removeFeature 
package:flutter/…/material/material.dart:480
flutter: #3      InkFeature.dispose 
package:flutter/…/material/material.dart:573
flutter: #4      _TextFieldState.deactivate 
package:flutter/…/material/text_field.dart:730
flutter: #5      StatefulElement.deactivate 
package:flutter/…/widgets/framework.dart:3909
flutter: #6      _InactiveElements._deactivateRecursively 
package:flutter/…/widgets/framework.dart:1714
flutter: #7      ComponentElement.visitChildren 
package:flutter/…/widgets/framework.dart:3770
flutter: #8      _InactiveElements._deactivateRecursively 
package:flutter/…/widgets/framework.dart:1716
flutter: #9      ComponentElement.visitChildren 
package:flutter/…/widgets/framework.dart:3770
flutter: #10     _InactiveElements._deactivateRecursively 
package:flutter/…/widgets/framework.dart:1716
flutter: #11     ComponentElement.visitChildren 
package:flutter/…/widgets/framework.dart:3770
flutter: #12     _InactiveElements._deactivateRecursively 
package:flutter/…/widgets/framework.dart:1716
flutter: #13     ComponentElement.visitChildren 
package:flutter/…/widgets/framework.dart:3770
flutter: #14     _InactiveElements._deactivateRecursively 
package:flutter/…/widgets/framework.dart:1716
flutter: #15     MultiChildRenderObjectElement.visitChildren 
package:flutter/…/widgets/framework.dart:4965
flutter: #16     _InactiveElements._deactivateRecursively 
package:flutter/…/widgets/framework.dart:1716
flutter: #17     ComponentElement.visitChildren 
package:flutter/…/widgets/framework.dart:3770
flutter: #18     _InactiveElements._deactivateRecursively 
package:flutter/…/widgets/framework.dart:1716
flutter: #19     ComponentElement.visitChildren 
package:flutter/…/widgets/framework.dart:3770
flutter: #20     _InactiveElements._deactivateRecursively 
package:flutter/…/widgets/framework.dart:1716
flutter: #21     ComponentElement.visitChildren 
package:flutter/…/widgets/framework.dart:3770
flutter: #22     _InactiveElements._deactivateRecursively 
package:flutter/…/widgets/framework.dart:1716
flutter: #23     SingleChildRenderObjectElement.visitChildren 
package:flutter/…/widgets/framework.dart:4864
flutter: #24     _InactiveElements._deactivateRecursively 
package:flutter/…/widgets/framework.dart:1716
flutter: #25     ComponentElement.visitChildren 
package:flutter/…/widgets/framework.dart:3770
flutter: #26     _InactiveElements._deactivateRecursively 
package:flutter/…/widgets/framework.dart:1716
flutter: #27     SingleChildRenderObjectElement.visitChildren 
package:flutter/…/widgets/framework.dart:4864
flutter: #28     _InactiveElements._deactivateRecursively 
package:flutter/…/widgets/framework.dart:1716
flutter: #29     ComponentElement.visitChildren 
package:flutter/…/widgets/framework.dart:3770
flutter: #30     _InactiveElements._deactivateRecursively 
package:flutter/…/widgets/framework.dart:1716
flutter: #31     ComponentElement.visitChildren 
package:flutter/…/widgets/framework.dart:3770
flutter: #32     _InactiveElements._deactivateRecursively 
package:flutter/…/widgets/framework.dart:1716
flutter: #33     ComponentElement.visitChildren 
package:flutter/…/widgets/framework.dart:3770
flutter: #34     _InactiveElements._deactivateRecursively 
package:flutter/…/widgets/framework.dart:1716
flutter: #35     ComponentElement.visitChildren 
package:flutter/…/widgets/framework.dart:3770
flutter: #36     _InactiveElements._deactivateRecursively 
package:flutter/…/widgets/framework.dart:1716
flutter: #37     ComponentElement.visitChildren 
package:flutter/…/widgets/framework.dart:3770
flutter: #38     _InactiveElements._deactivateRecursively 
package:flutter/…/widgets/framework.dart:1716
flutter: #39     SingleChildRenderObjectElement.visitChildren 
package:flutter/…/widgets/framework.dart:4864
flutter: #40     _InactiveElements._deactivateRecursively 
package:flutter/…/widgets/framework.dart:1716
flutter: #41     ComponentElement.visitChildren 
package:flutter/…/widgets/framework.dart:3770
flutter: #42     _InactiveElements._deactivateRecursively 
package:flutter/…/widgets/framework.dart:1716
flutter: #43     SingleChildRenderObjectElement.visitChildren 
package:flutter/…/widgets/framework.dart:4864
flutter: #44     _InactiveElements._deactivateRecursively 
package:flutter/…/widgets/framework.dart:1716
flutter: #45     SingleChildRenderObjectElement.visitChildren 
package:flutter/…/widgets/framework.dart:4864
flutter: #46     _InactiveElements._deactivateRecursively 
package:flutter/…/widgets/framework.dart:1716
flutter: #47     SingleChildRenderObjectElement.visitChildren 
package:flutter/…/widgets/framework.dart:4864
flutter: #48     _InactiveElements._deactivateRecursively 
package:flutter/…/widgets/framework.dart:1716
flutter: #49     ComponentElement.visitChildren 
package:flutter/…/widgets/framework.dart:3770
flutter: #50     _InactiveElements._deactivateRecursively 
package:flutter/…/widgets/framework.dart:1716
flutter: #51     SingleChildRenderObjectElement.visitChildren 
package:flutter/…/widgets/framework.dart:4864
flutter: #52     _InactiveElements._deactivateRecursively 
package:flutter/…/widgets/framework.dart:1716
flutter: #53     ComponentElement.visitChildren 
package:flutter/…/widgets/framework.dart:3770
flutter: #54     _InactiveElements._deactivateRecursively 
package:flutter/…/widgets/framework.dart:1716
flutter: #55     SingleChildRenderObjectElement.visitChildren 
package:flutter/…/widgets/framework.dart:4864
flutter: #56     _InactiveElements._deactivateRecursively 
package:flutter/…/widgets/framework.dart:1716
flutter: #57     ComponentElement.visitChildren 
package:flutter/…/widgets/framework.dart:3770
flutter: #58     _InactiveElements._deactivateRecursively 
package:flutter/…/widgets/framework.dart:1716
flutter: #59     ComponentElement.visitChildren 
package:flutter/…/widgets/framework.dart:3770
flutter: #60     _InactiveElements._deactivateRecursively 
package:flutter/…/widgets/framework.dart:1716
flutter: #61     ComponentElement.visitChildren 
package:flutter/…/widgets/framework.dart:3770
flutter: #62     _InactiveElements._deactivateRecursively 
package:flutter/…/widgets/framework.dart:1716
flutter: #63     SingleChildRenderObjectElement.visitChildren 
package:flutter/…/widgets/framework.dart:4864
flutter: #64     _InactiveElements._deactivateRecursively 
package:flutter/…/widgets/framework.dart:1716
flutter: #65     ComponentElement.visitChildren 
package:flutter/…/widgets/framework.dart:3770
flutter: #66     _InactiveElements._deactivateRecursively 
package:flutter/…/widgets/framework.dart:1716
flutter: #67     SingleChildRenderObjectElement.visitChildren 
package:flutter/…/widgets/framework.dart:4864
flutter: #68     _InactiveElements._deactivateRecursively 
package:flutter/…/widgets/framework.dart:1716
flutter: #69     ComponentElement.visitChildren 
package:flutter/…/widgets/framework.dart:3770
flutter: #70     _InactiveElements._deactivateRecursively 
package:flutter/…/widgets/framework.dart:1716
flutter: #71     ComponentElement.visitChildren 
package:flutter/…/widgets/framework.dart:3770
flutter: #72     _InactiveElements._deactivateRecursively 
package:flutter/…/widgets/framework.dart:1716
flutter: #73     SingleChildRenderObjectElement.visitChildren 
package:flutter/…/widgets/framework.dart:4864
flutter: #74     _InactiveElements._deactivateRecursively 
package:flutter/…/widgets/framework.dart:1716
flutter: #75     ComponentElement.visitChildren 
package:flutter/…/widgets/framework.dart:3770
flutter: #76     _InactiveElements._deactivateRecursively 
package:flutter/…/widgets/framework.dart:1716
flutter: #77     ComponentElement.visitChildren 
package:flutter/…/widgets/framework.dart:3770
flutter: #78     _InactiveElements._deactivateRecursively 
package:flutter/…/widgets/framework.dart:1716
flutter: #79     ComponentElement.visitChildren 
package:flutter/…/widgets/framework.dart:3770
flutter: #80     _InactiveElements._deactivateRecursively 
package:flutter/…/widgets/framework.dart:1716
flutter: #81     _InactiveElements.add 
package:flutter/…/widgets/framework.dart:1725
flutter: #82     Element.deactivateChild 
package:flutter/…/widgets/framework.dart:2992
flutter: #83     RenderObjectElement.updateChildren 
package:flutter/…/widgets/framework.dart:4694
flutter: #84     MultiChildRenderObjectElement.update 
package:flutter/…/widgets/framework.dart:4992
flutter: #85     Element.updateChild 
package:flutter/…/widgets/framework.dart:2748
flutter: #86     _TheatreElement.update 
package:flutter/…/widgets/overlay.dart:508
flutter: #87     Element.updateChild 
package:flutter/…/widgets/framework.dart:2748
flutter: #88     ComponentElement.performRebuild 
package:flutter/…/widgets/framework.dart:3747
flutter: #89     Element.rebuild 
package:flutter/…/widgets/framework.dart:3559
flutter: #90     BuildOwner.buildScope 
package:flutter/…/widgets/framework.dart:2273
flutter: #91     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding&WidgetsBinding.drawFrame 
package:flutter/…/widgets/binding.dart:700
flutter: #92     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding._handlePersistentFrameCallback 
package:flutter/…/rendering/binding.dart:268
flutter: #93     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._invokeFrameCallback 
package:flutter/…/scheduler/binding.dart:988
flutter: #94     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.handleDrawFrame 
package:flutter/…/scheduler/binding.dart:928
flutter: #95     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._handleDrawFrame 
package:flutter/…/scheduler/binding.dart:840
flutter: #99     _invoke (dart:ui/hooks.dart:209:10)
flutter: #100    _drawFrame (dart:ui/hooks.dart:168:3)
flutter: (elided 5 frames from class _AssertionError and package dart:async)
flutter: ════════════════════════════════════════════════════════════════════════════════════════════════════
```

```
[✓] Flutter (Channel stable, v1.2.1, on Mac OS X 10.14.4 18E226, locale ru-RU)
    • Flutter version 1.2.1 at /Users/reuf/development/flutter
    • Framework revision 8661d8aecd (8 weeks ago), 2019-02-14 19:19:53 -0800
    • Engine revision 3757390fa4
    • Dart version 2.1.2 (build 2.1.2-dev.0.0 0a7dcf17eb)

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/reuf/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)
    • All Android licenses accepted.

[!] iOS toolchain - develop for iOS devices (Xcode 10.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.2, Build version 10E125
    ✗ libimobiledevice and ideviceinstaller are not installed. To install with Brew, run:
        brew update
        brew install --HEAD usbmuxd
        brew link usbmuxd
        brew install --HEAD libimobiledevice
        brew install ideviceinstaller
    ✗ ios-deploy not installed. To install:
        brew install ios-deploy
    • CocoaPods version 1.5.3

[!] Android Studio (version 3.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    • Dart plugin version 173.4700
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)

[✓] VS Code (version 1.33.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 2.25.0

[✓] Connected device (1 available)
    • iPhone X • CAB2B208-B34A-4042-9C15-30EB7E4CB38A • ios • com.apple.CoreSimulator.SimRuntime.iOS-12-2 (simulator)

! Doctor found issues in 2 categories.
```

```
import 'package:flutter/material.dart';

class OrderScreen extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Container(
      child: TextField(
        maxLines: 22,
      ),
    );
  }
}
```

When I put focus on input, then I do navigation (Navigator.of(context)
              .push(TransitionPageIOS(widget: ConfirmOrderScenes()));), the error occurs above.

```
class TransitionPageIOS extends CupertinoPageRoute {
  final Widget widget;

  @override
  Color get barrierColor => null;

  @override
  String get barrierLabel => null;

  @override
  String get currentResult => widget.toStringShort();

  @override
  bool canTransitionFrom(TransitionRoute<dynamic> previousRoute) {
    return true;
  }

  @override
  bool canTransitionTo(TransitionRoute<dynamic> nextRoute) {
    return true;
  }

  @override
  Duration get transitionDuration => const Duration(milliseconds: 550);

  @override
  Widget buildTransitions(BuildContext context, Animation<double> animation,
      Animation<double> secondaryAnimation, Widget child) {
    return CupertinoPageTransition(
        linearTransition: false,
        primaryRouteAnimation: animation,
        secondaryRouteAnimation: secondaryAnimation,
        child: child);
  }

  TransitionPageIOS({this.widget})
      : super(
          builder: (context) => Scaffold(
                body: widget,
                resizeToAvoidBottomPadding: false,
              ),
        );
}
```
Main

```
class NoSplashFactory extends InteractiveInkFeatureFactory {
  const NoSplashFactory();

  @override
  InteractiveInkFeature create(
      {MaterialInkController controller,
      RenderBox referenceBox,
      Offset position,
      Color color,
      TextDirection textDirection,
      bool containedInkWell = false,
      rectCallback,
      BorderRadius borderRadius,
      ShapeBorder customBorder,
      double radius,
      onRemoved}) {
    return new NoSplash(
      controller: controller,
      referenceBox: referenceBox,
    );
  }
}

class NoSplash extends InteractiveInkFeature {
  NoSplash({
    @required MaterialInkController controller,
    @required RenderBox referenceBox,
  })  : assert(controller != null),
        assert(referenceBox != null),
        super(
          controller: controller,
          referenceBox: referenceBox,
        );

  @override
  void paintFeature(Canvas canvas, Matrix4 transform) {}
}

child: MaterialApp(
          theme: ThemeData(
              splashFactory: NoSplashFactory(),
              accentColor: Color.fromRGBO(11, 32, 49, 0.5),
              textTheme: TextTheme(
                  body1: TextStyle(color: Colors.white, fontFamily: 'Lato'))),
          home: Scaffold(
...
```

**Comment by AtixD** [comment]
here is the solution to this problem 
https://github.com/flutter/flutter/issues/20874
