### ISSUE TITLE
image_picker: Fatal Exception when setting up a maxWidth / maxHeight

### ISSUE THREAD

**Issue by TheScayn** [flutter/flutter#30783]
Same issue as #29594, but I'm on version 0.5.2.

## Description

When I try to get an image from the gallery with unbounded height and width, it perfectly works. However, with a certain amount of maxWidth and maxHeight, the app crashes.

Nevertheless, It does work when I pick a picture from the camera.

I believed that the version 0.5.1 fixed the issue by "not removing the original image after scaled" (#1445) but the problem seems to persist :/

Furthermore, sometimes, the problem completely erases the picture from the gallery!

## Error

```
E/BitmapFactory(31370): Unable to decode stream: java.io.FileNotFoundException: /storage/emulated/0/DCIM/Screenshots/Screenshot_20190408-214739_Drive.jpg (No such file or directory)
D/AndroidRuntime(31370): Shutting down VM
E/AndroidRuntime(31370): FATAL EXCEPTION: main
E/AndroidRuntime(31370): Process: com.example.app, PID: 31370
E/AndroidRuntime(31370): java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=2342, result=-1, data=Intent { dat=content://com.android.providers.media.documents/document/image:8670 flg=0x1 }} to activity {com.example.app/com.example.app.MainActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'int android.graphics.Bitmap.getWidth()' on a null object reference
E/AndroidRuntime(31370): 	at android.app.ActivityThread.deliverResults(ActivityThread.java:4491)
E/AndroidRuntime(31370): 	at android.app.ActivityThread.handleSendResult(ActivityThread.java:4534)
E/AndroidRuntime(31370): 	at android.app.ActivityThread.-wrap20(Unknown Source:0)
E/AndroidRuntime(31370): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1752)
E/AndroidRuntime(31370): 	at android.os.Handler.dispatchMessage(Handler.java:105)
E/AndroidRuntime(31370): 	at android.os.Looper.loop(Looper.java:164)
E/AndroidRuntime(31370): 	at android.app.ActivityThread.main(ActivityThread.java:6944)
E/AndroidRuntime(31370): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(31370): 	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
E/AndroidRuntime(31370): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)
E/AndroidRuntime(31370): Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'int android.graphics.Bitmap.getWidth()' on a null object reference
E/AndroidRuntime(31370): 	at io.flutter.plugins.imagepicker.ImageResizer.resizedImage(ImageResizer.java:48)
E/AndroidRuntime(31370): 	at io.flutter.plugins.imagepicker.ImageResizer.resizeImageIfNeeded(ImageResizer.java:37)
E/AndroidRuntime(31370): 	at io.flutter.plugins.imagepicker.ImagePickerDelegate.handleImageResult(ImagePickerDelegate.java:430)
E/AndroidRuntime(31370): 	at io.flutter.plugins.imagepicker.ImagePickerDelegate.handleChooseImageResult(ImagePickerDelegate.java:372)
E/AndroidRuntime(31370): 	at io.flutter.plugins.imagepicker.ImagePickerDelegate.onActivityResult(ImagePickerDelegate.java:351)
E/AndroidRuntime(31370): 	at io.flutter.app.FlutterPluginRegistry.onActivityResult(FlutterPluginRegistry.java:210)
E/AndroidRuntime(31370): 	at io.flutter.app.FlutterActivityDelegate.onActivityResult(FlutterActivityDelegate.java:143)
E/AndroidRuntime(31370): 	at io.flutter.app.FlutterActivity.onActivityResult(FlutterActivity.java:142)
E/AndroidRuntime(31370): 	at android.app.Activity.dispatchActivityResult(Activity.java:7556)
E/AndroidRuntime(31370): 	at android.app.ActivityThread.deliverResults(ActivityThread.java:4487)
E/AndroidRuntime(31370): 	... 9 more
```

## Code

```dart
Future getImage(ImageSource source) async {
    var image = await ImagePicker.pickImage(source: source, maxWidth: 640, maxHeight: 480);
    setState(() {
      _image = image;
    });
}
```

## Plugins

```dart
  http: ^0.12.0+1
  image_picker: ^0.5.2
  flutter_exif_rotation: ^0.2.1
  permission_handler: ^2.2.0
```

**Comment by jlcool** [comment]
Really, it's not that maxwidth doesn't crash, but the pictures are still unreadable, please officially solve it.

**Comment by escamoteur** [comment]
this is now tracked here https://github.com/flutter/flutter/issues/40831. Best to upvote that issue.

**Comment by escamoteur** [comment]
It seems that the latest version no longer crashes but ignores the size.
