### ISSUE TITLE
[path_provider] plugin causes android.os.strictmode.DiskReadViolation

### ISSUE THREAD

**Issue by ened** [flutter/flutter#30794]
Currently, the path_provider plugin causes an `android.os.strictmode.DiskReadViolation` warning on Android.

```
StrictMode policy violation; ~duration=2 ms: android.os.strictmode.DiskReadViolation
    at android.os.StrictMode$AndroidBlockGuardPolicy.onReadFromDisk(StrictMode.java:1514)
    at java.io.UnixFileSystem.checkAccess(UnixFileSystem.java:251)
    at java.io.File.exists(File.java:815)
    at android.app.ContextImpl.ensureExternalDirsExistOrFilter(ContextImpl.java:2895)
    at android.app.ContextImpl.getExternalCacheDirs(ContextImpl.java:852)
    at android.content.ContextWrapper.getExternalCacheDirs(ContextWrapper.java:284)
    at io.flutter.plugins.pathprovider.PathProviderPlugin.getPathProviderExternalCacheDirectories(PathProviderPlugin.java:75)
    at io.flutter.plugins.pathprovider.PathProviderPlugin.onMethodCall(PathProviderPlugin.java:48)
    at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:201)
    at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:88)
    at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:219)
    at android.os.MessageQueue.nativePollOnce(Native Method)
    at android.os.MessageQueue.next(MessageQueue.java:386)
    at android.os.Looper.loop(Looper.java:169)
    at android.app.ActivityThread.main(ActivityThread.java:7470)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:958)
```

You can enable StrictMode checking by amending `onCreate` in the Application:

```
    @Override
    public void onCreate() {
        super.onCreate();

        StrictMode.setThreadPolicy(
                new StrictMode.ThreadPolicy
                        .Builder()
                        .detectAll()
                        .penaltyLog()
                        .build()
        );
        StrictMode.setVmPolicy(
                new StrictMode.VmPolicy
                        .Builder()
                        .detectAll()
                        .penaltyLog()
                        .build()
        );

    }
```

**Comment by escamoteur** [comment]
Hi, sorry for the delay, I just want to check if you could solve this problem.

**Comment by iapicca** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
  
Thanks for your contribution.
