### ISSUE TITLE
trying to get context from registar to pass to native android library, but the registar context is null

### ISSUE THREAD

**Issue by drkhannah** [flutter/flutter#30853]
I'm trying to create a Flutter Plugin that uses a native Android sdk

I'm able to compile the .aar libraries of the sdk and use them in the project but the sdk requires me to get the context of the main activity

here is the error im getting

```Installing build/app/outputs/apk/app.apk...
E/MethodChannel#mychart_plugin(16533): Failed to handle method call
E/MethodChannel#mychart_plugin(16533): kotlin.KotlinNullPointerException
E/MethodChannel#mychart_plugin(16533): 	at org.ccf.flutter.plugin.mychart_plugin.MychartPlugin.getContext(MychartPlugin.kt:79)
E/MethodChannel#mychart_plugin(16533): 	at epic.mychart.android.library.api.authentication.WPAPIAuthentication$1.getContext(WPAPIAuthentication.java:564)
E/MethodChannel#mychart_plugin(16533): 	at epic.mychart.android.library.prelogin.AuthenticationService.libraryLogin(AuthenticationService.java:461)
E/MethodChannel#mychart_plugin(16533): 	at epic.mychart.android.library.api.authentication.WPAPIAuthentication.login(WPAPIAuthentication.java:411)
E/MethodChannel#mychart_plugin(16533): 	at org.ccf.flutter.plugin.mychart_plugin.MychartPlugin.onMethodCall(MychartPlugin.kt:42)
E/MethodChannel#mychart_plugin(16533): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:201)
E/MethodChannel#mychart_plugin(16533): 	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:88)
E/MethodChannel#mychart_plugin(16533): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:219)
E/MethodChannel#mychart_plugin(16533): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/MethodChannel#mychart_plugin(16533): 	at android.os.MessageQueue.next(MessageQueue.java:325)
E/MethodChannel#mychart_plugin(16533): 	at android.os.Looper.loop(Looper.java:142)
E/MethodChannel#mychart_plugin(16533): 	at android.app.ActivityThread.main(ActivityThread.java:6541)
E/MethodChannel#mychart_plugin(16533): 	at java.lang.reflect.Method.invoke(Native Method)
E/MethodChannel#mychart_plugin(16533): 	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
E/MethodChannel#mychart_plugin(16533): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)```

here is my code for getting the context


```package org.ccf.flutter.plugin.mychart_plugin

import io.flutter.plugin.common.MethodCall
import io.flutter.plugin.common.MethodChannel
import io.flutter.plugin.common.MethodChannel.MethodCallHandler
import io.flutter.plugin.common.MethodChannel.Result
import io.flutter.plugin.common.PluginRegistry.Registrar

import epic.mychart.android.library.api.authentication.WPAPIAuthentication;
import epic.mychart.android.library.api.general.WPAccessResult;
import epic.mychart.android.library.api.prelogin.WPAPIPrelogin;
import android.widget.Toast
import android.util.Log
import android.content.Intent
import android.app.Activity
import android.support.v4.app.FragmentActivity
import android.support.v4.app.FragmentManager
import android.content.Context
import io.flutter.plugin.common.PluginRegistry



class MychartPlugin: MethodCallHandler, WPAPIAuthentication.IWPOnLoginListener {
  private var registrar: PluginRegistry.Registrar? = null
  private val LOGIN_REQUEST_CODE = 9876

  fun MychartPlugin(registrar: PluginRegistry.Registrar) {
    this.registrar = registrar
  }
  companion object {
    @JvmStatic
    fun registerWith(registrar: Registrar) {
      val channel = MethodChannel(registrar.messenger(), "mychart_plugin")
      channel.setMethodCallHandler(MychartPlugin())
    }
  }

  override fun onMethodCall(call: MethodCall, result: Result) {
    if (call.method == "getPlatformVersion") {
      result.success("Android ${android.os.Build.VERSION.RELEASE}")
    } else if (call.method == "MyChartSdkLogin") {
      WPAPIAuthentication.login(this, "TURKJ123", "TurkJ123", LOGIN_REQUEST_CODE)
      result.success("called MyChartSdkLogin")
    }  else {
      result.notImplemented()
    }
  }


  override fun onActivityResult(requestCode: Int, resultCode: Int, data: Intent) {
    // super.onActivityResult(requestCode, resultCode, data)
    if (requestCode == LOGIN_REQUEST_CODE) {
      if (resultCode == Activity.RESULT_OK) {
        // login successful
        Log.i("LoginFragment", "OK")

      } else {
        // login failed
        val result = WPAPIAuthentication.getLoginResult(data)
        Log.i("LoginFragment", result.toString())
        val errorMessage = result.getErrorMessage(getContext())
        if (!errorMessage.isEmpty()) {
          Toast.makeText(getContext(), errorMessage, Toast.LENGTH_LONG).show()
        }
      }
    }
  }

  override fun startActivityForResult(p0: Intent, p1: Int) {
    // super.startActivityForResult(p0, p1)
  }

  override fun getSupportFragmentManager(): FragmentManager {
    val act = registrar!!.activity() as FragmentActivity
    return act.getSupportFragmentManager()
  }

  override fun getContext(): Context {
    return registrar!!.context()
  }
}
```

notice the override getContext() method that im overriding from the sdk, I think this context call to the registar is where my KotlinNullPointerException is coming from

**Comment by drkhannah** [comment]
also at compile time in android studio it doesn't recognize any of the sdk imports when im working in the native android plugin class like this one for example `import epic.mychart.android.library.api.authentication.WPAPIAuthentication;` 

is there a way to get android studio to recognize these at compile time? i tried to add the libraries to the plugin android module in Android Studio's project structure as a module dependency, but they are still not recognized by Android Studio

any help here would be greatly appreciated as well

thank you

**Comment by wesleyguirra** [comment]
did you get how to actieve this?
