### ISSUE TITLE
Flutter headless runner + hot restart == main running twice

### ISSUE THREAD

**Issue by long1eu** [flutter/flutter#30918]
I have an issue with the flutter headless runner. When I hit hot restart it seems like my apps `main` runs twice. Here is a minimal example.

https://github.com/long1eu/double_main

```
Performing hot restart...
Syncing files to device Razvan’s iPad...
flutter: main called
Restarted application in 2,077ms.
flutter: main called
[VERBOSE-2:ui_dart_state.cc(148)] Unhandled Exception: MissingPluginException(No implementation found for method ForegroundRunner.initialize on channel com.app/foreground_channel)
#0      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:300:7)
<asynchronous suspension>
#1      _MyAppState.initState (package:double_main/main.dart:24:13)
#2      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3846:58)
#3      ComponentElement.mount (package:flutter/src/widgets/framework.dart:3711:5)
#4      Element.inflateWidget (package:flutter/src/widgets/framework.dart:2956:14)
#5      Element.updateChild (package:flutter/src/widgets/framework.dart:2759:12)
#6      RenderObjectToWidgetElement._rebuild (package:flutter/src/widgets/binding.dart:933:16)
#7      RenderObjectToWidgetElement.mount (package:flutter/src/widgets/binding.dart:904:5)
#8      RenderObjectToWidgetAdapter.attachToRenderTree.<anonymous closure> (package:flutter/src/widgets/binding.dart:850:17)
#9      BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2253:19)
#10     RenderObjectToWidgetAdapter.attachToRenderTree (package:flutter/src/widgets/binding.dart:849:13)
#11     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding&WidgetsBinding.attachRootWidget (package:flutter/src/widgets/binding.dart:736:7)
#12     runApp (package:flutter/src/widgets/binding.dart:780:7)
#13     main (package:double_main/main.dart:8:3)
#14     _runMainZoned.<anonymous closure>.<anonymous closure> (dart:ui/hooks.dart:189:25)
#15     _rootRun (dart:async/zone.dart:1124:13)
#16     _CustomZone.run (dart:async/zone.dart:1021:19)
#17     _runZoned (dart:async/zone.dart:1516:10)
#18     runZoned (dart:async/zone.dart:1500:12)
#19     _runMainZoned.<anonymous closure> (dart:ui/hooks.dart:180:5)
#20     _startIsolate.<anonymous closure> (dart:isolate/runtime/libisolate_patch.dart:300:19)
#21     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:171:12)
```

**Comment by jonahwilliams** [comment]
I suspect this is related to the issues with android alarm manager and others where we naively attempt to reload all running isolates with a flutter view.

**Comment by long1eu** [comment]
I only tested this on iOS.

**Comment by long1eu** [comment]
any workaround this?

**Comment by long1eu** [comment]
This is very annoying. Can you please point me in the right direction?

**Comment by long1eu** [comment]
any news?

**Comment by long1eu** [comment]
Sorry to spam this but this is important to me.

**Comment by long1eu** [comment]
@Hixie @jonahwilliams anyone?

**Comment by audkar** [comment]
> I suspect this is related to the issues with android alarm manager and others where we naively attempt to reload all running isolates with a flutter view.

@jonahwilliams is there any workaround we can try to solve this on our end?

**Comment by darshankawar** [comment]
Considering the age of the issue and lack of activity, I am going ahead and closing this as stale.
I cloned the repo to run it on iOS, but since there are lot of compile errors due to app being created with very old version, I could not replicate it.
@long1eu If you are still experiencing this issue using latest stable version, please open a new issue using template so that we can address it.
If anybody disagrees, please write in comments and I'll reopen it.
