### ISSUE TITLE
"Change Rect internal representation from Float32List to Float64List (#8524)" causes Rect comparisons to fail

### ISSUE THREAD

**Issue by bkonyi** [flutter/flutter#30920]
Sample of failing test ([full logs here](https://api.cirrus-ci.com/v1/task/5135058510807040/logs/test.log)):

```
04:04 +3164 ~31 -6: /tmp/flutter sdk/packages/flutter/test/material/scaffold_test.dart: Scaffold and extreme window padding                                                                            
══╡ EXCEPTION CAUGHT BY FLUTTER TEST FRAMEWORK ╞════════════════════════════════════════════════════
The following TestFailure object was thrown running a test:
  Expected: Rect:<Rect.fromLTRB(36.0, 255.0, 113.0, 332.0)>
  Actual: Rect:<Rect.fromLTRB(36.0, 255.0, 113.0, 332.0)>

When the exception was thrown, this was the stack:
#4      main.<anonymous closure> (file:///tmp/flutter%20sdk/packages/flutter/test/material/scaffold_test.dart:765:5)
<asynchronous suspension>
#5      testWidgets.<anonymous closure>.<anonymous closure> (package:flutter_test/src/widget_tester.dart:108:25)
<asynchronous suspension>
#6      TestWidgetsFlutterBinding._runTestBody (package:flutter_test/src/binding.dart:589:19)
<asynchronous suspension>
#9      TestWidgetsFlutterBinding._runTest (package:flutter_test/src/binding.dart:573:14)
#10     AutomatedTestWidgetsFlutterBinding.runTest.<anonymous closure> (package:flutter_test/src/binding.dart:920:24)
#16     AutomatedTestWidgetsFlutterBinding.runTest (package:flutter_test/src/binding.dart:917:15)
#17     testWidgets.<anonymous closure> (package:flutter_test/src/widget_tester.dart:106:22)
#18     Declarer.test.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:test_api/src/backend/declarer.dart:168:27)
<asynchronous suspension>
#19     Invoker.waitForOutstandingCallbacks.<anonymous closure> (package:test_api/src/backend/invoker.dart:250:15)
<asynchronous suspension>
#24     Invoker.waitForOutstandingCallbacks (package:test_api/src/backend/invoker.dart:247:5)
#25     Declarer.test.<anonymous closure>.<anonymous closure> (package:test_api/src/backend/declarer.dart:166:33)
#30     Declarer.test.<anonymous closure> (package:test_api/src/backend/declarer.dart:165:13)
<asynchronous suspension>
#31     Invoker._onRun.<anonymous closure>.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:test_api/src/backend/invoker.dart:400:25)
<asynchronous suspension>
#45     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:382:19)
#46     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:416:5)
#47     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:171:12)
(elided 28 frames from class _FakeAsync, package dart:async, package dart:async-patch, and package
stack_trace)

This was caught by the test expectation on the following line:
  file:///tmp/flutter%20sdk/packages/flutter/test/material/scaffold_test.dart line 765

The test description was:
Scaffold and extreme window padding
════════════════════════════════════════════════════════════════════════════════════════════════════
```

Bisected failing engine roll to the following commit: https://github.com/flutter/engine/commit/0b36d3e2f0235f25dc5b5657bd2e594fe7414aee

See flutter/engine#8545 for more details.

**Comment by dnfield** [comment]
`Rect.toString` drops precision to make the numbers more readable.  The actual values are more like

```
 Expected: Rect:<Rect.fromLTRB(36.0, 307.0, 113.0, 384.0)>
  Actual: Rect:<Rect.fromLTRB(35.99999999999999, 307.0, 113.0, 384.0)>
```

**Comment by Hixie** [comment]
The cleanest fix here is probably to figure out why we're getting errors accumulated and redo our math to avoid that. Failing that we can have a `rectMoreOrLessEquals` matcher, I guess.

Re the precision issue, see https://github.com/flutter/flutter/issues/1221

**Comment by HansMuller** [comment]
There's a clue in the fact that the loss of precision seems to be  nearly exclusively due to WidgetTester.getRect(someFloatingActionButton).
