### ISSUE TITLE
failed : flutter build apk --target-platform android-arm64

### ISSUE THREAD

**Issue by jianxia84** [flutter/flutter#31024]
Flutter crash report; please file at https://github.com/flutter/flutter/issues.

## command

flutter build apk --target-platform android-arm64

## exception

FileSystemException: FileSystemException: Deletion failed, path = 'D:\Program Files\flutter\bin\cache\artifacts\engine' (OS Error: 另一个程序正在使用此文件，进程无法访问。
, errno = 32)

```
#0      _Directory._deleteSync (dart:io/directory_impl.dart:206:7)
#1      FileSystemEntity.deleteSync (dart:io/file_system_entity.dart:466:47)
#2      ForwardingFileSystemEntity.deleteSync (package:file/src/forwarding/forwarding_file_system_entity.dart:72:16)
#3      CachedArtifact.update (package:flutter_tools/src/cache.dart:261:16)
<asynchronous suspension>
#4      Cache.updateAll (package:flutter_tools/src/cache.dart:219:26)
<asynchronous suspension>
#5      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:534:19)
<asynchronous suspension>
#6      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:486:33)
<asynchronous suspension>
#7      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:142:29)
<asynchronous suspension>
#8      _rootRun (dart:async/zone.dart:1124:13)
#9      _CustomZone.run (dart:async/zone.dart:1021:19)
#10     _runZoned (dart:async/zone.dart:1516:10)
#11     runZoned (dart:async/zone.dart:1463:12)
#12     AppContext.run (package:flutter_tools/src/base/context.dart:141:18)
<asynchronous suspension>
#13     FlutterCommand.run (package:flutter_tools/src/runner/flutter_command.dart:477:20)
#14     CommandRunner.runCommand (package:args/command_runner.dart:196:27)
<asynchronous suspension>
#15     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:396:21)
<asynchronous suspension>
#16     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:142:29)
<asynchronous suspension>
#17     _rootRun (dart:async/zone.dart:1124:13)
#18     _CustomZone.run (dart:async/zone.dart:1021:19)
#19     _runZoned (dart:async/zone.dart:1516:10)
#20     runZoned (dart:async/zone.dart:1463:12)
#21     AppContext.run (package:flutter_tools/src/base/context.dart:141:18)
<asynchronous suspension>
#22     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:356:19)
<asynchronous suspension>
#23     CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:111:29)
#24     new Future.sync (dart:async/future.dart:224:31)
#25     CommandRunner.run (package:args/command_runner.dart:111:11)
#26     FlutterCommandRunner.run (package:flutter_tools/src/runner/flutter_command_runner.dart:242:18)
#27     run.<anonymous closure> (package:flutter_tools/runner.dart:60:20)
<asynchronous suspension>
#28     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:142:29)
<asynchronous suspension>
#29     _rootRun (dart:async/zone.dart:1124:13)
#30     _CustomZone.run (dart:async/zone.dart:1021:19)
#31     _runZoned (dart:async/zone.dart:1516:10)
#32     runZoned (dart:async/zone.dart:1463:12)
#33     AppContext.run (package:flutter_tools/src/base/context.dart:141:18)
<asynchronous suspension>
#34     runInContext (package:flutter_tools/src/context_runner.dart:51:24)
<asynchronous suspension>
#35     run (package:flutter_tools/runner.dart:51:10)
#36     main (package:flutter_tools/executable.dart:59:9)
<asynchronous suspension>
#37     main (file:///D:/Program%20Files/flutter/packages/flutter_tools/bin/flutter_tools.dart:8:3)
#38     _startIsolate.<anonymous closure> (dart:isolate/runtime/lib/isolate_patch.dart:298:32)
#39     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/lib/isolate_patch.dart:171:12)
```

## flutter doctor

```
[32m[✓][39m Flutter (Channel dev, v1.3.10, on Microsoft Windows [Version 10.0.17134.706], locale zh-CN)
    [32m•[39m Flutter version 1.3.10 at D:\Program Files\flutter
    [32m•[39m Framework revision 4feefa3c9a (4 weeks ago), 2019-03-14 10:21:03 -0400
    [32m•[39m Engine revision 8b1a299ed5
    [32m•[39m Dart version 2.2.1 (build 2.2.1-dev.1.0 674fd0e060)

[32m[✓][39m Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    [32m•[39m Android SDK at D:\Android\sdk
    [32m•[39m Android NDK location not configured (optional; useful for native profiling support)
    [32m•[39m Platform android-28, build-tools 28.0.3
    [32m•[39m ANDROID_HOME = D:\Android\sdk
    [32m•[39m Java binary at: D:\Program Files\Android\Android Studio\jre\bin\java
    [32m•[39m Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)
    [32m•[39m All Android licenses accepted.

[32m[✓][39m Android Studio (version 3.3)
    [32m•[39m Android Studio at D:\Program Files\Android\Android Studio
    [32m•[39m Flutter plugin version 33.3.1
    [32m•[39m Dart plugin version 182.5215
    [32m•[39m Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)

[33m[!][39m IntelliJ IDEA Community Edition (version 2018.3)
    [32m•[39m IntelliJ at D:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2018.3.1
    [31m✗[39m Flutter plugin not installed; this adds Flutter specific functionality.
    [31m✗[39m Dart plugin not installed; this adds Dart specific functionality.
    [32m•[39m For information about installing plugins, see
      https://flutter.io/intellij-setup/#installing-the-plugins

[33m[!][39m Connected device
    [33m![39m No devices available

[33m![39m Doctor found issues in 2 categories.
```

**Comment by michaelg29** [comment]
Run this command in the terminal:
flutter clean
It will delete all existing files. This helps because the file is likely being used elsewhere.
And then rerun the command and it should work.

**Comment by christopherfujino** [comment]
@jianxia84 is your flutter install still in this state?

**Comment by jianxia84** [comment]
> @jianxia84 is your flutter install still in this state?

I upgraded the flutter version ，it's ok now

**Comment by christopherfujino** [comment]
@jianxia84 I'm glad your situation was resolved. Thanks for filing an issue!
