### ISSUE TITLE
Is this a typo? assert(transform.determinant != 0.0);

### ISSUE THREAD

**Issue by yczhangsjtu** [flutter/flutter#31045]
I found this line of code in flutter/lib/src/painting/matrix_utils.dart, line 166, commit: 27b058a41

```
assert(transform.determinant != 0.0);
```

I guess it is expected to be:

```
assert(transform.determinant() != 0.0);
```

However, if my guess is correct, there is another issue which causes this assertion to fail. Followed are the steps to reproduce

1. Replace `determinant` with `determinant()` as above;
2. Open project `flutter_gallery` in Android Studio;
3. Start running `main.dart` in Android simulator;
4. As the application is launched, tap 'Material -> Bottom app bar' to open the bottom app bar demo;
5. Tap 'None' radio in FAB shape, the Floating Action Button should disappear;
6. Tap 'Circular' or 'Diamond' radio in  FAB shape.

The console output looks as follows

```
Launching lib/main.dart on Android SDK built for x86 in debug mode...
Initializing gradle...
Resolving dependencies...
Running Gradle task 'assembleDebug'...
Built build/app/outputs/apk/debug/app-debug.apk.
Installing build/app/outputs/apk/app.apk...
Syncing files to device Android SDK built for x86...
D/EGL_emulation( 7685): eglMakeCurrent: 0xe74852a0: ver 3 0 (tinfo 0xe74832e0)
I/flutter ( 7685): ══╡ EXCEPTION CAUGHT BY RENDERING LIBRARY ╞═════════════════════════════════════════════════════════
I/flutter ( 7685): The following NoSuchMethodError was thrown during paint():
I/flutter ( 7685): The getter 'left' was called on null.
I/flutter ( 7685): Receiver: null
I/flutter ( 7685): Tried calling: left
I/flutter ( 7685): 
I/flutter ( 7685): When the exception was thrown, this was the stack:
I/flutter ( 7685): #0      Object.noSuchMethod (dart:core-patch/object_patch.dart:50:5)
I/flutter ( 7685): #1      Rect.overlaps (dart:ui/geometry.dart:771:24)
I/flutter ( 7685): #2      _DiamondNotchedRectangle.getOuterPath (package:flutter_gallery/demo/material/bottom_app_bar_demo.dart:459:15)
I/flutter ( 7685): #3      _BottomAppBarClipper.getClip (package:flutter/src/material/bottom_app_bar.dart:166:18)
I/flutter ( 7685): #4      _RenderCustomClip._updateClip (package:flutter/src/rendering/proxy_box.dart:1212:25)
I/flutter ( 7685): #5      RenderPhysicalShape.paint (package:flutter/src/rendering/proxy_box.dart:1780:7)
I/flutter ( 7685): #6      RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2104:7)
I/flutter ( 7685): #7      PaintingContext.paintChild (package:flutter/src/rendering/object.dart:173:13)
I/flutter ( 7685): #8      _RenderCustomMultiChildLayoutBox&RenderBox&ContainerRenderObjectMixin&RenderBoxContainerDefaultsMixin.defaultPaint (package:flutter/src/rendering/box.dart:2273:15)
I/flutter ( 7685): #9      RenderCustomMultiChildLayoutBox.paint (package:flutter/src/rendering/custom_layout.dart:361:5)
I/flutter ( 7685): #10     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2104:7)
I/flutter ( 7685): #11     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:173:13)
I/flutter ( 7685): #12     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:123:15)
I/flutter ( 7685): #13     _RenderInkFeatures.paint (package:flutter/src/material/material.dart:510:11)
I/flutter ( 7685): #14     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2104:7)
I/flutter ( 7685): #15     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:173:13)
I/flutter ( 7685): #16     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:123:15)
I/flutter ( 7685): #17     PaintingContext.pushLayer (package:flutter/src/rendering/object.dart:370:12)
I/flutter ( 7685): #18     RenderPhysicalModel.paint (package:flutter/src/rendering/proxy_box.dart:1716:15)
I/flutter ( 7685): #19     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2104:7)
I/flutter ( 7685): #20     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:173:13)
I/flutter ( 7685): #21     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:123:15)
I/flutter ( 7685): #22     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2104:7)
I/flutter ( 7685): #23     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:173:13)
I/flutter ( 7685): #24     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:123:15)
I/flutter ( 7685): #25     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2104:7)
I/flutter ( 7685): #26     PaintingContext._repaintCompositedChild (package:flutter/src/rendering/object.dart:128:11)
I/flutter ( 7685): #27     PaintingContext.repaintCompositedChild (package:flutter/src/rendering/object.dart:96:5)
I/flutter ( 7685): #28     PipelineOwner.flushPaint (package:flutter/src/rendering/object.dart:859:29)
I/flutter ( 7685): #29     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding.drawFrame (package:flutter/src/rendering/binding.dart:349:19)
I/flutter ( 7685): #30     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding&WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:701:13)
I/flutter ( 7685): #31     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:286:5)
I/flutter ( 7685): #32     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1012:15)
I/flutter ( 7685): #33     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:952:9)
I/flutter ( 7685): #34     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:864:5)
I/flutter ( 7685): #38     _invoke (dart:ui/hooks.dart:219:10)
I/flutter ( 7685): #39     _drawFrame (dart:ui/hooks.dart:178:3)
I/flutter ( 7685): (elided 3 frames from package dart:async)
I/flutter ( 7685): 
I/flutter ( 7685): The following RenderObject was being processed when the exception was fired:
I/flutter ( 7685):   RenderPhysicalShape#9225c relayoutBoundary=up1
I/flutter ( 7685):   creator: PhysicalShape ← BottomAppBar ← _DemoBottomAppBar ← MediaQuery ←
I/flutter ( 7685):   LayoutId-[<_ScaffoldSlot.bottomNavigationBar>] ← CustomMultiChildLayout ← AnimatedBuilder ←
I/flutter ( 7685):   DefaultTextStyle ← AnimatedDefaultTextStyle ← _InkFeatures-[GlobalKey#52319 ink renderer] ←
I/flutter ( 7685):   NotificationListener<LayoutChangedNotification> ← PhysicalModel ← ⋯
I/flutter ( 7685):   parentData: offset=Offset(0.0, 635.4); id=_ScaffoldSlot.bottomNavigationBar (can use size)
I/flutter ( 7685):   constraints: BoxConstraints(w=411.4, 0.0<=h<=683.4)
I/flutter ( 7685):   size: Size(411.4, 48.0)
I/flutter ( 7685):   elevation: 8.0
I/flutter ( 7685):   color: Color(0xffffffff)
I/flutter ( 7685):   shadowColor: Color(0xffffffff)
I/flutter ( 7685):   clipper: _BottomAppBarClipper
I/flutter ( 7685): This RenderObject had the following descendants (showing up to depth 5):
I/flutter ( 7685):   RenderCustomPaint#22f12 relayoutBoundary=up2
I/flutter ( 7685):     _RenderInkFeatures#b82a0 relayoutBoundary=up3
I/flutter ( 7685):       RenderPadding#39bef relayoutBoundary=up4
I/flutter ( 7685):         RenderFlex#40c20 relayoutBoundary=up5
I/flutter ( 7685):           RenderSemanticsGestureHandler#24e16 relayoutBoundary=up6
I/flutter ( 7685):           RenderSemanticsGestureHandler#cdda6 relayoutBoundary=up6
I/flutter ( 7685):           RenderSemanticsGestureHandler#26a78 relayoutBoundary=up6
I/flutter ( 7685): ════════════════════════════════════════════════════════════════════════════════════════════════════
I/flutter ( 7685): Another exception was thrown: 'package:flutter/src/painting/matrix_utils.dart': Failed assertion: line 166 pos 12: 'transform.determinant() != 0.0': is not true.
I/flutter ( 7685): Another exception was thrown: NoSuchMethodError: The getter 'left' was called on null.
I/flutter ( 7685): Another exception was thrown: 'package:flutter/src/painting/matrix_utils.dart': Failed assertion: line 166 pos 12: 'transform.determinant() != 0.0': is not true.
Application finished.
```

**Comment by jonahwilliams** [comment]
This is definitely a bug, thank you for finding it!

**Comment by zoeyfan** [comment]
@jonahwilliams , looking at the PR associated with this bug, may I assume this has been fixed?

**Comment by jonahwilliams** [comment]
Yes, it ended up being cleaned up in a different pr: https://github.com/flutter/flutter/pull/31568
