### ISSUE TITLE
Testing buttons using tester.tap to show a dialog gives Framework Error

### ISSUE THREAD

**Issue by Tricky12321** [flutter/flutter#31049]
## Steps to Reproduce
1. Have a method open an AlertDialog
2. Have a button execute the method 
3. In a test, use `await tester.tap(find.byKey(const Key('LoginBtnKey')));` to tap the button
4. Then verify that the dialog is shown using `expect(find.byType(AlertDialog), findsOneWidget);`
This gives a framework error.

## Logs

```
══╡ EXCEPTION CAUGHT BY GESTURE ╞═══════════════════════════════════════════════════════════════════
The following assertion was thrown while handling a gesture:
'package:flutter/src/widgets/localizations.dart': Failed assertion: line 446 pos 12: 'context !=
null': is not true.

Either the assertion indicates an error in the framework itself, or we should provide substantially
more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=BUG.md

When the exception was thrown, this was the stack:
#2      Localizations.of (package:flutter/src/widgets/localizations.dart:446:12)
#3      debugCheckHasMaterialLocalizations.<anonymous closure> (package:flutter/src/material/debug.dart:88:23)
#4      debugCheckHasMaterialLocalizations (package:flutter/src/material/debug.dart:127:4)
#5      showDialog (package:flutter/src/material/dialog.dart:701:10)
```

```
Analyzing weekplanner...                                                
No issues found! (ran in 6.1s; 157 public members lack documentation)
```

```
[✓] Flutter (Channel stable, v1.2.1, on Mac OS X 10.14.4 18E226, locale da-DK)
    • Flutter version 1.2.1 at /Users/Tricky/development/flutter
    • Framework revision 8661d8aecd (8 weeks ago), 2019-02-14 19:19:53 -0800
    • Engine revision 3757390fa4
    • Dart version 2.1.2 (build 2.1.2-dev.0.0 0a7dcf17eb)

[!] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/Tricky/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)
    ✗ Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses

[✓] iOS toolchain - develop for iOS devices (Xcode 10.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.2, Build version 10E125
    • ios-deploy 1.9.4
    • CocoaPods version 1.6.1

[✓] Android Studio (version 3.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 33.3.1
    • Dart plugin version 182.5215
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)

[✓] IntelliJ IDEA Community Edition (version 2018.3.5)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 33.3.2
    • Dart plugin version 183.5912.23

[!] VS Code (version 1.29.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    ✗ Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[!] Connected device
    ! No devices available

! Doctor found issues in 3 categories.
```

**Comment by analistacarlosh** [comment]
I'm looking for the same resolutions.

**Comment by TahaTesser** [comment]
Hi @Tricky12321 
Are you still experiencing this issue latest dev channel?
If yes,  can you please provide your `flutter doctor -v` and `flutter run --verbose`? 
Also, to better address the issue, would be helpful if you could post a minimal code sample to reproduce the problem
Thank you

**Comment by iapicca** [comment]
Without additional information we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
