### ISSUE TITLE
My flutter app once loaded on ios device and not able to watch continuous and hot reload

### ISSUE THREAD

**Issue by ParasShahh** [flutter/flutter#31052]
Flutter crash report; please file at https://github.com/flutter/flutter/issues.

## command

flutter run

## exception

ArgumentError: Invalid argument(s): Cannot find executable for null.

```
#0      _getExecutable (package:process/src/interface/local_process_manager.dart:113:5)
#1      LocalProcessManager.start (package:process/src/interface/local_process_manager.dart:41:7)
#2      runCommand (package:flutter_tools/src/base/process.dart:116:25)
#3      _IOSDevicePortForwarder.forward (package:flutter_tools/src/ios/devices.dart:565:23)
<asynchronous suspension>
#4      ProtocolDiscovery._forwardPort (package:flutter_tools/src/protocol_discovery.dart:89:54)
<asynchronous suspension>
#5      ProtocolDiscovery._handleLine (package:flutter_tools/src/protocol_discovery.dart:78:27)
#6      _rootRunUnary (dart:async/zone.dart:1132:38)
#7      _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#8      _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
#9      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#10     _DelayedData.perform (dart:async/stream_impl.dart:591:14)
#11     _StreamImplEvents.handleNext (dart:async/stream_impl.dart:707:11)
#12     _PendingEvents.schedule.<anonymous closure> (dart:async/stream_impl.dart:667:7)
#13     _rootRun (dart:async/zone.dart:1124:13)
#14     _CustomZone.run (dart:async/zone.dart:1021:19)
#15     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:947:23)
#16     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#17     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#18     _runPendingImmediateCallback (dart:isolate/runtime/libisolate_patch.dart:115:13)
#19     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:172:5)
```

## flutter doctor

```
[32m[✓][39m Flutter (Channel stable, v1.2.1, on Mac OS X 10.14 18A391, locale en-GB)
    [32m•[39m Flutter version 1.2.1 at /Users/parassmacmin/Documents/flutter
    [32m•[39m Framework revision 8661d8aecd (8 weeks ago), 2019-02-14 19:19:53 -0800
    [32m•[39m Engine revision 3757390fa4
    [32m•[39m Dart version 2.1.2 (build 2.1.2-dev.0.0 0a7dcf17eb)

[32m[✓][39m Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    [32m•[39m Android SDK at /usr/local/share/android-sdk
    [32m•[39m Android NDK location not configured (optional; useful for native profiling support)
    [32m•[39m Platform android-28, build-tools 28.0.3
    [32m•[39m ANDROID_HOME = /usr/local/share/android-sdk
    [32m•[39m Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    [32m•[39m Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)
    [32m•[39m All Android licenses accepted.

[32m[✓][39m iOS toolchain - develop for iOS devices (Xcode 10.1)
    [32m•[39m Xcode at /Applications/Xcode.app/Contents/Developer
    [32m•[39m Xcode 10.1, Build version 10B61
    [32m•[39m ios-deploy 1.9.4
    [32m•[39m CocoaPods version 1.5.3

[32m[✓][39m Android Studio (version 3.2)
    [32m•[39m Android Studio at /Applications/Android Studio.app/Contents
    [32m•[39m Flutter plugin version 31.3.1
    [32m•[39m Dart plugin version 181.5656
    [32m•[39m Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)

[32m[✓][39m VS Code (version 1.33.0)
    [32m•[39m VS Code at /Applications/Visual Studio Code.app/Contents
    [32m•[39m Flutter extension version 2.25.0

[32m[✓][39m Connected device (1 available)
    [32m•[39m EWW iPhone • 313dca23570e33afe2f45885d20158e8cf953f8e • ios • iOS 12.1.2

[32m•[39m No issues found!
```

**Comment by jmagman** [comment]
_iproxyPath was null, `which` couldn't find it.  This was resolved with https://github.com/flutter/flutter/pull/34669.
