### ISSUE TITLE
SliverList with ListView Axis.horizontal

### ISSUE THREAD

**Issue by samuelg123** [flutter/flutter#31075]
Hi, I'm new in flutter. I found strange behavior. I want to use SliverList with ListView scrollDirection : Axis.horizontal. But it not works and throws an exception. 

I also tested : 
- ListView with scrollDirection : Axis.vertical. (Works)
- ListView with fixed height using Container. (Works)

## Steps to Reproduce

[main.dart](https://gist.github.com/samuelg123/77e740b858a7bd007f0a2eba3f5e47c2)

```
Scaffold(
      body: CustomScrollView(
        slivers: <Widget>[
          SliverAppBar(
            title: Text("Test App"),
            pinned: true,
          ),
          SliverList(
            delegate: SliverChildListDelegate(
              <Widget>[
                Column(
                  mainAxisSize: MainAxisSize.min,
                  children: <Widget>[
                    Flexible(
                      child: ListView(
                        shrinkWrap: true,
                        scrollDirection: Axis.horizontal, //Axis.vertical = Working
                        children: <Widget>[
                          Text('OK 1'),
                          Text('OK 2'),
                          Text('OK 3'),
                          Text('OK 4'),
                        ],
                      ),
                    ),
                  ],
                ),
              ],
            ),
          ),
        ],
      ),
    );
```

## Logs

```
[ +559 ms] I/flutter (28066): ══╡ EXCEPTION CAUGHT BY RENDERING LIBRARY ╞═════════════════════════════════════════════════════════
[  +12 ms] I/flutter (28066): The following assertion was thrown during performLayout():
[        ] I/flutter (28066): 'package:flutter/src/rendering/viewport.dart': Failed assertion: line 1604 pos 16:
[        ] I/flutter (28066): 'constraints.hasBoundedHeight': is not true.


[        ] I/flutter (28066): When the exception was thrown, this was the stack:
[  +28 ms] I/flutter (28066): #2      RenderShrinkWrappingViewport.performLayout (package:flutter/src/rendering/viewport.dart:1604:16)
[   +1 ms] I/flutter (28066): #3      RenderObject.layout (package:flutter/src/rendering/object.dart:1632:7)
[   +9 ms] I/flutter (28066): #4      _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
[   +1 ms] I/flutter (28066): #5      RenderObject.layout (package:flutter/src/rendering/object.dart:1632:7)
[        ] I/flutter (28066): #6      _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
```

```
flutter analyze
Analyzing flutter_list_test...
No issues found! (ran in 3.1s)
```

```
[√] Flutter (Channel stable, v1.2.1, on Microsoft Windows [Version 10.0.17134.706], locale en-US)
    • Flutter version 1.2.1 at C:\Android\flutter
    • Framework revision 8661d8aecd (9 weeks ago), 2019-02-14 19:19:53 -0800
    • Engine revision 3757390fa4
    • Dart version 2.1.2 (build 2.1.2-dev.0.0 0a7dcf17eb)

[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at C:\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)
    • All Android licenses accepted.

[√] Android Studio (version 3.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 34.0.1
    • Dart plugin version 182.5215
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)

• No issues found!
```

**Comment by panmin** [comment]
the same problem, have you resolve it?

**Comment by samuelg123** [comment]
@panmin Not really. I think the main problem is in ListView. It needs a predefined height. So if you need temporary fix, just replace Flexible to SizedBox (height: 100, child: ListView(), )

I've tested on latest stable version (1.7.8+hotfix.4) and it still not working.

```I/flutter (18423): Another exception was thrown: 'package:flutter/src/rendering/sliver_multi_box_adaptor.dart': Failed assertion: line 549 pos 12: 'child.hasSize': is not true.```

**Comment by escamoteur** [comment]
I think you could use `IntrinsicHeight` here (not tested) but @samuelg123 is right, the row has an undefined height so you have to give it some constrains.

Please ask questions like this on stackoverflow because we are not able to give individual support here.
