### ISSUE TITLE
java.lang.NoClassDefFoundError: com.google.firebase.FirebaseApp

### ISSUE THREAD

**Issue by samycodes** [flutter/flutter#31123]
## Steps to Reproduce
I have an application with Flutter. It works really fine, but the app crashes on API level 18 and 19.
When I try to run test the apk in Test Lab, it show me error on API level 18 and 19

## Logs

```
 Fatal exception
	at com.google.firebase.provider.FirebaseInitProvider.onCreate(com.google.firebase:firebase-common@@16.0.2:53)
FATAL EXCEPTION: main
java.lang.NoClassDefFoundError: com.google.firebase.FirebaseApp
	at com.google.firebase.provider.FirebaseInitProvider.onCreate(com.google.firebase:firebase-common@@16.0.2:53)
	at android.content.ContentProvider.attachInfo(ContentProvider.java:1214)
	at android.content.ContentProvider.attachInfo(ContentProvider.java:1189)
	at com.google.firebase.provider.FirebaseInitProvider.attachInfo(com.google.firebase:firebase-common@@16.0.2:47)
	at android.app.ActivityThread.installProvider(ActivityThread.java:5119)
	at android.app.ActivityThread.installContentProviders(ActivityThread.java:4725)
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4665)
	at android.app.ActivityThread.access$1400(ActivityThread.java:159)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1376)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:176)
	at android.app.ActivityThread.main(ActivityThread.java:5419)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:525)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1046)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:862)
	at dalvik.system.NativeStart.main(Native Method)
```

## gradle.build

```
def localProperties = new Properties()
def localPropertiesFile = rootProject.file('local.properties')
if (localPropertiesFile.exists()) {
    localPropertiesFile.withReader('UTF-8') { reader ->
        localProperties.load(reader)
    }
}

def flutterRoot = localProperties.getProperty('flutter.sdk')
if (flutterRoot == null) {
    throw new GradleException("Flutter SDK not found. Define location with flutter.sdk in the local.properties file.")
}

def flutterVersionCode = localProperties.getProperty('flutter.versionCode')
if (flutterVersionCode == null) {
    flutterVersionCode = '1'
}

def flutterVersionName = localProperties.getProperty('flutter.versionName')
if (flutterVersionName == null) {
    flutterVersionName = '1.0'
}

apply plugin: 'com.android.application'
apply from: "$flutterRoot/packages/flutter_tools/gradle/flutter.gradle"

repositories {
    mavenCentral()
    maven { url 'https://mapbox.bintray.com/mapbox' }
}

def keystoreProperties = new Properties()
def keystorePropertiesFile = rootProject.file('key.properties')
if (keystorePropertiesFile.exists()) {
    keystoreProperties.load(new FileInputStream(keystorePropertiesFile))
}

android {
    compileSdkVersion 28
    lintOptions {
        disable 'InvalidPackage'
    }
    defaultConfig {
        // TODO: Specify your own unique Application ID (https://developer.android.com/studio/build/application-id.html).
        applicationId "com.tripmate.myapp"
        minSdkVersion 16
        targetSdkVersion 27
        versionCode flutterVersionCode.toInteger()
        versionName flutterVersionName
        testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"
        multiDexEnabled true
        ndk {
        abiFilters 'armeabi-v7a'
        }

    }
    signingConfigs {
        release {
            keyAlias keystoreProperties['keyAlias']
            keyPassword keystoreProperties['keyPassword']
            storeFile file(keystoreProperties['storeFile'])
            storePassword keystoreProperties['storePassword']
        }
    }
    buildTypes {
        release {
            signingConfig signingConfigs.release
        }
    }
    buildToolsVersion '28.0.3'
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
}

flutter {
    source '../..'
}

dependencies {
    implementation 'android.arch.core:runtime:1.1.1'
    implementation 'com.android.support:multidex:1.0.0'
    implementation 'com.android.support.constraint:constraint-layout:1.1.3'
    testImplementation 'junit:junit:4.12'
    androidTestImplementation 'com.android.support.test:runner:1.0.2'
    androidTestImplementation 'com.android.support.test.espresso:espresso-core:3.0.2'
    implementation 'com.google.firebase:firebase-core:16.0.7'
    //Maps Box Maps SDK
    implementation 'com.mapbox.mapboxsdk:mapbox-android-sdk:7.1.2'
    //Permission management API
    implementation 'com.google.android.gms:play-services-maps:16.1.0'
    //Google play services
    implementation 'com.google.android.gms:play-services-location:16.0.0'
    //Bubble Layout
    implementation 'com.daasuu:BubbleLayout:1.2.0'
    //Mapbox navigation
    implementation 'com.mapbox.mapboxsdk:mapbox-android-navigation-ui:0.30.0'
    //Mapbox Annotation Plugin
    implementation 'com.mapbox.mapboxsdk:mapbox-android-plugin-annotation-v7:0.5.0'
    implementation 'com.android.support:design:1.0.0'

}

configurations.all {
    resolutionStrategy {
        force 'com.android.support:support-v4:27.1.0'
    }
}

apply plugin: 'com.google.gms.google-services'
apply plugin: 'io.fabric'

```

Can anyone help me with this?

**Comment by kroikie** [comment]
@samycodes

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/1132. Any further collaboration will be done there.

**Comment by gofur** [comment]
i have same problem
`FATAL EXCEPTION: main
java.lang.NoClassDefFoundError: com.google.firebase.FirebaseApp
	at com.google.firebase.provider.FirebaseInitProvider.onCreate(com.google.firebase:firebase-common@@17.1.0:53)
	at android.content.ContentProvider.attachInfo(ContentProvider.java:1214)
	at android.content.ContentProvider.attachInfo(ContentProvider.java:1189)
	at com.google.firebase.provider.FirebaseInitProvider.attachInfo(com.google.firebase:firebase-common@@17.1.0:47)
	at android.app.ActivityThread.installProvider(ActivityThread.java:5119)
	at android.app.ActivityThread.installContentProviders(ActivityThread.java:4725)
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4665)
	at android.app.ActivityThread.access$1400(ActivityThread.java:159)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1376)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:176)
	at android.app.ActivityThread.main(ActivityThread.java:5419)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:525)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1046)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:862)
	at dalvik.system.NativeStart.main(Native Method)`

Device: Samsung Galaxy S3 
OS : Android 4.3

anyone can help?

**Comment by diegobarle** [comment]
> @samycodes
> 
> This issue has been moved to [FirebaseExtended/flutterfire#1132](https://github.com/FirebaseExtended/flutterfire/issues/1132). Any further collaboration will be done there.

It says the issue has been moved here, which has been closed because it can be resolved by following [this answer](https://github.com/flutter/flutter/issues/40759#issuecomment-533499874) however I have I have already done this and the java.lang.NoClassDefFoundError: com.google.firebase.FirebaseApp is still happening

`FATAL EXCEPTION: main
java.lang.NoClassDefFoundError: com.google.firebase.FirebaseApp
	at com.google.firebase.provider.FirebaseInitProvider.onCreate(FirebaseInitProvider.java:51)
	at android.content.ContentProvider.attachInfo(ContentProvider.java:1214)
	at android.content.ContentProvider.attachInfo(ContentProvider.java:1189)
	at com.google.firebase.provider.FirebaseInitProvider.attachInfo(FirebaseInitProvider.java:45)
	at android.app.ActivityThread.installProvider(ActivityThread.java:5119)
	at android.app.ActivityThread.installContentProviders(ActivityThread.java:4725)
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4665)
	at android.app.ActivityThread.access$1400(ActivityThread.java:159)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1376)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:176)
	at android.app.ActivityThread.main(ActivityThread.java:5419)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:525)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1046)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:862)
	at dalvik.system.NativeStart.main(Native Method)`

Any ideas? I cannot find a solution to this anywhere..
