### ISSUE TITLE
Flutter Line chart intermittent rendering issue

### ISSUE THREAD

**Issue by 2intor** [flutter/flutter#31126]
Same Problem. I hope someone is looking into it. It has been showstopper for us.

Please check below full error trace.
```
I/flutter (25291): ══╡ EXCEPTION CAUGHT BY RENDERING LIBRARY ╞═════════════════════════════════════════════════════════
I/flutter (25291): The following assertion was thrown during paint():
I/flutter (25291): 'package:charts_common/src/chart/layout/layout_manager_impl.dart': Failed assertion: line 115 pos
I/flutter (25291): 12: '_drawAreaBoundsOutdated == false': is not true.
I/flutter (25291): 
I/flutter (25291): Either the assertion indicates an error in the framework itself, or we should provide substantially
I/flutter (25291): more information in this error message to help you determine and fix the underlying cause.
I/flutter (25291): In either case, please report this assertion by filing a bug on GitHub:
I/flutter (25291):   https://github.com/flutter/flutter/issues/new?template=BUG.md
I/flutter (25291): 
I/flutter (25291): When the exception was thrown, this was the stack:
I/flutter (25291): #2      LayoutManagerImpl.drawableLayoutAreaBounds (package:charts_common/src/chart/layout/layout_manager_impl.dart:115:12)
I/flutter (25291): #3      BaseChart.drawableLayoutAreaBounds (package:charts_common/src/chart/common/base_chart.dart:414:22)
I/flutter (25291): #4      _LinePointLayoutView.paint (package:charts_common/src/chart/common/behavior/line_point_highlighter.dart:418:30)
I/flutter (25291): #5      BaseChart.paint.<anonymous closure> (package:charts_common/src/chart/common/base_chart.dart:579:12)
I/flutter (25291): #6      List.forEach (dart:core/runtime/libgrowable_array.dart:278:8)
I/flutter (25291): #7      BaseChart.paint (package:charts_common/src/chart/common/base_chart.dart:577:38)
I/flutter (25291): #8      ChartContainerCustomPaint.paint (package:charts_flutter/src/chart_container.dart:381:11)
I/flutter (25291): #9      RenderCustomPaint._paintWithPainter (package:flutter/src/rendering/custom_paint.dart:521:13)
I/flutter (25291): #10     RenderCustomPaint.paint (package:flutter/src/rendering/custom_paint.dart:559:7)
I/flutter (25291): #11     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2092:7)
I/flutter (25291): #12     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:173:13)
I/flutter (25291): #13     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:123:15)
I/flutter (25291): #14     RenderPointerListener.paint (package:flutter/src/rendering/proxy_box.dart:2629:11)
I/flutter (25291): #15     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2092:7)
I/flutter (25291): #16     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:173:13)
I/flutter (25291): #17     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:123:15)
I/flutter (25291): #18     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2092:7)
I/flutter (25291): #19     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:173:13)
I/flutter (25291): #20     _RenderCustomMultiChildLayoutBox&RenderBox&ContainerRenderObjectMixin&RenderBoxContainerDefaultsMixin.defaultPaint (package:flutter/src/rendering/box.dart:2273:15)
I/flutter (25291): #21     RenderCustomMultiChildLayoutBox.paint (package:flutter/src/rendering/custom_layout.dart:361:5)
I/flutter (25291): #22     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2092:7)
I/flutter (25291): #23     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:173:13)
I/flutter (25291): #24     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:123:15)
I/flutter (25291): #25     RenderDecoratedBox.paint (package:flutter/src/rendering/proxy_box.dart:1987:11)
I/flutter (25291): #26     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2092:7)
I/flutter (25291): #27     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:173:13)
I/flutter (25291): #28     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:123:15)
I/flutter (25291): #29     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2092:7)
I/flutter (25291): #30     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:173:13)
I/flutter (25291): #31     _RenderFlex&RenderBox&ContainerRenderObjectMixin&RenderBoxContainerDefaultsMixin.defaultPaint (package:flutter/src/rendering/box.dart:2273:15)
I/flutter (25291): #32     RenderFlex.paint (package:flutter/src/rendering/flex.dart:931:7)
I/flutter (25291): #33     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2092:7)
I/flutter (25291): #34     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:173:13)
I/flutter (25291): #35     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:123:15)
I/flutter (25291): #36     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2092:7)
I/flutter (25291): #37     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:173:13)
I/flutter (25291): #38     _RenderFlex&RenderBox&ContainerRenderObjectMixin&RenderBoxContainerDefaultsMixin.defaultPaint (package:flutter/src/rendering/box.dart:2273:15)
I/flutter (25291): #39     RenderFlex.paint (package:flutter/src/rendering/flex.dart:931:7)
I/flutter (25291): #40     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2092:7)
I/flutter (25291): #41     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:173:13)
I/flutter (25291): #42     _RenderSingleChildViewport.paint.paintContents (package:flutter/src/widgets/single_child_scroll_view.dart:522:17)
I/flutter (25291): #43     PaintingContext.pushLayer (package:flutter/src/rendering/object.dart:370:12)
I/flutter (25291): #44     PaintingContext.pushClipRect (package:flutter/src/rendering/object.dart:394:7)
I/flutter (25291): #45     _RenderSingleChildViewport.paint (package:flutter/src/widgets/single_child_scroll_view.dart:526:17)
I/flutter (25291): #46     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2092:7)
I/flutter (25291): #47     PaintingContext._repaintCompositedChild (package:flutter/src/rendering/object.dart:128:11)
I/flutter (25291): #48     PaintingContext.repaintCompositedChild (package:flutter/src/rendering/object.dart:96:5)
I/flutter (25291): #49     PipelineOwner.flushPaint (package:flutter/src/rendering/object.dart:853:29)
I/flutter (25291): #50     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding.drawFrame (package:flutter/src/rendering/binding.dart:331:19)
I/flutter (25291): #51     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding&WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:701:13)
I/flutter (25291): #52     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:268:5)
I/flutter (25291): #53     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:988:15)
I/flutter (25291): #54     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:928:9)
I/flutter (25291): #55     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:840:5)
I/flutter (25291): #59     _invoke (dart:ui/hooks.dart:209:10)
I/flutter (25291): #60     _drawFrame (dart:ui/hooks.dart:168:3)
I/flutter (25291): (elided 5 frames from class _AssertionError and package dart:async)
I/flutter (25291): 
I/flutter (25291): The following RenderObject was being processed when the exception was fired:
I/flutter (25291):   ChartContainerRenderObject<num>#e456d
I/flutter (25291):   creator: ChartContainer<num> ← Listener ← _GestureSemantics ← RawGestureDetector ← GestureDetector
I/flutter (25291):   ← LayoutId-[<chartContainer>] ← CustomMultiChildLayout ← LineChart ← DecoratedBox ← ConstrainedBox
I/flutter (25291):   ← Container ← Column ← ⋯
I/flutter (25291):   parentData: <none> (can use size)
I/flutter (25291):   constraints: BoxConstraints(w=360.0, h=200.0)
I/flutter (25291):   semantic boundary
I/flutter (25291):   size: Size(360.0, 200.0)
I/flutter (25291): This RenderObject has no descendants.
I/flutter (25291): ════════════════════════════════════════════════════════════════════════════════════════════════════
I/flutter (25291): Another exception was thrown: 'package:charts_common/src/chart/layout/layout_manager_impl.dart': Failed assertion: line 115 pos 12: '_drawAreaBoundsOutdated == false': is not true.
E
```

**Comment by BondarenkoStas** [comment]
@2intor did you manage to fix it?

**Comment by iapicca** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
  
Thanks for your contribution.
