### ISSUE TITLE
FileSystemException: FileSystemException: Cannot open file, path = 'app_dir\.flutter-plugins' (OS Error: Access is denied. , errno = 5)

### ISSUE THREAD

**Issue by TesfahunK** [flutter/flutter#31135]
Im setting flutter on a new Laptop and this is all i am getting, any Solution, im using windows 10(1809)

Flutter crash report; please file at https://github.com/flutter/flutter/issues.

## command

flutter run --machine -t lib\main.dart -d accf85a0a93c --track-widget-creation --start-paused

## exception

FileSystemException: FileSystemException: Cannot open file, path = 'D:\Pomp\shoa\propapp\.flutter-plugins' (OS Error: Access is denied.
, errno = 5)

```
#0      _File.throwIfError (dart:io/file_impl.dart:643:7)
#1      _File.openSync (dart:io/file_impl.dart:487:5)
#2      _File.writeAsBytesSync (dart:io/file_impl.dart:612:31)
#3      _File.writeAsStringSync (dart:io/file_impl.dart:636:5)
#4      _LocalFile&LocalFileSystemEntity&ForwardingFile.writeAsStringSync (package:file/src/forwarding/forwarding_file.dart:147:16)
#5      _writeFlutterPluginsList (package:flutter_tools/src/plugins.dart:99:17)
#6      refreshPluginsList (package:flutter_tools/src/plugins.dart:288:24)
#7      FlutterProject.ensureReadyForPlatformSpecificTooling (package:flutter_tools/src/project.dart:143:5)
<asynchronous suspension>
#8      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:535:21)
<asynchronous suspension>
#9      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:482:33)
<asynchronous suspension>
#10     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:142:29)
<asynchronous suspension>
#11     _rootRun (dart:async/zone.dart:1124:13)
#12     _CustomZone.run (dart:async/zone.dart:1021:19)
#13     _runZoned (dart:async/zone.dart:1516:10)
#14     runZoned (dart:async/zone.dart:1463:12)
#15     AppContext.run (package:flutter_tools/src/base/context.dart:141:18)
<asynchronous suspension>
#16     FlutterCommand.run (package:flutter_tools/src/runner/flutter_command.dart:473:20)
#17     CommandRunner.runCommand (package:args/command_runner.dart:196:27)
<asynchronous suspension>
#18     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:396:21)
<asynchronous suspension>
#19     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:142:29)
<asynchronous suspension>
#20     _rootRun (dart:async/zone.dart:1124:13)
#21     _CustomZone.run (dart:async/zone.dart:1021:19)
#22     _runZoned (dart:async/zone.dart:1516:10)
#23     runZoned (dart:async/zone.dart:1463:12)
#24     AppContext.run (package:flutter_tools/src/base/context.dart:141:18)
<asynchronous suspension>
#25     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:356:19)
<asynchronous suspension>
#26     CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:111:29)
#27     new Future.sync (dart:async/future.dart:224:31)
#28     CommandRunner.run (package:args/command_runner.dart:111:11)
#29     FlutterCommandRunner.run (package:flutter_tools/src/runner/flutter_command_runner.dart:242:18)
#30     run.<anonymous closure> (package:flutter_tools/runner.dart:60:20)
<asynchronous suspension>
#31     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:142:29)
<asynchronous suspension>
#32     _rootRun (dart:async/zone.dart:1124:13)
#33     _CustomZone.run (dart:async/zone.dart:1021:19)
#34     _runZoned (dart:async/zone.dart:1516:10)
#35     runZoned (dart:async/zone.dart:1463:12)
#36     AppContext.run (package:flutter_tools/src/base/context.dart:141:18)
<asynchronous suspension>
#37     runInContext (package:flutter_tools/src/context_runner.dart:48:24)
<asynchronous suspension>
#38     run (package:flutter_tools/runner.dart:51:10)
#39     main (package:flutter_tools/executable.dart:52:9)
<asynchronous suspension>
#40     main (file:///E:/b/rr/tmpdrhwmy/w/archive/flutter/packages/flutter_tools/bin/flutter_tools.dart:8:3)
#41     _startIsolate.<anonymous closure> (dart:isolate/runtime/libisolate_patch.dart:298:32)
#42     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:171:12)
```

## flutter doctor

```
[✓] Flutter (Channel stable, v1.2.1, on Microsoft Windows [Version 10.0.17763.437], locale en-US)
    • Flutter version 1.2.1 at C:\flutter
    • Framework revision 8661d8aecd (9 weeks ago), 2019-02-14 19:19:53 -0800
    • Engine revision 3757390fa4
    • Dart version 2.1.2 (build 2.1.2-dev.0.0 0a7dcf17eb)

[!] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at C:\Users\Pomp\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses

[✓] Android Studio (version 3.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 33.4.1
    • Dart plugin version 182.5215
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)

[✓] VS Code (version 1.33.1)
    • VS Code at C:\Users\Pomp\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 2.25.0

[✓] Connected device (1 available)
    • G630 U10 • accf85a0a93c • android-arm • Android 4.3 (API 18)

! Doctor found issues in 1 category.
```

**Comment by H03in** [comment]
just remove .flutter-plugins file inside project folder.

**Comment by kf6gpe** [comment]
@TesfahunK , did that work for you?

**Comment by beingbsal** [comment]
> just remove .flutter-plugins file inside project folder.

Excuse me sir, What should we do for this?
FileSystemException: FileSystemException: Cannot open file, path = 'D:\Flutter\flutter\bin\cache\artifacts\engine\windows-x64\flutter_tester.exe' (OS Error: Access is denied.
, errno = 5

**Comment by MuhamadJalal** [comment]
I face the same issue, And solved by:
1- remove the following files 
                projectDir/.packages 
                projectDir/.flutter-plugins
                projectDir/.flutter-plugins-dependencies.
2- run command  **### flutter pub get** to create new projectDir/.packages file.
3- run command **### flutter packages get** to create the others files

Hope this help,
