### ISSUE TITLE
App crashes on startup (UnsatisfiedLinkError)

### ISSUE THREAD

**Issue by signshah** [flutter/flutter#31162]
## Steps to Reproduce
I have below dependencies in my yaml file.

> cupertino_icons: ^0.1.2
  firebase_auth: ^0.8.4+2
  cloud_firestore: ^0.9.13+1
  firebase_messaging: ^4.0.0+2
  firebase_storage: ^2.1.0+1
  firebase_core: ^0.3.4
  intl_translation: ^0.17.3
  http: ^0.12.0+1
  xml: ^3.3.1
  uuid: ^2.0.0
  shared_preferences: ^0.5.2
  flutter_staggered_grid_view: ^0.2.7
  google_sign_in: ^4.0.1+3
  flutter_facebook_login: ^2.0.0
  flutter_signin_button: ^0.2.8
  image_picker: ^0.5.3+1
  mlkit: ^0.10.1
  path_provider: ^0.5.0+1
  cached_network_image: ^0.7.0
  permission_handler: ^3.0.0
  url_launcher: ^5.0.2
  firebase_admob: ^0.8.0+3
  flutter_inapp_purchase: ^0.9.2
  share: ^0.6.1

Below are is my **app/build.gradle**.

> 
		def localProperties = new Properties()
		def localPropertiesFile = rootProject.file('local.properties')
		if (localPropertiesFile.exists()) {
			localPropertiesFile.withReader('UTF-8') { reader ->
				localProperties.load(reader)
			}
		}

		def flutterRoot = localProperties.getProperty('flutter.sdk')
		if (flutterRoot == null) {
			throw new GradleException("Flutter SDK not found. Define location with flutter.sdk in the local.properties file.")
		}

		def flutterVersionCode = localProperties.getProperty('flutter.versionCode')
		if (flutterVersionCode == null) {
			flutterVersionCode = '1'
		}

		def flutterVersionName = localProperties.getProperty('flutter.versionName')
		if (flutterVersionName == null) {
			flutterVersionName = '1.0'
		}

		apply plugin: 'com.android.application'
		apply from: "$flutterRoot/packages/flutter_tools/gradle/flutter.gradle"

		def keystoreProperties = new Properties()
		def keystorePropertiesFile = rootProject.file('key.properties')
		if (keystorePropertiesFile.exists()) {
			keystoreProperties.load(new FileInputStream(keystorePropertiesFile))
		}

		android {
			compileSdkVersion 28

			lintOptions {
				disable 'InvalidPackage'
			}

			defaultConfig {
				applicationId "abc.xyz.myapp"
				minSdkVersion 21
				targetSdkVersion 28
				multiDexEnabled true
				versionCode 5
				versionName flutterVersionName
				testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
				ndk.abiFilters 'armeabi-v7a', 'arm64-v8a'
				
			}

			signingConfigs {
				release {
					keyAlias keystoreProperties['keyAlias']
					keyPassword keystoreProperties['keyPassword']
					storeFile file(keystoreProperties['storeFile'])
					storePassword keystoreProperties['storePassword']
				}
			}

			buildTypes {
				release {
					signingConfig signingConfigs.release
				   
				}
			}
		}

		flutter {
			source '../..'
		}

		dependencies {
			testImplementation 'junit:junit:4.12'
			androidTestImplementation 'androidx.test:runner:1.1.1'
			androidTestImplementation 'androidx.test.espresso:espresso-core:3.1.1'
			implementation 'com.google.firebase:firebase-core:16.0.8'
			implementation 'androidx.appcompat:appcompat:1.1.0-alpha04'
			implementation 'androidx.legacy:legacy-support-v4:1.0.0'
		}

		apply plugin: 'com.google.gms.google-services'

Create a release app by running the **Flutter build apk** command.  Install the apk by running **flutter install** or  release it on Google Play and download it. 

## Logs

> 
		2019-04-16 18:48:32.081 5723-5723/? E/ProActivieLaunch: Sending Broadcast
		2019-04-16 18:48:32.087 3867-4310/? E/ActivityManager: TouchDown intent received, starting ActiveLaunch
		2019-04-16 18:48:32.115 13270-13270/? E/Zygote: isWhitelistProcess - Process is Whitelisted
		2019-04-16 18:48:32.117 13270-13270/? E/Zygote: accessInfo : 1
		2019-04-16 18:48:32.132 13270-13270/? E/.myapp: Not starting debugger since process cannot load the jdwp agent.
		2019-04-16 18:48:32.246 3541-3637/? E/IptablesRestoreController: [iptables debug]iptables-restore execute *filter
			-D fw_standby_uid -m owner --uid-owner 10727 -j DROP
			COMMIT
		2019-04-16 18:48:32.261 3541-3637/? E/IptablesRestoreController: [iptables debug]iptables-restore execute done *filter
			-D fw_standby_uid -m owner --uid-owner 10727 -j DROP
			COMMIT
			, res : 0
		2019-04-16 18:48:32.367 3541-3637/? E/IptablesRestoreController: [iptables debug]iptables-restore execute *filter
			-I bw_happy_box -m owner --uid-owner 10116 --jump RETURN
			COMMIT
		2019-04-16 18:48:32.383 3541-3637/? E/IptablesRestoreController: [iptables debug]iptables-restore execute done *filter
			-I bw_happy_box -m owner --uid-owner 10116 --jump RETURN
			COMMIT
			, res : 0
		2019-04-16 18:48:32.385 3541-3637/? E/IptablesRestoreController: [iptables debug]iptables-restore execute *filter
			-D bw_penalty_box -m owner --uid-owner 10116 --jump REJECT
			COMMIT
		2019-04-16 18:48:32.395 13270-13270/? E/AndroidRuntime: FATAL EXCEPTION: main
			Process: abc.xyz.myappo, PID: 13270
			java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/abc.xyz.myappo-3sapFtWxo9ENC0Ct-NdQOw==/base.apk"],nativeLibraryDirectories=[/data/app/abc.xyz.myappo-3sapFtWxo9ENC0Ct-NdQOw==/lib/arm64, /data/app/abc.xyz.myappo-3sapFtWxo9ENC0Ct-NdQOw==/base.apk!/lib/arm64-v8a, /system/lib64, /system/vendor/lib64]]] couldn't find "libflutter.so"
				at java.lang.Runtime.loadLibrary0(Runtime.java:1012)
				at java.lang.System.loadLibrary(System.java:1669)
				at io.flutter.view.FlutterMain.startInitialization(FlutterMain.java:160)
				at io.flutter.view.FlutterMain.startInitialization(FlutterMain.java:135)
				at io.flutter.app.FlutterApplication.onCreate(FlutterApplication.java:22)
				at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1154)
				at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6217)
				at android.app.ActivityThread.access$1200(ActivityThread.java:237)
				at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1785)
				at android.os.Handler.dispatchMessage(Handler.java:106)
				at android.os.Looper.loop(Looper.java:214)
				at android.app.ActivityThread.main(ActivityThread.java:7045)
				at java.lang.reflect.Method.invoke(Native Method)
				at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
				at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:964)
		2019-04-16 18:48:32.409 3541-3637/? E/IptablesRestoreController: [iptables debug]iptables-restore execute done *filter
			-D bw_penalty_box -m owner --uid-owner 10116 --jump REJECT
			COMMIT
			, res : 0
		2019-04-16 18:48:32.520 13324-13324/? E/Zygote: isWhitelistProcess - Process is Whitelisted
		2019-04-16 18:48:32.521 13324-13324/? E/Zygote: accessInfo : 1
		2019-04-16 18:48:32.531 13324-13324/? E/android.vendin: Not starting debugger since process cannot load the jdwp agent.
		2019-04-16 18:48:32.560 5723-31002/? E/id.app.launche: No package ID ff found for ID 0xffffffff.
		2019-04-16 18:48:32.564 5723-31002/? E/IconLoader: Could not find icon drawable from resource
			android.content.res.Resources$NotFoundException: Resource ID #0xffffffff
				at android.content.res.ResourcesImpl.getValueForDensity(ResourcesImpl.java:237)
				at android.content.res.Resources.getDrawableForDensity(Resources.java:902)
				at android.content.res.Resources.getDrawable(Resources.java:842)
				at com.android.systemui.shared.recents.model.IconLoader.createNewIconForTask(IconLoader.java:118)
				at com.android.systemui.shared.recents.model.IconLoader.getAndInvalidateIfModified(IconLoader.java:94)
				at com.android.systemui.shared.recents.model.RecentsTaskLoader.getAndUpdateActivityIcon(RecentsTaskLoader.java:328)
				at com.android.systemui.shared.recents.model.RecentsTaskLoadPlan.executePlan(RecentsTaskLoadPlan.java:225)
				at com.android.systemui.shared.recents.model.RecentsTaskLoader.loadTasks(RecentsTaskLoader.java:173)
				at com.android.launcher3.quickstep.RecentsModel.onTaskStackChangedBackground(RecentsModel.java:253)
				at com.android.systemui.shared.system.TaskStackChangeListeners.onTaskStackChanged(TaskStackChangeListeners.java:82)
				at android.app.ITaskStackListener$Stub.onTransact(ITaskStackListener.java:50)
				at android.os.Binder.execTransact(Binder.java:739)
		2019-04-16 18:48:32.591 3541-3637/? E/IptablesRestoreController: [iptables debug]iptables-restore execute *filter
			-D bw_happy_box -m owner --uid-owner 10116 --jump RETURN
			COMMIT
		2019-04-16 18:48:32.613 3541-3637/? E/IptablesRestoreController: [iptables debug]iptables-restore execute done *filter
			-D bw_happy_box -m owner --uid-owner 10116 --jump RETURN
			COMMIT
			, res : 0
		2019-04-16 18:48:32.613 3541-3637/? E/IptablesRestoreController: [iptables debug]iptables-restore execute *filter
			-I bw_penalty_box -m owner --uid-owner 10116 --jump REJECT
			COMMIT
		2019-04-16 18:48:32.617 32464-32488/? E/PBSessionCacheImpl: sessionId[142779737370187316] not persisted.
		2019-04-16 18:48:32.636 3541-3637/? E/IptablesRestoreController: [iptables debug]iptables-restore execute done *filter
			-I bw_penalty_box -m owner --uid-owner 10116 --jump REJECT
			COMMIT
			, res : 0
		2019-04-16 18:48:32.674 4795-7628/? E/rs$DefaultThreadFactory: ===== Detect pool-thread leak =====
		2019-04-16 18:48:32.675 4795-7628/? E/rs$DefaultThreadFactory: dalvik.system.VMStack.getThreadStackTrace(Native Method)
		2019-04-16 18:48:32.675 4795-7628/? E/rs$DefaultThreadFactory: java.lang.Thread.getStackTrace(Thread.java:1538)
		2019-04-16 18:48:32.675 4795-7628/? E/rs$DefaultThreadFactory: java.util.concurrent.Executors$DefaultThreadFactory.newThread(Executors.java:569)
		2019-04-16 18:48:32.675 4795-7628/? E/rs$DefaultThreadFactory: rsb.newThread(Unknown Source:9)
		2019-04-16 18:48:32.675 4795-7628/? E/rs$DefaultThreadFactory: java.util.concurrent.ThreadPoolExecutor$Worker.<init>(ThreadPoolExecutor.java:636)
		2019-04-16 18:48:32.675 4795-7628/? E/rs$DefaultThreadFactory: java.util.concurrent.ThreadPoolExecutor.addWorker(ThreadPoolExecutor.java:950)
		2019-04-16 18:48:32.675 4795-7628/? E/rs$DefaultThreadFactory: java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1393)
		2019-04-16 18:48:32.675 4795-7628/? E/rs$DefaultThreadFactory: rme.a(:com.google.android.gms@16089037@16.0.89 (100400-239467275):22)
		2019-04-16 18:48:32.675 4795-7628/? E/rs$DefaultThreadFactory: rme.execute(:com.google.android.gms@16089037@16.0.89 (100400-239467275):4)
		2019-04-16 18:48:32.675 4795-7628/? E/rs$DefaultThreadFactory: zah.run(:com.google.android.gms@16089037@16.0.89 (100400-239467275):33)
		2019-04-16 18:48:32.675 4795-7628/? E/rs$DefaultThreadFactory: bgxm.run(:com.google.android.gms@16089037@16.0.89 (100400-239467275):2)
		2019-04-16 18:48:32.675 4795-7628/? E/rs$DefaultThreadFactory: rmf.b(:com.google.android.gms@16089037@16.0.89 (100400-239467275):32)
		2019-04-16 18:48:32.675 4795-7628/? E/rs$DefaultThreadFactory: rmf.run(:com.google.android.gms@16089037@16.0.89 (100400-239467275):21)
		2019-04-16 18:48:32.675 4795-7628/? E/rs$DefaultThreadFactory: java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
		2019-04-16 18:48:32.675 4795-7628/? E/rs$DefaultThreadFactory: java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
		2019-04-16 18:48:32.675 4795-7628/? E/rs$DefaultThreadFactory: rsc.run(Unknown Source:7)
		2019-04-16 18:48:32.675 4795-7628/? E/rs$DefaultThreadFactory: java.lang.Thread.run(Thread.java:764)
		2019-04-16 18:48:32.686 5723-13340/? E/Launcher.WallpaperUtils: bitmap.recycle() on releaseWallpaperDrawable
		2019-04-16 18:48:32.776 13357-13357/? E/Zygote: isWhitelistProcess - Process is Whitelisted
		2019-04-16 18:48:32.777 13357-13357/? E/Zygote: accessInfo : 1
		2019-04-16 18:48:32.783 13357-13357/? E/android.dqagen: Not starting debugger since process cannot load the jdwp agent.
		2019-04-16 18:48:32.926 13404-13404/? E/Zygote: isWhitelistProcess - Process is Whitelisted
		2019-04-16 18:48:32.927 13404-13404/? E/Zygote: accessInfo : 1
		2019-04-16 18:48:32.935 13404-13404/? E/e.process.gapp: Not starting debugger since process cannot load the jdwp agent.
		2019-04-16 18:48:33.669 23366-13355/? E/FasUtils: pkg=null userId=0 has no information
		2019-04-16 18:48:33.817 23366-13355/? E/FasUtils: pkg=null userId=0 has no information
		2019-04-16 18:48:33.902 23366-13355/? E/FasUtils: pkg=null userId=0 has no information
		2019-04-16 18:48:33.905 23366-13355/? E/FasUtils: pkg=null userId=0 has no information
		2019-04-16 18:48:34.305 23366-13355/? E/FasUtils: pkg=null userId=0 has no information
		2019-04-16 18:48:34.346 23366-13355/? E/FasUtils: pkg=null userId=0 has no information
		2019-04-16 18:48:34.491 13094-13202/? E/CompactDiskManagerImpl.cpp: Failed to remove new folder structure directories: No such file or directory
		2019-04-16 18:48:34.688 23366-13355/? E/FasUtils: pkg=null userId=0 has no information
		2019-04-16 18:48:34.697 23366-13355/? E/FasUtils: pkg=null userId=0 has no information
		2019-04-16 18:48:34.896 13094-13208/? E/CompactDiskManagerImpl.cpp: Failed to remove new folder structure directories: No such file or directory
		2019-04-16 18:48:34.916 13094-13200/? E/CompactDiskManagerImpl.cpp: Failed to remove new folder structure directories: No such file or directory
		2019-04-16 18:48:34.938 13094-13202/? E/CompactDiskManagerImpl.cpp: Failed to remove new folder structure directories: No such file or directory
		2019-04-16 18:48:34.960 23366-13355/? E/FasUtils: pkg=null userId=0 has no information
		2019-04-16 18:48:34.964 13094-13207/? E/fb4a.GraphServiceQueryExecutor: query error
			X.4l8: [code] 1675012 [message]: There was a problem with this request. We're working on getting it fixed as soon as we can. [extra]: 
				at X.11z.onError(:187337)
				at X.1Gt.onError(:203860)
				at com.facebook.common.jniexecutors.NativeRunnable.run(Native Method)
				at com.facebook.common.jniexecutors.PooledNativeRunnable.run(:137014)
				at X.1DO.execute(:95801)
				at com.facebook.common.jniexecutors.NativeRunnable.run(Native Method)
				at com.facebook.common.jniexecutors.PooledNativeRunnable.run(:137014)
				at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:459)
				at X.0YT.run(:51585)
				at X.0YU.run(:156773)
				at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
				at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
				at X.0Yd.run(:157019)
				at X.0Ye.run(:51590)
				at java.lang.Thread.run(Thread.java:764)
		2019-04-16 18:48:34.999 13094-13207/? E/CompactDiskManagerImpl.cpp: Failed to remove new folder structure directories: No such file or directory
		2019-04-16 18:48:35.024 13094-13199/? E/fb4a.6Eh: Error with Auto Sync Locale
			java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String com.fasterxml.jackson.databind.JsonNode.asText()' on a null object reference
				at X.6Xc.ewA(:836204)
				at X.2bv.handleResponse(:419410)
				at X.278.run(:279170)
				at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:459)
				at X.0YT.run(:51585)
				at X.0YU.run(:156773)
				at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
				at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
				at X.0Yd.run(:157019)
				at X.0Ye.run(:51590)
				at java.lang.Thread.run(Thread.java:764)
		2019-04-16 18:48:35.034 13094-13218/? E/CompactDiskManagerImpl.cpp: Failed to remove new folder structure directories: No such file or directory
		2019-04-16 18:48:35.060 13094-13192/? E/CompactDiskManagerImpl.cpp: Failed to remove new folder structure directories: No such file or directory
		2019-04-16 18:48:35.071 13094-13199/? E/CompactDiskManagerImpl.cpp: Failed to remove new folder structure directories: No such file or directory
		2019-04-16 18:48:35.087 13094-13218/? E/CompactDiskManagerImpl.cpp: Failed to remove new folder structure directories: No such file or directory
		2019-04-16 18:48:35.346 13094-13450/? E/fb4a.GRAPHQL_QUERY_STRING: Trying to use query id on graph services backed query 'InspirationCategoriesGraphQL'. The id is now removed from Java layer. See https://fburl.com/7c0t5i23 for more explanation.
		2019-04-16 18:48:35.347 13094-13450/? E/fb4a.GRAPHQL_QUERY_STRING: Trying to use query id on graph services backed query 'InspirationCategoriesGraphQL'. The id is now removed from Java layer. See https://fburl.com/7c0t5i23 for more explanation.
		2019-04-16 18:48:37.415 3319-5268/? E/BufferQueueProducer: [com.android.systemui.ImageWallpaper[4370]#0] disconnect: not connected (req=1)

```
```

```
```

```
```

**Comment by htsnet** [comment]
My app is crashing only under Android 9. The main page is showed, no ads and, then, the app crash. Under an old Android version it is OK. Ok also in emulator. It seems that is something about Admob. No error is showed.

I am using these packages:
  cupertino_icons: ^0.1.2
  shared_preferences: ^0.5.2
  url_launcher: ^5.0.2
  firebase_admob: ^0.8.0+4
  firebase_messaging: 4.0.0+3
  firebase_analytics: 2.1.1+2
  firebase_core: ^0.3.4
  font_awesome_flutter: ^8.4.0
  flutter_launcher_icons: ^0.7.0

**Comment by signshah** [comment]
@htsnet have you found anything?

**Comment by htsnet** [comment]
@signshah nothing yet. In my Galsy S8 / Android 9, most times do not show any ad. Once I saw the ad. And sometimes the app crash. I another cell phone (Galaxy S4 / Android 5.0.1) everything OK.

**Comment by AdamBCo** [comment]
@htsnet Any luck?

**Comment by htsnet** [comment]
@signshah The app does not crash anymore, but the ads sometimes appears, sometimes not. I think that is an issue with Admob, not Flutter. But I am not sure.

**Comment by matte5031** [comment]
app crashes for me aswell because of firebase_admob

**Comment by kf6gpe** [comment]
@signshah , were you trying to use firebase_admob as well? Wondering if this is one issue or two. Thanks!

**Comment by signshah** [comment]
@kf6gpe I haven't worked on the app since so long but I heard that flutter team has fixed the issue. Now with the flutter master channel it should work. I will try and update the post whenever I get time. Thanks for your time.

**Comment by TahaTesser** [comment]
Hi @signshah 
given your last message I feel safe to close this issue,
if you disagree please write in the comments and I will reopen it. 
Thank you
