### ISSUE TITLE
Is there a way to verify keys for flutter driver testing. _DriverError: Failed to fulfill Tap due to remote error

### ISSUE THREAD

**Issue by snickersv2** [flutter/flutter#31167]
### Description

We are new on flutter and we are planning to write integration testing using flutter_driver as per documentation. We want to ask if there is a way to verify the keys we used during testing. For example check in debug mode if FlutterDriver can perform actions like tap or using SerializableFinder can actually find a widget with a certain key.
Currently we encounter this error below while calling driver.tap on a few widgets. (https://docs.flutter.io/flutter/flutter_driver/FlutterDriver/tap.html)
```
_DriverError: Failed to fulfill Tap due to remote error
Original error: Bad state: The client is closed.

#0      Client._send (package:json_rpc_2/src/client.dart:139:19)
#1      Client.sendRequest (package:json_rpc_2/src/client.dart:107:5)
#2      Peer.sendRequest (package:json_rpc_2/src/peer.dart:68:15)
#3      Scope.sendRequestRaw (package:vm_service_client/src/scope.dart:64:23)
<asynchronous suspension>
#4      VMIsolateRef.invokeExtension (package:vm_service_client/src/isolate.dart:361:19)
#5      FlutterDriver._sendCommand (package:flutter_driver/src/driver/driver.dart:397:63)
<asynchronous suspension>
#6      FlutterDriver.tap (package:flutter_driver/src/driver/driver.dart:441:11)
<asynchronous suspension>
#7      main.<anonymous closure>.<anonymous closure> (file:///Users/abanv2/Documents/Bitbucket/janus-mobile-app/test_driver/main_page_nav_test.dart:173:22)
<asynchronous suspension>
#8      Declarer.test.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:test_api/src/backend/declarer.dart:168:27)
<asynchronous suspension>
#9      Invoker.waitForOutstandingCallbacks.<anonymous closure> (package:test_api/src/backend/invoker.dart:250:15)
<asynchronous suspension>
#10     _rootRun (dart:async/zone.dart:1124:13)
#11     _CustomZone.run (dart:async/zone.dart:1021:19)
#12     _runZoned (dart:async/zone.dart:1516:10)
#13     runZoned (dart:async/zone.dart:1463:12)
#14     Invoker.waitForOutstandingCallbacks (package:test_api/src/backend/invoker.dart:247:5)
#15     Declarer.test.<anonymous closure>.<anonymous closure> (package:test_api/src/backend/declarer.dart:166:33)
#16     _rootRun (dart:async/zone.dart:1124:13)
#17     _CustomZone.run (dart:async/zone.dart:1021:19)
#18     _runZoned (dart:async/zone.dart:1516:10)
#19     runZoned (dart:async/zone.dart:1463:12)
#20     Declarer.test.<anonymous closure> (package:test_api/src/backend/declarer.dart:165:13)
<asynchronous suspension>
#21     Invoker._onRun.<anonymous closure>.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:test_api/src/backend/invoker.dart:400:25)
<asynchronous suspension>
#22     new Future.<anonymous closure> (dart:async/future.dart:176:37)
#23     StackZoneSpecification._run (package:stack_trace/src/stack_zone_specification.dart:209:15)
#24     StackZoneSpecification._registerCallback.<anonymous closure> (package:stack_trace/src/stack_zone_specification.dart:119:48)
#25     _rootRun (dart:async/zone.dart:1120:38)
#26     _CustomZone.run (dart:async/zone.dart:1021:19)
#27     _CustomZone.runGuarded (dart:async/zone.dart:923:7)
#28     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:963:23)
#29     StackZoneSpecification._run (package:stack_trace/src/stack_zone_specification.dart:209:15)
#30     StackZoneSpecification._registerCallback.<anonymous closure> (package:stack_trace/src/stack_zone_specification.dart:119:48)
#31     _rootRun (dart:async/zone.dart:1124:13)
#32     _CustomZone.run (dart:async/zone.dart:1021:19)
#33     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:947:23)
#34     Timer._createTimer.<anonymous closure> (dart:async/runtime/libtimer_patch.dart:21:15)
#35     _Timer._runTimers (dart:isolate/runtime/libtimer_impl.dart:382:19)
#36     _Timer._handleMessage (dart:isolate/runtime/libtimer_impl.dart:416:5)
#37     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:171:12)_
```

### Configurations:
First I run the app with this Run/Debug config:
![Screen Shot 2019-04-16 at 5 16 54 PM](https://user-images.githubusercontent.com/49699862/56252219-b1119f00-606b-11e9-8ad9-37c4b7ec7226.png)

And then I run the test with this config:
![Screen Shot 2019-04-16 at 5 15 01 PM](https://user-images.githubusercontent.com/49699862/56252231-c2f34200-606b-11e9-9be7-ed7a64dd6157.png)

This is based on this article (although not exactly the same execution)
https://medium.com/flutter-community/hot-reload-for-flutter-integration-tests-e0478b63bd54

Kindly advise and let me know if you need more info. Thank you.

### Flutter Doctor
```
[✓] Flutter (Channel stable, v1.2.1, on Mac OS X 10.14.4 18E226, locale en-US)
    • Flutter version 1.2.1 at /Users/abanv2/Documents/Flutter/sdk/flutter
    • Framework revision 8661d8aecd (9 weeks ago), 2019-02-14 19:19:53 -0800
    • Engine revision 3757390fa4
    • Dart version 2.1.2 (build 2.1.2-dev.0.0 0a7dcf17eb)

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/abanv2/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling
      support)
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = /Users/abanv2/Library/Android/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_152-release-1248-b01)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.2, Build version 10E125
    • ios-deploy 1.9.4
    • CocoaPods version 1.6.1

[✓] Android Studio (version 3.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 33.4.1
    • Dart plugin version 182.5215
    • Java version OpenJDK Runtime Environment (build
      1.8.0_152-release-1248-b01)

[✓] IntelliJ IDEA Community Edition (version 2019.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 33.4.3
    • Dart plugin version 191.6183.87

[✓] Connected device (1 available)
    • SM A520F • 52105109ea678475 • android-arm64 • Android 8.0.0 (API 26)
      (emulator)

• No issues found!
```

**Comment by TahaTesser** [comment]
Hi @snickersv2 
It is recommended to use `integration_test` instead of `flutter_driver` if you have such an issue with `integration_test`. Please file a new issue with all the details
