### ISSUE TITLE
Task :device_info:compileDebugJavaWithJavac FAILED  

### ISSUE THREAD

**Issue by MattL-NZ** [flutter/flutter#31221]
I am trying to run a flutter application and I'm getting a 
`Task :device_info:compileDebugJavaWithJavac FAILED`  error.
I am getting this when running `flutter run`

I only seem to have issues when building it for Android. When i build it for iOS it runs fine which makes me think its something to do with Gradle.

## Logs

`flutter run --verbose`
```[  +31 ms] executing: [/Users/mattlist/flutter/] git log -n 1 --pretty=format:%H
[  +50 ms] Exit code 0 from: git log -n 1 --pretty=format:%H
[        ] b963c15efbb32f1604cf604e40f6dac5daad395e
[        ] executing: [/Users/mattlist/flutter/] git describe --match v*.*.* --first-parent --long --tags
[  +83 ms] Exit code 0 from: git describe --match v*.*.* --first-parent --long --tags
[        ] v1.5.0-11-gb963c15ef
[  +16 ms] executing: [/Users/mattlist/flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[  +16 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/master
[        ] executing: [/Users/mattlist/flutter/] git ls-remote --get-url origin
[  +12 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[  +56 ms] executing: [/Users/mattlist/flutter/] git rev-parse --abbrev-ref HEAD
[  +11 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] master
[ +254 ms] executing: /Users/mattlist/Library/Android/sdk/platform-tools/adb devices -l
[  +33 ms] Exit code 0 from: /Users/mattlist/Library/Android/sdk/platform-tools/adb devices -l
[        ] List of devices attached
           emulator-5554          device product:sdk_gphone_x86_64 model:Android_SDK_built_for_x86_64 device:generic_x86_64 transport_id:1
[  +30 ms] executing: idevice_id -h
[  +44 ms] /usr/bin/xcrun simctl list --json devices
[ +211 ms] /Users/mattlist/Library/Android/sdk/platform-tools/adb -s emulator-5554 shell getprop
[  +64 ms] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +7 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FuchsiaCacheArtifacts' is not required, skipping update.
[ +100 ms] Found plugin device_info at /Users/mattlist/.pub-cache/hosted/pub.dartlang.org/device_info-0.4.0+1/
[  +30 ms] Found plugin flutter_webview_plugin at /Users/mattlist/.pub-cache/hosted/pub.dartlang.org/flutter_webview_plugin-0.3.1/
[  +15 ms] Found plugin package_info at /Users/mattlist/.pub-cache/hosted/pub.dartlang.org/package_info-0.3.2+1/
[   +5 ms] Found plugin path_provider at /Users/mattlist/.pub-cache/hosted/pub.dartlang.org/path_provider-0.4.1/
[   +2 ms] Found plugin permission_handler at /Users/mattlist/.pub-cache/hosted/pub.dartlang.org/permission_handler-3.0.0/
[   +8 ms] Found plugin shared_preferences at /Users/mattlist/.pub-cache/hosted/pub.dartlang.org/shared_preferences-0.4.3/
[  +17 ms] Found plugin uni_links at /Users/mattlist/.pub-cache/hosted/pub.dartlang.org/uni_links-0.1.4/
[   +1 ms] Found plugin url_launcher at /Users/mattlist/.pub-cache/hosted/pub.dartlang.org/url_launcher-4.1.0+1/
[  +36 ms] Found plugin device_info at /Users/mattlist/.pub-cache/hosted/pub.dartlang.org/device_info-0.4.0+1/
[  +14 ms] Found plugin flutter_webview_plugin at /Users/mattlist/.pub-cache/hosted/pub.dartlang.org/flutter_webview_plugin-0.3.1/
[  +11 ms] Found plugin package_info at /Users/mattlist/.pub-cache/hosted/pub.dartlang.org/package_info-0.3.2+1/
[   +3 ms] Found plugin path_provider at /Users/mattlist/.pub-cache/hosted/pub.dartlang.org/path_provider-0.4.1/
[   +1 ms] Found plugin permission_handler at /Users/mattlist/.pub-cache/hosted/pub.dartlang.org/permission_handler-3.0.0/
[   +7 ms] Found plugin shared_preferences at /Users/mattlist/.pub-cache/hosted/pub.dartlang.org/shared_preferences-0.4.3/
[   +9 ms] Found plugin uni_links at /Users/mattlist/.pub-cache/hosted/pub.dartlang.org/uni_links-0.1.4/
[   +1 ms] Found plugin url_launcher at /Users/mattlist/.pub-cache/hosted/pub.dartlang.org/url_launcher-4.1.0+1/
[  +41 ms] ro.hardware = ranchu
[  +22 ms] Using hardware rendering with device Android SDK built for x86 64. If you get graphics artifacts, consider enabling software rendering with "--enable-software-rendering".
[  +29 ms] Launching lib/main.dart on Android SDK built for x86 64 in debug mode...
[  +54 ms] executing: /Users/mattlist/Library/Android/sdk/platform-tools/adb -s emulator-5554 shell -x logcat -v time -t 1
[  +23 ms] Exit code 0 from: /Users/mattlist/Library/Android/sdk/platform-tools/adb -s emulator-5554 shell -x logcat -v time -t 1
[        ] --------- beginning of main
           04-18 08:20:17.528 I/GnssLocationProvider( 1842): WakeLock released by handleMessage(REPORT_SV_STATUS, 0, com.android.server.location.GnssLocationProvider$SvStatusInfo@27b6d86)
[   +3 ms] executing: /Users/mattlist/Library/Android/sdk/platform-tools/adb -s emulator-5554 shell -x logcat -v time
[   +7 ms] executing: /Users/mattlist/Library/Android/sdk/platform-tools/adb version
[  +35 ms] Android Debug Bridge version 1.0.40
           Version 28.0.2-5303910
           Installed as /Users/mattlist/Library/Android/sdk/platform-tools/adb
[   +5 ms] executing: /Users/mattlist/Library/Android/sdk/platform-tools/adb start-server
[  +65 ms] Building APK
[  +42 ms] Initializing gradle...
[  +13 ms] Using gradle from /Users/mattlist/Downloads/kamino-master/android/gradlew.
[  +25 ms] executing: /usr/bin/defaults read /Applications/Android Studio.app/Contents/Info
[  +72 ms] Exit code 0 from: /usr/bin/defaults read /Applications/Android Studio.app/Contents/Info
[        ] {
               CFBundleDevelopmentRegion = English;
               CFBundleDocumentTypes =     (
                           {
                       CFBundleTypeExtensions =             (
                           ipr
                       );
                       CFBundleTypeIconFile = "studio.icns";
                       CFBundleTypeName = "Android Studio Project File";
                       CFBundleTypeRole = Editor;
                   },
                           {
                       CFBundleTypeExtensions =             (
                           "*"
                       );
                       CFBundleTypeName = "All documents";
                       CFBundleTypeOSTypes =             (
                           "****"
                       );
                       CFBundleTypeRole = Editor;
                       LSTypeIsPackage = 0;
                   }
               );
               CFBundleExecutable = studio;
               CFBundleGetInfoString = "Android Studio 3.3, build AI-182.5107.16.33.5314842. Copyright JetBrains s.r.o., (c) 2000-2019";
               CFBundleIconFile = "studio.icns";
               CFBundleIdentifier = "com.google.android.studio";
               CFBundleInfoDictionaryVersion = "6.0";
               CFBundleName = "Android Studio";
               CFBundlePackageType = APPL;
               CFBundleShortVersionString = "3.3";
               CFBundleSignature = "????";
               CFBundleURLTypes =     (
                           {
                       CFBundleTypeRole = Editor;
                       CFBundleURLName = Stacktrace;
                       CFBundleURLSchemes =             (
                           idea
                       );
                   }
               );
               CFBundleVersion = "AI-182.5107.16.33.5314842";
               JVMOptions =     {
                   ClassPath =
                   "$APP_PACKAGE/Contents/lib/bootstrap.jar:$APP_PACKAGE/Contents/lib/extensions.jar:$APP_PACKAGE/Contents/lib/util.jar:$APP_PACKAGE/Contents/lib/jdom.jar:$APP_PACKAGE/Contents/lib/log4j.jar:$APP_PACKAGE/Conte
                   nts/lib/trove4j.jar:$APP_PACKAGE/Contents/lib/jna.jar";
                   JVMVersion = "1.8*,1.8+";
                   MainClass = "com.intellij.idea.Main";
                   Properties =         {
                       "idea.executable" = studio;
                       "idea.home.path" = "$APP_PACKAGE/Contents";
                       "idea.java.redist" = Bundled;
                       "idea.paths.selector" = "AndroidStudio3.3";
                       "idea.platform.prefix" = AndroidStudio;
                   };
                   WorkingDirectory = "$APP_PACKAGE/Contents/bin";
               };
               LSApplicationCategoryType = "public.app-category.developer-tools";
               LSArchitecturePriority =     (
                   "x86_64"
               );
               LSMinimumSystemVersion = "10.8";
               LSRequiresNativeExecution = YES;
               NSHighResolutionCapable = 1;
               NSSupportsAutomaticGraphicsSwitching = 1;
           }
[  +56 ms] executing: /usr/bin/defaults read /Applications/Android Studio.app/Contents/Info CFBundleShortVersionString
[  +78 ms] Exit code 0 from: /usr/bin/defaults read /Applications/Android Studio.app/Contents/Info CFBundleShortVersionString
[        ] 3.3
[  +87 ms] executing: /Users/mattlist/Downloads/kamino-master/android/gradlew -v
[ +677 ms] 
                    ------------------------------------------------------------
                    Gradle 4.10.1
                    ------------------------------------------------------------

                    Build time:   2018-09-12 11:33:27 UTC
                    Revision:     76c9179ea9bddc32810f9125ad97c3315c544919

                    Kotlin DSL:   1.0-rc-6
                    Kotlin:       1.2.61
                    Groovy:       2.4.15
                    Ant:          Apache Ant(TM) version 1.9.11 compiled on March 23 2018
                    JVM:          1.8.0_152-release (JetBrains s.r.o 25.152-b01)
                    OS:           Mac OS X 10.14.4 x86_64
[   +9 ms] Initializing gradle... (completed in 1.0s)
[   +1 ms] Running 'gradlew build'...
[   +1 ms] executing: [/Users/mattlist/Downloads/kamino-master/android/] /Users/mattlist/Downloads/kamino-master/android/gradlew build
[+1191 ms] > Task :device_info:preBuild UP-TO-DATE
[        ] > Task :device_info:preDebugBuild UP-TO-DATE
[  +95 ms] > Task :device_info:compileDebugAidl NO-SOURCE
[        ] > Task :device_info:compileDebugRenderscript UP-TO-DATE
[        ] > Task :device_info:checkDebugManifest UP-TO-DATE
[        ] > Task :device_info:generateDebugBuildConfig UP-TO-DATE
[        ] > Transform aapt2-osx.jar (com.android.tools.build:aapt2:3.3.2-5309881) with Aapt2Extractor
[        ] > Task :device_info:generateDebugResValues UP-TO-DATE
[        ] > Task :device_info:generateDebugResources UP-TO-DATE
[        ] > Task :device_info:packageDebugResources UP-TO-DATE
[        ] > Task :device_info:processDebugManifest UP-TO-DATE
[        ] > Task :device_info:generateDebugRFile UP-TO-DATE
[        ] > Task :device_info:prepareLintJar UP-TO-DATE
[        ] > Task :device_info:generateDebugSources UP-TO-DATE
[        ] > Task :device_info:javaPreCompileDebug UP-TO-DATE
[  +98 ms] > Task :device_info:compileDebugJavaWithJavac FAILED
[   +1 ms] /Users/mattlist/.pub-cache/hosted/pub.dartlang.org/device_info-0.4.0+1/android/src/main/java/io/flutter/plugins/deviceinfo/DeviceInfoPlugin.java:13: error: package io.flutter.plugin.common does not exist
[   +2 ms] import io.flutter.plugin.common.MethodCall;
[        ]                                ^
[        ] /Users/mattlist/.pub-cache/hosted/pub.dartlang.org/device_info-0.4.0+1/android/src/main/java/io/flutter/plugins/deviceinfo/DeviceInfoPlugin.java:14: error: package io.flutter.plugin.common does not exist
[        ] import io.flutter.plugin.common.MethodChannel;
[        ]                                ^
[        ] /Users/mattlist/.pub-cache/hosted/pub.dartlang.org/device_info-0.4.0+1/android/src/main/java/io/flutter/plugins/deviceinfo/DeviceInfoPlugin.java:15: error: package io.flutter.plugin.common.MethodChannel does not
exist
[   +1 ms] import io.flutter.plugin.common.MethodChannel.MethodCallHandler;
[        ]                                              ^
[        ] /Users/mattlist/.pub-cache/hosted/pub.dartlang.org/device_info-0.4.0+1/android/src/main/java/io/flutter/plugins/deviceinfo/DeviceInfoPlugin.java:16: error: package io.flutter.plugin.common.MethodChannel does not
exist
[        ] import io.flutter.plugin.common.MethodChannel.Result;
[        ]                                              ^
[        ] /Users/mattlist/.pub-cache/hosted/pub.dartlang.org/device_info-0.4.0+1/android/src/main/java/io/flutter/plugins/deviceinfo/DeviceInfoPlugin.java:17: error: package io.flutter.plugin.common.PluginRegistry does not
exist
[        ] import io.flutter.plugin.common.PluginRegistry.Registrar;
[        ]                                               ^
[        ] /Users/mattlist/.pub-cache/hosted/pub.dartlang.org/device_info-0.4.0+1/android/src/main/java/io/flutter/plugins/deviceinfo/DeviceInfoPlugin.java:23: error: cannot find symbol
[        ] public class DeviceInfoPlugin implements MethodCallHandler {
[        ]                                          ^
[        ]   symbol: class MethodCallHandler
[        ] /Users/mattlist/.pub-cache/hosted/pub.dartlang.org/device_info-0.4.0+1/android/src/main/java/io/flutter/plugins/deviceinfo/DeviceInfoPlugin.java:30: error: cannot find symbol
[        ]   public static void registerWith(Registrar registrar) {
[        ]                                   ^
[        ]   symbol:   class Registrar
[        ]   location: class DeviceInfoPlugin
[        ] /Users/mattlist/.pub-cache/hosted/pub.dartlang.org/device_info-0.4.0+1/android/src/main/java/io/flutter/plugins/deviceinfo/DeviceInfoPlugin.java:42: error: cannot find symbol
[        ]   public void onMethodCall(MethodCall call, Result result) {
[        ]                            ^
[        ]   symbol:   class MethodCall
[        ]   location: class DeviceInfoPlugin
[        ] /Users/mattlist/.pub-cache/hosted/pub.dartlang.org/device_info-0.4.0+1/android/src/main/java/io/flutter/plugins/deviceinfo/DeviceInfoPlugin.java:42: error: cannot find symbol
[        ]   public void onMethodCall(MethodCall call, Result result) {
[        ]                                             ^
[        ]   symbol:   class Result
[        ]   location: class DeviceInfoPlugin
[        ] /Users/mattlist/.pub-cache/hosted/pub.dartlang.org/device_info-0.4.0+1/android/src/main/java/io/flutter/plugins/deviceinfo/DeviceInfoPlugin.java:31: error: cannot find symbol
[        ]     final MethodChannel channel =
[        ]           ^
[        ]   symbol:   class MethodChannel
[        ]   location: class DeviceInfoPlugin
[        ] /Users/mattlist/.pub-cache/hosted/pub.dartlang.org/device_info-0.4.0+1/android/src/main/java/io/flutter/plugins/deviceinfo/DeviceInfoPlugin.java:32: error: cannot find symbol
[        ]         new MethodChannel(registrar.messenger(), "plugins.flutter.io/device_info");
[        ]             ^
[        ]   symbol:   class MethodChannel
[        ]   location: class DeviceInfoPlugin
[        ] /Users/mattlist/.pub-cache/hosted/pub.dartlang.org/device_info-0.4.0+1/android/src/main/java/io/flutter/plugins/deviceinfo/DeviceInfoPlugin.java:41: error: method does not override or implement a method from a
supertype
[        ]   @Override
[        ]   ^
[        ] 12 errors
[        ] FAILURE: Build failed with an exception.
[        ] * What went wrong:
[        ] Execution failed for task ':device_info:compileDebugJavaWithJavac'.
[        ] > Compilation failed; see the compiler error output for details.
[        ] * Try:
[        ] Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
[        ] * Get more help at https://help.gradle.org
[        ] BUILD FAILED in 1s
[        ] 10 actionable tasks: 1 executed, 9 up-to-date
[        ]          *********************************************************
[        ] WARNING: This version of device_info will break your Android build if it or its dependencies aren't compatible with AndroidX.
[        ]          See https://goo.gl/CP92wY for more information on the problem and how to fix it.
[        ]          This warning prints for all Android build failures. The real root cause of the error may be unrelated.
[        ]          *********************************************************
[ +360 ms] Running 'gradlew build'... (completed in 1.8s)
[   +5 ms] "flutter run" took 4,063ms.
[        ] "flutter run" took 4,063ms.
Gradle build failed: 1

#0      throwToolExit (package:flutter_tools/src/base/common.dart:24:3)
#1      _buildGradleProjectV1 (package:flutter_tools/src/android/gradle.dart:366:5)
<asynchronous suspension>
#2      buildGradleProject (package:flutter_tools/src/android/gradle.dart:342:14)
<asynchronous suspension>
#3      buildApk (package:flutter_tools/src/android/apk.dart:34:9)
<asynchronous suspension>
#4      AndroidDevice.startApp (package:flutter_tools/src/android/android_device.dart:377:13)
<asynchronous suspension>
#5      FlutterDevice.runHot (package:flutter_tools/src/resident_runner.dart:364:54)
<asynchronous suspension>
#6      HotRunner.run (package:flutter_tools/src/run_hot.dart:253:39)
<asynchronous suspension>
#7      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:422:37)
<asynchronous suspension>
#8      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:559:18)
#9      _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:77:64)
#10     _rootRunUnary (dart:async/zone.dart:1132:38)
#11     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#12     _FutureListener.handleValue (dart:async/future_impl.dart:126:18)
#13     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:639:45)
#14     Future._propagateToListeners (dart:async/future_impl.dart:668:32)
#15     Future._complete (dart:async/future_impl.dart:473:7)
#16     _SyncCompleter.complete (dart:async/future_impl.dart:51:12)
#17     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:28:18)
#18     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:294:13)
#19     RunCommand.usageValues (package:flutter_tools/src/commands/run.dart)
#20     _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:77:64)
#21     _rootRunUnary (dart:async/zone.dart:1132:38)
#22     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#23     _FutureListener.handleValue (dart:async/future_impl.dart:126:18)
#24     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:639:45)
#25     Future._propagateToListeners (dart:async/future_impl.dart:668:32)
#26     Future._complete (dart:async/future_impl.dart:473:7)
#27     _SyncCompleter.complete (dart:async/future_impl.dart:51:12)
#28     _AsyncAwaitCompleter.complete.<anonymous closure> (dart:async-patch/async_patch.dart:33:20)
#29     _rootRun (dart:async/zone.dart:1124:13)
#30     _CustomZone.run (dart:async/zone.dart:1021:19)
#31     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:947:23)
#32     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#33     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#34     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:115:13)
#35     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:5)```

## Flutter Doctor
`flutter doctor -v`
```[✓] Flutter (Channel master, v1.5.1-pre.11, on Mac OS X 10.14.4 18E226, locale en-NZ)
    • Flutter version 1.5.1-pre.11 at /Users/mattlist/flutter
    • Framework revision b963c15efb (19 hours ago), 2019-04-16 21:23:18 -0400
    • Engine revision b819b62bed
    • Dart version 2.3.0 (build 2.3.0-dev.0.0 8e73b3c006)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/mattlist/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)
    • All Android licenses accepted.

[!] iOS toolchain - develop for iOS devices (Xcode 10.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.2, Build version 10E125
    • ios-deploy 2.0.0
    ✗ ios-deploy out of date (1.9.4 is required). To upgrade with Brew:
        brew upgrade ios-deploy
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 34.0.1
    • Dart plugin version 182.5215
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)

[✓] VS Code (version 1.33.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 2.25.1

[✓] Connected device (1 available)
    • Android SDK built for x86 64 • emulator-5554 • android-x64 • Android 9 (API 28) (emulator)

! Doctor found issues in 1 category.```

**Comment by blasten** [comment]
Without concrete steps to repro this issue, I can't be sure if this an issue on Flutter or on your app.  Feel free to file a new bug with a minimal repro case.
