### ISSUE TITLE
Assert connecting to Activity service under Linux

### ISSUE THREAD

**Issue by jimbeveridge** [flutter/flutter#313]
Running my application on Linux on Mojo, the app asserts connecting to the Activity service. abarth said this shouldn't happen.

```
[1111/112628:ERROR:dart_error.cc(16)] Unhandled exception:
'packages/mojo/src/application_connection.dart': Failed assertion: line 84: '!proxy.impl.isBound &&
        (remoteServiceProvider != null) &&
        remoteServiceProvider.impl.isBound' is not true.
#0      _AssertionError._throwNew (dart:core-patch/errors_patch.dart:27)
#1      ApplicationConnection.requestService (packages/mojo/src/application_connection.dart:84)
#2      _Shell._connectToService (packages/flutter/src/services/shell.dart:59)
#3      _Shell.connectToService (packages/flutter/src/services/shell.dart:74)
#4      _initActivityProxy (packages/flutter/src/services/activity.dart:25)
#5      _activityProxy (packages/flutter/src/services/activity.dart:29)
#6      _activityProxy (packages/flutter/src/services/activity.dart:29)
#7      activity (packages/flutter/src/services/activity.dart:30)
#8      activity (packages/flutter/src/services/activity.dart:30)
#9      MyApp.initState (lib/main.dart:102)
#10     StatefulComponentElement._firstBuild (packages/flutter/src/widgets/framework.dart:1120)
#11     ComponentElement.mount (packages/flutter/src/widgets/framework.dart:1032)
#12     Element._inflateWidget (packages/flutter/src/widgets/framework.dart:765)
#13     Element.updateChild (packages/flutter/src/widgets/framework.dart:644)
#14     RenderObjectToWidgetElement.mount (packages/flutter/src/widgets/binding.dart:149)
#15     RenderObjectToWidgetAdapter.attachToRenderTree.<anonymous closure> (packages/flutter/src/widgets/binding.dart:117)
#16     BuildableElement.lockState (packages/flutter/src/widgets/framework.dart:924)
#17     RenderObjectToWidgetAdapter.attachToRenderTree (packages/flutter/src/widgets/binding.dart:114)
#18     WidgetFlutterBinding._runApp (packages/flutter/src/widgets/binding.dart:76)
#19     runApp (packages/flutter/src/widgets/binding.dart:83)
#20     main (lib/main.dart:209)
```

**Comment by jamesr** [comment]
Are there any other errors?  What is supposed to be providing the activity service?

**Comment by jimbeveridge** [comment]
The Activity service doesn't exist under Linux. However, the defined behavior in Flutter (according to Adam) is that connections always succeed, even if the service doesn't exist, and writing to them always succeeds. Service that aren't there just don't reply.

I already have a fix from Adam that I will create a PR for.
