### ISSUE TITLE
Firebase Messaging: crash after getToken and onMessage don't show notification.

### ISSUE THREAD

**Issue by followthemoney1** [flutter/flutter#31304]
When I call the firebaseMessaging.getToken () method, I always get the application crash, stack trace: 
```
Installing build/app/outputs/apk/app.apk...
Syncing files to device Redmi 4 Prime...
E/flutter (23484): [ERROR:flutter/shell/platform/android/platform_view_android_jni.cc(40)] java.lang.NoSuchMethodError: No virtual method getInstanceId()Lcom/google/android/gms/tasks/Task; in class Lcom/google/firebase/iid/FirebaseInstanceId; or its super classes (declaration of 'com.google.firebase.iid.FirebaseInstanceId' appears in /data/app/menus.flutterocrmenu-1/base.apk:classes17.dex)
E/flutter (23484): 	at io.flutter.plugins.firebasemessaging.FirebaseMessagingPlugin.onMethodCall(FirebaseMessagingPlugin.java:118)
E/flutter (23484): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:201)
E/flutter (23484): 	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:88)
E/flutter (23484): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:219)
E/flutter (23484): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/flutter (23484): 	at android.os.MessageQueue.next(MessageQueue.java:323)
E/flutter (23484): 	at android.os.Looper.loop(Looper.java:136)
E/flutter (23484): 	at android.app.ActivityThread.main(ActivityThread.java:6236)
E/flutter (23484): 	at java.lang.reflect.Method.invoke(Native Method)
E/flutter (23484): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:891)
E/flutter (23484): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:781)
E/flutter (23484): 
F/flutter (23484): [FATAL:flutter/shell/platform/android/platform_view_android_jni.cc(77)] Check failed: CheckException(env). 
F/libc    (23484): Fatal signal 6 (SIGABRT), code -6 in tid 23484 (.flutterocrmenu)
*** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
LineageOS Version: 'unknown'
Build fingerprint: 'Xiaomi/lineage_markw/markw:7.1.2/NJH47F/e9331b6247:userdebug/release-keys'
Revision: '0'
ABI: 'arm64'
pid: 23484, tid: 23484, name: .flutterocrmenu  >>> menus.flutterocrmenu <<<
signal 6 (SIGABRT), code -6 (SI_TKILL), fault addr --------
Abort message: '[FATAL:flutter/shell/platform/android/platform_view_android_jni.cc(77)] Check failed: CheckException(env). 
'
    x0   0000000000000000  x1   0000000000005bbc  x2   0000000000000006  x3   0000000000000008
    x4   0000000000000036  x5   0000000000008000  x6   0000007f87b6e000  x7   0000000000000000
    x8   0000000000000083  x9   ffffffffffffffdf  x10  0000000000000000  x11  0000000000000001
    x12  0000000000000018  x13  0000000000000000  x14  0000000000000000  x15  000e055ccfc11943
    x16  0000007f84fcfec8  x17  0000007f84f7906c  x18  0000000000000010  x19  0000007f87c27b40
    x20  0000000000000006  x21  0000007f87c27a98  x22  000000000000000b  x23  0000007f7a2629d0
    x24  0000000000000033  x25  0000000000000050  x26  0000000000000034  x27  0000000000000000
    x28  0000000000000001  x29  0000007ff27e5800  x30  0000007f84f76498
    sp   0000007ff27e57e0  pc   0000007f84f79074  pstate 0000000060000000
backtrace:
    #00 pc 000000000006d074  /system/lib64/libc.so (tgkill+8)
    #01 pc 000000000006a494  /system/lib64/libc.so (pthread_kill+64)
    #02 pc 0000000000024110  /system/lib64/libc.so (raise+24)
    #03 pc 000000000001c9c8  /system/lib64/libc.so (abort+52)
    #04 pc 0000000000d14354  /data/app/menus.flutterocrmenu-1/lib/arm64/libflutter.so (offset 0xd00000)
    #05 pc 0000000000d07394  /data/app/menus.flutterocrmenu-1/lib/arm64/libflutter.so (offset 0xd00000)
    #06 pc 0000000000d058b0  /data/app/menus.flutterocrmenu-1/lib/arm64/libflutter.so (offset 0xd00000)
    #07 pc 0000000000d49c84  /data/app/menus.flutterocrmenu-1/lib/arm64/libflutter.so (offset 0xd00000)
    #08 pc 0000000000d14e14  /data/app/menus.flutterocrmenu-1/lib/arm64/libflutter.so (offset 0xd00000)
    #09 pc 0000000000d18c5c  /data/app/menus.flutterocrmenu-1/lib/arm64/libflutter.so (offset 0xd00000)
    #10 pc 00000000000183a8  /system/lib64/libutils.so (_ZN7android6Looper9pollInnerEi+916)
    #11 pc 0000000000017f54  /system/lib64/libutils.so (_ZN7android6Looper8pollOnceEiPiS1_PPv+60)
    #12 pc 00000000000f22bc  /system/lib64/libandroid_runtime.so (_ZN7android18NativeMessageQueue8pollOnceEP7_JNIEnvP8_jobjecti+48)
    #13 pc 000000007533b7a0  /data/dalvik-cache/arm64/system@framework@boot.oat (offset 0x2a15000)
Lost connection to device.
Error writing "build/flutter_assets/assets/image_placeholde.jpg" to DevFS: HttpException: Connection closed before full header was received, uri = http://127.0.0.1:59597/
Error writing "build/flutter_assets/assets/logo_toolbar.png" to DevFS: HttpException: Connection closed before full header was received, uri = http://127.0.0.1:59597/
Error writing "build/flutter_assets/packages/flutter_google_places/assets/google_black.png" to DevFS: HttpException: Connection closed before full header was received, uri = http://127.0.0.1:59597/
Error writing "build/flutter_assets/packages/flutter_google_places/assets/google_white.png" to DevFS: HttpException: Connection closed before full header was received, uri = http://127.0.0.1:59597/
Error writing "build/flutter_assets/packages/cupertino_icons/assets/CupertinoIcons.ttf" to DevFS: HttpException: Connection closed before full header was received, uri = http://127.0.0.1:59597/
Error writing "build/flutter_assets/fonts/MaterialIcons-Regular.ttf" to DevFS: HttpException: Connection closed before full header was received, uri = http://127.0.0.1:59597/
Error writing "build/flutter_assets/AssetManifest.json" to DevFS: HttpException: Connection closed before full header was received, uri = http://127.0.0.1:59597/
Error writing "build/flutter_assets/FontManifest.json" to DevFS: HttpException: Connection closed before full header was received, uri = http://127.0.0.1:59597/
Error writing "build/flutter_assets/LICENSE" to DevFS: HttpException: Connection closed before full header was received, uri = http://127.0.0.1:59597/
```
but method `firebaseMessaging.onTokenRefresh` works fine.

Between this, when I try to get a notification, I always get into the `onMessage` method, but when the application is open, the notification itself does not show what could be the reason?
 
I also wanted to clarify **if you have some way to pass a bool parameter and in case of false do not show the notification, get into the `onMessage` method, but after certain actions do not show or show the notification?**

**Comment by Abgaryan** [comment]
@followthemoney1  did you found any workaround?

**Comment by followthemoney1** [comment]
@Abgaryan yep, u don't know why, but in my case I just using specific dependencies version:
``` firebase_core: ^0.3.0
  firebase_database: ^2.0.3
  firebase_auth: ^0.8.4+5
  cloud_firestore: ^0.9.13+1
  firebase_storage: ^2.1.0+1
  firebase_remote_config: ^0.1.0
  firebase_messaging: ^4.0.0+3```

**Comment by creativefull** [comment]
try ```flutter clean``` and then run again
