### ISSUE TITLE
NPE in SpriteBox.handleEvent

### ISSUE THREAD

**Issue by apwilson** [flutter/flutter#3133]
```
I/flutter : ------------------------------------------------------------------------
I/flutter : -- EXCEPTION CAUGHT BY GESTURE LIBRARY ---------------------------------
I/flutter : The following exception was raised while dispatching a pointer event:
I/flutter : The null object does not have a getter 'iterator'.
I/flutter : NoSuchMethodError: method not found: 'iterator'
I/flutter : Receiver: null
I/flutter : Arguments: []
I/flutter : Event:
I/flutter : PointerMoveEvent(Point(744.5, 162.5))
I/flutter : Target:
I/flutter : SpriteBox
I/flutter : Stack trace:
I/flutter : #0      Object._noSuchMethod (dart:core-patch/object_patch.dart:42)
I/flutter : #1      Object.noSuchMethod (dart:core-patch/object_patch.dart:45)
I/flutter : #2      SpriteBox.handleEvent (<>/flutter/packages/flutter_sprites/lib/src/sprite_box.dart:227)
I/flutter : #3      BindingBase&Scheduler&Gesturer.dispatchEvent (<>/flutter/packages/flutter/lib/src/gestures/binding.dart:98)
I/flutter : #4      BindingBase&Scheduler&Gesturer._handlePointerEvent (<>/flutter/packages/flutter/lib/src/gestures/binding.dart:72)
I/flutter : #5      BindingBase&Scheduler&Gesturer._handlePointerPacket (<>/flutter/packages/flutter/lib/src/gestures/binding.dart:44)
I/flutter : #6      _dispatchPointerPacket (file:///b/build/slave/Linux_Engine/build/src/out/android_Release/gen/sky/bindings/hooks.dart:43)
I/flutter : ------------------------------------------------------------------------
```

**Comment by abarth** [comment]
@vlidholt

**Comment by eseidelGoogle** [comment]
flutter_sprites is no longer in master.
