### ISSUE TITLE
Crash in ShaderWarmUp.execute()

### ISSUE THREAD

**Issue by giovannilattanzio** [flutter/flutter#31355]
## Steps to Reproduce

1. Start a new project (even the default one) and run it

## Logs

```
E/flutter ( 8575): [ERROR:flutter/lib/ui/ui_dart_state.cc(148)] Unhandled Exception: Exception: operation failed
E/flutter ( 8575): null
```

From **flutter analyze**

```
Analyzing prova...                                                      
No issues found! (ran in 2.3s)
```

From **flutter doctor -v**

```
[✓] Flutter (Channel beta, v1.4.9-hotfix.1, on Mac OS X 10.14.3 18D109, locale it-IT)
    • Flutter version 1.4.9-hotfix.1 at /Users/Giovanni/development/flutter
    • Framework revision 88fa7ea403 (9 days ago), 2019-04-11 14:01:46 -0700
    • Engine revision 4737fc5cd8
    • Dart version 2.2.1 (build 2.2.1-dev.4.0 None)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Library/Java/Extensions/android/library/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = /Library/Java/Extensions/android/library/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.2, Build version 10E125
    • ios-deploy 2.0.0
    • CocoaPods version 1.5.3

[!] Android Studio (version 3.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)

[✓] IntelliJ IDEA Community Edition (version 2019.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 34.0.4
    • Dart plugin version 191.6183.88

[✓] VS Code (version 1.33.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 2.24.0

[✓] Connected device (1 available)
    • Samsung Galaxy S8, 7 0 0, API 24, 1440x2960 • 192.168.56.101:5555 • android-x86 • Android 7.0 (API 24)
```

(I'm using IntelliJ as IDE, so the Android Studio issues are not a big deal)

The project seems to work just fine regardless, but it's a bit annoying to have this error popping out at the beginning.

**Comment by sejalmutha** [comment]
Is this problem solved? 
I am facing same problem

**Comment by qinAI** [comment]
Is this problem solved?
I am facing same problem

**Comment by bchauca** [comment]
Same here, after use restat app on vs code on mac osx.

**Comment by ramsestom** [comment]
Same issue with VisualStudio on Windows 10

Here is the error log output:
```
Launching lib\main.dart on SM G9350 in debug mode...
Built build\app\outputs\apk\debug\app-debug.apk.
E/flutter ( 3282): [ERROR:flutter/lib/ui/ui_dart_state.cc(148)] Unhandled Exception: Exception: operation failed
E/flutter ( 3282): #0      ShaderWarmUp.execute 
E/flutter ( 3282): <asynchronous suspension>
E/flutter ( 3282): #1      PaintingBinding.initInstances 
E/flutter ( 3282): #2      SemanticsBinding.initInstances 
E/flutter ( 3282): #3      RendererBinding.initInstances 
E/flutter ( 3282): #4      WidgetsBinding.initInstances 
E/flutter ( 3282): #5      new BindingBase 
E/flutter ( 3282): #6      new _WidgetsFlutterBinding&BindingBase&GestureBinding (package:flutter/src/widgets/binding.dart)
E/flutter ( 3282): #7      new _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding (package:flutter/src/widgets/binding.dart)
E/flutter ( 3282): #8      new _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding (package:flutter/src/widgets/binding.dart)
E/flutter ( 3282): #9      new _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding (package:flutter/src/widgets/binding.dart)
E/flutter ( 3282): #10     new _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding (package:flutter/src/widgets/binding.dart)
E/flutter ( 3282): #11     new _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding (package:flutter/src/widgets/binding.dart)
E/flutter ( 3282): #12     new _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding&WidgetsBinding (package:flutter/src/widgets/binding.dart)
E/flutter ( 3282): #13     new WidgetsFlutterBinding (package:flutter/src/widgets/binding.dart)
E/flutter ( 3282): #14     WidgetsFlutterBinding.ensureInitialized 
E/flutter ( 3282): #15     runApp 
E/flutter ( 3282): #16     main
E/flutter ( 3282): #17     _runMainZoned.<anonymous closure>.<anonymous closure>  (dart:ui/hooks.dart:229:25)
E/flutter ( 3282): #18     _rootRun  (dart:async/zone.dart:1124:13)
E/flutter ( 3282): #19     _CustomZone.run  (dart:async/zone.dart:1021:19)
E/flutter ( 3282): #20     _runZoned  (dart:async/zone.dart:1516:10)
E/flutter ( 3282): #21     runZoned  (dart:async/zone.dart:1500:12)
E/flutter ( 3282): #22     _runMainZoned.<anonymous closure>  (dart:ui/hooks.dart:221:5)
E/flutter ( 3282): #23     _startIsolate.<anonymous closure>  (dart:isolate-patch/isolate_patch.dart:305:19)
E/flutter ( 3282): #24     _RawReceivePortImpl._handleMessage  (dart:isolate-patch/isolate_patch.dart:172:12)
E/flutter ( 3282):
Reloaded 1 of 468 libraries in 485ms.
```
and it occurs at initialisation of the flutter app (at this line of code):
`void main() => runApp(new MyApp());`

**Comment by yrom** [comment]
Same issue here. But it was occured in production app on the user device. I have no idea to reproduce.

The logs:
```
1 #0 ShaderWarmUp.execute (package:flutter/src/painting/shader_warm_up.dart:90)
2 <asynchronous suspension>
3 #1 PaintingBinding.initInstances (package:flutter/src/painting/binding.dart:25)
4 #2 SemanticsBinding.initInstances (package:flutter/src/semantics/binding.dart:22)
5 #3 RendererBinding.initInstances (package:flutter/src/rendering/binding.dart:29)
6 #4 WidgetsBinding.initInstances (package:flutter/src/widgets/binding.dart:252)
7 #5 new BindingBase. (package:flutter/src/foundation/binding.dart:56)
8 #6 new _WidgetsFlutterBinding&BindingBase&GestureBinding. (package:flutter/src/widgets/binding.dart:0)
9 #7 new _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding. (package:flutter/src/widgets/binding.dart:0)
10 #8 new _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding. (package:flutter/src/widgets/binding.dart:0)
11 #9 new _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding. (package:flutter/src/widgets/binding.dart:0)
12 #10 new _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding. (package:flutter/src/widgets/binding.dart:0)
13 #11 new _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding. (package:flutter/src/widgets/binding.dart:0)
14 #12 new _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding&WidgetsBinding. (package:flutter/src/widgets/binding.dart:0)
15 #13 new WidgetsFlutterBinding. (package:flutter/src/widgets/binding.dart:0)
16 #14 WidgetsFlutterBinding.ensureInitialized (package:flutter/src/widgets/binding.dart:1053)
17 #15 main.<anonymous closure>
18 #18 _runZoned (dart:async/zone.dart:1516)
19 #19 runZoned (dart:async/zone.dart:1500)
20 #20 main (package:peppersoup/main.dart:17)
21 #21 _runMainZoned.<anonymous closure>.<anonymous closure> (dart:ui/hooks.dart:229)
22 #24 _runZoned (dart:async/zone.dart:1516)
23 #25 runZoned (dart:async/zone.dart:1500)
24 #26 _runMainZoned.<anonymous closure> (dart:ui/hooks.dart:221)
25 #27 _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:305)
26 #28 _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172)
```
Device: google Pixel 2, Android 5.1.1

Flutter version is `1.9.1+hotfix.4`

**Comment by HansMuller** [comment]
I'm running into this, with the current build.  The following trivial app crashes as reported earlier. It displays what's expected.

CC @liyuqian 

```dart
import 'package:flutter/material.dart';

class Home extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    const String logoAsset = 'images/logo.png';
    return Scaffold(
     Padding(
        padding: EdgeInsets.all(64),
        child: Image.asset(logoAsset),
      ),
    );
  }
}

void main() {
  runApp(MaterialApp(home: Home()));
}
```

The pubspec.yaml contains
```json
flutter:
  assets:
    - images/logo.png
```

And [images/logo.png is from pixabay](https://pixabay.com/illustrations/mountain-icon-sign-design-symbol-1849091/)

![logo](https://user-images.githubusercontent.com/1377460/68610751-53acc780-046d-11ea-98ab-af0020a7d199.png)

```
E/flutter ( 4605): [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: Exception: operation failed
E/flutter ( 4605): #0      ShaderWarmUp.execute (package:flutter/src/painting/shader_warm_up.dart:90:5)
E/flutter ( 4605): <asynchronous suspension>
E/flutter ( 4605): #1      PaintingBinding.initInstances (package:flutter/src/painting/binding.dart:25:20)
E/flutter ( 4605): #2      SemanticsBinding.initInstances (package:flutter/src/semantics/binding.dart:22:11)
E/flutter ( 4605): #3      RendererBinding.initInstances (package:flutter/src/rendering/binding.dart:29:11)
E/flutter ( 4605): #4      WidgetsBinding.initInstances (package:flutter/src/widgets/binding.dart:253:11)
E/flutter ( 4605): #5      new BindingBase (package:flutter/src/foundation/binding.dart:56:5)
E/flutter ( 4605): #6      new _WidgetsFlutterBinding&BindingBase&GestureBinding (package:flutter/src/widgets/binding.dart)
E/flutter ( 4605): #7      new _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding (package:flutter/src/widgets/binding.dart)
E/flutter ( 4605): #8      new _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding (package:flutter/src/widgets/binding.dart)
E/flutter ( 4605): #9      new _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding (package:flutter/src/widgets/binding.dart)
E/flutter ( 4605): #10     new _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding (package:flutter/src/widgets/binding.dart)
E/flutter ( 4605): #11     new _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding (package:flutter/src/widgets/binding.dart)
E/flutter ( 4605): #12     new _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding&WidgetsBinding (package:flutter/src/widgets/binding.dart)
E/flutter ( 4605): #13     new WidgetsFlutterBinding (package:flutter/src/widgets/binding.dart)
E/flutter ( 4605): #14     WidgetsFlutterBinding.ensureInitialized (package:flutter/src/widgets/binding.dart:1083:7)
E/flutter ( 4605): #15     runApp (package:flutter/src/widgets/binding.dart:868:25)
E/flutter ( 4605): #16     main (package:test_issue/main.dart:24:3)
E/flutter ( 4605): #17     _runMainZoned.<anonymous closure>.<anonymous closure> (dart:ui/hooks.dart:239:25)
E/flutter ( 4605): #18     _rootRun (dart:async/zone.dart:1124:13)
E/flutter ( 4605): #19     _CustomZone.run (dart:async/zone.dart:1021:19)
E/flutter ( 4605): #20     _runZoned (dart:async/zone.dart:1516:10)
E/flutter ( 4605): #21     runZoned (dart:async/zone.dart:1500:12)
E/flutter ( 4605): #22     _runMainZoned.<anonymous closure> (dart:ui/hooks.dart:231:5)
E/flutter ( 4605): #23     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:305:19)
E/flutter ( 4605): #24     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:12)
E/flutter ( 4605):
Syncing files to device Pixel 2...
 7,678ms (!)
```
I'm running the app on an Android device

```
 flutter doctor -v
[✓] Flutter (Channel master, v1.10.16-pre.114, on Linux, locale en_US.UTF-8)
    • Flutter version 1.10.16-pre.114 at /usr/local/google/home/hansmuller/github/flutter
    • Framework revision 20169f0d2f (79 minutes ago), 2019-11-11 12:08:17 -0500
    • Engine revision eec36a8d4f
    • Dart version 2.7.0
...

[✓] Connected device (1 available)
    • Pixel 2 • FA79D1A03597 • android-arm64 • Android 10 (API 29)
```

**Comment by liyuqian** [comment]
Thank @jason-simmons for voluntarily taking a look into this!

**Comment by jason-simmons** [comment]
This regressed due to https://github.com/flutter/engine/commit/2dcfaaeb5d3caee2bf7488e90abadf0456f43922

@cyanglaz

**Comment by liyuqian** [comment]
Thank you @jason-simmons for the quick fix! @cyanglaz : do you think it's possible to come up with a unit test that would fail before Jason's fix, and pass after that? It would be nice to have such a test to guard future regressions like this one.

**Comment by DIGITALSQUAD** [comment]
Still facing this issue with Flutter 1.12.13+hotfix.8 and Dart 2.7.0
Any updates?

```
D/FlutterActivity( 4873): Using the launch theme as normal theme.
D/FlutterActivityAndFragmentDelegate( 4873): Setting up FlutterEngine.
D/FlutterActivityAndFragmentDelegate( 4873): No preferred FlutterEngine was provided. Creating a new FlutterEngine for this FlutterFragment.
D/FlutterActivityAndFragmentDelegate( 4873): Attaching FlutterEngine to the Activity that owns this Fragment.
D/FlutterView( 4873): Attaching to a FlutterEngine: io.flutter.embedding.engine.FlutterEngine@b686a8c
D/FlutterActivityAndFragmentDelegate( 4873): Executing Dart entrypoint: main, and sending initial route: /
E/flutter ( 4873): [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: Exception: operation failed
E/flutter ( 4873): #0      ShaderWarmUp.execute (package:flutter/src/painting/shader_warm_up.dart:90:5)
E/flutter ( 4873): <asynchronous suspension>
E/flutter ( 4873): #1      PaintingBinding.initInstances (package:flutter/src/painting/binding.dart:25:20)
E/flutter ( 4873): #2      SemanticsBinding.initInstances (package:flutter/src/semantics/binding.dart:22:11)
E/flutter ( 4873): #3      RendererBinding.initInstances (package:flutter/src/rendering/binding.dart:29:11)
E/flutter ( 4873): #4      WidgetsBinding.initInstances (package:flutter/src/widgets/binding.dart:253:11)
E/flutter ( 4873): #5      new BindingBase (package:flutter/src/foundation/binding.dart:56:5)
E/flutter ( 4873): #6      new _WidgetsFlutterBinding&BindingBase&GestureBinding (package:flutter/src/widgets/binding.dart)
E/flutter ( 4873): #7      new _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding (package:flutter/src/widgets/binding.dart)
E/flutter ( 4873): #8      new _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding (package:flutter/src/widgets/binding.dart)
E/flutter ( 4873): #9      new _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding (package:flutter/src/widgets/binding.dart)
E/flutter ( 4873): #10     new _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding (package:flutter/src/widgets/binding.dart)
E/flutter ( 4873): #11     new _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding (package:flutter/src/widgets/binding.dart)
E/flutter ( 4873): #12     new _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding&WidgetsBinding (package:flutter/src/widgets/binding.dart)
E/flutter ( 4873): #13     new WidgetsFlutterBinding (package:flutter/src/widgets/binding.dart)
E/flutter ( 4873): #14     WidgetsFlutterBinding.ensureInitialized (package:flutter/src/widgets/binding.dart:1083:7)
E/flutter ( 4873): #15     runApp (package:flutter/src/widgets/binding.dart:868:25)
E/flutter ( 4873): #16     main (package:my_bootstrap/main.dart:3:16)
E/flutter ( 4873): #17     _runMainZoned.<anonymous closure>.<anonymous closure> (dart:ui/hooks.dart:239:25)
E/flutter ( 4873): #18     _rootRun (dart:async/zone.dart:1126:13)
E/flutter ( 4873): #19     _CustomZone.run (dart:async/zone.dart:1023:19)
E/flutter ( 4873): #20     _runZoned (dart:async/zone.dart:1518:10)
E/flutter ( 4873): #21     runZoned (dart:async/zone.dart:1502:12)
E/flutter ( 4873): #22     _runMainZoned.<anonymous closure> (dart:ui/hooks.dart:231:5)
E/flutter ( 4873): #23     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:307:19)
E/flutter ( 4873): #24     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:174:12)
E/flutter ( 4873):
```

**Comment by liyuqian** [comment]
@DIGITALSQUAD : this issue should have been fixed by https://github.com/flutter/engine/pull/13785 and https://github.com/flutter/engine/pull/13812. Maybe it's a new issue. Can you please share the detailed steps to reproduce this error? For example, output of `flutter doctor -v`, the device/emulator you used, and a minimal Flutter app would be helpful.

**Comment by DIGITALSQUAD** [comment]
@liyuqian thanks for your reply. 
The emulator(Google Pixel 2) is predefined device on Genymotion.
**flutter doctor -v**
```
[✓] Flutter (Channel stable, v1.12.13+hotfix.8, on Mac OS X 10.14.6 18G95, locale ja-JP)
    • Flutter version 1.12.13+hotfix.8 at /Developer/flutter
    • Framework revision 0b8abb4724 (2 weeks ago), 2020-02-11 11:44:36 -0800
    • Engine revision e1e6ced81d
    • Dart version 2.7.0


[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/tahara_satoshi/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 28.0.3
    • ANDROID_HOME = /Users/tahara_satoshi/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.2.1, Build version 11B53
    • CocoaPods version 1.8.0

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 43.0.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] VS Code (version 1.42.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.8.0

[✓] Connected device (1 available)
    • Google Pixel 2 • 192.168.57.101:5555 • android-x86 • Android 9 (API 28)

• No issues found!
```

**Comment by liyuqian** [comment]
@DIGITALSQUAD : Genymotion reminds me of https://github.com/flutter/flutter/issues/39828. Can you please try running on a qemu_system-x86_64 emulator (from Android studio)?

**Comment by DIGITALSQUAD** [comment]
@liyuqian You're right. Works fine on qemu_system-x86_64 emulator. Thanks a lot.
