### ISSUE TITLE
PageStorage unreachable on showDialog?

### ISSUE THREAD

**Issue by madqueendany** [flutter/flutter#31381]
It seems that the PageStorage widget doesn't reach the dialog context.

## Steps to Reproduce

1. Create a basic application
2. Wrap the `Scaffold`'s `body` with a PageStorage (provide `PageStorageKey` and `...bucket` 
3. Add some data to the bucket using `_pageStorageBucket.writeState(...)`
4. Access the data on the Body widget via `PageStorage.of(context).readState(...)`
5. Add a button on the Body widget that will show a dialog when `pressed`
6. On the builder of that dialog, read the state again.
7. Consult the [gist](https://gist.github.com/kevinespaldon/ddce83099145c30c407b4338366ac6e2) for more info.

## Logs

```
[  +27 ms] executing: [mydirectory] git rev-parse --abbrev-ref --symbolic @{u}
[  +34 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/stable
[        ] executing: [mydirectory] git rev-parse --abbrev-ref HEAD
[   +7 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] stable
[        ] executing: [mydirectory] git ls-remote --get-url origin
[   +7 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[        ] executing: [mydirectory] git log -n 1 --pretty=format:%H
[  +10 ms] Exit code 0 from: git log -n 1 --pretty=format:%H
[        ] 8661d8aecd626f7f57ccbcb735553edc05a2e713
[        ] executing: [mydirectory] git log -n 1 --pretty=format:%ar
[  +12 ms] Exit code 0 from: git log -n 1 --pretty=format:%ar
[        ] 9 weeks ago
[   +1 ms] executing: [mydirectory] git describe --match v*.*.* --first-parent --long --tags
[  +14 ms] Exit code 0 from: git describe --match v*.*.* --first-parent --long --tags
[        ] v1.2.1-0-g8661d8aec
[ +296 ms] executing: /usr/Library/Android/sdk/platform-tools/adb devices -l
[  +10 ms] Exit code 0 from: /usr/Library/Android/sdk/platform-tools/adb devices -l
[        ] List of devices attached
[   +5 ms] executing: idevice_id -h
[  +38 ms] /usr/bin/xcrun simctl list --json devices
[ +215 ms] More than one device connected; please specify a device with the '-d <deviceId>' flag, or use '-d all' to act on all devices.
[   +6 ms] iPhone 5s     • 22892DF4-5CD3-4DE9-8CA9-3F5B0268B82F • ios • com.apple.CoreSimulator.SimRuntime.iOS-12-2 (simulator)
[        ] iPhone Xs Max • 64FE21E8-B354-4C50-BB3B-DE40350BFA1D • ios • com.apple.CoreSimulator.SimRuntime.iOS-12-2 (simulator)
[  +11 ms] "flutter run" took 507ms.
[        ] "flutter run" took 507ms.

#0      throwToolExit (package:flutter_tools/src/base/common.dart:24:3)
#1      RunCommand.validateCommand (package:flutter_tools/src/commands/run.dart:240:7)
<asynchronous suspension>
#2      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:525:11)
<asynchronous suspension>
#3      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:482:33)
<asynchronous suspension>
#4      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:142:29)
<asynchronous suspension>
#5      _rootRun (dart:async/zone.dart:1124:13)
#6      _CustomZone.run (dart:async/zone.dart:1021:19)
#7      _runZoned (dart:async/zone.dart:1516:10)
#8      runZoned (dart:async/zone.dart:1463:12)
#9      AppContext.run (package:flutter_tools/src/base/context.dart:141:18)
<asynchronous suspension>
#10     FlutterCommand.run (package:flutter_tools/src/runner/flutter_command.dart:473:20)
#11     CommandRunner.runCommand (package:args/command_runner.dart:196:27)
<asynchronous suspension>
#12     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:396:21)
<asynchronous suspension>
#13     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:142:29)
<asynchronous suspension>
#14     _rootRun (dart:async/zone.dart:1124:13)
#15     _CustomZone.run (dart:async/zone.dart:1021:19)
#16     _runZoned (dart:async/zone.dart:1516:10)
#17     runZoned (dart:async/zone.dart:1463:12)
#18     AppContext.run (package:flutter_tools/src/base/context.dart:141:18)
<asynchronous suspension>
#19     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:356:19)
<asynchronous suspension>
#20     CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:111:29)
#21     new Future.sync (dart:async/future.dart:224:31)
#22     CommandRunner.run (package:args/command_runner.dart:111:11)
#23     FlutterCommandRunner.run (package:flutter_tools/src/runner/flutter_command_runner.dart:242:18)
#24     run.<anonymous closure> (package:flutter_tools/runner.dart:60:20)
<asynchronous suspension>
#25     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:142:29)
<asynchronous suspension>
#26     _rootRun (dart:async/zone.dart:1124:13)
#27     _CustomZone.run (dart:async/zone.dart:1021:19)
#28     _runZoned (dart:async/zone.dart:1516:10)
#29     runZoned (dart:async/zone.dart:1463:12)
#30     AppContext.run (package:flutter_tools/src/base/context.dart:141:18)
<asynchronous suspension>
#31     runInContext (package:flutter_tools/src/context_runner.dart:48:24)
<asynchronous suspension>
#32     run (package:flutter_tools/runner.dart:51:10)
#33     main (package:flutter_tools/executable.dart:52:9)
<asynchronous suspension>
#34     main (file://mydirectorypackages/flutter_tools/bin/flutter_tools.dart:8:3)
#35     _startIsolate.<anonymous closure> (dart:isolate/runtime/libisolate_patch.dart:298:32)
#36     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:171:12)
```

```
Analyzing page_storage_on_dialogs...                                    
No issues found! (ran in 1.7s)
```

```
[✓] Flutter (Channel stable, v1.2.1, on Mac OS X 10.14.3 18D109, locale en-AE)
    • Flutter version 1.2.1 at /Users/kevinespaldon/Development/flutter
    • Framework revision 8661d8aecd (9 weeks ago), 2019-02-14 19:19:53 -0800
    • Engine revision 3757390fa4
    • Dart version 2.1.2 (build 2.1.2-dev.0.0 0a7dcf17eb)

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/kevinespaldon/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.2.1, Build version 10E1001
    • ios-deploy 1.9.4
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 32.0.1
    • Dart plugin version 182.5124
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)

[✓] VS Code (version 1.33.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 2.25.1

[✓] Connected device (2 available)
    • iPhone 5s     • 22892DF4-5CD3-4DE9-8CA9-3F5B0268B82F • ios • com.apple.CoreSimulator.SimRuntime.iOS-12-2 (simulator)
    • iPhone Xs Max • 64FE21E8-B354-4C50-BB3B-DE40350BFA1D • ios • com.apple.CoreSimulator.SimRuntime.iOS-12-2 (simulator)

• No issues found!
```

**Comment by TahaTesser** [comment]
Hi @madqueendany 
Are you still experiencing this issue with latest stable?
If yes, can you please provide your `flutter doctor -v` and `flutter run --verbose`? 
Also, to better address the issue, would be helpful if you could post a minimal code sample to reproduce the problem
Thank you

**Comment by madqueendany** [comment]
Hi @TahaTesser, It has been a while since I faced this issue and I've since moved on and found a different approach.

**Comment by TahaTesser** [comment]
Hi @madqueendany 
given your last message I feel safe to close this issue,
if you disagree please write in the comments and I will reopen it. 
Thank you
