### ISSUE TITLE
Cannot use RawDatagramSocket broadcast in android hotspot mode

### ISSUE THREAD

**Issue by devxpy** [flutter/flutter#31428]
**Steps to reproduce**

- Grab your android device
- Turn off mobile data
- Turn on hostpot
- Run the following code:-

```dart
final sock = await RawDatagramSocket.bind(InternetAddress.anyIPv4, 0);
sock.broadcastEnabled = true;

print(await sock.send([0], InternetAddress("255.255.255.255"), 5046));

await sock.listen(
  (event) {
    print(event);
  },
  onError: (e) {
    throw e;
  }
);
```

**Expected result**

The devices connected to the hotspot receive the datagram I sent

**Actual result**

```
I/flutter ( 7344): 0
E/flutter ( 7344): [ERROR:flutter/lib/ui/ui_dart_state.cc(148)] Unhandled Exception: SocketException: Send failed (OS Error: Network is unreachable, errno = 101), address = 0.0.0.0, port = 0
E/flutter ( 7344): #0      main.<anonymous closure> (package:meghshala_app_flutter/main.dart:38:5)
E/flutter ( 7344): #1      _rootRunUnary (dart:async/zone.dart:1132:38)
E/flutter ( 7344): #2      _CustomZone.runUnary (dart:async/zone.dart:1029:19)
E/flutter ( 7344): #3      _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
E/flutter ( 7344): #4      _BufferingStreamSubscription._sendError.sendError (dart:async/stream_impl.dart:358:15)
E/flutter ( 7344): #5      _BufferingStreamSubscription._sendError (dart:async/stream_impl.dart:373:16)
E/flutter ( 7344): #6      _DelayedError.perform (dart:async/stream_impl.dart:602:14)
E/flutter ( 7344): #7      _StreamImplEvents.handleNext (dart:async/stream_impl.dart:707:11)
E/flutter ( 7344): #8      _PendingEvents.schedule.<anonymous closure> (dart:async/stream_impl.dart:667:7)
E/flutter ( 7344): #9      _rootRun (dart:async/zone.dart:1120:38)
E/flutter ( 7344): #10     _CustomZone.run (dart:async/zone.dart:1021:19)
E/flutter ( 7344): #11     _CustomZone.runGuarded (dart:async/zone.dart:923:7)
E/flutter ( 7344): #12     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:963:23)
E/flutter ( 7344): #13     _rootRun (dart:async/zone.dart:1124:13)
E/flutter ( 7344): #14     _CustomZone.run (dart:async/zone.dart:1021:19)
E/flutter ( 7344): #15     _CustomZone.runGuarded (dart:async/zone.dart:923:7)
E/flutter ( 7344): #16     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:963:23)
E/flutter ( 7344): #17     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
E/flutter ( 7344): #18     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
E/flutter ( 7344): 
I/flutter ( 7344): RawSocketEvent.closed
```

---

**Why do I need this?**

Because I want my application to be able to broadcast to other devices on the hotspot that it has created, without having an internet connection.

---

<details>
<summary> 
$ flutter doctor -v
</summary>

```
[✓] Flutter (Channel stable, v1.2.1, on Mac OS X 10.14.4 18E226, locale en)
    • Flutter version 1.2.1 at /Users/dev/Tools/flutter
    • Framework revision 8661d8aecd (10 weeks ago), 2019-02-14 19:19:53 -0800
    • Engine revision 3757390fa4
    • Dart version 2.1.2 (build 2.1.2-dev.0.0 0a7dcf17eb)

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/dev/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Users/dev/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/182.5314842/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.2.1, Build version 10E1001
    • ios-deploy 1.9.4
    • CocoaPods version 1.7.0.beta.3

[✓] Android Studio (version 3.3)
    • Android Studio at /Users/dev/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/182.5314842/Android Studio.app/Contents
    • Flutter plugin version 34.0.1
    • Dart plugin version 182.5215
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)

[✓] Connected device (1 available)
    • Nexus 5 • 0553a8d90a662209 • android-arm • Android 7.1.2 (API 25)

• No issues found!

```

</details>

**Comment by iapicca** [comment]
Hi @devxpy  
are you still experiencing this issue with the latest stable version of flutter?
thank you

**Comment by VladyslavBondarenko** [comment]
The issue is already long time not active and without answer.
Could everyone who still has this problem please file a new issue with the exact descriptions what happens, minimal reproducible sample code, logs and the output of `flutter doctor -v` please.
