### ISSUE TITLE
FirebaseAuthplugin causing "Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '*** -[__NSDictionaryM setObject:forKey:]: object cannot be nil"

### ISSUE THREAD

**Issue by molundb** [flutter/flutter#31481]
Hello, I am having some trouble with the FirebaseAuth package. Whenever I run the app I get `Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '*** -[__NSDictionaryM setObject:forKey:]: object cannot be nil"`

I am sorry, I don't know how to reproduce this problem; I have been having it for a while now and before it I had other errors. I am using firebase_auth: ^0.8.4+2.

If I craete a new project and cop lib, pubspec.yaml and GoogleService-Info.plist to it it builds.

I'd be extremely grateful for any help!

Dependencies in pubspec.yaml: 
```
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cloud_firestore: ^0.9.0
  firebase_analytics: ^2.0.0
  rxdart: ^0.19.0
  cached_network_image: ^0.5.1
  firebase_auth: ^0.8.4+2
  intl: ^0.15.7               
  http: ^0.12.0
  shared_preferences: ^0.4.3
  share: ^0.5.3
  flutter_webview_plugin: ^0.3.1
  mailer: ^2.1.2
  flutter_launcher_icons: ^0.7.0
  package_info: ^0.4.0
  flutter_circular_chart: ^0.1.0
  dots_indicator: ^0.0.4
  url_launcher: 4.2.0+1
  webview_flutter: ^0.3.4
  connectivity: ^0.4.2
  vibrate: ^0.0.4
  devicelocale: ^0.1.1
  firebase_core: 0.3.1+1
```

## Logs

flutter run -v
```
nw_socket_handle_socket_event [C2.1:3] Socket received CONNECTED event
[        ] [DEVICE LOG] 2019-04-23 12:18:31.784597+0200  localhost Runner[14797]: (libnetwork.dylib) [com.apple.network:]
nw_endpoint_flow_protocol_connected [C2.1 216.58.211.10:443 in_progress socket-flow (satisfied)] Transport protocol connected
[   +2 ms] [DEVICE LOG] 2019-04-23 12:18:31.787232+0200  localhost Runner[14797]: (CFNetwork) TIC TLS Event [2:0x60000078a280]: 1, Pending(0)
[  +12 ms] [DEVICE LOG] 2019-04-23 12:18:31.800924+0200  localhost Runner[14797]: (CFNetwork) TIC TLS Event [2:0x60000078a280]: 11, Pending(0)
[        ] [DEVICE LOG] 2019-04-23 12:18:31.801241+0200  localhost Runner[14797]: (CFNetwork) TIC TLS Event [2:0x60000078a280]: 14, Pending(0)
[  +26 ms] [DEVICE LOG] 2019-04-23 12:18:31.824838+0200  localhost Runner[14797]: (CoreFoundation) *** Terminating app due to uncaught exception
'NSInvalidArgumentException', reason: '*** -[__NSDictionaryM setObject:forKey:]: object cannot be nil (key: 0)'
[        ] [DEVICE LOG] *** First throw call stack:
[        ] [DEVICE LOG] (
[        ] [DEVICE LOG] 	0   CoreFoundation                      0x000000010cf236fb __exceptionPreprocess + 331
[        ] [DEVICE LOG] 	1   libobjc.A.dylib                     0x000000010c4c7ac5 objc_exception_throw + 48
[        ] [DEVICE LOG] 	2   CoreFoundation                      0x000000010ce71ddc _CFThrowFormattedException + 194
[        ] [DEVICE LOG] 	3   CoreFoundation                      0x000000010cf929d6 -[__NSDictionaryM setObject:forKey:] + 1046
[        ] [DEVICE LOG] 	4   Runner                              0x00000001073156e0 -[FLTFirebaseAuthPlugin handleMethodCall:result:] + 15616
[        ] [DEVICE LOG] 	5   Flutter                             0x00000001092b27ba __45-[FlutterMethodChannel
setMethodCallHandler:]_block_invoke + 115
[        ] [DEVICE LOG] 	6   Flutter                             0x00000001092cf4ac
_ZNK5shell21PlatformMessageRouter21HandlePlatformMessageEN3fml6RefPtrIN5blink15PlatformMessageEEE + 166
[        ] [DEVICE LOG] 	7   Flutter                             0x00<…>
[   +9 ms] *** First throw call stack:
[        ] (
[        ] 	0   CoreFoundation                      0x000000010cf236fb __exceptionPreprocess + 331
[        ] 	1   libobjc.A.dylib                     0x000000010c4c7ac5 objc_exception_throw + 48
[        ] 	2   CoreFoundation                      0x000000010ce71ddc _CFThrowFormattedException + 194
[        ] 	3   CoreFoundation                      0x000000010cf929d6 -[__NSDictionaryM setObject:forKey:] + 1046
[        ] 	4   Runner                              0x00000001073156e0 -[FLTFirebaseAuthPlugin handleMethodCall:result:] + 15616
[        ] 	5   Flutter                             0x00000001092b27ba __45-[FlutterMethodChannel setMethodCallHandler:]_block_invoke + 115
[        ] 	6   Flutter                             0x00000001092cf4ac
_ZNK5shell21PlatformMessageRouter21HandlePlatformMessageEN3fml6RefPtrIN5blink15PlatformMessageEEE + 166
[        ] 	7   Flutter                             0x00<…>
[   +2 ms] Service protocol connection closed.
[        ] Lost connection to device.
[ +183 ms] Syncing files to device iPhone 6...
[   +1 ms] DevFS: Starting sync from LocalDirectory: '/Users/martinlundberg/AndroidStudioProjects/tlycs_flutter'
[        ] Scanning project files
[  +17 ms] Scanning package files
[ +140 ms] Scanning asset files
[  +12 ms] Scanning for deleted files
[  +18 ms] Compiling dart to kernel with 824 updated files
[   +8 ms] /Users/martinlundberg/Dev/flutter/bin/cache/dart-sdk/bin/dart
/Users/martinlundberg/Dev/flutter/bin/cache/artifacts/engine/darwin-x64/frontend_server.dart.snapshot --sdk-root
/Users/martinlundberg/Dev/flutter/bin/cache/artifacts/engine/common/flutter_patched_sdk/ --incremental --strong --target=flutter --output-dill
build/app.dill --packages /Users/martinlundberg/AndroidStudioProjects/tlycs_flutter/.packages --filesystem-scheme org-dartlang-root
[+1613 ms] Updating files
[   +8 ms] DevFS sync failed. Lost connection to device: SocketException: OS Error: Connection refused, errno = 61, address = 127.0.0.1, port =
52856
[        ] Syncing files to device iPhone 6... (completed in 1,822ms)
[   +1 ms] "flutter run" took 150,878ms.
[        ] "flutter run" took 150,878ms.

#0      throwToolExit (package:flutter_tools/src/base/common.dart:24:3)
#1      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:411:7)
<asynchronous suspension>
#2      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:545:18)
#3      _asyncThenWrapperHelper.<anonymous closure> (dart:async/runtime/libasync_patch.dart:77:64)
#4      _rootRunUnary (dart:async/zone.dart:1132:38)
#5      _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#6      _FutureListener.handleValue (dart:async/future_impl.dart:126:18)
#7      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:639:45)
#8      Future._propagateToListeners (dart:async/future_impl.dart:668:32)
#9      Future._complete (dart:async/future_impl.dart:473:7)
#10     _SyncCompleter.complete (dart:async/future_impl.dart:51:12)
#11     _AsyncAwaitCompleter.complete (dart:async/runtime/libasync_patch.dart:28:18)
#12     _completeOnAsyncReturn (dart:async/runtime/libasync_patch.dart:294:13)
#13     RunCommand.usageValues (package:flutter_tools/src/commands/run.dart)
#14     _asyncThenWrapperHelper.<anonymous closure> (dart:async/runtime/libasync_patch.dart:77:64)
#15     _rootRunUnary (dart:async/zone.dart:1132:38)
#16     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#17     _FutureListener.handleValue (dart:async/future_impl.dart:126:18)
#18     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:639:45)
#19     Future._propagateToListeners (dart:async/future_impl.dart:668:32)
#20     Future._complete (dart:async/future_impl.dart:473:7)
#21     _SyncCompleter.complete (dart:async/future_impl.dart:51:12)
#22     _AsyncAwaitCompleter.complete.<anonymous closure> (dart:async/runtime/libasync_patch.dart:33:20)
#23     _rootRun (dart:async/zone.dart:1124:13)
#24     _CustomZone.run (dart:async/zone.dart:1021:19)
#25     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:947:23)
#26     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#27     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#28     _runPendingImmediateCallback (dart:isolate/runtime/libisolate_patch.dart:115:13)
#29     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:172:5)
```

flutter analyze
```
   info • The class 'Stream' was not exported from 'dart:core' until version 2.1, but this code is required to be able to run on earlier versions
          • lib/blocs/CommunityImpactBloc.dart:10:3 • sdk_version_async_exported_from_core
   info • The class 'Stream' was not exported from 'dart:core' until version 2.1, but this code is required to be able to run on earlier versions
          • lib/blocs/GlobalGoalsBloc.dart:9:3 • sdk_version_async_exported_from_core
   info • The method '_getFirstImpacts' isn't used • lib/blocs/GlobalGoalsBloc.dart:121:16 • unused_element
   info • The value of the field '_iconBgPath' isn't used • lib/models/Charity.dart:15:10 • unused_field
   info • Unused import: 'package:tlycs_flutter/util/constants.dart' • lib/models/Impact.dart:4:8 • unused_import
   info • Avoid wrapping fields in getters and setters just to be "safe" • lib/models/PaymentCard.dart:17:14 • unnecessary_getters_setters
   info • Avoid wrapping fields in getters and setters just to be "safe" • lib/models/PaymentCard.dart:22:7 • unnecessary_getters_setters
   info • The class 'Future' was not exported from 'dart:core' until version 2.1, but this code is required to be able to run on earlier versions
          • lib/providers/AuthImpl.dart:8:3 • sdk_version_async_exported_from_core
   info • The class 'Future' was not exported from 'dart:core' until version 2.1, but this code is required to be able to run on earlier versions
          • lib/providers/AuthImpl.dart:11:3 • sdk_version_async_exported_from_core
   info • The class 'Future' was not exported from 'dart:core' until version 2.1, but this code is required to be able to run on earlier versions
          • lib/providers/AuthImpl.dart:13:3 • sdk_version_async_exported_from_core
   info • The class 'Future' was not exported from 'dart:core' until version 2.1, but this code is required to be able to run on earlier versions
          • lib/providers/AuthImpl.dart:15:3 • sdk_version_async_exported_from_core
   info • The class 'Future' was not exported from 'dart:core' until version 2.1, but this code is required to be able to run on earlier versions
          • lib/providers/AuthImpl.dart:17:3 • sdk_version_async_exported_from_core
   info • The class 'Future' was not exported from 'dart:core' until version 2.1, but this code is required to be able to run on earlier versions
          • lib/providers/AuthImpl.dart:19:3 • sdk_version_async_exported_from_core
   info • The class 'Future' was not exported from 'dart:core' until version 2.1, but this code is required to be able to run on earlier versions
          • lib/providers/AuthImpl.dart:21:3 • sdk_version_async_exported_from_core
   info • The class 'Future' was not exported from 'dart:core' until version 2.1, but this code is required to be able to run on earlier versions
          • lib/providers/AuthImpl.dart:23:3 • sdk_version_async_exported_from_core
   info • The class 'Stream' was not exported from 'dart:core' until version 2.1, but this code is required to be able to run on earlier versions
          • lib/providers/AuthImpl.dart:25:3 • sdk_version_async_exported_from_core
   info • The class 'Future' was not exported from 'dart:core' until version 2.1, but this code is required to be able to run on earlier versions
          • lib/providers/AuthImpl.dart:27:3 • sdk_version_async_exported_from_core
   info • The class 'Future' was not exported from 'dart:core' until version 2.1, but this code is required to be able to run on earlier versions
          • lib/providers/AuthImpl.dart:29:3 • sdk_version_async_exported_from_core
   info • The class 'Future' was not exported from 'dart:core' until version 2.1, but this code is required to be able to run on earlier versions
          • lib/providers/AuthImpl.dart:31:3 • sdk_version_async_exported_from_core
   info • The class 'Future' was not exported from 'dart:core' until version 2.1, but this code is required to be able to run on earlier versions
          • lib/providers/AuthImpl.dart:38:3 • sdk_version_async_exported_from_core
   info • The class 'Future' was not exported from 'dart:core' until version 2.1, but this code is required to be able to run on earlier versions
          • lib/providers/AuthImpl.dart:57:3 • sdk_version_async_exported_from_core
   info • The class 'Future' was not exported from 'dart:core' until version 2.1, but this code is required to be able to run on earlier versions
          • lib/providers/AuthImpl.dart:66:3 • sdk_version_async_exported_from_core
   info • The class 'Future' was not exported from 'dart:core' until version 2.1, but this code is required to be able to run on earlier versions
          • lib/providers/AuthImpl.dart:70:3 • sdk_version_async_exported_from_core
   info • The class 'Future' was not exported from 'dart:core' until version 2.1, but this code is required to be able to run on earlier versions
          • lib/providers/AuthImpl.dart:76:3 • sdk_version_async_exported_from_core
   info • The class 'Future' was not exported from 'dart:core' until version 2.1, but this code is required to be able to run on earlier versions
          • lib/providers/AuthImpl.dart:85:3 • sdk_version_async_exported_from_core
   info • The class 'Future' was not exported from 'dart:core' until version 2.1, but this code is required to be able to run on earlier versions
          • lib/providers/AuthImpl.dart:93:3 • sdk_version_async_exported_from_core
   info • The class 'Future' was not exported from 'dart:core' until version 2.1, but this code is required to be able to run on earlier versions
          • lib/providers/AuthImpl.dart:99:3 • sdk_version_async_exported_from_core
   info • The class 'Stream' was not exported from 'dart:core' until version 2.1, but this code is required to be able to run on earlier versions
          • lib/providers/AuthImpl.dart:105:3 • sdk_version_async_exported_from_core
   info • The class 'Future' was not exported from 'dart:core' until version 2.1, but this code is required to be able to run on earlier versions
          • lib/providers/AuthImpl.dart:113:3 • sdk_version_async_exported_from_core
   info • The class 'Future' was not exported from 'dart:core' until version 2.1, but this code is required to be able to run on earlier versions
          • lib/providers/AuthImpl.dart:122:3 • sdk_version_async_exported_from_core
   info • The class 'Future' was not exported from 'dart:core' until version 2.1, but this code is required to be able to run on earlier versions
          • lib/providers/AuthImpl.dart:129:3 • sdk_version_async_exported_from_core
   info • The method '_buildImpactsBottomPadding' isn't used • lib/screens/charity_description_page/CharityDescriptionPage.dart:74:10 •
          unused_element
   info • The class 'Future' was not exported from 'dart:core' until version 2.1, but this code is required to be able to run on earlier versions
          • lib/screens/feedback_page/FeedbackPage.dart:142:3 • sdk_version_async_exported_from_core
   info • The method '_buildCurrentBox' isn't used • lib/screens/home_page/widgets/GlobalGoalCard.dart:256:10 • unused_element
   info • The method '_showSnackBarWelcome' isn't used • lib/screens/login_page/LoginPage.dart:268:8 • unused_element
   info • The method '_userIsSignedIn' isn't used • lib/screens/login_page/LoginPage.dart:273:16 • unused_element
   info • The method '_createAccountPressed' isn't used • lib/screens/login_start_page/LoginStartPage.dart:112:16 • unused_element
   info • The method '_loginPressed' isn't used • lib/screens/login_start_page/LoginStartPage.dart:136:16 • unused_element
warning • The parameter 'title' is required • lib/screens/select_purchase_option_page/widgets/PurchaseOptionCard.dart:200:13 •
       missing_required_param
   info • The value of the field '_newsletter' isn't used • lib/screens/settings_page/SettingsPage.dart:32:8 • unused_field
   info • The method '_buildNicknameListTile' isn't used • lib/screens/settings_page/SettingsPage.dart:177:18 • unused_element
   info • The method '_buildNotificationSection' isn't used • lib/screens/settings_page/SettingsPage.dart:192:16 • unused_element
   info • The method '_buildRewatchOnboardingListTile' isn't used • lib/screens/settings_page/SettingsPage.dart:222:18 • unused_element
   info • The method '_switchNewsletter' isn't used • lib/screens/settings_page/SettingsPage.dart:361:8 • unused_element
   info • Unused import: 'dart:io' • lib/screens/settings_page/widgets/RemoveUserPopup.dart:2:8 • unused_import
   info • Unused import: 'package:tlycs_flutter/blocs/UserBloc.dart' • lib/screens/settings_page/widgets/RemoveUserPopup.dart:6:8 • unused_import
   info • Unused import: 'package:tlycs_flutter/models/PaymentCard.dart' • lib/screens/settings_page/widgets/RemoveUserPopup.dart:7:8 •
          unused_import
   info • Unused import: 'package:tlycs_flutter/models/User.dart' • lib/screens/settings_page/widgets/RemoveUserPopup.dart:8:8 • unused_import
   info • Unused import: 'package:tlycs_flutter/util/CustomerCardCache.dart' • lib/screens/settings_page/widgets/RemoveUserPopup.dart:10:8 •
          unused_import
   info • Unused import: 'package:tlycs_flutter/util/HttpClient.dart' • lib/screens/settings_page/widgets/RemoveUserPopup.dart:11:8 •
          unused_import
   info • The method '_buildAchievementsTab' isn't used • lib/screens/user_page/UserPage.dart:167:13 • unused_element
   info • The class 'Future' was not exported from 'dart:core' until version 2.1, but this code is required to be able to run on earlier versions
          • lib/screens/user_page/widgets/ButtonOptionDialog.dart:4:10 • sdk_version_async_exported_from_core
   info • Unused import: 'package:tlycs_flutter/util/Calculations.dart' • lib/screens/user_page/widgets/TransactionRows.dart:4:8 • unused_import
   info • The class 'Future' was not exported from 'dart:core' until version 2.1, but this code is required to be able to run on earlier versions
          • lib/screens/webviews_with_stripe_element/SharedWebviewMethods.dart:63:3 • sdk_version_async_exported_from_core
   info • The class 'Future' was not exported from 'dart:core' until version 2.1, but this code is required to be able to run on earlier versions
          • lib/screens/webviews_with_stripe_element/SharedWebviewMethods.dart:115:3 • sdk_version_async_exported_from_core
   info • The class 'Future' was not exported from 'dart:core' until version 2.1, but this code is required to be able to run on earlier versions
          • lib/screens/webviews_with_stripe_element/SharedWebviewMethods.dart:121:3 • sdk_version_async_exported_from_core
   info • The class 'Future' was not exported from 'dart:core' until version 2.1, but this code is required to be able to run on earlier versions
          • lib/screens/webviews_with_stripe_element/SharedWebviewMethods.dart:184:3 • sdk_version_async_exported_from_core
   info • The class 'Future' was not exported from 'dart:core' until version 2.1, but this code is required to be able to run on earlier versions
          • lib/screens/webviews_with_stripe_element/SharedWebviewMethods.dart:196:3 • sdk_version_async_exported_from_core
   info • The class 'Future' was not exported from 'dart:core' until version 2.1, but this code is required to be able to run on earlier versions
          • lib/screens/webviews_with_stripe_element/SharedWebviewMethods.dart:200:3 • sdk_version_async_exported_from_core
   info • The class 'Future' was not exported from 'dart:core' until version 2.1, but this code is required to be able to run on earlier versions
          • lib/screens/webviews_with_stripe_element/SharedWebviewMethods.dart:214:3 • sdk_version_async_exported_from_core
   info • The class 'Future' was not exported from 'dart:core' until version 2.1, but this code is required to be able to run on earlier versions
          • lib/util/CustomerCardCache.dart:13:3 • sdk_version_async_exported_from_core
   info • The class 'Future' was not exported from 'dart:core' until version 2.1, but this code is required to be able to run on earlier versions
          • lib/util/CustomerCardCache.dart:19:14 • sdk_version_async_exported_from_core
   info • The class 'Future' was not exported from 'dart:core' until version 2.1, but this code is required to be able to run on earlier versions
          • lib/util/CustomerCardCache.dart:23:14 • sdk_version_async_exported_from_core
   info • The class 'Future' was not exported from 'dart:core' until version 2.1, but this code is required to be able to run on earlier versions
          • lib/util/CustomerCardCache.dart:31:14 • sdk_version_async_exported_from_core
   info • The class 'Future' was not exported from 'dart:core' until version 2.1, but this code is required to be able to run on earlier versions
          • lib/util/EmailSender.dart:18:3 • sdk_version_async_exported_from_core
   info • The class 'Future' was not exported from 'dart:core' until version 2.1, but this code is required to be able to run on earlier versions
          • lib/util/EmailSender.dart:25:5 • sdk_version_async_exported_from_core
   info • The class 'Future' was not exported from 'dart:core' until version 2.1, but this code is required to be able to run on earlier versions
          • lib/util/HttpClient.dart:21:3 • sdk_version_async_exported_from_core
   info • The class 'Future' was not exported from 'dart:core' until version 2.1, but this code is required to be able to run on earlier versions
          • lib/util/HttpClient.dart:28:3 • sdk_version_async_exported_from_core
   info • The class 'Future' was not exported from 'dart:core' until version 2.1, but this code is required to be able to run on earlier versions
          • lib/util/HttpClient.dart:33:3 • sdk_version_async_exported_from_core
   info • The class 'Future' was not exported from 'dart:core' until version 2.1, but this code is required to be able to run on earlier versions
          • lib/util/HttpClient.dart:42:3 • sdk_version_async_exported_from_core
   info • The class 'Future' was not exported from 'dart:core' until version 2.1, but this code is required to be able to run on earlier versions
          • lib/util/HttpClient.dart:47:3 • sdk_version_async_exported_from_core
   info • The class 'Future' was not exported from 'dart:core' until version 2.1, but this code is required to be able to run on earlier versions
          • lib/util/HttpClient.dart:57:3 • sdk_version_async_exported_from_core
   info • The class 'Future' was not exported from 'dart:core' until version 2.1, but this code is required to be able to run on earlier versions
          • lib/util/HttpClient.dart:70:3 • sdk_version_async_exported_from_core
   info • The class 'Future' was not exported from 'dart:core' until version 2.1, but this code is required to be able to run on earlier versions
          • lib/util/HttpClient.dart:84:3 • sdk_version_async_exported_from_core
   info • The class 'Future' was not exported from 'dart:core' until version 2.1, but this code is required to be able to run on earlier versions
          • lib/util/HttpClient.dart:88:3 • sdk_version_async_exported_from_core
   info • The class 'Future' was not exported from 'dart:core' until version 2.1, but this code is required to be able to run on earlier versions
          • lib/util/HttpClient.dart:92:3 • sdk_version_async_exported_from_core
   info • The class 'Future' was not exported from 'dart:core' until version 2.1, but this code is required to be able to run on earlier versions
          • lib/util/HttpClient.dart:96:3 • sdk_version_async_exported_from_core
   info • The class 'Future' was not exported from 'dart:core' until version 2.1, but this code is required to be able to run on earlier versions
          • lib/util/HttpClient.dart:97:29 • sdk_version_async_exported_from_core
   info • The method '_containsOneLowerCaseLetter' isn't used • lib/util/ValidatedForm.dart:270:8 • unused_element
   info • The method '_containsOneUpperCaseLetter' isn't used • lib/util/ValidatedForm.dart:275:8 • unused_element
   info • The method '_containsOneNumber' isn't used • lib/util/ValidatedForm.dart:280:8 • unused_element
   info • The value of the field '_validator' isn't used • lib/util/ValidatedForm.dart:301:33 • unused_field
   info • This class (or a class which this class inherits from) is marked as '@immutable', but one or more of its instance fields are not final:
          PaymentCardCurrentValue.showRemoveOption • lib/widgets/PaymentCardCurrentValue.dart:16:7 • must_be_immutable
   info • The class 'Future' was not exported from 'dart:core' until version 2.1, but this code is required to be able to run on earlier versions
          • lib/widgets/PaymentCardCurrentValue.dart:37:5 • sdk_version_async_exported_from_core
   info • The class 'Future' was not exported from 'dart:core' until version 2.1, but this code is required to be able to run on earlier versions
          • lib/widgets/PaymentCardCurrentValue.dart:95:3 • sdk_version_async_exported_from_core

85 issues found. (ran in 3.4s)
```

flutter doctor -v
```
[✓] Flutter (Channel stable, v1.2.1, on Mac OS X 10.14.4 18E226, locale en-SE)
    • Flutter version 1.2.1 at /Users/martinlundberg/Dev/flutter
    • Framework revision 8661d8aecd (10 weeks ago), 2019-02-14 19:19:53 -0800
    • Engine revision 3757390fa4
    • Dart version 2.1.2 (build 2.1.2-dev.0.0 0a7dcf17eb)

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/martinlundberg/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.2.1, Build version 10E1001
    • ios-deploy 1.9.4
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 33.3.1
    • Dart plugin version 182.5215
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)

[✓] IntelliJ IDEA Ultimate Edition (version 2018.1.3)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 29.0.2
    • Dart plugin version 181.4892.1

[✓] IntelliJ IDEA Community Edition (version 2018.1.6)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 29.0.2
    • Dart plugin version 181.5540.11

[✓] VS Code (version 1.33.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 2.25.1

[✓] Connected device (1 available)
    • iPhone 6 • 63E1705F-F8E7-4916-8C58-D2307D217DCD • ios • com.apple.CoreSimulator.SimRuntime.iOS-12-2 (simulator)

• No issues found!
```

**Comment by molundb** [comment]
Solved by creating a new flutter project and copying all the files there,
