### ISSUE TITLE
Gesture Detector : The getter 'globalPosition' was called on null.

### ISSUE THREAD

**Issue by mohamed6996** [flutter/flutter#31499]
I`m trying to detect vertical drag details using this widget 

```
Widget detect() {
    //Vertical drag details
    DragStartDetails startVerticalDragDetails;
    DragUpdateDetails updateVerticalDragDetails;

    return GestureDetector(
      onVerticalDragStart: (dragDetails) {
        startVerticalDragDetails = dragDetails;
      },
      onVerticalDragUpdate: (dragDetails) {
        updateVerticalDragDetails = dragDetails;
      },
      onVerticalDragEnd: (endDetails) {
        double dx = updateVerticalDragDetails.globalPosition.dx -
            startVerticalDragDetails.globalPosition.dx;
        double dy = updateVerticalDragDetails.globalPosition.dy -
            startVerticalDragDetails.globalPosition.dy;
      },
      child: Container(
        color: Colors.red,
        height: 100,
        width: 100,
      ),
    );
  }
```

but i get this exception every time: 

```
I/flutter (16616): The getter 'globalPosition' was called on null.
I/flutter (16616): Receiver: null
I/flutter (16616): Tried calling: globalPosition
I/flutter (16616): 
I/flutter (16616): When the exception was thrown, this was the stack:
I/flutter (16616): #0      Object.noSuchMethod (dart:core/runtime/libobject_patch.dart:50:5)
I/flutter (16616): #1      _HomePageFE.detect.<anonymous closure> (package:quirkpod/frontend/homePageFE.dart:626:47)
I/flutter (16616): #2      DragGestureRecognizer.didStopTrackingLastPointer.<anonymous closure> (package:flutter/src/gestures/monodrag.dart:210:45)
I/flutter (16616): #3      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:102:24)
I/flutter (16616): #4      DragGestureRecognizer.didStopTrackingLastPointer (package:flutter/src/gestures/monodrag.dart:210:9)
I/flutter (16616): #5      OneSequenceGestureRecognizer.stopTrackingPointer (package:flutter/src/gestures/recognizer.dart:231:9)
I/flutter (16616): #6      OneSequenceGestureRecognizer.stopTrackingIfPointerNoLongerDown (package:flutter/src/gestures/recognizer.dart:240:7)
I/flutter (16616): #7      DragGestureRecognizer.handleEvent (package:flutter/src/gestures/monodrag.dart:157:5)
I/flutter (16616): #8      PointerRouter._dispatch (package:flutter/src/gestures/pointer_router.dart:73:12)
I/flutter (16616): #9      PointerRouter.route (package:flutter/src/gestures/pointer_router.dart:101:11)
I/flutter (16616): #10     _WidgetsFlutterBinding&BindingBase&GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:180:19)
I/flutter (16616): #11     _WidgetsFlutterBinding&BindingBase&GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:158:22)
I/flutter (16616): #12     _WidgetsFlutterBinding&BindingBase&GestureBinding._handlePointerEvent (package:flutter/src/gestures/binding.dart:138:7)
I/flutter (16616): #13     _WidgetsFlutterBinding&BindingBase&GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:101:7)
I/flutter (16616): #14     _WidgetsFlutterBinding&BindingBase&GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:85:7)
I/flutter (16616): #15     _invoke1 (dart:ui/hooks.dart:168:13)
I/flutter (16616): #16     _dispatchPointerDataPacket (dart:ui/hooks.dart:122:5)
I/flutter (16616): 
I/flutter (16616): Handler: onEnd
I/flutter (16616): Recognizer:
I/flutter (16616):   VerticalDragGestureRecognizer#8cff7(debugOwner: GestureDetector)
```

Note that:

 ```

onVerticalDragStart: (dragDetails) {
        startVerticalDragDetails = dragDetails;
      },
```
startVerticalDragDetails  here in not null;

unlike in

```
onVerticalDragEnd: (endDetails) {
        double dx = updateVerticalDragDetails.globalPosition.dx -
            startVerticalDragDetails.globalPosition.dx;
        double dy = updateVerticalDragDetails.globalPosition.dy -
            startVerticalDragDetails.globalPosition.dy;
      },
```

```
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, v1.0.0, on Microsoft Windows [Version 10.0.17763.437], locale en-US)
[√] Android toolchain - develop for Android devices (Android SDK 28.0.3)
[√] Android Studio (version 3.4)
[√] IntelliJ IDEA Community Edition (version 2019.1)
[√] VS Code (version 1.33.1)
[√] Connected device (1 available)

• No issues found!

```

**Comment by BaderEddineOuaich** [comment]
Please use `setState(()` { yourVariable = newValue; });`` whenever you want to update a new value.

**Comment by BaderEddineOuaich** [comment]
Please use `setState(() { yourVariable = newValue; });`` whenever you want to update a new value.

Your code will be like:
``
Widget detect() {
    //Vertical drag details
    DragStartDetails startVerticalDragDetails;
    DragUpdateDetails updateVerticalDragDetails;

    return GestureDetector(
      onVerticalDragStart: (dragDetails) {
setState(()
{
        startVerticalDragDetails = dragDetails;
});

      },
      onVerticalDragUpdate: (dragDetails) {
setState(()
{
        updateVerticalDragDetails = dragDetails;
});
      },
      onVerticalDragEnd: (endDetails) {
        double dx = updateVerticalDragDetails.globalPosition.dx -
            startVerticalDragDetails.globalPosition.dx;
        double dy = updateVerticalDragDetails.globalPosition.dy -
            startVerticalDragDetails.globalPosition.dy;
      },
      child: Container(
        color: Colors.red,
        height: 100,
        width: 100,
      ),
    );
  }
``

**Comment by BaderEddineOuaich** [comment]
Please use `setState(() { yourVariable = newValue; });`` whenever you want to update a new value.

**Comment by BaderEddineOuaich** [comment]
Please use `` setState(() { yourVariable = newValue; }); `` whenever you want to update a new value.

**Comment by mohamed6996** [comment]
I`ve tried it , but still not working

**Comment by mohamed6996** [comment]
I converted this widget into a stateful widget and worked correctly :D
