### ISSUE TITLE
Oops; flutter has exited unexpectedly. 

### ISSUE THREAD

**Issue by AbdullahHanfy** [flutter/flutter#31572]
[flutter_01.log](https://github.com/flutter/flutter/files/3113854/flutter_01.log)
Flutter crash report; please file at https://github.com/flutter/flutter/issues.

## command

flutter run

## exception

ProcessException: ProcessException: Process "D:\Abdullah^^\3rd year\Second term\Software 2\flutter\projects\first_app\android\gradlew.bat" exited abnormally:
Error: Could not find or load main class org.gradle.wrapper.GradleWrapperMain
  Command: D:\Abdullah^^\3rd year\Second term\Software 2\flutter\projects\first_app\android\gradlew.bat -v

```
#0      runCheckedAsync (package:flutter_tools/src/base/process.dart:250:5)
<asynchronous suspension>
#1      _initializeGradle (package:flutter_tools/src/android/gradle.dart:210:9)
<asynchronous suspension>
#2      _ensureGradle (package:flutter_tools/src/android/gradle.dart:191:37)
<asynchronous suspension>
#3      _readGradleProject (package:flutter_tools/src/android/gradle.dart:119:31)
<asynchronous suspension>
#4      _gradleProject (package:flutter_tools/src/android/gradle.dart:111:34)
<asynchronous suspension>
#5      getGradleAppOut (package:flutter_tools/src/android/gradle.dart:105:29)
<asynchronous suspension>
#6      AndroidApk.fromAndroidProject (package:flutter_tools/src/application_package.dart:137:23)
<asynchronous suspension>
#7      ApplicationPackageFactory.getPackageForPlatform (package:flutter_tools/src/application_package.dart:37:32)
<asynchronous suspension>
#8      FlutterDevice.runHot (package:flutter_tools/src/resident_runner.dart:288:56)
<asynchronous suspension>
#9      HotRunner.run (package:flutter_tools/src/run_hot.dart:295:39)
<asynchronous suspension>
#10     RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:405:37)
<asynchronous suspension>
#11     FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:545:18)
#12     _asyncThenWrapperHelper.<anonymous closure> (dart:async/runtime/libasync_patch.dart:77:64)
#13     _rootRunUnary (dart:async/zone.dart:1132:38)
#14     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#15     _FutureListener.handleValue (dart:async/future_impl.dart:126:18)
#16     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:639:45)
#17     Future._propagateToListeners (dart:async/future_impl.dart:668:32)
#18     Future._complete (dart:async/future_impl.dart:473:7)
#19     _SyncCompleter.complete (dart:async/future_impl.dart:51:12)
#20     _AsyncAwaitCompleter.complete (dart:async/runtime/libasync_patch.dart:28:18)
#21     _completeOnAsyncReturn (dart:async/runtime/libasync_patch.dart:294:13)
#22     RunCommand.usageValues (package:flutter_tools/src/commands/run.dart)
#23     _asyncThenWrapperHelper.<anonymous closure> (dart:async/runtime/libasync_patch.dart:77:64)
#24     _rootRunUnary (dart:async/zone.dart:1132:38)
#25     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#26     _FutureListener.handleValue (dart:async/future_impl.dart:126:18)
#27     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:639:45)
#28     Future._propagateToListeners (dart:async/future_impl.dart:668:32)
#29     Future._complete (dart:async/future_impl.dart:473:7)
#30     _SyncCompleter.complete (dart:async/future_impl.dart:51:12)
#31     _AsyncAwaitCompleter.complete (dart:async/runtime/libasync_patch.dart:28:18)
#32     _completeOnAsyncReturn (dart:async/runtime/libasync_patch.dart:294:13)
#33     AndroidDevice.targetPlatform (package:flutter_tools/src/android/android_device.dart)
#34     _asyncThenWrapperHelper.<anonymous closure> (dart:async/runtime/libasync_patch.dart:77:64)
#35     _rootRunUnary (dart:async/zone.dart:1132:38)
#36     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#37     _FutureListener.handleValue (dart:async/future_impl.dart:126:18)
#38     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:639:45)
#39     Future._propagateToListeners (dart:async/future_impl.dart:668:32)
#40     Future._complete (dart:async/future_impl.dart:473:7)
#41     _SyncCompleter.complete (dart:async/future_impl.dart:51:12)
#42     _AsyncAwaitCompleter.complete.<anonymous closure> (dart:async/runtime/libasync_patch.dart:33:20)
#43     _rootRun (dart:async/zone.dart:1124:13)
#44     _CustomZone.run (dart:async/zone.dart:1021:19)
#45     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:947:23)
#46     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#47     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#48     _runPendingImmediateCallback (dart:isolate/runtime/libisolate_patch.dart:115:13)
#49     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:172:5)
```

## flutter doctor

```
 [32m[✓] [39m Flutter (Channel stable, v1.2.1, on Microsoft Windows [Version 10.0.16299.1029], locale en-US)
     [32m• [39m Flutter version 1.2.1 at C:\Users\Abdullah\flutter
     [32m• [39m Framework revision 8661d8aecd (10 weeks ago), 2019-02-14 19:19:53 -0800
     [32m• [39m Engine revision 3757390fa4
     [32m• [39m Dart version 2.1.2 (build 2.1.2-dev.0.0 0a7dcf17eb)

 [32m[✓] [39m Android toolchain - develop for Android devices (Android SDK version 28.0.3)
     [32m• [39m Android SDK at C:\Users\Abdullah\AppData\Local\Android\sdk
     [32m• [39m Android NDK location not configured (optional; useful for native profiling support)
     [32m• [39m Platform android-28, build-tools 28.0.3
     [32m• [39m ANDROID_HOME = C:\Users\Abdullah\AppData\Local\Android
     [32m• [39m Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
     [32m• [39m Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
     [32m• [39m All Android licenses accepted.

 [32m[✓] [39m Android Studio (version 3.4)
     [32m• [39m Android Studio at C:\Program Files\Android\Android Studio
     [32m• [39m Flutter plugin version 34.0.2
     [32m• [39m Dart plugin version 183.5901
     [32m• [39m Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

 [32m[✓] [39m Connected device (1 available)
     [32m• [39m Android SDK built for x86 • emulator-5554 • android-x86 • Android 9 (API 28) (emulator)

 [32m• [39m No issues found!
```

**Comment by canewsin** [comment]
same for me with latest flutter master

**Comment by jonahwilliams** [comment]
Have you copied or moved the android folder in such a way that gradle wrapper was lost? For example: https://stackoverflow.com/questions/29805622/could-not-find-or-load-main-class-org-gradle-wrapper-gradlewrappermain

**Comment by jonahwilliams** [comment]
Please include the output of `flutter doctor -v`

**Comment by canewsin** [comment]
even 
`flutter doctor`
throwing the error
fatal: bad config line 1 in file .git/config
Building flutter tool...
Running pub upgrade...
Doctor summary (to see all details, run flutter doctor -v):

```
Oops; flutter has exited unexpectedly.
Sending crash report to Google.
Failed to send crash report. Server responded with HTTP status code 400
Crash report written to C:\flutter\1.0.0\bin\flutter_01.log;
please let us know at https://github.com/flutter/flutter/issues.
```

**Comment by jonahwilliams** [comment]
It sounds like the download might have been corrupted

**Comment by canewsin** [comment]
is there any repair cmd in flutter tool

**Comment by jonahwilliams** [comment]
No, but if the download is corrupted the hypothetical repair command likely wouldn't work any way. I would recommend redownloading

**Comment by canewsin** [comment]
i had copy of flutter zip i will reuse it, it might download necessary files, can we use old downloded tools(i mean bin downloaded after flutter doctor invoked first time) without downloading or deleting folder is recommended

**Comment by canewsin** [comment]
Ok Solved My Issue by deleting and unzipping binaries

**Comment by AbdullahHanfy** [comment]
> Ok Solved My Issue by deleting and unzipping binaries

where the binaries ??

**Comment by canewsin** [comment]
I mean Unzipping normal Downlod File to be downloaded to run flutter development which is available on flutter.dev site
https://flutter.dev/docs/get-started/install

**Comment by janmoppel** [comment]
Hello @AbdullahHanfy !

Did you manage to solve the issue? Does the problem still persist in the latest stable version?

**Comment by iapicca** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
  
Thanks for your contribution.
