### ISSUE TITLE
Flutter crashes when renaming Runner project

### ISSUE THREAD

**Issue by vikramkapoor** [flutter/flutter#31583]
## Steps to Reproduce

1. ... Type "Flutter run" in project
2. ...
3. ...

## Logs

Flutter crash report; please file at https://github.com/flutter/flutter/issues.

## command

flutter run --verbose

## exception

ProcessException: ProcessException: No such file or directory
  Command: /usr/bin/xcodebuild -project /Users/vikramkapoor/Documents/GitHub/Safeho/ios/Runner.xcodeproj -target Runner -showBuildSettings

```
#0      _ProcessImpl._runAndWait (dart:io/runtime/binprocess_patch.dart:489:7)
#1      _runNonInteractiveProcessSync (dart:io/runtime/binprocess_patch.dart:634:18)
#2      Process.runSync (dart:io/runtime/binprocess_patch.dart:66:12)
#3      LocalProcessManager.runSync (package:process/src/interface/local_process_manager.dart:83:20)
#4      _runWithLoggingSync (package:flutter_tools/src/base/process.dart:325:48)
#5      runCheckedSync (package:flutter_tools/src/base/process.dart:283:10)
#6      XcodeProjectInterpreter.getBuildSettings (package:flutter_tools/src/ios/xcodeproj.dart:151:24)
#7      IosProject.buildSettings (package:flutter_tools/src/project.dart:262:42)
#8      IosProject.productBundleIdentifier (package:flutter_tools/src/project.dart:248:56)
#9      new BuildableIOSApp (package:flutter_tools/src/application_package.dart:293:66)
#10     new IOSApp.fromIosProject (package:flutter_tools/src/application_package.dart:281:12)
#11     ApplicationPackageFactory.getPackageForPlatform (package:flutter_tools/src/application_package.dart:41:22)
<asynchronous suspension>
#12     FlutterDevice.runHot (package:flutter_tools/src/resident_runner.dart:288:56)
<asynchronous suspension>
#13     HotRunner.run (package:flutter_tools/src/run_hot.dart:295:39)
<asynchronous suspension>
#14     RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:405:37)
<asynchronous suspension>
#15     FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:545:18)
#16     _asyncThenWrapperHelper.<anonymous closure> (dart:async/runtime/libasync_patch.dart:77:64)
#17     _rootRunUnary (dart:async/zone.dart:1132:38)
#18     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#19     _FutureListener.handleValue (dart:async/future_impl.dart:126:18)
#20     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:639:45)
#21     Future._propagateToListeners (dart:async/future_impl.dart:668:32)
#22     Future._complete (dart:async/future_impl.dart:473:7)
#23     _SyncCompleter.complete (dart:async/future_impl.dart:51:12)
#24     _AsyncAwaitCompleter.complete (dart:async/runtime/libasync_patch.dart:28:18)
#25     _completeOnAsyncReturn (dart:async/runtime/libasync_patch.dart:294:13)
#26     RunCommand.usageValues (package:flutter_tools/src/commands/run.dart)
#27     _asyncThenWrapperHelper.<anonymous closure> (dart:async/runtime/libasync_patch.dart:77:64)
#28     _rootRunUnary (dart:async/zone.dart:1132:38)
#29     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#30     _FutureListener.handleValue (dart:async/future_impl.dart:126:18)
#31     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:639:45)
#32     Future._propagateToListeners (dart:async/future_impl.dart:668:32)
#33     Future._complete (dart:async/future_impl.dart:473:7)
#34     _SyncCompleter.complete (dart:async/future_impl.dart:51:12)
#35     _AsyncAwaitCompleter.complete.<anonymous closure> (dart:async/runtime/libasync_patch.dart:33:20)
#36     _rootRun (dart:async/zone.dart:1124:13)
#37     _CustomZone.run (dart:async/zone.dart:1021:19)
#38     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:947:23)
#39     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#40     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#41     _runPendingImmediateCallback (dart:isolate/runtime/libisolate_patch.dart:115:13)
#42     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:172:5)
```

## flutter doctor

```
ESC[32m[✓]ESC[39m Flutter (Channel stable, v1.2.1, on Mac OS X 10.14.4 18E226, locale en-US)
    ESC[32m•ESC[39m Flutter version 1.2.1 at /Users/vikramkapoor/development/flutter
    ESC[32m•ESC[39m Framework revision 8661d8aecd (10 weeks ago), 2019-02-14 19:19:53 -0800
    ESC[32m•ESC[39m Engine revision 3757390fa4
    ESC[32m•ESC[39m Dart version 2.1.2 (build 2.1.2-dev.0.0 0a7dcf17eb)

ESC[31m[✗]ESC[39m Android toolchain - develop for Android devices
    ESC[31m✗ESC[39m Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.io/setup/#android-setup for detailed instructions).
      If Android SDK has been installed to a custom location, set ANDROID_HOME to that location.
      You may also want to add it to your PATH environment variable.


ESC[32m[✓]ESC[39m iOS toolchain - develop for iOS devices (Xcode 10.2.1)
    ESC[32m•ESC[39m Xcode at /Applications/Xcode.app/Contents/Developer
    ESC[32m•ESC[39m Xcode 10.2.1, Build version 10E1001
    ESC[32m•ESC[39m ios-deploy 1.9.4
    ESC[32m•ESC[39m CocoaPods version 1.6.1

ESC[33m[!]ESC[39m Android Studio (not installed)
    ESC[32m•ESC[39m Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.io/setup/#android-setup for detailed instructions).

ESC[32m[✓]ESC[39m Connected device (1 available)
    ESC[32m•ESC[39m iPhone Xʀ • B2EF6AB8-734D-497D-9324-B5DCD7DD0627 • ios • com.apple.CoreSimulator.SimRuntime.iOS-12-2 (simulator)

ESC[33m!ESC[39m Doctor found issues in 2 categories.
```
(END)

```
```

```
```

**Comment by jonahwilliams** [comment]
This might happen if the `ios/` sub-project is damaged or missing. Did this recently start happening, or is this a new application?

**Comment by vikramkapoor** [comment]
It happened because I changed the project name from Runner to my own custom name. That wasn't really necessary so I reverted it to solve the issue.

**Comment by jonahwilliams** [comment]
We should add better error handling here
