### ISSUE TITLE
App not launching iOS

### ISSUE THREAD

**Issue by Pareshoct7** [flutter/flutter#31646]
## command

flutter run

## exception

FileSystemException: FileSystemException: Getting current working directory failed, path = '' (OS Error: Too many open files, errno = 24)

```
#0      _uriBaseClosure (dart:io/runtime/bindirectory_patch.dart:64:5)
#1      Uri.base (dart:core/runtime/liburi_patch.dart:21:41)
#2      current (package:path/path.dart:84:17)
#3      new Context (package:path/src/context.dart:31:21)
#4      LocalFileSystem.path (package:file/src/backends/local/local_file_system.dart:34:29)
#5      writeBundle.<anonymous closure> (package:flutter_tools/src/bundle.dart:233:34)
<asynchronous suspension>
#6      MappedIterator.moveNext (dart:_internal/iterable.dart:392:18)
#7      Future.wait (dart:async/future.dart:393:26)
#8      writeBundle (package:flutter_tools/src/bundle.dart:231:16)
#9      _AsyncAwaitCompleter.start (dart:async/runtime/libasync_patch.dart:49:6)
#10     writeBundle (package:flutter_tools/src/bundle.dart:225:25)
#11     assemble (package:flutter_tools/src/bundle.dart:221:9)
#12     _AsyncAwaitCompleter.start (dart:async/runtime/libasync_patch.dart:49:6)
#13     assemble (package:flutter_tools/src/bundle.dart:189:22)
#14     build (package:flutter_tools/src/bundle.dart:154:9)
#15     _asyncThenWrapperHelper.<anonymous closure> (dart:async/runtime/libasync_patch.dart:77:64)
#16     _rootRunUnary (dart:async/zone.dart:1132:38)
#17     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#18     _FutureListener.handleValue (dart:async/future_impl.dart:126:18)
#19     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:639:45)
#20     Future._propagateToListeners (dart:async/future_impl.dart:668:32)
#21     Future._complete (dart:async/future_impl.dart:473:7)
#22     _SyncCompleter.complete (dart:async/future_impl.dart:51:12)
#23     _AsyncAwaitCompleter.complete (dart:async/runtime/libasync_patch.dart:28:18)
#24     _completeOnAsyncReturn (dart:async/runtime/libasync_patch.dart:294:13)
#25     buildAssets (package:flutter_tools/src/bundle.dart)
#26     _asyncThenWrapperHelper.<anonymous closure> (dart:async/runtime/libasync_patch.dart:77:64)
#27     _rootRunUnary (dart:async/zone.dart:1132:38)
#28     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#29     _FutureListener.handleValue (dart:async/future_impl.dart:126:18)
#30     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:639:45)
#31     Future._propagateToListeners (dart:async/future_impl.dart:668:32)
#32     Future._complete (dart:async/future_impl.dart:473:7)
#33     _SyncCompleter.complete (dart:async/future_impl.dart:51:12)
#34     _AsyncAwaitCompleter.complete (dart:async/runtime/libasync_patch.dart:28:18)
#35     _completeOnAsyncReturn (dart:async/runtime/libasync_patch.dart:294:13)
#36     _ManifestAssetBundle.build (package:flutter_tools/src/asset.dart)
#37     _asyncThenWrapperHelper.<anonymous closure> (dart:async/runtime/libasync_patch.dart:77:64)
#38     _rootRunUnary (dart:async/zone.dart:1132:38)
#39     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#40     _FutureListener.handleValue (dart:async/future_impl.dart:126:18)
#41     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:639:45)
#42     Future._propagateToListeners (dart:async/future_impl.dart:668:32)
#43     Future._complete (dart:async/future_impl.dart:473:7)
#44     _SyncCompleter.complete (dart:async/future_impl.dart:51:12)
#45     _AsyncAwaitCompleter.complete (dart:async/runtime/libasync_patch.dart:28:18)
#46     _completeOnAsyncReturn (dart:async/runtime/libasync_patch.dart:294:13)
#47     _obtainLicenses (package:flutter_tools/src/asset.dart)
#48     _asyncThenWrapperHelper.<anonymous closure> (dart:async/runtime/libasync_patch.dart:77:64)
#49     _rootRunUnary (dart:async/zone.dart:1132:38)
#50     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#51     _FutureListener.handleValue (dart:async/future_impl.dart:126:18)
#52     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:639:45)
#53     Future._propagateToListeners (dart:async/future_impl.dart:668:32)
#54     Future._completeWithValue (dart:async/future_impl.dart:483:5)
#55     Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:513:7)
#56     _rootRun (dart:async/zone.dart:1124:13)
#57     _CustomZone.run (dart:async/zone.dart:1021:19)
#58     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:947:23)
#59     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#60     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#61     _runPendingImmediateCallback (dart:isolate/runtime/libisolate_patch.dart:115:13)
#62     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:172:5)
```

## flutter doctor

```
[32m[✓][39m Flutter (Channel stable, v1.2.1, on Mac OS X 10.14.4 18E226, locale en-IN)
    [32m•[39m Flutter version 1.2.1 at /Users/Paresh/development/flutter
    [32m•[39m Framework revision 8661d8aecd (2 months ago), 2019-02-14 19:19:53 -0800
    [32m•[39m Engine revision 3757390fa4
    [32m•[39m Dart version 2.1.2 (build 2.1.2-dev.0.0 0a7dcf17eb)

[32m[✓][39m Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    [32m•[39m Android SDK at /Users/Paresh/Library/Android/sdk
    [32m•[39m Android NDK location not configured (optional; useful for native profiling
      support)
    [32m•[39m Platform android-28, build-tools 28.0.3
    [32m•[39m Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    [32m•[39m Java version OpenJDK Runtime Environment (build
      1.8.0_152-release-1248-b01)
    [32m•[39m All Android licenses accepted.

[32m[✓][39m iOS toolchain - develop for iOS devices (Xcode 10.2.1)
    [32m•[39m Xcode at /Applications/Xcode.app/Contents/Developer
    [32m•[39m Xcode 10.2.1, Build version 10E1001
    [32m•[39m ios-deploy 1.9.4
    [32m•[39m CocoaPods version 1.6.1

[32m[✓][39m Android Studio (version 3.3)
    [32m•[39m Android Studio at /Applications/Android Studio.app/Contents
    [32m•[39m Flutter plugin version 33.4.1
    [32m•[39m Dart plugin version 182.5215
    [32m•[39m Java version OpenJDK Runtime Environment (build
      1.8.0_152-release-1248-b01)

[32m[✓][39m Connected device (1 available)
    [32m•[39m iPhone Xʀ • 7EEBE15C-6D78-4895-BA18-98DCFE611764 • ios •
      com.apple.CoreSimulator.SimRuntime.iOS-12-2 (simulator)

[32m•[39m No issues found!
```

**Comment by jonahwilliams** [comment]
Perhaps try https://superuser.com/questions/433746/is-there-a-fix-for-the-too-many-open-files-in-system-error-on-os-x-10-7-1/1171028 ?

**Comment by jkira** [comment]
I'm also having this issue... can't run the app in the iOS simulator any more. 

FileSystemException: FileSystemException: Getting current working directory failed, path = '' (OS Error: Too many open files, errno = 24)

Changing the maxfiles limit makes no difference.

I *can* install to my iOS device however.

**Comment by iapicca** [comment]
Hi @Pareshoct7  
are you still experiencing this issue with the latest stable version of flutter?
thank you

**Comment by Pareshoct7** [comment]
@iapicca I drop the project at that time because there is no solution to this issue and now I am working on a different project where I don't show this error anymore. but I don't get the solution anyway.

**Comment by iapicca** [comment]
Hi @Pareshoct7 
given your last message I'm closing the issue for now
if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact descriptions what happens, logs and the output of 'flutter doctor -v'  please.
All system setups can be slightly different so it's always better to open new issues and reference related issues.
