### ISSUE TITLE
Engine crash during unconstrained layout

### ISSUE THREAD

**Issue by tvolkert** [flutter/flutter#31650]
```dart
import 'package:flutter/material.dart';

void main() {
  runApp(MaterialApp(
    title: 'Crasher',
    home: Scaffold(
      body: SafeArea(
        child: Crasher(),
      ),
    ),
  ));
}

class Crasher extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    Widget child = ListWheelScrollView(
      itemExtent: 20,
      onSelectedItemChanged: (int index) {},
      children: <Widget>[
        Text('item'),
      ],
    );

    return Material(
      child: FittedBox(
        child: Center(
          child: child,
        ),
      ),
    );
  }
}
```

Running this yields the following crash in the engine:

```
F/flutter (13463): [FATAL:flutter/flow/layers/transform_layer.cc(28)] Check failed: transform_.isFinite(). 
F/libc    (13463): Fatal signal 6 (SIGABRT), code -6 in tid 13480 (1.gpu)
*** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
```

**Comment by tvolkert** [comment]
Looks like this was introduced in https://github.com/flutter/engine/pull/8585

**Comment by tvolkert** [comment]
This rolled into the framework in https://github.com/flutter/flutter/pull/31179, which translates to version `1.5.2`

**Comment by tvolkert** [comment]
When we fix, please add a test that would have caught this.

**Comment by liyuqian** [comment]
I did a `flutter run` and got the following error message:
```
I/flutter (10811): ══╡ EXCEPTION CAUGHT BY RENDERING LIBRARY ╞═════════════════════════════════════════════════════════
I/flutter (10811): The following assertion was thrown during performResize():
I/flutter (10811): RenderListWheelViewport object was given an infinite size during layout.
I/flutter (10811): This probably means that it is a render object that tries to be as big as possible, but it was put
I/flutter (10811): inside another render object that allows its children to pick their own size.
I/flutter (10811): The nearest ancestor providing an unbounded width constraint is:
I/flutter (10811):   RenderFittedBox#429fb relayoutBoundary=up4 NEEDS-LAYOUT NEEDS-PAINT
I/flutter (10811):   creator: FittedBox ← DefaultTextStyle ← AnimatedDefaultTextStyle ← _InkFeatures-[GlobalKey#659ed
I/flutter (10811):   ink renderer] ← NotificationListener<LayoutChangedNotification> ← PhysicalModel ←
I/flutter (10811):   AnimatedPhysicalModel ← Material ← Crasher ← MediaQuery ← Padding ← SafeArea ← ⋯
I/flutter (10811):   parentData: <none> (can use size)
I/flutter (10811):   constraints: BoxConstraints(0.0<=w<=360.0, 0.0<=h<=568.0)
I/flutter (10811):   size: MISSING
I/flutter (10811):   fit: contain
I/flutter (10811):   alignment: center
I/flutter (10811):   textDirection: ltr
I/flutter (10811): The nearest ancestor providing an unbounded height constraint is:
I/flutter (10811):   RenderFittedBox#429fb relayoutBoundary=up4 NEEDS-LAYOUT NEEDS-PAINT
I/flutter (10811):   creator: FittedBox ← DefaultTextStyle ← AnimatedDefaultTextStyle ← _InkFeatures-[GlobalKey#659ed
I/flutter (10811):   ink renderer] ← NotificationListener<LayoutChangedNotification> ← PhysicalModel ←
I/flutter (10811):   AnimatedPhysicalModel ← Material ← Crasher ← MediaQuery ← Padding ← SafeArea ← ⋯
I/flutter (10811):   parentData: <none> (can use size)
I/flutter (10811):   constraints: BoxConstraints(0.0<=w<=360.0, 0.0<=h<=568.0)
I/flutter (10811):   size: MISSING
I/flutter (10811):   fit: contain
I/flutter (10811):   alignment: center
I/flutter (10811):   textDirection: ltr
I/flutter (10811): The constraints that applied to the RenderListWheelViewport were:
I/flutter (10811):   BoxConstraints(unconstrained)
I/flutter (10811): The exact size it was given was:
I/flutter (10811):   Size(Infinity, Infinity)
I/flutter (10811): See https://flutter.io/layout/ for more information.
I/flutter (10811): 
I/flutter (10811): When the exception was thrown, this was the stack:
I/flutter (10811): #0      RenderBox.debugAssertDoesMeetConstraints.<anonymous closure> (package:flutter/src/rendering/box.dart:1749:9)
I/flutter (10811): #1      RenderBox.debugAssertDoesMeetConstraints (package:flutter/src/rendering/box.dart:1823:6)
I/flutter (10811): #2      RenderBox.size=.<anonymous closure> (package:flutter/src/rendering/box.dart:1543:17)
I/flutter (10811): #3      RenderBox.size= (package:flutter/src/rendering/box.dart:1543:65)
I/flutter (10811): #4      RenderListWheelViewport.performResize (package:flutter/src/rendering/list_wheel_viewport.dart:558:5)
I/flutter (10811): #5      RenderObject.layout (package:flutter/src/rendering/object.dart:1617:9)
I/flutter (10811): #6      _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter (10811): #7      RenderObject.layout (package:flutter/src/rendering/object.dart:1632:7)
I/flutter (10811): #8      _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter (10811): #9      RenderObject.layout (package:flutter/src/rendering/object.dart:1632:7)
I/flutter (10811): #10     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
...
```

**Comment by liyuqian** [comment]
During `flutter run --profile` and `flutter run --release`, I got
```
I/flutter (11396): ══╡ EXCEPTION CAUGHT BY RENDERING LIBRARY ╞═════════════════════════════════════════════════════════
I/flutter (11396): The following UnsupportedError was thrown during performLayout():
I/flutter (11396): Unsupported operation: Infinity or NaN toInt
I/flutter (11396): 
I/flutter (11396): When the exception was thrown, this was the stack:
I/flutter (11396): #0      _Double.toInt (dart:core/runtime/lib/double.dart:183)
I/flutter (11396): #1      _Double.floor (dart:core/runtime/lib/double.dart:152)
I/flutter (11396): #2      RenderListWheelViewport.scrollOffsetToIndex (package:flutter/src/rendering/list_wheel_viewport.dart:356)
I/flutter (11396): #3      RenderListWheelViewport.performLayout (package:flutter/src/rendering/list_wheel_viewport.dart:630)
I/flutter (11396): #4      RenderObject.layout (package:flutter/src/rendering/object.dart:1632)
I/flutter (11396): #5      _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105)
I/flutter (11396): #6      RenderObject.layout (package:flutter/src/rendering/object.dart:1632)
I/flutter (11396): #7      _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105)
I/flutter (11396): #8      RenderObject.layout (package:flutter/src/rendering/object.dart:1632)
I/flutter (11396): #9      _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105)
I/flutter (11396): #10     RenderObject.layout (package:flutter/src/rendering/object.dart:1632)
I/flutter (11396): #11     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105)
I/flutter (11396): #12     RenderObject.layout (package:flutter/src/rendering/object.dart:1632)
I/flutter (11396): #13     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105)
I/flutter (11396): #14     RenderObject.layout (package:flutter/src/rendering/object.dart:1632)
I/flutter (11396): #15     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105)
I/flutter (11396): #16     RenderObject.layout (package:flutter/src/rendering/object.dart:1632)
I/flutter (11396): #17     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105)
I/flutter (11396): #18     RenderObject.layout (package:flutter/src/rendering/object.dart:1632)
I/flutter (11396): #19     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105)
I/flutter (11396): #20     RenderObject.layout (package:flutter/src/rendering/object.dart:1632)
I/flutter (11396): #21     RenderPositionedBox.performLayout (package:flutter/src/rendering/shifted_box.dart:385)
I/flutter (11396): #22     RenderObject.layout (package:flutter/src/rendering/object.dart:1632)
I/flutter (11396): #23     RenderFittedBox.performLayout (package:flutter/src/rendering/proxy_box.dart:2287)
I/flutter (11396): #24     RenderObject.layout (package:flutter/src/rendering/object.dart:1632)
I/flutter (11396): #25     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105)
...
```

**Comment by liyuqian** [comment]
CC @xster (the author of list_wheel_scroll_view.dart according to git blame)

**Comment by liyuqian** [comment]
Oh, I was on an older version of Flutter. When I checked out the tip of tree, I got
```
F/flutter (11573): [FATAL:flutter/flow/layers/transform_layer.cc(28)] Check failed: transform_.isFinite(). 
F/libc    (11573): Fatal signal 6 (SIGABRT), code -6 in tid 11590 (1.gpu)
```

**Comment by tvolkert** [comment]
fwiw, the code should result in an exception - just not an engine crash 😄

**Comment by liyuqian** [comment]
Ah, the older version doesn't have the engine `FML_CHECK` yet. Once I comment the `FML_CHECK`, I got the exact same exception in https://github.com/flutter/flutter/issues/31650#issuecomment-487123842

According to https://github.com/flutter/flutter/issues/31650#issuecomment-487128158, I think we have two options here:
1. In the framework, check the matrix when it's sent from the framework to the engine, and throw an exception there.
2. Lower `FML_CHECK` to `FML_DCHECK` so it would only crash engine in `unopt` engine build.

@chinmaygarde and I discussed option 2 when we first implemented the check, and we decided that a bad/corrupted matrix should have a crash in all builds instead of just `unopt` builds.

**Comment by tvolkert** [comment]
I'm ok with option 1, but shouldn't we be hitting the assertion in https://github.com/flutter/flutter/issues/31650#issuecomment-487123842 before we send the matrix to the engine anyway?

**Comment by liyuqian** [comment]
BTW, I pinpointed the location where the NaN is generated: https://github.com/flutter/flutter/compare/master...liyuqian:check_transform_matrix#diff-f41d041ddd3fe665cc9e123f992bb5e0R2277

**Comment by rajeshzmoke** [comment]
App crashing in release

```
flutter: ══╡ EXCEPTION CAUGHT BY SCHEDULER LIBRARY ╞═════════════════════════════════════════════════════════
flutter: The following assertion was thrown during a scheduler callback:
flutter: Offset argument contained a NaN value.
flutter: 'dart:ui/painting.dart': Failed assertion: line 38: '<optimized out>'
flutter:
flutter: Either the assertion indicates an error in the framework itself, or we should provide substantially
flutter: more information in this error message to help you determine and fix the underlying cause.
flutter: In either case, please report this assertion by filing a bug on GitHub:
flutter:   https://github.com/flutter/flutter/issues/new?template=BUG.md
flutter:
flutter: When the exception was thrown, this was the stack:
flutter: #2      _offsetIsValid (dart:ui/painting.dart:38:10)
flutter: #3      Path.contains (dart:ui/painting.dart:2090:12)
flutter: #4      ClipPathLayer.find (package:flutter/src/rendering/layer.dart:1137:19)
flutter: #5      ContainerLayer.find (package:flutter/src/rendering/layer.dart:616:36)
flutter: #6      OffsetLayer.find (package:flutter/src/rendering/layer.dart:846:18)
flutter: #7      TransformLayer.find (package:flutter/src/rendering/layer.dart:1218:18)
flutter: #8      ContainerLayer.find (package:flutter/src/rendering/layer.dart:616:36)
flutter: #9      ClipPathLayer.find (package:flutter/src/rendering/layer.dart:1139:18)
flutter: #10     ContainerLayer.find (package:flutter/src/rendering/layer.dart:616:36)
flutter: #11     PhysicalModelLayer.find (package:flutter/src/rendering/layer.dart:1515:18)
flutter: #12     ContainerLayer.find (package:flutter/src/rendering/layer.dart:616:36)
flutter: #13     OffsetLayer.find (package:flutter/src/rendering/layer.dart:846:18)
flutter: #14     ContainerLayer.find (package:flutter/src/rendering/layer.dart:616:36)
flutter: #15     OffsetLayer.find (package:flutter/src/rendering/layer.dart:846:18)
flutter: #16     ContainerLayer.find (package:flutter/src/rendering/layer.dart:616:36)
flutter: #17     PhysicalModelLayer.find (package:flutter/src/rendering/layer.dart:1515:18)
flutter: #18     ContainerLayer.find (package:flutter/src/rendering/layer.dart:616:36)
flutter: #19     OffsetLayer.find (package:flutter/src/rendering/layer.dart:846:18)
flutter: #20     ContainerLayer.find (package:flutter/src/rendering/layer.dart:616:36)
flutter: #21     OffsetLayer.find (package:flutter/src/rendering/layer.dart:846:18)
flutter: #22     ContainerLayer.find (package:flutter/src/rendering/layer.dart:616:36)
flutter: #23     OffsetLayer.find (package:flutter/src/rendering/layer.dart:846:18)
flutter: #24     TransformLayer.find (package:flutter/src/rendering/layer.dart:1218:18)
flutter: #25     RenderView._updateSystemChrome (package:flutter/src/rendering/view.dart:218:58)
flutter: #26     RenderView.compositeFrame (package:flutter/src/rendering/view.dart:201:9)
flutter: #27     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding.drawFrame (package:flutter/src/rendering/binding.dart:350:16)
flutter: #28     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding&WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:701:13)
flutter: #29     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:286:5)
flutter: #30     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1012:15)
flutter: #31     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:952:9)
flutter: #32     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:864:5)
flutter: #36     _invoke (dart:ui/hooks.dart:219:10)
flutter: #37     _drawFrame (dart:ui/hooks.dart:178:3)
flutter: (elided 5 frames from class _AssertionError and package dart:async)
flutter: ════════════════════════════════════════════════════════════════════════════════════════════════════
```

**Comment by liyuqian** [comment]
@rajeshzmoke your crash seems to be different from the issue that we're tracking here (`_offsetIsValid` instead of `Check failed: transform_.isFinite()`). Can you please create a new issue with instructions on how to reproduce the crash? (A single-file minimal Flutter app that reproduces the crash would be the best.)

**Comment by rajeshzmoke** [comment]
@liyuqian  `Check failed: transform_.isFinite() ` does come when in release mode.. the error i've posted is in debug build

**Comment by liyuqian** [comment]
@rajeshzmoke I see. Do you have some code that can reproduce the crash? That would tremendously help us debug the issue.

**Comment by C-Aniruddh** [comment]
@tvolkert any definitive solution to this problem?

**Comment by tvolkert** [comment]
To our knowledge, the issue (or at least the code path in which it was originally reported) has been fixed by adding asserts in the framework (so real errors are still reported, but they don't get all the way to the engine and cause the app to crash).

@C-Aniruddh and @rajeshzmoke if you're still seeing this and have a small case in which it reliably reproduces, we'd love to take a look!

**Comment by C-Aniruddh** [comment]
@tvolkert should I pick these commits and rebuild flutter or they've been merged into the main branch? If I have to rebuild the engine manually, is there any specific guide for the compilation process?

**Comment by tvolkert** [comment]
They've all been merged into master at this point, so you shouldn't have to build a local engine.

**Comment by liyuqian** [comment]
@C-Aniruddh : btw, https://github.com/flutter/engine/commit/f1d821d8fde79569f801cb9c902c2e9d45b46fb6 is replacing `FML_CHECK` with `FML_DCHECK` so it won't crash the engine in release just in case that the framework doesn't catch the invalid matrix.
