### ISSUE TITLE
Exception during Hero animation when pop is interrupted by push

### ISSUE THREAD

**Issue by spkersten** [flutter/flutter#31667]
On iOS, when using the swipe gesture to pop a route, if a new route is pushed before the pop finishes this exception gets thrown:

```
flutter: ══╡ EXCEPTION CAUGHT BY SCHEDULER LIBRARY ╞═════════════════════════════════════════════════════════
flutter: The following assertion was thrown during a scheduler callback:
flutter: 'package:flutter/src/widgets/heroes.dart': Failed assertion: line 530 pos 14: 'manifest.toHero ==
flutter: newManifest.fromHero': is not true.
flutter:
flutter: Either the assertion indicates an error in the framework itself, or we should provide substantially
flutter: more information in this error message to help you determine and fix the underlying cause.
flutter: In either case, please report this assertion by filing a bug on GitHub:
flutter:   https://github.com/flutter/flutter/issues/new?template=BUG.md
flutter:
flutter: When the exception was thrown, this was the stack:
flutter: #2      _HeroFlight.divert (package:flutter/src/widgets/heroes.dart:530:14)
flutter: #3      HeroController._startHeroTransition (package:flutter/src/widgets/heroes.dart:736:25)
flutter: #4      HeroController._maybeStartHeroTransition.<anonymous closure> (package:flutter/src/widgets/heroes.dart:684:11)
flutter: #5      _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1012:15)
flutter: #6      _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:960:9)
flutter: #7      _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:864:5)
flutter: #11     _invoke (dart:ui/hooks.dart:219:10)
flutter: #12     _drawFrame (dart:ui/hooks.dart:178:3)
flutter: (elided 5 frames from class _AssertionError and package dart:async)
flutter: ════════════════════════════════════════════════════════════════════════════════════════════════════
```

Minimal example:
```dart
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) => MaterialApp(home: Page1());
}

class Page1 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return GestureDetector(
      onTap: () => Navigator.of(context).push(MaterialPageRoute(builder: (_) => Page2())),
      child: Container(
        color: Colors.blue,
        child: Center(
          child: Hero(
            transitionOnUserGestures: true,
            tag: "superman",
            child: Container(width: 40, height: 40, color: Colors.yellow),
          ),
        ),
      ),
    );
  }
}

class Page2 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Container(
      color: Colors.green,
      child: Center(
        child: Hero(
          transitionOnUserGestures: true,
          tag: "superman",
          child: Container(width: 40, height: 40, color: Colors.yellow),
        ),
      ),
    );
  }
}
```

When on the `Page2`, swipe to go back to `Page1` and tap the background to trigger a new push.

```
[✓] Flutter (Channel unknown, v1.4.18, on Mac OS X 10.14.3 18D109, locale en-NL)
    • Flutter version 1.4.18 at /Users/sander/Development/.../flutter
    • Framework revision 8bea3fb2eb (2 weeks ago), 2019-04-11 13:11:22 -0700
    • Engine revision 72986c39ea
    • Dart version 2.2.1 (build 2.2.1-dev.3.1 None)
```

**Comment by LongCatIsLooong** [comment]
@spkersten is this issue still relevant? This looks like a dup of #29544.
