### ISSUE TITLE
iOS build fail after error message: argument type 'Int32List' can't be assigned to the parameter type 'Uint16List' in /lib/flare.dart

### ISSUE THREAD

**Issue by KylChiang** [flutter/flutter#31723]
## Steps to Reproduce

I've been stunk in iOS archive some days, another issue is about the certificate but solved.
HELP THANK YOU!

1. run $flutter build ios
2. got error message below:
```
Running Xcode build...                                                  
                                                   
 ├─Building Dart code...                                    14.1s
Xcode build done.                                           23.0s
Failed to build iOS app
Error output from Xcode build:
↳
    ** BUILD FAILED **


Xcode's output:
↳
    === BUILD TARGET Runner OF PROJECT Runner WITH CONFIGURATION Release ===
    Building AOT snapshot in release mode (ios-release)...          

    Compiler message:

    file:///Users/user/flutter/.pub-cache/hosted/pub.dartlang.org/flare_flutter-1.5.0/lib/flare.dart:1
    023:18: Error: The argument type 'Int32List' can't be assigned to the parameter type
    'Uint16List'.

     - 'Int32List' is from 'dart:typed_data'.

     - 'Uint16List' is from 'dart:typed_data'.

    Try changing the type of the parameter, or casting the argument to 'Uint16List'.

            indices: _indices, textureCoordinates: _uvBuffer);

                     ^

    Compiler terminated unexpectedly.
    Failed to build /Users/user/Documents/flutter/Project.

Encountered error while building for device.
```

### **Run `flutter run --verbose`**
```
(file:///Users/user/flutter/packages/flutter_tools/bin/flutter_tools.dart:8:3)
                        #36     _startIsolate.<anonymous closure>
(dart:isolate-patch/isolate_patch.dart:298:32)
                        #37     _RawReceivePortImpl._handleMessage
(dart:isolate-patch/isolate_patch.dart:171:12)
                    
                    
                        Failed to package /Users/user/Documents/flutter/Project.
                    
                    
[+13276 ms] Could not build the precompiled application for the device.
[ +101 ms] Error launching application on user@iPhone 7.
[   +5 ms] "flutter run" took 268,010ms.
[        ] "flutter run" took 268,010ms.

#0      throwToolExit (package:flutter_tools/src/base/common.dart:24:3)
#1      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:436:7)
<asynchronous suspension>
#2      FlutterCommand.verifyThenRunCommand
(package:flutter_tools/src/runner/flutter_command.dart:488:18)
#3      _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:77:64)
#4      _rootRunUnary (dart:async/zone.dart:1132:38)
#5      _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#6      _FutureListener.handleValue (dart:async/future_impl.dart:126:18)
#7      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:639:45)
#8      Future._propagateToListeners (dart:async/future_impl.dart:668:32)
#9      Future._complete (dart:async/future_impl.dart:473:7)
#10     _SyncCompleter.complete (dart:async/future_impl.dart:51:12)
#11     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:28:18)
#12     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:294:13)
#13     RunCommand.usageValues (package:flutter_tools/src/commands/run.dart)
#14     _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:77:64)
#15     _rootRunUnary (dart:async/zone.dart:1132:38)
#16     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#17     _FutureListener.handleValue (dart:async/future_impl.dart:126:18)
#18     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:639:45)
#19     Future._propagateToListeners (dart:async/future_impl.dart:668:32)
#20     Future._complete (dart:async/future_impl.dart:473:7)
#21     _SyncCompleter.complete (dart:async/future_impl.dart:51:12)
#22     _AsyncAwaitCompleter.complete.<anonymous closure> (dart:async-patch/async_patch.dart:33:20)
#23     _rootRun (dart:async/zone.dart:1124:13)
#24     _CustomZone.run (dart:async/zone.dart:1021:19)
#25     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:947:23)
#26     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#27     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#28     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:115:13)
#29     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:5)
```

### **Run `flutter analyze`**
```
Analyzing Project...                                                     

   info • This function has a return type of 'Route', but doesn't end with a return statement •
          lib/app.dart:129:3 • missing_return
   info • Unused import: 'dart:convert' • lib/data/model/serializer/serializers.dart:3:8 •
          unused_import
   info • Unused import: 'package:built_value/built_value.dart' •
          lib/data/model/serializer/serializers.dart:6:8 • unused_import
   info • Duplicate import • lib/home.dart:6:8 • duplicate_import
   info • 'birthday' is deprecated and shouldn't be used • lib/supplemental/build_admob.dart:36:3 •
          deprecated_member_use
   info • 'designedForFamilies' is deprecated and shouldn't be used •
          lib/supplemental/build_admob.dart:38:3 • deprecated_member_use
   info • 'gender' is deprecated and shouldn't be used • lib/supplemental/build_admob.dart:39:3 •
          deprecated_member_use
   info • 'MobileAdGender' is deprecated and shouldn't be used •
          lib/supplemental/build_admob.dart:40:7 • deprecated_member_use
   info • Unused import: 'package:flutter_html/flutter_html.dart' •
          lib/ui/detail/detail_page.dart:9:8 • unused_import
   info • Unused import: 'dart:convert' • lib/ui/detail/detail_page.dart:16:8 • unused_import
```

### **Run `flutter doctor -v`**
```
[✓] Flutter (Channel master, v1.5.9-pre.42, on Mac OS X 10.14.4 18E226, locale zh-Hant-TW)
    • Flutter version 1.5.9-pre.42 at /Users/user/flutter
    • Framework revision cbfa4e5483 (6 hours ago), 2019-04-26 20:25:02 -0700
    • Engine revision 7f753f8f52
    • Dart version 2.3.0 (build 2.3.0-dev.0.3 c46deebfb6)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/user/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.2.1, Build version 10E1001
    • ios-deploy 1.9.4
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.4)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 34.0.2
    • Dart plugin version 183.5901
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

[!] IntelliJ IDEA Community Edition (version 2017.3.4)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.dev/intellij-setup/#installing-the-plugins

[✓] VS Code (version 1.33.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 2.25.1

[✓] Connected device (1 available)
    • user@iPhone 7 • 1fb22a1bde1609e9daa**********197f59be402 • ios • iOS 12.2

! Doctor found issues in 1 category.
```

**Comment by KylChiang** [comment]
sorry wrong place.
