### ISSUE TITLE
Debug mode json parser error

### ISSUE THREAD

**Issue by jld3103** [flutter/flutter#31737]
## Steps to Reproduce
google/flutter-desktop-embedding#356
I was using the desktop embedding in debug mode and after an update it broke (For the error message look in the above referenced issue).
The error occurred because a float value was separated with a comma.

## Fix
The simple fix:
```
export LC_NUMERIC="en_US.UTF-8"
```

I hope there is a way to specify the numeric language in the dart json serializer.
Maybe this issue has to go deeper into the dart repo.

**Comment by jonahwilliams** [comment]
It looks like the JSON implementation on linux used a locale setting where it shouldn't have.

More context from original bug:


**Describe the bug**
I updated this project and the example app stopped working in debug mode. The app starts fine, but the logger/debugger stops. I'm getting this error:
```
Launching lib/main.dart on Linux in debug mode...
Building Linux application...                                           
Error initializing DevFS: FormatException: Unexpected character (at character
293)
...ns":0,"avgCollectionPeriodMillis":0,000000,"used":524288,"capacity":2097...
                                       ^


Lost connection to device.
Unhandled exception:
FormatException: Unexpected character (at character 293)
...ns":0,"avgCollectionPeriodMillis":0,000000,"used":524288,"capacity":2097...
                                       ^

#0      _ChunkedJsonParser.fail (dart:convert-patch/convert_patch.dart:1392:5)
#1      _ChunkedJsonParser.parse (dart:convert-patch/convert_patch.dart:922:48)
#2      _parseJson (dart:convert-patch/convert_patch.dart:29:10)
#3      JsonDecoder.convert (dart:convert/json.dart:493:36)
#4      JsonCodec.decode (dart:convert/json.dart:151:41)
#5      jsonDecode (dart:convert/json.dart:94:10)
#6      _MapStream._handleData (dart:async/stream_pipe.dart:227:21)
#7      _ForwardingStreamSubscription._handleData (dart:async/stream_pipe.dart:164:13)
#8      _rootRunUnary (dart:async/zone.dart:1132:38)
#9      _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#10     _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
#11     CastStreamSubscription._onData (dart:_internal/async_cast.dart:81:11)
#12     _rootRunUnary (dart:async/zone.dart:1132:38)
#13     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#14     _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
#15     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#16     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#17     _ForwardingStreamSubscription._add (dart:async/stream_pipe.dart:132:11)
#18     _ForwardingStream._handleData (dart:async/stream_pipe.dart:98:10)
#19     _ForwardingStreamSubscription._handleData (dart:async/stream_pipe.dart:164:13)
#20     _rootRunUnary (dart:async/zone.dart:1132:38)
#21     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#22     _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
#23     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#24     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#25     _SyncStreamController._sendData (dart:async/stream_controller.dart:764:19)
#26     _StreamController._add (dart:async/stream_controller.dart:640:7)
#27     _StreamController.add (dart:async/stream_controller.dart:586:5)
#28     new _WebSocketImpl._fromSocket.<anonymous closure> (dart:_http/websocket_impl.dart:1138:21)
#29     _rootRunUnary (dart:async/zone.dart:1132:38)
#30     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#31     _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
#32     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#33     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#34     _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:68:11)
#35     _EventSinkWrapper.add (dart:async/stream_transformers.dart:15:11)
#36     _WebSocketProtocolTransformer._messageFrameEnd (dart:_http/websocket_impl.dart:334:22)
#37     _WebSocketProtocolTransformer.add (dart:_http/websocket_impl.dart:229:46)
#38     _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:120:24)
#39     _rootRunUnary (dart:async/zone.dart:1132:38)
#40     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#41     _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
#42     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#43     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#44     _SyncStreamController._sendData (dart:async/stream_controller.dart:764:19)
#45     _StreamController._add (dart:async/stream_controller.dart:640:7)
#46     _StreamController.add (dart:async/stream_controller.dart:586:5)
#47     _Socket._onData (dart:io-patch/socket_patch.dart:1774:41)
#48     _rootRunUnary (dart:async/zone.dart:1136:13)
#49     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#50     _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
#51     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#52     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#53     _SyncStreamController._sendData (dart:async/stream_controller.dart:764:19)
#54     _StreamController._add (dart:async/stream_controller.dart:640:7)
#55     _StreamController.add (dart:async/stream_controller.dart:586:5)
#56     new _RawSocket.<anonymous closure> (dart:io-patch/socket_patch.dart:1323:33)
#57     _NativeSocket.issueReadEvent.issue (dart:io-patch/socket_patch.dart:844:14)
#58     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#59     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#60     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:115:13)
#61     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:5)
```
(Sometimes the stack trace is missing)

**Development Environment (please complete the following information):**
* OS: Ubuntu 19.04
* Developer tools version (Xcode, Visual Studio, or gcc): 
gcc version: gcc (Ubuntu 8.3.0-6ubuntu1) 8.3.0

**Doctor Output**
For build issues, please provide the output of `flutter doctor -v`:
```
[✓] Flutter (Channel dev, v1.5.8, on Linux, locale en_US.UTF-8)
    • Flutter version 1.5.8 at /home/jld3103/flutter
    • Framework revision 0ba67226ee (3 days ago), 2019-04-24 17:18:28 -0700
    • Engine revision c63d1cf9c9
    • Dart version 2.3.0 (build 2.3.0-dev.0.1 1f1592edce)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /home/jld3103/Android/Sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = /home/jld3103/Android/Sdk
    • Java binary at: /home/jld3103/.local/share/JetBrains/Toolbox/apps/AndroidStudio/ch-0/183.5452501/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b16-5323222)
    • All Android licenses accepted.

[✓] Android Studio (version 3.4)
    • Android Studio at /home/jld3103/.local/share/JetBrains/Toolbox/apps/AndroidStudio/ch-0/183.5452501
    • Flutter plugin version 35.0.1
    • Dart plugin version 183.5901
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b16-5323222)

[✓] Connected device (1 available)
    • Linux • Linux • linux-x64 • Linux

• No issues found!
```

**Comment by jld3103** [comment]
How are we going to fix this?

**Comment by mraleph** [comment]
The bug is in the `JSONWriter`, it uses locale dependent format:

```
void JSONWriter::PrintValue(double d) {
  PrintCommaIfNeeded();
  buffer_.Printf("%f", d);
}
``` 

/cc @rmacnak-google

**Comment by rmacnak-google** [comment]
@bkonyi

**Comment by bkonyi** [comment]
As far as I can tell, `vsnprintf` (the underlying method used to write into our buffer) doesn't take the system locale into account. I can't seem to find anywhere else in the VM that could result in it being changed either...

**Comment by bkonyi** [comment]
Hm, maybe we just need to set `LC_NUMERIC="en_US.UTF-8"` as part of our build?

**Comment by mraleph** [comment]
@bkonyi 

> As far as I can tell, vsnprintf (the underlying method used to write into our buffer) doesn't take the system locale into account. 

```
$ man 3 printf
...
       For some numeric conversions a radix character ("decimal point") or thousands' grouping character is used.  The actual character used depends on  the  LC_NUMERIC
       part of the locale.  (See setlocale(3).)  The POSIX locale uses '.' as radix character, and does not have a grouping character.  Thus,

               printf("%'.2f", 1234567.89);

       results in "1234567.89" in the POSIX locale, in "1234567,89" in the nl_NL locale, and in "1.234.567,89" in the da_DK locale.
```

> Hm, maybe we just need to set LC_NUMERIC="en_US.UTF-8" as part of our build?

I think we should just use `DoubleToCString` which uses Grisu, which always uses `.` as a separator. 

(That what `Double::ToCString` does - so we would match `JsonEncoder` output).

**Comment by multiarts** [comment]
Here solved with LC_NUMERIC, only the VS Code debug (F5) that presents the same error, but it executes normal the hot reload by the terminal.

**Comment by stuartmorgan** [comment]
Who is the right person to assign this to? This has already been reported several times by people trying desktop on Linux (which in desktop terms makes it a top-reported issue).

**Comment by mraleph** [comment]
@bkonyi could you change `JSONWriter::PrintValue(double d)` do use Grisu (double-convertion) instead of `printf`?

**Comment by bkonyi** [comment]
> @bkonyi could you change `JSONWriter::PrintValue(double d)` to use Grisu (double-convertion) instead of `printf`? Seems like a one line fix to me - so I am just assigning it to you.

Almost a one liner, but not quite :-) CL up for review [here](https://dart-review.googlesource.com/c/sdk/+/101101).
