### ISSUE TITLE
Can't build APK in release mode.

### ISSUE THREAD

**Issue by festelo** [flutter/flutter#31752]
Can't build APK in release mode, debug is cool. Flutter version I tried: v1.2.1 (last stable) and v1.5.4 (last beta). The same issue when build in codemagick
```
Initializing gradle...                                              1,5s
Resolving dependencies...                                           8,0s
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
U
nhandled exception:
dynamic is not a subtype of #lib24::Context in :async_temporary_1
#0      TypeEnvironment.type
Error (package:kernel/type_environment.dart:112:7)
#1      Expression.getStaticTypeAsInstanceOf (package:kernel/ast.dart:2227:11)
#2      MethodInvocation.getStaticType (package:kernel/ast.dart:2835:35)
#3      SummaryCollector._staticType (package:vm/transformations/type_flow/summary_collector.dart:677:32)
#4      SummaryCollector.visitMethodInvocation (package:vm/transformations/type_flow/summary_collector.dart:952:14)
#5      MethodInvocation.accept (package:kernel/ast.dart:2864:36)
#6      SummaryCollector._visit (package:vm/transformations/type_flow/summary_collector.dart:545:42)
#7      SummaryCollector.visitVariableSet (package:vm/transformations/type_flow/summary_collector.dart:1160:22)
#8      VariableSet.accept (package:kernel/ast.dart:2292:36)
#9      SummaryCollector._visit (package:vm/transformations/type_flow/summary_collector.dart:545:42)
#10     SummaryCollector.visitExpressionStatement (package:vm/transformations/type_flow/summary_collector.dart:1218:5)
#11     ExpressionStatement.a
ccept (package:kernel/ast.dart:3913:35)
#12     SummaryCollector._visit (package:vm/transformations/type_flow/summ
ary_collector.dart:545:42)
#13     List.forEach (dart:core-patch/growable_array.dart:278:8)
#14     SummaryCollector.visitBlock (package:vm/transformations/type_flow/summar
y_collector.dart:1188:21)
#15     Block.accept (package:kernel/ast.dart:3941:35)
#16
 SummaryCollector._visit (package:vm/transformations/type_flow/summary_collector.dart:545:42)
#17
     SummaryCollector.visitLabeledStatement (package:vm/transformations/type_flow/summary_colle
ctor.dart:1264:5)
#18     LabeledStatement.accept (package:kernel/ast.dart:4044:35)
#19     Summ
aryCollector._visit (package:vm/transformations/type_flow/summary_collector.dart:5
45:42)
#20     List.forEach (dart:core-patch/growable_array.dart:278:8)
#21     SummaryCollector.visitBlock (packa
ge:vm/transformations/type_flow/summary_collector.dart:1188:21)
#22     Block.ac
cept (package:kernel/ast.dart:3941:35)
#23     SummaryCollector._visit (pack
age:vm/transformations/type_flow/summary_collector.dart:545:42)
#24     SummaryCollector.visitTryCatch (package:vm/transformations/type_flow/summary_collector.dart:1290:5)
#25     TryCatch.accept (package:kernel/ast.dart:4387:35)
#26     SummaryCollec
tor._visit (package:vm/transformations/type_flow/summary_collector.dart:545:42)
#27     SummaryCollector._handleNestedFunctionNode (package:vm/transformations/type_flow/summary_c
ollector.dart:734:5)
#28     SummaryCollector.visitFunctionDeclaration (package:vm/transformations/type_
flow/summary_collector.dart:1248:5)
#29     FunctionDeclaration.accept (package:kernel/ast.dart:4682:35)
#30
   SummaryCollector._visit (package:vm/transformations/type_flow/summary_collector.dart:545:42)
#31     List.forEach (dart:core-patch/growable_array.dart:278:8)
#32
 SummaryCollector.visitBlock (package:vm/transformations/type_flow/summary_collector.dart:1188:21)
#33     Block.acce
pt (package:kernel/ast.dart:3941:35)
#34     SummaryCollector._visit (package:vm/transformations/type_flow/summary_collector.dart:545:42)
#35     SummaryCol
lector._handleNestedFunctionNode (package:vm/transformations/type_flow/summary_collector.d
art:734:5)
#36     SummaryCollector.visitFunctionExpression (package:
vm/transformations/type_flow/summary_collector.dart:842:5)
#37     FunctionExpression.accept
 (package:kernel/ast.dart:3746:36)
#38     SummaryCollector._visit (packa
ge:vm/transformations/type_flow/summary_collector.dart:545:42)
#39     SummaryCollecto
r._visitArguments (package:vm/transformations/type_flow/summary_collector.dart:559:16)
#40     SummaryCollector.visitMethodInvocation (package:vm/transformations/type_flow/summa
ry_collector.dart:917:18)
#41     MethodInvocation.accept (package:kernel/ast.dart:28
64:36)
#42     SummaryCollector._visit (package:vm/transformations/type_flow/summary_collector.dart:545:42)
#43     SummaryCollector._declareVariable (package:vm/transformations/type_flow/summary_collector.dart:62
7:27)
#44     SummaryCollector.visitVariableDeclaration (package:vm/transformations/type_flow/summary_
collector.dart:1312:15)
#45     VariableDeclaration.accept (package:kernel
/ast.dart:4647:35)
#46     SummaryCollector._visit (package:vm/transformations/type_flow/
summary_collector.dart:545:42)
#47     List.forEach (dart:core-patch/growable
_array.dart:278:8)
#48     SummaryCollector.visitBlock (package:vm/transformations/type_flo
w/summary_collector.dart:1188:21)
#49     Block.accept (package:kernel/ast.dart:3941:35)
#50     SummaryC
ollector._visit (package:vm/transformations/type_flow/summary_collector.dart:545:42)
#51     SummaryCollector.visitIfStatement (package:vm/tran
sformations/type_flow/summary_collector.dart:1255:5)
#52     IfStatement.accept (package:kernel/ast.da
rt:4329:35)
#53     SummaryCollector._visit (package:vm/transformations/type_flow/summary_collector.dart:545:42)
#54     List.forEach (dart:core-patch/growable_array.
dart:278:8)
#55     SummaryCollector.visitBlock (package:vm/transformations/type_
flow/summary_collector.dart:1188:21)
#56     Block.accept (package:kernel/a
st.dart:3941:35)
#57     SummaryCollector._visit (package:vm/transformations/type_flow/summary_collector.dart
:545:42)
#58     SummaryCollector.createSummary (package:vm/transformations/type_flow/summary_collector.d
art:460:9)
#59     TypeFlowAnalysis.getSummary (package:vm/transformat
ions/type_flow/analysis.dart:1375:52)
#60     _DirectInvocation._processFunction (package:vm/transformati
ons/type_flow/analysis.dart:236:14)
#61     _DirectInvocation.process (package
:vm/transformations/type_flow/analysis.dart:169:14)
#62     _WorkList.processInvocation (package:vm/tr
ansformations/type_flow/analysis.dart:1270:32)
#63     _WorkList.process (package:vm/transformations/type_flow/analysis.dart
:1250:7)
#64     TypeFlowAnalysis.process (package:vm/
transformations/type_flow/analysis.dart:1388:14)
#65
   transformComponent (package:vm/transformations/type_flow/transformer.dart:70:20)
#66     _runGlobalTrans
formations (package:vm/kernel_front_end.dart:392:5)
<asynchronous suspension
>
#67     compileToKernel (package:vm/kernel_front_end.dart:305:11)
<asynch
ronous suspension>
#68     FrontendCompiler.compile.<anonymous closure> (pac
kage:vm/frontend_server.dart:350:56)
#69     new Future.<anonymous closure> (dar
t:async/future.dart:176:37)
#70     _rootRun (dart:async/zone.dart:1120:38)

#71     _CustomZone.run (dart:async/zone.dart:1021:19)
#72     _Cust
omZone.runGuarded (dart:async/zone.dart:923:7)
#73     _CustomZone.bindCallb
ackGuarded.<anonymous closure> (dart:async/zone.dart:963:23)
#74
    _rootRun (dart:async/zone.dart:1124:13)
#75     _CustomZone.run (dart:async/
zone.dart:1021:19)
#76     _CustomZone.bindCallback.<anonymous closure> (dart
:async/zone.dart:947:23)
#77     Timer._createTimer.<anonymous closure> (da
rt:async-patch/timer_patch.dart:21:15)
#78     _Timer._runTimers (dart:is
olate-patch/timer_impl.dart:382:19)
#79     _Timer._handleMessage (dart:iso
late-patch/timer_impl.dart:416:5)
#80     _RawReceivePortImpl._handleMessag
e (dart:isolate-patch/isolate_patch.dart:171:12)

Compiler terminated unexpectedly.
Running Gradle task 'bundleRelease'...
Running Gradle task 'bundleRelease'... Done                        24,6s
```

**Comment by festelo** [comment]
Works fine with /dev channel
