### ISSUE TITLE
i can't show any dialog

### ISSUE THREAD

**Issue by minh98** [flutter/flutter#31766]
```
Performing hot restart...
Syncing files to device iPhone Xʀ...
Restarted application in 2,077ms.
flutter: ══╡ EXCEPTION CAUGHT BY GESTURE ╞═══════════════════════════════════════════════════════════════════
flutter: The following assertion was thrown while handling a gesture:
flutter: No MaterialLocalizations found.
flutter: MyApp widgets require MaterialLocalizations to be provided by a Localizations widget ancestor.
flutter: Localizations are used to generate many different messages, labels,and abbreviations which are used
flutter: by the material library.
flutter: To introduce a MaterialLocalizations, either use a  MaterialApp at the root of your application to
flutter: include them automatically, or add a Localization widget with a MaterialLocalizations delegate.
flutter: The specific widget that could not find a MaterialLocalizations ancestor was:
flutter:   MyApp
flutter: The ancestors of this widget were:
flutter:   [root]
flutter:
flutter: When the exception was thrown, this was the stack:
flutter: #0      debugCheckHasMaterialLocalizations.<anonymous closure> (package:flutter/src/material/debug.dart:124:7)
flutter: #1      debugCheckHasMaterialLocalizations (package:flutter/src/material/debug.dart:127:4)
flutter: #2      showDialog (package:flutter/src/material/dialog.dart:701:10)
flutter: #3      _MyAppState._tapOnImage (package:test_intern_2/main.dart:81:5)
flutter: #4      _MyAppState.buildGridView.<anonymous closure>.<anonymous closure> (package:test_intern_2/main.dart:64:15)
flutter: #5      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:120:24)
flutter: #6      TapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:242:9)
flutter: #7      TapGestureRecognizer.acceptGesture (package:flutter/src/gestures/tap.dart:204:7)
flutter: #8      GestureArenaManager.sweep (package:flutter/src/gestures/arena.dart:156:27)
flutter: #9      _WidgetsFlutterBinding&BindingBase&GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:218:20)
flutter: #10     _WidgetsFlutterBinding&BindingBase&GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:192:22)
flutter: #11     _WidgetsFlutterBinding&BindingBase&GestureBinding._handlePointerEvent (package:flutter/src/gestures/binding.dart:149:7)
flutter: #12     _WidgetsFlutterBinding&BindingBase&GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:101:7)
flutter: #13     _WidgetsFlutterBinding&BindingBase&GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:85:7)
flutter: #17     _invoke1 (dart:ui/hooks.dart:223:10)
flutter: #18     _dispatchPointerDataPacket (dart:ui/hooks.dart:144:5)
flutter: (elided 3 frames from package dart:async)
flutter:
flutter: Handler: onTap
flutter: Recognizer:
flutter:   TapGestureRecognizer#28e54(debugOwner: GestureDetector, state: ready, won arena, finalPosition:
flutter:   Offset(61.5, 173.5), sent tap down)
```

flutter doctor -v 
```
[✓] Flutter (Channel stable, v1.2.1, on Mac OS X 10.14.3 18D42, locale en-VN)
    • Flutter version 1.2.1 at /Users/tbm/Documents/Flutter/FlutterSDK/flutter
    • Framework revision 8661d8aecd (2 months ago), 2019-02-14 19:19:53 -0800
    • Engine revision 3757390fa4
    • Dart version 2.1.2 (build 2.1.2-dev.0.0 0a7dcf17eb)

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/tbm/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.2, Build version 10E125
    • ios-deploy 1.9.4
    • CocoaPods version 1.6.1

[✓] Android Studio (version 3.4)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 35.0.1
    • Dart plugin version 183.5901
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

[✓] Connected device (1 available)
    • iPhone Xʀ • 649D73AF-588F-4C7A-808C-E536884497FA • ios • com.apple.CoreSimulator.SimRuntime.iOS-12-2 (simulator)

• No issues found!
```

**Comment by minh98** [comment]
i was fixed. tks
