### ISSUE TITLE
how can i solve this error '_drawAreaBoundsOutdated == false': is not true.

### ISSUE THREAD

**Issue by anwar907** [flutter/flutter#31778]
## Steps to Reproduce

```
  @override
  Widget build(BuildContext context) {
    var judul = _judul;
    return Scaffold(
        body: Stack(
      children: <Widget>[
        Text(judul),
        Padding(
          padding: EdgeInsets.only(top: 15.0),
          child: Container(
            child: new charts.OrdinalComboChart(
              seriesList,
              animate: animate,
              behaviors: [
                new charts.SeriesLegend(),
                new charts.PanAndZoomBehavior(),
                new charts.InitialSelection(),
                new charts.LinePointHighlighter(),
              ],
              defaultRenderer: new charts.BarRendererConfig(
                symbolRenderer: new IconRender(Icons.cloud),
                // stackHorizontalSeparator: 10.0,
                groupingType: charts.BarGroupingType.grouped,
              ),
              customSeriesRenderers: [
                new charts.LineRendererConfig(customRendererId: 'customLine')
              ],
              // rtlSpec: charts.RTLSpec(axisDirection: charts.AxisDirection.reversed),
              
            ),
          ),
        )
      ],
    ));
  }```

## Logs

```(11562): ══╡ EXCEPTION CAUGHT BY RENDERING LIBRARY ╞═════════════════════════════════════════════════════════
I/flutter (11562): The following assertion was thrown during paint():
I/flutter (11562): 'package:charts_common/src/chart/layout/layout_manager_impl.dart': Failed assertion: line 115 pos
I/flutter (11562): 12: '_drawAreaBoundsOutdated == false': is not true.
I/flutter (11562): Either the assertion indicates an error in the framework itself, or we should provide substantially
I/flutter (11562): more information in this error message to help you determine and fix the underlying cause.
I/flutter (11562): In either case, please report this assertion by filing a bug on GitHub:
I/flutter (11562):   https://github.com/flutter/flutter/issues/new?template=BUG.md
I/flutter (11562): When the exception was thrown, this was the stack:
I/flutter (11562): #2      LayoutManagerImpl.drawableLayoutAreaBounds (package:charts_common/src/chart/layout/layout_manager_impl.dart:115:12)
I/flutter (11562): #3      BaseChart.drawableLayoutAreaBounds (package:charts_common/src/chart/common/base_chart.dart:414:22)
I/flutter (11562): #4      _LinePointLayoutView.paint (package:charts_common/src/chart/common/behavior/line_point_highlighter.dart:418:30)
I/flutter (11562): #5      BaseChart.paint.<anonymous closure> (package:charts_common/src/chart/common/base_chart.dart:579:12)
I/flutter (11562): #6      List.forEach (dart:core/runtime/libgrowable_array.dart:278:8)
I/flutter (11562): #7      BaseChart.paint (package:charts_common/src/chart/common/base_chart.dart:577:38)
I/flutter (11562): #8      ChartContainerCustomPaint.paint (package:charts_flutter/src/chart_container.dart:381:11)
I/flutter (11562): #9      RenderCustomPaint._paintWithPainter (package:flutter/src/rendering/custom_paint.dart:521:13)
I/flutter (11562): #10     RenderCustomPaint.paint (package:flutter/src/rendering/custom_paint.dart:559:7)
I/flutter (11562): #11     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2092:7)
I/flutter (11562): #12     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:173:13)
I/flutter (11562): #13     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:123:15)
I/flutter (11562): #14     RenderPointerListener.paint (package:flutter/src/rendering/proxy_box.dart:2629:11)
I/flutter (11562): #15     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2092:7)
I/flutter (11562): #16     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:173:13)
I/flutter (11562): #17     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:123:15)
I/flutter (11562): #18     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2092:7)
I/flutter (11562): #19     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:173:13)
I/flutter (11562): #20     _RenderCustomMultiChildLayoutBox&RenderBox&ContainerRenderObjectMixin&RenderBoxContainerDefaultsMixin.defaultPaint (package:flutter/src/rendering/box.dart:2273:15)
I/flutter (11562): #21     RenderCustomMultiChildLayoutBox.paint (package:flutter/src/rendering/custom_layout.dart:361:5)
I/flutter (11562): #22     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2092:7)
I/flutter (11562): #23     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:173:13)
I/flutter (11562): #24     RenderShiftedBox.paint (package:flutter/src/rendering/shifted_box.dart:70:15)
I/flutter (11562): #25     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2092:7)
I/flutter (11562): #26     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:173:13)
I/flutter (11562): #27     _RenderStack&RenderBox&ContainerRenderObjectMixin&RenderBoxContainerDefaultsMixin.defaultPaint (package:flutter/src/rendering/box.dart:2273:15)
I/flutter (11562): #28     RenderStack.paintStack (package:flutter/src/rendering/stack.dart:594:5)
I/flutter (11562): #29     RenderStack.paint (package:flutter/src/rendering/stack.dart:602:7)
I/flutter (11562): #30     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2092:7)
I/flutter (11562): #31     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:173:13)
I/flutter (11562): #32     _RenderCustomMultiChildLayoutBox&RenderBox&ContainerRenderObjectMixin&RenderBoxContainerDefaultsMixin.defaultPaint (package:flutter/src/rendering/box.dart:2273:15)
I/flutter (11562): #33     RenderCustomMultiChildLayoutBox.paint (package:flutter/src/rendering/custom_layout.dart:361:5)
I/flutter (11562): #34     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2092:7)
I/flutter (11562): #35     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:173:13)
I/flutter (11562): #36     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:123:15)
I/flutter (11562): #37     _RenderInkFeatures.paint (package:flutter/src/material/material.dart:504:11)
I/flutter (11562): #38     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2092:7)
I/flutter (11562): #39     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:173:13)
I/flutter (11562): #40     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:123:15)
I/flutter (11562): #41     RenderPhysicalModel.paint.<anonymous closure> (package:flutter/src/rendering/proxy_box.dart:1737:88)
I/flutter (11562): #42     ClipContext._clipAndPaint (package:flutter/src/painting/clip.dart:29:12)
I/flutter (11562): #43     ClipContext.clipRRectAndPaint (package:flutter/src/painting/clip.dart:49:5)
I/flutter (11562): #44     RenderPhysicalModel.paint (package:flutter/src/rendering/proxy_box.dart:1737:17)
I/flutter (11562): #45     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2092:7)
I/flutter (11562): #46     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:173:13)
I/flutter (11562): #47     _RenderCustomMultiChildLayoutBox&RenderBox&ContainerRenderObjectMixin&RenderBoxContainerDefaultsMixin.defaultPaint (package:flutter/src/rendering/box.dart:2273:15)
I/flutter (11562): #48     RenderCustomMultiChildLayoutBox.paint (package:flutter/src/rendering/custom_layout.dart:361:5)
I/flutter (11562): #49     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2092:7)
I/flutter (11562): #50     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:173:13)
I/flutter (11562): #51     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:123:15)
I/flutter (11562): #52     _RenderInkFeatures.paint (package:flutter/src/material/material.dart:504:11)
I/flutter (11562): #53     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2092:7)
I/flutter (11562): #54     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:173:13)
I/flutter (11562): #55     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:123:15)
I/flutter (11562): #56     PaintingContext.pushLayer (package:flutter/src/rendering/object.dart:370:12)
I/flutter (11562): #57     RenderPhysicalModel.paint (package:flutter/src/rendering/proxy_box.dart:1717:17)
I/flutter (11562): #58     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2092:7)
I/flutter (11562): #59     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:173:13)
I/flutter (11562): #60     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:123:15)
I/flutter (11562): #61     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2092:7)
I/flutter (11562): #62     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:173:13)
I/flutter (11562): #63     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:123:15)
I/flutter (11562): #64     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2092:7)
I/flutter (11562): #65     PaintingContext._repaintCompositedChild (package:flutter/src/rendering/object.dart:128:11)
I/flutter (11562): #66     PaintingContext.repaintCompositedChild (package:flutter/src/rendering/object.dart:96:5)
I/flutter (11562): #67     PipelineOwner.flushPaint (package:flutter/src/rendering/object.dart:853:29)
I/flutter (11562): #68     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding.drawFrame (package:flutter/src/rendering/binding.dart:331:19)
I/flutter (11562): #69     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding&WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:701:13)
I/flutter (11562): #70     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:268:5)
I/flutter (11562): #71     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:988:15)
I/flutter (11562): #72     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:928:9)
I/flutter (11562): #73     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:840:5)
I/flutter (11562): #77     _invoke (dart:ui/hooks.dart:209:10)
I/flutter (11562): #78     _drawFrame (dart:ui/hooks.dart:168:3)
I/flutter (11562): (elided 5 frames from class _AssertionError and package dart:async)
I/flutter (11562): The following RenderObject was being processed when the exception was fired:
I/flutter (11562):   ChartContainerRenderObject<String>#79818
I/flutter (11562):   creator: ChartContainer<String> ← Listener ← _GestureSemantics ← RawGestureDetector ←
I/flutter (11562):   GestureDetector ← LayoutId-[<chartContainer>] ← CustomMultiChildLayout ← OrdinalComboChart ←
I/flutter (11562):   Container ← Padding ← Stack ← MediaQuery ← ⋯
I/flutter (11562):   parentData: <none> (can use size)
I/flutter (11562):   constraints: BoxConstraints(w=320.0, h=405.0)
I/flutter (11562):   semantic boundary
I/flutter (11562):   size: Size(320.0, 405.0)
I/flutter (11562): This RenderObject has no descendants.
I/flutter (11562): ════════════════════════════════════════════════════════════════════════════════════════════════════
I/flutter (11562): Another exception was thrown: 'package:charts_common/src/chart/layout/layout_manager_impl.dart': Failed assertion: line 115 pos 12: '_drawAreaBoundsOutdated == false': is not true.
I/flutter (11562): Another exception was thrown: 'package:charts_common/src/chart/layout/layout_manager_impl.dart': Failed assertion: line 115 pos 12: '_drawAreaBoundsOutdated == false': is not true.
I/flutter (11562): Another exception was thrown: 'package:charts_common/src/chart/layout/layout_manager_impl.dart': Failed assertion: line 115 pos 12: '_drawAreaBoundsOutdated == false': is not true.```


```flutter doctor -v
[✓] Flutter (Channel stable, v1.2.1, on Linux, locale en_US.UTF-8)
    • Flutter version 1.2.1 at /home/boot/flutter
    • Framework revision 8661d8aecd (2 months ago), 2019-02-14 19:19:53 -0800
    • Engine revision 3757390fa4
    • Dart version 2.1.2 (build 2.1.2-dev.0.0 0a7dcf17eb)

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /home/boot/Android/Sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /home/boot/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b16-5323222)
    • All Android licenses accepted.

[✓] Android Studio (version 3.4)
    • Android Studio at /home/boot/android-studio
    • Flutter plugin version 34.0.2
    • Dart plugin version 183.5901
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b16-5323222)

[✓] IntelliJ IDEA Ultimate Edition (version 2018.3)
    • IntelliJ at /home/boot/idea-IU-183.5429.30
    • Flutter plugin version 34.0.2
    • Dart plugin version 183.6156.10

[✓] VS Code (version 1.31.1)
    • VS Code at /usr/share/code
    • Flutter extension version 2.25.1

[✓] Connected device (1 available)
    • SM J111F • 42005cdca14d6300 • android-arm • Android 5.1.1 (API 22)
```

**Comment by Huyston** [comment]
This happens to me when I update the chart series with a point that is out of the bounds of the x-axis. If I reload the page, it draws fine again. Maybe it is missing a reload method to redefine the bounds and redraw the chart.

**Comment by anwar907** [comment]
> This happens to me when I update the chart series with a point that is out of the bounds of the x-axis. If I reload the page, it draws fine again. Maybe it is missing a reload method to redefine the bounds and redraw the chart.

and now, do you have solved in your apps?

**Comment by krish30393** [comment]
In my case i use delay like follow  and my issue is solved 

Future.delayed(const Duration(milliseconds: 500), () {

// Here you can write your code

  setState(() {
    // render your chart here 
  });

});

**Comment by krish30393** [comment]
> > This happens to me when I update the chart series with a point that is out of the bounds of the x-axis. If I reload the page, it draws fine again. Maybe it is missing a reload method to redefine the bounds and redraw the chart.
> 
> and now, do you have solved in your apps?

Future.delayed(const Duration(milliseconds: 500), () {

// Here you can write your code

  setState(() {
    // Here you can write your code for open new view
  });

});

use this

**Comment by FannyFanFan** [comment]
excuse me ! so is there a better solution to this problem ?

**Comment by FannyFanFan** [comment]
@anwar907  excuse me ! so is there a better solution to this problem ?

**Comment by shaybc** [comment]
> @anwar907 excuse me ! so is there a better solution to this problem ?

Yes!

**instead of:** using a fixed delay, where you don't know how much time your asynchronous call will take (for instance load chart data from json on the web - you can't guess it will take 500 milliseconds), i.e _Future.delayed(const Duration(milliseconds: 500)..._

**Do this:** 
1. you'r widget should be a StatefulWidget
2. at the build(BuildContext context) method instead of you'r chart put a variable that you set as a (state) class var of the type _Widget_ lets call it 'lineChart'
3. at the beginning of the (state) class set the 'lineChart' var to be a default widget (for instance Text() with the word "Loading...")
4. now you can asynchronously load you'r data, and at the _'then'_ section - call _setState_ and set render you'r chart, and set it to the _'lineChart'_ var

sorry for the long example, but i wanted it to work so you can test it,
take a look at this working example code:


```

import 'package:charts_flutter/flutter.dart' as charts;
import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';

void main() => runApp(HomePage());

class PointModel {
  final String name;
  final int pointX;
  final int pointY;

  PointModel({this.name, this.pointX, this.pointY});
}

class Config {
  static List<PointModel> _chartDataList = [];
  static bool _loaded = false;

  static isLoaded() {
    return _loaded;
  }

  static loadChartDataList() async
  {
    // fetch data from web ...
    await loadFromWeb();
    _loaded = true;
  }

  static loadFromWeb()
  {
    // but here i will add test data
    _chartDataList.add(PointModel(pointX: 0, pointY: 24));
    _chartDataList.add(PointModel(pointX: 12, pointY: 40));
    _chartDataList.add(PointModel(pointX: 20, pointY: 18));
    _chartDataList.add(PointModel(pointX: 23, pointY: 30));
    _chartDataList.add(PointModel(pointX: 40, pointY: 12));
    _chartDataList.add(PointModel(pointX: 60, pointY: 15));
  }

  static getChartDataList() {
    if (!_loaded) loadChartDataList();
    return _chartDataList;
  }
}

class HomePage extends StatefulWidget {
  _HomePageState createState() => _HomePageState();
}

class _HomePageState extends State<HomePage> {
  List<charts.Series<PointModel, int>> _chartDataSeries = [];
  List<PointModel> chartDataList = [];
  Widget lineChart = Text("Loading ...");

  @override
  Widget build(BuildContext context) {
    // this is where i use Config class to perform my asynchronous load data
    // and check if it's loaded so this section will occur only once
    if (!Config.isLoaded()) Config.loadChartDataList().then((value) =>

    // call the setState() to tell flutter that it should re-evaluate the widget tree based
    // on this code changing the state of the class (the vars i.e. lineChart) and decide if
    // it wants to redraw, this is the reason to put lineChart as a var of the class
    // so when it changes - it changes the class state
    setState(() {
      print("Finished loading Json config from web!");
      chartDataList = Config.getChartDataList();

      // construct you'r chart data series
      _chartDataSeries.add(
        charts.Series(
          colorFn: (__, _) => charts.ColorUtil.fromDartColor(Colors.blue),
          id: 'My test Chart',
          data: chartDataList,
          domainFn: (PointModel pointModel, _) => pointModel.pointX,
          measureFn: (PointModel pointModel, _) => pointModel.pointY,
        ),
      );

      // now change the 'Loading...' widget with the real chart widget
      lineChart = charts.LineChart(_chartDataSeries,
          defaultRenderer: new charts.LineRendererConfig(
              includeArea: true, stacked: true),
          animate: true,
          animationDuration: Duration(seconds: 2),
          behaviors: [
            new charts.ChartTitle('Y axis name',
                behaviorPosition:
                charts.BehaviorPosition.bottom,
                titleOutsideJustification: charts
                    .OutsideJustification.middleDrawArea),
            new charts.ChartTitle('X axis name',
                behaviorPosition:
                charts.BehaviorPosition.start,
                titleOutsideJustification: charts
                    .OutsideJustification.middleDrawArea),
          ]);
    }));

    // here return your widget where the chart is drawn
    return MaterialApp(
      home: Padding(
        padding: EdgeInsets.all(8.0),
        child: Container(
          child: Center(
            child: Column(
              children: <Widget>[
                Text(
                  'Hello world line chart',
                  style: TextStyle(fontSize: 20.0,
                      fontWeight: FontWeight.bold,
                      color: Color(0xff747A80)),
                ),
                Expanded(
                  child: lineChart,
                ),
              ],
            ),
          ),
        ),
      ),
    );
  }
}

```

**Comment by RuchiraSheyan** [comment]
Can add this code before rendering the chart. 
sleep(const Duration(seconds:1));
https://stackoverflow.com/a/28776365/7870443

**Comment by Gabplay** [comment]
> > @anwar907 excuse me ! so is there a better solution to this problem ?
> 
> Yes!
> 
> **instead of:** using a fixed delay, where you don't know how much time your asynchronous call will take (for instance load chart data from json on the web - you can't guess it will take 500 milliseconds), i.e _Future.delayed(const Duration(milliseconds: 500)..._
> 
> **Do this:**
> 
> 1. you'r widget should be a StatefulWidget
> 2. at the build(BuildContext context) method instead of you'r chart put a variable that you set as a (state) class var of the type _Widget_ lets call it 'lineChart'
> 3. at the beginning of the (state) class set the 'lineChart' var to be a default widget (for instance Text() with the word "Loading...")
> 4. now you can asynchronously load you'r data, and at the _'then'_ section - call _setState_ and set render you'r chart, and set it to the _'lineChart'_ var
> 

Thank you that really worked for me, I was using a variable to change only the TimeSeriesChart data, but using a variable for the whole widget is the solution!!!
