### ISSUE TITLE
error on putting network image as marker icon google map flutter

### ISSUE THREAD

**Issue by DanialV** [flutter/flutter#31829]
I have network image and I want to use this as marker icon I convert it to BitmapDescriptor and place it into marker icon however it's not working.
I first convert network image to BitmapDescriptor.

```
      var _markerIconImage = new NetworkImage("https://cdn4.vectorstock.com/i/1000x1000/81/78/place-marker-icon-vector-6348178.jpg");
      _markerIconImage.obtainKey(new ImageConfiguration(
        size: Size(60,60),
      )).then((val) {
        var load = _markerIconImage.load(val);
        load.addListener((listener, err) async {
          ByteData iconByteData = await listener.image.toByteData();
          _markerIcon = BitmapDescriptor.fromBytes(iconByteData.buffer.asUint8List());
          });
        });
      });
```
then I place marker icon into google map marker widget

```
              new Marker(
                  markerId: MarkerId("sampleID"),
                  rotation: (deviceLocations[i]['last_location']['bearing']).toDouble(),
                  position: new LatLng(
                      deviceLocations[i]['last_location']['location']
                          ['latitude'],
                      deviceLocations[i]['last_location']['location']
                          ['longitude']),
                  icon: _markerIcon);
```
However, no icon showed on the map and it getting this error
```
D/skia    ( 9966): --- Failed to create image decoder with message 'unimplemented'
E/MethodChannel#plugins.flutter.io/google_maps_0( 9966): Failed to handle method call
E/MethodChannel#plugins.flutter.io/google_maps_0( 9966): java.lang.IllegalArgumentException: Unable to interpret bytes as a valid image.
E/MethodChannel#plugins.flutter.io/google_maps_0( 9966): 	at io.flutter.plugins.googlemaps.Convert.getBitmapFromBytes(Convert.java:74)
E/MethodChannel#plugins.flutter.io/google_maps_0( 9966): 	at io.flutter.plugins.googlemaps.Convert.toBitmapDescriptor(Convert.java:62)
E/MethodChannel#plugins.flutter.io/google_maps_0( 9966): 	at io.flutter.plugins.googlemaps.Convert.interpretMarkerOptions(Convert.java:308)
E/MethodChannel#plugins.flutter.io/google_maps_0( 9966): 	at io.flutter.plugins.googlemaps.MarkersController.addMarker(MarkersController.java:91)
E/MethodChannel#plugins.flutter.io/google_maps_0( 9966): 	at io.flutter.plugins.googlemaps.MarkersController.addMarkers(MarkersController.java:35)
E/MethodChannel#plugins.flutter.io/google_maps_0( 9966): 	at io.flutter.plugins.googlemaps.GoogleMapController.onMethodCall(GoogleMapController.java:224)
E/MethodChannel#plugins.flutter.io/google_maps_0( 9966): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:201)
E/MethodChannel#plugins.flutter.io/google_maps_0( 9966): 	at io.flutter.view.FlutterNativeView$PlatformMessageHandlerImpl.handleMessageFromDart(FlutterNativeView.java:188)
E/MethodChannel#plugins.flutter.io/google_maps_0( 9966): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:202)
E/MethodChannel#plugins.flutter.io/google_maps_0( 9966): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/MethodChannel#plugins.flutter.io/google_maps_0( 9966): 	at android.os.MessageQueue.next(MessageQueue.java:326)
E/MethodChannel#plugins.flutter.io/google_maps_0( 9966): 	at android.os.Looper.loop(Looper.java:160)
E/MethodChannel#plugins.flutter.io/google_maps_0( 9966): 	at android.app.ActivityThread.main(ActivityThread.java:6669)
E/MethodChannel#plugins.flutter.io/google_maps_0( 9966): 	at java.lang.reflect.Method.invoke(Native Method)
E/MethodChannel#plugins.flutter.io/google_maps_0( 9966): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
E/MethodChannel#plugins.flutter.io/google_maps_0( 9966): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
E/MethodChannel#plugins.flutter.io/google_maps_0( 9966): Caused by: java.lang.IllegalArgumentException: Unable to decode bytes as a valid bitmap.
E/MethodChannel#plugins.flutter.io/google_maps_0( 9966): 	at io.flutter.plugins.googlemaps.Convert.toBitmap(Convert.java:219)
E/MethodChannel#plugins.flutter.io/google_maps_0( 9966): 	at io.flutter.plugins.googlemaps.Convert.getBitmapFromBytes(Convert.java:71)
E/MethodChannel#plugins.flutter.io/google_maps_0( 9966): 	... 15 more
E/flutter ( 9966): [ERROR:flutter/lib/ui/ui_dart_state.cc(148)] Unhandled Exception: PlatformException(error, Unable to interpret bytes as a valid image., null)
E/flutter ( 9966): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:564:7)
E/flutter ( 9966): #1      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:302:33)
E/flutter ( 9966): <asynchronous suspension>
E/flutter ( 9966): #2      GoogleMapController._updateMarkers (file:///home/danial/Android/flutter/.pub-cache/hosted/pub.dartlang.org/google_maps_flutter-0.5.7/lib/src/controller.dart:107:19)
E/flutter ( 9966): <asynchronous suspension>
E/flutter ( 9966): #3      _GoogleMapState._updateMarkers (file:///home/danial/Android/flutter/.pub-cache/hosted/pub.dartlang.org/google_maps_flutter-0.5.7/lib/src/google_map.dart:210:16)
E/flutter ( 9966): <asynchronous suspension>
E/flutter ( 9966): #4      _GoogleMapState.didUpdateWidget (file:///home/danial/Android/flutter/.pub-cache/hosted/pub.dartlang.org/google_maps_flutter-0.5.7/lib/src/google_map.dart:192:5)
E/flutter ( 9966): #5      StatefulElement.update (package:flutter/src/widgets/framework.dart:3879:58)
E/flutter ( 9966): #6      Element.updateChild (package:flutter/src/widgets/framework.dart:2748:15)
E/flutter ( 9966): #7      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3747:16)
E/flutter ( 9966): #8      Element.rebuild (package:flutter/src/widgets/framework.dart:3559:5)
E/flutter ( 9966): #9      StatelessElement.update (package:flutter/src/widgets/framework.dart:3796:5)
E/flutter ( 9966): #10     Element.updateChild (package:flutter/src/widgets/framework.dart:2748:15)
E/flutter ( 9966): #11     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3747:16)
E/flutter ( 9966): #12     Element.rebuild (package:flutter/src/widgets/framework.dart:3559:5)
E/flutter ( 9966): #13     StatefulElement.update (package:flutter/src/widgets/framework.dart:3894:5)
E/flutter ( 9966): #14     Element.updateChild (package:flutter/src/widgets/framework.dart:2748:15)
E/flutter ( 9966): #15     RenderObjectElement.updateChildren (package:flutter/src/widgets/framework.dart:4601:32)
E/flutter ( 9966): #16     MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4992:17)
E/flutter ( 9966): #17     Element.updateChild (package:flutter/src/widgets/framework.dart:2748:15)
E/flutter ( 9966): #18     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3747:16)
E/flutter ( 9966): #19     Element.rebuild (package:flutter/src/widgets/framework.dart:3559:5)
E/flutter ( 9966): #20     StatelessElement.update (package:flutter/src/widgets/framework.dart:3796:5)
E/flutter ( 9966): #21     Element.updateChild (package:flutter/src/widgets/framework.dart:2748:15)
E/flutter ( 9966): #22     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3747:16)
E/flutter ( 9966): #23     Element.rebuild (package:flutter/src/widgets/framework.dart:3559:5)
E/flutter ( 9966): #24     ProxyElement.update (package:flutter/src/widgets/framework.dart:4006:5)
E/flutter ( 9966): #25     Element.updateChild (package:flutter/src/widgets/framework.dart:2748:15)
E/flutter ( 9966): #26     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3747:16)
E/flutter ( 9966): #27     Element.rebuild (package:flutter/src/widgets/framework.dart:3559:5)
E/flutter ( 9966): #28     ProxyElement.update (package:flutter/src/widgets/framework.dart:4006:5)
E/flutter ( 9966): #29     Element.updateChild (package:flutter/src/widgets/framework.dart:2748:15)
E/flutter ( 9966): #30     RenderObjectElement.updateChildren (package:flutter/src/widgets/framework.dart:4601:32)
E/flutter ( 9966): #31     MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4992:17)
E/flutter ( 9966): #32     Element.updateChild (package:flutter/src/widgets/framework.dart:2748:15)
E/flutter ( 9966): #33     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3747:16)
E/flutter ( 9966): #34     Element.rebuild (package:flutter/src/widgets/framework.dart:3559:5)
E/flutter ( 9966): #35     StatefulElement.update (package:flutter/src/widgets/framework.dart:3894:5)
E/flutter ( 9966): #36     Element.updateChild (package:flutter/src/widgets/framework.dart:2748:15)
E/flutter ( 9966): #37     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3747:16)
E/flutter ( 9966): #38     Element.rebuild (package:flutter/src/widgets/framework.dart:3559:5)
E/flutter ( 9966): #39     ProxyElement.update (package:flutter/src/widgets/framework.dart:4006:5)
E/flutter ( 9966): #40     Element.updateChild (package:flutter/src/widgets/framework.dart:2748:15)
E/flutter ( 9966): #41     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3747:16)
```

Here is my flutter doctor -v output

```
[✓] Flutter (Channel stable, v1.2.1, on Linux, locale en_US.UTF-8)
    • Flutter version 1.2.1 at /home/danial/Android/flutter
    • Framework revision 8661d8aecd (2 months ago), 2019-02-14 19:19:53 -0800
    • Engine revision 3757390fa4
    • Dart version 2.1.2 (build 2.1.2-dev.0.0 0a7dcf17eb)

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /home/danial/Android/Sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /home/danial/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)
    • All Android licenses accepted.

[✓] Android Studio (version 3.3)
    • Android Studio at /home/danial/android-studio
    • Flutter plugin version 34.0.1
    • Dart plugin version 182.5215
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)

[!] VS Code (version 1.33.1)
    • VS Code at /usr/share/code
    ✗ Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 9 (API 28) (emulator)
```

**Comment by ertgl** [comment]
@DanialV You might need to check `format` parameter in the `toByteData` method, since it's default to `ImageByteFormat.rawRgba`.

https://docs.flutter.io/flutter/dart-ui/Image/toByteData.html

**Comment by BondarenkoStas** [comment]
@DanialV did you resolve the issue?

**Comment by iapicca** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
  
Thanks for your contribution.
