### ISSUE TITLE
Error after config and run ios flavor flag

### ISSUE THREAD

**Issue by PauloKeller** [flutter/flutter#31863]
- Flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, v1.2.1, on Mac OS X 10.14.4 18E226, locale pt-BR)
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[✓] iOS toolchain - develop for iOS devices (Xcode 10.2.1)
[✓] Android Studio (version 3.3)
[✓] VS Code (version 1.32.3)
[✓] Connected device (1 available)

After config a homol flavor following the current flavor guide **https://medium.com/@salvatoregiordanoo/flavoring-flutter-392aaa875f36** 

when I run `flutter run --flavor homol`, the following error was throw:

> === BUILD TARGET Runner OF PROJECT Runner WITH CONFIGURATION Debug ===

    ld: framework not found App
    clang: error: linker command failed with exit code 1 (use -v to see invocation)

- Log
>/Users/paulokeller/Library/Developer/Xcode/DerivedData/Runner-enkqhwessloskigvlyeekibwfqwm/Build/Intermediates.noindex/Runner.build/Debug-homol-iphonesimulator
                   /Runner.build/Objects-normal/x86_64/Runner_dependency_info.dat -o
                   /Users/paulokeller/Workspace/flutter/kipstone-flutter/build/ios/Debug-homol-iphonesimulator/Runner.app/Runner
               ld: framework not found App
               clang: error: linker command failed with exit code 1 (use -v to see invocation)
           
           
>[  +52 ms] Could not build the application for the simulator.
>[   +2 ms] Error launching application on iPhone Xʀ.
>[   +6 ms] "flutter run" took 89.877ms.
>[        ] "flutter run" took 89.877ms.

>#0      throwToolExit (package:flutter_tools/src/base/common.dart:24:3)
>#1      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:411:7)
><asynchronous suspension>
>#2      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner>/flutter_command.dart:545:18)
>#3      _asyncThenWrapperHelper.<anonymous closure> (dart:async/runtime/libasync_patch.dart:77:64)
>#4      _rootRunUnary (dart:async/zone.dart:1132:38)
>#5      _CustomZone.runUnary (dart:async/zone.dart:1029:19)
>#6      _FutureListener.handleValue (dart:async/future_impl.dart:126:18)
>#7      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:639:45)
>#8      Future._propagateToListeners (dart:async/future_impl.dart:668:32)
#9      Future._complete (dart:async/future_impl.dart:473:7)
#10     _SyncCompleter.complete (dart:async/future_impl.dart:51:12)
#11     _AsyncAwaitCompleter.complete (dart:async/runtime/libasync_patch.dart:28:18)
#12     _completeOnAsyncReturn (dart:async/runtime/libasync_patch.dart:294:13)
#13     RunCommand.usageValues (package:flutter_tools/src/commands/run.dart)
#14     _asyncThenWrapperHelper.<anonymous closure> (dart:async/runtime/libasync_patch.dart:77:64)
#15     _rootRunUnary (dart:async/zone.dart:1132:38)
#16     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#17     _FutureListener.handleValue (dart:async/future_impl.dart:126:18)
#18     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:639:45)
#19     Future._propagateToListeners (dart:async/future_impl.dart:668:32)
#20     Future._complete (dart:async/future_impl.dart:473:7)
#21     _SyncCompleter.complete (dart:async/future_impl.dart:51:12)
#22     _AsyncAwaitCompleter.complete.<anonymous closure> (dart:async/runtime/libasync_patch.dart:33:20)
#23     _rootRun (dart:async/zone.dart:1124:13)
#24     _CustomZone.run (dart:async/zone.dart:1021:19)
#25     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:947:23)
#26     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#27     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#28     _runPendingImmediateCallback (dart:isolate/runtime/libisolate_patch.dart:115:13)
#29     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:172:5)

**Comment by PauloKeller** [comment]
Related to [#3](https://github.com/iakta/flutter_flavors/issues/3)
