### ISSUE TITLE
iOS Add2App profile mode can't attach/find observatory

### ISSUE THREAD

**Issue by dnfield** [flutter/flutter#31872]
`flutter run --profile` on a iPhone allows you to attach and use the observatory in a normal way.

However, running in a profile mode add2app scenario does not.

**Comment by dnfield** [comment]
For some reason, it looks like `DartServiceIsolate:NotifyServerState` isn't getting called in this mode.

**Comment by dnfield** [comment]
@dannyvalente - I was able to get this working eventually by what I suspect was some mix of cleans and restarts.  This makes me suspect that we're caching some build artifact incorrectly.

Can you try to delete the `build` directory in your Flutter application, and run things in profile mode again and see if it works?  If not, there's something else going on here that I'm missing.

**Comment by dannyvalente** [comment]
@dnfield, thanks for the tip. I tried that and I think you're right as now I see the app outputting that the observatory is listening, however flutter attach fails to attach every time with the following:

Waiting for a connection from Flutter on Danny's iPhone 6...
Done.
Syncing files to device Danny's iPhone 6...
Error -32601 received from application: Method not found

**Comment by dnfield** [comment]
Well that's progress at least.  So one issue is that we're not properly doing a rebuild (or just not doing a clean?) when we change modes in the add2app case.

For the method not found, does that consistently reproduce?  Do you get anything more if you run the application in verbose logging mode?

**Comment by jonahwilliams** [comment]
In this case `flutter doctor -v`?

I've disabled all of the fingerprinting done by the tool itself

**Comment by dannyvalente** [comment]
Yes i can reproduce this consistently.

How do you run in verbose logging mode? Is this documented in the add2app documentation?

**Comment by dnfield** [comment]
Ahh sorry, I keep forgetting - for add2app it should just be verbose already.

Do you get any interesting output in the Xcode console when you see the method not found in your attach window?

**Comment by dannyvalente** [comment]
No I checked that and there was no output after it says that the observatory is listening. There were no exceptions or any output at all.

**Comment by dnfield** [comment]
I haven't been able to reproduce this.  Are you able to reproduce it with a "fresh" add2app setup?

**Comment by dannyvalentesonos** [comment]
@dnfield Does this help? After the initial error, I hit the Hot Reload button in Android Studio, and this output came up. (Still nothing in the XCode output console though).

Initializing hot reload...
Syncing files to device Danny's iPhone 6...
Error 100 received from application: Feature is disabled
Unhandled exception:
{code: 100, message: Feature is disabled, data: {request: {method: _reloadSources, params: {pause: true, rootLibUri: file:///private/var/mobile/Containers/Data/Application/ACDEAD4D-D07B-489F-A8F0-174888788C48/tmp/flutter_moduleQZxSIn/flutter_module/lib/main.dart.incremental.dill, packagesUri: file:///private/var/mobile/Containers/Data/Application/ACDEAD4D-D07B-489F-A8F0-174888788C48/tmp/flutter_moduleQZxSIn/flutter_module/.packages, isolateId: isolates/865762522}}, details: Compiler is disabled in AOT mode.}}
#0      _rootHandleUncaughtError.<anonymous closure> (dart:async/zone.dart:1112:29)
#1      _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#2      _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#3      _runPendingImmediateCallback (dart:isolate/runtime/libisolate_patch.dart:115:13)
#4      _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:172:5)

I plan on trying with a newer version of Flutter to see if it helps. (I'm using Flutter 1.2.1 here)

**Comment by dnfield** [comment]
Hot reload isn't supported in profile.  That's expected.

**Comment by dnfield** [comment]
Can you try `flutter attach --profile`?

**Comment by dannyvalentesonos** [comment]
That seems to work.

flutter_module danny.valente$ flutter attach --profile
Waiting for a connection from Flutter on Danny's iPhone 6...
Done.

An Observatory debugger and profiler on Danny's iPhone 6 is available at http://127.0.0.1:1025/
For a more detailed help message, press "h". To detach, press "d"; to quit, press "q".


And in the observatory, I can get some information. I can't seem to get the CPU profile or metrics views to do much though. Is there something you want me to look at to to see that we're good? I can see the timeline view, which is good.

**Comment by dnfield** [comment]
Woohoo!

/cc @liyuqian @cbracken - they'd have more information on using that to create a Skia trace.

This bug should stay open until we properly clean the assets between builds for Add2App.

**Comment by dannyvalentesonos** [comment]
Is there a way we could get this to work with Android Studio though? Or is there no way to get the Widget Inspector to work on profile builds? I suppose it's not something we should be trying to do with a profile build anyway...

**Comment by dannyvalentesonos** [comment]
Thanks for the help @dnfield by the way!!

**Comment by dnfield** [comment]
@jmagman - is this of interest to you?

The root cause appears to be that add to app use cases on iOS are not properly clearing out old build artifacts between builds (or perhaps when switching build modes e.g. from debug to profile).

**Comment by jmagman** [comment]
I can take a look!

**Comment by jmagman** [comment]
The `MyApp/my_flutter/.ios/Runner.xcodeproj` Profile build configuration is using the Config/Release.xcconfig as its base, which still contains `FLUTTER_BUILD_MODE=release` instead of dropping back to parse the build config as "Profile".  So in my testing the observatory never even started when the host was running a Profile build config.
See:
https://github.com/flutter/flutter/blob/master/packages/flutter_tools/templates/module/ios/host_app_ephemeral/Config.tmpl/Release.xcconfig
https://github.com/flutter/flutter/blob/master/packages/flutter_tools/templates/module/ios/host_app_ephemeral/Runner.xcodeproj.tmpl/project.pbxproj.tmpl#L261
https://github.com/flutter/flutter/blob/master/packages/flutter_tools/bin/xcode_backend.sh#L62 
https://github.com/flutter/flutter/pull/23387/files#diff-0d00f38df3883291f23cee8074ac075d.

However that's not getting me to the "Method not found" stage since flutter attach can't even connect to the observatory (that error message means the method is missing from the VM service).  When I fix that problem, I'm able to `flutter attach` and take screenshots swapping back and forth from debug and profile.  So I wasn't able to reproduce the exact reported issue.

**Comment by jmagman** [comment]
I created https://github.com/flutter/flutter/issues/35298 to track the issue that the observatory doesn't start.  We can keep tracking the "Method not found" issue here.

**Comment by jmagman** [comment]
> The `MyApp/my_flutter/.ios/Runner.xcodeproj` Profile build configuration is using the Config/Release.xcconfig as its base, which still contains `FLUTTER_BUILD_MODE=release` instead of dropping back to parse the build config as "Profile". 

This was a red herring since the host app was correctly passing the --profile flag to `Flutter run`.  See https://github.com/flutter/flutter/issues/35302.
