### ISSUE TITLE
Code from example of dynamic ListView’s update results in error

### ISSUE THREAD

**Issue by mikepyts** [flutter/flutter#31892]
## Steps to Reproduce
1. Open [flutter for Android developers guide](https://flutter.dev/docs/get-started/flutter-for/android-devs)
2. Navigate to [how do I update ListView’s dynamically?](https://flutter.dev/docs/get-started/flutter-for/android-devs#how-do-i-update-listviews-dynamically)
3. Copy code from first example to main.dart and run on any Android device
4. Tap on any list item.

## Actual results:
You will get an error ```type 'List<dynamic>' is not a subtype of type 'List<Widget>'```

## Visual presentation:
http://joxi.ru/52aang7IEbGy12

## Possible solution:
Change ```List widgets = <Widget>[]``` to ```List<Widget> widgets = []``` in widget list declaration

## Logs
```
I/flutter ( 7668): ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
I/flutter ( 7668): The following assertion was thrown building SampleAppPage(dirty, state: _SampleAppPageState#01dc8):
I/flutter ( 7668): type 'List<dynamic>' is not a subtype of type 'List<Widget>'
I/flutter ( 7668): 
I/flutter ( 7668): Either the assertion indicates an error in the framework itself, or we should provide substantially
I/flutter ( 7668): more information in this error message to help you determine and fix the underlying cause.
I/flutter ( 7668): In either case, please report this assertion by filing a bug on GitHub:
I/flutter ( 7668):   https://github.com/flutter/flutter/issues/new?template=BUG.md
I/flutter ( 7668): 
I/flutter ( 7668): When the exception was thrown, this was the stack:
I/flutter ( 7668): #0      _SampleAppPageState.build (package:graph/main.dart:45:32)
I/flutter ( 7668): #1      StatefulElement.build (package:flutter/src/widgets/framework.dart:3825:27)
I/flutter ( 7668): #2      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3739:15)
I/flutter ( 7668): #3      Element.rebuild (package:flutter/src/widgets/framework.dart:3565:5)
I/flutter ( 7668): #4      BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2278:33)
I/flutter ( 7668): #5      _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding&WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:700:20)
I/flutter ( 7668): #6      _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:286:5)
I/flutter ( 7668): #7      _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1012:15)
I/flutter ( 7668): #8      _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:952:9)
I/flutter ( 7668): #9      _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:864:5)
I/flutter ( 7668): #13     _invoke (dart:ui/hooks.dart:219:10)
I/flutter ( 7668): #14     _drawFrame (dart:ui/hooks.dart:178:3)
I/flutter ( 7668): (elided 3 frames from package dart:async)
I/flutter ( 7668): ════════════════════════════════════════════════════════════════════════════════════════════════════
```

```
```

```
C:\Flutter\bin\flutter.bat doctor --verbose
[√] Flutter (Channel beta, v1.5.4, on Microsoft Windows [Version 10.0.17763.437], locale en-US)
    • Flutter version 1.5.4 at C:\Flutter
    • Framework revision b593f5167b (9 days ago), 2019-04-22 07:51:33 -0700
    • Engine revision ca31a7c57b
    • Dart version 2.3.0 (build 2.3.0-dev.0.1 cf4444b803)

[!] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at C:\Users\Asus\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses

[√] Android Studio (version 3.4)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 35.0.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

[!] VS Code (version 1.32.3)
    • VS Code at C:\Users\Asus\AppData\Local\Programs\Microsoft VS Code
    X Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[√] Connected device (2 available)
    • LEX626                    • LEY8A07370008961 • android-arm64 • Android 6.0 (API 23)
    • Android SDK built for x86 • emulator-5554    • android-x86   • Android 9 (API 28) (emulator)

! Doctor found issues in 2 categories.
```

**Comment by BondarenkoStas** [comment]
@mikejurka seems that it's fixed, i tried and it run just fine, i think it's safe to close the issue.
