### ISSUE TITLE
startAfterDocument not working on Android

### ISSUE THREAD

**Issue by creativecreatorormaybenot** [flutter/flutter#31913]
I know that this feature is really fresh (https://github.com/flutter/plugins/pull/1476), however, I planned on switching to this convenience method for a while since I was doing pagination manually already.

Basically, previously I used the following:

```
query.startAfter([document['fieldOne'], document['fieldTwo'], document.documentID]).getDocuments()
```

I supplied the fields to `startAfter` manually and now I tried to just swap that with `query.startAfterDocument(document).getDocuments()`, but it is not working.

At first it just returned the documents from the start instead of paginating and after restarting the application, I am now seeing the following exception all the time:

```
E/MethodChannel#plugins.flutter.io/cloud_firestore(13420): Failed to handle method call
E/MethodChannel#plugins.flutter.io/cloud_firestore(13420): java.lang.IllegalArgumentException: Invalid query. Expected a string for document ID in startAfter(), but got null.
E/MethodChannel#plugins.flutter.io/cloud_firestore(13420): 	at com.google.firebase.firestore.Query.boundFromFields(com.google.firebase:firebase-firestore@@18.2.0:656)
E/MethodChannel#plugins.flutter.io/cloud_firestore(13420): 	at com.google.firebase.firestore.Query.startAfter(com.google.firebase:firebase-firestore@@18.2.0:523)
E/MethodChannel#plugins.flutter.io/cloud_firestore(13420): 	at io.flutter.plugins.firebase.cloudfirestore.CloudFirestorePlugin.getQuery(CloudFirestorePlugin.java:219)
E/MethodChannel#plugins.flutter.io/cloud_firestore(13420): 	at io.flutter.plugins.firebase.cloudfirestore.CloudFirestorePlugin.onMethodCall(CloudFirestorePlugin.java:559)
E/MethodChannel#plugins.flutter.io/cloud_firestore(13420): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:201)
E/MethodChannel#plugins.flutter.io/cloud_firestore(13420): 	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:88)
E/MethodChannel#plugins.flutter.io/cloud_firestore(13420): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:219)
E/MethodChannel#plugins.flutter.io/cloud_firestore(13420): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/MethodChannel#plugins.flutter.io/cloud_firestore(13420): 	at android.os.MessageQueue.next(MessageQueue.java:326)
E/MethodChannel#plugins.flutter.io/cloud_firestore(13420): 	at android.os.Looper.loop(Looper.java:160)
E/MethodChannel#plugins.flutter.io/cloud_firestore(13420): 	at android.app.ActivityThread.main(ActivityThread.java:6669)
E/MethodChannel#plugins.flutter.io/cloud_firestore(13420): 	at java.lang.reflect.Method.invoke(Native Method)
E/MethodChannel#plugins.flutter.io/cloud_firestore(13420): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
E/MethodChannel#plugins.flutter.io/cloud_firestore(13420): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
E/flutter (13420): [ERROR:flutter/lib/ui/ui_dart_state.cc(148)] Unhandled Exception: PlatformException(error, Invalid query. Expected a string for document ID in startAfter(), but got null., null)
```

I looked at the Java implementation, but I could not quite figure out why it does not work.  
I will just switch back to manual pagination for now, so no worries about my case.

**Comment by collinjackson** [comment]
@creativecreatorormaybenot I'm not clear on why you self-closed this issue, can you clarify?

**Comment by creativecreatorormaybenot** [comment]
@collinjackson Because https://github.com/flutter/flutter/issues/32031 is the actual issue. I think that `orderBy(FieldPath.documentID())` is the problem nonetheless.
