### ISSUE TITLE
Plugging an iPhone into a Mac causes ideviceinfo error

### ISSUE THREAD

**Issue by mjohnsullivan** [flutter/flutter#32008]
Plugging an iPhone into a Mac caused the following error to occur when running 'flutter doctor'. This went away after the phone was unplugged.

```
flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel beta, v1.5.4-hotfix.1, on Mac OS X 10.14.4 18E226, locale en-US)
⣻Unhandled exception:
Exception: ideviceinfo returned an error:
ERROR: Could not connect to lockdownd, error code -2

#0      IMobileDevice.getInfoForDevice (package:flutter_tools/src/ios/mac.dart:141:9)
<asynchronous suspension>
#1      IOSDevice.getAttachedDevices (package:flutter_tools/src/ios/devices.dart:156:55)
<asynchronous suspension>
#2      IOSDevices.pollingGetDevices (package:flutter_tools/src/ios/devices.dart:110:57)
#3      PollingDeviceDiscovery.devices (package:flutter_tools/src/device.dart:186:52)
<asynchronous suspension>
#4      DeviceManager.getAllConnectedDevices (package:flutter_tools/src/device.dart:114:46)
<asynchronous suspension>
#5      DeviceValidator.validate (package:flutter_tools/src/doctor.dart:705:54)
<asynchronous suspension>
... 
```

**Comment by SunlightBro** [comment]
```
    ✗ libimobiledevice and ideviceinstaller are not installed or require updating. To update, run:
        brew uninstall --ignore-dependencies libimobiledevice
        brew install --HEAD libimobiledevice
        brew install ideviceinstaller
```
https://github.com/flutter/flutter/issues/12628

**Comment by amirh** [comment]
I just ran into the same issue, while the ideviceinfo issue resolved itself somehow, `flutter doctor` shouldn't crash when it happens, my crashing flutter doctor output:

```
 flutter doctor -v
[✓] Flutter (Channel master, v1.5.9-pre.244, on Mac OS X 10.14.4 18E227, locale en-US)
    • Flutter version 1.5.9-pre.244 at /Users/amirha/git/flutter/flutter
    • Framework revision bcae3563d4 (65 minutes ago), 2019-05-14 11:04:16 -0700
    • Engine revision a89cf80d4d
    • Dart version 2.3.1 (build 2.3.1-dev.0.0 a0290f823c)

⣻Unhandled exception:
Exception: ideviceinfo returned an error:
ERROR: Could not connect to lockdownd, error code -8

#0      IMobileDevice.getInfoForDevice (package:flutter_tools/src/ios/mac.dart:141:9)
<asynchronous suspension>
#1      IOSDevice.getAttachedDevices (package:flutter_tools/src/ios/devices.dart:157:55)
<asynchronous suspension>
#2      IOSDevices.pollingGetDevices (package:flutter_tools/src/ios/devices.dart:111:57)
#3      PollingDeviceDiscovery.devices (package:flutter_tools/src/device.dart:188:52)
<asynchronous suspension>
#4      DeviceManager.getAllConnectedDevices (package:flutter_tools/src/device.dart:116:46)
<asynchronous suspension>
#5      DeviceValidator.validate (package:flutter_tools/src/doctor.dart:705:54)
<asynchronous suspension>
#6      Doctor.startValidatorTasks (package:flutter_tools/src/doctor.dart:129:52)
#7      Doctor.diagnose (package:flutter_tools/src/doctor.dart:200:41)
#8      _AsyncAwaitCompleter.start (dart:async-patch/async_patch.dart:49:6)
#9      Doctor.diagnose (package:flutter_tools/src/doctor.dart:190:24)
#10     DoctorCommand.runCommand (package:flutter_tools/src/commands/doctor.dart:48:39)
#11     _AsyncAwaitCompleter.start (dart:async-patch/async_patch.dart:49:6)
#12     DoctorCommand.runCommand (package:flutter_tools/src/commands/doctor.dart:34:42)
#13     FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:488:18)
#14     _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:77:64)
#15     _rootRunUnary (dart:async/zone.dart:1132:38)
#16     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#17     _FutureListener.handleValue (dart:async/future_impl.dart:126:18)
#18     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:639:45)
#19     Future._propagateToListeners (dart:async/future_impl.dart:668:32)
#20     Future._complete (dart:async/future_impl.dart:473:7)
#21     _SyncCompleter.complete (dart:async/future_impl.dart:51:12)
#22     _AsyncAwaitCompleter.complete.<anonymous closure> (dart:async-patch/async_patch.dart:33:20)
#23     _rootRun (dart:async/zone.dart:1124:13)
#24     _CustomZone.run (dart:async/zone.dart:1021:19)
#25     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:947:23)
#26     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#27     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#28     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:115:13)
#29     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:5)
```

**Comment by kangwang1988** [comment]
Duple of: https://github.com/flutter/flutter/issues/24600
