### ISSUE TITLE
Crash Report: AndroidDevice.uninstallApp failure

### ISSUE THREAD

**Issue by bgrgv** [flutter/flutter#32085]
Flutter crash report; please file at https://github.com/flutter/flutter/issues.

## command

flutter run

## exception

ProcessException: ProcessException: Process "C:\Users\blesi\AppData\Local\Android\sdk\platform-tools\adb.exe" exited abnormally:
error: device '192.168.1.104:5555' not found
- waiting for device -
error: protocol fault (couldn't read status): Connection reset by peer
  Command: C:\Users\blesi\AppData\Local\Android\sdk\platform-tools\adb.exe -s 192.168.1.104:5555 uninstall com.example.shotrate

```
#0      runCheckedAsync (package:flutter_tools/src/base/process.dart:255:5)
<asynchronous suspension>
#1      AndroidDevice.uninstallApp (package:flutter_tools/src/android/android_device.dart:308:40)
<asynchronous suspension>
#2      AndroidDevice._installLatestApp (package:flutter_tools/src/android/android_device.dart:332:20)
<asynchronous suspension>
#3      AndroidDevice.startApp (package:flutter_tools/src/android/android_device.dart:390:16)
<asynchronous suspension>
#4      FlutterDevice.runHot (package:flutter_tools/src/resident_runner.dart:364:54)
<asynchronous suspension>
#5      HotRunner.run (package:flutter_tools/src/run_hot.dart:253:39)
<asynchronous suspension>
#6      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:428:37)
<asynchronous suspension>
#7      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:559:18)
#8      _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:77:64)
#9      _rootRunUnary (dart:async/zone.dart:1132:38)
#10     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#11     _FutureListener.handleValue (dart:async/future_impl.dart:126:18)
#12     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:639:45)
#13     Future._propagateToListeners (dart:async/future_impl.dart:668:32)
#14     Future._complete (dart:async/future_impl.dart:473:7)
#15     _SyncCompleter.complete (dart:async/future_impl.dart:51:12)
#16     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:28:18)
#17     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:294:13)
#18     RunCommand.usageValues (package:flutter_tools/src/commands/run.dart)
#19     _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:77:64)
#20     _rootRunUnary (dart:async/zone.dart:1132:38)
#21     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#22     _FutureListener.handleValue (dart:async/future_impl.dart:126:18)
#23     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:639:45)
#24     Future._propagateToListeners (dart:async/future_impl.dart:668:32)
#25     Future._complete (dart:async/future_impl.dart:473:7)
#26     _SyncCompleter.complete (dart:async/future_impl.dart:51:12)
#27     _AsyncAwaitCompleter.complete.<anonymous closure> (dart:async-patch/async_patch.dart:33:20)
#28     _rootRun (dart:async/zone.dart:1124:13)
#29     _CustomZone.run (dart:async/zone.dart:1021:19)
#30     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:947:23)
#31     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#32     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#33     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:115:13)
#34     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:5)
```

## flutter doctor

```
[32m[✓][39m Flutter (Channel beta, v1.5.4-hotfix.2, on Microsoft Windows [Version 10.0.17134.706], locale en-US)
    [32m•[39m Flutter version 1.5.4-hotfix.2 at C:\flutter
    [32m•[39m Framework revision 7a4c33425d (5 days ago), 2019-04-29 11:05:24 -0700
    [32m•[39m Engine revision 52c7a1e849
    [32m•[39m Dart version 2.3.0 (build 2.3.0-dev.0.5 a1668566e5)

[32m[✓][39m Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    [32m•[39m Android SDK at C:\Users\blesi\AppData\Local\Android\sdk
    [32m•[39m Android NDK location not configured (optional; useful for native profiling support)
    [32m•[39m Platform android-28, build-tools 28.0.3
    [32m•[39m Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    [32m•[39m Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)
    [32m•[39m All Android licenses accepted.

[32m[✓][39m Android Studio (version 3.3)
    [32m•[39m Android Studio at C:\Program Files\Android\Android Studio
    [32m•[39m Flutter plugin version 33.4.1
    [32m•[39m Dart plugin version 182.5215
    [32m•[39m Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)

[32m[✓][39m VS Code (version 1.33.1)
    [32m•[39m VS Code at C:\Users\blesi\AppData\Local\Programs\Microsoft VS Code
    [32m•[39m Flutter extension version 2.26.1

[32m[✓][39m Connected device (1 available)
    [32m•[39m Zenfone Max Pro M1 • 192.168.1.104:5555 • android-arm64 • Android 9 (API 28)

[32m•[39m No issues found!
```

**Comment by BondarenkoStas** [comment]
@bgrgv did you manage to fix it?

**Comment by bgrgv** [comment]
Yes, I did a clean install and config of Flutter.
