### ISSUE TITLE
[Bug] Gradle app:validateSigningProdRelease fails - no error?

### ISSUE THREAD

**Issue by matanshukry** [flutter/flutter#32099]
## Steps to Reproduce

1. flutter clean
2. flutter build appbundle --release --flavor prod -v

## Logs

flutter build:
```
...
[        ] > Task :app:configureProdReleaseDependencies UP-TO-DATE
[        ] > Task :app:packageProdReleaseBundle UP-TO-DATE
[        ] > Task :app:validateSigningProdRelease FAILED
[        ]          *********************************************************
[        ] WARNING: This version of google_sign_in will break your Android build if it or its dependencies aren't compatible with AndroidX.
[        ]          See https://goo.gl/CP92wY for more information on the problem and how to fix it.
[        ]          This warning prints for all Android build failures. The real root cause of the error may be unrelated.
[        ]          *********************************************************
[        ] 110 actionable tasks: 4 executed, 106 up-to-date
[ +389 ms] Running Gradle task 'bundleProdRelease'... (completed in 3.3s)
[   +2 ms] "flutter appbundle" took 8,227ms.
[        ] "flutter appbundle" took 8,227ms.
Gradle task bundleProdRelease failed with exit code 1

#0      throwToolExit (package:flutter_tools/src/base/common.dart:24:3)
#1      _buildGradleProjectV2 (package:flutter_tools/src/android/gradle.dart:472:5)
<asynchronous suspension>
#2      buildGradleProject (package:flutter_tools/src/android/gradle.dart:342:14)
<asynchronous suspension>
#3      buildAppBundle (package:flutter_tools/src/android/app_bundle.dart:43:10)
<asynchronous suspension>
#4      BuildAppBundleCommand.runCommand (package:flutter_tools/src/commands/build_appbundle.dart:43:11)
<asynchronous suspension>
#5      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:488:18)
<asynchronous suspension>
#6      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:424:33)
<asynchronous suspension>
#7      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:29)
<asynchronous suspension>
#8      _rootRun (dart:async/zone.dart:1124:13)
#9      _CustomZone.run (dart:async/zone.dart:1021:19)
#10     _runZoned (dart:async/zone.dart:1516:10)
#11     runZoned (dart:async/zone.dart:1463:12)
#12     AppContext.run (package:flutter_tools/src/base/context.dart:152:18)
<asynchronous suspension>
#13     FlutterCommand.run (package:flutter_tools/src/runner/flutter_command.dart:415:20)
#14     CommandRunner.runCommand (package:args/command_runner.dart:196:27)
<asynchronous suspension>
#15     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:396:21)
<asynchronous suspension>
#16     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:29)
<asynchronous suspension>
#17     _rootRun (dart:async/zone.dart:1124:13)
#18     _CustomZone.run (dart:async/zone.dart:1021:19)
#19     _runZoned (dart:async/zone.dart:1516:10)
#20     runZoned (dart:async/zone.dart:1463:12)
#21     AppContext.run (package:flutter_tools/src/base/context.dart:152:18)
<asynchronous suspension>
#22     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:356:19)
<asynchronous suspension>
#23     CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:111:29)
#24     new Future.sync (dart:async/future.dart:224:31)
#25     CommandRunner.run (package:args/command_runner.dart:111:11)
#26     FlutterCommandRunner.run (package:flutter_tools/src/runner/flutter_command_runner.dart:242:18)
#27     run.<anonymous closure> (package:flutter_tools/runner.dart:60:20)
<asynchronous suspension>
#28     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:29)
<asynchronous suspension>
#29     _rootRun (dart:async/zone.dart:1124:13)
#30     _CustomZone.run (dart:async/zone.dart:1021:19)
#31     _runZoned (dart:async/zone.dart:1516:10)
#32     runZoned (dart:async/zone.dart:1463:12)
#33     AppContext.run (package:flutter_tools/src/base/context.dart:152:18)
<asynchronous suspension>
#34     runInContext (package:flutter_tools/src/context_runner.dart:50:24)
<asynchronous suspension>
#35     run (package:flutter_tools/runner.dart:51:10)
#36     main (package:flutter_tools/executable.dart:58:9)
<asynchronous suspension>
#37     main (file:///D:/dev/Flutter/packages/flutter_tools/bin/flutter_tools.dart:8:3)
#38     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:298:32)
```

I also ran the gradle task manually, from inside the android directory:
`./gradlew app:validateSigningProdRelease --debug | tee log`
Since the output is very big, I'm narrowing it to the place where it fails (although no reason):

Output:
```
21:37:52.130 [DEBUG] [org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter] Executing actions for task ':app:validateSigningProdRelease'.
21:37:52.130 [DEBUG] [org.gradle.internal.operations.DefaultBuildOperationExecutor] Build operation 'Execute validate for :app:validateSigningProdRelease' started
21:37:52.131 [DEBUG] [org.gradle.internal.operations.DefaultBuildOperationExecutor] Completing Build operation 'Execute validate for :app:validateSigningProdRelease'
21:37:52.131 [DEBUG] [org.gradle.internal.operations.DefaultBuildOperationExecutor] Build operation 'Execute validate for :app:validateSigningProdRelease' completed
21:37:52.131 [DEBUG] [org.gradle.api.internal.changedetection.state.CacheBackedTaskHistoryRepository] Implementation for task ':app:validateSigningProdRelease': com.android.build.gradle.internal.tasks.ValidateSigningTask_Decorated@48ebc7884b0d329c625acf12c11140ed
21:37:52.131 [DEBUG] [org.gradle.api.internal.changedetection.state.CacheBackedTaskHistoryRepository] Action implementations for task ':app:validateSigningProdRelease': [com.android.build.gradle.internal.tasks.ValidateSigningTask_Decorated@48ebc7884b0d329c625acf12c
11140ed]
21:37:52.131 [DEBUG] [org.gradle.api.internal.changedetection.changes.TaskFingerprintUtil] Fingerprinting property dummyOutputDirectory (Output) for task ':app:validateSigningProdRelease'
21:37:52.131 [DEBUG] [org.gradle.api.internal.changedetection.changes.TaskFingerprintUtil] Fingerprinting property dummyOutputDirectory (Output) for task ':app:validateSigningProdRelease'
21:37:52.131 [DEBUG] [org.gradle.internal.execution.impl.steps.CacheStep] Not storing result of task ':app:validateSigningProdRelease' in cache because the execution failed
21:37:52.131 [DEBUG] [org.gradle.api.internal.tasks.execution.ResolveTaskArtifactStateTaskExecuter] Removed task artifact state for {} from context.
21:37:52.131 [DEBUG] [org.gradle.internal.operations.DefaultBuildOperationExecutor] Completing Build operation 'Task :app:validateSigningProdRelease'
21:37:52.132 [DEBUG] [org.gradle.internal.operations.DefaultBuildOperationExecutor] Build operation 'Task :app:validateSigningProdRelease' completed
21:37:52.132 [INFO] [org.gradle.execution.plan.DefaultPlanExecutor] :app:validateSigningProdRelease (Thread[Execution worker for ':',5,main]) completed. Took 0.002 secs
21:37:52.132 [DEBUG] [org.gradle.internal.resources.AbstractTrackedResourceLock] Execution worker for ':': released lock on :
```

Flutter analyze:
```
$ flutter analyze
Analyzing strw-mobile...
No issues found! (ran in 2.8s)
```

Flutter doctor -v:
```
$ flutter doctor -v
[√] Flutter (Channel master, v1.5.9-pre.149, on Microsoft Windows [Version 10.0.17763.475], locale en-US)
    • Flutter version 1.5.9-pre.149 at D:\dev\Flutter
    • Framework revision 2f75005a16 (3 hours ago), 2019-05-04 09:14:49 -0700
    • Engine revision 1d062db4db
    • Dart version 2.3.0 (build 2.3.0-dev.0.5 dbe80f3397)

[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at D:/dev/Android/Sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = D:/dev/Android/Sdk
    • Java binary at: D:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
    • All Android licenses accepted.

[√] Android Studio (version 3.4)
    • Android Studio at D:\Program Files\Android\Android Studio
    • Flutter plugin version 35.2.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

[√] IntelliJ IDEA Community Edition (version 2019.1)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2018.1.2
    • Flutter plugin version 35.2.3
    • Dart plugin version 191.7019

[!] Connected device
    ! No devices available

! Doctor found issues in 1 category.
```

**Comment by matanshukry** [comment]
Found the issue: the key algorithm of my store was DSA and not RSA (jarsigner.exe complained it wasn't strong enough).

In order to find it, I had to try and build a signed release apk in android studio for the android project of my flutter project. I don't know why, but not the flutter command nor the gradle command I ran showed the error, while android studio showed them easily in a second.

**Comment by ezraaaa** [comment]
I'm facing this similar issue when I am building a release apk with `flutter build apk` and I get `Gradle task assembleRelease failed with exit code 1`. Is there any solution to this?

**Comment by matanshukry** [comment]
@ezraaaa try to do as said. Open your android project in android studio, and do a build. I don't know why, but it's the only place I could ever see the actual errors.

**Comment by ezraaaa** [comment]
@matanshukry omg silly me, I just found out my `storeFile` in `key.properties` file does not match my keystore's name and it works right after I renamed it.
