### ISSUE TITLE
Invalid locale 'mk_MK' for Macedonian language

### ISSUE THREAD

**Issue by jovanovski** [flutter/flutter#32090]
## Steps to Reproduce

1. Creating a custom locale 'mk_MK' for Macedonian (unsupported by default) by using [this](https://github.com/flutter/website/blob/master/examples/internationalization/add_language/lib/main.dart) official example. Ends up looking like [this](https://gist.github.com/jovanovski/42ee25930984f024d7ad33e7b33912f9)
2. Adding the delegate to `localizationsDelegates` like [this](https://gist.github.com/jovanovski/d1ef5e91e98a9c4e0a09abfe396c1219)

## Logs
```
E/flutter ( 8700): [ERROR:flutter/lib/ui/ui_dart_state.cc(148)] Unhandled Exception: Invalid argument(s): Invalid locale 'mk_MK'
E/flutter ( 8700): #0      Intl._throwLocaleError (package:intl/intl.dart:240:5)
E/flutter ( 8700): #1      Intl.verifiedLocale (package:intl/intl.dart:234:21)
E/flutter ( 8700): #2      new DateFormat (file:///Users/gjavonovski/lib/flutter/.pub-cache/hosted/pub.dartlang.org/intl-0.15.7/lib/src/intl/date_format.dart:246:20)
E/flutter ( 8700): #3      _MkMaterialLocalizationsDelegate.load (package:mojvozduh_flutter/localization/MkMaterialLocalizationDelegate.dart:23:30)
E/flutter ( 8700): <asynchronous suspension>
E/flutter ( 8700): #4      _loadAll (package:flutter/src/widgets/localizations.dart:57:49)
E/flutter ( 8700): #5      _LocalizationsState.load (package:flutter/src/widgets/localizations.dart:508:62)
E/flutter ( 8700): #6      _LocalizationsState.didUpdateWidget (package:flutter/src/widgets/localizations.dart:497:7)
E/flutter ( 8700): #7      StatefulElement.update (package:flutter/src/widgets/framework.dart:3879:58)
E/flutter ( 8700): #8      Element.updateChild (package:flutter/src/widgets/framework.dart:2748:15)
E/flutter ( 8700): #9      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3747:16)
E/flutter ( 8700): #10     Element.rebuild (package:flutter/src/widgets/framework.dart:3559:5)
E/flutter ( 8700): #11     ProxyElement.update (package:flutter/src/widgets/framework.dart:4006:5)
E/flutter ( 8700): #12     Element.updateChild (package:flutter/src/widgets/framework.dart:2748:15)
E/flutter ( 8700): #13     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3747:16)
E/flutter ( 8700): #14     Element.rebuild (package:flutter/src/widgets/framework.dart:3559:5)
E/flutter ( 8700): #15     StatefulElement.update (package:flutter/src/widgets/framework.dart:3894:5)
E/flutter ( 8700): #16     Element.updateChild (package:flutter/src/widgets/framework.dart:2748:15)
E/flutter ( 8700): #17     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3747:16)
E/flutter ( 8700): #18     Element.rebuild (package:flutter/src/widgets/framework.dart:3559:5)
E/flutter ( 8700): #19     ProxyElement.update (package:flutter/src/widgets/framework.dart:4006:5)
E/flutter ( 8700): #20     Element.updateChild (package:flutter/src/widgets/framework.dart:2748:15)
E/flutter ( 8700): #21     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3747:16)
E/flutter ( 8700): #22     Element.rebuild (package:flutter/src/widgets/framework.dart:3559:5)
E/flutter ( 8700): #23     StatefulElement.update (package:flutter/src/widgets/framework.dart:3894:5)
E/flutter ( 8700): #24     Element.updateChild (package:flutter/src/widgets/framework.dart:2748:15)
E/flutter ( 8700): #25     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3747:16)
E/flutter ( 8700): #26     Element.rebuild (package:flutter/src/widgets/framework.dart:3559:5)
E/flutter ( 8700): #27     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2273:33)
E/flutter ( 8700): #28     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding&WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:700:20)
E/flutter ( 8700): #29     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:268:5)
E/flutter ( 8700): #30     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:988:15)
E/flutter ( 8700): #31     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:928:9)
E/flutter ( 8700): #32     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:840:5)
E/flutter ( 8700): #33     _rootRun (dart:async/zone.dart:1124:13)
E/flutter ( 8700): #34     _CustomZone.run (dart:async/zone.dart:1021:19)
E/flutter ( 8700): #35     _CustomZone.runGuarded (dart:async/zone.dart:923:7)
E/flutter ( 8700): #36     _invoke (dart:ui/hooks.dart:209:10)
E/flutter ( 8700): #37     _drawFrame (dart:ui/hooks.dart:168:3)
```

Nothing connected in `flutter analyze` output

```
[✓] Flutter (Channel stable, v1.2.1, on Mac OS X 10.14.4 18E227, locale en-NL)
    • Flutter version 1.2.1 at /Users/gjavonovski/lib/flutter
    • Framework revision 8661d8aecd (3 months ago), 2019-02-14 19:19:53 -0800
    • Engine revision 3757390fa4
    • Dart version 2.1.2 (build 2.1.2-dev.0.0 0a7dcf17eb)

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/gjavonovski/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = /Users/gjavonovski/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
    • All Android licenses accepted.

[!] iOS toolchain - develop for iOS devices (Xcode 10.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.2.1, Build version 10E1001
    • ios-deploy 1.9.4
    • CocoaPods version 1.6.0

[✓] Android Studio (version 3.4)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 35.2.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

[✓] Connected device (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 9 (API 28) (emulator)

```

**Comment by HansMuller** [comment]
Thanks for the report; we'll look into it.

**Comment by Darknutrino** [comment]
I got the same issue, invalid locale ml_IN for Malayalam language. I also follow official example from flutter website as jovanovski said above and the logs are same.

**Comment by jovanovski** [comment]
I have a temporary, but unsustainable workaround:

```
  @override
  Future<MaterialLocalizations> load(Locale locale) async {
    final String localeName = intl.Intl.canonicalizedLocale(locale.toString());
//    await intl.initializeDateFormatting(localeName, null); // Make sure to comment this out if following the official guide otherwise you will encounter random failures with "Cannot write to unmodifiable Map" error
    return SynchronousFuture<MaterialLocalizations>(
      MkMaterialLocalizations(
        localeName: localeName,
        fullYearFormat: intl.DateFormat('y', "en_US"), // Changed here from "mk_MK" to "en_US" or any other supported locale
        mediumDateFormat: intl.DateFormat('EEE, MMM d', "en_US"), // Same here
        longDateFormat: intl.DateFormat('EEEE, MMMM d, y', "en_US"), // Same here
        yearMonthFormat: intl.DateFormat('MMMM y', "en_US"), // Same here
        decimalFormat: intl.NumberFormat('#,##0.###', "en_US"), // Same here
        twoDigitZeroPaddedFormat: intl.NumberFormat('00', "en_US"), // Same here
      ),
    );
  }
```

Not all libraries like this, so an official fix would be much better.

**Comment by Darknutrino** [comment]
Thank you @jovanovski. the temporary workaround is OK. Yeah like you said an official fix would be much better.

**Comment by HansMuller** [comment]
I've tried your app, albeit with a main that specified `supportedLocales`, and did not encounter any problems: https://gist.github.com/HansMuller/b357cbf7c04d4e7c24411ba1ec675973.

The app's pubspec.yaml includes a dependency on the Dart intl package (version 0.15.8) and the flutter_localizations package:

```
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: 0.15.8
```

I'm running on the current "tip of tree" version of Flutter.

**Comment by Darknutrino** [comment]
The problem occur when changing the language while running the application. otherwise no problem.

**Comment by Darknutrino** [comment]
could you check this one [app](https://akhilpaulnp@bitbucket.org/akhilpaulnp/app_localization.git) it shows error alternatively. first time shows error then select same language again no problem.

**Comment by HansMuller** [comment]
I wasn't able to see the app at https://bitbucket.org/akhilpaulnp/app_localization/src/master/. After a couple of refreshes and retries I still get:
> Having trouble showing that directory
> Normally, you'd see the directory here, but something didn't go right.

**Comment by Darknutrino** [comment]
please do => git clone https://bitbucket.org/akhilpaulnp/app_localization.git
and run the app and check the log. if you got any problem while clone the app please let me know. I will share it through any other medium.

**Comment by totalerex** [comment]
I got the same issue implementing custom locale. 
Workaround listed above works only in static (start application with any locale already selected), but doesn't work if app locale changed by user ("Cannot write to unmodifiable Map" error).

**Comment by jovanovski** [comment]
@totalerex Did you remove `await intl.initializeDateFormatting(localeName, null);` this line?

@HansMuller Do you think we'll have any updates on this soon?

**Comment by totalerex** [comment]
@jovanovski , yes i tried this way, 
but I also need date/number formatting for my locale already present in intl package, I need user option to change locale, so...
If we can fix/workaround "Cannot write to unmodifiable Map" exception it would be also OK, as for me.

I have created more generic bug - #33375 , there are some investigations and my current workaround described.

**Comment by jovanovski** [comment]
This is really causing some issues, now on locales such as `mk` I have to force `en_US` dates which look bad :(

**Comment by kinex** [comment]
Could this be related issue (different locale though):
```dart
Invalid argument(s): Invalid locale 'be_BY'
Intl._throwLocaleError (Intl.java:239)
Intl.verifiedLocale (Intl.java:233)
Intl.verifiedLocale (Intl.java:218)
DateTimeFormatter.init:_shortDateFormat (DateTimeFormatter.java:4)
DateTimeFormatter.get:_shortDateFormat (DateTimeFormatter.java:4)
DateTimeFormatter.toShortDateString (DateTimeFormatter.java:20)
```
 I found this from my Crashlytics errors (so it happens on end user's device).

Exception occurs in my code here:
```dart
class DateTimeFormatter {
  static final _shortDateFormat = DateFormat.yMd();
...

**Comment by jovanovski** [comment]
Yes it is! It's just an unsupported locale in Flutter. 
This is really giving my app a bad user experience, since dates are now in `en_US` while the whole app is in another locale.

@HansMuller Is anything planned for this? Can I somehow help in adding the `mk_MK` locale to Flutter?

**Comment by VladyslavBondarenko** [comment]
Hi @jovanovski,
mk_MK seems to be supported. Tried with current master `1.20.0-3.0.pre.142` - all strings are translated.

<details>
 <summary>code sample</summary>

```
import 'package:flutter/material.dart';
import 'package:flutter_localizations/flutter_localizations.dart';

void main() => runApp(MaterialApp(
  home: MyApp(),
  localizationsDelegates: [
    GlobalMaterialLocalizations.delegate,
  ],
  supportedLocales: [
    const Locale('en', 'US'),
    const Locale('mk', 'MK'),
  ],
  theme: ThemeData.light().copyWith(
    primaryColor: Colors.green,
  ),
));

class MyApp extends StatefulWidget {
  @override
  _MyAppState createState() => _MyAppState();
}

class _MyAppState extends State<MyApp> {

  @override
  Widget build(BuildContext context) {
    return SafeArea(
      child: Scaffold(
          body: Center(
              child: RaisedButton(
                child: Text("datepicker"),
                onPressed: () async {
                  await showDatePicker(
                    initialDatePickerMode: DatePickerMode.day,
                    context: context,
                    firstDate: DateTime.now().subtract(Duration(days: 36500)),
                    lastDate: DateTime.now().add(Duration(days: 36500)),
                    initialDate: DateTime.now(),
                    locale: Locale('mk', 'MK'),
                    builder: (BuildContext context, Widget child) {
                      return Theme(
                        data: Theme.of(context),
                        child: child,
                        isMaterialAppTheme: true,
                      );
                    },
                  );
                },
              )
          )
      ),
    );
  }
}
```

</details> 

Closing as fixed. Please comment here or file a new issue if I'm wrong
