### ISSUE TITLE
Exception caught by gesture (long press in TextField)

### ISSUE THREAD

**Issue by sgon00** [flutter/flutter#32117]
This exception doesn't harm anything to my app so far. I report this issue just because the flutter run console having this words `In either case, please report this assertion by filing a bug on GitHub`.

```
$ flutter doctor -v
[✓] Flutter (Channel dev, v1.4.12, on Mac OS X 10.13.6 17G4015, locale en-CN)
    • Flutter version 1.4.12
    • Framework revision 294d7ea0cf (4 weeks ago), 2019-04-08 12:37:43 -0700
    • Engine revision ff1bcdc009
    • Dart version 2.2.1 (build 2.2.1-dev.3.0 None)

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[!] iOS toolchain - develop for iOS devices (Xcode 9.4.1)
    ......
[!] Android Studio (version 3.1)
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)
    ......

[✓] VS Code (version 1.33.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 2.26.1

[✓] Connected device (1 available)
    • MI 8 SE • 192.168.44.201:5555 • android-arm64 • Android 8.1.0 (API 27)
```

Long Press a normal TextField:

```dart
     TextField(
        decoration: InputDecoration(
          hintText: 'hello', 
          hintStyle: TextStyle(color: _iconColor, fontSize: 15.0),
          border: InputBorder.none,
        ),
        minLines: 1,
        maxLines: 5,
      )
```

flutter run console report this:

```
I/flutter (22904): ══╡ EXCEPTION CAUGHT BY GESTURE ╞═══════════════════════════════════════════════════════════════════
I/flutter (22904): The following assertion was thrown while handling a gesture:
I/flutter (22904): 'package:flutter/src/widgets/text_selection.dart': Failed assertion: line 335 pos 12: '_toolbar ==
I/flutter (22904): null': is not true.
I/flutter (22904): 
I/flutter (22904): Either the assertion indicates an error in the framework itself, or we should provide substantially
I/flutter (22904): more information in this error message to help you determine and fix the underlying cause.
I/flutter (22904): In either case, please report this assertion by filing a bug on GitHub:
I/flutter (22904):   https://github.com/flutter/flutter/issues/new?template=BUG.md
I/flutter (22904): 
I/flutter (22904): When the exception was thrown, this was the stack:
I/flutter (22904): #2      TextSelectionOverlay.showToolbar (package:flutter/src/widgets/text_selection.dart:335:12)
I/flutter (22904): #3      EditableTextState.showToolbar (package:flutter/src/widgets/editable_text.dart:1362:23)
I/flutter (22904): #4      _TextFieldState._handleSingleLongTapEnd (package:flutter/src/material/text_field.dart:736:35)
I/flutter (22904): #5      _TextSelectionGestureDetectorState._handleLongPressEnd (package:flutter/src/widgets/text_selection.dart:897:14)
I/flutter (22904): #6      LongPressGestureRecognizer.handlePrimaryPointer.<anonymous closure> (package:flutter/src/gestures/long_press.dart:198:13)
I/flutter (22904): #7      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:166:24)
I/flutter (22904): #8      LongPressGestureRecognizer.handlePrimaryPointer (package:flutter/src/gestures/long_press.dart:197:11)
I/flutter (22904): #9      PrimaryPointerGestureRecognizer.handleEvent (package:flutter/src/gestures/recognizer.dart:436:9)
I/flutter (22904): #10     PointerRouter._dispatch (package:flutter/src/gestures/pointer_router.dart:73:12)
I/flutter (22904): #11     PointerRouter.route (package:flutter/src/gestures/pointer_router.dart:101:11)
I/flutter (22904): #12     _WidgetsFlutterBinding&BindingBase&GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:221:19)
I/flutter (22904): #13     _WidgetsFlutterBinding&BindingBase&GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:199:22)
I/flutter (22904): #14     _WidgetsFlutterBinding&BindingBase&GestureBinding._handlePointerEvent (package:flutter/src/gestures/binding.dart:156:7)
I/flutter (22904): #15     _WidgetsFlutterBinding&BindingBase&GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:102:7)
I/flutter (22904): #16     _WidgetsFlutterBinding&BindingBase&GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:86:7)
I/flutter (22904): #20     _invoke1 (dart:ui/hooks.dart:233:10)
I/flutter (22904): #21     _dispatchPointerDataPacket (dart:ui/hooks.dart:154:5)
I/flutter (22904): (elided 5 frames from class _AssertionError and package dart:async)
I/flutter (22904): 
I/flutter (22904): Handler: onLongPressEnd
I/flutter (22904): Recognizer:
I/flutter (22904):   LongPressGestureRecognizer#592c3(debugOwner: _TextSelectionGestureDetectorState#ada05, state:
I/flutter (22904):   possible)
I/flutter (22904): ════════════════════════════════════════════════════════════════════════════════════════════════════
```

**Comment by TahaTesser** [comment]
Hi @sgon00 
Testing your code on `Flutter 1.12.13+hotfix.8` and it doesn't throw an exception. 
If you're still experiencing this issue, please create a new issue and provide the information required in the template.
Thank you
