### ISSUE TITLE
java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Class java.lang.ClassLoader.loadClass(java.lang.String)' on a null object reference

### ISSUE THREAD

**Issue by junkojunko** [flutter/flutter#32111]
hi，how can i solved this issue，i m using vscode and added foreign mirror
。i used flutter doctor in powershell that is ok

**Comment by junkojunko** [comment]
Flutter crash report; please file at https://github.com/flutter/flutter/issues.

## command

flutter run

## exception

ProcessException: ProcessException: Process "D:\androidsdk\platform-tools\adb" exited abnormally:
Starting: Intent { act=android.intent.action.RUN flg=0x20000000 cmp=com.example.upload/.MainActivity (has extras) }


Exception occurred while executing:
java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Class java.lang.ClassLoader.loadClass(java.lang.String)' on a null object reference
	at android.app.LoadedApk.createAppFactory(LoadedApk.java:224)
	at android.app.LoadedApk.<init>(LoadedApk.java:152)
	at android.app.ActivityThread.getPackageInfo(ActivityThread.java:2043)
	at android.app.ActivityThread.getPackageInfo(ActivityThread.java:1998)
	at android.app.ActivityThread.getPackageInfo(ActivityThread.java:1970)
	at android.app.ContextImpl.createPackageContextAsUser(ContextImpl.java:2054)
	at com.android.server.AttributeCache.get(AttributeCache.java:135)
	at com.android.server.am.ActivityRecord.<init>(ActivityRecord.java:903)
	at com.android.server.am.ActivityStarter.startActivity(ActivityStarter.java:804)
	at com.android.server.am.ActivityStarter.startActivity(ActivityStarter.java:528)
	at com.android.server.am.ActivityStarter.startActivityMayWait(ActivityStarter.java:1057)
	at com.android.server.am.ActivityStarter.execute(ActivityStarter.java:473)
	at com.android.server.am.ActivityManagerService.startActivityAsUser(ActivityManagerService.java:4841)
	at com.android.server.am.ActivityManagerShellCommand.runStartActivity(ActivityManagerShellCommand.java:458)
	at com.android.server.am.ActivityManagerShellCommand.onCommand(ActivityManagerShellCommand.java:139)
	at android.os.ShellCommand.exec(ShellCommand.java:103)
	at com.android.server.am.ActivityManagerService.onShellCommand(ActivityManagerService.java:15478)
	at android.os.Binder.shellCommand(Binder.java:631)
	at android.os.Binder.onTransact(Binder.java:529)
	at android.app.IActivityManager$Stub.onTransact(IActivityManager.java:4397)
	at com.android.server.am.ActivityManagerService.onTransact(ActivityManagerService.java:3114)
	at android.os.Binder.execTransact(Binder.java:726)
  Command: D:\androidsdk\platform-tools\adb -s emulator-5554 shell am start -a android.intent.action.RUN -f 0x20000000 --ez enable-background-compilation true --ez enable-dart-profiling true --ez enable-checked-mode true --ez verify-entry-points true com.example.upload/com.example.upload.MainActivity

```
#0      runCheckedAsync (package:flutter_tools/src/base/process.dart:250:5)
<asynchronous suspension>
#1      AndroidDevice.startApp (package:flutter_tools/src/android/android_device.dart:444:34)
<asynchronous suspension>
#2      FlutterDevice.runHot (package:flutter_tools/src/resident_runner.dart:308:54)
<asynchronous suspension>
#3      HotRunner.run (package:flutter_tools/src/run_hot.dart:295:39)
<asynchronous suspension>
#4      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:405:37)
<asynchronous suspension>
#5      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:545:18)
#6      _asyncThenWrapperHelper.<anonymous closure> (dart:async/runtime/libasync_patch.dart:77:64)
#7      _rootRunUnary (dart:async/zone.dart:1132:38)
#8      _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#9      _FutureListener.handleValue (dart:async/future_impl.dart:126:18)
#10     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:639:45)
#11     Future._propagateToListeners (dart:async/future_impl.dart:668:32)
#12     Future._complete (dart:async/future_impl.dart:473:7)
#13     _SyncCompleter.complete (dart:async/future_impl.dart:51:12)
#14     _AsyncAwaitCompleter.complete (dart:async/runtime/libasync_patch.dart:28:18)
#15     _completeOnAsyncReturn (dart:async/runtime/libasync_patch.dart:294:13)
#16     RunCommand.usageValues (package:flutter_tools/src/commands/run.dart)
#17     _asyncThenWrapperHelper.<anonymous closure> (dart:async/runtime/libasync_patch.dart:77:64)
#18     _rootRunUnary (dart:async/zone.dart:1132:38)
#19     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#20     _FutureListener.handleValue (dart:async/future_impl.dart:126:18)
#21     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:639:45)
#22     Future._propagateToListeners (dart:async/future_impl.dart:668:32)
#23     Future._complete (dart:async/future_impl.dart:473:7)
#24     _SyncCompleter.complete (dart:async/future_impl.dart:51:12)
#25     _AsyncAwaitCompleter.complete (dart:async/runtime/libasync_patch.dart:28:18)
#26     _completeOnAsyncReturn (dart:async/runtime/libasync_patch.dart:294:13)
#27     AndroidDevice.targetPlatform (package:flutter_tools/src/android/android_device.dart)
#28     _asyncThenWrapperHelper.<anonymous closure> (dart:async/runtime/libasync_patch.dart:77:64)
#29     _rootRunUnary (dart:async/zone.dart:1132:38)
#30     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#31     _FutureListener.handleValue (dart:async/future_impl.dart:126:18)
#32     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:639:45)
#33     Future._propagateToListeners (dart:async/future_impl.dart:668:32)
#34     Future._complete (dart:async/future_impl.dart:473:7)
#35     _SyncCompleter.complete (dart:async/future_impl.dart:51:12)
#36     _AsyncAwaitCompleter.complete.<anonymous closure> (dart:async/runtime/libasync_patch.dart:33:20)
#37     _rootRun (dart:async/zone.dart:1124:13)
#38     _CustomZone.run (dart:async/zone.dart:1021:19)
#39     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:947:23)
#40     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#41     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#42     _runPendingImmediateCallback (dart:isolate/runtime/libisolate_patch.dart:115:13)
#43     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:172:5)
```

## flutter doctor

```
[32m[✓][39m Flutter (Channel stable, v1.2.1, on Microsoft Windows [Version 10.0.17134.706], locale zh-CN)
    [32m•[39m Flutter version 1.2.1 at D:\Flutter\flutter
    [32m•[39m Framework revision 8661d8aecd (3 months ago), 2019-02-14 19:19:53 -0800
    [32m•[39m Engine revision 3757390fa4
    [32m•[39m Dart version 2.1.2 (build 2.1.2-dev.0.0 0a7dcf17eb)

[32m[✓][39m Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    [32m•[39m Android SDK at D:\androidsdk
    [32m•[39m Android NDK location not configured (optional; useful for native profiling support)
    [32m•[39m Platform android-28, build-tools 28.0.3
    [32m•[39m ANDROID_HOME = D:\androidsdk
    [32m•[39m Java binary at: D:\android studio\jre\bin\java
    [32m•[39m Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
    [32m•[39m All Android licenses accepted.

[32m[✓][39m Android Studio (version 3.4)
    [32m•[39m Android Studio at D:\android studio
    [32m•[39m Flutter plugin version 35.2.1
    [32m•[39m Dart plugin version 183.6270
    [32m•[39m Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

[32m[✓][39m Connected device (1 available)
    [32m•[39m Android SDK built for x86 • emulator-5554 • android-x86 • Android P (API 27) (emulator)

[32m•[39m No issues found!
```

**Comment by BondarenkoStas** [comment]
@junkojunko did you manage to solve it?

**Comment by iapicca** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
  
Thanks for your contribution.

**Comment by pranjal-joshi** [comment]
I am facing the same issue.
What is the solution to resolve this?

Here's an error dump:

```
ProcessException: Process exited abnormally:
Starting: Intent { act=android.intent.action.RUN flg=0x20000000 cmp=com.example.radiance_flutter/.MainActivity (has extras) }


Exception occurred while executing:
java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Class java.lang.ClassLoader.loadClass(java.lang.String)' on a null object reference
	at android.app.LoadedApk.createAppFactory(LoadedApk.java:224)
	at android.app.LoadedApk.<init>(LoadedApk.java:152)
	at android.app.ActivityThread.getPackageInfo(ActivityThread.java:2043)
	at android.app.ActivityThread.getPackageInfo(ActivityThread.java:1998)
	at android.app.ActivityThread.getPackageInfo(ActivityThread.java:1970)
	at android.app.ContextImpl.createPackageContextAsUser(ContextImpl.java:2054)
	at com.android.server.AttributeCache.get(AttributeCache.java:135)
	at com.android.server.am.ActivityRecord.<init>(ActivityRecord.java:903)
	at com.android.server.am.ActivityStarter.startActivity(ActivityStarter.java:804)
	at com.android.server.am.ActivityStarter.startActivity(ActivityStarter.java:528)
	at com.android.server.am.ActivityStarter.startActivityMayWait(ActivityStarter.java:1057)
	at com.android.server.am.ActivityStarter.execute(ActivityStarter.java:473)
	at com.android.server.am.ActivityManagerService.startActivityAsUser(ActivityManagerService.java:4841)
	at com.android.server.am.ActivityManagerShellCommand.runStartActivity(ActivityManagerShellCommand.java:458)
	at com.android.server.am.ActivityManagerShellCommand.onCommand(ActivityManagerShellCommand.java:139)
	at android.os.ShellCommand.exec(ShellCommand.java:103)
	at com.android.server.am.ActivityManagerService.onShellCommand(ActivityManagerService.java:15478)
	at android.os.Binder.shellCommand(Binder.java:631)
	at android.os.Binder.onTransact(Binder.java:529)
	at android.app.IActivityManager$Stub.onTransact(IActivityManager.java:4397)
	at com.android.server.am.ActivityManagerService.onTransact(ActivityManagerService.java:3114)
	at android.os.Binder.execTransact(Binder.java:726)
```

**Comment by namchuai** [comment]
This issue happen when I tried to run flutter on android emulator on mac os. It did not happen when I run on windows.

**Comment by iapicca** [comment]
Could everyone who still has this problem please file a new issue with the exact descriptions what happens, logs and the output of 'flutter doctor -v'  please.
All system setups can be slightly different so it's always better to open new issues and reference related issues.

**Comment by ch-muhammad-adil** [comment]
faced exactly same issue in android and answer is here, 

https://stackoverflow.com/questions/50900658/attempt-to-invoke-virtual-method-java-lang-class-java-lang-classloader-loadclas

it is API P issue in android.

**Comment by fvasquezjatar** [comment]
> Could everyone who still has this problem please file a new issue with the exact descriptions what happens, logs and the output of 'flutter doctor -v' please.
> All system setups can be slightly different so it's always better to open new issues and reference related issues.

Facing the same issue here:

`Launching lib/main.dart on Android SDK built for x86 in debug mode...
Running Gradle task 'assembleDebug'...
✓ Built build/app/outputs/apk/debug/app-debug.apk.
Finished with error: ProcessException: Process exited abnormally:
Starting: Intent { act=android.intent.action.RUN flg=0x20000000 cmp=com.example.app/.MainActivity (has extras) }


Exception occurred while executing:
java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Class java.lang.ClassLoader.loadClass(java.lang.String)' on a null object reference
	at android.app.LoadedApk.createAppFactory(LoadedApk.java:224)
	at android.app.LoadedApk.<init>(LoadedApk.java:152)
	at android.app.ActivityThread.getPackageInfo(ActivityThread.java:2043)
	at android.app.ActivityThread.getPackageInfo(ActivityThread.java:1998)
	at android.app.ActivityThread.getPackageInfo(ActivityThread.java:1970)
	at android.app.ContextImpl.createPackageContextAsUser(ContextImpl.java:2054)
	at com.android.server.AttributeCache.get(AttributeCache.java:135)
	at com.android.server.am.ActivityRecord.<init>(ActivityRecord.java:903)
	at com.android.server.am.ActivityStarter.startActivity(ActivityStarter.java:804)
	at com.android.server.am.ActivityStarter.startActivity(ActivityStarter.java:528)
	at com.android.server.am.ActivityStarter.startActivityMayWait(ActivityStarter.java:1057)
	at com.android.server.am.ActivityStarter.execute(ActivityStarter.java:473)
	at com.android.server.am.ActivityManagerService.startActivityAsUser(ActivityManagerService.java:4841)
	at com.android.server.am.ActivityManagerShellCommand.runStartActivity(ActivityManagerShellCommand.java:458)
	at com.android.server.am.ActivityManagerShellCommand.onCommand(ActivityManagerShellCommand.java:139)
	at android.os.ShellCommand.exec(ShellCommand.java:103)
	at com.android.server.am.ActivityManagerService.onShellCommand(ActivityManagerService.java:15478)
	at android.os.Binder.shellCommand(Binder.java:631)
	at android.os.Binder.onTransact(Binder.java:529)
	at android.app.IActivityManager$Stub.onTransact(IActivityManager.java:4397)
	at com.android.server.am.ActivityManagerService.onTransact(ActivityManagerService.java:3114)
	at android.os.Binder.execTransact(Binder.java:726)
  Command: /Users/cartman/Library/Android/sdk/platform-tools/adb -s emulator-5554 shell am start -a android.intent.action.RUN -f 0x20000000 --ez enable-background-compilation true --ez enable-dart-profiling true --ez enable-checked-mode true --ez verify-entry-points true --ez start-paused true com.example.app/com.example.app.MainActivity`

**flutter doctor -v**

`flutter doctor -v
[✓] Flutter (Channel stable, v1.12.13+hotfix.8, on Mac OS X 10.15.4 19E266, locale en-US)
    • Flutter version 1.12.13+hotfix.8 at /Users/cartman/flutter
    • Framework revision 0b8abb4724 (7 weeks ago), 2020-02-11 11:44:36 -0800
    • Engine revision e1e6ced81d
    • Dart version 2.7.0

 
[!] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/cartman/Library/Android/sdk
    • Android NDK at /Users/cartman/Library/Android/sdk/ndk-bundle
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio 3.6.1.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses

[!] Xcode - develop for iOS and macOS (Xcode 11.4)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.4, Build version 11E146
    ✗ CocoaPods installed but not working.
        You appear to have CocoaPods installed but it is not working.
        This can happen if the version of Ruby that CocoaPods was installed with is different from the one being used to invoke it.
        This can usually be fixed by re-installing CocoaPods. For more info, see https://github.com/flutter/flutter/issues/14293.
      To re-install CocoaPods, run:
        sudo gem install cocoapods

[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio 3.6.1.app/Contents
    • Flutter plugin version 44.0.2
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)

[!] Android Studio (version 3.4)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

[✓] IntelliJ IDEA Ultimate Edition (version 2019.3.4)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 44.0.3
    • Dart plugin version 193.6911.31

[✓] VS Code (version 1.43.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.8.1

[✓] Connected device (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android P (API 27) (emulator)

! Doctor found issues in 3 categories.
`
