### ISSUE TITLE
"Unhandled Exception: NoSuchMethodError: The method 'call' was called on null."  when run async proccessing

### ISSUE THREAD

**Issue by karmactonics** [flutter/flutter#32179]
## Steps to Reproduce
The following error occurs every time I do async processing using Future class.
However, the app does not stop working.

## Logs

```
Unhandled Exception: NoSuchMethodError: The method 'call' was called on null.
Receiver: null
Tried calling: call()
#0      new Future.<anonymous closure> (dart:async/future.dart)
#1      _rootRun (dart:async/zone.dart:1120:38)
#2      _CustomZone.run (dart:async/zone.dart:1021:19)
#3      _CustomZone.runGuarded (dart:async/zone.dart:923:7)
#4      _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:963:23)
#5      _rootRun (dart:async/zone.dart:1124:13)
#6      _CustomZone.run (dart:async/zone.dart:1021:19)
#7      _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:947:23)
#8      Timer._createTimer.<anonymous closure> (dart:async-patch/timer_patch.dart:21:15)
#9      _Timer._runTimers (dart:isolate-patch/timer_impl.dart:382:19)
#10     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:416:5)
#11     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:171:12)
```

## flutter doctor

```
[✓] Flutter (Channel master, v1.5.6-pre.186, on Mac OS X 10.14.3 18D109, locale ja-JP)
    • Flutter version 1.5.6-pre.186 at /Users/Karma_mac/Documents/workspace/flutter
    • Framework revision f61a2c3907 (4 hours ago), 2019-05-06 14:36:30 -0700
    • Engine revision ee6412a74d
    • Dart version 2.3.0 (build 2.3.0-dev.0.5 dbe80f3397)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/Karma_mac/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.2, Build version 10E125
    • ios-deploy 1.9.4
    • CocoaPods version 1.6.0.beta.2

[✓] Android Studio (version 3.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 32.0.1
    • Dart plugin version 182.5124
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)

[✓] VS Code (version 1.33.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 2.26.1

[✓] Connected device (1 available)
    • iPhone X • **** • ios • iOS 12.1.2
```

**Comment by karmactonics** [comment]
solved. it depends local processing, sorry about that.

**Comment by JJLewis** [comment]
I'm getting the same error, what did you change to fix it?

**Comment by karmactonics** [comment]
@JJLewis 
The reason was that when calling FlutterMethodChannel.invokeMethod in each native processing (for example, Swift code side for iOS), a non-existent method name was specified.
I hope to be helpful.
