### ISSUE TITLE
flutter crashed

### ISSUE THREAD

**Issue by zcweng** [flutter/flutter#32277]
## Steps to Reproduce
1. release build & run
2. 
3. ...

## Logs
```
05-08 10:47:59.596 10156 8300 8300 E InputEventReceiver: Exception dispatching input event.
05-08 10:47:59.596 10156 8300 8300 E MessageQueue-JNI: Exception in MessageQueue callback: handleReceiveCallback
05-08 10:47:59.597 10156 8300 8300 E MessageQueue-JNI: java.lang.NullPointerException: Attempt to invoke virtual method 'float android.view.InputDevice$MotionRange.getMin()' on a null object reference
05-08 10:47:59.597 10156 8300 8300 E MessageQueue-JNI: at io.flutter.view.FlutterView.addPointerForIndex(FlutterView.java:480)
05-08 10:47:59.597 10156 8300 8300 E MessageQueue-JNI: at io.flutter.view.FlutterView.onTouchEvent(FlutterView.java:542)
05-08 10:47:59.597 10156 8300 8300 E MessageQueue-JNI: at android.view.View.dispatchTouchEvent(View.java:12533)
05-08 10:47:59.597 10156 8300 8300 E MessageQueue-JNI: at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3032)
05-08 10:47:59.597 10156 8300 8300 E MessageQueue-JNI: at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2662)
05-08 10:47:59.597 10156 8300 8300 E MessageQueue-JNI: at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3032)
05-08 10:47:59.597 10156 8300 8300 E MessageQueue-JNI: at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2662)
05-08 10:47:59.597 10156 8300 8300 E MessageQueue-JNI: at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3032)
05-08 10:47:59.597 10156 8300 8300 E MessageQueue-JNI: at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2662)
05-08 10:47:59.597 10156 8300 8300 E MessageQueue-JNI: at com.android.internal.policy.DecorView.superDispatchTouchEvent(DecorView.java:461)
05-08 10:47:59.597 10156 8300 8300 E MessageQueue-JNI: at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1830)
05-08 10:47:59.597 10156 8300 8300 E MessageQueue-JNI: at android.app.Activity.dispatchTouchEvent(Activity.java:3453)
05-08 10:47:59.597 10156 8300 8300 E MessageQueue-JNI: at com.android.internal.policy.DecorView.dispatchTouchEvent(DecorView.java:419)
05-08 10:47:59.597 10156 8300 8300 E MessageQueue-JNI: at android.view.View.dispatchPointerEvent(View.java:12774)
05-08 10:47:59.597 10156 8300 8300 E MessageQueue-JNI: at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:5263)
05-08 10:47:59.597 10156 8300 8300 E MessageQueue-JNI: at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:5063)
05-08 10:47:59.597 10156 8300 8300 E MessageQueue-JNI: at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4578)
05-08 10:47:59.597 10156 8300 8300 E MessageQueue-JNI: at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4631)
05-08 10:47:59.597 10156 8300 8300 E MessageQueue-JNI: at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4597)
05-08 10:47:59.597 10156 8300 8300 E MessageQueue-JNI: at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:4737)
05-08 10:47:59.597 10156 8300 8300 E MessageQueue-JNI: at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4605)
05-08 10:47:59.597 10156 8300 8300 E MessageQueue-JNI: at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:4794)
05-08 10:47:59.597 10156 8300 8300 E MessageQueue-JNI: at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4578)
05-08 10:47:59.597 10156 8300 8300 E MessageQueue-JNI: at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4631)
05-08 10:47:59.597 10156 8300 8300 E MessageQueue-JNI: at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4597)
05-08 10:47:59.597 10156 8300 8300 E MessageQueue-JNI: at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4605)
05-08 10:47:59.597 10156 8300 8300 E MessageQueue-JNI: at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4578)
05-08 10:47:59.597 10156 8300 8300 E MessageQueue-JNI: at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:7304)
05-08 10:47:59.597 10156 8300 8300 E MessageQueue-JNI: at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:7273)
05-08 10:47:59.597 10156 8300 8300 E MessageQueue-JNI: at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:7234)
05-08 10:47:59.597 10156 8300 8300 E MessageQueue-JNI: at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:7410)
05-08 10:47:59.597 10156 8300 8300 E MessageQueue-JNI: at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:247)
05-08 10:47:59.597 10156 8300 8300 E MessageQueue-JNI: at android.os.MessageQueue.nativePollOnce(Native Method)
05-08 10:47:59.597 10156 8300 8300 E MessageQueue-JNI: at android.os.MessageQueue.next(MessageQueue.java:326)
05-08 10:47:59.597 10156 8300 8300 E MessageQueue-JNI: at android.os.Looper.loop(Looper.java:165)
05-08 10:47:59.597 10156 8300 8300 E MessageQueue-JNI: at android.app.ActivityThread.main(ActivityThread.java:6806)
05-08 10:47:59.597 10156 8300 8300 E MessageQueue-JNI: at java.lang.reflect.Method.invoke(Native Method)
05-08 10:47:59.597 10156 8300 8300 E MessageQueue-JNI: at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
05-08 10:47:59.597 10156 8300 8300 E MessageQueue-JNI: at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:873)
05-08 10:47:59.597 10156 8300 8300 D AndroidRuntime: Shutting down VM
FATAL
EXCEPTION
05-08 10:47:59.597 10156 8300 8300 E AndroidRuntime: FATAL EXCEPTION: main
05-08 10:47:59.597 10156 8300 8300 E AndroidRuntime: Process: com.izhaowo.user, PID: 8300
05-08 10:47:59.597 10156 8300 8300 E AndroidRuntime: java.lang.NullPointerException: Attempt to invoke virtual method 'float android.view.InputDevice$MotionRange.getMin()' on a null object reference
05-08 10:47:59.597 10156 8300 8300 E AndroidRuntime: at io.flutter.view.FlutterView.addPointerForIndex(FlutterView.java:480)
05-08 10:47:59.597 10156 8300 8300 E AndroidRuntime: at io.flutter.view.FlutterView.onTouchEvent(FlutterView.java:542)
05-08 10:47:59.597 10156 8300 8300 E AndroidRuntime: at android.view.View.dispatchTouchEvent(View.java:12533)
05-08 10:47:59.597 10156 8300 8300 E AndroidRuntime: at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3032)
05-08 10:47:59.597 10156 8300 8300 E AndroidRuntime: at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2662)
05-08 10:47:59.597 10156 8300 8300 E AndroidRuntime: at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3032)
05-08 10:47:59.597 10156 8300 8300 E AndroidRuntime: at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2662)
05-08 10:47:59.597 10156 8300 8300 E AndroidRuntime: at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3032)
05-08 10:47:59.597 10156 8300 8300 E AndroidRuntime: at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2662)
05-08 10:47:59.597 10156 8300 8300 E AndroidRuntime: at com.android.internal.policy.DecorView.superDispatchTouchEvent(DecorView.java:461)
05-08 10:47:59.597 10156 8300 8300 E AndroidRuntime: at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1830)
05-08 10:47:59.597 10156 8300 8300 E AndroidRuntime: at android.app.Activity.dispatchTouchEvent(Activity.java:3453)
05-08 10:47:59.597 10156 8300 8300 E AndroidRuntime: at com.android.internal.policy.DecorView.dispatchTouchEvent(DecorView.java:419)
05-08 10:47:59.597 10156 8300 8300 E AndroidRuntime: at android.view.View.dispatchPointerEvent(View.java:12774)
05-08 10:47:59.597 10156 8300 8300 E AndroidRuntime: at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:5263)
05-08 10:47:59.597 10156 8300 8300 E AndroidRuntime: at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:5063)
05-08 10:47:59.597 10156 8300 8300 E AndroidRuntime: at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4578)
05-08 10:47:59.597 10156 8300 8300 E AndroidRuntime: at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4631)
05-08 10:47:59.597 10156 8300 8300 E AndroidRuntime: at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4597)
05-08 10:47:59.597 10156 8300 8300 E AndroidRuntime: at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:4737)
05-08 10:47:59.597 10156 8300 8300 E AndroidRuntime: at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4605)
05-08 10:47:59.597 10156 8300 8300 E AndroidRuntime: at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:4794)
05-08 10:47:59.597 10156 8300 8300 E AndroidRuntime: at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4578)
05-08 10:47:59.597 10156 8300 8300 E AndroidRuntime: at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4631)
05-08 10:47:59.597 10156 8300 8300 E AndroidRuntime: at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4597)
05-08 10:47:59.597 10156 8300 8300 E AndroidRuntime: at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4605)
05-08 10:47:59.597 10156 8300 8300 E AndroidRuntime: at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4578)
05-08 10:47:59.597 10156 8300 8300 E AndroidRuntime: at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:7304)
05-08 10:47:59.597 10156 8300 8300 E AndroidRuntime: at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:7273)
05-08 10:47:59.597 10156 8300 8300 E AndroidRuntime: at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:7234)
05-08 10:47:59.597 10156 8300 8300 E AndroidRuntime: at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:7410)
05-08 10:47:59.597 10156 8300 8300 E AndroidRuntime: at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:247)
05-08 10:47:59.597 10156 8300 8300 E AndroidRuntime: at android.os.MessageQueue.nativePollOnce(Native Method)
05-08 10:47:59.597 10156 8300 8300 E AndroidRuntime: at android.os.MessageQueue.next(MessageQueue.java:326)
05-08 10:47:59.597 10156 8300 8300 E AndroidRuntime: at android.os.Looper.loop(Looper.java:165)
05-08 10:47:59.597 10156 8300 8300 E AndroidRuntime: at android.app.ActivityThread.main(ActivityThread.java:6806)
05-08 10:47:59.597 10156 8300 8300 E AndroidRuntime: at java.lang.reflect.Method.invoke(Native Method)
05-08 10:47:59.597 10156 8300 8300 E AndroidRuntime: at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
05-08 10:47:59.597 10156 8300 8300 E AndroidRuntime: at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:873)
```

```
```

```
```

**Comment by zcweng** [comment]
![image](https://user-images.githubusercontent.com/6629581/57360486-deee8d00-71ac-11e9-8fbc-37d253546a31.png)

**Comment by zcweng** [comment]
> I had this problem too, it just seems to happen on the stable channel
> 
> #28490

i pull last stable channel(1.5.4-hotfix.2) and crash fixed.
