### ISSUE TITLE
flutter upgrade to 1.5 fails

### ISSUE THREAD

**Issue by kinex** [flutter/flutter#32288]
```
PS D:\work\flutter\myapp> flutter upgrade
Upgrading Flutter from C:\tools\fluttersdk\flutter...
From https://github.com/flutter/flutter
   8661d8aec..7a4c33425  stable                  -> origin/stable
 + d8b4a72b4...a314da37b Hixie-patch-1           -> origin/Hixie-patch-1  (forced update)
 * [new branch]          Hixie-patch-2           -> origin/Hixie-patch-2
   8661d8aec..7a4c33425  beta                    -> origin/beta
   007a415c2..0ba67226e  dev                     -> origin/dev
 * [new branch]          kevmoo.web_template     -> origin/kevmoo.web_template
   e50ebfc6f..13985db2d  master                  -> origin/master
 * [new branch]          revert-28919-composite_elevations -> origin/revert-28919-composite_elevations
 * [new branch]          revert-29010-re_enable_dart2js -> origin/revert-29010-re_enable_dart2js
 * [new branch]          revert-29323-roll_branch -> origin/revert-29323-roll_branch
 * [new branch]          revert-30339-tap-buttons -> origin/revert-30339-tap-buttons
 * [new branch]          revert-30919-initial_auth_codes -> origin/revert-30919-initial_auth_codes
 * [new branch]          revert-30951-roll_branch -> origin/revert-30951-roll_branch
 * [new branch]          revert-30991-caretheight -> origin/revert-30991-caretheight
 * [new branch]          revert-30995-revert_engine -> origin/revert-30995-revert_engine
 * [new branch]          revert-31736-roll_build -> origin/revert-31736-roll_build
 * [new branch]          revert-31801-revert-30339-tap-buttons -> origin/revert-31801-revert-30339-tap-buttons
 * [new branch]          v1.4.5-hotfixes         -> origin/v1.4.5-hotfixes
 * [new branch]          v1.4.6-hotfixes         -> origin/v1.4.6-hotfixes
 * [new branch]          v1.4.9-hotfixes         -> origin/v1.4.9-hotfixes
 * [new branch]          v1.5.4-hotfixes         -> origin/v1.5.4-hotfixes
 * [new tag]             v1.4.6-hotfix.1         -> v1.4.6-hotfix.1
 * [new tag]             v1.5.4-hotfix.2         -> v1.5.4-hotfix.2
 * [new tag]             v1.5.8                  -> v1.5.8
 * [new tag]             v1.3.0                  -> v1.3.0
 * [new tag]             v1.3.1                  -> v1.3.1
 * [new tag]             v1.3.10                 -> v1.3.10
 * [new tag]             v1.3.11                 -> v1.3.11
 * [new tag]             v1.3.12                 -> v1.3.12
 * [new tag]             v1.3.13                 -> v1.3.13
 * [new tag]             v1.3.14                 -> v1.3.14
 * [new tag]             v1.3.2                  -> v1.3.2
 * [new tag]             v1.3.3                  -> v1.3.3
 * [new tag]             v1.3.4                  -> v1.3.4
 * [new tag]             v1.3.5                  -> v1.3.5
 * [new tag]             v1.3.6                  -> v1.3.6
 * [new tag]             v1.3.7                  -> v1.3.7
 * [new tag]             v1.3.8                  -> v1.3.8
 * [new tag]             v1.3.9                  -> v1.3.9
 * [new tag]             v1.4.0                  -> v1.4.0
 * [new tag]             v1.4.1                  -> v1.4.1
 * [new tag]             v1.4.10                 -> v1.4.10
 * [new tag]             v1.4.11                 -> v1.4.11
 * [new tag]             v1.4.12                 -> v1.4.12
 * [new tag]             v1.4.13                 -> v1.4.13
 * [new tag]             v1.4.14                 -> v1.4.14
 * [new tag]             v1.4.15                 -> v1.4.15
 * [new tag]             v1.4.16                 -> v1.4.16
 * [new tag]             v1.4.17                 -> v1.4.17
 * [new tag]             v1.4.18                 -> v1.4.18
 * [new tag]             v1.4.19                 -> v1.4.19
 * [new tag]             v1.4.2                  -> v1.4.2
 * [new tag]             v1.4.3                  -> v1.4.3
 * [new tag]             v1.4.4                  -> v1.4.4
 * [new tag]             v1.4.5                  -> v1.4.5
 * [new tag]             v1.4.6                  -> v1.4.6
 * [new tag]             v1.4.7                  -> v1.4.7
 * [new tag]             v1.4.8                  -> v1.4.8
 * [new tag]             v1.4.9                  -> v1.4.9
 * [new tag]             v1.5.0                  -> v1.5.0
 * [new tag]             v1.5.1                  -> v1.5.1
 * [new tag]             v1.5.2                  -> v1.5.2
 * [new tag]             v1.5.3                  -> v1.5.3
 * [new tag]             v1.5.4                  -> v1.5.4
 * [new tag]             v1.5.4-hotfix.1         -> v1.5.4-hotfix.1
 * [new tag]             v1.5.5                  -> v1.5.5
 * [new tag]             v1.5.6                  -> v1.5.6
 * [new tag]             v1.5.7                  -> v1.5.7
Updating 8661d8aec..7a4c33425
 dev/bots/serviceaccount.enc                        |  Bin 0 -> 2067 bytes
 .../app/src/main/res/mipmap-hdpi/ic_launcher.png   |  Bin 0 -> 544 bytes
 .../app/src/main/res/mipmap-mdpi/ic_launcher.png   |  Bin 0 -> 442 bytes
 .../app/src/main/res/mipmap-xhdpi/ic_launcher.png  |  Bin 0 -> 721 bytes
 .../app/src/main/res/mipmap-xxhdpi/ic_launcher.png |  Bin 0 -> 1031 bytes
 .../src/main/res/mipmap-xxxhdpi/ic_launcher.png    |  Bin 0 -> 1443 bytes
 .../AppIcon.appiconset/Icon-App-1024x1024@1x.png   |  Bin 0 -> 11112 bytes
 .../AppIcon.appiconset/Icon-App-20x20@1x.png       |  Bin 0 -> 564 bytes
 .../AppIcon.appiconset/Icon-App-20x20@2x.png       |  Bin 0 -> 1283 bytes
 .../AppIcon.appiconset/Icon-App-20x20@3x.png       |  Bin 0 -> 1588 bytes
 .../AppIcon.appiconset/Icon-App-29x29@1x.png       |  Bin 0 -> 1025 bytes
 .../AppIcon.appiconset/Icon-App-29x29@2x.png       |  Bin 0 -> 1716 bytes
 .../AppIcon.appiconset/Icon-App-29x29@3x.png       |  Bin 0 -> 1920 bytes
 .../AppIcon.appiconset/Icon-App-40x40@1x.png       |  Bin 0 -> 1283 bytes
 .../AppIcon.appiconset/Icon-App-40x40@2x.png       |  Bin 0 -> 1895 bytes
 .../AppIcon.appiconset/Icon-App-40x40@3x.png       |  Bin 0 -> 2665 bytes
 .../AppIcon.appiconset/Icon-App-60x60@2x.png       |  Bin 0 -> 2665 bytes
 .../AppIcon.appiconset/Icon-App-60x60@3x.png       |  Bin 0 -> 3831 bytes
 .../AppIcon.appiconset/Icon-App-76x76@1x.png       |  Bin 0 -> 1888 bytes
 .../AppIcon.appiconset/Icon-App-76x76@2x.png       |  Bin 0 -> 3294 bytes
 .../AppIcon.appiconset/Icon-App-83.5x83.5@2x.png   |  Bin 0 -> 3612 bytes
 .../LaunchImage.imageset/LaunchImage.png           |  Bin 0 -> 68 bytes
 .../LaunchImage.imageset/LaunchImage@2x.png        |  Bin 0 -> 68 bytes
 .../LaunchImage.imageset/LaunchImage@3x.png        |  Bin 0 -> 68 bytes
 .../bin/src/main/res/mipmap-hdpi/ic_launcher.png   |  Bin 0 -> 544 bytes
 .../bin/src/main/res/mipmap-mdpi/ic_launcher.png   |  Bin 0 -> 442 bytes
 .../bin/src/main/res/mipmap-xhdpi/ic_launcher.png  |  Bin 0 -> 721 bytes
 .../bin/src/main/res/mipmap-xxhdpi/ic_launcher.png |  Bin 0 -> 1031 bytes
 .../src/main/res/mipmap-xxxhdpi/ic_launcher.png    |  Bin 0 -> 1443 bytes
 .../app/src/main/res/mipmap-hdpi/ic_launcher.png   |  Bin 0 -> 544 bytes
 .../app/src/main/res/mipmap-mdpi/ic_launcher.png   |  Bin 0 -> 442 bytes
 .../app/src/main/res/mipmap-xhdpi/ic_launcher.png  |  Bin 0 -> 721 bytes
 .../app/src/main/res/mipmap-xxhdpi/ic_launcher.png |  Bin 0 -> 1031 bytes
 .../src/main/res/mipmap-xxxhdpi/ic_launcher.png    |  Bin 0 -> 1443 bytes
 .../EarlGrey/EarlGrey/EarlGrey.framework/EarlGrey  |  Bin 0 -> 6070016 bytes
 .../EarlGrey/EarlGrey.framework/Info.plist         |  Bin 0 -> 1298 bytes
 .../AppIcon.appiconset/Icon-App-1024x1024@1x.png   |  Bin 0 -> 11112 bytes
 .../AppIcon.appiconset/Icon-App-20x20@1x.png       |  Bin 0 -> 564 bytes
 .../AppIcon.appiconset/Icon-App-20x20@2x.png       |  Bin 0 -> 1283 bytes
 .../AppIcon.appiconset/Icon-App-20x20@3x.png       |  Bin 0 -> 1588 bytes
 .../AppIcon.appiconset/Icon-App-29x29@1x.png       |  Bin 0 -> 1025 bytes
 .../AppIcon.appiconset/Icon-App-29x29@2x.png       |  Bin 0 -> 1716 bytes
 .../AppIcon.appiconset/Icon-App-29x29@3x.png       |  Bin 0 -> 1920 bytes
 .../AppIcon.appiconset/Icon-App-40x40@1x.png       |  Bin 0 -> 1283 bytes
 .../AppIcon.appiconset/Icon-App-40x40@2x.png       |  Bin 0 -> 1895 bytes
 .../AppIcon.appiconset/Icon-App-40x40@3x.png       |  Bin 0 -> 2665 bytes
 .../AppIcon.appiconset/Icon-App-60x60@2x.png       |  Bin 0 -> 2665 bytes
 .../AppIcon.appiconset/Icon-App-60x60@3x.png       |  Bin 0 -> 3831 bytes
 .../AppIcon.appiconset/Icon-App-76x76@1x.png       |  Bin 0 -> 1888 bytes
 .../AppIcon.appiconset/Icon-App-76x76@2x.png       |  Bin 0 -> 3294 bytes
 .../AppIcon.appiconset/Icon-App-83.5x83.5@2x.png   |  Bin 0 -> 3612 bytes
 .../values/strings_en.arb}                         |    0
 .../test/data/dart_dependencies_test/.dartignore   |    0
 1588 files changed, 65756 insertions(+), 16597 deletions(-)

Upgrading engine...
Checking Dart SDK version...
Downloading Dart SDK from Flutter engine 52c7a1e849a170be4b2b2fe34142ca2c0a6fea1f...
Unzipping Dart SDK...
Building flutter tool...
Running pub upgrade...
Downloading android-arm-profile/windows-x64 tools...                0,3s
Downloading android-arm-release/windows-x64 tools...                0,3s
Downloading android-arm64-profile/windows-x64 tools...              0,2s
Downloading android-arm64-release/windows-x64 tools...              0,2s
Downloading android-arm-dynamic-profile/windows-x64 tools...         0,3s
Downloading android-arm-dynamic-release/windows-x64 tools...         0,2s
Downloading android-arm64-dynamic-profile/windows-x64 tools...         0,3s
Downloading android-arm64-dynamic-release/windows-x64 tools...         0,3s
Downloading android-x86 tools...                                    1,3s
Downloading android-x64 tools...                                    1,2s
Downloading android-arm tools...                                    0,5s
Downloading android-arm-profile tools...                            0,4s
Downloading android-arm-release tools...                            0,4s
Downloading android-arm64 tools...                                  0,5s
Downloading android-arm64-profile tools...                          0,4s
Downloading android-arm64-release tools...                          0,3s
Downloading android-arm-dynamic-profile tools...                    0,4s
Downloading android-arm-dynamic-release tools...                    0,4s
Downloading android-arm64-dynamic-profile tools...                  0,5s
Downloading android-arm64-dynamic-release tools...                  0,4s
Downloading package sky_engine...                                   0,2s
Downloading common tools...                                         0,6s
Downloading common tools...                                         0,6s
Downloading windows-x64 tools...                                    1,4s

Oops; flutter has exited unexpectedly.
Sending crash report to Google.
Crash report sent (report ID: f379a90c0847f0e9)
Crash report written to C:\tools\fluttersdk\flutter\flutter_03.log;
please let us know at https://github.com/flutter/flutter/issues.

Flutter 1.2.1 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 8661d8aecd (3 months ago) • 2019-04-29 11:05:24 -0700
Engine • revision 52c7a1e849
Tools • Dart 2.1.2 (build 2.1.2-dev.0.0 0a7dcf17eb)

Running flutter doctor...

Oops; flutter has exited unexpectedly.
Sending crash report to Google.
Crash report sent (report ID: 29ff10f0479f619f)
Crash report written to C:\tools\fluttersdk\flutter\flutter_04.log;
please let us know at https://github.com/flutter/flutter/issues.
```

Log file C:\tools\fluttersdk\flutter\flutter_04.log:

Flutter crash report; please file at https://github.com/flutter/flutter/issues.

## command

flutter --no-version-check doctor

## exception

FileSystemException: FileSystemException: Cannot open file, path = 'C:\tools\fluttersdk\flutter\bin\cache\artifacts\engine\windows-x64\icudtl.dat' (OS Error: Pyydettyä toimintoa ei voi suorittaa tiedostolle, jonka käyttäjän yhdistämä osa on avoinna.
, errno = 1224)

```
#0      _File.throwIfError (dart:io/file_impl.dart:643:7)
#1      _File.openSync (dart:io/file_impl.dart:487:5)
#2      _File.writeAsBytesSync (dart:io/file_impl.dart:612:31)
#3      _LocalFile&LocalFileSystemEntity&ForwardingFile.writeAsBytesSync (package:file/src/forwarding/forwarding_file.dart:124:16)
#4      _WindowsUtils._unpackArchive (package:flutter_tools/src/base/os.dart:235:16)
#5      _WindowsUtils.unzip (package:flutter_tools/src/base/os.dart:191:5)
......

```

**Comment by DanTup** [comment]
It seems like a file in `C:\tools\fluttersdk\flutter\bin\cache` may be locked. Do you have your IDE open? If so, try closing (if not, try rebooting) then try running `flutter doctor` to force it to download anything that's still missing.

**Comment by kinex** [comment]
Fixed by restarting by PC and running `flutter upgrade` again. 

IDE (VS Code) was open when I initially run `flutter upgrade`. Then I closed IDE and run `flutter upgrade` again, same error. Finally restarting PC fixed the issue.
