### ISSUE TITLE
flutter webdev serve failing on below

### ISSUE THREAD

**Issue by kw2019ltd** [flutter/flutter#32300]
[INFO] Unhandled exception:
```
Bad state: Unable to start build daemon.
#0      _handleDaemonStartup (package:build_daemon/client.dart:52:5)
<asynchronous suspension>
#1      BuildDaemonClient.connect (package:build_daemon/client.dart:142:11)
<asynchronous suspension>
#2      connectClient (package:webdev/src/daemon_client.dart:17:23)
#3      _startBuildDaemon (package:webdev/src/serve/dev_workflow.dart:24:18)
<asynchronous suspension>
#4      DevWorkflow.start (package:webdev/src/serve/dev_workflow.dart:165:24)
<asynchronous suspension>
#5      ServeCommand.run (package:webdev/src/command/serve_command.dart:110:27)
<asynchronous suspension>
#6      CommandRunner.runCommand (package:args/command_runner.dart:196:27)
<asynchronous suspension>
#7      _CommandRunner.runCommand (package:webdev/src/webdev_command_runner.dart:38:24)
<asynchronous suspension>
#8      CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:111:29)
#9      new Future.sync (dart:async/future.dart:224:31)
#10     CommandRunner.run (package:args/command_runner.dart:111:11)
#11     run (package:webdev/src/webdev_command_runner.dart:19:56)
#12     main (file:///C:/Users/kotaibaw/AppData/Roaming/Pub/Cache/hosted/pub.dartlang.org/webdev-2.0.4/bin/webdev.dart:17:22)
<asynchronous suspension>
#13     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:298:32)
#14     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:171:12)
```

C:\Tools\flutter_web-master\examples\hello_world>

**Comment by kevmoo** [comment]
@kw2019ltd – could you provide more information? What command did you execute? Which version of Flutter are you using?

CC @jakemac53 @grouma

**Comment by grouma** [comment]
Closing in favor of https://github.com/dart-lang/webdev/issues/375

Can you take a look at the latest comment in the issue above and provide the requested details.

**Comment by pouledodue** [comment]
same here
I added details
