### ISSUE TITLE
_dismissedBottomSheets assertion failure in ScaffoldState.showBottomSheet

### ISSUE THREAD

**Issue by jason-simmons** [flutter/flutter#3232]
Open the Stocks app.  Double-tap on a symbol to show the pop-up at the bottom of the screen.  Repeatedly drag the pop-up down and up with fast motions.

Eventually this assertion will trigger:

```
7ms total 13.123ms
I/flutter (18081): ══╡ EXCEPTION CAUGHT BY GESTURE LIBRARY ╞═══════════════════════════════════════════════════════════════════════════════
I/flutter (18081): The following exception was raised while routing a pointer event:
I/flutter (18081): 'package:flutter/src/material/scaffold.dart': Failed assertion: line 402: '_dismissedBottomSheets != null' is not true.
I/flutter (18081): Either the assertion indicates an error in the framework itself, or we should provide substantially more information in
I/flutter (18081): this error message to help you determine and fix the underlying cause.
I/flutter (18081): In either case, please report this assertion by filing a bug on GitHub:
I/flutter (18081):   https://github.com/flutter/flutter/issues/new
I/flutter (18081): Event:
I/flutter (18081):   PointerMoveEvent(Point(206.3, 569.0))
I/flutter (18081): Stack trace:
I/flutter (18081): #0      _AssertionError._throwNew (dart:core-patch/errors_patch.dart:27)
I/flutter (18081): #1      ScaffoldState.showBottomSheet.<anonymous closure> (package:flutter/src/material/scaffold.dart:402)
I/flutter (18081): #2      _PersistentBottomSheetState._handleStatusChange (package:flutter/src/material/scaffold.dart:702)
I/flutter (18081): #3      Animation&AnimationEagerListenerMixin&AnimationLocalListenersMixin&AnimationLocalStatusListenersMixin.notifyStatusListeners (package:flutter/src/animation/listener_helpers.dart:87)
I/flutter (18081): #4      AnimationController._checkStatusChanged (package:flutter/src/animation/animation_controller.dart:240)
I/flutter (18081): #5      AnimationController.value= (package:flutter/src/animation/animation_controller.dart:124)
I/flutter (18081): #6      _BottomSheetState._handleDragUpdate (package:flutter/src/material/bottom_sheet.dart:102)
I/flutter (18081): #7      _DragGestureRecognizer.handleEvent (package:flutter/src/gestures/drag.dart:77)
I/flutter (18081): #8      PointerRouter.route (package:flutter/src/gestures/pointer_router.dart:53)
I/flutter (18081): #9      BindingBase&Scheduler&Gesturer.handleEvent (package:flutter/src/gestures/binding.dart:110)
I/flutter (18081): #10     BindingBase&Scheduler&Gesturer.dispatchEvent (package:flutter/src/gestures/binding.dart:88)
I/flutter (18081): #11     BindingBase&Scheduler&Gesturer._handlePointerEvent (package:flutter/src/gestures/binding.dart:70)
I/flutter (18081): #12     BindingBase&Scheduler&Gesturer._handlePointerPacket (package:flutter/src/gestures/binding.dart:42)
I/flutter (18081): #13     _dispatchPointerPacket (file:///ssd2/sky/engine/src/out/android_Debug/gen/sky/bindings/hooks.dart:43)
I/flutter (18081): ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
```

**Comment by jason-simmons** [comment]
@Hixie

**Comment by Hixie** [comment]
cc @HansMuller

**Comment by abarth** [comment]
We could be hitting the dismissed state multiple times via `_BottomSheetState._handleDragEnd` before we get a chance to rebuild and remove the sheet from the tree.
