### ISSUE TITLE
dart:ui/hooks.dart': Failed assertion: line 278: '<optimized out>': is not true and unable to scroll page down

### ISSUE THREAD

**Issue by JONA-Cureambit** [flutter/flutter#32403]
I am getting below error when scrolling page down. Before upgrading to  v1.5.4-hotfix.2 (stable) it was working fine.
Also i am unable to scroll page down.

E/flutter (21327): [ERROR:flutter/shell/common/shell.cc(184)] Dart Error: Unhandled exception:
E/flutter (21327): 'dart:ui/hooks.dart': Failed assertion: line 278: '<optimized out>': is not true.
E/flutter (21327): #0      _AssertionError._doThrowNew (dart:core-patch/errors_patch.dart:40:39)
E/flutter (21327): #1      _AssertionError._throwNew (dart:core-patch/errors_patch.dart:36:5)
E/flutter (21327): #2      _unpackPointerDataPacket (dart:ui/hooks.dart:278:10)
E/flutter (21327): #3      _dispatchPointerDataPacket (dart:ui/hooks.dart:154:94)
I/chatty  (21327): uid=10091(com.cureambit.my_markdown_app) Thread-2 identical 6 lines

## Logs

   [verbose_log.txt](https://github.com/flutter/flutter/files/3162048/verbose_log.txt)

```
return ListView(
      scrollDirection: Axis.vertical,
      padding: EdgeInsets.only(left: 10.0, right: 10.0, top: 10.0),
      children: mdWidgets,
    );
```

     `flutter analyze` : No issues found! (ran in 2.5s)

√] Flutter (Channel stable, v1.5.4-hotfix.2, on Microsoft Windows [Version 10.0.17134.706], locale
en-IN)
    • Flutter version 1.5.4-hotfix.2 at C:\dart_flutter\flutter
    • Framework revision 7a4c33425d (10 days ago), 2019-04-29 11:05:24 -0700
    • Engine revision 52c7a1e849
    • Dart version 2.3.0 (build 2.3.0-dev.0.5 a1668566e5)

[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at C:\Users\John\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)
    • All Android licenses accepted.

[√] Android Studio (version 3.2)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 31.3.1
    • Dart plugin version 181.5656
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)

[√] Connected device (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 9 (API 28) (emulator)

• No issues found!

**Comment by JONA-Cureambit** [comment]
This issue got resolved after re-installing flutter SDK (i.e purge existing SDK and install fresh SDK on my machine).
