### ISSUE TITLE
"vm_service_client 0.2.6+2, flutter_driver error" when running stocks sample

### ISSUE THREAD

**Issue by slillon** [flutter/flutter#32438]
## Steps to Reproduce

1. git clone https://github.com/flutter/flutter.git
2. cd examples/stocks
3. flutter channel dev
4. flutter packages get

The output of the last command throws:

Because every version of flutter_driver from sdk depends on vm_service_client 0.2.6+1 and stocks depends on vm_service_client 0.2.6+2, flutter_driver from sdk is forbidden.
So, because stocks depends on flutter_driver any from sdk, version solving failed.

## Logs

```
[+8947 ms] Because every version of flutter_driver from sdk depends on vm_service_client 0.2.6+1 and stocks depends on
vm_service_client 0.2.6+2, flutter_driver from sdk is forbidden.
[   +4 ms] So, because stocks depends on flutter_driver any from sdk, version solving failed.
[  +49 ms] Running "flutter packages get" in stocks... (completed in 9,0s)
[   +1 ms] "flutter run" took 9.955ms.
[        ] "flutter run" took 9.955ms.
pub get failed (1)

#0      throwToolExit (package:flutter_tools/src/base/common.dart:24:3)
#1      pub (package:flutter_tools/src/dart/pub.dart:173:5)
<asynchronous suspension>
#2      pubGet (package:flutter_tools/src/dart/pub.dart:106:13)
<asynchronous suspension>
#3      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:476:13)
<asynchronous suspension>
#4      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:424:33)
<asynchronous suspension>
#5      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:142:29)
<asynchronous suspension>
#6      _rootRun (dart:async/zone.dart:1124:13)
#7      _CustomZone.run (dart:async/zone.dart:1021:19)
#8      _runZoned (dart:async/zone.dart:1516:10)
#9      runZoned (dart:async/zone.dart:1463:12)
#10     AppContext.run (package:flutter_tools/src/base/context.dart:141:18)
<asynchronous suspension>
#11     FlutterCommand.run (package:flutter_tools/src/runner/flutter_command.dart:415:20)
#12     CommandRunner.runCommand (package:args/command_runner.dart:196:27)
<asynchronous suspension>
#13     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:396:21)
<asynchronous suspension>
#14     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:142:29)
<asynchronous suspension>
#15     _rootRun (dart:async/zone.dart:1124:13)
#16     _CustomZone.run (dart:async/zone.dart:1021:19)
#17     _runZoned (dart:async/zone.dart:1516:10)
#18     runZoned (dart:async/zone.dart:1463:12)
#19     AppContext.run (package:flutter_tools/src/base/context.dart:141:18)
<asynchronous suspension>
#20     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:356:19)
<asynchronous suspension>
#21     CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:111:29)
#22     new Future.sync (dart:async/future.dart:224:31)
#23     CommandRunner.run (package:args/command_runner.dart:111:11)
#24     FlutterCommandRunner.run (package:flutter_tools/src/runner/flutter_command_runner.dart:242:18)
#25     run.<anonymous closure> (package:flutter_tools/runner.dart:60:20)
<asynchronous suspension>
#26     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:142:29)
<asynchronous suspension>
#27     _rootRun (dart:async/zone.dart:1124:13)
#28     _CustomZone.run (dart:async/zone.dart:1021:19)
#29     _runZoned (dart:async/zone.dart:1516:10)
#30     runZoned (dart:async/zone.dart:1463:12)
#31     AppContext.run (package:flutter_tools/src/base/context.dart:141:18)
<asynchronous suspension>
#32     runInContext (package:flutter_tools/src/context_runner.dart:50:24)
<asynchronous suspension>
#33     run (package:flutter_tools/runner.dart:51:10)
#34     main (package:flutter_tools/executable.dart:60:9)
<asynchronous suspension>
#35     main (file:///Users/slillo/Tools/flutter/packages/flutter_tools/bin/flutter_tools.dart:8:3)
#36     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:298:32)
#37     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:171:12)
```

```
Because every version of flutter_driver from sdk depends on vm_service_client 0.2.6+1 and stocks depends on vm_service_client 0.2.6+2, flutter_driver from sdk is forbidden.
So, because stocks depends on flutter_driver any from sdk, version solving failed.
Running "flutter packages get" in stocks...
pub get failed (1)
```

```
[✓] Flutter (Channel dev, v1.5.8, on Mac OS X 10.14.4 18E226, locale es-CL)
    • Flutter version 1.5.8 at /Users/slillo/Tools/flutter
    • Framework revision 0ba67226ee (2 weeks ago), 2019-04-24 17:18:28 -0700
    • Engine revision c63d1cf9c9
    • Dart version 2.3.0 (build 2.3.0-dev.0.1 1f1592edce)


[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/slillo/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
    • All Android licenses accepted.

[!] iOS toolchain - develop for iOS devices (Xcode 10.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.2.1, Build version 10E1001
    ✗ Verify that all connected devices have been paired with this computer in Xcode.
      If all devices have been paired, libimobiledevice and ideviceinstaller may require updating.
      To update with Brew, run:
        brew update
        brew uninstall --ignore-dependencies libimobiledevice
        brew uninstall --ignore-dependencies usbmuxd
        brew install --HEAD usbmuxd
        brew unlink usbmuxd
        brew link usbmuxd
        brew install --HEAD libimobiledevice
        brew install ideviceinstaller
    • ios-deploy 1.9.4
    • CocoaPods version 1.6.1

[✓] Android Studio (version 3.4)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 35.0.1
    • Dart plugin version 183.5901
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

[!] IntelliJ IDEA Ultimate Edition (version 2019.1)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.dev/intellij-setup/#installing-the-plugins

[✓] VS Code (version 1.33.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 2.25.1

[✓] Connected device (1 available)
    • iPhone Xʀ • 487FBE6D-CD08-4FA9-A11F-03E3C07DD00B • ios • com.apple.CoreSimulator.SimRuntime.iOS-12-2 (simulator)

! Doctor found issues in 2 categories.
```

**Comment by BondarenkoStas** [comment]
@slillon I tried it with current flutter stable v1.9.1+hotfix.4, everything's fine. Thank you for report, I think it's safe to close the issue.
