### ISSUE TITLE
[in_app_purchase] Fatal Exception: java.lang.IllegalStateException Reply already submitted

### ISSUE THREAD

**Issue by benadrasni** [flutter/flutter#32462]
in_app_purchase 0.1.0+1

I've got an error through Crashlytics. It was marked as a crash, but I don't remember to see it on the phone (Pixel 2XL - Android 10). Application seems to behave normally.

## Logs

Fatal Exception: java.lang.IllegalStateException: Reply already submitted
       at io.flutter.embedding.engine.dart.DartMessenger$Reply.reply(DartMessenger.java:124)
       at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler$1.success(MethodChannel.java:204)
       at io.flutter.plugins.inapppurchase.InAppPurchasePlugin$1.onBillingSetupFinished(InAppPurchasePlugin.java:132)
       at com.android.billingclient.api.BillingClientImpl$BillingServiceConnection.onServiceConnected(BillingClientImpl.java:1030)
       at android.app.LoadedApk$ServiceDispatcher.doConnected(LoadedApk.java:1957)
       at android.app.LoadedApk$ServiceDispatcher$RunConnection.run(LoadedApk.java:1989)
       at android.os.Handler.handleCallback(Handler.java:883)
       at android.os.Handler.dispatchMessage(Handler.java:100)
       at android.os.Looper.loop(Looper.java:214)
       at android.app.ActivityThread.main(ActivityThread.java:7116)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:925)

C:\Dev\Projects\abherbs_flutter>flutter analyze
Analyzing abherbs_flutter...
No issues found! (ran in 10.8s)

C:\Dev\Projects\abherbs_flutter>flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[Ô^Ü] Flutter (Channel dev, v1.5.3, on Microsoft Windows [Version 6.1.7601],
    locale sk-SK)
[Ô^Ü] Android toolchain - develop for Android devices (Android SDK version 28.0.
3)
[Ô^Ü] Android Studio (version 3.4)
[!] IntelliJ IDEA Ultimate Edition (version 2019.1)
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
[!] Connected device
    ! No devices available

! Doctor found issues in 2 categories.

**Comment by mklim** [comment]
Thanks for the report!
