### ISSUE TITLE
Camera Plugin has many error when I use CupertinoApp?

### ISSUE THREAD

**Issue by NTMS2017** [flutter/flutter#32473]
I just copy/paste the code from https://pub.dev/packages/camera#-example-tab-. Only changes I made in App part. I use CupertinoApp and got tons of error. When I change to MaterialApp while using I got different usage error.

After seeing **Google I/0 2019 https://www.youtube.com/watch?v=3PdUaidHc-E**  I thought I can use camera plugin with no error. 

**MaterialApp Usage Error:**
```
I/flutter ( 8171): Error: Uninitialized CameraController.
I/flutter ( 8171): Error Message: takePicture was called on uninitialized CameraController
D/ViewRootImpl@30dc3f9[MainActivity]( 8171): ViewPostIme pointer 0
D/ViewRootImpl@30dc3f9[MainActivity]( 8171): ViewPostIme pointer 1
D/ViewRootImpl@30dc3f9[MainActivity]( 8171): ViewPostIme pointer 0
D/ViewRootImpl@30dc3f9[MainActivity]( 8171): ViewPostIme pointer 1
D/ViewRootImpl@30dc3f9[MainActivity]( 8171): ViewPostIme pointer 0
D/ViewRootImpl@30dc3f9[MainActivity]( 8171): ViewPostIme pointer 1
I/CameraManager( 8171): getCameraCharacteristics : cameraId = 1
V/Surface ( 8171): sf_framedrop debug : 0x4f4c, game : false, logging : 0
V/Surface ( 8171): sf_framedrop debug : 0x4f4c, game : false, logging : 0
I/CameraManager( 8171): getCameraCharacteristics : cameraId = 1
D/ViewRootImpl@30dc3f9[MainActivity]( 8171): ViewPostIme pointer 0
D/ViewRootImpl@30dc3f9[MainActivity]( 8171): ViewPostIme pointer 1
I/Choreographer( 8171): Skipped 69 frames!  The application may be doing too much work on its main thread.
V/Surface ( 8171): sf_framedrop debug : 0x4f4c, game : false, logging : 0
E/flutter ( 8171): [ERROR:flutter/lib/ui/ui_dart_state.cc(148)] Unhandled Exception: A CameraController was used after being disposed.
E/flutter ( 8171): Once you have called dispose() on a CameraController, it can no longer be used.
E/flutter ( 8171): #0      ChangeNotifier._debugAssertNotDisposed.<anonymous closure> (package:flutter/src/foundation/change_notifier.dart:105:9)
E/flutter ( 8171): #1      ChangeNotifier._debugAssertNotDisposed (package:flutter/src/foundation/change_notifier.dart:111:6)
E/flutter ( 8171): #2      ChangeNotifier.notifyListeners (package:flutter/src/foundation/change_notifier.dart:200:12)
E/flutter ( 8171): #3      ValueNotifier.value= (package:flutter/src/foundation/change_notifier.dart:270:5)
E/flutter ( 8171): #4      CameraController.initialize (package:camera/camera.dart:236:7)
E/flutter ( 8171): <asynchronous suspension>
E/flutter ( 8171): #5      _CameraExampleHomeState.onNewCameraSelected (package:capital_fast_credit/main.dart:121:24)
E/flutter ( 8171): <asynchronous suspension>
E/flutter ( 8171): #6      _RadioState._handleChanged (package:flutter/src/material/radio.dart)
E/flutter ( 8171): #7      RenderToggleable._handleTap (package:flutter/src/material/toggleable.dart:285:9)
E/flutter ( 8171): #8      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:166:24)
E/flutter ( 8171): #9      TapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:240:9)
E/flutter ( 8171): #10     TapGestureRecognizer.acceptGesture (package:flutter/src/gestures/tap.dart:211:7)
E/flutter ( 8171): #11     GestureArenaManager.sweep (package:flutter/src/gestures/arena.dart:156:27)
E/flutter ( 8171): #12     _WidgetsFlutterBinding&BindingBase&GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:225:20)
E/flutter ( 8171): #13     _WidgetsFlutterBinding&BindingBase&GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:199:22)
E/flutter ( 8171): #14     _WidgetsFlutterBinding&BindingBase&GestureBinding._handlePointerEvent (package:flutter/src/gestures/binding.dart:156:7)
E/flutter ( 8171): #15     _WidgetsFlutterBinding&BindingBase&GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:102:7)
E/flutter ( 8171): #16     _WidgetsFlutterBinding&BindingBase&GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:86:7)
E/flutter ( 8171): #17     _rootRunUnary (dart:async/zone.dart:1136:13)
E/flutter ( 8171): #18     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
E/flutter ( 8171): #19     _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
E/flutter ( 8171): #20     _invoke1 (dart:ui/hooks.dart:233:10)
E/flutter ( 8171): #21     _dispatchPointerDataPacket (dart:ui/hooks.dart:154:5)
E/flutter ( 8171): 
D/ViewRootImpl@30dc3f9[MainActivity]( 8171): ViewPostIme pointer 0
D/ViewRootImpl@30dc3f9[MainActivity]( 8171): ViewPostIme pointer 1
I/CameraManager( 8171): getCameraCharacteristics : cameraId = 1
V/Surface ( 8171): sf_framedrop debug : 0x4f4c, game : false, logging : 0
V/Surface ( 8171): sf_framedrop debug : 0x4f4c, game : false, logging : 0
I/CameraManager( 8171): getCameraCharacteristics : cameraId = 1
I/Choreographer( 8171): Skipped 73 frames!  The application may be doing too much work on its main thread.
V/Surface ( 8171): sf_framedrop debug : 0x4f4c, game : false, logging : 0
D/ViewRootImpl@30dc3f9[MainActivity]( 8171): ViewPostIme pointer 0
D/ViewRootImpl@30dc3f9[MainActivity]( 8171): ViewPostIme pointer 1
D/ViewRootImpl@30dc3f9[MainActivity]( 8171): MSG_WINDOW_FOCUS_CHANGED 0
D/SensorManager( 8171): unregisterListener ::   
```

**CupertinoApp Code:**
```
List<CameraDescription> cameras;

void main() async {
  await SystemChrome.setEnabledSystemUIOverlays([]);
  await SystemChrome.setPreferredOrientations([DeviceOrientation.portraitUp]);

  try {
    cameras = await availableCameras();
  } on CameraException catch (e) {
    logError(e.code, e.description);
  }
  runApp(new MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    SystemChrome.setEnabledSystemUIOverlays([]);
    SystemChrome.setPreferredOrientations([DeviceOrientation.portraitUp]);
    return CupertinoApp(
      debugShowCheckedModeBanner: false,
      title: 'Capital Fast',
      theme: CupertinoThemeData(
        primaryColor: Colors.green,
      ),
      home: CameraExampleHome(title: 'Capital Fast'),
    );
  }
}
```

**CupertinoApp Error:**
```
Resolving dependencies...
Running Gradle task 'assembleDebug'...
Built build/app/outputs/apk/debug/app-debug.apk.
Installing build/app/outputs/apk/app.apk...
Syncing files to device SM G935F...
I/flutter (11149): ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
I/flutter (11149): The following assertion was thrown building AppBar(dirty, dependencies:
I/flutter (11149): [_LocalizationsScope-[GlobalKey#0292c]], state: _AppBarState#f8a86):
I/flutter (11149): No MaterialLocalizations found.
I/flutter (11149): AppBar widgets require MaterialLocalizations to be provided by a Localizations widget ancestor.
I/flutter (11149): Localizations are used to generate many different messages, labels,and abbreviations which are used
I/flutter (11149): by the material library. 
I/flutter (11149): To introduce a MaterialLocalizations, either use a  MaterialApp at the root of your application to
I/flutter (11149): include them automatically, or add a Localization widget with a MaterialLocalizations delegate.
I/flutter (11149): The specific widget that could not find a MaterialLocalizations ancestor was:
I/flutter (11149):   AppBar
I/flutter (11149): The ancestors of this widget were:
I/flutter (11149):   FlexibleSpaceBarSettings
I/flutter (11149):   ConstrainedBox(BoxConstraints(0.0<=w<=Infinity, 0.0<=h<=56.0))
I/flutter (11149):   MediaQuery(MediaQueryData(size: Size(360.0, 640.0), devicePixelRatio: 4.0, textScaleFactor: 1.0,
I/flutter (11149):   platformBrightness: Brightness.light, padding: EdgeInsets.zero, viewInsets: EdgeInsets.zero,
I/flutter (11149):   alwaysUse24HourFormat: true, accessibleNavigation: falsedisableAnimations: falseinvertColors:
I/flutter (11149):   falseboldText: false))
I/flutter (11149):   LayoutId-[<_ScaffoldSlot.appBar>](id: _ScaffoldSlot.appBar)
I/flutter (11149):   CustomMultiChildLayout
I/flutter (11149):   AnimatedBuilder(animation: AnimationController#8d9b4(⏭ 1.000; paused))
I/flutter (11149):   DefaultTextStyle(debugLabel: (englishLike body1 2014).merge(blackMountainView body1), inherit:
I/flutter (11149):   false, color: Color(0xdd000000), family: Roboto, size: 14.0, weight: 400, baseline: alphabetic,
I/flutter (11149):   decoration: TextDecoration.none, softWrap: wrapping at box width, overflow: clip)
I/flutter (11149):   AnimatedDefaultTextStyle(duration: 200ms, debugLabel: (englishLike body1
I/flutter (11149):   2014).merge(blackMountainView body1), inherit: false, color: Color(0xdd000000), family: Roboto,
I/flutter (11149):   size: 14.0, weight: 400, baseline: alphabetic, decoration: TextDecoration.none, softWrap: wrapping
I/flutter (11149):   at box width, overflow: clip)
I/flutter (11149):   _InkFeatures-[GlobalKey#680b5 ink renderer]
I/flutter (11149):   NotificationListener<LayoutChangedNotification>
I/flutter (11149):   PhysicalModel(shape: rectangle, borderRadius: BorderRadius.zero, elevation: 0.0, color:
I/flutter (11149):   Color(0xfffafafa), shadowColor: Color(0xff000000))
I/flutter (11149):   AnimatedPhysicalModel(duration: 200ms, shape: rectangle, borderRadius: BorderRadius.zero,
I/flutter (11149):   elevation: 0.0, color: Color(0xfffafafa), animateColor: false, shadowColor: Color(0xff000000),
I/flutter (11149):   animateShadowColor: true)
I/flutter (11149):   Material(type: canvas, color: Color(0xfffafafa))
I/flutter (11149):   PrimaryScrollController(ScrollController#f669f(no clients))
I/flutter (11149):   _ScaffoldScope
I/flutter (11149):   Scaffold-[LabeledGlobalKey<ScaffoldState>#98c98]
I/flutter (11149):   CameraExampleHome
I/flutter (11149):   Semantics(container: false, properties: SemanticsProperties, label: null, value: null, hint: null,
I/flutter (11149):   hintOverrides: null)
I/flutter (11149):   Builder
I/flutter (11149):   RepaintBoundary-[GlobalKey#dc660]
I/flutter (11149):   IgnorePointer(ignoring: false)
I/flutter (11149):   Stack(alignment: AlignmentDirectional.topStart, fit: passthrough, overflow: clip)
I/flutter (11149):   _CupertinoBackGestureDetector<dynamic>
I/flutter (11149):   DecoratedBox(bg: _CupertinoEdgeShadowDecoration(edgeGradient:
I/flutter (11149):   LinearGradient(AlignmentDirectional(0.9, 0.0), AlignmentDirectional.centerEnd, [Color(0x00000000),
I/flutter (11149):   Color(0x04000000), Color(0x12000000), Color(0x38000000)], [0.0, 0.3, 0.6, 1.0], TileMode.clamp)))
I/flutter (11149):   DecoratedBoxTransition(animation: AnimationController#a922d(⏭ 1.000; paused; for
I/flutter (11149):   CupertinoPageRoute<dynamic>(/))➩ProxyAnimation➩Cubic(0.35, 0.91, 0.33,
I/flutter (11149):   0.97)➩DecorationTween(_CupertinoEdgeShadowDecoration(edgeGradient: null) →
I/flutter (11149):   _CupertinoEdgeShadowDecoration(edgeGradient: LinearGradient(AlignmentDirectional(0.9, 0.0),
I/flutter (11149):   AlignmentDirectional.centerEnd, [Color(0x00000000), Color(0x04000000), Color(0x12000000),
I/flutter (11149):   Color(0x38000000)], [0.0, 0.3, 0.6, 1.0],
I/flutter (11149):   TileMode.clamp)))➩_CupertinoEdgeShadowDecoration(edgeGradient:
I/flutter (11149):   LinearGradient(AlignmentDirectional(0.9, 0.0), AlignmentDirectional.centerEnd, [Color(0x00000000),
I/flutter (11149):   Color(0x04000000), Color(0x12000000), Color(0x38000000)], [0.0, 0.3, 0.6, 1.0], TileMode.clamp)))
I/flutter (11149):   FractionalTranslation
I/flutter (11149):   SlideTransition(animation: AnimationController#a922d(⏭ 1.000; paused; for
I/flutter (11149):   CupertinoPageRoute<dynamic>(/))➩ProxyAnimation➩Cubic(0.35, 0.91, 0.33, 0.97)ₒₙ/Cubic(0.67, 0.03,
I/flutter (11149):   0.65, 0.09)➩Tween<Offset>(Offset(1.0, 0.0) → Offset(0.0, 0.0))➩Offset(0.0, 0.0))
I/flutter (11149):   FractionalTranslation
I/flutter (11149):   SlideTransition(animation: kAlwaysDismissedAnimation➩ProxyAnimation➩ProxyAnimation➩Cubic(0.35,
I/flutter (11149):   0.91, 0.33, 0.97)ₒₙ/Cubic(0.67, 0.03, 0.65, 0.09)➩Tween<Offset>(Offset(0.0, 0.0) → Offset(-0.3,
I/flutter (11149):   0.0))➩Offset(0.0, 0.0))
I/flutter (11149):   CupertinoPageTransition
I/flutter (11149):   AnimatedBuilder(animation: Listenable.merge([AnimationController#a922d(⏭ 1.000; paused; for
I/flutter (11149):   CupertinoPageRoute<dynamic>(/))➩ProxyAnimation,
I/flutter (11149):   kAlwaysDismissedAnimation➩ProxyAnimation➩ProxyAnimation]))
I/flutter (11149):   RepaintBoundary
I/flutter (11149):   _FocusScopeMarker
I/flutter (11149):   Semantics(container: false, properties: SemanticsProperties, label: null, value: null, hint: null,
I/flutter (11149):   hintOverrides: null)
I/flutter (11149):   FocusScope
I/flutter (11149):   PageStorage
I/flutter (11149):   Offstage(offstage: false)
I/flutter (11149):   _ModalScopeStatus(active)
I/flutter (11149):   _ModalScope<dynamic>-[LabeledGlobalKey<_ModalScopeState<dynamic>>#5f330]
I/flutter (11149):   _OverlayEntry-[LabeledGlobalKey<_OverlayEntryState>#58379]
I/flutter (11149):   Stack(alignment: AlignmentDirectional.topStart, fit: expand, overflow: clip)
I/flutter (11149):   _Theatre
I/flutter (11149):   Overlay-[LabeledGlobalKey<OverlayState>#0b5b0]
I/flutter (11149):   _FocusScopeMarker
I/flutter (11149):   Semantics(container: false, properties: SemanticsProperties, label: null, value: null, hint: null,
I/flutter (11149):   hintOverrides: null)
I/flutter (11149):   FocusScope
I/flutter (11149):   AbsorbPointer(absorbing: false)
I/flutter (11149):   Listener(listeners: [down, up, cancel], behavior: deferToChild)
I/flutter (11149):   Navigator-[GlobalObjectKey<NavigatorState> _WidgetsAppState#e1e75]
I/flutter (11149):   DefaultTextStyle(inherit: false, color: Color(0xff000000), family: .SF Pro Text, size: 17.0,
I/flutter (11149):   letterSpacing: -0.4, decoration: TextDecoration.none, softWrap: wrapping at box width, overflow:
I/flutter (11149):   clip)
I/flutter (11149):   Title(title: "Capital Fast", color: Color(0xff007aff))
I/flutter (11149):   Directionality(textDirection: ltr)
I/flutter (11149):   _LocalizationsScope-[GlobalKey#0292c]
I/flutter (11149):   Semantics(container: false, properties: SemanticsProperties, label: null, value: null, hint: null,
I/flutter (11149):   textDirection: ltr, hintOverrides: null)
I/flutter (11149):   Localizations(locale: en_US, delegates: [DefaultCupertinoLocalizations.delegate(en_US),
I/flutter (11149):   DefaultWidgetsLocalizations.delegate(en_US)])
I/flutter (11149):   MediaQuery(MediaQueryData(size: Size(360.0, 640.0), devicePixelRatio: 4.0, textScaleFactor: 1.0,
I/flutter (11149):   platformBrightness: Brightness.light, padding: EdgeInsets.zero, viewInsets: EdgeInsets.zero,
I/flutter (11149):   alwaysUse24HourFormat: true, accessibleNavigation: falsedisableAnimations: falseinvertColors:
I/flutter (11149):   falseboldText: false))
I/flutter (11149):   WidgetsApp-[GlobalObjectKey _CupertinoAppState#d945e]
I/flutter (11149):   IconTheme(IconThemeData#884be(color: MaterialColor(primary value: Color(0xff4caf50))))
I/flutter (11149):   _InheritedCupertinoTheme
I/flutter (11149):   CupertinoTheme
I/flutter (11149):   ScrollConfiguration(behavior: _AlwaysCupertinoScrollBehavior)
I/flutter (11149):   CupertinoApp
I/flutter (11149):   MyApp
I/flutter (11149):   [root]
I/flutter (11149): 
I/flutter (11149): When the exception was thrown, this was the stack:
I/flutter (11149): #0      debugCheckHasMaterialLocalizations.<anonymous closure> (package:flutter/src/material/debug.dart:124:7)
I/flutter (11149): #1      debugCheckHasMaterialLocalizations (package:flutter/src/material/debug.dart:127:4)
I/flutter (11149): #2      _AppBarState.build (package:flutter/src/material/app_bar.dart:409:12)
I/flutter (11149): #3      StatefulElement.build (package:flutter/src/widgets/framework.dart:3825:27)
I/flutter (11149): #4      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3739:15)
I/flutter (11149): #5      Element.rebuild (package:flutter/src/widgets/framework.dart:3565:5)
I/flutter (11149): #6      ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3722:5)
I/flutter (11149): #7      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3864:11)
I/flutter (11149): #8      ComponentElement.mount (package:flutter/src/widgets/framework.dart:3717:5)
I/flutter (11149): #9      Element.inflateWidget (package:flutter/src/widgets/framework.dart:2961:14)
I/flutter (11149): #10     Element.updateChild (package:flutter/src/widgets/framework.dart:2764:12)
I/flutter (11149): #11     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3750:16)
I/flutter (11149): #12     Element.rebuild (package:flutter/src/widgets/framework.dart:3565:5)
I/flutter (11149): #13     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3722:5)
I/flutter (11149): #14     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3717:5)
I/flutter (11149): #15     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2961:14)
I/flutter (11149): #16     Element.updateChild (package:flutter/src/widgets/framework.dart:2764:12)
I/flutter (11149): #17     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4876:14)
I/flutter (11149): #18     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2961:14)
I/flutter (11149): #19     Element.updateChild (package:flutter/src/widgets/framework.dart:2764:12)
I/flutter (11149): #20     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3750:16)
I/flutter (11149): #21     Element.rebuild (package:flutter/src/widgets/framework.dart:3565:5)
I/flutter (11149): #22     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3722:5)
I/flutter (11149): #23     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3717:5)
I/flutter (11149): #24     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2961:14)
I/flutter (11149): #25     Element.updateChild (package:flutter/src/widgets/framework.dart:2764:12)
I/flutter (11149): #26     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3750:16)
I/flutter (11149): #27     Element.rebuild (package:flutter/src/widgets/framework.dart:3565:5)
I/flutter (11149): #28     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3722:5)
I/flutter (11149): #29     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3717:5)
I/flutter (11149): #30     ParentDataElement.mount (package:flutter/src/widgets/framework.dart:4063:11)
I/flutter (11149): #31     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2961:14)
I/flutter (11149): #32     MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4982:32)
I/flutter (11149): #33     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2961:14)
I/flutter (11149): #34     Element.updateChild (package:flutter/src/widgets/framework.dart:2764:12)
I/flutter (11149): #35     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3750:16)
I/flutter (11149): #36     Element.rebuild (package:flutter/src/widgets/framework.dart:3565:5)
I/flutter (11149): #37     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3722:5)
I/flutter (11149): #38     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3864:11)
I/flutter (11149): #39     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3717:5)
I/flutter (11149): #40     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2961:14)
I/flutter (11149): #41     Element.updateChild (package:flutter/src/widgets/framework.dart:2764:12)
I/flutter (11149): #42     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3750:16)
I/flutter (11149): #43     Element.rebuild (package:flutter/src/widgets/framework.dart:3565:5)
I/flutter (11149): #44     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3722:5)
I/flutter (11149): #45     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3717:5)
I/flutter (11149): #46     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2961:14)
I/flutter (11149): #47     Element.updateChild (package:flutter/src/widgets/framework.dart:2764:12)
I/flutter (11149): #48     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3750:16)
I/flutter (11149): #49     Element.rebuild (package:flutter/src/widgets/framework.dart:3565:5)
I/flutter (11149): #50     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3722:5)
I/flutter (11149): #51     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3864:11)
I/flutter (11149): #52     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3717:5)
I/flutter (11149): #53     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2961:14)
I/flutter (11149): #54     Element.updateChild (package:flutter/src/widgets/framework.dart:2764:12)
I/flutter (11149): #55     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4876:14)
I/flutter (11149): #56     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2961:14)
I/flutter (11149): #57     Element.updateChild (package:flutter/src/widgets/framework.dart:2764:12)
I/flutter (11149): #58     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3750:16)
I/flutter (11149): #59     Element.rebuild (package:flutter/src/widgets/framework.dart:3565:5)
I/flutter (11149): #60     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3722:5)
I/flutter (11149): #61     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3717:5)
I/flutter (11149): #62     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2961:14)
I/flutter (11149): #63     Element.updateChild (package:flutter/src/widgets/framework.dart:2764:12)
I/flutter (11149): #64     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4876:14)
I/flutter (11149): #65     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2961:14)
```

**Flutter doctor -v**
```
flutter doctor -v
[✓] Flutter (Channel stable, v1.5.4-hotfix.2, on Mac OS X 10.14.4 18E226, locale tr-CY)
    • Flutter version 1.5.4-hotfix.2 at /users/niyazitoros/flutter
    • Framework revision 7a4c33425d (11 days ago), 2019-04-29 11:05:24 -0700
    • Engine revision 52c7a1e849
    • Dart version 2.3.0 (build 2.3.0-dev.0.5 a1668566e5)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/niyazitoros/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
    • All Android licenses accepted.

[!] iOS toolchain - develop for iOS devices (Xcode 10.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.2.1, Build version 10E1001
    • ios-deploy 2.0.0
    ✗ ios-deploy out of date (1.9.4 is required). To upgrade with Brew:
        brew upgrade ios-deploy
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.4)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 35.3.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

[✓] IntelliJ IDEA Community Edition (version 2019.1.2)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 35.3.3
    • Dart plugin version 191.7141.49

[✓] Connected device (1 available)
    • SM G935F • ce12160c0d86152e01 • android-arm64 • Android 8.0.0 (API 26)

! Doctor found issues in 1 category.

```

**Comment by NTMS2017** [comment]
Found the working solution for MaterialApp examples in here: https://flutter.dev/docs/cookbook/plugins/picture-using-camera

But I like to use it with CupertinoApp and having problem to integrate.
