### ISSUE TITLE
add2app crash java.lang.NullPointerException: Attempt to invoke virtual method 'io.flutter.embedding.engine.renderer.FlutterRenderer io.flutter.embedding.engine.FlutterEngine.getRenderer()' on a null object reference

### ISSUE THREAD

**Issue by daibao520** [flutter/flutter#32491]
(Android) I add flutter to my exist app. when the app enter background for awhile and enter foreground. I start flutter activity then call alipay(another app). crash.

```
E/AndroidRuntime: FATAL EXCEPTION: main   
    java.lang.NullPointerException: Attempt to invoke virtual method 'io.flutter.embedding.engine.renderer.FlutterRenderer io.flutter.embedding.engine.FlutterEngine.getRenderer()' on a null object reference
        at io.flutter.embedding.android.FlutterView.resetWillNotDraw(FlutterView.java:438)
        at io.flutter.embedding.android.FlutterView.access$000(FlutterView.java:59)
        at io.flutter.embedding.android.FlutterView$1.onAccessibilityChanged(FlutterView.java:96)
        at io.flutter.view.AccessibilityBridge$2.onAccessibilityStateChanged(AccessibilityBridge.java:285)
        at android.view.accessibility.AccessibilityManager.lambda$notifyAccessibilityStateChanged$0(AccessibilityManager.java:1157)
        at android.view.accessibility.-$$Lambda$AccessibilityManager$yzw5NYY7_MfAQ9gLy3mVllchaXo.run(Unknown Source:4)
        at android.os.Handler.handleCallback(Handler.java:907)
        at android.os.Handler.dispatchMessage(Handler.java:105)
        at android.os.Looper.loop(Looper.java:216)
        at android.app.ActivityThread.main(ActivityThread.java:7593)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:987)
```
If the app not enter background for awhile and back would not crash.

This is the activity start sequence
flutter activity -> native web activity -> pay activity -> call other app

**Comment by kangwang1988** [comment]
@daibao520 
Can you create a minimal demo project which can reproduce this issue? It would be much helpful.
Besides, paste 'flutter doctor -v' please.
