### ISSUE TITLE
AccessibilityBridge not release and make crash

### ISSUE THREAD

**Issue by daibao520** [flutter/flutter#32549]
When FlutterActivity destroy and FlutterView detachFromFlutterEngine  accessibilityBridge not call method release. so not remove listener from accessibilityManager.
When there is a accessibilityEvent sent. old listener be called. but no flutter engine attach  to it. then crash

```
E/AndroidRuntime: FATAL EXCEPTION: main   
    java.lang.NullPointerException: Attempt to invoke virtual method 'io.flutter.embedding.engine.renderer.FlutterRenderer io.flutter.embedding.engine.FlutterEngine.getRenderer()' on a null object reference
        at io.flutter.embedding.android.FlutterView.resetWillNotDraw(FlutterView.java:438)
        at io.flutter.embedding.android.FlutterView.access$000(FlutterView.java:59)
        at io.flutter.embedding.android.FlutterView$1.onAccessibilityChanged(FlutterView.java:96)
        at io.flutter.view.AccessibilityBridge$2.onAccessibilityStateChanged(AccessibilityBridge.java:285)
        at android.view.accessibility.AccessibilityManager.lambda$notifyAccessibilityStateChanged$0(AccessibilityManager.java:1157)
        at android.view.accessibility.-$$Lambda$AccessibilityManager$yzw5NYY7_MfAQ9gLy3mVllchaXo.run(Unknown Source:4)
        at android.os.Handler.handleCallback(Handler.java:907)
        at android.os.Handler.dispatchMessage(Handler.java:105)
        at android.os.Looper.loop(Looper.java:216)
        at android.app.ActivityThread.main(ActivityThread.java:7593)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:987)
```

My English is not good. I don't know if describe clearly.

**Comment by kangwang1988** [comment]
@daibao520 
Please paste `flutter doctor -v` and a minimal demo project which can help reproduce this issue?
Though I can understand your issue, however, a demo would make the issue more easy to diagnose.

**Comment by daibao520** [comment]
> @daibao520
> Please paste `flutter doctor -v` and a minimal demo project which can help reproduce this issue?
> Though I can understand your issue, however, a demo would make the issue more easy to diagnose.

```
PS D:\lb\flutter_module_liaobei> flutter doctor -v
[√] Flutter (Channel stable, v1.5.4-hotfix.2, on Microsoft Windows [Version 10.0.17763.475], locale zh-CN)
    • Flutter version 1.5.4-hotfix.2 at D:\Program Files\flutter
    • Framework revision 7a4c33425d (13 days ago), 2019-04-29 11:05:24 -0700
    • Engine revision 52c7a1e849
    • Dart version 2.3.0 (build 2.3.0-dev.0.5 a1668566e5)


[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at D:\AndroidSDK
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = D:\AndroidSDK
    • Java binary at: D:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)
    • All Android licenses accepted.

[√] Android Studio (version 3.3)
    • Android Studio at D:\Program Files\Android\Android Studio
    • Flutter plugin version 34.0.1
    • Dart plugin version 182.5215
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)

[!] IntelliJ IDEA Community Edition (version 2016.2)
    • IntelliJ at D:\Program Files (x86)\JetBrains\IntelliJ IDEA Community Edition 2016.2.4
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.dev/intellij-setup/#installing-the-plugins
    X This install is older than the minimum recommended version of 2017.1.0.
```

I add flutter to exist android app. The FlutterView is io.flutter.embedding.android.FlutterView not io.flutter.view.FlutterView.
I start a FlutterActivity from another activity. when FlutterActivity create i find the FlutterView register a 
AccessibilityStateChangeListener. when FlutterActivity close the listener not remove.

```
public void attachToFlutterEngine(@NonNull FlutterEngine flutterEngine) {
        Log.d("FlutterView", "attachToFlutterEngine()");
        if (this.isAttachedToFlutterEngine()) {
            if (flutterEngine == this.flutterEngine) {
                Log.d("FlutterView", "Already attached to this engine. Doing nothing.");
                return;
            }

            Log.d("FlutterView", "Currently attached to a different engine. Detaching.");
            this.detachFromFlutterEngine();
        }

        this.flutterEngine = flutterEngine;
        this.flutterEngine.getRenderer().attachToRenderSurface(this.renderSurface);
        this.textInputPlugin = new TextInputPlugin(this, this.flutterEngine.getDartExecutor());
        this.androidKeyProcessor = new AndroidKeyProcessor(this.flutterEngine.getKeyEventChannel(), this.textInputPlugin);
        this.androidTouchProcessor = new AndroidTouchProcessor(this.flutterEngine.getRenderer());
        this.accessibilityBridge = new AccessibilityBridge(this, flutterEngine.getAccessibilityChannel(), (AccessibilityManager)this.getContext().getSystemService("accessibility"), this.getContext().getContentResolver(), (PlatformViewsAccessibilityDelegate)null);
        this.accessibilityBridge.setOnAccessibilityChangeListener(this.onAccessibilityChangeListener);
        this.resetWillNotDraw(this.accessibilityBridge.isAccessibilityEnabled(), this.accessibilityBridge.isTouchExplorationEnabled());
        this.textInputPlugin.getInputMethodManager().restartInput(this);
        this.sendUserSettingsToFlutter();
        this.sendLocalesToFlutter(this.getResources().getConfiguration());
        this.sendViewportMetricsToFlutter();
    }
```
Here FlutterView register AccessibilityStateChangeListener 
```
this.accessibilityBridge = new AccessibilityBridge(this, flutterEngine.getAccessibilityChannel(), 
```

There is a method "release" in AccessibilityBridge use to remove the listener. but it is not called when FlutterActivity destroy
```
 public void release() {
        if (this.platformViewsAccessibilityDelegate != null) {
            this.platformViewsAccessibilityDelegate.detachAccessibiltyBridge();
        }

        this.setOnAccessibilityChangeListener((AccessibilityBridge.OnAccessibilityChangeListener)null);
        this.accessibilityManager.removeAccessibilityStateChangeListener(this.accessibilityStateChangeListener);
        if (VERSION.SDK_INT >= 19) {
            this.accessibilityManager.removeTouchExplorationStateChangeListener(this.touchExplorationStateChangeListener);
        }

        this.contentResolver.unregisterContentObserver(this.animationScaleObserver);
    }
```

when a event be catched by the listener. OnAccessibilityChangeListener be called. 
```
private FlutterView(@NonNull Context context, @Nullable AttributeSet attrs, @Nullable FlutterView.RenderMode renderMode, @Nullable FlutterView.TransparencyMode transparencyMode) {
        super(context, attrs);
        this.viewportMetrics = new ViewportMetrics();
        this.onAccessibilityChangeListener = new OnAccessibilityChangeListener() {
            public void onAccessibilityChanged(boolean isAccessibilityEnabled, boolean isTouchExplorationEnabled) {
                FlutterView.this.resetWillNotDraw(isAccessibilityEnabled, isTouchExplorationEnabled);
            }
        };
        this.renderMode = renderMode == null ? FlutterView.RenderMode.surface : renderMode;
        this.transparencyMode = transparencyMode != null ? transparencyMode : FlutterView.TransparencyMode.opaque;
        this.init();
    }
```

Then resetWillNotDraw be called.  the flutterEngine is null. crash
```
private void resetWillNotDraw(boolean isAccessibilityEnabled, boolean isTouchExplorationEnabled) {
        if (!this.flutterEngine.getRenderer().isSoftwareRenderingEnabled()) {
            this.setWillNotDraw(!isAccessibilityEnabled && !isTouchExplorationEnabled);
        } else {
            this.setWillNotDraw(false);
        }

    }
```

I don't know if you understand. demo may be later

**Comment by daibao520** [comment]
@kangwang1988 

```
PS D:\lb\flutter_module_liaobei> flutter doctor -v
[√] Flutter (Channel stable, v1.5.4-hotfix.2, on Microsoft Windows [Version 10.0.17763.475], locale zh-CN)
    • Flutter version 1.5.4-hotfix.2 at D:\Program Files\flutter
    • Framework revision 7a4c33425d (13 days ago), 2019-04-29 11:05:24 -0700
    • Engine revision 52c7a1e849
    • Dart version 2.3.0 (build 2.3.0-dev.0.5 a1668566e5)


[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at D:\AndroidSDK
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = D:\AndroidSDK
    • Java binary at: D:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)
    • All Android licenses accepted.

[√] Android Studio (version 3.3)
    • Android Studio at D:\Program Files\Android\Android Studio
    • Flutter plugin version 34.0.1
    • Dart plugin version 182.5215
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)

[!] IntelliJ IDEA Community Edition (version 2016.2)
    • IntelliJ at D:\Program Files (x86)\JetBrains\IntelliJ IDEA Community Edition 2016.2.4
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.dev/intellij-setup/#installing-the-plugins
    X This install is older than the minimum recommended version of 2017.1.0.
```

I add flutter to exist android app. The FlutterView is io.flutter.embedding.android.FlutterView not io.flutter.view.FlutterView.
I start a FlutterActivity from another activity. when FlutterActivity create i find the FlutterView register a 
AccessibilityStateChangeListener. when FlutterActivity close the listener not remove.

```
public void attachToFlutterEngine(@NonNull FlutterEngine flutterEngine) {
        Log.d("FlutterView", "attachToFlutterEngine()");
        if (this.isAttachedToFlutterEngine()) {
            if (flutterEngine == this.flutterEngine) {
                Log.d("FlutterView", "Already attached to this engine. Doing nothing.");
                return;
            }

            Log.d("FlutterView", "Currently attached to a different engine. Detaching.");
            this.detachFromFlutterEngine();
        }

        this.flutterEngine = flutterEngine;
        this.flutterEngine.getRenderer().attachToRenderSurface(this.renderSurface);
        this.textInputPlugin = new TextInputPlugin(this, this.flutterEngine.getDartExecutor());
        this.androidKeyProcessor = new AndroidKeyProcessor(this.flutterEngine.getKeyEventChannel(), this.textInputPlugin);
        this.androidTouchProcessor = new AndroidTouchProcessor(this.flutterEngine.getRenderer());
        this.accessibilityBridge = new AccessibilityBridge(this, flutterEngine.getAccessibilityChannel(), (AccessibilityManager)this.getContext().getSystemService("accessibility"), this.getContext().getContentResolver(), (PlatformViewsAccessibilityDelegate)null);
        this.accessibilityBridge.setOnAccessibilityChangeListener(this.onAccessibilityChangeListener);
        this.resetWillNotDraw(this.accessibilityBridge.isAccessibilityEnabled(), this.accessibilityBridge.isTouchExplorationEnabled());
        this.textInputPlugin.getInputMethodManager().restartInput(this);
        this.sendUserSettingsToFlutter();
        this.sendLocalesToFlutter(this.getResources().getConfiguration());
        this.sendViewportMetricsToFlutter();
    }
```
Here FlutterView register AccessibilityStateChangeListener 
```
this.accessibilityBridge = new AccessibilityBridge(this, flutterEngine.getAccessibilityChannel(), 
```

There is a method "release" in AccessibilityBridge use to remove the listener. but it is not called when FlutterActivity destroy
```
 public void release() {
        if (this.platformViewsAccessibilityDelegate != null) {
            this.platformViewsAccessibilityDelegate.detachAccessibiltyBridge();
        }

        this.setOnAccessibilityChangeListener((AccessibilityBridge.OnAccessibilityChangeListener)null);
        this.accessibilityManager.removeAccessibilityStateChangeListener(this.accessibilityStateChangeListener);
        if (VERSION.SDK_INT >= 19) {
            this.accessibilityManager.removeTouchExplorationStateChangeListener(this.touchExplorationStateChangeListener);
        }

        this.contentResolver.unregisterContentObserver(this.animationScaleObserver);
    }
```

when a event be catched by the listener. OnAccessibilityChangeListener be called. 
```
private FlutterView(@NonNull Context context, @Nullable AttributeSet attrs, @Nullable FlutterView.RenderMode renderMode, @Nullable FlutterView.TransparencyMode transparencyMode) {
        super(context, attrs);
        this.viewportMetrics = new ViewportMetrics();
        this.onAccessibilityChangeListener = new OnAccessibilityChangeListener() {
            public void onAccessibilityChanged(boolean isAccessibilityEnabled, boolean isTouchExplorationEnabled) {
                FlutterView.this.resetWillNotDraw(isAccessibilityEnabled, isTouchExplorationEnabled);
            }
        };
        this.renderMode = renderMode == null ? FlutterView.RenderMode.surface : renderMode;
        this.transparencyMode = transparencyMode != null ? transparencyMode : FlutterView.TransparencyMode.opaque;
        this.init();
    }
```

Then resetWillNotDraw be called.  the flutterEngine is null. crash
```
private void resetWillNotDraw(boolean isAccessibilityEnabled, boolean isTouchExplorationEnabled) {
        if (!this.flutterEngine.getRenderer().isSoftwareRenderingEnabled()) {
            this.setWillNotDraw(!isAccessibilityEnabled && !isTouchExplorationEnabled);
        } else {
            this.setWillNotDraw(false);
        }

    }
```

I don't know if you understand. demo may be later

**Comment by daibao520** [comment]
@kangwang1988 
你是中国的，太好了，我可以说中文了。
我是把flutter嵌入到我已有的工程里面，在里面做一些新功能，用单独一个FlutterActivity。关闭这个activity以后，一旦受到AccessibilityChange事件，没有释放掉的之前注册的那个接收函数被调用，就崩了。

resetWillNotDraw被调用，但是这个flutterEngine已经在detachFromFlutterEngine函数里被设置成null了

**Comment by daibao520** [comment]
Demo project too big
https://pan.baidu.com/s/1lvp7PnbJW1GrtiJAXkQZdQ 
code：zx6x 
@kangwang1988

**Comment by kangwang1988** [comment]
@daibao520 
I've run this demo project using latest master.
How can I reproduce the issue you reported, the 
```
E/AndroidRuntime: FATAL EXCEPTION: main   
    java.lang.NullPointerException: Attempt to invoke virtual method 'io.flutter.embedding.engine.renderer.FlutterRenderer io.flutter.embedding.engine.FlutterEngine.getRenderer()' on a null object reference
        at io.flutter.embedding.android.FlutterView.resetWillNotDraw(FlutterView.java:438)
        at io.flutter.embedding.android.FlutterView.access$000(FlutterView.java:59)
        at io.flutter.embedding.android.FlutterView$1.onAccessibilityChanged(FlutterView.java:96)
        at io.flutter.view.AccessibilityBridge$2.onAccessibilityStateChanged(AccessibilityBridge.java:285)
        at android.view.accessibility.AccessibilityManager.lambda$notifyAccessibilityStateChanged$0(AccessibilityManager.java:1157)
        at android.view.accessibility.-$$Lambda$AccessibilityManager$yzw5NYY7_MfAQ9gLy3mVllchaXo.run(Unknown Source:4)
        at android.os.Handler.handleCallback(Handler.java:907)
        at android.os.Handler.dispatchMessage(Handler.java:105)
        at android.os.Looper.loop(Looper.java:216)
        at android.app.ActivityThread.main(ActivityThread.java:7593)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:987)
```

**Comment by daibao520** [comment]
@kangwang1988 
1  click "START FLUTTER ACTIVITY"  button
2  click  "close activity" button
3  click "START FLUTTER ACTIVITY"  button
4  click "pay" button
use HUAWEI P30, Mate 10 test

Any time the activity contain io.flutter.embedding.android.FlutterView was destroyed and recreated app would crash

**Comment by hongyangAndroid** [comment]
@daibao520 

我也遇到了相同的问题，准备尝试手动remove一下，还没有线上测试，这边是否有更好的解决方案？

```
AccessibilityManager accessibilityManager = (AccessibilityManager)this.getContext().getSystemService(Context.ACCESSIBILITY_SERVICE);
            accessibilityManager.removeAccessibilityStateChangeListener(mFlutterView);
```

**Comment by daibao520** [comment]
@hongyangAndroid 我们的做法不比你的好，我们是把flutter嵌到一个table页里了，这样它就不销毁了

**Comment by xster** [comment]
Merging into #33173

**Comment by mindeng** [comment]
> @daibao520
> 
> 我也遇到了相同的问题，准备尝试手动remove一下，还没有线上测试，这边是否有更好的解决方案？
> 
> ```
> AccessibilityManager accessibilityManager = (AccessibilityManager)this.getContext().getSystemService(Context.ACCESSIBILITY_SERVICE);
>             accessibilityManager.removeAccessibilityStateChangeListener(mFlutterView);
> ```

我也遇到类似的问题，请问线上尝试的效果如何？是在 onDestroy() 回调里面 remove 的吗？
