### ISSUE TITLE
installed failed

### ISSUE THREAD

**Issue by 593361260** [flutter/flutter#32733]
Flutter crash report; please file at https://github.com/flutter/flutter/issues.

## command

flutter build bundle --suppress-analytics --target H:\future\flutter_list\lib\main.dart --filesystem-scheme org-dartlang-root --track-widget-creation --compilation-trace-file compilation.txt --depfile H:\future\flutter_list\build\app\intermediates\flutter\debug/snapshot_blob.bin.d --asset-dir H:\future\flutter_list\build\app\intermediates\flutter\debug/flutter_assets --debug

## exception

NoSuchMethodError: NoSuchMethodError: The getter 'length' was called on null.
Receiver: null
Tried calling: length

```
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:50:5)
#1      _Uri._uriEncode (dart:core-patch/uri_patch.dart:44:23)
#2      Uri.encodeFull (dart:core/uri.dart:1145:17)
#3      MappedListIterable.elementAt (dart:_internal/iterable.dart:414:29)
#4      MappedListIterable.elementAt (dart:_internal/iterable.dart:414:40)
#5      ListIterable.toList (dart:_internal/iterable.dart:219:19)
#6      FlutterManifest.assets (package:flutter_tools/src/flutter_manifest.dart:182:11)
#7      _parseAssets (package:flutter_tools/src/asset.dart:558:40)
#8      _ManifestAssetBundle.build (package:flutter_tools/src/asset.dart:142:53)
<asynchronous suspension>
#9      buildAssets (package:flutter_tools/src/bundle.dart:178:40)
<asynchronous suspension>
#10     build (package:flutter_tools/src/bundle.dart:147:36)
<asynchronous suspension>
#11     BuildBundleCommand.runCommand (package:flutter_tools/src/commands/build_bundle.dart:75:11)
<asynchronous suspension>
#12     FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:559:18)
<asynchronous suspension>
#13     FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:495:33)
<asynchronous suspension>
#14     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:142:29)
<asynchronous suspension>
#15     _rootRun (dart:async/zone.dart:1124:13)
#16     _CustomZone.run (dart:async/zone.dart:1021:19)
#17     _runZoned (dart:async/zone.dart:1516:10)
#18     runZoned (dart:async/zone.dart:1463:12)
#19     AppContext.run (package:flutter_tools/src/base/context.dart:141:18)
<asynchronous suspension>
#20     FlutterCommand.run (package:flutter_tools/src/runner/flutter_command.dart:486:20)
#21     CommandRunner.runCommand (package:args/command_runner.dart:196:27)
<asynchronous suspension>
#22     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:396:21)
<asynchronous suspension>
#23     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:142:29)
<asynchronous suspension>
#24     _rootRun (dart:async/zone.dart:1124:13)
#25     _CustomZone.run (dart:async/zone.dart:1021:19)
#26     _runZoned (dart:async/zone.dart:1516:10)
#27     runZoned (dart:async/zone.dart:1463:12)
#28     AppContext.run (package:flutter_tools/src/base/context.dart:141:18)
<asynchronous suspension>
#29     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:356:19)
<asynchronous suspension>
#30     CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:111:29)
#31     new Future.sync (dart:async/future.dart:224:31)
#32     CommandRunner.run (package:args/command_runner.dart:111:11)
#33     FlutterCommandRunner.run (package:flutter_tools/src/runner/flutter_command_runner.dart:242:18)
#34     run.<anonymous closure> (package:flutter_tools/runner.dart:60:20)
<asynchronous suspension>
#35     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:142:29)
<asynchronous suspension>
#36     _rootRun (dart:async/zone.dart:1124:13)
#37     _CustomZone.run (dart:async/zone.dart:1021:19)
#38     _runZoned (dart:async/zone.dart:1516:10)
#39     runZoned (dart:async/zone.dart:1463:12)
#40     AppContext.run (package:flutter_tools/src/base/context.dart:141:18)
<asynchronous suspension>
#41     runInContext (package:flutter_tools/src/context_runner.dart:50:24)
<asynchronous suspension>
#42     run (package:flutter_tools/runner.dart:51:10)
#43     main (package:flutter_tools/executable.dart:60:9)
<asynchronous suspension>
#44     main (file:///C:/b/s/w/ir/k/archive/flutter/packages/flutter_tools/bin/flutter_tools.dart:8:3)
#45     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:298:32)
#46     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:171:12)
```

## flutter doctor

```
[✓] Flutter (Channel stable, v1.5.4-hotfix.2, on Microsoft Windows [Version 10.0.17134.706], locale zh-CN)
    • Flutter version 1.5.4-hotfix.2 at H:\future\flutter
    • Framework revision 7a4c33425d (2 weeks ago), 2019-04-29 11:05:24 -0700
    • Engine revision 52c7a1e849
    • Dart version 2.3.0 (build 2.3.0-dev.0.5 a1668566e5)

[!] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at C:\dev\Sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: C:\dev\android-studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses

[✓] Android Studio (version 3.4)
    • Android Studio at C:\dev\android-studio
    • Flutter plugin version 35.3.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

[✓] IntelliJ IDEA Ultimate Edition (version 2018.1)
    • IntelliJ at G:\program Files\JetBrains\IntelliJ IDEA 2018.1.3
    • Flutter plugin version 31.3.1
    • Dart plugin version 181.4892.1

[✓] Connected device (3 available)
    • vivo X7                   • 53c94a39      • android-arm64 • Android 5.1.1 (API 22)
    • MI 5                      • d4100a8       • android-arm64 • Android 8.0.0 (API 26)
    • Android SDK built for x86 • emulator-5554 • android-x86   • Android P (API 27) (emulator)

! Doctor found issues in 1 category.
```

**Comment by BondarenkoStas** [comment]
@593361260 Did you manage to fix it? Please provide a code example that reproduces the issue.

**Comment by iapicca** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
  
Thanks for your contribution.
