### ISSUE TITLE
Flutter command error

### ISSUE THREAD

**Issue by JiaJiefei** [flutter/flutter#32805]
Flutter crash report; please file at https://github.com/flutter/flutter/issues.

## command

flutter doctor --android-licenses

## exception

ProcessException: ProcessException: 该版本的 %1 与你运行的 Windows 版本不兼容。请查看计算机的系统信息，然后联系软件发布者。

  Command: F:\AndroidStudio\studio\jre\bin\java.EXE -version

```
#0      _ProcessImpl._runAndWait (dart:io/runtime/binprocess_patch.dart:488:7)
#1      _runNonInteractiveProcessSync (dart:io/runtime/binprocess_patch.dart:633:18)
#2      Process.runSync (dart:io/runtime/binprocess_patch.dart:66:12)
#3      LocalProcessManager.runSync (package:process/src/interface/local_process_manager.dart:83:20)
#4      AndroidStudio._init (package:flutter_tools/src/android/android_studio.dart:264:51)
#5      new AndroidStudio (package:flutter_tools/src/android/android_studio.dart:36:5)
#6      new AndroidStudio.fromHomeDot (package:flutter_tools/src/android/android_studio.dart:73:14)
#7      AndroidStudio._allLinuxOrWindows (package:flutter_tools/src/android/android_studio.dart:215:54)
#8      AndroidStudio.allInstalled (package:flutter_tools/src/android/android_studio.dart:148:40)
#9      AndroidStudio.latestValid (package:flutter_tools/src/android/android_studio.dart:138:41)
#10     AppContext._generateIfNecessary.<anonymous closure> (package:flutter_tools/src/base/context.dart:99:41)
#11     __InternalLinkedHashMap&_HashVMBase&MapMixin&_LinkedHashMapMixin.putIfAbsent (dart:collection/runtime/libcompact_hash.dart:284:23)
#12     AppContext._generateIfNecessary (package:flutter_tools/src/base/context.dart:87:20)
#13     AppContext.[] (package:flutter_tools/src/base/context.dart:114:32)
#14     AppContext.[] (package:flutter_tools/src/base/context.dart:113:22)
#15     AppContext.[] (package:flutter_tools/src/base/context.dart:113:22)
#16     androidStudio (package:flutter_tools/src/android/android_studio.dart:16:43)
#17     javaPath (package:flutter_tools/src/android/android_studio.dart:30:24)
#18     AndroidSdk.findJavaBinary (package:flutter_tools/src/android/android_sdk.dart:449:24)
#19     AndroidSdk.sdkManagerEnv (package:flutter_tools/src/android/android_sdk.dart:484:33)
#20     AndroidSdk.sdkManagerVersion (package:flutter_tools/src/android/android_sdk.dart:497:109)
#21     AndroidLicenseValidator.runLicenseManager (package:flutter_tools/src/android/android_workflow.dart:277:64)
<asynchronous suspension>
#22     Doctor.diagnose (package:flutter_tools/src/doctor.dart:176:38)
<asynchronous suspension>
#23     DoctorCommand.runCommand (package:flutter_tools/src/commands/doctor.dart:48:39)
<asynchronous suspension>
#24     FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:401:18)
#25     _asyncThenWrapperHelper.<anonymous closure> (dart:async/runtime/libasync_patch.dart:77:64)
#26     _rootRunUnary (dart:async/zone.dart:1132:38)
#27     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#28     _FutureListener.handleValue (dart:async/future_impl.dart:129:18)
#29     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:642:45)
#30     Future._propagateToListeners (dart:async/future_impl.dart:671:32)
#31     Future._complete (dart:async/future_impl.dart:476:7)
#32     _SyncCompleter.complete (dart:async/future_impl.dart:51:12)
#33     _AsyncAwaitCompleter.complete.<anonymous closure> (dart:async/runtime/libasync_patch.dart:33:20)
#34     _rootRun (dart:async/zone.dart:1124:13)
#35     _CustomZone.run (dart:async/zone.dart:1021:19)
#36     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:947:23)
#37     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#38     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#39     _runPendingImmediateCallback (dart:isolate/runtime/libisolate_patch.dart:115:13)
#40     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:172:5)
```

## flutter doctor

```
encountered exception: ProcessException: 该版本的 %1 与你运行的 Windows 版本不兼容。请查看计算机的系统信息，然后联系软件发布者。

  Command: F:\AndroidStudio\studio\jre\bin\java.EXE -version

#0      _ProcessImpl._runAndWait (dart:io/runtime/binprocess_patch.dart:488:7)
#1      _runNonInteractiveProcessSync (dart:io/runtime/binprocess_patch.dart:633:18)
#2      Process.runSync (dart:io/runtime/binprocess_patch.dart:66:12)
#3      LocalProcessManager.runSync (package:process/src/interface/local_process_manager.dart:83:20)
#4      AndroidStudio._init (package:flutter_tools/src/android/android_studio.dart:264:51)
#5      new AndroidStudio (package:flutter_tools/src/android/android_studio.dart:36:5)
#6      new AndroidStudio.fromHomeDot (package:flutter_tools/src/android/android_studio.dart:73:14)
#7      AndroidStudio._allLinuxOrWindows (package:flutter_tools/src/android/android_studio.dart:215:54)
#8      AndroidStudio.allInstalled (package:flutter_tools/src/android/android_studio.dart:148:40)
#9      AndroidStudioValidator.allValidators (package:flutter_tools/src/android/android_studio_validator.dart:20:55)
#10     _DefaultDoctorValidatorsProvider.validators (package:flutter_tools/src/doctor.dart:60:51)
#11     Doctor.validators (package:flutter_tools/src/doctor.dart:103:46)
#12     Doctor.startValidatorTasks (package:flutter_tools/src/doctor.dart:110:39)
#13     Doctor.diagnose (package:flutter_tools/src/doctor.dart:184:41)
<asynchronous suspension>
#14     _doctorText.<anonymous closure> (package:flutter_tools/runner.dart:188:26)
#15     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:142:29)
<asynchronous suspension>
#16     _rootRun (dart:async/zone.dart:1124:13)
#17     _CustomZone.run (dart:async/zone.dart:1021:19)
#18     _runZoned (dart:async/zone.dart:1516:10)
#19     runZoned (dart:async/zone.dart:1463:12)
#20     AppContext.run (package:flutter_tools/src/base/context.dart:141:18)
<asynchronous suspension>
#21     _doctorText (package:flutter_tools/runner.dart:187:19)
<asynchronous suspension>
#22     _createLocalCrashReport (package:flutter_tools/runner.dart:165:32)
<asynchronous suspension>
#23     _handleToolError (package:flutter_tools/runner.dart:120:33)
<asynchronous suspension>
#24     run.<anonymous closure> (package:flutter_tools/runner.dart:64:20)
<asynchronous suspension>
#25     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:142:29)
<asynchronous suspension>
#26     _rootRun (dart:async/zone.dart:1124:13)
#27     _CustomZone.run (dart:async/zone.dart:1021:19)
#28     _runZoned (dart:async/zone.dart:1516:10)
#29     runZoned (dart:async/zone.dart:1463:12)
#30     AppContext.run (package:flutter_tools/src/base/context.dart:141:18)
<asynchronous suspension>
#31     runInContext (package:flutter_tools/src/context_runner.dart:43:24)
<asynchronous suspension>
#32     run (package:flutter_tools/runner.dart:51:10)
#33     main (package:flutter_tools/executable.dart:51:9)
<asynchronous suspension>
#34     main (file:///E:/b/build/slave/Windows_Flutter_Packaging/build/archive/flutter/packages/flutter_tools/bin/flutter_tools.dart:8:3)
#35     _startIsolate.<anonymous closure> (dart:isolate/runtime/libisolate_patch.dart:287:32)
#36     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:171:12)
```

**Comment by BondarenkoStas** [comment]
@JiaJiefei did you manage to fix it? Is it Windows 7 x86?

**Comment by iapicca** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
  
Thanks for your contribution.
