### ISSUE TITLE
 Failed assertion: line 770: 'node._needsPaint' is not true.

### ISSUE THREAD

**Issue by eseidelGoogle** [flutter/flutter#3283]
https://github.com/flutter/flutter/compare/master...eseidelGoogle:perf_overlay_gallery?expand=1
Attempting to add a perf overlay toggle to the drawer in the material gallery app.

FYI @Hixie 

```
I/flutter : ══╡ EXCEPTION CAUGHT BY SCHEDULER LIBRARY ╞═════════════════════════════════════════════════════════
I/flutter : The following exception was raised during a scheduler callback:
I/flutter : 'package:flutter/src/rendering/object.dart': Failed assertion: line 770: 'node._needsPaint' is not
I/flutter : true.
I/flutter : Either the assertion indicates an error in the framework itself, or we should provide substantially
I/flutter : more information in this error message to help you determine and fix the underlying cause.
I/flutter : In either case, please report this assertion by filing a bug on GitHub:
I/flutter :   https://github.com/flutter/flutter/issues/new
I/flutter : Stack trace:
I/flutter : #0      _AssertionError._throwNew (dart:core-patch/errors_patch.dart:27)
I/flutter : #1      PipelineOwner.flushPaint (package:flutter/src/rendering/object.dart:770)
I/flutter : #2      BindingBase&Scheduler&Gesturer&Services&Renderer.beginFrame (package:flutter/src/rendering/binding.dart:90)
I/flutter : #3      WidgetFlutterBinding.beginFrame (package:flutter/src/widgets/binding.dart:103)
I/flutter : #4      BindingBase&Scheduler&Gesturer&Services&Renderer._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:82)
I/flutter : #5      BindingBase&Scheduler.invokeFrameCallback (package:flutter/src/scheduler/scheduler.dart:270)
I/flutter : #6      BindingBase&Scheduler.handleBeginFrame (package:flutter/src/scheduler/scheduler.dart:247)
I/flutter : #7      _beginFrame (file:///b/build/slave/Linux_Engine/build/src/out/android_Release/gen/sky/bindings/hooks.dart:48)
I/flutter : ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
```

**Comment by eseidelGoogle** [comment]
I hit this again just now with:
https://github.com/flutter/flutter/compare/master...eseidelGoogle:overlay_atom?expand=1

**Comment by Hixie** [comment]
I looked at the code, but there's nothing obvious. This assert should definitely never fire the way the code is written as far as I can tell. I couldn't reproduce though. Can you elaborate on what the steps to reproduce are? I tried taking your code but I wasn't sure what to do then.
