### ISSUE TITLE
flutter run -v  getting oops 

### ISSUE THREAD

**Issue by enasellithy** [flutter/flutter#32861]
```
[  +24 ms] executing: [/home/dev/flutter/] git rev-parse --abbrev-ref --symbolic
@{u}
[  +33 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/stable
[        ] executing: [/home/dev/flutter/] git rev-parse --abbrev-ref HEAD
[   +7 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] stable
[   +2 ms] executing: [/home/dev/flutter/] git ls-remote --get-url origin
[   +7 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[        ] executing: [/home/dev/flutter/] git log -n 1 --pretty=format:%H
[   +8 ms] Exit code 0 from: git log -n 1 --pretty=format:%H
[        ] 8661d8aecd626f7f57ccbcb735553edc05a2e713
[        ] executing: [/home/dev/flutter/] git log -n 1 --pretty=format:%ar
[   +9 ms] Exit code 0 from: git log -n 1 --pretty=format:%ar
[        ] 3 months ago
[        ] executing: [/home/dev/flutter/] git describe --match v*.*.*
--first-parent --long --tags
[  +10 ms] Exit code 0 from: git describe --match v*.*.* --first-parent --long
--tags
[   +1 ms] v1.2.1-0-g8661d8aec
[  +92 ms] executing: /home/dev/Android/Sdk/platform-tools/adb devices -l
[   +8 ms] Exit code 0 from: /home/dev/Android/Sdk/platform-tools/adb devices -l
[        ] List of devices attached
           420026259a557200       device usb:2-1 product:coreprimeve3gxx
           model:SM_G361H device:coreprimeve3g transport_id:3
[ +235 ms] /home/dev/Android/Sdk/platform-tools/adb -s 420026259a557200 shell
getprop
[  +65 ms] ro.hardware = sc8830
[        ] ro.build.characteristics = default
[ +678 ms] Launching lib/main.dart on SM G361H in debug mode...
[  +21 ms] Initializing gradle...
[  +11 ms] Using gradle from /home/dev/apps/myapp/android/gradlew.
[  +63 ms] executing: /home/dev/apps/myapp/android/gradlew -v
[+15339 ms] Downloading
https://services.gradle.org/distributions/gradle-4.10.2-all.zip


                     Exception in thread "main" java.net.UnknownHostException:
                     services.gradle.org
                     	at
                     	java.net.AbstractPlainSocketImpl.connect(AbstractPlainSock
                     	etImpl.java:184)
                     	at
                     	java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
                     	at java.net.Socket.connect(Socket.java:589)
                     	at
                     	sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:
                     	673)
                     	at
                     	sun.security.ssl.BaseSSLSocketImpl.connect(BaseSSLSocketIm
                     	pl.java:173)
                     	at sun.net.NetworkClient.doConnect(NetworkClient.java:180)
                     	at
                     	sun.net.www.http.HttpClient.openServer(HttpClient.java:432
                     	)
                     	at
                     	sun.net.www.http.HttpClient.openServer(HttpClient.java:527
                     	)
                     	at
                     	sun.net.www.protocol.https.HttpsClient.<init>(HttpsClient.
                     	java:264)
                     	at
                     	sun.net.www.protocol.https.HttpsClient.New(HttpsClient.jav
                     	a:367)
                     	at
                     	sun.net.www.protocol.https.AbstractDelegateHttpsURLConnect
                     	ion.getNewHttpClient(AbstractDelegateHttpsURLConnection.ja
                     	va:200)
                     	at
                     	sun.net.www.protocol.http.HttpURLConnection.plainConnect0(
                     	HttpURLConnection.java:1157)
                     	at
                     	sun.net.www.protocol.http.HttpURLConnection.plainConnect(H
                     	ttpURLConnection.java:1032)
                     	at
                     	sun.net.www.protocol.https.AbstractDelegateHttpsURLConnect
                     	ion.connect(AbstractDelegateHttpsURLConnection.java:177)
                     	at
                     	sun.net.www.protocol.http.HttpURLConnection.getInputStream
                     	0(HttpURLConnection.java:1546)
                     	at
                     	sun.net.www.protocol.http.HttpURLConnection.getInputStream
                     	(HttpURLConnection.java:1474)
                     	at
                     	sun.net.www.protocol.https.HttpsURLConnectionImpl.getInput
                     	Stream(HttpsURLConnectionImpl.java:254)
                     	at
                     	org.gradle.wrapper.Download.downloadInternal(Download.java
                     	:58)
                     	at org.gradle.wrapper.Download.download(Download.java:44)
                     	at org.gradle.wrapper.Install$1.call(Install.java:61)
                     	at org.gradle.wrapper.Install$1.call(Install.java:48)
                     	at
                     	org.gradle.wrapper.ExclusiveFileAccessManager.access(Exclu
                     	siveFileAccessManager.java:65)
                     	at org.gradle.wrapper.Install.createDist(Install.java:48)
                     	at
                     	org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor
                     	.java:128)
                     	at
                     	org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMai
                     	n.java:61)
[  +14 ms] "flutter run" took 16,475ms.
[        ] "flutter run" took 16,475ms.

Oops; flutter has exited unexpectedly.
Sending crash report to Google.
Failed to send crash report due to a network error: SocketException: Failed host
lookup: 'clients2.google.com' (OS Error: No address associated with hostname,
errno = -5)
```

![Screenshot from 2019-05-17 02-41-48](https://user-images.githubusercontent.com/17440978/57897548-8c206f80-7855-11e9-8044-5d22361408a9.png)
![Uploading Screenshot from 2019-05-17 02-50-11.png…]()

**Comment by BondarenkoStas** [comment]
@enasellithy is it still an issue with current flutter stable? Please paste your graddle-wrapper.properties. Could you update gradle version to the latest 5.6.2?

**Comment by iapicca** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
  
Thanks for your contribution.
