### ISSUE TITLE
iOS 12.3 iPhone X can't run in profile version but debug & release is ok

### ISSUE THREAD

**Issue by adamjuhasz** [flutter/flutter#32912]
Flutter crashing (but not the app, it remains on the screen and responsive) when trying to run the profile version on an iPhone X while a profile version runs successfully on an Android device (Essential PH 1). On the iPhone, both `release` and  `debug` versions run just fine.

| Component | Version |
|---|---|
| iPhone | iOS 12.3 |
| Flutter | 1.5.4-hotfix.2 |
| Essential | Android 10 |

## Steps to Reproduce

Try to `Debug -> Start Debugging` from VS Code or run `flutter run --profile` from the command line.

## Logs

Flutter crash report; please file at https://github.com/flutter/flutter/issues.

### command

```
$ flutter run --profile -d 341faf193f0c04bb3f5f29d2d208ff78efc346a5
Launching lib/main.dart on Adam’s iPhone X in profile mode...
Automatically signing iOS for device deployment using specified development team in Xcode project: 2ZG8V3KUG2
Running Xcode build...                                                  
 ├─Building Dart code...                                    21.5s
 ├─Generating dSYM file...                                   1.0s
 ├─Stripping debug symbols...                                0.7s
 ├─Assembling Flutter resources...                           0.9s
 └─Compiling, linking and signing...                         8.0s
Xcode build done.                                           33.6s
flutter: RouteSettings("/", null)                                       
Installing and launching...                                         8.8s

Oops; flutter has exited unexpectedly.
Sending crash report to Google.
Crash report sent (report ID: d8304edd0595f238)
 
Crash report written to /Users/ajuhasz/tgthr/monorepo/alfie/flutter_01.log;
please let us know at https://github.com/flutter/flutter/issues.
```

### exception

HttpException: HttpException: , uri = http://127.0.0.1:1027/PScoHbFm7Ys=/ws

```
#0      _defaultOpenChannel (package:flutter_tools/src/vmservice.dart:89:16)
<asynchronous suspension>
#1      VMService.connect (package:flutter_tools/src/vmservice.dart:255:61)
<asynchronous suspension>
#2      FlutterDevice._connect (package:flutter_tools/src/resident_runner.dart:128:44)
<asynchronous suspension>
#3      ResidentRunner.connectToServiceProtocol (package:flutter_tools/src/resident_runner.dart:793:20)
<asynchronous suspension>
#4      ColdRunner.run (package:flutter_tools/src/run_cold.dart:73:15)
<asynchronous suspension>
#5      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:428:37)
<asynchronous suspension>
#6      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:559:18)
#7      _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:77:64)
#8      _rootRunUnary (dart:async/zone.dart:1132:38)
#9      _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#10     _FutureListener.handleValue (dart:async/future_impl.dart:126:18)
#11     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:639:45)
#12     Future._propagateToListeners (dart:async/future_impl.dart:668:32)
#13     Future._complete (dart:async/future_impl.dart:473:7)
#14     _SyncCompleter.complete (dart:async/future_impl.dart:51:12)
#15     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:28:18)
#16     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:294:13)
#17     RunCommand.usageValues (package:flutter_tools/src/commands/run.dart)
#18     _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:77:64)
#19     _rootRunUnary (dart:async/zone.dart:1132:38)
#20     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#21     _FutureListener.handleValue (dart:async/future_impl.dart:126:18)
#22     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:639:45)
#23     Future._propagateToListeners (dart:async/future_impl.dart:668:32)
#24     Future._complete (dart:async/future_impl.dart:473:7)
#25     _SyncCompleter.complete (dart:async/future_impl.dart:51:12)
#26     _AsyncAwaitCompleter.complete.<anonymous closure> (dart:async-patch/async_patch.dart:33:20)
#27     _rootRun (dart:async/zone.dart:1124:13)
#28     _CustomZone.run (dart:async/zone.dart:1021:19)
#29     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:947:23)
#30     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#31     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#32     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:115:13)
#33     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:5)
```

### flutter doctor
```
$ flutter doctor -v
[✓] Flutter (Channel stable, v1.5.4-hotfix.2, on Mac OS X 10.14.4 18E226, locale en-US)
    • Flutter version 1.5.4-hotfix.2 at /Users/ajuhasz/flutter
    • Framework revision 7a4c33425d (3 weeks ago), 2019-04-29 11:05:24 -0700
    • Engine revision 52c7a1e849
    • Dart version 2.3.0 (build 2.3.0-dev.0.5 a1668566e5)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/ajuhasz/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.2.1, Build version 10E1001
    • ios-deploy 1.9.4
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 32.0.1
    • Dart plugin version 182.5215
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)

[✓] IntelliJ IDEA Ultimate Edition (version 2018.1.3)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 31.3.1
    • Dart plugin version 181.4892.1

[✓] VS Code (version 1.34.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.0.2

[✓] Connected device (3 available)
    • PH 1            • PM1LHMA851702444                         • android-arm64 • Android 10 (API 28)
    • Adam’s iPhone X • 341faf193f0c04bb3f5f29d2d208ff78efc346a5 • ios           • iOS 12.3
    • iPhone Xʀ       • DFA633E4-14F2-44AF-ABBB-E88626529FB3     • ios           • com.apple.CoreSimulator.SimRuntime.iOS-12-2 (simulator)

• No issues found!
```

## Release mode
```
$ flutter run --release -d 341faf193f0c04bb3f5f29d2d208ff78efc346a5
Launching lib/main.dart on Adam’s iPhone X in release mode...
Automatically signing iOS for device deployment using specified development team in Xcode project: 2ZG8V3KUG2
Running Xcode build...                                                  
 ├─Building Dart code...                                     3.7s
 ├─Generating dSYM file...                                   0.2s
 ├─Stripping debug symbols...                                0.0s
 ├─Assembling Flutter resources...                           1.5s
 └─Compiling, linking and signing...                         1.8s
Xcode build done.                                            8.6s
Installing and launching...                                         9.9s

To quit, press "q".
flutter: RouteSettings("/", null)
```

## Essential PH 1 
```
$ flutter run --profile -d PM1LHMA851702444
Initializing gradle...                                              1.5s
Resolving dependencies...                                          10.3s
Launching lib/main.dart on PH 1 in profile mode...
Running Gradle task 'assembleProfile'...                                
Running Gradle task 'assembleProfile'... Done                      29.6s
Built build/app/outputs/apk/profile/app-profile.apk (7.8MB).
Installing build/app/outputs/apk/app.apk...                         2.9s

An Observatory debugger and profiler on PH 1 is available at http://127.0.0.1:63169/SDEIp5COPRA=/
For a more detailed help message, press "h". To quit, press "q".
I/flutter (18875): RouteSettings("/", null)
D/OpenGLRenderer(18875): Swap behavior 2
W/Gralloc3(18875): mapper 3.x is not supported
 
```

**Comment by smitthakkar1** [comment]
facing the same issue
