### ISSUE TITLE
 'YamlMap' is not a subtype of type 'String' in type cast

### ISSUE THREAD

**Issue by therichiekumar** [flutter/flutter#32958]
Flutter crash report; please file at https://github.com/flutter/flutter/issues.

## command

flutter build bundle --suppress-analytics --target lib/main.dart --compilation-trace-file compilation.txt --target-platform android-arm --precompiled --asset-dir C:\Users\Ashwani Kumar\Desktop\fluttercourse\ecom\build\app\intermediates\flutter\release/flutter_assets --release

## exception

_CastError: type 'YamlMap' is not a subtype of type 'String' in type cast

```
#0      _CastListBase.[] (dart:_internal/cast.dart:99:46)
#1      __CastListBase&_CastIterableBase&ListMixin.elementAt (dart:collection/list.dart:55:33)
#2      MappedListIterable.elementAt (dart:_internal/iterable.dart:414:40)
#3      MappedListIterable.elementAt (dart:_internal/iterable.dart:414:40)
#4      ListIterable.toList (dart:_internal/iterable.dart:219:19)
#5      FlutterManifest.assets (package:flutter_tools/src/flutter_manifest.dart:182:11)
#6      _parseAssets (package:flutter_tools/src/asset.dart:558:40)
#7      _ManifestAssetBundle.build (package:flutter_tools/src/asset.dart:142:53)
<asynchronous suspension>
#8      buildAssets (package:flutter_tools/src/bundle.dart:178:40)
<asynchronous suspension>
#9      build (package:flutter_tools/src/bundle.dart:147:36)
<asynchronous suspension>
#10     BuildBundleCommand.runCommand (package:flutter_tools/src/commands/build_bundle.dart:75:11)
<asynchronous suspension>
#11     FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:559:18)
<asynchronous suspension>
#12     FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:495:33)
<asynchronous suspension>
#13     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:142:29)
<asynchronous suspension>
#14     _rootRun (dart:async/zone.dart:1124:13)
#15     _CustomZone.run (dart:async/zone.dart:1021:19)
#16     _runZoned (dart:async/zone.dart:1516:10)
#17     runZoned (dart:async/zone.dart:1463:12)
#18     AppContext.run (package:flutter_tools/src/base/context.dart:141:18)
<asynchronous suspension>
#19     FlutterCommand.run (package:flutter_tools/src/runner/flutter_command.dart:486:20)
#20     CommandRunner.runCommand (package:args/command_runner.dart:196:27)
<asynchronous suspension>
#21     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:396:21)
<asynchronous suspension>
#22     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:142:29)
<asynchronous suspension>
#23     _rootRun (dart:async/zone.dart:1124:13)
#24     _CustomZone.run (dart:async/zone.dart:1021:19)
#25     _runZoned (dart:async/zone.dart:1516:10)
#26     runZoned (dart:async/zone.dart:1463:12)
#27     AppContext.run (package:flutter_tools/src/base/context.dart:141:18)
<asynchronous suspension>
#28     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:356:19)
<asynchronous suspension>
#29     CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:111:29)
#30     new Future.sync (dart:async/future.dart:224:31)
#31     CommandRunner.run (package:args/command_runner.dart:111:11)
#32     FlutterCommandRunner.run (package:flutter_tools/src/runner/flutter_command_runner.dart:242:18)
#33     run.<anonymous closure> (package:flutter_tools/runner.dart:60:20)
<asynchronous suspension>
#34     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:142:29)
<asynchronous suspension>
#35     _rootRun (dart:async/zone.dart:1124:13)
#36     _CustomZone.run (dart:async/zone.dart:1021:19)
#37     _runZoned (dart:async/zone.dart:1516:10)
#38     runZoned (dart:async/zone.dart:1463:12)
#39     AppContext.run (package:flutter_tools/src/base/context.dart:141:18)
<asynchronous suspension>
#40     runInContext (package:flutter_tools/src/context_runner.dart:50:24)
<asynchronous suspension>
#41     run (package:flutter_tools/runner.dart:51:10)
#42     main (package:flutter_tools/executable.dart:60:9)
<asynchronous suspension>
#43     main (file:///C:/b/s/w/ir/k/archive/flutter/packages/flutter_tools/bin/flutter_tools.dart:8:3)
#44     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:298:32)
#45     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:171:12)
```

## flutter doctor

```
[✓] Flutter (Channel stable, v1.5.4-hotfix.2, on Microsoft Windows [Version 10.0.17134.706], locale en-IN)
    • Flutter version 1.5.4-hotfix.2 at C:\Users\Ashwani Kumar\flutter
    • Framework revision 7a4c33425d (3 weeks ago), 2019-04-29 11:05:24 -0700
    • Engine revision 52c7a1e849
    • Dart version 2.3.0 (build 2.3.0-dev.0.5 a1668566e5)

[!] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at C:\Users\Ashwani Kumar\AppData\Local\Android\Sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-Q, build-tools 28.0.3
    • ANDROID_HOME = C:\Users\Ashwani Kumar\AppData\Local\Android\Sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
    ✗ Android license status unknown.
      Try re-installing or updating your Android SDK Manager.
      See https://developer.android.com/studio/#downloads or visit https://flutter.dev/setup/#android-setup for detailed instructions.

[✓] Android Studio (version 3.4)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 35.3.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

[✓] VS Code, 64-bit edition (version 1.33.1)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Flutter extension version 3.0.2

[!] Connected device
    ! No devices available

! Doctor found issues in 2 categories.
```

**Comment by rakeshlanjewarwork** [comment]
Please post the code to reproduce the error !!

**Comment by harshapulikollu** [comment]
I had same issue when I upgraded flutter and `fonts` in `pubspec.yaml` file as fonts were defined under any parent instead of fonts parent.
Check your `pubspec.yaml` if you made any recent changes try to revert or check for as any typo or indentation.I think this issue is being caused that file.

**Comment by majakozar** [comment]
I got the same error in my application and after some time I notice that the issue is pubspec.yaml.

I accidentally add additional - in assets so instead of  "- assets/logo.png" I got "- - assets/logo.png".

My suggestion is to double check spelling in yaml file.

**Comment by therichiekumar** [comment]
Thanks @majakozar
