### ISSUE TITLE
[android_alarm_manager] Regression in android_alarm_manager

### ISSUE THREAD

**Issue by tensor-programming** [flutter/flutter#32976]
When using the dev channel of flutter, (`v1.6.0`)  using the `android_alarm_manager: ^0.4.1+6` causes the application to crash at the android level.  This maybe related to #32657

Stack trace received included these main lines:
```
An error occurred while executing doInBackground()

Caused by: java.lang.RuntimeException: Methods marked with @UiThread 
must be executed on the main thread. Current thread: AsyncTask #3
```

Moving back to flutter stable channel (`v1.5.4-hotfix.2`) resolved this issue with the alarm manager giving me the expected behavior.

**Comment by arlucio** [comment]
Also when using dev channel, got this error while trying to run a transaction using FirebaseDatabase plugin, just like this guy: https://stackoverflow.com/questions/56209091/flutter-firebasedatabase-run-transaction-chash

`User code called from the Firebase Database runloop threw an exception:
java.lang.RuntimeException: Methods marked with @UiThread must be executed on the main thread. Current thread: FirebaseDatabaseWorker
	at io.flutter.embedding.engine.FlutterJNI.ensureRunningOnMainThread(FlutterJNI.java:605)
	at io.flutter.embedding.engine.FlutterJNI.dispatchPlatformMessage(FlutterJNI.java:515)
at io.flutter.embedding.engine.dart.DartMessenger.send(DartMessenger.java:76)
at io.flutter.embedding.engine.dart.DartExecutor.send(DartExecutor.java:166)
at io.flutter.view.FlutterNativeView.send(FlutterNativeView.java:155)
at io.flutter.plugin.common.MethodChannel.invokeMethod(MethodChannel.java:98)
at io.flutter.plugins.firebase.database.FirebaseDatabasePlugin$1.doTransaction(FirebaseDatabasePlugin.java:345)
at com.google.firebase.database.core.Repo.startTransaction(com.google.firebase:firebase-database@@17.0.0:831)
at com.google.firebase.database.DatabaseReference$4.run(com.google.firebase:firebase-database@@17.0.0:511)
`

Going back to stable channel fixed it, and it worked normally without errors.
