### ISSUE TITLE
App with WebView crashes when put into background 

### ISSUE THREAD

**Issue by mathisgerdes** [flutter/flutter#32984]
## Steps to Reproduce
Using the latest stable version of flutter (v1.5.4-hotfix.2) and the webview developers preview (webview_flutter 0.3.7+1), the following app crashes when put into the background (home button, or app overview):
```
import 'package:flutter/material.dart';
import 'package:webview_flutter/webview_flutter.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      home: MyHomePage(),
    );
  }
}

class MyHomePage extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('Flutter Demo Page'),
      ),
      body: const WebView(
        initialUrl: 'https://google.com',
      ),
    );
  }
}
```
It works fine with flutter version v1.2.1 and the same version of webview.

## Logs
```
[+2175 ms] D/AndroidRuntime(21113): Shutting down VM
[   +2 ms] E/AndroidRuntime(21113): FATAL EXCEPTION: main
[        ] E/AndroidRuntime(21113): Process: org.example.flutter_app, PID: 21113
[        ] E/AndroidRuntime(21113): java.lang.NullPointerException: Attempt to invoke virtual method 'long
android.view.accessibility.AccessibilityNodeInfo.getSourceNodeId()' on a null object reference
[   +1 ms] E/AndroidRuntime(21113): 	at android.view.View.populateVirtualStructure(View.java:8499)
[        ] E/AndroidRuntime(21113): 	at android.view.View.populateVirtualStructure(View.java:8580)
[        ] E/AndroidRuntime(21113): 	at android.view.View.populateVirtualStructure(View.java:8580)
[        ] E/AndroidRuntime(21113): 	at android.view.View.populateVirtualStructure(View.java:8580)
[        ] E/AndroidRuntime(21113): 	at android.view.View.populateVirtualStructure(View.java:8580)
[        ] E/AndroidRuntime(21113): 	at android.view.View.onProvideVirtualStructureCompat(View.java:7998)
[        ] E/AndroidRuntime(21113): 	at android.view.View.onProvideVirtualStructure(View.java:7979)
[        ] E/AndroidRuntime(21113): 	at android.view.View.dispatchProvideStructureForAssistOrAutofill(View.java:8645)
[        ] E/AndroidRuntime(21113): 	at android.view.View.dispatchProvideStructure(View.java:8592)
[        ] E/AndroidRuntime(21113): 	at android.view.ViewGroup.dispatchProvideStructure(ViewGroup.java:3546)
[        ] E/AndroidRuntime(21113): 	at android.view.ViewGroup.dispatchProvideStructure(ViewGroup.java:3546)
[        ] E/AndroidRuntime(21113): 	at android.view.ViewGroup.dispatchProvideStructure(ViewGroup.java:3546)
[        ] E/AndroidRuntime(21113): 	at android.app.assist.AssistStructure$WindowNode.<init>(AssistStructure.java:524)
[        ] E/AndroidRuntime(21113): 	at android.app.assist.AssistStructure.<init>(AssistStructure.java:2052)
[        ] E/AndroidRuntime(21113): 	at android.app.ActivityThread.handleRequestAssistContextExtras(ActivityThread.java:3215)
[        ] E/AndroidRuntime(21113): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1772)
[        ] E/AndroidRuntime(21113): 	at android.os.Handler.dispatchMessage(Handler.java:106)
[        ] E/AndroidRuntime(21113): 	at android.os.Looper.loop(Looper.java:193)
[        ] E/AndroidRuntime(21113): 	at android.app.ActivityThread.main(ActivityThread.java:6718)
[        ] E/AndroidRuntime(21113): 	at java.lang.reflect.Method.invoke(Native Method)
[        ] E/AndroidRuntime(21113): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
[        ] E/AndroidRuntime(21113): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
[        ] I/Process (21113): Sending signal. PID: 21113 SIG: 9
[  +42 ms] Service protocol connection closed.
[   +2 ms] Lost connection to device.
[   +9 ms] DevFS: Deleting filesystem on the device (file:///data/user/0/org.examle.flutter_app/code_cache/flutter_appDJHJRW/flutter_app/)
[   +1 ms] Sending to VM service: _deleteDevFS({fsName: flutter_app})
[ +257 ms] Ignored error while cleaning up DevFS: TimeoutException after 0:00:00.250000: Future not completed
```

# flutter analyze
```
No issues found! (ran in 2.3s)
```

# Flutter doctor -v
```
[✓] Flutter (Channel stable, v1.5.4-hotfix.2, on Linux, locale en_US.UTF-8)
    • Flutter version 1.5.4-hotfix.2 at /home/username/software/flutter
    • Framework revision 7a4c33425d (3 weeks ago), 2019-04-29 11:05:24 -0700
    • Engine revision 52c7a1e849
    • Dart version 2.3.0 (build 2.3.0-dev.0.5 a1668566e5)

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /home/username/Android/Sdk
    • Android NDK location not configured (optional; useful for native profiling
      support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /home/username/software/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_152-release-1343-b16-5323222)
    • All Android licenses accepted.

[✓] Android Studio (version 3.4)
    • Android Studio at /home/username/software/android-studio
    • Flutter plugin version 35.3.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build
      1.8.0_152-release-1343-b16-5323222)

[!] IntelliJ IDEA Community Edition (version 2018.2)
    • IntelliJ at /home/username/software/intellij
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    • Dart plugin version 182.5215
    • For information about installing plugins, see
      https://flutter.dev/intellij-setup/#installing-the-plugins

[✓] Connected device (1 available)
    • Pixel 2 • FA7AK1A03482 • android-arm64 • Android 9 (API 28)
```

**Comment by mtallenca** [comment]
I'm seeing lots of these crashes as well - esp on Galaxy S10/Note 9

**Comment by rohansohonee** [comment]
Samsung Galaxy S8 is crashing. Any fix?

**Comment by Vanethos** [comment]
I'm also seeing this issue, but with an Android native view, not webview

**Comment by shinayser** [comment]
I am seeing this issue, but instead of WebView I am using GoogeMaps widget.
Probably this is an issue with the Platform Views.

**Comment by jyp334** [comment]
Please let me know if you have the latest solution, because my application also has this problem. My flutter version is 1.7.6,webview_flutter is 0.39+1.

**Comment by LempereurBenjamin** [comment]
Same issue with GoogeMaps widget on a OnePlus 6.
Flutter version is Channel stable, v1.5.4-hotfix.2, on Linux, locale en_US.UTF-8.
google_maps_flutter version is 0.5.19.

**Comment by thedejifab** [comment]
Any fix here yet?

**Comment by PingShen** [comment]
any fix??????????????
@shinayser

**Comment by shinayser** [comment]
> any fix??????????????
> @shinayser

Nope. No fix. What I've done is removing the widget form the widget tree right before going to the background.
I am using `WidgetsBindingObserver`for that and doing the removal on the  `didChangeAppLifecycleState` method

**Comment by iapicca** [comment]
Hi all
are you still experiencing the same issue with the latest stable version 
and the latest webview_flutter `^0.3.18+1`?

To upgrade flutter you please run 
`flutter channel stable`
`flutter upgrade --force`
`flutter clean`
`flutter pub cache repair`

If the issue persist please provide your updated 
`flutter doctor -v` and `flutter run --verbose`
together with a a minimal code sample to reproduce the problem
thank you

**Comment by dnfield** [comment]
I'm closing this since it's had no activity in a while and has the waiting label.  I believe the bot is just backlogged and missing a bunch of these.  Please feel free to add more details if you want this re-opened.

**Comment by furyou81** [comment]
have you tried this?

Seems that adding this permission in AndroidManifest.xml is also solving the issue

<uses-permission android:name="android.permission.WAKE_LOCK"/>

https://github.com/flutter/flutter/issues/49912
https://github.com/pichillilorenzo/flutter_inappwebview/issues/373

**Comment by iapicca** [comment]
Could everyone who still has this problem please file a new issue with the exact description of what happens, logs and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
