### ISSUE TITLE
How to show web page using either WebView evaluateJavascript or loadUrl?

### ISSUE THREAD

**Issue by NTMS2017** [flutter/flutter#32980]
Can load url when passing a javascript function.
First I try to load web page as; _myController.evaluateJavascript and nothings happened.
Secondly I try to load web page as; _myController.loadUrl and got an error.

How to show web page using either WebView evaluateJavascript or loadUrl?

**Error:**
```
flutter: Page finished loading: https://stackoverflow.com/
[VERBOSE-2:ui_dart_state.cc(148)] Unhandled Exception: PlatformException(loadUrl_failed, Failed parsing the URL, Request was: '{
    headers = "<null>";
    url = "javascript:(function() { var head = document.getElementsByClassName('header')[0].style.display='none'; })()";
}')
#0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:564:7)
#1      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:302:33)
<asynchronous suspension>
#2      WebViewController.loadUrl (package:webview_flutter/webview_flutter.dart:426:21)
<asynchronous suspension>
```

**First:**
```
 onPageFinished: (url){
                print('Page finished loading: $url');
                _myController.evaluateJavascript("document.getElementsByClassName('header')[0].style.display='none'");
                setState(() {
                  _loadedPage = true;
                });
              },
```

**Second:**
 ```
onPageFinished: (url){
                print('Page finished loading: $url');
                _myController.loadUrl("javascript:(function() { " +
                    "var head = document.getElementsByClassName('header')[0].style.display='none'; " +
                    "})()");

                setState(() {
                  _loadedPage = true;
                });
              },
```

**Comment by jun-hak** [comment]
Is it solved? I have same problem. loadUrl is not working in ios.

**Comment by FTK09** [comment]
me too.

**Comment by rudratibicle** [comment]
me too
