### ISSUE TITLE
Tab controller exception caught by animation library

### ISSUE THREAD

**Issue by abdulRehmann** [flutter/flutter#32990]
## Steps to Reproduce

1. Go to kitchen screen.
2. Click [[Cakes Tab]] and swipe cake items.
3. Tap [[Dishes Tab]] when you are at the last item of cakes. Animation length > 1 error occurs.
4. Tap [[Cakes Tab]] and you neither able to swipe items nor change them.

/******************************* Gif ***********************************************/
/**********************************************************************************/
![20190519150455480x960](https://user-images.githubusercontent.com/26773947/57980709-18928400-7a48-11e9-8c47-807e5b049c06.gif)

/******************************* Source Code Link *******************************/
/*********************************************************************************/
https://gist.github.com/abdulRehmann/3b355b501305f7ab926d97101812d93f

## Logs

```
2019-05-19 15:19:20.775 23704-23704/com.example.nested_tab_bar I/zygote64: Late-enabling -Xcheck:jni
2019-05-19 15:19:21.090 23704-23745/com.example.nested_tab_bar I/ResourceExtractor: Found extracted resources res_timestamp-1-1558260759708
2019-05-19 15:19:21.090 23704-23745/com.example.nested_tab_bar I/ResourceExtractor: Resource version mismatch res_timestamp-1-1558261159237
2019-05-19 15:19:21.137 23704-23704/com.example.nested_tab_bar D/PhoneWindow: windowLightStatusBar : false, disable View.SYSTEM_UI_FLAG_LIGHT_STATUS_BAR
2019-05-19 15:19:21.710 23704-23745/com.example.nested_tab_bar I/ResourceExtractor: Extracted baseline resource assets/flutter_assets/kernel_blob.bin
2019-05-19 15:19:21.713 23704-23745/com.example.nested_tab_bar I/ResourceExtractor: Extracted baseline resource assets/flutter_assets/vm_snapshot_data
2019-05-19 15:19:21.839 23704-23745/com.example.nested_tab_bar I/ResourceExtractor: Extracted baseline resource assets/flutter_assets/isolate_snapshot_data
2019-05-19 15:19:21.871 23704-23704/com.example.nested_tab_bar I/Adreno: QUALCOMM build                   : 14c0496, Ida6448821d
    Build Date                       : 01/08/18
    OpenGL ES Shader Compiler Version: EV031.22.00.01
    Local Branch                     : 
    Remote Branch                    : refs/tags/AU_LINUX_ANDROID_LA.UM.6.5.R1.08.00.00.312.043
    Remote Branch                    : NONE
    Reconstruct Branch               : NOTHING
2019-05-19 15:19:21.872 23704-23704/com.example.nested_tab_bar I/vndksupport: sphal namespace is not configured for this process. Loading /vendor/lib64/hw/gralloc.msm8996.so from the current namespace instead.
2019-05-19 15:19:21.876 23704-23704/com.example.nested_tab_bar I/Adreno: PFP: 0x005ff087, ME: 0x005ff063
2019-05-19 15:19:22.048 23704-23785/com.example.nested_tab_bar D/OpenGLRenderer: HWUI GL Pipeline
2019-05-19 15:19:22.081 23704-23704/com.example.nested_tab_bar D/BezellessGripSuppressionFilter: getdisplaysize, x : 1440 y : 2880
2019-05-19 15:19:22.122 23704-23785/com.example.nested_tab_bar I/OpenGLRenderer: Initialized EGL, version 1.4
2019-05-19 15:19:22.122 23704-23785/com.example.nested_tab_bar D/OpenGLRenderer: Swap behavior 2
2019-05-19 15:19:22.380 23704-23785/com.example.nested_tab_bar I/vndksupport: sphal namespace is not configured for this process. Loading /vendor/lib64/hw/gralloc.msm8996.so from the current namespace instead.
2019-05-19 15:19:22.396 23704-23704/com.example.nested_tab_bar I/Timeline: Timeline: Activity_idle id: android.os.BinderProxy@273444a time:126582999
2019-05-19 15:19:22.433 23704-23780/com.example.nested_tab_bar I/flutter: Observatory listening on http://127.0.0.1:48281/9Iyf5n4iJlw=/
2019-05-19 15:19:23.491 23704-23773/com.example.nested_tab_bar I/flutter: initState = KitchenTabs
2019-05-19 15:19:23.741 23704-23773/com.example.nested_tab_bar I/flutter: initState = KitchenBodyState
2019-05-19 15:19:24.278 23704-23773/com.example.nested_tab_bar I/flutter: Dish Tabs
2019-05-19 15:21:16.884 23704-23704/com.example.nested_tab_bar I/ViewRootImpl: ViewRoot's Touch Event : ACTION_DOWN
2019-05-19 15:21:16.927 23704-23704/com.example.nested_tab_bar I/ViewRootImpl: ViewRoot's Touch Event : ACTION_UP
2019-05-19 15:21:17.221 23704-23773/com.example.nested_tab_bar I/flutter: *************************************************
2019-05-19 15:21:17.221 23704-23773/com.example.nested_tab_bar I/flutter: Parent Tab: 1
2019-05-19 15:21:17.221 23704-23773/com.example.nested_tab_bar I/flutter: *************************************************
2019-05-19 15:21:17.223 23704-23704/com.example.nested_tab_bar I/AudioManagerEx: AudioManagerEx created
2019-05-19 15:21:17.416 23704-23773/com.example.nested_tab_bar I/flutter: Deal Tabs
2019-05-19 15:21:17.416 23704-23773/com.example.nested_tab_bar I/flutter: Deal Tabs
2019-05-19 15:21:18.006 23704-23704/com.example.nested_tab_bar I/ViewRootImpl: ViewRoot's Touch Event : ACTION_DOWN
2019-05-19 15:21:18.124 23704-23704/com.example.nested_tab_bar I/ViewRootImpl: ViewRoot's Touch Event : ACTION_UP
2019-05-19 15:21:19.219 23704-23704/com.example.nested_tab_bar I/ViewRootImpl: ViewRoot's Touch Event : ACTION_DOWN
2019-05-19 15:21:19.299 23704-23704/com.example.nested_tab_bar I/ViewRootImpl: ViewRoot's Touch Event : ACTION_UP
2019-05-19 15:21:19.321 23704-23773/com.example.nested_tab_bar I/flutter: *************************************************
2019-05-19 15:21:19.321 23704-23773/com.example.nested_tab_bar I/flutter: Parent Tab: 0
2019-05-19 15:21:19.321 23704-23773/com.example.nested_tab_bar I/flutter: *************************************************
2019-05-19 15:21:19.325 23704-23773/com.example.nested_tab_bar I/flutter: cakesController.index: 0
2019-05-19 15:21:19.325 23704-23773/com.example.nested_tab_bar I/flutter: cakesController.previousIndex: 1
2019-05-19 15:21:19.327 23704-23773/com.example.nested_tab_bar I/flutter: cakesController.index: 0
2019-05-19 15:21:19.327 23704-23773/com.example.nested_tab_bar I/flutter: cakesController.previousIndex: 0
2019-05-19 15:21:19.446 23704-23773/com.example.nested_tab_bar I/flutter: Dish Tabs
2019-05-19 15:21:19.539 23704-23773/com.example.nested_tab_bar I/flutter: ══╡ EXCEPTION CAUGHT BY ANIMATION LIBRARY ╞═════════════════════════════════════════════════════════
2019-05-19 15:21:19.579 23704-23773/com.example.nested_tab_bar I/flutter: The following assertion was thrown while notifying listeners for AnimationController:
2019-05-19 15:21:19.579 23704-23773/com.example.nested_tab_bar I/flutter: 'package:flutter/src/material/tab_controller.dart': Failed assertion: line 180 pos 12: 'length > 1':
2019-05-19 15:21:19.579 23704-23773/com.example.nested_tab_bar I/flutter: is not true.
2019-05-19 15:21:19.594 23704-23773/com.example.nested_tab_bar I/flutter: Either the assertion indicates an error in the framework itself, or we should provide substantially
2019-05-19 15:21:19.594 23704-23773/com.example.nested_tab_bar I/flutter: more information in this error message to help you determine and fix the underlying cause.
2019-05-19 15:21:19.594 23704-23773/com.example.nested_tab_bar I/flutter: In either case, please report this assertion by filing a bug on GitHub:
2019-05-19 15:21:19.595 23704-23773/com.example.nested_tab_bar I/flutter:   https://github.com/flutter/flutter/issues/new?template=BUG.md
2019-05-19 15:21:19.595 23704-23773/com.example.nested_tab_bar I/flutter: When the exception was thrown, this was the stack:
2019-05-19 15:21:19.619 23704-23773/com.example.nested_tab_bar I/flutter: #2      TabController.offset= (package:flutter/src/material/tab_controller.dart:180:12)
2019-05-19 15:21:19.619 23704-23773/com.example.nested_tab_bar I/flutter: #3      _TabBarViewState._handleScrollNotification (package:flutter/src/material/tabs.dart:1249:19)
2019-05-19 15:21:19.619 23704-23773/com.example.nested_tab_bar I/flutter: #4      NotificationListener._dispatch (package:flutter/src/widgets/notification_listener.dart:127:27)
2019-05-19 15:21:19.619 23704-23773/com.example.nested_tab_bar I/flutter: #5      Notification.visitAncestor (package:flutter/src/widgets/notification_listener.dart:45:20)
2019-05-19 15:21:19.620 23704-23773/com.example.nested_tab_bar I/flutter: #6      _ScrollNotification&LayoutChangedNotification&ViewportNotificationMixin.visitAncestor (package:flutter/src/widgets/scroll_notification.dart:31:18)
2019-05-19 15:21:19.620 23704-23773/com.example.nested_tab_bar I/flutter: #7      Element.visitAncestorElements (package:flutter/src/widgets/framework.dart:3355:39)
2019-05-19 15:21:19.620 23704-23773/com.example.nested_tab_bar I/flutter: #8      Notification.dispatch (package:flutter/src/widgets/notification_listener.dart:61:13)
2019-05-19 15:21:19.620 23704-23773/com.example.nested_tab_bar I/flutter: #9      ScrollActivity.dispatchScrollUpdateNotification (package:flutter/src/widgets/scroll_activity.dart:96:92)
2019-05-19 15:21:19.620 23704-23773/com.example.nested_tab_bar I/flutter: #10     ScrollPosition.didUpdateScrollPositionBy (package:flutter/src/widgets/scroll_position.dart:658:14)
2019-05-19 15:21:19.620 23704-23773/com.example.nested_tab_bar I/flutter: #11     ScrollPosition.setPixels (package:flutter/src/widgets/scroll_position.dart:219:9)
2019-05-19 15:21:19.620 23704-23773/com.example.nested_tab_bar I/flutter: #12     ScrollPositionWithSingleContext.setPixels (package:flutter/src/widgets/scroll_position_with_single_context.dart:84:18)
2019-05-19 15:21:19.620 23704-23773/com.example.nested_tab_bar I/flutter: #13     DrivenScrollActivity._tick (package:flutter/src/widgets/scroll_activity.dart:629:18)
2019-05-19 15:21:19.620 23704-23773/com.example.nested_tab_bar I/flutter: #14     _AnimationController&Animation&AnimationEagerListenerMixin&AnimationLocalListenersMixin.notifyListeners (package:flutter/src/animation/listener_helpers.dart:126:19)
2019-05-19 15:21:19.621 23704-23773/com.example.nested_tab_bar I/flutter: #15     AnimationController._tick (package:flutter/src/animation/animation_controller.dart:750:5)
2019-05-19 15:21:19.621 23704-23773/com.example.nested_tab_bar I/flutter: #16     Ticker._tick (package:flutter/src/scheduler/ticker.dart:228:5)
2019-05-19 15:21:19.621 23704-23773/com.example.nested_tab_bar I/flutter: #17     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1012:15)
2019-05-19 15:21:19.621 23704-23773/com.example.nested_tab_bar I/flutter: #18     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.handleBeginFrame.<anonymous closure> (package:flutter/src/scheduler/binding.dart:928:11)
2019-05-19 15:21:19.621 23704-23773/com.example.nested_tab_bar I/flutter: #19     __InternalLinkedHashMap&_HashVMBase&MapMixin&_LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:367:8)
2019-05-19 15:21:19.621 23704-23773/com.example.nested_tab_bar I/flutter: #20     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.handleBeginFrame (package:flutter/src/scheduler/binding.dart:926:17)
2019-05-19 15:21:19.621 23704-23773/com.example.nested_tab_bar I/flutter: #21     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._handleBeginFrame (package:flutter/src/scheduler/binding.dart:856:5)
2019-05-19 15:21:19.621 23704-23773/com.example.nested_tab_bar I/flutter: #25     _invoke1 (dart:ui/hooks.dart:233:10)
2019-05-19 15:21:19.621 23704-23773/com.example.nested_tab_bar I/flutter: #26     _beginFrame (dart:ui/hooks.dart:172:3)
2019-05-19 15:21:19.622 23704-23773/com.example.nested_tab_bar I/flutter: (elided 5 frames from class _AssertionError and package dart:async)
2019-05-19 15:21:19.629 23704-23773/com.example.nested_tab_bar I/flutter: The AnimationController notifying listeners was:
2019-05-19 15:21:19.629 23704-23773/com.example.nested_tab_bar I/flutter:   AnimationController#c91da(▶ 63.551; for DrivenScrollActivity)
2019-05-19 15:21:19.629 23704-23773/com.example.nested_tab_bar I/flutter: ════════════════════════════════════════════════════════════════════════════════════════════════════
```

```
D:\Z\Foody\foody\nested_tab_bar>flutter analyze
Analyzing nested_tab_bar...
No issues found! (ran in 13.3s)
```

```
D:\Z\Foody\foody\nested_tab_bar>flutter doctor -v
[√] Flutter (Channel stable, v1.5.4-hotfix.2, on Microsoft Windows [Version 10.0.17763.503], locale en-GB)
    • Flutter version 1.5.4-hotfix.2 at D:\Local DIsk C\Flutter\flutter
    • Framework revision 7a4c33425d (3 weeks ago), 2019-04-29 11:05:24 -0700
    • Engine revision 52c7a1e849
    • Dart version 2.3.0 (build 2.3.0-dev.0.5 a1668566e5)


[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at C:\Users\Abdul_Rehman\AppData\Local\Android\Sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = C:\Users\Abdul_Rehman\AppData\Local\Android\Sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
    • All Android licenses accepted.

[√] Android Studio (version 3.4)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 35.3.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

[!] IntelliJ IDEA Community Edition (version 2017.3)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2017.3.4
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.dev/intellij-setup/#installing-the-plugins

[√] VS Code (version 1.33.1)
    • VS Code at C:\Users\Abdul_Rehman\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.0.2

[√] Connected device (1 available)
    • VS988 • VS988b5b39e94 • android-arm64 • Android 8.0.0 (API 26)

! Doctor found issues in 1 category.
```

**Comment by TahaTesser** [comment]
Hi @abdulRehmann 
Trying to reproduce the exception and no issues on latest dev channel
```
[✓] Flutter (Channel dev, v1.18.0, on Mac OS X 10.15.4 19E266, locale en-GB)
    • Flutter version 1.18.0 at /Users/taha/Code/flutter_dev
    • Framework revision 14f3a36aba (3 days ago), 2020-04-03 17:06:01 -0700
    • Engine revision 09bc1fc45e
    • Dart version 2.8.0 (build 2.8.0-dev.20.0 e736495eb7)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/taha/Code/sdk
    • Platform android-29, build-tools 29.0.3
    • ANDROID_HOME = /Users/taha/Code/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.4)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.4, Build version 11E146
    • CocoaPods version 1.9.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 45.0.1
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build
      1.8.0_212-release-1586-b4-5784211)

[✓] VS Code (version 1.43.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.9.0

[✓] Connected device (4 available)
    • SM M305F   • 32003c30dc19668f • android-arm64  • Android 10 (API 29)
    • macOS      • macOS            • darwin-x64     • Mac OS X 10.15.4 19E266
    • Chrome     • chrome           • web-javascript • Google Chrome
      80.0.3987.149
    • Web Server • web-server       • web-javascript • Flutter Tools

• No issues found!

```

if you're still experiencing this problem, please create a new issue and provide the information required in
the template.
Thank you
