### ISSUE TITLE
My application was running successfuly and now it dosen't (main.dart not implemented), (CreateProcessW 193)

### ISSUE THREAD

**Issue by HudaAlmowafy** [flutter/flutter#33023]
## Steps to Reproduce

1. when running any flutter application (worked before).
2. The main.dart not implemented error appears.
3. and when I write flutter run command in terminal, the CreateProcessW 193 error appears.

## Logs

Flutter crash report; please file at https://github.com/flutter/flutter/issues.

## command

flutter run --verbose

## exception

ProcessException: ProcessException: %1 is not a valid Win32 application.

  Command: C:\Users\Huda Almowafy\IdeaProjects\Project\mes\android\gradlew.bat -v

```
#0      runAsync (package:flutter_tools/src/base/process.dart:232:33)
<asynchronous suspension>
#1      runCheckedAsync (package:flutter_tools/src/base/process.dart:248:34)
<asynchronous suspension>
#2      _initializeGradle (package:flutter_tools/src/android/gradle.dart:225:9)
<asynchronous suspension>
#3      _ensureGradle (package:flutter_tools/src/android/gradle.dart:206:37)
<asynchronous suspension>
#4      _readGradleProject (package:flutter_tools/src/android/gradle.dart:134:31)
<asynchronous suspension>
#5      _gradleProject (package:flutter_tools/src/android/gradle.dart:111:34)
<asynchronous suspension>
#6      getGradleAppOut (package:flutter_tools/src/android/gradle.dart:105:29)
<asynchronous suspension>
#7      AndroidApk.fromAndroidProject (package:flutter_tools/src/application_package.dart:154:23)
<asynchronous suspension>
#8      ApplicationPackageFactory.getPackageForPlatform (package:flutter_tools/src/application_package.dart:46:32)
<asynchronous suspension>
#9      FlutterDevice.runHot (package:flutter_tools/src/resident_runner.dart:345:56)
<asynchronous suspension>
#10     HotRunner.run (package:flutter_tools/src/run_hot.dart:253:39)
<asynchronous suspension>
#11     RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:428:37)
<asynchronous suspension>
#12     FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:559:18)
#13     _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:77:64)
#14     _rootRunUnary (dart:async/zone.dart:1132:38)
#15     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#16     _FutureListener.handleValue (dart:async/future_impl.dart:126:18)
#17     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:639:45)
#18     Future._propagateToListeners (dart:async/future_impl.dart:668:32)
#19     Future._complete (dart:async/future_impl.dart:473:7)
#20     _SyncCompleter.complete (dart:async/future_impl.dart:51:12)
#21     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:28:18)
#22     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:294:13)
#23     RunCommand.usageValues (package:flutter_tools/src/commands/run.dart)
#24     _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:77:64)
#25     _rootRunUnary (dart:async/zone.dart:1132:38)
#26     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#27     _FutureListener.handleValue (dart:async/future_impl.dart:126:18)
#28     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:639:45)
#29     Future._propagateToListeners (dart:async/future_impl.dart:668:32)
#30     Future._complete (dart:async/future_impl.dart:473:7)
#31     _SyncCompleter.complete (dart:async/future_impl.dart:51:12)
#32     _AsyncAwaitCompleter.complete.<anonymous closure> (dart:async-patch/async_patch.dart:33:20)
#33     _rootRun (dart:async/zone.dart:1124:13)
#34     _CustomZone.run (dart:async/zone.dart:1021:19)
#35     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:947:23)
#36     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#37     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#38     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:115:13)
#39     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:5)
```

## flutter doctor

```
[32m[✓][39m Flutter (Channel stable, v1.5.4-hotfix.2, on Microsoft Windows [Version 10.0.17134.648], locale en-US)
    [32m•[39m Flutter version 1.5.4-hotfix.2 at C:\src\flutter
    [32m•[39m Framework revision 7a4c33425d (3 weeks ago), 2019-04-29 11:05:24 -0700
    [32m•[39m Engine revision 52c7a1e849
    [32m•[39m Dart version 2.3.0 (build 2.3.0-dev.0.5 a1668566e5)

[32m[✓][39m Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    [32m•[39m Android SDK at E:\Android
    [32m•[39m Android NDK location not configured (optional; useful for native profiling support)
    [32m•[39m Platform android-28, build-tools 28.0.3
    [32m•[39m ANDROID_HOME = E:\Android
    [32m•[39m Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    [32m•[39m Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b01)
    [32m•[39m All Android licenses accepted.

[32m[✓][39m Android Studio (version 3.0)
    [32m•[39m Android Studio at C:\Program Files\Android\Android Studio
    [32m•[39m Flutter plugin version 23.2.1
    [32m•[39m Dart plugin version 171.4424
    [32m•[39m Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b01)

[32m[✓][39m IntelliJ IDEA Community Edition (version 2019.1)
    [32m•[39m IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2018.3.5
    [32m•[39m Flutter plugin version 35.3.3
    [32m•[39m Dart plugin version 191.7141.49

[32m[✓][39m VS Code, 32-bit edition (version 1.32.1)
    [32m•[39m VS Code at C:\Program Files (x86)\Microsoft VS Code
    [32m•[39m Flutter extension version 2.24.0

[32m[✓][39m Connected device (1 available)
    [32m•[39m WAS LX1A • 2XJDU17714002440 • android-arm64 • Android 8.0.0 (API 26)

[32m•[39m No issues found!
```

```
```

```
```

```
```

**Comment by HudaAlmowafy** [comment]
Everything was happened when I added firebase_database and firebase_auth packages to pubspec.yaml and work with it.

**Comment by blasten** [comment]
This is fixed on master.

**Comment by kroikie** [comment]
@HudaAlmowafy

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/368. Any further collaboration will be done there.
