### ISSUE TITLE
NoSuchMethodError: The getter 'executable' was called on null.

### ISSUE THREAD

**Issue by kasnet** [flutter/flutter#33027]
Flutter crash report; please file at https://github.com/flutter/flutter/issues.

## command

flutter run

## exception

NoSuchMethodError: NoSuchMethodError: The getter 'executable' was called on null.
Receiver: null
Tried calling: executable

```
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:50:5)
#1      BuildableMacOSApp.executable (package:flutter_tools/src/macos/application_package.dart:142:28)
#2      MacOSDevice.stopApp (package:flutter_tools/src/macos/macos_device.dart:110:28)
<asynchronous suspension>
#3      MacOSDevice.startApp (package:flutter_tools/src/macos/macos_device.dart:81:11)
<asynchronous suspension>
#4      FlutterDevice.runHot (package:flutter_tools/src/resident_runner.dart:364:54)
<asynchronous suspension>
#5      HotRunner.run (package:flutter_tools/src/run_hot.dart:253:39)
<asynchronous suspension>
#6      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:430:37)
<asynchronous suspension>
#7      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:488:18)
#8      _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:77:64)
#9      _rootRunUnary (dart:async/zone.dart:1132:38)
#10     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#11     _FutureListener.handleValue (dart:async/future_impl.dart:126:18)
#12     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:639:45)
#13     Future._propagateToListeners (dart:async/future_impl.dart:668:32)
#14     Future._complete (dart:async/future_impl.dart:473:7)
#15     _SyncCompleter.complete (dart:async/future_impl.dart:51:12)
#16     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:28:18)
#17     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:294:13)
#18     RunCommand.usageValues (package:flutter_tools/src/commands/run.dart)
#19     _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:77:64)
#20     _rootRunUnary (dart:async/zone.dart:1132:38)
#21     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#22     _FutureListener.handleValue (dart:async/future_impl.dart:126:18)
#23     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:639:45)
#24     Future._propagateToListeners (dart:async/future_impl.dart:668:32)
#25     Future._complete (dart:async/future_impl.dart:473:7)
#26     _SyncCompleter.complete (dart:async/future_impl.dart:51:12)
#27     _AsyncAwaitCompleter.complete.<anonymous closure> (dart:async-patch/async_patch.dart:33:20)
#28     _rootRun (dart:async/zone.dart:1124:13)
#29     _CustomZone.run (dart:async/zone.dart:1021:19)
#30     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:947:23)
#31     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#32     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#33     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:115:13)
#34     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:5)
```

## flutter doctor

```
[32m[✓][39m Flutter (Channel unknown, v1.6.1-pre.4, on Mac OS X 10.13.3 17D102, locale zh-Hans-CN)
    [32m•[39m Flutter version 1.6.1-pre.4 at /usr/local/flutter
    [32m•[39m Framework revision 7d667decd5 (5 days ago), 2019-05-15 04:35:39 -0400
    [32m•[39m Engine revision 208011758f
    [32m•[39m Dart version 2.3.1 (build 2.3.1-dev.0.0 a0290f823c)

[31m[✗][39m Android toolchain - develop for Android devices
    [31m✗[39m Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/setup/#android-setup for detailed instructions).
      If the Android SDK has been installed to a custom location, set ANDROID_HOME to that location.
      You may also want to add it to your PATH environment variable.


[33m[!][39m iOS toolchain - develop for iOS devices (Xcode 9.4.1)
    [32m•[39m Xcode at /Applications/Xcode.app/Contents/Developer
    [32m•[39m Xcode 9.4.1, Build version 9F2000
    [31m✗[39m libimobiledevice and ideviceinstaller are not installed. To install with Brew, run:
        brew update
        brew install --HEAD usbmuxd
        brew link usbmuxd
        brew install --HEAD libimobiledevice
        brew install ideviceinstaller
    [31m✗[39m ios-deploy not installed. To install:
        brew install ios-deploy
    [31m✗[39m CocoaPods not installed.
        CocoaPods is used to retrieve the iOS platform side's plugin code that responds to your plugin usage on the Dart side.
        Without resolving iOS dependencies with CocoaPods, plugins will not work on iOS.
        For more info, see https://flutter.dev/platform-plugins
      To install:
        brew install cocoapods
        pod setup

[33m[!][39m Android Studio (not installed)
    [32m•[39m Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/setup/#android-setup for detailed instructions).

[33m[!][39m IntelliJ IDEA Ultimate Edition (version 2018.3.1)
    [32m•[39m IntelliJ at /Applications/IntelliJ IDEA.app
    [31m✗[39m Flutter plugin not installed; this adds Flutter specific functionality.
    [31m✗[39m Dart plugin not installed; this adds Dart specific functionality.
    [32m•[39m For information about installing plugins, see
      https://flutter.dev/intellij-setup/#installing-the-plugins

[32m[✓][39m VS Code (version 1.34.0)
    [32m•[39m VS Code at /Applications/Visual Studio Code.app/Contents
    [32m•[39m Flutter extension version 3.0.2

[32m[✓][39m Connected device (1 available)
    [32m•[39m macOS • macOS • darwin-x64 • Mac OS X 10.13.3 17D102

[33m![39m Doctor found issues in 4 categories.
```

**Comment by mmaitlen** [comment]
Getting the same error, flutter_02.log included

Flutter crash report; please file at https://github.com/flutter/flutter/issues.

## command

flutter run

## exception

NoSuchMethodError: NoSuchMethodError: The getter 'executable' was called on null.
Receiver: null
Tried calling: executable

```
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:50:5)
#1      BuildableMacOSApp.executable (package:flutter_tools/src/macos/application_package.dart:142:28)
#2      MacOSDevice.stopApp (package:flutter_tools/src/macos/macos_device.dart:110:28)
<asynchronous suspension>
#3      MacOSDevice.startApp (package:flutter_tools/src/macos/macos_device.dart:81:11)
<asynchronous suspension>
#4      FlutterDevice.runHot (package:flutter_tools/src/resident_runner.dart:364:54)
<asynchronous suspension>
#5      HotRunner.run (package:flutter_tools/src/run_hot.dart:253:39)
<asynchronous suspension>
#6      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:430:37)
<asynchronous suspension>
#7      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:488:18)
#8      _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:77:64)
#9      _rootRunUnary (dart:async/zone.dart:1132:38)
#10     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#11     _FutureListener.handleValue (dart:async/future_impl.dart:126:18)
#12     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:639:45)
#13     Future._propagateToListeners (dart:async/future_impl.dart:668:32)
#14     Future._complete (dart:async/future_impl.dart:473:7)
#15     _SyncCompleter.complete (dart:async/future_impl.dart:51:12)
#16     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:28:18)
#17     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:294:13)
#18     RunCommand.usageValues (package:flutter_tools/src/commands/run.dart)
#19     _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:77:64)
#20     _rootRunUnary (dart:async/zone.dart:1132:38)
#21     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#22     _FutureListener.handleValue (dart:async/future_impl.dart:126:18)
#23     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:639:45)
#24     Future._propagateToListeners (dart:async/future_impl.dart:668:32)
#25     Future._complete (dart:async/future_impl.dart:473:7)
#26     _SyncCompleter.complete (dart:async/future_impl.dart:51:12)
#27     _AsyncAwaitCompleter.complete.<anonymous closure> (dart:async-patch/async_patch.dart:33:20)
#28     _rootRun (dart:async/zone.dart:1124:13)
#29     _CustomZone.run (dart:async/zone.dart:1021:19)
#30     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:947:23)
#31     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#32     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#33     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:115:13)
#34     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:5)
```

## flutter doctor

```
[32m[✓][39m Flutter (Channel dev, v1.6.0, on Mac OS X 10.13.6 17G65, locale en-US)
    [32m•[39m Flutter version 1.6.0 at /Users/maitm003/Workspace/flutter
    [32m•[39m Framework revision ed90d05596 (6 days ago), 2019-05-14 17:09:29 -0700
    [32m•[39m Engine revision 832cdacc6f
    [32m•[39m Dart version 2.3.1 (build 2.3.1-dev.0.0 a0290f823c)

[32m[✓][39m Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    [32m•[39m Android SDK at /Users/maitm003/Library/Android/sdk
    [32m•[39m Android NDK location not configured (optional; useful for native profiling support)
    [32m•[39m Platform android-28, build-tools 28.0.3
    [32m•[39m Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    [32m•[39m Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)
    [32m•[39m All Android licenses accepted.

[32m[✓][39m iOS toolchain - develop for iOS devices (Xcode 10.1)
    [32m•[39m Xcode at /Applications/Xcode.app/Contents/Developer
    [32m•[39m Xcode 10.1, Build version 10B61
    [32m•[39m ios-deploy 1.9.4
    [32m•[39m CocoaPods version 1.5.3

[32m[✓][39m Android Studio (version 3.2)
    [32m•[39m Android Studio at /Applications/Android Studio.app/Contents
    [32m•[39m Flutter plugin version 31.1.1
    [32m•[39m Dart plugin version 181.5656
    [32m•[39m Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)

[32m[✓][39m IntelliJ IDEA Community Edition (version 2018.1.5)
    [32m•[39m IntelliJ at /Applications/IntelliJ IDEA CE.app
    [32m•[39m Flutter plugin version 29.0.2
    [32m•[39m Dart plugin version 181.4892.1

[32m[✓][39m VS Code (version 1.34.0)
    [32m•[39m VS Code at /Applications/Visual Studio Code.app/Contents
    [32m•[39m Flutter extension version 3.0.2

[32m[✓][39m Connected device (2 available)
    [32m•[39m Android SDK built for x86 • emulator-5554 • android-x86 • Android 9 (API 28) (emulator)
    [32m•[39m macOS                     • macOS         • darwin-x64  • Mac OS X 10.13.6 17G65

[32m•[39m No issues found!
```

**Comment by mmaitlen** [comment]
Just realized I was running in Flutter dev channel instead of master.  @kasnet have you tried switching to master channel?

**Comment by BondarenkoStas** [comment]
@kasnet did you solve the issue?

**Comment by iapicca** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
  
Thanks for your contribution.
