### ISSUE TITLE
Error while building widget from StreamBuilder

### ISSUE THREAD

**Issue by jeantuffier** [flutter/flutter#33076]
## Steps to Reproduce

replace 
```
StreamBuilder _buildFromStream() {
    return StreamBuilder<ViewAllScreenState>(
      stream: _bloc.stream,
      initialData: _bloc.getInitialState(),
      builder: (context, snapshot) {
        return ListView.builder(
          itemCount: snapshot.data.items.length,
          itemBuilder: (context, index) => snapshot.data.items[index].widget,
          scrollDirection: Axis.vertical,
          controller: _scrollController,
        );
      },
    );
  }
```
with
```
StreamBuilder _buildFromStream() {
    return StreamBuilder<ViewAllScreenState>(
      stream: _bloc.stream,
      initialData: _bloc.getInitialState(),
      builder: (context, snapshot) {
        Text("list of ${snapshot.data.items.length}");
      },
    );
  }
```

## Logs

`flutter run --verbose` result :
```
 +81 ms] I/flutter ( 3004): ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
[        ] I/flutter ( 3004): The following assertion was thrown building StreamBuilder<ViewAllScreenState>(dirty, state:
[        ] I/flutter ( 3004): _StreamBuilderBaseState<ViewAllScreenState, AsyncSnapshot<ViewAllScreenState>>#29feb):
[        ] I/flutter ( 3004): A build function returned null.
[        ] I/flutter ( 3004): The offending widget is: StreamBuilder<ViewAllScreenState>
[        ] I/flutter ( 3004): Build functions must never return null. To return an empty space that causes the building widget to
[        ] I/flutter ( 3004): fill available room, return "new Container()". To return an empty space that takes as little room as
[        ] I/flutter ( 3004): possible, return "new Container(width: 0.0, height: 0.0)".
[   +4 ms] I/flutter ( 3004): 
[        ] I/flutter ( 3004): When the exception was thrown, this was the stack:
[   +5 ms] I/flutter ( 3004): #0      debugWidgetBuilderValue.<anonymous closure> (package:flutter/src/widgets/debug.dart:270:7)
[        ] I/flutter ( 3004): #1      debugWidgetBuilderValue (package:flutter/src/widgets/debug.dart:287:4)
[        ] I/flutter ( 3004): #2      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3737:7)
[        ] I/flutter ( 3004): #3      Element.rebuild (package:flutter/src/widgets/framework.dart:3559:5)
[        ] I/flutter ( 3004): #4      ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3716:5)
[        ] I/flutter ( 3004): #5      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3864:11)
[        ] I/flutter ( 3004): #6      ComponentElement.mount (package:flutter/src/widgets/framework.dart:3711:5)
[  +13 ms] I/flutter ( 3004): #7      Element.inflateWidget (package:flutter/src/widgets/framework.dart:2956:14)
[        ] I/flutter ( 3004): #8      Element.updateChild (package:flutter/src/widgets/framework.dart:2759:12)
[        ] I/flutter ( 3004): #9      SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4876:14)
[        ] I/flutter ( 3004): #10     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2956:14)
[        ] I/flutter ( 3004): #11     Element.updateChild (package:flutter/src/widgets/framework.dart:2759:12)
[        ] I/flutter ( 3004): #12     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4876:14)
[        ] I/flutter ( 3004): #13     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2956:14)
[        ] I/flutter ( 3004): #14     Element.updateChild (package:flutter/src/widgets/framework.dart:2759:12)
[        ] I/flutter ( 3004): #15     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3747:16)
[        ] I/flutter ( 3004): #16     Element.rebuild (package:flutter/src/widgets/framework.dart:3559:5)
[        ] I/flutter ( 3004): #17     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3716:5)
[        ] I/flutter ( 3004): #18     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3711:5)
[        ] I/flutter ( 3004): #19     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2956:14)
[        ] I/flutter ( 3004): #20     Element.updateChild (package:flutter/src/widgets/framework.dart:2759:12)
[        ] I/flutter ( 3004): #21     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3747:16)
[        ] I/flutter ( 3004): #22     Element.rebuild (package:flutter/src/widgets/framework.dart:3559:5)
[        ] I/flutter ( 3004): #23     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3716:5)
[        ] I/flutter ( 3004): #24     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3711:5)
[        ] I/flutter ( 3004): #25     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2956:14)
[        ] I/flutter ( 3004): #26     Element.updateChild (package:flutter/src/widgets/framework.dart:2759:12)
[        ] I/flutter ( 3004): #27     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3747:16)
[        ] I/flutter ( 3004): #28     Element.rebuild (package:flutter/src/widgets/framework.dart:3559:5)
[        ] I/flutter ( 3004): #29     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3716:5)
[        ] I/flutter ( 3004): #30     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3711:5)
[        ] I/flutter ( 3004): #31     ParentDataElement.mount (package:flutter/src/widgets/framework.dart:4063:11)
[        ] I/flutter ( 3004): #32     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2956:14)
[        ] I/flutter ( 3004): #33     MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4982:32)
[        ] I/flutter ( 3004): #34     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2956:14)
[        ] I/flutter ( 3004): #35     Element.updateChild (package:flutter/src/widgets/framework.dart:2759:12)
[        ] I/flutter ( 3004): #36     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3747:16)
[        ] I/flutter ( 3004): #37     Element.rebuild (package:flutter/src/widgets/framework.dart:3559:5)
[        ] I/flutter ( 3004): #38     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3716:5)
[        ] I/flutter ( 3004): #39     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3864:11)
[        ] I/flutter ( 3004): #40     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3711:5)
[        ] I/flutter ( 3004): #41     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2956:14)
[        ] I/flutter ( 3004): #42     Element.updateChild (package:flutter/src/widgets/framework.dart:2759:12)
[        ] I/flutter ( 3004): #43     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3747:16)
[        ] I/flutter ( 3004): #44     Element.rebuild (package:flutter/src/widgets/framework.dart:3559:5)
[        ] I/flutter ( 3004): #45     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3716:5)
[        ] I/flutter ( 3004): #46     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3711:5)
[        ] I/flutter ( 3004): #47     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2956:14)
[        ] I/flutter ( 3004): #48     Element.updateChild (package:flutter/src/widgets/framework.dart:2759:12)
[        ] I/flutter ( 3004): #49     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3747:16)
[        ] I/flutter ( 3004): #50     Element.rebuild (package:flutter/src/widgets/framework.dart:3559:5)
[        ] I/flutter ( 3004): #51     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3716:5)
[        ] I/flutter ( 3004): #52     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3864:11)
[        ] I/flutter ( 3004): #53     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3711:5)
[        ] I/flutter ( 3004): #54     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2956:14)
[        ] I/flutter ( 3004): #55     Element.updateChild (package:flutter/src/widgets/framework.dart:2759:12)
[        ] I/flutter ( 3004): #56     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4876:14)
[        ] I/flutter ( 3004): #57     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2956:14)
[        ] I/flutter ( 3004): #58     Element.updateChild (package:flutter/src/widgets/framework.dart:2759:12)
[        ] I/flutter ( 3004): #59     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3747:16)
[        ] I/flutter ( 3004): #60     Element.rebuild (package:flutter/src/widgets/framework.dart:3559:5)
[        ] I/flutter ( 3004): #61     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3716:5)
[        ] I/flutter ( 3004): #62     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3711:5)
[        ] I/flutter ( 3004): #63     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2956:14)
[        ] I/flutter ( 3004): #64     Element.updateChild (package:flutter/src/widgets/framework.dart:2759:12)
[        ] I/flutter ( 3004): #65     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4876:14)
[        ] I/flutter ( 3004): #66     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2956:14)
[        ] I/flutter ( 3004): #67     Element.updateChild (package:flutter/src/widgets/framework.dart:2759:12)
[        ] I/flutter ( 3004): #68     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3747:16)
[        ] I/flutter ( 3004): #69     Element.rebuild (package:flutter/src/widgets/framework.dart:3559:5)
[        ] I/flutter ( 3004): #70     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3716:5)
[        ] I/flutter ( 3004): #71     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3864:11)
[        ] I/flutter ( 3004): #72     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3711:5)
[        ] I/flutter ( 3004): #73     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2956:14)
[        ] I/flutter ( 3004): #74     Element.updateChild (package:flutter/src/widgets/framework.dart:2759:12)
[        ] I/flutter ( 3004): #75     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3747:16)
[        ] I/flutter ( 3004): #76     Element.rebuild (package:flutter/src/widgets/framework.dart:3559:5)
[        ] I/flutter ( 3004): #77     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3716:5)
[        ] I/flutter ( 3004): #78     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3864:11)
[        ] I/flutter ( 3004): #79     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3711:5)
[        ] I/flutter ( 3004): #80     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2956:14)
[        ] I/flutter ( 3004): #81     Element.updateChild (package:flutter/src/widgets/framework.dart:2759:12)
[        ] I/flutter ( 3004): #82     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3747:16)
[        ] I/flutter ( 3004): #83     Element.rebuild (package:flutter/src/widgets/framework.dart:3559:5)
[        ] I/flutter ( 3004): #84     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3716:5)
[        ] I/flutter ( 3004): #85     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3711:5)
[        ] I/flutter ( 3004): #86     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2956:14)
[        ] I/flutter ( 3004): #87     Element.updateChild (package:flutter/src/widgets/framework.dart:2759:12)
[        ] I/flutter ( 3004): #88     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3747:16)
[        ] I/flutter ( 3004): #89     Element.rebuild (package:flutter/src/widgets/framework.dart:3559:5)
[        ] I/flutter ( 3004): #90     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3716:5)
[        ] I/flutter ( 3004): #91     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3711:5)
[        ] I/flutter ( 3004): #92     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2956:14)
[        ] I/flutter ( 3004): #93     Element.updateChild (package:flutter/src/widgets/framework.dart:2759:12)
[        ] I/flutter ( 3004): #94     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3747:16)
[        ] I/flutter ( 3004): #95     Element.rebuild (package:flutter/src/widgets/framework.dart:3559:5)
[        ] I/flutter ( 3004): #96     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3716:5)
[        ] I/flutter ( 3004): #97     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3864:11)
[        ] I/flutter ( 3004): #98     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3711:5)
[        ] I/flutter ( 3004): #99     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2956:14)
[        ] I/flutter ( 3004): #100    Element.updateChild (package:flutter/src/widgets/framework.dart:2759:12)
[        ] I/flutter ( 3004): #101    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3747:16)
[        ] I/flutter ( 3004): #102    Element.rebuild (package:flutter/src/widgets/framework.dart:3559:5)
[        ] I/flutter ( 3004): #103    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3716:5)
[        ] I/flutter ( 3004): #104    StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3864:11)
[        ] I/flutter ( 3004): #105    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3711:5)
[        ] I/flutter ( 3004): #106    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2956:14)
[        ] I/flutter ( 3004): #107    Element.updateChild (package:flutter/src/widgets/framework.dart:2759:12)
[        ] I/flutter ( 3004): #108    SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4876:14)
[        ] I/flutter ( 3004): #109    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2956:14)
[        ] I/flutter ( 3004): #110    Element.updateChild (package:flutter/src/widgets/framework.dart:2759:12)
[        ] I/flutter ( 3004): #111    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3747:16)
[        ] I/flutter ( 3004): #112    Element.rebuild (package:flutter/src/widgets/framework.dart:3559:5)
[        ] I/flutter ( 3004): #113    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3716:5)
[        ] I/flutter ( 3004): #114    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3711:5)
[        ] I/flutter ( 3004): #115    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2956:14)
[        ] I/flutter ( 3004): #116    Element.updateChild (package:flutter/src/widgets/framework.dart:2759:12)
[        ] I/flutter ( 3004): #117    SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4876:14)
[        ] I/flutter ( 3004): #118    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2956:14)
[        ] I/flutter ( 3004): #119    Element.updateChild (package:flutter/src/widgets/framework.dart:2759:12)
[        ] I/flutter ( 3004): #120    SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4876:14)
[        ] I/flutter ( 3004): #121    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2956:14)
[        ] I/flutter ( 3004): #122    Element.updateChild (package:flutter/src/widgets/framework.dart:2759:12)
[        ] I/flutter ( 3004): #123    SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4876:14)
[        ] I/flutter ( 3004): #124    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2956:14)
[        ] I/flutter ( 3004): #125    Element.updateChild (package:flutter/src/widgets/framework.dart:2759:12)
[        ] I/flutter ( 3004): #126    SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4876:14)
[        ] I/flutter ( 3004): #127    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2956:14)
[        ] I/flutter ( 3004): #128    Element.updateChild (package:flutter/src/widgets/framework.dart:2759:12)
[        ] I/flutter ( 3004): #129    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3747:16)
[        ] I/flutter ( 3004): #130    Element.rebuild (package:flutter/src/widgets/framework.dart:3559:5)
[        ] I/flutter ( 3004): #131    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3716:5)
[        ] I/flutter ( 3004): #132    StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3864:11)
[        ] I/flutter ( 3004): #133    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3711:5)
[        ] I/flutter ( 3004): #134    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2956:14)
[        ] I/flutter ( 3004): #135    Element.updateChild (package:flutter/src/widgets/framework.dart:2759:12)
[        ] I/flutter ( 3004): #136    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3747:16)
[        ] I/flutter ( 3004): #137    Element.rebuild (package:flutter/src/widgets/framework.dart:3559:5)
[ +985 ms] I/flutter ( 3004): #138    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3716:5)
[        ] I/flutter ( 3004): #139    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3711:5)
[        ] I/flutter ( 3004): #140    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2956:14)
[        ] I/flutter ( 3004): #141    Element.updateChild (package:flutter/src/widgets/framework.dart:2759:12)
[        ] I/flutter ( 3004): #142    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3747:16)
[        ] I/flutter ( 3004): #143    Element.rebuild (package:flutter/src/widgets/framework.dart:3559:5)
[        ] I/flutter ( 3004): #144    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3716:5)
[        ] I/flutter ( 3004): #145    StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3864:11)
[        ] I/flutter ( 3004): #146    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3711:5)
[        ] I/flutter ( 3004): #147    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2956:14)
[        ] I/flutter ( 3004): #148    Element.updateChild (package:flutter/src/widgets/framework.dart:2759:12)
[        ] I/flutter ( 3004): #149    SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4876:14)
[        ] I/flutter ( 3004): #150    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2956:14)
[        ] I/flutter ( 3004): #151    Element.updateChild (package:flutter/src/widgets/framework.dart:2759:12)
[        ] I/flutter ( 3004): #152    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3747:16)
[        ] I/flutter ( 3004): #153    Element.rebuild (package:flutter/src/widgets/framework.dart:3559:5)
[   +1 ms] I/flutter ( 3004): #154    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3716:5)
[        ] I/flutter ( 3004): #155    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3711:5)
[        ] I/flutter ( 3004): #156    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2956:14)
[        ] I/flutter ( 3004): #157    Element.updateChild (package:flutter/src/widgets/framework.dart:2759:12)
[        ] I/flutter ( 3004): #158    SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4876:14)
[  +12 ms] I/flutter ( 3004): #159    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2956:14)
[        ] I/flutter ( 3004): #160    Element.updateChild (package:flutter/src/widgets/framework.dart:2759:12)
[        ] I/flutter ( 3004): #161    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3747:16)
[        ] I/flutter ( 3004): #162    Element.rebuild (package:flutter/src/widgets/framework.dart:3559:5)
[        ] I/flutter ( 3004): #163    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3716:5)
[        ] I/flutter ( 3004): #164    StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3864:11)
[        ] I/flutter ( 3004): #165    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3711:5)
[        ] I/flutter ( 3004): #166    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2956:14)
[        ] I/flutter ( 3004): #167    Element.updateChild (package:flutter/src/widgets/framework.dart:2759:12)
[        ] I/flutter ( 3004): #168    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3747:16)
[        ] I/flutter ( 3004): #169    Element.rebuild (package:flutter/src/widgets/framework.dart:3559:5)
[        ] I/flutter ( 3004): #170    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3716:5)
[        ] I/flutter ( 3004): #171    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3711:5)
[        ] I/flutter ( 3004): #172    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2956:14)
[        ] I/flutter ( 3004): #173    Element.updateChild (package:flutter/src/widgets/framework.dart:2759:12)
[        ] I/flutter ( 3004): #174    SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4876:14)
[        ] I/flutter ( 3004): #175    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2956:14)
[        ] I/flutter ( 3004): #176    Element.updateChild (package:flutter/src/widgets/framework.dart:2759:12)
[        ] I/flutter ( 3004): #177    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3747:16)
[        ] I/flutter ( 3004): #178    Element.rebuild (package:flutter/src/widgets/framework.dart:3559:5)
[        ] I/flutter ( 3004): #179    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3716:5)
[        ] I/flutter ( 3004): #180    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3711:5)
[        ] I/flutter ( 3004): #181    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2956:14)
[        ] I/flutter ( 3004): #182    Element.updateChild (package:flutter/src/widgets/framework.dart:2759:12)
[        ] I/flutter ( 3004): #183    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3747:16)
[        ] I/flutter ( 3004): #184    Element.rebuild (package:flutter/src/widgets/framework.dart:3559:5)
[        ] I/flutter ( 3004): #185    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3716:5)
[        ] I/flutter ( 3004): #186    StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3864:11)
[        ] I/flutter ( 3004): #187    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3711:5)
[        ] I/flutter ( 3004): #188    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2956:14)
[        ] I/flutter ( 3004): #189    Element.updateChild (package:flutter/src/widgets/framework.dart:2759:12)
[        ] I/flutter ( 3004): #190    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3747:16)
[        ] I/flutter ( 3004): #191    Element.rebuild (package:flutter/src/widgets/framework.dart:3559:5)
[        ] I/flutter ( 3004): #192    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3716:5)
[        ] I/flutter ( 3004): #193    StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3864:11)
[        ] I/flutter ( 3004): #194    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3711:5)
[        ] I/flutter ( 3004): #195    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2956:14)
[        ] I/flutter ( 3004): #196    Element.updateChild (package:flutter/src/widgets/framework.dart:2759:12)
[        ] I/flutter ( 3004): #197    RenderObjectElement.updateChildren (package:flutter/src/widgets/framework.dart:4659:32)
[        ] I/flutter ( 3004): #198    MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4992:17)
[        ] I/flutter ( 3004): #199    Element.updateChild (package:flutter/src/widgets/framework.dart:2748:15)
[        ] I/flutter ( 3004): #200    _TheatreElement.update (package:flutter/src/widgets/overlay.dart:508:16)
[        ] I/flutter ( 3004): #201    Element.updateChild (package:flutter/src/widgets/framework.dart:2748:15)
[        ] I/flutter ( 3004): #202    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3747:16)
[        ] I/flutter ( 3004): #203    Element.rebuild (package:flutter/src/widgets/framework.dart:3559:5)
[        ] I/flutter ( 3004): #204    StatefulElement.update (package:flutter/src/widgets/framework.dart:3894:5)
[        ] I/flutter ( 3004): #205    Element.updateChild (package:flutter/src/widgets/framework.dart:2748:15)
[        ] I/flutter ( 3004): #206    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3747:16)
[        ] I/flutter ( 3004): #207    Element.rebuild (package:flutter/src/widgets/framework.dart:3559:5)
[        ] I/flutter ( 3004): #208    ProxyElement.update (package:flutter/src/widgets/framework.dart:4006:5)
[        ] I/flutter ( 3004): #209    Element.updateChild (package:flutter/src/widgets/framework.dart:2748:15)
[        ] I/flutter ( 3004): #210    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4883:14)
[        ] I/flutter ( 3004): #211    Element.updateChild (package:flutter/src/widgets/framework.dart:2748:15)
[        ] I/flutter ( 3004): #212    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3747:16)
[        ] I/flutter ( 3004): #213    Element.rebuild (package:flutter/src/widgets/framework.dart:3559:5)
[        ] I/flutter ( 3004): #214    StatefulElement.update (package:flutter/src/widgets/framework.dart:3894:5)
[        ] I/flutter ( 3004): #215    Element.updateChild (package:flutter/src/widgets/framework.dart:2748:15)
[        ] I/flutter ( 3004): #216    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4883:14)
[        ] I/flutter ( 3004): #217    Element.updateChild (package:flutter/src/widgets/framework.dart:2748:15)
[        ] I/flutter ( 3004): #218    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4883:14)
[        ] I/flutter ( 3004): #219    Element.updateChild (package:flutter/src/widgets/framework.dart:2748:15)
[        ] I/flutter ( 3004): #220    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3747:16)
[        ] I/flutter ( 3004): #221    Element.rebuild (package:flutter/src/widgets/framework.dart:3559:5)
[        ] I/flutter ( 3004): #222    BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2273:33)
[        ] I/flutter ( 3004): #223    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding&WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:700:20)
[        ] I/flutter ( 3004): #224    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:268:5)
[        ] I/flutter ( 3004): #225    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:988:15)
[        ] I/flutter ( 3004): #226    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:928:9)
[        ] I/flutter ( 3004): #227    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:840:5)
[        ] I/flutter ( 3004): #231    _invoke (dart:ui/hooks.dart:209:10)
[        ] I/flutter ( 3004): #232    _drawFrame (dart:ui/hooks.dart:168:3)
[        ] I/flutter ( 3004): (elided 3 frames from package dart:async)
[        ] I/flutter ( 3004): ════════════════════════════════════════════════════════════════════════════════════════════════════
```

`flutter analyze` result :
```
Analyzing in_order...                                                   
No issues found! (ran in 1.6s)
```

`flutter doctor -v` result :
```
[!] Flutter (Channel stable, v1.2.1, on Linux, locale en_US.UTF-8)
    • Flutter version 1.2.1 at /home/jean/development/flutter
    • Framework revision 8661d8aecd (3 months ago), 2019-02-14 19:19:53 -0800
    • Engine revision 3757390fa4
    • Dart version 2.1.2 (build 2.1.2-dev.0.0 0a7dcf17eb)
    ✗ Downloaded executables cannot execute on host.
      See https://github.com/flutter/flutter/issues/6207 for more information
      On Debian/Ubuntu/Mint: sudo apt-get install lib32stdc++6
      On Fedora: dnf install libstdc++.i686
      On Arch: pacman -S lib32-libstdc++5 (you need to enable multilib: https://wiki.archlinux.org/index.php/Official_repositories#multilib)


[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /home/jean/Android/Sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /home/jean/applications/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b16-5323222)
    • All Android licenses accepted.

[✓] Android Studio (version 3.4)
    • Android Studio at /home/jean/applications/android-studio
    • Flutter plugin version 35.3.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b16-5323222)

[✓] Connected device (1 available)
    • SM G970F • RF8M20KBKCL • android-arm64 • Android 9 (API 28)

! Doctor found issues in 1 category.

```

**Comment by LongCatIsLooong** [comment]
As the error message says, you didn't return in the builder function.

**Comment by jeantuffier** [comment]
Oh man, Looks like I was really tired when I made this. This is not the correct log message at all 😅
