### ISSUE TITLE
flutter build apk --release failed

### ISSUE THREAD

**Issue by Unfreeze-kk** [flutter/flutter#33103]
## Steps to Reproduce

1. flutter build apk --release

## Logs

```
Compiler message:                                                       
Error: SDK root directory not found: file:///Users/dengkangkang/dev/flutter/bin/cache/artifacts/engine/common/flutter_patched_sdk_product/.
Error: Error when reading 'file:///Users/dengkangkang/dev/flutter/bin/cache/artifacts/engine/common/flutter_patched_sdk_product/platform_strong.dill': No such file or directory
Error: Error when reading 'file:///Users/dengkangkang/dev/flutter/bin/cache/artifacts/engine/common/flutter_patched_sdk_product/platform_strong.dill': No such file or directory
Unhandled exception:                                                    
Crash when compiling package:flutter_app/main.dart,                     
at character offset null:                                               
RangeError (index): Index out of range: no indices are valid: 0         
#0      Uint8List.[] (dart:typed_data-patch/typed_data_patch.dart:2188:7)
#1      BinaryBuilder.readByte (package:kernel/binary/ast_from_binary.dart:95:27)
#2      BinaryBuilder.readUint32 (package:kernel/binary/ast_from_binary.dart:115:13)
#3      BinaryBuilder.readComponent (package:kernel/binary/ast_from_binary.dart:435:17)
#4      ProcessedOptions.loadComponent (package:front_end/src/base/processed_options.dart:388:10)
#5      ProcessedOptions.loadLinkDependencies.<anonymous closure> (package:front_end/src/base/processed_options.dart:376:35)
#6      MappedListIterable.elementAt (dart:_internal/iterable.dart:414:29)
#7      ListIterable.toList (dart:_internal/iterable.dart:219:19)       
#8      ProcessedOptions.loadLinkDependencies (package:front_end/src/base/processed_options.dart:376:67)
<asynchronous suspension>                                               
#9      generateKernelInternal.<anonymous closure> (package:front_end/src/kernel_generator_impl.dart:95:42)
<asynchronous suspension>                                               
#10     withCrashReporting (package:front_end/src/fasta/crash.dart:122:24)
<asynchronous suspension>                                               
#11     generateKernelInternal (package:front_end/src/kernel_generator_impl.dart:55:10)
<asynchronous suspension>                                               
#12     kernelForProgram.<anonymous closure> (package:front_end/src/api_prototype/kernel_generator.dart:48:28)
<asynchronous suspension>                                               
#13     CompilerContext.runWithOptions.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart:134:20)
<asynchronous suspension>                                               
#14     CompilerContext.runInContext.<anonymous closure>.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart:122:46)
#15     new Future.sync (dart:async/future.dart:224:31)                 
#16     CompilerContext.runInContext.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart:122:19)
#17     _rootRun (dart:async/zone.dart:1124:13)                         
#18     _CustomZone.run (dart:async/zone.dart:1021:19)                  
#19     _runZoned (dart:async/zone.dart:1516:10)                        
#20     runZoned (dart:async/zone.dart:1463:12)                         
#21     CompilerContext.runInContext (package:front_end/src/fasta/compiler_context.dart:121:12)
#22     CompilerContext.runWithOptions (package:front_end/src/fasta/compiler_context.dart:132:10)
#23     kernelForProgram (package:front_end/src/api_prototype/kernel_generator.dart:47:32)
<asynchronous suspension>                                               
#24     compileToKernel (package:vm/kernel_front_end.dart:301:27)       
<asynchronous suspension>                                               
#25     FrontendCompiler.compile.<anonymous closure> (package:vm/frontend_server.dart:350:56)
#26     new Future.<anonymous closure> (dart:async/future.dart:176:37)  
#27     _rootRun (dart:async/zone.dart:1120:38)                         
#28     _CustomZone.run (dart:async/zone.dart:1021:19)                  
#29     _CustomZone.runGuarded (dart:async/zone.dart:923:7)             
#30     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:963:23)
#31     _rootRun (dart:async/zone.dart:1124:13)                         
#32     _CustomZone.run (dart:async/zone.dart:1021:19)                  
#33     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:947:23)
#34     Timer._createTimer.<anonymous closure> (dart:async-patch/timer_patch.dart:21:15)
#35     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:382:19)   
#36     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:416:5)
#37     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:171:12)
                                                                        
                                                                        
#0      Uint8List.[] (dart:typed_data-patch/typed_data_patch.dart:2188:7)
#1      BinaryBuilder.readByte (package:kernel/binary/ast_from_binary.dart:95:27)
#2      BinaryBuilder.readUint32 (package:kernel/binary/ast_from_binary.dart:115:13)
#3      BinaryBuilder.readComponent (package:kernel/binary/ast_from_binary.dart:435:17)
#4      ProcessedOptions.loadComponent (package:front_end/src/base/processed_options.dart:388:10)
#5      ProcessedOptions.loadLinkDependencies.<anonymous closure> (package:front_end/src/base/processed_options.dart:376:35)
#6      MappedListIterable.elementAt (dart:_internal/iterable.dart:414:29)
#7      ListIterable.toList (dart:_internal/iterable.dart:219:19)       
#8      ProcessedOptions.loadLinkDependencies (package:front_end/src/base/processed_options.dart:376:67)
<asynchronous suspension>                                               
#9      generateKernelInternal.<anonymous closure> (package:front_end/src/kernel_generator_impl.dart:95:42)
<asynchronous suspension>                                               
#10     withCrashReporting (package:front_end/src/fasta/crash.dart:122:24)
<asynchronous suspension>                                               
#11     generateKernelInternal (package:front_end/src/kernel_generator_impl.dart:55:10)
<asynchronous suspension>                                               
#12     kernelForProgram.<anonymous closure> (package:front_end/src/api_prototype/kernel_generator.dart:48:28)
<asynchronous suspension>                                               
#13     CompilerContext.runWithOptions.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart:134:20)
<asynchronous suspension>                                               
#14     CompilerContext.runInContext.<anonymous closure>.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart:122:46)

```

```
Analyzing OpAndroid...                                                  

   info • This function has a return type of 'Future<void>', but doesn't end with a return statement • lib/bloc/Bloc.dart:62:3 • missing_return
   info • The function '_$BaseRspToJson' isn't used • lib/data/http/rsp/BaseRsp.g.dart:13:22 • unused_element
   info • Unused import: 'package:flutter_app/data/http/rsp/data/LoginData.dart' • lib/data/http/rsp/ClientListRsp.dart:4:8 • unused_import
   info • The function '_$ClientListRspToJson' isn't used • lib/data/http/rsp/ClientListRsp.g.dart:18:22 • unused_element
   info • Unused import: 'package:flutter_app/data/http/rsp/data/ClientListData.dart' • lib/data/http/rsp/ClientNeedListRsp.dart:3:8 • unused_import
   info • Unused import: 'package:flutter_app/data/http/rsp/data/LoginData.dart' • lib/data/http/rsp/ClientNeedListRsp.dart:5:8 • unused_import
   info • The function '_$ClientNeedListRspToJson' isn't used • lib/data/http/rsp/ClientNeedListRsp.g.dart:18:22 • unused_element
   info • Unused import: 'package:flutter_app/data/http/rsp/data/ClientListData.dart' • lib/data/http/rsp/ClientSupportListRsp.dart:2:8 • unused_import
   info • Unused import: 'package:flutter_app/data/http/rsp/data/ClientNeedListData.dart' • lib/data/http/rsp/ClientSupportListRsp.dart:3:8 • unused_import
   info • Unused import: 'package:flutter_app/data/http/rsp/data/LoginData.dart' • lib/data/http/rsp/ClientSupportListRsp.dart:4:8 • unused_import
   info • Name non-constant identifiers using lowerCamelCase • lib/data/http/rsp/ClientSupportListRsp.dart:64:7 • non_constant_identifier_names
   info • Name non-constant identifiers using lowerCamelCase • lib/data/http/rsp/ClientSupportListRsp.dart:65:7 • non_constant_identifier_names
   info • Name non-constant identifiers using lowerCamelCase • lib/data/http/rsp/ClientSupportListRsp.dart:66:7 • non_constant_identifier_names
   info • Name non-constant identifiers using lowerCamelCase • lib/data/http/rsp/ClientSupportListRsp.dart:67:7 • non_constant_identifier_names
   info • Name non-constant identifiers using lowerCamelCase • lib/data/http/rsp/ClientSupportListRsp.dart:68:10 • non_constant_identifier_names
   info • Name non-constant identifiers using lowerCamelCase • lib/data/http/rsp/ClientSupportListRsp.dart:74:10 • non_constant_identifier_names
   info • Name non-constant identifiers using lowerCamelCase • lib/data/http/rsp/ClientSupportListRsp.dart:75:7 • non_constant_identifier_names
   info • Name non-constant identifiers using lowerCamelCase • lib/data/http/rsp/ClientSupportListRsp.dart:76:7 • non_constant_identifier_names
   info • Name non-constant identifiers using lowerCamelCase • lib/data/http/rsp/ClientSupportListRsp.dart:82:7 • non_constant_identifier_names
   info • Name non-constant identifiers using lowerCamelCase • lib/data/http/rsp/ClientSupportListRsp.dart:83:10 • non_constant_identifier_names
   info • Name non-constant identifiers using lowerCamelCase • lib/data/http/rsp/ClientSupportListRsp.dart:84:10 • non_constant_identifier_names
   info • Name non-constant identifiers using lowerCamelCase • lib/data/http/rsp/ClientSupportListRsp.dart:85:10 • non_constant_identifier_names
   info • Name non-constant identifiers using lowerCamelCase • lib/data/http/rsp/ClientSupportListRsp.dart:86:10 • non_constant_identifier_names
   info • Name non-constant identifiers using lowerCamelCase • lib/data/http/rsp/ClientSupportListRsp.dart:87:10 • non_constant_identifier_names
   info • Name non-constant identifiers using lowerCamelCase • lib/data/http/rsp/ClientSupportListRsp.dart:88:7 • non_constant_identifier_names
   info • The function '_$ClientSupportListRspToJson' isn't used • lib/data/http/rsp/ClientSupportListRsp.g.dart:20:22 • unused_element
   info • The function '_$ClientSupportToJson' isn't used • lib/data/http/rsp/ClientSupportListRsp.g.dart:57:22 • unused_element
   info • Name non-constant identifiers using lowerCamelCase • lib/data/http/rsp/DailiesRsp.dart:48:10 • non_constant_identifier_names
   info • Name non-constant identifiers using lowerCamelCase • lib/data/http/rsp/DailiesRsp.dart:49:10 • non_constant_identifier_names
   info • Name non-constant identifiers using lowerCamelCase • lib/data/http/rsp/DailiesRsp.dart:50:10 • non_constant_identifier_names
   info • Name non-constant identifiers using lowerCamelCase • lib/data/http/rsp/DailiesRsp.dart:51:10 • non_constant_identifier_names
   info • Name non-constant identifiers using lowerCamelCase • lib/data/http/rsp/DailiesRsp.dart:52:10 • non_constant_identifier_names
   info • Name non-constant identifiers using lowerCamelCase • lib/data/http/rsp/DailiesRsp.dart:53:10 • non_constant_identifier_names
   info • The function '_$DailiesRspToJson' isn't used • lib/data/http/rsp/DailiesRsp.g.dart:18:22 • unused_element
   info • The function '_$DailyRspDataToJson' isn't used • lib/data/http/rsp/DailiesRsp.g.dart:34:22 • unused_element
   info • The function '_$DailyToJson' isn't used • lib/data/http/rsp/DailiesRsp.g.dart:47:22 • unused_element
   info • The function '_$LoginRspToJson' isn't used • lib/data/http/rsp/LoginRsp.g.dart:18:22 • unused_element
   info • Unused import: 'package:flutter_app/data/http/rsp/data/ClientListData.dart' • lib/data/http/rsp/OperationLogsRsp.dart:3:8 • unused_import
   info • Unused import: 'package:flutter_app/data/http/rsp/data/ClientNeedListData.dart' • lib/data/http/rsp/OperationLogsRsp.dart:4:8 • unused_import
   info • Unused import: 'package:flutter_app/data/http/rsp/data/LoginData.dart' • lib/data/http/rsp/OperationLogsRsp.dart:5:8 • unused_import
   info • Unused import: 'package:flutter_app/data/http/rsp/data/VisitLogsData.dart' • lib/data/http/rsp/OperationLogsRsp.dart:7:8 • unused_import
   info • The function '_$OperationLogsRspToJson' isn't used • lib/data/http/rsp/OperationLogsRsp.g.dart:18:22 • unused_element
   info • Unused import: 'package:flutter_app/data/http/rsp/data/LoginData.dart' • lib/data/http/rsp/SourceTypesRsp.dart:3:8 • unused_import
   info • Unused import: 'package:flutter_app/page/RadioListPage.dart' • lib/data/http/rsp/SourceTypesRsp.dart:5:8 • unused_import
   info • The function '_$SourceTypesRspToJson' isn't used • lib/data/http/rsp/SourceTypesRsp.g.dart:19:22 • unused_element
   info • Unused import: 'package:flutter_app/data/http/rsp/data/ClientListData.dart' • lib/data/http/rsp/VisitLogsRsp.dart:3:8 • unused_import
   info • Unused import: 'package:flutter_app/data/http/rsp/data/ClientNeedListData.dart' • lib/data/http/rsp/VisitLogsRsp.dart:4:8 • unused_import
   info • Unused import: 'package:flutter_app/data/http/rsp/data/LoginData.dart' • lib/data/http/rsp/VisitLogsRsp.dart:5:8 • unused_import
   info • The function '_$VisitLogsRspToJson' isn't used • lib/data/http/rsp/VisitLogsRsp.g.dart:18:22 • unused_element
   info • Name non-constant identifiers using lowerCamelCase • lib/data/http/rsp/data/ClientListData.dart:61:7 • non_constant_identifier_names
   info • Name non-constant identifiers using lowerCamelCase • lib/data/http/rsp/data/ClientListData.dart:62:10 • non_constant_identifier_names
   info • Name non-constant identifiers using lowerCamelCase • lib/data/http/rsp/data/ClientListData.dart:63:7 • non_constant_identifier_names
   info • Name non-constant identifiers using lowerCamelCase • lib/data/http/rsp/data/ClientListData.dart:65:10 • non_constant_identifier_names
   info • Name non-constant identifiers using lowerCamelCase • lib/data/http/rsp/data/ClientListData.dart:66:10 • non_constant_identifier_names
   info • Name non-constant identifiers using lowerCamelCase • lib/data/http/rsp/data/ClientListData.dart:67:10 • non_constant_identifier_names
   info • Name non-constant identifiers using lowerCamelCase • lib/data/http/rsp/data/ClientListData.dart:69:10 • non_constant_identifier_names
   info • Name non-constant identifiers using lowerCamelCase • lib/data/http/rsp/data/ClientListData.dart:70:10 • non_constant_identifier_names
   info • Name non-constant identifiers using lowerCamelCase • lib/data/http/rsp/data/ClientListData.dart:72:7 • non_constant_identifier_names
   info • Name non-constant identifiers using lowerCamelCase • lib/data/http/rsp/data/ClientListData.dart:73:7 • non_constant_identifier_names
   info • Name non-constant identifiers using lowerCamelCase • lib/data/http/rsp/data/ClientListData.dart:74:10 • non_constant_identifier_names
   info • Name non-constant identifiers using lowerCamelCase • lib/data/http/rsp/data/ClientListData.dart:75:10 • non_constant_identifier_names
   info • Name non-constant identifiers using lowerCamelCase • lib/data/http/rsp/data/ClientListData.dart:77:7 • non_constant_identifier_names
   info • Name non-constant identifiers using lowerCamelCase • lib/data/http/rsp/data/ClientListData.dart:78:10 • non_constant_identifier_names
   info • Name non-constant identifiers using lowerCamelCase • lib/data/http/rsp/data/ClientListData.dart:79:10 • non_constant_identifier_names
   info • Name non-constant identifiers using lowerCamelCase • lib/data/http/rsp/data/ClientListData.dart:80:7 • non_constant_identifier_names
   info • Name non-constant identifiers using lowerCamelCase • lib/data/http/rsp/data/ClientListData.dart:81:10 • non_constant_identifier_names
   info • Name non-constant identifiers using lowerCamelCase • lib/data/http/rsp/data/ClientListData.dart:82:7 • non_constant_identifier_names
   info • Name non-constant identifiers using lowerCamelCase • lib/data/http/rsp/data/ClientListData.dart:83:7 • non_constant_identifier_names
   info • Name non-constant identifiers using lowerCamelCase • lib/data/http/rsp/data/ClientListData.dart:85:7 • non_constant_identifier_names
   info • Name non-constant identifiers using lowerCamelCase • lib/data/http/rsp/data/ClientListData.dart:87:10 • non_constant_identifier_names
   info • Name non-constant identifiers using lowerCamelCase • lib/data/http/rsp/data/ClientListData.dart:88:10 • non_constant_identifier_names
   info • Name non-constant identifiers using lowerCamelCase • lib/data/http/rsp/data/ClientListData.dart:89:10 • non_constant_identifier_names
   info • Name non-constant identifiers using lowerCamelCase • lib/data/http/rsp/data/ClientListData.dart:90:10 • non_constant_identifier_names
   info • Name non-constant identifiers using lowerCamelCase • lib/data/http/rsp/data/ClientListData.dart:91:10 • non_constant_identifier_names
   info • The function '_$ClientListDataToJson' isn't used • lib/data/http/rsp/data/ClientListData.g.dart:18:22 • unused_element
   info • The function '_$ClientToJson' isn't used • lib/data/http/rsp/data/ClientListData.g.dart:57:22 • unused_element
   info • Name non-constant identifiers using lowerCamelCase • lib/data/http/rsp/data/ClientNeedListData.dart:40:8 • non_constant_identifier_names
   info • Name non-constant identifiers using lowerCamelCase • lib/data/http/rsp/data/ClientNeedListData.dart:41:11 • non_constant_identifier_names
   info • Name non-constant identifiers using lowerCamelCase • lib/data/http/rsp/data/ClientNeedListData.dart:42:8 • non_constant_identifier_names
   info • Name non-constant identifiers using lowerCamelCase • lib/data/http/rsp/data/ClientNeedListData.dart:43:11 • non_constant_identifier_names
   info • The function '_$ClientNeedListDataToJson' isn't used • lib/data/http/rsp/data/ClientNeedListData.g.dart:15:22 • unused_element
   info • The function '_$NeedToJson' isn't used • lib/data/http/rsp/data/ClientNeedListData.g.dart:27:22 • unused_element
   info • The function '_$LoginDataToJson' isn't used • lib/data/http/rsp/data/LoginData.g.dart:13:22 • unused_element
   info • Name non-constant identifiers using lowerCamelCase • lib/data/http/rsp/data/OperationLogsData.dart:28:10 • non_constant_identifier_names
   info • Name non-constant identifiers using lowerCamelCase • lib/data/http/rsp/data/OperationLogsData.dart:29:10 • non_constant_identifier_names
   info • Name non-constant identifiers using lowerCamelCase • lib/data/http/rsp/data/OperationLogsData.dart:30:10 • non_constant_identifier_names
   info • Name non-constant identifiers using lowerCamelCase • lib/data/http/rsp/data/OperationLogsData.dart:31:10 • non_constant_identifier_names
   info • The function '_$OperationLogsDataToJson' isn't used • lib/data/http/rsp/data/OperationLogsData.g.dart:16:22 • unused_element
   info • The function '_$OperationLogToJson' isn't used • lib/data/http/rsp/data/OperationLogsData.g.dart:28:22 • unused_element
   info • The function '_$RadioBeanToJson' isn't used • lib/data/http/rsp/data/RadioBean.g.dart:13:22 • unused_element
   info • Name non-constant identifiers using lowerCamelCase • lib/data/http/rsp/data/VisitLogsData.dart:49:11 • non_constant_identifier_names
   info • Name non-constant identifiers using lowerCamelCase • lib/data/http/rsp/data/VisitLogsData.dart:50:11 • non_constant_identifier_names
   info • Name non-constant identifiers using lowerCamelCase • lib/data/http/rsp/data/VisitLogsData.dart:51:8 • non_constant_identifier_names
   info • Name non-constant identifiers using lowerCamelCase • lib/data/http/rsp/data/VisitLogsData.dart:52:11 • non_constant_identifier_names
   info • Name non-constant identifiers using lowerCamelCase • lib/data/http/rsp/data/VisitLogsData.dart:54:11 • non_constant_identifier_names
   info • Name non-constant identifiers using lowerCamelCase • lib/data/http/rsp/data/VisitLogsData.dart:55:8 • non_constant_identifier_names
   info • Name non-constant identifiers using lowerCamelCase • lib/data/http/rsp/data/VisitLogsData.dart:56:11 • non_constant_identifier_names
   info • Name non-constant identifiers using lowerCamelCase • lib/data/http/rsp/data/VisitLogsData.dart:57:11 • non_constant_identifier_names
   info • Name non-constant identifiers using lowerCamelCase • lib/data/http/rsp/data/VisitLogsData.dart:60:11 • non_constant_identifier_names
   info • The function '_$VisitLogsDataToJson' isn't used • lib/data/http/rsp/data/VisitLogsData.g.dart:16:22 • unused_element
   info • The function '_$VisitLogToJson' isn't used • lib/data/http/rsp/data/VisitLogsData.g.dart:35:22 • unused_element
   info • This class (or a class which this class inherits from) is marked as '@immutable', but one or more of its instance fields are not final: RadioListPage._radioValues, RadioListPage.groupValue •
          lib/page/RadioListPage.dart:5:7 • must_be_immutable
   info • This method overrides a method annotated as @mustCallSuper in 'AutomaticKeepAliveClientMixin', but does not invoke the overridden method • lib/page/clientdetails/ClientInfoPage.dart:30:10 • must_call_super
   info • This method overrides a method annotated as @mustCallSuper in 'AutomaticKeepAliveClientMixin', but does not invoke the overridden method • lib/page/clientdetails/ClientNeed.dart:30:10 • must_call_super
   info • This method overrides a method annotated as @mustCallSuper in 'AutomaticKeepAliveClientMixin', but does not invoke the overridden method • lib/page/clientdetails/ContactsPage.dart:27:10 • must_call_super
   info • Unused import: 'package:flutter_app/CommonRoute.dart' • lib/page/clientdetails/NewNeed.dart:2:8 • unused_import
   info • Unused import: 'package:flutter_app/data/http/rsp/BaseRsp.dart' • lib/page/clientdetails/NewNeed.dart:4:8 • unused_import
   info • Unused import: 'package:flutter_app/data/http/rsp/LoginRsp.dart' • lib/page/clientdetails/NewNeed.dart:5:8 • unused_import
   info • Unused import: 'package:flutter_app/data/persistence/Persistence.dart' • lib/page/clientdetails/NewNeed.dart:6:8 • unused_import
   info • Unused import: 'package:flutter_app/page/HomePage.dart' • lib/page/clientdetails/NewNeed.dart:7:8 • unused_import
   info • Unused import: 'package:flutter_app/CommonRoute.dart' • lib/page/clientdetails/NewPlainVisit.dart:2:8 • unused_import
   info • Unused import: 'package:flutter_app/data/http/rsp/BaseRsp.dart' • lib/page/clientdetails/NewPlainVisit.dart:4:8 • unused_import
   info • Unused import: 'package:flutter_app/data/http/rsp/LoginRsp.dart' • lib/page/clientdetails/NewPlainVisit.dart:5:8 • unused_import
   info • Unused import: 'package:flutter_app/data/persistence/Persistence.dart' • lib/page/clientdetails/NewPlainVisit.dart:7:8 • unused_import
   info • Unused import: 'package:flutter_app/page/HomePage.dart' • lib/page/clientdetails/NewPlainVisit.dart:8:8 • unused_import
   info • Unused import: 'package:flutter_app/CommonRoute.dart' • lib/page/clientdetails/NewPreSaleSupport.dart:2:8 • unused_import
   info • Unused import: 'package:flutter_app/data/http/rsp/BaseRsp.dart' • lib/page/clientdetails/NewPreSaleSupport.dart:5:8 • unused_import
   info • Unused import: 'package:flutter_app/data/http/rsp/LoginRsp.dart' • lib/page/clientdetails/NewPreSaleSupport.dart:6:8 • unused_import
   info • Unused import: 'package:flutter_app/data/persistence/Persistence.dart' • lib/page/clientdetails/NewPreSaleSupport.dart:8:8 • unused_import
   info • Unused import: 'package:flutter_app/page/HomePage.dart' • lib/page/clientdetails/NewPreSaleSupport.dart:9:8 • unused_import
   info • Unused import: 'package:flutter_app/CommonRoute.dart' • lib/page/clientdetails/NewSpecialVisit.dart:3:8 • unused_import
   info • Unused import: 'package:flutter_app/data/http/rsp/BaseRsp.dart' • lib/page/clientdetails/NewSpecialVisit.dart:6:8 • unused_import
   info • Unused import: 'package:flutter_app/data/http/rsp/LoginRsp.dart' • lib/page/clientdetails/NewSpecialVisit.dart:7:8 • unused_import
   info • Unused import: 'package:flutter_app/data/http/rsp/data/RadioBean.dart' • lib/page/clientdetails/NewSpecialVisit.dart:8:8 • unused_import
   info • Unused import: 'package:flutter_app/data/persistence/Persistence.dart' • lib/page/clientdetails/NewSpecialVisit.dart:9:8 • unused_import
   info • Unused import: 'package:flutter_app/page/HomePage.dart' • lib/page/clientdetails/NewSpecialVisit.dart:10:8 • unused_import
   info • Unused import: 'package:flutter_app/page/RadioListPage.dart' • lib/page/clientdetails/NewSpecialVisit.dart:11:8 • unused_import
   info • This method overrides a method annotated as @mustCallSuper in 'AutomaticKeepAliveClientMixin', but does not invoke the overridden method • lib/page/clientdetails/OperationLogPage.dart:31:10 • must_call_super
   info • This method overrides a method annotated as @mustCallSuper in 'AutomaticKeepAliveClientMixin', but does not invoke the overridden method • lib/page/clientdetails/VisitLogPage.dart:36:10 • must_call_super
   info • This function has a return type of 'Widget', but doesn't end with a return statement • lib/weight/DotsIndicator.dart:37:3 • missing_return
   info • Unused import: 'package:flutter_app/main.dart' • test/widget_test.dart:10:8 • unused_import

131 issues found. (ran in 3.1s)
```

```
[✓] Flutter (Channel beta, v1.5.4-hotfix.2, on Mac OS X 10.14.3 18D109, locale zh-Hans-CN)
    • Flutter version 1.5.4-hotfix.2 at /Users/dengkangkang/dev/flutter
    • Framework revision 7a4c33425d (3 weeks ago), 2019-04-29 11:05:24 -0700
    • Engine revision 52c7a1e849
    • Dart version 2.3.0 (build 2.3.0-dev.0.5 a1668566e5)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/dengkangkang/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)
    • All Android licenses accepted.

[!] iOS toolchain - develop for iOS devices (Xcode 10.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.2.1, Build version 10E1001
    • ios-deploy 2.0.0
    ✗ ios-deploy out of date (1.9.4 is required). To upgrade with Brew:
        brew upgrade ios-deploy
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 32.0.1
    • Dart plugin version 182.5124
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)

[✓] IntelliJ IDEA Ultimate Edition (version 2019.1.2)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 35.3.3
    • Dart plugin version 191.7141.49

[✓] Connected device (1 available)
    • CLT AL00 • D5F0218512002638 • android-arm64 • Android 9 (API 28)

! Doctor found issues in 1 category.

```

**Comment by Unfreeze-kk** [comment]
I changed channel to master.Then it work.
