### ISSUE TITLE
Render exception trying to use canvas.drawImage

### ISSUE THREAD

**Issue by danielwilson1702** [flutter/flutter#33112]
## Steps to Reproduce
Hi folks I am trying to paint an image so that I can try applying a mask to it. Can't figure it out but the code is throwing an error telling me to report it:

```import 'dart:math';
import 'dart:typed_data';
import 'dart:ui';

import 'package:flutter/material.dart';
import 'package:flutter/services.dart';

class MyPainter extends CustomPainter {
  MyPainter();

  var imagetoDraw;

  getImageFromAsset() {
    rootBundle.load("images/my_mask.png").then((bd) {
      Uint8List lst = new Uint8List.view(bd.buffer);

      instantiateImageCodec(lst).then((codec) {
        codec.getNextFrame().then((frameInfo) {
          imagetoDraw = frameInfo.image;
          print("bkImage instantiated: $imagetoDraw");
        });
      });
    });
  }

  @override
  void paint(Canvas canvas, Size size) {
    Paint paint = new Paint();
    canvas.drawImage(imagetoDraw, Offset.zero, paint);
  }

  @override
  bool shouldRepaint(CustomPainter oldDelegate) {
    return true;
  }
}
```

Code CustomPainter is used:
```
void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        appBar:
            AppBar(backgroundColor: Colors.blue, title: Text('I am a title')),
        backgroundColor: Colors.teal,
        body: SafeArea(
          child: Stack(
            children: <Widget>[
              Container(
                  height: 100.0,
                  width: 100.0,
                  child: CustomPaint(foregroundPainter: MyPainter())),
            ],
          ),
        ),
      ),
    );
  }
}
```

## Logs

```
I/flutter ( 9727): ══╡ EXCEPTION CAUGHT BY RENDERING LIBRARY ╞═════════════════════════════════════════════════════════
I/flutter ( 9727): The following assertion was thrown during paint():
I/flutter ( 9727): 'dart:ui/painting.dart': Failed assertion: line 3433: '<optimized out>': is not true.
I/flutter ( 9727): 
I/flutter ( 9727): Either the assertion indicates an error in the framework itself, or we should provide substantially
I/flutter ( 9727): more information in this error message to help you determine and fix the underlying cause.
I/flutter ( 9727): In either case, please report this assertion by filing a bug on GitHub:
I/flutter ( 9727):   https://github.com/flutter/flutter/issues/new?template=BUG.md
I/flutter ( 9727): 
I/flutter ( 9727): When the exception was thrown, this was the stack:
I/flutter ( 9727): #2      Canvas.drawImage (dart:ui/painting.dart:3433:12)
I/flutter ( 9727): #3      MyPainter.paint (package:mi_card/MyPainter.dart:29:12)
I/flutter ( 9727): #4      RenderCustomPaint._paintWithPainter (package:flutter/src/rendering/custom_paint.dart:523:13)
I/flutter ( 9727): #5      RenderCustomPaint.paint (package:flutter/src/rendering/custom_paint.dart:566:7)
I/flutter ( 9727): #6      RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2104:7)
I/flutter ( 9727): #7      PaintingContext.paintChild (package:flutter/src/rendering/object.dart:173:13)
I/flutter ( 9727): #8      _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:123:15)
I/flutter ( 9727): #9      RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2104:7)
I/flutter ( 9727): #10     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:173:13)
I/flutter ( 9727): #11     _RenderStack&RenderBox&ContainerRenderObjectMixin&RenderBoxContainerDefaultsMixin.defaultPaint (package:flutter/src/rendering/box.dart:2273:15)
I/flutter ( 9727): #12     RenderStack.paintStack (package:flutter/src/rendering/stack.dart:594:5)
I/flutter ( 9727): #13     RenderStack.paint (package:flutter/src/rendering/stack.dart:602:7)
I/flutter ( 9727): #14     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2104:7)
I/flutter ( 9727): #15     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:173:13)
I/flutter ( 9727): #16     RenderShiftedBox.paint (package:flutter/src/rendering/shifted_box.dart:70:15)
I/flutter ( 9727): #17     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2104:7)
I/flutter ( 9727): #18     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:173:13)
I/flutter ( 9727): #19     _RenderCustomMultiChildLayoutBox&RenderBox&ContainerRenderObjectMixin&RenderBoxContainerDefaultsMixin.defaultPaint (package:flutter/src/rendering/box.dart:2273:15)
I/flutter ( 9727): #20     RenderCustomMultiChildLayoutBox.paint (package:flutter/src/rendering/custom_layout.dart:361:5)
I/flutter ( 9727): #21     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2104:7)
I/flutter ( 9727): #22     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:173:13)
I/flutter ( 9727): #23     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:123:15)
I/flutter ( 9727): #24     _RenderInkFeatures.paint (package:flutter/src/material/material.dart:510:11)
I/flutter ( 9727): #25     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2104:7)
I/flutter ( 9727): #26     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:173:13)
I/flutter ( 9727): #27     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:123:15)
I/flutter ( 9727): #28     PaintingContext.pushLayer (package:flutter/src/rendering/object.dart:370:12)
I/flutter ( 9727): #29     RenderPhysicalModel.paint (package:flutter/src/rendering/proxy_box.dart:1716:15)
I/flutter ( 9727): #30     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2104:7)
I/flutter ( 9727): #31     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:173:13)
I/flutter ( 9727): #32     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:123:15)
I/flutter ( 9727): #33     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2104:7)
I/flutter ( 9727): #34     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:173:13)
I/flutter ( 9727): #35     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:123:15)
I/flutter ( 9727): #36     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2104:7)
I/flutter ( 9727): #37     PaintingContext._repaintCompositedChild (package:flutter/src/rendering/object.dart:128:11)
I/flutter ( 9727): #38     PaintingContext.repaintCompositedChild (package:flutter/src/rendering/object.dart:96:5)
I/flutter ( 9727): #39     PaintingContext._compositeChild (package:flutter/src/rendering/object.dart:190:7)
I/flutter ( 9727): #40     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:171:7)
I/flutter ( 9727): #41     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:123:15)
I/flutter ( 9727): #42     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2104:7)
I/flutter ( 9727): #43     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:173:13)
I/flutter ( 9727): #44     RenderAnimatedOpacity.paint (package:flutter/src/rendering/proxy_box.dart:910:17)
I/flutter ( 9727): #45     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2104:7)
I/flutter ( 9727): #46     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:173:13)
I/flutter ( 9727): #47     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:123:15)
I/flutter ( 9727): #48     RenderFractionalTranslation.paint (package:flutter/src/rendering/proxy_box.dart:2406:13)
I/flutter ( 9727): #49     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2104:7)
I/flutter ( 9727): #50     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:173:13)
I/flutter ( 9727): #51     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:123:15)
I/flutter ( 9727): #52     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2104:7)
I/flutter ( 9727): #53     PaintingContext._repaintCompositedChild (package:flutter/src/rendering/object.dart:128:11)
I/flutter ( 9727): #54     PaintingContext.repaintCompositedChild (package:flutter/src/rendering/object.dart:96:5)
I/flutter ( 9727): #55     PaintingContext._compositeChild (package:flutter/src/rendering/object.dart:190:7)
I/flutter ( 9727): #56     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:171:7)
I/flutter ( 9727): #57     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:123:15)
I/flutter ( 9727): #58     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2104:7)
I/flutter ( 9727): #59     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:173:13)
I/flutter ( 9727): #60     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:123:15)
I/flutter ( 9727): #61     RenderOffstage.paint (package:flutter/src/rendering/proxy_box.dart:3028:11)
I/flutter ( 9727): #62     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2104:7)
I/flutter ( 9727): #63     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:173:13)
I/flutter ( 9727): #64     _RenderStack&RenderBox&ContainerRenderObjectMixin&RenderBoxContainerDefaultsMixin.defaultPaint (package:flutter/src/rendering/box.dart:2273:15)
I/flutter ( 9727): #65     RenderStack.paintStack (package:flutter/src/rendering/stack.dart:594:5)
I/flutter ( 9727): #66     RenderStack.paint (package:flutter/src/rendering/stack.dart:602:7)
I/flutter ( 9727): #67     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2104:7)
I/flutter ( 9727): #68     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:173:13)
I/flutter ( 9727): #69     __RenderTheatre&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:123:15)
I/flutter ( 9727): #70     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2104:7)
I/flutter ( 9727): #71     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:173:13)
I/flutter ( 9727): #72     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:123:15)
I/flutter ( 9727): #73     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2104:7)
I/flutter ( 9727): #74     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:173:13)
I/flutter ( 9727): #75     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:123:15)
I/flutter ( 9727): #76     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2104:7)
I/flutter ( 9727): #77     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:173:13)
I/flutter ( 9727): #78     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:123:15)
I/flutter ( 9727): #79     RenderPointerListener.paint (package:flutter/src/rendering/proxy_box.dart:2608:11)
I/flutter ( 9727): #80     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2104:7)
I/flutter ( 9727): #81     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:173:13)
I/flutter ( 9727): #82     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:123:15)
I/flutter ( 9727): #83     RenderCustomPaint.paint (package:flutter/src/rendering/custom_paint.dart:564:11)
I/flutter ( 9727): #84     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2104:7)
I/flutter ( 9727): #85     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:173:13)
I/flutter ( 9727): #86     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:123:15)
I/flutter ( 9727): #87     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2104:7)
I/flutter ( 9727): #88     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:173:13)
I/flutter ( 9727): #89     RenderView.paint (package:flutter/src/rendering/view.dart:182:15)
I/flutter ( 9727): #90     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2104:7)
I/flutter ( 9727): #91     PaintingContext._repaintCompositedChild (package:flutter/src/rendering/object.dart:128:11)
I/flutter ( 9727): #92     PaintingContext.repaintCompositedChild (package:flutter/src/rendering/object.dart:96:5)
I/flutter ( 9727): #93     PipelineOwner.flushPaint (package:flutter/src/rendering/object.dart:859:29)
I/flutter ( 9727): #94     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding.drawFrame (package:flutter/src/rendering/binding.dart:349:19)
I/flutter ( 9727): #95     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding&WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:701:13)
I/flutter ( 9727): #96     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:286:5)
I/flutter ( 9727): #97     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1012:15)
I/flutter ( 9727): #98     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:952:9)
I/flutter ( 9727): #99     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.scheduleWarmUpFrame.<anonymous closure> (package:flutter/src/scheduler/binding.dart:773:7)
I/flutter ( 9727): #108    _Timer._runTimers (dart:isolate-patch/timer_impl.dart:382:19)
I/flutter ( 9727): #109    _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:416:5)
I/flutter ( 9727): #110    _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:171:12)
I/flutter ( 9727): (elided 10 frames from class _AssertionError, package dart:async, and package dart:async-patch)
I/flutter ( 9727): 
I/flutter ( 9727): The following RenderObject was being processed when the exception was fired:
I/flutter ( 9727):   RenderCustomPaint#5387c
I/flutter ( 9727):   creator: CustomPaint ← ConstrainedBox ← Container ← Stack ← MediaQuery ← Padding ← SafeArea ←
I/flutter ( 9727):   MediaQuery ← LayoutId-[<_ScaffoldSlot.body>] ← CustomMultiChildLayout ← AnimatedBuilder ←
I/flutter ( 9727):   DefaultTextStyle ← ⋯
I/flutter ( 9727):   parentData: <none> (can use size)
I/flutter ( 9727):   constraints: BoxConstraints(w=100.0, h=100.0)
I/flutter ( 9727):   size: Size(100.0, 100.0)
I/flutter ( 9727): This RenderObject has no descendants.
```

```
No issues found! (ran in 1.9s)
```

```
[√] Flutter (Channel beta, v1.5.4-hotfix.2, on Microsoft Windows [Version 10.0.17134.765], locale en-GB)
    • Flutter version 1.5.4-hotfix.2 at C:\flutter\flutter_windows_v0.5.1-beta\flutter
    • Framework revision 7a4c33425d (3 weeks ago), 2019-04-29 11:05:24 -0700
    • Engine revision 52c7a1e849
    • Dart version 2.3.0 (build 2.3.0-dev.0.5 a1668566e5)


[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at C:\Users\user\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
    • All Android licenses accepted.

[√] Android Studio (version 3.4)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 35.3.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

[√] Connected device (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 9 (API 28) (emulator)

```

**Comment by danielwilson1702** [comment]
A) Wasn't calling the image loading function (doh)
B) The actual image appears to not draw but that's for some other reason so I'll close this for the moment.
