### ISSUE TITLE
Can't return const from factory constructors on widgets when app started directly from IntelliJ.

### ISSUE THREAD

**Issue by MiSikora** [flutter/flutter#33123]
## Steps to Reproduce

```dart
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: MyHomePage.create(),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({Key key}) : super(key: key);

  factory MyHomePage.create() => const MyHomePage();

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  int _counter = 0;

  void _incrementCounter() {
    setState(() {
      _counter++;
    });
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text("🐛"),
      ),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            Text(
              'You have pushed the button this many times:',
            ),
            Text(
              '$_counter',
              style: Theme.of(context).textTheme.display1,
            ),
          ],
        ),
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: _incrementCounter,
        tooltip: 'Increment',
        child: Icon(Icons.add),
      ),
    );
  }
}
```

1. Run the code above from IntelliJ with `Run` (`⌃+R`).
2. Red screen with error is shown instead of the app.

When I run the app from a terminal with the `flutter run` command everything works normally.

## Stacktrace

```
I/flutter (12403): ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
I/flutter (12403): The following _CompileTimeError was thrown building MyApp(dirty):
I/flutter (12403): 'package:untitled1/main.dart': error: Not a constant expression.
I/flutter (12403): 
I/flutter (12403): When the exception was thrown, this was the stack:
I/flutter (12403): #0      MyApp.build (package:untitled1/main.dart:9:24)
I/flutter (12403): #1      StatelessElement.build (package:flutter/src/widgets/framework.dart:3789:28)
I/flutter (12403): #2      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3739:15)
I/flutter (12403): #3      Element.rebuild (package:flutter/src/widgets/framework.dart:3565:5)
I/flutter (12403): #4      ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3722:5)
I/flutter (12403): #5      ComponentElement.mount (package:flutter/src/widgets/framework.dart:3717:5)
I/flutter (12403): #6      Element.inflateWidget (package:flutter/src/widgets/framework.dart:2961:14)
I/flutter (12403): #7      Element.updateChild (package:flutter/src/widgets/framework.dart:2764:12)
I/flutter (12403): #8      RenderObjectToWidgetElement._rebuild (package:flutter/src/widgets/binding.dart:933:16)
I/flutter (12403): #9      RenderObjectToWidgetElement.mount (package:flutter/src/widgets/binding.dart:904:5)
I/flutter (12403): #10     RenderObjectToWidgetAdapter.attachToRenderTree.<anonymous closure> (package:flutter/src/widgets/binding.dart:850:17)
I/flutter (12403): #11     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2258:19)
I/flutter (12403): #12     RenderObjectToWidgetAdapter.attachToRenderTree (package:flutter/src/widgets/binding.dart:849:13)
I/flutter (12403): #13     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding&WidgetsBinding.attachRootWidget (package:flutter/src/widgets/binding.dart:736:7)
I/flutter (12403): #14     runApp (package:flutter/src/widgets/binding.dart:780:7)
I/flutter (12403): #15     main (package:untitled1/main.dart:3:16)
I/flutter (12403): #16     _runMainZoned.<anonymous closure>.<anonymous closure> (dart:ui/hooks.dart:199:25)
I/flutter (12403): #21     _runMainZoned.<anonymous closure> (dart:ui/hooks.dart:190:5)
I/flutter (12403): #22     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:300:19)
I/flutter (12403): #23     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:171:12)
I/flutter (12403): (elided 4 frames from package dart:async)
I/flutter (12403): ════════════════════════════════════════════════════════════════════════════════════════════════════
```

## `flutter analyze`

```
No issues found! (ran in 4.7s)
```

## `flutter doctor -v`

There is an iOS issue but I just tested on Android.

```
[✓] Flutter (Channel beta, v1.5.4-hotfix.2, on Mac OS X 10.14.4 18E226, locale en-PL)
    • Flutter version 1.5.4-hotfix.2 at /Users/michalsikora/.flutter_sdk/flutter
    • Framework revision 7a4c33425d (3 weeks ago), 2019-04-29 11:05:24 -0700
    • Engine revision 52c7a1e849
    • Dart version 2.3.0 (build 2.3.0-dev.0.5 a1668566e5)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/michalsikora/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = /Users/michalsikora/Library/Android/sdk
    • Java binary at: /Users/michalsikora/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/183.5522156/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
    • All Android licenses accepted.

[!] iOS toolchain - develop for iOS devices (Xcode 10.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.2.1, Build version 10E1001
    ✗ Verify that all connected devices have been paired with this computer in Xcode.
      If all devices have been paired, libimobiledevice and ideviceinstaller may require updating.
      To update with Brew, run:
        brew update
        brew uninstall --ignore-dependencies libimobiledevice
        brew uninstall --ignore-dependencies usbmuxd
        brew install --HEAD usbmuxd
        brew unlink usbmuxd
        brew link usbmuxd
        brew install --HEAD libimobiledevice
        brew install ideviceinstaller
    • ios-deploy 1.9.4
    • CocoaPods version 1.6.1

[✓] Android Studio (version 3.4)
    • Android Studio at /Users/michalsikora/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/183.5522156/Android Studio.app/Contents
    • Flutter plugin version 35.3.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

[✓] VS Code (version 1.33.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.0.2

[✓] Connected device (1 available)
    • FRD L09 • 73QDU16B24003748 • android-arm64 • Android 7.0 (API 24)

! Doctor found issues in 1 category.
```

**Comment by BondarenkoStas** [comment]
@MiSikora do you still encounter the issue?

**Comment by iapicca** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
  
Thanks for your contribution.
