### ISSUE TITLE
Can not rebuild SliverPersistentHeader

### ISSUE THREAD

**Issue by halkliff** [flutter/flutter#33131]
So, this error occours when trying to set the state of a `SliverPersistentHeader`'s pinned to either `true` or `false` through `setState()`.

## Steps to Reproduce

1. Receive a new state for a `SliverPersistentHeader` (through streams or providers)
2. try to set the `pinned` property to either `true` or `false` using `setState()`
3. Error occours.

## Logs

```

I/flutter ( 6052): ══╡ EXCEPTION CAUGHT BY RENDERING LIBRARY ╞═════════════════════════════════════════════════════════
I/flutter ( 6052): The following assertion was thrown during performLayout():
I/flutter ( 6052): 'package:flutter/src/rendering/viewport.dart': Failed assertion: line 1219 pos 12: 'center.parent ==
I/flutter ( 6052): this': is not true.
I/flutter ( 6052): 
I/flutter ( 6052): Either the assertion indicates an error in the framework itself, or we should provide substantially
I/flutter ( 6052): more information in this error message to help you determine and fix the underlying cause.
I/flutter ( 6052): In either case, please report this assertion by filing a bug on GitHub:
I/flutter ( 6052):   https://github.com/flutter/flutter/issues/new?template=BUG.md
I/flutter ( 6052): 
I/flutter ( 6052): When the exception was thrown, this was the stack:
I/flutter ( 6052): #2      RenderViewport.performLayout (package:flutter/src/rendering/viewport.dart:1219:12)
I/flutter ( 6052): #3      RenderObject._layoutWithoutResize (package:flutter/src/rendering/object.dart:1519:7)
I/flutter ( 6052): #4      PipelineOwner.flushLayout (package:flutter/src/rendering/object.dart:766:18)
I/flutter ( 6052): #5      _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding.drawFrame (package:flutter/src/rendering/binding.dart:347:19)
I/flutter ( 6052): #6      _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding&WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:701:13)
I/flutter ( 6052): #7      _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:286:5)
I/flutter ( 6052): #8      _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1012:15)
I/flutter ( 6052): #9      _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:952:9)
I/flutter ( 6052): #10     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:864:5)
I/flutter ( 6052): #14     _invoke (dart:ui/hooks.dart:219:10)
I/flutter ( 6052): #15     _drawFrame (dart:ui/hooks.dart:178:3)
I/flutter ( 6052): (elided 5 frames from class _AssertionError and package dart:async)
I/flutter ( 6052): 
I/flutter ( 6052): The following RenderObject was being processed when the exception was fired:
I/flutter ( 6052):   RenderViewport#4fb20 NEEDS-LAYOUT NEEDS-PAINT
I/flutter ( 6052):   creator: Viewport ← IgnorePointer-[GlobalKey#67aef] ← Semantics ← Listener ← _GestureSemantics ←
I/flutter ( 6052):   RawGestureDetector-[LabeledGlobalKey<RawGestureDetectorState>#02a04] ← Listener ← _ScrollableScope
I/flutter ( 6052):   ← _ScrollSemantics-[GlobalKey#8cd1b] ← RepaintBoundary ← CustomPaint ← RepaintBoundary ← ⋯
I/flutter ( 6052):   parentData: <none> (can use size)
I/flutter ( 6052):   constraints: BoxConstraints(0.0<=w<=411.4, 0.0<=h<=774.9)
I/flutter ( 6052):   layer: OffsetLayer#7ce24
I/flutter ( 6052):   size: Size(411.4, 774.9)
I/flutter ( 6052):   axisDirection: down
I/flutter ( 6052):   crossAxisDirection: right
I/flutter ( 6052):   offset: ScrollPositionWithSingleContext#61fcb(offset: 168.3, range: 0.0..745.1, viewport: 774.9,
I/flutter ( 6052):   ScrollableState, AlwaysScrollableScrollPhysics -> ClampingScrollPhysics, IdleScrollActivity#9317e,
I/flutter ( 6052):   ScrollDirection.idle)
I/flutter ( 6052):   anchor: 0.0
I/flutter ( 6052): This RenderObject had the following descendants (showing up to depth 5):
I/flutter ( 6052):   _RenderSliverFloatingPinnedPersistentHeaderForWidgets#ed3fc NEEDS-LAYOUT NEEDS-PAINT
I/flutter ( 6052):   RenderSliverList#2ee47 relayoutBoundary=up1
I/flutter ( 6052):     RenderIndexedSemantics#e07fc relayoutBoundary=up2 NEEDS-PAINT
I/flutter ( 6052):       RenderRepaintBoundary#1727a relayoutBoundary=up3 NEEDS-PAINT
I/flutter ( 6052):         RenderSemanticsAnnotations#5dddb relayoutBoundary=up4 NEEDS-PAINT
I/flutter ( 6052):           RenderPadding#c6dbc relayoutBoundary=up5 NEEDS-PAINT
I/flutter ( 6052):     RenderIndexedSemantics#42075 relayoutBoundary=up2 NEEDS-PAINT
I/flutter ( 6052):       RenderRepaintBoundary#62574 relayoutBoundary=up3 NEEDS-PAINT
I/flutter ( 6052):         RenderSemanticsAnnotations#8aacf relayoutBoundary=up4 NEEDS-PAINT
I/flutter ( 6052):           RenderPadding#372cd relayoutBoundary=up5 NEEDS-PAINT
I/flutter ( 6052):     RenderIndexedSemantics#50f9b relayoutBoundary=up2 NEEDS-PAINT
I/flutter ( 6052):       RenderRepaintBoundary#ce3ce relayoutBoundary=up3 NEEDS-PAINT
I/flutter ( 6052):         RenderSemanticsAnnotations#25881 relayoutBoundary=up4 NEEDS-PAINT
I/flutter ( 6052):           RenderPadding#78584 relayoutBoundary=up5 NEEDS-PAINT
I/flutter ( 6052):     RenderIndexedSemantics#2adff relayoutBoundary=up2
I/flutter ( 6052):       RenderRepaintBoundary#bb7f8 relayoutBoundary=up3
I/flutter ( 6052):         RenderSemanticsAnnotations#dd7b6 relayoutBoundary=up4
I/flutter ( 6052):           RenderPadding#85888 relayoutBoundary=up5
I/flutter ( 6052):     RenderIndexedSemantics#2573e relayoutBoundary=up2
I/flutter ( 6052):       RenderRepaintBoundary#dd78a relayoutBoundary=up3
I/flutter ( 6052):         RenderSemanticsAnnotations#dee52 relayoutBoundary=up4
I/flutter ( 6052):           RenderPadding#8fa14 relayoutBoundary=up5
I/flutter ( 6052):     RenderIndexedSemantics#0adb0 relayoutBoundary=up2
I/flutter ( 6052):       RenderRepaintBoundary#f02cf relayoutBoundary=up3
I/flutter ( 6052):         RenderSemanticsAnnotations#da398 relayoutBoundary=up4
I/flutter ( 6052):           RenderPadding#312eb relayoutBoundary=up5
I/flutter ( 6052):   ...(descendants list truncated after 25 lines)
I/flutter ( 6052): ════════════════════════════════════════════════════════════════════════════════════════════════════
I/flutter ( 6052): Another exception was thrown: NoSuchMethodError: The getter 'visible' was called on null.
```

Flutter Analyze:

```
Analyzing ema_app...

   info - Name non-constant identifiers using lowerCamelCase - lib\themes.dart:3:17 - non_constant_identifier_names
   info - Name non-constant identifiers using lowerCamelCase - lib\themes.dart:32:17 - non_constant_identifier_names
```

Flutter Doctor:

```
[√] Flutter (Channel stable, v1.5.4-hotfix.2, on Microsoft Windows [versÃ£o 10.0.17134.765], locale pt-BR)
    • Flutter version 1.5.4-hotfix.2 at C:\tools\flutter
    • Framework revision 7a4c33425d (3 weeks ago), 2019-04-29 11:05:24 -0700
    • Engine revision 52c7a1e849
    • Dart version 2.3.0 (build 2.3.0-dev.0.5 a1668566e5)


[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at C:\Users\werbe\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: C:\Users\werbe\AppData\Local\JetBrains\Toolbox\apps\AndroidStudio\ch-0\183.5522156\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
    • All Android licenses accepted.

[√] Android Studio (version 3.4)
    • Android Studio at C:\Users\werbe\AppData\Local\JetBrains\Toolbox\apps\AndroidStudio\ch-0\183.5522156
    • Flutter plugin version 35.3.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

[!] IntelliJ IDEA Ultimate Edition (version 2019.1)
    • IntelliJ at C:\Users\werbe\AppData\Local\JetBrains\Toolbox\apps\IDEA-U\ch-0\191.7141.44
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.dev/intellij-setup/#installing-the-plugins

[√] Connected device (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 9 (API 28) (emulator)

! Doctor found issues in 1 category.
```

**Comment by BondarenkoStas** [comment]
@halkliff please provide a code example to exactly reproduce it. is it the same with current flutter stable version?

**Comment by BondarenkoStas** [comment]
Ok, thank you, then I think it's safe to close it.
