### ISSUE TITLE
 Compiler failed on /Users/busayoadebayo/AndroidStudioProjects/flutter_app/lib/main.dart Error launching application on iPhone Xʀ.

### ISSUE THREAD

**Issue by midastouch365** [flutter/flutter#33169]
## Steps to Reproduce

https://gist.github.com/midastouch365/363b9afd892880e17fe1ad5f63b455a8
-->

1. I created a new flutter application from scratch. And the code that flutter populated after that was suppose to allow me click a button and change the value of the int in the body
2.  Without making any changes to the original code, I ran the program. It works perfectly in the past, but now Im receiving an error code.
3. The error code say "Launching lib/main.dart on iPhone Xʀ in debug mode...

Compiler message:
```
Error: Error when reading 'file:///Users/busayoadebayo/Desktop/flutter/bin/cache/artifacts/engine/common/flutter_patched_sdk/platform_strong.dill': No such file or directory
Unhandled exception:
RangeError (index): Index out of range: no indices are valid: 0
#0      Uint8List.[] (dart:typed_data-patch/typed_data_patch.dart:2188:7)
#1      BinaryBuilder.readByte (package:kernel/binary/ast_from_binary.dart:95:27)
#2      BinaryBuilder.readUint32 (package:kernel/binary/ast_from_binary.dart:115:13)
#3      BinaryBuilder.readComponent (package:kernel/binary/ast_from_binary.dart:435:17)
#4      IncrementalCompiler.prepareSummary (package:front_end/src/fasta/incremental_compiler.dart:594:12)
#5      IncrementalCompiler.computeDelta.<anonymous closure> (package:front_end/src/fasta/incremental_compiler.dart:150:25)
<asynchronous suspension>
#6      CompilerContext.runInContext.<anonymous closure>.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart:122:46)
#7      new Future.sync (dart:async/future.dart:224:31)
#8      CompilerContext.runInContext.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart:122:19)
#9      _rootRun (dart:async/zone.dart:1124:13)
#10     _CustomZone.run (dart:async/zone.dart:1021:19)
#11     _runZoned (dart:async/zone.dart:1516:10)
#12     runZoned (dart:async/zone.dart:1463:12)
#13     CompilerContext.runInContext (package:front_end/src/fasta/compiler_context.dart:121:12)
#14     IncrementalCompiler.computeDelta (package:front_end/src/fasta/incremental_compiler.dart:127:20)
<asynchronous suspension>
#15     IncrementalCompiler.compile (package:vm/incremental_compiler.dart:48:44)
<asynchronous suspension>
#16     FrontendCompiler.compile.<anonymous closure> (package:vm/frontend_server.dart:341:67)
#17     new Future.<anonymous closure> (dart:async/future.dart:176:37)
#18     _rootRun (dart:async/zone.dart:1120:38)
#19     _CustomZone.run (dart:async/zone.dart:1021:19)
#20     _CustomZone.runGuarded (dart:async/zone.dart:923:7)
#21     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:963:23)
#22     _rootRun (dart:async/zone.dart:1124:13)
#23     _CustomZone.run (dart:async/zone.dart:1021:19)
#24     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:947:23)
#25     Timer._createTimer.<anonymous closure> (dart:async-patch/timer_patch.dart:21:15)
#26     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:382:19)
#27     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:416:5)
#28     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:171:12)

Compiler failed on /Users/busayoadebayo/AndroidStudioProjects/flutter_app/lib/main.dart
Error launching application on iPhone Xʀ."
```
## LOG
```
<!--
      [  +26 ms] executing: [/Users/busayoadebayo/Desktop/flutter/] git log -n 1 --pretty=format:%H
[  +32 ms] Exit code 0 from: git log -n 1 --pretty=format:%H
[        ] 7a4c33425ddd78c54aba07d86f3f9a4a0051769b
[        ] executing: [/Users/busayoadebayo/Desktop/flutter/] git describe --match v*.*.* --first-parent --long --tags
[  +10 ms] Exit code 0 from: git describe --match v*.*.* --first-parent --long --tags
[        ] v1.5.4-hotfix.2-0-g7a4c33425
[  +13 ms] executing: [/Users/busayoadebayo/Desktop/flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[   +9 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/stable
[        ] executing: [/Users/busayoadebayo/Desktop/flutter/] git ls-remote --get-url origin
[   +9 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[  +53 ms] executing: [/Users/busayoadebayo/Desktop/flutter/] git rev-parse --abbrev-ref HEAD
[  +15 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] stable
[ +195 ms] executing: /Users/busayoadebayo/Library/Android/sdk/platform-tools/adb devices -l
[  +11 ms] Exit code 0 from: /Users/busayoadebayo/Library/Android/sdk/platform-tools/adb devices -l
[        ] List of devices attached
[   +5 ms] executing: idevice_id -h
[  +35 ms] /usr/bin/xcrun simctl list --json devices
[ +181 ms] No connected devices.
[        ] Run 'flutter emulators' to list and start any available device emulators.
[        ] If you expected your device to be detected, please run "flutter doctor" to diagnose
[        ] potential issues, or visit https://flutter.dev/setup/ for troubleshooting tips.
[  +11 ms] "flutter run" took 453ms.
[        ] "flutter run" took 453ms.

#0      throwToolExit (package:flutter_tools/src/base/common.dart:24:3)
#1      RunCommand.validateCommand (package:flutter_tools/src/commands/run.dart:257:7)
<asynchronous suspension>
#2      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:538:11)
<asynchronous suspension>
#3      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:495:33)
<asynchronous suspension>
#4      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:142:29)
<asynchronous suspension>
#5      _rootRun (dart:async/zone.dart:1124:13)
#6      _CustomZone.run (dart:async/zone.dart:1021:19)
#7      _runZoned (dart:async/zone.dart:1516:10)
#8      runZoned (dart:async/zone.dart:1463:12)
#9      AppContext.run (package:flutter_tools/src/base/context.dart:141:18)
<asynchronous suspension>
#10     FlutterCommand.run (package:flutter_tools/src/runner/flutter_command.dart:486:20)
#11     CommandRunner.runCommand (package:args/command_runner.dart:196:27)
<asynchronous suspension>
#12     FlutterCommandRunner.runCommand.<anonymous closure>
(package:flutter_tools/src/runner/flutter_command_runner.dart:396:21)
<asynchronous suspension>
#13     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:142:29)
<asynchronous suspension>
#14     _rootRun (dart:async/zone.dart:1124:13)
#15     _CustomZone.run (dart:async/zone.dart:1021:19)
#16     _runZoned (dart:async/zone.dart:1516:10)
#17     runZoned (dart:async/zone.dart:1463:12)
#18     AppContext.run (package:flutter_tools/src/base/context.dart:141:18)
<asynchronous suspension>
#19     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:356:19)
<asynchronous suspension>
#20     CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:111:29)
#21     new Future.sync (dart:async/future.dart:224:31)
#22     CommandRunner.run (package:args/command_runner.dart:111:11)
#23     FlutterCommandRunner.run (package:flutter_tools/src/runner/flutter_command_runner.dart:242:18)
#24     run.<anonymous closure> (package:flutter_tools/runner.dart:60:20)
<asynchronous suspension>
#25     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:142:29)
<asynchronous suspension>
#26     _rootRun (dart:async/zone.dart:1124:13)
#27     _CustomZone.run (dart:async/zone.dart:1021:19)
#28     _runZoned (dart:async/zone.dart:1516:10)
#29     runZoned (dart:async/zone.dart:1463:12)
#30     AppContext.run (package:flutter_tools/src/base/context.dart:141:18)
<asynchronous suspension>
#31     runInContext (package:flutter_tools/src/context_runner.dart:50:24)
<asynchronous suspension>
#32     run (package:flutter_tools/runner.dart:51:10)
#33     main (package:flutter_tools/executable.dart:60:9)
<asynchronous suspension>
#34     main (file:///b/s/w/ir/k/archive/flutter/packages/flutter_tools/bin/flutter_tools.dart:8:3)
#35     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:298:32)
#36     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:171:12)
```
```
Analyzing flutter_app...                                                
No issues found! (ran in 2.0s)
```
```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, v1.5.4-hotfix.2, on Mac OS X 10.14.5 18F132, locale en-US)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[✓] iOS toolchain - develop for iOS devices (Xcode 10.2.1)
[✓] Android Studio (version 3.4)
[✓] Connected device (1 available)

• No issues found!
```

**Comment by BondarenkoStas** [comment]
@midastouch365 did you manage to solve it? 
> Error: Error when reading 'file:///Users/busayoadebayo/Desktop/flutter/bin/cache/artifacts/engine/common/flutter_patched_sdk/platform_strong.dill': No such file or directory

It looks a lot like https://github.com/flutter/flutter/issues/33390. Can you please try this https://github.com/flutter/flutter/issues/33390#issuecomment-496246965?

**Comment by iapicca** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
  
Thanks for your contribution.
