### ISSUE TITLE
I am having trouble using Future.

### ISSUE THREAD

**Issue by huoshulei** [flutter/flutter#33174]
I am having trouble using Future:
```
Performing hot reload...
Syncing files to device SCL TL00...
Reloaded 1 of 454 libraries in 820ms.
V/AudioManager(24644): playSoundEffect   effectType: 0
V/AudioManager(24644): querySoundEffectsEnabled...
V/AudioManager(24644): isWiredHeadsetOn...
V/AudioManager(24644): isBluetoothA2dpOn...
I/flutter (24644): ══╡ EXCEPTION CAUGHT BY GESTURE ╞═══════════════════════════════════════════════════════════════════
I/flutter (24644): The following assertion was thrown while handling a gesture:
I/flutter (24644): type 'Future<dynamic>' is not a subtype of type 'Future<bool>'
I/flutter (24644): Either the assertion indicates an error in the framework itself, or we should provide substantially
I/flutter (24644): more information in this error message to help you determine and fix the underlying cause.
I/flutter (24644): In either case, please report this assertion by filing a bug on GitHub:
I/flutter (24644):   https://github.com/flutter/flutter/issues/new?template=BUG.md
I/flutter (24644): When the exception was thrown, this was the stack:
I/flutter (24644): #0      _MyHomePageState.checkJoinGroup (package:flutter_text_field/main.dart:48:36)
I/flutter (24644): #1      _MyHomePageState.build.<anonymous closure> (package:flutter_text_field/main.dart:41:13)
I/flutter (24644): #2      _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:511:14)
I/flutter (24644): #3      _InkResponseState.build.<anonymous closure> (package:flutter/src/material/ink_well.dart:566:30)
I/flutter (24644): #4      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:166:24)
I/flutter (24644): #5      TapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:240:9)
I/flutter (24644): #6      TapGestureRecognizer.handlePrimaryPointer (package:flutter/src/gestures/tap.dart:177:9)
I/flutter (24644): #7      PrimaryPointerGestureRecognizer.handleEvent (package:flutter/src/gestures/recognizer.dart:436:9)
I/flutter (24644): #8      PointerRouter._dispatch (package:flutter/src/gestures/pointer_router.dart:73:12)
I/flutter (24644): #9      PointerRouter.route (package:flutter/src/gestures/pointer_router.dart:101:11)
I/flutter (24644): #10     _WidgetsFlutterBinding&BindingBase&GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:221:19)
I/flutter (24644): #11     _WidgetsFlutterBinding&BindingBase&GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:199:22)
I/flutter (24644): #12     _WidgetsFlutterBinding&BindingBase&GestureBinding._handlePointerEvent (package:flutter/src/gestures/binding.dart:156:7)
I/flutter (24644): #13     _WidgetsFlutterBinding&BindingBase&GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:102:7)
I/flutter (24644): #14     _WidgetsFlutterBinding&BindingBase&GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:86:7)
I/flutter (24644): #18     _invoke1 (dart:ui/hooks.dart:233:10)
I/flutter (24644): #19     _dispatchPointerDataPacket (dart:ui/hooks.dart:154:5)
I/flutter (24644): (elided 3 frames from package dart:async)
I/flutter (24644): Handler: onTap
I/flutter (24644): Recognizer:
I/flutter (24644):   TapGestureRecognizer#477c7(debugOwner: GestureDetector, state: possible, won arena, finalPosition:
I/flutter (24644):   Offset(41.5, 110.0), sent tap down)
I/flutter (24644): ════════════════════════════════════════════════════════════════════════════════════════════════════
E/HAL     (24644): hw_get_module_by_class: lib loaded: /system/lib/hw/gralloc.msm8909.so
E/HAL     (24644): hw_get_module_by_class: lib loaded: /system/lib/hw/gralloc.msm8909.so
I/Timeline(24644): Timeline: Activity_idle id: android.os.BinderProxy@37a6d065 time:421534701
I/art     (24644): Ignoring second debugger -- accepting and dropping
I/Timeline(24644): Timeline: Activity_idle id: android.os.BinderProxy@37a6d065 time:421560772
I/art     (24644): Ignoring second debugger -- accepting and dropping
I/art     (24644): Ignoring second debugger -- accepting and dropping
I/art     (24644): Ignoring second debugger -- accepting and dropping

```
code:
```
 Future<bool> checkJoinGroup() => httpJson();

  Future<dynamic> httpJson() async {
    return Future.value(
            {"total": 0, "rows": true, "message": "获取成功", "status": "success"})
        .then(_logicalSuccessTransform);
  }

  /// 返回结果统一处理
  dynamic _logicalSuccessTransform(Map<String, dynamic> resp) {
    return resp['rows'];
  }
```

**Comment by superciccio** [comment]
```
Future<bool> checkJoinGroup() => httpJson();
   Future<bool> httpJson() async {
    return Future.value(
           true);
  }

bool _logicalSuccessTransform(Map<String, dynamic> resp) {
    return resp['rows']; // this needs to boolean
  }
```

**Comment by huoshulei** [comment]
Because the interface returns data is dynamic

**Comment by BondarenkoStas** [comment]
This is a question better suited for StackOverflow, since there doesn’t seem to be anything wrong with Flutter itself. Closing, as this is not an issue report. See https://flutter.dev/community for support options.
