### ISSUE TITLE
flutter doctor exception: 'isNotEmpty' was called on null

### ISSUE THREAD

**Issue by Zazo032** [flutter/flutter#33207]
## Steps to Reproduce

1. Upgrade to latest `master` version (1.6.1-pre.87)
2. Run `flutter doctor --verbose`

## Logs

```
flutter doctor --verbose
[✓] Flutter (Channel master, v1.6.1-pre.87, on Mac OS X 10.14.6 18G29g, locale es-ES)
    • Flutter version 1.6.1-pre.87 at /Applications/flutter
    • Framework revision a6f1c095dc (75 minutes ago), 2019-05-22 10:19:08 -0700
    • Engine revision 64f18f2cb6
    • Dart version 2.3.2 (build 2.3.2-dev.0.0 fde6a5917e)

⢿Unhandled exception:
NoSuchMethodError: The getter 'isNotEmpty' was called on null.
Receiver: null
Tried calling: isNotEmpty
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:50:5)
#1      FuchsiaSdk.listDevices (package:flutter_tools/src/fuchsia/fuchsia_sdk.dart:53:20)
<asynchronous suspension>
#2      FuchsiaDevices.pollingGetDevices (package:flutter_tools/src/fuchsia/fuchsia_device.dart:151:42)
<asynchronous suspension>
#3      PollingDeviceDiscovery.devices (package:flutter_tools/src/device.dart:188:52)
<asynchronous suspension>
#4      DeviceManager.getAllConnectedDevices (package:flutter_tools/src/device.dart:116:46)
<asynchronous suspension>
#5      DeviceValidator.validate (package:flutter_tools/src/doctor.dart:705:54)
<asynchronous suspension>
#6      Doctor.startValidatorTasks (package:flutter_tools/src/doctor.dart:129:52)
#7      Doctor.diagnose (package:flutter_tools/src/doctor.dart:200:41)
#8      _AsyncAwaitCompleter.start (dart:async-patch/async_patch.dart:49:6)
#9      Doctor.diagnose (package:flutter_tools/src/doctor.dart:190:24)
#10     DoctorCommand.runCommand (package:flutter_tools/src/commands/doctor.dart:48:39)
#11     _AsyncAwaitCompleter.start (dart:async-patch/async_patch.dart:49:6)
#12     DoctorCommand.runCommand (package:flutter_tools/src/commands/doctor.dart:34:42)
#13     FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:488:18)
#14     _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:77:64)
#15     _rootRunUnary (dart:async/zone.dart:1132:38)
#16     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#17     _FutureListener.handleValue (dart:async/future_impl.dart:126:18)
#18     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:639:45)
#19     Future._propagateToListeners (dart:async/future_impl.dart:668:32)
#20     Future._complete (dart:async/future_impl.dart:473:7)
#21     _SyncCompleter.complete (dart:async/future_impl.dart:51:12)
#22     _AsyncAwaitCompleter.complete.<anonymous closure> (dart:async-patch/async_patch.dart:33:20)
#23     _rootRun (dart:async/zone.dart:1124:13)
#24     _CustomZone.run (dart:async/zone.dart:1021:19)
#25     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:947:23)
#26     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#27     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#28     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:115:13)
#29     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:5)
```

**Comment by Zazo032** [comment]
Solved in latest master release
