### ISSUE TITLE
Flutter build apk/ appbundle crashes everytime

### ISSUE THREAD

**Issue by kohinoor98** [flutter/flutter#33209]
## command

flutter build appbundle

## exception

ProcessException: ProcessException: Process "D:\AndroidProjects\miras\android\gradlew.bat" exited abnormally:
Error: Could not find or load main class org.gradle.wrapper.GradleWrapperMain
  Command: D:\AndroidProjects\miras\android\gradlew.bat -v

```
#0      runCheckedAsync (package:flutter_tools/src/base/process.dart:255:5)
<asynchronous suspension>
#1      _initializeGradle (package:flutter_tools/src/android/gradle.dart:221:9)
<asynchronous suspension>
#2      _ensureGradle (package:flutter_tools/src/android/gradle.dart:202:37)
<asynchronous suspension>
#3      buildGradleProject (package:flutter_tools/src/android/gradle.dart:332:31)
<asynchronous suspension>
#4      buildAppBundle (package:flutter_tools/src/android/app_bundle.dart:43:10)
<asynchronous suspension>
#5      BuildAppBundleCommand.runCommand (package:flutter_tools/src/commands/build_appbundle.dart:43:11)
<asynchronous suspension>
#6      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:488:18)
#7      _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:77:64)
#8      _rootRunUnary (dart:async/zone.dart:1132:38)
#9      _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#10     _FutureListener.handleValue (dart:async/future_impl.dart:126:18)
#11     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:639:45)
#12     Future._propagateToListeners (dart:async/future_impl.dart:668:32)
#13     Future._complete (dart:async/future_impl.dart:473:7)
#14     _SyncCompleter.complete (dart:async/future_impl.dart:51:12)
#15     _AsyncAwaitCompleter.complete.<anonymous closure> (dart:async-patch/async_patch.dart:33:20)
#16     _rootRun (dart:async/zone.dart:1124:13)
#17     _CustomZone.run (dart:async/zone.dart:1021:19)
#18     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:947:23)
#19     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#20     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#21     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:115:13)
#22     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:5)
```

## flutter doctor

```
[32m[✓][39m Flutter (Channel dev, v1.6.0, on Microsoft Windows [Version 10.0.17763.503], locale en-IN)
    [32m•[39m Flutter version 1.6.0 at D:\Android\flutter
    [32m•[39m Framework revision ed90d05596 (8 days ago), 2019-05-14 17:09:29 -0700
    [32m•[39m Engine revision 832cdacc6f
    [32m•[39m Dart version 2.3.1 (build 2.3.1-dev.0.0 a0290f823c)

[32m[✓][39m Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    [32m•[39m Android SDK at C:\Users\kohin\AppData\Local\Android\sdk
    [32m•[39m Android NDK location not configured (optional; useful for native profiling support)
    [32m•[39m Platform android-28, build-tools 28.0.3
    [32m•[39m Java binary at: D:\Android\jre\bin\java
    [32m•[39m Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)
    [32m•[39m All Android licenses accepted.

[32m[✓][39m Android Studio (version 3.3)
    [32m•[39m Android Studio at D:\Android
    [32m•[39m Flutter plugin version 33.4.1
    [32m•[39m Dart plugin version 182.5215
    [32m•[39m Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)

[32m[✓][39m VS Code (version 1.34.0)
    [32m•[39m VS Code at C:\Users\kohin\AppData\Local\Programs\Microsoft VS Code
    [32m•[39m Flutter extension version 3.0.2

[33m[!][39m Connected device
    [33m![39m No devices available

[33m![39m Doctor found issues in 1 category.
```

**Comment by PauloKeller** [comment]
Similar issue:

```
 #0      throwToolExit (package:flutter_tools/src/base/common.dart:24:3)
#1      _buildGradleProjectV2 (package:flutter_tools/src/android/gradle.dart:497:7)
<asynchronous suspension>
#2      buildGradleProject (package:flutter_tools/src/android/gradle.dart:342:14)
<asynchronous suspension>
#3      buildAppBundle (package:flutter_tools/src/android/app_bundle.dart:43:10)
<asynchronous suspension>
#4      BuildAppBundleCommand.runCommand (package:flutter_tools/src/commands/build_appbundle.dart:50:11)
<asynchronous suspension>
#5      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:488:18)
#6      _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:77:64)
#7      _rootRunUnary (dart:async/zone.dart:1132:38)
#8      _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#9      _FutureListener.handleValue (dart:async/future_impl.dart:126:18)
#10     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:639:45)
#11     Future._propagateToListeners (dart:async/future_impl.dart:668:32)
#12     Future._complete (dart:async/future_impl.dart:473:7)
#13     _SyncCompleter.complete (dart:async/future_impl.dart:51:12)
#14     _AsyncAwaitCompleter.complete.<anonymous closure> (dart:async-patch/async_patch.dart:33:20)
#15     _rootRun (dart:async/zone.dart:1124:13)
#16     _CustomZone.run (dart:async/zone.dart:1021:19)
#17     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:947:23)
#18     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#19     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#20     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:115:13)
#21     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:5)
```

**Comment by sean5530** [comment]
I too have this same issue...

**Comment by BondarenkoStas** [comment]
is it still an issue? Can you delete flutter cache? Please paste your gradle-wrapper.properties

**Comment by iapicca** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
  
Thanks for your contribution.

**Comment by jonhunterking** [comment]
When I try and create my app bundle I get a similar issue: 

"* Error running Gradle:
ProcessException: Process "C:\flutter_ble-master\example\android\gradlew.bat" exited abnormally:

  Command: C:\flutter_ble-master\example\android\gradlew.bat app:properties


Please review your Gradle project setup in the android/ folder.
"
any idea how to fix this?

**Comment by kohinoor98** [comment]
What I did was reinstall flutter and create a new project and start fresh with a clean gradle
Re-configured everything, now that particular project is working
