### ISSUE TITLE
[camera] Camera plugin fails my build

### ISSUE THREAD

**Issue by Shuyinsama** [flutter/flutter#33222]
I am really getting very desperate. I am close to a deadline and suddenly this error pops up. My builds have been succeeding all week but of all moments when this has to happen is 1 day before a planned submit of the app.

I have no clue where to look anymore I have tried opening the project in Android Studio, I have cleared the gradle caches, cleared the `pub-cache` folder. I have tried downgrading all plugins to a pre AndroidX plugins. All to no avail.

When I run `flutter build apk -v` I get the following message:

```log
 Task :app:mergeReleaseResources FAILED
[        ]          *********************************************************
[        ] WARNING: This version of camera will break your Android build if it or its dependencies aren't compatible with AndroidX.
[        ]          See https://goo.gl/CP92wY for more information on the problem and how to fix it.
[        ]          This warning prints for all Android build failures. The real root cause of the error may be unrelated.
[        ]          *********************************************************
[        ] 134 actionable tasks: 6 executed, 128 up-to-date
[ +413 ms] Running Gradle task 'assembleRelease'... (completed in 8.3s)
[   +4 ms] "flutter apk" took 74,973ms.
[        ] "flutter apk" took 74,973ms.
Gradle task assembleRelease failed with exit code 1

#0      throwToolExit (package:flutter_tools/src/base/common.dart:24:3)
#1      _buildGradleProjectV2 (package:flutter_tools/src/android/gradle.dart:478:5)
<asynchronous suspension>
#2      buildGradleProject (package:flutter_tools/src/android/gradle.dart:346:14)
<asynchronous suspension>
#3      buildApk (package:flutter_tools/src/android/apk.dart:34:9)
<asynchronous suspension>
#4      BuildApkCommand.runCommand (package:flutter_tools/src/commands/build_apk.dart:51:11)
<asynchronous suspension>
#5      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:559:18)
#6      _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:77:64)
#7      _rootRunUnary (dart:async/zone.dart:1132:38)
#8      _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#9      _FutureListener.handleValue (dart:async/future_impl.dart:126:18)
#10     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:639:45)
#11     Future._propagateToListeners (dart:async/future_impl.dart:668:32)
#12     Future._complete (dart:async/future_impl.dart:473:7)
#13     _SyncCompleter.complete (dart:async/future_impl.dart:51:12)
#14     _AsyncAwaitCompleter.complete.<anonymous closure> (dart:async-patch/async_patch.dart:33:20)
#15     _rootRun (dart:async/zone.dart:1124:13)
#16     _CustomZone.run (dart:async/zone.dart:1021:19)
#17     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:947:23)
#18     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#19     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#20     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:115:13)
#21     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:5)
```

This has happened before but then downgrading the packages would be enough, but sadly this time it is not helping.

Here is my output of `flutter doctor`
```log
[✓] Flutter (Channel stable, v1.5.4-hotfix.2, on Mac OS X 10.14.5 18F132, locale en-NL)
    • Flutter version 1.5.4-hotfix.2 at /Users/patrick/flutter
    • Framework revision 7a4c33425d (3 weeks ago), 2019-04-29 11:05:24 -0700
    • Engine revision 52c7a1e849
    • Dart version 2.3.0 (build 2.3.0-dev.0.5 a1668566e5)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/patrick/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = /Users/patrick/Library/Android/sdk
    • ANDROID_SDK_ROOT = /Users/patrick/Library/Android/sdk
    • Java binary at: /Users/patrick/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/183.5522156/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.2.1, Build version 10E1001
    • ios-deploy 1.9.4
    • CocoaPods version 1.6.1

[✓] Android Studio (version 3.4)
    • Android Studio at /Users/patrick/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/183.5522156/Android Studio.app/Contents
    • Flutter plugin version 35.0.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

[✓] IntelliJ IDEA Ultimate Edition (version 2019.1.2)
    • IntelliJ at /Users/patrick/Applications/JetBrains Toolbox/IntelliJ IDEA Ultimate.app
    • Flutter plugin version 35.3.3
    • Dart plugin version 191.7141.49

[✓] VS Code (version 1.33.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.0.2
```

and these are the packages I have right now
```log
fluro: ^1.4.0
camera: ^0.5.0
path_provider: ^0.5.0+1
flutter_staggered_grid_view: ^0.2.7
flutter_launcher_icons: ^0.7.0
transparent_image: ^1.0.0
html_unescape: ^1.0.1+2
firebase_analytics: ^2.1.1+3
firebase_messaging: ^4.0.0+4
url_launcher: ^5.0.2
http: ^0.12.0+1
sqflite: ^1.1.5
flutter_offline: ^0.2.4+1
logging: ^0.11.3+2
flutter_html: ^0.9.6
photo_view: ^0.3.1
esys_flutter_share: ^1.0.1
native_device_orientation: ^0.2.0
image: ^2.1.0
```

**Comment by PsyKoMari** [comment]
Have you found a solution? 
Is your project using androidX? I saw the link in your log..

`          *********************************************************
[        ] WARNING: This version of camera will break your Android build if it or its dependencies aren't compatible with AndroidX.
[        ]          See https://goo.gl/CP92wY for more information on the problem and how to fix it.
[        ]          This warning prints for all Android build failures. The real root cause of the error may be unrelated.
[        ]          *********************************************************`

and it seems that if you don't want to migrate to androidX you need to use camera: 0.2.9+1

**Comment by PsyKoMari** [comment]
Have you found a solution?
Is your project using androidX?

**Comment by zglnfsdyy** [comment]
1.首先你的项目是否迁移androidX
2.查看android=>app=>build.gradle=>defaultConfig中的minSdkVersion最小也是21

**Comment by Shuyinsama** [comment]
I did not figure out why it didn't. I have updated recently all my packages including flutter itself and all seems to build fine now. I even updated the app to comply to the 64bit Play Story guidelines.

Sorry if I don't have a definitive answer on why it does work for me now. The project is using Android X and that setup was correct.
