### ISSUE TITLE
Error rendering InputDecorator ('child.parent == this' is not true)

### ISSUE THREAD

**Issue by jaysephjw** [flutter/flutter#33235]
I'm working on creating a custom input and want to wrap it with an InputDecorator. It's working fine, just prints this error a bunch (every redraw?): 

```
flutter: 'package:flutter/src/rendering/box.dart': Failed assertion: line 2161 pos 12: 'child.parent == this': is not true.` 
flutter: #2      RenderBox.applyPaintTransform (package:flutter/src/rendering/box.dart:2161:12)
flutter: #3      _RenderDecoration.applyPaintTransform (package:flutter/src/material/input_decorator.dart:1403:11)
flutter: #4      _SemanticsGeometry._computeValues 
```

Color input  I'm building for context: 
<img width="300" alt="Screen Shot 2019-05-22 at 8 13 53 PM" src="https://user-images.githubusercontent.com/3268245/58223360-26593b00-7cce-11e9-921e-b610317a55fb.png">

* only reproduces when isempty is true and hinttext is set
* not a crash or blocker for me

## Steps to Reproduce

```
void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  const MyApp({Key key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
        theme: ThemeData(
          primarySwatch: Colors.blue,
        ),
        home: InputDecorator(
            decoration: InputDecoration(hintText: 'Hint text'),
            isFocused: true,
            isEmpty: true,
            child: Container()));
  }
}
```
* My full use case is inside Focus <- Material <- Scaffold but still reproduces w/o those things. 

## Logs

<details><summary>full log</summary>
<p>

```
flutter: ══╡ EXCEPTION CAUGHT BY SCHEDULER LIBRARY ╞═════════════════════════════════════════════════════════
flutter: The following assertion was thrown during a scheduler callback:
flutter: 'package:flutter/src/rendering/box.dart': Failed assertion: line 2161 pos 12: 'child.parent ==
flutter: this': is not true.
flutter:
flutter: Either the assertion indicates an error in the framework itself, or we should provide substantially
flutter: more information in this error message to help you determine and fix the underlying cause.
flutter: In either case, please report this assertion by filing a bug on GitHub:
flutter:   https://github.com/flutter/flutter/issues/new?template=BUG.md
flutter:
flutter: When the exception was thrown, this was the stack:
flutter: #2      RenderBox.applyPaintTransform (package:flutter/src/rendering/box.dart:2161:12)
flutter: #3      _RenderDecoration.applyPaintTransform (package:flutter/src/material/input_decorator.dart:1403:11)
flutter: #4      _SemanticsGeometry._computeValues (package:flutter/src/rendering/object.dart:3559:14)
flutter: #5      new _SemanticsGeometry (package:flutter/src/rendering/object.dart:3521:5)
flutter: #6      _SwitchableSemanticsFragment.compileChildren (package:flutter/src/rendering/object.dart:3390:11)
flutter: #7      _SyncIterator.moveNext (dart:core-patch/core_patch.dart:152:12)
flutter: #8      List.addAll (dart:core-patch/growable_array.dart:193:13)
flutter: #9      _SwitchableSemanticsFragment.compileChildren (package:flutter/src/rendering/object.dart:3422:16)
flutter: #10     _SyncIterator.moveNext (dart:core-patch/core_patch.dart:152:12)
flutter: #11     List.addAll (dart:core-patch/growable_array.dart:193:13)
flutter: #12     _SwitchableSemanticsFragment.compileChildren (package:flutter/src/rendering/object.dart:3422:16)
flutter: #13     _SyncIterator.moveNext (dart:core-patch/core_patch.dart:152:12)
flutter: #14     List.addAll (dart:core-patch/growable_array.dart:193:13)
flutter: #15     _RootSemanticsFragment.compileChildren (package:flutter/src/rendering/object.dart:3302:16)
flutter: #16     _SyncIterator.moveNext (dart:core-patch/core_patch.dart:152:12)
flutter: #17     Iterable.single (dart:core/iterable.dart:552:13)
flutter: #18     RenderObject._updateSemantics (package:flutter/src/rendering/object.dart:2396:7)
flutter: #19     PipelineOwner.flushSemantics (package:flutter/src/rendering/object.dart:959:16)
flutter: #20     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding.drawFrame (package:flutter/src/rendering/binding.dart:350:19)
flutter: #21     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding&WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:701:13)
flutter: #22     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:285:5)
flutter: #23     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1012:15)
flutter: #24     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:952:9)
flutter: #25     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.scheduleWarmUpFrame.<anonymous closure> (package:flutter/src/scheduler/binding.dart:773:7)
flutter: #34     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:382:19)
flutter: #35     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:416:5)
flutter: #36     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:171:12)
```

</p></details>

```
Analyzing flutter_keyboard_actions...                                   
No issues found! (ran in 2.6s)
```
```
[✓] Flutter (Channel dev, v1.6.1, on Mac OS X 10.14.4 18E226, locale en-US)
    • Flutter version 1.6.1 at /Users/jwarrick/tools/flutter
    • Framework revision d31ce31a27 (2 days ago), 2019-05-20 17:25:59 -0700
    • Engine revision e3772232c2
    • Dart version 2.3.1 (build 2.3.1-dev.0.0 b48c8b1d1c)
[✓] iOS toolchain - develop for iOS devices (Xcode 10.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.1, Build version 10B61
    • ios-deploy 1.9.4
    • CocoaPods version 1.5.3
[✓] Connected device (1 available)
    • iPhone 7 • CCFE4EFF-0F46-4020-A1F9-902C9D5FBFD6 • ios • iOS 12.1 (simulator)
```

cheers and thanks for everything!

**Comment by jaysephjw** [comment]
Debugging at the point of the assertion, it looks like there's an unexpected `RenderAnimatedOpacity` between `child` and `parent`: 

<img width="600" alt="Screen Shot 2019-05-22 at 8 24 54 PM" src="https://user-images.githubusercontent.com/3268245/58223721-b51a8780-7ccf-11e9-8dff-1245bbb17445.png">

Here's `child.toString`:
 
```
RenderParagraph#8d590 relayoutBoundary=up17
 │ creator: RichText ← Text ← FadeTransition ← AnimatedOpacity ←
 │   _Decorator ← InputDecorator ← Container ← _FocusMarker ← Focus
 │   ← ColorInput ← Column ← Padding ← ⋯
 │ parentData: <none> (can use size)
 │ constraints: BoxConstraints(w=345.0, 0.0<=h<=Infinity)
 │ size: Size(345.0, 19.0)
 │ textAlign: start
 │ textDirection: ltr
 │ softWrap: wrapping at box width
 │ overflow: ellipsis
 │ locale: en_US
 │ maxLines: unlimited
 ╘═╦══ text ═══
   ║ TextSpan:
   ║   debugLabel: ((englishLike subhead 2014).merge(blackCupertino
   ║     subhead)).copyWith
   ║   inherit: false
   ║   color: Color(0x8a000000)
   ║   family: .SF UI Text
   ║   size: 16.0
   ║   weight: 400
   ║   baseline: alphabetic
   ║   decoration: TextDecoration.none
   ║   "Input Color"
   ╚═══════════
```

Looking for related issues I found https://github.com/flutter/flutter/issues/20283, which might include removing InputDecorators Opacity so could maybe be addressed at the same time.

**Comment by justinmc** [comment]
Thanks for the clear issue and all the details.  How do you get the exception to happen?  Does it just happen when you start the app?  I don't see the error when I run the code you gave.  Maybe I need to try on a physical iOS device.

**Comment by jaysephjw** [comment]
No problem. It happens right away on load in the iOS Simulator (iphone XS 12.1). Haven't tried on other devices.

**Comment by justinmc** [comment]
I was able to reproduce this on the iOS simulator now.  I think I was using Android yesterday, so I marked this as an iOS issue.

I see the same thing you pointed out with RenderAnimatedOpacity getting inserted between RenderParagraph and RenderDecoration, but RenderDecoration thinks its child is RenderAnimatedOpacity.

@HansMuller Do you have a hunch on this or know anyone that would?

**Comment by HansMuller** [comment]
I don't see the an obvious problem source. InputDecoration hints are unconditionally wrapped with an AnimatedOpacity widget - https://github.com/flutter/flutter/blob/master/packages/flutter/lib/src/material/input_decorator.dart#L1952

**Comment by iapicca** [comment]
Hi @jaysephjw 
if you are still experiencing the issue 
with the latest stable version of flutter
could you please provide your `flutter doctor -v` , 
your `flutter run --verbose` 
and a reproducible minimal code sample.
Thank you

**Comment by TahaTesser** [comment]
Hi @jaysephjw 
if you're still experiencing this problem, please create a new issue and provide the information
required in the template.
Thank you
