### ISSUE TITLE
Mediaquery called with a context that does not require a media query.

### ISSUE THREAD

**Issue by Tormenator1** [flutter/flutter#33313]
## Steps to Reproduce

1. Look at the [linked](https://gist.github.com/Tormenator1/e5e43c2f67527993d75b4b7a45a1e476) gist file
2. Attempt to run it
3. See the below.

## Logs
```
Launching lib\main.dart on Moto G4 Plus in debug mode...
Built build\app\outputs\apk\debug\app-debug.apk.
I/OpenGLRenderer(17056): Initialized EGL, version 1.4
D/OpenGLRenderer(17056): Swap behavior 1
I/flutter (17056): ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
I/flutter (17056): The following assertion was thrown building _TabControllerScope:
I/flutter (17056): MediaQuery.of() called with a context that does not contain a MediaQuery.
I/flutter (17056): No MediaQuery ancestor could be found starting from the context that was passed to MediaQuery.of().
I/flutter (17056): This can happen because you do not have a WidgetsApp or MaterialApp widget (those widgets introduce
I/flutter (17056): a MediaQuery), or it can happen if the context you use comes from a widget above those widgets.
I/flutter (17056): The context used was:
I/flutter (17056):   Scaffold(dirty, state: ScaffoldState#0c2e2(lifecycle state: initialized, tickers: tracking 1
I/flutter (17056):   ticker))
I/flutter (17056):
I/flutter (17056): When the exception was thrown, this was the stack:
I/flutter (17056): #0      MediaQuery.of 
I/flutter (17056): #1      ScaffoldState.didChangeDependencies 
I/flutter (17056): #2      StatefulElement._firstBuild 
I/flutter (17056): #3      ComponentElement.mount 
I/flutter (17056): #4      Element.inflateWidget 
I/flutter (17056): #5      Element.updateChild 
I/flutter (17056): #6      ComponentElement.performRebuild 
I/flutter (17056): #7      Element.rebuild 
I/flutter (17056): #8      ComponentElement._firstBuild 
I/flutter (17056): #9      ComponentElement.mount 
I/flutter (17056): #10     Element.inflateWidget 
I/flutter (17056): #11     Element.updateChild 
I/flutter (17056): #12     ComponentElement.performRebuild 
I/flutter (17056): #13     Element.rebuild 
I/flutter (17056): #14     ComponentElement._firstBuild 
I/flutter (17056): #15     StatefulElement._firstBuild 
I/flutter (17056): #16     ComponentElement.mount 
I/flutter (17056): #17     Element.inflateWidget 
I/flutter (17056): #18     Element.updateChild 
I/flutter (17056): #19     ComponentElement.performRebuild 
I/flutter (17056): #20     Element.rebuild 
I/flutter (17056): #21     ComponentElement._firstBuild 
I/flutter (17056): #22     ComponentElement.mount 
I/flutter (17056): #23     Element.inflateWidget 
I/flutter (17056): #24     Element.updateChild 
I/flutter (17056): #25     RenderObjectToWidgetElement._rebuild 
I/flutter (17056): #26     RenderObjectToWidgetElement.mount 
I/flutter (17056): #27     RenderObjectToWidgetAdapter.attachToRenderTree.<anonymous closure> 
I/flutter (17056): #28     BuildOwner.buildScope 
I/flutter (17056): #29     RenderObjectToWidgetAdapter.attachToRenderTree 
I/flutter (17056): #30     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding&WidgetsBinding.attachRootWidget 
I/flutter (17056): #31     runApp 
I/flutter (17056): #32     main
I/flutter (17056): #33     _runMainZoned.<anonymous closure>.<anonymous closure>  (dart:ui/hooks.dart:199:25)
I/flutter (17056): #38     _runMainZoned.<anonymous closure>  (dart:ui/hooks.dart:190:5)
I/flutter (17056): #39     _startIsolate.<anonymous closure>  (dart:isolate-patch/isolate_patch.dart:300:19)
I/flutter (17056): #40     _RawReceivePortImpl._handleMessage  (dart:isolate-patch/isolate_patch.dart:171:12)
I/flutter (17056): (elided 4 frames from package dart:async)
I/flutter (17056): ════════════════════════════════════════════════════════════════════════════════════════════════════
I/flutter (17056): ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
I/flutter (17056): The following assertion was thrown building _TabControllerScope:
I/flutter (17056): MediaQuery.of() called with a context that does not contain a MediaQuery.
I/flutter (17056): No MediaQuery ancestor could be found starting from the context that was passed to MediaQuery.of().
I/flutter (17056): This can happen because you do not have a WidgetsApp or MaterialApp widget (those widgets introduce
I/flutter (17056): a MediaQuery), or it can happen if the context you use comes from a widget above those widgets.
I/flutter (17056): The context used was:
I/flutter (17056):   Scaffold(dirty, state: ScaffoldState#e7a9d(lifecycle state: initialized, tickers: tracking 1
I/flutter (17056):   ticker))
I/flutter (17056):
I/flutter (17056): When the exception was thrown, this was the stack:
I/flutter (17056): #0      MediaQuery.of 
I/flutter (17056): #1      ScaffoldState.didChangeDependencies 
I/flutter (17056): #2      StatefulElement._firstBuild 
I/flutter (17056): #3      ComponentElement.mount 
I/flutter (17056): #4      Element.inflateWidget 
I/flutter (17056): #5      Element.updateChild 
I/flutter (17056): #6      ComponentElement.performRebuild 
I/flutter (17056): #7      Element.rebuild 
I/flutter (17056): #8      ProxyElement.update 
I/flutter (17056): #9      Element.updateChild 
I/flutter (17056): #10     ComponentElement.performRebuild 
I/flutter (17056): #11     Element.rebuild 
I/flutter (17056): #12     StatefulElement.update 
I/flutter (17056): #13     Element.updateChild 
I/flutter (17056): #14     ComponentElement.performRebuild 
I/flutter (17056): #15     Element.rebuild 
I/flutter (17056): #16     BuildOwner.buildScope 
I/flutter (17056): #17     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding&WidgetsBinding.drawFrame 
I/flutter (17056): #18     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding._handlePersistentFrameCallback 
I/flutter (17056): #19     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._invokeFrameCallback 
I/flutter (17056): #20     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.handleDrawFrame 
I/flutter (17056): #21     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.scheduleWarmUpFrame.<anonymous closure> 
I/flutter (17056): #23     _Timer._runTimers  (dart:isolate-patch/timer_impl.dart:382:19)
I/flutter (17056): #24     _Timer._handleMessage  (dart:isolate-patch/timer_impl.dart:416:5)
I/flutter (17056): #25     _RawReceivePortImpl._handleMessage  (dart:isolate-patch/isolate_patch.dart:171:12)
I/flutter (17056): (elided one frame from package dart:async-patch)
I/flutter (17056): ════════════════════════════════════════════════════════════════════════════════════════════════════
Reloaded 1 of 440 libraries in 521ms.
Application finished.
Exited (sigint)

```

```
Error response from the server: SERVER_ERROR FileSystemException(path=C:\Users\Skeletor\AppData\Local\Application
Data\*; message=Directory listing failed)
#0      _PhysicalFolder.getChildren (package:analyzer/file_system/physical_file_system.dart:334:7)
#1      _OverlayFolder.getChildren (package:analyzer/file_system/overlay_file_system.dart:334:10)
#2      ContextManagerImpl._createContext.checkManifestFilesIn
(package:analysis_server/src/context_manager.dart:1144:32)
#3      ContextManagerImpl._createContext.checkManifestFilesIn
(package:analysis_server/src/context_manager.dart:1152:33)
#4      ContextManagerImpl._createContext.checkManifestFilesIn
(package:analysis_server/src/context_manager.dart:1152:33)
#5      ContextManagerImpl._createContext.checkManifestFilesIn
(package:analysis_server/src/context_manager.dart:1152:33)
#6      ContextManagerImpl._createContext (package:analysis_server/src/context_manager.dart:1158:25)
#7      ContextManagerImpl._createContexts (package:analysis_server/src/context_manager.dart:1191:16)
#8      ContextManagerImpl.setRoots (package:analysis_server/src/context_manager.dart:736:9)
#9      AnalysisServer.setAnalysisRoots (package:analysis_server/src/analysis_server.dart:521:22)
#10     AnalysisDomainHandler.setAnalysisRoots (package:analysis_server/src/domain_analysis.dart:390:14)
#11     AnalysisDomainHandler.handleRequest (package:analysis_server/src/domain_analysis.dart:324:16)
#12     AnalysisServer.handleRequest.<anonymous closure>.<anonymous closure>
(package:analysis_server/src/analysis_server.dart:337:45)
#13     _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:258:15)
#14     AnalysisServer.handleRequest.<anonymous closure> (package:analysis_server/src/analysis_server.dart:333:50)
#15     _rootRun (dart:async/zone.dart:1124:13)
#16     _CustomZone.run (dart:async/zone.dart:1021:19)
#17     _runZoned (dart:async/zone.dart:1516:10)
#18     runZoned (dart:async/zone.dart:1500:12)
#19     AnalysisServer.handleRequest (package:analysis_server/src/analysis_server.dart:332:5)
#20     ByteStreamServerChannel._readRequest.<anonymous closure>
(package:analysis_server/src/channel/byte_stream_channel.dart:174:16)
#21     _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:258:15)
#22     ByteStreamServerChannel._readRequest (package:analysis_server/src/channel/byte_stream_channel.dart:165:47)
#23     ByteStreamServerChannel.listen.<anonymous closure>
(package:analysis_server/src/channel/byte_stream_channel.dart:110:26)
#24     _rootRunUnary (dart:async/zone.dart:1132:38)
#25     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#26     _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
#27     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#28     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#29     _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:68:11)
#30     _EventSinkWrapper.add (dart:async/stream_transformers.dart:15:11)
#31     _StringAdapterSink.add (dart:convert/string_conversion.dart:236:11)
#32     _LineSplitterSink._addLines (dart:convert/line_splitter.dart:150:13)
#33     _LineSplitterSink.addSlice (dart:convert/line_splitter.dart:125:5)
#34     StringConversionSinkMixin.add (dart:convert/string_conversion.dart:163:5)
#35     _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:120:24)
#36     _rootRunUnary (dart:async/zone.dart:1132:38)
#37     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#38     _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
#39     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#40     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#41     _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:68:11)
#42     _EventSinkWrapper.add (dart:async/stream_transformers.dart:15:11)
#43     _StringAdapterSink.add (dart:convert/string_conversion.dart:236:11)
#44     _StringAdapterSink.addSlice (dart:convert/string_conversion.dart:241:7)
#45     _Utf8ConversionSink.addSlice (dart:convert/string_conversion.dart:312:20)
#46     _Utf8ConversionSink.add (dart:convert/string_conversion.dart:305:5)
#47     _ConverterStreamEventSink.add (dart:convert/chunked_conversion.dart:72:18)
#48     _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:120:24)
#49     _rootRunUnary (dart:async/zone.dart:1132:38)
#50     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#51     _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
#52     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#53     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#54     _SyncStreamController._sendData (dart:async/stream_controller.dart:764:19)
#55     _StreamController._add (dart:async/stream_controller.dart:640:7)
#56     _StreamController.add (dart:async/stream_controller.dart:586:5)
#57     _Socket._onData (dart:io-patch/socket_patch.dart:1774:41)
#58     _rootRunUnary (dart:async/zone.dart:1136:13)
#59     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#60     _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
#61     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#62     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#63     _SyncStreamController._sendData (dart:async/stream_controller.dart:764:19)
#64     _StreamController._add (dart:async/stream_controller.dart:640:7)
#65     _StreamController.add (dart:async/stream_controller.dart:586:5)
#66     new _RawSocket.<anonymous closure> (dart:io-patch/socket_patch.dart:1323:33)
#67     _NativeSocket.issueReadEvent.issue (dart:io-patch/socket_patch.dart:844:14)
#68     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#69     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#70     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:115:13)
#71     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:5)
```
I am unable to find any documentation on these analysis errors,and they still persisted after reinstalling Flutter.

```
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, v1.5.4-hotfix.2, on Microsoft Windows [Version 10.0.17134.648], locale en-US)

[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[!] Android Studio (version 3.4)
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
[√] VS Code, 64-bit edition (version 1.33.1)
[√] Connected device (1 available)

! Doctor found issues in 1 category.
```
This is all that I've gotten

**Comment by shihaohong** [comment]
You have to wrap your `DefaultTabController` in a [`MaterialApp`](https://api.flutter.dev/flutter/material/MaterialApp-class.html). 

Note that the error message in your stack trace also provides that clue:
```
I/flutter (17056): No MediaQuery ancestor could be found starting from the context that was passed to MediaQuery.of().
I/flutter (17056): This can happen because you do not have a WidgetsApp or MaterialApp widget (those widgets introduce
I/flutter (17056): a MediaQuery), or it can happen if the context you use comes from a widget above those widgets.
```

Give that a try, and if it works, please close this issue.

**Comment by Tormenator1** [comment]
I did what you suggested and it worked. Thank you. Next time I'll read the stack trace more carefully.
