### ISSUE TITLE
BigInt encoding failed

### ISSUE THREAD

**Issue by shashkiranr** [flutter/flutter#33334]
Hi,

Unable to encode big int with json. If there is a workaround kindly let me know.

```
 BigInt test = BigInt.from(121312646141481);
 print(json.encode(test));
```

```
I/flutter ( 8787): The following JsonUnsupportedObjectError was thrown building Builder:
I/flutter ( 8787): Converting object to an encodable object failed: Instance of '_BigIntImpl'
I/flutter ( 8787): The following JsonUnsupportedObjectError was thrown building Builder:
I/flutter ( 8787): Converting object to an encodable object failed: Instance of '_BigIntImpl'
I/flutter ( 8787): 
I/flutter ( 8787): When the exception was thrown, this was the stack:
I/flutter ( 8787): #0      _JsonStringifier.writeObject (dart:convert/json.dart:647:7)
I/flutter ( 8787): #1      _JsonStringStringifier.printOn (dart:convert/json.dart:834:17)
I/flutter ( 8787): #2      _JsonStringStringifier.stringify (dart:convert/json.dart:819:5)
I/flutter ( 8787): #3      JsonEncoder.convert (dart:convert/json.dart:255:30)
I/flutter ( 8787): #4      JsonCodec.encode (dart:convert/json.dart:166:45)
I/flutter ( 8787): #5      _HomeState.initState (package:test_app/home/home.dart:102:16)
I/flutter ( 8787): #6      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3846:58)
I/flutter ( 8787): #7      ComponentElement.mount (package:flutter/src/widgets/framework.dart:3717:5)
I/flutter ( 8787): #8      Element.inflateWidget (package:flutter/src/widgets/framework.dart:2961:14)
I/flutter ( 8787): #9      Element.updateChild (package:flutter/src/widgets/framework.dart:2764:12)
I/flutter ( 8787): #10     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4876:14)
I/flutter ( 8787): #11     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2961:14)
I/flutter ( 8787): #12     Element.updateChild (package:flutter/src/widgets/framework.dart:2764:12)
I/flutter ( 8787): #13     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3750:16)
I/flutter ( 8787): #14     Element.rebuild (package:flutter/src/widgets/framework.dart:3565:5)
I/flutter ( 8787): #15     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3722:5)
I/flutter ( 8787): #16     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3717:5)
I/flutter ( 8787): #17     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2961:14)
I/flutter ( 8787): #18     Element.updateChild (package:flutter/src/widgets/framework.dart:2764:12)
I/flutter ( 8787): #19     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4876:14)
I/flutter ( 8787): #20     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2961:14)
I/flutter ( 8787): #21     Element.updateChild (package:flutter/src/widgets/framework.dart:2764:12)
I/flutter ( 8787): #22     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4876:14)
I/flutter ( 8787): #23     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2961:14)
I/flutter ( 8787): #24     Element.updateChild (package:flutter/src/widgets/framework.dart:2764:12)
I/flutter ( 8787): #25     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4876:14)
I/flutter ( 8787): #26     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2961:14)
I/flutter ( 8787): #27     Element.updateChild (package:flutter/src/widgets/framework.dart:2764:12)
I/flutter ( 8787): #28     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4876:14)
I/flutter ( 8787): #29     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2961:14)
I/flutter ( 8787): #30     Element.updateChild (package:flutter/src/widgets/framework.dart:2764:12)
I/flutter ( 8787): #31     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3750:16)
I/flutter ( 8787): #32     Element.rebuild (package:flutter/src/widgets/framework.dart:3565:5)
I/flutter ( 8787): #33     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3722:5)
I/flutter ( 8787): #34     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3864:11)
I/flutter ( 8787): #35     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3717:5)
I/flutter ( 8787): #36     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2961:14)
I/flutter ( 8787): #37     Element.updateChild (package:flutter/src/widgets/framework.dart:2764:12)
I/flutter ( 8787): #38     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3750:16)
I/flutter ( 8787): #39     Element.rebuild (package:flutter/src/widgets/framework.dart:3565:5)
I/flutter ( 8787): #40     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3722:5)
I/flutter ( 8787): #41     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3717:5)
I/flutter ( 8787): #42     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2961:14)
I/flutter ( 8787): #43     Element.updateChild (package:flutter/src/widgets/framework.dart:2764:12)
I/flutter ( 8787): #44     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3750:16)
I/flutter ( 8787): #45     Element.rebuild (package:flutter/src/widgets/framework.dart:3565:5)
I/flutter ( 8787): #46     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3722:5)
I/flutter ( 8787): #47     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3864:11)
I/flutter ( 8787): #48     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3717:5)
I/flutter ( 8787): #49     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2961:14)
I/flutter ( 8787): #50     Element.updateChild (package:flutter/src/widgets/framework.dart:2764:12)
I/flutter ( 8787): #51     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4876:14)
I/flutter ( 8787): #52     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2961:14)
I/flutter ( 8787): #53     Element.updateChild (package:flutter/src/widgets/framework.dart:2764:12)
I/flutter ( 8787): #54     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3750:16)
I/flutter ( 8787): #55     Element.rebuild (package:flutter/src/widgets/framework.dart:3565:5)
I/flutter ( 8787): #56     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3722:5)
I/flutter ( 8787): #57     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3717:5)
I/flutter ( 8787): #58     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2961:14)
I/flutter ( 8787): #59     Element.updateChild (package:flutter/src/widgets/framework.dart:2764:12)
I/flutter ( 8787): #60     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4876:14)
I/flutter ( 8787): #61     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2961:14)
I/flutter ( 8787): #62     Element.updateChild (package:flutter/src/widgets/framework.dart:2764:12)
I/flutter ( 8787): #63     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3750:16)
I/flutter ( 8787): #64     Element.rebuild (package:flutter/src/widgets/framework.dart:3565:5)
I/flutter ( 8787): #65     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3722:5)
I/flutter ( 8787): #66     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3864:11)
I/flutter ( 8787): #67     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3717:5)
I/flutter ( 8787): #68     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2961:14)
I/flutter ( 8787): #69     Element.updateChild (package:flutter/src/widgets/framework.dart:2764:12)
I/flutter ( 8787): #70     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3750:16)
I/flutter ( 8787): #71     Element.rebuild (package:flutter/src/widgets/framework.dart:3565:5)
I/flutter ( 8787): #72     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3722:5)
I/flutter ( 8787): #73     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3717:5)
I/flutter ( 8787): #74     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2961:14)
I/flutter ( 8787): #75     Element.updateChild (package:flutter/src/widgets/framework.dart:2764:12)
I/flutter ( 8787): #76     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4876:14)
I/flutter ( 8787): #77     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2961:14)
I/flutter ( 8787): #78     Element.updateChild (package:flutter/src/widgets/framework.dart:2764:12)
I/flutter ( 8787): #79     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3750:16)
I/flutter ( 8787): #80     Element.rebuild (package:flutter/src/widgets/framework.dart:3565:5)
I/flutter ( 8787): #81     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3722:5)
I/flutter ( 8787): #82     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3717:5)
I/flutter ( 8787): #83     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2961:14)
I/flutter ( 8787): #84     Element.updateChild (package:flutter/src/widgets/framework.dart:2764:12)
I/flutter ( 8787): #85     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3750:16)
I/flutter ( 8787): #86     Element.rebuild (package:flutter/src/widgets/framework.dart:3565:5)
I/flutter ( 8787): #87     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3722:5)
I/flutter ( 8787): #88     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3864:11)
I/flutter ( 8787): #89     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3717:5)
I/flutter ( 8787): #90     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2961:14)
I/flutter ( 8787): #91     Element.updateChild (package:flutter/src/widgets/framework.dart:2764:12)
I/flutter ( 8787): #92     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3750:16)
I/flutter ( 8787): #93     Element.rebuild (package:flutter/src/widgets/framework.dart:3565:5)
I/flutter ( 8787): #94     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3722:5)
I/flutter ( 8787): #95     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3864:11)
I/flutter ( 8787): #96     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3717:5)
I/flutter ( 8787): #97     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2961:14)
I/flutter ( 8787): #98     MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4982:32)
I/flutter ( 8787): #99     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2961:14)
I/flutter ( 8787): #100    Element.updateChild (package:flutter/src/widgets/framework.dart:2764:12)
I/flutter ( 8787): #101    _TheatreElement.mount (package:flutter/src/widgets/overlay.dart:593:16)
I/flutter ( 8787): #102    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2961:14)
I/flutter ( 8787): #103    Element.updateChild (package:flutter/src/widgets/framework.dart:2764:12)
I/flutter ( 8787): #104    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3750:16)
I/flutter ( 8787): #105    Element.rebuild (package:flutter/src/widgets/framework.dart:3565:5)
I/flutter ( 8787): #106    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3722:5)
I/flutter ( 8787): #107    StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3864:11)
I/flutter ( 8787): #108    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3717:5)
I/flutter ( 8787): #109    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2961:14)
I/flutter ( 8787): #110    Element.updateChild (package:flutter/src/widgets/framework.dart:2764:12)
I/flutter ( 8787): #111    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3750:16)
I/flutter ( 8787): #112    Element.rebuild (package:flutter/src/widgets/framework.dart:3565:5)
I/flutter ( 8787): #113    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3722:5)
I/flutter ( 8787): #114    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3717:5)
I/flutter ( 8787): #115    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2961:14)
I/flutter ( 8787): #116    Element.updateChild (package:flutter/src/widgets/framework.dart:2764:12)
I/flutter ( 8787): #117    SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4876:14)
I/flutter ( 8787): #118    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2961:14)
I/flutter ( 8787): #119    Element.updateChild (package:flutter/src/widgets/framework.dart:2764:12)
I/flutter ( 8787): #120    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3750:16)
I/flutter ( 8787): #121    Element.rebuild (package:flutter/src/widgets/framework.dart:3565:5)
I/flutter ( 8787): #122    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3722:5)
I/flutter ( 8787): #123    StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3864:11)
I/flutter ( 8787): #124    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3717:5)
I/flutter ( 8787): #125    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2961:14)
I/flutter ( 8787): #126    Element.updateChild (package:flutter/src/widgets/framework.dart:2764:12)
I/flutter ( 8787): #127    SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4876:14)
I/flutter ( 8787): #128    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2961:14)
I/flutter ( 8787): #129    Element.updateChild (package:flutter/src/widgets/framework.dart:2764:12)
I/flutter ( 8787): #130    SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4876:14)
I/flutter ( 8787): #131    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2961:14)
I/flutter ( 8787): #132    Element.updateChild (package:flutter/src/widgets/framework.dart:2764:12)
I/flutter ( 8787): #133    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3750:16)
I/flutter ( 8787): #134    Element.rebuild (package:flutter/src/widgets/framework.dart:3565:5)
I/flutter ( 8787): #135    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3722:5)
I/flutter ( 8787): #136    StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3864:11)
I/flutter ( 8787): #137    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3717:5)
I/flutter ( 8787): #138    Element.inflateWidget (package:flutter/src/widgets/framework.dart:2961:14)
I/flutter ( 8787): #139    Element.updateChild (package:flutter/src/widgets/framework.dart:2764:12)
I/flutter ( 8787): #140    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3750:16)
I/flutter ( 8787): #141    Element.rebuild (package:flutter/src/widgets/framework.dart:3565:5)
I/flutter ( 8787): #142    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3722:5)
I/flutter ( 8787): #143    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3717:5)
```

**Flutter Doctor**

```
[✓] Flutter (Channel stable, v1.5.4-hotfix.2, on Mac OS X 10.14.5 18F132, locale en-US)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[!] iOS toolchain - develop for iOS devices (Xcode 10.2.1)
    ✗ Verify that all connected devices have been paired with this computer in Xcode.
      If all devices have been paired, libimobiledevice and ideviceinstaller may require updating.
      To update with Brew, run:
        brew update
        brew uninstall --ignore-dependencies libimobiledevice
        brew uninstall --ignore-dependencies usbmuxd
        brew install --HEAD usbmuxd
        brew unlink usbmuxd
        brew link usbmuxd
        brew install --HEAD libimobiledevice
        brew install ideviceinstaller
[✓] Android Studio (version 3.4)
[!] IntelliJ IDEA Ultimate Edition (version 2019.1.1)
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
[!] IntelliJ IDEA Community Edition (version 2017.3.5)
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
[!] VS Code (version 1.33.1)
    ✗ Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter
[!] Connected device
    ! No devices available
```

**Comment by kangwang1988** [comment]
@shashkiranr 
BigInt is not allowed in json.encode.
Maybe you can try to convert the BigInt into a String so that it could be allowed. Besides, BigInt.tryParse can also parse a string into BigInt.

**Comment by shashkiranr** [comment]
@kangwang1988 I need to send the BigInt to a Rest API. it will not accept string that's where i am facing the issue.

**Comment by kangwang1988** [comment]
@shashkiranr 
You may try writing your own json encoder.

**Comment by timsneath** [comment]
Hi @shashkiranr -- thanks for filing the issue. The `json` class is part of the `dart:convert` package, which is a separate repo. In fact, this issue is already tracked there, but reading the log it seems like it's related to JSON limitations. See https://github.com/dart-lang/convert/issues/19 for more. Thanks for using Flutter!
