### ISSUE TITLE
Oops; flutter has exited unexpectedly.

### ISSUE THREAD

**Issue by nogamba** [flutter/flutter#33356]
## Steps to Reproduce

Running into this issue with flutter

1. running flutter doctor
2. resulting output:

Oops; flutter has exited unexpectedly.
Sending crash report to Google.

## Logs

Flutter crash report; please file at https://github.com/flutter/flutter/issues.

## command

flutter doctor

## exception

FileSystemException: FileSystemException: Cannot open file, path = 'C:\Users\flutter\version' (OS Error: Access is denied.
, errno = 5)

```
#0      _File.open.<anonymous closure> (dart:io/file_impl.dart:364:9)
#1      _rootRunUnary (dart:async/zone.dart:1132:38)
#2      _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#3      _FutureListener.handleValue (dart:async/future_impl.dart:126:18)
#4      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:639:45)
#5      Future._propagateToListeners (dart:async/future_impl.dart:668:32)
#6      Future._completeWithValue (dart:async/future_impl.dart:483:5)
#7      Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:513:7)
#8      _rootRun (dart:async/zone.dart:1124:13)
#9      _CustomZone.run (dart:async/zone.dart:1021:19)
#10     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:947:23)
#11     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#12     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#13     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:115:13)
#14     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:5)
```

## flutter doctor

```
[32m[✓][39m Flutter (Channel stable, v1.2.1, on Microsoft Windows [Version 10.0.17134.765], locale en-US)
    [32m•[39m Flutter version 1.2.1 at C:\Users\flutter
    [32m•[39m Framework revision 8661d8aecd (3 months ago), 2019-02-14 19:19:53 -0800
    [32m•[39m Engine revision 52c7a1e849
    [32m•[39m Dart version 2.3.0 (build 2.3.0-dev.0.5 a1668566e5)

[32m[✓][39m Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    [32m•[39m Android SDK at C:\Users\<username>\AppData\Local\Android\sdk
    [32m•[39m Android NDK location not configured (optional; useful for native profiling support)
    [32m•[39m Platform android-28, build-tools 28.0.3
    [32m•[39m Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    [32m•[39m Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
    [32m•[39m All Android licenses accepted.

[32m[✓][39m Android Studio (version 3.4)
    [32m•[39m Android Studio at C:\Program Files\Android\Android Studio
    [32m•[39m Flutter plugin version 35.3.1
    [32m•[39m Dart plugin version 183.6270
    [32m•[39m Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

[33m[!][39m IntelliJ IDEA Ultimate Edition (version 2019.1)
    [32m•[39m IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA 2019.1
    [31m✗[39m Flutter plugin not installed; this adds Flutter specific functionality.
    [31m✗[39m Dart plugin not installed; this adds Dart specific functionality.
    [32m•[39m For information about installing plugins, see
      https://flutter.dev/intellij-setup/#installing-the-plugins

[32m[✓][39m VS Code (version 1.34.0)
    [32m•[39m VS Code at C:\Users\<username>\AppData\Local\Programs\Microsoft VS Code
    [32m•[39m Flutter extension version 3.0.2

[33m[!][39m Connected device
    [33m![39m No devices available

[33m![39m Doctor found issues in 2 categories.
```

**Comment by mateuszmatyszkowicz** [comment]
@nogamba  This issue looks similar maybe comments there could help https://github.com/flutter/flutter/issues/25011

**Comment by nogamba** [comment]
Thank you.

I solved the issue by deleting the flutter directory from my Windows 10 PC, then removing path variables and reinstalling it. This seemed to work.
