### ISSUE TITLE
flutter run problem

### ISSUE THREAD

**Issue by ArtHoffmann** [flutter/flutter#33389]
Hello, 
currently i have the problem that i get the following message at flutter run.
i use Java 8 etc. 
I also have the problem that I don't get the lockfile deleted at Android Studio, it is added back to the folder every time I restart the program.

Thanks.

`Flutter crash report; please file at https://github.com/flutter/flutter/issues.

## command

flutter run

## exception

ProcessException: ProcessException: Process "C:\Users\xx\Desktop\test2\testproject2\android\gradlew.bat" exited abnormally:
Downloading https://services.gradle.org/distributions/gradle-4.10.2-all.zip

Exception in thread "main" java.net.ConnectException: Connection timed out: connect
	at java.net.DualStackPlainSocketImpl.connect0(Native Method)
	at java.net.DualStackPlainSocketImpl.socketConnect(DualStackPlainSocketImpl.java:79)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:172)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:673)
	at sun.security.ssl.BaseSSLSocketImpl.connect(BaseSSLSocketImpl.java:173)
	at sun.net.NetworkClient.doConnect(NetworkClient.java:180)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:432)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:527)
	at sun.net.www.protocol.https.HttpsClient.<init>(HttpsClient.java:264)
	at sun.net.www.protocol.https.HttpsClient.New(HttpsClient.java:367)
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(AbstractDelegateHttpsURLConnection.java:191)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1138)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1032)
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:177)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1546)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1474)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:254)
	at org.gradle.wrapper.Download.downloadInternal(Download.java:58)
	at org.gradle.wrapper.Download.download(Download.java:44)
	at org.gradle.wrapper.Install$1.call(Install.java:61)
	at org.gradle.wrapper.Install$1.call(Install.java:48)
	at org.gradle.wrapper.ExclusiveFileAccessManager.access(ExclusiveFileAccessManager.java:65)
	at org.gradle.wrapper.Install.createDist(Install.java:48)
	at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:128)
	at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:61)
  Command: C:\Users\xx\Desktop\test2\testproject2\android\gradlew.bat -v`

**Comment by ArtHoffmann** [comment]
The problem was solved, it was due to the proxy configuration of gradle.

systemProp.http.proxyHost=ip
systemProp.http.proxyPort=8080
systemProp.http.proxyUser=xxx
systemProp.http.proxyPassword=***
systemProp.https.proxyHost=ip
systemProp.https.proxyPort=8080
systemProp.https.proxyUser=xxx
systemProp.https.proxyPassword=***

**Comment by Bruskyer** [comment]
this is our first test app on flutter but not working because of gradle error during download gradle 4.10.2-all but can not. the above proxy setting for which configuration file ?

**Comment by ArtHoffmann** [comment]
Hello, Bruskyer,
you find the configuration file in C:\Users\x.y\.gradle\gradle.properties.

You can open and edit this file with notepad -> In the post above you can find the properties.

**Comment by Homebrew1** [comment]
遇到了同样的问题，问一下gradle怎么配置的,我找到了Flutter/examples/platform_channel/android/gradle.properties,请问有没有用
