### ISSUE TITLE
Oops; flutter has exited unexpectedly. Sending crash report to Google.

### ISSUE THREAD

**Issue by victoriavhe** [flutter/flutter#33415]
I get this error when I tried to run my app :

```Oops; flutter has exited unexpectedly.
Sending crash report to Google.
Crash report sent (report ID: 622616ae1d8b594c)
 
Crash report written to /Users/victoria/IdeaProjects/myporjectname/example/flutter_08.log;
Flutter crash report; please file at https://github.com/flutter/flutter/issues.

```

and below is the message inside flutter_08.log. 
please let me know what I should do. 

## command

flutter run

## exception

FileSystemException: FileSystemException: Creation failed, path = '/packages' (OS Error: Permission denied, errno = 13)

```
#0      _Directory.createSync (dart:io/directory_impl.dart:138:7)
#1      _Directory.createSync (dart:io/directory_impl.dart:133:16)
#2      _Directory.createSync (dart:io/directory_impl.dart:133:16)
#3      _LocalDirectory&LocalFileSystemEntity&ForwardingDirectory.createSync (package:file/src/forwarding/forwarding_directory.dart:22:16)
#4      writeBundle.<anonymous closure> (package:flutter_tools/src/bundle.dart:232:19)
<asynchronous suspension>
#5      MappedIterator.moveNext (dart:_internal/iterable.dart:392:18)
#6      Future.wait (dart:async/future.dart:393:26)
#7      writeBundle (package:flutter_tools/src/bundle.dart:229:16)
#8      _AsyncAwaitCompleter.start (dart:async-patch/async_patch.dart:49:6)
#9      writeBundle (package:flutter_tools/src/bundle.dart:221:25)
#10     assemble (package:flutter_tools/src/bundle.dart:217:9)
#11     _AsyncAwaitCompleter.start (dart:async-patch/async_patch.dart:49:6)
#12     assemble (package:flutter_tools/src/bundle.dart:185:22)
#13     build (package:flutter_tools/src/bundle.dart:150:9)
#14     _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:77:64)
#15     _rootRunUnary (dart:async/zone.dart:1132:38)
#16     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#17     _FutureListener.handleValue (dart:async/future_impl.dart:126:18)
#18     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:639:45)
#19     Future._propagateToListeners (dart:async/future_impl.dart:668:32)
#20     Future._complete (dart:async/future_impl.dart:473:7)
#21     _SyncCompleter.complete (dart:async/future_impl.dart:51:12)
#22     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:28:18)
#23     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:294:13)
#24     buildAssets (package:flutter_tools/src/bundle.dart)
#25     _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:77:64)
#26     _rootRunUnary (dart:async/zone.dart:1132:38)
#27     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#28     _FutureListener.handleValue (dart:async/future_impl.dart:126:18)
#29     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:639:45)
#30     Future._propagateToListeners (dart:async/future_impl.dart:668:32)
#31     Future._complete (dart:async/future_impl.dart:473:7)
#32     _SyncCompleter.complete (dart:async/future_impl.dart:51:12)
#33     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:28:18)
#34     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:294:13)
#35     _ManifestAssetBundle.build (package:flutter_tools/src/asset.dart)
#36     _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:77:64)
#37     _rootRunUnary (dart:async/zone.dart:1132:38)
#38     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#39     _FutureListener.handleValue (dart:async/future_impl.dart:126:18)
#40     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:639:45)
#41     Future._propagateToListeners (dart:async/future_impl.dart:668:32)
#42     Future._complete (dart:async/future_impl.dart:473:7)
#43     _SyncCompleter.complete (dart:async/future_impl.dart:51:12)
#44     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:28:18)
#45     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:294:13)
#46     _obtainLicenses (package:flutter_tools/src/asset.dart)
#47     _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:77:64)
#48     _rootRunUnary (dart:async/zone.dart:1132:38)
#49     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#50     _FutureListener.handleValue (dart:async/future_impl.dart:126:18)
#51     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:639:45)
#52     Future._propagateToListeners (dart:async/future_impl.dart:668:32)
#53     Future._completeWithValue (dart:async/future_impl.dart:483:5)
#54     Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:513:7)
#55     _rootRun (dart:async/zone.dart:1124:13)
#56     _CustomZone.run (dart:async/zone.dart:1021:19)
#57     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:947:23)
#58     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#59     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#60     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:115:13)
#61     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:5)
```

## flutter doctor

```
[32m[✓][39m Flutter (Channel master, v1.6.4-pre.18, on Mac OS X 10.14.5 18F132, locale en-US)
    [32m•[39m Flutter version 1.6.4-pre.18 at /Users/victoria/Library/flutter
    [32m•[39m Framework revision 323373d333 (13 hours ago), 2019-05-27 12:27:28 -0700
    [32m•[39m Engine revision 8dc3a4cde2
    [32m•[39m Dart version 2.3.2 (build 2.3.2-dev.0.0 e3edfd36b2)

[32m[✓][39m Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    [32m•[39m Android SDK at /Users/victoria/Library/Android/sdk
    [32m•[39m Android NDK location not configured (optional; useful for native profiling support)
    [32m•[39m Platform android-28, build-tools 28.0.3
    [32m•[39m Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    [32m•[39m Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)
    [32m•[39m All Android licenses accepted.

[32m[✓][39m Xcode - develop for iOS and macOS (Xcode 10.2.1)
    [32m•[39m Xcode at /Applications/Xcode.app/Contents/Developer
    [32m•[39m Xcode 10.2.1, Build version 10E1001
    [32m•[39m CocoaPods version 1.5.3

[33m[!][39m iOS tools - develop for iOS devices
    [31m✗[39m libimobiledevice and ideviceinstaller are not installed. To install with Brew, run:
        brew update
        brew install --HEAD usbmuxd
        brew link usbmuxd
        brew install --HEAD libimobiledevice
        brew install ideviceinstaller
    [32m•[39m ios-deploy 1.9.4

[32m[✓][39m Android Studio (version 3.3)
    [32m•[39m Android Studio at /Applications/Android Studio.app/Contents
    [32m•[39m Flutter plugin version 33.4.1
    [32m•[39m Dart plugin version 182.5215
    [32m•[39m Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)

[32m[✓][39m IntelliJ IDEA Ultimate Edition (version 2018.3.6)
    [32m•[39m IntelliJ at /Applications/IntelliJ IDEA.app
    [32m•[39m Flutter plugin version 35.3.1
    [32m•[39m Dart plugin version 183.6270

[32m[✓][39m VS Code (version 1.34.0)
    [32m•[39m VS Code at /Applications/Visual Studio Code.app/Contents
    [32m•[39m Flutter extension version 3.0.2

[32m[✓][39m Connected device (1 available)
    [32m•[39m iPhone Xʀ • 1A326011-2738-40C5-B74B-8936396C6373 • ios • com.apple.CoreSimulator.SimRuntime.iOS-12-2 (simulator)

[33m![39m Doctor found issues in 1 category.
```

**Comment by ashishlanghe90** [comment]
Same issue is with me...unable to open flutter in iOS
Did you resolve it..?

**Comment by iapicca** [comment]
Hi @victoriavhe 
are you still experiencing this issue with the latest version of Flutter?
If so can you please provide your `flutter doctor -v`?
Also, to better address the issue, would be helpful
if you could post a self contained app on github
or the steps to reproduce it.
Thank you

**Comment by iapicca** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
  
Thanks for your contribution.
