### ISSUE TITLE
Bad error message using AssetImage when missing MaterialApp / WidgetsApp

### ISSUE THREAD

**Issue by ianloic** [flutter/flutter#3341]
I forgot to include a MaterialApp in my tree and when I went to use an AssetImage I got:
```
assset bundle is: null
══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
The following exception was raised building AssetImage(name: lib/assets/f.png; height: 48.0):
The null object does not have a method 'loadImage'.

NoSuchMethodError: method not found: 'loadImage'
Receiver: null
Arguments: ["lib/assets/f.png"]
Stack trace:
#0      Object._noSuchMethod (dart:core-patch/object_patch.dart:42)
#1      Object.noSuchMethod (dart:core-patch/object_patch.dart:45)
#2      AssetImage.build (package:flutter/src/widgets/basic.dart:2302)
#3      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:1410)
#4      BuildableElement.rebuild (package:flutter/src/widgets/framework.dart:1344)
#5      ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:1396)
#6      ComponentElement.mount (package:flutter/src/widgets/framework.dart:1391)
#7      Element.inflateWidget (package:flutter/src/widgets/framework.dart:1022)
#8      Element.updateChild (package:flutter/src/widgets/framework.dart:904)
#9      SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:2043)
(etc)
```

@Hixie says it should have a better error message.

**Comment by Hixie** [comment]
We should either assert that there's a bundle and suggest that you need a MaterialApp, WidgetsApp, AssetVendor, or DefaultAssetBundle widget in your tree, or, we should move the default asset bundle logic from WidgetsApp to DefaultAssetBundle.of. Probably the latter.

**Comment by Hixie** [comment]
@ianloic let me know if you run into this again, in theory it should be fixed now
