### ISSUE TITLE
Flutter driver NoSuchMethodError: The method 'group' was called on null.

### ISSUE THREAD

**Issue by zadouyoune** [flutter/flutter#33428]
approvals_progress_page_test.dart
`

import 'dart:async';

import 'package:flutter_driver/flutter_driver.dart';
import 'package:test_api/test_api.dart';
void main() {

  group('scrolling performance test',() {
    FlutterDriver driver;

    setUpAll(() async {
      driver = await FlutterDriver.connect();
    });

    tearDownAll(() async {
      if (driver != null)
        driver.close();
    });

    test('measure', () async {
      final Timeline timeline = await driver.traceAction(() async {
        await driver.tap(find.text('Material'));

        final SerializableFinder demoList = find.byValueKey('ApprovalsPage');

        for (int i = 0; i < 5; i++) {
          await driver.scroll(demoList, 0.0, -300.0, const Duration(milliseconds: 300));
          await Future<void>.delayed(const Duration(milliseconds: 500));
        }

        // Scroll up
        for (int i = 0; i < 5; i++) {
        await driver.scroll(demoList, 0.0, 300.0, const Duration(milliseconds: 300));
        await Future<void>.delayed(const Duration(milliseconds: 500));
        }
      });

      TimelineSummary.summarize(timeline)
        ..writeSummaryToFile('home_scroll_perf', pretty: true)
        ..writeTimelineToFile('home_scroll_perf', pretty: true);
    });
  });
}

`

error:
`
Unhandled exception:
NoSuchMethodError: The method 'group' was called on null.
Receiver: null
Tried calling: group("scrolling performance test", Closure: () => Null, onPlatform: null, retry: null, skip: null, solo: false, tags: null, testOn: null, timeout: null)
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:50:5)
#1      group (package:test_api/test_api.dart:179:13)
#2      main (file://VSCode_workspace/hello_word/test_driver/approvals_progress_page_test.dart:9:3)
#3      _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:300:19)
#4      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:171:12)

`

**Comment by RedBrogdon** [comment]
Just ran into this myself. The issue is the way the test library is being imported:

```
import 'package:test_api/test_api.dart';
```

Changing that to a direct import of package test:

```
import 'package:test/test.dart';
```

solved the problem.

CC: @grouma, is there anything that can be done to improve the error message here?

**Comment by grouma** [comment]
I'm going to start a doc to brainstorm ideas.

I have one potential solution that isn't the best. We can mark the `test_api` library as deprecated with a warning that users should really be importing `package:test`. Of course this warning will be ignored by `package:test_core`, `package:test` and a few other packages that actually depend on `package:test_api`.
