### ISSUE TITLE
Strange background grey color in the first render of DatePicker

### ISSUE THREAD

**Issue by huangbao21** [flutter/flutter#33507]
## Steps to Reproduce

1.
```dart
.....
 ListTile(
                          onTap: () async {
                            DateTime dateTime = await showDatePicker(
                              locale: Locale('zh'),
                              context: context,
                              initialDate: DateTime.now(),
                              firstDate: DateTime(1900),
                              lastDate: DateTime(2030),
                              builder: (BuildContext context, Widget child) {
                                return Theme(
                                    data: ThemeData.light(), child: child);
                              },
                            );
                 .....
                 }
           }
```
2.  show DatePickerDialog
3. 
![image](https://user-images.githubusercontent.com/17422412/58544164-54d99780-8233-11e9-9fd8-104c2b3c4c02.png)
there was a grey color
4. close it, then open it again , it's normal
![image](https://user-images.githubusercontent.com/17422412/58544294-8f433480-8233-11e9-85c5-a41d4b252c74.png)

## Logs

```
[  +32 ms] executing: [D:\d\flutter\] git log -n 1 --pretty=format:%H
[ +109 ms] Exit code 0 from: git log -n 1 --pretty=format:%H
[   +2 ms] 6861c2cca0ac21380bede5e0565f7ca4ebda1f45
[   +1 ms] executing: [D:\d\flutter\] git describe --match v*.*.* --first-parent --long --tags
[ +132 ms] Exit code 0 from: git describe --match v*.*.* --first-parent --long --tags
[  +13 ms] v1.6.0-14-g6861c2cca
[  +11 ms] executing: [D:\d\flutter\] git rev-parse --abbrev-ref --symbolic @{u}
[  +90 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[   +2 ms] origin/master
[   +2 ms] executing: [D:\d\flutter\] git ls-remote --get-url origin
[  +83 ms] Exit code 0 from: git ls-remote --get-url origin
[   +3 ms] https://github.com/flutter/flutter.git
[ +129 ms] executing: [D:\d\flutter\] git rev-parse --abbrev-ref HEAD
[  +89 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[   +1 ms] master
[  +97 ms] executing: D:\d\Program Files\Android\Sdk\platform-tools\adb.exe devices -l
[  +68 ms] Exit code 0 from: D:\d\Program Files\Android\Sdk\platform-tools\adb.exe devices -l
[   +1 ms] List of devices attached
           37ff6895               device product:hero2qltezc model:SM_G9350 device:hero2qltechn transport_id:4
           emulator-5554          device product:sdk_phone_x86 model:Android_SDK_built_for_x86 device:generic_x86 transport_id:2
[  +59 ms] More than one device connected; please specify a device with the '-d <deviceId>' flag, or use '-d all' to act on all devices.
[   +5 ms] D:\d\Program Files\Android\Sdk\platform-tools\adb.exe -s 37ff6895 shell getprop
[ +179 ms] ro.hardware = qcom
[   +2 ms] D:\d\Program Files\Android\Sdk\platform-tools\adb.exe -s emulator-5554 shell getprop
[  +69 ms] ro.hardware = ranchu
[   +3 ms] SM G9350                  • 37ff6895      • android-arm64 • Android 8.0.0 (API 26)
[   +1 ms] Android SDK built for x86 • emulator-5554 • android-x86   • Android 9 (API 28) (emulator)
[  +11 ms] "flutter run" took 586ms.
[        ] "flutter run" took 586ms.

#0      throwToolExit (package:flutter_tools/src/base/common.dart:24:3)
#1      RunCommand.validateCommand (package:flutter_tools/src/commands/run.dart:257:7)
<asynchronous suspension>
#2      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:467:11)
<asynchronous suspension>
#3      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:424:33)
<asynchronous suspension>
#4      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:29)
<asynchronous suspension>
#5      _rootRun (dart:async/zone.dart:1124:13)
#6      _CustomZone.run (dart:async/zone.dart:1021:19)
#7      _runZoned (dart:async/zone.dart:1516:10)
#8      runZoned (dart:async/zone.dart:1463:12)
#9      AppContext.run (package:flutter_tools/src/base/context.dart:152:18)
<asynchronous suspension>
#10     FlutterCommand.run (package:flutter_tools/src/runner/flutter_command.dart:415:20)
#11     CommandRunner.runCommand (package:args/command_runner.dart:196:27)
<asynchronous suspension>
#12     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:396:21)
<asynchronous suspension>
#13     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:29)
<asynchronous suspension>
#14     _rootRun (dart:async/zone.dart:1124:13)
#15     _CustomZone.run (dart:async/zone.dart:1021:19)
#16     _runZoned (dart:async/zone.dart:1516:10)
#17     runZoned (dart:async/zone.dart:1463:12)
#18     AppContext.run (package:flutter_tools/src/base/context.dart:152:18)
<asynchronous suspension>
#19     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:356:19)
<asynchronous suspension>
#20     CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:111:29)
#21     new Future.sync (dart:async/future.dart:224:31)
#22     CommandRunner.run (package:args/command_runner.dart:111:11)
#23     FlutterCommandRunner.run (package:flutter_tools/src/runner/flutter_command_runner.dart:242:18)
#24     run.<anonymous closure> (package:flutter_tools/runner.dart:60:20)
<asynchronous suspension>
#25     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:29)
<asynchronous suspension>
#26     _rootRun (dart:async/zone.dart:1124:13)
#27     _CustomZone.run (dart:async/zone.dart:1021:19)
#28     _runZoned (dart:async/zone.dart:1516:10)
#29     runZoned (dart:async/zone.dart:1463:12)
#30     AppContext.run (package:flutter_tools/src/base/context.dart:152:18)
<asynchronous suspension>
#31     runInContext (package:flutter_tools/src/context_runner.dart:52:24)
<asynchronous suspension>
#32     run (package:flutter_tools/runner.dart:51:10)
#33     main (package:flutter_tools/executable.dart:59:9)
<asynchronous suspension>
#34     main (file:///D:/d/flutter/packages/flutter_tools/bin/flutter_tools.dart:8:3)
#35     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:298:32)
#36     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:171:12)
```

```
No issues found! (ran in 10.7s)
```

```
[√] Flutter (Channel master, v1.6.1-pre.14, on Microsoft Windows [Version 10.0.17763.503], locale zh-CN)
    • Flutter version 1.6.1-pre.14 at D:\d\flutter
    • Framework revision 6861c2cca0 (13 days ago), 2019-05-15 20:47:39 -0400
    • Engine revision dd65a8884e
    • Dart version 2.3.1 (build 2.3.1-dev.0.0 57c970d87a)


[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at D:\d\Program Files\Android\Sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = D:\d\Program Files\Android\Sdk
    • Java binary at: D:\d\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)
    • All Android licenses accepted.

[√] Android Studio (version 3.3)
    • Android Studio at D:\d\Program Files\Android\Android Studio
    • Flutter plugin version 32.0.1
    • Dart plugin version 182.5215
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)

[√] IntelliJ IDEA Ultimate Edition (version 2018.1)
    • IntelliJ at D:\d\Program Files\JetBrains\IntelliJ IDEA 2018.1.1
    • Flutter plugin version 31.3.1
    • Dart plugin version 181.4445.29

[√] Connected device (2 available)
    • SM G9350                  • 37ff6895      • android-arm64 • Android 8.0.0 (API 26)
    • Android SDK built for x86 • emulator-5554 • android-x86   • Android 9 (API 28) (emulator)

• No issues found!
```
Otherwise, if I checkout stable branch, it doesn't have this trouble. But the DataPicker's header will spill 5px

**Comment by TahaTesser** [comment]
Hi @huangbao21 
Does this issue still occurs for you?

**Comment by huangbao21** [comment]
OK，I forgot to close it
