### ISSUE TITLE
Failed assertion: 'notification.metrics.axis == widget.axis' when using nested Scrollable

### ISSUE THREAD

**Issue by aryzhov** [flutter/flutter#33504]
I was working on a Grid widget that can be scrolled horizontally and vertically. I used a `Scrollable` for vertical scrolling and a `SliverFixedExtentList` for horizontal scrolling. That solution has worked, except for occasional assertion errors when the grid is scrolled right to the very end, or left to the very beginning:

```bash
I/flutter (16512): ══╡ EXCEPTION CAUGHT BY ANIMATION LIBRARY ╞═════════════════════════════════════════════════════════
I/flutter (16512): The following assertion was thrown while notifying listeners for AnimationController:
I/flutter (16512): 'package:flutter/src/widgets/overscroll_indicator.dart': Failed assertion: line 177 pos 14:
I/flutter (16512): 'notification.metrics.axis == widget.axis': is not true.
I/flutter (16512): 
I/flutter (16512): Either the assertion indicates an error in the framework itself, or we should provide substantially
I/flutter (16512): more information in this error message to help you determine and fix the underlying cause.
I/flutter (16512): In either case, please report this assertion by filing a bug on GitHub:
I/flutter (16512):   https://github.com/flutter/flutter/issues/new?template=BUG.md
I/flutter (16512): 
I/flutter (16512): When the exception was thrown, this was the stack:
I/flutter (16512): #2      _GlowingOverscrollIndicatorState._handleScrollNotification (package:flutter/src/widgets/overscroll_indicator.dart:177:14)
I/flutter (16512): #3      NotificationListener._dispatch (package:flutter/src/widgets/notification_listener.dart:127:27)
I/flutter (16512): #4      Notification.visitAncestor (package:flutter/src/widgets/notification_listener.dart:45:20)
I/flutter (16512): #5      _ScrollNotification&LayoutChangedNotification&ViewportNotificationMixin.visitAncestor (package:flutter/src/widgets/scroll_notification.dart:31:18)
I/flutter (16512): #6      Element.visitAncestorElements (package:flutter/src/widgets/framework.dart:3447:39)
I/flutter (16512): #7      Notification.dispatch (package:flutter/src/widgets/notification_listener.dart:61:13)
I/flutter (16512): #8      BallisticScrollActivity.dispatchOverscrollNotification (package:flutter/src/widgets/scroll_activity.dart:556:108)
I/flutter (16512): #9      ScrollPosition.didOverscrollBy (package:flutter/src/widgets/scroll_position.dart:675:14)
I/flutter (16512): #10     ScrollPosition.setPixels (package:flutter/src/widgets/scroll_position.dart:222:9)
I/flutter (16512): #11     ScrollPositionWithSingleContext.setPixels (package:flutter/src/widgets/scroll_position_with_single_context.dart:84:18)
I/flutter (16512): #12     BallisticScrollActivity.applyMoveTo (package:flutter/src/widgets/scroll_activity.dart:547:21)
I/flutter (16512): #13     BallisticScrollActivity._tick (package:flutter/src/widgets/scroll_activity.dart:534:10)
I/flutter (16512): #14     _AnimationController&Animation&AnimationEagerListenerMixin&AnimationLocalListenersMixin.notifyListeners (package:flutter/src/animation/listener_helpers.dart:126:19)
I/flutter (16512): #15     AnimationController._tick (package:flutter/src/animation/animation_controller.dart:765:5)
I/flutter (16512): #16     Ticker._tick (package:flutter/src/scheduler/ticker.dart:228:5)
I/flutter (16512): #17     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1012:15)
I/flutter (16512): #18     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.handleBeginFrame.<anonymous closure> (package:flutter/src/scheduler/binding.dart:928:11)
I/flutter (16512): #19     __InternalLinkedHashMap&_HashVMBase&MapMixin&_LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:367:8)
I/flutter (16512): #20     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.handleBeginFrame (package:flutter/src/scheduler/binding.dart:926:17)
I/flutter (16512): #21     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._handleBeginFrame (package:flutter/src/scheduler/binding.dart:856:5)
I/flutter (16512): #25     _invoke1 (dart:ui/hooks.dart:234:10)
I/flutter (16512): #26     _beginFrame (dart:ui/hooks.dart:172:3)
I/flutter (16512): (elided 5 frames from class _AssertionError and package dart:async)
I/flutter (16512): 
I/flutter (16512): The AnimationController notifying listeners was:
I/flutter (16512):   AnimationController#2c4ff(▶ 1589.129; for BallisticScrollActivity)
I/flutter (16512): ════════════════════════════════════════════════════════════════════════════════════════════════════
```
The error occurs only on Android. iOS works fine. 

## To Reproduce
Copy the following to `lib/main.dart` and run on an Android:

```dart
import 'package:flutter/material.dart';
import 'package:flutter/rendering.dart';

void main() {
  runApp(SampleApp());
}

class SampleApp extends StatefulWidget {
  @override
  _SampleAppState createState() => new _SampleAppState();
}

class _SampleAppState extends State<SampleApp> {

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        appBar: AppBar(
          title: Text('Sample App'),
        ),
        body: Grid(50, 25, 80, 50),
      ),
    );
  }
}

class Grid extends StatelessWidget {

  final double columnWidth;
  final double rowHeight;
  final int rows;
  final int columns;
  
  Grid(this.rows, this.columns, this.columnWidth, this.rowHeight);

  @override
  Widget build(BuildContext context) {
    return Scrollable(
      semanticChildCount: rows,
      axisDirection: AxisDirection.down,
      viewportBuilder: (context, offset) {
        return CustomScrollView(
          scrollDirection: Axis.horizontal,
          slivers: [
            SliverFixedExtentList(
              itemExtent: columnWidth,
              delegate: SliverChildBuilderDelegate(
                (context, column) => GridColumn(rows, rowHeight, column, offset),
                childCount: columns,
              ),
            )
          ]
        );
      },
    );
  }
}

class GridColumn extends StatelessWidget {

  final int rows;
  final int column;
  final double rowHeight;
  final ViewportOffset offset;

  GridColumn(this.rows, this.rowHeight, this.column, this.offset);

  @override
  Widget build(BuildContext context) {
    return Container(
      decoration: BoxDecoration(
        border: Border(
          right: BorderSide(color: Colors.black, width: 1, ),
        ),
      ),
      child: Viewport(
        offset: this.offset,
        slivers: <Widget>[
          SliverFixedExtentList(
            itemExtent: rowHeight,
            delegate: SliverChildBuilderDelegate(
              (context, row) {
                return Container(
                  decoration: BoxDecoration(
                    border: Border(
                      bottom: BorderSide(color: Colors.black, width: 1, ),
                    ),
                  ),
                  child: Center(child: Text("$row:$column")),
                );
              },
              childCount: rows,
            ),
          ),
        ],
      ),
    );
  }
}
```

## Workaround
I found a workaround that involves putting a `NotificationListener` between the two `Scrollable`s to suppress occasional `OverscrollNotification` events that get propagated to the outer `Scrollable`:

```dart
  @override
  Widget build(BuildContext context) {
    return Scrollable(
      semanticChildCount: rows,
      axisDirection: AxisDirection.down,
      viewportBuilder: (context, offset) {
        return NotificationListener<OverscrollNotification>(
          // Suppress OverscrollNotification events that escape from the inner scrollable
          onNotification: (notification) => notification.metrics.axisDirection != AxisDirection.down,
          child: CustomScrollView(
            scrollDirection: Axis.horizontal,
            slivers: [
              SliverFixedExtentList(
                itemExtent: columnWidth,
                delegate: SliverChildBuilderDelegate(
                  (context, column) => GridColumn(rows, rowHeight, column, offset),
                  childCount: columns,
                ),
              )
            ]
          ),
        );
      },
    );
```
Note that the workaround is not a perfect solution because overscroll events could be useful if there is another Scrollable that contains the grid, for example a `TabView`. The fix could be as simple as replacing the failing `assert` with a `if(...) return false`.  

## flutter doctor

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel dev, v1.6.5, on Mac OS X 10.14.4 18E227, locale en-US)

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 10.2.1)
[✓] iOS tools - develop for iOS devices
[✓] Android Studio (version 3.4)
[✓] VS Code (version 1.34.0)
[✓] Connected device (3 available)

• No issues found!
```

**Comment by TahaTesser** [comment]
Hi @aryzhov 
Can't reproduce it on the latest `stable` or `master`, on several tries 

<details> 
<summary>multiple flutter doctor -v</summary> 

```bash
[✓] Flutter (Channel stable, 1.22.5, on macOS 11.1 20C69 darwin-x64, locale
    en-GB)
    • Flutter version 1.22.5 at /Users/tahatesser/Code/flutter_stable
    • Framework revision 7891006299 (6 days ago), 2020-12-10 11:54:40 -0800
    • Engine revision ae90085a84
    • Dart version 2.10.4

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/tahatesser/Code/sdk
    • Platform android-30, build-tools 30.0.2
    • ANDROID_HOME = /Users/tahatesser/Code/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.3)
    • Xcode at /Volumes/Extreme/Xcode.app/Contents/Developer
    • Xcode 12.3, Build version 12C33
    • CocoaPods version 1.10.0

[!] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.52.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.17.0

[✓] Connected device (3 available)
    • RMX2001 (mobile)     • EUYTFEUSQSRGDA6D                     •
      android-arm64 • Android 10 (API 29)
    • Taha’s iPad (mobile) • 00008020-000255113EE8402E            • ios
      • iOS 14.3
    • iPhone 12 (mobile)   • 01685E98-F396-4EB9-9C58-8B92677E24D5 • ios
      • com.apple.CoreSimulator.SimRuntime.iOS-14-3 (simulator)

! Doctor found issues in 1 category.
```

```bash
[✓] Flutter (Channel master, 1.25.0-9.0.pre.87, on macOS 11.1 20C69 darwin-x64,
    locale en-GB)
    • Flutter version 1.25.0-9.0.pre.87 at /Users/tahatesser/Code/flutter_master
    • Framework revision 1abe1d4c61 (3 hours ago), 2020-12-16 02:28:03 -0500
    • Engine revision 0445f7985e
    • Dart version 2.12.0 (build 2.12.0-155.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/tahatesser/Code/sdk
    • Platform android-30, build-tools 30.0.2
    • ANDROID_HOME = /Users/tahatesser/Code/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.3)
    • Xcode at /Volumes/Extreme/Xcode.app/Contents/Developer
    • Xcode 12.3, Build version 12C33
    • CocoaPods version 1.10.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)

[!] Android Studio
    • Android Studio at /Applications/Android/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    ✗ Android Studio not found at /Applications/Android/Contents
    • Try updating or re-installing Android Studio.

[✓] VS Code (version 1.52.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.17.0

[✓] Connected device (5 available)
    • RMX2001 (mobile)     • EUYTFEUSQSRGDA6D                     •
      android-arm64  • Android 10 (API 29)
    • Taha’s iPad (mobile) • 00008020-000255113EE8402E            • ios
      • iOS 14.3
    • iPhone 12 (mobile)   • 01685E98-F396-4EB9-9C58-8B92677E24D5 • ios
      • com.apple.CoreSimulator.SimRuntime.iOS-14-3 (simulator)
    • macOS (desktop)      • macos                                • darwin-x64
      • macOS 11.1 20C69 darwin-x64
    • Chrome (web)         • chrome                               •
      web-javascript • Google Chrome 87.0.4280.88

! Doctor found issues in 1 category.
```


</details>

If you can still reproduce it, Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

**Comment by fzyzcjy** [comment]
I can reproduce it. Thanks for the workaround, works for me!
