### ISSUE TITLE
unsupported multiclient unsolicited response code 1009 Unhandled exception:

### ISSUE THREAD

**Issue by khushwaqt** [flutter/flutter#33503]
## Steps to Reproduce

1-Installed flutter plug in from File -->Settings --> Plugin and install latest flutter plugin.
2- After that I created a new flutter project from android studio , which prompted me to install flutter SDK. I install flutter SDK and add the path.
3- Then i connected a device to the PC and run the application. I tried running it from android studio terminal here are the result. 

## Logs
```
Microsoft Windows [Version 10.0.17763.503]
(c) 2018 Microsoft Corporation. All rights reserved.

H:\AndroidStudio\timer>flutter run
Error retrieving device properties for ro.product.cpu.abi:

Launching lib/main.dart on SM G355H in debug mode...
Initializing gradle...                                              1.5s
Resolving dependencies...                                           7.2s
--------- beginning of /dev/log/main
--------- beginning of /dev/log/system
05-29 11:57:43.359 E/        (  173): unsupported multiclient unsolicited response code 1009
Unhandled exception:
Exit code -1073740940 from: C:\Users\imran.ali\AppData\Local\Android\sdk\platform-tools\adb.exe -s 4203c933c40d4100 shell -x logcat -v time -t 1
#0      _runWithLoggingSync (package:flutter_tools/src/base/process.dart:360:7)
#1      runCheckedSync (package:flutter_tools/src/base/process.dart:289:10)
#2      AndroidDevice.lastLogcatTimestamp (package:flutter_tools/src/android/android_device.dart:513:27)
#3      _AdbLogReader._start (package:flutter_tools/src/android/android_device.dart:688:41)
#4      _runGuarded (dart:async/stream_controller.dart:805:24)
#5      _BroadcastStreamController._subscribe (dart:async/broadcast_stream_controller.dart:213:7)
#6      _ControllerStream._createSubscription (dart:async/stream_controller.dart:818:19)
#7      _StreamImpl.listen (dart:async/stream_impl.dart:472:9)
#8      FlutterDevice.startEchoingDeviceLog (package:flutter_tools/src/resident_runner.dart:318:71)
#9      FlutterDevice.runHot (package:flutter_tools/src/resident_runner.dart:361:5)
<asynchronous suspension>
#10     HotRunner.run (package:flutter_tools/src/run_hot.dart:253:39)
<asynchronous suspension>
#11     RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:428:37)
<asynchronous suspension>
#12     FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:559:18)
#13     _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:77:64)
#14     _rootRunUnary (dart:async/zone.dart:1132:38)
#15     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#16     _FutureListener.handleValue (dart:async/future_impl.dart:126:18)
#17     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:639:45)
#18     Future._propagateToListeners (dart:async/future_impl.dart:668:32)
#19     Future._complete (dart:async/future_impl.dart:473:7)
#20     _SyncCompleter.complete (dart:async/future_impl.dart:51:12)
#21     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:28:18)
#22     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:294:13)
#23     RunCommand.usageValues (package:flutter_tools/src/commands/run.dart)
#24     _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:77:64)
#25     _rootRunUnary (dart:async/zone.dart:1132:38)
#26     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#27     _FutureListener.handleValue (dart:async/future_impl.dart:126:18)
#28     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:639:45)
#29     Future._propagateToListeners (dart:async/future_impl.dart:668:32)
#30     Future._complete (dart:async/future_impl.dart:473:7)
#31     _SyncCompleter.complete (dart:async/future_impl.dart:51:12)
#32     _AsyncAwaitCompleter.complete.<anonymous closure> (dart:async-patch/async_patch.dart:33:20)
#33     _rootRun (dart:async/zone.dart:1124:13)
#34     _CustomZone.run (dart:async/zone.dart:1021:19)
#35     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:947:23)
#36     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#37     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#38     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:115:13)
#39     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:5)
```

```
```

```
H:\AndroidStudio\timer>flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel beta, v1.5.4-hotfix.2, on Microsoft Windows [Version 10.0.17763.503], locale en-US)

[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[√] Android Studio (version 3.4)

Scanning for devices is taking a long time...-Error retrieving device properties for ro.product.cpu.abi:

[√] Connected device (1 available)

• No issues found!

H:\AndroidStudio\timer>flutter doctor -v
[√] Flutter (Channel beta, v1.5.4-hotfix.2, on Microsoft Windows [Version 10.0.17763.503], locale en-US)
    • Flutter version 1.5.4-hotfix.2 at H:\flutterSdk\flutter
    • Framework revision 7a4c33425d (4 weeks ago), 2019-04-29 11:05:24 -0700
    • Engine revision 52c7a1e849
    • Dart version 2.3.0 (build 2.3.0-dev.0.5 a1668566e5)


Checking Android licenses is taking an unexpectedly long time...-Error retrieving device properties for ro.product.cpu.abi:

[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at C:\Users\imran.ali\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
    • All Android licenses accepted.

[√] Android Studio (version 3.4)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 35.3.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

[√] Connected device (1 available)
    • SM G355H • 4203c933c40d4100 • android-arm • Android null (API null)

• No issues found!

```
```
```
Already tried multiple options. Tried with emulator changing the device, restarting the IDE and PC as well. Adding ADBto path. But nothing worked.

**Comment by DanTup** [comment]
This looks like the same issue as https://github.com/flutter/flutter/issues/33938. There's a PR at https://github.com/flutter/flutter/pull/33951 that should fix this.
