### ISSUE TITLE
Flutter Tool crashed unexpectedly when running "flutter test", Deletion failed, path = 'build\unit_test_assets', errno = 145

### ISSUE THREAD

**Issue by JSANL** [flutter/flutter#33536]
## command

flutter test test\notifications\fcm_notification_test.dart

## exception

FileSystemException: FileSystemException: Deletion failed, path = 'build\unit_test_assets' (OS Error: Das Verzeichnis ist nicht leer.
, errno = 145)

"Das Verzeichnis ist nicht leer." means "the directory is not empty".

```
#0      _Directory._deleteSync (dart:io/directory_impl.dart:206:7)
#1      FileSystemEntity.deleteSync (dart:io/file_system_entity.dart:466:47)
#2      ForwardingFileSystemEntity.deleteSync (package:file/src/forwarding/forwarding_file_system_entity.dart:72:16)
#3      writeBundle (package:flutter_tools/src/bundle.dart:232:15)
<asynchronous suspension>
#4      TestCommand._buildTestAsset (package:flutter_tools/src/commands/test.dart:242:11)
<asynchronous suspension>
#5      TestCommand.runCommand (package:flutter_tools/src/commands/test.dart:130:13)
<asynchronous suspension>
#6      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:142:29)
<asynchronous suspension>
#7      _rootRun (dart:async/zone.dart:1124:13)
#8      _CustomZone.run (dart:async/zone.dart:1021:19)
#9      _runZoned (dart:async/zone.dart:1516:10)
#10     runZoned (dart:async/zone.dart:1463:12)
#11     AppContext.run (package:flutter_tools/src/base/context.dart:141:18)
<asynchronous suspension>
#12     FastFlutterCommand.run (package:flutter_tools/src/runner/flutter_command.dart:780:20)
#13     CommandRunner.runCommand (package:args/command_runner.dart:196:27)
<asynchronous suspension>
#14     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:396:21)
<asynchronous suspension>
#15     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:142:29)
<asynchronous suspension>
#16     _rootRun (dart:async/zone.dart:1124:13)
#17     _CustomZone.run (dart:async/zone.dart:1021:19)
#18     _runZoned (dart:async/zone.dart:1516:10)
#19     runZoned (dart:async/zone.dart:1463:12)
#20     AppContext.run (package:flutter_tools/src/base/context.dart:141:18)
<asynchronous suspension>
#21     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:356:19)
<asynchronous suspension>
#22     CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:111:29)
#23     new Future.sync (dart:async/future.dart:224:31)
#24     CommandRunner.run (package:args/command_runner.dart:111:11)
#25     FlutterCommandRunner.run (package:flutter_tools/src/runner/flutter_command_runner.dart:242:18)
#26     run.<anonymous closure> (package:flutter_tools/runner.dart:60:20)
<asynchronous suspension>
#27     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:142:29)
<asynchronous suspension>
#28     _rootRun (dart:async/zone.dart:1124:13)
#29     _CustomZone.run (dart:async/zone.dart:1021:19)
#30     _runZoned (dart:async/zone.dart:1516:10)
#31     runZoned (dart:async/zone.dart:1463:12)
#32     AppContext.run (package:flutter_tools/src/base/context.dart:141:18)
<asynchronous suspension>
#33     runInContext (package:flutter_tools/src/context_runner.dart:50:24)
<asynchronous suspension>
#34     run (package:flutter_tools/runner.dart:51:10)
#35     main (package:flutter_tools/executable.dart:60:9)
<asynchronous suspension>
#36     main (file:///E:/Development/flutter/packages/flutter_tools/bin/flutter_tools.dart:8:3)
#37     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:298:32)
#38     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:171:12)
```

## flutter doctor

```
[32m[✓][39m Flutter (Channel beta, v1.5.4-hotfix.2, on Microsoft Windows [Version 10.0.17134.765], locale de-DE)
    [32m•[39m Flutter version 1.5.4-hotfix.2 at E:\Development\flutter
    [32m•[39m Framework revision 7a4c33425d (4 weeks ago), 2019-04-29 11:05:24 -0700
    [32m•[39m Engine revision 52c7a1e849
    [32m•[39m Dart version 2.3.0 (build 2.3.0-dev.0.5 a1668566e5)

[32m[✓][39m Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    [32m•[39m Android SDK at E:\Development\Android_SDK
    [32m•[39m Android NDK location not configured (optional; useful for native profiling support)
    [32m•[39m Platform android-28, build-tools 28.0.3
    [32m•[39m Java binary at: E:\Development\Android Studio\jre\bin\java
    [32m•[39m Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)
    [32m•[39m All Android licenses accepted.

[32m[✓][39m Android Studio (version 3.2)
    [32m•[39m Android Studio at E:\Development\Android Studio
    [32m•[39m Flutter plugin version 29.1.1
    [32m•[39m Dart plugin version 181.5656
    [32m•[39m Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)

[33m[!][39m Connected device
    [33m![39m No devices available

[33m![39m Doctor found issues in 1 category.
```

**Comment by jmagman** [comment]
Similar to https://github.com/flutter/flutter/issues/45265.

**Comment by jonahwilliams** [comment]
Tentatively de-duping into https://github.com/flutter/flutter/issues/50880
