### ISSUE TITLE
MacOS builds can swallow errors in non-verbose mode

### ISSUE THREAD

**Issue by stuartmorgan** [flutter/flutter#33582]
Non-verbose builds often don't have useful information about build failures. It would be helpful to run the build output through processing to try to extract errors.

**Comment by stuartmorgan** [comment]
As a recent example: if `build bundle` fails inside the tool_backend script, there are no useful failure messages in non-verbose build.

**Comment by johannesvuorinen** [comment]
This started to happen to us after upgrading to Flutter 1.20 from 1.17.

**Comment by stuartmorgan** [comment]
This was fixed by https://github.com/flutter/flutter/pull/63815

**Comment by tvolkert** [comment]
Reopening this since I just witnessed it with null safety errors.

Build output when verbose logging was enabled: https://gist.github.com/tvolkert/15b96a879c7c1faa43efe47c7797d93c

Relevant snippet is:

```
[+1079 ms] Error: This project cannot run with sound null safety, because one or more project dependencies do not
[        ] support null safety:
[        ]  - package:http
[        ]  - package:intl
[        ]  - package:http_parser
```

... but when run without verbose logging enabled, all I saw was:

```
$ flutter run -d macos
Running "flutter pub get" in payouts...                            474ms
Launching lib/main.dart on macOS in debug mode...
Running pod install...                                           1,404ms
ld: framework not found App                                             
clang: error: linker command failed with exit code 1 (use -v to see invocation)
note: Using new build system                                            
note: Planning build                                                    
note: Constructing build description                                    
** BUILD FAILED **                                                      
                                                                        
Building macOS application...                                           
Exception: Build process failed
```

Version info:

```
[✓] Flutter (Channel master, 1.24.0-8.0.pre.153, on Mac OS X 10.15.3 19D76 darwin-x64, locale en-US)
    • Flutter version 1.24.0-8.0.pre.153 at /Users/tvolkert/project/flutter/flutter
    • Framework revision 99e0d3b9cf (5 hours ago), 2020-11-09 10:54:49 -0800
    • Engine revision 3cf2922269
    • Dart version 2.12.0 (build 2.12.0-28.0.dev)
```

**Comment by tvolkert** [comment]
Just ran into this again at ToT.  The following error was swallowed in non-verbose mode but shows up in the verbose logs:

```
[ +437 ms] lib/src/pivot/basic_list_view.dart:384:37: Error: A value of type 'Object?' can't be assigned to a variable of type 'ListViewSlot'.
[        ]  - 'Object' is from 'dart:core'.
[        ]  - 'ListViewSlot' is from 'package:payouts/src/pivot/basic_list_view.dart' ('lib/src/pivot/basic_list_view.dart').
[        ]     final ListViewSlot slot = child.slot;
[        ]                                     ^
[  +14 ms] lib/src/pivot/basic_table_view.dart:545:38: Error: A value of type 'Object?' can't be assigned to a variable of type 'TableViewSlot'.
[        ]  - 'Object' is from 'dart:core'.
[        ]  - 'TableViewSlot' is from 'package:payouts/src/pivot/basic_table_view.dart' ('lib/src/pivot/basic_table_view.dart').
[        ]     final TableViewSlot slot = child.slot;
[        ]                                      ^
[+5364 ms] [+5816 ms] lib/src/pivot/basic_list_view.dart:384:37: Error: A value of type 'Object?' can't be assigned to a variable of type 'ListViewSlot'.
[        ] [   +1 ms]  - 'Object' is from 'dart:core'.
[        ] [        ]  - 'ListViewSlot' is from 'package:payouts/src/pivot/basic_list_view.dart' ('lib/src/pivot/basic_list_view.dart').
[        ] [        ]     final ListViewSlot slot = child.slot;
[        ] [        ]                                     ^
[  +16 ms] [  +16 ms] lib/src/pivot/basic_table_view.dart:545:38: Error: A value of type 'Object?' can't be assigned to a variable of type 'TableViewSlot'.
[        ] [        ]  - 'Object' is from 'dart:core'.
[        ] [        ]  - 'TableViewSlot' is from 'package:payouts/src/pivot/basic_table_view.dart' ('lib/src/pivot/basic_table_view.dart').
[        ] [        ]     final TableViewSlot slot = child.slot;
```

/cc @cbracken

**Comment by jmagman** [comment]
I think you're seeing something much worse @tvolkert, and I don't seen an immediate duplicate for it.
`assemble` is failing (from his logs):
```
[        ]            <asynchronous suspension>
[  +11 ms] [  +13 ms] "flutter assemble" took 10,707ms.
[   +6 ms] [   +6 ms] 
[        ]            #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
[        ]            #1      AssembleCommand.runCommand (package:flutter_tools/src/commands/assemble.dart:307:7)
[        ]            <asynchronous suspension>
[        ]            #2      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1036:27)
[        ]            <asynchronous suspension>
[        ]            #3      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:152:19)
[        ]            <asynchronous suspension>
[        ]            #4      CommandRunner.runCommand (package:args/command_runner.dart:197:13)
[        ]            <asynchronous suspension>
[        ]            #5      FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:283:9)
[        ]            <asynchronous suspension>
[        ]            #6      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:152:19)
[        ]            <asynchronous suspension>
[        ]            #7      FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:239:5)
[        ]            <asynchronous suspension>
[        ]            #8      run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:62:9)
[        ]            <asynchronous suspension>
[        ]            #9      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:152:19)
[        ]            <asynchronous suspension>
[        ]            #10     main (package:flutter_tools/executable.dart:92:3)
[        ]            <asynchronous suspension>
[ +253 ms] [ +255 ms] ensureAnalyticsSent: 254ms
[   +1 ms] [   +1 ms] Running shutdown hooks
[        ] [        ] Shutdown hooks complete
[        ] [        ] exiting with code 1
[  +28 ms] ProcessProductPackaging ""
/Users/tvolkert/project/sci/apps/payouts/build/macos/Build/Intermediates.noindex/Runner.build/Debug/Runner.build/payouts.app.xcent (in target 'Runner' from
project 'Runner')
...
```
but the failure exit code doesn't stop the compilation, it keeps right on trucking, then eventually fails AT RUNTIME on the device because App.framework isn't found.  `macos_assemble.sh` doesn't have `set -e` and it's not exiting the entire script with a failure exit code when it happens.

**Comment by jmagman** [comment]
I'm going to re-close this in favor of https://github.com/flutter/flutter/issues/78348 since the symptoms are similar but @tvolkert's issue is much worse.
