### ISSUE TITLE
[google_maps_flutter] Add support for heatmap layer 

### ISSUE THREAD

**Issue by Rob-Biemans** [flutter/flutter#33586]
Add heatmap layer api support as in the Google Maps Javascript API, which can be found here; https://developers.google.com/maps/documentation/javascript/heatmaplayer

**Comment by XinyueZ** [comment]
+1

**Comment by Rob-Biemans** [comment]
@stuartmorgan Could you please label this issue? Thank you for your effort!

**Comment by urmilshroff** [comment]
Any word on this issue? I'm also looking for a way to display density hotspots/heatmaps in my Flutter app with the Maps plugin.

**Comment by jerfeson** [comment]
I am looking forward to this feature.+1

**Comment by DCubix** [comment]
I needed this feature asap!

**Comment by clemclx** [comment]
Agree ! Would really appreciate heatmap layer support..

**Comment by fvisticot** [comment]
Mandature for our app. Please add thaïs feature

**Comment by srburton** [comment]
No app é apenas um MVP, pode esperar essa funcionalidade.

**Comment by MpEliaz** [comment]
Please add!

**Comment by SvenSlijkoord** [comment]
Heatmap support is implemented for both Android & iOS in PR flutter/plugins#2454 but I am having trouble getting the podspec file to build because `Google-Maps-iOS-Utils` is a static framework dependency.

The `build_all_plugins_ipa` task gives the following error:
```
[!] The 'Pods-Runner' target has transitive dependencies that include statically linked binaries
```

Does anyone know how to include the `Google-Maps-iOS-Utils` dependency without breaking the build?

**Comment by arok** [comment]
@SvenSlijkoord https://github.com/googlemaps/google-maps-ios-utils/issues/23

**Comment by cyanglaz** [comment]
After looking into the `google-maps-utils` repo, I want to experiment to have a separate flutter plugin to handle all the features in the `google-maps-utils`. I will set up the new plugin and add some minimum code. After that, we can work together to add these new features. Including heat-map mentioned in this issue.

**Comment by lbk9** [comment]
+1 this would be a brilliant thing to have accessible in Flutter

**Comment by debasiskoley** [comment]
+1, looking forward to having full heatmap support in Flutter!

**Comment by bmabir17** [comment]
+1, looking forward to having full heatmap support in Flutter!

**Comment by bmabir17** [comment]
I urgently needed this feature so i have forked the [pull request](https://github.com/SvenSlijkoord/plugins/tree/implement_google_maps_flutter_heatmap ) 
And published a forked package [google_maps_flutter_heatmap](https://pub.dev/packages/google_maps_flutter_heatmap) (Tested only on android)

**Comment by rouvoy** [comment]
Thanks for the fork and the package release, but it only seems to work on Android, unfortunately.

**Comment by arok** [comment]
@rouvoy see my fork https://github.com/arok/plugins/tree/implement_google_maps_flutter_heatmap it also works on iOS

**Comment by mlemos** [comment]
Please add this feature. This is a must-have for lots of maps based applications.

**Comment by Alystrasz** [comment]
Here's the current situation of Flutter heatmaps:
* there's one PR from @SvenSlijkoord implementing the feature (https://github.com/flutter/plugins/pull/2454), but it does not pass CI checks and seems inactive;
* @bmabir17's fork (https://github.com/bmabir17/google_maps_flutter_heatmap) does not work on iOS;
* @arok's fork (https://github.com/arok/plugins/tree/implement_google_maps_flutter_heatmap) compiles on both Android and iOS, but have some display issues on iOS (screenshots available on [this StackOverflow post](https://stackoverflow.com/a/63447286/11243782)).

Any volunteer to develop this feature? :smile:

**Comment by BhupinderRana** [comment]
> Here's the current situation of Flutter heatmaps:
> 
> * there's one PR from @SvenSlijkoord implementing the feature ([flutter/plugins#2454](https://github.com/flutter/plugins/pull/2454)), but it does not pass CI checks and seems inactive;
> * @bmabir17's fork (https://github.com/bmabir17/google_maps_flutter_heatmap) does not work on iOS;
> * @arok's fork (https://github.com/arok/plugins/tree/implement_google_maps_flutter_heatmap) compiles on both Android and iOS, but have some display issues on iOS (screenshots available on [this StackOverflow post](https://stackoverflow.com/a/63447286/11243782)).
> 
> Any volunteer to develop this feature? 😄

Hi is it any package right know to implement heat maps in flutter ? please

**Comment by BhupinderRana** [comment]
https://github.com/BhupinderRana/google_maps_flutter_heatmap

**Comment by eamirho3ein3** [comment]
I needed this feature for web!

**Comment by ViniciusDiasSilva** [comment]
+1 looking forward to seeing it available

**Comment by Wian-TMC** [comment]
+1 looking forward to seeing it available. Hopefully any day now

**Comment by ruhulmath08** [comment]
Please update this package. This package is not dart null safety enable.

**Comment by Rexios80** [comment]
Working on this in #5274. I have tested basic heatmap support on Android and web. iOS and more testing needs done.

**Comment by Rexios80** [comment]
iOS implementation is working now too

**Comment by ZhuBoao** [comment]
> iOS implementation is working now too

looking forward to this to be merged!

**Comment by paulinavita** [comment]
Hi, any updates on this? Thanks!

**Comment by Rexios80** [comment]
The PR for this has been useable for a long time: https://github.com/flutter/plugins/pull/5274#issuecomment-1120439314

**Comment by wH1t3-l0tUs** [comment]
@Rexios80 I have imported it like your comment, but doesn't work, does it change to the new version? can you show me?

**Comment by Rexios80** [comment]
What doesn't work about it?

**Comment by wH1t3-l0tUs** [comment]
crashed on android with this message

```
E/AndroidRuntime(18527): java.lang.IllegalArgumentException: No input points.
E/AndroidRuntime(18527): 	at com.google.maps.android.heatmaps.HeatmapTileProvider$Builder.weightedData(HeatmapTileProvider.java:209)
E/AndroidRuntime(18527): 	at io.flutter.plugins.googlemaps.HeatmapBuilder.setWeightedData(HeatmapBuilder.java:25)
E/AndroidRuntime(18527): 	at io.flutter.plugins.googlemaps.Convert.interpretHeatmapOptions(Convert.java:606)
E/AndroidRuntime(18527): 	at io.flutter.plugins.googlemaps.HeatmapsController.addHeatmap(HeatmapsController.java:66)
E/AndroidRuntime(18527): 	at io.flutter.plugins.googlemaps.HeatmapsController.addHeatmaps(HeatmapsController.java:32)
E/AndroidRuntime(18527): 	at io.flutter.plugins.googlemaps.GoogleMapController.updateInitialHeatmaps(GoogleMapController.java:873)
E/AndroidRuntime(18527): 	at io.flutter.plugins.googlemaps.GoogleMapController.onMapReady(GoogleMapController.java:215)
E/AndroidRuntime(18527): 	at com.google.android.gms.maps.zzaf.zzb(com.google.android.gms:play-services-maps@@18.1.0:1)
E/AndroidRuntime(18527): 	at com.google.android.gms.maps.internal.zzar.zza(com.google.android.gms:play-services-maps@@18.1.0:6)
E/AndroidRuntime(18527): 	at com.google.android.gms.internal.maps.zzb.onTransact(com.google.android.gms:play-services-maps@@18.1.0:3)
E/AndroidRuntime(18527): 	at android.os.Binder.transact(Binder.java:1164)
E/AndroidRuntime(18527): 	at em.c(:com.google.android.gms.dynamite_mapsdynamite@223616044@22.36.16 (190400-0):2)
E/AndroidRuntime(18527): 	at com.google.maps.api.android.lib6.impl.bg.run(:com.google.android.gms.dynamite_mapsdynamite@223616044@22.36.16 (190400-0):1)
E/AndroidRuntime(18527): 	at android.os.Handler.handleCallback(Handler.java:942)
E/AndroidRuntime(18527): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/AndroidRuntime(18527): 	at android.os.Looper.loopOnce(Looper.java:201)
E/AndroidRuntime(18527): 	at android.os.Looper.loop(Looper.java:288)
E/AndroidRuntime(18527): 	at android.app.ActivityThread.main(ActivityThread.java:7898)
E/AndroidRuntime(18527): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(18527): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
E/AndroidRuntime(18527): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
I/Process (18527): Sending signal. PID: 18527 SIG: 9
Lost connection to device.
```

**Comment by Rexios80** [comment]
Did you pass a heatmap with no points?

**Comment by wH1t3-l0tUs** [comment]
Yes I fixed it, the map was created before the data had come

**Comment by Rexios80** [comment]
I should probably add an assertion that the heatmap data isn't empty

**Comment by wH1t3-l0tUs** [comment]
@Rexios80 is there any way to control the camera of the heatmap? I want to change the position of it, but the googlemapcontroller is not able to use in it.

**Comment by Rexios80** [comment]
Yeah it is

**Comment by wH1t3-l0tUs** [comment]
@Rexios80 can you show it? I have to recreate the map to init the camera position again

**Comment by Rexios80** [comment]
The heatmap is just a layer. Everything else works exactly the same as without heatmaps.

**Comment by wH1t3-l0tUs** [comment]
@Rexios80 Is there any way to keep the color of the layer when we zoom in? As I zoom out, the color of each point is correct, but when zooming in, the points combine together, but their color is change to the max intensity

**Comment by SuhasGaidhane** [comment]
anyone have working project to Show HeatMap on FlutterApp 
Please provide Github Link

**Comment by Rexios80** [comment]
The example app in my fork has a heatmap implementation

**Comment by click2cloud-suhas** [comment]
give me Github Link

**Comment by stuartmorgan** [comment]
This is in progress; keeping P1.

**Comment by ZhuBoao** [comment]
Would love to see this one being implemented.

**Comment by stuartmorgan** [comment]
The PR had been blocked on a significant API wrapping issue, but that has been resolved an the PR is once again making good progress.

**Comment by trevor-nomadik** [comment]
> The PR had been blocked on a significant API wrapping issue, but that has been resolved an the PR is once again making good progress.

Anyway I can help? Would definitely solve one of my current problems.

**Comment by wangela** [comment]
Heatmap layer support has been released for apps targeting Android, iOS, and web in google_maps_flutter [v2.8.0](https://pub.dev/packages/google_maps_flutter/changelog#280) 🚀
