### ISSUE TITLE
Exception from the Dart analysis server when developing plugin with v1.5.4-hotfix.2

### ISSUE THREAD

**Issue by dragonetail** [flutter/flutter#33592]
## Steps to Reproduce

1. Flutter SDK 1.5.4-hotfix.2 +  Dart Code 2.3.0 + Visual Studio Code 1.34.0 + flutter plugin 3.0.2 
2. plugin project with platform codes, for example/lib/main.dart, flutter select ios device and run app
3. example/ios/.symlinks will be created
4. reboot vscode, then there will be error on dependence import(Target of URI doesn't exist) and notification will report analysis server exception like:
```
Exception from the Dart analysis server: FileSystemException(path=/Users/user/workspace/ios/flutter_test/example/ios/.symlinks/plugins/flutter_test/example/ios/.symlinks/plugins/flutter_test/example/ios/.symlinks/plugins/flutter_test/example/ios/.symlinks/plugins/flutter_test/example/ios/.symlinks/plugins/flutter_test/example/ios/.symlinks/plugins/flutter_test/example/ios/.symlinks/plugins/flutter_test/example/ios/.symlinks/plugins/flutter_test/example/ios/.symlinks/plugins/flutter_test/example/ios/.symlinks/plugins/flutter_test/example/ios/.symlinks/plugins/flutter_test/example/ios/.symlinks/plugins/flutter_test/example/ios/.symlinks/plugins/flutter_test/example/ios/.symlinks/plugins/flutter_test/example/ios/.symlinks/plugins/flutter_test/example/ios/.symlinks/plugins/flutter_test/exampl...
```
5. delete the generated folder example/ios/.symlinks, and reboot vscode, all will be back to OK.

## flutter doctor -v

```
[✓] Flutter (Channel stable, v1.5.4-hotfix.2, on Mac OS X 10.14.5 18F132, locale zh-Hans-CN)
    • Flutter version 1.5.4-hotfix.2 at /Users/user1/flutter
    • Framework revision 7a4c33425d (4 weeks ago), 2019-04-29 11:05:24 -0700
    • Engine revision 52c7a1e849
    • Dart version 2.3.0 (build 2.3.0-dev.0.5 a1668566e5)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/user1/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.2.1, Build version 10E1001
    • ios-deploy 1.9.4
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.4)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 35.3.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

[✓] VS Code (version 1.34.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.0.2

[✓] Connected device (2 available)
    • ALP AL00  • D3H0218130018779                     • android-arm64 • Android 9 (API 28)
    • iPhone Xʀ • 712E2892-3341-44B1-B0B5-1922546455CF • ios           • com.apple.CoreSimulator.SimRuntime.iOS-12-2
      (simulator)
```

## flutter analyze

```
Error response from the server: SERVER_ERROR                            
FileSystemException(path=/Users/user1/workspace/ios/flutter_test/example/ios/.symlinks/plugins/flutter_photo_help
er/example/ios/.symlinks/plugins/flutter_test/example/ios/.symlinks/plugins/flutter_test/example/ios/.sym
links/plugins/flutter_test/example/ios/.symlinks/plugins/flutter_test/example/ios/.symlinks/plugins/flutt
er_photo_helper/example/ios/.symlinks/plugins/flutter_test/example/ios/.symlinks/plugins/flutter_test/exa
mple/ios/.symlinks/plugins/flutter_test/example/ios/.symlinks/plugins/flutter_test/example/ios/.symlinks/
plugins/flutter_test/example/ios/.symlinks/plugins/flutter_test/example/ios/.symlinks/plugins/flutter_pho
to_helper/example/ios/.symlinks/plugins/flutter_test/example/ios/.symlinks/plugins/flutter_test/example/i
os/.symlinks/plugins/flutter_test/example/ios/.symlinks/plugins/flutter_test/example/ios/.symlinks/plugin
s/flutter_test/example/ios/Runner.xcworkspace/xcuserdata/user1.xcuserdat; message=Directory listing failed)
#0      _PhysicalFolder.getChildren (package:analyzer/file_system/physical_file_system.dart:334:7)
#1      _OverlayFolder.getChildren (package:analyzer/file_system/overlay_file_system.dart:334:10)
#2      ContextManagerImpl._createContext.checkManifestFilesIn (package:analysis_server/src/context_manager.dart:1144:32)
#3      ContextManagerImpl._createContext.checkManifestFilesIn (package:analysis_server/src/context_manager.dart:1152:33)
#4      ContextManagerImpl._createContext.checkManifestFilesIn (package:analysis_server/src/context_manager.dart:1152:33)
#5      ContextManagerImpl._createContext.checkManifestFilesIn (package:analysis_server/src/context_manager.dart:1152:33)
#6      ContextManagerImpl._createContext.checkManifestFilesIn (package:analysis_server/src/context_manager.dart:1152:33)
#7      ContextManagerImpl._createContext.checkManifestFilesIn (package:analysis_server/src/context_manager.dart:1152:33)
#8      ContextManagerImpl._createContext.checkManifestFilesIn (package:analysis_server/src/context_manager.dart:1152:33)
#9      ContextManagerImpl._createContext.checkManifestFilesIn (package:analysis_server/src/context_manager.dart:1152:33)
#10     ContextManagerImpl._createContext.checkManifestFilesIn (package:analysis_server/src/context_manager.dart:1152:33)
#11     ContextManagerImpl._createContext.checkManifestFilesIn (package:analysis_server/src/context_manager.dart:1152:33)
#12     ContextManagerImpl._createContext.checkManifestFilesIn (package:analysis_server/src/context_manager.dart:1152:33)
#13     ContextManagerImpl._createContext.checkManifestFilesIn (package:analysis_server/src/context_manager.dart:1152:33)
#14     ContextManagerImpl._createContext.checkManifestFilesIn (package:analysis_server/src/context_manager.dart:1152:33)
#15     ContextManagerImpl._createContext.checkManifestFilesIn (package:analysis_server/src/context_manager.dart:1152:33)
#16     ContextManagerImpl._createContext.checkManifestFilesIn (package:analysis_server/src/context_manager.dart:1152:33)
#17     ContextManagerImpl._createContext.checkManifestFilesIn (package:analysis_server/src/context_manager.dart:1152:33)
#18     ContextManagerImpl._createContext.checkManifestFilesIn (package:analysis_server/src/context_manager.dart:1152:33)
#19     ContextManagerImpl._createContext.checkManifestFilesIn (package:analysis_server/src/context_manager.dart:1152:33)
#20     ContextManagerImpl._createContext.checkManifestFilesIn (package:analysis_server/src/context_manager.dart:1152:33)
#21     ContextManagerImpl._createContext.checkManifestFilesIn (package:analysis_server/src/context_manager.dart:1152:33)
#22     ContextManagerImpl._createContext.checkManifestFilesIn (package:analysis_server/src/context_manager.dart:1152:33)
#23     ContextManagerImpl._createContext.checkManifestFilesIn (package:analysis_server/src/context_manager.dart:1152:33)
#24     ContextManagerImpl._createContext.checkManifestFilesIn (package:analysis_server/src/context_manager.dart:1152:33)
#25     ContextManagerImpl._createContext.checkManifestFilesIn (package:analysis_server/src/context_manager.dart:1152:33)
#26     ContextManagerImpl._createContext.checkManifestFilesIn (package:analysis_server/src/context_manager.dart:1152:33)
#27     ContextManagerImpl._createContext.checkManifestFilesIn (package:analysis_server/src/context_manager.dart:1152:33)
#28     ContextManagerImpl._createContext.checkManifestFilesIn (package:analysis_server/src/context_manager.dart:1152:33)
#29     ContextManagerImpl._createContext.checkManifestFilesIn (package:analysis_server/src/context_manager.dart:1152:33)
#30     ContextManagerImpl._createContext.checkManifestFilesIn (package:analysis_server/src/context_manager.dart:1152:33)
#31     ContextManagerImpl._createContext.checkManifestFilesIn (package:analysis_server/src/context_manager.dart:1152:33)
#32     ContextManagerImpl._createContext.checkManifestFilesIn (package:analysis_server/src/context_manager.dart:1152:33)
#33     ContextManagerImpl._createContext.checkManifestFilesIn (package:analysis_server/src/context_manager.dart:1152:33)
#34     ContextManagerImpl._createContext.checkManifestFilesIn (package:analysis_server/src/context_manager.dart:1152:33)
#35     ContextManagerImpl._createContext.checkManifestFilesIn (package:analysis_server/src/context_manager.dart:1152:33)
#36     ContextManagerImpl._createContext.checkManifestFilesIn (package:analysis_server/src/context_manager.dart:1152:33)
#37     ContextManagerImpl._createContext.checkManifestFilesIn (package:analysis_server/src/context_manager.dart:1152:33)
#38     ContextManagerImpl._createContext.checkManifestFilesIn (package:analysis_server/src/context_manager.dart:1152:33)
#39     ContextManagerImpl._createContext.checkManifestFilesIn (package:analysis_server/src/context_manager.dart:1152:33)
#40     ContextManagerImpl._createContext.checkManifestFilesIn (package:analysis_server/src/context_manager.dart:1152:33)
#41     ContextManagerImpl._createContext.checkManifestFilesIn (package:analysis_server/src/context_manager.dart:1152:33)
#42     ContextManagerImpl._createContext.checkManifestFilesIn (package:analysis_server/src/context_manager.dart:1152:33)
#43     ContextManagerImpl._createContext.checkManifestFilesIn (package:analysis_server/src/context_manager.dart:1152:33)
#44     ContextManagerImpl._createContext.checkManifestFilesIn (package:analysis_server/src/context_manager.dart:1152:33)
#45     ContextManagerImpl._createContext.checkManifestFilesIn (package:analysis_server/src/context_manager.dart:1152:33)
#46     ContextManagerImpl._createContext.checkManifestFilesIn (package:analysis_server/src/context_manager.dart:1152:33)
#47     ContextManagerImpl._createContext.checkManifestFilesIn (package:analysis_server/src/context_manager.dart:1152:33)
#48     ContextManagerImpl._createContext.checkManifestFilesIn (package:analysis_server/src/context_manager.dart:1152:33)
#49     ContextManagerImpl._createContext.checkManifestFilesIn (package:analysis_server/src/context_manager.dart:1152:33)
#50     ContextManagerImpl._createContext.checkManifestFilesIn (package:analysis_server/src/context_manager.dart:1152:33)
#51     ContextManagerImpl._createContext.checkManifestFilesIn (package:analysis_server/src/context_manager.dart:1152:33)
#52     ContextManagerImpl._createContext.checkManifestFilesIn (package:analysis_server/src/context_manager.dart:1152:33)
#53     ContextManagerImpl._createContext.checkManifestFilesIn (package:analysis_server/src/context_manager.dart:1152:33)
#54     ContextManagerImpl._createContext.checkManifestFilesIn (package:analysis_server/src/context_manager.dart:1152:33)
#55     ContextManagerImpl._createContext.checkManifestFilesIn (package:analysis_server/src/context_manager.dart:1152:33)
#56     ContextManagerImpl._createContext.checkManifestFilesIn (package:analysis_server/src/context_manager.dart:1152:33)
#57     ContextManagerImpl._createContext.checkManifestFilesIn (package:analysis_server/src/context_manager.dart:1152:33)
#58     ContextManagerImpl._createContext.checkManifestFilesIn (package:analysis_server/src/context_manager.dart:1152:33)
#59     ContextManagerImpl._createContext.checkManifestFilesIn (package:analysis_server/src/context_manager.dart:1152:33)
#60     ContextManagerImpl._createContext.checkManifestFilesIn (package:analysis_server/src/context_manager.dart:1152:33)
#61     ContextManagerImpl._createContext.checkManifestFilesIn (package:analysis_server/src/context_manager.dart:1152:33)
#62     ContextManagerImpl._createContext.checkManifestFilesIn (package:analysis_server/src/context_manager.dart:1152:33)
#63     ContextManagerImpl._createContext.checkManifestFilesIn (package:analysis_server/src/context_manager.dart:1152:33)
#64     ContextManagerImpl._createContext.checkManifestFilesIn (package:analysis_server/src/context_manager.dart:1152:33)
#65     ContextManagerImpl._createContext.checkManifestFilesIn (package:analysis_server/src/context_manager.dart:1152:33)
#66     ContextManagerImpl._createContext.checkManifestFilesIn (package:analysis_server/src/context_manager.dart:1152:33)
#67     ContextManagerImpl._createContext.checkManifestFilesIn (package:analysis_server/src/context_manager.dart:1152:33)
#68     ContextManagerImpl._createContext.checkManifestFilesIn (package:analysis_server/src/context_manager.dart:1152:33)
#69     ContextManagerImpl._createContext.checkManifestFilesIn (package:analysis_server/src/context_manager.dart:1152:33)
#70     ContextManagerImpl._createContext.checkManifestFilesIn (package:analysis_server/src/context_manager.dart:1152:33)
#71     ContextManagerImpl._createContext.checkManifestFilesIn (package:analysis_server/src/context_manager.dart:1152:33)
#72     ContextManagerImpl._createContext.checkManifestFilesIn (package:analysis_server/src/context_manager.dart:1152:33)
#73     ContextManagerImpl._createContext.checkManifestFilesIn (package:analysis_server/src/context_manager.dart:1152:33)
#74     ContextManagerImpl._createContext.checkManifestFilesIn (package:analysis_server/src/context_manager.dart:1152:33)
#75     ContextManagerImpl._createContext.checkManifestFilesIn (package:analysis_server/src/context_manager.dart:1152:33)
#76     ContextManagerImpl._createContext.checkManifestFilesIn (package:analysis_server/src/context_manager.dart:1152:33)
#77     ContextManagerImpl._createContext.checkManifestFilesIn (package:analysis_server/src/context_manager.dart:1152:33)
#78     ContextManagerImpl._createContext.checkManifestFilesIn (package:analysis_server/src/context_manager.dart:1152:33)
#79     ContextManagerImpl._createContext.checkManifestFilesIn (package:analysis_server/src/context_manager.dart:1152:33)
#80     ContextManagerImpl._createContext.checkManifestFilesIn (package:analysis_server/src/context_manager.dart:1152:33)
#81     ContextManagerImpl._createContext.checkManifestFilesIn (package:analysis_server/src/context_manager.dart:1152:33)
#82     ContextManagerImpl._createContext.checkManifestFilesIn (package:analysis_server/src/context_manager.dart:1152:33)
#83     ContextManagerImpl._createContext.checkManifestFilesIn (package:analysis_server/src/context_manager.dart:1152:33)
#84     ContextManagerImpl._createContext.checkManifestFilesIn (package:analysis_server/src/context_manager.dart:1152:33)
#85     ContextManagerImpl._createContext.checkManifestFilesIn (package:analysis_server/src/context_manager.dart:1152:33)
#86     ContextManagerImpl._createContext.checkManifestFilesIn (package:analysis_server/src/context_manager.dart:1152:33)
#87     ContextManagerImpl._createContext.checkManifestFilesIn (package:analysis_server/src/context_manager.dart:1152:33)
#88     ContextManagerImpl._createContext.checkManifestFilesIn (package:analysis_server/src/context_manager.dart:1152:33)
#89     ContextManagerImpl._createContext.checkManifestFilesIn (package:analysis_server/src/context_manager.dart:1152:33)
#90     ContextManagerImpl._createContext.checkManifestFilesIn (package:analysis_server/src/context_manager.dart:1152:33)
#91     ContextManagerImpl._createContext.checkManifestFilesIn (package:analysis_server/src/context_manager.dart:1152:33)
#92     ContextManagerImpl._createContext.checkManifestFilesIn (package:analysis_server/src/context_manager.dart:1152:33)
#93     ContextManagerImpl._createContext.checkManifestFilesIn (package:analysis_server/src/context_manager.dart:1152:33)
#94     ContextManagerImpl._createContext.checkManifestFilesIn (package:analysis_server/src/context_manager.dart:1152:33)
#95     ContextManagerImpl._createContext.checkManifestFilesIn (package:analysis_server/src/context_manager.dart:1152:33)
#96     ContextManagerImpl._createContext.checkManifestFilesIn (package:analysis_server/src/context_manager.dart:1152:33)
#97     ContextManagerImpl._createContext (package:analysis_server/src/context_manager.dart:1158:25)
#98     ContextManagerImpl._createContexts (package:analysis_server/src/context_manager.dart:1191:16)
#99     ContextManagerImpl.setRoots (package:analysis_server/src/context_manager.dart:736:9)
#100    AnalysisServer.setAnalysisRoots (package:analysis_server/src/analysis_server.dart:521:22)
#101    AnalysisDomainHandler.setAnalysisRoots (package:analysis_server/src/domain_analysis.dart:390:14)
#102    AnalysisDomainHandler.handleRequest (package:analysis_server/src/domain_analysis.dart:324:16)
#103    AnalysisServer.handleRequest.<anonymous closure>.<anonymous closure>
(package:analysis_server/src/analysis_server.dart:337:45)
#104    _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:258:15)
#105    AnalysisServer.handleRequest.<anonymous closure> (package:analysis_server/src/analysis_server.dart:333:50)
#106    _rootRun (dart:async/zone.dart:1124:13)
#107    _CustomZone.run (dart:async/zone.dart:1021:19)
#108    _runZoned (dart:async/zone.dart:1516:10)
#109    runZoned (dart:async/zone.dart:1500:12)
#110    AnalysisServer.handleRequest (package:analysis_server/src/analysis_server.dart:332:5)
#111    ByteStreamServerChannel._readRequest.<anonymous closure>
(package:analysis_server/src/channel/byte_stream_channel.dart:174:16)
#112    _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:258:15)
#113    ByteStreamServerChannel._readRequest (package:analysis_server/src/channel/byte_stream_channel.dart:165:47)
#114    ByteStreamServerChannel.listen.<anonymous closure>
(package:analysis_server/src/channel/byte_stream_channel.dart:110:26)
#115    _rootRunUnary (dart:async/zone.dart:1132:38)
#116    _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#117    _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
#118    _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#119    _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#120    _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:68:11)
#121    _EventSinkWrapper.add (dart:async/stream_transformers.dart:15:11)
#122    _StringAdapterSink.add (dart:convert/string_conversion.dart:236:11)
#123    _LineSplitterSink._addLines (dart:convert/line_splitter.dart:150:13)
#124    _LineSplitterSink.addSlice (dart:convert/line_splitter.dart:125:5)
#125    StringConversionSinkMixin.add (dart:convert/string_conversion.dart:163:5)
#126    _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:120:24)
#127    _rootRunUnary (dart:async/zone.dart:1132:38)
#128    _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#129    _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
#130    _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#131    _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#132    _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:68:11)
#133    _EventSinkWrapper.add (dart:async/stream_transformers.dart:15:11)
#134    _StringAdapterSink.add (dart:convert/string_conversion.dart:236:11)
#135    _StringAdapterSink.addSlice (dart:convert/string_conversion.dart:241:7)
#136    _Utf8ConversionSink.addSlice (dart:convert/string_conversion.dart:312:20)
#137    _Utf8ConversionSink.add (dart:convert/string_conversion.dart:305:5)
#138    _ConverterStreamEventSink.add (dart:convert/chunked_conversion.dart:72:18)
#139    _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:120:24)
#140    _rootRunUnary (dart:async/zone.dart:1132:38)
#141    _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#142    _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
#143    _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#144    _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#145    _SyncStreamController._sendData (dart:async/stream_controller.dart:764:19)
#146    _StreamController._add (dart:async/stream_controller.dart:640:7)
#147    _StreamController.add (dart:async/stream_controller.dart:586:5)
#148    _Socket._onData (dart:io-patch/socket_patch.dart:1774:41)
#149    _rootRunUnary (dart:async/zone.dart:1136:13)
#150    _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#151    _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
#152    _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#153    _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#154    _SyncStreamController._sendData (dart:async/stream_controller.dart:764:19)
#155    _StreamController._add (dart:async/stream_controller.dart:640:7)
#156    _StreamController.add (dart:async/stream_controller.dart:586:5)
#157    new _RawSocket.<anonymous closure> (dart:io-patch/socket_patch.dart:1323:33)
#158    _NativeSocket.issueReadEvent.issue (dart:io-patch/socket_patch.dart:844:14)
#159    _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#160    _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#161    _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:115:13)
#162    _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:5)
```

**Comment by AmolGangadhare** [comment]
+1

I'm also getting this error on `flutter analyze`. But I didn't get this on a normal project, I got this on a `plugin` I created.

**Comment by DanTup** [comment]
This looks like https://github.com/dart-lang/sdk/issues/36919.
