### ISSUE TITLE
App crashes only in Release mode, Debug works

### ISSUE THREAD

**Issue by theshivamlko** [flutter/flutter#33637]
```
  Process: com.empowerplus.app, PID: 4911
    java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.empowerplus.app-ClCeyl19oxJ9dqWp0hoyqw==/base.apk"],nativeLibraryDirectories=[/data/app/com.empowerplus.app-ClCeyl19oxJ9dqWp0hoyqw==/lib/arm64, /data/app/com.empowerplus.app-ClCeyl19oxJ9dqWp0hoyqw==/base.apk!/lib/arm64-v8a, /system/lib64, /system/vendor/lib64]]] couldn't find "libflutter.so"
        at java.lang.Runtime.loadLibrary0(Runtime.java:1011)
        at java.lang.System.loadLibrary(System.java:1657)
        at io.flutter.view.FlutterMain.startInitialization(FlutterMain.java:161)
        at io.flutter.view.FlutterMain.startInitialization(FlutterMain.java:136)
        at io.flutter.app.FlutterApplication.onCreate(FlutterApplication.java:22)
        at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1129)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6023)
        at android.app.ActivityThread.-wrap1(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1756)
        at android.os.Handler.dispatchMessage(Handler.java:105)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6798)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
```

flutter doctor -v

```
[√] Flutter (Channel stable, v1.5.4-hotfix.2, on Microsoft Windows [Version 10.0.17763.503], locale en-US)
    • Flutter version 1.5.4-hotfix.2 at C:\Users\Navoki\flutter
    • Framework revision 7a4c33425d (5 weeks ago), 2019-04-29 11:05:24 -0700
    • Engine revision 52c7a1e849
    • Dart version 2.3.0 (build 2.3.0-dev.0.5 a1668566e5)


[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at C:\Users\Navoki\Android\SDK
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = C:\Users\Navoki\Android\SDK
    • Java binary at: C:\Users\Navoki\android-studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b01)
    • All Android licenses accepted.

[√] Android Studio (version 3.4)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 35.3.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

[√] Android Studio (version 3.5)
    • Android Studio at C:\Users\Navoki\android-studio
    • Flutter plugin version 35.3.2
    • Dart plugin version 191.7019
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b01)

[√] IntelliJ IDEA Community Edition (version 2019.1)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2019.1.2
    • Flutter plugin version 35.3.3
    • Dart plugin version 191.7221

[√] VS Code (version 1.34.0)
    • VS Code at C:\Users\Navoki\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.0.2

[√] Connected device (1 available)
    • ONEPLUS A3003 • ec6202af • android-arm64 • Android 8.0.0 (API 26)

• No issues found!

```

**Comment by BondarenkoStas** [comment]
@theshivamlko did you manage to solve it?

**Comment by theshivamlko** [comment]
Yes,resolved, the PDF library i was using didn't create .so file for release mode. I had to add this to make it work, it was not flutter issue

`    buildTypes {
        release {
            signingConfig signingConfigs.config
            ndk {
                abiFilters "armeabi-v7a"
            }
        }

        debug {
            signingConfig signingConfigs.debug
        }
    }`
