### ISSUE TITLE
[image_picker] Permission Denied using maxHeight and maxWidth

### ISSUE THREAD

**Issue by FilipeOS** [flutter/flutter#33655]
Hi,

So, in my other threat I posted about the issue I'm having with image_picker ImageSource.camera having permission issues.

Ignoring that (for now), the ImageSource.gallery always worked BUT when I try to set like this, it fires an Exception. Permission to access Storage is being asked once I click on gallery button on my app.

My code:
```
var imageFile = await ImagePicker.pickImage(source: ImageSource.gallery, maxHeight: 1920, maxWidth: 1920);
```
Issue:
```
E/AndroidRuntime( 2665): java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=2342, result=-1, data=Intent { dat=content://com.android.providers.media.documents/document/image:3463 flg=0x1 }} to activity {com.company.flutter_app/com.company.flutter_app.MainActivity}: java.lang.RuntimeException: java.io.FileNotFoundException: /storage/emulated/0/Android/data/com.company.flutter_app/files/Pictures/scaled_20190527_143641.jpg (Permission denied)
E/AndroidRuntime( 2665): 	at android.app.ActivityThread.deliverResults(ActivityThread.java:4604)
E/AndroidRuntime( 2665): 	at android.app.ActivityThread.handleSendResult(ActivityThread.java:4646)
E/AndroidRuntime( 2665): 	at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:49)
E/AndroidRuntime( 2665): 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
E/AndroidRuntime( 2665): 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
E/AndroidRuntime( 2665): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1947)
E/AndroidRuntime( 2665): 	at android.os.Handler.dispatchMessage(Handler.java:106)
E/AndroidRuntime( 2665): 	at android.os.Looper.loop(Looper.java:214)
E/AndroidRuntime( 2665): 	at android.app.ActivityThread.main(ActivityThread.java:7032)
E/AndroidRuntime( 2665): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime( 2665): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
E/AndroidRuntime( 2665): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:965)
E/AndroidRuntime( 2665): Caused by: java.lang.RuntimeException: java.io.FileNotFoundException: /storage/emulated/0/Android/data/com.company.flutter_app/files/Pictures/scaled_20190527_143641.jpg (Permission denied)
E/AndroidRuntime( 2665): 	at io.flutter.plugins.imagepicker.ImageResizer.resizeImageIfNeeded(ImageResizer.java:42)
E/AndroidRuntime( 2665): 	at io.flutter.plugins.imagepicker.ImagePickerDelegate.handleImageResult(ImagePickerDelegate.java:503)
E/AndroidRuntime( 2665): 	at io.flutter.plugins.imagepicker.ImagePickerDelegate.handleChooseImageResult(ImagePickerDelegate.java:442)
E/AndroidRuntime( 2665): 	at io.flutter.plugins.imagepicker.ImagePickerDelegate.onActivityResult(ImagePickerDelegate.java:421)
E/AndroidRuntime( 2665): 	at io.flutter.app.FlutterPluginRegistry.onActivityResult(FlutterPluginRegistry.java:222)
E/AndroidRuntime( 2665): 	at io.flutter.app.FlutterActivityDelegate.onActivityResult(FlutterActivityDelegate.java:142)
E/AndroidRuntime( 2665): 	at io.flutter.app.FlutterActivity.onActivityResult(FlutterActivity.java:142)
E/AndroidRuntime( 2665): 	at android.app.Activity.dispatchActivityResult(Activity.java:7759)
E/AndroidRuntime( 2665): 	at android.app.ActivityThread.deliverResults(ActivityThread.java:4597)
E/AndroidRuntime( 2665): 	... 11 more
E/AndroidRuntime( 2665): Caused by: java.io.FileNotFoundException: /storage/emulated/0/Android/data/com.company.flutter_app/files/Pictures/scaled_20190527_143641.jpg (Permission denied)
E/AndroidRuntime( 2665): 	at java.io.FileOutputStream.open0(Native Method)
E/AndroidRuntime( 2665): 	at java.io.FileOutputStream.open(FileOutputStream.java:308)
E/AndroidRuntime( 2665): 	at java.io.FileOutputStream.<init>(FileOutputStream.java:238)
E/AndroidRuntime( 2665): 	at java.io.FileOutputStream.<init>(FileOutputStream.java:180)
E/AndroidRuntime( 2665): 	at io.flutter.plugins.imagepicker.ImageResizer.resizedImage(ImageResizer.java:96)
E/AndroidRuntime( 2665): 	at io.flutter.plugins.imagepicker.ImageResizer.resizeImageIfNeeded(ImageResizer.java:37)
```

The folder exist but nothing inside it:
`/Android/data/com.company.flutter_app/files/Pictures/`

Any solution for this?

Samsung S10 with Android 9

**Comment by BondarenkoStas** [comment]
@FilipeOS did you find a solution to it? Is it the same while using current flutter stable? Did you try `flutter clean`?

**Comment by iapicca** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
  
Thanks for your contribution.

**Comment by FilipeOS** [comment]
Sorry, I got issues with my GitHub account.

For some miracle after I update all my dependencies, after a couple weeks started working so I guess it was some compatibility issues.

Thank you.

**Comment by iapicca** [comment]
Hi @FilipeOS 
I'm glad to hear that you solved the issue,
thank you for letting me know
