### ISSUE TITLE
flutter generate is crashing Unhandled exception: Deserializing

### ISSUE THREAD

**Issue by humblerookie** [flutter/flutter#33715]
flutter generate is crashing and throwing this error
**flutter generate**
```
starting build daemon...                                            1.0s

Unhandled exception:
Deserializing '[ServerLog, level, INFO, message, About to build [goodreads_client]...]' to 'unspecified' failed due to: Tried to construct class "ServerLog" with null field "log". This is forbidden; to allow it, mark "log" with @nullable.
#0      BuiltJsonSerializers._deserialize (package:built_value/src/built_json_serializers.dart:126:11)
#1      BuiltJsonSerializers.deserialize (package:built_value/src/built_json_serializers.dart:105:18)
#2      new BuildDaemonClient._.<anonymous closure> (package:build_daemon/client.dart:76:36)
#3      _rootRunUnary (dart:async/zone.dart:1132:38)
#4      _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#5      _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
#6      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#7      _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#8      _ForwardingStreamSubscription._add (dart:async/stream_pipe.dart:132:11)
#9      _ForwardingStream._handleData (dart:async/stream_pipe.dart:98:10)
#10     _ForwardingStreamSubscription._handleData (dart:async/stream_pipe.dart:164:13)
#11     _rootRunUnary (dart:async/zone.dart:1132:38)
#12     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#13     _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
#14     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#15     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#16     _SyncStreamController._sendData (dart:async/stream_controller.dart:764:19)
#17     _StreamController._add (dart:async/stream_controller.dart:640:7)
#18     _rootRunUnary (dart:async/zone.dart:1132:38)
#19     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#20     _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
#21     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#22     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#23     _SyncStreamController._sendData (dart:async/stream_controller.dart:764:19)
#24     _StreamController._add (dart:async/stream_controller.dart:640:7)
#25     _StreamController.add (dart:async/stream_controller.dart:586:5)
#26     new _WebSocketImpl._fromSocket.<anonymous closure> (dart:_http/websocket_impl.dart:1138:21)
#27     _rootRunUnary (dart:async/zone.dart:1132:38)
#28     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#29     _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
#30     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#31     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#32     _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:68:11)
#33     _EventSinkWrapper.add (dart:async/stream_transformers.dart:15:11)
#34     _WebSocketProtocolTransformer._messageFrameEnd (dart:_http/websocket_impl.dart:334:22)
#35     _WebSocketProtocolTransformer.add (dart:_http/websocket_impl.dart:229:46)
#36     _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:120:24)
#37     _rootRunUnary (dart:async/zone.dart:1132:38)
#38     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#39     _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
#40     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#41     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#42     _SyncStreamController._sendData (dart:async/stream_controller.dart:764:19)
#43     _StreamController._add (dart:async/stream_controller.dart:640:7)
#44     _StreamController.add (dart:async/stream_controller.dart:586:5)
#45     _Socket._onData (dart:io-patch/socket_patch.dart:1774:41)
#46     _rootRunUnary (dart:async/zone.dart:1136:13)
#47     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#48     _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
#49     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#50     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#51     _SyncStreamController._sendData (dart:async/stream_controller.dart:764:19)
#52     _StreamController._add (dart:async/stream_controller.dart:640:7)
#53     _StreamController.add (dart:async/stream_controller.dart:586:5)
#54     new _RawSocket.<anonymous closure> (dart:io-patch/socket_patch.dart:1323:33)
#55     _NativeSocket.issueReadEvent.issue (dart:io-patch/socket_patch.dart:844:14)
#56     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#57     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#58     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:115:13)
#59     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:5)

```

Please let me know if you need more info.
I'm using the latest **flutter 1.5.4 hotfix 2**

**Comment by jonahwilliams** [comment]
While this has been fixed on master, there is a workaround for older versions. Try adding the following line to you pubspec.yaml.

```
builders:
   ...
   build_daemon: 0.6.1
```

**Comment by humblerookie** [comment]
Updated title for visibility. @jonahwilliams  thanks a lot this works :)
