### ISSUE TITLE
error while building a windows desktop app :  MSBUILD error MSB1009 project file does not exist

### ISSUE THREAD

**Issue by houssemDevs** [flutter/flutter#33726]
hi,
I tried to build the vanilla sample app got from `flutter create` for windows desktop, but I hit the error in the title.

#### System info
* windows 10 pro build 
* visual studio 2019 with desktop development C++ workload
* MSVC v142, v141, and v140 all installed
* Windows 10 SDK (10.0.17134.0) installed

#### flutter doctor -v
```
[√] Flutter (Channel master, v1.6.8-pre.31, on Microsoft Windows [Version 10.0.17134.799], locale en-US)
    • Flutter version 1.6.8-pre.31 at C:\flutter
    • Framework revision 31318b0ebf (16 hours ago), 2019-06-01 15:49:19 -0700
    • Engine revision a4b7d1c289
    • Dart version 2.3.2 (build 2.3.2-dev.0.0 224f82c21c)


[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at C:\android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = C:\android\sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
    • All Android licenses accepted.

[√] Android Studio (version 3.4)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 35.3.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

[√] VS Code, 64-bit edition (version 1.34.0)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Flutter extension version 3.1.0

[√] Connected device (1 available)
    • Windows • Windows • windows-x64 • Microsoft Windows [Version 10.0.17134.799]

• No issues found!
```

#### flutter build windows -v
```
[  +24 ms] executing: [C:\flutter\] git log -n 1 --pretty=format:%H
[ +125 ms] Exit code 0 from: git log -n 1 --pretty=format:%H
[   +3 ms] 31318b0ebf139e04a058bcb28db1339553429031
[        ] executing: [C:\flutter\] git describe --match v*.*.* --first-parent --long --tags
[ +108 ms] Exit code 0 from: git describe --match v*.*.* --first-parent --long --tags
[        ] v1.6.7-31-g31318b0eb
[   +9 ms] executing: [C:\flutter\] git rev-parse --abbrev-ref --symbolic @{u}
[  +97 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/master
[        ] executing: [C:\flutter\] git ls-remote --get-url origin
[  +89 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[ +116 ms] executing: [C:\flutter\] git rev-parse --abbrev-ref HEAD
[  +82 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] master
[  +54 ms] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +5 ms] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[ +140 ms] Building Windows application...
[ +179 ms] **********************************************************************
[        ] ** Visual Studio 2019 Developer Command Prompt v16.1.1
[        ] ** Copyright (c) 2019 Microsoft Corporation
[        ] **********************************************************************
[+3789 ms] [vcvarsall.bat] Environment initialized for: 'x64'
[ +116 ms] Microsoft (R) Build Engine version 16.1.76+g14b0a930a7 for .NET Framework
[        ] Copyright (C) Microsoft Corporation. All rights reserved.
[        ] MSBUILD : error MSB1009: Project file does not exist.
[        ] Switch: Runner.sln
[  +12 ms] Building Windows application... (completed in 4.1s)
[   +2 ms] "flutter windows" took 4,304ms.
[        ] "flutter windows" took 4,304ms.
Build process failed

#0      throwToolExit (package:flutter_tools/src/base/common.dart:24:3)
#1      buildWindows (package:flutter_tools/src/windows/build_windows.dart:77:5)
<asynchronous suspension>
#2      BuildWindowsCommand.runCommand (package:flutter_tools/src/commands/build_windows.dart:62:11)
<asynchronous suspension>
#3      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:488:18)
#4      _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:77:64)
#5      _rootRunUnary (dart:async/zone.dart:1132:38)
#6      _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#7      _FutureListener.handleValue (dart:async/future_impl.dart:126:18)
#8      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:639:45)
#9      Future._propagateToListeners (dart:async/future_impl.dart:668:32)
#10     Future._complete (dart:async/future_impl.dart:473:7)
#11     _SyncCompleter.complete (dart:async/future_impl.dart:51:12)
#12     _AsyncAwaitCompleter.complete.<anonymous closure> (dart:async-patch/async_patch.dart:33:20)
#13     _rootRun (dart:async/zone.dart:1124:13)
#14     _CustomZone.run (dart:async/zone.dart:1021:19)
#15     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:947:23)
#16     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#17     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#18     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:115:13)
#19     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:5)
```

**Comment by stuartmorgan** [comment]
There's no support for desktop in `flutter create` yet; see https://github.com/flutter/flutter/wiki/Desktop-shells#using-the-shells

#30704 tracks this for Windows.
