### ISSUE TITLE
'package:flutter/src/widgets/image.dart': Failed assertion: line 939 pos 12: '_frameNumber == null || !synchronousCall': is not true.

### ISSUE THREAD

**Issue by anasiqbal** [flutter/flutter#33732]
Hi,

I have a screen hierarchy as follows:

1. Home screen
2. Details screen: displays details of an item along with an image (network image)
3. Payment screen: allows you to add some payment info if you want to buy the item

You can go to the payment screen from details screen and when you are done you return back to the details screen (I am using `Navigator.popUntill`);

**Issue:**
When I first open the 'Details screen' every thing works perfect and the image loads without any hiccups but when I return to the 'Details screen' from the 'Payments screen'... I get the following error. Afterwards when I go back to the home screen and then comeback to the 'Details screen' no exceptions again.

Also worth noting that if I remove the NetworkImage from the Details screen the issue disappears.

```
I/flutter (29320): ══╡ EXCEPTION CAUGHT BY IMAGE RESOURCE SERVICE ╞════════════════════════════════════════════════════
I/flutter (29320): The following assertion was thrown by a synchronously-called image listener:
I/flutter (29320): 'package:flutter/src/widgets/image.dart': Failed assertion: line 939 pos 12: '_frameNumber == null
I/flutter (29320): || !synchronousCall': is not true.
I/flutter (29320):
I/flutter (29320): Either the assertion indicates an error in the framework itself, or we should provide substantially
I/flutter (29320): more information in this error message to help you determine and fix the underlying cause.
I/flutter (29320): In either case, please report this assertion by filing a bug on GitHub:
I/flutter (29320):   https://github.com/flutter/flutter/issues/new?template=BUG.md
I/flutter (29320):
I/flutter (29320): When the exception was thrown, this was the stack:
I/flutter (29320): #2      _ImageState._handleImageFrame 
package:flutter/…/widgets/image.dart:939
I/flutter (29320): #3      ImageStreamCompleter.addListener 
package:flutter/…/painting/image_stream.dart:358
I/flutter (29320): #4      MultiFrameImageStreamCompleter.addListener 
package:flutter/…/painting/image_stream.dart:717
I/flutter (29320): #5      ImageStream.addListener 
package:flutter/…/painting/image_stream.dart:262
I/flutter (29320): #6      _ImageState._listenToStream 
package:flutter/…/widgets/image.dart:982
I/flutter (29320): #7      _ImageState.didChangeDependencies 
package:flutter/…/widgets/image.dart:882
I/flutter (29320): #8      StatefulElement.didChangeDependencies 
package:flutter/…/widgets/framework.dart:4073
I/flutter (29320): #9      Element.activate 
package:flutter/…/widgets/framework.dart:3157
I/flutter (29320): #10     StatefulElement.activate 
package:flutter/…/widgets/framework.dart:3996
I/flutter (29320): #11     Element._activateRecursively 
package:flutter/…/widgets/framework.dart:3126
I/flutter (29320): #12     SingleChildRenderObjectElement.visitChildren 
package:flutter/…/widgets/framework.dart:4961
I/flutter (29320): #13     Element._activateRecursively 
package:flutter/…/widgets/framework.dart:3128
I/flutter (29320): #14     MultiChildRenderObjectElement.visitChildren 
package:flutter/…/widgets/framework.dart:5062
I/flutter (29320): #15     Element._activateRecursively 
package:flutter/…/widgets/framework.dart:3128
I/flutter (29320): #16     ComponentElement.visitChildren 
package:flutter/…/widgets/framework.dart:3867
I/flutter (29320): #17     Element._activateRecursively 
package:flutter/…/widgets/framework.dart:3128
I/flutter (29320): #18     ComponentElement.visitChildren 
package:flutter/…/widgets/framework.dart:3867
I/flutter (29320): #19     Element._activateRecursively 
package:flutter/…/widgets/framework.dart:3128
I/flutter (29320): #20     SingleChildRenderObjectElement.visitChildren 
package:flutter/…/widgets/framework.dart:4961
I/flutter (29320): #21     Element._activateRecursively 
package:flutter/…/widgets/framework.dart:3128
I/flutter (29320): #22     ComponentElement.visitChildren 
package:flutter/…/widgets/framework.dart:3867
I/flutter (29320): #23     Element._activateRecursively 
package:flutter/…/widgets/framework.dart:3128
I/flutter (29320): #24     MultiChildRenderObjectElement.visitChildren 
package:flutter/…/widgets/framework.dart:5062
I/flutter (29320): #25     Element._activateRecursively 
package:flutter/…/widgets/framework.dart:3128
I/flutter (29320): #26     MultiChildRenderObjectElement.visitChildren 
package:flutter/…/widgets/framework.dart:5062
I/flutter (29320): #27     Element._activateRecursively 
package:flutter/…/widgets/framework.dart:3128
I/flutter (29320): #28     SingleChildRenderObjectElement.visitChildren 
package:flutter/…/widgets/framework.dart:4961
I/flutter (29320): #29     Element._activateRecursively 
package:flutter/…/widgets/framework.dart:3128
I/flutter (29320): #30     ComponentElement.visitChildren 
package:flutter/…/widgets/framework.dart:3867
I/flutter (29320): #31     Element._activateRecursively 
package:flutter/…/widgets/framework.dart:3128
I/flutter (29320): #32     MultiChildRenderObjectElement.visitChildren 
package:flutter/…/widgets/framework.dart:5062
I/flutter (29320): #33     Element._activateRecursively 
package:flutter/…/widgets/framework.dart:3128
I/flutter (29320): #34     SingleChildRenderObjectElement.visitChildren 
package:flutter/…/widgets/framework.dart:4961
I/flutter (29320): #35     Element._activateRecursively 
package:flutter/…/widgets/framework.dart:3128
I/flutter (29320): #36     ComponentElement.visitChildren 
package:flutter/…/widgets/framework.dart:3867
I/flutter (29320): #37     Element._activateRecursively 
package:flutter/…/widgets/framework.dart:3128
I/flutter (29320): #38     ComponentElement.visitChildren 
package:flutter/…/widgets/framework.dart:3867
I/flutter (29320): #39     Element._activateRecursively 
package:flutter/…/widgets/framework.dart:3128
I/flutter (29320): #40     ComponentElement.visitChildren 
package:flutter/…/widgets/framework.dart:3867
I/flutter (29320): #41     Element._activateRecursively 
package:flutter/…/widgets/framework.dart:3128
I/flutter (29320): #42     MultiChildRenderObjectElement.visitChildren 
package:flutter/…/widgets/framework.dart:5062
I/flutter (29320): #43     Element._activateRecursively 
package:flutter/…/widgets/framework.dart:3128
I/flutter (29320): #44     ComponentElement.visitChildren 
package:flutter/…/widgets/framework.dart:3867
I/flutter (29320): #45     Element._activateRecursively 
package:flutter/…/widgets/framework.dart:3128
I/flutter (29320): #46     ComponentElement.visitChildren 
package:flutter/…/widgets/framework.dart:3867
I/flutter (29320): #47     Element._activateRecursively 
package:flutter/…/widgets/framework.dart:3128
I/flutter (29320): #48     ComponentElement.visitChildren 
package:flutter/…/widgets/framework.dart:3867
I/flutter (29320): #49     Element._activateRecursively 
package:flutter/…/widgets/framework.dart:3128
I/flutter (29320): #50     SingleChildRenderObjectElement.visitChildren 
package:flutter/…/widgets/framework.dart:4961
I/flutter (29320): #51     Element._activateRecursively 
package:flutter/…/widgets/framework.dart:3128
I/flutter (29320): #52     ComponentElement.visitChildren 
package:flutter/…/widgets/framework.dart:3867
I/flutter (29320): #53     Element._activateRecursively 
package:flutter/…/widgets/framework.dart:3128
I/flutter (29320): #54     SingleChildRenderObjectElement.visitChildren 
package:flutter/…/widgets/framework.dart:4961
I/flutter (29320): #55     Element._activateRecursively 
package:flutter/…/widgets/framework.dart:3128
I/flutter (29320): #56     ComponentElement.visitChildren 
package:flutter/…/widgets/framework.dart:3867
I/flutter (29320): #57     Element._activateRecursively 
package:flutter/…/widgets/framework.dart:3128
I/flutter (29320): #58     ComponentElement.visitChildren 
package:flutter/…/widgets/framework.dart:3867
I/flutter (29320): #59     Element._activateRecursively 
package:flutter/…/widgets/framework.dart:3128
I/flutter (29320): #60     ComponentElement.visitChildren 
package:flutter/…/widgets/framework.dart:3867
I/flutter (29320): #61     Element._activateRecursively 
package:flutter/…/widgets/framework.dart:3128
I/flutter (29320): #62     ComponentElement.visitChildren 
package:flutter/…/widgets/framework.dart:3867
I/flutter (29320): #63     Element._activateRecursively 
package:flutter/…/widgets/framework.dart:3128
I/flutter (29320): #64     ComponentElement.visitChildren 
package:flutter/…/widgets/framework.dart:3867
I/flutter (29320): #65     Element._activateRecursively 
package:flutter/…/widgets/framework.dart:3128
I/flutter (29320): #66     ComponentElement.visitChildren 
package:flutter/…/widgets/framework.dart:3867
I/flutter (29320): #67     Element._activateRecursively 
package:flutter/…/widgets/framework.dart:3128
I/flutter (29320): #68     ComponentElement.visitChildren 
package:flutter/…/widgets/framework.dart:3867
I/flutter (29320): #69     Element._activateRecursively 
package:flutter/…/widgets/framework.dart:3128
I/flutter (29320): #70     SingleChildRenderObjectElement.visitChildren 
package:flutter/…/widgets/framework.dart:4961
I/flutter (29320): #71     Element._activateRecursively 
package:flutter/…/widgets/framework.dart:3128
I/flutter (29320): #72     ComponentElement.visitChildren 
package:flutter/…/widgets/framework.dart:3867
I/flutter (29320): #73     Element._activateRecursively 
package:flutter/…/widgets/framework.dart:3128
I/flutter (29320): #74     SingleChildRenderObjectElement.visitChildren 
package:flutter/…/widgets/framework.dart:4961
I/flutter (29320): #75     Element._activateRecursively 
package:flutter/…/widgets/framework.dart:3128
I/flutter (29320): #76     SingleChildRenderObjectElement.visitChildren 
package:flutter/…/widgets/framework.dart:4961
I/flutter (29320): #77     Element._activateRecursively 
package:flutter/…/widgets/framework.dart:3128
I/flutter (29320): #78     SingleChildRenderObjectElement.visitChildren 
package:flutter/…/widgets/framework.dart:4961
I/flutter (29320): #79     Element._activateRecursively 
package:flutter/…/widgets/framework.dart:3128
I/flutter (29320): #80     SingleChildRenderObjectElement.visitChildren 
package:flutter/…/widgets/framework.dart:4961
I/flutter (29320): #81     Element._activateRecursively 
package:flutter/…/widgets/framework.dart:3128
I/flutter (29320): #82     ComponentElement.visitChildren 
package:flutter/…/widgets/framework.dart:3867
I/flutter (29320): #83     Element._activateRecursively 
package:flutter/…/widgets/framework.dart:3128
I/flutter (29320): #84     ComponentElement.visitChildren 
package:flutter/…/widgets/framework.dart:3867
I/flutter (29320): #85     Element._activateRecursively 
package:flutter/…/widgets/framework.dart:3128
I/flutter (29320): #86     ComponentElement.visitChildren 
package:flutter/…/widgets/framework.dart:3867
I/flutter (29320): #87     Element._activateRecursively 
package:flutter/…/widgets/framework.dart:3128
I/flutter (29320): #88     SingleChildRenderObjectElement.visitChildren 
package:flutter/…/widgets/framework.dart:4961
I/flutter (29320): #89     Element._activateRecursively 
package:flutter/…/widgets/framework.dart:3128
I/flutter (29320): #90     ComponentElement.visitChildren 
package:flutter/…/widgets/framework.dart:3867
I/flutter (29320): #91     Element._activateRecursively 
package:flutter/…/widgets/framework.dart:3128
I/flutter (29320): #92     SingleChildRenderObjectElement.visitChildren 
package:flutter/…/widgets/framework.dart:4961
I/flutter (29320): #93     Element._activateRecursively 
package:flutter/…/widgets/framework.dart:3128
I/flutter (29320): #94     ComponentElement.visitChildren 
package:flutter/…/widgets/framework.dart:3867
I/flutter (29320): #95     Element._activateRecursively 
package:flutter/…/widgets/framework.dart:3128
I/flutter (29320): #96     ComponentElement.visitChildren 
package:flutter/…/widgets/framework.dart:3867
I/flutter (29320): #97     Element._activateRecursively 
package:flutter/…/widgets/framework.dart:3128
I/flutter (29320): #98     SingleChildRenderObjectElement.visitChildren 
package:flutter/…/widgets/framework.dart:4961
I/flutter (29320): #99     Element._activateRecursively 
package:flutter/…/widgets/framework.dart:3128
I/flutter (29320): #100    ComponentElement.visitChildren 
package:flutter/…/widgets/framework.dart:3867
I/flutter (29320): #101    Element._activateRecursively 
package:flutter/…/widgets/framework.dart:3128
I/flutter (29320): #102    ComponentElement.visitChildren 
package:flutter/…/widgets/framework.dart:3867
I/flutter (29320): #103    Element._activateRecursively 
package:flutter/…/widgets/framework.dart:3128
I/flutter (29320): #104    ComponentElement.visitChildren 
package:flutter/…/widgets/framework.dart:3867
I/flutter (29320): #105    Element._activateRecursively 
package:flutter/…/widgets/framework.dart:3128
I/flutter (29320): #106    Element._activateWithParent 
package:flutter/…/widgets/framework.dart:3119
I/flutter (29320): #107    Element.inflateWidget 
package:flutter/…/widgets/framework.dart:3045
I/flutter (29320): #108    Element.updateChild 
package:flutter/…/widgets/framework.dart:2856
I/flutter (29320): #109    RenderObjectElement.updateChildren 
package:flutter/…/widgets/framework.dart:4756
I/flutter (29320): #110    MultiChildRenderObjectElement.update 
package:flutter/…/widgets/framework.dart:5089
I/flutter (29320): #111    Element.updateChild 
package:flutter/…/widgets/framework.dart:2845
I/flutter (29320): #112    _TheatreElement.update 
package:flutter/…/widgets/overlay.dart:607
I/flutter (29320): #113    Element.updateChild 
package:flutter/…/widgets/framework.dart:2845
I/flutter (29320): #114    ComponentElement.performRebuild 
package:flutter/…/widgets/framework.dart:3847
I/flutter (29320): #115    Element.rebuild 
package:flutter/…/widgets/framework.dart:3657
I/flutter (29320): #116    StatefulElement.update 
package:flutter/…/widgets/framework.dart:3991
I/flutter (29320): #117    Element.updateChild 
package:flutter/…/widgets/framework.dart:2845
I/flutter (29320): #118    ComponentElement.performRebuild 
package:flutter/…/widgets/framework.dart:3847
I/flutter (29320): #119    Element.rebuild 
package:flutter/…/widgets/framework.dart:3657
I/flutter (29320): #120    ProxyElement.update 
package:flutter/…/widgets/framework.dart:4103
I/flutter (29320): #121    _InheritedNotifierElement.update 
package:flutter/…/widgets/inherited_notifier.dart:94
I/flutter (29320): #122    Element.updateChild 
package:flutter/…/widgets/framework.dart:2845
I/flutter (29320): #123    SingleChildRenderObjectElement.update 
package:flutter/…/widgets/framework.dart:4980
I/flutter (29320): #124    Element.updateChild 
package:flutter/…/widgets/framework.dart:2845
I/flutter (29320): #125    ComponentElement.performRebuild 
package:flutter/…/widgets/framework.dart:3847
I/flutter (29320): #126    Element.rebuild 
package:flutter/…/widgets/framework.dart:3657
I/flutter (29320): #127    StatefulElement.update 
package:flutter/…/widgets/framework.dart:3991
I/flutter (29320): #128    Element.updateChild 
package:flutter/…/widgets/framework.dart:2845
I/flutter (29320): #129    SingleChildRenderObjectElement.update 
package:flutter/…/widgets/framework.dart:4980
I/flutter (29320): #130    Element.updateChild 
package:flutter/…/widgets/framework.dart:2845
I/flutter (29320): #131    SingleChildRenderObjectElement.update 
package:flutter/…/widgets/framework.dart:4980
I/flutter (29320): #132    Element.updateChild 
package:flutter/…/widgets/framework.dart:2845
I/flutter (29320): #133    ComponentElement.performRebuild 
package:flutter/…/widgets/framework.dart:3847
I/flutter (29320): #134    Element.rebuild 
package:flutter/…/widgets/framework.dart:3657
I/flutter (29320): #135    BuildOwner.buildScope 
package:flutter/…/widgets/framework.dart:2315
I/flutter (29320): #136    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding&WidgetsBinding.drawFrame 
package:flutter/…/widgets/binding.dart:700
I/flutter (29320): #137    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding._handlePersistentFrameCallback 
package:flutter/…/rendering/binding.dart:285
I/flutter (29320): #138    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._invokeFrameCallback 
package:flutter/…/scheduler/binding.dart:1012
I/flutter (29320): #139    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.handleDrawFrame 
package:flutter/…/scheduler/binding.dart:952
I/flutter (29320): #140    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._handleDrawFrame 
package:flutter/…/scheduler/binding.dart:864
I/flutter (29320): #144    _invoke  (dart:ui/hooks.dart:220:10)
I/flutter (29320): #145    _drawFrame  (dart:ui/hooks.dart:178:3)
I/flutter (29320): (elided 5 frames from class _AssertionError and package dart:async)
I/flutter (29320): ════════════════════════════════════════════════════════════════════════════════════════════════════
```

**Comment by iapicca** [comment]
Hi  @anasiqbal 
are you still experiencing this issue with the latest version of Flutter?
If so please reply attaching your `flutter doctor -v`,
you may also please post a self contained app on github 
to help us to better address the issue.
Thank you

**Comment by iapicca** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
  
Thanks for your contribution.
