### ISSUE TITLE
The TextAlign of TexField was broken!

### ISSUE THREAD

**Issue by leyan95** [flutter/flutter#33748]
when i add TextAlign to the TextFiel it was broken
```dart
                      Container(
                          width: 40,
                          alignment: Alignment.center,
                          child: TextField(
                            keyboardType: TextInputType.number,
                            textAlign: TextAlign.center,
                            style: new TextStyle(
                              fontSize: 20.0,
                              color: Colors.blueAccent,
                            ),
                            decoration: InputDecoration(
                              border: OutlineInputBorder(
                                borderSide: BorderSide(
                                    style: BorderStyle.none, width: 0),
                              ),
                              contentPadding: EdgeInsets.only(),
                            ),
                          ),
                        )
```
## Logs

```
I/flutter ( 4713): ══╡ EXCEPTION CAUGHT BY RENDERING LIBRARY ╞═════════════════════════════════════════════════════════
I/flutter ( 4713): The following assertion was thrown during performLayout():
I/flutter ( 4713): Please see the documentation for computeDistanceToActualBaseline for the required calling
I/flutter ( 4713): conventions of this method.
I/flutter ( 4713): 'package:flutter/src/rendering/box.dart': Failed assertion: line 1642 pos 12: '!_debugDoingBaseline'
I/flutter ( 4713): Either the assertion indicates an error in the framework itself, or we should provide substantially
I/flutter ( 4713): more information in this error message to help you determine and fix the underlying cause.
I/flutter ( 4713): In either case, please report this assertion by filing a bug on GitHub:
I/flutter ( 4713):   https://github.com/flutter/flutter/issues/new?template=BUG.md
I/flutter ( 4713): When the exception was thrown, this was the stack:
I/flutter ( 4713): #2      RenderBox.getDistanceToBaseline (package:flutter/src/rendering/box.dart:1642:12)
I/flutter ( 4713): #3      _RenderDecoration._layoutLineBox (package:flutter/src/material/input_decorator.dart:828:33)
I/flutter ( 4713): #4      _RenderDecoration._layout (package:flutter/src/material/input_decorator.dart:868:34)
I/flutter ( 4713): #5      _RenderDecoration.performLayout (package:flutter/src/material/input_decorator.dart:1071:44)
I/flutter ( 4713): #6      RenderObject.layout (package:flutter/src/rendering/object.dart:1644:7)
I/flutter ( 4713): #7      _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter ( 4713): #8      RenderObject.layout (package:flutter/src/rendering/object.dart:1644:7)
I/flutter ( 4713): #9      _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter ( 4713): #10     RenderObject.layout (package:flutter/src/rendering/object.dart:1644:7)
I/flutter ( 4713): #11     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter ( 4713): #12     RenderObject.layout (package:flutter/src/rendering/object.dart:1644:7)
I/flutter ( 4713): #13     RenderPositionedBox.performLayout (package:flutter/src/rendering/shifted_box.dart:385:13)
I/flutter ( 4713): #14     RenderObject.layout (package:flutter/src/rendering/object.dart:1644:7)
I/flutter ( 4713): #15     RenderConstrainedBox.performLayout (package:flutter/src/rendering/proxy_box.dart:259:13)
I/flutter ( 4713): #16     RenderObject.layout (package:flutter/src/rendering/object.dart:1644:7)
I/flutter ( 4713): #17     RenderFlex.performLayout (package:flutter/src/rendering/flex.dart:738:15)
I/flutter ( 4713): #18     RenderObject.layout (package:flutter/src/rendering/object.dart:1644:7)
I/flutter ( 4713): #19     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter ( 4713): #20     RenderObject.layout (package:flutter/src/rendering/object.dart:1644:7)
I/flutter ( 4713): #21     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter ( 4713): #22     RenderObject.layout (package:flutter/src/rendering/object.dart:1644:7)
I/flutter ( 4713): #23     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter ( 4713): #24     RenderObject.layout (package:flutter/src/rendering/object.dart:1644:7)
I/flutter ( 4713): #25     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter ( 4713): #26     _RenderCustomClip.performLayout (package:flutter/src/rendering/proxy_box.dart:1215:11)
I/flutter ( 4713): #27     RenderObject.layout (package:flutter/src/rendering/object.dart:1644:7)
I/flutter ( 4713): #28     RenderPadding.performLayout (package:flutter/src/rendering/shifted_box.dart:199:11)
I/flutter ( 4713): #29     RenderObject.layout (package:flutter/src/rendering/object.dart:1644:7)
I/flutter ( 4713): #30     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter ( 4713): #31     RenderObject.layout (package:flutter/src/rendering/object.dart:1644:7)
I/flutter ( 4713): #32     RenderFlex.performLayout (package:flutter/src/rendering/flex.dart:738:15)
I/flutter ( 4713): #33     RenderObject.layout (package:flutter/src/rendering/object.dart:1644:7)
I/flutter ( 4713): #34     RenderFlex.performLayout (package:flutter/src/rendering/flex.dart:738:15)
I/flutter ( 4713): #35     RenderObject.layout (package:flutter/src/rendering/object.dart:1644:7)
I/flutter ( 4713): #36     RenderListBody.performLayout (package:flutter/src/rendering/list_body.dart:148:15)
I/flutter ( 4713): #37     RenderObject.layout (package:flutter/src/rendering/object.dart:1644:7)
I/flutter ( 4713): #38     RenderPadding.performLayout (package:flutter/src/rendering/shifted_box.dart:199:11)
I/flutter ( 4713): #39     RenderObject.layout (package:flutter/src/rendering/object.dart:1644:7)
I/flutter ( 4713): #40     _RenderSingleChildViewport.performLayout (package:flutter/src/widgets/single_child_scroll_view.dart:497:13)
I/flutter ( 4713): #41     RenderObject.layout (package:flutter/src/rendering/object.dart:1644:7)
I/flutter ( 4713): #42     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter ( 4713): #43     RenderObject.layout (package:flutter/src/rendering/object.dart:1644:7)
I/flutter ( 4713): #44     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter ( 4713): #45     RenderObject.layout (package:flutter/src/rendering/object.dart:1644:7)
I/flutter ( 4713): #46     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter ( 4713): #47     RenderObject.layout (package:flutter/src/rendering/object.dart:1644:7)
I/flutter ( 4713): #48     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter ( 4713): #49     RenderObject.layout (package:flutter/src/rendering/object.dart:1644:7)
I/flutter ( 4713): #50     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter ( 4713): #51     RenderObject.layout (package:flutter/src/rendering/object.dart:1644:7)
I/flutter ( 4713): #52     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter ( 4713): #53     RenderObject.layout (package:flutter/src/rendering/object.dart:1644:7)
I/flutter ( 4713): #54     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter ( 4713): #55     RenderObject.layout (package:flutter/src/rendering/object.dart:1644:7)
I/flutter ( 4713): #56     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter ( 4713): #57     RenderObject.layout (package:flutter/src/rendering/object.dart:1644:7)
I/flutter ( 4713): #58     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter ( 4713): #59     RenderObject.layout (package:flutter/src/rendering/object.dart:1644:7)
I/flutter ( 4713): #60     RenderFlex.performLayout (package:flutter/src/rendering/flex.dart:798:17)
I/flutter ( 4713): #61     RenderObject.layout (package:flutter/src/rendering/object.dart:1644:7)
I/flutter ( 4713): #62     RenderConstrainedBox.performLayout (package:flutter/src/rendering/proxy_box.dart:259:13)
I/flutter ( 4713): #63     RenderObject.layout (package:flutter/src/rendering/object.dart:1644:7)
I/flutter ( 4713): #64     RenderIntrinsicWidth.performLayout (package:flutter/src/rendering/proxy_box.dart:640:13)
I/flutter ( 4713): #65     RenderObject.layout (package:flutter/src/rendering/object.dart:1644:7)
I/flutter ( 4713): #66     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter ( 4713): #67     RenderObject.layout (package:flutter/src/rendering/object.dart:1644:7)
I/flutter ( 4713): #68     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter ( 4713): #69     RenderObject.layout (package:flutter/src/rendering/object.dart:1644:7)
I/flutter ( 4713): #70     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter ( 4713): #71     _RenderCustomClip.performLayout (package:flutter/src/rendering/proxy_box.dart:1215:11)
I/flutter ( 4713): #72     RenderObject.layout (package:flutter/src/rendering/object.dart:1644:7)
I/flutter ( 4713): #73     RenderConstrainedBox.performLayout (package:flutter/src/rendering/proxy_box.dart:259:13)
I/flutter ( 4713): #74     RenderObject.layout (package:flutter/src/rendering/object.dart:1644:7)
I/flutter ( 4713): #75     RenderPositionedBox.performLayout (package:flutter/src/rendering/shifted_box.dart:385:13)
I/flutter ( 4713): #76     RenderObject.layout (package:flutter/src/rendering/object.dart:1644:7)
I/flutter ( 4713): #77     RenderPadding.performLayout (package:flutter/src/rendering/shifted_box.dart:199:11)
I/flutter ( 4713): #78     RenderObject.layout (package:flutter/src/rendering/object.dart:1644:7)
I/flutter ( 4713): #79     RenderPadding.performLayout (package:flutter/src/rendering/shifted_box.dart:199:11)
I/flutter ( 4713): #80     RenderObject.layout (package:flutter/src/rendering/object.dart:1644:7)
I/flutter ( 4713): #81     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter ( 4713): #82     RenderObject.layout (package:flutter/src/rendering/object.dart:1644:7)
I/flutter ( 4713): #83     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter ( 4713): #84     RenderObject.layout (package:flutter/src/rendering/object.dart:1644:7)
I/flutter ( 4713): #85     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter ( 4713): #86     RenderObject.layout (package:flutter/src/rendering/object.dart:1644:7)
I/flutter ( 4713): #87     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter ( 4713): #88     RenderObject.layout (package:flutter/src/rendering/object.dart:1644:7)
I/flutter ( 4713): #89     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter ( 4713): #90     RenderObject.layout (package:flutter/src/rendering/object.dart:1644:7)
I/flutter ( 4713): #91     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter ( 4713): #92     RenderObject.layout (package:flutter/src/rendering/object.dart:1644:7)
I/flutter ( 4713): #93     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter ( 4713): #94     RenderOffstage.performLayout (package:flutter/src/rendering/proxy_box.dart:3011:13)
I/flutter ( 4713): #95     RenderObject.layout (package:flutter/src/rendering/object.dart:1644:7)
I/flutter ( 4713): #96     RenderStack.performLayout (package:flutter/src/rendering/stack.dart:510:15)
I/flutter ( 4713): #97     RenderObject.layout (package:flutter/src/rendering/object.dart:1644:7)
I/flutter ( 4713): #98     __RenderTheatre&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter ( 4713): #99     RenderObject.layout (package:flutter/src/rendering/object.dart:1644:7)
I/flutter ( 4713): #100    _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter ( 4713): #101    RenderObject.layout (package:flutter/src/rendering/object.dart:1644:7)
I/flutter ( 4713): #102    _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter ( 4713): #103    RenderObject.layout (package:flutter/src/rendering/object.dart:1644:7)
I/flutter ( 4713): #104    _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter ( 4713): #105    RenderObject.layout (package:flutter/src/rendering/object.dart:1644:7)
I/flutter ( 4713): #106    _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter ( 4713): #107    RenderObject.layout (package:flutter/src/rendering/object.dart:1644:7)
I/flutter ( 4713): #108    _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter ( 4713): #109    RenderObject.layout (package:flutter/src/rendering/object.dart:1644:7)
I/flutter ( 4713): #110    RenderView.performLayout (package:flutter/src/rendering/view.dart:151:13)
I/flutter ( 4713): #111    RenderObject._layoutWithoutResize (package:flutter/src/rendering/object.dart:1519:7)
I/flutter ( 4713): #112    PipelineOwner.flushLayout (package:flutter/src/rendering/object.dart:766:18)
I/flutter ( 4713): #113    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding.drawFrame (package:flutter/src/rendering/binding.dart:336:19)
I/flutter ( 4713): #114    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding&WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:701:13)
Reloaded 10 of 563 libraries in 1,129ms.
I/flutter ( 4713): #115    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:275:5)
I/flutter ( 4713): #116    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1008:15)
I/flutter ( 4713): #117    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:948:9)
I/flutter ( 4713): #118    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.scheduleWarmUpFrame.<anonymous closure> (package:flutter/src/scheduler/binding.dart:769:7)
I/flutter ( 4713): #120    _Timer._runTimers (dart:isolate/runtime/lib/timer_impl.dart:382:19)
I/flutter ( 4713): #121    _Timer._handleMessage (dart:isolate/runtime/lib/timer_impl.dart:416:5)
I/flutter ( 4713): #122    _RawReceivePortImpl._handleMessage (dart:isolate/runtime/lib/isolate_patch.dart:171:12)
I/flutter ( 4713): (elided 3 frames from class _AssertionError and package dart:async)
I/flutter ( 4713): The following RenderObject was being processed when the exception was fired:
I/flutter ( 4713):   _RenderDecoration#824f5 relayoutBoundary=up34 NEEDS-LAYOUT NEEDS-PAINT
I/flutter ( 4713):   creator: _Decorator ← InputDecorator ← AnimatedBuilder ← Listener ← RawGestureDetector ←
I/flutter ( 4713):   TextSelectionGestureDetector ← IgnorePointer ← Semantics ← TextField ← Align ← ConstrainedBox ←
I/flutter ( 4713):   Container ← ⋯
I/flutter ( 4713):   parentData: <none> (can use size)
I/flutter ( 4713):   constraints: BoxConstraints(0.0<=w<=40.0, 0.0<=h<=Infinity)
I/flutter ( 4713):   size: MISSING
I/flutter ( 4713): This RenderObject had the following descendants (showing up to depth 5):
I/flutter ( 4713):   RenderRepaintBoundary#c49c5 NEEDS-LAYOUT NEEDS-PAINT
I/flutter ( 4713):     RenderRepaintBoundary#ca3b5 NEEDS-LAYOUT NEEDS-PAINT
I/flutter ( 4713):       RenderCustomPaint#8b2ad NEEDS-LAYOUT NEEDS-PAINT
I/flutter ( 4713):         RenderRepaintBoundary#4bc8e NEEDS-LAYOUT NEEDS-PAINT
I/flutter ( 4713):           RenderPointerListener#b7dee NEEDS-LAYOUT NEEDS-PAINT
I/flutter ( 4713):   RenderConstrainedBox#94703 relayoutBoundary=up35 NEEDS-PAINT
I/flutter ( 4713):   RenderCustomPaint#6cbe3 NEEDS-LAYOUT NEEDS-PAINT
I/flutter ( 4713): ════════════════════════════════════════════════════════════════════════════════════════════════════
I/flutter ( 4713): Another exception was thrown: RenderBox was not laid out: _RenderDecoration#824f5 relayoutBoundary=up34 NEEDS-PAINT
I/flutter ( 4713): Another exception was thrown: RenderBox was not laid out: RenderPointerListener#c4740 relayoutBoundary=up33 NEEDS-PAINT
I/flutter ( 4713): Another exception was thrown: RenderBox was not laid out: RenderIgnorePointer#1cd97 relayoutBoundary=up32 NEEDS-PAINT
I/flutter ( 4713): Another exception was thrown: RenderBox was not laid out: RenderSemanticsAnnotations#30b34 relayoutBoundary=up31 NEEDS-PAINT
I/flutter ( 4713): Another exception was thrown: RenderBox was not laid out: RenderPositionedBox#1f4df relayoutBoundary=up30 NEEDS-PAINT
I/flutter ( 4713): Another exception was thrown: Please see the documentation for computeDistanceToActualBaseline for the required calling conventions of this method.
I/flutter ( 4713): Another exception was thrown: Please see the documentation for computeDistanceToActualBaseline for the required calling conventions of this method.
I/flutter ( 4713): Another exception was thrown: Please see the documentation for computeDistanceToActualBaseline for the required calling conventions of this method.
I/flutter ( 4713): Another exception was thrown: Please see the documentation for computeDistanceToActualBaseline for the required calling conventions of this method.
I/flutter ( 4713): Another exception was thrown: Please see the documentation for computeDistanceToActualBaseline for the required calling conventions of this method.
I/flutter ( 4713): Another exception was thrown: Please see the documentation for computeDistanceToActualBaseline for the required calling conventions of this method.
I/flutter ( 4713): Another exception was thrown: Please see the documentation for computeDistanceToActualBaseline for the required calling conventions of this method.
I/flutter ( 4713): Another exception was thrown: Please see the documentation for computeDistanceToActualBaseline for the required calling conventions of this method.
I/flutter ( 4713): Another exception was thrown: Please see the documentation for computeDistanceToActualBaseline for the required calling conventions of this method.
I/flutter ( 4713): Another exception was thrown: Please see the documentation for computeDistanceToActualBaseline for the required calling conventions of this method.
I/flutter ( 4713): Another exception was thrown: RenderBox was not laid out: RenderRepaintBoundary#c49c5 NEEDS-LAYOUT NEEDS-PAINT

```

**Comment by HansMuller** [comment]
@leyan95 - could you provide the output of `flutter doctor`? It would help to know what version of Flutter you're running.

**Comment by justinmc** [comment]
I tried this on a physical Pixel 2 and didn't get an exception.

```dart
import 'package:flutter/material.dart';

void main() => runApp(App());

class App extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: "test",
      theme: ThemeData(
        primarySwatch: Colors.purple
      ),
      home: MyWidget()
    );
  }
}

class MyWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Container(
        width: 40,
        alignment: Alignment.center,
        child: TextField(
          keyboardType: TextInputType.number,
          textAlign: TextAlign.center,
          style: TextStyle(
            fontSize: 20.0,
            color: Colors.blueAccent,
          ),
          decoration: InputDecoration(
            border: OutlineInputBorder(
              borderSide: BorderSide(
                  style: BorderStyle.none, width: 0),
            ),
            contentPadding: EdgeInsets.only(),
          ),
        ),
      ),
    );
  }
}
```

**Comment by leyan95** [comment]
I didn't do anything. It repaired itself. I couldn't feel my head.

## flutter doctor -v
```shell
[√] Flutter (Channel master, v1.3.14-pre.66, on Microsoft Windows [Version 10.0.17134.765], locale zh-CN)
    • Flutter version 1.3.14-pre.66 at D:\Dev\Flutter
    • Framework revision 91b71ba964 (2 months ago), 2019-03-24 16:18:43 -0400
    • Engine revision dcc72c7176
    • Dart version 2.2.1 (build 2.2.1-dev.2.0 None)
```

**Comment by justinmc** [comment]
Alright, hopefully a recent code change fixed it!  Please reopen if you run into this again.

**Comment by leyan95** [comment]
@justinmc I will. Thank you for your kind help.
