### ISSUE TITLE
TextFormField typed some Chinese, it will flash a blue line on Android devices

### ISSUE THREAD

**Issue by huangbao21** [flutter/flutter#33758]
## Steps to Reproduce

![TIM图片20190603193741](https://user-images.githubusercontent.com/17422412/58799164-1d099000-8637-11e9-8380-016832cff184.gif)

![image](https://user-images.githubusercontent.com/17422412/58799214-4d512e80-8637-11e9-897d-fd2815868598.png)

```
TextFormField(
                    autovalidate: true,
                    style: TextStyle(fontSize: 16),
                    controller: _contentController,
                    maxLength: 500,
                    maxLines: 6,
                    decoration: InputDecoration(
                      border: InputBorder.none,
                      filled: true,
                      fillColor: Colors.grey[200],
                      hintStyle:
                          TextStyle(color: Colors.grey[400], fontSize: 16),
                      hintText: "填写10个字以上的问题描述或意见建议，以便我们更好地提供帮助",
                    ),
                    validator: (String v) {
                      return v.trim().length > 0 ? null : '请输入内容';
                    },
                  )
```

## Logs

```
[  +31 ms] executing: [D:\d\flutter\] git log -n 1 --pretty=format:%H
[ +110 ms] Exit code 0 from: git log -n 1 --pretty=format:%H
[   +2 ms] bd9d31abd9e11a4cd691c431db69cee0ad407f85
[        ] executing: [D:\d\flutter\] git describe --match v*.*.* --first-parent --long --tags
[  +86 ms] Exit code 0 from: git describe --match v*.*.* --first-parent --long --tags
[        ] v1.6.7-33-gbd9d31abd
[  +11 ms] executing: [D:\d\flutter\] git rev-parse --abbrev-ref --symbolic @{u}
[  +72 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/master
[        ] executing: [D:\d\flutter\] git ls-remote --get-url origin
[  +72 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[ +115 ms] executing: [D:\d\flutter\] git rev-parse --abbrev-ref HEAD
[  +78 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] master
[  +88 ms] executing: D:\d\Program Files\Android\Sdk\platform-tools\adb.exe devices -l
[  +42 ms] Exit code 0 from: D:\d\Program Files\Android\Sdk\platform-tools\adb.exe devices -l
[        ] List of devices attached
           37ff6895               device product:hero2qltezc model:SM_G9350 device:hero2qltechn transport_id:6
           emulator-5554          device product:sdk_gphone_x86 model:Android_SDK_built_for_x86 device:generic_x86
           transport_id:1
[  +68 ms] More than one device connected; please specify a device with the '-d <deviceId>' flag, or use '-d all' to act on alldevices.
[   +5 ms] D:\d\Program Files\Android\Sdk\platform-tools\adb.exe -s 37ff6895 shell getprop
[ +190 ms] ro.hardware = qcom
[   +4 ms] D:\d\Program Files\Android\Sdk\platform-tools\adb.exe -s emulator-5554 shell getprop
[  +78 ms] ro.hardware = ranchu
[   +2 ms] SM G9350                  • 37ff6895      • android-arm64 • Android 8.0.0 (API 26)
[   +1 ms] Android SDK built for x86 • emulator-5554 • android-x86   • Android 9 (API 28) (emulator)
[   +9 ms] "flutter run" took 570ms.
[        ] "flutter run" took 570ms.

#0      throwToolExit (package:flutter_tools/src/base/common.dart:24:3)
#1      RunCommand.validateCommand (package:flutter_tools/src/commands/run.dart:275:7)
<asynchronous suspension>
#2      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:467:11)
<asynchronous suspension>
#3      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:424:33)
<asynchronous suspension>
#4      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:29)
<asynchronous suspension>
#5      _rootRun (dart:async/zone.dart:1124:13)
#6      _CustomZone.run (dart:async/zone.dart:1021:19)
#7      _runZoned (dart:async/zone.dart:1516:10)
#8      runZoned (dart:async/zone.dart:1463:12)
#9      AppContext.run (package:flutter_tools/src/base/context.dart:152:18)
<asynchronous suspension>
#10     FlutterCommand.run (package:flutter_tools/src/runner/flutter_command.dart:415:20)
#11     CommandRunner.runCommand (package:args/command_runner.dart:196:27)
<asynchronous suspension>
#12     FlutterCommandRunner.runCommand.<anonymous closure>
(package:flutter_tools/src/runner/flutter_command_runner.dart:396:21)
<asynchronous suspension>
#13     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:29)
<asynchronous suspension>
#14     _rootRun (dart:async/zone.dart:1124:13)
#15     _CustomZone.run (dart:async/zone.dart:1021:19)
#16     _runZoned (dart:async/zone.dart:1516:10)
#17     runZoned (dart:async/zone.dart:1463:12)
#18     AppContext.run (package:flutter_tools/src/base/context.dart:152:18)
<asynchronous suspension>
#19     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:356:19)
<asynchronous suspension>
#20     CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:111:29)
#21     new Future.sync (dart:async/future.dart:224:31)
#22     CommandRunner.run (package:args/command_runner.dart:111:11)
#23     FlutterCommandRunner.run (package:flutter_tools/src/runner/flutter_command_runner.dart:242:18)
#24     run.<anonymous closure> (package:flutter_tools/runner.dart:60:20)
<asynchronous suspension>
#25     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:29)
<asynchronous suspension>
#26     _rootRun (dart:async/zone.dart:1124:13)
#27     _CustomZone.run (dart:async/zone.dart:1021:19)
#28     _runZoned (dart:async/zone.dart:1516:10)
#29     runZoned (dart:async/zone.dart:1463:12)
#30     AppContext.run (package:flutter_tools/src/base/context.dart:152:18)
<asynchronous suspension>
#31     runInContext (package:flutter_tools/src/context_runner.dart:54:24)
<asynchronous suspension>
#32     run (package:flutter_tools/runner.dart:51:10)
#33     main (package:flutter_tools/executable.dart:62:9)
<asynchronous suspension>
#34     main (file:///D:/d/flutter/packages/flutter_tools/bin/flutter_tools.dart:8:3)
#35     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:298:32)
#36     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:171:12)
```

```
Analyzing chips_flutter...

   info - This function has a return type of 'Future<bool>', but doesn't end with a return statement -
          lib\feedback_widget.dart:16:18 - missing_return
   info - This function has a return type of 'Route', but doesn't end with a return statement - lib\main.dart:89:26 -
          missing_return
   info - This function has a return type of 'Future<bool>', but doesn't end with a return statement -
          lib\medal_widget.dart:36:18 - missing_return
   info - This function has a return type of 'Future<bool>', but doesn't end with a return statement -
          lib\profile_widget.dart:35:36 - missing_return
   info - This function has a return type of 'Future<bool>', but doesn't end with a return statement -
          lib\rank_overview.dart:34:18 - missing_return
   info - This function has a return type of 'Future<bool>', but doesn't end with a return statement -
          lib\task_widget.dart:33:18 - missing_return

6 issues found. (ran in 12.8s)
```

```
[√] Flutter (Channel master, v1.6.8-pre.33, on Microsoft Windows [Version 10.0.17763.529], locale zh-CN)
    • Flutter version 1.6.8-pre.33 at D:\d\flutter
    • Framework revision bd9d31abd9 (4 hours ago), 2019-06-03 03:28:55 -0400
    • Engine revision 184b6e36e8
    • Dart version 2.3.2 (build 2.3.2-dev.0.0 224f82c21c)


[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at D:\d\Program Files\Android\Sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = D:\d\Program Files\Android\Sdk
    • Java binary at: D:\d\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)
    • All Android licenses accepted.

[√] Android Studio (version 3.3)
    • Android Studio at D:\d\Program Files\Android\Android Studio
    • Flutter plugin version 32.0.1
    • Dart plugin version 182.5215
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)

[√] IntelliJ IDEA Ultimate Edition (version 2018.1)
    • IntelliJ at D:\d\Program Files\JetBrains\IntelliJ IDEA 2018.1.1
    • Dart plugin version 181.4445.29

[√] Connected device (2 available)
    • SM G9350                  • 37ff6895      • android-arm64 • Android 8.0.0 (API 26)
    • Android SDK built for x86 • emulator-5554 • android-x86   • Android 9 (API 28) (emulator)

• No issues found!
```

**Comment by TahaTesser** [comment]
Hi @huangbao21 
Are you still experiencing this issue?
Thank you

**Comment by VladyslavBondarenko** [comment]
@huangbao21 
I can't reproduce it with flutter v1.16.1
Please comment if the issue still persists and I'll reopen it
Thank you
