### ISSUE TITLE
The method 'goIdle' was called on null. NoSuchMethodError was thrown while notifying listeners for AnimationController

### ISSUE THREAD

**Issue by pisa97** [flutter/flutter#33753]
This is my error's logs:

```
flutter: ══╡ EXCEPTION CAUGHT BY ANIMATION LIBRARY ╞═════════════════════
flutter: The following NoSuchMethodError was thrown while notifying listeners for AnimationController:
flutter: The method 'goIdle' was called on null.
flutter: Receiver: null
flutter: Tried calling: goIdle()
flutter:
flutter: When the exception was thrown, this was the stack:
flutter: #0      BallisticScrollActivity._tick (package:flutter/src/widgets/scroll_activity.dart:535)
flutter: #1      _AnimationController&Animation&AnimationEagerListenerMixin&AnimationLocalListenersMixin.notifyListeners (package:flutter/src/animation/listener_helpers.dart:126)
flutter: #2      AnimationController._tick (package:flutter/src/animation/animation_controller.dart:750)
flutter: #3      Ticker._tick (package:flutter/src/scheduler/ticker.dart:228)
flutter: #4      _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1012)
flutter: #5      _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.handleBeginFrame.<anonymous closure> (package:flutter/src/scheduler/binding.dart:928)
flutter: #6      __InternalLinkedHashMap&_HashVMBase&MapMixin&_LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:367)
flutter: #7      _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.handleBeginFrame (package:flutter/src/scheduler/binding.dart:926)
flutter: #8      _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._handleBeginFrame (package:flutter/src/scheduler/binding.dart:856)
flutter: #12     _invoke1 (dart:ui/hooks.dart:233)
flutter: #13     _beginFrame (dart:ui/hooks.dart:172)
flutter: (elided 3 frames from package dart:async)
flutter:
flutter: The AnimationController notifying listeners was:
flutter:   AnimationController#36d81(▶ -75.000; paused; DISPOSED; for BallisticScrollActivity)
```

This happen when I scroll very fast to the top of the scroll view which is embedded into a NotificationListener widget. Does anyone know the problem? Is this the best approach to do something while scrolling or not? Thanks you in advance. Arcangelo :)

**Comment by Piinks** [comment]
Hi @pisa97, Can you post a reproduction of the issue? We will need more information to help you resolve it.

**Comment by JohnSnooow** [comment]
same error happen to me,      Help me... I cant reproduce this exception, but happens many on production

**Comment by Jordhan-Carvalho** [comment]
Having the same issue after adding this piece of code on the callback function of a ScrollControler listener
`double newPos = _scrollController.position.pixels - 40;
  _scrollController.position.moveTo(newPos, duration: Duration(milliseconds: 1500));`

Only happens when scrolling top to bottom fast.

**Comment by yatindeokar** [comment]
I am facing the same issue any solution

Error: `The method 'goIdle' was called on null.
Receiver: null
Tried calling: goIdle()`
**File: (package:flutter/src/widgets/scroll_activity.dart:535:16)**
void _tick() {
    if (!applyMoveTo(_controller.value))
      delegate.goIdle();
  }

**Comment by MOOUDE** [comment]
I am facing the same issue here as well

**Comment by JulianDavidGamboa** [comment]
A possible solution is that they can validate that the controller does the animation only if the position is different from null      

```
  if (_pageController.position != null) {
          _pageController.position.animateTo(
            _screenSize.width * 0.3,
            duration: Duration(milliseconds: 1000),
            curve: Curves.elasticOut,
          );
        }
```

In this way the error will stop coming out.
