### ISSUE TITLE
video_player crashes with a video made by Samsung Galaxy s9

### ISSUE THREAD

**Issue by Vitaly-V** [flutter/flutter#33841]
## Steps to Reproduce

If I use Samsung Galaxy s9 to make a video and try to show this video in tabs it crashes.
 E.g 1st tab shows video, 2nd doesn't, 3rd shows, etc...
[main.dart](https://gist.github.com/Vitaly-V/929298ea19048343b57d3ec6251ea619)

[Video sample from Galaxy s9](https://drive.google.com/open?id=1-y4MXiisWQIc9E965krKiOrSpYRmJkg6)

## Logs

```
[   +2 ms] 🔥  To hot reload changes while running, press "r". To hot restart (and rebuild state), press "R".
[   +1 ms] An Observatory debugger and profiler on Redmi Note 5 is available at: http://127.0.0.1:57008/01h5V8BgpQc=/
[        ] For a more detailed help message, press "h". To detach, press "d"; to quit, press "q".
[+1773 ms] W/AMessage(15232): failed to deliver message as target handler 1 is gone.
[+3837 ms] I/ExoPlayerImpl(15232): Init d6b8442 [ExoPlayerLib/2.9.6] [whyred, Redmi Note 5, Xiaomi, 27]
[  +27 ms] I/zygote64(15232): Do partial code cache collection, code=30KB, data=25KB
[        ] I/zygote64(15232): After code cache collection, code=30KB, data=25KB
[        ] I/zygote64(15232): Increasing code cache capacity to 128KB
[  +18 ms] I/OMXClient(15232): Treble IOmx obtained
[  +25 ms] D/SurfaceUtils(15232): connecting to surface 0x6fc798c010, reason connectToSurface
[        ] I/MediaCodec(15232): [OMX.qcom.video.decoder.avc] setting surface generation to 15597571
[        ] D/SurfaceUtils(15232): disconnecting from surface 0x6fc798c010, reason connectToSurface(reconnect)
[        ] D/SurfaceUtils(15232): connecting to surface 0x6fc798c010, reason connectToSurface(reconnect)
[   +5 ms] I/ExtendedACodec(15232): setupVideoDecoder()
[   +6 ms] E/ACodec  (15232): [OMX.qcom.video.decoder.avc] configureCodec returning error -12
[        ] E/ACodec  (15232): signalError(omxError 0x80001001, internalError -12)
[        ] E/MediaCodec(15232): Codec reported err 0xfffffff4, actionCode 0, while in state 3
[        ] W/MediaAnalyticsItem(15232): Unable to record:
(codec:0:-1:-11:0:10:android.media.mediacodec.codec=OMX.qcom.video.decoder.avc:android.media.mediacodec.mode=video:android.media.mediacodec.secure=0:android.media.mediacodec.width=3840:android.media.mediacodec.height=2160:android.me
dia.mediacodec.rotation-degrees=90:android.media.mediacodec.maxwidth=3840:android.media.mediacodec.maxheight=2160:android.media.mediacodec.errcode=-12:android.media.mediacodec.errstate=3:) [forcenew=0]
[   +1 ms] D/SurfaceUtils(15232): disconnecting from surface 0x6fc798c010, reason disconnectFromSurface
[        ] E/MediaCodec(15232): configure failed with err 0xfffffff4, resetting...
[   +8 ms] I/OMXClient(15232): Treble IOmx obtained
[  +24 ms] W/MediaAnalyticsItem(15232): Unable to record: (codec:0:-1:-11:0:3:android.media.mediacodec.codec=OMX.qcom.video.decoder.avc:android.media.mediacodec.mode=video:android.media.mediacodec.secure=0:) [forcenew=0]
[   +7 ms] W/MediaCodecRenderer(15232): Failed to initialize decoder: OMX.qcom.video.decoder.avc
[        ] W/MediaCodecRenderer(15232): android.media.MediaCodec$CodecException: Error 0xfffffff4
[        ] W/MediaCodecRenderer(15232):         at android.media.MediaCodec.native_configure(Native Method)
[        ] W/MediaCodecRenderer(15232):         at android.media.MediaCodec.configure(MediaCodec.java:1943)
[        ] W/MediaCodecRenderer(15232):         at android.media.MediaCodec.configure(MediaCodec.java:1872)
[        ] W/MediaCodecRenderer(15232):         at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.configureCodec(MediaCodecVideoRenderer.java:483)
[        ] W/MediaCodecRenderer(15232):         at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.initCodec(MediaCodecRenderer.java:805)
[        ] W/MediaCodecRenderer(15232):         at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.initCodecWithFallback(MediaCodecRenderer.java:745)
[        ] W/MediaCodecRenderer(15232):         at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.maybeInitCodec(MediaCodecRenderer.java:474)
[        ] W/MediaCodecRenderer(15232):         at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.reinitializeCodec(MediaCodecRenderer.java:1261)
[        ] W/MediaCodecRenderer(15232):         at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.onInputFormatChanged(MediaCodecRenderer.java:1111)
[        ] W/MediaCodecRenderer(15232):         at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.onInputFormatChanged(MediaCodecVideoRenderer.java:552)
[        ] W/MediaCodecRenderer(15232):         at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:647)
[        ] W/MediaCodecRenderer(15232):         at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:529)
[        ] W/MediaCodecRenderer(15232):         at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:300)
[        ] W/MediaCodecRenderer(15232):         at android.os.Handler.dispatchMessage(Handler.java:102)
[        ] W/MediaCodecRenderer(15232):         at android.os.Looper.loop(Looper.java:176)
[        ] W/MediaCodecRenderer(15232):         at android.os.HandlerThread.run(HandlerThread.java:65)
[        ] E/ExoPlayerImplInternal(15232): Playback error.
[        ] E/ExoPlayerImplInternal(15232): com.google.android.exoplayer2.ExoPlaybackException: com.google.android.exoplayer2.mediacodec.MediaCodecRenderer$DecoderInitializationException: Decoder init failed:
OMX.qcom.video.decoder.avc, Format(1, null, null, video/avc, null, -1, null, [3840, 2160, 30.0], [-1, -1])
[        ] E/ExoPlayerImplInternal(15232):      at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.maybeInitCodec(MediaCodecRenderer.java:479)
[        ] E/ExoPlayerImplInternal(15232):      at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.reinitializeCodec(MediaCodecRenderer.java:1261)
[        ] E/ExoPlayerImplInternal(15232):      at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.onInputFormatChanged(MediaCodecRenderer.java:1111)
[        ] E/ExoPlayerImplInternal(15232):      at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.onInputFormatChanged(MediaCodecVideoRenderer.java:552)
[        ] E/ExoPlayerImplInternal(15232):      at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:647)
[        ] E/ExoPlayerImplInternal(15232):      at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:529)
[        ] E/ExoPlayerImplInternal(15232):      at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:300)
[        ] E/ExoPlayerImplInternal(15232):      at android.os.Handler.dispatchMessage(Handler.java:102)
[        ] E/ExoPlayerImplInternal(15232):      at android.os.Looper.loop(Looper.java:176)
[        ] E/ExoPlayerImplInternal(15232):      at android.os.HandlerThread.run(HandlerThread.java:65)
[        ] E/ExoPlayerImplInternal(15232): Caused by: com.google.android.exoplayer2.mediacodec.MediaCodecRenderer$DecoderInitializationException: Decoder init failed: OMX.qcom.video.decoder.avc, Format(1, null, null, video/avc,
null, -1, null, [3840, 2160, 30.0], [-1, -1])
[        ] E/ExoPlayerImplInternal(15232):      at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.initCodecWithFallback(MediaCodecRenderer.java:753)
[        ] E/ExoPlayerImplInternal(15232):      at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.maybeInitCodec(MediaCodecRenderer.java:474)
[        ] E/ExoPlayerImplInternal(15232):      ... 9 more
[        ] E/ExoPlayerImplInternal(15232): Caused by: android.media.MediaCodec$CodecException: Error 0xfffffff4
[        ] E/ExoPlayerImplInternal(15232):      at android.media.MediaCodec.native_configure(Native Method)
[        ] E/ExoPlayerImplInternal(15232):      at android.media.MediaCodec.configure(MediaCodec.java:1943)
[        ] E/ExoPlayerImplInternal(15232):      at android.media.MediaCodec.configure(MediaCodec.java:1872)
[        ] E/ExoPlayerImplInternal(15232):      at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.configureCodec(MediaCodecVideoRenderer.java:483)
[        ] E/ExoPlayerImplInternal(15232):      at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.initCodec(MediaCodecRenderer.java:805)
[        ] E/ExoPlayerImplInternal(15232):      at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.initCodecWithFallback(MediaCodecRenderer.java:745)
[        ] E/ExoPlayerImplInternal(15232):      ... 10 more
[   +7 ms] I/flutter (15232): Video player had error com.google.android.exoplayer2.ExoPlaybackException: com.google.android.exoplayer2.mediacodec.MediaCodecRenderer$DecoderInitializationException: Decoder init failed:
OMX.qcom.video.decoder.avc, Format(1, null, null, video/avc, null, -1, null, [3840, 2160, 30.0], [-1, -1])
[+3997 ms] I/zygote64(15232): Do partial code cache collection, code=61KB, data=46KB
[        ] I/zygote64(15232): After code cache collection, code=61KB, data=46KB
[        ] I/zygote64(15232): Increasing code cache capacity to 256KB
[+5074 ms] I/ExoPlayerImpl(15232): Release d3704c9 [ExoPlayerLib/2.9.6] [whyred, Redmi Note 5, Xiaomi, 27] [goog.exo.core]
[  +20 ms] E/BufferQueueProducer(15232): [SurfaceTexture-0-15232-0] cancelBuffer: BufferQueue has been abandoned
[  +16 ms] I/chatty  (15232): uid=10145(com.example.video_test) JNISurfaceTextu identical 5 lines
[        ] E/BufferQueueProducer(15232): [SurfaceTexture-0-15232-0] cancelBuffer: BufferQueue has been abandoned
[        ] D/SurfaceUtils(15232): disconnecting from surface 0x6fc5192010, reason disconnectFromSurface
[   +9 ms] W/MediaAnalyticsItem(15232): Unable to record:
(codec:0:-1:-11:0:5:android.media.mediacodec.codec=OMX.qcom.video.decoder.avc:android.media.mediacodec.mode=video:android.media.mediacodec.secure=0:android.media.mediacodec.mime=video/avc:android.media.mediacodec.bytesin=5046240:)
[forcenew=0]
[  +15 ms] W/MediaAnalyticsItem(15232): Unable to record:
(codec:0:-1:-11:0:5:android.media.mediacodec.codec=OMX.google.aac.decoder:android.media.mediacodec.mode=audio:android.media.mediacodec.secure=0:android.media.mediacodec.mime=audio/mp4a-latm:android.media.mediacodec.bytesin=17166:)
[forcenew=0]
[+23406 ms] I/ExoPlayerImpl(15232): Init 52062b5 [ExoPlayerLib/2.9.6] [whyred, Redmi Note 5, Xiaomi, 27]
[  +61 ms] I/OMXClient(15232): Treble IOmx obtained
[  +70 ms] D/SurfaceUtils(15232): connecting to surface 0x6fcbb1f010, reason connectToSurface
[        ] I/MediaCodec(15232): [OMX.qcom.video.decoder.avc] setting surface generation to 15597572
[        ] D/SurfaceUtils(15232): disconnecting from surface 0x6fcbb1f010, reason connectToSurface(reconnect)
[        ] D/SurfaceUtils(15232): connecting to surface 0x6fcbb1f010, reason connectToSurface(reconnect)
[        ] I/ExtendedACodec(15232): setupVideoDecoder()
[   +9 ms] I/ExtendedACodec(15232): Decoder will be in frame by frame mode
[  +25 ms] D/SurfaceUtils(15232): set up nativeWindow 0x6fcbb1f010 for 3840x2160, color 0x7fa30c06, rotation 90, usage 0x20002900
[   +7 ms] W/GrallocMapperPassthrough(15232): buffer descriptor with invalid usage bits 0x2000
[  +26 ms] I/chatty  (15232): uid=10145(com.example.video_test) CodecLooper identical 1 line
[        ] W/GrallocMapperPassthrough(15232): buffer descriptor with invalid usage bits 0x2000
[        ] I/OMXClient(15232): Treble IOmx obtained
[        ] I/ACodec  (15232): codec does not support config priority (err -2147483648)
[        ] W/GrallocMapperPassthrough(15232): buffer descriptor with invalid usage bits 0x2000
[        ] I/ACodec  (15232): codec does not support config priority (err -2147483648)
[        ] I/ACodec  (15232): codec does not support config operating rate (err -2147483648)
[        ] W/ExtendedACodec(15232): Failed to get extension for extradata parameter
[  +29 ms] D/SurfaceUtils(15232): set up nativeWindow 0x6fcbb1f010 for 3840x2160, color 0x7fa30c06, rotation 90, usage 0x20002900
[   +6 ms] D/AudioTrack(15232): Client defaulted notificationFrames to 7688 for frameCount 15376
[  +37 ms] W/GrallocMapperPassthrough(15232): buffer descriptor with invalid usage bits 0x2000
[  +13 ms] W/GrallocMapperPassthrough(15232): buffer descriptor with invalid usage bits 0x2000
[  +43 ms] I/chatty  (15232): uid=10145(com.example.video_test) JNISurfaceTextu identical 1 line
[        ] W/GrallocMapperPassthrough(15232): buffer descriptor with invalid usage bits 0x2000
[ +643 ms] I/ExoPlayerImpl(15232): Release d6b8442 [ExoPlayerLib/2.9.6] [whyred, Redmi Note 5, Xiaomi, 27] [goog.exo.core]
[ +601 ms] I/ExoPlayerImpl(15232): Init 4b95f95 [ExoPlayerLib/2.9.6] [whyred, Redmi Note 5, Xiaomi, 27]
[  +31 ms] I/OMXClient(15232): Treble IOmx obtained
[  +22 ms] D/SurfaceUtils(15232): connecting to surface 0x6fc7033010, reason connectToSurface
[        ] I/MediaCodec(15232): [OMX.qcom.video.decoder.avc] setting surface generation to 15597573
[        ] D/SurfaceUtils(15232): disconnecting from surface 0x6fc7033010, reason connectToSurface(reconnect)
[        ] D/SurfaceUtils(15232): connecting to surface 0x6fc7033010, reason connectToSurface(reconnect)
[   +2 ms] I/ExtendedACodec(15232): setupVideoDecoder()
[   +4 ms] E/ACodec  (15232): [OMX.qcom.video.decoder.avc] configureCodec returning error -12
[        ] E/ACodec  (15232): signalError(omxError 0x80001001, internalError -12)
[   +4 ms] E/MediaCodec(15232): Codec reported err 0xfffffff4, actionCode 0, while in state 3
[        ] W/MediaAnalyticsItem(15232): Unable to record:
(codec:0:-1:-11:0:10:android.media.mediacodec.codec=OMX.qcom.video.decoder.avc:android.media.mediacodec.mode=video:android.media.mediacodec.secure=0:android.media.mediacodec.width=3840:android.media.mediacodec.height=2160:android.me
dia.mediacodec.rotation-degrees=90:android.media.mediacodec.maxwidth=3840:android.media.mediacodec.maxheight=2160:android.media.mediacodec.errcode=-12:android.media.mediacodec.errstate=3:) [forcenew=0]
[  +33 ms] D/SurfaceUtils(15232): disconnecting from surface 0x6fc7033010, reason disconnectFromSurface
[        ] E/MediaCodec(15232): configure failed with err 0xfffffff4, resetting...
[        ] I/OMXClient(15232): Treble IOmx obtained
[   +1 ms] W/MediaAnalyticsItem(15232): Unable to record: (codec:0:-1:-11:0:3:android.media.mediacodec.codec=OMX.qcom.video.decoder.avc:android.media.mediacodec.mode=video:android.media.mediacodec.secure=0:) [forcenew=0]
[   +5 ms] W/MediaCodecRenderer(15232): Failed to initialize decoder: OMX.qcom.video.decoder.avc
[        ] W/MediaCodecRenderer(15232): android.media.MediaCodec$CodecException: Error 0xfffffff4
[        ] W/MediaCodecRenderer(15232):         at android.media.MediaCodec.native_configure(Native Method)
[        ] W/MediaCodecRenderer(15232):         at android.media.MediaCodec.configure(MediaCodec.java:1943)
[        ] W/MediaCodecRenderer(15232):         at android.media.MediaCodec.configure(MediaCodec.java:1872)
[        ] W/MediaCodecRenderer(15232):         at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.configureCodec(MediaCodecVideoRenderer.java:483)
[        ] W/MediaCodecRenderer(15232):         at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.initCodec(MediaCodecRenderer.java:805)
[        ] W/MediaCodecRenderer(15232):         at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.initCodecWithFallback(MediaCodecRenderer.java:745)
[        ] W/MediaCodecRenderer(15232):         at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.maybeInitCodec(MediaCodecRenderer.java:474)
[        ] W/MediaCodecRenderer(15232):         at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.reinitializeCodec(MediaCodecRenderer.java:1261)
[        ] W/MediaCodecRenderer(15232):         at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.onInputFormatChanged(MediaCodecRenderer.java:1111)
[        ] W/MediaCodecRenderer(15232):         at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.onInputFormatChanged(MediaCodecVideoRenderer.java:552)
[        ] W/MediaCodecRenderer(15232):         at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:647)
[        ] W/MediaCodecRenderer(15232):         at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:529)
[        ] W/MediaCodecRenderer(15232):         at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:300)
[        ] W/MediaCodecRenderer(15232):         at android.os.Handler.dispatchMessage(Handler.java:102)
[        ] W/MediaCodecRenderer(15232):         at android.os.Looper.loop(Looper.java:176)
[        ] W/MediaCodecRenderer(15232):         at android.os.HandlerThread.run(HandlerThread.java:65)
[        ] E/ExoPlayerImplInternal(15232): Playback error.
[        ] E/ExoPlayerImplInternal(15232): com.google.android.exoplayer2.ExoPlaybackException: com.google.android.exoplayer2.mediacodec.MediaCodecRenderer$DecoderInitializationException: Decoder init failed:
OMX.qcom.video.decoder.avc, Format(1, null, null, video/avc, null, -1, null, [3840, 2160, 30.0], [-1, -1])
[        ] E/ExoPlayerImplInternal(15232):      at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.maybeInitCodec(MediaCodecRenderer.java:479)
[        ] E/ExoPlayerImplInternal(15232):      at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.reinitializeCodec(MediaCodecRenderer.java:1261)
[        ] E/ExoPlayerImplInternal(15232):      at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.onInputFormatChanged(MediaCodecRenderer.java:1111)
[        ] E/ExoPlayerImplInternal(15232):      at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.onInputFormatChanged(MediaCodecVideoRenderer.java:552)
[        ] E/ExoPlayerImplInternal(15232):      at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:647)
[        ] E/ExoPlayerImplInternal(15232):      at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:529)
[        ] E/ExoPlayerImplInternal(15232):      at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:300)
[        ] E/ExoPlayerImplInternal(15232):      at android.os.Handler.dispatchMessage(Handler.java:102)
[        ] E/ExoPlayerImplInternal(15232):      at android.os.Looper.loop(Looper.java:176)
[        ] E/ExoPlayerImplInternal(15232):      at android.os.HandlerThread.run(HandlerThread.java:65)
[        ] E/ExoPlayerImplInternal(15232): Caused by: com.google.android.exoplayer2.mediacodec.MediaCodecRenderer$DecoderInitializationException: Decoder init failed: OMX.qcom.video.decoder.avc, Format(1, null, null, video/avc,
null, -1, null, [3840, 2160, 30.0], [-1, -1])
[        ] E/ExoPlayerImplInternal(15232):      at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.initCodecWithFallback(MediaCodecRenderer.java:753)
[        ] E/ExoPlayerImplInternal(15232):      at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.maybeInitCodec(MediaCodecRenderer.java:474)
[        ] E/ExoPlayerImplInternal(15232):      ... 9 more
[        ] E/ExoPlayerImplInternal(15232): Caused by: android.media.MediaCodec$CodecException: Error 0xfffffff4
[        ] E/ExoPlayerImplInternal(15232):      at android.media.MediaCodec.native_configure(Native Method)
[        ] E/ExoPlayerImplInternal(15232):      at android.media.MediaCodec.configure(MediaCodec.java:1943)
[        ] E/ExoPlayerImplInternal(15232):      at android.media.MediaCodec.configure(MediaCodec.java:1872)
[        ] E/ExoPlayerImplInternal(15232):      at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.configureCodec(MediaCodecVideoRenderer.java:483)
[        ] E/ExoPlayerImplInternal(15232):      at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.initCodec(MediaCodecRenderer.java:805)
[        ] E/ExoPlayerImplInternal(15232):      at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.initCodecWithFallback(MediaCodecRenderer.java:745)
[        ] E/ExoPlayerImplInternal(15232):      ... 10 more
[   +5 ms] I/flutter (15232): Video player had error com.google.android.exoplayer2.ExoPlaybackException: com.google.android.exoplayer2.mediacodec.MediaCodecRenderer$DecoderInitializationException: Decoder init failed:
OMX.qcom.video.decoder.avc, Format(1, null, null, video/avc, null, -1, null, [3840, 2160, 30.0], [-1, -1])
[ +898 ms] I/ExoPlayerImpl(15232): Release 52062b5 [ExoPlayerLib/2.9.6] [whyred, Redmi Note 5, Xiaomi, 27] [goog.exo.core]
[   +9 ms] E/BufferQueueProducer(15232): [SurfaceTexture-0-15232-2] cancelBuffer: BufferQueue has been abandoned
[  +12 ms] I/chatty  (15232): uid=10145(com.example.video_test) JNISurfaceTextu identical 5 lines
[   +3 ms] E/BufferQueueProducer(15232): [SurfaceTexture-0-15232-2] cancelBuffer: BufferQueue has been abandoned
[        ] D/SurfaceUtils(15232): disconnecting from surface 0x6fcbb1f010, reason disconnectFromSurface
[   +8 ms] W/MediaAnalyticsItem(15232): Unable to record:
(codec:0:-1:-11:0:10:android.media.mediacodec.codec=OMX.qcom.video.decoder.avc:android.media.mediacodec.mode=video:android.media.mediacodec.secure=0:android.media.mediacodec.width=3840:android.media.mediacodec.height=2160:android.me
dia.mediacodec.rotation-degrees=90:android.media.mediacodec.maxwidth=3840:android.media.mediacodec.maxheight=2160:android.media.mediacodec.mime=video/avc:android.media.mediacodec.bytesin=5046240:) [forcenew=0]
[  +11 ms] W/MediaAnalyticsItem(15232): Unable to record:
(codec:0:-1:-11:0:5:android.media.mediacodec.codec=OMX.google.aac.decoder:android.media.mediacodec.mode=audio:android.media.mediacodec.secure=0:android.media.mediacodec.mime=audio/mp4a-latm:android.media.mediacodec.bytesin=17166:)
[forcenew=0]
[ +373 ms] I/ExoPlayerImpl(15232): Init 4d24c75 [ExoPlayerLib/2.9.6] [whyred, Redmi Note 5, Xiaomi, 27]
[  +35 ms] I/OMXClient(15232): Treble IOmx obtained
[  +29 ms] D/SurfaceUtils(15232): connecting to surface 0x6fcbba4010, reason connectToSurface
[        ] I/MediaCodec(15232): [OMX.qcom.video.decoder.avc] setting surface generation to 15597574
[        ] D/SurfaceUtils(15232): disconnecting from surface 0x6fcbba4010, reason connectToSurface(reconnect)
[        ] D/SurfaceUtils(15232): connecting to surface 0x6fcbba4010, reason connectToSurface(reconnect)
[   +1 ms] I/ExtendedACodec(15232): setupVideoDecoder()
[  +11 ms] I/ExtendedACodec(15232): Decoder will be in frame by frame mode
[  +22 ms] D/SurfaceUtils(15232): set up nativeWindow 0x6fcbba4010 for 3840x2160, color 0x7fa30c06, rotation 90, usage 0x20002900
[   +6 ms] W/GrallocMapperPassthrough(15232): buffer descriptor with invalid usage bits 0x2000
[  +28 ms] I/chatty  (15232): uid=10145(com.example.video_test) CodecLooper identical 1 line
[   +3 ms] W/GrallocMapperPassthrough(15232): buffer descriptor with invalid usage bits 0x2000
[        ] I/OMXClient(15232): Treble IOmx obtained
[        ] W/GrallocMapperPassthrough(15232): buffer descriptor with invalid usage bits 0x2000
[   +1 ms] I/ACodec  (15232): codec does not support config priority (err -2147483648)
[   +3 ms] I/ACodec  (15232): codec does not support config priority (err -2147483648)
[   +2 ms] I/ACodec  (15232): codec does not support config operating rate (err -2147483648)
[        ] W/ExtendedACodec(15232): Failed to get extension for extradata parameter
[  +17 ms] D/SurfaceUtils(15232): set up nativeWindow 0x6fcbba4010 for 3840x2160, color 0x7fa30c06, rotation 90, usage 0x20002900
[  +34 ms] D/AudioTrack(15232): Client defaulted notificationFrames to 7688 for frameCount 15376
[  +21 ms] W/GrallocMapperPassthrough(15232): buffer descriptor with invalid usage bits 0x2000
[  +19 ms] W/GrallocMapperPassthrough(15232): buffer descriptor with invalid usage bits 0x2000
[ +107 ms] I/chatty  (15232): uid=10145(com.example.video_test) JNISurfaceTextu identical 1 line
[        ] W/GrallocMapperPassthrough(15232): buffer descriptor with invalid usage bits 0x2000
[ +696 ms] I/ExoPlayerImpl(15232): Release 4b95f95 [ExoPlayerLib/2.9.6] [whyred, Redmi Note 5, Xiaomi, 27] [goog.exo.core]


```

```
$ flutter analyze
Analyzing video_test...                                                 
No issues found! (ran in 2.1s)

```

```
$ flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel beta, v1.6.3, on Mac OS X 10.14.5 18F132, locale en-UA)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[✓] iOS toolchain - develop for iOS devices (Xcode 10.2.1)
[✓] Android Studio (version 3.4)
[✓] IntelliJ IDEA Ultimate Edition (version 2019.1.1)
[✓] VS Code (version 1.33.1)
[✓] Connected device (2 available)

• No issues found!

```

**Comment by TahaTesser** [comment]
Hi @Vitaly-V 
if you're still experiencing this problem with latest stable, please create a new issue and provide the information required in the template.
Thank you
