### ISSUE TITLE
flutter attach and mDNS

### ISSUE THREAD

**Issue by collaorodrigo7** [flutter/flutter#33906]
I know that being able to develop/debug on an iPhone using windows is not in the official docs, but [this post](https://medium.com/flutter-community/developing-and-debugging-flutter-apps-for-ios-without-a-mac-8d362a8ec667) explains pretty well what would be needed to be able to do it.
I was able to follow it and develop/hot reload in iOS from windows. Pretty amazing experience.
However, while doing it I think I may have discovered a couple of problems on `multicast_dns.dart`.
_Important Note: I have multiple network adapters on my laptop._

## Steps to Reproduce

1. Run flutter run on macOS, and successfully run the application.
2. Install all the requirements to make iOS be recognized by flutter in windows. ([More info](https://medium.com/flutter-community/developing-and-debugging-flutter-apps-for-ios-without-a-mac-8d362a8ec667))
3. User the patches from [this post](https://medium.com/flutter-community/developing-and-debugging-flutter-apps-for-ios-without-a-mac-8d362a8ec667)
4. Run flutter attach

The first problem I encounter is that flutter attach will crash saying:
      
        Oops; flutter has exited unexpectedly. 

## Logs, 
Please see "Logs 1" at the end

## What I think that happened
I believe this is caused because on 
`\Pub\Cache\hosted\pub.dartlang.org\multicast_dns-0.1.1\lib\src\constants.dart`
mDnsPort is set to 5353. However, for some reason I do not understand, mDNS is not running on port 5353 on this laptop. (I tried all this in a clean windows VM and this was not a problem port 5353 was correct).

After figuring out what port was used for mDNSResponder.exe, I was able to modify the constant value of the port, and move forward.
My question here is, should `flutter attach` have an optional parameter for the port of mDNSPort instead of just being a constant? Perhaps `--mdns-port` ?

## Second Problem
After the previous problem was fixed, I was able to get a step further, but then later run into another problem.
Again, 

        Oops; flutter has exited unexpectedly. 

## Logs, Please see "Logs 2" at the end

My laptop has multiple network adapters, and I believe the problem is inside the for loop
```for (NetworkInterface interface in interfaces) {```
when it is trying to assign the value of socket. I noticed I have many interfaces on the interface array, and probably for some of those mDns is not available and therefore crashing there while trying to connect.
I was able to fix this by just try/catching what's inside that for loop. (This will be a problem if ALL the attempts to create a connection fail, in which case I think an error should be thrown)

After fixing this last problem, I was able to successfully attach to the iOS application on my phone, and hot reload and debug.

Before I realized how to fix these 2 problems, I noticed that disabling ALL my network interfaces will solve the problem too, I was able to attach and debug, and that's how I ended up realizing about the port for mDNSResponse and the problem with all the other network interfaces.

I do not know if this will matter to you now, as developing on iOS devices from windows is not officially supported, but at least for me and my team, this is such a game changer, and this was the last thing my team needed before we can transition our app from React Native to Flutter.

## command

  flutter attach

  ## exception

  SocketException: SocketException: Failed to create datagram socket (OS Error: Only one usage of each socket address (protocol/network address/port) is normally permitted.
  , errno = 10048), address = 0.0.0.0, port = 5353

  ```
  #0      _NativeSocket.bindDatagram (dart:io-patch/socket_patch.dart:615:7)
  <asynchronous suspension>
  #1      _RawDatagramSocket.bind (dart:io-patch/socket_patch.dart:1881:26)
  #2      RawDatagramSocket.bind (dart:io-patch/socket_patch.dart:1839:31)
  #3      MDnsClient.start (package:multicast_dns/multicast_dns.dart:78:41)
  <asynchronous suspension>
  #4      MDnsObservatoryDiscovery.query (package:flutter_tools/src/commands/attach.dart:421:20)
  <asynchronous suspension>
  #5      AttachCommand._attachToDevice (package:flutter_tools/src/commands/attach.dart:231:88)
  <asynchronous suspension>
  #6      AttachCommand.runCommand.<anonymous closure> (package:flutter_tools/src/commands/attach.dart:175:19)
  #7      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:29)
  <asynchronous suspension>
  #8      _rootRun (dart:async/zone.dart:1124:13)
  #9      _CustomZone.run (dart:async/zone.dart:1021:19)
  #10     _runZoned (dart:async/zone.dart:1516:10)
  #11     runZoned (dart:async/zone.dart:1463:12)
  #12     AppContext.run (package:flutter_tools/src/base/context.dart:152:18)
  <asynchronous suspension>
  #13     AttachCommand.runCommand (package:flutter_tools/src/commands/attach.dart:174:19)
  <asynchronous suspension>
  #14     FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:488:18)
  #15     _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:77:64)
  #16     _rootRunUnary (dart:async/zone.dart:1132:38)
  #17     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
  #18     _FutureListener.handleValue (dart:async/future_impl.dart:126:18)
  #19     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:639:45)
  #20     Future._propagateToListeners (dart:async/future_impl.dart:668:32)
  #21     Future._complete (dart:async/future_impl.dart:473:7)
  #22     _SyncCompleter.complete (dart:async/future_impl.dart:51:12)
  #23     _AsyncAwaitCompleter.complete.<anonymous closure> (dart:async-patch/async_patch.dart:33:20)
  #24     _rootRun (dart:async/zone.dart:1124:13)
  #25     _CustomZone.run (dart:async/zone.dart:1021:19)
  #26     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:947:23)
  #27     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
  #28     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
  #29     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:115:13)
  #30     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:5)
  ```

  ## flutter doctor

  ```
  [32m[✓][39m Flutter (Channel beta, v1.6.3, on Microsoft Windows [Version 10.0.17134.765], locale en-US)
      [32m•[39m Flutter version 1.6.3 at D:\Flutter\flutter
      [32m•[39m Framework revision bc7bc94083 (13 days ago), 2019-05-23 10:29:07 -0700
      [32m•[39m Engine revision 8dc3a4cde2
      [32m•[39m Dart version 2.3.2 (build 2.3.2-dev.0.0 e3edfd36b2)

  [32m[✓][39m Android toolchain - develop for Android devices (Android SDK version 28.0.3)
      [32m•[39m Android SDK at C:\Users\Rodrigo\AppData\Local\Android\sdk
      [32m•[39m Android NDK location not configured (optional; useful for native profiling support)
      [32m•[39m Platform android-28, build-tools 28.0.3
      [32m•[39m Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
      [32m•[39m Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b02)
      [32m•[39m All Android licenses accepted.

  [32m[✓][39m Android Studio (version 3.1)
      [32m•[39m Android Studio at C:\Program Files\Android\Android Studio
      [32m•[39m Flutter plugin version 29.0.1
      [32m•[39m Dart plugin version 173.4700
      [32m•[39m Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b02)

  [32m[✓][39m VS Code (version 1.34.0)
      [32m•[39m VS Code at C:\Users\Rodrigo\AppData\Local\Programs\Microsoft VS Code
      [32m•[39m Flutter extension version 3.1.0

  [32m[✓][39m Connected device (1 available)
      [32m•[39m Rodrigoâ€™s iPhone • f276cb97b3639dff6ed5a58122ab6e8e6605abe9 • ios • iOS 12.2

  [32m•[39m No issues found!
  ```

# Log 2

## command

flutter attach

## exception

SocketException: SocketException: Failed to create datagram socket (OS Error: The requested address is not valid in its context.
, errno = 10049), address = , port = 55340

```
#0      _NativeSocket.bindDatagram (dart:io-patch/socket_patch.dart:615:7)
<asynchronous suspension>
#1      _RawDatagramSocket.bind (dart:io-patch/socket_patch.dart:1881:26)
#2      RawDatagramSocket.bind (dart:io-patch/socket_patch.dart:1839:31)
#3      MDnsClient.start (package:multicast_dns/multicast_dns.dart:111:76)
<asynchronous suspension>
#4      MDnsObservatoryDiscovery.query (package:flutter_tools/src/commands/attach.dart:421:20)
<asynchronous suspension>
#5      AttachCommand._attachToDevice (package:flutter_tools/src/commands/attach.dart:231:88)
<asynchronous suspension>
#6      AttachCommand.runCommand.<anonymous closure> (package:flutter_tools/src/commands/attach.dart:175:19)
#7      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:29)
<asynchronous suspension>
#8      _rootRun (dart:async/zone.dart:1124:13)
#9      _CustomZone.run (dart:async/zone.dart:1021:19)
#10     _runZoned (dart:async/zone.dart:1516:10)
#11     runZoned (dart:async/zone.dart:1463:12)
#12     AppContext.run (package:flutter_tools/src/base/context.dart:152:18)
<asynchronous suspension>
#13     AttachCommand.runCommand (package:flutter_tools/src/commands/attach.dart:174:19)
<asynchronous suspension>
#14     FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:488:18)
#15     _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:77:64)
#16     _rootRunUnary (dart:async/zone.dart:1132:38)
#17     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#18     _FutureListener.handleValue (dart:async/future_impl.dart:126:18)
#19     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:639:45)
#20     Future._propagateToListeners (dart:async/future_impl.dart:668:32)
#21     Future._complete (dart:async/future_impl.dart:473:7)
#22     _SyncCompleter.complete (dart:async/future_impl.dart:51:12)
#23     _AsyncAwaitCompleter.complete.<anonymous closure> (dart:async-patch/async_patch.dart:33:20)
#24     _rootRun (dart:async/zone.dart:1124:13)
#25     _CustomZone.run (dart:async/zone.dart:1021:19)
#26     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:947:23)
#27     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#28     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#29     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:115:13)
#30     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:5)
```

## flutter doctor

```
[32m[✓][39m Flutter (Channel beta, v1.6.3, on Microsoft Windows [Version 10.0.17134.765], locale en-US)
    [32m•[39m Flutter version 1.6.3 at D:\Flutter\flutter
    [32m•[39m Framework revision bc7bc94083 (13 days ago), 2019-05-23 10:29:07 -0700
    [32m•[39m Engine revision 8dc3a4cde2
    [32m•[39m Dart version 2.3.2 (build 2.3.2-dev.0.0 e3edfd36b2)

[32m[✓][39m Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    [32m•[39m Android SDK at C:\Users\Rodrigo\AppData\Local\Android\sdk
    [32m•[39m Android NDK location not configured (optional; useful for native profiling support)
    [32m•[39m Platform android-28, build-tools 28.0.3
    [32m•[39m Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    [32m•[39m Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b02)
    [32m•[39m All Android licenses accepted.

[32m[✓][39m Android Studio (version 3.1)
    [32m•[39m Android Studio at C:\Program Files\Android\Android Studio
    [32m•[39m Flutter plugin version 29.0.1
    [32m•[39m Dart plugin version 173.4700
    [32m•[39m Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b02)

[32m[✓][39m VS Code (version 1.34.0)
    [32m•[39m VS Code at C:\Users\Rodrigo\AppData\Local\Programs\Microsoft VS Code
    [32m•[39m Flutter extension version 3.1.0

[32m[✓][39m Connected device (1 available)
    [32m•[39m Rodrigoâ€™s iPhone • f276cb97b3639dff6ed5a58122ab6e8e6605abe9 • ios • iOS 12.2

[32m•[39m No issues found!
```

**Comment by janmoppel** [comment]
Hello @collaorodrigo7 !

Does the problem still persist in the latest stable version?

**Comment by iapicca** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
  
Thanks for your contribution.
