### ISSUE TITLE
Flutter Doctor crashes everytime 

### ISSUE THREAD

**Issue by urvishjarvis1** [flutter/flutter#33966]
## Steps to Reproduce

1. Flutter doctor

## Logs

```
```
Flutter crash report; please file at https://github.com/flutter/flutter/issues.

## command

flutter doctor

## exception

ProcessException: ProcessException: Permission denied
  Command: /home/urvish/android-studio/jre/bin/java -version

```
#0      _ProcessImpl._runAndWait (dart:io-patch/process_patch.dart:489:7)
#1      _runNonInteractiveProcessSync (dart:io-patch/process_patch.dart:634:18)
#2      Process.runSync (dart:io-patch/process_patch.dart:66:12)
#3      LocalProcessManager.runSync (package:process/src/interface/local_process_manager.dart:83:20)
#4      AndroidStudio._init (package:flutter_tools/src/android/android_studio.dart:298:51)
#5      new AndroidStudio (package:flutter_tools/src/android/android_studio.dart:40:5)
#6      AndroidStudio._allLinuxOrWindows._checkWellKnownPath (package:flutter_tools/src/android/android_studio.dart:260:23)
#7      AndroidStudio._allLinuxOrWindows (package:flutter_tools/src/android/android_studio.dart:266:26)
#8      AndroidStudio.allInstalled (package:flutter_tools/src/android/android_studio.dart:175:40)
#9      AndroidStudioValidator.allValidators (package:flutter_tools/src/android/android_studio_validator.dart:21:55)
#10     _DefaultDoctorValidatorsProvider.validators (package:flutter_tools/src/doctor.dart:65:51)
#11     Doctor.validators (package:flutter_tools/src/doctor.dart:121:46)
#12     Doctor.startValidatorTasks (package:flutter_tools/src/doctor.dart:128:39)
#13     Doctor.diagnose (package:flutter_tools/src/doctor.dart:200:41)
<asynchronous suspension>
#14     DoctorCommand.runCommand (package:flutter_tools/src/commands/doctor.dart:48:39)
<asynchronous suspension>
#15     FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:559:18)
#16     _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:77:64)
#17     _rootRunUnary (dart:async/zone.dart:1132:38)
#18     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#19     _FutureListener.handleValue (dart:async/future_impl.dart:126:18)
#20     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:639:45)
#21     Future._propagateToListeners (dart:async/future_impl.dart:668:32)
#22     Future._complete (dart:async/future_impl.dart:473:7)
#23     _SyncCompleter.complete (dart:async/future_impl.dart:51:12)
#24     _AsyncAwaitCompleter.complete.<anonymous closure> (dart:async-patch/async_patch.dart:33:20)
#25     _rootRun (dart:async/zone.dart:1124:13)
#26     _CustomZone.run (dart:async/zone.dart:1021:19)
#27     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:947:23)
#28     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#29     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#30     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:115:13)
#31     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:5)
```

## flutter doctor

```
[!] Flutter (Channel stable, v1.5.4-hotfix.2, on Linux, locale en_IN)
    • Flutter version 1.5.4-hotfix.2 at /home/urvish/flutter
    • Framework revision 7a4c33425d (5 weeks ago), 2019-04-29 11:05:24 -0700
    • Engine revision 52c7a1e849
    • Dart version 2.3.0 (build 2.3.0-dev.0.5 a1668566e5)
    ✗ Downloaded executables cannot execute on host.
      See https://github.com/flutter/flutter/issues/6207 for more information
      On Debian/Ubuntu/Mint: sudo apt-get install lib32stdc++6
      On Fedora: dnf install libstdc++.i686
      On Arch: pacman -S lib32-gcc-libs


[!] Android toolchain - develop for Android devices
    • Android SDK at /usr/lib/android-sdk/
    • Android NDK location not configured (optional; useful for native profiling
      support)
    ✗ Unable to locate Android SDK.
      Install Android Studio from:
      https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK
      components.
      (or visit https://flutter.dev/setup/#android-setup for detailed
      instructions).
      If the Android SDK has been installed to a custom location, set
      ANDROID_HOME to that location.
      You may also want to add it to your PATH environment variable.

    • ANDROID_HOME = /usr/lib/android-sdk/
    ✗ No valid Android SDK platforms found in /usr/lib/android-sdk/platforms.
      Directory was empty.
    • Try re-installing or updating your Android SDK,
      visit https://flutter.dev/setup/#android-setup for detailed instructions.

! Doctor found issues in 2 categories.
```

```
```

**Comment by PsychoXIVI** [comment]
Can you use `/home/urvish/android-studio/jre/bin/java -version` from your teminal by yourself (without root/admin)?

Maybe you unpacked the precompiled java binaries without making them executable?

**Comment by urvishjarvis1** [comment]
Yes, I am able to use it without root permission.

**Comment by urvishjarvis1** [comment]
able to solve by allowing java to be executable
