### ISSUE TITLE
Flutter Doctor & Flutter create doesn't work if there is "space" in path

### ISSUE THREAD

**Issue by Saifallak** [flutter/flutter#33972]
## Steps to Reproduce

1. download flutter and upgrade it latest stable ver.
2. do flutter doctor ( my user name on windows have spaces )
3. crash

## Logs

```
C:\Users\Mohamed Adel>flutter doctor -v
[√] Flutter (Channel beta, v1.6.3, on Microsoft Windows [Version 10.0.17763.503], locale en-US)
    • Flutter version 1.6.3 at C:\SDKs\flutter
    • Framework revision bc7bc94083 (2 weeks ago), 2019-05-23 10:29:07 -0700
    • Engine revision 8dc3a4cde2
    • Dart version 2.3.2 (build 2.3.2-dev.0.0 e3edfd36b2)

\CreateProcessW failed 193
Unhandled exception:
ProcessException: %1 is not a valid Win32 application.

  Command: C:\Users\Mohamed Adel\AppData\Local\Android\sdk\platform-tools\adb.exe devices -l
#0      _ProcessImpl._runAndWait (dart:io-patch/process_patch.dart:489:7)
#1      _runNonInteractiveProcessSync (dart:io-patch/process_patch.dart:634:18)
#2      Process.runSync (dart:io-patch/process_patch.dart:66:12)
#3      LocalProcessManager.runSync (package:process/src/interface/local_process_manager.dart:83:20)
#4      _runWithLoggingSync (package:flutter_tools/src/base/process.dart:333:48)
#5      runSync (package:flutter_tools/src/base/process.dart:306:10)
#6      getAdbDevices (package:flutter_tools/src/android/android_device.dart:560:12)
#7      AndroidDevices.pollingGetDevices (package:flutter_tools/src/android/android_device.dart:55:53)
<asynchronous suspension>
#8      PollingDeviceDiscovery.devices (package:flutter_tools/src/device.dart:188:52)
<asynchronous suspension>
#9      DeviceManager.getAllConnectedDevices (package:flutter_tools/src/device.dart:116:46)
<asynchronous suspension>
#10     DeviceValidator.validate (package:flutter_tools/src/doctor.dart:705:54)
<asynchronous suspension>
#11     Doctor.startValidatorTasks (package:flutter_tools/src/doctor.dart:129:52)
#12     Doctor.diagnose (package:flutter_tools/src/doctor.dart:200:41)
#13     _AsyncAwaitCompleter.start (dart:async-patch/async_patch.dart:49:6)
#14     Doctor.diagnose (package:flutter_tools/src/doctor.dart:190:24)
#15     DoctorCommand.runCommand (package:flutter_tools/src/commands/doctor.dart:48:39)
#16     _AsyncAwaitCompleter.start (dart:async-patch/async_patch.dart:49:6)
#17     DoctorCommand.runCommand (package:flutter_tools/src/commands/doctor.dart:34:42)
#18     FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:488:18)
#19     _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:77:64)
#20     _rootRunUnary (dart:async/zone.dart:1132:38)
#21     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#22     _FutureListener.handleValue (dart:async/future_impl.dart:126:18)
#23     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:639:45)
#24     Future._propagateToListeners (dart:async/future_impl.dart:668:32)
#25     Future._complete (dart:async/future_impl.dart:473:7)
#26     _SyncCompleter.complete (dart:async/future_impl.dart:51:12)
#27     _AsyncAwaitCompleter.complete.<anonymous closure> (dart:async-patch/async_patch.dart:33:20)
#28     _rootRun (dart:async/zone.dart:1124:13)
#29     _CustomZone.run (dart:async/zone.dart:1021:19)
#30     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:947:23)
#31     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#32     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#33     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:115:13)
#34     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:5)
```

it's the same issue with flutter create , and i think the same with other cmds that use paths i dunno only i could try is flutter create and doctor

@mohamedadel217 follow this

**Comment by blasten** [comment]
This is fixed on master.
