### ISSUE TITLE
google_sign_in throws an Unknown PlatformException after token expires

### ISSUE THREAD

**Issue by emilioschepis** [flutter/flutter#33981]
## Steps to Reproduce

1. Create a simple Flutter project with `google_sign_in` but without `firebase_auth` (or any Firebase dependency).
2. Authenticate with a Google account.
3. Try accessing the `authentication` via `await <GoogleSignInAccount>.authentication` and read the token.
4. Keep the application open for over an hour (until the token expires).
5. Try to again `await <GoogleSignInAccount>.authentication`: this throws a `PlatformException(exception, Unknown, null)`.

## Small code snippet
_Note: `auth_service` is just a wrapper that exposes a `GoogleSignIn` instance._
```
Future<void> tryPlatform() async {
  var account = auth_service.google.currentUser;

  if (account == null) throw Exception('No account.');

  final authentication = await account.authentication;

  if (authentication == null) throw Exception('No authentication.');

  final response = await http.get(
      'https://www.googleapis.com/oauth2/v3/tokeninfo?id_token=${authentication.idToken}');

  if (response.statusCode != 200) throw Exception('Failed check.');

  final data = convert.jsonDecode(response.body) as Map<String, dynamic>;

  if (data == null || !data.containsKey('exp'))
    throw Exception('Failed decoding.');

  print(DateTime.fromMillisecondsSinceEpoch(int.parse(data['exp']) * 1000));
}
```

## Screenshot
_Note: I tried to call the function three times before the token expired and once after it did. This is the result._
<img width="732" alt="image" src="https://user-images.githubusercontent.com/16031715/59045058-9f849080-887f-11e9-8fc7-413043ff021b.png">

## Flutter Doctor
```
[✓] Flutter (Channel stable, v1.5.4-hotfix.2, on Mac OS X 10.14.5 18F132, locale en-US)
    • Flutter version 1.5.4-hotfix.2 at /Users/emilio/Library/Flutter
    • Framework revision 7a4c33425d (5 weeks ago), 2019-04-29 11:05:24 -0700
    • Engine revision 52c7a1e849
    • Dart version 2.3.0 (build 2.3.0-dev.0.5 a1668566e5)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/emilio/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.2.1, Build version 10E1001
    • ios-deploy 1.9.4
    • CocoaPods version 1.6.1

[✓] Android Studio (version 3.4)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 36.0.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

[!] VS Code (version 1.34.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    ✗ Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (2 available)
    • Android SDK built for x86 • emulator-5554                        • android-x86 • Android 9 (API 28) (emulator)
```

**Comment by vintage** [comment]
That's not the issue with Flutter itself, but with the plugin you are playing with. You should have more luck reporting an issue there.

**Comment by emilioschepis** [comment]
Unfortunately you can't report an issue in the plugins repository. 
The [`README.md`](https://github.com/flutter/plugins/blob/master/packages/google_sign_in/README.md) explicitly says that issues must be reported here.

**Comment by wreppun** [comment]
I have a fuller stack trace here (not that it's much help):

```
GoogleSignIn: PlatformException(exception, Unknown, null), 
#0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:564:7)                                                                                                                                                    
#1      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:302:33)                                                                 
<asynchronous suspension>                                                                                                                                      
#2      GoogleSignInAccount.authentication (package:google_sign_in/google_sign_in.dart:85:36)                                                                  
<asynchronous suspension>                                                                                                                                      
#3      GoogleSignInAccount.authHeaders (package:google_sign_in/google_sign_in.dart:101:33)
```

Looks like it's throwing from the `getTokens` call in Java.

**Comment by wreppun** [comment]
I added some logging in the plugin and got

```
W/System.err(17884): java.util.concurrent.ExecutionException: com.google.android.gms.auth.GoogleAuthException: Unknown
W/System.err(17884):    at com.google.common.util.concurrent.AbstractFuture.getDoneValue(AbstractFuture.java:500)
W/System.err(17884):    at com.google.common.util.concurrent.AbstractFuture.get(AbstractFuture.java:459)
W/System.err(17884):    at com.google.common.util.concurrent.AbstractFuture$TrustedFuture.get(AbstractFuture.java:76)
W/System.err(17884):    at io.flutter.plugins.googlesignin.GoogleSignInPlugin$Delegate$7.run(GoogleSignInPlugin.java:468)
W/System.err(17884):    at io.flutter.plugins.googlesignin.BackgroundTaskRunner$1.run(BackgroundTaskRunner.java:62)
W/System.err(17884):    at android.os.Handler.handleCallback(Handler.java:790)
W/System.err(17884):    at android.os.Handler.dispatchMessage(Handler.java:99)
W/System.err(17884):    at android.os.Looper.loop(Looper.java:164)
W/System.err(17884):    at android.app.ActivityThread.main(ActivityThread.java:6494)
W/System.err(17884):    at java.lang.reflect.Method.invoke(Native Method)
W/System.err(17884):    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
W/System.err(17884):    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
W/System.err(17884): Caused by: com.google.android.gms.auth.GoogleAuthException: Unknown
W/System.err(17884):    at com.google.android.gms.auth.zze.zzb(Unknown Source:20)
W/System.err(17884):    at com.google.android.gms.auth.zzd.zza(Unknown Source:77)
W/System.err(17884):    at com.google.android.gms.auth.zzd.zzb(Unknown Source:20)
W/System.err(17884):    at com.google.android.gms.auth.zzd.getToken(Unknown Source:7)
W/System.err(17884):    at com.google.android.gms.auth.zzd.getToken(Unknown Source:5)
W/System.err(17884):    at com.google.android.gms.auth.GoogleAuthUtil.getToken(Unknown Source:57)
W/System.err(17884):    at io.flutter.plugins.googlesignin.GoogleSignInPlugin$Delegate$6.call(GoogleSignInPlugin.java:455)
W/System.err(17884):    at io.flutter.plugins.googlesignin.GoogleSignInPlugin$Delegate$6.call(GoogleSignInPlugin.java:450)
W/System.err(17884):    at io.flutter.plugins.googlesignin.BackgroundTaskRunner$2.run(BackgroundTaskRunner.java:84)
W/System.err(17884):    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
W/System.err(17884):    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
W/System.err(17884):    at java.lang.Thread.run(Thread.java:764)
```

**Comment by wreppun** [comment]
@emilioschepis , I'm not sure what you ended up doing about this, but I ended up working around it by catching the platform exception, re-initializing my `GoogleSignIn` reference, signing in silently, and then retrying the `.authHeaders` call.

```dart
  GoogleApi() {
    _init([]);
  }

  Future<void> _init(List<String> scopes, {bool suppressErrors = true}) async {
    _googleSignIn = GoogleSignIn(scopes: []);

    await _googleSignIn.signInSilently(suppressErrors: suppressErrors);
  }

  Future<Map<String, String>> get headers async {
    return _makeRequest(() => _googleSignIn.currentUser?.authHeaders ?? {});
  }  

  Future<T> _makeRequest<T>(Future<T> Function() request) async {
    try {
      return await request();
    } on PlatformException catch (platformError, platformStacktrace) {
      debugPrint(
          'Caught a platform exception in GoogleSignIn\n$platformError, $platformStacktrace');

      try {
        debugPrint('Re-initializing _googleSignIn');

        await _init(_googleSignIn.scopes, suppressErrors: false);

        debugPrint('Retrying headers fetch');

        return await request();
      } catch (error, stacktrace) {
        debugPrint('Failed to re-initialize _googleSignIn\n$error, $stacktrace');

        rethrow;
      }
    }
```

**Comment by emilioschepis** [comment]
> @emilioschepis , I'm not sure what you ended up doing about this, but I ended up working around it by catching the platform exception, re-initializing my `GoogleSignIn` reference, signing in silently, and then retrying the `.authHeaders` call.

Thank you, I will definitely try this when I get to work.
I did not think re-initializing would help, but that makes sense since the authentication obviously works on first launch and the only thing that doesn't change during the lifetime of the app is the `GoogleSignIn` instance.

I'll leave this issue open for further comments and maybe an official statement / fix.

**Comment by nvma** [comment]
Same issue here. I ended up doing something similar to @wreppun's method, but it's less than ideal. I'm wondering why so few people experience this problem, I found this ticket in a couple of minutes.

**Comment by nerder** [comment]
We are facing the same issue, but the strange thing for us is that only 1 user (that we know of) is having the issue, meanwhile, we are still seeing other successfully signing in. For proposed fix seems like to fix an issue that can be also fixed by simply removing and reinstalling the app right?

That's a very strange issue, that for some reason seems to be related to the `SHA-1` of the `OAuth 2.0 Client IDs` also. We are a bit on a dead-end here.

**Comment by nerder** [comment]
We are still investigating this but our exception seems to be a bit different. Any clue of what it can be?

```
Non-fatal Exception: java.lang.Exception: PlatformException(exception, Unknown, null)
       at StandardMethodCodec.decodeEnvelope(StandardMethodCodec.java:569)
       at MethodChannel._invokeMethod(MethodChannel.java:159)
       at MethodChannel.invokeMapMethod(MethodChannel.java:359)
```

**Comment by kristhyanmatos** [comment]
olá, passei pelo mesmo problema. Resolvi ajustando a hora do pc

**Comment by burakturker** [comment]
> We are still investigating this but our exception seems to be a bit different. Any clue of what it can be?
> 
> ```
> Non-fatal Exception: java.lang.Exception: PlatformException(exception, Unknown, null)
>        at StandardMethodCodec.decodeEnvelope(StandardMethodCodec.java:569)
>        at MethodChannel._invokeMethod(MethodChannel.java:159)
>        at MethodChannel.invokeMapMethod(MethodChannel.java:359)
> ```

I started getting this error when I set the date of the emulator to a forward date and I deleted my application and reinstalled it and it was fixed.

I've tested it by pushing the emulator date forward a few times. google sign in is getting this error if your emulator date is forward.

if you changed the date&time settings. Changing this setting may fix your problem.
Automatic date & time -> enable

**Comment by fakfa19** [comment]
I solved this problem by don't call `GoogleSignIn().disconnect();` when sign out.
However, I'm not sure this is the right way.

**Comment by stuartmorgan-g** [comment]
Closing as obsolete; this API usage flow does not existing in version 7.x, and the underlying SDK on Android has been replaced. If there are issues with exceptions after expiration with the new API, please file a new issue with details.
