### ISSUE TITLE
Adding a ListView Builder causes error

### ISSUE THREAD

**Issue by bramses** [flutter/flutter#34007]
## Steps to Reproduce

1. 
```
class ExampleApp extends StatelessWidget {
  final List<String> entries = <String>['A', 'B', 'C'];
  final List<int> colorCodes = <int>[600, 500, 100];

  @override
  Widget build(BuildContext context) {
    return ListView.builder(
        padding: const EdgeInsets.all(8.0),
        itemCount: entries.length,
        itemBuilder: (context, int index) {
          return Container(
            height: 50,
            width: 50,
            color: Colors.amber[colorCodes[index]],
            child: Center(
              child: Text('Entry ${entries[index]}'),
            ),
          );
        });
  }
```
## Logs

```
flutter: ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
flutter: The following assertion was thrown building
flutter: RawGestureDetector-[LabeledGlobalKey<RawGestureDetectorState>#03103](state:
flutter: RawGestureDetectorState#1a64a(gestures: <none>, behavior: opaque)):
flutter: 'package:flutter/src/widgets/framework.dart': Failed assertion: line 4869 pos 12: 'child == _child':
flutter: is not true.
flutter:
flutter: Either the assertion indicates an error in the framework itself, or we should provide substantially
flutter: more information in this error message to help you determine and fix the underlying cause.
flutter: In either case, please report this assertion by filing a bug on GitHub:
flutter:   https://github.com/flutter/flutter/issues/new?template=BUG.md
flutter:
flutter: When the exception was thrown, this was the stack:
flutter: #2      SingleChildRenderObjectElement.forgetChild (package:flutter/src/widgets/framework.dart:4869:12)
flutter: #3      Element._retakeInactiveElement (package:flutter/src/widgets/framework.dart:2922:14)
flutter: #4      Element.inflateWidget (package:flutter/src/widgets/framework.dart:2949:32)
flutter: #5      Element.updateChild (package:flutter/src/widgets/framework.dart:2764:12)
flutter: #6      SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4876:14)
flutter: #7      Element.inflateWidget (package:flutter/src/widgets/framework.dart:2961:14)
flutter: #8      Element.updateChild (package:flutter/src/widgets/framework.dart:2764:12)
flutter: #9      SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4876:14)
flutter: #10     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2961:14)
flutter: #11     Element.updateChild (package:flutter/src/widgets/framework.dart:2764:12)
flutter: #12     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4876:14)
flutter: #13     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2961:14)
flutter: #14     Element.updateChild (package:flutter/src/widgets/framework.dart:2764:12)
flutter: #15     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3750:16)
flutter: #16     Element.rebuild (package:flutter/src/widgets/framework.dart:3565:5)
flutter: #17     StatefulElement.update (package:flutter/src/widgets/framework.dart:3894:5)
flutter: #18     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:15)
flutter: #19     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4883:14)
flutter: #20     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:15)
flutter: #21     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3750:16)
flutter: #22     Element.rebuild (package:flutter/src/widgets/framework.dart:3565:5)
flutter: #23     ProxyElement.update (package:flutter/src/widgets/framework.dart:4006:5)
flutter: #24     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:15)
flutter: #25     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4883:14)
flutter: #26     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:15)
flutter: #27     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3750:16)
flutter: #28     Element.rebuild (package:flutter/src/widgets/framework.dart:3565:5)
flutter: #29     StatefulElement.update (package:flutter/src/widgets/framework.dart:3894:5)
flutter: #30     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:15)
flutter: #31     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3750:16)
flutter: #32     Element.rebuild (package:flutter/src/widgets/framework.dart:3565:5)
flutter: #33     StatelessElement.update (package:flutter/src/widgets/framework.dart:3796:5)
flutter: #34     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:15)
flutter: #35     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3750:16)
flutter: #36     Element.rebuild (package:flutter/src/widgets/framework.dart:3565:5)
flutter: #37     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2278:33)
flutter: #38     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding&WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:700:20)
flutter: #39     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:286:5)
flutter: #40     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1012:15)
flutter: #41     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:952:9)
flutter: #42     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.scheduleWarmUpFrame.<anonymous closure> (package:flutter/src/scheduler/binding.dart:773:7)
flutter: #44     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:382:19)
flutter: #45     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:416:5)
flutter: #46     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:171:12)
flutter: (elided 3 frames from class _AssertionError and package dart:async-patch)
```

```
```

```
first_flutter_app git:(master) ✗ flutter doctor -v
[✓] Flutter (Channel stable, v1.5.4-hotfix.2, on Mac OS X 10.14.5 18F132, locale en-US)
    • Flutter version 1.5.4-hotfix.2 at /Users/bramadams/Desktop/code/flutter
    • Framework revision 7a4c33425d (5 weeks ago), 2019-04-29 11:05:24 -0700
    • Engine revision 52c7a1e849
    • Dart version 2.3.0 (build 2.3.0-dev.0.5 a1668566e5)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/bramadams/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.2.1, Build version 10E1001
    • ios-deploy 1.9.4
    • CocoaPods version 1.7.0

[✓] Android Studio (version 3.4)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 36.0.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

[✓] VS Code (version 1.34.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.0.2

[✓] Connected device (1 available)
    • iPhone Xʀ • 452270EF-0DAC-4460-B993-F2BD17E9601E • ios • com.apple.CoreSimulator.SimRuntime.iOS-12-2 (simulator)

• No issues found!
```

**Comment by bramses** [comment]
Needed to wrap it in a MaterialView!
