### ISSUE TITLE
cloud_functions plugin - java.lang.NullPointerException during call()

### ISSUE THREAD

**Issue by eliezedeck** [flutter/flutter#34011]
On iOS, call to a Cloud Function works. On Android, I get the following (same exact Dart function calling the same function):

```
E/MethodChannel#cloud_functions(13636): Failed to handle method call
E/MethodChannel#cloud_functions(13636): java.lang.NullPointerException: null reference
E/MethodChannel#cloud_functions(13636): 	at com.google.android.gms.common.internal.Preconditions.checkNotNull(Unknown Source)
E/MethodChannel#cloud_functions(13636): 	at com.google.firebase.functions.FirebaseFunctions.<init>(com.google.firebase:firebase-functions@@17.0.0:81)
E/MethodChannel#cloud_functions(13636): 	at com.google.firebase.functions.FunctionsMultiResourceComponent.get(com.google.firebase:firebase-functions@@17.0.0:46)
E/MethodChannel#cloud_functions(13636): 	at com.google.firebase.functions.FirebaseFunctions.getInstance(com.google.firebase:firebase-functions@@17.0.0:137)
E/MethodChannel#cloud_functions(13636): 	at com.google.firebase.functions.FirebaseFunctions.getInstance(com.google.firebase:firebase-functions@@17.0.0:146)
E/MethodChannel#cloud_functions(13636): 	at io.flutter.plugins.firebase.cloudfunctions.cloudfunctions.CloudFunctionsPlugin.onMethodCall(CloudFunctionsPlugin.java:45)
E/MethodChannel#cloud_functions(13636): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:222)
E/MethodChannel#cloud_functions(13636): 	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:90)
E/MethodChannel#cloud_functions(13636): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:234)
E/MethodChannel#cloud_functions(13636): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/MethodChannel#cloud_functions(13636): 	at android.os.MessageQueue.next(MessageQueue.java:359)
E/MethodChannel#cloud_functions(13636): 	at android.os.Looper.loop(Looper.java:138)
E/MethodChannel#cloud_functions(13636): 	at android.app.ActivityThread.main(ActivityThread.java:6531)
E/MethodChannel#cloud_functions(13636): 	at java.lang.reflect.Method.invoke(Native Method)
E/MethodChannel#cloud_functions(13636): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:941)
E/MethodChannel#cloud_functions(13636): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:831)
E/flutter (13636): [ERROR:flutter/lib/ui/ui_dart_state.cc(148)] Unhandled Exception: Exception: Unable to call function productsUpdateStocksNumber
```

Flutter Doctor:

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel beta, v1.6.3, on Mac OS X 10.13.6 17G7024, locale en-MG)

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[✓] iOS toolchain - develop for iOS devices (Xcode 10.1)
[✓] Android Studio (version 3.4)
[✓] VS Code (version 1.34.0)
[✓] Connected device (2 available)

• No issues found!
```

**Comment by mcprakash** [comment]
Hi @justinmc 
 Please let me know if you have found a solution to this issue. I am also facing a similar issue. 

Best
Chandra

**Comment by eliezedeck** [comment]
@mcprakash I did not. I used different mechanism instead.

**Comment by mcprakash** [comment]
@eliezedeck Please let me know how I can fix this. That would be of great help.

**Comment by eliezedeck** [comment]
@mcprakash There are countless ways to get your function to be invoked. Remember that Firebase is based on events that causes your functions to be called.

Your functions can be triggered thru:

- Firestore document mutations
- Realtime database mutations
- Storage upload
- ...

Choose what's best for you and what you already use. For example, if you choose Firestore, register a function that will be called when a document is added, make sure your application puts the correct document to the right path and your function will be called.

**Comment by kroikie** [comment]
@eliezedeck

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/1192. Any further collaboration will be done there.
