### ISSUE TITLE
video_player plugin breaks flutter build ios

### ISSUE THREAD

**Issue by wemped** [flutter/flutter#34071]
When I try to build for an iOS device/simulator I get this error message
```
Building test_project for device (ios-release)...
Automatically signing iOS for device deployment using specified development team in Xcode project: **********
Running pod install...                                              1.4s
Running Xcode build...
 ├─Building Dart code...                                     2.4s
 ├─Generating dSYM file...                                   0.2s
 ├─Stripping debug symbols...                                0.0s
 ├─Assembling Flutter resources...                           1.1s
 └─Compiling, linking and signing...                         1.2s
Xcode build done.                                            6.1s
Failed to build iOS app
Error output from Xcode build:
↳
    ** BUILD FAILED **


Xcode's output:
↳
    === BUILD TARGET Runner OF PROJECT Runner WITH CONFIGURATION Release ===
/test_project/ios/Runner/GeneratedPluginRegistrant.m:6:9: fatal error: 'video_player/VideoPlayerPlugin.h' file not found
    #import <video_player/VideoPlayerPlugin.h>
            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    1 error generated.
/test_project/ios/Runner/GeneratedPluginRegistrant.m:6:9: fatal error: 'video_player/VideoPlayerPlugin.h' file not found
    #import <video_player/VideoPlayerPlugin.h>
            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    1 error generated.

Encountered error while building for device.
```

If I remove the video_player plugin from the pubspec.yaml it works as intended. 
I've tried many versions of the video_player plugin, all w/ the same result 
## Steps to Reproduce

1. Create a new Flutter project
2. Add `video_player: 0.10.1+3` to the dependencies 
3. Attempt to build for iOS device or simulator, through Android Studio or command line

## Logs

`flutter build ios --verbose` yields
```
Encountered error while building for device.

#0      throwToolExit (package:flutter_tools/src/base/common.dart:24:3)
#1      BuildIOSCommand.runCommand (package:flutter_tools/src/commands/build_ios.dart:94:7)
<asynchronous suspension>
#2      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:559:18)
#3      _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:77:64)
#4      _rootRunUnary (dart:async/zone.dart:1132:38)
#5      _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#6      _FutureListener.handleValue (dart:async/future_impl.dart:126:18)
#7      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:639:45)
#8      Future._propagateToListeners (dart:async/future_impl.dart:668:32)
#9      Future._complete (dart:async/future_impl.dart:473:7)
#10     _SyncCompleter.complete (dart:async/future_impl.dart:51:12)
#11     _AsyncAwaitCompleter.complete.<anonymous closure> (dart:async-patch/async_patch.dart:33:20)
#12     _rootRun (dart:async/zone.dart:1124:13)
#13     _CustomZone.run (dart:async/zone.dart:1021:19)
#14     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:947:23)
#15     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#16     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#17     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:115:13)
#18     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:5)
```

```
```

**Comment by wemped** [comment]
old but possibly related
https://github.com/flutter/flutter/issues/18265

**Comment by volkangurol** [comment]
can you try this version without  putting ^  ?   video_player: 0.5.2

**Comment by wemped** [comment]
Got the same error
```
Error output from Xcode build:
↳
    ** BUILD FAILED **


Xcode's output:
↳
    /test_project/ios/Runner/GeneratedPluginRegistrant.m:6:9: fatal error: 'video_player/VideoPlayerPlugin.h' file not found
    #import <video_player/VideoPlayerPlugin.h>
            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    1 error generated.

Encountered error while building for device.
```

**Comment by vintage** [comment]
That's not the issue with Flutter itself, but with the plugin you are playing with. You should have more luck reporting issue there.

**Comment by wemped** [comment]
@vintage 
https://github.com/flutter/plugins
`Please file any issues, bugs, or feature requests in the main flutter repo.`

This is plugin maintained by the Flutter team and they've asked to open issues for it on this main repo.

**Comment by wemped** [comment]
I think I found the issue, looks like my `ios/Podfile` wasn't setup correctly.
Found what it was supposed to look like by doing a fresh `flutter create blank` and adding the `video_player` plugin to the pubspec.yaml. After that, I built the project for iOS and a `ios/Podfile` was created that looked like this 
```
# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

# CocoaPods analytics sends network stats synchronously affecting flutter build latency.
ENV['COCOAPODS_DISABLE_STATS'] = 'true'

project 'Runner', {
  'Debug' => :debug,
  'Profile' => :release,
  'Release' => :release,
}

def parse_KV_file(file, separator='=')
  file_abs_path = File.expand_path(file)
  if !File.exists? file_abs_path
    return [];
  end
  pods_ary = []
  skip_line_start_symbols = ["#", "/"]
  File.foreach(file_abs_path) { |line|
      next if skip_line_start_symbols.any? { |symbol| line =~ /^\s*#{symbol}/ }
      plugin = line.split(pattern=separator)
      if plugin.length == 2
        podname = plugin[0].strip()
        path = plugin[1].strip()
        podpath = File.expand_path("#{path}", file_abs_path)
        pods_ary.push({:name => podname, :path => podpath});
      else
        puts "Invalid plugin specification: #{line}"
      end
  }
  return pods_ary
end

target 'Runner' do
  # Prepare symlinks folder. We use symlinks to avoid having Podfile.lock
  # referring to absolute paths on developers' machines.
  system('rm -rf .symlinks')
  system('mkdir -p .symlinks/plugins')

  # Flutter Pods
  generated_xcode_build_settings = parse_KV_file('./Flutter/Generated.xcconfig')
  if generated_xcode_build_settings.empty?
    puts "Generated.xcconfig must exist. If you're running pod install manually, make sure flutter packages get is executed first."
  end
  generated_xcode_build_settings.map { |p|
    if p[:name] == 'FLUTTER_FRAMEWORK_DIR'
      symlink = File.join('.symlinks', 'flutter')
      File.symlink(File.dirname(p[:path]), symlink)
      pod 'Flutter', :path => File.join(symlink, File.basename(p[:path]))
    end
  }

  # Plugin Pods
  plugin_pods = parse_KV_file('../.flutter-plugins')
  plugin_pods.map { |p|
    symlink = File.join('.symlinks', 'plugins', p[:name])
    File.symlink(p[:path], symlink)
    pod p[:name], :path => File.join(symlink, 'ios')
  }
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['ENABLE_BITCODE'] = 'NO'
    end
  end
end
```

Replacing my current `ios/Podfile` w/ the above solved my issue.
