### ISSUE TITLE
StackOverflowError when open Google Assistant

### ISSUE THREAD

**Issue by yuridiniz** [flutter/flutter#34102]
## Steps to Reproduce

1. Add some PlatformView to your app (Can be tested with the Google Maps exemple app [https://pub.dev/packages/google_maps_flutter](https://pub.dev/packages/google_maps_flutter))
2. Open the app on any screen that has a Google Maps
3. Keep the home button pressed until Google Assistant appears
4. Wait a few seconds (+/- 10s)

_Tested on an Android 8.0 physical device_

## Logs

```
Fatal Exception: java.lang.StackOverflowError: stack size 8MB
       at java.lang.reflect.Method.invoke(Method.java)
       at io.flutter.view.AccessibilityViewEmbedder$ReflectionAccessors.getChildId(AccessibilityViewEmbedder.java:477)
       at io.flutter.view.AccessibilityViewEmbedder$ReflectionAccessors.access$500(AccessibilityViewEmbedder.java:411)
       at io.flutter.view.AccessibilityViewEmbedder.addChildrenToFlutterNode(AccessibilityViewEmbedder.java:168)
       at io.flutter.view.AccessibilityViewEmbedder.convertToFlutterNode(AccessibilityViewEmbedder.java:139)
       at io.flutter.view.AccessibilityViewEmbedder.getRootNode(AccessibilityViewEmbedder.java:85)
       at io.flutter.view.AccessibilityBridge.createAccessibilityNodeInfo(AccessibilityBridge.java:509)
       at android.view.View.populateVirtualStructure(View.java:8022)
       at android.view.View.populateVirtualStructure(View.java:8025)
       at android.view.View.populateVirtualStructure(View.java:8025)
       at android.view.View.populateVirtualStructure(View.java:8025)
       at android.view.View.populateVirtualStructure(View.java:8025)
       at android.view.View.populateVirtualStructure(View.java:8025)
       at android.view.View.populateVirtualStructure(View.java:8025)
       at android.view.View.populateVirtualStructure(View.java:8025)
       at android.view.View.populateVirtualStructure(View.java:8025)
       at android.view.View.populateVirtualStructure(View.java:8025)
       at android.view.View.populateVirtualStructure(View.java:8025)
       at android.view.View.onProvideVirtualStructure(View.java:7594)
       at android.view.View.dispatchProvideStructureForAssistOrAutofill(View.java:8094)
       at android.view.View.dispatchProvideStructure(View.java:8037)
       at android.view.ViewGroup.dispatchProvideStructure(ViewGroup.java:3462)
       at android.view.ViewGroup.dispatchProvideStructure(ViewGroup.java:3462)
       at android.view.ViewGroup.dispatchProvideStructure(ViewGroup.java:3462)
       at android.app.assist.AssistStructure$WindowNode.<init>(AssistStructure.java:512)
       at android.app.assist.AssistStructure.<init>(AssistStructure.java:1912)
       at android.app.ActivityThread.handleRequestAssistContextExtras(ActivityThread.java:3056)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1820)
       at android.os.Handler.dispatchMessage(Handler.java:105)
       at android.os.Looper.loop(Looper.java:164)
       at android.app.ActivityThread.main(ActivityThread.java:6592)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:769)
```

```
[✓] Flutter (Channel stable, v1.5.4-hotfix.2, on Linux, locale pt_BR.UTF-8)
    • Flutter version 1.5.4-hotfix.2 at /home/yuri/development/flutter
    • Framework revision 7a4c33425d (6 weeks ago), 2019-04-29 11:05:24 -0700
    • Engine revision 52c7a1e849
    • Dart version 2.3.0 (build 2.3.0-dev.0.5 a1668566e5)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /home/yuri/Android/Sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = /home/yuri/Android/Sdk
    • Java binary at: /home/yuri/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b16-5323222)
    • All Android licenses accepted.

[✓] Android Studio (version 3.4)
    • Android Studio at /home/yuri/android-studio
    • Flutter plugin version 35.2.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b16-5323222)

[!] IntelliJ IDEA Community Edition (version 2019.1)
    • IntelliJ at /home/yuri/idea-IC-191.6707.61
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.dev/intellij-setup/#installing-the-plugins

[✓] VS Code (version 1.34.0)
    • VS Code at /usr/share/code
    • Flutter extension version 3.1.0

[✓] Connected device (1 available)
    • Moto Z2 Play • 0040861752 • android-arm • Android 8.0.0 (API 26)

! Doctor found issues in 1 category.
```

**Comment by sergicastellsague** [comment]
If it helps, we are experiencing this same issue, and the reports we have (not many different users sadly) indicates that it happens with the OnePlus with Android 9.0

**Comment by sergicastellsague** [comment]
Seems to be same as https://github.com/flutter/flutter/issues/38063

**Comment by mikhail-tokarev** [comment]
Hi @yuridiniz 
I see there's an open issue addressing the case you described;
please follow up on the issue liked above.

I'm closing the current one as duplicate
if you disagree please write in the comments
and I will reopen it

(thanks @sergicastellsague)
