### ISSUE TITLE
FATAL EXCEPTION: Timer-0

### ISSUE THREAD

**Issue by BND10706** [flutter/flutter#34101]
After update to Flutter, I am getting this error when I am trying to run a function in my application.

```
E/AndroidRuntime( 9793): FATAL EXCEPTION: Timer-0
E/AndroidRuntime( 9793): Process: org.heartchurch.heartland, PID: 9793
E/AndroidRuntime( 9793): java.lang.RuntimeException: Methods marked with @UiThread must be executed on the main thread. Current thread: Timer-0
E/AndroidRuntime( 9793): 	at io.flutter.embedding.engine.FlutterJNI.ensureRunningOnMainThread(FlutterJNI.java:605)
E/AndroidRuntime( 9793): 	at io.flutter.embedding.engine.FlutterJNI.dispatchPlatformMessage(FlutterJNI.java:515)
E/AndroidRuntime( 9793): 	at io.flutter.embedding.engine.dart.DartMessenger.send(DartMessenger.java:76)
E/AndroidRuntime( 9793): 	at io.flutter.embedding.engine.dart.DartExecutor.send(DartExecutor.java:166)
E/AndroidRuntime( 9793): 	at io.flutter.view.FlutterNativeView.send(FlutterNativeView.java:155)
E/AndroidRuntime( 9793): 	at io.flutter.plugin.common.MethodChannel.invokeMethod(MethodChannel.java:98)
E/AndroidRuntime( 9793): 	at io.flutter.plugin.common.MethodChannel.invokeMethod(MethodChannel.java:84)
E/AndroidRuntime( 9793): 	at live.exit.musicplayer.MusicPlayer$play$1.run(MusicPlayer.kt:49)
E/AndroidRuntime( 9793): 	at java.util.TimerThread.mainLoop(Timer.java:562)
E/AndroidRuntime( 9793): 	at java.util.TimerThread.run(Timer.java:512)
```

```
 info • This class (or a class which this class inherits from) is marked as '@immutable', but one or more of its instance fields are not
          final: PrayerSubmit.things • lib/pages/prayerSubmit.dart:5:7 • must_be_immutable
   info • Avoid using braces in interpolation when not needed • lib/pages/prayerSubmit.dart:30:151 • unnecessary_brace_in_string_interps
   info • The value of the local variable 'sendReports' isn't used • lib/pages/prayerSubmit.dart:32:11 • unused_local_variable

```

```
[✓] Flutter (Channel beta, v1.6.3, on Mac OS X 10.14.4 18E226, locale en-US)
    • Flutter version 1.6.3 at /Users/Brandon/Desktop/Programming/DEV/flutter
    • Framework revision bc7bc94083 (2 weeks ago), 2019-05-23 10:29:07 -0700
    • Engine revision 8dc3a4cde2
    • Dart version 2.3.2 (build 2.3.2-dev.0.0 e3edfd36b2)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/Brandon/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Users/Brandon/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/183.5522156/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.2, Build version 10E125
    • ios-deploy 1.9.4
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.4)
    • Android Studio at /Users/Brandon/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/183.5522156/Android
      Studio.app/Contents
    • Flutter plugin version 35.1.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

[✓] IntelliJ IDEA Ultimate Edition (version 2019.1.3)
    • IntelliJ at /Users/Brandon/Applications/JetBrains Toolbox/IntelliJ IDEA Ultimate.app
    • Flutter plugin version 35.3.3
    • Dart plugin version 191.7479.14

[✓] VS Code (version 1.33.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.0.1

[✓] Connected device (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 9 (API 28) (emulator)

• No issues found!

```

**Comment by anujsing1** [comment]
after flutter upgrade, I am also getting the same error 


E/AndroidRuntime: FATAL EXCEPTION: Timer-0
    Process: x.x.x.x.x, PID: 9178
    java.lang.RuntimeException: Methods marked with @UiThread must be executed on the main thread. Current thread: Timer-0
        at io.flutter.embedding.engine.FlutterJNI.ensureRunningOnMainThread(FlutterJNI.java:794)
        at io.flutter.embedding.engine.FlutterJNI.dispatchPlatformMessage(FlutterJNI.java:684)
        at io.flutter.embedding.engine.dart.DartMessenger.send(DartMessenger.java:80)
        at io.flutter.embedding.engine.dart.DartExecutor.send(DartExecutor.java:189)
        at io.flutter.view.FlutterNativeView.send(FlutterNativeView.java:155)
        at io.flutter.view.FlutterView.send(FlutterView.java:750)
        at io.flutter.plugin.common.MethodChannel.invokeMethod(MethodChannel.java:98)
        at io.flutter.plugin.common.MethodChannel.invokeMethod(MethodChannel.java:84)

**Comment by janmoppel** [comment]
Hello @BND10706 !

Does the problem still persist in the latest stable version?

**Comment by iapicca** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
  
Thanks for your contribution.
