### ISSUE TITLE
FileSystemException: FileSystemException: Cannot open file, path = 'build\app.dill' (OS Error:  The system can not find the file specified.

### ISSUE THREAD

**Issue by tianzhiguo123** [flutter/flutter#34143]
Flutter crash report; please file at https://github.com/flutter/flutter/issues.

## command

flutter build bundle --suppress-analytics --target E:\testDemo\cmlive-flutter\lib/main.dart --compilation-trace-file compilation.txt --target-platform android-arm64 --depfile E:\testDemo\cmlive-flutter\.android\Flutter\build\intermediates\flutter\debug/snapshot_blob.bin.d --asset-dir E:\testDemo\cmlive-flutter\.android\Flutter\build\intermediates\flutter\debug/flutter_assets --debug

## exception

FileSystemException: FileSystemException: Cannot open file, path = 'build\app.dill' (OS Error: 系统找不到指定的文件。
, errno = 2)

```
#0      _File.open.<anonymous closure> (dart:io/file_impl.dart:368:9)
#1      _rootRunUnary (dart:async/zone.dart:1132:38)
#2      _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#3      _FutureListener.handleValue (dart:async/future_impl.dart:129:18)
#4      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:642:45)
#5      Future._propagateToListeners (dart:async/future_impl.dart:671:32)
#6      Future._completeWithValue (dart:async/future_impl.dart:486:5)
#7      Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:516:7)
#8      _rootRun (dart:async/zone.dart:1124:13)
#9      _CustomZone.run (dart:async/zone.dart:1021:19)
#10     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:947:23)
#11     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#12     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#13     _runPendingImmediateCallback (dart:isolate/runtime/libisolate_patch.dart:115:13)
#14     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:172:5)
```

## flutter doctor

```
[✓] Flutter (Channel master, v0.10.3-pre.16, on Microsoft Windows [Version 10.0.17134.765], locale zh-CN)
    • Flutter version 0.10.3-pre.16 at C:\flutter_dev\flutter
    • Framework revision b10868731c (6 months ago), 2018-12-22 14:14:30 +0800
    • Engine revision 215ca15600
    • Dart version 2.2.0 (build 2.2.0-dev.1.1 f9ebf21297)

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at D:\Google\android_tools
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = D:\Google\android_tools
    • Java binary at: D:\as\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
    • All Android licenses accepted.

[✓] Android Studio (version 3.4)
    • Android Studio at D:\as
    • Flutter plugin version 36.0.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

[✓] Connected device (1 available)
    • Redmi 5 Plus • 3383492a0804 • android-arm64 • Android 8.1.0 (API 27)

• No issues found!
```

**Comment by janmoppel** [comment]
Hello @tianzhiguo123 !

Did you manage to solve the issue? Does the problem still persist in the latest stable version?

**Comment by iapicca** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
  
Thanks for your contribution.
