### ISSUE TITLE
A lot of NPEs from flutter 1.6.3

### ISSUE THREAD

**Issue by benadrasni** [flutter/flutter#34182]
Since I switched to flutter beta channel (1.6.3) I am getting a lot of NPEs from Crashlytics

## Logs

```
Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'long android.view.accessibility.AccessibilityNodeInfo.getSourceNodeId()' on a null object reference
       at android.view.View.populateVirtualStructure(View.java:9276)
       at android.view.View.populateVirtualStructure(View.java:9357)
       at android.view.View.populateVirtualStructure(View.java:9357)
       at android.view.View.populateVirtualStructure(View.java:9357)
       at android.view.View.populateVirtualStructure(View.java:9357)
       at android.view.View.onProvideVirtualStructureCompat(View.java:8775)
       at android.view.View.onProvideVirtualStructure(View.java:8756)
       at android.view.View.dispatchProvideStructureForAssistOrAutofill(View.java:9422)
       at android.view.View.dispatchProvideStructure(View.java:9369)
       at android.view.ViewGroup.dispatchProvideStructure(ViewGroup.java:3731)
       at android.view.ViewGroup.dispatchProvideStructure(ViewGroup.java:3731)
       at android.view.ViewGroup.dispatchProvideStructure(ViewGroup.java:3731)
       at android.app.assist.AssistStructure$WindowNode.<init>(AssistStructure.java:519)
       at android.app.assist.AssistStructure.<init>(AssistStructure.java:2047)
       at android.app.ActivityThread.handleRequestAssistContextExtras(ActivityThread.java:3358)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1882)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:214)
       at android.app.ActivityThread.main(ActivityThread.java:6981)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1445)
```
	   
```
Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'long android.view.accessibility.AccessibilityNodeInfo.getSourceNodeId()' on a null object reference
       at android.view.View.populateVirtualStructure(View.java:8020)
       at android.view.View.populateVirtualStructure(View.java:8068)
       at android.view.View.populateVirtualStructure(View.java:8068)
       at android.view.View.populateVirtualStructure(View.java:8068)
       at android.view.View.populateVirtualStructure(View.java:8068)
       at android.view.View.onProvideVirtualStructure(View.java:7629)
       at android.view.View.dispatchProvideStructureForAssistOrAutofill(View.java:8133)
       at android.view.View.dispatchProvideStructure(View.java:8080)
       at android.view.ViewGroup.dispatchProvideStructure(ViewGroup.java:3473)
       at android.view.ViewGroup.dispatchProvideStructure(ViewGroup.java:3473)
       at android.view.ViewGroup.dispatchProvideStructure(ViewGroup.java:3473)
       at android.app.assist.AssistStructure$WindowNode.<init>(AssistStructure.java:512)
       at android.app.assist.AssistStructure.<init>(AssistStructure.java:1912)
       at android.app.ActivityThread.handleRequestAssistContextExtras(ActivityThread.java:3014)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1812)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:172)
       at android.app.ActivityThread.main(ActivityThread.java:6590)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)	
```   
	   
```
Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'long android.view.accessibility.AccessibilityNodeInfo.getSourceNodeId()' on a null object reference
       at android.view.View.populateVirtualStructure(View.java:8695)
       at android.view.View.populateVirtualStructure(View.java:8743)
       at android.view.View.populateVirtualStructure(View.java:8743)
       at android.view.View.populateVirtualStructure(View.java:8743)
       at android.view.View.populateVirtualStructure(View.java:8743)
       at android.view.View.onProvideVirtualStructure(View.java:8304)
       at android.view.View.dispatchProvideStructureForAssistOrAutofill(View.java:8808)
       at android.view.View.dispatchProvideStructure(View.java:8755)
       at android.view.ViewGroup.dispatchProvideStructure(ViewGroup.java:3681)
       at android.view.ViewGroup.dispatchProvideStructure(ViewGroup.java:3681)
       at android.view.ViewGroup.dispatchProvideStructure(ViewGroup.java:3681)
       at android.app.assist.AssistStructure$WindowNode.<init>(AssistStructure.java:512)
       at android.app.assist.AssistStructure.<init>(AssistStructure.java:1912)
       at android.app.ActivityThread.handleRequestAssistContextExtras(ActivityThread.java:3203)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1938)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:164)
       at android.app.ActivityThread.main(ActivityThread.java:7000)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:441)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1408)	   
```
	   
```
Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method android.view.DisplayAdjustments android.view.Display.getDisplayAdjustments()' on a null object reference
       at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1900)
       at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1636)
       at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7946)
       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1092)
       at android.view.Choreographer.doCallbacks(Choreographer.java:893)
       at android.view.Choreographer.doFrame(Choreographer.java:812)
       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1078)
       at android.os.Handler.handleCallback(Handler.java:907)
       at android.os.Handler.dispatchMessage(Handler.java:105)
       at android.os.Looper.loop(Looper.java:216)
       at android.app.ActivityThread.main(ActivityThread.java:7593)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:987)	
```   
	   
```
Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'android.view.DisplayAdjustments android.view.Display.getDisplayAdjustments()' on a null object reference
       at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1746)
       at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1515)
       at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7266)
       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:981)
       at android.view.Choreographer.doCallbacks(Choreographer.java:790)
       at android.view.Choreographer.doFrame(Choreographer.java:721)
       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:967)
       at android.os.Handler.handleCallback(Handler.java:808)
       at android.os.Handler.dispatchMessage(Handler.java:101)
       at android.os.Looper.loop(Looper.java:166)
       at android.app.ActivityThread.main(ActivityThread.java:7529)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:245)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:921)	   
```
	   
```
Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'int android.view.Display.getDisplayId()' on a null object reference
       at android.view.ViewRootImpl$1.onDisplayChanged(ViewRootImpl.java:1201)
       at android.hardware.display.DisplayManagerGlobal$DisplayListenerDelegate.handleMessage(DisplayManagerGlobal.java:515)
       at android.os.Handler.dispatchMessage(Handler.java:108)
       at android.os.Looper.loop(Looper.java:166)
       at android.app.ActivityThread.main(ActivityThread.java:7529)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:245)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:921)	   
```
	   
```
Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'int android.view.Display.getDisplayId()' on a null object reference
       at android.view.ViewRootImpl$1.onDisplayChanged(ViewRootImpl.java:1145)
       at android.hardware.display.DisplayManagerGlobal$DisplayListenerDelegate.handleMessage(DisplayManagerGlobal.java:633)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:193)
       at android.app.ActivityThread.main(ActivityThread.java:6718)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
```

```
Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'int android.view.Display.getDisplayId()' on a null object reference
       at android.view.ViewRootImpl$1.onDisplayChanged(ViewRootImpl.java:1158)
       at android.hardware.display.DisplayManagerGlobal$DisplayListenerDelegate.handleMessage(DisplayManagerGlobal.java:653)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:280)
       at android.app.ActivityThread.main(ActivityThread.java:6710)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
```	

```
Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'int android.view.Display.getDisplayId()' on a null object reference
       at android.view.ViewRootImpl$1.onDisplayChanged(ViewRootImpl.java:1109)
       at android.hardware.display.DisplayManagerGlobal$DisplayListenerDelegate.handleMessage(DisplayManagerGlobal.java:493)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:164)
       at android.app.ActivityThread.main(ActivityThread.java:6626)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:811)	   
````

```
C:\Dev\Projects\abherbs_flutter>flutter analyze
Running "flutter pub get" in abherbs_flutter...                     1,3s
Analyzing abherbs_flutter...
No issues found! (ran in 9.8s)
```

```
C:\Dev\Projects\abherbs_flutter>flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[Ô^Ü] Flutter (Channel beta, v1.6.3, on Microsoft Windows [Version 6.1.7601],
    locale sk-SK)
[Ô^Ü] Android toolchain - develop for Android devices (Android SDK version 28.0.
3)
[Ô^Ü] Android Studio (version 3.4)
[!] IntelliJ IDEA Ultimate Edition (version 2019.1)
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
[!] Connected device
    ! No devices available

! Doctor found issues in 2 categories.
```

**Comment by mayurdhurpate** [comment]
Same here. I'm on the Flutter 1.9.1+hotfix 5 channel and I'm too receiving multiple
`java.lang.NullPointerException: Attempt to invoke virtual method 'android.view.DisplayAdjustments android.view.Display.getDisplayAdjustments()' on a null object reference` style errors.

Any ideas where this might be coming from?

Example (line 1788):

```
Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'android.view.DisplayAdjustments android.view.Display.getDisplayAdjustments()' on a null object reference
       at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1788)
       at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1532)
       at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7419)
       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1092)
       at android.view.Choreographer.doCallbacks(Choreographer.java:888)
       at android.view.Choreographer.doFrame(Choreographer.java:819)
       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1078)
       at android.os.Handler.handleCallback(Handler.java:873)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:201)
       at android.app.ActivityThread.main(ActivityThread.java:6810)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:873)
```
Another one (line 1760)
```
Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'android.view.DisplayAdjustments android.view.Display.getDisplayAdjustments()' on a null object reference
       at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1760)
       at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1505)
       at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7353)
       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1100)
       at android.view.Choreographer.doCallbacks(Choreographer.java:895)
       at android.view.Choreographer.doFrame(Choreographer.java:826)
       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1086)
       at android.os.Handler.handleCallback(Handler.java:873)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:201)
       at android.app.ActivityThread.main(ActivityThread.java:6864)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:873)
```

And a few more. These were reported  on Crashylytics and I couldn't reproduce it. It could be related to Firebase SDKs or Youtube embed SDKs used by the app.

**Flutter Doctor**

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, v1.9.1+hotfix.5, on Mac OS X 10.14.6 18G95, locale en-IN)
 
[!] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses
[✓] Xcode - develop for iOS and macOS (Xcode 10.3)
[✓] Android Studio (version 3.3)
[✓] VS Code (version 1.40.1)
```

**Comment by PingShen** [comment]
how to fix these issues????

**Comment by PingShen** [comment]
no one fix these crashes?
google team?

**Comment by iapicca** [comment]
Hi @benadrasni 
are you still experiencing this issue with the latest stable version of flutter?
If so could you please provide your updated `flutter doctor -v` 
and your `flutter run --verbose` and a reproducible minimal code sample
or the steps to reproduce the problem.
Thank you

**Comment by TahaTesser** [comment]
Hi everyone
Could everyone who still has this problem please file a new issue with the exact descriptions what happens, logs and the output of 'flutter doctor -v'  please.
All system setups can be slightly different so it's always better to open new issues and reference related issues.
Thank you
