### ISSUE TITLE
Flutter Dropdownbutton issue

### ISSUE THREAD

**Issue by shraddhamhetre** [flutter/flutter#34218]
Error message
``` 
══╡ EXCEPTION CAUGHT BY RENDERING LIBRARY ╞═════════════════════════════════════════════════════════
I/flutter (22946): The following assertion was thrown during performLayout():
I/flutter (22946): 'package:flutter/src/material/dropdown.dart': Failed assertion: line 488 pos 15: 'value == null ||
I/flutter (22946): items.where((DropdownMenuItem<T> item) => item.value == value).length == 1': is not true.
I/flutter (22946): Either the assertion indicates an error in the framework itself, or we should provide substantially
I/flutter (22946): more information in this error message to help you determine and fix the underlying cause.
I/flutter (22946): In either case, please report this assertion by filing a bug on GitHub:
I/flutter (22946):   https://github.com/flutter/flutter/issues/new
I/flutter (22946): When the exception was thrown, this was the stack:
I/flutter (22946): #2      new DropdownButton (package:flutter/src/material/dropdown.dart:488:15)
I/flutter (22946): #3      get_Questions_State.getQuestion (package:sps_revised/ir_Template.dart:337:27)
I/flutter (22946): #4      get_Questions_State.build.<anonymous closure> (package:sps_revised/ir_Template.dart:510:34)
I/flutter (22946): #5      SliverChildBuilderDelegate.build (package:flutter/src/widgets/sliver.dart:258:20)
I/flutter (22946): #6      SliverMultiBoxAdaptorElement._build.<anonymous closure> (package:flutter/src/widgets/sliver.dart:783:67)
I/flutter (22946): #7      _HashMap.putIfAbsent (dart:collection/runtime/libcollection_patch.dart:143:29)
I/flutter (22946): #8      SliverMultiBoxAdaptorElement._build (package:flutter/src/widgets/sliver.dart:783:26)
I/flutter (22946): #9      SliverMultiBoxAdaptorElement.createChild.<anonymous closure> (package:flutter/src/widgets/sliver.dart:796:55)
I/flutter (22946): #10     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2235:19)
I/flutter (22946): #11     SliverMultiBoxAdaptorElement.createChild (package:flutter/src/widgets/sliver.dart:789:11)
I/flutter (22946): #12     RenderSliverMultiBoxAdaptor._createOrObtainChild.<anonymous closure> (package:flutter/src/rendering/sliver_multi_box_adaptor.dart:254:23)
I/flutter (22946): #13     RenderObject.invokeLayoutCallback.<anonymous closure> (package:flutter/src/rendering/object.dart:1659:58)
I/flutter (22946): #14     PipelineOwner._enableMutationsToDirtySubtrees (package:flutter/src/rendering/object.dart:728:15)
I/flutter (22946): #15     RenderObject.invokeLayoutCallback (package:flutter/src/rendering/object.dart:1659:13)
I/flutter (22946): #16     RenderSliverMultiBoxAdaptor._createOrObtainChild (package:flutter/src/rendering/sliver_multi_box_adaptor.dart:243:5)
I/flutter (22946): #17     RenderSliverMultiBoxAdaptor.insertAndLayoutChild (package:flutter/src/rendering/sliver_multi_box_adaptor.dart:381:5)
I/flutter (22946): #18     RenderSliverList.performLayout.advance (package:flutter/src/rendering/sliver_list.dart:190:19)
I/flutter (22946): #19     RenderSliverList.performLayout (package:flutter/src/rendering/sliver_list.dart:233:19)
I/flutter (22946): #20     RenderObject.layout (package:flutter/src/rendering/object.dart:1563:7)
I/flutter (22946): #21     RenderSliverPadding.performLayout (package:flutter/src/rendering/sliver_padding.dart:182:11)
I/flutter (22946): #22     RenderObject.layout (package:flutter/src/rendering/object.dart:1563:7)
I/flutter (22946): #23     RenderViewportBase.layoutChildSequence (package:flutter/src/rendering/viewport.dart:405:13)
I/flutter (22946): #24     RenderViewport._attemptLayout (package:flutter/src/rendering/viewport.dart:1320:12)
I/flutter (22946): #25     RenderViewport.performLayout (package:flutter/src/rendering/viewport.dart:1238:20)
I/flutter (22946): #26     RenderObject.layout (package:flutter/src/rendering/object.dart:1563:7)
I/flutter (22946): #27     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:108:13)
I/flutter (22946): #28     RenderObject.layout (package:flutter/src/rendering/object.dart:1563:7)
I/flutter (22946): #29     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:108:13)
I/flutter (22946): #30     RenderObject.layout (package:flutter/src/rendering/object.dart:1563:7)
I/flutter (22946): #31     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:108:13)
I/flutter (22946): #32     RenderObject.layout (package:flutter/src/rendering/object.dart:1563:7)
I/flutter (22946): #33     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:108:13)
I/flutter (22946): #34     RenderObject.layout (package:flutter/src/rendering/object.dart:1563:7)
I/flutter (22946): #35     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:108:13)
I/flutter (22946): #36     RenderObject.layout (package:flutter/src/rendering/object.dart:1563:7)
I/flutter (22946): #37     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:108:13)
I/flutter (22946): #38     RenderObject.layout (package:flutter/src/rendering/object.dart:1563:7)
I/flutter (22946): #39     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:108:13)
I/flutter (22946): #40     RenderObject.layout (package:flutter/src/rendering/object.dart:1563:7)
I/flutter (22946): #41     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:108:13)
I/flutter (22946): #42     RenderObject.layout (package:flutter/src/rendering/object.dart:1563:7)
I/flutter (22946): #43     MultiChildLayoutDelegate.layoutChild (package:flutter/src/rendering/custom_layout.dart:141:11)
I/flutter (22946): #44     _ScaffoldLayout.performLayout (package:flutter/src/material/scaffold.dart:338:7)
I/flutter (22946): #45     MultiChildLayoutDelegate._callPerformLayout (package:flutter/src/rendering/custom_layout.dart:211:7)
I/flutter (22946): #46     RenderCustomMultiChildLayoutBox.performLayout (package:flutter/src/rendering/custom_layout.dart:355:14)
I/flutter (22946): #47     RenderObject.layout (package:flutter/src/rendering/object.dart:1563:7)
I/flutter (22946): #48     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:108:13)
I/flutter (22946): #49     RenderObject.layout (package:flutter/src/rendering/object.dart:1563:7)
I/flutter (22946): #50     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:108:13)
I/flutter (22946): #51     _RenderCustomClip.performLayout (package:flutter/src/rendering/proxy_box.dart:1192:11)
I/flutter (22946): #52     RenderObject.layout (package:flutter/src/rendering/object.dart:1563:7)
I/flutter (22946): #53     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:108:13)
I/flutter (22946): #54     RenderObject.layout (package:flutter/src/rendering/object.dart:1563:7)
I/flutter (22946): #55     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:108:13)
I/flutter (22946): #56     RenderObject.layout (package:flutter/src/rendering/object.dart:1563:7)
I/flutter (22946): #57     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:108:13)
I/flutter (22946): #58     RenderObject.layout (package:flutter/src/rendering/object.dart:1563:7)
I/flutter (22946): #59     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:108:13)
I/flutter (22946): #60     RenderObject.layout (package:flutter/src/rendering/object.dart:1563:7)
I/flutter (22946): #61     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:108:13)
I/flutter (22946): #62     RenderObject.layout (package:flutter/src/rendering/object.dart:1563:7)
I/flutter (22946): #63     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:108:13)
I/flutter (22946): #64     RenderObject.layout (package:flutter/src/rendering/object.dart:1563:7)
I/flutter (22946): #65     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:108:13)
I/flutter (22946): #66     RenderObject.layout (package:flutter/src/rendering/object.dart:1563:7)
I/flutter (22946): #67     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:108:13)
I/flutter (22946): #68     RenderOffstage.performLayout (package:flutter/src/rendering/proxy_box.dart:2884:13)
I/flutter (22946): #69     RenderObject.layout (package:flutter/src/rendering/object.dart:1563:7)
I/flutter (22946): #70     RenderStack.performLayout (package:flutter/src/rendering/stack.dart:520:15)
I/flutter (22946): #71     RenderObject._layoutWithoutResize (package:flutter/src/rendering/object.dart:1438:7)
I/flutter (22946): #72     PipelineOwner.flushLayout (package:flutter/src/rendering/object.dart:697:18)
I/flutter (22946): #73     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding.drawFrame (package:flutter/src/rendering/binding.dart:270:19)
I/flutter (22946): #74     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding&WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:654:13)
I/flutter (22946): #75     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:208:5)
I/flutter (22946): #76     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:990:15)
I/flutter (22946): #77     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:930:9)
I/flutter (22946): #78     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:842:5)
I/flutter (22946): #79     _invoke (dart:ui/hooks.dart:128:13)
I/flutter (22946): #80     _drawFrame (dart:ui/hooks.dart:117:3)
I/flutter (22946): (elided 2 frames from class _AssertionError)
I/flutter (22946): The following RenderObject was being processed when the exception was fired:
I/flutter (22946):   RenderSliverList#30514 relayoutBoundary=up2 NEEDS-LAYOUT NEEDS-PAINT
I/flutter (22946):   creator: SliverList ← MediaQuery ← SliverPadding ← Viewport ← _ScrollableScope ←
I/flutter (22946):   IgnorePointer-[GlobalKey#a4cc9] ← Semantics ← Listener ← _GestureSemantics ←
I/flutter (22946):   RawGestureDetector-[LabeledGlobalKey<RawGestureDetectorState>#53730] ←
I/flutter (22946):   _ScrollSemantics-[GlobalKey#9215c] ← RepaintBoundary ← ⋯
I/flutter (22946):   parentData: paintOffset=Offset(0.0, 0.0) (can use size)
I/flutter (22946):   constraints: SliverConstraints(AxisDirection.down, GrowthDirection.forward, ScrollDirection.idle,
I/flutter (22946):   scrollOffset: 0.0, remainingPaintExtent: 512.0, crossAxisExtent: 360.0, crossAxisDirection:
I/flutter (22946):   AxisDirection.right, viewportMainAxisExtent: 512.0, remainingCacheExtent: 762.0 cacheOrigin: 0.0 )
I/flutter (22946):   geometry: null
I/flutter (22946):   currently live children: 0 to 0
I/flutter (22946): This RenderObject had the following descendants (showing up to depth 5):
I/flutter (22946):   RenderRepaintBoundary#ca9a1 relayoutBoundary=up3 NEEDS-PAINT
I/flutter (22946):     RenderSemanticsAnnotations#979ae relayoutBoundary=up4 NEEDS-PAINT
I/flutter (22946):       RenderPadding#bc09f relayoutBoundary=up5 NEEDS-PAINT
I/flutter (22946):         RenderPhysicalShape#268c4 relayoutBoundary=up6 NEEDS-PAINT
I/flutter (22946):           RenderCustomPaint#4f366 relayoutBoundary=up7 NEEDS-PAINT
I/flutter (22946): ════════════════════════════════════════════════════════════════════════════════════════════════════
I/flutter (22946): Another exception was thrown: NoSuchMethodError: The getter 'scrollOffsetCorrection' was called on null.
I/flutter (22946): Another exception was thrown: NoSuchMethodError: The method 'debugAssertIsValid' was called on null.
I/flutter (22946): Another exception was thrown: NoSuchMethodError: The getter 'visible' was called on null.
```

**Comment by shraddhamhetre** [comment]
This is my code:

new DropdownButton(
                        items: option.map((String value) {
                          return new DropdownMenuItem<String>(
                            value: value,
                            child: new Text(value),
                          );
                        }
                        ).toList(),
                        onChanged:(value){
                          setState(() {
                            currentvalue= value;
                            questAnsTransList[index].answer= value.toString();
                            questAnsTransList[index].jndid= DateTime.now().millisecondsSinceEpoch.toString();
                            print(currentvalue.toString());
                          });

                        },
                        value: currentvalue,
                      )

**Comment by jpeiffer** [comment]
From your error, the following assertion failed:
> items.where((DropdownMenuItem<T> item) => item.value == value).length == 1)

What that does in simplified terms is ensure that every item has a unique value.  What seems likely is that you have two options in the dropdown where the values equal each other, and that's not allowed per the docs.

> The [items] must have distinct values.

**Comment by justinmc** [comment]
Good call @jpeiffer.  I saw another issue recently with the same error message (https://github.com/flutter/flutter/issues/34168) but I think these might just be the same user error.

@shraddhamhetre Let me know if that doesn't fix your problem.

**Comment by VladyslavBondarenko** [comment]
@shraddhamhetre 
I hope you've solved the issue, closing
if you disagree please write in the comments and I will reopen it. 
Thank you
