### ISSUE TITLE
.android file lost in flutter module

### ISSUE THREAD

**Issue by JiweiMaster** [flutter/flutter#34303]
when I use flutter module which inserted into android native project,  I add a pub into pubspec.yaml file, it caused the loss of .android file of flutter module, the follwing is flutter_o1.log, the error didn't always happened.

Flutter crash report; please file at https://github.com/flutter/flutter/issues.

## command

flutter --no-color packages get

## exception

FileSystemException: FileSystemException: Deletion failed, path = 'E:\AndroidStudioProject\flutter_module\.android' (OS Error: 另一个程序正在使用此文件，进程无法访问。
, errno = 32)

```
#0      _Directory._deleteSync (dart:io/directory_impl.dart:206:7)
#1      FileSystemEntity.deleteSync (dart:io/file_system_entity.dart:466:47)
#2      ForwardingFileSystemEntity.deleteSync (package:file/src/forwarding/forwarding_file_system_entity.dart:72:16)
#3      _deleteIfExistsSync (package:flutter_tools/src/project.dart:511:15)
#4      AndroidProject._regenerateLibrary (package:flutter_tools/src/project.dart:463:5)
#5      AndroidProject.ensureReadyForPlatformSpecificTooling (package:flutter_tools/src/project.dart:427:7)
<asynchronous suspension>
#6      FlutterProject.ensureReadyForPlatformSpecificTooling (package:flutter_tools/src/project.dart:165:19)
<asynchronous suspension>
#7      PackagesGetCommand.runCommand (package:flutter_tools/src/commands/packages.dart:97:23)
<asynchronous suspension>
#8      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:559:18)
#9      _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:77:64)
#10     _rootRunUnary (dart:async/zone.dart:1132:38)
#11     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#12     _FutureListener.handleValue (dart:async/future_impl.dart:126:18)
#13     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:639:45)
#14     Future._propagateToListeners (dart:async/future_impl.dart:668:32)
#15     Future._complete (dart:async/future_impl.dart:473:7)
#16     _SyncCompleter.complete (dart:async/future_impl.dart:51:12)
#17     _AsyncAwaitCompleter.complete.<anonymous closure> (dart:async-patch/async_patch.dart:33:20)
#18     _rootRun (dart:async/zone.dart:1124:13)
#19     _CustomZone.run (dart:async/zone.dart:1021:19)
#20     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:947:23)
#21     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#22     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#23     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:115:13)
#24     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:5)
```

## flutter doctor

```
[✓] Flutter (Channel stable, v1.5.4-hotfix.2, on Microsoft Windows [Version 10.0.17134.765], locale zh-CN)
    • Flutter version 1.5.4-hotfix.2 at E:\nrecWorkSpace\flutter\flutter
    • Framework revision 7a4c33425d (6 weeks ago), 2019-04-29 11:05:24 -0700
    • Engine revision 52c7a1e849
    • Dart version 2.3.0 (build 2.3.0-dev.0.5 a1668566e5)

[!] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at E:\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 28.0.3
    • Java binary at: E:\Program Files\Android\android-studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses

[!] Android Studio (version 3.0)
    • Android Studio at E:\Program Files\Android\Android Studio3.0.1
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b01)

[✓] Android Studio (version 3.3)
    • Android Studio at E:\Program Files\Android\android-studio
    • Flutter plugin version 33.4.1
    • Dart plugin version 182.5215
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)

[!] IntelliJ IDEA Ultimate Edition (version 2018.3)
    • IntelliJ at E:\Program Files\IntelliJ IDEA 2018.3.5
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.dev/intellij-setup/#installing-the-plugins

[✓] Connected device (1 available)
    • OD103 • 9f1ac2c9 • android-arm64 • Android 7.1.1 (API 25)

! Doctor found issues in 3 categories.
```

**Comment by jmagman** [comment]
Missing a `\` between flutter_module and .android? `E:\AndroidStudioProject\flutter_module.android`

**Comment by blasten** [comment]
This is expected. The `.android` directory is regenerated automatically when you run `flutter pub get` or the build command.   You can also run `flutter build make-host-app-editable` to keep the `.android` directory around.

**Comment by blasten** [comment]
Duplicate of https://github.com/flutter/flutter/issues/30842
