### ISSUE TITLE
Crash when run 'Flutter doctor'

### ISSUE THREAD

**Issue by huiyumiao** [flutter/flutter#34311]
Flutter crash report; please file at https://github.com/flutter/flutter/issues.

## command

flutter doctor

## exception

FileSystemException: FileSystemException: Cannot copy file to '/Users/mhy/flutter/bin/cache/artifacts/engine/ios/LICENSE', path = '/Users/mhy/flutter/LICENSE' (OS Error: No such file or directory, errno = 2)

```
#0      _File.copy.<anonymous closure> (dart:io/file_impl.dart:336:9)
#1      _rootRunUnary (dart:async/zone.dart:1132:38)
#2      _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#3      _FutureListener.handleValue (dart:async/future_impl.dart:126:18)
#4      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:639:45)
#5      Future._propagateToListeners (dart:async/future_impl.dart:668:32)
#6      Future._completeWithValue (dart:async/future_impl.dart:483:5)
#7      Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:513:7)
#8      _rootRun (dart:async/zone.dart:1124:13)
#9      _CustomZone.run (dart:async/zone.dart:1021:19)
#10     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:947:23)
#11     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#12     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#13     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:115:13)
#14     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:5)
```

## flutter doctor

```
[32m[✓][39m Flutter (Channel beta, v1.6.3, on Mac OS X 10.14.5 18F132, locale zh-Hans-CN)
    [32m•[39m Flutter version 1.6.3 at /Users/mhy/flutter
    [32m•[39m Framework revision bc7bc94083 (3 weeks ago), 2019-05-23 10:29:07 -0700
    [32m•[39m Engine revision 8dc3a4cde2
    [32m•[39m Dart version 2.3.2 (build 2.3.2-dev.0.0 e3edfd36b2)

[31m[✗][39m Android toolchain - develop for Android devices
    [31m✗[39m Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/setup/#android-setup for detailed instructions).
      If the Android SDK has been installed to a custom location, set ANDROID_HOME to that location.
      You may also want to add it to your PATH environment variable.


[33m[!][39m iOS toolchain - develop for iOS devices (Xcode 10.2.1)
    [32m•[39m Xcode at /Applications/Xcode.app/Contents/Developer
    [32m•[39m Xcode 10.2.1, Build version 10E1001
    [31m✗[39m Verify that all connected devices have been paired with this computer in Xcode.
      If all devices have been paired, libimobiledevice and ideviceinstaller may require updating.
      To update with Brew, run:
        brew update
        brew uninstall --ignore-dependencies libimobiledevice
        brew uninstall --ignore-dependencies usbmuxd
        brew install --HEAD usbmuxd
        brew unlink usbmuxd
        brew link usbmuxd
        brew install --HEAD libimobiledevice
        brew install ideviceinstaller
    [31m✗[39m ios-deploy not installed. To install:
        brew install ios-deploy
    [32m•[39m CocoaPods version 1.5.3

[33m[!][39m Android Studio (not installed)
    [32m•[39m Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/setup/#android-setup for detailed instructions).

[33m[!][39m IntelliJ IDEA Ultimate Edition (version 2017.3.1)
    [32m•[39m IntelliJ at /Applications/IntelliJ IDEA.app
    [31m✗[39m Flutter plugin not installed; this adds Flutter specific functionality.
    [31m✗[39m Dart plugin not installed; this adds Dart specific functionality.
    [32m•[39m For information about installing plugins, see
      https://flutter.dev/intellij-setup/#installing-the-plugins

[32m[✓][39m VS Code (version 1.35.0)
    [32m•[39m VS Code at /Applications/Visual Studio Code.app/Contents
    [32m•[39m Flutter extension version 3.1.0

[32m[✓][39m Connected device (2 available)
    [32m•[39m iPhone 5s • 9f3db3ef637811211ddc05f54b45cdcdebe2fbd1 • ios • iOS 10.3.1
    [32m•[39m iPhone Xʀ • C77E2F8A-DE82-403F-B35D-BE6AC714EC32     • ios • com.apple.CoreSimulator.SimRuntime.iOS-12-2
      (simulator)

[33m![39m Doctor found issues in 4 categories.
```

**Comment by jonahwilliams** [comment]
Can you try running `flutter precache --force`?

**Comment by huiyumiao** [comment]
I had reinstalled the SDK and then it is ok. Thanks

**Comment by jonahwilliams** [comment]
Okay, it looks like something went wrong when we were caching artifacts and we didn't detect it. We should probably need download checksums for all artifacts.

**Comment by patelkrunal78** [comment]
Very Similar To [Flutter plugin not installed error;. When running flutter doctor](https://icetutor.com/question/flutter-plugin-not-installed-error-when-running-flutter-doctor)
