### ISSUE TITLE
Rendering Assertion Error: bodyMaxHeight <= math.max(0.0, looseConstraints.maxHeight - contentTop)

### ISSUE THREAD

**Issue by green-Flamingo** [flutter/flutter#34326]
## Introduction
We have a StatefullWidget containing a Scaffold, a Scrollview in its body, a BottomAppBar with a notch containing a FloatingActionButton.

When scrolling around randomly, the following assertion error is thrown:

```
I/flutter (29780): ══╡ EXCEPTION CAUGHT BY RENDERING LIBRARY ╞═════════════════════════════════════════════════════════
I/flutter (29780): The following assertion was thrown during performLayout():
I/flutter (29780): 'package:flutter/src/material/scaffold.dart': Failed assertion: line 423 pos 16: 'bodyMaxHeight <=
I/flutter (29780): math.max(0.0, looseConstraints.maxHeight - contentTop)': is not true.
I/flutter (29780): 
I/flutter (29780): Either the assertion indicates an error in the framework itself, or we should provide substantially
I/flutter (29780): more information in this error message to help you determine and fix the underlying cause.
I/flutter (29780): In either case, please report this assertion by filing a bug on GitHub:
I/flutter (29780):   https://github.com/flutter/flutter/issues/new?template=BUG.md
I/flutter (29780): 
I/flutter (29780): When the exception was thrown, this was the stack:
I/flutter (29780): #2      _ScaffoldLayout.performLayout (package:flutter/src/material/scaffold.dart:423:16)
I/flutter (29780): #3      MultiChildLayoutDelegate._callPerformLayout (package:flutter/src/rendering/custom_layout.dart:212:7)
I/flutter (29780): #4      RenderCustomMultiChildLayoutBox.performLayout (package:flutter/src/rendering/custom_layout.dart:356:14)
I/flutter (29780): #5      RenderObject._layoutWithoutResize (package:flutter/src/rendering/object.dart:1519:7)
I/flutter (29780): #6      PipelineOwner.flushLayout (package:flutter/src/rendering/object.dart:766:18)
I/flutter (29780): #7      _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding.drawFrame (package:flutter/src/rendering/binding.dart:347:19)
I/flutter (29780): #8      _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding&WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:701:13)
I/flutter (29780): #9      _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:286:5)
I/flutter (29780): #10     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1012:15)
I/flutter (29780): #11     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:952:9)
I/flutter (29780): #12     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:864:5)
I/flutter (29780): #16     _invoke (dart:ui/hooks.dart:219:10)
I/flutter (29780): #17     _drawFrame (dart:ui/hooks.dart:178:3)
I/flutter (29780): (elided 5 frames from class _AssertionError and package dart:async)
I/flutter (29780): 
I/flutter (29780): The following RenderObject was being processed when the exception was fired:
I/flutter (29780):   RenderCustomMultiChildLayoutBox#0211b NEEDS-LAYOUT NEEDS-PAINT
I/flutter (29780):   creator: CustomMultiChildLayout ← AnimatedBuilder ← DefaultTextStyle ← AnimatedDefaultTextStyle ←
I/flutter (29780):   _InkFeatures-[GlobalKey#fe169 ink renderer] ← NotificationListener<LayoutChangedNotification> ←
I/flutter (29780):   PhysicalModel ← AnimatedPhysicalModel ← Material ← PrimaryScrollController ← _ScaffoldScope ←
I/flutter (29780):   Scaffold ← ⋯
I/flutter (29780):   parentData: <none> (can use size)
I/flutter (29780):   constraints: BoxConstraints(w=411.4, h=683.4)
I/flutter (29780):   size: Size(411.4, 683.4)
I/flutter (29780): This RenderObject had the following descendants (showing up to depth 5):
I/flutter (29780):   _RenderLayoutBuilder#c4759 relayoutBoundary=up1
I/flutter (29780):     RenderConstrainedBox#f3db9 relayoutBoundary=up2
I/flutter (29780):       RenderRepaintBoundary#7768d NEEDS-PAINT
I/flutter (29780):         RenderCustomPaint#4fd8f NEEDS-PAINT
I/flutter (29780):           RenderRepaintBoundary#3b2ce
I/flutter (29780):   RenderConstrainedBox#f158f relayoutBoundary=up1 NEEDS-PAINT
I/flutter (29780):     RenderPhysicalShape#9331d NEEDS-PAINT
I/flutter (29780):       RenderCustomPaint#26663 NEEDS-PAINT
I/flutter (29780):         _RenderInkFeatures#a489b NEEDS-PAINT
I/flutter (29780):           RenderPadding#db65e NEEDS-PAINT
I/flutter (29780):   RenderStack#80cab relayoutBoundary=up1
I/flutter (29780):     RenderTransform#033b9 relayoutBoundary=up2
I/flutter (29780):       RenderTransform#b621a relayoutBoundary=up3
I/flutter (29780):         RenderSemanticsAnnotations#56fe9 relayoutBoundary=up4
I/flutter (29780):           _RenderInputPadding#e9ac7 relayoutBoundary=up5
I/flutter (29780): ════════════════════════════════════════════════════════════════════════════════════════════════════
```

Because we are using a BottomAppBar with a notch and a FloatingActionButton (FAB) inside it, we want the area behind the FAB, forming the notch, to be transparent, because we are hiding the BottomAppBar on scroll, with the help of an AnimatedContainer. Therefore we have set the following flag set to true inside our Scaffold:

`extendBody: true`

When removing this flag, the error does not occur anymore, but as stated above, this is not an option for us.

## Steps to Reproduce
We created a sample code to replicate the error, in as small a scale as possible:

https://gist.github.com/green-Flamingo/4cf417f80bc3c6aa86c4a27cf287fefb

## Logs

```
>flutter analyze
Analyzing flutter_app...
No issues found! (ran in 4.4s)
```

```
>flutter doctor -v
[√] Flutter (Channel stable, v1.5.4-hotfix.2, on Microsoft Windows [Version 10.0.17134.799], locale de-DE)
    • Flutter version 1.5.4-hotfix.2 at C:\Users\robin\Documents\flutter_windows_v1.2.1-stable\flutter
    • Framework revision 7a4c33425d (6 weeks ago), 2019-04-29 11:05:24 -0700
    • Engine revision 52c7a1e849
    • Dart version 2.3.0 (build 2.3.0-dev.0.5 a1668566e5)


[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at C:\Users\robin\AppData\Local\Android\Sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = C:\Users\robin\AppData\Local\Android\Sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
    • All Android licenses accepted.

[√] Android Studio (version 3.4)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 36.0.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

[√] IntelliJ IDEA Ultimate Edition (version 2018.2)
    • IntelliJ at C:\Users\robin\AppData\Local\JetBrains\Toolbox\apps\IDEA-U\ch-0\182.4505.22
    • Flutter plugin version 31.3.3
    • Dart plugin version 182.5215

[√] Connected device (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 9 (API 28) (emulator)

• No issues found!
```

**Comment by shihaohong** [comment]
Hi! I just tested the code you provided in the gist and was not able to reproduce the issue. Is there a particular way you have to scroll to cause the error to trigger?

**Comment by green-Flamingo** [comment]
Hey @shihaohong 
We created a gif for you in which we reproduced the error. We tested it with several emulators (on different Windows machines) and Android devices, and unfortunately the error occurred with every setup. As already mentioned, when you set `extendBody: false`, the error no longer occurs. Hope this helps!

![2019-06-12-20-35-26](https://user-images.githubusercontent.com/51404636/59379539-2f7e7a80-8d57-11e9-8c1c-6a558365fe5f.gif)

**Comment by shihaohong** [comment]
I just tried it and I cannot seem to reproduce this on the `master` branch. I don't doubt the authenticity of your issue though, we'll probably have to do some more digging as to what's causing this particular issue. 

At first glance into the code in `scaffold.dart`, for some reason, `bodyMaxHeight` (the height of the body + bottom widget) somehow exceeds the designated allowed space briefly, triggering the assert you see. However, it's not immediately clear why that's triggering in this scenario.

**Comment by green-Flamingo** [comment]
We just did a few more tests and found out that the more powerful the device is, the longer you can scroll back and forth without getting the error, as shown on the gif [here](https://github.com/flutter/flutter/issues/34326#issuecomment-501418280). In addition, the error does not occur if you scroll only very slowly.

Unfortunately, we have just started to develop an app with the flutter framework and therefore have a relatively superficial understanding of the things.

**Comment by shihaohong** [comment]
@green-Flamingo That's pretty useful information. My hunch is that there could be that some logic in the code that does not accurately clamp down the values to the maximum height that the body can occupy while taking into account the height of the bottom widget. With more powerful device, maybe those devices can pick up updates to those heights faster and more accurately, and with slower devices, they are slower to adjust to those heights and are thus causing the issue you're seeing.

We'll need to verify that this is the case, and if so, fix it. Thank you for being so comprehensive!

**Comment by shihaohong** [comment]
In the meantime, since this is triggered by an assert statement, your users will not see this assert message, nor do I think there will be any major side-effects to the issue you're seeing. Asserts are only thrown when built in debug mode. One way to verify this is to build it in release mode and see if anything unusual happens.

**Comment by shihaohong** [comment]
In the meantime, since this is triggered by an assert statement, your users should not experience this error message. Asserts are only thrown when built in debug mode. You could verify if there are any real side effects to your users by trying your build in release mode and see if anything unusual happens.
