### ISSUE TITLE
build failed

### ISSUE THREAD

**Issue by asfaqueahmedsakkar** [flutter/flutter#34320]
flutter build bundle --suppress-analytics --target F:\Android\team_plan\lib\main.dart --track-widget-creation --compilation-trace-file compilation.txt --target-platform android-arm64 --depfile F:\Android\team_plan\build\app\intermediates\flutter\debug/snapshot_blob.bin.d --asset-dir F:\Android\team_plan\build\app\intermediates\flutter\debug/flutter_assets --debug

## exception

NoSuchMethodError: NoSuchMethodError: The getter 'length' was called on null.
Receiver: null
Tried calling: length

```
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:50:5)
#1      _Uri._uriEncode (dart:core-patch/uri_patch.dart:44:23)
#2      Uri.encodeFull (dart:core/uri.dart:1145:17)
#3      MappedListIterable.elementAt (dart:_internal/iterable.dart:414:29)
#4      MappedListIterable.elementAt (dart:_internal/iterable.dart:414:40)
#5      ListIterable.toList (dart:_internal/iterable.dart:219:19)
#6      FlutterManifest.assets (package:flutter_tools/src/flutter_manifest.dart:182:11)
#7      _parseAssets (package:flutter_tools/src/asset.dart:558:40)
#8      _ManifestAssetBundle.build (package:flutter_tools/src/asset.dart:142:53)
<asynchronous suspension>
#9      buildAssets (package:flutter_tools/src/bundle.dart:178:40)
<asynchronous suspension>
#10     build (package:flutter_tools/src/bundle.dart:147:36)
<asynchronous suspension>
#11     BuildBundleCommand.runCommand (package:flutter_tools/src/commands/build_bundle.dart:75:11)
<asynchronous suspension>
#12     FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:559:18)
<asynchronous suspension>
#13     FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:495:33)
<asynchronous suspension>
#14     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:142:29)
<asynchronous suspension>
#15     _rootRun (dart:async/zone.dart:1124:13)
#16     _CustomZone.run (dart:async/zone.dart:1021:19)
#17     _runZoned (dart:async/zone.dart:1516:10)
#18     runZoned (dart:async/zone.dart:1463:12)
#19     AppContext.run (package:flutter_tools/src/base/context.dart:141:18)
<asynchronous suspension>
#20     FlutterCommand.run (package:flutter_tools/src/runner/flutter_command.dart:486:20)
#21     CommandRunner.runCommand (package:args/command_runner.dart:196:27)
<asynchronous suspension>
#22     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:396:21)
<asynchronous suspension>
#23     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:142:29)
<asynchronous suspension>
#24     _rootRun (dart:async/zone.dart:1124:13)
#25     _CustomZone.run (dart:async/zone.dart:1021:19)
#26     _runZoned (dart:async/zone.dart:1516:10)
#27     runZoned (dart:async/zone.dart:1463:12)
#28     AppContext.run (package:flutter_tools/src/base/context.dart:141:18)
<asynchronous suspension>
#29     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:356:19)
<asynchronous suspension>
#30     CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:111:29)
#31     new Future.sync (dart:async/future.dart:224:31)
#32     CommandRunner.run (package:args/command_runner.dart:111:11)
#33     FlutterCommandRunner.run (package:flutter_tools/src/runner/flutter_command_runner.dart:242:18)
#34     run.<anonymous closure> (package:flutter_tools/runner.dart:60:20)
<asynchronous suspension>
#35     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:142:29)
<asynchronous suspension>
#36     _rootRun (dart:async/zone.dart:1124:13)
#37     _CustomZone.run (dart:async/zone.dart:1021:19)
#38     _runZoned (dart:async/zone.dart:1516:10)
#39     runZoned (dart:async/zone.dart:1463:12)
#40     AppContext.run (package:flutter_tools/src/base/context.dart:141:18)
<asynchronous suspension>
#41     runInContext (package:flutter_tools/src/context_runner.dart:50:24)
<asynchronous suspension>
#42     run (package:flutter_tools/runner.dart:51:10)
#43     main (package:flutter_tools/executable.dart:60:9)
<asynchronous suspension>
#44     main (file:///D:/flutter/packages/flutter_tools/bin/flutter_tools.dart:8:3)
#45     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:298:32)
#46     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:171:12)
```

## flutter doctor

```
[✓] Flutter (Channel beta, v1.5.4-hotfix.2, on Microsoft Windows [Version 10.0.17763.529], locale en-US)
    • Flutter version 1.5.4-hotfix.2 at D:\flutter
    • Framework revision 7a4c33425d (6 weeks ago), 2019-04-29 11:05:24 -0700
    • Engine revision 52c7a1e849
    • Dart version 2.3.0 (build 2.3.0-dev.0.5 a1668566e5)

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at C:\Users\Ry\AppData\Local\Android\Sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = C:\Users\Ry\AppData\Local\Android\Sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
    • All Android licenses accepted.

[✓] Android Studio (version 3.4)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 36.1.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

[✓] VS Code (version 1.34.0)
    • VS Code at C:\Users\Ry\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.0.2

[✓] VS Code, 64-bit edition (version 1.33.1)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Flutter extension version 3.0.2

[✓] Connected device (2 available)
    • Redmi Note 4  • 789eda320504  • android-arm64 • Android 7.0 (API 24)
    • ONEPLUS A5000 • emulator-5554 • android-x86   • Android 7.1.1 (API 25)

• No issues found!
```

**Comment by jonahwilliams** [comment]
While we definitely shouldn't crash here, it looks like there is probably a syntax error in your pubspec.yaml, could you post that as well?
