### ISSUE TITLE
App crashes when sending a notification from Firebase

### ISSUE THREAD

**Issue by StanBegthel** [flutter/flutter#34325]
## Steps to Reproduce
So I got the parts of code for the notifications done, even the implementations in build.gradle etc. And it still gives me an error.

main.dart
```
class _AppState extends State<App> {
  FirebaseAuth _auth = FirebaseAuth.instance;
  FirebaseMessaging _firebaseMessaging = FirebaseMessaging();

  @override
  void initState() {
    super.initState();
    firebaseCloudMessaging_Listeners();
  }

  void firebaseCloudMessaging_Listeners() {
    if (Platform.isIOS) iOS_Permission();


    _firebaseMessaging.getToken().then((token) {
      print(token);
    });

    _firebaseMessaging.configure(
      onMessage: (Map<String, dynamic> message) async {
        print('on message $message');
      },
      onResume: (Map<String, dynamic> message) async {
        print('on resume $message');
      },
      onLaunch: (Map<String, dynamic> message) async {
        print('on launch $message');
      },
    );
  }

  void iOS_Permission() {
    _firebaseMessaging.requestNotificationPermissions(
        IosNotificationSettings(sound: true, badge: true, alert: true));
    _firebaseMessaging.onIosSettingsRegistered
        .listen((IosNotificationSettings settings) {
      print("Settings registered: $settings");
    });
  }
```

Android manifest
```
<!--suppress ALL -->
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    package="com.p4.tinder">
    <uses-permission android:name="android.permission.INTERNET"/>

    <!-- io.flutter.app.FlutterApplication is an android.app.Application that
         calls FlutterMain.startInitialization(this); in its onCreate method.
         In most cases you can leave this as-is, but you if you want to provide
         additional functionality it is fine to subclass or reimplement
         FlutterApplication and put your custom class here. -->
    <application
        android:name="io.flutter.app.FlutterApplication"
        android:label="tinder"
        android:icon="@mipmap/ic_launcher">

        <activity
            android:name=".MainActivity"
            android:launchMode="singleTop"
            android:theme="@style/LaunchTheme"
            android:configChanges="orientation|keyboardHidden|keyboard|screenSize|locale|layoutDirection|fontScale|screenLayout|density|uiMode"
            android:hardwareAccelerated="true"
            android:windowSoftInputMode="adjustResize">
            <!-- This keeps the window background of the activity showing
                 until Flutter renders its first frame. It can be removed if
                 there is no splash screen (such as the default splash screen
                 defined in @style/LaunchTheme). -->

            <meta-data
                android:name="io.flutter.app.android.SplashScreenUntilFirstFrame"
                android:value="true" />
            <intent-filter>
                <action android:name="FLUTTER_NOTIFICATION_CLICK" />
                <category android:name="android.intent.category.DEFAULT" />
            </intent-filter>
            <intent-filter>
                <action android:name="android.intent.action.MAIN"/>
                <category android:name="android.intent.category.LAUNCHER"/>
            </intent-filter>
        </activity>
        <service
            android:name=".FlutterFirebaseMessagingService">
            <intent-filter>
                <action android:name="com.google.firebase.MESSAGING_EVENT" />
            </intent-filter>
            <intent-filter>
                <action android:name="FLUTTER_NOTIFICATION_CLICK" />
                <category android:name="android.intent.category.DEFAULT" />
            </intent-filter>
        </service>
    </application>
</manifest>

```

## Logs
```
D/FirebaseAuth(15346): Notifying id token listeners about user ( Uy8bYR2eKHdDN2eNmRtWsauj1iy1 ).
W/com.p4.tinder(15346): Accessing hidden field Ljava/net/Socket;->impl:Ljava/net/SocketImpl; (light greylist, reflection)
W/com.p4.tinder(15346): Accessing hidden method Ldalvik/system/CloseGuard;->get()Ldalvik/system/CloseGuard; (light greylist, linking)
W/com.p4.tinder(15346): Accessing hidden method Ldalvik/system/CloseGuard;->open(Ljava/lang/String;)V (light greylist, linking)
W/com.p4.tinder(15346): Accessing hidden field Ljava/io/FileDescriptor;->descriptor:I (light greylist, JNI)
W/com.p4.tinder(15346): Accessing hidden method Ljava/security/spec/ECParameterSpec;->setCurveName(Ljava/lang/String;)V (light greylist, reflection)
W/com.p4.tinder(15346): Accessing hidden method Ldalvik/system/BlockGuard;->getThreadPolicy()Ldalvik/system/BlockGuard$Policy; (light greylist, linking)
W/com.p4.tinder(15346): Accessing hidden method Ldalvik/system/BlockGuard$Policy;->onNetwork()V (light greylist, linking)
D/AndroidRuntime(15346): Shutting down VM
E/AndroidRuntime(15346): FATAL EXCEPTION: main
E/AndroidRuntime(15346): Process: com.p4.tinder, PID: 15346
E/AndroidRuntime(15346): java.lang.RuntimeException: Unable to instantiate service com.p4.tinder.FlutterFirebaseMessagingService: java.lang.ClassNotFoundException: Didn't find class "com.p4.tinder.FlutterFirebaseMessagingService" on path: DexPathList[[zip file "/data/app/com.p4.tinder-3ry9p2qura9V_CMN3p3EPw==/base.apk"],nativeLibraryDirectories=[/data/app/com.p4.tinder-3ry9p2qura9V_CMN3p3EPw==/lib/x86, /data/app/com.p4.tinder-3ry9p2qura9V_CMN3p3EPw==/base.apk!/lib/x86, /system/lib]]
E/AndroidRuntime(15346): 	at android.app.ActivityThread.handleCreateService(ActivityThread.java:3519)
E/AndroidRuntime(15346): 	at android.app.ActivityThread.access$1300(ActivityThread.java:199)
E/AndroidRuntime(15346): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1666)
E/AndroidRuntime(15346): 	at android.os.Handler.dispatchMessage(Handler.java:106)
E/AndroidRuntime(15346): 	at android.os.Looper.loop(Looper.java:193)
E/AndroidRuntime(15346): 	at android.app.ActivityThread.main(ActivityThread.java:6669)
E/AndroidRuntime(15346): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(15346): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
E/AndroidRuntime(15346): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
E/AndroidRuntime(15346): Caused by: java.lang.ClassNotFoundException: Didn't find class "com.p4.tinder.FlutterFirebaseMessagingService" on path: DexPathList[[zip file "/data/app/com.p4.tinder-3ry9p2qura9V_CMN3p3EPw==/base.apk"],nativeLibraryDirectories=[/data/app/com.p4.tinder-3ry9p2qura9V_CMN3p3EPw==/lib/x86, /data/app/com.p4.tinder-3ry9p2qura9V_CMN3p3EPw==/base.apk!/lib/x86, /system/lib]]
E/AndroidRuntime(15346): 	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:134)
E/AndroidRuntime(15346): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
E/AndroidRuntime(15346): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
E/AndroidRuntime(15346): 	at android.app.AppComponentFactory.instantiateService(AppComponentFactory.java:103)
E/AndroidRuntime(15346): 	at androidx.core.app.CoreComponentFactory.instantiateService(CoreComponentFactory.java:68)
E/AndroidRuntime(15346): 	at android.app.ActivityThread.handleCreateService(ActivityThread.java:3514)
E/AndroidRuntime(15346): 	... 8 more
I/Process (15346): Sending signal. PID: 15346 SIG: 9
```

```info: This class (or a class which this class inherits from) is marked as '@immutable', but one or more of its instance fields are not final: ButtonNS.vertical (must_be_immutable at [tinder] lib\Components\ButtonNS.dart:3)
info: This class (or a class which this class inherits from) is marked as '@immutable', but one or more of its instance fields are not final: ButtonS.vertical (must_be_immutable at [tinder] lib\Components\ButtonS.dart:3)
info: Unused import: 'package:tinder/Constants.dart'. (unused_import at [tinder] lib\Components\CustomTile.dart:2)
info: Unused import: 'package:tinder/Components/UserExpensionItem.dart'. (unused_import at [tinder] lib\Components\EditedExpensionTile.dart:6)
info: The value of the local variable 'theme' isn't used. (unused_local_variable at [tinder] lib\Components\EditedExpensionTile.dart:193)
info: The value of the field '_receivers' isn't used. (unused_field at [tinder] lib\Data\CloudFireStoreFeedback.dart:6)
info: The value of the field '_questions' isn't used. (unused_field at [tinder] lib\Data\CloudFireStoreFeedback.dart:7)
info: Name non-constant identifiers using lowerCamelCase. (non_constant_identifier_names at [tinder] lib\Data\QuestionInfo.dart:3)
info: Name non-constant identifiers using lowerCamelCase. (non_constant_identifier_names at [tinder] lib\Data\QuestionInfo.dart:5)
info: This method overrides a method annotated as @mustCallSuper in 'State', but does not invoke the overridden method. (must_call_super at [tinder] lib\Views\App.dart:23)
info: This function has a return type of 'Widget', but doesn't end with a return statement. (missing_return at [tinder] lib\Views\App.dart:69)
info: Unused import: 'package:tinder/main.dart'. (unused_import at [tinder] lib\Views\ExtraFeedback.dart:9)
info: The top level variable '_firestore' isn't used. (unused_element at [tinder] lib\Views\ExtraFeedback.dart:11)
info: This class (or a class which this class inherits from) is marked as '@immutable', but one or more of its instance fields are not final: ExtraFeedback.userId (must_be_immutable at [tinder] lib\Views\ExtraFeedback.dart:17)
info: Unused import: 'package:async/async.dart'. (unused_import at [tinder] lib\Views\HomeWidget.dart:10)
info: Unused import: 'package:tinder/Data/QuestionInfo.dart'. (unused_import at [tinder] lib\Views\HomeWidget.dart:11)
info: This function has a return type of 'Stream<QuerySnapshot>', but doesn't end with a return statement. (missing_return at [tinder] lib\Views\HomeWidget.dart:38)
info: Set literals were not supported until version 2.2, but this code is required to be able to run on earlier versions. (sdk_version_set_literal at [tinder] lib\Views\HomeWidget.dart:106)
info: Equality operator `==` invocation with references of unrelated types. (unrelated_type_equality_checks at [tinder] lib\Views\HomeWidget.dart:106)
info: This class (or a class which this class inherits from) is marked as '@immutable', but one or more of its instance fields are not final: ResetPassword.showSpinner, ResetPassword.email (must_be_immutable at [tinder] lib\Views\ResetPassword.dart:7)
info: Unused import: 'login_screen.dart'. (unused_import at [tinder] lib\Views\TeacherWidget.dart:5)
info: Unused import: 'package:avataaar_image/avataaar_image.dart'. (unused_import at [tinder] lib\Views\TeacherWidget.dart:7)
info: Unused import: 'package:tinder/main.dart'. (unused_import at [tinder] lib\Views\TeacherWidget.dart:8)
info: The top level variable '_auth' isn't used. (unused_element at [tinder] lib\Views\TeacherWidget.dart:10)
info: Unused import: 'package:firebase_auth/firebase_auth.dart'. (unused_import at [tinder] lib\Views\answers_feedback_screen.dart:3)
info: Unused import: 'package:tinder/Data/CloudFirestoreUsers.dart'. (unused_import at [tinder] lib\Views\answers_feedback_screen.dart:5)
info: Unused import: 'specific_feedback_screen.dart'. (unused_import at [tinder] lib\Views\answers_feedback_screen.dart:6)
info: Use `;` instead of `{}` for empty constructor bodies. (empty_constructor_bodies at [tinder] lib\Views\answers_feedback_screen.dart:15)
info: The value of the field '_userId' isn't used. (unused_field at [tinder] lib\Views\answers_feedback_screen.dart:29)
info: The top level variable '_formKey' isn't used. (unused_element at [tinder] lib\Views\feedback_test.dart:22)
info: The top level variable '_auth' isn't used. (unused_element at [tinder] lib\Views\feedback_test.dart:23)
info: The top level variable '_userId' isn't used. (unused_element at [tinder] lib\Views\feedback_test.dart:26)
info: The top level variable '_result' isn't used. (unused_element at [tinder] lib\Views\feedback_test.dart:27)
info: The top level variable '_totalString' isn't used. (unused_element at [tinder] lib\Views\feedback_test.dart:28)
info: The value of the local variable 'user' isn't used. (unused_local_variable at [tinder] lib\Views\login_screen.dart:86)
info: The value of the field '_userId' isn't used. (unused_field at [tinder] lib\Views\read_feedback_screen.dart:21)
info: The value of the local variable 'title' isn't used. (unused_local_variable at [tinder] lib\Views\read_feedback_screen.dart:66)
info: The value of the local variable 'snackBar' isn't used. (unused_local_variable at [tinder] lib\Views\read_feedback_screen.dart:67)
info: This class (or a class which this class inherits from) is marked as '@immutable', but one or more of its instance fields are not final: SelectQuestionsScreen.cloudFirestoreUsers, SelectQuestionsScreen.cloudFireStroreQuestions, SelectQuestionsScreen.cloudFireStoreFeedback (must_be_immutable at [tinder] lib\Views\select_questions_screen.dart:15)
info: Unused import: 'dart:io'. (unused_import at [tinder] lib\Views\specific_feedback_screen.dart:1)
info: Unused import: 'package:firebase_auth/firebase_auth.dart'. (unused_import at [tinder] lib\Views\specific_feedback_screen.dart:6)
info: Unused import: 'package:flutter/services.dart'. (unused_import at [tinder] lib\Views\specific_feedback_screen.dart:7)
info: Unused import: 'package:share_extend/share_extend.dart'. (unused_import at [tinder] lib\Views\specific_feedback_screen.dart:15)
info: Use `;` instead of `{}` for empty constructor bodies. (empty_constructor_bodies at [tinder] lib\Views\specific_feedback_screen.dart:22)
info: The value of the field '_selectedChoice' isn't used. (unused_field at [tinder] lib\Views\specific_feedback_screen.dart:28)
info: The value of the field '_result' isn't used. (unused_field at [tinder] lib\Views\specific_feedback_screen.dart:40)
info: The value of the field '_totalString' isn't used. (unused_field at [tinder] lib\Views\specific_feedback_screen.dart:41)
info: The value of the local variable 'pdf' isn't used. (unused_local_variable at [tinder] lib\Views\specific_feedback_screen.dart:84)
info: Unused import: 'package:tinder/Views/ExtraFeedback.dart'. (unused_import at [tinder] lib\main.dart:3)
info: Unused import: 'package:firebase_core/firebase_core.dart'. (unused_import at [tinder] lib\main.dart:10)
info: The value of the field '_auth' isn't used. (unused_field at [tinder] lib\main.dart:20)
info: Name non-constant identifiers using lowerCamelCase. (non_constant_identifier_names at [tinder] lib\main.dart:29)
info: Name non-constant identifiers using lowerCamelCase. (non_constant_identifier_names at [tinder] lib\main.dart:50)
```

```
[√] Flutter (Channel stable, v1.5.4-hotfix.2, on Microsoft Windows [Version 10.0.17763.503], locale nl-NL)
    • Flutter version 1.5.4-hotfix.2 at C:\src\flutter
    • Framework revision 7a4c33425d (6 weeks ago), 2019-04-29 11:05:24 -0700
    • Engine revision 52c7a1e849
    • Dart version 2.3.0 (build 2.3.0-dev.0.5 a1668566e5)


[!] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at C:\Users\stanb\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses

[√] Android Studio (version 3.4)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 36.0.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

[!] IntelliJ IDEA Ultimate Edition (version 2018.3)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA 2018.3.3
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.dev/intellij-setup/#installing-the-plugins

[!] VS Code (version 1.33.1)
    • VS Code at C:\Users\stanb\AppData\Local\Programs\Microsoft VS Code
    X Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[√] Connected device (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 9 (API 28) (emulator)

! Doctor found issues in 3 categories.

```

**Comment by StanBegthel** [comment]
By removing the service section in AndroidManifest.xml it completely works! Thanks for the ones who were thinking about a solution though!
