### ISSUE TITLE
DeadLine Excedeed with cloud function

### ISSUE THREAD

**Issue by DjivaCanessane** [flutter/flutter#34383]
Till this morning I didn't get any error running my flutter code which uses cloud Function :

    try{
                      var reponseServer = 
                       await (CloudFunctions.instance.getHttpsCallable(
                        functionName: "sendNote",     
                        )
                        .call(<String,dynamic>{
                          "prenomReceiver":prenom,
                          "numeroReceiver": numero,
                          "numeroSender": user.phoneNumber,
                        }).then((result){return result;}));
                    if(reponseServer.data == 0){
                      Fluttertoast.showToast(
                        msg: "Envoie réussie",
                        toastLength: Toast.LENGTH_LONG,
                        gravity: ToastGravity.CENTER,
                        timeInSecForIos: 3,
                        backgroundColor: Colors.black,
                        textColor: Colors.white
                      );
                      Navigator.of(context).popUntil((route) => route.isFirst);
                    }else{
                    Navigator.of(context).popUntil((route) => route.isFirst);
                    }
                    
                    }catch(e){
                      print(e);
                    }
But now I get a cloudFunction error 'DEADLINE EXCEDEED':

CloudFunctionsException
hashCode:987002427
runtimeType:Type (CloudFunctionsException)
code:"DEADLINE_EXCEEDED"
message:"DEADLINE_EXCEEDED"
details:null

, even if I executed the function only 20 times today.

This is my cloud function code:

    exports.sendNote = functions.https.onCall(async(data,context)=>{
    const numeroReceiver:string = data['numeroReceiver'];
    console.log('1');
    const numeroSender:string = data['numeroSender'];
    console.log('2');
    const critere:number = data['critere'];
    console.log('3');
    context.instanceIdToken;
    console.log('4');
    admin.auth().verifyIdToken;
    console.log('5');
    const connaissance:number = data['connaissance'];
    console.log('15');
    const version:number = 1;
    console.log('16');

    function recalcul(note:number, moyenne:number, nombreNote:number, coeff:number){
        console.log('17');
        let resultat:number;
        console.log('18');
        resultat = (((moyenne*nombreNote)+(note*coeff))/(nombreNote+1)).valueOf();
        console.log('19');
        return resultat;
    }

    try{
        
        console.log(numeroReceiver);
        console.log(numeroSender);
        console.log(data);
        
        await admin.firestore().collection('Connaissance').doc('numeroReceiver').collection('Contact').doc(numeroSender).create({'valeur':humour});
        console.log('20pre');
        await admin.firestore().collection('Critere').doc(numeroReceiver).collection('Contact').doc(numeroSender).create({'valeur':critere});
       
        if(retour === true){
            console.log('29');
            const connaissanceBA:number = connaissance;
            console.log('30');
            const amisB = admin.firestore().collection('Amis').doc(numeroSender);
            console.log('33');
            const amisA = admin.firestore().collection('Amis').doc(numeroReceiver);
            console.log('34');

            const demande = await admin.firestore().collection('Demande').where('demandeur','==',numeroReceiver).where('demandé','==',numeroSender).get();
            console.log('35');
            demande.forEach(async documentSnapshot => {
                await documentSnapshot.ref.update({'retour': true});
                console.log('36');
            });
            console.log('37');

            const connaissanceAB:number = (await admin.firestore().collection("Connaissance").doc(numeroSender).collection('Contact').doc(numeroReceiver).get()).get('valeur');
            console.log('40');
            const connaissanceABBA:number = Math.round((connaissanceAB+connaissanceBA)/2);
            console.log('41');
            console.log(connaissanceAB);
            console.log(connaissanceBA);
            console.log(((connaissanceAB+connaissanceBA)/2));
            console.log(connaissanceABBA);

            await amisA.update({
                [`amis.${numeroSender}`] : {
                    connaissanceABBA: connaissanceABBA,
                    version: version,
                    time: admin.firestore.FieldValue.serverTimestamp()
                  }
            });
            console.log('42');
            await amisB.update({
                [`amis.${numeroSender}`] : {
                    connaissanceABBA: connaissanceABBA,
                    version: version,
                    time: admin.firestore.FieldValue.serverTimestamp()
                  }
            });
            console.log('43');
            const critereAB = await admin.firestore().collection('Humour').doc(numeroSender).collection('Contact').doc(numeroReceiver).get();
            var coeffAscendant:number = 0;
            console.log('66');
            var coeffDescendant:number = 0;
            console.log('67');
            
            switch(connaissanceABBA){
                case 1:{
                    console.log('68');
                    coeffAscendant = 0.5;
                    console.log('69');
                    coeffDescendant = 1.5;
                    console.log('70');
                    break;
                }
                case 2:{
                    console.log('71');
                    coeffAscendant = 0.6;
                    console.log('72');
                    coeffDescendant = 1.4;
                    console.log('73');
                    break;
                }
                case 3:{
                    console.log('74');
                    coeffAscendant = 0.7;
                    console.log('75');
                    coeffDescendant = 1.3;
                    console.log('76');
                    break;
                }
                case 4:{
                    console.log('77');
                    coeffAscendant = 0.8;
                    console.log('78');
                    coeffDescendant = 1.2;
                    console.log('79');
                    break;
                }
                case 5:{
                    console.log('80');
                    coeffAscendant = 0.9;
                    console.log('81');
                    coeffDescendant = 1.1;
                    console.log('82');
                    break;
                }
                case 6:{
                    console.log('84');
                    coeffAscendant = 1.0;
                    console.log('85');
                    coeffDescendant = 1.0;
                    console.log('86');
                    break;
                }
                case 7:{
                    console.log('87');
                    coeffAscendant = 1.1;
                    console.log('88');
                    coeffDescendant = 0.9;
                    console.log('89');
                    break;
                }
                case 8:{
                    console.log('90');
                    coeffAscendant = 1.2;
                    console.log('91');
                    coeffDescendant = 0.8;
                    console.log('92');
                    break;
                }
                case 9:{
                    console.log('93');
                    coeffAscendant = 1.3;
                    console.log('94');
                    coeffDescendant = 0.7;
                    console.log('95');
                    break;

                }
                case 10:{
                    console.log('96');
                    coeffAscendant = 1.5;
                    console.log('97');
                    coeffDescendant = 0.5;
                    console.log('98');
                    break;
                }
            }

            if(coeffAscendant !== 0){
                console.log('99');
                await admin.firestore().collection('Critere').doc(numeroReceiver).collection('Contact').doc(numeroSender)
                .update({'coeff':coeffAscendant});
                console.log('100');
                await moyenneA.ref.update({'critere': recalcul(critere,moyenneA.get('critere'),nombreNoteA,coeffAscendant)});
                console.log('109');

                await critereAB.ref.update({'coeff':coeffAscendant});
                console.log('119');
                await moyenneB.ref.update({'critere': recalcul(critereAB.get('valeur'),moyenneB.get('critere'),nombreNoteB,coeffAscendant)});
                console.log('136');
                await moyenneB.ref.update({'nombre': 1+nombreNoteB});
                console.log('137');
            }else{
                console.log('138');
                return 2;
            }

          
            const profilB = await admin.firestore().collection('Profil').doc(numeroSender).get();
            console.log('139');
            const payload = 
            {
                "notification":
                {
                    "title": "Youhouuu",
                    "body": profilB.get('prenom')+" vous a accepté, allez voir ses criteres !",
                    "sound": "default"
                },
                "data": 
                {
                    "sendername": "app",
                    "message": profilB.get('prenom')+" vous a accepté, allez voir ses criteres !"
                }
            };
            console.log('140');
            await admin.messaging().sendToDevice((await admin.firestore().collection('Token').doc(numeroReceiver).get()).get('token'), payload);
            console.log('141');
            return 0;

Firebase console is showing me every console.log until console.log('141'); except console.log('138').
Firebase console finishes the execution with this message: sendNote
Function execution took 15730 ms, finished with status code: 200.

## Logs

[  +48 ms] executing: [/Users/evvon/flutter/] git log -n 1 --pretty=format:%H
[  +49 ms] Exit code 0 from: git log -n 1 --pretty=format:%H
[        ] 7a4c33425ddd78c54aba07d86f3f9a4a0051769b
[        ] executing: [/Users/evvon/flutter/] git describe --match v*.*.* --first-parent --long --tags
[  +24 ms] Exit code 0 from: git describe --match v*.*.* --first-parent --long --tags
[        ] v1.5.4-hotfix.2-0-g7a4c33425
[  +12 ms] executing: [/Users/evvon/flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[  +16 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/stable
[        ] executing: [/Users/evvon/flutter/] git ls-remote --get-url origin
[  +16 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[  +83 ms] executing: [/Users/evvon/flutter/] git rev-parse --abbrev-ref HEAD
[  +18 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] stable
[ +395 ms] executing: /Users/evvon/Library/Android/sdk/platform-tools/adb devices -l
[  +14 ms] Exit code 0 from: /Users/evvon/Library/Android/sdk/platform-tools/adb devices -l
[   +2 ms] List of devices attached
           10d6c699               device usb:337641472X product:whyred model:Redmi_Note_5 device:whyred transport_id:19
[  +12 ms] executing: idevice_id -h
[  +51 ms] /usr/bin/xcrun simctl list --json devices
[ +250 ms] More than one device connected; please specify a device with the '-d <deviceId>' flag, or use '-d all' to act on all devices.
[   +6 ms] /Users/evvon/Library/Android/sdk/platform-tools/adb -s 10d6c699 shell getprop
[  +95 ms] ro.hardware = qcom
[   +5 ms] Redmi Note 5 • 10d6c699                             • android-arm64 • Android 8.1.0 (API 27)
[   +1 ms] iPhone 7     • 0F5B3A36-C545-452D-ADFE-731D14926C92 • ios           • com.apple.CoreSimulator.SimRuntime.iOS-12-2 (simulator)
[  +16 ms] "flutter run" took 864ms.
[        ] "flutter run" took 864ms.

#0      throwToolExit (package:flutter_tools/src/base/common.dart:24:3)
#1      RunCommand.validateCommand (package:flutter_tools/src/commands/run.dart:257:7)
<asynchronous suspension>
#2      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:538:11)
<asynchronous suspension>
#3      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:495:33)
<asynchronous suspension>
#4      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:142:29)
<asynchronous suspension>
#5      _rootRun (dart:async/zone.dart:1124:13)
#6      _CustomZone.run (dart:async/zone.dart:1021:19)
#7      _runZoned (dart:async/zone.dart:1516:10)
#8      runZoned (dart:async/zone.dart:1463:12)
#9      AppContext.run (package:flutter_tools/src/base/context.dart:141:18)
<asynchronous suspension>
#10     FlutterCommand.run (package:flutter_tools/src/runner/flutter_command.dart:486:20)
#11     CommandRunner.runCommand (package:args/command_runner.dart:196:27)
<asynchronous suspension>
#12     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:396:21)
<asynchronous suspension>
#13     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:142:29)
<asynchronous suspension>
#14     _rootRun (dart:async/zone.dart:1124:13)
#15     _CustomZone.run (dart:async/zone.dart:1021:19)
#16     _runZoned (dart:async/zone.dart:1516:10)
#17     runZoned (dart:async/zone.dart:1463:12)
#18     AppContext.run (package:flutter_tools/src/base/context.dart:141:18)
<asynchronous suspension>
#19     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:356:19)
<asynchronous suspension>
#20     CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:111:29)
#21     new Future.sync (dart:async/future.dart:224:31)
#22     CommandRunner.run (package:args/command_runner.dart:111:11)
#23     FlutterCommandRunner.run (package:flutter_tools/src/runner/flutter_command_runner.dart:242:18)
#24     run.<anonymous closure> (package:flutter_tools/runner.dart:60:20)
<asynchronous suspension>
#25     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:142:29)
<asynchronous suspension>
#26     _rootRun (dart:async/zone.dart:1124:13)
#27     _CustomZone.run (dart:async/zone.dart:1021:19)
#28     _runZoned (dart:async/zone.dart:1516:10)
#29     runZoned (dart:async/zone.dart:1463:12)
#30     AppContext.run (package:flutter_tools/src/base/context.dart:141:18)
<asynchronous suspension>
#31     runInContext (package:flutter_tools/src/context_runner.dart:50:24)
<asynchronous suspension>
#32     run (package:flutter_tools/runner.dart:51:10)
#33     main (package:flutter_tools/executable.dart:60:9)
<asynchronous suspension>
#34     main (file:///Users/evvon/flutter/packages/flutter_tools/bin/flutter_tools.dart:8:3)
#35     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:298:32)
#36     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:171:12)

Analyzing baobab...                                                     

   info • This function has a return type of 'Color', but doesn't end with a return statement • lib/A.dart:42:10 • missing_return
   info • Unused import: 'package:cloud_firestore/cloud_firestore.dart' • lib/AmisAmi.dart:2:8 • unused_import
   info • Unused import: 'package:flutter_spinkit/flutter_spinkit.dart' • lib/AmisAmi.dart:4:8 • unused_import
   info • Unused import: 'package:flutter_sticky_header/flutter_sticky_header.dart' • lib/AmisAmi.dart:5:8 • unused_import
   info • Unused import: 'note.dart' • lib/demande.dart:4:8 • unused_import
   info • Unused import: 'main.dart' • lib/demande.dart:7:8 • unused_import
   info • Unused import: 'package:flutter_fluid_slider/flutter_fluid_slider.dart' • lib/demande.dart:9:8 • unused_import
   info • Unused import: 'dart:ui' • lib/graphique.dart:3:8 • unused_import
   info • The method '_apuyer' isn't used • lib/inscription.dart:32:8 • unused_element
   info • The value of the field '_time' isn't used • lib/inscription.dart:42:13 • unused_field
   info • 'child' is deprecated and shouldn't be used • lib/inscription.dart:152:19 • deprecated_member_use
warning • The parameter 'onPressed' is required • lib/inscription.dart:155:23 • missing_required_param
   info • Unused import: 'demande.dart' • lib/main.dart:4:8 • unused_import
   info • Unused import: 'profil.dart' • lib/main.dart:5:8 • unused_import
   info • Unused import: 'note.dart' • lib/main.dart:6:8 • unused_import
   info • Unused import: 'inscription.dart' • lib/main.dart:7:8 • unused_import
   info • Unused import: 'package:firebase_core/firebase_core.dart' • lib/main.dart:10:8 • unused_import
   info • Unused import: 'package:cloud_firestore/cloud_firestore.dart' • lib/note.dart:4:8 • unused_import
   info • Unused import: 'main.dart' • lib/note.dart:6:8 • unused_import
   info • Unused import: 'noterDeep.dart' • lib/note.dart:9:8 • unused_import
   info • The value of the field '_apuie2' isn't used • lib/note.dart:29:8 • unused_field
   info • The value of the field '_apuie3' isn't used • lib/note.dart:30:8 • unused_field
   info • 'child' is deprecated and shouldn't be used • lib/note.dart:329:17 • deprecated_member_use
warning • The parameter 'onPressed' is required • lib/note.dart:332:21 • missing_required_param
   info • Unused import: 'package:cloud_firestore/cloud_firestore.dart' • lib/noterDeep.dart:3:8 • unused_import
   info • Unused import: 'main.dart' • lib/noterDeep.dart:6:8 • unused_import
   info • The method '_apuyer' isn't used • lib/noterDeep.dart:69:8 • unused_element
   info • 'child' is deprecated and shouldn't be used • lib/noterDeep.dart:207:23 • deprecated_member_use
warning • The parameter 'onPressed' is required • lib/noterDeep.dart:210:27 • missing_required_param
   info • Unused import: 'graphique.dart' • lib/principale.dart:4:8 • unused_import
   info • Unused import: 'slider.dart' • lib/principale.dart:10:8 • unused_import
   info • Unused import: 'package:progress_indicators/progress_indicators.dart' • lib/principale.dart:12:8 • unused_import
   info • Unused import: 'note.dart' • lib/principale.dart:16:8 • unused_import
   info • Unused import: 'main.dart' • lib/principale.dart:19:8 • unused_import
   info • Unused import: 'login.dart' • lib/principale.dart:21:8 • unused_import
   info • The value of the field '_contact' isn't used • lib/principale.dart:70:18 • unused_field
   info • Unused import: 'scan.dart' • lib/profil.dart:7:8 • unused_import
   info • Unused import: 'note.dart' • lib/profil.dart:11:8 • unused_import
   info • Duplicate import • lib/profil.dart:15:8 • duplicate_import
   info • Unused import: 'package:page_view_indicators/circle_page_indicator.dart' • lib/profil.dart:21:8 • unused_import
   info • Unused import: 'note.dart' • lib/search.dart:5:8 • unused_import
   info • Name non-constant identifiers using lowerCamelCase • lib/slider.dart:208:39 • non_constant_identifier_names
   info • Name non-constant identifiers using lowerCamelCase • lib/slider.dart:214:10 • non_constant_identifier_names
   info • Name non-constant identifiers using lowerCamelCase • lib/slider.dart:232:11 • non_constant_identifier_names
   info • Name non-constant identifiers using lowerCamelCase • lib/slider.dart:233:11 • non_constant_identifier_names
   info • Name non-constant identifiers using lowerCamelCase • lib/slider.dart:242:11 • non_constant_identifier_names
   info • Name non-constant identifiers using lowerCamelCase • lib/slider.dart:245:11 • non_constant_identifier_names
   info • Name non-constant identifiers using lowerCamelCase • lib/slider.dart:246:11 • non_constant_identifier_names
   info • Name non-constant identifiers using lowerCamelCase • lib/slider.dart:275:39 • non_constant_identifier_names
   info • Name non-constant identifiers using lowerCamelCase • lib/slider.dart:281:10 • non_constant_identifier_names
   info • Name non-constant identifiers using lowerCamelCase • lib/slider.dart:403:39 • non_constant_identifier_names
   info • Name non-constant identifiers using lowerCamelCase • lib/slider.dart:408:10 • non_constant_identifier_names
   info • This function has a return type of 'Path', but doesn't end with a return statement • lib/slider.dart:414:3 • missing_return
   info • Name non-constant identifiers using lowerCamelCase • lib/slider.dart:612:39 • non_constant_identifier_names
   info • Name non-constant identifiers using lowerCamelCase • lib/slider.dart:617:10 • non_constant_identifier_names
   info • Name non-constant identifiers using lowerCamelCase • lib/slider.dart:797:32 • non_constant_identifier_names

56 issues found. (ran in 7.7s)

[✓] Flutter (Channel stable, v1.5.4-hotfix.2, on Mac OS X 10.14.6 18G29g, locale fr-FR)
    • Flutter version 1.5.4-hotfix.2 at /Users/evvon/flutter
    • Framework revision 7a4c33425d (6 weeks ago), 2019-04-29 11:05:24 -0700
    • Engine revision 52c7a1e849
    • Dart version 2.3.0 (build 2.3.0-dev.0.5 a1668566e5)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/evvon/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.2.1, Build version 10E1001
    • ios-deploy 1.9.4
    • CocoaPods version 1.6.1

[✓] Android Studio (version 3.4)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 35.2.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

[✓] VS Code (version 1.35.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.1.0

[✓] Connected device (2 available)
    • Redmi Note 5 • 10d6c699                             • android-arm64 • Android 8.1.0 (API 27)
    • iPhone 7     • 0F5B3A36-C545-452D-ADFE-731D14926C92 • ios           • com.apple.CoreSimulator.SimRuntime.iOS-12-2 (simulator)

• No issues found!

**Comment by DjivaCanessane** [comment]
The issue is fixed when I used batch writes in cloud function.
