### ISSUE TITLE
iOS: modify project name, and then fail to run "flutter run" command

### ISSUE THREAD

**Issue by testing2007** [flutter/flutter#34397]
I want to change the default project name "runner" to "Boxuegu", I can normal to run it by xCode, but when I use vscode IDE to execute "flutter  run " command in terminal, the output error in following. so How to change the default project "runner"? pls, thank you.

Flutter crash report; please file at https://github.com/flutter/flutter/issues.

## command

flutter run

## exception

ProcessException: ProcessException: No such file or directory
  Command: /usr/bin/xcodebuild -project /Users/apple/Documents/WorkspaceBoxueguFlutter/boxuegu/ios/Runner.xcodeproj -target Runner -showBuildSettings

```
#0      _ProcessImpl._runAndWait (dart:io/runtime/binprocess_patch.dart:489:7)
#1      _runNonInteractiveProcessSync (dart:io/runtime/binprocess_patch.dart:634:18)
#2      Process.runSync (dart:io/runtime/binprocess_patch.dart:66:12)
#3      LocalProcessManager.runSync (package:process/src/interface/local_process_manager.dart:83:20)
#4      _runWithLoggingSync (package:flutter_tools/src/base/process.dart:325:48)
#5      runCheckedSync (package:flutter_tools/src/base/process.dart:283:10)
#6      XcodeProjectInterpreter.getBuildSettings (package:flutter_tools/src/ios/xcodeproj.dart:151:24)
#7      IosProject.buildSettings (package:flutter_tools/src/project.dart:262:42)
#8      IosProject.productBundleIdentifier (package:flutter_tools/src/project.dart:248:56)
#9      new BuildableIOSApp (package:flutter_tools/src/application_package.dart:293:66)
#10     new IOSApp.fromIosProject (package:flutter_tools/src/application_package.dart:281:12)
#11     ApplicationPackageFactory.getPackageForPlatform (package:flutter_tools/src/application_package.dart:41:22)
<asynchronous suspension>
#12     FlutterDevice.runHot (package:flutter_tools/src/resident_runner.dart:288:56)
<asynchronous suspension>
#13     HotRunner.run (package:flutter_tools/src/run_hot.dart:295:39)
<asynchronous suspension>
#14     RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:405:37)
<asynchronous suspension>
#15     FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:545:18)
#16     _asyncThenWrapperHelper.<anonymous closure> (dart:async/runtime/libasync_patch.dart:77:64)
#17     _rootRunUnary (dart:async/zone.dart:1132:38)
#18     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#19     _FutureListener.handleValue (dart:async/future_impl.dart:126:18)
#20     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:639:45)
#21     Future._propagateToListeners (dart:async/future_impl.dart:668:32)
#22     Future._complete (dart:async/future_impl.dart:473:7)
#23     _SyncCompleter.complete (dart:async/future_impl.dart:51:12)
#24     _AsyncAwaitCompleter.complete (dart:async/runtime/libasync_patch.dart:28:18)
#25     _completeOnAsyncReturn (dart:async/runtime/libasync_patch.dart:294:13)
#26     RunCommand.usageValues (package:flutter_tools/src/commands/run.dart)
#27     _asyncThenWrapperHelper.<anonymous closure> (dart:async/runtime/libasync_patch.dart:77:64)
#28     _rootRunUnary (dart:async/zone.dart:1132:38)
#29     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#30     _FutureListener.handleValue (dart:async/future_impl.dart:126:18)
#31     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:639:45)
#32     Future._propagateToListeners (dart:async/future_impl.dart:668:32)
#33     Future._complete (dart:async/future_impl.dart:473:7)
#34     _SyncCompleter.complete (dart:async/future_impl.dart:51:12)
#35     _AsyncAwaitCompleter.complete.<anonymous closure> (dart:async/runtime/libasync_patch.dart:33:20)
#36     _rootRun (dart:async/zone.dart:1124:13)
#37     _CustomZone.run (dart:async/zone.dart:1021:19)
#38     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:947:23)
#39     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#40     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#41     _runPendingImmediateCallback (dart:isolate/runtime/libisolate_patch.dart:115:13)
#42     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:172:5)
```

## flutter doctor

```
[32m[✓][39m Flutter (Channel stable, v1.2.1, on Mac OS X 10.14.5 18F132, locale zh-Hans-CN)
    [32m•[39m Flutter version 1.2.1 at /Users/apple/flutter
    [32m•[39m Framework revision 8661d8aecd (4 months ago), 2019-02-14 19:19:53 -0800
    [32m•[39m Engine revision 3757390fa4
    [32m•[39m Dart version 2.1.2 (build 2.1.2-dev.0.0 0a7dcf17eb)

[32m[✓][39m Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    [32m•[39m Android SDK at /Users/apple/Library/Android/sdk
    [32m•[39m Android NDK location not configured (optional; useful for native profiling support)
    [32m•[39m Platform android-28, build-tools 28.0.3
    [32m•[39m Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    [32m•[39m Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)
    [32m•[39m All Android licenses accepted.

[32m[✓][39m iOS toolchain - develop for iOS devices (Xcode 10.2.1)
    [32m•[39m Xcode at /Applications/Xcode.app/Contents/Developer
    [32m•[39m Xcode 10.2.1, Build version 10E1001
    [32m•[39m ios-deploy 1.9.4
    [32m•[39m CocoaPods version 1.5.3

[32m[✓][39m Android Studio (version 3.3)
    [32m•[39m Android Studio at /Applications/Android Studio.app/Contents
    [32m•[39m Flutter plugin version 33.1.1
    [32m•[39m Dart plugin version 182.5215
    [32m•[39m Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)

[32m[✓][39m VS Code (version 1.35.1)
    [32m•[39m VS Code at /Applications/Visual Studio Code.app/Contents
    [32m•[39m Flutter extension version 3.1.0

[32m[✓][39m Connected device (1 available)
    [32m•[39m Zander  iPhone • b80d5d3014545382a8408aad7746f3bc637a3a1b • ios • iOS 12.2

[32m•[39m No issues found!
```

**Comment by stuartmorgan** [comment]
If you want to use a different project name, you'll need to use [Add-to-App](https://github.com/flutter/flutter/wiki/Add-Flutter-to-existing-apps); Flutter-managed projects require the project and target names used in the template.

**Comment by testing2007** [comment]
thank u, I'll try it.
