### ISSUE TITLE
gclient sync  : src/third_party/glfw (ERROR)

### ISSUE THREAD

**Issue by GuoZhiQiang** [flutter/flutter#34400]
I want to build flutter `engine` . I have flowed the steps of [Setting-up-the-Engine-development-environment](https://github.com/flutter/flutter/wiki/Setting-up-the-Engine-development-environment). When i run `gclient sync`, the errors come up:
```
WARNING: subprocess '"git" "-c" "core.deltaBaseCacheLimit=2g" "clone" "--no-checkout" "--progress" "https://fuchsia.googlesource.com/third_party/glfw" "/Users/guo/Documents/iOS/FlutterFolder/engine_qunfeng/engine/src/third_party/_gclient_glfw_TGcGRH"' in /Users/guo/Documents/iOS/FlutterFolder/engine_qunfeng/engine failed; will retry after a short nap...
WARNING: subprocess '"git" "-c" "core.deltaBaseCacheLimit=2g" "fetch" "origin"' in /Users/guo/Documents/iOS/FlutterFolder/engine_qunfeng/engine/src/third_party/dart failed; will retry after a short nap...
WARNING: subprocess '"git" "-c" "core.deltaBaseCacheLimit=2g" "fetch" "origin"' in /Users/guo/Documents/iOS/FlutterFolder/engine_qunfeng/engine/src/third_party/libwebp failed; will retry after a short nap...
WARNING: subprocess '"git" "-c" "core.deltaBaseCacheLimit=2g" "fetch" "origin"' in /Users/guo/Documents/iOS/FlutterFolder/engine_qunfeng/engine/src/third_party/pkg/when failed; will retry after a short nap...
WARNING: subprocess '"git" "-c" "core.deltaBaseCacheLimit=2g" "fetch" "origin"' in /Users/guo/Documents/iOS/FlutterFolder/engine_qunfeng/engine/src/third_party/skia failed; will retry after a short nap...
WARNING: subprocess '"git" "-c" "core.deltaBaseCacheLimit=2g" "clone" "--no-checkout" "--progress" "https://fuchsia.googlesource.com/third_party/wuffs" "/Users/guo/Documents/iOS/FlutterFolder/engine_qunfeng/engine/src/third_party/_gclient_wuffs_kRXUYW"' in /Users/guo/Documents/iOS/FlutterFolder/engine_qunfeng/engine failed; will retry after a short nap...

[0:01:26] Still working on:
[0:01:26]   src/third_party/dart
[0:01:26]   src/third_party/glfw
[0:01:26]   src/third_party/libwebp
[0:01:26]   src/third_party/pkg/when
[0:01:26]   src/third_party/skia
[0:01:26]   src/third_party/wuffs

[0:01:36] Still working on:
[0:01:36]   src/third_party/dart
[0:01:36]   src/third_party/glfw
[0:01:36]   src/third_party/libwebp
[0:01:36]   src/third_party/pkg/when
[0:01:36]   src/third_party/skia
[0:01:36]   src/third_party/wuffs

WARNING: subprocess '"git" "-c" "core.deltaBaseCacheLimit=2g" "clone" "--no-checkout" "--progress" "https://fuchsia.googlesource.com/third_party/glfw" "/Users/guo/Documents/iOS/FlutterFolder/engine_qunfeng/engine/src/third_party/_gclient_glfw_TGcGRH"' in /Users/guo/Documents/iOS/FlutterFolder/engine_qunfeng/engine failed; will retry after a short nap...
WARNING: subprocess '"git" "-c" "core.deltaBaseCacheLimit=2g" "fetch" "origin"' in /Users/guo/Documents/iOS/FlutterFolder/engine_qunfeng/engine/src/third_party/dart failed; will retry after a short nap...
WARNING: subprocess '"git" "-c" "core.deltaBaseCacheLimit=2g" "fetch" "origin"' in /Users/guo/Documents/iOS/FlutterFolder/engine_qunfeng/engine/src/third_party/libwebp failed; will retry after a short nap...
WARNING: subprocess '"git" "-c" "core.deltaBaseCacheLimit=2g" "fetch" "origin"' in /Users/guo/Documents/iOS/FlutterFolder/engine_qunfeng/engine/src/third_party/pkg/when failed; will retry after a short nap...
WARNING: subprocess '"git" "-c" "core.deltaBaseCacheLimit=2g" "fetch" "origin"' in /Users/guo/Documents/iOS/FlutterFolder/engine_qunfeng/engine/src/third_party/skia failed; will retry after a short nap...
WARNING: subprocess '"git" "-c" "core.deltaBaseCacheLimit=2g" "clone" "--no-checkout" "--progress" "https://fuchsia.googlesource.com/third_party/wuffs" "/Users/guo/Documents/iOS/FlutterFolder/engine_qunfeng/engine/src/third_party/_gclient_wuffs_kRXUYW"' in /Users/guo/Documents/iOS/FlutterFolder/engine_qunfeng/engine failed; will retry after a short nap...

[0:02:36] Still working on:
[0:02:36]   src/third_party/dart
[0:02:36]   src/third_party/glfw
[0:02:36]   src/third_party/libwebp
[0:02:36]   src/third_party/pkg/when
[0:02:36]   src/third_party/skia
[0:02:36]   src/third_party/wuffs

WARNING: subprocess '"git" "-c" "core.deltaBaseCacheLimit=2g" "clone" "--no-checkout" "--progress" "https://fuchsia.googlesource.com/third_party/glfw" "/Users/guo/Documents/iOS/FlutterFolder/engine_qunfeng/engine/src/third_party/_gclient_glfw_TGcGRH"' in /Users/guo/Documents/iOS/FlutterFolder/engine_qunfeng/engine failed; will retry after a short nap...
WARNING: subprocess '"git" "-c" "core.deltaBaseCacheLimit=2g" "fetch" "origin"' in /Users/guo/Documents/iOS/FlutterFolder/engine_qunfeng/engine/src/third_party/dart failed; will retry after a short nap...
WARNING: subprocess '"git" "-c" "core.deltaBaseCacheLimit=2g" "fetch" "origin"' in /Users/guo/Documents/iOS/FlutterFolder/engine_qunfeng/engine/src/third_party/libwebp failed; will retry after a short nap...
WARNING: subprocess '"git" "-c" "core.deltaBaseCacheLimit=2g" "fetch" "origin"' in /Users/guo/Documents/iOS/FlutterFolder/engine_qunfeng/engine/src/third_party/pkg/when failed; will retry after a short nap...
WARNING: subprocess '"git" "-c" "core.deltaBaseCacheLimit=2g" "fetch" "origin"' in /Users/guo/Documents/iOS/FlutterFolder/engine_qunfeng/engine/src/third_party/skia failed; will retry after a short nap...
WARNING: subprocess '"git" "-c" "core.deltaBaseCacheLimit=2g" "clone" "--no-checkout" "--progress" "https://fuchsia.googlesource.com/third_party/wuffs" "/Users/guo/Documents/iOS/FlutterFolder/engine_qunfeng/engine/src/third_party/_gclient_wuffs_kRXUYW"' in /Users/guo/Documents/iOS/FlutterFolder/engine_qunfeng/engine failed; will retry after a short nap...

[0:03:57] Still working on:
[0:03:57]   src/third_party/dart
[0:03:57]   src/third_party/glfw
[0:03:57]   src/third_party/libwebp
[0:03:57]   src/third_party/pkg/when
[0:03:57]   src/third_party/skia
[0:03:57]   src/third_party/wuffs

WARNING: subprocess '"git" "-c" "core.deltaBaseCacheLimit=2g" "clone" "--no-checkout" "--progress" "https://fuchsia.googlesource.com/third_party/glfw" "/Users/guo/Documents/iOS/FlutterFolder/engine_qunfeng/engine/src/third_party/_gclient_glfw_TGcGRH"' in /Users/guo/Documents/iOS/FlutterFolder/engine_qunfeng/engine failed; will retry after a short nap...
WARNING: subprocess '"git" "-c" "core.deltaBaseCacheLimit=2g" "fetch" "origin"' in /Users/guo/Documents/iOS/FlutterFolder/engine_qunfeng/engine/src/third_party/dart failed; will retry after a short nap...
WARNING: subprocess '"git" "-c" "core.deltaBaseCacheLimit=2g" "fetch" "origin"' in /Users/guo/Documents/iOS/FlutterFolder/engine_qunfeng/engine/src/third_party/libwebp failed; will retry after a short nap...
WARNING: subprocess '"git" "-c" "core.deltaBaseCacheLimit=2g" "fetch" "origin"' in /Users/guo/Documents/iOS/FlutterFolder/engine_qunfeng/engine/src/third_party/pkg/when failed; will retry after a short nap...
WARNING: subprocess '"git" "-c" "core.deltaBaseCacheLimit=2g" "fetch" "origin"' in /Users/guo/Documents/iOS/FlutterFolder/engine_qunfeng/engine/src/third_party/skia failed; will retry after a short nap...
WARNING: subprocess '"git" "-c" "core.deltaBaseCacheLimit=2g" "clone" "--no-checkout" "--progress" "https://fuchsia.googlesource.com/third_party/wuffs" "/Users/guo/Documents/iOS/FlutterFolder/engine_qunfeng/engine/src/third_party/_gclient_wuffs_kRXUYW"' in /Users/guo/Documents/iOS/FlutterFolder/engine_qunfeng/engine failed; will retry after a short nap...

[0:05:12] Still working on:
[0:05:12]   src/third_party/dart
[0:05:12]   src/third_party/glfw
[0:05:12]   src/third_party/libwebp
[0:05:12]   src/third_party/pkg/when
[0:05:12]   src/third_party/skia
[0:05:12]   src/third_party/wuffs
Syncing projects:  34% (31/91) src/third_party/wuffs   

src/third_party/glfw (ERROR)
----------------------------------------
[0:00:01] Started.
[0:00:01] 

________ running 'git -c core.deltaBaseCacheLimit=2g clone --no-checkout --progress https://fuchsia.googlesource.com/third_party/glfw /Users/guo/Documents/iOS/FlutterFolder/engine_qunfeng/engine/src/third_party/_gclient_glfw_TGcGRH' in '/Users/guo/Documents/iOS/FlutterFolder/engine_qunfeng/engine'
[0:00:01] Cloning into '/Users/guo/Documents/iOS/FlutterFolder/engine_qunfeng/engine/src/third_party/_gclient_glfw_TGcGRH'...
[0:01:17] fatal: unable to access 'https://fuchsia.googlesource.com/third_party/glfw/': Failed to connect to fuchsia.googlesource.com port 443: Operation timed out

________ running 'git -c core.deltaBaseCacheLimit=2g clone --no-checkout --progress https://fuchsia.googlesource.com/third_party/glfw /Users/guo/Documents/iOS/FlutterFolder/engine_qunfeng/engine/src/third_party/_gclient_glfw_TGcGRH' in '/Users/guo/Documents/iOS/FlutterFolder/engine_qunfeng/engine'
[0:01:17] Cloning into '/Users/guo/Documents/iOS/FlutterFolder/engine_qunfeng/engine/src/third_party/_gclient_glfw_TGcGRH'...
[0:02:33] fatal: unable to access 'https://fuchsia.googlesource.com/third_party/glfw/': Failed to connect to fuchsia.googlesource.com port 443: Operation timed out

________ running 'git -c core.deltaBaseCacheLimit=2g clone --no-checkout --progress https://fuchsia.googlesource.com/third_party/glfw /Users/guo/Documents/iOS/FlutterFolder/engine_qunfeng/engine/src/third_party/_gclient_glfw_TGcGRH' in '/Users/guo/Documents/iOS/FlutterFolder/engine_qunfeng/engine'
[0:02:34] Cloning into '/Users/guo/Documents/iOS/FlutterFolder/engine_qunfeng/engine/src/third_party/_gclient_glfw_TGcGRH'...
[0:03:50] fatal: unable to access 'https://fuchsia.googlesource.com/third_party/glfw/': Failed to connect to fuchsia.googlesource.com port 443: Operation timed out

________ running 'git -c core.deltaBaseCacheLimit=2g clone --no-checkout --progress https://fuchsia.googlesource.com/third_party/glfw /Users/guo/Documents/iOS/FlutterFolder/engine_qunfeng/engine/src/third_party/_gclient_glfw_TGcGRH' in '/Users/guo/Documents/iOS/FlutterFolder/engine_qunfeng/engine'
[0:03:52] Cloning into '/Users/guo/Documents/iOS/FlutterFolder/engine_qunfeng/engine/src/third_party/_gclient_glfw_TGcGRH'...
[0:05:08] fatal: unable to access 'https://fuchsia.googlesource.com/third_party/glfw/': Failed to connect to fuchsia.googlesource.com port 443: Operation timed out
Traceback (most recent call last):
  File "/Users/guo/Documents/iOS/depot_tools/gclient_scm.py", line 1054, in _Clone
    print_stdout=print_stdout, stdout=stdout)
  File "/Users/guo/Documents/iOS/depot_tools/gclient_scm.py", line 1378, in _Run
    gclient_utils.CheckCallAndFilterAndHeader(cmd, env=env, **kwargs)
  File "/Users/guo/Documents/iOS/depot_tools/gclient_utils.py", line 344, in CheckCallAndFilterAndHeader
    return CheckCallAndFilter(args, **kwargs)
  File "/Users/guo/Documents/iOS/depot_tools/gclient_utils.py", line 606, in CheckCallAndFilter
    rv, args, kwargs.get('cwd', None), None, None)
CalledProcessError: Command 'git -c core.deltaBaseCacheLimit=2g clone --no-checkout --progress https://fuchsia.googlesource.com/third_party/glfw /Users/guo/Documents/iOS/FlutterFolder/engine_qunfeng/engine/src/third_party/_gclient_glfw_TGcGRH' returned non-zero exit status 128 in /Users/guo/Documents/iOS/FlutterFolder/engine_qunfeng/engine
[0:05:12] _____ Conflicting directory found in /Users/guo/Documents/iOS/FlutterFolder/engine_qunfeng/engine/src/third_party/glfw. Moving to /Users/guo/Documents/iOS/FlutterFolder/engine_qunfeng/engine/_bad_scm/src/third_party/glfwLiSGtB.
----------------------------------------


Warnings:
Conflicting directory /Users/guo/Documents/iOS/FlutterFolder/engine_qunfeng/engine/src/third_party/glfw moved to /Users/guo/Documents/iOS/FlutterFolder/engine_qunfeng/engine/_bad_scm/src/third_party/glfwLiSGtB.
Conflicting directory /Users/guo/Documents/iOS/FlutterFolder/engine_qunfeng/engine/src/third_party/wuffs moved to /Users/guo/Documents/iOS/FlutterFolder/engine_qunfeng/engine/_bad_scm/src/third_party/wuffsz4ixP0.
Traceback (most recent call last):
  File "/Users/guo/Documents/iOS/depot_tools/metrics.py", line 266, in print_notice_and_exit
    yield
  File "/Users/guo/Documents/iOS/depot_tools/gclient.py", line 3127, in <module>
    sys.exit(main(sys.argv[1:]))
  File "/Users/guo/Documents/iOS/depot_tools/gclient.py", line 3113, in main
    return dispatcher.execute(OptionParser(), argv)
  File "/Users/guo/Documents/iOS/depot_tools/subcommand.py", line 252, in execute
    return command(parser, args[1:])
  File "/Users/guo/Documents/iOS/depot_tools/gclient.py", line 2692, in CMDsync
    ret = client.RunOnDeps('update', args)
  File "/Users/guo/Documents/iOS/depot_tools/gclient.py", line 1727, in RunOnDeps
    patch_refs=patch_refs, target_branches=target_branches)
  File "/Users/guo/Documents/iOS/depot_tools/gclient_utils.py", line 894, in flush
    reraise(e[0], e[1], e[2])
  File "/Users/guo/Documents/iOS/depot_tools/gclient_utils.py", line 971, in run
    self.item.run(*self.args, **self.kwargs)
  File "/Users/guo/Documents/iOS/depot_tools/gclient.py", line 902, in run
    file_list)
  File "/Users/guo/Documents/iOS/depot_tools/gclient_scm.py", line 133, in RunCommand
    return getattr(self, command)(options, args, file_list)
  File "/Users/guo/Documents/iOS/depot_tools/gclient_scm.py", line 558, in update
    self._DeleteOrMove(options.force)
  File "/Users/guo/Documents/iOS/depot_tools/gclient_scm.py", line 208, in _DeleteOrMove
    shutil.move(self.checkout_path, dest_path)
  File "/usr/local/Cellar/python@2/2.7.15/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shutil.py", line 316, in move
    copy2(src, real_dst)
  File "/usr/local/Cellar/python@2/2.7.15/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shutil.py", line 144, in copy2
    copyfile(src, dst)
  File "/usr/local/Cellar/python@2/2.7.15/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shutil.py", line 96, in copyfile
    with open(src, 'rb') as fsrc:
IOError: [Errno 2] No such file or directory: '/Users/guo/Documents/iOS/FlutterFolder/engine_qunfeng/engine/src/third_party/glfw'

```

#### flutter doctor -v
```
[✓] Flutter (Channel stable, v1.5.4-hotfix.2, on Mac OS X 10.14 18A391, locale zh-Hans-CN)
    • Flutter version 1.5.4-hotfix.2 at /Users/guo/Documents/iOS/flutter
    • Framework revision 7a4c33425d (6 weeks ago), 2019-04-29 11:05:24 -0700
    • Engine revision 52c7a1e849
    • Dart version 2.3.0 (build 2.3.0-dev.0.5 a1668566e5)

[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/setup/#android-setup for detailed instructions).
      If the Android SDK has been installed to a custom location, set ANDROID_HOME to that location.
      You may also want to add it to your PATH environment variable.


[!] iOS toolchain - develop for iOS devices (Xcode 10.1)
    • Xcode at /Applications/Xcode10.app/Contents/Developer
    • Xcode 10.1, Build version 10B61
    ✗ Verify that all connected devices have been paired with this computer in Xcode.
      If all devices have been paired, libimobiledevice and ideviceinstaller may require updating.
      To update with Brew, run:
        brew update
        brew uninstall --ignore-dependencies libimobiledevice
        brew uninstall --ignore-dependencies usbmuxd
        brew install --HEAD usbmuxd
        brew unlink usbmuxd
        brew link usbmuxd
        brew install --HEAD libimobiledevice
        brew install ideviceinstaller
    • ios-deploy 1.9.4
    • CocoaPods version 1.5.3

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/setup/#android-setup for detailed instructions).

[✓] VS Code (version 1.35.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.1.0

[✓] Connected device (1 available)
    • iPhone 6 • 59AD1AC6-4189-4500-85A2-11C07B4E4C47 • ios • iOS 9.3 (simulator)
```

**Comment by stuartmorgan** [comment]
This looks like a connectivity issue; have you retried?

**Comment by GuoZhiQiang** [comment]
Finally , I change `export https_proxy="https://127.0.0.1:8123/` into `export https_proxy="http://localhost:8123/`. It works !

**Comment by GuoZhiQiang** [comment]
@stuartmorgan  It's the error of `https`.

**Comment by stuartmorgan** [comment]
If you are proxying downloads, and the proxy isn't working correctly, that's beyond the control of the Flutter project; given that, closing.

**Comment by GuoZhiQiang** [comment]
Well ,not every developer in the world can download resources form google's service referred by `Flutter` project. So i need to use proxy. Anyway thanks for your help.
