### ISSUE TITLE
android.arch.lifecycle.DefaultLifecycleObserver classloading crash

### ISSUE THREAD

**Issue by xster** [flutter/flutter#34401]
I've been struggling with this one for a bit so socializing a bit to get some help. Repro's at https://github.com/xster/flutter-test/tree/master/t130_leaf_flutter_android_support

During the build, I'm getting

```
Task :app:preColdswapDebug
AGPBI: {"kind":"warning","text":"Interface `android.arch.lifecycle.DefaultLifecycleObserver` not found. It\u0027s needed to make sure desugaring of `io.flutter.embedding.engine.FlutterEngineAndroidLifecycle$1` is correct. Desugaring will assume that this interface has no default method.","sources":[{"file":"/Users/xster/development/flutter/bin/cache/artifacts/engine/android-arm64/flutter.jar"}],"tool":"D8"}
```

When I'm running, it crashes with

```
2019-06-13 03:00:24.472 5924-5924/com.example.t130_leaf_flutter_android_support E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.example.t130_leaf_flutter_android_support, PID: 5924
    java.lang.NoClassDefFoundError: Failed resolution of: Landroid/arch/lifecycle/DefaultLifecycleObserver;
        at io.flutter.embedding.engine.FlutterEngine.<init>(FlutterEngine.java:137)
        at com.example.t130_leaf_flutter_android_support.MyApp$flutterEngine2$2.invoke(MyApp.kt:36)
        at com.example.t130_leaf_flutter_android_support.MyApp$flutterEngine2$2.invoke(MyApp.kt:10)
        at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
        at com.example.t130_leaf_flutter_android_support.MyApp.getFlutterEngine2(Unknown Source:25)
        at com.example.t130_leaf_flutter_android_support.MainActivity.onCreate(MainActivity.kt:46)
        at android.app.Activity.performCreate(Activity.java:7458)
        at android.app.Activity.performCreate(Activity.java:7448)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1286)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3382)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3587)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:86)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2185)
        at android.os.Handler.dispatchMessage(Handler.java:112)
        at android.os.Looper.loop(Looper.java:216)
        at android.app.ActivityThread.main(ActivityThread.java:7593)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:987)
2019-06-13 03:00:24.473 5924-5924/com.example.t130_leaf_flutter_android_support E/AndroidRuntime: Caused by: java.lang.ClassNotFoundException: Didn't find class "android.arch.lifecycle.DefaultLifecycleObserver" on path: DexPathList[[zip file "/data/app/com.example.t130_leaf_flutter_android_support-BgpzPndChTSSOQlG8zHIXg==/base.apk", zip file "/data/app/com.example.t130_leaf_flutter_android_support-BgpzPndChTSSOQlG8zHIXg==/split_lib_dependencies_apk.apk", zip file "/data/app/com.example.t130_leaf_flutter_android_support-BgpzPndChTSSOQlG8zHIXg==/split_lib_resources_apk.apk", zip file "/data/app/com.example.t130_leaf_flutter_android_support-BgpzPndChTSSOQlG8zHIXg==/split_lib_slice_0_apk.apk", zip file "/data/app/com.example.t130_leaf_flutter_android_support-BgpzPndChTSSOQlG8zHIXg==/split_lib_slice_1_apk.apk", zip file "/data/app/com.example.t130_leaf_flutter_android_support-BgpzPndChTSSOQlG8zHIXg==/split_lib_slice_2_apk.apk", zip file "/data/app/com.example.t130_leaf_flutter_android_support-BgpzPndChTSSOQlG8zHIXg==/split_lib_slice_3_apk.apk", zip file "/data/app/com.example.t130_leaf_flutter_android_support-BgpzPndChTSSOQlG8zHIXg==/split_lib_slice_4_apk.apk", zip file "/data/app/com.example.t130_leaf_flutter_android_support-BgpzPndChTSSOQlG8zHIXg==/split_lib_slice_5_apk.apk", zip file "/data/app/com.example.t130_leaf_flutter_android_support-BgpzPndChTSSOQlG8zHIXg==/split_lib_slice_6_apk.apk", zip file "/data/app/com.example.t130_leaf_flutter_android_support-BgpzPndChTSSOQlG8zHIXg==/split_lib_slice_7_apk.apk", zip file "/data/app/com.example.t130_leaf_flutter_android_support-BgpzPndChTSSOQlG8zHIXg==/split_lib_slice_8_apk.apk", zip file "/data/app/com.example.t130_leaf_flutter_android_support-BgpzPndChTSSOQlG8zHIXg==/split_lib_slice_9_apk.apk"],nativeLibraryDirectories=[/data/app/com.example.t130_leaf_flutter_android_support-BgpzPndChTSSOQlG8zHIXg==/lib/arm64, /data/app/com.example.t130_leaf_flutter_android_support-BgpzPndChTSSOQlG8zHIXg==/base.apk!/lib/arm64-v8a, /data/app/com.example.t130_leaf_flutter_android_support-BgpzPndChTSSOQlG8zHIXg==/split_lib_dependencies_apk.apk!/lib/arm64-v8a, /data/app/com.example.t130_leaf_flutter_android_support-BgpzPndChTSSOQlG8zHIXg==/split_lib_resources_apk.apk!/lib/arm64-v8a, /data/app/com.example.t130_leaf_flutter_android_support-BgpzPndChTSSOQlG8zHIXg==/split_lib_slice_0_apk.apk!/lib/arm64-v8a, /data/app/com.example.t130_leaf_flutter_android_support-BgpzPndChTSSOQlG8zHIXg==/split_lib_slice_1_apk.apk!/lib/arm64-v8a, /data/app/com.example.t130_leaf_flutter_android_support-BgpzPndChTSSOQlG8zHIXg==/split_lib_slice_2_apk.apk!/lib/arm64-v8a, /data/app/com.example.t130_leaf_flutter_android_support-BgpzPndChTSSOQlG8zHIXg==/split_lib_slice_3_apk.apk!/lib/arm64-v8a, /data/app/com.example.t130_leaf_flutter_android_support-BgpzPndChTSSOQlG8zHIXg==/split_lib_slice_4_apk.apk!/lib/arm64-v8a, /data/app/com.example.t130_leaf_flutter_android_support-BgpzPndChTSSOQlG8zHIXg==/split_lib_slice_5_apk.apk!/lib/arm64-v8a, /data/app/com.example.t130_leaf_flutter_android_support-BgpzPndChTSSOQlG8zHIXg==/split_lib_slice_6_apk.apk!/lib/arm64-v8a, /data/app/com.example.t130_leaf_flutter_android_support-BgpzPndChTSSOQlG8zHIXg==/split_lib_slice_7_apk.apk!/lib/arm64-v8a, /data/app/com.example.t130_leaf_flutter_android_support-BgpzPndChTSSOQlG8zHIXg==/split_lib_slice_8_apk.apk!/lib/arm64-v8a, /data/app/com.example.t130_leaf_flutter_android_support-BgpzPndChTSSOQlG8zHIXg==/split_lib_slice_9_apk.apk!/lib/arm64-v8a, /system/lib64, /product/lib64]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:134)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        	... 21 more
    	Suppressed: java.io.IOException: No original dex files found for dex location /data/app/com.example.t130_leaf_flutter_android_support-BgpzPndChTSSOQlG8zHIXg==/split_lib_resources_apk.apk
        at dalvik.system.DexFile.openDexFileNative(Native Method)
        at dalvik.system.DexFile.openDexFile(DexFile.java:354)
        at dalvik.system.DexFile.<init>(DexFile.java:101)
2019-06-13 03:00:24.473 5924-5924/com.example.t130_leaf_flutter_android_support E/AndroidRuntime:     at dalvik.system.DexFile.<init>(DexFile.java:75)
        at dalvik.system.DexPathList.loadDexFile(DexPathList.java:394)
        at dalvik.system.DexPathList.makeDexElements(DexPathList.java:354)
        at dalvik.system.DexPathList.<init>(DexPathList.java:164)
        at dalvik.system.BaseDexClassLoader.<init>(BaseDexClassLoader.java:74)
        at dalvik.system.BaseDexClassLoader.<init>(BaseDexClassLoader.java:65)
        at dalvik.system.PathClassLoader.<init>(PathClassLoader.java:64)
        at com.android.internal.os.ClassLoaderFactory.createClassLoader(ClassLoaderFactory.java:73)
        at com.android.internal.os.ClassLoaderFactory.createClassLoader(ClassLoaderFactory.java:88)
        at android.app.ApplicationLoaders.getClassLoader(ApplicationLoaders.java:84)
        at android.app.ApplicationLoaders.getClassLoader(ApplicationLoaders.java:40)
        at android.app.LoadedApk.createOrUpdateClassLoaderLocked(LoadedApk.java:801)
        at android.app.LoadedApk.getClassLoader(LoadedApk.java:884)
        at android.app.LoadedApk.getResources(LoadedApk.java:1135)
        at android.app.ContextImpl.createAppContext(ContextImpl.java:2623)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6568)
        at android.app.ActivityThread.access$2000(ActivityThread.java:273)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2011)
        		... 6 more
```

Even looking at the engine jar with attached source shows

<img width="724" alt="Screen Shot 2019-06-13 at 3 01 33 AM" src="https://user-images.githubusercontent.com/156888/59423743-99167d00-8d87-11e9-805c-29603cf606bf.png">

for DefaultLifecycleObserver. The other lifecycle stuff comes from

<img width="504" alt="Screen Shot 2019-06-13 at 3 02 23 AM" src="https://user-images.githubusercontent.com/156888/59423786-b0556a80-8d87-11e9-994d-ce97a35a4f84.png">

Did I hook something incorrectly?

cc @matthew-carroll

**Comment by matthew-carroll** [comment]
For that class, you need to include the java8 extension of the lifecycle lib.

https://mvnrepository.com/artifact/android.arch.lifecycle/common-java8/1.1.0

**Comment by xster** [comment]
yup, that did it. I wonder why I didn't run into trouble before with it and does that need to be in our module template's build.gradle.tmpl?

**Comment by xster** [comment]
For anyone finding this bug because they ran into this issue:

We're not shipping one of the classes we end up instantiating when any engine consumers (including plugins) try to get a lifecycle observer on Android components. 

For now, you need to add

`implementation 'android.arch.lifecycle:common-java8:1.1.0'`

to the `dependencies { }` section of your app Android's build.gradle.

Don't add it to your Flutter module project's `.android` wrapper project's build.gradle since until we decide otherwise in https://github.com/flutter/flutter/issues/32989, that build.gradle is ephemeral and auto-regenerate on `flutter packages get`.

**Comment by blasten** [comment]
This only happens when ProGuard is enabled. Alternatively, `adding -ignorewarnings to `proguard-rules.pro` also fixes that issue.

See https://github.com/flutter/flutter/issues/31922#issuecomment-503754500 . 

@matthew-carroll I think we should update the [public docs](https://flutter.dev/docs/deployment/android#enabling-proguard), wdyt?

**Comment by blasten** [comment]
cc @sfshaza2

**Comment by blasten** [comment]
This shouldn't be an issue anymore.
