### ISSUE TITLE
NullPointerException: Attempt to read from field 'int io.flutter.view.AccessibilityBridge$SemanticsNode.platformViewId

### ISSUE THREAD

**Issue by davidmartos96** [flutter/flutter#34415]
## Steps to Reproduce

Activate **TalkBack** on Android.

1. Tap on one of the bottom navigation tabs in the example provided (just focus with TalkBack).
2. Drag from the selected tab towards the bottom Android actions panel (example image).

![image](https://user-images.githubusercontent.com/22084723/59447651-e0daea00-8e03-11e9-8b94-3471891a49e9.png)

3. Crash occurs

The device in which I tested it is a Moto G5 Plus.

## Logs

```
E/AndroidRuntime( 5454): java.lang.NullPointerException: Attempt to read from field 'int io.flutter.view.AccessibilityBridge$SemanticsNode.platformViewId' on a null object reference
E/AndroidRuntime( 5454): 	at io.flutter.view.AccessibilityBridge$SemanticsNode.access$1400(AccessibilityBridge.java:1710)
E/AndroidRuntime( 5454): 	at io.flutter.view.AccessibilityBridge.onAccessibilityHoverEvent(AccessibilityBridge.java:1129)
E/AndroidRuntime( 5454): 	at io.flutter.view.FlutterView.onHoverEvent(FlutterView.java:462)
E/AndroidRuntime( 5454): 	at android.view.View.dispatchHoverEvent(View.java:12698)
E/AndroidRuntime( 5454): 	at android.view.View.dispatchGenericMotionEvent(View.java:12615)
E/AndroidRuntime( 5454): 	at android.view.ViewGroup.dispatchTransformedGenericPointerEvent(ViewGroup.java:2515)
E/AndroidRuntime( 5454): 	at android.view.ViewGroup.dispatchHoverEvent(ViewGroup.java:2148)
E/AndroidRuntime( 5454): 	at android.view.View.dispatchGenericMotionEvent(View.java:12615)
E/AndroidRuntime( 5454): 	at android.view.ViewGroup.dispatchTransformedGenericPointerEvent(ViewGroup.java:2515)
E/AndroidRuntime( 5454): 	at android.view.ViewGroup.dispatchHoverEvent(ViewGroup.java:2148)
E/AndroidRuntime( 5454): 	at android.view.View.dispatchGenericMotionEvent(View.java:12615)
E/AndroidRuntime( 5454): 	at android.view.ViewGroup.dispatchTransformedGenericPointerEvent(ViewGroup.java:2515)
E/AndroidRuntime( 5454): 	at android.view.ViewGroup.dispatchHoverEvent(ViewGroup.java:2148)
E/AndroidRuntime( 5454): 	at android.view.View.dispatchGenericMotionEvent(View.java:12615)
E/AndroidRuntime( 5454): 	at com.android.internal.policy.DecorView.superDispatchGenericMotionEvent(DecorView.java:448)
E/AndroidRuntime( 5454): 	at com.android.internal.policy.PhoneWindow.superDispatchGenericMotionEvent(PhoneWindow.java:1840)
E/AndroidRuntime( 5454): 	at android.app.Activity.dispatchGenericMotionEvent(Activity.java:3437)
E/AndroidRuntime( 5454): 	at com.android.internal.policy.DecorView.dispatchGenericMotionEvent(DecorView.java:412)
E/AndroidRuntime( 5454): 	at android.view.View.dispatchPointerEvent(View.java:12756)
E/AndroidRuntime( 5454): 	at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:5117)
E/AndroidRuntime( 5454): 	at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4916)
E/AndroidRuntime( 5454): 	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4433)
E/AndroidRuntime( 5454): 	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4486)
E/AndroidRuntime( 5454): 	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4452)
E/AndroidRuntime( 5454): 	at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:4592)
E/AndroidRuntime( 5454): 	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4460)
E/AndroidRuntime( 5454): 	at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:4649)
E/AndroidRuntime( 5454): 	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4433)
E/AndroidRuntime( 5454): 	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4486)
E/AndroidRuntime( 5454): 	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4452)
E/AndroidRuntime( 5454): 	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4460)
E/AndroidRuntime( 5454): 	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4433)
E/AndroidRuntime( 5454): 	at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:7103)
E/AndroidRuntime( 5454): 	at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:7072)
E/AndroidRuntime( 5454): 	at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:7033)
E/AndroidRuntime( 5454): 	at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:7206)
E/AndroidRuntime( 5454): 	at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:186)
E/AndroidRuntime( 5454): 	at android.view.InputEventReceiver.nativeConsumeBatchedInputEvents(Native Method)
E/AndroidRuntime( 5454): 	at android.view.InputEventReceiver.consumeBatchedInputEvents(InputEventReceiver.java:177)
E/AndroidRuntime( 5454): 	at android.view.ViewRootImpl.doConsumeBatchedInput(ViewRootImpl.java:7177)
E/AndroidRuntime( 5454): 	at android.view.ViewRootImpl$ConsumeBatchedInputRunnable.run(ViewRootImpl.java:7229)
E/AndroidRuntime( 5454): 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:949)
E/AndroidRuntime( 5454): 	at android.view.Choreographer.doCallbacks(Choreographer.java:761)
E/AndroidRuntime( 5454): 	at android.view.Choreographer.doFrame(Choreographer.java:690)
E/AndroidRuntime( 5454): 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:935)
E/AndroidRuntime( 5454): 	at android.os.Handler.handleCallback(Handler.java:873)
E/AndroidRuntime( 5454): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/AndroidRuntime( 5454): 	at android.os.Looper.loop(Looper.java:193)
E/AndroidRuntime( 5454): 	at android.app.ActivityThread.main(ActivityThread.java:6718)
E/AndroidRuntime( 5454): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime( 5454): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
E/AndroidRuntime( 5454): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
I/Process ( 5454): Sending signal. PID: 5454 SIG: 9
```

```
Analyzing platformviewid_null...                                        
No issues found! (ran in 1.1s)
```

```
[✓] Flutter (Channel unknown, v1.9.1+hotfix.2, on Linux, locale en_US.UTF-8)
    • Flutter version 1.9.1+hotfix.2 at /home/david/opt/flutter
    • Framework revision 2d2a1ffec9 (4 weeks ago), 2019-09-06 18:39:49 -0700
    • Engine revision b863200c37
    • Dart version 2.5.0

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /home/david/Android/Sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 28.0.3
    • Java binary at: /home/david/opt/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Android Studio (version 3.5)
    • Android Studio at /home/david/opt/android-studio
    • Flutter plugin version 39.0.3
    • Dart plugin version 191.8423
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
```

## Code to reproduce:

```dart
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: MyHomePage(),
    );
  }
}

class MyHomePage extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text("Crash TalkBack"),
      ),
      bottomNavigationBar: BottomNavigationBar(
        type: BottomNavigationBarType.fixed,
        currentIndex: 0,
        items: [
          BottomNavigationBarItem(
            title: Text(
              "Tab 1",
            ),
            icon: Icon(Icons.home),
          ),
          BottomNavigationBarItem(
            title: Text(
              "Tab 2",
            ),
            icon: Icon(Icons.home),
          ),
          BottomNavigationBarItem(
            title: Text(
              "Tab 3",
            ),
            icon: Icon(Icons.home),
          ),
        ],
        onTap: (_index) {},
      ),
    );
  }
}
```

**Comment by nanox77** [comment]
I'm using Flutter version **1.7.8+hotfix.4** and I have same issue when put in background and resume app.

**Comment by janmoppel** [comment]
Hello @davidmartos96 and @nanox77 !

Did you manage to solve the issue? Does the problem still persist in the latest stable version?

**Comment by davidmartos96** [comment]
@janmoppel I just tried the provided sample code in 1.9.1+hotfix.2 and it crashes exactly the same way. I updated the crash stack trace for the current Flutter stable version.

**Comment by confiks** [comment]
@janmoppel We can reproduce the issue as well. When TalkBack is enabled, the app crashes on certain taps with exactly the stacktrace posted in this thread. 

The crash seems to occur [here](https://github.com/flutter/engine/blob/e3e2a38/shell/platform/android/io/flutter/view/AccessibilityBridge.java#L1155), where `getRootSemanticsNode().hitTest` apparently returns `null`.

This seems to be caused by `hitTest` on the root `SemanticsNode` [here](https://github.com/flutter/engine/blob/e3e2a38/shell/platform/android/io/flutter/view/AccessibilityBridge.java#L2021) apparently not matching the event coordinates.

**Comment by snaeji** [comment]
We are also having this issue and it's critical for our blind users. Hope this gets fixed soon.

**Comment by singun-lxd** [comment]
Same issue with Flutter v1.12.13+hotfix8

**Comment by sunndog** [comment]
Same issue with Flutter 1.12.13+hotfix.9.  Tested across stable, beta, & dev channels and the bug still exists.  Is there any other information you need?  It's super simple to recreate with a new app...

**Comment by sunndog** [comment]
@eseidel @dnfield This crashing issue is a show stopper for us.  Is there any information I can give you to encourage some dev attention?  thanks...

**Comment by VladyslavBondarenko** [comment]
I can reproduce it with any app.
1. Tap on one of the bottom navigation tabs (just focus with TalkBack).
2. Swipe from the very top of the screen to the bottom.

https://github.com/flutter/flutter/issues/48573#issuecomment-615933925

**Comment by xster** [comment]
@GaryQian to take a look

**Comment by GaryQian** [comment]
https://github.com/flutter/engine/pull/17833 should fix this.

**Comment by sunndog** [comment]
@xster @GaryQian Thanks for the quick follow up.
