### ISSUE TITLE
Crash when clicking Debug Paint in Dart DevTools

### ISSUE THREAD

**Issue by aaronraimist** [flutter/flutter#34453]
## Steps to Reproduce

1. Build https://git.pattle.im/pattle/app on iOS
2. Open Dart DevTools
3. Click Debug Paint

## Logs

```
flutter: ══╡ EXCEPTION CAUGHT BY RENDERING LIBRARY ╞═════════════════════════════════════════════════════════
flutter: The following assertion was thrown during paint():
flutter: 'package:flutter/src/rendering/sliver_padding.dart': Failed assertion: line 334 pos 18:
flutter: 'innerRect.bottom <= outerRect.bottom': is not true.
flutter:
flutter: Either the assertion indicates an error in the framework itself, or we should provide substantially
flutter: more information in this error message to help you determine and fix the underlying cause.
flutter: In either case, please report this assertion by filing a bug on GitHub:
flutter:   https://github.com/flutter/flutter/issues/new?template=BUG.md
flutter:
flutter: When the exception was thrown, this was the stack:
flutter: #2      RenderSliverPadding.debugPaint.<anonymous closure> (package:flutter/src/rendering/sliver_padding.dart:334:18)
flutter: #3      RenderSliverPadding.debugPaint (package:flutter/src/rendering/sliver_padding.dart:339:6)
flutter: #4      RenderObject._paintWithContext.<anonymous closure> (package:flutter/src/rendering/object.dart:2111:7)
flutter: #5      RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2115:6)
flutter: #6      PaintingContext.paintChild (package:flutter/src/rendering/object.dart:173:13)
flutter: #7      RenderViewportBase._paintContents (package:flutter/src/rendering/viewport.dart:528:17)
flutter: #8      PaintingContext.pushLayer (package:flutter/src/rendering/object.dart:370:12)
flutter: #9      PaintingContext.pushClipRect (package:flutter/src/rendering/object.dart:394:7)
flutter: #10     RenderViewportBase.paint (package:flutter/src/rendering/viewport.dart:519:15)
flutter: #11     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2104:7)
flutter: #12     PaintingContext._repaintCompositedChild (package:flutter/src/rendering/object.dart:128:11)
flutter: #13     PaintingContext.repaintCompositedChild (package:flutter/src/rendering/object.dart:96:5)
flutter: #14     PipelineOwner.flushPaint (package:flutter/src/rendering/object.dart:859:29)
flutter: #15     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding.drawFrame (package:flutter/src/rendering/binding.dart:349:19)
flutter: #16     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding&WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:701:13)
flutter: #17     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:286:5)
flutter: #18     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1012:15)
Lost connection to device.
flutter: #19     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:952:9)
flutter: #20     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:864:5)
flutter: #24     _invoke (dart:ui/hooks.dart:219:10)
flutter: #25     _drawFrame (dart:ui/hooks.dart:178:3)
flutter: (elided 5 frames from class _AssertionError and package dart:async)
flutter:
flutter: The following RenderObject was being processed when the exception was fired:
flutter:   RenderViewport#85677
flutter:   creator: Viewport ← IgnorePointer-[GlobalKey#4e03f] ← Semantics ← Listener ← _GestureSemantics ←
flutter:   RawGestureDetector-[LabeledGlobalKey<RawGestureDetectorState>#e7113] ← Listener ← _ScrollableScope
flutter:   ← _ScrollSemantics-[GlobalKey#e1e51] ← Scrollable ← ListView ← StreamBuilder<List<ChatItem>> ← ⋯
flutter:   parentData: <none> (can use size)
flutter:   constraints: BoxConstraints(0.0<=w<=375.0, h=648.0)
flutter:   layer: OffsetLayer#446ae
flutter:   size: Size(375.0, 648.0)
flutter:   axisDirection: up
flutter:   crossAxisDirection: right
flutter:   offset: ScrollPositionWithSingleContext#2cd31(offset: 0.0, range: 0.0..161.0, viewport: 648.0,
flutter:   ScrollableState, AlwaysScrollableScrollPhysics -> BouncingScrollPhysics, IdleScrollActivity#32053,
flutter:   ScrollDirection.idle)
flutter:   anchor: 0.0
```

There are not any major issues.

```
Analyzing app...                                                        

   info • The type of the function literal can't be inferred because the literal has a block as its body • lib/src/app.dart:45:14 •
          strong_mode_top_level_function_literal_block
   info • Unused import: 'package:pattle/src/app.dart' • lib/src/sentry.dart:22:8 • unused_import
   info • Unused import: 'package:pattle/src/ui/main/overview/models/chat_overview.dart' • lib/src/ui/initial/initial_bloc.dart:19:8 • unused_import
   info • The value of the local variable 'sentState' isn't used • lib/src/ui/main/chat/chat_bloc.dart:131:22 • unused_local_variable
   info • Unused import: 'dart:async' • lib/src/ui/main/chat/chat_page.dart:17:8 • unused_import
   info • Unused import: 'dart:async' • lib/src/ui/main/chat/image/image_page.dart:17:8 • unused_import
   info • This class (or a class which this class inherits from) is marked as '@immutable', but one or more of its instance fields are not final:
          MessageBubble._isStartOfGroup, MessageBubble._isEndOfGroup • lib/src/ui/main/chat/widgets/image_bubble.dart:27:7 • must_be_immutable
   info • Unused import: 'package:matrix_sdk/matrix_sdk.dart' • lib/src/ui/main/chat/widgets/item.dart:19:8 • unused_import
   info • Unused import: 'package:pattle/src/ui/resources/theme.dart' • lib/src/ui/main/chat/widgets/item.dart:21:8 • unused_import
   info • Unused import: 'package:pattle/src/ui/util/date_format.dart' • lib/src/ui/main/chat/widgets/item.dart:22:8 • unused_import
   info • Unused import: 'package:pattle/src/ui/util/user.dart' • lib/src/ui/main/chat/widgets/item.dart:23:8 • unused_import
   info • Unused import: 'image_bubble.dart' • lib/src/ui/main/chat/widgets/item.dart:25:8 • unused_import
   info • Unused import: 'state/member_bubble.dart' • lib/src/ui/main/chat/widgets/item.dart:26:8 • unused_import
   info • Unused import: 'text_bubble.dart' • lib/src/ui/main/chat/widgets/item.dart:27:8 • unused_import
   info • This class (or a class which this class inherits from) is marked as '@immutable', but one or more of its instance fields are not final:
          MessageBubble._isStartOfGroup, MessageBubble._isEndOfGroup • lib/src/ui/main/chat/widgets/message_bubble.dart:31:16 • must_be_immutable
   info • Unused import: 'dart:ui' • lib/src/ui/main/chat/widgets/redacted_bubble.dart:18:8 • unused_import
   info • This class (or a class which this class inherits from) is marked as '@immutable', but one or more of its instance fields are not final:
          MessageBubble._isStartOfGroup, MessageBubble._isEndOfGroup • lib/src/ui/main/chat/widgets/redacted_bubble.dart:30:7 • must_be_immutable
   info • Unused import: 'package:pattle/src/ui/resources/localizations.dart' • lib/src/ui/main/chat/widgets/state/member_bubble.dart:23:8 • unused_import
   info • Unused import: 'package:pattle/src/ui/util/user.dart' • lib/src/ui/main/chat/widgets/state/member_bubble.dart:24:8 • unused_import
   info • Unused import: '../bubble.dart' • lib/src/ui/main/chat/widgets/state/member_bubble.dart:26:8 • unused_import
   info • Unused import: 'dart:ui' • lib/src/ui/main/chat/widgets/text_bubble.dart:18:8 • unused_import
   info • This class (or a class which this class inherits from) is marked as '@immutable', but one or more of its instance fields are not final:
          MessageBubble._isStartOfGroup, MessageBubble._isEndOfGroup • lib/src/ui/main/chat/widgets/text_bubble.dart:32:7 • must_be_immutable
   info • Unused import: 'package:meta/meta.dart' • lib/src/ui/main/models/chat_item.dart:19:8 • unused_import
   info • Unused import: 'dart:async' • lib/src/ui/main/overview/chat_overview_page.dart:17:8 • unused_import
   info • Unused import: 'package:matrix_sdk/matrix_sdk.dart' • lib/src/ui/main/overview/create/group/create_group_details_page.dart:18:8 • unused_import
   info • Unused import: 'package:pattle/src/ui/util/matrix_image.dart' • lib/src/ui/main/overview/create/group/create_group_details_page.dart:23:8 •
          unused_import
   info • Unused import: 'package:pattle/src/ui/util/matrix_image.dart' • lib/src/ui/main/overview/create/group/create_group_members_page.dart:23:8 •
          unused_import
   info • Unused import: 'dart:typed_data' • lib/src/ui/main/overview/models/chat_overview.dart:18:8 • unused_import
   info • Unused import: 'package:pattle/src/ui/util/user.dart' • lib/src/ui/main/overview/widgets/member_subtitle.dart:21:8 • unused_import
   info • Unused import: 'package:meta/meta.dart' • lib/src/ui/util/user.dart:21:8 • unused_import
   info • Unused import: 'package:flutter/material.dart' • test/widget_test.dart:1:8 • unused_import
   info • Unused import: 'package:flutter_test/flutter_test.dart' • test/widget_test.dart:2:8 • unused_import
   info • Unused import: 'package:pattle/main.dart' • test/widget_test.dart:4:8 • unused_import
```

```
[✓] Flutter (Channel stable, v1.5.4-hotfix.2, on Mac OS X 10.14.5 18F132, locale en-US)
    • Flutter version 1.5.4-hotfix.2 at /Users/aaronraimist/Development/Flutter/flutter
    • Framework revision 7a4c33425d (6 недель назад), 2019-04-29 11:05:24 -0700
    • Engine revision 52c7a1e849
    • Dart version 2.3.0 (build 2.3.0-dev.0.5 a1668566e5)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/aaronraimist/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 11.0)
    • Xcode at /Applications/Xcode-beta.app/Contents/Developer
    • Xcode 11.0, Build version 11M336w
    • ios-deploy 1.9.4
    • CocoaPods version 1.7.1

[✓] Android Studio (version 3.4)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 35.3.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

[!] VS Code (version 1.34.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    ✗ Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (1 available)
    • xxxxx

! Doctor found issues in 1 category.
```

I'm not using VS Code for Flutter.

**Comment by miquelbeltran** [comment]
I have the same issue, when using Flutter Inspector as soon as I click on the button to draw the layout on screen:

```
flutter: ══╡ EXCEPTION CAUGHT BY RENDERING LIBRARY ╞═════════════════════════════════════════════════════════
flutter: The following assertion was thrown during paint():
flutter: 'package:flutter/src/rendering/sliver_padding.dart': Failed assertion: line 342 pos 18:
flutter: 'innerRect.bottom <= outerRect.bottom': is not true.
flutter:
flutter: Either the assertion indicates an error in the framework itself, or we should provide substantially
flutter: more information in this error message to help you determine and fix the underlying cause.
flutter: In either case, please report this assertion by filing a bug on GitHub:
flutter:   https://github.com/flutter/flutter/issues/new?template=BUG.md
flutter:
flutter: When the exception was thrown, this was the stack:
flutter: #2      RenderSliverPadding.debugPaint.<anonymous closure> (package:flutter/src/rendering/sliver_padding.dart:342:18)
flutter: #3      RenderSliverPadding.debugPaint (package:flutter/src/rendering/sliver_padding.dart:347:6)
flutter: #4      RenderObject._paintWithContext.<anonymous closure> (package:flutter/src/rendering/object.dart:2096:7)
flutter: #5      RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2100:6)
flutter: #6      PaintingContext.paintChild (package:flutter/src/rendering/object.dart:172:13)
flutter: #7      RenderViewportBase._paintContents (package:flutter/src/rendering/viewport.dart:527:17)
flutter: #8      PaintingContext.pushLayer (package:flutter/src/rendering/object.dart:369:12)
flutter: #9      PaintingContext.pushClipRect (package:flutter/src/rendering/object.dart:393:7)
flutter: #10     RenderViewportBase.paint (package:flutter/src/rendering/viewport.dart:518:15)
flutter: #11     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2089:7)
flutter: #12     PaintingContext._repaintCompositedChild (package:flutter/src/rendering/object.dart:127:11)
flutter: #13     PaintingContext.repaintCompositedChild (package:flutter/src/rendering/object.dart:95:5)
flutter: #14     PipelineOwner.flushPaint (package:flutter/src/rendering/object.dart:858:29)
flutter: #15     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding.drawFrame (package:flutter/src/rendering/binding.dart:348:19)
flutter: #16     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding&WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:701:13)
flutter: #17     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:285:5)
flutter: #18     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1016:15)
flutter: #19     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:958:9)
flutter: #20     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:874:5)
flutter: #24     _invoke (dart:ui/hooks.dart:236:10)
flutter: #25     _drawFrame (dart:ui/hooks.dart:194:3)
flutter: (elided 5 frames from class _AssertionError and package dart:async)
flutter:
flutter: The following RenderObject was being processed when the exception was fired: RenderViewport#4a269:
flutter:   needs compositing
flutter:   creator: Viewport ← IgnorePointer-[GlobalKey#1afe5] ← Semantics ← Listener ← _GestureSemantics ←
flutter:     RawGestureDetector-[LabeledGlobalKey<RawGestureDetectorState>#ac984] ← Listener ← _ScrollableScope
flutter:     ← _ScrollSemantics-[GlobalKey#84661] ← Scrollable ← ListView ←
flutter:     StreamBuilder<MessagesListViewModel> ← ⋯
flutter:   parentData: <none> (can use size)
flutter:   constraints: BoxConstraints(0.0<=w<=375.0, 0.0<=h<=618.0)
flutter:   layer: OffsetLayer#900f5
flutter:   size: Size(375.0, 618.0)
flutter:   axisDirection: up
flutter:   crossAxisDirection: right
flutter:   offset: ScrollPositionWithSingleContext#ff421(offset: 0.0, range: 0.0..7088.5, viewport: 618.0,
flutter:     ScrollableState, BouncingScrollPhysics, IdleScrollActivity#58e51, ScrollDirection.idle)
flutter:   anchor: 0.0
flutter: This RenderObject had the following descendants (showing up to depth 5):
flutter:     center child: RenderSliverPadding#ea71d relayoutBoundary=up1
flutter:       child: RenderSliverList#7abe8 relayoutBoundary=up2
flutter:         child with index 0: RenderIndexedSemantics#fb802 relayoutBoundary=up3
flutter:           child: RenderRepaintBoundary#d88c8 relayoutBoundary=up4
flutter:             child: RenderSemanticsGestureHandler#0cb6d relayoutBoundary=up5
flutter:         child with index 1: RenderIndexedSemantics#84c1b relayoutBoundary=up3
flutter:           child: RenderRepaintBoundary#1b60f relayoutBoundary=up4
flutter:             child: RenderSemanticsGestureHandler#6a289 relayoutBoundary=up5
flutter:         child with index 2: RenderIndexedSemantics#d56f8 relayoutBoundary=up3
flutter:           child: RenderRepaintBoundary#6633d relayoutBoundary=up4
flutter:             child: RenderSemanticsGestureHandler#0d833 relayoutBoundary=up5
flutter:         child with index 3: RenderIndexedSemantics#8f390 relayoutBoundary=up3 NEEDS-PAINT
flutter:           child: RenderRepaintBoundary#7bc40 relayoutBoundary=up4 NEEDS-PAINT
flutter:             child: RenderSemanticsGestureHandler#570f0 relayoutBoundary=up5 NEEDS-PAINT
flutter: ════════════════════════════════════════════════════════════════════════════════════════════════════
Lost connection to device.
```

```
[✓] Flutter (Channel beta, v1.7.8+hotfix.3, on Mac OS X 10.14.5 18F132, locale en-DE)
    • Flutter version 1.7.8+hotfix.3 at /Users/miquel/dev/tools/flutter
    • Framework revision b712a172f9 (9 days ago), 2019-07-09 13:14:38 -0700
    • Engine revision 54ad777fd2
    • Dart version 2.4.0

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/miquel/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 10.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.2.1, Build version 10E1001
    • CocoaPods version 1.7.0

[✓] iOS tools - develop for iOS devices
    • ios-deploy 1.9.4

[✓] Android Studio (version 3.4)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 36.0.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

[✓] IntelliJ IDEA Ultimate Edition (version 2019.1.3)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 37.0.3
    • Dart plugin version 191.7830

[✓] IntelliJ IDEA Community Edition (version 2019.1.3)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 36.1.4
    • Dart plugin version 191.7830

[✓] Connected device (1 available)
    • iPhone X • 118AF3BE-C730-4748-8F48-58E04E9CA921 • ios • com.apple.CoreSimulator.SimRuntime.iOS-12-2 (simulator)

• No issues found!
```

I use IntelliJ IDEA Ultimate Edition.

**Comment by elisamuelps** [comment]
I'm having the same issue, I'm on Android Studio 3.6, and after I press on the flutter inspector that is located on the Dart Devtools panel, the app immediately crashes.

**Comment by TahaTesser** [comment]
Hi @aaronraimist 
Not able to reproduce this issue on multiple tries in Android Studio 

<details> 
<summary>Code Sample</summary> 

```
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Material App',
      theme: ThemeData.dark(),
      home: Home(),
    );
  }
}

class Home extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('Material App Bar'),
      ),
      body: Center(
        child: Container(
          child: Text('Hello World'),
        ),
      ),
      floatingActionButton: FloatingActionButton(
        child: Icon(Icons.add),
        onPressed: () {},
      ),
    );
  }
}

``` 

</details> 


<details> 
<summary>flutter doctor -v</summary> 

```
[✓] Flutter (Channel dev, 1.21.0-1.0.pre, on Mac OS X 10.15.6 19G73, locale
    en-GB)
    • Flutter version 1.21.0-1.0.pre at /Users/taha/Code/flutter_dev
    • Framework revision f25bd9c55c (3 weeks ago), 2020-07-14 20:26:01 -0400
    • Engine revision 99c2b3a245
    • Dart version 2.9.0 (build 2.9.0-21.0.dev 20bf2fcf56)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
    • Android SDK at /Users/taha/Code/sdk
    • Platform android-30, build-tools 30.0.1
    • ANDROID_HOME = /Users/taha/Code/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.6)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.6, Build version 11E708
    • CocoaPods version 1.9.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 48.0.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.47.3)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.13.1

 
[✓] Connected device (4 available)            
    • Taha’s iPhone (mobile) • 00008020-001059882212002E • ios            • iOS
      13.6
    • macOS (desktop)        • macos                     • darwin-x64     • Mac
      OS X 10.15.6 19G73
    • Web Server (web)       • web-server                • web-javascript •
      Flutter Tools
    • Chrome (web)           • chrome                    • web-javascript •
      Google Chrome 84.0.4147.105

• No issues found!
```

</details> 


Could everyone who still has this problem please file a new issue with the exact description of what happens, logs and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
