### ISSUE TITLE
can't able to add two specific packages

### ISSUE THREAD

**Issue by ShashankSirmour** [flutter/flutter#34493]
## Steps to Reproduce

1. can't able to add  two specific packages in the project it gives a lot of  error 

packages are 

  flutter_downloader: ^1.1.7
  admob_flutter: ^0.3.1

## Logs

```
ms] > Task :app:transformDexArchiveWithExternalLibsDexMergerForDebug FAILED
[   +3 ms] D8: Program type already present: android.support.v4.app.INotificationSideChannel
[   +3 ms] 61 actionable tasks: 5 executed, 56 up-to-date
[        ] FAILURE: Build failed with an exception.
[   +1 ms] * What went wrong:
[        ] Execution failed for task ':app:transformDexArchiveWithExternalLibsDexMergerForDebug'.
[   +1 ms] > com.android.builder.dexing.DexArchiveMergerException: Error while merging dex archives:
C:\Users\Superman\Dev\Create\doc\bookconda\build\app\intermediates\transforms\dexBuilder\debug\2.jar,
C:\Users\Superman\Dev\Create\doc\bookconda\build\app\intermediates\transforms\dexBuilder\debug\3.jar,
C:\Users\Superman\Dev\Create\doc\bookconda\build\app\intermediates\transforms\dexBuilder\debug\4.jar,
C:\Users\Superman\Dev\Create\doc\bookconda\build\app\intermediates\transforms\dexBuilder\debug\5.jar,
C:\Users\Superman\Dev\Create\doc\bookconda\build\app\intermediates\transforms\dexBuilder\debug\6.jar,
C:\Users\Superman\Dev\Create\doc\bookconda\build\app\intermediates\transforms\dexBuilder\debug\7.jar,
C:\Users\Superman\Dev\Create\doc\bookconda\build\app\intermediates\transforms\dexBuilder\debug\8.jar,
C:\Users\Superman\Dev\Create\doc\bookconda\build\app\intermediates\transforms\dexBuilder\debug\9.jar,
C:\Users\Superman\Dev\Create\doc\bookconda\build\app\intermediates\transforms\dexBuilder\debug\10.jar,
C:\Users\Superman\Dev\Create\doc\bookconda\build\app\intermediates\transforms\dexBuilder\debug\11.jar,
C:\Users\Superman\Dev\Create\doc\bookconda\build\app\intermediates\transforms\dexBuilder\debug\12.jar,
C:\Users\Superman\Dev\Create\doc\bookconda\build\app\intermediates\transforms\dexBuilder\debug\13.jar,
C:\Users\Superman\Dev\Create\doc\bookconda\build\app\intermediates\transforms\dexBuilder\debug\14.jar,
C:\Users\Superman\Dev\Create\doc\bookconda\build\app\intermediates\transforms\dexBuilder\debug\15.jar,
C:\Users\Superman\Dev\Create\doc\bookconda\build\app\intermediates\transforms\dexBuilder\debug\16.jar,
C:\Users\Superman\Dev\Create\doc\bookconda\build\app\intermediates\transforms\dexBuilder\debug\17.jar,
C:\Users\Superman\Dev\Create\doc\bookconda\build\app\intermediates\transforms\dexBuilder\debug\18.jar,
C:\Users\Superman\Dev\Create\doc\bookconda\build\app\intermediates\transforms\dexBuilder\debug\19.jar,
C:\Users\Superman\Dev\Create\doc\bookconda\build\app\intermediates\transforms\dexBuilder\debug\20.jar,
C:\Users\Superman\Dev\Create\doc\bookconda\build\app\intermediates\transforms\dexBuilder\debug\21.jar,
C:\Users\Superman\Dev\Create\doc\bookconda\build\app\intermediates\transforms\dexBuilder\debug\22.jar,
C:\Users\Superman\Dev\Create\doc\bookconda\build\app\intermediates\transforms\dexBuilder\debug\23.jar,
C:\Users\Superman\Dev\Create\doc\bookconda\build\app\intermediates\transforms\dexBuilder\debug\24.jar,
C:\Users\Superman\Dev\Create\doc\bookconda\build\app\intermediates\transforms\dexBuilder\debug\25.jar,
C:\Users\Superman\Dev\Create\doc\bookconda\build\app\intermediates\transforms\dexBuilder\debug\26.jar,
C:\Users\Superman\Dev\Create\doc\bookconda\build\app\intermediates\transforms\dexBuilder\debug\27.jar,
C:\Users\Superman\Dev\Create\doc\bookconda\build\app\intermediates\transforms\dexBuilder\debug\28.jar,
C:\Users\Superman\Dev\Create\doc\bookconda\build\app\intermediates\transforms\dexBuilder\debug\29.jar,
C:\Users\Superman\Dev\Create\doc\bookconda\build\app\intermediates\transforms\dexBuilder\debug\30.jar,
C:\Users\Superman\Dev\Create\doc\bookconda\build\app\intermediates\transforms\dexBuilder\debug\31.jar,
C:\Users\Superman\Dev\Create\doc\bookconda\build\app\intermediates\transforms\dexBuilder\debug\32.jar,
C:\Users\Superman\Dev\Create\doc\bookconda\build\app\intermediates\transforms\dexBuilder\debug\33.jar,
C:\Users\Superman\Dev\Create\doc\bookconda\build\app\intermediates\transforms\dexBuilder\debug\34.jar,
C:\Users\Superman\Dev\Create\doc\bookconda\build\app\intermediates\transforms\dexBuilder\debug\35.jar,
C:\Users\Superman\Dev\Create\doc\bookconda\build\app\intermediates\transforms\dexBuilder\debug\36.jar,
C:\Users\Superman\Dev\Create\doc\bookconda\build\app\intermediates\transforms\dexBuilder\debug\37.jar,
C:\Users\Superman\Dev\Create\doc\bookconda\build\app\intermediates\transforms\dexBuilder\debug\38.jar,
C:\Users\Superman\Dev\Create\doc\bookconda\build\app\intermediates\transforms\dexBuilder\debug\39.jar,
C:\Users\Superman\Dev\Create\doc\bookconda\build\app\intermediates\transforms\dexBuilder\debug\40.jar,
C:\Users\Superman\Dev\Create\doc\bookconda\build\app\intermediates\transforms\dexBuilder\debug\41.jar,
C:\Users\Superman\Dev\Create\doc\bookconda\build\app\intermediates\transforms\dexBuilder\debug\42.jar,
C:\Users\Superman\Dev\Create\doc\bookconda\build\app\intermediates\transforms\dexBuilder\debug\43.jar,
C:\Users\Superman\Dev\Create\doc\bookconda\build\app\intermediates\transforms\dexBuilder\debug\44.jar,
C:\Users\Superman\Dev\Create\doc\bookconda\build\app\intermediates\transforms\dexBuilder\debug\45.jar,
C:\Users\Superman\Dev\Create\doc\bookconda\build\app\intermediates\transforms\dexBuilder\debug\46.jar,
C:\Users\Superman\Dev\Create\doc\bookconda\build\app\intermediates\transforms\dexBuilder\debug\47.jar,
C:\Users\Superman\Dev\Create\doc\bookconda\build\app\intermediates\transforms\dexBuilder\debug\48.jar,
C:\Users\Superman\Dev\Create\doc\bookconda\build\app\intermediates\transforms\dexBuilder\debug\49.jar,
C:\Users\Superman\Dev\Create\doc\bookconda\build\app\intermediates\transforms\dexBuilder\debug\50.jar,
C:\Users\Superman\Dev\Create\doc\bookconda\build\app\intermediates\transforms\dexBuilder\debug\51.jar,
C:\Users\Superman\Dev\Create\doc\bookconda\build\app\intermediates\transforms\dexBuilder\debug\52.jar,
C:\Users\Superman\Dev\Create\doc\bookconda\build\app\intermediates\transforms\dexBuilder\debug\53.jar,
C:\Users\Superman\Dev\Create\doc\bookconda\build\app\intermediates\transforms\dexBuilder\debug\54.jar,
C:\Users\Superman\Dev\Create\doc\bookconda\build\app\intermediates\transforms\dexBuilder\debug\55.jar,
C:\Users\Superman\Dev\Create\doc\bookconda\build\app\intermediates\transforms\dexBuilder\debug\56.jar,
C:\Users\Superman\Dev\Create\doc\bookconda\build\app\intermediates\transforms\dexBuilder\debug\57.jar,
C:\Users\Superman\Dev\Create\doc\bookconda\build\app\intermediates\transforms\dexBuilder\debug\58.jar,
C:\Users\Superman\Dev\Create\doc\bookconda\build\app\intermediates\transforms\dexBuilder\debug\59.jar,
C:\Users\Superman\Dev\Create\doc\bookconda\build\app\intermediates\transforms\dexBuilder\debug\60.jar,
C:\Users\Superman\Dev\Create\doc\bookconda\build\app\intermediates\transforms\dexBuilder\debug\61.jar,
C:\Users\Superman\Dev\Create\doc\bookconda\build\app\intermediates\transforms\dexBuilder\debug\62.jar,
C:\Users\Superman\Dev\Create\doc\bookconda\build\app\intermediates\transforms\dexBuilder\debug\63.jar,
C:\Users\Superman\Dev\Create\doc\bookconda\build\app\intermediates\transforms\dexBuilder\debug\64.jar,
C:\Users\Superman\Dev\Create\doc\bookconda\build\app\intermediates\transforms\dexBuilder\debug\65.jar,
C:\Users\Superman\Dev\Create\doc\bookconda\build\app\intermediates\transforms\dexBuilder\debug\66.jar,
C:\Users\Superman\Dev\Create\doc\bookconda\build\app\intermediates\transforms\dexBuilder\debug\67.jar,
C:\Users\Superman\Dev\Create\doc\bookconda\build\app\intermediates\transforms\dexBuilder\debug\68.jar,
C:\Users\Superman\Dev\Create\doc\bookconda\build\app\intermediates\transforms\dexBuilder\debug\69.jar,
C:\Users\Superman\Dev\Create\doc\bookconda\build\app\intermediates\transforms\dexBuilder\debug\70.jar,
C:\Users\Superman\Dev\Create\doc\bookconda\build\app\intermediates\transforms\dexBuilder\debug\71.jar,
C:\Users\Superman\Dev\Create\doc\bookconda\build\app\intermediates\transforms\dexBuilder\debug\72.jar
[  +15 ms]   Learn how to resolve the issue at https://developer.android.com/studio/build/dependencies#duplicate_classes.
[   +2 ms]   Program type already present: android.support.v4.app.INotificationSideChannel
[        ] * Try:
[        ] Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan
to get full insights.
[   +1 ms] * Get more help at https://help.gradle.org
[        ] BUILD FAILED in 15s
[ +437 ms] Running Gradle task 'assembleDebug'... (completed in 16.5s)
[   +1 ms] *******************************************************************************************
[        ] The Gradle failure may have been because of AndroidX incompatibilities in this Flutter app.
[        ] See https://goo.gl/CP92wY for more information on the problem and how to fix it.
[   +1 ms] *******************************************************************************************
[   +3 ms] "flutter run" took 24,753ms.
[        ] "flutter run" took 24,753ms.
Gradle task assembleDebug failed with exit code 1

#0      throwToolExit (package:flutter_tools/src/base/common.dart:24:3)
#1      _buildGradleProjectV2 (package:flutter_tools/src/android/gradle.dart:478:5)
<asynchronous suspension>
#2      buildGradleProject (package:flutter_tools/src/android/gradle.dart:346:14)
<asynchronous suspension>
#3      buildApk (package:flutter_tools/src/android/apk.dart:34:9)
<asynchronous suspension>
#4      AndroidDevice.startApp (package:flutter_tools/src/android/android_device.dart:377:13)
<asynchronous suspension>
#5      FlutterDevice.runHot (package:flutter_tools/src/resident_runner.dart:364:54)
<asynchronous suspension>
#6      HotRunner.run (package:flutter_tools/src/run_hot.dart:253:39)
<asynchronous suspension>
#7      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:428:37)
<asynchronous suspension>
#8      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:559:18)
#9      _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:77:64)
#10     _rootRunUnary (dart:async/zone.dart:1132:38)
#11     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#12     _FutureListener.handleValue (dart:async/future_impl.dart:126:18)
#13     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:639:45)
#14     Future._propagateToListeners (dart:async/future_impl.dart:668:32)
#15     Future._complete (dart:async/future_impl.dart:473:7)
#16     _SyncCompleter.complete (dart:async/future_impl.dart:51:12)
#17     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:28:18)
#18     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:294:13)
#19     RunCommand.usageValues (package:flutter_tools/src/commands/run.dart)
#20     _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:77:64)
#21     _rootRunUnary (dart:async/zone.dart:1132:38)
#22     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#23     _FutureListener.handleValue (dart:async/future_impl.dart:126:18)
#24     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:639:45)
#25     Future._propagateToListeners (dart:async/future_impl.dart:668:32)
#26     Future._complete (dart:async/future_impl.dart:473:7)
#27     _SyncCompleter.complete (dart:async/future_impl.dart:51:12)
#28     _AsyncAwaitCompleter.complete.<anonymous closure> (dart:async-patch/async_patch.dart:33:20)
#29     _rootRun (dart:async/zone.dart:1124:13)
#30     _CustomZone.run (dart:async/zone.dart:1021:19)
#31     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:947:23)
#32     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#33     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#34     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:115:13)
#35     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:5)

```

```
No issues found! (ran in 7.8s)
```

```
[√] Flutter (Channel stable, v1.5.4-hotfix.2, on Microsoft Windows [Version 10.0.17763.557], locale en-IN)
    • Flutter version 1.5.4-hotfix.2 at C:\src\flutter
    • Framework revision 7a4c33425d (7 weeks ago), 2019-04-29 11:05:24 -0700
    • Engine revision 52c7a1e849
    • Dart version 2.3.0 (build 2.3.0-dev.0.5 a1668566e5)


[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at C:\Users\Superman\AppData\Local\Android\Sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = C:\Users\Superman\AppData\Local\Android\Sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)
    • All Android licenses accepted.

[√] Android Studio (version 3.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 33.3.1
    • Dart plugin version 182.5215
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)

[√] IntelliJ IDEA Ultimate Edition (version 2017.3)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA 2017.3.4
    • Flutter plugin version 29.0.1
    • Dart plugin version 173.4700

[√] VS Code, 64-bit edition (version 1.35.1)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Flutter extension version 3.1.0

[√] Connected device (1 available)
    • Redmi Note 5 Pro • 93e9909b • android-arm64 • Android 8.1.0 (API 27)

• No issues found!
```

**Comment by hemnathmouli** [comment]
Did you try androidX migration?

**Comment by ShashankSirmour** [comment]
> Did you try androidX migration? https://goo.gl/CP92wY

I try but it is prompting  "No Usages Found in the Project"

**Comment by ShashankSirmour** [comment]
I also try to manually migrate but nothing changes except now I am getting error some error I just imported two package nothing in the code just example pre-populated code try this if you want to see

**Comment by ShashankSirmour** [comment]
I try to migrate with these packages and it gives me more error 


''' cupertino_icons: ^0.1.2
  html: ^0.13.3+3
  http: ^0.12.0
  bubble_bottom_bar: ^1.2.0
  cached_network_image: ^0.6.0
  auto_size_text: ^2.0.0+2
  flutter_widget_from_html_core:
  path_provider: 
  flutter_downloader: 
  scoped_model: ^1.0.1
  flutter_pdfview: ^1.0.0+4
  flutter_slidable: ^0.5.3
  share: ^0.6.1+1
  flutter_fluid_slider: ^1.0.1
  admob_flutter: 
'''

**Comment by ShashankSirmour** [comment]
thank you @hemnathmouli  doing wrong in the process of  androidX migration  now i manage to do it thank you very much for your help

**Comment by hemnathmouli** [comment]
@ShashankSirmour I don't know why but that sounds like you're ironic.

**Comment by ShashankSirmour** [comment]
@hemnathmouli  sorry if I said something wrong I.I just thanks you for advice as I am not considering androidX to create that much problem thank you again as of your suggestions I followed the process again and did it thank you again.
