### ISSUE TITLE
[image_picker] pickImage 0.6.0+9

### ISSUE THREAD

**Issue by alange-pivotal** [flutter/flutter#34496]
Having this issue on IOS:

[VERBOSE-2:ui_dart_state.cc(148)] Unhandled Exception: MissingPluginException(No implementation found for method pickImage on channel external_custom_packages.plugins.flutter.io/image_picker)
#0 MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:300:7)

#1 ImagePicker.pickImage (package:image_picker/image_picker.dart:53:40)

#2 _AvatarNameComponents._getPicture (package:swopda_frontend/widgets/editcontact/avatar_name_components.dart:85:23)

#3 _AvatarNameComponents._settingCustomModalBottomSheet.. (package:swopda_frontend/widgets/editcontact/avatar_name_components.dart:141:21)
#4 _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:511:14)
#5 _InkResponseState.build. (package:flutter/src/material/ink_well.dart:566:30)
#6 GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:166:24)
#7 TapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:240:9)
#8 TapGestureRecognizer.acceptGesture (package:flutter/src/gestures/tap.dart:211:7)
#9 GestureArenaManager.sweep (package:flutter/src/gestures/arena.dart:156:27)
#10 _WidgetsFlutterBinding&BindingBase&GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:225:20)
#11 _WidgetsFlutterBinding&BindingBase&GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:199:22)
#12 _WidgetsFlutterBinding&BindingBase&GestureBinding._handlePointerEvent (package:flutter/src/gestures/binding.dart:156:7)
#13 _WidgetsFlutterBinding&BindingBase&GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:102:7)
#14 _WidgetsFlutterBinding&BindingBase&GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:86:7)
#15 _rootRunUnary (dart:async/zone.dart:1136:13)
#16 _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#17 _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
#18 _invoke1 (dart:ui/hooks.dart:233:10)
#19 _dispatchPointerDataPacket (dart:ui/hooks.dart:154:5)

using:
image_picker: ^0.6.0+9
in pubspec.yml

using flutter project -i swift -a kotlin

[✓] Flutter (Channel stable, v1.5.4-hotfix.2, on Mac OS X 10.14.5 18F132, locale de-DE)
    • Flutter version 1.5.4-hotfix.2 at /Users/alange/development/flutter/flutter
    • Framework revision 7a4c33425d (7 weeks ago), 2019-04-29 11:05:24 -0700
    • Engine revision 52c7a1e849
    • Dart version 2.3.0 (build 2.3.0-dev.0.5 a1668566e5)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/alange/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • ANDROID_SDK_ROOT = /Users/alange/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.2.1, Build version 10E1001
    • ios-deploy 1.9.4
    • CocoaPods version 1.7.2

[✓] Android Studio (version 3.4)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 36.1.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

[✓] IntelliJ IDEA Ultimate Edition (version 2019.1.2)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 35.3.3
    • Dart plugin version 191.7141.49

[✓] Connected device (1 available)
    • PivotalMobile • 32c1ad6310195ce0d99e3bf1e4611a3b15265e8e • ios • iOS 12.3.1

• No issues found!

**Comment by alange-pivotal** [comment]
Solved it by fully removing the plugin from my mac incl. cache.

registering:
+ (void)registerWithRegistrar:(NSObject<FlutterPluginRegistrar> *)registrar {
  FlutterMethodChannel *channel =
      [FlutterMethodChannel methodChannelWithName:@"external_custom_packages.plugins.flutter.io/image_picker"
                                  binaryMessenger:[registrar messenger]];
  UIViewController *viewController =
      [UIApplication sharedApplication].delegate.window.rootViewController;
  FLTImagePickerPlugin *instance =
      [[FLTImagePickerPlugin alloc] initWithViewController:viewController];
  [registrar addMethodCallDelegate:instance channel:channel];
}
was not called proper. 

After getting the plugin and using it, everything worked... 
Still I am not sure why it happened.
