### ISSUE TITLE
Flutter_driver not working with Stack widget ?

### ISSUE THREAD

**Issue by Pyozer** [flutter/flutter#34503]
Hi,

I'm trying to add some integration tests with `flutter_driver`, but i have some issues..
On some screen of the app (SplashScreen, and my Main screen), the widgets are not detected, either using text, byType or even byValueKey.

After some tests, I think that it is about the Stack widget. In fact, I remove Stack widget on my SplashScreen, without change my test, and the flutter_driver finally detect my Text.

To launch the test I using this command:
`flutter clean && flutter build apk --debug && flutter drive --target=test_driver/app.dart`

Flutter doctor -v:
```
[✓] Flutter (Channel beta, v1.6.3, on Mac OS X 10.14.5 18F203, locale en-GB)
    • Flutter version 1.6.3 at /Users/podpak/Tools/flutter
    • Framework revision bc7bc94083 (3 weeks ago), 2019-05-23 10:29:07 -0700
    • Engine revision 8dc3a4cde2
    • Dart version 2.3.2 (build 2.3.2-dev.0.0 e3edfd36b2)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/podpak/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.2.1, Build version 10E1001
    • ios-deploy 1.9.4
    • CocoaPods version 1.7.0

[✓] Android Studio (version 3.4)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 36.1.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

[✓] VS Code (version 1.35.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.1.0

[✓] Connected device (1 available)
    • ONEPLUS A6013 • 192.168.1.99:5555 • android-arm64 • Android 9 (API 28)

• No issues found!
```

Splashscreen code that **not** working:

```dart
return Scaffold(
  body: Stack(
    alignment: Alignment.center,
    children: [
      const SplashScreenLogo(),
      SafeArea(
        bottom: false,
        child: Padding(
          padding: const EdgeInsets.fromLTRB(20.0, 20.0, 20.0, 0),
          child: Column(
            crossAxisAlignment: CrossAxisAlignment.stretch,
            mainAxisSize: MainAxisSize.max,
            children: [
              FutureBuilder<PackageInfo>(
                future: PackageInfo.fromPlatform(),
                builder: (context, snap) {
                  if (!snap.hasData) return Text("");
                  return Text(
                    '${snap.data.version} (${snap.data.buildNumber})',
                    textAlign: TextAlign.end,
                    style: const TextStyle(color: Colors.black26),
                  );
                },
              ),
              const Expanded(child: SizedBox()),
              Text(
                _currentMessage,
                textAlign: TextAlign.center,
                style: const TextStyle(fontSize: 18.0),
              ),
              const SizedBox(height: 24.0),
              false
                  ? const SizedBox.shrink()
                  : Center(child: RetryButton(onPress: _initAllData)),
              const SizedBox(height: 24.0),
              LinearProgressIndicator(value: _isLoading ? null : 0),
            ],
          ),
        ),
      ),
    ],
  ),
);
```

Splashscreen code that working:

```dart
return Scaffold(
  body: SafeArea(
    bottom: false,
    child: Padding(
      padding: const EdgeInsets.fromLTRB(20.0, 20.0, 20.0, 0),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.stretch,
        mainAxisSize: MainAxisSize.max,
        children: [
          FutureBuilder<PackageInfo>(
            future: PackageInfo.fromPlatform(),
            builder: (context, snap) {
              if (!snap.hasData) return Text("");
              return Text(
                '${snap.data.version} (${snap.data.buildNumber})',
                textAlign: TextAlign.end,
                style: const TextStyle(color: Colors.black26),
              );
            },
          ),
          const Expanded(child: SizedBox()),
          Text(
            "Loading",
            textAlign: TextAlign.center,
            style: const TextStyle(fontSize: 18.0),
          ),
          const SizedBox(height: 24.0),
          false
              ? const SizedBox.shrink()
              : Center(child: RetryButton(onPress: _initAllData)),
          const SizedBox(height: 24.0),
          LinearProgressIndicator(value: _isLoading ? null : 0),
        ],
      ),
    ),
  ),
);
```

My test :
```dart
import 'package:flutter_driver/flutter_driver.dart';
import 'package:test/test.dart';

void main() {
  group('Testing app', () {
    FlutterDriver driver;

    // Connect to the Flutter driver before running any tests.
    setUpAll(() async {
      driver = await FlutterDriver.connect();
    });

    // Close the connection to the driver after the tests have completed.
    tearDownAll(() async {
      if (driver != null) {
        driver.close();
      }
    });

    test('Test Splashscreen', () async {
      await driver.waitFor(find.text("Loading"));
    });
  });
}
```

Here it's the log when it's not working:
```
[info ] FlutterDriver: Connecting to Flutter application at http://127.0.0.1:56257/obqYBar-XP4=/
[trace] FlutterDriver: Isolate found with number: 129091108
[trace] FlutterDriver: Isolate is paused at start.
[trace] FlutterDriver: Attempting to resume isolate
[trace] FlutterDriver: Waiting for service extension
[info ] FlutterDriver: Connected to Flutter application.
00:01 +0: Testing app Test Splashscreen
[warning] FlutterDriver: waitFor message is taking a long time to complete...
00:31 +0 -1: Testing app Test Splashscreen [E]
  TimeoutException after 0:00:30.000000: Test timed out after 30 seconds.
  package:test_api/src/backend/invoker.dart 332:28              Invoker._handleError.<fn>
  dart:async/zone.dart 1120:38                                  _rootRun
  dart:async/zone.dart 1021:19                                  _CustomZone.run
  package:test_api/src/backend/invoker.dart 330:10              Invoker._handleError
  package:test_api/src/backend/invoker.dart 283:9               Invoker.heartbeat.<fn>.<fn>
  dart:async/zone.dart 1124:13                                  _rootRun
  dart:async/zone.dart 1021:19                                  _CustomZone.run
  package:test_api/src/backend/invoker.dart 281:38              Invoker.heartbeat.<fn>
  package:stack_trace/src/stack_zone_specification.dart 209:15  StackZoneSpecification._run
  package:stack_trace/src/stack_zone_specification.dart 119:48  StackZoneSpecification._registerCallback.<fn>
  dart:async/zone.dart 1124:13                                  _rootRun
  dart:async/zone.dart 1021:19                                  _CustomZone.run
  dart:async/zone.dart 947:23                                   _CustomZone.bindCallback.<fn>
  dart:async-patch/timer_patch.dart 21:15                       Timer._createTimer.<fn>
  dart:isolate-patch/timer_impl.dart 382:19                     _Timer._runTimers
  dart:isolate-patch/timer_impl.dart 416:5                      _Timer._handleMessage
  dart:isolate-patch/isolate_patch.dart 171:12                  _RawReceivePortImpl._handleMessage
  ===== asynchronous gap ===========================
  dart:async/zone.dart 1045:19                                  _CustomZone.registerCallback
  dart:async/zone.dart 946:22                                   _CustomZone.bindCallback
  dart:async/zone.dart 1191:21                                  _rootCreateTimer
  dart:async/zone.dart 1088:19                                  _CustomZone.createTimer
  package:test_api/src/backend/invoker.dart 280:34              Invoker.heartbeat
  package:test_api/src/backend/invoker.dart 243:5               Invoker.waitForOutstandingCallbacks
  package:test_api/src/backend/declarer.dart 166:33             Declarer.test.<fn>.<fn>
  dart:async/zone.dart 1124:13                                  _rootRun
  dart:async/zone.dart 1021:19                                  _CustomZone.run
  dart:async/zone.dart 1516:10                                  _runZoned
  dart:async/zone.dart 1463:12                                  runZoned
  package:test_api/src/backend/declarer.dart 165:13             Declarer.test.<fn>
  ===== asynchronous gap ===========================
  dart:async/zone.dart 1045:19                                  _CustomZone.registerCallback
  dart:async/zone.dart 962:22                                   _CustomZone.bindCallbackGuarded
  dart:async/timer.dart 52:45                                   new Timer
  dart:async/timer.dart 87:9                                    Timer.run
  dart:async/future.dart 174:11                                 new Future
  package:test_api/src/backend/invoker.dart 399:21              Invoker._onRun.<fn>.<fn>.<fn>

00:31 +0 -1: Testing app (tearDownAll)
00:31 +0 -1: Testing app Test Splashscreen [E]
  DriverError: Failed to fulfill WaitFor due to remote error
  Original error: Bad state: The client closed with pending request "ext.flutter.driver".
  Original stack trace:
  #0      new Client.withoutJson.<anonymous closure> (package:json_rpc_2/src/client.dart:70:24)
  #1      StackZoneSpecification._run (package:stack_trace/src/stack_zone_specification.dart:209:15)
  #2      StackZoneSpecification._registerCallback.<anonymous closure> (package:stack_trace/src/stack_zone_specification.dart:119:48)
  #3      _rootRun (dart:async/zone.dart:1120:38)
  #4      _CustomZone.run (dart:async/zone.dart:1021:19)
  #5      _FutureListener.handleWhenComplete (dart:async/future_impl.dart:150:18)
  #6      Future._propagateToListeners.handleWhenCompleteCallback (dart:async/future_impl.dart:609:39)
  #7      Future._propagateToListeners (dart:async/future_impl.dart:665:37)
  #8      Future._propagateToListeners (dart:async/future_impl.dart:566:9)
  #9      Future._completeWithValue (dart:async/future_impl.dart:483:5)
  #10     Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:513:7)
  #11     StackZoneSpecification._run (package:stack_trace/src/stack_zone_specification.dart:209:15)
  #12     StackZoneSpecification._registerCallback.<anonymous closure> (package:stack_trace/src/stack_zone_specification.dart:119:48)
  #13     _rootRun (dart:async/zone.dart:1124:13)
  #14     _CustomZone.run (dart:async/zone.dart:1021:19)
  #15     _CustomZone.runGuarded (dart:async/zone.dart:923:7)
  #16     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:963:23)
  #17     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
  #18     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
  #19     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:391:30)
  #20     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:416:5)
  #21     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:171:12)


  package:flutter_driver/src/driver/driver.dart 416:7   FlutterDriver._sendCommand
  ===== asynchronous gap ===========================
  dart:async/future_impl.dart 22:43                     _Completer.completeError
  dart:async-patch/async_patch.dart 40:18               _AsyncAwaitCompleter.completeError
  package:flutter_driver/src/driver/driver.dart         FlutterDriver._sendCommand
  ===== asynchronous gap ===========================
  dart:async/zone.dart 1062:19                          _CustomZone.registerBinaryCallback
  dart:async-patch/async_patch.dart 86:23               _asyncErrorWrapperHelper
  package:flutter_driver/src/driver/driver.dart         FlutterDriver._sendCommand
  package:flutter_driver/src/driver/driver.dart 454:11  FlutterDriver.waitFor
  ===== asynchronous gap ===========================
  dart:async/zone.dart 1053:19                          _CustomZone.registerUnaryCallback
  dart:async-patch/async_patch.dart 77:23               _asyncThenWrapperHelper
  package:test_api/src/backend/declarer.dart            Declarer.test.<fn>.<fn>.<fn>
  package:test_api/src/backend/invoker.dart 250:15      Invoker.waitForOutstandingCallbacks.<fn>
  ===== asynchronous gap ===========================
  dart:async/zone.dart 1045:19                          _CustomZone.registerCallback
  dart:async/zone.dart 962:22                           _CustomZone.bindCallbackGuarded
  dart:async/timer.dart 52:45                           new Timer
  dart:async/timer.dart 87:9                            Timer.run
  dart:async/future.dart 174:11                         new Future
  package:test_api/src/backend/invoker.dart 399:21      Invoker._onRun.<fn>.<fn>.<fn>

00:31 +0 -1: Some tests failed.

Unhandled exception:
Dummy exception to set exit code.
#0      _rootHandleUncaughtError.<anonymous closure> (dart:async/zone.dart:1112:29)
#1      _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#2      _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#3      _Timer._runTimers (dart:isolate-patch/timer_impl.dart:391:30)
#4      _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:416:5)
#5      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:171:12)
Stopping application instance.
Driver tests failed: 255
```

Thank you for your help ;)

**Comment by dnfield** [comment]
Your non-working example doesn't seem to have the text `Loading` anywhere in it...

**Comment by Pyozer** [comment]
@dnfield It has "Loading" text, it's just that I forgot to replace the `_currentMessage` variable by "Loading" to have a simpler code.
In "real" code, my working example use also `_currentMessage`.

**Comment by Pyozer** [comment]
Hi, I made some other tests to find the issue, I realized that the issue is not directly due to the Stack widget but the Align widget.
I test again the code that I provide before, and both are working, but before create this issue, my code wasn't exactly the same (I edit it to have a simpler code for the issue, but that wasn't a good idea..)

You can find [here](https://gist.github.com/Pyozer/3d3830ea74c7d069dc5f91b5e3f6641b) the correct code (one working, other not, and my test file).

My other tests are working great (except one but I think it's the same issue).
In SplashScreen, when I keep my Align widget with the LinearProgressIndicator, it is not working, my "Loading" text is not detected (even if I put it in 2nd position in the list).

But if I remove the Align widget (the 3rd element in my Stack list), the "Loading" text is detected, and the test working.

I have no idea if it's a flutter_driver issue or if I made something wrong..

**Comment by Pyozer** [comment]
_Edit :_
I think it is due to animation (that could also explain why my other test on my main screen, is not working, I also have animations on it).
It could be same issue as [#25975](https://github.com/flutter/flutter/issues/25975)

**Comment by Pyozer** [comment]
I found the solution !
The flutter driver is by default frame synchronized, it will wait until there is no pending frame(s), but if there is infinite animation, the test will go to the timeout and fail.

To fix this, you need to wrap your tests with the driver.runUnsynchronized() method.
Like this:
```dart
test('Test SplashScreen', () async {
  await driver.runUnsynchronized(() async {
    await driver.waitFor(find.text("Loading"));
  });
});
```
(Only if you have an infinite animation or you want to continue before end of an animation)

Hoping it can help someone else ;)
