### ISSUE TITLE
Google map trown error while creating style

### ISSUE THREAD

**Issue by farhanrahmadi** [flutter/flutter#34544]
## What result i want
[map style i want](https://cdn.toolset.com/wp-content/uploads/2017/12/toolset-maps-custom-styling-silver.png?x67680)

## What it result
[what it result](https://ucarecdn.com/fa6c1d12-89ee-41e6-bf6a-1bf2cd9f7b2b/Screenshot_1560615189.png)

## Logs

```
E/flutter ( 8885): [ERROR:flutter/lib/ui/ui_dart_state.cc(148)] Unhandled Exception: Instance of 'MapStyleException'
E/flutter ( 8885): #0      GoogleMapController.setMapStyle (package:google_maps_flutter/src/controller.dart:194:7)
E/flutter ( 8885): <asynchronous suspension>
E/flutter ( 8885): #1      _CariinState.build.<anonymous closure> (package:cariin_mobile/pages/Dashboard/Cariin/cariin.dart:192:23)
E/flutter ( 8885): #2      _GoogleMapState.onPlatformViewCreated (package:google_maps_flutter/src/google_map.dart:278:14)
E/flutter ( 8885): <asynchronous suspension>
E/flutter ( 8885): #3      AndroidViewController._create (package:flutter/src/services/platform_views.dart:634:15)
E/flutter ( 8885): <asynchronous suspension>
E/flutter ( 8885): #4      AndroidViewController.setSize (package:flutter/src/services/platform_views.dart:556:14)
E/flutter ( 8885): <asynchronous suspension>
E/flutter ( 8885): #5      RenderAndroidView._sizePlatformView (package:flutter/src/rendering/platform_view.dart:189:29)
E/flutter ( 8885): <asynchronous suspension>
E/flutter ( 8885): #6      RenderAndroidView.performResize (package:flutter/src/rendering/platform_view.dart:170:5)
E/flutter ( 8885): #7      RenderObject.layout (package:flutter/src/rendering/object.dart:1605:9)
E/flutter ( 8885): #8      MultiChildLayoutDelegate.layoutChild (package:flutter/src/rendering/custom_layout.dart:142:11)
E/flutter ( 8885): #9      _ScaffoldLayout.performLayout (package:flutter/src/material/scaffold.dart:443:7)
E/flutter ( 8885): #10     MultiChildLayoutDelegate._callPerformLayout (package:flutter/src/rendering/custom_layout.dart:212:7)
E/flutter ( 8885): #11     RenderCustomMultiChildLayoutBox.performLayout (package:flutter/src/rendering/custom_layout.dart:356:14)
E/flutter ( 8885): #12     RenderObject.layout (package:flutter/src/rendering/object.dart:1620:7)
E/flutter ( 8885): #13     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
E/flutter ( 8885): #14     RenderObject.layout (package:flutter/src/rendering/object.dart:1620:7)
E/flutter ( 8885): #15     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
E/flutter ( 8885): #16     _RenderCustomClip.performLayout (package:flutter/src/rendering/proxy_box.dart:1214:11)
E/flutter ( 8885): #17     RenderObject.layout (package:flutter/src/rendering/object.dart:1620:7)
E/flutter ( 8885): #18     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
E/flutter ( 8885): #19     RenderObject.layout (package:flutter/src/rendering/object.dart:1620:7)
E/flutter ( 8885): #20     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
E/flutter ( 8885): #21     RenderObject.layout (package:flutter/src/rendering/object.dart:1620:7)
E/flutter ( 8885): #22     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
E/flutter ( 8885): #23     RenderObject.layout (package:flutter/src/rendering/object.dart:1620:7)
E/flutter ( 8885): #24     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
E/flutter ( 8885): #25     RenderObject.layout (package:flutter/src/rendering/object.dart:1620:7)
E/flutter ( 8885): #26     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
E/flutter ( 8885): #27     RenderObject.layout (package:flutter/src/rendering/object.dart:1620:7)
E/flutter ( 8885): #28     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
E/flutter ( 8885): #29     RenderObject.layout (package:flutter/src/rendering/object.dart:1620:7)
E/flutter ( 8885): #30     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
E/flutter ( 8885): #31     RenderObject.layout (package:flutter/src/rendering/object.dart:1620:7)
E/flutter ( 8885): #32     RenderOffstage.performLayout (package:flutter/src/rendering/proxy_box.dart:3074:14)
E/flutter ( 8885): #33     RenderObject.layout (package:flutter/src/rendering/object.dart:1620:7)
E/flutter ( 8885): #34     RenderStack.performLayout (package:flutter/src/rendering/stack.dart:510:15)
E/flutter ( 8885): #35     RenderObject._layoutWithoutResize (package:flutter/src/rendering/object.dart:1497:7)
E/flutter ( 8885): #36     PipelineOwner.flushLayout (package:flutter/src/render
D/        ( 8885): HostConnection::get() New Host Connection established 0x6e360140, tid 10007
I/zygote  ( 8885): Background concurrent copying GC freed 107013(3MB) AllocSpace objects, 46(1644KB) LOS objects, 30% free, 13MB/19MB, paused 253us total 195.557ms

```

## my code calling map
```
Widget build(BuildContext context) {
    return new Scaffold(
      body: GoogleMap(
        initialCameraPosition: _kGooglePlex,
        onMapCreated: (GoogleMapController controller) {
          _controller = controller;
          _controller.setMapStyle(style);
        },
      ),
    );
  }
```

## My style
```
 [
    {
      "elementType": "geometry",
      "stylers": [
        {
          "color": "#f5f5f5"
        }
      ]
    },
    {
      "elementType": "labels.icon",
      "stylers": [
        {
          "visibility": "off"
        }
      ]
    },
    {
      "elementType": "labels.text.fill",
      "stylers": [
        {
          "color": "#616161"
        }
      ]
    },
    {
      "elementType": "labels.text.stroke",
      "stylers": [
        {
          "color": "#f5f5f5"
        }
      ]
    },
    {
      "featureType": "administrative.land_parcel",
      "elementType": "labels.text.fill",
      "stylers": [
        {
          "color": "#bdbdbd"
        }
      ]
    },
    {
      "featureType": "poi",
      "elementType": "geometry",
      "stylers": [
        {
          "color": "#eeeeee"
        }
      ]
    },
    {
      "featureType": "poi",
      "elementType": "labels.text.fill",
      "stylers": [
        {
          "color": "#757575"
        }
      ]
    },
    {
      "featureType": "poi.park",
      "elementType": "geometry",
      "stylers": [
        {
          "color": "#e5e5e5"
        }
      ]
    },
    {
      "featureType": "poi.park",
      "elementType": "labels.text.fill",
      "stylers": [
        {
          "color": "#9e9e9e"
        }
      ]
    },
    {
      "featureType": "road",
      "elementType": "geometry",
      "stylers": [
        {
          "color": "#ffffff"
        }
      ]
    },
    {
      "featureType": "road.arterial",
      "elementType": "labels.text.fill",
      "stylers": [
        {
          "color": "#757575"
        }
      ]
    },
    {
      "featureType": "road.highway",
      "elementType": "geometry",
      "stylers": [
        {
          "color": "#dadada"
        }
      ]
    },
    {
      "featureType": "road.highway",
      "elementType": "labels.text.fill",
      "stylers": [
        {
          "color": "#616161"
        }
      ]
    },
    {
      "featureType": "road.local",
      "elementType": "labels.text.fill",
      "stylers": [
        {
          "color": "#9e9e9e"
        }
      ]
    },
    {
      "featureType": "transit.line",
      "elementType": "geometry",
      "stylers": [
        {
          "color": "#e5e5e5"
        }
      ]
    },
    {
      "featureType": "transit.station",
      "elementType": "geometry",
      "stylers": [
        {
          "color": "#eeeeee"
        }
      ]
    },
    {
      "featureType": "water",
      "elementType": "geometry",
      "stylers": [
        {
          "color": "#c9c9c9"
        }
      ]
    },
    {
      "featureType": "water",
      "elementType": "labels.text.fill",
      "stylers": [
        {
          "color": "#9e9e9e"
        }
      ]
    }
  ]
```

i apreciate all help 
thanks

**Comment by farhanrahmadi** [comment]
Sorry my bad i should convert style to json first
