### ISSUE TITLE
flutter run fails (crashes) if installed apk is --deploy

### ISSUE THREAD

**Issue by eseidelGoogle** [flutter/flutter#3455]
```
flutter build apk --release
flutter install
flutter run
```

```
I/ActivityManager(  756): Displayed io.flutter.MaterialGallery/org.domokit.sky.shell.SkyActivity: +654ms
--------- beginning of crash
F/libc    (23823): Fatal signal 11 (SIGSEGV), code 1, fault addr 0xb in tid 23873 (ui_thread)
I/flutter (23823): Observatory listening on http://127.0.0.1:51519
I/flutter (23823): Diagnostic server listening on http://127.0.0.1:39809
I/MicrophoneInputStream( 1389): mic_close gfk@21b9dbeb
I/DEBUG   (  187): *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
I/DEBUG   (  187): Build fingerprint: 'google/hammerhead/hammerhead:5.1/LMY06B/1666863:userdebug/dev-keys'
I/DEBUG   (  187): Revision: '11'
I/DEBUG   (  187): ABI: 'arm'
I/DEBUG   (  187): pid: 23823, tid: 23873, name: ui_thread  >>> io.flutter.MaterialGallery <<<
I/DEBUG   (  187): signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0xb
I/DEBUG   (  187):     r0 0000001f  r1 a280cdb0  r2 0000000e  r3 00000000
I/DEBUG   (  187):     r4 a280aafc  r5 a3add640  r6 a3add5c8  r7 00000000
I/DEBUG   (  187):     r8 a280b1ac  r9 0000000e  sl a280b19c  fp a3add5c8
I/DEBUG   (  187):     ip a3adbd7c  sp a280aa60  lr a333b3f1  pc a3342606  cpsr 400d0030
I/DEBUG   (  187): 
I/DEBUG   (  187): backtrace:
I/DEBUG   (  187):     #00 pc 0043c606  /data/app/io.flutter.MaterialGallery-2/lib/arm/libsky_shell.so
I/DEBUG   (  187):     #01 pc 00464733  /data/app/io.flutter.MaterialGallery-2/lib/arm/libsky_shell.so
I/DEBUG   (  187):     #02 pc 0048b3f7  /data/app/io.flutter.MaterialGallery-2/lib/arm/libsky_shell.so
I/DEBUG   (  187):     #03 pc 003b3647  /data/app/io.flutter.MaterialGallery-2/lib/arm/libsky_shell.so
I/DEBUG   (  187):     #04 pc 003b6c09  /data/app/io.flutter.MaterialGallery-2/lib/arm/libsky_shell.so
I/DEBUG   (  187):     #05 pc 003b71e9  /data/app/io.flutter.MaterialGallery-2/lib/arm/libsky_shell.so
I/DEBUG   (  187):     #06 pc 003b7341  /data/app/io.flutter.MaterialGallery-2/lib/arm/libsky_shell.so
I/DEBUG   (  187):     #07 pc 0000019c  <unknown>
D/audio_hw_primary(  190): disable_audio_route: reset and update mixer path: audio-record
D/audio_hw_primary(  190): disable_snd_device: snd_device(55: voice-rec-mic)
I/HotwordRecognitionRnr( 1389): Hotword detection finished
I/HotwordRecognitionRnr( 1389): Stopping hotword detection.
I/DEBUG   (  187): 
I/DEBUG   (  187): Tombstone written to: /data/tombstones/tombstone_04
I/BootReceiver(  756): Copying /data/tombstones/tombstone_04 to DropBox (SYSTEM_TOMBSTONE)
W/ActivityManager(  756):   Force finishing activity 1 io.flutter.MaterialGallery/org.domokit.sky.shell.SkyActivity
W/InputDispatcher(  756): channel '12395030 io.flutter.MaterialGallery/org.domokit.sky.shell.SkyActivity (server)' ~ Consumer closed input channel or an error occurred.  events=0x9
E/InputDispatcher(  756): channel '12395030 io.flutter.MaterialGallery/org.domokit.sky.shell.SkyActivity (server)' ~ Channel is unrecoverably broken and will be disposed!
I/WindowState(  756): WIN DEATH: Window{12395030 u0 io.flutter.MaterialGallery/org.domokit.sky.shell.SkyActivity}
W/InputDispatcher(  756): Attempted to unregister already unregistered input channel '12395030 io.flutter.MaterialGallery/org.domokit.sky.shell.SkyActivity (server)'
I/WindowState(  756): WIN DEATH: Window{18bb83eb u0 SurfaceView}
I/Zygote  (  201): Process 23823 exited due to signal (11)
W/ActivityManager(  756): Exception thrown during pause
W/ActivityManager(  756): android.os.DeadObjectException
W/ActivityManager(  756): 	at android.os.BinderProxy.transactNative(Native Method)
W/ActivityManager(  756): 	at android.os.BinderProxy.transact(Binder.java:496)
W/ActivityManager(  756): 	at android.app.ApplicationThreadProxy.schedulePauseActivity(ApplicationThreadNative.java:704)
W/ActivityManager(  756): 	at com.android.server.am.ActivityStack.startPausingLocked(ActivityStack.java:825)
W/ActivityManager(  756): 	at com.android.server.am.ActivityStack.finishActivityLocked(ActivityStack.java:2726)
W/ActivityManager(  756): 	at com.android.server.am.ActivityStack.finishTopRunningActivityLocked(ActivityStack.java:2583)
W/ActivityManager(  756): 	at com.android.server.am.ActivityStackSupervisor.finishTopRunningActivityLocked(ActivityStackSupervisor.java:2478)
W/ActivityManager(  756): 	at com.android.server.am.ActivityManagerService.handleAppCrashLocked(ActivityManagerService.java:11467)
W/ActivityManager(  756): 	at com.android.server.am.ActivityManagerService.makeAppCrashingLocked(ActivityManagerService.java:11364)
W/ActivityManager(  756): 	at com.android.server.am.ActivityManagerService.crashApplication(ActivityManagerService.java:12048)
W/ActivityManager(  756): 	at com.android.server.am.ActivityManagerService.handleApplicationCrashInner(ActivityManagerService.java:11559)
W/ActivityManager(  756): 	at com.android.server.am.NativeCrashListener$NativeCrashReporter.run(NativeCrashListener.java:86)
E/lowmemorykiller(  171): Error opening /proc/23823/oom_score_adj; errno=2
I/ActivityManager(  756): Process io.flutter.MaterialGallery (pid 23823) has died
```

**Comment by eseidelGoogle** [comment]
Assuming this is fixed.
