### ISSUE TITLE
FileSystemException when bin/cache is read-only

### ISSUE THREAD

**Issue by ruuda** [flutter/flutter#34566]
I am trying to package Flutter for [Nixpkgs](https://github.com/nixos/nixpkgs). Nixpkgs stores binaries in a read-only directory. I don't suppose Flutter intends to support this, but `flutter` asked me to file a bug report, so here it is.

## Steps to Reproduce

1. Save the following to `default.nix`:

```nix
with import (fetchTarball {
  url = "https://github.com/NixOS/nixpkgs/archive/7815c86c104a99417db844791dcda34fe7a7965f.tar.gz";
  sha256 = "0k6ws2b2b6vrvq2g5h8fi8qscb0wk0wy097cnf36f9acd126k43j";
}) {};

stdenv.mkDerivation rec {
  version = "1.5.4-hotfix.2";
  name = "flutter-${version}";
  src = fetchTarball {
    url = "https://storage.googleapis.com/flutter_infra/releases/stable/linux/flutter_linux_v${version}-stable.tar.xz";
    sha256 = "0lj4yh2f0kb8p2964fr3ax9f1ra05kvv7vhr8qlwj8jszpbq662n";
  };
  buildInputs = [ bash curl git coreutils lzma libGLU ];
  buildCommand = "ln -s $src $out";
}
```
2. Run [`nix run`](https://nixos.org/nix/) in the directory where `default.nix` resides.
3. Run `flutter`.

## command

flutter 

## exception

FileSystemException: FileSystemException: Cannot open file, path = '/nix/store/zw091dp4cp17p62jrnn6vqs3gqn03kv0-source/bin/cache/lockfile' (OS Error: Permission denied, errno = 13)

```
#0      _File.open.<anonymous closure> (dart:io/file_impl.dart:364:9)
#1      _rootRunUnary (dart:async/zone.dart:1132:38)
#2      _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#3      _FutureListener.handleValue (dart:async/future_impl.dart:126:18)
#4      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:639:45)
#5      Future._propagateToListeners (dart:async/future_impl.dart:668:32)
#6      Future._completeWithValue (dart:async/future_impl.dart:483:5)
#7      Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:513:7)
#8      _rootRun (dart:async/zone.dart:1124:13)
#9      _CustomZone.run (dart:async/zone.dart:1021:19)
#10     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:947:23)
#11     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#12     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#13     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:115:13)
#14     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:5)
```

## flutter doctor

```
[!] Flutter (Channel stable, v1.5.4-hotfix.2, on Linux, locale en_GB.UTF8)
    • Flutter version 1.5.4-hotfix.2 at /nix/store/zw091dp4cp17p62jrnn6vqs3gqn03kv0-source
    • Framework revision 7a4c33425d (7 weeks ago), 2019-04-29 11:05:24 -0700
    • Engine revision 52c7a1e849
    • Dart version 2.3.0 (build 2.3.0-dev.0.5 a1668566e5)
    ✗ Downloaded executables cannot execute on host.
      See https://github.com/flutter/flutter/issues/6207 for more information
      On Debian/Ubuntu/Mint: sudo apt-get install lib32stdc++6
      On Fedora: dnf install libstdc++.i686
      On Arch: pacman -S lib32-gcc-libs


[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/setup/#android-setup for detailed instructions).
      If the Android SDK has been installed to a custom location, set ANDROID_HOME to that location.
      You may also want to add it to your PATH environment variable.


[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/setup/#android-setup for detailed instructions).

[!] Connected device
    ! No devices available

! Doctor found issues in 4 categories.
```

**Comment by jonahwilliams** [comment]
Flutter can't function without write permissions in it's installation root. I recommend using an official distribution and installing somewhere with write permissions
