### ISSUE TITLE
error during perform resize

### ISSUE THREAD

**Issue by eyalkutz** [flutter/flutter#34593]
## Steps to Reproduce

1. my code:
```dart
import 'package:flutter/material.dart';
import 'dart:math';
import 'dart:async';
import 'package:flutter/services.dart' show rootBundle;
import 'dart:convert';
import 'package:flutter/scheduler.dart' show timeDilation;

void main() {
  //timeDilation = 0.2;
  runApp(MyApp());
}

Future<String> loadAsset(String path) async {
  //return Future.delayed(Duration(seconds: 1),()=>rootBundle.loadString(path));
  return rootBundle.loadString(path);
}

Future<AssetImage> loadImage(String path) async {
  return Future(() => AssetImage(path));
}

class MyApp extends StatelessWidget {
  @override
  Widget build(buid_context) {
    return MaterialApp(
        home: Scaffold(
            appBar: AppBar(
              title: Text('Books'),
            ),
            body: Material(
                //color: Colors.green,
                child: HomeScreen())));
  }
}

class HomeScreen extends StatelessWidget {
  @override
  Color random_color() {
    return Color((Random().nextDouble() * 0xFFFFFF).toInt() << 0)
        .withOpacity(1.0);
  }

  List<List<Color>> random_colors() {
    List<List<Color>> all = [];
    List<Color> row = [];
    for (var i = 0; i < 20; i++) {
      for (var j = 0; j < 20; j++) {
        row.add(random_color());
      }
      all.add(row);
      row = [];
    }
    return all;
  }

  Widget build(context) {
    List<Widget> vertical = [];
    List<Widget> horizontal = [];
    var colors = random_colors();
    for (var i = 0; i < 20; i++) {
      for (var j = 0; j < 20; j++) {
        horizontal.add(Thambnail('pride_and_prejudice'));
      }
      vertical.add(
        Container(
          padding: EdgeInsets.all(5.0),
          child: Card(
            elevation: 10.0,
            shape: RoundedRectangleBorder(
                borderRadius: BorderRadius.circular(15.0)),
            child: Column(
              children: <Widget>[
                Container(
                    padding: EdgeInsets.all(10.0),
                    alignment: Alignment.topLeft,
                    child: Align(
                      alignment: Alignment(-0.9, -0.9),
                      child: Text('Genre $i'),
                    )),
                Container(
                  height: 150,
                  child: ListView(
                      scrollDirection: Axis.horizontal, children: horizontal),
                ),
              ],
            ),
          ),
        ),
      );
      horizontal = [];
    }
    return ListView(
      children: vertical,
    );
  }
}

class Thambnail extends StatelessWidget {
  final String book;
  Thambnail(this.book);
  @override
  Widget build(BuildContext context) {
    return Padding(
          padding: const EdgeInsets.all(8.0),
    child: Column(
      children: <Widget>[
        GestureDetector(
            onTap: () {
              return Navigator.push(
                  context,
                  MaterialPageRoute(
                      builder: (context) => BookView(
                            book: book,
                          )));
            },
            child: ClipRRect(
              borderRadius: BorderRadius.circular(15.0),
              child: Hero(
                tag: book,
                child: Container(
                  width: 70,
                  child: FittedBox(
                      fit: BoxFit.fill,
                      child:
                          Image.asset('assets/$book/cover.jpg')),
                ),
              ),
            ),
          ),
          Text(book)
          ],
        )
        
        ); 
  }
}



class BookView extends StatelessWidget {
  Future<String> text;
  Image image;
  final Color color;
  final String book;

  BookView({this.color, this.book}) {
    image = Image.asset('assets/$book/cover.jpg');
    text = loadAsset('assets/$book/content.txt');
  }

  List<Widget> seperateLines(String text,
      {TextStyle style = const TextStyle()}) {
    try {
      List<String> lines = LineSplitter().convert(text);
      List<Widget> texts = [];
      for (var line in lines) {
        texts.add(Padding(
          padding: const EdgeInsets.fromLTRB(8.0, 3.0, 8.0, 3.0),
          child: Text(line),
        ));
      }
      print(lines);
      texts.add(Container(
        height: 20,
      ));
      return texts;
    } catch (Exception) {
      print('seperate_lines ERROR');
      return [
        Text(
          'The function "seperate_lines" errored',
          style: style,
        )
      ];
    }
  }

  Widget cover(double width, double height) {
    return Hero(
      tag: book,
      child: Container(
        width: width,
        height: height,
        color: color,
        child: FittedBox(fit: BoxFit.fill, child: image),
      ),
    );
  }

  @override
  Widget build(BuildContext context) {
    var width = MediaQuery.of(context).size.width; //width of the screen
    var height = MediaQuery.of(context).size.height; //height of the screen
    return Material(
      child: FutureBuilder(
          future: text,
          builder: (BuildContext context, AsyncSnapshot<String> snapshot) {
            if (snapshot.connectionState == ConnectionState.done) {
              return ListView(
                children: <Widget>[
                  cover(width, height),
                  ...seperateLines(snapshot.data,
                      style: TextStyle(fontSize: 200))
                ],
              );
            } else {
              return ListView(
                children: <Widget>[
                  cover(width, height),
                  Container(
                    height: 1000,
                  ),
                ],
              );
            }
          }),
    );
  }
}
```
3. produces the error when I click on a thambnail
4. the error:
```
I/flutter (19179):   ← ⋯
I/flutter (19179):   parentData: <none> (can use size)
I/flutter (19179):   constraints: BoxConstraints(w=70.0, 0.0<=h<=Infinity)
I/flutter (19179):   size: MISSING
I/flutter (19179):   fit: fill
I/flutter (19179):   alignment: center
I/flutter (19179):   textDirection: ltr
I/flutter (19179): This RenderObject had the following descendants (showing up to depth 5):
I/flutter (19179):   RenderSemanticsAnnotations#fd308 relayoutBoundary=up12 NEEDS-PAINT
I/flutter (19179):     RenderImage#db9c0 relayoutBoundary=up13 NEEDS-PAINT
I/flutter (19179): 
```
## Logs

```
[  +26 ms] executing: [C:\developement\flutter\] git log -n 1 --pretty=format:%H
[  +72 ms] Exit code 0 from: git log -n 1 --pretty=format:%H
[        ] 7a4c33425ddd78c54aba07d86f3f9a4a0051769b
[        ] executing: [C:\developement\flutter\] git describe --match v*.*.* --first-parent --long --tags
[  +49 ms] Exit code 0 from: git describe --match v*.*.* --first-parent --long --tags
[        ] v1.5.4-hotfix.2-0-g7a4c33425
[  +13 ms] executing: [C:\developement\flutter\] git rev-parse --abbrev-ref --symbolic @{u}
[  +43 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/stable
[        ] executing: [C:\developement\flutter\] git ls-remote --get-url origin
[  +38 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[  +76 ms] executing: [C:\developement\flutter\] git rev-parse --abbrev-ref HEAD
[  +41 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] stable
[  +37 ms] executing: C:\developement\AndroidSdk\platform-tools\adb.exe devices -l
[  +25 ms] Exit code 0 from: C:\developement\AndroidSdk\platform-tools\adb.exe devices -l
[   +1 ms] List of devices attached
[  +28 ms] No connected devices.
[  +13 ms] "flutter run" took 142ms.
[        ] "flutter run" took 142ms.

#0      throwToolExit (package:flutter_tools/src/base/common.dart:24:3)
#1      RunCommand.validateCommand (package:flutter_tools/src/commands/run.dart:257:7)
<asynchronous suspension>
#2      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:538:11)
<asynchronous suspension>
#3      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:495:33)
<asynchronous suspension>
#4      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:142:29)
<asynchronous suspension>
#5      _rootRun (dart:async/zone.dart:1124:13)
#6      _CustomZone.run (dart:async/zone.dart:1021:19)
#7      _runZoned (dart:async/zone.dart:1516:10)
#8      runZoned (dart:async/zone.dart:1463:12)
#9      AppContext.run (package:flutter_tools/src/base/context.dart:141:18)
<asynchronous suspension>
#10     FlutterCommand.run (package:flutter_tools/src/runner/flutter_command.dart:486:20)
#11     CommandRunner.runCommand (package:args/command_runner.dart:196:27)
<asynchronous suspension>
#12     FlutterCommandRunner.runCommand.<anonymous closure>
(package:flutter_tools/src/runner/flutter_command_runner.dart:396:21)
<asynchronous suspension>
#13     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:142:29)
<asynchronous suspension>
#14     _rootRun (dart:async/zone.dart:1124:13)
#15     _CustomZone.run (dart:async/zone.dart:1021:19)
#16     _runZoned (dart:async/zone.dart:1516:10)
#17     runZoned (dart:async/zone.dart:1463:12)
#18     AppContext.run (package:flutter_tools/src/base/context.dart:141:18)
<asynchronous suspension>
#19     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:356:19)
<asynchronous suspension>
#20     CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:111:29)
#21     new Future.sync (dart:async/future.dart:224:31)
#22     CommandRunner.run (package:args/command_runner.dart:111:11)
#23     FlutterCommandRunner.run (package:flutter_tools/src/runner/flutter_command_runner.dart:242:18)
#24     run.<anonymous closure> (package:flutter_tools/runner.dart:60:20)
<asynchronous suspension>
#25     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:142:29)
<asynchronous suspension>
#26     _rootRun (dart:async/zone.dart:1124:13)
#27     _CustomZone.run (dart:async/zone.dart:1021:19)
#28     _runZoned (dart:async/zone.dart:1516:10)
#29     runZoned (dart:async/zone.dart:1463:12)
#30     AppContext.run (package:flutter_tools/src/base/context.dart:141:18)
<asynchronous suspension>
#31     runInContext (package:flutter_tools/src/context_runner.dart:50:24)
<asynchronous suspension>
#32     run (package:flutter_tools/runner.dart:51:10)
#33     main (package:flutter_tools/executable.dart:60:9)
<asynchronous suspension>
#34     main (file:///C:/b/s/w/ir/k/archive/flutter/packages/flutter_tools/bin/flutter_tools.dart:8:3)
#35     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:298:32)
#36     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:171:12)




C:\developement\flutter_books>
```

```
Analyzing flutter_books...

   info - Unused import: 'dart:async' - assets\organizer.dart:3:8 - unused_import
   info - The value of the local variable 'exp' isn't used - assets\organizer.dart:7:7 - unused_local_variable
   info - Unused import: 'dart:async' - build\app\intermediates\flutter\debug\flutter_assets\assets\organizer.dart:3:8 -
          unused_import
   info - The value of the local variable 'exp' isn't used -
          build\app\intermediates\flutter\debug\flutter_assets\assets\organizer.dart:7:7 - unused_local_variable
   info - Unused import: 'dart:async' - build\app\intermediates\flutter\release\flutter_assets\assets\organizer.dart:3:8
          - unused_import
   info - The value of the local variable 'exp' isn't used -
          build\app\intermediates\flutter\release\flutter_assets\assets\organizer.dart:7:7 - unused_local_variable
   info - Unused import: 'dart:async' -
          build\app\intermediates\merged_assets\debug\mergeDebugAssets\out\flutter_assets\assets\organizer.dart:3:8 -
          unused_import
   info - The value of the local variable 'exp' isn't used -
          build\app\intermediates\merged_assets\debug\mergeDebugAssets\out\flutter_assets\assets\organizer.dart:7:7 -
          unused_local_variable
   info - Unused import: 'dart:async' -
          build\app\intermediates\merged_assets\release\mergeReleaseAssets\out\flutter_assets\assets\organizer.dart:3:8
          - unused_import
   info - The value of the local variable 'exp' isn't used -
          build\app\intermediates\merged_assets\release\mergeReleaseAssets\out\flutter_assets\assets\organizer.dart:7:7
          - unused_local_variable
   info - Unused import: 'package:flutter/scheduler.dart' - lib\main.dart:6:8 - unused_import
   info - Name non-constant identifiers using lowerCamelCase - lib\main.dart:24:16 - non_constant_identifier_names
   info - Method doesn't override an inherited method - lib\main.dart:38:9 - override_on_non_overriding_method
   info - Name non-constant identifiers using lowerCamelCase - lib\main.dart:38:9 - non_constant_identifier_names
   info - Name non-constant identifiers using lowerCamelCase - lib\main.dart:43:21 - non_constant_identifier_names
   info - The value of the local variable 'colors' isn't used - lib\main.dart:59:9 - unused_local_variable
   info - This class (or a class which this class inherits from) is marked as '@immutable', but one or more of its
          instance fields are not final: BookView.text, BookView.image - lib\main.dart:257:7 - must_be_immutable
   info - The for, if and spread elements were not supported until version 2.2.2, but this code is required to be able
          to run on earlier versions - lib\main.dart:319:19 - sdk_version_ui_as_code

18 issues found. (ran in 9.5s)
```

```
[√] Flutter (Channel stable, v1.5.4-hotfix.2, on Microsoft Windows [Version 10.0.17134.829], locale en-US)
    • Flutter version 1.5.4-hotfix.2 at C:\developement\flutter
    • Framework revision 7a4c33425d (7 weeks ago), 2019-04-29 11:05:24 -0700
    • Engine revision 52c7a1e849
    • Dart version 2.3.0 (build 2.3.0-dev.0.5 a1668566e5)

[!] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at C:\developement\AndroidSdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = C:\developement\AndroidSdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
    X Android license status unknown.
      Try re-installing or updating your Android SDK Manager.
      See https://developer.android.com/studio/#downloads or visit https://flutter.dev/setup/#android-setup for detailed
      instructions.

[√] Android Studio (version 3.4)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 36.0.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

[√] VS Code (version 1.35.0)
    • VS Code at C:\Users\אייל קוץ\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.1.0

[√] Connected device (1 available)
    • ONEPLUS A6003 • 29484b14 • android-arm64 • Android 9 (API 28)

! Doctor found issues in 1 category.
```

**Comment by janmoppel** [comment]
Hello @eyalkutz !

Did you manage to solve the issue? Does the problem still persist in the latest stable version?

**Comment by iapicca** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
  
Thanks for your contribution.
