### ISSUE TITLE
flutter create crashing with latest 1.5.4 upgrade

### ISSUE THREAD

**Issue by narodnik** [flutter/flutter#34661]
My setup is perfectly fine. It was working before I upgraded to latest flutter.

## Steps to Reproduce

Run flutter create command

## Logs

```
$ flutter --version
Flutter 1.5.4-hotfix.2 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 7a4c33425d (7 weeks ago) • 2019-04-29 11:05:24 -0700
Engine • revision 52c7a1e849
Tools • Dart 2.3.0 (build 2.3.0-dev.0.5 a1668566e5)
$ flutter create new_project
Creating project new_project...
  new_project/README.md (created)
  new_project/android/app/build.gradle (created)
  new_project/android/app/src/main/java/com/example/new_project/MainActivity.java (created)
  new_project/android/new_project_android.iml (created)
  new_project/android/build.gradle (created)
  new_project/new_project.iml (created)
  new_project/test/widget_test.dart (created)
  new_project/ios/Flutter/Release.xcconfig (created)
  new_project/ios/Flutter/AppFrameworkInfo.plist (created)
  new_project/ios/Flutter/Debug.xcconfig (created)
  new_project/ios/Runner/Base.lproj/Main.storyboard (created)
  new_project/ios/Runner/Base.lproj/LaunchScreen.storyboard (created)
  new_project/ios/Runner/Assets.xcassets/LaunchImage.imageset/LaunchImage@2x.png (created)
  new_project/ios/Runner/Assets.xcassets/LaunchImage.imageset/LaunchImage@3x.png (created)
  new_project/ios/Runner/Assets.xcassets/LaunchImage.imageset/LaunchImage.png (created)
  new_project/ios/Runner/Assets.xcassets/LaunchImage.imageset/README.md (created)
  new_project/ios/Runner/Assets.xcassets/LaunchImage.imageset/Contents.json (created)
  new_project/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-20x20@1x.png (created)
  new_project/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-29x29@3x.png (created)
  new_project/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-60x60@2x.png (created)
  new_project/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-29x29@2x.png (created)
  new_project/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-20x20@3x.png (created)
  new_project/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-40x40@3x.png (created)
  new_project/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-20x20@2x.png (created)
  new_project/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-29x29@1x.png (created)
  new_project/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-40x40@1x.png (created)
  new_project/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-76x76@1x.png (created)
  new_project/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-83.5x83.5@2x.png (created)
  new_project/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-76x76@2x.png (created)
  new_project/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-40x40@2x.png (created)
  new_project/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-1024x1024@1x.png (created)
  new_project/ios/Runner/Assets.xcassets/AppIcon.appiconset/Contents.json (created)
  new_project/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-60x60@3x.png (created)
  new_project/ios/Runner/Info.plist (created)
  new_project/ios/Runner.xcodeproj/xcshareddata/xcschemes/Runner.xcscheme (created)
  new_project/ios/Runner.xcodeproj/project.xcworkspace/contents.xcworkspacedata (created)
  new_project/ios/Runner.xcworkspace/contents.xcworkspacedata (created)
  new_project/pubspec.yaml (created)
  new_project/.metadata (created)
  new_project/.gitignore (created)
  new_project/ios/Runner/AppDelegate.h (created)
  new_project/ios/Runner/main.m (created)
  new_project/ios/Runner/AppDelegate.m (created)
  new_project/ios/Runner.xcodeproj/project.pbxproj (created)
  new_project/web/index.html (created)
  new_project/.idea/workspace.xml (created)
  new_project/.idea/modules.xml (created)
  new_project/.idea/runConfigurations/main_dart.xml (created)
  new_project/.idea/libraries/KotlinJavaRuntime.xml (created)
  new_project/.idea/libraries/Dart_SDK.xml (created)
  new_project/.idea/libraries/Flutter_for_Android.xml (created)
  new_project/android/app/src/profile/AndroidManifest.xml (created)
  new_project/android/app/src/debug/AndroidManifest.xml (created)
  new_project/android/app/src/main/res/values/styles.xml (created)
  new_project/android/app/src/main/res/mipmap-mdpi/ic_launcher.png (created)
  new_project/android/app/src/main/res/mipmap-xxxhdpi/ic_launcher.png (created)
  new_project/android/app/src/main/res/mipmap-xxhdpi/ic_launcher.png (created)
  new_project/android/app/src/main/res/mipmap-xhdpi/ic_launcher.png (created)
  new_project/android/app/src/main/res/mipmap-hdpi/ic_launcher.png (created)
  new_project/android/app/src/main/res/drawable/launch_background.xml (created)
  new_project/android/app/src/main/AndroidManifest.xml (created)
  new_project/android/gradle.properties (created)

Oops; flutter has exited unexpectedly.
Sending crash report to Google.
Crash report sent (report ID: 761b0d58cb7960b0)
 
Crash report written to /home/kk/src/flutter/flutter_03.log;     
please let us know at https://github.com/flutter/flutter/issues.
```

Flutter crash report; please file at https://github.com/flutter/flutter/issues.

## command

flutter create new_project

## exception

TemplateException: Value was missing for section tag: androidX. (3:1)
{{#androidX}}
^

```
#0      Renderer._renderSection (package:mustache/src/renderer.dart:136:9)
#1      Renderer.visitSection (package:mustache/src/renderer.dart:115:7)
#2      SectionNode.accept (package:mustache/src/node.dart:63:43)
#3      Renderer.render.<anonymous closure> (package:mustache/src/renderer.dart:58:30)
#4      List.forEach (dart:core-patch/growable_array.dart:278:8)
#5      Renderer.render (package:mustache/src/renderer.dart:58:13)
#6      Template.render (package:mustache/src/template.dart:40:14)
#7      Template.renderString (package:mustache/src/template.dart:33:5)
#8      Template.render.<anonymous closure> (package:flutter_tools/src/template.dart:157:77)
#9      __InternalLinkedHashMap&_HashVMBase&MapMixin&_LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:367:8)
#10     Template.render (package:flutter_tools/src/template.dart:109:24)
#11     CreateCommand._renderTemplate (package:flutter_tools/src/commands/create.dart:575:21)
#12     CreateCommand._generateApp (package:flutter_tools/src/commands/create.dart:502:23)
<asynchronous suspension>
#13     CreateCommand.runCommand (package:flutter_tools/src/commands/create.dart:353:37)
<asynchronous suspension>
#14     FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:559:18)
<asynchronous suspension>
#15     FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:495:33)
<asynchronous suspension>
#16     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:142:29)
<asynchronous suspension>
#17     _rootRun (dart:async/zone.dart:1124:13)
#18     _CustomZone.run (dart:async/zone.dart:1021:19)
#19     _runZoned (dart:async/zone.dart:1516:10)
#20     runZoned (dart:async/zone.dart:1463:12)
#21     AppContext.run (package:flutter_tools/src/base/context.dart:141:18)
<asynchronous suspension>
#22     FlutterCommand.run (package:flutter_tools/src/runner/flutter_command.dart:486:20)
#23     CommandRunner.runCommand (package:args/command_runner.dart:196:27)
<asynchronous suspension>
#24     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:396:21)
<asynchronous suspension>
#25     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:142:29)
<asynchronous suspension>
#26     _rootRun (dart:async/zone.dart:1124:13)
#27     _CustomZone.run (dart:async/zone.dart:1021:19)
#28     _runZoned (dart:async/zone.dart:1516:10)
#29     runZoned (dart:async/zone.dart:1463:12)
#30     AppContext.run (package:flutter_tools/src/base/context.dart:141:18)
<asynchronous suspension>
#31     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:356:19)
<asynchronous suspension>
#32     CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:111:29)
#33     new Future.sync (dart:async/future.dart:224:31)
#34     CommandRunner.run (package:args/command_runner.dart:111:11)
#35     FlutterCommandRunner.run (package:flutter_tools/src/runner/flutter_command_runner.dart:242:18)
#36     run.<anonymous closure> (package:flutter_tools/runner.dart:60:20)
<asynchronous suspension>
#37     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:142:29)
<asynchronous suspension>
#38     _rootRun (dart:async/zone.dart:1124:13)
#39     _CustomZone.run (dart:async/zone.dart:1021:19)
#40     _runZoned (dart:async/zone.dart:1516:10)
#41     runZoned (dart:async/zone.dart:1463:12)
#42     AppContext.run (package:flutter_tools/src/base/context.dart:141:18)
<asynchronous suspension>
#43     runInContext (package:flutter_tools/src/context_runner.dart:50:24)
<asynchronous suspension>
#44     run (package:flutter_tools/runner.dart:51:10)
#45     main (package:flutter_tools/executable.dart:60:9)
<asynchronous suspension>
#46     main (file:///b/s/w/ir/k/archive/flutter/packages/flutter_tools/bin/flutter_tools.dart:8:3)
#47     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:298:32)
#48     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:171:12)
```

## flutter doctor

```
[✓] Flutter (Channel stable, v1.5.4-hotfix.2, on Linux, locale en_US.utf8)
    • Flutter version 1.5.4-hotfix.2 at /opt/flutter
    • Framework revision 7a4c33425d (7 weeks ago), 2019-04-29 11:05:24 -0700
    • Engine revision 52c7a1e849
    • Dart version 2.3.0 (build 2.3.0-dev.0.5 a1668566e5)

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /opt/android-sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = /opt/android-sdk
    • Java binary at: /usr/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-b03)
    • All Android licenses accepted.

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/setup/#android-setup for detailed instructions).

[!] Connected device
    ! No devices available

! Doctor found issues in 2 categories.
```

**Comment by narodnik** [comment]
Also note that everything else works. Running my existing projects, launching the emulator .etc Just creating a new one doesn't.

**Comment by jonahwilliams** [comment]
I'm not able to reproduce on 1.5.4, did you make any modifications to flutter locally?

**Comment by narodnik** [comment]
chmod -R 777 /opt/flutter/

**Comment by narodnik** [comment]
Re-installed Flutter and it works. Sorry for the bother.
