### ISSUE TITLE
Android AdMob Plugin Crash Missing Resource

### ISSUE THREAD

**Issue by caseta** [flutter/flutter#34689]
Android crashes on open as of admob plugin `^0.6.1`

`firebase_admob: ^0.9.0+1 --> CURRENT VERSION`
`firebase_admob: ^0.6.1 --> BREAKS`
`firebase_admob: ^0.5.7 --> WORKS`

I commented out all actual plugin code and only have the plugin defined in my `pubsec.yaml` and it crashes. Works fine on iOS

Stack trace:

```
2019-06-18 21:25:24.096 31490-4806/? I/Icing: IndexChimeraService.getServiceInterface callingPackage=com.google.android.gms componentName=AppsCorpus serviceId=SEARCH_CORPORA
2019-06-18 21:25:24.126 19996-20009/? E/s.nexuslaunche: No package ID ff found for ID 0xffffffff.
2019-06-18 21:25:24.128 31490-9848/? I/Icing: Usage reports ok 0, Failed Usage reports 0, indexed 0, rejected 0
2019-06-18 21:25:24.131 19996-20009/? E/IconLoader: Could not find icon drawable from resource
    android.content.res.Resources$NotFoundException: Resource ID #0xffffffff
        at android.content.res.ResourcesImpl.getValueForDensity(ResourcesImpl.java:225)
        at android.content.res.Resources.getDrawableForDensity(Resources.java:887)
        at android.content.res.Resources.getDrawable(Resources.java:827)
        at com.android.systemui.shared.recents.model.IconLoader.createNewIconForTask(SourceFile:118)
        at com.android.systemui.shared.recents.model.IconLoader.getAndInvalidateIfModified(SourceFile:94)
        at com.android.systemui.shared.recents.model.RecentsTaskLoader.getAndUpdateActivityIcon(SourceFile:325)
        at com.android.systemui.shared.recents.model.RecentsTaskLoadPlan.executePlan(SourceFile:188)
        at com.android.systemui.shared.recents.model.RecentsTaskLoader.loadTasks(SourceFile:173)
        at com.android.quickstep.RecentsModel.onTaskStackChangedBackground(SourceFile:214)
        at com.android.systemui.shared.system.TaskStackChangeListeners.onTaskStackChanged(SourceFile:80)
        at android.app.ITaskStackListener$Stub.onTransact(ITaskStackListener.java:50)
        at android.os.Binder.execTransact(Binder.java:731)
2019-06-18 21:25:24.131 19996-20009/? W/ziparchive: Unable to open '/data/app/com.MY.PACKAGE-e12umTipQfrtv-8jJMNp2w==/base.apk': No such file or directory
2019-06-18 21:25:24.131 19996-20009/? E/s.nexuslaunche: Failed to open APK '/data/app/com.MY.PACKAGE-e12umTipQfrtv-8jJMNp2w==/base.apk' I/O error
2019-06-18 21:25:24.131 19996-20009/? E/ResourcesManager: failed to add asset path /data/app/com.MY.PACKAGE-e12umTipQfrtv-8jJMNp2w==/base.apk
2019-06-18 21:25:24.131 19996-20009/? W/PackageManager: Failure retrieving resources for com.MY.PACKAGE
2019-06-18 21:25:24.149 31490-9848/? I/Icing: Usage reports ok 0, Failed Usage reports 0, indexed 0, rejected 0
```

Here's the `flutter doctor -v`:

```
[✓] Flutter (Channel stable, v1.5.4-hotfix.2, on Mac OS X 10.14.4 18E226, locale en-US)
    • Flutter version 1.5.4-hotfix.2 at /Users/administrator/Library/Flutter/flutter
    • Framework revision 7a4c33425d (7 weeks ago), 2019-04-29 11:05:24 -0700
    • Engine revision 52c7a1e849
    • Dart version 2.3.0 (build 2.3.0-dev.0.5 a1668566e5)

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/administrator/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.1, Build version 10B61
    • ios-deploy 1.9.4
    • CocoaPods version 1.6.1

[✓] Android Studio (version 3.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 31.3.1
    • Dart plugin version 181.5656
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)

[✓] Connected device (1 available)
    • Pixel 2 XL • ID • android-arm64 • Android 9 (API 28)

• No issues found!

```

**Comment by janmoppel** [comment]
Hello @caseta !

Did you manage to solve the issue? Does the problem still persist in the latest stable version?

**Comment by kroikie** [comment]
@caseta

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/1177. Any further collaboration will be done there.
