### ISSUE TITLE
XIAOMI Android 9.0  java.lang.NullPointerException: Attempt to invoke virtual method 'io.flutter.embedding.engine.renderer.FlutterRenderer io.flutter.embedding.engine.FlutterEngine.getRenderer()' on a null object reference

### ISSUE THREAD

**Issue by haibinpark** [flutter/flutter#34694]
## Steps to Reproduce

I Added Flutter to existing apps,When I open the flutter page, the application crashes.
```
class XXXActivity : FlutterActivity(), FlutterFragment.FlutterEngineProvider {


    private class IntentBuilder// Override the constructor to specify your class.
    internal constructor() : FlutterActivity.IntentBuilder(XXXActivity::class.java)

    override fun getFlutterEngine(p0: Context): FlutterEngine? {
        return cachedFlutterEngine
    }

    private fun createPluginRegistry(messenger: BinaryMessenger, activity: Activity): PluginRegistry {
        return object : PluginRegistry {
            override fun registrarFor(s: String): PluginRegistry.Registrar {
                return object : PluginRegistry.Registrar {
                    override fun activity(): Activity {
                        return activity
                    }

                    override fun context(): Context {
                        return activity
                    }

                    override fun activeContext(): Context {
                        return activity
                    }

                    override fun messenger(): BinaryMessenger {
                        return messenger
                    }

                    override fun textures(): TextureRegistry? {
                        return null
                    }

                    override fun platformViewRegistry(): PlatformViewRegistry? {
                        return null
                    }

                    override fun view(): io.flutter.view.FlutterView? {
                        return null
                    }

                    override fun lookupKeyForAsset(s: String): String? {
                        return null
                    }

                    override fun lookupKeyForAsset(s: String, s1: String): String? {
                        return null
                    }

                    override fun publish(o: Any): PluginRegistry.Registrar {
                        return this
                    }

                    override fun addRequestPermissionsResultListener(requestPermissionsResultListener: PluginRegistry.RequestPermissionsResultListener): PluginRegistry.Registrar {
                        return this
                    }

                    override fun addActivityResultListener(activityResultListener: PluginRegistry.ActivityResultListener): PluginRegistry.Registrar {
                        return this
                    }

                    override fun addNewIntentListener(newIntentListener: PluginRegistry.NewIntentListener): PluginRegistry.Registrar {
                        return this
                    }

                    override fun addUserLeaveHintListener(userLeaveHintListener: PluginRegistry.UserLeaveHintListener): PluginRegistry.Registrar {
                        return this
                    }

                    override fun addViewDestroyListener(viewDestroyListener: PluginRegistry.ViewDestroyListener): PluginRegistry.Registrar {
                        return this
                    }
                }
            }

            override fun hasPlugin(s: String): Boolean {
                return false
            }

            override fun <T> valuePublishedByPlugin(s: String): T? {
                return null
            }
        }
    }

    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        myActivity = this
        permissionsChecker = PermissionsChecker(GymchainApplaction.getInstance())
//        setContentView(R.layout.activity_vitality)
        try {
//            ButterKnife.bind(this)
        } catch (e: java.lang.Exception) {
            e.printStackTrace()
        }
        init(this as Context)
        val intentExtras = intent.extras.keySet().associateBy({ it }, { intent.extras.get(it) })
        eventChannelSink?.success(intentExtras)
        GeneratedPluginRegistrant.registerWith(createPluginRegistry(cachedFlutterEngine.dartExecutor, this))
    }



    override fun onPostResume() {
        super.onPostResume()
    }

    override fun onBackPressed() {
        super.onBackPressed()
    }

    private var locationUtils: LocationUtils? = null
    internal val PERMISSIONS = arrayOf<String>(ACCESS_FINE_LOCATION)
    private var permissionsChecker: PermissionsChecker? = null


    companion object {
        private lateinit var cachedFlutterEngine: FlutterEngine
        private var eventChannelSink: EventChannel.EventSink? = null
        private const val EVENT_CHANNEL_NAME = "pro.truongsinh.flutter.android_flutter_host/event"
        private var myActivity: XXXActivity? = null
        private var methodChannel: MethodChannel? = null
        private var isInitializeStatus = false

        @JvmStatic
        fun init(context: Context) {
            if (::cachedFlutterEngine.isInitialized && isInitializeStatus) {
                return
            }
            // Flutter must be initialized before FlutterEngines can be created.
            FlutterMain.startInitialization(context)
            FlutterMain.ensureInitializationComplete(context, arrayOf())
            isInitializeStatus = true
            // Instantiate a cachedFlutterEngine.
            cachedFlutterEngine = FlutterEngine(context)
            val eventChannel = EventChannel(cachedFlutterEngine.dartExecutor, EVENT_CHANNEL_NAME)
            eventChannel.setStreamHandler(object : EventChannel.StreamHandler {
                override fun onListen(o: Any?, eventSink: EventChannel.EventSink) {
                    eventChannelSink = eventSink
                }

                override fun onCancel(o: Any?) {
                }
            })
            initMethodChannel(context as Activity)
            if (context !is VitalityActivity) {
                val flutterEmbeddingActivityIntent = XXXActivity.createBuilder1()
                    .initialRoute("hello")
                    .build(context)
                flutterEmbeddingActivityIntent.addFlags(Intent.FLAG_ACTIVITY_NEW_TASK)
                ContextCompat.startActivity(context, flutterEmbeddingActivityIntent, null)
            }
        }

        private fun initMethodChannel(context: Activity) {
            try {
                methodChannel = MethodChannel(cachedFlutterEngine.dartExecutor, METH_CHANNEL_NAME)
                methodChannel?.setMethodCallHandler { methodCall, result ->
                    when (methodCall.method) {
                        
                    }
                }
            } catch (e: Exception) {
                e.printStackTrace()
            }
        }

        // This is the method that others will use to create
        // an Intent that launches MyFlutterActivity.
        @JvmStatic
        fun createBuilder1(): FlutterActivity.IntentBuilder {
            return IntentBuilder()
        }

        @JvmStatic
        fun setStatus(status: Boolean) {
            isInitializeStatus = status
        }
    }
}
```

## Logs

```
06-19 10:40:23.023 28481 28481 D AndroidRuntime: Shutting down VM
06-19 10:40:23.023 28481 28481 E AndroidRuntime: FATAL EXCEPTION: main
06-19 10:40:23.023 28481 28481 E AndroidRuntime: Process: com.handring.healthychain, PID: 28481
06-19 10:40:23.023 28481 28481 E AndroidRuntime: java.lang.NullPointerException: Attempt to invoke virtual method 'io.flutter.embedding.engine.renderer.FlutterRenderer io.flutter.embedding.engine.FlutterEngine.getRenderer()' on a null object reference
06-19 10:40:23.023 28481 28481 E AndroidRuntime: at io.flutter.embedding.android.FlutterView.resetWillNotDraw(FlutterView.java:438)
06-19 10:40:23.023 28481 28481 E AndroidRuntime: at io.flutter.embedding.android.FlutterView.access$000(FlutterView.java:59)
06-19 10:40:23.023 28481 28481 E AndroidRuntime: at io.flutter.embedding.android.FlutterView$1.onAccessibilityChanged(FlutterView.java:96)
06-19 10:40:23.023 28481 28481 E AndroidRuntime: at io.flutter.view.AccessibilityBridge$2.onAccessibilityStateChanged(AccessibilityBridge.java:285)
06-19 10:40:23.023 28481 28481 E AndroidRuntime: at android.view.accessibility.AccessibilityManager.lambda$notifyAccessibilityStateChanged$0(AccessibilityManager.java:1152)
06-19 10:40:23.023 28481 28481 E AndroidRuntime: at android.view.accessibility.-$$Lambda$AccessibilityManager$yzw5NYY7_MfAQ9gLy3mVllchaXo.run(Unknown Source:4)
06-19 10:40:23.023 28481 28481 E AndroidRuntime: at android.os.Handler.handleCallback(Handler.java:873)
06-19 10:40:23.023 28481 28481 E AndroidRuntime: at android.os.Handler.dispatchMessage(Handler.java:99)
06-19 10:40:23.023 28481 28481 E AndroidRuntime: at android.os.Looper.loop(Looper.java:201)
06-19 10:40:23.023 28481 28481 E AndroidRuntime: at android.app.ActivityThread.main(ActivityThread.java:6806)
06-19 10:40:23.023 28481 28481 E AndroidRuntime: at java.lang.reflect.Method.invoke(Native Method)
06-19 10:40:23.023 28481 28481 E AndroidRuntime: at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
06-19 10:40:23.023 28481 28481 E AndroidRuntime: at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:873)
```

```
```

flutter doctor -v
```
[✓] Flutter (Channel stable, v1.5.4-hotfix.2, on Mac OS X 10.13.6 17G65, locale zh-Hans-CN)
    • Flutter version 1.5.4-hotfix.2 at /Users/cc/flutter/flutter
    • Framework revision 7a4c33425d (7 weeks ago), 2019-04-29 11:05:24 -0700
    • Engine revision 52c7a1e849
    • Dart version 2.3.0 (build 2.3.0-dev.0.5 a1668566e5)

 
[!] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/cc/Downloads/android-sdk-macos
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = /Users/cc/Downloads/android-sdk-macos
    • Java binary at: /Library/Java/JavaVirtualMachines/jdk1.8.0_161.jdk/Contents/Home/bin/java
    • Java version Java(TM) SE Runtime Environment (build 1.8.0_161-b12)
    ✗ Android license status unknown.
      Try re-installing or updating your Android SDK Manager.
      See https://developer.android.com/studio/#downloads or visit https://flutter.dev/setup/#android-setup for
      detailed instructions.

[!] iOS toolchain - develop for iOS devices (Xcode 9.4.1)
    • Xcode at /Applications/Xcode9.app/Contents/Developer
    • Xcode 9.4.1, Build version 9F2000
    ✗ Verify that all connected devices have been paired with this computer in Xcode.
      If all devices have been paired, libimobiledevice and ideviceinstaller may require updating.
      To update with Brew, run:
        brew update
        brew uninstall --ignore-dependencies libimobiledevice
        brew uninstall --ignore-dependencies usbmuxd
        brew install --HEAD usbmuxd
        brew unlink usbmuxd
        brew link usbmuxd
        brew install --HEAD libimobiledevice
        brew install ideviceinstaller
    • ios-deploy 1.9.2
    ✗ ios-deploy out of date (1.9.4 is required). To upgrade with Brew:
        brew upgrade ios-deploy
    ✗ CocoaPods not installed.
        CocoaPods is used to retrieve the iOS platform side's plugin code that responds to your plugin usage on
        the Dart side.
        Without resolving iOS dependencies with CocoaPods, plugins will not work on iOS.
        For more info, see https://flutter.dev/platform-plugins
      To install:
        brew install cocoapods
        pod setup

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/setup/#android-setup for detailed instructions).

[!] IntelliJ IDEA Ultimate Edition (version 2018.1.3)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.dev/intellij-setup/#installing-the-plugins

[!] Connected device
    ! No devices available

! Doctor found issues in 5 categories.
```

**Comment by Liuzhiyang94** [comment]
I init the flutter in the `application`, try call `fun init(context: Context)` in the application?

**Comment by haibinpark** [comment]
@Liuzhiyang94 ，Thank you for your reply, I tried your way,but I still can't ,The question remains.

**Comment by BondarenkoStas** [comment]
@haibinpark is it the same while using the current flutter stable v1.9.1+hotfix.4?

**Comment by iapicca** [comment]
Hi @haibinpark 
are you still experiencing this issue with the latest stable version of flutter?
If so could you please provide your updated `flutter doctor -v` 
and your `flutter run --verbose` and a reproducible minimal code sample
or the steps to reproduce the problem.
Thank you

**Comment by TahaTesser** [comment]
Hi @haibinpark 
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.
