### ISSUE TITLE
flutter_patched_sdk_produc t.zip 404 not found

### ISSUE THREAD

**Issue by Jakevin** [flutter/flutter#34703]
1. run flutter doctor -v
2. show Download failed.
URL:
https://storage.googleapis.com/flutter_infra/flutter//flutter_patched_sdk_produc
t.zip
Error: 404 Not Found

## Logs

```
git:(beta) ✗ flutter doctor -v
Downloading common tools...
Download failed.
URL:
https://storage.googleapis.com/flutter_infra/flutter//flutter_patched_sdk_produc
t.zip
Error: 404 Not Found

#0      throwToolExit (package:flutter_tools/src/base/common.dart:24:3)
#1      _attempt (package:flutter_tools/src/base/net.dart:76:7)
<asynchronous suspension>
#2      fetchUrl (package:flutter_tools/src/base/net.dart:22:36)
<asynchronous suspension>
#3      _downloadFile (package:flutter_tools/src/cache.dart:934:37)
<asynchronous suspension>
#4      CachedArtifact._downloadArchive.<anonymous closure>
(package:flutter_tools/src/cache.dart:404:17)
<asynchronous suspension>
#5      CachedArtifact._withDownloadFile
(package:flutter_tools/src/cache.dart:433:26)
<asynchronous suspension>
#6      CachedArtifact._downloadArchive
(package:flutter_tools/src/cache.dart:400:12)
#7      CachedArtifact._downloadZipArchive
(package:flutter_tools/src/cache.dart:420:12)
#8      EngineCachedArtifact.updateInner
(package:flutter_tools/src/cache.dart:567:13)
<asynchronous suspension>
#9      CachedArtifact.update (package:flutter_tools/src/cache.dart:363:11)
<asynchronous suspension>
#10     Cache.updateAll (package:flutter_tools/src/cache.dart:287:26)
<asynchronous suspension>
#11     FlutterCommand.verifyThenRunCommand
(package:flutter_tools/src/runner/flutter_command.dart:472:19)
<asynchronous suspension>
#12     FlutterCommand.run.<anonymous closure>
(package:flutter_tools/src/runner/flutter_command.dart:424:33)
<asynchronous suspension>
#13     AppContext.run.<anonymous closure>
(package:flutter_tools/src/base/context.dart:153:29)
<asynchronous suspension>
#14     _rootRun (dart:async/zone.dart:1124:13)
#15     _CustomZone.run (dart:async/zone.dart:1021:19)
#16     _runZoned (dart:async/zone.dart:1516:10)
#17     runZoned (dart:async/zone.dart:1463:12)
#18     AppContext.run (package:flutter_tools/src/base/context.dart:152:18)
<asynchronous suspension>
#19     FlutterCommand.run
(package:flutter_tools/src/runner/flutter_command.dart:415:20)
#20     CommandRunner.runCommand (package:args/command_runner.dart:196:27)
<asynchronous suspension>
#21     FlutterCommandRunner.runCommand.<anonymous closure>
(package:flutter_tools/src/runner/flutter_command_runner.dart:396:21)
<asynchronous suspension>
#22     AppContext.run.<anonymous closure>
(package:flutter_tools/src/base/context.dart:153:29)
<asynchronous suspension>
#23     _rootRun (dart:async/zone.dart:1124:13)
#24     _CustomZone.run (dart:async/zone.dart:1021:19)
#25     _runZoned (dart:async/zone.dart:1516:10)
#26     runZoned (dart:async/zone.dart:1463:12)
#27     AppContext.run (package:flutter_tools/src/base/context.dart:152:18)
<asynchronous suspension>
#28     FlutterCommandRunner.runCommand
(package:flutter_tools/src/runner/flutter_command_runner.dart:356:19)
<asynchronous suspension>
#29     CommandRunner.run.<anonymous closure>
(package:args/command_runner.dart:111:29)
#30     new Future.sync (dart:async/future.dart:224:31)
#31     CommandRunner.run (package:args/command_runner.dart:111:11)
#32     FlutterCommandRunner.run
(package:flutter_tools/src/runner/flutter_command_runner.dart:242:18)
#33     run.<anonymous closure> (package:flutter_tools/runner.dart:60:20)
<asynchronous suspension>
#34     AppContext.run.<anonymous closure>
(package:flutter_tools/src/base/context.dart:153:29)
<asynchronous suspension>
#35     _rootRun (dart:async/zone.dart:1124:13)
#36     _CustomZone.run (dart:async/zone.dart:1021:19)
#37     _runZoned (dart:async/zone.dart:1516:10)
#38     runZoned (dart:async/zone.dart:1463:12)
#39     AppContext.run (package:flutter_tools/src/base/context.dart:152:18)
<asynchronous suspension>
#40     runInContext (package:flutter_tools/src/context_runner.dart:51:24)
<asynchronous suspension>
#41     run (package:flutter_tools/runner.dart:51:10)
#42     main (package:flutter_tools/executable.dart:59:9)
<asynchronous suspension>
#43     main
(file:///Users/jakevinlo/development/flutter/packages/flutter_tools/bin/flutter_
tools.dart:8:3)
#44     _startIsolate.<anonymous closure>
(dart:isolate-patch/isolate_patch.dart:298:32)
#45     _RawReceivePortImpl._handleMessage
(dart:isolate-patch/isolate_patch.dart:171:12)
```

**Comment by BondarenkoStas** [comment]
@Jakevin do you still have the issue? The url has two // slashes, that's why it's not found, another question how it happened. What the version of flutter do you use?

**Comment by iapicca** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
  
Thanks for your contribution.
