### ISSUE TITLE
about  ExpansionTile

### ISSUE THREAD

**Issue by crystal-lee** [flutter/flutter#34716]
## Steps to Reproduce

1. I use ExpansionTile, and it have several thousand children, so the page is very Caton  
2.I try use ListView in children, and make a mistake.  
3.what should i do

## code
```
Widget buildView(
    AccountState state, Dispatch dispatch, ViewService viewService) {
  CircleIconBuilder circleIconBuilder = CircleIconBuilder();
  return _buildPhoneChat(state, dispatch, viewService, circleIconBuilder);
}

Widget _buildPhoneChat(AccountState accountState, Dispatch dispatch,
    ViewService viewService, CircleIconBuilder circleIconBuilder) {
  return ExpansionTile(
    initiallyExpanded: accountState.friendSelect != null,
    key: PageStorageKey<AccountState>(accountState),
    title: Container(),
//    children: _buildChatContactList(accountState, dispatch, viewService, circleIconBuilder),
    children: <Widget>[
      ListView.builder(
          itemCount: 10,
          itemBuilder: (context, index) {
            println('index -- $index');
            return _buildChatContact(accountState, accountState.chatContactDataList[index], dispatch, viewService, circleIconBuilder);
          }),
    ],
  );
}

Widget _buildChatContact(
    AccountState state,
    ChatContactData chatContactData,
    Dispatch dispatch,
    ViewService viewService,
    CircleIconBuilder circleIconBuilder) {
  bool checked = state.friendSelect?.id == chatContactData.id;
  return ListTile(
    title: GestureDetector(),
    selected: checked,
  );
}

List<Widget> _buildChatContactList(AccountState state, Dispatch dispatch,
    ViewService viewService, CircleIconBuilder circleIconBuilder) {
  List<Widget> tiles = List();
  for (var chatContactData in state.chatContactDataList) {
    tiles.add(_buildChatContact(
        state, chatContactData, dispatch, viewService, circleIconBuilder));
  }
  return tiles;
}
```

## Logs

```
06-19 20:36:14.554 1661-1685/com.crystal.fish_redux_example I/flutter: ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
06-19 20:36:14.585 1661-1685/com.crystal.fish_redux_example I/flutter: The following assertion was thrown building ListView(scrollDirection: vertical, primary: using
06-19 20:36:14.585 1661-1685/com.crystal.fish_redux_example I/flutter: primary controller, AlwaysScrollableScrollPhysics, dependencies: [PrimaryScrollController,
06-19 20:36:14.585 1661-1685/com.crystal.fish_redux_example I/flutter: MediaQuery]):
06-19 20:36:14.585 1661-1685/com.crystal.fish_redux_example I/flutter: type 'bool' is not a subtype of type 'double'
06-19 20:36:14.605 1661-1685/com.crystal.fish_redux_example I/flutter: Either the assertion indicates an error in the framework itself, or we should provide substantially
06-19 20:36:14.605 1661-1685/com.crystal.fish_redux_example I/flutter: more information in this error message to help you determine and fix the underlying cause.
06-19 20:36:14.605 1661-1685/com.crystal.fish_redux_example I/flutter: In either case, please report this assertion by filing a bug on GitHub:
06-19 20:36:14.605 1661-1685/com.crystal.fish_redux_example I/flutter:   https://github.com/flutter/flutter/issues/new?template=BUG.md
06-19 20:36:14.606 1661-1685/com.crystal.fish_redux_example I/flutter: When the exception was thrown, this was the stack:
06-19 20:36:14.633 1661-1685/com.crystal.fish_redux_example I/flutter: #0      ScrollPosition.restoreScrollOffset (package:flutter/src/widgets/scroll_position.dart:356:20)
06-19 20:36:14.633 1661-1685/com.crystal.fish_redux_example I/flutter: #1      new ScrollPosition (package:flutter/src/widgets/scroll_position.dart:82:7)
06-19 20:36:14.634 1661-1685/com.crystal.fish_redux_example I/flutter: #2      new ScrollPositionWithSingleContext (package:flutter/src/widgets/scroll_position_with_single_context.dart:58:8)
06-19 20:36:14.634 1661-1685/com.crystal.fish_redux_example I/flutter: #3      ScrollableState._updatePosition (package:flutter/src/widgets/scrollable.dart:327:10)
06-19 20:36:14.634 1661-1685/com.crystal.fish_redux_example I/flutter: #4      ScrollableState.didChangeDependencies (package:flutter/src/widgets/scrollable.dart:335:5)
06-19 20:36:14.634 1661-1685/com.crystal.fish_redux_example I/flutter: #5      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3862:12)
06-19 20:36:14.634 1661-1685/com.crystal.fish_redux_example I/flutter: #6      ComponentElement.mount (package:flutter/src/widgets/framework.dart:3717:5)
06-19 20:36:14.634 1661-1685/com.crystal.fish_redux_example I/flutter: #7      Element.inflateWidget (package:flutter/src/widgets/framework.dart:2961:14)
06-19 20:36:14.634 1661-1685/com.crystal.fish_redux_example I/flutter: #8      Element.updateChild (package:flutter/src/widgets/framework.dart:2764:12)
06-19 20:36:14.634 1661-1685/com.crystal.fish_redux_example I/flutter: #9      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3750:16)
06-19 20:36:14.634 1661-1685/com.crystal.fish_redux_example I/flutter: #10     Element.rebuild (package:flutter/src/widgets/framework.dart:3565:5)
06-19 20:36:14.634 1661-1685/com.crystal.fish_redux_example I/flutter: #11     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3722:5)
06-19 20:36:14.634 1661-1685/com.crystal.fish_redux_example I/flutter: #12     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3717:5)
06-19 20:36:14.635 1661-1685/com.crystal.fish_redux_example I/flutter: #13     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2961:14)
06-19 20:36:14.635 1661-1685/com.crystal.fish_redux_example I/flutter: #14     Element.updateChild (package:flutter/src/widgets/framework.dart:2764:12)
06-19 20:36:14.635 1661-1685/com.crystal.fish_redux_example I/flutter: #15     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4876:14)
06-19 20:36:14.635 1661-1685/com.crystal.fish_redux_example I/flutter: #16     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2961:14)
06-19 20:36:14.635 1661-1685/com.crystal.fish_redux_example I/flutter: #17     MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4982:32)
06-19 20:36:14.635 1661-1685/com.crystal.fish_redux_example I/flutter: #18     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2961:14)
06-19 20:36:14.636 1661-1685/com.crystal.fish_redux_example I/flutter: #19     Element.updateChild (package:flutter/src/widgets/framework.dart:2764:12)
06-19 20:36:14.636 1661-1685/com.crystal.fish_redux_example I/flutter: #20     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4883:14)
06-19 20:36:14.636 1661-1685/com.crystal.fish_redux_example I/flutter: #21     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:15)
06-19 20:36:14.637 1661-1685/com.crystal.fish_redux_example I/flutter: #22     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4883:14)
06-19 20:36:14.637 1661-1685/com.crystal.fish_redux_example I/flutter: #23     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:15)
06-19 20:36:14.637 1661-1685/com.crystal.fish_redux_example I/flutter: #24     RenderObjectElement.updateChildren (package:flutter/src/widgets/framework.dart:4601:32)
06-19 20:36:14.637 1661-1685/com.crystal.fish_redux_example I/flutter: #25     MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4992:17)
06-19 20:36:14.638 1661-1685/com.crystal.fish_redux_example I/flutter: #26     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:15)
06-19 20:36:14.638 1661-1685/com.crystal.fish_redux_example I/flutter: #27     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4883:14)
06-19 20:36:14.638 1661-1685/com.crystal.fish_redux_example I/flutter: #28     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:15)
06-19 20:36:14.638 1661-1685/com.crystal.fish_redux_example I/flutter: #29     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4883:14)
06-19 20:36:14.638 1661-1685/com.crystal.fish_redux_example I/flutter: #30     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:15)
06-19 20:36:14.638 1661-1685/com.crystal.fish_redux_example I/flutter: #31     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3750:16)
06-19 20:36:14.638 1661-1685/com.crystal.fish_redux_example I/flutter: #32     Element.rebuild (package:flutter/src/widgets/framework.dart:3565:5)
06-19 20:36:14.638 1661-1685/com.crystal.fish_redux_example I/flutter: #33     StatelessElement.update (package:flutter/src/widgets/framework.dart:3796:5)
06-19 20:36:14.638 1661-1685/com.crystal.fish_redux_example I/flutter: #34     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:15)
06-19 20:36:14.638 1661-1685/com.crystal.fish_redux_example I/flutter: #35     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3750:16)
06-19 20:36:14.639 1661-1685/com.crystal.fish_redux_example I/flutter: #36     Element.rebuild (package:flutter/src/widgets/framework.dart:3565:5)
06-19 20:36:14.639 1661-1685/com.crystal.fish_redux_example I/flutter: #37     StatefulElement.update (package:flutter/src/widgets/framework.dart:3894:5)
06-19 20:36:14.639 1661-1685/com.crystal.fish_redux_example I/flutter: #38     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:15)
06-19 20:36:14.639 1661-1685/com.crystal.fish_redux_example I/flutter: #39     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3750:16)
06-19 20:36:14.639 1661-1685/com.crystal.fish_redux_example I/flutter: #40     Element.rebuild (package:flutter/src/widgets/framework.dart:3565:5)
06-19 20:36:14.639 1661-1685/com.crystal.fish_redux_example I/flutter: #41     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2278:33)
06-19 20:36:14.639 1661-1685/com.crystal.fish_redux_example I/flutter: #42     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding&WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:700:20)
06-19 20:36:14.639 1661-1685/com.crystal.fish_redux_example I/flutter: #43     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:286:5)
06-19 20:36:14.639 1661-1685/com.crystal.fish_redux_example I/flutter: #44     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1012:15)
06-19 20:36:14.639 1661-1685/com.crystal.fish_redux_example I/flutter: #45     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:952:9)
06-19 20:36:14.640 1661-1685/com.crystal.fish_redux_example I/flutter: #46     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:864:5)
06-19 20:36:14.640 1661-1685/com.crystal.fish_redux_example I/flutter: #50     _invoke (dart:ui/hooks.dart:219:10)
06-19 20:36:14.640 1661-1685/com.crystal.fish_redux_example I/flutter: #51     _drawFrame (dart:ui/hooks.dart:178:3)
06-19 20:36:14.640 1661-1685/com.crystal.fish_redux_example I/flutter: (elided 3 frames from package dart:async)
06-19 20:36:14.641 1661-1685/com.crystal.fish_redux_example I/flutter: ════════════════════════════════════════════════════════════════════════════════════════════════════
06-19 20:36:29.926 1661-1685/com.crystal.fish_redux_example I/flutter: Another exception was thrown: type 'bool' is not a subtype of type 'double'
06-19 20:36:35.929 1661-1685/com.crystal.fish_redux_example I/flutter: Another exception was thrown: type 'bool' is not a subtype of type 'double'

```
```

**Comment by emilioschepis** [comment]
Did you manage to find a solution?

**Comment by deadsoul44** [comment]
I have the same exception. I think there is a bug in expansion tile when it is inside list view. Stackoverflow label is wrong. There is no action for 8 months?

**Comment by VladyslavBondarenko** [comment]
Hi @crystal-lee 
Is it still an issue? 
Could you provide a [minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example)?
May be related to https://github.com/flutter/flutter/issues/36539

**Comment by iapicca** [comment]
Without additional information we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
