### ISSUE TITLE
FireBase phone auth

### ISSUE THREAD

**Issue by MeshalEnzi** [flutter/flutter#34756]
Hi, as you say on the title the auth for the phone doesn't work

here is my code:
```
Future<void> _sendCodeToPhoneNumber() async {
    final PhoneVerificationCompleted verificationCompleted = (FirebaseUser user) {
      setState(() {
        print('Inside _sendCodeToPhoneNumber: signInWithPhoneNumber auto succeeded: $user');
      });
    };

    final PhoneVerificationFailed verificationFailed = (AuthException authException) {
      setState(() {
        print('Phone number verification failed. Code: ${authException.code}. Message: ${authException.message}');}
      );
    };

    final PhoneCodeSent codeSent =
        (String verificationId, [int forceResendingToken]) async {
      this.verificationId = verificationId;
      print("code sent to " + phoneNum);
    };

    final PhoneCodeAutoRetrievalTimeout codeAutoRetrievalTimeout =
        (String verificationId) {
      this.verificationId = verificationId;
      print("time out");
    };

    await FirebaseAuth.instance.verifyPhoneNumber(
        phoneNumber: phoneController.text,
        timeout: const Duration(seconds: 5),
        verificationCompleted: verificationCompleted,
        verificationFailed: verificationFailed,
        codeSent: codeSent,
        codeAutoRetrievalTimeout: codeAutoRetrievalTimeout);
  }


  void _signInWithPhoneNumber(String smsCode) async {
    await FirebaseAuth.instance
        .signInWithPhoneNumber(
        verificationId: verificationId,
        smsCode: smsCode)
        .then((FirebaseUser user) async {
      final FirebaseUser currentUser = await FirebaseAuth.instance.currentUser();
      assert(user.uid == currentUser.uid);
      print('signed in with phone number successful: user -> $user');
    });

  }
```
============================================

here is the console:
```
[VERBOSE-2:ui_dart_state.cc(148)] Unhandled Exception: MissingPluginException(No implementation found for method verifyPhoneNumber on channel plugins.flutter.io/firebase_auth)
#0      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:300:7)
<asynchronous suspension>
#1      FirebaseAuth.verifyPhoneNumber (package:firebase_auth/firebase_auth.dart:321:19)
<asynchronous suspension>
#2      MapSampleState._sendCodeToPhoneNumber (package:maptest/main.dart:96:33)
<asynchronous suspension>
#3      MapSampleState.phoneVerify.<anonymous closure> (package:maptest/main.dart:948:25)
#4      _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:635:14)
#5      _InkResponseState.build.<anonymous closure> (package:flutter/src/material/ink_well.dart:711:32)
#6      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:181:24)
#7      TapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:352:11)
#8      TapGestureRecognizer.handle<…>
```

**Comment by BondarenkoStas** [comment]
@MeshalEnzi is it the same while using current firebase_auth 0.14.0+5?

**Comment by iapicca** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
  
Thanks for your contribution.

**Comment by rohandalvi** [comment]
I am also facing the same problem. I am using the latest firebase_auth library.

**Comment by iapicca** [comment]
Could everyone who still has this problem please file a new issue with the exact descriptions what happens, logs and the output of 'flutter doctor -v'  please.
All system setups can be slightly different so it's always better to open new issues and reference related issues.
