### ISSUE TITLE
flutter_plugin_tools analyze => FileSystemException

### ISSUE THREAD

**Issue by duzenko** [flutter/flutter#34777]
```
Antons-Mac:flutterplugins a$ pub global run flutter_plugin_tools analyze --plugins google_maps_flutter
Activating tuneup package...
Package tuneup is currently active at version 0.3.6+1.
Resolving dependencies...
+ analysis_server_lib 0.1.6
+ args 1.5.2
+ charcode 1.1.2
+ cli_util 0.1.3+2
+ collection 1.14.11
+ intl 0.15.8
+ logging 0.11.3+2
+ meta 1.1.7
+ path 1.6.2
+ source_span 1.5.5
+ string_scanner 1.0.4
+ term_glyph 1.1.0
+ tuneup 0.3.6+1
+ yaml 2.1.16
Precompiling executables...
Precompiled tuneup:tuneup.
Installed executable tuneup.
Warning: Pub installs executables into $HOME/.pub-cache/bin, which is not on your path.
You can fix that by adding this to your shell's config file (.bashrc, .bash_profile, etc.):

  export PATH="$PATH":"$HOME/.pub-cache/bin"

Activated tuneup 0.3.6+1.
Running "flutter packages get" in google_maps_flutter...            0.6s
Running "flutter packages get" in example...                        0.7s
Running "flutter packages get" in example...                        0.6s
Checking project google_maps_flutter...
Unhandled exception:
[Analyzer RequestError method: analysis.setAnalysisRoots, code: SERVER_ERROR, message: FileSystemException(path=/Users/a/Documents/flutterplugins/packages/google_maps_flutter/example/ios/.symlinks/plugins/google_maps_flutter/example/ios/.symlinks/plugins/google_maps_flutter/example/ios/.symlinks/plugins/google_maps_flutter/example/ios/.symlinks/plugins/google_maps_flutter/example/ios/.symlinks/plugins/google_maps_flutter/example/ios/.symlinks/plugins/google_maps_flutter/example/ios/.symlinks/plugins/google_maps_flutter/example/ios/.symlinks/plugins/google_maps_flutter/example/ios/.symlinks/plugins/google_maps_flutter/example/ios/.symlinks/plugins/google_maps_flutter/example/ios/.symlinks/plugins/google_maps_flutter/example/ios/.symlinks/plugins/google_maps_flutter/example/ios/.symlinks/plugins/google_maps_flutter/example/ios/.symlinks/plugins/google_maps_flutter/example/ios/.symlinks/plugins/google_maps_flutter/example/ios/.symlinks/plugins/google_maps_flutter/example/ios/.symlinks/plugins/google_maps_flutter/example/ios/Pods/GoogleMaps/Maps/Frameworks/GoogleMaps.framework/Resources/GoogleMaps.bundle/bubble_right@3x.p; message=Directory listing failed)]
#0      _rootHandleUncaughtError.<anonymous closure> (dart:async/zone.dart:1112:29)
#1      _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#2      _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#3      _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:115:13)
#4      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:5)



The following packages have analyzer errors (see above):
 * google_maps_flutter
```

**Comment by BondarenkoStas** [comment]
@duzenko Please provide your flutter doctor -v output. Do you encounter the issue while using current flutter stable v1.9.1+hotfix.4?

**Comment by duzenko** [comment]
No crash with v1.9.1+hotfix.2
What about https://github.com/flutter/flutter/issues/33964? Still crashes

**Comment by BondarenkoStas** [comment]
Closing it, if it will appear or you have new input, please comment, I will re-open the issue right away.
