### ISSUE TITLE
.flutter-plugins (OS Error: Permission denied, errno = 13)

### ISSUE THREAD

**Issue by appjitsu** [flutter/flutter#34824]
## Steps to Reproduce

Just running the app.

## pubspec.yaml

```
version: 0.4.1+6

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_auth:
  cloud_firestore:
  date_format: ^1.0.6
  auto_size_text: ^0.3.0
  flutter_bloc: ^0.7.0
  flutter_crashlytics: ^0.2.1
  camera: ^0.4.2
  path_provider: ^0.5.0+1
  meta: ^1.1.6
  equatable: ^0.1.6
  image_picker: ^0.5.0+3
  timeago: ^2.0.10
  firebase_storage: ^2.1.0+1
  chewie:
  file_picker: ^1.2.0
  flutter_full_pdf_viewer: ^1.0.4
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
   - assets/
```

## command

flutter build bundle --suppress-analytics --target .../lib/main.dart --track-widget-creation --compilation-trace-file compilation.txt --target-platform android-arm64 --depfile .../build/app/intermediates/flutter/debug/snapshot_blob.bin.d --asset-dir .../build/app/intermediates/flutter/debug/flutter_assets --debug

## exception

FileSystemException: FileSystemException: Cannot open file, path = '.../.flutter-plugins' (OS Error: Permission denied, errno = 13)

```
#0      _File.throwIfError (dart:io/file_impl.dart:643:7)
#1      _File.openSync (dart:io/file_impl.dart:487:5)
#2      _File.writeAsBytesSync (dart:io/file_impl.dart:612:31)
#3      _File.writeAsStringSync (dart:io/file_impl.dart:636:5)
#4      _LocalFile&LocalFileSystemEntity&ForwardingFile.writeAsStringSync (package:file/src/forwarding/forwarding_file.dart:147:16)
#5      _writeFlutterPluginsList (package:flutter_tools/src/plugins.dart:99:17)
#6      refreshPluginsList (package:flutter_tools/src/plugins.dart:288:24)
#7      FlutterProject.ensureReadyForPlatformSpecificTooling (package:flutter_tools/src/project.dart:164:5)
<asynchronous suspension>
#8      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:549:21)
<asynchronous suspension>
#9      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:495:33)
<asynchronous suspension>
#10     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:142:29)
<asynchronous suspension>
#11     _rootRun (dart:async/zone.dart:1124:13)
#12     _CustomZone.run (dart:async/zone.dart:1021:19)
#13     _runZoned (dart:async/zone.dart:1516:10)
#14     runZoned (dart:async/zone.dart:1463:12)
#15     AppContext.run (package:flutter_tools/src/base/context.dart:141:18)
<asynchronous suspension>
#16     FlutterCommand.run (package:flutter_tools/src/runner/flutter_command.dart:486:20)
#17     CommandRunner.runCommand (package:args/command_runner.dart:196:27)
<asynchronous suspension>
#18     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:396:21)
<asynchronous suspension>
#19     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:142:29)
<asynchronous suspension>
#20     _rootRun (dart:async/zone.dart:1124:13)
#21     _CustomZone.run (dart:async/zone.dart:1021:19)
#22     _runZoned (dart:async/zone.dart:1516:10)
#23     runZoned (dart:async/zone.dart:1463:12)
#24     AppContext.run (package:flutter_tools/src/base/context.dart:141:18)
<asynchronous suspension>
#25     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:356:19)
<asynchronous suspension>
#26     CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:111:29)
#27     new Future.sync (dart:async/future.dart:224:31)
#28     CommandRunner.run (package:args/command_runner.dart:111:11)
#29     FlutterCommandRunner.run (package:flutter_tools/src/runner/flutter_command_runner.dart:242:18)
#30     run.<anonymous closure> (package:flutter_tools/runner.dart:60:20)
<asynchronous suspension>
#31     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:142:29)
<asynchronous suspension>
#32     _rootRun (dart:async/zone.dart:1124:13)
#33     _CustomZone.run (dart:async/zone.dart:1021:19)
#34     _runZoned (dart:async/zone.dart:1516:10)
#35     runZoned (dart:async/zone.dart:1463:12)
#36     AppContext.run (package:flutter_tools/src/base/context.dart:141:18)
<asynchronous suspension>
#37     runInContext (package:flutter_tools/src/context_runner.dart:50:24)
<asynchronous suspension>
#38     run (package:flutter_tools/runner.dart:51:10)
#39     main (package:flutter_tools/executable.dart:60:9)
<asynchronous suspension>
#40     main (file:///b/s/w/ir/k/archive/flutter/packages/flutter_tools/bin/flutter_tools.dart:8:3)
#41     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:298:32)
#42     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:171:12)
```
## flutter doctor

```
[✓] Flutter (Channel stable, v1.5.4-hotfix.2, on Mac OS X 10.14.5 18F132, locale en-US)
    • Flutter version 1.5.4-hotfix.2 at /Users/jason/flutter
    • Framework revision 7a4c33425d (7 weeks ago), 2019-04-29 11:05:24 -0700
    • Engine revision 52c7a1e849
    • Dart version 2.3.0 (build 2.3.0-dev.0.5 a1668566e5)

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/user/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • ANDROID_SDK_ROOT = /Users/user/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.2.1, Build version 10E1001
    • ios-deploy 1.9.4
    • CocoaPods version 1.5.0

[✓] Android Studio (version 3.4)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 36.1.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

[✓] VS Code (version 1.35.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.1.0

[✓] Connected device (2 available)
    • Pixel XL  • HT68K0200907                         • android-arm64 • Android 9 (API 28)
    • iPhone Xʀ • CEE7AD1E-8259-4414-B615-3372D6EED2D2 • ios           • com.apple.CoreSimulator.SimRuntime.iOS-12-2 (simulator)

• No issues found!
```

**Comment by kangwang1988** [comment]
@appjitsu 
Can you delete the flutter-plugins file manually(it's expected to created automatically),and rerun 'flutter run --verbose' and paste the log here?

**Comment by appjitsu** [comment]
Yep. That is what it was. Thanks for your help.

**Comment by kangwang1988** [comment]
@appjitsu 
Can this issue be closed now, as it seems working now.

**Comment by appjitsu** [comment]
Yes. Thanks.

**Comment by Hinal1108** [comment]
> @appjitsu
> Can you delete the flutter-plugins file manually(it's expected to created automatically),and rerun 'flutter run --verbose' and paste the log here?

Thanks, it's working for me

**Comment by marv0** [comment]
> @appjitsu
> Can you delete the flutter-plugins file manually(it's expected to created automatically),and rerun 'flutter run --verbose' and paste the log here?

This did the trick for me too .thanks a lot
