### ISSUE TITLE
Crash on release mode

### ISSUE THREAD

**Issue by ksimbili** [flutter/flutter#3492]
```
══╡ EXCEPTION CAUGHT BY RENDERING LIBRARY ╞═════════════════════════════════════════════════════════
The following NoSuchMethodError was thrown during performLayout():
The null object does not have a getter 'inMicroseconds'.

NoSuchMethodError: method not found: 'inMicroseconds'
Receiver: null
Arguments: []
The following RenderObject was being processed when the exception was fired:
  _RenderLazyBlock NEEDS-LAYOUT
This RenderObject had the following descendants (showing up to depth 5):
  RenderRepaintBoundary relayoutSubtreeRoot=up1
    RenderPadding relayoutSubtreeRoot=up2
      RenderSemanticsGestureHandler relayoutSubtreeRoot=up3
        RenderPointerListener relayoutSubtreeRoot=up4
          RenderSemanticsGestureHandler relayoutSubtreeRoot=up5
  RenderRepaintBoundary relayoutSubtreeRoot=up1
    RenderPadding relayoutSubtreeRoot=up2
      RenderSemanticsGestureHandler relayoutSubtreeRoot=up3
        RenderPointerListener relayoutSubtreeRoot=up4
          RenderSemanticsGestureHandler relayoutSubtreeRoot=up5
  RenderRepaintBoundary relayoutSubtreeRoot=up1
    RenderPadding relayoutSubtreeRoot=up2
      RenderSemanticsGestureHandler relayoutSubtreeRoot=up3
        RenderPointerListener relayoutSubtreeRoot=up4
          RenderSemanticsGestureHandler relayoutSubtreeRoot=up5
  RenderRepaintBoundary relayoutSubtreeRoot=up1
    RenderPadding relayoutSubtreeRoot=up2
      RenderSemanticsGestureHandler relayoutSubtreeRoot=up3
        RenderPointerListener relayoutSubtreeRoot=up4
          RenderSemanticsGestureHandler relayoutSubtreeRoot=up5
Stack trace:
#0      Object._noSuchMethod (dart:core-patch/object_patch.dart:42)
#1      Object.noSuchMethod (dart:core-patch/object_patch.dart:45)
#2      ScrollableState.didUpdateScrollBehavior (package:flutter/src/widgets/scrollable.dart:392)
#3      _LazyBlockState._handleExtentsChanged.<anonymous closure> (package:flutter/src/widgets/lazy_block.dart:175)
#4      State.setState (package:flutter/src/widgets/framework.dart:420)
#5      _LazyBlockState._handleExtentsChanged (package:flutter/src/widgets/lazy_block.dart:174)
#6      _LazyBlockElement._layout (package:flutter/src/widgets/lazy_block.dart:652)
#7      RenderObject.invokeLayoutCallback (package:flutter/src/rendering/object.dart:1348)
#8      _RenderLazyBlock.performLayout (package:flutter/src/widgets/lazy_block.dart:376)
#9      RenderObject._layoutWithoutResize (package:flutter/src/rendering/object.dart:1146)
#10     PipelineOwner.flushLayout (package:flutter/src/rendering/object.dart:727)
#11     BindingBase&Scheduler&Gesturer&Services&Renderer.beginFrame (package:flutter/src/rendering/binding.dart:121)
#12     WidgetFlutterBinding.beginFrame (package:flutter/src/widgets/binding.dart:103)
#13     BindingBase&Scheduler&Gesturer&Services&Renderer._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:115)
#14     BindingBase&Scheduler._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:391)
#15     BindingBase&Scheduler.handleBeginFrame (package:flutter/src/scheduler/binding.dart:353)
#16     _beginFrame (file:///b/build/slave/Linux_Engine/build/src/out/Release/gen/sky/bindings/hooks.dart:48)
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
```

**Comment by Hixie** [comment]
Does this still happen if you update to tip of tree? I fixed something like this recently.

**Comment by tonygentilcore** [comment]
This is at 31d199b0ee2cfa9af4ad709d48bb6a700cb99665

**Comment by Hixie** [comment]
well bummer. We'll check it out!

**Comment by Hixie** [comment]
@abarth Yeah this is in the same spot as before. _simulation isn't null, but _controller.lastElapsedDuration is. I don't understand how this can be, looking at the code.

**Comment by tonygentilcore** [comment]
Actually, it's possible @ksimbili was running w/ code prior to that roll. He's confirming.

**Comment by ksimbili** [comment]
I just saw those crashes at 31d199b
<https://github.com/flutter/flutter/commit/31d199b0ee2cfa9af4ad709d48bb6a700cb99665>

**Comment by Hixie** [comment]
I suspect this is now manifesting as https://github.com/flutter/flutter/issues/3675.

**Comment by Hixie** [comment]
Have any of you seen the "NoSuchMethodError: method not found: 'inMicroseconds'" message in the last month or so? If so, please do reopen this bug. For now I'm going to close this and assume that the assert in #3675 is about the same underlying problem (if I recall correctly it's an assert I added when trying to pin down this issue).
