### ISSUE TITLE
Flutter MacOS desktop error

### ISSUE THREAD

**Issue by jaumard** [flutter/flutter#34930]
I having no problem on Android and iOS, but once I try to launch on macOS, I'm getting an error when I push a new route (only after my animated button finish, without animation no error).

Here is the error:
```
21:30:06.034 7 info flutter.tools  ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
21:30:06.034 8 info flutter.tools  The following assertion was thrown building InkWell(gestures: <none>, clipped to BoxShape.rectangle,
21:30:06.034 9 info flutter.tools  dependencies: [_FocusMarker, _LocalizationsScope-[GlobalKey#a999c], Directionality,
21:30:06.034 10 info flutter.tools  _InheritedTheme], state: _InkResponseState<InkResponse>#779ff):
21:30:06.034 11 info flutter.tools  setState() or markNeedsBuild() called during build.
21:30:06.034 12 info flutter.tools  This RawMaterialButton widget cannot be marked as needing to build because the framework is already
21:30:06.034 13 info flutter.tools  in the process of building widgets.  A widget can be marked as needing to be built during the build
21:30:06.034 14 info flutter.tools  phase only if one of its ancestors is currently building. This exception is allowed because the
21:30:06.034 15 info flutter.tools  framework builds parent widgets before children, which means a dirty descendant will always be
21:30:06.035 16 info flutter.tools  built. Otherwise, the framework might not visit this widget during this build phase.
21:30:06.035 17 info flutter.tools  The widget on which setState() or markNeedsBuild() was called was:
21:30:06.035 18 info flutter.tools    RawMaterialButton
21:30:06.035 19 info flutter.tools  The widget which was currently being built when the offending call was made was:
21:30:06.035 20 info flutter.tools    InkWell
21:30:06.035 21 info flutter.tools  
21:30:06.038 22 info flutter.tools  When the exception was thrown, this was the stack:
21:30:06.038 23 info flutter.tools  #0      Element.markNeedsBuild.<anonymous closure> (package:flutter/src/widgets/framework.dart:3670:11)
21:30:06.039 24 info flutter.tools  #1      Element.markNeedsBuild (package:flutter/src/widgets/framework.dart:3685:6)
21:30:06.039 25 info flutter.tools  #2      State.setState (package:flutter/src/widgets/framework.dart:1161:14)
21:30:06.039 26 info flutter.tools  #3      _RawMaterialButtonState._handleHoveredChanged (package:flutter/src/material/button.dart:267:7)
21:30:06.039 27 info flutter.tools  #4      _InkResponseState.updateHighlight (package:flutter/src/material/ink_well.dart:567:18)
21:30:06.039 28 info flutter.tools  #5      _InkResponseState._handleHoverChange (package:flutter/src/material/ink_well.dart:693:7)
21:30:06.039 29 info flutter.tools  #6      _InkResponseState._handlePointerExit (package:flutter/src/material/ink_well.dart:689:54)
21:30:06.039 30 info flutter.tools  #7      MouseTracker.detachAnnotation (package:flutter/src/gestures/mouse_tracking.dart:130:20)
21:30:06.039 31 info flutter.tools  #8      RenderPointerListener._updateAnnotations (package:flutter/src/rendering/proxy_box.dart:2575:45)
21:30:06.039 32 info flutter.tools  #9      RenderPointerListener.onPointerEnter= (package:flutter/src/rendering/proxy_box.dart:2517:7)
21:30:06.040 33 info flutter.tools  #10     Listener.updateRenderObject (package:flutter/src/widgets/basic.dart:5570:9)
21:30:06.040 34 info flutter.tools  #11     RenderObjectElement.update (package:flutter/src/widgets/framework.dart:4726:12)
21:30:06.040 35 info flutter.tools  #12     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:5097:11)
21:30:06.040 36 info flutter.tools  #13     Element.updateChild (package:flutter/src/widgets/framework.dart:2876:15)
21:30:06.041 37 info flutter.tools  #14     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3935:16)
21:30:06.042 38 info flutter.tools  #15     Element.rebuild (package:flutter/src/widgets/framework.dart:3721:5)
21:30:06.042 39 info flutter.tools  #16     StatefulElement.update (package:flutter/src/widgets/framework.dart:4085:5)
21:30:06.042 40 info flutter.tools  #17     Element.updateChild (package:flutter/src/widgets/framework.dart:2876:15)
21:30:06.042 41 info flutter.tools  #18     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3935:16)
21:30:06.042 42 info flutter.tools  #19     Element.rebuild (package:flutter/src/widgets/framework.dart:3721:5)
21:30:06.042 43 info flutter.tools  #20     ProxyElement.update (package:flutter/src/widgets/framework.dart:4219:5)
21:30:06.042 44 info flutter.tools  #21     Element.updateChild (package:flutter/src/widgets/framework.dart:2876:15)
21:30:06.042 45 info flutter.tools  #22     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3935:16)
21:30:06.042 46 info flutter.tools  #23     Element.rebuild (package:flutter/src/widgets/framework.dart:3721:5)
21:30:06.042 47 info flutter.tools  #24     StatefulElement.update (package:flutter/src/widgets/framework.dart:4085:5)
21:30:06.042 48 info flutter.tools  #25     Element.updateChild (package:flutter/src/widgets/framework.dart:2876:15)
21:30:06.042 49 info flutter.tools  #26     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:5099:14)
21:30:06.042 50 info flutter.tools  #27     Element.updateChild (package:flutter/src/widgets/framework.dart:2876:15)
21:30:06.042 51 info flutter.tools  #28     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3935:16)
21:30:06.043 52 info flutter.tools  #29     Element.rebuild (package:flutter/src/widgets/framework.dart:3721:5)
21:30:06.043 53 info flutter.tools  #30     StatelessElement.update (package:flutter/src/widgets/framework.dart:3981:5)
21:30:06.044 54 info flutter.tools  #31     Element.updateChild (package:flutter/src/widgets/framework.dart:2876:15)
21:30:06.044 55 info flutter.tools  #32     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:5099:14)
21:30:06.044 56 info flutter.tools  #33     Element.updateChild (package:flutter/src/widgets/framework.dart:2876:15)
21:30:06.044 57 info flutter.tools  #34     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3935:16)
21:30:06.046 58 info flutter.tools  #35     Element.rebuild (package:flutter/src/widgets/framework.dart:3721:5)
21:30:06.046 59 info flutter.tools  #36     StatelessElement.update (package:flutter/src/widgets/framework.dart:3981:5)
21:30:06.046 60 info flutter.tools  #37     Element.updateChild (package:flutter/src/widgets/framework.dart:2876:15)
21:30:06.046 61 info flutter.tools  #38     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:5099:14)
21:30:06.046 62 info flutter.tools  #39     Element.updateChild (package:flutter/src/widgets/framework.dart:2876:15)
21:30:06.048 63 info flutter.tools  #40     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3935:16)
21:30:06.048 64 info flutter.tools  #41     Element.rebuild (package:flutter/src/widgets/framework.dart:3721:5)
21:30:06.048 65 info flutter.tools  #42     StatefulElement.update (package:flutter/src/widgets/framework.dart:4085:5)
21:30:06.048 66 info flutter.tools  #43     Element.updateChild (package:flutter/src/widgets/framework.dart:2876:15)
21:30:06.048 67 info flutter.tools  #44     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3935:16)
21:30:06.048 68 info flutter.tools  #45     Element.rebuild (package:flutter/src/widgets/framework.dart:3721:5)
21:30:06.048 69 info flutter.tools  #46     StatefulElement.update (package:flutter/src/widgets/framework.dart:4085:5)
21:30:06.048 70 info flutter.tools  #47     Element.updateChild (package:flutter/src/widgets/framework.dart:2876:15)
21:30:06.048 71 info flutter.tools  #48     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:5099:14)
21:30:06.048 72 info flutter.tools  #49     Element.updateChild (package:flutter/src/widgets/framework.dart:2876:15)
21:30:06.048 73 info flutter.tools  #50     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3935:16)
21:30:06.048 74 info flutter.tools  #51     Element.rebuild (package:flutter/src/widgets/framework.dart:3721:5)
21:30:06.048 75 info flutter.tools  #52     ProxyElement.update (package:flutter/src/widgets/framework.dart:4219:5)
21:30:06.048 76 info flutter.tools  #53     _InheritedNotifierElement.update (package:flutter/src/widgets/inherited_notifier.dart:94:11)
21:30:06.048 77 info flutter.tools  #54     Element.updateChild (package:flutter/src/widgets/framework.dart:2876:15)
21:30:06.048 78 info flutter.tools  #55     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3935:16)
21:30:06.048 79 info flutter.tools  #56     Element.rebuild (package:flutter/src/widgets/framework.dart:3721:5)
21:30:06.048 80 info flutter.tools  #57     StatefulElement.update (package:flutter/src/widgets/framework.dart:4085:5)
21:30:06.048 81 info flutter.tools  #58     Element.updateChild (package:flutter/src/widgets/framework.dart:2876:15)
21:30:06.048 82 info flutter.tools  #59     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:5099:14)
21:30:06.049 83 info flutter.tools  #60     Element.updateChild (package:flutter/src/widgets/framework.dart:2876:15)
21:30:06.050 84 info flutter.tools  #61     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:5099:14)
21:30:06.050 85 info flutter.tools  #62     Element.updateChild (package:flutter/src/widgets/framework.dart:2876:15)
21:30:06.050 86 info flutter.tools  #63     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3935:16)
21:30:06.050 87 info flutter.tools  #64     Element.rebuild (package:flutter/src/widgets/framework.dart:3721:5)
21:30:06.050 88 info flutter.tools  #65     StatefulElement.update (package:flutter/src/widgets/framework.dart:4085:5)
21:30:06.050 89 info flutter.tools  #66     Element.updateChild (package:flutter/src/widgets/framework.dart:2876:15)
21:30:06.050 90 info flutter.tools  #67     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3935:16)
21:30:06.050 91 info flutter.tools  #68     Element.rebuild (package:flutter/src/widgets/framework.dart:3721:5)
21:30:06.050 92 info flutter.tools  #69     StatelessElement.update (package:flutter/src/widgets/framework.dart:3981:5)
21:30:06.050 93 info flutter.tools  #70     Element.updateChild (package:flutter/src/widgets/framework.dart:2876:15)
21:30:06.050 94 info flutter.tools  #71     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:5099:14)
21:30:06.050 95 info flutter.tools  #72     Element.updateChild (package:flutter/src/widgets/framework.dart:2876:15)
21:30:06.050 96 info flutter.tools  #73     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3935:16)
21:30:06.050 97 info flutter.tools  #74     Element.rebuild (package:flutter/src/widgets/framework.dart:3721:5)
21:30:06.050 98 info flutter.tools  #75     StatelessElement.update (package:flutter/src/widgets/framework.dart:3981:5)
21:30:06.050 99 info flutter.tools  #76     Element.updateChild (package:flutter/src/widgets/framework.dart:2876:15)
21:30:06.050 100 info flutter.tools  #77     HookElement.updateChild (package:flutter_hooks/src/framework.dart:334:18)
21:30:06.050 101 info flutter.tools  #78     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3935:16)
21:30:06.051 102 info flutter.tools  #79     Element.rebuild (package:flutter/src/widgets/framework.dart:3721:5)
21:30:06.051 103 info flutter.tools  #80     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2340:33)
21:30:06.052 104 info flutter.tools  #81     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding&WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:700:20)
21:30:06.052 105 info flutter.tools  #82     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:285:5)
21:30:06.053 106 info flutter.tools  #83     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1016:15)
21:30:06.053 107 info flutter.tools  #84     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:958:9)
21:30:06.053 108 info flutter.tools  #85     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:874:5)
21:30:06.054 109 info flutter.tools  #89     _invoke (dart:ui/hooks.dart:236:10)
21:30:06.055 110 info flutter.tools  #90     _drawFrame (dart:ui/hooks.dart:194:3)
21:30:06.055 111 info flutter.tools  (elided 3 frames from package dart:async)
21:30:06.055 112 info flutter.tools  ════════════════════════════════════════════════════════════════════════════════════════════════════
21:30:06.063 113 info flutter.tools  Another exception was thrown: 'package:flutter/src/material/material.dart': Failed assertion: line 585 pos 12: 'referenceBox.attached': is not true.
21:30:06.082 114 info runtime.gc collection time 57ms • 39.5MB used of 47.0MB • isolates/830309596
21:30:06.105 115 info flutter.tools  Another exception was thrown: 'package:flutter/src/material/material.dart': Failed assertion: line 585 pos 12: 'referenceBox.attached': is not true.
21:30:06.127 116 info flutter.tools  Another exception was thrown: 'package:flutter/src/material/material.dart': Failed assertion: line 585 pos 12: 'referenceBox.attached': is not true.
21:30:06.148 117 info flutter.tools  Another exception was thrown: 'package:flutter/src/material/material.dart': Failed assertion: line 585 pos 12: 'referenceBox.attached': is not true.
21:30:06.162 118 info flutter.tools  Another exception was thrown: 'package:flutter/src/material/material.dart': Failed assertion: line 585 pos 12: 'referenceBox.attached': is not true.
21:30:06.175 119 info flutter.tools  Another exception was thrown: 'package:flutter/src/material/material.dart': Failed assertion: line 585 pos 12: 'referenceBox.attached': is not true.
21:30:06.190 120 info flutter.tools  Another exception was thrown: 'package:flutter/src/material/material.dart': Failed assertion: line 585 pos 12: 'referenceBox.attached': is not true.
21:30:06.237 121 info runtime.gc collection time 71ms • 44.7MB used of 48.0MB • isolates/830309596
21:30:06.337 122 info runtime.gc collection time 74ms • 39.2MB used of 56.3MB • isolates/830309596
21:30:07.080 123 info runtime.gc collection time 84ms • 51.1MB used of 57.3MB • isolates/830309596
21:30:07.138 124 info runtime.gc collection time 85ms • 40.0MB used of 57.3MB • isolates/830309596
21:30:07.327 125 info flutter.tools  Another exception was thrown: 'package:flutter/src/widgets/framework.dart': Failed assertion: line 4363 pos 14: '_dependents.isEmpty': is not true.

```

To reproduce: 

```
import 'dart:io';

import 'package:flutter/foundation.dart';
import 'package:flutter/material.dart';
import 'package:flutter_hooks/flutter_hooks.dart';

void main() {
  if (!Platform.isAndroid && !Platform.isIOS) {
    debugDefaultTargetPlatformOverride = TargetPlatform.fuchsia; //FIXME remove when desktop is supported
  }
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key key, this.title}) : super(key: key);

  final String title;

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: Padding(
        padding: const EdgeInsets.all(16.0),
        child: Center(
          child: ProgressButton(
            child: Text('LOGIN'),
            until: () => Future.delayed(Duration(seconds: 1)),
            onSuccess: (_) {
              Navigator.of(context).push(MaterialPageRoute(builder: (BuildContext context) {
                return Scaffold(
                  appBar: AppBar(
                    title: Text('ok'),
                  ),
                  body: Placeholder(),
                );
              }));
            },
          ),
        ),
      ),
    );
  }
}

enum ProgressButtonState { idle, progress, done }

class ProgressButton extends HookWidget {
  final EdgeInsets padding;
  final Color color;
  final Widget child;
  final double elevation;
  final Future Function() until;
  final Function(dynamic, dynamic) onError;
  final Function(dynamic) onSuccess;

  ProgressButton({Key key, this.padding, this.color, this.child, this.elevation, this.until, this.onError, this.onSuccess}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    final _globalKey = useMemoized(() => GlobalKey());
    final _width = useState(double.infinity);
    final _isPressed = useState(false);
    final _state = useState(ProgressButtonState.idle);
    final _controller = useAnimationController(duration: Duration(milliseconds: 500));
    final _anim = useAnimation(Tween(begin: 0.0, end: 1.0).animate(_controller));
    final initialWidth = useState<double>(null);
    final height = useState<double>(null);
    final isFinish = useState<bool>(false);
    final result = useState<dynamic>(null);

    useEffect(() {
      _controller.addStatusListener((status) {
        if (status == AnimationStatus.completed && isFinish.value) {
          onSuccess(result.value);
        }
      });
      return () {
        reset(_state, _width, _isPressed, initialWidth);
      };
    }, [this]);

    return Container(
      key: _globalKey,
      width: initialWidth.value == null ? double.infinity : initialWidth.value - ((initialWidth.value - height.value) * _anim),
      height: _isPressed.value ? 55 : null,
      child: RaisedButton(
        shape: _isPressed.value ? RoundedRectangleBorder(borderRadius: BorderRadius.circular(35)) : null,
        padding: _isPressed.value ? EdgeInsets.zero : padding,
        color: color,
        disabledColor: _state.value == ProgressButtonState.done ? Theme.of(context).accentColor : color,
        child: buildButtonChild(_state),
        onPressed: _isPressed.value
            ? null
            : () async {
                initialWidth.value = _globalKey.currentContext.size.width;
                height.value = _globalKey.currentContext.size.height;

                _isPressed.value = true;
                if (_state.value == ProgressButtonState.idle) {
                  _controller.forward();
                  _state.value = ProgressButtonState.progress;
                }
                try {
                  result.value = await until();
                  _state.value = ProgressButtonState.done;
                  isFinish.value = true;
                  if (_controller.isCompleted) {
                    onSuccess(result);
                  }
                } catch (err, stacktrace) {
                  onError(err, stacktrace);
                  _controller.reverse();
                  reset(_state, _width, _isPressed, initialWidth);
                }
              },
      ),
    );
  }

  Widget buildButtonChild(ValueNotifier<ProgressButtonState> state) {
    if (state.value == ProgressButtonState.idle) {
      return child;
    } else if (state.value == ProgressButtonState.progress) {
      return CircularProgressIndicator(
        value: null,
        valueColor: AlwaysStoppedAnimation<Color>(Colors.black),
      );
    } else {
      return Icon(Icons.check, color: Colors.white);
    }
  }

  void reset(
    ValueNotifier<ProgressButtonState> state,
    ValueNotifier<double> width,
    ValueNotifier<bool> isPressed,
    ValueNotifier<double> initialWidth,
  ) {
    isPressed.value = false;
    width.value = double.infinity;
    state.value = ProgressButtonState.idle;
    initialWidth.value = null;
  }
}
```
It use `flutter_hooks`.

Env:
```
[✓] Flutter (Channel dev, v1.7.8, on Mac OS X 10.14.5 18F132, locale fr-FR)
    • Flutter version 1.7.8 at /Users/jaumard/flutter
    • Framework revision d51fd86cdb (17 hours ago), 2019-06-21 22:31:55 -0400
    • Engine revision d004bcd4d6
    • Dart version 2.4.0

 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/jaumard/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 10.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.2.1, Build version 10E1001
    • CocoaPods version 1.6.0

[✓] iOS tools - develop for iOS devices
    • ios-deploy 1.9.4

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 3.4)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 36.1.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

[✓] IntelliJ IDEA Ultimate Edition (version 2019.1.3)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 36.1.4
    • Dart plugin version 191.7830

[✓] Connected device (3 available)
    • iPhone X • B9C382ED-425A-48A3-9DDA-B1C15D7BA485 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-12-1 (simulator)
    • macOS    • macOS                                • darwin-x64     • Mac OS X 10.14.5 18F132
    • web      • web                                  • web-javascript • Google Chrome 75.0.3770.100 


• No issues found!
```

**Comment by stuartmorgan** [comment]
@gspencergoog The stack suggests this is hover-related.

**Comment by jaumard** [comment]
It append also on Linux, look like desktop related

**Comment by gspencergoog** [comment]
Actually, this has the same problem on Android too, at least.  A simpler repro case (just navigating when the button is clicked) doesn't repro this, so I'll have to deconstruct it a bit more and see if I can get it to happen without the hooks package in the mix.

**Comment by gspencergoog** [comment]
Actually, this no longer fails if I change the `onPressed` to be:
```dart
        onPressed: () async {...}
```
Instead of the conditional.  Of course, that means the button can't be disabled, which implies that there's still a bug here somewhere.

**Comment by jaumard** [comment]
Look like it's ok now on master and MacOSX build :)
