### ISSUE TITLE
“gen_snapshot” is not optimized for your Mac and needs to be updated.

### ISSUE THREAD

**Issue by debragail** [flutter/flutter#34976]
“gen_snapshot” is not optimized for your Mac and needs to be updated.

Android Studio 3.4.1
Build #AI-183.6156.11.34.5522156, built on May 1, 2019
JRE: 1.8.0_152-release-1343-b01 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.14.4

**Comment by abbazer** [comment]
The same problem after upgrading to MacOS Catalina. Before this problem didn't appear.

## command

`flutter build aot --suppress-analytics --quiet --target lib/main.dart --target-platform android-arm --output-dir /Users/developer/Projects/bta-auth/build/app/intermediates/flutter/release --target-platform android-arm --release`

## exception

ProcessException: ProcessException: Bad CPU type in executable
  Command: /Users/developer/flutter/bin/cache/artifacts/engine/android-arm-release/darwin-x64/gen_snapshot --causal_async_stacks --deterministic --snapshot_kind=app-aot-blobs --vm_snapshot_data=/Users/developer/Projects/bta-auth/build/app/intermediates/flutter/release/vm_snapshot_data --isolate_snapshot_data=/Users/developer/Projects/bta-auth/build/app/intermediates/flutter/release/isolate_snapshot_data --vm_snapshot_instructions=/Users/developer/Projects/bta-auth/build/app/intermediates/flutter/release/vm_snapshot_instr --isolate_snapshot_instructions=/Users/developer/Projects/bta-auth/build/app/intermediates/flutter/release/isolate_snapshot_instr --no-sim-use-hardfp --no-use-integer-division /Users/developer/Projects/bta-auth/build/app/intermediates/flutter/release/app.dill

```
#0      runCommandAndStreamOutput (package:flutter_tools/src/base/process.dart:142:27)
<asynchronous suspension>
#1      GenSnapshot.run (package:flutter_tools/src/base/build.dart:68:12)
#2      AOTSnapshotter.build.<anonymous closure> (package:flutter_tools/src/base/build.dart:207:88)
#3      AOTSnapshotter._timedStep (package:flutter_tools/src/base/build.dart:363:33)
<asynchronous suspension>
#4      AOTSnapshotter.build (package:flutter_tools/src/base/build.dart:207:43)
<asynchronous suspension>
#5      BuildAotCommand.runCommand (package:flutter_tools/src/commands/build_aot.dart:143:56)
<asynchronous suspension>
#6      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:559:18)
<asynchronous suspension>
#7      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:495:33)
<asynchronous suspension>
#8      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:142:29)
<asynchronous suspension>
#9      _rootRun (dart:async/zone.dart:1124:13)
#10     _CustomZone.run (dart:async/zone.dart:1021:19)
#11     _runZoned (dart:async/zone.dart:1516:10)
#12     runZoned (dart:async/zone.dart:1463:12)
#13     AppContext.run (package:flutter_tools/src/base/context.dart:141:18)
<asynchronous suspension>
#14     FlutterCommand.run (package:flutter_tools/src/runner/flutter_command.dart:486:20)
#15     CommandRunner.runCommand (package:args/command_runner.dart:196:27)
<asynchronous suspension>
#16     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:396:21)
<asynchronous suspension>
#17     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:142:29)
<asynchronous suspension>
#18     _rootRun (dart:async/zone.dart:1124:13)
#19     _CustomZone.run (dart:async/zone.dart:1021:19)
#20     _runZoned (dart:async/zone.dart:1516:10)
#21     runZoned (dart:async/zone.dart:1463:12)
#22     AppContext.run (package:flutter_tools/src/base/context.dart:141:18)
<asynchronous suspension>
#23     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:356:19)
<asynchronous suspension>
#24     CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:111:29)
#25     new Future.sync (dart:async/future.dart:224:31)
#26     CommandRunner.run (package:args/command_runner.dart:111:11)
#27     FlutterCommandRunner.run (package:flutter_tools/src/runner/flutter_command_runner.dart:242:18)
#28     run.<anonymous closure> (package:flutter_tools/runner.dart:60:20)
<asynchronous suspension>
#29     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:142:29)
<asynchronous suspension>
#30     _rootRun (dart:async/zone.dart:1124:13)
#31     _CustomZone.run (dart:async/zone.dart:1021:19)
#32     _runZoned (dart:async/zone.dart:1516:10)
#33     runZoned (dart:async/zone.dart:1463:12)
#34     AppContext.run (package:flutter_tools/src/base/context.dart:141:18)
<asynchronous suspension>
#35     runInContext (package:flutter_tools/src/context_runner.dart:50:24)
<asynchronous suspension>
#36     run (package:flutter_tools/runner.dart:51:10)
#37     main (package:flutter_tools/executable.dart:60:9)
<asynchronous suspension>
#38     main (file:///Users/developer/flutter/packages/flutter_tools/bin/flutter_tools.dart:8:3)
#39     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:298:32)
#40     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:171:12)
```

## flutter doctor

```
[!] Flutter (Channel stable, v1.5.4-hotfix.2, on Mac OS X 10.15 19A487l, locale en-KG)
    • Flutter version 1.5.4-hotfix.2 at /Users/developer/flutter
    • Framework revision 7a4c33425d (8 weeks ago), 2019-04-29 11:05:24 -0700
    • Engine revision 52c7a1e849
    • Dart version 2.3.0 (build 2.3.0-dev.0.5 a1668566e5)
    ✗ Downloaded executables cannot execute on host.
      See https://github.com/flutter/flutter/issues/6207 for more information


[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/developer/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
    • All Android licenses accepted.

[!] iOS toolchain - develop for iOS devices (Xcode 10.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.2.1, Build version 10E1001
    ✗ libimobiledevice and ideviceinstaller are not installed. To install with Brew, run:
        brew update
        brew install --HEAD usbmuxd
        brew link usbmuxd
        brew install --HEAD libimobiledevice
        brew install ideviceinstaller
    • ios-deploy 1.9.4
    • CocoaPods version 1.7.2

[✓] Android Studio (version 3.4)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 36.1.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

[✓] IntelliJ IDEA Ultimate Edition (version 2019.1.3)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 36.1.4
    • Dart plugin version 191.7830

[✓] VS Code (version 1.35.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.1.0

[!] Connected device
    ! No devices available

! Doctor found issues in 3 categories.
```

**Comment by tvolkert** [comment]
Closing as a dup of https://github.com/flutter/flutter/issues/22598
