### ISSUE TITLE
E/flutter (12282): [ERROR:flutter/lib/ui/ui_dart_state.cc(148)] Unhandled Exception: HttpException: , uri = ..........

### ISSUE THREAD

**Issue by putrautama007** [flutter/flutter#34980]
I have the error when I run the application, the error is as below:

```
Launching lib/main.dart on Android SDK built for x86 in debug mode...
Initializing gradle...
Resolving dependencies...
Running Gradle task 'assembleDebug'...
Built build/app/outputs/apk/debug/app-debug.apk.
Installing build/app/outputs/apk/app.apk...
Syncing files to device Android SDK built for x86...
D/EGL_emulation(12282): eglMakeCurrent: 0xa4e63920: ver 3 0 (tinfo 0x9b8be970)
E/flutter (12282): [ERROR:flutter/lib/ui/ui_dart_state.cc(148)] Unhandled Exception: HttpException: , uri = ....... (link)
E/flutter (12282): #0      ApiProvider.fetchToken (package:cari_mobile_flutter_main/src/resources/network/api_provider.dart:40:40)
E/flutter (12282): <asynchronous suspension>
E/flutter (12282): #1      Repository.fetchToken (package:cari_mobile_flutter_main/src/resources/repositories/repository.dart:10:31)
E/flutter (12282): #2      SplashBloc.fetchToken (package:cari_mobile_flutter_main/src/blocs/splash/splash_bloc.dart:18:38)
E/flutter (12282): <asynchronous suspension>
E/flutter (12282): #3      _SplashScreenState.initState (package:cari_mobile_flutter_main/src/view/splash/splash.dart:29:10)
E/flutter (12282): #4      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3846:58)
E/flutter (12282): #5      ComponentElement.mount (package:flutter/src/widgets/framework.dart:3717:5)
E/flutter (12282): #6      Element.inflateWidget (package:flutter/src/widgets/framework.dart:2961:14)
E/flutter (12282): #7      Element.updateChild (package:flutter/src/widgets/framework.dart:2764:12)
E/flutter (12282): #8      SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4876:14)
E/flutter (12282): #9      Element.inflateWidget (package:flutter/src/widgets/framework.dart:2961:14)
E/flutter (12282): #10     Element.updateChild (package:flutter/src/widgets/framework.dart:2764:12)
E/flutter (12282): #11     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3750:16)
E/flutter (12282): #12     Element.rebuild (package:flutter/src/widgets/framework.dart:3565:5)
E/flutter (12282): #13     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3722:5)
E/flutter (12282): #14     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3717:5)
E/flutter (12282): #15     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2961:14)
E/flutter (12282): #16     Element.updateChild (package:flutter/src/widgets/framework.dart:2764:12)
E/flutter (12282): #17     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4876:14)
E/flutter (12282): #18     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2961:14)
E/flutter (12282): #19     Element.updateChild (package:flutter/src/widgets/framework.dart:2764:12)
E/flutter (12282): #20     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4876:14)
E/flutter (12282): #21     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2961:14)
E/flutter (12282): #22     Element.updateChild (package:flutter/src/widgets/framework.dart:2764:12)
E/flutter (12282): #23     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4876:14)
E/flutter (12282): #24     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2961:14)
E/flutter (12282): #25     Element.updateChild (package:flutter/src/widgets/framework.dart:2764:12)
E/flutter (12282): #26     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4876:14)
E/flutter (12282): #27     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2961:14)
E/flutter (12282): #28     Element.updateChild (package:flutter/src/widgets/framework.dart:2764:12)
E/flutter (12282): #29     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3750:16)
E/flutter (12282): #30     Element.rebuild (package:flutter/src/widgets/framework.dart:3565:5)
E/flutter (12282): #31     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3722:5)
E/flutter (12282): #32     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3864:11)
E/flutter (12282): #33     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3717:5)
E/flutter (12282): #34     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2961:14)
E/flutter (12282): #35     Element.updateChild (package:flutter/src/widgets/framework.dart:2764:12)
E/flutter (12282): #36     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3750:16)
E/flutter (12282): #37     Element.rebuild (package:flutter/src/widgets/framework.dart:3565:5)
E/flutter (12282): #38     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3722:5)
E/flutter (12282): #39     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3717:5)
E/flutter (12282): #40     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2961:14)
E/flutter (12282): #41     Element.updateChild (package:flutter/src/widgets/framework.dart:2764:12)
E/flutter (12282): #42     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3750:16)
E/flutter (12282): #43     Element.rebuild (package:flutter/src/widgets/framework.dart:3565:5)
E/flutter (12282): #44     ComponentE
```

I get this error because I want to call API for access or get a token. But, I actually got an error like this: `Unhandled Exception: HttpException: , uri = ....... (link)`.

Previously I could not give the link address because it was confidential.
Is there a solution to overcome this error / problem? I beg for your help.

Thank you.

**Comment by ketanm** [comment]
@putrautama007 

Above error is coming from your code and implementation. Either handle exception around site and log error or review your implementation or share relevant implementation code.

Ketan

**Comment by putrautama007** [comment]
@ketanm 
Thank you for the help, I will try to review my code again

**Comment by putrautama007** [comment]
@ketanm 
can flutter connect to an API that uses an API with the HTTP1.1 protocol version?

**Comment by ketanm** [comment]
It should not be an issue. Are you using a correct package? Please see this documentation to ensure usage is correct - https://flutter.dev/docs/cookbook/networking/fetch-data

**Comment by putrautama007** [comment]
yes I have used the correct package
http package

**Comment by ketanm** [comment]
Hi @putrautama007,

Your posted code has exception handling and prints. Do you see any one of those on the console?

Did not see anything major in the code, except you can avoid resource leak by calling `httpClient.close()` etc. Let me know if you actually see anything on the console from this method. Original stack trace does not tell me which file this method is defined.

**Comment by ketanm** [comment]
Can you update how it was solved?

**Comment by putrautama007** [comment]
API problems occur because they still use HTTP protocol version 1.1
so when the version is upgraded there is no problem when accessing
