### ISSUE TITLE
Error when using: Color(0xFF8D8E98)

### ISSUE THREAD

**Issue by Ignisstorm** [flutter/flutter#34981]
<----------------------------------My Code-------------------------------------->
```
import 'package:flutter/material.dart';
import 'package:font_awesome_flutter/font_awesome_flutter.dart';

const bottomContainerHeight = 80.0;
const activeCardColor = Color(0xFF1D1E33);
const bottomContainerColor = Color(0xFFEB1555);

class InputPage extends StatefulWidget {
  @override
  _InputPageState createState() => _InputPageState();
}

class _InputPageState extends State<InputPage> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('BMI CALCULATOR'),
      ),
      body: Column(children: <Widget>[
        Expanded(
            child: Row(
          children: <Widget>[
            Expanded(
              child: ReusableCard(
                color: activeCardColor,
                cardChild: ReusableCardIconText(
                    icon: FontAwesomeIcons.mars, text: 'Male'),
              ),
            ),
            Expanded(
                child: ReusableCard(
              color: activeCardColor,
              cardChild: ReusableCardIconText(
                  icon: FontAwesomeIcons.venus, text: 'Female'),
            )),
          ],
        )),
        Expanded(
            child: Row(
          children: <Widget>[
            Expanded(
                child: ReusableCard(
              color: activeCardColor,
            )),
          ],
        )),
        Expanded(
            child: Row(
          children: <Widget>[
            Expanded(
                child: ReusableCard(
              color: activeCardColor,
            )),
            Expanded(
                child: ReusableCard(
              color: activeCardColor,
            )),
          ],
        )),
        Container(
          color: bottomContainerColor,
          margin: EdgeInsets.only(top: 10.0),
          width: double.infinity,
          height: bottomContainerHeight,
        ),
      ]),
    );
  }
}

class ReusableCardIconText extends StatelessWidget {
  ReusableCardIconText({this.icon, this.text});

  final icon;
  final text;

  @override
  Widget build(BuildContext context) {
    return Column(
      mainAxisAlignment: MainAxisAlignment.center,
      children: <Widget>[
        Icon(
          icon,
          size: 80.0,
        ),
        SizedBox(
          height: 15.0,
        ),
        Text(
          text,
          style: TextStyle(
            fontSize: 18.0,
            color: Color(0xFF8D8E98),
          ),
        )
      ],
    );
  }
}

class ReusableCard extends StatelessWidget {
  ReusableCard({@required this.color, this.cardChild});

  final Color color;
  final Widget cardChild;

  @override
  Widget build(BuildContext context) {
    return Container(
      child: cardChild,
      margin: EdgeInsets.all(15.0),
      decoration: BoxDecoration(
        color: color,
        borderRadius: BorderRadius.circular(10.0),
      ),
    );
  }
}
```
<----------------------------the error message----------------------------------->
```
Launching lib/main.dart on iPhone Xʀ in debug mode...
Running Xcode build...
Xcode build done.                                            6.5s
Syncing files to device iPhone Xʀ...
flutter: ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
flutter: The following assertion was thrown building WidgetsApp-[GlobalObjectKey
flutter: _MaterialAppState#2926b](dirty, state: _WidgetsAppState#665ca):
flutter: 'package:flutter/src/widgets/title.dart': Failed assertion: line 24 pos 15: 'color != null &&
flutter: color.alpha == 0xFF': is not true.
flutter:
flutter: Either the assertion indicates an error in the framework itself, or we should provide substantially
flutter: more information in this error message to help you determine and fix the underlying cause.
flutter: In either case, please report this assertion by filing a bug on GitHub:
flutter:   https://github.com/flutter/flutter/issues/new?template=BUG.md
flutter:
flutter: When the exception was thrown, this was the stack:
flutter: #2      new Title (package:flutter/src/widgets/title.dart:24:15)
flutter: #3      _WidgetsAppState.build (package:flutter/src/widgets/app.dart:1180:15)
flutter: #4      StatefulElement.build (package:flutter/src/widgets/framework.dart:3825:27)
flutter: #5      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3739:15)
flutter: #6      Element.rebuild (package:flutter/src/widgets/framework.dart:3565:5)
flutter: #7      ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3722:5)
flutter: #8      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3864:11)
flutter: #9      ComponentElement.mount (package:flutter/src/widgets/framework.dart:3717:5)
flutter: #10     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2961:14)
flutter: #11     Element.updateChild (package:flutter/src/widgets/framework.dart:2764:12)
flutter: #12     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3750:16)
flutter: #13     Element.rebuild (package:flutter/src/widgets/framework.dart:3565:5)
flutter: #14     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3722:5)
flutter: #15     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3717:5)
flutter: #16     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2961:14)
flutter: #17     Element.updateChild (package:flutter/src/widgets/framework.dart:2764:12)
flutter: #18     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3750:16)
flutter: #19     Element.rebuild (package:flutter/src/widgets/framework.dart:3565:5)
flutter: #20     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3722:5)
flutter: #21     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3864:11)
flutter: #22     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3717:5)
flutter: #23     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2961:14)
flutter: #24     Element.updateChild (package:flutter/src/widgets/framework.dart:2764:12)
flutter: #25     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3750:16)
flutter: #26     Element.rebuild (package:flutter/src/widgets/framework.dart:3565:5)
flutter: #27     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3722:5)
flutter: #28     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3717:5)
flutter: #29     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2961:14)
flutter: #30     Element.updateChild (package:flutter/src/widgets/framework.dart:2764:12)
flutter: #31     RenderObjectToWidgetElement._rebuild (package:flutter/src/widgets/binding.dart:933:16)
flutter: #32     RenderObjectToWidgetElement.mount (package:flutter/src/widgets/binding.dart:904:5)
flutter: #33     RenderObjectToWidgetAdapter.attachToRenderTree.<anonymous closure> (package:flutter/src/widgets/binding.dart:850:17)
flutter: #34     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2258:19)
flutter: #35     RenderObjectToWidgetAdapter.attachToRenderTree (package:flutter/src/widgets/binding.dart:849:13)
flutter: #36     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding&WidgetsBinding.attachRootWidget (package:flutter/src/widgets/binding.dart:736:7)
flutter: #37     runApp (package:flutter/src/widgets/binding.dart:780:7)
flutter: #38     main (package:project1_app/main.dart:5:16)
flutter: #39     _runMainZoned.<anonymous closure>.<anonymous closure> (dart:ui/hooks.dart:199:25)
flutter: #44     _runMainZoned.<anonymous closure> (dart:ui/hooks.dart:190:5)
flutter: #45     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:300:19)
flutter: #46     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:171:12)
flutter: (elided 6 frames from class _AssertionError and package dart:async)
flutter: ════════════════════════════════════════════════════════════════════════════════════════════════════
flutter: Another exception was thrown: 'package:flutter/src/widgets/title.dart': Failed assertion: line 24 pos 15: 'color != null && color.alpha == 0xFF': is not true.
flutter: Another exception was thrown: 'package:flutter/src/widgets/title.dart': Failed assertion: line 24 pos 15: 'color != null && color.alpha == 0xFF': is not true.
flutter: ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
flutter: The following assertion was thrown building WidgetsApp-[GlobalObjectKey
flutter: _MaterialAppState#2926b](dirty, state: _WidgetsAppState#665ca):
flutter: 'package:flutter/src/widgets/title.dart': Failed assertion: line 24 pos 15: 'color != null &&
flutter: color.alpha == 0xFF': is not true.
flutter:
flutter: Either the assertion indicates an error in the framework itself, or we should provide substantially
flutter: more information in this error message to help you determine and fix the underlying cause.
flutter: In either case, please report this assertion by filing a bug on GitHub:
flutter:   https://github.com/flutter/flutter/issues/new?template=BUG.md
flutter:
flutter: When the exception was thrown, this was the stack:
flutter: #2      new Title (package:flutter/src/widgets/title.dart:24:15)
flutter: #3      _WidgetsAppState.build (package:flutter/src/widgets/app.dart:1180:15)
flutter: #4      StatefulElement.build (package:flutter/src/widgets/framework.dart:3825:27)
flutter: #5      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3739:15)
flutter: #6      Element.rebuild (package:flutter/src/widgets/framework.dart:3565:5)
flutter: #7      StatefulElement.update (package:flutter/src/widgets/framework.dart:3894:5)
flutter: #8      Element.updateChild (package:flutter/src/widgets/framework.dart:2753:15)
flutter: #9      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3750:16)
flutter: #10     Element.rebuild (package:flutter/src/widgets/framework.dart:3565:5)
flutter: #11     ProxyElement.update (package:flutter/src/widgets/framework.dart:4006:5)
flutter: #12     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:15)
flutter: #13     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3750:16)
flutter: #14     Element.rebuild (package:flutter/src/widgets/framework.dart:3565:5)
flutter: #15     StatefulElement.update (package:flutter/src/widgets/framework.dart:3894:5)
flutter: #16     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:15)
flutter: #17     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3750:16)
flutter: #18     Element.rebuild (package:flutter/src/widgets/framework.dart:3565:5)
flutter: #19     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2278:33)
flutter: #20     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding&WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:700:20)
flutter: #21     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:286:5)
flutter: #22     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1012:15)
flutter: #23     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:952:9)
flutter: #24     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.scheduleWarmUpFrame.<anonymous closure> (package:flutter/src/scheduler/binding.dart:773:7)
flutter: #26     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:382:19)
flutter: #27     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:416:5)
flutter: #28     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:171:12)
flutter: (elided 3 frames from class _AssertionError and package dart:async-patch)
flutter: ════════════════════════════════════════════════════════════════════════════════════════════════════
<img width="338" alt="Screenshot 2019-06-24 at 12 19 42" src="https://user-images.githubusercontent.com/43708340/60013610-29ee3200-967f-11e9-8ae9-2bc8f9c8300c.png">
```

**Comment by ketanm** [comment]
@Ignisstorm  

Error message right in the log that you shared above. Currently, Flutter API for `Title` explicitly needs alpha value to be set to 0xFF. See documentation: https://api.flutter.dev/flutter/widgets/Title/Title.html

Change following, spcifically one that is set as Title color.
```
const activeCardColor = Color(0xFF1D1E33); 
const bottomContainerColor = Color(0xFFEB1555);
```

Hope this helps
Ketan

**Comment by VladyslavBondarenko** [comment]
Closing as solved and not an issue with flutter
