### ISSUE TITLE
Failed assertion: line 26: '<optimized out>'

### ISSUE THREAD

**Issue by duzenko** [flutter/flutter#34991]
## Steps to Reproduce
```

  Widget buildBody(BuildContext context) {
    final listView = Flexible(
      child: RefreshIndicator(
        key: _refreshIndicatorKey,
        onRefresh: reloadData,
        child: Scrollbar(
          child: ListView.builder(
            scrollDirection: Axis.vertical,
            shrinkWrap: true,
            itemCount: list.length,
            itemBuilder: (context, index) {
              if (index == list.length - 1 && !isLoading && !endReached) {
                SchedulerBinding.instance.addPostFrameCallback((_) {
                  print('reloading - last element reached: $index');
                  loadData();
                });
              }
              var w = listBuilder(context, index);
              if (widget.canEditItems)
                w = GestureDetector(
                  child: w,
                  onTap: () => editItem(index),
                );
              return w;
            },
          ),
        ),
      ),
    );

    final header = buildHeader();
    var widgetTree = <Widget>[listView];
    if (header != null) widgetTree.insert(0, header);
    widgetTree = <Widget>[
      Column(
        children: widgetTree,
      )
    ];

    if (isLoading)
      widgetTree.add(Stack(
        children: [
          new Opacity(
            opacity: 0.3,
            child: const ModalBarrier(dismissible: false, color: Colors.grey),
          ),
          new Center(
            child: new CircularProgressIndicator(),
          ),
        ],
      ));
    return new Stack(children: widgetTree);
  }

```

## Logs

```
Launching lib\main.dart on LGM G600L in debug mode...
Initializing gradle...
Resolving dependencies...
Running Gradle task 'assembleDebug'...
Built build\app\outputs\apk\debug\app-debug.apk.
Installing build\app\outputs\apk\app.apk...
Syncing files to device LGM G600L...
I/flutter (25002): UserData
I/flutter (25002): {"_id":null,"count":12}
I/flutter (25002): [{"_id":"5d00b5fb1b61d305a92234c5","status":"Opportunity","serialNumber":19,"date":"2019-06-12T08:21:15.807Z","salesperson":"Dwight Schrute"},{"_id":"5cbde86198edd338c2faa5cc","status":"Opportunity","serialNumber":17,"date":"2019-04-22T16:14:25.152Z","property":{"_id":"584efea5fc6ad00d29de5152","name":"Shops at Dakota Crossing"},"client":{"_id":"584efe61fc6ad00d29de514f","name":"CBRE Washington DC"},"salesperson":"Dwight Schrute"},{"_id":"5cbdd2db98edd338c2faa5ac","status":"Opportunity","serialNumber":16,"date":"2019-04-22T14:42:35.680Z","source":"This","dueDate":"2019-04-16T04:00:00.000Z","property":{"_id":"5c768b8efbf9410db664a54d","name":"Scranton Branch"},"client":{"_id":"5c26282a0017651e7fefa963","name":"Dunder Mifflin"},"salesperson":"Paul Test"},{"_id":"5cbdd2c598edd338c2faa5a0","status":"Opportunity","serialNumber":15,"date":"2019-04-22T14:42:13.016Z","salesperson":"Dwight Schrute"},{"_id":"5cacae9e6ce2222e0962ced4","status":"Opportunity","serialNumber":14,"date":"2019-04-09T14:39:26.510Z","property"
I/ViewRootImpl(25002): ViewRoot's Touch Event : ACTION_DOWN
I/ViewRootImpl(25002): ViewRoot's Touch Event : ACTION_UP
I/flutter (25002): {"_id":null,"count":12}
I/flutter (25002): [{"_id":"5d00b5fb1b61d305a92234c5","status":"Opportunity","serialNumber":19,"date":"2019-06-12T08:21:15.807Z","salesperson":"Dwight Schrute"},{"_id":"5cbde86198edd338c2faa5cc","status":"Opportunity","serialNumber":17,"date":"2019-04-22T16:14:25.152Z","property":{"_id":"584efea5fc6ad00d29de5152","name":"Shops at Dakota Crossing"},"client":{"_id":"584efe61fc6ad00d29de514f","name":"CBRE Washington DC"},"salesperson":"Dwight Schrute"},{"_id":"5cbdd2db98edd338c2faa5ac","status":"Opportunity","serialNumber":16,"date":"2019-04-22T14:42:35.680Z","source":"This","dueDate":"2019-04-16T04:00:00.000Z","property":{"_id":"5c768b8efbf9410db664a54d","name":"Scranton Branch"},"client":{"_id":"5c26282a0017651e7fefa963","name":"Dunder Mifflin"},"salesperson":"Paul Test"},{"_id":"5cbdd2c598edd338c2faa5a0","status":"Opportunity","serialNumber":15,"date":"2019-04-22T14:42:13.016Z","salesperson":"Dwight Schrute"},{"_id":"5cacae9e6ce2222e0962ced4","status":"Opportunity","serialNumber":14,"date":"2019-04-09T14:39:26.510Z","property"
I/ViewRootImpl(25002): ViewRoot's Touch Event : ACTION_DOWN
I/zygote64(25002): Do partial code cache collection, code=27KB, data=25KB
I/zygote64(25002): After code cache collection, code=27KB, data=25KB
I/zygote64(25002): Increasing code cache capacity to 128KB
I/ViewRootImpl(25002): ViewRoot's Touch Event : ACTION_UP
I/flutter (25002): ══╡ EXCEPTION CAUGHT BY RENDERING LIBRARY ╞═════════════════════════════════════════════════════════
I/flutter (25002): The following assertion was thrown during paint():
I/flutter (25002): Rect argument contained a NaN value.
I/flutter (25002): 'dart:ui/painting.dart': Failed assertion: line 26: '<optimized out>'
I/flutter (25002): 
I/flutter (25002): Either the assertion indicates an error in the framework itself, or we should provide substantially
I/flutter (25002): more information in this error message to help you determine and fix the underlying cause.
I/flutter (25002): In either case, please report this assertion by filing a bug on GitHub:
I/flutter (25002):   https://github.com/flutter/flutter/issues/new?template=BUG.md
I/flutter (25002): 
I/flutter (25002): When the exception was thrown, this was the stack:
I/flutter (25002): #2      _rectIsValid (dart:ui/painting.dart:26:10)
I/flutter (25002): #3      Canvas.drawRect (dart:ui/painting.dart:3322:12)
I/flutter (25002): #4      ScrollbarPainter._paintVerticalThumb (package:flutter/src/widgets/scrollbar.dart:135:14)
I/flutter (25002): #5      ScrollbarPainter._paintThumb (package:flutter/src/widgets/scrollbar.dart:201:12)
I/flutter (25002): #6      ScrollbarPainter.paint (package:flutter/src/widgets/scrollbar.dart:218:9)
I/flutter (25002): #7      RenderCustomPaint._paintWithPainter (package:flutter/src/rendering/custom_paint.dart:523:13)
I/flutter (25002): #8      RenderCustomPaint.paint (package:flutter/src/rendering/custom_paint.dart:566:7)
I/flutter (25002): #9      RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2104:7)
I/flutter (25002): #10     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:173:13)
I/flutter (25002): #11     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:123:15)
I/flutter (25002): #12     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2104:7)
I/flutter (25002): #13     PaintingContext._repaintCompositedChild (package:flutter/src/rendering/object.dart:128:11)
I/flutter (25002): #14     PaintingContext.repaintCompositedChild (package:flutter/src/rendering/object.dart:96:5)
I/flutter (25002): #15     PipelineOwner.flushPaint (package:flutter/src/rendering/object.dart:859:29)
I/flutter (25002): #16     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding.drawFrame (package:flutter/src/rendering/binding.dart:349:19)
I/flutter (25002): #17     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding&WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:701:13)
I/flutter (25002): #18     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:286:5)
I/flutter (25002): #19     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1012:15)
I/flutter (25002): #20     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:952:9)
I/flutter (25002): #21     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:864:5)
I/flutter (25002): #25     _invoke (dart:ui/hooks.dart:219:10)
I/flutter (25002): #26     _drawFrame (dart:ui/hooks.dart:178:3)
I/flutter (25002): (elided 5 frames from class _AssertionError and package dart:async)
I/flutter (25002): 
I/flutter (25002): The following RenderObject was being processed when the exception was fired:
I/flutter (25002):   RenderCustomPaint#5cfed relayoutBoundary=up5
I/flutter (25002):   creator: CustomPaint ← RepaintBoundary ← NotificationListener<ScrollNotification> ← Scrollbar ←
I/flutter (25002):   NotificationListener<OverscrollIndicatorNotification> ←
I/flutter (25002):   NotificationListener<ScrollNotification>-[GlobalKey#8f3db] ← Stack ←
I/flutter (25002):   RefreshIndicator-[LabeledGlobalKey<RefreshIndicatorState>#3c40e] ← Flexible ← Column ← Stack ←
I/flutter (25002):   MediaQuery ← ⋯
I/flutter (25002):   parentData: <none> (can use size)
I/flutter (25002):   constraints: BoxConstraints(0.0<=w<=360.0, 0.0<=h<=495.0)
I/flutter (25002):   size: Size(360.0, 0.0)
I/flutter (25002): This RenderObject had the following descendants (showing up to depth 5):
I/flutter (25002):   RenderRepaintBoundary#316c3 relayoutBoundary=up6
I/flutter (25002):     RenderRepaintBoundary#a03a8 relayoutBoundary=up7
I/flutter (25002):       RenderCustomPaint#dd408 relayoutBoundary=up8
I/flutter (25002):         RenderRepaintBoundary#27471 relayoutBoundary=up9
I/flutter (25002):           _RenderScrollSemantics#b5007 relayoutBoundary=up10
I/flutter (25002): ════════════════════════════════════════════════════════════════════════════════════════════════════
I/flutter (25002): {"_id":null,"count":12}
I/flutter (25002): [{"_id":"5d00b5fb1b61d305a92234c5","status":"Opportunity","serialNumber":19,"date":"2019-06-12T08:21:15.807Z","salesperson":"Dwight Schrute"},{"_id":"5cbde86198edd338c2faa5cc","status":"Opportunity","serialNumber":17,"date":"2019-04-22T16:14:25.152Z","property":{"_id":"584efea5fc6ad00d29de5152","name":"Shops at Dakota Crossing"},"client":{"_id":"584efe61fc6ad00d29de514f","name":"CBRE Washington DC"},"salesperson":"Dwight Schrute"},{"_id":"5cbdd2db98edd338c2faa5ac","status":"Opportunity","serialNumber":16,"date":"2019-04-22T14:42:35.680Z","source":"This","dueDate":"2019-04-16T04:00:00.000Z","property":{"_id":"5c768b8efbf9410db664a54d","name":"Scranton Branch"},"client":{"_id":"5c26282a0017651e7fefa963","name":"Dunder Mifflin"},"salesperson":"Paul Test"},{"_id":"5cbdd2c598edd338c2faa5a0","status":"Opportunity","serialNumber":15,"date":"2019-04-22T14:42:13.016Z","salesperson":"Dwight Schrute"},{"_id":"5cacae9e6ce2222e0962ced4","status":"Opportunity","serialNumber":14,"date":"2019-04-09T14:39:26.510Z","property"
```

```
D:\dev\pavement>flutter doctor -v
[√] Flutter (Channel stable, v1.5.4-hotfix.2, on Microsoft Windows [Version 10.0.17134.765], locale en-GB)
    • Flutter version 1.5.4-hotfix.2 at C:\tools\flutter
    • Framework revision 7a4c33425d (8 weeks ago), 2019-04-29 11:05:24 -0700
    • Engine revision 52c7a1e849
    • Dart version 2.3.0 (build 2.3.0-dev.0.5 a1668566e5)


[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at c:\tools\Android-SDK
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = c:\tools\Android-SDK
    • Java binary at: C:\tools\android-studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
    • All Android licenses accepted.

[√] Android Studio (version 3.4)
    • Android Studio at C:\tools\android-studio
    • Flutter plugin version 36.1.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

[!] VS Code, 32-bit edition (version 1.34.0)
    • VS Code at C:\Program Files (x86)\Microsoft VS Code
    X Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[√] Connected device (1 available)
    • LGM G600L • LGMG600Lf8469764 • android-arm64 • Android 8.0.0 (API 26)

! Doctor found issues in 1 category.
```

**Comment by LongCatIsLooong** [comment]
@duzenko could you try running the code against the current master branch? It might have been fixed on master already.

**Comment by duzenko** [comment]
@LongCatIsLooong 
How do I do that?

**Comment by LongCatIsLooong** [comment]
Run `flutter channel master`
https://github.com/flutter/flutter/wiki/Flutter-build-release-channels

**Comment by duzenko** [comment]
Apparently does not happen in master

**Comment by LongCatIsLooong** [comment]
@duzenko thanks for confirming! I'm going to close the issue. The next stable release will contain the fix.
