### ISSUE TITLE
Trying navigating to Next screen from Login screen, getting error  Another exception was thrown: There are multiple heroes that share the same tag within a subtree.

### ISSUE THREAD

**Issue by MuthuSubramaniam** [flutter/flutter#35039]
In my Login Page 
```dart
 @override
  Widget build(BuildContext context) {
    _mContext = context;
    return new Scaffold(
      body: new Stack(
        children: <Widget>[
          new Container(
            decoration: new BoxDecoration(
              image: new DecorationImage(
                image: new AssetImage("assets/images/bg.png"),
                fit: BoxFit.fill,
              ),
            ),
          ),
          loginMainUI(context, ctrlUserName, ctrlUserPassword, _onLoginTapped,
              _moveToForgotPassword, _ppOrToUTapped)
        ],
      ),
    );
  }

  void _onLoginTapped() {
    print(ctrlUserName.text.toString());
    print(ctrlUserPassword.text.toString());
  }

  void _moveToForgotPassword() {
    print('Forgot password tapped');
    Navigator.pushNamed(context, '/home');
  }
`
***loginMainUI***
`Widget loginMainUI(
  BuildContext context,
  TextEditingController ctrlUserName,
  TextEditingController ctrlUserPassword,
  Function _onLoginTapped,
  Function _moveToForgotPassword,
  Function _ppOrToUTapped,
) {
  final double deviceWidth = MediaQuery.of(context).size.width;

  return Container(
    child: Padding(
      padding: EdgeInsets.symmetric(horizontal: 30.0),
      child: new SingleChildScrollView(
        child: Container(
          child: Column(
            mainAxisAlignment: MainAxisAlignment.center,
            crossAxisAlignment: CrossAxisAlignment.center,
            children: <Widget>[
              VerticalSpacing(height: 50.0),
              Image.asset(
                "assets/ic_header_logo_white.png",
                fit: BoxFit.contain,
                height: 40,
              ),
              VerticalSpacing(
                height: 50.0,
              ),
              loginTextField("Email or Mobile Number(60)", ctrlUserName, false,
                  TextInputType.emailAddress),
              VerticalSpacing(
                height: 20.0,
              ),
              loginTextField(
                  "Password", ctrlUserPassword, true, TextInputType.text),
              VerticalSpacing(
                height: 30.0,
              ),
              forgotPasswordButton(_moveToForgotPassword),
             /* InkWell(
                child: new Text(
                  'Forgot Password?',
                  style: TextStyle(
                    fontSize: 15,
                    color: Colors.white,
                    decoration: TextDecoration.underline,
                  ),
                ),
                onTap: () => _moveToForgotPassword,
              ),*/
              VerticalSpacing(
                height: 30.0,
              ),
              SizedBox(
                width: double.infinity,
                child: RaisedButton(
                  textColor: Colors.white,
                  color: Colors.blue,
                  shape: new RoundedRectangleBorder(
                      borderRadius: new BorderRadius.circular(3.0)),
                  onPressed: _onLoginTapped,
                  child: Text(
                    "Sign In",
                    style: TextStyle(fontWeight: FontWeight.bold),
                  ),
                ),
              ),
              VerticalSpacing(height: 30.0),
              Row(
                crossAxisAlignment: CrossAxisAlignment.center,
                children: <Widget>[
                  Expanded(
                    child: new Container(
                        height: 1,
                        width: deviceWidth * .3,
                        color: Colors.white),
                  ),
                  Text(
                    '  OR  ',
                    style: TextStyle(color: Colors.white),
                  ),
                  Expanded(
                    child: new Container(
                        height: 1,
                        width: deviceWidth * .3,
                        color: Colors.white),
                  ),
                ],
              ),
              Row(
                children: <Widget>[
                  Expanded(
                    child: new Container(
                      padding: EdgeInsets.only(top: 10),
                      child: FloatingActionButton(
                          backgroundColor: Colors.white,
                          onPressed: () {},
                          child: Image.asset('assets/images/facebookIcon.png')),
                    ),
                  ),
                  Expanded(
                    child: new Container(
                      padding: EdgeInsets.only(top: 10),
                      child: FloatingActionButton(
                          backgroundColor: Colors.white,
                          onPressed: () {},
                          child: Image.asset('assets/images/googleIcon.png')),
                    ),
                  ),
                ],
              ),
              VerticalSpacing(
                height: 20.0,
              ),
              InkWell(
                child: new RichText(
                  text: new TextSpan(
                    style: new TextStyle(
                      fontSize: 14.0,
                      color: Colors.white,
                    ),
                    children: <TextSpan>[
                      new TextSpan(text: 'New User? '),
                      new TextSpan(
                          text: 'Sign up here',
                          style: new TextStyle(fontWeight: FontWeight.bold)),
                    ],
                  ),
                ),
              ),
              VerticalSpacing(
                height: 20.0,
              ),
              Row(
                mainAxisAlignment: MainAxisAlignment.center,
                children: <Widget>[
                  InkWell(
                    child: Text(
                      'Privacy Policy',
                      style: TextStyle(
                          decoration: TextDecoration.underline,
                          color: Colors.white),
                    ),
                    onTap: () => _ppOrToUTapped(""),
                  ),
                  Text(
                    ' and ',
                    style: TextStyle(color: Colors.white),
                  ),
                  InkWell(
                    child: Text(
                      'Terms of Use',
                      style: TextStyle(
                          decoration: TextDecoration.underline,
                          color: Colors.white),
                    ),
                    onTap: () =>
                        _ppOrToUTapped(""),
                  ),
                ],
              ),
            ],
          ),
        ),
      ),
    ),
  );`

forgotPasswordButton
`import 'package:flutter/material.dart';

Widget forgotPasswordButton(Function moveToForgotPassword) {
  return Center(
    child: Opacity(
      opacity: 0.2,
      child: RaisedButton(
          child: Text('Forgot Password?',style: TextStyle(color: Colors.white),),
          onPressed: () => moveToForgotPassword()),
    ),
  );
}
`


================
Error
Another exception was thrown: There are multiple heroes that share the same tag within a subtree.

 Forgot password tapped
 ══╡ EXCEPTION CAUGHT BY SCHEDULER LIBRARY ╞═════════════════════════════════════════════════════════
 The following assertion was thrown during a scheduler callback:
 There are multiple heroes that share the same tag within a subtree.
 Within each subtree for which heroes are to be animated (typically a PageRoute subtree), each Hero
 must have a unique non-null tag.
 In this case, multiple heroes had the following tag: <default FloatingActionButton tag>
 Here is the subtree for one of the offending heroes:
 # Hero(tag: <default FloatingActionButton tag>, state: _HeroState#4a4c8)
 # └KeyedSubtree-[GlobalKey#86553]
 #  └RawMaterialButton(state: _RawMaterialButtonState#40898)
 #   └Semantics(container: true, properties: SemanticsProperties, label: null, value: null, hint: null, hintOverrides: null, renderObject: RenderSemanticsAnnotations#c7a67 relayoutBoundary=up16)
 #    └_InputPadding(renderObject: _RenderInputPadding#cb7db relayoutBoundary=up17)
 #     └ConstrainedBox(BoxConstraints(w=56.0, h=56.0), renderObject: RenderConstrainedBox#1122f relayoutBoundary=up18)
 #      └Material(type: button, elevation: 6.0, color: Color(0xffffffff), textStyle.debugLabel: ((englishLike button 2014).merge((whiteMountainView button).apply)).copyWith, textStyle.inherit: false, textStyle.color: Color(0xffffffff), textStyle.family: Monstserrat, textStyle.size: 14.0, textStyle.weight: 500, textStyle.letterSpacing: 1.2, textStyle.baseline: alphabetic, textStyle.decoration: TextDecoration.none, shape: CircleBorder(BorderSide(Color(0xff000000), 0.0, BorderStyle.none)), state: _MaterialState#aa0ca)
 #       └_MaterialInterior(duration: 200ms, shape: CircleBorder(BorderSide(Color(0xff000000), 0.0, BorderStyle.none)), elevation: 6.0, color: Color(0xffffffff), shadowColor: Color(0xff000000), state: _MaterialInteriorState#4e32f(ticker inactive))
 #        └PhysicalShape(clipper: ShapeBorderClipper, elevation: 6.0, color: Color(0xffffffff), shadowColor: Color(0xff000000), renderObject: RenderPhysicalShape#96db6)
 #         └_ShapeBorderPaint
 #          └CustomPaint(renderObject: RenderCustomPaint#535bf)
 #           └NotificationListener<LayoutChangedNotification>
 #            └_InkFeatures-[GlobalKey#8def5 ink renderer](renderObject: _RenderInkFeatures#32662)
 #             └AnimatedDefaultTextStyle(duration: 200ms, debugLabel: ((englishLike button 2014).merge((whiteMountainView button).apply)).copyWith, inherit: false, color: Color(0xffffffff), family: Monstserrat, size: 14.0, weight: 500, letterSpacing: 1.2, baseline: alphabetic, decoration: TextDecoration.none, softWrap: wrapping at box width, overflow: clip, state: _AnimatedDefaultTextStyleState#9b797(ticker inactive))
 #              └DefaultTextStyle(debugLabel: ((englishLike button 2014).merge((whiteMountainView button).apply)).copyWith, inherit: false, color: Color(0xffffffff), family: Monstserrat, size: 14.0, weight: 500, letterSpacing: 1.2, baseline: alphabetic, decoration: TextDecoration.none, softWrap: wrapping at box width, overflow: clip)
 #               └InkWell(gestures: [tap], clipped to BoxShape.rectangle, state: _InkResponseState<InkResponse>#2d196)
 #                └GestureDetector
 #                 └RawGestureDetector(state: RawGestureDetectorState#57be3(gestures: [tap], behavior: opaque))
 #                  └_GestureSemantics(renderObject: RenderSemanticsGestureHandler#c6787)
 #                   └Listener(listeners: [down], behavior: opaque, renderObject: RenderPointerListener#f1e01)
 #                    └Builder
 #                     └IconTheme(IconThemeData#15fa8(color: Color(0xffffffff)))
 #                      └Container(padding: EdgeInsets.zero)
 #                       └Padding(padding: EdgeInsets.zero, renderObject: RenderPadding#719d5)
 #                        └Center(alignment: center, widthFactor: 1.0, heightFactor: 1.0, renderObject: RenderPositionedBox#82b3b)
 #                         └Builder
 #                          └IconTheme(IconThemeData#15fa8(color: Color(0xffffffff)))
 #                           └Image(image: AssetImage(bundle: null, name: "assets/images/googleIcon.png"), alignment: center, this.excludeFromSemantics: false, filterQuality: low, state: _ImageState#e02be(stream: ImageStream#e754b(MultiFrameImageStreamCompleter#8628c, [32×32] @ 1.0x, 1 listener), pixels: [32×32] @ 1.0x))
 #                            └Semantics(container: false, properties: SemanticsProperties, value: null, hint: null, hintOverrides: null, renderObject: RenderSemanticsAnnotations#2dcf1 relayoutBoundary=up1)
 #                             └RawImage(image: [32×32], alignment: center, invertColors: false, filterQuality: low, renderObject: RenderImage#8c6ee relayoutBoundary=up2)
 
 When the exception was thrown, this was the stack:
 #0      Hero._allHeroesFor.visitor.<anonymous closure> (package:flutter/src/widgets/heroes.dart:210:15)
 #1      Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:220:12)
 #2      ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3755:14)
 #3      Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:225:15)
 #4      SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:4848:14)
 #5      Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:225:15)
 #6      ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3755:14)
 #7      Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:225:15)
 #8      ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3755:14)
 #9      Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:225:15)
 #10     MultiChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:4948:16)
 #11     Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:225:15)
 #12     MultiChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:4948:16)
 #13     Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:225:15)
 #14     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3755:14)
 #15     Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:225:15)
 #16     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:4848:14)
 #17     Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:225:15)
 #18     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3755:14)
 #19     Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:225:15)
 #20     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:4848:14)
 #21     Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:225:15)
 #22     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:4848:14)
 #23     Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:225:15)
 #24     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:4848:14)
 #25     Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:225:15)
 #26     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:4848:14)
 #27     Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:225:15)
 #28     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3755:14)
 #29     Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:225:15)
 #30     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:4848:14)
 #31     Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:225:15)
 #32     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:4848:14)
 #33     Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:225:15)
 #34     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:4848:14)
 #35     Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:225:15)
 #36     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:4848:14)
 #37     Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:225:15)
 #38     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3755:14)
 #39     Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:225:15)
 #40     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3755:14)
 #41     Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:225:15)
 #42     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3755:14)
 #43     Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:225:15)
 #44     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3755:14)
 #45     Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:225:15)
 #46     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3755:14)
 #47     Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:225:15)
 #48     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:4848:14)
 #49     Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:225:15)
 #50     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3755:14)
 #51     Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:225:15)
 #52     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:4848:14)
 #53     Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:225:15)
 #54     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3755:14)
 #55     Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:225:15)
 #56     MultiChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:4948:16)
 #57     Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:225:15)
 #58     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3755:14)
 #59     Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:225:15)
 #60     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3755:14)
 #61     Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:225:15)
 #62     MultiChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:4948:16)
 #63     Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:225:15)
 #64     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3755:14)
 #65     Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:225:15)
 #66     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3755:14)
 #67     Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:225:15)
 #68     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3755:14)
 #69     Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:225:15)
 #70     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:4848:14)
 #71     Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:225:15)
 #72     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3755:14)
 #73     Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:225:15)
 #74     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:4848:14)
 #75     Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:225:15)
 #76     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3755:14)
 #77     Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:225:15)
 #78     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3755:14)
 #79     Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:225:15)
 #80     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3755:14)
 #81     Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:225:15)
 #82     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3755:14)
 #83     Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:225:15)
 #84     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3755:14)
 #85     Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:225:15)
 #86     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3755:14)
 #87     Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:225:15)
 #88     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:4848:14)
 #89     Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:225:15)
 #90     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:3755:14)
 #91     Hero._allHeroesFor.visitor (package:flutter/src/widgets/heroes.dart:225:15)
 #92     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:4848:14)
 #93     Element.visitChildElements (package:flutter/src/widgets/framework.dart:2686:5)
 #94     Hero._allHeroesFor (package:flutter/src/widgets/heroes.dart:227:13)
 #95     HeroController._startHeroTransition (package:flutter/src/widgets/heroes.dart:655:53)
 #96     HeroController._maybeStartHeroTransition.<anonymous closure> (package:flutter/src/widgets/heroes.dart:630:11)
 #97     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:990:15)
 #98     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:938:9)
 #99     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:842:5)
 #100    _invoke (dart:ui/hooks.dart:154:13)
 #101    _drawFrame (dart:ui/hooks.dart:143:3)
 ════════════════════════════════════════════════════════════════════════════════════════════════════
```

**Comment by BondarenkoStas** [comment]
@MuthuSubramaniam Can you please try it using current flutter stable? I think if should have been fixed in https://github.com/flutter/flutter/pull/29069.

**Comment by iapicca** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
  
Thanks for your contribution.
