### ISSUE TITLE
Flutter crash report

### ISSUE THREAD

**Issue by JamesKarl** [flutter/flutter#35032]
Flutter crash report; please file at https://github.com/flutter/flutter/issues.

## command

flutter build ios

## exception

FormatException: FormatException: Bad UTF-8 encoding 0x3f (at offset 1702)

```
#0      _Utf8Decoder.convert (dart:convert/utf.dart:444:15)
#1      _Utf8ConversionSink.addSlice (dart:convert/string_conversion.dart:309:14)
#2      _Utf8ConversionSink.add (dart:convert/string_conversion.dart:305:5)
#3      _ConverterStreamEventSink.add (dart:convert/chunked_conversion.dart:72:18)
#4      _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:120:24)
#5      _rootRunUnary (dart:async/zone.dart:1132:38)
#6      _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#7      _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
#8      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#9      _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#10     _SyncStreamController._sendData (dart:async/stream_controller.dart:764:19)
#11     _StreamController._add (dart:async/stream_controller.dart:640:7)
#12     _StreamController.add (dart:async/stream_controller.dart:586:5)
#13     _Socket._onData (dart:io-patch/socket_patch.dart:1774:41)
#14     _rootRunUnary (dart:async/zone.dart:1136:13)
#15     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#16     _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
#17     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#18     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#19     _SyncStreamController._sendData (dart:async/stream_controller.dart:764:19)
#20     _StreamController._add (dart:async/stream_controller.dart:640:7)
#21     _StreamController.add (dart:async/stream_controller.dart:586:5)
#22     new _RawSocket.<anonymous closure> (dart:io-patch/socket_patch.dart:1323:33)
#23     _NativeSocket.issueReadEvent.issue (dart:io-patch/socket_patch.dart:844:14)
#24     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#25     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#26     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:115:13)
#27     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:5)
```

## flutter doctor

```
[33m[!][39m Flutter (Channel stable, v1.5.4-hotfix.2, on Mac OS X 10.15 19A471t, locale en-CN)
    [32m•[39m Flutter version 1.5.4-hotfix.2 at /Users/jameskarl/devenv/dart/flutter-stable
    [32m•[39m Framework revision 7a4c33425d (8 weeks ago), 2019-04-29 11:05:24 -0700
    [32m•[39m Engine revision 52c7a1e849
    [32m•[39m Dart version 2.3.0 (build 2.3.0-dev.0.5 a1668566e5)
    [31m✗[39m Downloaded executables cannot execute on host.
      See https://github.com/flutter/flutter/issues/6207 for more information


[32m[✓][39m Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    [32m•[39m Android SDK at /Users/jameskarl/devenv/android/android-sdk-macosx/
    [32m•[39m Android NDK location not configured (optional; useful for native profiling support)
    [32m•[39m Platform android-28, build-tools 28.0.3
    [32m•[39m ANDROID_HOME = /Users/jameskarl/devenv/android/android-sdk-macosx
    [32m•[39m Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    [32m•[39m Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
    [32m•[39m All Android licenses accepted.

[32m[✓][39m iOS toolchain - develop for iOS devices (Xcode 10.2.1)
    [32m•[39m Xcode at /Applications/Xcode.app/Contents/Developer
    [32m•[39m Xcode 10.2.1, Build version 10E1001
    [32m•[39m ios-deploy 1.9.4
    [32m•[39m CocoaPods version 1.7.2

[32m[✓][39m Android Studio (version 3.4)
    [32m•[39m Android Studio at /Applications/Android Studio.app/Contents
    [32m•[39m Flutter plugin version 36.1.1
    [32m•[39m Dart plugin version 183.6270
    [32m•[39m Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

[32m[✓][39m IntelliJ IDEA Ultimate Edition (version 2018.3.6)
    [32m•[39m IntelliJ at /Applications/IntelliJ IDEA.app
    [32m•[39m Flutter plugin version 34.0.2
    [32m•[39m Dart plugin version 183.6156.10

[32m[✓][39m VS Code (version 1.34.0)
    [32m•[39m VS Code at /Applications/Visual Studio Code.app/Contents
    [32m•[39m Flutter extension version 3.1.0

[33m[!][39m Connected device
    [33m![39m No devices available

[33m![39m Doctor found issues in 2 categories.
```

**Comment by rashedmyt** [comment]
@JamesKarl can you try what's mentioned here https://github.com/flutter/flutter/issues/6207#issuecomment-418595627 and report back

**Comment by kangwang1988** [comment]
The utf-8 issue seems not related to #6207
@JamesKarl Can you try to debug the flutter_tools to see which kind of log is causing the utf8 issue, it appears from time to time. However, I can't diagnose it as i can't reproduce it.

**Comment by JamesKarl** [comment]
@kangwang1988 I am sorry for delay. It worked well before I upgraded Xcode to 11.0 beta (11M336w) and Mac OS to 10.15 Beta (19A471t). It still works well in my workmate's build environment(Mac OS too) with the exact same code base. 

I am sorry that I don't know how to debug the flutter_tools. Could you supply some tutorial or steps on how to debug flutter_tools? thank you very much.

**Comment by JamesKarl** [comment]
@rashedmyt  Thank you for your support. #6207 is "Run as a release on Ubuntu 16.04 / libstdc++.so.6 reported missing".  But I am working on Mac OS to 10.15 Beta.

**Comment by JamesKarl** [comment]
@kangwang1988 
I tried the solution mentioned in #6207 which could not solve my problem. My build environment is Mac OS 10.15 Beta,  Xcode to 11.0 beta.

rm -rf flutter/bin/cache
flutter doctor -v

[!] Flutter (Channel stable, v1.5.4-hotfix.2, on Mac OS X 10.15 19A471t, locale en-CN)
    • Flutter version 1.5.4-hotfix.2 at /Users/jameskarl/devenv/dart/flutter-stable
    • Framework revision 7a4c33425d (8 weeks ago), 2019-04-29 11:05:24 -0700
    • Engine revision 52c7a1e849
    • Dart version 2.3.0 (build 2.3.0-dev.0.5 a1668566e5)
    ✗ Downloaded executables cannot execute on host.
      See https://github.com/flutter/flutter/issues/6207 for more information

**Comment by rashedmyt** [comment]
@JamesKarl looks like many are facing this issue.. #33909

**Comment by JamesKarl** [comment]
@rashedmyt the following temporary solution from #33909 is okay to me. Maybe that is the root cause. It's expected to be fixed in future ASAP. Thank you very much.

> @kangwang1988 temporary solution for iOS is to remove armv7 and armv7s from Valid architectures in Build Settings section. It drops support for iPhone 5, iPhone 5C, iPad 4 and older devices
