### ISSUE TITLE
Exception while typing stuff randomly into a TextField

### ISSUE THREAD

**Issue by marcglasberg** [flutter/flutter#35068]
This exception was thrown while I was typing stuff randomly into a TextField:

```
I/flutter ( 3891): ══╡ EXCEPTION CAUGHT BY SERVICES LIBRARY ╞══════════════════════════════════════════════════════════
I/flutter ( 3891): The following NoSuchMethodError was thrown during a platform message callback:
I/flutter ( 3891): The getter 'length' was called on null.
I/flutter ( 3891): Receiver: null
I/flutter ( 3891): Tried calling: length
I/flutter ( 3891): 
I/flutter ( 3891): When the exception was thrown, this was the stack:
I/flutter ( 3891): #0      Object.noSuchMethod (dart:core-patch/object_patch.dart:50:5)
I/flutter ( 3891): #1      RenderEditable._handleHorizontalArrows (package:flutter/src/rendering/editable.dart:431:49)
I/flutter ( 3891): #2      RenderEditable._handleKeyEvent (package:flutter/src/rendering/editable.dart:400:19)
I/flutter ( 3891): #3      RawKeyboard._handleKeyEvent (package:flutter/src/services/raw_keyboard.dart:494:17)
I/flutter ( 3891): <asynchronous suspension>
I/flutter ( 3891): #4      BasicMessageChannel.setMessageHandler.<anonymous closure> (package:flutter/src/services/platform_channel.dart:65:49)
I/flutter ( 3891): <asynchronous suspension>
I/flutter ( 3891): #5      BinaryMessages.handlePlatformMessage (package:flutter/src/services/platform_messages.dart:76:33)
I/flutter ( 3891): <asynchronous suspension>
I/flutter ( 3891): #6      _invoke3.<anonymous closure> (dart:ui/hooks.dart:263:15)
I/flutter ( 3891): #10     _invoke3 (dart:ui/hooks.dart:262:10)
I/flutter ( 3891): #11     _dispatchPlatformMessage (dart:ui/hooks.dart:136:5)
I/flutter ( 3891): (elided 3 frames from package dart:async)
I/flutter ( 3891): ════════════════════════════════════════════════════════════════════════════════════════════════════

```

```
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, v1.5.4-hotfix.2, on Microsoft Windows [Version 10.0.17763.557], locale pt-BR)

[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[√] Android Studio (version 3.2)
[√] IntelliJ IDEA Ultimate Edition (version 2018.3)
[√] IntelliJ IDEA Ultimate Edition (version 2019.1)
[√] Connected device (1 available)

• No issues found!

```

**Comment by TahaTesser** [comment]
Hi @marcglasberg 
Are you still experiencing this issue with latest stable?
can you please provide your `flutter doctor -v` and `flutter run --verbose`? Also, to better address the issue, would be helpful if you could post a minimal code sample to reproduce the problem Thank you
Thank you

**Comment by marcglasberg** [comment]
@TahaTesser No, I'm not. I'll close this. And reopen if I see it again. Thanks.
