### ISSUE TITLE
Cannot write in text field

### ISSUE THREAD

**Issue by AliShehab93** [flutter/flutter#35069]
```
 16 of 1089 libraries in 849ms.
flutter: ══╡ EXCEPTION CAUGHT BY GESTURE ╞═══════════════════════════════════════════════════════════════════
flutter: The following assertion was thrown while handling a gesture:
flutter: 'package:flutter/src/widgets/text_selection.dart': Failed assertion: line 335 pos 12: '_toolbar ==
flutter: null': is not true.
flutter:
flutter: Either the assertion indicates an error in the framework itself, or we should provide substantially
flutter: more information in this error message to help you determine and fix the underlying cause.
flutter: In either case, please report this assertion by filing a bug on GitHub:
flutter:   https://github.com/flutter/flutter/issues/new?template=BUG.md
flutter:
flutter: When the exception was thrown, this was the stack:
flutter: #2      TextSelectionOverlay.showToolbar (package:flutter/src/widgets/text_selection.dart:335:12)
flutter: #3      EditableTextState.showToolbar (package:flutter/src/widgets/editable_text.dart:1373:23)
flutter: #4      _TextFieldState._handleSingleLongTapEnd (package:flutter/src/material/text_field.dart:741:35)
flutter: #5      _TextSelectionGestureDetectorState._handleLongPressEnd (package:flutter/src/widgets/text_selection.dart:896:14)
flutter: #6      LongPressGestureRecognizer.handlePrimaryPointer.<anonymous closure> (package:flutter/src/gestures/long_press.dart:198:13)
flutter: #7      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:166:24)
flutter: #8      LongPressGestureRecognizer.handlePrimaryPointer (package:flutter/src/gestures/long_press.dart:197:11)
flutter: #9      PrimaryPointerGestureRecognizer.handleEvent (package:flutter/src/gestures/recognizer.dart:436:9)
flutter: #10     PointerRouter._dispatch (package:flutter/src/gestures/pointer_router.dart:73:12)
flutter: #11     PointerRouter.route (package:flutter/src/gestures/pointer_router.dart:101:11)
flutter: #12     _WidgetsFlutterBinding&BindingBase&GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:221:19)
flutter: #13     _WidgetsFlutterBinding&BindingBase&GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:199:22)
flutter: #14     _WidgetsFlutterBinding&BindingBase&GestureBinding._handlePointerEvent (package:flutter/src/gestures/binding.dart:156:7)
flutter: #15     _WidgetsFlutterBinding&BindingBase&GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:102:7)
flutter: #16     _WidgetsFlutterBinding&BindingBase&GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:86:7)
flutter: #20     _invoke1 (dart:ui/hooks.dart:233:10)
flutter: #21     _dispatchPointerDataPacket (dart:ui/hooks.dart:154:5)
flutter: (elided 5 frames from class _AssertionError and package dart:async)
flutter:
flutter: Handler: onLongPressEnd
flutter: Recognizer:
flutter:   LongPressGestureRecognizer#fcdb9(debugOwner: _TextSelectionGestureDetectorState#ed101, state:
flutter:   possible)
flutter: ════════════════════════════════════════════════════════════════════════════════════════════════════
```

**Comment by HansMuller** [comment]
If you provide the output of flutter doctor, to help us understand what version of Flutter you're using and what device/emulator you're targeting, and a small self contained app that demonstrates the problem, we'll look into it.

**Comment by AliShehab93** [comment]
Hello HansMuller... I will tell you the problem that I faced since I changed my structure when I faced this issue. This problem was that I put in a stack two scaffolds in children, the first one is always visible but the other scaffold is under a visibility widget thus in my stack I have scaffold and a visibility widget which has a scaffold. in the first scaffold, I have pages with button navigation and in the other scaffold, I have a container with text fields and buttons, etc.. The problem is that when I open this scaffold to add post so I need to add text to text fields, the text fields are disabled and I cannot add to it anything but I can click on buttons. This is the problem and I didn't understand the problem.
Hope you can find a solution to that.
Thank you

**Comment by Hixie** [comment]
We really need a small self contained app that demonstrates the problem, like Hans said. Without it it's really hard for us to know how to even reproduce the issue.
