### ISSUE TITLE
Google Map crashes Android App - Flutter

### ISSUE THREAD

**Issue by TecHaxter** [flutter/flutter#35071]
The Error showed when I logged in again, each time: 
```
I/Google Maps Android API( 2899): Google Play services package version: 17455037
W/System  ( 2899): A resource failed to call release.
W/ter.geolocatio( 2899): Accessing hidden method Ldalvik/system/CloseGuard;->warnIfOpen()V (light greylist, linking)
I/flutter ( 2899): Map Created
D/libEGL  ( 2899): eglInitialize: enter
D/libEGL  ( 2899): eglInitialize: exit(res=1)
W/com.flutter.geolocation( 2899): type=1400 audit(0.0:20303): avc: denied { search } for comm=474C5468726561642037393734 name="ctx" dev="debugfs" ino=15090 scontext=u:r:untrusted_app_27:s0:c512,c768 tcontext=u:object_r:qti_debugfs:s0 tclass=dir permissive=0
D/AndroidRuntime( 2899): Shutting down VM
E/AndroidRuntime( 2899): FATAL EXCEPTION: main
E/AndroidRuntime( 2899): Process: com.flutter.geolocation, PID: 2899
E/AndroidRuntime( 2899): java.lang.NullPointerException: Attempt to invoke virtual method 'int android.view.Display.getDisplayId()' on a null object reference
E/AndroidRuntime( 2899):        at android.view.ViewRootImpl$ViewRootHandler.handleMessage(ViewRootImpl.java:4260)
E/AndroidRuntime( 2899):        at android.os.Handler.dispatchMessage(Handler.java:106)
E/AndroidRuntime( 2899):        at android.os.Looper.loop(Looper.java:201)
E/AndroidRuntime( 2899):        at android.app.ActivityThread.main(ActivityThread.java:6806)
E/AndroidRuntime( 2899):        at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime( 2899):        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
E/AndroidRuntime( 2899):        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:873)
E/MQSEventManagerDelegate( 2899): failed to get MQSService.
I/Process ( 2899): Sending signal. PID: 2899 SIG: 9
Lost connection to device.
```
Code :
```
 GoogleMapController mapController;
  Location location = new Location();

  Map<PolylineId, Polyline> _mapPolylines = {};
  int _polylineIdCounter = 1;

  final List<LatLng> points = <LatLng>[];


  getRoute() {
    Firestore.instance
      .collection(widget.institute)
      .document(widget.bus)
      .collection('Route')
      .snapshots()
      .listen(
        (snap)  => snap.documents.forEach((doc){
          print(doc.data['LatLng'].latitude.toString());
          points.add(LatLng(doc.data['LatLng'].latitude, doc.data['LatLng'].longitude));                   
        }),
      );
  }

  @override
  void initState() {
    super.initState();
    getRoute();
  }


  @override
  Widget build(BuildContext context) {
    
    return Scaffold(
      appBar: AppBar(
        title: Text("GeoLocation"),
      ),
      drawer: DrawerWidget(name: widget.name, userID: widget.userID,),
      body: Stack(
        children: <Widget>[
          GoogleMap(
            initialCameraPosition: CameraPosition(
              target: LatLng(26.2389, 73.0243),
              zoom: 12
            ),
            rotateGesturesEnabled: true,
            compassEnabled: true,
            onMapCreated: _onMapCreated,
            myLocationEnabled: true,
            myLocationButtonEnabled: false,
            mapType: MapType.normal,
            polylines: Set<Polyline>.of(_mapPolylines.values),
          ),
          Positioned(
            bottom: 50,
            right: 20,
            child: RawMaterialButton(
              child: Icon(Icons.gps_fixed, size: 30.0),
              fillColor: white,
              shape: new CircleBorder(),
              onPressed: () => {} , //_animateToUser,
              padding: EdgeInsets.all(8.0),
            ),
          ),
          StreamBuilder(
            stream: Firestore.instance.collection(widget.institute.toString()).document(widget.bus.toString()).collection("Driver").snapshots(),
            builder: (context, snap) {
              if(snap.hasData) {
                List<DocumentSnapshot> snapshot = snap.data.documents;
                if(snapshot[0]['session'] == 1)
                {
                  return Container(
                    height: 50,
                    width: double.infinity,
                    child: Text("Online", textAlign: TextAlign.center,),
                    color: white,
                  );
                } else {
                  return Container(
                    height: 50,
                    width: double.infinity,
                    child: Text("Offline", textAlign: TextAlign.center,),
                    color: white,
                  );
                }
              } else {
                return Container(
                    child: Text("Error Data"),
                );
              }
            },
          )
        ],
      ),
    );
  }

  void _add() {
    final String polylineIdVal = 'polyline_id_$_polylineIdCounter';
    _polylineIdCounter++;
    final PolylineId polylineId = PolylineId(polylineIdVal);

    final Polyline polyline = Polyline(
      polylineId: polylineId,
      consumeTapEvents: true,
      color: Colors.grey,
      width: 20,
      points: points,
    );

    setState(() {
      _mapPolylines[polylineId] = polyline;
    });
  }

  _animateToUser() async {
    //location.onLocationChanged();
    var pos = await location.getLocation();
    mapController.animateCamera(CameraUpdate.newCameraPosition(
      CameraPosition(
        target: LatLng(pos.latitude, pos.longitude),
        zoom: 17.0,
      )
    ));
  }

  _onMapCreated(GoogleMapController controller) {
    _add();
    setState(() {
      mapController = controller;
    });
  }
```

When I removed GoogleMap Widget the code worked perfectly fine, so I again checked code inside GoogleMap e.g _onMapCreated function and the error was the same.
So I believe the error is only from GoogleMap Widget.

**Comment by rashedmyt** [comment]
most crashes occur due to not giving permissions in `AndroidManifest.xml` or `Info.plist` and your phone or emulator

**Comment by TecHaxter** [comment]
I have already gave permission in AndroidManifest.xml along with API key : 
'<meta-data android:name="com.google.android.geo.API_KEY"
               android:value="YOUR-KEY-HERE"/>'

**Comment by TecHaxter** [comment]
`    <uses-permission android:name="android.permission.ACCESS_FINE_LOCATION"/>
`
I have used Permissions.

**Comment by TahaTesser** [comment]
Hi @TecHaxter 

Please make sure you have properly the API key in Android Manifest [google_maps_flutter](https://pub.dev/packages/google_maps_flutter)

Try running this sample code

### Code Sample
```
import 'package:flutter/material.dart';
import 'package:google_maps_flutter/google_maps_flutter.dart';
import 'package:location/location.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      debugShowCheckedModeBanner: false,
      title: 'Material App',
      theme: ThemeData.dark(),
      home: Home(),
    );
  }
}

class Home extends StatefulWidget {
  @override
  _HomeState createState() => _HomeState();
}

class _HomeState extends State<Home> {
  GoogleMapController mapController;
  Location location = new Location();

  Map<PolylineId, Polyline> _mapPolylines = {};
  int _polylineIdCounter = 1;

  final List<LatLng> points = <LatLng>[];

  void _add() {
    final String polylineIdVal = 'polyline_id_$_polylineIdCounter';
    _polylineIdCounter++;
    final PolylineId polylineId = PolylineId(polylineIdVal);

    final Polyline polyline = Polyline(
      polylineId: polylineId,
      consumeTapEvents: true,
      color: Colors.pink,
      width: 20,
      points: points,
    );

    setState(() {
      _mapPolylines[polylineId] = polyline;
    });
  }

  _onMapCreated(GoogleMapController controller) {
    _add();
    setState(() {
      mapController = controller;
    });
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('Material App Bar'),
      ),
      body: Center(
        child: GoogleMap(
          initialCameraPosition:
              CameraPosition(target: LatLng(26.2389, 73.0243), zoom: 12),
          rotateGesturesEnabled: true,
          compassEnabled: true,
          myLocationEnabled: true,
          myLocationButtonEnabled: false,
          mapType: MapType.normal,
          onMapCreated: _onMapCreated,
          polylines: Set<Polyline>.of(_mapPolylines.values),
        ),
      ),
      floatingActionButton: FloatingActionButton(
        child: Icon(Icons.add),
        onPressed: () {},
      ),
    );
  }
}
```

if you're still experiencing this problem, please create a new issue and provide the information required in the template.
Thank you

**Comment by userasad** [comment]
In my case, it was due to the missing permission in AndroidManifest.xml 
Adding permission resolved my issue.

`<uses-permission android:name="android.permission.ACCESS_FINE_LOCATION"/>`
