### ISSUE TITLE
flutter has exited unexpectedly when flutter upgrade --force 

### ISSUE THREAD

**Issue by dannyZhou** [flutter/flutter#35105]
```
$ proxychains -q flutter upgrade --force 

Oops; flutter has exited unexpectedly.
Sending crash report to Google.
Crash report sent (report ID: 6ca911a35283973f)
 
Crash report written to /home/danny/sda4/git/flutter/flutter_01.log;
please let us know at https://github.com/flutter/flutter/issues.

# danny @ archlinux in ~/git/flutter on git:master o [15:43:54] C:1
```
$ cat flutter_01.log 
Flutter crash report; please file at https://github.com/flutter/flutter/issues.

## command

flutter upgrade --force

## exception

ProcessException: ProcessException: Process "git" exited abnormally:
fatal: ambiguous argument 'v0.0.0': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
  Command: git reset --hard v0.0.0

```
#0      runCheckedAsync (package:flutter_tools/src/base/process.dart:259:7)
<asynchronous suspension>
#1      UpgradeCommandRunner.resetChanges (package:flutter_tools/src/commands/upgrade.dart:135:39)
<asynchronous suspension>
#2      UpgradeCommandRunner.runCommand (package:flutter_tools/src/commands/upgrade.dart:86:11)
<asynchronous suspension>
#3      UpgradeCommand.runCommand (package:flutter_tools/src/commands/upgrade.dart:47:32)
<asynchronous suspension>
#4      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:478:18)
<asynchronous suspension>
#5      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:383:33)
<asynchronous suspension>
#6      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:29)
<asynchronous suspension>
#7      _rootRun (dart:async/zone.dart:1124:13)
#8      _CustomZone.run (dart:async/zone.dart:1021:19)
#9      _runZoned (dart:async/zone.dart:1516:10)
#10     runZoned (dart:async/zone.dart:1463:12)
#11     AppContext.run (package:flutter_tools/src/base/context.dart:152:18)
<asynchronous suspension>
#12     FlutterCommand.run (package:flutter_tools/src/runner/flutter_command.dart:375:20)
#13     CommandRunner.runCommand (package:args/command_runner.dart:197:27)
<asynchronous suspension>
#14     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:396:21)
<asynchronous suspension>
#15     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:29)
<asynchronous suspension>
#16     _rootRun (dart:async/zone.dart:1124:13)
#17     _CustomZone.run (dart:async/zone.dart:1021:19)
#18     _runZoned (dart:async/zone.dart:1516:10)
#19     runZoned (dart:async/zone.dart:1463:12)
#20     AppContext.run (package:flutter_tools/src/base/context.dart:152:18)
<asynchronous suspension>
#21     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:356:19)
<asynchronous suspension>
#22     CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:112:25)
#23     new Future.sync (dart:async/future.dart:224:31)
#24     CommandRunner.run (package:args/command_runner.dart:112:14)
#25     FlutterCommandRunner.run (package:flutter_tools/src/runner/flutter_command_runner.dart:242:18)
#26     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:62:22)
<asynchronous suspension>
#27     _rootRun (dart:async/zone.dart:1124:13)
#28     _CustomZone.run (dart:async/zone.dart:1021:19)
#29     _runZoned (dart:async/zone.dart:1516:10)
#30     runZoned (dart:async/zone.dart:1500:12)
#31     run.<anonymous closure> (package:flutter_tools/runner.dart:60:18)
<asynchronous suspension>
#32     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:29)
<asynchronous suspension>
#33     _rootRun (dart:async/zone.dart:1124:13)
#34     _CustomZone.run (dart:async/zone.dart:1021:19)
#35     _runZoned (dart:async/zone.dart:1516:10)
#36     runZoned (dart:async/zone.dart:1463:12)
#37     AppContext.run (package:flutter_tools/src/base/context.dart:152:18)
<asynchronous suspension>
#38     runInContext (package:flutter_tools/src/context_runner.dart:56:24)
<asynchronous suspension>
#39     run (package:flutter_tools/runner.dart:51:10)
#40     main (package:flutter_tools/executable.dart:62:9)
<asynchronous suspension>
#41     main (file:///home/danny/sda4/git/flutter/packages/flutter_tools/bin/flutter_tools.dart:8:3)
#42     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:299:32)
#43     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:12)
```

## flutter doctor

```
[✓] Flutter (Channel master, v0.0.0-unknown, on Linux, locale en_US.UTF-8)
    • Flutter version 0.0.0-unknown at /home/danny/sda4/git/flutter
    • Framework revision 305a99501e (9 hours ago), 2019-06-25 18:20:39 -0400
    • Engine revision 107fe82343
    • Dart version 2.4.0

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /home/danny/sda4/software/android-sdk/
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = /home/danny/sda4/software/android-sdk/
    • ANDROID_SDK_ROOT = /home/danny/sda4/software/android-sdk/
    • Java binary at: /opt/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b16-5323222)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Linux toolchain - develop for Linux desktop
    • clang++ 8.0.0
    • GNU Make 4.2.1

[!] Android Studio (version 3.4)
    • Android Studio at /opt/android-studio
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b16-5323222)

[!] IntelliJ IDEA Ultimate Edition (version 2018.3)
    • IntelliJ at /opt/intellij-idea-ultimate-edition
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.dev/intellij-setup/#installing-the-plugins

[✓] Connected device (2 available)
    • Linux  • Linux  • linux-x64      • Linux
    • Chrome • chrome • web-javascript • Google Chrome 72.0.3626.14 dev


! Doctor found issues in 2 categories.
```

**Comment by dannyZhou** [comment]
```
$ flutter upgrade --force 

Oops; flutter has exited unexpectedly.
Sending crash report to Google.
^C
```

Because I am in china, you know, some network problem will occur, so, I need use `proxychains ` to avoid some network problem.

Other maybe useful information 
1. `flutter version`   print nothing
2. `uname -a `  print `archlinux 4.14.90-1-lts #1 SMP Fri Dec 21 15:53:10 CET 2018 x86_64 GNU/Linux`
3. `git log -1` print 
```
commit 305a99501e50ebf1a4b4dae7c26fbb9c7a8f9c35 (grafted, HEAD -> master, origin/master, origin/HEAD)
Author: engine-flutter-autoroll <engine-flutter-autoroll@skia.org>
Date:   Tue Jun 25 18:20:39 2019 -0400

```

**Comment by christopherfujino** [comment]
Hey @dannyZhou, so the problem is that the flutter tool cannot identify the version you are on, probably because it is missing git tags. `git fetch origin` (assuming origin is the name of the official flutter repo) should grab all missing tags.

I'm wondering how you installed flutter--did you git clone the repo? Did you by any chance do a shallow clone?

**Comment by dannyZhou** [comment]
I clone this repo by command 
`git clone -b master https://github.com/flutter/flutter.git --depth=1`

maybe because of this.

**Comment by christopherfujino** [comment]
@dannyZhou Yeah, when you clone with `--depth=1`, it won't have any of the history, and thus the version tags. To unshallow a clone, issue:

```
git fetch --unshallow
```

Let me know if that works?

**Comment by dannyZhou** [comment]
Works fine after run 
```
git fetch --unshallow
```
thanks.
