### ISSUE TITLE
animateTo() called after AnimationController.dispose()

### ISSUE THREAD

**Issue by ravenblackx** [flutter/flutter#35193]
There might be enough information in the log message already to debug, but the log specifically asks me to file a bug here, so here's a bug.

## Steps to Reproduce

Ask ravenblack@google.com for internal details. (To remind myself in a no-internal-information way: swiping away a pane is the trigger.)

## Logs
```
flutter: ══╡ EXCEPTION CAUGHT BY GESTURE LIBRARY ╞═══════════════════════════════════════════════════════════
flutter: The following assertion was thrown while dispatching a pointer event:
flutter: AnimationController.animateTo() called after AnimationController.dispose()
flutter: AnimationController methods should not be used after calling dispose.
flutter: 'package:flutter/src/animation/animation_controller.dart':
flutter: Failed assertion: line 508 pos 7: '_ticker != null'
flutter: 
flutter: Either the assertion indicates an error in the framework itself, or we should provide substantially
flutter: more information in this error message to help you determine and fix the underlying cause.
flutter: In either case, please report this assertion by filing a bug on GitHub:
flutter:   https://github.com/flutter/flutter/issues/new?template=BUG.md
flutter: 
flutter: When the exception was thrown, this was the stack:
flutter: #2      AnimationController.animateTo (package:flutter/src/animation/animation_controller.dart:508:7)
flutter: #3      GestureHintOpacityModel.showGestureHint (package:redacted:63:24)
flutter: #4      SurfaceCoordinator.showGestureHint (package:redacted:81:22)
flutter: #5      GestureHintWidget.build.<anonymous closure> (package:redacted:41:30)
flutter: #6      RenderPointerListener.handleEvent (package:flutter/src/rendering/proxy_box.dart:2687:14)
flutter: #7      _WidgetsFlutterBinding&BindingBase&GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:198:22)
flutter: #8      _WidgetsFlutterBinding&BindingBase&GestureBinding._handlePointerEvent (package:flutter/src/gestures/binding.dart:156:7)
flutter: #9      _WidgetsFlutterBinding&BindingBase&GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:102:7)
flutter: #10     _WidgetsFlutterBinding&BindingBase&GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:86:7)
flutter: #14     _invoke1 (dart:ui/hooks.dart:250:10)
flutter: #15     _dispatchPointerDataPacket (dart:ui/hooks.dart:159:5)
flutter: (elided 5 frames from class _AssertionError and package dart:async)
flutter: 
flutter: Event:
flutter:   PointerUpEvent#8b331(position: Offset(1114.4, 280.8), timeStamp: 433792:12:13.139838, pointer: 11,
flutter:   kind: mouse, down: false, pressure: 0.0, pressureMin: 0.0, pressureMax: 0.0)
flutter: Target:
flutter:   RenderPointerListener#0367a DETACHED
flutter: ════════════════════════════════════════════════════════════════════════════════════════════════════

```

**Comment by TahaTesser** [comment]
Hi @ravenblackx 
Are you still experiencing this issue with the latest version of Flutter? If so please provide your updated `flutter doctor -v` and `flutter run --verbose` together with a minimal code sample to reproduce the problem 
Thank you

**Comment by ravenblackx** [comment]
With an 8 month gap my one-sentence hint to remind me how to reproduce the issue is no longer enough.
