### ISSUE TITLE
Input field fails to build

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#352]
STEPS TO REPRODUCE
1. Launch a tip of tree Stocks app, using a tip of tree Engine build, on Android (M).
2. Tap the search icon.

```
11-12 21:16:26.447 17969 17988 I sky     : Exception caught while building DefaultTextStyle(inhert: false; color: Color(0xffffffff); size: 20.0; weight: 500; baseline: alphabetic)
11-12 21:16:26.448 17969 17988 I sky     : 'packages/mojo/src/application_connection.dart': Failed assertion: line 84: '!proxy.impl.isBound &&
11-12 21:16:26.448 17969 17988 I sky     :         (remoteServiceProvider != null) &&
11-12 21:16:26.449 17969 17988 I sky     :         remoteServiceProvider.impl.isBound' is not true.
11-12 21:16:26.449 17969 17988 I sky     : Stack trace:
11-12 21:16:26.459 17969 17988 I sky     : #0      _AssertionError._throwNew (dart:core-patch/errors_patch.dart:27)
11-12 21:16:26.459 17969 17988 I sky     : #1      ApplicationConnection.requestService (packages/mojo/src/application_connection.dart:84)
11-12 21:16:26.460 17969 17988 I sky     : #2      _Shell._connectToService (packages/flutter/src/services/shell.dart:59)
11-12 21:16:26.460 17969 17988 I sky     : #3      _Shell.connectToService (packages/flutter/src/services/shell.dart:74)
11-12 21:16:26.460 17969 17988 I sky     : #4      _KeyboardConnection._KeyboardConnection (packages/flutter/src/services/keyboard.dart:17)
11-12 21:16:26.460 17969 17988 I sky     : #5      _KeyboardConnection.instance (packages/flutter/src/services/keyboard.dart:23)
11-12 21:16:26.460 17969 17988 I sky     : #6      _KeyboardConnection.instance (packages/flutter/src/services/keyboard.dart:23)
11-12 21:16:26.460 17969 17988 I sky     : #7      keyboard (packages/flutter/src/services/keyboard.dart:112)
11-12 21:16:26.460 17969 17988 I sky     : #8      keyboard (packages/flutter/src/services/keyboard.dart:112)
11-12 21:16:26.460 17969 17988 I sky     : #9      KeyboardHandle.unattached (packages/flutter/src/services/keyboard.dart:74)
11-12 21:16:26.460 17969 17988 I sky     : #10     KeyboardHandle.unattached (packages/flutter/src/services/keyboard.dart:74)
11-12 21:16:26.460 17969 17988 I sky     : #11     InputState.InputState (packages/flutter/src/material/input.dart:45)
11-12 21:16:26.460 17969 17988 I sky     : #12     Input.createState (packages/flutter/src/material/input.dart:39)
11-12 21:16:26.460 17969 17988 I sky     : #13     StatefulComponentElement.StatefulComponentElement (packages/flutter/src/widgets/framework.dart:1102)
11-12 21:16:26.460 17969 17988 I sky     : #14     StatefulComponent.createElement (packages/flutter/src/widgets/framework.dart:317)
11-12 21:16:26.460 17969 17988 I sky     : #15     Element._inflateWidget (packages/flutter/src/widgets/framework.dart:764)
11-12 21:16:26.460 17969 17988 I sky     : #16     Element.updateChild (packages/flutter/src/widgets/framework.dart:644)
11-12 21:16:26.460 17969 17988 I sky     : #17     ComponentElement.performRebuild (packages/flutter/src/widgets/framework.dart:1062)
11-12 21:16:26.460 17969 17988 I sky     : #18     BuildableElement.rebuild (packages/flutter/src/widgets/framework.dart:991)
11-12 21:16:26.461 17969 17988 I sky     : #19     ProxyElement.update (packages/flutter/src/widgets/framework.dart:1186)
```

**Comment by abarth** [comment]
I fixed this issue today,
