### ISSUE TITLE
Using TextFields in ReorderableLists creates stacking issues with copy/paste menu

### ISSUE THREAD

**Issue by jlund24** [flutter/flutter#35227]
When using TextFields in an item in a ReorderableListView, some stacking issues seem to be created by the painting of the selection handle and/or selection menu. When text is selected on the top line, the text selection menu is hidden under the app bar. In addition, when the selection handle or menu are present and the line is long pressed (triggering a reorder), an exception titled "LeaderLayer anchor must come before FollowerLayer in paint order, but the reverse was true." is thrown. More details are below.

## Steps to Reproduce
[Here](https://gist.github.com/jlund24/f5c5f28c3606598a052e7a80cda184e7) is code for a simple version that reproduces the issue.

**Obstructed Selection Menu**
1. long press on text in the top item of the list

Should look like:
![Screen Shot 2019-06-27 at 4 57 53 PM](https://user-images.githubusercontent.com/22064842/60306263-c5d8a180-98fc-11e9-855c-391d38ddeb17.png)

**Reorder Error**
1. long press or tap on text in any item to bring up the selection handle 
2. long press on the drag handle at the left to trigger reorder
3. check logs for exception

## Logs
The following exception in the logs only occurs following the Reorder Error described above. The first issue does not generate any error.

```
[+26238 ms] I/flutter ( 9802): ══╡ EXCEPTION CAUGHT BY SCHEDULER LIBRARY ╞═════════════════════════════════════════════════════════
[        ] I/flutter ( 9802): The following assertion was thrown during a scheduler callback:
[        ] I/flutter ( 9802): LeaderLayer anchor must come before FollowerLayer in paint order, but the reverse was true.
[        ] I/flutter ( 9802): 'package:flutter/src/rendering/layer.dart':
[        ] I/flutter ( 9802): Failed assertion: line 1913 pos 12: 'link.leader._lastOffset != null'
[        ] I/flutter ( 9802): 
[        ] I/flutter ( 9802): Either the assertion indicates an error in the framework itself, or we should provide substantially
[        ] I/flutter ( 9802): more information in this error message to help you determine and fix the underlying cause.
[        ] I/flutter ( 9802): In either case, please report this assertion by filing a bug on GitHub:
[        ] I/flutter ( 9802):   https://github.com/flutter/flutter/issues/new?template=BUG.md
[        ] I/flutter ( 9802): 
[        ] I/flutter ( 9802): When the exception was thrown, this was the stack:
[        ] I/flutter ( 9802): #2      FollowerLayer._establishTransform (package:flutter/src/rendering/layer.dart:1913:12)
[        ] I/flutter ( 9802): #3      FollowerLayer.addToScene (package:flutter/src/rendering/layer.dart:1974:5)
[        ] I/flutter ( 9802): #4      Layer._addToSceneWithRetainedRendering (package:flutter/src/rendering/layer.dart:208:20)
[        ] I/flutter ( 9802): #5      ContainerLayer.addChildrenToScene (package:flutter/src/rendering/layer.dart:767:15)
[        ] I/flutter ( 9802): #6      ClipRectLayer.addToScene (package:flutter/src/rendering/layer.dart:1055:5)
[        ] I/flutter ( 9802): #7      Layer._addToSceneWithRetainedRendering (package:flutter/src/rendering/layer.dart:208:20)
[        ] I/flutter ( 9802): #8      ContainerLayer.addChildrenToScene (package:flutter/src/rendering/layer.dart:767:15)
[        ] I/flutter ( 9802): #9      PhysicalModelLayer.addToScene (package:flutter/src/rendering/layer.dart:1630:5)
[        ] I/flutter ( 9802): #10     Layer._addToSceneWithRetainedRendering (package:flutter/src/rendering/layer.dart:208:20)
[        ] I/flutter ( 9802): #11     ContainerLayer.addChildrenToScene (package:flutter/src/rendering/layer.dart:767:15)
[        ] I/flutter ( 9802): #12     OffsetLayer.addToScene (package:flutter/src/rendering/layer.dart:933:5)
[        ] I/flutter ( 9802): #13     Layer._addToSceneWithRetainedRendering (package:flutter/src/rendering/layer.dart:208:20)
[   +3 ms] I/flutter ( 9802): #14     ContainerLayer.addChildrenToScene (package:flutter/src/rendering/layer.dart:767:15)
[        ] I/flutter ( 9802): #15     OffsetLayer.addToScene (package:flutter/src/rendering/layer.dart:933:5)
[        ] I/flutter ( 9802): #16     Layer._addToSceneWithRetainedRendering (package:flutter/src/rendering/layer.dart:208:20)
[        ] I/flutter ( 9802): #17     ContainerLayer.addChildrenToScene (package:flutter/src/rendering/layer.dart:767:15)
[        ] I/flutter ( 9802): #18     TransformLayer.addToScene (package:flutter/src/rendering/layer.dart:1266:5)
[        ] I/flutter ( 9802): #19     OffsetLayer.buildScene (package:flutter/src/rendering/layer.dart:908:5)
[        ] I/flutter ( 9802): #20     RenderView.compositeFrame (package:flutter/src/rendering/view.dart:199:36)
[        ] I/flutter ( 9802): #21     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding.drawFrame (package:flutter/src/rendering/binding.dart:349:16)
[   +4 ms] I/flutter ( 9802): #22     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding&WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:701:13)
[        ] I/flutter ( 9802): #23     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:285:5)
[        ] I/flutter ( 9802): #24     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1012:15)
[        ] I/flutter ( 9802): #25     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:952:9)
[        ] I/flutter ( 9802): #26     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:864:5)
[        ] I/flutter ( 9802): #30     _invoke (dart:ui/hooks.dart:220:10)
[        ] I/flutter ( 9802): #31     _drawFrame (dart:ui/hooks.dart:178:3)
[        ] I/flutter ( 9802): (elided 5 frames from class _AssertionError and package dart:async)
[        ] I/flutter ( 9802): ════════════════════════════════════════════════════════════════════════════════════════════════════
```

```
Analyzing copy_paste_menu_bug...                                        
No issues found! (ran in 3.2s)
```

```
[✓] Flutter (Channel beta, v1.6.3, on Mac OS X 10.14.5 18F132, locale en-US)
    • Flutter version 1.6.3 at /Users/johnlund/Documents/flutter
    • Framework revision bc7bc94083 (5 weeks ago), 2019-05-23 10:29:07 -0700
    • Engine revision 8dc3a4cde2
    • Dart version 2.3.2 (build 2.3.2-dev.0.0 e3edfd36b2)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/johnlund/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
    • All Android licenses accepted.

[!] iOS toolchain - develop for iOS devices (Xcode 10.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.2.1, Build version 10E1001
    ✗ Verify that all connected devices have been paired with this computer in Xcode.
      If all devices have been paired, libimobiledevice and ideviceinstaller may require updating.
      To update with Brew, run:
        brew update
        brew uninstall --ignore-dependencies libimobiledevice
        brew uninstall --ignore-dependencies usbmuxd
        brew install --HEAD usbmuxd
        brew unlink usbmuxd
        brew link usbmuxd
        brew install --HEAD libimobiledevice
        brew install ideviceinstaller
    • ios-deploy 1.9.2
    ✗ ios-deploy out of date (1.9.4 is required). To upgrade with Brew:
        brew upgrade ios-deploy
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.4)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 36.1.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

[!] VS Code (version 1.34.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    ✗ Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 9 (API 28) (emulator)

! Doctor found issues in 2 categories.
```

**Comment by justinmc** [comment]
Thanks for following up with this issue, this is super clear.

**Comment by jlund24** [comment]
Thanks, any ideas? I've also discovered a similar, but distinct error is triggered by long pressing on any textfield when the selection menu or handles are shown. Happens on both iOS and Android whether or not it's in a reorderablelistview.

**Comment by justinmc** [comment]
Can you elaborate on that one?  If you just put a plain TextField near the top of an app with an AppBar, the selection menu should appear on top of the AppBar.

**Comment by jlund24** [comment]
Sorry, not sure how I missed this. The error that appears is similar to the second error above related to the later order. I can post an example and better explanation tomorrow

**Comment by justinmc** [comment]
@jlund24 Just a reminder for that example if you've still got it on your mind.

**Comment by jlund24** [comment]
@justinmc Thanks for the reminder, after looking into the additional issue some more, it looks like it's just a duplicate of a preexisting issue. The original two issues described in this issue are still relevant though

**Comment by justinmc** [comment]
Got it, thanks for following up.  I'll take a look at the original problems.

**Comment by justinmc** [comment]
@DaveShuckerow Not sure if you're the right person but I see your name on ReorderableListView.  Any insight into this exception?  Maybe nested Overlays not being doable?

**Comment by justinmc** [comment]
I spent a few hours looking into this and didn't get anywhere promising, but some takeaways were:

  1. It is possible to put an Overlay inside of another Overlay, in general.
  1. The error has a comment near its assertion that says to set `parentUsesSize` to true if it errors, but it seems like that is already being done in this case.
  1. Specifically rendering the toolbar inside of another overlay is what causes the error.

**Comment by gbaldeck** [comment]
Any updates on this? I've run into this error in my app and haven't found a solution. I'm using Flutter 1.13.6-pre.23 from the master branch.

**Comment by justinmc** [comment]
I haven't had a chance to look at this again, unfortunately.  If anyone has any more info or ideas let me know.

And if you give a 👍 to the original issue up top it will help us to prioritize this.

**Comment by Faiyyaz** [comment]
Even i m having the same issue please help

**Comment by darshankawar** [comment]
Hi @jlund24,
I tried to replicate this issue on latest dev channel but didn't see any exception being thrown. When I long pressed and dragged any of the items to reorder, I was able to reorder it without any exception in the console. Here's the log:

</details>


<details>
<summary>log</summary>

```
Launching lib/main1.dart on SM A260G in debug mode...
Running Gradle task 'assembleDebug'...
✓ Built build/app/outputs/flutter-apk/app-debug.apk.
Installing build/app/outputs/flutter-apk/app.apk...                 9.3s
Waiting for SM A260G to report its views...
Debug service listening on ws://127.0.0.1:59352/Gcpg5grgVco=/ws
Syncing files to device SM A260G...
W/IInputConnectionWrapper( 4583): getCursorCapsMode on inactive InputConnection
W/IInputConnectionWrapper( 4583): getTextBeforeCursor on inactive InputConnection
W/IInputConnectionWrapper( 4583): getTextAfterCursor on inactive InputConnection
W/IInputConnectionWrapper( 4583): getSelectedText on inactive InputConnection
I/zygote  ( 4583): Do partial code cache collection, code=61KB, data=48KB
I/zygote  ( 4583): After code cache collection, code=61KB, data=48KB
I/zygote  ( 4583): Increasing code cache capacity to 256KB
W/libEGL  ( 4583): EGLNativeWindowType 0xd414a008 disconnect failed
W/IInputConnectionWrapper( 4583): getCursorCapsMode on inactive InputConnection
W/IInputConnectionWrapper( 4583): getCursorCapsMode on inactive InputConnection
D/mali_winsys( 4583): EGLint new_window_surface(egl_winsys_display *, void *, EGLSurface, EGLConfig, egl_winsys_surface **, egl_color_buffer_format *, EGLBoolean) returns 0x3000,  [540x888]-format:1
W/IInputConnectionWrapper( 4583): getCursorCapsMode on inactive InputConnection
I/zygote  ( 4583): Do full code cache collection, code=125KB, data=94KB
I/zygote  ( 4583): After code cache collection, code=101KB, data=65KB
W/IInputConnectionWrapper( 4583): getTextBeforeCursor on inactive InputConnection
W/IInputConnectionWrapper( 4583): getTextAfterCursor on inactive InputConnection
W/IInputConnectionWrapper( 4583): getTextBeforeCursor on inactive InputConnection
W/IInputConnectionWrapper( 4583): getTextAfterCursor on inactive InputConnection
W/IInputConnectionWrapper( 4583): getSelectedText on inactive InputConnection
W/IInputConnectionWrapper( 4583): getCursorCapsMode on inactive InputConnection
W/IInputConnectionWrapper( 4583): getSelectedText on inactive InputConnection
W/IInputConnectionWrapper( 4583): getTextBeforeCursor on inactive InputConnection
W/IInputConnectionWrapper( 4583): getTextBeforeCursor on inactive InputConnection
W/IInputConnectionWrapper( 4583): getTextAfterCursor on inactive InputConnection
W/IInputConnectionWrapper( 4583): getSelectedText on inactive InputConnection
I/zygote  ( 4583): Do partial code cache collection, code=109KB, data=80KB
I/zygote  ( 4583): After code cache collection, code=109KB, data=80KB
I/zygote  ( 4583): Increasing code cache capacity to 512KB
W/IInputConnectionWrapper( 4583): getCursorCapsMode on inactive InputConnection
W/IInputConnectionWrapper( 4583): getTextBeforeCursor on inactive InputConnection
W/IInputConnectionWrapper( 4583): getTextAfterCursor on inactive InputConnection
W/IInputConnectionWrapper( 4583): getSelectedText on inactive InputConnection
W/libEGL  ( 4583): EGLNativeWindowType 0xe9062008 disconnect failed
D/mali_winsys( 4583): EGLint new_window_surface(egl_winsys_display *, void *, EGLSurface, EGLConfig, egl_winsys_surface **, egl_color_buffer_format *, EGLBoolean) returns 0x3000,  [540x888]-format:1
W/libEGL  ( 4583): EGLNativeWindowType 0xcd6a1008 disconnect failed
W/libEGL  ( 4583): EGLNativeWindowType 0xd61af808 disconnect failed
```

</details>

Also, the text selection menu is properly displayed when I select first item from the list, as shown below:

![35227](https://user-images.githubusercontent.com/67046386/87540494-6a22b700-c6bd-11ea-8002-a6acbcce40d3.png)

I tested on Android 8.1.  Can you please confirm if you still experience this issue on latest Flutter version (eg: dev, master) ?

**Comment by jlund24** [comment]
Thanks for following up. I'll try to test this again before the end of the week and let you know

**Comment by jlund24** [comment]
@darshankawar I can confirm that (when using the provided code in the gist above), neither error occurs on either iOS or Android builds using the most recent version of flutter stable. The only thing I observed was that there are some slight differences in behavior between iOS on long pressing the TextFields such as whether the TextField retains focus on being rearranged or whether long-pressing on an unfocused TextField brings up the TextSelectionMenu. I don't think those are important issues, and further investigation might just prove them to be predictable and intended behavior so I think this issue can be closed.

**Comment by darshankawar** [comment]
Closing this issue as fixed per @jlund24's above comment.
