### ISSUE TITLE
I can't call sub widget gridview  Another exception was thrown: NoSuchMethodError: The method '>' was called on null.

### ISSUE THREAD

**Issue by Prepear** [flutter/flutter#35247]
### **Logs**
```
> 

> 

> Performing hot reload...                                               |I/flutter (20338): ══╡ EXCEPTION CAUGHT BY RENDERING LIBRARY ╞═════════════════════════════════════════════════════════

I/flutter (20338): The following assertion was thrown during performResize():
I/flutter (20338): Vertical viewport was given unbounded height.
I/flutter (20338): Viewports expand in the scrolling direction to fill their container.In this case, a vertical
I/flutter (20338): viewport was given an unlimited amount of vertical space in which to expand. This situation
I/flutter (20338): typically happens when a scrollable widget is nested inside another scrollable widget.
I/flutter (20338): If this widget is always nested in a scrollable widget there is no need to use a viewport because
I/flutter (20338): there will always be enough vertical space for the children. In this case, consider using a Column
I/flutter (20338): instead. Otherwise, consider using the "shrinkWrap" property (or a ShrinkWrappingViewport) to size
I/flutter (20338): the height of the viewport to the sum of the heights of its children.
I/flutter (20338): When the exception was thrown, this was the stack:
I/flutter (20338): #0      RenderViewport.performResize.<anonymous closure> (package:flutter/src/rendering/viewport.dart:1147:15)
I/flutter (20338): #1      RenderViewport.performResize (package:flutter/src/rendering/viewport.dart:1200:6)
I/flutter (20338): #2      RenderObject.layout (package:flutter/src/rendering/object.dart:1604:9)
I/flutter (20338): #3      _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter (20338): #4      RenderObject.layout (package:flutter/src/rendering/object.dart:1619:7)
I/flutter (20338): #5      _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter (20338): #6      RenderObject.layout (package:flutter/src/rendering/object.dart:1619:7)
I/flutter (20338): #7      _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter (20338): #8      RenderObject.layout (package:flutter/src/rendering/object.dart:1619:7)
I/flutter (20338): #9      _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter (20338): #10     RenderObject.layout (package:flutter/src/rendering/object.dart:1619:7)
I/flutter (20338): #11     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter (20338): #12     RenderObject.layout (package:flutter/src/rendering/object.dart:1619:7)
I/flutter (20338): #13     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter (20338): #14     RenderObject.layout (package:flutter/src/rendering/object.dart:1619:7)
I/flutter (20338): #15     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter (20338): #16     RenderObject.layout (package:flutter/src/rendering/object.dart:1619:7)
I/flutter (20338): #17     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter (20338): #18     RenderObject.layout (package:flutter/src/rendering/object.dart:1619:7)
I/flutter (20338): #19     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter (20338): #20     RenderObject.layout (package:flutter/src/rendering/object.dart:1619:7)
I/flutter (20338): #21     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter (20338): #22     RenderObject.layout (package:flutter/src/rendering/object.dart:1619:7)
I/flutter (20338): #23     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter (20338): #24     RenderObject.layout (package:flutter/src/rendering/object.dart:1619:7)
I/flutter (20338): #25     RenderSliverList.performLayout (package:flutter/src/rendering/sliver_list.dart:165:27)
I/flutter (20338): #26     RenderObject.layout (package:flutter/src/rendering/object.dart:1619:7)
I/flutter (20338): #27     RenderSliverPadding.performLayout (package:flutter/src/rendering/sliver_padding.dart:181:11)
I/flutter (20338): #28     RenderObject.layout (package:flutter/src/rendering/object.dart:1619:7)
I/flutter (20338): #29     RenderViewportBase.layoutChildSequence (package:flutter/src/rendering/viewport.dart:406:13)
I/flutter (20338): #30     RenderShrinkWrappingViewport._attemptLayout (package:flutter/src/rendering/viewport.dart:1663:12)
I/flutter (20338): #31     RenderShrinkWrappingViewport.performLayout (package:flutter/src/rendering/viewport.dart:1626:20)
I/flutter (20338): #32     RenderObject.layout (package:flutter/src/rendering/object.dart:1619:7)
I/flutter (20338): #33     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter (20338): #34     RenderObject.layout (package:flutter/src/rendering/object.dart:1619:7)
I/flutter (20338): #35     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter (20338): #36     RenderObject.layout (package:flutter/src/rendering/object.dart:1619:7)
I/flutter (20338): #37     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter (20338): #38     RenderObject.layout (package:flutter/src/rendering/object.dart:1619:7)
I/flutter (20338): #39     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter (20338): #40     RenderObject.layout (package:flutter/src/rendering/object.dart:1619:7)
I/flutter (20338): #41     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter (20338): #42     RenderObject.layout (package:flutter/src/rendering/object.dart:1619:7)
I/flutter (20338): #43     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter (20338): #44     RenderObject.layout (package:flutter/src/rendering/object.dart:1619:7)
I/flutter (20338): #45     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter (20338): #46     RenderObject.layout (package:flutter/src/rendering/object.dart:1619:7)
I/flutter (20338): #47     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter (20338): #48     RenderObject.layout (package:flutter/src/rendering/object.dart:1619:7)
I/flutter (20338): #49     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter (20338): #50     RenderObject.layout (package:flutter/src/rendering/object.dart:1619:7)
I/flutter (20338): #51     RenderFlex.performLayout (package:flutter/src/rendering/flex.dart:743:15)
I/flutter (20338): #52     RenderObject.layout (package:flutter/src/rendering/object.dart:1619:7)
I/flutter (20338): #53     RenderPadding.performLayout (package:flutter/src/rendering/shifted_box.dart:206:11)
I/flutter (20338): #54     RenderObject.layout (package:flutter/src/rendering/object.dart:1619:7)
I/flutter (20338): #55     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter (20338): #56     RenderObject.layout (package:flutter/src/rendering/object.dart:1619:7)
I/flutter (20338): #57     RenderFlex.performLayout (package:flutter/src/rendering/flex.dart:743:15)
I/flutter (20338): #58     RenderObject.layout (package:flutter/src/rendering/object.dart:1619:7)
I/flutter (20338): #59     MultiChildLayoutDelegate.layoutChild (package:flutter/src/rendering/custom_layout.dart:142:11)
I/flutter (20338): #60     _ScaffoldLayout.performLayout (package:flutter/src/material/scaffold.dart:443:7)
I/flutter (20338): #61     MultiChildLayoutDelegate._callPerformLayout (package:flutter/src/rendering/custom_layout.dart:212:7)
I/flutter (20338): #62     RenderCustomMultiChildLayoutBox.performLayout (package:flutter/src/rendering/custom_layout.dart:356:14)
I/flutter (20338): #63     RenderObject.layout (package:flutter/src/rendering/object.dart:1619:7)
I/flutter (20338): #64     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter (20338): #65     RenderObject.layout (package:flutter/src/rendering/object.dart:1619:7)
I/flutter (20338): #66     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter (20338): #67     _RenderCustomClip.performLayout (package:flutter/src/rendering/proxy_box.dart:1214:11)
I/flutter (20338): #68     RenderObject.layout (package:flutter/src/rendering/object.dart:1619:7)
I/flutter (20338): #69     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter (20338): #70     RenderObject.layout (package:flutter/src/rendering/object.dart:1619:7)
I/flutter (20338): #71     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter (20338): #72     RenderObject.layout (package:flutter/src/rendering/object.dart:1619:7)
I/flutter (20338): #73     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter (20338): #74     RenderObject.layout (package:flutter/src/rendering/object.dart:1619:7)
I/flutter (20338): #75     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter (20338): #76     RenderObject.layout (package:flutter/src/rendering/object.dart:1619:7)
I/flutter (20338): #77     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter (20338): #78     RenderObject.layout (package:flutter/src/rendering/object.dart:1619:7)
I/flutter (20338): #79     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter (20338): #80     RenderObject.layout (package:flutter/src/rendering/object.dart:1619:7)
I/flutter (20338): #81     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter (20338): #82     RenderObject.layout (package:flutter/src/rendering/object.dart:1619:7)
I/flutter (20338): #83     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter (20338): #84     RenderOffstage.performLayout (package:flutter/src/rendering/proxy_box.dart:3076:13)
I/flutter (20338): #85     RenderObject.layout (package:flutter/src/rendering/object.dart:1619:7)
I/flutter (20338): #86     RenderStack.performLayout (package:flutter/src/rendering/stack.dart:510:15)
I/flutter (20338): #87     RenderObject.layout (package:flutter/src/rendering/object.dart:1619:7)
I/flutter (20338): #88     __RenderTheatre&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter (20338): #89     RenderObject.layout (package:flutter/src/rendering/object.dart:1619:7)
I/flutter (20338): #90     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter (20338): #91     RenderObject.layout (package:flutter/src/rendering/object.dart:1619:7)
I/flutter (20338): #92     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter (20338): #93     RenderObject.layout (package:flutter/src/rendering/object.dart:1619:7)
I/flutter (20338): #94     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter (20338): #95     RenderObject.layout (package:flutter/src/rendering/object.dart:1619:7)
I/flutter (20338): #96     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter (20338): #97     RenderObject.layout (package:flutter/src/rendering/object.dart:1619:7)
I/flutter (20338): #98     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter (20338): #99     RenderObject.layout (package:flutter/src/rendering/object.dart:1619:7)
I/flutter (20338): #100    RenderView.performLayout (package:flutter/src/rendering/view.dart:151:13)
I/flutter (20338): #101    RenderObject._layoutWithoutResize (package:flutter/src/rendering/object.dart:1496:7)
I/flutter (20338): #102    PipelineOwner.flushLayout (package:flutter/src/rendering/object.dart:765:18)
I/flutter (20338): #103    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding.drawFrame (package:flutter/src/rendering/binding.dart:346:19)
I/flutter (20338): #104    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding&WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:701:13)
I/flutter (20338): #105    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:285:5)Reloaded 4 of 586 libraries in 1,939ms.
I/flutter (20338): #106    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1012:15)
I/flutter (20338): #107    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:952:9)
I/flutter (20338): #108    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.scheduleWarmUpFrame.<anonymous closure> (package:flutter/src/scheduler/binding.dart:773:7)
I/flutter (20338): #110    _Timer._runTimers (dart:isolate-patch/timer_impl.dart:382:19)
I/flutter (20338): #111    _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:416:5)
I/flutter (20338): #112    _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:12)
I/flutter (20338): (elided one frame from package dart:async-patch)
I/flutter (20338): The following RenderObject was being processed when the exception was fired: RenderViewport#627c0 NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE:
I/flutter (20338):   needs compositing
I/flutter (20338):   creator: Viewport ← IgnorePointer-[GlobalKey#0d861] ← Semantics ← Listener ← _GestureSemantics ←
I/flutter (20338):     RawGestureDetector-[LabeledGlobalKey<RawGestureDetectorState>#150a4] ← Listener ← _ScrollableScope
I/flutter (20338):     ← _ScrollSemantics-[GlobalKey#f3a0b] ← RepaintBoundary ← CustomPaint ← RepaintBoundary ← ⋯
I/flutter (20338):   parentData: <none> (can use size)
I/flutter (20338):   constraints: BoxConstraints(w=340.0, 0.0<=h<=Infinity)
I/flutter (20338):   size: MISSING
I/flutter (20338):   axisDirection: down
I/flutter (20338):   crossAxisDirection: right
I/flutter (20338):   offset: ScrollPositionWithSingleContext#ff561(offset: 0.0, range: null..null, viewport: null,
I/flutter (20338):     ScrollableState, AlwaysScrollableScrollPhysics -> ClampingScrollPhysics, IdleScrollActivity#8de67,
I/flutter (20338):     ScrollDirection.idle)
I/flutter (20338):   anchor: 0.0
I/flutter (20338): This This RenderObject had the following descendants (showing up to depth 5):
I/flutter (20338):     center child: RenderSliverPadding#f859b NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
I/flutter (20338):       child: RenderSliverGrid#3102b NEEDS-LAYOUT NEEDS-PAINT
I/flutter (20338): ════════════════════════════════════════════════════════════════════════════════════════════════════
I/flutter (20338): Another exception was thrown: RenderBox was not laid out: RenderViewport#627c0 NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
I/flutter (20338): Another exception was thrown: RenderBox was not laid out: RenderViewport#627c0 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
I/flutter (20338): Another exception was thrown: RenderBox was not laid out: RenderIgnorePointer#a321f relayoutBoundary=up27 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
I/flutter (20338): Another exception was thrown: RenderBox was not laid out: RenderSemanticsAnnotations#175db relayoutBoundary=up26 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
I/flutter (20338): Another exception was thrown: RenderBox was not laid out: RenderPointerListener#20ebc relayoutBoundary=up25 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
I/flutter (20338): Another exception was thrown: RenderBox was not laid out: RenderSemanticsGestureHandler#c87c6 relayoutBoundary=up24 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
I/flutter (20338): Another exception was thrown: RenderBox was not laid out: RenderPointerListener#df2bf relayoutBoundary=up23 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
I/flutter (20338): Another exception was thrown: RenderBox was not laid out: _RenderScrollSemantics#656de relayoutBoundary=up22 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
I/flutter (20338): Another exception was thrown: RenderBox was not laid out: RenderRepaintBoundary#560fd relayoutBoundary=up21 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
I/flutter (20338): Another exception was thrown: RenderBox was not laid out: RenderCustomPaint#6e082 relayoutBoundary=up20 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
I/flutter (20338): Another exception was thrown: RenderBox was not laid out: RenderRepaintBoundary#9a83b relayoutBoundary=up19 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
I/flutter (20338): Another exception was thrown: RenderBox was not laid out: RenderRepaintBoundary#4aab9 relayoutBoundary=up18 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
I/flutter (20338): Another exception was thrown: 'package:flutter/src/rendering/sliver_multi_box_adaptor.dart': Failed assertion: line 549 pos 12: 'child.hasSize': is not true.
I/flutter (20338): Another exception was thrown: NoSuchMethodError: The getter 'scrollOffsetCorrection' was called on null.
I/flutter (20338): Another exception was thrown: NoSuchMethodError: The method 'debugAssertIsValid' was called on null.
I/flutter (20338): Another exception was thrown: RenderBox was not laid out: RenderShrinkWrappingViewport#971b4 relayoutBoundary=up14 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
I/flutter (20338): Another exception was thrown: RenderBox was not laid out: RenderIgnorePointer#bc095 relayoutBoundary=up13 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
I/flutter (20338): Another exception was thrown: RenderBox was not laid out: RenderSemanticsAnnotations#5568c relayoutBoundary=up12 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
I/flutter (20338): Another exception was thrown: RenderBox was not laid out: RenderPointerListener#34db3 relayoutBoundary=up11 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
I/flutter (20338): Another exception was thrown: RenderBox was not laid out: RenderSemanticsGestureHandler#44356 relayoutBoundary=up10 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
I/flutter (20338): Another exception was thrown: RenderBox was not laid out: RenderPointerListener#37986 relayoutBoundary=up9 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
I/flutter (20338): Another exception was thrown: RenderBox was not laid out: _RenderScrollSemantics#97c09 relayoutBoundary=up8 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
I/flutter (20338): Another exception was thrown: RenderBox was not laid out: RenderRepaintBoundary#b54d9 relayoutBoundary=up7 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
I/flutter (20338): Another exception was thrown: RenderBox was not laid out: RenderCustomPaint#19970 relayoutBoundary=up6 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
I/flutter (20338): Another exception was thrown: RenderBox was not laid out: RenderRepaintBoundary#7d23e relayoutBoundary=up5 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
I/flutter (20338): Another exception was thrown: RenderBox was not laid out: RenderFlex#20d99 relayoutBoundary=up4 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
I/flutter (20338): Another exception was thrown: RenderBox was not laid out: RenderPadding#17f02 relayoutBoundary=up3 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
I/flutter (20338): Another exception was thrown: RenderBox was not laid out: RenderDecoratedBox#6f913 relayoutBoundary=up2 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
I/flutter (20338): Another exception was thrown: RenderBox was not laid out: RenderFlex#f2219 relayoutBoundary=up1 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
I/flutter (20338): Another exception was thrown: NoSuchMethodError: The method '>' was called on null.   

> 

> 

> 
```
### **My Code**

**Main**

```
 body: Container(
        child: Column(children: <Widget>[
          Container(
            child: new ProjectIndexTab(),
          ),
          Container(
            color: KwanjaiColors.bg,
            child: Container(
              padding: EdgeInsets.symmetric(horizontal: 10.0, vertical: 10.0),
              child: Column(
                children: <Widget>[
                  Container(child: ProjectIndexWorkDaily()),
                  Container(child: ProjectGridList())
                ],
              ),
            ),
          )
        ]),
      ), 
```

**Sub widget ProjectGridList()**
```

class ProjectGridList extends StatefulWidget {
  final String title;
  ProjectGridList({Key key, this.title}) : super(key: key);
  @override
  ProjectGridListState createState() => new ProjectGridListState();
}

class ProjectGridListState extends State<ProjectGridList> {
  @override
  Widget build(BuildContext context) {
    return  GridView.builder(
        itemCount: projectAll.length,
        gridDelegate:
            SliverGridDelegateWithFixedCrossAxisCount(crossAxisCount: 2 ,
            ),
        itemBuilder: (BuildContext context, int index) {
          return ProjectGridDetails(
            project_name: projectAll[index].project_name,
            project_picture: projectAll[index].project_picture,
            project_price: projectAll[index].project_price,
            project_old: projectAll[index].project_old,
          );
        });
```

**Comment by BondarenkoStas** [comment]
@Prepear This is a question better suited for StackOverflow, since there doesn’t seem to be anything wrong with Flutter itself. Closing, as this is not an issue report. See https://flutter.dev/community for support options.
