### ISSUE TITLE
Pressing the right arrow key in a textfield leads to error if deployed in a simulator

### ISSUE THREAD

**Issue by ehhc** [flutter/flutter#35268]
## Steps to Reproduce

1. Use the app like given below and deploy it to the simulator (needed because otherwise there are no arrow keys on the keyboard .. )
2. click into the textfield and type some text using the hardware keyboard of your computer
3. press the right-arrow key on your hardware keyboard of your computer
4. see stacktrace below

Stacktrace:
```
I/flutter ( 3978): ══╡ EXCEPTION CAUGHT BY SERVICES LIBRARY ╞══════════════════════════════════════════════════════════
I/flutter ( 3978): The following NoSuchMethodError was thrown during a platform message callback:
I/flutter ( 3978): The getter 'length' was called on null.
I/flutter ( 3978): Receiver: null
I/flutter ( 3978): Tried calling: length
I/flutter ( 3978): 
I/flutter ( 3978): When the exception was thrown, this was the stack:
I/flutter ( 3978): #0      Object.noSuchMethod (dart:core-patch/object_patch.dart:50:5)
I/flutter ( 3978): #1      RenderEditable._handleHorizontalArrows (package:flutter/src/rendering/editable.dart:431:49)
I/flutter ( 3978): #2      RenderEditable._handleKeyEvent (package:flutter/src/rendering/editable.dart:400:19)
I/flutter ( 3978): #3      RawKeyboard._handleKeyEvent (package:flutter/src/services/raw_keyboard.dart:494:17)
I/flutter ( 3978): <asynchronous suspension>
I/flutter ( 3978): #4      BasicMessageChannel.setMessageHandler.<anonymous closure> (package:flutter/src/services/platform_channel.dart:65:49)
I/flutter ( 3978): <asynchronous suspension>
I/flutter ( 3978): #5      BinaryMessages.handlePlatformMessage (package:flutter/src/services/platform_messages.dart:76:33)
I/flutter ( 3978): <asynchronous suspension>
I/flutter ( 3978): #6      _invoke3.<anonymous closure> (dart:ui/hooks.dart:263:15)
I/flutter ( 3978): #10     _invoke3 (dart:ui/hooks.dart:262:10)
I/flutter ( 3978): #11     _dispatchPlatformMessage (dart:ui/hooks.dart:136:5)
I/flutter ( 3978): (elided 3 frames from package dart:async)
I/flutter ( 3978): ════════════════════════════════════════════════════════════════════════════════════════════════════
```

App:
```
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      home: Scaffold(
        body: Center(
          child: TextFormField(),
        ),
      )
    );
  }
}
```

## Logs

`flutter doctor -v`:

```
C:\Users\xx\textfield>flutter doctor -v
[√] Flutter (Channel stable, v1.5.4-hotfix.2, on Microsoft Windows [Version 10.0.17763.557], locale de-DE)
    • Flutter version 1.5.4-hotfix.2 at C:\Dev\flutter
    • Framework revision 7a4c33425d (9 weeks ago), 2019-04-29 11:05:24 -0700
    • Engine revision 52c7a1e849
    • Dart version 2.3.0 (build 2.3.0-dev.0.5 a1668566e5)


[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at C:\Users\x\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
    • All Android licenses accepted.

[√] Android Studio (version 3.4)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 36.1.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

[!] IntelliJ IDEA Ultimate Edition (version 2017.3)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA 2017.3.4
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.dev/intellij-setup/#installing-the-plugins

[√] IntelliJ IDEA Ultimate Edition (version 2019.1)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA 2018.2.1
    • Flutter plugin version 36.1.4
    • Dart plugin version 191.7830

[√] Connected device (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 8.1.0 (API 27) (emulator)

! Doctor found issues in 1 category.

```

**Comment by HansMuller** [comment]
CC @gspencergoog

**Comment by TahaTesser** [comment]
Hi @ehhc 
This issue doesn't reproduce on latest dev 

<details>
<summary>`flutter doctor -v`</summary>

```
[✓] Flutter (Channel dev, v1.18.0, on Mac OS X 10.15.4 19E266, locale en-GB)
    • Flutter version 1.18.0 at /Users/taha/Code/flutter_dev
    • Framework revision 8f7327f83a (31 hours ago), 2020-04-06 22:11:01 -0400
    • Engine revision 49891e0653
    • Dart version 2.8.0 (build 2.8.0-dev.20.0 1210d27678)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/taha/Code/sdk
    • Platform android-29, build-tools 29.0.3
    • ANDROID_HOME = /Users/taha/Code/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.
[✓] Xcode - develop for iOS and macOS (Xcode 11.4)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.4, Build version 11E146
    • CocoaPods version 1.9.1
[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome
[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 45.0.1
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build
      1.8.0_212-release-1586-b4-5784211)
[✓] VS Code (version 1.43.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.9.1
[✓] Connected device (4 available)
    • SM M305F   • 32003c30dc19668f • android-arm64  • Android 10 (API 29)
    • macOS      • macOS            • darwin-x64     • Mac OS X 10.15.4 19E266
    • Chrome     • chrome           • web-javascript • Google Chrome
      80.0.3987.149
    • Web Server • web-server       • web-javascript • Flutter Tools
• No issues found!
```

</details>

if you disagree please write in the comments and I will reopen it 
Thank you
