### ISSUE TITLE
Adding controller.value to Text crashes app

### ISSUE THREAD

**Issue by skaterdude** [flutter/flutter#35287]
Using the code from the appbrewery flash-chat-flutter app, added an animation controller per steps in lesson "F12.5 Custom Animations - Tickers, Animation Controllers, Animation values.mp4".  

Here's the setup:
  void initState() {
    super.initState();
    controller = AnimationController(
      duration: Duration(seconds: 1),
      vsync: this,
      upperBound: 100,
    );
    controller.forward();
    controller.addListener(() {
      setState(() {});
      print(controller.value);
    });
  }

And here's the code that results in the crash.

                Text(
                  '${controller.value.toInt()}%',
                  style: TextStyle(
                    fontSize: 45.0,
                    fontWeight: FontWeight.w900,
                  ),

The code appears to exactly match what's in the lesson, and there's no problem there.

## Logs

```
Performing hot restart...
Syncing files to device Pixel 2 XL...
Restarted application in 4,981ms.
I/flutter ( 9966): 0.0
I/flutter ( 9966): 0.0
I/flutter ( 9966): 3.3333000000000004
I/flutter ( 9966): ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
I/flutter ( 9966): The following assertion was thrown building WelcomeScreen(dirty, state:
I/flutter ( 9966): _WelcomeScreenState#8022f(ticker active)):
I/flutter ( 9966): 'dart:ui/painting.dart': Failed assertion: line 187: '<optimized out>': is not true.
I/flutter ( 9966): 
I/flutter ( 9966): Either the assertion indicates an error in the framework itself, or we should provide substantially
I/flutter ( 9966): more information in this error message to help you determine and fix the underlying cause.
I/flutter ( 9966): In either case, please report this assertion by filing a bug on GitHub:
I/flutter ( 9966):   https://github.com/flutter/flutter/issues/new?template=BUG.md
I/flutter ( 9966): 
I/flutter ( 9966): When the exception was thrown, this was the stack:
I/flutter ( 9966): #2      Color.withOpacity (dart:ui/painting.dart:187:12)
I/flutter ( 9966): #3      _WelcomeScreenState.build (package:flash_chat/screens/welcome_screen.dart:32:35)
I/flutter ( 9966): #4      StatefulElement.build (package:flutter/src/widgets/framework.dart:3825:27)
I/flutter ( 9966): #5      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3739:15)
I/flutter ( 9966): #6      Element.rebuild (package:flutter/src/widgets/framework.dart:3565:5)
I/flutter ( 9966): #7      BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2278:33)
I/flutter ( 9966): #8      _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding&WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:700:20)
I/flutter ( 9966): #9      _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:286:5)
I/flutter ( 9966): #10     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1012:15)
I/flutter ( 9966): #11     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:952:9)
I/flutter ( 9966): #12     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:864:5)
I/flutter ( 9966): #16     _invoke (dart:ui/hooks.dart:219:10)
I/flutter ( 9966): #17     _drawFrame (dart:ui/hooks.dart:178:3)
I/flutter ( 9966): (elided 5 frames from class _AssertionError and package dart:async)
I/flutter ( 9966): ════════════════════════════════════════════════════════════════════════════════════════════════════
I/flutter ( 9966): 11.6249
I/flutter ( 9966): Another exception was thrown: 'dart:ui/painting.dart': Failed assertion: line 187: '<optimized out>': is not true.
I/flutter ( 9966): 13.286100000000001
(repeats many times)

Also, on the screen of the device, it shows:

'dart:ui/painting.dart': Failed assertion: line 187: '<optimized out>': is not true.

```

```
Analyzing flash-chat-flutter...
No issues found! (ran in 7.5s)

```
flutter 

```
[√] Flutter (Channel stable, v1.5.4-hotfix.2, on Microsoft Windows [Version 6.1.7601], locale en-US)
    • Flutter version 1.5.4-hotfix.2 at F:\src\Flutter\flutter
    • Framework revision 7a4c33425d (9 weeks ago), 2019-04-29 11:05:24 -0700
    • Engine revision 52c7a1e849
    • Dart version 2.3.0 (build 2.3.0-dev.0.5 a1668566e5)
```

**Comment by skaterdude** [comment]
Found the problem.  I missed the part in the lesson where, after changing the upperBound to 100, the red.withOpacity(controller.value) is changed back to white.  So the problem appears to be that if you give the opacity as > 1, the app crashes with no useful indication of the source of the problem.  Shouldn't the method check for a value within bounds and flag an error message that notes an out-of-bounds condition?  Or force any value >1 to 1?  While an erroneous value is definitely the cause of the problem, erroneous values happen, and can also be security issues.  So not checking bounds is a problem.

**Comment by mikhail-tokarev** [comment]
hi @skaterdude 
I'm glad that you found a solution.

I think it's safe to close this issue,
if you disagree please write in the comments and I will reopen it.
