### ISSUE TITLE
Add support for infinite GridView.builder (with itemCount set to null)

### ISSUE THREAD

**Issue by modulovalue** [flutter/flutter#35328]
```dart
GridView.builder(
  gridDelegate: SliverGridDelegateWithFixedCrossAxisCount(crossAxisCount: 2),
  itemBuilder: (context, index) {
    if (index < 10)
      return Text(index.toString());
    else
      return null;
  },
);
```

I expected GridView.builder to behave the same as ListView.builder i.e. scrolling past the last element before null is returned should not be possible.

But the following is thrown:

```
                                                   
Reloaded 105 of 1547 libraries in 2.313ms.
flutter: ══╡ EXCEPTION CAUGHT BY RENDERING LIBRARY ╞═════════════════════════════════════════════════════════
flutter: The following assertion was thrown during performLayout():
flutter: 'package:flutter/src/rendering/sliver_grid.dart': Failed assertion: line 227 pos 12: 'childCount !=
flutter: null': is not true.
flutter: 
flutter: Either the assertion indicates an error in the framework itself, or we should provide substantially
flutter: more information in this error message to help you determine and fix the underlying cause.
flutter: In either case, please report this assertion by filing a bug on GitHub:
flutter:   https://github.com/flutter/flutter/issues/new?template=BUG.md
flutter: 
flutter: When the exception was thrown, this was the stack:
flutter: #2      SliverGridRegularTileLayout.computeMaxScrollOffset (package:flutter/src/rendering/sliver_grid.dart:227:12)
flutter: #3      RenderSliverGrid.performLayout (package:flutter/src/rendering/sliver_grid.dart:545:35)
flutter: #4      RenderObject.layout (package:flutter/src/rendering/object.dart:1619:7)
flutter: #5      RenderSliverPadding.performLayout (package:flutter/src/rendering/sliver_padding.dart:181:11)
flutter: #6      RenderObject.layout (package:flutter/src/rendering/object.dart:1619:7)
flutter: #7      RenderViewportBase.layoutChildSequence (package:flutter/src/rendering/viewport.dart:406:13)
flutter: #8      RenderViewport._attemptLayout (package:flutter/src/rendering/viewport.dart:1334:12)
flutter: #9      RenderViewport.performLayout (package:flutter/src/rendering/viewport.dart:1252:20)
flutter: #10     RenderObject._layoutWithoutResize (package:flutter/src/rendering/object.dart:1496:7)
flutter: #11     PipelineOwner.flushLayout (package:flutter/src/rendering/object.dart:765:18)
flutter: #12     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding.drawFrame (package:flutter/src/rendering/binding.dart:346:19)
flutter: #13     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding&WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:701:13)
flutter: #14     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:285:5)
flutter: #15     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1016:15)
flutter: #16     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:958:9)
flutter: #17     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:874:5)
flutter: #21     _invoke (dart:ui/hooks.dart:236:10)
flutter: #22     _drawFrame (dart:ui/hooks.dart:194:3)
flutter: (elided 5 frames from class _AssertionError and package dart:async)
flutter: 
flutter: The following RenderObject was being processed when the exception was fired: RenderSliverGrid#bbf52 relayoutBoundary=up2 NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE:
flutter:   needs compositing
flutter:   creator: SliverGrid ← MediaQuery ← SliverPadding ← Viewport ← IgnorePointer-[GlobalKey#8b00f] ←
flutter:     Semantics ← Listener ← _GestureSemantics ←
flutter:     RawGestureDetector-[LabeledGlobalKey<RawGestureDetectorState>#b1c7a] ← Listener ← _ScrollableScope
flutter:     ← _ScrollSemantics-[GlobalKey#a279e] ← ⋯
flutter:   parentData: paintOffset=Offset(0.0, 0.0) (can use size)
flutter:   constraints: SliverConstraints(AxisDirection.down, GrowthDirection.forward, ScrollDirection.reverse,
flutter:     scrollOffset: 2065.0, remainingPaintExtent: 837.0, crossAxisExtent: 717.0, crossAxisDirection:
flutter:     AxisDirection.right, viewportMainAxisExtent: 837.0, remainingCacheExtent: 1337.0 cacheOrigin:
flutter:     -250.0 )
flutter:   geometry: SliverGeometry(scrollExtent: Infinity, hidden, maxPaintExtent: Infinity,
flutter:     hasVisualOverflow: true, cacheExtent: 9.4)
flutter:   no children current live
flutter: This RenderObject has no descendants.
flutter: ════════════════════════════════════════════════════════════════════════════════════════════════════
flutter: Another exception was thrown: 'package:flutter/src/rendering/sliver_grid.dart': Failed assertion: line 227 pos 12: 'childCount != null': is not true.
flutter: Another exception was thrown: 'package:flutter/src/rendering/sliver_grid.dart': Failed assertion: line 227 pos 12: 'childCount != null': is not true.
flutter: Another exception was thrown: 'package:flutter/src/rendering/sliver_grid.dart': Failed assertion: line 227 pos 12: 'childCount != null': is not true.
```

```
[✓] Flutter (Channel dev, v1.7.11, on Mac OS X 10.14.5 18F132, locale de-DE)
    • Flutter version 1.7.11 at /Users/x/Desktop/flutter
    • Framework revision 43b03127d4 (2 days ago), 2019-06-26 23:27:39 -0400
    • Engine revision f3761ba8d0
    • Dart version 2.4.0
```

**Comment by minh98** [comment]
why do you not trying use itemCount

**Comment by modulovalue** [comment]
> why do you not trying use itemCount

I have a big list that needs to be filtered. I can't get the length of the filtered list without iterating through the whole iterable. 
But I would need the length of the iterable to use GridView with itemCount. 
Omitting the itemCount and using a `CachingIterable` does give me pretty significant performance improvements, therefore, to remove UI Jank as much as possible I want to use GridView.builder without the itemCount property.

**Comment by talhabalaj** [comment]
Any updates on this?

**Comment by crtl** [comment]
This issue still exists.

**Comment by Piinks** [comment]
This feature is currently supported, closing as completed.
