### ISSUE TITLE
getting error while build apk

### ISSUE THREAD

**Issue by elyasbeshkani** [flutter/flutter#35337]
Hi
what is this error?

## command
```
flutter build apk --release
```
## exception
```
ProcessException: ProcessException: Process "F:\MyProjects\alimelodi\android\gradlew.bat" exited abnormally:
Exception in thread "main" java.lang.RuntimeException: Could not load wrapper properties from 'F:\MyProjects\alimelodi\android\gradle\wrapper\gradle-wrapper.properties'.
	at org.gradle.wrapper.WrapperExecutor.<init>(WrapperExecutor.java:64)
	at org.gradle.wrapper.WrapperExecutor.forWrapperPropertiesFile(WrapperExecutor.java:47)
	at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:60)
Caused by: java.net.URISyntaxException: Illegal character in scheme name at index 15: distributionUrl=https://services.gradle.org/distributions/gradle-4.10.2-all.zip
	at java.net.URI$Parser.fail(URI.java:2848)
	at java.net.URI$Parser.checkChars(URI.java:3021)
	at java.net.URI$Parser.parse(URI.java:3048)
	at java.net.URI.<init>(URI.java:588)
	at org.gradle.wrapper.WrapperExecutor.readDistroUrl(WrapperExecutor.java:81)
	at org.gradle.wrapper.WrapperExecutor.prepareDistributionUri(WrapperExecutor.java:70)
	at org.gradle.wrapper.WrapperExecutor.<init>(WrapperExecutor.java:57)
	... 2 more
  Command: F:\MyProjects\alimelodi\android\gradlew.bat -v

#0      runCheckedAsync (package:flutter_tools/src/base/process.dart:255:5)
<asynchronous suspension>
#1      _initializeGradle (package:flutter_tools/src/android/gradle.dart:225:9)
<asynchronous suspension>
#2      _ensureGradle (package:flutter_tools/src/android/gradle.dart:206:37)
<asynchronous suspension>
#3      buildGradleProject (package:flutter_tools/src/android/gradle.dart:336:31)
<asynchronous suspension>
#4      buildApk (package:flutter_tools/src/android/apk.dart:34:9)
<asynchronous suspension>
#5      BuildApkCommand.runCommand (package:flutter_tools/src/commands/build_apk.dart:51:11)
<asynchronous suspension>
#6      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:559:18)
#7      _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:77:64)
#8      _rootRunUnary (dart:async/zone.dart:1132:38)
#9      _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#10     _FutureListener.handleValue (dart:async/future_impl.dart:126:18)
#11     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:639:45)
#12     Future._propagateToListeners (dart:async/future_impl.dart:668:32)
#13     Future._complete (dart:async/future_impl.dart:473:7)
#14     _SyncCompleter.complete (dart:async/future_impl.dart:51:12)
#15     _AsyncAwaitCompleter.complete.<anonymous closure> (dart:async-patch/async_patch.dart:33:20)
#16     _rootRun (dart:async/zone.dart:1124:13)
#17     _CustomZone.run (dart:async/zone.dart:1021:19)
#18     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:947:23)
#19     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#20     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#21     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:115:13)
#22     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:5)
```
## flutter doctor
```
[32m[✓][39m Flutter (Channel stable, v1.5.4-hotfix.2, on Microsoft Windows [Version 10.0.17763.316], locale fa-IR)
    [32m•[39m Flutter version 1.5.4-hotfix.2 at F:\flutter
    [32m•[39m Framework revision 7a4c33425d (9 weeks ago), 2019-04-29 11:05:24 -0700
    [32m•[39m Engine revision 52c7a1e849
    [32m•[39m Dart version 2.3.0 (build 2.3.0-dev.0.5 a1668566e5)

[32m[✓][39m Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    [32m•[39m Android SDK at F:\sdk
    [32m•[39m Android NDK location not configured (optional; useful for native profiling support)
    [32m•[39m Platform android-28, build-tools 28.0.3
    [32m•[39m ANDROID_HOME = F:\sdk
    [32m•[39m Java binary at: F:\android-studio\jre\bin\java
    [32m•[39m Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)
    [32m•[39m All Android licenses accepted.

[32m[✓][39m Android Studio (version 3.3)
    [32m•[39m Android Studio at F:\android-studio
    [32m•[39m Flutter plugin version 34.0.1
    [32m•[39m Dart plugin version 182.5215
    [32m•[39m Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)

[32m[✓][39m VS Code (version 1.35.1)
    [32m•[39m VS Code at C:\Users\Elyas\AppData\Local\Programs\Microsoft VS Code
    [32m•[39m Flutter extension version 3.2.0

[32m[✓][39m Connected device (1 available)
    [32m•[39m Android SDK built for x86 • emulator-5554 • android-x86 • Android 8.0.0 (API 26) (emulator)

[32m•[39m No issues found!
```

**Comment by buaashuai** [comment]
i meet the same error too.

**Comment by BondarenkoStas** [comment]
@elyasbeshkani Did you manage to solve the issue? Please provide your gradle-wrapper.properties content.

**Comment by iapicca** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
  
Thanks for your contribution.
