### ISSUE TITLE
i have problem to install app on my emulator and my emulator version is android 9

### ISSUE THREAD

**Issue by mehdidavarpanah66** [flutter/flutter#35357]
```
Launching lib\main.dart on SM J730F in debug mode...
Initializing gradle...
Resolving dependencies...
Running Gradle task 'assembleDebug'...
Built build\app\outputs\apk\debug\app-debug.apk.
Security exception: Permission Denial: forceStopPackage() from pid=22863, uid=2000 requires android.permission.FORCE_STOP_PACKAGES

java.lang.SecurityException: Permission Denial: forceStopPackage() from pid=22863, uid=2000 requires android.permission.FORCE_STOP_PACKAGES
	at com.android.server.am.ActivityManagerService.forceStopPackage(ActivityManagerService.java:8748)
	at com.android.server.am.ActivityManagerShellCommand.runForceStop(ActivityManagerShellCommand.java:967)
	at com.android.server.am.ActivityManagerShellCommand.onCommand(ActivityManagerShellCommand.java:197)
	at android.os.ShellCommand.exec(ShellCommand.java:103)
	at com.android.server.am.ActivityManagerService.onShellCommand(ActivityManagerService.java:20320)
	at android.os.Binder.shellCommand(Binder.java:642)
	at android.os.Binder.onTransact(Binder.java:540)
	at android.app.IActivityManager$Stub.onTransact(IActivityManager.java:3442)
	at com.android.server.am.ActivityManagerService.onTransact(ActivityManagerService.java:4181)
	at android.os.Binder.execTransact(Binder.java:739)
Installing build\app\outputs\apk\app.apk...
Error: ADB exited with exit code 1
Performing Streamed Install

adb: failed to install G:\flutter_project\f_project\foodyhouse\build\app\outputs\apk\app.apk: Security exception: Permission Denial: runInstallCreate from pm command asks to run as user -1 but is calling from user 0; this requires android.permission.INTERACT_ACROSS_USERS_FULL

java.lang.SecurityException: Permission Denial: runInstallCreate from pm command asks to run as user -1 but is calling from user 0; this requires android.permission.INTERACT_ACROSS_USERS_FULL
	at com.android.server.am.UserController.handleIncomingUser(UserController.java:1827)
	at com.android.server.am.ActivityManagerService.
Error launching application on SM J730F.
```

**Comment by allanrg4** [comment]
You can check this [post](https://es.stackoverflow.com/questions/276288/error-en-app-flutter-en-la-api-level-29-pie-de-android/276303#276303) on stackoverflow in spanish, that work for me.

**Comment by PredatH0r** [comment]
I have a Samsung J7 too and after upgrading to Android 9 a few days ago, I get the same error when I try to deploy my app through USB debugging cable.
The same app works fine on other phones and on an Emulator running Android 9, so it seems like Samsung broke the J7 for developers

**Comment by PredatH0r** [comment]
Found the solution in this post now: https://stackoverflow.com/questions/56723254/permission-denial-rununinstall-from-pm-command-asks-to-run-as-user-1-but-is-ca

1) disable developer mode on your J7
2) restart your phone
3) enable developer again (by clicking 7 times on the build number in the device infos)

**Comment by BondarenkoStas** [comment]
Thank you @PredatH0r ! @mehdidavarpanah66 did you manage to solve the issue?

**Comment by iapicca** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
  
Thanks for your contribution.
