### ISSUE TITLE
[image_picker] Crash when picking Imgur GIF.

### ISSUE THREAD

**Issue by ozzy1873** [flutter/flutter#35372]
## Steps to Reproduce

1. Install Imgur
2. Use the image picker to pick an Imgur Reaction Gif
3. Crashes instantly and no exception is caught.

This used to work, but I don't remember which version of image_picker.

## Logs

```
2019-06-30 10:21:51.754 9260-9260/? E/CursorWindow: Failed to read row 0, column 0 from a CursorWindow which has 1 rows, 0 columns.
2019-06-30 10:21:51.756 9260-9260/? D/AndroidRuntime: Shutting down VM
2019-06-30 10:21:51.758 9260-9260/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.myapp.android, PID: 9260
    java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=2342, result=-1, data=Intent { dat=content://com.imgur.mobile.reactionsprovider/internal_imgur_files/imgur_reaction.gif typ=image/gif flg=0x3 }} to activity {com.myapp.android/com.myapp.android.MainActivity}: java.lang.IllegalStateException: Couldn't read row 0, col 0 from CursorWindow.  Make sure the Cursor is initialized correctly before accessing data from it.
        at android.app.ActivityThread.deliverResults(ActivityThread.java:4398)
        at android.app.ActivityThread.handleSendResult(ActivityThread.java:4440)
        at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:49)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1816)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6718)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
     Caused by: java.lang.IllegalStateException: Couldn't read row 0, col 0 from CursorWindow.  Make sure the Cursor is initialized correctly before accessing data from it.
        at android.database.CursorWindow.nativeGetString(Native Method)
        at android.database.CursorWindow.getString(CursorWindow.java:465)
        at android.database.AbstractWindowedCursor.getString(AbstractWindowedCursor.java:51)
        at android.database.CursorWrapper.getString(CursorWrapper.java:137)
        at io.flutter.plugins.imagepicker.FileUtils.getImageExtension(FileUtils.java:182)
        at io.flutter.plugins.imagepicker.FileUtils.getPathFromRemoteUri(FileUtils.java:144)
        at io.flutter.plugins.imagepicker.FileUtils.getPathFromUri(FileUtils.java:44)
        at io.flutter.plugins.imagepicker.ImagePickerDelegate.handleChooseImageResult(ImagePickerDelegate.java:441)
        at io.flutter.plugins.imagepicker.ImagePickerDelegate.onActivityResult(ImagePickerDelegate.java:421)
        at io.flutter.app.FlutterPluginRegistry.onActivityResult(FlutterPluginRegistry.java:222)
        at io.flutter.app.FlutterActivityDelegate.onActivityResult(FlutterActivityDelegate.java:141)
        at io.flutter.app.FlutterActivity.onActivityResult(FlutterActivity.java:142)
        at android.app.Activity.dispatchActivityResult(Activity.java:7462)
        at android.app.ActivityThread.deliverResults(ActivityThread.java:4391)
        at android.app.ActivityThread.handleSendResult(ActivityThread.java:4440) 
        at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:49) 
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1816) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:193) 
        at android.app.ActivityThread.main(ActivityThread.java:6718) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858) 
2019-06-30 10:21:51.828 1177-1186/? I/system_server: Background concurrent copying GC freed 227671(16MB) AllocSpace objects, 1023(54MB) LOS objects, 34% free, 44MB/68MB, paused 73us total 128.606ms
2019-06-30 10:21:51.849 1177-3583/? W/ActivityManager:   Force finishing activity com.myapp.android/.MainActivity
2019-06-30 10:21:51.855 9260-9260/? I/Process: Sending signal. PID: 9260 SIG: 9
```

```
No issues found! (ran in 13.5s)
```

```
[√] Flutter (Channel beta, v1.6.3, on Microsoft Windows [Version 10.0.18362.207], locale en-US)
    • Flutter version 1.6.3 at c:\src\flutter
    • Framework revision bc7bc94083 (5 weeks ago), 2019-05-23 10:29:07 -0700
    • Engine revision 8dc3a4cde2
    • Dart version 2.3.2 (build 2.3.2-dev.0.0 e3edfd36b2)


[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at C:\Users\john\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
    • All Android licenses accepted.

[√] Android Studio (version 3.4)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 36.1.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

[√] Connected device (1 available)
    • Pixel 3 • 8B8X15F76 • android-arm64 • Android 9 (API 28)

• No issues found!
```

**Comment by AmolGangadhare** [comment]
Same error for me. I didn't try it with gif, it crashed when I select file manager in select photo wizard

![image](https://user-images.githubusercontent.com/33967327/60662068-04300c80-9e79-11e9-9e1e-ffd208d4d5a0.png)

**Comment by AmolGangadhare** [comment]
Possible #35632 and fix flutter/plugins#1804 try it again in a new version

**Comment by BondarenkoStas** [comment]
@ozzy1873 Please report if you got it working. The fix is already on the current flutter stable.

**Comment by ozzy1873** [comment]
Yes, this is working now. Thanks!
