### ISSUE TITLE
[ERROR:flutter/lib/ui/ui_dart_state.cc(148)] Unhandled Exception: FormatException: Unexpected character (at character 2)

### ISSUE THREAD

**Issue by rrifafauzikomara** [flutter/flutter#35395]
I have a code like this:

  ```
var jsonData;
  final fileUtils = FileUtils();

@override
  void initState() {
    super.initState();
    getJsonData();
  }

getJsonData() async {
    var strData = await fileUtils.readFromFile();
    jsonData = json.decode(strData);
  }

getJsonCatList() {
    return Center(
      child: FutureBuilder(
        future: jsonData,
        initialData: null,
        builder: (context, AsyncSnapshot<String> snapshot) {
          if (snapshot.connectionState == ConnectionState.done) {
            if (snapshot.hasError) {
              return Text(snapshot.error.toString());
            } else if (snapshot.hasData) {
              if (jsonData != null) {
//                jsonData = jsonDecode(snapshot.data);
                return _cardCategory(jsonData);
              } else {
                return Text('Data kosong');
              }
            } else {
              return Text('Ini apa 1');
            }
          }
          return Center(child: CircularProgressIndicator());
        },
      ),
    );
  }

Widget _cardCategory(jsonData) {
//    var numItems = snapshot == null ? 0 : snapshot.data.catlist.sublist(0, 7).length;
    var numItems = jsonData.catlist.sublist(0, 7).length;
    return Container(
      transform: Matrix4.translationValues(0.0, -20.0, 0.0),
      child: Card(
        elevation: 5.0,
        shape: RoundedRectangleBorder(borderRadius: BorderRadius.all(Radius.circular(5))),
        margin: EdgeInsets.only(left: 16.0, right: 16.0),
        child: numItems == 0 ? Container() : GridView.builder(
          shrinkWrap: true,
          primary: false, //kill scrollable
          itemCount: numItems + 1, //must keep using +1
          gridDelegate: SliverGridDelegateWithFixedCrossAxisCount(crossAxisCount: 4),
          itemBuilder: (BuildContext context, int index) {
            String imagePath;
            String itemText;
            if (index == numItems) {
              imagePath = 'assets/images/main/cat_999.png';
              itemText = 'More';
            } else {
              imagePath = 'assets/images/main/cat_${jsonData.catlist[index].a}.png';
              itemText = jsonData.catlist[index].c;
            }
            return GestureDetector(
                child: Card(
                  elevation: 0.0,
                  child: Column(
                    children: <Widget>[
                      Expanded(
                        child: Image.asset(imagePath, fit: BoxFit.cover),
                      ),
                      Text(
                        itemText,
                        style: TextStyle(fontSize: 10),
                      ),
                    ],
                  ),
                ),
//                onTap: () {
//                  index == 7 ? _showModalBottomSheet(snapshot) : nextScreen17(index);
//                }
            );
          },
        ),
      ),
    );
  }
```

Flow:
1. I save the JSON data from the get API into the File Manager. (This works)
2. I read the contents of the file manager (This also works)
3. I want to display JSON data from the file manager and displayed in the application. (This is a problem, as in the code above)

When I run the application, there is an error as below:
```
I/flutter (22494): save data to file .json File: '/data/user/0/com.cariaja.cari_mobile_flutter_main/app_flutter/cai_file.json'
E/flutter (22494): [ERROR:flutter/lib/ui/ui_dart_state.cc(148)] Unhandled Exception: FormatException: Unexpected character (at character 2)
E/flutter (22494): {ver: 1.1.4, catlist: [{a: 1, b: 0, c: Food & Beverage, d: maincat_eat_58dp...
E/flutter (22494):  ^
E/flutter (22494): 
E/flutter (22494): #0      _ChunkedJsonParser.fail (dart:convert-patch/convert_patch.dart:1392:5)
E/flutter (22494): #1      _ChunkedJsonParser.parse (dart:convert-patch/convert_patch.dart:922:48)
E/flutter (22494): #2      _parseJson (dart:convert-patch/convert_patch.dart:29:10)
E/flutter (22494): #3      JsonDecoder.convert (dart:convert/json.dart:493:36)
E/flutter (22494): #4      JsonCodec.decode (dart:convert/json.dart:151:41)
E/flutter (22494): #5      MainPageState.getJsonData (package:cari_mobile_flutter_main/src/view/main/main_page.dart:159:21)
E/flutter (22494): <asynchronous suspension>
E/flutter (22494): #6      MainPageState.initState (package:cari_mobile_flutter_main/src/view/main/main_page.dart:147:5)
E/flutter (22494): #7      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3846:58)
E/flutter (22494): #8      ComponentElement.mount (package:flutter/src/widgets/framework.dart:3717:5)
E/flutter (22494): #9      Element.inflateWidget (package:flutter/src/widgets/framework.dart:2961:14)
E/flutter (22494): #10     Element.updateChild (package:flutter/src/widgets/framework.dart:2764:12)
E/flutter (22494): #11     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3750:16)
E/flutter (22494): #12     Element.rebuild (package:flutter/src/widgets/framework.dart:3565:5)
E/flutter (22494): #13     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3722:5)
E/flutter (22494): #14     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3717:5)
E/flutter (22494): #15     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2961:14)
E/flutter (22494): #16     Element.updateChild (package:flutter/src/widgets/framework.dart:2764:12)
E/flutter (22494): #17     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3750:16)
E/flutter (22494): #18     Element.rebuild (package:flutter/src/widgets/framework.dart:3565:5)
E/flutter (22494): #19     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3722:5)
E/flutter (22494): #20     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3717:5)
E/flutter (22494): #21     ParentDataElement.mount (package:flutter/src/widgets/framework.dart:4063:11)
E/flutter (22494): #22     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2961:14)
E/flutter (22494): #23     MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4982:32)
E/flutter (22494): #24     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2961:14)
E/flutter (22494): #25     Element.updateChild (package:flutter/src/widgets/framework.dart:2764:12)
E/flutter (22494): #26     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3750:16)
E/flutter (22494): #27     Element.rebuild (package:flutter/src/widgets/framework.dart:3565:5)
E/flutter (22494): #28     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3722:5)
E/flutter (22494): #29     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3864:11)
E/flutter (22494): #30     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3717:5)
E/flutter (22494): #31     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2961:14)
E/flutter (22494): #32     Element.updateChild (package:flutter/src/widgets/framework.dart:2764:12)
E/flutter (22494): #33     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3750:16)
E/flutter (22494): #34     Element.rebuild (package:flutter/src/widgets/framework.dart:3565:5)
E/flutter (22494): #35     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3722:5)
E/flutter (22494): #36     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3717:5)
E/flutter (22494): #37     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2961:14)
E/flutter (22494): #38     Element.updateChild (package:flutter/src/widgets/framework.dart:2764:12)
E/flutter (22494): #39     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3750:16)
E/flutter (22494): #40     Element.rebuild (package:flutter/src/widgets/framework.dart:3565:5)
E/flutter (22494): #41     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3722:5)
E/flutter (22494): #42     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3864:11)
E/flutter (22494): #43     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3717:5)
E/flutter (22494): #44     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2961:14)
E/flutter (22494): #45     Element.updateChild (package:flutter/src/widgets/
```

and in the application, it always calls the loading indicator continuously.

Anyone can help me? And what should I improve on my code above?

**Comment by miyoyo** [comment]
Your JSON is invalid (you need quotes around strings)
This issue should not have been posted here, as this is not a crash, an error internal to the framework, or an error in the native side.

Please use https://stackoverflow.com or such next time.

**Comment by Alixhan** [comment]
This is just an exception.

**Comment by rrifafauzikomara** [comment]
Yeah, it's already fixed it. Just save the data before decode then read the data, decode it, display it to a widget.

Sorry for ask here, because yesterday I try to ask in https://stackoverflow.com/ it's can't because when choosing tags, the results don't appear. So I can't make a question there
