### ISSUE TITLE
Don't run experimental tests on stable branches 

### ISSUE THREAD

**Issue by tvolkert** [flutter/flutter#35471]
As seen in https://cirrus-ci.com/task/6220526698102784:

We're attempting to run web tests on stable branches (`flutter build web -v in dev\integration_tests\web`), and they're failing with:

```
Experimental feature web is not supported on stable branches
#0      throwToolExit (package:flutter_tools/src/base/common.dart:28:3)
#1      FlutterCommand.validateCommand (package:flutter_tools/src/runner/flutter_command.dart:569:7)
<asynchronous suspension>
#2      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:462:11)
<asynchronous suspension>
#3      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:383:33)
<asynchronous suspension>
#4      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:29)
<asynchronous suspension>
#5      _rootRun (dart:async/zone.dart:1124:13)
#6      _CustomZone.run (dart:async/zone.dart:1021:19)
#7      _runZoned (dart:async/zone.dart:1516:10)
#8      runZoned (dart:async/zone.dart:1463:12)
#9      AppContext.run (package:flutter_tools/src/base/context.dart:152:18)
<asynchronous suspension>
#10     FlutterCommand.run (package:flutter_tools/src/runner/flutter_command.dart:375:20)
#11     CommandRunner.runCommand (package:args/command_runner.dart:197:27)
<asynchronous suspension>
#12     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:396:21)
```

**Comment by tvolkert** [comment]
@jonahwilliams @digiter

**Comment by tvolkert** [comment]
Closing as obsolete
