### ISSUE TITLE
[web]: Flutter build crashed 

### ISSUE THREAD

**Issue by maxnemoy** [flutter/flutter#35500]
## Steps to Reproduce

1. flutter create --web ./newweb && cd newweb
2. flutter run -d chrome

## Logs

```
flutter run -d chrome -v
...
[   +4 ms] Succeeded after 4.3s with 0 outputs (0 actions)

[+7014 ms] "flutter run" took 19,155ms.
[        ] "flutter run" took 19,155ms.
Unable to connect to Chrome debug port: 43437
 type 'Utf8Decoder' is not a subtype of type 'StreamTransformer<Uint8List, String>' of 'streamTransformer'

#0      throwToolExit (package:flutter_tools/src/base/common.dart:28:3)
#1      ChromeLauncher._connect (package:flutter_tools/src/web/chrome.dart:139:7)
<asynchronous suspension>
#2      ChromeLauncher.launch (package:flutter_tools/src/web/chrome.dart:120:12)
<asynchronous suspension>
#3      ResidentWebRunner.run (package:flutter_tools/src/resident_web_runner.dart:150:48)
<asynchronous suspension>
#4      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:469:37)
<asynchronous suspension>
#5      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:477:18)
<asynchronous suspension>
#6      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:383:33)
<asynchronous suspension>
#7      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:29)
<asynchronous suspension>
#8      _rootRun (dart:async/zone.dart:1124:13)
#9      _CustomZone.run (dart:async/zone.dart:1021:19)
#10     _runZoned (dart:async/zone.dart:1516:10)
#11     runZoned (dart:async/zone.dart:1463:12)
#12     AppContext.run (package:flutter_tools/src/base/context.dart:152:18)
<asynchronous suspension>
#13     FlutterCommand.run (package:flutter_tools/src/runner/flutter_command.dart:375:20)
#14     CommandRunner.runCommand (package:args/command_runner.dart:197:27)
<asynchronous suspension>
#15     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:396:21)
<asynchronous suspension>
#16     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:29)
<asynchronous suspension>
#17     _rootRun (dart:async/zone.dart:1124:13)
#18     _CustomZone.run (dart:async/zone.dart:1021:19)
#19     _runZoned (dart:async/zone.dart:1516:10)
#20     runZoned (dart:async/zone.dart:1463:12)
#21     AppContext.run (package:flutter_tools/src/base/context.dart:152:18)
<asynchronous suspension>
#22     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:356:19)
<asynchronous suspension>
#23     CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:112:25)
#24     new Future.sync (dart:async/future.dart:224:31)
#25     CommandRunner.run (package:args/command_runner.dart:112:14)
#26     FlutterCommandRunner.run (package:flutter_tools/src/runner/flutter_command_runner.dart:242:18)
#27     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:62:22)
<asynchronous suspension>
#28     _rootRun (dart:async/zone.dart:1124:13)
#29     _CustomZone.run (dart:async/zone.dart:1021:19)
#30     _runZoned (dart:async/zone.dart:1516:10)
#31     runZoned (dart:async/zone.dart:1500:12)
#32     run.<anonymous closure> (package:flutter_tools/runner.dart:60:18)
<asynchronous suspension>
#33     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:29)
<asynchronous suspension>
#34     _rootRun (dart:async/zone.dart:1124:13)
#35     _CustomZone.run (dart:async/zone.dart:1021:19)
#36     _runZoned (dart:async/zone.dart:1516:10)
#37     runZoned (dart:async/zone.dart:1463:12)
#38     AppContext.run (package:flutter_tools/src/base/context.dart:152:18)
<asynchronous suspension>
#39     runInContext (package:flutter_tools/src/context_runner.dart:56:24)
<asynchronous suspension>
#40     run (package:flutter_tools/runner.dart:51:10)
#41     main (package:flutter_tools/executable.dart:62:9)
<asynchronous suspension>
#42     main (file:///home/maxnemoy/libs/flutter/packages/flutter_tools/bin/flutter_tools.dart:8:3)
#43     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:303:32)
#44     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:12)
```

## flutter doctor -v
```
[✓] Flutter (Channel master, v1.8.1-pre.10, on Linux, locale en_US.UTF-8)
    • Flutter version 1.8.1-pre.10 at /home/maxnemoy/libs/flutter
    • Framework revision 556e374e02 (56 minutes ago), 2019-07-02 17:40:55 -0700
    • Engine revision 7d3e722349
    • Dart version 2.5.0 (build 2.5.0-dev.0.0 67ab3be10d)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.0)
    • Android SDK at /home/maxnemoy/Android/Sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.0
    • Java binary at: /home/maxnemoy/progs/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b16-5323222)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Linux toolchain - develop for Linux desktop
    • clang++ 6.0.0
    • GNU Make 4.1

[✓] Android Studio (version 3.4)
    • Android Studio at /home/maxnemoy/progs/android-studio
    • Flutter plugin version 36.1.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b16-5323222)

[✓] VS Code (version 1.35.1)
    • VS Code at /usr/share/code
    • Flutter extension version 3.2.0

[✓] Connected device (2 available)
    • Linux  • Linux  • linux-x64      • Linux
    • Chrome • chrome • web-javascript • Google Chrome 75.0.3770.100 


• No issues found!
```

PS same problem for flutter_web

**Comment by githubjin** [comment]
same problem for flutter

**Comment by githubjin** [comment]
flutter channel dev @maxnemoy

**Comment by maxnemoy** [comment]
`Flutter 1.8.1-pre.20` -> solved the problem with `webdev serve`
`Flutter 1.8.1-pre.22` -> solved the problem with `flutter run -d chrome`

**Comment by githubjin** [comment]
same problem

Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel master, v1.8.1-pre.22, on Mac OS X 10.14.5 18F132, locale zh-Hans-CN)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 10.2.1)
[✓] iOS tools - develop for iOS devices
[✓] Chrome - develop for the web
[✓] Android Studio (version 3.4)
[✓] VS Code (version 1.36.0)
[✓] Connected device (3 available)

• No issues found!

**Comment by jonahwilliams** [comment]
This should be fixed on the latest master

**Comment by githubjin** [comment]
Error: "The argument type 'Utf8Decoder' can't be assigned to the parameter type 'StreamTransformer<Uint8List, dynamic>'."
How to fix: Use StreamTransformer.bind(Stream) instead of Stream.transform(StreamTransformer).
Example:
Before: foo.transform(utf8.decoder)...
After: utf8.decoder.bind(foo)...

**Comment by jonahwilliams** [comment]
@githubjin To upgrade run `flutter channel master` and then `flutter upgrade`. If this still doesn't work, please paste the results of `flutter doctor -v` so I can see the exact commit you are on.

**Comment by ACChe** [comment]
Same problem at ver.1.9, but I did not install Android part, will it lead to problems?

**Comment by housed-cjy** [comment]
gradle version is not right  , open android project  and then  sync  downloading
