### ISSUE TITLE
i have a problem in webdev serve

### ISSUE THREAD

**Issue by ocelili** [flutter/flutter#35512]
when I try the webdev serve the error appears

PS F:\belajar_flutter\retgoo_internal> webdev serve
```
[INFO] Starting resource servers...Unhandled exception:
SocketException: Failed to create server socket (OS Error: Only one usage of each socket address (protocol/network address/port) is normally permitted.
, errno = 10048), address = 127.0.0.1, port = 8080
#0      _NativeSocket.bind (dart:io-patch/socket_patch.dart:591:7)
<asynchronous suspension>
#1      _RawServerSocket.bind (dart:io-patch/socket_patch.dart:1206:26)
#2      _ServerSocket.bind (dart:io-patch/socket_patch.dart:1466:29)
#3      ServerSocket.bind (dart:io-patch/socket_patch.dart:1457:26)
#4      _HttpServer.bind (dart:_http/http_impl.dart:2520:25)
#5      HttpServer.bind (dart:_http:227:19)
#6      HttpMultiServer.loopback.<anonymous closure> (package:http_multi_server/http_multi_server.dart:113:39)
#7      HttpMultiServer._loopback (package:http_multi_server/http_multi_server.dart:172:30)
<asynchronous suspension>
#8      HttpMultiServer.loopback (package:http_multi_server/http_multi_server.dart:111:12)
#9      HttpMultiServer.bind (package:http_multi_server/http_multi_server.dart:148:30)
#10     WebDevServer.start (package:webdev/src/serve/webdev_server.dart:84:40)
#11     _AsyncAwaitCompleter.start (dart:async-patch/async_patch.dart:49:6)
#12     WebDevServer.start (package:webdev/src/serve/webdev_server.dart:55:36)
#13     ServerManager.start (package:webdev/src/serve/server_manager.dart:22:38)
#14     _AsyncAwaitCompleter.start (dart:async-patch/async_patch.dart:49:6)
#15     ServerManager.start (package:webdev/src/serve/server_manager.dart:18:37)
#16     _startServerManager (package:webdev/src/serve/dev_workflow.dart:85:27)
#17     _AsyncAwaitCompleter.start (dart:async-patch/async_patch.dart:49:6)
#18     _startServerManager (package:webdev/src/serve/dev_workflow.dart:66:42)
#19     DevWorkflow.start (package:webdev/src/serve/dev_workflow.dart:186:31)
#20     _RootZone.runUnary (dart:async/zone.dart:1379:54)
#21     _FutureListener.handleValue (dart:async/future_impl.dart:126:18)
#22     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:639:45)
#23     Future._propagateToListeners (dart:async/future_impl.dart:668:32)
#24     Future._complete (dart:async/future_impl.dart:473:7)
#25     _SyncCompleter.complete (dart:async/future_impl.dart:51:12)
#26     _AsyncAwaitCompleter.complete.<anonymous closure> (dart:async-patch/async_patch.dart:33:20)
#27     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#28     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#29     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:115:13)
#30     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:5)
[INFO] Starting resource servers...Unhandled exception:
SocketException: Failed to create server socket (OS Error: Only one usage of each socket address (protocol/network address/port) is normally permitted.
, errno = 10048), address = 127.0.0.1, port = 8080
#0      _NativeSocket.bind (dart:io-patch/socket_patch.dart:591:7)
<asynchronous suspension>
#1      _RawServerSocket.bind (dart:io-patch/socket_patch.dart:1206:26)
#2      _ServerSocket.bind (dart:io-patch/socket_patch.dart:1466:29)
#3      ServerSocket.bind (dart:io-patch/socket_patch.dart:1457:26)
#4      _HttpServer.bind (dart:_http/http_impl.dart:2520:25)
#5      HttpServer.bind (dart:_http:227:19)
#6      HttpMultiServer.loopback.<anonymous closure> (package:http_multi_server/http_multi_server.dart:113:39)
#7      HttpMultiServer._loopback (package:http_multi_server/http_multi_server.dart:172:30)
<asynchronous suspension>
#8      HttpMultiServer.loopback (package:http_multi_server/http_multi_server.dart:111:12)
#9      HttpMultiServer.bind (package:http_multi_server/http_multi_server.dart:148:30)
#10     WebDevServer.start (package:webdev/src/serve/webdev_server.dart:84:40)
#11     _AsyncAwaitCompleter.start (dart:async-patch/async_patch.dart:49:6)
#12     WebDevServer.start (package:webdev/src/serve/webdev_server.dart:55:36)
#13     ServerManager.start (package:webdev/src/serve/server_manager.dart:22:38)
#14     _AsyncAwaitCompleter.start (dart:async-patch/async_patch.dart:49:6)
#15     ServerManager.start (package:webdev/src/serve/server_manager.dart:18:37)
#16     _startServerManager (package:webdev/src/serve/dev_workflow.dart:85:27)
#17     _AsyncAwaitCompleter.start (dart:async-patch/async_patch.dart:49:6)
#18     _startServerManager (package:webdev/src/serve/dev_workflow.dart:66:42)
#19     DevWorkflow.start (package:webdev/src/serve/dev_workflow.dart:186:31)
#20     _RootZone.runUnary (dart:async/zone.dart:1379:54)
#21     _FutureListener.handleValue (dart:async/future_impl.dart:126:18)
#22     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:639:45)
#23     Future._propagateToListeners (dart:async/future_impl.dart:668:32)
#24     Future._complete (dart:async/future_impl.dart:473:7)
#25     _SyncCompleter.complete (dart:async/future_impl.dart:51:12)
#26     _AsyncAwaitCompleter.complete.<anonymous closure> (dart:async-patch/async_patch.dart:33:20)
#27     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#28     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#29     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:115:13)
#30     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:5)
```

I don't know the problem where is it, please help me !!

**Comment by maxnemoy** [comment]
@ocelili if U use flutter >= 1.8.1-pre.10 
try `flutter version v1.8.0`

**Comment by ocelili** [comment]
@maxnemoy this problem arises when I delete the cache in C: \ Users \ username \ AppData \ Roaming \ Pub \ Cache

**Comment by BondarenkoStas** [comment]
@ocelili Do you still encounter the problem? Please provide your flutter doctor -v output.

**Comment by jonahwilliams** [comment]
The webdev serve development process for flutter has been deprecated since we've unforked. You can now use the regular flutter_tool, following the instructions at https://flutter.dev/web
