### ISSUE TITLE
flutter_driver screenshot fails with "[VERBOSE-2:rasterizer.cc(321)] Last layer tree was null when screenshotting."

### ISSUE THREAD

**Issue by StepFischer** [flutter/flutter#35521]
Hi,

currently I am trying to set up everything to automatically capturing screenshots for my app using the Integration Testing with flutter_driver.

My test code looks as follows
```dart
// ./test_driver/screenshot.dart
// Imports the Flutter Driver API
import 'package:flutter_driver/flutter_driver.dart';
import 'package:test/test.dart' as test;

void main() {
  test.group('Nt App Screenshots', () {
    // First, define the Finders. We can use these to locate Widgets from the
    // test suite. Note: the Strings provided to the `byValueKey` method must
    // be the same as the Strings we used for the Keys in step 1.
    final screenFinder = find.byValueKey('screen');

    FlutterDriver driver;

    // Connect to the Flutter driver before running any tests
    test.setUpAll(() async {
      driver = await FlutterDriver.connect();
    });

    // Close the connection to the driver after the tests have completed
    test.tearDownAll(() async {
      if (driver != null) {
        driver.close();
      }
    });

    test.test('Make screenshots', () async {
      test.expect(driver.waitFor(screenFinder), test.completes);
      await driver.waitFor(screenFinder);
      await driver.screenshot();
    });
  });
}
```

Which leads to the following output when executing `flutter drive --target=./test_driver/screenshot.dart`
```zsh
Using device iPhone 7 Plus.
Starting application: ./test_driver/screenshot.dart
Running Xcode build...

 ├─Assembling Flutter resources...                           1.9s
 └─Compiling, linking and signing...                        12.1s
Xcode build done.                                           19.1s
[Crashlytics] Version 3.12.0 (136)
Configuring the default Firebase app...
flutter: Observatory listening on http://127.0.0.1:52107/JCZ3xdDGRYo=/
Configured the default Firebase app __FIRAPP_DEFAULT.
[Fabric] [Fabric +with] called multiple times. Only the first call is honored, please pass all kits you wish to initialize
	[C4.1 907F9BF1-C641-4FAA-9A4C-A9C5F92A6B3C 192.168.107.129:52110<->157.240.27.18:443]
	Connected Path: satisfied (Path is satisfied), interface: en0
	Duration: 0.310s, DNS @0.001s took 0.007s, TCP @0.025s took 0.024s, TLS took 0.071s
	bytes in/out: 3934/773, packets in/out: 6/7, rtt: 0.019s, retransmitted packets: 0, out-of-order packets: 0
	[C3.1 0CFF480A-D723-4ADE-9B11-AA70F7228EC6 192.168.107.129:52109<->157.240.27.18:443]
	Connected Path: satisfied (Path is satisfied), interface: en0
	Duration: 0.320s, DNS @0.000s took 0.012s, TCP @0.027s took 0.023s, TLS took 0.068s
	bytes in/out: 4009/1015, packets in/out: 7/7, rtt: 0.021s, retransmitted packets: 0, out-of-order packets: 0
	[C2.1 061A056B-5F4C-4131-84F5-A871471B803A 192.168.107.129:52111<->172.217.21.202:443]
	Connected Path: satisfied (Path is satisfied), interface: en0
	Duration: 0.365s, DNS @0.001s took 0.039s, TCP @0.041s took 0.028s, TLS took 0.196s
	bytes in/out: 4661/1085, packets in/out: 8/9, rtt: 0.026s, retransmitted packets: 0, out-of-order packets: 0
	[C1.1 354C8917-A902-42EF-AFB1-F6EF7FDC9FC3 192.168.107.129:52108<->54.243.221.190:443]
	Connected Path: satisfied (Path is satisfied), interface: en0
	Duration: 0.566s, DNS @0.003s took 0.034s, TCP @0.048s took 0.107s, TLS took 0.239s
	bytes in/out: 7274/1322, packets in/out: 7/3, rtt: 0.100s, retransmitted packets: 0, out-of-order packets: 0
00:00 +0: Nt App Screenshots (setUpAll)
[info ] FlutterDriver: Connecting to Flutter application at http://127.0.0.1:52107/JCZ3xdDGRYo=/
[trace] FlutterDriver: Isolate found with number: 541189528
[trace] FlutterDriver: Isolate is paused at start.
[trace] FlutterDriver: Attempting to resume isolate
[trace] FlutterDriver: Waiting for service extension
[info ] FlutterDriver: Connected to Flutter application.
00:00 +0: Nt App Screenshots Make screenshots
	[C5.1 FD8BF0C7-9417-4B9C-BAED-3A354575C63D 192.168.107.129:52117<->216.58.205.227:443]
	Connected Path: satisfied (Path is satisfied), interface: en0
	Duration: 0.146s, DNS @0.000s took 0.002s, TCP @0.003s took 0.022s, TLS took 0.062s
	bytes in/out: 4444/771, packets in/out: 8/8, rtt: 0.021s, retransmitted packets: 0, out-of-order packets: 0
	[C6.1 0417BE41-E9B3-4A98-96FB-065ECAED3347 192.168.107.129:52118<->172.217.19.78:443]
	Connected Path: satisfied (Path is satisfied), interface: en0
	Duration: 0.186s, DNS @0.000s took 0.001s, TCP @0.003s took 0.025s, TLS took 0.067s
	bytes in/out: 3859/764, packets in/out: 7/8, rtt: 0.024s, retransmitted packets: 0, out-of-order packets: 0
	[C7.1 5C71013A-5566-471C-963E-E7A556244041 192.168.107.129:52119<->172.217.19.78:443]
	Connected Path: satisfied (Path is satisfied), interface: en0
	Duration: 0.187s, DNS @0.000s took 0.001s, TCP @0.002s took 0.027s, TLS took 0.066s
	bytes in/out: 3617/1251, packets in/out: 7/9, rtt: 0.025s, retransmitted packets: 0, out-of-order packets: 0
[VERBOSE-2:rasterizer.cc(321)] Last layer tree was null when screenshotting.
00:02 +0 -1: Nt App Screenshots Make screenshots [E]
  JSON-RPC error -32000: Could not capture image screenshot.
  package:json_rpc_2/src/client.dart 110:64             Client.sendRequest
  package:json_rpc_2/src/peer.dart 68:15                Peer.sendRequest
  package:flutter_driver/src/driver/driver.dart 702:53  FlutterDriver.screenshot
  ===== asynchronous gap ===========================
  dart:async/zone.dart 1053:19                          _CustomZone.registerUnaryCallback
  dart:async-patch/async_patch.dart 77:23               _asyncThenWrapperHelper
  package:flutter_driver/src/driver/driver.dart         FlutterDriver.screenshot
  test_driver/screenshot_test.dart 34:20                main.<fn>.<fn>
  ===== asynchronous gap ===========================
  dart:async/zone.dart 1053:19                          _CustomZone.registerUnaryCallback
  dart:async-patch/async_patch.dart 77:23               _asyncThenWrapperHelper
  test_driver/screenshot_test.dart                      main.<fn>.<fn>
  package:test_api/src/backend/declarer.dart 168:27     Declarer.test.<fn>.<fn>.<fn>
  ===== asynchronous gap ===========================
  dart:async/zone.dart 1053:19                          _CustomZone.registerUnaryCallback
  dart:async-patch/async_patch.dart 77:23               _asyncThenWrapperHelper
  package:test_api/src/backend/declarer.dart            Declarer.test.<fn>.<fn>.<fn>
  package:test_api/src/backend/invoker.dart 250:15      Invoker.waitForOutstandingCallbacks.<fn>
  ===== asynchronous gap ===========================
  dart:async/zone.dart 1045:19                          _CustomZone.registerCallback
  dart:async/zone.dart 962:22                           _CustomZone.bindCallbackGuarded
  dart:async/timer.dart 52:45                           new Timer
  dart:async/timer.dart 87:9                            Timer.run
  dart:async/future.dart 174:11                         new Future
  package:test_api/src/backend/invoker.dart 399:21      Invoker._onRun.<fn>.<fn>.<fn>

00:03 +0 -1: Nt App Screenshots (tearDownAll)
00:03 +0 -1: Some tests failed.

Unhandled exception:
Dummy exception to set exit code.
#0      _rootHandleUncaughtError.<anonymous closure> (dart:async/zone.dart:1112:29)
#1      _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#2      _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#3      _Timer._runTimers (dart:isolate-patch/timer_impl.dart:391:30)
#4      _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:416:5)
#5      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:171:12)
Stopping application instance.
Driver tests failed: 255
```

I have also tried several solutions, like waiting some extra seconds before screenshotting, because I saw some comment that the function has to wait 2 seconds by default to let the rasterizer finish its work. Sencond I had already checked if the beta and dev channel hat fixed the issue, but no luck.

This is my flutter doctor output
```zsh
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, v1.5.4-hotfix.2, on Mac OS X 10.14.5 18F203, locale en-GB)

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[✓] iOS toolchain - develop for iOS devices (Xcode 10.2.1)
[✓] Android Studio (version 3.4)
[✓] VS Code (version 1.35.1)
[✓] Connected device (1 available)

• No issues found!
```

Trying to use the flutter screenshot function results in a correct screenshot of the device screen.

Any thoughts or advises on this issue?

Best regards,
Stephan

**Comment by StepFischer** [comment]
So, it seems that I have found the solution by myself.

The issue is caused by an overlay (modal dialog) on iOS, which asks the user to allow to forward to google.com.

I guess this causes the layer tree to be null, because there are no Flutter widgets living on this overlay or something similiar. (I am not familiar with the in-depth rendering flow)

So I will close this issue and leave this comment for documentation purposes.
