### ISSUE TITLE
Error running Gradle on flutter build

### ISSUE THREAD

**Issue by MqtUA** [flutter/flutter#35525]
When i trying to run any project in Emulator or Physical Device i get same error:

```
flutter run
Launching lib/main.dart on SM J600F in debug mode...
Initializing gradle...                                              4,3s
Resolving dependencies...
* Error running Gradle:
ProcessException: Process
"C:\Users\maxpu\Documents\DEV\Flutter_Pojects\test_app\android\gradlew.bat"
exited abnormally:
FAILURE: Build failed with an exception.
* What went wrong:
org/gradle/launcher/daemon/protocol/DaemonMessageSerializer$BuildSerializer
* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
* Get more help at https://help.gradle.org
  Command:
  C:\Users\maxpu\Documents\DEV\Flutter_Pojects\test_app\android\gradlew.bat
  app:properties
Please review your Gradle project setup in the android/ folder.
```

## Steps to Reproduce

1. Created new project in Android Studio
2. run in console "flutter pub get"
3. run in console "flutter run"

## Logs
```
$ flutter run --verbose
[  +63 ms] executing: [C:\Flutter\] git log -n 1 --pretty=format:%H
[ +224 ms] Exit code 0 from: git log -n 1 --pretty=format:%H
[   +6 ms] 7a4c33425ddd78c54aba07d86f3f9a4a0051769b
[   +1 ms] executing: [C:\Flutter\] git describe --match v*.*.* --first-parent
--long --tags
[ +195 ms] Exit code 0 from: git describe --match v*.*.* --first-parent --long
--tags
[   +2 ms] v1.5.4-hotfix.2-0-g7a4c33425
[  +23 ms] executing: [C:\Flutter\] git rev-parse --abbrev-ref --symbolic @{u}
[ +191 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[   +1 ms] origin/stable
[        ] executing: [C:\Flutter\] git ls-remote --get-url origin
[ +162 ms] Exit code 0 from: git ls-remote --get-url origin
[   +1 ms] https://github.com/flutter/flutter.git
[ +243 ms] executing: [C:\Flutter\] git rev-parse --abbrev-ref HEAD
[ +183 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[   +1 ms] stable
[ +137 ms] executing:
C:\Users\maxpu\AppData\Local\Android\sdk\platform-tools\adb.exe devices -l
[ +138 ms] Exit code 0 from:
C:\Users\maxpu\AppData\Local\Android\sdk\platform-tools\adb.exe devices -l
[   +2 ms] List of devices attached
           520059e5c05b357b       device product:j6ltecis model:SM_J600F
           device:j6lte transport_id:1
[  +29 ms] C:\Users\maxpu\AppData\Local\Android\sdk\platform-tools\adb.exe -s
520059e5c05b357b shell getprop
[ +324 ms] Artifact Instance of 'FlutterWebSdk' is not required, skipping
update.
[  +13 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required,
skipping update.
[   +3 ms] Artifact Instance of 'MacOSEngineArtifacts' is not required, skippingupdate.
[   +3 ms] Artifact Instance of 'LinuxEngineArtifacts' is not required, skippingupdate.
[   +2 ms] Artifact Instance of 'FuchsiaCacheArtifacts' is not required,
skipping update.
[ +336 ms] ro.hardware = samsungexynos7870
[  +75 ms] Launching lib/main.dart on SM J600F in debug mode...
[  +42 ms] Initializing gradle...
[   +3 ms] Using gradle from
C:\Users\maxpu\Documents\DEV\Flutter_Pojects\test_app\android\gradlew.bat.
[ +231 ms] executing:
C:\Users\maxpu\Documents\DEV\Flutter_Pojects\test_app\android\gradlew.bat -v
[+1951 ms]
                    ------------------------------------------------------------
                    Gradle 4.10.2
                    ------------------------------------------------------------

                    Build time:   2018-09-19 18:10:15 UTC
                    Revision:     b4d8d5d170bb4ba516e88d7fe5647e2323d791dd

                    Kotlin DSL:   1.0-rc-6
                    Kotlin:       1.2.61
                    Groovy:       2.4.15
                    Ant:          Apache Ant(TM) version 1.9.11 compiled on
                    March 23 2018
                    JVM:          1.8.0_152-release (JetBrains s.r.o 25.152-b01)
                    OS:           Windows 10 10.0 amd64
[  +24 ms] Initializing gradle... (completed in 2,2s)
[   +2 ms] Resolving dependencies...
[   +1 ms] executing:
[C:\Users\maxpu\Documents\DEV\Flutter_Pojects\test_app\android\]
C:\Users\maxpu\Documents\DEV\Flutter_Pojects\test_app\android\gradlew.bat
app:properties
[+1463 ms]
                    FAILURE: Build failed with an exception.

                    * What went wrong:
                    org/gradle/launcher/daemon/protocol/DaemonMessageSerializer$
                    BuildSerializer

                    * Try:
                    Run with --stacktrace option to get the stack trace. Run
                    with --info or --debug option to get more log output. Run
                    with --scan to get full insights.

                    * Get more help at https://help.gradle.org
[   +9 ms] Resolving dependencies... (completed in 1,5s)
[   +7 ms] * Error running Gradle:
           ProcessException: Process

"C:\Users\maxpu\Documents\DEV\Flutter_Pojects\test_app\android\gradlew.bat"
           exited abnormally:

           FAILURE: Build failed with an exception.

           * What went wrong:

org/gradle/launcher/daemon/protocol/DaemonMessageSerializer$BuildSerializer

           * Try:
           Run with --stacktrace option to get the stack trace. Run with --info or --debug
           option to get more log output. Run with --scan to get full insights.

           * Get more help at https://help.gradle.org
             Command:

C:\Users\maxpu\Documents\DEV\Flutter_Pojects\test_app\android\gradlew.bat
             app:properties

[  +25 ms] "flutter run" took 5 026ms.
[   +1 ms] "flutter run" took 5 026ms.
Please review your Gradle project setup in the android/ folder.

#0      throwToolExit (package:flutter_tools/src/base/common.dart:24:3)
#1      _readGradleProject (package:flutter_tools/src/android/gradle.dart:158:7)<asynchronous suspension>
#2      _gradleProject (package:flutter_tools/src/android/gradle.dart:111:34)
<asynchronous suspension>
#3      getGradleAppOut (package:flutter_tools/src/android/gradle.dart:105:29)
<asynchronous suspension>
#4      AndroidApk.fromAndroidProject
(package:flutter_tools/src/application_package.dart:154:23)
<asynchronous suspension>
#5      ApplicationPackageFactory.getPackageForPlatform
(package:flutter_tools/src/application_package.dart:46:32)
<asynchronous suspension>
#6      FlutterDevice.runHot
(package:flutter_tools/src/resident_runner.dart:345:56)
<asynchronous suspension>
#7      HotRunner.run (package:flutter_tools/src/run_hot.dart:253:39)
<asynchronous suspension>
#8      RunCommand.runCommand
(package:flutter_tools/src/commands/run.dart:428:37)
<asynchronous suspension>
#9      FlutterCommand.verifyThenRunCommand
(package:flutter_tools/src/runner/flutter_command.dart:559:18)
#10     _asyncThenWrapperHelper.<anonymous closure>
(dart:async-patch/async_patch.dart:77:64)
#11     _rootRunUnary (dart:async/zone.dart:1132:38)
#12     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#13     _FutureListener.handleValue (dart:async/future_impl.dart:126:18)
#14     Future._propagateToListeners.handleValueCallback
(dart:async/future_impl.dart:639:45)
#15     Future._propagateToListeners (dart:async/future_impl.dart:668:32)
#16     Future._complete (dart:async/future_impl.dart:473:7)
#17     _SyncCompleter.complete (dart:async/future_impl.dart:51:12)
#18     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:28:18) #19     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:294:13)
#20     RunCommand.usageValues (package:flutter_tools/src/commands/run.dart)
#21     _asyncThenWrapperHelper.<anonymous closure>
(dart:async-patch/async_patch.dart:77:64)
#22     _rootRunUnary (dart:async/zone.dart:1132:38)
#23     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#24     _FutureListener.handleValue (dart:async/future_impl.dart:126:18)
#25     Future._propagateToListeners.handleValueCallback
(dart:async/future_impl.dart:639:45)
#26     Future._propagateToListeners (dart:async/future_impl.dart:668:32)
#27     Future._complete (dart:async/future_impl.dart:473:7)
#28     _SyncCompleter.complete (dart:async/future_impl.dart:51:12)
#29     _AsyncAwaitCompleter.complete.<anonymous closure>
(dart:async-patch/async_patch.dart:33:20)
#30     _rootRun (dart:async/zone.dart:1124:13)
#31     _CustomZone.run (dart:async/zone.dart:1021:19)
#32     _CustomZone.bindCallback.<anonymous closure>
(dart:async/zone.dart:947:23)
#33     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#34     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#35     _runPendingImmediateCallback
(dart:isolate-patch/isolate_patch.dart:115:13)
#36     _RawReceivePortImpl._handleMessage
(dart:isolate-patch/isolate_patch.dart:172:5)
```

```
$ flutter analyze
Analyzing test_app...
No issues found! (ran in 32.4s)
```

```
$ flutter doctor -v
[√] Flutter (Channel stable, v1.5.4-hotfix.2, on Microsoft Windows [Version
    10.0.18356.16], locale uk-UA)
    • Flutter version 1.5.4-hotfix.2 at C:\Flutter
    • Framework revision 7a4c33425d (9 weeks ago), 2019-04-29 11:05:24 -0700
    • Engine revision 52c7a1e849
    • Dart version 2.3.0 (build 2.3.0-dev.0.5 a1668566e5)


[√] Android toolchain - develop for Android devices (Android SDK version 29.0.0)
    • Android SDK at C:\Users\maxpu\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling
      support)
    • Platform android-29, build-tools 29.0.0
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_152-release-1343-b01)
    • All Android licenses accepted.

[√] Android Studio (version 3.4)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 37.0.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build
      1.8.0_152-release-1343-b01)

[√] VS Code, 64-bit edition (version 1.35.1)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Flutter extension version 3.2.0

[√] Connected device (1 available)
    • SM J600F • 520059e5c05b357b • android-arm • Android 9 (API 28)

• No issues found!
```

**Comment by MqtUA** [comment]
Solved this by changing Gradle version in `android\gradle\wrapper\gradle-wrapper.properties` from 4.10.2 to 5.5.
Also changed it in `Flutter_DIR\packages\flutter_tools\templates\app\android.tmpl\gradle\wrapper\gradle-wrapper.properties` so that all new projects was with this fix.
New gradle-wrapper.properties:
```
distributionBase=GRADLE_USER_HOME
distributionPath=wrapper/dists
zipStoreBase=GRADLE_USER_HOME
zipStorePath=wrapper/dists
distributionUrl=https\://services.gradle.org/distributions/gradle-5.5-all.zip
```
