### ISSUE TITLE
[web]: Flutter wed build crash with a NoSuchMethodError: The getter 'renames' was called on null.

### ISSUE THREAD

**Issue by marmotini** [flutter/flutter#35526]
I'm trying to migrating a Flutter mobile app to Flutter web using the provided [guidelines](https://github.com/flutter/flutter_web/blob/master/docs/migration_guide.md). App runs well but the flutter web build is crashing when trying to build. 

**Environment** 

Dart VM version: 2.3.1 (Tue May 21 19:28:38 2019 +0200) on "windows_x64"
Flutter 1.6.3 • channel beta • https://github.com/flutter/flutter.git
Framework • revision bc7bc94083 (6 weeks ago) • 2019-05-23 10:29:07 -0700
Engine • revision 8dc3a4cde2
Tools • Dart 2.3.2 (build 2.3.2-dev.0.0 e3edfd36b2)
Firefox 67.0.4 (64-bit)

Below is the stacktrace

```
NoSuchMethodError: The getter 'renames' was called on null.
Receiver: null
Tried calling: renames
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:50:5)
#1      TemporaryNamer.getName (package:dev_compiler/src/compiler/js_names.dart:93:24)
#2      Printer.visitIdentifier (package:dev_compiler/src/js_ast/printer.dart:932:20)
#3      Identifier.accept (package:dev_compiler/src/js_ast/nodes.dart:1392:50)
#4      Printer.visit (package:dev_compiler/src/js_ast/printer.dart:216:10)
#5      Printer.visitNestedExpression (package:dev_compiler/src/js_ast/printer.dart:638:7)
#6      Printer.visitVariableInitialization (package:dev_compiler/src/js_ast/printer.dart:720:5)
#7      VariableInitialization.accept (package:dev_compiler/src/js_ast/nodes.dart:1007:15)
#8      Printer.visit (package:dev_compiler/src/js_ast/printer.dart:216:10)
#9      Printer.visitNestedExpression (package:dev_compiler/src/js_ast/printer.dart:638:7)
#10     Printer.visitCommaSeparated (package:dev_compiler/src/js_ast/printer.dart:228:7)
#11     Printer.visitVariableDeclarationList (package:dev_compiler/src/js_ast/printer.dart:649:5)
#12     VariableDeclarationList.accept (package:dev_compiler/src/js_ast/nodes.dart:955:15)
#13     Printer.visit (package:dev_compiler/src/js_ast/printer.dart:216:10)
#14     Printer.visitNestedExpression (package:dev_compiler/src/js_ast/printer.dart:638:7)
#15     Printer.visitExpressionStatement (package:dev_compiler/src/js_ast/printer.dart:302:5)
#16     ExpressionStatement.accept (package:dev_compiler/src/js_ast/nodes.dart:466:50)
#17     Printer.visit (package:dev_compiler/src/js_ast/printer.dart:216:10)
#18     Printer.blockOutWithoutBraces (package:dev_compiler/src/js_ast/printer.dart:271:7)
#19     List.forEach (dart:core-patch/growable_array.dart:278:8)
#20     Printer.blockOut (package:dev_compiler/src/js_ast/printer.dart:281:21)
#21     Printer.blockBody (package:dev_compiler/src/js_ast/printer.dart:248:7)
#22     Printer.visitArrowFun (package:dev_compiler/src/js_ast/printer.dart:1028:7)
#23     ArrowFun.accept (package:dev_compiler/src/js_ast/nodes.dart:1524:50)
#24     Printer.visit (package:dev_compiler/src/js_ast/printer.dart:216:10)
#25     Printer.visitNestedExpression (package:dev_compiler/src/js_ast/printer.dart:633:7)
#26     Printer.visitCall (package:dev_compiler/src/js_ast/printer.dart:763:5)
#27     Call.accept (package:dev_compiler/src/js_ast/nodes.dart:1176:50)
#28     MetaLet.accept (package:dev_compiler/src/compiler/js_metalet.dart:157:29)
#29     Printer.visit (package:dev_compiler/src/js_ast/printer.dart:216:10)
#30     Printer.visitNestedExpression (package:dev_compiler/src/js_ast/printer.dart:638:7)
#31     Printer.visitConditional (package:dev_compiler/src/js_ast/printer.dart:744:5)
#32     Conditional.accept (package:dev_compiler/src/js_ast/nodes.dart:1153:50)
#33     MetaLet.accept (package:dev_compiler/src/compiler/js_metalet.dart:157:29)
#34     Printer.visit (package:dev_compiler/src/js_ast/printer.dart:216:10)
#35     Printer.visitNestedExpression (package:dev_compiler/src/js_ast/printer.dart:638:7)
#36     Printer.visitCommaSeparated (package:dev_compiler/src/js_ast/printer.dart:228:7)
#37     Printer.visitCall (package:dev_compiler/src/js_ast/printer.dart:766:5)
#38     Call.accept (package:dev_compiler/src/js_ast/nodes.dart:1176:50)
#39     Printer.visit (package:dev_compiler/src/js_ast/printer.dart:216:10)
#40     Printer.visitNestedExpression (package:dev_compiler/src/js_ast/printer.dart:638:7)
#41     Printer.visitReturn (package:dev_compiler/src/js_ast/printer.dart:476:7)
#42     Return.accept (package:dev_compiler/src/js_ast/nodes.dart:662:50)
#43     Printer.visit (package:dev_compiler/src/js_ast/printer.dart:216:10)
#44     Printer.blockOutWithoutBraces (package:dev_compiler/src/js_ast/printer.dart:271:7)
#45     List.forEach (dart:core-patch/growable_array.dart:278:8)
#46     Printer.blockOut (package:dev_compiler/src/js_ast/printer.dart:281:21)
#47     Printer.visitMethod (package:dev_compiler/src/js_ast/printer.dart:1220:7)
#48     Method.accept (package:dev_compiler/src/js_ast/nodes.dart:1918:50)
#49     Printer.visit (package:dev_compiler/src/js_ast/printer.dart:216:10)
#50     Printer.visitClassExpression (package:dev_compiler/src/js_ast/printer.dart:1180:9)
#51     ClassExpression.accept (package:dev_compiler/src/js_ast/nodes.dart:1878:50)
#52     Printer.visit (package:dev_compiler/src/js_ast/printer.dart:216:10)
#53     Printer.visitNestedExpression (package:dev_compiler/src/js_ast/printer.dart:638:7)
#54     Printer.visitAssignment (package:dev_compiler/src/js_ast/printer.dart:713:7)
#55     Assignment.accept (package:dev_compiler/src/js_ast/nodes.dart:986:50)
#56     Printer.visit (package:dev_compiler/src/js_ast/printer.dart:216:10)
#57     Printer.visitNestedExpression (package:dev_compiler/src/js_ast/printer.dart:638:7)
#58     Printer.visitExpressionStatement (package:dev_compiler/src/js_ast/printer.dart:302:5)
#59     ExpressionStatement.accept (package:dev_compiler/src/js_ast/nodes.dart:466:50)
#60     Printer.visit (package:dev_compiler/src/js_ast/printer.dart:216:10)
#61     Printer.blockOutWithoutBraces (package:dev_compiler/src/js_ast/printer.dart:271:7)
#62     List.forEach (dart:core-patch/growable_array.dart:278:8)
#63     Printer.blockOut (package:dev_compiler/src/js_ast/printer.dart:281:21)
#64     Printer.blockBody (package:dev_compiler/src/js_ast/printer.dart:248:7)
#65     Printer.functionOut (package:dev_compiler/src/js_ast/printer.dart:599:5)
#66     Printer.visitFun (package:dev_compiler/src/js_ast/printer.dart:999:5)
#67     Fun.accept (package:dev_compiler/src/js_ast/nodes.dart:1497:50)
#68     Printer.visit (package:dev_compiler/src/js_ast/printer.dart:216:10)
#69     Printer.visitNestedExpression (package:dev_compiler/src/js_ast/printer.dart:638:7)
#70     Printer.visitCommaSeparated (package:dev_compiler/src/js_ast/printer.dart:228:7)
#71     Printer.visitCall (package:dev_compiler/src/js_ast/printer.dart:766:5)
#72     Call.accept (package:dev_compiler/src/js_ast/nodes.dart:1176:50)
#73     Printer.visit (package:dev_compiler/src/js_ast/printer.dart:216:10)
#74     Printer.visitNestedExpression (package:dev_compiler/src/js_ast/printer.dart:638:7)
#75     Printer.visitExpressionStatement (package:dev_compiler/src/js_ast/printer.dart:302:5)
#76     ExpressionStatement.accept (package:dev_compiler/src/js_ast/nodes.dart:466:50)
#77     Printer.visit (package:dev_compiler/src/js_ast/printer.dart:216:10)
#78     List.forEach (dart:core-patch/growable_array.dart:278:8)
#79     Printer.visitAll (package:dev_compiler/src/js_ast/printer.dart:234:11)
#80     Printer.visitProgram (package:dev_compiler/src/js_ast/printer.dart:242:5)
#81     Program.accept (package:dev_compiler/src/js_ast/nodes.dart:361:50)
#82     JSModuleFile.getCode (package:dev_compiler/src/analyzer/module_compiler.dart:272:10)
#83     JSModuleFile.writeCodeSync (package:dev_compiler/src/analyzer/module_compiler.dart:304:16)
#84     _compile (package:dev_compiler/src/analyzer/command.dart:168:12)
#85     compile (package:dev_compiler/src/analyzer/command.dart:56:18)
#86     compile (package:dev_compiler/src/compiler/shared_command.dart:405:18)
#87     _CompilerWorker.performRequest.<anonymous closure> (file:///C:/b/s/w/ir/k/src/third_party/dart/pkg/dev_compiler/bin/dartdevc.dart:55:39)
#88     _rootRun (dart:async/zone.dart:1124:13)
#89     _CustomZone.run (dart:async/zone.dart:1021:19)
#90     _runZoned (dart:async/zone.dart:1516:10)
#91     runZoned (dart:async/zone.dart:1463:12)
#92     _CompilerWorker.performRequest (file:///C:/b/s/w/ir/k/src/third_party/dart/pkg/dev_compiler/bin/dartdevc.dart:55:24)
<asynchronous suspension>
#93     AsyncWorkerLoop.run.<anonymous closure> (package:bazel_worker/src/worker/async_worker_loop.dart:33:41)
#94     _rootRun (dart:async/zone.dart:1124:13)
#95     _CustomZone.run (dart:async/zone.dart:1021:19)
#96     _runZoned (dart:async/zone.dart:1516:10)
#97     runZoned (dart:async/zone.dart:1463:12)
#98     AsyncWorkerLoop.run (package:bazel_worker/src/worker/async_worker_loop.dart:33:26)
<asynchronous suspension>
#99     main (file:///C:/b/s/w/ir/k/src/third_party/dart/pkg/dev_compiler/bin/dartdevc.dart:28:57)
<asynchronous suspension>
#100    _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:296:32)
#101    _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:171:12)

```

[This](https://github.com/marmotini/sample_finance_app_3/tree/web) is the app I'm trying to implement on.

**Comment by marmotini** [comment]
Found the issue. After updating the dependency versions for build_runner & build_web_compilers it works. I think https://github.com/flutter/flutter_web/blob/master/docs/migration_guide.md pubspec.yaml section might need to be updated to include the right versions. Thanks.

**Comment by tvolkert** [comment]
Thanks @marmotini .  I'm going to close this issue - feel free to re-open if you think there's reason to keep it open.
