### ISSUE TITLE
 Android cannot catch Error behavior of single transaction

### ISSUE THREAD

**Issue by hisurga** [flutter/flutter#35529]
Android and iOS have different behavior of single transaction.  
I think Flutter for Android or cloud_firestore for Android can not handle the error correctly.

### e.g.1

throw in transaction.  
Of course, transaction will fail.

But Android had crash.

1. test code

```dart
await _db.runTransaction((Transaction tx) async {
  print('Transaction start');
  throw 'err';
}).then((value) {
  print('ok');
}).catchError((err) {
  print(err);
});
}
```

2. Result of Android Simulator

```I/flutter (11258): Transaction start
E/CloudFirestorePlugin(11258): java.lang.Exception: Do transaction failed.
E/CloudFirestorePlugin(11258): java.util.concurrent.ExecutionException: java.lang.Exception: Do transaction failed.
E/CloudFirestorePlugin(11258):  at com.google.android.gms.tasks.Tasks.zzb(Unknown Source:61)
E/CloudFirestorePlugin(11258):  at com.google.android.gms.tasks.Tasks.await(Unknown Source:33)
E/CloudFirestorePlugin(11258):  at io.flutter.plugins.firebase.cloudfirestore.CloudFirestorePlugin$4.apply(CloudFirestorePlugin.java:409)
E/CloudFirestorePlugin(11258):  at io.flutter.plugins.firebase.cloudfirestore.CloudFirestorePlugin$4.apply(CloudFirestorePlugin.java:361)
E/CloudFirestorePlugin(11258):  at com.google.firebase.firestore.FirebaseFirestore.lambda$runTransaction$1(com.google.firebase:firebase-firestore@@19.0.0:283)
E/CloudFirestorePlugin(11258):  at com.google.firebase.firestore.FirebaseFirestore$$Lambda$3.call(Unknown Source:6)
E/CloudFirestorePlugin(11258):  at com.google.android.gms.tasks.zzv.run(Unknown Source:2)
E/CloudFirestorePlugin(11258):  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
E/CloudFirestorePlugin(11258):  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
E/CloudFirestorePlugin(11258):  at java.lang.Thread.run(Thread.java:764)
E/CloudFirestorePlugin(11258): Caused by: java.lang.Exception: Do transaction failed.
E/CloudFirestorePlugin(11258):  at io.flutter.plugins.firebase.cloudfirestore.CloudFirestorePlugin$4$1$1.error(CloudFirestorePlugin.java:391)
E/CloudFirestorePlugin(11258):  at io.flutter.plugin.common.MethodChannel$IncomingResultHandler.reply(MethodChannel.java:181)
E/CloudFirestorePlugin(11258):  at io.flutter.embedding.engine.dart.DartMessenger.handlePlatformMessageResponse(DartMessenger.java:103)
E/CloudFirestorePlugin(11258):  at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessageResponse(FlutterJNI.java:228)
E/CloudFirestorePlugin(11258):  at android.os.MessageQueue.nativePollOnce(Native Method)
E/CloudFirestorePlugin(11258):  at android.os.MessageQueue.next(MessageQueue.java:325)
E/CloudFirestorePlugin(11258):  at android.os.Looper.loop(Looper.java:142)
E/CloudFirestorePlugin(11258):  at android.app.ActivityThread.main(ActivityThread.java:6494)
E/CloudFirestorePlugin(11258):  at java.lang.reflect.Method.invoke(Native Method)
E/CloudFirestorePlugin(11258):  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
E/CloudFirestorePlugin(11258):  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
I/flutter (11258): PlatformException(Error performing transaction, java.lang.Exception: Do transaction failed., null)
D/AndroidRuntime(11258): Shutting down VM
E/AndroidRuntime(11258): FATAL EXCEPTION: main
E/AndroidRuntime(11258): Process: com.example.flutter_firestore, PID: 11258
E/AndroidRuntime(11258): java.lang.IllegalStateException: Reply already submitted
E/AndroidRuntime(11258):    at io.flutter.embedding.engine.dart.DartMessenger$Reply.reply(DartMessenger.java:124)
E/AndroidRuntime(11258):    at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler$1.success(MethodChannel.java:204)
E/AndroidRuntime(11258):    at io.flutter.plugins.firebase.cloudfirestore.CloudFirestorePlugin$3.onComplete(CloudFirestorePlugin.java:425)
E/AndroidRuntime(11258):    at com.google.android.gms.tasks.zzj.run(Unknown Source:4)
E/AndroidRuntime(11258):    at android.os.Handler.handleCallback(Handler.java:790)
E/AndroidRuntime(11258):    at android.os.Handler.dispatchMessage(Handler.java:99)
E/AndroidRuntime(11258):    at android.os.Looper.loop(Looper.java:164)
E/AndroidRuntime(11258):    at android.app.ActivityThread.main(ActivityThread.java:6494)
E/AndroidRuntime(11258):    at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(11258):    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
E/AndroidRuntime(11258):    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
```

3. Result of iOS simulator

```
flutter: Transaction start
flutter: PlatformException(error, err, null)
```

### e.g.2

At first, test code get 'book1' doc.  
After that, test code don't write 'book1' doc.  
So, transaction will fail.

But, Android could not detect failure.

1. test code

```dart
final CollectionReference booksRef = _db.collection('/books');

await _db.runTransaction((Transaction tx) async {
  print('Transaction start');
  DocumentSnapshot book1Snapshot = await tx.get(booksRef.document('book1'));

  if (book1Snapshot.exists) {
    await tx.update(booksRef.document('book2'),
        <String, dynamic>{'title': book1Snapshot.data['title']});
  }
}).then((value) {
  print('ok');
}).catchError((err) {
  print(err);
});
```

2. Result of Android

```
I/flutter (11258): Transaction start
I/flutter (11258): Transaction start
I/flutter (11258): ok
```

3. Result of iOS

```
flutter: Transaction start
flutter: Transaction start
flutter: Transaction start
flutter: Transaction start
flutter: Transaction start
flutter: Transaction start
flutter: PlatformException(9, Transaction failed all retries.: Every document read in a transaction must also be written in that transaction., null)
```

## My environment
```
dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^0.4.0
  cloud_firestore: ^0.12.5+2
```

```
[✓] Flutter (Channel stable, v1.5.4-hotfix.2, on Mac OS X 10.14.5 18F132, locale ja-JP)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[✓] iOS toolchain - develop for iOS devices (Xcode 10.2.1)
[✓] Android Studio (version 3.4)
[!] VS Code (version 1.35.0)
    ✗ Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter
[✓] Connected device (2 available)
```

**Comment by jasonkaruza** [comment]
I have this issue as well.

**Comment by mpivchev** [comment]
I have the same issue. `java.lang.IllegalStateException: Reply already submitted` always gets thrown whenever Firestore throws the main exception.

**Comment by jasonkaruza** [comment]
I've noticed that I have an issue with 0.12.9 doing a batch commit, but 0.12.8 has the transaction problem for iOS. So it is definitely a versioning issue with the latest cloud_firestore.

**Comment by mk-dev-1** [comment]
Has anyone been able to identify this error more exactly? As this error does not seem to occur consistently, we unfortunately have shipped a version with this error to production, so we need a fix asap...

**Comment by BondarenkoStas** [comment]
@hisurga Can you provide your flutter doctor -v output?

**Comment by hisurga** [comment]
@BondarenkoStas 

sorry for late

This is doctor result when submitted the issue.  I know this is old version, but I did not try latest version.

```
  ╔════════════════════════════════════════════════════════════════════════════╗
  ║ A new version of Flutter is available!                                     ║
  ║                                                                            ║
  ║ To update to the latest version, run "flutter upgrade".                    ║
  ╚════════════════════════════════════════════════════════════════════════════╝


[✓] Flutter (Channel stable, v1.7.8+hotfix.3, on Mac OS X 10.14.5 18F132, locale ja-JP)
    • Flutter version 1.7.8+hotfix.3 at /Users/hisurga/Library/flutter
    • Framework revision b712a172f9 (3 months ago), 2019-07-09 13:14:38 -0700
    • Engine revision 54ad777fd2
    • Dart version 2.4.0

 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/hisurga/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 10.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.2.1, Build version 10E1001
    • CocoaPods version 1.7.0

[✓] iOS tools - develop for iOS devices
    • ios-deploy 1.9.4

[✓] Android Studio (version 3.4)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 36.1.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

[!] VS Code (version 1.37.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    ✗ Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[!] Connected device
    ! No devices available

! Doctor found issues in 2 categories.
```

**Comment by kroikie** [comment]
@hisurga

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/1220. Any further collaboration will be done there.
