### ISSUE TITLE
A problem occurred configuring project ':sqflite'.

### ISSUE THREAD

**Issue by netopaez97** [flutter/flutter#35532]
## Steps to Reproduce

I am trying to use sqflite package v. 1.0.0 in my iOS/android project. I tried to install this package and it went wrong in Android. I thought it could be due other packages installed in the app. However, I tested a simple new app with sqflite package v.1.0.0. and it went wrong too.

1. flutter create test_example
2. add sqflite: ^1.0.0 to pubspec.yaml file.
3. flutter run

And no more.

## Logs

Flutter run --verbose

```
iMac-de-Luis:text_example netopaez$ flutter run --verbose
[  +32 ms] executing: [/Users/netopaez/Documents/Programas/flutter/] git log -n 1
--pretty=format:%H
[  +40 ms] Exit code 0 from: git log -n 1 --pretty=format:%H
[        ] 7a4c33425ddd78c54aba07d86f3f9a4a0051769b
[        ] executing: [/Users/netopaez/Documents/Programas/flutter/] git describe
--match v*.*.* --first-parent --long --tags
[  +11 ms] Exit code 0 from: git describe --match v*.*.* --first-parent --long
--tags
[        ] v1.5.4-hotfix.2-0-g7a4c33425
[  +11 ms] executing: [/Users/netopaez/Documents/Programas/flutter/] git rev-parse
--abbrev-ref --symbolic @{u}
[   +9 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/stable
[        ] executing: [/Users/netopaez/Documents/Programas/flutter/] git ls-remote
--get-url origin
[   +8 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[  +50 ms] executing: [/Users/netopaez/Documents/Programas/flutter/] git rev-parse
--abbrev-ref HEAD
[  +10 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] stable
[ +188 ms] executing: /Users/netopaez/Library/Android/sdk/platform-tools/adb devices
-l
[   +9 ms] Exit code 0 from: /Users/netopaez/Library/Android/sdk/platform-tools/adb
devices -l
[        ] List of devices attached
           ZY323KJ97S             device usb:338690048X product:deen
           model:motorola_one device:deen_sprout transport_id:2
[   +8 ms] executing: idevice_id -h
[ +169 ms] executing: which ideviceinstaller
[   +5 ms] Exit code 0 from: which ideviceinstaller
[        ] /usr/local/bin/ideviceinstaller
[        ] executing: which iproxy
[   +3 ms] Exit code 0 from: which iproxy
[        ] /usr/local/bin/iproxy
[   +3 ms] /usr/bin/xcrun simctl list --json devices
[ +186 ms] More than one device connected; please specify a device with the '-d
<deviceId>'
                    flag, or use '-d all' to act on all devices.
[   +6 ms] /Users/netopaez/Library/Android/sdk/platform-tools/adb -s ZY323KJ97S
shell getprop
[  +62 ms] ro.hardware = qcom
[   +5 ms] motorola one                    • ZY323KJ97S
•
           android-arm64 • Android 9 (API 28)
[   +1 ms] iPad de Luis Ernesto Páez Ortiz •
b213df91972589fed7571df9e98504ae123185f3 • ios
           • iOS 12.3.1
[  +13 ms] "flutter run" took 672ms.
[        ] "flutter run" took 672ms.

<<<<<SINCE HERE IN RED>>>>

#0      throwToolExit (package:flutter_tools/src/base/common.dart:24:3)
#1      RunCommand.validateCommand
(package:flutter_tools/src/commands/run.dart:257:7)
<asynchronous suspension>
#2      FlutterCommand.verifyThenRunCommand
(package:flutter_tools/src/runner/flutter_command.dart:538:11)
<asynchronous suspension>
#3      FlutterCommand.run.<anonymous closure>
(package:flutter_tools/src/runner/flutter_command.dart:495:33)
<asynchronous suspension>
#4      AppContext.run.<anonymous closure>
(package:flutter_tools/src/base/context.dart:142:29)
<asynchronous suspension>
#5      _rootRun (dart:async/zone.dart:1124:13)
#6      _CustomZone.run (dart:async/zone.dart:1021:19)
#7      _runZoned (dart:async/zone.dart:1516:10)
#8      runZoned (dart:async/zone.dart:1463:12)
#9      AppContext.run (package:flutter_tools/src/base/context.dart:141:18)
<asynchronous suspension>
#10     FlutterCommand.run
(package:flutter_tools/src/runner/flutter_command.dart:486:20)
#11     CommandRunner.runCommand (package:args/command_runner.dart:196:27)
<asynchronous suspension>
#12     FlutterCommandRunner.runCommand.<anonymous closure>
(package:flutter_tools/src/runner/flutter_command_runner.dart:396:21)
<asynchronous suspension>
#13     AppContext.run.<anonymous closure>
(package:flutter_tools/src/base/context.dart:142:29)
<asynchronous suspension>
#14     _rootRun (dart:async/zone.dart:1124:13)
#15     _CustomZone.run (dart:async/zone.dart:1021:19)
#16     _runZoned (dart:async/zone.dart:1516:10)
#17     runZoned (dart:async/zone.dart:1463:12)
#18     AppContext.run (package:flutter_tools/src/base/context.dart:141:18)
<asynchronous suspension>
#19     FlutterCommandRunner.runCommand
(package:flutter_tools/src/runner/flutter_command_runner.dart:356:19)
<asynchronous suspension>
#20     CommandRunner.run.<anonymous closure>
(package:args/command_runner.dart:111:29)
#21     new Future.sync (dart:async/future.dart:224:31)
#22     CommandRunner.run (package:args/command_runner.dart:111:11)
#23     FlutterCommandRunner.run
(package:flutter_tools/src/runner/flutter_command_runner.dart:242:18)
#24     run.<anonymous closure> (package:flutter_tools/runner.dart:60:20)
<asynchronous suspension>
#25     AppContext.run.<anonymous closure>
(package:flutter_tools/src/base/context.dart:142:29)
<asynchronous suspension>
#26     _rootRun (dart:async/zone.dart:1124:13)
#27     _CustomZone.run (dart:async/zone.dart:1021:19)
#28     _runZoned (dart:async/zone.dart:1516:10)
#29     runZoned (dart:async/zone.dart:1463:12)
#30     AppContext.run (package:flutter_tools/src/base/context.dart:141:18)
<asynchronous suspension>
#31     runInContext (package:flutter_tools/src/context_runner.dart:50:24)
<asynchronous suspension>
#32     run (package:flutter_tools/runner.dart:51:10)
#33     main (package:flutter_tools/executable.dart:60:9)
<asynchronous suspension>
#34     main
(file:///b/s/w/ir/k/archive/flutter/packages/flutter_tools/bin/flutter_tools.dart:8:
3)
#35     _startIsolate.<anonymous closure>
(dart:isolate-patch/isolate_patch.dart:298:32)
#36     _RawReceivePortImpl._handleMessage
(dart:isolate-patch/isolate_patch.dart:171:12)
```

Flutter analyze

```
iMac-de-Luis:text_example netopaez$ flutter analyze
Analyzing text_example...                                               
No issues found! (ran in 5.2s)
```

Flutter doctor
```
iMac-de-Luis:text_example netopaez$ flutter analyze
Analyzing text_example...                                               
No issues found! (ran in 5.2s)
iMac-de-Luis:text_example netopaez$ flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, v1.5.4-hotfix.2, on Mac OS X 10.14.5 18F132, locale
    es-CO)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.0)
[✓] iOS toolchain - develop for iOS devices (Xcode 10.2.1)
[✓] Android Studio (version 3.4)
[✓] VS Code (version 1.35.1)
[✓] Connected device (2 available)

• No issues found!
```

But when I run >flutter run, the output show:
```
iMac-de-Luis:text_example netopaez$ flutter run -d ZY323KJ97S
Launching lib/main.dart on motorola one in debug mode...
Initializing gradle...                                              3,1s
Resolving dependencies...                                               
* Error running Gradle:
ProcessException: Process
"/Users/netopaez/Documents/Cerrejon/GIP/Proyectos/text_example/android/gradlew"
exited abnormally:

> Configure project :sqflite

Project evaluation failed including an error in afterEvaluate {}. Run with
--stacktrace for details of the afterEvaluate {} error.

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':sqflite'.
> Could not resolve all artifacts for configuration ':sqflite:classpath'.
   > Could not resolve com.android.tools.build:gradle:3.4.0.
     Required by:
         project :sqflite
      > Could not resolve com.android.tools.build:gradle:3.4.0.
         > Could not get resource
         'https://dl.google.com/dl/android/maven2/com/android/tools/build/gradle/3.4
         .0/gradle-3.4.0.pom'.
            > Could not GET
            'https://dl.google.com/dl/android/maven2/com/android/tools/build/gradle/
            3.4.0/gradle-3.4.0.pom'.
               > sun.security.validator.ValidatorException: PKIX path building
               failed: sun.security.provider.certpath.SunCertPathBuilderException:
               unable to find valid certification path to requested target

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug
option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 4s
  Command:
  /Users/netopaez/Documents/Cerrejon/GIP/Proyectos/text_example/android/gradlew
  app:properties


Please review your Gradle project setup in the android/ folder.
```

The IOS app runs good. 

## Gradle

android/build.gradle

```
buildscript {
    repositories {
        google()
        jcenter()
    }

    dependencies {
        classpath 'com.android.tools.build:gradle:3.2.1'
    }
}

allprojects {
    repositories {
        google()
        jcenter()
    }
}

rootProject.buildDir = '../build'
subprojects {
    project.buildDir = "${rootProject.buildDir}/${project.name}"
}
subprojects {
    project.evaluationDependsOn(':app')
}

task clean(type: Delete) {
    delete rootProject.buildDir
}
```

android/app/build.gradle

```
def localProperties = new Properties()
def localPropertiesFile = rootProject.file('local.properties')
if (localPropertiesFile.exists()) {
    localPropertiesFile.withReader('UTF-8') { reader ->
        localProperties.load(reader)
    }
}

def flutterRoot = localProperties.getProperty('flutter.sdk')
if (flutterRoot == null) {
    throw new GradleException("Flutter SDK not found. Define location with flutter.sdk in the local.properties file.")
}

def flutterVersionCode = localProperties.getProperty('flutter.versionCode')
if (flutterVersionCode == null) {
    flutterVersionCode = '1'
}

def flutterVersionName = localProperties.getProperty('flutter.versionName')
if (flutterVersionName == null) {
    flutterVersionName = '1.0'
}

apply plugin: 'com.android.application'
apply from: "$flutterRoot/packages/flutter_tools/gradle/flutter.gradle"

android {
    compileSdkVersion 28

    lintOptions {
        disable 'InvalidPackage'
    }

    defaultConfig {
        // TODO: Specify your own unique Application ID (https://developer.android.com/studio/build/application-id.html).
        applicationId "com.example.text_example"
        minSdkVersion 16
        targetSdkVersion 28
        versionCode flutterVersionCode.toInteger()
        versionName flutterVersionName
        testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"
    }

    buildTypes {
        release {
            // TODO: Add your own signing config for the release build.
            // Signing with the debug keys for now, so `flutter run --release` works.
            signingConfig signingConfigs.debug
        }
    }
}

flutter {
    source '../..'
}

dependencies {
    testImplementation 'junit:junit:4.12'
    androidTestImplementation 'com.android.support.test:runner:1.0.2'
    androidTestImplementation 'com.android.support.test.espresso:espresso-core:3.0.2'
}

```

**Comment by timrijckaert** [comment]
Same error here

**Comment by BondarenkoStas** [comment]
Thank you @timrijckaert ! @netopaez97 did you manage to solve the issue?

**Comment by netopaez97** [comment]
Hi Mr. Stanislav. The problem was the company where I was working had a restriction in network, then, the sqflite package couldn't being installed in a good way.

I could solve the problem connecting my computer to another network with no restrictions.

Thank you for reply!

**Comment by netopaez97** [comment]
Hi Mr. Stanislav. The problem was the company where I was working had a restriction in network, then, the sqflite package couldn't being installed in a good way.

I could solve the problem connecting my computer to another network with no restrictions.

Thank you for reply!

**Comment by rahmanrezaee** [comment]
run `flutter pub cache repair`
and `flutter clean`
Good luck
