### ISSUE TITLE
ExpansionTile throws a hard to grok error if key is not specified

### ISSUE THREAD

**Issue by mehmetf** [flutter/flutter#35539]
Internal: b/136556227

In the leafy app, there are several places where `ExpansionTile` is being used without a key. The documentation states that if the tile scrolls off screen, a key must be used. However, the assertion thrown in debug mode is very cryptic:

```
I/flutter (31757): ═════════════════════════════════════════════════════════════════
I/flutter (31757): 
I/flutter (31757): SEVERE: 2019-07-02 09:06:27.497352: ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞════════════════════════
I/flutter (31757): The following assertion was thrown building
I/flutter (31757): DefaultTextStyle(debugLabel: (englishLike body1
I/flutter (31757): 2014).merge(unknown), inherit: false, color: Color(0xdd000000),
I/flutter (31757): family: Roboto, size: 14.0, weight: 400, baseline: alphabetic,
I/flutter (31757): decoration: TextDecoration.none, softWrap: wrapping at box width,
I/flutter (31757): overflow: clip):
I/flutter (31757): type 'double' is not a subtype of type 'bool'
I/flutter (31757): 
I/flutter (31757): Either the assertion indicates an error in the framework itself,
I/flutter (31757): or we should provide substantially more information in this error
I/flutter (31757): message to help you determine and fix the underlying cause.
I/flutter (31757): In either case, please report this assertion by filing a bug on
I/flutter (31757): GitHub:
I/flutter (31757):   https://github.com/flutter/flutter/issues/new?template=BUG.md
I/flutter (31757): 
I/flutter (31757): When the exception was thrown, this was the stack:
I/flutter (31757): #0      _ExpansionTileState.initState (package:flutter/src/material/expansion_tile.dart:112:5)
I/flutter (31757): #1      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4033:58)
I/flutter (31757): #2      ComponentElement.mount (package:flutter/src/widgets/framework.dart:3902:5)
I/flutter (31757): #3      Element.inflateWidget (package:flutter/src/widgets/framework.dart:3084:14)
I/flutter (31757): #4      Element.updateChild (package:flutter/src/widgets/framework.dart:2887:12)
```

Crashes happen in release mode as well but the errors vary.

Always requiring key would be a breaking change so I am not sure what can be done here.

**Comment by shihaohong** [comment]
https://github.com/flutter/flutter/issues/10867 seems related to this issue

**Comment by shihaohong** [comment]
I can't seem to reproduce this error case. I tried the following: 
```
import 'package:flutter/material.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: MyHomePage(),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key key}) : super(key: key);

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: PageView(
        children: <Widget>[
          Center(
            child: ExpansionTile(
              title: Text('Expansion Tile 1'),
              children: <Widget>[
                Text('Hello 1!'),
              ],
            ),
          ),
          Center(
            child: ExpansionTile(
              title: Text('Expansion Tile 2'),
              children: <Widget>[
                Text('Hello 2!'),
              ],
            ),
          ),
          Center(
            child: ExpansionTile(
              title: Text('Expansion Tile 3'),
              children: <Widget>[
                Text('Hello 3!'),
              ],
            ),
          ),
        ],
      ),
    );
  }
}
```

I checked the internal bug and there isn't enough information there to get this error to show up.

**Comment by Hixie** [comment]
comments say it can't be reproduced
