### ISSUE TITLE
Could not find method veclasspathrsionName

### ISSUE THREAD

**Issue by rashcms** [flutter/flutter#35542]
after updating flutter and android studio I cannot run my flutter application

Error : 
**Could not find method veclasspathrsionName() for arguments**

**flutter run output :** 
```
flutter run
Launching lib/main.dart on LG in debug mode...
Initializing gradle...                                              2.9s
Resolving dependencies...                                               
* Error running Gradle:
ProcessException: Process "/Users/user/Desktop/projects/myproject/android/gradlew" exited abnormally:

FAILURE: Build failed with an exception.

* Where:
Build file '/Users/user/Desktop/projects/myproject/android/app/build.gradle' line: 41

* What went wrong:
A problem occurred evaluating project ':app'.
> Could not find method veclasspathrsionName() for arguments [1.0.0] on DefaultConfig_Decorated{name=main, dimension=null, minSdkVersion=DefaultApiVersion{mApiLevel=16,
mCodename='null'}, targetSdkVersion=DefaultApiVersion{mApiLevel=27, mCodename='null'}, renderscriptTargetApi=null, renderscriptSupportModeEnabled=null,
renderscriptSupportModeBlasEnabled=null, renderscriptNdkModeEnabled=null, versionCode=1, versionName=null, applicationId=org.myname.myname, testApplicationId=null,
testInstrumentationRunner=null, testInstrumentationRunnerArguments={}, testHandleProfiling=null, testFunctionalTest=null, signingConfig=null, resConfig=null,
mBuildConfigFields={}, mResValues={}, mProguardFiles=[], mConsumerProguardFiles=[], mManifestPlaceholders={}, mWearAppUnbundled=null} of type
com.android.build.gradle.internal.dsl.DefaultConfig.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1s
  Command: /Users/user/Desktop/projects/myproject/android/gradlew app:properties


Please review your Gradle project setup in the android/ folder.

```
**flutter run --verbose output :** 

```
flutter run --verbose
[  +60 ms] executing: [/Users/user/Documents/flutter/] git log -n 1 --pretty=format:%H
[  +60 ms] Exit code 0 from: git log -n 1 --pretty=format:%H
[   +1 ms] 7a4c33425ddd78c54aba07d86f3f9a4a0051769b
[        ] executing: [/Users/user/Documents/flutter/] git describe --match v*.*.* --first-parent --long --tags
[  +18 ms] Exit code 0 from: git describe --match v*.*.* --first-parent --long --tags
[        ] v1.5.4-hotfix.2-0-g7a4c33425
[  +19 ms] executing: [/Users/user/Documents/flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[  +14 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/stable
[        ] executing: [/Users/user/Documents/flutter/] git ls-remote --get-url origin
[  +13 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[ +100 ms] executing: [/Users/user/Documents/flutter/] git rev-parse --abbrev-ref HEAD
[  +19 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[   +1 ms] stable
[ +152 ms] executing: /Users/user/Library/Android/sdk/platform-tools/adb devices -l
[  +10 ms] Exit code 0 from: /Users/user/Library/Android/sdk/platform-tools/adb devices -l
[        ] List of devices attached
           LGc913b9a2         device usb:4195549184X product:h1_global_com model:LG device:h1 transport_id:3
[  +21 ms] executing: idevice_id -h
[  +35 ms] /Users/user/Library/Android/sdk/platform-tools/adb -s LGc913b9a2 shell getprop
[ +124 ms] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +6 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FuchsiaCacheArtifacts' is not required, skipping update.
[ +148 ms] Found plugin fluttertoast at /Users/user/Documents/flutter/.pub-cache/hosted/pub.dartlang.org/fluttertoast-3.1.0/
[  +19 ms] Found plugin sqflite at /Users/user/Documents/flutter/.pub-cache/hosted/pub.dartlang.org/sqflite-1.1.6+1/
[  +78 ms] Found plugin fluttertoast at /Users/user/Documents/flutter/.pub-cache/hosted/pub.dartlang.org/fluttertoast-3.1.0/
[  +15 ms] Found plugin sqflite at /Users/user/Documents/flutter/.pub-cache/hosted/pub.dartlang.org/sqflite-1.1.6+1/
[  +92 ms] ro.hardware = h1
[        ] ro.build.characteristics = default
[  +75 ms] Launching lib/main.dart on LG in debug mode...
[  +26 ms] Initializing gradle...
[  +11 ms] Using gradle from /Users/user/Desktop/projects/myproject/android/gradlew.
[+1567 ms] executing: /usr/bin/defaults read /Applications/Android Studio.app/Contents/Info
[  +40 ms] Exit code 0 from: /usr/bin/defaults read /Applications/Android Studio.app/Contents/Info
[        ] {
               CFBundleDevelopmentRegion = English;
               CFBundleDocumentTypes =     (
                           {
                       CFBundleTypeExtensions =             (
                           ipr
                       );
                       CFBundleTypeIconFile = "studio.icns";
                       CFBundleTypeName = "Android Studio Project File";
                       CFBundleTypeRole = Editor;
                   },
                           {
                       CFBundleTypeExtensions =             (
                           "*"
                       );
                       CFBundleTypeName = "All documents";
                       CFBundleTypeOSTypes =             (
                           "****"
                       );
                       CFBundleTypeRole = Editor;
                       LSTypeIsPackage = 0;
                   }
               );
               CFBundleExecutable = studio;
               CFBundleGetInfoString = "Android Studio 3.4, build AI-183.6156.11.34.5522156. Copyright JetBrains s.r.o., (c) 2000-2019";
               CFBundleIconFile = "studio.icns";
               CFBundleIdentifier = "com.google.android.studio";
               CFBundleInfoDictionaryVersion = "6.0";
               CFBundleName = "Android Studio";
               CFBundlePackageType = APPL;
               CFBundleShortVersionString = "3.4";
               CFBundleSignature = "????";
               CFBundleURLTypes =     (
                           {
                       CFBundleTypeRole = Editor;
                       CFBundleURLName = Stacktrace;
                       CFBundleURLSchemes =             (
                           idea
                       );
                   }
               );
               CFBundleVersion = "AI-183.6156.11.34.5522156";
               JVMOptions =     {
                   ClassPath =
                   "$APP_PACKAGE/Contents/lib/bootstrap.jar:$APP_PACKAGE/Contents/lib/extensions.jar:$APP_PACKAGE/Contents/lib/util.jar:$APP_PACKAGE/Contents/lib/jdom.jar:$AP
                   P_PACKAGE/Contents/lib/log4j.jar:$APP_PACKAGE/Contents/lib/trove4j.jar:$APP_PACKAGE/Contents/lib/jna.jar";
                   JVMVersion = "1.8*,1.8+";
                   MainClass = "com.intellij.idea.Main";
                   Properties =         {
                       "idea.executable" = studio;
                       "idea.home.path" = "$APP_PACKAGE/Contents";
                       "idea.java.redist" = Bundled;
                       "idea.paths.selector" = "AndroidStudio3.4";
                       "idea.platform.prefix" = AndroidStudio;
                   };
                   WorkingDirectory = "$APP_PACKAGE/Contents/bin";
               };
               LSApplicationCategoryType = "public.app-category.developer-tools";
               LSArchitecturePriority =     (
                   "x86_64"
               );
               LSMinimumSystemVersion = "10.8";
               LSRequiresNativeExecution = YES;
               NSHighResolutionCapable = 1;
               NSSupportsAutomaticGraphicsSwitching = 1;
           }
[  +20 ms] executing: /usr/bin/defaults read /Applications/Android Studio.app/Contents/Info CFBundleShortVersionString
[  +43 ms] Exit code 0 from: /usr/bin/defaults read /Applications/Android Studio.app/Contents/Info CFBundleShortVersionString
[        ] 3.4
[ +115 ms] executing: /Users/user/Desktop/projects/myproject/android/gradlew -v
[+1095 ms] 
                    ------------------------------------------------------------
                    Gradle 4.10.2
                    ------------------------------------------------------------

                    Build time:   2018-09-19 18:10:15 UTC
                    Revision:     b4d8d5d170bb4ba516e88d7fe5647e2323d791dd

                    Kotlin DSL:   1.0-rc-6
                    Kotlin:       1.2.61
                    Groovy:       2.4.15
                    Ant:          Apache Ant(TM) version 1.9.11 compiled on March 23 2018
                    JVM:          1.8.0_152-release (JetBrains s.r.o 25.152-b01)
                    OS:           Mac OS X 10.13.6 x86_64
[  +25 ms] Initializing gradle... (completed in 2.9s)
[   +1 ms] Resolving dependencies...
[   +1 ms] executing: [/Users/user/Desktop/projects/myproject/android/] /Users/user/Desktop/projects/myproject/android/gradlew app:properties
[+1244 ms] 
                    FAILURE: Build failed with an exception.

                    * Where:
                    Build file '/Users/user/Desktop/projects/myproject/android/app/build.gradle' line: 41

                    * What went wrong:
                    A problem occurred evaluating project ':app'.
                    > Could not find method veclasspathrsionName() for arguments [1.0.0] on DefaultConfig_Decorated{name=main, dimension=null,
                    minSdkVersion=DefaultApiVersion{mApiLevel=16, mCodename='null'}, targetSdkVersion=DefaultApiVersion{mApiLevel=27, mCodename='null'},
                    renderscriptTargetApi=null, renderscriptSupportModeEnabled=null, renderscriptSupportModeBlasEnabled=null, renderscriptNdkModeEnabled=null, versionCode=1,
                    versionName=null, applicationId=org.myname.myname, testApplicationId=null, testInstrumentationRunner=null, testInstrumentationRunnerArguments={},
                    testHandleProfiling=null, testFunctionalTest=null, signingConfig=null, resConfig=null, mBuildConfigFields={}, mResValues={}, mProguardFiles=[],
                    mConsumerProguardFiles=[], mManifestPlaceholders={}, mWearAppUnbundled=null} of type com.android.build.gradle.internal.dsl.DefaultConfig.

                    * Try:
                    Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

                    * Get more help at https://help.gradle.org

                    BUILD FAILED in 1s
[   +8 ms] Resolving dependencies... (completed in 1.3s)
[   +5 ms] * Error running Gradle:
           ProcessException: Process "/Users/user/Desktop/projects/myproject/android/gradlew" exited abnormally:
           
           FAILURE: Build failed with an exception.
           
           * Where:
           Build file '/Users/user/Desktop/projects/myproject/android/app/build.gradle' line: 41
           
           * What went wrong:
           A problem occurred evaluating project ':app'.
           > Could not find method veclasspathrsionName() for arguments [1.0.0] on DefaultConfig_Decorated{name=main, dimension=null,
minSdkVersion=DefaultApiVersion{mApiLevel=16,
           mCodename='null'}, targetSdkVersion=DefaultApiVersion{mApiLevel=27, mCodename='null'}, renderscriptTargetApi=null, renderscriptSupportModeEnabled=null,
           renderscriptSupportModeBlasEnabled=null, renderscriptNdkModeEnabled=null, versionCode=1, versionName=null, applicationId=org.myname.myname, testApplicationId=null,
           testInstrumentationRunner=null, testInstrumentationRunnerArguments={}, testHandleProfiling=null, testFunctionalTest=null, signingConfig=null, resConfig=null,
           mBuildConfigFields={}, mResValues={}, mProguardFiles=[], mConsumerProguardFiles=[], mManifestPlaceholders={}, mWearAppUnbundled=null} of type
           com.android.build.gradle.internal.dsl.DefaultConfig.
           
           * Try:
           Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
           
           * Get more help at https://help.gradle.org
           
           BUILD FAILED in 1s
             Command: /Users/user/Desktop/projects/myproject/android/gradlew app:properties
           
[  +12 ms] "flutter run" took 5,033ms.
[        ] "flutter run" took 5,033ms.
Please review your Gradle project setup in the android/ folder.

#0      throwToolExit (package:flutter_tools/src/base/common.dart:24:3)
#1      _readGradleProject (package:flutter_tools/src/android/gradle.dart:158:7)
<asynchronous suspension>
#2      _gradleProject (package:flutter_tools/src/android/gradle.dart:111:34)
<asynchronous suspension>
#3      getGradleAppOut (package:flutter_tools/src/android/gradle.dart:105:29)
<asynchronous suspension>
#4      AndroidApk.fromAndroidProject (package:flutter_tools/src/application_package.dart:154:23)
<asynchronous suspension>
#5      ApplicationPackageFactory.getPackageForPlatform (package:flutter_tools/src/application_package.dart:46:32)
<asynchronous suspension>
#6      FlutterDevice.runHot (package:flutter_tools/src/resident_runner.dart:345:56)
<asynchronous suspension>
#7      HotRunner.run (package:flutter_tools/src/run_hot.dart:253:39)
<asynchronous suspension>
#8      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:428:37)
<asynchronous suspension>
#9      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:559:18)
#10     _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:77:64)
#11     _rootRunUnary (dart:async/zone.dart:1132:38)
#12     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#13     _FutureListener.handleValue (dart:async/future_impl.dart:126:18)
#14     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:639:45)
#15     Future._propagateToListeners (dart:async/future_impl.dart:668:32)
#16     Future._complete (dart:async/future_impl.dart:473:7)
#17     _SyncCompleter.complete (dart:async/future_impl.dart:51:12)
#18     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:28:18)
#19     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:294:13)
#20     RunCommand.usageValues (package:flutter_tools/src/commands/run.dart)
#21     _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:77:64)
#22     _rootRunUnary (dart:async/zone.dart:1132:38)
#23     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#24     _FutureListener.handleValue (dart:async/future_impl.dart:126:18)
#25     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:639:45)
#26     Future._propagateToListeners (dart:async/future_impl.dart:668:32)
#27     Future._complete (dart:async/future_impl.dart:473:7)
#28     _SyncCompleter.complete (dart:async/future_impl.dart:51:12)
#29     _AsyncAwaitCompleter.complete.<anonymous closure> (dart:async-patch/async_patch.dart:33:20)
#30     _rootRun (dart:async/zone.dart:1124:13)
#31     _CustomZone.run (dart:async/zone.dart:1021:19)
#32     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:947:23)
#33     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#34     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#35     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:115:13)
#36     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:5)

```

**Comment by BondarenkoStas** [comment]
@rashcms did you manage to solve the issue? Do you experience it while using current flutter stable?

**Comment by iapicca** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
  
Thanks for your contribution.
