### ISSUE TITLE
[image_picker] Plugin crash while picking image

### ISSUE THREAD

**Issue by AmolGangadhare** [flutter/flutter#35632]
## Steps to Reproduce
1. Call `var image = await ImagePicker.pickImage(source: ImageSource.gallery);`.
2. Select a file manager or other apps.
3. Select pictures/images and select the image.
Also, sometimes it crashed while selecting an image from google photos.

## Logs

```
[+14795 ms] E/CursorWindow(19732): Failed to read row 0, column 0 from a CursorWindow which has 1 rows, 0 columns.
[   +2 ms] D/AndroidRuntime(19732): Shutting down VM
[   +6 ms] E/AndroidRuntime(19732): FATAL EXCEPTION: main
[        ] E/AndroidRuntime(19732): Process: com.poc_app, PID: 19732
[        ] E/AndroidRuntime(19732): java.lang.RuntimeException: Failure delivering result ResultInfo{who=null,
request=2342, result=-1, data=Intent {
dat=content://com.lenovo.FileBrowser.FileProvider/root_path/storage/emulated/0/Pictures/Screenshots/Screenshot_201
90704-162625.png flg=0x3 }} to activity {com.poc_app/com.poc_app.MainActivity}:
java.lang.IllegalStateException: Couldn't read row 0, col 0 from CursorWindow.  Make sure the Cursor is
initialized correctly before accessing data from it.
[   +1 ms] E/AndroidRuntime(19732): 	at android.app.ActivityThread.deliverResults(ActivityThread.java:4382)
[        ] E/AndroidRuntime(19732): 	at android.app.ActivityThread.handleSendResult(ActivityThread.java:4426)
[        ] E/AndroidRuntime(19732): 	at android.app.ActivityThread.-wrap20(Unknown Source:0)
[        ] E/AndroidRuntime(19732): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1685)
[        ] E/AndroidRuntime(19732): 	at android.os.Handler.dispatchMessage(Handler.java:106)
[        ] E/AndroidRuntime(19732): 	at android.os.Looper.loop(Looper.java:164)
[        ] E/AndroidRuntime(19732): 	at android.app.ActivityThread.main(ActivityThread.java:6626)
[        ] E/AndroidRuntime(19732): 	at java.lang.reflect.Method.invoke(Native Method)
[        ] E/AndroidRuntime(19732): 	at
com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
[        ] E/AndroidRuntime(19732): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:811)
[        ] E/AndroidRuntime(19732): Caused by: java.lang.IllegalStateException: Couldn't read row 0, col 0 from
CursorWindow.  Make sure the Cursor is initialized correctly before accessing data from it.
[        ] E/AndroidRuntime(19732): 	at android.database.CursorWindow.nativeGetString(Native Method)
[        ] E/AndroidRuntime(19732): 	at android.database.CursorWindow.getString(CursorWindow.java:438)
[        ] E/AndroidRuntime(19732): 	at
android.database.AbstractWindowedCursor.getString(AbstractWindowedCursor.java:51)
[        ] E/AndroidRuntime(19732): 	at android.database.CursorWrapper.getString(CursorWrapper.java:137)
[        ] E/AndroidRuntime(19732): 	at
io.flutter.plugins.imagepicker.FileUtils.getImageExtension(FileUtils.java:182)
[        ] E/AndroidRuntime(19732): 	at
io.flutter.plugins.imagepicker.FileUtils.getPathFromRemoteUri(FileUtils.java:144)
[        ] E/AndroidRuntime(19732): 	at io.flutter.plugins.imagepicker.FileUtils.getPathFromUri(FileUtils.java:44)
[        ] E/AndroidRuntime(19732): 	at
io.flutter.plugins.imagepicker.ImagePickerDelegate.handleChooseImageResult(ImagePickerDelegate.java:441)
[        ] E/AndroidRuntime(19732): 	at
io.flutter.plugins.imagepicker.ImagePickerDelegate.onActivityResult(ImagePickerDelegate.java:421)
[        ] E/AndroidRuntime(19732): 	at
io.flutter.app.FlutterPluginRegistry.onActivityResult(FlutterPluginRegistry.java:222)
[        ] E/AndroidRuntime(19732): 	at
io.flutter.app.FlutterActivityDelegate.onActivityResult(FlutterActivityDelegate.java:142)
[        ] E/AndroidRuntime(19732): 	at io.flutter.app.FlutterActivity.onActivityResult(FlutterActivity.java:142)
[        ] E/AndroidRuntime(19732): 	at android.app.Activity.dispatchActivityResult(Activity.java:7305)
[        ] E/AndroidRuntime(19732): 	at android.app.ActivityThread.deliverResults(ActivityThread.java:4378)
[        ] E/AndroidRuntime(19732): 	... 9 more
```

```
[✓] Flutter (Channel stable, v1.5.4-hotfix.2, on Mac OS X 10.14.5 18F132, locale en-IN)
    • Flutter version 1.5.4-hotfix.2 at /Volumes/MyData/Flutter_SDK/flutter
    • Framework revision 7a4c33425d (10 weeks ago), 2019-04-29 11:05:24 -0700
    • Engine revision 52c7a1e849
    • Dart version 2.3.0 (build 2.3.0-dev.0.5 a1668566e5)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.0-rc1)
    • Android SDK at /Users/admin/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.0-rc1
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.2.1, Build version 10E1001
    • ios-deploy 1.9.4
    • CocoaPods version 1.7.1

[✓] Android Studio (version 3.4)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 37.0.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

[✓] VS Code (version 1.35.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.1.0

[✓] Connected device (1 available)
    • Moto G 5 Plus • ZY22433CCB • android-arm • Android 8.1.0 (API 27)

• No issues found!
```

![image](https://user-images.githubusercontent.com/33967327/60717171-c3023000-9f3e-11e9-82ea-c2dde206a8b9.png)

**Comment by xiaobeiy** [comment]
I also encountered such problems on some devices of Huawei and Samsung. Looking forward to the solution of this problem.
