### ISSUE TITLE
Trying to make the social media icons clickable but not working

### ISSUE THREAD

**Issue by sourabh99967780** [flutter/flutter#35653]
```
import 'package:flutter/material.dart';
import 'package:font_awesome_flutter/font_awesome_flutter.dart';
import 'package:url_launcher/url_launcher.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    Widget titleSection = Container(
      padding: const EdgeInsets.all(32),
      child: Row(
        children: <Widget>[
          Expanded(
            child: Column(
              crossAxisAlignment: CrossAxisAlignment.start,
              children: [
                Container(
                  padding: const EdgeInsets.only(bottom: 0),
                  child: Text(
                    'Sourabh Kumar',
                    style: TextStyle(
                      fontWeight: FontWeight.bold,
                      fontSize: 18,
                    ),
                  ),
                ),
                Text(
                  'Machine Learning Developer and UI Designer',
                  style: TextStyle(
                    color: Colors.grey[500],
                  ),
                  softWrap: true,
                ),
              ],
            ),
          ),
          Icon(
            Icons.call,
            color: Colors.greenAccent,
            size: 35,
          ),
        ],
      ),
    );

    Column _buildButtonColumn(Color color, IconData icon, String label, String url) {
      return Column(
        mainAxisSize: MainAxisSize.min,
        mainAxisAlignment: MainAxisAlignment.center,
        children: [
          IconButton(icon: Icon(icon, color: color), onPressed: _launchURL(url)),
          Container(
            margin: const EdgeInsets.only(top: 8),
            child: Text(
              label,
              style: TextStyle(
                fontSize: 12,
                fontWeight: FontWeight.w400,
                color: color,
              ),
            ),
          ),
        ],
      );
    }

    Color color = Theme.of(context).primaryColor;
    Widget buttonSection = Container(
      child: Row(
        mainAxisAlignment: MainAxisAlignment.spaceEvenly,
        children: <Widget>[
          _buildButtonColumn(color, FontAwesomeIcons.linkedin, 'Linkedin', 'https://www.linkedin.com/in/sourabh-kumar-08987560/'),
          _buildButtonColumn(color, FontAwesomeIcons.facebook, 'Facebook', 'https://www.facebook.com/hellodoodsourabh'),
          _buildButtonColumn(color, FontAwesomeIcons.instagram, 'Instagram', 'https://www.instagram.com/prophet.code/?hl=en'),
          _buildButtonColumn(color, FontAwesomeIcons.github, "Github", 'https://github.com/sourabh99967780')
        ],
      ),
    );

    Widget textSection = Container(
      padding: const EdgeInsets.all(32),
      child: Column(
      crossAxisAlignment: CrossAxisAlignment.start,
        children: <Widget>[
          Text('About Me',
            style: TextStyle(
              fontSize: 20,
              fontWeight: FontWeight.bold,
            ),
          ),
          Divider(color: Colors.grey, height: 3),
          Padding(
            padding: const EdgeInsets.all(8),
          ),
          Text('Machine Learning Developer and Data Science Enthusiast. Proficient at operating Linux and its file system and some other open source tools. I can also make website’s front-end using HTML, JS and CSS and operate the back-end database.'
              'Apart from the technical stuff, I am also a experienced graphic Designer and learning MoGraphs.', softWrap: true),
        ],
      ),
    );

    return MaterialApp (
      title: "Profile Page",
      home: Scaffold(
        appBar: AppBar(
          title: Text('My Profile'),
          backgroundColor: Colors.blueAccent,
        ),
        body: ListView(
            children: [
              Image.asset(
                'assets/images/image_copy.jpeg',
                width: 600,
                height: 290,
                fit: BoxFit.cover,
        ),
              titleSection,
              buttonSection,
              textSection,
            ],
        ),
      ),
    );
  }
}

_launchURL(String url) async {
  launch(url);
}
```

Issue:
```
Performing hot reload...
Syncing files to device Android SDK built for x86...
I/flutter ( 4202): ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
I/flutter ( 4202): The following assertion was thrown building MyApp(dirty):
I/flutter ( 4202): type 'Future<dynamic>' is not a subtype of type '() => void'
I/flutter ( 4202): 
I/flutter ( 4202): Either the assertion indicates an error in the framework itself, or we should provide substantially
I/flutter ( 4202): more information in this error message to help you determine and fix the underlying cause.
I/flutter ( 4202): In either case, please report this assertion by filing a bug on GitHub:
I/flutter ( 4202):   https://github.com/flutter/flutter/issues/new?template=BUG.md
I/flutter ( 4202): 
I/flutter ( 4202): When the exception was thrown, this was the stack:
I/flutter ( 4202): #0      MyApp.build._buildButtonColumn (package:first_layout/main.dart:52:65)
I/flutter ( 4202): #1      MyApp.build (package:first_layout/main.dart:73:29)
I/flutter ( 4202): #2      StatelessElement.build (package:flutter/src/widgets/framework.dart:3789:28)
I/flutter ( 4202): #3      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3739:15)
I/flutter ( 4202): #4      Element.rebuild (package:flutter/src/widgets/framework.dart:3565:5)
I/flutter ( 4202): #5      BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2278:33)
I/flutter ( 4202): #6      _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding&WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:700:20)
I/flutter ( 4202): #7      _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:286:5)
I/flutter ( 4202): #8      _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1012:15)
I/flutter ( 4202): #9      _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:952:9)
I/flutter ( 4202): #10     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.scheduleWarmUpFrame.<anonymous closure> (package:flutter/src/scheduler/binding.dart:773:7)
I/flutter ( 4202): #12     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:382:19)
I/flutter ( 4202): #13     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:416:5)
I/flutter ( 4202): #14     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:171:12)
I/flutter ( 4202): (elided one frame from package dart:async-patch)
I/flutter ( 4202): ════════════════════════════════════════════════════════════════════════════════════════════════════
Reloaded 1 of 443 libraries in 250ms.
E/flutter ( 4202): [ERROR:flutter/shell/common/shell.cc(184)] Dart Error: Unhandled exception:
E/flutter ( 4202): MissingPluginException(No implementation found for method launch on channel plugins.flutter.io/url_launcher)
E/flutter ( 4202): #0      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:300:7)
E/flutter ( 4202): <asynchronous suspension>
E/flutter ( 4202): #1      launch (package:url_launcher/url_launcher.dart:82:38)
E/flutter ( 4202): <asynchronous suspension>
E/flutter ( 4202): #2      _launchURL (package:first_layout/main.dart:128:3)
E/flutter ( 4202): <asynchronous suspension>
E/flutter ( 4202): #3      MyApp.build._buildButtonColumn (package:first_layout/main.dart:52:65)
E/flutter ( 4202): #4      MyApp.build (package:first_layout/main.dart:73:29)
E/flutter ( 4202): #5      StatelessElement.build (package:flutter/src/widgets/framework.dart:3789:28)
E/flutter ( 4202): #6      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3739:15)
E/flutter ( 4202): #7      Element.rebuild (package:flutter/src/widgets/framework.dart:3565:5)
E/flutter ( 4202): #8      BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2278:33)
E/flutter ( 4202): #9      _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding&WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:700:20)
E/flutter ( 4202): #10     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:286:5)
E/flutter ( 4202): #11     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1012:15)
E/flutter ( 4202): #12     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:952:9)
E/flutter ( 4202): #13     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.scheduleWarmUpFrame.<anonymous closure> (package:flutter/src/scheduler/binding.dart:773:7)
E/flutter ( 4202): #14     Timer._createTimer.<anonymous closure> (dart:async-patch/timer_patch.dart:21:15)
E/flutter ( 4202): #15     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:382:19)
E/flutter ( 4202): #16     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:416:5)
E/flutter ( 4202): #17     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:171:12)
```
![Screenshot (15)](https://user-images.githubusercontent.com/37808636/60744321-0b4b3d80-9f93-11e9-9518-0506f61b9110.png)

**Comment by msal4** [comment]
The callback function `_launchURL` must not be `async` because IconButton expects it to be `void`
remove the async keyword
```dart
// ...
_launchURL(String url) => launch(url)
```

**Comment by shihaohong** [comment]
Seems like the suggestion provided by @msal4 makes sense, so I'll close this issue. Feel free to reopen if you feel like your problem was not addressed.

**Comment by camillo777** [comment]
See here:

https://stackoverflow.com/questions/50422167/flutter-can-i-pass-arguments-to-a-function-defined-in-an-onpress-event-on-a-but

So actually we're not passing a function itself (recall that everything is an object in Dart, even a function) to onPressed property, we create an anonymous function which calls our function. The same as:

```
new RaisedButton(
          onPressed: () => calculate(1, 100),
          ...
    ),
```

or

`onPressed: () { calculate(1,100);}`
