### ISSUE TITLE
Text widget assert statement not showing location of error

### ISSUE THREAD

**Issue by redayoub47** [flutter/flutter#35666]
In the error log I want to know exactly which line the error occurred on to fix the line in the

**Comment by shihaohong** [comment]
Hi, the stack trace should reveal the lines for which an error occurs. Is there a particular instance or use case where you are not receiving the line numbers?

**Comment by redayoub47** [comment]
for example this 
`class TodoListView extends StatefulWidget {
    static const routeName ="/todo_list_view";
    TodoListView({Key key, this.title}) : super(key: key);

    final String title;

    @override
   _TodoListViewState createState() => _TodoListViewState();
}
class _TodoListViewState extends State<TodoListView> {

    final TodoList list=ModalRoute.of().settings.arguments;

    @override
    Widget build(BuildContext context) {

        return Scaffold(
            appBar: AppBar(
               title: Text(widget.title),
            ),//appBar
            body: Text(list.title),

        );//Scaffold
  }
}`
when i ran the app i get an error 
`Failed assertion: line 241 pos 10: 'data != null` 
but it didn't specify which text widget is talking about and it turns out that i din't send the title

**Comment by shihaohong** [comment]
Could you share the entire stack trace, as well as a reproducible sample? The code block you shared does not have enough context for me to try it on another machine.

**Comment by redayoub47** [comment]
I'm Using SDK 1.5.4-hotfix.2
here's page code :
```
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key key, this.title}) : super(key: key);

  final String title;

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  int _counter = 0;

  void _incrementCounter() {
    setState(() {
      _counter++;
    });
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(null),
      ),
      body: Row(
        children: <Widget>[Text(null)],
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: _incrementCounter,
        tooltip: 'Increment',
        child: Icon(Icons.add),
      ),
    );
  }
}

```
and the the runtime exception i got

```
I/flutter ( 3472): ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
I/flutter ( 3472): The following assertion was thrown building MyHomePage(dirty, state: _MyHomePageState#b721d):
I/flutter ( 3472): A non-null String must be provided to a Text widget.
I/flutter ( 3472): 'package:flutter/src/widgets/text.dart': Failed assertion: line 241 pos 10: 'data != null'
I/flutter ( 3472): Either the assertion indicates an error in the framework itself, or we should provide substantially
I/flutter ( 3472): more information in this error message to help you determine and fix the underlying cause.
I/flutter ( 3472): In either case, please report this assertion by filing a bug on GitHub:
I/flutter ( 3472):   https://github.com/flutter/flutter/issues/new?template=BUG.md
I/flutter ( 3472): When the exception was thrown, this was the stack:
I/flutter ( 3472): #2      new Text (package:flutter/src/widgets/text.dart:241:10)
I/flutter ( 3472): #3      _MyHomePageState.build (package:hello_world/main.dart:40:16)
       ⣾I/flutter ( 3472): #4      StatefulElement.build (package:flutter/src/widgets/framework.dart:3825:27)
I/flutter ( 3472): #5      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3739:15)
I/flutter ( 3472): #6      Element.rebuild (package:flutter/src/widgets/framework.dart:3565:5)
I/flutter ( 3472): #7      StatefulElement.update (package:flutter/src/widgets/framework.dart:3894:5)
I/flutter ( 3472): #8      Element.updateChild (package:flutter/src/widgets/framework.dart:2753:15)
I/flutter ( 3472): #9      SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4883:14)
I/flutter ( 3472): #10     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:15)
I/flutter ( 3472): #11     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3750:16)
I/flutter ( 3472): #12     Element.rebuild (package:flutter/src/widgets/framework.dart:3565:5)
I/flutter ( 3472): #13     StatelessElement.update (package:flutter/src/widgets/framework.dart:3796:5)
I/flutter ( 3472): #14     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:15)
I/flutter ( 3472): #15     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4883:14)
I/flutter ( 3472): #16     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:15)
I/flutter ( 3472): #17     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4883:14)
I/flutter ( 3472): #18     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:15)
I/flutter ( 3472): #19     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4883:14)
I/flutter ( 3472): #20     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:15)
I/flutter ( 3472): #21     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4883:14)
I/flutter ( 3472): #22     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:15)
I/flutter ( 3472): #23     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3750:16)
I/flutter ( 3472): #24     Element.rebuild (package:flutter/src/widgets/framework.dart:3565:5)
I/flutter ( 3472): #25     StatefulElement.update (package:flutter/src/widgets/framework.dart:3894:5)
I/flutter ( 3472): #26     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:15)
I/flutter ( 3472): #27     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3750:16)
I/flutter ( 3472): #28     Element.rebuild (package:flutter/src/widgets/framework.dart:3565:5)
I/flutter ( 3472): #29     StatelessElement.update (package:flutter/src/widgets/framework.dart:3796:5)
I/flutter ( 3472): #30     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:15)
I/flutter ( 3472): #31     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3750:16)
I/flutter ( 3472): #32     Element.rebuild (package:flutter/src/widgets/framework.dart:3565:5)
I/flutter ( 3472): #33     StatefulElement.update (package:flutter/src/widgets/framework.dart:3894:5)
I/flutter ( 3472): #34     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:15)
I/flutter ( 3472): #35     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4883:14)
I/flutter ( 3472): #36     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:15)
I/flutter ( 3472): #37     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3750:16)
I/flutter ( 3472): #38     Element.rebuild (package:flutter/src/widgets/framework.dart:3565:5)
I/flutter ( 3472): #39     ProxyElement.update (package:flutter/src/widgets/framework.dart:4006:5)
I/flutter ( 3472): #40     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:15)
I/flutter ( 3472): #41     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4883:14)
I/flutter ( 3472): #42     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:15)
I/flutter ( 3472): #43     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3750:16)
I/flutter ( 3472): #44     Element.rebuild (package:flutter/src/widgets/framework.dart:3565:5)
I/flutter ( 3472): #45     StatefulElement.update (package:flutter/src/widgets/framework.dart:3894:5)
I/flutter ( 3472): #46     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:15)
I/flutter ( 3472): #47     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3750:16)
I/flutter ( 3472): #48     Element.rebuild (package:flutter/src/widgets/framework.dart:3565:5)
I/flutter ( 3472): #49     StatelessElement.update (package:flutter/src/widgets/framework.dart:3796:5)
I/flutter ( 3472): #50     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:15)
I/flutter ( 3472): #51     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4883:14)
I/flutter ( 3472): #52     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:15)
I/flutter ( 3472): #53     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3750:16)
I/flutter ( 3472): #54     Element.rebuild (package:flutter/src/widgets/framework.dart:3565:5)
I/flutter ( 3472): #55     ProxyElement.update (package:flutter/src/widgets/framework.dart:4006:5)
I/flutter ( 3472): #56     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:15)
I/flutter ( 3472): #57     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3750:16)
I/flutter ( 3472): #58     Element.rebuild (package:flutter/src/widgets/framework.dart:3565:5)
I/flutter ( 3472): #59     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2278:33)
I/flutter ( 3472): #60     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding&WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:700:20)
I/flutter ( 3472): #61     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:286:5)
I/flutter ( 3472): #62     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1012:15)
I/flutter ( 3472): #63     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:952:9)
I/flutter ( 3472): #64     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.scheduleWarmUpFrame.<anonymous closure> (package:flutter/src/scheduler/binding.dart:773:7)
I/flutter ( 3472): #66     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:382:19)
I/flutter ( 3472): #67     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:416:5)
I/flutter ( 3472): #68     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:171:12)
```

**Comment by shihaohong** [comment]
That makes sense. `I/flutter ( 3472): #3      ** _MyHomePageState.build (package:hello_world/main.dart:40:16)**` tells you which build method throws the exception, but not which `Text` widget within the build method.

**Comment by redayoub47** [comment]
Ok it seams i didn't see it
