### ISSUE TITLE
Crash report sender itself crashed

### ISSUE THREAD

**Issue by tgavara** [flutter/flutter#35682]
## command

`flutter --no-color run --machine --track-widget-creation --device-id=320850ce125e71d9 lib\main.dart`

## exception

_TypeError: type 'String' is not a subtype of type 'YamlList'

```
#0      _validateFlutter (package:flutter_tools/src/flutter_manifest.dart:354:28)
#1      _validate (package:flutter_tools/src/flutter_manifest.dart:312:9)
<asynchronous suspension>
#2      FlutterManifest._createFromYaml (package:flutter_tools/src/flutter_manifest.dart:45:40)
<asynchronous suspension>
#3      FlutterManifest.createFromString (package:flutter_tools/src/flutter_manifest.dart:40:12)
<asynchronous suspension>
#4      FlutterManifest.createFromPath (package:flutter_tools/src/flutter_manifest.dart:34:12)
<asynchronous suspension>
#5      FlutterProject._readManifest (package:flutter_tools/src/project.dart:153:60)
<asynchronous suspension>
#6      FlutterProject.fromDirectory (package:flutter_tools/src/project.dart:44:44)
<asynchronous suspension>
#7      FlutterProject.current (package:flutter_tools/src/project.dart:55:46)
#8      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:548:59)
<asynchronous suspension>
#9      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:495:33)
<asynchronous suspension>
#10     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:142:29)
<asynchronous suspension>
#11     _rootRun (dart:async/zone.dart:1124:13)
#12     _CustomZone.run (dart:async/zone.dart:1021:19)
#13     _runZoned (dart:async/zone.dart:1516:10)
#14     runZoned (dart:async/zone.dart:1463:12)
#15     AppContext.run (package:flutter_tools/src/base/context.dart:141:18)
<asynchronous suspension>
#16     FlutterCommand.run (package:flutter_tools/src/runner/flutter_command.dart:486:20)
#17     CommandRunner.runCommand (package:args/command_runner.dart:196:27)
<asynchronous suspension>
#18     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:396:21)
<asynchronous suspension>
#19     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:142:29)
<asynchronous suspension>
#20     _rootRun (dart:async/zone.dart:1124:13)
#21     _CustomZone.run (dart:async/zone.dart:1021:19)
#22     _runZoned (dart:async/zone.dart:1516:10)
#23     runZoned (dart:async/zone.dart:1463:12)
#24     AppContext.run (package:flutter_tools/src/base/context.dart:141:18)
<asynchronous suspension>
#25     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:356:19)
<asynchronous suspension>
#26     CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:111:29)
#27     new Future.sync (dart:async/future.dart:224:31)
#28     CommandRunner.run (package:args/command_runner.dart:111:11)
#29     FlutterCommandRunner.run (package:flutter_tools/src/runner/flutter_command_runner.dart:242:18)
#30     run.<anonymous closure> (package:flutter_tools/runner.dart:60:20)
<asynchronous suspension>
#31     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:142:29)
<asynchronous suspension>
#32     _rootRun (dart:async/zone.dart:1124:13)
#33     _CustomZone.run (dart:async/zone.dart:1021:19)
#34     _runZoned (dart:async/zone.dart:1516:10)
#35     runZoned (dart:async/zone.dart:1463:12)
#36     AppContext.run (package:flutter_tools/src/base/context.dart:141:18)
<asynchronous suspension>
#37     runInContext (package:flutter_tools/src/context_runner.dart:50:24)
<asynchronous suspension>
#38     run (package:flutter_tools/runner.dart:51:10)
#39     main (package:flutter_tools/executable.dart:60:9)
<asynchronous suspension>
#40     main (file:///C:/b/s/w/ir/k/archive/flutter/packages/flutter_tools/bin/flutter_tools.dart:8:3)
#41     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:298:32)
#42     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:171:12)
```

## flutter doctor

```
[✓] Flutter (Channel stable, v1.5.4-hotfix.2, on Microsoft Windows [Version 6.1.7601], locale en-US)
    • Flutter version 1.5.4-hotfix.2 at C:\flutter
    • Framework revision 7a4c33425d (10 weeks ago), 2019-04-29 11:05:24 -0700
    • Engine revision 52c7a1e849
    • Dart version 2.3.0 (build 2.3.0-dev.0.5 a1668566e5)

[!] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at C:\Users\trivikramg\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: C:\Program Files\Android\Android Studio1\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses

[!] Android Studio (version 3.1)
    • Android Studio at C:\Program Files\Android\Android Studio
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    ✗ Unable to find bundled Java version.
    • Try updating or re-installing Android Studio.

[✓] Android Studio (version 3.3)
    • Android Studio at C:\Program Files\Android\Android Studio1
    • Flutter plugin version 34.0.1
    • Dart plugin version 182.5215
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)

[!] IntelliJ IDEA Community Edition (version 2018.2)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2018.2.4
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.dev/intellij-setup/#installing-the-plugins

[✓] Connected device (1 available)
    • SM G900H • 320850ce125e71d9 • android-arm • Android 6.0.1 (API 23)

! Doctor found issues in 3 categories.
```

**Comment by janmoppel** [comment]
Hello @tgavara !

Did you manage to solve the issue? Does the problem still persist in the latest stable version?

**Comment by iapicca** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
  
Thanks for your contribution.
