### ISSUE TITLE
Building AOT snapshot in release mode (ios-release)...    Bad CPU type in executable      Dart snapshot generator failed with exit code 1 .  Building App.framework for arm64..

### ISSUE THREAD

**Issue by Suman085** [flutter/flutter#35701]
## Steps to Reproduce

1. ...i can build and run the app in my device.
2...`flutter build ios --release` throwing exceptions, and hence I cannot build archive for release.

## Logs

ProcessException: ProcessException: Process "xcrun" exited abnormally:
clang: error: no such file or directory: 'build/aot/arm64/snapshot_assembly.S'
clang: error: no input files
  Command: xcrun cc -arch arm64 -miphoneos-version-min=8.0 -c build/aot/arm64/snapshot_assembly.S -o build/aot/arm64/snapshot_assembly.o

```
#0      runCheckedAsync (package:flutter_tools/src/base/process.dart:255:5)
<asynchronous suspension>
#1      Xcode.cc (package:flutter_tools/src/ios/mac.dart:231:12)
#2      AOTSnapshotter._buildIosFramework (package:flutter_tools/src/base/build.dart:253:49)
<asynchronous suspension>
#3      AOTSnapshotter.build (package:flutter_tools/src/base/build.dart:225:38)
<asynchronous suspension>
#4      BuildAotCommand.runCommand.<anonymous closure> (package:flutter_tools/src/commands/build_aot.dart:112:44)
#5      __InternalLinkedHashMap&_HashVMBase&MapMixin&_LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:367:8)
#6      BuildAotCommand.runCommand (package:flutter_tools/src/commands/build_aot.dart:111:19)
#7      _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:77:64)
#8      _rootRunUnary (dart:async/zone.dart:1132:38)
#9      _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#10     _FutureListener.handleValue (dart:async/future_impl.dart:126:18)
#11     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:639:45)
#12     Future._propagateToListeners (dart:async/future_impl.dart:668:32)
#13     Future._complete (dart:async/future_impl.dart:473:7)
#14     _SyncCompleter.complete (dart:async/future_impl.dart:51:12)
#15     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:28:18)
#16     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:294:13)
#17     AOTSnapshotter.compileKernel (package:flutter_tools/src/base/build.dart)
#18     _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:77:64)
#19     _rootRunUnary (dart:async/zone.dart:1132:38)
#20     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#21     _FutureListener.handleValue (dart:async/future_impl.dart:126:18)
#22     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:639:45)
#23     Future._propagateToListeners (dart:async/future_impl.dart:668:32)
#24     Future._complete (dart:async/future_impl.dart:473:7)
#25     _SyncCompleter.complete (dart:async/future_impl.dart:51:12)
#26     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:28:18)
#27     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:294:13)
#28     _LocalFile&LocalFileSystemEntity&ForwardingFile.writeAsString (package:file/src/forwarding/forwarding_file.dart)
#29     _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:77:64)
#30     _rootRunUnary (dart:async/zone.dart:1132:38)
#31     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#32     _FutureListener.handleValue (dart:async/future_impl.dart:126:18)
#33     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:639:45)
#34     Future._propagateToListeners (dart:async/future_impl.dart:668:32)
#35     Future._completeWithValue (dart:async/future_impl.dart:483:5)
#36     Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:513:7)
#37     _rootRun (dart:async/zone.dart:1124:13)
#38     _CustomZone.run (dart:async/zone.dart:1021:19)
#39     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:947:23)
#40     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#41     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#42     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:115:13)
#43     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:5)
```

## flutter doctor -v
```
[✓] Flutter (Channel stable, v1.5.4-hotfix.2, on Mac OS X 10.14.3 18D109, locale en-US)
    • Flutter version 1.5.4-hotfix.2 at /Users/xxx/Downloads/flutter
    • Framework revision 7a4c33425d (10 weeks ago), 2019-04-29 11:05:24 -0700
    • Engine revision 52c7a1e849
    • Dart version 2.3.0 (build 2.3.0-dev.0.5 a1668566e5)

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/xxx/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = /Users/xxx/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.2.1)
    • Xcode at /Users/xxx/Downloads/Xcode.app/Contents/Developer
    • Xcode 10.2.1, Build version 10E1001
    • ios-deploy 1.9.4
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.4)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 37.0.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

[✓] Connected device (1 available)
    • edheba macbook’s iPhone • 00008020-00096DC1029A002E • ios • iOS 12.2

• No issues found!

```
```

**Comment by Suman085** [comment]
Found a solution, In my case it was two identical project . One of which i had created some months ago. The new project i created wasn't working for me.
->Goto If u project build folder of any other flutter projects that you have created  before your macOS update/or flutter( i am not sure what was causing). 
->Copy pasting the build/AOT folder and pasting it in your new project will solve the issue.

**Comment by janmoppel** [comment]
Hello @Suman085 !

Did you manage to solve the issue? Does the problem still persist in the latest stable version?

**Comment by lengqingfeng** [comment]
I have same error , how to fix
