### ISSUE TITLE
VideoRecorder: Invalid argument(s)

### ISSUE THREAD

**Issue by titanbender** [flutter/flutter#35732]
## Steps to Reproduce

I'm working on a VideoRecorder on Flutter. The Xcode build completes, however, an error is caught by the widgets library: 

```
flutter: The following ArgumentError was thrown building VideoRecorderExample(dirty, state:
flutter: _VideoRecorderExampleState#b6178):
flutter: Invalid argument(s)
```

This is the error stack: 

```
flutter: When the exception was thrown, this was the stack:
flutter: #0      List.[] (dart:core-patch/growable_array.dart:145:60)
flutter: #1      _VideoRecorderExampleState._cameraTogglesRowWidget (package:flutter_video_app/main.dart:133:47)
flutter: #2      _VideoRecorderExampleState.build (package:flutter_video_app/main.dart:82:17)
flutter: #3      StatefulElement.build (package:flutter/src/widgets/framework.dart:3825:27)
flutter: #4      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3739:15)
flutter: #5      Element.rebuild (package:flutter/src/widgets/framework.dart:3565:5)
flutter: #6      StatefulElement.update (package:flutter/src/widgets/framework.dart:3894:5)
flutter: #7      Element.updateChild (package:flutter/src/widgets/framework.dart:2753:15)
flutter: #8      SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4883:14)
flutter: #9      Element.updateChild (package:flutter/src/widgets/framework.dart:2753:15)
flutter: #10     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3750:16)
flutter: #11     Element.rebuild (package:flutter/src/widgets/framework.dart:3565:5)
flutter: #12     StatelessElement.update (package:flutter/src/widgets/framework.dart:3796:5)
flutter: #13     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:15)
flutter: #14     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4883:14)
flutter: #15     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:15)
flutter: #16     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4883:14)
flutter: #17     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:15)
flutter: #18     RenderObjectElement.updateChildren (package:flutter/src/widgets/framework.dart:4601:32)
flutter: #19     MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4992:17)
flutter: #20     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:15)
flutter: #21     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3750:16)
flutter: #22     Element.rebuild (package:flutter/src/widgets/framework.dart:3565:5)
flutter: #23     StatefulElement.update (package:flutter/src/widgets/framework.dart:3894:5)
flutter: #24     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:15)
flutter: #25     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4883:14)
flutter: #26     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:15)
flutter: #27     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3750:16)
flutter: #28     Element.rebuild (package:flutter/src/widgets/framework.dart:3565:5)
flutter: #29     StatefulElement.update (package:flutter/src/widgets/framework.dart:3894:5)
flutter: #30     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:15)
flutter: #31     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4883:14)
flutter: #32     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:15)
flutter: #33     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3750:16)
flutter: #34     Element.rebuild (package:flutter/src/widgets/framework.dart:3565:5)
flutter: #35     StatefulElement.update (package:flutter/src/widgets/framework.dart:3894:5)
flutter: #36     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:15)
flutter: #37     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4883:14)
flutter: #38     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:15)
flutter: #39     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3750:16)
flutter: #40     Element.rebuild (package:flutter/src/widgets/framework.dart:3565:5)
flutter: #41     StatefulElement.update (package:flutter/src/widgets/framework.dart:3894:5)
flutter: #42     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:15)
flutter: #43     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3750:16)
flutter: #44     Element.rebuild (package:flutter/src/widgets/framework.dart:3565:5)
flutter: #45     StatelessElement.update (package:flutter/src/widgets/framework.dart:3796:5)
flutter: #46     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:15)
flutter: #47     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3750:16)
flutter: #48     Element.rebuild (package:flutter/src/widgets/framework.dart:3565:5)
flutter: #49     StatefulElement.update (package:flutter/src/widgets/framework.dart:3894:5)
flutter: #50     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:15)
flutter: #51     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4883:14)
flutter: #52     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:15)
flutter: #53     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3750:16)
flutter: #54     Element.rebuild (package:flutter/src/widgets/framework.dart:3565:5)
flutter: #55     ProxyElement.update (package:flutter/src/widgets/framework.dart:4006:5)
flutter: #56     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:15)
flutter: #57     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4883:14)
flutter: #58     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:15)
flutter: #59     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3750:16)
flutter: #60     Element.rebuild (package:flutter/src/widgets/framework.dart:3565:5)
flutter: #61     StatefulElement.update (package:flutter/src/widgets/framework.dart:3894:5)
flutter: #62     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:15)
flutter: #63     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3750:16)
flutter: #64     Element.rebuild (package:flutter/src/widgets/framework.dart:3565:5)
flutter: #65     StatelessElement.update (package:flutter/src/widgets/framework.dart:3796:5)
flutter: #66     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:15)
flutter: #67     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4883:14)
flutter: #68     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:15)
flutter: #69     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3750:16)
flutter: #70     Element.rebuild (package:flutter/src/widgets/framework.dart:3565:5)
flutter: #71     ProxyElement.update (package:flutter/src/widgets/framework.dart:4006:5)
flutter: #72     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:15)
flutter: #73     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3750:16)
flutter: #74     Element.rebuild (package:flutter/src/widgets/framework.dart:3565:5)
flutter: #75     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2278:33)
flutter: #76     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding&WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:700:20)
flutter: #77     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:286:5)
flutter: #78     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1012:15)
flutter: #79     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:952:9)
flutter: #80     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.scheduleWarmUpFrame.<anonymous closure> (package:flutter/src/scheduler/binding.dart:773:7)
flutter: #82     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:382:19)
flutter: #83     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:416:5)
flutter: #84     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:171:12)
flutter: (elided one frame from package dart:async-patch)
flutter: ════════════════════════════════════════════════════════════════════════════════════════════════════
```

My main.dart is located here and I'm using the following dependencies: 
https://gist.github.com/titanbender/ff0effa126c1025393c598558bd47e2d
```
  camera: ^0.2.9+1
  fluttertoast: ^2.2.6
  path_provider: ^1.1.0
  video_player: ^0.10.1+3
```

#### `flutter run --verbose` 

https://gist.github.com/titanbender/5d1f503a3140751afcec570aa99360d2

#### `flutter analyze` 

`Analyzing flutter_video_app...

   info • Unused import: 'package:video_player/video_player.dart' • lib/main.dart:7:8 • unused_import
   info • Avoid using braces in interpolation when not needed • lib/main.dart:287:46 • unnecessary_brace_in_string_interps
   info • Unused import: 'package:flutter_video_app/main.dart' • test/widget_test.dart:11:8 • unused_import
  error • The function 'MyApp' isn't defined • test/widget_test.dart:16:29 • undefined_function

4 issues found. (ran in 2.8s)`

####  `flutter doctor -v` 

`[✓] Flutter (Channel stable, v1.5.4-hotfix.2, on Mac OS X 10.14.5 18F132, locale en-US)
    • Flutter version 1.5.4-hotfix.2 at /Users/Bender/OneDrive/flutter/flutter
    • Framework revision 7a4c33425d (2 months ago), 2019-04-29 11:05:24 -0700
    • Engine revision 52c7a1e849
    • Dart version 2.3.0 (build 2.3.0-dev.0.5 a1668566e5)

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.0)
    • Android SDK at /Users/Bender/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.2.1, Build version 10E1001
    • ios-deploy 1.9.4
    • CocoaPods version 1.7.3

[✓] Android Studio (version 3.4)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 37.0.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

[✓] Connected device (1 available)
    • iPhone Xʀ • 3BDC538F-F027-4396-9A93-CBECB969F427 • ios • com.apple.CoreSimulator.SimRuntime.iOS-12-2 (simulator)

• No issues found!`

I'm new to Flutter, so I realize it might be a simple fix that I've just not been able to identify.

**Comment by ketanm** [comment]
@titanbender 

The first snippet you mentioned that it compiled and then gave the following error? This line appears to be partial, can you share full error? `flutter: The following ArgumentError was thrown building VideoRecorderExample(dirty, state:`

If you want then can use `cameras = await availableCameras()`, it improves readability but technically same as `.then`.

Not sure if this may fix an issue or not but see if you can avoid using `GlobalKey`, in your code I don't see it as necessary.

Sorry, it is hard to see which code is throwing ArgumentError.

**Comment by BondarenkoStas** [comment]
@titanbender Did you manage to solve the issue? Do you experience it with latest flutter stable and latest video_player?

**Comment by iapicca** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
  
Thanks for your contribution.
