### ISSUE TITLE
[Desktop MacOS] RawMaterialButton: setState called during build

### ISSUE THREAD

**Issue by modulovalue** [flutter/flutter#35808]
Changing the theme in my application on Flutter Desktop (MacOS) results in the exception below.
(It did work fine on a prior flutter commit).

I currently don't have the time to create a reproducible example. My temporary fix is to remove the setState call at ` _RawMaterialButtonState._handleHoveredChanged (package:flutter/src/material/button.dart:267:7)`.

Stacktrace:

```
flutter: ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
flutter: The following assertion was thrown building InkWell(gestures: <none>, clipped to BoxShape.rectangle,
flutter: dependencies: [_LocalizationsScope-[GlobalKey#66e77], _InheritedTheme, Directionality,
flutter: _FocusMarker], state: _InkResponseState<InkResponse>#9eeba):
flutter: setState() or markNeedsBuild() called during build.
flutter: This RawMaterialButton widget cannot be marked as needing to build because the framework is already
flutter: in the process of building widgets.  A widget can be marked as needing to be built during the build
flutter: phase only if one of its ancestors is currently building. This exception is allowed because the
flutter: framework builds parent widgets before children, which means a dirty descendant will always be
flutter: built. Otherwise, the framework might not visit this widget during this build phase.
flutter: The widget on which setState() or markNeedsBuild() was called was:
flutter:   RawMaterialButton
flutter: The widget which was currently being built when the offending call was made was:
flutter:   InkWell
flutter: 
flutter: When the exception was thrown, this was the stack:
flutter: #0      Element.markNeedsBuild.<anonymous closure> (package:flutter/src/widgets/framework.dart:3670:11)
flutter: #1      Element.markNeedsBuild (package:flutter/src/widgets/framework.dart:3685:6)
flutter: #2      State.setState (package:flutter/src/widgets/framework.dart:1161:14)
flutter: #3      _RawMaterialButtonState._handleHoveredChanged (package:flutter/src/material/button.dart:267:7)
flutter: #4      _InkResponseState.updateHighlight (package:flutter/src/material/ink_well.dart:567:18)
flutter: #5      _InkResponseState._handleHoverChange (package:flutter/src/material/ink_well.dart:693:7)
flutter: #6      _InkResponseState._handlePointerExit (package:flutter/src/material/ink_well.dart:689:54)
flutter: #7      MouseTracker.detachAnnotation (package:flutter/src/gestures/mouse_tracking.dart:130:20)
flutter: #8      RenderPointerListener._updateAnnotations (package:flutter/src/rendering/proxy_box.dart:2575:45)
flutter: #9      RenderPointerListener.onPointerEnter= (package:flutter/src/rendering/proxy_box.dart:2517:7)
flutter: #10     Listener.updateRenderObject (package:flutter/src/widgets/basic.dart:5570:9)
flutter: #11     RenderObjectElement.update (package:flutter/src/widgets/framework.dart:4726:12)
flutter: #12     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:5097:11)
flutter: #13     Element.updateChild (package:flutter/src/widgets/framework.dart:2876:15)
flutter: #14     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3935:16)
flutter: #15     Element.rebuild (package:flutter/src/widgets/framework.dart:3721:5)
flutter: #16     StatefulElement.update (package:flutter/src/widgets/framework.dart:4085:5)
flutter: #17     Element.updateChild (package:flutter/src/widgets/framework.dart:2876:15)
flutter: #18     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3935:16)
flutter: #19     Element.rebuild (package:flutter/src/widgets/framework.dart:3721:5)
flutter: #20     ProxyElement.update (package:flutter/src/widgets/framework.dart:4219:5)
flutter: #21     Element.updateChild (package:flutter/src/widgets/framework.dart:2876:15)
flutter: #22     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3935:16)
flutter: #23     Element.rebuild (package:flutter/src/widgets/framework.dart:3721:5)
flutter: #24     StatefulElement.update (package:flutter/src/widgets/framework.dart:4085:5)
flutter: #25     Element.updateChild (package:flutter/src/widgets/framework.dart:2876:15)
flutter: #26     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:5099:14)
flutter: #27     Element.updateChild (package:flutter/src/widgets/framework.dart:2876:15)
flutter: #28     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3935:16)
flutter: #29     Element.rebuild (package:flutter/src/widgets/framework.dart:3721:5)
flutter: #30     StatelessElement.update (package:flutter/src/widgets/framework.dart:3981:5)
flutter: #31     Element.updateChild (package:flutter/src/widgets/framework.dart:2876:15)
flutter: #32     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:5099:14)
flutter: #33     Element.updateChild (package:flutter/src/widgets/framework.dart:2876:15)
flutter: #34     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3935:16)
flutter: #35     Element.rebuild (package:flutter/src/widgets/framework.dart:3721:5)
flutter: #36     StatelessElement.update (package:flutter/src/widgets/framework.dart:3981:5)
flutter: #37     Element.updateChild (package:flutter/src/widgets/framework.dart:2876:15)
flutter: #38     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:5099:14)
flutter: #39     Element.updateChild (package:flutter/src/widgets/framework.dart:2876:15)
flutter: #40     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3935:16)
flutter: #41     Element.rebuild (package:flutter/src/widgets/framework.dart:3721:5)
flutter: #42     StatefulElement.update (package:flutter/src/widgets/framework.dart:4085:5)
flutter: #43     Element.updateChild (package:flutter/src/widgets/framework.dart:2876:15)
flutter: #44     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3935:16)
flutter: #45     Element.rebuild (package:flutter/src/widgets/framework.dart:3721:5)
flutter: #46     StatefulElement.update (package:flutter/src/widgets/framework.dart:4085:5)
flutter: #47     Element.updateChild (package:flutter/src/widgets/framework.dart:2876:15)
flutter: #48     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:5099:14)
flutter: #49     Element.updateChild (package:flutter/src/widgets/framework.dart:2876:15)
flutter: #50     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3935:16)
flutter: #51     Element.rebuild (package:flutter/src/widgets/framework.dart:3721:5)
flutter: #52     ProxyElement.update (package:flutter/src/widgets/framework.dart:4219:5)
flutter: #53     _InheritedNotifierElement.update (package:flutter/src/widgets/inherited_notifier.dart:94:11)
flutter: #54     Element.updateChild (package:flutter/src/widgets/framework.dart:2876:15)
flutter: #55     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3935:16)
flutter: #56     Element.rebuild (package:flutter/src/widgets/framework.dart:3721:5)
flutter: #57     StatefulElement.update (package:flutter/src/widgets/framework.dart:4085:5)
flutter: #58     Element.updateChild (package:flutter/src/widgets/framework.dart:2876:15)
flutter: #59     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:5099:14)
flutter: #60     Element.updateChild (package:flutter/src/widgets/framework.dart:2876:15)
flutter: #61     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:5099:14)
flutter: #62     Element.updateChild (package:flutter/src/widgets/framework.dart:2876:15)
flutter: #63     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3935:16)
flutter: #64     Element.rebuild (package:flutter/src/widgets/framework.dart:3721:5)
flutter: #65     StatefulElement.update (package:flutter/src/widgets/framework.dart:4085:5)
flutter: #66     Element.updateChild (package:flutter/src/widgets/framework.dart:2876:15)
flutter: #67     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3935:16)
flutter: #68     Element.rebuild (package:flutter/src/widgets/framework.dart:3721:5)
flutter: #69     StatelessElement.update (package:flutter/src/widgets/framework.dart:3981:5)
flutter: #70     Element.updateChild (package:flutter/src/widgets/framework.dart:2876:15)
flutter: #71     RenderObjectElement.updateChildren (package:flutter/src/widgets/framework.dart:4817:32)
flutter: #72     MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:5208:17)
flutter: #73     Element.updateChild (package:flutter/src/widgets/framework.dart:2876:15)
flutter: #74     HookElement.updateChild (package:flutter_hooks/src/framework.dart:335:18)
flutter: #75     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3935:16)
flutter: #76     Element.rebuild (package:flutter/src/widgets/framework.dart:3721:5)
flutter: #77     StatefulElement.update (package:flutter/src/widgets/framework.dart:4085:5)
flutter: #78     Element.updateChild (package:flutter/src/widgets/framework.dart:2876:15)
flutter: #79     RenderObjectElement.updateChildren (package:flutter/src/widgets/framework.dart:4817:32)
flutter: #80     MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:5208:17)
flutter: #81     Element.updateChild (package:flutter/src/widgets/framework.dart:2876:15)
flutter: #82     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:5099:14)
flutter: #83     Element.updateChild (package:flutter/src/widgets/framework.dart:2876:15)
flutter: #84     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:5099:14)
flutter: #85     Element.updateChild (package:flutter/src/widgets/framework.dart:2876:15)
flutter: #86     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3935:16)
flutter: #87     Element.rebuild (package:flutter/src/widgets/framework.dart:3721:5)
flutter: #88     StatelessElement.update (package:flutter/src/widgets/framework.dart:3981:5)
flutter: #89     Element.updateChild (package:flutter/src/widgets/framework.dart:2876:15)
flutter: #90     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3935:16)
flutter: #91     Element.rebuild (package:flutter/src/widgets/framework.dart:3721:5)
flutter: #92     ProxyElement.update (package:flutter/src/widgets/framework.dart:4219:5)
flutter: #93     Element.updateChild (package:flutter/src/widgets/framework.dart:2876:15)
flutter: #94     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3935:16)
flutter: #95     Element.rebuild (package:flutter/src/widgets/framework.dart:3721:5)
flutter: #96     StatefulElement.update (package:flutter/src/widgets/framework.dart:4085:5)
flutter: #97     Element.updateChild (package:flutter/src/widgets/framework.dart:2876:15)
flutter: #98     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3935:16)
flutter: #99     Element.rebuild (package:flutter/src/widgets/framework.dart:3721:5)
flutter: #100    StatelessElement.update (package:flutter/src/widgets/framework.dart:3981:5)
flutter: #101    Element.updateChild (package:flutter/src/widgets/framework.dart:2876:15)
flutter: #102    SliverMultiBoxAdaptorElement.updateChild (package:flutter/src/widgets/sliver.dart:1181:36)
flutter: #103    SliverMultiBoxAdaptorElement.performRebuild.processElement (package:flutter/src/widgets/sliver.dart:1113:34)
flutter: #104    Iterable.forEach (dart:core/iterable.dart:277:30)
flutter: #105    SliverMultiBoxAdaptorElement.performRebuild (package:flutter/src/widgets/sliver.dart:1139:24)
flutter: #106    SliverMultiBoxAdaptorElement.update (package:flutter/src/widgets/sliver.dart:1084:7)
flutter: #107    Element.updateChild (package:flutter/src/widgets/framework.dart:2876:15)
flutter: #108    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:5099:14)
flutter: #109    Element.updateChild (package:flutter/src/widgets/framework.dart:2876:15)
flutter: #110    RenderObjectElement.updateChildren (package:flutter/src/widgets/framework.dart:4817:32)
flutter: #111    MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:5208:17)
flutter: #112    _ViewportElement.update (package:flutter/src/widgets/viewport.dart:192:11)
flutter: #113    Element.updateChild (package:flutter/src/widgets/framework.dart:2876:15)
flutter: #114    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:5099:14)
flutter: #115    Element.updateChild (package:flutter/src/widgets/framework.dart:2876:15)
flutter: #116    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:5099:14)
flutter: #117    Element.updateChild (package:flutter/src/widgets/framework.dart:2876:15)
flutter: #118    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:5099:14)
flutter: #119    Element.updateChild (package:flutter/src/widgets/framework.dart:2876:15)
flutter: #120    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:5099:14)
flutter: #121    Element.updateChild (package:flutter/src/widgets/framework.dart:2876:15)
flutter: #122    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3935:16)
flutter: #123    Element.rebuild (package:flutter/src/widgets/framework.dart:3721:5)
flutter: #124    StatefulElement.update (package:flutter/src/widgets/framework.dart:4085:5)
flutter: #125    Element.updateChild (package:flutter/src/widgets/framework.dart:2876:15)
flutter: #126    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:5099:14)
flutter: #127    Element.updateChild (package:flutter/src/widgets/framework.dart:2876:15)
flutter: #128    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3935:16)
flutter: #129    Element.rebuild (package:flutter/src/widgets/framework.dart:3721:5)
flutter: #130    ProxyElement.update (package:flutter/src/widgets/framework.dart:4219:5)
flutter: #131    Element.updateChild (package:flutter/src/widgets/framework.dart:2876:15)
flutter: #132    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:5099:14)
flutter: #133    Element.updateChild (package:flutter/src/widgets/framework.dart:2876:15)
flutter: #134    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3935:16)
flutter: #135    Element.rebuild (package:flutter/src/widgets/framework.dart:3721:5)
flutter: #136    StatefulElement.update (package:flutter/src/widgets/framework.dart:4085:5)
flutter: #137    Element.updateChild (package:flutter/src/widgets/framework.dart:2876:15)
flutter: #138    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3935:16)
flutter: #139    Element.rebuild (package:flutter/src/widgets/framework.dart:3721:5)
flutter: #140    ProxyElement.update (package:flutter/src/widgets/framework.dart:4219:5)
flutter: #141    Element.updateChild (package:flutter/src/widgets/framework.dart:2876:15)
flutter: #142    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3935:16)
flutter: #143    Element.rebuild (package:flutter/src/widgets/framework.dart:3721:5)
flutter: #144    StatelessElement.update (package:flutter/src/widgets/framework.dart:3981:5)
flutter: #145    Element.updateChild (package:flutter/src/widgets/framework.dart:2876:15)
flutter: #146    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3935:16)
flutter: #147    Element.rebuild (package:flutter/src/widgets/framework.dart:3721:5)
flutter: #148    ProxyElement.update (package:flutter/src/widgets/framework.dart:4219:5)
flutter: #149    Element.updateChild (package:flutter/src/widgets/framework.dart:2876:15)
flutter: #150    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3935:16)
flutter: #151    Element.rebuild (package:flutter/src/widgets/framework.dart:3721:5)
flutter: #152    ProxyElement.update (package:flutter/src/widgets/framework.dart:4219:5)
flutter: #153    Element.updateChild (package:flutter/src/widgets/framework.dart:2876:15)
flutter: #154    RenderObjectElement.updateChildren (package:flutter/src/widgets/framework.dart:4817:32)
flutter: #155    MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:5208:17)
flutter: #156    Element.updateChild (package:flutter/src/widgets/framework.dart:2876:15)
flutter: #157    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3935:16)
flutter: #158    Element.rebuild (package:flutter/src/widgets/framework.dart:3721:5)
flutter: #159    StatefulElement.update (package:flutter/src/widgets/framework.dart:4085:5)
flutter: #160    Element.updateChild (package:flutter/src/widgets/framework.dart:2876:15)
flutter: #161    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3935:16)
flutter: #162    Element.rebuild (package:flutter/src/widgets/framework.dart:3721:5)
flutter: #163    ProxyElement.update (package:flutter/src/widgets/framework.dart:4219:5)
flutter: #164    Element.updateChild (package:flutter/src/widgets/framework.dart:2876:15)
flutter: #165    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3935:16)
flutter: #166    Element.rebuild (package:flutter/src/widgets/framework.dart:3721:5)
flutter: #167    StatefulElement.update (package:flutter/src/widgets/framework.dart:4085:5)
flutter: #168    Element.updateChild (package:flutter/src/widgets/framework.dart:2876:15)
flutter: #169    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:5099:14)
flutter: #170    Element.updateChild (package:flutter/src/widgets/framework.dart:2876:15)
flutter: #171    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3935:16)
flutter: #172    Element.rebuild (package:flutter/src/widgets/framework.dart:3721:5)
flutter: #173    StatelessElement.update (package:flutter/src/widgets/framework.dart:3981:5)
flutter: #174    Element.updateChild (package:flutter/src/widgets/framework.dart:2876:15)
flutter: #175    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:5099:14)
flutter: #176    Element.updateChild (package:flutter/src/widgets/framework.dart:2876:15)
flutter: #177    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3935:16)
flutter: #178    Element.rebuild (package:flutter/src/widgets/framework.dart:3721:5)
flutter: #179    StatefulElement.update (package:flutter/src/widgets/framework.dart:4085:5)
flutter: #180    Element.updateChild (package:flutter/src/widgets/framework.dart:2876:15)
flutter: #181    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3935:16)
flutter: #182    Element.rebuild (package:flutter/src/widgets/framework.dart:3721:5)
flutter: #183    StatefulElement.update (package:flutter/src/widgets/framework.dart:4085:5)
flutter: #184    Element.updateChild (package:flutter/src/widgets/framework.dart:2876:15)
flutter: #185    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3935:16)
flutter: #186    Element.rebuild (package:flutter/src/widgets/framework.dart:3721:5)
flutter: #187    ProxyElement.update (package:flutter/src/widgets/framework.dart:4219:5)
flutter: #188    Element.updateChild (package:flutter/src/widgets/framework.dart:2876:15)
flutter: #189    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3935:16)
flutter: #190    Element.rebuild (package:flutter/src/widgets/framework.dart:3721:5)
flutter: #191    ProxyElement.update (package:flutter/src/widgets/framework.dart:4219:5)
flutter: #192    Element.updateChild (package:flutter/src/widgets/framework.dart:2876:15)
flutter: #193    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3935:16)
flutter: #194    Element.rebuild (package:flutter/src/widgets/framework.dart:3721:5)
flutter: #195    StatefulElement.update (package:flutter/src/widgets/framework.dart:4085:5)
flutter: #196    Element.updateChild (package:flutter/src/widgets/framework.dart:2876:15)
flutter: #197    HookElement.updateChild (package:flutter_hooks/src/framework.dart:335:18)
flutter: #198    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3935:16)
flutter: #199    Element.rebuild (package:flutter/src/widgets/framework.dart:3721:5)
flutter: #200    BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2340:33)
flutter: #201    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding&WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:700:20)
flutter: #202    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:285:5)
flutter: #203    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1016:15)
flutter: #204    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:958:9)
flutter: #205    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:874:5)
flutter: #209    _invoke (dart:ui/hooks.dart:236:10)
flutter: #210    _drawFrame (dart:ui/hooks.dart:194:3)
flutter: (elided 3 frames from package dart:async)
flutter: ════════════════════════════════════════════════════════════════════════════════════════════════════
flutter: Another exception was thrown: 'package:flutter/src/material/material.dart': Failed assertion: line 585 pos 12: 'referenceBox.attached': is not true.
flutter: Another exception was thrown: A RenderFlex overflowed by 99352 pixels on the right.
flutter: Another exception was thrown: 'package:flutter/src/material/material.dart': Failed assertion: line 585 pos 12: 'referenceBox.attached': is not true.

```

Doctor: 

```
[✓] Flutter (Channel dev, v1.7.11, on Mac OS X 10.14.5 18F132, locale de-DE)
    • Flutter version 1.7.11 at /Users/x/Desktop/flutter
    • Framework revision 43b03127d4 (13 days ago), 2019-06-26 23:27:39 -0400
    • Engine revision f3761ba8d0
    • Dart version 2.4.0

 
[!] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/x/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Library/Java/JavaVirtualMachines/jdk1.8.0_152.jdk/Contents/Home/bin/java
    • Java version Java(TM) SE Runtime Environment (build 1.8.0_152-ea-b05)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses

[✓] Xcode - develop for iOS and macOS (Xcode 10.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.2.1, Build version 10E1001
    • CocoaPods version 1.7.1

[✓] iOS tools - develop for iOS devices
    • ios-deploy 1.9.4

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/setup/#android-setup for detailed instructions).

[✓] Connected device (2 available)
    • macOS  • macOS  • darwin-x64     • Mac OS X 10.14.5 18F132
    • Chrome • chrome • web-javascript • Google Chrome 75.0.3770.100 


! Doctor found issues in 2 categories.

```

**Comment by stuartmorgan** [comment]
@gspencergoog This is another issue like the ones I mentioned earlier today.

**Comment by dkwingsmt** [comment]
https://github.com/flutter/flutter/pull/37342 might fix it.

**Comment by modulovalue** [comment]
I assume you mean to try it out when the PR lands? Will do!

**Comment by modulovalue** [comment]
I do not have this issue on the current master anymore. Thanks!
