### ISSUE TITLE
flutter run --profile crashes (failed to find snapshot)

### ISSUE THREAD

**Issue by oli06** [flutter/flutter#35824]
Hi,

I'm trying to run my app on my device in profile mode with the command `flutter run --profile -d DEVICE_ID`. It crashes after the xcode build with following output: 
```
Failed to find snapshot: /var/containers/Bundle/Application/D5AE5AD2-B159-4763-BA93-A4A303F2DCDD/Runner.app/Frameworks/App.framework/flutter_assets/kernel_blob.bin
[VERBOSE-2:engine.cc(115)] Engine run configuration was invalid.        
[VERBOSE-2:FlutterEngine.mm(304)] Could not launch engine with configuration.
```

## command
```
flutter run --profile -d 57f9fABCDEF418dd747e8908ea308288d6e29968
```
## exception
```
HttpException: HttpException: , uri = http://127.0.0.1:1026/IhQzBpttNiA=/ws
```
```
#0      _defaultOpenChannel (package:flutter_tools/src/vmservice.dart:89:16)
<asynchronous suspension>
#1      VMService.connect (package:flutter_tools/src/vmservice.dart:255:61)
<asynchronous suspension>
#2      FlutterDevice._connect (package:flutter_tools/src/resident_runner.dart:128:44)
<asynchronous suspension>
#3      ResidentRunner.connectToServiceProtocol (package:flutter_tools/src/resident_runner.dart:793:20)
<asynchronous suspension>
#4      ColdRunner.run (package:flutter_tools/src/run_cold.dart:73:15)
<asynchronous suspension>
#5      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:428:37)
<asynchronous suspension>
#6      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:559:18)
#7      _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:77:64)
#8      _rootRunUnary (dart:async/zone.dart:1132:38)
#9      _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#10     _FutureListener.handleValue (dart:async/future_impl.dart:126:18)
#11     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:639:45)
#12     Future._propagateToListeners (dart:async/future_impl.dart:668:32)
#13     Future._complete (dart:async/future_impl.dart:473:7)
#14     _SyncCompleter.complete (dart:async/future_impl.dart:51:12)
#15     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:28:18)
#16     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:294:13)
#17     RunCommand.usageValues (package:flutter_tools/src/commands/run.dart)
#18     _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:77:64)
#19     _rootRunUnary (dart:async/zone.dart:1132:38)
#20     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#21     _FutureListener.handleValue (dart:async/future_impl.dart:126:18)
#22     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:639:45)
#23     Future._propagateToListeners (dart:async/future_impl.dart:668:32)
#24     Future._complete (dart:async/future_impl.dart:473:7)
#25     _SyncCompleter.complete (dart:async/future_impl.dart:51:12)
#26     _AsyncAwaitCompleter.complete.<anonymous closure> (dart:async-patch/async_patch.dart:33:20)
#27     _rootRun (dart:async/zone.dart:1124:13)
#28     _CustomZone.run (dart:async/zone.dart:1021:19)
#29     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:947:23)
#30     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#31     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#32     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:115:13)
#33     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:5)
```

## flutter doctor

```
[32m[✓][39m Flutter (Channel stable, v1.5.4-hotfix.3-pre.2, on Mac OS X 10.14.5 18F132, locale de-DE)
    [32m•[39m Flutter version 1.5.4-hotfix.3-pre.2 at /Users/oliver/flutter
    [32m•[39m Framework revision 6853656d41 (23 hours ago), 2019-07-08 23:53:47 +0200
    [32m•[39m Engine revision 52c7a1e849
    [32m•[39m Dart version 2.3.0 (build 2.3.0-dev.0.5 a1668566e5)

[31m[✗][39m Android toolchain - develop for Android devices
    [31m✗[39m Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/setup/#android-setup for detailed instructions).
      If the Android SDK has been installed to a custom location, set ANDROID_HOME to that location.
      You may also want to add it to your PATH environment variable.


[32m[✓][39m iOS toolchain - develop for iOS devices (Xcode 10.2.1)
    [32m•[39m Xcode at /Applications/Xcode.app/Contents/Developer
    [32m•[39m Xcode 10.2.1, Build version 10E1001
    [32m•[39m ios-deploy 1.9.4
    [32m•[39m CocoaPods version 1.6.1

[33m[!][39m Android Studio (not installed)
    [32m•[39m Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/setup/#android-setup for detailed instructions).

[32m[✓][39m VS Code (version 1.36.1)
    [32m•[39m VS Code at /Applications/Visual Studio Code.app/Contents
    [32m•[39m Flutter extension version 3.2.0

[32m[✓][39m Connected device (2 available)
    [32m•[39m Olis iPhone • 57f9fABCDEF418dd747e8908ea308288d6e29968 • ios • iOS 12.3.1
    [32m•[39m iPhone Xʀ   • 7CA1551F-9EF8-41B2-86C9-5FE77264624E     • ios • com.apple.CoreSimulator.SimRuntime.iOS-12-2 (simulator)

[33m![39m Doctor found issues in 2 categories.
```

**Comment by BondarenkoStas** [comment]
@oli06 Do you experience it using latest flutter stable?

**Comment by iapicca** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
  
Thanks for your contribution.
