### ISSUE TITLE
Execution failed for task ':app:compileflutterBuildEscapDebugArm64'.

### ISSUE THREAD

**Issue by bhanuka96** [flutter/flutter#35854]
## **flutter doctor**
```
> [√] Flutter (Channel stable, v1.7.8+hotfix.3, on Microsoft Windows [Version 10.0.18362.30], locale en-US)
> [√] Android toolchain - develop for Android devices (Android SDK version 29.0.0)
> [√] Android Studio (version 3.4)
> [√] VS Code (version 1.36.1)
> [√] Connected device (1 available)
```
## **flutter run --flavor escap -t lib/main_escap.dart --verbose**
```
[   +2 ms] Compiler failed on C:\Users\bhanuka\Documents\Native-App-master\lib/main_escap.dart
[        ] #0      throwToolExit (package:flutter_tools/src/base/common.dart:28:3)
[        ] #1      BundleBuilder.build (package:flutter_tools/src/bundle.dart:97:9)
[        ] <asynchronous suspension>
[        ] #2      BuildBundleCommand.runCommand (package:flutter_tools/src/commands/build_bundle.dart:116:25)
[        ] <asynchronous suspension>
[        ] #3      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:478:18)
[        ] <asynchronous suspension>
[        ] #4      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:383:33)
[        ] <asynchronous suspension>
[        ] #5      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:29)
[        ] <asynchronous suspension>
[        ] #6      _rootRun (dart:async/zone.dart:1124:13)
[        ] #7      _CustomZone.run (dart:async/zone.dart:1021:19)
[        ] #8      _runZoned (dart:async/zone.dart:1516:10)
[   +8 ms] #9      runZoned (dart:async/zone.dart:1463:12)
[   +2 ms] #10     AppContext.run (package:flutter_tools/src/base/context.dart:152:18)
[        ] <asynchronous suspension>
[   +1 ms] #11     FlutterCommand.run (package:flutter_tools/src/runner/flutter_command.dart:375:20)
[   +1 ms] #12     CommandRunner.runCommand (package:args/command_runner.dart:197:27)
[        ] <asynchronous suspension>
[        ] #13     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:396:21)
[        ] <asynchronous suspension>
[   +1 ms] #14     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:29)
[        ] <asynchronous suspension>
[   +7 ms] #15     _rootRun (dart:async/zone.dart:1124:13)
[        ] #16     _CustomZone.run (dart:async/zone.dart:1021:19)
[        ] #17     _runZoned (dart:async/zone.dart:1516:10)
[        ] #18     runZoned (dart:async/zone.dart:1463:12)
[        ] #19     AppContext.run (package:flutter_tools/src/base/context.dart:152:18)
[        ] <asynchronous suspension>
[        ] #20     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:356:19)
[        ] <asynchronous suspension>
[        ] #21     CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:112:25)
[        ] #22     new Future.sync (dart:async/future.dart:224:31)
[        ] #23     CommandRunner.run (package:args/command_runner.dart:112:14)
[        ] #24     FlutterCommandRunner.run (package:flutter_tools/src/runner/flutter_command_runner.dart:242:18)
[        ] #25     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:62:22)
[        ] <asynchronous suspension>
[        ] #26     _rootRun (dart:async/zone.dart:1124:13)
[        ] #27     _CustomZone.run (dart:async/zone.dart:1021:19)
[        ] #28     _runZoned (dart:async/zone.dart:1516:10)
[        ] #29     runZoned (dart:async/zone.dart:1500:12)
[        ] #30     run.<anonymous closure> (package:flutter_tools/runner.dart:60:18)
[        ] <asynchronous suspension>
[        ] #31     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:29)
[        ] <asynchronous suspension>
[        ] #32     _rootRun (dart:async/zone.dart:1124:13)
[   +4 ms] #33     _CustomZone.run (dart:async/zone.dart:1021:19)
[   +5 ms] #34     _runZoned (dart:async/zone.dart:1516:10)
[        ] #35     runZoned (dart:async/zone.dart:1463:12)
[        ] #36     AppContext.run (package:flutter_tools/src/base/context.dart:152:18)
[   +9 ms] <asynchronous suspension>
[        ] #37     runInContext (package:flutter_tools/src/context_runner.dart:56:24)
[        ] > Task :app:compileflutterBuildEscapDebugArm64 FAILED
[        ] 1 actionable task: 1 executed
[        ]          *********************************************************
[        ] WARNING: This version of connectivity will break your Android build if it or its dependencies aren't compatible with AndroidX.
[        ]          See https://goo.gl/CP92wY for more information on the problem and how to fix it.
[        ]          This warning prints for all Android build failures. The real root cause of the error may be unrelated.
[        ]          *********************************************************
[        ] <asynchronous suspension>
[        ] #38     run (package:flutter_tools/runner.dart:51:10)
[        ] #39     main (package:flutter_tools/executable.dart:62:9)
[        ] <asynchronous suspension>
[        ] #40     main (file:///C:/src/flutter/packages/flutter_tools/bin/flutter_tools.dart:8:3)
[        ] #41     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:299:32)
[        ] #42     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:12)
[        ] FAILURE: Build failed with an exception.
[        ] * Where:
[        ] Script 'C:\src\flutter\packages\flutter_tools\gradle\flutter.gradle' line: 665
[        ] * What went wrong:
[   +4 ms] Execution failed for task ':app:compileflutterBuildEscapDebugArm64'.
[        ] > Process 'command 'C:\src\flutter\bin\flutter.bat'' finished with non-zero exit value 1
[        ] * Try:
[        ] Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
[        ] * Get more help at https://help.gradle.org
[        ] BUILD FAILED in 13s
[ +506 ms] Running Gradle task 'assembleEscapDebug'... (completed in 14.7s)
[        ] *******************************************************************************************
[        ] The Gradle failure may have been because of AndroidX incompatibilities in this Flutter app.
[        ] See https://goo.gl/CP92wY for more information on the problem and how to fix it.
[        ] *******************************************************************************************
[  +19 ms] "flutter run" took 23,297ms.
[        ] "flutter run" took 23,297ms.
Gradle task assembleEscapDebug failed with exit code 1

#0      throwToolExit (package:flutter_tools/src/base/common.dart:28:3)
#1      _buildGradleProjectV2 (package:flutter_tools/src/android/gradle.dart:507:5)
#2      _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:77:64)
#3      _rootRunUnary (dart:async/zone.dart:1132:38)
#4      _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#5      _FutureListener.handleValue (dart:async/future_impl.dart:126:18)
#6      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:639:45)
#7      Future._propagateToListeners (dart:async/future_impl.dart:668:32)
#8      Future._complete (dart:async/future_impl.dart:473:7)
#9      _SyncCompleter.complete (dart:async/future_impl.dart:51:12)
#10     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:28:18)
#11     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:294:13)
#12     runCommandAndStreamOutput (package:flutter_tools/src/base/process.dart)
#13     _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:77:64)
#14     _rootRunUnary (dart:async/zone.dart:1132:38)
#15     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#16     _FutureListener.handleValue (dart:async/future_impl.dart:126:18)
#17     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:639:45)
#18     Future._propagateToListeners (dart:async/future_impl.dart:668:32)
#19     Future._completeWithValue (dart:async/future_impl.dart:483:5)
#20     Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:513:7)
#21     _rootRun (dart:async/zone.dart:1124:13)
#22     _CustomZone.run (dart:async/zone.dart:1021:19)
#23     _CustomZone.runGuarded (dart:async/zone.dart:923:7)
#24     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:963:23)
#25     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#26     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#27     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:116:13)
#28     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:173:5))
```

## **flutter build apk --flavor escap -t lib/main_escap.dart**
```
You are building a fat APK that includes binaries for android-arm, android-arm64.
If you are deploying the app to the Play Store, it's recommended to use app bundles or split the APK to reduce the APK size.
    To generate an app bundle, run:
        flutter build appbundle --target-platform android-arm,android-arm64
        Learn more on: https://developer.android.com/guide/app-bundle
    To split the APKs per ABI, run:
        flutter build apk --target-platform android-arm,android-arm64 --split-per-abi
        Learn more on:  https://developer.android.com/studio/build/configure-apk-splits#configure-abi-split
Initializing gradle...                                              1.0s
Resolving dependencies...                                           6.6s
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)

Compiler message:
file:///C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_svg-0.12.4+1/lib/src/picture_provider.dart:335:20: Error: The argument type 'String' can't be assigned to the parameter
type 'DiagnosticsNode'.
 - 'DiagnosticsNode' is from 'package:flutter/src/foundation/diagnostics.dart' ('file:///C:/src/flutter/packages/flutter/lib/src/foundation/diagnostics.dart').
Try changing the type of the parameter, or casting the argument to 'DiagnosticsNode'.
          context: 'while resolving a picture',
                   ^
file:///C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_svg-0.12.4+1/lib/src/picture_provider.dart:337:33: Error: The argument type 'Null Function(StringBuffer)' can't be assig
ned to the parameter type 'Iterable<DiagnosticsNode> Function()'.
 - 'StringBuffer' is from 'dart:core'.
 - 'Iterable' is from 'dart:core'.
 - 'DiagnosticsNode' is from 'package:flutter/src/foundation/diagnostics.dart' ('file:///C:/src/flutter/packages/flutter/lib/src/foundation/diagnostics.dart').
Try changing the type of the parameter, or casting the argument to 'Iterable<DiagnosticsNode> Function()'.
          informationCollector: (StringBuffer information) {
                                ^
file:///C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_svg-0.12.4+1/lib/src/picture_provider.dart:432:31: Error: The argument type 'Null Function(StringBuffer)' can't be assig
ned to the parameter type 'Iterable<DiagnosticsNode> Function()'.
 - 'StringBuffer' is from 'dart:core'.
 - 'Iterable' is from 'dart:core'.
 - 'DiagnosticsNode' is from 'package:flutter/src/foundation/diagnostics.dart' ('file:///C:/src/flutter/packages/flutter/lib/src/foundation/diagnostics.dart').
Try changing the type of the parameter, or casting the argument to 'Iterable<DiagnosticsNode> Function()'.
        informationCollector: (StringBuffer information) {
                              ^
file:///C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_svg-0.12.4+1/lib/src/picture_provider.dart:495:31: Error: The argument type 'Null Function(StringBuffer)' can't be assig
ned to the parameter type 'Iterable<DiagnosticsNode> Function()'.
 - 'StringBuffer' is from 'dart:core'.
 - 'Iterable' is from 'dart:core'.
 - 'DiagnosticsNode' is from 'package:flutter/src/foundation/diagnostics.dart' ('file:///C:/src/flutter/packages/flutter/lib/src/foundation/diagnostics.dart').
Try changing the type of the parameter, or casting the argument to 'Iterable<DiagnosticsNode> Function()'.
        informationCollector: (StringBuffer information) {
                              ^
file:///C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_svg-0.12.4+1/lib/src/picture_provider.dart:559:31: Error: The argument type 'Null Function(StringBuffer)' can't be assig
ned to the parameter type 'Iterable<DiagnosticsNode> Function()'.
 - 'StringBuffer' is from 'dart:core'.
 - 'Iterable' is from 'dart:core'.
 - 'DiagnosticsNode' is from 'package:flutter/src/foundation/diagnostics.dart' ('file:///C:/src/flutter/packages/flutter/lib/src/foundation/diagnostics.dart').
Try changing the type of the parameter, or casting the argument to 'Iterable<DiagnosticsNode> Function()'.
        informationCollector: (StringBuffer information) {
                              ^
file:///C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_svg-0.12.4+1/lib/src/picture_stream.dart:256:16: Error: The argument type 'String' can't be assigned to the parameter ty
pe 'DiagnosticsNode'.
 - 'DiagnosticsNode' is from 'package:flutter/src/foundation/diagnostics.dart' ('file:///C:/src/flutter/packages/flutter/lib/src/foundation/diagnostics.dart').
Try changing the type of the parameter, or casting the argument to 'DiagnosticsNode'.
      context: context,
               ^
file:///C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_svg-0.12.4+1/lib/src/picture_stream.dart:301:18: Error: The argument type 'String' can't be assigned to the parameter ty
pe 'DiagnosticsNode'.
 - 'DiagnosticsNode' is from 'package:flutter/src/foundation/diagnostics.dart' ('file:///C:/src/flutter/packages/flutter/lib/src/foundation/diagnostics.dart').
Try changing the type of the parameter, or casting the argument to 'DiagnosticsNode'.
        context: 'resolving a single-frame picture stream',
                 ^
file:///C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_svg-0.12.4+1/lib/svg.dart:158:18: Error: The argument type 'String' can't be assigned to the parameter type 'Diagnostics
Node'.
 - 'DiagnosticsNode' is from 'package:flutter/src/foundation/diagnostics.dart' ('file:///C:/src/flutter/packages/flutter/lib/src/foundation/diagnostics.dart').
Try changing the type of the parameter, or casting the argument to 'DiagnosticsNode'.
        context: 'picture failed to precache',
                 ^
file:///C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_svg-0.12.4+1/lib/src/svg/parser_state.dart:399:35: Error: The argument type 'Null Function(StringBuffer)' can't be assig
ned to the parameter type 'Iterable<DiagnosticsNode> Function()'.
 - 'StringBuffer' is from 'dart:core'.
 - 'Iterable' is from 'dart:core'.
 - 'DiagnosticsNode' is from 'package:flutter/src/foundation/diagnostics.dart' ('file:///C:/src/flutter/packages/flutter/lib/src/foundation/diagnostics.dart').
Try changing the type of the parameter, or casting the argument to 'Iterable<DiagnosticsNode> Function()'.
            informationCollector: (StringBuffer buff) {
                                  ^
file:///C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_svg-0.12.4+1/lib/src/svg/parser_state.dart:408:22: Error: The argument type 'String' can't be assigned to the parameter
type 'DiagnosticsNode'.
 - 'DiagnosticsNode' is from 'package:flutter/src/foundation/diagnostics.dart' ('file:///C:/src/flutter/packages/flutter/lib/src/foundation/diagnostics.dart').
Try changing the type of the parameter, or casting the argument to 'DiagnosticsNode'.
            context: 'in _Element.clipPath',
                     ^
file:///C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_svg-0.12.4+1/lib/src/svg/parser_state.dart:798:31: Error: The argument type 'Null Function(StringBuffer)' can't be assig
ned to the parameter type 'Iterable<DiagnosticsNode> Function()'.
 - 'StringBuffer' is from 'dart:core'.
 - 'Iterable' is from 'dart:core'.
 - 'DiagnosticsNode' is from 'package:flutter/src/foundation/diagnostics.dart' ('file:///C:/src/flutter/packages/flutter/lib/src/foundation/diagnostics.dart').
Try changing the type of the parameter, or casting the argument to 'Iterable<DiagnosticsNode> Function()'.
        informationCollector: (StringBuffer buff) {
                              ^
file:///C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_svg-0.12.4+1/lib/src/svg/parser_state.dart:809:18: Error: The argument type 'String' can't be assigned to the parameter
type 'DiagnosticsNode'.
 - 'DiagnosticsNode' is from 'package:flutter/src/foundation/diagnostics.dart' ('file:///C:/src/flutter/packages/flutter/lib/src/foundation/diagnostics.dart').
Try changing the type of the parameter, or casting the argument to 'DiagnosticsNode'.
        context: 'in parseSvgElement',
                 ^
file:///C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_svg-0.12.4+1/lib/src/utilities/errors.dart:8:32: Error: The argument type 'String' can't be assigned to the parameter ty
pe 'DiagnosticsNode'.
 - 'DiagnosticsNode' is from 'package:flutter/src/foundation/diagnostics.dart' ('file:///C:/src/flutter/packages/flutter/lib/src/foundation/diagnostics.dart').
Try changing the type of the parameter, or casting the argument to 'DiagnosticsNode'.
      context: 'in $methodName',
                               ^
file:///C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_svg-0.12.4+1/lib/src/utilities/errors.dart:10:29: Error: The argument type 'Null Function(StringBuffer)' can't be assign
ed to the parameter type 'Iterable<DiagnosticsNode> Function()'.
 - 'StringBuffer' is from 'dart:core'.
 - 'Iterable' is from 'dart:core'.
 - 'DiagnosticsNode' is from 'package:flutter/src/foundation/diagnostics.dart' ('file:///C:/src/flutter/packages/flutter/lib/src/foundation/diagnostics.dart').
Try changing the type of the parameter, or casting the argument to 'Iterable<DiagnosticsNode> Function()'.
      informationCollector: (StringBuffer buff) {
                            ^
Compiler terminated unexpectedly.

FAILURE: Build failed with an exception.

* Where:
Script 'C:\src\flutter\packages\flutter_tools\gradle\flutter.gradle' line: 638

* What went wrong:
Execution failed for task ':app:compileflutterBuildEscapReleaseArm'.
> Process 'command 'C:\src\flutter\bin\flutter.bat'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 15s
Running Gradle task 'assembleEscapRelease'...
Running Gradle task 'assembleEscapRelease'... Done                 16.3s
Gradle task assembleEscapRelease failed with exit code 1
```

**Comment by zukinaru** [comment]
i got similiar error, when trying to build APK in flutter v1.7.8+hotfix.3

**Comment by janmoppel** [comment]
Hello @bhanuka96 !

Did you manage to solve the issue? Does the problem still exist in the latest stable version?

Thank you.

**Comment by prasant10050** [comment]
I am also facing the same issue,someone help me on my production app
