### ISSUE TITLE
problem while running flutter web project

### ISSUE THREAD

**Issue by ocelili** [flutter/flutter#35967]
when I just opened my web flutter project in the visual studio code and tried debugging without changing any files, an error occurred 

> 

> [INFO] Connecting to the build daemon...
> [INFO] Generating build script...
> [INFO] Generating build script completed, took 1.6s
> [INFO]
> [INFO] Starting daemon...
> [INFO] Initializing inputs
> [INFO] Reading cached asset graph...
> [INFO] Reading cached asset graph completed, took 1.0s
> [INFO] Checking for updates since last build...
> [INFO] Checking for updates since last build completed, took 33.1s
> [INFO] Initializing inputs
> [INFO] Reading cached asset graph...
> [INFO] Reading cached asset graph completed, took 1.0s
> [INFO]
> [INFO] Checking for updates since last build...
> [INFO] Checking for updates since last build completed, took 33.1s
> [INFO]
> [INFO] Setting up file watchers...
> [INFO] Setting up file watchers completed, took 10ms
> [INFO]
> [INFO] Registering build targets...
> [INFO] Starting initial build...
> [INFO] Serving DevTools at http://127.0.0.1:62497
> [INFO] Starting resource servers...
> [INFO] Serving `web` on http://127.0.0.1:62484
> [INFO] About to build [web]...
> [INFO] Running build...
> [INFO] 1.0s elapsed, 0/0 actions completed.
> [INFO] Running build completed, took 1.5s
> [INFO] Caching finalized dependency graph...
> [INFO] Caching finalized dependency graph completed, took 777ms
> [INFO] Succeeded after 2.3s with 0 outputs (0 actions)
> Unhandled exception:
> FormatException: Unexpected character (at character 1)
> Not Found
> ^
> 
> #0      _ChunkedJsonParser.fail  (dart:convert-patch/convert_patch.dart:1392:5)
> #1      _ChunkedJsonParser.parseNumber  (dart:convert-patch/convert_patch.dart:1259:9)
> #2      _ChunkedJsonParser.parse  (dart:convert-patch/convert_patch.dart:924:22)
> #3      _parseJson  (dart:convert-patch/convert_patch.dart:29:10)
> #4      JsonDecoder.convert  (dart:convert/json.dart:493:36)
> #5      JsonCodec.decode  (dart:convert/json.dart:151:41)
> #6      jsonDecode  (dart:convert/json.dart:94:10)
> #7      parse
> #8      Sources.scriptParsed  (package:dwds/src/sources.dart:55:19)
> <asynchronous suspension>
> #9      _RootZone.runUnaryGuarded  (dart:async/zone.dart:1314:10)
> #10     CastStreamSubscription._onData  (dart:_internal/async_cast.dart:81:11)
> #11     _RootZone.runUnaryGuarded  (dart:async/zone.dart:1314:10)
> #12     _BufferingStreamSubscription._sendData  (dart:async/stream_impl.dart:336:11)
> #13     _BufferingStreamSubscription._add  (dart:async/stream_impl.dart:263:7)
> #14     _SinkTransformerStreamSubscription._add  (dart:async/stream_transformers.dart:68:11)
> #15     _EventSinkWrapper.add  (dart:async/stream_transformers.dart:15:11)
> #16     WipDomain.eventStream.<anonymous closure>.<anonymous closure>  (package:webkit_inspection_protocol/webkit_inspection_protocol.dart:301:26)
> #17     _HandlerEventSink.add  (dart:async/stream_transformers.dart:228:7)
> #18     _SinkTransformerStreamSubscription._handleData  (dart:async/stream_transformers.dart:120:24)
> #19     _RootZone.runUnaryGuarded  (dart:async/zone.dart:1314:10)
> #20     _BufferingStreamSubscription._sendData  (dart:async/stream_impl.dart:336:11)
> #21     _DelayedData.perform  (dart:async/stream_impl.dart:591:14)
> #22     _StreamImplEvents.handleNext  (dart:async/stream_impl.dart:707:11)
> #23     _PendingEvents.schedule.<anonymous closure>  (dart:async/stream_impl.dart:667:7)
> #24     _microtaskLoop  (dart:async/schedule_microtask.dart:41:21)
> #25     _startMicrotaskLoop  (dart:async/schedule_microtask.dart:50:5)
> #26     _runPendingImmediateCallback  (dart:isolate-patch/isolate_patch.dart:116:13)
> #27     _RawReceivePortImpl._handleMessage  (dart:isolate-patch/isolate_patch.dart:173:5)
> 
> Exited (255)

I have followed [this](I have followed this)
but still an error

**Comment by robertgol** [comment]
Same for me. Fresh Flutter installation (1.7) -> new Dart: Flutter web project in IntelliJ-> running produces same error.

**Comment by gabrielscr** [comment]
Same...

**Comment by ocelili** [comment]
@gabrielscr and @ robertgol did you already find the solution?

**Comment by robertgol** [comment]
@ocelili nope, I tried switching to 'flutter channel master', but then running the project produced multiple errors - 'You found a bug in our compiler' - or something smiliar. I'm going to file a bug for this later today if I find the time.

**Comment by robertgol** [comment]
@ocelili I found a solution. To run the app I'm just using the `webdev` command.

**What is the problem (my guess):**
I'm pretty sure it's an issue with the run configuration in **IntelliJ**.
At work, I'm using the **Ultimate** edition - with it I was able to run the default web app without this problem.

At home where I'm using the **Community** edition, the run configuration for the web app is different than the one in Ultimate.
This is Community:
![intellij_community_run_config](https://user-images.githubusercontent.com/17677124/61149369-42fd3c80-a4e1-11e9-8f2b-81494860d16a.png)
I don't even have a proper run configuration available in the list. The one that worked in the Ultimate was called **index.html**. I guess it might be related to the fact that the Community edition does not support web development tooling.

**How to run the app:**
Anyway, as a workaround, I'm just running my app from the command line using the `webdev` command.
I'm on Windows so this is how to do it:
1. Open cmd
2. cd into your web app project directory (ex. C:\Users\user\IdeaProjects\flutter_web_app)
3. run this command: `webdev serve --launch-in-chrome --auto refresh`

```
...
--[no-]launch-in-chrome       Automatically launches your application in Chrome with the
                                  debug port open. Use chrome-debug-port to specify a specific
                                  port to attach to an already running chrome instance instead.
...
--auto                        Automatically performs an action after each build:

                                  restart: Reload modules and re-invoke main (loses current
                                  state)
                                  refresh: Performs a full page refresh.
                                  [restart, refresh]
...
```
Chrome window should open on `localhost`. You can now edit your code in IntelliJ and once you hit save the chrome window will get refreshed. (You could also use the `restart` flag for **stateless hot-reload** if you wish).

I hope it's possible to actually do it **properly** in IntelliJ IDEA Community edition.
So if anyone has a clue how to do it, feel welcome to add a response. :D

Cheers

**Comment by icatalud** [comment]
Yes, the `webdev serve` command works, however it should still work correctly using the IDE. Besides it's not exactly the same, since the IDE has some kind of debugging UI, for example you can click stop. If the UI is not working, it shouldn't be offered at all, or instructions should be clear about this.
This problem requires a solution or clarification. There is another post about this issue #37490, apparently it's a problem of paths in windows. I read there that they fixed it, but it's still not working.

**Comment by LeXuanKhanh** [comment]
have they fixed it yet ?, i got the same error too
the webdev command is little different from debugging, webdev simply run and build the web, while debugging allow us to use devtool to debug the UI too, like when you hit run on android studio or  IntelliJ IDEA
