### ISSUE TITLE
Google Maps issue when I tap Toggle Platform: E/MethodChannel#flutter/platform_views( 4164): Failed to handle method call

### ISSUE THREAD

**Issue by pedromassango** [flutter/flutter#35983]
```
E/MethodChannel#flutter/platform_views( 4164): Failed to handle method call
E/MethodChannel#flutter/platform_views( 4164): java.lang.NullPointerException: Attempt to invoke virtual method 'double java.lang.Double.doubleValue()' on a null object reference
E/MethodChannel#flutter/platform_views( 4164): 	at io.flutter.plugin.platform.PlatformViewsController.createPlatformView(PlatformViewsController.java:165)
E/MethodChannel#flutter/platform_views( 4164): 	at io.flutter.plugin.platform.PlatformViewsController.onMethodCall(PlatformViewsController.java:142)
E/MethodChannel#flutter/platform_views( 4164): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:201)
E/MethodChannel#flutter/platform_views( 4164): 	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:88)
E/MethodChannel#flutter/platform_views( 4164): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:219)
E/MethodChannel#flutter/platform_views( 4164): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/MethodChannel#flutter/platform_views( 4164): 	at android.os.MessageQueue.next(MessageQueue.java:323)
E/MethodChannel#flutter/platform_views( 4164): 	at android.os.Looper.loop(Looper.java:136)
E/MethodChannel#flutter/platform_views( 4164): 	at android.app.ActivityThread.main(ActivityThread.java:6119)
E/MethodChannel#flutter/platform_views( 4164): 	at java.lang.reflect.Method.invoke(Native Method)
E/MethodChannel#flutter/platform_views( 4164): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
E/MethodChannel#flutter/platform_views( 4164): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
E/flutter ( 4164): [ERROR:flutter/lib/ui/ui_dart_state.cc(148)] Unhandled Exception: PlatformException(error, Attempt to invoke virtual method 'double java.lang.Double.doubleValue()' on a null object reference, null)
E/flutter ( 4164): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:564:7)
E/flutter ( 4164): #1      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:302:33)
E/flutter ( 4164): <asynchronous suspension>
E/flutter ( 4164): #2      PlatformViewsService.initUiKitView (package:flutter/src/services/platform_views.dart:132:41)
E/flutter ( 4164): <asynchronous suspension>
E/flutter ( 4164): #3      _UiKitViewState._createNewUiKitView (package:flutter/src/widgets/platform_view.dart:454:71)
E/flutter ( 4164): <asynchronous suspension>
E/flutter ( 4164): #4      _UiKitViewState._initializeOnce (package:flutter/src/widgets/platform_view.dart:404:5)
E/flutter ( 4164): #5      _UiKitViewState.didChangeDependencies (package:flutter/src/widgets/platform_view.dart:414:5)
E/flutter ( 4164): #6      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3862:12)
E/flutter ( 4164): #7      ComponentElement.mount (package:flutter/src/widgets/framework.dart:3717:5)
E/flutter ( 4164): #8      Element.inflateWidget (package:flutter/src/widgets/framework.dart:2961:14)
E/flutter ( 4164): #9      Element.updateChild (package:flutter/src/widgets/framework.dart:2764:12)
E/flutter ( 4164): #10     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3750:16)
E/flutter ( 4164): #11     Element.rebuild (package:flutter/src/widgets/framework.dart:3565:5)
E/flutter ( 4164): #12     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3722:5)
E/flutter ( 4164): #13     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3864:11)
E/flutter ( 4164): #14     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3717:5)
E/flutter ( 4164): #15     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2961:14)
E/flutter ( 4164): #16     MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4982:32)
E/flutter ( 4164): #17     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2961:14)
E/flutter ( 4164): #18     Element.updateChild (package:flutter/src/widgets/framework.dart:2764:12)
E/flutter ( 4164): #19     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3750:16)
E/flutter ( 4164): #20     Element.rebuild (package:flutter/src/widgets/framework.dart:3565:5)
E/flutter ( 4164): #21     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3722:5)
E/flutter ( 4164): #22     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3864:11)
E/flutter ( 4164): #23     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3717:5)
E/flutter ( 4164): #24     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2961:14)
E/flutter ( 4164): #25     Element.updateChild (package:flutter/src/widgets/framework.dart:2764:12)
E/flutter ( 4164): #26     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3750:16)
E/flutter ( 4164): #27     Element.rebuild (package:flutter/src/widgets/framework.dart:3565:5)
E/flutter ( 4164): #28     StatelessElement.update (package:flutter/src/widgets/framework.dart:3796:5)
E/flutter ( 4164): #29     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:15)
E/flutter ( 4164): #30     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4883:14)
E/flutter ( 4164): #31     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:15)
E/flutter ( 4164): #32     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4883:14)
E/flutter ( 4164): #33     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:15)
E/flutter ( 4164): #34     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4883:14)
E/flutter ( 4164): #35     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:15)
E/flutter ( 4164): #36     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3750:16)
E/flutter ( 4164): #37     Element.rebuild (package:flutter/src/widgets/framework.dart:3565:5)
E/flutter ( 4164): #38     StatefulElement.update (package:flutter/src/widgets/framework.dart:3894:5)
E/flutter ( 4164): #39     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:15)
E/flutter ( 4164): #40     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3750:16)
E/flutter ( 4164): #41     Element.rebuild (package:flutter/src/widgets/framework.dart:3565:5)
E/flutter ( 4164): #42     StatelessElement.update (package:flutter/src/widgets/framework.dart:3796:5)
E/flutter ( 4164): #43     Element.updateChil
```

## Steps to Reproduce
1. Open a page with a GoogleMaps widget
2. Open Flutter Performance tab
3. Click on Toggle Platform

**Comment by timbaert** [comment]
I encountered the same problem. @pedromassango , were you able to solve the problem?

**Comment by pedromassango** [comment]
Sorry @timbaert I did't found anything

**Comment by BondarenkoStas** [comment]
@pedromassango Please provide your `flutter doctor -v` output. Also please provide  a small self-contained app that demonstrates the problem to be sure to reproduce it correctly.
Do you encounter it using latest flutter stable and latest maps plugin?

**Comment by iapicca** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
  
Thanks for your contribution.
