### ISSUE TITLE
flutter doctor

### ISSUE THREAD

**Issue by GaryHos** [flutter/flutter#35981]
执行不了 flutter doctor 
Doctor summary (to see all details, run flutter doctor -v):

Oops; flutter has exited unexpectedly.
Sending crash report to Google.

log
Flutter crash report; please file at https://github.com/flutter/flutter/issues.

## command

flutter doctor

## exception

ArgumentError: Invalid argument(s): join(null, "Applications"): part 0 was null, but part 1 was not.

```
#0      _validateArgList (package:path/src/context.dart:1088:5)
#1      Context.join (package:path/src/context.dart:231:5)
#2      AndroidStudio._allMacOS (package:flutter_tools/src/android/android_studio.dart:203:29)
#3      AndroidStudio.allInstalled (package:flutter_tools/src/android/android_studio.dart:175:26)
#4      AndroidStudioValidator.allValidators (package:flutter_tools/src/android/android_studio_validator.dart:21:55)
#5      _DefaultDoctorValidatorsProvider.validators (package:flutter_tools/src/doctor.dart:88:51)
#6      Doctor.validators (package:flutter_tools/src/doctor.dart:144:46)
#7      Doctor.startValidatorTasks (package:flutter_tools/src/doctor.dart:151:39)
#8      Doctor.diagnose (package:flutter_tools/src/doctor.dart:223:41)
<asynchronous suspension>
#9      DoctorCommand.runCommand (package:flutter_tools/src/commands/doctor.dart:48:39)
<asynchronous suspension>
#10     FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:478:18)
<asynchronous suspension>
#11     FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:383:33)
<asynchronous suspension>
#12     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:29)
<asynchronous suspension>
#13     _rootRun (dart:async/zone.dart:1124:13)
#14     _CustomZone.run (dart:async/zone.dart:1021:19)
#15     _runZoned (dart:async/zone.dart:1516:10)
#16     runZoned (dart:async/zone.dart:1463:12)
#17     AppContext.run (package:flutter_tools/src/base/context.dart:152:18)
<asynchronous suspension>
#18     FlutterCommand.run (package:flutter_tools/src/runner/flutter_command.dart:375:20)
#19     CommandRunner.runCommand (package:args/command_runner.dart:197:27)
<asynchronous suspension>
#20     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:396:21)
<asynchronous suspension>
#21     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:29)
<asynchronous suspension>
#22     _rootRun (dart:async/zone.dart:1124:13)
#23     _CustomZone.run (dart:async/zone.dart:1021:19)
#24     _runZoned (dart:async/zone.dart:1516:10)
#25     runZoned (dart:async/zone.dart:1463:12)
#26     AppContext.run (package:flutter_tools/src/base/context.dart:152:18)
<asynchronous suspension>
#27     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:356:19)
<asynchronous suspension>
#28     CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:112:25)
#29     new Future.sync (dart:async/future.dart:224:31)
#30     CommandRunner.run (package:args/command_runner.dart:112:14)
#31     FlutterCommandRunner.run (package:flutter_tools/src/runner/flutter_command_runner.dart:242:18)
#32     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:62:22)
<asynchronous suspension>
#33     _rootRun (dart:async/zone.dart:1124:13)
#34     _CustomZone.run (dart:async/zone.dart:1021:19)
#35     _runZoned (dart:async/zone.dart:1516:10)
#36     runZoned (dart:async/zone.dart:1500:12)
#37     run.<anonymous closure> (package:flutter_tools/runner.dart:60:18)
<asynchronous suspension>
#38     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:29)
<asynchronous suspension>
#39     _rootRun (dart:async/zone.dart:1124:13)
#40     _CustomZone.run (dart:async/zone.dart:1021:19)
#41     _runZoned (dart:async/zone.dart:1516:10)
#42     runZoned (dart:async/zone.dart:1463:12)
#43     AppContext.run (package:flutter_tools/src/base/context.dart:152:18)
<asynchronous suspension>
#44     runInContext (package:flutter_tools/src/context_runner.dart:56:24)
<asynchronous suspension>
#45     run (package:flutter_tools/runner.dart:51:10)
#46     main (package:flutter_tools/executable.dart:62:9)
<asynchronous suspension>
#47     main (file:///b/s/w/ir/k/archive/flutter/packages/flutter_tools/bin/flutter_tools.dart:8:3)
#48     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:299:32)
#49     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:12)
```

## flutter doctor

```
[32m[✓][39m Flutter (Channel stable, v1.7.8+hotfix.3, on Mac OS X 10.14.4 18E226, locale
    zh-Hans-CN)
    [32m•[39m Flutter version 1.7.8+hotfix.3 at
      /Users/heguoqing/Documents/flutter/flutter
    [32m•[39m Framework revision b712a172f9 (2 days ago), 2019-07-09 13:14:38 -0700
    [32m•[39m Engine revision 54ad777fd2
    [32m•[39m Dart version 2.4.0

[31m[✗][39m Android toolchain - develop for Android devices
    [31m✗[39m Unable to locate Android SDK.
      Install Android Studio from:
      https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK
      components.
      (or visit https://flutter.dev/setup/#android-setup for detailed
      instructions).
      If the Android SDK has been installed to a custom location, set
      ANDROID_HOME to that location.
      You may also want to add it to your PATH environment variable.


[31m[✗][39m Xcode - develop for iOS and macOS
    [31m✗[39m Xcode installation is incomplete; a full installation is necessary for iOS
      development.
      Download at: https://developer.apple.com/xcode/download/
      Or install Xcode via the App Store.
      Once installed, run:
        sudo xcode-select --switch /Applications/Xcode.app/Contents/Developer
    [31m✗[39m CocoaPods not installed.
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin
        code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To install:
        brew install cocoapods
        pod setup

[31m[✗][39m iOS tools - develop for iOS devices
    [31m✗[39m libimobiledevice and ideviceinstaller are not installed. To install with
      Brew, run:
        brew update
        brew install --HEAD usbmuxd
        brew link usbmuxd
        brew install --HEAD libimobiledevice
        brew install ideviceinstaller
    [31m✗[39m ios-deploy not installed. To install:
        brew install ios-deploy

[33m![39m Doctor found issues in 3 categories.

**Comment by stuartmorgan** [comment]
Have you explicitly removed `HOME` from your environment?

**Comment by GaryHos** [comment]
> 您是否明确删除`HOME`了您的环境？

不太明白您的操作

**Comment by GaryHos** [comment]
重装了mac系统, 解决了这个不知道什么问题的问题
