### ISSUE TITLE
Flutter is crashing (Android SDK 23, emulator)

### ISSUE THREAD

**Issue by olostan** [flutter/flutter#3601]
Did fresh install on Mac OS 10.11, dart 1.16, Android emulator 6.0), when running any Flutter app, I get:
```
➢ flutter start --checked;flutter logs
Building APK in debug mode (android-x64)...
Warning: signing the APK using the debug keystore.
Built build/app.apk (9.0MB).
Installing app.apk on device.
Running lib/main.dart on Android SDK built for x86 64...
Showing Android SDK built for x86 64 logs:
--------- beginning of crash
F/DEBUG   :     #20 pc 000000000001ce55  /system/lib64/libc.so (__bionic_clone+53)
F/DEBUG   : 
F/DEBUG   : Tombstone written to: /data/tombstones/tombstone_04
--------- beginning of main
--------- beginning of system
W/ActivityManager:   Force finishing activity io.flutter.examples.HelloWorld/org.domokit.sky.shell.SkyActivity
W/ActivityManager: Exception thrown during pause
W/ActivityManager: android.os.DeadObjectException
W/ActivityManager: 	at android.os.BinderProxy.transactNative(Native Method)
W/ActivityManager: 	at android.os.BinderProxy.transact(Binder.java:503)
W/ActivityManager: 	at android.app.ApplicationThreadProxy.schedulePauseActivity(ApplicationThreadNative.java:727)
W/ActivityManager: 	at com.android.server.am.ActivityStack.startPausingLocked(ActivityStack.java:867)
W/ActivityManager: 	at com.android.server.am.ActivityStack.finishActivityLocked(ActivityStack.java:2907)
W/ActivityManager: 	at com.android.server.am.ActivityStack.finishTopRunningActivityLocked(ActivityStack.java:2763)
W/ActivityManager: 	at com.android.server.am.ActivityStackSupervisor.finishTopRunningActivityLocked(ActivityStackSupervisor.java:2755)
W/ActivityManager: 	at com.android.server.am.ActivityManagerService.handleAppCrashLocked(ActivityManagerService.java:11971)
W/ActivityManager: 	at com.android.server.am.ActivityManagerService.makeAppCrashingLocked(ActivityManagerService.java:11867)
W/ActivityManager: 	at com.android.server.am.ActivityManagerService.crashApplication(ActivityManagerService.java:12556)
W/ActivityManager: 	at com.android.server.am.ActivityManagerService.handleApplicationCrashInner(ActivityManagerService.java:12063)
W/ActivityManager: 	at com.android.server.am.NativeCrashListener$NativeCrashReporter.run(NativeCrashListener.java:86)
```

```
➢ flutter doctor
[✓] Flutter (on Mac OS, channel alpha)
    • Flutter at /Users/vshybanov/code/dart/flutter/flutter
    • Framework revision 731c590 (8 days ago), engine revision 284929b

[✓] Android toolchain - develop for Android devices (Android SDK 23.0.2)
    • Android SDK at /usr/local/opt/android-sdk
    • Platform android-23, build-tools 23.0.2
    • Java(TM) SE Runtime Environment (build 1.8.0_92-b14)

[✓] iOS toolchain - develop for iOS devices (Xcode 7.3)
    • XCode at /Applications/Xcode.app/Contents/Developer
    • Xcode 7.3, Build version 7D175

[✓] Atom - a lightweight development environment for Flutter
    • Atom installed; Flutter plugin version 0.2.2
```

**Comment by eseidelGoogle** [comment]
I believe we have all our emulator issues fixed these days, but I'd *love* to know if you're still hitting this?

Happy to investigate further if you are!

**Comment by olostan** [comment]
Actually I am still facing random crashes (mostly on iOS devices), but can't figure out exact reason. I'll open new issue if I'll get stack trace or any other details

**Comment by eseidelGoogle** [comment]
@olostan @tvolkert is in the process of fixing a known debug-only crash on iOS physical devices which may help you.

Any crashes you encounter we would *love* to hear about! :)

**Comment by tvolkert** [comment]
https://github.com/flutter/flutter/issues/4560

**Comment by olostan** [comment]
@eseidelGoogle yep, looks like exactly what I am observing (crashes during gallery is run for some time on iPhone)

**Comment by tvolkert** [comment]
@olostan this should be fixed on master now.
