### ISSUE TITLE
创建stepper 以后进入页面报错

### ISSUE THREAD

**Issue by lchaoge** [flutter/flutter#36039]
## Steps to code

```
child: Stepper(
                    currentStep: 0,
                    steps: [
                      Step(
                        title: Text('title1'),
                        content: Text('content1'),
                      ),
                      Step(
                        title: Text('title2'),
                        content: Text('content2')
                      ),
                      Step(
                        title: Text('title3'),
                        content: Text('content3')
                      )
                    ]
                )
```

## Logs
```
E/LIBSEC  (12957): firewall read failed or timeout
I/flutter (12957): ══╡ EXCEPTION CAUGHT BY RENDERING LIBRARY ╞═════════════════════════════════════════════════════════
I/flutter (12957): The following assertion was thrown during performLayout():
I/flutter (12957): 'package:flutter/src/rendering/viewport.dart': Failed assertion: line 1611 pos 16:
I/flutter (12957): 'constraints.hasBoundedWidth': is not true.
I/flutter (12957): Either the assertion indicates an error in the framework itself, or we should provide substantially
I/flutter (12957): more information in this error message to help you determine and fix the underlying cause.
I/flutter (12957): In either case, please report this assertion by filing a bug on GitHub:
I/flutter (12957):   https://github.com/flutter/flutter/issues/new?template=BUG.md
I/flutter (12957): When the exception was thrown, this was the stack:
I/flutter (12957): #2      RenderShrinkWrappingViewport.performLayout (package:flutter/src/rendering/viewport.dart:1611:16)
I/flutter (12957): #3      RenderObject.layout (package:flutter/src/rendering/object.dart:1619:7)
I/flutter (12957): #4      _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter (12957): #5      RenderObject.layout (package:flutter/src/rendering/object.dart:1619:7)
I/flutter (12957): #6      _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter (12957): #7      RenderObject.layout (package:flutter/src/rendering/object.dart:1619:7)
I/flutter (12957): #8      _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter (12957): #9      RenderObject.layout (package:flutter/src/rendering/object.dart:1619:7)
I/flutter (12957): #10     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter (12957): #11     RenderObject.layout (package:flutter/src/rendering/object.dart:1619:7)
I/flutter (12957): #12     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter (12957): #13     RenderObject.layout (package:flutter/src/rendering/object.dart:1619:7)
I/flutter (12957): #14     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter (12957): #15     RenderObject.layout (package:flutter/src/rendering/object.dart:1619:7)
I/flutter (12957): #16     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter (12957): #17     RenderObject.layout (package:flutter/src/rendering/object.dart:1619:7)
I/flutter (12957): #18     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter (12957): #19     RenderObject.layout (package:flutter/src/rendering/object.dart:1619:7)
I/flutter (12957): #20     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter (12957): #21     RenderObject.layout (package:flutter/src/rendering/object.dart:1619:7)
I/flutter (12957): #22     RenderFlex.performLayout (package:flutter/src/rendering/flex.dart:743:15)
I/flutter (12957): #23     RenderObject.layout (package:flutter/src/rendering/object.dart:1619:7)
I/flutter (12957): #24     RenderFlex.performLayout (package:flutter/src/rendering/flex.dart:743:15)
I/flutter (12957): #25     RenderObject.layout (package:flutter/src/rendering/object.dart:1619:7)
I/flutter (12957): #26     RenderPadding.performLayout (package:flutter/src/rendering/shifted_box.dart:206:11)
I/flutter (12957): #27     RenderObject.layout (package:flutter/src/rendering/object.dart:1619:7)
I/flutter (12957): #28     MultiChildLayoutDelegate.layoutChild (package:flutter/src/rendering/custom_layout.dart:142:11)
I/flutter (12957): #29     _ScaffoldLayout.performLayout (package:flutter/src/material/scaffold.dart:443:7)
I/flutter (12957): #30     MultiChildLayoutDelegate._callPerformLayout (package:flutter/src/rendering/custom_layout.dart:212:7)
I/flutter (12957): #31     RenderCustomMultiChildLayoutBox.performLayout (package:flutter/src/rendering/custom_layout.dart:356:14)
I/flutter (12957): #32     RenderObject.layout (package:flutter/src/rendering/object.dart:1619:7)
I/flutter (12957): #33     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter (12957): #34     RenderObject.layout (package:flutter/src/rendering/object.dart:1619:7)
I/flutter (12957): #35     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter (12957): #36     _RenderCustomClip.performLayout (package:flutter/src/rendering/proxy_box.dart:1214:11)
I/flutter (12957): #37     RenderObject.layout (package:flutter/src/rendering/object.dart:1619:7)
I/flutter (12957): #38     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter (12957): #39     RenderObject.layout (package:flutter/src/rendering/object.dart:1619:7)
I/flutter (12957): #40     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter (12957): #41     RenderObject.layout (package:flutter/src/rendering/object.dart:1619:7)
I/flutter (12957): #42     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter (12957): #43     RenderObject.layout (package:flutter/src/rendering/object.dart:1619:7)
I/flutter (12957): #44     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter (12957): #45     RenderObject.layout (package:flutter/src/rendering/object.dart:1619:7)
I/flutter (12957): #46     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter (12957): #47     RenderObject.layout (package:flutter/src/rendering/object.dart:1619:7)
I/flutter (12957): #48     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter (12957): #49     RenderObject.layout (package:flutter/src/rendering/object.dart:1619:7)
I/flutter (12957): #50     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter (12957): #51     RenderObject.layout (package:flutter/src/rendering/object.dart:1619:7)
I/flutter (12957): #52     RenderOffstage.performLayout (package:flutter/src/rendering/proxy_box.dart:3074:14)
I/flutter (12957): #53     RenderObject.layout (package:flutter/src/rendering/object.dart:1619:7)
I/flutter (12957): #54     RenderStack.performLayout (package:flutter/src/rendering/stack.dart:510:15)
I/flutter (12957): #55     RenderObject._layoutWithoutResize (package:flutter/src/rendering/object.dart:1496:7)
I/flutter (12957): #56     PipelineOwner.flushLayout (package:flutter/src/rendering/object.dart:765:18)
I/flutter (12957): #57     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding.drawFrame (package:flutter/src/rendering/binding.dart:346:19)
I/flutter (12957): #58     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding&WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:701:13)
I/flutter (12957): #59     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:285:5)
I/flutter (12957): #60     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1016:15)
I/flutter (12957): #61     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:958:9)
I/flutter (12957): #62     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:874:5)
I/flutter (12957): #66     _invoke (dart:ui/hooks.dart:236:10)
I/flutter (12957): #67     _drawFrame (dart:ui/hooks.dart:194:3)
I/flutter (12957): (elided 5 frames from class _AssertionError and package dart:async)
I/flutter (12957): The following RenderObject was being processed when the exception was fired: RenderShrinkWrappingViewport#c94ea relayoutBoundary=up13 NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE:
I/flutter (12957):   needs compositing
I/flutter (12957):   creator: ShrinkWrappingViewport ← IgnorePointer-[GlobalKey#bf5f8] ← Semantics ← Listener ←
I/flutter (12957):     _GestureSemantics ← RawGestureDetector-[LabeledGlobalKey<RawGestureDetectorState>#b4eef] ←
I/flutter (12957):     Listener ← _ScrollableScope ← _ScrollSemantics-[GlobalKey#1fb07] ← RepaintBoundary ← CustomPaint ←
I/flutter (12957):     RepaintBoundary ← ⋯
I/flutter (12957):   parentData: <none> (can use size)
I/flutter (12957):   constraints: BoxConstraints(unconstrained)
I/flutter (12957):   size: MISSING
I/flutter (12957):   axisDirection: down
I/flutter (12957):   crossAxisDirection: right
I/flutter (12957):   offset: ScrollPositionWithSingleContext#4eb5c(offset: 0.0, range: null..null, viewport: null,
I/flutter (12957):     ScrollableState, AlwaysScrollableScrollPhysics -> ClampingScrollPhysics, IdleScrollActivity#0e720,
I/flutter (12957):     ScrollDirection.idle)
I/flutter (12957): This RenderObject had the following descendants (showing up to depth 5):
I/flutter (12957):     child 0: RenderSliverPadding#fd4fb NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
I/flutter (12957):       child: RenderSliverList#cca70 NEEDS-LAYOUT NEEDS-PAINT
I/flutter (12957): ════════════════════════════════════════════════════════════════════════════════════════════════════
I/flutter (12957): Another exception was thrown: RenderBox was not laid out: RenderShrinkWrappingViewport#c94ea relayoutBoundary=up13 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
I/flutter (12957): Another exception was thrown: RenderBox was not laid out: RenderIgnorePointer#28bf2 relayoutBoundary=up12 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
I/flutter (12957): Another exception was thrown: RenderBox was not laid out: RenderSemanticsAnnotations#4177d relayoutBoundary=up11 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
I/flutter (12957): Another exception was thrown: RenderBox was not laid out: RenderPointerListener#923b2 relayoutBoundary=up10 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
I/flutter (12957): Another exception was thrown: RenderBox was not laid out: RenderSemanticsGestureHandler#945ca relayoutBoundary=up9 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
I/flutter (12957): Another exception was thrown: RenderBox was not laid out: RenderPointerListener#2e20b relayoutBoundary=up8 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
I/flutter (12957): Another exception was thrown: RenderBox was not laid out: _RenderScrollSemantics#41279 relayoutBoundary=up7 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
I/flutter (12957): Another exception was thrown: RenderBox was not laid out: RenderRepaintBoundary#9339a relayoutBoundary=up6 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
I/flutter (12957): Another exception was thrown: RenderBox was not laid out: RenderCustomPaint#92708 relayoutBoundary=up5
NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
I/flutter (12957): Another exception was thrown: RenderBox was not laid out: RenderRepaintBoundary#4b927 relayoutBoundary=up4 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
I/flutter (12957): Another exception was thrown: RenderBox was not laid out: RenderFlex#03b90 relayoutBoundary=up3 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
I/flutter (12957): Another exception was thrown: RenderBox was not laid out: RenderFlex#e4466 relayoutBoundary=up2 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
I/flutter (12957): Another exception was thrown: RenderBox was not laid out: RenderPadding#c102d relayoutBoundary=up1 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
I/flutter (12957): Another exception was thrown: NoSuchMethodError: The method '>' was called on null.
```

**Comment by LongCatIsLooong** [comment]
The stack trace doesn't seem to have much to do with stepper. Your viewport's width is not bounded. A similar question on stackoverflow: https://stackoverflow.com/questions/54020068/constraints-hasboundedwidth-is-not-true. Does that fix your problem?

**Comment by VladyslavBondarenko** [comment]
@lchaoge 
I hope you've solved the issue.
Could everyone who still has this problem please file a new issue with the exact descriptions what happens, logs and the output of `flutter doctor -v` please.
