### ISSUE TITLE
[android_alarm_manager] stop working after flutter upgrade

### ISSUE THREAD

**Issue by hgouveia** [flutter/flutter#36059]
After upgrade Flutter yesterday (2019-07-11), android_alarm_manager (0.4.1+6)  crashed my App as soon is opened ,  not useful information was reported on logcat , just that app crashed

but i moved the initialization when pressing a button, still crashing but i got this Callstack:

```log
E/AndroidRuntime(21658): java.lang.RuntimeException: An error occurred while executing doInBackground()
E/AndroidRuntime(21658): 	at android.os.AsyncTask$3.done(AsyncTask.java:366)
E/AndroidRuntime(21658): 	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383)
E/AndroidRuntime(21658): 	at java.util.concurrent.FutureTask.setException(FutureTask.java:252)
E/AndroidRuntime(21658): 	at java.util.concurrent.FutureTask.run(FutureTask.java:271)
E/AndroidRuntime(21658): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
E/AndroidRuntime(21658): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
E/AndroidRuntime(21658): 	at java.lang.Thread.run(Thread.java:784)
E/AndroidRuntime(21658): Caused by: java.lang.RuntimeException: Methods marked with @UiThread must be executed on the main thread. Current thread: AsyncTask #5
E/AndroidRuntime(21658): 	at io.flutter.embedding.engine.FlutterJNI.ensureRunningOnMainThread(FlutterJNI.java:794)
E/AndroidRuntime(21658): 	at io.flutter.embedding.engine.FlutterJNI.dispatchPlatformMessage(FlutterJNI.java:684)
E/AndroidRuntime(21658): 	at io.flutter.embedding.engine.dart.DartMessenger.send(DartMessenger.java:80)
E/AndroidRuntime(21658): 	at io.flutter.embedding.engine.dart.DartExecutor.send(DartExecutor.java:189)
E/AndroidRuntime(21658): 	at io.flutter.view.FlutterNativeView.send(FlutterNativeView.java:155)
E/AndroidRuntime(21658): 	at io.flutter.plugin.common.MethodChannel.invokeMethod(MethodChannel.java:98)
E/AndroidRuntime(21658): 	at io.flutter.plugin.common.MethodChannel.invokeMethod(MethodChannel.java:84)
E/AndroidRuntime(21658): 	at io.flutter.plugins.androidalarmmanager.AlarmService.invokeCallbackDispatcher(AlarmService.java:170)
E/AndroidRuntime(21658): 	at io.flutter.plugins.androidalarmmanager.AlarmService.onHandleWork(AlarmService.java:151)
E/AndroidRuntime(21658): 	at androidx.core.app.JobIntentService$CommandProcessor.doInBackground(JobIntentService.java:392)
E/AndroidRuntime(21658): 	at androidx.core.app.JobIntentService$CommandProcessor.doInBackground(JobIntentService.java:383)
E/AndroidRuntime(21658): 	at android.os.AsyncTask$2.call(AsyncTask.java:345)
E/AndroidRuntime(21658): 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
E/AndroidRuntime(21658): 	... 3 more
```

> Flutter doctor
```log
[v] Flutter (Channel stable, v1.7.8+hotfix.3, on Microsoft Windows [Version 10.0.17763.557], locale en-US)
    • Flutter version 1.7.8+hotfix.3 at G:\data\SDKs\flutter
    • Framework revision b712a172f9 (3 days ago), 2019-07-09 13:14:38 -0700
    • Engine revision 54ad777fd2
    • Dart version 2.4.0


[v] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at G:\data\Programs\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = G:\data\Programs\Android\sdk
    • Java binary at: C:\Program Files\Java\jdk1.8.0_162\bin\java
    • Java version Java(TM) SE Runtime Environment (build 1.8.0_162-b12)
    • All Android licenses accepted.

[v] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[!] Android Studio (not installed)
```

> Application.java
```java
package com.example.helloworld;

import io.flutter.app.FlutterApplication;
import io.flutter.plugin.common.PluginRegistry;
import io.flutter.plugin.common.PluginRegistry.PluginRegistrantCallback;
import io.flutter.plugins.GeneratedPluginRegistrant;
import io.flutter.plugins.androidalarmmanager.AlarmService;

public class Application extends FlutterApplication implements PluginRegistrantCallback {
  @Override
  public void onCreate() {
    super.onCreate();
    AlarmService.setPluginRegistrant(this);
  }

  @Override
  public void registerWith(PluginRegistry registry) {
    GeneratedPluginRegistrant.registerWith(registry);
  }
}
```
>MainActivity.java
```java
package com.example.helloworld;

import android.os.Bundle;
import io.flutter.app.FlutterActivity;
import io.flutter.plugins.GeneratedPluginRegistrant;

public class MainActivity extends FlutterActivity {
	public static final String TAG = "LockerMainActivity";
  @Override
  protected void onCreate(Bundle savedInstanceState) {
    super.onCreate(savedInstanceState);
    GeneratedPluginRegistrant.registerWith(this);
  }
}
```
>AndroidManifest.xml
```xml
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    package="com.example.helloworld">

    <!-- The INTERNET permission is required for development. Specifically,
         flutter needs it to communicate with the running application
         to allow setting breakpoints, to provide hot reload, etc.
    -->
    <uses-permission android:name="android.permission.INTERNET"/>
    <uses-permission android:name="android.permission.RECEIVE_BOOT_COMPLETED"/>
    <uses-permission android:name="android.permission.WAKE_LOCK"/>


    <!-- io.flutter.app.FlutterApplication is an android.app.Application that
         calls FlutterMain.startInitialization(this); in its onCreate method.
         In most cases you can leave this as-is, but you if you want to provide
         additional functionality it is fine to subclass or reimplement
         FlutterApplication and put your custom class here. -->
    <application
        android:name=".Application"
        android:label="hello_world"
        android:icon="@mipmap/ic_launcher">
        <activity
            android:name=".MainActivity"
            android:launchMode="singleTop"
            android:theme="@style/LaunchTheme"
            android:configChanges="orientation|keyboardHidden|keyboard|screenSize|locale|layoutDirection|fontScale|screenLayout|density"
            android:hardwareAccelerated="true"
            android:windowSoftInputMode="adjustResize">
            <!-- This keeps the window background of the activity showing
                 until Flutter renders its first frame. It can be removed if
                 there is no splash screen (such as the default splash screen
                 defined in @style/LaunchTheme). -->
            <meta-data
                android:name="io.flutter.app.android.SplashScreenUntilFirstFrame"
                android:value="true" />
            <intent-filter>
                <action android:name="android.intent.action.MAIN"/>
                <category android:name="android.intent.category.LAUNCHER"/>
            </intent-filter>
        </activity>

        <!-- android_alarm_manager -->
        <service
            android:name="io.flutter.plugins.androidalarmmanager.AlarmService"
            android:permission="android.permission.BIND_JOB_SERVICE"
            android:exported="false"/>
        <receiver
            android:name="io.flutter.plugins.androidalarmmanager.AlarmBroadcastReceiver"
            android:exported="false"/>
        <receiver
            android:name="io.flutter.plugins.androidalarmmanager.RebootBroadcastReceiver"
            android:enabled="false">
            <intent-filter>
                <action android:name="android.intent.action.BOOT_COMPLETED"></action>
            </intent-filter>
        </receiver>
    </application>
</manifest>
````
> main.dart
```dart
import 'dart:isolate';
import 'package:flutter/material.dart';
import 'package:android_alarm_manager/android_alarm_manager.dart';

import 'ui/home.dart';

void printHello() {
  final DateTime now = DateTime.now();
  final int isolateId = Isolate.current.hashCode;
  print("[$now] Hello, world! isolate=${isolateId} function='$printHello'");
}

main() async {
  final int helloAlarmID = 0;
  await AndroidAlarmManager.initialize(); // <<-------- MAKE IT CRASH
  runApp(MyApp());
  await AndroidAlarmManager.periodic(const Duration(minutes: 1), helloAlarmID, printHello);
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
        title: 'MyApp',
        theme: ThemeData(
          primarySwatch: Colors.purple,
        ),
        routes: {
          '/home': (_) => HomeScreen(),
        },
        home: HomeScreen();
  }
}
```

**Comment by MichealReed** [comment]
Those of us using threads other than the UI are still battling for a fix in the issue below. In the mean time you can revert to a previous flutter version. I used v1.5.3.

https://github.com/flutter/flutter/issues/34993

**Comment by amirh** [comment]
I believe this is a duplicate of https://github.com/flutter/flutter/issues/32976 which was fixed by https://github.com/flutter/plugins/pull/1641 the fix is available starting version 0.4.1+7 of the plugin.

Can you try with the latest version of the plugin?

**Comment by hgouveia** [comment]
@amirh Hello, i've tried already with `0.4.1+7` and `0.4.1+8` , and the issue still persists

**Comment by hgouveia** [comment]
@amirh  i did a new test, and it seems to be working for me now, i will close it , and open it in the future if happend again, thanks

**Comment by Udit-singh** [comment]
@hgouveia @amirh The same issue is still happening in `Flutter v1.22.5 Stable channel`
