### ISSUE TITLE
InvokeMethod issue on Android side, MethodChannel and EventChannel must be executed on the main thread 

### ISSUE THREAD

**Issue by BlazJeger** [flutter/flutter#36051]
## Steps to Reproduce

Currently developing an App in flutter which is communicating with Android through EventChannels and MethodChannels, 
got some problem since I updated flutter from 1.5.4 to 1.7.8. So basically my workflow follows this steps.
1. On android side I am waiting for detection of sensor
2. On detection i read it and invoke a method from Flutter
3. Flutter generates a string based on argument, which he returns over method channel
4. When i get the String back on Android side, I use that String and run other methods
5. I send a variable on EventStream sink back to flutter
6. Flutter listens to stream and displays the content

And there are a couple of issues, your invoke method needs to run on MainThread, same goes for pushing variables on EventSink. **Is this a bug in the new version or you just want us to do with a single thread?** Second issue i found was even in the previous version, I simply don't know how and didn't find anything on the internet or your docs about **awaiting results of invokeMethod on Android side**, in flutter you can simply create a Future method and await it, but in Kotlin i don't know how (Currently time racing with Thread.Sleep(50ms)). Any suggestions? Am i doing something wrong? 
**I am doing all of this on MainActivity, is this the source of problem?**
I tried to wrap it inside runOnUiThread, but it freezes my UI for the doing, would like to work it as async. 
**What are your words on that, what direction will you go next?**
## Logs

Setting methodCallHandler on Flutter:

  _channel.setMethodCallHandler(_checkPassword);

![image](https://user-images.githubusercontent.com/43069274/61110636-fcc7bf00-a487-11e9-8e48-bd5e139c2721.png)

Invoking method on Android:

![image](https://user-images.githubusercontent.com/43069274/61108988-0c450900-a484-11e9-8557-cdde5e0b6aa9.png)

Log error after update (Same for Invoke method and EventChannel):

W/Binder: Caught a RuntimeException from the binder stub implementation.
    java.lang.RuntimeException: Methods marked with @UiThread must be executed on the main thread. Current thread: Binder:10473_3
        at io.flutter.embedding.engine.FlutterJNI.ensureRunningOnMainThread(FlutterJNI.java:794)
        at io.flutter.embedding.engine.FlutterJNI.dispatchPlatformMessage(FlutterJNI.java:684)
        at io.flutter.embedding.engine.dart.DartMessenger.send(DartMessenger.java:80)
        at io.flutter.embedding.engine.dart.DartExecutor.send(DartExecutor.java:189)
        at io.flutter.view.FlutterNativeView.send(FlutterNativeView.java:155)
        at io.flutter.view.FlutterView.send(FlutterView.java:750)
        at io.flutter.view.FlutterView.send(FlutterView.java:740)
        at io.flutter.plugin.common.EventChannel$IncomingStreamRequestHandler$EventSinkImplementation.error(EventChannel.java:235)
        at com.tracklegit.mobile.MainActivity.onTagDiscovered(MainActivity.kt:145)
        at android.nfc.NfcActivityManager.onTagDiscovered(NfcActivityManager.java:602)
        at android.nfc.IAppCallback$Stub.onTransact(IAppCallback.java:83)
        at android.os.Binder.execTransact(Binder.java:739)
```
```

[√] Flutter (Channel stable, v1.7.8+hotfix.3, on Microsoft Windows [Version 10.0.17763.615], locale sl-SI)
    • Flutter version 1.7.8+hotfix.3 at D:\Games\flutter
    • Framework revision b712a172f9 (2 days ago), 2019-07-09 13:14:38 -0700
    • Engine revision 54ad777fd2
    • Dart version 2.4.0

[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at C:\Users\blazj\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
    • All Android licenses accepted.

[√] Android Studio (version 3.4)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 37.0.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

[√] VS Code (version 1.36.1)
    • VS Code at C:\Users\blazj\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.2.0

[√] Connected device (1 available)
    • SM G950F • 988a5c344849314e57 • android-arm64 • Android 9 (API 28)

• No issues found!
```
```

**Comment by ioaccept** [comment]
I have the same problem. Does one have an answer?

**Comment by BondarenkoStas** [comment]
@BlazJeger Is it the same using current flutter stable?
Also, please do not include screenshots of code. This makes it extremely tedious to reproduce the issue, as we would have to manually transcribe your example. If you want to highlight syntax, you can wrap it into triple backticks with language in the beginning like
````dart
some code
````

**Comment by jamesncl** [comment]
I'm not an expert on these things so take with a pinch of salt, but seeing as there isn't much response to this old issue, here are some suggestions:

**Is this a bug in the new version or you just want us to do with a single thread?** 

I think this is deliberate. It makes sense that you need to invokeMethod on the Android side using the UI thread, because it's the UI thread on the Dart side which is listening

**I simply don't know how and didn't find anything on the internet or your docs about awaiting results of invokeMethod on Android side, in flutter you can simply create a Future method and await it, but in Kotlin i don't know how (Currently time racing with Thread.Sleep(50ms)). Any suggestions?**

Don't use Thread.sleep. I can think of two strategies:

- Don't try to await on the Android side. Instead, start whatever process you are doing on a separate thread (e.g. using AsyncTask or Kotlin's coroutines) and just return a boolean to indicate to the Flutter side that the request to start the task was successful. When the task is completed, call invokeMethod from the Android to the Dart / Flutter side with the result of your task.

- Kotlin appears to have [support for async / await](https://kotlinlang.org/docs/reference/coroutines/composing-suspending-functions.html) although I haven't used these myself, which might be easier

I am doing all of this on MainActivity, is this the source of problem?
- Not necessarily, that's what I'm doing and it seems to work great:

```
const val METHOD_CHANNEL_BILLING = "com.example/billing"

class MainActivity: FlutterActivity() {

  companion object {
    lateinit var methodChannelBilling: MethodChannel
  }
 
  private lateinit var methodHandlerBilling: MethodHandlerBilling

  override fun onCreate(savedInstanceState: Bundle?) {
    super.onCreate(savedInstanceState)
    GeneratedPluginRegistrant.registerWith(this)

    methodChannelBilling = MethodChannel(flutterView, METHOD_CHANNEL_BILLING)
    methodHandlerBilling = MethodHandlerBilling()
    methodChannelBilling.setMethodCallHandler(methodHandlerBilling)
  }
}

class MethodHandlerBilling() : MethodChannel.MethodCallHandler {
    override fun onMethodCall(call: MethodCall, result: MethodChannel.Result) {
        // Note: this method is invoked on the main thread.
        when (call.method) {
            "queryProductsForSale" -> {
               ...
            }
            else -> {
                result.notImplemented()
            }
        }
    }
}
```

**Comment by rafaelsetragni** [comment]
```
abstract class Payload {

  // optimizes future cast
  Type type;
  String actionButtonPressed;

  @mustCallSuper
  Payload(){
    type = runtimeType;
  }

  @mustCallSuper
  Map<String, String> toMap() => ({ 'type': runtimeType.toString() });

  Payload fromMap(Map<String, dynamic> receivedPayload){
    this.actionButtonPressed = receivedPayload['action_key'];
    return this;
  }
}
```
**Please, its not finished yet**. The code is not intuitive enough. But you can test the example code and see the polimorfism working on payload.

Commit differences bellow:
https://github.com/rafaelsetragni/flutter_local_notifications/commit/2e95146717b707ad1011cb419de0c68f3dd7edbe

**Comment by Garciconx** [comment]
> ## Steps to Reproduce
> Currently developing an App in flutter which is communicating with Android through EventChannels and MethodChannels,
> got some problem since I updated flutter from 1.5.4 to 1.7.8. So basically my workflow follows this steps.
> 
> 1. On android side I am waiting for detection of sensor
> 2. On detection i read it and invoke a method from Flutter
> 3. Flutter generates a string based on argument, which he returns over method channel
> 4. When i get the String back on Android side, I use that String and run other methods
> 5. I send a variable on EventStream sink back to flutter
> 6. Flutter listens to stream and displays the content
> 
> And there are a couple of issues, your invoke method needs to run on MainThread, same goes for pushing variables on EventSink. **Is this a bug in the new version or you just want us to do with a single thread?** Second issue i found was even in the previous version, I simply don't know how and didn't find anything on the internet or your docs about **awaiting results of invokeMethod on Android side**, in flutter you can simply create a Future method and await it, but in Kotlin i don't know how (Currently time racing with Thread.Sleep(50ms)). Any suggestions? Am i doing something wrong?
> **I am doing all of this on MainActivity, is this the source of problem?**
> I tried to wrap it inside runOnUiThread, but it freezes my UI for the doing, would like to work it as async.
> **What are your words on that, what direction will you go next?**
> 
> ## Logs
> Setting methodCallHandler on Flutter:
> 
> _channel.setMethodCallHandler(_checkPassword);
> 
> ![image](https://user-images.githubusercontent.com/43069274/61110636-fcc7bf00-a487-11e9-8e48-bd5e139c2721.png)
> 
> Invoking method on Android:
> 
> ![image](https://user-images.githubusercontent.com/43069274/61108988-0c450900-a484-11e9-8557-cdde5e0b6aa9.png)
> 
> Log error after update (Same for Invoke method and EventChannel):
> 
> ```
> W/Binder: Caught a RuntimeException from the binder stub implementation.
>     java.lang.RuntimeException: Methods marked with @UiThread must be executed on the main thread. Current thread: Binder:10473_3
>         at io.flutter.embedding.engine.FlutterJNI.ensureRunningOnMainThread(FlutterJNI.java:794)
>         at io.flutter.embedding.engine.FlutterJNI.dispatchPlatformMessage(FlutterJNI.java:684)
>         at io.flutter.embedding.engine.dart.DartMessenger.send(DartMessenger.java:80)
>         at io.flutter.embedding.engine.dart.DartExecutor.send(DartExecutor.java:189)
>         at io.flutter.view.FlutterNativeView.send(FlutterNativeView.java:155)
>         at io.flutter.view.FlutterView.send(FlutterView.java:750)
>         at io.flutter.view.FlutterView.send(FlutterView.java:740)
>         at io.flutter.plugin.common.EventChannel$IncomingStreamRequestHandler$EventSinkImplementation.error(EventChannel.java:235)
>         at com.tracklegit.mobile.MainActivity.onTagDiscovered(MainActivity.kt:145)
>         at android.nfc.NfcActivityManager.onTagDiscovered(NfcActivityManager.java:602)
>         at android.nfc.IAppCallback$Stub.onTransact(IAppCallback.java:83)
>         at android.os.Binder.execTransact(Binder.java:739)
> ```
> 
> ```
> 
> 
> [√] Flutter (Channel stable, v1.7.8+hotfix.3, on Microsoft Windows [Version 10.0.17763.615], locale sl-SI)
>     • Flutter version 1.7.8+hotfix.3 at D:\Games\flutter
>     • Framework revision b712a172f9 (2 days ago), 2019-07-09 13:14:38 -0700
>     • Engine revision 54ad777fd2
>     • Dart version 2.4.0
> 
> [√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
>     • Android SDK at C:\Users\blazj\AppData\Local\Android\sdk
>     • Android NDK location not configured (optional; useful for native profiling support)
>     • Platform android-28, build-tools 28.0.3
>     • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
>     • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
>     • All Android licenses accepted.
> 
> [√] Android Studio (version 3.4)
>     • Android Studio at C:\Program Files\Android\Android Studio
>     • Flutter plugin version 37.0.1
>     • Dart plugin version 183.6270
>     • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
> 
> [√] VS Code (version 1.36.1)
>     • VS Code at C:\Users\blazj\AppData\Local\Programs\Microsoft VS Code
>     • Flutter extension version 3.2.0
> 
> [√] Connected device (1 available)
>     • SM G950F • 988a5c344849314e57 • android-arm64 • Android 9 (API 28)
> 
> • No issues found!
> ```

i have the same issue!

**Comment by kf6gpe** [comment]
I'm not sure where to route this one; so labeling.

**Comment by marcosmko** [comment]
I just had this problem (v1.12.13+hotfix.9), what I did was force executing the `invokeMethod` on main thread.

```java
new Handler(Looper.getMainLooper()).post(new Runnable() {
    @Override
    public void run() {
        channel.invokeMethod( ... );
    }
});
```

In your case, I suggest you invoke another method in your ```success``` response to continue processing.

Hope it helps!!

**Comment by kinex** [comment]
To wait for the `invokeMethod` call from Kotlin to Dart to finish before continuing execution in the original thread, you can use `CompletableDeferred`. Example:

```kotlin
val deferred = CompletableDeferred<Boolean>()
CoroutineScope(Dispatchers.Main).launch {
    channel?.invokeMethod("name", args, object : MethodChannel.Result {
        override fun success(result: Any?) {
            deferred.complete(true)
        }
    
        override fun error(code: String?, msg: String?, details: Any?) {
            deferred.complete(false)
        }
    
        override fun notImplemented() {
            deferred.complete(false)
        }
    })
}
val result = deferred.await()
```

**Comment by heqingbao** [comment]
```kotlin
Handler(Looper.getMainLooper()).post {
    channel.invokeMethod( ... )
}
```

**Comment by fernando-s97** [comment]
```kotlin
runOnUiThread { channel.invokeMethod( ... ) }
```
