### ISSUE TITLE
Flutter not working after upgrading

### ISSUE THREAD

**Issue by wmorrison1967** [flutter/flutter#36146]
I upgraded to:
Flutter:1.7.8+hotfix.3
Dart: 2.4

No issues reported at the end of the upgrade.  Suddenly my project cannot build.  I decided to create a new project and tried to build the default flutter project.  I got the same error:
```
Launching lib/main.dart on SM J701M in debug mode...
Built build/app/outputs/apk/debug/app-debug.apk.
Security exception: Permission Denial: forceStopPackage() from pid=10286, uid=2000 requires android.permission.FORCE_STOP_PACKAGES

java.lang.SecurityException: Permission Denial: forceStopPackage() from pid=10286, uid=2000 requires android.permission.FORCE_STOP_PACKAGES
	at com.android.server.am.ActivityManagerService.forceStopPackage(ActivityManagerService.java:8748)
	at com.android.server.am.ActivityManagerShellCommand.runForceStop(ActivityManagerShellCommand.java:967)
	at com.android.server.am.ActivityManagerShellCommand.onCommand(ActivityManagerShellCommand.java:197)
	at android.os.ShellCommand.exec(ShellCommand.java:103)
	at com.android.server.am.ActivityManagerService.onShellCommand(ActivityManagerService.java:20320)
	at android.os.Binder.shellCommand(Binder.java:642)
	at android.os.Binder.onTransact(Binder.java:540)
	at android.app.IActivityManager$Stub.onTransact(IActivityManager.java:3442)
	at com.android.server.am.ActivityManagerService.onTransact(ActivityManagerService.java:4181)
	at android.os.Binder.execTransact(Binder.java:739)
Error: ADB exited with exit code 1
Performing Streamed Install

adb: failed to install /Users/wilfordmorrison/testnew/build/app/outputs/apk/app.apk: Security exception: Permission Denial: runInstallCreate from pm command asks to run as user -1 but is calling from user 0; this requires android.permission.INTERACT_ACROSS_USERS_FULL

java.lang.SecurityException: Permission Denial: runInstallCreate from pm command asks to run as user -1 but is calling from user 0; this requires android.permission.INTERACT_ACROSS_USERS_FULL
	at com.android.server.am.UserController.handleIncomingUser(UserController.java:1827)
	at com.android.server.am.ActivityManagerService.handleIncomingUser(ActivityManagerService.java:25069)
	at android.app.ActivityManager.handleIncomingUser(ActivityManager.java:4848)
	at com.android.server.pm.PackageManagerShellCommand.translateUserId(PackageManagerShellCommand.java:2402)
	at com.android.server.pm.PackageManagerShellCommand.doCreateSession(PackageManagerShellCommand.java:2408)
	at com.android.server.pm.PackageManagerShellCommand.runInstall(PackageManagerShellCommand.java:907)
	at com.android.server.pm.PackageManagerShellCommand.onCommand(Pa
Error launching application on SM J701M.
Exited (sigterm)
```
I added the permission stated above but same error.  Now I am totally lost.  For context the ios version of the default app works.

Regards,
Will

**Comment by ClaudineiOlSantos** [comment]
I have same issue.

**Comment by wmorrison1967** [comment]
The fix is to turn off usb debugging on the device.  Then reboot it.  Then turn if back on again.

**Comment by BondarenkoStas** [comment]
@wmorrison1967 Cool, then I think it's safe to close the issue. If you have any updates or encounter it again, please don't hesitate to comment and I will re-open it.
