### ISSUE TITLE
[IOS]Dart snapshot generator failed with exit code -6  Unexpected object (Class with illegal cid, full-aot)

### ISSUE THREAD

**Issue by tango5614** [flutter/flutter#36155]
I get this error when trying to build an IOS app in release mode.
<pre>
<code>
   BUILD TARGET Runner OF PROJECT Runner WITH CONFIGURATION Release ===
   Building AOT snapshot in release mode (ios-release)...
   Unexpected object (Class with illegal cid, full-aot): 0x10e48e471 Library:'dart:collection' Class:
   _CompactLinkedHashSet@3220832
    Dart snapshot generator failed with exit code -6
    Building AOT snapshot in release mode (ios-release)...              4.0s
    Built to build/aot/.
    Snapshotting (IOSArch.arm64) exited with non-zero exit code: -6
    cp: build/aot/App.framework: No such file or directory
    error: cannot parse the debug map for 'build/aot/App.framework/App': No such file or directory
    Failed to generate debug symbols (dSYM) file for build/aot/App.framework/App.
</code>
</pre>
(part of) the log with -v options
<pre>
<code>
             [ +882 ms] Building AOT snapshot in release mode (ios-release)...
               [   +5 ms] Compiling Dart to kernel: /Users/wangwenjie/project/flutter_aww/lib/main.dart
               [ +804 ms] Skipping kernel compilation. Fingerprint match.
               [  +11 ms] executing: /usr/bin/arch -x86_64
               /usr/local/flutter/bin/cache/artifacts/engine/ios-release/gen_snapshot --causal_async_stacks
               --deterministic --snapshot_kind=app-aot-assembly
--assembly=build/aot/arm64/snapshot_assembly.S
               build/aot/app.dill
               [+2845 ms] Unexpected object (Class with illegal cid, full-aot): 0x107d0e471
Library:'dart:collection'
               Class: _CompactLinkedHashSet@3220832
               [   +8 ms] Dart snapshot generator failed with exit code -6
               [   +9 ms] Building AOT snapshot in release mode (ios-release)... (completed in 3.7s)
               [        ] Building AOT snapshot in release mode (ios-release)... (completed in 3.7s)
               [        ] Built to build/aot/.
               [   +1 ms] "flutter aot" took 4,924ms.
               [        ] "flutter aot" took 4,924ms.
               [   +1 ms] Snapshotting (IOSArch.arm64) exited with non-zero exit code: -6
               ♦ cp -r -- build/aot/App.framework /Users/wangwenjie/project/flutter_aww/ios/Flutter
               cp: build/aot/App.framework: No such file or directory
               ♦ mkdir -p -- build/dSYMs.noindex
               ♦ xcrun dsymutil -o build/dSYMs.noindex/App.framework.dSYM build/aot/App.framework/App
               error: cannot parse the debug map for 'build/aot/App.framework/App': No such file or
directory
               Failed to generate debug symbols (dSYM) file for build/aot/App.framework/App.

[  +44 ms] "flutter ios" took 17,367ms.
[        ] "flutter ios" took 17,367ms.
Encountered error while building for device.

#0      throwToolExit (package:flutter_tools/src/base/common.dart:28:3)
#1      BuildIOSCommand.runCommand (package:flutter_tools/src/commands/build_ios.dart:94:7)
<asynchronous suspension>
#2      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:478:18)
<asynchronous suspension>
#3      FlutterCommand.run.<anonymous closure>
(package:flutter_tools/src/runner/flutter_command.dart:383:33)
<asynchronous suspension>
#4      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:29)
<asynchronous suspension>
#5      _rootRun (dart:async/zone.dart:1124:13)
#6      _CustomZone.run (dart:async/zone.dart:1021:19)
#7      _runZoned (dart:async/zone.dart:1516:10)
#8      runZoned (dart:async/zone.dart:1463:12)
#9      AppContext.run (package:flutter_tools/src/base/context.dart:152:18)
<asynchronous suspension>
#10     FlutterCommand.run (package:flutter_tools/src/runner/flutter_command.dart:375:20)
#11     CommandRunner.runCommand (package:args/command_runner.dart:197:27)
<asynchronous suspension>
#12     FlutterCommandRunner.runCommand.<anonymous closure>
(package:flutter_tools/src/runner/flutter_command_runner.dart:396:21)
<asynchronous suspension>
#13     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:29)
<asynchronous suspension>
#14     _rootRun (dart:async/zone.dart:1124:13)
#15     _CustomZone.run (dart:async/zone.dart:1021:19)
#16     _runZoned (dart:async/zone.dart:1516:10)
#17     runZoned (dart:async/zone.dart:1463:12)
#18     AppContext.run (package:flutter_tools/src/base/context.dart:152:18)
<asynchronous suspension>
#19     FlutterCommandRunner.runCommand
(package:flutter_tools/src/runner/flutter_command_runner.dart:356:19)
<asynchronous suspension>
#20     CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:112:25)
#21     new Future.sync (dart:async/future.dart:224:31)
#22     CommandRunner.run (package:args/command_runner.dart:112:14)
#23     FlutterCommandRunner.run (package:flutter_tools/src/runner/flutter_command_runner.dart:242:18)
#24     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:62:22)
<asynchronous suspension>
#25     _rootRun (dart:async/zone.dart:1124:13)
#26     _CustomZone.run (dart:async/zone.dart:1021:19)
#27     _runZoned (dart:async/zone.dart:1516:10)
#28     runZoned (dart:async/zone.dart:1500:12)
#29     run.<anonymous closure> (package:flutter_tools/runner.dart:60:18)
<asynchronous suspension>
#30     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:29)
<asynchronous suspension>
#31     _rootRun (dart:async/zone.dart:1124:13)
#32     _CustomZone.run (dart:async/zone.dart:1021:19)
#33     _runZoned (dart:async/zone.dart:1516:10)
#34     runZoned (dart:async/zone.dart:1463:12)
#35     AppContext.run (package:flutter_tools/src/base/context.dart:152:18)
<asynchronous suspension>
#36     runInContext (package:flutter_tools/src/context_runner.dart:56:24)
<asynchronous suspension>
#37     run (package:flutter_tools/runner.dart:51:10)
#38     main (package:flutter_tools/executable.dart:62:9)
<asynchronous suspension>
#39     main (file:///usr/local/flutter/packages/flutter_tools/bin/flutter_tools.dart:8:3)
#40     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:299:32)
#41     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:12)
</code>
</pre>

And the output of `flutter doctor` command.Although I'm pretty sure my environment is OK because I can successfully build an empty project.
<pre>
<code>
Doctor summary (to see all details, run flutter doctor -v):
[!] Flutter (Channel stable, v1.7.8+hotfix.3, on Mac OS X 10.15 19A487l, locale zh-Hans-CN)
    ✗ Downloaded executables cannot execute on host.
      See https://github.com/flutter/flutter/issues/6207 for more information

[!] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    ✗ Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses
[✓] Xcode - develop for iOS and macOS (Xcode 10.2.1)
[✓] iOS tools - develop for iOS devices
[✓] Android Studio (version 3.4)
[✓] IntelliJ IDEA Ultimate Edition (version 2019.1.2)
[✓] VS Code (version 1.36.1)
[!] Connected device
    ! No devices available

! Doctor found issues in 3 categories.
</code>
</pre>

I've looked through some similar issues but got no solution.Need your help.
Similar issues: #21831, #14891, #35613

**Comment by tango5614** [comment]
I have solved this problem.It's because I had a custom entry file named `main_dev.dart` instead of `main.dart`.Everything is OK after adding the `--target=lib/main_dev.dart` option to the command.
Maybe it should be pointed out on flutter's document or somewhere conspicuous.
