### ISSUE TITLE
Flutter is crashing when fully restarting the app after exiting.

### ISSUE THREAD

**Issue by 2208Abhinav** [flutter/flutter#36157]
Following is the crash report:

Flutter crash report; please file at https://github.com/flutter/flutter/issues.

## command

flutter run --machine -t lib/main.dart -d fa8ba8ec0104 --track-widget-creation --start-paused

## exception

RpcException: JSON-RPC error -32000: Service protocol could not handle or find a handler for the requested method.

```
package:json_rpc_2/src/client.dart 110:64              Client.sendRequest
package:json_rpc_2/src/peer.dart 79:15                 Peer.sendRequest
package:flutter_tools/src/vmservice.dart 316:13        VMService._sendRequest
package:flutter_tools/src/vmservice.dart 851:60        VM.invokeRpcRaw
===== asynchronous gap ===========================
package:flutter_tools/src/vmservice.dart 872:49        VM.invokeRpc
===== asynchronous gap ===========================
package:flutter_tools/src/vmservice.dart 941:12        VM.runInView
package:flutter_tools/src/vmservice.dart 1455:20       FlutterView.runFromSource
===== asynchronous gap ===========================
package:flutter_tools/src/run_hot.dart 372:24          HotRunner._launchInView
package:flutter_tools/src/run_hot.dart 387:19          HotRunner._launchFromDevFS
===== asynchronous gap ===========================
package:flutter_tools/src/run_hot.dart 458:11          HotRunner._restartFromSources
===== asynchronous gap ===========================
package:flutter_tools/src/run_hot.dart 546:46          HotRunner.restart
===== asynchronous gap ===========================
package:flutter_tools/src/commands/daemon.dart 874:19  AppInstance.restart
package:flutter_tools/src/commands/daemon.dart 544:18  AppDomain.restart.<fn>
package:flutter_tools/src/base/context.dart 153:29     AppContext.run.<fn>
===== asynchronous gap ===========================
dart:async/zone.dart 1124:13                           _rootRun
dart:async/zone.dart 1021:19                           _CustomZone.run
dart:async/zone.dart 1516:10                           _runZoned
dart:async/zone.dart 1463:12                           runZoned
package:flutter_tools/src/base/context.dart 152:18     AppContext.run
===== asynchronous gap ===========================
package:flutter_tools/src/commands/daemon.dart 887:20  AppInstance._runInZone
package:flutter_tools/src/commands/daemon.dart 543:32  AppDomain.restart
===== asynchronous gap ===========================
package:flutter_tools/src/commands/daemon.dart 189:34  Domain.handleCommand.<fn>
dart:async/future.dart 224:31                          new Future.sync
package:flutter_tools/src/commands/daemon.dart 186:77  Domain.handleCommand
package:flutter_tools/src/commands/daemon.dart 145:26  Daemon._handleRequest
dart:async/zone.dart 1132:38                           _rootRunUnary
dart:async/zone.dart 1029:19                           _CustomZone.runUnary
dart:async/zone.dart 931:7                             _CustomZone.runUnaryGuarded
dart:async/stream_impl.dart 336:11                     _BufferingStreamSubscription._sendData
dart:async/stream_impl.dart 263:7                      _BufferingStreamSubscription._add
dart:async/stream_pipe.dart 132:11                     _ForwardingStreamSubscription._add
dart:async/stream_pipe.dart 232:10                     _MapStream._handleData
dart:async/stream_pipe.dart 164:13                     _ForwardingStreamSubscription._handleData
dart:async/zone.dart 1132:38                           _rootRunUnary
dart:async/zone.dart 1029:19                           _CustomZone.runUnary
dart:async/zone.dart 931:7                             _CustomZone.runUnaryGuarded
dart:async/stream_impl.dart 336:11                     _BufferingStreamSubscription._sendData
dart:async/stream_impl.dart 263:7                      _BufferingStreamSubscription._add
dart:async/stream_pipe.dart 132:11                     _ForwardingStreamSubscription._add
dart:async/stream_pipe.dart 207:12                     _WhereStream._handleData
dart:async/stream_pipe.dart 164:13                     _ForwardingStreamSubscription._handleData
dart:async/zone.dart 1132:38                           _rootRunUnary
dart:async/zone.dart 1029:19                           _CustomZone.runUnary
dart:async/zone.dart 931:7                             _CustomZone.runUnaryGuarded
dart:async/stream_impl.dart 336:11                     _BufferingStreamSubscription._sendData
dart:async/stream_impl.dart 263:7                      _BufferingStreamSubscription._add
dart:async/stream_transformers.dart 68:11              _SinkTransformerStreamSubscription._add
dart:async/stream_transformers.dart 15:11              _EventSinkWrapper.add
dart:convert/string_conversion.dart 236:11             _StringAdapterSink.add
dart:convert/line_splitter.dart 150:13                 _LineSplitterSink._addLines
dart:convert/line_splitter.dart 125:5                  _LineSplitterSink.addSlice
dart:convert/string_conversion.dart 163:5              StringConversionSinkMixin.add
dart:async/stream_transformers.dart 120:24             _SinkTransformerStreamSubscription._handleData
dart:async/zone.dart 1132:38                           _rootRunUnary
dart:async/zone.dart 1029:19                           _CustomZone.runUnary
dart:async/zone.dart 931:7                             _CustomZone.runUnaryGuarded
dart:async/stream_impl.dart 336:11                     _BufferingStreamSubscription._sendData
dart:async/stream_impl.dart 263:7                      _BufferingStreamSubscription._add
dart:async/stream_transformers.dart 68:11              _SinkTransformerStreamSubscription._add
dart:async/stream_transformers.dart 15:11              _EventSinkWrapper.add
dart:convert/string_conversion.dart 236:11             _StringAdapterSink.add
dart:convert/string_conversion.dart 241:7              _StringAdapterSink.addSlice
dart:convert/string_conversion.dart 312:20             _Utf8ConversionSink.addSlice
dart:convert/string_conversion.dart 305:5              _Utf8ConversionSink.add
dart:convert/chunked_conversion.dart 72:18             _ConverterStreamEventSink.add
dart:async/stream_transformers.dart 120:24             _SinkTransformerStreamSubscription._handleData
dart:async/zone.dart 1132:38                           _rootRunUnary
dart:async/zone.dart 1029:19                           _CustomZone.runUnary
dart:async/zone.dart 931:7                             _CustomZone.runUnaryGuarded
dart:async/stream_impl.dart 336:11                     _BufferingStreamSubscription._sendData
dart:async/stream_impl.dart 263:7                      _BufferingStreamSubscription._add
dart:async/stream_controller.dart 764:19               _SyncStreamController._sendData
dart:async/stream_controller.dart 640:7                _StreamController._add
dart:async/stream_controller.dart 586:5                _StreamController.add
dart:io-patch/socket_patch.dart 1786:41                _Socket._onData
dart:async/zone.dart 1136:13                           _rootRunUnary
dart:async/zone.dart 1029:19                           _CustomZone.runUnary
dart:async/zone.dart 931:7                             _CustomZone.runUnaryGuarded
dart:async/stream_impl.dart 336:11                     _BufferingStreamSubscription._sendData
dart:async/stream_impl.dart 263:7                      _BufferingStreamSubscription._add
dart:async/stream_controller.dart 764:19               _SyncStreamController._sendData
dart:async/stream_controller.dart 640:7                _StreamController._add
dart:async/stream_controller.dart 586:5                _StreamController.add
dart:io-patch/socket_patch.dart 1335:33                new _RawSocket.<fn>
dart:io-patch/socket_patch.dart 856:14                 _NativeSocket.issueReadEvent.issue
dart:async/schedule_microtask.dart 41:21               _microtaskLoop
dart:async/schedule_microtask.dart 50:5                _startMicrotaskLoop
dart:isolate-patch/isolate_patch.dart 116:13           _runPendingImmediateCallback
dart:isolate-patch/isolate_patch.dart 173:5            _RawReceivePortImpl._handleMessage
```

## flutter doctor

```
[✓] Flutter (Channel stable, v1.7.8+hotfix.3, on Mac OS X 10.14.5 18F132, locale en-IN)
    • Flutter version 1.7.8+hotfix.3 at /Users/abhinav/development/flutter
    • Framework revision b712a172f9 (5 days ago), 2019-07-09 13:14:38 -0700
    • Engine revision 54ad777fd2
    • Dart version 2.4.0

[!] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/abhinav/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = /Users/abhinav/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses

[✓] Xcode - develop for iOS and macOS (Xcode 10.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.1, Build version 10B61
    • CocoaPods version 1.7.2

[✗] iOS tools - develop for iOS devices
    ✗ libimobiledevice and ideviceinstaller are not installed. To install with Brew, run:
        brew update
        brew install --HEAD usbmuxd
        brew link usbmuxd
        brew install --HEAD libimobiledevice
        brew install ideviceinstaller
    ✗ ios-deploy not installed. To install:
        brew install ios-deploy

[✓] Android Studio (version 3.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 31.3.1
    • Dart plugin version 181.5656
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)

[✓] VS Code (version 1.36.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.2.0

[✓] Connected device (1 available)
    • Redmi Note 4 • fa8ba8ec0104 • android-arm64 • Android 7.0 (API 24)

! Doctor found issues in 2 categories.
```

**Comment by jonahwilliams** [comment]
@2208Abhinav Can you be more specific about the scenario here? Is this crashing when you exit? crashing when you hot restart? Does it happen from the command line or from an IDE?

Thanks!

**Comment by Parables** [comment]
I was already running Channel stable, v1.5.4-hotfix.2, on Linux, when VS code prompted me that there is a new version. I upgraded Flutter and from then, flutter run crashes, flutter build apk crashes.

Tried downgrading by deleting my entire flutter directory, extracting the old version v1.5.4 again and placed it in the same directory. To test it, i created a new project and executed flutter run.....

IT CRASHED AGAIN and I'm freaking out as I am so close to the deadline and I am to submit the project by Tuesday... 

PLEASE SAVE ME FROM THIS NIGHTMARE!!!

**Comment by Parables** [comment]
Here is my log file



Flutter crash report; please file at https://github.com/flutter/flutter/issues.

## command

flutter run

## exception

ProcessException: ProcessException: Permission denied
  Command: /media/parables/ParaDisk/Workspace/Susu-App/SusuMobileApp/susumobileapp/android/gradlew -v

```
#0      runAsync (package:flutter_tools/src/base/process.dart:232:33)
<asynchronous suspension>
#1      runCheckedAsync (package:flutter_tools/src/base/process.dart:248:34)
<asynchronous suspension>
#2      _initializeGradle (package:flutter_tools/src/android/gradle.dart:225:9)
<asynchronous suspension>
#3      _ensureGradle (package:flutter_tools/src/android/gradle.dart:206:37)
<asynchronous suspension>
#4      _readGradleProject (package:flutter_tools/src/android/gradle.dart:134:31)
<asynchronous suspension>
#5      _gradleProject (package:flutter_tools/src/android/gradle.dart:111:34)
<asynchronous suspension>
#6      getGradleAppOut (package:flutter_tools/src/android/gradle.dart:105:29)
<asynchronous suspension>
#7      AndroidApk.fromAndroidProject (package:flutter_tools/src/application_package.dart:154:23)
<asynchronous suspension>
#8      ApplicationPackageFactory.getPackageForPlatform (package:flutter_tools/src/application_package.dart:46:32)
<asynchronous suspension>
#9      FlutterDevice.runHot (package:flutter_tools/src/resident_runner.dart:345:56)
<asynchronous suspension>
#10     HotRunner.run (package:flutter_tools/src/run_hot.dart:253:39)
<asynchronous suspension>
#11     RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:428:37)
<asynchronous suspension>
#12     FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:559:18)
#13     _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:77:64)
#14     _rootRunUnary (dart:async/zone.dart:1132:38)
#15     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#16     _FutureListener.handleValue (dart:async/future_impl.dart:126:18)
#17     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:639:45)
#18     Future._propagateToListeners (dart:async/future_impl.dart:668:32)
#19     Future._complete (dart:async/future_impl.dart:473:7)
#20     _SyncCompleter.complete (dart:async/future_impl.dart:51:12)
#21     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:28:18)
#22     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:294:13)
#23     RunCommand.usageValues (package:flutter_tools/src/commands/run.dart)
#24     _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:77:64)
#25     _rootRunUnary (dart:async/zone.dart:1132:38)
#26     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#27     _FutureListener.handleValue (dart:async/future_impl.dart:126:18)
#28     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:639:45)
#29     Future._propagateToListeners (dart:async/future_impl.dart:668:32)
#30     Future._complete (dart:async/future_impl.dart:473:7)
#31     _SyncCompleter.complete (dart:async/future_impl.dart:51:12)
#32     _AsyncAwaitCompleter.complete.<anonymous closure> (dart:async-patch/async_patch.dart:33:20)
#33     _rootRun (dart:async/zone.dart:1124:13)
#34     _CustomZone.run (dart:async/zone.dart:1021:19)
#35     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:947:23)
#36     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#37     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#38     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:115:13)
#39     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:5)
```

## flutter doctor

```
[32m[✓][39m Flutter (Channel stable, v1.5.4-hotfix.2, on Linux, locale en_US.UTF-8)
    [32m•[39m Flutter version 1.5.4-hotfix.2 at /home/parables/flutter
    [32m•[39m Framework revision 7a4c33425d (3 months ago), 2019-04-29 11:05:24 -0700
    [32m•[39m Engine revision 52c7a1e849
    [32m•[39m Dart version 2.3.0 (build 2.3.0-dev.0.5 a1668566e5)

[32m[✓][39m Android toolchain - develop for Android devices (Android SDK version 29.0.0)
    [32m•[39m Android SDK at /home/parables/Android/Sdk
    [32m•[39m Android NDK location not configured (optional; useful for native profiling
      support)
    [32m•[39m Platform android-29, build-tools 29.0.0
    [32m•[39m Java binary at: /home/parables/android-studio/jre/bin/java
    [32m•[39m Java version OpenJDK Runtime Environment (build
      1.8.0_152-release-1343-b16-5323222)
    [32m•[39m All Android licenses accepted.

[32m[✓][39m Android Studio (version 3.4)
    [32m•[39m Android Studio at /home/parables/android-studio
    [32m•[39m Flutter plugin version 37.0.1
    [32m•[39m Dart plugin version 183.6270
    [32m•[39m Java version OpenJDK Runtime Environment (build
      1.8.0_152-release-1343-b16-5323222)

[32m[✓][39m VS Code (version 1.36.1)
    [32m•[39m VS Code at /usr/share/code
    [32m•[39m Flutter extension version 3.2.0

[32m[✓][39m Connected device (1 available)
    [32m•[39m itel P51 • BQ4S4SFAAYVKNZKF • android-arm • Android 7.0 (API 24)

[32m•[39m No issues found!
```

**Comment by jonahwilliams** [comment]
@Parables that is a completely unrelated issue. It looks like you are missing execute permission on the gradle script. This can happen if you setup your project in a directory that needs admin/sudo permissions. A quick search turned up https://stackoverflow.com/questions/17668265/gradlew-permission-denied, but this is unrelated to flutter

**Comment by Parables** [comment]
I think it has something to do with my gradlew file. I tried deleting it and used flutter create to recreate it. But it seems that didn't help. I also tried these:https://stackoverflow.com/a/33820642 and it changed the permission to 755 but  Flutter crashed when I executed flutter run

**Comment by Parables** [comment]
> @Parables that is a completely unrelated issue. It looks like you are missing execute permission on the gradle script. This can happen if you setup your project in a directory that needs admin/sudo permissions. A quick search turned up https://stackoverflow.com/questions/17668265/gradlew-permission-denied, but this is unrelated to flutter

I have tried everything on that link you sent and it still crashed

Do I have to until android studio and delete all the gradle directories to fix this?

**Comment by 2208Abhinav** [comment]
@jonahwilliams following is the order:
1) I press the hardware back button on the phone.
2) The app minimizes.
3) I do restart by using the green refresh icon in Visual Studio Code.
4) And then I get this error.

**Comment by jonahwilliams** [comment]
Does this work correctly if you don't pass `--start-paused` ?

**Comment by 2208Abhinav** [comment]
@jonahwilliams I can't pass any parameters because I am not starting the app from terminal but I am doing it from VsCode using `Ctrl + f5` shortcut and the green refresh icon for restart.

**Comment by 2208Abhinav** [comment]
I repeated this whole scenario with the terminal (flutter run -> to run the app). The only difference is it didn't crash this time (on restart using using R) but was stuck on this (This is taking an unexpectedly long time.) message. One thing I have noticed is that when I press the back button to minimize the app this type of behavior is seen but when I use the home button to minimize the app and then do the restart it's working fine. My guess here is that flutter is losing connection with the app in the former scenario.

**Comment by canewsin** [comment]
this behavior already exists in v1.5.4-xxx but it didn't effect release product or debug product it's not related to flutter upgrade

**Comment by 2208Abhinav** [comment]
@canewsin yes this behavior is not affecting the development process in any way. I just thought to show it to flutter team in case something else is present here. And I think that this behavior existed in v1.5.4-xxx also and by chance, I noticed it after the upgrade.

**Comment by jonahwilliams** [comment]
I think we've fixed this issue with some of the additional error handling we've been adding to the flutter tool in the past few weeks. @2208Abhinav can you verify whether you are still experiencing this issue on either the latest stable or a current dev release?

**Comment by 2208Abhinav** [comment]
I tested it and now it's working fine. Thanks!

**Comment by jonahwilliams** [comment]
Perfect, thank you!
