### ISSUE TITLE
 'package:flutter/src/widgets/navigator.dart': Failed assertion: line 1748 pos 12: '!_debugLocked':  is not true.

### ISSUE THREAD

**Issue by sovoereign** [flutter/flutter#36177]
>  'package:flutter/src/widgets/navigator.dart': Failed assertion: line 1748 pos 12: '!_debugLocked':
>  is not true.

Getting issue while routing from one screen to another.

**Comment by sunxianglei** [comment]
I have meeted same problem, and find this error  is actually the second exception, first exception is 
```
 Failed assertion: line 175 pos 12: **'!_transitionCompleter.isCompleted**
```
the first exception will cause the second exception.

and my fault is calling Navigator.push() in `OnTap(){}` closure, when I call it in onPress(){} closure then the problem disappear.  it's very strange! finally, I use Navigator.pushNamed() to jump another screen, and I haven't meet this error again.

**Comment by BondarenkoStas** [comment]
@sovoereign Do you encounter the issue using current flutter stable or master?

**Comment by SeyedAbdollahi** [comment]
> ════════ Exception caught by widgets library════════
The following assertion was thrown building Panel(dirty):
setState() or markNeedsBuild() called during build.
This Overlay widget cannot be marked as needing to build because the framework is already in the process of building widgets.  A widget can be marked as needing to be built during the build phase only if one of its ancestors is currently building. This exception is allowed because the framework builds parent widgets before children, which means a dirty descendant will always be built. Otherwise, the framework might not visit this widget during this build phase.
The widget on which setState() or markNeedsBuild() was called was: Overlay-[LabeledGlobalKey<OverlayState>#781f4]
  state: OverlayState#219d4(entries: [OverlayEntry#0e838(opaque: false; maintainState: false), OverlayEntry#c325c(opaque: false; maintainState: true), OverlayEntry#3194a(opaque: false; maintainState: false), OverlayEntry#94ae7(opaque: false; maintainState: true)])
The widget which was currently being built when the offending call was made was: Panel
  dirty
User-created ancestor of the error-causing widget was: 
  Scaffold file:///C:/Users/Reza%20Abdollahi/Desktop/gui/ajans_app/lib/pages/Panel.dart:9:17
When the exception was thrown, this was the stack: 
#0      Element.markNeedsBuild.<anonymous closure> (package:flutter/src/widgets/framework.dart:3687:11)
#1      Element.markNeedsBuild (package:flutter/src/widgets/framework.dart:3702:6)
#2      State.setState (package:flutter/src/widgets/framework.dart:1161:14)
#3      OverlayState.insertAll (package:flutter/src/widgets/overlay.dart:346:5)
#4      OverlayRoute.install (package:flutter/src/widgets/routes.dart:43:24)
...
════════ (2) Exception caught by widgets library ════════
'package:flutter/src/widgets/navigator.dart': Failed assertion: line 2247 pos 12: '!_debugLocked': is not true.
User-created ancestor of the error-causing widget was: 
  MaterialApp file:///C:/Users/Reza%20Abdollahi/Desktop/gui/ajans_app/lib/pages/Panel.dart:8:12
═════════════════════════════════════════

i have same error.
Flutter v1.9.1+hotfix.2
Dart 2.5.0

**Comment by SandaBurido** [comment]
> I have met same problem, and find this error is actually the second exception, first exception is
> 
> ```
>  Failed assertion: line 175 pos 12: **'!_transitionCompleter.isCompleted**
> ```
> 
> the first exception will cause the second exception.
> 
> and my fault is calling Navigator.push() in `OnTap(){}` closure, when I call it in onPress(){} closure then the problem disappear. it's very strange! finally, I use Navigator.pushNamed() to jump another screen, and I haven't meet this error again.

Worked too, Tks. @sunxianglei

**Comment by Invincible1996** [comment]
Unhandled Exception: 'package:flutter/src/widgets/navigator.dart': Failed assertion: line 1930 pos 12: '!_debugLocked': is not true.

**Comment by it-sam** [comment]
https://github.com/flutter/flutter/issues/16602#issuecomment-407916243

**Comment by softmarshmallow** [comment]
in my case, it was empty default tab controller causing this issue.

**Comment by AxesandGrinds** [comment]
In my case, I set route with a screen then try to call the same screen using navigator... without pushnamed somewhere else and this error came up. If you're using routes for a particular screen then always use routes for that screen. It was a clumsy mistake on my part.

**Comment by toritroniks** [comment]
The same thing started happening to me after I updated Flutter and Dart (after a long time without updating).

In my case I realized that I had another exception before this error appeared.
```
setState() or markNeedsBuild called during build
```

I fixed it by using a `PostFrameCallback`
```
          WidgetsBinding.instance.addPostFrameCallback((_) {
            Navigator.of(context)
                .pushReplacementNamed(MyScreen.routeName);
          });
```

Hope this helps someone.

Flutter 1.17.4
Tools • Dart 2.8.4

**Comment by DanielCardona** [comment]
> The same thing started happening to me after I updated Flutter and Dart (after a long time without updating).
> 
> In my case I realized that I had another exception before this error appeared.
> 
> ```
> setState() or markNeedsBuild called during build
> ```
> 
> I fixed it by using a `PostFrameCallback`
> 
> ```
>           WidgetsBinding.instance.addPostFrameCallback((_) {
>             Navigator.of(context)
>                 .pushReplacementNamed(MyScreen.routeName);
>           });
> ```
> 
> Hope this helps someone.
> 
> Flutter 1.17.4
> Tools • Dart 2.8.4

THANKS @toritroniks !!!

**Comment by onuohasilver** [comment]
> 
> 
> The same thing started happening to me after I updated Flutter and Dart (after a long time without updating).
> 
> In my case I realized that I had another exception before this error appeared.
> 
> ```
> setState() or markNeedsBuild called during build
> ```
> 
> I fixed it by using a `PostFrameCallback`
> 
> ```
>           WidgetsBinding.instance.addPostFrameCallback((_) {
>             Navigator.of(context)
>                 .pushReplacementNamed(MyScreen.routeName);
>           });
> ```
> 
> Hope this helps someone.
> 
> Flutter 1.17.4
> Tools • Dart 2.8.4

Thanks a lot, been trying to figure this out for a while.

**Comment by panchalAlpit** [comment]
> > The same thing started happening to me after I updated Flutter and Dart (after a long time without updating).
> > In my case I realized that I had another exception before this error appeared.
> > ```
> > setState() or markNeedsBuild called during build
> > ```
> > 
> > 
> > I fixed it by using a `PostFrameCallback`
> > ```
> >           WidgetsBinding.instance.addPostFrameCallback((_) {
> >             Navigator.of(context)
> >                 .pushReplacementNamed(MyScreen.routeName);
> >           });
> > ```
> > 
> > 
> > Hope this helps someone.
> > Flutter 1.17.4
> > Tools • Dart 2.8.4
> 
> THANKS @toritroniks !!!


It's not working if I use:- 
WidgetsBinding.instance.addPostFrameCallback((_) {
              Navigator.pop(context);
            });
Can you please suggest to me, how to fix this issue.

**Comment by jameskaguo777** [comment]
> The same thing started happening to me after I updated Flutter and Dart (after a long time without updating).
> 
> In my case I realized that I had another exception before this error appeared.
> 
> ```
> setState() or markNeedsBuild called during build
> ```
> 
> I fixed it by using a `PostFrameCallback`
> 
> ```
>           WidgetsBinding.instance.addPostFrameCallback((_) {
>             Navigator.of(context)
>                 .pushReplacementNamed(MyScreen.routeName);
>           });
> ```
> 
> Hope this helps someone.
> 
> Flutter 1.17.4
> Tools • Dart 2.8.4

Lifetime saver

**Comment by iapicca** [comment]
Hi @sovoereign 
are you still experiencing the issue with the latest stable (or above)?
if so could you please provide 
your updated `flutter doctor -v`, 
your `flutter run --verbose` 
and a minimal reproducible code sample.
Thank you

**Comment by takaomatt** [comment]
> > > The same thing started happening to me after I updated Flutter and Dart (after a long time without updating).
> > > In my case I realized that I had another exception before this error appeared.
> > > ```
> > > setState() or markNeedsBuild called during build
> > > ```
> > > 
> > > 
> > > I fixed it by using a `PostFrameCallback`
> > > ```
> > >           WidgetsBinding.instance.addPostFrameCallback((_) {
> > >             Navigator.of(context)
> > >                 .pushReplacementNamed(MyScreen.routeName);
> > >           });
> > > ```
> > > 
> > > 
> > > Hope this helps someone.
> > > Flutter 1.17.4
> > > Tools • Dart 2.8.4
> > 
> > 
> > THANKS @toritroniks !!!
> 
> It's not working if I use:-
> WidgetsBinding.instance.addPostFrameCallback((_) {
> Navigator.pop(context);
> });
> Can you please suggest to me, how to fix this issue.

I would also like to know the answer to this question - the solution for me did not work for `.pop()`

**Comment by steveartfx** [comment]
Was getting something similar, the fix for me was to use await before Navigator:
             if (response.statusCode == 200) {
                    await Navigator.pushNamedAndRemoveUntil(context, '/home', (_) => false); ...


                if(dialogOpen) {
                  Navigator.of(context).pop();
                }

**Comment by adityajoshi12** [comment]
This usually arises if you do not put the Navigator function inside (){}. I faced something like it and I simply added my Navigator.push()...  inside (){}.
And the error resolved.

**Comment by Amitzala143** [comment]
Hi all,
There are  some cases
1. You are changing the state of current widget and redirecting to other screen without completing build
2. You are redirecting to same route same route 
3. You are calling setState{()} method in build method of widget
4. You redirecting to other screen without closing dialog properly
In my case I was push the screen in init state method so its have not time to build

@override
  void initState() {
    super.initState();
    _con.initPlatFormChannel();
    Future.delayed(Duration.zero, () {
      _con.buildList(context: context);
    });
    /* if (userRepo.currentUser.value.apiToken != null) {
      Navigator.of(context).pushReplacementNamed('/Pages', arguments: 2);
    }*/
  }

like this than i have comment the code

**Comment by tianye19941001** [comment]
I change flutter version to v1.20.3 to fixed this

**Comment by Lurzapps** [comment]
setState() or markNeedsBuild() called during build.

**Comment by ZiaUrRahmam** [comment]
i am also facing the sam issue
package:flutter/src/widgets/navigator.dart': Failed assertion: line 3352 pos 12: '!_debugLocked': is not true.
