### ISSUE TITLE
my flutter problem

### ISSUE THREAD

**Issue by wuyongfei-1** [flutter/flutter#36342]
```
[{"event":"app.progress","params":{"appId":"8edf1121-1b85-465d-81a3-4f591ee17f8d","id":"5","progressId":"hot.restart","message":"Performing hot restart..."}}]Performing hot restart...
Syncing files to device Android SDK built for x86...
Restarted application in 1,833ms.
I/flutter (23620): ══╡ EXCEPTION CAUGHT BY RENDERING LIBRARY ╞═════════════════════════════════════════════════════════
I/flutter (23620): The following assertion was thrown during performLayout():
I/flutter (23620): FlutterError contained multiple error summaries.
I/flutter (23620): All FlutterError objects should have only a single short (one line) summary description of the
I/flutter (23620): problem that was detected.
I/flutter (23620): Malformed FlutterError:
I/flutter (23620):   RenderCustomMultiChildLayoutBox object was given an infinite size during layout.
I/flutter (23620):   This probably means that it is a render object that tries to be as big as possible, but it was put
I/flutter (23620):   inside another render object that allows its children to pick their own size.
I/flutter (23620):   RenderCustomMultiChildLayoutBox object was given an infinite size during layout.
I/flutter (23620):   This probably means that it is a render object that tries to be as big as possible, but it was put
I/flutter (23620):   inside another render object that allows its children to pick their own size.
I/flutter (23620):   The nearest ancestor providing an unbounded width constraint is: RenderFlex#e0d2e relayoutBoundary=up5 NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE:
I/flutter (23620):     creator: Row ← Container ← RepaintBoundary ← IndexedSemantics ←
I/flutter (23620):       NotificationListener<KeepAliveNotification> ← KeepAlive ← AutomaticKeepAlive ← KeyedSubtree ←
I/flutter (23620):       SliverList ← MediaQuery ← SliverPadding ← Viewport ← ⋯
I/flutter (23620):     parentData: <none> (can use size)
I/flutter (23620):     constraints: BoxConstraints(w=411.4, 0.0<=h<=Infinity)
I/flutter (23620):     size: MISSING
I/flutter (23620):     direction: horizontal
I/flutter (23620):     mainAxisAlignment: start
I/flutter (23620):     mainAxisSize: max
I/flutter (23620):     crossAxisAlignment: center
I/flutter (23620):     textDirection: ltr
I/flutter (23620):     verticalDirection: down
I/flutter (23620):   The nearest ancestor providing an unbounded height constraint is: RenderIndexedSemantics#81d43 relayoutBoundary=up3 NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE:
I/flutter (23620):     creator: IndexedSemantics ← NotificationListener<KeepAliveNotification> ← KeepAlive ←
I/flutter (23620):       AutomaticKeepAlive ← KeyedSubtree ← SliverList ← MediaQuery ← SliverPadding ← Viewport ←
I/flutter (23620):       IgnorePointer-[GlobalKey#bbda0] ← Semantics ← Listener ← ⋯
I/flutter (23620):     parentData: index=1; layoutOffset=0.0 (can use size)
I/flutter (23620):     constraints: BoxConstraints(w=411.4, 0.0<=h<=Infinity)
I/flutter (23620):     semantic boundary
I/flutter (23620):     size: MISSING
I/flutter (23620):     index: 1
I/flutter (23620):   The constraints that applied to the RenderCustomMultiChildLayoutBox were:
I/flutter (23620):     BoxConstraints(unconstrained)
I/flutter (23620):   The exact size it was given was:
I/flutter (23620):     Size(Infinity, Infinity)
I/flutter (23620):   See https://flutter.dev/docs/development/ui/layout/box-constraints for more information.
I/flutter (23620): 
I/flutter (23620): The malformed error has 2 summaries.
I/flutter (23620): Summary 1: RenderCustomMultiChildLayoutBox object was given an infinite size during layout.
I/flutter (23620): Summary 2: RenderCustomMultiChildLayoutBox object was given an infinite size during layout.
I/flutter (23620): 
I/flutter (23620): This error should still help you solve your problem, however please also report this malformed error
I/flutter (23620): in the framework by filing a bug on GitHub:
I/flutter (23620):   https://github.com/flutter/flutter/issues/new?template=BUG.md
I/flutter (23620): 
I/flutter (23620): When the exception was thrown, this was the stack:
I/flutter (23620): #0      new FlutterError.fromParts.<anonymous closure> (package:flutter/src/foundation/assertions.dart:540:9)
I/flutter (23620): #1      new FlutterError.fromParts (package:flutter/src/foundation/assertions.dart:543:6)
I/flutter (23620): #2      RenderBox.debugAssertDoesMeetConstraints.<anonymous closure> (package:flutter/src/rendering/box.dart:1966:28)
I/flutter (23620): #3      RenderBox.debugAssertDoesMeetConstraints (package:flutter/src/rendering/box.dart:2029:6)
I/flutter (23620): #4      RenderBox.size=.<anonymous closure> (package:flutter/src/rendering/box.dart:1740:7)
I/flutter (23620): #5      RenderBox.size= (package:flutter/src/rendering/box.dart:1742:6)
I/flutter (23620): #6      RenderCustomMultiChildLayoutBox.performLayout (package:flutter/src/rendering/custom_layout.dart:355:5)
I/flutter (23620): #7      RenderObject.layout (package:flutter/src/rendering/object.dart:1619:7)
I/flutter (23620): #8      RenderFlex.performLayout (package:flutter/src/rendering/flex.dart:743:15)
I/flutter (23620): #9      RenderObject.layout (package:flutter/src/rendering/object.dart:1619:7)
I/flutter (23620): #10     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter (23620): #11     RenderObject.layout (package:flutter/src/rendering/object.dart:1619:7)
I/flutter (23620): #12     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter (23620): #13     RenderObject.layout (package:flutter/src/rendering/object.dart:1619:7)
I/flutter (23620): #14     RenderSliverMultiBoxAdaptor.insertAndLayoutChild (package:flutter/src/rendering/sliver_multi_box_adaptor.dart:492:13)
I/flutter (23620): #15     RenderSliverList.performLayout.advance (package:flutter/src/rendering/sliver_list.dart:191:19)
I/flutter (23620): #16     RenderSliverList.performLayout (package:flutter/src/rendering/sliver_list.dart:234:19)
I/flutter (23620): #17     RenderObject.layout (package:flutter/src/rendering/object.dart:1619:7)
I/flutter (23620): #18     RenderSliverPadding.performLayout (package:flutter/src/rendering/sliver_padding.dart:181:11)
I/flutter (23620): #19     RenderObject.layout (package:flutter/src/rendering/object.dart:1619:7)
I/flutter (23620): #20     RenderViewportBase.layoutChildSequence (package:flutter/src/rendering/viewport.dart:406:13)
I/flutter (23620): #21     RenderViewport._attemptLayout (package:flutter/src/rendering/viewport.dart:1334:12)
I/flutter (23620): #22     RenderViewport.performLayout (package:flutter/src/rendering/viewport.dart:1252:20)
I/flutter (23620): #23     RenderObject.layout (package:flutter/src/rendering/object.dart:1619:7)
I/flutter (23620): #24     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter (23620): #25     RenderObject.layout (package:flutter/src/rendering/object.dart:1619:7)
I/flutter (23620): #26     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter (23620): #27     RenderObject.layout (package:flutter/src/rendering/object.dart:1619:7)
I/flutter (23620): #28     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter (23620): #29     RenderObject.layout (package:flutter/src/rendering/object.dart:1619:7)
I/flutter (23620): #30     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter (23620): #31     RenderObject.layout (package:flutter/src/rendering/object.dart:1619:7)
I/flutter (23620): #32     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter (23620): #33     RenderObject.layout (package:flutter/src/rendering/object.dart:1619:7)
I/flutter (23620): #34     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter (23620): #35     RenderObject.layout (package:flutter/src/rendering/object.dart:1619:7)
I/flutter (23620): #36     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter (23620): #37     RenderObject.layout (package:flutter/src/rendering/object.dart:1619:7)
I/flutter (23620): #38     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter (23620): #39     RenderObject.layout (package:flutter/src/rendering/object.dart:1619:7)
I/flutter (23620): #40     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter (23620): #41     RenderObject.layout (package:flutter/src/rendering/object.dart:1619:7)
I/flutter (23620): #42     RenderFlex.performLayout (package:flutter/src/rendering/flex.dart:805:17)
I/flutter (23620): #43     RenderObject.layout (package:flutter/src/rendering/object.dart:1619:7)
I/flutter (23620): #44     MultiChildLayoutDelegate.layoutChild (package:flutter/src/rendering/custom_layout.dart:142:11)
I/flutter (23620): #45     _ScaffoldLayout.performLayout (package:flutter/src/material/scaffold.dart:443:7)
I/flutter (23620): #46     MultiChildLayoutDelegate._callPerformLayout (package:flutter/src/rendering/custom_layout.dart:212:7)
I/flutter (23620): #47     RenderCustomMultiChildLayoutBox.performLayout (package:flutter/src/rendering/custom_layout.dart:356:14)
I/flutter (23620): #48     RenderObject.layout (package:flutter/src/rendering/object.dart:1619:7)
I/flutter (23620): #49     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter (23620): #50     RenderObject.layout (package:flutter/src/rendering/object.dart:1619:7)
I/flutter (23620): #51     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter (23620): #52     _RenderCustomClip.performLayout (package:flutter/src/rendering/proxy_box.dart:1214:11)
I/flutter (23620): #53     RenderObject.layout (package:flutter/src/rendering/object.dart:1619:7)
I/flutter (23620): #54     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter (23620): #55     RenderObject.layout (package:flutter/src/rendering/object.dart:1619:7)
I/flutter (23620): #56     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter (23620): #57     RenderObject.layout (package:flutter/src/rendering/object.dart:1619:7)
I/flutter (23620): #58     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter (23620): #59     RenderObject.layout (package:flutter/src/rendering/object.dart:1619:7)
I/flutter (23620): #60     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter (23620): #61     RenderObject.layout (package:flutter/src/rendering/object.dart:1619:7)
I/flutter (23620): #62     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter (23620): #63     RenderObject.layout (package:flutter/src/rendering/object.dart:1619:7)
I/flutter (23620): #64     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter (23620): #65     RenderObject.layout (package:flutter/src/rendering/object.dart:1619:7)
I/flutter (23620): #66     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter (23620): #67     RenderObject.layout (package:flutter/src/rendering/object.dart:1619:7)
I/flutter (23620): #68     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter (23620): #69     RenderOffstage.performLayout (package:flutter/src/rendering/proxy_box.dart:3076:13)
I/flutter (23620): #70     RenderObject.layout (package:flutter/src/rendering/object.dart:1619:7)
I/flutter (23620): #71     RenderStack.performLayout (package:flutter/src/rendering/stack.dart:510:15)
I/flutter (23620): #72     RenderObject.layout (package:flutter/src/rendering/object.dart:1619:7)
I/flutter (23620): #73     __RenderTheatre&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter (23620): #74     RenderObject.layout (package:flutter/src/rendering/object.dart:1619:7)
I/flutter (23620): #75     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter (23620): #76     RenderObject.layout (package:flutter/src/rendering/object.dart:1619:7)
I/flutter (23620): #77     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter (23620): #78     RenderObject.layout (package:flutter/src/rendering/object.dart:1619:7)
I/flutter (23620): #79     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter (23620): #80     RenderObject.layout (package:flutter/src/rendering/object.dart:1619:7)
I/flutter (23620): #81     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter (23620): #82     RenderObject.layout (package:flutter/src/rendering/object.dart:1619:7)
I/flutter (23620): #83     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter (23620): #84     RenderObject.layout (package:flutter/src/rendering/object.dart:1619:7)
I/flutter (23620): #85     RenderView.performLayout (package:flutter/src/rendering/view.dart:151:13)
I/flutter (23620): #86     RenderObject._layoutWithoutResize (package:flutter/src/rendering/object.dart:1496:7)
I/flutter (23620): #87     PipelineOwner.flushLayout (package:flutter/src/rendering/object.dart:765:18)
I/flutter (23620): #88     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding.drawFrame (package:flutter/src/rendering/binding.dart:346:19)
I/flutter (23620): #89     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding&WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:701:13)
I/flutter (23620): #90     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:285:5)
I/flutter (23620): #91     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1016:15)
I/flutter (23620): #92     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:958:9)
I/flutter (23620): #93     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.scheduleWarmUpFrame.<anonymous closure> (package:flutter/src/scheduler/binding.dart:784:7)
I/flutter (23620): #102    _Timer._runTimers (dart:isolate-patch/timer_impl.dart:382:19)
I/flutter (23620): #103    _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:416:5)
I/flutter (23620): #104    _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:12)
I/flutter (23620): (elided 8 frames from package dart:async and package dart:async-patch)
I/flutter (23620): 
I/flutter (23620): The following RenderObject was being processed when the exception was fired: RenderCustomMultiChildLayoutBox#05da7 relayoutBoundary=up6 NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE:
I/flutter (23620):   creator: CustomMultiChildLayout ← BarChart ← SimpleBarChart ← Row ← Container ← RepaintBoundary ←
I/flutter (23620):     IndexedSemantics ← NotificationListener<KeepAliveNotification> ← KeepAlive ← AutomaticKeepAlive ←
I/flutter (23620):     KeyedSubtree ← SliverList ← ⋯
I/flutter (23620):   parentData: offset=Offset(0.0, 0.0); flex=null; fit=null (can use size)
I/flutter (23620):   constraints: BoxConstraints(unconstrained)
I/flutter (23620):   size: Size(Infinity, Infinity)
I/flutter (23620): This RenderObject had the following descendants (showing up to depth 5):
I/flutter (23620):     child 1: RenderSemanticsGestureHandler#7f10b NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
I/flutter (23620):       child: RenderPointerListener#61c6a NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
I/flutter (23620):         child: ChartContainerRenderObject<String>#a8a56 NEEDS-LAYOUT NEEDS-PAINT
I/flutter (23620): ════════════════════════════════════════════════════════════════════════════════════════════════════
I/flutter (23620): Another exception was thrown: FlutterError contained multiple error summaries.
I/chatty  (23620): uid=10085(com.example.fluttergtu) Thread-2 identical 1 line
I/flutter (23620): Another exception was thrown: FlutterError contained multiple error summaries.
I/flutter (23620): Another exception was thrown: NoSuchMethodError: The method '>' was called on null.
I/flutter (23620): Another exception was thrown: FlutterError contained multiple error summaries.
I/chatty  (23620): uid=10085(com.example.fluttergtu) Thread-2 identical 2 lines
I/flutter (23620): Another exception was thrown: FlutterError contained multiple error summaries.
I/flutter (23620): Another exception was thrown: NoSuchMethodError: The method '>' was called on null.
I/flutter (23620): Another exception was thrown: FlutterError contained multiple error summaries.
```

**Comment by marijndegen** [comment]
How can you expect anyone to look at this code without even specifying what behaviour you expect and what doesn't work? 👎

**Comment by BondarenkoStas** [comment]
@wuyongfei-1 This is a question better suited for StackOverflow, since there doesn’t seem to be anything wrong with Flutter itself, but related to implementation. Closing, as this is not an issue report. See https://flutter.dev/community for support options.
Please look closer to the stacktrace, I believe there is enough information to dig into the problem. If you disagree, please comment and I will re-open the issue right away.
