### ISSUE TITLE
webview show nothing on Nexus 6p

### ISSUE THREAD

**Issue by lyodooo** [flutter/flutter#36351]
# Steps to Reproduce
run the following code on Android emulator and iOS emulator, everything is fine, but on Nexus 6p just show white screen like the picture:
![image](https://user-images.githubusercontent.com/17489199/61361072-52e69900-a8b2-11e9-9062-977979790522.png)

```
import 'dart:async';

import 'package:flutter/cupertino.dart';
import 'package:webview_flutter/webview_flutter.dart';

void main() => runApp(App());

class App extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return CupertinoApp(
      home: WebPage(),
    );
  }
}

class WebPage extends StatefulWidget {
  @override
  _WebPageState createState() => _WebPageState();
}

class _WebPageState extends State<WebPage> {
  final Completer<WebViewController> _controller =
      Completer<WebViewController>();

  @override
  Widget build(BuildContext context) {
    return CupertinoPageScaffold(
        child: WebView(
      initialUrl: 'https://www.bilibili.com/',
      javascriptMode: JavascriptMode.unrestricted,
      onWebViewCreated: (WebViewController webViewController) {
        _controller.complete(webViewController);
      },
    ));
  }
}

```

## Logs

```
[ +743 ms] D/ApplicationLoaders(27978): ignored Vulkan layer search path /data/app/com.android.chrome-1/lib/arm:/data/app/com.android.chrome-1/base.apk!/lib/armeabi-v7a
for namespace 0x71fd0f40f0
[        ] I/WebViewFactory(27978): Loading com.android.chrome version 71.0.3578.99 (code 357809902)
[        ] E/webviewchromiumloader(27978): Failed to open relro file /data/misc/shared_relro/libwebviewchromium64.relro: No such file or directory
[        ] W/WebViewFactory(27978): failed to load with relro file, proceeding without
[  +25 ms] E/cr_LibraryLoader(27978): Unable to load library: monochrome
[   +4 ms] E/WebViewFactory(27978): error instantiating provider
[        ] E/WebViewFactory(27978): java.lang.reflect.InvocationTargetException
[        ] E/WebViewFactory(27978):     at java.lang.reflect.Constructor.newInstance0(Native Method)
[        ] E/WebViewFactory(27978):     at java.lang.reflect.Constructor.newInstance(Constructor.java:430)
[        ] E/WebViewFactory(27978):     at android.webkit.WebViewFactory.getProvider(WebViewFactory.java:198)
[        ] E/WebViewFactory(27978):     at android.webkit.WebView.getFactory(WebView.java:2341)
[        ] E/WebViewFactory(27978):     at android.webkit.WebView.ensureProviderCreated(WebView.java:2336)
[        ] E/WebViewFactory(27978):     at android.webkit.WebView.setOverScrollMode(WebView.java:2395)
[        ] E/WebViewFactory(27978):     at android.view.View.<init>(View.java:4023)
[        ] E/WebViewFactory(27978):     at android.view.View.<init>(View.java:4146)
[        ] E/WebViewFactory(27978):     at android.view.ViewGroup.<init>(ViewGroup.java:579)
[        ] E/WebViewFactory(27978):     at android.widget.AbsoluteLayout.<init>(AbsoluteLayout.java:55)
[        ] E/WebViewFactory(27978):     at android.webkit.WebView.<init>(WebView.java:627)
[        ] E/WebViewFactory(27978):     at android.webkit.WebView.<init>(WebView.java:572)
[        ] E/WebViewFactory(27978):     at android.webkit.WebView.<init>(WebView.java:555)
[        ] E/WebViewFactory(27978):     at android.webkit.WebView.<init>(WebView.java:542)
[        ] E/WebViewFactory(27978):     at android.webkit.WebView.<init>(WebView.java:532)
[        ] E/WebViewFactory(27978):     at io.flutter.plugins.webviewflutter.InputAwareWebView.<init>(InputAwareWebView.java:27)
[        ] E/WebViewFactory(27978):     at io.flutter.plugins.webviewflutter.FlutterWebView.<init>(FlutterWebView.java:38)
[        ] E/WebViewFactory(27978):     at io.flutter.plugins.webviewflutter.WebViewFactory.create(WebViewFactory.java:29)
[        ] E/WebViewFactory(27978):     at io.flutter.plugin.platform.SingleViewPresentation.onCreate(SingleViewPresentation.java:154)
[        ] E/WebViewFactory(27978):     at android.app.Dialog.dispatchOnCreate(Dialog.java:402)
[        ] E/WebViewFactory(27978):     at android.app.Dialog.show(Dialog.java:301)
[        ] E/WebViewFactory(27978):     at android.app.Presentation.show(Presentation.java:235)
[        ] E/WebViewFactory(27978):     at io.flutter.plugin.platform.VirtualDisplayController.<init>(VirtualDisplayController.java:92)
[        ] E/WebViewFactory(27978):     at io.flutter.plugin.platform.VirtualDisplayController.create(VirtualDisplayController.java:52)
[        ] E/WebViewFactory(27978):     at io.flutter.plugin.platform.PlatformViewsController$1.createPlatformView(PlatformViewsController.java:97)
[        ] E/WebViewFactory(27978):     at io.flutter.embedding.engine.systemchannels.PlatformViewsChannel$1.create(PlatformViewsChannel.java:87)
[        ] E/WebViewFactory(27978):     at io.flutter.embedding.engine.systemchannels.PlatformViewsChannel$1.onMethodCall(PlatformViewsChannel.java:51)
[        ] E/WebViewFactory(27978):     at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:222)
[        ] E/WebViewFactory(27978):     at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:96)
[        ] E/WebViewFactory(27978):     at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:643)
[        ] E/WebViewFactory(27978):     at android.os.MessageQueue.nativePollOnce(Native Method)
[        ] E/WebViewFactory(27978):     at android.os.MessageQueue.next(MessageQueue.java:323)
[   +1 ms] E/WebViewFactory(27978):     at android.os.Looper.loop(Looper.java:136)
[        ] E/WebViewFactory(27978):     at android.app.ActivityThread.main(ActivityThread.java:6121)
[        ] E/WebViewFactory(27978):     at java.lang.reflect.Method.invoke(Native Method)
[        ] E/WebViewFactory(27978):     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889)
[        ] E/WebViewFactory(27978):     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)
[        ] E/WebViewFactory(27978): Caused by: java.lang.RuntimeException: Cannot load WebView
[        ] E/WebViewFactory(27978):     at com.android.webview.chromium.WebViewChromiumFactoryProvider.a(SourceFile:118)
[        ] E/WebViewFactory(27978):     at com.android.webview.chromium.WebViewChromiumFactoryProvider.<init>(SourceFile:32)
[        ] E/WebViewFactory(27978):     ... 37 more
[        ] E/WebViewFactory(27978): Caused by: aBo
[        ] E/WebViewFactory(27978):     at org.chromium.base.library_loader.LibraryLoader.c(SourceFile:83)
[        ] E/WebViewFactory(27978):     at org.chromium.base.library_loader.LibraryLoader.b(SourceFile:34)
[        ] E/WebViewFactory(27978):     at com.android.webview.chromium.WebViewChromiumFactoryProvider.a(SourceFile:109)
[        ] E/WebViewFactory(27978):     ... 38 more
[        ] E/WebViewFactory(27978): Caused by: java.lang.UnsatisfiedLinkError: dlopen failed: "/data/app/com.android.chrome-1/base.apk!/lib/armeabi-v7a/libmonochrome.so"
is 32-bit instead of 64-bit
[        ] E/WebViewFactory(27978):     at java.lang.Runtime.loadLibrary0(Runtime.java:989)
[        ] E/WebViewFactory(27978):     at java.lang.System.loadLibrary(System.java:1562)
[        ] E/WebViewFactory(27978):     at org.chromium.base.library_loader.LibraryLoader.c(SourceFile:65)
[        ] E/WebViewFactory(27978):     ... 40 more
[  +21 ms] E/MethodChannel#flutter/platform_views(27978): Failed to handle method call
[        ] E/MethodChannel#flutter/platform_views(27978): android.util.AndroidRuntimeException: java.lang.reflect.InvocationTargetException
[        ] E/MethodChannel#flutter/platform_views(27978):       at android.webkit.WebViewFactory.getProvider(WebViewFactory.java:204)
[        ] E/MethodChannel#flutter/platform_views(27978):       at android.webkit.WebView.getFactory(WebView.java:2341)
[        ] E/MethodChannel#flutter/platform_views(27978):       at android.webkit.WebView.ensureProviderCreated(WebView.java:2336)
[        ] E/MethodChannel#flutter/platform_views(27978):       at android.webkit.WebView.setOverScrollMode(WebView.java:2395)
[        ] E/MethodChannel#flutter/platform_views(27978):       at android.view.View.<init>(View.java:4023)
[        ] E/MethodChannel#flutter/platform_views(27978):       at android.view.View.<init>(View.java:4146)
[        ] E/MethodChannel#flutter/platform_views(27978):       at android.view.ViewGroup.<init>(ViewGroup.java:579)
[        ] E/MethodChannel#flutter/platform_views(27978):       at android.widget.AbsoluteLayout.<init>(AbsoluteLayout.java:55)
[        ] E/MethodChannel#flutter/platform_views(27978):       at android.webkit.WebView.<init>(WebView.java:627)
[        ] E/MethodChannel#flutter/platform_views(27978):       at android.webkit.WebView.<init>(WebView.java:572)
[        ] E/MethodChannel#flutter/platform_views(27978):       at android.webkit.WebView.<init>(WebView.java:555)
[        ] E/MethodChannel#flutter/platform_views(27978):       at android.webkit.WebView.<init>(WebView.java:542)
[        ] E/MethodChannel#flutter/platform_views(27978):       at android.webkit.WebView.<init>(WebView.java:532)
[        ] E/MethodChannel#flutter/platform_views(27978):       at io.flutter.plugins.webviewflutter.InputAwareWebView.<init>(InputAwareWebView.java:27)
[        ] E/MethodChannel#flutter/platform_views(27978):       at io.flutter.plugins.webviewflutter.FlutterWebView.<init>(FlutterWebView.java:38)
[        ] E/MethodChannel#flutter/platform_views(27978):       at io.flutter.plugins.webviewflutter.WebViewFactory.create(WebViewFactory.java:29)
[        ] E/MethodChannel#flutter/platform_views(27978):       at io.flutter.plugin.platform.SingleViewPresentation.onCreate(SingleViewPresentation.java:154)
[        ] E/MethodChannel#flutter/platform_views(27978):       at android.app.Dialog.dispatchOnCreate(Dialog.java:402)
[        ] E/MethodChannel#flutter/platform_views(27978):       at android.app.Dialog.show(Dialog.java:301)
[        ] E/MethodChannel#flutter/platform_views(27978):       at android.app.Presentation.show(Presentation.java:235)
[        ] E/MethodChannel#flutter/platform_views(27978):       at io.flutter.plugin.platform.VirtualDisplayController.<init>(VirtualDisplayController.java:92)
[        ] E/MethodChannel#flutter/platform_views(27978):       at io.flutter.plugin.platform.VirtualDisplayController.create(VirtualDisplayController.java:52)
[        ] E/MethodChannel#flutter/platform_views(27978):       at io.flutter.plugin.platform.PlatformViewsController$1.createPlatformView(PlatformViewsController.java:97)
[        ] E/MethodChannel#flutter/platform_views(27978):       at io.flutter.embedding.engine.systemchannels.PlatformViewsChannel$1.create(PlatformViewsChannel.java:87)
[        ] E/MethodChannel#flutter/platform_views(27978):       at
io.flutter.embedding.engine.systemchannels.PlatformViewsChannel$1.onMethodCall(PlatformViewsChannel.java:51)
[   +1 ms] E/MethodChannel#flutter/platform_views(27978):       at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:222)
[        ] E/MethodChannel#flutter/platform_views(27978):       at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:96)
[        ] E/MethodChannel#flutter/platform_views(27978):       at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:643)
[        ] E/MethodChannel#flutter/platform_views(27978):       at android.os.MessageQueue.nativePollOnce(Native Method)
[        ] E/MethodChannel#flutter/platform_views(27978):       at android.os.MessageQueue.next(MessageQueue.java:323)
[        ] E/MethodChannel#flutter/platform_views(27978):       at android.os.Looper.loop(Looper.java:136)
[        ] E/MethodChannel#flutter/platform_views(27978):       at android.app.ActivityThread.main(ActivityThread.java:6121)
[        ] E/MethodChannel#flutter/platform_views(27978):       at java.lang.reflect.Method.invoke(Native Method)
[        ] E/MethodChannel#flutter/platform_views(27978):       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889)
[        ] E/MethodChannel#flutter/platform_views(27978):       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)
[        ] E/MethodChannel#flutter/platform_views(27978): Caused by: java.lang.reflect.InvocationTargetException
[        ] E/MethodChannel#flutter/platform_views(27978):       at java.lang.reflect.Constructor.newInstance0(Native Method)
[        ] E/MethodChannel#flutter/platform_views(27978):       at java.lang.reflect.Constructor.newInstance(Constructor.java:430)
[        ] E/MethodChannel#flutter/platform_views(27978):       at android.webkit.WebViewFactory.getProvider(WebViewFactory.java:198)
[        ] E/MethodChannel#flutter/platform_views(27978):       ... 34 more
[        ] E/MethodChannel#flutter/platform_views(27978): Caused by: java.lang.RuntimeException: Cannot load WebView
[        ] E/MethodChannel#flutter/platform_views(27978):       at com.android.webview.chromium.WebViewChromiumFactoryProvider.a(SourceFile:118)
[        ] E/MethodChannel#flutter/platform_views(27978):       at com.android.webview.chromium.WebViewChromiumFactoryProvider.<init>(SourceFile:32)
[        ] E/MethodChannel#flutter/platform_views(27978):       ... 37 more
[        ] E/MethodChannel#flutter/platform_views(27978): Caused by: aBo
[        ] E/MethodChannel#flutter/platform_views(27978):       at org.chromium.base.library_loader.LibraryLoader.c(SourceFile:83)
[        ] E/MethodChannel#flutter/platform_views(27978):       at org.chromium.base.library_loader.LibraryLoader.b(SourceFile:34)
[        ] E/MethodChannel#flutter/platform_views(27978):       at com.android.webview.chromium.WebViewChromiumFactoryProvider.a(SourceFile:109)
[        ] E/MethodChannel#flutter/platform_views(27978):       ... 38 more
[        ] E/MethodChannel#flutter/platform_views(27978): Caused by: java.lang.UnsatisfiedLinkError: dlopen failed:
"/data/app/com.android.chrome-1/base.apk!/lib/armeabi-v7a/libmonochrome.so" is 32-bit instead of 64-bit
[        ] E/MethodChannel#flutter/platform_views(27978):       at java.lang.Runtime.loadLibrary0(Runtime.java:989)
[        ] E/MethodChannel#flutter/platform_views(27978):       at java.lang.System.loadLibrary(System.java:1562)
[        ] E/MethodChannel#flutter/platform_views(27978):       at org.chromium.base.library_loader.LibraryLoader.c(SourceFile:65)
[        ] E/MethodChannel#flutter/platform_views(27978):       ... 40 more
[  +12 ms] E/flutter (27978): [ERROR:flutter/lib/ui/ui_dart_state.cc(148)] Unhandled Exception: PlatformException(error, java.lang.reflect.InvocationTargetException,
null)
[        ] E/flutter (27978): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:564:7)
[        ] E/flutter (27978): #1      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:316:33)
[        ] E/flutter (27978): <asynchronous suspension>
[        ] E/flutter (27978): #2      AndroidViewController._create (package:flutter/src/services/platform_views.dart:639:54)
[        ] E/flutter (27978): <asynchronous suspension>
[        ] E/flutter (27978): #3      AndroidViewController.setSize (package:flutter/src/services/platform_views.dart:556:14)
[        ] E/flutter (27978): <asynchronous suspension>
[        ] E/flutter (27978): #4      RenderAndroidView._sizePlatformView (package:flutter/src/rendering/platform_view.dart:189:29)
[        ] E/flutter (27978): <asynchronous suspension>
[        ] E/flutter (27978): #5      RenderAndroidView.performResize (package:flutter/src/rendering/platform_view.dart:170:5)
[        ] E/flutter (27978): #6      RenderObject.layout (package:flutter/src/rendering/object.dart:1604:9)
[        ] E/flutter (27978): #7      _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout
(package:flutter/src/rendering/proxy_box.dart:105:13)
[        ] E/flutter (27978): #8      RenderObject.layout (package:flutter/src/rendering/object.dart:1619:7)
[        ] E/flutter (27978): #9      RenderStack.performLayout (package:flutter/src/rendering/stack.dart:510:15)
[        ] E/flutter (27978): #10     RenderObject.layout (package:flutter/src/rendering/object.dart:1619:7)
[        ] E/flutter (27978): #11     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout
(package:flutter/src/rendering/proxy_box.dart:105:13)
[        ] E/flutter (27978): #12     RenderObject.layout (package:flutter/src/rendering/object.dart:1619:7)
[   +1 ms] E/flutter (27978): #13     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout
(package:flutter/src/rendering/proxy_box.dart:105:13)
[   +1 ms] E/flutter (27978): #14     RenderObject.layout (package:flutter/src/rendering/object.dart:1619:7)
[        ] E/flutter (27978): #15     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout
(package:flutter/src/rendering/proxy_box.dart:105:13)
[   +1 ms] E/flutter (27978): #16     RenderObject.layout (package:flutter/src/rendering/object.dart:1619:7)
[        ] E/flutter (27978): #17     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout
(package:flutter/src/rendering/proxy_box.dart:105:13)
[   +4 ms] E/flutter (27978): #18     RenderObject.layout (package:flutter/src/rendering/object.dart:1619:7)
[        ] E/flutter (27978): #19     RenderStack.performLayout (package:flutter/src/rendering/stack.dart:510:15)
[        ] E/flutter (27978): #20     RenderObject.layout (package:flutter/src/rendering/object.dart:1619:7)
[        ] E/flutter (27978): #21     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout
(package:flutter/src/rendering/proxy_box.dart:105:13)
[        ] E/flutter (27978): #22     RenderObject.layout (package:flutter/src/rendering/object.dart:1619:7)
[        ] E/flutter (27978): #23     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout
(package:flutter/src/rendering/proxy_box.dart:105:13)
[        ] E/flutter (27978): #24     RenderObject.layout (package:flutter/src/rendering/object.dart:1619:7)
[        ] E/flutter (27978): #25     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout
(package:flutter/src/rendering/proxy_box.dart:105:13)
[        ] E/flutter (27978): #26     RenderObject.layout (package:flutter/src/rendering/object.dart:1619:7)
[        ] E/flutter (27978): #27     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout
(package:flutter/src/rendering/proxy_box.dart:105:13)
[        ] E/flutter (27978): #28     RenderObject.layout (package:flutter/src/rendering/object.dart:1619:7)
[        ] E/flutter (27978): #29     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout
(package:flutter/src/rendering/proxy_box.dart:105:13)
[        ] E/flutter (27978): #30     RenderObject.layout (package:flutter/src/rendering/object.dart:1619:7)
[        ] E/flutter (27978): #31     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout
(package:flutter/src/rendering/proxy_box.dart:105:13)
[        ] E/flutter (27978): #32     RenderOffstage.performLayout (package:flutter/src/rendering/proxy_box.dart:3076:13)
[        ] E/flutter (27978): #33     RenderObject.layout (package:flutter/src/rendering/object.dart:1619:7)
[        ] E/flutter (27978): #34     RenderStack.performLayout (package:flutter/src/rendering/stack.dart:510:15)
[        ] E/flutter (27978): #35     RenderObject.layout (package:flutter/src/rendering/object.dart:1619:7)
[        ] E/flutter (27978): #36     __RenderTheatre&RenderBox&RenderObjectWithChildMix
[ +511 ms] -> 6c5aa7b9-6b32-47e6-98bb-28487667b1af

```
## flutter doctor -v

```
[✓] Flutter (Channel stable, v1.7.8+hotfix.3, on Mac OS X 10.14.5 18F132, locale zh-Hans-CN)
    • Flutter version 1.7.8+hotfix.3 at /Users/ld/tools/flutter
    • Framework revision b712a172f9 (8 days ago), 2019-07-09 13:14:38 -0700
    • Engine revision 54ad777fd2
    • Dart version 2.4.0

 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/ld/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
    • All Android licenses accepted.

[!] Xcode - develop for iOS and macOS
    ✗ Xcode installation is incomplete; a full installation is necessary for iOS development.
      Download at: https://developer.apple.com/xcode/download/
      Or install Xcode via the App Store.
      Once installed, run:
        sudo xcode-select --switch /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.7.4

[✗] iOS tools - develop for iOS devices
    ✗ libimobiledevice and ideviceinstaller are not installed. To install with Brew, run:
        brew update
        brew install --HEAD usbmuxd
        brew link usbmuxd
        brew install --HEAD libimobiledevice
        brew install ideviceinstaller
    ✗ ios-deploy not installed. To install:
        brew install ios-deploy

[✓] Android Studio (version 3.4)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 36.1.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

[!] IntelliJ IDEA Community Edition (version 2018.3)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.dev/intellij-setup/#installing-the-plugins

[✓] Connected device (1 available)
    • Nexus 6P • ENU7N15C29000856 • android-arm64 • Android 7.1.2 (API 25)

! Doctor found issues in 3 categories.
```
## device info
![image](https://user-images.githubusercontent.com/17489199/61361104-672a9600-a8b2-11e9-9600-a4fa5a7af14e.png)

**Comment by BondarenkoStas** [comment]
@lyodooo Can you please try if you encounter the issue using current flutter stable or master?

**Comment by iapicca** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
  
Thanks for your contribution.
