### ISSUE TITLE
Firebase plugin causes iOS not to build

### ISSUE THREAD

**Issue by Ruben-Krueger** [flutter/flutter#36390]
## Steps to Reproduce

1. Follow installation instructions for firebase and google sign in plugins
2. Flutter run

pubspec.yaml
``
dependencies:
  flutter:
    sdk: flutter

  transparent_image: ^1.0.0

  google_sign_in: ^4.0.4

  firebase_auth: ^0.6.2+1
``

  http: ^0.12.0+2

## Logs

```
Flutter output:
#0      throwToolExit (package:flutter_tools/src/base/common.dart:28:3)
#1      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:475:7)
<asynchronous suspension>
#2      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:478:18)
<asynchronous suspension>
#3      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:383:33)
<asynchronous suspension>
#4      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:29)
<asynchronous suspension>
#5      _rootRun (dart:async/zone.dart:1124:13)
#6      _CustomZone.run (dart:async/zone.dart:1021:19)
#7      _runZoned (dart:async/zone.dart:1516:10)
#8      runZoned (dart:async/zone.dart:1463:12)
#9      AppContext.run (package:flutter_tools/src/base/context.dart:152:18)
<asynchronous suspension>
#10     FlutterCommand.run (package:flutter_tools/src/runner/flutter_command.dart:375:20)
#11     CommandRunner.runCommand (package:args/command_runner.dart:197:27)
<asynchronous suspension>
#12     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:396:21)
<asynchronous suspension>
#13     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:29)
<asynchronous suspension>
#14     _rootRun (dart:async/zone.dart:1124:13)
#15     _CustomZone.run (dart:async/zone.dart:1021:19)
#16     _runZoned (dart:async/zone.dart:1516:10)
#17     runZoned (dart:async/zone.dart:1463:12)
#18     AppContext.run (package:flutter_tools/src/base/context.dart:152:18)
<asynchronous suspension>
#19     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:356:19)
<asynchronous suspension>
#20     CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:112:25)
#21     new Future.sync (dart:async/future.dart:224:31)
#22     CommandRunner.run (package:args/command_runner.dart:112:14)
#23     FlutterCommandRunner.run (package:flutter_tools/src/runner/flutter_command_runner.dart:242:18)
#24     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:62:22)
<asynchronous suspension>
#25     _rootRun (dart:async/zone.dart:1124:13)
#26     _CustomZone.run (dart:async/zone.dart:1021:19)
#27     _runZoned (dart:async/zone.dart:1516:10)
#28     runZoned (dart:async/zone.dart:1500:12)
#29     run.<anonymous closure> (package:flutter_tools/runner.dart:60:18)
<asynchronous suspension>
#30     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:29)
<asynchronous suspension>
#31     _rootRun (dart:async/zone.dart:1124:13)
#32     _CustomZone.run (dart:async/zone.dart:1021:19)
#33     _runZoned (dart:async/zone.dart:1516:10)
#34     runZoned (dart:async/zone.dart:1463:12)
#35     AppContext.run (package:flutter_tools/src/base/context.dart:152:18)
<asynchronous suspension>
#36     runInContext (package:flutter_tools/src/context_runner.dart:56:24)
<asynchronous suspension>
#37     run (package:flutter_tools/runner.dart:51:10)
#38     main (package:flutter_tools/executable.dart:62:9)
<asynchronous suspension>
#39     main (file:///Users/rubenkrueger/downloads/flutter/packages/flutter_tools/bin/flutter_tools.dart:8:3)
#40     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:299:32)
#41     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:12)

Xcode:
Failed to build iOS app
Error output from Xcode build:
↳
    ** BUILD FAILED **


Xcode's output:
↳
    === BUILD TARGET firebase_auth OF PROJECT Pods WITH CONFIGURATION Debug ===
    /Users/rubenkrueger/downloads/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_auth-0.6.6/ios/Classes/FirebaseAuthPlugin.m:85:57: error: incompatible block pointer types sending 'void (^)(FIRUser *__strong, NSError *__strong)' to parameter of type 'FIRAuthDataResultCallback _Nullable' (aka 'void (^)(FIRAuthDataResult * _Nullable __strong, NSError * _Nullable __strong)')
                                                 completion:^(FIRUser *user, NSError *error) {
                                                            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    In module 'FirebaseAuth' imported from /Users/rubenkrueger/comuno/ios/Pods/Headers/Public/Firebase/Firebase.h:12:
    /Users/rubenkrueger/comuno/ios/Pods/FirebaseAuth/Firebase/Auth/Source/Public/FIRAuth.h:500:66: note: passing argument to parameter 'completion' here
                      completion:(nullable FIRAuthDataResultCallback)completion;
                                                                     ^
    /Users/rubenkrueger/downloads/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_auth-0.6.6/ios/Classes/FirebaseAuthPlugin.m:92:57: error: incompatible block pointer types sending 'void (^)(FIRUser *__strong, NSError *__strong)' to parameter of type 'FIRAuthDataResultCallback _Nullable' (aka 'void (^)(FIRAuthDataResult * _Nullable __strong, NSError * _Nullable __strong)')
                                                 completion:^(FIRUser *user, NSError *error) {
                                                            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    In module 'FirebaseAuth' imported from /Users/rubenkrueger/comuno/ios/Pods/Headers/Public/Firebase/Firebase.h:12:
    /Users/rubenkrueger/comuno/ios/Pods/FirebaseAuth/Firebase/Auth/Source/Public/FIRAuth.h:500:66: note: passing argument to parameter 'completion' here
                      completion:(nullable FIRAuthDataResultCallback)completion;
                                                                     ^
    /Users/rubenkrueger/downloads/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_auth-0.6.6/ios/Classes/FirebaseAuthPlugin.m:101:57: error: incompatible block pointer types sending 'void (^)(FIRUser *__strong, NSError *__strong)' to parameter of type 'FIRAuthDataResultCallback _Nullable' (aka 'void (^)(FIRAuthDataResult * _Nullable __strong, NSError * _Nullable __strong)')
                                                 completion:^(FIRUser *user, NSError *error) {
                                                            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    In module 'FirebaseAuth' imported from /Users/rubenkrueger/comuno/ios/Pods/Headers/Public/Firebase/Firebase.h:12:
    /Users/rubenkrueger/comuno/ios/Pods/FirebaseAuth/Firebase/Auth/Source/Public/FIRAuth.h:500:66: note: passing argument to parameter 'completion' here
                      completion:(nullable FIRAuthDataResultCallback)completion;
                                                                     ^
    /Users/rubenkrueger/downloads/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_auth-0.6.6/ios/Classes/FirebaseAuthPlugin.m:108:57: error: incompatible block pointer types sending 'void (^)(FIRUser *__strong, NSError *__strong)' to parameter of type 'FIRAuthDataResultCallback _Nullable' (aka 'void (^)(FIRAuthDataResult * _Nullable __strong, NSError * _Nullable __strong)')
                                                 completion:^(FIRUser *user, NSError *error) {
                                                            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    In module 'FirebaseAuth' imported from /Users/rubenkrueger/comuno/ios/Pods/Headers/Public/Firebase/Firebase.h:12:
    /Users/rubenkrueger/comuno/ios/Pods/FirebaseAuth/Firebase/Auth/Source/Public/FIRAuth.h:500:66: note: passing argument to parameter 'completion' here
                      completion:(nullable FIRAuthDataResultCallback)completion;
                                                                     ^
    /Users/rubenkrueger/downloads/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_auth-0.6.6/ios/Classes/FirebaseAuthPlugin.m:123:9: warning: 'fetchProvidersForEmail:completion:' is deprecated: Please use fetchSignInMethodsForEmail:completion: for Objective-C or fetchSignInMethods(forEmail:completion:) for Swift instead. [-Wdeprecated-declarations]
            fetchProvidersForEmail:email
            ^
    In module 'FirebaseAuth' imported from /Users/rubenkrueger/comuno/ios/Pods/Headers/Public/Firebase/Firebase.h:12:
    /Users/rubenkrueger/comuno/ios/Pods/FirebaseAuth/Firebase/Auth/Source/Public/FIRAuth.h:334:1: note: 'fetchProvidersForEmail:completion:' has been explicitly marked deprecated here
    DEPRECATED_MSG_ATTRIBUTE("Please use fetchSignInMethodsForEmail:completion: for Objective-C or "
    ^
    In module 'UIKit' imported from /Users/rubenkrueger/comuno/ios/Pods/Target Support Files/firebase_auth/firebase_auth-prefix.pch:2:
    In module 'Foundation' imported from /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator12.2.sdk/System/Library/Frameworks/UIKit.framework/Headers/UIKit.h:8:
    In module 'CoreFoundation' imported from /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator12.2.sdk/System/Library/Frameworks/Foundation.framework/Headers/Foundation.h:6:
    In module 'Darwin' imported from /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator12.2.sdk/System/Library/Frameworks/CoreFoundation.framework/Headers/CoreFoundation.h:16:
    /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator12.2.sdk/usr/include/AvailabilityMacros.h:180:64: note: expanded from macro 'DEPRECATED_MSG_ATTRIBUTE'
                #define DEPRECATED_MSG_ATTRIBUTE(s) __attribute__((deprecated(s)))
                                                                   ^
    /Users/rubenkrueger/downloads/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_auth-0.6.6/ios/Classes/FirebaseAuthPlugin.m:179:38: error: incompatible block pointer types sending 'void (^)(NSError * _Nullable __strong)' to parameter of type 'FIRAuthDataResultCallback _Nullable' (aka 'void (^)(FIRAuthDataResult * _Nullable __strong, NSError * _Nullable __strong)')
                              completion:^(NSError *_Nullable error) {
                                         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    In module 'FirebaseAuth' imported from /Users/rubenkrueger/comuno/ios/Pods/Headers/Public/Firebase/Firebase.h:12:
    /Users/rubenkrueger/comuno/ios/Pods/FirebaseAuth/Firebase/Auth/Source/Public/FIRUser.h:260:74: note: passing argument to parameter 'completion' here
                              completion:(nullable FIRAuthDataResultCallback)completion;
                                                                             ^
    /Users/rubenkrueger/downloads/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_auth-0.6.6/ios/Classes/FirebaseAuthPlugin.m:189:38: error: incompatible block pointer types sending 'void (^)(NSError * _Nullable __strong)' to parameter of type 'FIRAuthDataResultCallback _Nullable' (aka 'void (^)(FIRAuthDataResult * _Nullable __strong, NSError * _Nullable __strong)')
                              completion:^(NSError *_Nullable error) {
                                         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    In module 'FirebaseAuth' imported from /Users/rubenkrueger/comuno/ios/Pods/Headers/Public/Firebase/Firebase.h:12:
    /Users/rubenkrueger/comuno/ios/Pods/FirebaseAuth/Firebase/Auth/Source/Public/FIRUser.h:260:74: note: passing argument to parameter 'completion' here
                              completion:(nullable FIRAuthDataResultCallback)completion;
                                                                             ^
    /Users/rubenkrueger/downloads/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_auth-0.6.6/ios/Classes/FirebaseAuthPlugin.m:197:38: error: incompatible block pointer types sending 'void (^)(NSError * _Nullable __strong)' to parameter of type 'FIRAuthDataResultCallback _Nullable' (aka 'void (^)(FIRAuthDataResult * _Nullable __strong, NSError * _Nullable __strong)')
                              completion:^(NSError *_Nullable error) {
                                         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    In module 'FirebaseAuth' imported from /Users/rubenkrueger/comuno/ios/Pods/Headers/Public/Firebase/Firebase.h:12:
    /Users/rubenkrueger/comuno/ios/Pods/FirebaseAuth/Firebase/Auth/Source/Public/FIRUser.h:260:74: note: passing argument to parameter 'completion' here
                              completion:(nullable FIRAuthDataResultCallback)completion;
                                                                             ^
    /Users/rubenkrueger/downloads/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_auth-0.6.6/ios/Classes/FirebaseAuthPlugin.m:207:38: error: incompatible block pointer types sending 'void (^)(NSError * _Nullable __strong)' to parameter of type 'FIRAuthDataResultCallback _Nullable' (aka 'void (^)(FIRAuthDataResult * _Nullable __strong, NSError * _Nullable __strong)')
                              completion:^(NSError *_Nullable error) {
                                         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    In module 'FirebaseAuth' imported from /Users/rubenkrueger/comuno/ios/Pods/Headers/Public/Firebase/Firebase.h:12:
    /Users/rubenkrueger/comuno/ios/Pods/FirebaseAuth/Firebase/Auth/Source/Public/FIRUser.h:260:74: note: passing argument to parameter 'completion' here
                              completion:(nullable FIRAuthDataResultCallback)completion;
                                                                             ^
    /Users/rubenkrueger/downloads/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_auth-0.6.6/ios/Classes/FirebaseAuthPlugin.m:215:38: error: incompatible block pointer types sending 'void (^)(NSError * _Nullable __strong)' to parameter of type 'FIRAuthDataResultCallback _Nullable' (aka 'void (^)(FIRAuthDataResult * _Nullable __strong, NSError * _Nullable __strong)')
                              completion:^(NSError *_Nullable error) {
                                         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    In module 'FirebaseAuth' imported from /Users/rubenkrueger/comuno/ios/Pods/Headers/Public/Firebase/Firebase.h:12:
    /Users/rubenkrueger/comuno/ios/Pods/FirebaseAuth/Firebase/Auth/Source/Public/FIRUser.h:260:74: note: passing argument to parameter 'completion' here
                              completion:(nullable FIRAuthDataResultCallback)completion;
                                                                             ^
    /Users/rubenkrueger/downloads/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_auth-0.6.6/ios/Classes/FirebaseAuthPlugin.m:224:67: error: incompatible block pointer types sending 'void (^)(FIRUser *__strong, NSError *__strong)' to parameter of type 'FIRAuthDataResultCallback _Nullable' (aka 'void (^)(FIRAuthDataResult * _Nullable __strong, NSError * _Nullable __strong)')
                                                           completion:^(FIRUser *user, NSError *error) {
                                                                      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    In module 'FirebaseAuth' imported from /Users/rubenkrueger/comuno/ios/Pods/Headers/Public/Firebase/Firebase.h:12:
    /Users/rubenkrueger/comuno/ios/Pods/FirebaseAuth/Firebase/Auth/Source/Public/FIRUser.h:360:64: note: passing argument to parameter 'completion' here
                    completion:(nullable FIRAuthDataResultCallback)completion;
                                                                   ^
    /Users/rubenkrueger/downloads/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_auth-0.6.6/ios/Classes/FirebaseAuthPlugin.m:235:67: error: incompatible block pointer types sending 'void (^)(FIRUser *__strong, NSError *__strong)' to parameter of type 'FIRAuthDataResultCallback _Nullable' (aka 'void (^)(FIRAuthDataResult * _Nullable __strong, NSError * _Nullable __strong)')
                                                           completion:^(FIRUser *user, NSError *error) {
                                                                      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    In module 'FirebaseAuth' imported from /Users/rubenkrueger/comuno/ios/Pods/Headers/Public/Firebase/Firebase.h:12:
    /Users/rubenkrueger/comuno/ios/Pods/FirebaseAuth/Firebase/Auth/Source/Public/FIRUser.h:360:64: note: passing argument to parameter 'completion' here
                    completion:(nullable FIRAuthDataResultCallback)completion;
                                                                   ^
    /Users/rubenkrueger/downloads/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_auth-0.6.6/ios/Classes/FirebaseAuthPlugin.m:244:67: error: incompatible block pointer types sending 'void (^)(FIRUser *__strong, NSError *__strong)' to parameter of type 'FIRAuthDataResultCallback _Nullable' (aka 'void (^)(FIRAuthDataResult * _Nullable __strong, NSError * _Nullable __strong)')
                                                           completion:^(FIRUser *user, NSError *error) {
                                                                      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    In module 'FirebaseAuth' imported from /Users/rubenkrueger/comuno/ios/Pods/Headers/Public/Firebase/Firebase.h:12:
    /Users/rubenkrueger/comuno/ios/Pods/FirebaseAuth/Firebase/Auth/Source/Public/FIRUser.h:360:64: note: passing argument to parameter 'completion' here
                    completion:(nullable FIRAuthDataResultCallback)completion;
                                                                   ^
    /Users/rubenkrueger/downloads/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_auth-0.6.6/ios/Classes/FirebaseAuthPlugin.m:255:67: error: incompatible block pointer types sending 'void (^)(FIRUser *__strong, NSError *__strong)' to parameter of type 'FIRAuthDataResultCallback _Nullable' (aka 'void (^)(FIRAuthDataResult * _Nullable __strong, NSError * _Nullable __strong)')
                                                           completion:^(FIRUser *user, NSError *error) {
                                                                      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    In module 'FirebaseAuth' imported from /Users/rubenkrueger/comuno/ios/Pods/Headers/Public/Firebase/Firebase.h:12:
    /Users/rubenkrueger/comuno/ios/Pods/FirebaseAuth/Firebase/Auth/Source/Public/FIRUser.h:360:64: note: passing argument to parameter 'completion' here
                    completion:(nullable FIRAuthDataResultCallback)completion;
                                                                   ^
    /Users/rubenkrueger/downloads/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_auth-0.6.6/ios/Classes/FirebaseAuthPlugin.m:264:67: error: incompatible block pointer types sending 'void (^)(FIRUser *__strong, NSError *__strong)' to parameter of type 'FIRAuthDataResultCallback _Nullable' (aka 'void (^)(FIRAuthDataResult * _Nullable __strong, NSError * _Nullable __strong)')
                                                           completion:^(FIRUser *user, NSError *error) {
                                                                      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    In module 'FirebaseAuth' imported from /Users/rubenkrueger/comuno/ios/Pods/Headers/Public/Firebase/Firebase.h:12:
    /Users/rubenkrueger/comuno/ios/Pods/FirebaseAuth/Firebase/Auth/Source/Public/FIRUser.h:360:64: note: passing argument to parameter 'completion' here
                    completion:(nullable FIRAuthDataResultCallback)completion;
                                                                   ^
    /Users/rubenkrueger/downloads/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_auth-0.6.6/ios/Classes/FirebaseAuthPlugin.m:368:57: error: incompatible block pointer types sending 'void (^)(FIRUser *__strong, NSError *__strong)' to parameter of type 'FIRAuthDataResultCallback _Nullable' (aka 'void (^)(FIRAuthDataResult * _Nullable __strong, NSError * _Nullable __strong)')
                                                 completion:^(FIRUser *user, NSError *error) {
                                                            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    In module 'FirebaseAuth' imported from /Users/rubenkrueger/comuno/ios/Pods/Headers/Public/Firebase/Firebase.h:12:
    /Users/rubenkrueger/comuno/ios/Pods/FirebaseAuth/Firebase/Auth/Source/Public/FIRAuth.h:500:66: note: passing argument to parameter 'completion' here
                      completion:(nullable FIRAuthDataResultCallback)completion;
                                                                     ^
    /Users/rubenkrueger/downloads/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_auth-0.6.6/ios/Classes/FirebaseAuthPlugin.m:392:62: warning: implicit conversion loses integer precision: 'long' to 'int' [-Wshorten-64-to-32]
      userData[@"lastSignInTimestamp"] = [NSNumber numberWithInt:lastSignInDate];
                                         ~                       ^~~~~~~~~~~~~~
    2 warnings and 15 errors generated.

Could not build the application for the simulator.
Error launching application on iPhone Xʀ.


```
[✓] Flutter (Channel stable, v1.7.8+hotfix.3, on Mac OS X 10.14.5 18F132, locale en-US)
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 10.2.1)
[✓] iOS tools - develop for iOS devices
[✓] Android Studio (version 3.2)
[!] VS Code (version 1.31.1)
    ✗ Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter
[✓] Connected device (1 available)

! Doctor found issues in 1 category.
```

**Comment by kroikie** [comment]
@Ruben-Krueger

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/1098. Any further collaboration will be done there.
