### ISSUE TITLE
When running tests with the "connectivity" package an error is thrown.

### ISSUE THREAD

**Issue by earyzhe** [flutter/flutter#36440]
## Steps to Reproduce

When running a test with the "connectivity" package an error is thrown. This error is not thrown when running the application normally in an emulator.

## Logs

Run with "flutter test"

```
══╡ EXCEPTION CAUGHT BY SERVICES LIBRARY ╞══════════════════════════════════════════════════════════
The following MissingPluginException was thrown while activating platform stream on channel
plugins.flutter.io/connectivity_status:
MissingPluginException(No implementation found for method listen on channel
plugins.flutter.io/connectivity_status)

When the exception was thrown, this was the stack:
#0      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:314:7)
<asynchronous suspension>
#1      EventChannel.receiveBroadcastStream.<anonymous closure> (package:flutter/src/services/platform_channel.dart:504:29)
<asynchronous suspension>
#9      new MainModel (package:shutterstock_scroll/logic/main_model.dart:37:40)
#10     main (file:///Users/earyzhe/dev/FlutterProjects/shutterstock_scroll/test/main_model_test.dart:49:17)
#12     main (file:///Users/earyzhe/dev/FlutterProjects/shutterstock_scroll/test/main_model_test.dart:11:10)
#17     Declarer.declare (package:test_api/src/backend/declarer.dart:127:22)
#18     RemoteListener.start.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:test_api/src/remote_listener.dart:124:26)
(elided 26 frames from package dart:async and package dart:async-patch)
════════════════════════════════════════════════════════════════════════════════════════════════════
```

```
Analyzing shutterstock_scroll...                                        
No issues found! (ran in 2.0s)
```

```
earyzhe@MacBook-Pro-2:~/dev/FlutterProjects/shutterstock_scroll$ flutter doctor -v
[✓] Flutter (Channel stable, v1.7.8+hotfix.3, on Mac OS X 10.14.5 18F132, locale en-GB)
    • Flutter version 1.7.8+hotfix.3 at /Users/earyzhe/dev/SDKs/flutter
    • Framework revision b712a172f9 (9 days ago), 2019-07-09 13:14:38 -0700
    • Engine revision 54ad777fd2
    • Dart version 2.4.0

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/earyzhe/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 10.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.2.1, Build version 10E1001
    • CocoaPods version 1.7.4

[✓] iOS tools - develop for iOS devices
    • ios-deploy 1.9.4

[✓] Android Studio (version 3.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 33.3.1
    • Dart plugin version 182.5215
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)

[✓] IntelliJ IDEA Community Edition (version 2018.3.4)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 33.2.2
    • Dart plugin version 183.5901

[✓] VS Code (version 1.36.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.2.0

[✓] Connected device (1 available)
    • iPhone 8 Plus • E99EAA77-7875-4E70-9D09-34C74EF7FD1A • ios • com.apple.CoreSimulator.SimRuntime.iOS-12-2 (simulator)
```

**Comment by DenisMrGnusa** [comment]
is there an answer to this question?

**Comment by stevanus1997** [comment]
you just need to flutter run again

**Comment by BondarenkoStas** [comment]
Will just leave it here in case any answer will appear https://stackoverflow.com/questions/56546254/no-implementation-found-for-method-listen-on-channel-for-connectionstatus-librar.
Is the issue still relevant?

**Comment by iapicca** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
  
Thanks for your contribution.
