### ISSUE TITLE
ERROR:flutter/runtime/dart_isolate.cc(808)

### ISSUE THREAD

**Issue by MahdiPishguy** [flutter/flutter#36443]
when i run flutter application i get this error:
```
> E/DartVM  (17840): vm-service: Error: Unhandled exception:
> E/DartVM  (17840): Unrecognized response: null
> E/DartVM  (17840): #0      new Response.from (dart:_vmservice/message_router.dart:70:7)
> E/DartVM  (17840): #1      Message._setResponseFromPort (dart:_vmservice/message.dart:244:29)
> E/DartVM  (17840): #2      Message.sendToVM.<anonymous closure> (dart:_vmservice/message.dart:216:7)
> E/DartVM  (17840): #3      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:12)
> E/DartVM  (17840): 
> Lost connection to device.
> E/flutter (17840): [ERROR:flutter/runtime/dart_isolate.cc(808)] Unhandled exception:
> E/flutter (17840): Unrecognized response: null
> E/flutter (17840): #0      new Response.from (dart:_vmservice/message_router.dart:70:7)
> E/flutter (17840): #1      Message._setResponseFromPort (dart:_vmservice/message.dart:244:29)
> E/flutter (17840): #2      Message.sendToVM.<anonymous closure> (dart:_vmservice/message.dart:216:7)
> Failed to send request: {"jsonrpc":"2.0","id":"7","method":"getVM","params":{}}
```
`flutter doctor` result:

```
[√] Flutter (Channel master, v1.8.2-pre.81, on Microsoft Windows [Version 10.0.17763.615], locale en-US)
    • Flutter version 1.8.2-pre.81 at E:\Software\flutter
    • Framework revision 578204df19 (13 hours ago), 2019-07-17 18:24:24 -0700
    • Engine revision f348270047
    • Dart version 2.5.0 (build 2.5.0-dev.1.0 2b3336b51e)


[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at E:\Software\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = E:\Software\sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[X] Visual Studio - develop for Windows
    X Visual Studio not installed; this is necessary for Windows development.
      Download at https://visualstudio.microsoft.com/downloads/.

[√] Android Studio (version 3.6)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 37.0.2
    • Dart plugin version 191.7830
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)

[√] VS Code (version 1.35.0)
    • VS Code at C:\Users\mahdi\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.1.0

[√] Connected device (3 available)
    • WAS LX1A • 2XJDU17C14006203 • android-arm64  • Android 8.0.0 (API 26)
    • Windows  • Windows          • windows-x64    • Microsoft Windows [Version 10.0.17763.615]
    • Chrome   • chrome           • web-javascript • Google Chrome 74.0.3729.131

! Doctor found issues in 1 category.

E:\Software\flutter>

```

**Comment by BondarenkoStas** [comment]
@MahdiPishguy Is the issue still relevant? Can you please try it with current stable and current master version?
If yes, please provide  a small self-contained app that demonstrates the problem. You can include small examples [inline if they're enclosed by backticks](https://help.github.com/en/articles/creating-and-highlighting-code-blocks), or just provide a public link to a github "gist" - https://gist.github.com/.

**Comment by MahdiPishguy** [comment]
@BondarenkoStas this problem happens on when i try to debug application, unfortunately i can't make small project because i don't really when that happen and which action cause of getting this error

**Comment by MahdiPishguy** [comment]
@BondarenkoStas i think, after updating dart and flutter version, that cause of solve problem, but still i'm not sure

**Comment by BondarenkoStas** [comment]
Ok, I think it will be fine to close the issue for now, as there is not much info where to investigate it. If you encounter it again @MahdiPishguy or have any new input, please don't hesitate to comment this one and I will re-open it right away, or file a new issue.

**Comment by othniel7195** [comment]
@MahdiPishguy  How to solve the problem

**Comment by MahdiPishguy** [comment]
> 
> 
> @MahdiPishguy How to solve the problem

I updated to latest version of Dart, i think i updated to beta channel
