### ISSUE TITLE
Issue between 1.5.8 and 1.6.0

### ISSUE THREAD

**Issue by dolphinxx** [flutter/flutter#36444]
## Steps to Reproduce

I have written a flutter plugin for baidu TTS, [https://github.com/dolphinxx/flutter_baidu_tts](https://github.com/dolphinxx/flutter_baidu_tts), it contains some jni libs for android [here](https://github.com/dolphinxx/flutter_baidu_tts/tree/master/android/libs).
It keeps working until upgrading flutter from `v1.5.4-hotfix.2` to `v1.7.8+hotfix.3` yesterday,  I also switched flutter version to `v1.8.1`, `v1.7.11` and `v1.6.0`,  but with no luck. Then I switch flutter to `v1.5.8`, the plugin works fine again. 
So I guess there may be something different between `v1.5.8` and `v1.6.0` which effects the jni library. I cannot figure out it from the changelog, so can you please help me.

It can be reproduced by following steps:
1. clone the plugin  [here](https://github.com/dolphinxx/flutter_baidu_tts)
2. run the example on android device.
3. click `init` button, then click the play icon(small triangle) at the bottom, if the flutter version is `1.5.8` or bellow, the tts will start to speak. However if you switch flutter version to `1.6.0` or higher, the tts will never speak.

## Logs

```
```

```
```

`flutter doctor -v` for `1.6.0`
```
[√] Flutter (Channel unknown, v1.6.0, on Microsoft Windows [Version 10.0.17134.648], locale zh-CN)
    • Flutter version 1.6.0 at E:\devtools\flutter
    • Framework revision ed90d05596 (9 weeks ago), 2019-05-14 17:09:29 -0700
    • Engine revision 832cdacc6f
    • Dart version 2.3.1 (build 2.3.1-dev.0.0 a0290f823c)


[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at E:\devtools\android-sdk-windows
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-Q, build-tools 28.0.3
    • Java binary at: E:\devtools\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
    • All Android licenses accepted.

[√] Android Studio (version 3.4)
    • Android Studio at E:\devtools\Android Studio
    • Flutter plugin version 37.0.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
```

`flutter doctor` for `1.5.8`
```
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel unknown, v1.5.8, on Microsoft Windows [Version 10.0.17134.648], locale zh-CN)

[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[√] Android Studio (version 3.4)
[!] IntelliJ IDEA Ultimate Edition (version 2018.1)
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
[!] IntelliJ IDEA Ultimate Edition (version 2019.1)
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
[√] Connected device (1 available)

! Doctor found issues in 2 categories.
```

**Comment by dolphinxx** [comment]
I decompiled the Baidu SDK today and did some debugging, and finally I caught an exception related to this issue:
```
E/----: b.a.a.C.a.a()
    java.lang.reflect.UndeclaredThrowableException
        at $Proxy4.onSynthesizeStart(Unknown Source)
        at com.baidu.tts.a.c.B$1.onSynthesizeStart(B.java:91)
        at com.baidu.tts.b.a.a.A.a(A.java:96)
        at com.baidu.tts.b.a.a.C$a.a(C.java:186)
        at com.baidu.tts.b.a.a.C$a.call(C.java:206)
        at com.baidu.tts.b.a.a.C$a.call(C.java:176)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:784)
     Caused by: java.lang.reflect.InvocationTargetException
        at java.lang.reflect.Method.invoke(Native Method)
        at com.baidu.tts.aop.AInterceptorHandler.invoke(AInterceptorHandler.java:51)
        at java.lang.reflect.Proxy.invoke(Proxy.java:1006)
        at $Proxy4.onSynthesizeStart(Unknown Source) 
        at com.baidu.tts.a.c.B$1.onSynthesizeStart(B.java:91) 
        at com.baidu.tts.b.a.a.A.a(A.java:96) 
        at com.baidu.tts.b.a.a.C$a.a(C.java:186) 
        at com.baidu.tts.b.a.a.C$a.call(C.java:206) 
        at com.baidu.tts.b.a.a.C$a.call(C.java:176) 
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) 
        at java.lang.Thread.run(Thread.java:784) 
     Caused by: java.lang.RuntimeException: Methods marked with @UiThread must be executed on the main thread. Current thread: EngineExecutorPoolThread(1)
        at io.flutter.embedding.engine.FlutterJNI.ensureRunningOnMainThread(FlutterJNI.java:807)
        at io.flutter.embedding.engine.FlutterJNI.dispatchPlatformMessage(FlutterJNI.java:697)
        at io.flutter.embedding.engine.dart.DartMessenger.send(DartMessenger.java:80)
        at io.flutter.embedding.engine.dart.DartExecutor.send(DartExecutor.java:187)
        at io.flutter.view.FlutterNativeView.send(FlutterNativeView.java:128)
        at io.flutter.plugin.common.MethodChannel.invokeMethod(MethodChannel.java:98)
        at io.flutter.plugin.common.MethodChannel.invokeMethod(MethodChannel.java:84)
        at com.whaleread.flutter_baidu_tts.Tts.onSynthesizeStart(Tts.java:437)
        at com.baidu.tts.a.b.A$1.onSynthesizeStart(A.java:62)
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.baidu.tts.aop.AInterceptorHandler.invoke(AInterceptorHandler.java:51) 
        at java.lang.reflect.Proxy.invoke(Proxy.java:1006) 
        at $Proxy4.onSynthesizeStart(Unknown Source) 
        at com.baidu.tts.a.c.B$1.onSynthesizeStart(B.java:91) 
        at com.baidu.tts.b.a.a.A.a(A.java:96) 
        at com.baidu.tts.b.a.a.C$a.a(C.java:186) 
        at com.baidu.tts.b.a.a.C$a.call(C.java:206) 
        at com.baidu.tts.b.a.a.C$a.call(C.java:176) 
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) 
        at java.lang.Thread.run(Thread.java:784) 
```

This issue comes only with Flutter `v1.6.0` and above, even with the latest `v1.9.5`

**Comment by dolphinxx** [comment]
Duplicate of #34993
