### ISSUE TITLE
null does not support macOS desktop development

### ISSUE THREAD

**Issue by franciscojma86** [flutter/flutter#36473]
Getting an exception when running the linux FDE example app. Got it working after checking out the latest engine commit in the Flutter framework f3482700474a791dabe9c4783568ed0fe512b04d. I have since pulled the latest engine commit and it still works, even after running flutter --local-engine=host_debug_unopt clean.

I also saw this on macOS two days ago, but don't have the trace for that

Trace:

## command

flutter --local-engine=host_debug_unopt run

## exception

_Exception: Exception: null does not support macOS desktop development

```
#0      _artifactToFileName (package:flutter_tools/src/artifacts.dart:74:9)
#1      LocalEngineArtifacts.getArtifactPath (package:flutter_tools/src/artifacts.dart:342:37)
#2      flutterMacOSFrameworkDir (package:flutter_tools/src/ios/xcodeproj.dart:31:54)
#3      updateGeneratedXcodeProperties (package:flutter_tools/src/ios/xcodeproj.dart:78:11)
<asynchronous suspension>
#4      MacOSProject._updateGeneratedXcodeConfigIfNeeded (package:flutter_tools/src/project.dart:703:13)
<asynchronous suspension>
#5      MacOSProject.ensureReadyForPlatformSpecificTooling (package:flutter_tools/src/project.dart:698:11)
<asynchronous suspension>
#6      FlutterProject.ensureReadyForPlatformSpecificTooling (package:flutter_tools/src/project.dart:210:19)
<asynchronous suspension>
#7      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:474:21)
<asynchronous suspension>
#8      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:384:33)
#9      _AsyncAwaitCompleter.start (dart:async-patch/async_patch.dart:49:6)
#10     FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:379:13)
#11     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:154:29)
#12     _AsyncAwaitCompleter.start (dart:async-patch/async_patch.dart:49:6)
#13     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:154:7)
#14     _rootRun (dart:async/zone.dart:1124:13)
#15     _CustomZone.run (dart:async/zone.dart:1021:19)
#16     _runZoned (dart:async/zone.dart:1516:10)
#17     runZoned (dart:async/zone.dart:1463:12)
#18     AppContext.run (package:flutter_tools/src/base/context.dart:153:18)
#19     _AsyncAwaitCompleter.start (dart:async-patch/async_patch.dart:49:6)
#20     AppContext.run (package:flutter_tools/src/base/context.dart:140:19)
#21     FlutterCommand.run (package:flutter_tools/src/runner/flutter_command.dart:376:20)
#22     CommandRunner.runCommand (package:args/command_runner.dart:197:27)
#23     _AsyncAwaitCompleter.start (dart:async-patch/async_patch.dart:49:6)
#24     CommandRunner.runCommand (package:args/command_runner.dart:145:23)
#25     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:396:21)
#26     _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:77:64)
#27     _rootRunUnary (dart:async/zone.dart:1132:38)
#28     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#29     _FutureListener.handleValue (dart:async/future_impl.dart:126:18)
#30     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:639:45)
#31     Future._propagateToListeners (dart:async/future_impl.dart:668:32)
#32     Future._complete (dart:async/future_impl.dart:473:7)
#33     _SyncCompleter.complete (dart:async/future_impl.dart:51:12)
#34     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:28:18)
#35     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:294:13)
#36     FlutterVersion.checkFlutterVersionFreshness (package:flutter_tools/src/version.dart)
#37     _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:77:64)
#38     _rootRunUnary (dart:async/zone.dart:1132:38)
#39     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#40     _FutureListener.handleValue (dart:async/future_impl.dart:126:18)
#41     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:639:45)
#42     Future._propagateToListeners (dart:async/future_impl.dart:668:32)
#43     Future._complete (dart:async/future_impl.dart:473:7)
#44     _SyncCompleter.complete (dart:async/future_impl.dart:51:12)
#45     _AsyncAwaitCompleter.complete.<anonymous closure> (dart:async-patch/async_patch.dart:33:20)
#46     _rootRun (dart:async/zone.dart:1120:38)
#47     _CustomZone.run (dart:async/zone.dart:1021:19)
#48     _CustomZone.runGuarded (dart:async/zone.dart:923:7)
#49     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:963:23)
#50     _rootRun (dart:async/zone.dart:1124:13)
#51     _CustomZone.run (dart:async/zone.dart:1021:19)
#52     _CustomZone.runGuarded (dart:async/zone.dart:923:7)
#53     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:963:23)
#54     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)

[ +146 ms] [✓] Flutter (Channel master, v1.7.4-pre.413, on Linux, locale en_US.UTF-8)
[        ]     • Flutter version 1.7.4-pre.413 at /usr/local/google/home/franciscojma/Developer/flutter
[        ]     • Framework revision 5a34e7981e (13 minutes ago), 2019-07-18 10:45:37 -0700
[        ]     • Engine revision f348270047
[        ]     • Dart version 2.5.0 (build 2.5.0-dev.1.0 2b3336b51e)
[+1326 ms] [✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[        ]     • Android SDK at /usr/local/google/home/franciscojma/Android/Sdk
[        ]     • Android NDK location not configured (optional; useful for native profiling support)
[        ]     • Platform android-29, build-tools 28.0.3
[        ]     • Java binary at: /opt/android-studio-with-blaze-3.4/jre/bin/java
[        ]     • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b16-5323222)
[        ]     • All Android licenses accepted.
[   +1 ms] [✓] Chrome - develop for the web
[        ]     • Chrome at google-chrome
[        ] [✓] Linux toolchain - develop for Linux desktop
[        ]     • clang++ 4.0.1
[        ]     • GNU Make 4.1
[        ] [✓] Android Studio (version 3.4)
[        ]     • Android Studio at /opt/android-studio-with-blaze-3.4
[        ]     • Flutter plugin version 36.0.1
[        ]     • Dart plugin version 183.6270
[        ]     • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b16-5323222)
[        ] [✓] VS Code (version 1.36.1)
[        ]     • VS Code at /usr/share/code
[        ]     • Flutter extension version 3.2.0
[        ] [✓] Connected device (2 available)
[        ]     • Linux  • Linux  • linux-x64      • Linux
[        ]     • Chrome • chrome • web-javascript • Google Chrome 75.0.3770.142 
[        ] • No issues found!

**Comment by blasten** [comment]
It looks like we don't pass the target platform in https://github.com/flutter/flutter/blob/master/packages/flutter_tools/lib/src/artifacts.dart#L342

**Comment by stuartmorgan** [comment]
Capturing from offline discussion, separately from the specific error here it seems like we should take at look at whether `FlutterProject.ensureReadyForPlatformSpecificTooling` actually needs to run every platform's updates, vs. only the one being currently built. It seems like it would be simpler/faster to update only the necessary platform projects.

**Comment by jonahwilliams** [comment]
I did not add tests for these checks, so I will roll them back.
