### ISSUE TITLE
Image Picker - Error Piking Image "PlatformException(already_active, Image picker is already active, null)"

### ISSUE THREAD

**Issue by FlutterForefront** [flutter/flutter#36529]
```
E/flutter (23001): [ERROR:flutter/lib/ui/ui_dart_state.cc(148)] Unhandled Exception: PlatformException(already_active, Image picker is already active, null)
E/flutter (23001): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:564:7)
E/flutter (23001): #1      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:316:33)
E/flutter (23001): <asynchronous suspension>
E/flutter (23001): #2      ImagePicker.pickImage (package:image_picker/image_picker.dart:50:40)
E/flutter (23001): <asynchronous suspension>
E/flutter (23001): #3      _MyHomePageState._onImageButtonPressed.<anonymous closure> (package:vendor_app/main.dart:64:34)
E/flutter (23001): #4      State.setState (package:flutter/src/widgets/framework.dart:1141:30)
E/flutter (23001): #5      _MyHomePageState._onImageButtonPressed (package:vendor_app/main.dart:45:5)
E/flutter (23001): #6      _MyHomePageState.build.<anonymous closure> (package:vendor_app/main.dart:149:15)
E/flutter (23001): #7      _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:635:14)
E/flutter (23001): #8      _InkResponseState.build.<anonymous closure> (package:flutter/src/material/ink_well.dart:711:32)
E/flutter (23001): #9      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:182:24)
E/flutter (23001): #10     TapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:365:11)
E/flutter (23001): #11     TapGestureRecognizer.acceptGesture (package:flutter/src/gestures/tap.dart:312:7)
E/flutter (23001): #12     GestureArenaManager.sweep (package:flutter/src/gestures/arena.dart:156:27)
E/flutter (23001): #13     _WidgetsFlutterBinding&BindingBase&GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:222:20)
E/flutter (23001): #14     _WidgetsFlutterBinding&BindingBase&GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:198:22)
E/flutter (23001): #15     _WidgetsFlutterBinding&BindingBase&GestureBinding._handlePointerEvent (package:flutter/src/gestures/binding.dart:156:7)
E/flutter (23001): #16     _WidgetsFlutterBinding&BindingBase&GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:102:7)
E/flutter (23001): #17     _WidgetsFlutterBinding&BindingBase&GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:86:7)
E/flutter (23001): #18     _rootRunUnary (dart:async/zone.dart:1136:13)
E/flutter (23001): #19     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
E/flutter (23001): #20     _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
E/flutter (23001): #21     _invoke1 (dart:ui/hooks.dart:250:10)
E/flutter (23001): #22     _dispatchPointerDataPacket (dart:ui/hooks.dart:159:5)
E/flutter (23001): 
```

**Comment by zzpmaster** [comment]
+1

**Comment by Mephistol** [comment]
have you solved this problem?

**Comment by chloe722** [comment]
I encountered the same issue

**Comment by TejaDroid** [comment]
This same issue also encounter in my app, [Here](https://github.com/flutter/flutter/issues/19103#issuecomment-412647536) got the solution, may this will help you too.

**Comment by david701** [comment]
I solved the problem by running "flutter clean"

**Comment by VickySalunkhe** [comment]
facing the same issue on beta and master channels

**Comment by loveangle66** [comment]
+1

**Comment by LIPKKKK** [comment]
+1

**Comment by wang709693972wei** [comment]
+1

**Comment by wang709693972wei** [comment]
请问下大家是怎么解决的

**Comment by firatcetiner** [comment]
Same issue here.`ImagePicker.pickImage()` returns object every single time, just annoying

**Comment by BondarenkoStas** [comment]
Can somebody please provide  a small self-contained app that demonstrates the problem? You can include small examples [inline if they're enclosed by backticks](https://help.github.com/en/articles/creating-and-highlighting-code-blocks), or just provide a public link to a github "gist" - https://gist.github.com/.

**Comment by iapicca** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
  
Thanks for your contribution.

**Comment by hahazheng** [comment]
我也遇到了同样的问题 ，有解决方案了么

**Comment by mahbubsabuj** [comment]
> I solved the problem by running "flutter clean"

thanks.it worked!

**Comment by PitiDev** [comment]
+1 same

**Comment by yuhaocan** [comment]
If you have use Flutter_Boost maybe this problem is

**Comment by ajouni** [comment]
> I solved the problem by running "flutter clean"

True story

**Comment by migalv** [comment]
Hello, I found this issue from a Crashlytics report in Firebase, so I don't know exactly how to reproduce this. And I would like to solve it. Can anyone help me out?

**Comment by iapicca** [comment]
Could everyone who still has this problem please file a new issue with the exact descriptions what happens, logs and the output of 'flutter doctor -v'  please.
All system setups can be slightly different so it's always better to open new issues and reference related issues.

**Comment by hpsaah** [comment]
I had the same error and I solved the problem by upgrading the image_picker package to ^0.6.2+1

**Comment by weshare12** [comment]
same problem

**Comment by DCrow** [comment]
Having the same problem on `image_picker: 0.6.4`

**Comment by moho12n** [comment]
having the same problem on  multi_image_picker: ^4.6.5+rc.1
