### ISSUE TITLE
Flutter module not working with Flutter Plugin, java.lang.NoClassDefFoundError: Failed resolution of: <>/plugins/sharedpreferences/SharedPreferencesPlugin

### ISSUE THREAD

**Issue by rodolfoizidoro** [flutter/flutter#36576]
The Flutter module was working perfectly in my application.
When I added the shared_preferences Plugin. It has stopped working and I can no longer compile the application.

How to work with plugins in Flutter Module?

## Steps to Reproduce

Follow add existings app tutorial.

Add in your flutter project shared_preferences.

## Logs

```
```

```
```

```
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: br.com.myapp, PID: 5780
    java.lang.RuntimeException: Unable to start activity ComponentInfo{br.com.myapp/br.com.myapp.flutter.OpenFlutterActivity}: java.lang.RuntimeException: Failed to call observer method
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2339)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2413)
        at android.app.ActivityThread.access$800(ActivityThread.java:155)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1317)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:135)
        at android.app.ActivityThread.main(ActivityThread.java:5343)
        at java.lang.reflect.Method.invoke(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:372)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:905)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:700)
     Caused by: java.lang.RuntimeException: Failed to call observer method
        at androidx.lifecycle.ClassesInfoCache$MethodReference.invokeCallback(ClassesInfoCache.java:225)
        at androidx.lifecycle.ClassesInfoCache$CallbackInfo.invokeMethodsForEvent(ClassesInfoCache.java:193)
        at androidx.lifecycle.ClassesInfoCache$CallbackInfo.invokeCallbacks(ClassesInfoCache.java:184)
        at androidx.lifecycle.ReflectiveGenericLifecycleObserver.onStateChanged(ReflectiveGenericLifecycleObserver.java:36)
        at androidx.lifecycle.LifecycleRegistry$ObserverWithState.dispatchEvent(LifecycleRegistry.java:355)
        at androidx.lifecycle.LifecycleRegistry.addObserver(LifecycleRegistry.java:181)
        at io.flutter.facade.Flutter.createView(Flutter.java:91)
        at io.flutter.facade.FlutterFragment.onCreateView(FlutterFragment.java:38)
        at io.flutter.facade.FlutterFragment.onCreateView(FlutterFragment.java:19)
        at androidx.fragment.app.Fragment.performCreateView(Fragment.java:2439)
        at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManager.java:1460)
        at androidx.fragment.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1784)
        at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManager.java:1852)
        at androidx.fragment.app.BackStackRecord.executeOps(BackStackRecord.java:802)
        at androidx.fragment.app.FragmentManagerImpl.executeOps(FragmentManager.java:2625)
        at androidx.fragment.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2411)
        at androidx.fragment.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManager.java:2366)
        at androidx.fragment.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2273)
        at androidx.fragment.app.FragmentManagerImpl.dispatchStateChange(FragmentManager.java:3273)
        at androidx.fragment.app.FragmentManagerImpl.dispatchActivityCreated(FragmentManager.java:3229)
        at androidx.fragment.app.FragmentController.dispatchActivityCreated(FragmentController.java:201)
        at androidx.fragment.app.FragmentActivity.onStart(FragmentActivity.java:620)
        at androidx.appcompat.app.AppCompatActivity.onStart(AppCompatActivity.java:178)
        at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1259)
        at android.app.Activity.performStart(Activity.java:6026)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2302)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2413) 
        at android.app.ActivityThread.access$800(ActivityThread.java:155) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1317) 
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:135) 
        at android.app.ActivityThread.main(ActivityThread.java:5343) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at java.lang.reflect.Method.invoke(Method.java:372) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:905) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:700) 
     Caused by: java.lang.NoClassDefFoundError: Failed resolution of: Lio/flutter/plugins/sharedpreferences/SharedPreferencesPlugin;
        at io.flutter.plugins.GeneratedPluginRegistrant.registerWith(GeneratedPluginRegistrant.java:14)
        at io.flutter.facade.Flutter$2.onCreate(Flutter.java:98)
        at java.lang.reflect.Method.invoke(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:372)
        at androidx.lifecycle.ClassesInfoCache$MethodReference.invokeCallback(ClassesInfoCache.java:215)
        at androidx.lifecycle.ClassesInfoCache$CallbackInfo.invokeMethodsForEvent(ClassesInfoCache.java:193) 
        at androidx.lifecycle.ClassesInfoCache$CallbackInfo.invokeCallbacks(ClassesInfoCache.java:184) 
        at androidx.lifecycle.ReflectiveGenericLifecycleObserver.onStateChanged(ReflectiveGenericLifecycleObserver.java:36) 
        at androidx.lifecycle.LifecycleRegistry$ObserverWithState.dispatchEvent(LifecycleRegistry.java:355) 
        at androidx.lifecycle.LifecycleRegistry.addObserver(LifecycleRegistry.java:181) 
        at io.flutter.facade.Flutter.createView(Flutter.java:91) 
        at io.flutter.facade.FlutterFragment.onCreateView(FlutterFragment.java:38) 
        at io.flutter.facade.FlutterFragment.onCreateView(FlutterFragment.java:19) 
        at androidx.fragment.app.Fragment.performCreateView(Fragment.java:2439) 
        at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManager.java:1460) 
        at androidx.fragment.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1784) 
        at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManager.java:1852) 
        at androidx.fragment.app.BackStackRecord.executeOps(BackStackRecord.java:802) 
        at androidx.fragment.app.FragmentManagerImpl.executeOps(FragmentManager.java:2625) 
        at androidx.fragment.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2411) 
        at androidx.fragment.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManager.java:2366) 
        at androidx.fragment.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2273) 
        at androidx.fragment.app.FragmentManagerImpl.dispatchStateChange(FragmentManager.java:3273) 
        at androidx.fragment.app.FragmentManagerImpl.dispatchActivityCreated(FragmentManager.java:3229) 
        at androidx.fragment.app.FragmentController.dispatchActivityCreated(FragmentController.java:201) 
        at androidx.fragment.app.FragmentActivity.onStart(FragmentActivity.java:620) 
        at androidx.appcompat.app.AppCompatActivity.onStart(AppCompatActivity.java:178) 
        at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1259) 
        at android.app.Activity.performStart(Activity.java:6026) 
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2302) 
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2413) 
        at android.app.ActivityThread.access$800(ActivityThread.java:155) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1317) 
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:135) 
        at android.app.ActivityThread.main(ActivityThread.java:5343) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at java.lang.reflect.Method.invoke(Method.java:372) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:905) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:700) 
     Caused by: java.lang.ClassNotFoundException: Didn't find class "io.flutter.plugins.sharedpreferences.SharedPreferencesPlugin" on path: DexPathList[[zip file "/data/app/br.com.myapp2/base.apk", zip file "

```

**Comment by marianoarga** [comment]
Same issue here

**Comment by marianoarga** [comment]
@rodolfoizidoro Adding producFlavors (like I already did on other projects), fixed the issue

```
    flavorDimensions 'abi'
    productFlavors {
        arm32 {
            dimension 'abi'
            ndk {
                abiFilters 'armeabi-v7a'
                versionCode 1080032
                versionName "1.08.00.32"
            }
        }
        arm64 {
            dimension 'abi'
            ndk {
                abiFilters 'arm64-v8a'
                versionCode 1080064
                versionName "1.08.00.64"
            }
        }
        x86 {
            dimension 'abi'
            ndk {
                abiFilters 'x86'
                versionCode 1080086
                versionName "1.08.00.86"
            }
        }
    }
```

**Comment by rodolfoizidoro** [comment]
Hello @marianoarga  Do you have same example your gradle file?

**Comment by marianoarga** [comment]
Sure @rodolfoizidoro 
Note that you may not need to implement firebase nor apply gms plugin
Another note, you will have to run your project with productFlavor:
`flutter run --flavor x86`
(x86 for my emulator, it may be ARM for your physical device)

```
def localProperties = new Properties()
def localPropertiesFile = rootProject.file('local.properties')
if (localPropertiesFile.exists()) {
    localPropertiesFile.withReader('UTF-8') { reader ->
        localProperties.load(reader)
    }
}

def flutterRoot = localProperties.getProperty('flutter.sdk')
if (flutterRoot == null) {
    throw new GradleException("Flutter SDK not found. Define location with flutter.sdk in the local.properties file.")
}

apply plugin: 'com.android.application'
apply from: "$flutterRoot/packages/flutter_tools/gradle/flutter.gradle"

def keystorePropertiesFile = rootProject.file("key.properties")
def keystoreProperties = new Properties()
keystoreProperties.load(new FileInputStream(keystorePropertiesFile))

android {
    compileSdkVersion 28

    lintOptions {
        disable 'InvalidPackage'
    }

    defaultConfig {
        // TODO: Specify your own unique Application ID (https://developer.android.com/studio/build/application-id.html).
        applicationId "com.compay.app_name"
        minSdkVersion 16
        targetSdkVersion 28
        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
        resConfigs "en", "es"
        multiDexEnabled true
    }

    flavorDimensions 'abi'
    productFlavors {
        arm32 {
            dimension 'abi'
            ndk {
                abiFilters 'armeabi-v7a'
                versionCode 1010032
                versionName "1.01.00.32"
            }
        }
        arm64 {
            dimension 'abi'
            ndk {
                abiFilters 'arm64-v8a'
                versionCode 1010064
                versionName "1.01.00.64"
            }
        }
        x86 {
            dimension 'abi'
            ndk {
                abiFilters 'x86'
                versionCode 1010086
                versionName "1.01.00.86"
            }
        }
    }

    buildTypes {
        debug{
            signingConfig signingConfigs.debug
        }
    }
}

flutter {
    source '../..'
}

dependencies {
    testImplementation 'junit:junit:4.12'
    androidTestImplementation 'androidx.test:runner:1.1.1'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.1.1'
    implementation 'com.google.firebase:firebase-core:17.0.0'
}

apply plugin: 'com.google.gms.google-services'
```

**Comment by rodolfoizidoro** [comment]
@marianoarga Thanks so much, i going try this

**Comment by jmagman** [comment]
Are you still seeing this issue?

**Comment by rodolfoizidoro** [comment]
Hi @jmagman When generate aar in Flutter Module not generated dependencies her and cause this crash.

A solution in Android is use Fat AAR with a new module encapsulating flutter.  

But in IOS I don`t know. 

In resume flutter module not working fine when module contains dependencies that generated native code how plugin `shared_preferences`

**Comment by LNeway** [comment]
I have the same issue.

**Comment by blasten** [comment]
Is this still an issue? I seem to be able to compile AARs (with `flutter build aar` if I use `shared_preferences`.

**Comment by jmagman** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!

Thanks for your contribution.
