### ISSUE TITLE
cloud_functions plugin - "Functions component does not exist" error

### ISSUE THREAD

**Issue by kostaa** [flutter/flutter#36605]
Getting a NullPointerException from the plugin. I also have a cloud firestore plugin which is working correctly. 

```
E/MethodChannel#cloud_functions(32656): Failed to handle method call
E/MethodChannel#cloud_functions(32656): java.lang.NullPointerException: Functions component does not exist.
E/MethodChannel#cloud_functions(32656): 	at com.google.android.gms.common.internal.Preconditions.checkNotNull(Unknown Source:11)
E/MethodChannel#cloud_functions(32656): 	at com.google.firebase.functions.FirebaseFunctions.getInstance(com.google.firebase:firebase-functions@@17.0.0:135)
E/MethodChannel#cloud_functions(32656): 	at io.flutter.plugins.firebase.cloudfunctions.cloudfunctions.CloudFunctionsPlugin.onMethodCall(CloudFunctionsPlugin.java:43)
E/MethodChannel#cloud_functions(32656): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:222)
E/MethodChannel#cloud_functions(32656): 	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:96)
E/MethodChannel#cloud_functions(32656): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:643)
E/MethodChannel#cloud_functions(32656): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/MethodChannel#cloud_functions(32656): 	at android.os.MessageQueue.next(MessageQueue.java:376)
E/MethodChannel#cloud_functions(32656): 	at android.os.Looper.loop(Looper.java:244)
E/MethodChannel#cloud_functions(32656): 	at android.app.ActivityThread.main(ActivityThread.java:6748)
E/MethodChannel#cloud_functions(32656): 	at java.lang.reflect.Method.invoke(Native Method)
E/MethodChannel#cloud_functions(32656): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
E/MethodChannel#cloud_functions(32656): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
```
**pubspec.yaml**

dependencies:
  cloud_firestore: 0.12.7
  cloud_functions: 0.4.0+2
  firebase_core: 0.4.0+6
```
```
**build.gradle**

    dependencies {
        classpath 'com.android.tools.build:gradle:3.3.0'
        classpath 'com.google.gms:google-services:3.2.1'
    }

```
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, v1.7.8+hotfix.3, on Microsoft Windows [Version 10.0.17134.885], locale en-GB)

[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[!] Android Studio (version 3.4)
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
[√] IntelliJ IDEA Community Edition (version 2019.1)
[√] Connected device (1 available)

! Doctor found issues in 1 category.
```

**Comment by kostaa** [comment]
I have managed to resolve this issue by following this [StackOverflow issue](https://stackoverflow.com/questions/54382246/flutter-firestore-component-is-not-present) by adding the **'exclude group: 'com.google.guava', module: 'guava-jdk5'** to the gradle dependencies:

```
 dependencies {
        classpath 'com.android.tools.build:gradle:3.3.0'
        classpath ('com.google.gms:google-services:3.2.1') {
            exclude group: 'com.google.guava', module: 'guava-jdk5'
        }
    }
``` 
I am going to keep this issue open as this should be documented somewhere.

**Comment by kroikie** [comment]
@kostaa

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/1191. Any further collaboration will be done there.
