### ISSUE TITLE
layout_bench.dart is broken

### ISSUE THREAD

**Issue by mraleph** [flutter/flutter#3663]
## Steps to Reproduce

```
$ out/Release/sky_shell --non-interactive --packages=$FLUTTER_DIR/packages/flutter/.packages $FLUTTER_DIR/packages/flutter/benchmark/stocks/layout_bench.dart
[0502/162929:ERROR:dart_error.cc(17)] Unhandled exception:
The null object does not have a method 'run'.

NoSuchMethodError: method not found: 'run'
Receiver: null
Arguments: [Closure: (FakeAsync) => dynamic]
#0      Object._noSuchMethod (dart:core-patch/object_patch.dart:42)
#1      Object.noSuchMethod (dart:core-patch/object_patch.dart:45)
#2      TestWidgetsFlutterBinding.runTest (package:flutter_test/src/binding.dart:192:15)
#3      benchmarkWidgets (package:flutter_test/src/widget_tester.dart:85:18)
#4      main (/usr/local/google/home/vegorov/src/flutter/flutter/packages/flutter/benchmark/stocks/layout_bench.dart:15:3)
#5      _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:261)
#6      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:148)
```

This is because `runTest` needs `fakeAsync` which is created in the `preTest` which `benchmarkWidgets` does not call.

/cc @Hixie

**Comment by Hixie** [comment]
my bad

**Comment by eseidelGoogle** [comment]
Is this fixed now @Hixie?

**Comment by Hixie** [comment]
Yep.
