### ISSUE TITLE
74220a75630f6c4b

### ISSUE THREAD

**Issue by Ahmedesayed** [flutter/flutter#36649]
Flutter crash report; please file at https://github.com/flutter/flutter/issues.

## command

flutter packages get

## exception

YamlException: Error on line 21, column 1: Expected a space but found a tab.
   ╷
21 │     onesignal:
   │ ^^^^
   ╵

```
#0      Parser.parse (package:yaml/src/parser.dart:50:7)
#1      Loader._loadMapping (package:yaml/src/loader.dart:163:37)
#2      Loader._loadNode (package:yaml/src/loader.dart:86:16)
#3      Loader._loadMapping (package:yaml/src/loader.dart:163:19)
#4      Loader._loadNode (package:yaml/src/loader.dart:86:16)
#5      Loader._loadDocument (package:yaml/src/loader.dart:62:20)
#6      Loader.load (package:yaml/src/loader.dart:54:20)
#7      loadYamlDocument (package:yaml/yaml.dart:51:25)
#8      loadYamlNode (package:yaml/yaml.dart:42:5)
#9      loadYaml (package:yaml/yaml.dart:34:5)
#10     FlutterManifest.createFromString (package:flutter_tools/src/flutter_manifest.dart:38:28)
#11     FlutterManifest.createFromPath (package:flutter_tools/src/flutter_manifest.dart:32:12)
#12     FlutterProject._readManifest (package:flutter_tools/src/project.dart:167:54)
#13     FlutterProject.fromDirectory (package:flutter_tools/src/project.dart:45:38)
#14     FlutterProject.fromPath (package:flutter_tools/src/project.dart:60:50)
#15     PackagesGetCommand.usageValues (package:flutter_tools/src/commands/packages.dart:80:55)
<asynchronous suspension>
#16     FlutterCommand._sendUsage (package:flutter_tools/src/runner/flutter_command.dart:411:58)
<asynchronous suspension>
#17     FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:392:17)
<asynchronous suspension>
#18     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:29)
<asynchronous suspension>
#19     _rootRun (dart:async/zone.dart:1124:13)
#20     _CustomZone.run (dart:async/zone.dart:1021:19)
#21     _runZoned (dart:async/zone.dart:1516:10)
#22     runZoned (dart:async/zone.dart:1463:12)
#23     AppContext.run (package:flutter_tools/src/base/context.dart:152:18)
<asynchronous suspension>
#24     FlutterCommand.run (package:flutter_tools/src/runner/flutter_command.dart:375:20)
#25     CommandRunner.runCommand (package:args/command_runner.dart:197:27)
<asynchronous suspension>
#26     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:396:21)
<asynchronous suspension>
#27     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:29)
<asynchronous suspension>
#28     _rootRun (dart:async/zone.dart:1124:13)
#29     _CustomZone.run (dart:async/zone.dart:1021:19)
#30     _runZoned (dart:async/zone.dart:1516:10)
#31     runZoned (dart:async/zone.dart:1463:12)
#32     AppContext.run (package:flutter_tools/src/base/context.dart:152:18)
<asynchronous suspension>
#33     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:356:19)
<asynchronous suspension>
#34     CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:112:25)
#35     new Future.sync (dart:async/future.dart:224:31)
#36     CommandRunner.run (package:args/command_runner.dart:112:14)
#37     FlutterCommandRunner.run (package:flutter_tools/src/runner/flutter_command_runner.dart:242:18)
#38     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:62:22)
<asynchronous suspension>
#39     _rootRun (dart:async/zone.dart:1124:13)
#40     _CustomZone.run (dart:async/zone.dart:1021:19)
#41     _runZoned (dart:async/zone.dart:1516:10)
#42     runZoned (dart:async/zone.dart:1500:12)
#43     run.<anonymous closure> (package:flutter_tools/runner.dart:60:18)
<asynchronous suspension>
#44     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:29)
<asynchronous suspension>
#45     _rootRun (dart:async/zone.dart:1124:13)
#46     _CustomZone.run (dart:async/zone.dart:1021:19)
#47     _runZoned (dart:async/zone.dart:1516:10)
#48     runZoned (dart:async/zone.dart:1463:12)
#49     AppContext.run (package:flutter_tools/src/base/context.dart:152:18)
<asynchronous suspension>
#50     runInContext (package:flutter_tools/src/context_runner.dart:56:24)
<asynchronous suspension>
#51     run (package:flutter_tools/runner.dart:51:10)
#52     main (package:flutter_tools/executable.dart:62:9)
<asynchronous suspension>
#53     main (file:///Users/ahmedelsayed/Downloads/flutter/packages/flutter_tools/bin/flutter_tools.dart:8:3)
#54     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:299:32)
#55     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:12)
```

## flutter doctor

```
[✓] Flutter (Channel stable, v1.7.8+hotfix.3, on Mac OS X 10.14.5 18F132, locale en-EG)
    • Flutter version 1.7.8+hotfix.3 at /Users/ahmedelsayed/Downloads/flutter
    • Framework revision b712a172f9 (12 days ago), 2019-07-09 13:14:38 -0700
    • Engine revision 54ad777fd2
    • Dart version 2.4.0

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/ahmedelsayed/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 10.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.1, Build version 10B61
    • CocoaPods version 1.6.0

[!] iOS tools - develop for iOS devices
    ✗ Verify that all connected devices have been paired with this computer in Xcode.
      If all devices have been paired, libimobiledevice and ideviceinstaller may require updating.
      To update with Brew, run:
        brew update
        brew uninstall --ignore-dependencies libimobiledevice
        brew uninstall --ignore-dependencies usbmuxd
        brew install --HEAD usbmuxd
        brew unlink usbmuxd
        brew link usbmuxd
        brew install --HEAD libimobiledevice
        brew install ideviceinstaller
    • ios-deploy 1.9.2
    ✗ ios-deploy out of date (1.9.4 is required). To upgrade with Brew:
        brew upgrade ios-deploy

[✓] Android Studio (version 3.4)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 37.1.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

[✓] VS Code (version 1.36.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.2.0

[!] Connected device
    ! No devices available

! Doctor found issues in 2 categories.
```

**Comment by DanTup** [comment]
> Expected a space but found a tab.

It seems like you may have mixed indenting in your pubspec.yaml (some tabs, where there should only be spaces), possibly on the line that adds the `onesignal` dependency. Please try changing all your indenting to consistent spaces to see if that solves the issue.
