### ISSUE TITLE
when i send a image from cameraStream to native(java),the app will Lost connection to device

### ISSUE THREAD

**Issue by bladeofgod** [flutter/flutter#36658]
## Steps to Reproduce

I develop with dart&java, when i send a image Data from camera stream, to native(java),the app will stop, actually it's dark screen and pause there. And the log show "Lost connection to device". it's happend at  camera ResolutionPreset is medium and high . low it's working but cant use because image it's too small and low quailty.
at last thanks for help.  :)

## Logs
```
  E/flutter ( 6983): [ERROR:flutter/lib/ui/ui_dart_state.cc(148)] Unhandled Exception: CameraException(No camera is streaming images, stopImageStream was called when no camera is streaming images.)
E/flutter ( 6983): #0      CameraController.stopImageStream (package:camera/camera.dart:397:7)
E/flutter ( 6983): <asynchronous suspension>
E/flutter ( 6983): #1      _MyHomePageState.onCameraSelected.<anonymous closure>.<anonymous closure> (package:flutter_decode_qr_demo_1/main.dart:127:24)
E/flutter ( 6983): #2      _rootRun (dart:async/zone.dart:1120:38)
E/flutter ( 6983): #3      _CustomZone.run (dart:async/zone.dart:1021:19)
E/flutter ( 6983): #4      _FutureListener.handleWhenComplete (dart:async/future_impl.dart:150:18)
E/flutter ( 6983): #5      Future._propagateToListeners.handleWhenCompleteCallback (dart:async/future_impl.dart:609:39)
E/flutter ( 6983): #6      Future._propagateToListeners (dart:async/future_impl.dart:665:37)
E/flutter ( 6983): #7      Future._complete (dart:async/future_impl.dart:473:7)
E/flutter ( 6983): #8      new Future.delayed.<anonymous closure> (dart:async/future.dart:313:16)
E/flutter ( 6983): #9      _rootRun (dart:async/zone.dart:1120:38)
E/flutter ( 6983): #10     _CustomZone.run (dart:async/zone.dart:1021:19)
E/flutter ( 6983): #11     _CustomZone.runGuarded (dart:async/zone.dart:923:7)
E/flutter ( 6983): #12     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:963:23)
E/flutter ( 6983): #13     _rootRun (dart:async/zone.dart:1124:13)
E/flutter ( 6983): #14     _CustomZone.run (dart:async/zone.dart:1021:19)
E/flutter ( 6983): #15     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:947:23)
E/flutter ( 6983): #16     Timer._createTimer.<anonymous closure> (dart:async/runtime/libtimer_patch.dart:21:15)
E/flutter ( 6983): #17     _Timer._runTimers (dart:isolate/runtime/libtimer_impl.dart:382:19)
E/flutter ( 6983): #18     _Timer._handleMessage (dart:isolate/runtime/libtimer_impl.dart:416:5)
E/flutter ( 6983): #19     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:171:12)
E/flutter ( 6983): 
Lost connection to device.
```

**Comment by bladeofgod** [comment]
It's there any size limit of methodChannel for send data? :)

**Comment by BondarenkoStas** [comment]
@bladeofgod Could you please check it with current stable channel and current camera version?

**Comment by iapicca** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!

Could everyone who still has this problem please file a new issue with the exact descriptions what happens, logs and the output of ' flutter doctor -v'  please.
All system setups can be slightly different so its always better to open new issues and reference related issues.
