### ISSUE TITLE
Adding Implementation of any Firebase Service Causes App To Crash Immediately

### ISSUE THREAD

**Issue by kalittles** [flutter/flutter#36687]
## Steps to Reproduce

1. Start application on Android Q Pixel 3 or Emulator targeting APIs 28.
2. Follow tutorial on Firebase website for an Android application to get Firebase SDK installed on Flutter application. 
3. Add classpath 'com.google.gms:google-services:4.2.0' to the project level build.gradle
4. Add  implementation 'com.google.firebase:firebase-messaging:19.0.1' to the app level gradle file
5. apply plugin: 'com.google.gms.google-services' to the bottom of the app level gradle file
6. I hit "Login" (my app uses flutter_bloc.dart from this tutorial) 

https://medium.com/flutter-community/flutter-login-tutorial-with-flutter-bloc-ea606ef701ad

7. Launch application
NOTE: COMMENTING OUT THE IMPLEMENTATION LINE CAUSES IT TO RUN LIKE USUAL (but obviously removes the firebase connection). AFTER REMOVING THE LINE, THE FIREBASE SITE SAYS "THE APP IS CONNECTED" EVEN THOUGH I'VE COMMENTED OUT THE LINE. I'VE ALSO TRIED USING OTHER SERVICES (MESSAGING SPECIFICALLY, SAME RESULT).

```

E/flutter (27829): [ERROR:flutter/shell/platform/android/platform_view_android_jni.cc(40)] java.lang.NoClassDefFoundError: Failed resolution of: Landroid/support/v4/app/ActivityCompat;
E/flutter (27829): 	at com.lyokone.location.LocationPlugin.checkPermissions(LocationPlugin.java:193)
E/flutter (27829): 	at com.lyokone.location.LocationPlugin.onListen(LocationPlugin.java:278)
E/flutter (27829): 	at io.flutter.plugin.common.EventChannel$IncomingStreamRequestHandler.onListen(EventChannel.java:193)
E/flutter (27829): 	at io.flutter.plugin.common.EventChannel$IncomingStreamRequestHandler.onMessage(EventChannel.java:172)
E/flutter (27829): 	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:96)
E/flutter (27829): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:643)
E/flutter (27829): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/flutter (27829): 	at android.os.MessageQueue.next(MessageQueue.java:326)
E/flutter (27829): 	at android.os.Looper.loop(Looper.java:160)
E/flutter (27829): 	at android.app.ActivityThread.main(ActivityThread.java:6718)
E/flutter (27829): 	at java.lang.reflect.Method.invoke(Native Method)
E/flutter (27829): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
E/flutter (27829): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
E/flutter (27829): Caused by: java.lang.ClassNotFoundException: Didn't find class "android.support.v4.app.ActivityCompat" on path: DexPathList[[zip file "/data/app/com.market.marketapp-FLOHvmxMmjP59BQUYfveIQ==/base.apk"],nativeLibraryDirectories=[/data/app/com.market.marketapp-FLOHvmxMmjP59BQUYfveIQ==/lib/arm64, /data/app/com.market.marketapp-FLOHvmxMmjP59BQUYfveIQ==/base.apk!/lib/arm64-v8a, /system/lib64]]
E/flutter (27829): 	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:134)
E/flutter (27829): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
E/flutter (27829): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
E/flutter (27829): 	... 13 more
E/flutter (27829): 
F/flutter (27829): [FATAL:flutter/shell/platform/android/platform_view_android_jni.cc(77)] Check failed: CheckException(env). 
F/libc    (27829): Fatal signal 6 (SIGABRT), code -6 (SI_TKILL) in tid 27829 (arket.marketapp), pid 27829 (arket.marketapp)
*** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
Build fingerprint: 'google/blueline/blueline:9/PQ3A.190705.003/5600800:user/release-keys'
Revision: 'MP1.0'
ABI: 'arm64'
pid: 27829, tid: 27829, name: arket.marketapp  >>> com.market.marketapp <<<
signal 6 (SIGABRT), code -6 (SI_TKILL), fault addr --------
Abort message: '[FATAL:flutter/shell/platform/android/platform_view_android_jni.cc(77)] Check failed: CheckException(env). 
'
    x0  0000000000000000  x1  0000000000006cb5  x2  0000000000000006  x3  0000000000000008
    x4  0000000000000000  x5  0000000000000000  x6  0000000000000000  x7  0000000000800000
    x8  0000000000000083  x9  0000007f6d9f80a0  x10 fffffff87ffffbdf  x11 0000000000000001
    x12 0101010101010101  x13 0000000000000028  x14 ffffffffffffffff  x15 0000000000000018
    x16 0000007f6da322c8  x17 0000007f6d96fdcc  x18 0000007fcb2b0d8a  x19 0000000000006cb5
    x20 0000000000006cb5  x21 0000007fcb2b16b8  x22 0000007ece2b3840  x23 0000007ece2b3718
    x24 0000007ece2b3700  x25 0000000000000003  x26 0000000000000000  x27 0000000000000001
    x28 0000000000000027  x29 0000007fcb2b16a0
    sp  0000007fcb2b1660  lr  0000007f6d96494c  pc  0000007f6d964974
backtrace:
    #00 pc 0000000000021974  /system/lib64/libc.so (abort+116)
    #01 pc 0000000000d34a40  /data/app/com.market.marketapp-FLOHvmxMmjP59BQUYfveIQ==/lib/arm64/libflutter.so (offset 0xd20000)
    #02 pc 0000000000d2778c  /data/app/com.market.marketapp-FLOHvmxMmjP59BQUYfveIQ==/lib/arm64/libflutter.so (offset 0xd20000)
    #03 pc 0000000000d25cb0  /data/app/com.market.marketapp-FLOHvmxMmjP59BQUYfveIQ==/lib/arm64/libflutter.so (offset 0xd20000)
    #04 pc 0000000000d6c078  /data/app/com.market.marketapp-FLOHvmxMmjP59BQUYfveIQ==/lib/arm64/libflutter.so (offset 0xd20000)
    #05 pc 0000000000d354ec  /data/app/com.market.marketapp-FLOHvmxMmjP59BQUYfveIQ==/lib/arm64/libflutter.so (offset 0xd20000)
    #06 pc 0000000000d3a1f4  /data/app/com.market.marketapp-FLOHvmxMmjP59BQUYfveIQ==/lib/arm64/libflutter.so (offset 0xd20000)
    #07 pc 0000000000014128  /system/lib64/libutils.so (android::Looper::pollInner(int)+824)
    #08 pc 0000000000013d4c  /system/lib64/libutils.so (android::Looper::pollOnce(int, int*, int*, void**)+60)
    #09 pc 000000000011fa40  /system/lib64/libandroid_runtime.so (android::android_os_MessageQueue_nativePollOnce(_JNIEnv*, _jobject*, long, int)+44)
    #10 pc 00000000003e1fec  /system/framework/arm64/boot-framework.oat (offset 0x3cd000) (android.media.MediaExtractor.seekTo [DEDUPED]+140)
    #11 pc 0000000000545b88  /system/lib64/libart.so (art_quick_invoke_stub+584)
    #12 pc 00000000000cf698  /system/lib64/libart.so (art::ArtMethod::Invoke(art::Thread*, unsigned int*, unsigned int, art::JValue*, char const*)+200)
    #13 pc 000000000027a978  /system/lib64/libart.so (art::interpreter::ArtInterpreterToCompiledCodeBridge(art::Thread*, art::ArtMethod*, art::ShadowFrame*, unsigned short, art::JValue*)+344)
    #14 pc 00000000002749b8  /system/lib64/libart.so (bool art::interpreter::DoCall<false, false>(art::ArtMethod*, art::Thread*, art::ShadowFrame&, art::Instruction const*, unsigned short, art::JValue*)+948)
    #15 pc 0000000000516b64  /system/lib64/libart.so (MterpInvokeDirect+296)
    #16 pc 0000000000538294  /system/lib64/libart.so (ExecuteMterpImpl+14484)
    #17 pc 0000000000aecf50  /system/framework/boot-framework.vdex (android.os.MessageQueue.next+38)
    #18 pc 000000000024e938  /system/lib64/libart.so (_ZN3art11interpreterL7ExecuteEPNS_6ThreadERKNS_20CodeItemDataAccessorERNS_11ShadowFrameENS_6JValueEb.llvm.953976685+488)
    #19 pc 0000000000254098  /system/lib64/libart.so (art::interpreter::ArtInterpreterToInterpreterBridge(art::Thread*, art::CodeItemDataAccessor const&, art::ShadowFrame*, art::JValue*)+216)
    #20 pc 000000000027499c  /system/lib64/libart.so (bool art::interpreter::DoCall<false, false>(art::ArtMethod*, art::Thread*, art::ShadowFrame&, art::Instruction const*, unsigned short, art::JValue*)+920)
    #21 pc 0000000000515830  /system/lib64/libart.so (MterpInvokeVirtual+588)
    #22 pc 0000000000538194  /system/lib64/libart.so (ExecuteMterpImpl+14228)
    #23 pc 0000000000aec9fc  /system/framework/boot-framework.vdex (android.os.Looper.loop+128)
    #24 pc 000000000024e938  /system/lib64/libart.so (_ZN3art11interpreterL7ExecuteEPNS_6ThreadERKNS_20CodeItemDataAccessorERNS_11ShadowFrameENS_6JValueEb.llvm.953976685+488)
    #25 pc 0000000000254098  /system/lib64/libart.so (art::interpreter::ArtInterpreterToInterpreterBridge(art::Thread*, art::CodeItemDataAccessor const&, art::ShadowFrame*, art::JValue*)+216)
    #26 pc 000000000027499c  /system/lib64/libart.so (bool art::interpreter::DoCall<false, false>(art::ArtMethod*, art::Thread*, art::ShadowFrame&, art::Instruction const*, unsigned short, art::JValue*)+920)
    #27 pc 0000000000516d28  /system/lib64/libart.so (MterpInvokeStatic+204)
    #28 pc 0000000000538314  /system/lib64/libart.so (ExecuteMterpImpl+14612)
    #29 pc 0000000000385b8a  /system/framework/boot-framework.vdex (android.app.ActivityThread.main+214)
    #30 pc 000000000024e938  /system/lib64/libart.so (_ZN3art11interpreterL7ExecuteEPNS_6ThreadERKNS_20CodeItemDataAccessorERNS_11ShadowFrameENS_6JValueEb.llvm.953976685+488)
    #31 pc 00000000005064ec  /system/lib64/libart.so (artQuickToInterpreterBridge+1032)
    #32 pc 000000000054ecfc  /system/lib64/libart.so (art_quick_to_interpreter_bridge+92)
    #33 pc 0000000000545e4c  /system/lib64/libart.so (art_quick_invoke_static_stub+604)
    #34 pc 00000000000cf6b8  /system/lib64/libart.so (art::ArtMethod::Invoke(art::Thread*, unsigned int*, unsigned int, art::JValue*, char const*)+232)
    #35 pc 000000000044f524  /system/lib64/libart.so (art::(anonymous namespace)::InvokeWithArgArray(art::ScopedObjectAccessAlreadyRunnable const&, art::ArtMethod*, art::(anonymous namespace)::ArgArray*, art::JValue*, char const*)+104)
    #36 pc 0000000000450f88  /system/lib64/libart.so (art::InvokeMethod(art::ScopedObjectAccessAlreadyRunnable const&, _jobject*, _jobject*, _jobject*, unsigned long)+1440)
    #37 pc 00000000003e255c  /system/lib64/libart.so (art::Method_invoke(_JNIEnv*, _jobject*, _jobject*, _jobjectArray*)+52)
    #38 pc 000000000011e6d4  /system/framework/arm64/boot.oat (offset 0x114000) (java.lang.Class.getDeclaredMethodInternal [DEDUPED]+180)
    #39 pc 0000000000545b88  /system/lib64/libart.so (art_quick_invoke_stub+584)
    #40 pc 00000000000cf698  /system/lib64/libart.so (art::ArtMethod::Invoke(art::Thread*, unsigned int*, unsigned int, art::JValue*, char const*)+200)
    #41 pc 000000000027a978  /system/lib64/libart.so (art::interpreter::ArtInterpreterToCompiledCodeBridge(art::Thread*, art::ArtMethod*, art::ShadowFrame*, unsigned short, art::JValue*)+344)
    #42 pc 00000000002749b8  /system/lib64/libart.so (bool art::interpreter::DoCall<false, false>(art::ArtMethod*, art::Thread*, art::ShadowFrame&, art::Instruction const*, unsigned short, art::JValue*)+948)
    #43 pc 0000000000515830  /system/lib64/libart.so (MterpInvokeVirtual+588)
    #44 pc 0000000000538194  /system/lib64/libart.so (ExecuteMterpImpl+14228)
    #45 pc 0000000000c0db26  /system/framework/boot-framework.vdex (com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run+22)
    #46 pc 000000000024e938  /system/lib64/libart.so (_ZN3art11interpreterL7ExecuteEPNS_6ThreadERKNS_20CodeItemDataAccessorERNS_11ShadowFrameENS_6JValueEb.llvm.953976685+488)
    #47 pc 00000000005064ec  /system/lib64/libart.so (artQuickToInterpreterBridge+1032)
    #48 pc 000000000054ecfc  /system/lib64/libart.so (art_quick_to_interpreter_bridge+92)
    #49 pc 0000000000beb4a0  /system/framework/arm64/boot-framework.oat (offset 0x3cd000) (com.android.internal.os.ZygoteInit.main+3088)
    #50 pc 0000000000545e4c  /system/lib64/libart.so (art_quick_invoke_static_stub+604)
    #51 pc 00000000000cf6b8  /system/lib64/libart.so (art::ArtMethod::Invoke(art::Thread*, unsigned int*, unsigned int, art::JValue*, char const*)+232)
    #52 pc 000000000044f524  /system/lib64/libart.so (art::(anonymous namespace)::InvokeWithArgArray(art::ScopedObjectAccessAlreadyRunnable const&, art::ArtMethod*, art::(anonymous namespace)::ArgArray*, art::JValue*, char const*)+104)
    #53 pc 000000000044f17c  /system/lib64/libart.so (art::InvokeWithVarArgs(art::ScopedObjectAccessAlreadyRunnable const&, _jobject*, _jmethodID*, std::__va_list)+424)
    #54 pc 00000000003594dc  /system/lib64/libart.so (art::JNI::CallStaticVoidMethodV(_JNIEnv*, _jclass*, _jmethodID*, std::__va_list)+768)
    #55 pc 00000000000b1ef4  /system/lib64/libandroid_runtime.so (_JNIEnv::CallStaticVoidMethod(_jclass*, _jmethodID*, ...)+120)
    #56 pc 00000000000b487c  /system/lib64/libandroid_runtime.so (android::AndroidRuntime::start(char const*, android::Vector<android::String8> const&, bool)+756)
    #57 pc 000000000000219c  /system/bin/app_process64 (main+1200)
    #58 pc 00000000000ace6c  /system/lib64/libc.so (__libc_init+88)
Lost connection to device.
Could not update files on device: HttpException: Connection closed before full header was received, uri = http://127.0.0.1:50666/v94XncjUWPc=/
```
**FLUTTER ANALYSIS**
```

Analyzing marketapp...

   info - Unused import: 'package:marketapp/Repository/UserRepository.dart' - lib\Areas\Meet\MeetPage.dart:4:8 - unused_import
   info - The class '_MeetPageResponseState' isn't used - lib\Areas\Meet\MeetState.dart:8:7 - unused_element
   info - Unused import: 'SplashPage.dart' - lib\Main.dart:12:8 - unused_import

3 issues found. (ran in 7.4s)

```

```
```

[√] Flutter (Channel stable, v1.7.8+hotfix.3, on Microsoft Windows [Version 10.0.18362.239], locale en-US)
    • Flutter version 1.7.8+hotfix.3 at C:\src\flutter
    • Framework revision b712a172f9 (13 days ago), 2019-07-09 13:14:38 -0700
    • Engine revision 54ad777fd2
    • Dart version 2.4.0

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.0)
    • Android SDK at C:\Users\nvn\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.0
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
    • All Android licenses accepted.

[√] Android Studio (version 3.4)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 37.1.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

[√] Connected device (1 available)
    • Pixel 3 • 88LX01L9L • android-arm64 • Android 9 (API 28)

```
```

This is incredibly frustrating - any advice on how to debug these issues more effectively would also be much appreciated. At this point, I wish I had just built the application using native Android / iOS.

**Comment by kalittles** [comment]
I'll try to reproduce with a smaller app, but I'm unsure because it looks like it has something to do with asking for permissions.

**Comment by kalittles** [comment]
I tracked down the issue. I was using dependency
location: ^1.4.1

Updated my location to 2.3.5 and recasting all of the location parameters solved the problem.

**Comment by kalittles** [comment]
I tracked down the issue. I was using dependency
location: ^1.4.1

Updated my location to 2.3.5 and recasting all of the location parameters solved the problem.
