### ISSUE TITLE
A ticker was started twice.

### ISSUE THREAD

**Issue by panmin** [flutter/flutter#36680]
```
I/flutter (13598): ══╡ EXCEPTION CAUGHT BY GESTURE ╞═══════════════════════════════════════════════════════════════════
I/flutter (13598): The following assertion was thrown while handling a gesture:
I/flutter (13598): A ticker was started twice.
I/flutter (13598): A ticker that is already active cannot be started again without first stopping it.
I/flutter (13598): The affected ticker was: _WidgetTicker(created by _GlowingOverscrollIndicatorState#1febb(lifecycle
I/flutter (13598): state: created, tickers: tracking 1 ticker))
I/flutter (13598): The stack trace when the _WidgetTicker was actually created was:
I/flutter (13598): #0      new Ticker.<anonymous closure> (package:flutter/src/scheduler/ticker.dart:64:40)
I/flutter (13598): #1      new Ticker (package:flutter/src/scheduler/ticker.dart:66:6)
I/flutter (13598): #2      new _WidgetTicker (package:flutter/src/widgets/ticker_provider.dart:225:80)
I/flutter (13598): #3      __GlowingOverscrollIndicatorState&State&TickerProviderStateMixin.createTicker
I/flutter (13598): (package:flutter/src/widgets/ticker_provider.dart:161:34)
I/flutter (13598): #4      new _GlowController (package:flutter/src/widgets/overscroll_indicator.dart:264:33)
I/flutter (13598): #5      _GlowingOverscrollIndicatorState.initState
I/flutter (13598): (package:flutter/src/widgets/overscroll_indicator.dart:139:26)
I/flutter (13598): #6      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4033:58)
I/flutter (13598): #7      ComponentElement.mount (package:flutter/src/widgets/framework.dart:3902:5)
I/flutter (13598): #8      Element.inflateWidget (package:flutter/src/widgets/framework.dart:3084:14)
I/flutter (13598): #9      Element.updateChild (package:flutter/src/widgets/framework.dart:2887:12)
I/flutter (13598): #10     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3935:16)
I/flutter (13598): #11     Element.rebuild (package:flutter/src/widgets/framework.dart:3721:5)
I/flutter (13598): #12     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3907:5)
I/flutter (13598): #13     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4053:11)
I/flutter (13598): #14     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3902:5)
I/flutter (13598): #15     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3084:14)
I/flutter (13598): #16     Element.updateChild (package:flutter/src/widgets/framework.dart:2887:12)
I/flutter (13598): #17     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3935:16)
I/flutter (13598): #18     Element.rebuild (package:flutter/src/widgets/framework.dart:3721:5)
I/flutter (13598): #19     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3907:5)
I/flutter (13598): #20     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3902:5)
I/flutter (13598): #21     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3084:14)
I/flutter (13598): #22     Element.updateChild (package:flutter/src/widgets/framework.dart:2887:12)
I/flutter (13598): #23     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3935:16)
I/flutter (13598): #24     Element.rebuild (package:flutter/src/widgets/framework.dart:3721:5)
I/flutter (13598): #25     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3907:5)
I/flutter (13598): #26     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3902:5)
I/flutter (13598): #27     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3084:14)
I/flutter (13598): #28     Element.updateChild (package:flutter/src/widgets/framework.dart:2887:12)
I/flutter (13598): #29     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3935:16)
I/flutter (13598): #30     Element.rebuild (package:flutter/src/widgets/framework.dart:3721:5)
I/flutter (13598): #31     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3907:5)
I/flutter (13598): #32     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3902:5)
I/flutter (13598): #33     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3084:14)
I/flutter (13598): #34     Element.updateChild (package:flutter/src/widgets/framework.dart:2887:12)
I/flutter (13598): #35     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3935:16)
I/flutter (13598): #36     Element.rebuild (package:flutter/src/widgets/framework.dart:3721:5)
I/flutter (13598): #37     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3907:5)
I/flutter (13598): #38     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3902:5)
I/flutter (13598): #39     ParentDataElement.mount (package:flutter/src/widgets/framework.dart:4279:11)
I/flutter (13598): #40     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3084:14)
I/flutter (13598): #41     MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5198:32)
I/flutter (13598): #42     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3084:14)
I/flutter (13598): #43     Element.updateChild (package:flutter/src/widgets/framework.dart:2887:12)
I/flutter (13598): #44     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3935:16)
I/flutter (13598): #45     Element.rebuild (package:flutter/src/widgets/framework.dart:3721:5)
I/flutter (13598): #46     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3907:5)
I/flutter (13598): #47     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4053:11)
I/flutter (13598): #48     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3902:5)
I/flutter (13598): #49     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3084:14)
I/flutter (13598): #50     Element.updateChild (package:flutter/src/widgets/framework.dart:2887:12)
I/flutter (13598): #51     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3935:16)
I/flutter (13598): #52     Element.rebuild (package:flutter/src/widgets/framework.dart:3721:5)
I/flutter (13598): #53     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3907:5)
I/flutter (13598): #54     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3902:5)
I/flutter (13598): #55     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3084:14)
I/flutter (13598): #56     Element.updateChild (package:flutter/src/widgets/framework.dart:2887:12)
I/flutter (13598): #57     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3935:16)
I/flutter (13598): #58     Element.rebuild (package:flutter/src/widgets/framework.dart:3721:5)
I/flutter (13598): #59     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3907:5)
I/flutter (13598): #60     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4053:11)
I/flutter (13598): #61     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3902:5)
I/flutter (13598): #62     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3084:14)
I/flutter (13598): #63     Element.updateChild (package:flutter/src/widgets/framework.dart:2887:12)
I/flutter (13598): #64     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5092:14)
I/flutter (13598): #65     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3084:14)
I/flutter (13598): #66     Element.updateChild (package:flutter/src/widgets/framework.dart:2887:12)
I/flutter (13598): #67     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3935:16)
I/flutter (13598): #68     Element.rebuild (package:flutter/src/widgets/framework.dart:3721:5)
I/flutter (13598): #69     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3907:5)
I/flutter (13598): #70     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3902:5)
I/flutter (13598): #71     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3084:14)
I/flutter (13598): #72     Element.updateChild (package:flutter/src/widgets/framework.dart:2887:12)
I/flutter (13598): #73     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5092:14)
I/flutter (13598): #74     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3084:14)
I/flutter (13598): #75     Element.updateChild (package:flutter/src/widgets/framework.dart:2887:12)
I/flutter (13598): #76     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3935:16)
I/flutter (13598): #77     Element.rebuild (package:flutter/src/widgets/framework.dart:3721:5)
I/flutter (13598): #78     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3907:5)
I/flutter (13598): #79     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4053:11)
I/flutter (13598): #80     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3902:5)
I/flutter (13598): #81     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3084:14)
I/flutter (13598): #82     Element.updateChild (package:flutter/src/widgets/framework.dart:2887:12)
I/flutter (13598): #83     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3935:16)
I/flutter (13598): #84     Element.rebuild (package:flutter/src/widgets/framework.dart:3721:5)
I/flutter (13598): #85     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3907:5)
I/flutter (13598): #86     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4053:11)
I/flutter (13598): #87     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3902:5)
I/flutter (13598): #88     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3084:14)
I/flutter (13598): #89     Element.updateChild (package:flutter/src/widgets/framework.dart:2887:12)
I/flutter (13598): #90     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3935:16)
I/flutter (13598): #91     Element.rebuild (package:flutter/src/widgets/framework.dart:3721:5)
I/flutter (13598): #92     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3907:5)
I/flutter (13598): #93     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3902:5)
I/flutter (13598): #94     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3084:14)
I/flutter (13598): #95     Element.updateChild (package:flutter/src/widgets/framework.dart:2887:12)
I/flutter (13598): #96     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3935:16)
I/flutter (13598): #97     Element.rebuild (package:flutter/src/widgets/framework.dart:3721:5)
I/flutter (13598): #98     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3907:5)
I/flutter (13598): #99     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3902:5)
I/flutter (13598): #100    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3084:14)
I/flutter (13598): #101    Element.updateChild (package:flutter/src/widgets/framework.dart:2887:12)
I/flutter (13598): #102    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3935:16)
I/flutter (13598): #103    Element.rebuild (package:flutter/src/widgets/framework.dart:3721:5)
I/flutter (13598): #104    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3907:5)
I/flutter (13598): #105    StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4053:11)
I/flutter (13598): #106    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3902:5)
I/flutter (13598): #107    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3084:14)
I/flutter (13598): #108    Element.updateChild (package:flutter/src/widgets/framework.dart:2887:12)
I/flutter (13598): #109    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3935:16)
I/flutter (13598): #110    Element.rebuild (package:flutter/src/widgets/framework.dart:3721:5)
I/flutter (13598): #111    BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2340:33)
I/flutter (13598): #112
I/flutter (13598): _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding&WidgetsBinding.drawFrame
I/flutter (13598): (package:flutter/src/widgets/binding.dart:700:20)
I/flutter (13598): #113
I/flutter (13598): _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding._handlePersistentFrameCallback
I/flutter (13598): (package:flutter/src/rendering/binding.dart:285:5)
I/flutter (13598): #114
I/flutter (13598): _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._invokeFrameCallback
I/flutter (13598): (package:flutter/src/scheduler/binding.dart:1016:15)
I/flutter (13598): #115
I/flutter (13598): _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.handleDrawFrame
I/flutter (13598): (package:flutter/src/scheduler/binding.dart:958:9)
I/flutter (13598): #116
I/flutter (13598): _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._handleDrawFrame
I/flutter (13598): (package:flutter/src/scheduler/binding.dart:874:5)
I/flutter (13598): #120    _invoke (dart:ui/hooks.dart:236:10)
I/flutter (13598): #121    _drawFrame (dart:ui/hooks.dart:194:3)
I/flutter (13598): (elided 3 frames from package dart:async)
I/flutter (13598): 
I/flutter (13598): 
I/flutter (13598): When the exception was thrown, this was the stack:
I/flutter (13598): #0      Ticker.start.<anonymous closure> (package:flutter/src/scheduler/ticker.dart:148:9)
I/flutter (13598): #1      Ticker.start (package:flutter/src/scheduler/ticker.dart:155:6)
I/flutter (13598): #2      _GlowController.pull (package:flutter/src/widgets/overscroll_indicator.dart:372:29)
I/flutter (13598): #3      _GlowingOverscrollIndicatorState._handleScrollNotification (package:flutter/src/widgets/overscroll_indicator.dart:196:28)
I/flutter (13598): #4      NotificationListener._dispatch (package:flutter/src/widgets/notification_listener.dart:127:27)
I/flutter (13598): #5      Notification.visitAncestor (package:flutter/src/widgets/notification_listener.dart:45:20)
I/flutter (13598): #6      _ScrollNotification&LayoutChangedNotification&ViewportNotificationMixin.visitAncestor (package:flutter/src/widgets/scroll_notification.dart:31:18)
I/flutter (13598): #7      Element.visitAncestorElements (package:flutter/src/widgets/framework.dart:3492:39)
I/flutter (13598): #8      Notification.dispatch (package:flutter/src/widgets/notification_listener.dart:61:13)
I/flutter (13598): #9      DragScrollActivity.dispatchOverscrollNotification (package:flutter/src/widgets/scroll_activity.dart:450:114)
I/flutter (13598): #10     ScrollPosition.didOverscrollBy (package:flutter/src/widgets/scroll_position.dart:680:14)
I/flutter (13598): #11     ScrollPosition.setPixels (package:flutter/src/widgets/scroll_position.dart:222:9)
I/flutter (13598): #12     ScrollPositionWithSingleContext.setPixels (package:flutter/src/widgets/scroll_position_with_single_context.dart:83:18)
I/flutter (13598): #13     ScrollPositionWithSingleContext.applyUserOffset (package:flutter/src/widgets/scroll_position_with_single_context.dart:126:5)
I/flutter (13598): #14     ScrollDragController.update (package:flutter/src/widgets/scroll_activity.dart:372:14)
I/flutter (13598): #15     ScrollableState._handleDragUpdate (package:flutter/src/widgets/scrollable.dart:498:12)
I/flutter (13598): #16     DragGestureRecognizer._checkUpdate.<anonymous closure> (package:flutter/src/gestures/monodrag.dart:383:46)
I/flutter (13598): #17     GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:182:24)
I/flutter (13598): #18     DragGestureRecognizer._checkUpdate (package:flutter/src/gestures/monodrag.dart:383:7)
I/flutter (13598): #19     DragGestureRecognizer.handleEvent (package:flutter/src/gestures/monodrag.dart:253:9)
I/flutter (13598): #20     PointerRouter._dispatch (package:flutter/src/gestures/pointer_router.dart:75:13)
I/flutter (13598): #21     PointerRouter.route (package:flutter/src/gestures/pointer_router.dart:102:11)
I/flutter (13598): #22     _WidgetsFlutterBinding&BindingBase&GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:218:19)
I/flutter (13598): #23     _WidgetsFlutterBinding&BindingBase&GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:198:22)
I/flutter (13598): #24     _WidgetsFlutterBinding&BindingBase&GestureBinding._handlePointerEvent (package:flutter/src/gestures/binding.dart:156:7)
I/flutter (13598): #25     _WidgetsFlutterBinding&BindingBase&GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:102:7)
I/flutter (13598): #26     _WidgetsFlutterBinding&BindingBase&GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:86:7)
I/flutter (13598): #30     _invoke1 (dart:ui/hooks.dart:250:10)
I/flutter (13598): #31     _dispatchPointerDataPacket (dart:ui/hooks.dart:159:5)
I/flutter (13598): (elided 3 frames from package dart:async)
I/flutter (13598): 
I/flutter (13598): Handler: "onUpdate"
I/flutter (13598): Recognizer:
I/flutter (13598):   VerticalDragGestureRecognizer#60a2e
I/flutter (13598): ════════════════════════════════════════════════════════════════════════════════════════════════════
I/flutter (13598): Another exception was thrown: A ticker was started twice.
I/chatty  (13598): uid=10343(u0_a343) 1.ui identical 136 lines
```

**Comment by BondarenkoStas** [comment]
@panmin Please provide your ```flutter doctor -v```. Also Please provide  a small self-contained app that demonstrates the problem. You can include small examples [inline if they're enclosed by backticks](https://help.github.com/en/articles/creating-and-highlighting-code-blocks), or just provide a public link to a github "gist" - https://gist.github.com/.

**Comment by iapicca** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
  
Thanks for your contribution.

**Comment by NathanAP** [comment]
Sorry if I shouldn't reopen this with this context, but I'm getting this error in Flutter desktop (Mac). In Android my screen works fine, but in Mac if I try to navigate to it, my App instantly freeze and if I open directly, it freezes when I try to do any gesture. The screen has a scroll and some Streambuilders (which I don't think is the problem since its working fine on Android). This issue started less than 10 days ago when I upgraded my master channel. I guess this is the best I could tell about it, sorry again if this shouldn't be here.

**Comment by iapicca** [comment]
Hi @NathanAP 
would you mind to open a new issue filling the information indicated in the template
thank you
