### ISSUE TITLE
Can not Create new flutter project using android studio 

### ISSUE THREAD

**Issue by GayatriDarji** [flutter/flutter#36746]
Flutter crash report; please file at https://github.com/flutter/flutter/issues.

## command

flutter --no-color create --template app --description A new Flutter application. --org com.example --ios-language swift --android-language kotlin flutter_app

## exception

FileSystemException: FileSystemException: Cannot create file, path = 'D:\Development\Flutter\flutter_temp\flutter_app\android\app\src\main\res\mipmap-hdpi\ic_launcher.png' (OS Error: Access is denied.
, errno = 5)

```
#0      _File.throwIfError (dart:io/file_impl.dart:643:7)
#1      _File.createSync (dart:io/file_impl.dart:281:5)
#2      _LocalFile&LocalFileSystemEntity&ForwardingFile.createSync (package:file/src/forwarding/forwarding_file.dart:24:16)
#3      Template.render.<anonymous closure> (package:flutter_tools/src/template.dart:145:28)
#4      __InternalLinkedHashMap&_HashVMBase&MapMixin&_LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:367:8)
#5      Template.render (package:flutter_tools/src/template.dart:114:24)
#6      CreateCommand._renderTemplate (package:flutter_tools/src/commands/create.dart:622:21)
#7      CreateCommand._generateApp (package:flutter_tools/src/commands/create.dart:545:23)
<asynchronous suspension>
#8      CreateCommand.runCommand (package:flutter_tools/src/commands/create.dart:396:37)
<asynchronous suspension>
#9      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:478:18)
<asynchronous suspension>
#10     FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:383:33)
<asynchronous suspension>
#11     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:29)
<asynchronous suspension>
#12     _rootRun (dart:async/zone.dart:1124:13)
#13     _CustomZone.run (dart:async/zone.dart:1021:19)
#14     _runZoned (dart:async/zone.dart:1516:10)
#15     runZoned (dart:async/zone.dart:1463:12)
#16     AppContext.run (package:flutter_tools/src/base/context.dart:152:18)
<asynchronous suspension>
#17     FlutterCommand.run (package:flutter_tools/src/runner/flutter_command.dart:375:20)
#18     CommandRunner.runCommand (package:args/command_runner.dart:197:27)
<asynchronous suspension>
#19     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:396:21)
<asynchronous suspension>
#20     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:29)
<asynchronous suspension>
#21     _rootRun (dart:async/zone.dart:1124:13)
#22     _CustomZone.run (dart:async/zone.dart:1021:19)
#23     _runZoned (dart:async/zone.dart:1516:10)
#24     runZoned (dart:async/zone.dart:1463:12)
#25     AppContext.run (package:flutter_tools/src/base/context.dart:152:18)
<asynchronous suspension>
#26     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:356:19)
<asynchronous suspension>
#27     CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:112:25)
#28     new Future.sync (dart:async/future.dart:224:31)
#29     CommandRunner.run (package:args/command_runner.dart:112:14)
#30     FlutterCommandRunner.run (package:flutter_tools/src/runner/flutter_command_runner.dart:242:18)
#31     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:62:22)
<asynchronous suspension>
#32     _rootRun (dart:async/zone.dart:1124:13)
#33     _CustomZone.run (dart:async/zone.dart:1021:19)
#34     _runZoned (dart:async/zone.dart:1516:10)
#35     runZoned (dart:async/zone.dart:1500:12)
#36     run.<anonymous closure> (package:flutter_tools/runner.dart:60:18)
<asynchronous suspension>
#37     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:29)
<asynchronous suspension>
#38     _rootRun (dart:async/zone.dart:1124:13)
#39     _CustomZone.run (dart:async/zone.dart:1021:19)
#40     _runZoned (dart:async/zone.dart:1516:10)
#41     runZoned (dart:async/zone.dart:1463:12)
#42     AppContext.run (package:flutter_tools/src/base/context.dart:152:18)
<asynchronous suspension>
#43     runInContext (package:flutter_tools/src/context_runner.dart:56:24)
<asynchronous suspension>
#44     run (package:flutter_tools/runner.dart:51:10)
#45     main (package:flutter_tools/executable.dart:62:9)
<asynchronous suspension>
#46     main (file:///C:/b/s/w/ir/k/archive/flutter/packages/flutter_tools/bin/flutter_tools.dart:8:3)
#47     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:299:32)
#48     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:12)
```

## flutter doctor

```
[✓] Flutter (Channel stable, v1.7.8+hotfix.3, on Microsoft Windows [Version 6.3.9600], locale en-US)
    • Flutter version 1.7.8+hotfix.3 at C:\Src\flutter
    • Framework revision b712a172f9 (2 weeks ago), 2019-07-09 13:14:38 -0700
    • Engine revision 54ad777fd2
    • Dart version 2.4.0

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at D:\android-sdk-window
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = D:\android-sdk-window
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
    • All Android licenses accepted.

[✓] Android Studio (version 3.4)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 37.1.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

[!] Connected device
    ! No devices available

! Doctor found issues in 1 category.
```

**Comment by ibhavikmakwana** [comment]
Try disabling your Antivirus or Windows Defender.

**Comment by GayatriDarji** [comment]
@ibhavikmakwana  thank You . I disable  Antivirus. Now it is working .
