### ISSUE TITLE
Assertion failure when rotating screen during animation

### ISSUE THREAD

**Issue by jason-simmons** [flutter/flutter#3675]
1) Run Stocks and scroll the list
2) Tap on the Android task switcher while the list is animating
3) Rotate the screen
4) Resume the Stocks app

This triggers an assertion failure:

I/flutter (17668): The following assertion was thrown during performLayout():
I/flutter (17668): 'package:flutter/src/widgets/scrollable.dart': Failed assertion: line 389: '_controller.isAnimating
I/flutter (17668): || _simulation == null' is not true.
I/flutter (17668): Either the assertion indicates an error in the framework itself, or we should provide substantially
I/flutter (17668): more information in this error message to help you determine and fix the underlying cause.
I/flutter (17668): In either case, please report this assertion by filing a bug on GitHub:
I/flutter (17668):   https://github.com/flutter/flutter/issues/new
I/flutter (17668): The following RenderObject was being processed when the exception was fired:
I/flutter (17668):   RenderList NEEDS-LAYOUT
I/flutter (17668): This RenderObject had the following creator information:
I/flutter (17668):   ListViewport ← Listener ← _GestureSemantics ← RawGestureDetector-[GlobalKey 623875018] ←
I/flutter (17668):   ScrollableList-['stock-list'] ← StockList ← Container-['StockHomeTab.market'] ←
I/flutter (17668):   KeyedSubtree-['['StockHomeTab.market']'] ← RepaintBoundary-['['['StockHomeTab.market']']'] ←
I/flutter (17668):   PageViewport ← ⋯
I/flutter (17668): This RenderObject had the following descendants (showing up to depth 5):
I/flutter (17668):   RenderRepaintBoundary
I/flutter (17668):     RenderSemanticsGestureHandler
I/flutter (17668):       RenderPointerListener
I/flutter (17668):         RenderDecoratedBox
I/flutter (17668):           RenderPadding
I/flutter (17668):   RenderRepaintBoundary NEEDS-LAYOUT
I/flutter (17668):     RenderSemanticsGestureHandler NEEDS-LAYOUT
I/flutter (17668):       RenderPointerListener NEEDS-LAYOUT
I/flutter (17668):         RenderDecoratedBox NEEDS-LAYOUT
I/flutter (17668):           RenderPadding NEEDS-LAYOUT
I/flutter (17668):   RenderRepaintBoundary NEEDS-LAYOUT
I/flutter (17668):     RenderSemanticsGestureHandler NEEDS-LAYOUT
I/flutter (17668):       RenderPointerListener NEEDS-LAYOUT
I/flutter (17668):         RenderDecoratedBox NEEDS-LAYOUT
I/flutter (17668):           RenderPadding NEEDS-LAYOUT
I/flutter (17668):   RenderRepaintBoundary NEEDS-LAYOUT
I/flutter (17668):     RenderSemanticsGestureHandler NEEDS-LAYOUT
I/flutter (17668):       RenderPointerListener NEEDS-LAYOUT
I/flutter (17668):         RenderDecoratedBox NEEDS-LAYOUT
I/flutter (17668):           RenderPadding NEEDS-LAYOUT
I/flutter (17668): When the exception was thrown, this was the stack:
I/flutter (17668): #0      _AssertionError._throwNew (dart:core-patch/errors_patch.dart:27)
I/flutter (17668): #1      ScrollableState.didUpdateScrollBehavior (package:flutter/src/widgets/scrollable.dart:389)
I/flutter (17668): #2      _ScrollableListState._handleExtentsChanged.<anonymous closure> (package:flutter/src/widgets/scrollable_list.dart:96)
I/flutter (17668): #3      State.setState (package:flutter/src/widgets/framework.dart:419)
I/flutter (17668): #4      _ScrollableListState._handleExtentsChanged (package:flutter/src/widgets/scrollable_list.dart:95)
I/flutter (17668): #5      _VirtualListViewportElement.layout (package:flutter/src/widgets/scrollable_list.dart:285)
I/flutter (17668): #6      RenderObject.invokeLayoutCallback (package:flutter/src/rendering/object.dart:1348)
I/flutter (17668): #7      RenderList.performLayout (package:flutter/src/rendering/list.dart:138)
I/flutter (17668): #8      RenderObject.layout (package:flutter/src/rendering/object.dart:1268)
I/flutter (17668): #9      RenderProxyBox.performLayout (package:flutter/src/rendering/proxy_box.dart:80)
I/flutter (17668): #10     RenderObject.layout (package:flutter/src/rendering/object.dart:1268)
I/flutter (17668): #11     RenderProxyBox.performLayout (package:flutter/src/rendering/proxy_box.dart:80)
...

**Comment by jason-simmons** [comment]
Just saw another one of these in Gallery

07-21 14:13:00.758 15204 15240 I flutter : ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
07-21 14:13:00.773 15204 15240 I flutter : The following assertion was thrown while finalizing the widget tree:
07-21 14:13:00.784 15204 15240 I flutter : 'package:flutter/src/widgets/scrollable.dart': Failed assertion: line 561: '_controller.isAnimating
07-21 14:13:00.784 15204 15240 I flutter : || _simulation == null' is not true.
07-21 14:13:00.834 15204 15240 I flutter : When the exception was thrown, this was the stack:
07-21 14:13:00.879 15204 15240 I flutter : #0      _AssertionError._throwNew (dart:core-patch/errors_patch.dart:27)
07-21 14:13:00.879 15204 15240 I flutter : #1      _AssertionError._checkAssertion (dart:core-patch/errors_patch.dart:34)
07-21 14:13:00.879 15204 15240 I flutter : #2      ScrollableState._stop (package:flutter/src/widgets/scrollable.dart:561)
07-21 14:13:00.879 15204 15240 I flutter : #3      ScrollableState.dispose (package:flutter/src/widgets/scrollable.dart:261)
07-21 14:13:00.879 15204 15240 I flutter : #4      StatefulElement.unmount (package:flutter/src/widgets/framework.dart:2119)
07-21 14:13:00.879 15204 15240 I flutter : #5      _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1064)
07-21 14:13:00.879 15204 15240 I flutter : #6      _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1068)
07-21 14:13:00.880 15204 15240 I flutter : #7      ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:1999)
07-21 14:13:00.880 15204 15240 I flutter : #8      _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1066)
07-21 14:13:00.880 15204 15240 I flutter : #9      _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1068)
07-21 14:13:00.880 15204 15240 I flutter : #10     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:2623)
07-21 14:13:00.880 15204 15240 I flutter : #11     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1066)
07-21 14:13:00.880 15204 15240 I flutter : #12     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1068)
07-21 14:13:00.881 15204 15240 I flutter : #13     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:1999)
07-21 14:13:00.881 15204 15240 I flutter : #14     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1066)
07-21 14:13:00.881 15204 15240 I flutter : #15     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1068)
07-21 14:13:00.881 15204 15240 I flutter : #16     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:1999)
07-21 14:13:00.881 15204 15240 I flutter : #17     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1066)
07-21 14:13:00.881 15204 15240 I flutter : #18     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1068)
07-21 14:13:00.881 15204 15240 I flutter : #19     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:1999)
07-21 14:13:00.882 15204 15240 I flutter : #20     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1066)
07-21 14:13:00.882 15204 15240 I flutter : #21     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1068)
07-21 14:13:00.882 15204 15240 I flutter : #22     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:1999)
07-21 14:13:00.882 15204 15240 I flutter : #23     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1066)
07-21 14:13:00.882 15204 15240 I flutter : #24     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1068)
07-21 14:13:00.882 15204 15240 I flutter : #25     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:1999)
07-21 14:13:00.882 15204 15240 I flutter : #26     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1066)
07-21 14:13:00.887 15204 15240 I flutter : #27     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1068)
07-21 14:13:00.887 15204 15240 I flutter : #28     MultiChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:2710)
07-21 14:13:00.887 15204 15240 I flutter : #29     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1066)
07-21 14:13:00.887 15204 15240 I flutter : #30     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1068)
07-21 14:13:00.887 15204 15240 I flutter : #31     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:1999)
07-21 14:13:00.888 15204 15240 I flutter : #32     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1066)
07-21 14:13:00.888 15204 15240 I flutter : #33     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1068)
07-21 14:13:00.888 15204 15240 I flutter : #34     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:1999)
07-21 14:13:00.888 15204 15240 I flutter : #35     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1066)
07-21 14:13:00.888 15204 15240 I flutter : #36     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1068)
07-21 14:13:00.888 15204 15240 I flutter : #37     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:1999)
07-21 14:13:00.888 15204 15240 I flutter : #38     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1066)
07-21 14:13:00.889 15204 15240 I flutter : #39     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1068)
07-21 14:13:00.889 15204 15240 I flutter : #40     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:2623)
07-21 14:13:00.889 15204 15240 I flutter : #41     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1066)
07-21 14:13:00.889 15204 15240 I flutter : #42     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1068)
07-21 14:13:00.889 15204 15240 I flutter : #43     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:1999)
07-21 14:13:00.889 15204 15240 I flutter : #44     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1066)
07-21 14:13:00.890 15204 15240 I flutter : #45     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1068)
07-21 14:13:00.890 15204 15240 I flutter : #46     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:2623)
07-21 14:13:00.890 15204 15240 I flutter : #47     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1066)
07-21 14:13:00.890 15204 15240 I flutter : #48     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1068)
07-21 14:13:00.890 15204 15240 I flutter : #49     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:1999)
07-21 14:13:00.890 15204 15240 I flutter : #50     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1066)
07-21 14:13:00.890 15204 15240 I flutter : #51     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1068)
07-21 14:13:00.891 15204 15240 I flutter : #52     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:2623)
07-21 14:13:00.891 15204 15240 I flutter : #53     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1066)
07-21 14:13:00.891 15204 15240 I flutter : #54     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1068)
07-21 14:13:00.891 15204 15240 I flutter : #55     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:1999)
07-21 14:13:00.891 15204 15240 I flutter : #56     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1066)
07-21 14:13:00.891 15204 15240 I flutter : #57     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1068)
07-21 14:13:00.891 15204 15240 I flutter : #58     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:1999)
07-21 14:13:00.892 15204 15240 I flutter : #59     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1066)
07-21 14:13:00.892 15204 15240 I flutter : #60     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1068)
07-21 14:13:00.892 15204 15240 I flutter : #61     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:1999)
07-21 14:13:00.892 15204 15240 I flutter : #62     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1066)
07-21 14:13:00.892 15204 15240 I flutter : #63     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1068)
07-21 14:13:00.892 15204 15240 I flutter : #64     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:1999)
07-21 14:13:00.893 15204 15240 I flutter : #65     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1066)
07-21 14:13:00.902 15204 15240 I flutter : #66     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1068)
07-21 14:13:00.902 15204 15240 I flutter : #67     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:1999)
07-21 14:13:00.902 15204 15240 I flutter : #68     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1066)
07-21 14:13:00.902 15204 15240 I flutter : #69     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1068)
07-21 14:13:00.902 15204 15240 I flutter : #70     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:1999)
07-21 14:13:00.902 15204 15240 I flutter : #71     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1066)
07-21 14:13:00.903 15204 15240 I flutter : #72     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1068)
07-21 14:13:00.903 15204 15240 I flutter : #73     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:1999)
07-21 14:13:00.903 15204 15240 I flutter : #74     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1066)
07-21 14:13:00.903 15204 15240 I flutter : #75     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1068)
07-21 14:13:00.903 15204 15240 I flutter : #76     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:1999)
07-21 14:13:00.903 15204 15240 I flutter : #77     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1066)
07-21 14:13:00.904 15204 15240 I flutter : #78     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1068)
07-21 14:13:00.904 15204 15240 I flutter : #79     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:2623)
07-21 14:13:00.904 15204 15240 I flutter : #80     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1066)
07-21 14:13:00.904 15204 15240 I flutter : #81     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1068)
07-21 14:13:00.904 15204 15240 I flutter : #82     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:2623)
07-21 14:13:00.904 15204 15240 I flutter : #83     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1066)
07-21 14:13:00.904 15204 15240 I flutter : #84     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1068)
07-21 14:13:00.905 15204 15240 I flutter : #85     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:1999)
07-21 14:13:00.905 15204 15240 I flutter : #86     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1066)
07-21 14:13:00.905 15204 15240 I flutter : #87     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1068)
07-21 14:13:00.905 15204 15240 I flutter : #88     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:2623)
07-21 14:13:00.905 15204 15240 I flutter : #89     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1066)
07-21 14:13:00.905 15204 15240 I flutter : #90     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1068)
07-21 14:13:00.905 15204 15240 I flutter : #91     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:2623)
07-21 14:13:00.906 15204 15240 I flutter : #92     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1066)
07-21 14:13:00.906 15204 15240 I flutter : #93     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1068)
07-21 14:13:00.906 15204 15240 I flutter : #94     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:1999)
07-21 14:13:00.906 15204 15240 I flutter : #95     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1066)
07-21 14:13:00.906 15204 15240 I flutter : #96     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1068)
07-21 14:13:00.906 15204 15240 I flutter : #97     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:2623)
07-21 14:13:00.906 15204 15240 I flutter : #98     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1066)
07-21 14:13:00.907 15204 15240 I flutter : #99     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1068)
07-21 14:13:00.907 15204 15240 I flutter : #100    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:1999)
07-21 14:13:00.907 15204 15240 I flutter : #101    _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1066)
07-21 14:13:00.907 15204 15240 I flutter : #102    _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1068)
07-21 14:13:00.907 15204 15240 I flutter : #103    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:1999)
07-21 14:13:00.907 15204 15240 I flutter : #104    _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1066)
07-21 14:13:00.908 15204 15240 I flutter : #105    _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1068)
07-21 14:13:00.908 15204 15240 I flutter : #106    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:1999)
07-21 14:13:00.908 15204 15240 I flutter : #107    _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1066)
07-21 14:13:00.908 15204 15240 I flutter : #108    _InactiveElements._unmountAll (package:flutter/src/widgets/framework.dart:1076)
07-21 14:13:00.908 15204 15240 I flutter : #109    BuildOwner.finalizeTree.<anonymous closure> (package:flutter/src/widgets/framework.dart:1268)
07-21 14:13:00.908 15204 15240 I flutter : #110    BuildOwner.lockState (package:flutter/src/widgets/framework.dart:1199)
07-21 14:13:00.913 15204 15240 I flutter : #111    BuildOwner.finalizeTree (package:flutter/src/widgets/framework.dart:1267)
07-21 14:13:00.913 15204 15240 I flutter : #112    BindingBase&SchedulerBinding&GestureBinding&ServicesBinding&RendererBinding&WidgetsBinding.beginFrame (package:flutter/src/widgets/binding.dart:211)
07-21 14:13:00.913 15204 15240 I flutter : #113    BindingBase&SchedulerBinding&GestureBinding&ServicesBinding&RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:149)
07-21 14:13:00.913 15204 15240 I flutter : #114    BindingBase&SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:476)
07-21 14:13:00.913 15204 15240 I flutter : #115    BindingBase&SchedulerBinding.handleBeginFrame (package:flutter/src/scheduler/binding.dart:436)
07-21 14:13:00.914 15204 15240 I flutter : #116    _beginFrame (file:///ssd2/sky/engine/src/out/android_debug_unopt/gen/sky/bindings/dart_ui/hooks.dart:48)
07-21 14:13:00.914 15204 15240 I flutter : ════════════════════════════════════════════════════════════════════════════════════════════════════
