### ISSUE TITLE
Material Gallery crash in HeroController

### ISSUE THREAD

**Issue by jimbeveridge** [flutter/flutter#3682]
## Steps to Reproduce

I was looking at the list of Components in the Material Gallery. I  thought that I accidentally dragged a finger on the screen and it crashed, but I can't reproduce it.
## Flutter Doctor

```
[✓] Flutter (on Linux, channel master)
    • Flutter at /media/jimbe/mojossd/sysui/src/third_party/flutter
    • Framework revision 60755f6d9c (3 days ago), engine revision 28fbcc3a38

[✓] Android toolchain - develop for Android devices (Android SDK 23.0.2)
    • Android SDK at /usr/local/google/home/jimbe/Android/Sdk
    • Platform android-23, build-tools 23.0.2
    • OpenJDK Runtime Environment (build 1.8.0-google-v7-119990345-117822431)

[✓] Atom - a lightweight development environment for Flutter
    • Atom installed; Flutter plugin version 0.2.2
```
## Logs and Crash Reports

Please attach any relevent logs or crash reports.

```
I/flutter (13489): ══╡ EXCEPTION CAUGHT BY SCHEDULER LIBRARY ╞═════════════════════════════════════════════════════════
I/flutter (13489): The following assertion was thrown during a scheduler callback:
I/flutter (13489): 'package:flutter/src/widgets/heroes.dart': Failed assertion: line 481: '_from != null' is not true.
I/flutter (13489): Either the assertion indicates an error in the framework itself, or we should provide substantially
I/flutter (13489): more information in this error message to help you determine and fix the underlying cause.
I/flutter (13489): In either case, please report this assertion by filing a bug on GitHub:
I/flutter (13489):   https://github.com/flutter/flutter/issues/new
I/flutter (13489): When the exception was thrown, this was the stack:
I/flutter (13489): #0      _AssertionError._throwNew (dart:core-patch/errors_patch.dart:27)
I/flutter (13489): #1      HeroController._getMostValuableKeys (package:flutter/src/widgets/heroes.dart:481)
I/flutter (13489): #2      HeroController._updateQuest (package:flutter/src/widgets/heroes.dart:492)
I/flutter (13489): #3      BindingBase&SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:393)
I/flutter (13489): #4      BindingBase&SchedulerBinding.handleBeginFrame (package:flutter/src/scheduler/binding.dart:362)
I/flutter (13489): #5      _beginFrame (file:///b/build/slave/Linux_Engine/build/src/out/android_Release/gen/sky/bindings/hooks.dart:48)
I/flutter (13489): ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

```

**Comment by HansMuller** [comment]
This code path doesn't exist anymore, see https://github.com/flutter/flutter/pull/8112
