### ISSUE TITLE
[video_player] does not support http url on Android 9.0

### ISSUE THREAD

**Issue by zhengbomo** [flutter/flutter#36849]
```dart
var url = "http://test.bombox.org/test.mp4"
VideoPlayerController.network(url);
```

it doesn't work and log the following error on Android9.0, but work well on Android 8.0-
```

E/ExoPlayerImplInternal( 5671): Source error.
E/ExoPlayerImplInternal( 5671): com.google.android.exoplayer2.upstream.HttpDataSource$HttpDataSourceException: Unable to connect to http://test.bombox.org/test.mp4
E/ExoPlayerImplInternal( 5671): 	at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.open(DefaultHttpDataSource.java:281)
E/ExoPlayerImplInternal( 5671): 	at com.google.android.exoplayer2.upstream.StatsDataSource.open(StatsDataSource.java:83)
E/ExoPlayerImplInternal( 5671): 	at com.google.android.exoplayer2.source.ExtractorMediaPeriod$ExtractingLoadable.load(ExtractorMediaPeriod.java:885)
E/ExoPlayerImplInternal( 5671): 	at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:381)
E/ExoPlayerImplInternal( 5671): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
E/ExoPlayerImplInternal( 5671): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
E/ExoPlayerImplInternal( 5671): 	at java.lang.Thread.run(Thread.java:764)
E/ExoPlayerImplInternal( 5671): Caused by: java.io.IOException: Cleartext HTTP traffic to test.bombox.org not permitted
E/ExoPlayerImplInternal( 5671): 	at com.android.okhttp.HttpHandler$CleartextURLFilter.checkURLPermitted(HttpHandler.java:115)
E/ExoPlayerImplInternal( 5671): 	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:458)
E/ExoPlayerImplInternal( 5671): 	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.connect(HttpURLConnectionImpl.java:127)
E/ExoPlayerImplInternal( 5671): 	at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.makeConnection(DefaultHttpDataSource.java:528)
E/ExoPlayerImplInternal( 5671): 	at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.makeConnection(DefaultHttpDataSource.java:444)
E/ExoPlayerImplInternal( 5671): 	at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.open(DefaultHttpDataSource.java:279)
E/ExoPlayerImplInternal( 5671): 	... 6 more
V/DartMessenger( 5671): Sending message with callback over channel 'flutter.io/videoPlayer/videoEvents0'
I/flutter ( 5671): Video player had error com.google.android.exoplayer2.ExoPlaybackException: com.google.android.exoplayer2.upstream.HttpDataSource$HttpDataSourceException: Unable to connect to http://test.bombox.org/test.mp4
```

when i try to change the url for https for the same video file, it work well
```dart
var url = "https://xf-xfsdk-doc.oss-cn-shenzhen.aliyuncs.com/iOS/temp/test.mp4"
VideoPlayerController.network(url);
```

[video_player]
Android 9.0 Simulator

how can i fix it? help

**Comment by BugsBunnyBR** [comment]
Did you try Https? New versions of Android enforce security.

**Comment by zhengbomo** [comment]
> Did you try Https? New versions of Android enforce security.

yes，https work, but http throw error 
```
HttpDataSourceException: Unable to connect to http://test.bombox.org/test.mp4
```
is there any way compatible way for http on Android 9.0 ?

**Comment by you-zuo** [comment]
android:usesCleartextTraffic="true" add into AndroidManifest.xml

**Comment by zhengbomo** [comment]
> android:usesCleartextTraffic="true" add into AndroidManifest.xml

@you-zuo it doesn‘t work

```xml
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    package="io.flutter.plugins.videoplayerexample">

    <uses-permission android:name="android.permission.INTERNET"/>

    <application
        android:name="io.flutter.app.FlutterApplication"
        android:usesCleartextTraffic="true"
        android:label="video_player_example"
        android:icon="@mipmap/ic_launcher"
        android:networkSecurityConfig="@xml/network_security_config">
        <activity
            android:name=".MainActivity"
            android:launchMode="singleTop"
            android:theme="@style/LaunchTheme"
            android:configChanges="orientation|keyboardHidden|keyboard|screenSize|locale|layoutDirection"
            android:hardwareAccelerated="true"
            android:windowSoftInputMode="adjustResize">
            <meta-data
                android:name="io.flutter.app.android.SplashScreenUntilFirstFrame"
                android:value="true" />
            <intent-filter>
                <action android:name="android.intent.action.MAIN"/>
                <category android:name="android.intent.category.LAUNCHER"/>
            </intent-filter>
        </activity>
    </application>
</manifest>
```

**Comment by BugsBunnyBR** [comment]
check the contents of `network_security_config.xml`

medium that may help: https://medium.com/@son.rommer/fix-cleartext-traffic-error-in-android-9-pie-2f4e9e2235e6

Just as a note: You really should try to use https as the platform recommends/enforces for your release builds. There is not just a good reason not to use https in these days.

**Comment by zhengbomo** [comment]
@BugsBunnyBR I do the config by the following link, it doesnot work too, i use the official demo [video_player](https://github.com/flutter/plugins/tree/master/packages/video_player)

**Comment by BugsBunnyBR** [comment]
Post the contents of network_security_config.xml

**Comment by zhengbomo** [comment]
i use the official demo here: [network_security_config.xml](https://github.com/flutter/plugins/blob/master/packages/video_player/example/android/app/src/main/res/xml/network_security_config.xml)
```xml
<?xml version="1.0" encoding="utf-8"?>
<network-security-config>
    <domain-config cleartextTrafficPermitted="true">
        <domain includeSubdomains="true">www.sample-videos.com</domain>
        <domain includeSubdomains="true">184.72.239.149</domain>
        <domain includeSubdomains="true">test.bombox.org</domain>
        <domain includeSubdomains="true">127.0.0.1</domain>
        <domain includeSubdomains="true">localhost</domain>
    </domain-config>
</network-security-config>
```

**Comment by BugsBunnyBR** [comment]
1) That file does in the apk, that is in the phone/emulator. So localhost or 127.0.0.1 is the phone. Not you dev machine. Even in the emulator. Try to place your machine IP.
2) remove domains you don't use.

**Comment by zhengbomo** [comment]
clean the flutter and retry, it works, configuration is the same as the official demo

**Comment by kyawthura2018** [comment]
Thanks this works for me. Thank you so much.

> check the contents of `network_security_config.xml`
> 
> medium that may help: https://medium.com/@son.rommer/fix-cleartext-traffic-error-in-android-9-pie-2f4e9e2235e6
> 
> Just as a note: You really should try to use https as the platform recommends/enforces for your release builds. There is not just a good reason not to use https in these days.
> For iOS you also need https:
> https://techcrunch.com/2016/06/14/apple-will-require-https-connections-for-ios-apps-by-the-end-of-2016/
