### ISSUE TITLE
WhereIterator.moveNext: Failed assertion: boolean expression must not be null

### ISSUE THREAD

**Issue by JamesKarl** [flutter/flutter#36928]
```
I/flutter: ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
I/flutter: The following assertion was thrown building PlanWaybillWidget(dirty, state:
I/flutter: _PlanWaybillWidgetState#8699a):
I/flutter: Failed assertion: boolean expression must not be null
I/flutter: Either the assertion indicates an error in the framework itself, or we should provide substantially
I/flutter: more information in this error message to help you determine and fix the underlying cause.
I/flutter: In either case, please report this assertion by filing a bug on GitHub:
I/flutter:   https://github.com/flutter/flutter/issues/new?template=BUG.md
I/flutter: When the exception was thrown, this was the stack:
I/flutter: #0      WhereIterator.moveNext (dart:_internal/iterable.dart:439:11)
I/flutter: #1      MappedIterator.moveNext (dart:_internal/iterable.dart:391:19)
I/flutter: #2      new List.from (dart:core-patch/array_patch.dart:45:19)
I/flutter: #3      Iterable.toList (dart:core/iterable.dart:398:5)
I/flutter: #4      ApiPlanOfAssayReportBean.getCheckedWaybillId (package:shop_mobile/repository/anslysis/bean/ApiAssayQueryWaybillBean.dart:80:11)
I/flutter: #5      _PlanWaybillWidgetState._buildRightColumn (package:shop_mobile/stories/pad/assay/waybill/PlanWaybillWidget.dart:95:23)
I/flutter: #6      _PlanWaybillWidgetState._buildPlanItemView (package:shop_mobile/stories/pad/assay/waybill/PlanWaybillWidget.dart:81:13)
I/flutter: #7      _PlanWaybillWidgetState.build (package:shop_mobile/stories/pad/assay/waybill/PlanWaybillWidget.dart:53:14)
I/flutter: #8      StatefulElement.build (package:flutter/src/widgets/framework.dart:4012:27)
I/flutter: #9      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3924:15)
I/flutter: #10     Element.rebuild (package:flutter/src/widgets/framework.dart:3721:5)
I/flutter: #11     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3907:5)
I/flutter: #12     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4053:11)
I/flutter: #13     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3902:5)
I/flutter: #14     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3084:14)
I/flutter: #15     Element.updateChild (package:flutter/src/widgets/framework.dart:2887:12)
I/flutter: #16     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5092:14)
I/flutter: #17     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3084:14)
I/flutter: #18     Element.updateChild (package:flutter/src/widgets/framework.dart:2887:12)
I/flutter: #19     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5092:14)
I/flutter: #20     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3084:14)
I/flutter: #21     Element.updateChild (package:flutter/src/widgets/framework.dart:2887:12)
I/flutter: #22     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3935:16)
I/flutter: #23     Element.rebuild (package:flutter/src/widgets/framework.dart:3721:5)
I/flutter: #24     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3907:5)
I/flutter: #25     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3902:5)
I/flutter: #26     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3084:14)
I/flutter: #27     Element.updateChild (package:flutter/src/widgets/framework.dart:2887:12)
I/flutter: #28     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3935:16)
I/flutter: #29     Element.rebuild (package:flutter/src/widgets/framework.dart:3721:5)
I/flutter: #30     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3907:5)
I/flutter: #31     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3902:5)
I/flutter: #32     ParentDataElement.mount (package:flutter/src/widgets/framework.dart:4279:11)
I/flutter: #33     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3084:14)
I/flutter: #34     Element.updateChild (package:flutter/src/widgets/framework.dart:2887:12)
I/flutter: #35     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3935:16)
I/flutter: #36     Element.rebuild (package:flutter/src/widgets/framework.dart:3721:5)
I/flutter: #37     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3907:5)
I/flutter: #38     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4053:11)
I/flutter: #39     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3902:5)
I/flutter: #40     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3084:14)
I/flutter: #41     Element.updateChild (package:flutter/src/widgets/framework.dart:2887:12)
I/flutter: #42     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3935:16)
I/flutter: #43     Element.rebuild (package:flutter/src/widgets/framework.dart:3721:5)
I/flutter: #44     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3907:5)
I/flutter: #45     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3902:5)
I/flutter: #46     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3084:14)
I/flutter: #47     Element.updateChild (package:flutter/src/widgets/framework.dart:2887:12)
I/flutter: #48     SliverMultiBoxAdaptorElement.updateChild (package:flutter/src/widgets/sliver.dart:1181:36)
I/flutter: #49     SliverMultiBoxAdaptorElement.createChild.<anonymous closure> (package:flutter/src/widgets/sliver.dart:1166:20)
I/flutter: #50     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2320:19)
I/flutter: #51     SliverMultiBoxAdaptorElement.createChild (package:flutter/src/widgets/sliver.dart:1159:11)
I/flutter: #52     RenderSliverMultiBoxAdaptor._createOrObtainChild.<anonymous closure> (package:flutter/src/rendering/sliver_multi_box_adaptor.dart:354:23)
I/flutter: #53     RenderObject.invokeLayoutCallback.<anonymous closure> (package:flutter/src/rendering/object.dart:1715:58)
I/flutter: #54     PipelineOwner._enableMutationsToDirtySubtrees (package:flutter/src/rendering/object.dart:796:15)
I/flutter: #55     RenderObject.invokeLayoutCallback (package:flutter/src/rendering/object.dart:1715:13)
I/flutter: #56     RenderSliverMultiBoxAdaptor._createOrObtainChild (package:flutter/src/rendering/sliver_multi_box_adaptor.dart:343:5)
I/flutter: #57     RenderSliverMultiBoxAdaptor.addInitialChild (package:flutter/src/rendering/sliver_multi_box_adaptor.dart:427:5)
I/flutter: #58     RenderSliverList.performLayout (package:flutter/src/rendering/sliver_list.dart:78:12)
I/flutter: #59     RenderObject.layout (package:flutter/src/rendering/object.dart:1619:7)
I/flutter: #60     RenderSliverPadding.performLayout (package:flutter/src/rendering/sliver_padding.dart:181:11)
I/flutter: #61     RenderObject.layout (package:flutter/src/rendering/object.dart:1619:7)
I/flutter: #62     RenderViewportBase.layoutChildSequence (package:flutter/src/rendering/viewport.dart:406:13)
I/flutter: #63     RenderViewport._attemptLayout (package:flutter/src/rendering/viewport.dart:1334:12)
I/flutter: #64     RenderViewport.performLayout (package:flutter/src/rendering/viewport.dart:1252:20)
I/flutter: #65     RenderObject.layout (package:flutter/src/rendering/object.dart:1619:7)
I/flutter: #66     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter: #67     RenderObject.layout (package:flutter/src/rendering/object.dart:1619:7)
I/flutter: #68     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter: #69     RenderObject.layout (package:flutter/src/rendering/object.dart:1619:7)
I/flutter: #70     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter: #71     RenderObject.layout (package:flutter/src/rendering/object.dart:1619:7)
I/flutter: #72     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter: #73     RenderObject.layout (package:flutter/src/rendering/object.dart:1619:7)
I/flutter: #74     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter: #75     RenderObject.layout (package:flutter/src/rendering/object.dart:1619:7)
I/flutter: #76     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter: #77     RenderObject.layout (package:flutter/src/rendering/object.dart:1619:7)
I/flutter: #78     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter: #79     RenderObject.layout (package:flutter/src/rendering/object.dart:1619:7)
I/flutter: #80     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter: #81     RenderObject.layout (package:flutter/src/rendering/object.dart:1619:7)
I/flutter: #82     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter: #83     RenderObject.layout (package:flutter/src/rendering/object.dart:1619:7)
I/flutter: #84     RenderPadding.performLayout (package:flutter/src/rendering/shifted_box.dart:206:11)
I/flutter: #85     RenderObject.layout (package:flutter/src/rendering/object.dart:1619:7)
I/flutter: #86     MultiChildLayoutDelegate.layoutChild (package:flutter/src/rendering/custom_layout.dart:142:11)
I/flutter: #87     _ScaffoldLayout.performLayout (package:flutter/src/material/scaffold.dart:443:7)
I/flutter: #88     MultiChildLayoutDelegate._callPerformLayout (package:flutter/src/rendering/custom_layout.dart:212:7)
I/flutter: #89     RenderCustomMultiChildLayoutBox.performLayout (package:flutter/src/rendering/custom_layout.dart:356:14)
I/flutter: #90     RenderObject._layoutWithoutResize (package:flutter/src/rendering/object.dart:1496:7)
I/flutter: #91     PipelineOwner.flushLayout (package:flutter/src/rendering/object.dart:765:18)
I/flutter: #92     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding.drawFrame (package:flutter/src/rendering/binding.dart:346:19)
I/flutter: #93     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding&WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:701:13)
I/flutter: #94     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:285:5)
I/flutter: #95     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1016:15)
I/flutter: #96     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:958:9)
I/flutter: #97     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:874:5)
I/flutter: #101    _invoke (dart:ui/hooks.dart:236:10)
I/flutter: #102    _drawFrame (dart:ui/hooks.dart:194:3)
I/flutter: (elided 3 frames from package dart:async)
```

**Comment by BondarenkoStas** [comment]
@JamesKarl is the issue still relevant? If yes, please provide  a small self-contained app that demonstrates the problem. You can include small examples [inline if they're enclosed by backticks](https://help.github.com/en/articles/creating-and-highlighting-code-blocks), or just provide a public link to a github "gist" - https://gist.github.com/. Also your `flutter doctor -v` output.

**Comment by JamesKarl** [comment]
@BondarenkoStas This issue doesn't occur recently. You can close this issues for now. If this issue reproduce again in future, I will provide a self-contained app. Thank you very much for your support and efforts.
