### ISSUE TITLE
Upgrade Crash report

### ISSUE THREAD

**Issue by YeyuanLee** [flutter/flutter#36941]
## command
```
flutter upgrade --force
```
## exception
```
ProcessException: ProcessException: Process "git" exited abnormally:
error: unable to stat just-written file packages/flutter_tools/test/android/android_emulator_test.dart: No such file or directory
error: unable to stat just-written file packages/flutter_tools/test/android/android_sdk_test.dart: No such file or directory
error: unable to stat just-written file packages/flutter_tools/test/android/android_studio_test.dart: No such file or directory
error: unable to stat just-written file packages/flutter_tools/test/android/android_studio_validator_test.dart: No such file or directory
error: unable to stat just-written file packages/flutter_tools/test/android/android_workflow_test.dart: No such file or directory
error: unable to stat just-written file packages/flutter_tools/test/android/gradle_test.dart: No such file or directory
error: unable to stat just-written file packages/flutter_tools/test/application_package_test.dart: No such file or directory
error: unable to stat just-written file packages/flutter_tools/test/artifacts_test.dart: No such file or directory
error: unable to stat just-written file packages/flutter_tools/test/asset_bundle_package_fonts_test.dart: No such file or directory
error: unable to stat just-written file packages/flutter_tools/test/asset_bundle_package_test.dart: No such file or directory
error: unable to stat just-written file packages/flutter_tools/test/asset_bundle_test.dart: No such file or directory
error: unable to stat just-written file packages/flutter_tools/test/asset_bundle_variant_test.dart: No such file or directory
error: unable to stat just-written file packages/flutter_tools/test/asset_test.dart: No such file or directory
warning: unable to unlink 'packages/flutter_tools/test/base': Directory not empty
fatal: cannot create directory at 'packages/flutter_tools/test/base': Directory not empty
  Command: git reset --hard v1.8.1
```
```
#0      runCheckedAsync (package:flutter_tools/src/base/process.dart:259:7)
<asynchronous suspension>
#1      UpgradeCommandRunner.resetChanges (package:flutter_tools/src/commands/upgrade.dart:135:39)
<asynchronous suspension>
#2      UpgradeCommandRunner.runCommand (package:flutter_tools/src/commands/upgrade.dart:86:11)
<asynchronous suspension>
#3      UpgradeCommand.runCommand (package:flutter_tools/src/commands/upgrade.dart:47:32)
<asynchronous suspension>
#4      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:477:18)
<asynchronous suspension>
#5      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:383:33)
<asynchronous suspension>
#6      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:154:29)
<asynchronous suspension>
#7      _rootRun (dart:async/zone.dart:1124:13)
#8      _CustomZone.run (dart:async/zone.dart:1021:19)
#9      _runZoned (dart:async/zone.dart:1516:10)
#10     runZoned (dart:async/zone.dart:1463:12)
#11     AppContext.run (package:flutter_tools/src/base/context.dart:153:18)
<asynchronous suspension>
#12     FlutterCommand.run (package:flutter_tools/src/runner/flutter_command.dart:375:20)
#13     CommandRunner.runCommand (package:args/command_runner.dart:197:27)
<asynchronous suspension>
#14     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:396:21)
<asynchronous suspension>
#15     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:154:29)
<asynchronous suspension>
#16     _rootRun (dart:async/zone.dart:1124:13)
#17     _CustomZone.run (dart:async/zone.dart:1021:19)
#18     _runZoned (dart:async/zone.dart:1516:10)
#19     runZoned (dart:async/zone.dart:1463:12)
#20     AppContext.run (package:flutter_tools/src/base/context.dart:153:18)
<asynchronous suspension>
#21     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:356:19)
<asynchronous suspension>
#22     CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:112:25)
#23     new Future.sync (dart:async/future.dart:224:31)
#24     CommandRunner.run (package:args/command_runner.dart:112:14)
#25     FlutterCommandRunner.run (package:flutter_tools/src/runner/flutter_command_runner.dart:242:18)
#26     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:62:22)
<asynchronous suspension>
#27     _rootRun (dart:async/zone.dart:1124:13)
#28     _CustomZone.run (dart:async/zone.dart:1021:19)
#29     _runZoned (dart:async/zone.dart:1516:10)
#30     runZoned (dart:async/zone.dart:1500:12)
#31     run.<anonymous closure> (package:flutter_tools/runner.dart:60:18)
<asynchronous suspension>
#32     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:154:29)
<asynchronous suspension>
#33     _rootRun (dart:async/zone.dart:1124:13)
#34     _CustomZone.run (dart:async/zone.dart:1021:19)
#35     _runZoned (dart:async/zone.dart:1516:10)
#36     runZoned (dart:async/zone.dart:1463:12)
#37     AppContext.run (package:flutter_tools/src/base/context.dart:153:18)
<asynchronous suspension>
#38     runInContext (package:flutter_tools/src/context_runner.dart:56:24)
<asynchronous suspension>
#39     run (package:flutter_tools/runner.dart:51:10)
#40     main (package:flutter_tools/executable.dart:62:9)
<asynchronous suspension>
#41     main (file:///E:/flutter/packages/flutter_tools/bin/flutter_tools.dart:8:3)
#42     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:303:32)
#43     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:12)
```

## flutter doctor

```
[32m[✓][39m Flutter (Channel master, v1.8.2-pre.181, on Microsoft Windows [Version 10.0.18362.239], locale zh-CN)
    [32m•[39m Flutter version 1.8.2-pre.181 at E:\flutter
    [32m•[39m Framework revision c15cfdd6af (6 hours ago), 2019-07-24 22:44:12 -0700
    [32m•[39m Engine revision 3c51a7bfff
    [32m•[39m Dart version 2.5.0 (build 2.5.0-dev.0.0 b5aeaa6796)

[33m[!][39m Android toolchain - develop for Android devices (Android SDK version 27.0.3)
    [32m•[39m Android SDK at E:\Android\Sdk
    [32m•[39m Android NDK location not configured (optional; useful for native profiling support)
    [31m✗[39m Flutter requires Android SDK 28 and the Android BuildTools 28.0.3
      To update using sdkmanager, run:
        "E:\Android\Sdk\tools\bin\sdkmanager" "platforms;android-28" "build-tools;28.0.3"
      or visit https://flutter.dev/setup/#android-setup for detailed instructions.
    [33m![39m Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses

[31m[✗][39m Chrome - develop for the web (Cannot find chrome executable at .\Google\Chrome\Application\chrome.exe)
    [33m![39m CHROME_EXECUTABLE not set

[32m[✓][39m Visual Studio - develop for Windows (Visual Studio Community 2019 16.1.6)
    [32m•[39m Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    [32m•[39m Visual Studio Community 2019 version 16.1.29102.190

[33m[!][39m Android Studio (not installed)
    [32m•[39m Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/setup/#android-setup for detailed instructions).

[32m[✓][39m Connected device (2 available)
    [32m•[39m Windows • Windows • windows-x64    • Microsoft Windows [Version 10.0.18362.239]
    [32m•[39m Chrome  • chrome  • web-javascript • unknown (unsupported)

[33m![39m Doctor found issues in 3 categories.
```

**Comment by BondarenkoStas** [comment]
@YeyuanLee did you manage to resolve the problem?

**Comment by iapicca** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!

Could everyone who still has this problem please file a new issue with the exact descriptions what happens, logs and the output of ' flutter doctor -v'  please.
All system setups can be slightly different so its always better to open new issues and reference related issues.
