### ISSUE TITLE
[webview_flutter] Trying to change state onPageFinished gives dirty state error

### ISSUE THREAD

**Issue by herrmartell** [flutter/flutter#36953]
## Steps to Reproduce
```dart
@override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        brightness: Brightness.light,
        iconTheme: IconThemeData(color: Colors.black),
        backgroundColor: Colors.white,
        actions: <Widget>[
          NavigationControls(_controller.future),
        ],
        leading: IconButton(
          icon: Icon(
            RefereeIcons.back,
            color: Colors.black,
            size: 22.0,
          ),
          onPressed: () => Navigator.of(context).pop(),
        ),
        automaticallyImplyLeading: false,
      ),
      body: Stack(
        children: <Widget>[
          Builder(
            builder: (BuildContext context) {
              return WebView(
                initialUrl: widget.initialUrl,
                javascriptMode: JavascriptMode.unrestricted,
                onWebViewCreated: (WebViewController webViewController) {
                  _controller.complete(webViewController);
                },
                onPageFinished: (url) {
                  setState(() {
                    isLoading = false;
                  });
                },
              );
            },
          ),
          isLoading
              ? SizedBox(
                  height: 2.0,
                  child: LinearProgressIndicator(
                    backgroundColor: Colors.purple,
                    valueColor: AlwaysStoppedAnimation<Color>(Colors.white),
                  ),
                )
              : null,
        ],
      ),
    );
  }
```

1.  Just try to change state on methods onPageFinished or onWebViewCreated

## Logs
```
I/flutter (16347): ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
I/flutter (16347): The following assertion was thrown building StatisticsPage(dirty, state:
I/flutter (16347): _StatisticsPageState#26b8f):
I/flutter (16347): Assertion failed
I/flutter (16347): 
I/flutter (16347): Either the assertion indicates an error in the framework itself, or we should provide substantially
I/flutter (16347): more information in this error message to help you determine and fix the underlying cause.
I/flutter (16347): In either case, please report this assertion by filing a bug on GitHub:
I/flutter (16347):   https://github.com/flutter/flutter/issues/new?template=BUG.md
I/flutter (16347): 
I/flutter (16347): When the exception was thrown, this was the stack:
I/flutter (16347): #0      new MultiChildRenderObjectWidget.<anonymous closure> (package:flutter/src/widgets/framework.dart:1691:11)
I/flutter (16347): #1      new MultiChildRenderObjectWidget (package:flutter/src/widgets/framework.dart:1696:8)
I/flutter (16347): #2      new Stack (package:flutter/src/widgets/basic.dart:3118:8)
I/flutter (16347): #3      _StatisticsPageState.build (package:refereepro_fans/pages/statistics_page.dart:51:13)
I/flutter (16347): #4      StatefulElement.build (package:flutter/src/widgets/framework.dart:4012:27)
I/flutter (16347): #5      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3924:15)
I/flutter (16347): #6      Element.rebuild (package:flutter/src/widgets/framework.dart:3721:5)
I/flutter (16347): #7      BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2340:33)
I/flutter (16347): #8      _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding&WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:700:20)
I/flutter (16347): #9      _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:285:5)
I/flutter (16347): #10     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1016:15)
I/flutter (16347): #11     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:958:9)
I/flutter (16347): #12     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:874:5)
I/flutter (16347): #16     _invoke (dart:ui/hooks.dart:236:10)
I/flutter (16347): #17     _drawFrame (dart:ui/hooks.dart:194:3)
I/flutter (16347): (elided 3 frames from package dart:async)
I/flutter (16347): ════════════════════════════════════════════════════════════════════════════════════════════════════
```

```
[✓] Flutter (Channel stable, v1.7.8+hotfix.4, on Mac OS X 10.14.6 18G84, locale en-MX)
    • Flutter version 1.7.8+hotfix.4 at /Users/herrmartell/Flutter
    • Framework revision 20e59316b8 (7 days ago), 2019-07-18 20:04:33 -0700
    • Engine revision fee001c93f
    • Dart version 2.4.0

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.1)
    • Android SDK at /Users/herrmartell/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.1
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 10.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.3, Build version 10G8
    • CocoaPods version 1.7.4

[!] iOS tools - develop for iOS devices
    ✗ Verify that all connected devices have been paired with this computer in Xcode.
      If all devices have been paired, libimobiledevice and ideviceinstaller may require updating.
      To update with Brew, run:
        brew update
        brew uninstall --ignore-dependencies libimobiledevice
        brew uninstall --ignore-dependencies usbmuxd
        brew install --HEAD usbmuxd
        brew unlink usbmuxd
        brew link usbmuxd
        brew install --HEAD libimobiledevice
        brew install ideviceinstaller
    • ios-deploy 1.9.4

[✓] Android Studio (version 3.4)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 37.1.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

[✓] Connected device (1 available)
    • SM A505G • R28M30ZYWMB • android-arm64 • Android 9 (API 28)

! Doctor found issues in 1 category.
```

**Comment by kf6gpe** [comment]
Touching for 2020 triage work. This may still be an issue in 1.12, but I'm not sure.

**Comment by darshankawar** [comment]
Hi @herrmartell,
I tried to replicate this issue on latest Flutter `dev channel (1.20.0-0.0.pre)` and with latest version of `webview_flutter`, but didn't see any error after changing state in `onPageFinished` method.

<details>
<summary>code sample</summary>

```
return Scaffold(
      appBar: AppBar(
        brightness: Brightness.light,
        iconTheme: IconThemeData(color: Colors.black),
        backgroundColor: Colors.white,
        leading: IconButton(
          icon: Icon(
            Icons.arrow_back,
            color: Colors.black,
            size: 22.0,
          ),
          onPressed: () => Navigator.of(context).pop(),
        ),
        automaticallyImplyLeading: false,
      ),
      body: Stack(
        children: <Widget>[
          Builder(
            builder: (BuildContext context) {
              return WebView(
                initialUrl: 'https://google.com',
                javascriptMode: JavascriptMode.unrestricted,
                onWebViewCreated: (WebViewController webViewController) {
                  _controller.complete(webViewController);
                },
                onPageFinished: (url) {
                  setState(() {
                    isLoading = true; // <- changed false to true
                  });
                },
              );
            },
          ),
          isLoading
              ? SizedBox(
            height: 2.0,
            child: LinearProgressIndicator(
              backgroundColor: Colors.purple,
              valueColor: AlwaysStoppedAnimation<Color>(Colors.white),
            ),
          )
              : Container(),
        ],
      )
      ,
    );
```

</details>

Can you please confirm if you still experience this issue on latest Flutter version and `webview_flutter` ?

**Comment by herrmartell** [comment]
I no longer experience this issue.

**Comment by darshankawar** [comment]
Hi @herrmartell, 
Given your last message I feel safe to close this issue.
if you disagree please write in the comments and I will reopen it. 
Thanks.
