### ISSUE TITLE
Firebase Performance: New HttpMetric on Android throws exception if Uri ends with ?

### ISSUE THREAD

**Issue by nishtahir** [flutter/flutter#36990]
This works on iOS without an issue but throws an exception on Android

```
FirebasePerformance.instance.newHttpMetric("http://google.com?", ...);
```

Android Stacktrace
```
E/MethodChannel#plugins.flutter.io/firebase_performance(12376): Failed to handle method call
E/MethodChannel#plugins.flutter.io/firebase_performance(12376): java.lang.StringIndexOutOfBoundsException: String index out of range: -1
E/MethodChannel#plugins.flutter.io/firebase_performance(12376): 	at java.lang.String.substring(String.java:1975)
E/MethodChannel#plugins.flutter.io/firebase_performance(12376): 	at com.google.android.gms.internal.firebase-perf.zzbk.zzn(Unknown Source:8)
E/MethodChannel#plugins.flutter.io/firebase_performance(12376): 	at com.google.android.gms.internal.firebase-perf.zzau.zza(Unknown Source:23)
E/MethodChannel#plugins.flutter.io/firebase_performance(12376): 	at com.google.firebase.perf.metrics.HttpMetric.<init>(Unknown Source:4)
E/MethodChannel#plugins.flutter.io/firebase_performance(12376): 	at com.google.firebase.perf.FirebasePerformance.newHttpMetric(Unknown Source:70)
E/MethodChannel#plugins.flutter.io/firebase_performance(12376): 	at io.flutter.plugins.firebaseperformance.FlutterFirebasePerformance.newHttpMetric(FlutterFirebasePerformance.java:100)
E/MethodChannel#plugins.flutter.io/firebase_performance(12376): 	at io.flutter.plugins.firebaseperformance.FlutterFirebasePerformance.onMethodCall(FlutterFirebasePerformance.java:65)
E/MethodChannel#plugins.flutter.io/firebase_performance(12376): 	at io.flutter.plugins.firebaseperformance.FirebasePerformancePlugin.onMethodCall(FirebasePerformancePlugin.java:32)
E/MethodChannel#plugins.flutter.io/firebase_performance(12376): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:222)
E/MethodChannel#plugins.flutter.io/firebase_performance(12376): 	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:96)
E/MethodChannel#plugins.flutter.io/firebase_performance(12376): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:643)
E/MethodChannel#plugins.flutter.io/firebase_performance(12376): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/MethodChannel#plugins.flutter.io/firebase_performance(12376): 	at android.os.MessageQueue.next(MessageQueue.java:325)
E/MethodChannel#plugins.flutter.io/firebase_performance(12376): 	at android.os.Looper.loop(Looper.java:142)
E/MethodChannel#plugins.flutter.io/firebase_performance(12376): 	at android.app.ActivityThread.main(ActivityThread.java:6494)
E/MethodChannel#plugins.flutter.io/firebase_performance(12376): 	at java.lang.reflect.Method.invoke(Native Method)
E/MethodChannel#plugins.flutter.io/firebase_performance(12376): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
E/MethodChannel#plugins.flutter.io/firebase_performance(12376): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
```

Flutter trace

```
E/flutter (12376): [ERROR:flutter/lib/ui/ui_dart_state.cc(148)] Unhandled Exception: PlatformException(error, String index out of range: -1, null)
E/flutter (12376): #0      StandardMethodCodec.decodeEnvelope 
package:flutter/…/services/message_codecs.dart:564
E/flutter (12376): #1      MethodChannel.invokeMethod 
package:flutter/…/services/platform_channel.dart:316
E/flutter (12376): <asynchronous suspension>
E/flutter (12376): #2      FirebasePerformance.newHttpMetric 
package:firebase_performance/src/firebase_performance.dart:76
E/flutter (12376): #3      _MetricHttpClient.send
```

Removing the trailing `?` fixes the issue
```
    var strUri = request.url.toString();
    strUri = strUri.endsWith("?") ? strUri.substring(0, strUri.length - 1): strUri;

    final HttpMetric metric = FirebasePerformance.instance.newHttpMetric(strUri, ...);
```

**Comment by kroikie** [comment]
@nishtahir

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/1136. Any further collaboration will be done there.
