### ISSUE TITLE
Assertion failed error

### ISSUE THREAD

**Issue by ThatsEli** [flutter/flutter#37136]
I have a problem with flutter and the error log suggest reporting this issue.

> I/flutter (20162): ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
I/flutter (20162): The following assertion was thrown building Post(dirty, state: _PostState#a2a2a):
I/flutter (20162): Assertion failed
I/flutter (20162):
I/flutter (20162): Either the assertion indicates an error in the framework itself, or we should provide substantially
I/flutter (20162): more information in this error message to help you determine and fix the underlying cause.
I/flutter (20162): In either case, please report this assertion by filing a bug on GitHub:
I/flutter (20162):   https://github.com/flutter/flutter/issues/new?template=BUG.md

Due to the project being larger than one file, I uploaded it on Github([here](https://github.com/ThatsEli/drawErrorExample)). Don't wonder about the name, I used this repo before for an issue with another project :)

## Steps to Reproduce

1. Run the App
2. Login/Authenticate with reddit
3. Scroll down 

## Logs

```
[+3607 ms] I/flutter (20752): ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
[  +14 ms] I/flutter (20752): The following assertion was thrown building Post(dirty, state: _PostState#34fc0):
[   +2 ms] I/flutter (20752): Assertion failed
[   +2 ms] I/flutter (20752):
[   +2 ms] I/flutter (20752): Either the assertion indicates an error in the framework itself, or we should provide substantially
[   +7 ms] I/flutter (20752): more information in this error message to help you determine and fix the underlying cause.
[   +4 ms] I/flutter (20752): In either case, please report this assertion by filing a bug on GitHub:
[   +2 ms] I/flutter (20752):   https://github.com/flutter/flutter/issues/new?template=BUG.md
[   +7 ms] I/flutter (20752):
[   +1 ms] I/flutter (20752): When the exception was thrown, this was the stack:
[   +2 ms] I/flutter (20752): #0      new MultiChildRenderObjectWidget.<anonymous closure>
(package:flutter/src/widgets/framework.dart:1691:11)
[  +10 ms] I/flutter (20752): #1      new MultiChildRenderObjectWidget (package:flutter/src/widgets/framework.dart:1696:8)
[   +2 ms] I/flutter (20752): #2      new Flex (package:flutter/src/widgets/basic.dart:3707:8)
[   +1 ms] I/flutter (20752): #3      new Column (package:flutter/src/widgets/basic.dart:4234:8)
[   +9 ms] I/flutter (20752): #4      _PostState.build (package:redditclient/widgets/post.dart:36:15)
[   +2 ms] I/flutter (20752): #5      StatefulElement.build (package:flutter/src/widgets/framework.dart:4012:27)
[   +1 ms] I/flutter (20752): #6      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3924:15)
[   +1 ms] I/flutter (20752): #7      Element.rebuild (package:flutter/src/widgets/framework.dart:3721:5)
[   +7 ms] I/flutter (20752): #8      ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3907:5)
[   +2 ms] I/flutter (20752): #9      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4053:11)
[   +2 ms] I/flutter (20752): #10     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3902:5)
[   +1 ms] I/flutter (20752): #11     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3084:14)
[   +8 ms] I/flutter (20752): #12     Element.updateChild (package:flutter/src/widgets/framework.dart:2887:12)
[   +2 ms] I/flutter (20752): #13     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5092:14)
[   +3 ms] I/flutter (20752): #14     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3084:14)
[  +16 ms] I/flutter (20752): #15     Element.updateChild (package:flutter/src/widgets/framework.dart:2887:12)
[   +2 ms] I/flutter (20752): #16     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5092:14)
[   +3 ms] I/flutter (20752): #17     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3084:14)
[   +2 ms] I/flutter (20752): #18     Element.updateChild (package:flutter/src/widgets/framework.dart:2887:12)
[   +7 ms] I/flutter (20752): #19     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3935:16)
[   +2 ms] I/flutter (20752): #20     Element.rebuild (package:flutter/src/widgets/framework.dart:3721:5)
[   +2 ms] I/flutter (20752): #21     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3907:5)
[   +9 ms] I/flutter (20752): #22     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3902:5)
[   +2 ms] I/flutter (20752): #23     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3084:14)
[   +2 ms] I/flutter (20752): #24     Element.updateChild (package:flutter/src/widgets/framework.dart:2887:12)
[   +2 ms] I/flutter (20752): #25     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3935:16)
[   +9 ms] I/flutter (20752): #26     Element.rebuild (package:flutter/src/widgets/framework.dart:3721:5)
[   +2 ms] I/flutter (20752): #27     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3907:5)
[   +1 ms] I/flutter (20752): #28     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3902:5)
[   +1 ms] I/flutter (20752): #29     ParentDataElement.mount (package:flutter/src/widgets/framework.dart:4279:11)
[   +8 ms] I/flutter (20752): #30     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3084:14)
[   +2 ms] I/flutter (20752): #31     Element.updateChild (package:flutter/src/widgets/framework.dart:2887:12)
[   +2 ms] I/flutter (20752): #32     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3935:16)
[   +2 ms] I/flutter (20752): #33     Element.rebuild (package:flutter/src/widgets/framework.dart:3721:5)
[   +7 ms] I/flutter (20752): #34     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3907:5)
[   +2 ms] I/flutter (20752): #35     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4053:11)
[   +2 ms] I/flutter (20752): #36     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3902:5)
[   +2 ms] I/flutter (20752): #37     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3084:14)
[   +9 ms] I/flutter (20752): #38     Element.updateChild (package:flutter/src/widgets/framework.dart:2887:12)
[   +3 ms] I/flutter (20752): #39     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3935:16)
[   +2 ms] I/flutter (20752): #40     Element.rebuild (package:flutter/src/widgets/framework.dart:3721:5)
[   +7 ms] I/flutter (20752): #41     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3907:5)
[   +1 ms] I/flutter (20752): #42     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3902:5)
[   +2 ms] I/flutter (20752): #43     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3084:14)
[   +2 ms] I/flutter (20752): #44     Element.updateChild (package:flutter/src/widgets/framework.dart:2887:12)
[   +8 ms] I/flutter (20752): #45     SliverMultiBoxAdaptorElement.updateChild (package:flutter/src/widgets/sliver.dart:1181:36)
[   +2 ms] I/flutter (20752): #46     SliverMultiBoxAdaptorElement.createChild.<anonymous closure>
(package:flutter/src/widgets/sliver.dart:1166:20)
[   +3 ms] I/flutter (20752): #47     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2320:19)
[   +8 ms] I/flutter (20752): #48     SliverMultiBoxAdaptorElement.createChild (package:flutter/src/widgets/sliver.dart:1159:11)
[   +2 ms] I/flutter (20752): #49     RenderSliverMultiBoxAdaptor._createOrObtainChild.<anonymous closure>
(package:flutter/src/rendering/sliver_multi_box_adaptor.dart:354:23)
[   +3 ms] I/flutter (20752): #50     RenderObject.invokeLayoutCallback.<anonymous closure>
(package:flutter/src/rendering/object.dart:1715:58)
[   +8 ms] I/flutter (20752): #51     PipelineOwner._enableMutationsToDirtySubtrees (package:flutter/src/rendering/object.dart:796:15)
[   +2 ms] I/flutter (20752): #52     RenderObject.invokeLayoutCallback (package:flutter/src/rendering/object.dart:1715:13)
[   +2 ms] I/flutter (20752): #53     RenderSliverMultiBoxAdaptor._createOrObtainChild
(package:flutter/src/rendering/sliver_multi_box_adaptor.dart:343:5)
[  +10 ms] I/flutter (20752): #54     RenderSliverMultiBoxAdaptor.insertAndLayoutChild
(package:flutter/src/rendering/sliver_multi_box_adaptor.dart:489:5)
[   +2 ms] I/flutter (20752): #55     RenderSliverList.performLayout.advance (package:flutter/src/rendering/sliver_list.dart:191:19)
[   +2 ms] I/flutter (20752): #56     RenderSliverList.performLayout (package:flutter/src/rendering/sliver_list.dart:234:19)
[   +2 ms] I/flutter (20752): #57     RenderObject.layout (package:flutter/src/rendering/object.dart:1619:7)
[   +9 ms] I/flutter (20752): #58     RenderSliverPadding.performLayout (package:flutter/src/rendering/sliver_padding.dart:181:11)
[   +2 ms] I/flutter (20752): #59     RenderObject.layout (package:flutter/src/rendering/object.dart:1619:7)
[   +2 ms] I/flutter (20752): #60     RenderViewportBase.layoutChildSequence (package:flutter/src/rendering/viewport.dart:406:13)
[   +9 ms] I/flutter (20752): #61     RenderViewport._attemptLayout (package:flutter/src/rendering/viewport.dart:1334:12)
[   +2 ms] I/flutter (20752): #62     RenderViewport.performLayout (package:flutter/src/rendering/viewport.dart:1252:20)
[   +1 ms] I/flutter (20752): #63     RenderObject._layoutWithoutResize (package:flutter/src/rendering/object.dart:1496:7)
[   +2 ms] I/flutter (20752): #64     PipelineOwner.flushLayout (package:flutter/src/rendering/object.dart:765:18)
[   +7 ms] I/flutter (20752): #65
_WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding.dra
wFrame (package:flutter/src/rendering/binding.dart:346:19)
[   +3 ms] I/flutter (20752): #66
_WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding&Wid
getsBinding.drawFrame (package:flutter/src/widgets/binding.dart:701:13)
[  +14 ms] I/flutter (20752): #67
_WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding._ha
ndlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:285:5)
[   +3 ms] I/flutter (20752): #68
_WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._invokeFrameCallback
(package:flutter/src/scheduler/binding.dart:1016:15)
[   +2 ms] I/flutter (20752): #69
_WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.handleDrawFrame
(package:flutter/src/scheduler/binding.dart:958:9)
[   +9 ms] I/flutter (20752): #70
_WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._handleDrawFrame
(package:flutter/src/scheduler/binding.dart:874:5)
[   +3 ms] I/flutter (20752): #74     _invoke (dart:ui/hooks.dart:236:10)
[   +1 ms] I/flutter (20752): #75     _drawFrame (dart:ui/hooks.dart:194:3)
[  +13 ms] I/flutter (20752): (elided 3 frames from package dart:async)
[   +3 ms] I/flutter (20752): ════════════════════════════════════════════════════════════════════════════════════════════════════
```

```
Analyzing redditclient...
No issues found! (ran in 3.5s)
```

```
[√] Flutter (Channel stable, v1.7.8+hotfix.4, on Microsoft Windows [Version 10.0.17134.885], locale de-DE)
    • Flutter version 1.7.8+hotfix.4 at C:\Users\Elias\Documents\develop\flutter
    • Framework revision 20e59316b8 (9 days ago), 2019-07-18 20:04:33 -0700
    • Engine revision fee001c93f
    • Dart version 2.4.0


[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at C:\Android\android-sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = C:\Android\android-sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
    • All Android licenses accepted.

[!] Android Studio (version 3.4)
    • Android Studio at C:\Program Files\Android\Android Studio
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

[√] VS Code (version 1.36.1)
    • VS Code at C:\Users\Elias\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.2.0

[√] Connected device (1 available)
    • ONEPLUS A5010 • 192.168.179.134:5556 • android-arm64 • Android 9 (API 28)

! Doctor found issues in 1 category.
```

**Comment by ThatsEli** [comment]
Okay, I found my error. I returned null instead of an Widget in the post.dart in my repo. But I think this error message could be more accurate(As stated in the error :) ). I will leave this issue open for a day or so and wait if you want to change the error message. If not, you can just close it or I will do it later on. :)
