### ISSUE TITLE
DefaultTabController crashes when created with zero tabs

### ISSUE THREAD

**Issue by matthew5025** [flutter/flutter#37139]
## Steps to Reproduce
Courtesy of @SayidHosseini, the sample code to reproduce the problem is located [here](https://gist.github.com/SayidHosseini/fb57979d442df109bd78d110a4574c3d).

It is related to https://github.com/flutter/flutter/issues/20292

The comment reporting the problem is https://github.com/flutter/flutter/issues/20292#issuecomment-510938804

1. Create a DefaultTabController with no tabs
2. It crashes

## Logs

`I/flutter (14434): ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
I/flutter (14434): The following assertion was thrown building MyApp(dirty, state: _MyAppState#650a5):
I/flutter (14434): 'package:flutter/src/material/tab_controller.dart': Failed assertion: line 316 pos 15: 'initialIndex
I/flutter (14434): >= 0 && initialIndex < length': is not true.
I/flutter (14434): 
I/flutter (14434): Either the assertion indicates an error in the framework itself, or we should provide substantially
I/flutter (14434): more information in this error message to help you determine and fix the underlying cause.
I/flutter (14434): In either case, please report this assertion by filing a bug on GitHub:
I/flutter (14434):   https://github.com/flutter/flutter/issues/new?template=BUG.md
I/flutter (14434): 
I/flutter (14434): When the exception was thrown, this was the stack:
I/flutter (14434): #2      new DefaultTabController (package:flutter/src/material/tab_controller.dart:316:15)
I/flutter (14434): #3      _MyAppState.build (package:flutter_app/main.dart:18:15)
I/flutter (14434): #4      StatefulElement.build (package:flutter/src/widgets/framework.dart:4021:27)
I/flutter (14434): #5      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3933:15)
I/flutter (14434): #6      Element.rebuild (package:flutter/src/widgets/framework.dart:3730:5)
I/flutter (14434): #7      ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3916:5)
I/flutter (14434): #8      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4062:11)
I/flutter (14434): #9      ComponentElement.mount (package:flutter/src/widgets/framework.dart:3911:5)
I/flutter (14434): #10     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3093:14)
I/flutter (14434): #11     Element.updateChild (package:flutter/src/widgets/framework.dart:2896:12)
I/flutter (14434): #12     RenderObjectToWidgetElement._rebuild (package:flutter/src/widgets/binding.dart:939:16)
I/flutter (14434): #13     RenderObjectToWidgetElement.mount (package:flutter/src/widgets/binding.dart:910:5)
I/flutter (14434): #14     RenderObjectToWidgetAdapter.attachToRenderTree.<anonymous closure> (package:flutter/src/widgets/binding.dart:856:17)
I/flutter (14434): #15     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2320:19)
I/flutter (14434): #16     RenderObjectToWidgetAdapter.attachToRenderTree (package:flutter/src/widgets/binding.dart:855:13)
I/flutter (14434): #17     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding&WidgetsBinding.attachRootWidget (package:flutter/src/widgets/binding.dart:736:7)
I/flutter (14434): #18     runApp (package:flutter/src/widgets/binding.dart:786:7)
I/flutter (14434): #19     main (package:flutter_app/main.dart:3:16)
I/flutter (14434): #20     _runMainZoned.<anonymous closure>.<anonymous closure> (dart:ui/hooks.dart:216:25)
I/flutter (14434): #25     _runMainZoned.<anonymous closure> (dart:ui/hooks.dart:208:5)
I/flutter (14434): #26     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:305:19)
I/flutter (14434): #27     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:12)
I/flutter (14434): (elided 6 frames from class _AssertionError and package dart:async)
I/flutter (14434): ════════════════════════════════════════════════════════════════════════════════════════════════════
`

**Comment by matthew5025** [comment]
Added PR https://github.com/flutter/flutter/pull/37140 to fix this simple issue.
