### ISSUE TITLE
Unable to show dialog from Cupertino App

### ISSUE THREAD

**Issue by VadimOsovsky** [flutter/flutter#37142]
Can't show CupertinoAlertDialog from CupertinoApp (apparently flutter is complaining about MaterialLocalizations). Changing the root from CupertinoApp to MaterialApp seems to work fine.

### main.dart
```
void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    if (Platform.isIOS) {
      return CupertinoApp(
        title: 'Flutter Demo',
        debugShowCheckedModeBanner: false,
        theme: CupertinoThemeData(
          primaryColor: CupertinoColors.activeGreen,
        ),
        home: TodosScreenIOS(),
      );
    } else {
      return MaterialApp(
        title: 'Flutter Demo',
        debugShowCheckedModeBanner: false,
        theme: ThemeData(
          primarySwatch: Colors.teal,
        ),
        home: MyHomePage(title: 'Flutter Demo Home Page'),
      );
    }
  }
}
```
### todos_screen_ios.dart
```
import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';
import 'package:flutter_bloc/flutter_bloc.dart';
import 'package:todo/dbs/todos_db/todo_item.dart';
import 'package:todo/todos/bloc.dart';

class TodosScreenIOS extends StatefulWidget {
  @override
  _TodosScreenIOSState createState() => _TodosScreenIOSState();
}

class _TodosScreenIOSState extends State<TodosScreenIOS> {
  TodosBloc _todosBloc = TodosBloc();

  Widget _buildAddTodoDialog(_) {
    return CupertinoAlertDialog(
      title: Text("Add To Do"),
      content: CupertinoTextField(
        autofocus: true,
      ),
      actions: <Widget>[
        CupertinoDialogAction(
          onPressed: () {}, child: Text("Add"), isDefaultAction: true,)
      ],
    );
  }

  Widget _buildTodoItem(BuildContext context, TodoItem todo) {
    return Padding(
      key: Key(todo.id.toString()),
      padding: const EdgeInsets.symmetric(horizontal: 24.0, vertical: 4.0),
      child: Row(
        mainAxisAlignment: MainAxisAlignment.spaceBetween,
        children: <Widget>[
          Text(todo.task),
          Switch.adaptive(
            value: todo.isDone,
            onChanged: (value) {
              UpdateTodo(todo.copyWith(isDone: !todo.isDone));
            },
          )
        ],
      ),
    );
  }

  @override
  Widget build(BuildContext context) {
    return CupertinoPageScaffold(
      child: CustomScrollView(slivers: <Widget>[
        CupertinoSliverNavigationBar(
          leading: GestureDetector(
            child: Column(
              mainAxisAlignment: MainAxisAlignment.center,
              children: <Widget>[
                Text(
                  "Settings",
                  style: TextStyle(color: CupertinoColors.activeGreen),
                )
              ],
            ),
            onTap: () {
              showDialog(context: context, builder: _buildAddTodoDialog);
            },
          ),
          middle: CupertinoSegmentedControl(
            onValueChanged: (int newValue) {},
            children: ({
              0: Padding(
                  padding: EdgeInsets.symmetric(horizontal: 5),
                  child: Text("All")),
              1: Padding(
                  padding: EdgeInsets.symmetric(horizontal: 5),
                  child: Text("To do")),
              2: Padding(
                  padding: EdgeInsets.symmetric(horizontal: 5),
                  child: Text("Done")),
            }),
          ),
          trailing: GestureDetector(
            child: Icon(
              CupertinoIcons.add_circled_solid,
              size: 35.0,
            ),
            onTap: () {
              showDialog(context: context, builder: _buildAddTodoDialog);
            },
          ),
          largeTitle: Text("To Do App"),
        ),
        BlocBuilder<TodosBloc, TodosState>(
            bloc: _todosBloc,
            builder: (BuildContext context, TodosState state) {
              print(state);
              if (state is TodosLoaded) {
                return SliverList(
                  delegate: SliverChildBuilderDelegate(
                        (BuildContext context, int index) {
                      return _buildTodoItem(
                          context, state.todos.elementAt(index));
                    },
                    childCount: state.todos.length,
                  ),
                );
              } else if (state is TodosNotLoaded) {
                return SliverFillRemaining(
                    child: Center(child: Text("Error loading todos")));
              } else {
                return SliverFillRemaining(child: CupertinoActivityIndicator());
              }
            })
      ]),
    );
  }

  @override
  void dispose() {
    _todosBloc.dispose();
    super.dispose();
  }
}

```
## Logs

```
flutter: ══╡ EXCEPTION CAUGHT BY GESTURE ╞═══════════════════════════════════════════════════════════════════
flutter: The following assertion was thrown while handling a gesture:
flutter: No MaterialLocalizations found.
flutter: TodosScreenIOS widgets require MaterialLocalizations to be provided by a Localizations widget
flutter: ancestor.
flutter: Localizations are used to generate many different messages, labels,and abbreviations which are used
flutter: by the material library.
flutter: To introduce a MaterialLocalizations, either use a  MaterialApp at the root of your application to
flutter: include them automatically, or add a Localization widget with a MaterialLocalizations delegate.
flutter: The specific widget that could not find a MaterialLocalizations ancestor was:
flutter:   TodosScreenIOS
flutter: The ancestors of this widget were:
flutter:   Semantics(container: false, properties: SemanticsProperties, label: null, value: null, hint: null,
flutter: hintOverrides: null)
flutter:   Builder
flutter:   RepaintBoundary-[GlobalKey#d81e7]
flutter:   IgnorePointer(ignoring: false)
flutter:   Stack(alignment: AlignmentDirectional.topStart, fit: passthrough, overflow: clip)
flutter:   _CupertinoBackGestureDetector<dynamic>
flutter:   DecoratedBox(bg: _CupertinoEdgeShadowDecoration(edgeGradient:
flutter: LinearGradient(AlignmentDirectional(0.9, 0.0), AlignmentDirectional.centerEnd, [Color(0x00000000),
flutter: Color(0x04000000), Color(0x12000000), Color(0x38000000)], [0.0, 0.3, 0.6, 1.0], TileMode.clamp)))
flutter:   DecoratedBoxTransition(animation: AnimationController#6ed96(⏭ 1.000; paused; for
flutter: CupertinoPageRoute<dynamic>(/))➩ProxyAnimation➩Cubic(0.35, 0.91, 0.33,
flutter: 0.97)➩DecorationTween(_CupertinoEdgeShadowDecoration(edgeGradient: null) →
flutter: _CupertinoEdgeShadowDecoration(edgeGradient: LinearGradient(AlignmentDirectional(0.9, 0.0),
flutter: AlignmentDirectional.centerEnd, [Color(0x00000000), Color(0x04000000), Color(0x12000000),
flutter: Color(0x38000000)], [0.0, 0.3, 0.6, 1.0],
flutter: TileMode.clamp)))➩_CupertinoEdgeShadowDecoration(edgeGradient:
flutter: LinearGradient(AlignmentDirectional(0.9, 0.0), AlignmentDirectional.centerEnd, [Color(0x00000000),
flutter: Color(0x04000000), Color(0x12000000), Color(0x38000000)], [0.0, 0.3, 0.6, 1.0], TileMode.clamp)))
flutter:   FractionalTranslation
flutter:   SlideTransition(animation: AnimationController#6ed96(⏭ 1.000; paused; for
flutter: CupertinoPageRoute<dynamic>(/))➩ProxyAnimation➩Cubic(0.35, 0.91, 0.33, 0.97)ₒₙ/Cubic(0.67, 0.03,
flutter: 0.65, 0.09)➩Tween<Offset>(Offset(1.0, 0.0) → Offset(0.0, 0.0))➩Offset(0.0, 0.0))
flutter:   FractionalTranslation
flutter:   SlideTransition(animation: kAlwaysDismissedAnimation➩ProxyAnimation➩ProxyAnimation➩Cubic(0.35,
flutter: 0.91, 0.33, 0.97)ₒₙ/Cubic(0.67, 0.03, 0.65, 0.09)➩Tween<Offset>(Offset(0.0, 0.0) → Offset(-0.3,
flutter: 0.0))➩Offset(0.0, 0.0))
flutter:   CupertinoPageTransition
flutter:   AnimatedBuilder(animation: Listenable.merge([AnimationController#6ed96(⏭ 1.000; paused; for
flutter: CupertinoPageRoute<dynamic>(/))➩ProxyAnimation,
flutter: kAlwaysDismissedAnimation➩ProxyAnimation➩ProxyAnimation]))
flutter:   RepaintBoundary
flutter:   _FocusMarker
flutter:   Semantics(container: false, properties: SemanticsProperties, label: null, value: null, hint: null,
flutter: hintOverrides: null)
flutter:   FocusScope(node: FocusScopeNode#163ee)
flutter:   PageStorage
flutter:   Offstage(offstage: false)
flutter:   _ModalScopeStatus(active)
flutter:   _ModalScope<dynamic>-[LabeledGlobalKey<_ModalScopeState<dynamic>>#8e1c3]
flutter:   _OverlayEntry-[LabeledGlobalKey<_OverlayEntryState>#ab15a]
flutter:   Stack(alignment: AlignmentDirectional.topStart, fit: expand, overflow: clip)
flutter:   _Theatre
flutter:   Overlay-[LabeledGlobalKey<OverlayState>#22d8a]
flutter:   _FocusMarker
flutter:   Semantics(container: false, properties: SemanticsProperties, label: null, value: null, hint: null,
flutter: hintOverrides: null)
flutter:   FocusScope(AUTOFOCUS, node: FocusScopeNode#44380)
flutter:   AbsorbPointer(absorbing: false)
flutter:   Listener(listeners: [down, up, cancel], behavior: deferToChild)
flutter:   Navigator-[GlobalObjectKey<NavigatorState> _WidgetsAppState#d8543]
flutter:   DefaultTextStyle(inherit: false, color: Color(0xff000000), family: .SF Pro Text, size: 17.0,
flutter: letterSpacing: -0.4, decoration: TextDecoration.none, softWrap: wrapping at box width, overflow:
flutter: clip)
flutter:   Title(title: "Flutter Demo", color: Color(0xff007aff))
flutter:   Directionality(textDirection: ltr)
flutter:   _LocalizationsScope-[GlobalKey#5a02a]
flutter:   Semantics(container: false, properties: SemanticsProperties, label: null, value: null, hint: null,
flutter: textDirection: ltr, hintOverrides: null)
flutter:   Localizations(locale: en_US, delegates: [DefaultCupertinoLocalizations.delegate(en_US),
flutter: DefaultWidgetsLocalizations.delegate(en_US)])
flutter:   MediaQuery(MediaQueryData(size: Size(414.0, 896.0), devicePixelRatio: 2.0, textScaleFactor: 1.0,
flutter: platformBrightness: Brightness.light, padding: EdgeInsets(0.0, 44.0, 0.0, 34.0), viewPadding:
flutter: EdgeInsets(0.0, 44.0, 0.0, 34.0), viewInsets: EdgeInsets.zero, alwaysUse24HourFormat: false,
flutter: accessibleNavigation: false, disableAnimations: false, invertColors: false, boldText: false))
flutter:   DefaultFocusTraversal
flutter:   WidgetsApp-[GlobalObjectKey _CupertinoAppState#4ae6e]
flutter:   IconTheme(IconThemeData#a13f5(color: Color(0xff4cd964)))
flutter:   _InheritedCupertinoTheme
flutter:   CupertinoTheme
flutter:   ScrollConfiguration(behavior: _AlwaysCupertinoScrollBehavior)
flutter:   CupertinoApp
flutter:   MyApp
flutter:   [root]
flutter:
flutter: When the exception was thrown, this was the stack:
flutter: #0      debugCheckHasMaterialLocalizations.<anonymous closure> (package:flutter/src/material/debug.dart:125:7)
flutter: #1      debugCheckHasMaterialLocalizations (package:flutter/src/material/debug.dart:128:4)
flutter: #2      showDialog (package:flutter/src/material/dialog.dart:702:10)
flutter: #3      _TodosScreenIOSState.build.<anonymous closure> (package:todo/todos/todos_screen_ios.dart:86:15)
flutter: #4      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:182:24)
flutter: #5      TapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:365:11)
flutter: #6      TapGestureRecognizer.acceptGesture (package:flutter/src/gestures/tap.dart:312:7)
flutter: #7      GestureArenaManager.sweep (package:flutter/src/gestures/arena.dart:156:27)
flutter: #8      _WidgetsFlutterBinding&BindingBase&GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:222:20)
flutter: #9      _WidgetsFlutterBinding&BindingBase&GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:198:22)
flutter: #10     _WidgetsFlutterBinding&BindingBase&GestureBinding._handlePointerEvent (package:flutter/src/gestures/binding.dart:156:7)
flutter: #11     _WidgetsFlutterBinding&BindingBase&GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:102:7)
flutter: #12     _WidgetsFlutterBinding&BindingBase&GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:86:7)
flutter: #16     _invoke1 (dart:ui/hooks.dart:250:10)
flutter: #17     _dispatchPointerDataPacket (dart:ui/hooks.dart:159:5)
flutter: (elided 3 frames from package dart:async)
flutter:
flutter: Handler: "onTap"
flutter: Recognizer:
flutter:   TapGestureRecognizer#6a6b4
flutter: ════════════════════════════════════════════════════════════════════════════════════════════════════
```

```
MacBook-Pro-Vadim:todo vadim$ flutter analyze
Analyzing todo...                                                       
No issues found! (ran in 5.4s)
```

```
[✓] Flutter (Channel stable, v1.7.8+hotfix.4, on Mac OS X 10.14.6 18G84, locale en-RU)
    • Flutter version 1.7.8+hotfix.4 at /Users/vadim/Documents/flutter
    • Framework revision 20e59316b8 (10 days ago), 2019-07-18 20:04:33 -0700
    • Engine revision fee001c93f
    • Dart version 2.4.0

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.0)
    • Android SDK at /Users/vadim/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.0
    • ANDROID_HOME = /Users/vadim/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 10.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.3, Build version 10G8
    • CocoaPods version 1.7.5

[✓] iOS tools - develop for iOS devices
    • ios-deploy 1.9.4

[!] Android Studio (version 3.4)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

[✓] IntelliJ IDEA Community Edition (version 2019.1.3)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 37.1.3
    • Dart plugin version 191.7830

[✓] VS Code (version 1.36.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.2.0

[✓] Connected device (1 available)
    • iPhone Xʀ • 86BA0C86-5BB6-4B4C-830E-D20DEF68924F • ios • com.apple.CoreSimulator.SimRuntime.iOS-12-4 (simulator)

! Doctor found issues in 1 category.

```

**Comment by LongCatIsLooong** [comment]
[`showDialog`](https://api.flutter.dev/flutter/material/showDialog.html) (in your `onTap` callback) shows the material dialog.
