### ISSUE TITLE
Bad state: Future already completed calling for unknown reason

### ISSUE THREAD

**Issue by ConProgramming** [flutter/flutter#37201]
I get this error sometimes in my app, but I'm unsure of its origin because this is all it provides me with 

```
I/flutter (10601): #0      _AsyncCompleter.complete (dart:async/future_impl.dart:39:31)
I/flutter (10601): #1      Route.didComplete (package:flutter/src/widgets/navigator.dart:189:19)
I/flutter (10601): #2      NavigatorState.pushReplacement.<anonymous closure> (package:flutter/src/widgets/navigator.dart:1846:13)
I/flutter (10601): #3      TickerFuture.whenCompleteOrCancel.thunk (package:flutter/src/scheduler/ticker.dart:389:15)
I/flutter (10601): #4      _rootRunUnary (dart:async/zone.dart:1132:38)
I/flutter (10601): #5      _CustomZone.runUnary (dart:async/zone.dart:1029:19)
I/flutter (10601): #6      _FutureListener.handleValue (dart:async/future_impl.dart:126:18)
I/flutter (10601): #7      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:639:45)
I/flutter (10601): #8      Future._propagateToListeners (dart:async/future_impl.dart:668:32)
I/flutter (10601): #9      Future._completeWithValue (dart:async/future_impl.dart:483:5)
I/flutter (10601): #10     Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:513:7)
I/flutter (10601): #11     _rootRun (dart:async/zone.dart:1124:13)
I/flutter (10601): #12     _CustomZone.run (dart:async/zone.dart:1021:19)
I/flutter (10601): #13     _CustomZone.runGuarded (dart:async/zone.dart
I/flutter (10601): Caught error: Bad state: Future already completed
```

I'm unsure why this was happening mostly because the logging is inadequate

My `flutter doctor -v`

```
[✓] Flutter (Channel stable, v1.7.8+hotfix.4, on Mac OS X 10.14 18A391, locale en-US)
    • Flutter version 1.7.8+hotfix.4 at /Users/conneraldrich/flutter
    • Framework revision 20e59316b8 (11 days ago), 2019-07-18 20:04:33 -0700
    • Engine revision fee001c93f
    • Dart version 2.4.0

 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/conneraldrich/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 9.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 9.4.1, Build version 9F2000
    • CocoaPods version 1.6.1

[✓] iOS tools - develop for iOS devices
    • ios-deploy 1.9.4

[✓] Android Studio (version 3.4)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 37.1.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

[✓] VS Code (version 1.36.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.2.0

[✓] Connected device (1 available)
    • SM G892U • 988a1b3841504a3149 • android-arm64 • Android 8.0.0 (API 26)

• No issues found!
```

**Comment by escamoteur** [comment]
please ask such question son stackoverflow, thanks
