### ISSUE TITLE
Throw a tool exit when gradle wrapper fails to download gradle

### ISSUE THREAD

**Issue by zanderso** [flutter/flutter#37249]
```shell
ProcessException: Process "...\gradlew.bat" exited abnormally:
Downloading https://services.gradle.org/distributions/gradle-4.1.1-all.zip


Exception in thread "main" java.io.FileNotFoundException: https://downloads.gradle.org/distributions/gradle-4.1.1-all.zip
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1872)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1474)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:254)
	at org.gradle.wrapper.Download.downloadInternal(Download.java:58)
	at org.gradle.wrapper.Download.download(Download.java:44)
	at org.gradle.wrapper.Install$1.call(Install.java:61)
	at org.gradle.wrapper.Install$1.call(Install.java:48)
	at org.gradle.wrapper.ExclusiveFileAccessManager.access(ExclusiveFileAccessManager.java:65)
	at org.gradle.wrapper.Install.createDist(Install.java:48)
	at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:128)
	at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:61)
```

**Comment by zanderso** [comment]
Possibly related: https://github.com/flutter/flutter/issues/36353

**Comment by passsy** [comment]
Fixed by https://github.com/flutter/flutter/pull/37526 isn't it?

**Comment by christopherfujino** [comment]
@passsy thanks for catching that :)
