### ISSUE TITLE
How to replay a finished video from Video playeur package ?

### ISSUE THREAD

**Issue by nitneuq33** [flutter/flutter#37252]
Hello I try the video playeur plugin but when the video is finish and I repress play and apply _controller.play()  the video can't play anymore. I observed that to relaunch video, I need to recall _controller.initialized but after some replay the app crash. Are there a simple solution to juste replay finised video after press on _controller.play()  ? 

```
I/ACoI/ExoPlayerImpl(27679): Init f25c7c7 [ExoPlayerLib/2.9.6] [herolte, SM-G930F, samsung, 26]
V/Surface (27679): sf_framedrop debug : 0x4f4c, game : false, logging : 0
I/ACodec  (27679):  [] Now uninitialized
I/ACodec  (27679): [] onAllocateComponent
I/OMXClient(27679): Treble IOmx obtained
I/ACodec  (27679): [OMX.Exynos.avc.dec] Now Loaded
V/Surface (27679): sf_framedrop debug : 0x4f4c, game : false, logging : 0
D/SurfaceUtils(27679): connecting to surface 0x75a26db010, reason connectToSurface
I/MediaCodec(27679): [OMX.Exynos.avc.dec] setting surface generation to 28343308
D/SurfaceUtils(27679): disconnecting from surface 0x75a26db010, reason connectToSurface(reconnect)
D/SurfaceUtils(27679): connecting to surface 0x75a26db010, reason connectToSurface(reconnect)
I/MediaCodec(27679): failed to configure codec bacause of codec capacity
E/MediaCodec(27679): Codec reported err 0xffffec77, actionCode 0, while in state 3
D/SurfaceUtils(27679): disconnecting from surface 0x75a26db010, reason disconnectFromSurface
E/MediaCodec(27679): configure failed with err 0xffffec77, resetting...
I/ACodec  (27679):  [OMX.Exynos.avc.dec] Now uninitialized
I/ACodec  (27679):  [] Now kWhatShutdownCompleted event : 8483
I/MediaCodec(27679): Codec shutdown complete
I/ACodec  (27679):  [] Now uninitialized
I/ACodec  (27679): [] onAllocateComponent
I/OMXClient(27679): Treble IOmx obtained
I/ACodec  (27679): [OMX.Exynos.avc.dec] Now Loaded
I/ACodec  (27679):  [OMX.Exynos.avc.dec] Now uninitialized
I/ACodec  (27679):  [] Now kWhatShutdownCompleted event : 8483
I/MediaCodec(27679): Codec shutdown complete
W/MediaCodecRenderer(27679): Failed to initialize decoder: OMX.Exynos.avc.dec
W/MediaCodecRenderer(27679): android.media.MediaCodec$CodecException: Error 0xffffec77
W/MediaCodecRenderer(27679): 	at android.media.MediaCodec.native_configure(Native Method)
W/MediaCodecRenderer(27679): 	at android.media.MediaCodec.configure(MediaCodec.java:1935)
W/MediaCodecRenderer(27679): 	at android.media.MediaCodec.configure(MediaCodec.java:1864)
W/MediaCodecRenderer(27679): 	at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.configureCodec(MediaCodecVideoRenderer.java:483)
W/MediaCodecRenderer(27679): 	at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.initCodec(MediaCodecRenderer.java:805)
W/MediaCodecRenderer(27679): 	at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.initCodecWithFallback(MediaCodecRenderer.java:745)
W/MediaCodecRenderer(27679): 	at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.maybeInitCodec(MediaCodecRenderer.java:474)
W/MediaCodecRenderer(27679): 	at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.reinitializeCodec(MediaCodecRenderer.java:1261)
W/MediaCodecRenderer(27679): 	at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.onInputFormatChanged(MediaCodecRenderer.java:1111)
W/MediaCodecRenderer(27679): 	at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.onInputFormatChanged(MediaCodecVideoRenderer.java:552)
W/MediaCodecRenderer(27679): 	at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:647)
W/MediaCodecRenderer(27679): 	at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:529)
W/MediaCodecRenderer(27679): 	at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:300)
W/MediaCodecRenderer(27679): 	at android.os.Handler.dispatchMessage(Handler.java:101)
W/MediaCodecRenderer(27679): 	at android.os.Looper.loop(Looper.java:164)
W/MediaCodecRenderer(27679): 	at android.os.HandlerThread.run(HandlerThread.java:65)
E/ExoPlayerImplInternal(27679): Playback error.
E/ExoPlayerImplInternal(27679): com.google.android.exoplayer2.ExoPlaybackException: com.google.android.exoplayer2.mediacodec.MediaCodecRenderer$DecoderInitializationException: Decoder init failed: OMX.Exynos.avc.dec, Format(1, null, null, video/avc, null, -1, null, [1440, 1080, -1.0], [-1, -1])
E/ExoPlayerImplInternal(27679): 	at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.maybeInitCodec(MediaCodecRenderer.java:479)
E/ExoPlayerImplInternal(27679): 	at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.reinitializeCodec(MediaCodecRenderer.java:1261)
E/ExoPlayerImplInternal(27679): 	at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.onInputFormatChanged(MediaCodecRenderer.java:1111)
E/ExoPlayerImplInternal(27679): 	at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.onInputFormatChanged(MediaCodecVideoRenderer.java:552)
E/ExoPlayerImplInternal(27679): 	at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:647)
E/ExoPlayerImplInternal(27679): 	at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:529)
E/ExoPlayerImplInternal(27679): 	at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:300)
E/ExoPlayerImplInternal(27679): 	at android.os.Handler.dispatchMessage(Handler.java:101)
E/ExoPlayerImplInternal(27679): 	at android.os.Looper.loop(Looper.java:164)
E/ExoPlayerImplInternal(27679): 	at android.os.HandlerThread.run(HandlerThread.java:65)
E/ExoPlayerImplInternal(27679): Caused by: com.google.android.exoplayer2.mediacodec.MediaCodecRenderer$DecoderInitializationException: Decoder init failed: OMX.Exynos.avc.dec, Format(1, null, null, video/avc, null, -1, null, [1440, 1080, -1.0], [-1, -1])
E/ExoPlayerImplInternal(27679): 	at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.initCodecWithFallback(MediaCodecRenderer.java:753)
E/ExoPlayerImplInternal(27679): 	at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.maybeInitCodec(MediaCodecRenderer.java:474)
E/ExoPlayerImplInternal(27679): 	... 9 more
E/ExoPlayerImplInternal(27679): Caused by: android.media.MediaCodec$CodecException: Error 0xffffec77
E/ExoPlayerImplInternal(27679): 	at android.media.MediaCodec.native_configure(Native Method)
E/ExoPlayerImplInternal(27679): 	at android.media.MediaCodec.configure(MediaCodec.java:1935)
E/ExoPlayerImplInternal(27679): 	at android.media.MediaCodec.configure(MediaCodec.java:1864)
E/ExoPlayerImplInternal(27679): 	at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.configureCodec(MediaCodecVideoRenderer.java:483)
E/ExoPlayerImplInternal(27679): 	at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.initCodec(MediaCodecRenderer.java:805)
E/ExoPlayerImplInternal(27679): 	at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.initCodecWithFallback(MediaCodecRenderer.java:745)
E/ExoPlayerImplInternal(27679): 	... 10 more

**Comment by BondarenkoStas** [comment]
@nitneuq33 Please provide your ```flutter doctor -v``` and if possible some code example that reproduces the issue.

**Comment by iapicca** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!

Could everyone who still has this problem please file a new issue with the exact descriptions what happens, logs and the output of ' flutter doctor -v'  please.
All system setups can be slightly different so its always better to open new issues and reference related issues.
