### ISSUE TITLE
webview_flutter

### ISSUE THREAD

**Issue by mimicode** [flutter/flutter#37289]
```
W/PlatformViewsController(29433): Creating a virtual display of size: [1080, 11562] may result in problems(https://github.com/flutter/flutter/issues/2897).It is larger than the device screen size: [1080, 1920].
W/ContentCatcher(29433): Failed to notify a WebView
E/WindowManager(29433): BadTokenException or InvalidDisplayException, clean up.
E/MethodChannel#flutter/platform_views(29433): Failed to handle method call
E/MethodChannel#flutter/platform_views(29433): java.lang.RuntimeException: Adding window failed
E/MethodChannel#flutter/platform_views(29433): 	at android.view.ViewRootImpl.setView(ViewRootImpl.java:802)
E/MethodChannel#flutter/platform_views(29433): 	at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:356)
E/MethodChannel#flutter/platform_views(29433): 	at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:94)
E/MethodChannel#flutter/platform_views(29433): 	at android.app.Dialog.show(Dialog.java:329)
E/MethodChannel#flutter/platform_views(29433): 	at android.app.Presentation.show(Presentation.java:249)
E/MethodChannel#flutter/platform_views(29433): 	at io.flutter.plugin.platform.VirtualDisplayController.resize(VirtualDisplayController.java:149)
E/MethodChannel#flutter/platform_views(29433): 	at io.flutter.plugin.platform.PlatformViewsController$1.resizePlatformView(PlatformViewsController.java:165)
E/MethodChannel#flutter/platform_views(29433): 	at io.flutter.embedding.engine.systemchannels.PlatformViewsChannel$1.resize(PlatformViewsChannel.java:120)
E/MethodChannel#flutter/platform_views(29433): 	at io.flutter.embedding.engine.systemchannels.PlatformViewsChannel$1.onMethodCall(PlatformViewsChannel.java:57)
E/MethodChannel#flutter/platform_views(29433): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:222)
E/MethodChannel#flutter/platform_views(29433): 	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:96)
E/MethodChannel#flutter/platform_views(29433): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:643)
E/MethodChannel#flutter/platform_views(29433): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/MethodChannel#flutter/platform_views(29433): 	at android.os.MessageQueue.next(MessageQueue.java:332)
E/MethodChannel#flutter/platform_views(29433): 	at android.os.Looper.loop(Looper.java:168)
E/MethodChannel#flutter/platform_views(29433): 	at android.app.ActivityThread.main(ActivityThread.java:6867)
E/MethodChannel#flutter/platform_views(29433): 	at java.lang.reflect.Method.invoke(Native Method)
E/MethodChannel#flutter/platform_views(29433): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
E/MethodChannel#flutter/platform_views(29433): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:876)
E/MethodChannel#flutter/platform_views(29433): Caused by: android.os.DeadObjectException
E/MethodChannel#flutter/platform_views(29433): 	at android.os.BinderProxy.transactNative(Native Method)
E/MethodChannel#flutter/platform_views(29433): 	at android.os.BinderProxy.transact(BinderProxy.java:479)
E/MethodChannel#flutter/platform_views(29433): 	at android.view.IWindowSession$Stub$Proxy.addToDisplay(IWindowSession.java:835)
E/MethodChannel#flutter/platform_views(29433): 	at android.view.ViewRootImpl.setView(ViewRootImpl.java:790)
E/MethodChannel#flutter/platform_views(29433): 	... 18 more
D/AndroidRuntime(29433): Shutting down VM
E/AndroidRuntime(29433): FATAL EXCEPTION: main
E/AndroidRuntime(29433): Process: com.example.ffxapp, PID: 29433
E/AndroidRuntime(29433): DeadSystemException: The system died; earlier logs will point to the root cause
I/flutter (29433): 错误日志输出：══╡ EXCEPTION CAUGHT BY FLUTTER FRAMEWORK ╞══════════════════════
I/flutter (29433): The following PlatformException was thrown:
I/flutter (29433): PlatformException(error, Adding window failed, null)
I/flutter (29433): 
I/flutter (29433): When the exception was thrown, this was the stack:
I/flutter (29433): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:564:7)
I/flutter (29433): #1      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:316:33)
I/flutter (29433): <asynchronous suspension>
I/flutter (29433): #2      AndroidViewController.setSize (package:flutter/src/services/platform_views.dart:558:41)
I/flutter (29433): <asynchronous suspension>
I/flutter (29433): #3      RenderAndroidView._sizePlatformView (package:flutter/src/rendering/platform_view.dart:189:29)
I/flutter (29433): <asynchronous suspension>
I/flutter (29433): #4      RenderAndroidView.performResize (package:flutter/src/rendering/platform_view.dart:170:5)
I/flutter (29433): #5      RenderObject.layout (package:flutter/src/rendering/object.dart:1604:9)
I/flutter (29433): #6      _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.perform
W/System.err(29433): java.lang.RuntimeException: android.os.DeadSystemException
W/System.err(29433): 	at android.net.ConnectivityManager.getActiveNetworkInfo(ConnectivityManager.java:894)
W/System.err(29433): 	at cn.jiguang.g.a.e(Unknown Source:10)
W/System.err(29433): 	at cn.jiguang.a.a.c.e.a(Unknown Source:107)
W/System.err(29433): 	at cn.jiguang.a.a.c.e.a(Unknown Source:32)
W/System.err(29433): 	at cn.jiguang.a.a.c.e.uncaughtException(Unknown Source:13)
W/System.err(29433): 	at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1068)
W/System.err(29433): 	at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1063)
W/System.err(29433): 	at java.lang.Thread.dispatchUncaughtException(Thread.java:1955)
W/System.err(29433): Caused by: android.os.DeadSystemException
W/System.err(29433): 	... 8 more
W/System.err(29433): java.lang.RuntimeException: android.os.DeadSystemException
W/System.err(29433): 	at android.net.ConnectivityManager.getActiveNetworkInfo(ConnectivityManager.java:894)
W/System.err(29433): 	at cn.jiguang.g.a.e(Unknown Source:10)
W/System.err(29433): 	at cn.jiguang.a.a.c.e.c(Unknown Source:20)
W/System.err(29433): 	at cn.jiguang.a.a.c.e.a(Unknown Source:0)
W/System.err(29433): 	at cn.jiguang.a.a.c.f.run(Unknown Source:10)
W/System.err(29433): Caused by: android.os.DeadSystemException
W/System.err(29433): 	... 5 more
W/System.err(29433): java.lang.RuntimeException: android.os.DeadSystemException
Lost connection to device.
```

**Comment by miyoyo** [comment]
Are you trying to spawn a webview in a scrollable?

**Comment by check0927** [comment]
I also want to know the answer.

**Comment by BondarenkoStas** [comment]
@mimicode Please provide more information, what you tried to archive? Is the issue still relevant? It's not unexpected that the system died while trying to run a display with 11562px width.

**Comment by qq326646683** [comment]
same issue
<img width="849" alt="android_crash2" src="https://user-images.githubusercontent.com/15717688/67459771-e5de5e80-f66b-11e9-8a63-e355c2ae7b7d.png">

**Comment by BondarenkoStas** [comment]
@qq326646683 Can you paste the full exception? And describe steps how to reproduce it

**Comment by kf6gpe** [comment]
Closing this bug as it looks stale and unactionable. If you like, @qq326646683 and @mimicode, can you please re-open with the output of `flutter doctor`, the version of the webview plugin you're using from your `pubspec.yaml`, and a small reproducible case? Thanks!

**Comment by krishnaSoni2113** [comment]
> Are you trying to spawn a webview in a scrollable?
@miyoyo I am also facing the same issue and Yes, I am using the Webview as a child of the ScrollView.
Do you have any solution of this crash?
Thanks.

**Comment by miyoyo** [comment]
Webviews will always require a set size that's not obscenely big. Being in a scrollable will automatically give it infinite height, which crashes the webview.
