### ISSUE TITLE
shared_preferences: Failed to handle method call

### ISSUE THREAD

**Issue by sterrenburg** [flutter/flutter#37296]
When calling `setString` or another `set` method on an instantiated `SharedPreferences` instance, I receive the following error: `Failed to handle method call`.

I have tried to assert that the instance is instantiated, then call the following:

```
await _preferences.setString('key', 'value');
```

I expect the method call to return a Future which returns true.

This issue occurs on both physical devices and emulators.

This is the stack trace:

```
E/MethodChannel#plugins.flutter.io/shared_preferences(17960): Failed to handle method call
E/MethodChannel#plugins.flutter.io/shared_preferences(17960): java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.String.startsWith(java.lang.String)' on a null object reference
E/MethodChannel#plugins.flutter.io/shared_preferences(17960): 	at io.flutter.plugins.sharedpreferences.SharedPreferencesPlugin.onMethodCall(SharedPreferencesPlugin.java:163)
E/MethodChannel#plugins.flutter.io/shared_preferences(17960): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:222)
E/MethodChannel#plugins.flutter.io/shared_preferences(17960): 	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:96)
E/MethodChannel#plugins.flutter.io/shared_preferences(17960): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:644)
E/MethodChannel#plugins.flutter.io/shared_preferences(17960): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/MethodChannel#plugins.flutter.io/shared_preferences(17960): 	at android.os.MessageQueue.next(MessageQueue.java:326)
E/MethodChannel#plugins.flutter.io/shared_preferences(17960): 	at android.os.Looper.loop(Looper.java:160)
E/MethodChannel#plugins.flutter.io/shared_preferences(17960): 	at android.app.ActivityThread.main(ActivityThread.java:7029)
E/MethodChannel#plugins.flutter.io/shared_preferences(17960): 	at java.lang.reflect.Method.invoke(Native Method)
E/MethodChannel#plugins.flutter.io/shared_preferences(17960): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:537)
E/MethodChannel#plugins.flutter.io/shared_preferences(17960): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
I/flutter (17960): 2019-07-31T12:19:34.891151	I	LocalStorage:	 set key: pihole_user_flutterhole_port value: 80
I/flutter (17960): 2019-07-31T12:19:34.891563	I	LocalStorage:	 set key: pihole_user_flutterhole_auth value: 
E/MethodChannel#plugins.flutter.io/shared_preferences(17960): Failed to handle method call
E/MethodChannel#plugins.flutter.io/shared_preferences(17960): java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.String.startsWith(java.lang.String)' on a null object reference
E/MethodChannel#plugins.flutter.io/shared_preferences(17960): 	at io.flutter.plugins.sharedpreferences.SharedPreferencesPlugin.onMethodCall(SharedPreferencesPlugin.java:163)
E/MethodChannel#plugins.flutter.io/shared_preferences(17960): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:222)
E/MethodChannel#plugins.flutter.io/shared_preferences(17960): 	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:96)
E/MethodChannel#plugins.flutter.io/shared_preferences(17960): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:644)
E/MethodChannel#plugins.flutter.io/shared_preferences(17960): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/MethodChannel#plugins.flutter.io/shared_preferences(17960): 	at android.os.MessageQueue.next(MessageQueue.java:326)
E/MethodChannel#plugins.flutter.io/shared_preferences(17960): 	at android.os.Looper.loop(Looper.java:160)
E/MethodChannel#plugins.flutter.io/shared_preferences(17960): 	at android.app.ActivityThread.main(ActivityThread.java:7029)
E/MethodChannel#plugins.flutter.io/shared_preferences(17960): 	at java.lang.reflect.Method.invoke(Native Method)
E/MethodChannel#plugins.flutter.io/shared_preferences(17960): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:537)
E/MethodChannel#plugins.flutter.io/shared_preferences(17960): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
I/flutter (17960): 2019-07-31T12:19:34.892007	I	LocalStorage:	 set key: pihole_user_flutterhole_allowselfsigned value: false
I/flutter (17960): 2019-07-31T12:19:34.892404	I	LocalStorage:	 set key: pihole_user_flutterhole_proxy_host value: 
E/MethodChannel#plugins.flutter.io/shared_preferences(17960): Failed to handle method call
E/MethodChannel#plugins.flutter.io/shared_preferences(17960): java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.String.startsWith(java.lang.String)' on a null object reference
E/MethodChannel#plugins.flutter.io/shared_preferences(17960): 	at io.flutter.plugins.sharedpreferences.SharedPreferencesPlugin.onMethodCall(SharedPreferencesPlugin.java:163)
E/MethodChannel#plugins.flutter.io/shared_preferences(17960): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:222)
E/MethodChannel#plugins.flutter.io/shared_preferences(17960): 	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:96)
E/MethodChannel#plugins.flutter.io/shared_preferences(17960): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:644)
E/MethodChannel#plugins.flutter.io/shared_preferences(17960): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/MethodChannel#plugins.flutter.io/shared_preferences(17960): 	at android.os.MessageQueue.next(MessageQueue.java:326)
E/MethodChannel#plugins.flutter.io/shared_preferences(17960): 	at android.os.Looper.loop(Looper.java:160)
E/MethodChannel#plugins.flutter.io/shared_preferences(17960): 	at android.app.ActivityThread.main(ActivityThread.java:7029)
E/MethodChannel#plugins.flutter.io/shared_preferences(17960): 	at java.lang.reflect.Method.invoke(Native Method)
E/MethodChannel#plugins.flutter.io/shared_preferences(17960): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:537)
E/MethodChannel#plugins.flutter.io/shared_preferences(17960): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
I/flutter (17960): 2019-07-31T12:19:34.892863	I	LocalStorage:	 set key: pihole_user_flutterhole_proxy_username value: 
E/MethodChannel#plugins.flutter.io/shared_preferences(17960): Failed to handle method call
E/MethodChannel#plugins.flutter.io/shared_preferences(17960): java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.String.startsWith(java.lang.String)' on a null object reference
E/MethodChannel#plugins.flutter.io/shared_preferences(17960): 	at io.flutter.plugins.sharedpreferences.SharedPreferencesPlugin.onMethodCall(SharedPreferencesPlugin.java:163)
E/MethodChannel#plugins.flutter.io/shared_preferences(17960): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:222)
E/MethodChannel#plugins.flutter.io/shared_preferences(17960): 	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:96)
E/MethodChannel#plugins.flutter.io/shared_preferences(17960): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:644)
E/MethodChannel#plugins.flutter.io/shared_preferences(17960): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/MethodChannel#plugins.flutter.io/shared_preferences(17960): 	at android.os.MessageQueue.next(MessageQueue.java:326)
E/MethodChannel#plugins.flutter.io/shared_preferences(17960): 	at android.os.Looper.loop(Looper.java:160)
E/MethodChannel#plugins.flutter.io/shared_preferences(17960): 	at android.app.ActivityThread.main(ActivityThread.java:7029)
E/MethodChannel#plugins.flutter.io/shared_preferences(17960): 	at java.lang.reflect.Method.invoke(Native Method)
E/MethodChannel#plugins.flutter.io/shared_preferences(17960): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:537)
E/MethodChannel#plugins.flutter.io/shared_preferences(17960): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
I/flutter (17960): 2019-07-31T12:19:34.893263	I	LocalStorage:	 set key: pihole_user_flutterhole_proxy_password value: 
E/MethodChannel#plugins.flutter.io/shared_preferences(17960): Failed to handle method call
E/MethodChannel#plugins.flutter.io/shared_preferences(17960): java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.String.startsWith(java.lang.String)' on a null object reference
E/MethodChannel#plugins.flutter.io/shared_preferences(17960): 	at io.flutter.plugins.sharedpreferences.SharedPreferencesPlugin.onMethodCall(SharedPreferencesPlugin.java:163)
E/MethodChannel#plugins.flutter.io/shared_preferences(17960): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:222)
E/MethodChannel#plugins.flutter.io/shared_preferences(17960): 	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:96)
E/MethodChannel#plugins.flutter.io/shared_preferences(17960): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:644)
E/MethodChannel#plugins.flutter.io/shared_preferences(17960): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/MethodChannel#plugins.flutter.io/shared_preferences(17960): 	at android.os.MessageQueue.next(MessageQueue.java:326)
E/MethodChannel#plugins.flutter.io/shared_preferences(17960): 	at android.os.Looper.loop(Looper.java:160)
E/MethodChannel#plugins.flutter.io/shared_preferences(17960): 	at android.app.ActivityThread.main(ActivityThread.java:7029)
E/MethodChannel#plugins.flutter.io/shared_preferences(17960): 	at java.lang.reflect.Method.invoke(Native Method)
E/MethodChannel#plugins.flutter.io/shared_preferences(17960): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:537)
E/MethodChannel#plugins.flutter.io/shared_preferences(17960): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
I/chatty  (17960): uid=10277(sterrenburg.github.flutterhole) identical 3 lines
E/MethodChannel#plugins.flutter.io/shared_preferences(17960): Failed to handle method call
E/MethodChannel#plugins.flutter.io/shared_preferences(17960): java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.String.startsWith(java.lang.String)' on a null object reference
E/MethodChannel#plugins.flutter.io/shared_preferences(17960): 	at io.flutter.plugins.sharedpreferences.SharedPreferencesPlugin.onMethodCall(SharedPreferencesPlugin.java:163)
E/MethodChannel#plugins.flutter.io/shared_preferences(17960): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:222)
E/MethodChannel#plugins.flutter.io/shared_preferences(17960): 	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:96)
E/MethodChannel#plugins.flutter.io/shared_preferences(17960): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:644)
E/MethodChannel#plugins.flutter.io/shared_preferences(17960): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/MethodChannel#plugins.flutter.io/shared_preferences(17960): 	at android.os.MessageQueue.next(MessageQueue.java:326)
E/MethodChannel#plugins.flutter.io/shared_preferences(17960): 	at android.os.Looper.loop(Looper.java:160)
E/MethodChannel#plugins.flutter.io/shared_preferences(17960): 	at android.app.ActivityThread.main(ActivityThread.java:7029)
E/MethodChannel#plugins.flutter.io/shared_preferences(17960): 	at java.lang.reflect.Method.invoke(Native Method)
E/MethodChannel#plugins.flutter.io/shared_preferences(17960): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:537)
E/MethodChannel#plugins.flutter.io/shared_preferences(17960): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
```

Flutter doctor -v:

```
[√] Flutter (Channel master, v1.8.2-pre.124, on Microsoft Windows [Version 10.0.17134.885], locale en-NL)
    • Flutter version 1.8.2-pre.124 at C:\Users\user\src\flutter
    • Framework revision 7bd3e44d9b (10 days ago), 2019-07-21 05:03:27 -0400
    • Engine revision 1fb61b0344
    • Dart version 2.5.0 (build 2.5.0-dev.1.0 a089199b93)


[√] Android toolchain - develop for Android devices (Android SDK version 29.0.1)
    • Android SDK at C:\Users\user\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.1
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.1.6)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.1.29102.190

[√] Android Studio (version 3.4)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 37.1.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

[√] VS Code, 64-bit edition (version 1.36.1)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Flutter extension version 3.2.0

[√] Connected device (3 available)
    • GM1913  • 3ab4c05a • android-arm64  • Android 9 (API 28)
    • Windows • Windows  • windows-x64    • Microsoft Windows [Version 10.0.17134.885]
    • Chrome  • chrome   • web-javascript • Google Chrome 75.0.3770.142

• No issues found!
```

The project I am working on is open source, this is the interface for SharedPreferences: https://github.com/sterrenburg/flutterhole/blob/master/lib/service/local_storage.dart.

**Comment by BugsBunnyBR** [comment]
Hey, @sterrenburg , does this is still happening to you? Would you mind providing the shared preferences version you are using? Have you tried it with the latest version? https://github.com/flutter/plugins/blob/master/packages/shared_preferences/CHANGELOG.md

**Comment by TahaTesser** [comment]
Hi @sterrenburg 
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.
