### ISSUE TITLE
Firebase Auth 0.14.0 getIdToken IllegalArgumentException Unsupported value: null

### ISSUE THREAD

**Issue by geekydiamond** [flutter/flutter#37294]
I have a working system on 0.13.1+1. Upgraded to 0.14.0 and made relevant changes to getIdToken:
	FirebaseUser user = await FirebaseAuth.instance.currentUser();
	String idToken = await user.getIdToken();
became
	FirebaseUser user = await FirebaseAuth.instance.currentUser();
	IdTokenResult idTokenResult = await user.getIdToken();
	String idToken = idTokenResult.token;

However, I now get a failure which closes the app instantly
 java.lang.IllegalArgumentException: Unsupported value: null
 	at io.flutter.plugin.common.StandardMessageCodec.writeValue(StandardMessageCodec.java:294)
 	at io.flutter.plugin.common.StandardMessageCodec.writeValue(StandardMessageCodec.java:291)
 	at io.flutter.plugin.common.StandardMessageCodec.writeValue(StandardMessageCodec.java:291)
 	at io.flutter.plugin.common.StandardMethodCodec.encodeSuccessEnvelope(StandardMethodCodec.java:57)
 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler$1.success(MethodChannel.java:225)
 	at io.flutter.plugins.firebaseauth.FirebaseAuthPlugin$2.onComplete(FirebaseAuthPlugin.java:554)
 	at com.google.android.gms.tasks.zzj.run(Unknown Source:4)
 	at android.os.Handler.handleCallback(Handler.java:790)
 	at android.os.Handler.dispatchMessage(Handler.java:99)
 	at android.os.Looper.loop(Looper.java:164)
 	at android.app.ActivityThread.main(ActivityThread.java:7000)
 	at java.lang.reflect.Method.invoke(Native Method)
 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:441)
 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1408)

**Comment by PaoloMazz** [comment]
I got the same problem.

**Comment by rafael-playko** [comment]
I have the same stack trace, but when logging in with a github auth provider. The crash seems to be caused by the additionalUserInfo map key in the onComplete method in FirebaseAuthPlugin.java

**Comment by escamoteur** [comment]
If you still have the problem please raise a new issue here https://github.com/FirebaseExtended/flutterfire
