### ISSUE TITLE
Cloud Firestore Android "An error occurred while executing doInBackground()" AsyncTask.done

### ISSUE THREAD

**Issue by creativecreatorormaybenot** [flutter/flutter#37356]
This issue has been reported previously in #27840, however, been closed. Hence, I am reporting this again as this is occuring in `Channel master, v1.8.2-pre.229`, `cloud_firestore: 0.12.9`.

I got this report from a Play Store Pre-launch report. Here are the device specifications:

```
Screen Size: 1080 × 1920
Screen Density (dpi): 420
Model Name: Pixel 2
RAM: 4096 MB
Manufacturer: Google
OpenGL ES Version: 3.2
Android Version: Android 8.1
Native Platform: armeabi-v7a
CPU Make: Qualcomm
CPU Model: MSM8998
```

Here is the expcetion:

```
FATAL EXCEPTION: AsyncTask #2
java.lang.RuntimeException: An error occurred while executing doInBackground()
	at android.os.AsyncTask$3.done(AsyncTask.java:353)
	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383)
	at java.util.concurrent.FutureTask.setException(FutureTask.java:252)
	at java.util.concurrent.FutureTask.run(FutureTask.java:271)
	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:245)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
	at java.lang.Thread.run(Thread.java:764)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'com.google.firebase.firestore.ak com.google.firebase.firestore.ak.a(com.google.firebase.firestore.d, java.lang.Object)' on a null object reference
	at io.flutter.plugins.firebase.cloudfirestore.CloudFirestorePlugin$7.doInBackground(Unknown Source:20)
	at io.flutter.plugins.firebase.cloudfirestore.CloudFirestorePlugin$7.doInBackground(Unknown Source:2)
	at android.os.AsyncTask$2.call(AsyncTask.java:333)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	... 4 more
```

This is the Logcat before that point:

```
07-31 00:14:03.657: D/PhoneSwitcherNetworkRequstListener(1610): got request NetworkRequest [ TRACK_DEFAULT id=19, [ Capabilities: INTERNET&NOT_RESTRICTED&TRUSTED&NOT_VPN] ] with score 60
07-31 00:14:03.658: D/Ethernet(1082): got request NetworkRequest [ TRACK_DEFAULT id=19, [ Capabilities: INTERNET&NOT_RESTRICTED&TRUSTED&NOT_VPN] ] with score 60
07-31 00:14:03.658: D/WIFI_UT(1082): got request NetworkRequest [ TRACK_DEFAULT id=19, [ Capabilities: INTERNET&NOT_RESTRICTED&TRUSTED&NOT_VPN] ] with score 60
07-31 00:14:03.658: D/WIFI(1082): got request NetworkRequest [ TRACK_DEFAULT id=19, [ Capabilities: INTERNET&NOT_RESTRICTED&TRUSTED&NOT_VPN] ] with score 60
07-31 00:14:03.658: D/ConnectivityService(1082): requestNetwork for uid/pid:10140/12358 NetworkRequest [ TRACK_DEFAULT id=20, [ Capabilities: INTERNET&NOT_RESTRICTED&TRUSTED&NOT_VPN] ]
07-31 00:14:03.659: D/Ethernet(1082): got request NetworkRequest [ TRACK_DEFAULT id=20, [ Capabilities: INTERNET&NOT_RESTRICTED&TRUSTED&NOT_VPN] ] with score 60
07-31 00:14:03.659: D/WIFI_AWARE_FACTORY(1082): got request NetworkRequest [ TRACK_DEFAULT id=20, [ Capabilities: INTERNET&NOT_RESTRICTED&TRUSTED&NOT_VPN] ] with score 60
07-31 00:14:03.659: D/PhoneSwitcherNetworkRequstListener(1610): got request NetworkRequest [ TRACK_DEFAULT id=20, [ Capabilities: INTERNET&NOT_RESTRICTED&TRUSTED&NOT_VPN] ] with score 60
07-31 00:14:03.659: D/WIFI_UT(1082): got request NetworkRequest [ TRACK_DEFAULT id=20, [ Capabilities: INTERNET&NOT_RESTRICTED&TRUSTED&NOT_VPN] ] with score 60
07-31 00:14:03.659: D/WIFI(1082): got request NetworkRequest [ TRACK_DEFAULT id=20, [ Capabilities: INTERNET&NOT_RESTRICTED&TRUSTED&NOT_VPN] ] with score 60
07-31 00:14:03.679: I/Robo(12309): Finished writing artifact file /storage/emulated/0/app_firebase_test_lab/accessibility1.meta
07-31 00:14:03.848: I/ActivityManager(1082): Killing 10465:com.android.settings/1000 (adj 906): empty #17
07-31 00:14:03.849: W/zygote64(1082): kill(-10465, 9) failed: No such process
07-31 00:14:03.854: I/Robo(12309): Finished writing artifact file /storage/emulated/0/app_firebase_test_lab/1.png
07-31 00:14:03.855: W/zygote64(1082): kill(-10465, 9) failed: No such process
07-31 00:14:03.862: I/Robo(12309): Waiting because there are no actionable elements on screen.
07-31 00:14:03.862: I/Robo(12309): Performing androidx.test.tools.crawler.controller.action.WaitAction@5db4a2.
07-31 00:14:03.864: I/Robo(12358): Waiting 1000 milliseconds.
07-31 00:14:03.899: W/zygote64(1082): kill(-10465, 9) failed: No such process
07-31 00:14:03.899: I/zygote64(1082): Successfully killed process cgroup uid 1000 pid 10465 in 49ms
07-31 00:14:03.899: I/zygote64(1082): --------- beginning of crash
```

**Comment by kroikie** [comment]
@creativecreatorormaybenot

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/1209. Any further collaboration will be done there.
