### ISSUE TITLE
ProcessException: Process "E:\CoWork_pk\cowork\android\gradlew.bat" exited abnormally:

### ISSUE THREAD

**Issue by saadjavaidalvi** [flutter/flutter#37379]
## Logs

```
[   +1 ms] D8: Program type already present: android.support.v4.media.MediaBrowserCompat$CustomActionCallback
[   +7 ms] 136 actionable tasks: 5 executed, 131 up-to-date
[        ]          *********************************************************
[   +3 ms] WARNING: This version of connectivity will break your Android build if it or its dependencies aren't compatible with AndroidX.
[        ]          See https://goo.gl/CP92wY for more information on the problem and how to fix it.
[        ]          This warning prints for all Android build failures. The real root cause of the error may be unrelated.
[        ]          *********************************************************
[ +105 ms] FAILURE: Build failed with an exception.
[  +44 ms] * What went wrong:
[   +1 ms] Execution failed for task ':app:transformDexArchiveWithExternalLibsDexMergerForDebug'.
[   +1 ms] > com.android.builder.dexing.DexArchiveMergerException: Error while merging dex archives:
E:\CoWork_pk\cowork\build\app\intermediates\transforms\dexBuilder\debug\2.jar,
E:\CoWork_pk\cowork\build\app\intermediates\transforms\dexBuilder\debug\3.jar,
E:\CoWork_pk\cowork\build\app\intermediates\transforms\dexBuilder\debug\4.jar,
E:\CoWork_pk\cowork\build\app\intermediates\transforms\dexBuilder\debug\5.jar,
E:\CoWork_pk\cowork\build\app\intermediates\transforms\dexBuilder\debug\6.jar,
E:\CoWork_pk\cowork\build\app\intermediates\transforms\dexBuilder\debug\7.jar,
E:\CoWork_pk\cowork\build\app\intermediates\transforms\dexBuilder\debug\8.jar,
E:\CoWork_pk\cowork\build\app\intermediates\transforms\dexBuilder\debug\9.jar,
E:\CoWork_pk\cowork\build\app\intermediates\transforms\dexBuilder\debug\10.jar,
E:\CoWork_pk\cowork\build\app\intermediates\transforms\dexBuilder\debug\11.jar,
E:\CoWork_pk\cowork\build\app\intermediates\transforms\dexBuilder\debug\12.jar,
E:\CoWork_pk\cowork\build\app\intermediates\transforms\dexBuilder\debug\13.jar,
E:\CoWork_pk\cowork\build\app\intermediates\transforms\dexBuilder\debug\14.jar,
E:\CoWork_pk\cowork\build\app\intermediates\transforms\dexBuilder\debug\15.jar,
E:\CoWork_pk\cowork\build\app\intermediates\transforms\dexBuilder\debug\16.jar,
E:\CoWork_pk\cowork\build\app\intermediates\transforms\dexBuilder\debug\17.jar,
E:\CoWork_pk\cowork\build\app\intermediates\transforms\dexBuilder\debug\18.jar,
E:\CoWork_pk\cowork\build\app\intermediates\transforms\dexBuilder\debug\19.jar,
E:\CoWork_pk\cowork\build\app\intermediates\transforms\dexBuilder\debug\20.jar,
E:\CoWork_pk\cowork\build\app\intermediates\transforms\dexBuilder\debug\21.jar,
E:\CoWork_pk\cowork\build\app\intermediates\transforms\dexBuilder\debug\22.jar,
E:\CoWork_pk\cowork\build\app\intermediates\transforms\dexBuilder\debug\40.jar,
E:\CoWork_pk\cowork\build\app\intermediates\transforms\dexBuilder\debug\43.jar,
E:\CoWork_pk\cowork\build\app\intermediates\transforms\dexBuilder\debug\46.jar,
E:\CoWork_pk\cowork\build\app\intermediates\transforms\dexBuilder\debug\49.jar,
E:\CoWork_pk\cowork\build\app\intermediates\transforms\dexBuilder\debug\52.jar,
E:\CoWork_pk\cowork\build\app\intermediates\transforms\dexBuilder\debug\55.jar,
E:\CoWork_pk\cowork\build\app\intermediates\transforms\dexBuilder\debug\58.jar,
E:\CoWork_pk\cowork\build\app\intermediates\transforms\dexBuilder\debug\61.jar,
E:\CoWork_pk\cowork\build\app\intermediates\transforms\dexBuilder\debug\64.jar,
E:\CoWork_pk\cowork\build\app\intermediates\transforms\dexBuilder\debug\67.jar,
E:\CoWork_pk\cowork\build\app\intermediates\transforms\dexBuilder\debug\70.jar,
E:\CoWork_pk\cowork\build\app\intermediates\transforms\dexBuilder\debug\73.jar,
E:\CoWork_pk\cowork\build\app\intermediates\transforms\dexBuilder\debug\76.jar,
E:\CoWork_pk\cowork\build\app\intermediates\transforms\dexBuilder\debug\79.jar,
E:\CoWork_pk\cowork\build\app\intermediates\transforms\dexBuilder\debug\82.jar,
E:\CoWork_pk\cowork\build\app\intermediates\transforms\dexBuilder\debug\85.jar,
E:\CoWork_pk\cowork\build\app\intermediates\transforms\dexBuilder\debug\88.jar,
E:\CoWork_pk\cowork\build\app\intermediates\transforms\dexBuilder\debug\91.jar,
E:\CoWork_pk\cowork\build\app\intermediates\transforms\dexBuilder\debug\94.jar,
E:\CoWork_pk\cowork\build\app\intermediates\transforms\dexBuilder\debug\97.jar,
E:\CoWork_pk\cowork\build\app\intermediates\transforms\dexBuilder\debug\100.jar,
E:\CoWork_pk\cowork\build\app\intermediates\transforms\dexBuilder\debug\103.jar,
E:\CoWork_pk\cowork\build\app\intermediates\transforms\dexBuilder\debug\106.jar,
E:\CoWork_pk\cowork\build\app\intermediates\transforms\dexBuilder\debug\109.jar,
E:\CoWork_pk\cowork\build\app\intermediates\transforms\dexBuilder\debug\112.jar,
E:\CoWork_pk\cowork\build\app\intermediates\transforms\dexBuilder\debug\115.jar,
E:\CoWork_pk\cowork\build\app\intermediates\transforms\dexBuilder\debug\118.jar,
E:\CoWork_pk\cowork\build\app\intermediates\transforms\dexBuilder\debug\121.jar,
E:\CoWork_pk\cowork\build\app\intermediates\transforms\dexBuilder\debug\124.jar
[  +20 ms]   Learn how to resolve the issue at https://developer.android.com/studio/build/dependencies#duplicate_classes.
[        ]   Program type already present: android.support.v4.media.MediaBrowserCompat$CustomActionCallback
[        ] * Try:
[        ] Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to
get full insights.
[  +34 ms] * Get more help at https://help.gradle.org
[   +1 ms] BUILD FAILED in 20s
[ +302 ms] Running Gradle task 'assembleDebug'... (completed in 21.4s)
[        ] *******************************************************************************************
[        ] The Gradle failure may have been because of AndroidX incompatibilities in this Flutter app.
[        ] See https://goo.gl/CP92wY for more information on the problem and how to fix it.
[        ] *******************************************************************************************
[   +5 ms] "flutter run" took 31,595ms.
[   +4 ms] "flutter run" took 31,595ms.
Gradle task assembleDebug failed with exit code 1

#0      throwToolExit (package:flutter_tools/src/base/common.dart:24:3)
#1      _buildGradleProjectV2 (package:flutter_tools/src/android/gradle.dart:462:5)
<asynchronous suspension>
#2      buildGradleProject (package:flutter_tools/src/android/gradle.dart:331:14)
<asynchronous suspension>
#3      buildApk (package:flutter_tools/src/android/apk.dart:43:10)
<asynchronous suspension>
#4      AndroidDevice.startApp (package:flutter_tools/src/android/android_device.dart:378:13)
<asynchronous suspension>
#5      FlutterDevice.runHot (package:flutter_tools/src/resident_runner.dart:308:54)
<asynchronous suspension>
#6      HotRunner.run (package:flutter_tools/src/run_hot.dart:295:39)
<asynchronous suspension>
#7      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:405:37)
<asynchronous suspension>
#8      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:545:18)
#9      _asyncThenWrapperHelper.<anonymous closure> (dart:async/runtime/libasync_patch.dart:77:64)
#10     _rootRunUnary (dart:async/zone.dart:1132:38)
#11     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#12     _FutureListener.handleValue (dart:async/future_impl.dart:126:18)
#13     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:639:45)
#14     Future._propagateToListeners (dart:async/future_impl.dart:668:32)
#15     Future._complete (dart:async/future_impl.dart:473:7)
#16     _SyncCompleter.complete (dart:async/future_impl.dart:51:12)
#17     _AsyncAwaitCompleter.complete (dart:async/runtime/libasync_patch.dart:28:18)
#18     _completeOnAsyncReturn (dart:async/runtime/libasync_patch.dart:294:13)
#19     RunCommand.usageValues (package:flutter_tools/src/commands/run.dart)
#20     _asyncThenWrapperHelper.<anonymous closure> (dart:async/runtime/libasync_patch.dart:77:64)
#21     _rootRunUnary (dart:async/zone.dart:1132:38)
#22     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#23     _FutureListener.handleValue (dart:async/future_impl.dart:126:18)
#24     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:639:45)
#25     Future._propagateToListeners (dart:async/future_impl.dart:668:32)
#26     Future._complete (dart:async/future_impl.dart:473:7)
#27     _SyncCompleter.complete (dart:async/future_impl.dart:51:12)
#28     _AsyncAwaitCompleter.complete (dart:async/runtime/libasync_patch.dart:28:18)
#29     _completeOnAsyncReturn (dart:async/runtime/libasync_patch.dart:294:13)
#30     AndroidDevice.targetPlatform (package:flutter_tools/src/android/android_device.dart)
#31     _asyncThenWrapperHelper.<anonymous closure> (dart:async/runtime/libasync_patch.dart:77:64)
#32     _rootRunUnary (dart:async/zone.dart:1132:38)
#33     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#34     _FutureListener.handleValue (dart:async/future_impl.dart:126:18)
#35     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:639:45)
#36     Future._propagateToListeners (dart:async/future_impl.dart:668:32)
#37     Future._complete (dart:async/future_impl.dart:473:7)
#38     _SyncCompleter.complete (dart:async/future_impl.dart:51:12)
#39     _AsyncAwaitCompleter.complete.<anonymous closure> (dart:async/runtime/libasync_patch.dart:33:20)
#40     _rootRun (dart:async/zone.dart:1124:13)
#41     _CustomZone.run (dart:async/zone.dart:1021:19)
#42     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:947:23)
#43     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#44     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#45     _runPendingImmediateCallback (dart:isolate/runtime/libisolate_patch.dart:115:13)
#46     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:172:5)

```
```

* Error running Gradle:
ProcessException: Process "E:\CoWork_pk\cowork\android\gradlew.bat" exited abnormally:

FAILURE: Build failed with an exception.

* Where:
Build file 'E:\CoWork_pk\cowork\android\app\build.gradle' line: 43

* What went wrong:
A problem occurred evaluating project ':app'.
> Could not find method compile() for arguments [com.android.support:multidex:1.0.3] on DefaultConfig_Decorated{name=main, dimension=null, minSdkVersion=null, targetSdkVersion=null, renderscriptTargetApi=null, renderscriptSupportModeEnabled=null, renderscriptSupportModeBlasEnabled=null, renderscriptNdkModeEnabled=null, versionCode=null, versionName=null, applicationId=com.example.cowork, testApplicationId=null, testInstrumentationRunner=null, testInstrumentationRunnerArguments={}, testHandleProfiling=null, testFunctionalTest=null, signingConfig=null, resConfig=null, mBuildConfigFields={}, mResValues={}, mProguardFiles=[], mConsumerProguardFiles=[], mManifestPlaceholders={}, mWearAppUnbundled=null} of type com.android.build.gradle.internal.dsl.DefaultConfig.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 4s
  Command: E:\CoWork_pk\cowork\android\gradlew.bat app:properties

Please review your Gradle project setup in the android/ folder

```

**Comment by BondarenkoStas** [comment]
@saadjavaidalvi is the issue still relevant? Please provide your ```flutter doctor -v``` output. Can you come up with some small self-contained app that demonstrates the issue?

**Comment by iapicca** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!

Could everyone who still has this problem please file a new issue with the exact descriptions what happens, logs and the output of ' flutter doctor -v'  please.
All system setups can be slightly different so its always better to open new issues and reference related issues.
