### ISSUE TITLE
google_maps_flutter - GoogleMap widget can't be placed in a Column

### ISSUE THREAD

**Issue by viratshukla** [flutter/flutter#37383]
If I put Google Map widget directly inside scafold's body or inside a Stack, it works fine.
But when I am trying to put it inside Column(), then it throws following error - 
## Steps to Reproduce
```
Column(
          children: <Widget>[
            GoogleMap(
              mapType: MapType.normal,
              initialCameraPosition: CameraPosition(target: _center, zoom: 15),
            ),
          ],
        ),
```
## Logs
```
D/SharedPreferencesImpl( 8803): Time required to fsync /data/user/0/com.mobily.mobily_b2b/shared_prefs/FlutterSharedPreferences.xml: [<1: 0, <2: 0, <4: 0, <8: 0, <16: 0, <32: 0, <64: 0, <128: 0, <256: 0, <512: 0, <1024: 0, <2048: 1, <4096: 0, <8192: 0, <16384: 0, >=16384: 0]
I/flutter ( 8803): ══╡ EXCEPTION CAUGHT BY RENDERING LIBRARY ╞═════════════════════════════════════════════════════════
I/flutter ( 8803): The following assertion was thrown during performResize():
I/flutter ( 8803): FlutterError contained multiple error summaries.
I/flutter ( 8803): All FlutterError objects should have only a single short (one line) summary description of the
I/flutter ( 8803): problem that was detected.
I/flutter ( 8803): Malformed FlutterError:
I/flutter ( 8803):   RenderAndroidView object was given an infinite size during layout.
I/flutter ( 8803):   This probably means that it is a render object that tries to be as big as possible, but it was put
I/flutter ( 8803):   inside another render object that allows its children to pick their own size.
I/flutter ( 8803):   RenderAndroidView object was given an infinite size during layout.
I/flutter ( 8803):   This probably means that it is a render object that tries to be as big as possible, but it was put
I/flutter ( 8803):   inside another render object that allows its children to pick their own size.
I/flutter ( 8803):   The nearest ancestor providing an unbounded height constraint is: RenderFlex#6b811 relayoutBoundary=up1 NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE:
I/flutter ( 8803):     creator: Column ← MediaQuery ← LayoutId-[<_ScaffoldSlot.body>] ← CustomMultiChildLayout ←
I/flutter ( 8803):       AnimatedBuilder ← DefaultTextStyle ← AnimatedDefaultTextStyle ← _InkFeatures-[GlobalKey#b0092 ink
I/flutter ( 8803):       renderer] ← NotificationListener<LayoutChangedNotification> ← PhysicalModel ←
I/flutter ( 8803):       AnimatedPhysicalModel ← Material ← ⋯
I/flutter ( 8803):     parentData: offset=Offset(0.0, 0.0); id=_ScaffoldSlot.body (can use size)
I/flutter ( 8803):     constraints: BoxConstraints(0.0<=w<=360.0, 0.0<=h<=592.0)
I/flutter ( 8803):     size: MISSING
I/flutter ( 8803):     direction: vertical
I/flutter ( 8803):     mainAxisAlignment: start
I/flutter ( 8803):     mainAxisSize: max
I/flutter ( 8803):     crossAxisAlignment: center
I/flutter ( 8803):     verticalDirection: down
I/flutter ( 8803):   The constraints that applied to the RenderAndroidView were:
I/flutter ( 8803):     BoxConstraints(0.0<=w<=360.0, 0.0<=h<=Infinity)
I/flutter ( 8803):   The exact size it was given was:
I/flutter ( 8803):     Size(360.0, Infinity)
I/flutter ( 8803):   See https://flutter.dev/docs/development/ui/layout/box-constraints for more information.
I/flutter ( 8803): 
I/flutter ( 8803): The malformed error has 2 summaries.
I/flutter ( 8803): Summary 1: RenderAndroidView object was given an infinite size during layout.
I/flutter ( 8803): Summary 2: RenderAndroidView object was given an infinite size during layout.
I/flutter ( 8803): 
I/flutter ( 8803): This error should still help you solve your problem, however please also report this malformed error
I/flutter ( 8803): in the framework by filing a bug on GitHub:
I/flutter ( 8803):   https://github.com/flutter/flutter/issues/new?template=BUG.md
I/flutter ( 8803): 
I/flutter ( 8803): When the exception was thrown, this was the stack:
I/flutter ( 8803): #0      new FlutterError.fromParts.<anonymous closure> (package:flutter/src/foundation/assertions.dart:540:9)
I/flutter ( 8803): #1      new FlutterError.fromParts (package:flutter/src/foundation/assertions.dart:543:6)
I/flutter ( 8803): #2      RenderBox.debugAssertDoesMeetConstraints.<anonymous closure> (package:flutter/src/rendering/box.dart:1966:28)
I/flutter ( 8803): #3      RenderBox.debugAssertDoesMeetConstraints (package:flutter/src/rendering/box.dart:2029:6)
I/flutter ( 8803): #4      RenderBox.size=.<anonymous closure> (package:flutter/src/rendering/box.dart:1740:7)
I/flutter ( 8803): #5      RenderBox.size= (package:flutter/src/rendering/box.dart:1742:6)
I/flutter ( 8803): #6      RenderAndroidView.performResize (package:flutter/src/rendering/platform_view.dart:169:5)
I/flutter ( 8803): #7      RenderObject.layout (package:flutter/src/rendering/object.dart:1604:9)
I/flutter ( 8803): #8      RenderFlex.performLayout (package:flutter/src/rendering/flex.dart:743:15)
I/flutter ( 8803): #9      RenderObject.layout (package:flutter/src/rendering/object.dart:1619:7)
I/flutter ( 8803): #10     MultiChildLayoutDelegate.layoutChild (package:flutter/src/rendering/custom_layout.dart:142:11)
I/flutter ( 8803): #11     _ScaffoldLayout.performLayout (package:flutter/src/material/scaffold.dart:443:7)
I/flutter ( 8803): #12     MultiChildLayoutDelegate._callPerformLayout (package:flutter/src/rendering/custom_layout.dart:212:7)
I/flutter ( 8803): #13     RenderCustomMultiChildLayoutBox.performLayout (package:flutter/src/rendering/custom_layout.dart:356:14)
I/flutter ( 8803): #14     RenderObject.layout (package:flutter/src/rendering/object.dart:1619:7)
I/flutter ( 8803): #15     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter ( 8803): #16     RenderObject.layout (package:flutter/src/rendering/object.dart:1619:7)
I/flutter ( 8803): #17     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter ( 8803): #18     _RenderCustomClip.performLayout (package:flutter/src/rendering/proxy_box.dart:1214:11)
I/flutter ( 8803): #19     RenderObject.layout (package:flutter/src/rendering/object.dart:1619:7)
I/flutter ( 8803): #20     RenderPadding.performLayout (package:flutter/src/rendering/shifted_box.dart:206:11)
I/flutter ( 8803): #21     RenderObject.layout (package:flutter/src/rendering/object.dart:1619:7)
I/flutter ( 8803): #22     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter ( 8803): #23     RenderObject.layout (package:flutter/src/rendering/object.dart:1619:7)
I/flutter ( 8803): #24     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter ( 8803): #25     RenderObject.layout (package:flutter/src/rendering/object.dart:1619:7)
I/flutter ( 8803): #26     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter ( 8803): #27     RenderObject.layout (package:flutter/src/rendering/object.dart:1619:7)
I/flutter ( 8803): #28     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter ( 8803): #29     RenderObject.layout (package:flutter/src/rendering/object.dart:1619:7)
I/flutter ( 8803): #30     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter ( 8803): #31     RenderObject.layout (package:flutter/src/rendering/object.dart:1619:7)
I/flutter ( 8803): #32     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter ( 8803): #33     RenderObject.layout (package:flutter/src/rendering/object.dart:1619:7)
I/flutter ( 8803): #34     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter ( 8803): #35     RenderObject.layout (package:flutter/src/rendering/object.dart:1619:7)
I/flutter ( 8803): #36     RenderOffstage.performLayout (package:flutter/src/rendering/proxy_box.dart:3074:14)
I/flutter ( 8803): #37     RenderObject.layout (package:flutter/src/rendering/object.dart:1619:7)
I/flutter ( 8803): #38     RenderStack.performLayout (package:flutter/src/rendering/stack.dart:510:15)
I/flutter ( 8803): #39     RenderObject._layoutWithoutResize (package:flutter/src/rendering/object.dart:1496:7)
I/flutter ( 8803): #40     PipelineOwner.flushLayout (package:flutter/src/rendering/object.dart:765:18)
I/flutter ( 8803): #41     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding.drawFrame (package:flutter/src/rendering/binding.dart:346:19)
I/flutter ( 8803): #42     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding&WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:701:13)
I/flutter ( 8803): #43     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:285:5)
I/flutter ( 8803): #44     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1016:15)
I/flutter ( 8803): #45     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:958:9)
I/flutter ( 8803): #46     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:874:5)
I/flutter ( 8803): #50     _invoke (dart:ui/hooks.dart:236:10)
I/flutter ( 8803): #51     _drawFrame (dart:ui/hooks.dart:194:3)
I/flutter ( 8803): (elided 3 frames from package dart:async)
I/flutter ( 8803): 
I/flutter ( 8803): The following RenderObject was being processed when the exception was fired: RenderAndroidView#48805 NEEDS-LAYOUT NEEDS-PAINT:
I/flutter ( 8803):   needs compositing
I/flutter ( 8803):   creator: _AndroidPlatformView ← _FocusMarker ← Focus ← AndroidView ← GoogleMap ← Column ← MediaQuery
I/flutter ( 8803):     ← LayoutId-[<_ScaffoldSlot.body>] ← CustomMultiChildLayout ← AnimatedBuilder ← DefaultTextStyle ←
I/flutter ( 8803):     AnimatedDefaultTextStyle ← ⋯
I/flutter ( 8803):   parentData: offset=Offset(0.0, 0.0); flex=null; fit=null (can use size)
I/flutter ( 8803):   constraints: BoxConstraints(0.0<=w<=360.0, 0.0<=h<=Infinity)
I/flutter ( 8803):   semantic boundary
I/flutter ( 8803):   size: Size(360.0, Infinity)
I/flutter ( 8803): This RenderObject has no descendants.
I/flutter ( 8803): ════════════════════════════════════════════════════════════════════════════════════════════════════
I/flutter ( 8803): Another exception was thrown: FlutterError contained multiple error summaries.
I/flutter ( 8803): Another exception was thrown: A RenderFlex overflowed by Infinity pixels on the bottom.

<!-- Finally, paste the output of running `flutter doctor -v` here. -->

```
```
flutter doctor -v
[√] Flutter (Channel stable, v1.7.8+hotfix.4, on Microsoft Windows [Version 10.0.17134.765], locale en-US)
    • Flutter version 1.7.8+hotfix.4 at D:\flutter
    • Framework revision 20e59316b8 (13 days ago), 2019-07-18 20:04:33 -0700
    • Engine revision fee001c93f
    • Dart version 2.4.0


[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at D:\Studio\Sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = D:\Studio\Sdk
    • Java binary at: C:\Users\80065124\Downloads\android-studio- 3.5 canary 13\android-studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)
    • All Android licenses accepted.

[!] Android Studio (version 2.3)
    • Android Studio at C:\Program Files\Android\Android Studio2.3
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[√] Android Studio (version 3.4)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 37.1.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

[√] Android Studio (version 3.5)
    • Android Studio at C:\Users\80065124\Downloads\android-studio- 3.5 canary 13\android-studio
    • Flutter plugin version 37.1.3
    • Dart plugin version 191.7830
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)

[√] Connected device (1 available)
    • Mi A2 • 4bc59cd • android-arm64 • Android 9 (API 28)

! Doctor found issues in 1 category.

```

**Comment by alikamal1** [comment]
you can specify the size of the map
`Column(
children: [
SizedBox(
                width: MediaQuery.of(context).size.width,
                height: MediaQuery.of(context).size.height ,
child: GoogleMap(
mapType: MapType.normal,
initialCameraPosition: CameraPosition(target: _center, zoom: 15),
)),
],
),`

**Comment by viratshukla** [comment]
If placed in column, only zoom in map is working, that is also on double tap. No zooming out, no sliding in map to other location. Its like a static image of map.

**Comment by BondarenkoStas** [comment]
@viratshukla is the issue still relevant? What the version of google_maps_flutter do you use?

**Comment by alikamal1** [comment]
@viratshukla you can set gesture recognizer for google map inside the column  
``` dart
Column(
children: [
 SizedBox(
  width: MediaQuery.of(context).size.width,  // or use fixed size like 200
  height: MediaQuery.of(context).size.height,
  child: GoogleMap(
               gestureRecognizers: <Factory<OneSequenceGestureRecognizer>>[
                  Factory<OneSequenceGestureRecognizer>(
                      () => EagerGestureRecognizer())].toSet(),
     mapType: MapType.normal,
     initialCameraPosition: CameraPosition(target: _center, zoom: 15),
   ))
])
```

**Comment by viratshukla** [comment]
> @viratshukla you can set gesture recognizer for google map inside the column
> 
> ```dart
> Column(
> children: [
>  SizedBox(
>   width: MediaQuery.of(context).size.width,  // or use fixed size like 200
>   height: MediaQuery.of(context).size.height,
>   child: GoogleMap(
>     gestureRecognizers: <Factory<OneSequenceGestureRecognizer>>[
>          Factory<OneSequenceGestureRecognizer>(
>         () => EagerGestureRecognizer())].toSet(),
>      mapType: MapType.normal,
>      initialCameraPosition: CameraPosition(target: _center, zoom: 15),
>    ))
> ])
> ```

Thanks :)

**Comment by viratshukla** [comment]
thanks @alikamal1

**Comment by alok1upadhyay** [comment]
how about expand

**Comment by anurag-176** [comment]
Or just simply...`SizedBox(
          height: MediaQuery.of(context).size.height*0.5,
          child: ...,
        ),`
