### ISSUE TITLE
Cloud Firestore transactions hang or crash app with Flutter v1.7.8

### ISSUE THREAD

**Issue by danisun** [flutter/flutter#37443]
When using Flutter 1.7.8-hotfix.2 with cloud firestore 0.10.1 and firestore core 0.3.4 calling the following method never returns. Only the 'before transaction' text is printed.

```
pubspec.yaml

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^0.3.4
  cloud_firestore: ^0.10.1
```
```
  Future<void> test() async {
    try {
      print('before transaction');
      await _firestore.runTransaction((Transaction tx) async {
        print('in transaction');
        throw Exception();
      });
    } catch (e) {
      print('caught $e');
    }
    print('after transaction');
  }
```
If I upgrade cloud firestore and firebase core to versions: 0.12.7+1 and 0.4.0 respectively and then invoke the above test() method, the exception thrown from inside the transaction causes the application to crash with the following exception:

```
pubspec.yaml

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^0.4.0
  cloud_firestore: ^0.12.7+1
```
```
2019-08-02 11:58:00.399 13370-13405/com.acubeware.satisfy I/flutter: before transaction
2019-08-02 11:58:00.665 13370-13405/com.acubeware.satisfy I/flutter: in transaction
2019-08-02 11:58:00.709 13370-13446/com.acubeware.satisfy E/CloudFirestorePlugin: java.lang.Exception: DoTransaction failed: Exception
    java.util.concurrent.ExecutionException: java.lang.Exception: DoTransaction failed: Exception
        at com.google.android.gms.tasks.Tasks.zzb(Unknown Source:61)
        at com.google.android.gms.tasks.Tasks.await(Unknown Source:33)
        at io.flutter.plugins.firebase.cloudfirestore.CloudFirestorePlugin$4.apply(CloudFirestorePlugin.java:424)
        at io.flutter.plugins.firebase.cloudfirestore.CloudFirestorePlugin$4.apply(CloudFirestorePlugin.java:376)
        at com.google.firebase.firestore.FirebaseFirestore.lambda$runTransaction$1(com.google.firebase:firebase-firestore@@19.0.0:283)
        at com.google.firebase.firestore.FirebaseFirestore$$Lambda$3.call(Unknown Source:6)
        at com.google.android.gms.tasks.zzv.run(Unknown Source:2)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:764)
     Caused by: java.lang.Exception: DoTransaction failed: Exception
        at io.flutter.plugins.firebase.cloudfirestore.CloudFirestorePlugin$4$1$1.error(CloudFirestorePlugin.java:406)
        at io.flutter.plugin.common.MethodChannel$IncomingResultHandler.reply(MethodChannel.java:201)
        at io.flutter.embedding.engine.dart.DartMessenger.handlePlatformMessageResponse(DartMessenger.java:114)
        at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessageResponse(FlutterJNI.java:653)
        at android.os.MessageQueue.nativePollOnce(Native Method)
        at android.os.MessageQueue.next(MessageQueue.java:326)
        at android.os.Looper.loop(Looper.java:160)
        at android.app.ActivityThread.main(ActivityThread.java:6669)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
2019-08-02 11:58:00.713 13370-13370/com.acubeware.satisfy D/AndroidRuntime: Shutting down VM
2019-08-02 11:58:00.714 13370-13370/com.acubeware.satisfy E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.acubeware.satisfy, PID: 13370
    java.lang.IllegalStateException: Reply already submitted
        at io.flutter.embedding.engine.dart.DartMessenger$Reply.reply(DartMessenger.java:135)
        at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler$1.error(MethodChannel.java:230)
        at io.flutter.plugins.firebase.cloudfirestore.CloudFirestorePlugin$3.onComplete(CloudFirestorePlugin.java:442)
        at com.google.android.gms.tasks.zzj.run(Unknown Source:4)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6669)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
2019-08-02 11:58:00.762 13370-13370/com.acubeware.satisfy I/Process: Sending signal. PID: 13370 SIG: 9
```

```
flutter analyze
Analyzing satisfy...
No issues found! (ran in 2.5s)
```

```
flutter doctor -v
[√] Flutter (Channel stable, v1.7.8+hotfix.2, on Microsoft Windows [Version 10.0.18362.239], locale en-NZ)
    • Flutter version 1.7.8+hotfix.2 at C:\Users\Danita\Development\flutter_windows_v1.7.8+hotfix.2-stable\flutter
    • Framework revision 2e540931f7 (4 weeks ago), 2019-07-02 09:31:07 -0700
    • Engine revision b1cb0d9e9b
    • Dart version 2.4.0


[√] Android toolchain - develop for Android devices (Android SDK version 29.0.1)
    • Android SDK at C:\Program Files (x86)\Android\android-sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.1
    • ANDROID_HOME = C:\Program Files (x86)\Android\android-sdk
    • ANDROID_SDK_ROOT = C:\Program Files (x86)\Android\android-sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
    • All Android licenses accepted.

[√] Android Studio (version 3.4)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 37.1.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

[!] IntelliJ IDEA Community Edition (version 2016.2)
    • IntelliJ at C:\Program Files (x86)\JetBrains\IntelliJ IDEA Community Edition 2016.2.5
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.dev/intellij-setup/#installing-the-plugins
    X This install is older than the minimum recommended version of 2017.1.0.

[√] IntelliJ IDEA Community Edition (version 2018.3)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2018.3
    • Flutter plugin version 32.0.2
    • Dart plugin version 183.4733

[!] VS Code, 64-bit edition (version 1.31.1)
    • VS Code at C:\Program Files\Microsoft VS Code
    X Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[√] Connected device (1 available)
    • Android SDK built for x86 64 • emulator-5554 • android-x64 • Android 9 (API 28) (emulator)

! Doctor found issues in 2 categories.
```

**Comment by thevzurd** [comment]
I had the same problem. Try this. Hope it Helps 
[FIrestore Transaction Handler](https://github.com/thevzurd/Firestore-Transaction-Handler)

**Comment by escamoteur** [comment]
If you still have this problem please file a new issue here https://github.com/FirebaseExtended/flutterfire

**Comment by lemonxah** [comment]
same error here is my stack trace,
`Fatal Exception: java.lang.NullPointerException
Attempt to invoke virtual method 'void d.a.b.a.i.a(java.lang.String, java.lang.Object)' on a null object reference
io.flutter.plugins.firebase.cloudfirestore.CloudFirestorePlugin$EventObserver.a (CloudFirestorePlugin.java:33)
io.flutter.plugins.firebase.cloudfirestore.CloudFirestorePlugin$EventObserver.a (CloudFirestorePlugin.java:2)
com.google.firebase.firestore.Query.a (Query.java:27)
com.google.firebase.firestore.Query$$Lambda$3.a (Query.java:6)
com.google.firebase.firestore.core.AsyncEventListener.a (AsyncEventListener.java:6)
com.google.firebase.firestore.core.AsyncEventListener$$Lambda$1.run (AsyncEventListener.java:6)
android.os.Handler.handleCallback (Handler.java:883)
android.os.Handler.dispatchMessage (Handler.java:100)
android.os.Looper.loop (Looper.java:237)
android.app.ActivityThread.main (ActivityThread.java:7857)
java.lang.reflect.Method.invoke (Method.java)
com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:493)
com.android.internal.os.ZygoteInit.main (ZygoteInit.java:1076)`

**Comment by lemonxah** [comment]
i have gone down to 0.13.1 and will test to make sure that i dont get that error, unfortunately this is a new app so i dont know when this was introduced since i started with 0.13.5. It works 95% of the time and then out of the blue the app dies, you start it back up and everything works again even the thing that made it crash. also FYI this happens on a delete, add, update and even on the remote phone that has Streambuilders for the data that is being changed. Sometimes just deleting a list item on my phone crashes my wife's phone.
