### ISSUE TITLE
 Another exception was thrown: 'package:flutter/src/gestures/monodrag.dart': Failed assertion: line 387 pos 12: '_initialButtons == kPrimaryButton': is not true.

### ISSUE THREAD

**Issue by kecson** [flutter/flutter#37466]
### 1. build a page
```dart
  @override
  Widget build(BuildContext context) {
    return DefaultTabController(
      length: 2,
      child: Scaffold(
          appBar: AppBar(
            title: Text('tabbar'),
            bottom: TabBar(
                tabs: Iterable.generate(2, (index) => Tab(text: 'tab$index'))
                    .toList()),
          ),
          body: TabBarView(children: [
            ListView.builder(
                itemBuilder: (context, index) => ListTile(
                      title: Text('tab 0 list: Item $index'),
                    )),
            ListView.builder(
                itemBuilder: (context, index) => ListTile(
                      title: Text('tab 1 list: Item $index'),
                    ))
          ])),
    );
  }

```
## Logs

```
I/HiTouch_PressGestureDetector: ACTION_POINTER_DOWN.
I/flutter: ══╡ EXCEPTION CAUGHT BY GESTURE LIBRARY ╞═══════════════════════════════════════════════════════════
I/flutter: The following assertion was thrown while dispatching a pointer event:
I/flutter: 'package:flutter/src/gestures/monodrag.dart': Failed assertion: line 357 pos 12: '_initialButtons ==
I/flutter: kPrimaryButton': is not true.
I/flutter: Either the assertion indicates an error in the framework itself, or we should provide substantially
I/flutter: more information in this error message to help you determine and fix the underlying cause.
I/flutter: In either case, please report this assertion by filing a bug on GitHub:
I/flutter:   https://github.com/flutter/flutter/issues/new?template=BUG.md
I/flutter: When the exception was thrown, this was the stack:
I/flutter: #2      DragGestureRecognizer._checkStart (package:flutter/src/gestures/monodrag.dart:357:12)
I/flutter: #3      DragGestureRecognizer.acceptGesture (package:flutter/src/gestures/monodrag.dart:298:7)
I/flutter: #4      GestureArenaManager.sweep (package:flutter/src/gestures/arena.dart:156:27)
I/flutter: #5      _WidgetsFlutterBinding&BindingBase&GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:222:20)
I/flutter: #6      _WidgetsFlutterBinding&BindingBase&GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:198:22)
I/flutter: #7      _WidgetsFlutterBinding&BindingBase&GestureBinding._handlePointerEvent (package:flutter/src/gestures/binding.dart:156:7)
I/flutter: #8      _WidgetsFlutterBinding&BindingBase&GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:102:7)
I/flutter: #9      _WidgetsFlutterBinding&BindingBase&GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:86:7)
I/flutter: #13     _invoke1 (dart:ui/hooks.dart:250:10)
I/flutter: #14     _dispatchPointerDataPacket (dart:ui/hooks.dart:159:5)
I/flutter: (elided 5 frames from class _AssertionError and package dart:async)
I/flutter: Event:
I/flutter:   PointerUpEvent#a8059(position: Offset(101.6, 324.5), timeStamp: 429:52:23.054000, pointer: 101,
I/flutter:   kind: touch, down: false, pressure: 0.1, pressureMin: 0.0)
I/flutter: Target:
I/flutter:   <WidgetsFlutterBinding>
I/flutter: ════════════════════════════════════════════════════════════════════════════════════════════════════
I/flutter: Another exception was thrown: 'package:flutter/src/gestures/monodrag.dart': Failed assertion: line 387 pos 12: '_initialButtons == kPrimaryButton': is not true.
```

```
```

```
```

**Comment by stuartmorgan** [comment]
CC @dkwingsmt

**Comment by dkwingsmt** [comment]
I'm able to reproduce and I'm investigating.

**Comment by yourshinsuke** [comment]
not yet.

1.17

**Comment by dkwingsmt** [comment]
> not yet.
> 
> 
> 
> 1.17

The same error can be caused by different reasons. Can you describe how to reproduce yours?

**Comment by ztigunes** [comment]
i have same issue. Are there any bug fix or workaround solution ? When i use tabbar like dummy user with two or three finger (gesture) it freeze all tab bar views.

flutter: ══╡ EXCEPTION CAUGHT BY GESTURE LIBRARY ╞═══════════════════════════════════════════════════════════
flutter: The following assertion was thrown while routing a pointer event:
flutter: 'package:flutter/src/gestures/monodrag.dart': Failed assertion: line 416 pos 12: '_initialButtons ==
flutter: kPrimaryButton': is not true.
flutter:
flutter: Either the assertion indicates an error in the framework itself, or we should provide substantially
flutter: more information in this error message to help you determine and fix the underlying cause.
flutter: In either case, please report this assertion by filing a bug on GitHub:
flutter: https://github.com/flutter/flutter/issues/new?template=BUG.md
flutter:
flutter: When the exception was thrown, this was the stack:
flutter: #2 DragGestureRecognizer._checkEnd
package:flutter/…/gestures/monodrag.dart:416
flutter: #3 DragGestureRecognizer.didStopTrackingLastPointer
package:flutter/…/gestures/monodrag.dart:358
flutter: #4 OneSequenceGestureRecognizer.stopTrackingPointer
package:flutter/…/gestures/recognizer.dart:343
flutter: #5 DragGestureRecognizer._giveUpPointer
package:flutter/…/gestures/monodrag.dart:367
flutter: #6 DragGestureRecognizer.handleEvent
package:flutter/…/gestures/monodrag.dart:256
flutter: #7 PointerRouter._dispatch
package:flutter/…/gestures/pointer_router.dart:78

igunes@igunes ios % flutter doctor -v
[✓] Flutter (Channel stable, 1.20.3, on Mac OS X 10.15.6 19G2021, locale en-TR)
• Flutter version 1.20.3 at /users/igunes/flutter
• Framework revision 216dee6 (13 days ago), 2020-09-01 12:24:47 -0700
• Engine revision d1bc06f032
• Dart version 2.9.2

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
• Android SDK at /Users/igunes/Library/Android/sdk
• Platform android-30, build-tools 30.0.0
• Java binary at: /Applications/Android
Studio.app/Contents/jre/jdk/Contents/Home/bin/java
• Java version OpenJDK Runtime Environment (build
1.8.0_242-release-1644-b3-6222593)
• All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.7)
• Xcode at /Applications/Xcode.app/Contents/Developer
• Xcode 11.7, Build version 11E801a
• CocoaPods version 1.9.3

[✓] Android Studio (version 4.0)
• Android Studio at /Applications/Android Studio.app/Contents
• Flutter plugin version 48.1.2
• Dart plugin version 193.7361
• Java version OpenJDK Runtime Environment (build
1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.49.0)
• VS Code at /Applications/Visual Studio Code.app/Contents
• Flutter extension version 3.14.1

[✓] Connected device (1 available)
• Mustafa’s iPad (mobile) • ec9cc0171e4772f3dbca05f0c732828429310826 • ios •
iOS 13.5.1
