### ISSUE TITLE
flutter on tablet: RangeError (length) invalid value: Valid value range is empty: 0. It seems that if the device is not connected to the internet and has Firebase on it, it gets this error. Is there any exception handling I can do there?

### ISSUE THREAD

**Issue by kushtra24** [flutter/flutter#37472]
The app works everywhere but on a table, even the emulator tablets work, 
I got a Huawei MediaPad m5 android 9,  last android security update was 5, june 2019.

console log is this

```
Launching lib\main.dart on CMR W09 in debug mode...
Initializing gradle...
Resolving dependencies...
Running Gradle task 'assembleDebug'...
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
Built build\app\outputs\apk\debug\app-debug.apk.
Installing build\app\outputs\apk\app.apk...
W/DynamiteModule(12312): Local module descriptor class for providerinstaller not found.
I/DynamiteModule(12312): Considering local module providerinstaller:0 and remote module providerinstaller:0
W/ProviderInstaller(12312): Failed to load providerinstaller module: No acceptable module found. Local version is 0 and remote version is 0.
I/com.avl.newapp(12312): The ClassLoaderContext is a special shared library.
I/chatty  (12312): uid=10142(com.avl.newapp) FirestoreWorker identical 1 line
I/com.avl.newapp(12312): The ClassLoaderContext is a special shared library.
W/FirebaseMessagingPlugin(12312): getToken, error fetching instanceID: 
W/FirebaseMessagingPlugin(12312): java.io.IOException: SERVICE_NOT_AVAILABLE
W/FirebaseMessagingPlugin(12312): 	at com.google.firebase.iid.zzr.zza(Unknown Source:66)
W/FirebaseMessagingPlugin(12312): 	at com.google.firebase.iid.zzr.zza(Unknown Source:79)
W/FirebaseMessagingPlugin(12312): 	at com.google.firebase.iid.zzu.then(Unknown Source:4)
W/FirebaseMessagingPlugin(12312): 	at com.google.android.gms.tasks.zzd.run(Unknown Source:5)
W/FirebaseMessagingPlugin(12312): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
W/FirebaseMessagingPlugin(12312): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
W/FirebaseMessagingPlugin(12312): 	at java.lang.Thread.run(Thread.java:784)
V/NativeCrypto(12312): Registering com/google/android/gms/org/conscrypt/NativeCrypto's 284 native methods...
W/com.avl.newapp(12312): Accessing hidden method Ljava/security/spec/ECParameterSpec;->getCurveName()Ljava/lang/String; (light greylist, reflection)
D/NetworkSecurityConfig(12312): No Network Security Config specified, using platform default
I/ProviderInstaller(12312): Installed default security provider GmsCore_OpenSSL
E/        (12312): [ZeroHung]zrhung_get_config: Get config failed for wp[0x0008]
D/ConnectivityManager(12312): requestNetwork and the calling app is: com.avl.newapp
D/ConnectivityManager(12312): requestNetwork and the calling app is: com.avl.newapp
W/com.avl.newapp(12312): Accessing hidden field Ljava/nio/Buffer;->address:J (light greylist, reflection)
Syncing files to device CMR W09...
W/ManagedChannelImpl(12312): [{0}] Failed to resolve name. status={1}
W/Firestore(12312): (18.2.0) [OnlineStateTracker]: Could not reach Cloud Firestore backend. Connection failed 1 times. Most recent error: Status{code=UNAVAILABLE, description=Unable to resolve host firestore.googleapis.com, cause=java.lang.RuntimeException: java.net.UnknownHostException: Unable to resolve host "firestore.googleapis.com": No address associated with hostname
W/Firestore(12312): 	at io.grpc.internal.DnsNameResolver.resolveAll(DnsNameResolver.java:331)
W/Firestore(12312): 	at io.grpc.internal.DnsNameResolver$1.run(DnsNameResolver.java:214)
W/Firestore(12312): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
W/Firestore(12312): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
W/Firestore(12312): 	at java.lang.Thread.run(Thread.java:784)
W/Firestore(12312): Caused by: java.net.UnknownHostException: Unable to resolve host "firestore.googleapis.com": No address associated with hostname
W/Firestore(12312): 	at java.net.Inet6AddressImpl.lookupHostByName(Inet6AddressImpl.java:157)
W/Firestore(12312): 	at java.net.Inet6AddressImpl.lookupAllHostAddr(Inet6AddressImpl.java:105)
W/Firestore(12312): 	at java.net.InetAddress.getAllByName(InetAddress.java:1154)
W/Firestore(12312): 	at io.grpc.internal.DnsNameResolver$JdkAddressResolver.resolveAddress(DnsNameResolver.java:517)
W/Firestore(12312): 	at io.grpc.internal.DnsNameResolver.resolveAll(DnsNameResolver.java:299)
W/Firestore(12312): 	... 4 more
W/Firestore(12312): Caused by: android.system.GaiException: android_getaddrinfo failed: EAI_NODATA (No address associated with hostname)
W/Firestore(12312): 	at libcore.io.Linux.android_getaddrinfo(Native Method)
W/Firestore(12312): 	at libcore.io.BlockGuardOs.android_getaddrinfo(BlockGuardOs.java:172)
W/Firestore(12312): 	at java.net.Inet6AddressImpl.lookupHostByName(Inet6AddressImpl.java:137)
W/Firestore(12312): 	... 8 more
W/Firestore(12312): }
W/Firestore(12312): This typically indicates that your device does not have a healthy Internet connection at the moment. The client will operate in offline mode until it is able to successfully connect to the backend.
I/flutter (12312): null
I/flutter (12312): ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
I/flutter (12312): The following RangeError was thrown building StreamBuilder<QuerySnapshot>(dirty, state:
I/flutter (12312): _StreamBuilderBaseState<QuerySnapshot, AsyncSnapshot<QuerySnapshot>>#f8fd7):
I/flutter (12312): RangeError (index): Invalid value: Valid value range is empty: 0
I/flutter (12312): 
I/flutter (12312): When the exception was thrown, this was the stack:
I/flutter (12312): #0      List.[] (dart:core-patch/growable_array.dart:145:60)
I/flutter (12312): #1      List.elementAt (dart:core-patch/growable_array.dart:351:16)
I/flutter (12312): #2      MyAppState.build.<anonymous closure>.<anonymous closure> (package:new_app/main.dart:113:97)
I/flutter (12312): #3      StreamBuilder.build (package:flutter/src/widgets/async.dart:425:74)
I/flutter (12312): #4      _StreamBuilderBaseState.build (package:flutter/src/widgets/async.dart:125:48)
I/flutter (12312): #5      StatefulElement.build (package:flutter/src/widgets/framework.dart:4012:27)
I/flutter (12312): #6      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3924:15)
I/flutter (12312): #7      Element.rebuild (package:flutter/src/widgets/framework.dart:3721:5)
I/flutter (12312): #8      StatefulElement.update (package:flutter/src/widgets/framework.dart:4085:5)
I/flutter (12312): #9      Element.updateChild (package:flutter/src/widgets/framework.dart:2876:15)
I/flutter (12312): #10     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3935:16)
I/flutter (12312): #11     Element.rebuild (package:flutter/src/widgets/framework.dart:3721:5)
I/flutter (12312): #12     ProxyElement.update (package:flutter/src/widgets/framework.dart:4219:5)
I/flutter (12312): #13     Element.updateChild (package:flutter/src/widgets/framework.dart:2876:15)
I/flutter (12312): #14     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3935:16)
I/flutter (12312): #15     Element.rebuild (package:flutter/src/widgets/framework.dart:3721:5)
I/flutter (12312): #16     StatefulElement.update (package:flutter/src/widgets/framework.dart:4085:5)
I/flutter (12312): #17     Element.updateChild (package:flutter/src/widgets/framework.dart:2876:15)
I/flutter (12312): #18     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3935:16)
I/flutter (12312): #19     Element.rebuild (package:flutter/src/widgets/framework.dart:3721:5)
I/flutter (12312): #20     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2340:33)
I/flutter (12312): #21     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding&WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:700:20)
I/flutter (12312): #22     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:285:5)
I/flutter (12312): #23     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1016:15)
I/flutter (12312): #24     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:958:9)
I/flutter (12312): #25     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.scheduleWarmUpFrame.<anonymous closure> (package:flutter/src/scheduler/binding.dart:784:7)
I/flutter (12312): #34     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:382:19)
I/flutter (12312): #35     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:416:5)
I/flutter (12312): #36     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:12)
I/flutter (12312): (elided 8 frames from package dart:async and package dart:async-patch)
I/flutter (12312): ════════════════════════════════════════════════════════════════════════════════════════════════════
E/flutter (12312): [ERROR:flutter/lib/ui/ui_dart_state.cc(148)] Unhandled Exception: NoSuchMethodError: The method 'ancestorStateOfType' was called on null.
E/flutter (12312): Receiver: null
E/flutter (12312): Tried calling: ancestorStateOfType(Instance of 'TypeMatcher<NavigatorState>')
E/flutter (12312): #0      Object.noSuchMethod (dart:core-patch/object_patch.dart:50:5)
E/flutter (12312): #1      Navigator.of (package:flutter/src/widgets/navigator.dart:1458:19)
E/flutter (12312): #2      SplashState.checkFirstSeen (package:new_app/main.dart:142:17)
E/flutter (12312): #3      _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:77:64)
E/flutter (12312): #4      _rootRunUnary (dart:async/zone.dart:1132:38)
E/flutter (12312): #5      _CustomZone.runUnary (dart:async/zone.dart:1029:19)
E/flutter (12312): #6      _FutureListener.handleValue (dart:async/future_impl.dart:126:18)
E/flutter (12312): #7      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:639:45)
E/flutter (12312): #8      Future._propagateToListeners (dart:async/future_impl.dart:668:32)
E/flutter (12312): #9      Future._complete (dart:async/future_impl.dart:473:7)
E/flutter (12312): #10     _SyncCompleter.complete (dart:async/future_impl.dart:51:12)
E/flutter (12312): #11     _AsyncAwaitCompleter.complete.<anonymous closure> (dart:async-patch/async_patch.dart:33:20)
E/flutter (12312): #12     _rootRun (dart:async/zone.dart:1120:38)
E/flutter (12312): #13     _CustomZone.run (dart:async/zone.dart:1021:19)
E/flutter (12312): #14     _CustomZone.runGuarded (dart:async/zone.dart:923:7)
E/flutter (12312): #15     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:963:23)
E/flutter (12312): #16     _rootRun (dart:async/zone.dart:1124:13)
E/flutter (12312): #17     _CustomZone.run (dart:async/zone.dart:1021:19)
E/flutter (12312): #18     _CustomZone.runGuarded (dart:async/zone.dart:923:7)
E/flutter (12312): #19     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:963:23)
E/flutter (12312): #20     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
E/flutter (12312): #21     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
E/flutter (12312): 
E/flutter (12312): [ERROR:flutter/lib/ui/ui_dart_state.cc(148)] Unhandled Exception: type 'QuerySnapshot' is not a subtype of type 'DocumentSnapshot'
E/flutter (12312): #0      new PushNotificationBloc.<anonymous closure>.<anonymous closure> (package:new_app/blocs/push_notification_bloc.dart:14:109)
E/flutter (12312): #1      _rootRunUnary (dart:async/zone.dart:1132:38)
E/flutter (12312): #2      _CustomZone.runUnary (dart:async/zone.dart:1029:19)
E/flutter (12312): #3      _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
E/flutter (12312): #4      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
E/flutter (12312): #5      _DelayedData.perform (dart:async/stream_impl.dart:591:14)
E/flutter (12312): #6      _StreamImplEvents.handleNext (dart:async/stream_impl.dart:707:11)
E/flutter (12312): #7      _PendingEvents.schedule.<anonymous closure> (dart:async/stream_impl.dart:667:7)
E/flutter (12312): #8      _rootRun (dart:async/zone.dart:1120:38)
E/flutter (12312): #9      _CustomZone.run (dart:async/zone.dart:1021:19)
E/flutter (12312): #10     _CustomZone.runGuarded (dart:async/zone.dart:923:7)
E/flutter (12312): #11     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:963:23)
E/flutter (12312): #12     _rootRun (dart:async/zone.dart:1124:13)
E/flutter (12312): #13     _CustomZone.run (dart:async/zone.dart:1021:19)
E/flutter (12312): #14     _CustomZone.runGuarded (dart:async/zone.dart:923:7)
E/flutter (12312): #15     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:963:23)
E/flutter (12312): #16     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
E/flutter (12312): #17     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
E/flutter (12312): 
E/flutter (12312): [ERROR:flutter/lib/ui/ui_dart_state.cc(148)] Unhandled Exception: type 'QuerySnapshot' is not a subtype of type 'DocumentSnapshot'
E/flutter (12312): #0      new PushNotificationBloc.<anonymous closure>.<anonymous closure> (package:new_app/blocs/push_notification_bloc.dart:14:109)
E/flutter (12312): #1      _rootRunUnary (dart:async/zone.dart:1132:38)
E/flutter (12312): #2      _CustomZone.runUnary (dart:async/zone.dart:1029:19)
E/flutter (12312): #3      _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
E/flutter (12312): #4      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
E/flutter (12312): #5      _DelayedData.perform (dart:async/stream_impl.dart:591:14)
E/flutter (12312): #6      _StreamImplEvents.handleNext (dart:async/stream_impl.dart:707:11)
E/flutter (12312): #7      _PendingEvents.schedule.<anonymous closure> (dart:async/stream_impl.dart:667:7)
E/flutter (12312): #8      _rootRun (dart:async/zone.dart:1120:38)
E/flutter (12312): #9      _CustomZone.run (dart:async/zone.dart:1021:19)
E/flutter (12312): #10     _CustomZone.runGuarded (dart:async/zone.dart:923:7)
E/flutter (12312): #11     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:963:23)
E/flutter (12312): #12     _rootRun (dart:async/zone.dart:1124:13)
E/flutter (12312): #13     _CustomZone.run (dart:async/zone.dart:1021:19)
E/flutter (12312): #14     _CustomZone.runGuarded (dart:async/zone.dart:923:7)
E/flutter (12312): #15     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:963:23)
E/flutter (12312): #16     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
E/flutter (12312): #17     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
E/flutter (12312): 
W/ManagedChannelImpl(12312): [{0}] Failed to resolve name. status={1}
W/ManagedChannelImpl(12312): [{0}] Failed to resolve name. status={1}
D/AwareBitmapCacher(12312): handleInit switch not opened pid=12312
W/ManagedChannelImpl(12312): [{0}] Failed to resolve name. status={1}
W/ManagedChannelImpl(12312): [{0}] Failed to resolve name. status={1}
W/ManagedChannelImpl(12312): [{0}] Failed to resolve name. status={1}
W/ManagedChannelImpl(12312): [{0}] Failed to resolve name. status={1}
```

Flutter doctor is this:

```
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, v1.7.8+hotfix.4, on Microsoft Windows [Version 10.0.16299.1268], locale de-DE)
[!] Android toolchain - develop for Android devices (Android SDK version 29.0.0-rc3)
    X Android license status unknown.
      Try re-installing or updating your Android SDK Manager.
      See https://developer.android.com/studio/#downloads or visit https://flutter.dev/setup/#android-setup for detailed instructions.
[√] Android Studio (version 3.4)
[√] Proxy Configuration
[√] Connected device (2 available)

! Doctor found issues in 1 category.
```

**Comment by kushtra24** [comment]
OK, It seems that if the device is not connected to the internet and has Firebase on it. It gets this error, My question is there any exception handling I can do there?

**Comment by kroikie** [comment]
@kushtra24

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/351. Any further collaboration will be done there.
