### ISSUE TITLE
EXCEPTION CAUGHT BY GESTURE 

### ISSUE THREAD

**Issue by mostafa2142** [flutter/flutter#37476]
So Im New With Flutter And Im Trying to have Http Request  And I get This Error And I CANT figured out what does it mean 
```
Error I Get : 
I/flutter ( 7259): ══╡ EXCEPTION CAUGHT BY GESTURE ╞═══════════════════════════════════════════════════════════════════
I/flutter ( 7259): The following assertion was thrown while handling a gesture:
I/flutter ( 7259): setState() callback argument returned a Future.
I/flutter ( 7259): The setState() method on _LoginState#e5014 was called with a closure or method that returned a
I/flutter ( 7259): Future. Maybe it is marked as "async".
I/flutter ( 7259): Instead of performing asynchronous work inside a call to setState(), first execute the work (without
I/flutter ( 7259): updating the widget state), and then synchronously update the state inside a call to setState().
I/flutter ( 7259): 
I/flutter ( 7259): When the exception was thrown, this was the stack:
I/flutter ( 7259): #0      State.setState.<anonymous closure> (package:flutter/src/widgets/framework.dart:1144:9)
I/flutter ( 7259): #1      State.setState (package:flutter/src/widgets/framework.dart:1160:6)
I/flutter ( 7259): #2      _LoginState.build.<anonymous closure> (package:testflutter/main.dart:111:25)
I/flutter ( 7259): #3      _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:635:14)
I/flutter ( 7259): #4      _InkResponseState.build.<anonymous closure> (package:flutter/src/material/ink_well.dart:711:32)
I/flutter ( 7259): #5      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:182:24)
I/flutter ( 7259): #6      TapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:365:11)
I/flutter ( 7259): #7      TapGestureRecognizer.acceptGesture (package:flutter/src/gestures/tap.dart:312:7)
I/flutter ( 7259): #8      GestureArenaManager.sweep (package:flutter/src/gestures/arena.dart:156:27)
I/flutter ( 7259): #9      _WidgetsFlutterBinding&BindingBase&GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:222:20)
I/flutter ( 7259): #10     _WidgetsFlutterBinding&BindingBase&GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:198:22)
I/flutter ( 7259): #11     _WidgetsFlutterBinding&BindingBase&GestureBinding._handlePointerEvent (package:flutter/src/gestures/binding.dart:156:7)
I/flutter ( 7259): #12     _WidgetsFlutterBinding&BindingBase&GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:102:7)
I/flutter ( 7259): #13     _WidgetsFlutterBinding&BindingBase&GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:86:7)
I/flutter ( 7259): #17     _invoke1 (dart:ui/hooks.dart:250:10)
I/flutter ( 7259): #18     _dispatchPointerDataPacket (dart:ui/hooks.dart:159:5)
I/flutter ( 7259): (elided 3 frames from package dart:async)
```
My Code : 

```
import 'dart:async';
import 'dart:convert';
import 'package:flutter/material.dart';
import 'package:http/http.dart' as http;
import 'package:shared_preferences/shared_preferences.dart';

import 'SecondPage.dart';

void main() {
  runApp(MaterialApp(
    title: "Login",
    home: Login(),
  ));
}

class Login extends StatefulWidget {
  @override
  _LoginState createState() => _LoginState();
}

class _LoginState extends State<Login> {
  Map list = {};

  TextEditingController _usernameController = new TextEditingController();
  TextEditingController _passwordController = new TextEditingController();

  @override
  void initState() {
    // TODO: implement initState
    super.initState();
    debugPrint("Init State");
    setsharedprefences();
  }

  String a, b;

  SharedPreferences preferences;

  setsharedprefences() async {
    preferences = await SharedPreferences.getInstance();
    setState(() {
      a = preferences.getString("username");
      b = preferences.getString("password");
    });
  }

  storedate() {
    preferences.setString("username", _usernameController.text);
    preferences.setString("password", _passwordController.text);
  }

  String msg = '';

  void getJson() async {
    print("Here is Working 1");

    list = await SendHttpRequest();
    print(list);
    print("Here is Working 2");

    if (list['error'] == true) {
      setState(() {
        msg = "Your Username Or your Password is Wrong";
      });
//      dialog(context, "Error Is :"+list['error'].toString(),list['MSG']);

    } else {

      Navigator.pushReplacement(context, MaterialPageRoute(builder: (context) {
        return SecondPage();
      }));


    }
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text("Login"),
        centerTitle: true,
        backgroundColor: Colors.amberAccent,
      ),
      body: ListView(
        children: <Widget>[
          Container(
              margin: EdgeInsets.all(20.0),
              child: Column(
                children: <Widget>[
                  TextField(
                    controller: _usernameController,
                    decoration: InputDecoration(
                      icon: Icon(Icons.verified_user),
                      labelText: "UserName",
                      hintText: "Enter Your UserName",
                    ),
                  ),
                  TextField(
                    controller: _passwordController,
                    decoration: InputDecoration(
                      icon: Icon(Icons.lock),
                      labelText: "Password",
                      hintText: "Enter Your Password",
                    ),
                  ),
                  RaisedButton(
                      child: Text("Login"),
                      onPressed: () {
                        setState(() async {
                          getJson();
                          storedate();
                        });
                      }),
                  Text('$msg'),
                  Text('$a'),
                  Text('$b'),
                ],
              ))
        ],
      ),
    );
  }

  Future<Map> SendHttpRequest() async {
    String url =
        "CENSORED";

    http.Response response = await http.post(url, body: {
      "username": _usernameController.text,
      "password": _passwordController.text,
    });
    print(response.statusCode);

    return json.decode(response.body);
  }
}

dialog(BuildContext Context, String Msg, String bool) {
  var alert = AlertDialog(
    title: Text(Msg),
    content: Text(bool),
    actions: <Widget>[
      RaisedButton(
        color: Colors.black,
        onPressed: () {
          Navigator.pop(Context);
        },
        child: Text(
          "Ok",
          style: TextStyle(color: Colors.white),
        ),
      )
    ],
  );
  return showDialog(
      context: Context,
      builder: (Context) {
        return alert;
      });
}
```

**Comment by Lucas0Braz** [comment]
What do you have in the class SharedPreferences? It is a model ?

**Comment by BondarenkoStas** [comment]
This is a question better suited for StackOverflow, since there doesn’t seem to be anything wrong with Flutter itself. Closing, as this is not an issue report. See https://flutter.dev/community for support options.
If you disagree, feel free to comment and I will reopen the issue.
