### ISSUE TITLE
Crash on android build and inconsistently after flutter upgrade 

### ISSUE THREAD

**Issue by lifenautjoe** [flutter/flutter#37487]
## Steps to Reproduce

1. Do flutter upgrade on latest stable channel
2. Update all dependenices
3. Observe the app run sometimes, other times crash, other times run and then crash in between.

## Logs

**The logs I've managed to get from one of these inconsistent occasions**

```
Launching lib/main.dart on Android SDK built for x86 in debug mode...
Initializing gradle...
Resolving dependencies...
Running Gradle task 'assembleDevelopmentDebug'...
Built build/app/outputs/apk/development/debug/app-development-debug.apk.
Installing build/app/outputs/apk/app.apk...
W/penbook.app.de(11918): Accessing hidden method Landroid/view/accessibility/AccessibilityNodeInfo;->getSourceNodeId()J (light greylist, reflection)
W/penbook.app.de(11918): Accessing hidden method Landroid/view/accessibility/AccessibilityRecord;->getSourceNodeId()J (light greylist, reflection)
W/penbook.app.de(11918): Accessing hidden field Landroid/view/accessibility/AccessibilityNodeInfo;->mChildNodeIds:Landroid/util/LongArray; (light greylist, reflection)
W/penbook.app.de(11918): Accessing hidden method Landroid/util/LongArray;->get(I)J (light greylist, reflection)
I/OpenGLRenderer(11918): Initialized EGL, version 1.4
D/OpenGLRenderer(11918): Swap behavior 1
D/        (11918): HostConnection::get() New Host Connection established 0xe6852e80, tid 11966
W/OpenGLRenderer(11918): Failed to choose config with EGL_SWAP_BEHAVIOR_PRESERVED, retrying without...
D/OpenGLRenderer(11918): Swap behavior 0
D/EGL_emulation(11918): eglCreateContext: 0xe4a858a0: maj 3 min 0 rcv 3
D/EGL_emulation(11918): eglMakeCurrent: 0xe4a858a0: ver 3 0 (tinfo 0xcc15bdd0)
D/        (11918): HostConnection::get() New Host Connection established 0xe3070c00, tid 11949
D/EGL_emulation(11918): eglCreateContext: 0xcfb246c0: maj 3 min 0 rcv 3
D/EGL_emulation(11918): eglMakeCurrent: 0xcfb246c0: ver 3 0 (tinfo 0xcfb43030)
I/flutter (11918): Setting localisation service with en
I/Choreographer(11918): Skipped 60 frames!  The application may be doing too much work on its main thread.
D/EGL_emulation(11918): eglMakeCurrent: 0xe4a858a0: ver 3 0 (tinfo 0xcc15bdd0)
I/OpenGLRenderer(11918): Davey! duration=1124ms; Flags=1, IntendedVsync=13986055395862, Vsync=13987055395822, OldestInputEvent=9223372036854775807, NewestInputEvent=0, HandleInputStart=13987065570482, AnimationStart=13987065642482, PerformTraversalsStart=13987065668482, DrawStart=13987071012482, SyncQueued=13987072522482, SyncStart=13987074469482, IssueDrawCommandsStart=13987074636482, SwapBuffers=13987144739482, FrameCompleted=13987182305482, DequeueBufferDuration=25613000, QueueBufferDuration=424000, 
W/SoundPool(11918): Use of stream types is deprecated for operations other than volume control
W/SoundPool(11918): See the documentation of SoundPool() for what to use instead with android.media.AudioAttributes to qualify your playback use case
W/Glide   (11918): Failed to find GeneratedAppGlideModule. You should include an annotationProcessor compile dependency on com.github.bumptech.glide:compiler in your application and a @GlideModule annotated AppGlideModule implementation or LibraryGlideModules will be silently ignored
I/OMXClient(11918): IOmx service obtained
D/NetworkSecurityConfig(11918): No Network Security Config specified, using platform default
W/penbook.app.de(11918): Accessing hidden method Ldalvik/system/CloseGuard;->get()Ldalvik/system/CloseGuard; (light greylist, reflection)
W/penbook.app.de(11918): Accessing hidden method Ldalvik/system/CloseGuard;->open(Ljava/lang/String;)V (light greylist, reflection)
W/penbook.app.de(11918): Accessing hidden method Ldalvik/system/CloseGuard;->warnIfOpen()V (light greylist, reflection)
W/Intercom realtime(11918): No realtime endpoints present so we can't connect
I/Choreographer(11918): Skipped 33 frames!  The application may be doing too much work on its main thread.
I/OMXClient(11918): IOmx service obtained
I/OMXClient(11918): IOmx service obtained
I/OMXClient(11918): IOmx service obtained
D/EGL_emulation(11918): eglMakeCurrent: 0xcfb246c0: ver 3 0 (tinfo 0xcfb43030)
W/Intercom realtime(11918): No realtime endpoints present so we can't connect
Syncing files to device Android SDK built for x86...
W/penbook.app.de(11918): Accessing hidden method Lcom/android/org/conscrypt/OpenSSLSocketImpl;->setAlpnProtocols([B)V (light greylist, reflection)
D/FirebaseApp(11918): com.google.firebase.auth.FirebaseAuth is not linked. Skipping initialization.
W/penbook.app.de(11918): Accessing hidden method Lcom/android/org/conscrypt/OpenSSLSocketImpl;->getAlpnSelectedProtocol()[B (light greylist, reflection)
D/FirebaseInstanceId(11918): topic sync succeeded
W/penbook.app.de(11918): Long monitor contention with owner OS_REG_USER (12081) at long android.content.res.ApkAssets.nativeLoad(java.lang.String, boolean, boolean, boolean)(ApkAssets.java:-2) waiters=0 in android.view.Display android.app.ResourcesManager.getAdjustedDisplay(int, android.content.res.Resources) for 552ms
E/AndroidRuntime(11918): FATAL EXCEPTION: OSH_NetworkHandlerThread
E/AndroidRuntime(11918): Process: social.openbook.app.dev, PID: 11918
E/AndroidRuntime(11918): java.lang.RuntimeException: Methods marked with @UiThread must be executed on the main thread. Current thread: OSH_NetworkHandlerThread
E/AndroidRuntime(11918): 	at io.flutter.embedding.engine.FlutterJNI.ensureRunningOnMainThread(FlutterJNI.java:794)
E/AndroidRuntime(11918): 	at io.flutter.embedding.engine.FlutterJNI.invokePlatformMessageResponseCallback(FlutterJNI.java:727)
E/AndroidRuntime(11918): 	at io.flutter.embedding.engine.dart.DartMessenger$Reply.reply(DartMessenger.java:140)
E/AndroidRuntime(11918): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler$1.success(MethodChannel.java:225)
E/AndroidRuntime(11918): 	at com.onesignal.flutter.OSFlutterChangeTagsHandler.onSuccess(OneSignalTagsController.java:43)
E/AndroidRuntime(11918): 	at com.onesignal.UserStateSynchronizer.internalSyncUserState(UserStateSynchronizer.java:196)
E/AndroidRuntime(11918): 	at com.onesignal.UserStateSynchronizer.syncUserState(UserStateSynchronizer.java:170)
E/AndroidRuntime(11918): 	at com.onesignal.UserStateSynchronizer$NetworkHandlerThread$1.run(UserStateSynchronizer.java:77)
E/AndroidRuntime(11918): 	at android.os.Handler.handleCallback(Handler.java:873)
E/AndroidRuntime(11918): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/AndroidRuntime(11918): 	at android.os.Looper.loop(Looper.java:193)
E/AndroidRuntime(11918): 	at android.os.HandlerThread.run(HandlerThread.java:65)
I/Process (11918): Sending signal. PID: 11918 SIG: 9
Application finished.
```

**Flutter doctor output**

```
[✓] Flutter (Channel stable, v1.7.8+hotfix.4, on Mac OS X 10.14.6 18G84, locale
    en-NL)
    • Flutter version 1.7.8+hotfix.4 at
      /Users/lifenautjoe/Documents/code/libraries/flutter
    • Framework revision 20e59316b8 (2 weeks ago), 2019-07-18 20:04:33 -0700
    • Engine revision fee001c93f
    • Dart version 2.4.0


[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/lifenautjoe/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling
      support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 10.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.2, Build version 10E125
    • CocoaPods version 1.7.5

[✓] iOS tools - develop for iOS devices
    • ios-deploy 1.9.4

[✓] Android Studio (version 3.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 33.4.1
    • Dart plugin version 182.5215
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)

[✓] IntelliJ IDEA Ultimate Edition (version 2018.3.5)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 33.3.2
    • Dart plugin version 183.5912.23

[✓] Connected device (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 9 (API 28)
      (emulator)
```

**Comment by lifenautjoe** [comment]
An issue of the onesignal library. Didn't notice until someone else pointed out the logs, my bad, sorry.
