### ISSUE TITLE
Shared_prefereneces giving gradle error

### ISSUE THREAD

**Issue by Deepavsp** [flutter/flutter#37557]
I'm using shared_preferences ^0.5.3+4 in my flutter project. When trying to run the app, I'm getting the following gradle error.

```
Launching lib\main.dart on LLD AL20 in debug mode...
Initializing gradle...
Resolving dependencies...
* Error running Gradle:
ProcessException: Process "C:\Users\Deepa\table_app\android\gradlew.bat" exited abnormally:

> Configure project :shared_preferences

Project evaluation failed including an error in afterEvaluate {}. Run with --stacktrace for details of the afterEvaluate {} error.

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':shared_preferences'.
> Could not resolve all artifacts for configuration ':shared_preferences:classpath'.
   > Could not download builder.jar (com.android.tools.build:builder:3.4.0)
      > Could not get resource 'https://dl.google.com/dl/android/maven2/com/android/tools/build/builder/3.4.0/builder-3.4.0.jar'.
         > Premature end of Content-Length delimited message body (expected: 31027880; received: 4456416
   > Could not download bundletool.jar (com.android.tools.build:bundletool:0.7.2)
      > Could not get resource 'https://dl.google.com/dl/android/maven2/com/android/tools/build/bundletool/0.7.2/bundletool-0.7.2.jar'.
         > Premature end of Content-Length delimited message body (expected: 5039840; received: 4456416

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 12m 40s
  Command: C:\Users\Deepa\table_app\android\gradlew.bat app:properties

Finished with error: Please review your Gradle project setup in the android/ folder.

```
      
Output of  `flutter run --verbose` 

```
[  +40 ms] executing: [C:\flutter\] git log -n 1 --pretty=format:%H
[ +129 ms] Exit code 0 from: git log -n 1 --pretty=format:%H
[   +7 ms] 20e59316b8b8474554b38493b8ca888794b0234a
[   +2 ms] executing: [C:\flutter\] git describe --match v*.*.* --first-parent --long --tags
[  +83 ms] Exit code 0 from: git describe --match v*.*.* --first-parent --long --tags
[   +2 ms] v1.7.8+hotfix.4-0-g20e59316b
[  +33 ms] executing: [C:\flutter\] git rev-parse --abbrev-ref --symbolic @{u}
[ +112 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[   +7 ms] origin/stable
[   +3 ms] executing: [C:\flutter\] git ls-remote --get-url origin
[ +120 ms] Exit code 0 from: git ls-remote --get-url origin
[   +5 ms] https://github.com/flutter/flutter.git
[ +162 ms] executing: [C:\flutter\] git rev-parse --abbrev-ref HEAD
[  +41 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[   +2 ms] stable
[  +63 ms] executing: C:\Users\Deepa\AppData\Local\Android\sdk\platform-tools\adb.exe devices -l
[  +33 ms] Exit code 0 from: C:\Users\Deepa\AppData\Local\Android\sdk\platform-tools\adb.exe devices -l
[   +2 ms] List of devices attached
           BRB3Y18614008282       device product:LLD-AL20 model:LLD_AL20 device:HWLLD-H2 transport_id:7
           emulator-5554          device product:sdk_gphone_x86 model:Android_SDK_built_for_x86 device:generic_x86
           transport_id:3
[  +23 ms] C:\Users\Deepa\AppData\Local\Android\sdk\platform-tools\adb.exe -s BRB3Y18614008282 shell getprop
[ +196 ms] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[  +14 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[   +3 ms] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[   +5 ms] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[   +3 ms] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[   +3 ms] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[ +118 ms] Found plugin shared_preferences at C:\flutter\.pub-cache\hosted\pub.dartlang.org\shared_preferences-0.5.3+4\
[ +170 ms] Found plugin shared_preferences at C:\flutter\.pub-cache\hosted\pub.dartlang.org\shared_preferences-0.5.3+4\
[  +47 ms] ro.hardware = hi6250
[   +3 ms] ro.build.characteristics = default
[  +29 ms] Launching lib/main.dart on LLD AL20 in debug mode...
[  +29 ms] Initializing gradle...
[   +5 ms] Using gradle from C:\Users\Deepa\table_app\android\gradlew.bat.
[ +452 ms] executing: C:\Users\Deepa\table_app\android\gradlew.bat -v
[+2550 ms]
                    ------------------------------------------------------------
                    Gradle 4.10.2
                    ------------------------------------------------------------

                    Build time:   2018-09-19 18:10:15 UTC
                    Revision:     b4d8d5d170bb4ba516e88d7fe5647e2323d791dd

                    Kotlin DSL:   1.0-rc-6
                    Kotlin:       1.2.61
                    Groovy:       2.4.15
                    Ant:          Apache Ant(TM) version 1.9.11 compiled on March 23 2018
                    JVM:          1.8.0_152-release (JetBrains s.r.o 25.152-b01)
                    OS:           Windows 10 10.0 amd64
[  +16 ms] Initializing gradle... (completed in 3.0s)
[   +2 ms] Resolving dependencies...
[   +1 ms] executing: [C:\Users\Deepa\table_app\android\] C:\Users\Deepa\table_app\android\gradlew.bat app:properties
[+587662 ms]
                      > Configure project :shared_preferences

                      Project evaluation failed including an error in afterEvaluate {}. Run with --stacktrace for
                      details of the afterEvaluate {} error.

                      FAILURE: Build failed with an exception.

                      * What went wrong:
                      A problem occurred configuring project ':shared_preferences'.
                      > Could not resolve all artifacts for configuration ':shared_preferences:classpath'.
                         > Could not download builder.jar (com.android.tools.build:builder:3.4.0)
                            > Could not get resource
                            'https://dl.google.com/dl/android/maven2/com/android/tools/build/builder/3.4.0/builder-3.4.0                            .jar'.
                               > Premature end of Content-Length delimited message body (expected: 31027880; received:
                               4456416
                         > Could not download bundletool.jar (com.android.tools.build:bundletool:0.7.2)
                            > Could not get resource
                            'https://dl.google.com/dl/android/maven2/com/android/tools/build/bundletool/0.7.2/bundletool                            -0.7.2.jar'.
                               > Premature end of Content-Length delimited message body (expected: 5039840; received:
                               2359280

                      * Try:
                      Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more                      log output. Run with --scan to get full insights.

                      * Get more help at https://help.gradle.org

                      BUILD FAILED in 9m 46s
[  +76 ms] Resolving dependencies... (completed in 587.7s, longer than expected)
[  +25 ms] * Error running Gradle:
           ProcessException: Process "C:\Users\Deepa\table_app\android\gradlew.bat" exited abnormally:

           > Configure project :shared_preferences

           Project evaluation failed including an error in afterEvaluate {}. Run with --stacktrace for details of the
afterEvaluate
           {} error.

           FAILURE: Build failed with an exception.

           * What went wrong:
           A problem occurred configuring project ':shared_preferences'.
           > Could not resolve all artifacts for configuration ':shared_preferences:classpath'.
              > Could not download builder.jar (com.android.tools.build:builder:3.4.0)
                 > Could not get resource
                 'https://dl.google.com/dl/android/maven2/com/android/tools/build/builder/3.4.0/builder-3.4.0.jar'.
                    > Premature end of Content-Length delimited message body (expected: 31027880; received: 4456416
              > Could not download bundletool.jar (com.android.tools.build:bundletool:0.7.2)
                 > Could not get resource

'https://dl.google.com/dl/android/maven2/com/android/tools/build/bundletool/0.7.2/bundletool-0.7.2.jar'.
                    > Premature end of Content-Length delimited message body (expected: 5039840; received: 2359280

           * Try:
           Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log
output. Run with
           --scan to get full insights.

           * Get more help at https://help.gradle.org

           BUILD FAILED in 9m 46s
             Command: C:\Users\Deepa\table_app\android\gradlew.bat app:properties

[  +45 ms] "flutter run" took 5,91,554ms.
[   +5 ms] "flutter run" took 5,91,554ms.
Please review your Gradle project setup in the android/ folder.

#0      throwToolExit (package:flutter_tools/src/base/common.dart:28:3)
#1      _readGradleProject (package:flutter_tools/src/android/gradle.dart:158:7)
<asynchronous suspension>
#2      _gradleProject (package:flutter_tools/src/android/gradle.dart:111:34)
<asynchronous suspension>
#3      getGradleAppOut (package:flutter_tools/src/android/gradle.dart:105:29)
<asynchronous suspension>
#4      AndroidApk.fromAndroidProject (package:flutter_tools/src/application_package.dart:160:23)
<asynchronous suspension>
#5      ApplicationPackageFactory.getPackageForPlatform (package:flutter_tools/src/application_package.dart:47:32)
<asynchronous suspension>
#6      FlutterDevice.runHot (package:flutter_tools/src/resident_runner.dart:352:56)
<asynchronous suspension>
#7      HotRunner.run (package:flutter_tools/src/run_hot.dart:251:39)
<asynchronous suspension>
#8      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:469:37)
<asynchronous suspension>
#9      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:478:18)
<asynchronous suspension>
#10     FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:383:33)
<asynchronous suspension>
#11     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:29)
<asynchronous suspension>
#12     _rootRun (dart:async/zone.dart:1124:13)
#13     _CustomZone.run (dart:async/zone.dart:1021:19)
#14     _runZoned (dart:async/zone.dart:1516:10)
#15     runZoned (dart:async/zone.dart:1463:12)
#16     AppContext.run (package:flutter_tools/src/base/context.dart:152:18)
<asynchronous suspension>
#17     FlutterCommand.run (package:flutter_tools/src/runner/flutter_command.dart:375:20)
#18     CommandRunner.runCommand (package:args/command_runner.dart:197:27)
<asynchronous suspension>
#19     FlutterCommandRunner.runCommand.<anonymous closure>
(package:flutter_tools/src/runner/flutter_command_runner.dart:396:21)
<asynchronous suspension>
#20     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:29)
<asynchronous suspension>
#21     _rootRun (dart:async/zone.dart:1124:13)
#22     _CustomZone.run (dart:async/zone.dart:1021:19)
#23     _runZoned (dart:async/zone.dart:1516:10)
#24     runZoned (dart:async/zone.dart:1463:12)
#25     AppContext.run (package:flutter_tools/src/base/context.dart:152:18)
<asynchronous suspension>
#26     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:356:19)
<asynchronous suspension>
#27     CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:112:25)
#28     new Future.sync (dart:async/future.dart:224:31)
#29     CommandRunner.run (package:args/command_runner.dart:112:14)
#30     FlutterCommandRunner.run (package:flutter_tools/src/runner/flutter_command_runner.dart:242:18)
#31     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:62:22)
<asynchronous suspension>
#32     _rootRun (dart:async/zone.dart:1124:13)
#33     _CustomZone.run (dart:async/zone.dart:1021:19)
#34     _runZoned (dart:async/zone.dart:1516:10)
#35     runZoned (dart:async/zone.dart:1500:12)
#36     run.<anonymous closure> (package:flutter_tools/runner.dart:60:18)
<asynchronous suspension>
#37     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:29)
<asynchronous suspension>
#38     _rootRun (dart:async/zone.dart:1124:13)
#39     _CustomZone.run (dart:async/zone.dart:1021:19)
#40     _runZoned (dart:async/zone.dart:1516:10)
#41     runZoned (dart:async/zone.dart:1463:12)
#42     AppContext.run (package:flutter_tools/src/base/context.dart:152:18)
<asynchronous suspension>
#43     runInContext (package:flutter_tools/src/context_runner.dart:56:24)
<asynchronous suspension>
#44     run (package:flutter_tools/runner.dart:51:10)
#45     main (package:flutter_tools/executable.dart:62:9)
<asynchronous suspension>
#46     main (file:///C:/b/s/w/ir/k/archive/flutter/packages/flutter_tools/bin/flutter_tools.dart:8:3)
#47     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:299:32)
#48     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:12)
```

     output of flutter analyze

```
Running "flutter pub get" in table_app...                           1.5s
Analyzing table_app...

   info - Unused import: 'package:dots_indicator/dots_indicator.dart' - lib\on_board_page.dart:2:8 - unused_import

1 issue found. (ran in 31.6s)
```

 Output of  `flutter doctor -v` here

```
Flutter (Channel stable, v1.7.8+hotfix.4, on Microsoft Windows [Version 10.0.17763.292], locale en-IN)
    • Flutter version 1.7.8+hotfix.4 at C:\flutter
    • Framework revision 20e59316b8 (2 weeks ago), 2019-07-18 20:04:33 -0700
    • Engine revision fee001c93f
    • Dart version 2.4.0


[√] Android toolchain - develop for Android devices (Android SDK version 29.0.1)
    • Android SDK at C:\Users\Deepa\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.1
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
    • All Android licenses accepted.

[√] Android Studio (version 3.4)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 38.1.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

[!] VS Code (version 1.36.1)
    • VS Code at C:\Users\Deepa\AppData\Local\Programs\Microsoft VS Code
    X Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[√] Connected device (2 available)
    • LLD AL20                  • BRB3Y18614008282 • android-arm64 • Android 8.0.0 (API 26)
    • Android SDK built for x86 • emulator-5554    • android-x86   • Android 8.0.0 (API 26) (emulator)

! Doctor found issues in 1 category.
```

**Comment by jatinjain001** [comment]
how you solve it further , I m also having same error
