### ISSUE TITLE
Cloud Firestore An error occurred while executing doInBackground() (AsyncTask$3.done)

### ISSUE THREAD

**Issue by creativecreatorormaybenot** [flutter/flutter#37569]
```
FATAL EXCEPTION: AsyncTask #3
Process: app, PID: 15840
java.lang.RuntimeException: An error occurred while executing doInBackground()
	at android.os.AsyncTask$3.done(AsyncTask.java:354)
	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383)
	at java.util.concurrent.FutureTask.setException(FutureTask.java:252)
	at java.util.concurrent.FutureTask.run(FutureTask.java:271)
	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:245)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:764)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'com.google.firebase.firestore.ak com.google.firebase.firestore.ak.a(com.google.firebase.firestore.d, java.lang.Object)' on a null object reference
	at io.flutter.plugins.firebase.cloudfirestore.CloudFirestorePlugin$7.doInBackground(Unknown Source:20)
	at io.flutter.plugins.firebase.cloudfirestore.CloudFirestorePlugin$7.doInBackground(Unknown Source:2)
	at android.os.AsyncTask$2.call(AsyncTask.java:333)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	... 4 more
```

I am getting this error from quite a few clients. #27840 and [this source](https://stackoverflow.com/q/50280256/6509751) suggest that this is an issue related to having different instances of Cloud Firestore with different configurations.  
However, this should not be the case for me as I use `Firestore.instance` everywhere.

I figured that I might try to store a **single Firestore object** in my whole app and see if this resolves the issue, i.e. rather than calling `Firestore.instance` in different places, I only call it once.

## Edit

What I mentioned above **does not fix** the issue and I am seeing this crash very frequently now.

Another edit: I encountered this on an Android Q emulator now, i.e. right after start up. I encounter it **every time** I clear the storage and start up the app.

Another one: I am seeing this on live devices now as well (always got this in Play Store pre-launch reports), and the pattern I am seeing is that it happens  on `Pixel 2` devices. I think that I saw some other devices with it at some point, but I see it a lot on `Pixel 2`'s.

**Comment by kroikie** [comment]
@creativecreatorormaybenot

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/1208. Any further collaboration will be done there.
