### ISSUE TITLE
HttpException: HttpException: , uri = https://storage.googleapis.com/flutter_infra/flutter/c8f4f5d5ccfc7c0e031cb688adae7f75e076f363/android-arm-release/windows-x64.zip

### ISSUE THREAD

**Issue by Kevin088** [flutter/flutter#37575]
## command
```
flutter doctor
```
## exception
```
HttpException: HttpException: , uri = https://storage.googleapis.com/flutter_infra/flutter/c8f4f5d5ccfc7c0e031cb688adae7f75e076f363/android-arm-release/windows-x64.zip
```
```
#0      _attempt (package:flutter_tools/src/base/net.dart:71:39)
<asynchronous suspension>
#1      fetchUrl (package:flutter_tools/src/base/net.dart:22:36)
<asynchronous suspension>
#2      _downloadFile (package:flutter_tools/src/cache.dart:1028:37)
<asynchronous suspension>
#3      CachedArtifact._downloadArchive.<anonymous closure> (package:flutter_tools/src/cache.dart:444:17)
<asynchronous suspension>
#4      CachedArtifact._withDownloadFile (package:flutter_tools/src/cache.dart:473:26)
<asynchronous suspension>
#5      CachedArtifact._downloadArchive (package:flutter_tools/src/cache.dart:440:12)
#6      CachedArtifact._downloadZipArchive (package:flutter_tools/src/cache.dart:460:12)
#7      EngineCachedArtifact.updateInner (package:flutter_tools/src/cache.dart:607:13)
<asynchronous suspension>
#8      CachedArtifact.update (package:flutter_tools/src/cache.dart:403:11)
<asynchronous suspension>
#9      Cache.updateAll (package:flutter_tools/src/cache.dart:324:26)
<asynchronous suspension>
#10     FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:470:19)
<asynchronous suspension>
#11     FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:407:33)
<asynchronous suspension>
#12     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:154:29)
<asynchronous suspension>
#13     _rootRun (dart:async/zone.dart:1124:13)
#14     _CustomZone.run (dart:async/zone.dart:1021:19)
#15     _runZoned (dart:async/zone.dart:1516:10)
#16     runZoned (dart:async/zone.dart:1463:12)
#17     AppContext.run (package:flutter_tools/src/base/context.dart:153:18)
<asynchronous suspension>
#18     FlutterCommand.run (package:flutter_tools/src/runner/flutter_command.dart:397:20)
#19     CommandRunner.runCommand (package:args/command_runner.dart:197:27)
<asynchronous suspension>
#20     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:402:21)
<asynchronous suspension>
#21     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:154:29)
<asynchronous suspension>
#22     _rootRun (dart:async/zone.dart:1124:13)
#23     _CustomZone.run (dart:async/zone.dart:1021:19)
#24     _runZoned (dart:async/zone.dart:1516:10)
#25     runZoned (dart:async/zone.dart:1463:12)
#26     AppContext.run (package:flutter_tools/src/base/context.dart:153:18)
<asynchronous suspension>
#27     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:356:19)
<asynchronous suspension>
#28     CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:112:25)
#29     new Future.sync (dart:async/future.dart:224:31)
#30     CommandRunner.run (package:args/command_runner.dart:112:14)
#31     FlutterCommandRunner.run (package:flutter_tools/src/runner/flutter_command_runner.dart:242:18)
#32     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:63:22)
<asynchronous suspension>
#33     _rootRun (dart:async/zone.dart:1124:13)
#34     _CustomZone.run (dart:async/zone.dart:1021:19)
#35     _runZoned (dart:async/zone.dart:1516:10)
#36     runZoned (dart:async/zone.dart:1500:12)
#37     run.<anonymous closure> (package:flutter_tools/runner.dart:61:18)
<asynchronous suspension>
#38     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:154:29)
<asynchronous suspension>
#39     _rootRun (dart:async/zone.dart:1124:13)
#40     _CustomZone.run (dart:async/zone.dart:1021:19)
#41     _runZoned (dart:async/zone.dart:1516:10)
#42     runZoned (dart:async/zone.dart:1463:12)
#43     AppContext.run (package:flutter_tools/src/base/context.dart:153:18)
<asynchronous suspension>
#44     runInContext (package:flutter_tools/src/context_runner.dart:58:24)
<asynchronous suspension>
#45     run (package:flutter_tools/runner.dart:50:10)
#46     main (package:flutter_tools/executable.dart:63:9)
<asynchronous suspension>
#47     main (file:///D:/soft/flutter/packages/flutter_tools/bin/flutter_tools.dart:8:3)
#48     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:303:32)
#49     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:12)
```

## flutter doctor

```
encountered exception: VersionCheckError: Command exited with code 128: git log -n 1 --pretty=format:%ad --date=iso
Standard error: fatal: bad default revision 'HEAD'


#0      _runSync (package:flutter_tools/src/version.dart:525:5)
#1      FlutterVersion._latestGitCommitDate (package:flutter_tools/src/version.dart:145:12)
#2      FlutterVersion.frameworkCommitDate (package:flutter_tools/src/version.dart:133:37)
#3      FlutterVersion.frameworkDate (package:flutter_tools/src/version.dart:95:31)
#4      FlutterValidator.validate (package:flutter_tools/src/doctor.dart:518:127)
<asynchronous suspension>
#5      Doctor.startValidatorTasks (package:flutter_tools/src/doctor.dart:140:52)
#6      Doctor.diagnose (package:flutter_tools/src/doctor.dart:211:41)
<asynchronous suspension>
#7      _doctorText.<anonymous closure> (package:flutter_tools/runner.dart:202:26)
#8      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:154:29)
<asynchronous suspension>
#9      _rootRun (dart:async/zone.dart:1124:13)
#10     _CustomZone.run (dart:async/zone.dart:1021:19)
#11     _runZoned (dart:async/zone.dart:1516:10)
#12     runZoned (dart:async/zone.dart:1463:12)
#13     AppContext.run (package:flutter_tools/src/base/context.dart:153:18)
<asynchronous suspension>
#14     _doctorText (package:flutter_tools/runner.dart:201:19)
<asynchronous suspension>
#15     _createLocalCrashReport (package:flutter_tools/runner.dart:179:32)
<asynchronous suspension>
#16     _handleToolError (package:flutter_tools/runner.dart:134:33)
<asynchronous suspension>
#17     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:68:22)
<asynchronous suspension>
#18     _rootRun (dart:async/zone.dart:1124:13)
#19     _CustomZone.run (dart:async/zone.dart:1021:19)
#20     _runZoned (dart:async/zone.dart:1516:10)
#21     runZoned (dart:async/zone.dart:1500:12)
#22     run.<anonymous closure> (package:flutter_tools/runner.dart:61:18)
<asynchronous suspension>
#23     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:154:29)
<asynchronous suspension>
#24     _rootRun (dart:async/zone.dart:1124:13)
#25     _CustomZone.run (dart:async/zone.dart:1021:19)
#26     _runZoned (dart:async/zone.dart:1516:10)
#27     runZoned (dart:async/zone.dart:1463:12)
#28     AppContext.run (package:flutter_tools/src/base/context.dart:153:18)
<asynchronous suspension>
#29     runInContext (package:flutter_tools/src/context_runner.dart:58:24)
<asynchronous suspension>
#30     run (package:flutter_tools/runner.dart:50:10)
#31     main (package:flutter_tools/executable.dart:63:9)
<asynchronous suspension>
#32     main (file:///D:/soft/flutter/packages/flutter_tools/bin/flutter_tools.dart:8:3)
#33     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:303:32)
#34     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:12)
```

**Comment by ketanm** [comment]
Hi @Kevin088 

You seem to have installation issues. Please follow the steps as listed in the guide. 
Also before reporting, do a search for existing reported issues. 

The similar issue has already been closed and clarified - https://github.com/flutter/flutter/issues/22547
#22547
