### ISSUE TITLE
`flutter analyze` fails

### ISSUE THREAD

**Issue by redsolver** [flutter/flutter#37589]
## Steps to Reproduce

1. `flutter create example`
2. `cd example`
3. `flutter analyze`

## Logs

`flutter analyze --verbose`

```
[  +16 ms] executing: [/home/redsolver/dev/flutter/] git log -n 1 --pretty=format:%H
[  +25 ms] Exit code 0 from: git log -n 1 --pretty=format:%H
[        ] 20e59316b8b8474554b38493b8ca888794b0234a
[        ] executing: [/home/redsolver/dev/flutter/] git describe --match v*.*.* --first-parent --long --tags
[  +12 ms] Exit code 0 from: git describe --match v*.*.* --first-parent --long --tags
[        ] v1.7.8+hotfix.4-0-g20e59316b
[   +7 ms] executing: [/home/redsolver/dev/flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[  +10 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/stable
[        ] executing: [/home/redsolver/dev/flutter/] git ls-remote --get-url origin
[   +8 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[  +29 ms] executing: [/home/redsolver/dev/flutter/] git rev-parse --abbrev-ref HEAD
[  +11 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] stable
[  +26 ms] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +2 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[ +239 ms] dart /home/redsolver/dev/flutter/bin/cache/dart-sdk/bin/snapshots/analysis_server.dart.snapshot --disable-server-feature-completion --disable-server-feature-search --sdk
/home/redsolver/dev/flutter/bin/cache/dart-sdk
[  +20 ms] ==> {"id":"1","method":"server.setSubscriptions","params":{"subscriptions":["STATUS"]}}
[        ] ==> {"id":"2","method":"analysis.setAnalysisRoots","params":{"included":["/home/redsolver/tmp/example"],"excluded":[]}}
[        ] Analyzing example...
[ +193 ms] <== {"event":"server.connected","params":{"version":"1.27.1","pid":5521,"sessionId":""}}
[  +12 ms] <== {"id":"1"}
[ +126 ms] <== {"event":"analysis.errors","params":{"file":"/home/redsolver/tmp/example/pubspec.yaml","errors":[]}}
[   +3 ms] <== {"event":"analysis.errors","params":{"file":"/home/redsolver/tmp/example/android/app/src/main/AndroidManifest.xml","errors":[]}}
[        ] <== {"event":"analysis.errors","params":{"file":"/home/redsolver/tmp/example/android/app/src/profile/AndroidManifest.xml","errors":[]}}
[        ] <== {"event":"analysis.errors","params":{"file":"/home/redsolver/tmp/example/android/app/src/debug/AndroidManifest.xml","errors":[]}}
[  +30 ms] <== {"id":"2"}
[   +7 ms] <== {"event":"server.status","params":{"analysis":{"isAnalyzing":true}}}
[+1388 ms] <== {"event":"server.error","params":{"isFatal":false,"message":"Analysis failed: /home/redsolver/tmp/example/lib/main.dart context: exception_20190804_233038_450","stackTrace":"type
'DynamicTypeImpl' is not a subtype of type 'InterfaceType'\n#0      TypeProviderForLink._buildInterfaceType (package:analyzer/src/summary/link.dart:5535:5)\n#1      TypeProviderForLink.listType
(package:analyzer/src/summary/link.dart:5474:21)\n#2      ExprBuilder._pushList (package:analyzer/src/summary/expr_builder.dart:898:49)\n#3      ExprBuilder.build
(package:analyzer/src/summary/expr_builder.dart:213:11)\n#4      ExprTypeComputer.compute (package:analyzer/src/summary/link.dart:2533:29)\n#5      TypeInferenceNode.evaluate
(package:analyzer/src/summary/link.dart:5357:36)\n#6      TypeInferenceDependencyWalker.evaluate (package:analyzer/src/summary/link.dart:5200:7)\n#7      DependencyWalker.walk.strongConnect
(package:analyzer/src/summary/link.dart:2213:13)\n#8      DependencyWalker.walk (package:analyzer/src/summary/link.dart:2232:18)\n#9      VariableElementForLink.inferredType
(package:analyzer/src/summary/link.dart:5633:47)\n#10     TopLevelVariableElementForLink.link (package:analyzer/src/summary/link.dart:5185:48)\n#11     CompilationUnitElementInBuildUnit.link
(package:analyzer/src/summary/link.dart:1629:16)\n#12     LibraryElementInBuildUnit.link (package:analyzer/src/summary/link.dart:3840:12)\n#13     LibraryCycleNode.link
(package:analyzer/src/summary/link.dart:3540:15)\n#14     LibraryCycleDependencyWalker.evaluate (package:analyzer/src/summary/link.dart:3480:7)\n#15     DependencyWalker.walk.strongConnect
(package:analyzer/src/summary/link.dart:2213:13)\n#16     DependencyWalker.walk.strongConnect (package:analyzer/src/summary/link.dart:2179:24)\n#17     DependencyWalker.walk.strongConnect
(package:analyzer/src/summary/link.dart:2179:24)\n#18     DependencyWalker.walk (package:analyzer/src/summary/link.dart:2232:18)\n#19     LibraryCycleForLink.ensureLinked
(package:analyzer/src/summary/link.dart:3513:42)\n#20     Linker.link (package:analyzer/src/summary/link.dart:4045:35)\n#21     _relink (package:analyzer/src/summary/link.dart:311:74)\n#22     link
(package:analyzer/src/summary/link.dart:125:3)\n#23     LibraryContext.load.<anonymous closure> (package:analyzer/src/dart/analysis/library_context.dart:217:25)\n#24     PerformanceLog.run
(package:analyzer/src/dart/analysis/performance_logger.dart:34:15)\n#25     LibraryContext.load (package:analyzer/src/dart/analysis/library_context.dart:216:12)\n#26     new LibraryContext
(package:analyzer/src/dart/analysis/library_context.dart:98:7)\n#27     AnalysisDriver._createLibraryContext (package:analyzer/src/dart/analysis/driver.dart:1594:29)\n#28
AnalysisDriver._computeAnalysisResult.<anonymous closure> (package:analyzer/src/dart/analysis/driver.dart:1405:30)\n#29     PerformanceLog.run
(package:analyzer/src/dart/analysis/performance_logger.dart:34:15)\n#30     AnalysisDriver._computeAnalysisResult (package:analyzer/src/dart/analysis/driver.dart:1395:20)\n#31     AnalysisDriver.performWork
(package:analyzer/src/dart/analysis/driver.dart:1215:33)\n<asynchronous suspension>\n#32     AnalysisDriverScheduler._run (package:analyzer/src/dart/analysis/driver.dart:2132:24)\n<asynchronous
suspension>\n#33     AnalysisDriverScheduler.start (package:analyzer/src/dart/analysis/driver.dart:2062:5)\n#34     new AnalysisServer (package:analysis_server/src/analysis_server.dart:208:29)\n#35
SocketServer.createAnalysisServer (package:analysis_server/src/socket_server.dart:86:26)\n#36     StdioAnalysisServer.serveStdio (package:analysis_server/src/server/stdio_server.dart:37:18)\n#37
Driver.startAnalysisServer.<anonymous closure> (package:analysis_server/src/server/driver.dart:542:21)\n#38     _rootRun (dart:async/zone.dart:1124:13)\n#39     _CustomZone.run
(dart:async/zone.dart:1021:19)\n#40     _runZoned (dart:async/zone.dart:1516:10)\n#41     runZoned (dart:async/zone.dart:1463:12)\n#42     Driver._captureExceptions
(package:analysis_server/src/server/driver.dart:627:12)\n#43     Driver.startAnalysisServer (package:analysis_server/src/server/driver.dart:540:7)\n#44     Driver.start.<anonymous closure>
(package:analysis_server/src/server/driver.dart:444:9)\n#45     _AsyncAwaitCompleter.start (dart:async-patch/async_patch.dart:49:6)\n#46     Driver.start.<anonymous closure>
(package:analysis_server/src/server/driver.dart:439:43)\n#47     CompilerContext.runInContext.<anonymous closure>.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart:122:46)\n#48     new
Future.sync (dart:async/future.dart:224:31)\n#49     CompilerContext.runInContext.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart:122:19)\n#50     _rootRun
(dart:async/zone.dart:1124:13)\n#51     _CustomZone.run (dart:async/zone.dart:1021:19)\n#52     _runZoned (dart:async/zone.dart:1516:10)\n#53     runZoned (dart:async/zone.dart:1463:12)\n#54
CompilerContext.runInContext (package:front_end/src/fasta/compiler_context.dart:121:12)\n#55     CompilerContext.runWithDefaultOptions (package:front_end/src/fasta/compiler_context.dart:140:56)\n#56
Driver.start (package:analysis_server/src/server/driver.dart:439:21)\n#57     main (file:///b/s/w/ir/k/src/third_party/dart/pkg/analysis_server/bin/server.dart:12:11)\n#58     _AsyncAwaitCompleter.start
(dart:async-patch/async_patch.dart:49:6)\n#59     main (file:///b/s/w/ir/k/src/third_party/dart/pkg/analysis_server/bin/server.dart:10:10)\n#60     _startIsolate.<anonymous closure>
(dart:isolate-patch/isolate_patch.dart:299:32)\n#61     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:12)\n\n"}}
[  +15 ms] Error from the analysis server: Analysis failed: /home/redsolver/tmp/example/lib/main.dart context: exception_20190804_233038_450
[   +1 ms] type 'DynamicTypeImpl' is not a subtype of type 'InterfaceType'
           #0      TypeProviderForLink._buildInterfaceType (package:analyzer/src/summary/link.dart:5535:5)
           #1      TypeProviderForLink.listType (package:analyzer/src/summary/link.dart:5474:21)
           #2      ExprBuilder._pushList (package:analyzer/src/summary/expr_builder.dart:898:49)
           #3      ExprBuilder.build (package:analyzer/src/summary/expr_builder.dart:213:11)
           #4      ExprTypeComputer.compute (package:analyzer/src/summary/link.dart:2533:29)
           #5      TypeInferenceNode.evaluate (package:analyzer/src/summary/link.dart:5357:36)
           #6      TypeInferenceDependencyWalker.evaluate (package:analyzer/src/summary/link.dart:5200:7)
           #7      DependencyWalker.walk.strongConnect (package:analyzer/src/summary/link.dart:2213:13)
           #8      DependencyWalker.walk (package:analyzer/src/summary/link.dart:2232:18)
           #9      VariableElementForLink.inferredType (package:analyzer/src/summary/link.dart:5633:47)
           #10     TopLevelVariableElementForLink.link (package:analyzer/src/summary/link.dart:5185:48)
           #11     CompilationUnitElementInBuildUnit.link (package:analyzer/src/summary/link.dart:1629:16)
           #12     LibraryElementInBuildUnit.link (package:analyzer/src/summary/link.dart:3840:12)
           #13     LibraryCycleNode.link (package:analyzer/src/summary/link.dart:3540:15)
           #14     LibraryCycleDependencyWalker.evaluate (package:analyzer/src/summary/link.dart:3480:7)
           #15     DependencyWalker.walk.strongConnect (package:analyzer/src/summary/link.dart:2213:13)
           #16     DependencyWalker.walk.strongConnect (package:analyzer/src/summary/link.dart:2179:24)
           #17     DependencyWalker.walk.strongConnect (package:analyzer/src/summary/link.dart:2179:24)
           #18     DependencyWalker.walk (package:analyzer/src/summary/link.dart:2232:18)
           #19     LibraryCycleForLink.ensureLinked (package:analyzer/src/summary/link.dart:3513:42)
           #20     Linker.link (package:analyzer/src/summary/link.dart:4045:35)
           #21     _relink (package:analyzer/src/summary/link.dart:311:74)
           #22     link (package:analyzer/src/summary/link.dart:125:3)
           #23     LibraryContext.load.<anonymous closure> (package:analyzer/src/dart/analysis/library_context.dart:217:25)
           #24     PerformanceLog.run (package:analyzer/src/dart/analysis/performance_logger.dart:34:15)
           #25     LibraryContext.load (package:analyzer/src/dart/analysis/library_context.dart:216:12)
           #26     new LibraryContext (package:analyzer/src/dart/analysis/library_context.dart:98:7)
           #27     AnalysisDriver._createLibraryContext (package:analyzer/src/dart/analysis/driver.dart:1594:29)
           #28     AnalysisDriver._computeAnalysisResult.<anonymous closure> (package:analyzer/src/dart/analysis/driver.dart:1405:30)
           #29     PerformanceLog.run (package:analyzer/src/dart/analysis/performance_logger.dart:34:15)
           #30     AnalysisDriver._computeAnalysisResult (package:analyzer/src/dart/analysis/driver.dart:1395:20)
           #31     AnalysisDriver.performWork (package:analyzer/src/dart/analysis/driver.dart:1215:33)
           <asynchronous suspension>
           #32     AnalysisDriverScheduler._run (package:analyzer/src/dart/analysis/driver.dart:2132:24)
           <asynchronous suspension>
           #33     AnalysisDriverScheduler.start (package:analyzer/src/dart/analysis/driver.dart:2062:5)
           #34     new AnalysisServer (package:analysis_server/src/analysis_server.dart:208:29)
           #35     SocketServer.createAnalysisServer (package:analysis_server/src/socket_server.dart:86:26)
           #36     StdioAnalysisServer.serveStdio (package:analysis_server/src/server/stdio_server.dart:37:18)
           #37     Driver.startAnalysisServer.<anonymous closure> (package:analysis_server/src/server/driver.dart:542:21)
           #38     _rootRun (dart:async/zone.dart:1124:13)
           #39     _CustomZone.run (dart:async/zone.dart:1021:19)
           #40     _runZoned (dart:async/zone.dart:1516:10)
           #41     runZoned (dart:async/zone.dart:1463:12)
           #42     Driver._captureExceptions (package:analysis_server/src/server/driver.dart:627:12)
           #43     Driver.startAnalysisServer (package:analysis_server/src/server/driver.dart:540:7)
           #44     Driver.start.<anonymous closure> (package:analysis_server/src/server/driver.dart:444:9)
           #45     _AsyncAwaitCompleter.start (dart:async-patch/async_patch.dart:49:6)
           #46     Driver.start.<anonymous closure> (package:analysis_server/src/server/driver.dart:439:43)
           #47     CompilerContext.runInContext.<anonymous closure>.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart:122:46)
           #48     new Future.sync (dart:async/future.dart:224:31)
           #49     CompilerContext.runInContext.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart:122:19)
           #50     _rootRun (dart:async/zone.dart:1124:13)
           #51     _CustomZone.run (dart:async/zone.dart:1021:19)
           #52     _runZoned (dart:async/zone.dart:1516:10)
           #53     runZoned (dart:async/zone.dart:1463:12)
           #54     CompilerContext.runInContext (package:front_end/src/fasta/compiler_context.dart:121:12)
           #55     CompilerContext.runWithDefaultOptions (package:front_end/src/fasta/compiler_context.dart:140:56)
           #56     Driver.start (package:analysis_server/src/server/driver.dart:439:21)
           #57     main (file:///b/s/w/ir/k/src/third_party/dart/pkg/analysis_server/bin/server.dart:12:11)
           #58     _AsyncAwaitCompleter.start (dart:async-patch/async_patch.dart:49:6)
           #59     main (file:///b/s/w/ir/k/src/third_party/dart/pkg/analysis_server/bin/server.dart:10:10)
           #60     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:299:32)
           #61     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:12)
           
           
[ +782 ms] <== {"event":"server.error","params":{"isFatal":false,"message":"Analysis failed: /home/redsolver/tmp/example/test/widget_test.dart context: exception_20190804_233039_252","stackTrace":"type
'DynamicTypeImpl' is not a subtype of type 'InterfaceType'\n#0      TypeProviderForLink._buildInterfaceType (package:analyzer/src/summary/link.dart:5535:5)\n#1      TypeProviderForLink.listType
(package:analyzer/src/summary/link.dart:5474:21)\n#2      ExprBuilder._pushList (package:analyzer/src/summary/expr_builder.dart:898:49)\n#3      ExprBuilder.build
(package:analyzer/src/summary/expr_builder.dart:213:11)\n#4      ExprTypeComputer.compute (package:analyzer/src/summary/link.dart:2533:29)\n#5      TypeInferenceNode.evaluate
(package:analyzer/src/summary/link.dart:5357:36)\n#6      TypeInferenceDependencyWalker.evaluate (package:analyzer/src/summary/link.dart:5200:7)\n#7      DependencyWalker.walk.strongConnect
(package:analyzer/src/summary/link.dart:2213:13)\n#8      DependencyWalker.walk (package:analyzer/src/summary/link.dart:2232:18)\n#9      VariableElementForLink.inferredType
(package:analyzer/src/summary/link.dart:5633:47)\n#10     TopLevelVariableElementForLink.link (package:analyzer/src/summary/link.dart:5185:48)\n#11     CompilationUnitElementInBuildUnit.link
(package:analyzer/src/summary/link.dart:1629:16)\n#12     LibraryElementInBuildUnit.link (package:analyzer/src/summary/link.dart:3840:12)\n#13     LibraryCycleNode.link
(package:analyzer/src/summary/link.dart:3540:15)\n#14     LibraryCycleDependencyWalker.evaluate (package:analyzer/src/summary/link.dart:3480:7)\n#15     DependencyWalker.walk.strongConnect
(package:analyzer/src/summary/link.dart:2213:13)\n#16     DependencyWalker.walk.strongConnect (package:analyzer/src/summary/link.dart:2179:24)\n#17     DependencyWalker.walk.strongConnect
(package:analyzer/src/summary/link.dart:2179:24)\n#18     DependencyWalker.walk (package:analyzer/src/summary/link.dart:2232:18)\n#19     LibraryCycleForLink.ensureLinked
(package:analyzer/src/summary/link.dart:3513:42)\n#20     Linker.link (package:analyzer/src/summary/link.dart:4045:35)\n#21     _relink (package:analyzer/src/summary/link.dart:311:74)\n#22     link
(package:analyzer/src/summary/link.dart:125:3)\n#23     LibraryContext.load.<anonymous closure> (package:analyzer/src/dart/analysis/library_context.dart:217:25)\n#24     PerformanceLog.run
(package:analyzer/src/dart/analysis/performance_logger.dart:34:15)\n#25     LibraryContext.load (package:analyzer/src/dart/analysis/library_context.dart:216:12)\n#26     new LibraryContext
(package:analyzer/src/dart/analysis/library_context.dart:98:7)\n#27     AnalysisDriver._createLibraryContext (package:analyzer/src/dart/analysis/driver.dart:1594:29)\n#28
AnalysisDriver._computeAnalysisResult.<anonymous closure> (package:analyzer/src/dart/analysis/driver.dart:1405:30)\n#29     PerformanceLog.run
(package:analyzer/src/dart/analysis/performance_logger.dart:34:15)\n#30     AnalysisDriver._computeAnalysisResult (package:analyzer/src/dart/analysis/driver.dart:1395:20)\n#31     AnalysisDriver.performWork
(package:analyzer/src/dart/analysis/driver.dart:1215:33)\n<asynchronous suspension>\n#32     AnalysisDriverScheduler._run (package:analyzer/src/dart/analysis/driver.dart:2132:24)\n<asynchronous
suspension>\n#33     AnalysisDriverScheduler.start (package:analyzer/src/dart/analysis/driver.dart:2062:5)\n#34     new AnalysisServer (package:analysis_server/src/analysis_server.dart:208:29)\n#35
SocketServer.createAnalysisServer (package:analysis_server/src/socket_server.dart:86:26)\n#36     StdioAnalysisServer.serveStdio (package:analysis_server/src/server/stdio_server.dart:37:18)\n#37
Driver.startAnalysisServer.<anonymous closure> (package:analysis_server/src/server/driver.dart:542:21)\n#38     _rootRun (dart:async/zone.dart:1124:13)\n#39     _CustomZone.run
(dart:async/zone.dart:1021:19)\n#40     _runZoned (dart:async/zone.dart:1516:10)\n#41     runZoned (dart:async/zone.dart:1463:12)\n#42     Driver._captureExceptions
(package:analysis_server/src/server/driver.dart:627:12)\n#43     Driver.startAnalysisServer (package:analysis_server/src/server/driver.dart:540:7)\n#44     Driver.start.<anonymous closure>
(package:analysis_server/src/server/driver.dart:444:9)\n#45     _AsyncAwaitCompleter.start (dart:async-patch/async_patch.dart:49:6)\n#46     Driver.start.<anonymous closure>
(package:analysis_server/src/server/driver.dart:439:43)\n#47     CompilerContext.runInContext.<anonymous closure>.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart:122:46)\n#48     new
Future.sync (dart:async/future.dart:224:31)\n#49     CompilerContext.runInContext.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart:122:19)\n#50     _rootRun
(dart:async/zone.dart:1124:13)\n#51     _CustomZone.run (dart:async/zone.dart:1021:19)\n#52     _runZoned (dart:async/zone.dart:1516:10)\n#53     runZoned (dart:async/zone.dart:1463:12)\n#54
CompilerContext.runInContext (package:front_end/src/fasta/compiler_context.dart:121:12)\n#55     CompilerContext.runWithDefaultOptions (package:front_end/src/fasta/compiler_context.dart:140:56)\n#56
Driver.start (package:analysis_server/src/server/driver.dart:439:21)\n#57     main (file:///b/s/w/ir/k/src/third_party/dart/pkg/analysis_server/bin/server.dart:12:11)\n#58     _AsyncAwaitCompleter.start
(dart:async-patch/async_patch.dart:49:6)\n#59     main (file:///b/s/w/ir/k/src/third_party/dart/pkg/analysis_server/bin/server.dart:10:10)\n#60     _startIsolate.<anonymous closure>
(dart:isolate-patch/isolate_patch.dart:299:32)\n#61     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:12)\n\n"}}
[   +3 ms] Error from the analysis server: Analysis failed: /home/redsolver/tmp/example/test/widget_test.dart context: exception_20190804_233039_252
[        ] type 'DynamicTypeImpl' is not a subtype of type 'InterfaceType'
           #0      TypeProviderForLink._buildInterfaceType (package:analyzer/src/summary/link.dart:5535:5)
           #1      TypeProviderForLink.listType (package:analyzer/src/summary/link.dart:5474:21)
           #2      ExprBuilder._pushList (package:analyzer/src/summary/expr_builder.dart:898:49)
           #3      ExprBuilder.build (package:analyzer/src/summary/expr_builder.dart:213:11)
           #4      ExprTypeComputer.compute (package:analyzer/src/summary/link.dart:2533:29)
           #5      TypeInferenceNode.evaluate (package:analyzer/src/summary/link.dart:5357:36)
           #6      TypeInferenceDependencyWalker.evaluate (package:analyzer/src/summary/link.dart:5200:7)
           #7      DependencyWalker.walk.strongConnect (package:analyzer/src/summary/link.dart:2213:13)
           #8      DependencyWalker.walk (package:analyzer/src/summary/link.dart:2232:18)
           #9      VariableElementForLink.inferredType (package:analyzer/src/summary/link.dart:5633:47)
           #10     TopLevelVariableElementForLink.link (package:analyzer/src/summary/link.dart:5185:48)
           #11     CompilationUnitElementInBuildUnit.link (package:analyzer/src/summary/link.dart:1629:16)
           #12     LibraryElementInBuildUnit.link (package:analyzer/src/summary/link.dart:3840:12)
           #13     LibraryCycleNode.link (package:analyzer/src/summary/link.dart:3540:15)
           #14     LibraryCycleDependencyWalker.evaluate (package:analyzer/src/summary/link.dart:3480:7)
           #15     DependencyWalker.walk.strongConnect (package:analyzer/src/summary/link.dart:2213:13)
           #16     DependencyWalker.walk.strongConnect (package:analyzer/src/summary/link.dart:2179:24)
           #17     DependencyWalker.walk.strongConnect (package:analyzer/src/summary/link.dart:2179:24)
           #18     DependencyWalker.walk (package:analyzer/src/summary/link.dart:2232:18)
           #19     LibraryCycleForLink.ensureLinked (package:analyzer/src/summary/link.dart:3513:42)
           #20     Linker.link (package:analyzer/src/summary/link.dart:4045:35)
           #21     _relink (package:analyzer/src/summary/link.dart:311:74)
           #22     link (package:analyzer/src/summary/link.dart:125:3)
           #23     LibraryContext.load.<anonymous closure> (package:analyzer/src/dart/analysis/library_context.dart:217:25)
           #24     PerformanceLog.run (package:analyzer/src/dart/analysis/performance_logger.dart:34:15)
           #25     LibraryContext.load (package:analyzer/src/dart/analysis/library_context.dart:216:12)
           #26     new LibraryContext (package:analyzer/src/dart/analysis/library_context.dart:98:7)
           #27     AnalysisDriver._createLibraryContext (package:analyzer/src/dart/analysis/driver.dart:1594:29)
           #28     AnalysisDriver._computeAnalysisResult.<anonymous closure> (package:analyzer/src/dart/analysis/driver.dart:1405:30)
           #29     PerformanceLog.run (package:analyzer/src/dart/analysis/performance_logger.dart:34:15)
           #30     AnalysisDriver._computeAnalysisResult (package:analyzer/src/dart/analysis/driver.dart:1395:20)
           #31     AnalysisDriver.performWork (package:analyzer/src/dart/analysis/driver.dart:1215:33)
           <asynchronous suspension>
           #32     AnalysisDriverScheduler._run (package:analyzer/src/dart/analysis/driver.dart:2132:24)
           <asynchronous suspension>
           #33     AnalysisDriverScheduler.start (package:analyzer/src/dart/analysis/driver.dart:2062:5)
           #34     new AnalysisServer (package:analysis_server/src/analysis_server.dart:208:29)
           #35     SocketServer.createAnalysisServer (package:analysis_server/src/socket_server.dart:86:26)
           #36     StdioAnalysisServer.serveStdio (package:analysis_server/src/server/stdio_server.dart:37:18)
           #37     Driver.startAnalysisServer.<anonymous closure> (package:analysis_server/src/server/driver.dart:542:21)
           #38     _rootRun (dart:async/zone.dart:1124:13)
           #39     _CustomZone.run (dart:async/zone.dart:1021:19)
           #40     _runZoned (dart:async/zone.dart:1516:10)
           #41     runZoned (dart:async/zone.dart:1463:12)
           #42     Driver._captureExceptions (package:analysis_server/src/server/driver.dart:627:12)
           #43     Driver.startAnalysisServer (package:analysis_server/src/server/driver.dart:540:7)
           #44     Driver.start.<anonymous closure> (package:analysis_server/src/server/driver.dart:444:9)
           #45     _AsyncAwaitCompleter.start (dart:async-patch/async_patch.dart:49:6)
           #46     Driver.start.<anonymous closure> (package:analysis_server/src/server/driver.dart:439:43)
           #47     CompilerContext.runInContext.<anonymous closure>.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart:122:46)
           #48     new Future.sync (dart:async/future.dart:224:31)
           #49     CompilerContext.runInContext.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart:122:19)
           #50     _rootRun (dart:async/zone.dart:1124:13)
           #51     _CustomZone.run (dart:async/zone.dart:1021:19)
           #52     _runZoned (dart:async/zone.dart:1516:10)
           #53     runZoned (dart:async/zone.dart:1463:12)
           #54     CompilerContext.runInContext (package:front_end/src/fasta/compiler_context.dart:121:12)
           #55     CompilerContext.runWithDefaultOptions (package:front_end/src/fasta/compiler_context.dart:140:56)
           #56     Driver.start (package:analysis_server/src/server/driver.dart:439:21)
           #57     main (file:///b/s/w/ir/k/src/third_party/dart/pkg/analysis_server/bin/server.dart:12:11)
           #58     _AsyncAwaitCompleter.start (dart:async-patch/async_patch.dart:49:6)
           #59     main (file:///b/s/w/ir/k/src/third_party/dart/pkg/analysis_server/bin/server.dart:10:10)
           #60     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:299:32)
           #61     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:12)
           
           
[   +6 ms] <== {"event":"server.status","params":{"analysis":{"isAnalyzing":false}}}
[   +6 ms] Analyzing example... (completed in 2,6s)
[   +2 ms] "flutter analyze" took 2.872ms.
[        ] "flutter analyze" took 2.872ms.
Server error(s) occurred. (ran in 2.6s)

#0      throwToolExit (package:flutter_tools/src/base/common.dart:28:3)
#1      AnalyzeOnce.analyze (package:flutter_tools/src/commands/analyze_once.dart:159:7)
<asynchronous suspension>
#2      AnalyzeCommand.runCommand (package:flutter_tools/src/commands/analyze.dart:102:9)
<asynchronous suspension>
#3      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:478:18)
<asynchronous suspension>
#4      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:383:33)
<asynchronous suspension>
#5      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:29)
<asynchronous suspension>
#6      _rootRun (dart:async/zone.dart:1124:13)
#7      _CustomZone.run (dart:async/zone.dart:1021:19)
#8      _runZoned (dart:async/zone.dart:1516:10)
#9      runZoned (dart:async/zone.dart:1463:12)
#10     AppContext.run (package:flutter_tools/src/base/context.dart:152:18)
<asynchronous suspension>
#11     FlutterCommand.run (package:flutter_tools/src/runner/flutter_command.dart:375:20)
#12     CommandRunner.runCommand (package:args/command_runner.dart:197:27)
<asynchronous suspension>
#13     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:396:21)
<asynchronous suspension>
#14     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:29)
<asynchronous suspension>
#15     _rootRun (dart:async/zone.dart:1124:13)
#16     _CustomZone.run (dart:async/zone.dart:1021:19)
#17     _runZoned (dart:async/zone.dart:1516:10)
#18     runZoned (dart:async/zone.dart:1463:12)
#19     AppContext.run (package:flutter_tools/src/base/context.dart:152:18)
<asynchronous suspension>
#20     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:356:19)
<asynchronous suspension>
#21     CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:112:25)
#22     new Future.sync (dart:async/future.dart:224:31)
#23     CommandRunner.run (package:args/command_runner.dart:112:14)
#24     FlutterCommandRunner.run (package:flutter_tools/src/runner/flutter_command_runner.dart:242:18)
#25     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:62:22)
<asynchronous suspension>
#26     _rootRun (dart:async/zone.dart:1124:13)
#27     _CustomZone.run (dart:async/zone.dart:1021:19)
#28     _runZoned (dart:async/zone.dart:1516:10)
#29     runZoned (dart:async/zone.dart:1500:12)
#30     run.<anonymous closure> (package:flutter_tools/runner.dart:60:18)
<asynchronous suspension>
#31     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:29)
<asynchronous suspension>
#32     _rootRun (dart:async/zone.dart:1124:13)
#33     _CustomZone.run (dart:async/zone.dart:1021:19)
#34     _runZoned (dart:async/zone.dart:1516:10)
#35     runZoned (dart:async/zone.dart:1463:12)
#36     AppContext.run (package:flutter_tools/src/base/context.dart:152:18)
<asynchronous suspension>
#37     runInContext (package:flutter_tools/src/context_runner.dart:56:24)
<asynchronous suspension>
#38     run (package:flutter_tools/runner.dart:51:10)
#39     main (package:flutter_tools/executable.dart:62:9)
<asynchronous suspension>
#40     main (file:///home/redsolver/dev/flutter/packages/flutter_tools/bin/flutter_tools.dart:8:3)
#41     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:299:32)
#42     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:12)




```

```
[✓] Flutter (Channel stable, v1.7.8+hotfix.4, on Linux, locale de_DE.UTF-8)
    • Flutter version 1.7.8+hotfix.4 at /home/redsolver/dev/flutter
    • Framework revision 20e59316b8 (vor 2 Wochen), 2019-07-18 20:04:33 -0700
    • Engine revision fee001c93f
    • Dart version 2.4.0

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /home/redsolver/Android/Sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 28.0.3
    • Java binary at: /home/redsolver/opt/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b16-5323222)
    • All Android licenses accepted.

[!] Android Studio (version 3.4)
    • Android Studio at /home/redsolver/opt/android-studio
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b16-5323222)

[✓] VS Code (version 1.36.1)
    • VS Code at /usr/share/code
    • Flutter extension version 3.3.0

[!] Connected device
    ! No devices available

! Doctor found issues in 2 categories.
```

**Comment by redsolver** [comment]
Fixed by fully reinstalling Flutter
