### ISSUE TITLE
Process Exception: Process dir/gradlew.bat exited abnormally

### ISSUE THREAD

**Issue by thekingrenz23** [flutter/flutter#37598]
## Steps to Reproduce

1. I created a new project using vscode command pallete 
2. Then run the application (i did not change anything in the starter code)
3. Shows the error on the gradlew.bat

## Logs

```
flutter run
```

```
ProcessException: Process "C:\Users\Renz\Documents\Flutter Projects\gocart\android\gradlew.bat" exited abnormally:
Exception in thread "main" java.lang.NullPointerException
	at org.gradle.wrapper.BootstrapMainStarter.findLauncherJar(BootstrapMainStarter.java:34)
	at org.gradle.wrapper.BootstrapMainStarter.start(BootstrapMainStarter.java:25)
	at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:129)
	at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:61)
  Command: C:\Users\Renz\Documents\Flutter Projects\gocart\android\gradlew.bat -v
Exited (sigterm)
```

**Comment by blasten** [comment]
what is the output of `flutter doctor`? What is the content of the file `<app>\android\gradle\gradle-wrapper.properties`?
