### ISSUE TITLE
Exception in adding firebase to flutter project

### ISSUE THREAD

**Issue by HoseinHaqiqian** [flutter/flutter#37605]
This problem occurs when i am trying to add firebase dependencies to my flutter project.

here's some details :

> pubspec.yaml : 

```
dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^0.4.0+1
  firebase_analytics: ^4.0.2

```

> android/build.gradle
```

buildscript {
    repositories {
        google()
        jcenter()
        
    }
    
    dependencies {
        classpath 'com.android.tools.build:gradle:3.2.1'
        classpath 'com.google.gms:google-services:3.2.1'
    }
}

allprojects {
   
    repositories {
        google()
        jcenter()
    }
}

rootProject.buildDir = '../build'
subprojects {
    project.buildDir = "${rootProject.buildDir}/${project.name}"
}
subprojects {
    project.evaluationDependsOn(':app')
}

task clean(type: Delete) {
    delete rootProject.buildDir
}

```

> android/app/build.gradle

```
dependencies {
    
    testImplementation 'junit:junit:4.12'
    androidTestImplementation 'com.android.support.test:runner:1.0.2'
    androidTestImplementation 'com.android.support.test.espresso:espresso-core:3.0.2'
}
apply plugin: 'com.google.gms.google-services'

```

> gradle-wrapper.properties
```

    #Fri Jun 23 08:50:38 CEST 2017
    distributionBase=GRADLE_USER_HOME
    distributionPath=wrapper/dists
    zipStoreBase=GRADLE_USER_HOME
    zipStorePath=wrapper/dists
    distributionUrl=https\://services.gradle.org/distributions/gradle-5.1.1-all.zip

```

> Result in flutter run --verbose mode :

```
Gradle task assembleDebug failed with exit code 1

#0      throwToolExit
(package:flutter_tools/src/base/common.dart:28:3)
#1      _buildGradleProjectV2
(package:flutter_tools/src/android/gradle.dart:507:5)     
<asynchronous suspension>
#2      buildGradleProject
(package:flutter_tools/src/android/gradle.dart:346:14)    
<asynchronous suspension>
#3      buildApk
(package:flutter_tools/src/android/apk.dart:34:9)
<asynchronous suspension>
#4      AndroidDevice.startApp
(package:flutter_tools/src/android/android_device.dart:426:13)
<asynchronous suspension>
#5      FlutterDevice.runHot
(package:flutter_tools/src/resident_runner.dart:371:54)   
<asynchronous suspension>
#6      HotRunner.run
(package:flutter_tools/src/run_hot.dart:251:39)
<asynchronous suspension>
#7      RunCommand.runCommand
(package:flutter_tools/src/commands/run.dart:469:37)      
<asynchronous suspension>
#8      FlutterCommand.verifyThenRunCommand
(package:flutter_tools/src/runner/flutter_command.dart:478:18)
<asynchronous suspension>
#9      FlutterCommand.run.<anonymous closure>
(package:flutter_tools/src/runner/flutter_command.dart:383:33)
<asynchronous suspension>
#10     AppContext.run.<anonymous closure>
(package:flutter_tools/src/base/context.dart:153:29)      
<asynchronous suspension>
#11     _rootRun (dart:async/zone.dart:1124:13)
#12     _CustomZone.run (dart:async/zone.dart:1021:19)    
#13     _runZoned (dart:async/zone.dart:1516:10)
#14     runZoned (dart:async/zone.dart:1463:12)
#15     AppContext.run
(package:flutter_tools/src/base/context.dart:152:18)      
<asynchronous suspension>
#16     FlutterCommand.run
(package:flutter_tools/src/runner/flutter_command.dart:375:20)
#17     CommandRunner.runCommand
(package:args/command_runner.dart:197:27)
<asynchronous suspension>
#18     FlutterCommandRunner.runCommand.<anonymous        
closure>
(package:flutter_tools/src/runner/flutter_command_runner.dart:396:21)
<asynchronous suspension>
#19     AppContext.run.<anonymous closure>
(package:flutter_tools/src/base/context.dart:153:29)      
<asynchronous suspension>
#20     _rootRun (dart:async/zone.dart:1124:13)
#21     _CustomZone.run (dart:async/zone.dart:1021:19)    
#22     _runZoned (dart:async/zone.dart:1516:10)
#23     runZoned (dart:async/zone.dart:1463:12)
#24     AppContext.run
(package:flutter_tools/src/base/context.dart:152:18)      
<asynchronous suspension>
#25     FlutterCommandRunner.runCommand
(package:flutter_tools/src/runner/flutter_command_runner.dart:356:19)
<asynchronous suspension>
#26     CommandRunner.run.<anonymous closure>
(package:args/command_runner.dart:112:25)
#27     new Future.sync (dart:async/future.dart:224:31)   
#28     CommandRunner.run
(package:args/command_runner.dart:112:14)
#29     FlutterCommandRunner.run
(package:flutter_tools/src/runner/flutter_command_runner.dart:242:18)
#30     run.<anonymous closure>.<anonymous closure>       
(package:flutter_tools/runner.dart:62:22)
<asynchronous suspension>
#31     _rootRun (dart:async/zone.dart:1124:13)
#32     _CustomZone.run (dart:async/zone.dart:1021:19)    
#33     _runZoned (dart:async/zone.dart:1516:10)
#34     runZoned (dart:async/zone.dart:1500:12)
#35     run.<anonymous closure>
(package:flutter_tools/runner.dart:60:18)
<asynchronous suspension>
#36     AppContext.run.<anonymous closure>
(package:flutter_tools/src/base/context.dart:153:29)      
<asynchronous suspension>
#37     _rootRun (dart:async/zone.dart:1124:13)
#38     _CustomZone.run (dart:async/zone.dart:1021:19)    
#39     _runZoned (dart:async/zone.dart:1516:10)
#40     runZoned (dart:async/zone.dart:1463:12)
#41     AppContext.run
(package:flutter_tools/src/base/context.dart:152:18)      
<asynchronous suspension>
#42     runInContext
(package:flutter_tools/src/context_runner.dart:56:24)     
<asynchronous suspension>
#43     run (package:flutter_tools/runner.dart:51:10)     
#44     main (package:flutter_tools/executable.dart:62:9) 
<asynchronous suspension>
#45     main
(file:///C:/src/packages/flutter_tools/bin/flutter_tools.dart:8:3)
#46     _startIsolate.<anonymous closure>
(dart:isolate-patch/isolate_patch.dart:299:32)
#47     _RawReceivePortImpl._handleMessage
(dart:isolate-patch/isolate_patch.dart:172:12)
```

**Comment by jonahwilliams** [comment]
This issue doesn't actually contain the stack trace from the Gradle error so it isn't possible to determine what went wrong. I'm closing the issue because this is likely stale, but feel free to open a new issue that includes more details
