### ISSUE TITLE
'_state._element == null': is not true.

### ISSUE THREAD

**Issue by nazmulgazi1989** [flutter/flutter#37609]
```
 When the exception was thrown, this was the stack:
I/flutter (11761): #2      new StatefulElement (package:flutter/src/widgets/framework.dart:3817:12)
I/flutter (11761): #3      StatefulWidget.createElement (package:flutter/src/widgets/framework.dart:788:38)
I/flutter (11761): #4      Element.inflateWidget (package:flutter/src/widgets/framework.dart:2959:40)
I/flutter (11761): #5      MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4982:32)
I/flutter (11761): #6      Element.inflateWidget (package:flutter/src/widgets/framework.dart:2961:14)
I/flutter (11761): #7      Element.updateChild (package:flutter/src/widgets/framework.dart:2764:12)
I/flutter (11761): #8      SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4876:14)
I/flutter (11761): #9      Element.inflateWidget (package:flutter/src/widgets/framework.dart:2961:14)
I/flutter (11761): #10     Element.updateChild (package:flutter/src/widgets/framework.dart:2764:12)
I/flutter (11761): #11     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4876:14)
I/flutter (11761): #12     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2961:14)
I/flutter (11761): #13     Element.updateChild (package:flutter/src/widgets/framework.dart:2764:12)
I/flutter (11761): #14     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3750:16)
I/flutter (11761): #15     Element.rebuild (package:flutter/src/widgets/framework.dart:3565:5)
I/flutter (11761): #16     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3722:5)
I/flutter (11761): #17     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3864:11)
I/flutter (11761): #18     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3717:5)
I/flutter (11761): #19     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2961:14)
I/flutter (11761): #20     Element.updateChild (package:flutter/src/widgets/framework.dart:2764:12)
I/flutter (11761): #21     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3750:16)
I/flutter (11761): #22     Element.rebuild (package:flutter/src/widgets/framework.dart:3565:5)
I/flutter (11761): #23     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3722:5)
I/flutter (11761): #24     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3717:5)
I/flutter (11761): #25     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2961:14)
I/flutter (11761): #26     Element.updateChild (package:flutter/src/widgets/framework.dart:2764:12)
I/flutter (11761): #27     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3750:16)
I/flutter (11761): #28     Element.rebuild (package:flutter/src/widgets/framework.dart:3565:5)
I/flutter (11761): #29     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3722:5)
I/flutter (11761): #30     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3717:5)
I/flutter (11761): #31     ParentDataElement.mount (package:flutter/src/widgets/framework.dart:4063:11)
I/flutter (11761): #32     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2961:14)
I/flutter (11761): #33     MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4982:32)
I/flutter (11761): #34     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2961:14)
I/flutter (11761): #35     Element.updateChild (package:flutter/src/widgets/framework.dart:2764:12)
I/flutter (11761): #36     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4876:14)
I/flutter (11761): #37     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2961:14)
I/flutter (11761): #38     Element.updateChild (package:flutter/src/widgets/framework.dart:2764:12)
I/flutter (11761): #39     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4876:14)
I/flutter (11761): #40     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2961:14)
I/flutter (11761): #41     Element.updateChild (package:flutter/src/widgets/framework.dart:2764:12)
I/flutter (11761): #42     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3750:16)
I/flutter (11761): #43     Element.rebuild (package:flutter/src/widgets/framework.dart:3565:5)
I/flutter (11761): #44     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3722:5)
I/flutter (11761): #45     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3717:5)
I/flutter (11761): #46     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2961:14)
I/flutter (11761): #47     MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4982:32)
I/flutter (11761): #48     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2961:14)
I/flutter (11761): #49     Element.updateChild (package:flutter/src/widgets/framework.dart:2764:12)
I/flutter (11761): #50     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4876:14)
I/flutter (11761): #51     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2961:14)
I/flutter (11761): #52     MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4982:32)
I/flutter (11761): #53     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2961:14)
I/flutter (11761): #54     Element.updateChild (package:flutter/src/widgets/framework.dart:2764:12)
I/flutter (11761): #55     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3750:16)
I/flutter (11761): #56     Element.rebuild (package:flutter/src/widgets/framework.dart:3565:5)
I/flutter (11761): #57     ProxyElement.update (package:flutter/src/widgets/framework.dart:4006:5)
I/flutter (11761): #58     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:15)
I/flutter (11761): #59     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4883:14)
I/flutter (11761): #60     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:15)
I/flutter (11761): #61     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3750:16)
I/flutter (11761): #62     Element.rebuild (package:flutter/src/widgets/framework.dart:3565:5)
I/flutter (11761): #63     StatelessElement.update (package:flutter/src/widgets/framework.dart:3796:5)
I/flutter (11761): #64     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:15)
I/flutter (11761): #65     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3750:16)
I/flutter (11761): #66     Element.rebuild (package:flutter/src/widgets/framework.dart:3565:5)
I/flutter (11761): #67     ProxyElement.update (package:flutter/src/widgets/framework.dart:4006:5)
I/flutter (11761): #68     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:15)
I/flutter (11761): #69     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3750:16)
I/flutter (11761): #70     Element.rebuild (package:flutter/src/widgets/framework.dart:3565:5)
I/flutter (11761): #71     ProxyElement.update (package:flutter/src/widgets/framework.dart:4006:5)
I/flutter (11761): #72     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:15)
I/flutter (11761): #73     RenderObjectElement.updateChildren (package:flutter/src/widgets/framework.dart:4601:32)
I/flutter (11761): #74     MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4992:17)
I/flutter (11761): #75     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:15)
I/flutter (11761): #76     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3750:16)
I/flutter (11761): #77     Element.rebuild (package:flutter/src/widgets/framework.dart:3565:5)
I/flutter (11761): #78     StatefulElement.update (package:flutter/src/widgets/framework.dart:3894:5)
I/flutter (11761): #79     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:15)
I/flutter (11761): #80     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3750:16)
I/flutter (11761): #81     Element.rebuild (package:flutter/src/widgets/framework.dart:3565:5)
I/flutter (11761): #82     ProxyElement.update (package:flutter/src/widgets/framework.dart:4006:5)
I/flutter (11761): #83     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:15)
I/flutter (11761): #84     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3750:16)
I/flutter (11761): #85     Element.rebuild (package:flutter/src/widgets/framework.dart:3565:5)
I/flutter (11761): #86     StatefulElement.update (package:flutter/src/widgets/framework.dart:3894:5)
I/flutter (11761): #87     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:15)
I/flutter (11761): #88     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4883:14)
I/flutter (11761): #89     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:15)
I/flutter (11761): #90     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3750:16)
I/flutter (11761): #91     Element.rebuild (package:flutter/src/widgets/framework.dart:3565:5)
I/flutter (11761): #92     StatelessElement.update (package:flutter/src/widgets/framework.dart:3796:5)
I/flutter (11761): #93     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:15)
I/flutter (11761): #94     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4883:14)
I/flutter (11761): #95     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:15)
I/flutter (11761): #96     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3750:16)
I/flutter (11761): #97     Element.rebuild (package:flutter/src/widgets/framework.dart:3565:5)
I/flutter (11761): #98     StatefulElement.update (package:flutter/src/widgets/framework.dart:3894:5)
I/flutter (11761): #99     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:15)
I/flutter (11761): #100    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3750:16)
I/flutter (11761): #101    Element.rebuild (package:flutter/src/widgets/framework.dart:3565:5)
I/flutter (11761): #102    StatefulElement.update (package:flutter/src/widgets/framework.dart:3894:5)
I/flutter (11761): #103    Element.updateChild (package:flutter/src/widgets/framework.dart:2753:15)
I/flutter (11761): #104    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3750:16)
I/flutter (11761): #105    Element.rebuild (package:flutter/src/widgets/framework.dart:3565:5)
I/flutter (11761): #106    ProxyElement.update (package:flutter/src/widgets/framework.dart:4006:5)
I/flutter (11761): #107    Element.updateChild (package:flutter/src/widgets/framework.dart:2753:15)
I/flutter (11761): #108    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3750:16)
I/flutter (11761): #109    Element.rebuild (package:flutter/src/widgets/framework.dart:3565:5)
I/flutter (11761): #110    ProxyElement.update (package:flutter/src/widgets/framework.dart:4006:5)
I/flutter (11761): #111    Element.updateChild (package:flutter/src/widgets/framework.dart:2753:15)
I/flutter (11761): #112    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3750:16)
I/flutter (11761): #113    Element.rebuild (package:flutter/src/widgets/framework.dart:3565:5)
I/flutter (11761): #114    StatefulElement.update (package:flutter/src/widgets/framework.dart:3894:5)
I/flutter (11761): #115    Element.updateChild (package:flutter/src/widgets/framework.dart:2753:15)
I/flutter (11761): #116    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3750:16)
I/flutter (11761): #117    Element.rebuild (package:flutter/src/widgets/framework.dart:3565:5)
I/flutter (11761): #118    StatefulElement.update (package:flutter/src/widgets/framework.dart:3894:5)
I/flutter (11761): #119    Element.updateChild (package:flutter/src/widgets/framework.dart:2753:15)
I/flutter (11761): #120    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3750:16)
I/flutter (11761): #121    Element.rebuild (package:flutter/src/widgets/framework.dart:3565:5)
I/flutter (11761): #122    BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2278:33)
I/flutter (11761): #123    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding&WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:700:20)
I/flutter (11761): #124    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:286:5)
I/flutter (11761): #125    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1012:15)
I/flutter (11761): #126    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:952:9)
I/flutter (11761): #127    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:864:5)
I/flutter (11761): #131    _invoke (dart:ui/hooks.dart:219:10)
I/flutter (11761): #132    _drawFrame (dart:ui/hooks.dart:178:3)
I/flutter (11761): (elided 5 frames from class _AssertionError and package dart:async)
I/flutter (11761): ════════════════════════════════════════════════════════════════════════════════════════════════════
I/flutter (11761): Another exception was thrown: 'package:flutter/src/widgets/framework.dart': Failed assertion: line 3817 pos 12: '_state._element == null': is not true.
```

**Comment by BondarenkoStas** [comment]
This is a question better suited for StackOverflow, since there doesn’t seem to be anything wrong with Flutter itself, but related to the implementation. Closing, as this is not an issue report. See https://flutter.dev/community for support options.
If you disagree, feel free to comment and I will reopen the issue.
