### ISSUE TITLE
[google_maps_flutter] app crash after launch

### ISSUE THREAD

**Issue by BenBao93** [flutter/flutter#37678]
After adding the google maps package to my project the app keeps crashing right after launch. Seemingly the app crashes so quick that the debugger is unable to read any exceptions and remains in the 'installing' phase, despite the app having launched and crashed.

I have no import of the package or any code, it crashes from just adding the package.

## Steps to Reproduce

1. Add google maps flutter package latest (0.5.20+1) to pubspec.yaml
2. App crashes upon launch

## Logs

By attaching a physical device to test I was able to extract these logs:

`java.lang.RuntimeException: Unable to instantiate activity ComponentInfo{com............./com................MainActivity}: java.lang.ClassNotFoundException: Didn't find class "com...............MainActivity" on path: DexPathList[[zip file "/data/app/com...........-qRKkvwDPfrnh5VO0RW4KKw==/base.apk"],nativeLibraryDirectories=[/data/app/com...................-qRKkvwDPfrnh5VO0RW4KKw==/lib/arm64, /data/app/com....................-qRKkvwDPfrnh5VO0RW4KKw==/base.apk!/lib/arm64-v8a, /system/lib64]]
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2876)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3081)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1831)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:201)
	at android.app.ActivityThread.main(ActivityThread.java:6810)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:873)
Caused by: java.lang.ClassNotFoundException: Didn't find class "com....................MainActivity" on path: DexPathList[[zip file "/data/app/com...............-qRKkvwDPfrnh5VO0RW4KKw==/base.apk"],nativeLibraryDirectories=[/data/app/com................-qRKkvwDPfrnh5VO0RW4KKw==/lib/arm64, /data/app/com..................-qRKkvwDPfrnh5VO0RW4KKw==/base.apk!/lib/arm64-v8a, /system/lib64]]
	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:134)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
	at android.app.AppComponentFactory.instantiateActivity(AppComponentFactory.java:69)
	at androidx.core.app.CoreComponentFactory.instantiateActivity(CoreComponentFactory.java:43)
	at android.app.Instrumentation.newActivity(Instrumentation.java:1216)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2864)
	... 11 more
`

**Comment by BenBao93** [comment]
After updating the flutter sdk to version v1.7.8+hotfix.4 and using the recently released maps plugin update to 0.5.20+2 this seems to be resolved.
