### ISSUE TITLE
HeroController._getMostValuableKeys throws an exception

### ISSUE THREAD

**Issue by danrubel** [flutter/flutter#3769]
## Steps to Reproduce

Launched the app on my Android phone then picked up and logged into the phone more or less at the same time as the app was launching. I've only seen this exception once.

## Flutter Doctor
```
[✓] Flutter (on Mac OS, channel master)
    • Flutter at /Users/danrubel/home/git/flutter/flutter
    • Framework revision a9b965cb9b (3 days ago), engine revision d85ead8ec2

[✓] Android toolchain - develop for Android devices (Android SDK 22.0.1)
    • Android SDK at /Users/danrubel/Library/Android/sdk
    • Platform android-22, build-tools 22.0.1
    • Java(TM) SE Runtime Environment (build 1.8.0_72-b15)

[✓] iOS toolchain - develop for iOS devices (Xcode 7.2.1)
    • XCode at /Applications/Xcode.app/Contents/Developer
    • Xcode 7.2.1, Build version 7C1002
    x ideviceinstaller not available; this is used to discover connected iOS devices.
      Install via 'brew install ideviceinstaller'.
    x ios-deploy not available; this is used to deploy to connected iOS devices.
      Install via 'brew install ios-deploy'.

[✓] Atom - a lightweight development environment for Flutter
    • Atom installed; Flutter plugin version 0.2.2
```
## Logs and Crash Reports
```
Installing app.apk to Nexus 5X...
Running lib/main.dart on Nexus 5X...
Observatory listening on http://127.0.0.1:16223
Diagnostic server listening on http://127.0.0.1:8101
Showing Nexus 5X logs:
--------- beginning of main
I/flutter : Diagnostic server listening on http://127.0.0.1:47736
--------- beginning of system
I/flutter : ══╡ EXCEPTION CAUGHT BY SCHEDULER LIBRARY ╞═════════════════════════════════════════════════════════
I/flutter : The following assertion was thrown during a scheduler callback:
I/flutter : 'package:flutter/src/widgets/heroes.dart': Failed assertion: line 481: '_from != null' is not true.
I/flutter : Either the assertion indicates an error in the framework itself, or we should provide substantially
I/flutter : more information in this error message to help you determine and fix the underlying cause.
I/flutter : In either case, please report this assertion by filing a bug on GitHub:
I/flutter :   https://github.com/flutter/flutter/issues/new
I/flutter : When the exception was thrown, this was the stack:
I/flutter : #0      _AssertionError._throwNew (dart:core-patch/errors_patch.dart:27)
I/flutter : #1      HeroController._getMostValuableKeys (package:flutter/src/widgets/heroes.dart:481)
I/flutter : #2      HeroController._updateQuest (package:flutter/src/widgets/heroes.dart:492)
I/flutter : #3      BindingBase&SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:393)
I/flutter : #4      BindingBase&SchedulerBinding.handleBeginFrame (package:flutter/src/scheduler/binding.dart:362)
I/flutter : #5      _beginFrame (file:///b/build/slave/Linux_Engine/build/src/out/android_Release/gen/sky/bindings/hooks.dart:48)
I/flutter : ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
1 item1 processlib/connection.dart5:1
LFUTF-8Dartmaster
```

**Comment by abarth** [comment]
@Hixie

**Comment by HansMuller** [comment]
The most valuable keys feature has been removed: #5500
