### ISSUE TITLE
Latest Add2App changes fail to load flutter test iOS app with plugins

### ISSUE THREAD

**Issue by BernardGatt** [flutter/flutter#37756]
## Steps to Reproduce

1. Create a Flutter Module
2. Add a dependency that contains a native iOS plugin ex `shared_preferences: 0.5.0`
3. Run

## Logs

```
[DEVICE LOG] 2019-08-07 08:39:27.141956+0200  localhost Runner[2036]: (Flutter) [VERBOSE-2:engine.cc(120)] Engine run configuration was invalid.
[VERBOSE-2:engine.cc(120)] Engine run configuration was invalid.
[DEVICE LOG] 2019-08-07 08:39:27.142038+0200  localhost Runner[2036]: (Flutter) [VERBOSE-2:shell.cc(407)] Could not launch engine with configuration.
[VERBOSE-2:shell.cc(407)] Could not launch engine with configuration.
```

```
No issues found! (ran in 1.8s)
```

```
[✓] Flutter (Channel master, v1.8.4-pre.127, on Mac OS X 10.14.5 18F203, locale en-MT)
    • Flutter version 1.8.4-pre.127 at /Users/dev/Development/flutter
    • Framework revision c08a3c7a0a (63 minutes ago), 2019-08-06 22:38:09 -0700
    • Engine revision 4291770479
    • Dart version 2.5.0 (build 2.5.0-dev.1.0 574c4a51c6)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/dev/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 10.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.3, Build version 10G8
    • CocoaPods version 1.7.3

[✓] Android Studio (version 3.4)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 38.1.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

[✓] VS Code (version 1.36.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.3.0

[✓] Connected device (1 available)
    • iPhone Xʀ • 0121CCE3-D8B9-4BC2-8AFA-02D5DA296B21 • ios • com.apple.CoreSimulator.SimRuntime.iOS-12-4 (simulator)
```

**Comment by jmagman** [comment]
Does step 3 `Run` mean `flutter run` from the module directory?  Or are you running from one of the Xcode projects.
I made a new module inside an existing app, added `shared_preferences: 0.5.0` and then `flutter packages get` then `flutter run` from the module directory and I don't see that error.

**Comment by BernardGatt** [comment]
Yes, from the module directory.

This is happening on a new standalone module when running the test app inside .ios folder.

**Comment by jmagman** [comment]
And you ran `flutter packages get` after adding the plugin?

**Comment by BernardGatt** [comment]
Same issue.

Just tested with a new module to remove any variables.

This is what I did:
```
flutter create -t module my_flutter
cd my_flutter
flutter run
```
👍 

Then proceeded to add ``shared_preferences: 0.5.0`` to pubspec.yaml

```
flutter packages get
flutter run
```

💥💥

```
[VERBOSE-2:shell.cc(178)] Dart Error: Can't load Kernel binary: Invalid kernel binary format version.
[VERBOSE-2:engine.cc(176)] Could not prepare to run the isolate.
[VERBOSE-2:engine.cc(123)] Engine not prepare and launch isolate.
[VERBOSE-2:FlutterEngine.mm(294)] Could not launch engine with configuration.
vm-service: Error: Unhandled exception:
Unrecognized response: null
#0      new Response.from (dart:_vmservice/message_router.dart:70:7)
#1      Message._setResponseFromPort (dart:_vmservice/message.dart:244:29)
#2      Message.sendToVM.<anonymous closure> (dart:_vmservice/message.dart:216:7)
#3      _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:171:12)
```

**Comment by jmagman** [comment]
I wasn't able to reproduce your exact error, but I do see a pretty large problem where the local engine isn't being embedded.
Can you try adding install_flutter_engine_pod to your module's .ios/Podfile (not the existing app) target 'Runner'?
```
target 'Runner' do
  install_flutter_engine_pod
  install_flutter_plugin_pods flutter_application_path
end
```

**Comment by BernardGatt** [comment]
That did it :)

Thanks for your help!

**Comment by jmagman** [comment]
@BernardGatt And thank you for your detailed issue! Fix incoming...
