### ISSUE TITLE
Exception thrown while building "Title" when using mojo shell to run a Material app

### ISSUE THREAD

**Issue by aghassemi** [flutter/flutter#378]
When running a Flutter app in mojo shell, I always get a red screen at the beginning because of the following exception:
```
Exception caught while building Title("MyTitle")
The null object does not have a getter 'ptr'.

NoSuchMethodError: method not found: 'ptr'
Receiver: null
Arguments: []
Stack trace:
#0      Object._noSuchMethod (dart:core-patch/object_patch.dart:42)
#1      Object.noSuchMethod (dart:core-patch/object_patch.dart:45)
#2      ApplicationConnection.requestService (packages/mojo/src/application_connection.dart:89)
#3      _Shell._connectToService (packages/flutter/src/services/shell.dart:59)
#4      _Shell.connectToService (packages/flutter/src/services/shell.dart:74)
#5      _initActivityProxy (packages/flutter/src/services/activity.dart:25)
#6      _activityProxy (packages/flutter/src/services/activity.dart:29)
#7      _activityProxy (packages/flutter/src/services/activity.dart:29)
#8      updateTaskDescription (packages/flutter/src/services/activity.dart:65)
#9      Title.build (packages/flutter/src/material/title.dart:17)
#10     ComponentElement.performRebuild (packages/flutter/src/widgets/framework.dart:1050)
#11     BuildableElement.rebuild (packages/flutter/src/widgets/framework.dart:991)
#12     ComponentElement._firstBuild (packages/flutter/src/widgets/framework.dart:1037)
#13     ComponentElement.mount (packages/flutter/src/widgets/framework.dart:1032)
#14     Element._inflateWidget (packages/flutter/src/widgets/framework.dart:765)
#15     Element.updateChild (packages/flutter/src/widgets/framework.dart:644)
#16     ComponentElement.performRebuild (packages/flutter/src/widgets/framework.dart:1062)
#17     BuildableElement.rebuild (packages/flutter/src/widgets/framework.dart:991)
#18     ComponentElement._firstBuild (packages/flutter/src/widgets/framework.dart:1037)
#19     ComponentElement.mount (packages/flutter/src/widgets/framework.dart:1032)
#20     Element._inflateWidget (packages/flutter/src/widgets/framework.dart:765)
#21     Element.updateChild (packages/flutter/src/widgets/framework.dart:644)
#22     ComponentElement.performRebuild (packages/flutter/src/widgets/framework.dart:1062)
#23     BuildableElement.rebuild (packages/flutter/src/widgets/framework.dart:991)
#24     ComponentElement._firstBuild (packages/flutter/src/widgets/framework.dart:1037)
#25     ComponentElement.mount (packages/flutter/src/widgets/framework.dart:1032)
#26     Element._inflateWidget (packages/flutter/src/widgets/framework.dart:765)
#27     Element.updateChild (packages/flutter/src/widgets/framework.dart:644)
#28     ComponentElement.performRebuild (packages/flutter/src/widgets/framework.dart:1062)
#29     BuildableElement.rebuild (packages/flutter/src/widgets/framework.dart:991)
#30     ComponentElement._firstBuild (packages/flutter/src/widgets/framework.dart:1037)
#31     ComponentElement.mount (packages/flutter/src/widgets/framework.dart:1032)
#32     Element._inflateWidget (packages/flutter/src/widgets/framework.dart:765)
#33     Element.updateChild (packages/flutter/src/widgets/framework.dart:644)
#34     ComponentElement.performRebuild (packages/flutter/src/widgets/framework.dart:1062)
#35     BuildableElement.rebuild (packages/flutter/src/widgets/framework.dart:991)
#36     ComponentElement._firstBuild (packages/flutter/src/widgets/framework.dart:1037)
#37     ComponentElement.mount (packages/flutter/src/widgets/framework.dart:1032)
#38     Element._inflateWidget (packages/flutter/src/widgets/framework.dart:765)
#39     Element.updateChild (packages/flutter/src/widgets/framework.dart:644)
#40     ComponentElement.performRebuild (packages/flutter/src/widgets/framework.dart:1062)
#41     BuildableElement.rebuild (packages/flutter/src/widgets/framework.dart:991)
#42     ComponentElement._firstBuild (packages/flutter/src/widgets/framework.dart:1037)
#43     StatefulComponentElement._firstBuild (packages/flutter/src/widgets/framework.dart:1131)
#44     ComponentElement.mount (packages/flutter/src/widgets/framework.dart:1032)
#45     Element._inflateWidget (packages/flutter/src/widgets/framework.dart:765)
#46     Element.updateChild (packages/flutter/src/widgets/framework.dart:644)
#47     RenderObjectToWidgetElement.mount (packages/flutter/src/widgets/binding.dart:149)
#48     RenderObjectToWidgetAdapter.attachToRenderTree.<anonymous closure> (packages/flutter/src/widgets/binding.dart:117)
#49     BuildableElement.lockState (packages/flutter/src/widgets/framework.dart:924)
#50     RenderObjectToWidgetAdapter.attachToRenderTree (packages/flutter/src/widgets/binding.dart:114)
#51     WidgetFlutterBinding._runApp (packages/flutter/src/widgets/binding.dart:76)
#52     runApp (packages/flutter/src/widgets/binding.dart:83)
#53     main (lib/main.dart:25)
```

but rotating the device to rebuild the app fixes the issue.

This can be reproduced simply by this main code
```
import 'package:flutter/material.dart';

void main() {
  runApp(new MaterialApp(
      title: 'MyTitle',
      routes: {'/': (RouteArguments args) => new Container()}));
}
```

Looks like `runApp` is trying to talk to Android for setting up the toolbar too early, but on the second rebuild after rotating the phone things are setup and it succeeds.

This started happening about a week ago, it was fine before that. 

@abarth @jamesr 

CC @mishadynin

**Comment by abarth** [comment]
I believe this is fixed on top-of-tree.  At least, when I looked at the issue with @jimbeveridge, we had something that worked in his setup.

**Comment by aghassemi** [comment]
@abarth I am still using Flutter from pub. I will update to the new flow and check out Flutter at head soon and update the issue accordingly.

**Comment by IvBaranov** [comment]
Got the same issue, but with input widget:
```
-- EXCEPTION IN SCHEDULER CALLBACK --
The null object does not have a getter 'attached'.

NoSuchMethodError: method not found: 'attached'
Receiver: null
Arguments: []
Stack trace:
#0      Object._noSuchMethod (dart:core-patch/object_patch.dart:42)
#1      Object.noSuchMethod (dart:core-patch/object_patch.dart:45)
#2      InputState.dispose (packages/flutter/src/material/input.dart:146)
#3      StatefulComponentElement.unmount (packages/flutter/src/widgets/framework.dart:1154)
#4      _InactiveElements._unmount (packages/flutter/src/widgets/framework.dart:476)
#5      _InactiveElements._unmount.<anonymous closure> (packages/flutter/src/widgets/framework.dart:480)
#6      MultiChildRenderObjectElement.visitChildren (packages/flutter/src/widgets/framework.dart:1625)
#7      _InactiveElements._unmount (packages/flutter/src/widgets/framework.dart:478)
#8      _InactiveElements._unmount.<anonymous closure> (packages/flutter/src/widgets/framework.dart:480)
#9      OneChildRenderObjectElement.visitChildren (packages/flutter/src/widgets/framework.dart:1540)
#10     _InactiveElements._unmount (packages/flutter/src/widgets/framework.dart:478)
#11     _InactiveElements._unmount.<anonymous closure


Exception caught while building Input-[GlobalKey 731563076]
The null object does not have a getter 'attached'.
NoSuchMethodError: method not found: 'attached'
Receiver: null
Arguments: []
Stack trace:
#0      Object._noSuchMethod (dart:core-patch/object_patch.dart:42)
#1      Object.noSuchMethod (dart:core-patch/object_patch.dart:45)
#2      InputState.buildContent (packages/flutter/src/material/input.dart:81)
#3      ScrollableState.build (packages/flutter/src/widgets/scrollable.dart:108)
#4      ComponentElement.performRebuild (packages/flutter/src/widgets/framework.dart:1050)
#5      BuildableElement.rebuild (packages/flutter/src/widgets/framework.dart:991)
#6      StatefulComponentElement.update (packages/flutter/src/widgets/framework.dart:1149)
#7      Element.updateChild (packages/flutter/src/widgets/framework.dart:637)
#8      RenderObjectElement.updateChildren (packages/flutter/src/widgets/framework.dart:1448)
#9      MultiChildRenderObjectElement.update (packages/flutter/src/widgets/framework.dart:1642)
#10     Element.updateChild (packages/flutter/src/widgets/framework.dart:637)
#11     OneChildRenderObjectElement.update (packages/flutter/src/widgets/framework.dart:1558)
#12     Element.updateChild (packages/flutter/src/widgets/framework.dart:637)
#13     ComponentElement.performRebuild (packages/flutter/src/widgets/framework.dart:1062)
#14     BuildableElement.rebuild (packages/flutter/src/widgets/framework.dart:991)
#15     StatelessComponentElement.update (packages/flutter/src/widgets/framework.dart:1095)
#16     Element.updateChild (packages/flutter/src/widgets/framework.dart:637)
#17     ComponentElement.performRebuild (packages/flutter/src/widgets/framework.dart:1062)
#18     BuildableElement.rebuild (packages/flutter/src/widgets/framework.dart:991)
#19     ProxyElement.update (packages/flutter/src/widgets/framework.dart:1186)
#20     Element.updateChild (packages/flutter/src/widgets/framework.dart:637)
#21     OneChildRenderObjectElement.update (packages/flutter/src/widgets/framework.dart:1558)
#22     Element.updateChild (packages/flutter/src/widgets/framework.dart:637)
#23     ComponentElement.performRebuild (packages/flutter/src/widgets/framework.dart:1062)
#24     BuildableElement.rebuild (packages/flutter/src/widgets/framework.dart:991)
#25     StatelessComponentElement.update (packages/flutter/src/widgets/framework.dart:1095)
#26     Element.updateChild (packages/flutter/src/widgets/framework.dart:637)
#27     ComponentElement.performRebuild (packages/flutter/src/widgets/framework.dart:1062)
#28     BuildableElement.rebuild (packages/flutter/src/widgets/framework.dart:991)
#29     StatefulComponentElement.update (packages/flutter/src/widgets/framework.dart:1149)
#30     Element.updateChild (packages/flutter/src/widgets/framework.dart:637)
#31     ComponentElement.performRebuild (packages/flutter/src/widgets/framework.dart:1062)
#32     BuildableElement.rebuild (packages/flutter/src/widgets/framework.dart:991)
#33     ProxyElement.update (packages/flutter/src/widgets/framework.dart:1186)
#34     Element.updateChild (packages/flutter/src/widgets/framework.dart:637)
#35     ComponentElement.performRebuild (packages/flutter/src/widgets/framework.dart:1062)
#36     BuildableElement.rebuild (packages/flutter/src/widgets/framework.dart:991)
#37     StatelessComponentElement.update (packages/flutter/src/widgets/framework.dart:1095)
#38     Element.updateChild (packages/flutter/src/widgets/framework.dart:637)
#39     ComponentElement.performRebuild (packages/flutter/src/widgets/framework.dart:1062)
#40     BuildableElement.rebuild (packages/flutter/src/widgets/framework.dart:991)
#41     ProxyElement.update (packages/flutter/src/widgets/framework.dart:1186)
#42     Element.updateChild (packages/flutter/src/widgets/framework.dart:637)
#43     RenderObjectElement.updateChildren (packages/flutter/src/widgets/framework.dart:1448)
#44     MultiChildRenderObjectElement.update (packages/flutter/src/widgets/framework.dart:1642)
#45     Element.updateChild (packages/flutter/src/widgets/framework.dart:637)
#46     ComponentElement.performRebuild (packages/flutter/src/widgets/framework.dart:1062)
#47     BuildableElement.rebuild (packages/flutter/src/widgets/framework.dart:991)
#48     StatelessComponentElement.update (packages/flutter/src/widgets/framework.dart:1095)
#49     Element.updateChild (packages/flutter/src/widgets/framework.dart:637)
#50     ComponentElement.performRebuild (packages/flutter/src/widgets/framework.dart:1062)
#51     BuildableElement.rebuild (packages/flutter/src/widgets/framework.dart:991)
#52     StatefulComponentElement.update (packages/flutter/src/widgets/framework.dart:1149)
#53     Element.updateChild (packages/flutter/src/widgets/framework.dart:637)
#54     ComponentElement.performRebuild (packages/flutter/src/widgets/framework.dart:1062)
#55     BuildableElement.rebuild (packages/flutter/src/widgets/framework.dart:991)
#56     StatelessComponentElement.update (packages/flutter/src/widgets/framework.dart:1095)
#57     Element.updateChild (packages/flutter/src/widgets/framework.dart:637)
#58     Element._inflateWidget (packages/flutter/src/widgets/framework.dart:759)
#59     Element.updateChild (packages/flutter/src/widgets/framework.dart:644)
#60     OneChildRenderObjectElement.mount (packages/flutter/src/widgets/framework.dart:1552)
#61     Element._inflateWidget (packages/flutter/src/widgets/framework.dart:765)
#62     Element.updateChild (packages/flutter/src/widgets/framework.dart:644)
#63     OneChildRenderObjectElement.mount (packages/flutter/src/widgets/framework.dart:1552)
#64     Element._inflateWidget (packages/flutter/src/widgets/framework.dart:765)
#65     Element.updateChild (packages/flutter/src/widgets/framework.dart:644)
#66     ComponentElement.performRebuild (packages/flutter/src/widgets/framework.dart:1062)
#67     BuildableElement.rebuild (packages/flutter/src/widgets/framework.dart:991)
#68     ComponentElement._firstBuild (packages/flutter/src/widgets/framework.dart:1037)
#69     StatefulComponentElement._firstBuild (packages/flutter/src/widgets/framework.dart:1131)
#70     ComponentElement.mount (packages/flutter/src/widgets/framework.dart:1032)
#71     Element._inflateWidget (packages/flutter/src/widgets/framework.dart:765)
#72     Element.updateChild (packages/flutter/src/widgets/framework.dart:644)
#73     ComponentElement.performRebuild (packages/flutter/src/widgets/framework.dart:1062)
#74     BuildableElement.rebuild (packages/flutter/src/widgets/framework.dart:991)
#75     WidgetFlutterBinding.buildDirtyElements.<anonymous closure> (packages/flutter/src/widgets/binding.dart:55)
#76     BuildableElement.lockState (packages/flutter/src/widgets/framework.dart:924)
#77     WidgetFlutterBinding.buildDirtyElements (packages/flutter/src/widgets/binding.dart:50)
#78     WidgetFlutterBinding.beginFrame (packages/flutter/src/widgets/binding.dart:26)
#79     FlutterBinding._handlePersistentFrameCallback (packages/flutter/src/rendering/binding.dart:184)
#80     Scheduler.invokeCallback (packages/flutter/src/animation/scheduler.dart:81)
#81     Scheduler.beginFrame (packages/flutter/src/animation/scheduler.dart:67)
#82     _beginFrame (file:///usr/local/google/home/johnmccutchan/workspace/flutter/engine/src/out/android_Release/gen/sky/bindings/Customhooks.dart:35)

```

**Comment by abarth** [comment]
> Got the same issue, but with input widget:

That looks like a separate issue.  Would you be willing to file a new bug about that issue along with the steps to reproduce it?  Thanks!

**Comment by IvBaranov** [comment]
@abarth Exception thrown while building widgets #381

**Comment by aghassemi** [comment]
Verified that not an issue @ HEAD of Flutter. Closing.
