### ISSUE TITLE
FileSystemException when launching flutter even with correct permissions

### ISSUE THREAD

**Issue by txtsd** [flutter/flutter#37858]
It was running fine on `1.7.8.hotfix.3`. This started happening after the update to `1.7.8.hotfix.4`. Additionally, `adb devices -l` just stalls in Android Studio, and does nothing.
`touch /opt/flutter/bin/cache/flutter_version_check.stamp` with correct permissions does not fix the issue either.

## Steps to Reproduce

1. Run `flutter` in terminal.
2. It spits out `Oops; flutter has exited unexpectedly.` immediately.

## Logs
Flutter crash report; please file at https://github.com/flutter/flutter/issues.

## command

flutter 

## exception

FileSystemException: FileSystemException: Cannot open file, path = '/opt/flutter/bin/cache/flutter_version_check.stamp' (OS Error: Permission denied, errno = 13)

```
#0      _File.throwIfError (dart:io/file_impl.dart:643:7)
#1      _File.openSync (dart:io/file_impl.dart:487:5)
#2      _File.writeAsBytesSync (dart:io/file_impl.dart:612:31)
#3      _File.writeAsStringSync (dart:io/file_impl.dart:636:5)
#4      _LocalFile&LocalFileSystemEntity&ForwardingFile.writeAsStringSync (package:file/src/forwarding/forwarding_file.dart:152:16)
#5      Cache.setStampFor (package:flutter_tools/src/cache.dart:243:35)
#6      VersionCheckStamp.store (package:flutter_tools/src/version.dart:469:20)
<asynchronous suspension>
#7      FlutterVersion._getLatestAvailableFlutterDate (package:flutter_tools/src/version.dart:391:31)
<asynchronous suspension>
#8      FlutterVersion.checkFlutterVersionFreshness (package:flutter_tools/src/version.dart:296:52)
<asynchronous suspension>
#9      FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:372:41)
<asynchronous suspension>
#10     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:29)
<asynchronous suspension>
#11     _rootRun (dart:async/zone.dart:1124:13)
#12     _CustomZone.run (dart:async/zone.dart:1021:19)
#13     _runZoned (dart:async/zone.dart:1516:10)
#14     runZoned (dart:async/zone.dart:1463:12)
#15     AppContext.run (package:flutter_tools/src/base/context.dart:152:18)
<asynchronous suspension>
#16     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:356:19)
<asynchronous suspension>
#17     CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:112:25)
#18     new Future.sync (dart:async/future.dart:224:31)
#19     CommandRunner.run (package:args/command_runner.dart:112:14)
#20     FlutterCommandRunner.run (package:flutter_tools/src/runner/flutter_command_runner.dart:242:18)
#21     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:62:22)
<asynchronous suspension>
#22     _rootRun (dart:async/zone.dart:1124:13)
#23     _CustomZone.run (dart:async/zone.dart:1021:19)
#24     _runZoned (dart:async/zone.dart:1516:10)
#25     runZoned (dart:async/zone.dart:1500:12)
#26     run.<anonymous closure> (package:flutter_tools/runner.dart:60:18)
<asynchronous suspension>
#27     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:29)
<asynchronous suspension>
#28     _rootRun (dart:async/zone.dart:1124:13)
#29     _CustomZone.run (dart:async/zone.dart:1021:19)
#30     _runZoned (dart:async/zone.dart:1516:10)
#31     runZoned (dart:async/zone.dart:1463:12)
#32     AppContext.run (package:flutter_tools/src/base/context.dart:152:18)
<asynchronous suspension>
#33     runInContext (package:flutter_tools/src/context_runner.dart:56:24)
<asynchronous suspension>
#34     run (package:flutter_tools/runner.dart:51:10)
#35     main (package:flutter_tools/executable.dart:62:9)
<asynchronous suspension>
#36     main (file:///b/s/w/ir/k/archive/flutter/packages/flutter_tools/bin/flutter_tools.dart:8:3)
#37     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:299:32)
#38     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:12)
```

```
[✓] Flutter (Channel stable, v1.7.8+hotfix.4, on Linux, locale en_US.UTF-8)
    • Flutter version 1.7.8+hotfix.4 at /opt/flutter
    • Framework revision 20e59316b8 (3 weeks ago), 2019-07-18 20:04:33 -0700
    • Engine revision d004bcd4d6
    • Dart version 2.4.0

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /opt/android-sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = /opt/android-sdk
    • Java binary at: /opt/android-studio/jre/bin/java
    • Java version openjdk version "1.8.0_152-release"
    • All Android licenses accepted.

[✓] Android Studio (version 3.4)
    • Android Studio at /opt/android-studio
    • Flutter plugin version 38.1.1
    • Dart plugin version 183.6270
    • Java version openjdk version "1.8.0_152-release"

[!] Connected device
    ! No devices available

! Doctor found issues in 1 category.
```

**Comment by jonahwilliams** [comment]
It doesn't look like you have the correct permissions here. Nevertheless we shouldn't crash

**Comment by txtsd** [comment]
`/opt/flutter` and everything underneath belongs to the group flutterusers, which the user I run as is a part of.

It worked fine this way until the latest hotfix.
