### ISSUE TITLE
Flutter Module -> Dart Error: Can't load Kernel binary: Invalid kernel binary format version.

### ISSUE THREAD

**Issue by vishna** [flutter/flutter#37852]
iOS Simulator white screen of death

## Steps to Reproduce

Based on: [Add Flutter to existing apps](https://github.com/flutter/flutter/wiki/Add-Flutter-to-existing-apps) page.

0. Have iOS simulator running.
1. Switch to master channel `flutter channel master`
2. Create flutter module `flutter create -t module my_flutter`
3. Go to module directory execute `flutter run`
4. Observe beautiful flutter counter app running on iOS Simulator 🎉 
5. Now add `cached_network_image: ^1.1.1` to `pubspec.yaml`
5. Do `flutter run` again and enter the sadness 😭

Here's a script to repro: https://gist.github.com/vishna/a171fc4420e2fc2b90b8254bc3bde0f7

## Logs

```
Running "flutter pub get" in my_flutter...                      4.0s
Launching lib/main.dart on iPhone Xʀ in debug mode...
Running pod install...                                              2.1s
Running Xcode build...                                                  
                                                   
 ├─Assembling Flutter resources...                           7.7s
 └─Compiling, linking and signing...                        13.9s
Xcode build done.                                           26.2s
[VERBOSE-2:shell.cc(178)] Dart Error: Can't load Kernel binary: Invalid kernel binary format version.
[VERBOSE-2:engine.cc(176)] Could not prepare to run the isolate.
[VERBOSE-2:engine.cc(123)] Engine not prepare and launch isolate.
[VERBOSE-2:FlutterEngine.mm(294)] Could not launch engine with configuration.
vm-service: Error: Unhandled exception:
Unrecognized response: null
#0      new Response.from (dart:_vmservice/message_router.dart:70:7)
#1      Message._setResponseFromPort (dart:_vmservice/message.dart:244:29)
#2      Message.sendToVM.<anonymous closure> (dart:_vmservice/message.dart:216:7)
#3      _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:171:12)
```

```
[✓] Flutter (Channel master, v1.8.5-pre.64, on Mac OS X 10.14.6 18G87, locale en-DE)
    • Flutter version 1.8.5-pre.64 at /Users/vishna/flutter
    • Framework revision b11c5acaa6 (17 hours ago), 2019-08-07 10:16:33 -0700
    • Engine revision 739b2dd4b2
    • Dart version 2.5.0 (build 2.5.0-dev.1.0 c262cbd414)

[✓] Xcode - develop for iOS and macOS (Xcode 10.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.2.1, Build version 10E1001
    • CocoaPods version 1.6.0

[✓] Connected device (1 available)
    • iPhone Xʀ • 9EBC1F10-02BA-478C-AA61-553015BCAA69 • ios • com.apple.CoreSimulator.SimRuntime.iOS-12-2 (simulator)
```

**Comment by jason-simmons** [comment]
Looks like this is associated with https://github.com/flutter/flutter/commit/bd47a31e32d7c65ef35524f3bf18655e513e3a5b

@jmagman

**Comment by jmagman** [comment]
Can you try adding install_flutter_engine_pod to your module's .ios/Podfile (not the existing app) target 'Runner'?
```
target 'Runner' do
  install_flutter_engine_pod
  install_flutter_plugin_pods flutter_application_path
end
```

**Comment by vishna** [comment]
That fixes the problem  🎉Hoping your PR gets merged soon.

**Comment by sramac2** [comment]
[https://fantashit.com/invalid-kernel-binary-format-version/] this solution worked for me, I deleted the cache folder inside my flutter folder and when I ran`flutter doctor -v` dart SDK and all other required folders will be installed. This solved the issue for me after so long
