### ISSUE TITLE
Plenty of spam in logs while running flutter run

### ISSUE THREAD

**Issue by MaskyS** [flutter/flutter#37859]
I'm not sure if this is because of flutter or one of its plugins. I remember running flutter run in verbose mode once, but running in normal mode also dumps hundreds of lines into by debug console, like:

```
F/m.android.phon(24685): runtime.cc:558]   kernel: ep_poll+0x28e/0x33f
F/m.android.phon(24685): runtime.cc:558]   kernel: SyS_epoll_wait+0x96/0xb4
F/m.android.phon(24685): runtime.cc:558]   kernel: SyS_epoll_pwait+0x93/0x114
F/m.android.phon(24685): runtime.cc:558]   kernel: do_fast_syscall_32+0xd5/0x148
F/m.android.phon(24685): runtime.cc:558]   at android.os.Looper.loop(Looper.java:160)
F/m.android.phon(24685): runtime.cc:558]   at android.os.HandlerThread.run(HandlerThread.java:65)
F/m.android.phon(24685): runtime.cc:558]
...
F/m.android.phon(30185): runtime.cc:558]   native: #10 pc 0008f065  /system/lib/libc.so (__pthread_start(void*)+53)
F/m.android.phon(30185): runtime.cc:558]   native: #11 pc 0002485b  /system/lib/libc.so (__start_thread+75)
F/m.android.phon(30185): runtime.cc:558]   (no managed stack frames)
F/m.android.phon(30185): runtime.cc:558]
F/m.android.phon(30185): runtime.cc:558] "LocaleTracker" prio=5 tid=20 Native
F/m.android.phon(30185): runtime.cc:558]   | group="" sCount=1 dsCount=0 flags=1 obj=0x12f80818 self=0xde1ec000
F/m.android.phon(30185): runtime.cc:558]   | sysTid=30213 nice=0 ...
```

I can't really debug now.
Previous context: I hadn't been developing for months, came back, upgraded flutter, and found that previously perfectly fine code now spat out undecipherable messages because of the androidx update. I tried following Flutter's guides for migrating to androidx and the suggested solutions on the hundreds of issue threads opened here but didn't work. Had to create a fresh project, add all plugin dependencies one by one, then copy all my code over for it to finally work. Then I did the above and the logs haven't stopped since.

## Logs

`flutter doctor -v`

```
[✓] Flutter (Channel beta, v1.7.8+hotfix.4, on Linux, locale en_US.UTF-8)
    • Flutter version 1.7.8+hotfix.4 at /home/maskys/devel/flutter
    • Framework revision 20e59316b8 (3 weeks ago), 2019-07-18 20:04:33 -0700
    • Engine revision fee001c93f
    • Dart version 2.4.0

 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /home/maskys/Android/Sdk
    • Android NDK location not configured (optional; useful for native profiling
      support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /opt/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_152-release-1136-b06)
    • All Android licenses accepted.

[!] Android Studio (version 3.2)
    • Android Studio at /opt/android-studio
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build
      1.8.0_152-release-1136-b06)

[✓] VS Code (version 1.36.1)
    • VS Code at /usr/share/code
    • Flutter extension version 3.3.0

[✓] Connected device (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 9 (API
      28) (emulator)

! Doctor found issues in 1 category.

```

`flutter analyze` returned only some unrelated minor errors.

```
   info • This class (or a class which this class inherits from) is marked as
          '@immutable', but one or more of its instance fields are not final:
          RateDialog.buildContext • lib/UI/rate_dialog.dart:4:7 •
          must_be_immutable
   info • The value of the local variable 'borderDeco' isn't used •
          lib/UI/steps/year.dart:28:11 • unused_local_variable
   info • This class (or a class which this class inherits from) is marked as
          '@immutable', but one or more of its instance fields are not final:
          ClassTile.isOngoing, ClassTile.formatter •
          lib/pages/schedule.dart:254:7 • must_be_immutable
   info • The value of the local variable 'appName' isn't used •
          lib/pages/settings.dart:39:12 • unused_local_variable
   info • The value of the local variable 'packageName' isn't used •
          lib/pages/settings.dart:40:12 • unused_local_variable
   info • The value of the local variable 'buildNumber' isn't used •
          lib/pages/settings.dart:42:12 • unused_local_variable
   info • This function has a return type of 'FutureOr<bool>', but doesn't end
          with a return statement • lib/pages/syllabus.dart:148:50 •
          missing_return
```

**Comment by zanderso** [comment]
Does this still happen with a more recent stable version?

**Comment by MaskyS** [comment]
I haven't experienced it recently on the beta/stable branch.

**Comment by aminjoharinia** [comment]
it still exists in 1.17.0

**Comment by zanderso** [comment]
@aminjoharinia please open a new issue with full details. Thanks!
