### ISSUE TITLE
flutter has exited unexpectedly when building ios plugin

### ISSUE THREAD

**Issue by bitsydarel** [flutter/flutter#37861]
Flutter crash report; please file at https://github.com/flutter/flutter/issues.

## command

flutter run --debug -d all

## exception

ProcessException: ProcessException: Process "/usr/bin/xcrun" exited abnormally:
An error was encountered processing the command (domain=IXUserPresentableErrorDomain, code=1):
This app could not be installed at this time.
Could not hardlink copy /Users/darelbitsy/Library/Developer/CoreSimulator/Devices/0CA345D1-9EE9-47CD-8419-75EF2D059B99/data/Containers/Bundle/Application/1D3DB2B6-E1FC-4247-BBA6-10F1C26575FE/Runner.app to /Users/darelbitsy/Library/Developer/CoreSimulator/Devices/0CA345D1-9EE9-47CD-8419-75EF2D059B99/data/Library/Caches/com.apple.mobile.installd.staging/temp.iymvod/extracted/Payload/Runner.app with manifest /Users/darelbitsy/Library/Developer/CoreSimulator/Devices/0CA345D1-9EE9-47CD-8419-75EF2D059B99/data/Library/Caches/com.apple.mobile.installd.staging/temp.iymvod/extracted/com.apple.deltainstallcommands.com.transportexchangegroup.flutterPendoExample
Could not hardlink copy /Users/darelbitsy/Library/Developer/CoreSimulator/Devices/0CA345D1-9EE9-47CD-8419-75EF2D059B99/data/Containers/Bundle/Application/1D3DB2B6-E1FC-4247-BBA6-10F1C26575FE/Runner.app to /Users/darelbitsy/Library/Developer/CoreSimulator/Devices/0CA345D1-9EE9-47CD-8419-75EF2D059B99/data/Library/Caches/com.apple.mobile.installd.staging/temp.iymvod/extracted/Payload/Runner.app with manifest /Users/darelbitsy/Library/Developer/CoreSimulator/Devices/0CA345D1-9EE9-47CD-8419-75EF2D059B99/data/Library/Caches/com.apple.mobile.installd.staging/temp.iymvod/extracted/com.apple.deltainstallcommands.com.transportexchangegroup.flutterPendoExample
Underlying error (domain=MIInstallerErrorDomain, code=8):
	Could not hardlink copy /Users/darelbitsy/Library/Developer/CoreSimulator/Devices/0CA345D1-9EE9-47CD-8419-75EF2D059B99/data/Containers/Bundle/Application/1D3DB2B6-E1FC-4247-BBA6-10F1C26575FE/Runner.app to /Users/darelbitsy/Library/Developer/CoreSimulator/Devices/0CA345D1-9EE9-47CD-8419-75EF2D059B99/data/Library/Caches/com.apple.mobile.installd.staging/temp.iymvod/extracted/Payload/Runner.app with manifest /Users/darelbitsy/Library/Developer/CoreSimulator/Devices/0CA345D1-9EE9-47CD-8419-75EF2D059B99/data/Library/Caches/com.apple.mobile.installd.staging/temp.iymvod/extracted/com.apple.deltainstallcommands.com.transportexchangegroup.flutterPendoExample
  Command: /usr/bin/xcrun simctl install 0CA345D1-9EE9-47CD-8419-75EF2D059B99 /Users/darelbitsy/IdeaProjects/flutter_pendo/example/build/ios/iphonesimulator/Runner.app

```
#0      runCheckedAsync (package:flutter_tools/src/base/process.dart:259:7)
<asynchronous suspension>
#1      SimControl.install (package:flutter_tools/src/ios/simulators.dart:128:16)
#2      IOSSimulator._setupUpdatedApplicationBundle (package:flutter_tools/src/ios/simulators.dart:415:31)
<asynchronous suspension>
#3      IOSSimulator.startApp (package:flutter_tools/src/ios/simulators.dart:315:15)
<asynchronous suspension>
#4      FlutterDevice.runHot (package:flutter_tools/src/resident_runner.dart:371:54)
#5      _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:77:64)
#6      _rootRunUnary (dart:async/zone.dart:1132:38)
#7      _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#8      _FutureListener.handleValue (dart:async/future_impl.dart:126:18)
#9      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:639:45)
#10     Future._propagateToListeners (dart:async/future_impl.dart:668:32)
#11     Future._complete (dart:async/future_impl.dart:473:7)
#12     _SyncCompleter.complete (dart:async/future_impl.dart:51:12)
#13     _AsyncAwaitCompleter.complete.<anonymous closure> (dart:async-patch/async_patch.dart:33:20)
#14     _rootRun (dart:async/zone.dart:1120:38)
#15     _CustomZone.run (dart:async/zone.dart:1021:19)
#16     _CustomZone.runGuarded (dart:async/zone.dart:923:7)
#17     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:963:23)
#18     _rootRun (dart:async/zone.dart:1124:13)
#19     _CustomZone.run (dart:async/zone.dart:1021:19)
#20     _CustomZone.runGuarded (dart:async/zone.dart:923:7)
#21     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:963:23)
#22     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#23     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#24     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:116:13)
#25     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:173:5)
```

## flutter doctor

```
[✓] Flutter (Channel stable, v1.7.8+hotfix.4, on Mac OS X 10.14.6 18G87, locale
    fr-UA)
    • Flutter version 1.7.8+hotfix.4 at /Users/darelbitsy/tools/flutter
    • Framework revision 20e59316b8 (3 weeks ago), 2019-07-18 20:04:33 -0700
    • Engine revision fee001c93f
    • Dart version 2.4.0

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/darelbitsy/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling
      support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Users/darelbitsy/Library/Application
      Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/183.5692245/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_152-release-1343-b01)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 10.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.3, Build version 10G8
    • CocoaPods version 1.6.1

[✓] iOS tools - develop for iOS devices
    • ios-deploy 1.9.4

[✓] Android Studio (version 3.4)
    • Android Studio at /Users/darelbitsy/Library/Application
      Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/183.5692245/Android
      Studio.app/Contents
    • Flutter plugin version 38.1.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build
      1.8.0_152-release-1343-b01)

[✓] IntelliJ IDEA Ultimate Edition (version 2019.2)
    • IntelliJ at /Users/darelbitsy/Applications/JetBrains Toolbox/IntelliJ IDEA
      Ultimate.app
    • Flutter plugin version 37.1.3
    • Dart plugin version 191.7830

[✓] VS Code (version 1.36.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.2.0

[✓] Connected device (2 available)
    • SM G950F  • ce11171b538698150c                   • android-arm64 • Android
      9 (API 28)
    • iPhone Xʀ • 0CA345D1-9EE9-47CD-8419-75EF2D059B99 • ios           •
      com.apple.CoreSimulator.SimRuntime.iOS-12-4 (simulator)

• No issues found!
```

**Comment by bitsydarel** [comment]
ios build seem to finish properly

Flutter crash report; please file at https://github.com/flutter/flutter/issues.

## command

flutter run --debug --build

## exception

ProcessException: ProcessException: Process "/usr/bin/xcrun" exited abnormally:
An error was encountered processing the command (domain=IXUserPresentableErrorDomain, code=1):
This app could not be installed at this time.
Could not hardlink copy /Users/darelbitsy/Library/Developer/CoreSimulator/Devices/0CA345D1-9EE9-47CD-8419-75EF2D059B99/data/Containers/Bundle/Application/1D3DB2B6-E1FC-4247-BBA6-10F1C26575FE/Runner.app to /Users/darelbitsy/Library/Developer/CoreSimulator/Devices/0CA345D1-9EE9-47CD-8419-75EF2D059B99/data/Library/Caches/com.apple.mobile.installd.staging/temp.n25hpl/extracted/Payload/Runner.app with manifest /Users/darelbitsy/Library/Developer/CoreSimulator/Devices/0CA345D1-9EE9-47CD-8419-75EF2D059B99/data/Library/Caches/com.apple.mobile.installd.staging/temp.n25hpl/extracted/com.apple.deltainstallcommands.com.transportexchangegroup.flutterPendoExample
Could not hardlink copy /Users/darelbitsy/Library/Developer/CoreSimulator/Devices/0CA345D1-9EE9-47CD-8419-75EF2D059B99/data/Containers/Bundle/Application/1D3DB2B6-E1FC-4247-BBA6-10F1C26575FE/Runner.app to /Users/darelbitsy/Library/Developer/CoreSimulator/Devices/0CA345D1-9EE9-47CD-8419-75EF2D059B99/data/Library/Caches/com.apple.mobile.installd.staging/temp.n25hpl/extracted/Payload/Runner.app with manifest /Users/darelbitsy/Library/Developer/CoreSimulator/Devices/0CA345D1-9EE9-47CD-8419-75EF2D059B99/data/Library/Caches/com.apple.mobile.installd.staging/temp.n25hpl/extracted/com.apple.deltainstallcommands.com.transportexchangegroup.flutterPendoExample
Underlying error (domain=MIInstallerErrorDomain, code=8):
	Could not hardlink copy /Users/darelbitsy/Library/Developer/CoreSimulator/Devices/0CA345D1-9EE9-47CD-8419-75EF2D059B99/data/Containers/Bundle/Application/1D3DB2B6-E1FC-4247-BBA6-10F1C26575FE/Runner.app to /Users/darelbitsy/Library/Developer/CoreSimulator/Devices/0CA345D1-9EE9-47CD-8419-75EF2D059B99/data/Library/Caches/com.apple.mobile.installd.staging/temp.n25hpl/extracted/Payload/Runner.app with manifest /Users/darelbitsy/Library/Developer/CoreSimulator/Devices/0CA345D1-9EE9-47CD-8419-75EF2D059B99/data/Library/Caches/com.apple.mobile.installd.staging/temp.n25hpl/extracted/com.apple.deltainstallcommands.com.transportexchangegroup.flutterPendoExample
  Command: /usr/bin/xcrun simctl install 0CA345D1-9EE9-47CD-8419-75EF2D059B99 /Users/darelbitsy/IdeaProjects/flutter_pendo/example/build/ios/iphonesimulator/Runner.app

```
#0      runCheckedAsync (package:flutter_tools/src/base/process.dart:259:7)
<asynchronous suspension>
#1      SimControl.install (package:flutter_tools/src/ios/simulators.dart:128:16)
#2      IOSSimulator._setupUpdatedApplicationBundle (package:flutter_tools/src/ios/simulators.dart:415:31)
<asynchronous suspension>
#3      IOSSimulator.startApp (package:flutter_tools/src/ios/simulators.dart:315:15)
<asynchronous suspension>
#4      FlutterDevice.runHot (package:flutter_tools/src/resident_runner.dart:371:54)
#5      _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:77:64)
#6      _rootRunUnary (dart:async/zone.dart:1132:38)
#7      _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#8      _FutureListener.handleValue (dart:async/future_impl.dart:126:18)
#9      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:639:45)
#10     Future._propagateToListeners (dart:async/future_impl.dart:668:32)
#11     Future._complete (dart:async/future_impl.dart:473:7)
#12     _SyncCompleter.complete (dart:async/future_impl.dart:51:12)
#13     _AsyncAwaitCompleter.complete.<anonymous closure> (dart:async-patch/async_patch.dart:33:20)
#14     _rootRun (dart:async/zone.dart:1120:38)
#15     _CustomZone.run (dart:async/zone.dart:1021:19)
#16     _CustomZone.runGuarded (dart:async/zone.dart:923:7)
#17     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:963:23)
#18     _rootRun (dart:async/zone.dart:1124:13)
#19     _CustomZone.run (dart:async/zone.dart:1021:19)
#20     _CustomZone.runGuarded (dart:async/zone.dart:923:7)
#21     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:963:23)
#22     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#23     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#24     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:116:13)
#25     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:173:5)
```

## flutter doctor

```
[✓] Flutter (Channel stable, v1.7.8+hotfix.4, on Mac OS X 10.14.6 18G87, locale
    fr-UA)
    • Flutter version 1.7.8+hotfix.4 at /Users/darelbitsy/tools/flutter
    • Framework revision 20e59316b8 (3 weeks ago), 2019-07-18 20:04:33 -0700
    • Engine revision fee001c93f
    • Dart version 2.4.0

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/darelbitsy/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling
      support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Users/darelbitsy/Library/Application
      Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/183.5692245/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_152-release-1343-b01)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 10.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.3, Build version 10G8
    • CocoaPods version 1.6.1

[✓] iOS tools - develop for iOS devices
    • ios-deploy 1.9.4

[✓] Android Studio (version 3.4)
    • Android Studio at /Users/darelbitsy/Library/Application
      Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/183.5692245/Android
      Studio.app/Contents
    • Flutter plugin version 38.1.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build
      1.8.0_152-release-1343-b01)

[✓] IntelliJ IDEA Ultimate Edition (version 2019.2)
    • IntelliJ at /Users/darelbitsy/Applications/JetBrains Toolbox/IntelliJ IDEA
      Ultimate.app
    • Flutter plugin version 37.1.3
    • Dart plugin version 191.7830

[✓] VS Code (version 1.36.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.2.0

[✓] Connected device (1 available)
    • iPhone Xʀ • 0CA345D1-9EE9-47CD-8419-75EF2D059B99 • ios •
      com.apple.CoreSimulator.SimRuntime.iOS-12-4 (simulator)

• No issues found!
```

**Comment by bitsydarel** [comment]
same result after running flutter clean

Flutter crash report; please file at https://github.com/flutter/flutter/issues.

## command

flutter run --debug --build

## exception

ProcessException: ProcessException: Process "/usr/bin/xcrun" exited abnormally:
An error was encountered processing the command (domain=IXUserPresentableErrorDomain, code=1):
This app could not be installed at this time.
Could not hardlink copy /Users/darelbitsy/Library/Developer/CoreSimulator/Devices/0CA345D1-9EE9-47CD-8419-75EF2D059B99/data/Containers/Bundle/Application/1D3DB2B6-E1FC-4247-BBA6-10F1C26575FE/Runner.app to /Users/darelbitsy/Library/Developer/CoreSimulator/Devices/0CA345D1-9EE9-47CD-8419-75EF2D059B99/data/Library/Caches/com.apple.mobile.installd.staging/temp.j2AXaB/extracted/Payload/Runner.app with manifest /Users/darelbitsy/Library/Developer/CoreSimulator/Devices/0CA345D1-9EE9-47CD-8419-75EF2D059B99/data/Library/Caches/com.apple.mobile.installd.staging/temp.j2AXaB/extracted/com.apple.deltainstallcommands.com.transportexchangegroup.flutterPendoExample
Could not hardlink copy /Users/darelbitsy/Library/Developer/CoreSimulator/Devices/0CA345D1-9EE9-47CD-8419-75EF2D059B99/data/Containers/Bundle/Application/1D3DB2B6-E1FC-4247-BBA6-10F1C26575FE/Runner.app to /Users/darelbitsy/Library/Developer/CoreSimulator/Devices/0CA345D1-9EE9-47CD-8419-75EF2D059B99/data/Library/Caches/com.apple.mobile.installd.staging/temp.j2AXaB/extracted/Payload/Runner.app with manifest /Users/darelbitsy/Library/Developer/CoreSimulator/Devices/0CA345D1-9EE9-47CD-8419-75EF2D059B99/data/Library/Caches/com.apple.mobile.installd.staging/temp.j2AXaB/extracted/com.apple.deltainstallcommands.com.transportexchangegroup.flutterPendoExample
Underlying error (domain=MIInstallerErrorDomain, code=8):
	Could not hardlink copy /Users/darelbitsy/Library/Developer/CoreSimulator/Devices/0CA345D1-9EE9-47CD-8419-75EF2D059B99/data/Containers/Bundle/Application/1D3DB2B6-E1FC-4247-BBA6-10F1C26575FE/Runner.app to /Users/darelbitsy/Library/Developer/CoreSimulator/Devices/0CA345D1-9EE9-47CD-8419-75EF2D059B99/data/Library/Caches/com.apple.mobile.installd.staging/temp.j2AXaB/extracted/Payload/Runner.app with manifest /Users/darelbitsy/Library/Developer/CoreSimulator/Devices/0CA345D1-9EE9-47CD-8419-75EF2D059B99/data/Library/Caches/com.apple.mobile.installd.staging/temp.j2AXaB/extracted/com.apple.deltainstallcommands.com.transportexchangegroup.flutterPendoExample
  Command: /usr/bin/xcrun simctl install 0CA345D1-9EE9-47CD-8419-75EF2D059B99 /Users/darelbitsy/IdeaProjects/flutter_pendo/example/build/ios/iphonesimulator/Runner.app

```
#0      runCheckedAsync (package:flutter_tools/src/base/process.dart:259:7)
<asynchronous suspension>
#1      SimControl.install (package:flutter_tools/src/ios/simulators.dart:128:16)
#2      IOSSimulator._setupUpdatedApplicationBundle (package:flutter_tools/src/ios/simulators.dart:415:31)
<asynchronous suspension>
#3      IOSSimulator.startApp (package:flutter_tools/src/ios/simulators.dart:315:15)
<asynchronous suspension>
#4      FlutterDevice.runHot (package:flutter_tools/src/resident_runner.dart:371:54)
#5      _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:77:64)
#6      _rootRunUnary (dart:async/zone.dart:1132:38)
#7      _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#8      _FutureListener.handleValue (dart:async/future_impl.dart:126:18)
#9      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:639:45)
#10     Future._propagateToListeners (dart:async/future_impl.dart:668:32)
#11     Future._complete (dart:async/future_impl.dart:473:7)
#12     _SyncCompleter.complete (dart:async/future_impl.dart:51:12)
#13     _AsyncAwaitCompleter.complete.<anonymous closure> (dart:async-patch/async_patch.dart:33:20)
#14     _rootRun (dart:async/zone.dart:1120:38)
#15     _CustomZone.run (dart:async/zone.dart:1021:19)
#16     _CustomZone.runGuarded (dart:async/zone.dart:923:7)
#17     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:963:23)
#18     _rootRun (dart:async/zone.dart:1124:13)
#19     _CustomZone.run (dart:async/zone.dart:1021:19)
#20     _CustomZone.runGuarded (dart:async/zone.dart:923:7)
#21     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:963:23)
#22     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#23     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#24     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:116:13)
#25     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:173:5)
```

## flutter doctor

```
[✓] Flutter (Channel stable, v1.7.8+hotfix.4, on Mac OS X 10.14.6 18G87, locale
    fr-UA)
    • Flutter version 1.7.8+hotfix.4 at /Users/darelbitsy/tools/flutter
    • Framework revision 20e59316b8 (3 weeks ago), 2019-07-18 20:04:33 -0700
    • Engine revision fee001c93f
    • Dart version 2.4.0

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/darelbitsy/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling
      support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Users/darelbitsy/Library/Application
      Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/183.5692245/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_152-release-1343-b01)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 10.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.3, Build version 10G8
    • CocoaPods version 1.6.1

[✓] iOS tools - develop for iOS devices
    • ios-deploy 1.9.4

[✓] Android Studio (version 3.4)
    • Android Studio at /Users/darelbitsy/Library/Application
      Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/183.5692245/Android
      Studio.app/Contents
    • Flutter plugin version 38.1.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build
      1.8.0_152-release-1343-b01)

[✓] IntelliJ IDEA Ultimate Edition (version 2019.2)
    • IntelliJ at /Users/darelbitsy/Applications/JetBrains Toolbox/IntelliJ IDEA
      Ultimate.app
    • Flutter plugin version 37.1.3
    • Dart plugin version 191.7830

[✓] VS Code (version 1.36.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.2.0

[✓] Connected device (1 available)
    • iPhone Xʀ • 0CA345D1-9EE9-47CD-8419-75EF2D059B99 • ios •
      com.apple.CoreSimulator.SimRuntime.iOS-12-4 (simulator)

• No issues found!
```

**Comment by bitsydarel** [comment]
i have successfully launched the app by opening the plugin in xcode and deleting the app on the emulator.

**Comment by jmagman** [comment]
Possibly the same cause as https://github.com/flutter/flutter/issues/34477.
What's your pubspec version?

**Comment by bitsydarel** [comment]
version: 0.0.1

**Comment by jmagman** [comment]
Same issue as https://github.com/flutter/flutter/issues/34477.

**Comment by oligazar** [comment]
I have the same problem. And my pubspec version: 1.0.0+1. So  #34477 is not working for me. Any ideas?

**Comment by devxpy** [comment]
@jmagman I'm getting the same error, even after hard-coding the version and build number in xcode.

- Only affects new projects, created with `--template=plugin`. 
- Older projects still work, even if they didn't have an explicit `version` in `example/pubspec.yaml` !

[Full Ouput](https://gist.github.com/devxpy/aece67e3daeeb5e9671258817bee28d0)

<details>
<summary> exception </summary>
<p>

```
ProcessException: ProcessException: Process "/usr/bin/xcrun" exited abnormally:
An error was encountered processing the command (domain=IXUserPresentableErrorDomain, code=1):
This app could not be installed at this time.
Could not hardlink copy /Users/dev/Library/Developer/CoreSimulator/Devices/B0274C37-FA4A-4292-89E2-AB45C4ED7BB6/data/Containers/Bundle/Application/55BF7ED0-B261-49A8-95FF-BA4190C05C2F/Runner.app to /Users/dev/Library/Developer/CoreSimulator/Devices/B0274C37-FA4A-4292-89E2-AB45C4ED7BB6/data/Library/Caches/com.apple.mobile.installd.staging/temp.yIC0oY/extracted/Payload/Runner.app with manifest /Users/dev/Library/Developer/CoreSimulator/Devices/B0274C37-FA4A-4292-89E2-AB45C4ED7BB6/data/Library/Caches/com.apple.mobile.installd.staging/temp.yIC0oY/extracted/com.apple.deltainstallcommands.com.scientifichackers.awsIotExample
Could not hardlink copy /Users/dev/Library/Developer/CoreSimulator/Devices/B0274C37-FA4A-4292-89E2-AB45C4ED7BB6/data/Containers/Bundle/Application/55BF7ED0-B261-49A8-95FF-BA4190C05C2F/Runner.app to /Users/dev/Library/Developer/CoreSimulator/Devices/B0274C37-FA4A-4292-89E2-AB45C4ED7BB6/data/Library/Caches/com.apple.mobile.installd.staging/temp.yIC0oY/extracted/Payload/Runner.app with manifest /Users/dev/Library/Developer/CoreSimulator/Devices/B0274C37-FA4A-4292-89E2-AB45C4ED7BB6/data/Library/Caches/com.apple.mobile.installd.staging/temp.yIC0oY/extracted/com.apple.deltainstallcommands.com.scientifichackers.awsIotExample
Underlying error (domain=MIInstallerErrorDomain, code=8):
	Could not hardlink copy /Users/dev/Library/Developer/CoreSimulator/Devices/B0274C37-FA4A-4292-89E2-AB45C4ED7BB6/data/Containers/Bundle/Application/55BF7ED0-B261-49A8-95FF-BA4190C05C2F/Runner.app to /Users/dev/Library/Developer/CoreSimulator/Devices/B0274C37-FA4A-4292-89E2-AB45C4ED7BB6/data/Library/Caches/com.apple.mobile.installd.staging/temp.yIC0oY/extracted/Payload/Runner.app with manifest /Users/dev/Library/Developer/CoreSimulator/Devices/B0274C37-FA4A-4292-89E2-AB45C4ED7BB6/data/Library/Caches/com.apple.mobile.installd.staging/temp.yIC0oY/extracted/com.apple.deltainstallcommands.com.scientifichackers.awsIotExample
  Command: /usr/bin/xcrun simctl install B0274C37-FA4A-4292-89E2-AB45C4ED7BB6 /Users/dev/FlutterProjects/aws_iot_new/example/build/ios/iphonesimulator/Runner.app
#0      runCheckedAsync (package:flutter_tools/src/base/process.dart:259:7)
<asynchronous suspension>
#1      SimControl.install (package:flutter_tools/src/ios/simulators.dart:145:16)
#2      IOSSimulator._setupUpdatedApplicationBundle (package:flutter_tools/src/ios/simulators.dart:437:31)
<asynchronous suspension>
#3      IOSSimulator.startApp (package:flutter_tools/src/ios/simulators.dart:339:15)
<asynchronous suspension>
#4      FlutterDevice.runHot (package:flutter_tools/src/resident_runner.dart:378:54)
#5      _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:71:64)
#6      _rootRunUnary (dart:async/zone.dart:1132:38)
#7      _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#8      _FutureListener.handleValue (dart:async/future_impl.dart:137:18)
#9      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:678:45)
#10     Future._propagateToListeners (dart:async/future_impl.dart:707:32)
#11     Future._completeWithValue (dart:async/future_impl.dart:522:5)
#12     Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:552:7)
#13     _rootRun (dart:async/zone.dart:1124:13)
#14     _CustomZone.run (dart:async/zone.dart:1021:19)
#15     _CustomZone.runGuarded (dart:async/zone.dart:923:7)
#16     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:963:23)
#17     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#18     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#19     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:116:13)
#20     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:173:5)
```

</p>
</details>

<details>
<summary>flutter doctor -v</summary>
<p>

```
[✓] Flutter (Channel stable, v1.9.1+hotfix.6, on Mac OS X 10.14.6 18G103, locale en)
    • Flutter version 1.9.1+hotfix.6 at /Users/dev/Tools/flutter
    • Framework revision 68587a0916 (3 months ago), 2019-09-13 19:46:58 -0700
    • Engine revision b863200c37
    • Dart version 2.5.0

[!] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/dev/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Users/dev/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-1/191.5977832/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses

[✓] Xcode - develop for iOS and macOS (Xcode 10.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.3, Build version 10G8
    • CocoaPods version 1.8.4

[✓] Android Studio (version 3.5)
    • Android Studio at /Users/dev/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-1/191.5977832/Android Studio.app/Contents
    • Flutter plugin version 41.0.2
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] IntelliJ IDEA Ultimate Edition (version 2019.2.4)
    • IntelliJ at /Users/dev/Applications/JetBrains Toolbox/IntelliJ IDEA Ultimate.app
    • Flutter plugin version 41.0.3
    • Dart plugin version 192.7402

[✓] VS Code (version 1.40.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.6.0

[✓] Connected device (1 available)
    • iPhone Xʀ • B0274C37-FA4A-4292-89E2-AB45C4ED7BB6 • ios • com.apple.CoreSimulator.SimRuntime.iOS-12-4 (simulator)

! Doctor found issues in 1 category.
```

</p>
</details>
