### ISSUE TITLE
Http request hunging (until timeout) in Honor 9 Device

### ISSUE THREAD

**Issue by mauriziobarucco** [flutter/flutter#37924]
## Steps to Reproduce

My app works well on many device types, but with Honor 9 every http request hung up until timeout:
- Android version 9.1
- Flutter version 1.7.8+hotfix.4
- plugin http: 0.12.0+2

i obtain the error:
[ZeroHung]zrhung_get_config: Get config failed for wp[0x0008]

For several months the app works well with Xiaomi and Samsung devices; now testing with Honor 9 terminal appear this blocking problem.

## Logs

```
[  +1 ms] I/flutter (11209): ***...start _registration
[  +11 ms] W/InputMethodManager(11209): startInputReason = 4
[  +11 ms] I/flutter (11209): Registration request : http://10.0.2.2:8080/LeoChecklist/rest/leoAuth/v2/registration/mobile, clientId:LEOCHECKLIST_APP_LOCAL
[   +1 ms] E/        (11209): [ZeroHung]zrhung_get_config: Get config failed for wp[0x0008]
[  +22 ms] I/flutter (11209): Running on STF-L09 / man:HUAWEI / prod:STF-L09 / VERSION:REL-9 
[+27008 ms] E/        (11209): [ZeroHung]zrhung_get_config: Get config failed for wp[0x0008]
[+26512 ms] E/        (11209): [ZeroHung]zrhung_get_config: Get config failed for wp[0x0008]
[+26287 ms] E/        (11209): [ZeroHung]zrhung_get_config: Get config failed for wp[0x0008]
[+26513 ms] E/        (11209): [ZeroHung]zrhung_get_config: Get config failed for wp[0x0008]
[+26507 ms] E/        (11209): [ZeroHung]zrhung_get_config: Get config failed for wp[0x0008]
[+1052 ms] E/flutter (11209): [ERROR:flutter/lib/ui/ui_dart_state.cc(148)] Unhandled Exception: SocketException: OS Error: Connection timed out, errno = 110, address = 10.0.2.2, port = 37662
[   +1 ms] E/flutter (11209): #0      IOClient.send (package:http/src/io_client.dart:33:23)
[        ] E/flutter (11209): <asynchronous suspension>
[        ] E/flutter (11209): #1      BaseClient._sendUnstreamed (package:http/src/base_client.dart:169:38)
[        ] E/flutter (11209): <asynchronous suspension>
[        ] E/flutter (11209): #2      BaseClient.get (package:http/src/base_client.dart:32:7)
[   +1 ms] E/flutter (11209): #3      get.<anonymous closure> (package:http/http.dart:46:36)
[        ] E/flutter (11209): #4      _withClient (package:http/http.dart:166:20)
[        ] E/flutter (11209): <asynchronous suspension>
[        ] E/flutter (11209): #5      get (package:http/http.dart:46:5)
[        ] E/flutter (11209): #6      AuthManager.registration (package:LeoChecklist/core/auth/auth_manager.dart:158:30)
[        ] E/flutter (11209): <asynchronous suspension>
[        ] E/flutter (11209): #7      AuthManager._createFlutterWebviewPluginAndHandler.<anonymous closure> (package:LeoChecklist/core/auth/auth_manager.dart:355:43)
[        ] E/flutter (11209): #8      _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:77:64)
[        ] E/flutter (11209): #9      _rootRunUnary (dart:async/zone.dart:1132:38)
[        ] E/flutter (11209): #10     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
[        ] E/flutter (11209): #11     _FutureListener.handleValue (dart:async/future_impl.dart:126:18)
[        ] E/flutter (11209): #12     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:639:45)
[        ] E/flutter (11209): #13     Future._propagateToListeners (dart:async/future_impl.dart:668:32)
[        ] E/flutter (11209): #14     Future._complete (dart:async/future_impl.dart:473:7)
[        ] E/flutter (11209): #15     _SyncCompleter.complete (dart:async/future_impl.dart:51:12)
[        ] E/flutter (11209): #16     _rootRunUnary (dart:async/zone.dart:1132:38)
[        ] E/flutter (11209): #17     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
[        ] E/flutter (11209): #18     _FutureListener.handleValue (dart:async/future_impl.dart:126:18)
[        ] E/flutter (11209): #19     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:639:45)
[        ] E/flutter (11209): #20     Future._propagateToListeners (dart:async/future_impl.dart:668:32)
[        ] E/flutter (11209): #21     Future._complete (dart:async/future_impl.dart:473:7)
[        ] E/flutter (11209): #22     _SyncCompleter.complete (dart:async/future_impl.dart:51:12)
[        ] E/flutter (11209): #23     _rootRunUnary (dart:async/zone.dart:1132:38)
[        ] E/flutter (11209): #24     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
[        ] E/flutter (11209): #25     _FutureListener.handleValue (dart:async/future_impl.dart:126:18)
[        ] E/flutter (11209): #26     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:639:45)
[        ] E/flutter (11209): #27     Future._propagateToListeners (dart:async/future_impl.dart:668:32)
[        ] E/flutter (11209): #28     Future._complete (dart:async/future_impl.dart:473:7)
[        ] E/flutter (11209): #29     _SyncCompleter.complete (dart:async/future_impl.dart:51:12)
[        ] E/flutter (11209): #30     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:28:18)
[        ] E/flutter (11209): #31     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:294:13)
[        ] E/flutter (11209): #32     MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart)
[        ] E/flutter (11209): #33     _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:77:64)
[        ] E/flutter (11209): #34     _rootRunUnary (dart:async/zone.dart:1132:38)
[        ] E/flutter (11209): #35     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
[        ] E/flutter (11209): #36     _FutureListener.handleValue (dart:async/future_impl.dart:126:18)
[        ] E/flutter (11209): #37     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:639:45)
[        ] E/flutter (11209): #38     Future._propagateToListeners (dart:async/future_impl.dart:668:32)
[        ] E/flutter (11209): #39     Future._completeWithValue (dart:async/future_impl.dart:483:5)
[        ] E/flutter (11209): #40     Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:513:7)
[        ] E/flutter (11209): #41     _rootRun (dart:async/zone.dart:1124:13)
[        ] E/flutter (11209): #42     _CustomZone.run (dart:async/zone.dart:1021:19)
[        ] E/flutter (11209): #43     _CustomZone.runGuarded (dart:async/zone.dart:923:7)
[        ] E/flutter (11209): #44     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:963:23)
[        ] E/flutter (11209): #45     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
[        ] E/flutter (11209): #46     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
[        ] E/flutter (11209): 
[+25459 ms] E/    
```

```
flutter analyze
Analyzing leo_checklist...
No issues found! (ran in 9.1s)
```

```
flutter doctor -v
[√] Flutter (Channel stable, v1.7.8+hotfix.4, on Microsoft Windows [Version 10.0.17763.107], locale it-IT)
    • Flutter version 1.7.8+hotfix.4 at C:\flutter
    • Framework revision 20e59316b8 (3 weeks ago), 2019-07-18 20:04:33 -0700
    • Engine revision fee001c93f
    • Dart version 2.4.0


[√] Android toolchain - develop for Android devices (Android SDK version 29.0.1)
    • Android SDK at C:\Users\maubc\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.1
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
    • All Android licenses accepted.

[√] Android Studio (version 3.4)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 38.1.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

[√] VS Code, 64-bit edition (version 1.36.1)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Flutter extension version 3.3.0

[√] Connected device (1 available)
    • STF L09 • 7BKDU17705001078 • android-arm64 • Android 9 (API 28)

• No issues found!
```

**Comment by aajinkya1203** [comment]
Can confirm this happens on Honor 9. Think its a Honor issue.
Any solution?

**Comment by darshankawar** [comment]
@mauriziobarucco 
Is this still a valid issue using latest Flutter version on Honor device ?
If so, can you provide latest `flutter doctor -v` and a minimal complete reproducible code sample that shows the issue ?

**Comment by mauriziobarucco** [comment]
> @mauriziobarucco
> Is this still a valid issue using latest Flutter version on Honor device ?
> If so, can you provide latest `flutter doctor -v` and a minimal complete reproducible code sample that shows the issue ?

No, now is all working properly.

**Comment by darshankawar** [comment]
Thanks @mauriziobarucco for confirming. Closing this based on above comment.

**Comment by hassankz1** [comment]
what is the solution ? Please help me
