### ISSUE TITLE
 _StreamBuilderBaseState<QuerySnapshot, AsyncSnapshot<QuerySnapshot>: Assertion failed

### ISSUE THREAD

**Issue by kokcheng95** [flutter/flutter#38031]
## Steps to Reproduce

**Source Code**

	@override
	  Widget build(BuildContext context) {
		final form = Form(
		  key: formKey,
		  child: ListView(
			padding: const EdgeInsets.all(8.0),
			children: <Widget>[
			  Padding(
				padding: _padding,
				child: Column(
				  crossAxisAlignment: CrossAxisAlignment.stretch,
				  children: [
					TextFormField(
					  style: Theme.of(context).textTheme.display1,
					  decoration: InputDecoration(
						labelStyle: Theme.of(context).textTheme.display1,
						labelText: 'Car Plate No',
						border: OutlineInputBorder(
						  borderRadius: BorderRadius.circular(0.0),
						),
					  ),
					  keyboardType: TextInputType.text,
					  validator: (input) =>
						  input.isEmpty ? 'Please Enter Car Plate No' : null,
					  onSaved: (input) => _carPlateNo = input,
					),
					_createDropdown(),
				  ],
				),
			  ),
			  RotatedBox(
				quarterTurns: 1,
				child: Icon(
				  Icons.compare_arrows,
				  size: 40.0,
				),
			  ),
			  Padding(
				padding: _padding,
				child: Column(
				  crossAxisAlignment: CrossAxisAlignment.stretch,
				  children: [
					InputDecorator(
					  child: Text(
						_warrantyValue,
						style: Theme.of(context).textTheme.display1,
					  ),
					  decoration: InputDecoration(
						labelText: 'Warranty',
						labelStyle: Theme.of(context).textTheme.display1,
						border: OutlineInputBorder(
						  borderRadius: BorderRadius.circular(0.0),
						),
					  ),
					),
				  ],
				),
			  ),
			  Padding(
				padding: _padding,
				child: Column(
				  crossAxisAlignment: CrossAxisAlignment.stretch,
				  children: [
					InputDecorator(
					  child: DateTimePickerFormField(
						inputType: InputType.date,
						format: dateFormat,
						editable: true,
						initialDate: DateTime.now(),
						onChanged: (date) {},
					  ),
					  decoration: InputDecoration(
						labelText: 'Date',
						labelStyle: Theme.of(context).textTheme.display1,
						border: OutlineInputBorder(
						  borderRadius: BorderRadius.circular(0.0),
						),
					  ),
					)
				  ],
				),
			  ),
			  StreamBuilder<QuerySnapshot>(
				stream: Firestore.instance.collection('cardetail').snapshots(),
				builder: (context, AsyncSnapshot<QuerySnapshot> snapshot) {
				  if (!snapshot.hasData) return Text('Loading data');

				  switch (snapshot.connectionState) {
					case ConnectionState.waiting:
					  return new Center(child: new CircularProgressIndicator());
					default:
					return new Column(
					  children:snapshot.data.documents.map((DocumentSnapshot document) {
						print(document['car_plate_nm'])  ;
						ListTile(
						  title:  new Text(document['car_plate_nm']),
						);
					  }).toList());

					
				  }
1. I created a Streambuilder and query the data from firestore, i can see the data are returning from document when i log print(document['car_plate_nm'])  ;
2. But there is error assertion failed

## Logs

```
Reload already in progress, ignoring request
Restarted application in 5,080ms.
I/flutter (14886): hasData
I/flutter (14886): hasData
I/flutter (14886): ddsssss
I/flutter (14886): ggg
I/flutter (14886): asdasdasdas
I/flutter (14886): shaft 777
I/flutter (14886): asdasdasdas
I/flutter (14886): hash 8888
I/flutter (14886): ddsssss
I/flutter (14886): cdb8967

[ +174 ms] I/flutter (32741): ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY
╞═══════════════════════════════════════════════════════════
[   +1 ms] I/flutter (32741): The following assertion was thrown building StreamBuilder<QuerySnapshot>(dirty, state:
[        ] I/flutter (32741): _StreamBuilderBaseState<QuerySnapshot, AsyncSnapshot<QuerySnapshot>>#b9839):
[   +1 ms] I/flutter (32741): Assertion failed
[        ] I/flutter (32741): Either the assertion indicates an error in the framework itself, or we should provide
substantially
[   +1 ms] I/flutter (32741): more information in this error message to help you determine and fix the underlying cause.
[        ] I/flutter (32741): In either case, please report this assertion by filing a bug on GitHub:
[   +1 ms] I/flutter (32741):   https://github.com/flutter/flutter/issues/new?template=BUG.md
[        ] I/flutter (32741): When the exception was thrown, this was the stack:
[        ] I/flutter (32741): #0      new MultiChildRenderObjectWidget.<anonymous closure>
(package:flutter/src/widgets/framework.dart:1691:11)
[   +1 ms] I/flutter (32741): #1      new MultiChildRenderObjectWidget (package:flutter/src/widgets/framework.dart:1696:8)
[   +1 ms] I/flutter (32741): #2      new Flex (package:flutter/src/widgets/basic.dart:3707:8)
[        ] I/flutter (32741): #3      new Column (package:flutter/src/widgets/basic.dart:4234:8)
[        ] I/flutter (32741): #4      _ConverterRouteState.build.<anonymous closure>
(package:udacity/converter_route.dart:338:28)
[   +2 ms] I/flutter (32741): #5      StreamBuilder.build (package:flutter/src/widgets/async.dart:425:74)
[        ] I/flutter (32741): #6      _StreamBuilderBaseState.build (package:flutter/src/widgets/async.dart:125:48)
[   +1 ms] I/flutter (32741): #7      StatefulElement.build (package:flutter/src/widgets/framework.dart:4012:27)
[        ] I/flutter (32741): #8      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3924:15)
[   +1 ms] I/flutter (32741): #9      Element.rebuild (package:flutter/src/widgets/framework.dart:3721:5)
[        ] I/flutter (32741): #10     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2340:33)
[        ] I/flutter (32741): #11
_WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding&WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:700:20)
[   +5 ms] I/flutter (32741): #12
_WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:285:5)
[  +26 ms] I/flutter (32741): #13
_WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._invokeFrameCallback
(package:flutter/src/scheduler/binding.dart:1016:15)
[   +1 ms] I/flutter (32741): #14
_WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.handleDrawFrame
(package:flutter/src/scheduler/binding.dart:958:9)
[   +4 ms] I/flutter (32741): #15
_WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._handleDrawFrame
(package:flutter/src/scheduler/binding.dart:874:5)
[   +1 ms] I/flutter (32741): #19     _invoke (dart:ui/hooks.dart:236:10)
[   +2 ms] I/flutter (32741): #20     _drawFrame (dart:ui/hooks.dart:194:3)
[        ] I/flutter (32741): (elided 3 frames from package dart:async)
[        ] I/flutter (32741):
════════════════════════════════════════════════════════════════════════════════════════════════════
```

```
PS C:\Udacity training\udacity> flutter analyze
Analyzing udacity...

   info - The value of the field '_purchaseDate' isn't used - lib\converter_route.dart:60:12 - unused_field
   info - The value of the field '_showValidationError' isn't used - lib\converter_route.dart:67:8 - unused_field
   info - The method '_format' isn't used - lib\converter_route.dart:141:10 - unused_element
   info - The method '_getUnit' isn't used - lib\converter_route.dart:183:8 - unused_element
   info - Unused import: 'package:firebase_database/firebase_database.dart' - lib\main.dart:10:8 - unused_import

5 issues found. (ran in 8.5s)
```
it's only have unused import.

```
[√] Flutter (Channel beta, v1.7.8+hotfix.4, on Microsoft Windows [Version 10.0.17134.885], locale en-MY)
    • Flutter version 1.7.8+hotfix.4 at C:\flutter
    • Framework revision 20e59316b8 (3 weeks ago), 2019-07-18 20:04:33 -0700
    • Engine revision fee001c93f
    • Dart version 2.4.0


[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at C:\Users\cheng\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 28.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
    • All Android licenses accepted.

[!] Android Studio (version 3.4)
    • Android Studio at C:\Program Files\Android\Android Studio
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

[√] VS Code (version 1.36.1)
    • VS Code at C:\Users\cheng\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.3.0

[√] Connected device (1 available)
    • N5116 • 53f26512 • android-arm • Android 4.3 (API 18)

! Doctor found issues in 1 category.
```

**Comment by TahaTesser** [comment]
Hi @kokcheng95 
if you're still experiencing this problem, please create a new issue and provide the information required in the template.
Thank you
