### ISSUE TITLE
[web] run crashed on windows

### ISSUE THREAD

**Issue by maxnemoy** [flutter/flutter#38290]
## Steps to Reproduce

```
flutter create --web  .
flutter run -d chrome
```
## Logs

<details>
<summary>logs</summary>

```
Failed to build application for the web.

#0      throwToolExit (package:flutter_tools/src/base/common.dart:28:3)
#1      ResidentWebRunner.run (package:flutter_tools/src/build_runner/resident_web_runner.dart:167:7)
<asynchronous suspension>
#2      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:472:37)
<asynchronous suspension>
#3      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:490:18)
#4      _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:77:64)
#5      _rootRunUnary (dart:async/zone.dart:1132:38)
#6      _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#7      _FutureListener.handleValue (dart:async/future_impl.dart:126:18)
#8      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:639:45)
#9      Future._propagateToListeners (dart:async/future_impl.dart:668:32)
#10     Future._complete (dart:async/future_impl.dart:473:7)
#11     _SyncCompleter.complete (dart:async/future_impl.dart:51:12)
#12     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:28:18)
#13     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:294:13)
#14     RunCommand.usageValues (package:flutter_tools/src/commands/run.dart)
#15     _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:77:64)
#16     _rootRunUnary (dart:async/zone.dart:1132:38)
#17     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#18     _FutureListener.handleValue (dart:async/future_impl.dart:126:18)
#19     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:639:45)
#20     Future._propagateToListeners (dart:async/future_impl.dart:668:32)
#21     Future._complete (dart:async/future_impl.dart:473:7)
#22     _SyncCompleter.complete (dart:async/future_impl.dart:51:12)
#23     _AsyncAwaitCompleter.complete.<anonymous closure> (dart:async-patch/async_patch.dart:33:20)
#24     _rootRun (dart:async/zone.dart:1120:38)
#25     _CustomZone.run (dart:async/zone.dart:1021:19)
#26     _CustomZone.runGuarded (dart:async/zone.dart:923:7)
#27     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:963:23)
#28     _rootRun (dart:async/zone.dart:1124:13)
#29     _CustomZone.run (dart:async/zone.dart:1021:19)
#30     _CustomZone.runGuarded (dart:async/zone.dart:923:7)
#31     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:963:23)
#32     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#33     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#34     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:116:13)
#35     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:173:5)
```

</details>

## Flutter doctor

```
C:\source>flutter doctor -v
[√] Flutter (Channel master, v1.8.5-pre.117, on Microsoft Windows [Version 10.0.18362.267], locale ru-RU)
    • Flutter version 1.8.5-pre.117 at C:\libs\flutter
    • Framework revision 83a8a575ee (2 days ago), 2019-08-10 12:38:20 -0700
    • Engine revision ff49ca1c6e
    • Dart version 2.5.0 (build 2.5.0-dev.1.0 f29f41f1a5)


[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at C:\Users\maxne\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio CommunityВ 2019 16.2.1)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio CommunityВ 2019 version 16.2.29201.188

[√] Android Studio (version 3.4)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 38.2.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

[√] VS Code (version 1.37.0)
    • VS Code at C:\Users\maxne\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.3.0

[√] Connected device (2 available)
    • Windows • Windows • windows-x64    • Microsoft Windows [Version 10.0.18362.267]
    • Chrome  • chrome  • web-javascript • Google Chrome 76.0.3809.100

• No issues found!
```

**Comment by jonahwilliams** [comment]
You'll need to rerun with `-v` to capture verbose logs to see what went wrong here

**Comment by maxnemoy** [comment]
@jonahwilliams ,

<details>
<summary>flutter run -d chrome -v</summary>
```
[  +28 ms] executing: [C:\libs\flutter\] git log -n 1 --pretty=format:%H
[  +60 ms] Exit code 0 from: git log -n 1 --pretty=format:%H
[        ] 83a8a575eed882c49b629effedf7c95b6184515d
[        ] executing: [C:\libs\flutter\] git describe --match v*.*.* --first-parent --long --tags
[  +52 ms] Exit code 0 from: git describe --match v*.*.* --first-parent --long --tags
[        ] v1.8.4-117-g83a8a575e
[   +8 ms] executing: [C:\libs\flutter\] git rev-parse --abbrev-ref --symbolic @{u}
[  +37 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/master
[        ] executing: [C:\libs\flutter\] git ls-remote --get-url origin
[  +34 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[  +90 ms] executing: [C:\libs\flutter\] git rev-parse --abbrev-ref HEAD
[  +36 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] master
[ +100 ms] executing: C:\Users\maxne\AppData\Local\Android\sdk\platform-tools\adb.exe devices -l
[  +23 ms] Exit code 0 from: C:\Users\maxne\AppData\Local\Android\sdk\platform-tools\adb.exe devices -l
[        ] List of devices attached
[  +45 ms] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[ +302 ms] Building application for the web...
[+12152 ms] Starting daemon...
[ +183 ms] Initializing inputs
[ +239 ms] Bad state: Unable to start build daemon.
[   +4 ms] #0      _handleDaemonStartup (package:build_daemon/client.dart:82:5)
           <asynchronous suspension>
           #1      BuildDaemonClient.connect (package:build_daemon/client.dart:183:11)
           <asynchronous suspension>
           #2      BuildDaemonCreator._connectClient (package:flutter_tools/src/build_runner/web_fs.dart:305:30)
           #3      BuildDaemonCreator.startBuildDaemon (package:flutter_tools/src/build_runner/web_fs.dart:271:46)
           <asynchronous suspension>
           #4      WebFs.start (package:flutter_tools/src/build_runner/web_fs.dart:143:8)
           <asynchronous suspension>
           #5      ResidentWebRunner.run (package:flutter_tools/src/build_runner/resident_web_runner.dart:156:34)
           <asynchronous suspension>
           #6      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:472:37)
           <asynchronous suspension>
           #7      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:490:18)
           #8      _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:77:64)
           #9      _rootRunUnary (dart:async/zone.dart:1132:38)
           #10     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
           #11     _FutureListener.handleValue (dart:async/future_impl.dart:126:18)
           #12     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:639:45)
           #13     Future._propagateToListeners (dart:async/future_impl.dart:668:32)
           #14     Future._complete (dart:async/future_impl.dart:473:7)
           #15     _SyncCompleter.complete (dart:async/future_impl.dart:51:12)
           #16     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:28:18)
           #17     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:294:13)
           #18     RunCommand.usageValues (package:flutter_tools/src/commands/run.dart)
           #19     _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:77:64)
           #20     _rootRunUnary (dart:async/zone.dart:1132:38)
           #21     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
           #22     _FutureListener.handleValue (dart:async/future_impl.dart:126:18)
           #23     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:639:45)
           #24     Future._propagateToListeners (dart:async/future_impl.dart:668:32)
           #25     Future._complete (dart:async/future_impl.dart:473:7)
           #26     _SyncCompleter.complete (dart:async/future_impl.dart:51:12)
           #27     _AsyncAwaitCompleter.complete.<anonymous closure> (dart:async-patch/async_patch.dart:33:20)
           #28     _rootRun (dart:async/zone.dart:1120:38)
           #29     _CustomZone.run (dart:async/zone.dart:1021:19)
           #30     _CustomZone.runGuarded (dart:async/zone.dart:923:7)
           #31     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:963:23)
           #32     _rootRun (dart:async/zone.dart:1124:13)
           #33     _CustomZone.run (dart:async/zone.dart:1021:19)
           #34     _CustomZone.runGuarded (dart:async/zone.dart:923:7)
           #35     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:963:23)
           #36     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
           #37     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
           #38     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:116:13)
           #39     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:173:5)

[  +19 ms] Building application for the web... (completed in 12,6s)
[   +1 ms] "flutter run" took 13 120ms.
Failed to build application for the web.

#0      throwToolExit (package:flutter_tools/src/base/common.dart:28:3)
#1      ResidentWebRunner.run (package:flutter_tools/src/build_runner/resident_web_runner.dart:167:7)
<asynchronous suspension>
#2      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:472:37)
<asynchronous suspension>
#3      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:490:18)
#4      _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:77:64)
#5      _rootRunUnary (dart:async/zone.dart:1132:38)
#6      _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#7      _FutureListener.handleValue (dart:async/future_impl.dart:126:18)
#8      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:639:45)
#9      Future._propagateToListeners (dart:async/future_impl.dart:668:32)
#10     Future._complete (dart:async/future_impl.dart:473:7)
#11     _SyncCompleter.complete (dart:async/future_impl.dart:51:12)
#12     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:28:18)
#13     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:294:13)
#14     RunCommand.usageValues (package:flutter_tools/src/commands/run.dart)
#15     _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:77:64)
#16     _rootRunUnary (dart:async/zone.dart:1132:38)
#17     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#18     _FutureListener.handleValue (dart:async/future_impl.dart:126:18)
#19     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:639:45)
#20     Future._propagateToListeners (dart:async/future_impl.dart:668:32)
#21     Future._complete (dart:async/future_impl.dart:473:7)
#22     _SyncCompleter.complete (dart:async/future_impl.dart:51:12)
#23     _AsyncAwaitCompleter.complete.<anonymous closure> (dart:async-patch/async_patch.dart:33:20)
#24     _rootRun (dart:async/zone.dart:1120:38)
#25     _CustomZone.run (dart:async/zone.dart:1021:19)
#26     _CustomZone.runGuarded (dart:async/zone.dart:923:7)
#27     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:963:23)
#28     _rootRun (dart:async/zone.dart:1124:13)
#29     _CustomZone.run (dart:async/zone.dart:1021:19)
#30     _CustomZone.runGuarded (dart:async/zone.dart:923:7)
#31     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:963:23)
#32     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#33     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#34     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:116:13)
#35     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:173:5)
```
</details>

**Comment by jonahwilliams** [comment]
What happens if you cycle a `flutter clean` in there, does it fail with the same error?

**Comment by maxnemoy** [comment]
the problem remains.
problem appeared a few builds ago.
on Linux and macOS there is no problem, only windows

**Comment by jld3103** [comment]
I have the same error on Linux :(

**Comment by rostopira** [comment]
Current master crashes after JS exception thrown with _very useful_ `null` in terminal and closes chrome window, I can't even figure out what the error is
Who on earth decided that it's a good idea?

**Comment by jld3103** [comment]
Error gone for me for several versions now

**Comment by grouma** [comment]
The ` Unable to start build daemon` issue should now be resolved. This issue was due to poor logic around invalidating the cached build snapshot. @jakemac53 made a fix in `package:build_runner` / `package:build_daemon` to solve this issue.

**Comment by maxnemoy** [comment]
after upgrading to version 1.9.4-pre.37, i have another problem

` FileSystemException: Directory listing failed, path = 'c:\users\maxnemoy\documents\src\newweb2\.dart_tool\*'`
 
[log](https://gist.github.com/maxnemoy/087df4f4261ad53a7f6c7bd8c827d06bl)

```
[√] Flutter (Channel master, v1.9.4-pre.37, on Microsoft Windows [Version 10.0.18362.295], locale ru-RU)
    • Flutter version 1.9.4-pre.37 at C:\libs\flutter
    • Framework revision 98ef956073 (4 hours ago), 2019-08-22 16:26:36 -0400
    • Engine revision 5f03c7e35d
    • Dart version 2.5.0

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at C:\Users\maxnemoy\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio CommunityВ 2019 16.2.2)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio CommunityВ 2019 version 16.2.29209.62

[√] Android Studio (version 3.4)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 38.2.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

[√] VS Code (version 1.37.1)
    • VS Code at C:\Users\maxnemoy\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.3.0

[√] Connected device (2 available)
    • Windows • Windows • windows-x64    • Microsoft Windows [Version 10.0.18362.295]
    • Chrome  • chrome  • web-javascript • Google Chrome 76.0.3809.100
```

**Comment by jonahwilliams** [comment]
Workaround for now: manually create .dart_tool in the root of your flutter project. Fix will land in linked PR above

**Comment by maxnemoy** [comment]
yes it is works
the thank you
