### ISSUE TITLE
Tests are failing in CI and reporting that they're OK

### ISSUE THREAD

**Issue by mklim** [flutter/flutter#38330]
Probably two separate problems here, whatever caused the failure and the fact that run_tests.py is returning 0 instead of 1 on tests failure.

```
Caused by: java.lang.ClassNotFoundException: io.flutter.embedding.android.FlutterActivity
	at org.robolectric.internal.bytecode.SandboxClassLoader.getByteCode(SandboxClassLoader.java:154)
	at org.robolectric.internal.bytecode.SandboxClassLoader.maybeInstrumentClass(SandboxClassLoader.java:114)
	at org.robolectric.internal.bytecode.SandboxClassLoader.lambda$findClass$0(SandboxClassLoader.java:107)
	at org.robolectric.util.PerfStatsCollector.measure(PerfStatsCollector.java:50)
	at org.robolectric.internal.bytecode.SandboxClassLoader.findClass(SandboxClassLoader.java:106)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
```

https://cirrus-ci.com/task/4808020213628928

**Comment by mklim** [comment]
It looks like _none_ of our tests are returning output in `run_tests.py`.

**Comment by mklim** [comment]
My first reading was right. The tests were normally using `subprocess.check_call` to automatically throw if any of the tests failed. The new JUNit tests were just using `call` instead and returning a status code which is then being ignored in `main()`.

**Comment by mklim** [comment]
Tests are back up and running, but `FlutterActivityAndFragmentDelegateTest` was disabled in order to turn the tests back on. Still need to fix it and turn it back on. /cc @matthew-carroll I'm closing this issue since CI is back to reporting failures correctly.
