### ISSUE TITLE
'package:flutter/src/rendering/object.dart': Failed assertion: line 1544: '!_needsCompositingBitsUpdate' is not true

### ISSUE THREAD

**Issue by apwilson** [flutter/flutter#3839]
```
15:19:07.984: ══╡ EXCEPTION CAUGHT BY RENDERING LIBRARY ╞═════════════════════════════════════════════════════════
15:19:07.987: The following assertion was thrown during paint():
15:19:07.992: 'package:flutter/src/rendering/object.dart': Failed assertion: line 1544:
15:19:07.993: '!_needsCompositingBitsUpdate' is not true.
15:19:07.995: Either the assertion indicates an error in the framework itself, or we should provide substantially
15:19:07.996: more information in this error message to help you determine and fix the underlying cause.
15:19:07.997: In either case, please report this assertion by filing a bug on GitHub:
15:19:07.998: https://github.com/flutter/flutter/issues/new
15:19:07.999: The following RenderObject was being processed when the exception was fired:
15:19:08.000: MyWidget relayoutSubtreeRoot=up2
15:19:08.001: This RenderObject had the following creator information:
15:19:08.005: MyWidget ← BlockBody ← Viewport ← Listener ← _GestureSemantics ←
15:19:08.011: RawGestureDetector-[GlobalKey 887099739] ← ScrollableViewport ← Block ← CustomPaint ← Banner ← ⋯
15:19:08.013: This RenderObject has no descendants.
15:19:08.015: When the exception was thrown, this was the stack:
15:19:08.017: #0      _AssertionError._throwNew (dart:core-patch/errors_patch.dart:27)
15:19:08.019: #1      RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:1544)
15:19:08.021: #2      PaintingContext.paintChild (package:flutter/src/rendering/object.dart:94)
15:19:08.023: #3      MyRendorObject.paint.<anonymous closure> (package:<redacted>.dart:607)
15:19:08.026: #4      PaintingContext.pushClipRect (package:flutter/src/rendering/object.dart:224)
15:19:08.028: #5      MyRendorObject.paint (package:<redacted>.dart:598)
15:19:08.030: #6      RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:1555)
15:19:08.032: #7      PaintingContext.paintChild (package:flutter/src/rendering/object.dart:94)
15:19:08.035: #8      RenderBox&ContainerRenderObjectMixin&RenderBoxContainerDefaultsMixin.defaultPaint (package:flutter/src/rendering/box.dart:1109)
15:19:08.037: #9      RenderBlock.paint (package:flutter/src/rendering/block.dart:265)
15:19:08.040: #10     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:1555)
15:19:08.042: #11     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:94)
15:19:08.045: #12     RenderViewport.paint.paintContents (package:flutter/src/rendering/viewport.dart:313)
15:19:08.047: #13     PaintingContext.pushClipRect (package:flutter/src/rendering/object.dart:224)
15:19:08.050: #14     RenderViewport.paint (package:flutter/src/rendering/viewport.dart:318)
15:19:08.051: #15     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:1555)
15:19:08.052: #16     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:94)
15:19:08.055: #17     RenderProxyBox.paint (package:flutter/src/rendering/proxy_box.dart:91)
15:19:08.057: #18     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:1555)
15:19:08.059: #19     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:94)
15:19:08.062: #20     RenderProxyBox.paint (package:flutter/src/rendering/proxy_box.dart:91)
15:19:08.064: #21     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:1555)
15:19:08.066: #22     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:94)
15:19:08.069: #23     RenderProxyBox.paint (package:flutter/src/rendering/proxy_box.dart:91)
15:19:08.071: #24     RenderCustomPaint.paint (package:flutter/src/rendering/proxy_box.dart:1572)
15:19:08.074: #25     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:1555)
15:19:08.076: #26     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:94)
15:19:08.079: #27     RenderView.paint (package:flutter/src/rendering/view.dart:121)
15:19:08.081: #28     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:1555)
15:19:08.083: #29     PaintingContext.repaintCompositedChild (package:flutter/src/rendering/object.dart:80)
15:19:08.086: #30     PipelineOwner.flushPaint (package:flutter/src/rendering/object.dart:771)
15:19:08.088: #31     BindingBase&SchedulerBinding&GestureBinding&ServicesBinding&RendererBinding.beginFrame (package:flutter/src/rendering/binding.dart:137)
15:19:08.090: #32     BindingBase&SchedulerBinding&GestureBinding&ServicesBinding&RendererBinding&WidgetsBinding.beginFrame (package:flutter/src/widgets/binding.dart:205)
15:19:08.093: #33     BindingBase&SchedulerBinding&GestureBinding&ServicesBinding&RendererBinding&WidgetsBinding._runApp (package:flutter/src/widgets/binding.dart:230)
15:19:08.095: #34     runApp (package:flutter/src/widgets/binding.dart:244)
15:19:08.098: #35     main.<main_async_body> (lib/main.dart:129)
15:19:08.100: #36     Future.Future.microtask.<anonymous closure> (dart:async/future.dart:144)
15:19:08.102: #37     _microtaskLoop (dart:async/schedule_microtask.dart:41)
15:19:08.105: #38     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50)
15:19:08.107: ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
```

**Comment by Hixie** [comment]
Probably caused by the child visitor being incorrectly implemented.

**Comment by goderbauer** [comment]
Any chance somebody still remembers what the cause of this exception was? Or what additional information would have been helpful? With the current information on the bug I don't know how to provide a better error message.
