### ISSUE TITLE
Crash bug when Listview nested in another CustomScrollView(or listview) without using Fixed height Contanier

### ISSUE THREAD

**Issue by LuZhengdong** [flutter/flutter#38415]
PROBLEM LOGS:
```
2019-08-13 17:15:10.105 12590-12656/com.example.flutter_app I/flutter: ══╡ EXCEPTION CAUGHT BY RENDERING LIBRARY ╞═════════════════════════════════════════════════════════
2019-08-13 17:15:10.105 12590-12656/com.example.flutter_app I/flutter: The following assertion was thrown during performLayout():
2019-08-13 17:15:10.105 12590-12656/com.example.flutter_app I/flutter: 'package:flutter/src/rendering/viewport.dart': Failed assertion: line 1616 pos 16:
2019-08-13 17:15:10.105 12590-12656/com.example.flutter_app I/flutter: 'constraints.hasBoundedHeight': is not true.
2019-08-13 17:15:10.105 12590-12656/com.example.flutter_app I/flutter: Either the assertion indicates an error in the framework itself, or we should provide substantially
2019-08-13 17:15:10.105 12590-12656/com.example.flutter_app I/flutter: more information in this error message to help you determine and fix the underlying cause.
2019-08-13 17:15:10.105 12590-12656/com.example.flutter_app I/flutter: In either case, please report this assertion by filing a bug on GitHub:
2019-08-13 17:15:10.105 12590-12656/com.example.flutter_app I/flutter:   https://github.com/flutter/flutter/issues/new?template=BUG.md
2019-08-13 17:15:10.105 12590-12656/com.example.flutter_app I/flutter: When the exception was thrown, this was the stack:
2019-08-13 17:15:10.105 12590-12656/com.example.flutter_app I/flutter: #2      RenderShrinkWrappingViewport.performLayout (package:flutter/src/rendering/viewport.dart:1616:16)
2019-08-13 17:15:10.105 12590-12656/com.example.flutter_app I/flutter: #3      RenderObject.layout (package:flutter/src/rendering/object.dart:1619:7)
2019-08-13 17:15:10.105 12590-12656/com.example.flutter_app I/flutter: #4      _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
2019-08-13 17:15:10.105 12590-12656/com.example.flutter_app I/flutter: #5      RenderObject.layout (package:flutter/src/rendering/object.dart:1619:7)
2019-08-13 17:15:10.105 12590-12656/com.example.flutter_app I/flutter: #6      _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
2019-08-13 17:15:10.105 12590-12656/com.example.flutter_app I/flutter: #7      RenderObject.layout (package:flutter/src/rendering/object.dart:1619:7)
2019-08-13 17:15:10.105 12590-12656/com.example.flutter_app I/flutter: #8      _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
2019-08-13 17:15:10.105 12590-12656/com.example.flutter_app I/flutter: #9      RenderObject.layout (package:flutter/src/rendering/object.dart:1619:7)
2019-08-13 17:15:10.105 12590-12656/com.example.flutter_app I/flutter: #10     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
2019-08-13 17:15:10.105 12590-12656/com.example.flutter_app I/flutter: #11     RenderObject.layout (package:flutter/src/rendering/object.dart:1619:7)
2019-08-13 17:15:10.105 12590-12656/com.example.flutter_app I/flutter: #12     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
2019-08-13 17:15:10.105 12590-12656/com.example.flutter_app I/flutter: #13     RenderObject.layout (package:flutter/src/rendering/object.dart:1619:7)
2019-08-13 17:15:10.105 12590-12656/com.example.flutter_app I/flutter: #14     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
2019-08-13 17:15:10.105 12590-12656/com.example.flutter_app I/flutter: #15     RenderObject.layout (package:flutter/src/rendering/object.dart:1619:7)
2019-08-13 17:15:10.105 12590-12656/com.example.flutter_app I/flutter: #16     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
2019-08-13 17:15:10.105 12590-12656/com.example.flutter_app I/flutter: #17     RenderObject.layout (package:flutter/src/rendering/object.dart:1619:7)
2019-08-13 17:15:10.105 12590-12656/com.example.flutter_app I/flutter: #18     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
2019-08-13 17:15:10.105 12590-12656/com.example.flutter_app I/flutter: #19     RenderObject.layout (package:flutter/src/rendering/object.dart:1619:7)
2019-08-13 17:15:10.106 12590-12656/com.example.flutter_app I/flutter: #20     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
2019-08-13 17:15:10.106 12590-12656/com.example.flutter_app I/flutter: #21     RenderObject.layout (package:flutter/src/rendering/object.dart:1619:7)
2019-08-13 17:15:10.106 12590-12656/com.example.flutter_app I/flutter: #22     RenderFlex.performLayout (package:flutter/src/rendering/flex.dart:743:15)
2019-08-13 17:15:10.106 12590-12656/com.example.flutter_app I/flutter: #23     RenderObject.layout (package:flutter/src/rendering/object.dart:1619:7)
2019-08-13 17:15:10.106 12590-12656/com.example.flutter_app I/flutter: #24     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
2019-08-13 17:15:10.106 12590-12656/com.example.flutter_app I/flutter: #25     RenderObject.layout (package:flutter/src/rendering/object.dart:1619:7)
2019-08-13 17:15:10.106 12590-12656/com.example.flutter_app I/flutter: #26     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
2019-08-13 17:15:10.106 12590-12656/com.example.flutter_app I/flutter: #27     RenderObject.layout (package:flutter/src/rendering/object.dart:1619:7)
2019-08-13 17:15:10.106 12590-12656/com.example.flutter_app I/flutter: #28     RenderSliverList.performLayout (package:flutter/src/rendering/sliver_list.dart:165:27)
2019-08-13 17:15:10.106 12590-12656/com.example.flutter_app I/flutter: #29     RenderObject.layout (package:flutter/src/rendering/object.dart:1619:7)
2019-08-13 17:15:10.106 12590-12656/com.example.flutter_app I/flutter: #30     RenderViewportBase.layoutChildSequence (package:flutter/src/rendering/viewport.dart:406:13)
2019-08-13 17:15:10.106 12590-12656/com.example.flutter_app I/flutter: #31     RenderViewport._attemptLayout (package:flutter/src/rendering/viewport.dart:1334:12)
2019-08-13 17:15:10.106 12590-12656/com.example.flutter_app I/flutter: #32     RenderViewport.performLayout (package:flutter/src/rendering/viewport.dart:1252:20)
2019-08-13 17:15:10.106 12590-12656/com.example.flutter_app I/flutter: #33     RenderObject.layout (package:flutter/src/rendering/object.dart:1619:7)
2019-08-13 17:15:10.106 12590-12656/com.example.flutter_app I/flutter: #34     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
2019-08-13 17:15:10.106 12590-12656/com.example.flutter_app I/flutter: #35     RenderObject.layout (package:flutter/src/rendering/object.dart:1619:7)
2019-08-13 17:15:10.106 12590-12656/com.example.flutter_app I/flutter: #36     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
2019-08-13 17:15:10.106 12590-12656/com.example.flutter_app I/flutter: #37     RenderObject.layout (package:flutter/src/rendering/object.dart:1619:7)
2019-08-13 17:15:10.106 12590-12656/com.example.flutter_app I/flutter: #38     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
2019-08-13 17:15:10.106 12590-12656/com.example.flutter_app I/flutter: #39     RenderObject.layout (package:flutter/src/rendering/object.dart:1619:7)
2019-08-13 17:15:10.106 12590-12656/com.example.flutter_app I/flutter: #40     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
2019-08-13 17:15:10.106 12590-12656/com.example.flutter_app I/flutter: #41     RenderObject.layout (package:flutter/src/rendering/object.dart:1619:7)
2019-08-13 17:15:10.106 12590-12656/com.example.flutter_app I/flutter: #42     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
2019-08-13 17:15:10.106 12590-12656/com.example.flutter_app I/flutter: #43     RenderObject.layout (package:flutter/src/rendering/object.dart:1619:7)
2019-08-13 17:15:10.106 12590-12656/com.example.flutter_app I/flutter: #44     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
2019-08-13 17:15:10.106 12590-12656/com.example.flutter_app I/flutter: #45     RenderObject.layout (package:flutter/src/rendering/object.dart:1619:7)
2019-08-13 17:15:10.106 12590-12656/com.example.flutter_app I/flutter: #46     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
2019-08-13 17:15:10.106 12590-12656/com.example.flutter_app I/flutter: #47     RenderObject.layout (package:flutter/src/rendering/object.dart:1619:7)
2019-08-13 17:15:10.106 12590-12656/com.example.flutter_app I/flutter: #48     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
2019-08-13 17:15:10.106 12590-12656/com.example.flutter_app I/flutter: #49     RenderObject.layout (package:flutter/src/rendering/object.dart:1619:7)
2019-08-13 17:15:10.106 12590-12656/com.example.flutter_app I/flutter: #50     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
2019-08-13 17:15:10.106 12590-12656/com.example.flutter_app I/flutter: #51     RenderObject.layout (package:flutter/src/rendering/object.dart:1619:7)
2019-08-13 17:15:10.106 12590-12656/com.example.flutter_app I/flutter: #52     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
2019-08-13 17:15:10.106 12590-12656/com.example.flutter_app I/flutter: #53     RenderObject.layout (package:flutter/src/rendering/object.dart:1619:7)
2019-08-13 17:15:10.106 12590-12656/com.example.flutter_app I/flutter: #54     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
2019-08-13 17:15:10.106 12590-12656/com.example.flutter_app I/flutter: #55     RenderObject.layout (package:flutter/src/rendering/object.dart:1619:7)
2019-08-13 17:15:10.106 12590-12656/com.example.flutter_app I/flutter: #56     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
2019-08-13 17:15:10.106 12590-12656/com.example.flutter_app I/flutter: #57     RenderObject.layout (package:flutter/src/rendering/object.dart:1619:7)
2019-08-13 17:15:10.106 12590-12656/com.example.flutter_app I/flutter: #58     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
2019-08-13 17:15:10.106 12590-12656/com.example.flutter_app I/flutter: #59     RenderObject.layout (package:flutter/src/rendering/object.dart:1619:7)
2019-08-13 17:15:10.106 12590-12656/com.example.flutter_app I/flutter: #60     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
2019-08-13 17:15:10.106 12590-12656/com.example.flutter_app I/flutter: #61     RenderObject.layout (package:flutter/src/rendering/object.dart:1619:7)
2019-08-13 17:15:10.106 12590-12656/com.example.flutter_app I/flutter: #62     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
2019-08-13 17:15:10.106 12590-12656/com.example.flutter_app I/flutter: #63     RenderObject.layout (package:flutter/src/rendering/object.dart:1619:7)
2019-08-13 17:15:10.106 12590-12656/com.example.flutter_app I/flutter: #64     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
2019-08-13 17:15:10.106 12590-12656/com.example.flutter_app I/flutter: #65     RenderObject.layout (package:flutter/src/rendering/object.dart:1619:7)
2019-08-13 17:15:10.106 12590-12656/com.example.flutter_app I/flutter: #66     RenderOffstage.performLayout (package:flutter/src/rendering/proxy_box.dart:3074:14)
2019-08-13 17:15:10.106 12590-12656/com.example.flutter_app I/flutter: #67     RenderObject.layout (package:flutter/src/rendering/object.dart:1619:7)
2019-08-13 17:15:10.107 12590-12656/com.example.flutter_app I/flutter: #68     RenderStack.performLayout (package:flutter/src/rendering/stack.dart:510:15)
2019-08-13 17:15:10.107 12590-12656/com.example.flutter_app I/flutter: #69     RenderObject._layoutWithoutResize (package:flutter/src/rendering/object.dart:1496:7)
2019-08-13 17:15:10.107 12590-12656/com.example.flutter_app I/flutter: #70     PipelineOwner.flushLayout (package:flutter/src/rendering/object.dart:765:18)
2019-08-13 17:15:10.107 12590-12656/com.example.flutter_app I/flutter: #71     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding.drawFrame (package:flutter/src/rendering/binding.dart:346:19)
2019-08-13 17:15:10.107 12590-12656/com.example.flutter_app I/flutter: #72     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding&WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:701:13)
2019-08-13 17:15:10.107 12590-12656/com.example.flutter_app I/flutter: #73     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:285:5)
2019-08-13 17:15:10.107 12590-12656/com.example.flutter_app I/flutter: #74     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1016:15)
2019-08-13 17:15:10.107 12590-12656/com.example.flutter_app I/flutter: #75     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:958:9)
2019-08-13 17:15:10.107 12590-12656/com.example.flutter_app I/flutter: #76     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:874:5)
2019-08-13 17:15:10.107 12590-12656/com.example.flutter_app I/flutter: #80     _invoke (dart:ui/hooks.dart:236:10)
2019-08-13 17:15:10.107 12590-12656/com.example.flutter_app I/flutter: #81     _drawFrame (dart:ui/hooks.dart:194:3)
2019-08-13 17:15:10.107 12590-12656/com.example.flutter_app I/flutter: (elided 5 frames from class _AssertionError and package dart:async)
2019-08-13 17:15:10.107 12590-12656/com.example.flutter_app I/flutter: The following RenderObject was being processed when the exception was fired: RenderShrinkWrappingViewport#ecc26 relayoutBoundary=up14 NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE:
2019-08-13 17:15:10.107 12590-12656/com.example.flutter_app I/flutter:   needs compositing
2019-08-13 17:15:10.107 12590-12656/com.example.flutter_app I/flutter:   creator: ShrinkWrappingViewport ← IgnorePointer-[GlobalKey#298b3] ← Semantics ← Listener ←
2019-08-13 17:15:10.107 12590-12656/com.example.flutter_app I/flutter:     _GestureSemantics ← RawGestureDetector-[LabeledGlobalKey<RawGestureDetectorState>#dd1c3] ←
2019-08-13 17:15:10.107 12590-12656/com.example.flutter_app I/flutter:     Listener ← _ScrollableScope ← _ScrollSemantics-[GlobalKey#d3aa6] ← RepaintBoundary ← CustomPaint ←
2019-08-13 17:15:10.107 12590-12656/com.example.flutter_app I/flutter:     RepaintBoundary ← ⋯
2019-08-13 17:15:10.107 12590-12656/com.example.flutter_app I/flutter:   parentData: <none> (can use size)
2019-08-13 17:15:10.107 12590-12656/com.example.flutter_app I/flutter:   constraints: BoxConstraints(0.0<=w<=411.4, 0.0<=h<=Infinity)
2019-08-13 17:15:10.107 12590-12656/com.example.flutter_app I/flutter:   size: MISSING
2019-08-13 17:15:10.107 12590-12656/com.example.flutter_app I/flutter:   axisDirection: right
2019-08-13 17:15:10.107 12590-12656/com.example.flutter_app I/flutter:   crossAxisDirection: down
2019-08-13 17:15:10.107 12590-12656/com.example.flutter_app I/flutter:   offset: ScrollPositionWithSingleContext#fe898(offset: 0.0, range: null..null, viewport: null,
2019-08-13 17:15:10.107 12590-12656/com.example.flutter_app I/flutter:     ScrollableState, ClampingScrollPhysics, IdleScrollActivity#d4385, ScrollDirection.idle)
2019-08-13 17:15:10.107 12590-12656/com.example.flutter_app I/flutter: This RenderObject had the following descendants (showing up to depth 5):
2019-08-13 17:15:10.107 12590-12656/com.example.flutter_app I/flutter:     child 0: RenderSliverPadding#0b7b6 NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
2019-08-13 17:15:10.107 12590-12656/com.example.flutter_app I/flutter:       child: RenderSliverList#d80b3 NEEDS-LAYOUT NEEDS-PAINT
```

![image](https://user-images.githubusercontent.com/4636078/62930352-d2eb1a80-bdee-11e9-87a6-444d628128c2.png)

![image](https://user-images.githubusercontent.com/4636078/62930201-8a336180-bdee-11e9-9bc4-b7cb101e95c8.png)

if i removed the contanier or delete the fixed height of the container , the app will crash,I do not know why, is it a bug?

**Comment by BondarenkoStas** [comment]
@LuZhengdong From the first view, it seems to be the desired behavior as infinite height will lead to infinite box size.
I think it's safe to close the issue. If you disagree, feel free to comment and I will reopen it.
