### ISSUE TITLE
[windows] flutter upgrade crashed

### ISSUE THREAD

**Issue by maxnemoy** [flutter/flutter#38420]
unable to complete update in windows

## Steps to Reproduce

git clone -b stable https://github.com/flutter/flutter.git
flutter channel master && flutter upgrade

## Logs
<details>
<summary>log</summary>

```
C:\Users\maxne>flutter upgrade
Checking Dart SDK version...
Downloading Dart SDK from Flutter engine 7dfdfc6faeb60192ab1f55ddb928a61438ea9399...
Unzipping Dart SDK...
Building flutter tool...
Running pub upgrade...
CreateProcessW failed 5

CreateProcessW failed 5

CreateProcessW failed 5
Unhandled exception:
ProcessException: Отказано в доступе.

  Command: "\"C:\Program Files\Git\cmd\git.EXE\"" log -n 1 --pretty=format:%H
#0      _ProcessImpl._runAndWait (dart:io-patch/process_patch.dart:496:7)
#1      _runNonInteractiveProcessSync (dart:io-patch/process_patch.dart:641:18)
#2      Process.runSync (dart:io-patch/process_patch.dart:66:12)
#3      LocalProcessManager.runSync (package:process/src/interface/local_process_manager.dart:93:20)
#4      _runWithLoggingSync (package:flutter_tools/src/base/process.dart:349:48)
#5      runSync (package:flutter_tools/src/base/process.dart:321:10)
#6      _runGit (package:flutter_tools/src/version.dart:535:10)
#7      new FlutterVersion (package:flutter_tools/src/version.dart:23:26)
#8      runInContext.<anonymous closure> (package:flutter_tools/src/context_runner.dart:85:29)
#9      AppContext._generateIfNecessary.<anonymous closure> (package:flutter_tools/src/base/context.dart:99:41)
#10     __InternalLinkedHashMap&_HashVMBase&MapMixin&_LinkedHashMapMixin.putIfAbsent (dart:collection-patch/compact_hash.dart:291:23)
#11     AppContext._generateIfNecessary (package:flutter_tools/src/base/context.dart:87:20)
#12     AppContext.get (package:flutter_tools/src/base/context.dart:115:32)
#13     FlutterVersion.instance (package:flutter_tools/src/version.dart:186:49)
#14     new _DefaultUsage (package:flutter_tools/src/reporting/usage.dart:148:58)
#15     new Usage (package:flutter_tools/src/reporting/usage.dart:70:9)
#16     runInContext.<anonymous closure> (package:flutter_tools/src/context_runner.dart:104:20)
#17     AppContext._generateIfNecessary.<anonymous closure> (package:flutter_tools/src/base/context.dart:99:41)
#18     __InternalLinkedHashMap&_HashVMBase&MapMixin&_LinkedHashMapMixin.putIfAbsent (dart:collection-patch/compact_hash.dart:291:23)
#19     AppContext._generateIfNecessary (package:flutter_tools/src/base/context.dart:87:20)
#20     AppContext.get (package:flutter_tools/src/base/context.dart:115:32)
#21     Usage.instance (package:flutter_tools/src/reporting/usage.dart:76:40)
#22     flutterUsage (package:flutter_tools/src/reporting/usage.dart:60:33)
#23     _handleToolError (package:flutter_tools/runner.dart:120:7)
<asynchronous suspension>
#24     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:77:13)
<asynchronous suspension>
#25     _rootRunBinary (dart:async/zone.dart:1148:13)
#26     _CustomZone.runBinary (dart:async/zone.dart:1037:19)
#27     runZoned.<anonymous closure> (dart:async/zone.dart:1479:21)
#28     _CustomZone.handleUncaughtError (dart:async/zone.dart:1003:19)
#29     Future._propagateToListeners (dart:async/future_impl.dart:589:16)
#30     Future._completeError (dart:async/future_impl.dart:491:5)
#31     _SyncCompleter._completeError (dart:async/future_impl.dart:55:12)
#32     _Completer.completeError (dart:async/future_impl.dart:27:5)
#33     _AsyncAwaitCompleter.completeError (dart:async-patch/async_patch.dart:40:18)
#34     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart)
<asynchronous suspension>
#35     _rootRun (dart:async/zone.dart:1124:13)
#36     _CustomZone.run (dart:async/zone.dart:1021:19)
#37     _runZoned (dart:async/zone.dart:1516:10)
#38     runZoned (dart:async/zone.dart:1500:12)
#39     run.<anonymous closure> (package:flutter_tools/runner.dart:61:18)
<asynchronous suspension>
#40     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:154:29)
<asynchronous suspension>
#41     _rootRun (dart:async/zone.dart:1124:13)
#42     _CustomZone.run (dart:async/zone.dart:1021:19)
#43     _runZoned (dart:async/zone.dart:1516:10)
#44     runZoned (dart:async/zone.dart:1463:12)
#45     AppContext.run (package:flutter_tools/src/base/context.dart:153:18)
<asynchronous suspension>
#46     runInContext (package:flutter_tools/src/context_runner.dart:58:24)
<asynchronous suspension>
#47     run (package:flutter_tools/runner.dart:50:10)
#48     main (package:flutter_tools/executable.dart:65:9)
<asynchronous suspension>
#49     main (file:///C:/libs/flutter/packages/flutter_tools/bin/flutter_tools.dart:8:3)
#50     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:303:32)
#51     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:12)
```
</details>

## flutter doctor

not working

**Comment by WindzTrumpet** [comment]
I have a same issues on master but stable It's still work.

**Comment by dolpheen** [comment]
Same on master, stable - ok

**Comment by mraleph** [comment]
This looks like a double escaping caused by dart-lang/sdk@8a0ae573a1ae1bcce4658096ee3b4934ce8539a8 

/fyi @ZichangG @a-siva - seems like we did a breaking change which broke anybody already doing escaping by hand.

**Comment by reg-codeswop** [comment]
I have the exact same issue.  I cannot run the Flutter command.  Not sure how to switch to the stable channel without a working flutter command?

**Comment by WindzTrumpet** [comment]
@reg-coseswop go to flutter folder and type git checkout stable

**Comment by WindzTrumpet** [comment]
> I have the exact same issue. I cannot run the Flutter command. Not sure how to switch to the stable channel without a working flutter command?

go to flutter folder and type git checkout stable

**Comment by ZichangG** [comment]
I will revert the change first and submit a fix later.
https://dart-review.googlesource.com/c/sdk/+/112921
