### ISSUE TITLE
Need better error message when not passing BuildContext to DefaultTextStyle.inherit

### ISSUE THREAD

**Issue by drewwarren** [flutter/flutter#3843]
When first using `DefaultTextStyle.inherit` I did not pass a `context` parameter and I got an exception that did not make it as obvious what the issue was. I would suggest making context a required parameter opposed to an optional named parameter. An alternative would be an assertion generating a better error message. I am not used to passing context when constructing widgets so I imagine it is something I would constantly forget to do when using factory constructors that want me to pass the context.

How I was improperly calling DefaultTextStyle.inherit without passing context: context.
```
    return new DefaultTextStyle.inherit(
      style: new TextStyle(fontSize: 22.0),
      child: new Row(
        children: [
          new Text(emphasized, style: const TextStyle(fontWeight: FontWeight.w500)),
          new Text(" $light", style: const TextStyle(fontWeight: FontWeight.w300)),
        ]
      )
    );
```

The error I received which required me to dig a little to understand the fix:
```
exception: [NoSuchMethodError objects/3]
I/flutter : ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
I/flutter : The following NoSuchMethodError was thrown building EmphasizedHeader:
I/flutter : The null object does not have a method 'inheritFromWidgetOfExactType'.
I/flutter : NoSuchMethodError: method not found: 'inheritFromWidgetOfExactType'
I/flutter : Receiver: null
I/flutter : Arguments: [Type: class 'DefaultTextStyle']
I/flutter : When the exception was thrown, this was the stack:
exception: [NoSuchMethodError objects/280]
I/flutter : #0      Object._noSuchMethod (dart:core-patch/object_patch.dart:42)
I/flutter : #1      Object.noSuchMethod (dart:core-patch/object_patch.dart:45)
I/flutter : #2      DefaultTextStyle.of (package:flutter/src/widgets/basic.dart:2027)
I/flutter : #3      DefaultTextStyle.DefaultTextStyle.inherit (package:flutter/src/widgets/basic.dart:1997)
...
```

```
[✓] Flutter (on Linux, channel master)
    • Flutter at /usr/local/google/home/drewwarren/flutter
    • Framework revision 826936cd33 (3 hours ago), engine revision 77426f65fd

[✓] Android toolchain - develop for Android devices (Android SDK 23.0.2)
    • Android SDK at /usr/local/google/users/drewwarren/aswb-sdk
    • Platform android-23, build-tools 23.0.2
    • OpenJDK Runtime Environment (build 1.8.0-google-v7-119990345-117822431)

[✓] Atom - a lightweight development environment for Flutter
    • Atom installed; Flutter plugin version 0.2.2
```

**Comment by abarth** [comment]
Sorry to have missed that.  https://github.com/flutter/flutter/pull/3844 adds an assert, which will hopefully give you a better error message.

**Comment by abarth** [comment]
@pq I tried using the `@required` annotation, but it didn't seem to generate an error when the parameter was missing.  /me probably wan't using it correctly.

**Comment by abarth** [comment]
Here's the diff I tried for `@required`.

```
diff --git a/dev/manual_tests/card_collection.dart b/dev/manual_tests/card_collection.dart
index 3541673..d4c9809 100644
--- a/dev/manual_tests/card_collection.dart
+++ b/dev/manual_tests/card_collection.dart
@@ -319,7 +319,7 @@ class CardCollectionState extends State<CardCollection> {
               )
             )
           : new DefaultTextStyle.inherit(
-              context: context,
+              // context: context,
               style: cardLabelStyle.copyWith(
                 fontSize: _varyFontSizes ? 5.0 + index : null
               ),
diff --git a/packages/flutter/lib/src/widgets/basic.dart b/packages/flutter/lib/src/widgets/basic.dart
index fc7e18d..2fd81d1 100644
--- a/packages/flutter/lib/src/widgets/basic.dart
+++ b/packages/flutter/lib/src/widgets/basic.dart
@@ -1987,12 +1987,12 @@ class DefaultTextStyle extends InheritedWidget {
   /// [BuildContext].
   factory DefaultTextStyle.inherit({
     Key key,
-    BuildContext context,
+    @required BuildContext context,
     TextStyle style,
     TextAlign textAlign,
     bool softWrap,
     TextOverflow overflow,
-    Widget child
+    @required Widget child
   }) {
     assert(context != null);
     assert(child != null);
```

**Comment by pq** [comment]
@abarth : it doesn't look like anything on your end.  More likely a bug in the analyzer.  Investigating...  Thanks!

**Comment by pq** [comment]
@abarth : confirmed that this is on our end.  The good news is it will be fixed for the next dev roll.  The bad news is we just did one and you can't use this annotation until the next one is pulled in.  In the meantime, we'll have to sit tight. 😿 

cc @Hixie @eseidel: TL;DR `@required` is not safe until we roll (and integrate) the `dev-4` build.

**Comment by abarth** [comment]
Thanks @pq !

**Comment by pq** [comment]
FWIW, https://github.com/dart-lang/sdk/issues/26440 is now fixed and we should be good to play with required annotations again with the next dev release.
