### ISSUE TITLE
SocketException: SocketException: Write failed

### ISSUE THREAD

**Issue by irakli1990** [flutter/flutter#38528]
## My code
```
 Future<CountryMapper> _sendCountryBorder(CountryBorder border) async {
    var data = {
      "CountryFrom": border.countryFrom,
      "CountryTo": border.countryTo,
      "IDDriver": border.iDDriver,
      "EnteryTime": "\/Date(${border.dateTime.millisecondsSinceEpoch})\/"
    };
    var body = json.encode(data);
    print(body);
    final response = await http.post('$endpoint',
        headers: {HttpHeaders.contentTypeHeader: 'application/json'},
        body: body);
    return borderFromJson(response.body);
  }

  CountryMapper borderFromJson(String str) {
    final jsonData = json.decode(str);
    return CountryMapper.fromJson(jsonData);
  }

  Future<bool> _sendToServer() async {
    return showDialog(
        context: context,
        builder: (context) => AlertDialog(
              title: Text('Czy chcesz wysłac danne na server?'),
              actions: <Widget>[
                FlatButton(
                  child: Text('NIE'),
                  onPressed: () => Navigator.pop(context, false),
                ),
                FlatButton(
                    child: Text('TAK'),
                    onPressed: () => this.borderList.forEach((countryBorder) {
                          _sendCountryBorder(countryBorder);
                        })),
              ],
            ));
  }
```
I have Internet permitions in all Android manifest.

## exception
```

SocketException: SocketException: Write failed (OS Error: Trwa zamykanie potoku.
, errno = 232), port = 0


I/flutter ( 7636): {"CountryFrom":"ARM","CountryTo":"AZE","IDDriver":"246","EnteryTime":"/Date(1565611200000)/"}
E/flutter ( 7636): [ERROR:flutter/lib/ui/ui_dart_state.cc(148)] Unhandled Exception: SocketException: OS Error: No route to host, errno = 113, address = tsonlinenew.tachoapi.com, port = 49818
E/flutter ( 7636): #0      IOClient.send (package:http/src/io_client.dart:33:23)
E/flutter ( 7636): <asynchronous suspension>
E/flutter ( 7636): #1      BaseClient._sendUnstreamed (package:http/src/base_client.dart:169:38)
E/flutter ( 7636): <asynchronous suspension>
E/flutter ( 7636): #2      BaseClient.post (package:http/src/base_client.dart:54:7)
E/flutter ( 7636): #3      post.<anonymous closure> (package:http/http.dart:70:16)
E/flutter ( 7636): #4      _withClient (package:http/http.dart:166:20)
E/flutter ( 7636): <asynchronous suspension>
E/flutter ( 7636): #5      post (package:http/http.dart:69:5)
E/flutter ( 7636): #6      _BordersListPageState._sendCountryBorder (package:tsonline/src/ui/borders.dart:88:28)
E/flutter ( 7636): <asynchronous suspension>
E/flutter ( 7636): #7      _BordersListPageState._sendToServer.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:tsonline/src/ui/borders.dart:112:27)
E/flutter ( 7636): #8      List.forEach (dart:core-patch/growable_array.dart:278:8)
E/flutter ( 7636): #9      _BordersListPageState._sendToServer.<anonymous closure>.<anonymous closure> (package:tsonline/src/ui/borders.dart:111:54)
E/flutter ( 7636): #10     _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:635:14)
E/flutter ( 7636): #11     _InkResponseState.build.<anonymous closure> (package:flutter/src/material/ink_well.dart:711:32)
E/flutter ( 7636): #12     GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:182:24)
E/flutter ( 7636): #13     TapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:365:11)
E/flutter ( 7636): #14     TapGestureRecognizer.handlePrimaryPointer (package:flutter/src/gestures/tap.dart:275:7)
E/flutter ( 7636): #15     PrimaryPointerGestureRecognizer.handleEvent (package:flutter/src/gestures/recognizer.dart:455:9)
E/flutter ( 7636): #16     PointerRouter._dispatch (package:flutter/src/gestures/pointer_router.dart:75:13)
E/flutter ( 7636): #17     PointerRouter.route (package:flutter/src/gestures/pointer_router.dart:102:11)
E/flutter ( 7636): #18     _WidgetsFlutterBinding&BindingBase&GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:218:19)
E/flutter ( 7636): #19     _WidgetsFlutterBinding&BindingBase&GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:198:22)
E/flutter ( 7636): #20     _WidgetsFlutterBinding&BindingBase&GestureBinding._handlePointerEvent (package:flutter/src/gestures/binding.dart:156:7)
E/flutter ( 7636): #21     _WidgetsFlutterBinding&BindingBase&GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:102:7)
E/flutter ( 7636): #22     _WidgetsFlutterBinding&BindingBase&GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:86:7)
E/flutter ( 7636): #23     _rootRunUnary (dart:async/zone.dart:1136:13)
E/flutter ( 7636): #24     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
E/flutter ( 7636): #25     _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
E/flutter ( 7636): #26     _invoke1 (dart:ui/hooks.dart:250:10)
E/flutter ( 7636): #27     _dispatchPointerDataPacket (dart:ui/hooks.dart:159:5)

```

```
info - Name non-constant identifiers using lowerCamelCase - lib\src\data\model\country\country_maper.dart:1:33 - non_constant_identifier_names
   info - Name non-constant identifiers using lowerCamelCase - lib\src\data\model\country\country_maper.dart:1:55 - non_constant_identifier_names
   info - Name non-constant identifiers using lowerCamelCase - lib\src\data\model\country\country_maper.dart:1:75 - non_constant_identifier_names
   info - Name non-constant identifiers using lowerCamelCase - lib\src\data\model\country\country_maper.dart:1:94 - non_constant_identifier_names
   info - Name non-constant identifiers using lowerCamelCase - lib\src\data\model\country\country_maper.dart:1:135 - non_constant_identifier_names
   info - Name non-constant identifiers using lowerCamelCase - lib\src\data\model\country\country_maper.dart:1:153 - non_constant_identifier_names
   info - Name non-constant identifiers using lowerCamelCase - lib\src\data\model\country\country_maper.dart:1:169 - non_constant_identifier_names
   info - Name non-constant identifiers using lowerCamelCase - lib\src\data\model\country\country_maper.dart:1:184 - non_constant_identifier_names

```

```
[√] Flutter (Channel stable, v1.7.8+hotfix.4, on Microsoft Windows [Version 10.0.17763.615], locale pl-PL)
    • Flutter version 1.7.8+hotfix.4 at C:\flutter
    • Framework revision 20e59316b8 (4 weeks ago), 2019-07-18 20:04:33 -0700
    • Engine revision fee001c93f
    • Dart version 2.4.0


[√] Android toolchain - develop for Android devices (Android SDK version 29.0.0-rc2)
    • Android SDK at C:\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.0-rc2
    • ANDROID_HOME = C:\Android
    • Java binary at: C:\androidstudio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
    • All Android licenses accepted.

[√] Android Studio (version 3.4)
    • Android Studio at C:\androidstudio
    • Flutter plugin version 38.2.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

[√] VS Code (version 1.37.0)
    • VS Code at C:\Users\Użytkownik\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.3.0

[√] Connected device (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 8.1.0 (API 27) (emulator)

• No issues found!

```

**Comment by irakli1990** [comment]
solved!

**Comment by irakli1990** [comment]
It is issue of ports and net routing in my case.
