### ISSUE TITLE
Flutter Web runner closes silently on (probably JS) exception

### ISSUE THREAD

**Issue by rostopira** [flutter/flutter#38539]
I have some issue in my Flutter Web app.
But I can't debug it, because when issue occurs chrome window closes itself silently, without any logs in stdout.
I can see issue in JS console, if I use `flutter build web` and run index.html manually, but it's minified so not useful at all.

It's serious bug that drives development nearly impossible and frustrating.
Please add copy of JS console output to stdout or just don't close window.

**Comment by rostopira** [comment]
Ping @jonahwilliams cause I know, that he wrote Chrome runner logic

**Comment by jonahwilliams** [comment]
> I can see issue in JS console,

Could you include that issue in this report?

**Comment by rostopira** [comment]
@jonahwilliams yeah, sure
```
Uncaught TypeError: J.ag(...).i is not a function
    at Object.b9 (main.dart.js:2238)
    at Bo.$2 (main.dart.js:34217)
    at Object.Tu (main.dart.js:1527)
    at Object.Oh (main.dart.js:3050)
    at cl (main.dart.js:3764)
    at RTCPeerConnection.<anonymous> (main.dart.js:34139)
main.dart.js:18036 Uncaught NoSuchMethodError: method not found: 'call'
Receiver: Closure 'minified:Bs'
Arguments: [Instance of 'minified:cA', Instance of 'minified:C']
    at Object.d (http://localhost:63342/flutter-webrtc-master2/flutter-webrtc-master2/example/build/web/main.dart.js:1567:3)
    at Bs.kS (http://localhost:63342/flutter-webrtc-master2/flutter-webrtc-master2/example/build/web/main.dart.js:18036:26)
    at Object.RW (http://localhost:63342/flutter-webrtc-master2/flutter-webrtc-master2/example/build/web/main.dart.js:2272:32)
    at Object.hI (http://localhost:63342/flutter-webrtc-master2/flutter-webrtc-master2/example/build/web/main.dart.js:1521:10)
    at Object.Ts (http://localhost:63342/flutter-webrtc-master2/flutter-webrtc-master2/example/build/web/main.dart.js:1544:10)
    at Object.Tu (http://localhost:63342/flutter-webrtc-master2/flutter-webrtc-master2/example/build/web/main.dart.js:1529:41)
    at Object.Oh (http://localhost:63342/flutter-webrtc-master2/flutter-webrtc-master2/example/build/web/main.dart.js:3050:27)
    at cl (http://localhost:63342/flutter-webrtc-master2/flutter-webrtc-master2/example/build/web/main.dart.js:3764:19)
    at RTCPeerConnection.<anonymous> (http://localhost:63342/flutter-webrtc-master2/flutter-webrtc-master2/example/build/web/main.dart.js:34143:85)
```

As I said, it's minified

I stuck on this issue while working on unpublished fork of flutter-webrtc plugin, it's open source, so I can provide zip with whole project, if you wish

**Comment by yjbanov** [comment]
Could you edit your `build.yaml` and change the `dart2js_args` options to include `--minify=false`?

Here's an example `build.yaml` file: https://github.com/dart-lang/build/blob/master/build_web_compilers/build.yaml

**Comment by rostopira** [comment]
@yjbanov I can't find `build.yaml` file anywhere
Did I mentioned, that I'm using unforked flutter web on master and not the fork?

**Comment by rostopira** [comment]
I've updated flutter to v1.9.1-pre.59, issue is gone
