### ISSUE TITLE
Focused & populated TextField causes strange behavior inside Scaffold

### ISSUE THREAD

**Issue by jaleelfingo** [flutter/flutter#38588]
## Steps to Reproduce

For sample application
1. Run application
2. Select second field
3. Select first field (populated with 'test')
4. Tap big teal container (should push a new scaffold)
5. On new scaffold, select second field, then first field again 
PROBLEM: 
6. Tapping big teal container does nothing, requires 2 additional taps before a scaffold is pushed again

Example application

https://gist.github.com/jaleelfingo/624584616824e2b1bfd0f6999326aac3

```
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatelessWidget {
  MyHomePage({Key key, this.title}) : super(key: key) {
      a.text = 'test';
  }

  final String title;
  final TextEditingController a = TextEditingController();
  final TextEditingController b = TextEditingController();

  final FocusNode bnode = FocusNode();


  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Column(
        children: <Widget>[
          Container(
            height: 10 + MediaQuery.of(context).padding.top,
          ),
          Expanded(
            child: Column(
              children: <Widget>[
                Padding(
                  padding: const EdgeInsets.all(50.0),
                  child: TextField(
                    autofocus: true,
                    controller: a,

                    textInputAction: TextInputAction.next,
                  decoration: InputDecoration(
                    hintText: 'A',
                  ),
                  ),
                ),
                Padding(
                  padding: const EdgeInsets.all(58.0),
                  child: TextField(
                    autofocus: true,
                    controller: b,
                  focusNode: bnode,
                  decoration: InputDecoration(
                    hintText: 'B',
                  ),
                  ),
                ),
                Expanded(
                  child: GestureDetector(
                      onTap:  () {
                        Navigator.of(context).push(MaterialPageRoute(builder: (_) => MyHomePage(title: '2',)));
                      },
                    child: Container(width: 100, height: 100, color: Colors.teal,)
                  ),
                )
              ],
            ),
          ),
        ],
      ),
    );
  }
}
```

## Logs

`flutter run --verbose` doesn't show anything after the following lines, I don't see anything printed while reproducing this issue

```
[        ] Updating files
[ +137 ms] DevFS: Sync finished
[        ] Syncing files to device iPhone... (completed in 1,326ms)
[        ] Synced 0.9MB.
[   +1 ms] Sending to VM service: _flutter.listViews({})
[   +3 ms] Result: {type: FlutterViewList, views: [{type: FlutterView, id: _flutterView/0x105022620, isolate: {type: @Isolate, fixedId: true, id: isolates/1055889331, name: main.dart$main-1055889331, number: 1055889331}}]}
[        ] <- accept
[        ] Connected to _flutterView/0x105022620.
[   +2 ms] 🔥  To hot reload changes while running, press "r". To hot restart (and rebuild state), press "R".
[        ] An Observatory debugger and profiler on iPhone is available at: http://127.0.0.1:1027/_YG8fhRvHkw=/
[        ] For a more detailed help message, press "h". To detach, press "d"; to quit, press "q".

```

Flutter analyze output:

```
$ flutter analyze
Analyzing flutter_app...
No issues found! (ran in 2.0s)
```

Flutter doctor output:

```
$ flutter doctor -v
[✓] Flutter (Channel stable, v1.7.8+hotfix.4, on Mac OS X 10.14.4 18E226, locale en-US)
    • Flutter version 1.7.8+hotfix.4 at /Users/jaleel/jalibs/flutter
    • Framework revision 20e59316b8 (4 weeks ago), 2019-07-18 20:04:33 -0700
    • Engine revision fee001c93f
    • Dart version 2.4.0


[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/jaleel/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 10.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.2.1, Build version 10E1001
    • CocoaPods version 1.7.2

[✓] iOS tools - develop for iOS devices
    • ios-deploy 1.9.4

[✓] Android Studio (version 3.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 33.3.1
    • Dart plugin version 182.5215
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)

[✓] VS Code (version 1.35.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.1.0

[✓] Connected device (2 available)
    • iPhone    • 12ddcafc9794714ec709f38322960ee6ec6b0752 • ios • iOS 12.3.1
    • iPhone Xs • 025BE904-1E8D-4D34-AAA7-B972A3E363EA     • ios • com.apple.CoreSimulator.SimRuntime.iOS-12-2 (simulator)

• No issues found!
```

Additional notes that may or may not be useful:

In the bigger, more complicated app, I get the same stacktrace detailed here https://github.com/flutter/flutter/issues/37046 , followed by truncated logs that appear to mean the same thing:

```
flutter: ══╡ EXCEPTION CAUGHT BY RENDERING LIBRARY ╞═════════════════════════════════════════════════════════
flutter: The following assertion was thrown during performLayout():
flutter: 'package:flutter/src/rendering/box.dart': Failed assertion: line 1694 pos 18: 'debugDoingThisResize
flutter: || debugDoingThisLayout ||
flutter:                  (RenderObject.debugActiveLayout == parent && _size._canBeUsedByParent)': is not
flutter: true.
flutter:
flutter: Either the assertion indicates an error in the framework itself, or we should provide substantially
flutter: more information in this error message to help you determine and fix the underlying cause.
flutter: In either case, please report this assertion by filing a bug on GitHub:
flutter:   https://github.com/flutter/flutter/issues/new?template=BUG.md
flutter:
flutter: When the exception was thrown, this was the stack:
flutter: #2      RenderBox.size.<anonymous closure> (package:flutter/src/rendering/box.dart:1694:18)
flutter: #3      RenderBox.size (package:flutter/src/rendering/box.dart:1700:6)
flutter: #4      RenderFractionalTranslation.applyPaintTransform (package:flutter/src/rendering/proxy_box.dart:2425:24)
flutter: #5      RenderObject.getTransformTo (package:flutter/src/rendering/object.dart:2167:24)
flutter: #6      RenderBox.globalToLocal (package:flutter/src/rendering/box.dart:2244:31)
flutter: #7      _ToolbarRenderBox.performLayout (package:flutter/src/cupertino/text_selection.dart:167:35)
flutter: #8      RenderObject.layout (package:flutter/src/rendering/object.dart:1619:7)
flutter: #9      _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
flutter: #10     RenderObject.layout (package:flutter/src/rendering/object.dart:1619:7)
flutter: #11     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
flutter: #12     RenderObject.layout (package:flutter/src/rendering/object.dart:1619:7)
flutter: #13     RenderStack.performLayout (package:flutter/src/rendering/stack.dart:510:15)
flutter: #14     RenderObject._layoutWithoutResize (package:flutter/src/rendering/object.dart:1496:7)
flutter: #15     PipelineOwner.flushLayout (package:flutter/src/rendering/object.dart:765:18)
flutter: #16     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding.drawFrame (package:flutter/src/rendering/binding.dart:346:19)
flutter: #17     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding&WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:701:13)
flutter: #18     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:285:5)
flutter: #19     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1016:15)
flutter: #20     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:958:9)
flutter: #21     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:874:5)
flutter: #25     _invoke (dart:ui/hooks.dart:236:10)
flutter: #26     _drawFrame (dart:ui/hooks.dart:194:3)
flutter: (elided 5 frames from class _AssertionError and package dart:async)
flutter:
flutter: The following RenderObject was being processed when the exception was fired: _ToolbarRenderBox#a6e8d NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE:
flutter:   needs compositing
flutter:   creator: CupertinoTextSelectionToolbar ← CompositedTransformFollower ← FadeTransition ←
flutter:     _OverlayEntry-[LabeledGlobalKey<_OverlayEntryState>#ed73d] ← Stack ← _Theatre ←
flutter:     Overlay-[LabeledGlobalKey<OverlayState>#54c03] ← _FocusMarker ← Semantics ← FocusScope ←
flutter:     AbsorbPointer ← Listener ← ⋯
flutter:   parentData: <none> (can use size)
flutter:   constraints: BoxConstraints(w=375.0, h=667.0)
flutter:   size: Size(375.0, 667.0)
flutter: This RenderObject had the following descendants (showing up to depth 5):
flutter:     child: RenderDecoratedBox#d1048 relayoutBoundary=up1 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
flutter:       child: RenderFlex#540f2 relayoutBoundary=up2 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
flutter:         child 1: RenderSemanticsGestureHandler#14c7c relayoutBoundary=up3 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
flutter:           child: RenderPointerListener#9c4ac relayoutBoundary=up4 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
flutter:             child: RenderSemanticsAnnotations#acade relayoutBoundary=up5 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
flutter:         child 2: RenderConstrainedBox#c4200 relayoutBoundary=up3 NEEDS-PAINT
flutter:         child 3: RenderSemanticsGestureHandler#cdc50 relayoutBoundary=up3 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
flutter:           child: RenderPointerListener#3d01a relayoutBoundary=up4 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
flutter:             child: RenderSemanticsAnnotations#b2666 relayoutBoundary=up5 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
flutter: ════════════════════════════════════════════════════════════════════════════════════════════════════
flutter: Another exception was thrown: NoSuchMethodError: The method 'toDouble' was called on null.
flutter: Another exception was thrown: 'package:flutter/src/rendering/box.dart': Failed assertion: line 1694 pos 18: 'debugDoingThisResize || debugDoingThisLayout ||
flutter: Another exception was thrown: NoSuchMethodError: The method 'toDouble' was called on null.
```

but I don't get the same stacktrace when encountering this issue in the example app I posted

Apologies for the weird title, I don't know exactly how to describe this issue

**Comment by jaleelfingo** [comment]
Actually, this can also be reproduced even on the first screen if you tap the second field, then the second field, then try to press the big teal container

**Comment by LongCatIsLooong** [comment]
It should be fixed on master. Could you try switching to master and see if that's the case? Please feel free to reopen if that doesn't fix it for you.
