### ISSUE TITLE
NoSuchMethodError: The getter 'cls' was called on null

### ISSUE THREAD

**Issue by pyetti** [flutter/flutter#38581]
Flutter crash report; please file at https://github.com/flutter/flutter/issues.

## command

```
flutter --no-color run --machine --track-widget-creation --device-id=LMQ610TA35997ea --start-paused lib/main.dart
```
## exception

```
SocketException: SocketException: Write failed (OS Error: Broken pipe, errno = 32), port = 0
```

## flutter doctor

```
[✓] Flutter (Channel stable, v1.7.8+hotfix.4, on Mac OS X 10.14.6 18G87, locale en-US)
    • Flutter version 1.7.8+hotfix.4 at /Users/peteryetti/development/flutter
    • Framework revision 20e59316b8 (4 weeks ago), 2019-07-18 20:04:33 -0700
    • Engine revision fee001c93f
    • Dart version 2.4.0

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/peteryetti/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/devTools/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 10.3)
    • Xcode at /Applications/devTools/Xcode.app/Contents/Developer
    • Xcode 10.3, Build version 10G8
    • CocoaPods version 1.7.3

[✓] iOS tools - develop for iOS devices
    • ios-deploy 1.9.4

[✓] Android Studio (version 3.4)
    • Android Studio at /Applications/devTools/Android Studio.app/Contents
    • Flutter plugin version 38.2.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

[✓] Connected device (1 available)
    • LM Q610 FGN • LMQ610TA35997ea • android-arm • Android 8.1.0 (API 27)

• No issues found!
```

## Console Output
```
Unhandled exception:
NoSuchMethodError: The getter 'cls' was called on null.
Receiver: null
Tried calling: cls
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:50:5)
#1      BodyBuilder.lookupInstanceMember (package:front_end/src/fasta/kernel/body_builder.dart:1604:30)
#2      BodyBuilder.scopeLookup (package:front_end/src/fasta/kernel/body_builder.dart:1764:13)
#3      BodyBuilder.handleIdentifier (package:front_end/src/fasta/kernel/body_builder.dart:1700:12)
#4      Parser.ensureIdentifier (package:front_end/src/fasta/parser/parser.dart:2165:14)
#5      Parser.parseSend (package:front_end/src/fasta/parser/parser.dart:4932:32)
#6      Parser.parseSendOrFunctionLiteral (package:front_end/src/fasta/parser/parser.dart:4675:12)
#7      Parser.parsePrimary (package:front_end/src/fasta/parser/parser.dart:4233:14)
#8      Parser.parseUnaryExpression (package:front_end/src/fasta/parser/parser.dart:4172:12)
#9      Parser.parsePrecedenceExpression (package:front_end/src/fasta/parser/parser.dart:3961:13)
#10     Parser.parseExpression (package:front_end/src/fasta/parser/parser.dart:3933:13)
#11     BodyBuilder.parseSingleExpression (package:front_end/src/fasta/kernel/body_builder.dart:1111:20)
#12     SourceLoader.buildExpression (package:front_end/src/fasta/source/source_loader.dart:327:21)
<asynchronous suspension>
#13     IncrementalCompiler.compileExpression.<anonymous closure> (package:front_end/src/fasta/incremental_compiler.dart:795:61)
<asynchronous suspension>
#14     CompilerContext.runInContext.<anonymous closure>.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart:122:46)
#15     new Future.sync (dart:async/future.dart:224:31)
#16     CompilerContext.runInContext.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart:122:19)
#17     _rootRun (dart:async/zone.dart:1124:13)
#18     _CustomZone.run (dart:async/zone.dart:1021:19)
#19     _runZoned (dart:async/zone.dart:1516:10)
#20     runZoned (dart:async/zone.dart:1463:12)
#21     CompilerContext.runInContext (package:front_end/src/fasta/compiler_context.dart:121:12)
#22     IncrementalCompiler.compileExpression (package:front_end/src/fasta/incremental_compiler.dart:726:26)
<asynchronous suspension>
#23     IncrementalCompiler.compileExpression (package:vm/incremental_compiler.dart:156:23)
#24     FrontendCompiler.compileExpression (package:vm/frontend_server.dart:527:44)
<asynchronous suspension>
#25     _FlutterFrontendCompiler.compileExpression (package:frontend_server/server.dart:62:22)
#26     listenAndCompile.<anonymous closure> (package:vm/frontend_server.dart:812:20)
<asynchronous suspension>
#27     _RootZone.runUnaryGuarded (dart:async/zone.dart:1314:10)
#28     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#29     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#30     _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:68:11)
#31     _EventSinkWrapper.add (dart:async/stream_transformers.dart:15:11)
#32     _StringAdapterSink.add (dart:convert/string_conversion.dart:236:11)
#33     _LineSplitterSink._addLines (dart:convert/line_splitter.dart:150:13)
#34     _LineSplitterSink.addSlice (dart:convert/line_splitter.dart:125:5)
#35     StringConversionSinkMixin.add (dart:convert/string_conversion.dart:163:5)
#36     _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:120:24)
#37     _RootZone.runUnaryGuarded (dart:async/zone.dart:1314:10)
#38     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#39     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#40     _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:68:11)
#41     _EventSinkWrapper.add (dart:async/stream_transformers.dart:15:11)
#42     _StringAdapterSink.add (dart:convert/string_conversion.dart:236:11)
#43     _StringAdapterSink.addSlice (dart:convert/string_conversion.dart:241:7)
#44     _Utf8ConversionSink.addSlice (dart:convert/string_conversion.dart:312:20)
#45     _Utf8ConversionSink.add (dart:convert/string_conversion.dart:305:5)
#46     _ConverterStreamEventSink.add (dart:convert/chunked_conversion.dart:72:18)
#47     _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:120:24)
#48     _RootZone.runUnaryGuarded (dart:async/zone.dart:1314:10)
#49     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#50     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#51     _SyncStreamController._sendData (dart:async/stream_controller.dart:764:19)
#52     _StreamController._add (dart:async/stream_controller.dart:640:7)
#53     _StreamController.add (dart:async/stream_controller.dart:586:5)
#54     _Socket._onData (dart:io-patch/socket_patch.dart:1786:41)
#55     _RootZone.runUnaryGuarded (dart:async/zone.dart:1314:10)
#56     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#57     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#58     _SyncStreamController._sendData (dart:async/stream_controller.dart:764:19)
#59     _StreamController._add (dart:async/stream_controller.dart:640:7)
#60     _StreamController.add (dart:async/stream_controller.dart:586:5)
#61     new _RawSocket.<anonymous closure> (dart:io-patch/socket_patch.dart:1335:33)
#62     _NativeSocket.issueReadEvent.issue (dart:io-patch/socket_patch.dart:856:14)
#63     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#64     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#65     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:116:13)
#66     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:173:5)

Oops; flutter has exited unexpectedly.
Sending crash report to Google.
Crash report sent (report ID: a7678e4033a5f597)
```

**Comment by dnfield** [comment]
Do you have a project or file that results in this?

**Comment by pyetti** [comment]
It hasn't happened in a while now, and to be honest, I've been trying to implement a change and have made so many changes since then that I'm not sure what may have been causing it. If it happens again, I'll post

**Comment by dnfield** [comment]
I'm going to close this in that case - /cc @aam or @rmacnak-google if either of you think this is helpful or want it re-opened.

Pleaes do re-open it if you're seeing it again.
