### ISSUE TITLE
google_map_flutter crash when open second time

### ISSUE THREAD

**Issue by trantrongkim98** [flutter/flutter#38597]
## issue

When I opened the map, I began to feel the map lagged, then I closed the map and opened it again then I had problems with my app, it was crash.

## Steps to Reproduce

1 open map
2. close map
3. open  map -> crash

## Logs
```
E/AndroidRuntime(  721): java.lang.NullPointerException: Attempt to invoke virtual method 'int android.view.Display.getDisplayId()' on a null object reference
E/AndroidRuntime(  721): 	at android.view.ViewRootImpl$ViewRootHandler.handleMessage(Unknown Source:249)
E/AndroidRuntime(  721): 	at android.os.Handler.dispatchMessage(Unknown Source:21)
E/AndroidRuntime(  721): 	at android.os.Looper.loop(Unknown Source:152)
E/AndroidRuntime(  721): 	at android.app.ActivityThread.main(Unknown Source:65)
E/AndroidRuntime(  721): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(  721): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(Unknown Source:11)
E/AndroidRuntime(  721): 	at com.android.internal.os.ZygoteInit.main(Unknown Source:338)


```

```
[✓] Flutter (Channel stable, v1.7.8+hotfix.4, on Linux, locale en_US.UTF-8)
    • Flutter version 1.7.8+hotfix.4 at /home/kim/flutter
    • Framework revision 20e59316b8 (4 weeks ago), 2019-07-18 20:04:33 -0700
    • Engine revision fee001c93f
    • Dart version 2.4.0

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.0)
    • Android SDK at /home/kim/Android/Sdk
    • Android NDK location not configured (optional; useful for native profiling
      support)
    • Platform android-29, build-tools 29.0.0
    • Java binary at: /snap/android-studio/77/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_152-release-1343-b16-5323222)
    • All Android licenses accepted.

[✓] Android Studio (version 3.4)
    • Android Studio at /snap/android-studio/77/android-studio
    • Flutter plugin version 36.0.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build
      1.8.0_152-release-1343-b16-5323222)

[✓] Connected device (1 available)
    • MI PAD 4 • 58e9aa99 • android-arm64 • Android 8.1.0 (API 27)

• No issues found!


```

**Comment by BondarenkoStas** [comment]
@trantrongkim98 Is the issue still relevant? Please specify version of your google_map_flutter

**Comment by iapicca** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact descriptions what happens, logs and the output of ' flutter doctor -v'  please.
All system setups can be slightly different so its always better to open new issues and reference related issues.
