### ISSUE TITLE
Flutter module with editable android directory - Gradle can't find local.properties

### ISSUE THREAD

**Issue by lucascolli** [flutter/flutter#38618]
In an Add2App project made editable with ```flutter make-host-app-editable```, local.properties is not created in the editable android/ module, but rather in the ephemeral .android/ module which is still generated. With local.properties being looked for in the editable module, any command that builds gradle will fail with:

```
$ flutter build apk --debug
Initializing gradle...                                              0.9s
Resolving dependencies...                                               
* Error running Gradle:
ProcessException: Process "/Users/.../Desktop/eComm/Android/flutter_module/android/gradlew" exited abnormally:

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project 'android'.
> A problem occurred configuring project ':flutter'.
   > SDK location not found. Define location with sdk.dir in the local.properties file or with an ANDROID_HOME environment variable.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get
full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 0s
  Command: /Users/.../Desktop/eComm/Android/flutter_module/android/gradlew app:properties


Please review your Gradle project setup in the android/ folder.
```

Since local.properties shouldn't be version controlled, and the only way (that I've found) to get an updated apk is with ./gradlew assembleDebug from the ephemeral module or by temporarily copying local.properties into the editable module and then using flutter build apk as usual, this is becoming a hinderance.

## Steps to Reproduce

1. Set up Android embedding project following [Add Flutter to existing apps](https://github.com/flutter/flutter/wiki/Add-Flutter-to-existing-apps) wiki
2. cd flutter_module
3. Make the native modules editable with flutter make-host-app-editable
4. flutter run or flutter build apk/flutter build aar

## Logs

```
$ flutter run --verbose
[  +30 ms] executing: [/Users/.../Desktop/lcedev/flutter/] git log -n 1 --pretty=format:%H
[  +41 ms] Exit code 0 from: git log -n 1 --pretty=format:%H
[        ] 83a8a575eed882c49b629effedf7c95b6184515d
[        ] executing: [/Users/.../Desktop/lcedev/flutter/] git describe --match v*.*.* --first-parent --long --tags
[  +25 ms] Exit code 0 from: git describe --match v*.*.* --first-parent --long --tags
[        ] v1.8.4-117-g83a8a575e
[   +9 ms] executing: [/Users/.../Desktop/lcedev/flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[   +7 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/master
[        ] executing: [/Users/.../Desktop/lcedev/flutter/] git ls-remote --get-url origin
[   +7 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[  +62 ms] executing: [/Users/.../Desktop/lcedev/flutter/] git rev-parse --abbrev-ref HEAD
[   +8 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] master
[ +329 ms] executing: /Users/.../Library/Android/sdk/platform-tools/adb devices -l
[  +10 ms] Exit code 0 from: /Users/.../Library/Android/sdk/platform-tools/adb devices -l
[        ] List of devices attached
           emulator-5554          device product:sdk_gphone_x86 model:Android_SDK_built_for_x86 device:generic_x86 transport_id:9
[  +18 ms] executing: /Users/.../Desktop/lcedev/flutter/bin/cache/artifacts/libimobiledevice/idevice_id -h
[  +51 ms] /usr/bin/xcrun simctl list --json devices
[ +276 ms] /Users/.../Library/Android/sdk/platform-tools/adb -s emulator-5554 shell getprop
[  +55 ms] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +3 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[  +44 ms] Found plugin flutter_crashlytics at
/Users/.../Desktop/lcedev/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_crashlytics-1.0.0/
[   +4 ms] Found plugin flutter_picker at
/Users/.../Desktop/lcedev/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_picker-1.0.13/
[  +82 ms] Found plugin flutter_crashlytics at
/Users/.../Desktop/lcedev/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_crashlytics-1.0.0/
[   +1 ms] Found plugin flutter_picker at
/Users/.../Desktop/lcedev/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_picker-1.0.13/
[  +52 ms] ro.hardware = ranchu
[   +8 ms] executing: [/Users/.../Desktop/eComm/Android/flutter_module/ios/Runner.xcodeproj/] /usr/bin/xcodebuild -project
/Users/.../Desktop/eComm/Android/flutter_module/ios/Runner.xcodeproj -target Runner -showBuildSettings
[+1567 ms] Exit code 0 from: /usr/bin/xcodebuild -project /Users/.../Desktop/eComm/Android/flutter_module/ios/Runner.xcodeproj
-target Runner -showBuildSettings
[   +1 ms] Build settings for action build and target Runner:

               *Removed lengthy xcode build settings to improve readability*

[  +55 ms] Using hardware rendering with device Android SDK built for x86. If you get graphics artifacts, consider enabling software
rendering
           with "--enable-software-rendering".
[  +14 ms] Launching lib/main.dart on Android SDK built for x86 in debug mode...
[  +11 ms] Initializing gradle...
[   +6 ms] Using gradle from /Users/.../Desktop/eComm/Android/flutter_module/android/gradlew.
[  +11 ms] executing: /usr/bin/defaults read /Applications/Android Studio.app/Contents/Info
[  +45 ms] Exit code 0 from: /usr/bin/defaults read /Applications/Android Studio.app/Contents/Info
[        ] {
               CFBundleDevelopmentRegion = English;
               CFBundleDocumentTypes =     (
                           {
                       CFBundleTypeExtensions =             (
                           ipr
                       );
                       CFBundleTypeIconFile = "studio.icns";
                       CFBundleTypeName = "Android Studio Project File";
                       CFBundleTypeRole = Editor;
                   },
                           {
                       CFBundleTypeExtensions =             (
                           "*"
                       );
                       CFBundleTypeName = "All documents";
                       CFBundleTypeOSTypes =             (
                           "****"
                       );
                       CFBundleTypeRole = Editor;
                       LSTypeIsPackage = 0;
                   }
               );
               CFBundleExecutable = studio;
               CFBundleGetInfoString = "Android Studio 3.4, build AI-183.6156.11.34.5522156. Copyright JetBrains s.r.o., (c)
               2000-2019";
               CFBundleIconFile = "studio.icns";
               CFBundleIdentifier = "com.google.android.studio";
               CFBundleInfoDictionaryVersion = "6.0";
               CFBundleName = "Android Studio";
               CFBundlePackageType = APPL;
               CFBundleShortVersionString = "3.4";
               CFBundleSignature = "????";
               CFBundleURLTypes =     (
                           {
                       CFBundleTypeRole = Editor;
                       CFBundleURLName = Stacktrace;
                       CFBundleURLSchemes =             (
                           idea
                       );
                   }
               );
               CFBundleVersion = "AI-183.6156.11.34.5522156";
               JVMOptions =     {
                   ClassPath =
                   "$APP_PACKAGE/Contents/lib/bootstrap.jar:$APP_PACKAGE/Contents/lib/extensions.jar:$APP_PACKAGE/Contents/lib/util.jar
                   :$APP_PACKAGE/Contents/lib/jdom.jar:$APP_PACKAGE/Contents/lib/log4j.jar:$APP_PACKAGE/Contents/lib/trove4j.jar:$APP_P
                   ACKAGE/Contents/lib/jna.jar";
                   JVMVersion = "1.8*,1.8+";
                   MainClass = "com.intellij.idea.Main";
                   Properties =         {
                       "idea.executable" = studio;
                       "idea.home.path" = "$APP_PACKAGE/Contents";
                       "idea.java.redist" = Bundled;
                       "idea.paths.selector" = "AndroidStudio3.4";
                       "idea.platform.prefix" = AndroidStudio;
                   };
                   WorkingDirectory = "$APP_PACKAGE/Contents/bin";
               };
               LSApplicationCategoryType = "public.app-category.developer-tools";
               LSArchitecturePriority =     (
                   "x86_64"
               );
               LSMinimumSystemVersion = "10.8";
               LSRequiresNativeExecution = YES;
               NSHighResolutionCapable = 1;
               NSSupportsAutomaticGraphicsSwitching = 1;
           }
[   +2 ms] executing: /usr/bin/defaults read /Applications/Android Studio.app/Contents/Info CFBundleShortVersionString
[  +43 ms] Exit code 0 from: /usr/bin/defaults read /Applications/Android Studio.app/Contents/Info CFBundleShortVersionString
[        ] 3.4
[  +80 ms] executing: /Users/.../Desktop/eComm/Android/flutter_module/android/gradlew -v
[ +708 ms] 
                    ------------------------------------------------------------
                    Gradle 4.10.1
                    ------------------------------------------------------------

                    Build time:   2018-09-12 11:33:27 UTC
                    Revision:     76c9179ea9bddc32810f9125ad97c3315c544919

                    Kotlin DSL:   1.0-rc-6
                    Kotlin:       1.2.61
                    Groovy:       2.4.15
                    Ant:          Apache Ant(TM) version 1.9.11 compiled on March 23 2018
                    JVM:          1.8.0_152-release (JetBrains s.r.o 25.152-b01)
                    OS:           Mac OS X 10.14.5 x86_64
[  +11 ms] Initializing gradle... (completed in 0.9s)
[   +1 ms] Resolving dependencies...
[        ] executing: [/Users/.../Desktop/eComm/Android/flutter_module/android/]
/Users/.../Desktop/eComm/Android/flutter_module/android/gradlew app:properties
[ +952 ms] 
                    FAILURE: Build failed with an exception.

                    * What went wrong:
                    A problem occurred configuring root project 'android'.
                    > A problem occurred configuring project ':flutter'.
                       > SDK location not found. Define location with sdk.dir in the local.properties file or with an ANDROID_HOME
                       environment variable.

                    * Try:
                    Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run
                    with --scan to get full insights.

                    * Get more help at https://help.gradle.org

                    BUILD FAILED in 0s
[   +5 ms] Resolving dependencies... (completed in 1.0s)
[   +3 ms] * Error running Gradle:
           ProcessException: Process "/Users/.../Desktop/eComm/Android/flutter_module/android/gradlew" exited abnormally:
           
           FAILURE: Build failed with an exception.
           
           * What went wrong:
           A problem occurred configuring root project 'android'.
           > A problem occurred configuring project ':flutter'.
              > SDK location not found. Define location with sdk.dir in the local.properties file or with an ANDROID_HOME environment
variable.
           
           * Try:
           Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with
--scan to get
           full insights.
           
           * Get more help at https://help.gradle.org
           
           BUILD FAILED in 0s
             Command: /Users/.../Desktop/eComm/Android/flutter_module/android/gradlew app:properties
           
[   +4 ms] "flutter run" took 4,490ms.
Please review your Gradle project setup in the android/ folder.

#0      throwToolExit (package:flutter_tools/src/base/common.dart:28:3)
#1      _readGradleProject (package:flutter_tools/src/android/gradle.dart:233:7)
<asynchronous suspension>
#2      _gradleAppProject (package:flutter_tools/src/android/gradle.dart:112:37)
<asynchronous suspension>
#3      getGradleAppOut (package:flutter_tools/src/android/gradle.dart:106:29)
<asynchronous suspension>
#4      AndroidApk.fromAndroidProject (package:flutter_tools/src/application_package.dart:165:23)
<asynchronous suspension>
#5      ApplicationPackageFactory.getPackageForPlatform (package:flutter_tools/src/application_package.dart:47:32)
<asynchronous suspension>
#6      FlutterDevice.runHot (package:flutter_tools/src/resident_runner.dart:359:56)
<asynchronous suspension>
#7      HotRunner.run (package:flutter_tools/src/run_hot.dart:253:39)
<asynchronous suspension>
#8      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:472:37)
<asynchronous suspension>
#9      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:490:18)
#10     _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:77:64)
#11     _rootRunUnary (dart:async/zone.dart:1132:38)
#12     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#13     _FutureListener.handleValue (dart:async/future_impl.dart:126:18)
#14     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:639:45)
#15     Future._propagateToListeners (dart:async/future_impl.dart:668:32)
#16     Future._complete (dart:async/future_impl.dart:473:7)
#17     _SyncCompleter.complete (dart:async/future_impl.dart:51:12)
#18     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:28:18)
#19     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:294:13)
#20     RunCommand.usageValues (package:flutter_tools/src/commands/run.dart)
#21     _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:77:64)
#22     _rootRunUnary (dart:async/zone.dart:1132:38)
#23     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#24     _FutureListener.handleValue (dart:async/future_impl.dart:126:18)
#25     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:639:45)
#26     Future._propagateToListeners (dart:async/future_impl.dart:668:32)
#27     Future._complete (dart:async/future_impl.dart:473:7)
#28     _SyncCompleter.complete (dart:async/future_impl.dart:51:12)
#29     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:28:18)
#30     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:294:13)
#31     AndroidDevice.isLocalEmulator (package:flutter_tools/src/android/android_device.dart)
#32     _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:77:64)
#33     _rootRunUnary (dart:async/zone.dart:1132:38)
#34     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#35     _FutureListener.handleValue (dart:async/future_impl.dart:126:18)
#36     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:639:45)
#37     Future._propagateToListeners (dart:async/future_impl.dart:668:32)
#38     Future._complete (dart:async/future_impl.dart:473:7)
#39     _SyncCompleter.complete (dart:async/future_impl.dart:51:12)
#40     _AsyncAwaitCompleter.complete.<anonymous closure> (dart:async-patch/async_patch.dart:33:20)
#41     _rootRun (dart:async/zone.dart:1120:38)
#42     _CustomZone.run (dart:async/zone.dart:1021:19)
#43     _CustomZone.runGuarded (dart:async/zone.dart:923:7)
#44     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:963:23)
#45     _rootRun (dart:async/zone.dart:1124:13)
#46     _CustomZone.run (dart:async/zone.dart:1021:19)
#47     _CustomZone.runGuarded (dart:async/zone.dart:923:7)
#48     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:963:23)
#49     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#50     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#51     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:116:13)
#52     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:173:5)
```

```
$ flutter doctor --verbose
[✓] Flutter (Channel master, v1.8.5-pre.117, on Mac OS X 10.14.5 18F132, locale en-US)
    • Flutter version 1.8.5-pre.117 at /Users/lcollins/Desktop/lcedev/flutter
    • Framework revision 83a8a575ee (5 days ago), 2019-08-10 12:38:20 -0700
    • Engine revision ff49ca1c6e
    • Dart version 2.5.0 (build 2.5.0-dev.1.0 f29f41f1a5)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/lcollins/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 10.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.3, Build version 10G8
    • CocoaPods version 1.7.2

[✓] Android Studio (version 3.4)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 37.0.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

[✓] VS Code (version 1.37.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.3.0

[✓] Connected device (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 9 (API 28) (emulator)

• No issues found!
```

**Comment by blasten** [comment]
@lucascolli I tested on stable and master, and I see a `/android/local.properties` file. `flutter build apk` and `flutter run` seem to work fine.

**Comment by jonahwilliams** [comment]
Closing as resolved
