### ISSUE TITLE
I follow the official documentation of flutter, create a new application, and report this error when running.

### ISSUE THREAD

**Issue by Jameszyq** [flutter/flutter#38672]
## Logs
```
Unhandled exception:
FormatException: Illegal scheme character (at character 7)
export PUB_HOSTED_URL=https://dart-pub.mirrors.sjtug.sjtu.edu.cn/
      ^

#0      _Uri._fail (dart:core/uri.dart:1620:5)
#1      _Uri._makeScheme (dart:core/uri.dart:2075:9)
#2      new _Uri.notSimple (dart:core/uri.dart:1462:18)
#3      Uri.parse (dart:core/uri.dart:1019:17)
#4      HostedSource._pubHostedUrlConfig (package:pub/src/source/hosted.dart:57:19)
#5      HostedSource.defaultUrl (package:pub/src/source/hosted.dart:50:28)
#6      new UploaderCommand (package:pub/src/command/uploader.dart:27:42)
#7      new PubCommandRunner (package:pub/src/command_runner.dart:107:16)
#8      main (file:///C:/b/s/w/ir/k/src/third_party/dart/third_party/pkg/pub/bin/pub.dart:8:3)
#9      _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:299:32)
#10     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:12)
Running "flutter pub get" in an1_salessystemmobile...
pub get failed (255)
```

**Comment by moroumo** [comment]
Found this issue in dart lang side: https://github.com/dart-lang/pub/issues/2046

**Comment by BondarenkoStas** [comment]
@Jameszyq I think it's safe to close the issue as it's dart related and is taken into account my the dart team. If you disagree, feel free to comment so I will reopen it.
