### ISSUE TITLE
Allow nested hero widgets

### ISSUE THREAD

**Issue by friebetill** [flutter/flutter#38684]
## Scenario
In my application I have a Markdown editor with three screens:
1. Screen to look at markdown (Screen A)
2. Screen to edit markdown (Screen B)
3. Screen to enlarge pictures in markdown (Screen C) 

To make the transition more comfortable for the user, I would like to use two independent `Hero` transitions:
1. From the first screen to the second screen to edit markdown (A -> B)
  Transition goes from a `MarkdownView` widget to a `MarkdownEdit` widget.
2. From the first screen to the third screen to view images in markdown enlarged (A -> C) 
  Transition goes from an `Image` widget inside the `MarkdownView` widget to an `Image` widget on the new screen.

## Problem
The second `Hero` widget is inside the first `Hero` widget and causes an assert error because of this PR #28470, because one should not nest `Hero` widgets. I don't know why this is technically impossible. The nested `Hero` widgets have different `Hero` tags and on the second and third screen there is only one `Hero` widget each.

If it's needed, I will write a small program to demonstrate the error, but since the error has already been mentioned several times in the given issues, I would like to present a scenario in which it makes sense to nest Hero widgets. I would also be happy about alternative solutions. 

## Related issues

#1398 introduces the problem, but unfortunately close without explanation.
#28470 adds the assert that causes the error, there are a few people complaining about the changes, but it is not further discussed.

## Logs

```
I/flutter (24765): ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
I/flutter (24765): The following assertion was thrown building Hero(tag: image-hero,
I/flutter (24765): dirty, state: _HeroState#1595c):
I/flutter (24765): A Hero widget cannot be the descendant of another Hero widget.
I/flutter (24765): 'package:flutter/src/widgets/heroes.dart':
I/flutter (24765): Failed assertion: line 359 pos 7: 'context.ancestorWidgetOfExactType(Hero) == null'
I/flutter (24765): 
I/flutter (24765): Either the assertion indicates an error in the framework itself, or we should provide substantially
I/flutter (24765): more information in this error message to help you determine and fix the underlying cause.
I/flutter (24765): In either case, please report this assertion by filing a bug on GitHub:
I/flutter (24765):   https://github.com/flutter/flutter/issues/new?template=BUG.md
I/flutter (24765): 
I/flutter (24765): When the exception was thrown, this was the stack:
I/flutter (24765): #2      _HeroState.build (package:flutter/src/widgets/heroes.dart:359:7)
I/flutter (24765): #3      StatefulElement.build (package:flutter/src/widgets/framework.dart:4012:27)
I/flutter (24765): #4      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3924:15)
I/flutter (24765): #5      Element.rebuild (package:flutter/src/widgets/framework.dart:3721:5)
I/flutter (24765): #6      ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3907:5)
I/flutter (24765): #7      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4053:11)
I/flutter (24765): #8      ComponentElement.mount (package:flutter/src/widgets/framework.dart:3902:5)
I/flutter (24765): #9      Element.inflateWidget (package:flutter/src/widgets/framework.dart:3084:14)
...
I/flutter (24765): #470    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:958:9)
I/flutter (24765): #471    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:874:5)
I/flutter (24765): #475    _invoke (dart:ui/hooks.dart:236:10)
I/flutter (24765): #476    _drawFrame (dart:ui/hooks.dart:194:3)
I/flutter (24765): (elided 5 frames from class _AssertionError and package dart:async)
I/flutter (24765): ════════════════════════════════════════════════════════════════════════════════════════════════════
```

```
[✓] Flutter (Channel unknown, v1.7.8+hotfix.3, on Mac OS X 10.14.5 18F132, locale en-DE)
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 10.2)
[✓] iOS tools - develop for iOS devices
[✓] Chrome - develop for the web
[✓] Android Studio (version 3.4)
[✓] VS Code (version 1.34.0)
[✓] Connected device (3 available)

• No issues found!
```

**Comment by alidawud** [comment]
I don't understand why disable nested hero.. don't make any sense!

**Comment by tapizquent** [comment]
Any update on this??

**Comment by TahaTesser** [comment]
Related to [#29565](https://github.com/flutter/flutter/issues/29565

**Comment by AnuragVadd** [comment]
![78686790-17dd3780-7911-11ea-9f44-f661626ce96d](https://user-images.githubusercontent.com/38868279/79688629-1561d280-826d-11ea-8f31-4c9023391f04.gif)
I was hoping to achieve the transition in the gif above using nested hero widgets. Inside the container, I have declared a column which has 3 children: Image and two text widgets. I tried to wrap the Image and the bottom text inside a Hero widget but since there was an assertion, I was unable to achieve this.

**Comment by candreotti** [comment]
Any news regarding this topic?
I am in the same situation, I need to have a nested hero inside of one of my widget...
Can someone explain me why this has been blocked and why should it be avoided?
Is it going to be fixed in the future or it will remain as is?
Thank you

**Comment by Dorbmon** [comment]
Anything New?It is important to be able to make a nested hero.

**Comment by ShehanMadushanka** [comment]
Pls allow nested hero widgets

**Comment by rayanht** [comment]
There is no need for nested Heros imo. You can achieve the sought result by putting two Heros side-by-side in Stack.

**Comment by f0rx** [comment]
This feature should be enabled!
Commenting the assertion in Hero class doesn't produce a bug, so Why?

**Comment by UttamPanchasara** [comment]
Commenting the assertion not working for me, it's not animating anymore

**Comment by eyalkutz** [comment]
Please note that that in a flow that starts at screen A and could then navigate to either screen B or C a nested hero widget that provides a different animation for each of these options might make sense even if the two animations would never happen at the same time

**Comment by brunodmn** [comment]
Same issue here, nested Heros throwing error even though it's shown normally.

**Comment by shifenis** [comment]
Someone has just found a solution to this? Without using `Stack`? 
Like in my case I have the `Hero` that is the first element of my `Scaffold`...
Why there is that assertion, what does it entail?

**Comment by namangor04** [comment]
> Someone has just found a solution to this? Without using `Stack`?
> Like in my case I have the `Hero` that is the first element of my `Scaffold`...
> Why there is that assertion, what does it entail?

Same situation here, i commented out the assertion in the heroes.dart, lines 441-444 on Flutter version 2.2.0 channel stable.

**Comment by ModWU** [comment]
> There is no need for nested Heros imo. You can achieve the sought result by putting two Heros side-by-side in Stack.

There are cases where you need to nest rather than juxtapose!

**Comment by vysakhrj** [comment]
Able to achieve similar effect using stack and making the background as seperate hero. Try it out if your designer needs this :)

**Comment by ercantomac** [comment]
Are there at least any plans for this? We definitely need it. Using Stack widget isn't always possible.

**Comment by rasitayaz** [comment]
Does removing the assertion cause any performance issues? I just checked #28470 and I can't comprehend how it got merged into the engine in the first place. It doesn't even have any reasonable explanation:

> A Hero widget currently can have other Hero widgets as its child, but according to its [documentation](https://api.flutter.dev/flutter/widgets/Hero-class.html) it should mark its child as a candidate for hero animations. So, having a Hero as a child to a Hero, is kind of redundant.

Well guess what, it is the opposite of redundant as stated by many people here, also in the pull request itself.

**Comment by hasanmhallak** [comment]
any updates on this??

**Comment by dev-mockingbird** [comment]
any updates on this??

**Comment by abenezeryohannes** [comment]
any update on this pls

**Comment by Pachebel** [comment]
Hi everybody, I solved this issue by passing the hero tag (and the imageUrl) between the routes, you can check the sample code below:

<details closed>
<summary> Minimal reproducible code:</summary>
<br>

``` dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});
  @override
  Widget build(BuildContext context) {
    return const MaterialApp(
      home: MyHomeView(),
    );
  }
}

class MyHomeView extends StatelessWidget {
  const MyHomeView({super.key});

  @override
  Widget build(BuildContext context) {
    const heroTag = 'your_hero_tag';
    const imageUrl = 'https://picsum.photos/250?image=9';

    return Scaffold(
      appBar: AppBar(
        title: const Text('Home View'),
      ),
      body: Column(
        children: [
          Center(
            child: GestureDetector(
              onTap: () => Navigator.push(
                context,
                MaterialPageRoute(
                  builder: (context) => const DetailView(
                    heroTag: heroTag,
                    imageUrl: imageUrl,
                  ),
                ),
              ),
              child: Hero(
                tag: heroTag,
                child: Image.network(imageUrl),
              ),
            ),
          ),
        ],
      ),
    );
  }
}

class DetailView extends StatelessWidget {
  final Object heroTag;
  final String imageUrl;

  const DetailView({super.key, required this.heroTag, required this.imageUrl});

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text('Detail View'),
      ),
      body: Column(
        mainAxisAlignment: MainAxisAlignment.end,
        children: [
          Hero(
            tag: heroTag,
            child: GestureDetector(
              onTap: () => Navigator.push(
                context,
                MaterialPageRoute(
                  builder: (context) => ImageView(
                    heroTag: heroTag,
                    imageUrl: imageUrl,
                  ),
                ),
              ),
              child: Image.network(
                imageUrl,
              ),
            ),
          ),
        ],
      ),
    );
  }
}

class ImageView extends StatelessWidget {
  final Object heroTag;
  final String imageUrl;

  const ImageView({super.key, required this.heroTag, required this.imageUrl});

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text('Image View'),
      ),
      body: Hero(
        tag: heroTag,
        child: Image.network(
          imageUrl,
        ),
      ),
    );
  }
}

```
</details>

The result:

![gravacao_hero](https://github.com/flutter/flutter/assets/89677437/1ea62f68-1da1-47af-acf4-77860d5181da)

Hope it helps :)

**Comment by Requieem** [comment]
Is this just being ignored? Pretty big issue imho. Is there any documented way of achieving the same results?

**Comment by Pachebel** [comment]
> Is this just being ignored? Pretty big issue imho. Is there any documented way of achieving the same results?

I've made a code that partially solves this problem, you can check it out:
https://github.com/flutter/flutter/issues/38684#issuecomment-2105880740

**Comment by thisisjaymehta** [comment]
A Flutter team member needs to address this. This is a very counterintuitive issue. Why are nested Hero widgets not allowed? Nested Hero widgets are essential for achieving this effect on multiple pages simultaneously.

**Comment by vietstone-ng** [comment]
@Pachebel your code passes a heroTag to multiple screens. Actually, we want multiple heroes in one screen. Something like this:
```
WidgetA(
  child: Hero(
    tag: 'hero-1',
    child: Column(
      children: [
        WidgetB(),
        Heror(
          tag: 'hero-2',
          child: WidgetC()
        ),
      ]
    )
  )
)
```

Then `hero-1` goes to ScreenA, and `hero-2` goes to ScreenB. They nested widgets in the parent screen.

**Comment by vietstone-ng** [comment]
+1 upvote for this feature

**Comment by Pachebel** [comment]
> @Pachebel your code passes a heroTag to multiple screens. Actually, we want multiple heroes in one screen. Something like this:
> 
> ```
> 
> WidgetA(
> 
>   child: Hero(
> 
>     tag: 'hero-1',
> 
>     child: Column(
> 
>       children: [
> 
>         WidgetB(),
> 
>         Heror(
> 
>           tag: 'hero-2',
> 
>           child: WidgetC()
> 
>         ),
> 
>       ]
> 
>     )
> 
>   )
> 
> )
> 
> ```
> 
> 
> 
> Then `hero-1` goes to DetailScreenA, and `hero-2` goes to DetailScreenC. They nested widgets in the parent screen.

Oooh, I see, sorry, I have misunderstood the real issue🫠

**Comment by firstmetcs** [comment]
Any updates? With our UI design, to be descendant of other heroes will be the Reasonable design, the page route to another page, mainwhile some widget will hero to the new page

**Comment by amir14a** [comment]
I have same problem and I don't know why this is blocked! what happen if you have nested heros?

**Comment by zamaniafshar** [comment]
+1

**Comment by SimplyLiz** [comment]
Any updates on this? The exception makes no sense. For now I’m also using the workaround of having to mod framework files, but that’s an ugly workaround imho. I would like to see that feature officially supported in flutter

**Comment by AlexeyKatsuro** [comment]
Are there any plans to address this issue? This feature is critical for many use cases. 

For example, in my chat app:  
- A long tap on a message card opens a contextual menu using a Hero animation for the entire message card (text + images).  
- Tapping on an image in the message card opens a full-screen viewer with another Hero animation.  

Currently, implementing such scenarios is difficult due to Hero's limitations. Improving Hero's flexibility would greatly benefit such cases.

**Comment by ercantomac** [comment]
An insight from the team would be needed before someone starts working on this

**Comment by bugrevealingbme** [comment]
any update?

**Comment by micheljung** [comment]
The assertion is only active in debug builds, not in release builds.

So I tested nested Hero widgets in a release build and it works just like expected - so apparently, it is generally possible.

It seems like the assertion is pointless and could just be removed.

**Comment by micheljung** [comment]
Workaround: Make the nested hero conditional on `kReleaseMode`.

**Comment by AlexeyKatsuro** [comment]
@micheljung the easyjet way to avoid the assertion:

```
class AppHero extends Hero {
  const AppHero({
    required super.tag,
    super.key,
    super.createRectTween,
    super.flightShuttleBuilder,
    super.placeholderBuilder,
    super.transitionOnUserGestures,
    required super.child,
  });
}
```

https://github.com/flutter/flutter/issues/38684#issuecomment-2587253234
