### ISSUE TITLE
error gradle running flutter app for first time

### ISSUE THREAD

**Issue by israakd** [flutter/flutter#38690]
im trying to run my first flutter app and stucked at this error

```
Launching lib\main.dart on SM A510F in debug mode...
Initializing gradle...
Finished with error: ProcessException: Process "C:\Users\DELL\Desktop\flutter_app1\android\gradlew.bat" exited abnormally:
Exception in thread "main" java.lang.RuntimeException: Timeout of 120000 reached waiting for exclusive access to file: C:\Users\DELL\.gradle\wrapper\dists\gradle-4.10.2-all\9fahxiiecdb76a5g3aw9oi8rv\gradle-4.10.2-all.zip
	at org.gradle.wrapper.ExclusiveFileAccessManager.access(ExclusiveFileAccessManager.java:61)
	at org.gradle.wrapper.Install.createDist(Install.java:48)
	at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:128)
	at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:61)
  Command: C:\Users\DELL\Desktop\flutter_app1\android\gradlew.bat -v
```

some notes: platform sdk 28 is unzipped in sdk/platforms/android-28, but the zip file had a folder named in it android-9. idk!

**Comment by BondarenkoStas** [comment]
@israakd Is it still relevant? Please provide your ```flutter doctor -v``` output.

**Comment by iapicca** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact descriptions what happens, logs and the output of ' flutter doctor -v'  please.
All system setups can be slightly different so its always better to open new issues and reference related issues.
