### ISSUE TITLE
flutter build aar not working 

### ISSUE THREAD

**Issue by rahuldevanavar91** [flutter/flutter#38694]
Following this [link](https://github.com/flutter/flutter/wiki/Add-Flutter-to-existing-apps) to add flutter in the existing app . to build AAR for android  I am using 
`flutter build aar` but I am getting the following error 

> Could not find a subcommand named "aar" for "flutter build".

**Flutter doctor** 

```

[✓] Flutter (Channel stable, v1.7.8+hotfix.4, on Mac OS X 10.14.6 18G87, locale en-IN)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)

```

**Comment by rahuldevanavar91** [comment]
@dnfield

**Comment by dnfield** [comment]
You need to be on a newer release.  Try dev or master.

**Comment by jmagman** [comment]
This is a relatively new feature.  @dnfield is referring to the dev or master channel.  Instructions for switching are here https://github.com/flutter/flutter/wiki/Flutter-build-release-channels.

**Comment by rahuldevanavar91** [comment]
@dnfield 
I think `build aar` is released on the stable channel, but I am getting the following error.
```
Gradle task assembleAarRelease failed with exit code 1

#0      throwToolExit (package:flutter_tools/src/base/common.dart:28:3)
#1      buildGradleAar (package:flutter_tools/src/android/gradle.dart:577:5)
#2      _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:71:64)
#3      _rootRunUnary (dart:async/zone.dart:1132:38)
#4      _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#5      _FutureListener.handleValue (dart:async/future_impl.dart:137:18)
#6      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:678:45)
#7      Future._propagateToListeners (dart:async/future_impl.dart:707:32)
#8      Future._completeWithValue (dart:async/future_impl.dart:522:5)
#9      _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:30:15)
#10     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:288:13)
#11     runCommandAndStreamOutput (package:flutter_tools/src/base/process.dart)
#12     _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:71:64)
#13     _rootRunUnary (dart:async/zone.dart:1132:38)
#14     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#15     _FutureListener.handleValue (dart:async/future_impl.dart:137:18)
#16     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:678:45)
#17     Future._propagateToListeners (dart:async/future_impl.dart:707:32)
#18     Future._completeWithValue (dart:async/future_impl.dart:522:5)
#19     Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:552:7)
#20     _rootRun (dart:async/zone.dart:1124:13)
#21     _CustomZone.run (dart:async/zone.dart:1021:19)
#22     _CustomZone.runGuarded (dart:async/zone.dart:923:7)
#23     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:963:23)
#24     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#25     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#26     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:116:13)
#27     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:173:5)



```

**Comment by dnfield** [comment]
@blasten 
It would help to see what the Gradle error is...
