### ISSUE TITLE
Failed to capture fingerprint of output files for task ':app:compileFlutterBuildDebugArm' property 'outputDirectory' during up-to-date check.

### ISSUE THREAD

**Issue by cristianfb1989** [flutter/flutter#38711]
Hi! I try debug my application but it show me this:

`What went wrong:`
`Failed to capture fingerprint of output files for task ':app:compileFlutterBuildDebugArm' property 'outputDirectory' during up-to-date check.`
`Could not read path 'C:\Users\(myuser)\Documents\pop_up\build\app\intermediates\flutter\debug\android-arm\flutter_assets\fonts'.`

```
Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option 
to get more log output. Run with --scan to get full insights.
```

```
BUILD FAILED in 1s
Gradle task assembleDebug failed with exit code 1
Exited (sigterm)
```

## command

```
flutter build bundle --target C:\Users\(myuser)\Documents\pop_up\lib\main.dart --target-platform android-arm --filesystem-scheme org-dartlang-root --track-widget-creation --depfile C:\Users\(myuser)\Documents\pop_up\build\app\intermediates\flutter\debug\android-arm/snapshot_blob.bin.d --asset-dir C:\Users\(myuser)\Documents\pop_up\build\app\intermediates\flutter\debug\android-arm/flutter_assets --debug
```

## exception

```
FileSystemException: FileSystemException: Deletion failed, path = 'C:\Users\(myuser)\Documents\pop_up\build\app\intermediates\flutter\debug\android-arm/flutter_assets' (OS Error: El directorio no está vacío.
, errno = 145)

#0      _Directory._deleteSync (dart:io/directory_impl.dart:206:7)
#1      FileSystemEntity.deleteSync (dart:io/file_system_entity.dart:464:47)
#2      ForwardingFileSystemEntity.deleteSync (package:file/src/forwarding/forwarding_file_system_entity.dart:72:16)
#3      writeBundle (package:flutter_tools/src/bundle.dart:181:15)
<asynchronous suspension>
#4      assemble (package:flutter_tools/src/bundle.dart:172:9)
<asynchronous suspension>
#5      BundleBuilder.build (package:flutter_tools/src/bundle.dart:115:11)
<asynchronous suspension>
#6      BuildBundleCommand.runCommand (package:flutter_tools/src/commands/build_bundle.dart:119:25)
<asynchronous suspension>
#7      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:490:18)
<asynchronous suspension>
#8      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:407:33)
<asynchronous suspension>
#9      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:154:29)
<asynchronous suspension>
#10     _rootRun (dart:async/zone.dart:1124:13)
#11     _CustomZone.run (dart:async/zone.dart:1021:19)
#12     _runZoned (dart:async/zone.dart:1516:10)
#13     runZoned (dart:async/zone.dart:1463:12)
#14     AppContext.run (package:flutter_tools/src/base/context.dart:153:18)
<asynchronous suspension>
#15     FlutterCommand.run (package:flutter_tools/src/runner/flutter_command.dart:397:20)
#16     CommandRunner.runCommand (package:args/command_runner.dart:197:27)
<asynchronous suspension>
#17     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:402:21)
<asynchronous suspension>
#18     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:154:29)
<asynchronous suspension>
#19     _rootRun (dart:async/zone.dart:1124:13)
#20     _CustomZone.run (dart:async/zone.dart:1021:19)
#21     _runZoned (dart:async/zone.dart:1516:10)
#22     runZoned (dart:async/zone.dart:1463:12)
#23     AppContext.run (package:flutter_tools/src/base/context.dart:153:18)
<asynchronous suspension>
#24     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:356:19)
<asynchronous suspension>
#25     CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:112:25)
#26     new Future.sync (dart:async/future.dart:224:31)
#27     CommandRunner.run (package:args/command_runner.dart:112:14)
#28     FlutterCommandRunner.run (package:flutter_tools/src/runner/flutter_command_runner.dart:242:18)
#29     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:63:22)
<asynchronous suspension>
#30     _rootRun (dart:async/zone.dart:1124:13)
#31     _CustomZone.run (dart:async/zone.dart:1021:19)
#32     _runZoned (dart:async/zone.dart:1516:10)
#33     runZoned (dart:async/zone.dart:1500:12)
#34     run.<anonymous closure> (package:flutter_tools/runner.dart:61:18)
<asynchronous suspension>
#35     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:154:29)
<asynchronous suspension>
#36     _rootRun (dart:async/zone.dart:1124:13)
#37     _CustomZone.run (dart:async/zone.dart:1021:19)
#38     _runZoned (dart:async/zone.dart:1516:10)
#39     runZoned (dart:async/zone.dart:1463:12)
#40     AppContext.run (package:flutter_tools/src/base/context.dart:153:18)
<asynchronous suspension>
#41     runInContext (package:flutter_tools/src/context_runner.dart:58:24)
<asynchronous suspension>
#42     run (package:flutter_tools/runner.dart:50:10)
#43     main (package:flutter_tools/executable.dart:65:9)
<asynchronous suspension>
#44     main (file:///C:/src/flutter/packages/flutter_tools/bin/flutter_tools.dart:8:3)
#45     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:303:32)
#46     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:12)
```

```
[✓] Flutter (Channel master, v1.9.1-pre.109, on Microsoft Windows [VersiÃ³n 10.0.16299.1087], locale es-AR)
    • Flutter version 1.9.1-pre.109 at C:\src\flutter
    • Framework revision ce6dedfc0c (9 hours ago), 2019-08-20 01:03:36 -0400
    • Engine revision 10167db433
    • Dart version 2.5.0

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.0)
    • Android SDK at C:\Users\(myuser)\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.0
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
    • All Android licenses accepted.

[✓] Android Studio (version 3.4)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 38.2.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

[✓] VS Code (version 1.37.1)
    • VS Code at C:\Users\(myuser)\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.3.0

[✓] Connected device (1 available)
    • LG H440AR • LGH440ARad51902f • android-arm • Android 5.0.1 (API 21)

• No issues found!
```

What can I do for fix it? Thx

**Comment by IgnacioCentola** [comment]
Well you can close the folder (I assume you´re using VS Code), open the terminal, go to your project path and use `flutter clean`, then re-open project. That works for me, but it is a recurrent issue, so it would be nice some kind of permanent solution from the Flutter team (or anyone who sees this)

Note: this issue does not ocurr when using Android Studio

**Comment by cristianfb1989** [comment]
@IgnacioCentola Thanks for the advice!

**Comment by ali80** [comment]
just reloading VSCode fixed it for me, weird.

**Comment by cristianfb1989** [comment]
@ali80 thx you!!
