### ISSUE TITLE
Assertion failed

### ISSUE THREAD

**Issue by SwissCheese5** [flutter/flutter#38745]
Hello, I'm getting the following error message in the console:

```
Initializing hot reload...
Syncing files to device Android SDK built for x86...
I/flutter (18113): ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
I/flutter (18113): The following assertion was thrown building ConfigureMeeting(dirty, dependencies:
I/flutter (18113): [_LocalizationsScope-[GlobalKey#988fd], _InheritedTheme], state:
I/flutter (18113): _ConfigureMeetingState#7b002(tickers: tracking 4 tickers)):
I/flutter (18113): Assertion failed
I/flutter (18113): 
I/flutter (18113): Either the assertion indicates an error in the framework itself, or we should provide substantially
I/flutter (18113): more information in this error message to help you determine and fix the underlying cause.
I/flutter (18113): In either case, please report this assertion by filing a bug on GitHub:
I/flutter (18113):   https://github.com/flutter/flutter/issues/new?template=BUG.md
I/flutter (18113): 
I/flutter (18113): User-created ancestor of the error-causing widget was:
I/flutter (18113):   MaterialApp file:///C:/Users/saad4/AndroidStudioProjects/meeting_maker/lib/main.dart:17:12
I/flutter (18113): 
I/flutter (18113): When the exception was thrown, this was the stack:
I/flutter (18113): #0      new MultiChildRenderObjectWidget.<anonymous closure> (package:flutter/src/widgets/framework.dart:1691:11)
I/flutter (18113): #1      new MultiChildRenderObjectWidget (package:flutter/src/widgets/framework.dart:1696:8)
I/flutter (18113): #2      new Flex (package:flutter/src/widgets/basic.dart:3711:8)
I/flutter (18113): #3      new Column (package:flutter/src/widgets/basic.dart:4247:8)
I/flutter (18113): #4      _ConfigureMeetingState.build.<anonymous closure> (package:meeting_maker/configure_meeting.dart:173:43)
I/flutter (18113): #5      MappedListIterable.elementAt (dart:_internal/iterable.dart:414:29)
I/flutter (18113): #6      ListIterable.toList (dart:_internal/iterable.dart:219:19)
I/flutter (18113): #7      _ConfigureMeetingState.build (package:meeting_maker/configure_meeting.dart:263:32)
I/flutter (18113): #8      StatefulElement.build (package:flutter/src/widgets/framework.dart:4039:27)
I/flutter (18113): #9      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3933:15)
I/flutter (18113): #10     Element.rebuild (package:flutter/src/widgets/framework.dart:3730:5)
I/flutter (18113): #11     StatefulElement.update (package:flutter/src/widgets/framework.dart:4112:5)
I/flutter (18113): #12     Element.updateChild (package:flutter/src/widgets/framework.dart:2885:15)
I/flutter (18113): #13     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:5126:14)
I/flutter (18113): #14     Element.updateChild (package:flutter/src/widgets/framework.dart:2885:15)
I/flutter (18113): #15     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3953:16)
I/flutter (18113): #16     Element.rebuild (package:flutter/src/widgets/framework.dart:3730:5)
I/flutter (18113): #17     StatelessElement.update (package:flutter/src/widgets/framework.dart:4008:5)
I/flutter (18113): #18     Element.updateChild (package:flutter/src/widgets/framework.dart:2885:15)
I/flutter (18113): #19     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:5126:14)
I/flutter (18113): #20     Element.updateChild (package:flutter/src/widgets/framework.dart:2885:15)
I/flutter (18113): #21     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:5126:14)
I/flutter (18113): #22     Element.updateChild (package:flutter/src/widgets/framework.dart:2885:15)
I/flutter (18113): #23     RenderObjectElement.updateChildren (package:flutter/src/widgets/framework.dart:4844:32)
I/flutter (18113): #24     MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:5235:17)
I/flutter (18113): #25     Element.updateChild (package:flutter/src/widgets/framework.dart:2885:15)
I/flutter (18113): #26     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3953:16)
I/flutter (18113): #27     Element.rebuild (package:flutter/src/widgets/framework.dart:3730:5)
I/flutter (18113): #28     StatefulElement.update (package:flutter/src/widgets/framework.dart:4112:5)
I/flutter (18113): #29     Element.updateChild (package:flutter/src/widgets/framework.dart:2885:15)
I/flutter (18113): #30     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:5126:14)
I/flutter (18113): #31     Element.updateChild (package:flutter/src/widgets/framework.dart:2885:15)
I/flutter (18113): #32     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3953:16)
I/flutter (18113): #33     Element.rebuild (package:flutter/src/widgets/framework.dart:3730:5)
I/flutter (18113): #34     StatefulElement.update (package:flutter/src/widgets/framework.dart:4112:5)
I/flutter (18113): #35     Element.updateChild (package:flutter/src/widgets/framework.dart:2885:15)
I/flutter (18113): #36     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:5126:14)
I/flutter (18113): #37     Element.updateChild (package:flutter/src/widgets/framework.dart:2885:15)
I/flutter (18113): #38     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3953:16)
I/flutter (18113): #39     Element.rebuild (package:flutter/src/widgets/framework.dart:3730:5)
I/flutter (18113): #40     StatefulElement.update (package:flutter/src/widgets/framework.dart:4112:5)
I/flutter (18113): #41     Element.updateChild (package:flutter/src/widgets/framework.dart:2885:15)
I/flutter (18113): #42     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:5126:14)
I/flutter (18113): #43     Element.updateChild (package:flutter/src/widgets/framework.dart:2885:15)
I/flutter (18113): #44     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3953:16)
I/flutter (18113): #45     Element.rebuild (package:flutter/src/widgets/framework.dart:3730:5)
I/flutter (18113): #46     StatefulElement.update (package:flutter/src/widgets/framework.dart:4112:5)
I/flutter (18113): #47     Element.updateChild (package:flutter/src/widgets/framework.dart:2885:15)
I/flutter (18113): #48     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3953:16)
I/flutter (18113): #49     Element.rebuild (package:flutter/src/widgets/framework.dart:3730:5)
I/flutter (18113): #50     StatelessElement.update (package:flutter/src/widgets/framework.dart:4008:5)
I/flutter (18113): #51     Element.updateChild (package:flutter/src/widgets/framework.dart:2885:15)
I/flutter (18113): #52     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3953:16)
I/flutter (18113): #53     Element.rebuild (package:flutter/src/widgets/framework.dart:3730:5)
I/flutter (18113): #54     StatefulElement.update (package:flutter/src/widgets/framework.dart:4112:5)
I/flutter (18113): #55     Element.updateChild (package:flutter/src/widgets/framework.dart:2885:15)
I/flutter (18113): #56     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:5126:14)
I/flutter (18113): #57     Element.updateChild (package:flutter/src/widgets/framework.dart:2885:15)
I/flutter (18113): #58     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3953:16)
I/flutter (18113): #59     Element.rebuild (package:flutter/src/widgets/framework.dart:3730:5)
I/flutter (18113): #60     ProxyElement.update (package:flutter/src/widgets/framework.dart:4246:5)
I/flutter (18113): #61     _InheritedNotifierElement.update (package:flutter/src/widgets/inherited_notifier.dart:94:11)
I/flutter (18113): #62     Element.updateChild (package:flutter/src/widgets/framework.dart:2885:15)
I/flutter (18113): #63     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:5126:14)
I/flutter (18113): #64     Element.updateChild (package:flutter/src/widgets/framework.dart:2885:15)
I/flutter (18113): #65     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3953:16)
I/flutter (18113): #66     Element.rebuild (package:flutter/src/widgets/framework.dart:3730:5)
I/flutter (18113): #67     StatefulElement.update (package:flutter/src/widgets/framework.dart:4112:5)
I/flutter (18113): #68     Element.updateChild (package:flutter/src/widgets/framework.dart:2885:15)
I/flutter (18113): #69     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3953:16)
I/flutter (18113): #70     Element.rebuild (package:flutter/src/widgets/framework.dart:3730:5)
I/flutter (18113): #71     StatelessElement.update (package:flutter/src/widgets/framework.dart:4008:5)
I/flutter (18113): #72     Element.updateChild (package:flutter/src/widgets/framework.dart:2885:15)
I/flutter (18113): #73     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:5126:14)
I/flutter (18113): #74     Element.updateChild (package:flutter/src/widgets/framework.dart:2885:15)
I/flutter (18113): #75     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3953:16)
I/flutter (18113): #76     Element.rebuild (package:flutter/src/widgets/framework.dart:3730:5)
I/flutter (18113): #77     ProxyElement.update (package:flutter/src/widgets/framework.dart:4246:5)
I/flutter (18113): #78     Element.updateChild (package:flutter/src/widgets/framework.dart:2885:15)
I/flutter (18113): #79     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3953:16)
I/flutter (18113): #80     Element.rebuild (package:flutter/src/widgets/framework.dart:3730:5)
I/flutter (18113): #81     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2340:33)
I/flutter (18113): #82     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding&WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:701:20)
I/flutter (18113): #83     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:285:5)
I/flutter (18113): #84     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1033:15)
I/flutter (18113): #85     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:975:9)
I/flutter (18113): #86     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.scheduleWarmUpFrame.<anonymous closure> (package:flutter/src/scheduler/binding.dart:784:7)
I/flutter (18113): #88     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:382:19)
I/flutter (18113): #89     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:416:5)
I/flutter (18113): #90     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:12)
I/flutter (18113): (elided one frame from package dart:async-patch)
I/flutter (18113): 
I/flutter (18113): ════════════════════════════════════════════════════════════════════════════════════════════════════
Reloaded 5 of 496 libraries in 1,206ms.
I/d.meeting_make(18113): Background concurrent copying GC freed 30707(1646KB) AllocSpace objects, 5(228KB) LOS objects, 49% free, 1951KB/3MB, paused 6.770ms total 79.661ms
I/flutter (18113): Another exception was thrown: Assertion failed
```

And this in my app: 
![image](https://user-images.githubusercontent.com/7407478/63212134-a72aa600-c108-11e9-933e-8d1820f602c3.png)

This is ONLY produced when I do the following in a Column widget:

```dart
if (_whitelists.containsKey(date))
  Column(
    children: <Widget>[
      Text(
          "Can attend during these times:"),
    ]..addAll(_whitelists[date]
          .map((timeOfDay) {
        Text(timeOfDay.toString());
      }).toList()),
  ),
```
When changing the <Widget>[] list with ..addAll, it throws an Assertion Failed error and I'm unsure why. What's the best way of fixing this? What is the alternative for a dynamic list like this?

**Comment by SwissCheese5** [comment]
Fixed.

```dart
if (_whitelists.containsKey(date))
  Column(
    children: <Widget>[
      Text(
          "Can attend during these times:"),
    ]..addAll(
        _whitelists[date]
            .map((timeOfDay) => Text(
                timeOfDay.toString()))
            .toList(),
      ),
  ),
```
it was the lack of a => and the usage of { } that caused the problem.
