### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by naxiemolv** [flutter/flutter#38747]
## Steps to Reproduce

1. ...item.current ? _showCurrent() : Container(),  OK
2. ...item.current ? _showCurrent() : null,  BUG
3. ...

## Logs

```
flutter: ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
flutter: The following assertion was thrown building:
flutter: Assertion failed
flutter:
flutter: Either the assertion indicates an error in the framework itself, or we should provide substantially
flutter: more information in this error message to help you determine and fix the underlying cause.
flutter: In either case, please report this assertion by filing a bug on GitHub:
flutter:   https://github.com/flutter/flutter/issues/new?template=BUG.md
flutter:
flutter: When the exception was thrown, this was the stack:
flutter: #0      new MultiChildRenderObjectWidget.<anonymous closure> (package:flutter/src/widgets/framework.dart:1691:11)
flutter: #1      new MultiChildRenderObjectWidget (package:flutter/src/widgets/framework.dart:1696:8)
flutter: #2      new Flex (package:flutter/src/widgets/basic.dart:3707:8)
flutter: #3      new Row (package:flutter/src/widgets/basic.dart:4038:8)
flutter: #4      _ResultRecordBodyState._buildCell (package:ear_magic/views/more/result_record.dart:117:11)
flutter: #5      _ResultRecordBodyState.build.<anonymous closure> (package:ear_magic/views/more/result_record.dart:77:18)
flutter: #6      SliverChildBuilderDelegate.build (package:flutter/src/widgets/sliver.dart:442:15)
flutter: #7      SliverMultiBoxAdaptorElement._build.<anonymous closure> (package:flutter/src/widgets/sliver.dart:1153:67)
flutter: #8      _HashMap.putIfAbsent (dart:collection-patch/collection_patch.dart:137:29)
flutter: #9      SliverMultiBoxAdaptorElement._build (package:flutter/src/widgets/sliver.dart:1153:26)
flutter: #10     SliverMultiBoxAdaptorElement.createChild.<anonymous closure> (package:flutter/src/widgets/sliver.dart:1166:55)
flutter: #11     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2320:19)
flutter: #12     SliverMultiBoxAdaptorElement.createChild (package:flutter/src/widgets/sliver.dart:1159:11)
flutter: #13     RenderSliverMultiBoxAdaptor._createOrObtainChild.<anonymous closure> (package:flutter/src/rendering/sliver_multi_box_adaptor.dart:354:23)
flutter: #14     RenderObject.invokeLayoutCallback.<anonymous closure> (package:flutter/src/rendering/object.dart:1715:58)
flutter: #15     PipelineOwner._enableMutationsToDirtySubtrees (package:flutter/src/rendering/object.dart:796:15)
flutter: #16     RenderObject.invokeLayoutCallback (package:flutter/src/rendering/object.dart:1715:13)
flutter: #17     RenderSliverMultiBoxAdaptor._createOrObtainChild (package:flutter/src/rendering/sliver_multi_box_adaptor.dart:343:5)
flutter: #18     RenderSliverMultiBoxAdaptor.insertAndLayoutChild (package:flutter/src/rendering/sliver_multi_box_adaptor.dart:489:5)
flutter: #19     RenderSliverList.performLayout.advance (package:flutter/src/rendering/sliver_list.dart:191:19)
flutter: #20     RenderSliverList.performLayout (package:flutter/src/rendering/sliver_list.dart:234:19)
flutter: #21     RenderObject.layout (package:flutter/src/rendering/object.dart:1619:7)
flutter: #22     RenderSliverPadding.performLayout (package:flutter/src/rendering/sliver_padding.dart:181:11)
flutter: #23     RenderObject.layout (package:flutter/src/rendering/object.dart:1619:7)
flutter: #24     RenderViewportBase.layoutChildSequence (package:flutter/src/rendering/viewport.dart:406:13)
flutter: #25     RenderViewport._attemptLayout (package:flutter/src/rendering/viewport.dart:1334:12)
flutter: #26     RenderViewport.performLayout (package:flutter/src/rendering/viewport.dart:1252:20)
flutter: #27     RenderObject._layoutWithoutResize (package:flutter/src/rendering/object.dart:1496:7)
flutter: #28     PipelineOwner.flushLayout (package:flutter/src/rendering/object.dart:765:18)
flutter: #29     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding.drawFrame (package:flutter/src/rendering/binding.dart:346:19)
flutter: #30     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding&WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:701:13)
flutter: #31     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:285:5)
flutter: #32     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1016:15)
flutter: #33     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:958:9)
flutter: #34     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:874:5)
flutter: #38     _invoke (dart:ui/hooks.dart:236:10)
flutter: #39     _drawFrame (dart:ui/hooks.dart:194:3)
flutter: (elided 3 frames from package dart:async)
flutter: ════════════════════════════════════════════════════════════════════════════════════════════════════
```

```
```

```
[✓] Flutter (Channel stable, v1.7.8+hotfix.4, on Mac OS X 10.14.5 18F132, locale
    zh-Hans-CN)
    • Flutter version 1.7.8+hotfix.4 at /Users/liyuyang/development/flutter
    • Framework revision 20e59316b8 (4 weeks ago), 2019-07-18 20:04:33 -0700
    • Engine revision fee001c93f
    • Dart version 2.4.0

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.0)
    • Android SDK at /Users/liyuyang/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling
      support)
    • Platform android-29, build-tools 29.0.0
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_152-release-1343-b01)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 10.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.2.1, Build version 10E1001
    • CocoaPods version 1.7.5

[✓] iOS tools - develop for iOS devices
    • ios-deploy 1.9.4

[!] Android Studio (version 3.4)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build
      1.8.0_152-release-1343-b01)

[✓] IntelliJ IDEA Ultimate Edition (version 2019.1.3)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 36.2.1
    • Dart plugin version 191.7830

[✓] VS Code (version 1.36.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.3.0

[✓] Connected device (2 available)
    • iPhoneX Tao • 6866ce9ec68a66bc2fc70e8a2d1324eeee8d8167 • ios • iOS 12.4
    • iPhone 8    • EDED4E00-E0CF-4924-8431-BC2EF07355D7     • ios •
      com.apple.CoreSimulator.SimRuntime.iOS-12-2 (simulator)
```

**Comment by shihaohong** [comment]
Could you please share more details or a minimal reproducible sample app? There isn't much we can do to look into this otherwise.

**Comment by iapicca** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact descriptions what happens, logs and the output of ' flutter doctor -v'  please.
All system setups can be slightly different so its always better to open new issues and reference related issues.
