### ISSUE TITLE
Can't run flutter on android

### ISSUE THREAD

**Issue by riobijanero** [flutter/flutter#38792]
Hello, 
i cannot run my flutter app on android 
can somebody please help me with this?

```flutter run -t lib/main_dev.dart --verbose     ```
I get

```
                                                                                                                    1 ↵  23  12:04:00
[  +33 ms] executing: [/Users/b.sellahi/Desktop/flutter-workspace/flutter/] git log -n 1 --pretty=format:%H
[  +45 ms] Exit code 0 from: git log -n 1 --pretty=format:%H
[        ] bc7bc940836f1f834699625426795fd6f07c18ec
[        ] executing: [/Users/b.sellahi/Desktop/flutter-workspace/flutter/] git describe --match v*.*.* --first-parent --long --tags
[  +35 ms] Exit code 0 from: git describe --match v*.*.* --first-parent --long --tags
[        ] v1.6.3-0-gbc7bc9408
[  +10 ms] executing: [/Users/b.sellahi/Desktop/flutter-workspace/flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[  +10 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/beta
[        ] executing: [/Users/b.sellahi/Desktop/flutter-workspace/flutter/] git ls-remote --get-url origin
[   +8 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[  +49 ms] executing: [/Users/b.sellahi/Desktop/flutter-workspace/flutter/] git rev-parse --abbrev-ref HEAD
[  +16 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] beta
[ +324 ms] executing: /Users/b.sellahi/Library/Android/sdk/platform-tools/adb devices -l
[  +10 ms] Exit code 0 from: /Users/b.sellahi/Library/Android/sdk/platform-tools/adb devices -l
[        ] List of devices attached
           emulator-5554          device product:sdk_gphone_x86 model:Android_SDK_built_for_x86 device:generic_x86 transport_id:2
[   +7 ms] executing: idevice_id -h
[  +32 ms] /usr/bin/xcrun simctl list --json devices
[ +236 ms] More than one device connected; please specify a device with the '-d <deviceId>' flag, or use '-d all' to act on all devices.
[   +3 ms] /Users/b.sellahi/Library/Android/sdk/platform-tools/adb -s emulator-5554 shell getprop
[  +33 ms] ro.hardware = ranchu
[   +4 ms] Android SDK built for x86 • emulator-5554                        • android-x86 • Android 10 (API 29) (emulator)
[        ] iPhone Xs                 • D841AE69-DB5B-402C-85C0-6E4C1874B2EE • ios         • com.apple.CoreSimulator.SimRuntime.iOS-12-2 (simulator)
[  +10 ms] "flutter run" took 677ms.
[        ] "flutter run" took 677ms.
```

```
#0      throwToolExit (package:flutter_tools/src/base/common.dart:24:3)
#1      RunCommand.validateCommand (package:flutter_tools/src/commands/run.dart:257:7)
<asynchronous suspension>
#2      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:467:11)
<asynchronous suspension>
#3      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:424:33)
<asynchronous suspension>
#4      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:29)
<asynchronous suspension>
#5      _rootRun (dart:async/zone.dart:1124:13)
#6      _CustomZone.run (dart:async/zone.dart:1021:19)
#7      _runZoned (dart:async/zone.dart:1516:10)
#8      runZoned (dart:async/zone.dart:1463:12)
#9      AppContext.run (package:flutter_tools/src/base/context.dart:152:18)
<asynchronous suspension>
#10     FlutterCommand.run (package:flutter_tools/src/runner/flutter_command.dart:415:20)
#11     CommandRunner.runCommand (package:args/command_runner.dart:196:27)
<asynchronous suspension>
#12     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:396:21)
<asynchronous suspension>
#13     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:29)
<asynchronous suspension>
#14     _rootRun (dart:async/zone.dart:1124:13)
#15     _CustomZone.run (dart:async/zone.dart:1021:19)
#16     _runZoned (dart:async/zone.dart:1516:10)
#17     runZoned (dart:async/zone.dart:1463:12)
#18     AppContext.run (package:flutter_tools/src/base/context.dart:152:18)
<asynchronous suspension>
#19     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:356:19)
<asynchronous suspension>
#20     CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:111:29)
#21     new Future.sync (dart:async/future.dart:224:31)
#22     CommandRunner.run (package:args/command_runner.dart:111:11)
#23     FlutterCommandRunner.run (package:flutter_tools/src/runner/flutter_command_runner.dart:242:18)
#24     run.<anonymous closure> (package:flutter_tools/runner.dart:60:20)
<asynchronous suspension>
#25     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:29)
<asynchronous suspension>
#26     _rootRun (dart:async/zone.dart:1124:13)
#27     _CustomZone.run (dart:async/zone.dart:1021:19)
#28     _runZoned (dart:async/zone.dart:1516:10)
#29     runZoned (dart:async/zone.dart:1463:12)
#30     AppContext.run (package:flutter_tools/src/base/context.dart:152:18)
<asynchronous suspension>
#31     runInContext (package:flutter_tools/src/context_runner.dart:51:24)
<asynchronous suspension>
#32     run (package:flutter_tools/runner.dart:51:10)
#33     main (package:flutter_tools/executable.dart:59:9)
<asynchronous suspension>
#34     main (file:///Users/b.sellahi/Desktop/flutter-workspace/flutter/packages/flutter_tools/bin/flutter_tools.dart:8:3)
#35     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:298:32)
#36     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:171:12)
```

```
[✓] Flutter (Channel beta, v1.6.3, on Mac OS X 10.14.5 18F132, locale de-DE)

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[✓] iOS toolchain - develop for iOS devices (Xcode 10.2.1)
[✓] Android Studio (version 3.4)
[✓] VS Code (version 1.37.0)
[✓] Connected device (2 available)

• No issues found!
```

**Comment by jld3103** [comment]
You have to many devices connected.
To get a devices list run ```flutter devices``` and insert the value of the 2nd column of the device you want to run the app on into this command: ```flutter run -d ID``` and replace ID with the value.

**Comment by BondarenkoStas** [comment]
@riobijanero, I think it's safe to close the issue. 
```More than one device connected; please specify a device with the '-d <deviceId>' flag, or use '-d all' to act on all devices.```
was mentioned in the log you posted.
I hope @jld3103 comment helped you to solve the issue. Anyway, feel free to open a new one to comment this one so I can reopen it.
