### ISSUE TITLE
When you press multiple buttons using a mouse on Chromebook and release outside of the window, the app does not fire Up events and crashes

### ISSUE THREAD

**Issue by dkwingsmt** [flutter/flutter#38852]
## Description
- Run flutter_gallery on a Chromebook, use a mouse
- Press both buttons and hold
- Drag out of the window
- Release one of the buttons (or both buttons)
- Move back into the window 
- App crashes

On the other hand, if you do the same thing but only presses only one button at the 2nd step, then it doesn't crash

## Investigation
This is the assertion that caused the crash:
```
E/flutter ( 3522): [ERROR:flutter/lib/ui/ui_dart_state.cc(148)] Unhandled Exception: 'package:flutter/src/gestures/converter.dart': Failed assertion: line 134 pos 20: '!state.down': is not true.
E/flutter ( 3522): #0      _AssertionError._doThrowNew (dart:core-patch/errors_patch.dart:40:39)
E/flutter ( 3522): #1      _AssertionError._throwNew (dart:core-patch/errors_patch.dart:36:5)
E/flutter ( 3522): #2      PointerEventConverter.expand (package:flutter/src/gestures/converter.dart:134:20)
E/flutter ( 3522): #3      _SyncIterator.moveNext (dart:core-patch/core_patch.dart:144:12)
E/flutter ( 3522): #4      ListQueue.addAll (dart:collection/queue.dart:655:25)
E/flutter ( 3522): #5      GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:84:27)
E/flutter ( 3522): #6      _rootRunUnary (dart:async/zone.dart:1136:13)
E/flutter ( 3522): #7      _CustomZone.runUnary (dart:async/zone.dart:1029:19)
E/flutter ( 3522): #8      _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
E/flutter ( 3522): #9      _invoke1 (dart:ui/hooks.dart:263:10)
E/flutter ( 3522): #10     _dispatchPointerDataPacket (dart:ui/hooks.dart:172:5)
```

This is the log when pressing two buttons:
```
I/System.out( 3604): onGenericMotionEvent: Change 3 buttons 0
I/System.out( 3604): onTouchEvent: Change 4 buttons 2
// When presseing the second button then drag
I/System.out( 3604): onTouchEvent: Change 5 buttons 3
// When releasing one of the buttons
I/System.out( 3604): onTouchEvent: Change 5 buttons 2
// When move back into the window
I/System.out( 3604): onGenericMotionEvent: Change 3 buttons 0
```

On the contrary, this is the log when pressing one button:
```
I/System.out( 3604): onGenericMotionEvent: Change 3 buttons 0          
I/System.out( 3604): onTouchEvent: Change 5 buttons 2
// When releasing the button
I/System.out( 3604): onTouchEvent: Change 6 buttons 0  
```

**Comment by dkwingsmt** [comment]
+cc @stuartmorgan

**Comment by stuartmorgan** [comment]
> Should we patch it in the engine or in the framework?

Platform-specific issues in the event stream should be treated as platform bugs, and fixed up at the platform (engine) level. Different platforms have different behaviors around edge cases like these ([macOS example](https://github.com/flutter/engine/blob/c3e9c14586566ae1afc28c560176e74f0af65c29/shell/platform/darwin/macos/framework/Source/FlutterViewController.mm#L39)), and handling them all in the framework would be a giant mess.

**Comment by dkwingsmt** [comment]
@stuartmorgan Yeah. But it really depends on how we define the behavior. We already have a lot of code that handles irregular cases like this, majorly in `converter.dart`, such as "if we receive an Up event without an Add then synthesize an Add first". Some of them those cases might actually server only one platform. So it's not that unreasonable to make just another case that "if we receive an Hover event without an Up then synthesize an Up first".

**Comment by stuartmorgan** [comment]
> We already have a lot of code that handles irregular cases like this, majorly in `converter.dart`

Yes, that code is already complicated, and that's the result of handling just the irregularities from two platforms (and only their touch input, which is relatively simple in its possible flows). Consider what that code will look like if we continue that approach to ~7 platforms, and include all the added complexities of mouse support on most of them.

**Comment by dkwingsmt** [comment]
@stuartmorgan In that case the logic will be
> If a device that has dispatched Down tries to dispatch a Hover without an Up, insert an Up.
which I believe will need to add states to `AndroidTouchProcessor`. Is it ok?

**Comment by stuartmorgan** [comment]
I don't know enough about the exact details of the event stream on Android to be able to advise on what the best fix is. On macOS, I was able to do specific targeted things for drag-in and drag-out edge cases by tracking state and observing the enter and exit events as well. Whether you could do something targeted like that here, rather than a very broad catch-all like you are suggesting, I don't know.

In general, more specific fixes are better because they are less likely to have unintended side-effects, but that may or may not be possible for this case in Android.

**Comment by pedromassangocode** [comment]
Is this still a valid issue?

**Comment by dkwingsmt** [comment]
Probably not. I haven't fixed it yet and I don't think anyone else has touched this part of code.
