### ISSUE TITLE
Format Exception Bad UTF-8 encoding when testing for ios

### ISSUE THREAD

**Issue by markrocks** [flutter/flutter#38910]
## command
```
flutter run
```

I have a project that runs fine when I test it on an Android emulator and/or devices ( launched from VS Code).  When I try the "flutter run" command to test on an ios device I get the following error:

## exception
```
FormatException: FormatException: Bad UTF-8 encoding 0xa5 (at offset 194)
```

```
#0      _Utf8Decoder.convert (dart:convert/utf.dart:530:13)
#1      _Utf8ConversionSink.addSlice (dart:convert/string_conversion.dart:309:14)
#2      _Utf8ConversionSink.add (dart:convert/string_conversion.dart:305:5)
#3      _ConverterStreamEventSink.add (dart:convert/chunked_conversion.dart:72:18)
#4      _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:120:24)
#5      _rootRunUnary (dart:async/zone.dart:1132:38)
#6      _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#7      _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
#8      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#9      _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#10     _SyncStreamController._sendData (dart:async/stream_controller.dart:764:19)
#11     _StreamController._add (dart:async/stream_controller.dart:640:7)
#12     _StreamController.add (dart:async/stream_controller.dart:586:5)
#13     _Socket._onData (dart:io-patch/socket_patch.dart:1786:41)
#14     _rootRunUnary (dart:async/zone.dart:1136:13)
#15     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#16     _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
#17     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#18     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#19     _SyncStreamController._sendData (dart:async/stream_controller.dart:764:19)
#20     _StreamController._add (dart:async/stream_controller.dart:640:7)
#21     _StreamController.add (dart:async/stream_controller.dart:586:5)
#22     new _RawSocket.<anonymous closure> (dart:io-patch/socket_patch.dart:1335:33)
#23     _NativeSocket.issueReadEvent.issue (dart:io-patch/socket_patch.dart:856:14)
#24     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#25     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#26     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:116:13)
#27     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:173:5)
```

## flutter doctor

```
[32m[✓][39m Flutter (Channel stable, v1.7.8+hotfix.4, on Mac OS X 10.14.4 18E226, locale en-US)
    [32m•[39m Flutter version 1.7.8+hotfix.4 at /Users/markmartin/Workspace/Development/Experiments/flutter
    [32m•[39m Framework revision 20e59316b8 (5 weeks ago), 2019-07-18 20:04:33 -0700
    [32m•[39m Engine revision fee001c93f
    [32m•[39m Dart version 2.4.0

[32m[✓][39m Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    [32m•[39m Android SDK at /Users/markmartin/Library/Android/sdk
    [32m•[39m Android NDK location not configured (optional; useful for native profiling support)
    [32m•[39m Platform android-28, build-tools 28.0.3
    [32m•[39m Java binary at: /Users/markmartin/Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    [32m•[39m Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)
    [32m•[39m All Android licenses accepted.

[32m[✓][39m Xcode - develop for iOS and macOS (Xcode 10.3)
    [32m•[39m Xcode at /Applications/Xcode.app/Contents/Developer
    [32m•[39m Xcode 10.3, Build version 10G8
    [32m•[39m CocoaPods version 1.7.5

[32m[✓][39m iOS tools - develop for iOS devices
    [32m•[39m ios-deploy 1.9.4

[32m[✓][39m Android Studio (version 3.3)
    [32m•[39m Android Studio at /Users/markmartin/Applications/Android Studio.app/Contents
    [32m•[39m Flutter plugin version 33.0.1
    [32m•[39m Dart plugin version 182.5215
    [32m•[39m Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)

[32m[✓][39m VS Code (version 1.37.1)
    [32m•[39m VS Code at /Users/markmartin/Applications/Visual Studio Code.app/Contents
    [32m•[39m Flutter extension version 3.3.0

[32m[✓][39m Connected device (1 available)
    [32m•[39m iPhone X • C3A49B52-4EB7-48AD-8E27-F3E8C7D5DB98 • ios • com.apple.CoreSimulator.SimRuntime.iOS-12-4 (simulator)

[32m•[39m No issues found!
```

**Comment by timsneath** [comment]
Unfortunately there isn't enough information on this bug to reproduce the issue. Closing for now. 

If you are still experiencing this issue, you're welcome to reopen it. Please tell us exactly how to reproduce the problem you're running into. Attach a small sample that demonstrates the issue, or include the specific tool commands that reproduce the problem along with the results of running `flutter doctor -v`. 

Thank you for using Flutter!
