### ISSUE TITLE
webview runs fine when installed via "flutter run --release", but error when installed via google play store

### ISSUE THREAD

**Issue by gisinator** [flutter/flutter#38998]
## Steps to Reproduce

Hello flutter-friends,

I am facing a weird problem: Within my app I call a webview which works perfectly fine when the app is installed via AndroidStudio via "flutter run --release". I make use of "webview_flutter" package 0.3.7:

```dart
Expanded(
  child: WebView(
    initialUrl: 'https://xyz.abc/terms',
    onPageFinished: (result) {
      setState(() {
        _touLoaded = true;
      });
    },
  ),
)
```

When I uploaded my app to google play and tested it in a closed group with invitations, it also worked like a charme and the web-content was displayed perfectly.

Now, I finally submitted it to production mode so that everyone can download the app. Now, when trying to open the webview, I get the following message (when connected to Android Studio):

## Logs

```
[ERROR:flutter/lib/ui/ui_dart_state.cc(148)] Unhandled Exception: PlatformException(error, Attempt to invoke virtual method 'int ja
va.lang.Integer.intValue()' on a null object reference, null)
E/flutter (31498): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:564)
E/flutter (31498): #1      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:316)
E/flutter (31498): <asynchronous suspension>
E/flutter (31498): #2      AndroidViewController._create (package:flutter/src/services/platform_views.dart:639)
E/flutter (31498): <asynchronous suspension>
E/flutter (31498): #3      AndroidViewController.setSize (package:flutter/src/services/platform_views.dart:556)
E/flutter (31498): <asynchronous suspension>
E/flutter (31498): #4      RenderAndroidView._sizePlatformView (package:flutter/src/rendering/platform_view.dart:189)
E/flutter (31498): <asynchronous suspension>
E/flutter (31498): #5      RenderAndroidView.performResize (package:flutter/src/rendering/platform_view.dart:170)
E/flutter (31498): #6      RenderObject.layout (package:flutter/src/rendering/object.dart:1604)
E/flutter (31498): #7      _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy
_box.dart:105)
E/flutter (31498): #8      RenderObject.layout (package:flutter/src/rendering/object.dart:1619)
E/flutter (31498): #9      RenderFlex.performLayout (package:flutter/src/rendering/flex.dart:805)
E/flutter (31498): #10     RenderObject.layout (package:flutter/src/rendering/object.dart:1619)
E/flutter (31498): #11     RenderPadding.performLayout (package:flutter/src/rendering/shifted_box.dart:206)
E/flutter (31498): #12     RenderObject.layout (package:flutter/src/rendering/object.dart:1619)
E/flutter (31498): #13     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy
_box.dart:105)
E/flutter (31498): #14     RenderObject.layout (package:flutter/src/rendering/object.dart:1619)
E/flutter (31498): #15     RenderConstrainedBox.performLayout (package:flutter/src/rendering/proxy_box.dart:259)
E/flutter (31498): #16     RenderObject.layout (package:flutter/src/rendering/object.dart:1619)
E/flutter (31498): #17     RenderPadding.performLayout (package:flutter/src/rendering/shifted_box.dart:206)
E/flutter (31498): #18     RenderObject.layout (package:flutter/src/rendering/object.dart:1619)
E/flutter (31498): #19     RenderStack.performLayout (package:flutter/src/rendering/stack.dart:510)
E/flutter (31498): #20     RenderObject._layoutWithoutResize (package:flutter/src/rendering/object.dart:1496)
E/flutter (31498): #21     PipelineOwner.flushLayout (package:flutter/src/rendering/object.dart:765)
E/flutter (31498): #22     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&Rendere
rBinding.drawFrame (package:flutter/src/rendering/binding.dart:346)
E/flutter (31498): #23     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&Rendere
rBinding&WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:701)
E/flutter (31498): #24     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&Rendere
rBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:285)
E/flutter (31498): #25     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._invokeFrameCallback (package:flutter/sr
c/scheduler/binding.dart:1016)
E/flutter (31498): #26     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.handleDrawFrame (package:flutter/src/sch
eduler/binding.dart:958)
E/flutter (31498): #27     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._handleDrawFrame (package:flutter/src/sc
heduler/binding.dart:874)
E/flutter (31498): #28     _rootRun (dart:async/zone.dart:1124)
E/flutter (31498): #29     _CustomZone.run (dart:async/zone.dart:1021)
E/flutter (31498): #30     _CustomZone.runGuarded (dart:async/zone.dart:923)
E/flutter (31498): #31     _invoke (dart:ui/hooks.dart:236)
E/flutter (31498): #32     _drawFrame (dart:ui/hooks.dart:194)
E/flutter (31498):
```

```
[√] Flutter (Channel stable, v1.7.8+hotfix.3, on Microsoft Windows [Version 10.0.17763.678], locale de-DE)
    • Flutter version 1.7.8+hotfix.3 at C:\flutter
    • Framework revision b712a172f9 (6 weeks ago), 2019-07-09 13:14:38 -0700
    • Engine revision 54ad777fd2
    • Dart version 2.4.0


[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at C:\Users\StudentenEngel\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)
    • All Android licenses accepted.

[√] Android Studio (version 3.5)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 38.2.3
    • Dart plugin version 191.8405
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)

[√] Connected device (1 available)
    • ANE LX1 • 9WV4C18816019837 • android-arm64 • Android 9 (API 28)

• No issues found!
```

**Comment by amirh** [comment]
Unfortunately we're losing the Java stack trace in the error log.
I sent https://github.com/flutter/engine/pull/11361 to include the stack trace.

Can you reproduce the error with that patch (either by building a local engine or waiting for the patch to make it to master). That should give us a better insight of what's going on.

**Comment by gisinator** [comment]
Thank you, sir.
I'm afraid I have to wait for the patch to make it to master. I'll update once I have the full stack strace.

**Comment by gisinator** [comment]
Problem solved!

I rebuilt the appbundle one more time, uploaded it, and after google review process it just got published as an update. Downloaded the new version and it works like a charme.

There was no change in code, so I'm afraid there must have been an error while building the appbundle last time. Weird, since I wouldnt have uploaded it if I had gotten notice of any errors. 

But that seems to be the only possibility I can think of. Anyway, most important thing: It works :)

Thanks to Amirh and colleagues for putting time and efforts looking into this!
