### ISSUE TITLE
Unable to run 'flutter build apk'

### ISSUE THREAD

**Issue by qchong** [flutter/flutter#3907]
## Steps to Reproduce

I'm using the 'master' branch. 

Ran these commands:
$ flutter create demoApp
$ cd demoApp
$ flutter build apk

## Flutter Doctor

Paste the output of running `flutter doctor` here.

[✓] Flutter (on Linux, channel master)
    • Flutter at /usr/local/google/home/quddusc/flutter
    • Framework revision 2f642ce908 (85 minutes ago), engine revision 57edc534d6

[✓] Android toolchain - develop for Android devices (Android SDK 24.0.0-preview)
    • Android SDK at /usr/local/google/home/quddusc/Android/Sdk
    • Platform android-N, build-tools 24.0.0-preview
    • OpenJDK Runtime Environment (IcedTea 2.6.6) (7u101-2.6.6-0ubuntu0.14.04.1)

[✓] Atom - a lightweight development environment for Flutter
    • Atom installed; Flutter plugin version 0.2.2

## Logs and Crash Reports

Please attach any relevent logs or crash reports.

Building APK in debug mode (android-arm)...
Exception in thread "main" java.lang.UnsupportedClassVersionError: com/android/dx/command/Main : Unsupported major.minor version 52.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:803)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:449)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:71)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
	at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:482)

Oops; flutter has exited unexpectedly: "Exit code 1 from: /usr/local/google/home/quddusc/Android/Sdk/build-tools/24.0.0-preview/dx --dex --force-jumbo --output /tmp/flutter_toolsb75eKg/classes.dex /usr/local/google/home/quddusc/flutter/bin/cache/artifacts/engine/android-arm/classes.dex.jar".

**Comment by devoncarew** [comment]
We may need to compile the class files so they're compatible with older JDKs.

**Comment by jason-simmons** [comment]
You must install the Java 8 JDK on your host in order to run the Android N development tools:
    http://developer.android.com/preview/setup-sdk.html

**Comment by eseidelGoogle** [comment]
We have an old bug about not supporting OpenJDK: https://github.com/flutter/flutter/issues/74

**Comment by qchong** [comment]
Closing as a duplicate.
