### ISSUE TITLE
CupertinoNavigationBar's back button does not work when transitionBetweenRoutes is set to true

### ISSUE THREAD

**Issue by pakyo-pan** [flutter/flutter#39095]
## Steps to Reproduce

1. Use the code below and `flutter run`
2. Press the button and push to `page two`
3. Press and hold the back button, then move your finger up, then press the back button, the back button does not work.

![57A3E3A7A927DFAE79406AC59B160CAA](https://user-images.githubusercontent.com/13342613/63564935-a62ac600-c599-11e9-988e-6430ce78e213.gif)

```dart
import 'package:flutter/material.dart';
import 'package:flutter/cupertino.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      debugShowCheckedModeBanner: false,
      home: PageOne(),
    );
  }
}

// page one
class PageOne extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return CupertinoPageScaffold(
      navigationBar: CupertinoNavigationBar(
        middle: Text('page one'),
      ),
      child: SafeArea(
        child: Center(
          child: CupertinoButton(
            onPressed: () {
              Navigator.push(
                context,
                CupertinoPageRoute(builder: (context) => PageTwo()),
              );
            },
            child: Text('go to PageTwo'),
          ),
        ),
      ),
    );
  }
}

// page two
class PageTwo extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return CupertinoPageScaffold(
      navigationBar: CupertinoNavigationBar(
        middle: Text('page two'),
      ),
      child: Container(),
    );
  }
}
```

## Logs

```
flutter: ══╡ EXCEPTION CAUGHT BY GESTURE ╞═══════════════════════════════════════════════════════════════════
flutter: The following assertion was thrown while handling a gesture:
flutter: 'package:flutter/src/widgets/heroes.dart': Failed assertion: line 634 pos 14: 'manifest.fromHero !=
flutter: newManifest.fromHero': is not true.
flutter:
flutter: Either the assertion indicates an error in the framework itself, or we should provide substantially
flutter: more information in this error message to help you determine and fix the underlying cause.
flutter: In either case, please report this assertion by filing a bug on GitHub:
flutter:   https://github.com/flutter/flutter/issues/new?template=BUG.md
flutter:
flutter: When the exception was thrown, this was the stack:
flutter: #2      _HeroFlight.divert (package:flutter/src/widgets/heroes.dart:634:14)
flutter: #3      HeroController._startHeroTransition (package:flutter/src/widgets/heroes.dart:824:25)
flutter: #4      HeroController._maybeStartHeroTransition (package:flutter/src/widgets/heroes.dart:761:9)
flutter: #5      HeroController.didStartUserGesture (package:flutter/src/widgets/heroes.dart:727:5)
flutter: #6      NavigatorState.didStartUserGesture (package:flutter/src/widgets/navigator.dart:2202:18)
flutter: #7      new _CupertinoBackGestureController (package:flutter/src/cupertino/route.dart:593:15)
flutter: #8      CupertinoPageRoute._startPopGesture (package:flutter/src/cupertino/route.dart:273:12)
flutter: #9      CupertinoPageRoute.buildPageTransitions.<anonymous closure> (package:flutter/src/cupertino/route.dart:317:36)
flutter: #10     _CupertinoBackGestureDetectorState._handleDragStart (package:flutter/src/cupertino/route.dart:505:37)
flutter: #11     DragGestureRecognizer._checkStart.<anonymous closure> (package:flutter/src/gestures/monodrag.dart:370:45)
flutter: #12     GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:182:24)
flutter: #13     DragGestureRecognizer._checkStart (package:flutter/src/gestures/monodrag.dart:370:7)
flutter: #14     DragGestureRecognizer.acceptGesture (package:flutter/src/gestures/monodrag.dart:304:7)
flutter: #15     GestureArenaManager._resolveByDefault (package:flutter/src/gestures/arena.dart:250:25)
flutter: #16     GestureArenaManager._tryToResolveArena.<anonymous closure> (package:flutter/src/gestures/arena.dart:231:31)
flutter: (elided 12 frames from class _AssertionError and package dart:async)
flutter:
flutter: Handler: "onStart"
flutter: Recognizer:
flutter:   HorizontalDragGestureRecognizer#a79c6
flutter: ════════════════════════════════════════════════════════════════════════════════════════════════════
flutter: Another exception was thrown: 'package:flutter/src/cupertino/route.dart': Failed assertion: line 516 pos 12: '_backGestureController != null': is not true.
```

```
[✓] Flutter (Channel dev, v1.9.3, on Mac OS X 10.13.6 17G8030, locale zh-Hans-CN)
    • Flutter version 1.9.3 at /Users/pakyo/Work/_sdk/flutter
    • Framework revision f515bf6abc (2 days ago), 2019-08-20 18:50:09 -0700
    • Engine revision c43739ba53
    • Dart version 2.5.0

 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/pakyo/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 28.0.3
    • ANDROID_HOME = /Users/pakyo/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 10.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.1, Build version 10B61
    • CocoaPods version 1.7.4

[✓] Android Studio (version 3.4)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 36.1.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

[✓] VS Code (version 1.37.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.3.0

[✓] Connected device (1 available)
    • iPhone 6s • 1EDF50E6-E957-4B69-807B-F98B9357E571 • ios • iOS 12.1 (simulator)

• No issues found!
```

**Comment by LongCatIsLooong** [comment]
Looks like a dup of https://github.com/flutter/flutter/issues/38183. Closing.

**Comment by sarimk80** [comment]
A widget is either stateful or stateless. If a widget can change—when a user interacts with it, for example—it’s stateful.

A stateless widget never changes. Icon, IconButton, and Text are examples of stateless widgets. Stateless widgets subclass StatelessWidget.

A stateful widget is dynamic: for example, it can change its appearance in response to events triggered by user interactions or when it receives data. Checkbox, Radio, Slider, InkWell, Form, and TextField are examples of stateful widgets. Stateful widgets subclass StatefulWidget.

//*****************************************************************
your class PageOne and PageTwo should extend stateful widget
//*****************************************************************
