### ISSUE TITLE
EXCEPTION CAUGHT BY WIDGETS LIBRARY 

### ISSUE THREAD

**Issue by mmzuo** [flutter/flutter#39107]
```
 ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
I/flutter ( 8169): The following assertion was thrown building:
I/flutter ( 8169): Assertion failed
I/flutter ( 8169):
I/flutter ( 8169): Either the assertion indicates an error in the framework itself, or we should provide substantially
I/flutter ( 8169): more information in this error message to help you determine and fix the underlying cause.
I/flutter ( 8169): In either case, please report this assertion by filing a bug on GitHub:
I/flutter ( 8169):   https://github.com/flutter/flutter/issues/new?template=BUG.md
I/flutter ( 8169):
I/flutter ( 8169): When the exception was thrown, this was the stack:
I/flutter ( 8169): #0      new MultiChildRenderObjectWidget.<anonymous closure> (package:flutter/src/widgets/framework.dart:1691:11)
I/flutter ( 8169): #1      new MultiChildRenderObjectWidget (package:flutter/src/widgets/framework.dart:1696:8)
I/flutter ( 8169): #2      new Flex (package:flutter/src/widgets/basic.dart:3707:8)
I/flutter ( 8169): #3      new Column (package:flutter/src/widgets/basic.dart:4234:8)
I/flutter ( 8169): #4      ContactState.build.<anonymous closure> (package:flutterdemo/contacts/contact_sider_list.dart:72:26)
I/flutter ( 8169): #5      SliverChildBuilderDelegate.build (package:flutter/src/widgets/sliver.dart:442:15)
I/flutter ( 8169): #6      SliverMultiBoxAdaptorElement._build.<anonymous closure> (package:flutter/src/widgets/sliver.dart:1153:67)
I/flutter ( 8169): #7      _HashMap.putIfAbsent (dart:collection-patch/collection_patch.dart:137:29)
I/flutter ( 8169): #8      SliverMultiBoxAdaptorElement._build (package:flutter/src/widgets/sliver.dart:1153:26)
I/flutter ( 8169): #9      SliverMultiBoxAdaptorElement.createChild.<anonymous closure> (package:flutter/src/widgets/sliver.dart:1166:55)
I/flutter ( 8169): #10     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2320:19)
I/flutter ( 8169): #11     SliverMultiBoxAdaptorElement.createChild (package:flutter/src/widgets/sliver.dart:1159:11)
I/flutter ( 8169): #12     RenderSliverMultiBoxAdaptor._createOrObtainChild.<anonymous closure> (package:flutter/src/rendering/sliver_multi_box_adaptor.dart:354:23)
I/flutter ( 8169): #13     RenderObject.invokeLayoutCallback.<anonymous closure> (package:flutter/src/rendering/object.dart:1715:58)
I/flutter ( 8169): #14     PipelineOwner._enableMutationsToDirtySubtrees (package:flutter/src/rendering/object.dart:796:15)
I/flutter ( 8169): #15     RenderObject.invokeLayoutCallback (package:flutter/src/rendering/object.dart:1715:13)
I/flutter ( 8169): #16     RenderSliverMultiBoxAdaptor._createOrObtainChild (package:flutter/src/rendering/sliver_multi_box_adaptor.dart:343:5)
I/flutter ( 8169): #17     RenderSliverMultiBoxAdaptor.insertAndLayoutChild (package:flutter/src/rendering/sliver_multi_box_adaptor.dart:489:5)
I/flutter ( 8169): #18     RenderSliverList.performLayout.advance (package:flutter/src/rendering/sliver_list.dart:191:19)
I/flutter ( 8169): #19     RenderSliverList.performLayout (package:flutter/src/rendering/sliver_list.dart:234:19)
I/flutter ( 8169): #20     RenderObject.layout (package:flutter/src/rendering/object.dart:1619:7)
I/flutter ( 8169): #21     RenderSliverPadding.performLayout (package:flutter/src/rendering/sliver_padding.dart:181:11)
I/flutter ( 8169): #22     RenderObject.layout (package:flutter/src/rendering/object.dart:1619:7)
I/flutter ( 8169): #23     RenderViewportBase.layoutChildSequence (package:flutter/src/rendering/viewport.dart:406:13)
I/flutter ( 8169): #24     RenderViewport._attemptLayout (package:flutter/src/rendering/viewport.dart:1334:12)
I/flutter ( 8169): #25     RenderViewport.performLayout (package:flutter/src/rendering/viewport.dart:1252:20)
I/flutter ( 8169): #26     RenderObject.layout (package:flutter/src/rendering/object.dart:1619:7)
I/flutter ( 8169): #27     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter ( 8169): #28     RenderObject.layout (package:flutter/src/rendering/object.dart:1619:7)
I/flutter ( 8169): #29     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter ( 8169): #30     RenderObject.layout (package:flutter/src/rendering/object.dart:1619:7)
I/flutter ( 8169): #31     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter ( 8169): #32     RenderObject.layout (package:flutter/src/rendering/object.dart:1619:7)
I/flutter ( 8169): #33     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter ( 8169): #34     RenderObject.layout (package:flutter/src/rendering/object.dart:1619:7)
I/flutter ( 8169): #35     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter ( 8169): #36     RenderObject.layout (package:flutter/src/rendering/object.dart:1619:7)
I/flutter ( 8169): #37     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter ( 8169): #38     RenderObject.layout (package:flutter/src/rendering/object.dart:1619:7)
I/flutter ( 8169): #39     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter ( 8169): #40     RenderObject.layout (package:flutter/src/rendering/object.dart:1619:7)
I/flutter ( 8169): #41     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter ( 8169): #42     RenderObject.layout (package:flutter/src/rendering/object.dart:1619:7)
I/flutter ( 8169): #43     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter ( 8169): #44     RenderObject.layout (package:flutter/src/rendering/object.dart:1619:7)
I/flutter ( 8169): #45     RenderStack.performLayout (package:flutter/src/rendering/stack.dart:510:15)
I/flutter ( 8169): #46     RenderObject.layout (package:flutter/src/rendering/object.dart:1619:7)
I/flutter ( 8169): #47     MultiChildLayoutDelegate.layoutChild (package:flutter/src/rendering/custom_layout.dart:142:11)
I/flutter ( 8169): #48     _ScaffoldLayout.performLayout (package:flutter/src/material/scaffold.dart:443:7)
I/flutter ( 8169): #49     MultiChildLayoutDelegate._callPerformLayout (package:flutter/src/rendering/custom_layout.dart:212:7)
I/flutter ( 8169): #50     RenderCustomMultiChildLayoutBox.performLayout (package:flutter/src/rendering/custom_layout.dart:356:14)
I/flutter ( 8169): #51     RenderObject.layout (package:flutter/src/rendering/object.dart:1619:7)
I/flutter ( 8169): #52     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter ( 8169): #53     RenderObject.layout (package:flutter/src/rendering/object.dart:1619:7)
I/flutter ( 8169): #54     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter ( 8169): #55     _RenderCustomClip.performLayout (package:flutter/src/rendering/proxy_box.dart:1214:11)
I/flutter ( 8169): #56     RenderObject.layout (package:flutter/src/rendering/object.dart:1619:7)
I/flutter ( 8169): #57     MultiChildLayoutDelegate.layoutChild (package:flutter/src/rendering/custom_layout.dart:142:11)
I/flutter ( 8169): #58     _ScaffoldLayout.performLayout (package:flutter/src/material/scaffold.dart:443:7)
I/flutter ( 8169): #59     MultiChildLayoutDelegate._callPerformLayout (package:flutter/src/rendering/custom_layout.dart:212:7)
I/flutter ( 8169): #60     RenderCustomMultiChildLayoutBox.performLayout (package:flutter/src/rendering/custom_layout.dart:356:14)
I/flutter ( 8169): #61     RenderObject.layout (package:flutter/src/rendering/object.dart:1619:7)
I/flutter ( 8169): #62     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter ( 8169): #63     RenderObject.layout (package:flutter/src/rendering/object.dart:1619:7)
I/flutter ( 8169): #64     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter ( 8169): #65     _RenderCustomClip.performLayout (package:flutter/src/rendering/proxy_box.dart:1214:11)
I/flutter ( 8169): #66     RenderObject.layout (package:flutter/src/rendering/object.dart:1619:7)
I/flutter ( 8169): #67     MultiChildLayoutDelegate.layoutChild (package:flutter/src/rendering/custom_layout.dart:142:11)
I/flutter ( 8169): #68     _ScaffoldLayout.performLayout (package:flutter/src/material/scaffold.dart:443:7)
I/flutter ( 8169): #69     MultiChildLayoutDelegate._callPerformLayout (package:flutter/src/rendering/custom_layout.dart:212:7)
I/flutter ( 8169): #70     RenderCustomMultiChildLayoutBox.performLayout (package:flutter/src/rendering/custom_layout.dart:356:14)
I/flutter ( 8169): #71     RenderObject._layoutWithoutResize (package:flutter/src/rendering/object.dart:1496:7)
I/flutter ( 8169): #72     PipelineOwner.flushLayout (package:flutter/src/rendering/object.dart:765:18)
I/flutter ( 8169): #73     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding.drawFrame (package:flutter/src/rendering/binding.dart:346:19)
I/flutter ( 8169): #74     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding&WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:701:13)
I/flutter ( 8169): #75     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:285:5)
I/flutter ( 8169): #76     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1016:15)
I/flutter ( 8169): #77     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:958:9)
I/flutter ( 8169): #78     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:874:5)
I/flutter ( 8169): #82     _invoke (dart:ui/hooks.dart:236:10)
I/flutter ( 8169): #83     _drawFrame (dart:ui/hooks.dart:194:3)
I/flutter ( 8169): (elided 3 frames from package dart:async)
I/flutter ( 8169): ════════════════════════════════════════════════════════════════════════════════════════════════════
I/flutter ( 8169): Another exception was thrown: Assertion failed
```

**Comment by Levi-Lesches** [comment]
1. Please give this a more meaningful title, I have no clue what happened here
2. It says `Assertion failed: `. Is there anything after that? What caused this? Can you post your code? Namely `ContactState.build`. Much more detail is needed here.

**Comment by BondarenkoStas** [comment]
@mmzuo Is it still relevant?

**Comment by iapicca** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact descriptions what happens, logs and the output of ' flutter doctor -v'  please.
All system setups can be slightly different so its always better to open new issues and reference related issues.
