### ISSUE TITLE
flutter module in native project, click bottom back in phone, can't back normally.

### ISSUE THREAD

**Issue by longdw** [flutter/flutter#39108]
I add a flutter module to my native android project, I `push` a page or `showModalBottomSheet` a dialog in flutter project, it looks like working very well in flutter project. But when I add it to android project,  I click the phone's bottom virtual back when a dialog is showing or push a page, all flutter pages are returned. It seems that dialog or page can't get focus.

I follow this article [https://github.com/flutter/flutter/wiki/Add-Flutter-to-existing-apps#use-the-flutter-module-from-your-java-code](https://github.com/flutter/flutter/wiki/Add-Flutter-to-existing-apps#use-the-flutter-module-from-your-java-code).

I don't have a nice way to solve this problem.

@xster @jmagman @dnfield

**Comment by xster** [comment]
Not sure I completely understood the problem. Are you saying Flutter isn't internally handling the back button press to pop Flutter internal routes and the Android activity stack is popped instead? 

Did you use io.flutter.embedding.android.FlutterActivity which overrides onBackPressed?

cc @matthew-carroll

**Comment by longdw** [comment]
Yes, back button press can't pop Flutter iternal routes and Android activity poped instead! My Activity extends AppCompatActivity not io.flutter.embedding.android.FlutterActivity.

I have solved this problem  temporarily to overrides onBackPressed and use channel to send message and invokeMethod.

```
public abstract class BaseFlutterActivity extends AppCompatActivity {

    public static final int RC_CATEGORY = 0x1001;

    protected String mJsonParams;
    protected WorkOrderBean mWorkOrderBean;

    @Override
    protected void onCreate(@Nullable Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);


        Eyes.setStatusBarLightMode(this, Color.WHITE);
//        supportRequestWindowFeature(Window.FEATURE_NO_TITLE);
        setContentView(R.layout.flutter_activity);
        getSupportActionBar().hide();

        mJsonParams = getIntent().getStringExtra(Contacts.APP_INTENT_PARAMS_ONE);

        mWorkOrderBean = new Gson().fromJson(mJsonParams, WorkOrderBean.class);

        initChannel();
    }

    private void initChannel() {
        ChannelUtil.initServiceChannel(this, initFlutterView(), new ChannelUtil.OnBackListener() {
            @Override
            public void onBack() {
                finish();
            }
        });
    }

    protected abstract FlutterView initFlutterView();

    @Override
    protected void onActivityResult(int requestCode, int resultCode, @Nullable Intent data) {
        if (data == null) {
            return;
        }
        if (requestCode == RC_CATEGORY) {
            CsmCategory csmCategory = (CsmCategory) data.getSerializableExtra(Contacts.APP_INTENT_PARAMS_ONE);
            HashMap<String, Object> params = new HashMap<>();
            params.put("type", ChannelUtil.MSGTYPE_CATEGORY);
            params.put("data", JsonUtil.toJson(csmCategory));
            ChannelUtil.sendMessage(params);
        }
    }

    @Override
    public void onBackPressed() {
        HashMap<String, Object> params = new HashMap<>();
        params.put("type", ChannelUtil.MSGTYPE_BACK);
        ChannelUtil.sendMessage(params);
    }
}
```

**Comment by xster** [comment]
Yes, a whole bunch of manual plumbing is generally needed if you use a FlutterView directly. Conceptually, we wouldn't have any way of figuring out when activity lifecycle events happen if you don't use the FlutterActivity. 

@matthew-carroll we should make the warnings very ominous on the website when we write this section.

**Comment by longdw** [comment]
you say FllutterActivity, do you mean My Activity should extends FlutterActivity not AppCompatActivity?

**Comment by matthew-carroll** [comment]
@longdw you should either use or extend `io.flutter.embedding.android.FlutterActivity`, or you should use a `io.flutter.embedding.android.FlutterFragment`, depending on your situation. Using a `FlutterActivity` is the easiest way to integrate Flutter with Android.

Here is a wiki guide for FlutterActivity:
https://github.com/flutter/flutter/wiki/Experimental:-Add-Flutter-Activity

**Comment by longdw** [comment]
thank you @matthew-carroll, I try to follow the wiki guide and use 
```
Intent defaultFlutter = FlutterActivity.createDefaultIntent(MainActivity.this);
startActivity(defaultFlutter);
```
but app crashed and throws these erros:

```
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.david.testpluginandroid/io.flutter.embedding.android.FlutterActivity}: java.lang.IllegalStateException: ensureInitializationComplete must be called after startInitialization
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2913)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3048)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1808)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6669)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
     Caused by: java.lang.IllegalStateException: ensureInitializationComplete must be called after startInitialization
        at io.flutter.view.FlutterMain.ensureInitializationComplete(FlutterMain.java:168)
        at io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.initializeFlutter(FlutterActivityAndFragmentDelegate.java:177)
        at io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.onAttach(FlutterActivityAndFragmentDelegate.java:140)
        at io.flutter.embedding.android.FlutterActivity.onCreate(FlutterActivity.java:399)
        at android.app.Activity.performCreate(Activity.java:7136)
        at android.app.Activity.performCreate(Activity.java:7127)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1271)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2893)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3048) 
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78) 
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1808) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:193) 
        at android.app.ActivityThread.main(ActivityThread.java:6669) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858) 
```

**Comment by matthew-carroll** [comment]
Oh, that's because no matter which approach you use, you'll still need to initialize the overall Flutter system. The easiest way to initialize Flutter is to add the following to your `Application` class:

```
onCreate() {
  super.onCreate();

  FlutterMain.startInitialization(this);
}
```

If you look at the source code of a full Flutter app, you'll see this same behavior in its `Application` class.

**Comment by xster** [comment]
Closing this issue for now. Please feel free to open another issue if you run into more problems.
