### ISSUE TITLE
Gradle task assembleDebug failed with exit code 1

### ISSUE THREAD

**Issue by Mellie45** [flutter/flutter#39117]
Keep running into this error after upgrading Android Studio to the latest version - 3.5.

Everything was fine before the upgrade.

```
flutter build bundle --target /Users/melcolton/development/bite/bite/lib/main.dart --target-platform android-x86 --filesystem-scheme org-dartlang-root --track-widget-creation --depfile /Users/melcolton/development/bite/bite/build/app/intermediates/flutter/debug/android-x86/snapshot_blob.bin.d --asset-dir /Users/melcolton/development/bite/bite/build/app/intermediates/flutter/debug/android-x86/flutter_assets --debug
```

## exception

```
NoSuchMethodError: NoSuchMethodError: The getter 'length' was called on null.
Receiver: null
Tried calling: length
```

```
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:51:5)
#1      _Uri._uriEncode (dart:core-patch/uri_patch.dart:44:23)
#2      Uri.encodeFull (dart:core/uri.dart:1148:17)
#3      MappedListIterable.elementAt (dart:_internal/iterable.dart:415:29)
#4      MappedListIterable.elementAt (dart:_internal/iterable.dart:415:40)
#5      ListIterable.toList (dart:_internal/iterable.dart:219:19)
#6      FlutterManifest.assets (package:flutter_tools/src/flutter_manifest.dart:187:11)
#7      _parseAssets (package:flutter_tools/src/asset.dart:557:40)
#8      _ManifestAssetBundle.build (package:flutter_tools/src/asset.dart:143:53)
<asynchronous suspension>
#9      buildAssets (package:flutter_tools/src/bundle.dart:137:40)
<asynchronous suspension>
#10     BundleBuilder.build (package:flutter_tools/src/bundle.dart:106:38)
<asynchronous suspension>
#11     BuildBundleCommand.runCommand (package:flutter_tools/src/commands/build_bundle.dart:119:25)
<asynchronous suspension>
#12     FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:490:18)
<asynchronous suspension>
#13     FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:407:33)
<asynchronous suspension>
#14     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:154:29)
<asynchronous suspension>
#15     _rootRun (dart:async/zone.dart:1124:13)
#16     _CustomZone.run (dart:async/zone.dart:1021:19)
#17     _runZoned (dart:async/zone.dart:1516:10)
#18     runZoned (dart:async/zone.dart:1463:12)
#19     AppContext.run (package:flutter_tools/src/base/context.dart:153:18)
<asynchronous suspension>
#20     FlutterCommand.run (package:flutter_tools/src/runner/flutter_command.dart:397:20)
#21     CommandRunner.runCommand (package:args/command_runner.dart:197:27)
<asynchronous suspension>
#22     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:402:21)
<asynchronous suspension>
#23     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:154:29)
<asynchronous suspension>
#24     _rootRun (dart:async/zone.dart:1124:13)
#25     _CustomZone.run (dart:async/zone.dart:1021:19)
#26     _runZoned (dart:async/zone.dart:1516:10)
#27     runZoned (dart:async/zone.dart:1463:12)
#28     AppContext.run (package:flutter_tools/src/base/context.dart:153:18)
<asynchronous suspension>
#29     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:356:19)
<asynchronous suspension>
#30     CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:112:25)
#31     new Future.sync (dart:async/future.dart:224:31)
#32     CommandRunner.run (package:args/command_runner.dart:112:14)
#33     FlutterCommandRunner.run (package:flutter_tools/src/runner/flutter_command_runner.dart:242:18)
#34     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:63:22)
<asynchronous suspension>
#35     _rootRun (dart:async/zone.dart:1124:13)
#36     _CustomZone.run (dart:async/zone.dart:1021:19)
#37     _runZoned (dart:async/zone.dart:1516:10)
#38     runZoned (dart:async/zone.dart:1500:12)
#39     run.<anonymous closure> (package:flutter_tools/runner.dart:61:18)
<asynchronous suspension>
#40     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:154:29)
<asynchronous suspension>
#41     _rootRun (dart:async/zone.dart:1124:13)
#42     _CustomZone.run (dart:async/zone.dart:1021:19)
#43     _runZoned (dart:async/zone.dart:1516:10)
#44     runZoned (dart:async/zone.dart:1463:12)
#45     AppContext.run (package:flutter_tools/src/base/context.dart:153:18)
<asynchronous suspension>
#46     runInContext (package:flutter_tools/src/context_runner.dart:58:24)
<asynchronous suspension>
#47     run (package:flutter_tools/runner.dart:50:10)
#48     main (package:flutter_tools/executable.dart:65:9)
<asynchronous suspension>
#49     main (file:///Users/melcolton/development/flutter/packages/flutter_tools/bin/flutter_tools.dart:8:3)
#50     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:303:32)
#51     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:12)
```

## flutter doctor

```
[✓] Flutter (Channel master, v1.9.1-pre.111, on Mac OS X 10.14.5 18F132, locale en-GB)
    • Flutter version 1.9.1-pre.111 at /Users/melcolton/development/flutter
    • Framework revision 109893c6cf (3 days ago), 2019-08-20 09:55:29 -0400
    • Engine revision 10167db433
    • Dart version 2.5.0

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.1)
    • Android SDK at /Users/melcolton/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.1
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 10.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.3, Build version 10G8
    • CocoaPods version 1.7.5

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 38.2.3
    • Dart plugin version 191.8423
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] IntelliJ IDEA Community Edition (version 2019.2)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 37.1.4
    • Dart plugin version 192.5728.98

[✓] Connected device (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 10 (API 29) (emulator)

• No issues found!
```

**Comment by jonahwilliams** [comment]
This was caused by a bug in the flutter manifest parsing when the yaml was incorrectly formatted and has since been fixed
