### ISSUE TITLE
Flutter 1.7.8.hotfix.4-1 crashes in linux

### ISSUE THREAD

**Issue by mesjetiu** [flutter/flutter#39179]
[flutter_05.log](https://github.com/flutter/flutter/files/3537071/flutter_05.log)

Hi!

I use flutter sdk in Arch linux and frequently it crashes. I attach the log crash to this issue.
```Flutter version: 1.7.8.hotfix.4-1```

Linux version (`uname -a`)
```
Linux msj 4.19.66-1-MANJARO #1 SMP PREEMPT Fri Aug 9 18:01:53 UTC 2019 x86_64 GNU/Linux
```

Crash message: 
```
Oops; flutter has exited unexpectedly.
Sending crash report to Google.
Crash report sent (report ID: dc3c4ace7a7c5c8a)
Crash report n to /home/carlos/flutter_05.log;             
please let us know at https://github.com/flutter/flutter/issues.
```

**Comment by acnologia000** [comment]
can you post contents of `/home/carlos/flutter_05.log` ?

**Comment by mesjetiu** [comment]
The file is attached to the first message. Here is the content:


`Flutter crash report; please file at https://github.com/flutter/flutter/issues.

## command

flutter doctor

## exception

FileSystemException: FileSystemException: Cannot open file, path = '/opt/flutter/bin/cache/flutter_version_check.stamp' (OS Error: Permission denied, errno = 13)

```
#0      _File.throwIfError (dart:io/file_impl.dart:643:7)
#1      _File.openSync (dart:io/file_impl.dart:487:5)
#2      _File.writeAsBytesSync (dart:io/file_impl.dart:612:31)
#3      _File.writeAsStringSync (dart:io/file_impl.dart:636:5)
#4      _LocalFile&LocalFileSystemEntity&ForwardingFile.writeAsStringSync (package:file/src/forwarding/forwarding_file.dart:152:16)
#5      Cache.setStampFor (package:flutter_tools/src/cache.dart:243:35)
#6      VersionCheckStamp.store (package:flutter_tools/src/version.dart:469:20)
<asynchronous suspension>
#7      FlutterVersion._getLatestAvailableFlutterDate (package:flutter_tools/src/version.dart:391:31)
<asynchronous suspension>
#8      FlutterVersion.checkFlutterVersionFreshness (package:flutter_tools/src/version.dart:296:52)
<asynchronous suspension>
#9      FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:372:41)
<asynchronous suspension>
#10     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:29)
<asynchronous suspension>
#11     _rootRun (dart:async/zone.dart:1124:13)
#12     _CustomZone.run (dart:async/zone.dart:1021:19)
#13     _runZoned (dart:async/zone.dart:1516:10)
#14     runZoned (dart:async/zone.dart:1463:12)
#15     AppContext.run (package:flutter_tools/src/base/context.dart:152:18)
<asynchronous suspension>
#16     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:356:19)
<asynchronous suspension>
#17     CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:112:25)
#18     new Future.sync (dart:async/future.dart:224:31)
#19     CommandRunner.run (package:args/command_runner.dart:112:14)
#20     FlutterCommandRunner.run (package:flutter_tools/src/runner/flutter_command_runner.dart:242:18)
#21     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:62:22)
<asynchronous suspension>
#22     _rootRun (dart:async/zone.dart:1124:13)
#23     _CustomZone.run (dart:async/zone.dart:1021:19)
#24     _runZoned (dart:async/zone.dart:1516:10)
#25     runZoned (dart:async/zone.dart:1500:12)
#26     run.<anonymous closure> (package:flutter_tools/runner.dart:60:18)
<asynchronous suspension>
#27     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:29)
<asynchronous suspension>
#28     _rootRun (dart:async/zone.dart:1124:13)
#29     _CustomZone.run (dart:async/zone.dart:1021:19)
#30     _runZoned (dart:async/zone.dart:1516:10)
#31     runZoned (dart:async/zone.dart:1463:12)
#32     AppContext.run (package:flutter_tools/src/base/context.dart:152:18)
<asynchronous suspension>
#33     runInContext (package:flutter_tools/src/context_runner.dart:56:24)
<asynchronous suspension>
#34     run (package:flutter_tools/runner.dart:51:10)
#35     main (package:flutter_tools/executable.dart:62:9)
<asynchronous suspension>
#36     main (file:///b/s/w/ir/k/archive/flutter/packages/flutter_tools/bin/flutter_tools.dart:8:3)
#37     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:299:32)
#38     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:12)
```

## flutter doctor

```
[32m[✓][39m Flutter (Channel stable, v1.7.8+hotfix.4, on Linux, locale es_ES.UTF-8)
    [32m•[39m Flutter version 1.7.8+hotfix.4 at /opt/flutter
    [32m•[39m Framework revision 20e59316b8 (hace 5 semanas), 2019-07-18 20:04:33 -0700
    [32m•[39m Engine revision fee001c93f
    [32m•[39m Dart version 2.4.0

[32m[✓][39m Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    [32m•[39m Android SDK at /home/carlos/Android/Sdk
    [32m•[39m Android NDK location not configured (optional; useful for native profiling
      support)
    [32m•[39m Platform android-29, build-tools 29.0.2
    [32m•[39m Java binary at: /opt/android-studio/jre/bin/java
    [32m•[39m Java version OpenJDK Runtime Environment (build
      1.8.0_152-release-1343-b16-5323222)
    [32m•[39m All Android licenses accepted.

[32m[✓][39m Android Studio (version 3.4)
    [32m•[39m Android Studio at /opt/android-studio
    [32m•[39m Flutter plugin version 38.2.1
    [32m•[39m Dart plugin version 183.6270
    [32m•[39m Java version OpenJDK Runtime Environment (build
      1.8.0_152-release-1343-b16-5323222)

[33m[!][39m Connected device
    [33m![39m No devices available

[33m![39m Doctor found issues in 1 category.
````

**Comment by VladyslavBondarenko** [comment]
duplicate https://github.com/flutter/flutter/issues/28210
