### ISSUE TITLE
Flutter Crashes when futter run command

### ISSUE THREAD

**Issue by StrangeNoob** [flutter/flutter#39185]
## Steps to Reproduce

1.  Flutter Crashes when ```futter run``` command
2. https://gist.github.com/StrangeNoob/7bdfb900a539e0429db1b1c22a4d177f
3. Crash Report

 ```
#0      runCheckedAsync (package:flutter_tools/src/base/process.dart:259:7)
<asynchronous suspension>
#1      _initializeGradle (package:flutter_tools/src/android/gradle.dart:225:9)
<asynchronous suspension>
#2      _ensureGradle (package:flutter_tools/src/android/gradle.dart:206:37)
<asynchronous suspension>
#3      _readGradleProject (package:flutter_tools/src/android/gradle.dart:134:31)
<asynchronous suspension>
#4      _gradleProject (package:flutter_tools/src/android/gradle.dart:111:34)
<asynchronous suspension>
#5      getGradleAppOut (package:flutter_tools/src/android/gradle.dart:105:29)
<asynchronous suspension>
#6      AndroidApk.fromAndroidProject (package:flutter_tools/src/application_package.dart:160:23)
<asynchronous suspension>
#7      ApplicationPackageFactory.getPackageForPlatform (package:flutter_tools/src/application_package.dart:47:32)
<asynchronous suspension>
#8      FlutterDevice.runHot (package:flutter_tools/src/resident_runner.dart:352:56)
<asynchronous suspension>
#9      HotRunner.run (package:flutter_tools/src/run_hot.dart:251:39)
<asynchronous suspension>
#10     RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:469:37)
<asynchronous suspension>
#11     FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:478:18)
<asynchronous suspension>
#12     FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:383:33)
<asynchronous suspension>
#13     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:29)
<asynchronous suspension>
#14     _rootRun (dart:async/zone.dart:1124:13)
#15     _CustomZone.run (dart:async/zone.dart:1021:19)
#16     _runZoned (dart:async/zone.dart:1516:10)
#17     runZoned (dart:async/zone.dart:1463:12)
#18     AppContext.run (package:flutter_tools/src/base/context.dart:152:18)
<asynchronous suspension>
#19     FlutterCommand.run (package:flutter_tools/src/runner/flutter_command.dart:375:20)
#20     CommandRunner.runCommand (package:args/command_runner.dart:197:27)
<asynchronous suspension>
#21     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:396:21)
<asynchronous suspension>
#22     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:29)
<asynchronous suspension>
#23     _rootRun (dart:async/zone.dart:1124:13)
#24     _CustomZone.run (dart:async/zone.dart:1021:19)
#25     _runZoned (dart:async/zone.dart:1516:10)
#26     runZoned (dart:async/zone.dart:1463:12)
#27     AppContext.run (package:flutter_tools/src/base/context.dart:152:18)
<asynchronous suspension>
#28     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:356:19)
<asynchronous suspension>
#29     CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:112:25)
#30     new Future.sync (dart:async/future.dart:224:31)
#31     CommandRunner.run (package:args/command_runner.dart:112:14)
#32     FlutterCommandRunner.run (package:flutter_tools/src/runner/flutter_command_runner.dart:242:18)
#33     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:62:22)
<asynchronous suspension>
#34     _rootRun (dart:async/zone.dart:1124:13)
#35     _CustomZone.run (dart:async/zone.dart:1021:19)
#36     _runZoned (dart:async/zone.dart:1516:10)
#37     runZoned (dart:async/zone.dart:1500:12)
#38     run.<anonymous closure> (package:flutter_tools/runner.dart:60:18)
<asynchronous suspension>
#39     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:29)
<asynchronous suspension>
#40     _rootRun (dart:async/zone.dart:1124:13)
#41     _CustomZone.run (dart:async/zone.dart:1021:19)
#42     _runZoned (dart:async/zone.dart:1516:10)
#43     runZoned (dart:async/zone.dart:1463:12)
#44     AppContext.run (package:flutter_tools/src/base/context.dart:152:18)
<asynchronous suspension>
#45     runInContext (package:flutter_tools/src/context_runner.dart:56:24)
<asynchronous suspension>
#46     run (package:flutter_tools/runner.dart:51:10)
#47     main (package:flutter_tools/executable.dart:62:9)
<asynchronous suspension>
#48     main (file:///C:/Flutter/flutter/packages/flutter_tools/bin/flutter_tools.dart:8:3)
#49     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:299:32)
#50     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:12)
```
## Logs

```
[ +113 ms] executing: [C:\Flutter\flutter\] git log -n 1 --pretty=format:%H
[+2945 ms] Exit code 0 from: git log -n 1 --pretty=format:%H
[   +1 ms] 20e59316b8b8474554b38493b8ca888794b0234a
[   +1 ms] executing: [C:\Flutter\flutter\] git describe --match v*.*.* --first-parent --long --tags
[ +732 ms] Exit code 0 from: git describe --match v*.*.* --first-parent --long --tags
[   +1 ms] v1.7.8+hotfix.4-0-g20e59316b
[  +23 ms] executing: [C:\Flutter\flutter\] git rev-parse --abbrev-ref --symbolic @{u}
[ +316 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[   +1 ms] origin/stable
[   +1 ms] executing: [C:\Flutter\flutter\] git ls-remote --get-url origin
[ +262 ms] Exit code 0 from: git ls-remote --get-url origin
[   +1 ms] https://github.com/flutter/flutter.git
[ +424 ms] executing: [C:\Flutter\flutter\] git rev-parse --abbrev-ref HEAD
[ +255 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[   +1 ms] stable
[ +347 ms] executing: D:\sdk\platform-tools\adb.exe devices -l
[ +188 ms] Exit code 0 from: D:\sdk\platform-tools\adb.exe devices -l
[   +4 ms] List of devices attached
           J8AAGF020968RP9        device product:WW_X00TD model:ASUS_X00TD device:ASUS_X00T_2 transport_id:1
[  +38 ms] D:\sdk\platform-tools\adb.exe -s J8AAGF020968RP9 shell getprop
[ +355 ms] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[  +75 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[   +3 ms] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[   +3 ms] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[   +2 ms] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[   +3 ms] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[ +337 ms] Found plugin cloud_firestore at C:\Flutter\flutter\.pub-cache\hosted\pub.dartlang.org\cloud_firestore-0.12.5+2\
[ +176 ms] Found plugin firebase_auth at C:\Flutter\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_auth-0.11.1+7\
[ +124 ms] Found plugin firebase_core at C:\Flutter\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_core-0.4.0+6\
[ +116 ms] Found plugin firebase_database at C:\Flutter\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_database-3.0.3\
[  +63 ms] Found plugin firebase_storage at C:\Flutter\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_storage-3.0.2\
[ +729 ms] Found plugin google_sign_in at C:\Flutter\flutter\.pub-cache\hosted\pub.dartlang.org\google_sign_in-4.0.2\
[ +877 ms] Found plugin cloud_firestore at C:\Flutter\flutter\.pub-cache\hosted\pub.dartlang.org\cloud_firestore-0.12.5+2\
[   +8 ms] Found plugin firebase_auth at C:\Flutter\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_auth-0.11.1+7\
[   +4 ms] Found plugin firebase_core at C:\Flutter\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_core-0.4.0+6\
[   +4 ms] Found plugin firebase_database at C:\Flutter\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_database-3.0.3\
[   +5 ms] Found plugin firebase_storage at C:\Flutter\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_storage-3.0.2\
[  +16 ms] Found plugin google_sign_in at C:\Flutter\flutter\.pub-cache\hosted\pub.dartlang.org\google_sign_in-4.0.2\
[+1407 ms] ro.hardware = qcom
[  +36 ms] Launching lib/main.dart on ASUS X00TD in debug mode...
[ +202 ms] Initializing gradle...
[   +3 ms] Using gradle from C:\Program Files\Git\Code\Anime-Quote-App\anime_qoutes\android\gradlew.bat.
[+5203 ms] executing: C:\Program Files\Git\Code\Anime-Quote-App\anime_qoutes\android\gradlew.bat -v
[+12838 ms]
                     ------------------------------------------------------------
                     Gradle 4.10.2
                     ------------------------------------------------------------

                     Build time:   2018-09-19 18:10:15 UTC
                     Revision:     b4d8d5d170bb4ba516e88d7fe5647e2323d791dd

                     Kotlin DSL:   1.0-rc-6
                     Kotlin:       1.2.61
                     Groovy:       2.4.15
                     Ant:          Apache Ant(TM) version 1.9.11 compiled on March 23 2018
                     JVM:          1.8.0_152-release (JetBrains s.r.o 25.152-b01)
                     OS:           Windows 10 10.0 amd64
[  +83 ms] "flutter run" took 23,185ms.
[   +1 ms] "flutter run" took 23,185ms.

Oops; flutter has exited unexpectedly.
Sending crash report to Google.
Crash report sent (report ID: bb5a69a5fb5efb5b)

Crash report written to C:\Program Files\Git\Code\Anime-Quote-App\anime_qoutes\flutter_16.log;
please let us know at https://github.com/flutter/flutter/issues.
```

```
Analyzing anime_qoutes...

   info - This class (or a class which this class inherits from) is marked as '@immutable', but one or more of its instance fields are not final:
          BottomNavyBar.selectedIndex - lib\bottom_navy_bar.dart:6:7 - must_be_immutable

```

## Flutter doctor
```
[√] Flutter (Channel stable, v1.7.8+hotfix.4, on Microsoft Windows [Version 10.0.17763.678], locale en-IN)
    • Flutter version 1.7.8+hotfix.4 at C:\Flutter\flutter
    • Framework revision 20e59316b8 (5 weeks ago), 2019-07-18 20:04:33 -0700
    • Engine revision fee001c93f
    • Dart version 2.4.0


[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at D:\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
    • All Android licenses accepted.

[√] Android Studio (version 3.4)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 37.1.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

[√] VS Code (version 1.37.1)
    • VS Code at C:\Users\Leon\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.3.0

[√] Connected device (1 available)
    • ASUS X00TD • J8AAGF020968RP9 • android-arm64 • Android 9 (API 28)

• No issues found!
```

**Comment by Levi-Lesches** [comment]
Please post the contents of `C:\Program Files\Git\Code\Anime-Quote-App\anime_qoutes\flutter_16.log` here

**Comment by Levi-Lesches** [comment]
But I believe I already know the issue. It's possible Flutter (and Gradle by extension) don't have access to your code. This is a common problem with putting things in `Program Files` -- they always require admin access. Might I suggest putting the code in your `users` folder? It helps keep things more organized, and less error-prone.

**Comment by StrangeNoob** [comment]
@Levi-Lesches 
#0      runCheckedAsync (package:flutter_tools/src/base/process.dart:259:7)
<asynchronous suspension>
#1      _initializeGradle (package:flutter_tools/src/android/gradle.dart:225:9)
<asynchronous suspension>
#2      _ensureGradle (package:flutter_tools/src/android/gradle.dart:206:37)
<asynchronous suspension>
#3      _readGradleProject (package:flutter_tools/src/android/gradle.dart:134:31)
<asynchronous suspension>
#4      _gradleProject (package:flutter_tools/src/android/gradle.dart:111:34)
<asynchronous suspension>
#5      getGradleAppOut (package:flutter_tools/src/android/gradle.dart:105:29)
<asynchronous suspension>
#6      AndroidApk.fromAndroidProject (package:flutter_tools/src/application_package.dart:160:23)
<asynchronous suspension>
#7      ApplicationPackageFactory.getPackageForPlatform (package:flutter_tools/src/application_package.dart:47:32)
<asynchronous suspension>
#8      FlutterDevice.runHot (package:flutter_tools/src/resident_runner.dart:352:56)
<asynchronous suspension>
#9      HotRunner.run (package:flutter_tools/src/run_hot.dart:251:39)
<asynchronous suspension>
#10     RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:469:37)
<asynchronous suspension>
#11     FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:478:18)
<asynchronous suspension>
#12     FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:383:33)
<asynchronous suspension>
#13     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:29)
<asynchronous suspension>
#14     _rootRun (dart:async/zone.dart:1124:13)
#15     _CustomZone.run (dart:async/zone.dart:1021:19)
#16     _runZoned (dart:async/zone.dart:1516:10)
#17     runZoned (dart:async/zone.dart:1463:12)
#18     AppContext.run (package:flutter_tools/src/base/context.dart:152:18)
<asynchronous suspension>
#19     FlutterCommand.run (package:flutter_tools/src/runner/flutter_command.dart:375:20)
#20     CommandRunner.runCommand (package:args/command_runner.dart:197:27)
<asynchronous suspension>
#21     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:396:21)
<asynchronous suspension>
#22     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:29)
<asynchronous suspension>
#23     _rootRun (dart:async/zone.dart:1124:13)
#24     _CustomZone.run (dart:async/zone.dart:1021:19)
#25     _runZoned (dart:async/zone.dart:1516:10)
#26     runZoned (dart:async/zone.dart:1463:12)
#27     AppContext.run (package:flutter_tools/src/base/context.dart:152:18)
<asynchronous suspension>
#28     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:356:19)
<asynchronous suspension>
#29     CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:112:25)
#30     new Future.sync (dart:async/future.dart:224:31)
#31     CommandRunner.run (package:args/command_runner.dart:112:14)
#32     FlutterCommandRunner.run (package:flutter_tools/src/runner/flutter_command_runner.dart:242:18)
#33     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:62:22)
<asynchronous suspension>
#34     _rootRun (dart:async/zone.dart:1124:13)
#35     _CustomZone.run (dart:async/zone.dart:1021:19)
#36     _runZoned (dart:async/zone.dart:1516:10)
#37     runZoned (dart:async/zone.dart:1500:12)
#38     run.<anonymous closure> (package:flutter_tools/runner.dart:60:18)
<asynchronous suspension>
#39     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:29)
<asynchronous suspension>
#40     _rootRun (dart:async/zone.dart:1124:13)
#41     _CustomZone.run (dart:async/zone.dart:1021:19)
#42     _runZoned (dart:async/zone.dart:1516:10)
#43     runZoned (dart:async/zone.dart:1463:12)
#44     AppContext.run (package:flutter_tools/src/base/context.dart:152:18)
<asynchronous suspension>
#45     runInContext (package:flutter_tools/src/context_runner.dart:56:24)
<asynchronous suspension>
#46     run (package:flutter_tools/runner.dart:51:10)
#47     main (package:flutter_tools/executable.dart:62:9)
<asynchronous suspension>
#48     main (file:///C:/Flutter/flutter/packages/flutter_tools/bin/flutter_tools.dart:8:3)
#49     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:299:32)
#50     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:12)

**Comment by BondarenkoStas** [comment]
@StrangeNoob please report if your issue was solved.
