### ISSUE TITLE
SecurityContext.setTrustedCertificatesBytes fails with 

### ISSUE THREAD

**Issue by BeStillAsBright** [flutter/flutter#39190]
Hi! I'm trying to use SecurityContext.setTrustedCertificateBytes with a DER encoded x509 certificate and my app keeps blowing up and telling me that it's an invalid PKCS12 format. However, the docs do not say that the x509 certificate needs to be encoded in PKCS12 (all it says is that it needs to be a DER encoding of the x509 cert). This occurs on both Android and iOS simulators. I'm wondering if I'm just missing something? I believe my code to convert the pem text certificate to the .DER binary encoding is correct, but I can post it if necessary. Of note: I am already obtaining a client private key and a client cert, converting them to PKCS12 format and setting the security context with them before I am setting the trusted certificate bytes, and I am not receiving a format error there on either platform.

## Steps to Reproduce

1. Obtain x509 certificate PEM via network
2. Convert x509 PEM to DER programmatically using OPENSSL in C via Platform Channel method call:
    1. Write x509 PEM to bio using BIO_write_ex
    2. Get X509 struct using PEM_read_bio_X509
    3. Create new bio for output
    4. Write x509 to BIO in DER format using i2d_X509_bio
    5. calloc() C array and call BIO_read_ex to fill it with the i2d'd bytes
    6. return DER converted to the appropriate type to get Uint8List back from method call
        * byte[] on Android
        * FlutterStandardTypedData: TypedDataWithBytes on iOS
3. Call SecurityContext.setTrustedCertificateBytes(der.toList()) (.toList() to convert to List<int> from Uint8List)

## Logs

```
[VERBOSE-2:ui_dart_state.cc(148)] Unhandled Exception: TlsException: Failure trusting builtin roots (OS Error: 
	BAD_PKCS12_DATA(pkcs8_x509.c:618), errno = 0)
#0      _SecurityContext.setTrustedCertificatesBytes (dart:io-patch/secure_socket_patch.dart:172:59)
#1      User.generateSecurityContext (package:seabrook_mobile/models/user.dart:128:21)
<asynchronous suspension>
#2      _LoginPageState.build.<anonymous closure>.<anonymous closure> (package:seabrook_mobile/screens/login_page.dart:124:50)
<asynchronous suspension>
#3      _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:511:14)
#4      _InkResponseState.build.<anonymous closure> (package:flutter/src/material/ink_well.dart:566:30)
#5      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:166:24)
#6      TapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:240:9)
#7      TapGestureRecognizer.handlePrimaryPointer (package:flutter/src/gestures/tap.dart:177:9)
#8      PrimaryPointe<…>
```

```
Analyzing seabrook_mobile...                                            

   info • Unused import: 'package:flutter_secure_storage/flutter_secure_storage.dart' • lib/main.dart:5:8 • unused_import
   info • Unused import: 'dart:ui' • lib/models/enclave.dart:1:8 • unused_import
   info • Avoid wrapping fields in getters and setters just to be "safe" • lib/models/user.dart:45:14 •
          unnecessary_getters_setters
   info • Avoid wrapping fields in getters and setters just to be "safe" • lib/models/user.dart:47:7 • unnecessary_getters_setters
   info • Unused import: 'dart:convert' • lib/sbk_crypto.dart:2:8 • unused_import
   info • Unused import: 'dart:io' • lib/sbk_crypto.dart:3:8 • unused_import
   info • Unused import: 'dart:async' • lib/screens/enclave_info_page.dart:1:8 • unused_import
   info • Unused import: 'dart:convert' • lib/screens/enclave_info_page.dart:2:8 • unused_import
   info • Unused import: 'dart:io' • lib/screens/enclave_info_page.dart:3:8 • unused_import
   info • Unused import: 'package:http/http.dart' • lib/screens/enclave_info_page.dart:7:8 • unused_import
   info • Unused import: 'package:seabrook_mobile/server_utils.dart' • lib/screens/enclave_info_page.dart:13:8 • unused_import
   info • Unused import: 'dart:convert' • lib/screens/key_test_page.dart:2:8 • unused_import
   info • Unused import: 'dart:io' • lib/screens/key_test_page.dart:3:8 • unused_import
   info • Unused import: 'package:provider/provider.dart' • lib/screens/key_test_page.dart:7:8 • unused_import
   info • Unused import: 'package:seabrook_mobile/screens/routes.dart' • lib/screens/key_test_page.dart:10:8 • unused_import
   info • Unused import: 'package:seabrook_mobile/server_utils.dart' • lib/screens/key_test_page.dart:11:8 • unused_import
   info • Unused import: 'package:seabrook_mobile/models/models.dart' • lib/screens/key_test_page.dart:12:8 • unused_import
   info • Unused import: 'dart:async' • lib/screens/login_page.dart:1:8 • unused_import
   info • Unused import: 'package:seabrook_mobile/screens/key_test_page.dart' • lib/screens/login_page.dart:10:8 • unused_import
   info • Unused import: 'package:seabrook_mobile/models/models.dart' • lib/screens/router.dart:2:8 • unused_import
   info • Unused import: 'dart:io' • lib/screens/signup_page.dart:3:8 • unused_import
   info • Unused import: 'package:provider/provider.dart' • lib/screens/signup_page.dart:9:8 • unused_import
```

```
[✓] Flutter (Channel stable, v1.5.4-hotfix.2, on Mac OS X 10.14.6 18G87, locale en-US)
    • Flutter version 1.5.4-hotfix.2 at /Users/mike/development/flutter
    • Framework revision 7a4c33425d (4 months ago), 2019-04-29 11:05:24 -0700
    • Engine revision 52c7a1e849
    • Dart version 2.3.0 (build 2.3.0-dev.0.5 a1668566e5)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/mike/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.3, Build version 10G8
    • ios-deploy 1.9.4
    • CocoaPods version 1.6.1

[✓] Android Studio (version 3.4)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 37.0.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

[✓] IntelliJ IDEA Community Edition (version 2019.1.2)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 37.0.2
    • Dart plugin version 191.7830

[✓] Connected device (1 available)
    • iPhone Xʀ • 45696439-655A-4C5C-8CB9-6B3BE0782582 • ios • com.apple.CoreSimulator.SimRuntime.iOS-12-4 (simulator)

• No issues found!

```

**Comment by rajashekarvys** [comment]
Same issue 

[ERROR:flutter/lib/ui/ui_dart_state.cc(148)] Unhandled Exception: TlsException: Failure trusting builtin roots (OS Error: 
    	BAD_PKCS12_DATA(pkcs8_x509.c:618), errno = 0)
    #0      _SecurityContext.setTrustedCertificatesBytes (dart:io-patch/secure_socket_patch.dart:172:59)
    #1      _LoginPageState.serverRequest (package:jhs_flutter_app/login/LoginApp.dart:150:13)
    <asynchronous suspension>
    #2      _LoginPageState.build.<anonymous closure> (package:jhs_flutter_app/login/LoginApp.dart:46:24)
    #3      _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:654:14)
    #4      _InkResponseState.build.<anonymous closure> (package:flutter/src/material/ink_well.dart:729:32)
    #5      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:182:24)
    #6      TapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:365:11)
    #7      TapGestureRecognizer.handlePrimaryPointer (package:flutter/src/gestures/tap.dart:275:7)
    #8      PrimaryPointerGestureRecognizer.handleEvent (package:flutter/src/gestures/recognizer.dart:455:9)
    #9      PointerRouter._dispatch (package:flutter/src/gestures/pointer_router.dart:75:13)
    #10     PointerRouter.route (package:flutter/src/gestures/pointer_router.dart:102:11)
    #11     GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:218:19)
    #12     GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:198:22)
    #13     GestureBinding._handlePointerEvent (package:flutter/src/gestures/binding.dart:156:7)
    #14     GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:102:7)
    #15     GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:86:7)
    #16     _rootRunUnary (dart:async/zone.dart:1136:13)
    #17     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
    #18     _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
    #19     _invoke1 (dart:ui/hooks.dart:263:10)
    #20     _dispatchPointerDataPacket (dart:ui/hooks.dart:172:5)

any solution.

**Comment by mleonhard** [comment]
I got it to work in iOS Simulator by passing a PKCS12 file created with this command:
```openssl pkcs12 -in api_service_cert.pem -nokeys -passout pass:password -export```

**Comment by escamoteur** [comment]
Got the same problem with a PEM file that works using openSSL or curl.
Converting to pkcs12 worked

**Comment by escamoteur** [comment]
I have absolutely no Idea why, but suddenly it also works with PEM files.
@ all others in this thread, can you still reproduce the error?

**Comment by inforaudio** [comment]
Some help? we are in the same problem.
we have crt file,, I should convert in PKCS12 format?

**Comment by totalerex** [comment]
I observed the same issue. As mentioned by @mleonhard, the certificate files must be created in special way. There is additional issue is that **iOS simulator always fails** to verify **self-signed** certificates, but Android emulator behaves well. 
So, for me, complete solution is listed in below steps, terminal commands are for macOS, replace values in square brackets (and remove brackets also :) ), `-outform DER` may be used also:
1. Download certificate from server:
`openssl s_client -connect [SERVER_URL]:[PORT] </dev/null | openssl x509 -outform PEM -out [FILENAME].pem` 
2. Generate pkcs12 from downloaded file:
`openssl pkcs12 -in [FILENAME].pem -nokeys -passout pass:[PASSWORD] -export -out [FILENAME].p12` 
3. Put generated p12 file to assets.
4. Some standard code: 
`final certificateBytes = await rootBundle.load('[FULL_FILENAME]')`
`SecurityContext context = SecurityContext();`
`context.setTrustedCertificatesBytes(certificateBytes, password: "[PASSWORD]"));`
 `final client = HttpClient(context: context,);`

Files generated in this way work both Android and iOS.

Formally we can close issue if there is nothing can be done on Flutter side, if it is some kind of OS restrictions.

**Comment by darshankawar** [comment]
@BeStillAsBright 
Is this still a valid issue using latest Flutter version ?

**Comment by ljmatan** [comment]
@darshankawar I've just stumbled upon the issue today if it's of any help, using latest master version.

**Comment by BeStillAsBright** [comment]
Hi! I'm sorry for not ressponding sooner. I was using Flutter for a research project that we have have since moved on from, so I have not tried the code with the latest update. I believe to resolve it I simply used PKCS12 but that was months ago I'll admit, so I could be wrong. I don't have my environment set up to test this anymore (we tore down the backend that the app talked to), so I can't tell you for sure if the latest update fixed it. I do hope that it is resolved with the new version!

**Comment by Mhamza-MM** [comment]
> I have absolutely no Idea why, but suddenly it also works with PEM files.
> @ all others in this thread, can you still reproduce the error?

I was having an issue with the .crt file that I was working with.
Then I got the .pem file from the back-end dev and just inserted it.
And it started working.

**Comment by jinaiyuanbaojie** [comment]
same issue. I can confirm that what I pass to is same as the badCertificateCallback param.
X509Certificate certain.der

**Comment by jinaiyuanbaojie** [comment]
> I have absolutely no Idea why, but suddenly it also works with PEM files.
> @ all others in this thread, can you still reproduce the error?

Does PEM work on Android side?

**Comment by kira2015** [comment]
The same problem I'm currently experiencing, running on iPhone12,15.5

TlsException (TlsException: Failure in setClientAuthoritiesBytes (OS Error: 
	BAD_PKCS12_DATA(pkcs8_x509.c:657), errno = 0))

**Comment by kira2015** [comment]
> same issue. I can confirm that what I pass to is same as the badCertificateCallback param.
> X509Certificate certain.der

@jinaiyuanbaojie  这个问题,你有新的发现吗? 我卡了好几天了,难受
