### ISSUE TITLE
Flutter Web: Application unexpectedly shuts down while hot restart!

### ISSUE THREAD

**Issue by gurleensethi** [flutter/flutter#39246]
Flutter crash report; please file at https://github.com/flutter/flutter/issues.

## command

flutter run -d chrome

## exception

ChromeDebugException: Unexpected error from chrome devtools:
text: Uncaught
exception:
  description: ReferenceError: require is not defined
    at <anonymous>:1:1
  type: object
  value: null
attempted JS eval: `require('dart_sdk').dart.getLibraries();`

```
#0      handleErrorIfPresent (package:dwds/src/services/chrome_proxy_service.dart:555:5)
#1      AppInspector._getLibraryRefs (package:dwds/src/debugging/inspector.dart:539:5)
<asynchronous suspension>
#2      AppInspector._initialize (package:dwds/src/debugging/inspector.dart:66:36)
<asynchronous suspension>
#3      AppInspector.initialize (package:dwds/src/debugging/inspector.dart:101:21)
<asynchronous suspension>
#4      ChromeProxyService.createIsolate (package:dwds/src/services/chrome_proxy_service.dart:108:37)
<asynchronous suspension>
#5      DevHandler._handleConnection.<anonymous closure> (package:dwds/src/handlers/dev_handler.dart:254:15)
<asynchronous suspension>
#6      _rootRunUnary (dart:async/zone.dart:1132:38)
#7      _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#8      _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
#9      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#10     _DelayedData.perform (dart:async/stream_impl.dart:591:14)
#11     _StreamImplEvents.handleNext (dart:async/stream_impl.dart:707:11)
#12     _PendingEvents.schedule.<anonymous closure> (dart:async/stream_impl.dart:667:7)
#13     _rootRun (dart:async/zone.dart:1120:38)
#14     _CustomZone.run (dart:async/zone.dart:1021:19)
#15     _CustomZone.runGuarded (dart:async/zone.dart:923:7)
#16     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:963:23)
#17     _rootRun (dart:async/zone.dart:1124:13)
#18     _CustomZone.run (dart:async/zone.dart:1021:19)
#19     _CustomZone.runGuarded (dart:async/zone.dart:923:7)
#20     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:963:23)
#21     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#22     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#23     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:116:13)
#24     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:173:5)
```

## flutter doctor

```
[32m[✓][39m Flutter (Channel unknown, v1.9.1, on Mac OS X 10.14.6 18G87, locale en-IN)
    [32m•[39m Flutter version 1.9.1 at /Users/gurleensethi/Documents/Flutter/flutter
    [32m•[39m Framework revision c382b8e990 (8 days ago), 2019-08-18 15:22:36 -0400
    [32m•[39m Engine revision 5540684152
    [32m•[39m Dart version 2.5.0

[32m[✓][39m Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    [32m•[39m Android SDK at /Users/gurleensethi/Library/Android/sdk
    [32m•[39m Android NDK location not configured (optional; useful for native profiling support)
    [32m•[39m Platform android-28, build-tools 28.0.3
    [32m•[39m Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    [32m•[39m Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
    [32m•[39m All Android licenses accepted.

[32m[✓][39m Xcode - develop for iOS and macOS (Xcode 10.3)
    [32m•[39m Xcode at /Applications/Xcode.app/Contents/Developer
    [32m•[39m Xcode 10.3, Build version 10G8
    [32m•[39m CocoaPods version 1.7.5

[32m[✓][39m Chrome - develop for the web
    [32m•[39m Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[32m[✓][39m Android Studio (version 3.4)
    [32m•[39m Android Studio at /Applications/Android Studio.app/Contents
    [32m•[39m Flutter plugin version 35.3.1
    [32m•[39m Dart plugin version 183.6270
    [32m•[39m Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

[32m[✓][39m IntelliJ IDEA Community Edition (version 2019.2.1)
    [32m•[39m IntelliJ at /Applications/IntelliJ IDEA CE.app
    [32m•[39m Flutter plugin version 38.2.4
    [32m•[39m Dart plugin version 192.6459

[32m[✓][39m VS Code (version 1.37.1)
    [32m•[39m VS Code at /Applications/Visual Studio Code.app/Contents
    [32m•[39m Flutter extension version 3.3.0

[32m[✓][39m Connected device (3 available)
    [32m•[39m ONEPLUS A6010             • 4c7b04d9      • android-arm64  • Android 9 (API 28)
    [32m•[39m Android SDK built for x86 • emulator-5554 • android-x86    • Android 9 (API 28) (emulator)
    [32m•[39m Chrome                    • chrome        • web-javascript • Google Chrome 76.0.3809.100 


[32m•[39m No issues found!
```

**Comment by jonahwilliams** [comment]
I don't know what version this is on, but 1.9.1 is fairly old and there have been many fixes since then. Is this still happening on the latest master?

**Comment by a-h-mzd** [comment]
@jonahwilliams ver1.10.2 problem still exists. please take a look at #40547

**Comment by iapicca** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact descriptions what happens, logs and the output of ' flutter doctor -v'  please.
All system setups can be slightly different so its always better to open new issues and reference related issues.
