### ISSUE TITLE
RenderCustomMultiChildLayoutBox object was given an infinite size during layout.

### ISSUE THREAD

**Issue by zxylovewl1** [flutter/flutter#39317]
```
Performing hot reload...
Syncing files to device MI 8...
Reloaded 0 of 1328 libraries in 329ms.
I/flutter (24931): 1
I/flutter (24931): ══╡ EXCEPTION CAUGHT BY RENDERING LIBRARY ╞═════════════════════════════════════════════════════════
I/flutter (24931): The following assertion was thrown during performLayout():
I/flutter (24931): FlutterError contained multiple error summaries.
I/flutter (24931): All FlutterError objects should have only a single short (one line) summary description of the
I/flutter (24931): problem that was detected.
I/flutter (24931): Malformed FlutterError:
I/flutter (24931):   RenderCustomMultiChildLayoutBox object was given an infinite size during layout.
I/flutter (24931):   This probably means that it is a render object that tries to be as big as possible, but it was put
I/flutter (24931):   inside another render object that allows its children to pick their own size.
I/flutter (24931):   RenderCustomMultiChildLayoutBox object was given an infinite size during layout.
I/flutter (24931):   This probably means that it is a render object that tries to be as big as possible, but it was put
I/flutter (24931):   inside another render object that allows its children to pick their own size.
I/flutter (24931):   The nearest ancestor providing an unbounded height constraint is: RenderIndexedSemantics#2237c relayoutBoundary=up16 NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE:
I/flutter (24931):     creator: IndexedSemantics ← NotificationListener<KeepAliveNotification> ← KeepAlive ←
I/flutter (24931):       AutomaticKeepAlive ← KeyedSubtree ← SliverList ← MediaQuery ← SliverPadding ←
I/flutter (24931):       ShrinkWrappingViewport ← IgnorePointer-[GlobalKey#d7aff] ← Semantics ← Listener ← ⋯
I/flutter (24931):     parentData: index=0; layoutOffset=0.0 (can use size)
I/flutter (24931):     constraints: BoxConstraints(w=392.7, 0.0<=h<=Infinity)
I/flutter (24931):     semantic boundary
I/flutter (24931):     size: MISSING
I/flutter (24931):     index: 0
I/flutter (24931):   The constraints that applied to the RenderCustomMultiChildLayoutBox were:
I/flutter (24931):     BoxConstraints(w=392.7, 0.0<=h<=Infinity)
I/flutter (24931):   The exact size it was given was:
I/flutter (24931):     Size(392.7, Infinity)
I/flutter (24931):   See https://flutter.dev/docs/development/ui/layout/box-constraints for more information.
I/flutter (24931): 
I/flutter (24931): The malformed error has 2 summaries.
I/flutter (24931): Summary 1: RenderCustomMultiChildLayoutBox object was given an infinite size during layout.
I/flutter (24931): Summary 2: RenderCustomMultiChildLayoutBox object was given an infinite size during layout.
I/flutter (24931): 
I/flutter (24931): This error should still help you solve your problem, however please also report this malformed error
I/flutter (24931): in the framework by filing a bug on GitHub:
I/flutter (24931):   https://github.com/flutter/flutter/issues/new?template=BUG.md
I/flutter (24931): 
I/flutter (24931): When the exception was thrown, this was the stack:
I/flutter (24931): #0      new FlutterError.fromParts.<anonymous closure> (package:flutter/src/foundation/assertions.dart:540:9)
I/flutter (24931): #1      new FlutterError.fromParts (package:flutter/src/foundation/assertions.dart:543:6)
I/flutter (24931): #2      RenderBox.debugAssertDoesMeetConstraints.<anonymous closure> (package:flutter/src/rendering/box.dart:1966:28)
I/flutter (24931): #3      RenderBox.debugAssertDoesMeetConstraints (package:flutter/src/rendering/box.dart:2029:6)
I/flutter (24931): #4      RenderBox.size=.<anonymous closure> (package:flutter/src/rendering/box.dart:1740:7)
I/flutter (24931): #5      RenderBox.size= (package:flutter/src/rendering/box.dart:1742:6)
I/flutter (24931): #6      RenderCustomMultiChildLayoutBox.performLayout (package:flutter/src/rendering/custom_layout.dart:355:5)
I/flutter (24931): #7      RenderObject.layout (package:flutter/src/rendering/object.dart:1619:7)
I/flutter (24931): #8      _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter (24931): #9      RenderObject.layout (package:flutter/src/rendering/object.dart:1619:7)
I/flutter (24931): #10     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter (24931): #11     _RenderCustomClip.performLayout (package:flutter/src/rendering/proxy_box.dart:1214:11)
I/flutter (24931): #12     RenderObject.layout (package:flutter/src/rendering/object.dart:1619:7)
I/flutter (24931): #13     RenderPadding.performLayout (package:flutter/src/rendering/shifted_box.dart:206:11)
I/flutter (24931): #14     RenderObject.layout (package:flutter/src/rendering/object.dart:1619:7)
I/flutter (24931): #15     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter (24931): #16     RenderObject.layout (package:flutter/src/rendering/object.dart:1619:7)
I/flutter (24931): #17     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter (24931): #18     RenderObject.layout (package:flutter/src/rendering/object.dart:1619:7)
I/flutter (24931): #19     RenderSliverList.performLayout (package:flutter/src/rendering/sliver_list.dart:165:27)
I/flutter (24931): #20     RenderObject.layout (package:flutter/src/rendering/object.dart:1619:7)
I/flutter (24931): #21     RenderSliverPadding.performLayout (package:flutter/src/rendering/sliver_padding.dart:181:11)
I/flutter (24931): #22     RenderObject.layout (package:flutter/src/rendering/object.dart:1619:7)
I/flutter (24931): #23     RenderViewportBase.layoutChildSequence (package:flutter/src/rendering/viewport.dart:406:13)
I/flutter (24931): #24     RenderShrinkWrappingViewport._attemptLayout (package:flutter/src/rendering/viewport.dart:1663:12)
I/flutter (24931): #25     RenderShrinkWrappingViewport.performLayout (package:flutter/src/rendering/viewport.dart:1626:20)
I/flutter (24931): #26     RenderObject.layout (package:flutter/src/rendering/object.dart:1619:7)
I/flutter (24931): #27     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter (24931): #28     RenderObject.layout (package:flutter/src/rendering/object.dart:1619:7)
I/flutter (24931): #29     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter (24931): #30     RenderObject.layout (package:flutter/src/rendering/object.dart:1619:7)
I/flutter (24931): #31     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter (24931): #32     RenderObject.layout (package:flutter/src/rendering/object.dart:1619:7)
I/flutter (24931): #33     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter (24931): #34     RenderObject.layout (package:flutter/src/rendering/object.dart:1619:7)
I/flutter (24931): #35     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter (24931): #36     RenderObject.layout (package:flutter/src/rendering/object.dart:1619:7)
I/flutter (24931): #37     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter (24931): #38     RenderObject.layout (package:flutter/src/rendering/object.dart:1619:7)
I/flutter (24931): #39     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter (24931): #40     RenderObject.layout (package:flutter/src/rendering/object.dart:1619:7)
I/flutter (24931): #41     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter (24931): #42     RenderObject.layout (package:flutter/src/rendering/object.dart:1619:7)
I/flutter (24931): #43     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter (24931): #44     RenderObject.layout (package:flutter/src/rendering/object.dart:1619:7)
I/flutter (24931): #45     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter (24931): #46     RenderObject.layout (package:flutter/src/rendering/object.dart:1619:7)
I/flutter (24931): #47     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter (24931): #48     RenderObject.layout (package:flutter/src/rendering/object.dart:1619:7)
I/flutter (24931): #49     RenderSliverList.performLayout (package:flutter/src/rendering/sliver_list.dart:165:27)
I/flutter (24931): #50     RenderObject.layout (package:flutter/src/rendering/object.dart:1619:7)
I/flutter (24931): #51     RenderViewportBase.layoutChildSequence (package:flutter/src/rendering/viewport.dart:406:13)
I/flutter (24931): #52     RenderViewport._attemptLayout (package:flutter/src/rendering/viewport.dart:1334:12)
I/flutter (24931): #53     RenderViewport.performLayout (package:flutter/src/rendering/viewport.dart:1252:20)
I/flutter (24931): #54     RenderObject._layoutWithoutResize (package:flutter/src/rendering/object.dart:1496:7)
I/flutter (24931): #55     PipelineOwner.flushLayout (package:flutter/src/rendering/object.dart:765:18)
I/flutter (24931): #56     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding.drawFrame (package:flutter/src/rendering/binding.dart:346:19)
I/flutter (24931): #57     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding&WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:701:13)
I/flutter (24931): #58     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:285:5)
I/flutter (24931): #59     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1016:15)
I/flutter (24931): #60     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:958:9)
I/flutter (24931): #61     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:874:5)
I/flutter (24931): #65     _invoke (dart:ui/hooks.dart:236:10)
I/flutter (24931): #66     _drawFrame (dart:ui/hooks.dart:194:3)
I/flutter (24931): (elided 3 frames from package dart:async)
I/flutter (24931): 
I/flutter (24931): The following RenderObject was being processed when the exception was fired: RenderCustomMultiChildLayoutBox#5d5d6 relayoutBoundary=up21 NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE:
I/flutter (24931):   creator: CustomMultiChildLayout ← AnimatedBuilder ← DefaultTextStyle ← AnimatedDefaultTextStyle ←
I/flutter (24931):     _InkFeatures-[GlobalKey#92cc0 ink renderer] ← NotificationListener<LayoutChangedNotification> ←
I/flutter (24931):     PhysicalModel ← AnimatedPhysicalModel ← Material ← PrimaryScrollController ← _ScaffoldScope ←
I/flutter (24931):     Scaffold ← ⋯
I/flutter (24931):   parentData: <none> (can use size)
I/flutter (24931):   constraints: BoxConstraints(w=392.7, 0.0<=h<=Infinity)
I/flutter (24931):   size: Size(392.7, Infinity)
I/flutter (24931): This RenderObject had the following descendants (showing up to depth 5):
I/flutter (24931):     child 1: RenderFlex#90341 NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
I/flutter (24931):       child 1: RenderPhysicalModel#05bbe NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
I/flutter (24931):         child: _RenderInkFeatures#5ae5d NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
I/flutter (24931):           child: RenderConstrainedBox#fe816 NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
I/flutter (24931):             child: RenderDecoratedBox#238a4 NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
I/flutter (24931):       child 2: RenderRepaintBoundary#44a79 NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
I/flutter (24931):         child: RenderCustomPaint#c510a NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
I/flutter (24931):           child: RenderRepaintBoundary#5fab6 NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
I/flutter (24931):             child: _RenderScrollSemantics#ec5e0 NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
I/flutter (24931):     child 2: RenderStack#7fee3 NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
I/flutter (24931):       child 1: RenderTransform#97873 NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
I/flutter (24931):         child: RenderTransform#eb6d5 NEEDS-LAYOUT NEEDS-PAINT
I/flutter (24931): ════════════════════════════════════════════════════════════════════════════════════════════════════
I/flutter (24931): Another exception was thrown: FlutterError contained multiple error summaries.
I/chatty  (24931): uid=10557(com.qlslylq.flutterdesign.flutter_design) Thread-3 identical 3 lines
I/flutter (24931): Another exception was thrown: FlutterError contained multiple error summaries.
I/flutter (24931): Another exception was thrown: 'package:flutter/src/widgets/scroll_position.dart': Failed assertion: line 457 pos 14: 'minScrollExtent <= maxScrollExtent': is not true.
I/flutter (24931): Another exception was thrown: RenderBox was not laid out: RenderShrinkWrappingViewport#90696 relayoutBoundary=up13 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
I/flutter (24931): Another exception was thrown: RenderBox was not laid out: RenderIgnorePointer#cec5a relayoutBoundary=up12 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
I/flutter (24931): Another exception was thrown: RenderBox was not laid out: RenderSemanticsAnnotations#05e06 relayoutBoundary=up11 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
I/flutter (24931): Another exception was thrown: RenderBox was not laid out: RenderPointerListener#920e3 relayoutBoundary=up10 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
I/flutter (24931): 1
I/flutter (24931): Another exception was thrown: RenderBox was not laid out: RenderSemanticsGestureHandler#0ee01 relayoutBoundary=up9 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
I/flutter (24931): Another exception was thrown: RenderBox was not laid out: RenderPointerListener#c47cb relayoutBoundary=up8 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
I/flutter (24931): Another exception was thrown: RenderBox was not laid out: _RenderScrollSemantics#58227 relayoutBoundary=up7 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
I/flutter (24931): Another exception was thrown: RenderBox was not laid out: RenderRepaintBoundary#e4c62 relayoutBoundary=up6 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
I/flutter (24931): Another exception was thrown: RenderBox was not laid out: RenderCustomPaint#7eadb relayoutBoundary=up5 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
I/flutter (24931): Another exception was thrown: RenderBox was not laid out: RenderRepaintBoundary#6f3a2 relayoutBoundary=up4 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
I/flutter (24931): Another exception was thrown: RenderBox was not laid out: RenderRepaintBoundary#6f3a2 relayoutBoundary=up4 NEEDS-PAINT
```

**Comment by BondarenkoStas** [comment]
The log says that box constraint height was set to infinity which gives infinite size of the box. See https://flutter.dev/community for support options. Closing, as this is not an issue report.
