### ISSUE TITLE
Crash on start after release build of gallery (from mac, to android)

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#3932]
```
05-16 11:18:51.811 10240 10267 F libc    : Fatal signal 5 (SIGTRAP), code 4 in tid 10267 (ui_thread)
05-16 11:18:51.907   194   194 W debuggerd: type=1400 audit(0.0:135): avc: denied { search } for name="io.flutter.gallery" dev="mmcblk0p28" ino=1490949 scontext=u:r:debuggerd:s0 tcontext=u:object_r:app_data_file:s0:c512,c768 tclass=dir permissive=0
05-16 11:18:51.912   194   194 F DEBUG   : *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
05-16 11:18:51.912   194   194 F DEBUG   : Build fingerprint: 'google/hammerhead/hammerhead:6.0.1/MOB30D/2704746:user/release-keys'
05-16 11:18:51.912   194   194 F DEBUG   : Revision: '11'
05-16 11:18:51.912   194   194 F DEBUG   : ABI: 'arm'
05-16 11:18:51.912   194   194 F DEBUG   : pid: 10240, tid: 10267, name: ui_thread  >>> io.flutter.gallery <<<
05-16 11:18:51.912   194   194 F DEBUG   : signal 5 (SIGTRAP), code 4 (TRAP_HWBKPT), fault addr 0x2800
05-16 11:18:51.927   194   194 W debuggerd: type=1400 audit(0.0:136): avc: denied { search } for name="io.flutter.gallery" dev="mmcblk0p28" ino=1490949 scontext=u:r:debuggerd:s0 tcontext=u:object_r:app_data_file:s0:c512,c768 tclass=dir permissive=0
05-16 11:18:51.929   194   194 F DEBUG   :     r0 b366b5ac  r1 b366b5a4  r2 b366b544  r3 b3658000
05-16 11:18:51.929   194   194 F DEBUG   :     r4 b3658000  r5 00000001  r6 a0872570  r7 b366b5ac
05-16 11:18:51.929   194   194 F DEBUG   :     r8 aef7f1d8  r9 aef7f1e8  sl b366b544  fp b366b5a4
05-16 11:18:51.929   194   194 F DEBUG   :     ip a228cbec  sp aef7f1d0  lr a1b33b71  pc a0872570  cpsr 000f0010
05-16 11:18:51.948   194   194 F DEBUG   : 
05-16 11:18:51.948   194   194 F DEBUG   : backtrace:
05-16 11:18:51.948   194   194 F DEBUG   :     #00 pc 00000570  /data/data/io.flutter.gallery/app_sky_shell/snapshot_aot_instr
05-16 11:18:51.948   194   194 F DEBUG   :     #01 pc 003d2b6f  /data/app/io.flutter.gallery-1/lib/arm/libsky_shell.so
05-16 11:18:51.948   194   194 F DEBUG   :     #02 pc 00388359  /data/app/io.flutter.gallery-1/lib/arm/libsky_shell.so
05-16 11:18:51.948   194   194 F DEBUG   :     #03 pc 002f427f  /data/app/io.flutter.gallery-1/lib/arm/libsky_shell.so
05-16 11:18:51.949   194   194 F DEBUG   :     #04 pc 002f42b9  /data/app/io.flutter.gallery-1/lib/arm/libsky_shell.so
05-16 11:18:51.949   194   194 F DEBUG   :     #05 pc 002f4615  /data/app/io.flutter.gallery-1/lib/arm/libsky_shell.so
05-16 11:18:51.949   194   194 F DEBUG   :     #06 pc 00474eb7  /data/app/io.flutter.gallery-1/lib/arm/libsky_shell.so
05-16 11:18:51.949   194   194 F DEBUG   :     #07 pc 002f3ee7  /data/app/io.flutter.gallery-1/lib/arm/libsky_shell.so
05-16 11:18:51.949   194   194 F DEBUG   :     #08 pc 00081419  /data/app/io.flutter.gallery-1/lib/arm/libsky_shell.so
05-16 11:18:51.949   194   194 F DEBUG   :     #09 pc 00358699  /data/app/io.flutter.gallery-1/lib/arm/libsky_shell.so
05-16 11:18:51.949   194   194 F DEBUG   :     #10 pc 002c793b  /data/app/io.flutter.gallery-1/lib/arm/libsky_shell.so
05-16 11:18:51.949   194   194 F DEBUG   :     #11 pc 002c73c1  /data/app/io.flutter.gallery-1/lib/arm/libsky_shell.so
05-16 11:18:51.949   194   194 F DEBUG   :     #12 pc 002c75a3  /data/app/io.flutter.gallery-1/lib/arm/libsky_shell.so
05-16 11:18:51.950   194   194 F DEBUG   :     #13 pc 002c75f3  /data/app/io.flutter.gallery-1/lib/arm/libsky_shell.so
05-16 11:18:51.950   194   194 F DEBUG   :     #14 pc 000b07a5  /data/app/io.flutter.gallery-1/lib/arm/libsky_shell.so
05-16 11:18:51.950   194   194 F DEBUG   :     #15 pc 000b17d1  /data/app/io.flutter.gallery-1/lib/arm/libsky_shell.so
05-16 11:18:51.950   194   194 F DEBUG   :     #16 pc 000b1a31  /data/app/io.flutter.gallery-1/lib/arm/libsky_shell.so
05-16 11:18:51.950   194   194 F DEBUG   :     #17 pc 000b1b17  /data/app/io.flutter.gallery-1/lib/arm/libsky_shell.so
05-16 11:18:51.950   194   194 F DEBUG   :     #18 pc 00094859  /data/app/io.flutter.gallery-1/lib/arm/libsky_shell.so
05-16 11:18:51.951   194   194 F DEBUG   :     #19 pc 00090ead  /data/app/io.flutter.gallery-1/lib/arm/libsky_shell.so
05-16 11:18:51.951   194   194 F DEBUG   :     #20 pc 0009c22d  /data/app/io.flutter.gallery-1/lib/arm/libsky_shell.so
05-16 11:18:51.951   194   194 F DEBUG   :     #21 pc 0009b715  /data/app/io.flutter.gallery-1/lib/arm/libsky_shell.so
05-16 11:18:51.951   194   194 F DEBUG   :     #22 pc 0003f45f  /system/lib/libc.so (__pthread_start(void*)+30)
05-16 11:18:51.951   194   194 F DEBUG   :     #23 pc 00019b43  /system/lib/libc.so (__start_thread+6)
05-16 11:18:52.052   801  1062 D ConnectivityService: updateNetworkScore for NetworkAgentInfo [WIFI () - 112] to 55
05-16 11:18:52.409   801 10283 W ActivityManager:   Force finishing activity io.flutter.gallery/org.domokit.sky.shell.SkyActivity
05-16 11:18:52.409   194   194 F DEBUG   : 
05-16 11:18:52.409   194   194 F DEBUG   : Tombstone written to: /data/tombstones/tombstone_04
05-16 11:18:52.409   194   194 E DEBUG   : AM write failed: Broken pipe
05-16 11:18:52.409   801   817 I BootReceiver: Copying /data/tombstones/tombstone_04 to DropBox (SYSTEM_TOMBSTONE)
05-16 11:18:52.465   801   899 I OpenGLRenderer: Initialized EGL, version 1.4
05-16 11:18:52.503   801  1170 D GraphicsStats: Buffer count: 4
05-16 11:18:52.504   801  5703 I WindowState: WIN DEATH: Window{331a39 u0 SurfaceView}
05-16 11:18:52.505   801   811 I WindowState: WIN DEATH: Window{48fa7f7 u0 io.flutter.gallery/org.domokit.sky.shell.SkyActivity}
05-16 11:18:52.530   208   208 I Zygote  : Process 10240 exited due to signal (5)
05-16 11:18:52.532   801   810 I art     : Background partial concurrent mark sweep GC freed 38666(2MB) AllocSpace objects, 21(2036KB) LOS objects, 32% free, 33MB/49MB, paused 1.165ms total 109.513ms
05-16 11:18:52.547   801  5699 I ActivityManager: Process io.flutter.gallery (pid 10240) has died
05-16 11:18:53.031   801   819 W WindowAnimator: Failed to dispatch window animation state change.
05-16 11:18:53.031   801   819 W WindowAnimator: android.os.DeadObjectException
05-16 11:18:53.031   801   819 W WindowAnimator: 	at android.os.BinderProxy.transactNative(Native Method)
05-16 11:18:53.031   801   819 W WindowAnimator: 	at android.os.BinderProxy.transact(Binder.java:503)
05-16 11:18:53.031   801   819 W WindowAnimator: 	at android.view.IWindow$Stub$Proxy.onAnimationStopped(IWindow.java:534)
05-16 11:18:53.031   801   819 W WindowAnimator: 	at com.android.server.wm.WindowAnimator.updateWindowsLocked(WindowAnimator.java:286)
05-16 11:18:53.031   801   819 W WindowAnimator: 	at com.android.server.wm.WindowAnimator.animateLocked(WindowAnimator.java:678)
05-16 11:18:53.031   801   819 W WindowAnimator: 	at com.android.server.wm.WindowAnimator.-wrap0(WindowAnimator.java)
05-16 11:18:53.031   801   819 W WindowAnimator: 	at com.android.server.wm.WindowAnimator$1.doFrame(WindowAnimator.java:123)
05-16 11:18:53.031   801   819 W WindowAnimator: 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:856)
05-16 11:18:53.031   801   819 W WindowAnimator: 	at android.view.Choreographer.doCallbacks(Choreographer.java:670)
05-16 11:18:53.031   801   819 W WindowAnimator: 	at android.view.Choreographer.doFrame(Choreographer.java:603)
05-16 11:18:53.031   801   819 W WindowAnimator: 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:844)
05-16 11:18:53.031   801   819 W WindowAnimator: 	at android.os.Handler.handleCallback(Handler.java:739)
05-16 11:18:53.031   801   819 W WindowAnimator: 	at android.os.Handler.dispatchMessage(Handler.java:95)
05-16 11:18:53.031   801   819 W WindowAnimator: 	at android.os.Looper.loop(Looper.java:148)
05-16 11:18:53.031   801   819 W WindowAnimator: 	at android.os.HandlerThread.run(HandlerThread.java:61)
05-16 11:18:53.031   801   819 W WindowAnimator: 	at com.android.server.ServiceThread.run(ServiceThread.java:46)
05-16 11:18:53.032   801   819 W WindowAnimator: Failed to dispatch window animation state change.
05-16 11:18:53.032   801   819 W WindowAnimator: android.os.DeadObjectException
05-16 11:18:53.032   801   819 W WindowAnimator: 	at android.os.BinderProxy.transactNative(Native Method)
05-16 11:18:53.032   801   819 W WindowAnimator: 	at android.os.BinderProxy.transact(Binder.java:503)
05-16 11:18:53.032   801   819 W WindowAnimator: 	at android.view.IWindow$Stub$Proxy.onAnimationStopped(IWindow.java:534)
05-16 11:18:53.032   801   819 W WindowAnimator: 	at com.android.server.wm.WindowAnimator.updateWindowsLocked(WindowAnimator.java:286)
05-16 11:18:53.032   801   819 W WindowAnimator: 	at com.android.server.wm.WindowAnimator.animateLocked(WindowAnimator.java:678)
05-16 11:18:53.032   801   819 W WindowAnimator: 	at com.android.server.wm.WindowAnimator.-wrap0(WindowAnimator.java)
05-16 11:18:53.032   801   819 W WindowAnimator: 	at com.android.server.wm.WindowAnimator$1.doFrame(WindowAnimator.java:123)
05-16 11:18:53.032   801   819 W WindowAnimator: 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:856)
05-16 11:18:53.032   801   819 W WindowAnimator: 	at android.view.Choreographer.doCallbacks(Choreographer.java:670)
05-16 11:18:53.032   801   819 W WindowAnimator: 	at android.view.Choreographer.doFrame(Choreographer.java:603)
05-16 11:18:53.032   801   819 W WindowAnimator: 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:844)
05-16 11:18:53.032   801   819 W WindowAnimator: 	at android.os.Handler.handleCallback(Handler.java:739)
05-16 11:18:53.032   801   819 W WindowAnimator: 	at android.os.Handler.dispatchMessage(Handler.java:95)
05-16 11:18:53.032   801   819 W WindowAnimator: 	at android.os.Looper.loop(Looper.java:148)
05-16 11:18:53.032   801   819 W WindowAnimator: 	at android.os.HandlerThread.run(HandlerThread.java:61)
05-16 11:18:53.032   801   819 W WindowAnimator: 	at com.android.server.ServiceThread.run(ServiceThread.java:46)
05-16 11:18:54.344   801  5699 W InputMethodManagerService: Got RemoteException sending setActive(false) notification to pid 10240 uid 10116
05-16 11:18:54.346   197   782 D audio_hw_primary: out_set_parameters: enter: usecase(1: low-latency-playback) kvpairs: routing=2
05-16 11:18:54.530   801   819 W AppOps  : Finishing op nesting under-run: uid 1000 pkg android code 24 time=0 duration=0 nesting=0
05-16 11:18:55.069   801  1062 D ConnectivityService: updateNetworkScore for NetworkAgentInfo [WIFI () - 112] to 56
05-16 11:18:55.907   801 30491 D NetlinkSocketObserver: NeighborEvent{elapsedMs=1642506353, 100.110.127.254, [00005E000165], RTM_NEWNEIGH, NUD_STALE}
05-16 11:18:57.513   197   782 D audio_hw_primary: disable_audio_route: reset and update mixer path: low-latency-playback
05-16 11:18:57.513   197   782 D audio_hw_primary: disable_snd_device: snd_device(2: speaker)
05-16 11:18:58.875 25200 25238 I Finsky  : [4580] com.google.android.finsky.c.e.run(1151): Replicating app states via AMAS.
05-16 11:18:59.006 25200 25238 I Finsky  : [4580] com.google.android.finsky.c.c.a(311): Completed 0 account content syncs with 0 successful.
05-16 11:18:59.007 25200 25200 I Finsky  : [1] com.google.android.finsky.services.j.a(149): Installation state replication succeeded.
05-16 11:19:07.183   801  1062 D ConnectivityService: updateNetworkScore for NetworkAgentInfo [WIFI () - 112] to 55
05-16 11:19:10.217   801  1062 D ConnectivityService: updateNetworkScore for NetworkAgentInfo [WIFI () - 112] to 56
05-16 11:19:19.303   801  1062 D ConnectivityService: updateNetworkScore for NetworkAgentInfo [WIFI () - 112] to 55
05-16 11:19:22.338   801  1062 D ConnectivityService: updateNetworkScore for NetworkAgentInfo [WIFI () - 112] to 56
05-16 11:19:22.473   207   282 I ThermalEngine: TM Id 'SKIN_THERMAL_management_1' Sensor 'xo_therm_pu2' - alarm cleared 1 at 38.0 degC
05-16 11:19:22.473   207   282 I ThermalEngine: ACTION: CPU - Setting CPU[0] to 2265600
05-16 11:19:22.474   207   282 I ThermalEngine: ACTION: CPU - Setting CPU[1] to 2265600
05-16 11:19:22.474   207   282 I ThermalEngine: ACTION: CPU - Setting CPU[2] to 2265600
05-16 11:19:22.474   207   282 I ThermalEngine: ACTION: CPU - Setting CPU[3] to 2265600
05-16 11:19:22.475   207   282 I ThermalEngine: ACTION: LCD - Setting max LCD brightness to 255
05-16 11:19:25.371   801  1062 D ConnectivityService: updateNetworkScore for NetworkAgentInfo [WIFI () - 112] to 55
05-16 11:19:28.406   801  1062 D ConnectivityService: updateNetworkScore for NetworkAgentInfo [WIFI () - 112] to 56
```

**Comment by sethladd** [comment]
cc @jason-simmons

**Comment by sethladd** [comment]
```
~/Code/flutter/examples/flutter_gallery[master] $ flutter --version
Flutter on channel master (from git@github.com:flutter/flutter.git)
Framework revision c5ff156f24 (13 minutes ago); engine revision a1f4a12baa
```

**Comment by sethladd** [comment]
Can't repro.
