### ISSUE TITLE
Return a non-empty response from setResourceCacheMaxBytes

### ISSUE THREAD

**Issue by abhishekamit** [flutter/flutter#39337]
The empty reply added to this channel in https://github.com/flutter/engine/pull/10434 ends up throwing this exception: https://github.com/flutter/flutter/blob/93c32c4ff667d82136dcc1f8ecef1b0ab993a047/packages/flutter/lib/src/services/platform_channel.dart#L319

Sorry, should have thought of this earlier. Can we add a non-empty reply to avoid the exception? Empty string instead of null?

/cc @dnfield

**Comment by abhishekamit** [comment]
Sorry, looks like this triggered a new issue:
```
08-29 09:28:30.088 10314 10337 E flutter : [ERROR:flutter/lib/ui/ui_dart_state.cc(148)] Unhandled Exception: FormatException: Unexpected character (at character 1)
08-29 09:28:30.088 10314 10337 E flutter : 
08-29 09:28:30.088 10314 10337 E flutter : ^
08-29 09:28:30.088 10314 10337 E flutter : 
08-29 09:28:30.088 10314 10337 E flutter : #0      _ChunkedJsonParser.fail (dart:convert-patch/convert_patch.dart:1392:5)
08-29 09:28:30.088 10314 10337 E flutter : #1      _ChunkedJsonParser.parseNumber (dart:convert-patch/convert_patch.dart:1259:9)
08-29 09:28:30.088 10314 10337 E flutter : #2      _ChunkedJsonParser.parse (dart:convert-patch/convert_patch.dart:924:22)
08-29 09:28:30.088 10314 10337 E flutter : #3      _parseJson (dart:convert-patch/convert_patch.dart:29:10)
08-29 09:28:30.088 10314 10337 E flutter : #4      JsonDecoder.convert (dart:convert/json.dart:493:36)
08-29 09:28:30.088 10314 10337 E flutter : #5      JsonCodec.decode (dart:convert/json.dart:151:41)
08-29 09:28:30.088 10314 10337 E flutter : #6      JSONMessageCodec.decodeMessage (package:flutter/src/services/message_codecs.dart:93:17)
08-29 09:28:30.088 10314 10337 E flutter : #7      JSONMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:141:54)
08-29 09:28:30.088 10314 10337 E flutter : #8      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:321:33)
08-29 09:28:30.088 10314 10337 E flutter : <asynchronous suspension>
```

The line before this in the stack trace was `await SystemChannels.skia.invokeMethod('Skia.setResourceCacheMaxBytes', 1024 * 1024 * 512);`

So it looks like the response must be valid JSON.

**Comment by dnfield** [comment]
Ahh right because it's a json codec channel.

Ok.  This is an easy fix.
