### ISSUE TITLE
onActivityResult can't triggered when add flutter module to android project.

### ISSUE THREAD

**Issue by longdw** [flutter/flutter#39384]
## Steps to Reproduce
1. add a plugin created myself to flutter module project 
2. run it, and onActivityResult can invoke
3. add flutter module project to android
4. run it, and onActivityResult can't invoke

```
[✓] Flutter (Channel master, v1.9.1-pre.58, on Mac OS X 10.13.6 17G2307, locale
    zh-Hans-CN)
    • Flutter version 1.9.1-pre.58 at /Users/longdw/flutter
    • Framework revision bc95f0881c (12 days ago), 2019-08-16 03:14:36 -0400
    • Engine revision bfa9be9978
    • Dart version 2.5.0 (build 2.5.0-dev.2.1 e35e8833ee)


[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/longdw/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling
      support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 10.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.0, Build version 10A255
    • CocoaPods version 1.6.1

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 38.2.3
    • Dart plugin version 191.8423
    • Java version OpenJDK Runtime Environment (build
      1.8.0_202-release-1483-b49-5587405)
```

these are demo projects, 
1. flutter module with a simple plugin, look at [testplugin](https://github.com/longdw/testplugin)
2. android project with flutter module, look at [TestPluginAndroid](https://github.com/longdw/TestPluginAndroid)

@xster

**Comment by longdw** [comment]
https://github.com/flutter/flutter/wiki/Experimental:-Adding-Flutter-to-Android  this is experimental, is there a stable way now? I want to use flutter module in my production code, now 90% of the work has been done, some minor bugs as I have posted above have prevented me from working now.

And this issue https://github.com/flutter/flutter/issues/38730 also have not a appropriate method to `setInitialRoute`

@xster

**Comment by longdw** [comment]
I try to follow the wiki guide and use

```
Intent defaultFlutter = FlutterActivity.createDefaultIntent(MainActivity.this);
startActivity(defaultFlutter);
```
but app crashed and throws these erros:

```
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.david.testpluginandroid/io.flutter.embedding.android.FlutterActivity}: java.lang.IllegalStateException: ensureInitializationComplete must be called after startInitialization
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2913)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3048)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1808)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6669)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
     Caused by: java.lang.IllegalStateException: ensureInitializationComplete must be called after startInitialization
        at io.flutter.view.FlutterMain.ensureInitializationComplete(FlutterMain.java:168)
        at io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.initializeFlutter(FlutterActivityAndFragmentDelegate.java:177)
        at io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.onAttach(FlutterActivityAndFragmentDelegate.java:140)
        at io.flutter.embedding.android.FlutterActivity.onCreate(FlutterActivity.java:399)
        at android.app.Activity.performCreate(Activity.java:7136)
        at android.app.Activity.performCreate(Activity.java:7127)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1271)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2893)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3048) 
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78) 
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1808) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:193) 
        at android.app.ActivityThread.main(ActivityThread.java:6669) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858) 
```

@dnfield  @xster  @RedBrogdon @zoechi

**Comment by longdw** [comment]
I followed https://github.com/flutter/flutter/wiki/Experimental:-Add-Flutter-View and used this method in my activity:
```
private void init() {

        FlutterMain.startInitialization(getApplicationContext());
        FlutterMain.ensureInitializationComplete(getApplicationContext(), null);

        FlutterEngine flutterEngine = new FlutterEngine(this);

        flutterEngine
                .getDartExecutor()
                .executeDartEntrypoint(
                        DartExecutor.DartEntrypoint.createDefault()
                );

        FlutterView flutterView = new FlutterView(this);
        flutterView.attachToFlutterEngine(flutterEngine);
        flutterEngine.getNavigationChannel().pushRoute("route");

        FrameLayout.LayoutParams layoutParams = new FrameLayout.LayoutParams(ViewGroup.LayoutParams.MATCH_PARENT, ViewGroup.LayoutParams.MATCH_PARENT);
        mRootView.addView(flutterView, layoutParams);
    }
```

but it also throwed errors:
```
java.lang.NoClassDefFoundError: Failed resolution of: Landroidx/lifecycle/DefaultLifecycleObserver;
        at io.flutter.embedding.engine.FlutterEngine.<init>(FlutterEngine.java:152)
        at com.david.testpluginandroid.OtherActivity.init(OtherActivity.java:49)
        at com.david.testpluginandroid.OtherActivity.onCreate(OtherActivity.java:40)
        at android.app.Activity.performCreate(Activity.java:7136)
        at android.app.Activity.performCreate(Activity.java:7127)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1271)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2893)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3048)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1808)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6669)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
     Caused by: java.lang.ClassNotFoundException: Didn't find class "androidx.lifecycle.DefaultLifecycleObserver"
```

**Comment by longdw** [comment]
I found a temporary solution, override `onActivityResult` in Activity,  and do it the following way:

```
@Override
    protected void onActivityResult(int requestCode, int resultCode, @Nullable Intent data) {

        mFlutterView.getPluginRegistry().onActivityResult(requestCode, resultCode, data);
}
```

**Comment by matthew-carroll** [comment]
Hi @longdw are you still experiencing any issues, or should we close this ticket?

We have a number of guides that now show developers how to use the v2 Android embedding:

https://flutter.dev/docs/development/add-to-app/android/project-setup

https://flutter.dev/docs/development/add-to-app/android/add-flutter-screen

https://flutter.dev/docs/development/add-to-app/android/add-flutter-fragment
