### ISSUE TITLE
Failed assertion: line 253 pos 10: 'data != null' A non-null String must be provided to a Text widget.

### ISSUE THREAD

**Issue by Ali-NS** [flutter/flutter#39412]
Hi,  
I have a problem with an app that's already running on android device.
1. Running command 'flutter run' done, build apk on android device is success.
2. Running the apps on android device is not problem, but after pushing 'Save' button there's appear a error message.

![Screenshot_20190828-225641](https://user-images.githubusercontent.com/53884434/63873922-b522d580-c9ea-11e9-948c-706358baa880.jpg)

3. Check database, input data success to database. 

##main.dart

```
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'dart:async';
import 'dart:convert';
import 'package:http/http.dart' as http;

class Response {
  final String status;
  final String message;

  Response({this.status, this.message});

  factory Response.fromJson(Map<String, dynamic> json) {
    return Response(
      status: json['status'],
      message: json['message'],
    );
  }
}

Future<Response> post(String url,var body)async{
  return await http
      .post(Uri.encodeFull(url), body: body, headers: {"Accept":"application/json"})
      .then((http.Response response) {

    final int statusCode = response.statusCode;

    if (statusCode < 200 || statusCode > 400 || json == null) {
      throw new Exception("Error while fetching data");
    }
    return Response.fromJson(json.decode(response.body));
  });
}

class EntryData extends StatefulWidget {
  @override
  EntryDataState createState() => new EntryDataState();
}

class EntryDataState extends State<EntryData> {

  // text field
  final _idController = TextEditingController();
  final _namaController = TextEditingController();
  final _nomorController = TextEditingController();
  
  // member simpan data
  String _response = '';
  bool apiCall = false;
  // widget simpan data
  Widget getProperWidget(){
    if(apiCall)
      return AlertDialog(
        content: new Column(
          children: <Widget>[
            CircularProgressIndicator(),
            Text("Please wait")
          ],
        )
      );
    else
      return Center(
        child: Text(
          _response,
          style: new TextStyle(fontSize: 15.0)
        )
      );
  }
  
  void _callPostAPI() {
    post(
        "http://192.168.1.1/restci/contact",
        {
          "id": _idController.text,
          "nama": _namaController.text,
          "nomor": _nomorController.text
        }).then((response) {

          setState(() {
            apiCall = false;
            _response = response.message;
          });

        },

        onError: (error) {
          apiCall = false;
          _response = error.toString();
        }
    );
  }
  
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('Contact'),
      ),
      body: SafeArea(
          child: ListView(
            padding: EdgeInsets.fromLTRB(20.0, 10.0, 20.0, 10.0),
            children: <Widget>[
              // text field
              TextField(
                controller: _idController,
                decoration: InputDecoration(
                  filled: false,
                  labelText: 'ID',
                ),
              ),
              // spacer
              SizedBox(height: 5.0),
              // text field
              TextField(
                controller: _namaController,
                decoration: InputDecoration(
                  filled: false,
                  labelText: 'Nama',
                ),
              ),
			  // spacer
              SizedBox(height: 5.0),
              // text field
              TextField(
                controller: _nomorController,
                decoration: InputDecoration(
                  filled: false,
                  labelText: 'Nomor',
                ),
              ),
              
			 // button
              RaisedButton(
                child: Text('SIMPAN'),
                onPressed: () {

                  setState((){
                    apiCall=true; // Set state like this
                  });

                  _callPostAPI();
                  },

              ),

              // POST Response
              getProperWidget(),

            ],
          )
      ),
    );
  }
}

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {

  @override
  Widget build(BuildContext context) {

    return MaterialApp(
      title: 'Entry Data Example',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: new EntryData(),
    );
  }
}

```
##Flutter Run
```
C:\src\AndroidStudioProjects\contact>flutter run
Launching lib/main.dart on SM J701F in debug mode...
Initializing gradle...                                              1.0s
Resolving dependencies...                                           3.5s
Running Gradle task 'assembleDebug'...
Running Gradle task 'assembleDebug'... Done                        17.4s
Built build\app\outputs\apk\debug\app-debug.apk.
Installing build\app\outputs\apk\app.apk...                        13.6s
D/SurfaceView(17817): surfaceChanged (720,1280) 1 #8 io.flutter.view.FlutterView{3d7ee7b VFE...... ......ID 0,0-720,1280}
D/ViewRootImpl@b34fb5f[MainActivity](17817): Relayout returned: old=[0,0][720,1280] new=[0,0][720,1280] result=0x3 surface={true 3823630336} changed=false
D/vndksupport(17817): Loading /vendor/lib/hw/android.hardware.graphics.mapper@2.0-impl.so from current namespace instead of sphal namespace.
D/ViewRootImpl@b34fb5f[MainActivity](17817): MSG_RESIZED: frame=[0,0][720,1280] ci=[0,48][0,0] vi=[0,48][0,0] or=1
D/ViewRootImpl@b34fb5f[MainActivity](17817): MSG_WINDOW_FOCUS_CHANGED 1 1
D/InputMethodManager(17817): prepareNavigationBarInfo() DecorView@4a029ac[MainActivity]
D/InputMethodManager(17817): getNavigationBarColor() -855310
D/InputMethodManager(17817): prepareNavigationBarInfo() DecorView@4a029ac[MainActivity]
D/InputMethodManager(17817): getNavigationBarColor() -855310
V/InputMethodManager(17817): Starting input: tba=com.example.contact ic=null mNaviBarColor -855310 mIsGetNaviBarColorSuccess true , NavVisible : true , NavTrans : false
D/InputMethodManager(17817): startInputInner - Id : 0
I/InputMethodManager(17817): startInputInner - mService.startInputOrWindowGainedFocus
D/InputTransport(17817): Input channel constructed: fd=90
D/InputMethodManager(17817): prepareNavigationBarInfo() DecorView@4a029ac[MainActivity]
D/InputMethodManager(17817): getNavigationBarColor() -855310
V/InputMethodManager(17817): Starting input: tba=com.example.contact ic=null mNaviBarColor -855310 mIsGetNaviBarColorSuccess true , NavVisible : true , NavTrans : false
D/InputMethodManager(17817): startInputInner - Id : 0
Syncing files to device SM J701F...
 3,540ms (!)

🔥  To hot reload changes while running, press "r". To hot restart (and rebuild state), press "R".
An Observatory debugger and profiler on SM J701F is available at: http://127.0.0.1:50759/JL99-Ll5Jy8=/
For a more detailed help message, press "h". To detach, press "d"; to quit, press "q".
D/ViewRootImpl@b34fb5f[MainActivity](17817): ViewPostIme pointer 0
D/ViewRootImpl@b34fb5f[MainActivity](17817): ViewPostIme pointer 1
D/InputMethodManager(17817): SSI - flag : 0 Pid : 17817 view : com.example.contact
D/InputMethodManager(17817): prepareNavigationBarInfo() DecorView@4a029ac[MainActivity]
D/InputMethodManager(17817): getNavigationBarColor() -855310
V/InputMethodManager(17817): Starting input: tba=com.example.contact ic=io.flutter.plugin.editing.InputConnectionAdaptor@800c6e5 mNaviBarColor -855310 mIsGetNaviBarColorSuccess true , NavVisible : true , NavTrans : false
D/InputMethodManager(17817): startInputInner - Id : 0
I/InputMethodManager(17817): startInputInner - mService.startInputOrWindowGainedFocus
D/InputTransport(17817): Input channel constructed: fd=93
D/InputTransport(17817): Input channel destroyed: fd=90
D/InputMethodManager(17817): prepareNavigationBarInfo() DecorView@4a029ac[MainActivity]
D/InputMethodManager(17817): getNavigationBarColor() -855310
D/ViewRootImpl@b34fb5f[MainActivity](17817): MSG_RESIZED: frame=[0,0][720,1280] ci=[0,48][0,618] vi=[0,48][0,618] or=1
D/ViewRootImpl@b34fb5f[MainActivity](17817): Relayout returned: old=[0,0][720,1280] new=[0,0][720,1280] result=0x1 surface={true 3823630336} changed=false
D/ViewRootImpl@b34fb5f[MainActivity](17817): ViewPostIme pointer 0
D/ViewRootImpl@b34fb5f[MainActivity](17817): ViewPostIme pointer 1
D/InputMethodManager(17817): prepareNavigationBarInfo() DecorView@4a029ac[MainActivity]
D/InputMethodManager(17817): getNavigationBarColor() -855310
V/InputMethodManager(17817): Starting input: tba=com.example.contact ic=io.flutter.plugin.editing.InputConnectionAdaptor@a446447 mNaviBarColor -855310 mIsGetNaviBarColorSuccess true , NavVisible : true , NavTrans : false
D/InputMethodManager(17817): startInputInner - Id : 0
I/InputMethodManager(17817): startInputInner - mService.startInputOrWindowGainedFocus
D/InputTransport(17817): Input channel constructed: fd=90
D/InputTransport(17817): Input channel destroyed: fd=93
D/InputMethodManager(17817): SSI - flag : 0 Pid : 17817 view : com.example.contact
D/InputMethodManager(17817): prepareNavigationBarInfo() DecorView@4a029ac[MainActivity]
D/InputMethodManager(17817): getNavigationBarColor() -855310
D/ViewRootImpl@b34fb5f[MainActivity](17817): ViewPostIme pointer 0
D/ViewRootImpl@b34fb5f[MainActivity](17817): ViewPostIme pointer 1
D/InputMethodManager(17817): prepareNavigationBarInfo() DecorView@4a029ac[MainActivity]
D/InputMethodManager(17817): getNavigationBarColor() -855310
V/InputMethodManager(17817): Starting input: tba=com.example.contact ic=io.flutter.plugin.editing.InputConnectionAdaptor@129ed9d mNaviBarColor -855310 mIsGetNaviBarColorSuccess true , NavVisible : true , NavTrans : false
D/InputMethodManager(17817): startInputInner - Id : 0
I/InputMethodManager(17817): startInputInner - mService.startInputOrWindowGainedFocus
D/InputTransport(17817): Input channel constructed: fd=93
D/InputTransport(17817): Input channel destroyed: fd=90
D/InputMethodManager(17817): SSI - flag : 0 Pid : 17817 view : com.example.contact
D/InputMethodManager(17817): prepareNavigationBarInfo() DecorView@4a029ac[MainActivity]
D/InputMethodManager(17817): getNavigationBarColor() -855310
D/InputMethodManager(17817): HSIFW - flag : 0 Pid : 17817
D/ViewRootImpl@b34fb5f[MainActivity](17817): MSG_RESIZED: frame=[0,0][720,1280] ci=[0,48][0,0] vi=[0,48][0,0] or=1
D/ViewRootImpl@b34fb5f[MainActivity](17817): Relayout returned: old=[0,0][720,1280] new=[0,0][720,1280] result=0x1 surface={true 3823630336} changed=false
D/ViewRootImpl@b34fb5f[MainActivity](17817): ViewPostIme pointer 0
D/ViewRootImpl@b34fb5f[MainActivity](17817): ViewPostIme pointer 1
I/flutter (17817): ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
I/flutter (17817): The following assertion was thrown building EntryData(dirty, state: EntryDataState#51fa4):
I/flutter (17817): A non-null String must be provided to a Text widget.
I/flutter (17817): 'package:flutter/src/widgets/text.dart':
I/flutter (17817): Failed assertion: line 253 pos 10: 'data != null'
I/flutter (17817):
I/flutter (17817): Either the assertion indicates an error in the framework itself, or we should provide substantially
I/flutter (17817): more information in this error message to help you determine and fix the underlying cause.
I/flutter (17817): In either case, please report this assertion by filing a bug on GitHub:
I/flutter (17817):   https://github.com/flutter/flutter/issues/new?template=BUG.md
I/flutter (17817):
I/flutter (17817): When the exception was thrown, this was the stack:
I/flutter (17817): #2      new Text (package:flutter/src/widgets/text.dart:253:10)
I/flutter (17817): #3      EntryDataState.getProperWidget (package:contact/main.dart:63:16)
I/flutter (17817): #4      EntryDataState.build (package:contact/main.dart:147:15)
I/flutter (17817): #5      StatefulElement.build (package:flutter/src/widgets/framework.dart:4012:27)
I/flutter (17817): #6      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3924:15)
I/flutter (17817): #7      Element.rebuild (package:flutter/src/widgets/framework.dart:3721:5)
I/flutter (17817): #8      BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2340:33)
I/flutter (17817): #9      _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding&WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:700:20)
I/flutter (17817): #10     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:285:5)I/flutter (17817): #11     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1016:15)
I/flutter (17817): #12     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:958:9)
I/flutter (17817): #13     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:874:5)
I/flutter (17817): #17     _invoke (dart:ui/hooks.dart:236:10)
I/flutter (17817): #18     _drawFrame (dart:ui/hooks.dart:194:3)
I/flutter (17817): (elided 5 frames from class _AssertionError and package dart:async)
I/flutter (17817): ════════════════════════════════════════════════════════════════════════════════════════════════════
D/ViewRootImpl@b34fb5f[MainActivity](17817): MSG_WINDOW_FOCUS_CHANGED 0 1
D/InputMethodManager(17817): prepareNavigationBarInfo() DecorView@4a029ac[MainActivity]
D/InputMethodManager(17817): getNavigationBarColor() -855310
D/ViewRootImpl@b34fb5f[MainActivity](17817): stopped(true) old=false
D/SurfaceView(17817): windowStopped(true) false io.flutter.view.FlutterView{3d7ee7b VFE...... .F....I. 0,0-720,1280} of ViewRootImpl@b34fb5f[MainActivity]
D/SurfaceView(17817): show() Surface(name=SurfaceView - com.example.contact/com.example.contact.MainActivity@3d7ee7b@0[17817])/@0xbbc3498 io.flutter.view.FlutterView{3d7ee7b VFE...... .F....I. 0,0-720,1280}
D/SurfaceView(17817): surfaceDestroyed callback.size 1 #1 io.flutter.view.FlutterView{3d7ee7b VFE...... .F....I. 0,0-720,1280}
W/libEGL  (17817): EGLNativeWindowType 0xebd6c008 disconnect failed
D/SurfaceView(17817): destroy() Surface(name=SurfaceView - com.example.contact/com.example.contact.MainActivity@3d7ee7b@0[17817])/@0xbbc3498 io.flutter.view.FlutterView{3d7ee7b VFE...... .F....I. 0,0-720,1280}
D/SurfaceView(17817): onWindowVisibilityChanged(4) false io.flutter.view.FlutterView{3d7ee7b VFE...... .F....I. 0,0-720,1280} of ViewRootImpl@b34fb5f[MainActivity]
W/libEGL  (17817): EGLNativeWindowType 0xe3e7f808 disconnect failed
D/OpenGLRenderer(17817): eglDestroySurface = 0xeb54e060, 0xe3e7f800
D/ViewRootImpl@b34fb5f[MainActivity](17817): Relayout returned: old=[0,0][720,1280] new=[0,0][720,1280] result=0x5 surface={false 0} changed=true
D/InputTransport(17817): Input channel destroyed: fd=93
D/SurfaceView(17817): onWindowVisibilityChanged(8) false io.flutter.view.FlutterView{3d7ee7b VFE...... .F....I. 0,0-720,1280} of ViewRootImpl@b34fb5f[MainActivity]
D/ViewRootImpl@b34fb5f[MainActivity](17817): Relayout returned: old=[0,0][720,1280] new=[0,0][720,1280] result=0x1 surface={false 0} changed=false
Lost connection to device.

C:\src\AndroidStudioProjects\contact>
```

**Comment by goderbauer** [comment]
This is probably a bug in your code:

```
_response = response.message;
```

this line probably sets _rseponse to null in certain cases and Text(null) is not allowed.

**Comment by sunaarun** [comment]
I have the same problem , and my String has a value , but i don't know why that's happening ,

**Comment by JainamF** [comment]
I'm with the same problem,
on hot reload it fetch data and display properly.
But still?!!!

**Comment by Umar-Khan-Yousafzai** [comment]
change your response.message.ToString() I had the same problem and I resolved this way. It then showed me where my data was null :)
