### ISSUE TITLE
Flutter tool should be more resillient or give a better error message if `.flutter_settings` is corrupted

### ISSUE THREAD

**Issue by dnfield** [flutter/flutter#39517]
Steps: make `.flutter_settings` contain invalid JSON (e.g. add a trailing comma).

Result:

```
dnfield@mbp:animations$ flutter run


Unhandled exception:
FormatException: Unexpected character (at line 3, character 1)
}
^

#0      _ChunkedJsonParser.fail (dart:convert-patch/convert_patch.dart:1392:5)
#1      _ChunkedJsonParser.parse (dart:convert-patch/convert_patch.dart:916:20)
#2      _parseJson (dart:convert-patch/convert_patch.dart:29:10)
#3      JsonDecoder.convert (dart:convert/json.dart:493:36)
#4      JsonCodec.decode (dart:convert/json.dart:151:41)
#5      new Config (package:flutter_tools/src/base/config.dart:14:22)
#6      runInContext.<anonymous closure> (package:flutter_tools/src/context_runner.dart:77:21)
#7      AppContext._generateIfNecessary.<anonymous closure> (package:flutter_tools/src/base/context.dart:99:41)
#8      _LinkedHashMapMixin.putIfAbsent (dart:collection-patch/compact_hash.dart:291:23)
#9      AppContext._generateIfNecessary (package:flutter_tools/src/base/context.dart:87:20)
#10     AppContext.get (package:flutter_tools/src/base/context.dart:115:32)
#11     Config.instance (package:flutter_tools/src/base/config.dart:17:41)
#12     new _DefaultUsage.<anonymous closure> (package:flutter_tools/src/reporting/usage.dart:195:25)
#13     WhereIterator.moveNext (dart:_internal/iterable.dart:440:11)
#14     MappedIterator.moveNext (dart:_internal/iterable.dart:392:19)
#15     Iterable.join (dart:core/iterable.dart:362:19)
#16     new _DefaultUsage (package:flutter_tools/src/reporting/usage.dart:198:10)
#17     new Usage (package:flutter_tools/src/reporting/usage.dart:70:9)
#18     runInContext.<anonymous closure> (package:flutter_tools/src/context_runner.dart:104:20)
#19     AppContext._generateIfNecessary.<anonymous closure> (package:flutter_tools/src/base/context.dart:99:41)
#20     _LinkedHashMapMixin.putIfAbsent (dart:collection-patch/compact_hash.dart:291:23)
#21     AppContext._generateIfNecessary (package:flutter_tools/src/base/context.dart:87:20)
#22     AppContext.get (package:flutter_tools/src/base/context.dart:115:32)
#23     Usage.instance (package:flutter_tools/src/reporting/usage.dart:76:40)
#24     flutterUsage (package:flutter_tools/src/reporting/usage.dart:60:33)
#25     _handleToolError (package:flutter_tools/runner.dart:121:5)
<asynchronous suspension>
#26     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:77:13)
<asynchronous suspension>
#27     _rootRunBinary (dart:async/zone.dart:1148:13)
#28     _CustomZone.runBinary (dart:async/zone.dart:1037:19)
#29     runZoned.<anonymous closure> (dart:async/zone.dart:1479:21)
#30     _CustomZone.handleUncaughtError (dart:async/zone.dart:1003:19)
#31     Future._propagateToListeners (dart:async/future_impl.dart:628:16)
#32     Future._completeError (dart:async/future_impl.dart:530:5)
#33     _AsyncAwaitCompleter.completeError (dart:async-patch/async_patch.dart:36:15)
#34     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart)
<asynchronous suspension>
#35     _rootRun (dart:async/zone.dart:1124:13)
#36     _CustomZone.run (dart:async/zone.dart:1021:19)
#37     _runZoned (dart:async/zone.dart:1516:10)
#38     runZoned (dart:async/zone.dart:1500:12)
#39     run.<anonymous closure> (package:flutter_tools/runner.dart:61:18)
<asynchronous suspension>
#40     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:154:29)
<asynchronous suspension>
#41     _rootRun (dart:async/zone.dart:1124:13)
#42     _CustomZone.run (dart:async/zone.dart:1021:19)
#43     _runZoned (dart:async/zone.dart:1516:10)
#44     runZoned (dart:async/zone.dart:1463:12)
#45     AppContext.run (package:flutter_tools/src/base/context.dart:153:18)
<asynchronous suspension>
#46     runInContext (package:flutter_tools/src/context_runner.dart:58:24)
<asynchronous suspension>
#47     run (package:flutter_tools/runner.dart:50:10)
#48     main (package:flutter_tools/executable.dart:65:9)
<asynchronous suspension>
#49     main (file:///Users/dnfield/src/flutter/packages/flutter_tools/bin/flutter_tools.dart:8:3)
#50     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:303:32)
#51     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:12)
```

It would be nicer if the tool caught this and told the user their settings file is not valid json and should be fixed (probably without the stack)

**Comment by jonahwilliams** [comment]
By default we delete the config settings if the parsing fails now.
