### ISSUE TITLE
Oops; flutter has exited unexpectedly. Sending crash report to Google. Crash report sent (report ID: 78a0358525a922d3) \CreateProcessW failed 193

### ISSUE THREAD

**Issue by ashishkumar90052** [flutter/flutter#39563]
## command

```flutter doctor --android-licenses```

## exception

```
ProcessException: ProcessException: %1 is not a valid Win32 application.

  Command: C:\Users\Ashish Kumar\AppData\Local\Android\sdk\tools\bin\sdkmanager.BAT --version
```

```
#0      _ProcessImpl._runAndWait (dart:io-patch/process_patch.dart:489:7)
#1      _runNonInteractiveProcessSync (dart:io-patch/process_patch.dart:634:18)
#2      Process.runSync (dart:io-patch/process_patch.dart:66:12)
#3      LocalProcessManager.runSync (package:process/src/interface/local_process_manager.dart:83:20)
#4      AndroidSdk.sdkManagerVersion (package:flutter_tools/src/android/android_sdk.dart:578:49)
#5      AndroidLicenseValidator.runLicenseManager (package:flutter_tools/src/android/android_workflow.dart:293:64)
<asynchronous suspension>
#6      Doctor.diagnose (package:flutter_tools/src/doctor.dart:215:38)
<asynchronous suspension>
#7      DoctorCommand.runCommand (package:flutter_tools/src/commands/doctor.dart:48:39)
<asynchronous suspension>
#8      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:478:18)
<asynchronous suspension>
#9      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:383:33)
<asynchronous suspension>
#10     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:29)
<asynchronous suspension>
#11     _rootRun (dart:async/zone.dart:1124:13)
#12     _CustomZone.run (dart:async/zone.dart:1021:19)
#13     _runZoned (dart:async/zone.dart:1516:10)
#14     runZoned (dart:async/zone.dart:1463:12)
#15     AppContext.run (package:flutter_tools/src/base/context.dart:152:18)
<asynchronous suspension>
#16     FlutterCommand.run (package:flutter_tools/src/runner/flutter_command.dart:375:20)
#17     CommandRunner.runCommand (package:args/command_runner.dart:197:27)
<asynchronous suspension>
#18     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:396:21)
<asynchronous suspension>
#19     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:29)
<asynchronous suspension>
#20     _rootRun (dart:async/zone.dart:1124:13)
#21     _CustomZone.run (dart:async/zone.dart:1021:19)
#22     _runZoned (dart:async/zone.dart:1516:10)
#23     runZoned (dart:async/zone.dart:1463:12)
#24     AppContext.run (package:flutter_tools/src/base/context.dart:152:18)
<asynchronous suspension>
#25     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:356:19)
<asynchronous suspension>
#26     CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:112:25)
#27     new Future.sync (dart:async/future.dart:224:31)
#28     CommandRunner.run (package:args/command_runner.dart:112:14)
#29     FlutterCommandRunner.run (package:flutter_tools/src/runner/flutter_command_runner.dart:242:18)
#30     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:62:22)
<asynchronous suspension>
#31     _rootRun (dart:async/zone.dart:1124:13)
#32     _CustomZone.run (dart:async/zone.dart:1021:19)
#33     _runZoned (dart:async/zone.dart:1516:10)
#34     runZoned (dart:async/zone.dart:1500:12)
#35     run.<anonymous closure> (package:flutter_tools/runner.dart:60:18)
<asynchronous suspension>
#36     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:29)
<asynchronous suspension>
#37     _rootRun (dart:async/zone.dart:1124:13)
#38     _CustomZone.run (dart:async/zone.dart:1021:19)
#39     _runZoned (dart:async/zone.dart:1516:10)
#40     runZoned (dart:async/zone.dart:1463:12)
#41     AppContext.run (package:flutter_tools/src/base/context.dart:152:18)
<asynchronous suspension>
#42     runInContext (package:flutter_tools/src/context_runner.dart:56:24)
<asynchronous suspension>
#43     run (package:flutter_tools/runner.dart:51:10)
#44     main (package:flutter_tools/executable.dart:62:9)
<asynchronous suspension>
#45     main (file:///C:/flutter/packages/flutter_tools/bin/flutter_tools.dart:8:3)
#46     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:299:32)
#47     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:12)
```

```
encountered exception: ProcessException: %1 is not a valid Win32 application.

  Command: C:\Users\Ashish Kumar\AppData\Local\Android\sdk\tools\bin\sdkmanager.BAT --licenses
```

```
#0      AndroidLicenseValidator.licensesAccepted (package:flutter_tools/src/android/android_workflow.dart:261:29)
<asynchronous suspension>
#1      AndroidLicenseValidator.validate (package:flutter_tools/src/android/android_workflow.dart:194:19)
<asynchronous suspension>
#2      GroupedValidator.validate (package:flutter_tools/src/doctor.dart:354:52)
#3      _AsyncAwaitCompleter.start (dart:async-patch/async_patch.dart:49:6)
#4      GroupedValidator.validate (package:flutter_tools/src/doctor.dart:351:36)
#5      Doctor.startValidatorTasks (package:flutter_tools/src/doctor.dart:152:52)
#6      Doctor.diagnose (package:flutter_tools/src/doctor.dart:223:41)
#7      _AsyncAwaitCompleter.start (dart:async-patch/async_patch.dart:49:6)
#8      Doctor.diagnose (package:flutter_tools/src/doctor.dart:213:24)
#9      _doctorText.<anonymous closure> (package:flutter_tools/runner.dart:193:26)
#10     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:29)
#11     _AsyncAwaitCompleter.start (dart:async-patch/async_patch.dart:49:6)
#12     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:7)
#13     _rootRun (dart:async/zone.dart:1124:13)
#14     _CustomZone.run (dart:async/zone.dart:1021:19)
#15     _runZoned (dart:async/zone.dart:1516:10)
#16     runZoned (dart:async/zone.dart:1463:12)
#17     AppContext.run (package:flutter_tools/src/base/context.dart:152:18)
#18     _AsyncAwaitCompleter.start (dart:async-patch/async_patch.dart:49:6)
#19     AppContext.run (package:flutter_tools/src/base/context.dart:140:19)
#20     _doctorText (package:flutter_tools/runner.dart:192:19)
#21     _AsyncAwaitCompleter.start (dart:async-patch/async_patch.dart:49:6)
#22     _doctorText (package:flutter_tools/runner.dart:188:27)
#23     _createLocalCrashReport (package:flutter_tools/runner.dart:170:32)
#24     _AsyncAwaitCompleter.start (dart:async-patch/async_patch.dart:49:6)
#25     _createLocalCrashReport (package:flutter_tools/runner.dart:155:37)
#26     _handleToolError (package:flutter_tools/runner.dart:125:33)
#27     _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:77:64)
#28     _rootRunUnary (dart:async/zone.dart:1132:38)
#29     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#30     _FutureListener.handleValue (dart:async/future_impl.dart:126:18)
#31     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:639:45)
#32     Future._propagateToListeners (dart:async/future_impl.dart:668:32)
#33     Future._complete (dart:async/future_impl.dart:473:7)
#34     _SyncCompleter.complete (dart:async/future_impl.dart:51:12)
#35     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:28:18)
#36     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:294:13)
#37     CrashReportSender.sendReport (package:flutter_tools/src/crash_reporting.dart)
#38     _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:77:64)
#39     _rootRunUnary (dart:async/zone.dart:1132:38)
#40     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#41     _FutureListener.handleValue (dart:async/future_impl.dart:126:18)
#42     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:639:45)
#43     Future._propagateToListeners (dart:async/future_impl.dart:668:32)
#44     Future._complete (dart:async/future_impl.dart:473:7)
#45     Stream.fold.<anonymous closure> (dart:async/stream.dart:742:18)
#46     _rootRun (dart:async/zone.dart:1120:38)
#47     _CustomZone.run (dart:async/zone.dart:1021:19)
#48     _CustomZone.runGuarded (dart:async/zone.dart:923:7)
#49     _BufferingStreamSubscription._sendDone.sendDone (dart:async/stream_impl.dart:389:13)
#50     _BufferingStreamSubscription._sendDone (dart:async/stream_impl.dart:399:15)
#51     _BufferingStreamSubscription._close (dart:async/stream_impl.dart:283:7)
#52     _SinkTransformerStreamSubscription._close (dart:async/stream_transformers.dart:96:11)
#53     _EventSinkWrapper.close (dart:async/stream_transformers.dart:23:11)
#54     _StringAdapterSink.close (dart:convert/string_conversion.dart:249:11)
#55     _Utf8ConversionSink.close (dart:convert/string_conversion.dart:300:20)
#56     _ConverterStreamEventSink.close (dart:convert/chunked_conversion.dart:80:18)
#57     _SinkTransformerStreamSubscription._handleDone (dart:async/stream_transformers.dart:141:24)
#58     _rootRun (dart:async/zone.dart:1120:38)
#59     _CustomZone.run (dart:async/zone.dart:1021:19)
#60     _CustomZone.runGuarded (dart:async/zone.dart:923:7)
#61     _BufferingStreamSubscription._sendDone.sendDone (dart:async/stream_impl.dart:389:13)
#62     _BufferingStreamSubscription._sendDone (dart:async/stream_impl.dart:399:15)
#63     _BufferingStreamSubscription._close (dart:async/stream_impl.dart:283:7)
#64     _ForwardingStream._handleDone (dart:async/stream_pipe.dart:106:10)
#65     _ForwardingStreamSubscription._handleDone (dart:async/stream_pipe.dart:172:13)
#66     _rootRun (dart:async/zone.dart:1120:38)
#67     _CustomZone.run (dart:async/zone.dart:1021:19)
#68     _CustomZone.runGuarded (dart:async/zone.dart:923:7)
#69     _BufferingStreamSubscription._sendDone.sendDone (dart:async/stream_impl.dart:389:13)
#70     _BufferingStreamSubscription._sendDone (dart:async/stream_impl.dart:399:15)
#71     _BufferingStreamSubscription._close (dart:async/stream_impl.dart:283:7)
#72     _SinkTransformerStreamSubscription._close (dart:async/stream_transformers.dart:96:11)
#73     _EventSinkWrapper.close (dart:async/stream_transformers.dart:23:11)
#74     _ByteAdapterSink.close (dart:convert/byte_conversion.dart:62:11)
#75     _FilterSink.close (dart:io/data_transformer.dart:637:11)
#76     _ConverterStreamEventSink.close (dart:convert/chunked_conversion.dart:80:18)
#77     _SinkTransformerStreamSubscription._handleDone (dart:async/stream_transformers.dart:141:24)
#78     _rootRun (dart:async/zone.dart:1120:38)
#79     _CustomZone.run (dart:async/zone.dart:1021:19)
#80     _CustomZone.runGuarded (dart:async/zone.dart:923:7)
#81     _BufferingStreamSubscription._sendDone.sendDone (dart:async/stream_impl.dart:389:13)
#82     _BufferingStreamSubscription._sendDone (dart:async/stream_impl.dart:399:15)
#83     _BufferingStreamSubscription._close (dart:async/stream_impl.dart:283:7)
#84     _ForwardingStream._handleDone (dart:async/stream_pipe.dart:106:10)
#85     _ForwardingStreamSubscription._handleDone (dart:async/stream_pipe.dart:172:13)
#86     _rootRun (dart:async/zone.dart:1120:38)
#87     _CustomZone.run (dart:async/zone.dart:1021:19)
#88     _CustomZone.runGuarded (dart:async/zone.dart:923:7)
#89     _BufferingStreamSubscription._sendDone.sendDone (dart:async/stream_impl.dart:389:13)
#90     _BufferingStreamSubscription._sendDone (dart:async/stream_impl.dart:399:15)
#91     _BufferingStreamSubscription._close (dart:async/stream_impl.dart:283:7)
#92     _SyncStreamController._sendDone (dart:async/stream_controller.dart:772:19)
#93     _StreamController._closeUnchecked (dart:async/stream_controller.dart:629:7)
#94     _StreamController.close (dart:async/stream_controller.dart:622:5)
#95     _HttpParser._closeIncoming (dart:_http/http_parser.dart:1037:23)
#96     _HttpParser._doParse (dart:_http/http_parser.dart:752:11)
#97     _HttpParser._parse (dart:_http/http_parser.dart:318:7)
#98     _HttpParser._onData (dart:_http/http_parser.dart:810:5)
#99     _rootRunUnary (dart:async/zone.dart:1132:38)
#100    _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#101    _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
#102    _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#103    _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#104    _SyncStreamController._sendData (dart:async/stream_controller.dart:764:19)
#105    _StreamController._add (dart:async/stream_controller.dart:640:7)
#106    _StreamController.add (dart:async/stream_controller.dart:586:5)
#107    _Socket._onData (dart:io-patch/socket_patch.dart:1786:41)
#108    _rootRunUnary (dart:async/zone.dart:1132:38)
#109    _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#110    _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
#111    _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#112    _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#113    _SyncStreamController._sendData (dart:async/stream_controller.dart:764:19)
#114    _StreamController._add (dart:async/stream_controller.dart:640:7)
#115    _StreamController.add (dart:async/stream_controller.dart:586:5)
#116    _RawSecureSocket._sendReadEvent (dart:io/secure_socket.dart:1004:19)
#117    _rootRun (dart:async/zone.dart:1120:38)
#118    _CustomZone.run (dart:async/zone.dart:1021:19)
#119    _CustomZone.runGuarded (dart:async/zone.dart:923:7)
#120    _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:963:23)
#121    _rootRun (dart:async/zone.dart:1124:13)
#122    _CustomZone.run (dart:async/zone.dart:1021:19)
#123    _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:947:23)
#124    Timer._createTimer.<anonymous closure> (dart:async-patch/timer_patch.dart:21:15)
#125    _Timer._runTimers (dart:isolate-patch/timer_impl.dart:382:19)
#126    _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:416:5)
#127    _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:12)
```

**Comment by BondarenkoStas** [comment]
@ashishkumar90052 Please provide ```flutter --version``` output.
Check out https://github.com/flutter/flutter/issues/18938 as it may be connected to your issue. Try to rename your user to not to have spaces in the name, or to move Android to a folder without spaces like C:\Temp\Android or similar.

**Comment by Yamonwan** [comment]
Please, can you help me how to change user name in window ?

**Comment by BondarenkoStas** [comment]
@Yamonwan it's easier to google it like https://www.computerhope.com/issues/ch000767.htm, depends on your windows version. Or just try to move your Android folder out of your user folder.

**Comment by Yamonwan** [comment]
Well, I chose to move android in "c: \ android"

Could this cause other problem to android studio?

If so, which configuration to perform?

**Comment by BondarenkoStas** [comment]
@Yamonwan as I know it shouldn't as far as you set all the paths correctly.
@ashishkumar90052 Please report if the issue is still relevant.

**Comment by ashishkumar90052** [comment]
thanks to all issue resolved

**Comment by yassine353** [comment]
i have same problem what can i do?

Sending crash report to Google.
Crash report sent (report ID: f6e09b835651ca22)
Oops; flutter has exited unexpectedly.
Crash report written to C:\Users\hp\flutter_06.log;
please let us know at https://github.com/flutter/flutter/issues.

**Comment by Hexunity** [comment]
Sending crash report to Google.
Crash report sent (report ID: 5a54e8bf272d2469)
Oops; flutter has exited unexpectedly.

**Comment by caselock1023** [comment]
Sending crash report to Google.
Crash report sent (report ID: 575b796e432ae61e)
Oops; flutter has exited unexpectedly.
