### ISSUE TITLE
Crash Report

### ISSUE THREAD

**Issue by jain-shreyansh** [flutter/flutter#39678]
## command

```flutter run```

## exception

```
String: Exit code 1 from: C:\Users\Shreyansh Jain\AppData\Local\Android\sdk\platform-tools\adb.exe -s c732f13c0005 shell -x logcat -v time -t 1

#0      _runWithLoggingSync (package:flutter_tools/src/base/process.dart:375:7)
#1      runCheckedSync (package:flutter_tools/src/base/process.dart:297:10)
#2      AndroidDevice.runAdbCheckedSync (package:flutter_tools/src/android/android_device.dart:180:12)
#3      AndroidDevice.lastLogcatTimestamp (package:flutter_tools/src/android/android_device.dart:571:27)
#4      _AdbLogReader._start (package:flutter_tools/src/android/android_device.dart:751:41)
#5      _runGuarded (dart:async/stream_controller.dart:805:24)
#6      _BroadcastStreamController._subscribe (dart:async/broadcast_stream_controller.dart:213:7)
#7      _ControllerStream._createSubscription (dart:async/stream_controller.dart:818:19)
#8      _StreamImpl.listen (dart:async/stream_impl.dart:472:9)
#9      FlutterDevice.startEchoingDeviceLog (package:flutter_tools/src/resident_runner.dart:325:38)
#10     FlutterDevice.runHot (package:flutter_tools/src/resident_runner.dart:368:5)
<asynchronous suspension>
#11     HotRunner.run (package:flutter_tools/src/run_hot.dart:251:39)
<asynchronous suspension>
#12     RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:469:37)
<asynchronous suspension>
#13     FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:478:18)
<asynchronous suspension>
#14     FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:383:33)
<asynchronous suspension>
#15     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:29)
<asynchronous suspension>
#16     _rootRun (dart:async/zone.dart:1124:13)
#17     _CustomZone.run (dart:async/zone.dart:1021:19)
#18     _runZoned (dart:async/zone.dart:1516:10)
#19     runZoned (dart:async/zone.dart:1463:12)
#20     AppContext.run (package:flutter_tools/src/base/context.dart:152:18)
<asynchronous suspension>
#21     FlutterCommand.run (package:flutter_tools/src/runner/flutter_command.dart:375:20)
#22     CommandRunner.runCommand (package:args/command_runner.dart:197:27)
<asynchronous suspension>
#23     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:396:21)
<asynchronous suspension>
#24     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:29)
<asynchronous suspension>
#25     _rootRun (dart:async/zone.dart:1124:13)
#26     _CustomZone.run (dart:async/zone.dart:1021:19)
#27     _runZoned (dart:async/zone.dart:1516:10)
#28     runZoned (dart:async/zone.dart:1463:12)
#29     AppContext.run (package:flutter_tools/src/base/context.dart:152:18)
<asynchronous suspension>
#30     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:356:19)
<asynchronous suspension>
#31     CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:112:25)
#32     new Future.sync (dart:async/future.dart:224:31)
#33     CommandRunner.run (package:args/command_runner.dart:112:14)
#34     FlutterCommandRunner.run (package:flutter_tools/src/runner/flutter_command_runner.dart:242:18)
#35     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:62:22)
<asynchronous suspension>
#36     _rootRun (dart:async/zone.dart:1124:13)
#37     _CustomZone.run (dart:async/zone.dart:1021:19)
#38     _runZoned (dart:async/zone.dart:1516:10)
#39     runZoned (dart:async/zone.dart:1500:12)
#40     run.<anonymous closure> (package:flutter_tools/runner.dart:60:18)
<asynchronous suspension>
#41     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:29)
<asynchronous suspension>
#42     _rootRun (dart:async/zone.dart:1124:13)
#43     _CustomZone.run (dart:async/zone.dart:1021:19)
#44     _runZoned (dart:async/zone.dart:1516:10)
#45     runZoned (dart:async/zone.dart:1463:12)
#46     AppContext.run (package:flutter_tools/src/base/context.dart:152:18)
<asynchronous suspension>
#47     runInContext (package:flutter_tools/src/context_runner.dart:56:24)
<asynchronous suspension>
#48     run (package:flutter_tools/runner.dart:51:10)
#49     main (package:flutter_tools/executable.dart:62:9)
<asynchronous suspension>
#50     main (file:///C:/flutter/packages/flutter_tools/bin/flutter_tools.dart:8:3)
#51     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:299:32)
#52     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:12)
```

## flutter doctor

```
[32m[✓][39m Flutter (Channel stable, v1.7.8+hotfix.4, on Microsoft Windows [Version 10.0.18362.295], locale en-US)
    [32m•[39m Flutter version 1.7.8+hotfix.4 at C:\flutter
    [32m•[39m Framework revision 20e59316b8 (6 weeks ago), 2019-07-18 20:04:33 -0700
    [32m•[39m Engine revision fee001c93f
    [32m•[39m Dart version 2.4.0

[32m[✓][39m Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    [32m•[39m Android SDK at C:\Users\Shreyansh Jain\AppData\Local\Android\sdk
    [32m•[39m Android NDK location not configured (optional; useful for native profiling support)
    [32m•[39m Platform android-28, build-tools 28.0.3
    [32m•[39m Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    [32m•[39m Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
    [32m•[39m All Android licenses accepted.

[32m[✓][39m Android Studio (version 3.4)
    [32m•[39m Android Studio at C:\Program Files\Android\Android Studio
    [32m•[39m Flutter plugin version 37.1.1
    [32m•[39m Dart plugin version 183.6270
    [32m•[39m Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

[32m[✓][39m VS Code (version 1.37.1)
    [32m•[39m VS Code at C:\Users\Shreyansh Jain\AppData\Local\Programs\Microsoft VS Code
    [32m•[39m Flutter extension version 3.3.0

[32m[✓][39m Connected device (1 available)
    [32m•[39m Redmi Note 5 • c732f13c0005 • android-arm64 • Android 8.1.0 (API 27)

[32m•[39m No issues found!
```

**Comment by BondarenkoStas** [comment]
Please post it on StackOverflow as well as most probably there is something wrong with the project, not with flutter itself.
Anyway, do you have any clues how to reproduce it?
