### ISSUE TITLE
examples/widgets/dropdown.dart asserts on selection

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#397]
In `examples/widgets/dropdown.dart` when you select something from the drop-down you get:

```
-- EXCEPTION IN SCHEDULER CALLBACK --
Bad state: Future already completed
Stack trace:
#0      _AsyncCompleter.complete (dart:async/future_impl.dart:40)
#1      TransitionRoute._handleStatusChanged (flutter/packages/flutter/lib/src/widgets/routes.dart:86)
#2      Performance._checkStatusChanged (flutter/packages/flutter/lib/src/animation/performance.dart:288)
#3      Performance.didTick (flutter/packages/flutter/lib/src/animation/performance.dart:315)
#4      Performance._tick (flutter/packages/flutter/lib/src/animation/performance.dart:310)
#5      SimulationStepper._tick (flutter/packages/flutter/lib/src/animation/simulation_stepper.dart:103)
#6      Ticker._tick (flutter/packages/flutter/lib/src/animation/ticker.dart:67)
#7      Scheduler.invokeCallback (flutter/packages/flutter/lib/src/animation/scheduler.dart:81)
#8      Scheduler.beginFrame.<anonymous closure> (flutter/packages/flutter/lib/src/animation/scheduler.dart:62)
#9      _HashVMBase&MapMixin&&_LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:340)
#10     Scheduler.beginFrame (flutter/packages/flutter/lib/src/animation/scheduler.dart:60)
...
```

**Comment by abarth** [comment]
I fixenated this.
