### ISSUE TITLE
[Web] "Flutter has exited unexpectedly" on hot restart

### ISSUE THREAD

**Issue by Akora-IngDKB** [flutter/flutter#39749]
## command
```
flutter run --machine --target lib\main.dart -d chrome --track-widget-creation --start-paused
```
## exception
```
NoSuchMethodError: NoSuchMethodError: The method 'toJson' was called on null.
Receiver: null
Tried calling: toJson()
```

```
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:51:5)
#1      SourceLocation.toJson (package:vm_service/vm_service.dart:5024:24)
#2      Frame.toJson (package:vm_service/vm_service.dart:3296:47)
#3      Event.toJson (package:vm_service/vm_service.dart:3022:47)
#4      VmServerConnection._delegateRequest.<anonymous closure> (package:vm_service/vm_service.dart:1141:28)
#5      _rootRunUnary (dart:async/zone.dart:1132:38)
#6      _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#7      _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
#8      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#9      _DelayedData.perform (dart:async/stream_impl.dart:591:14)
#10     _StreamImplEvents.handleNext (dart:async/stream_impl.dart:707:11)
#11     _PendingEvents.schedule.<anonymous closure> (dart:async/stream_impl.dart:667:7)
#12     _rootRun (dart:async/zone.dart:1120:38)
#13     _CustomZone.run (dart:async/zone.dart:1021:19)
#14     _CustomZone.runGuarded (dart:async/zone.dart:923:7)
#15     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:963:23)
#16     _rootRun (dart:async/zone.dart:1124:13)
#17     _CustomZone.run (dart:async/zone.dart:1021:19)
#18     _CustomZone.runGuarded (dart:async/zone.dart:923:7)
#19     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:963:23)
#20     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#21     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#22     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:116:13)
#23     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:173:5)
```

## flutter doctor

```
[✓] Flutter (Channel master, v1.9.8-pre.17, on Microsoft Windows [Version 10.0.18362.175], locale en-GH)
    • Flutter version 1.9.8-pre.17 at C:\flutter
    • Framework revision 359b532570 (5 days ago), 2019-08-29 19:35:06 -0700
    • Engine revision 9a17d8e451
    • Dart version 2.5.0 (build 2.5.0-dev.4.0 35382f9b14)

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.1)
    • Android SDK at C:\Users\debra\AppData\Local\Android\Sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.1
    • ANDROID_HOME = C:\Users\debra\AppData\Local\Android\Sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[✓] Android Studio (version 3.4)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 38.1.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

[✓] VS Code (version 1.37.1)
    • VS Code at C:\Users\debra\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.3.0

[✓] Connected device (1 available)
    • Chrome • chrome • web-javascript • Google Chrome 76.0.3809.132

• No issues found!
```

**Comment by jonahwilliams** [comment]
cc @jakemac53 @grouma

**Comment by grouma** [comment]
Almost certainly related to https://github.com/dart-lang/webdev/issues/586

**Comment by Akora-IngDKB** [comment]
Same behavior again. Not on hot restart this time. Just running normal and crashed.  
## command

flutter run --machine --target lib\main.dart -d chrome --track-widget-creation --start-paused

## exception

UnsupportedError: Unsupported operation: Cannot create multiple isolates for the same app

```
#0      ChromeProxyService.createIsolate (package:dwds/src/services/chrome_proxy_service.dart:108:7)
<asynchronous suspension>
#1      DevHandler._handleConnection.<anonymous closure> (package:dwds/src/handlers/dev_handler.dart:255:15)
<asynchronous suspension>
#2      _rootRunUnary (dart:async/zone.dart:1132:38)
#3      _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#4      _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
#5      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#6      _DelayedData.perform (dart:async/stream_impl.dart:591:14)
#7      _StreamImplEvents.handleNext (dart:async/stream_impl.dart:707:11)
#8      _PendingEvents.schedule.<anonymous closure> (dart:async/stream_impl.dart:667:7)
#9      _rootRun (dart:async/zone.dart:1120:38)
#10     _CustomZone.run (dart:async/zone.dart:1021:19)
#11     _CustomZone.runGuarded (dart:async/zone.dart:923:7)
#12     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:963:23)
#13     _rootRun (dart:async/zone.dart:1124:13)
#14     _CustomZone.run (dart:async/zone.dart:1021:19)
#15     _CustomZone.runGuarded (dart:async/zone.dart:923:7)
#16     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:963:23)
#17     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#18     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#19     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:116:13)
#20     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:173:5)
```

## flutter doctor

```
[✓] Flutter (Channel master, v1.9.8-pre.17, on Microsoft Windows [Version 10.0.18362.175], locale en-GH)
    • Flutter version 1.9.8-pre.17 at C:\flutter
    • Framework revision 359b532570 (5 days ago), 2019-08-29 19:35:06 -0700
    • Engine revision 9a17d8e451
    • Dart version 2.5.0 (build 2.5.0-dev.4.0 35382f9b14)

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.1)
    • Android SDK at C:\Users\debra\AppData\Local\Android\Sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.1
    • ANDROID_HOME = C:\Users\debra\AppData\Local\Android\Sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[✓] Android Studio (version 3.4)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 38.1.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

[✓] VS Code (version 1.37.1)
    • VS Code at C:\Users\debra\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.3.0

[✓] Connected device (1 available)
    • Chrome • chrome • web-javascript • Google Chrome 76.0.3809.132

• No issues found!
```

**Comment by yjbanov** [comment]
dwds has been updated recently. Can you please try again?

**Comment by Akora-IngDKB** [comment]
@yjbanov it's working fine so far.
