### ISSUE TITLE
android license status unknown

### ISSUE THREAD

**Issue by jayduttbhatt** [flutter/flutter#39823]
This happens all the time when i type flutter doctor 
and beacause of this issue gradle wrapper is not downloaded and installed
pls. someone give the soluion ASAP.

## flutter doctor
```
[√] Flutter (Channel stable, v1.7.8+hotfix.4, on Microsoft Windows [Version 10.0.17134.950], locale en-IN)
[!] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    X Android license status unknown.
      Try re-installing or updating your Android SDK Manager.
      See https://developer.android.com/studio/#downloads or visit https://flutter.dev/setup/#android-setup for detailed
      instructions.
[√] Android Studio (version 3.5)
[!] Connected device
    ! No devices available

! Doctor found issues in 2 categories.
```

**Comment by BondarenkoStas** [comment]
@jayduttbhatt Can you confirm you accepted all licenses?
Please also check https://github.com/flutter/flutter/issues/39637#issuecomment-526914541 in as it may solve your problem.

**Comment by brieucdesoutter** [comment]
I encounter this one too.
```
$ flutter upgrade
Upgrading Flutter from /Users/desoutte/flutter...
Updating c382b8e99..cc949a8e8
 16 files changed, 435 insertions(+), 308 deletions(-)
Current branch stable is up to date.
Building flutter tool...

Upgrading engine...

Flutter 1.9.1+hotfix.4 • channel stable • https://github.com/flutter/flutter.git
Framework • revision cc949a8e8b (10 days ago) • 2019-09-27 15:04:59 -0700
Engine • revision b863200c37
Tools • Dart 2.5.0

Running flutter doctor...
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, v1.9.1+hotfix.4, on Mac OS X 10.14.6 18G103, locale en-BE)
[!] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    ✗ Android license status unknown.
      Try re-installing or updating your Android SDK Manager.
      See https://developer.android.com/studio/#downloads or visit https://flutter.dev/setup/#android-setup for detailed instructions.
[✓] Xcode - develop for iOS and macOS (Xcode 11.0)
[✓] Android Studio (version 3.5)
[✓] IntelliJ IDEA Ultimate Edition (version 2019.2.3)
[✓] VS Code (version 1.38.0)
[!] Connected device
    ! No devices available

! Doctor found issues in 2 categories.
$ flutter doctor --android-licenses
A newer version of the Android SDK is required. To update, run:
/Users/desoutte/Library/Android/sdk/tools/bin/sdkmanager --update


$ /Users/desoutte/Library/Android/sdk/tools/bin/sdkmanager --update
Exception in thread "main" java.lang.NoClassDefFoundError: javax/xml/bind/annotation/XmlSchema
	at com.android.repository.api.SchemaModule$SchemaModuleVersion.<init>(SchemaModule.java:156)
	at com.android.repository.api.SchemaModule.<init>(SchemaModule.java:75)
	at com.android.sdklib.repository.AndroidSdkHandler.<clinit>(AndroidSdkHandler.java:81)
	at com.android.sdklib.tool.sdkmanager.SdkManagerCli.main(SdkManagerCli.java:73)
	at com.android.sdklib.tool.sdkmanager.SdkManagerCli.main(SdkManagerCli.java:48)
Caused by: java.lang.ClassNotFoundException: javax.xml.bind.annotation.XmlSchema
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:583)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	... 5 more
```

**Comment by BondarenkoStas** [comment]
@brieucdesoutter @jayduttbhatt do you use java higher than 1.8?

**Comment by brieucdesoutter** [comment]
@BondarenkoStas Yep 
```
desoutte@be1mcl-C02X53JKJGH6 ~ $ java -version
openjdk version "11.0.3" 2019-04-16 LTS
OpenJDK Runtime Environment Zulu11.31+11-CA (build 11.0.3+7-LTS)
OpenJDK 64-Bit Server VM Zulu11.31+11-CA (build 11.0.3+7-LTS, mixed mode)
```

**Comment by brieucdesoutter** [comment]
@BondarenkoStas Works just fine with JDK 1.8

```
desoutte@be1mcl-C02X53JKJGH6 ~ $ java -version
java version "1.8.0_191"
Java(TM) SE Runtime Environment (build 1.8.0_191-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.191-b12, mixed mode)
desoutte@be1mcl-C02X53JKJGH6 ~ $ flutter doctor --android-licenses
Warning: File /Users/desoutte/.android/repositories.cfg could not be loaded.
All SDK package licenses accepted.======] 100% Computing updates...
```

**Comment by brieucdesoutter** [comment]
Or is it ? 
I use sdkman. When switching to 1.8 I have the output mentionned above and it seems to work. When switching back to 11, the license issue is still menitonned by flutter doctor.

**Comment by BondarenkoStas** [comment]
Oh yes, it's known issue without solution yet, please check #31116. I would close this issue, please follow it in #39549.
