### ISSUE TITLE
xcodebuild: error: Scheme Runner is not currently configured for the build action.

### ISSUE THREAD

**Issue by dheeraj2dj** [flutter/flutter#39821]
## command
```
flutter run
```
## exception
```
String: Exit code 66 from: /usr/bin/env xcrun xcodebuild -configuration Debug -quiet -workspace Runner.xcworkspace -scheme Runner BUILD_DIR=/Users/dheeraj2dj/Projects/circle_app/build/ios -sdk iphoneos ONLY_ACTIVE_ARCH=YES ARCHS=arm64 SCRIPT_OUTPUT_STREAM_FILE=/var/folders/q7/c_5qfhz50yd9yx6rdqzd32pc0000gn/T/flutter_build_log_pipe.ufqB4g/pipe_to_stdout FLUTTER_SUPPRESS_ANALYTICS=true COMPILER_INDEX_STORE_ENABLE=NO -showBuildSettings
```

```
#0      _runWithLoggingSync (package:flutter_tools/src/base/process.dart:461:7)
#1      runCheckedSync (package:flutter_tools/src/base/process.dart:383:10)
#2      buildXcodeProject (package:flutter_tools/src/ios/mac.dart:466:69)
#3      _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:71:64)
#4      _rootRunUnary (dart:async/zone.dart:1132:38)
#5      _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#6      _FutureListener.handleValue (dart:async/future_impl.dart:137:18)
#7      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:678:45)
#8      Future._propagateToListeners (dart:async/future_impl.dart:707:32)
#9      Future._completeWithValue (dart:async/future_impl.dart:522:5)
#10     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:30:15)
#11     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:288:13)
#12     runAsync (package:flutter_tools/src/base/process.dart)
#13     _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:71:64)
#14     _rootRunUnary (dart:async/zone.dart:1132:38)
#15     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#16     _FutureListener.handleValue (dart:async/future_impl.dart:137:18)
#17     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:678:45)
#18     Future._propagateToListeners (dart:async/future_impl.dart:707:32)
#19     Future._completeWithValue (dart:async/future_impl.dart:522:5)
#20     Future.wait.<anonymous closure> (dart:async/future.dart:400:22)
#21     _rootRunUnary (dart:async/zone.dart:1132:38)
#22     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#23     _FutureListener.handleValue (dart:async/future_impl.dart:137:18)
#24     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:678:45)
#25     Future._propagateToListeners (dart:async/future_impl.dart:707:32)
#26     Future._complete (dart:async/future_impl.dart:512:7)
#27     Stream.fold.<anonymous closure> (dart:async/stream.dart:801:18)
#28     _rootRun (dart:async/zone.dart:1120:38)
#29     _CustomZone.run (dart:async/zone.dart:1021:19)
#30     _CustomZone.runGuarded (dart:async/zone.dart:923:7)
#31     _BufferingStreamSubscription._sendDone.sendDone (dart:async/stream_impl.dart:389:13)
#32     _BufferingStreamSubscription._sendDone (dart:async/stream_impl.dart:399:15)
#33     _BufferingStreamSubscription._close (dart:async/stream_impl.dart:283:7)
#34     _SinkTransformerStreamSubscription._close (dart:async/stream_transformers.dart:96:11)
#35     _EventSinkWrapper.close (dart:async/stream_transformers.dart:23:11)
#36     _StringAdapterSink.close (dart:convert/string_conversion.dart:249:11)
#37     _Utf8ConversionSink.close (dart:convert/string_conversion.dart:300:20)
#38     _ConverterStreamEventSink.close (dart:convert/chunked_conversion.dart:80:18)
#39     _SinkTransformerStreamSubscription._handleDone (dart:async/stream_transformers.dart:141:24)
#40     _rootRun (dart:async/zone.dart:1120:38)
#41     _CustomZone.run (dart:async/zone.dart:1021:19)
#42     _CustomZone.runGuarded (dart:async/zone.dart:923:7)
#43     _BufferingStreamSubscription._sendDone.sendDone (dart:async/stream_impl.dart:389:13)
#44     _BufferingStreamSubscription._sendDone (dart:async/stream_impl.dart:399:15)
#45     _BufferingStreamSubscription._close (dart:async/stream_impl.dart:283:7)
#46     _SyncStreamControllerDispatch._sendDone (dart:async/stream_controller.dart:772:19)
#47     _StreamController._closeUnchecked (dart:async/stream_controller.dart:629:7)
#48     _StreamController.close (dart:async/stream_controller.dart:622:5)
#49     _Socket._onData (dart:io-patch/socket_patch.dart:1798:21)
#50     _rootRunUnary (dart:async/zone.dart:1136:13)
#51     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#52     _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
#53     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#54     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#55     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:764:19)
#56     _StreamController._add (dart:async/stream_controller.dart:640:7)
#57     _StreamController.add (dart:async/stream_controller.dart:586:5)
#58     new _RawSocket.<anonymous closure> (dart:io-patch/socket_patch.dart:1346:35)
#59     _NativeSocket.issueReadEvent.issue (dart:io-patch/socket_patch.dart:853:18)
#60     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#61     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#62     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:116:13)
#63     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:173:5)
```

## flutter doctor

```
[✓] Flutter (Channel dev, v1.9.7, on Mac OS X 10.14.6 18G87, locale en-IN)
    • Flutter version 1.9.7 at /Users/dheeraj2dj/flutter
    • Framework revision 4984d1a33d (7 days ago), 2019-08-28 17:04:07 -0700
    • Engine revision f52c0b9270
    • Dart version 2.5.0

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.1)
    • Android SDK at /Users/dheeraj2dj/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.1
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 10.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.3, Build version 10G8
    • CocoaPods version 1.7.5

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 39.0.3
    • Dart plugin version 191.8423
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] VS Code (version 1.36.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.3.0

[✓] Connected device (1 available)
    • DJ's iPhone X • 5b024342788c426fa1b943c9df2a3fe5c6a57733 • ios • iOS 12.4.1

• No issues found!
```

**Comment by jmagman** [comment]
1. What's the output of:
```shell
$ xcrun xcodebuild -configuration Debug -workspace Runner.xcworkspace -scheme Runner BUILD_DIR=/Users/dheeraj2dj/Projects/circle_app/build/ios -sdk iphoneos ONLY_ACTIVE_ARCH=YES ARCHS=arm64 FLUTTER_SUPPRESS_ANALYTICS=true COMPILER_INDEX_STORE_ENABLE=NO -showBuildSettings
```

2. What happens when you build it from Xcode?
```shell
$ open /Users/dheeraj2dj/Projects/circle_app/ios/Runner.xcworkspace
```
Product > Build.

**Comment by Maosalas** [comment]
If I run 
```
xcrun xcodebuild -configuration Debug -workspace Runner.xcworkspace -scheme Runner BUILD_DIR=/Users/dheeraj2dj/Projects/circle_app/build/ios -sdk iphoneos ONLY_ACTIVE_ARCH=YES ARCHS=arm64 FLUTTER_SUPPRESS_ANALYTICS=true COMPILER_INDEX_STORE_ENABLE=NO -showBuildSettings
```
My output is this
```
Build settings from command line:
    ARCHS = arm64
    BUILD_DIR = /Users/dheeraj2dj/Projects/circle_app/build/ios    COMPILER_INDEX_STORE_ENABLE = NO    FLUTTER_SUPPRESS_ANALYTICS = true
    ONLY_ACTIVE_ARCH = YES
    SDKROOT = iphoneos13.2

xcodebuild: error: 'Runner.xcworkspace' does not exist.
```
And if I build it from Xcode, he builds it normally

**Comment by jmagman** [comment]
> And if I build it from Xcode, he builds it normally

If the Runner.xcworkspace does not exist, how are you opening it in Xcode?

**Comment by Maosalas** [comment]
I don't know, here is my ls of ios directory
```
Flutter			Podfile.lock		Runner.xcodeproj
Frameworks		Pods			Runner.xcworkspace
Podfile			Runner			ServiceDefinitions.json
```

**Comment by Maosalas** [comment]
Now im getting this error
```
Could not find the built application bundle at build/ios/iphoneos/Runner.app.
```
This error is by running on Visual Studio Code
```
flutter run
```
But when I build it from Xcode it builds normal

**Comment by jmagman** [comment]
@Maosalas can you file a new issue?

**Comment by kumarpalsinh25** [comment]
Hello,

I'm also facing issues while running an app on iOS simulator.

Finished with error: ProcessException: Process exited abnormally:

** Error **
xcodebuild: error: Scheme Runner is not currently configured for the build action.
  Command: /usr/bin/env xcrun xcodebuild -configuration Debug -quiet -workspace Runner.xcworkspace -scheme Runner BUILD_DIR=/Users/admin/Projects/Flutter_Projects/Live_Projects/GVBCK/build/ios -sdk iphonesimulator -arch x86_64 FLUTTER_SUPPRESS_ANALYTICS=true COMPILER_INDEX_STORE_ENABLE=NO -showBuildSettings

** Flutter Configuration **
[✓] Flutter (Channel stable, v1.12.13+hotfix.5, on Mac OS X 10.15.1 19B88, locale en-IN)
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 11.3)
[✓] Android Studio (version 3.5)
[✓] Connected device (1 available)

Please help me.

**Comment by jmagman** [comment]
> Hello,
> 
> I'm also facing issues while running an app on iOS simulator.
> 
> Finished with error: ProcessException: Process exited abnormally:
> 
> ** Error **
> xcodebuild: error: Scheme Runner is not currently configured for the build action.
> 
> Command: /usr/bin/env xcrun xcodebuild -configuration Debug -quiet -workspace Runner.xcworkspace -scheme Runner BUILD_DIR=/Users/admin/Projects/Flutter_Projects/Live_Projects/GVBCK/build/ios -sdk iphonesimulator -arch x86_64 FLUTTER_SUPPRESS_ANALYTICS=true COMPILER_INDEX_STORE_ENABLE=NO -showBuildSettings
> 
> ** Flutter Configuration **
> [✓] Flutter (Channel stable, v1.12.13+hotfix.5, on Mac OS X 10.15.1 19B88, locale en-IN)
> [✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
> [✓] Xcode - develop for iOS and macOS (Xcode 11.3)
> [✓] Android Studio (version 3.5)
> [✓] Connected device (1 available)
> 
> Please help me.

I created a new issue at https://github.com/flutter/flutter/issues/47261.  Your input in that issue would be greatly appreciated!
