### ISSUE TITLE
build aar failed if flutter_string_encryption is used

### ISSUE THREAD

**Issue by askarsyzdykov** [flutter/flutter#39957]
Build aar failed when I work with https://pub.dev/packages/flutter_string_encryption plugin, it depends on this Android library https://github.com/tozny/java-aes-crypto. This repo's artefacts host in maven { url 'https://jitpack.io' } and couldn't be resolved, because .android/build.gradle contains only google() and jcenter().

## Steps to Reproduce

1. run **flutter clean && flutter build aar -v**

## Logs

```
[+1130 ms] Running Gradle task 'assembleAarRelease'...                         1.1s
[  +12 ms] Built ../../build/host/outputs/repo.
[+2123 ms] FAILURE: Build failed with an exception.
[   +1 ms] * What went wrong:
[        ] Could not determine the dependencies of task ':flutter:compileReleaseAidl'.
[        ] > Could not resolve all task dependencies for configuration ':flutter:releaseCompileClasspath'.
[        ]    > Could not find com.github.tozny:java-aes-crypto:1.1.0.
[        ]      Searched in the following locations:
[        ]          file:/Users/username/Library/Android/sdk/extras/m2repository/com/github/tozny/java-aes-crypto/1.1.0/java-aes-crypto-1.1.0.pom
[        ]          file:/Users/username/Library/Android/sdk/extras/m2repository/com/github/tozny/java-aes-crypto/1.1.0/java-aes-crypto-1.1.0.jar
[        ]          file:/Users/username/Library/Android/sdk/extras/google/m2repository/com/github/tozny/java-aes-crypto/1.1.0/java-aes-crypto-1.1.0.pom
[        ]          file:/Users/username/Library/Android/sdk/extras/google/m2repository/com/github/tozny/java-aes-crypto/1.1.0/java-aes-crypto-1.1.0.jar
[        ]          file:/Users/username/Library/Android/sdk/extras/android/m2repository/com/github/tozny/java-aes-crypto/1.1.0/java-aes-crypto-1.1.0.pom
[        ]          file:/Users/username/Library/Android/sdk/extras/android/m2repository/com/github/tozny/java-aes-crypto/1.1.0/java-aes-crypto-1.1.0.jar
[        ]          https://dl.google.com/dl/android/maven2/com/github/tozny/java-aes-crypto/1.1.0/java-aes-crypto-1.1.0.pom
[        ]          https://dl.google.com/dl/android/maven2/com/github/tozny/java-aes-crypto/1.1.0/java-aes-crypto-1.1.0.jar
[        ]          https://jcenter.bintray.com/com/github/tozny/java-aes-crypto/1.1.0/java-aes-crypto-1.1.0.pom
[        ]          https://jcenter.bintray.com/com/github/tozny/java-aes-crypto/1.1.0/java-aes-crypto-1.1.0.jar
[        ]          file:/Users/username/Projects/myProject/flutter_lib/build/host/outputs/repo/com/github/tozny/java-aes-crypto/1.1.0/java-aes-crypto-1.1.0.pom
[        ]          file:/Users/username/Projects/myProject/flutter_lib/build/host/outputs/repo/com/github/tozny/java-aes-crypto/1.1.0/java-aes-crypto-1.1.0.jar
[        ]      Required by:
[        ]          project :flutter > com.github.sroddy.flutterstringencryption:flutter_string_encryption_release:1.0
[        ] * Try:
[        ] Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
[        ] * Get more help at https://help.gradle.org
[   +9 ms] Deprecated Gradle features were used in this build, making it incompatible with Gradle 5.0.
[        ] See https://docs.gradle.org/4.6/userguide/command_line_interface.html#sec:command_line_warnings
[        ] BUILD FAILED in 37s
[ +401 ms] Running Gradle task 'assembleAarRelease'... (completed in 37.6s)
[   +4 ms] "flutter aar" took 41,636ms.
Gradle task assembleAarRelease failed with exit code 1

#0      throwToolExit (package:flutter_tools/src/base/common.dart:28:3)
#1      buildGradleAar (package:flutter_tools/src/android/gradle.dart:594:5)
#2      _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:71:64)
#3      _rootRunUnary (dart:async/zone.dart:1132:38)
#4      _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#5      _FutureListener.handleValue (dart:async/future_impl.dart:137:18)
#6      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:678:45)
#7      Future._propagateToListeners (dart:async/future_impl.dart:707:32)
#8      Future._completeWithValue (dart:async/future_impl.dart:522:5)
#9      _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:30:15)
#10     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:288:13)
#11     runCommandAndStreamOutput (package:flutter_tools/src/base/process.dart)
#12     _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:71:64)
#13     _rootRunUnary (dart:async/zone.dart:1132:38)
#14     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#15     _FutureListener.handleValue (dart:async/future_impl.dart:137:18)
#16     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:678:45)
#17     Future._propagateToListeners (dart:async/future_impl.dart:707:32)
#18     Future._completeWithValue (dart:async/future_impl.dart:522:5)
#19     Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:552:7)
#20     _rootRun (dart:async/zone.dart:1124:13)
#21     _CustomZone.run (dart:async/zone.dart:1021:19)
#22     _CustomZone.runGuarded (dart:async/zone.dart:923:7)
#23     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:963:23)
#24     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#25     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#26     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:116:13)
#27     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:173:5)


```

## Flutter doctor
```

[✓] Flutter (Channel master, v1.9.8-pre.108, on Mac OS X 10.14.6 18G95, locale
    en-RU)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 10.2)
[✓] Android Studio (version 3.5)
[!] IntelliJ IDEA Community Edition (version 2018.3.5)
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
[✓] VS Code (version 1.36.1)
[✓] Connected device (1 available)

```

**Comment by askarsyzdykov** [comment]
@blasten hi, is it possible to add jitpack to build.gradle template or is there workaround?

**Comment by jonahwilliams** [comment]
If you want an editable build.gradle, I recommend creating a full android application instead of a module. I realize this is inconvenient, unfortunately the module format is quite limited
