### ISSUE TITLE
Android app is not running

### ISSUE THREAD

**Issue by icodepython** [flutter/flutter#39973]
My app works on iOS but when I run on android I get following error: please help!

```
Launching lib/main.dart on Android SDK built for x86 in debug mode...
Initializing gradle...
Finished with error: ProcessException: Process "/Users/username/Desktop/flutter_projects/myapp/android/gradlew" exited abnormally:
Downloading https://core.services.gradle.org/distributions/gradle-4.10.2-all.zip


Exception in thread "main" java.net.UnknownHostException: core.services.gradle.org
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:184)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:666)
	at sun.security.ssl.BaseSSLSocketImpl.connect(BaseSSLSocketImpl.java:173)
	at sun.net.NetworkClient.doConnect(NetworkClient.java:180)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:463)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:558)
	at sun.net.www.protocol.https.HttpsClient.<init>(HttpsClient.java:264)
	at sun.net.www.protocol.https.HttpsClient.New(HttpsClient.java:367)
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(AbstractDelegateHttpsURLConnection.java:191)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1156)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1050)
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:177)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1564)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1492)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:263)
	at org.gradle.wrapper.Download.downloadInternal(Download.java:58)
	at org.gradle.wrapper.Download.download(Download.java:44)
	at org.gradle.wrapper.Install$1.call(Install.java:61)
	at org.gradle.wrapper.Install$1.call(Install.java:48)
	at org.gradle.wrapper.ExclusiveFileAccessManager.access(ExclusiveFileAccessManager.java:65)
	at org.gradle.wrapper.Install.createDist(Install.java:48)
	at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:128)
	at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:61)
  Command: /Users/username/Desktop/flutterApps/myapp/android/gradlew -v
```

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, v1.7.8+hotfix.4, on Mac OS X 10.14.5 18F132, locale en-US)
 
[!] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses
[✓] Xcode - develop for iOS and macOS (Xcode 10.3)
[!] iOS tools - develop for iOS devices
    ✗ ideviceinstaller is not installed; this is used to discover connected iOS devices.
      To install with Brew, run:
        brew install --HEAD usbmuxd
        brew link usbmuxd
        brew install --HEAD libimobiledevice
        brew install ideviceinstaller
[✓] Android Studio (version 3.5)
[✓] Connected device (1 available)

! Doctor found issues in 2 categories.
```

**Comment by jonahwilliams** [comment]
This error indicates a failure to download the gradle version specified in your project's gradle wrapper. Try running again with a different/faster internet connection

**Comment by uzairleo** [comment]
bro we face the same issue ?

**Comment by alibabaintelligence** [comment]
your mom

**Comment by ephraimilunga** [comment]
Whoever faces this issue should do the following (**worked for me**) : 

Noticed the `core.` in `Downloading https://core.services.gradle.org/distributions/gradle-4.10.2-all.zip `  ?

Remove `core. ` so your URL should  now be :  

`Downloading https://services.gradle.org/distributions/gradle-4.10.2-all.zip`

**NOTE : The issue is that the Gradle Distributions URL has changed.**
