### ISSUE TITLE
Build AppBundle

### ISSUE THREAD

**Issue by chandrabezzo** [flutter/flutter#39974]
## flutter analyze
```
Analyzing simma...                                                      
No issues found! (ran in 6.4s)
```

## flutter doctor
```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, v1.7.8+hotfix.4, on Mac OS X 10.14.6 18G95, locale en-US)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 10.3)
[✓] iOS tools - develop for iOS devices
[✓] Android Studio (version 3.5)
[✓] IntelliJ IDEA Ultimate Edition (version 2018.3.6)
[✓] VS Code (version 1.37.1)
[!] Connected device
    ! No devices available

! Doctor found issues in 1 category.
```

```
flutter build appbundle --target-platform android-arm,android-arm64 -v
```
```
281 actionable tasks: 15 executed, 266 up-to-date
[ +360 ms] Running Gradle task 'bundleRelease'... (completed in 45.4s)
[  +22 ms] "flutter appbundle" took 50,223ms.
[        ] "flutter appbundle" took 50,223ms.
Gradle build failed to produce an Android bundle package.

#0      throwToolExit (package:flutter_tools/src/base/common.dart:28:3)
#1      _buildGradleProjectV2 (package:flutter_tools/src/android/gradle.dart:536:7)
#2      _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:77:64)
#3      _rootRunUnary (dart:async/zone.dart:1132:38)
#4      _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#5      _FutureListener.handleValue (dart:async/future_impl.dart:126:18)
#6      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:639:45)
#7      Future._propagateToListeners (dart:async/future_impl.dart:668:32)
#8      Future._complete (dart:async/future_impl.dart:473:7)
#9      _SyncCompleter.complete (dart:async/future_impl.dart:51:12)
#10     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:28:18)
#11     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:294:13)
#12     runCommandAndStreamOutput (package:flutter_tools/src/base/process.dart)
#13     _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:77:64)
#14     _rootRunUnary (dart:async/zone.dart:1132:38)
#15     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#16     _FutureListener.handleValue (dart:async/future_impl.dart:126:18)
#17     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:639:45)
#18     Future._propagateToListeners (dart:async/future_impl.dart:668:32)
#19     Future._completeWithValue (dart:async/future_impl.dart:483:5)
#20     Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:513:7)
#21     _rootRun (dart:async/zone.dart:1124:13)
#22     _CustomZone.run (dart:async/zone.dart:1021:19)
#23     _CustomZone.runGuarded (dart:async/zone.dart:923:7)
#24     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:963:23)
#25     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#26     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#27     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:116:13)
#28     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:173:5)
```

When I create flutter build apk --release not found problem overall working well. But when I try to build appbundle, this have an error. I not understand what should I do for resolve this error.

**Comment by BondarenkoStas** [comment]
This is a question better suited for StackOverflow, since there doesn’t seem to be anything wrong with Flutter itself, but related to gradle.
Looks very similar to #36067, please report if that will help. The case there was about underscore in the path, which is resolved on the ```master``` channel, but not in ```stable``` version which you use.

**Comment by chandrabezzo** [comment]
What do you mean about underscore? I don't have underscore path, maybe from my another library can make this error?

**Comment by chandrabezzo** [comment]
This issue I had resolve with downgrade de version at gradle

**Comment by rfogar2** [comment]
Any chance this will get a hotfix release?

**Comment by chandrabezzo** [comment]
Maybe Flutter team must support for all gradle version so this issue can solve. We must follow the version that recommend by Flutter, don't change version manually without know that version support or not.

**Comment by budioktaviyan** [comment]
This is still happen 'till now! and there's nothing to do with that ? @FlutterTeam ? do u mind to fix this for `stable` channel too ?

**Comment by Nico04** [comment]
Downgrading Gradle from 3.5.1 to 3.4.2 worked for me.

**Comment by M4iK26** [comment]
Still had the same problem - it did not worked with Gradle 3.5.2
**Downgrade to Gradle 3.4.2** helped.

**Comment by quetool** [comment]
I am getting the same issue, I am solving by generating bundle/apk from android studio. Don't know why flutter produce this issue now, everything was going well till last week

**Comment by adar2378** [comment]
Downgrade to Gradle 3.4.2 helped me too :D

**Comment by fajarainul** [comment]
I have to use Gradle 4.1.0 because of [this issue](https://stackoverflow.com/questions/62568757/playstore-error-app-bundle-contains-native-code-and-youve-not-uploaded-debug)

any ideas?

**Comment by chandrabezzo** [comment]
I think, prefer you don't change android internal gradle version
