### ISSUE TITLE
Oops; flutter has exited unexpectedly.

### ISSUE THREAD

**Issue by anwar907** [flutter/flutter#39987]
## command
```
flutter run
```
## exception
```
ProcessException: ProcessException: Process "/home/boot/workspace/cek/android/gradlew" exited abnormally:
Exception in thread "main" java.lang.RuntimeException: Timeout of 120000 reached waiting for exclusive access to file: /home/boot/.gradle/wrapper/dists/gradle-4.10.2-all/9fahxiiecdb76a5g3aw9oi8rv/gradle-4.10.2-all.zip
	at org.gradle.wrapper.ExclusiveFileAccessManager.access(ExclusiveFileAccessManager.java:61)
	at org.gradle.wrapper.Install.createDist(Install.java:48)
	at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:128)
	at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:61)
  Command: /home/boot/workspace/cek/android/gradlew -v
```
```
#0      runCheckedAsync (package:flutter_tools/src/base/process.dart:259:7)
<asynchronous suspension>
#1      _initializeGradle (package:flutter_tools/src/android/gradle.dart:225:9)
<asynchronous suspension>
#2      _ensureGradle (package:flutter_tools/src/android/gradle.dart:206:37)
<asynchronous suspension>
#3      _readGradleProject (package:flutter_tools/src/android/gradle.dart:134:31)
<asynchronous suspension>
#4      _gradleProject (package:flutter_tools/src/android/gradle.dart:111:34)
<asynchronous suspension>
#5      getGradleAppOut (package:flutter_tools/src/android/gradle.dart:105:29)
<asynchronous suspension>
#6      AndroidApk.fromAndroidProject (package:flutter_tools/src/application_package.dart:160:23)
<asynchronous suspension>
#7      ApplicationPackageFactory.getPackageForPlatform (package:flutter_tools/src/application_package.dart:47:32)
<asynchronous suspension>
#8      FlutterDevice.runHot (package:flutter_tools/src/resident_runner.dart:352:56)
<asynchronous suspension>
#9      HotRunner.run (package:flutter_tools/src/run_hot.dart:251:39)
<asynchronous suspension>
#10     RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:469:37)
<asynchronous suspension>
#11     FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:478:18)
<asynchronous suspension>
#12     FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:383:33)
<asynchronous suspension>
#13     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:29)
<asynchronous suspension>
#14     _rootRun (dart:async/zone.dart:1124:13)
#15     _CustomZone.run (dart:async/zone.dart:1021:19)
#16     _runZoned (dart:async/zone.dart:1516:10)
#17     runZoned (dart:async/zone.dart:1463:12)
#18     AppContext.run (package:flutter_tools/src/base/context.dart:152:18)
<asynchronous suspension>
#19     FlutterCommand.run (package:flutter_tools/src/runner/flutter_command.dart:375:20)
#20     CommandRunner.runCommand (package:args/command_runner.dart:197:27)
<asynchronous suspension>
#21     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:396:21)
<asynchronous suspension>
#22     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:29)
<asynchronous suspension>
#23     _rootRun (dart:async/zone.dart:1124:13)
#24     _CustomZone.run (dart:async/zone.dart:1021:19)
#25     _runZoned (dart:async/zone.dart:1516:10)
#26     runZoned (dart:async/zone.dart:1463:12)
#27     AppContext.run (package:flutter_tools/src/base/context.dart:152:18)
<asynchronous suspension>
#28     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:356:19)
<asynchronous suspension>
#29     CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:112:25)
#30     new Future.sync (dart:async/future.dart:224:31)
#31     CommandRunner.run (package:args/command_runner.dart:112:14)
#32     FlutterCommandRunner.run (package:flutter_tools/src/runner/flutter_command_runner.dart:242:18)
#33     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:62:22)
<asynchronous suspension>
#34     _rootRun (dart:async/zone.dart:1124:13)
#35     _CustomZone.run (dart:async/zone.dart:1021:19)
#36     _runZoned (dart:async/zone.dart:1516:10)
#37     runZoned (dart:async/zone.dart:1500:12)
#38     run.<anonymous closure> (package:flutter_tools/runner.dart:60:18)
<asynchronous suspension>
#39     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:29)
<asynchronous suspension>
#40     _rootRun (dart:async/zone.dart:1124:13)
#41     _CustomZone.run (dart:async/zone.dart:1021:19)
#42     _runZoned (dart:async/zone.dart:1516:10)
#43     runZoned (dart:async/zone.dart:1463:12)
#44     AppContext.run (package:flutter_tools/src/base/context.dart:152:18)
<asynchronous suspension>
#45     runInContext (package:flutter_tools/src/context_runner.dart:56:24)
<asynchronous suspension>
#46     run (package:flutter_tools/runner.dart:51:10)
#47     main (package:flutter_tools/executable.dart:62:9)
<asynchronous suspension>
#48     main (file:///home/boot/flutter/packages/flutter_tools/bin/flutter_tools.dart:8:3)
#49     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:299:32)
#50     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:12)
```

## flutter doctor

```
[32m[✓][39m Flutter (Channel stable, v1.7.8+hotfix.4, on Linux, locale en_US.UTF-8)
    [32m•[39m Flutter version 1.7.8+hotfix.4 at /home/boot/flutter
    [32m•[39m Framework revision 20e59316b8 (7 weeks ago), 2019-07-18 20:04:33 -0700
    [32m•[39m Engine revision fee001c93f
    [32m•[39m Dart version 2.4.0

[32m[✓][39m Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    [32m•[39m Android SDK at /home/boot/Android/Sdk
    [32m•[39m Android NDK location not configured (optional; useful for native profiling support)
    [32m•[39m Platform android-29, build-tools 29.0.2
    [32m•[39m Java binary at: /home/boot/android-studio/jre/bin/java
    [32m•[39m Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    [32m•[39m All Android licenses accepted.

[32m[✓][39m Android Studio (version 3.5)
    [32m•[39m Android Studio at /home/boot/android-studio
    [32m•[39m Flutter plugin version 39.0.3
    [32m•[39m Dart plugin version 191.8423
    [32m•[39m Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[32m[✓][39m IntelliJ IDEA Community Edition (version 2019.1)
    [32m•[39m IntelliJ at /home/boot/idea
    [32m•[39m Flutter plugin version 35.3.3
    [32m•[39m Dart plugin version 191.7221

[32m[✓][39m VS Code (version 1.38.0)
    [32m•[39m VS Code at /usr/share/code
    [32m•[39m Flutter extension version 3.4.1

[32m[✓][39m Connected device (1 available)
    [32m•[39m SM G610F • 33009f405dd093dd • android-arm • Android 8.1.0 (API 27)

[32m•[39m No issues found!
```

**Comment by anwar907** [comment]
[flutter_04.log](https://github.com/flutter/flutter/files/3585016/flutter_04.log)

**Comment by BondarenkoStas** [comment]
Seems to be the same as:
#39202
and as in other versions of flutter:
#34210
#33735
#38690

Please report if https://github.com/flutter/flutter/issues/39202#issuecomment-524658380 will help you.

**Comment by anwar907** [comment]
> Seems to be the same as:
> #39202
> and as in other versions of flutter:
> #34210
> #33735
> #38690
> 
> Please report if [#39202 (comment)](https://github.com/flutter/flutter/issues/39202#issuecomment-524658380) will help you.

I have try but this is not work

**Comment by BondarenkoStas** [comment]
@anwar907 It possibly may be an error in the implementation. Please provide  a small self-contained app that demonstrates the problem. You can include small examples [inline if they're enclosed by backticks](https://help.github.com/en/articles/creating-and-highlighting-code-blocks), or just provide a public link to a github "gist" - https://gist.github.com/.

**Comment by snehmehta** [comment]
**[SOLVED]**
Hey Guys, 
I had the same problem, i started flutter for first time and i had this error

```
ProcessException: ProcessException: Process "E:\Flutter\myapp\android\gradlew.bat" exited abnormally:
Exception in thread "main" java.lang.RuntimeException: Timeout of 120000 reached waiting for exclusive access to file: C:\Users\snehm\.gradle\wrapper\dists\gradle-4.10.2-all\9fahxiiecdb76a5g3aw9oi8rv\gradle-4.10.2-all.zip

```
And my brief flutter doctor is:

`Channel stable, v1.9.1+hotfix.5, on Microsoft Windows [Version 10.0.17763.805], locale en-IN
`

So what i did is download gradle-4.10.2-all from below link
https://gradle.org/next-steps/?version=4.10.2&format=all

and replace it with older thing in path 
`C:\Users\snehm\.gradle\wrapper\dists\gradle-4.10.2-all\9fahxiiecdb76a5g3aw9oi8rv\gradle-4.10.2-all.zip
`
Make sure you place it in right folder

**Comment by BondarenkoStas** [comment]
Oh

**Comment by iapicca** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact descriptions what happens, logs and the output of ' flutter doctor -v'  please.
All system setups can be slightly different so its always better to open new issues and reference related issues.
