### ISSUE TITLE
Dart SDK libraries and Flutter for web

### ISSUE THREAD

**Issue by jonahwilliams** [flutter/flutter#39998]
### Background

An *unsupported library* is either missing an implementation in the platform's libraries.json file, or has an implementation where all members throw when called.

The only mechanism for conditionally including code is config-specific imports and exports. The mechanism for using these is the presence/absence of an *unsupported library

### Specific Issues

- `dart:io` provides a reasonable set of functionality that we currently rely on in the framework. Specifically, we use the `HttpClient` to make network requests, `Platform` to detect the initial non-overridden platform, and `File` to transfer bytes across certain compute boundaries, like `Isolates` and through `PlatformChannels`. See also https://github.com/flutter/flutter/issues/32220, https://github.com/flutter/flutter/issues/36281, https://github.com/dart-lang/sdk/issues/35969

- The existing dart4web tooling refuses to compile applications to the web that have an *unsupported library* in the transitive closure, including `dart:isolate` and `dart:io`. Under this restriction, almost no current flutter applications will compile to the web unless all dependencies are rewritten to use config specific imports. See also https://github.com/dart-lang/build/pull/2420.

 - The analyzer does not support having multiple analysis summaries. Thus either dart libraries that exist are displayed as missing, or dart libraries that are missing are displayed as existing. See also https://github.com/flutter/flutter/issues/35588

- The analyzer is not capable of analyzing code that uses config specific imports beyond the default import case. Because it does not analyze other paths, the user is responsible for verifying that the interfaces are used in a compatible way. For example, an API incompatibility that will not be detected until compile time:

a.dart
```
import 'b.dart'
  if (dart.library.io) 'c.dart'

void main() {
  bar(1); // No error
}
```

b.dart
```
void bar(int x) { }
```

c.dart
```
import 'dart:io';

void bar(String x) { }
```

- The analyzer is not capable of analyzing code that uses config specific exports beyond the default export case. Config specific exports are required if a type from an *unsupported library* is a part of a public API. For example, to include `File` in an interface conditionally:

a.dart
```
export 'b.dart'
  if (dart.library.io) 'c.dart'
```
b.dart
```
void foo(Object file) {}
```

c.dart
```
import 'dart:io';

void foo(File file) {}
```

This relies on the fact that it is always safe to substitute the two APIs, but the caller will not get any information about which implementation is used, or when to use it.

- Pub is not capable of distinguishing between a library that conditionally supports Web/Flutter/Flutter for Web/VM. Specifically see https://github.com/flutter/flutter/issues/35588#issuecomment-524373451

### Library Delta

Due to the additional inclusion of web specific libraries that we can't currently remove, the delta between a Flutter for Mobile/Desktop and Flutter for Web is currently quite large. The complexity is entirely placed on our users to deal with:

Library | Web | Mobile/Desktop
-- | -- | --
ui | ✔ | ✔
async | ✔ | ✔
core | ✔ | ✔
collection | ✔ | ✔
typed_data | ✔ | ✔
developer | ✔ | ✔
convert | ✔ | ✔
math | ✔ | ✔
wasm | x | ✔
ffi | x | ✔
io | x | ✔
isolate | x| ✔
js | ✔| x
js_util | ✔ | x
html | ✔ | x
web_audio | ✔ | x
web_gl | ✔ | x
indexed_db | ✔ | x
web_sql | ✔ | x
svg | ✔ | x
mirrors | x | x

The only way to write an app, plugin, or package that works across all platforms without heavy use of config specific imports/exports is to _only_ touch libraries supported on all platforms. However this represents a lowest common denominator strategy, which is against the core principals of flutter.

### Comparison to method/message channels

Flutter already deals with platform specific features using platform channels. An asynchronous message is sent to the platform side, where platform code *may* respond (for example, a camera), or it might go into the void. The application author can choose to ignore the error or make a requirement, but Flutter itself does not make that choice.

The introduction of the web and web libraries has put us in a situation where we are deciding for the application author.

### Problems with `dart:html`

Due to the highly dynamic nature of the browser DOM, any usage of `dart:html` will transitively pull in almost all of the dart core libraries. These libraries are also somewhat intertwined with the implementation of dart2js, the production JavaScript compiler. This adds additional code size to all flutter applications, even though the only use case may be within the web implementation of dart:ui. The only alternative would be to use JavaScript interop, but this again pulls in `dart:html` transitively.

`dart:html` is also generated from a chrome IDL and may not be accurate for a given browser/version. It is somewhat equivalent to a code generated `dart:android` or `dart:ios` library.

### Rock and a Hard Place

It seems as if we either need dramatically better support for the config specific import or other conditional compilation feature, or we need to standardize the set of dart SDK libraries (even if some methods are unimplemented).

cc @Hixie @tvolkert @goderbauer @ferhatb

**Comment by yjbanov** [comment]
+1 We need a graceful solution to this problem. The web/vm dichotomy creates a barrier for plugin authors. The Flutter ecosystem grew under the assumption that `dart:io` is available, and simply removing it from the Web will make it harder to add Web support to existing plugins.

**Comment by tvolkert** [comment]
I recommended to @jonahwilliams that he put the options with pros and cons in a Google doc to better facilitate discussion.

**Comment by devoncarew** [comment]
> I think we should just dump every dart: library in there temporarily so that users don't see errors while building their plugin packages. We can supplement it with a lint that only allows web-specific dart: library imports in web plugin implementations.

This is feasible, and would ~match the behavior users see at runtime. 

> Would it be possible to configure the analyzer to use different sets of dart: libraries depending on whether the file is part of a plugin or part of the app?

It's something to consider, but it would add a lot of complexity; I'd prefer other solutions (like the lint one above).

> I think we could move a bit more quickly on the issue if we sat down and chatted for a bit sometime next week?

sgtm

**Comment by devoncarew** [comment]
And - re: the items about config specific imports above - my working understanding is that user's won't use them when building plugin; they would be using `dart:html` or js intereop.

**Comment by sh0umik** [comment]
Lot of packages depend on `dart:io` surely something need to be done.  Also there is no clear documentation on how to skip building for those files

```
transitive libraries have sdk dependencies that not supported on this platform:
mqtt_client|lib/mqtt_client.dart
```

Lets say if want to build without mqtt_client. Building without this lib wont hurt for web but i want to keep the lib for flutter native

**Comment by yjbanov** [comment]
> > I think we should just dump every dart: library in there temporarily so that users don't see errors while building their plugin packages. We can supplement it with a lint that only allows web-specific dart: library imports in web plugin implementations.
> 
> This is feasible, and would ~match the behavior users see at runtime.

In this mode what happens when a user attempts to auto-complete or find docs for the following classes: `Element`, `Window`, `Animation`, `Canvas`, `Point`? These classes exist both in `dart:ui`/`package:flutter` and in `dart:html`.

> > Would it be possible to configure the analyzer to use different sets of dart: libraries depending on whether the file is part of a plugin or part of the app?
> 
> It's something to consider, but it would add a lot of complexity; I'd prefer other solutions (like the lint one above).

Definitely no need to introduce unnecessary complexity. However, if the world we're heading towards is one that offers multiple sets of `dart:*` libraries in the same project, then we must make sure developers have the tools to navigate them fluently. If that requires more complexity in the tools, then that's a necessary complexity.

> > I think we could move a bit more quickly on the issue if we sat down and chatted for a bit sometime next week?

Has this chat happened yet? Any outcomes? If not, I'd like to participate.

**Comment by devoncarew** [comment]
We did discuss this; specifically, just the use of `dart:html` for Flutter web apps and plugins.

There's more details here: https://github.com/flutter/flutter/issues/35588#issuecomment-533246944, but we decided to add `dart:html` (and `dart:js` and `dart:js_util`) to the version of the Flutter SDK used for analysis, and create a lint which warns when dart:html is used in a context where those APIs won't be available at runtime (when the project is not a Flutter web project or a Flutter web plugin one).

**Comment by NicolasDionB** [comment]
@devoncarew That's good news! What about other packages like `dart:web_audio`?

**Comment by AndiDog** [comment]
Is there any working way right now of importing platform-specific code? I'm trying to distinguish use of raw grpc channel (works on iOS) vs. grpc-web channel (works on web, but not on iOS because of `dart:html` features not available).

This is surely also a big issue for library developers who want to create cross-platform code. In my example, the grpc-web feature fails to build on iOS due to

```
Compiler message:
../../../../.pub-cache/hosted/pub.dartlang.org/grpc-2.1.3/lib/src/client/transport/xhr_transport.dart:17:8: Error: Not found: 'dart:html'
import 'dart:html';
       ^
../../../../.pub-cache/hosted/pub.dartlang.org/http-0.12.0+4/lib/src/browser_client.dart:6:8: Error: Not found: 'dart:html'
import 'dart:html';
       ^
../../../../.pub-cache/hosted/pub.dartlang.org/grpc-2.1.3/lib/src/client/transport/xhr_transport.dart:30:9: Error: Type 'HttpRequest' not found.
  final HttpRequest _request;
        ^^^^^^^^^^^
[...]
```

I've tried [several ways already](https://stackoverflow.com/q/60336921/245706), but none of them worked.

Don't really want to use a hacky scripted solution, e.g. overwriting a code file before `flutter run -d <web-or-ios>`, if there's a viable Dart solution.

**Comment by NicolasDionB** [comment]
@AndiDog Sure! We use the following technique in our project and it works great. Only thing right now is that it's not possible to run unit test for web. But other than that, you can use imports like this:

```dart
import 'package:yourapp/myclass.dart' if (dart.library.html) 'package:yourapp/myclass_web.dart';
```

So this way you can use a different class definition for web and use `dasrt:html` in it where in your other class you can use `dart:io` or any generally available flutter package. Just be sure to have equivalent methods in both classes as you will get errors otherwise. I recommend using a base abstract class/interface. Hope this helps.

**Comment by AndiDog** [comment]
Exactly that type of if-else import did not work for me, more exactly with a use case where my application should talk grpc-web protocol on web, but raw gRPC on iOS – because grpc-web doesn't compile on iOS and raw grpc TLS connections are impossible in web browsers. Used the `if (dart.library.html)` approach and it still didn't work. I ended up doing the script solution for now, which replaces the source file before the platform build runs...

If you believe this should work, please ping me again and I will provide a reproducible example repo.

**Comment by muhleder** [comment]
Conditional imports on the web platform were broken for a while on the master branch. They should do what you need.

**Comment by Sunbreak** [comment]
> Exactly that type of if-else import did not work for me, more exactly with a use case where my application should talk grpc-web protocol on web, but raw gRPC on iOS – because grpc-web doesn't compile on iOS and raw grpc TLS connections are impossible in web browsers. Used the `if (dart.library.html)` approach and it still didn't work. I ended up doing the script solution for now, which replaces the source file before the platform build runs...
> 
> If you believe this should work, please ping me again and I will provide a reproducible example repo.

`Federated Plugin` may help: https://docs.google.com/document/d/1LD7QjmzJZLCopUrFAAE98wOUQpjmguyGTN2wd_89Srs/edit

Use `plugin_platform_interface` to abstract Dart VM and dartjs

Official example: [url_launcher](https://github.com/flutter/plugins/tree/master/packages/url_launcher)

Our own BLE example: [notepad_core](https://github.com/woodemi/notepad_core)

**Comment by deakjahn** [comment]
@AndiDog federated plugins. Nothing else really but that solves the problem all right.

And this also shows that the support is somehow already there. With federated plugins, you don't receive any warnings and it just works as expected. But of course, this adds extra complexity.

I'm in the process of turning my app into web while constantly checking at every corner that it stays Androd/iOS as well, compiles without warnings and runs correctly (and I'm determined to bend over backwards to ensure that). The app originally relied on many plugins that don't have web support yet. I added the support myself for the most important ones, some of those I even contributed back to the original authors. Those are re-engineered into federated plugins now.

I also had my own platform-specific support in my app, no separate plugin but using the same `MethodChannel` approach directly from `MainActivity.kt` and its iOS counterpart. While doing the initial steps of porting, I kinda had the feeling that it would be elegant to turn those into a federated plugin as well but resisted the temptation of major refactoring just for the sake of elegance.

Well, as it became clear later on, this was inevitable, not just elegant. So, all my platform specific support was moved into a federated plugin *inside* my app. All three usual federated parts (interface, original platform for mobile, web platform) are now libraries inside.

In one or two places, especially where the plugin author went at great lengths to provide backing support for this, I was able to use conditional imports. And if you really have a very simple set of functions or classes that you can duplicate exactly, these imports can help. But I have a feeling that federated plugins are the only really reliable and universal way to tackle this for now.

And this is not something the majority of users will like. They simply want the same source to run on all platforms, with very little tweaking, and only tweaking where the program logic calls for it, not merely because the tooling wants it.

**Comment by iapicca** [comment]
Hi all,
please include [grpc](https://pub.dev/packages/grpc) to the list
https://github.com/flutter/flutter/issues/48054
thank you

**Comment by len8657** [comment]
> Is there any working way right now of importing platform-specific code? I'm trying to distinguish use of raw grpc channel (works on iOS) vs. grpc-web channel (works on web, but not on iOS because of `dart:html` features not available).
> 
> This is surely also a big issue for library developers who want to create cross-platform code. In my example, the grpc-web feature fails to build on iOS due to
> 
> ```
> Compiler message:
> ../../../../.pub-cache/hosted/pub.dartlang.org/grpc-2.1.3/lib/src/client/transport/xhr_transport.dart:17:8: Error: Not found: 'dart:html'
> import 'dart:html';
>        ^
> ../../../../.pub-cache/hosted/pub.dartlang.org/http-0.12.0+4/lib/src/browser_client.dart:6:8: Error: Not found: 'dart:html'
> import 'dart:html';
>        ^
> ../../../../.pub-cache/hosted/pub.dartlang.org/grpc-2.1.3/lib/src/client/transport/xhr_transport.dart:30:9: Error: Type 'HttpRequest' not found.
>   final HttpRequest _request;
>         ^^^^^^^^^^^
> [...]
> ```
> 
> I've tried [several ways already](https://stackoverflow.com/q/60336921/245706), but none of them worked.
> 
> Don't really want to use a hacky scripted solution, e.g. overwriting a code file before `flutter run -d <web-or-ios>`, if there's a viable Dart solution.



> Is there any working way right now of importing platform-specific code? I'm trying to distinguish use of raw grpc channel (works on iOS) vs. grpc-web channel (works on web, but not on iOS because of `dart:html` features not available).
> 
> This is surely also a big issue for library developers who want to create cross-platform code. In my example, the grpc-web feature fails to build on iOS due to
> 
> ```
> Compiler message:
> ../../../../.pub-cache/hosted/pub.dartlang.org/grpc-2.1.3/lib/src/client/transport/xhr_transport.dart:17:8: Error: Not found: 'dart:html'
> import 'dart:html';
>        ^
> ../../../../.pub-cache/hosted/pub.dartlang.org/http-0.12.0+4/lib/src/browser_client.dart:6:8: Error: Not found: 'dart:html'
> import 'dart:html';
>        ^
> ../../../../.pub-cache/hosted/pub.dartlang.org/grpc-2.1.3/lib/src/client/transport/xhr_transport.dart:30:9: Error: Type 'HttpRequest' not found.
>   final HttpRequest _request;
>         ^^^^^^^^^^^
> [...]
> ```
> 
> I've tried [several ways already](https://stackoverflow.com/q/60336921/245706), but none of them worked.
> 
> Don't really want to use a hacky scripted solution, e.g. overwriting a code file before `flutter run -d <web-or-ios>`, if there's a viable Dart solution.

how to solve this problem,I need you  help

**Comment by NicolasDionB** [comment]
@len8657 If you read the original post, you can see that there is an `if` statement that you can use in your imports, as follows:

```
import 'b.dart'
  if (dart.library.io) 'c.dart'

void main() {
  bar(1); // No error
}
```

With this technique, one could check with on the html library and make a conditional import specific for web:

```
import 'my_class.dart'
  if (dart.library.html) 'my_class_web.dart'
```

We used this in our project and it works like a charm!

**Comment by adigujjar** [comment]
I got this error when try to run on chrome :(
Error: Unsupported operation: Platform._version
    at Object.throw_ [as throw] (http://localhost:65025/dart_sdk.js:4348:11)
    at Function._version (http://localhost:65025/dart_sdk.js:55019:17)
    at Function.get version [as version] (http://localhost:65025/dart_sdk.js:55093:27)
    at get _version (http://localhost:65025/dart_sdk.js:54963:27)
    at Function.desc.get [as _version] (http://localhost:65025/dart_sdk.js:4842:17)
    at Function.get version [as version] (http://localhost:65025/dart_sdk.js:54937:26)
    at Object._getHttpVersion (http://localhost:65025/dart_sdk.js:191712:31)
    at new _http._HttpClient.new (http://localhost:65025/dart_sdk.js:186683:28)
    at Function.new (http://localhost:65025/dart_sdk.js:181124:16)
    at get _httpClient (http://localhost:65025/dart_sdk.js:191708:34)
    at Function.desc.get [as _httpClient] (http://localhost:65025/dart_sdk.js:4842:17)
    at Function.connect (http://localhost:65025/dart_sdk.js:191326:35)
    at Function.connect (http://localhost:65025/dart_sdk.js:190033:35)
    at Function.connect (http://localhost:65025/packages/web_socket_channel/io.dart.lib.js:76:94)
    at get channel (http://localhost:65025/packages/magic_game/pages/playerGasture/TriangleShape.dart.lib.js:27016:36)
    at Function.desc.get [as channel] (http://localhost:65025/dart_sdk.js:4873:17)
    at Function.listenToSocket (http://localhost:65025/packages/magic_game/pages/playerGasture/TriangleShape.dart.lib.js:26961:48)
    at main$ (http://localhost:65025/packages/magic_game/pages/playerGasture/TriangleShape.dart.lib.js:27047:33)
    at main (http://localhost:65025/web_entrypoint.dart.lib.js:34:27)
    at main.next (<anonymous>)
    at http://localhost:65025/dart_sdk.js:37956:33
    at _RootZone.runUnary (http://localhost:65025/dart_sdk.js:37810:58)
    at _FutureListener.thenAwait.handleValue (http://localhost:65025/dart_sdk.js:32771:29)
    at handleValueCallback (http://localhost:65025/dart_sdk.js:33319:49)
    at Function._propagateToListeners (http://localhost:65025/dart_sdk.js:33357:17)
    at async._AsyncCallbackEntry.new.callback (http://localhost:65025/dart_sdk.js:33082:27)
    at Object._microtaskLoop (http://localhost:65025/dart_sdk.js:38071:13)
    at _startMicrotaskLoop (http://localhost:65025/dart_sdk.js:38077:13)
    at http://localhost:65025/dart_sdk.js:33574:9

**Comment by nicksnz3k** [comment]
> I got this error when try to run on chrome :(
> Error: Unsupported operation: Platform._version at Object.throw_ [as throw] (http://localhost:65025/dart_sdk.js:4348:11)
> at new _http._HttpClient.new (http://localhost:65025/dart_sdk.js:186683:28)

HttpClient error

**"http_client_base.dart"**
`
import 'package:http/http.dart';

BaseClient createHttpClient() => throw UnsupportedError(
    'Cannot create a client without dart:html or dart:io.');
`

**"http_client_nonweb.dart"**
`
import 'dart:io';

import 'package:http/http.dart';
import 'package:http/io_client.dart';

BaseClient createHttpClient() {
  HttpClient client = new HttpClient();
  client.connectionTimeout = new Duration(seconds: 30);
  return IOClient(client);
}
`

**"http_client_web.dart"**
`
import 'package:http/browser_client.dart';
import 'package:http/http.dart';

BaseClient createHttpClient() => BrowserClient();
`

**"WebApiClient.dart"**
`
import 'dart:convert';
import 'package:http/http.dart';
import 'package:http/io_client.dart';
import 'package:http/http.dart' as http;
import 'package:flutter/foundation.dart' show kIsWeb;
import 'package:meta/meta.dart';

// ignore: uri_does_not_exist
import 'http_client_base.dart'
// ignore: uri_does_not_exist
if (dart.library.html) 'http_client_web.dart'
// ignore: uri_does_not_exist
if (dart.library.io) 'http_client_nonweb.dart';

class WebApiClient {
  AccessToken _token = AccessToken();

  //static WebApiClient _instance;

  final BaseClient _client = createHttpClient();
}
`

**Comment by jimsnab** [comment]
> * twork requests, `Platform` to d

This is not really the answer, it is mixing interfaces. Aside from the basic functions having different arguments, how do you specify a private CA cert to BrowserClient?

For a technology that sets out to be cross platform for the Web, this inconsistent and incomplete support of HTTP, which I would think is a day 0 requirement, is causing me to strongly considering abandoning flutter.
