### ISSUE TITLE
Dropdown error

### ISSUE THREAD

**Issue by eSoftGic** [flutter/flutter#40077]
I am using flutter_form_builder.dart, following error is generated when initializing blank form for 
new entry.
```
I/flutter ( 6025): fetching state
I/flutter ( 6025): ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
I/flutter ( 6025): The following assertion was thrown building
I/flutter ( 6025): FormField<dynamic>-[LabeledGlobalKey<FormFieldState<dynamic>>#4371c](dirty, dependencies:
I/flutter ( 6025): [_FormScope], state: FormFieldState<dynamic>#565a4):
I/flutter ( 6025): 'package:flutter/src/material/dropdown.dart': Failed assertion: line 608 pos 15: 'items == null ||
I/flutter ( 6025): items.isEmpty || value == null || items.where((DropdownMenuItem<T> item) => item.value ==
I/flutter ( 6025): value).length == 1': is not true.
I/flutter ( 6025): 
I/flutter ( 6025): Either the assertion indicates an error in the framework itself, or we should provide substantially
I/flutter ( 6025): more information in this error message to help you determine and fix the underlying cause.
I/flutter ( 6025): In either case, please report this assertion by filing a bug on GitHub:
I/flutter ( 6025):   https://github.com/flutter/flutter/issues/new?template=BUG.md
I/flutter ( 6025): 
I/flutter ( 6025): When the exception was thrown, this was the stack:
I/flutter ( 6025): #2      new DropdownButton (package:flutter/src/material/dropdown.dart:608:15)
I/flutter ( 6025): #3      _FormBuilderDropdownState.build.<anonymous closure> (package:flutter_form_builder/src/fields/form_builder_dropdown.dart:104:20)
I/flutter ( 6025): #4      FormFieldState.build (package:flutter/src/widgets/form.dart)
I/flutter ( 6025): #5      StatefulElement.build (package:flutter/src/widgets/framework.dart:4012:27)
I/flutter ( 6025): #6      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3924:15)
I/flutter ( 6025): #7      Element.rebuild (package:flutter/src/widgets/framework.dart:3721:5)
I/flutter ( 6025): #8      StatefulElement.update (package:flutter/src/widgets/framework.dart:4085:5)
I/flutter ( 6025): #9      Element.updateChild (package:flutter/src/widgets/framework.dart:2876:15)
I/flutter ( 6025): #10     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3935:16)
I/flutter ( 6025): #11     Element.rebuild (package:flutter/src/widgets/framework.dart:3721:5)
I/flutter ( 6025): #12     StatefulElement.update (package:flutter/src/widgets/framework.dart:4085:5)
I/flutter ( 6025): #13     Element.updateChild (package:flutter/src/widgets/framework.dart:2876:15)
I/flutter ( 6025): #14     RenderObjectElement.updateChildren (package:flutter/src/widgets/framework.dart:4817:32)
I/flutter ( 6025): #15     MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:5208:17)
I/flutter ( 6025): #16     Element.updateChild (package:flutter/src/widgets/framework.dart:2876:15)
I/flutter ( 6025): #17     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3935:16)
I/flutter ( 6025): #18     Element.rebuild (package:flutter/src/widgets/framework.dart:3721:5)
I/flutter ( 6025): #19     ProxyElement.update (package:flutter/src/widgets/framework.dart:4219:5)
I/flutter ( 6025): #20     Element.updateChild (package:flutter/src/widgets/framework.dart:2876:15)
I/flutter ( 6025): #21     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3935:16)
I/flutter ( 6025): #22     Element.rebuild (package:flutter/src/widgets/framework.dart:3721:5)
I/flutter ( 6025): #23     StatefulElement.update (package:flutter/src/widgets/framework.dart:4085:5)
I/flutter ( 6025): #24     Element.updateChild (package:flutter/src/widgets/framework.dart:2876:15)
I/flutter ( 6025): #25     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3935:16)
I/flutter ( 6025): #26     Element.rebuild (package:flutter/src/widgets/framework.dart:3721:5)
I/flutter ( 6025): #27     StatefulElement.update (package:flutter/src/widgets/framework.dart:4085:5)
I/flutter ( 6025): #28     Element.updateChild (package:flutter/src/widgets/framework.dart:2876:15)
I/flutter ( 6025): #29     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3935:16)
I/flutter ( 6025): #30     Element.rebuild (package:flutter/src/widgets/framework.dart:3721:5)
I/flutter ( 6025): #31     StatefulElement.update (package:flutter/src/widgets/framework.dart:4085:5)
I/flutter ( 6025): #32     Element.updateChild (package:flutter/src/widgets/framework.dart:2876:15)
I/flutter ( 6025): #33     RenderObjectElement.updateChildren (package:flutter/src/widgets/framework.dart:4817:32)
I/flutter ( 6025): #34     MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:5208:17)
I/flutter ( 6025): #35     Element.updateChild (package:flutter/src/widgets/framework.dart:2876:15)
I/flutter ( 6025): #36     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:5099:14)
I/flutter ( 6025): #37     Element.updateChild (package:flutter/src/widgets/framework.dart:2876:15)
I/flutter ( 6025): #38     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:5099:14)
I/flutter ( 6025): #39     Element.updateChild (package:flutter/src/widgets/framework.dart:2876:15)
I/flutter ( 6025): #40     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:5099:14)
I/flutter ( 6025): #41     Element.updateChild (package:flutter/src/widgets/framework.dart:2876:15)
I/flutter ( 6025): #42     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:5099:14)
I/flutter ( 6025): #43     Element.updateChild (package:flutter/src/widgets/framework.dart:2876:15)
I/flutter ( 6025): #44     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:5099:14)
I/flutter ( 6025): #45     Element.updateChild (package:flutter/src/widgets/framework.dart:2876:15)
I/flutter ( 6025): #46     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3935:16)
I/flutter ( 6025): #47     Element.rebuild (package:flutter/src/widgets/framework.dart:3721:5)
I/flutter ( 6025): #48     StatefulElement.update (package:flutter/src/widgets/framework.dart:4085:5)
I/flutter ( 6025): #49     Element.updateChild (package:flutter/src/widgets/framework.dart:2876:15)
I/flutter ( 6025): #50     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:5099:14)
I/flutter ( 6025): #51     Element.updateChild (package:flutter/src/widgets/framework.dart:2876:15)
I/flutter ( 6025): #52     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3935:16)
I/flutter ( 6025): #53     Element.rebuild (package:flutter/src/widgets/framework.dart:3721:5)
I/flutter ( 6025): #54     ProxyElement.update (package:flutter/src/widgets/framework.dart:4219:5)
I/flutter ( 6025): #55     Element.updateChild (package:flutter/src/widgets/framework.dart:2876:15)
I/flutter ( 6025): #56     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:5099:14)
I/flutter ( 6025): #57     Element.updateChild (package:flutter/src/widgets/framework.dart:2876:15)
I/flutter ( 6025): #58     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:5099:14)
I/flutter ( 6025): #59     Element.updateChild (package:flutter/src/widgets/framework.dart:2876:15)
I/flutter ( 6025): #60     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:5099:14)
I/flutter ( 6025): #61     Element.updateChild (package:flutter/src/widgets/framework.dart:2876:15)
I/flutter ( 6025): #62     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:5099:14)
I/flutter ( 6025): #63     Element.updateChild (package:flutter/src/widgets/framework.dart:2876:15)
I/flutter ( 6025): #64     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3935:16)
I/flutter ( 6025): #65     Element.rebuild (package:flutter/src/widgets/framework.dart:3721:5)
I/flutter ( 6025): #66     StatelessElement.update (package:flutter/src/widgets/framework.dart:3981:5)
I/flutter ( 6025): #67     Element.updateChild (package:flutter/src/widgets/framework.dart:2876:15)
I/flutter ( 6025): #68     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3935:16)
I/flutter ( 6025): #69     Element.rebuild (package:flutter/src/widgets/framework.dart:3721:5)
I/flutter ( 6025): #70     StatefulElement.update (package:flutter/src/widgets/framework.dart:4085:5)
I/flutter ( 6025): #71     Element.updateChild (package:flutter/src/widgets/framework.dart:2876:15)
I/flutter ( 6025): #72     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3935:16)
I/flutter ( 6025): #73     Element.rebuild (package:flutter/src/widgets/framework.dart:3721:5)
I/flutter ( 6025): #74     StatefulElement.update (package:flutter/src/widgets/framework.dart:4085:5)
I/flutter ( 6025): #75     Element.updateChild (package:flutter/src/widgets/framework.dart:2876:15)
I/flutter ( 6025): #76     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3935:16)
I/flutter ( 6025): #77     Element.rebuild (package:flutter/src/widgets/framework.dart:3721:5)
I/flutter ( 6025): #78     ProxyElement.update (package:flutter/src/widgets/framework.dart:4219:5)
I/flutter ( 6025): #79     Element.updateChild (package:flutter/src/widgets/framework.dart:2876:15)
I/flutter ( 6025): #80     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3935:16)
I/flutter ( 6025): #81     Element.rebuild (package:flutter/src/widgets/framework.dart:3721:5)
I/flutter ( 6025): #82     StatelessElement.update (package:flutter/src/widgets/framework.dart:3981:5)
I/flutter ( 6025): #83     Element.updateChild (package:flutter/src/widgets/framework.dart:2876:15)
I/flutter ( 6025): #84     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:5099:14)
I/flutter ( 6025): #85     Element.updateChild (package:flutter/src/widgets/framework.dart:2876:15)
I/flutter ( 6025): #86     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3935:16)
I/flutter ( 6025): #87     Element.rebuild (package:flutter/src/widgets/framework.dart:3721:5)
I/flutter ( 6025): #88     ProxyElement.update (package:flutter/src/widgets/framework.dart:4219:5)
I/flutter ( 6025): #89     Element.updateChild (package:flutter/src/widgets/framework.dart:2876:15)
I/flutter ( 6025): #90     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3935:16)
I/flutter ( 6025): #91     Element.rebuild (package:flutter/src/widgets/framework.dart:3721:5)
I/flutter ( 6025): #92     ProxyElement.update (package:flutter/src/widgets/framework.dart:4219:5)
I/flutter ( 6025): #93     Element.updateChild (package:flutter/src/widgets/framework.dart:2876:15)
I/flutter ( 6025): #94     RenderObjectElement.updateChildren (package:flutter/src/widgets/framework.dart:4817:32)
I/flutter ( 6025): #95     MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:5208:17)
I/flutter ( 6025): #96     Element.updateChild (package:flutter/src/widgets/framework.dart:2876:15)
I/flutter ( 6025): #97     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3935:16)
I/flutter ( 6025): #98     Element.rebuild (package:flutter/src/widgets/framework.dart:3721:5)
I/flutter ( 6025): #99     StatefulElement.update (package:flutter/src/widgets/framework.dart:4085:5)
I/flutter ( 6025): #100    Element.updateChild (package:flutter/src/widgets/framework.dart:2876:15)
I/flutter ( 6025): #101    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3935:16)
I/flutter ( 6025): #102    Element.rebuild (package:flutter/src/widgets/framework.dart:3721:5)
I/flutter ( 6025): #103    ProxyElement.update (package:flutter/src/widgets/framework.dart:4219:5)
I/flutter ( 6025): #104    Element.updateChild (package:flutter/src/widgets/framework.dart:2876:15)
I/flutter ( 6025): #105    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3935:16)
I/flutter ( 6025): #106    Element.rebuild (package:flutter/src/widgets/framework.dart:3721:5)
I/flutter ( 6025): #107    StatefulElement.update (package:flutter/src/widgets/framework.dart:4085:5)
I/flutter ( 6025): #108    Element.updateChild (package:flutter/src/widgets/framework.dart:2876:15)
I/flutter ( 6025): #109    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:5099:14)
I/flutter ( 6025): #110    Element.updateChild (package:flutter/src/widgets/framework.dart:2876:15)
I/flutter ( 6025): #111    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3935:16)
I/flutter ( 6025): #112    Element.rebuild (package:flutter/src/widgets/framework.dart:3721:5)
I/flutter ( 6025): #113    StatelessElement.update (package:flutter/src/widgets/framework.dart:3981:5)
I/flutter ( 6025): #114    Element.updateChild (package:flutter/src/widgets/framework.dart:2876:15)
I/flutter ( 6025): #115    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:5099:14)
I/flutter ( 6025): #116    Element.updateChild (package:flutter/src/widgets/framework.dart:2876:15)
I/flutter ( 6025): #117    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3935:16)
I/flutter ( 6025): #118    Element.rebuild (package:flutter/src/widgets/framework.dart:3721:5)
I/flutter ( 6025): #119    StatefulElement.update (package:flutter/src/widgets/framework.dart:4085:5)
I/flutter ( 6025): #120    Element.updateChild (package:flutter/src/widgets/framework.dart:2876:15)
I/flutter ( 6025): #121    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3935:16)
I/flutter ( 6025): #122    Element.rebuild (package:flutter/src/widgets/framework.dart:3721:5)
I/flutter ( 6025): #123    StatefulElement.update (package:flutter/src/widgets/framework.dart:4085:5)
I/flutter ( 6025): #124    Element.updateChild (package:flutter/src/widgets/framework.dart:2876:15)
I/flutter ( 6025): #125    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3935:16)
I/flutter ( 6025): #126    Element.rebuild (package:flutter/src/widgets/framework.dart:3721:5)
I/flutter ( 6025): #127    ProxyElement.update (package:flutter/src/widgets/framework.dart:4219:5)
I/flutter ( 6025): #128    Element.updateChild (package:flutter/src/widgets/framework.dart:2876:15)
I/flutter ( 6025): #129    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3935:16)
I/flutter ( 6025): #130    Element.rebuild (package:flutter/src/widgets/framework.dart:3721:5)
I/flutter ( 6025): #131    ProxyElement.update (package:flutter/src/widgets/framework.dart:4219:5)
I/flutter ( 6025): #132    Element.updateChild (package:flutter/src/widgets/framework.dart:2876:15)
I/flutter ( 6025): #133    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3935:16)
I/flutter ( 6025): #134    Element.rebuild (package:flutter/src/widgets/framework.dart:3721:5)
I/flutter ( 6025): #135    StatefulElement.update (package:flutter/src/widgets/framework.dart:4085:5)
I/flutter ( 6025): #136    Element.updateChild (package:flutter/src/widgets/framework.dart:2876:15)
I/flutter ( 6025): #137    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3935:16)
```

**Comment by BondarenkoStas** [comment]
@eSoftGic Please provide  a small self-contained app that demonstrates the problem. You can include small examples [inline if they're enclosed by backticks](https://help.github.com/en/articles/creating-and-highlighting-code-blocks), or just provide a public link to a github "gist" - https://gist.github.com/.
Also please provide your ```flutter doctor -v``` output.
Please specify which version of ```flutter_form_builder``` you use.

**Comment by janmoppel** [comment]
Hello @eSoftGic !

Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the issue, if you have any more information for us; we will reopen it right away!

Thank you for your contribution.

P.S. If anyone still experience the same problem, please file a new issue with the information required in the template.
All system setups can be slightly different so it’s always better to open new issues and reference related issues.
