### ISSUE TITLE
Can not install and launch app after build 

### ISSUE THREAD

**Issue by zhouweidong** [flutter/flutter#40120]
[✓] Flutter (Channel stable, v1.7.8+hotfix.4, on Mac OS X 10.14.6 18G95, locale
    zh-Hans-CN)
    • Flutter version 1.7.8+hotfix.4 at /Users/zhouweidong/flutter/flutter
    • Framework revision 20e59316b8 (8 周前), 2019-07-18 20:04:33 -0700
    • Engine revision fee001c93f
    • Dart version 2.4.0

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/zhouweidong/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling
      support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_152-release-1248-b01)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 10.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.3, Build version 10G8
    • CocoaPods version 1.7.4

[✓] iOS tools - develop for iOS devices
    • ios-deploy 1.9.4

[✓] Android Studio (version 3.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 34.0.1
    • Dart plugin version 182.5215
    • Java version OpenJDK Runtime Environment (build
      1.8.0_152-release-1248-b01)

[!] IntelliJ IDEA Ultimate Edition (version 2017.2.1)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.dev/intellij-setup/#installing-the-plugins

[✓] Connected device (2 available)
    • Pixel     • HT69K0201716                         • android-arm64 • Android
      10 (API 29)
    • iPhone Xʀ • 803F3016-F5D4-44C6-89EA-96BBFAFB9289 • ios           •
      com.apple.CoreSimulator.SimRuntime.iOS-12-4 (simulator)
Here is message after "flutter doctor -v"

Now can not install and launch app after build 
here is error message:
Launching lib/main.dart on iPhone8 in debug mode...
Found saved certificate choice "iPhone Developer: Huaiqing Jia (LWV6L4VUQ9)". To clear, use "flutter config".
Signing iOS app for device deployment using developer identity: "iPhone Developer: Huaiqing Jia (LWV6L4VUQ9)"
Running Xcode build...
Xcode build done.                                           14.8s
Installing and launching...
Unhandled exception:
Bad state: Future already completed
#0      _AsyncCompleter.complete (dart:async/future_impl.dart:39:31)
#1      _NativeSocket.startConnect.<anonymous closure>.connectNext.<anonymous closure> (dart:io-patch/socket_patch.dart:521:23)
#2      _NativeSocket.issueWriteEvent.issue (dart:io-patch/socket_patch.dart:874:14)
#3      _NativeSocket.issueWriteEvent (dart:io-patch/socket_patch.dart:881:12)
#4      _NativeSocket.multiplex (dart:io-patch/socket_patch.dart:902:11)
#5      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:12)

**Comment by zhouweidong** [comment]
it is a network issues.
https://github.com/flutter/flutter/issues/27450
