### ISSUE TITLE
flutter --resident's ctrl-c doesn't shut down gracefully on android ("Unfortunately, <app name> has stopped" dialog).

### ISSUE THREAD

**Issue by apwilson** [flutter/flutter#4020]

**Comment by apwilson** [comment]
```
Showing Pixel C logs:
--------- beginning of main
I/flutter : touched anchor
I/flutter : delta -0.0
--------- beginning of system
--------- beginning of crash
F/libc    : Fatal signal 11 (SIGSEGV), code 1, fault addr 0xdae3ab88 in tid 25113 (ui_thread)
F/DEBUG   : *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
F/DEBUG   : Build fingerprint: 'google/ryu/dragon:6.0.1/MXC14G/2588522:user/release-keys'
F/DEBUG   : Revision: '0'
F/DEBUG   : ABI: 'arm'
F/DEBUG   : pid: 25098, tid: 25113, name: ui_thread  >>> <redacted> <<<
F/DEBUG   : signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0xdae3ab88
F/DEBUG   :     r0 00000000  r1 00000000  r2 00000003  r3 f4e67748
F/DEBUG   :     r4 e79fd1c0  r5 f4d82db8  r6 f4d82dfc  r7 dada5008
F/DEBUG   :     r8 e796dca0  r9 00000000  sl dae3a008  fp e79fc37c
F/DEBUG   :     ip e7b01ee8  sp ec69fe60  lr e74ff705  pc e74ff832  cpsr 600f0030
F/DEBUG   : 
F/DEBUG   : backtrace:
F/DEBUG   :     #00 pc 0056f832  /vendor/lib/libglcore.so
F/DEBUG   :     #01 pc 0056fabd  /vendor/lib/libglcore.so
F/DEBUG   :     #02 pc 005721cb  /vendor/lib/libglcore.so
F/DEBUG   :     #03 pc 00538f43  /vendor/lib/libglcore.so
F/DEBUG   :     #04 pc 005450c1  /vendor/lib/libglcore.so
F/DEBUG   :     #05 pc 003f0823  /vendor/lib/libglcore.so
F/DEBUG   :     #06 pc 003f07e7  /vendor/lib/libglcore.so
F/DEBUG   :     #07 pc 003f0997  /vendor/lib/libglcore.so
F/DEBUG   :     #08 pc 00542231  /vendor/lib/libglcore.so
F/DEBUG   :     #09 pc 003c2007  /vendor/lib/libglcore.so
F/DEBUG   :     #10 pc 0057538d  /vendor/lib/libglcore.so
F/DEBUG   :     #11 pc 00565a9b  /vendor/lib/libglcore.so
F/DEBUG   :     #12 pc 0000467d  /vendor/lib/egl/libGLESv2_tegra.so
F/DEBUG   :     #13 pc 0003d081  /vendor/lib/egl/libEGL_tegra.so
F/DEBUG   :     #14 pc 0003d10f  /vendor/lib/egl/libEGL_tegra.so
F/DEBUG   :     #15 pc 0000d4f1  /vendor/lib/egl/libEGL_tegra.so
F/DEBUG   :     #16 pc 000448e8  /vendor/lib/egl/libEGL_tegra.so
W/ActivityManager:   Force finishing activity <redacted>/org.domokit.sky.shell.SkyActivity
F/DEBUG   : 
F/DEBUG   : Tombstone written to: /data/tombstones/tombstone_03
W/ActivityManager: Exception thrown during pause
W/ActivityManager: android.os.DeadObjectException
W/ActivityManager: 	at android.os.BinderProxy.transactNative(Native Method)
W/ActivityManager: 	at android.os.BinderProxy.transact(Binder.java:503)
W/ActivityManager: 	at android.app.ApplicationThreadProxy.schedulePauseActivity(ApplicationThreadNative.java:727)
W/ActivityManager: 	at com.android.server.am.ActivityStack.startPausingLocked(ActivityStack.java:867)
W/ActivityManager: 	at com.android.server.am.ActivityStack.finishActivityLocked(ActivityStack.java:2907)
W/ActivityManager: 	at com.android.server.am.ActivityStack.finishTopRunningActivityLocked(ActivityStack.java:2763)
W/ActivityManager: 	at com.android.server.am.ActivityStackSupervisor.finishTopRunningActivityLocked(ActivityStackSupervisor.java:2760)
W/ActivityManager: 	at com.android.server.am.ActivityManagerService.handleAppCrashLocked(ActivityManagerService.java:12037)
W/ActivityManager: 	at com.android.server.am.ActivityManagerService.makeAppCrashingLocked(ActivityManagerService.java:11933)
W/ActivityManager: 	at com.android.server.am.ActivityManagerService.crashApplication(ActivityManagerService.java:12622)
W/ActivityManager: 	at com.android.server.am.ActivityManagerService.handleApplicationCrashInner(ActivityManagerService.java:12129)
W/ActivityManager: 	at com.android.server.am.NativeCrashListener$NativeCrashReporter.run(NativeCrashListener.java:86)

```

**Comment by apwilson** [comment]
I think this is fixed.
