### ISSUE TITLE
[web] Text with emojis or Chinese characters is clipped

### ISSUE THREAD

**Issue by deckerst** [flutter/flutter#40221]
Text rendering with the `enableExperimentalCanvasImplementation` flag fixes some issues (such as https://github.com/flutter/flutter/issues/36043), but line height computation is incorrect when the text includes emojis.

Example:
```dart
  TextMeasurementService.enableExperimentalCanvasImplementation = true;
  runApp(
    MaterialApp(
      home: Scaffold(
        body: Row(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            Container(
              width: 120,
              color: Colors.grey,
              child: Text('this is a text that contains emojis 🎉 so the line 🐱‍👤 height 🍱 computation is broken and the text gets clipped'),
            ),
            SizedBox(width: 4),
            Container(
              width: 120,
              color: Colors.grey,
              child: Text('this is a text that contains no emoji so the line height computation is fine'),
            ),
          ],
        ),
      ),
    ),
  );
```
![flutter-web-with-flag](https://user-images.githubusercontent.com/13898333/64670414-f497fa00-d49f-11e9-8045-23edfff43155.png)

I see the issue with:
- Safari on Mac
- Chrome on Mac & Windows
- Firefox on Windows

Curiously, there's no issue with Firefox on Mac.

flutter_web (forked) version: commit 3973ac (Sep 7)
Mac OS X 10.14.5 18F132, locale en-KR
Microsoft Windows [Version 10.0.18362.329], locale en-GB

**Comment by deckerst** [comment]
@mdebbar I just tried with flutter v1.12.11 and the new feature flag `FLUTTER_WEB_USE_EXPERIMENTAL_CANVAS_TEXT=true`.

Chrome on Mac (still clipped when there are emojis):
<img width="250" alt="Screen Shot 2019-11-25 at 9 18 59" src="https://user-images.githubusercontent.com/13898333/69504316-15330480-0f65-11ea-81b4-bb823f34dd92.png">

Firefox on Mac (emojis do not force higher lines, but we can see the text is overall slightly clipped, e.g. the descender of the `g`):
<img width="250" alt="Screen Shot 2019-11-25 at 9 22 48" src="https://user-images.githubusercontent.com/13898333/69504352-562b1900-0f65-11ea-8612-c92259c71140.png">

**Comment by kf6gpe** [comment]
Touching as part of an ongoing triage experiment.

**Comment by michaelchiowong** [comment]
Chinese characters are also shown strange when mixing with English when applying the enableExperimentalCanvasImplementation option during build.

![Screen Shot 2020-04-10 at 4 39 15 PM](https://user-images.githubusercontent.com/49760147/78976945-d388ac00-7b49-11ea-92ab-6be732fe16de.png)

**Comment by michaelchiowong** [comment]
Below are some other examples showing clipped characters. This is like fix a multi-line selection issue, but introducing several other major issue.

![Screen Shot 2020-04-10 at 4 41 24 PM](https://user-images.githubusercontent.com/49760147/78977109-206c8280-7b4a-11ea-901c-afc208244ddf.png)
![Screen Shot 2020-04-10 at 4 42 00 PM](https://user-images.githubusercontent.com/49760147/78977149-367a4300-7b4a-11ea-94cb-76f5a04ee0c5.png)

**Comment by iapicca** [comment]
Hi @deckerst 
testing the code below with the latest master
running `flutter run -d chrome --dart-define=FLUTTER_WEB_USE_SKIA=true`

<details>
  <summary>code sample</summary>

```dart
import 'package:flutter/material.dart';

  void main() =>
    runApp(
    MaterialApp(
      home: Scaffold(
        body: Row(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            Container(
              width: 120,
              color: Colors.grey,
              child: Text('this is a text that contains emojis 🎉 so the line 🐱‍👤 height 🍱 computation is broken and the text gets clipped'),
            ),
            SizedBox(width: 4),
            Container(
              width: 120,
              color: Colors.grey,
              child: Text('this is a text that contains no emoji so the line height computation is fine'),
            ),
          ],
        ),
      ),
    ),
  );

```

</details>


<details>
  <summary>logs</summary>

```bash
[ +294 ms] Launching lib/main.dart on Chrome in debug mode...
[  +77 ms] Updating assets
[ +216 ms] Syncing files to device Chrome...
[  +63 ms] Generating /Users/nevercode/Desktop/projects/master/android/app/src/main/java/io/flutter/plugins/GeneratedPluginRegistrant.java
[  +50 ms] <- reset
[  +16 ms] /Users/nevercode/development/flutter_master/bin/cache/dart-sdk/bin/dart --disable-dart-dev
/Users/nevercode/development/flutter_master/bin/cache/artifacts/engine/darwin-x64/frontend_server.dart.snapshot --sdk-root
/Users/nevercode/development/flutter_master/bin/cache/flutter_web_sdk/ --incremental --target=dartdevc --debugger-module-names -Ddart.developer.causal_async_stacks=true
-DFLUTTER_WEB_USE_SKIA=true --output-dill /var/folders/c3/l5jpznsj5k37yrj47l__xpw40000gn/T/flutter_tools.ZPVAs4/flutter_tool.spBknE/app.dill --libraries-spec
file:///Users/nevercode/development/flutter_master/bin/cache/flutter_web_sdk/libraries.json --packages .packages -Ddart.vm.profile=false -Ddart.vm.product=false
--bytecode-options=source-positions,local-var-info,debugger-stops,instance-field-initializers,keep-unreachable-code,avoid-closure-call-instructions --enable-asserts
--track-widget-creation --filesystem-root /var/folders/c3/l5jpznsj5k37yrj47l__xpw40000gn/T/flutter_tools.ZPVAs4/flutter_tools.oe3lSk --filesystem-scheme org-dartlang-app
--initialize-from-dill build/dfea9bfe94cb64da780a8ef62c567803.cache.dill.track.dill --platform
file:///Users/nevercode/development/flutter_master/bin/cache/flutter_web_sdk/kernel/flutter_ddc_sdk.dill
[  +17 ms] <- compile org-dartlang-app:/web_entrypoint.dart
[+11206 ms] Syncing files to device Chrome... (completed in 11,344ms, longer than expected)
[   +1 ms] Synced 21.5MB.
[        ] <- accept
[        ] Caching compiled dill
[ +879 ms] [CHROME]:
[   +1 ms] [CHROME]:DevTools listening on ws://127.0.0.1:51572/devtools/browser/0bd3d6e3-3c3b-455b-801d-415d13dcccef
[+5026 ms] Debug service listening on ws://127.0.0.1:51595/Yj_CyR9m8bg=

[ +277 ms] Debug service listening on ws://127.0.0.1:51595/Yj_CyR9m8bg=
[   +2 ms] Warning: Flutter's support for web development is not stable yet and hasn't
[        ] been thoroughly tested in production environments.
[        ] For more information see https://flutter.dev/web
[        ] 🔥  To hot restart changes while running, press "r" or "R".
[   +1 ms] For a more detailed help message, press "h". To quit, press "q".
[+4734 ms] Error: Unsupported operation: Picture.toImage not yet implemented for CanvasKit and HTML
                        at Object.throw_ [as throw] (http://localhost:51561/dart_sdk.js:4322:11)
                        at _engine.CkPicture.new.toImage (http://localhost:51561/dart_sdk.js:140409:17)
                        at DefaultShaderWarmUp.execute (http://localhost:51561/packages/flutter/src/painting/shader_warm_up.dart.lib.js:106:23)
                        at execute.next (<anonymous>)
                        at http://localhost:51561/dart_sdk.js:37203:33
                        at _RootZone.runUnary (http://localhost:51561/dart_sdk.js:37057:58)
                        at _FutureListener.thenAwait.handleValue (http://localhost:51561/dart_sdk.js:32041:29)
                        at handleValueCallback (http://localhost:51561/dart_sdk.js:32588:49)
                        at Function._propagateToListeners (http://localhost:51561/dart_sdk.js:32626:17)
                        at _Future.new.[_completeWithValue] (http://localhost:51561/dart_sdk.js:32469:23)
                        at async._AsyncCallbackEntry.new.callback (http://localhost:51561/dart_sdk.js:32491:35)
                        at Object._microtaskLoop (http://localhost:51561/dart_sdk.js:37318:13)
                        at _startMicrotaskLoop (http://localhost:51561/dart_sdk.js:37324:13)
                        at http://localhost:51561/dart_sdk.js:32843:9
```


</details>


<details>
  <summary>screenshot</summary>

![image](https://user-images.githubusercontent.com/45637986/86464233-bf62de00-bd37-11ea-8a33-ea86a8192590.png)


</details>


<details>
  <summary>doctor</summary>

```console
[✓] Flutter (Channel master, 1.20.0-3.0.pre.126, on Mac OS X 10.15.5 19F101, locale en-GB)
    • Flutter version 1.20.0-3.0.pre.126 at /Users/nevercode/development/flutter_master
    • Framework revision 462b0ea76e (15 hours ago), 2020-07-02 16:13:02 -0400
    • Engine revision 51ca1432b3
    • Dart version 2.9.0 (build 2.9.0-20.0.dev 8afe9875a6)


[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/nevercode/Library/Android/sdk
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.5, Build version 11E608c
    • CocoaPods version 1.9.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 46.0.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] VS Code
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.12.1

[✓] Connected device (4 available)
    • Pixel 3a (mobile) • 965AY0WP5C • android-arm64  • Android 10 (API 29)
    • macOS (desktop)   • macos      • darwin-x64     • Mac OS X 10.15.5 19F101
    • Web Server (web)  • web-server • web-javascript • Flutter Tools
    • Chrome (web)      • chrome     • web-javascript • Google Chrome 83.0.4103.116

• No issues found!
```

</details>

I cannot tell if the text isn't clipped due to emoj not shown
Keeping the issue open

Thank you

**Comment by mdebbar** [comment]
Deduplicating with https://github.com/flutter/flutter/issues/64792
