### ISSUE TITLE
Failed assertion: line 1773 pos 12: '_elements.contains(element)': is not true.

### ISSUE THREAD

**Issue by escamoteur** [flutter/flutter#40260]
Hi,

I was just playing a bit around to test the new structured errors.
So I added a `SingleChildScrollView`around the column of the default counter app and placed a Expanded around the Column which lead to an exception. I removed the Expanded again and saved and got this error here.

```

════════ Exception caught by widgets library ═══════════════════════════════════
The following assertion was thrown building Listener:
'package:flutter/src/widgets/framework.dart': Failed assertion: line 1773 pos 12: '_elements.contains(element)': is not true.


Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=BUG.md

User-created ancestor of the error-causing widget was
    SingleChildScrollView 
lib\main.dart:70
When the exception was thrown, this was the stack
#2      _InactiveElements.remove 
package:flutter/…/widgets/framework.dart:1773
#3      Element._retakeInactiveElement 
package:flutter/…/widgets/framework.dart:3059
#4      Element.inflateWidget 
package:flutter/…/widgets/framework.dart:3082
#5      Element.updateChild 
package:flutter/…/widgets/framework.dart:2897
#6      SingleChildRenderObjectElement.mount 
package:flutter/…/widgets/framework.dart:5129
...

This is the code while the error happens:


```
    return Scaffold(
      appBar: AppBar(

        title: Text(widget.title),
      ),
      body: Center(

        child: SingleChildScrollView(
                  child: Column(
            mainAxisAlignment: MainAxisAlignment.center,
            children: <Widget>[
              Text( 
                'You have pushed the button this many times:',
              ),
              Text(
                '$_counter',
                style: Theme.of(context).textTheme.display1,
              ),
            ],
          ),
        ),
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: _incrementCounter,
        tooltip: 'Increment',
        child: Icon(Icons.add),
      ), 
    );
  }
}
```

Removing the `SingleChildScrollView` and adding it again clears the exception.


![image](https://user-images.githubusercontent.com/16635729/64714288-ac3c0480-d4be-11e9-9d4b-aae3687c0019.png)


I use VS code with;

[√] Flutter (Channel master, v1.10.1-pre.41, on Microsoft Windows [Version 10.0.18362.295], locale de-DE)
    • Flutter version 1.10.1-pre.41 at C:\Entwicklung\flutter
    • Framework revision 5a3a46ada2 (4 days ago), 2019-09-07 18:37:41 -0400
    • Engine revision c9ea4dba8d
    • Dart version 2.5.0 (build 2.5.0-dev.4.0 ec7ec4ecf7)

 
[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at C:\Users\escam\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)
    • All Android licenses accepted.

[√] Android Studio (version 3.5)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 39.0.3
    • Dart plugin version 191.8423
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)

[√] IntelliJ IDEA Community Edition (version 2018.2)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2018.2.5
    • Flutter plugin version 29.1.3
    • Dart plugin version 182.4892.25

[√] VS Code, 64-bit edition (version 1.38.0)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Flutter extension version 3.4.1

[√] Connected device (1 available)
    • Android SDK built for x86 64 • emulator-5554 • android-x64 • Android 7.1.1 (API 25) (emulator)

**Comment by jacob314** [comment]
Fyi @InMatrix 
Example of hard to understand exceptions after a hot reload. Likely this case is due to a Flutter framework assertion that at minimum should get a detailed error message.

**Comment by Xentraxx** [comment]
I had the same error when changing in Dart DevTools from Android to IOS view.  The error persisted even when I changed back. After restarting the debugger it worked again. It happened only once. I wasn't able to reproduce the error afterwards.

**Comment by patniemeyer** [comment]
I am getting this error when I attempt to add AutomaticKeepAliveClientMixin to a view that is used in a TabBar.  It occurs consistently at a point where one of the (tabbed) views pushes a secondary view and then it returns.

**Comment by tharit-haup** [comment]
> I am getting this error when I attempt to add AutomaticKeepAliveClientMixin to a view that is used in a TabBar. It occurs consistently at a point where one of the (tabbed) views pushes a secondary view and then it returns.

Have you fixed this issue yet?

**Comment by Hannyul** [comment]
I had the same error when I tried to add ( theme in MaterialApp ) ,
when I stopped the debugging and re-run it again everything worked fine.

**Comment by chaochaox1990** [comment]
════════ (2) Exception caught by widgets library ═══════════════════════════════════════════════════
'package:flutter/src/widgets/framework.dart': Failed assertion: line 1786 pos 12: '_elements.contains(element)': is not true.
The relevant error-causing widget was: 
  MaterialApp file:///Users/limi/Desktop/installnew/install_master/lib/main.dart:117:24
════════════════════════════════════════════════════════════════════════════════════════════════════

════════ (3) Exception caught by widgets library ═══════════════════════════════════════════════════
'package:flutter/src/widgets/framework.dart': Failed assertion: line 1786 pos 12: '_elements.contains(element)': is not true.
The relevant error-causing widget was: 
  MaterialApp file:///Users/limi/Desktop/installnew/install_master/lib/main.dart:117:24
════════════════════════════════════════════════════════════════════════════════════════════════════

════════ (4) Exception caught by widgets library ═══════════════════════════════════════════════════
The getter 'userGestureInProgress' was called on null.
Receiver: null
Tried calling: userGestureInProgress
The relevant error-causing widget was: 
  MaterialApp file:///Users/limi/Desktop/installnew/install_master/lib/main.dart:117:24
════════════════════════════════════════════════════════════════════════════════════════════════════

**Comment by chaochaox1990** [comment]
════════ (2) Exception caught by widgets library ═══════════════════════════════════════════════════
'package:flutter/src/widgets/framework.dart': Failed assertion: line 1786 pos 12: '_elements.contains(element)': is not true.
The relevant error-causing widget was: 
  MaterialApp file:///Users/limi/Desktop/installnew/install_master/lib/main.dart:117:24
════════════════════════════════════════════════════════════════════════════════════════════════════

════════ (3) Exception caught by widgets library ═══════════════════════════════════════════════════
'package:flutter/src/widgets/framework.dart': Failed assertion: line 1786 pos 12: '_elements.contains(element)': is not true.
The relevant error-causing widget was: 
  MaterialApp file:///Users/limi/Desktop/installnew/install_master/lib/main.dart:117:24
════════════════════════════════════════════════════════════════════════════════════════════════════

════════ (4) Exception caught by widgets library ═══════════════════════════════════════════════════
The getter 'userGestureInProgress' was called on null.
Receiver: null
Tried calling: userGestureInProgress
The relevant error-causing widget was: 
  MaterialApp file:///Users/limi/Desktop/installnew/install_master/lib/main.dart:117:24
════════════════════════════════════════════════════════════════════════════════════════════════════

**Comment by chaochaox1990** [comment]
Anyone can show how to solve this issue.

**Comment by rohitsainik** [comment]
yes i am having same error when i naviget between diffrent screens in my application

**Comment by anilpandey071999** [comment]
did anyone was able to solve this issue? I also have the same problem

**Comment by markusaksli-nc** [comment]
I can't reproduce the original issue on the latest master `1.22.0-2.0.pre.59`.
<details>
 <summary>Code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        // This is the theme of your application.
        //
        // Try running your application with "flutter run". You'll see the
        // application has a blue toolbar. Then, without quitting the app, try
        // changing the primarySwatch below to Colors.green and then invoke
        // "hot reload" (press "r" in the console where you ran "flutter run",
        // or simply save your changes to "hot reload" in a Flutter IDE).
        // Notice that the counter didn't reset back to zero; the application
        // is not restarted.
        primarySwatch: Colors.blue,
        // This makes the visual density adapt to the platform that you run
        // the app on. For desktop platforms, the controls will be smaller and
        // closer together (more dense) than on mobile platforms.
        visualDensity: VisualDensity.adaptivePlatformDensity,
      ),
      home: MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key key, this.title}) : super(key: key);

  // This widget is the home page of your application. It is stateful, meaning
  // that it has a State object (defined below) that contains fields that affect
  // how it looks.

  // This class is the configuration for the state. It holds the values (in this
  // case the title) provided by the parent (in this case the App widget) and
  // used by the build method of the State. Fields in a Widget subclass are
  // always marked "final".

  final String title;

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  int _counter = 0;

  void _incrementCounter() {
    setState(() {
      // This call to setState tells the Flutter framework that something has
      // changed in this State, which causes it to rerun the build method below
      // so that the display can reflect the updated values. If we changed
      // _counter without calling setState(), then the build method would not be
      // called again, and so nothing would appear to happen.
      _counter++;
    });
  }

  @override
  Widget build(BuildContext context) {
    // This method is rerun every time setState is called, for instance as done
    // by the _incrementCounter method above.
    //
    // The Flutter framework has been optimized to make rerunning build methods
    // fast, so that you can just rebuild anything that needs updating rather
    // than having to individually change instances of widgets.
    return Scaffold(
      appBar: AppBar(
        // Here we take the value from the MyHomePage object that was created by
        // the App.build method, and use it to set our appbar title.
        title: Text(widget.title),
      ),
      body: Center(
        // Center is a layout widget. It takes a single child and positions it
        // in the middle of the parent.
        child: SingleChildScrollView(
          child: Expanded(
            child: Column(
              // Column is also a layout widget. It takes a list of children and
              // arranges them vertically. By default, it sizes itself to fit its
              // children horizontally, and tries to be as tall as its parent.
              //
              // Invoke "debug painting" (press "p" in the console, choose the
              // "Toggle Debug Paint" action from the Flutter Inspector in Android
              // Studio, or the "Toggle Debug Paint" command in Visual Studio Code)
              // to see the wireframe for each widget.
              //
              // Column has various properties to control how it sizes itself and
              // how it positions its children. Here we use mainAxisAlignment to
              // center the children vertically; the main axis here is the vertical
              // axis because Columns are vertical (the cross axis would be
              // horizontal).
              mainAxisAlignment: MainAxisAlignment.center,
              children: <Widget>[
                Text(
                  'You have pushed the button this many times:',
                ),
                Text(
                  '$_counter',
                  style: Theme.of(context).textTheme.headline4,
                ),
              ],
            ),
          ),
        ),
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: _incrementCounter,
        tooltip: 'Increment',
        child: Icon(Icons.add),
      ), // This trailing comma makes auto-formatting nicer for build methods.
    );
  }
}
```
</details>
<details>
 <summary>flutter doctor -v</summary>

```
[√] Flutter (Channel master, 1.22.0-2.0.pre.59, on Microsoft Windows [Version 10.0.19041.450], locale en-US)
    • Flutter version 1.22.0-2.0.pre.59 at C:\Development\flutter_master
    • Framework revision be7c7faee6 (7 hours ago), 2020-08-24 22:31:02 -0400
    • Engine revision 8107b36c7b
    • Dart version 2.10.0 (build 2.10.0-56.0.dev)

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
    • Android SDK at C:\Users\marku\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.1
    • Java binary at: C:\Users\marku\AppData\Local\JetBrains\Toolbox\apps\AndroidStudio\ch-0\193.6626763\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.6.5)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.6.30320.27
    • Windows 10 SDK version 10.0.18362.0

[√] Android Studio (version 4.0)
    • Android Studio at C:\Users\marku\AppData\Local\JetBrains\Toolbox\apps\AndroidStudio\ch-0\193.6626763
    • Flutter plugin version 47.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] Connected device (4 available)
    • sdk gphone x86 arm (mobile) • emulator-5554 • android-x86    • Android 11 (API 30) (emulator)
    • Windows (desktop)           • windows       • windows-x64    • Microsoft Windows [Version 10.0.19041.450]
    • Web Server (web)            • web-server    • web-javascript • Flutter Tools
    • Chrome (web)                • chrome        • web-javascript • Google Chrome 84.0.4147.135

• No issues found!
```
</details>

Could anyone who is still experiencing this issue please provide a [minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) with your `flutter doctor -v`

**Comment by harsh-joflee** [comment]
`FlutterPainter
lib/…/ViewCard/screen_fact_viewCard.dart:1580
When the exception was thrown, this was the stack
#2      _InactiveElements.remove
package:flutter/…/widgets/framework.dart:1964
#3      Element._retakeInactiveElement
package:flutter/…/widgets/framework.dart:3746
...     Normal element mounting (39 frames)
#42     Element.inflateWidget
package:flutter/…/widgets/framework.dart:3790
#43     MultiChildRenderObjectElement.inflateWidget
package:flutter/…/widgets/framework.dart:6422
#44     MultiChildRenderObjectElement.mount
package:flutter/…/widgets/framework.dart:6433
...     Normal element mounting (24 frames)
#68     Element.inflateWidget
package:flutter/…/widgets/framework.dart:3790
#69     Element.updateChild
package:flutter/…/widgets/framework.dart:3540
#70     RenderObjectToWidgetElement._rebuild
package:flutter/…/widgets/binding.dart:1198
#71     RenderObjectToWidgetElement.mount
package:flutter/…/widgets/binding.dart:1167
#72     RenderObjectToWidgetAdapter.attachToRenderTree.<anonymous closure>
package:flutter/…/widgets/binding.dart:1112
#73     BuildOwner.buildScope
package:flutter/…/widgets/framework.dart:2600
#74     RenderObjectToWidgetAdapter.attachToRenderTree
package:flutter/…/widgets/binding.dart:1111
#75     ScreenshotController.captureFromWidget
package:screenshot/screenshot.dart:158
#76     Constants.downloadWithScreenshot
package:psychology_facts/constants.dart:219
#77     ShareAndDownloadDialog.showQualityDialog.<anonymous closure>.<anonymous closure>
package:psychology_facts/Dialogs/share_and_download_dialog.dart:204
#78     GestureRecognizer.invokeCallback
package:flutter/…/gestures/recognizer.dart:198
#79     TapGestureRecognizer.handleTapUp
package:flutter/…/gestures/tap.dart:608
#80     BaseTapGestureRecognizer._checkUp
package:flutter/…/gestures/tap.dart:296
#81     BaseTapGestureRecognizer.handlePrimaryPointer
package:flutter/…/gestures/tap.dart:230
#82     PrimaryPointerGestureRecognizer.handleEvent
package:flutter/…/gestures/recognizer.dart:563
#83     PointerRouter._dispatch
package:flutter/…/gestures/pointer_router.dart:94
#84     PointerRouter._dispatchEventToRoutes.<anonymous closure>
package:flutter/…/gestures/pointer_router.dart:139
#85     _LinkedHashMapMixin.forEach (dart:collection-patch[/compact_hash.dart:539:8]())
#86     PointerRouter._dispatchEventToRoutes
package:flutter/…/gestures/pointer_router.dart:137
#87     PointerRouter.route
package:flutter/…/gestures/pointer_router.dart:123
#88     GestureBinding.handleEvent
package:flutter/…/gestures/binding.dart:439
#89     GestureBinding.dispatchEvent
package:flutter/…/gestures/binding.dart:419
#90     RendererBinding.dispatchEvent
package:flutter/…/rendering/binding.dart:322
#91     GestureBinding._handlePointerEventImmediately
package:flutter/…/gestures/binding.dart:374
#92     GestureBinding.handlePointerEvent
package:flutter/…/gestures/binding.dart:338
#93     GestureBinding._flushPointerEventQueue
package:flutter/…/gestures/binding.dart:296
#94     GestureBinding._handlePointerDataPacket
package:flutter/…/gestures/binding.dart:279
#98     _invoke1 (dart:ui[/hooks.dart:170:10]())
#99     PlatformDispatcher._dispatchPointerDataPacket (dart:ui[/platform_dispatcher.dart:331:7]())
#100    _dispatchPointerDataPacket (dart:ui[/hooks.dart:94:31]())
(elided 5 frames from class _AssertionError and dart:async)
════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by widgets library ═══════════════════════════════════
Duplicate GlobalKey detected in widget tree.
### ══════════════════════════════════════════════════════════════════════════════`

**Comment by harsh-joflee** [comment]
```
════════ Exception caught by widgets library ═══════════════════════════════════
The following assertion was thrown building ValueListenableBuilder<PainterControllerValue>(state: _ValueListenableBuilderState<PainterControllerValue>#f31a1):
'package:flutter[/src/widgets/framework.dart]()': Failed assertion: line 1964 pos 12: '_elements.contains(element)': is not true.
package:flutter/…/widgets/framework.dart:1964
2

Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  [https://github.com/flutter/flutter/issues/new?template=2_bug.md]()
```

**Comment by mdddj** [comment]
same error

**Comment by hyunuck** [comment]
An error occurred when I tried to move back after upgrade Flutter from Flutter 3.32.5 to 3.32.7.


```======== Exception caught by widgets library =======================================================
The following assertion was thrown building KeyedSubtree-[GlobalKey#678de]:
'package:flutter/src/widgets/framework.dart': Failed assertion: line 2114 pos 12: '_elements.contains(element)': is not true.


Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=02_bug.yml

The relevant error-causing widget was: 
  Scaffold-[GlobalKey#6f29e] Scaffold:file:///Users/hyunuck/Workspace/daygritapp/lib/router.dart:234:20
When the exception was thrown, this was the stack: 
#2      _InactiveElements.remove (package:flutter/src/widgets/framework.dart:2114:12)
#3      Element._retakeInactiveElement (package:flutter/src/widgets/framework.dart:4471:30)
...     Normal element mounting (25 frames)
#28     Element.inflateWidget (package:flutter/src/widgets/framework.dart:4539:16)
#29     MultiChildRenderObjectElement.inflateWidget (package:flutter/src/widgets/framework.dart:7159:36)
#30     MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:7175:32)
...     Normal element mounting (105 frames)
#135    Element.inflateWidget (package:flutter/src/widgets/framework.dart:4539:16)
#136    Element.updateChild (package:flutter/src/widgets/framework.dart:3998:20)
#137    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:7015:14)
#138    Element.updateChild (package:flutter/src/widgets/framework.dart:3982:15)
#139    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5738:16)
#140    Element.rebuild (package:flutter/src/widgets/framework.dart:5427:7)
#141    StatelessElement.update (package:flutter/src/widgets/framework.dart:5787:5)
#142    Element.updateChild (package:flutter/src/widgets/framework.dart:3982:15)
#143    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:7015:14)
#144    Element.updateChild (package:flutter/src/widgets/framework.dart:3982:15)
#145    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5738:16)
#146    Element.rebuild (package:flutter/src/widgets/framework.dart:5427:7)
#147    StatelessElement.update (package:flutter/src/widgets/framework.dart:5787:5)
#148    Element.updateChild (package:flutter/src/widgets/framework.dart:3982:15)
#149    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:7015:14)
#150    Element.updateChild (package:flutter/src/widgets/framework.dart:3982:15)
#151    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:7015:14)
#152    Element.updateChild (package:flutter/src/widgets/framework.dart:3982:15)
#153    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5738:16)
#154    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5874:11)
#155    Element.rebuild (package:flutter/src/widgets/framework.dart:5427:7)
#156    StatefulElement.update (package:flutter/src/widgets/framework.dart:5899:5)
#157    Element.updateChild (package:flutter/src/widgets/framework.dart:3982:15)
#158    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:7015:14)
#159    Element.updateChild (package:flutter/src/widgets/framework.dart:3982:15)
#160    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5738:16)
#161    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5874:11)
#162    Element.rebuild (package:flutter/src/widgets/framework.dart:5427:7)
#163    StatefulElement.update (package:flutter/src/widgets/framework.dart:5899:5)
#164    Element.updateChild (package:flutter/src/widgets/framework.dart:3982:15)
#165    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:7015:14)
#166    Element.updateChild (package:flutter/src/widgets/framework.dart:3982:15)
#167    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5738:16)
#168    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5874:11)
#169    Element.rebuild (package:flutter/src/widgets/framework.dart:5427:7)
#170    StatefulElement.update (package:flutter/src/widgets/framework.dart:5899:5)
#171    Element.updateChild (package:flutter/src/widgets/framework.dart:3982:15)
#172    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5738:16)
#173    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5874:11)
#174    Element.rebuild (package:flutter/src/widgets/framework.dart:5427:7)
#175    StatefulElement.update (package:flutter/src/widgets/framework.dart:5899:5)
#176    Element.updateChild (package:flutter/src/widgets/framework.dart:3982:15)
#177    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:7015:14)
#178    Element.updateChild (package:flutter/src/widgets/framework.dart:3982:15)
#179    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5738:16)
#180    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5874:11)
#181    Element.rebuild (package:flutter/src/widgets/framework.dart:5427:7)
#182    StatefulElement.update (package:flutter/src/widgets/framework.dart:5899:5)
#183    Element.updateChild (package:flutter/src/widgets/framework.dart:3982:15)
#184    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:7015:14)
#185    Element.updateChild (package:flutter/src/widgets/framework.dart:3982:15)
#186    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5738:16)
#187    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5874:11)
#188    Element.rebuild (package:flutter/src/widgets/framework.dart:5427:7)
#189    StatefulElement.update (package:flutter/src/widgets/framework.dart:5899:5)
#190    Element.updateChild (package:flutter/src/widgets/framework.dart:3982:15)
#191    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5738:16)
#192    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5874:11)
#193    Element.rebuild (package:flutter/src/widgets/framework.dart:5427:7)
#194    StatefulElement.update (package:flutter/src/widgets/framework.dart:5899:5)
#195    Element.updateChild (package:flutter/src/widgets/framework.dart:3982:15)
#196    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5738:16)
#197    Element.rebuild (package:flutter/src/widgets/framework.dart:5427:7)
#198    StatelessElement.update (package:flutter/src/widgets/framework.dart:5787:5)
#199    Element.updateChild (package:flutter/src/widgets/framework.dart:3982:15)
#200    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5738:16)
#201    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5874:11)
#202    Element.rebuild (package:flutter/src/widgets/framework.dart:5427:7)
#203    StatefulElement.update (package:flutter/src/widgets/framework.dart:5899:5)
#204    Element.updateChild (package:flutter/src/widgets/framework.dart:3982:15)
#205    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5738:16)
#206    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5874:11)
#207    Element.rebuild (package:flutter/src/widgets/framework.dart:5427:7)
#208    StatefulElement.update (package:flutter/src/widgets/framework.dart:5899:5)
#209    Element.updateChild (package:flutter/src/widgets/framework.dart:3982:15)
#210    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:7015:14)
#211    Element.updateChild (package:flutter/src/widgets/framework.dart:3982:15)
#212    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5738:16)
#213    Element.rebuild (package:flutter/src/widgets/framework.dart:5427:7)
#214    ProxyElement.update (package:flutter/src/widgets/framework.dart:6041:5)
#215    _InheritedNotifierElement.update (package:flutter/src/widgets/inherited_notifier.dart:108:11)
#216    Element.updateChild (package:flutter/src/widgets/framework.dart:3982:15)
#217    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:7015:14)
#218    Element.updateChild (package:flutter/src/widgets/framework.dart:3982:15)
#219    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5738:16)
#220    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5874:11)
#221    Element.rebuild (package:flutter/src/widgets/framework.dart:5427:7)
#222    StatefulElement.update (package:flutter/src/widgets/framework.dart:5899:5)
#223    Element.updateChild (package:flutter/src/widgets/framework.dart:3982:15)
#224    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5738:16)
#225    Element.rebuild (package:flutter/src/widgets/framework.dart:5427:7)
#226    ProxyElement.update (package:flutter/src/widgets/framework.dart:6041:5)
#227    Element.updateChild (package:flutter/src/widgets/framework.dart:3982:15)
#228    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5738:16)
#229    Element.rebuild (package:flutter/src/widgets/framework.dart:5427:7)
#230    ProxyElement.update (package:flutter/src/widgets/framework.dart:6041:5)
#231    Element.updateChild (package:flutter/src/widgets/framework.dart:3982:15)
#232    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5738:16)
#233    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5874:11)
#234    Element.rebuild (package:flutter/src/widgets/framework.dart:5427:7)
#235    StatefulElement.update (package:flutter/src/widgets/framework.dart:5899:5)
#236    Element.updateChild (package:flutter/src/widgets/framework.dart:3982:15)
#237    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5738:16)
#238    Element.rebuild (package:flutter/src/widgets/framework.dart:5427:7)
#239    StatelessElement.update (package:flutter/src/widgets/framework.dart:5787:5)
#240    Element.updateChild (package:flutter/src/widgets/framework.dart:3982:15)
#241    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5738:16)
#242    Element.rebuild (package:flutter/src/widgets/framework.dart:5427:7)
#243    StatelessElement.update (package:flutter/src/widgets/framework.dart:5787:5)
#244    Element.updateChild (package:flutter/src/widgets/framework.dart:3982:15)
#245    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:7015:14)
#246    Element.updateChild (package:flutter/src/widgets/framework.dart:3982:15)
#247    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5738:16)
#248    Element.rebuild (package:flutter/src/widgets/framework.dart:5427:7)
#249    ProxyElement.update (package:flutter/src/widgets/framework.dart:6041:5)
#250    Element.updateChild (package:flutter/src/widgets/framework.dart:3982:15)
#251    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5738:16)
#252    Element.rebuild (package:flutter/src/widgets/framework.dart:5427:7)
#253    ProxyElement.update (package:flutter/src/widgets/framework.dart:6041:5)
#254    Element.updateChild (package:flutter/src/widgets/framework.dart:3982:15)
#255    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5738:16)
#256    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5874:11)
#257    Element.rebuild (package:flutter/src/widgets/framework.dart:5427:7)
#258    StatefulElement.update (package:flutter/src/widgets/framework.dart:5899:5)
#259    Element.updateChild (package:flutter/src/widgets/framework.dart:3982:15)
#260    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5738:16)
#261    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5874:11)
#262    Element.rebuild (package:flutter/src/widgets/framework.dart:5427:7)
#263    StatefulElement.update (package:flutter/src/widgets/framework.dart:5899:5)
#264    Element.updateChild (package:flutter/src/widgets/framework.dart:3982:15)
#265    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5738:16)
#266    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5874:11)
#267    Element.rebuild (package:flutter/src/widgets/framework.dart:5427:7)
#268    BuildScope._tryRebuild (package:flutter/src/widgets/framework.dart:2694:15)
#269    BuildScope._flushDirtyElements (package:flutter/src/widgets/framework.dart:2752:11)
#270    BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:3056:18)
#271    WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:1240:21)
#272    RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:495:5)
#273    SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1438:15)
#274    SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1351:9)
#275    SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:1204:5)
#276    _invoke (dart:ui/hooks.dart:331:13)
#277    PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:444:5)
#278    _drawFrame (dart:ui/hooks.dart:303:31)
(elided 2 frames from class _AssertionError)
====================================================================================================
```
