### ISSUE TITLE
***ERR*** The Flutter SDK is not available.

### ISSUE THREAD

**Issue by imabhishekkumar** [flutter/flutter#40320]
When I try running webdev serve, I'm getting the following error, the project used to work fine a few days ago.

```
webdev serve
Unhandled exception:
ProcessException: ***OUT***

***ERR***
The Flutter SDK is not available.

***
  Command: E:\Program Files(x32)\Dart\dart-sdk\bin\pub.bat deps
#0      _runPubDeps (package:webdev/src/pubspec.dart:70:5)     
<asynchronous suspension>
#1      PubspecLock.read (package:webdev/src/pubspec.dart:84:11)      
<asynchronous suspension>
#2      readPubspecLock (package:webdev/src/command/shared.dart:63:39)
<asynchronous suspension>
#3      ServeCommand.run (package:webdev/src/command/serve_command.dart:117:29)
<asynchronous suspension>
#4      CommandRunner.runCommand (package:args/command_runner.dart:197:27)
<asynchronous suspension>
#5      _CommandRunner.runCommand (package:webdev/src/webdev_command_runner.dart:38:24)
<asynchronous suspension>
#6      CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:112:25)
#7      new Future.sync (dart:async/future.dart:224:31)
#8      CommandRunner.run (package:args/command_runner.dart:112:14)
#9      run (package:webdev/src/webdev_command_runner.dart:19:56)
#10     main (file:///C:/Users/abhis/AppData/Roaming/Pub/Cache/hosted/pub.dartlang.org/webdev-2.5.1/bin/webdev.dart:17:22)
<asynchronous suspension>
#11     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:299:32)
#12     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:12)
Unhandled exception:
ProcessException: ***OUT***

***ERR***
The Flutter SDK is not available.

***
  Command: E:\Program Files(x32)\Dart\dart-sdk\bin\pub.bat deps
#0      _runPubDeps (package:webdev/src/pubspec.dart:70:5)
<asynchronous suspension>
#1      PubspecLock.read (package:webdev/src/pubspec.dart:84:11)
<asynchronous suspension>
#2      readPubspecLock (package:webdev/src/command/shared.dart:63:39)
<asynchronous suspension>
#3      ServeCommand.run (package:webdev/src/command/serve_command.dart:117:29)
<asynchronous suspension>
#4      CommandRunner.runCommand (package:args/command_runner.dart:197:27)
<asynchronous suspension>
#5      _CommandRunner.runCommand (package:webdev/src/webdev_command_runner.dart:38:24)
<asynchronous suspension>
#6      CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:112:25)
#7      new Future.sync (dart:async/future.dart:224:31)
#8      CommandRunner.run (package:args/command_runner.dart:112:14)
#9      run (package:webdev/src/webdev_command_runner.dart:19:56)
#10     main (file:///C:/Users/abhis/AppData/Roaming/Pub/Cache/hosted/pub.dartlang.org/webdev-2.5.1/bin/webdev.dart:17:22)
<asynchronous suspension>
#11     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:299:32)
#12     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:12)
```
Here is my `flutter doctor` log: 
```
E:\portfolio_using_flutter>flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel master, v1.10.2-pre.54, on Microsoft Windows [Version 10.0.18362.295], locale en-IN)

[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[√] Android Studio (version 3.5)
[!] IntelliJ IDEA Ultimate Edition (version 2018.3)
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
[√] VS Code, 64-bit edition (version 1.38.1)
[!] Connected device
    ! No devices available

! Doctor found issues in 2 categories.
```

**Comment by jonahwilliams** [comment]
You can't use webdev serve on a Flutter or Flutter for Web application

**Comment by aishwaryagongalla** [comment]
> You can't use webdev serve on a Flutter or Flutter for Web application

Hey, when I use Flutter Build web command the output which I got is a code before 3days. And I don't see any latest updates on my web project build. if I run it in local Its Perfect. Can you please help with this.

**Comment by itsencrypted** [comment]
I'm having the same exact error. I'm unable to run webdev serve
_runPubDeps (package:webdev/src/pubspec.dart:70:5)
#1      PubspecLock.read (package:webdev/src/pubspec.dart:84:11)
#2      readPubspecLock (package:webdev/src/command/shared.dart:63:39)
#3      ServeCommand.run (package:webdev/src/command/serve_command.dart:90:29)
#4      CommandRunner.runCommand (package:args/command_runner.dart:197:27)
#5      _CommandRunner.runCommand (package:webdev/src/webdev_command_runner.dart:38:24)
#6      CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:112:25)
#7      new Future.sync (dart:async/future.dart:224:31)
#8      CommandRunner.run (package:args/command_runner.dart:112:14)
#9      run (package:webdev/src/webdev_command_runner.dart:19:56)
#10     main (file:///Users/juliana/.pub-cache/hosted/pub.dartlang.org/webdev-2.5.4/bin/webdev.dart:17:22)
#11     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:305:32)
#12     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:174:12)
