### ISSUE TITLE
Atom "break on exception" doesn't show exception

### ISSUE THREAD

**Issue by jimbeveridge** [flutter/flutter#4037]
### Summary

Observed behavior:
When the debugger breaks due to an error, I see the message `exception: [_TypeError objects/2]`.

Expected behavior:
I see the actual message from the exception that was thrown:
```
type 'MappedListIterable' is not a subtype of type 'List<Widget>' of 'children' where
  MappedListIterable is from dart:_internal
  List is from dart:core
  Widget is from package:flutter/src/widgets/framework.dart
```

This appears to be related to https://github.com/flutter/flutter/issues/2357, so perhaps the solution needs some tweaking?

### Details

When the code in my current project runs and crashes, I get these messages:
```
Installing app.apk to Nexus 9...
Running lib/main.dart on Nexus 9...
Observatory listening on http://127.0.0.1:16200
Diagnostic server listening on http://127.0.0.1:44822
Showing Nexus 9 logs:
--------- beginning of main
I/flutter : Diagnostic server listening on http://127.0.0.1:60450
exception: [_TypeError objects/2]
```

In particular, note that the entire error message is simply `[_TypeError objects/2]`. This is very terse!

If I click Go again, then I see this error from Flutter. This contains the complete exception message, which allows me to determine the actual problem.
```
--------- beginning of system
I/flutter : ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
I/flutter : The following assertion was thrown building TeamsApp:
I/flutter : type 'MappedListIterable' is not a subtype of type 'List<Widget>' of 'children' where
I/flutter :   MappedListIterable is from dart:_internal
I/flutter :   List is from dart:core
I/flutter :   Widget is from package:flutter/src/widgets/framework.dart
I/flutter : Either the assertion indicates an error in the framework itself, or we should provide substantially
I/flutter : more information in this error message to help you determine and fix the underlying cause.
I/flutter : In either case, please report this assertion by filing a bug on GitHub:
I/flutter :   https://github.com/flutter/flutter/issues/new
I/flutter : When the exception was thrown, this was the stack:
I/flutter : #0      TabBarView.TabBarView (package:flutter/src/material/tabs.dart:960)
I/flutter : #1      TeamsAppState.build (/media/jimbe/mojossd/sysui/src/teams/lib/teams_app.dart:252)
I/flutter : #2      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:1530)
I/flutter : #3      BuildableElement.rebuild (package:flutter/src/widgets/framework.dart:1446)
I/flutter : #4      ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:1516)
I/flutter : #5      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:1633)
I/flutter : #6      ComponentElement.mount (package:flutter/src/widgets/framework.dart:1511)
I/flutter : #7      Element.inflateWidget (package:flutter/src/widgets/framework.dart:1098)
I/flutter : #8      Element.updateChild (package:flutter/src/widgets/framework.dart:979)
I/flutter : #9      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:1542)
I/flutter : #10     BuildableElement.rebuild (package:flutter/src/widgets/framework.dart:1446)
[snip]
```
### flutter doctor
```
[✓] Flutter (on Linux, channel master)
    • Flutter at /media/jimbe/mojossd/sysui/src/third_party/flutter
    • Framework revision 06043b0585 (23 hours ago), engine revision a1f4a12baa

[✓] Android toolchain - develop for Android devices (Android SDK 23.0.2)
    • Android SDK at /usr/local/google/home/jimbe/Android/Sdk
    • Platform android-23, build-tools 23.0.2
    • OpenJDK Runtime Environment (build 1.8.0-google-v7-121669373-121622544)

[✓] Atom - a lightweight development environment for Flutter
    • Atom installed; Flutter plugin version 0.2.2
```

**Comment by sethladd** [comment]
Thanks for the report!
