### ISSUE TITLE
Flutter tabs demo crashes

### ISSUE THREAD

**Issue by jimbeveridge** [flutter/flutter#4046]
## Steps to Reproduce

Run flutter_gallery under Atom
Tap Components
Tap Tabs
Tap the TWO tab
*Crash*

Message in the Atom log window says `exception: [_TypeError objects/3]`.

If I click the Continue arrow on the right in Atom (not the one at the top of the screen), then I get the detailed log messages below.

## Flutter Doctor

```
[✓] Flutter (on Linux, channel master)
    • Flutter at /media/jimbe/mojossd/sysui/src/third_party/flutter
    • Framework revision 06043b0585 (24 hours ago), engine revision a1f4a12baa

[✓] Android toolchain - develop for Android devices (Android SDK 23.0.2)
    • Android SDK at /usr/local/google/home/jimbe/Android/Sdk
    • Platform android-23, build-tools 23.0.2
    • OpenJDK Runtime Environment (build 1.8.0-google-v7-121669373-121622544)

[✓] Atom - a lightweight development environment for Flutter
    • Atom installed; Flutter plugin version 0.2.2
```

## Logs and Crash Reports

```
E/flutter : [ERROR:dart_error.cc(17)] Unhandled exception:
E/flutter : type '_ScrollableViewportState' is not a subtype of type 'ScrollableState<Scrollable>' of 'function result' where
E/flutter :   _ScrollableViewportState is from package:flutter/src/widgets/scrollable.dart
E/flutter :   ScrollableViewport is from package:flutter/src/widgets/scrollable.dart
E/flutter :   ScrollableState is from package:flutter/src/widgets/scrollable.dart
E/flutter :   Scrollable is from package:flutter/src/widgets/scrollable.dart
E/flutter : 
E/flutter : #0      GlobalKey.currentState (package:flutter/src/widgets/framework.dart:167)
E/flutter : #1      TabsDemoState.build.<anonymous closure>.<anonymous closure> (/media/jimbe/mojossd/flutter/examples/flutter_gallery/lib/demo/tabs_demo.dart:46)
E/flutter : #2      State.setState (package:flutter/src/widgets/framework.dart:419)
E/flutter : #3      TabsDemoState.build.<anonymous closure> (/media/jimbe/mojossd/flutter/examples/flutter_gallery/lib/demo/tabs_demo.dart:44)
E/flutter : #4      TabBarSelectionState.value=.<anonymous closure> (package:flutter/src/material/tabs.dart:599)
E/flutter : #5      _RootZone.runUnary (dart:async/zone.dart:1204)
E/flutter : #6      _FutureListener.handleValue (dart:async/future_impl.dart:131)
E/flutter : #7      _Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:628)
E/flutter : #8      _Future._propagateToListeners (dart:async/future_impl.dart:658)
E/flutter : #9      _Future._completeWithValue (dart:async/future_impl.dart:468)
E/flutter : #10     _Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:519)
E/flutter : #11     _microtaskLoop (dart:async/schedule_microtask.dart:41)
E/flutter : #12     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50)
--------- beginning of system
```

> For more information about diagnosing and reporting Flutter bugs, please see [https://flutter.io/bug-reports/](https://flutter.io/bug-reports/).

**Comment by Hixie** [comment]
cc'ing @HansMuller for initial routing
