### ISSUE TITLE
/storage/emulated/0/ not accessible using Flutter

### ISSUE THREAD

**Issue by creativecreatorormaybenot** [flutter/flutter#40498]
There has been discussions about this all over the place, however, this still needs a definitive issue (and fix).

---

When trying to write files, create directories, etc. on Android using Flutter, the following error is thrown:

```
OS Error: Permission denied, errno = 13
```

The only operations that work are [`exists` operations](https://api.flutter.dev/flutter/dart-io/FileSystemEntity/existsSync.html) after specifying the `WRITE_EXTERNAL_STORAGE` permission and granting it.

**Comment by creativecreatorormaybenot** [comment]
@BondarenkoStas How is this a good question for StackOverflow? Maybe it would be if I was wrong, but according to my research this is a bug in Flutter.

**Comment by BondarenkoStas** [comment]
@creativecreatorormaybenot Can you please provide  a small self-contained app that demonstrates the problem. You can include small examples [inline if they're enclosed by backticks](https://help.github.com/en/articles/creating-and-highlighting-code-blocks), or just provide a public link to a github "gist" - https://gist.github.com/.
Also can you paste you ```flutter doctor -v``` output?

**Comment by creativecreatorormaybenot** [comment]
@BondarenkoStas 

Prerequisites: `WRITE_EXTERNAL_STORAGE` permission in the Android Manifest and allowed permission either in the app's settings or via in-app prompt.

```dart
File('/storage/emulator/0/test.txt').writeAsString('test'); // Will produce the error.

final directory = Directory('/storage/emulated/0/directory');
if (!directory.existsSync()) // This will not fail.
  directory.create(); // This will produce the error again.
```

**Comment by PerLycke** [comment]
@creativecreatorormaybenot You fixed this somehow?

**Comment by creativecreatorormaybenot** [comment]
I appreciate if anyone that makes progress on this could update everyone here and would do so myself.

**Comment by elmissouri16** [comment]
same issue  for me too if any one found solution or workaround will be great thank you

**Comment by jinfagang** [comment]
Same issue here, seems even call create() will not actual create such as directory.

**Comment by VladyslavBondarenko** [comment]
Related to https://github.com/flutter/flutter/issues/16347

**Comment by TahaTesser** [comment]
Hi @creativecreatorormaybenot 
I can still reproduce the issue

<details> 
<summary>code sample</summary> 

```dart
import 'dart:io';

import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Material App',
      theme: ThemeData.dark(),
      home: Home(),
    );
  }
}

class Home extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('Material App Bar'),
      ),
      body: Center(
        child: Container(
          child: Text('Hello World'),
        ),
      ),
      floatingActionButton: FloatingActionButton(
        child: Icon(Icons.add),
        onPressed: () {
          final directory = Directory('/storage/emulated/0/directory');
          if (!directory.existsSync()) // This will not fail.
            directory.create();
        },
      ),
    );
  }
}

``` 

</details>


<details> 
<summary>logs</summary> 

```bash
E/flutter (27227): [ERROR:flutter/lib/ui/ui_dart_state.cc(177)] Unhandled Exception: FileSystemException: Creation failed, path = '/storage/emulated/0/directory' (OS Error: Operation not permitted, errno = 1)
[38;5;244mE/flutter (27227): #0      _Directory.create.<anonymous closure> (dart:io/directory_impl.dart:117:11)[39;49m
[38;5;244mE/flutter (27227): #1      _rootRunUnary (dart:async/zone.dart:1194:47)[39;49m
[38;5;244mE/flutter (27227): #2      _CustomZone.runUnary (dart:async/zone.dart:1097:19)[39;49m
[38;5;244mE/flutter (27227): #3      _FutureListener.handleValue (dart:async/future_impl.dart:150:18)[39;49m
[38;5;244mE/flutter (27227): #4      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:703:45)[39;49m
[38;5;244mE/flutter (27227): #5      Future._propagateToListeners (dart:async/future_impl.dart:732:32)[39;49m
[38;5;244mE/flutter (27227): #6      Future._completeWithValue (dart:async/future_impl.dart:536:5)[39;49m
[38;5;244mE/flutter (27227): #7      Future._asyncCompleteWithValue.<anonymous closure> (dart:async/future_impl.dart:574:7)[39;49m
[38;5;244mE/flutter (27227): #8      _rootRun (dart:async/zone.dart:1186:13)[39;49m
[38;5;244mE/flutter (27227): #9      _CustomZone.run (dart:async/zone.dart:1090:19)[39;49m
[38;5;244mE/flutter (27227): #10     _CustomZone.runGuarded (dart:async/zone.dart:994:7)[39;49m
[38;5;244mE/flutter (27227): #11     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1034:23)[39;49m
[38;5;244mE/flutter (27227): #12     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)[39;49m
[38;5;244mE/flutter (27227): #13     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)[39;49m
E/flutter (27227):
D/ViewRootImpl[MainActivity](27227): windowFocusChanged hasFocus=false inTouchMode=true

```

</details>


<details> 
<summary>flutter doctor -v</summary> 

```bash
[✓] Flutter (Channel master, 1.25.0-5.0.pre.45, on macOS 11.0.1 20B29 darwin-x64, locale en-GB)
    • Flutter version 1.25.0-5.0.pre.45 at /Users/tahatesser/Code/flutter_master
    • Framework revision 81e1f7d1ed (11 hours ago), 2020-12-02 17:19:57 -0800
    • Engine revision 20caf54969
    • Dart version 2.12.0 (build 2.12.0-76.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/tahatesser/Code/sdk
    • Platform android-30, build-tools 30.0.2
    • ANDROID_HOME = /Users/tahatesser/Code/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.2)
    • Xcode at /Volumes/Extreme/Xcode.app/Contents/Developer
    • Xcode 12.2, Build version 12B45b
    • CocoaPods version 1.10.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.51.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.16.0

[✓] Connected device (5 available)
    • IN2011 (mobile)      • c9d8ee0c                  • android-arm64  • Android 11 (API 30)
    • Taha’s iPad (mobile) • 00008020-000255113EE8402E • ios            • iOS 14.2
    • macOS (desktop)      • macos                     • darwin-x64     • macOS 11.0.1 20B29 darwin-x64
    • Web Server (web)     • web-server                • web-javascript • Flutter Tools
    • Chrome (web)         • chrome                    • web-javascript • Google Chrome 87.0.4280.88

• No issues found!
```

</details>

**Comment by RomanTuras** [comment]
Hi, everyone!
I also got OS Error: `Permission denied, errno = 13` when try to access to file (read/write/create) from `/storage/emulated/0/`

In my case, **I was add one more permission in Manifest:** `ACCESS_MEDIA_LOCATION` and solved this issue.

So, Manifest are now contains three permissions: `READ_EXTERNAL_STORAGE`, `WRITE_EXTERNAL_STORAGE` and `ACCESS_MEDIA_LOCATION`.

Important, I also used Runtime Permission (from [permission_handler](https://pub.dev/packages/permission_handler) library) in my app.

Have a nice day!

**Comment by darshansharma** [comment]
> Hi, everyone!
> I also got OS Error: `Permission denied, errno = 13` when try to access to file (read/write/create) from `/storage/emulated/0/`
> 
> In my case, **I was add one more permission in Manifest:** `ACCESS_MEDIA_LOCATION` and solved this issue.
> 
> So, Manifest are now contains three permissions: `READ_EXTERNAL_STORAGE`, `WRITE_EXTERNAL_STORAGE` and `ACCESS_MEDIA_LOCATION`.
> 
> Important, I also used Runtime Permission (from [permission_handler](https://pub.dev/packages/permission_handler) library) in my app.
> 
> Have a nice day!

I am still getting this error when trying to create myDir
`E/flutter (18294): [ERROR:flutter/lib/ui/ui_dart_state.cc(186)] Unhandled Exception: FileSystemException: Creation failed, path = '/storage/emulated/0/mydir' (OS Error: Operation not permitted, errno = 1)`

**Comment by princesanjivy** [comment]
> > Hi, everyone!
> > I also got OS Error: `Permission denied, errno = 13` when try to access to file (read/write/create) from `/storage/emulated/0/`
> > In my case, **I was add one more permission in Manifest:** `ACCESS_MEDIA_LOCATION` and solved this issue.
> > So, Manifest are now contains three permissions: `READ_EXTERNAL_STORAGE`, `WRITE_EXTERNAL_STORAGE` and `ACCESS_MEDIA_LOCATION`.
> > Important, I also used Runtime Permission (from [permission_handler](https://pub.dev/packages/permission_handler) library) in my app.
> > Have a nice day!
> 
> I am still getting this error when trying to create myDir
> `E/flutter (18294): [ERROR:flutter/lib/ui/ui_dart_state.cc(186)] Unhandled Exception: FileSystemException: Creation failed, path = '/storage/emulated/0/mydir' (OS Error: Operation not permitted, errno = 1)`

Basically you dont have access to shared storage for that you have to use the Storage Access Framework API (SAF) and from Android 10+ Scoped Storage other apps cannot access unless user gives permission, also the `requestLegacyExternalStorage`, `WRITE_EXTERNAL_STORAGE` wont work in Android 11. Currenlty there is no package available to do this you've to implement this using the MethodChannel.

**Comment by darshansharma** [comment]
> > > Hi, everyone!
> > > I also got OS Error: `Permission denied, errno = 13` when try to access to file (read/write/create) from `/storage/emulated/0/`
> > > In my case, **I was add one more permission in Manifest:** `ACCESS_MEDIA_LOCATION` and solved this issue.
> > > So, Manifest are now contains three permissions: `READ_EXTERNAL_STORAGE`, `WRITE_EXTERNAL_STORAGE` and `ACCESS_MEDIA_LOCATION`.
> > > Important, I also used Runtime Permission (from [permission_handler](https://pub.dev/packages/permission_handler) library) in my app.
> > > Have a nice day!
> > 
> > 
> > I am still getting this error when trying to create myDir
> > `E/flutter (18294): [ERROR:flutter/lib/ui/ui_dart_state.cc(186)] Unhandled Exception: FileSystemException: Creation failed, path = '/storage/emulated/0/mydir' (OS Error: Operation not permitted, errno = 1)`
> 
> Basically you dont have access to shared storage for that you have to use the Storage Access Framework API (SAF) and from Android 10+ Scoped Storage other apps cannot access unless user gives permission, also the `requestLegacyExternalStorage`, `WRITE_EXTERNAL_STORAGE` wont work in Android 11. Currenlty there is no package available to do this you've to implement this using the MethodChannel.
> 
> And also this isn't an issue with the Flutter.

Then whose issue is this? And please tell more about methodchannel

**Comment by princesanjivy** [comment]
For example, you can achieve creation of file in Android 10+ by invoking the native code part using methodchannel in dart

<details><summary>MainActivity.java</summary>

```
@Override
    public void configureFlutterEngine(@NonNull FlutterEngine flutterEngine) {
        super.configureFlutterEngine(flutterEngine);

        new MethodChannel(flutterEngine.getDartExecutor().getBinaryMessenger(), CHANNEL).setMethodCallHandler(
                (call, result) -> {
                    myResult = result;
                    
                    if (call.method.equals("excel")) {
                        createFile(call.argument("bytes"), call.argument("name"));
                    } else {
                        result.notImplemented();
                    }
                }
        );
    }

    private void createFile(byte[] bytes, String name) {
        this.bytes = bytes;
        Intent intent = new Intent(Intent.ACTION_CREATE_DOCUMENT);

        intent.addCategory(Intent.CATEGORY_OPENABLE);
        intent.setType("application/vnd.openxmlformats-officedocument.spreadsheetml.sheet");
        intent.putExtra(Intent.EXTRA_TITLE, name+".xlsx");
        startActivityForResult(intent, CREATE_FILE_REQUEST_CODE);
    }

    private void writeFile(Uri uri) {

        try {
            ParcelFileDescriptor parcelFileDescriptor = this.getContentResolver().openFileDescriptor(uri, "w");

            FileOutputStream fileOutputStream = new FileOutputStream(parcelFileDescriptor.getFileDescriptor());
            fileOutputStream.write(this.bytes);

            fileOutputStream.close();
            parcelFileDescriptor.close();

            myResult.success("File saved!");
        } catch (IOException e) {
            e.printStackTrace();
        }

    }

    @Override
    protected void onActivityResult(int requestCode, int resultCode, Intent data) {
        super.onActivityResult(requestCode, resultCode, data);

        if (requestCode == CREATE_FILE_REQUEST_CODE && resultCode == Activity.RESULT_OK) {
            if (data != null) {
                writeFile(data.getData());
            }
        }
    }
```
</details>

Then call the particular native code by 

```
static const platform = const MethodChannel(CHANNEL);
await platform.invokeMethod('excel');
```

For more references 
[MethodChannel](https://flutter.dev/docs/development/platform-integration/platform-channels?tab=android-channel-java-tab)
[Scoped Storage](https://medium.com/microsoft-mobile-engineering/scoped-storage-in-android-10-android-11-28d58d989f3c)

**Comment by maplerder** [comment]
I found resolution in here https://stackoverflow.com/questions/69592763/cant-write-to-file-in-flutter

**Comment by darshankawar** [comment]
@creativecreatorormaybenot 
Coming back to this issue, can you take a look at above comments / solutions and see if they help to decide on status of this issue ?
Specially https://github.com/flutter/flutter/issues/40498#issuecomment-774138514, https://github.com/flutter/flutter/issues/40498#issuecomment-826331592 and https://github.com/flutter/flutter/issues/40498#issuecomment-1172115827

**Comment by creativecreatorormaybenot** [comment]
I think what is linked in https://github.com/flutter/flutter/issues/40498#issuecomment-1172115827 may be the solution to the problem. However, I do not have the capacity / code to test it right now. If someone else can confirm that `android.permission.MANAGE_EXTERNAL_STORAGE ` fixes the issue, we could close this.

It would help if it was documented somewhere in Flutter. However, this is specific to Android development, so it might not be necessary.

**Comment by TheVineet** [comment]
I am facing the same issue. None of the above solution works. There aint any reliable working solution in stackoverflow as well

**Comment by darshankawar** [comment]
Revisting this issue and verified using latest stable and master versions, I was able to replicate the reported error still:

<details>
<summary> console error log  </summary>

```

E/flutter (19457): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: PathAccessException: Creation failed, path = '/storage/emulated/0/directory' (OS Error: Permission denied, errno = 13)
E/flutter (19457): #0      _checkForErrorResponse (dart:io/common.dart:55:9)
E/flutter (19457): #1      _Directory.create.<anonymous closure> (dart:io/directory_impl.dart:109:9)
E/flutter (19457): #2      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:838:45)
E/flutter (19457): #3      Future._propagateToListeners (dart:async/future_impl.dart:867:13)
E/flutter (19457): #4      Future._completeWithValue (dart:async/future_impl.dart:643:5)
E/flutter (19457): #5      Future._asyncCompleteWithValue.<anonymous closure> (dart:async/future_impl.dart:713:7)
E/flutter (19457): #6      _microtaskLoop (dart:async/schedule_microtask.dart:40:21)
E/flutter (19457): #7      _startMicrotaskLoop (dart:async/schedule_microtask.dart:49:5)
E/flutter (19457): 

```

</details>

I tried by adding below permissions in manifest but still the exception occured:
```

<uses-permission android:name="WRITE_EXTERNAL_STORAGE"/>
    <uses-permission android:name="ACCESS_MEDIA_LOCATION"/>
    <uses-permission android:name="MANAGE_EXTERNAL_STORAGE" />
```

Code sample used: https://github.com/flutter/flutter/issues/40498#issuecomment-737914181

<details>
<summary> stable, master flutter doctor -v </summary>

```
[!] Flutter (Channel stable, 3.19.6, on macOS 12.2.1 21D62 darwin-x64, locale
    en-GB)
    • Flutter version 3.19.6 on channel stable at
      /Users/dhs/documents/fluttersdk/flutter
    ! Warning: `flutter` on your path resolves to
      /Users/dhs/Documents/Fluttersdk/flutter/bin/flutter, which is not inside
      your current Flutter SDK checkout at
      /Users/dhs/documents/fluttersdk/flutter. Consider adding
      /Users/dhs/documents/fluttersdk/flutter/bin to the front of your path.
    ! Warning: `dart` on your path resolves to
      /Users/dhs/Documents/Fluttersdk/flutter/bin/dart, which is not inside your
      current Flutter SDK checkout at /Users/dhs/documents/fluttersdk/flutter.
      Consider adding /Users/dhs/documents/fluttersdk/flutter/bin to the front
      of your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 54e66469a9 (6 days ago), 2024-04-17 13:08:03 -0700
    • Engine revision c4cd48e186
    • Dart version 3.3.4
    • DevTools version 2.31.1
    • If those were intentional, you can disregard the above warnings; however
      it is recommended to use "git" directly to perform update checks and
      upgrades.

[!] Xcode - develop for iOS and macOS (Xcode 12.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    ! Flutter recommends a minimum Xcode version of 13.
      Download the latest version or update via the Mac App Store.
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] VS Code (version 1.62.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.21.0

[✓] Connected device (5 available)
    • SM G975F (mobile)       • RZ8M802WY0X • android-arm64   • Android 11 (API 30)
    • Darshan's iphone (mobile)  • 21150b119064aecc249dfcfe05e259197461ce23 •
      ios            • iOS 14.4.1 18D61
    • iPhone 12 Pro Max (mobile) • A5473606-0213-4FD8-BA16-553433949729     •
      ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-3 (simulator)
    • macOS (desktop)            • macos                                    •
      darwin-x64     • Mac OS X 10.15.4 19E2269 darwin-x64
    • Chrome (web)               • chrome                                   •
      web-javascript • Google Chrome 98.0.4758.80

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.

[!] Flutter (Channel master, 3.22.0-14.0.pre.67, on macOS 12.2.1 21D62
    darwin-x64, locale en-GB)
    • Flutter version 3.22.0-14.0.pre.67 on channel master at
      /Users/dhs/documents/fluttersdk/flutter
    ! Warning: `flutter` on your path resolves to
      /Users/dhs/Documents/Fluttersdk/flutter/bin/flutter, which is not inside
      your current Flutter SDK checkout at
      /Users/dhs/documents/fluttersdk/flutter. Consider adding
      /Users/dhs/documents/fluttersdk/flutter/bin to the front of your path.
    ! Warning: `dart` on your path resolves to
      /Users/dhs/Documents/Fluttersdk/flutter/bin/dart, which is not inside your
      current Flutter SDK checkout at /Users/dhs/documents/fluttersdk/flutter.
      Consider adding /Users/dhs/documents/fluttersdk/flutter/bin to the front
      of your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 1a905d508d (20 hours ago), 2024-04-21 06:44:23 -0400
    • Engine revision 75ca2195c9
    • Dart version 3.5.0 (build 3.5.0-83.0.dev)
    • DevTools version 2.35.0-dev.8
    • If those were intentional, you can disregard the above warnings; however
      it is recommended to use "git" directly to perform update checks and
      upgrades.

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/dhs/Library/Android/sdk
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for
      more details.

[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 13C100
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] IntelliJ IDEA Ultimate Edition (version 2021.3.2)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 65.1.4
    • Dart plugin version 213.7228

[✓] VS Code (version 1.62.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.29.0

[✓] Connected device (3 available)
    • Darshan's iphone (mobile) • 21150b119064aecc249dfcfe05e259197461ce23 • ios
      • iOS 15.3.1 19D52
    • macOS (desktop)           • macos                                    •
      darwin-x64     • macOS 12.2.1 21D62 darwin-x64
    • Chrome (web)              • chrome                                   •
      web-javascript • Google Chrome 109.0.5414.119

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.
      
[!] Xcode - develop for iOS and macOS (Xcode 12.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    ! Flutter recommends a minimum Xcode version of 13.
      Download the latest version or update via the Mac App Store.
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] VS Code (version 1.62.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.21.0

[✓] Connected device (5 available)
    • SM G975F (mobile)       • RZ8M802WY0X • android-arm64   • Android 11 (API 30)
    • Darshan's iphone (mobile)  • 21150b119064aecc249dfcfe05e259197461ce23 •
      ios            • iOS 14.4.1 18D61
    • iPhone 12 Pro Max (mobile) • A5473606-0213-4FD8-BA16-553433949729     •
      ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-3 (simulator)
    • macOS (desktop)            • macos                                    •
      darwin-x64     • Mac OS X 10.15.4 19E2269 darwin-x64
    • Chrome (web)               • chrome                                   •
      web-javascript • Google Chrome 98.0.4758.80

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.



```

</details>

**Comment by brandon-watkins-avcrm** [comment]
Any updates on this? Or workarounds people have found?
