### ISSUE TITLE
FormField validators are invoked with incorrect/old values

### ISSUE THREAD

**Issue by daniel-v** [flutter/flutter#40494]
## Steps to Reproduce

Created a test file that explains what I get and what I expect. Can be found here: https://gist.github.com/daniel-v/f1133f3e39a5714a3774760dab3841b2

**In short**

I'd expect that when I call `FormState.validate()` in response to a `TextEditingController` notification, the validators would receive the value  of the `TextEditingController`. This isn't the case, it seems that `FormState` caches a value, which seems to be updated AFTER validators would run. FormState's value is passed to the validators, therefore validators are always receive a value that's old.

**Question**

Is that expected and is this how this should work?

**Repro**

```
flutter create repro_proj
cd repro_proj
curl https://gist.githubusercontent.com/daniel-v/f1133f3e39a5714a3774760dab3841b2/raw/f41c63228c5bfaadbd56210582613706d095856c/input_validation_test.dart -o test/form_validator_test.dart
flutter test test/form_validator_test.dart
```

## Logs

```
00:02 +0: Triggers validation with right value
══╡ EXCEPTION CAUGHT BY FLUTTER TEST FRAMEWORK ╞════════════════════════════════════════════════════
The following TestFailure object was thrown running a test:
  Expected: 'a'
  Actual: ''
   Which: is different. Both strings start the same, but the actual value is missing the following
trailing characters: a
```

## Doc tells me:

```
[√] Flutter (Channel stable, v1.9.1+hotfix.2, on Microsoft Windows [Version 10.0.18362.356], locale hu-HU)
    • Flutter version 1.9.1+hotfix.2 at C:\Users\Dev\Documents\3rdParty\flutter
    • Framework revision 2d2a1ffec9 (8 days ago), 2019-09-06 18:39:49 -0700
    • Engine revision b863200c37
    • Dart version 2.5.0


[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at C:\Users\Dev\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: C:\Users\Dev\Documents\3rdParty\AndroidStudio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)
    • All Android licenses accepted.
```

**Comment by mannprerak2** [comment]
I observed that setting **auto_validate = true** in Form leads to the test being passed

**Comment by daniel-v** [comment]
@mannprerak2 thank you for taking the time checking it out!

You are right, when `autovalidate` is true, the test pass, however that is a different use case. Imagine having more than a single field where you want to trigger certain events on form value change (such as enabling/disabling a submit button) but only if the form is valid. `autovalidate` and `onChange` combo has different side effects: 

1. `onChange` on form seems to be triggered as many times as the number of fields 
2. I'd still have to invoke `FormState.validate()` as it seems to be the only mechanic I could find to check if there are validation errors. Validation also forces a rebuild. Together with no. 1 it starts to be a "meh" workaround

A "livable" workaround I found is to use `scheduleMicrotask` in the `TextEditingController`'s listener callback to wait for the value of TextFormField to be updated.

**Comment by mannprerak2** [comment]
There is something strange going here
**Depending on the expected value, the 'actual' value is changing**
If you try this
```dart
await tester.enterText(find.byType(TextFormField), 'a');
await tester.pumpAndSettle();
expect(validatorTriggered, isTrue);
expect(formState.lastEditorValueBeforeValidation, 'b'); // this line now has 'b' instead of 'a'
```
the response's actual value now becomes 'a', which we wanted it to be
```
The following TestFailure object was thrown running a test:
  Expected: 'b'
  Actual: 'a'
   Which: is different.
          Expected: b
            Actual: a
                    ^
           Differ at offset 0
```
I think this might indicate something wrong with the test framework.

**Comment by SomeDudeeee** [comment]
i'm having the same issues, i wrote a dartpad example for anyone that wants to see: https://dartpad.dev/b6409e10de32b280b8938aa75364fa7b

this is especially annoying in cases like the example because it prompts the user to enter text for the first entered letter

**Comment by TahaTesser** [comment]
<details> 
<summary>Code Sample</summary> 

``` 
import 'package:flutter/material.dart';
import 'package:flutter_test/flutter_test.dart';

main() {
  testWidgets('Triggers validation with right value', (tester) async {
    String fieldValidatorValue;
    bool validatorTriggered = false;
    final fieldValidator = (String value) {
      validatorTriggered = true;
      // cache value received for validation
      fieldValidatorValue = value;
      return null;
    };
    final tFormApp = newFormApp(fieldValidator);
    await tester.pumpWidget(tFormApp);
    await tester.pumpAndSettle();
    // we expect both fieldValidatorValue and formState.lastEditorValue to be `null`
    final formFinder = find.byType(TestForm);
    final formState = tester.state<TestFormState>(formFinder);
    expect(validatorTriggered, isFalse);
    expect(fieldValidatorValue, isNull);
    expect(fieldValidatorValue, formState.lastEditorValueBeforeValidation);

    // when listeners of the TextEditingController are called, my expectation would be
    // that [FormFieldState.value] has already been updated to the new value
    // Side effect of not updating FormFieldState.value is that validator functions always
    // receive the old cached value instead.
    await tester.enterText(find.byType(TextFormField), 'a');
    await tester.pumpAndSettle();
    expect(validatorTriggered, isTrue);
    expect(formState.lastEditorValueBeforeValidation, 'a');
    expect(fieldValidatorValue, formState.lastEditorValueBeforeValidation);
  });
}

Widget newFormApp(FormFieldValidator<String> validator) {
  final testForm = TestForm(validator: validator);
  return MaterialApp(
    home: Scaffold(
      body: testForm,
    ),
  );
}

class TestForm extends StatefulWidget {
  final FormFieldValidator<String> validator;

  const TestForm({Key key, @required this.validator}) : super(key: key);

  @override
  TestFormState createState() => TestFormState();
}

class TestFormState extends State<TestForm> {
  final _editingController = TextEditingController();
  final _formKey = GlobalKey();
  @visibleForTesting
  String lastEditorValueBeforeValidation;

  @override
  void initState() {
    super.initState();
    _editingController.addListener(inputChanged);
  }

  @override
  void dispose() {
    _editingController.dispose();
    super.dispose();
  }

  void inputChanged() {
    // cache controller text for test to compare
    lastEditorValueBeforeValidation = _editingController.text;
    // trigger validation
    (_formKey.currentState as FormState).validate();
  }

  @override
  Widget build(BuildContext context) {
    return Form(
      key: _formKey,
      child: TextFormField(
        controller: _editingController,
        validator: widget.validator,
      ),
    );
  }
}

``` 

</details> 

<details> 
<summary>logs</summary> 

``` 
tahatesser@MacBook-Pro dev_flutter % flutterd test test/widget_test.dart 
00:09 +0: Triggers validation with right value                                                                           
══╡ EXCEPTION CAUGHT BY FLUTTER TEST FRAMEWORK ╞════════════════════════════════════════════════════
The following TestFailure object was thrown running a test:
  Expected: 'a'
  Actual: ''
   Which: is different. Both strings start the same, but the actual value is missing the following
trailing characters: a

When the exception was thrown, this was the stack:
#4      main.<anonymous closure> (file:///Users/tahatesser/AndroidStudioProjects/dev_flutter/test/widget_test.dart:32:5)
<asynchronous suspension>
#5      main.<anonymous closure> (file:///Users/tahatesser/AndroidStudioProjects/dev_flutter/test/widget_test.dart)
#6      testWidgets.<anonymous closure>.<anonymous closure> (package:flutter_test/src/widget_tester.dart:144:29)
<asynchronous suspension>
#7      testWidgets.<anonymous closure>.<anonymous closure> (package:flutter_test/src/widget_tester.dart)
#8      TestWidgetsFlutterBinding._runTestBody (package:flutter_test/src/binding.dart:739:19)
<asynchronous suspension>
#11     TestWidgetsFlutterBinding._runTest (package:flutter_test/src/binding.dart:719:14)
#12     AutomatedTestWidgetsFlutterBinding.runTest.<anonymous closure> (package:flutter_test/src/binding.dart:1119:24)
#13     FakeAsync.run.<anonymous closure>.<anonymous closure> (package:fake_async/fake_async.dart:177:54)
#18     withClock (package:clock/src/default.dart:46:10)
#19     FakeAsync.run.<anonymous closure> (package:fake_async/fake_async.dart:177:22)
#24     FakeAsync.run (package:fake_async/fake_async.dart:177:7)
#25     AutomatedTestWidgetsFlutterBinding.runTest (package:flutter_test/src/binding.dart:1116:15)
#26     testWidgets.<anonymous closure> (package:flutter_test/src/widget_tester.dart:137:24)
#27     Declarer.test.<anonymous closure>.<anonymous closure> (package:test_api/src/backend/declarer.dart:171:19)
<asynchronous suspension>
#28     Declarer.test.<anonymous closure>.<anonymous closure> (package:test_api/src/backend/declarer.dart)
#33     Declarer.test.<anonymous closure> (package:test_api/src/backend/declarer.dart:169:13)
#34     Invoker.waitForOutstandingCallbacks.<anonymous closure> (package:test_api/src/backend/invoker.dart:235:15)
#39     Invoker.waitForOutstandingCallbacks (package:test_api/src/backend/invoker.dart:232:5)
#40     Invoker._onRun.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:test_api/src/backend/invoker.dart:388:17)
<asynchronous suspension>
#41     Invoker._onRun.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:test_api/src/backend/invoker.dart)
#46     Invoker._onRun.<anonymous closure>.<anonymous closure> (package:test_api/src/backend/invoker.dart:374:9)
#47     Invoker._guardIfGuarded (package:test_api/src/backend/invoker.dart:420:15)
#48     Invoker._onRun.<anonymous closure> (package:test_api/src/backend/invoker.dart:373:7)
#55     Invoker._onRun (package:test_api/src/backend/invoker.dart:372:11)
#56     LiveTestController.run (package:test_api/src/backend/live_test_controller.dart:152:11)
#57     RemoteListener._runLiveTest.<anonymous closure> (package:test_api/src/remote_listener.dart:259:16)
#62     RemoteListener._runLiveTest (package:test_api/src/remote_listener.dart:258:5)
#63     RemoteListener._serializeTest.<anonymous closure> (package:test_api/src/remote_listener.dart:211:7)
#81     _GuaranteeSink.add (package:stream_channel/src/guarantee_channel.dart:124:12)
#82     new _MultiChannel.<anonymous closure> (package:stream_channel/src/multi_channel.dart:159:31)
#116    new _WebSocketImpl._fromSocket.<anonymous closure> (dart:_http/websocket_impl.dart:1145:21)
#124    _WebSocketProtocolTransformer._messageFrameEnd (dart:_http/websocket_impl.dart:338:23)
#125    _WebSocketProtocolTransformer.add (dart:_http/websocket_impl.dart:232:46)
#135    _Socket._onData (dart:io-patch/socket_patch.dart:2020:41)
#144    new _RawSocket.<anonymous closure> (dart:io-patch/socket_patch.dart:1556:33)
#145    _NativeSocket.issueReadEvent.issue (dart:io-patch/socket_patch.dart:1052:14)
(elided 108 frames from dart:async and package:stack_trace)

This was caught by the test expectation on the following line:
  file:///Users/tahatesser/AndroidStudioProjects/dev_flutter/test/widget_test.dart line 32
The test description was:
  Triggers validation with right value
════════════════════════════════════════════════════════════════════════════════════════════════════
00:09 +0 -1: Triggers validation with right value [E]                                                                    
  Test failed. See exception logs above.
  The test description was: Triggers validation with right value
  
00:09 +0 -1: Some tests failed.                                                                                          
tahatesser@MacBook-Pro dev_flutter % 
``` 

</details> 


<details> 
<summary>flutter doctor -v</summary> 

``` 
[✓] Flutter (Channel dev, 1.20.0-2.0.pre, on Mac OS X 10.15.5 19F101, locale
    en-GB)
    • Flutter version 1.20.0-2.0.pre at /Users/tahatesser/Code/flutter_dev
    • Framework revision 15a28159bc (9 days ago), 2020-06-23 04:52:58 -0700
    • Engine revision 91a63d6a44
    • Dart version 2.9.0 (build 2.9.0-19.0.dev 7e72c9ae7e)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
    • Android SDK at /Users/tahatesser/Code/sdk
    • Platform android-30, build-tools 30.0.0
    • ANDROID_HOME = /Users/tahatesser/Code/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.5, Build version 11E608c
    • CocoaPods version 1.9.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 47.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.46.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.12.1

[✓] Connected device (5 available)
    • SM M305F      • 32003c30dc19668f          • android-arm64  • Android 10
      (API 29)
    • Taha’s iPhone • 00008020-001059882212002E • ios            • iOS 13.5.1
    • macOS desktop • macos                     • darwin-x64     • Mac OS X
      10.15.5 19F101
    • Web Server    • web-server                • web-javascript • Flutter Tools
    • Chrome        • chrome                    • web-javascript • Google Chrome
      83.0.4103.116

• No issues found!

``` 

</details>

**Comment by seriousManual** [comment]
having this issue too

**Comment by exaby73** [comment]
As of `Master (3.6.0-3.0.pre.54)`, I can still reproduce this issue. Updating labels to reflect the same;

<details>
<summary>Code sample migrated to null safety</summary>

```dart
import 'package:flutter/material.dart';
import 'package:flutter_test/flutter_test.dart';

main() {
  testWidgets('Triggers validation with right value', (tester) async {
    String? fieldValidatorValue;
    bool validatorTriggered = false;
    String? fieldValidator(String? value) {
      validatorTriggered = true;
      // cache value received for validation
      fieldValidatorValue = value;
      return null;
    }

    final tFormApp = newFormApp(fieldValidator);
    await tester.pumpWidget(tFormApp);
    await tester.pumpAndSettle();
    // we expect both fieldValidatorValue and formState.lastEditorValue to be `null`
    final formFinder = find.byType(TestForm);
    final formState = tester.state<TestFormState>(formFinder);
    expect(validatorTriggered, isFalse);
    expect(fieldValidatorValue, isNull);
    expect(fieldValidatorValue, formState.lastEditorValueBeforeValidation);

    // when listeners of the TextEditingController are called, my expectation would be
    // that [FormFieldState.value] has already been updated to the new value
    // Side effect of not updating FormFieldState.value is that validator functions always
    // receive the old cached value instead.
    await tester.enterText(find.byType(TextFormField), 'a');
    await tester.pumpAndSettle();
    expect(validatorTriggered, isTrue);
    expect(formState.lastEditorValueBeforeValidation, 'a');
    expect(fieldValidatorValue, formState.lastEditorValueBeforeValidation);
  });
}

Widget newFormApp(FormFieldValidator<String> validator) {
  final testForm = TestForm(validator: validator);
  return MaterialApp(
    home: Scaffold(
      body: testForm,
    ),
  );
}

class TestForm extends StatefulWidget {
  final FormFieldValidator<String> validator;

  const TestForm({Key? key, required this.validator}) : super(key: key);

  @override
  TestFormState createState() => TestFormState();
}

class TestFormState extends State<TestForm> {
  final _editingController = TextEditingController();
  final _formKey = GlobalKey();
  @visibleForTesting
  String? lastEditorValueBeforeValidation;

  @override
  void initState() {
    super.initState();
    _editingController.addListener(inputChanged);
  }

  @override
  void dispose() {
    _editingController.dispose();
    super.dispose();
  }

  void inputChanged() {
    // cache controller text for test to compare
    lastEditorValueBeforeValidation = _editingController.text;
    // trigger validation
    (_formKey.currentState as FormState).validate();
  }

  @override
  Widget build(BuildContext context) {
    return Form(
      key: _formKey,
      child: TextFormField(
        controller: _editingController,
        validator: widget.validator,
      ),
    );
  }
}
```

</details>
