### ISSUE TITLE
Second run of `flutter run` of codelab throws exception

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#4051]
I deleted my build/ directory, and I used Atom to try to run the Flutter app on my Nexus 5. The app started on my phone, but I don't see messages. I see the following exception:

![screen shot 2016-05-19 at 12 39 56 pm](https://cloud.githubusercontent.com/assets/5479/15407247/cf57b7d0-1dbe-11e6-99d3-731d1818be3b.png)

```
W/System.err: java.io.IOException: FileClientSessionCache: Failed to delete /data/user/0/com.google.android.gms/app_sslcache/r11---sn-n4v7knel.gvt1.com.443.
W/System.err:   at com.android.org.conscrypt.FileClientSessionCache$Impl.delete(FileClientSessionCache.java:299)
W/System.err:   at com.android.org.conscrypt.FileClientSessionCache$Impl.makeRoom(FileClientSessionCache.java:258)
W/System.err:   at com.android.org.conscrypt.FileClientSessionCache$Impl.putSessionData(FileClientSessionCache.java:216)
W/System.err:   at com.android.org.conscrypt.ClientSessionContext.putSession(ClientSessionContext.java:120)
W/System.err:   at com.android.org.conscrypt.SSLParametersImpl.setupSession(SSLParametersImpl.java:610)
W/System.err:   at com.android.org.conscrypt.OpenSSLSocketImpl.startHandshake(OpenSSLSocketImpl.java:366)
W/System.err:   at android.net.SSLCertificateSocketFactory.verifyHostname(SSLCertificateSocketFactory.java:198)
W/System.err:   at android.net.SSLCertificateSocketFactory.createSocket(SSLCertificateSocketFactory.java:443)
W/System.err:   at com.android.okhttp.internal.http.SocketConnector.connectTls(SocketConnector.java:89)
W/System.err:   at com.android.okhttp.Connection.connect(Connection.java:143)
W/System.err:   at com.android.okhttp.Connection.connectAndSetOwner(Connection.java:185)
```

**Comment by Hixie** [comment]
Closing bugs relating to our old codelab. We will have a new codelab at some point.
