### ISSUE TITLE
flutter crashing behind nginx proxy

### ISSUE THREAD

**Issue by omontoya** [flutter/flutter#40535]
## command

flutter run -d chrome --web-port 4200

## exception

StateError: Bad state: Could not connect to application with appInstanceId: 3533c200-d7f3-11e9-a909-5b4d2faa400c

```
#0      DevHandler.startDebugService (package:dwds/src/handlers/dev_handler.dart:113:7)
<asynchronous suspension>
#1      DevHandler.loadAppServices.<anonymous closure> (package:dwds/src/handlers/dev_handler.dart:142:19)
<asynchronous suspension>
#2      _LinkedHashMapMixin.putIfAbsent (dart:collection-patch/compact_hash.dart:291:23)
#3      DevHandler.loadAppServices (package:dwds/src/handlers/dev_handler.dart:140:24)
#4      Dwds.debugConnection (package:dwds/dwds.dart:51:46)
<asynchronous suspension>
#5      WebFs.runAndDebug.<anonymous closure> (package:flutter_tools/src/build_runner/web_fs.dart:115:59)
<asynchronous suspension>
#6      _rootRunUnary (dart:async/zone.dart:1132:38)
#7      _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#8      _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
#9      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#10     _DelayedData.perform (dart:async/stream_impl.dart:591:14)
#11     _StreamImplEvents.handleNext (dart:async/stream_impl.dart:707:11)
#12     _PendingEvents.schedule.<anonymous closure> (dart:async/stream_impl.dart:667:7)
#13     _rootRun (dart:async/zone.dart:1120:38)
#14     _CustomZone.run (dart:async/zone.dart:1021:19)
#15     _CustomZone.runGuarded (dart:async/zone.dart:923:7)
#16     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:963:23)
#17     _rootRun (dart:async/zone.dart:1124:13)
#18     _CustomZone.run (dart:async/zone.dart:1021:19)
#19     _CustomZone.runGuarded (dart:async/zone.dart:923:7)
#20     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:963:23)
#21     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#22     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#23     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:116:13)
#24     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:173:5)
```

## flutter doctor

```
[✓] Flutter (Channel master, v1.10.3-pre.37, on Mac OS X 10.14.6 18G95, locale en-US)
    • Flutter version 1.10.3-pre.37 at /Users/omontoya/flutter
    • Framework revision 64300123fa (2 days ago), 2019-09-13 19:46:58 -0700
    • Engine revision 00c8941dae
    • Dart version 2.6.0 (build 2.6.0-dev.0.0 a554c8be6b)

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/omontoya/Library/Android/sdk/
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = /Users/omontoya/Library/Android/sdk/
    • ANDROID_SDK_ROOT = /Users/omontoya/Library/Android/sdk/
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version openjdk version "1.8.0_202-release"
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 10.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.3, Build version 10G8
    • CocoaPods version 1.7.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 39.0.3
    • Dart plugin version 191.8423
    • Java version openjdk version "1.8.0_202-release"

[✓] IntelliJ IDEA Community Edition (version 2019.2)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 38.2.4
    • Dart plugin version 192.6459

[✓] VS Code
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.1.0

[✓] Connected device (2 available)
    • Chrome • chrome • web-javascript • Google Chrome 76.0.3809.132
    • Server • web    • web-javascript • Flutter Tools

• No issues found!
```

**Comment by yjbanov** [comment]
@grouma This is because of the specialized browser-DDC handshake, right?

**Comment by jonahwilliams** [comment]
We'll likely need to catch this error in the tool. Then we can recommend using the debug extension if possible

**Comment by yjbanov** [comment]
> We'll likely need to catch this error in the tool.

Agreed, but I think `dwds` should communicate this error more gracefully than a `StateError`.

**Comment by grouma** [comment]
cc @jakemac53 this should be resolved with your recent changes around handshakes / null isolates correct?

**Comment by jakemac53** [comment]
This does not look related to the null isolate issue - we throw this error when trying to connect to an app but we can't find the requested dart app open in any chrome tab.

We could throw a more specialized error here if that makes it easier to more explicitly catch?

**Comment by grouma** [comment]
@jonahwilliams see https://github.com/dart-lang/webdev/pull/750 for handling these errors

**Comment by jonahwilliams** [comment]
Fixed via https://github.com/flutter/flutter/pull/43544
