### ISSUE TITLE
web hot-restart bug report

### ISSUE THREAD

**Issue by a-h-mzd** [flutter/flutter#40547]
Happened when I tried to hot-restart.

## command

flutter run -d chrome

## exception

ChromeDebugException: Unexpected error from chrome devtools:
text: Uncaught
exception:
  description: ReferenceError: require is not defined
    at <anonymous>:1:1
  type: object
  value: null
attempted JS eval: `require('dart_sdk').dart.getLibraries();`

```
#0      handleErrorIfPresent (package:dwds/src/services/chrome_proxy_service.dart:569:5)
#1      AppInspector._getLibraryRefs (package:dwds/src/debugging/inspector.dart:489:5)
<asynchronous suspension>
#2      AppInspector._initialize (package:dwds/src/debugging/inspector.dart:72:36)
<asynchronous suspension>
#3      AppInspector.initialize (package:dwds/src/debugging/inspector.dart:108:21)
#4      _AsyncAwaitCompleter.start (dart:async-patch/async_patch.dart:43:6)
#5      AppInspector.initialize (package:dwds/src/debugging/inspector.dart:84:41)
#6      ChromeProxyService.createIsolate (package:dwds/src/services/chrome_proxy_service.dart:112:37)
#7      _AsyncAwaitCompleter.start (dart:async-patch/async_patch.dart:43:6)
#8      ChromeProxyService.createIsolate (package:dwds/src/services/chrome_proxy_service.dart:106:29)
#9      DevHandler._handleConnection.<anonymous closure> (package:dwds/src/handlers/dev_handler.dart:259:15)
#10     _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:71:64)
#11     _rootRunUnary (dart:async/zone.dart:1132:38)
#12     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#13     _FutureListener.handleValue (dart:async/future_impl.dart:137:18)
#14     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:678:45)
#15     Future._propagateToListeners (dart:async/future_impl.dart:707:32)
#16     Future._addListener.<anonymous closure> (dart:async/future_impl.dart:387:9)
#17     _rootRun (dart:async/zone.dart:1124:13)
#18     _CustomZone.run (dart:async/zone.dart:1021:19)
#19     _CustomZone.runGuarded (dart:async/zone.dart:923:7)
#20     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:963:23)
#21     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#22     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#23     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:116:13)
#24     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:173:5)
```

## flutter doctor

```
[32m[✓][39m Flutter (Channel dev, v1.10.2, on Linux, locale en_US.UTF-8)
    [32m•[39m Flutter version 1.10.2 at /home/ehsan/FlutterSDK
    [32m•[39m Framework revision f5733f7a62 (4 days ago), 2019-09-11 21:03:42 -0700
    [32m•[39m Engine revision 7ea9884ab0
    [32m•[39m Dart version 2.5.0 (build 2.5.0-dev.4.0 be66176534)

[32m[✓][39m Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    [32m•[39m Android SDK at /home/ehsan/AndroidSDK
    [32m•[39m Android NDK location not configured (optional; useful for native profiling support)
    [32m•[39m Platform android-28, build-tools 28.0.3
    [32m•[39m ANDROID_HOME = /home/ehsan/AndroidSDK
    [32m•[39m Java binary at: /home/ehsan/.local/share/JetBrains/Toolbox/apps/AndroidStudio/ch-0/183.5522156/jre/bin/java
    [32m•[39m Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    [32m•[39m All Android licenses accepted.

[32m[✓][39m Chrome - develop for the web
    [32m•[39m CHROME_EXECUTABLE = /snap/bin/chromium

[32m[✓][39m Android Studio (version 3.5)
    [32m•[39m Android Studio at /home/ehsan/.local/share/JetBrains/Toolbox/apps/AndroidStudio/ch-0/183.5522156
    [32m•[39m Flutter plugin version 36.1.1
    [32m•[39m Dart plugin version 183.6270
    [32m•[39m Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[32m[✓][39m VS Code (version 1.38.1)
    [32m•[39m VS Code at /usr/share/code
    [32m•[39m Flutter extension version 3.4.1

[32m[✓][39m Connected device (2 available)
    [32m•[39m Chrome • chrome • web-javascript • Chromium 77.0.3865.75 snap
    [32m•[39m Server • web    • web-javascript • Flutter Tools

[32m•[39m No issues found!
```

**Comment by janmoppel** [comment]
Hello @a-h-mzd !

Thank you for posting an issue.
It seems like this behaviour was previously reported as well: #39246. When solution will be found - it will be posted on that issue.

As there is a report about the same problem, closing this thread for now.

Thank you.
