### ISSUE TITLE
NoSuchMethodError: NoSuchMethodError: The getter 'isolate' was called on null.

### ISSUE THREAD

**Issue by omontoya** [flutter/flutter#40557]
Flutter crash report; please file at https://github.com/flutter/flutter/issues.

## command

flutter run -d chrome --web-port 4200

## exception

NoSuchMethodError: NoSuchMethodError: The getter 'isolate' was called on null.
Receiver: null
Tried calling: isolate

```
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:51:5)
#1      Debugger._pauseHandler (package:dwds/src/debugging/debugger.dart:403:29)
<asynchronous suspension>
#2      _rootRunUnary (dart:async/zone.dart:1132:38)
#3      _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#4      _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
#5      CastStreamSubscription._onData (dart:_internal/async_cast.dart:81:11)
#6      _rootRunUnary (dart:async/zone.dart:1132:38)
#7      _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#8      _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
#9      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#10     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#11     _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:68:11)
#12     _EventSinkWrapper.add (dart:async/stream_transformers.dart:15:11)
#13     WipDomain.eventStream.<anonymous closure>.<anonymous closure> (package:webkit_inspection_protocol/webkit_inspection_protocol.dart:295:26)
#14     _HandlerEventSink.add (dart:async/stream_transformers.dart:228:7)
#15     _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:120:24)
#16     _rootRunUnary (dart:async/zone.dart:1132:38)
#17     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#18     _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
#19     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#20     _DelayedData.perform (dart:async/stream_impl.dart:591:14)
#21     _StreamImplEvents.handleNext (dart:async/stream_impl.dart:707:11)
#22     _PendingEvents.schedule.<anonymous closure> (dart:async/stream_impl.dart:667:7)
#23     _rootRun (dart:async/zone.dart:1120:38)
#24     _CustomZone.run (dart:async/zone.dart:1021:19)
#25     _CustomZone.runGuarded (dart:async/zone.dart:923:7)
#26     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:963:23)
#27     _rootRun (dart:async/zone.dart:1124:13)
#28     _CustomZone.run (dart:async/zone.dart:1021:19)
#29     _CustomZone.runGuarded (dart:async/zone.dart:923:7)
#30     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:963:23)
#31     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#32     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#33     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:116:13)
#34     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:173:5)
```

## flutter doctor

```
[32m[✓][39m Flutter (Channel master, v1.10.3-pre.42, on Mac OS X 10.14.6 18G95, locale en-US)
    [32m•[39m Flutter version 1.10.3-pre.42 at /Users/omontoya/flutter
    [32m•[39m Framework revision 5f14e98d3f (2 hours ago), 2019-09-15 22:31:41 -0400
    [32m•[39m Engine revision 6fbbfe18e8
    [32m•[39m Dart version 2.6.0 (build 2.6.0-dev.0.0 a554c8be6b)

[32m[✓][39m Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    [32m•[39m Android SDK at /Users/omontoya/Library/Android/sdk/
    [32m•[39m Android NDK location not configured (optional; useful for native profiling support)
    [32m•[39m Platform android-28, build-tools 28.0.3
    [32m•[39m ANDROID_HOME = /Users/omontoya/Library/Android/sdk/
    [32m•[39m ANDROID_SDK_ROOT = /Users/omontoya/Library/Android/sdk/
    [32m•[39m Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    [32m•[39m Java version openjdk version "1.8.0_202-release"
    [32m•[39m All Android licenses accepted.

[32m[✓][39m Xcode - develop for iOS and macOS (Xcode 10.3)
    [32m•[39m Xcode at /Applications/Xcode.app/Contents/Developer
    [32m•[39m Xcode 10.3, Build version 10G8
    [32m•[39m CocoaPods version 1.7.0

[32m[✓][39m Chrome - develop for the web
    [32m•[39m Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[32m[✓][39m Android Studio (version 3.5)
    [32m•[39m Android Studio at /Applications/Android Studio.app/Contents
    [32m•[39m Flutter plugin version 39.0.3
    [32m•[39m Dart plugin version 191.8423
    [32m•[39m Java version openjdk version "1.8.0_202-release"

[32m[✓][39m IntelliJ IDEA Community Edition (version 2019.2)
    [32m•[39m IntelliJ at /Applications/IntelliJ IDEA CE.app
    [32m•[39m Flutter plugin version 38.2.4
    [32m•[39m Dart plugin version 192.6459

[32m[✓][39m VS Code
    [32m•[39m VS Code at /Applications/Visual Studio Code.app/Contents
    [32m•[39m Flutter extension version 3.1.0

[32m[✓][39m Connected device (2 available)
    [32m•[39m Chrome • chrome • web-javascript • Google Chrome 76.0.3809.132
    [32m•[39m Server • web    • web-javascript • Flutter Tools

[32m•[39m No issues found!
```

**Comment by escamoteur** [comment]
Today happend to me with newer Flutter version:

Flutter crash report; please file at https://github.com/flutter/flutter/issues.

## command

flutter run -d chrome

## exception

NoSuchMethodError: NoSuchMethodError: The getter 'isolate' was called on null.
Receiver: null
Tried calling: isolate

```
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:51:5)
#1      Debugger._pauseHandler (package:dwds/src/debugging/debugger.dart:403:29)
<asynchronous suspension>
#2      _rootRunUnary (dart:async/zone.dart:1132:38)
#3      _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#4      _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
#5      CastStreamSubscription._onData (dart:_internal/async_cast.dart:81:11)
#6      _rootRunUnary (dart:async/zone.dart:1132:38)
#7      _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#8      _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
#9      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#10     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#11     _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:68:11)
#12     _EventSinkWrapper.add (dart:async/stream_transformers.dart:15:11)
#13     WipDomain.eventStream.<anonymous closure>.<anonymous closure> (package:webkit_inspection_protocol/webkit_inspection_protocol.dart:295:26)
#14     _HandlerEventSink.add (dart:async/stream_transformers.dart:228:7)
#15     _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:120:24)
#16     _rootRunUnary (dart:async/zone.dart:1132:38)
#17     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#18     _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
#19     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#20     _DelayedData.perform (dart:async/stream_impl.dart:591:14)
#21     _StreamImplEvents.handleNext (dart:async/stream_impl.dart:707:11)
#22     _PendingEvents.schedule.<anonymous closure> (dart:async/stream_impl.dart:667:7)
#23     _rootRun (dart:async/zone.dart:1120:38)
#24     _CustomZone.run (dart:async/zone.dart:1021:19)
#25     _CustomZone.runGuarded (dart:async/zone.dart:923:7)
#26     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:963:23)
#27     _rootRun (dart:async/zone.dart:1124:13)
#28     _CustomZone.run (dart:async/zone.dart:1021:19)
#29     _CustomZone.runGuarded (dart:async/zone.dart:923:7)
#30     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:963:23)
#31     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#32     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#33     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:116:13)
#34     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:173:5)
```

## flutter doctor

```
[32m[✓][39m Flutter (Channel master, v1.10.6-pre.19, on Microsoft Windows [Version 10.0.18362.295], locale de-DE)
    [32m•[39m Flutter version 1.10.6-pre.19 at C:\Entwicklung\flutter
    [32m•[39m Framework revision ec07e039c2 (9 hours ago), 2019-09-19 21:37:41 -0400
    [32m•[39m Engine revision 70f21b0edb
    [32m•[39m Dart version 2.6.0 (build 2.6.0-dev.1.0 7c1821c4aa)

[32m[✓][39m Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    [32m•[39m Android SDK at C:\Users\escam\AppData\Local\Android\sdk
    [32m•[39m Android NDK location not configured (optional; useful for native profiling support)
    [32m•[39m Platform android-29, build-tools 29.0.2
    [32m•[39m Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    [32m•[39m Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)
    [32m•[39m All Android licenses accepted.

[32m[✓][39m Chrome - develop for the web
    [32m•[39m Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[32m[✓][39m Android Studio (version 3.5)
    [32m•[39m Android Studio at C:\Program Files\Android\Android Studio
    [32m•[39m Flutter plugin version 39.0.3
    [32m•[39m Dart plugin version 191.8423
    [32m•[39m Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)

[32m[✓][39m IntelliJ IDEA Community Edition (version 2018.2)
    [32m•[39m IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2018.2.5
    [32m•[39m Flutter plugin version 29.1.3
    [32m•[39m Dart plugin version 182.4892.25

[32m[✓][39m VS Code, 64-bit edition (version 1.38.1)
    [32m•[39m VS Code at C:\Program Files\Microsoft VS Code
    [32m•[39m Flutter extension version 3.4.1

[32m[✓][39m Connected device (3 available)
    [32m•[39m Android SDK built for x86 64 • emulator-5554 • android-x64    • Android 7.1.1 (API 25) (emulator)
    [32m•[39m Chrome                       • chrome        • web-javascript • Google Chrome 76.0.3809.132
    [32m•[39m Server                       • web           • web-javascript • Flutter Tools

[32m•[39m No issues found!
```

**Comment by grouma** [comment]
@alan-knight has this been addressed?

**Comment by grouma** [comment]
These should all be addressed. Waiting on @jonahwilliams to pull the latest `package:dwds`

**Comment by jonahwilliams** [comment]
I haven't seen crashes like this in the error logs recently, so I'll call it fixed!
