### ISSUE TITLE
Flutter connectivity plugin has issue while checking internet status

### ISSUE THREAD

**Issue by JayM96** [flutter/flutter#40731]
## Steps to Reproduce

1. add connectivity: ^0.4.4 to pubspec.yaml
2. [network_utils.txt](https://github.com/flutter/flutter/files/3624505/network_utils.txt) add this file to your project.
3. Add the method to check internet status
```Dart
_submitSignUpForm() async {
    if (!_signUpFormKey.currentState.validate()) {
      return;
    }
    _signUpFormKey.currentState.save();

    print("Hello");
    NetworkCheck networkCheck = NetworkCheck();
    networkCheck.checkInternet((isNetworkPresent) async {
      if (!isNetworkPresent) {
        final snackBar =
            SnackBar(content: Text('Please check your internet connection !!'));

        Scaffold.of(context).showSnackBar(snackBar);
        return;
      } else {
        print("Hello2");
        setState(() {
          print("Hello3");
          isSignUpAuthenticating = true;
        });
      }
    });
  }
```

```Dart
import 'package:connectivity/connectivity.dart';

class NetworkCheck {
  Future<bool> check() async {
    var connectivityResult = await (Connectivity().checkConnectivity());
    if (connectivityResult == ConnectivityResult.mobile) {
      return true;
    } else if (connectivityResult == ConnectivityResult.wifi) {
      return true;
    }
    return false;
  }

  dynamic checkInternet(Function func) {
    check().then((internet) {
      if (internet != null && internet) {
        func(true);
      }
      else{
        func(false);
      }
    });
  }
}
```

## Logs
```
E/MethodChannel#plugins.flutter.io/connectivity(31648): Failed to handle method call
E/MethodChannel#plugins.flutter.io/connectivity(31648): java.lang.SecurityException: ConnectivityService: Neither user 10233 nor current process has android.permission.ACCESS_NETWORK_STATE.
E/MethodChannel#plugins.flutter.io/connectivity(31648): 	at android.os.Parcel.readException(Parcel.java:1627)
E/MethodChannel#plugins.flutter.io/connectivity(31648): 	at android.os.Parcel.readException(Parcel.java:1579)
E/MethodChannel#plugins.flutter.io/connectivity(31648): 	at android.net.IConnectivityManager$Stub$Proxy.getActiveNetwork(IConnectivityManager.java:1043)
E/MethodChannel#plugins.flutter.io/connectivity(31648): 	at android.net.ConnectivityManager.getActiveNetwork(ConnectivityManager.java:699)
E/MethodChannel#plugins.flutter.io/connectivity(31648): 	at io.flutter.plugins.connectivity.ConnectivityPlugin.getNetworkType(ConnectivityPlugin.java:70)
E/MethodChannel#plugins.flutter.io/connectivity(31648): 	at io.flutter.plugins.connectivity.ConnectivityPlugin.checkNetworkType(ConnectivityPlugin.java:135)
E/MethodChannel#plugins.flutter.io/connectivity(31648): 	at io.flutter.plugins.connectivity.ConnectivityPlugin.handleCheck(ConnectivityPlugin.java:131)
E/MethodChannel#plugins.flutter.io/connectivity(31648): 	at io.flutter.plugins.connectivity.ConnectivityPlugin.onMethodCall(ConnectivityPlugin.java:113)
E/MethodChannel#plugins.flutter.io/connectivity(31648): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:222)
E/MethodChannel#plugins.flutter.io/connectivity(31648): 	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:96)
E/MethodChannel#plugins.flutter.io/connectivity(31648): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:643)
E/MethodChannel#plugins.flutter.io/connectivity(31648): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/MethodChannel#plugins.flutter.io/connectivity(31648): 	at android.os.MessageQueue.next(MessageQueue.java:331)
E/MethodChannel#plugins.flutter.io/connectivity(31648): 	at android.os.Looper.loop(Looper.java:218)
E/MethodChannel#plugins.flutter.io/connectivity(31648): 	at android.app.ActivityThread.main(ActivityThread.java:5526)
E/MethodChannel#plugins.flutter.io/connectivity(31648): 	at java.lang.reflect.Method.invoke(Native Method)
E/MethodChannel#plugins.flutter.io/connectivity(31648): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
E/MethodChannel#plugins.flutter.io/connectivity(31648): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
E/flutter (31648): [ERROR:flutter/lib/ui/ui_dart_state.cc(148)] Unhandled Exception: PlatformException(error, ConnectivityService: Neither user 10233 nor current process has android.permission.ACCESS_NETWORK_STATE., null)
E/flutter (31648): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:564:7)
E/flutter (31648): #1      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:316:33)
E/flutter (31648): <asynchronous suspension>
E/flutter (31648): #2      Connectivity.checkConnectivity (package:connectivity/connectivity.dart:65:47)
E/flutter (31648): <asynchronous suspension>
E/flutter (31648): #3      NetworkCheck.check (package:flutter_quotes/utils/network_utils.dart:5:52)
E/flutter (31648): <asynchronous suspension>
E/flutter (31648): #4      NetworkCheck.checkInternet (package:flutter_quotes/utils/network_utils.dart:15:5)
E/flutter (31648): #5      _AuthPageState._submitLoginForm (package:flutter_quotes/auth/auth_page.dart:52:18)
E/flutter (31648): <asynchronous suspension>
E/flutter (31648): #6      _AuthPageState._buildSignIn.<anonymous closure> (package:flutter_quotes/auth/auth_page.dart:560:27)
E/flutter (31648): #7      _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:635:14)
E/flutter (31648): #8      _InkResponseState.build.<anonymous closure> (package:flutter/src/material/ink_well.dart:711:32)
E/flutter (31648): #9      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:182:24)
E/flutter (31648): #10     TapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:365:11)
E/flutter (31648): #11     TapGestureRecognizer.acceptGesture (package:flutter/src/gestures/tap.dart:312:7)
E/flutter (31648): #12     GestureArenaManager.sweep (package:flutter/src/gestures/arena.dart:156:27)
E/flutter (31648): #13     _WidgetsFlutterBinding&BindingBase&GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:222:20)
E/flutter (31648): #14     _WidgetsFlutterBinding&BindingBase&GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:198:22)
E/flutter (31648): #15     _WidgetsFlutterBinding&BindingBase&GestureBinding._handlePointerEvent (package:flutter/src/gestures/binding.dart:156:7)
E/flutter (31648): #16     _WidgetsFlutterBinding&BindingBase&GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:102:7)
E/flutter (31648): #17     _WidgetsFlutterBinding&BindingBase&GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:86:7)
E/flutter (31648): #18     _rootRunUnary (dart:async/zone.dart:1136:13)
E/flutter (31648): #19     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
E/flutter (31648): #20     _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
E/flutter (31648): #21     _invoke1 (dart:ui/hooks.dart:250:10)
E/flutter (31648): #22     _dispatchPointerDataPacket (dart:ui/hooks.dart:159:5)
E/flutter (31648): 
W/FA      (31648): Tasks have been queued for a long time
```

**Comment by escamoteur** [comment]
I think the reason is clearly stated in the log: `Neither user 10233 nor current process has android.permission.ACCESS_NETWORK_STATE`
See http://code2care.org/pages/neither-user-nor-current-process-has-android-permission-access_network_state/

Please be so kind and ask on Stackoverflow first the next time.

**Comment by JayM96** [comment]
Sorry, but i have already added in the manifest file so far. After that i have added this question to the github.

**Comment by escamoteur** [comment]
Hmm still seems to be more an Android problem. Try if SO has an answer
