### ISSUE TITLE
Build  on AppCenter failing to fetch firebase pods with `firebase_auth`

### ISSUE THREAD

**Issue by KieranLafferty** [flutter/flutter#40736]
## Steps to Reproduce

1. Upload and build app on appcenter

## Logs

```
  Inspecting targets to integrate
      Using `ARCHS` setting to build architectures of target `Pods-Runner`: (``)

    Finding Podfile changes
      M Flutter
      - firebase_auth
      - firebase_core
      - purchases_flutter
      - url_launcher

    Fetching external sources
    -> Fetching podspec for `Flutter` from `.symlinks/flutter/ios-release`
    -> Fetching podspec for `firebase_auth` from `.symlinks/plugins/firebase_auth/ios`
    -> Fetching podspec for `firebase_core` from `.symlinks/plugins/firebase_core/ios`
    -> Fetching podspec for `purchases_flutter` from `.symlinks/plugins/purchases_flutter/ios`
    -> Fetching podspec for `url_launcher` from `.symlinks/plugins/url_launcher/ios`

    Resolving dependencies of `Podfile`
    [!] CocoaPods could not find compatible versions for pod "GoogleUtilities/AppDelegateSwizzler":
      In snapshot (Podfile.lock):
        GoogleUtilities/AppDelegateSwizzler (= 6.3.0, ~> 6.0, ~> 6.2)

      In Podfile:
        firebase_auth (from `.symlinks/plugins/firebase_auth/ios`) was resolved to 0.0.1, which depends on
          Firebase/Auth (~> 6.0) was resolved to 6.8.1, which depends on
            FirebaseAuth (~> 6.2.3) was resolved to 6.2.3, which depends on
              GoogleUtilities/AppDelegateSwizzler (~> 6.2)

    It seems like you've changed the constraints of dependency `GoogleUtilities/AppDelegateSwizzler` inside your development pod `firebase_auth`.
    You should run `pod update GoogleUtilities/AppDelegateSwizzler` to apply changes you've made.

    /usr/local/lib/ruby/gems/2.6.0/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:328:in `raise_error_unless_state'
    /usr/local/lib/ruby/gems/2.6.0/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:310:in `block in unwind_for_conflict'
    /usr/local/lib/ruby/gems/2.6.0/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:308:in `tap'
    /usr/local/lib/ruby/gems/2.6.0/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:308:in `unwind_for_conflict'
    /usr/local/lib/ruby/gems/2.6.0/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:257:in `process_topmost_state'
    /usr/local/lib/ruby/gems/2.6.0/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:182:in `resolve'
    /usr/local/lib/ruby/gems/2.6.0/gems/molinillo-0.6.6/lib/molinillo/resolver.rb:43:in `resolve'
    /usr/local/lib/ruby/gems/2.6.0/gems/cocoapods-1.7.5/lib/cocoapods/resolver.rb:88:in `resolve'
    /usr/local/lib/ruby/gems/2.6.0/gems/cocoapods-1.7.5/lib/cocoapods/installer/analyzer.rb:939:in `block in resolve_dependencies'
    /usr/local/lib/ruby/gems/2.6.0/gems/cocoapods-1.7.5/lib/cocoapods/***_interface.rb:64:in `section'
    /usr/local/lib/ruby/gems/2.6.0/gems/cocoapods-1.7.5/lib/cocoapods/installer/analyzer.rb:937:in `resolve_dependencies'
    /usr/local/lib/ruby/gems/2.6.0/gems/cocoapods-1.7.5/lib/cocoapods/installer/analyzer.rb:118:in `analyze'
    /usr/local/lib/ruby/gems/2.6.0/gems/cocoapods-1.7.5/lib/cocoapods/installer.rb:398:in `analyze'
    /usr/local/lib/ruby/gems/2.6.0/gems/cocoapods-1.7.5/lib/cocoapods/installer.rb:221:in `block in resolve_dependencies'
    /usr/local/lib/ruby/gems/2.6.0/gems/cocoapods-1.7.5/lib/cocoapods/***_interface.rb:64:in `section'
    /usr/local/lib/ruby/gems/2.6.0/gems/cocoapods-1.7.5/lib/cocoapods/installer.rb:220:in `resolve_dependencies'
    /usr/local/lib/ruby/gems/2.6.0/gems/cocoapods-1.7.5/lib/cocoapods/installer.rb:156:in `install!'
    /usr/local/lib/ruby/gems/2.6.0/gems/cocoapods-1.7.5/lib/cocoapods/command/install.rb:51:in `run'
    /usr/local/lib/ruby/gems/2.6.0/gems/claide-1.0.3/lib/claide/command.rb:334:in `run'
    /usr/local/lib/ruby/gems/2.6.0/gems/cocoapods-1.7.5/lib/cocoapods/command.rb:52:in `run'
    /usr/local/lib/ruby/gems/2.6.0/gems/cocoapods-1.7.5/bin/pod:55:in `<top (required)>'
    /usr/local/lib/ruby/gems/2.6.0/bin/pod:23:in `load'
    /usr/local/lib/ruby/gems/2.6.0/bin/pod:23:in `<main>'

Error running pod install
##[error]/bin/bash failed with return code: 1
##[error]Bash failed with error: /bin/bash failed with return code: 1
```

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, v1.9.1+hotfix.2, on Mac OS X 10.14.6 18G95, locale en)
[!] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses
[✓] Xcode - develop for iOS and macOS (Xcode 10.3)
[!] Android Studio (not installed)
[!] Connected device
    ! No devices available
```

**Comment by KieranLafferty** [comment]
This happens on stable flutter channel after deleting and re-creating ios app using `flutter create .` within the flutter app directory

**Comment by escamoteur** [comment]
You are building the app on MS AppCenter? This doesn't happen when you build locally?
Did you use this setup https://buildflutter.com/deploying-flutter-apps-via-appcenter/ ?
could you share your build script?

**Comment by janmoppel** [comment]
Hello @KieranLafferty !

Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the issue, if you have any more information for us; we will reopen it right away!

Thank you for your contribution.

P.S. If anyone still experience the same problem, please file a new issue with the information required in the template.
All system setups can be slightly different so it’s always better to open new issues and reference related issues.
