### ISSUE TITLE
flutter doctor -v crash when checking Windows Desktop support

### ISSUE THREAD

**Issue by Zazo032** [flutter/flutter#40748]
## Steps to Reproduce

1. `flutter channel master`
2. `flutter upgrade`
3. `flutter doctor -v`

## Logs

```
PS C:\Users\Cristian> flutter doctor -v
[√] Flutter (Channel master, v1.10.4-pre.55, on Microsoft Windows [VersiÃ³n 10.0.17134.1006], locale es-ES)
    • Flutter version 1.10.4-pre.55 at C:\src\flutter
    • Framework revision abfad9cc49 (5 hours ago), 2019-09-18 00:14:41 -0400
    • Engine revision 36be89da49
    • Dart version 2.6.0 (build 2.6.0-dev.1.0 f22f62c85d)


[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at C:\Users\Cristian\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[☠] Visual Studio - develop for Windows (the doctor check crashed)
    X Due to an error, the doctor check did not complete. If the error message below is not helpful, please let us know
      about this issue at https://github.com/flutter/flutter/issues.
    X NoSuchMethodError: The method 'split' was called on null.
      Receiver: null
      Tried calling: split(".")
    • #0      Object.noSuchMethod (dart:core-patch/object_patch.dart:51:5)
      #1      VisualStudioValidator.majorVersion (package:flutter_tools/src/windows/visual_studio_validator.dart:15:65)
      #2      VisualStudioValidator.validate (package:flutter_tools/src/windows/visual_studio_validator.dart:64:55)
      <asynchronous suspension>
      #3      asyncGuard.<anonymous closure> (package:flutter_tools/src/base/async_guard.dart:111:32)
      <asynchronous suspension>
      #4      _rootRun (dart:async/zone.dart:1124:13)
      #5      _CustomZone.run (dart:async/zone.dart:1021:19)
      #6      _runZoned (dart:async/zone.dart:1516:10)
      #7      runZoned (dart:async/zone.dart:1500:12)
      #8      asyncGuard (package:flutter_tools/src/base/async_guard.dart:109:3)
      #9      Doctor.startValidatorTasks (package:flutter_tools/src/doctor.dart:158:9)
      #10     Doctor.diagnose (package:flutter_tools/src/doctor.dart:252:41)
      #11     _AsyncAwaitCompleter.start (dart:async-patch/async_patch.dart:43:6)
      #12     Doctor.diagnose (package:flutter_tools/src/doctor.dart:241:24)
      #13     DoctorCommand.runCommand (package:flutter_tools/src/commands/doctor.dart:59:39)
      #14     _AsyncAwaitCompleter.start (dart:async-patch/async_patch.dart:43:6)
      #15     DoctorCommand.runCommand (package:flutter_tools/src/commands/doctor.dart:45:42)
      #16     FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:519:18)
      #17     _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:71:64)
      #18     _rootRunUnary (dart:async/zone.dart:1132:38)
      #19     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
      #20     _FutureListener.handleValue (dart:async/future_impl.dart:137:18)
      #21     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:678:45)
      #22     Future._propagateToListeners (dart:async/future_impl.dart:707:32)
      #23     Future._completeWithValue (dart:async/future_impl.dart:522:5)
      #24     Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:552:7)
      #25     _rootRun (dart:async/zone.dart:1124:13)
      #26     _CustomZone.run (dart:async/zone.dart:1021:19)
      #27     _CustomZone.runGuarded (dart:async/zone.dart:923:7)
      #28     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:963:23)
      #29     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
      #30     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
      #31     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:116:13)
      #32     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:173:5)


[√] Android Studio (version 3.5)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 39.0.3
    • Dart plugin version 191.8423
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)

[√] Connected device (3 available)
    • Windows • Windows • windows-x64    • Microsoft Windows [VersiÃ³n 10.0.17134.1006]
    • Chrome  • chrome  • web-javascript • Google Chrome 77.0.3865.75
    • Server  • web     • web-javascript • Flutter Tools

! Doctor found issues in 1 category.
```

**Comment by escamoteur** [comment]
Do you have Visual Studio installed? If yes, which version?

**Comment by Zazo032** [comment]
No, I don't have Visual Studio installed, that may be the crash source but it should't fail to check if VS is not installed

**Comment by escamoteur** [comment]
100% agree, just wanted to clarify

**Comment by stuartmorgan** [comment]
@franciscojma86 This is a regression from the change to list components when VS isn't installed. We should allow passing null as the version from that branch, and have the VS class use the latest known version to choose strings when it's null.

Also, the test should be changed so that `setUp` doesn't always mock a valid installation as a baseline, since that prevented this from being caught by the tests.
