### ISSUE TITLE
Can't build flutter desktop example on windows 7

### ISSUE THREAD

**Issue by marinat** [flutter/flutter#40749]
Result of flutter run -d windows -v:
```
[  +47 ms] Building Windows application...
[ +174 ms] **********************************************************************
[   +1 ms] ** Visual Studio 2019 Developer Command Prompt v16.2.5
[   +1 ms] ** Copyright (c) 2019 Microsoft Corporation
[   +2 ms] **********************************************************************
[+1477 ms] [vcvarsall.bat] Environment initialized for: 'x64'
[ +125 ms] Microsoft (R) Build Engine version 16.2.37902+b5aaefc9f for .NET Framework
[   +2 ms] Copyright (C) Microsoft Corporation. All rights reserved.
[   +1 ms] Building the projects in this solution one at a time. To enable parallel build, please add the "-m" switch.
[  +62 ms] Build started 18.09.2019 13:37:25.
[ +226 ms] Project "D:\flutter-desktop-embedding-master\example\windows\Runner.sln" on node 1 (default targets).
[   +4 ms] ValidateSolutionConfiguration:
[   +1 ms]   Building solution configuration "Debug|x64".
[ +129 ms] Project "D:\flutter-desktop-embedding-master\example\windows\Runner.sln" (1) is building
"D:\flutter-desktop-embedding-master\example\windows\Runner.vcxproj" (2) on node 1 (default targets).
[   +3 ms] D:\flutter-desktop-embedding-master\example\windows\Runner.vcxproj(42,5): error MSB4019: The imported project

"D:\flutter-desktop-embedding-master\example\windows\flutter\Generated.props" was not found. Confirm that the path in
the <Import> declaration is correct, and that the file exists on disk.
[   +4 ms] Done Building Project "D:\flutter-desktop-embedding-master\example\windows\Runner.vcxproj" (default targets)
-- FAILED.
[  +25 ms] Done Building Project "D:\flutter-desktop-embedding-master\example\windows\Runner.sln" (default targets) --
FAILED.
[   +8 ms] Build FAILED.
[   +7 ms] "D:\flutter-desktop-embedding-master\example\windows\Runner.sln" (default target) (1) ->
[   +1 ms] "D:\flutter-desktop-embedding-master\example\windows\Runner.vcxproj" (default target) (2) ->
[   +1 ms]   D:\flutter-desktop-embedding-master\example\windows\Runner.vcxproj(42,5): error MSB4019: The imported
project "D:\flutter-desktop-embedding-master\example\windows\flutter\Generated.props" was not found. Confirm that the
path in the <Import> declaration is correct, and that the file exists on disk.
[  +14 ms]     0 Warning(s)
[   +1 ms]     1 Error(s)
[   +1 ms] Time Elapsed 00:00:00.41
[  +66 ms] Building Windows application... (completed in 2,3s)
[   +6 ms] "flutter run" took 3┬á546ms.
Build process failed. To view the stack trace, please run `flutter run -d windows -v`.

#0      throwToolExit (package:flutter_tools/src/base/common.dart:28:3)
#1      buildWindows (package:flutter_tools/src/windows/build_windows.dart:94:5)
<asynchronous suspension>
#2      WindowsDevice.startApp (package:flutter_tools/src/windows/windows_device.dart:84:13)
<asynchronous suspension>
#3      FlutterDevice.runHot (package:flutter_tools/src/resident_runner.dart:376:54)
<asynchronous suspension>
#4      HotRunner.run (package:flutter_tools/src/run_hot.dart:258:39)
<asynchronous suspension>
#5      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:480:37)
<asynchronous suspension>
#6      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:519:18)
#7      _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:71:64)
#8      _rootRunUnary (dart:async/zone.dart:1132:38)
#9      _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#10     _FutureListener.handleValue (dart:async/future_impl.dart:137:18)
#11     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:678:45)
#12     Future._propagateToListeners (dart:async/future_impl.dart:707:32)
#13     Future._completeWithValue (dart:async/future_impl.dart:522:5)
#14     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:30:15)
#15     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:288:13)
#16     RunCommand.usageValues (package:flutter_tools/src/commands/run.dart)
#17     _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:71:64)
#18     _rootRunUnary (dart:async/zone.dart:1132:38)
#19     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#20     _FutureListener.handleValue (dart:async/future_impl.dart:137:18)
#21     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:678:45)
#22     Future._propagateToListeners (dart:async/future_impl.dart:707:32)
#23     Future._completeWithValue (dart:async/future_impl.dart:522:5)
#24     Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:552:7)
#25     _rootRun (dart:async/zone.dart:1124:13)
#26     _CustomZone.run (dart:async/zone.dart:1021:19)
#27     _CustomZone.runGuarded (dart:async/zone.dart:923:7)
#28     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:963:23)
#29     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#30     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#31     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:116:13)
#32     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:173:5)
```
I found that Generated.props file located in D:\flutter-desktop-embedding-master\example\windows\flutter\ephemeral. Maybe problem with imports of project solution.

**Comment by escamoteur** [comment]
As even MS stops support for Windows 7 now I would not expect that Flutter Desktop which is just in alpha will support it. @csells am I right here?

**Comment by csells** [comment]
That's correct. Flutter for desktop apps may accidently work on Windows 7
but we don't currently have plans to support it explicitly.

**Comment by godot0413301** [comment]
There is a lot of computers runs windows7 in china

**Comment by marinat** [comment]
Same situation in Russia, it is sad that you will not support windows 7.

**Comment by escamoteur** [comment]
@csells Both are good points, but I think first Windows Desktop should reach Release state before we look at this again.

**Comment by stuartmorgan** [comment]
This issue has nothing to do with Windows 7.

> The imported project "D:\flutter-desktop-embedding-master\example\windows\flutter\Generated.props" was not found.

Your version of flutter-desktop-embedding is too old. Please see [the first paragraph here](https://github.com/google/flutter-desktop-embedding#setting-up).
