### ISSUE TITLE
error with url launcher for send email

### ISSUE THREAD

**Issue by nitneuq33** [flutter/flutter#40756]
Hello, I have problem only on iOS simulator to send email with url launcher.

It's works with android but not for iOS simulator.

I tried this simple example 

```

  String email="contact@ouiquit.com";
  _launchEmail() async {
    if (await canLaunch("mailto:$email")) {
      await launch("mailto:$email");
    } else {
      throw 'Could not launch';
    }
  }

  @override
  Widget build(BuildContext context) {


    return MaterialApp(
      theme: ThemeData(primaryColor: Colors.red),
      home: Scaffold(
        appBar: AppBar(
          title: Text('test mail'),
          actions: <Widget>[
            IconButton(
              onPressed: _launchEmail,
              icon: Icon(Icons.send),
            )
          ],
        ),
      ),
    );
  }
```

I have this issue
```

[VERBOSE-2:ui_dart_state.cc(148)] Unhandled Exception: MissingPluginException(No implementation found for method canLaunch on channel plugins.flutter.io/url_launcher)
#0      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:314:7)
<asynchronous suspension>
#1      canLaunch (package:url_launcher/url_launcher.dart:112:25)
<asynchronous suspension>
#2      _MyAppState._launchEmail (package:testmail/main.dart:20:15)
<asynchronous suspension>
#3      _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:654:14)
#4      _InkResponseState.build.<anonymous closure> (package:flutter/src/material/ink_well.dart:729:32)
#5      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:182:24)
#6      TapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:365:11)
#7      TapGestureRecognizer.handlePrimaryPointer (package:flutter/src/gestures/tap.dart:275:7)
#8      PrimaryPointerGestureRecognizer.handleEvent (package:flutter/src/<…>
```

**Comment by escamoteur** [comment]
There is no Email App installed on the iOS Simulator you only can test this on a real device. Could you try on a real iPhone?

Although I have to admit the exception seems to signal another problem.

**Comment by nitneuq33** [comment]
Thank you. no device to test, but this answer save my times :)

Le mer. 18 sept. 2019 à 18:30, escamoteur <notifications@github.com> a
écrit :

**Comment by TahaTesser** [comment]
Hi @nitneuq33 
Are you still experiencing this issue?
Thank you

**Comment by nitneuq33** [comment]
It’s ok 👌

Le mer. 26 févr. 2020 à 11:14, Taha Tesser <notifications@github.com> a
écrit :

**Comment by TahaTesser** [comment]
Hey @nitneuq33 
given your last message I feel safe to close this issue,
if you disagree please write in the comments and I will reopen it. 
Thank you
