### ISSUE TITLE
[web] `flutter build web --debug` fails when a plugin is included in the project

### ISSUE THREAD

**Issue by jkurtw** [flutter/flutter#40772]
I have a Flutter project that includes a web implementation of url_launcher. `flutter build web` succeeds, but `flutter build web --debug` fails with the following error.

```[  +79 ms] FileSystemException: Cannot copy file to 'build/web/main.dart.js.map', path =

'/Users/jkurtw/development/web_plugins/url_launcher_test/.dart_tool/build/flutter_web/url_launcher_test/lib/main_web_entrypoint.dart.js.map
           ' (OS Error: No such file or directory, errno = 2)
[   +9 ms] Compiling lib/main.dart for the Web... (completed in 7.1s)
[   +2 ms] "flutter web" took 7,479ms.
Failed to compile lib/main.dart for the Web.

#0      throwToolExit (package:flutter_tools/src/base/common.dart:28:3)
#1      buildWeb (package:flutter_tools/src/web/compile.dart:61:5)
<asynchronous suspension>
#2      BuildWebCommand.runCommand (package:flutter_tools/src/commands/build_web.dart:47:11)
<asynchronous suspension>
#3      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:490:18)
#4      _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:71:64)
#5      _rootRunUnary (dart:async/zone.dart:1132:38)
#6      _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#7      _FutureListener.handleValue (dart:async/future_impl.dart:137:18)
#8      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:678:45)
#9      Future._propagateToListeners (dart:async/future_impl.dart:707:32)
#10     Future._completeWithValue (dart:async/future_impl.dart:522:5)
#11     Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:552:7)
#12     _rootRun (dart:async/zone.dart:1124:13)
#13     _CustomZone.run (dart:async/zone.dart:1021:19)
#14     _CustomZone.runGuarded (dart:async/zone.dart:923:7)
#15     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:963:23)
#16     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#17     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#18     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:116:13)
#19     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:173:5)```

**Comment by jkurtw** [comment]
@hterkelsen

**Comment by jonahwilliams** [comment]
I misunderstood your issue. You cannot "build" a debug app. We should handle that better here with a clean error message

**Comment by johnpryan** [comment]
The `flutter build web --help` command makes it seem like `debug`, `profile`, and `release` are supported :

```
flutter build web --help
build a web application bundle.

Usage: flutter build web [arguments]
-h, --help             Print this usage information.
-t, --target=<path>    The main entry-point file of the application, as run on the device.
                       If the --target option is omitted, but a file name is provided on the command line, then that is used instead.
                       (defaults to "lib/main.dart")

    --[no-]pub         Whether to run "flutter pub get" before executing this command.
                       (defaults to on)

    --debug            Build a debug version of your app.
    --profile          Build a version of your app specialized for performance profiling.
    --release          Build a release version of your app (default mode).
```

For what it's worth, this seems to be working for apps that don't use plugins.

**Comment by jkurtw** [comment]
Docs too. https://flutter.dev/docs/testing/build-modes says:

Debug mode for a web app means that:
- The build is not minified and tree shaking has not been performed.
- The app is compiled with the dartdevc compiler for easier debugging.

It goes on to talk about `flutter run` and the default being a debug build, but we probably need to make it clear somewhere that `flutter build web --debug` is not a thing.

**Comment by jonahwilliams** [comment]
Yeah, I'll adjust the visible flags and make sure that throws a clear error message too
