### ISSUE TITLE
type 'WhereIterable<String>' is not a subtype of type 'List<String>'

### ISSUE THREAD

**Issue by DannyHinshaw** [flutter/flutter#40797]
## Steps to Reproduce

1. Take a `List<String>`, call `where` method on it to filter and then return a List<String>`
2. 
```
List<String> removeBlacklistItemReducer(List<String> state, RemoveBlacklistItemAction action) {
  final Iterable<String> newState = state.where((item) => item != action.item);
  return List<String>.from(newState);
}
```

## Logs

```
════════ Exception caught by gesture ═══════════════════════════════════════════════════════════════
The following assertion was thrown while handling a gesture:
type 'WhereIterable<String>' is not a subtype of type 'List<String>'


Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=BUG.md

When the exception was thrown, this was the stack: 
#0      editBlacklistItemReducer (package:flutter_hybrid_alert/src/store/reducers/blacklist_reducer.dart:13:16)
#1      TypedReducer.call (package:redux/src/utils.dart:103:14)
#2      combineReducers.<anonymous closure> (package:redux/src/utils.dart:248:22)
#3      appReducer (package:flutter_hybrid_alert/src/store/reducers/root_reducer.dart:14:32)
#4      Store._createReduceAndNotify.<anonymous closure> (package:redux/src/store.dart:218:21)
...
Handler: "onTap"
Recognizer: TapGestureRecognizer#dccdd
  debugOwner: GestureDetector
  state: possible
  won arena
  finalPosition: Offset(301.7, 291.8)
  finalLocalPosition: Offset(28.0, 22.2)
  sent tap down
════════════════════════════════════════════════════════════════════════════════════════════════════

```

```
Analyzing flutter_hybrid_alert...
No issues found! (ran in 4.4s)
```

```
[✓] Flutter (Channel stable, v1.9.1+hotfix.2, on Mac OS X 10.14.6 18G95, locale en-US)
    • Flutter version 1.9.1+hotfix.2 at /Users/danny/fvm/stable
    • Framework revision 2d2a1ffec9 (12 days ago), 2019-09-06 18:39:49 -0700
    • Engine revision b863200c37
    • Dart version 2.5.0


[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/danny/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Users/danny/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/191.5791312/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[!] Xcode - develop for iOS and macOS (Xcode 10.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.3, Build version 10G8
    ! CocoaPods out of date (1.6.0 is recommended).
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin code that responds to your plugin usage on the Dart
        side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To upgrade:
        sudo gem install cocoapods
        pod setup

[✓] Android Studio (version 3.5)
    • Android Studio at /Users/danny/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/191.5791312/Android
      Studio.app/Contents
    • Flutter plugin version 39.0.3
    • Dart plugin version 191.8423
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[!] IntelliJ IDEA Ultimate Edition (version 2019.2.2)
    • IntelliJ at /Users/danny/Applications/JetBrains Toolbox/IntelliJ IDEA Ultimate.app
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.dev/intellij-setup/#installing-the-plugins

[✓] Connected device (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 9 (API 28) (emulator)

! Doctor found issues in 2 categories.
```

**Comment by DannyHinshaw** [comment]
Was looking at the wrong function... PEBKAC. Nothing to see here....
