### ISSUE TITLE
滑动过程中，使用状态管理更新 可滑动页面，physics 从null变为NeverScrollableScrollPhysics (During the sliding process, use state management to update the slidable page, physics changes from null to NeverScrollableScrollPhysics)

### ISSUE THREAD

**Issue by ksiventy** [flutter/flutter#40835]
## Steps to Reproduce

1. ...   provide change status  ,scrollable
2. ...   physics  from null to NeverScrollableScrollPhysics
3. ...  scrolling

## Logs

```
══╡ EXCEPTION CAUGHT BY GESTURE ╞═══════════════════════════════════════════════════════════════════
I/flutter (20896): The following assertion was thrown while handling a gesture:
I/flutter (20896): 'package:flutter/src/widgets/scrollable.dart': Failed assertion: line 478 pos 12: '_drag == null':
I/flutter (20896): is not true.
I/flutter (20896): 
I/flutter (20896): Either the assertion indicates an error in the framework itself, or we should provide substantially
I/flutter (20896): more information in this error message to help you determine and fix the underlying cause.
I/flutter (20896): In either case, please report this assertion by filing a bug on GitHub:
I/flutter (20896):   https://github.com/flutter/flutter/issues/new?template=BUG.md
I/flutter (20896): 
I/flutter (20896): When the exception was thrown, this was the stack:
I/flutter (20896): #2      ScrollableState._handleDragDown (package:flutter/src/widgets/scrollable.dart:478:12)
I/flutter (20896): #3      DragGestureRecognizer.addAllowedPointer.<anonymous closure> (package:flutter/src/gestures/monodrag.dart:162:46)
I/flutter (20896): #4      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:166:24)
I/flutter (20896): #5      DragGestureRecognizer.addAllowedPointer (package:flutter/src/gestures/monodrag.dart:162:9)
I/flutter (20896): #6      GestureRecognizer.addPointer (package:flutter/src/gestures/recognizer.dart:96:7)
I/flutter (20896): #7      RawGestureDetectorState._handlePointerDown (package:flutter/src/widgets/gesture_detector.dart:779:18)
I/flutter (20896): #8      RenderPointerListener.handleEvent (package:flutter/src/rendering/proxy_box.dart:2622:14)
I/flutter (20896): #9      _WidgetsFlutterBinding&BindingBase&GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:199:22)
I/flutter (20896): #10     _WidgetsFlutterBinding&BindingBase&GestureBinding._handlePointerEvent (package:flutter/src/gestures/binding.dart:156:7)
I/flutter (20896): #11     _WidgetsFlutterBinding&BindingBase&GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:102:7)
I/flutter (20896): #12     _WidgetsFlutterBinding&BindingBase&GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:86:7)
I/flutter (20896): #16     _invoke1 (dart:ui/hooks.dart:233:10)
I/flutter (20896): #17     _dispatchPointerDataPacket (dart:ui/hooks.dart:154:5)
I/flutter (20896): (elided 5 frames from class _AssertionError and package dart:async)
I/flutter (20896): 
I/flutter (20896): Handler: onDown
I/flutter (20896): Recognizer:
I/flutter (20896):   VerticalDragGestureRecognizer#0195c(start behavior: start)
I/flutter (20896): ════════════════════════════════════════════════════════════════════════════════════════════════════
I/flutter (20896): Another exception was thrown: 'package:flutter/src/widgets/scrollable.dart': Failed assertion: line 487 pos 12: '_drag == null': is not true.
```

**Comment by BondarenkoStas** [comment]
@ksiventy Please provide your ```flutter doctor -v``` output. Can you also provide a small self-contained app that demonstrates the problem? You can include small examples [inline if they're enclosed by backticks](https://help.github.com/en/articles/creating-and-highlighting-code-blocks), or just provide a public link to a github "gist" - https://gist.github.com/. From the error message it seems that most probably the issue is caused by implementation.

**Comment by escamoteur** [comment]
May I add please describe your Problem more clearly currently we don't understand what you are doing and what the problem is
