### ISSUE TITLE
D8: Program type already present: io.flutter.BuildConfig

### ISSUE THREAD

**Issue by smrucv** [flutter/flutter#40830]
I'm using Android Studio and upgraded Flutter as suggested. Since that I cannot execute my app because Graddle exit with error "D8: Program type already present: io.flutter.BuildConfig"

**** Returned Message: (doesn't give any clue of what can be happening)
```
com.android.builder.dexing.DexArchiveMergerException: Error while merging dex archives: 
Learn how to resolve the issue at https://developer.android.com/studio/build/dependencies#duplicate_classes.
Program type already present: io.flutter.BuildConfig
	at com.android.builder.dexing.D8DexArchiveMerger.getExceptionToRethrow(D8DexArchiveMerger.java:131)
	at com.android.builder.dexing.D8DexArchiveMerger.mergeDexArchives(D8DexArchiveMerger.java:118)
	at com.android.build.gradle.internal.transforms.DexMergerTransformCallable.call(DexMergerTransformCallable.java:102)
	at com.android.build.gradle.internal.tasks.DexMergingTaskRunnable.run(DexMergingTask.kt:444)
	at com.android.build.gradle.internal.tasks.Workers$ActionFacade.run(Workers.kt:335)
	at org.gradle.workers.internal.DefaultWorkerServer.execute(DefaultWorkerServer.java:39)
	at org.gradle.workers.internal.NoIsolationWorkerFactory$1$1.execute(NoIsolationWorkerFactory.java:61)
	at org.gradle.workers.internal.AbstractWorker$1.call(AbstractWorker.java:44)
	at org.gradle.workers.internal.AbstractWorker$1.call(AbstractWorker.java:41)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor$CallableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:416)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor$CallableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:406)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor$1.execute(DefaultBuildOperationExecutor.java:165)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:250)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:158)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.call(DefaultBuildOperationExecutor.java:102)
	at org.gradle.internal.operations.DelegatingBuildOperationExecutor.call(DelegatingBuildOperationExecutor.java:36)
	at org.gradle.workers.internal.AbstractWorker.executeWrappedInBuildOperation(AbstractWorker.java:41)
	at org.gradle.workers.internal.NoIsolationWorkerFactory$1.execute(NoIsolationWorkerFactory.java:55)
	at org.gradle.workers.internal.DefaultWorkerExecutor$1.call(DefaultWorkerExecutor.java:105)
	at org.gradle.workers.internal.DefaultWorkerExecutor$1.call(DefaultWorkerExecutor.java:99)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at org.gradle.internal.work.DefaultConditionalExecutionQueue$ExecutionRunner.runExecution(DefaultConditionalExecutionQueue.java:215)
	at org.gradle.internal.work.DefaultConditionalExecutionQueue$ExecutionRunner.runBatch(DefaultConditionalExecutionQueue.java:164)
	at org.gradle.internal.work.DefaultConditionalExecutionQueue$ExecutionRunner.run(DefaultConditionalExecutionQueue.java:131)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
	at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:46)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)
	at java.lang.Thread.run(Thread.java:748)
Caused by: com.android.tools.r8.CompilationFailedException: Compilation failed to complete
	at com.android.tools.r8.utils.t.a(:55)
	at com.android.tools.r8.D8.run(:11)
	at com.android.builder.dexing.D8DexArchiveMerger.mergeDexArchives(D8DexArchiveMerger.java:116)
	... 30 more
Caused by: com.android.tools.r8.utils.AbortException: Error: Program type already present: io.flutter.BuildConfig
	at com.android.tools.r8.utils.Reporter.a(:21)
	at com.android.tools.r8.utils.Reporter.a(:7)
	at com.android.tools.r8.utils.t.a(:36)
	... 32 more


FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:mergeDexDebug'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.Workers$ActionFacade
   > com.android.builder.dexing.DexArchiveMergerException: Error while merging dex archives: 
     Learn how to resolve the issue at https://developer.android.com/studio/build/dependencies#duplicate_classes.
     Program type already present: io.flutter.BuildConfig

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1m 6s
Finished with error: Gradle task assembleDebug failed with exit code 1
```
**** Flutter Doctor:
```
/Users/dsalazar/FlutterSDK/flutter/bin/flutter doctor --verbose
[✓] Flutter (Channel master, v1.10.5-pre.22, on Mac OS X 10.13.6 17G7024, locale es-PA)
    • Flutter version 1.10.5-pre.22 at /Users/dsalazar/FlutterSDK/flutter
    • Framework revision ebd8e0b34b (42 minutes ago), 2019-09-19 03:38:41 -0400
    • Engine revision bf3af4d157
    • Dart version 2.6.0 (build 2.6.0-dev.1.0 ea969c358e)

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/dsalazar/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 28.0.3
    • ANDROID_HOME = /Users/dsalazar/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 9.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 9.3.1, Build version 9E501
    • CocoaPods version 1.6.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 39.0.3
    • Dart plugin version 191.8423
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] Connected device (3 available)
    • LG K530 • LGK53023932c17 • android-arm    • Android 7.0 (API 24)
    • Chrome  • chrome         • web-javascript • Google Chrome 76.0.3809.132
    • Server  • web            • web-javascript • Flutter Tools

• No issues found!
Process finished with exit code 0
```

I will appreciate if you can please give me an idea about what to check or change.

regards

**Comment by bubnenkoff** [comment]
Same issue after upgrade to latest master.

**Comment by smrucv** [comment]
> Same issue after upgrade to latest master.

What are your dependencies?

Mine are:

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  intl: ^0.15.8
  pdf: ^1.3.20
  bloc_pattern: ^1.3.0
  rxdart: ^0.20.0
  mailer: ^3.0.2
  path_provider: ^1.3.0
  font_awesome_flutter: ^8.2.0
  firebase_auth: ^0.14.0+4
  firebase_storage: ^3.0.6
  shared_preferences: ^0.4.3
  cloud_firestore: 0.12.9+1
  printing: ^2.1.2
  progress_indicators: ^0.1.2
  file_picker: ^1.4.0
  firebase_core: ^0.4.0
#  firebase_analytics: ^1.0.4  # add dependency for Google Analytics for Firebase

**Comment by bubnenkoff** [comment]
I got problem on building this project https://stackoverflow.com/questions/57996076/how-to-use-navigator-from-class-that-do-not-have-context

**Comment by edufolly** [comment]
@smrucv I received the same error, but after ```flutter clean``` and ```flutter packages get``` everything works great.

**Comment by sanekyy** [comment]
@edufolly the same error and the same solution. Thx.

**Comment by smrucv** [comment]
> @smrucv I received the same error, but after `flutter clean` and `flutter packages get` everything works great.

@edufolly Thank you!!! It worked perfectly.

**Comment by gaojuanjuan** [comment]
I used flutter clean but it didn't work out

**Comment by nb312** [comment]
> @smrucv I received the same error, but after `flutter clean` and `flutter packages get` everything works great.

Thanks, It works to me.

**Comment by smrucv** [comment]
did you do flutter packages get after that?

Dimas Salazar

"Los jóvenes venezolanos, ¿se dejarán abatir por las dificultades, o
tendrán el valor de ser cristianos de verdad y construir una sociedad
más justa, más fraterna, más acogedora y pacífica?"
Juan Pablo II (1985)

**Comment by searchy2** [comment]
For anyone wondering about the actual cause of this issue or want to solve the issue without doing a flutter clean/rebuild; the cause of the issue is that they now use R8 in Flutter.

Add the following line to your `.android/gradle.properties` file to fix the issue:
`android.enableR8=true`

**Comment by pratikbutani** [comment]
> @smrucv I received the same error, but after `flutter clean` and `flutter packages get` everything works great.

Love you man! <3 Thanks.

**Comment by ssdwho** [comment]
> @smrucv I received the same error, but after `flutter clean` and `flutter packages get` everything works great.

haha think simple and works 👍 thank you

**Comment by Muniru0** [comment]
@searchy2 adding your ``android.enableR8=true`` to ``.android/gradle.properties`` , and doing the flutter clean and the ``flutter packages get`` worked for me. But i don't know if enabling androidX also helped or not.

**Comment by takiuddin93** [comment]
> @smrucv I received the same error, but after `flutter clean` and `flutter packages get` everything works great.

Worked like a charm, thank you.

**Comment by abstractizm** [comment]
> @smrucv I received the same error, but after `flutter clean` and `flutter packages get` everything works great.

Awesome. Worked.

**Comment by phanirithvij** [comment]
@searchy2 flutter is adding `android.enableR8=true` by itself no need to add it manually. `flutter clean` worked for me

**Comment by MinceMan** [comment]
Adding `android.enableR8=true` is needed if you're using FlutterFragment or FlutterActivity in your existing app.

**Comment by phanirithvij** [comment]
If it's a plugin don't forget to clean under the `example` folder.
`flutter clean` and `flutter pub get` in both root and the `example` directory are required.

**Comment by radomir9720** [comment]
> @smrucv I received the same error, but after `flutter clean` and `flutter packages get` everything works great.

Thanks!

**Comment by pvthiendeveloper** [comment]
> @smrucv I received the same error, but after `flutter clean` and `flutter packages get` everything works great.

Thanks!

**Comment by mby-che** [comment]
@edufolly it worked for me, thanks a lot

**Comment by Condelab** [comment]
@edufolly it worked for me, thanks a bunch

**Comment by Morkos** [comment]
@edufolly woot! worked for me too.

**Comment by deatherving** [comment]
@edufolly It works. Thanks a lot.

**Comment by ifredom** [comment]
It would be great if flutter's problems were solved so well

**Comment by phoom-panichpat** [comment]
@edufolly Thanks !

**Comment by airrinascimento** [comment]
> @smrucv I received the same error, but after `flutter clean` and `flutter packages get` everything works great.

I've tried before, but it's no use.

I use this project, and it's not working.
https://github.com/mitesh77/Best-Flutter-UI-Templates/tree/master/best_flutter_ui_templates

**Comment by Mariobahaa** [comment]
> @smrucv I received the same error, but after `flutter clean` and `flutter packages get` everything works great.

Thank you! it works

**Comment by Prospyl** [comment]
> @smrucv I received the same error, but after `flutter clean` and `flutter packages get` everything works great.

it worked..Thanks alot for the help. Now i can move forward wit my code

**Comment by ismail1997** [comment]
I got the same error but after `flutter clean` and `flutter packages get` the issue is gone
thanks  a lot

**Comment by sachinmishra-gep** [comment]
I got the same error. This type of application is not as generic as we do except. IN my application development I was using the below mentioned dependencies  

```
  youtube_player_flutter: ^6.1.0+7
  webview_flutter: ^0.3.20+2
```

since  `youtube_player_flutter` internally it makes use of ` webview_flutter ` as one of the dependencies. I removed the dependencies   `webview_flutter` and it worked.

**Comment by msoham123** [comment]
> I got the same error. This type of application is not as generic as we do except. IN my application development I was using the below mentioned dependencies
> 
> ```
>   youtube_player_flutter: ^6.1.0+7
>   webview_flutter: ^0.3.20+2
> ```
> 
> since `youtube_player_flutter` internally it makes use of `webview_flutter` as one of the dependencies. I removed the dependencies `webview_flutter` and it worked.

This worked for me! I was using the youtube player and webview dependencies when you only need one!

**Comment by dothanhtin** [comment]
> @smrucv I received the same error, but after `flutter clean` and `flutter packages get` everything works great.

Thanks, i solved my problem

**Comment by hktom** [comment]
I got this problem cause  youtube_player_flutter and flutter_html were using the same dependency flutter_webview. 

I used this and work like a charm
https://github.com/sarbagyastha/youtube_player_flutter/issues/215

**Comment by thatgirlismylove** [comment]
> @smrucv I received the same error, but after `flutter clean` and `flutter packages get` everything works great.

thanks,it works!

**Comment by ikkyu0319** [comment]
thanks,it works!
