### ISSUE TITLE
ChromeDebugException: Unexpected error from chrome devtools

### ISSUE THREAD

**Issue by asmallkite** [flutter/flutter#40848]
[flutter_02.log](https://github.com/flutter/flutter/files/3631112/flutter_02.log)
content:

## command
```
flutter run -d chrome
```
## exception
```
ChromeDebugException: Unexpected error from chrome devtools:
text: Uncaught
exception:
  description: ReferenceError: require is not defined
    at <anonymous>:1:1
  type: object
  value: null
attempted JS eval: `require('dart_sdk').developer._extensions.keys.toList();`
```

```
#0      handleErrorIfPresent (package:dwds/src/services/chrome_proxy_service.dart:569:5)
#1      AppInspector._getExtensionRpcs (package:dwds/src/debugging/inspector.dart:505:5)
<asynchronous suspension>
#2      AppInspector._initialize (package:dwds/src/debugging/inspector.dart:78:40)
<asynchronous suspension>
#3      AppInspector.initialize (package:dwds/src/debugging/inspector.dart:108:21)
#4      _AsyncAwaitCompleter.start (dart:async-patch/async_patch.dart:43:6)
#5      AppInspector.initialize (package:dwds/src/debugging/inspector.dart:84:41)
#6      ChromeProxyService.createIsolate (package:dwds/src/services/chrome_proxy_service.dart:112:37)
#7      _AsyncAwaitCompleter.start (dart:async-patch/async_patch.dart:43:6)
#8      ChromeProxyService.createIsolate (package:dwds/src/services/chrome_proxy_service.dart:106:29)
#9      ChromeProxyService.create (package:dwds/src/services/chrome_proxy_service.dart:86:19)
#10     _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:71:64)
#11     _rootRunUnary (dart:async/zone.dart:1132:38)
#12     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#13     _FutureListener.handleValue (dart:async/future_impl.dart:137:18)
#14     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:678:45)
#15     Future._propagateToListeners (dart:async/future_impl.dart:707:32)
#16     Future._completeWithValue (dart:async/future_impl.dart:522:5)
#17     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:30:15)
#18     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:288:13)
#19     ChromeProxyService._initialize (package:dwds/src/services/chrome_proxy_service.dart)
#20     _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:71:64)
#21     _rootRunUnary (dart:async/zone.dart:1132:38)
#22     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#23     _FutureListener.handleValue (dart:async/future_impl.dart:137:18)
#24     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:678:45)
#25     Future._propagateToListeners (dart:async/future_impl.dart:707:32)
#26     Future._completeWithValue (dart:async/future_impl.dart:522:5)
#27     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:30:15)
#28     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:288:13)
#29     Debugger.create (package:dwds/src/debugging/debugger.dart)
#30     _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:71:64)
#31     _rootRunUnary (dart:async/zone.dart:1132:38)
#32     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#33     _FutureListener.handleValue (dart:async/future_impl.dart:137:18)
#34     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:678:45)
#35     Future._propagateToListeners (dart:async/future_impl.dart:707:32)
#36     Future._completeWithValue (dart:async/future_impl.dart:522:5)
#37     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:30:15)
#38     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:288:13)
#39     Debugger._initialize (package:dwds/src/debugging/debugger.dart)
#40     _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:71:64)
#41     _rootRunUnary (dart:async/zone.dart:1132:38)
#42     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#43     _FutureListener.handleValue (dart:async/future_impl.dart:137:18)
#44     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:678:45)
#45     Future._propagateToListeners (dart:async/future_impl.dart:707:32)
#46     Future._completeWithValue (dart:async/future_impl.dart:522:5)
#47     Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:552:7)
#48     _rootRun (dart:async/zone.dart:1124:13)
#49     _CustomZone.run (dart:async/zone.dart:1021:19)
#50     _CustomZone.runGuarded (dart:async/zone.dart:923:7)
#51     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:963:23)
#52     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#53     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#54     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:116:13)
#55     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:173:5)
```

## flutter doctor

```
[32m[✓][39m Flutter (Channel master, v1.10.5-pre.23, on Mac OS X 10.13.6 17G8030, locale zh-Hans-CN)
    [32m•[39m Flutter version 1.10.5-pre.23 at /Users/evanzhengli/Documents/flu/flutter
    [32m•[39m Framework revision e026bd3d33 (44 分钟前), 2019-09-19 07:29:41 -0400
    [32m•[39m Engine revision 1cada0a6dc
    [32m•[39m Dart version 2.6.0 (build 2.6.0-dev.0.0 ea969c358e)

[33m[!][39m Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    [32m•[39m Android SDK at /Users/evanzhengli/Library/Android/sdk
    [32m•[39m Android NDK location not configured (optional; useful for native profiling support)
    [32m•[39m Platform android-28, build-tools 28.0.3
    [32m•[39m ANDROID_HOME = /Users/evanzhengli/Library/Android/sdk
    [32m•[39m Java binary at: /Library/Java/JavaVirtualMachines/jdk-12.0.2.jdk/Contents/Home/bin/java
    [32m•[39m Java version Java(TM) SE Runtime Environment (build 12.0.2+10)
    [31m✗[39m Android license status unknown.
      Try re-installing or updating your Android SDK Manager.
      See https://developer.android.com/studio/#downloads or visit https://flutter.dev/setup/#android-setup for detailed instructions.

[31m[✗][39m Xcode - develop for iOS and macOS
    [31m✗[39m Xcode installation is incomplete; a full installation is necessary for iOS development.
      Download at: https://developer.apple.com/xcode/download/
      Or install Xcode via the App Store.
      Once installed, run:
        sudo xcode-select --switch /Applications/Xcode.app/Contents/Developer
    [31m✗[39m CocoaPods not installed.
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To install:
        sudo gem install cocoapods
        pod setup

[32m[✓][39m Chrome - develop for the web
    [32m•[39m Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[33m[!][39m Android Studio (not installed)
    [32m•[39m Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/setup/#android-setup for detailed instructions).

[32m[✓][39m VS Code (version 1.38.1)
    [32m•[39m VS Code at /Applications/Visual Studio Code.app/Contents
    [32m•[39m Flutter extension version 3.4.1

[32m[✓][39m Proxy Configuration
    [32m•[39m HTTP_PROXY is set
    [32m•[39m NO_PROXY is .oa.com,localhost,127.0.0.1
    [32m•[39m NO_PROXY contains 127.0.0.1
    [32m•[39m NO_PROXY contains localhost

[32m[✓][39m Connected device (2 available)
    [32m•[39m Chrome • chrome • web-javascript • Google Chrome 76.0.3809.132
    [32m•[39m Server • web    • web-javascript • Flutter Tools

[33m![39m Doctor found issues in 3 categories.
```

**Comment by escamoteur** [comment]
Does this happen with any App that you try?
If not, can you share this apps code?

**Comment by jonahwilliams** [comment]
I think this should be fixed with https://github.com/flutter/flutter/pull/40766

**Comment by UndCover** [comment]
Windows7 x64 

## command

flutter run -d chrome

## exception

ChromeDebugException: Unexpected error from chrome devtools:
text: Uncaught
exception:
  description: ReferenceError: require is not defined
    at <anonymous>:1:1
  type: object
  value: null
attempted JS eval: `require('dart_sdk').dart.getLibraries();`


```
#0      handleErrorIfPresent (package:dwds/src/services/chrome_proxy_service.dart:569:5)
#1      AppInspector._getLibraryRefs (package:dwds/src/debugging/inspector.dart:489:5)
<asynchronous suspension>
#2      AppInspector._initialize (package:dwds/src/debugging/inspector.dart:72:36)
<asynchronous suspension>
#3      AppInspector.initialize (package:dwds/src/debugging/inspector.dart:108:21)
#4      _AsyncAwaitCompleter.start (dart:async-patch/async_patch.dart:43:6)
#5      AppInspector.initialize (package:dwds/src/debugging/inspector.dart:84:41)
#6      ChromeProxyService.createIsolate (package:dwds/src/services/chrome_proxy_service.dart:112:37)
#7      _AsyncAwaitCompleter.start (dart:async-patch/async_patch.dart:43:6)
#8      ChromeProxyService.createIsolate (package:dwds/src/services/chrome_proxy_service.dart:106:29)
#9      ChromeProxyService.create (package:dwds/src/services/chrome_proxy_service.dart:86:19)
#10     _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:71:64)
#11     _rootRunUnary (dart:async/zone.dart:1132:38)
#12     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#13     _FutureListener.handleValue (dart:async/future_impl.dart:137:18)
#14     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:678:45)
#15     Future._propagateToListeners (dart:async/future_impl.dart:707:32)
#16     Future._completeWithValue (dart:async/future_impl.dart:522:5)
#17     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:30:15)
#18     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:288:13)
#19     ChromeProxyService._initialize (package:dwds/src/services/chrome_proxy_service.dart)
#20     _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:71:64)
#21     _rootRunUnary (dart:async/zone.dart:1132:38)
#22     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#23     _FutureListener.handleValue (dart:async/future_impl.dart:137:18)
#24     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:678:45)
#25     Future._propagateToListeners (dart:async/future_impl.dart:707:32)
#26     Future._completeWithValue (dart:async/future_impl.dart:522:5)
#27     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:30:15)
#28     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:288:13)
#29     Debugger.create (package:dwds/src/debugging/debugger.dart)
#30     _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:71:64)
#31     _rootRunUnary (dart:async/zone.dart:1132:38)
#32     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#33     _FutureListener.handleValue (dart:async/future_impl.dart:137:18)
#34     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:678:45)
#35     Future._propagateToListeners (dart:async/future_impl.dart:707:32)
#36     Future._completeWithValue (dart:async/future_impl.dart:522:5)
#37     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:30:15)
#38     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:288:13)
#39     Debugger._initialize (package:dwds/src/debugging/debugger.dart)
#40     _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:71:64)
#41     _rootRunUnary (dart:async/zone.dart:1132:38)
#42     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#43     _FutureListener.handleValue (dart:async/future_impl.dart:137:18)
#44     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:678:45)
#45     Future._propagateToListeners (dart:async/future_impl.dart:707:32)
#46     Future._completeWithValue (dart:async/future_impl.dart:522:5)
#47     Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:552:7)
#48     _rootRun (dart:async/zone.dart:1124:13)
#49     _CustomZone.run (dart:async/zone.dart:1021:19)
#50     _CustomZone.runGuarded (dart:async/zone.dart:923:7)
#51     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:963:23)
#52     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#53     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#54     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:116:13)
#55     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:173:5)
```

## flutter doctor

```
[✓] Flutter (Channel master, v1.10.6-pre.29, on Microsoft Windows [Version
    6.1.7601], locale zh-CN)
    • Flutter version 1.10.6-pre.29 at D:\flutter
    • Framework revision 919cc97f6a (2 days ago), 2019-09-20 14:57:05 -0700
    • Engine revision 99092a0436
    • Dart version 2.6.0 (build 2.6.0-dev.1.0 7c1821c4aa)

[!] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at C:\Users\undcover\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling
      support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: D:\AndroidStudio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)
    ✗ Android licenses not accepted.  To resolve this, run: flutter doctor
      --android-licenses

[✓] Chrome - develop for the web
    • Chrome at
      C:\Users\undcover\AppData\Local\Google\Chrome\Application\chrome.exe

[✓] Android Studio (version 3.2)
    • Android Studio at D:\AndroidStudio
    • Flutter plugin version 31.3.1
    • Dart plugin version 181.5656
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)

[!] IntelliJ IDEA Ultimate Edition (version 2018.2)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA 2018.2.5
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.dev/intellij-setup/#installing-the-plugins

[✓] Connected device (2 available)
    • Chrome • chrome • web-javascript • Google Chrome 73.0.3683.75
    • Server • web    • web-javascript • Flutter Tools

! Doctor found issues in 2 categories.
```

**Comment by escamoteur** [comment]
@jonahwilliams Looks as if its not fixed in the current master. Is the PR not yet published?

**Comment by iapicca** [comment]
Hi @asmallkite 
this [pr](https://github.com/flutter/flutter/pull/40766) should have solved the issue;
if  you are still experiencing this issue with the latest version of Flutter?
If the issue persist please provide your updated 
`flutter doctor -v` and `flutter run --verbose`
together with a minimal code sample to reproduce the problem
thank you

**Comment by iapicca** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact descriptions what happens, logs and the output of 'flutter doctor -v'  please.
All system setups can be slightly different so its always better to open new issues and reference related issues.
