### ISSUE TITLE
Android base with Flutter works on emulator x86 debug but not on release

### ISSUE THREAD

**Issue by oth-libs** [flutter/flutter#40853]
## Steps to Reproduce
Nothing specific, it just never works on my emulator on release mode

## Logs

```
    --------- beginning of crash
2019-09-19 15:54:29.126 10508-10508/app.prosperity.app E/AndroidRuntime: FATAL EXCEPTION: main
    Process: app.prosperity.app, PID: 10508
    java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/app.prosperity.app-iU2LSC2Jh5HUhthio7JeXA==/base.apk"],nativeLibraryDirectories=[/data/app/app.prosperity.app-iU2LSC2Jh5HUhthio7JeXA==/lib/x86, /data/app/app.prosperity.app-iU2LSC2Jh5HUhthio7JeXA==/base.apk!/lib/x86, /system/lib]]] couldn't find "libflutter.so"
        at java.lang.Runtime.loadLibrary0(Runtime.java:1012)
        at java.lang.System.loadLibrary(System.java:1669)
        at io.flutter.view.FlutterMain.startInitialization(FlutterMain.java:122)
        at io.flutter.view.FlutterMain.startInitialization(FlutterMain.java:99)
        at app.prosperity.app.lifecycle.LifecycleAwareFlutterActivity.onCreate(LifecycleAwareFlutterActivity.kt:15)
        at app.prosperity.app.login.ui.LoginActivity.onCreate(LoginActivity.kt:26)
        at android.app.Activity.performCreate(Activity.java:7136)
        at android.app.Activity.performCreate(Activity.java:7127)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1271)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2893)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3048)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1808)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6669)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
```

```
[✓] Flutter (Channel master, v1.8.1-pre.23, on Mac OS X 10.14.3 18D42, locale en-GB)
    • Flutter version 1.8.1-pre.23 at /Users/othman/Documents/flutter
    • Framework revision 3bf91b5436 (3 months ago), 2019-07-05 12:59:32 -0700
    • Engine revision 3c51a7bfff
    • Dart version 2.5.0 (build 2.5.0-dev.0.0 b5aeaa6796)

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/othman/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
    • All Android licenses accepted.

[✗] Xcode - develop for iOS and macOS
    ✗ Xcode installation is incomplete; a full installation is necessary for iOS development.
      Download at: https://developer.apple.com/xcode/download/
      Or install Xcode via the App Store.
      Once installed, run:
        sudo xcode-select --switch /Applications/Xcode.app/Contents/Developer
    ✗ CocoaPods not installed.
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To install:
        brew install cocoapods
        pod setup

[✗] iOS tools - develop for iOS devices
    ✗ libimobiledevice and ideviceinstaller are not installed. To install with Brew, run:
        brew update
        brew install --HEAD usbmuxd
        brew link usbmuxd
        brew install --HEAD libimobiledevice
        brew install ideviceinstaller
    ✗ ios-deploy not installed. To install:
        brew install ios-deploy

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 3.4)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 36.0.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

[✓] Connected device (4 available)
    • Nexus 5                   • 072314e200620ac4 • android-arm    • Android 6.0.1 (API 23)
    • Android SDK built for x86 • emulator-5554    • android-x86    • Android 9 (API 28) (emulator)
    • macOS                     • macOS            • darwin-x64     • Mac OS X 10.14.3 18D42
    • Chrome                    • chrome           • web-javascript • Google Chrome 76.0.3809.132 


! Doctor found issues in 2 categories.
```

**Comment by jonahwilliams** [comment]
Release x86 builds are not supported, nor are emulator release builds supported

**Comment by escamoteur** [comment]
@jonahwilliams Perhaps we should make this clearer in the error message?

**Comment by jonahwilliams** [comment]
This information is surfaced when trying to `flutter run`. It looks as if this APK was built and installed manually, so there is not much we can do. (If that wasn't the case, that is a separate issue)

**Comment by escamoteur** [comment]
Yeah I was actually wondering myself because flutter won't even start building a release if you target the emulator. 
@oth-libs Did you install the apk manually on the emulator? Just to clarify this

**Comment by oth-libs** [comment]
@esarbanis @jonahwilliams I have a base android project that is using an external flutter project, so I run the app from android studio on the android project but I don't really get any message other than the UnsatisfiedLinkError
