### ISSUE TITLE
Android crashes after choosing files

### ISSUE THREAD

**Issue by zylz10** [flutter/flutter#40938]
## Steps to Reproduce

1. Android crashes after choosing files

## Logs

```
 Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'int android.graphics.**Bitmap.getWidth()'** on a null object reference
        at io.flutter.plugins.imagepicker.ImageResizer.resizedImage(ImageResizer.java:53)
        at io.flutter.plugins.imagepicker.ImageResizer.resizeImageIfNeeded(ImageResizer.java:40)
        at io.flutter.plugins.imagepicker.ImagePickerDelegate.handleImageResult(ImagePickerDelegate.java:530)
        at io.flutter.plugins.imagepicker.ImagePickerDelegate.handleChooseImageResult(ImagePickerDelegate.java:463)
        at io.flutter.plugins.imagepicker.ImagePickerDelegate.onActivityResult(ImagePickerDelegate.java:442)
        at io.flutter.app.FlutterPluginRegistry.onActivityResult(FlutterPluginRegistry.java:204)
        at io.flutter.app.FlutterActivityDelegate.onActivityResult(FlutterActivityDelegate.java:132)
        at io.flutter.app.FlutterActivity.onActivityResult(FlutterActivity.java:142)
        at android.app.Activity.dispatchActivityResult(Activity.java:6529)
```

```
```

```
```

**Comment by BugsBunnyBR** [comment]
Hello there @zylz10 ,

Would you please share a few things with us?
What is the ImagePicker version you are using?
Are you able to reproduce it? Could give us a step by step of how to reproduce it?

**Comment by escamoteur** [comment]
Also please add the output of `flutter doctor`

**Comment by raphFlash** [comment]
I can't reproduce but i have crashes from crashlytics with this stacktrace 

> Fatal Exception: java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=2342, result=-1, data=Intent { dat=content://com.microsoft.skydrive.content.StorageAccessProvider/document/content://com.microsoft.skydrive.content.metadata/Drive/ID/1/Item/ID/3387/Property/?RefreshOption=AutoRefresh&RefreshTimeOut=15000 flg=0x1 }} to activity {com.xxx.xxx}: java.lang.NullPointerException: Attempt to invoke virtual method 'int android.graphics.Bitmap.getWidth()' on a null object reference
       at android.app.ActivityThread.deliverResults(ActivityThread.java:5078)
       at android.app.ActivityThread.handleSendResult(ActivityThread.java:5120)
       at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:49)
       at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
       at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2199)
       at android.os.Handler.dispatchMessage(Handler.java:112)
       at android.os.Looper.loop(Looper.java:216)
       at android.app.ActivityThread.main(ActivityThread.java:7625)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:987)

> Caused by java.lang.NullPointerException: Attempt to invoke virtual method 'int android.graphics.Bitmap.getWidth()' on a null object reference
       at io.flutter.plugins.imagepicker.ImageResizer.b(ImageResizer.java:6)
       at io.flutter.plugins.imagepicker.ImageResizer.a(ImageResizer.java:18)
       at io.flutter.plugins.imagepicker.ImagePickerDelegate.a(ImagePickerDelegate.java:49)
       at io.flutter.plugins.imagepicker.ImagePickerDelegate.a(ImagePickerDelegate.java:18)
       at io.flutter.plugins.imagepicker.ImagePickerDelegate.onActivityResult(ImagePickerDelegate.java:30)
       at io.flutter.app.FlutterPluginRegistry.onActivityResult(FlutterPluginRegistry.java:18)
       at io.flutter.app.FlutterActivityDelegate.onActivityResult(FlutterActivityDelegate.java:6)
       at io.flutter.app.FlutterActivity.onActivityResult(FlutterActivity.java:2)
       at android.app.Activity.dispatchActivityResult(Activity.java:7797)
       at android.app.ActivityThread.deliverResults(ActivityThread.java:5071)
       at android.app.ActivityThread.handleSendResult(ActivityThread.java:5120)
       at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:49)
       at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
       at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2199)
       at android.os.Handler.dispatchMessage(Handler.java:112)
       at android.os.Looper.loop(Looper.java:216)
       at android.app.ActivityThread.main(ActivityThread.java:7625)

on a Huawei P30, android 9
and HTC U11+, android 9

**Comment by escamoteur** [comment]
Could everyone who still has this problem please file a new issue with the exact descriptions what happens, logs and the output of ' flutter doctor -v'  please.
All system setups can be slightly different so its always better to open new issues and reference related issues.

Please also add the version of the image_picker that your are using. latest is 0.6.1+10 .
