### ISSUE TITLE
assertion was thrown building DefaultTextStyle

### ISSUE THREAD

**Issue by deboLing** [flutter/flutter#40933]
## Steps to Reproduce
```
════════ Exception Caught By widgets library ═══════════════════════════════════════════════════════
The following assertion was thrown building DefaultTextStyle(debugLabel: (dense body1 2014).merge(whiteMountainView body1), inherit: false, color: Color(0xffffffff), family: Roboto, size: 15.0, weight: 400, baseline: ideographic, decoration: TextDecoration.none, softWrap: wrapping at box width, overflow: clip):
'package:flutter/src/widgets/framework.dart': Failed assertion: line 4004 pos 12: '_state._element == null': is not true.

Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=BUG.md

When the exception was thrown, this was the stack: 
#2      new StatefulElement (package:flutter/src/widgets/framework.dart:4004:12)
#3      StatefulWidget.createElement (package:flutter/src/widgets/framework.dart:802:38)
#4      Element.inflateWidget (package:flutter/src/widgets/framework.dart:3082:40)
#5      Element.updateChild (package:flutter/src/widgets/framework.dart:2887:12)
#6      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3935:16)
...
════════════════════════════════════════════════════════════════════════════════════════════════════
```

**Comment by BondarenkoStas** [comment]
@deboLing This is a question better suited for StackOverflow, since there doesn’t seem to be anything wrong with Flutter itself, but related to the implementation. Closing, as this is not an issue report. See https://flutter.dev/community for support options.
If you disagree, feel free to comment and I will reopen the issue.
