### ISSUE TITLE
Crash on Android

### ISSUE THREAD

**Issue by jimbeveridge** [flutter/flutter#4095]
## Steps to Reproduce

(Running on Nexus 9 with Marshmallow)

1. Run my demo app
2. Hit "Back"
3. Run the Material Gallery
4. Hit "Back"
5. Run demo app again to bring up the existing instance
6. May have to repeat this process a couple of times.

## Flutter Doctor

```
[✓] Flutter (on Linux, channel master)
    • Flutter at /media/.../src/third_party/flutter
    • Framework revision 6f365d33ac (2 days ago), engine revision 7fab0c350b

[✓] Android toolchain - develop for Android devices (Android SDK 23.0.2)
    • Android SDK at /usr/local/google/home/jimbe/Android/Sdk
    • Platform android-23, build-tools 23.0.2
    • OpenJDK Runtime Environment (build 1.8.0-google-v7-121669373-121622544)

[✓] Atom - a lightweight development environment for Flutter
    • Atom installed; Flutter plugin version 0.2.2
```

## Logs and Crash Reports

```
--------- beginning of crash
F/libc    : Fatal signal 11 (SIGSEGV), code 1, fault addr 0x854 in tid 25750 (RenderThread)
F/DEBUG   : *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
F/DEBUG   : Build fingerprint: 'google/volantis/flounder:6.0.1/MOB30K/2787339:user/release-keys'
F/DEBUG   : Revision: '0'
F/DEBUG   : ABI: 'arm'
F/DEBUG   : pid: 25729, tid: 25750, name: RenderThread  >>> com.google.corp.teams <<<
F/DEBUG   : signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x854
F/DEBUG   :     r0 00000238  r1 dfead5ac  r2 00000000  r3 00000268
F/DEBUG   :     r4 00000238  r5 00000238  r6 e9b9e28d  r7 00000000
F/DEBUG   :     r8 eabdf73c  r9 df828800  sl ab1f9240  fp ab1f9268
F/DEBUG   :     ip eac47f1c  sp dfead554  lr eacdb267  pc eacdae62  cpsr 600f0030
F/DEBUG   : 
F/DEBUG   : backtrace:
F/DEBUG   :     #00 pc 0003fe62  /vendor/lib/egl/libEGL_tegra.so
F/DEBUG   :     #01 pc 00254264  [heap]
F/DEBUG   : 
F/DEBUG   : Tombstone written to: /data/tombstones/tombstone_05
W/ActivityManager:   Force finishing activity com.google.corp.teams/org.domokit.sky.shell.SkyActivity
W/ActivityManager: Exception thrown during pause
W/ActivityManager: android.os.DeadObjectException
W/ActivityManager: 	at android.os.BinderProxy.transactNative(Native Method)
W/ActivityManager: 	at android.os.BinderProxy.transact(Binder.java:503)
W/ActivityManager: 	at android.app.ApplicationThreadProxy.schedulePauseActivity(ApplicationThreadNative.java:727)
W/ActivityManager: 	at com.android.server.am.ActivityStack.startPausingLocked(ActivityStack.java:867)
W/ActivityManager: 	at com.android.server.am.ActivityStack.finishActivityLocked(ActivityStack.java:2907)
W/ActivityManager: 	at com.android.server.am.ActivityStack.finishTopRunningActivityLocked(ActivityStack.java:2763)
W/ActivityManager: 	at com.android.server.am.ActivityStackSupervisor.finishTopRunningActivityLocked(ActivityStackSupervisor.java:2760)
W/ActivityManager: 	at com.android.server.am.ActivityManagerService.handleAppCrashLocked(ActivityManagerService.java:12037)
W/ActivityManager: 	at com.android.server.am.ActivityManagerService.makeAppCrashingLocked(ActivityManagerService.java:11933)
W/ActivityManager: 	at com.android.server.am.ActivityManagerService.crashApplication(ActivityManagerService.java:12622)
W/ActivityManager: 	at com.android.server.am.ActivityManagerService.handleApplicationCrashInner(ActivityManagerService.java:12129)
W/ActivityManager: 	at com.android.server.am.NativeCrashListener$NativeCrashReporter.run(NativeCrashListener.java:86)
```

> For more information about diagnosing and reporting Flutter bugs, please see [https://flutter.io/bug-reports/](https://flutter.io/bug-reports/).

**Comment by jimbeveridge** [comment]
Closing this bug. I can no longer reproduce it.
