### ISSUE TITLE
Flutter crash report

### ISSUE THREAD

**Issue by gabrielrodrigodesbesell** [flutter/flutter#40965]
## command
```
flutter --no-color run --machine --track-widget-creation --device-id=2019040121181 lib\main.dart
```
## exception
```
FileSystemException: FileSystemException: Creation failed, path = 'C:\src\flutter\bin\cache\downloads\storage.googleapis.com\flutter_infra\flutter\@lt@@lt@@lt@@lt@@lt@@lt@@lt@ HEAD
b863200c37df4ed378042de11c4e9ff34e4e58c9
70f21b0edb0636fac38127b49064d03beb0a1ed8
@gt@@gt@@gt@@gt@@gt@@gt@@gt@ ec07e039c202c7fa407b931348bb783175730ed2' (OS Error: O sistema não pode encontrar o caminho especificado.
, errno = 3)

```
```
#0      _Directory.createSync (dart:io/directory_impl.dart:138:7)
#1      _Directory.createSync (dart:io/directory_impl.dart:133:16)
#2      ForwardingDirectory.createSync (package:file/src/forwarding/forwarding_directory.dart:22:16)
#3      _ensureExists (package:flutter_tools/src/cache.dart:1163:15)
#4      _downloadFile (package:flutter_tools/src/cache.dart:1148:3)
<asynchronous suspension>
#5      CachedArtifact._downloadArchive.<anonymous closure> (package:flutter_tools/src/cache.dart:492:17)
<asynchronous suspension>
#6      CachedArtifact._withDownloadFile (package:flutter_tools/src/cache.dart:521:26)
<asynchronous suspension>
#7      CachedArtifact._downloadArchive (package:flutter_tools/src/cache.dart:488:12)
#8      CachedArtifact._downloadZipArchive (package:flutter_tools/src/cache.dart:508:12)
#9      EngineCachedArtifact.updateInner (package:flutter_tools/src/cache.dart:656:13)
<asynchronous suspension>
#10     CachedArtifact.update (package:flutter_tools/src/cache.dart:450:11)
<asynchronous suspension>
#11     Cache.updateAll (package:flutter_tools/src/cache.dart:349:24)
<asynchronous suspension>
#12     FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:507:19)
<asynchronous suspension>
#13     FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:444:33)
<asynchronous suspension>
#14     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:157:29)
<asynchronous suspension>
#15     _rootRun (dart:async/zone.dart:1124:13)
#16     _CustomZone.run (dart:async/zone.dart:1021:19)
#17     _runZoned (dart:async/zone.dart:1516:10)
#18     runZoned (dart:async/zone.dart:1463:12)
#19     AppContext.run (package:flutter_tools/src/base/context.dart:156:18)
<asynchronous suspension>
#20     FlutterCommand.run (package:flutter_tools/src/runner/flutter_command.dart:434:20)
#21     CommandRunner.runCommand (package:args/command_runner.dart:197:27)
<asynchronous suspension>
#22     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:416:21)
<asynchronous suspension>
#23     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:157:29)
<asynchronous suspension>
#24     _rootRun (dart:async/zone.dart:1124:13)
#25     _CustomZone.run (dart:async/zone.dart:1021:19)
#26     _runZoned (dart:async/zone.dart:1516:10)
#27     runZoned (dart:async/zone.dart:1463:12)
#28     AppContext.run (package:flutter_tools/src/base/context.dart:156:18)
<asynchronous suspension>
#29     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:367:19)
<asynchronous suspension>
#30     CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:112:25)
#31     new Future.sync (dart:async/future.dart:224:31)
#32     CommandRunner.run (package:args/command_runner.dart:112:14)
#33     FlutterCommandRunner.run (package:flutter_tools/src/runner/flutter_command_runner.dart:251:18)
#34     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:63:22)
<asynchronous suspension>
#35     _rootRun (dart:async/zone.dart:1124:13)
#36     _CustomZone.run (dart:async/zone.dart:1021:19)
#37     _runZoned (dart:async/zone.dart:1516:10)
#38     runZoned (dart:async/zone.dart:1500:12)
#39     run.<anonymous closure> (package:flutter_tools/runner.dart:61:18)
<asynchronous suspension>
#40     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:157:29)
<asynchronous suspension>
#41     _rootRun (dart:async/zone.dart:1124:13)
#42     _CustomZone.run (dart:async/zone.dart:1021:19)
#43     _runZoned (dart:async/zone.dart:1516:10)
#44     runZoned (dart:async/zone.dart:1463:12)
#45     AppContext.run (package:flutter_tools/src/base/context.dart:156:18)
<asynchronous suspension>
#46     runInContext (package:flutter_tools/src/context_runner.dart:62:24)
<asynchronous suspension>
#47     run (package:flutter_tools/runner.dart:50:10)
#48     main (package:flutter_tools/executable.dart:65:9)
<asynchronous suspension>
#49     main (file:///C:/src/flutter/packages/flutter_tools/bin/flutter_tools.dart:8:3)
#50     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:303:32)
#51     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:12)
```

## flutter doctor

```
[✓] Flutter (Channel unknown, v1.9.1+hotfix.2, on Microsoft Windows [versÃ£o 10.0.17763.737], locale pt-BR)
    • Flutter version 1.9.1+hotfix.2 at C:\src\flutter
    • Framework revision 2d2a1ffec9 (13 days ago), 2019-09-06 18:39:49 -0700
    • Engine revision <<<<<<< HE
    • Dart version 2.5.0

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at C:\Users\Gabriel\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-Q, build-tools 28.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)
    • All Android licenses accepted.

[✓] Android Studio (version 3.5)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 39.0.3
    • Dart plugin version 191.8423
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)

[✓] VS Code (version 1.37.0)
    • VS Code at C:\Users\Gabriel\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.3.0

[✓] Connected device (1 available)
    • JICAI Q2 • 2019040121181 • android-arm • Android 6.0 (API 23)

• No issues found!
```

**Comment by BondarenkoStas** [comment]
@gabrielrodrigodesbesell I don't know how it happened, but your Engine revision is ```<<<<<<< HEAD```, and the exception is cause with searching of those "less then" (@lt) simbols. Did you change the version with `flutter version v1.9.1+hotfix.2`? In those cases channel is shown is `unknown`. Can you switch to the stable channel and do flutter upgrade?

**Comment by gabrielrodrigodesbesell** [comment]
@BondarenkoStas I don't understand how this happened too, just ran the command flutter clean and after that I could no longer compile the app because it returned this error.
I resolved by reinstalling the flutter in the same location. Even so thank you very much for the return.
