### ISSUE TITLE
`FLUTTER_STORAGE_BASE_URL` starts with space character, flutter upgrade will crash.

### ISSUE THREAD

**Issue by zbs-ha** [flutter/flutter#41018]
## command

flutter --no-color --no-version-check precache

## exception

FormatException: FormatException: Scheme not starting with alphabetic character (at character 1)
 https://storage.flutter-io.cn/flutter_infra/flutter/99092a0436a2dd3f1228ff...
^

```
#0      _Uri._fail (dart:core/uri.dart:1623:5)
#1      _Uri._makeScheme (dart:core/uri.dart:2184:7)
#2      new _Uri.notSimple (dart:core/uri.dart:1465:18)
#3      Uri.parse (dart:core/uri.dart:1022:17)
#4      EngineCachedArtifact.updateInner (package:flutter_tools/src/cache.dart:656:71)
<asynchronous suspension>
#5      CachedArtifact.update (package:flutter_tools/src/cache.dart:450:11)
<asynchronous suspension>
#6      Cache.updateAll (package:flutter_tools/src/cache.dart:349:24)
<asynchronous suspension>
#7      PrecacheCommand.runCommand (package:flutter_tools/src/commands/precache.dart:78:19)
<asynchronous suspension>
#8      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:527:18)
#9      _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:71:64)
#10     _rootRunUnary (dart:async/zone.dart:1132:38)
#11     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#12     _FutureListener.handleValue (dart:async/future_impl.dart:137:18)
#13     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:678:45)
#14     Future._propagateToListeners (dart:async/future_impl.dart:707:32)
#15     Future._completeWithValue (dart:async/future_impl.dart:522:5)
#16     Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:552:7)
#17     _rootRun (dart:async/zone.dart:1124:13)
#18     _CustomZone.run (dart:async/zone.dart:1021:19)
#19     _CustomZone.runGuarded (dart:async/zone.dart:923:7)
#20     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:963:23)
#21     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#22     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#23     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:116:13)
#24     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:173:5)
```

## flutter doctor

```
[✓] Flutter (Channel master, v1.10.6-pre.29, on Microsoft Windows [Version 10.0.18362.356], locale zh-CN)
    • Flutter version 1.10.6-pre.29 at C:\Users\31417\AppData\Local\Programs\flutter
    • Framework revision 919cc97f6a (10 hours ago), 2019-09-20 14:57:05 -0700
    • Engine revision 99092a0436
    • Dart version 2.6.0 (build 2.6.0-dev.1.0 7c1821c4aa)

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.0)
    • Android SDK at C:\Users\31417\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.0
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[✓] Android Studio (version 3.5)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 39.0.3
    • Dart plugin version 191.8423
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)

[✓] IntelliJ IDEA Ultimate Edition (version 2019.2)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA 2019.1.3
    • Flutter plugin version 39.0.5
    • Dart plugin version 192.6603.23

[✓] VS Code (version 1.38.1)
    • VS Code at C:\Users\31417\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.4.1

[✓] Connected device (2 available)
    • Chrome • chrome • web-javascript • Google Chrome 76.0.3809.132
    • Server • web    • web-javascript • Flutter Tools

• No issues found!
```

**Comment by zbs-ha** [comment]
It's my fault, i am so stupid. 
I think that `FLUTTER_STORAGE_BASE_URL` should be trim before used.

**Comment by BondarenkoStas** [comment]
@zbs-ha so was it unintentional space while export FLUTTER_STORAGE_BASE_URL?

**Comment by zbs-ha** [comment]
@BondarenkoStas yes, it was.  thank you.
