### ISSUE TITLE
MojoEventHandler is already handling events

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#4102]
_From @Kleak on May 23, 2016 12:4_

I'm following the codelab [here](https://codelabs.developers.google.com/codelabs/flutter/index.html?index=..%2F..%2Findex#11)
And after all the modification for integrate flutter inside my app i have this error `MojoEventHandler is already handling events`

and the stacktrace :
```
E/flutter : [ERROR:dart_error.cc(17)] Unhandled exception:
E/flutter : MojoApiError: MojoEventHandler is already handling events
E/flutter : #0      MojoEventHandler.beginHandlingEvents (package:mojo/src/event_stream.dart:193)
E/flutter : #1      Encoder.encodeInterface (package:mojo/src/codec.dart:227)
E/flutter : #2      _DatabaseReferenceAddChildEventListenerParams.encode (package:firebase/src/generated/firebase.mojom.dart:1086)
E/flutter : #3      Struct.serializeWithHeader (package:mojo/src/struct.dart:23)
E/flutter : #4      Proxy.sendMessage (package:mojo/src/proxy.dart:91)
E/flutter : #5      _DatabaseReferenceProxyCalls.addChildEventListener (package:firebase/src/generated/firebase.mojom.dart:3012)
E/flutter : #6      _FlutterQuery._on.<anonymous closure> (package:firebase/src/flutter/database.dart:217)
E/flutter : #7      _runGuarded (dart:async/stream_controller.dart:809)
E/flutter : #8      _BroadcastStreamController._subscribe (dart:async/broadcast_stream_controller.dart:224)
E/flutter : #9      _ControllerStream._createSubscription (dart:async/stream_controller.dart:827)
E/flutter : #10     _StreamImpl.listen (dart:async/stream_impl.dart:468)
E/flutter : #11     _ForwardingStreamSubscription._ForwardingStreamSubscription (dart:async/stream_pipe.dart:133)
E/flutter : #12     _ForwardingStream._createSubscription (dart:async/stream_pipe.dart:101)
E/flutter : #13     _ForwardingStream.listen (dart:async/stream_pipe.dart:93)
E/flutter : #14     ChatScreenState.initState.<anonymous closure>.<anonymous closure> (/home/kleak/Work/hello_world/lib/src/widgets/chat_screen.dart:32)
E/flutter : #15     State.setState (package:flutter/src/widgets/framework.dart:419)
E/flutter : #16     ChatScreenState.initState.<anonymous closure> (/home/kleak/Work/hello_world/lib/src/widgets/chat_screen.dart:31)
E/flutter : #17     _RootZone.runUnary (dart:async/zone.dart:1204)
E/flutter : #18     _FutureListener.handleValue (dart:async/future_impl.dart:131)
E/flutter : #19     _Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:628)
E/flutter : #20     _Future._propagateToListeners (dart:async/future_impl.dart:658)
E/flutter : #21     _Future._completeWithValue (dart:async/future_impl.dart:468)
E/flutter : #22     _Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:519)
E/flutter : #23     _microtaskLoop (dart:async/schedule_microtask.dart:41)
E/flutter : #24     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50)
```

Don't know if it's the right place to post the issue..

_Copied from original issue: flutter/firebase-dart#7_

**Comment by sethladd** [comment]
cc @collinjackson

**Comment by collinjackson** [comment]
Hi @Kleak, could you send us the contents of chat_screen.dart? I want to see if there's an issue with the initState method.

**Comment by Kleak** [comment]
up it's working now, I have update my flutter version since @abarth has push a new one

**Comment by collinjackson** [comment]
Great, thanks!
