### ISSUE TITLE
gradlew.bat exited abnormally when trying to run "default app"

### ISSUE THREAD

**Issue by Laban1** [flutter/flutter#41039]
## Issue

I have a clean installation of Android Studio, etc. (following the steps here: https://www.youtube.com/watch?v=x0uinJvhNxI).

I created a default skeleton app by: `flutter create first`

**flutter doctor** finds no issues (see below), but the app will not run: `Error running Gradle: ProcessException: Process "C:\Data\Devel\flutter\first\android\gradlew.bat" exited abnormally:`

I see plenty of similar issues, but no apparent solution.

Please help.

## Logs

```
C:\Data\Devel\flutter\first>flutter run --verbose
[  +16 ms] executing: [C:\Programs\flutter\] git log -n 1 --pretty=format:%H
[  +53 ms] Exit code 0 from: git log -n 1 --pretty=format:%H
[        ] 2d2a1ffec95cc70a3218872a2cd3f8de4933c42f
[        ] executing: [C:\Programs\flutter\] git describe --match v*.*.* --first-parent --long --tags
[  +37 ms] Exit code 0 from: git describe --match v*.*.* --first-parent --long --tags
[   +2 ms] v1.9.1+hotfix.2-0-g2d2a1ffec
[   +5 ms] executing: [C:\Programs\flutter\] git rev-parse --abbrev-ref --symbolic @{u}
[  +38 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[   +1 ms] origin/stable
[        ] executing: [C:\Programs\flutter\] git ls-remote --get-url origin
[  +33 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[  +61 ms] executing: [C:\Programs\flutter\] git rev-parse --abbrev-ref HEAD
[  +36 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] stable
[  +64 ms] executing: C:\Users\LarsO\AppData\Local\Android\sdk\platform-tools\adb.exe devices -l
[  +19 ms] Exit code 0 from: C:\Users\LarsO\AppData\Local\Android\sdk\platform-tools\adb.exe devices -l
[   +1 ms] List of devices attached
           emulator-5554          device product:sdk_gphone_x86 model:Android_SDK_built_for_x86 device:generic_x86
           transport_id:2
[  +12 ms] C:\Users\LarsO\AppData\Local\Android\sdk\platform-tools\adb.exe -s emulator-5554 shell getprop
[  +47 ms] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +5 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[  +77 ms] ro.hardware = ranchu
[  +25 ms] Using hardware rendering with device Android SDK built for x86. If you get graphics artifacts, consider
enabling
           software rendering with "--enable-software-rendering".
[  +14 ms] Launching lib\main.dart on Android SDK built for x86 in debug mode...
[   +8 ms] Initializing gradle...
[   +1 ms] Using gradle from C:\Data\Devel\flutter\first\android\gradlew.bat.
[  +80 ms] executing: C:\Data\Devel\flutter\first\android\gradlew.bat -v
[ +391 ms]
                    C:\Data\Devel\flutter\first>if "Windows_NT" == "Windows_NT" setlocal
                    C:\Data\Devel\flutter\first>set DEFAULT_JVM_OPTS=
                    C:\Data\Devel\flutter\first>set DIRNAME=C:\Data\Devel\flutter\first\android\
                    C:\Data\Devel\flutter\first>if "C:\Data\Devel\flutter\first\android\" == "" set DIRNAME=.
                    C:\Data\Devel\flutter\first>set APP_BASE_NAME=gradlew
                    C:\Data\Devel\flutter\first>set APP_HOME=C:\Data\Devel\flutter\first\android\
                    C:\Data\Devel\flutter\first>if defined JAVA_HOME goto findJavaFromJavaHome
                    C:\Data\Devel\flutter\first>set JAVA_HOME=C:\Program Files\Android\Android Studio\jre
                    C:\Data\Devel\flutter\first>set JAVA_EXE=C:\Program Files\Android\Android Studio\jre/bin/java.exe
                    C:\Data\Devel\flutter\first>if exist "C:\Program Files\Android\Android Studio\jre/bin/java.exe" goto init
                    C:\Data\Devel\flutter\first>if not "Windows_NT" == "Windows_NT" goto win9xME_args
                    C:\Data\Devel\flutter\first>if "@eval[2+2]" == "4" goto 4NT_args
                    C:\Data\Devel\flutter\first>set CMD_LINE_ARGS=
                    C:\Data\Devel\flutter\first>set _SKIP=2
                    C:\Data\Devel\flutter\first>if "x-v" == "x" goto execute
                    C:\Data\Devel\flutter\first>set CMD_LINE_ARGS=-v
                    C:\Data\Devel\flutter\first>goto execute
                    C:\Data\Devel\flutter\first>set CLASSPATH=C:\Data\Devel\flutter\first\android\\gradle\wrapper\gradle-wrapper.jar
                    C:\Data\Devel\flutter\first>"C:\Program Files\Android\Android Studio\jre/bin/java.exe" "-Dorg.gradle.appname=gradlew" -classpath
                    "C:\Data\Devel\flutter\first\android\\gradle\wrapper\gradle-wrapper.jar" org.gradle.wrapper.GradleWrapperMain -v

                    ------------------------------------------------------------
                    Gradle 5.4.1
                    ------------------------------------------------------------

                    Build time:   2019-04-26 08:14:42 UTC
                    Revision:     261d171646b36a6a28d5a19a69676cd098a4c19d

                    Kotlin:       1.3.21
                    Groovy:       2.5.4
                    Ant:          Apache Ant(TM) version 1.9.13 compiled on July 10 2018
                    JVM:          1.8.0_202-release (JetBrains s.r.o 25.202-b03)
                    OS:           Windows 10 10.0 amd64


                    C:\Data\Devel\flutter\first>if "0" == "0" goto mainEnd
                    C:\Data\Devel\flutter\first>if "Windows_NT" == "Windows_NT" endlocal
[  +10 ms] Initializing gradle... (completed in 0.5s)
[   +1 ms] Resolving dependencies...
[   +1 ms] executing: [C:\Data\Devel\flutter\first\android\] C:\Data\Devel\flutter\first\android\gradlew.bat
app:properties
[+2273 ms]
                    C:\Data\Devel\flutter\first\android>if "Windows_NT" == "Windows_NT" setlocal
                    C:\Data\Devel\flutter\first\android>set DEFAULT_JVM_OPTS=
                    C:\Data\Devel\flutter\first\android>set DIRNAME=C:\Data\Devel\flutter\first\android\
                    C:\Data\Devel\flutter\first\android>if "C:\Data\Devel\flutter\first\android\" == "" set DIRNAME=.
                    C:\Data\Devel\flutter\first\android>set APP_BASE_NAME=gradlew
                    C:\Data\Devel\flutter\first\android>set APP_HOME=C:\Data\Devel\flutter\first\android\
                    C:\Data\Devel\flutter\first\android>if defined JAVA_HOME goto findJavaFromJavaHome
                    C:\Data\Devel\flutter\first\android>set JAVA_HOME=C:\Program Files\Android\Android Studio\jre
                    C:\Data\Devel\flutter\first\android>set JAVA_EXE=C:\Program Files\Android\Android Studio\jre/bin/java.exe

                    C:\Data\Devel\flutter\first\android>if exist "C:\Program Files\Android\Android Studio\jre/bin/java.exe" goto init
                    C:\Data\Devel\flutter\first\android>if not "Windows_NT" == "Windows_NT" goto win9xME_args
                    C:\Data\Devel\flutter\first\android>if "@eval[2+2]" == "4" goto 4NT_args
                    C:\Data\Devel\flutter\first\android>set CMD_LINE_ARGS=
                    C:\Data\Devel\flutter\first\android>set _SKIP=2
                    C:\Data\Devel\flutter\first\android>if "xapp:properties" == "x" goto execute
                    C:\Data\Devel\flutter\first\android>set CMD_LINE_ARGS=app:properties
                    C:\Data\Devel\flutter\first\android>goto execute
                    C:\Data\Devel\flutter\first\android>set CLASSPATH=C:\Data\Devel\flutter\first\android\\gradle\wrapper\gradle-wrapper.jar
                    C:\Data\Devel\flutter\first\android>"C:\Program Files\Android\Android Studio\jre/bin/java.exe" "-Dorg.gradle.appname=gradlew" -classpath "C:\Data\Devel\flutter\first\android\\gradle\wrapper\gradle-wrapper.jar" org.gradle.wrapper.GradleWrapperMain app:properties
                    > Configure project :app
                    WARNING: API 'variant.getJavaCompile()' is obsolete and has been replaced with 'variant.getJavaCompileProvider()'.
                    It will be removed at the end of 2019.
                    For more information, see https://d.android.com/r/tools/task-configuration-avoidance.
                    To determine what is calling variant.getJavaCompile(), use -Pandroid.debug.obsoleteApi=true on the command line to display more information.
                    WARNING: API 'variant.getMergeAssets()' is obsolete and has been replaced with 'variant.getMergeAssetsProvider()'.
                    It will be removed at the end of 2019.
                    For more information, see https://d.android.com/r/tools/task-configuration-avoidance. To determine what is calling variant.getMergeAssets(), use -Pandroid.debug.obsoleteApi=true on the command line to display more information.
                    WARNING: API 'variantOutput.getProcessResources()' is obsolete and has been replaced with 'variantOutput.getProcessResourcesProvider()'.
                    It will be removed at the end of 2019.
                    For more information, see https://d.android.com/r/tools/task-configuration-avoidance.
                    To determine what is calling variantOutput.getProcessResources(), use
                    -Pandroid.debug.obsoleteApi=true on the command line to display more information.
                    C:\Data\Devel\flutter\first\android>if "1" == "0" goto mainEnd
                    C:\Data\Devel\flutter\first\android>rem Set variable GRADLE_EXIT_CONSOLE if you need the _script_ return code instead of
                    C:\Data\Devel\flutter\first\android>rem the _cmd.exe /c_ return code!
                    C:\Data\Devel\flutter\first\android>if not "" == "" exit 1
                    C:\Data\Devel\flutter\first\android>exit /b 1
[   +7 ms] Resolving dependencies... (completed in 2.3s)
[   +4 ms] * Error running Gradle: ProcessException: Process "C:\Data\Devel\flutter\first\android\gradlew.bat" exited abnormally:
           C:\Data\Devel\flutter\first\android>if "Windows_NT" == "Windows_NT" setlocal
           C:\Data\Devel\flutter\first\android>set DEFAULT_JVM_OPTS=
           C:\Data\Devel\flutter\first\android>set DIRNAME=C:\Data\Devel\flutter\first\android\
           C:\Data\Devel\flutter\first\android>if "C:\Data\Devel\flutter\first\android\" == "" set DIRNAME=.
           C:\Data\Devel\flutter\first\android>set APP_BASE_NAME=gradlew
           C:\Data\Devel\flutter\first\android>set APP_HOME=C:\Data\Devel\flutter\first\android\
           C:\Data\Devel\flutter\first\android>if defined JAVA_HOME goto findJavaFromJavaHome
           C:\Data\Devel\flutter\first\android>set JAVA_HOME=C:\Program Files\Android\Android Studio\jre
           C:\Data\Devel\flutter\first\android>set JAVA_EXE=C:\Program Files\Android\Android Studio\jre/bin/java.exe
           C:\Data\Devel\flutter\first\android>if exist "C:\Program Files\Android\Android Studio\jre/bin/java.exe" goto init
           C:\Data\Devel\flutter\first\android>if not "Windows_NT" == "Windows_NT" goto win9xME_args
           C:\Data\Devel\flutter\first\android>if "@eval[2+2]" == "4" goto 4NT_args
           C:\Data\Devel\flutter\first\android>set CMD_LINE_ARGS=
           C:\Data\Devel\flutter\first\android>set _SKIP=2
           C:\Data\Devel\flutter\first\android>if "xapp:properties" == "x" goto execute
           C:\Data\Devel\flutter\first\android>set CMD_LINE_ARGS=app:properties
           C:\Data\Devel\flutter\first\android>goto execute
           C:\Data\Devel\flutter\first\android>set CLASSPATH=C:\Data\Devel\flutter\first\android\\gradle\wrapper\gradle-wrapper.jar

           C:\Data\Devel\flutter\first\android>"C:\Program Files\Android\Android Studio\jre/bin/java.exe" "-Dorg.gradle.appname=gradlew" -classpath "C:\Data\Devel\flutter\first\android\\gradle\wrapper\gradle-wrapper.jar" org.gradle.wrapper.GradleWrapperMain app:properties
           > Configure project :app
           WARNING: API 'variant.getJavaCompile()' is obsolete and has been replaced with
'variant.getJavaCompileProvider()'.
           It will be removed at the end of 2019.
           For more information, see https://d.android.com/r/tools/task-configuration-avoidance.
           To determine what is calling variant.getJavaCompile(), use -Pandroid.debug.obsoleteApi=true on the command line to display more information.
           WARNING: API 'variant.getMergeAssets()' is obsolete and has been replaced with 'variant.getMergeAssetsProvider()'.
           It will be removed at the end of 2019.
           For more information, see https://d.android.com/r/tools/task-configuration-avoidance.
           To determine what is calling variant.getMergeAssets(), use -Pandroid.debug.obsoleteApi=true on the command line to
           display more information.
           WARNING: API 'variantOutput.getProcessResources()' is obsolete and has been replaced with
           'variantOutput.getProcessResourcesProvider()'.
           It will be removed at the end of 2019.
           For more information, see https://d.android.com/r/tools/task-configuration-avoidance.
           To determine what is calling variantOutput.getProcessResources(), use -Pandroid.debug.obsoleteApi=true on the command line to display more information.
           C:\Data\Devel\flutter\first\android>if "1" == "0" goto mainEnd
           C:\Data\Devel\flutter\first\android>rem Set variable GRADLE_EXIT_CONSOLE if you need the _script_ return code instead of
           C:\Data\Devel\flutter\first\android>rem the _cmd.exe /c_ return code!
           C:\Data\Devel\flutter\first\android>if not "" == "" exit 1
           C:\Data\Devel\flutter\first\android>exit /b 1
             Command: C:\Data\Devel\flutter\first\android\gradlew.bat app:properties

[   +8 ms] "flutter run" took 3,102ms.
Please review your Gradle project setup in the android/ folder.

#0      throwToolExit (package:flutter_tools/src/base/common.dart:28:3)
#1      _readGradleProject (package:flutter_tools/src/android/gradle.dart:233:7)
<asynchronous suspension>
#2      _gradleAppProject (package:flutter_tools/src/android/gradle.dart:112:37)
<asynchronous suspension>
#3      getGradleAppOut (package:flutter_tools/src/android/gradle.dart:106:29)
<asynchronous suspension>
#4      AndroidApk.fromAndroidProject (package:flutter_tools/src/application_package.dart:164:23)
<asynchronous suspension>
#5      ApplicationPackageFactory.getPackageForPlatform (package:flutter_tools/src/application_package.dart:46:32)
<asynchronous suspension>
#6      FlutterDevice.runHot (package:flutter_tools/src/resident_runner.dart:359:56)
<asynchronous suspension>
#7      HotRunner.run (package:flutter_tools/src/run_hot.dart:254:39)
<asynchronous suspension>
#8      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:472:37)
<asynchronous suspension>
#9      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:490:18)
#10     _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:71:64)
#11     _rootRunUnary (dart:async/zone.dart:1132:38)
#12     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#13     _FutureListener.handleValue (dart:async/future_impl.dart:137:18)
#14     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:678:45)
#15     Future._propagateToListeners (dart:async/future_impl.dart:707:32)
#16     Future._completeWithValue (dart:async/future_impl.dart:522:5)
#17     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:30:15)
#18     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:288:13)
#19     RunCommand.usageValues (package:flutter_tools/src/commands/run.dart)
#20     _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:71:64)
#21     _rootRunUnary (dart:async/zone.dart:1132:38)
#22     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#23     _FutureListener.handleValue (dart:async/future_impl.dart:137:18)
#24     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:678:45)
#25     Future._propagateToListeners (dart:async/future_impl.dart:707:32)
#26     Future._completeWithValue (dart:async/future_impl.dart:522:5)
#27     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:30:15)
#28     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:288:13)
#29     AndroidDevice.isLocalEmulator (package:flutter_tools/src/android/android_device.dart)
#30     _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:71:64)
#31     _rootRunUnary (dart:async/zone.dart:1132:38)
#32     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#33     _FutureListener.handleValue (dart:async/future_impl.dart:137:18)
#34     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:678:45)
#35     Future._propagateToListeners (dart:async/future_impl.dart:707:32)
#36     Future._completeWithValue (dart:async/future_impl.dart:522:5)
#37     Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:552:7)
#38     _rootRun (dart:async/zone.dart:1124:13)
#39     _CustomZone.run (dart:async/zone.dart:1021:19)
#40     _CustomZone.runGuarded (dart:async/zone.dart:923:7)
#41     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:963:23)
#42     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#43     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#44     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:116:13)
#45     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:173:5)

```

## Flutter Doctor

```
C:\Data\Devel\flutter\first>flutter doctor -v
[√] Flutter (Channel stable, v1.9.1+hotfix.2, on Microsoft Windows [Version 10.0.18362.356], locale en-US)
    • Flutter version 1.9.1+hotfix.2 at C:\Programs\flutter
    • Framework revision 2d2a1ffec9 (2 weeks ago), 2019-09-06 18:39:49 -0700
    • Engine revision b863200c37
    • Dart version 2.5.0

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at C:\Users\LarsO\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)
    • All Android licenses accepted.

[√] Android Studio (version 3.5)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 39.0.3
    • Dart plugin version 191.8423
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)

[√] Connected device (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 9 (API 28) (emulator)

• No issues found!

```

**Comment by Laban1** [comment]
Bump.  Anybody?

**Comment by escamoteur** [comment]
Hi, I would like to ask if you were able to solve this problem in the meantime?

Seems to be the same as https://github.com/flutter/flutter/issues/41766

**Comment by Laban1** [comment]
Yes and no.  I created a new project ("flutter create...") and this time it ran fine.  Go figure.  It sure would have been nice to have a more descriptive error message.

**Comment by escamoteur** [comment]
Thanks for the fast reply. Yes we are working on improving error messages.
