### ISSUE TITLE
Problem in running cross-platform Flutter App (Flutter 1.10.5 • channel dev)

### ISSUE THREAD

**Issue by ptyagicodecamp** [flutter/flutter#41049]
I'm getting following error log when trying to run Flutter app on Android. Works fine for Chrome.
Flutter installation info:
```
$ flutter --version
Flutter 1.10.5 • channel dev • https://github.com/flutter/flutter.git
Framework • revision 3cf88fed6d (3 days ago) • 2019-09-18 23:09:41 -0400
Engine • revision 33ad6757e8
Tools • Dart 2.6.0 (build 2.6.0-dev.0.0 cb80ea7ba9)

```

I'm using following check to separate web from mobile:
```
    if (dart.library.html) 'web.dart'
    if (dart.library.io) 'mobile.dart';
```

`error_log`
```
Launching lib/main.dart on Android SDK built for x86 in debug mode...
Initializing gradle...
Resolving dependencies...
Running Gradle task 'assembleDebug'...
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
Error reading dependency file /Users/ptyagi/Developer/ptyagicodecamp/flutter/x-flutter-landingpage/landingpage/build/app/intermediates/flutter/debug/android-x86/snapshot_blob.bin.d: java.lang.ArrayIndexOutOfBoundsException: 1
Error reading dependency file /Users/ptyagi/Developer/ptyagicodecamp/flutter/x-flutter-landingpage/landingpage/build/app/intermediates/flutter/debug/android-x86/snapshot_blob.bin.d: java.lang.ArrayIndexOutOfBoundsException: 1

Compiler message:
../../../../../fluttersdk/flutter/.pub-cache/hosted/pub.dartlang.org/firebase-5.0.4/lib/src/utils.dart:2:8: Error: Not found: 'dart:html'
import 'dart:html' show promiseToFuture;
       ^
../../../../../fluttersdk/flutter/.pub-cache/hosted/pub.dartlang.org/js-0.6.1+1/lib/js.dart:8:1: Error: Not found: 'dart:js'
export 'dart:js' show allowInterop, allowInteropCaptureThis;
^
../../../../../fluttersdk/flutter/.pub-cache/hosted/pub.dartlang.org/js-0.6.1+1/lib/js_util.dart:8:1: Error: Not found: 'dart:js_util'
export 'dart:js_util';
^
../../../../../fluttersdk/flutter/.pub-cache/hosted/pub.dartlang.org/firebase-5.0.4/lib/src/auth.dart:274:25: Error: Method not found: 'allowInterop'.
      var nextWrapper = allowInterop((firebase_interop.UserJsImpl user) {
                        ^^^^^^^^^^^^
../../../../../fluttersdk/flutter/.pub-cache/hosted/pub.dartlang.org/firebase-5.0.4/lib/src/auth.dart:278:26: Error: Method not found: 'allowInterop'.
      var errorWrapper = allowInterop((e) => _changeController.addError(e));
                         ^^^^^^^^^^^^
../../../../../fluttersdk/flutter/.pub-cache/hosted/pub.dartlang.org/firebase-5.0.4/lib/src/auth.dart:274:25: Error: The method 'allowInterop' isn't defined for the class 'Auth'.
 - 'Auth' is from 'package:firebase/src/auth.dart' ('../../../../../fluttersdk/flutter/.pub-cache/hosted/pub.dartlang.org/firebase-5.0.4/lib/src/auth.dart').
Try correcting the name to the name of an existing method, or defining a method named 'allowInterop'.
      var nextWrapper = allowInterop((firebase_interop.UserJsImpl user) {
                        ^^^^^^^^^^^^
../../../../../fluttersdk/flutter/.pub-cache/hosted/pub.dartlang.org/firebase-5.0.4/lib/src/auth.dart:278:26: Error: The method 'allowInterop' isn't defined for the class 'Auth'.
 - 'Auth' is from 'package:firebase/src/auth.dart' ('../../../../../fluttersdk/flutter/.pub-cache/hosted/pub.dartlang.org/firebase-5.0.4/lib/src/auth.dart').
Try correcting the name to the name of an existing method, or defining a method named 'allowInterop'.
      var errorWrapper = allowInterop((e) => _changeController.addError(e));
                         ^^^^^^^^^^^^
../../../../../fluttersdk/flutter/.pub-cache/hosted/pub.dartlang.org/firebase-5.0.4/lib/src/auth.dart:308:25: Error: Method not found: 'allowInterop'.
      var nextWrapper = allowInterop((firebase_interop.UserJsImpl user) {
                        ^^^^^^^^^^^^
../../../../../fluttersdk/flutter/.pub-cache/hosted/pub.dartlang.org/firebase-5.0.4/lib/src/auth.dart:313:11: Error: Method not found: 'allowInterop'.
          allowInterop((e) => _idTokenChangedController.addError(e));
          ^^^^^^^^^^^^
../../../../../fluttersdk/flutter/.pub-cache/hosted/pub.dartlang.org/firebase-5.0.4/lib/src/auth.dart:308:25: Error: The method 'allowInterop' isn't defined for the class 'Auth'.
 - 'Auth' is from 'package:firebase/src/auth.dart' ('../../../../../fluttersdk/flutter/.pub-cache/hosted/pub.dartlang.org/firebase-5.0.4/lib/src/auth.dart').
Try correcting the name to the name of an existing method, or defining a method named 'allowInterop'.
      var nextWrapper = allowInterop((firebase_interop.UserJsImpl user) {
                        ^^^^^^^^^^^^
../../../../../fluttersdk/flutter/.pub-cache/hosted/pub.dartlang.org/firebase-5.0.4/lib/src/auth.dart:313:11: Error: The method 'allowInterop' isn't defined for the class 'Auth'.
 - 'Auth' is from 'package:firebase/src/auth.dart' ('../../../../../fluttersdk/flutter/.pub-cache/hosted/pub.dartlang.org/firebase-5.0.4/lib/src/auth.dart').
Try correcting the name to the name of an existing method, or defining a method named 'allowInterop'.
          allowInterop((e) => _idTokenChangedController.addError(e));
          ^^^^^^^^^^^^
../../../../../fluttersdk/flutter/.pub-cache/hosted/pub.dartlang.org/firebase-5.0.4/lib/src/database.dart:164:9: Error: Method not found: 'allowInterop'.
        allowInterop((update) => jsify(transactionUpdate(dartify(update))));
        ^^^^^^^^^^^^
../../../../../fluttersdk/flutter/.pub-cache/hosted/pub.dartlang.org/firebase-5.0.4/lib/src/database.dart:166:26: Error: Method not found: 'allowInterop'.
    var onCompleteWrap = allowInterop(
                         ^^^^^^^^^^^^
../../../../../fluttersdk/flutter/.pub-cache/hosted/pub.dartlang.org/firebase-5.0.4/lib/src/database.dart:164:9: Error: The method 'allowInterop' isn't defined for the class 'DatabaseReference<T>'.
 - 'DatabaseReference' is from 'package:firebase/src/database.dart' ('../../../../../fluttersdk/flutter/.pub-cache/hosted/pub.dartlang.org/firebase-5.0.4/lib/src/database.dart').
Try correcting the name to the name of an existing method, or defining a method named 'allowInterop'.
        allowInterop((update) => jsify(transactionUpdate(dartify(update))));
        ^^^^^^^^^^^^
../../../../../fluttersdk/flutter/.pub-cache/hosted/pub.dartlang.org/firebase-5.0.4/lib/src/database.dart:166:26: Error: The method 'allowInterop' isn't defined for the class 'DatabaseReference<T>'.
 - 'DatabaseReference' is from 'package:firebase/src/database.dart' ('../../../../../fluttersdk/flutter/.pub-cache/hosted/pub.dartlang.org/firebase-5.0.4/lib/src/database.dart').
Try correcting the name to the name of an existing method, or defining a method named 'allowInterop'.
    var onCompleteWrap = allowInterop(
                         ^^^^^^^^^^^^
../../../../../fluttersdk/flutter/.pub-cache/hosted/pub.dartlang.org/firebase-5.0.4/lib/src/database.dart:299:24: Error: Method not found: 'allowInterop'.
    var callbackWrap = allowInterop((database_interop.DataSnapshotJsImpl data,
                       ^^^^^^^^^^^^
../../../../../fluttersdk/flutter/.pub-cache/hosted/pub.dartlang.org/firebase-5.0.4/lib/src/database.dart:299:24: Error: The method 'allowInterop' isn't defined for the class 'Query<T>'.
 - 'Query' is from 'package:firebase/src/database.dart' ('../../../../../fluttersdk/flutter/.pub-cache/hosted/pub.dartlang.org/firebase-5.0.4/lib/src/database.dart').
Try correcting the name to the name of an existing method, or defining a method named 'allowInterop'.
    var callbackWrap = allowInterop((database_interop.DataSnapshotJsImpl data,
                       ^^^^^^^^^^^^
../../../../../fluttersdk/flutter/.pub-cache/hosted/pub.dartlang.org/firebase-5.0.4/lib/src/database.dart:323:30: Error: Method not found: 'allowInterop'.
    jsObject.once(eventType, allowInterop(
                             ^^^^^^^^^^^^
../../../../../fluttersdk/flutter/.pub-cache/hosted/pub.dartlang.org/firebase-5.0.4/lib/src/database.dart:323:30: Error: The method 'allowInterop' isn't defined for the class 'Query<T>'.
 - 'Query' is from 'package:firebase/src/database.dart' ('../../../../../fluttersdk/flutter/.pub-cache/hosted/pub.dartlang.org/firebase-5.0.4/lib/src/database.dart').
Try correcting the name to the name of an existing method, or defining a method named 'allowInterop'.
    jsObject.once(eventType, allowInterop(
                             ^^^^^^^^^^^^
../../../../../fluttersdk/flutter/.pub-cache/hosted/pub.dartlang.org/firebase-5.0.4/lib/src/database.dart:399:22: Error: Method not found: 'allowInterop'.
    var actionWrap = allowInterop((d) => action(DataSnapshot.getInstance(d)));
                     ^^^^^^^^^^^^
../../../../../fluttersdk/flutter/.pub-cache/hosted/pub.dartlang.org/firebase-5.0.4/lib/src/database.dart:399:22: Error: The method 'allowInterop' isn't defined for the class 'DataSnapshot'.
 - 'DataSnapshot' is from 'package:firebase/src/database.dart' ('../../../../../fluttersdk/flutter/.pub-cache/hosted/pub.dartlang.org/firebase-5.0.4/lib/src/database.dart').
Try correcting the name to the name of an existing method, or defining a method named 'allowInterop'.
    var actionWrap = allowInterop((d) => action(DataSnapshot.getInstance(d)));
                     ^^^^^^^^^^^^
../../../../../fluttersdk/flutter/.pub-cache/hosted/pub.dartlang.org/firebase-5.0.4/lib/src/messaging.dart:70:27: Error: Method not found: 'allowInterop'.
      final nextWrapper = allowInterop((payload) {
                          ^^^^^^^^^^^^
../../../../../fluttersdk/flutter/.pub-cache/hosted/pub.dartlang.org/firebase-5.0.4/lib/src/messaging.dart:73:28: Error: Method not found: 'allowInterop'.
      final errorWrapper = allowInterop((e) {
                           ^^^^^^^^^^^^
../../../../../fluttersdk/flutter/.pub-cache/hosted/pub.dartlang.org/firebase-5.0.4/lib/src/messaging.dart:70:27: Error: The method 'allowInterop' isn't defined for the class 'Messaging'.
 - 'Messaging' is from 'package:firebase/src/messaging.dart' ('../../../../../fluttersdk/flutter/.pub-cache/hosted/pub.dartlang.org/firebase-5.0.4/lib/src/messaging.dart').
Try correcting the name to the name of an existing method, or defining a method named 'allowInterop'.
      final nextWrapper = allowInterop((payload) {
                          ^^^^^^^^^^^^
../../../../../fluttersdk/flutter/.pub-cache/hosted/pub.dartlang.org/firebase-5.0.4/lib/src/messaging.dart:73:28: Error: The method 'allowInterop' isn't defined for the class 'Messaging'.
 - 'Messaging' is from 'package:firebase/src/messaging.dart' ('../../../../../fluttersdk/flutter/.pub-cache/hosted/pub.dartlang.org/firebase-5.0.4/lib/src/messaging.dart').
Try correcting the name to the name of an existing method, or defining a method named 'allowInterop'.
      final errorWrapper = allowInterop((e) {
                           ^^^^^^^^^^^^
../../../../../fluttersdk/flutter/.pub-cache/hosted/pub.dartlang.org/firebase-5.0.4/lib/src/messaging.dart:85:27: Error: Method not found: 'allowInterop'.
      final nextWrapper = allowInterop((payload) {
                          ^^^^^^^^^^^^
../../../../../fluttersdk/flutter/.pub-cache/hosted/pub.dartlang.org/firebase-5.0.4/lib/src/messaging.dart:85:27: Error: The method 'allowInterop' isn't defined for the class 'Messaging'.
 - 'Messaging' is from 'package:firebase/src/messaging.dart' ('../../../../../fluttersdk/flutter/.pub-cache/hosted/pub.dartlang.org/firebase-5.0.4/lib/src/messaging.dart').
Try correcting the name to the name of an existing method, or defining a method named 'allowInterop'.
      final nextWrapper = allowInterop((payload) {
                          ^^^^^^^^^^^^
../../../../../fluttersdk/flutter/.pub-cache/hosted/pub.dartlang.org/firebase-5.0.4/lib/src/messaging.dart:95:27: Error: Method not found: 'allowInterop'.
      final nextWrapper = allowInterop((_) => null);
                          ^^^^^^^^^^^^
../../../../../fluttersdk/flutter/.pub-cache/hosted/pub.dartlang.org/firebase-5.0.4/lib/src/messaging.dart:96:28: Error: Method not found: 'allowInterop'.
      final errorWrapper = allowInterop((e) {
                           ^^^^^^^^^^^^
../../../../../fluttersdk/flutter/.pub-cache/hosted/pub.dartlang.org/firebase-5.0.4/lib/src/messaging.dart:95:27: Error: The method 'allowInterop' isn't defined for the class 'Messaging'.
 - 'Messaging' is from 'package:firebase/src/messaging.dart' ('../../../../../fluttersdk/flutter/.pub-cache/hosted/pub.dartlang.org/firebase-5.0.4/lib/src/messaging.dart').
Try correcting the name to the name of an existing method, or defining a method named 'allowInterop'.
      final nextWrapper = allowInterop((_) => null);
                          ^^^^^^^^^^^^
../../../../../fluttersdk/flutter/.pub-cache/hosted/pub.dartlang.org/firebase-5.0.4/lib/src/messaging.dart:96:28: Error: The method 'allowInterop' isn't defined for the class 'Messaging'.
 - 'Messaging' is from 'package:firebase/src/messaging.dart' ('../../../../../fluttersdk/flutter/.pub-cache/hosted/pub.dartlang.org/firebase-5.0.4/lib/src/messaging.dart').
Try correcting the name to the name of an existing method, or defining a method named 'allowInterop'.
      final errorWrapper = allowInterop((e) {
                           ^^^^^^^^^^^^
../../../../../fluttersdk/flutter/.pub-cache/hosted/pub.dartlang.org/firebase-5.0.4/lib/src/storage.dart:289:11: Error: Method not found: 'allowInterop'.
          allowInterop((storage_interop.UploadTaskSnapshotJsImpl data) {
          ^^^^^^^^^^^^
../../../../../fluttersdk/flutter/.pub-cache/hosted/pub.dartlang.org/firebase-5.0.4/lib/src/storage.dart:293:26: Error: Method not found: 'allowInterop'.
      var errorWrapper = allowInterop((e) => _changeController.addError(e));
                         ^^^^^^^^^^^^
../../../../../fluttersdk/flutter/.pub-cache/hosted/pub.dartlang.org/firebase-5.0.4/lib/src/storage.dart:294:26: Error: Method not found: 'allowInterop'.
      var onCompletion = allowInterop(() => _changeController.close());
                         ^^^^^^^^^^^^
../../../../../fluttersdk/flutter/.pub-cache/hosted/pub.dartlang.org/firebase-5.0.4/lib/src/storage.dart:289:11: Error: The method 'allowInterop' isn't defined for the class 'UploadTask'.
 - 'UploadTask' is from 'package:firebase/src/storage.dart' ('../../../../../fluttersdk/flutter/.pub-cache/hosted/pub.dartlang.org/firebase-5.0.4/lib/src/storage.dart').
Try correcting the name to the name of an existing method, or defining a method named 'allowInterop'.
          allowInterop((storage_interop.UploadTaskSnapshotJsImpl data) {
          ^^^^^^^^^^^^
../../../../../fluttersdk/flutter/.pub-cache/hosted/pub.dartlang.org/firebase-5.0.4/lib/src/storage.dart:293:26: Error: The method 'allowInterop' isn't defined for the class 'UploadTask'.
 - 'UploadTask' is from 'package:firebase/src/storage.dart' ('../../../../../fluttersdk/flutter/.pub-cache/hosted/pub.dartlang.org/firebase-5.0.4/lib/src/storage.dart').
Try correcting the name to the name of an existing method, or defining a method named 'allowInterop'.
      var errorWrapper = allowInterop((e) => _changeController.addError(e));
                         ^^^^^^^^^^^^
../../../../../fluttersdk/flutter/.pub-cache/hosted/pub.dartlang.org/firebase-5.0.4/lib/src/storage.dart:294:26: Error: The method 'allowInterop' isn't defined for the class 'UploadTask'.
 - 'UploadTask' is from 'package:firebase/src/storage.dart' ('../../../../../fluttersdk/flutter/.pub-cache/hosted/pub.dartlang.org/firebase-5.0.4/lib/src/storage.dart').
Try correcting the name to the name of an existing method, or defining a method named 'allowInterop'.
      var onCompletion = allowInterop(() => _changeController.close());
                         ^^^^^^^^^^^^
../../../../../fluttersdk/flutter/.pub-cache/hosted/pub.dartlang.org/firebase-5.0.4/lib/src/top_level.dart:139:7: Error: Method not found: 'hasProperty'.
  if (js.hasProperty(error, 'message')) {
      ^^^^^^^^^^^
../../../../../fluttersdk/flutter/.pub-cache/hosted/pub.dartlang.org/firebase-5.0.4/lib/src/top_level.dart:140:19: Error: Method not found: 'getProperty'.
    var message = js.getProperty(error, 'message');
                  ^^^^^^^^^^^
../../../../../fluttersdk/flutter/.pub-cache/hosted/pub.dartlang.org/firebase-5.0.4/lib/src/firestore.dart:96:30: Error: Method not found: 'allowInterop'.
    var updateFunctionWrap = allowInterop((transaction) =>
                             ^^^^^^^^^^^^
../../../../../fluttersdk/flutter/.pub-cache/hosted/pub.dartlang.org/firebase-5.0.4/lib/src/firestore.dart:96:30: Error: The method 'allowInterop' isn't defined for the class 'Firestore'.
 - 'Firestore' is from 'package:firebase/src/firestore.dart' ('../../../../../fluttersdk/flutter/.pub-cache/hosted/pub.dartlang.org/firebase-5.0.4/lib/src/firestore.dart').
Try correcting the name to the name of an existing method, or defining a method named 'allowInterop'.
    var updateFunctionWrap = allowInterop((transaction) =>
                             ^^^^^^^^^^^^
../../../../../fluttersdk/flutter/.pub-cache/hosted/pub.dartlang.org/firebase-5.0.4/lib/src/firestore.dart:297:11: Error: Method not found: 'allowInterop'.
          allowInterop((firestore_interop.DocumentSnapshotJsImpl snapshot) {
          ^^^^^^^^^^^^
../../../../../fluttersdk/flutter/.pub-cache/hosted/pub.dartlang.org/firebase-5.0.4/lib/src/firestore.dart:301:26: Error: Method not found: 'allowInterop'.
      var errorWrapper = allowInterop((e) => controller.addError(e));
                         ^^^^^^^^^^^^
../../../../../fluttersdk/flutter/.pub-cache/hosted/pub.dartlang.org/firebase-5.0.4/lib/src/firestore.dart:297:11: Error: The method 'allowInterop' isn't defined for the class 'DocumentReference'.
 - 'DocumentReference' is from 'package:firebase/src/firestore.dart' ('../../../../../fluttersdk/flutter/.pub-cache/hosted/pub.dartlang.org/firebase-5.0.4/lib/src/firestore.dart').
Try correcting the name to the name of an existing method, or defining a method named 'allowInterop'.
          allowInterop((firestore_interop.DocumentSnapshotJsImpl snapshot) {
          ^^^^^^^^^^^^
../../../../../fluttersdk/flutter/.pub-cache/hosted/pub.dartlang.org/firebase-5.0.4/lib/src/firestore.dart:301:26: Error: The method 'allowInterop' isn't defined for the class 'DocumentReference'.
 - 'DocumentReference' is from 'package:firebase/src/firestore.dart' ('../../../../../fluttersdk/flutter/.pub-cache/hosted/pub.dartlang.org/firebase-5.0.4/lib/src/firestore.dart').
Try correcting the name to the name of an existing method, or defining a method named 'allowInterop'.
      var errorWrapper = allowInterop((e) => controller.addError(e));
                         ^^^^^^^^^^^^
../../../../../fluttersdk/flutter/.pub-cache/hosted/pub.dartlang.org/firebase-5.0.4/lib/src/firestore.dart:436:9: Error: Method not found: 'allowInterop'.
        allowInterop((firestore_interop.QuerySnapshotJsImpl snapshot) {
        ^^^^^^^^^^^^
../../../../../fluttersdk/flutter/.pub-cache/hosted/pub.dartlang.org/firebase-5.0.4/lib/src/firestore.dart:440:24: Error: Method not found: 'allowInterop'.
    var errorWrapper = allowInterop((e) => controller.addError(e));
                       ^^^^^^^^^^^^
../../../../../fluttersdk/flutter/.pub-cache/hosted/pub.dartlang.org/firebase-5.0.4/lib/src/firestore.dart:436:9: Error: The method 'allowInterop' isn't defined for the class 'Query<T>'.
 - 'Query' is from 'package:firebase/src/firestore.dart' ('../../../../../fluttersdk/flutter/.pub-cache/hosted/pub.dartlang.org/firebase-5.0.4/lib/src/firestore.dart').
Try correcting the name to the name of an existing method, or defining a method named 'allowInterop'.
        allowInterop((firestore_interop.QuerySnapshotJsImpl snapshot) {
        ^^^^^^^^^^^^
../../../../../fluttersdk/flutter/.pub-cache/hosted/pub.dartlang.org/firebase-5.0.4/lib/src/firestore.dart:440:24: Error: The method 'allowInterop' isn't defined for the class 'Query<T>'.
 - 'Query' is from 'package:firebase/src/firestore.dart' ('../../../../../fluttersdk/flutter/.pub-cache/hosted/pub.dartlang.org/firebase-5.0.4/lib/src/firestore.dart').
Try correcting the name to the name of an existing method, or defining a method named 'allowInterop'.
    var errorWrapper = allowInterop((e) => controller.addError(e));
                       ^^^^^^^^^^^^
../../../../../fluttersdk/flutter/.pub-cache/hosted/pub.dartlang.org/firebase-5.0.4/lib/src/firestore.dart:766:9: Error: Method not found: 'allowInterop'.
        allowInterop((s) => callback(DocumentSnapshot.getInstance(s)));
        ^^^^^^^^^^^^
../../../../../fluttersdk/flutter/.pub-cache/hosted/pub.dartlang.org/firebase-5.0.4/lib/src/firestore.dart:766:9: Error: The method 'allowInterop' isn't defined for the class 'QuerySnapshot'.
 - 'QuerySnapshot' is from 'package:firebase/src/firestore.dart' ('../../../../../fluttersdk/flutter/.pub-cache/hosted/pub.dartlang.org/firebase-5.0.4/lib/src/firestore.dart').
Try correcting the name to the name of an existing method, or defining a method named 'allowInterop'.
        allowInterop((s) => callback(DocumentSnapshot.getInstance(s)));
        ^^^^^^^^^^^^
../../../../../fluttersdk/flutter/.pub-cache/hosted/pub.dartlang.org/firebase-5.0.4/lib/src/utils.dart:29:7: Error: Method not found: 'hasProperty'.
  if (util.hasProperty(jsObject, 'firestore') &&
      ^^^^^^^^^^^
../../../../../fluttersdk/flutter/.pub-cache/hosted/pub.dartlang.org/firebase-5.0.4/lib/src/utils.dart:30:7: Error: Method not found: 'hasProperty'.
      util.hasProperty(jsObject, 'id') &&
      ^^^^^^^^^^^
../../../../../fluttersdk/flutter/.pub-cache/hosted/pub.dartlang.org/firebase-5.0.4/lib/src/utils.dart:31:7: Error: Method not found: 'hasProperty'.
      util.hasProperty(jsObject, 'parent')) {
      ^^^^^^^^^^^
../../../../../fluttersdk/flutter/.pub-cache/hosted/pub.dartlang.org/firebase-5.0.4/lib/src/utils.dart:37:7: Error: Method not found: 'hasProperty'.
  if (util.hasProperty(jsObject, 'latitude') &&
      ^^^^^^^^^^^
../../../../../fluttersdk/flutter/.pub-cache/hosted/pub.dartlang.org/firebase-5.0.4/lib/src/utils.dart:38:7: Error: Method not found: 'hasProperty'.
      util.hasProperty(jsObject, 'longitude') &&
      ^^^^^^^^^^^
../../../../../fluttersdk/flutter/.pub-cache/hosted/pub.dartlang.org/firebase-5.0.4/lib/src/utils.dart:44:15: Error: Method not found: 'getProperty'.
  var proto = util.getProperty(jsObject, '__proto__');
              ^^^^^^^^^^^
../../../../../fluttersdk/flutter/.pub-cache/hosted/pub.dartlang.org/firebase-5.0.4/lib/src/utils.dart:46:7: Error: Method not found: 'hasProperty'.
  if (util.hasProperty(proto, 'toDate') &&
      ^^^^^^^^^^^
../../../../../fluttersdk/flutter/.pub-cache/hosted/pub.dartlang.org/firebase-5.0.4/lib/src/utils.dart:47:7: Error: Method not found: 'hasProperty'.
      util.hasProperty(proto, 'toMillis')) {
      ^^^^^^^^^^^
../../../../../fluttersdk/flutter/.pub-cache/hosted/pub.dartlang.org/firebase-5.0.4/lib/src/utils.dart:52:7: Error: Method not found: 'hasProperty'.
  if (util.hasProperty(proto, 'isEqual') &&
      ^^^^^^^^^^^
../../../../../fluttersdk/flutter/.pub-cache/hosted/pub.dartlang.org/firebase-5.0.4/lib/src/utils.dart:53:7: Error: Method not found: 'hasProperty'.
      util.hasProperty(proto, 'toBase64')) {
      ^^^^^^^^^^^
../../../../../fluttersdk/flutter/.pub-cache/hosted/pub.dartlang.org/firebase-5.0.4/lib/src/utils.dart:63:24: Error: Method not found: 'getProperty'.
    map[key] = dartify(util.getProperty(jsObject, key));
                       ^^^^^^^^^^^
../../../../../fluttersdk/flutter/.pub-cache/hosted/pub.dartlang.org/firebase-5.0.4/lib/src/utils.dart:87:17: Error: Method not found: 'newObject'.
    var jsMap = util.newObject();
                ^^^^^^^^^
../../../../../fluttersdk/flutter/.pub-cache/hosted/pub.dartlang.org/firebase-5.0.4/lib/src/utils.dart:89:7: Error: Method not found: 'setProperty'.
      util.setProperty(jsMap, key, jsify(value));
      ^^^^^^^^^^^
../../../../../fluttersdk/flutter/.pub-cache/hosted/pub.dartlang.org/firebase-5.0.4/lib/src/utils.dart:112:12: Error: Method not found: 'allowInterop'.
    return allowInterop(dartObject);
           ^^^^^^^^^^^^
../../../../../fluttersdk/flutter/.pub-cache/hosted/pub.dartlang.org/firebase-5.0.4/lib/src/utils.dart:120:5: Error: Method not found: 'callMethod'.
    util.callMethod(jsObject, method, args);
    ^^^^^^^^^^
../../../../../fluttersdk/flutter/.pub-cache/hosted/pub.dartlang.org/firebase-5.0.4/lib/src/utils.dart:133:5: Error: Method not found: 'promiseToFuture'.
    promiseToFuture(thenable);
    ^^^^^^^^^^^^^^^
../../../../../fluttersdk/flutter/.pub-cache/hosted/pub.dartlang.org/firebase-5.0.4/lib/src/utils.dart:138:27: Error: Method not found: 'allowInterop'.
  return PromiseJsImpl<S>(allowInterop((VoidFunc1 resolve, VoidFunc1 reject) {
                          ^^^^^^^^^^^^
../../../../../fluttersdk/flutter/.pub-cache/hosted/pub.dartlang.org/firebase-5.0.4/lib/src/utils.dart:149:40: Error: Method not found: 'allowInterop'.
VoidFunc1 resolveError(Completer c) => allowInterop(c.completeError);
                                       ^^^^^^^^^^^^
../../../../../fluttersdk/flutter/.pub-cache/hosted/pub.dartlang.org/firebase-5.0.4/lib/src/interop/js_interop.dart:17:7: Error: Method not found: 'hasProperty'.
  if (util.hasProperty(jsObject, "toDateString")) {
      ^^^^^^^^^^^
Unhandled exception:
FileSystemException(uri=org-dartlang-untranslatable-uri:dart%3Ahtml; message=StandardFileSystem only supports file:* and data:* URIs)
#0      StandardFileSystem.entityForUri (package:front_end/src/api_prototype/standard_file_system.dart:33:7)
#1      asFileUri (package:vm/kernel_front_end.dart:520:37)
<asynchronous suspension>
#2      writeDepfile (package:vm/kernel_front_end.dart:697:21)
<asynchronous suspension>
#3      FrontendCompiler.compile (package:vm/frontend_server.dart:407:15)
<asynchronous suspension>
#4      _FlutterFrontendCompiler.compile (package:frontend_server/server.dart:29:22)
<asynchronous suspension>
#5      starter (package:frontend_server/server.dart:132:27)
<asynchronous suspension>
#6      main (file:///b/s/w/ir/cache/builder/src/flutter/frontend_server/bin/starter.dart:8:30)
<asynchronous suspension>
#7      _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:303:32)
#8      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:12)

Compiler failed on /Users/ptyagi/Developer/ptyagicodecamp/flutter/x-flutter-landingpage/landingpage/lib/main.dart

FAILURE: Build failed with an exception.

* Where:
Script '/Users/ptyagi/fluttersdk/flutter/packages/flutter_tools/gradle/flutter.gradle' line: 789

* What went wrong:
Execution failed for task ':app:compileFlutterBuildDebugX86'.
> Process 'command '/Users/ptyagi/fluttersdk/flutter/bin/flutter'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 16s
Finished with error: Gradle task assembleDebug failed with exit code 1

```

**Comment by escamoteur** [comment]
Could you please try on master and on the stable branch?

**Comment by ptyagicodecamp** [comment]
@escamoteur same behavior on master and stable branches.

**Comment by escamoteur** [comment]
Ehm just one question how do you use
```Dart
if (dart.library.html) 'web.dart'
if (dart.library.io) 'mobile.dart';
```

Could you show me a bit more code? 

Does it work for a newly created project?

**Comment by escamoteur** [comment]
I m honestly surprised that it works on we but not on android

**Comment by ptyagicodecamp** [comment]
@escamoteur Oh...I found the problem. I was using `firebase` for my internal plugin name. Changing it to a different name helped solve the issue. Thank you so much for your help debug the issue.

**Comment by Baksman** [comment]
@ptyagicodecamp  im having thesame issue, internal plugin as in how?

**Comment by ptyagicodecamp** [comment]
@Baksman I had to replace `firebase` with `firetop`(anything but firebase) in [this example](https://github.com/ptyagicodecamp/x-flutter-landingpage/tree/master/landingpage/lib/plugins)

**Comment by emiliodallatorre** [comment]
> @Baksman I had to replace `firebase` with `firetop`(anything but firebase) in [this example](https://github.com/ptyagicodecamp/x-flutter-landingpage/tree/master/landingpage/lib/plugins)

Can you please provide a morein-depth explanation?
I'm trying to solve the same problem without any success.

**Comment by ZotInfo** [comment]
I have the same problem, please provide a more in-depth explanation?

**Comment by emiliodallatorre** [comment]
> I have the same problem, please provide a more in-depth explanation?

The solution I found was to divide in two branches my project, one for mobile devices with all classic fire base dependencies and one for web with all the raw dependencies (like `firestore.dart`) and a shared part for models and UI.

**Comment by oozd** [comment]
In my case I accidently imported: `import 'package:firebase/firestore.dart';`
instead of `import 'package:cloud_firestore/cloud_firestore.dart';`

**Comment by leadpresence** [comment]
More Emphasis on the previous post make sure you are not import 'package:firebase/firestore.dart'

[]

**Comment by thealmamun** [comment]
> In my case I accidently imported: `'package:firebase/firestore.dart';`
> instead of `'package:cloud_firestore/cloud_firestore.dart';`



> In my case I accidently imported: `'package:firebase/firestore.dart';`
> instead of `'package:cloud_firestore/cloud_firestore.dart';`

fixes my issue
