### ISSUE TITLE
ChromeOS: Flutter permissions complaint

### ISSUE THREAD

**Issue by mingsai** [flutter/flutter#41058]
## Steps to Reproduce

**Running on:**

> Linux version 4.19.44-04937-gd773af751792 (chrome-bot@chromeos-ci-try-us-east1-d-x32-0-aazm) (Chromium OS 9.0_pre353983_p20190325-r14 clang version 9.0.0 (/var/cache/chromeos-cache/distfiles/host/egit-src/llvm-project de7a0a152648d1a74cf4319920b1848aa00d1ca3) (based on LLVM 9.0.0svn)) #1 SMP PREEMPT Thu Aug 8 21:43:29 PDT 2019

1. Attempt to generate new flutter project from Android Studio, Visual Studio Code, or Terminal (flutter doctor -v)
2. Flutter reports a crash that appears related to permissions. It does not provide a suggested resolution.
3. See logs and advise soonest. Currently all attempts at flutter on this box are blocked. I do have it working on another machine.
4. Same issue occurs when I plug in a device.

## Logs

```
 flutter --verbose create foo

Oops; flutter has exited unexpectedly.
Sending crash report to Google.
Crash report sent (report ID: b366b98a9c17300d)
 
Crash report written to /home/tcarter/VSCProjects/flutter_01.log;
please let us know at https://github.com/flutter/flutter/issues.

Flutter crash report; please file at https://github.com/flutter/flutter/issues.

## command

flutter --verbose create foo

## exception

FileSystemException: FileSystemException: Cannot open file, path = '/home/tcarter/dev/flutter/bin/cache/lockfile' (OS Error: Permission denied, errno = 13)

```
#0      _File.open.<anonymous closure> (dart:io/file_impl.dart:364:9)
#1      _rootRunUnary (dart:async/zone.dart:1132:38)
#2      _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#3      _FutureListener.handleValue (dart:async/future_impl.dart:126:18)
#4      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:639:45)
#5      Future._propagateToListeners (dart:async/future_impl.dart:668:32)
#6      Future._completeWithValue (dart:async/future_impl.dart:483:5)
#7      Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:513:7)
#8      _rootRun (dart:async/zone.dart:1124:13)
#9      _CustomZone.run (dart:async/zone.dart:1021:19)
#10     _CustomZone.runGuarded (dart:async/zone.dart:923:7)
#11     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:963:23)
#12     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#13     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#14     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:116:13)
#15     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:173:5)
```

## flutter doctor

```
[✓] Flutter (Channel stable, v1.7.8+hotfix.4, on Linux, locale en_US.UTF-8)
    • Flutter version 1.7.8+hotfix.4 at /home/tcarter/dev/flutter
    • Framework revision 20e59316b8 (9 weeks ago), 2019-07-18 20:04:33 -0700
    • Engine revision fee001c93f
    • Dart version 2.4.0

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /home/tcarter/Android/Sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /opt/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Android Studio (version 3.5)
    • Android Studio at /opt/android-studio
    • Flutter plugin version 38.2.3
    • Dart plugin version 191.8423
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] VS Code (version 1.38.1)
    • VS Code at /usr/share/code
    • Flutter extension version 3.4.1

[!] Connected device
    ! No devices available

! Doctor found issues in 1 category.
```
```

Flutter crash report; please file at https://github.com/flutter/flutter/issues.

## command

flutter doctor

## exception

FileSystemException: FileSystemException: Cannot open file, path = '/home/tcarter/dev/flutter/bin/cache/lockfile' (OS Error: Permission denied, errno = 13)

```
#0      _File.open.<anonymous closure> (dart:io/file_impl.dart:364:9)
#1      _rootRunUnary (dart:async/zone.dart:1132:38)
#2      _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#3      _FutureListener.handleValue (dart:async/future_impl.dart:126:18)
#4      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:639:45)
#5      Future._propagateToListeners (dart:async/future_impl.dart:668:32)
#6      Future._completeWithValue (dart:async/future_impl.dart:483:5)
#7      Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:513:7)
#8      _rootRun (dart:async/zone.dart:1124:13)
#9      _CustomZone.run (dart:async/zone.dart:1021:19)
#10     _CustomZone.runGuarded (dart:async/zone.dart:923:7)
#11     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:963:23)
#12     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#13     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#14     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:116:13)
#15     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:173:5)
```

## flutter doctor

```
[✓] Flutter (Channel stable, v1.7.8+hotfix.4, on Linux, locale en_US.UTF-8)
    • Flutter version 1.7.8+hotfix.4 at /home/tcarter/dev/flutter
    • Framework revision 20e59316b8 (9 weeks ago), 2019-07-18 20:04:33 -0700
    • Engine revision fee001c93f
    • Dart version 2.4.0

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /home/tcarter/Android/Sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /opt/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Android Studio (version 3.5)
    • Android Studio at /opt/android-studio
    • Flutter plugin version 38.2.3
    • Dart plugin version 191.8423
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] VS Code (version 1.38.1)
    • VS Code at /usr/share/code
    • Flutter extension version 3.4.1

[✓] Connected device (1 available)
    • LGL83BL • LGL83BLd0aed60f • android-arm • Android 7.0 (API 24)

• No issues found!
```

**Comment by mingsai** [comment]
Upgrading to flutter 1.9.1+hotfix.4 has resolved this issue.
