### ISSUE TITLE
EXCEPTION CAUGHT BY SCHEDULER LIBRARY (Form)

### ISSUE THREAD

**Issue by leemuljadi** [flutter/flutter#41057]
```
════════ Exception caught by widgets library ═══════════════════════════════════════════════════════

The following NoSuchMethodError was thrown building _FormScope:
The getter 'initialValue' was called on null.
Receiver: null
Tried calling: initialValue

User-created ancestor of the error-causing widget was: 
  Form-[LabeledGlobalKey<FormState>#7e514] 
When the exception was thrown, this was the stack: 
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:51:5)
#1      _FormBuilderSegmentedControlState.initState (package:flutter_form_builder/src/fields/form_builder_segmented_control.dart:62:21)
#2      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4068:58)
#3      ComponentElement.mount (package:flutter/src/widgets/framework.dart:3919:5)
#4      Element.inflateWidget (package:flutter/src/widgets/framework.dart:3101:14)
...
════════════════════════════════════════════════════════════════════════════════════════════════════

════════ (2) Exception caught by rendering library ═════════════════════════════════════════════════
The _ScaffoldLayout custom multichild layout delegate forgot to lay out the following child:
User-created ancestor of the error-causing widget was: 
  Scaffold ════════════════════════════════════════════════════════════════════════════════════════════════════
```

### **flutter doctor -v**
```
[√] Flutter (Channel stable, v1.9.1+hotfix.2, on Microsoft Windows [Version 10.0.18362.356], locale en-AU)
    • Flutter version 1.9.1+hotfix.2 at C:\Flutter\flutter
    • Framework revision 2d2a1ffec9 (2 weeks ago), 2019-09-06 18:39:49 -0700
    • Engine revision b863200c37
    • Dart version 2.5.0

[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at C:\Users\Marvin\AppData\Local\Android\Sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = C:\Users\Marvin\AppData\Local\Android\Sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)
    • All Android licenses accepted.

[√] Android Studio (version 3.5)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 39.0.3
    • Dart plugin version 191.8423
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)

[√] Connected device (1 available)
    • Redmi 4X • 2be0bae7d630 • android-arm64 • Android 7.1.2 (API 25)

• No issues found!
Process finished with exit code 0
```

**Comment by BondarenkoStas** [comment]
@leemuljadi This is a question better suited for StackOverflow, since most probably it's related to the implementation. `The getter 'initialValue' was called on null`.
Please provide a small self-contained app that demonstrates the problem. You can include small examples [inline if they're enclosed by backticks](https://help.github.com/en/articles/creating-and-highlighting-code-blocks), or just provide a public link to a github "gist" - https://gist.github.com/.

**Comment by leemuljadi** [comment]
Okay thanks, @BondarenkoStas !
