### ISSUE TITLE
Base64 crash Invalid argument (Not a byte value at index 800: 0x2018): Instance of 'CodeUnits'

### ISSUE THREAD

**Issue by jaumard** [flutter/flutter#41083]
I reproduce on iOS and Android 
Code to reproduce:

```
const data = '<p>¡Felicidades, acabas de aceptar tu tercera transacción de tarjeta! ¿Listo para aprovechar al máximo la solución KiWi y ahorrar hasta \$12,000 por año? </p> <h4 style="color:#82bc00;">¿Cómo?<br></h4> <p>Invita a tus amigos a probar KiWi</p> <p>Recibe un mes de comisiones gratis por cada invitado, tan pronto como realicen su primera transacción. </p> <p>Ofrecemos un mes completo de transacciones gratis a tus amigos invitándolos a unirse a KiWi. </p> <h4 style="color:#82bc00;">¡Todos ganan!<br></h4> <p>¿Quieres saber más al respecto? </p> <p>&gt; Abre tu aplicación KiWi<br>&gt; Ve al menú<br>&gt; Haz clic en ‘Transacciones gratis’ </strong><br>&gt; ¡Invita a tus amigos! </p>, title: ¡Felicidades por tu tercera transacción!';
final contentBase64 = base64Encode(data.codeUnits);
print(contentBase64);
```

Look like the problem is because of characters `‘` and `’`, if I remove them it works. 

## Logs
```
flutter: ══╡ EXCEPTION CAUGHT BY FLUTTER FRAMEWORK ╞═════════════════════════════════════════════════════════
flutter: The following ArgumentError was thrown:
flutter: Invalid argument (Not a byte value at index 800: 0x2018): Instance of 'CodeUnits'
flutter:
flutter: When the exception was thrown, this was the stack:
flutter: #0      _Base64Encoder.encodeChunk (dart:convert/base64.dart:365:5)
flutter: #1      _Base64Encoder.encode (dart:convert/base64.dart:319:9)
flutter: #2      Base64Encoder.convert (dart:convert/base64.dart:234:26)
flutter: #3      Codec.encode (dart:convert/codec.dart:21:32)
flutter: #4      base64Encode (dart:convert/base64.dart:40:48)
flutter: #5      FcmTextManager._handleOnGoingMessage.<anonymous closure> (package:kiwi_mobile/common/fcm/fcm_text_manager.dart:60:33)
flutter: #6      _WebViewState._onPlatformViewCreated (package:webview_flutter/webview_flutter.dart:272:14)
flutter: #7      _UiKitViewState._createNewUiKitView (package:flutter/src/widgets/platform_view.dart:515:14)
flutter: <asynchronous suspension>
flutter: #8      _UiKitViewState._initializeOnce (package:flutter/src/widgets/platform_view.dart:453:5)
flutter: #9      _UiKitViewState.didChangeDependencies (package:flutter/src/widgets/platform_view.dart:463:5)
flutter: #10     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4086:12)
flutter: #11     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3919:5)
flutter: #12     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3101:14)
flutter: #13     Element.updateChild (package:flutter/src/widgets/framework.dart:2904:12)
flutter: #14     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3961:16)
flutter: #15     Element.rebuild (package:flutter/src/widgets/framework.dart:3738:5)
flutter: #16     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3924:5)
flutter: #17     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4088:11)
flutter: #18     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3919:5)
flutter: #19     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3101:14)
flutter: #20     Element.updateChild (package:flutter/src/widgets/framework.dart:2904:12)
flutter: #21     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5127:14)
flutter: #22     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3101:14)
flutter: #23     Element.updateChild (package:flutter/src/widgets/framework.dart:2904:12)
flutter: #24     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3961:16)
flutter: #25     Element.rebuild (package:flutter/src/widgets/framework.dart:3738:5)
flutter: #26     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3924:5)
flutter: #27     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3919:5)
flutter: #28     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3101:14)
flutter: #29     Element.updateChild (package:flutter/src/widgets/framework.dart:2904:12)
flutter: #30     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3961:16)
flutter: #31     Element.rebuild (package:flutter/src/widgets/framework.dart:3738:5)
flutter: #32     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3924:5)
flutter: #33     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3919:5)
flutter: #34     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3101:14)
flutter: #35     Element.updateChild (package:flutter/src/widgets/framework.dart:2904:12)
flutter: #36     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5127:14)
flutter: #37     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3101:14)
flutter: #38     MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5233:32)
flutter: #39     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3101:14)
flutter: #40     Element.updateChild (package:flutter/src/widgets/framework.dart:2904:12)
flutter: #41     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5127:14)
flutter: #42     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3101:14)
flutter: #43     Element.updateChild (package:flutter/src/widgets/framework.dart:2904:12)
flutter: #44     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5127:14)
flutter: #45     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3101:14)
flutter: #46     Element.updateChild (package:flutter/src/widgets/framework.dart:2904:12)
flutter: #47     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5127:14)
flutter: #48     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3101:14)
flutter: #49     Element.updateChild (package:flutter/src/widgets/framework.dart:2904:12)
flutter: #50     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5127:14)
flutter: #51     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3101:14)
flutter: #52     Element.updateChild (package:flutter/src/widgets/framework.dart:2904:12)
flutter: #53     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3961:16)
flutter: #54     Element.rebuild (package:flutter/src/widgets/framework.dart:3738:5)
flutter: #55     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3924:5)
flutter: #56     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3919:5)
flutter: #57     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3101:14)
flutter: #58     Element.updateChild (package:flutter/src/widgets/framework.dart:2904:12)
flutter: #59     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5127:14)
flutter: #60     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3101:14)
flutter: #61     Element.updateChild (package:flutter/src/widgets/framework.dart:2904:12)
flutter: #62     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3961:16)
flutter: #63     Element.rebuild (package:flutter/src/widgets/framework.dart:3738:5)
flutter: #64     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3924:5)
flutter: #65     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4088:11)
flutter: #66     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3919:5)
flutter: #67     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3101:14)
flutter: #68     Element.updateChild (package:flutter/src/widgets/framework.dart:2904:12)
flutter: #69     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5127:14)
flutter: #70     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3101:14)
flutter: #71     Element.updateChild (package:flutter/src/widgets/framework.dart:2904:12)
flutter: #72     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3961:16)
flutter: #73     Element.rebuild (package:flutter/src/widgets/framework.dart:3738:5)
flutter: #74     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3924:5)
flutter: #75     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3919:5)
flutter: #76     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3101:14)
flutter: #77     Element.updateChild (package:flutter/src/widgets/framework.dart:2904:12)
flutter: #78     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3961:16)
flutter: #79     Element.rebuild (package:flutter/src/widgets/framework.dart:3738:5)
flutter: #80     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3924:5)
flutter: #81     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3919:5)
flutter: #82     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3101:14)
flutter: #83     Element.updateChild (package:flutter/src/widgets/framework.dart:2904:12)
flutter: #84     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5127:14)
flutter: #85     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3101:14)
flutter: #86     Element.updateChild (package:flutter/src/widgets/framework.dart:2904:12)
flutter: #87     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3961:16)
flutter: #88     Element.rebuild (package:flutter/src/widgets/framework.dart:3738:5)
flutter: #89     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3924:5)
flutter: #90     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4088:11)
flutter: #91     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3919:5)
flutter: #92     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3101:14)
flutter: #93     Element.updateChild (package:flutter/src/widgets/framework.dart:2904:12)
flutter: #94     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3961:16)
flutter: #95     Element.rebuild (package:flutter/src/widgets/framework.dart:3738:5)
flutter: #96     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3924:5)
flutter: #97     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3919:5)
flutter: #98     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3101:14)
flutter: #99     Element.updateChild (package:flutter/src/widgets/framework.dart:2904:12)
flutter: #100    SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5127:14)
flutter: #101    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3101:14)
flutter: #102    Element.updateChild (package:flutter/src/widgets/framework.dart:2904:12)
flutter: #103    SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5127:14)
flutter: #104    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3101:14)
flutter: #105    Element.updateChild (package:flutter/src/widgets/framework.dart:2904:12)
flutter: #106    SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5127:14)
flutter: #107    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3101:14)
flutter: #108    Element.updateChild (package:flutter/src/widgets/framework.dart:2904:12)
flutter: #109    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3961:16)
flutter: #110    Element.rebuild (package:flutter/src/widgets/framework.dart:3738:5)
flutter: #111    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3924:5)
flutter: #112    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3919:5)
flutter: #113    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3101:14)
flutter: #114    Element.updateChild (package:flutter/src/widgets/framework.dart:2904:12)
flutter: #115    SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5127:14)
flutter: #116    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3101:14)
flutter: #117    Element.updateChild (package:flutter/src/widgets/framework.dart:2904:12)
flutter: #118    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3961:16)
flutter: #119    Element.rebuild (package:flutter/src/widgets/framework.dart:3738:5)
flutter: #120    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3924:5)
flutter: #121    StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4088:11)
flutter: #122    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3919:5)
flutter: #123    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3101:14)
flutter: #124    Element.updateChild (package:flutter/src/widgets/framework.dart:2904:12)
flutter: #125    SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5127:14)
flutter: #126    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3101:14)
flutter: #127    Element.updateChild (package:flutter/src/widgets/framework.dart:2904:12)
flutter: #128    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3961:16)
flutter: #129    Element.rebuild (package:flutter/src/widgets/framework.dart:3738:5)
flutter: #130    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3924:5)
flutter: #131    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3919:5)
flutter: #132    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3101:14)
flutter: #133    Element.updateChild (package:flutter/src/widgets/framework.dart:2904:12)
flutter: #134    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3961:16)
flutter: #135    Element.rebuild (package:flutter/src/widgets/framework.dart:3738:5)
flutter: #136    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3924:5)
flutter: #137    StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4088:11)
flutter: #138    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3919:5)
flutter: #139    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3101:14)
flutter: #140    Element.updateChild (package:flutter/src/widgets/framework.dart:2904:12)
flutter: #141    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3961:16)
flutter: #142    Element.rebuild (package:flutter/src/widgets/framework.dart:3738:5)
flutter: #143    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3924:5)
flutter: #144    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3919:5)
flutter: #145    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3101:14)
flutter: #146    Element.updateChild (package:flutter/src/widgets/framework.dart:2904:12)
flutter: #147    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3961:16)
flutter: #148    Element.rebuild (package:flutter/src/widgets/framework.dart:3738:5)
flutter: #149    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3924:5)
flutter: #150    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3919:5)
flutter: #151    ParentDataElement.mount (package:flutter/src/widgets/framework.dart:4314:11)
flutter: #152    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3101:14)
flutter: #153    MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5233:32)
flutter: #154    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3101:14)
flutter: #155    Element.updateChild (package:flutter/src/widgets/framework.dart:2904:12)
flutter: #156    SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5127:14)
flutter: #157    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3101:14)
flutter: #158    Element.updateChild (package:flutter/src/widgets/framework.dart:2904:12)
flutter: #159    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3961:16)
flutter: #160    Element.rebuild (package:flutter/src/widgets/framework.dart:3738:5)
flutter: #161    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3924:5)
flutter: #162    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3919:5)
flutter: #163    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3101:14)
flutter: #164    Element.updateChild (package:flutter/src/widgets/framework.dart:2904:12)
flutter: #165    _CupertinoDialogRenderElement.mount (package:flutter/src/cupertino/dialog.dart:410:23)
flutter: #166    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3101:14)
flutter: #167    Element.updateChild (package:flutter/src/widgets/framework.dart:2904:12)
flutter: #168    SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5127:14)
flutter: #169    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3101:14)
flutter: #170    Element.updateChild (package:flutter/src/widgets/framework.dart:2904:12)
flutter: #171    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3961:16)
flutter: #172    Element.rebuild (package:flutter/src/widgets/framework.dart:3738:5)
flutter: #173    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3924:5)
flutter: #174    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3919:5)
flutter: #175    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3101:14)
flutter: #176    Element.updateChild (package:flutter/src/widgets/framework.dart:2904:12)
flutter: #177    SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5127:14)
flutter: #178    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3101:14)
flutter: #179    Element.updateChild (package:flutter/src/widgets/framework.dart:2904:12)
flutter: #180    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3961:16)
flutter: #181    Element.rebuild (package:flutter/src/widgets/framework.dart:3738:5)
flutter: #182    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3924:5)
flutter: #183    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3919:5)
flutter: #184    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3101:14)
flutter: #185    Element.updateChild (package:flutter/src/widgets/framework.dart:2904:12)
flutter: #186    SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5127:14)
flutter: #187    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3101:14)
flutter: #188    Element.updateChild (package:flutter/src/widgets/framework.dart:2904:12)
flutter: #189    SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5127:14)
flutter: #190    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3101:14)
flutter: #191    Element.updateChild (package:flutter/src/widgets/framework.dart:2904:12)
flutter: #192    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3961:16)
flutter: #193    Element.rebuild (package:flutter/src/widgets/framework.dart:3738:5)
flutter: #194    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3924:5)
flutter: #195    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3919:5)
flutter: #196    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3101:14)
flutter: #197    Element.updateChild (package:flutter/src/widgets/framework.dart:2904:12)
flutter: #198    SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5127:14)
flutter: #199    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3101:14)
flutter: #200    Element.updateChild (package:flutter/src/widgets/framework.dart:2904:12)
flutter: #201    SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5127:14)
flutter: #202    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3101:14)
flutter: #203    Element.updateChild (package:flutter/src/widgets/framework.dart:2904:12)
flutter: #204    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3961:16)
flutter: #205    Element.rebuild (package:flutter/src/widgets/framework.dart:3738:5)
flutter: #206    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3924:5)
flutter: #207    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3919:5)
flutter: #208    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3101:14)
flutter: #209    Element.updateChild (package:flutter/src/widgets/framework.dart:2904:12)
flutter: #210    SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5127:14)
flutter: #211    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3101:14)
flutter: #212    Element.updateChild (package:flutter/src/widgets/framework.dart:2904:12)
flutter: #213    _LayoutBuilderElement._layout.<anonymous closure> (package:flutter/src/widgets/layout_builder.dart:115:18)
flutter: #214    BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2328:19)
flutter: #215    _LayoutBuilderElement._layout (package:flutter/src/widgets/layout_builder.dart:95:11)
flutter: #216    RenderObject.invokeLayoutCallback.<anonymous closure> (package:flutter/src/rendering/object.dart:1797:58)
flutter: #217    PipelineOwner._enableMutationsToDirtySubtrees (package:flutter/src/rendering/object.dart:875:15)
flutter: #218    RenderObject.invokeLayoutCallback (package:flutter/src/rendering/object.dart:1797:13)
flutter: #219    RenderConstrainedLayoutBuilder.layoutAndBuildChild (package:flutter/src/widgets/layout_builder.dart:173:5)
flutter: #220    _RenderLayoutBuilder.performLayout (package:flutter/src/widgets/layout_builder.dart:240:5)
flutter: #221    RenderObject.layout (package:flutter/src/rendering/object.dart:1701:7)
flutter: #222    _RenderLayoutBuilder.performLayout (package:flutter/src/widgets/layout_builder.dart:242:13)
flutter: #223    RenderObject.layout (package:flutter/src/rendering/object.dart:1701:7)
flutter: #224    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
flutter: #225    RenderObject.layout (package:flutter/src/rendering/object.dart:1701:7)
flutter: #226    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
flutter: #227    RenderObject.layout (package:flutter/src/rendering/object.dart:1701:7)
flutter: #228    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
flutter: #229    RenderObject.layout (package:flutter/src/rendering/object.dart:1701:7)
flutter: #230    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
flutter: #231    RenderObject.layout (package:flutter/src/rendering/object.dart:1701:7)
flutter: #232    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
flutter: #233    RenderOffstage.performLayout (package:flutter/src/rendering/proxy_box.dart:3140:13)
flutter: #234    RenderObject.layout (package:flutter/src/rendering/object.dart:1701:7)
flutter: #235    RenderStack.performLayout (package:flutter/src/rendering/stack.dart:510:15)
flutter: #236    RenderObject._layoutWithoutResize (package:flutter/src/rendering/object.dart:1578:7)
flutter: #237    PipelineOwner.flushLayout (package:flutter/src/rendering/object.dart:844:18)
flutter: #238    RendererBinding.drawFrame (package:flutter/src/rendering/binding.dart:341:19)
flutter: #239    WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:761:13)
flutter: #240    RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:280:5)
flutter: #241    SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1033:15)
flutter: #242    SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:975:9)
flutter: #243    SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:891:5)
flutter: #247    _invoke (dart:ui/hooks.dart:249:10)
flutter: #248    _drawFrame (dart:ui/hooks.dart:207:3)
flutter: (elided 3 frames from package dart:async)
```

## Flutter doctor:
```
[✓] Flutter (Channel stable, v1.9.1+hotfix.2, on Mac OS X 10.14.6 18G95, locale fr-FR)
    • Flutter version 1.9.1+hotfix.2 at /Users/jaumard/flutter
    • Framework revision 2d2a1ffec9 (2 weeks ago), 2019-09-06 18:39:49 -0700
    • Engine revision b863200c37
    • Dart version 2.5.0

[!] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/jaumard/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    ✗ Android SDK file not found: /Users/jaumard/Library/Android/sdk/platforms/android-29/android.jar.
    • Try re-installing or updating your Android SDK,
      visit https://flutter.dev/setup/#android-setup for detailed instructions.

[✓] Xcode - develop for iOS and macOS (Xcode 11.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.0, Build version 11A420a
    • CocoaPods version 1.6.0

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 39.0.3
    • Dart plugin version 191.8423
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] IntelliJ IDEA Ultimate Edition (version 2019.2.2)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 39.0.5
    • Dart plugin version 192.6603.23

[✓] Connected device (1 available)
    • iPhone 11 Pro Max • E915C4B9-4651-4CCE-9387-66BD92431436 • ios • com.apple.CoreSimulator.SimRuntime.iOS-13-0 (simulator)

! Doctor found issues in 1 category.
```

**Comment by escamoteur** [comment]
Yeah, this look indeed strange. But this isn't a Flutter problem it's part of the Dart-sdk do please raise the issue there.
