### ISSUE TITLE
RangeError (index): Invalid value: Not in range 0..3, inclusive:4

### ISSUE THREAD

**Issue by ggichure** [flutter/flutter#41117]
i recently ran into a problem with android 7 and 9 .the error displayed is ` RangeError (index): Invalid value: Not in range 0..3, inclusive:4`
Question is already on [SO](https://stackoverflow.com/q/57932338/10409567).
My splash screen works then after that  the app loads a root screen.
Here is the code for root screen:
```dart
class _RootScreenState extends State<RootScreen> {
  @override
  Widget build(BuildContext context) {
    return new StreamBuilder<FirebaseUser>(
      stream: FirebaseAuth.instance.onAuthStateChanged,
      builder: (BuildContext context, snapshot) {
        if (snapshot.connectionState == ConnectionState.waiting) {
          return new Container(
            color: Colors.white,
          );
        } else {
          if (snapshot.hasData) {
            return new Home(
              firebaseUser: snapshot.data,
            );
          } else {
            return OnBoarding();
          }
        }
      },
```
**flutter v 1.10.2**

![BPbAu](https://user-images.githubusercontent.com/31619962/65446129-62e3a180-de3c-11e9-8782-9b1284cce4e1.png)

## Logs

```
flutter run --verbose
[  +45 ms] executing: [E:\firefox\flutter_windows_v1.5.4-hotfix.2-stable\flutter\] git -c
log.showSignature=false log -n 1 --pretty=format:%H
[ +439 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[  +65 ms] f5733f7a62ebc7c2ba324a2b410cd81215956b7d
[   +2 ms] executing: [E:\firefox\flutter_windows_v1.5.4-hotfix.2-stable\flutter\] git describe --match
v*.*.* --first-parent --long --tags
[ +127 ms] Exit code 0 from: git describe --match v*.*.* --first-parent --long --tags
[   +1 ms] v1.10.2-0-gf5733f7a6
[  +52 ms] executing: [E:\firefox\flutter_windows_v1.5.4-hotfix.2-stable\flutter\] git rev-parse
--abbrev-ref --symbolic @{u}
[ +593 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[   +1 ms] origin/dev
[        ] executing: [E:\firefox\flutter_windows_v1.5.4-hotfix.2-stable\flutter\] git ls-remote --get-url
origin
[ +110 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[ +119 ms] executing: [E:\firefox\flutter_windows_v1.5.4-hotfix.2-stable\flutter\] git rev-parse
--abbrev-ref HEAD
[  +64 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] dev
[ +433 ms] executing: C:\Users\griffins\Downloads\sdk\platform-tools\adb.exe devices -l
[  +32 ms] Exit code 0 from: C:\Users\griffins\Downloads\sdk\platform-tools\adb.exe devices -l
[        ] List of devices attached
[  +15 ms] No supported devices connected.
[ +566 ms] "flutter run" took 562ms.

#0      throwToolExit (package:flutter_tools/src/base/common.dart:28:3)
#1      RunCommand.validateCommand (package:flutter_tools/src/commands/run.dart:268:7)
<asynchronous suspension>
#2      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:465:11)
<asynchronous suspension>
#3      FlutterCommand.run.<anonymous closure>
(package:flutter_tools/src/runner/flutter_command.dart:407:33)
<asynchronous suspension>
#4      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:154:29)
<asynchronous suspension>
#5      _rootRun (dart:async/zone.dart:1124:13)
#6      _CustomZone.run (dart:async/zone.dart:1021:19)
#7      _runZoned (dart:async/zone.dart:1516:10)
#8      runZoned (dart:async/zone.dart:1463:12)
#9      AppContext.run (package:flutter_tools/src/base/context.dart:153:18)
<asynchronous suspension>
#10     FlutterCommand.run (package:flutter_tools/src/runner/flutter_command.dart:397:20)
#11     CommandRunner.runCommand (package:args/command_runner.dart:197:27)
<asynchronous suspension>
#12     FlutterCommandRunner.runCommand.<anonymous closure>
(package:flutter_tools/src/runner/flutter_command_runner.dart:402:21)
<asynchronous suspension>
#13     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:154:29)
<asynchronous suspension>
#14     _rootRun (dart:async/zone.dart:1124:13)
#15     _CustomZone.run (dart:async/zone.dart:1021:19)
#16     _runZoned (dart:async/zone.dart:1516:10)
#17     runZoned (dart:async/zone.dart:1463:12)
#18     AppContext.run (package:flutter_tools/src/base/context.dart:153:18)
<asynchronous suspension>
#19     FlutterCommandRunner.runCommand
(package:flutter_tools/src/runner/flutter_command_runner.dart:356:19)
<asynchronous suspension>
#20     CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:112:25)
#21     new Future.sync (dart:async/future.dart:224:31)
#22     CommandRunner.run (package:args/command_runner.dart:112:14)
#23     FlutterCommandRunner.run (package:flutter_tools/src/runner/flutter_command_runner.dart:242:18)
#24     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:63:22)
<asynchronous suspension>
#25     _rootRun (dart:async/zone.dart:1124:13)
#26     _CustomZone.run (dart:async/zone.dart:1021:19)
#27     _runZoned (dart:async/zone.dart:1516:10)
#28     runZoned (dart:async/zone.dart:1500:12)
#29     run.<anonymous closure> (package:flutter_tools/runner.dart:61:18)
<asynchronous suspension>
#30     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:154:29)
<asynchronous suspension>
#31     _rootRun (dart:async/zone.dart:1124:13)
#32     _CustomZone.run (dart:async/zone.dart:1021:19)
#33     _runZoned (dart:async/zone.dart:1516:10)
#34     runZoned (dart:async/zone.dart:1463:12)
#35     AppContext.run (package:flutter_tools/src/base/context.dart:153:18)
<asynchronous suspension>
#36     runInContext (package:flutter_tools/src/context_runner.dart:61:24)
<asynchronous suspension>
#37     run (package:flutter_tools/runner.dart:50:10)
#38     main (package:flutter_tools/executable.dart:65:9)
<asynchronous suspension>
#39     main
(file:///E:/firefox/flutter_windows_v1.5.4-hotfix.2-stable/flutter/packages/flutter_tools/bin/flutter_tools.dart:8:3)
#40     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:303:32)
#41     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:12)



```

```
```

**flutter doctor -v**
```
flutter doctor -v
[√] Flutter (Channel dev, v1.10.2, on Microsoft Windows [Version 10.0.17763.503], locale en-US)
    • Flutter version 1.10.2 at E:\firefox\flutter_windows_v1.5.4-hotfix.2-stable\flutter
    • Framework revision f5733f7a62 (12 days ago), 2019-09-11 21:03:42 -0700
    • Engine revision 7ea9884ab0
    • Dart version 2.5.0 (build 2.5.0-dev.4.0 be66176534)


[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at C:\Users\griffins\Downloads\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 28.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)
    • All Android licenses accepted.

[√] Android Studio (version 3.5)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 39.0.3
    • Dart plugin version 191.8423
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)

[√] IntelliJ IDEA Community Edition (version 2019.1)
    • IntelliJ at C:\Users\griffins\AppData\Local\JetBrains\IntelliJ IDEA Community Edition 2019.1.1
    • Flutter plugin version 35.3.2
    • Dart plugin version 191.7019

[√] VS Code (version 1.38.1)
    • VS Code at C:\Users\griffins\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.4.1

[!] Connected device
    ! No devices available

! Doctor found issues in 1 category.
```

**Comment by goderbauer** [comment]
Can you post a runnable minimal code snippet that we can copy and run to reproduce the error?

**Comment by ggichure** [comment]
i cant single out sample code...i'm still trying to figure out what caused the crash .

**Comment by TahaTesser** [comment]
Hi @ggichure 
Closing as there are not sufficient details to act upon this issue. If the problem persists, please create a new issue and provide the information required in the template.
Thank you

**Comment by arnav1307** [comment]
well if you stop the app and run it again then it will work cause that's what happened with mine
