### ISSUE TITLE
MergeSemantics crashes when wrapping a recognizer-containing TextSpan

### ISSUE THREAD

**Issue by Piinks** [flutter/flutter#41134]
When wrapping a  `RichText` (and its `TextSpan` children) with `MergeSemantics`, a crash will be triggered if one of the `TextSpan`s has a `recognizer` set.

## Steps to Reproduce

Run this:

```dart
import 'package:flutter/gestures.dart';
import 'package:flutter/material.dart';
import 'package:url_launcher/url_launcher.dart' as launcher;

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) => MaterialApp(
    home: MyHomePage(title: 'Demo'));
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key key, this.title}) : super(key: key);
  final String title;
  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: Text(widget.title)),
      body: Center(
        child: MergeSemantics(
          child: RichText(
            text: TextSpan(
              style: TextStyle(color: Colors.black87),
              children: <TextSpan>[
                TextSpan(text: 'Visit'),
                TextSpan(
                  text: 'Flutter',
                  style: TextStyle(color: Colors.blue),
                  recognizer: TapGestureRecognizer()
                    ..onTap = () => launcher.launch('https://flutter.dev/'),
                ),
              ],
            ),
          ),
        )
      ),
    );
  }
}

```

## Logs

```
flutter: ══╡ EXCEPTION CAUGHT BY SCHEDULER LIBRARY ╞═════════════════════════════════════════════════════════
flutter: The following assertion was thrown during a scheduler callback:
flutter: 'package:flutter/src/semantics/semantics.dart': Failed assertion: line 2607 pos 16: 'node.parent ==
flutter: null || !node.parent.isPartOfNodeMerging || node.isMergedIntoParent': is not true.
flutter:
flutter: Either the assertion indicates an error in the framework itself, or we should provide substantially
flutter: more information in this error message to help you determine and fix the underlying cause.
flutter: In either case, please report this assertion by filing a bug on GitHub:
flutter:   https://github.com/flutter/flutter/issues/new?template=BUG.md
flutter:
flutter: When the exception was thrown, this was the stack:
flutter: #2      SemanticsOwner.sendSemanticsUpdate 
package:flutter/…/semantics/semantics.dart:2607
flutter: #3      PipelineOwner.flushSemantics 
package:flutter/…/rendering/object.dart:1039
flutter: #4      RendererBinding.drawFrame 
package:flutter/…/rendering/binding.dart:344
flutter: #5      WidgetsBinding.drawFrame 
package:flutter/…/widgets/binding.dart:776
flutter: #6      RendererBinding._handlePersistentFrameCallback 
package:flutter/…/rendering/binding.dart:279
flutter: #7      SchedulerBinding._invokeFrameCallback 
package:flutter/…/scheduler/binding.dart:1040
flutter: #8      SchedulerBinding.handleDrawFrame 
package:flutter/…/scheduler/binding.dart:982
flutter: #9      SchedulerBinding.scheduleWarmUpFrame.<anonymous closure> 
package:flutter/…/scheduler/binding.dart:791
flutter: #18     _Timer._runTimers  (dart:isolate-patch/timer_impl.dart:382:19)
flutter: #19     _Timer._handleMessage  (dart:isolate-patch/timer_impl.dart:416:5)
flutter: #20     _RawReceivePortImpl._handleMessage  (dart:isolate-patch/isolate_patch.dart:172:12)
flutter: (elided 10 frames from class _AssertionError, package dart:async, and package dart:async-patch)
flutter: ════════════════════════════════════════════════════════════════════════════════════════════════════
[VERBOSE-2:ui_dart_state.cc(148)] Unhandled Exception: Bad state: Future already completed
#0      _AsyncCompleter.complete  (dart:async/future_impl.dart:39:31)
#1      WidgetsBinding.drawFrame.<anonymous closure> 
package:flutter/…/widgets/binding.dart:769
#2      _rootRunUnary  (dart:async/zone.dart:1136:13)
#3      _CustomZone.runUnary  (dart:async/zone.dart:1029:19)
#4      _CustomZone.runUnaryGuarded  (dart:async/zone.dart:931:7)
#5      _invoke1  (dart:ui/hooks.dart:265:10)
#6      _reportTimings  (dart:ui/hooks.dart:203:3)
[VERBOSE-2:ui_dart_state.cc(148)] Unhandled Exception: Bad state: Future already completed
#0      _AsyncCompleter.complete  (dart:async/future_impl.dart:39:31)
#1      WidgetsBinding.drawFrame.<anonymous closure> 
package:flutter/…/widgets/binding.dart:769
#2      _rootRunUnary  (dart:async/zone.dart:1136:13)
#3      _CustomZone.runUnary  (dart:async/zone.dart:1029:19)
#4      _CustomZone.runUnaryGuarded  (dart:async/zone.dart:931:7)
#5      _invoke1  (dart:ui/hooks.dart:265:10)
#6      _reportTimings  (dart:ui/hooks.dart:203:3)

════════ Exception caught by scheduler library ═════════════════════════════════
The following assertion was thrown during a scheduler callback:
'package:flutter/src/semantics/semantics.dart': Failed assertion: line 2607 pos 16: 'node.parent == null || !node.parent.isPartOfNodeMerging || node.isMergedIntoParent': is not true.


Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=BUG.md

When the exception was thrown, this was the stack
#2      SemanticsOwner.sendSemanticsUpdate 
package:flutter/…/semantics/semantics.dart:2607
#3      PipelineOwner.flushSemantics 
package:flutter/…/rendering/object.dart:1039
#4      RendererBinding.drawFrame 
package:flutter/…/rendering/binding.dart:344
#5      WidgetsBinding.drawFrame 
package:flutter/…/widgets/binding.dart:776
#6      RendererBinding._handlePersistentFrameCallback 
package:flutter/…/rendering/binding.dart:279
...
════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by scheduler library ═════════════════════════════════
The following assertion was thrown during a scheduler callback:
'package:flutter/src/semantics/semantics.dart': Failed assertion: line 2607 pos 16: 'node.parent == null || !node.parent.isPartOfNodeMerging || node.isMergedIntoParent': is not true.


Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=BUG.md

When the exception was thrown, this was the stack
#2      SemanticsOwner.sendSemanticsUpdate 
package:flutter/…/semantics/semantics.dart:2607
#3      PipelineOwner.flushSemantics 
package:flutter/…/rendering/object.dart:1039
#4      RendererBinding.drawFrame 
package:flutter/…/rendering/binding.dart:344
#5      WidgetsBinding.drawFrame 
package:flutter/…/widgets/binding.dart:776
#6      RendererBinding._handlePersistentFrameCallback 
package:flutter/…/rendering/binding.dart:279
...
════════════════════════════════════════════════════════════════════════════════

```

```
$ flutter analyze
Analyzing playground...
No issues found! (ran in 2.5s)
```

```
$ flutter doctor -v
Downloading android-arm-profile/darwin-x64 tools...                 0.6s
Downloading android-arm-release/darwin-x64 tools...                 0.3s
Downloading android-arm64-profile/darwin-x64 tools...               0.3s
Downloading android-arm64-release/darwin-x64 tools...               0.3s
[✓] Flutter (Channel master, v1.10.6-pre.33, on Mac OS X 10.14.6 18G95, locale en-US)
    • Flutter version 1.10.6-pre.33 at /Users/katelovett/github/flutter
    • Framework revision 961f1b746d (3 hours ago), 2019-09-23 10:09:38 -0700
    • Engine revision b875c7a5ff
    • Dart version 2.6.0 (build 2.6.0-dev.0.0 7c1821c4aa)


[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/katelovett/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 10.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.1, Build version 10B61
    • CocoaPods version 1.7.2

[✓] Android Studio (version 3.4)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 36.1.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

[✓] IntelliJ IDEA Ultimate Edition (version 2019.1.2)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 39.0.2
    • Dart plugin version 191.8423

[✓] VS Code (version 1.38.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.4.1

[✓] Connected device (1 available)
    • SixthSense • 1c017dd332591e8a3553c3a7ec3f7a6daf2d1d27 • ios • iOS 12.4.1

• No issues found!
```

**Comment by Piinks** [comment]
cc/ @GaryQian and @dnfield

**Comment by fmedlin** [comment]
I can't repro this with the dependencies below. Builds and runs ok.

```
environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  url_launcher: ^5.4.10
```

```
$ flutter doctor -v
[✓] Flutter (Channel stable, v1.17.1, on Mac OS X 10.15.3 19D76, locale en-US)
    • Flutter version 1.17.1 at /Users/fred/repos/flutter
    • Framework revision f7a6a7906b (2 weeks ago), 2020-05-12 18:39:00 -0700
    • Engine revision 6bc433c6b6
    • Dart version 2.8.2

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/fred/Library/Android/sdk
    • Platform android-29, build-tools 29.0.3
    • ANDROID_HOME = /Users/fred/Library/Android/sdk
    • Java binary at: ...
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.5, Build version 11E608c
    • CocoaPods version 1.9.1

[✓] Android Studio (version 4.0)
    • Android Studio at ...
    • Flutter plugin version 45.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
```

**Comment by Piinks** [comment]
Still crashes. Not dependent on the package. :)

```dart
import 'package:flutter/gestures.dart';
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) => MaterialApp(
    home: MyHomePage(title: 'Demo'));
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key key, this.title}) : super(key: key);
  final String title;
  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: Text(widget.title)),
      body: Center(
        child: MergeSemantics(
          child: RichText(
            text: TextSpan(
              style: TextStyle(color: Colors.black87),
              children: <TextSpan>[
                TextSpan(text: 'Visit'),
                TextSpan(
                  text: 'Flutter',
                  style: TextStyle(color: Colors.blue),
                  recognizer: TapGestureRecognizer()
                    ..onTap = () {},
                ),
              ],
            ),
          ),
        )
      ),
    );
  }
}
```

### Stacktrace
```
flutter: ══╡ EXCEPTION CAUGHT BY SCHEDULER LIBRARY ╞═════════════════════════════════════════════════════════
flutter: The following assertion was thrown during a scheduler callback:
flutter: 'package:flutter/src/semantics/semantics.dart': Failed assertion: line 2623 pos 16: 'node.parent ==
flutter: null || !node.parent.isPartOfNodeMerging || node.isMergedIntoParent': is not true.
flutter:
flutter: Either the assertion indicates an error in the framework itself, or we should provide substantially
flutter: more information in this error message to help you determine and fix the underlying cause.
flutter: In either case, please report this assertion by filing a bug on GitHub:
flutter:   https://github.com/flutter/flutter/issues/new?template=BUG.md
flutter:
flutter: When the exception was thrown, this was the stack:
flutter: #2      SemanticsOwner.sendSemanticsUpdate 
package:flutter/…/semantics/semantics.dart:2623
flutter: #3      PipelineOwner.flushSemantics 
package:flutter/…/rendering/object.dart:1087
flutter: #4      RendererBinding.drawFrame 
package:flutter/…/rendering/binding.dart:409
flutter: #5      WidgetsBinding.drawFrame 
package:flutter/…/widgets/binding.dart:867
flutter: #6      RendererBinding._handlePersistentFrameCallback 
package:flutter/…/rendering/binding.dart:286
flutter: #7      SchedulerBinding._invokeFrameCallback 
package:flutter/…/scheduler/binding.dart:1115
flutter: #8      SchedulerBinding.handleDrawFrame 
package:flutter/…/scheduler/binding.dart:1054
flutter: #9      SchedulerBinding.scheduleWarmUpFrame.<anonymous closure> 
package:flutter/…/scheduler/binding.dart:863
flutter: (elided 13 frames from class _AssertionError, class _RawReceivePortImpl, class _Timer, dart:async, and dart:async-patch)
flutter: ════════════════════════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by scheduler library ═════════════════════════════════
The following assertion was thrown during a scheduler callback:
'package:flutter/src/widgets/binding.dart': Failed assertion: line 846 pos 14: '!_firstFrameCompleter.isCompleted': is not true.


Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=BUG.md

When the exception was thrown, this was the stack
#2      WidgetsBinding.drawFrame 
package:flutter/…/widgets/binding.dart:846
#3      RendererBinding._handlePersistentFrameCallback 
package:flutter/…/rendering/binding.dart:286
#4      SchedulerBinding._invokeFrameCallback 
package:flutter/…/scheduler/binding.dart:1115
#5      SchedulerBinding.handleDrawFrame 
package:flutter/…/scheduler/binding.dart:1054
#6      SchedulerBinding._handleDrawFrame 
package:flutter/…/scheduler/binding.dart:970
...
════════════════════════════════════════════════════════════════════════════════
══╡ EXCEPTION CAUGHT BY SCHEDULER LIBRARY ╞═════════════════════════════════════════════════════════
The following assertion was thrown during a scheduler callback:
'package:flutter/src/widgets/binding.dart': Failed assertion: line 846 pos 14:
'!_firstFrameCompleter.isCompleted': is not true.
Either the assertion indicates an error in the framework itself, or we should provide substantially
more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=BUG.md
When the exception was thrown, this was the stack:
#2      WidgetsBinding.drawFrame 
package:flutter/…/widgets/binding.dart:846
#3      RendererBinding._handlePersistentFrameCallback 
package:flutter/…/rendering/binding.dart:286
#4      SchedulerBinding._invokeFrameCallback 
package:flutter/…/scheduler/binding.dart:1115
#5      SchedulerBinding.handleDrawFrame 
package:flutter/…/scheduler/binding.dart:1054
#6      SchedulerBinding._handleDrawFrame 
package:flutter/…/scheduler/binding.dart:970
#10     _invoke  (dart:ui/hooks.dart:253:10)
#11     _drawFrame  (dart:ui/hooks.dart:211:3)
(elided 5 frames from class _AssertionError and dart:async)
════════════════════════════════════════════════════════════════════════════════════════════════════
[VERBOSE-2:ui_dart_state.cc(166)] Unhandled Exception: Build scheduled during frame.
While the widget tree was being built, laid out, and painted, a new frame was scheduled to rebuild the widget tree.
This might be because setState() was called from a layout or paint callback. If a change is needed to the widget tree, it should be applied as the tree is being built. Scheduling a change for the subsequent frame instead results in an interface that lags behind by one frame. If this was done to make your build dependent on a size measured at layout time, consider using a LayoutBuilder, CustomSingleChildLayout, or CustomMultiChildLayout. If, on the other hand, the one frame delay is the desired effect, for example because this is an animation, consider scheduling the frame in a post-frame callback using SchedulerBinding.addPostFrameCallback or using an AnimationController to trigger the animation.
#0      WidgetsBinding._handleBuildScheduled.<anonymous closure> (package:flutter/src/widgets/binding.dart:7<…>
Another exception was thrown: 'package:flutter/src/widgets/binding.dart': Failed assertion: line 838 pos 12: '!debugBuildingDirtyElements': is not true.

════════ Exception caught by scheduler library ═════════════════════════════════
'package:flutter/src/widgets/binding.dart': Failed assertion: line 838 pos 12: '!debugBuildingDirtyElements': is not true.
════════════════════════════════════════════════════════════════════════════════
```

### flutter doctor
```
[✓] Flutter (Channel master, 1.19.0-6.0.pre.12, on Mac OS X 10.15.4 19E287, locale en-US)
    • Flutter version 1.19.0-6.0.pre.12 at /Users/katelovett/github/flutter
    • Framework revision 496556eb70 (7 minutes ago), 2020-06-24 14:51:39 -0700
    • Engine revision 291dab6f17
    • Dart version 2.9.0 (build 2.9.0-18.0.dev d8eb844e5d)

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/katelovett/Library/Android/sdk
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.3.1, Build version 11C505
    • CocoaPods version 1.9.1

[✓] Android Studio (version 3.4)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 36.1.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

[✓] VS Code (version 1.45.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.11.0

[✓] Connected device (1 available)
    • iPhone 11 Pro Max • A8FFA716-A67B-4468-B92B-F2B61F2306A0 • ios • com.apple.CoreSimulator.SimRuntime.iOS-13-3 (simulator)
```

**Comment by TahaTesser** [comment]
<details> 
<summary>flutter doctor -v</summary> 

``` 
[✓] Flutter (Channel dev, 1.20.0-2.0.pre, on Mac OS X 10.15.5 19F101, locale
    en-GB)
    • Flutter version 1.20.0-2.0.pre at /Users/tahatesser/Code/flutter_dev
    • Framework revision 15a28159bc (6 days ago), 2020-06-23 04:52:58 -0700
    • Engine revision 91a63d6a44
    • Dart version 2.9.0 (build 2.9.0-19.0.dev 7e72c9ae7e)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
    • Android SDK at /Users/tahatesser/Code/sdk
    • Platform android-30, build-tools 30.0.0
    • ANDROID_HOME = /Users/tahatesser/Code/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.5, Build version 11E608c
    • CocoaPods version 1.9.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 47.0.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.46.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.12.0

[✓] Connected device (4 available)
    • SM M305F      • 32003c30dc19668f • android-arm64  • Android 10 (API 29)
    • macOS desktop • macos            • darwin-x64     • Mac OS X 10.15.5
      19F101
    • Web Server    • web-server       • web-javascript • Flutter Tools
    • Chrome        • chrome           • web-javascript • Google Chrome
      83.0.4103.116

• No issues found!

``` 

</details>

**Comment by Piinks** [comment]
Hey there! IIRC, the native behavior is that the screen reader will read the entire paragraph, notating the `link` as it read it.
Currently, the link is a separate node, so the reader stops when it reaches the link. The user needs to manually progress forward to the `link`, and then manually progress forward again to continue through the rest of the paragraph.

So in the case of the OP above, it would read `Visit`, and stop. Then you would need to trigger the next to be read, `Flutter (link)`. Ideally it would just read together `Visit Flutter (link).`, and the link is navigable as part of the native a11y interface.

**Comment by chunhtai** [comment]
This is fixed
