### ISSUE TITLE
flutter --no-color run --machine --track-widget-creation --device-id=chrome lib\main.dart

### ISSUE THREAD

**Issue by Avinash-Royal** [flutter/flutter#41179]
## exception
```
ChromeDebugException: Unexpected error from chrome devtools:
text: Uncaught
exception:
  description: ReferenceError: require is not defined
    at <anonymous>:1:1
  type: object
  value: null
attempted JS eval: `require('dart_sdk').dart.getLibraries();`
```

```
#0      handleErrorIfPresent (package:dwds/src/services/chrome_proxy_service.dart:569:5)
#1      AppInspector._getLibraryRefs (package:dwds/src/debugging/inspector.dart:489:5)
<asynchronous suspension>
#2      AppInspector._initialize (package:dwds/src/debugging/inspector.dart:72:36)
<asynchronous suspension>
#3      AppInspector.initialize (package:dwds/src/debugging/inspector.dart:108:21)
#4      _AsyncAwaitCompleter.start (dart:async-patch/async_patch.dart:43:6)
#5      AppInspector.initialize (package:dwds/src/debugging/inspector.dart:84:41)
#6      ChromeProxyService.createIsolate (package:dwds/src/services/chrome_proxy_service.dart:112:37)
#7      _AsyncAwaitCompleter.start (dart:async-patch/async_patch.dart:43:6)
#8      ChromeProxyService.createIsolate (package:dwds/src/services/chrome_proxy_service.dart:106:29)
#9      DevHandler._handleConnection.<anonymous closure> (package:dwds/src/handlers/dev_handler.dart:265:17)
#10     _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:71:64)
#11     _rootRunUnary (dart:async/zone.dart:1132:38)
#12     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#13     _FutureListener.handleValue (dart:async/future_impl.dart:137:18)
#14     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:678:45)
#15     Future._propagateToListeners (dart:async/future_impl.dart:707:32)
#16     Future._addListener.<anonymous closure> (dart:async/future_impl.dart:387:9)
#17     _rootRun (dart:async/zone.dart:1124:13)
#18     _CustomZone.run (dart:async/zone.dart:1021:19)
#19     _CustomZone.runGuarded (dart:async/zone.dart:923:7)
#20     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:963:23)
#21     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#22     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#23     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:116:13)
#24     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:173:5)
```

## flutter doctor

```
[✓] Flutter (Channel dev, v1.10.5, on Microsoft Windows [Version 10.0.18362.356], locale en-US)
    • Flutter version 1.10.5 at C:\Users\SoftAge\AndroidStudioProjects\flutter
    • Framework revision 3cf88fed6d (5 days ago), 2019-09-18 23:09:41 -0400
    • Engine revision 33ad6757e8
    • Dart version 2.6.0 (build 2.6.0-dev.1.0 cb80ea7ba9)

[!] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at C:\Users\SoftAge\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
    ✗ Android license status unknown.
      Try re-installing or updating your Android SDK Manager.
      See https://developer.android.com/studio/#downloads or visit https://flutter.dev/setup/#android-setup for detailed instructions.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[✓] Android Studio (version 3.4)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 39.0.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

[✓] IntelliJ IDEA Ultimate Edition (version 2019.2)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA
    • Flutter plugin version 39.0.5
    • Dart plugin version 192.6603.23

[✓] VS Code (version 1.38.1)
    • VS Code at C:\Users\SoftAge\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.4.1

[✓] Connected device (2 available)
    • Chrome • chrome • web-javascript • Google Chrome 77.0.3865.90
    • Server • web    • web-javascript • Flutter Tools

! Doctor found issues in 1 category.
```

**Comment by janmoppel** [comment]
Hello @Avinash-Royal !

Thank you for posting an issue.
This problem has been already reported and discussed here: https://github.com/dart-lang/webdev/issues/663
It should be resolved in this PR: https://github.com/dart-lang/webdev/pull/670. Try to update the `dwds` version to `0.6.2`.

Closing this issue for now. However, if proposed solution won't work for you, please feel free to open a new issue.

Thank you.
