### ISSUE TITLE
a Localizations ancestor was not found, scope != null

### ISSUE THREAD

**Issue by kasp1** [flutter/flutter#41205]
Hi there, I get the following error, not sure what may be wrong? The context seem to be legit.

```Launching lib\main.dart on Redmi 4X in debug mode...
Built build\app\outputs\apk\debug\app-debug.apk.
I/FA      ( 4800): Tag Manager is not found and thus will not be used
I/OpenGLRenderer( 4800): Initialized EGL, version 1.4
D/OpenGLRenderer( 4800): Swap behavior 1
I/Choreographer( 4800): Skipped 48 frames!  The application may be doing too much work on its main thread.
I/flutter ( 4800): ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
I/flutter ( 4800): The following assertion was thrown building App(dirty, state: AppState#0cb82):
I/flutter ( 4800): a Localizations ancestor was not found
I/flutter ( 4800): 'package:flutter/src/widgets/localizations.dart':
I/flutter ( 4800): Failed assertion: line 417 pos 12: 'scope != null'
I/flutter ( 4800):
I/flutter ( 4800): Either the assertion indicates an error in the framework itself, or we should provide substantially
I/flutter ( 4800): more information in this error message to help you determine and fix the underlying cause.
I/flutter ( 4800): In either case, please report this assertion by filing a bug on GitHub:
I/flutter ( 4800):   https://github.com/flutter/flutter/issues/new?template=BUG.md
I/flutter ( 4800):
I/flutter ( 4800): User-created ancestor of the error-causing widget was:
[38;5;248mI/flutter ( 4800):   Main[39;49m
I/flutter ( 4800):
I/flutter ( 4800): When the exception was thrown, this was the stack:
[38;5;244mI/flutter ( 4800): #2      Localizations.localeOf[39;49m
[38;5;248mI/flutter ( 4800): #3      AppState.build[39;49m
[38;5;244mI/flutter ( 4800): #4      StatefulElement.build[39;49m
[38;5;244mI/flutter ( 4800): #5      ComponentElement.performRebuild[39;49m
[38;5;244mI/flutter ( 4800): #6      Element.rebuild[39;49m
[38;5;244mI/flutter ( 4800): #7      ComponentElement._firstBuild[39;49m
[38;5;244mI/flutter ( 4800): #8      StatefulElement._firstBuild[39;49m
[38;5;244mI/flutter ( 4800): #9      ComponentElement.mount[39;49m
[38;5;244mI/flutter ( 4800): #10     Element.inflateWidget[39;49m
[38;5;244mI/flutter ( 4800): #11     Element.updateChild[39;49m
[38;5;244mI/flutter ( 4800): #12     ComponentElement.performRebuild[39;49m
[38;5;244mI/flutter ( 4800): #13     Element.rebuild[39;49m
[38;5;244mI/flutter ( 4800): #14     ComponentElement._firstBuild[39;49m
[38;5;244mI/flutter ( 4800): #15     ComponentElement.mount[39;49m
[38;5;244mI/flutter ( 4800): #16     Element.inflateWidget[39;49m
[38;5;244mI/flutter ( 4800): #17     Element.updateChild[39;49m
[38;5;244mI/flutter ( 4800): #18     RenderObjectToWidgetElement._rebuild[39;49m
[38;5;244mI/flutter ( 4800): #19     RenderObjectToWidgetElement.mount[39;49m
[38;5;244mI/flutter ( 4800): #20     RenderObjectToWidgetAdapter.attachToRenderTree.<anonymous closure>[39;49m
[38;5;244mI/flutter ( 4800): #21     BuildOwner.buildScope[39;49m
[38;5;244mI/flutter ( 4800): #22     RenderObjectToWidgetAdapter.attachToRenderTree[39;49m
[38;5;244mI/flutter ( 4800): #23     WidgetsBinding.attachRootWidget[39;49m
[38;5;244mI/flutter ( 4800): #24     WidgetsBinding.scheduleAttachRootWidget.<anonymous closure>[39;49m
[38;5;244mI/flutter ( 4800): #33     _Timer._runTimers  (dart:isolate-patch/timer_impl.dart:382:19)[39;49m
[38;5;244mI/flutter ( 4800): #34     _Timer._handleMessage  (dart:isolate-patch/timer_impl.dart:416:5)[39;49m
[38;5;244mI/flutter ( 4800): #35     _RawReceivePortImpl._handleMessage  (dart:isolate-patch/isolate_patch.dart:172:12)[39;49m
I/flutter ( 4800): (elided 10 frames from class _AssertionError, package dart:async, and package dart:async-patch)
I/flutter ( 4800):
I/flutter ( 4800): ════════════════════════════════════════════════════════════════════════════════════════════════════
```

Code excerpt:

```
void main() => runApp(Main());

class Main extends StatelessWidget {
  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) => App();
}

class App extends StatefulWidget {
  @override
  AppState createState() => AppState();
}

class AppState extends State<App> {
  @override
  Widget build(BuildContext context) {
    Wakelock.enable();

    Locale myLocale = Localizations.localeOf(context);
    print(myLocale.languageCode);
    // ...
```

the Doc:

```
flutter doctor -v
[√] Flutter (Channel master, v1.10.4-pre.8, on Microsoft Windows [Version 10.0.17763.737], locale en-US)
    • Flutter version 1.10.4-pre.8 at C:\flutter
    • Framework revision 64300123fa (11 days ago), 2019-09-13 19:46:58 -0700
    • Engine revision 00c8941dae
    • Dart version 2.6.0 (build 2.6.0-dev.0.0 a554c8be6b)

[!] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at C:\Users\Mirek\AppData\Local\Android\Sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = C:\Users\Mirek\AppData\Local\Android\Sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[!] Android Studio (version 3.4)
    • Android Studio at C:\Program Files\Android\Android Studio
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

[√] VS Code (version 1.38.1)
    • VS Code at C:\Users\Mirek\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.4.1

[√] Connected device (3 available)
    • Redmi 4X • 7c526f907cf4 • android-arm64  • Android 7.1.2 (API 25)
    • Chrome   • chrome       • web-javascript • Google Chrome 77.0.3865.90
    • Server   • web          • web-javascript • Flutter Tools

! Doctor found issues in 2 categories.
```

**Comment by escamoteur** [comment]
You have to use a MaterialApp or CupertinoApp to use Locales.

Please ask questions like that on stackoverflow. We cannot provide personal support here. Thanks!

**Comment by dpedrinha** [comment]
And it also must be called after the MaterialApp.

It won't work if you call it from a ChangeNotifierProvider model if it is a parent of MaterialApp. It needs to be a child of MaterialApp.
