### ISSUE TITLE
Crash with "Could not decompress image"

### ISSUE THREAD

**Issue by tp** [flutter/flutter#41290]
## Steps to Reproduce

We have an app that shows around 20 200*400px images per page. When I push additional pages ("going deeper") the total memory observed in the DevTools increases slightly, but overall caps at around 200 MB in out tests.

We've been hunting for the root cause of our crashes (most probably related to images) for a while now, going through all the known issues here in the repository. Unfortunately nothing helped so far, and we still see random crashes "out of nowhere', as the 200 MB memory usage should be fine on the iPhone 6S I am using.

Sadly I don't have a repro for the crasher. When I open the same page a second time (presumably loading the same images), it works fine.

## Logs

(Profile mode)
```
[   +4 ms] [VERBOSE-2:image_decoder.cc(242)] Could not decompress image.
[+2580 ms] Service protocol connection closed.
[   +1 ms] Lost connection to device.
```

```
No issues found! (ran in 8.0s)
```

```
[✓] Flutter (Channel unknown, v1.9.1+hotfix.2, on Mac OS X 10.14.6 18G95, locale en-DE)
    • Flutter version 1.9.1+hotfix.2 at /Users/timm/Downloads/flutter
    • Framework revision 2d2a1ffec9 (3 weeks ago), 2019-09-06 18:39:49 -0700
    • Engine revision b863200c37
    • Dart version 2.5.0

[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/setup/#android-setup for detailed instructions).
      If the Android SDK has been installed to a custom location, set ANDROID_HOME to that location.
      You may also want to add it to your PATH environment variable.


[✓] Xcode - develop for iOS and macOS (Xcode 10.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.3, Build version 10G8
    • CocoaPods version 1.7.5

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/setup/#android-setup for detailed instructions).

[✓] VS Code
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.4.1

[✓] Connected device (2 available)
    • AYM 6S    • 6f9f0bff76efd5e933be41f3b2d5075889d8a6ee • ios • iOS 12.2
    • iPhone Xʀ • CF08B5D5-EDF9-4D0F-83FB-8A79A141EFFC     • ios • com.apple.CoreSimulator.SimRuntime.iOS-12-4 (simulator)
```

Full crash log from the iPhone is here: https://gist.github.com/tp/e4f03cb5bbfb3b63c9af843099ac911d

When I run the app later with `flutter run --verbose` it ends with these lines:

```
[  +41 ms] [VERBOSE-2:image_decoder.cc(242)] Could not decompress image.
[ +157 ms] flutter: ══╡ EXCEPTION CAUGHT BY IMAGE RESOURCE SERVICE ╞════════════════════════════════════════════════════
[        ] flutter: The following _Exception was thrown resolving an image frame:
[        ] flutter: Exception: operation failed
[        ] flutter:
[        ] flutter: When the exception was thrown, this was the stack:
[        ] flutter: #0      MultiFrameImageStreamCompleter._decodeNextFrameAndSchedule (package:flutter/src/painting/image_stream.dart:680:20)
[        ] flutter: <asynchronous suspension>
[        ] flutter: #1      MultiFrameImageStreamCompleter._handleCodecReady (package:flutter/src/painting/image_stream.dart:644:7)
[        ] flutter: #10     NetworkToFileImage._loadAsync (package:network_to_file_image/network_to_file_image.dart)
[        ] flutter: <asynchronous suspension>
[        ] flutter: #11     NetworkToFileImage.load (package:network_to_file_image/network_to_file_image.dart:108:16)
[        ] flutter: #12     ImageProvider.resolve.<anonymous closure>.<anonymous closure>.<anonymous closure>
(package:flutter/src/painting/image_provider.dart:316:48)
[        ] flutter: #13     ImageCache.putIfAbsent (package:flutter/src/painting/image_cache.dart:160:22)
[        ] flutter: #14     ImageProvider.resolve.<anonymous closure>.<anonymous closure> (package:flutter/src/painting/image_provider.dart:316:25)
[  +24 ms] flutter: #15     SynchronousFuture.then (package:flutter/src/foundation/synchronous_future.dart:38:29)
[        ] flutter: #16     ImageProvider.resolve.<anonymous closure> (package:flutter/src/painting/image_provider.dart:313:11)
[        ] flutter: #20     ImageProvider.resolve (package:flutter/src/painting/image_provider.dart:305:16)
[        ] flutter: #21     _ImageState._resolveImage (package:flutter/src/widgets/image.dart:951:20)
[        ] flutter: #22     _ImageState.didChangeDependencies (package:flutter/src/widgets/image.dart:908:5)
[        ] flutter: #23     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4086:12)
[        ] flutter: #24     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3919:5)
[        ] flutter: #25     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3101:14)
[        ] flutter: #26     Element.updateChild (package:flutter/src/widgets/framework.dart:2904:12)
[        ] flutter: #27     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5127:14)
[        ] flutter: #28     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3101:14)
[        ] flutter: #29     Element.updateChild (package:flutter/src/widgets/framework.dart:2904:12)
[        ] flutter: #30     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5127:14)
[        ] flutter: #31     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3101:14)
[        ] flutter: #32     Element.updateChild (package:flutter/src/widgets/framework.dart:2904:12)
[        ] flutter: #33     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3961:16)
[        ] flutter: #34     Element.rebuild (package:flutter/src/widgets/framework.dart:3738:5)
[        ] flutter: #35     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3924:5)
[        ] flutter: #36     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3919:5)
[        ] flutter: #37     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3101:14)
[        ] flutter: #38     Element.updateChild (package:flutter/src/widgets/framework.dart:2904:12)
[        ] flutter: #39     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3961:16)
[        ] flutter: #40     Element.rebuild (package:flutter/src/widgets/framework.dart:3738:5)
[        ] flutter: #41     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3924:5)
[        ] flutter: #42     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3919:5)
[        ] flutter: #43     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3101:14)
[        ] flutter: #44     Element.updateChild (package:flutter/src/widgets/framework.dart:2904:12)
[        ] flutter: #45     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5127:14)
[        ] flutter: #46     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3101:14)
[        ] flutter: #47     Element.updateChild (package:flutter/src/widgets/framework.dart:2904:12)
[        ] flutter: #48     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3961:16)
[        ] flutter: #49     Element.rebuild (package:flutter/src/widgets/framework.dart:3738:5)
[        ] flutter: #50     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3924:5)
[        ] flutter: #51     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3919:5)
[        ] flutter: #52     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3101:14)
[        ] flutter: #53     MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5233:32)
[        ] flutter: #54     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3101:14)
[        ] flutter: #55     Element.updateChild (package:flutter/src/widgets/framework.dart:2904:12)
[        ] flutter: #56     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5127:14)
[        ] flutter: #57     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3101:14)
[        ] flutter: #58     MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5233:32)
[        ] flutter: #59     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3101:14)
[        ] flutter: #60     Element.updateChild (package:flutter/src/widgets/framework.dart:2904:12)
[        ] flutter: #61     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3961:16)
[        ] flutter: #62     Element.rebuild (package:flutter/src/widgets/framework.dart:3738:5)
[        ] flutter: #63     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3924:5)
[        ] flutter: #64     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3919:5)
[        ] flutter: #65     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3101:14)
[        ] flutter: #66     Element.updateChild (package:flutter/src/widgets/framework.dart:2904:12)
[        ] flutter: #67     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5127:14)
[        ] flutter: #68     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3101:14)
[        ] flutter: #69     Element.updateChild (package:flutter/src/widgets/framework.dart:2904:12)
[        ] flutter: #70     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3961:16)
[        ] flutter: #71     Element.rebuild (package:flutter/src/widgets/framework.dart:3738:5)
[        ] flutter: #72     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3924:5)
[        ] flutter: #73     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3919:5)
[        ] flutter: #74     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3101:14)
[        ] flutter: #75     Element.updateChild (package:flutter/src/widgets/framework.dart:2904:12)
[        ] flutter: #76     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5127:14)
[        ] flutter: #77     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3101:14)
[        ] flutter: #78     Element.updateChild (package:flutter/src/widgets/framework.dart:2904:12)
[        ] flutter: #79     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3961:16)
[        ] flutter: #80     Element.rebuild (package:flutter/src/widgets/framework.dart:3738:5)
[        ] flutter: #81     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3924:5)
[        ] flutter: #82     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3919:5)
[        ] flutter: #83     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3101:14)
[        ] flutter: #84     Element.updateChild (package:flutter/src/widgets/framework.dart:2904:12)
[        ] flutter: #85     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5127:14)
[        ] flutter: #86     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3101:14)
[        ] flutter: #87     Element.updateChild (package:flutter/src/widgets/framework.dart:2904:12)
[        ] flutter: #88     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3961:16)
[        ] flutter: #89     Element.rebuild (package:flutter/src/widgets/framework.dart:3738:5)
[        ] flutter: #90     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3924:5)
[        ] flutter: #91     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4088:11)
[        ] flutter: #92     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3919:5)
[        ] flutter: #93     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3101:14)
[        ] flutter: #94     Element.updateChild (package:flutter/src/widgets/framework.dart:2904:12)
[        ] flutter: #95     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3961:16)
[        ] flutter: #96     Element.rebuild (package:flutter/src/widgets/framework.dart:3738:5)
[        ] flutter: #97     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3924:5)
[        ] flutter: #98     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3919:5)
[        ] flutter: #99     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3101:14)
[        ] flutter: #100    Element.updateChild (package:flutter/src/widgets/framework.dart:2904:12)
[        ] flutter: #101    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3961:16)
[        ] flutter: #102    Element.rebuild (package:flutter/src/widgets/framework.dart:3738:5)
[        ] flutter: #103    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3924:5)
[        ] flutter: #104    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3919:5)
[        ] flutter: #105    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3101:14)
[        ] flutter: #106    Element.updateChild (package:flutter/src/widgets/framework.dart:2904:12)
[        ] flutter: #107    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3961:16)
[        ] flutter: #108    Element.rebuild (package:flutter/src/widgets/framework.dart:3738:5)
[        ] flutter: #109    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3924:5)
[  +12 ms] flutter: #110    StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4088:11)
[        ] flutter: #111    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3919:5)
[        ] flutter: #112    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3101:14)
[        ] flutter: #113    Element.updateChild (package:flutter/src/widgets/framework.dart:2904:12)
[        ] flutter: #114    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3961:16)
[        ] flutter: #115    Element.rebuild (package:flutter/src/widgets/framework.dart:3738:5)
[        ] flutter: #116    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3924:5)
[        ] flutter: #117    StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4088:11)
[        ] flutter: #118    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3919:5)
[        ] flutter: #119    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3101:14)
[        ] flutter: #120    MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5233:32)
[        ] flutter: #121    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3101:14)
[        ] flutter: #122    Element.updateChild (package:flutter/src/widgets/framework.dart:2904:12)
[        ] flutter: #123    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3961:16)
[        ] flutter: #124    Element.rebuild (package:flutter/src/widgets/framework.dart:3738:5)
[        ] flutter: #125    BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2348:33)
[        ] flutter: #126    WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:760:20)
[        ] flutter: #127    RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:280:5)
[        ] flutter: #128    SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1033:15)
[        ] flutter: #129    SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:975:9)
[        ] flutter: #130    SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:891:5)
[        ] flutter: #134    _invoke (dart:ui/hooks.dart:249:10)
[        ] flutter: #135    _drawFrame (dart:ui/hooks.dart:207:3)
[        ] flutter: (elided 14 frames from package dart:async and package dart:async-patch)
[  +13 ms] flutter:
[        ] flutter: Image provider:
[        ] flutter:
NetworkToFileImage("/var/mobile/Containers/Data/Application/BBD92A81-9952-4F07-BB65-D25965F4D2F4/Library/b09791c37f0a28878efca10c58e7d21f.jpg",
[        ] flutter: "https://cdn.aboutstatic.com/file/b09791c37f0a28878efca10c58e7d21f?width=800&quality=75&transparent=1",
[        ] flutter: scale: 1.0)
[        ] flutter: File:
[        ] flutter: /var/mobile/Containers/Data/Application/BBD92A81-9952-4F07-BB65-D25965F4D2F4/Library/b09791c37f0a28878efca10c58e7d21f.jpg
[        ] flutter: Url:
[        ] flutter: https://cdn.aboutstatic.com/file/b09791c37f0a28878efca10c58e7d21f?width=800&quality=75&transparent=1
[        ] flutter: ════════════════════════════════════════════════════════════════════════════════════════════════════
[  +45 ms] Service protocol connection closed.
[        ] Lost connection to device.
[   +1 ms] DevFS: Deleting filesystem on the device
(file:///private/var/mobile/Containers/Data/Application/BBD92A81-9952-4F07-BB65-D25965F4D2F4/tmp/aboutyou_mobile_app_fluttrv7EnmD/aboutyou_mobile_a
pp_fluttr/)
[        ] Sending to VM service: _deleteDevFS({fsName: aboutyou_mobile_app_fluttr})
[ +256 ms] Ignored error while cleaning up DevFS: TimeoutException after 0:00:00.250000: Future not completed
[   +2 ms] "flutter run" took 171,918ms.
```

What I found most interesting is this line (from the profile build on device):

```
Footprint:       226.23 MB -> 743.78 MB (+517.55 MB)
```

Do I understand that correctly that the engine tried to allocate an additional 200% of memory which then caused the system to kill it?

**Comment by tp** [comment]
PS: If you want to download the referenced sample images from the crash log for testing you can, but just be advised to do it in Chrome so you get the `WebP` image, which is what we use currently in the app.

**Comment by tp** [comment]
We found the culprit: Do to what seems a misconfiguration in the CDN one supposedly small image (https://cdn.aboutstatic.com/file/b09791c37f0a28878efca10c58e7d21f?width=800&quality=75&transparent=1) was returned as a 9584*10038px image:

![image](https://user-images.githubusercontent.com/52437/65610870-44071b80-dfb2-11e9-83c4-9f80d78254a0.png)

So as the first step we'll fix this image issue on our side.

I think that leaves 2 questions open:
- Is that allocation expected / reasonable for the given image dimensions?
- Can Flutter do better than crashing in such a case?

**Comment by dnfield** [comment]
This is expected.  That one large image is about 384 megabytes decompressed.  That puts you more than halfway to the point where an iPhone 6 will OOM kill you. If you had 20 more images additionally, that should easily get you there.

**Comment by dnfield** [comment]
(you can use the cacheWidth and cacheHeight parameters on images to avoid this)
