### ISSUE TITLE
CreateProcessW failed 87

### ISSUE THREAD

**Issue by prujohn** [flutter/flutter#41317]
## Steps to Reproduce

Not sure how to repro.  Running on Windows 10.  Flutter doctor fails each time.  What is interesting is that when I run adb.exe directly from the path given below, it runs fine.

## Logs

```
C:\Users\john>flutter doctor -v
[√] Flutter (Channel stable, v1.9.1+hotfix.2, on Microsoft Windows [Version 10.0.17763.737], locale en-US)
    • Flutter version 1.9.1+hotfix.2 at C:\src\flutter
    • Framework revision 2d2a1ffec9 (3 weeks ago), 2019-09-06 18:39:49 -0700
    • Engine revision b863200c37
    • Dart version 2.5.0

\CreateProcessW failed 87
Unable to run "adb", check your Android SDK installation and ANDROID_HOME environment variable:
C:\Users\john\AppData\Local\Android\sdk\platform-tools\adb.exe

#0      throwToolExit (package:flutter_tools/src/base/common.dart:28:3)
#1      getAdbDevices (package:flutter_tools/src/android/android_device.dart:684:5)
#2      AndroidDevices.pollingGetDevices (package:flutter_tools/src/android/android_device.dart:64:53)
<asynchronous suspension>
#3      PollingDeviceDiscovery.devices (package:flutter_tools/src/device.dart:270:52)
<asynchronous suspension>
#4      DeviceManager.getAllConnectedDevices (package:flutter_tools/src/device.dart:136:46)
<asynchronous suspension>
#5      DeviceValidator.validate (package:flutter_tools/src/doctor.dart:760:54)
<asynchronous suspension>
#6      Doctor.startValidatorTasks (package:flutter_tools/src/doctor.dart:140:52)
#7      Doctor.diagnose (package:flutter_tools/src/doctor.dart:211:41)
#8      _AsyncAwaitCompleter.start (dart:async-patch/async_patch.dart:43:6)
#9      Doctor.diagnose (package:flutter_tools/src/doctor.dart:201:24)
#10     DoctorCommand.runCommand (package:flutter_tools/src/commands/doctor.dart:59:39)
#11     _AsyncAwaitCompleter.start (dart:async-patch/async_patch.dart:43:6)
#12     DoctorCommand.runCommand (package:flutter_tools/src/commands/doctor.dart:45:42)
#13     FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:490:18)
#14     _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:71:64)
#15     _rootRunUnary (dart:async/zone.dart:1132:38)
#16     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#17     _FutureListener.handleValue (dart:async/future_impl.dart:137:18)
#18     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:678:45)
#19     Future._propagateToListeners (dart:async/future_impl.dart:707:32)
#20     Future._completeWithValue (dart:async/future_impl.dart:522:5)
#21     Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:552:7)
#22     _rootRun (dart:async/zone.dart:1124:13)
#23     _CustomZone.run (dart:async/zone.dart:1021:19)
#24     _CustomZone.runGuarded (dart:async/zone.dart:923:7)
#25     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:963:23)
#26     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#27     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#28     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:116:13)
#29     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:173:5)
```

**Comment by prujohn** [comment]
Solved.  I had to completely uninstall everything and reinstall.  This includes the Android folder in AppData/......
