### ISSUE TITLE
[Camera] Camera plugin throwing IllegalArgumentException(Bad argument passed to camera service) when takePicture.

### ISSUE THREAD

**Issue by steven2947** [flutter/flutter#41339]
When I use the `takePicture` method, it throws `IllegalArgumentException: Bad argument passed to camera service`.

## Logs
```
E/MethodChannel#plugins.flutter.io/camera(16147): Failed to handle method call
E/MethodChannel#plugins.flutter.io/camera(16147): java.lang.IllegalArgumentException: Bad argument passed to camera service
E/MethodChannel#plugins.flutter.io/camera(16147): 	at android.hardware.camera2.utils.CameraBinderDecorator.throwOnError(CameraBinderDecorator.java:114)
E/MethodChannel#plugins.flutter.io/camera(16147): 	at android.hardware.camera2.utils.CameraBinderDecorator$CameraBinderDecoratorListener.onAfterInvocation(CameraBinderDecorator.java:73)
E/MethodChannel#plugins.flutter.io/camera(16147): 	at android.hardware.camera2.utils.Decorator.invoke(Decorator.java:81)
E/MethodChannel#plugins.flutter.io/camera(16147): 	at java.lang.reflect.Proxy.invoke(Proxy.java:397)
E/MethodChannel#plugins.flutter.io/camera(16147): 	at $Proxy13.submitRequestList(Unknown Source)
E/MethodChannel#plugins.flutter.io/camera(16147): 	at android.hardware.camera2.impl.CameraDeviceImpl.submitCaptureRequest(CameraDeviceImpl.java:617)
E/MethodChannel#plugins.flutter.io/camera(16147): 	at android.hardware.camera2.impl.CameraDeviceImpl.capture(CameraDeviceImpl.java:503)
E/MethodChannel#plugins.flutter.io/camera(16147): 	at android.hardware.camera2.impl.CameraCaptureSessionImpl.capture(CameraCaptureSessionImpl.java:161)
E/MethodChannel#plugins.flutter.io/camera(16147): 	at io.flutter.plugins.camera.Camera.takePicture(Camera.java:267)
E/MethodChannel#plugins.flutter.io/camera(16147): 	at io.flutter.plugins.camera.CameraPlugin.onMethodCall(CameraPlugin.java:96)
E/MethodChannel#plugins.flutter.io/camera(16147): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:222)
E/MethodChannel#plugins.flutter.io/camera(16147): 	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:96)
E/MethodChannel#plugins.flutter.io/camera(16147): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:656)
E/MethodChannel#plugins.flutter.io/camera(16147): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/MethodChannel#plugins.flutter.io/camera(16147): 	at android.os.MessageQueue.next(MessageQueue.java:143)
E/MethodChannel#plugins.flutter.io/camera(16147): 	at android.os.Looper.loop(Looper.java:122)
E/MethodChannel#plugins.flutter.io/camera(16147): 	at android.app.ActivityThread.main(ActivityThread.java:5321)
E/MethodChannel#plugins.flutter.io/camera(16147): 	at java.lang.reflect.Method.invoke(Native Method)
E/MethodChannel#plugins.flutter.io/camera(16147): 	at java.lang.reflect.Method.invoke(Method.java:372)
E/MethodChannel#plugins.flutter.io/camera(16147): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:963)
E/MethodChannel#plugins.flutter.io/camera(16147): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:758)
```

## Solution
When I add `pictureImageReader.getSurface()` in the `createCaptureSession` method, it fixes the bug. So hopefully, it will be fixed in next version.

[explanation - stackoverflow](https://stackoverflow.com/questions/32516539/android-camera2-bad-argument-passed-to-camera-service)

[Camera.java](https://github.com/flutter/plugins/blob/a394c1318af55edc57ab93fc27c19894566bfb6b/packages/camera/android/src/main/java/io/flutter/plugins/camera/Camera.java#L355)

```dart
   private void createCaptureSession(
            int templateType, Runnable onSuccessCallback, Surface... surfaces)
            throws CameraAccessException {
 
       ....
  

        // Collect all surfaces we want to render to.
        List<Surface> surfaceList = new ArrayList<>();
        surfaceList.add(flutterSurface);
        surfaceList.addAll(remainingSurfaces);

        // steven add => fix Bad argument passed to camera service bug
        surfaceList.add(pictureImageReader.getSurface());

        // Start the session
        cameraDevice.createCaptureSession(surfaceList, callback, null);
    }
```

## flutter doctor
```
[✓] Flutter (Channel stable, v1.9.1+hotfix.2, on Mac OS X 10.14.6 18G95, locale zh-Hans-CN)
    • Flutter version 1.9.1+hotfix.2 at /Users/steven/Tools/sdk/flutter
    • Framework revision 2d2a1ffec9 (3 weeks ago), 2019-09-06 18:39:49 -0700
    • Engine revision b863200c37
    • Dart version 2.5.0

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/steven/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • ANDROID_HOME = /Users/steven/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 10.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.3, Build version 10G8
    • CocoaPods version 1.6.1

[✓] Android Studio (version 3.4)
    • Android Studio at /Applications/Android Studio 3.4 Preview.app/Contents
    • Flutter plugin version 38.2.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 39.0.3
    • Dart plugin version 191.8423
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] VS Code (version 1.38.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.4.1

[✓] Connected device (1 available)
    • 3288 • 4ZRV45UQ77 • android-arm • Android 5.1.1 (API 22)

Process finished with exit code 0
```

**Comment by mvanbeusekom** [comment]
Closing this issue since the problem as already been solved. Has been retested on Android 6 and 9.
