### ISSUE TITLE
Failed assertion: boolean expression must not be null,CAN ANYONE FIX IT OR FIND WHERE THE BOOL VALUE IS 

### ISSUE THREAD

**Issue by govindh163** [flutter/flutter#41365]
This was the code
```
 class MyOrders extends StatefulWidget {
  @override
  _MyOrdersState createState() => _MyOrdersState();
}

class _MyOrdersState extends State<MyOrders> with AfterLayoutMixin {
  @override
  void afterFirstLayout(BuildContext context) {
    refreshMyOrders();
  }

  @override
  Widget build(BuildContext context) {
    bool isLoggedIn = Provider.of<UserModel>(context).loggedIn;
    Widget kLoadingWidget(context) => Center(
      child: SpinKitFadingCube(
        color: Theme.of(context).primaryColor,
        size: 30.0,
      ),
    );
    return Scaffold(
        appBar: AppBar(
          leading: IconButton(
              icon: Icon(Icons.arrow_back_ios, size: 20),
              onPressed: () {
                Navigator.of(context).pop();
              }),
          title: Text( 'orderHistory'),
          backgroundColor: Colors.grey,
          elevation: 0.0,
        ),
        body: ListenableProvider.value(
            value: Provider.of<OrderModel>(context),
            child: Consumer<OrderModel>(builder: (context, model, child) {
              if (model.isLoading) {
                return Center(
                  child: kLoadingWidget(context),
                );
              }
              if (!isLoggedIn) {
                final LocalStorage storage = new LocalStorage('data_order');
                var orders = storage.getItem('orders');
                var listOrder = [];
                for (var i in orders) {
                  listOrder.add(Order.fromJson(i));
                }
                return Column(
                  crossAxisAlignment: CrossAxisAlignment.start,
                  children: <Widget>[
                    Padding(
                      padding:
                      EdgeInsets.symmetric(vertical: 15, horizontal: 15),
                      child:
                      Text("${listOrder.length} ${ 'items'}"),
                    ),
                    Expanded(
                      child: ListView.builder(
                          padding: EdgeInsets.symmetric(horizontal: 15),
                          itemCount: listOrder.length,
                          itemBuilder: (context, index) {
                            return OrderItem(
                              order: listOrder[listOrder.length - index - 1],
                              onRefresh: () {},
                            );
                          }),
                    )
                  ],
                );
              }

              if (model.errMsg != null && model.errMsg.isNotEmpty) {
                return Center(
                    child: Text('Error: ${model.errMsg}',
                        style: TextStyle(color: Colors.blue)));
              }

              if (model.myOrders.length == 0) {
                return Center(child: Text( 'noOrders'));
              }

              return Column(
                crossAxisAlignment: CrossAxisAlignment.start,
                children: <Widget>[
                  Padding(
                    padding: EdgeInsets.symmetric(vertical: 15, horizontal: 15),
                    child:
                    Text("${model.myOrders.length} ${ 'items'}"),
                  ),
                  Expanded(
                    child: ListView.//"DEBUGGING STOPS HERE"builder(
                        padding: EdgeInsets.symmetric(horizontal: 15),
                        itemCount: model.myOrders.length,
                        itemBuilder: (context, index) {
                          return OrderItem(
                            order: model.myOrders[index],
                            onRefresh: refreshMyOrders,
                          );
                        }),
                  )
                ],
              );
            })));
  }

  void refreshMyOrders() {
    Provider.of<OrderModel>(context)
        .getMyOrder(userModel: Provider.of<UserModel>(context));
  }
}

class OrderItem extends StatelessWidget {
  final Order order;
  final VoidCallback onRefresh;

  OrderItem({this.order, this.onRefresh});

  @override
  Widget build(BuildContext context) {
    return Column(
      children: <Widget>[
        Container(
          height: 40,
          padding: EdgeInsets.only(left: 10),
          decoration: BoxDecoration(
              color: Colors.grey, borderRadius: BorderRadius.circular(3)),
          child: Row(
            mainAxisAlignment: MainAxisAlignment.spaceBetween,
            crossAxisAlignment: CrossAxisAlignment.center,
            children: <Widget>[
              Text("#${order.number}",
                  style: TextStyle(
                      color: Colors.black, fontWeight: FontWeight.bold)),
            ],
          ),
        ),
        Padding(
          padding: EdgeInsets.symmetric(vertical: 10, horizontal: 10),
          child: Row(
            mainAxisAlignment: MainAxisAlignment.spaceBetween,
            children: <Widget>[
              Text('orderDate'),
              Text(
                DateFormat("dd/MM/yyyy").format(order.createdAt),
                style:
                TextStyle(color: Colors.black, fontWeight: FontWeight.bold),
              )
            ],
          ),
        ),
        Padding(
          padding: EdgeInsets.symmetric(vertical: 10, horizontal: 10),
          child: Row(
            mainAxisAlignment: MainAxisAlignment.spaceBetween,
            children: <Widget>[
              Text('status'),
              Text(
                order.status.toUpperCase(),
                style: TextStyle(
                    color: kOrderStatusColor[order.status] != null
                        ? HexColor(kOrderStatusColor[order.status])
                        : Colors.black,
                    fontWeight: FontWeight.bold),
              )
            ],
          ),
        ),
        Padding(
          padding: EdgeInsets.symmetric(vertical: 10, horizontal: 10),
          child: Row(
            crossAxisAlignment: CrossAxisAlignment.start,
            mainAxisAlignment: MainAxisAlignment.spaceBetween,
            children: <Widget>[
              Text( 'paymentMethod'),
              SizedBox(
                width: 15,
              ),
              Expanded(
                  child: Text(
                    order.paymentMethodTitle,
                    style:
                    TextStyle(color: Colors.black, fontWeight: FontWeight.bold),
                    textAlign: TextAlign.right,
                  ))
            ],
          ),
        ),
        Padding(
          padding: EdgeInsets.symmetric(vertical: 10, horizontal: 10),
          child: Row(
            mainAxisAlignment: MainAxisAlignment.spaceBetween,
            children: <Widget>[
              Text( 'total'),
              Text(
                getCurrecyFormatted(order.total),
                style:
                TextStyle(color: Colors.black, fontWeight: FontWeight.bold),
              )
            ],
          ),
        ),
        SizedBox(height: 20)
      ],
    );
  }
  static String getCurrecyFormatted(price) {
    Map<String, dynamic> defaultCurrency = kAdvanceConfig['DefaultCurrency'];
    final formatCurrency = new NumberFormat.currency(
        symbol: "",
        decimalDigits: defaultCurrency['decimalDigits']);
    try {
      String number = "";
      if (price is String) {
        number = formatCurrency
            .format(price.isNotEmpty ? double.parse(price) : 0);
      } else {
        number = formatCurrency.format(price);
      }
      return defaultCurrency['symbolBeforeTheNumber'] ? defaultCurrency['symbol']+number : number+defaultCurrency['symbol'];
    } catch (err) {
      return defaultCurrency['symbolBeforeTheNumber'] ? defaultCurrency['symbol']+ formatCurrency.format(0) : formatCurrency.format(0) + defaultCurrency['symbol'];
    }
  }

}
class HexColor extends Color {
  static int _getColorFromHex(String hexColor) {
    hexColor = hexColor.toUpperCase().replaceAll("#", "");
    if (hexColor.length == 6) {
      hexColor = "FF" + hexColor;
    }
    return int.parse(hexColor, radix: 16);
  }

  HexColor(final String hexColor) : super(_getColorFromHex(hexColor));
}
```
```
[+39938 ms] I/flutter (30957): ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
[   +1 ms] I/flutter (30957): The following assertion was thrown building OrderItem(dirty):
[        ] I/flutter (30957): Failed assertion: boolean expression must not be null
[        ] I/flutter (30957): 
[        ] I/flutter (30957): Either the assertion indicates an error in the framework itself, or we should provide substantially
[        ] I/flutter (30957): more information in this error message to help you determine and fix the underlying cause.
[        ] I/flutter (30957): In either case, please report this assertion by filing a bug on GitHub:
[        ] I/flutter (30957):   https://github.com/flutter/flutter/issues/new?template=BUG.md
[        ] I/flutter (30957): 
[        ] I/flutter (30957): Widget creation tracking is currently disabled. Enabling it enables improved error messages. It can
[        ] I/flutter (30957): be enabled by passing `--track-widget-creation` to `flutter run` or `flutter test`.
[        ] I/flutter (30957): 
[        ] I/flutter (30957): When the exception was thrown, this was the stack:
[        ] I/flutter (30957): #0      OrderItem.getCurrecyFormatted (package:watercartapp/odersPage.dart:236:29)
[        ] I/flutter (30957): #1      OrderItem.build (package:watercartapp/odersPage.dart:210:17)
[        ] I/flutter (30957): #2      StatelessElement.build (package:flutter/src/widgets/framework.dart:4002:28)
[        ] I/flutter (30957): #3      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3934:15)
[        ] I/flutter (30957): #4      Element.rebuild (package:flutter/src/widgets/framework.dart:3731:5)
[        ] I/flutter (30957): #5      ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3917:5)
[        ] I/flutter (30957): #6      ComponentElement.mount (package:flutter/src/widgets/framework.dart:3912:5)
[        ] I/flutter (30957): #7      Element.inflateWidget (package:flutter/src/widgets/framework.dart:3094:14)
[        ] I/flutter (30957): #8      Element.updateChild (package:flutter/src/widgets/framework.dart:2897:12)
[        ] I/flutter (30957): #9      SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5129:14)
[        ] I/flutter (30957): #10     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3094:14)
[        ] I/flutter (30957): #11     Element.updateChild (package:flutter/src/widgets/framework.dart:2897:12)
[        ] I/flutter (30957): #12     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5129:14)
[        ] I/flutter (30957): #13     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3094:14)
[        ] I/flutter (30957): #14     Element.updateChild (package:flutter/src/widgets/framework.dart:2897:12)
[        ] I/flutter (30957): #15     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3954:16)
[        ] I/flutter (30957): #16     Element.rebuild (package:flutter/src/widgets/framework.dart:3731:5)
[        ] I/flutter (30957): #17     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3917:5)
[        ] I/flutter (30957): #18     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3912:5)
[   +3 ms] I/flutter (30957): #19     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3094:14)
[        ] I/flutter (30957): #20     Element.updateChild (package:flutter/src/widgets/framework.dart:2897:12)
[        ] I/flutter (30957): #21     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3954:16)
[        ] I/flutter (30957): #22     Element.rebuild (package:flutter/src/widgets/framework.dart:3731:5)
[        ] I/flutter (30957): #23     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3917:5)
[   +1 ms] I/flutter (30957): #24     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3912:5)
[   +1 ms] I/flutter (30957): #25     ParentDataElement.mount (package:flutter/src/widgets/framework.dart:4307:11)
[        ] I/flutter (30957): #26     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3094:14)
[        ] I/flutter (30957): #27     Element.updateChild (package:flutter/src/widgets/framework.dart:2897:12)
[        ] I/flutter (30957): #28     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3954:16)
[        ] I/flutter (30957): #29     Element.rebuild (package:flutter/src/widgets/framework.dart:3731:5)
[        ] I/flutter (30957): #30     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3917:5)
[   +1 ms] I/flutter (30957): #31     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4081:11)
[   +1 ms] I/flutter (30957): #32     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3912:5)
[        ] I/flutter (30957): #33     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3094:14)
[        ] I/flutter (30957): #34     Element.updateChild (package:flutter/src/widgets/framework.dart:2897:12)
[        ] I/flutter (30957): #35     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3954:16)
[        ] I/flutter (30957): #36     Element.rebuild (package:flutter/src/widgets/framework.dart:3731:5)
[        ] I/flutter (30957): #37     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3917:5)
[        ] I/flutter (30957): #38     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3912:5)
[        ] I/flutter (30957): #39     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3094:14)
[        ] I/flutter (30957): #40     Element.updateChild (package:flutter/src/widgets/framework.dart:2897:12)
[        ] I/flutter (30957): #41     SliverMultiBoxAdaptorElement.updateChild (package:flutter/src/widgets/sliver.dart:1213:36)
[        ] I/flutter (30957): #42     SliverMultiBoxAdaptorElement.createChild.<anonymous closure> (package:flutter/src/widgets/sliver.dart:1198:20)
[        ] I/flutter (30957): #43     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2321:19)
[        ] I/flutter (30957): #44     SliverMultiBoxAdaptorElement.createChild (package:flutter/src/widgets/sliver.dart:1191:11)
[        ] I/flutter (30957): #45     RenderSliverMultiBoxAdaptor._createOrObtainChild.<anonymous closure> (package:flutter/src/rendering/sliver_multi_box_adaptor.dart:354:23)
[        ] I/flutter (30957): #46     RenderObject.invokeLayoutCallback.<anonymous closure> (package:flutter/src/rendering/object.dart:1797:58)
[        ] I/flutter (30957): #47     PipelineOwner._enableMutationsToDirtySubtrees (package:flutter/src/rendering/object.dart:875:15)
[   +1 ms] I/flutter (30957): #48     RenderObject.invokeLayoutCallback (package:flutter/src/rendering/object.dart:1797:13)
[        ] I/flutter (30957): #49     RenderSliverMultiBoxAdaptor._createOrObtainChild (package:flutter/src/rendering/sliver_multi_box_adaptor.dart:343:5)
[        ] I/flutter (30957): #50     RenderSliverMultiBoxAdaptor.addInitialChild (package:flutter/src/rendering/sliver_multi_box_adaptor.dart:427:5)
[        ] I/flutter (30957): #51     RenderSliverList.performLayout (package:flutter/src/rendering/sliver_list.dart:78:12)
[        ] I/flutter (30957): #52     RenderObject.layout (package:flutter/src/rendering/object.dart:1701:7)
[        ] I/flutter (30957): #53     RenderSliverPadding.performLayout (package:flutter/src/rendering/sliver_padding.dart:181:11)
[        ] I/flutter (30957): #54     RenderObject.layout (package:flutter/src/rendering/object.dart:1701:7)
[        ] I/flutter (30957): #55     RenderViewportBase.layoutChildSequence (package:flutter/src/rendering/viewport.dart:406:13)
[        ] I/flutter (30957): #56     RenderViewport._attemptLayout (package:flutter/src/rendering/viewport.dart:1355:12)
[        ] I/flutter (30957): #57     RenderViewport.performLayout (package:flutter/src/rendering/viewport.dart:1273:20)
[        ] I/flutter (30957): #58     RenderObject.layout (package:flutter/src/rendering/object.dart:1701:7)
[        ] I/flutter (30957): #59     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
[        ] I/flutter (30957): #60     RenderObject.layout (package:flutter/src/rendering/object.dart:1701:7)
[        ] I/flutter (30957): #61     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
[        ] I/flutter (30957): #62     RenderObject.layout (package:flutter/src/rendering/object.dart:1701:7)
[   +2 ms] I/flutter (30957): #63     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
[        ] I/flutter (30957): #64     RenderObject.layout (package:flutter/src/rendering/object.dart:1701:7)
[        ] I/flutter (30957): #65     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
[        ] I/flutter (30957): #66     RenderObject.layout (package:flutter/src/rendering/object.dart:1701:7)
[        ] I/flutter (30957): #67     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
[        ] I/flutter (30957): #68     RenderObject.layout (package:flutter/src/rendering/object.dart:1701:7)
[        ] I/flutter (30957): #69     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
[        ] I/flutter (30957): #70     RenderObject.layout (package:flutter/src/rendering/object.dart:1701:7)
[        ] I/flutter (30957): #71     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
[        ] I/flutter (30957): #72     RenderObject.layout (package:flutter/src/rendering/object.dart:1701:7)
[        ] I/flutter (30957): #73     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
[        ] I/flutter (30957): #74     RenderObject.layout (package:flutter/src/rendering/object.dart:1701:7)
[        ] I/flutter (30957): #75     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
[        ] I/flutter (30957): #76     RenderObject.layout (package:flutter/src/rendering/object.dart:1701:7)
[        ] I/flutter (30957): #77     RenderFlex.performLayout (package:flutter/src/rendering/flex.dart:806:17)
[        ] I/flutter (30957): #78     RenderObject.layout (package:flutter/src/rendering/object.dart:1701:7)
[        ] I/flutter (30957): #79     MultiChildLayoutDelegate.layoutChild (package:flutter/src/rendering/custom_layout.dart:142:11)
[        ] I/flutter (30957): #80     _ScaffoldLayout.performLayout (package:flutter/src/material/scaffold.dart:477:7)
[        ] I/flutter (30957): #81     MultiChildLayoutDelegate._callPerformLayout (package:flutter/src/rendering/custom_layout.dart:212:7)
[        ] I/flutter (30957): #82     RenderCustomMultiChildLayoutBox.performLayout (package:flutter/src/rendering/custom_layout.dart:356:14)
[        ] I/flutter (30957): #83     RenderObject.layout (package:flutter/src/rendering/object.dart:1701:7)
[        ] I/flutter (30957): #84     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
[        ] I/flutter (30957): #85     RenderObject.layout (package:flutter/src/rendering/object.dart:1701:7)
[        ] I/flutter (30957): #86     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
[        ] I/flutter (30957): #87     _RenderCustomClip.performLayout (package:flutter/src/rendering/proxy_box.dart:1232:11)
[        ] I/flutter (30957): #88     RenderObject.layout (package:flutter/src/rendering/object.dart:1701:7)
[        ] I/flutter (30957): #89     MultiChildLayoutDelegate.layoutChild (package:flutter/src/rendering/custom_layout.dart:142:11)
[        ] I/flutter (30957): #90     _ScaffoldLayout.performLayout (package:flutter/src/material/scaffold.dart:477:7)
[        ] I/flutter (30957): #91     MultiChildLayoutDelegate._callPerformLayout (package:flutter/src/rendering/custom_layout.dart:212:7)
[        ] I/flutter (30957): #92     RenderCustomMultiChildLayoutBox.performLayout (package:flutter/src/rendering/custom_layout.dart:356:14)
[        ] I/flutter (30957): #93     RenderObject._layoutWithoutResize (package:flutter/src/rendering/object.dart:1578:7)
[        ] I/flutter (30957): #94     PipelineOwner.flushLayout (package:flutter/src/rendering/object.dart:844:18)
[        ] I/flutter (30957): #95     RendererBinding.drawFrame (package:flutter/src/rendering/binding.dart:340:19)
[        ] I/flutter (30957): #96     WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:776:13)
[        ] I/flutter (30957): #97     RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:279:5)
[        ] I/flutter (30957): #98     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1040:15)
[        ] I/flutter (30957): #99     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:982:9)
[        ] I/flutter (30957): #100    SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:898:5)
[        ] I/flutter (30957): #104    _invoke (dart:ui/hooks.dart:249:10)
[        ] I/flutter (30957): #105    _drawFrame (dart:ui/hooks.dart:207:3)
[        ] I/flutter (30957): (elided 3 frames from package dart:async)
[        ] I/flutter (30957): 
[        ] I/flutter (30957): ════════════════════════════════════════════════════════════════════════════════════════════════════
[+292570 ms] Service protocol connection closed.
[   +2 ms] Lost connection to device.
[   +6 ms] DevFS: Deleting filesystem on the device (file:///data/user/0/com.smartiapps.watercartapp/code_cache/watercartappNMCJPH/watercartapp/)
[  +31 ms] Sending to VM service: _deleteDevFS({fsName: watercartapp})
[ +258 ms] Ignored error while cleaning up DevFS: TimeoutException after 0:00:00.250000: Future not completed
[   +5 ms] "flutter run" took 411,726ms.
```
```
F:\MobileAppProjects\watercartapp>flutter doctor -v
[√] Flutter (Channel dev, v1.10.2, on Microsoft Windows [Version 10.0.18362.356], locale en-US)
    • Flutter version 1.10.2 at E:\flutter
    • Framework revision f5733f7a62 (2 weeks ago), 2019-09-11 21:03:42 -0700
    • Engine revision 7ea9884ab0
    • Dart version 2.5.0 (build 2.5.0-dev.4.0 be66176534)


[√] Android toolchain - develop for Android devices (Android SDK version 29.0.1)
    • Android SDK at C:\Users\admin\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.1
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 3.5)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 39.0.3
    • Dart plugin version 191.8423
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)

[√] Connected device (3 available)
    • Redmi Note 7 Pro • dd1fde16 • android-arm64  • Android 9 (API 28)
    • Chrome           • chrome   • web-javascript • Google Chrome 77.0.3865.90
    • Server           • web      • web-javascript • Flutter Tools

• No issues found!

F:\MobileAppProjects\watercartapp>
```

**Comment by superciccio** [comment]
hi, 
this is null `order.status.toUpperCase(),`
your status is. to fix do the same you did for color

**Comment by govindh163** [comment]
ThanK You @superciccio Will Try it out!!

**Comment by BondarenkoStas** [comment]
Thank you @superciccio !
@govindh163 This is a question better suited for StackOverflow, since there doesn’t seem to be anything wrong with Flutter itself, but related to implementation. See https://flutter.dev/community for support options. In majority of cases failed assertion points to an error in the implementation, not to issues with Flutter SDK.

**Comment by escamoteur** [comment]
It always help to closely look at the stacktrace where you find in which method it happened. Also enabling break on all exceptions is good thing in the debugger

**Comment by govindh163** [comment]
Hey @superciccio Can I get To Know how do you Found  ' order.status.toUpperCase(),' is null?

Thanks In Advance!!

**Comment by superciccio** [comment]
> Hey @superciccio Can I get To Know how do you Found ' order.status.toUpperCase(),' is null?
> 
> Thanks In Advance!!

Sorry I was pointing to the wrong one, actually is `getCurrecyFormatted(order.total),`

first line of stacktrace is ` OrderItem.getCurrecyFormatted `

my mistake :)

**Comment by govindh163** [comment]
Yes,Fixed ThankYou Soo Much!!@superciccio
