### ISSUE TITLE
TextEditingController doesnot change text of TextEdit at Web.

### ISSUE THREAD

**Issue by alex89607** [flutter/flutter#41376]
When the user edit text at TextEdit and then put new text by TextEditController, then the previous text was appear.

1. Start Text(generated):
![изображение](https://user-images.githubusercontent.com/5480375/65698619-79c90480-e085-11e9-8fba-2a032fa1ddb3.png)

2. Edit Text
![изображение](https://user-images.githubusercontent.com/5480375/65698677-8fd6c500-e085-11e9-8236-273aaeee12c3.png)

3.Generate new text
![изображение](https://user-images.githubusercontent.com/5480375/65698717-a2e99500-e085-11e9-8104-32817c1b3fae.png)

4.Click at edit field
![изображение](https://user-images.githubusercontent.com/5480375/65698765-b432a180-e085-11e9-80f2-3e5a9e8aa17a.png)

## Steps to Reproduce
clone https://github.com/develop86229/texteditset190926.git

Its example "flutter create ."

```
import 'dart:math';
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key key, this.title}) : super(key: key);
  final String title;

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  int _counter = 0;
  TextEditingController myTextController = TextEditingController();
  var rnd = new Random();

  void _incrementCounter() {
    setState(() {
      _counter++;
    });
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            TextField(
              controller: myTextController,
            ),
            Text(
              'You have pushed the button this many times:',
            ),
            Text(
              '$_counter',
              style: Theme.of(context).textTheme.display1,
            ),
          ],
        ),
      ),
      floatingActionButton: FloatingActionButton(
        onPressed:
//        _incrementCounter,

            () {
          setState(() {
            myTextController.text = rnd.nextInt(1000000000).toString();
          });
        },
        tooltip: 'Increment',
        child: Icon(Icons.add),
      ), // This trailing comma makes auto-formatting nicer for build methods.
    );
  }
}


```

## Logs

```
[  +22 ms] executing: [D:\-inst\-SDKFlutter\flutter\] git -c log.showSignature=false log -n 1
--pretty=format:%H
[  +82 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[   +1 ms] e0247442d019516a534b66b4f5a8c47c1e2c0a3d
[   +1 ms] executing: [D:\-inst\-SDKFlutter\flutter\] git describe --match v*.*.* --first-parent --long --tags
[  +86 ms] Exit code 0 from: git describe --match v*.*.* --first-parent --long --tags
[   +2 ms] v1.10.6-23-ge0247442d
[  +10 ms] executing: [D:\-inst\-SDKFlutter\flutter\] git rev-parse --abbrev-ref --symbolic @{u}
[  +56 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[   +1 ms] origin/master
[   +1 ms] executing: [D:\-inst\-SDKFlutter\flutter\] git ls-remote --get-url origin
[  +49 ms] Exit code 0 from: git ls-remote --get-url origin
[   +1 ms] https://github.com/flutter/flutter.git
[  +90 ms] executing: [D:\-inst\-SDKFlutter\flutter\] git rev-parse --abbrev-ref HEAD
[  +54 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[   +2 ms] master
[ +110 ms] executing: D:\-inst\-SDKAndroid\Sdk\platform-tools\adb.exe devices -l
[  +40 ms] Exit code 0 from: D:\-inst\-SDKAndroid\Sdk\platform-tools\adb.exe devices -l
[   +1 ms] List of devices attached
[  +12 ms] More than one device connected; please specify a device with the '-d <deviceId>' flag, or use '-d
all' to act
           on all devices.
[  +36 ms] Chrome • chrome • web-javascript • Google Chrome 77.0.3865.90
[   +3 ms] Server • web    • web-javascript • Flutter Tools
[  +11 ms] "flutter run" took 270ms.

#0      throwToolExit (package:flutter_tools/src/base/common.dart:28:3)
#1      RunCommand.validateCommand (package:flutter_tools/src/commands/run.dart:276:7)
<asynchronous suspension>
#2      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:510:11)
<asynchronous suspension>
#3      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:452:33)
<asynchronous suspension>
#4      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:157:29)
<asynchronous suspension>
#5      _rootRun (dart:async/zone.dart:1124:13)
#6      _CustomZone.run (dart:async/zone.dart:1021:19)
#7      _runZoned (dart:async/zone.dart:1516:10)
#8      runZoned (dart:async/zone.dart:1463:12)
#9      AppContext.run (package:flutter_tools/src/base/context.dart:156:18)
<asynchronous suspension>
#10     FlutterCommand.run (package:flutter_tools/src/runner/flutter_command.dart:442:20)
#11     CommandRunner.runCommand (package:args/command_runner.dart:197:27)
<asynchronous suspension>
#12     FlutterCommandRunner.runCommand.<anonymous closure>
(package:flutter_tools/src/runner/flutter_command_runner.dart:416:21)
<asynchronous suspension>
#13     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:157:29)
<asynchronous suspension>
#14     _rootRun (dart:async/zone.dart:1124:13)
#15     _CustomZone.run (dart:async/zone.dart:1021:19)
#16     _runZoned (dart:async/zone.dart:1516:10)
#17     runZoned (dart:async/zone.dart:1463:12)
#18     AppContext.run (package:flutter_tools/src/base/context.dart:156:18)
<asynchronous suspension>
#19     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:367:19)
<asynchronous suspension>
#20     CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:112:25)
#21     new Future.sync (dart:async/future.dart:224:31)
#22     CommandRunner.run (package:args/command_runner.dart:112:14)
#23     FlutterCommandRunner.run (package:flutter_tools/src/runner/flutter_command_runner.dart:251:18)
#24     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:63:22)
<asynchronous suspension>
#25     _rootRun (dart:async/zone.dart:1124:13)
#26     _CustomZone.run (dart:async/zone.dart:1021:19)
#27     _runZoned (dart:async/zone.dart:1516:10)
#28     runZoned (dart:async/zone.dart:1500:12)
#29     run.<anonymous closure> (package:flutter_tools/runner.dart:61:18)
<asynchronous suspension>
#30     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:157:29)
<asynchronous suspension>
#31     _rootRun (dart:async/zone.dart:1124:13)
#32     _CustomZone.run (dart:async/zone.dart:1021:19)
#33     _runZoned (dart:async/zone.dart:1516:10)
#34     runZoned (dart:async/zone.dart:1463:12)
#35     AppContext.run (package:flutter_tools/src/base/context.dart:156:18)
<asynchronous suspension>
#36     runInContext (package:flutter_tools/src/context_runner.dart:62:24)
<asynchronous suspension>
#37     run (package:flutter_tools/runner.dart:50:10)
#38     main (package:flutter_tools/executable.dart:65:9)
<asynchronous suspension>
#39     main (file:///D:/-inst/-SDKFlutter/flutter/packages/flutter_tools/bin/flutter_tools.dart:8:3)
#40     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:303:32)
#41     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:12)


```
```

X:\-curr\--tests\texteditset190926>flutter analyze
Analyzing texteditset190926...

   info - The declaration '_incrementCounter' isn't referenced - lib\main.dart:53:8 - unused_element

1 issue found. (ran in 21.4s)

```
```

<!-- Finally, paste the output of running `flutter doctor -v` here. -->
[√] Flutter (Channel master, v1.10.7-pre.23, on Microsoft Windows [Version 10.0.17763.737], locale en-US)

[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[√] Chrome - develop for the web
[!] Android Studio (not installed)
[!] IntelliJ IDEA Ultimate Edition (version 2018.3)
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
[√] Connected device (2 available)



Flutter 1.10.7-pre.23 • channel master • https://github.com/flutter/flutter.git
Framework • revision e0247442d0 (8 hours ago) • 2019-09-26 02:49:41 -0400
Engine • revision 3713ecf107
Tools • Dart 2.6.0 (build 2.6.0-dev.2.0 c6a14f4459)
```

**Comment by alex89607** [comment]
May be someone seems useful, that we with **LiJonas** [developed](url=https://stackoverflow.com/questions/58167577/how-to-insert-two-action-at-one-button-onpress-delete-widget-and-create-it-by)a temporary workaround.

**Comment by nturgut** [comment]
I'll send a PR to fix this one today. 

Thanks for commenting on the issue.

**Comment by nturgut** [comment]
I sent out https://github.com/flutter/engine/pull/12698 for the fix
