### ISSUE TITLE
[WEB] Crash when running Web application from exists Mobile Application

### ISSUE THREAD

**Issue by jt100xu** [flutter/flutter#41388]
## Steps to Reproduce
1. My Flutter Application is working on Android/iOS
2. setup to Web Application.
3. run and crash.

## Logs
[flutter_07.log](https://github.com/flutter/flutter/files/3659024/flutter_07.log)
(content)
## command
```
flutter run -d chrome
```
## exception
```
SocketException: SocketException: Failed to create server socket (OS Error: Too many open files, errno = 24), address = 127.0.0.1, port = 59581
```
```
#0      _NativeSocket.bind (dart:io-patch/socket_patch.dart:642:7)
<asynchronous suspension>
#1      _RawServerSocket.bind (dart:io-patch/socket_patch.dart:1260:26)
#2      _ServerSocket.bind (dart:io-patch/socket_patch.dart:1520:29)
#3      ServerSocket.bind (dart:io-patch/socket_patch.dart:1511:26)
#4      _HttpServer.bind (dart:_http/http_impl.dart:2592:25)
#5      HttpServer.bind (dart:_http:227:19)
#6      HttpMultiServer.loopback.<anonymous closure> (package:http_multi_server/http_multi_server.dart:113:39)
#7      HttpMultiServer._loopback (package:http_multi_server/http_multi_server.dart:172:30)
<asynchronous suspension>
#8      HttpMultiServer.loopback (package:http_multi_server/http_multi_server.dart:111:12)
#9      HttpMultiServer.bind (package:http_multi_server/http_multi_server.dart:148:30)
#10     DebugService.start (package:dwds/src/services/debug_service.dart:158:40)
<asynchronous suspension>
#11     DevHandler.startDebugService (package:dwds/src/handlers/dev_handler.dart:122:25)
<asynchronous suspension>
#12     DevHandler.loadAppServices.<anonymous closure> (package:dwds/src/handlers/dev_handler.dart:143:19)
<asynchronous suspension>
#13     _LinkedHashMapMixin.putIfAbsent (dart:collection-patch/compact_hash.dart:291:23)
#14     DevHandler.loadAppServices (package:dwds/src/handlers/dev_handler.dart:141:24)
#15     Dwds.debugConnection (package:dwds/dwds.dart:51:46)
<asynchronous suspension>
#16     WebFs.runAndDebug.<anonymous closure> (package:flutter_tools/src/build_runner/web_fs.dart:120:23)
<asynchronous suspension>
#17     _rootRunUnary (dart:async/zone.dart:1132:38)
#18     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#19     _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
#20     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#21     _DelayedData.perform (dart:async/stream_impl.dart:591:14)
#22     _StreamImplEvents.handleNext (dart:async/stream_impl.dart:707:11)
#23     _PendingEvents.schedule.<anonymous closure> (dart:async/stream_impl.dart:667:7)
#24     _rootRun (dart:async/zone.dart:1120:38)
#25     _CustomZone.run (dart:async/zone.dart:1021:19)
#26     _CustomZone.runGuarded (dart:async/zone.dart:923:7)
#27     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:963:23)
#28     _rootRun (dart:async/zone.dart:1124:13)
#29     _CustomZone.run (dart:async/zone.dart:1021:19)
#30     _CustomZone.runGuarded (dart:async/zone.dart:923:7)
#31     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:963:23)
#32     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#33     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#34     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:116:13)
#35     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:173:5)
```

## flutter doctor

```
[32m[✓][39m Flutter (Channel master, v1.10.7-pre.27, on Mac OS X 10.14.4 18E226, locale en-VN)
    [32m•[39m Flutter version 1.10.7-pre.27 at /Program-files/flutter
    [32m•[39m Framework revision 7fa5dd7454 (2 hours ago), 2019-09-26 08:12:48 -0700
    [32m•[39m Engine revision 1060cfc7da
    [32m•[39m Dart version 2.6.0 (build 2.6.0-dev.0.0 dd65f97118)

[32m[✓][39m Android toolchain - develop for Android devices (Android SDK version 29.0.1)
    [32m•[39m Android SDK at /Program-files/android-sdk
    [32m•[39m Android NDK location not configured (optional; useful for native profiling support)
    [32m•[39m Platform android-29, build-tools 29.0.1
    [32m•[39m ANDROID_HOME = /Program-files/android-sdk
    [32m•[39m Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    [32m•[39m Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
    [32m•[39m All Android licenses accepted.

[33m[!][39m Xcode - develop for iOS and macOS (Xcode 10.1)
    [32m•[39m Xcode at /Applications/Xcode.app/Contents/Developer
    [32m•[39m Xcode 10.1, Build version 10B61
    [31m✗[39m CocoaPods installed but not working.
        You appear to have CocoaPods installed but it is not working.
        This can happen if the version of Ruby that CocoaPods was installed with is different from the one being used to invoke it.
        This can usually be fixed by re-installing CocoaPods. For more info, see https://github.com/flutter/flutter/issues/14293.
      To re-install CocoaPods, run:
        sudo gem install cocoapods
        pod setup

[32m[✓][39m Chrome - develop for the web
    [32m•[39m Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[32m[✓][39m Android Studio (version 3.2)
    [32m•[39m Android Studio at /Applications/Android Studio 3.2.app/Contents
    [32m•[39m Flutter plugin version 31.3.1
    [32m•[39m Dart plugin version 181.5656
    [32m•[39m Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)

[32m[✓][39m Android Studio (version 3.4)
    [32m•[39m Android Studio at /Applications/Android Studio 3.4.2.app/Contents
    [32m•[39m Flutter plugin version 38.1.1
    [32m•[39m Dart plugin version 183.6270
    [32m•[39m Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

[32m[✓][39m Android Studio (version 3.4)
    [32m•[39m Android Studio at /Applications/Android Studio.app/Contents
    [32m•[39m Flutter plugin version 38.1.1
    [32m•[39m Dart plugin version 183.6270
    [32m•[39m Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

[32m[✓][39m VS Code (version 1.27.1)
    [32m•[39m VS Code at /Applications/Visual Studio Code.app/Contents
    [32m•[39m Flutter extension version 2.18.0

[31m[☠][39m Connected device (the doctor check crashed)
    [31m✗[39m Due to an error, the doctor check did not complete. If the error message below is not helpful, please let us know about this
      issue at https://github.com/flutter/flutter/issues.
    [31m✗[39m ProcessException: Too many open files
        Command: /Applications/Google Chrome.app/Contents/MacOS/Google Chrome --version
    [32m•[39m #0      ChromeDevice.sdkNameAndVersion (package:flutter_tools/src/web/web_device.dart:111:36)
      <asynchronous suspension>
      #1      Device.descriptions (package:flutter_tools/src/device.dart:456:25)
      <asynchronous suspension>
      #2      DeviceValidator.validate (package:flutter_tools/src/doctor.dart:852:31)
      <asynchronous suspension>
      #3      asyncGuard.<anonymous closure> (package:flutter_tools/src/base/async_guard.dart:111:32)
      <asynchronous suspension>
      #4      _rootRun (dart:async/zone.dart:1124:13)
      #5      _CustomZone.run (dart:async/zone.dart:1021:19)
      #6      _runZoned (dart:async/zone.dart:1516:10)
      #7      runZoned (dart:async/zone.dart:1500:12)
      #8      asyncGuard (package:flutter_tools/src/base/async_guard.dart:109:3)
      #9      Doctor.startValidatorTasks (package:flutter_tools/src/doctor.dart:158:9)
      #10     Doctor.diagnose (package:flutter_tools/src/doctor.dart:252:41)
      #11     _AsyncAwaitCompleter.start (dart:async-patch/async_patch.dart:43:6)
      #12     Doctor.diagnose (package:flutter_tools/src/doctor.dart:241:24)
      #13     _doctorText.<anonymous closure> (package:flutter_tools/runner.dart:205:26)
      #14     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:157:29)
      #15     _AsyncAwaitCompleter.start (dart:async-patch/async_patch.dart:43:6)
      #16     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:157:7)
      #17     _rootRun (dart:async/zone.dart:1124:13)
      #18     _CustomZone.run (dart:async/zone.dart:1021:19)
      #19     _runZoned (dart:async/zone.dart:1516:10)
      #20     runZoned (dart:async/zone.dart:1463:12)
      #21     AppContext.run (package:flutter_tools/src/base/context.dart:156:18)
      #22     _AsyncAwaitCompleter.start (dart:async-patch/async_patch.dart:43:6)
      #23     AppContext.run (package:flutter_tools/src/base/context.dart:143:19)
      #24     _doctorText (package:flutter_tools/runner.dart:204:19)
      #25     _AsyncAwaitCompleter.start (dart:async-patch/async_patch.dart:43:6)
      #26     _doctorText (package:flutter_tools/runner.dart:200:27)
      #27     _createLocalCrashReport (package:flutter_tools/runner.dart:182:32)
      #28     _AsyncAwaitCompleter.start (dart:async-patch/async_patch.dart:43:6)
      #29     _createLocalCrashReport (package:flutter_tools/runner.dart:167:37)
      #30     _handleToolError (package:flutter_tools/runner.dart:138:31)
      #31     _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:71:64)
      #32     _rootRunUnary (dart:async/zone.dart:1132:38)
      #33     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
      #34     _FutureListener.handleValue (dart:async/future_impl.dart:137:18)
      #35     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:678:45)
      #36     Future._propagateToListeners (dart:async/future_impl.dart:707:32)
      #37     Future._completeWithValue (dart:async/future_impl.dart:522:5)
      #38     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:30:15)
      #39     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:288:13)
      #40     CrashReportSender.sendReport (package:flutter_tools/src/reporting/crash_reporting.dart)
      #41     _asyncErrorWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:78:45)
      #42     _rootRunBinary (dart:async/zone.dart:1144:38)
      #43     _CustomZone.runBinary (dart:async/zone.dart:1037:19)
      #44     _FutureListener.handleError (dart:async/future_impl.dart:151:20)
      #45     Future._propagateToListeners.handleError (dart:async/future_impl.dart:690:47)
      #46     Future._propagateToListeners (dart:async/future_impl.dart:711:24)
      #47     Future._completeError (dart:async/future_impl.dart:530:5)
      #48     _AsyncAwaitCompleter.completeError (dart:async-patch/async_patch.dart:36:15)
      #49     IOClient.send (package:http/src/io_client.dart)
      #50     _asyncErrorWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:78:45)
      #51     _rootRunBinary (dart:async/zone.dart:1144:38)
      #52     _CustomZone.runBinary (dart:async/zone.dart:1037:19)
      #53     _FutureListener.handleError (dart:async/future_impl.dart:151:20)
      #54     Future._propagateToListeners.handleError (dart:async/future_impl.dart:690:47)
      #55     Future._propagateToListeners (dart:async/future_impl.dart:711:24)
      #56     Future._completeError (dart:async/future_impl.dart:530:5)
      #57     Future._asyncCompleteError.<anonymous closure> (dart:async/future_impl.dart:578:7)
      #58     _rootRun (dart:async/zone.dart:1124:13)
      #59     _CustomZone.run (dart:async/zone.dart:1021:19)
      #60     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:947:23)
      #61     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
      #62     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
      #63     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:116:13)
      #64     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:173:5)


[33m![39m Doctor found issues in 2 categories.
```

**Comment by BondarenkoStas** [comment]
https://krypted.com/mac-os-x/maximum-files-in-mac-os-x/
@jt100xu It's not a solution in any way, but may be a workaround for a bit. What is your current maxfiles limit, is it 65535?

**Comment by janmoppel** [comment]
Hello @jt100xu !

Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the issue, if you have any more information for us; we will reopen it right away!

Thank you for your contribution.

P.S. If anyone still experience the same problem, please file a new issue with the information required in the template.
All system setups can be slightly different so it’s always better to open new issues and reference related issues.
