### ISSUE TITLE
[Flutter Web] compositing error with SweepGradient, RadialGradient decoration

### ISSUE THREAD

**Issue by maryx** [flutter/flutter#41389]
## Steps to Reproduce
1. Build basic Flutter app (`flutter create myapp`) on Flutter Web (chrome). Works fine.
2. Replace the `body` with this `background` widget:

```
final background = Container(
  decoration: BoxDecoration(
    gradient: SweepGradient(
      center: FractionalOffset.center,
      startAngle: -(math.pi / 2),
      endAngle: math.pi * 2 - (math.pi / 2),
      colors: const <Color>[
        Color(0xFF4285F4), // blue
        Color(0xFF34A853), // green
        Color(0xFFFBBC05), // yellow
        Color(0xFFEA4335), // red
        Color(0xFF4285F4), // blue
      ],
      stops: const <double>[0.0, 0.25, 0.5, 0.75, 1.0],
    ),
  ),
);
```
3. Run `flutter run -d <emulator>`. You get this:
![Screenshot from 2019-09-26 10-15-05](https://user-images.githubusercontent.com/3357543/65709810-8e39dc80-e046-11e9-8b3d-c9671f9498b9.png)

4. run `flutter run -d chrome`. You get an error and no UI on screen.

## Logs

```
$ flutter run -d chrome --verbose
[  +18 ms] executing: [REDACTED_DIRECTORY] git -c log.showSignature=false log -n 1
--pretty=format:%H
[  +41 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[        ] 9bd02a1787bd264fde13a445a900ca28d08e3cef
[        ] executing: [REDACTED_DIRECTORY] git describe --match v*.*.* --first-parent --long
--tags
[  +23 ms] Exit code 0 from: git describe --match v*.*.* --first-parent --long --tags
[        ] v1.10.5-73-g9bd02a1787
[   +9 ms] executing: [REDACTED_DIRECTORY] git rev-parse --abbrev-ref --symbolic @{u}
[   +7 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/master
[   +2 ms] executing: [REDACTED_DIRECTORY] git ls-remote --get-url origin
[   +6 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[  +52 ms] executing: [REDACTED_DIRECTORY] git rev-parse --abbrev-ref HEAD
[   +9 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] master
[  +78 ms] executing: REDACTED_DIRECTORY/Android/Sdk/platform-tools/adb devices -l
[   +9 ms] Exit code 0 from: REDACTED_DIRECTORY/Android/Sdk/platform-tools/adb devices -l
[        ] List of devices attached
[  +21 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[   +3 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[ +248 ms] Launching lib/main.dart on Chrome in debug mode...
[   +1 ms] Building application for the web...
[+10170 ms] Starting daemon...
[ +135 ms] Initializing inputs
[   +5 ms] Reading cached asset graph...
[ +137 ms] Reading cached asset graph completed, took 134ms

[ +195 ms] Checking for updates since last build...
[ +460 ms] Checking for updates since last build completed, took 460ms

[   +6 ms] Initializing inputs
[   +1 ms] Reading cached asset graph...
[        ] Reading cached asset graph completed, took 134ms
[        ] Checking for updates since last build...
[        ] Checking for updates since last build completed, took 460ms
[ +189 ms] Serving DevTools at http://127.0.0.1:36717

[ +603 ms] About to build [web]...
[   +7 ms] Running build...
[ +121 ms] Running build completed, took 53ms

[        ] Caching finalized dependency graph...
[   +4 ms] Caching finalized dependency graph completed, took 93ms

[   +3 ms] Succeeded after 151ms with 0 outputs (0 actions)

[+3241 ms] Failed to load asset at path: packages/build_web_compilers/src/dev_compiler/dart_sdk.js.

Status code: 404

Headers:
{
"date": "Thu, 26 Sep 2019 16:51:54 GMT",
"content-length": "9",
"x-frame-options": "SAMEORIGIN",
"content-type": "text/plain; charset=utf-8",
"x-xss-protection": "1; mode=block",
"x-content-type-options": "nosniff",
"server": "dart:io with Shelf",
"via": "1.1 shelf_proxy"
}

Content:
Not Found

[+1773 ms] Debug service listening on ws://127.0.0.1:43875/ivFmLDnL28Q=

[  +16 ms] Building application for the web... (completed in 17.1s)
[   +1 ms] 👻 👻 👻 👻 👻 👻 👻 👻 👻 👻 👻 👻 👻 👻 👻 👻 👻 👻 👻 👻
[        ] Warning: Flutter's support for building web applications is highly experimental.
[        ] For more information see https://github.com/flutter/flutter/issues/34082.
[        ] 👻 👻 👻 👻 👻 👻 👻 👻 👻 👻 👻 👻 👻 👻 👻 👻 👻 👻 👻 👻
[        ] 🔥  To hot restart (and rebuild state), press "R".
[        ] For a more detailed help message, press "h". To quit, press "q".
[   +6 ms] Debug service listening on ws://127.0.0.1:43875/ivFmLDnL28Q=
[ +419 ms] Another exception was thrown: Assertion failed:
file:////b/s/w/ir/cache/builder/src/out/host_debug/flutter_web_sdk/lib/ui/src/ui/compositing.dart:343:12
[ +986 ms] Another exception was thrown: Assertion failed:
file:////b/s/w/ir/cache/builder/src/out/host_debug/flutter_web_sdk/lib/ui/src/ui/compositing.dart:343:12
[+1000 ms] Another exception was thrown: Assertion failed:
file:////b/s/w/ir/cache/builder/src/out/host_debug/flutter_web_sdk/lib/ui/src/ui/compositing.dart:343:12
[+1136 ms] Another exception was thrown: UnimplementedError
[ +869 ms] Another exception was thrown: Assertion failed:

file:////b/s/w/ir/cache/builder/src/out/host_debug/flutter_web_sdk/lib/_engine/engine/surface/surface.dart:1071:14
[ +991 ms] Another exception was thrown: Assertion failed:
file:////b/s/w/ir/cache/builder/src/out/host_debug/flutter_web_sdk/lib/ui/src/ui/compositing.dart:343:12
[ +999 ms] Another exception was thrown: Assertion failed:
file:////b/s/w/ir/cache/builder/src/out/host_debug/flutter_web_sdk/lib/ui/src/ui/compositing.dart:343:12
[ +999 ms] Another exception was thrown: Assertion failed:
file:////b/s/w/ir/cache/builder/src/out/host_debug/flutter_web_sdk/lib/ui/src/ui/compositing.dart:343:12
[+1000 ms] Another exception was thrown: Assertion failed:
file:////b/s/w/ir/cache/builder/src/out/host_debug/flutter_web_sdk/lib/ui/src/ui/compositing.dart:343:12
[ +999 ms] Another exception was thrown: Assertion failed:
file:////b/s/w/ir/cache/builder/src/out/host_debug/flutter_web_sdk/lib/ui/src/ui/compositing.dart:343:12
[+1000 ms] Another exception was thrown: Assertion failed:
file:////b/s/w/ir/cache/builder/src/out/host_debug/flutter_web_sdk/lib/ui/src/ui/compositing.dart:343:12
[ +999 ms] Another exception was thrown: Assertion failed:
file:////b/s/w/ir/cache/builder/src/out/host_debug/flutter_web_sdk/lib/ui/src/ui/compositing.dart:343:12
[+1002 ms] Another exception was thrown: Assertion failed:
file:////b/s/w/ir/cache/builder/src/out/host_debug/flutter_web_sdk/lib/ui/src/ui/compositing.dart:343:12
[ +999 ms] Another exception was thrown: Assertion failed:

```

```
$ flutter analyze
Analyzing clock_competition...                                          
No issues found! (ran in 1.9s)
```

```
$ flutter doctor -v
[✓] Flutter (Channel master, v1.10.6-pre.73, on Linux, locale en_US.UTF-8)
    • Flutter version 1.10.6-pre.73 at REDACTED_DIRECTORY/github-forks/flutter
    • Framework revision 9bd02a1787 (20 hours ago), 2019-09-25 13:55:29 -0700
    • Engine revision 0bfca375b3
    • Dart version 2.6.0 (build 2.6.0-dev.2.0 69b5681546)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at  REDACTED_DIRECTORY/Android/Sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-stable, build-tools 28.0.3
    • Java binary at: /opt/android-studio-with-blaze-3.5/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Android Studio (version 3.3)
    • Android Studio at  REDACTED_DIRECTORY/Downloads/android-studio
    • Flutter plugin version 34.0.1
    • Dart plugin version 182.5215
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)

[✓] Android Studio (version 3.4)
    • Android Studio at /opt/android-studio-with-blaze-3.4
    • Flutter plugin version 37.1.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b16-5323222)

[✓] Android Studio (version 3.5)
    • Android Studio at /opt/android-studio-with-blaze-3.5
    • Flutter plugin version 39.0.3
    • Dart plugin version 191.8423
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] VS Code (version 1.23.1)
    • VS Code at /usr/share/code
    • Flutter extension version 2.14.0

[✓] Connected device (2 available)
    • Chrome • chrome • web-javascript • Google Chrome 77.0.3865.90
    • Server • web    • web-javascript • Flutter Tools

• No issues found!
```

**Comment by jkurtw** [comment]
cc @ferhatb is this something that can be supported on the web?

**Comment by ferhatb** [comment]
cc @jkurtw : Can be supported using webgl shader. 
@maryx : Thanks for filing this. Not likely to be supported in the short term. We will be looking at linear/radial shaders for drawVertices APIs soon, we'll keep this in mind since that would provide a workaround before this is available.

**Comment by rydmike** [comment]
Thanks @yjbanov for quickly finding that my issues was a duplicate and pointing me here. I will be following this case instead then.

**Comment by iapicca** [comment]
Hi @maryx 
the issue seems to persist running the code below with the latest master

<details>
  <summary>code sample</summary>

```dart
import 'package:flutter/material.dart';
import 'dart:math' as math;

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) => MaterialApp(
        home: MyHomePage(),
      );
}

class MyHomePage extends StatelessWidget {
  const MyHomePage({Key key}) : super(key: key);

  @override
  Widget build(BuildContext context) => Material(
        child: Center(
          child: Container(
            decoration: BoxDecoration(
              gradient: SweepGradient(
                center: FractionalOffset.center,
                startAngle: -(math.pi / 2),
                endAngle: math.pi * 2 - (math.pi / 2),
                colors: const <Color>[
                  Color(0xFF4285F4), // blue
                  Color(0xFF34A853), // green
                  Color(0xFFFBBC05), // yellow
                  Color(0xFFEA4335), // red
                  Color(0xFF4285F4), // blue
                ],
                stops: const <double>[0.0, 0.25, 0.5, 0.75, 1.0],
              ),
            ),
          ),
        ),
      );
}

```

</details>

<details>
  <summary>flutter run -d chrome -v</summary>

```bash
[ +311 ms] Launching lib/main.dart on Chrome in debug mode...
[  +83 ms] Updating assets
[ +173 ms] Syncing files to device Chrome...
[  +64 ms] Generating /Users/nevercode/Desktop/projects/master/android/app/src/main/java/io/flutter/plugins/GeneratedPluginRegistrant.java
[  +52 ms] <- reset
[   +9 ms] /Users/nevercode/development/flutter_master/bin/cache/dart-sdk/bin/dart --disable-dart-dev
/Users/nevercode/development/flutter_master/bin/cache/artifacts/engine/darwin-x64/frontend_server.dart.snapshot --sdk-root
/Users/nevercode/development/flutter_master/bin/cache/flutter_web_sdk/ --incremental --target=dartdevc --debugger-module-names -Ddart.developer.causal_async_stacks=true
--output-dill /var/folders/c3/l5jpznsj5k37yrj47l__xpw40000gn/T/flutter_tools.S8Bzd6/flutter_tool.fMZ6L9/app.dill --libraries-spec
file:///Users/nevercode/development/flutter_master/bin/cache/flutter_web_sdk/libraries.json --packages .packages -Ddart.vm.profile=false -Ddart.vm.product=false
--bytecode-options=source-positions,local-var-info,debugger-stops,instance-field-initializers,keep-unreachable-code,avoid-closure-call-instructions --enable-asserts
--track-widget-creation --filesystem-root /var/folders/c3/l5jpznsj5k37yrj47l__xpw40000gn/T/flutter_tools.S8Bzd6/flutter_tools.tVTH8q --filesystem-scheme org-dartlang-app
--initialize-from-dill build/cache.dill.track.dill --platform file:///Users/nevercode/development/flutter_master/bin/cache/flutter_web_sdk/kernel/flutter_ddc_sdk.dill
[  +25 ms] <- compile org-dartlang-app:/web_entrypoint.dart
[+18281 ms] Syncing files to device Chrome... (completed in 18,418ms, longer than expected)
[   +1 ms] Synced 21.9MB.
[        ] <- accept
[        ] Caching compiled dill
[ +867 ms] [CHROME]:
[   +2 ms] [CHROME]:DevTools listening on ws://127.0.0.1:52697/devtools/browser/1ba19b19-8903-450a-835e-ed2e3a9ede60
[+5299 ms] Debug service listening on ws://127.0.0.1:52722/QIzuF6494BM=

[ +294 ms] Debug service listening on ws://127.0.0.1:52722/QIzuF6494BM=
[   +2 ms] Warning: Flutter's support for web development is not stable yet and hasn't
[        ] been thoroughly tested in production environments.
[        ] For more information see https://flutter.dev/web
[        ] 🔥  To hot restart changes while running, press "r" or "R".
[   +1 ms] For a more detailed help message, press "h". To quit, press "q".
[+1391 ms] ══╡ EXCEPTION CAUGHT BY SCHEDULER LIBRARY ╞═════════════════════════════════════════════════════════

[   +4 ms] The following UnimplementedError was thrown during a scheduler callback:

[   +1 ms] UnimplementedError

[   +1 ms] When the exception was thrown, this was the stack:

[        ] dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 214:49  throw_

[        ] lib/_engine/engine/shader.dart 54:5                                           createPaintStyle

[   +1 ms] lib/_engine/engine/canvas_pool.dart 801:23                                    setUpPaint

[   +1 ms] lib/_engine/engine/bitmap_canvas.dart 211:31                                  [_setUpPaint]

[        ] lib/_engine/engine/bitmap_canvas.dart 308:5                                   drawRect

[        ] lib/_engine/engine/surface/recording_canvas.dart 1046:11                      apply

[        ] lib/_engine/engine/surface/recording_canvas.dart 161:24                       apply

[        ] lib/_engine/engine/surface/picture.dart 272:19                                paintCallback

[        ] lib/_engine/engine/surface/surface.dart 48:14                                 commitScene

[        ] lib/_engine/engine/surface/scene_builder.dart 547:7                           <fn>

[   +4 ms] lib/_engine/engine/profiler.dart 36:18                                        timeAction

[   +1 ms] lib/_engine/engine/surface/scene_builder.dart 541:12                          build

[   +4 ms] packages/flutter/src/rendering/layer.dart 808:35                              buildScene

[   +1 ms] packages/flutter/src/rendering/view.dart 230:36                               compositeFrame

[   +1 ms] packages/flutter/src/rendering/binding.dart 406:18                            drawFrame

[        ] packages/flutter/src/widgets/binding.dart 884:13                              drawFrame

[        ] packages/flutter/src/rendering/binding.dart 284:5                             [_handlePersistentFrameCallback]

[   +1 ms] packages/flutter/src/scheduler/binding.dart 1113:15                           [_invokeFrameCallback]

[        ] packages/flutter/src/scheduler/binding.dart 1052:9                            handleDrawFrame

[        ] packages/flutter/src/scheduler/binding.dart 861:7                             <fn>

[        ] dart-sdk/lib/_internal/js_dev_runtime/private/isolate_helper.dart 48:19       internalCallback

[        ] ════════════════════════════════════════════════════════════════════════════════════════════════════

[   +1 ms] Another exception was thrown: UnimplementedError

[+8723 ms] Another exception was thrown: PersistedOffset: is in an unexpected state.

[+17514 ms] Stopped debug service on ws://127.0.0.1:52722

[  +69 ms] Application finished.
[   +2 ms] "flutter run" took 60,275ms.
[   +6 ms] Running shutdown hooks
[        ] Shutdown hook priority 4
[  +89 ms] Shutdown hooks complete
[        ] exiting with code 0
```


</details>

<details>
  <summary>flutter run -d chrome --dart-define=FLUTTER_WEB_USE_SKIA=true -v</summary>

```bash
[ +167 ms] Syncing files to device Chrome...
[  +64 ms] Generating /Users/nevercode/Desktop/projects/master/android/app/src/main/java/io/flutter/plugins/GeneratedPluginRegistrant.java
[  +49 ms] <- reset
[   +9 ms] /Users/nevercode/development/flutter_master/bin/cache/dart-sdk/bin/dart --disable-dart-dev
/Users/nevercode/development/flutter_master/bin/cache/artifacts/engine/darwin-x64/frontend_server.dart.snapshot --sdk-root
/Users/nevercode/development/flutter_master/bin/cache/flutter_web_sdk/ --incremental --target=dartdevc --debugger-module-names -Ddart.developer.causal_async_stacks=true
-DFLUTTER_WEB_USE_SKIA=true --output-dill /var/folders/c3/l5jpznsj5k37yrj47l__xpw40000gn/T/flutter_tools.JNHfXt/flutter_tool.IR4wuw/app.dill --libraries-spec
file:///Users/nevercode/development/flutter_master/bin/cache/flutter_web_sdk/libraries.json --packages .packages -Ddart.vm.profile=false -Ddart.vm.product=false
--bytecode-options=source-positions,local-var-info,debugger-stops,instance-field-initializers,keep-unreachable-code,avoid-closure-call-instructions --enable-asserts
--track-widget-creation --filesystem-root /var/folders/c3/l5jpznsj5k37yrj47l__xpw40000gn/T/flutter_tools.JNHfXt/flutter_tools.IbGfil --filesystem-scheme org-dartlang-app
--initialize-from-dill build/dfea9bfe94cb64da780a8ef62c567803.cache.dill.track.dill --platform
file:///Users/nevercode/development/flutter_master/bin/cache/flutter_web_sdk/kernel/flutter_ddc_sdk.dill
[  +22 ms] <- compile org-dartlang-app:/web_entrypoint.dart
[+12059 ms] Syncing files to device Chrome... (completed in 12,189ms, longer than expected)
[   +2 ms] Synced 21.5MB.
[   +1 ms] <- accept
[        ] Caching compiled dill
[ +812 ms] [CHROME]:
[   +2 ms] [CHROME]:DevTools listening on ws://127.0.0.1:52836/devtools/browser/ae9415bf-7100-44ab-89c9-f992d9eb0b6e
[+5234 ms] Debug service listening on ws://127.0.0.1:52857/zOlsqj40eDo=

[ +273 ms] Debug service listening on ws://127.0.0.1:52857/zOlsqj40eDo=
[   +2 ms] Warning: Flutter's support for web development is not stable yet and hasn't
[        ] been thoroughly tested in production environments.
[        ] For more information see https://flutter.dev/web
[        ] 🔥  To hot restart changes while running, press "r" or "R".
[   +1 ms] For a more detailed help message, press "h". To quit, press "q".
[+1482 ms] Error: Unsupported operation: Picture.toImage not yet implemented for CanvasKit and HTML
                        at Object.throw_ [as throw] (http://localhost:52826/dart_sdk.js:4322:11)
                        at _engine.CkPicture.new.toImage (http://localhost:52826/dart_sdk.js:140409:17)
                        at DefaultShaderWarmUp.execute (http://localhost:52826/packages/flutter/src/painting/shader_warm_up.dart.lib.js:106:23)
                        at execute.next (<anonymous>)
                        at http://localhost:52826/dart_sdk.js:37203:33
                        at _RootZone.runUnary (http://localhost:52826/dart_sdk.js:37057:58)
                        at _FutureListener.thenAwait.handleValue (http://localhost:52826/dart_sdk.js:32041:29)
                        at handleValueCallback (http://localhost:52826/dart_sdk.js:32588:49)
                        at Function._propagateToListeners (http://localhost:52826/dart_sdk.js:32626:17)
                        at _Future.new.[_completeWithValue] (http://localhost:52826/dart_sdk.js:32469:23)
                        at async._AsyncCallbackEntry.new.callback (http://localhost:52826/dart_sdk.js:32491:35)
                        at Object._microtaskLoop (http://localhost:52826/dart_sdk.js:37318:13)
                        at _startMicrotaskLoop (http://localhost:52826/dart_sdk.js:37324:13)
                        at http://localhost:52826/dart_sdk.js:32843:9
[ +873 ms] ══╡ EXCEPTION CAUGHT BY RENDERING LIBRARY ╞═════════════════════════════════════════════════════════

[   +2 ms] The following UnimplementedError was thrown during paint():

[        ] UnimplementedError

[   +2 ms] The relevant error-causing widget was:

[        ]   Container file:///Users/nevercode/Desktop/projects/master/lib/main.dart:19:18

[   +2 ms] When the exception was thrown, this was the stack:

[        ] dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 214:49  throw_

[   +1 ms] lib/_engine/engine/shader.dart 67:5                                           createSkiaShader

[        ] lib/_engine/engine/compositor/painting.dart 144:18                            [_syncShader]

[   +2 ms] lib/_engine/engine/compositor/painting.dart 138:5                             set shader

[   +5 ms] packages/flutter/src/painting/box_decoration.dart 406:14                      [_getBackgroundPaint]

[        ] packages/flutter/src/painting/box_decoration.dart 445:31                      [_paintBackgroundColor]

[        ] packages/flutter/src/painting/box_decoration.dart 480:5                       paint

[        ] packages/flutter/src/rendering/proxy_box.dart 2021:16                         paint

[  +11 ms] packages/flutter/src/rendering/object.dart 2264:7                             [_paintWithContext]

[        ] packages/flutter/src/rendering/object.dart 184:12                             paintChild

[        ] packages/flutter/src/rendering/shifted_box.dart 70:14                         paint

[        ] packages/flutter/src/rendering/object.dart 2264:7                             [_paintWithContext]

[        ] packages/flutter/src/rendering/object.dart 184:12                             paintChild

[        ] packages/flutter/src/rendering/proxy_box.dart 129:14                          paint

[        ] packages/flutter/src/material/material.dart 531:11                            paint

[        ] packages/flutter/src/rendering/object.dart 2264:7                             [_paintWithContext]

[  +12 ms] packages/flutter/src/rendering/object.dart 184:12                             paintChild

[   +1 ms] packages/flutter/src/rendering/proxy_box.dart 129:14                          paint

[        ] packages/flutter/src/rendering/object.dart 391:12                             pushLayer

[   +1 ms] packages/flutter/src/rendering/proxy_box.dart 1800:14                         paint

[        ] packages/flutter/src/rendering/object.dart 2264:7                             [_paintWithContext]

[        ] packages/flutter/src/rendering/object.dart 184:12                             paintChild

[        ] packages/flutter/src/rendering/proxy_box.dart 129:14                          paint

[   +1 ms] packages/flutter/src/rendering/object.dart 2264:7                             [_paintWithContext]

[        ] packages/flutter/src/rendering/object.dart 184:12                             paintChild

[        ] packages/flutter/src/rendering/proxy_box.dart 129:14                          paint

[        ] packages/flutter/src/rendering/object.dart 2264:7                             [_paintWithContext]

[        ] packages/flutter/src/rendering/object.dart 135:10                             _repaintCompositedChild

[        ] packages/flutter/src/rendering/object.dart 95:5                               repaintCompositedChild

[        ] packages/flutter/src/rendering/object.dart 201:7                              [_compositeChild]

[        ] packages/flutter/src/rendering/object.dart 182:7                              paintChild

[        ] packages/flutter/src/rendering/proxy_box.dart 129:14                          paint

[   +9 ms] packages/flutter/src/rendering/object.dart 2264:7                             [_paintWithContext]

[        ] packages/flutter/src/rendering/object.dart 184:12                             paintChild

[        ] packages/flutter/src/rendering/proxy_box.dart 912:16                          paint

[        ] packages/flutter/src/rendering/object.dart 2264:7                             [_paintWithContext]

[        ] packages/flutter/src/rendering/object.dart 184:12                             paintChild

[        ] packages/flutter/src/rendering/proxy_box.dart 129:14                          paint

[        ] packages/flutter/src/rendering/proxy_box.dart 2514:13                         paint

[        ] packages/flutter/src/rendering/object.dart 2264:7                             [_paintWithContext]

[        ] packages/flutter/src/rendering/object.dart 184:12                             paintChild

[        ] packages/flutter/src/rendering/proxy_box.dart 129:14                          paint

[        ] packages/flutter/src/rendering/object.dart 2264:7                             [_paintWithContext]

[        ] packages/flutter/src/rendering/object.dart 135:10                             _repaintCompositedChild

[        ] packages/flutter/src/rendering/object.dart 95:5                               repaintCompositedChild

[        ] packages/flutter/src/rendering/object.dart 201:7                              [_compositeChild]

[        ] packages/flutter/src/rendering/object.dart 182:7                              paintChild

[        ] packages/flutter/src/rendering/proxy_box.dart 129:14                          paint

[        ] packages/flutter/src/rendering/object.dart 2264:7                             [_paintWithContext]

[        ] packages/flutter/src/rendering/object.dart 184:12                             paintChild

[        ] packages/flutter/src/rendering/proxy_box.dart 129:14                          paint

[        ] packages/flutter/src/rendering/proxy_box.dart 3238:11                         paint

[        ] packages/flutter/src/rendering/object.dart 2264:7                             [_paintWithContext]

[        ] packages/flutter/src/rendering/object.dart 184:12                             paintChild

[        ] packages/flutter/src/widgets/overlay.dart 737:14                              paintStack

[        ] packages/flutter/src/widgets/overlay.dart 747:7                               paint

[        ] packages/flutter/src/rendering/object.dart 2264:7                             [_paintWithContext]

[        ] packages/flutter/src/rendering/object.dart 184:12                             paintChild

[        ] packages/flutter/src/rendering/proxy_box.dart 129:14                          paint

[        ] packages/flutter/src/rendering/object.dart 2264:7                             [_paintWithContext]

[        ] packages/flutter/src/rendering/object.dart 184:12                             paintChild

[        ] packages/flutter/src/rendering/proxy_box.dart 129:14                          paint

[        ] packages/flutter/src/rendering/object.dart 2264:7                             [_paintWithContext]

[   +6 ms] packages/flutter/src/rendering/object.dart 184:12                             paintChild

[        ] packages/flutter/src/rendering/proxy_box.dart 129:14                          paint

[        ] packages/flutter/src/rendering/object.dart 2264:7                             [_paintWithContext]

[   +1 ms] packages/flutter/src/rendering/object.dart 184:12                             paintChild

[   +1 ms] packages/flutter/src/rendering/proxy_box.dart 129:14                          paint

[        ] packages/flutter/src/rendering/custom_paint.dart 575:11                       paint

[        ] packages/flutter/src/rendering/object.dart 2264:7                             [_paintWithContext]

[        ] packages/flutter/src/rendering/object.dart 184:12                             paintChild

[        ] packages/flutter/src/rendering/proxy_box.dart 129:14                          paint

[        ] packages/flutter/src/rendering/object.dart 2264:7                             [_paintWithContext]

[        ] packages/flutter/src/rendering/object.dart 184:12                             paintChild

[        ] packages/flutter/src/rendering/proxy_box.dart 129:14                          paint

[        ] packages/flutter/src/rendering/object.dart 2264:7                             [_paintWithContext]

[        ] packages/flutter/src/rendering/object.dart 184:12                             paintChild

[   +6 ms] packages/flutter/src/rendering/view.dart 213:14                               paint

[        ] packages/flutter/src/rendering/object.dart 2264:7                             [_paintWithContext]

[        ] packages/flutter/src/rendering/object.dart 135:10                             _repaintCompositedChild

[        ] packages/flutter/src/rendering/object.dart 95:5                               repaintCompositedChild

[        ] packages/flutter/src/rendering/object.dart 980:29                             flushPaint

[        ] packages/flutter/src/rendering/binding.dart 404:19                            drawFrame

[        ] packages/flutter/src/widgets/binding.dart 884:13                              drawFrame

[        ] packages/flutter/src/rendering/binding.dart 284:5                             [_handlePersistentFrameCallback]

[   +4 ms] packages/flutter/src/scheduler/binding.dart 1113:15                           [_invokeFrameCallback]

[        ] packages/flutter/src/scheduler/binding.dart 1052:9                            handleDrawFrame

[        ] packages/flutter/src/scheduler/binding.dart 861:7                             <fn>

[        ] dart-sdk/lib/_internal/js_dev_runtime/private/isolate_helper.dart 48:19       internalCallback

[   +1 ms] The following RenderObject was being processed when the exception was fired: RenderDecoratedBox#731d6 relayoutBoundary=up1:

[        ]   creator: DecoratedBox ← Container ← Center ← DefaultTextStyle ← AnimatedDefaultTextStyle ←

[   +1 ms]     _InkFeatures-[GlobalKey#0fbdf ink renderer] ← NotificationListener<LayoutChangedNotification> ←

[        ]     PhysicalModel ← AnimatedPhysicalModel ← Material ← MyHomePage ← Semantics ← ⋯

[   +7 ms]   parentData: offset=Offset(0.0, 0.0) (can use size)

[        ]   constraints: BoxConstraints(0.0<=w<=1200.0, 0.0<=h<=683.0)

[        ]   size: Size(1200.0, 683.0)

[        ]   decoration: BoxDecoration:

[   +4 ms]     gradient: SweepGradient(FractionalOffset(0.5, 0.5), -1.5707963267948966, 4.71238898038469,

[        ]       [Color(0xff4285f4), Color(0xff34a853), Color(0xfffbbc05), Color(0xffea4335), Color(0xff4285f4)],

[        ]       [0, 0.25, 0.5, 0.75, 1], TileMode.clamp)

[        ]   configuration: ImageConfiguration(bundle: PlatformAssetBundle#38815(), devicePixelRatio: 1.0,

[        ]     locale: en_US, textDirection: TextDirection.ltr, platform: android)

[        ] This RenderObject had the following descendants (showing up to depth 5):

[        ]     child: RenderLimitedBox#cafb0 relayoutBoundary=up2 NEEDS-PAINT

[        ]       child: RenderConstrainedBox#3cb88 relayoutBoundary=up3 NEEDS-PAINT

[        ] ════════════════════════════════════════════════════════════════════════════════════════════════════

[+29174 ms] Stopped debug service on ws://127.0.0.1:52857

[  +68 ms] Application finished.
[   +2 ms] "flutter run" took 54,588ms.
[   +6 ms] Running shutdown hooks
[        ] Shutdown hook priority 4
[  +96 ms] Shutdown hooks complete
[        ] exiting with code 0
```

</details>


<details>
  <summary>doctor</summary>

```console
[✓] Flutter (Channel master, 1.20.0-3.0.pre.126, on Mac OS X 10.15.5 19F101, locale en-GB)
    • Flutter version 1.20.0-3.0.pre.126 at /Users/nevercode/development/flutter_master
    • Framework revision 462b0ea76e (16 hours ago), 2020-07-02 16:13:02 -0400
    • Engine revision 51ca1432b3
    • Dart version 2.9.0 (build 2.9.0-20.0.dev 8afe9875a6)


[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/nevercode/Library/Android/sdk
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.5, Build version 11E608c
    • CocoaPods version 1.9.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 46.0.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] VS Code
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.12.1

[✓] Connected device (3 available)
    • macOS (desktop)  • macos      • darwin-x64     • Mac OS X 10.15.5 19F101
    • Web Server (web) • web-server • web-javascript • Flutter Tools
    • Chrome (web)     • chrome     • web-javascript • Google Chrome 83.0.4103.116

• No issues found!
```

</details>

Thank you

**Comment by II11II** [comment]
The same error

**Comment by ferhatb** [comment]
PR landed in master channel.
![Screen Shot 2020-10-22 at 10 06 29 PM](https://user-images.githubusercontent.com/5061034/96958629-e8f47080-14b2-11eb-9ee6-95803ba3632e.png)

**Comment by felixblaschke** [comment]
@yjbanov 
This issue is not resolved. While `SweepGradient` expects it's angles given in radians (default values are 0 and 2*pi), the CanvasKit renderer takes these angles as degree. The result is a much smaller circle.

![sweep-broken](https://user-images.githubusercontent.com/26407468/101276643-9cd56500-37ae-11eb-8c96-2facc53934ab.png)
Gradient used default values 0 to 2*pi. (Flutter Web CanvasKit on master channel.)

There was an unmerged PR by @hterkelsen that addressed this issue: https://github.com/flutter/engine/pull/21677

**Comment by hterkelsen** [comment]
This is now fixed in CanvasKit as well.
