### ISSUE TITLE
Problem!!, While running a Simple Google Map App. Help Please

### ISSUE THREAD

**Issue by navidanchitrali** [flutter/flutter#41387]
## Steps to Reproduce

1. ...   I have a problem, while running a simple google map app, which does not show any error and the google map is not showing after running. It 
2. ... It show the exception that API KEY is not found, i have put it in the Andoid.xml file as well
```
<application
        android:name="io.flutter.app.FlutterApplication"
        android:label="google_map_app"
        android:icon="@mipmap/ic_launcher">



        <activity
            android:name=".MainActivity"
            android:launchMode="singleTop"
            android:theme="@style/LaunchTheme"
            android:configChanges="orientation|keyboardHidden|keyboard|screenSize|locale|layoutDirection|fontScale|screenLayout|density|uiMode"
            android:hardwareAccelerated="true"
            android:windowSoftInputMode="adjustResize">



            <!-- This keeps the window background of the activity showing
                 until Flutter renders its first frame. It can be removed if
                 there is no splash screen (such as the default splash screen
                 defined in @style/LaunchTheme). -->

            <meta-data android:name="com.google.android.geo.API_KEY"
                android:value=" "/>


            <meta-data
                android:name="io.flutter.app.android.SplashScreenUntilFirstFrame"
                android:value="true" />



            <intent-filter>
                <action android:name="android.intent.action.MAIN"/>
                <category android:name="android.intent.category.LAUNCHER"/>
            </intent-filter>
        </activity>
    </application>
```
3. ... Here is the OUT PUT after running. 
```
Syncing files to device CPH1717...
I/BufferQueue(24310): [unnamed-24310-0](this:0x70d2330000,id:0,api:0,p:-1,c:-1) BufferQueue core=(24310:com.navidan.google_map_app)
I/BufferQueueConsumer(24310): [unnamed-24310-0](this:0x70d2330000,id:0,api:0,p:-1,c:24310) connect(C): consumer=(24310:com.navidan.google_map_app) controlledByApp=true
I/BufferQueueConsumer(24310): [unnamed-24310-0](this:0x70d2330000,id:0,api:0,p:-1,c:24310) setConsumerName: unnamed-24310-0
I/BufferQueueConsumer(24310): [SurfaceTexture-0-24310-0](this:0x70d2330000,id:0,api:0,p:-1,c:24310) setConsumerName: SurfaceTexture-0-24310-0
I/GLConsumer(24310): [SurfaceTexture-0-24310-0] detachFromContext
I/BufferQueueConsumer(24310): [SurfaceTexture-0-24310-0](this:0x70d2330000,id:0,api:0,p:-1,c:24310) setDefaultBufferSize: width=720 height=1280
I/zzbz    (24310): Making Creator dynamically
I/BufferQueueProducer(24310): [SurfaceTexture-0-24310-0](this:0x70d2330000,id:0,api:1,p:339,c:24310) connect(P): api=1 producer=(339:???) producerControlledByApp=false
I/BufferQueueConsumer(24310): [SurfaceTexture-0-24310-0](this:0x70d2330000,id:0,api:1,p:339,c:24310) getReleasedBuffers: returning mask 0xffffffffffffffff
I/BufferQueueProducer(24310): [SurfaceTexture-0-24310-0](this:0x70d2330000,id:0,api:1,p:339,c:24310) new GraphicBuffer needed
D/GraphicBuffer(24310): register, handle(0x70ee0326c0) (w:720 h:1280 s:720 f:0x22 u:0x000900)
I/DynamiteModule(24310): Considering local module com.google.android.gms.maps_dynamite:0 and remote module com.google.android.gms.maps_dynamite:221
I/DynamiteModule(24310): Selected remote version of com.google.android.gms.maps_dynamite, version >= 221
V/DynamiteModule(24310): Dynamite loader version >= 2, using loadModule2NoCrashUtils
D/BufferQueueProducer(24310): [SurfaceTexture-0-24310-0](this:0x70d2330000,id:0,api:1,p:339,c:24310) cancelBuffer: slot 0
W/System  (24310): ClassLoader referenced unknown path: 
D/ApplicationLoaders(24310): ignored Vulkan layer search path /data/app/com.google.android.gms-1/lib/arm64:/data/app/com.google.android.gms-1/base.apk!/lib/arm64-v8a for namespace 0x70f9b430f0
D/BufferQueueProducer(24310): [SurfaceTexture-0-24310-0](this:0x70d2330000,id:0,api:1,p:339,c:24310) cancelBuffer: slot 0
D/BufferQueueProducer(24310): [SurfaceTexture-0-24310-0](this:0x70d2330000,id:0,api:1,p:339,c:24310) cancelBuffer: slot 0
W/ChimeraDebugLogger(24310): Singleton logger instance not set.
D/BufferQueueProducer(24310): [SurfaceTexture-0-24310-0](this:0x70d2330000,id:0,api:1,p:339,c:24310) cancelBuffer: slot 0
W/System  (24310): ClassLoader referenced unknown path: /data/user_de/0/com.google.android.gms/app_chimera/m/000000ad/n/arm64-v8a
D/BufferQueueProducer(24310): [SurfaceTexture-0-24310-0](this:0x70d2330000,id:0,api:1,p:339,c:24310) cancelBuffer: slot 0
D/BufferQueueProducer(24310): [SurfaceTexture-0-24310-0](this:0x70d2330000,id:0,api:1,p:339,c:24310) cancelBuffer: slot 0
I/Google Maps Android API(24310): Google Play services client version: 12451000
I/Google Maps Android API(24310): Google Play services package version: 19275020
E/MethodChannel#flutter/platform_views(24310): Failed to handle method call
E/MethodChannel#flutter/platform_views(24310): java.lang.RuntimeException: API key not found.  Check that <meta-data android:name="com.google.android.geo.API_KEY" android:value="your API key"/> is in the <application> element of AndroidManifest.xml
E/MethodChannel#flutter/platform_views(24310): 	at com.google.maps.api.android.lib6.drd.r.b(:com.google.android.gms.dynamite_mapsdynamite@19275050@19.2.75 (040406-269183835):22)
E/MethodChannel#flutter/platform_views(24310): 	at com.google.maps.api.android.lib6.auth.f.a(:com.google.android.gms.dynamite_mapsdynamite@19275050@19.2.75 (040406-269183835):82)
E/MethodChannel#flutter/platform_views(24310): 	at com.google.maps.api.android.lib6.impl.f.a(:com.google.android.gms.dynamite_mapsdynamite@19275050@19.2.75 (040406-269183835):41)
E/MethodChannel#flutter/platform_views(24310): 	at com.google.android.gms.maps.internal.CreatorImpl.a(:com.google.android.gms.dynamite_mapsdynamite@19275050@19.2.75 (040406-269183835):54)
E/MethodChannel#flutter/platform_views(24310): 	at com.google.android.gms.maps.internal.CreatorImpl.newMapViewDelegate(:com.google.android.gms.dynamite_mapsdynamite@19275050@19.2.75 (040406-269183835):32)
E/MethodChannel#flutter/platform_views(24310): 	at com.google.android.gms.maps.internal.j.a(:com.google.android.gms.dynamite_mapsdynamite@19275050@19.2.75 (040406-269183835):62)
E/MethodChannel#flutter/platform_views(24310): 	at cv.onTransact(:com.google.android.gms.dynamite_mapsdynamite@19275050@19.2.75 (040406-269183835):4)
E/MethodChannel#flutter/platform_views(24310): 	at android.os.Binder.transact(Binder.java:504)
E/MethodChannel#flutter/platform_views(24310): 	at com.google.android.gms.internal.maps.zza.zza(Unknown Source)
E/MethodChannel#flutter/platform_views(24310): 	at com.google.android.gms.maps.internal.zzf.zza(Unknown Source)
E/MethodChannel#flutter/platform_views(24310): 	at com.google.android.gms.maps.MapView$zzb.createDelegate(Unknown Source)
E/MethodChannel#flutter/platform_views(24310): 	at com.google.android.gms.dynamic.DeferredLifecycleHelper.zaa(Unknown Source)
E/MethodChannel#flutter/platform_views(24310): 	at com.google.android.gms.dynamic.DeferredLifecycleHelper.onCreate(Unknown Source)
E/MethodChannel#flutter/platform_views(24310): 	at com.google.android.gms.maps.MapView.onCreate(Unknown Source)
E/MethodChannel#flutter/platform_views(24310): 	at io.flutter.plugins.googlemaps.GoogleMapController.init(GoogleMapController.java:135)
E/MethodChannel#flutter/platform_views(24310): 	at io.flutter.plugins.googlemaps.GoogleMapBuilder.build(GoogleMapBuilder.java:32)
E/MethodChannel#flutter/platform_views(24310): 	at io.flutter.plugins.googlemaps.GoogleMapFactory.create(GoogleMapFactory.java:51)
E/MethodChannel#flutter/platform_views(24310): 	at io.flutter.plugin.platform.SingleViewPresentation.onCreate(SingleViewPresentation.java:158)
E/MethodChannel#flutter/platform_views(24310): 	at android.app.Dialog.dispatchOnCreate(Dialog.java:472)
E/MethodChannel#flutter/platform_views(24310): 	at android.app.Dialog.show(Dialog.java:332)
E/MethodChannel#flutter/platform_views(24310): 	at android.app.Presentation.show(Presentation.java:235)
E/MethodChannel#flutter/platform_views(24310): 	at io.flutter.plugin.platform.VirtualDisplayController.<init>(VirtualDisplayController.java:92)
E/MethodChannel#flutter/platform_views(24310): 	at io.flutter.plugin.platform.VirtualDisplayController.create(VirtualDisplayController.java:52)
E/MethodChannel#flutter/platform_views(24310): 	at io.flutter.plugin.platform.PlatformViewsController$1.createPlatformView(PlatformViewsController.java:97)
E/MethodChannel#flutter/platform_views(24310): 	at io.flutter.embedding.engine.systemchannels.PlatformViewsChannel$1.create(PlatformViewsChannel.java:87)
E/MethodChannel#flutter/platform_views(24310): 	at io.flutter.embedding.engine.systemchannels.PlatformViewsChannel$1.onMethodCall(PlatformViewsChannel.java:51)
E/MethodChannel#flutter/platform_views(24310): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:222)
E/MethodChannel#flutter/platform_views(24310): 	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:96)
E/MethodChannel#flutter/platform_views(24310): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:656)
E/MethodChannel#flutter/platform_views(24310): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/MethodChannel#flutter/platform_views(24310): 	at android.os.MessageQueue.next(MessageQueue.java:328)
E/MethodChannel#flutter/platform_views(24310): 	at android.os.Looper.loop(Looper.java:173)
E/MethodChannel#flutter/platform_views(24310): 	at android.app.ActivityThread.main(ActivityThread.java:6661)
E/MethodChannel#flutter/platform_views(24310): 	at java.lang.reflect.Method.invoke(Native Method)
E/MethodChannel#flutter/platform_views(24310): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1106)
E/MethodChannel#flutter/platform_views(24310): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:967)
D/GraphicBuffer(24310): register, handle(0x70d23f4080) (w:720 h:1280 s:720 f:0x1 u:0x000b00)
E/flutter (24310): [ERROR:flutter/lib/ui/ui_dart_state.cc(148)] Unhandled Exception: PlatformException(error, API key not found.  Check that <meta-data android:name="com.google.android.geo.API_KEY" android:value="your API key"/> is in the <application> element of AndroidManifest.xml, null)
E/flutter (24310): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:569:7)
E/flutter (24310): #1      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:316:33)
E/flutter (24310): <asynchronous suspension>
E/flutter (24310): #2      AndroidViewController._create (package:flutter/src/services/platform_views.dart:640:54)
E/flutter (24310): <asynchronous suspension>
E/flutter (24310): #3      AndroidViewController.setSize (package:flutter/src/services/platform_views.dart:557:14)
E/flutter (24310): <asynchronous suspension>
E/flutter (24310): #4      RenderAndroidView._sizePlatformView (package:flutter/src/rendering/platform_view.dart:174:29)
E/flutter (24310): <asynchronous suspension>
E/flutter (24310): #5      RenderAndroidView.performResize (package:flutter/src/rendering/platform_view.dart:155:5)
E/flutter (24310): #6      RenderObject.layout (package:flutter/src/rendering/object.dart:1686:9)
E/flutter (24310): #7      RenderStack.performLayout (package:flutter/src/rendering/stack.dart:510:15)
E/flutter (24310): #8      RenderObject.layout (package:flutter/src/rendering/object.dart:1701:7)
E/flutter (24310): #9      RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
E/flutter (24310): #10     RenderObject.layout (package:flutter/src/rendering/object.dart:1701:7)
E/flutter (24310): #11     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
E/flutter (24310): #12     RenderObject.layout (package:flutter/src/rendering/object.dart:1701:7)
E/flutter (24310): #13     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
E/flutter (24310): #14     RenderObject.layout (package:flutter/src/rendering/object.dart:1701:7)
E/flutter (24310): #15     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
E/flutter (24310): #16     RenderObject.layout (package:flutter/src/rendering/object.dart:1701:7)
E/flutter (24310): #17     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
E/flutter (24310): #18     RenderObject.layout (package:flutter/src/rendering/object.dart:1701:7)
E/flutter (24310): #19     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
E/flutter (24310): #20     RenderObject.layout (package:flutter/src/rendering/object.dart:1701:7)
E/flutter (24310): #21     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
E/flutter (24310): #22     RenderObject.layout (package:flutter/src/rendering/object.dart:1701:7)
E/flutter (24310): #23     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
E/flutter (24310): #24     RenderOffstage.performLayout (package:flutter/src/rendering/proxy_box.dart:3140:13)
E/flutter (24310): #25     RenderObject.layout (package:flutter/src/rendering/object.dart:1701:7)
E/flutter (24310): #26     RenderStack.performLayout (package:flutter/src/rendering/stack.dart:510:15)
E/flutter (24310): #27     RenderObject.layout (package:flutter/src/rendering/object.dart:1701:7)
E/flutter (24310): #28     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
E/flutter (24310): #29     RenderObject.layout (package:flutter/src/rendering/object.dart:1701:7)
E/flutter (24310): #30     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
E/flutter (24310): #31     RenderObject.layout (package:flutter/src/rendering/object.dart:1701:7)
E/flutter (24310): #32     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
E/flutter (24310): #33     RenderObject.layout (package:flutter/src/rendering/object.dart:1701:7)
E/flutter (24310): #34     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
E/flutter (24310): #35     RenderObject.layout (package:flutter/src/rendering/object.dart:1701:7)
E/flutter (24310): #36     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
E/flutter (24310): #37     RenderObject.layout (package:flutter/src/rendering/object.dart:1701:7)
E/flutter (24310): #38     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
E/flutter (24310): #39     RenderObject.layout (package:flutter/src/rendering/object.dart:1701:7)
E/flutter (24310): #40     RenderView.performLayout (package:flutter/src/rendering/view.dart:152:13)
E/flutter (24310): #41     RenderObject._layoutWithoutResize (package:flutter/src/rend
D/BufferQueueProducer(24310): [SurfaceTexture-0-24310-0](this:0x70d2330000,id:0,api:1,p:339,c:24310) cancelBuffer: slot 0
D/BufferQueueProducer(24310): [SurfaceTexture-0-24310-0](this:0x70d2330000,id:0,api:1,p:339,c:24310) cancelBuffer: slot 0
D/BufferQueueProducer(24310): [SurfaceTexture-0-24310-0](this:0x70d2330000,id:0,api:1,p:339,c:24310) cancelBuffer: slot 0
D/OpenGLRenderer(24310): ProgramCache.generateProgram: 34359738369
D/BufferQueueProducer(24310): [SurfaceTexture-0-24310-0](this:0x70d2330000,id:0,api:1,p:339,c:24310) cancelBuffer: slot 0
D/BufferQueueProducer(24310): [SurfaceTexture-0-24310-0](this:0x70d2330000,id:0,api:1,p:339,c:24310) cancelBuffer: slot 0
D/BufferQueueProducer(24310): [SurfaceTexture-0-24310-0](this:0x70d2330000,id:0,api:1,p:339,c:24310) cancelBuffer: slot 0
D/BufferQueueProducer(24310): [SurfaceTexture-0-24310-0](this:0x70d2330000,id:0,api:1,p:339,c:24310) cancelBuffer: slot 0
D/BufferQueueProducer(24310): [SurfaceTexture-0-24310-0](this:0x70d2330000,id:0,api:1,p:339,c:24310) cancelBuffer: slot 0
D/BufferQueueProducer(24310): [SurfaceTexture-0-24310-0](this:0x70d2330000,id:0,api:1,p:339,c:24310) cancelBuffer: slot 0
D/BufferQueueProducer(24310): [SurfaceTexture-0-24310-0](this:0x70d2330000,id:0,api:1,p:339,c:24310) cancelBuffer: slot 0
D/BufferQueueProducer(24310): [SurfaceTexture-0-24310-0](this:0x70d2330000,id:0,api:1,p:339,c:24310) cancelBuffer: slot 0
D/BufferQueueProducer(24310): [SurfaceTexture-0-24310-0](this:0x70d2330000,id:0,api:1,p:339,c:24310) cancelBuffer: slot 0
D/BufferQueueProducer(24310): [SurfaceTexture-0-24310-0](this:0x70d2330000,id:0,api:1,p:339,c:24310) cancelBuffer: slot 0
D/BufferQueueProducer(24310): [SurfaceTexture-0-24310-0](this:0x70d2330000,id:0,api:1,p:339,c:24310) cancelBuffer: slot 0
D/BufferQueueProducer(24310): [SurfaceTexture-0-24310-0](this:0x70d2330000,id:0,api:1,p:339,c:24310) cancelBuffer: slot 0
```
```
C:\Users\hnawe\dartproject\google_map_app>flutter analyze
Analyzing google_map_app...
No issues found! (ran in 20.3s)
```
```  
NO ISSUE FOUND IN FLUTTER DOCTOR
```

**Comment by BondarenkoStas** [comment]
@navidanchitrali I wonder, will it write it as standard? 
```
    <meta-data
        android:name="com.google.android.geo.API_KEY"
        android:value="YOUR_API_KEY"/>
```
(you have no new line after meta-data)

**Comment by navidanchitrali** [comment]
@BondarenkoStas It doesn't work for me by putting into new line.
When i run the program it just show the black screen

**Comment by charkala** [comment]
The `<meta-data />` tag should be under `<application>` **NOT** `<activity>`.

**Comment by navidanchitrali** [comment]
@charkala  thanks alot. I have done it before, but this time work for me

**Comment by navidanchitrali** [comment]
@charkala  thanks alot. I have done it before, but this time work for me

**Comment by BondarenkoStas** [comment]
Ok, then I think it's safe to close the issue. If you have something new to add, please comment and I will re-open it.

**Comment by artikarande5** [comment]
I am also getting the same issue on android 10 MI 

D/BufferQueueProducer(22153): [SurfaceTexture-0-22153-1](this:0x77690ac800,id:1,api:1,p:579,c:22153) cancelBuffer: slot 0
I/BufferQueueProducer(22153): [SurfaceTexture-0-22153-1](this:0x77690ac800,id:1,api:1,p:579,c:22153) queueBuffer: slot 1 is dropped
I/BufferQueueProducer(22153): [SurfaceTexture-0-22153-1](this:0x77690ac800,id:1,api:1,p:579,c:22153) queueBuffer: slot 0 is dropped, handle=0x76c56e1c80
I/BufferQueueProducer(22153): [SurfaceTexture-0-22153-1](this:0x77690ac800,id:1,api:1,p:579,c:22153) queueBuffer: slot 1 is dropped, handle=0x76c5c3f880
I/BufferQueueProducer(22153): [SurfaceTexture-0-22153-1](this:0x77690ac800,id:1,api:1,p:579,c:22153) queueBuffer: slot 0 is dropped, handle=0x76c56e1c80
I/BufferQueueProducer(22153): [SurfaceTexture-0-22153-1](this:0x77690ac800,id:1,api:1,p:579,c:22153) queueBuffer: slot 1 is dropped, handle=0x76c5c3f880
I/BufferQueueProducer(22153): [SurfaceTexture-0-22153-1](this:0x77690ac800,id:1,api:1,p:579,c:22153) queueBuffer: slot 0 is dropped, handle=0x76c56e1c80
I/BufferQueueProducer(22153): [SurfaceTexture-0-22153-1](this:0x77690ac800,id:1,api:1,p:579,c:22153) queueBuffer: slot 1 is dropped, handle=0x76c5c3f880
I/BufferQueueProducer(22153): [SurfaceTexture-0-22153-1](this:0x77690ac800,id:1,api:1,p:579,c:22153) queueBuffer: slot 0 is dropped, handle=0x76c56e1c80
I/BufferQueueProducer(22153): [SurfaceTexture-0-22153-1](this:0x77690ac800,id:1,api:1,p:579,c:22153) queueBuffer: slot 1 is dropped, handle=0x76c5c3f880
I/BufferQueueProducer(22153): [SurfaceTexture-0-22153-1](this:0x77690ac800,id:1,api:1,p:579,c:22153) queueBuffer: slot 0 is dropped, handle=0x76c56e1c80
I/BufferQueueProducer(22153): [SurfaceTexture-0-22153-1](this:0x77690ac800,id:1,api:1,p:579,c:22153) queueBuffer: slot 1 is dropped, handle=0x76c5c3f880
I/BufferQueueProducer(22153): [SurfaceTexture-0-22153-1](this:0x77690ac800,id:1,api:1,p:579,c:22153) queueBuffer: slot 0 is dropped, handle=0x76c56e1c80
I/BufferQueueProducer(22153): [SurfaceTexture-0-22153-1](this:0x77690ac800,id:1,api:1,p:579,c:22153) queueBuffer: slot 1 is dropped, handle=0x76c5c3f880
I/BufferQueueProducer(22153): [SurfaceTexture-0-22153-1](this:0x77690ac800,id:1,api:1,p:579,c:22153) queueBuffer: slot 0 is dropped, handle=0x76c56e1c80
I/BufferQueueProducer(22153): [SurfaceTexture-0-22153-1](this:0x77690ac800,id:1,api:1,p:579,c:22153) queueBuffer: slot 1 is dropped, handle=0x76c5c3f880
I/BufferQueueProducer(22153): [SurfaceTexture-0-22153-1](this:0x77690ac800,id:1,api:1,p:579,c:22153) queueBuffer: slot 0 is dropped, handle=0x76c56e1c80
I/BufferQueueProducer(22153): [SurfaceTexture-0-22153-1](this:0x77690ac800,id:1,api:1,p:579,c:22153) queueBuffer: slot 1 is dropped, handle=0x76c5c3f880
I/BufferQueueProducer(22153): [SurfaceTexture-0-22153-1](this:0x77690ac800,id:1,api:1,p:579,c:22153) queueBuffer: slot 0 is dropped, handle=0x76c56e1c80
I/BufferQueueProducer(22153): [SurfaceTexture-0-22153-1](this:0x77690ac800,id:1,api:1,p:579,c:22153) queueBuffer: slot 1 is dropped, handle=0x76c5c3f880
I/BufferQueueProducer(22153): [SurfaceTexture-0-22153-1](this:0x77690ac800,id:1,api:1,p:579,c:22153) queueBuffer: slot 0 is dropped, handle=0x76c56e1c80
I/BufferQueueProducer(22153): [SurfaceTexture-0-22153-1](this:0x77690ac800,id:1,api:1,p:579,c:22153) queueBuffer: slot 1 is dropped, handle=0x76c5c3f880
I/BufferQueueProducer(22153): [SurfaceTexture-0-22153-1](this:0x77690ac800,id:1,api:1,p:579,c:22153) queueBuffer: slot 0 is dropped, handle=0x76c56e1c80
I/BufferQueueProducer(22153): [SurfaceTexture-0-22153-1](this:0x77690ac800,id:1,api:1,p:579,c:22153) queueBuffer: slot 1 is dropped, handle=0x76c5c3f880
I/BufferQueueProducer(22153): [SurfaceTexture-0-22153-1](this:0x77690ac800,id:1,api:1,p:579,c:22153) queueBuffer: slot 0 is dropped, handle=0x76c56e1c80
I/BufferQueueProducer(22153): [SurfaceTexture-0-22153-1](this:0x77690ac800,id:1,api:1,p:579,c:22153) queueBuffer: slot 1 is dropped, handle=0x76c5c3f880
I/BufferQueueProducer(22153): [SurfaceTexture-0-22153-1](this:0x77690ac800,id:1,api:1,p:579,c:22153) queueBuffer: slot 0 is dropped, handle=0x76c56e1c80
I/BufferQueueProducer(22153): [SurfaceTexture-0-22153-1](this:0x77690ac800,id:1,api:1,p:579,c:22153) queueBuffer: slot 1 is dropped, handle=0x76c5c3f880
I/BufferQueueProducer(22153): [SurfaceTexture-0-22153-1](this:0x77690ac800,id:1,api:1,p:579,c:22153) queueBuffer: slot 0 is dropped, handle=0x76c56e1c80
D/ViewRootImpl(22153): [TouchInput][ViewRootImpl] KeyEvent { action=ACTION_DOWN, keyCode=KEYCODE_BACK, scanCode=0, metaState=0, flags=0x48, repeatCount=0, eventTime=138556335, downTime=138556335, deviceId=-1, source=0x101, displayId=-1 }
I/BufferQueueProducer(22153): [SurfaceTexture-0-22153-1](this:0x77690ac800,id:1,api:1,p:579,c:22153) queueBuffer: slot 1 is dropped, handle=0x76c5c3f880
I/BufferQueueProducer(22153): [SurfaceTexture-0-22153-1](this:0x77690ac800,id:1,api:1,p:579,c:22153) queueBuffer: slot 0 is dropped, handle=0x76c56e1c80
D/ViewRootImpl(22153): [TouchInput][ViewRootImpl] KeyEvent { action=ACTION_UP, keyCode=KEYCODE_BACK, scanCode=0, metaState=0, flags=0x48, repeatCount=0, eventTime=138556368, downTime=138556335, deviceId=-1, source=0x101, displayId=-1 }
I/BufferQueueProducer(22153): [SurfaceTexture-0-22153-1](this:0x77690ac800,id:1,api:1,p:579,c:22153) queueBuffer: slot 1 is dropped, handle=0x76c5c3f880

I need help!

**Comment by artikarande5** [comment]
I try with hiding map visibility when I navigate to other screens, whenever map is required then only showing map visibility. it works for me for android 10 flickering issue. Also this will avoid all unnecessary log print

**Comment by PabloLema** [comment]
Hi, this bug is driving me crazy, doing some tests I put any value where the google API KEY for maps should go and the map loads normally in the application and the infinite log remains. So my conclusion is that somehow the api key that we put in the meta-data is not being recognized and it doesn't matter if it is correct or incorrect.
