### ISSUE TITLE
[ERROR:flutter/lib/ui/ui_dart_state.cc(148)] Unhandled Exception: FormatException: Invalid character

### ISSUE THREAD

**Issue by Medrov** [flutter/flutter#41390]
When I open other app with this [library](https://pub.dev/packages/intent#-readme-tab-), I get in console this error:

```
E/flutter (14176): [ERROR:flutter/lib/ui/ui_dart_state.cc(148)] Unhandled Exception: FormatException: Invalid character (at character 18)
E/flutter (14176): www.instagram.com/overlordstudio/
E/flutter (14176):                  ^
E/flutter (14176): 
E/flutter (14176): #0      _Uri._fail (dart:core/uri.dart:1623:5)
E/flutter (14176): #1      _Uri._normalizeRegName (dart:core/uri.dart:2147:9)
E/flutter (14176): #2      _Uri._makeHost (dart:core/uri.dart:2002:12)
E/flutter (14176): #3      new _Uri (dart:core/uri.dart:1513:12)
E/flutter (14176): #4      _AboutUsScreenState._launchURL (package:samuraigym/main_handler_children/info_page.dart:127:19)
E/flutter (14176): <asynchronous suspension>
E/flutter (14176): #5      _AboutUsScreenState._itemListSoso.<anonymous closure> (package:samuraigym/main_handler_children/info_page.dart:177:11)
E/flutter (14176): #6      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:182:24)
E/flutter (14176): #7      TapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:365:11)
E/flutter (14176): #8      TapGestureRecognizer.acceptGesture (package:flutter/src/gestures/tap.dart:312:7)
E/flutter (14176): #9      GestureArenaManager.sweep (package:flutter/src/gestures/arena.dart:156:27)
E/flutter (14176): #10     GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:222:20)
E/flutter (14176): #11     GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:198:22)
E/flutter (14176): #12     GestureBinding._handlePointerEvent (package:flutter/src/gestures/binding.dart:156:7)
E/flutter (14176): #13     GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:102:7)
E/flutter (14176): #14     GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:86:7)
E/flutter (14176): #15     _rootRunUnary (dart:async/zone.dart:1136:13)
E/flutter (14176): #16     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
E/flutter (14176): #17     _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
E/flutter (14176): #18     _invoke1 (dart:ui/hooks.dart:263:10)
E/flutter (14176): #19     _dispatchPointerDataPacket (dart:ui/hooks.dart:172:5)
E/flutter (14176): 
```

> `I have used this code:`

```
import 'package:intent/intent.dart' as intent;
import 'package:intent/action.dart' as action;

 // some code

 urls = [
    "www.instagram.com/overlordstudio/",
     ...
  ];

 // some code

_launchURL(int index) async {
   // some code
      intent.Intent()
        ..setAction(action.Action.ACTION_VIEW)
        ..setData(Uri(scheme: "https", host: urls[index]))
        ..startActivity().catchError((e) => print(e));
    
  }
```

**Comment by BondarenkoStas** [comment]
@Medrov Please provide your flutter doctor -v output. Also I think it would make sense to post the issue to https://github.com/itzmeanjan/intent/issues as well, as it's not a standart flutter plugin.

**Comment by stuartmorgan** [comment]
This isn't related to the intent package; the failure is in trying to construct the Uri argument (because the arguments being passed are invalid), so it's never even calling into the package.

@Mendrov See [the Uri] documentation. The host argument is just the host, not the whole post-scheme part of the URL.
