### ISSUE TITLE
NoSuchMethodError while running driver test on macos. I am receiving similar errors on any device other than android/ios

### ISSUE THREAD

**Issue by donkii** [flutter/flutter#41454]
## command

flutter drive --target=test_driver/app.dart

## exception

NoSuchMethodError: NoSuchMethodError: The getter 'index' was called on null.
Receiver: null
Tried calling: index

```
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:51:5)
#1      getNameForBuildMode (package:flutter_tools/src/build_info.dart:130:33)
#2      BuildableMacOSApp.applicationBundle (package:flutter_tools/src/macos/application_package.dart:135:21)
#3      BuildableMacOSApp.executable (package:flutter_tools/src/macos/application_package.dart:141:30)
#4      MacOSDevice.stopApp (package:flutter_tools/src/macos/macos_device.dart:126:28)
<asynchronous suspension>
#5      _stopApp (package:flutter_tools/src/commands/drive.dart:329:45)
<asynchronous suspension>
#6      _startApp (package:flutter_tools/src/commands/drive.dart:242:19)
<asynchronous suspension>
#7      DriveCommand.runCommand (package:flutter_tools/src/commands/drive.dart:124:51)
<asynchronous suspension>
#8      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:535:18)
#9      _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:71:64)
#10     _rootRunUnary (dart:async/zone.dart:1132:38)
#11     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#12     _FutureListener.handleValue (dart:async/future_impl.dart:137:18)
#13     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:678:45)
#14     Future._propagateToListeners (dart:async/future_impl.dart:707:32)
#15     Future._completeWithValue (dart:async/future_impl.dart:522:5)
#16     Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:552:7)
#17     _rootRun (dart:async/zone.dart:1124:13)
#18     _CustomZone.run (dart:async/zone.dart:1021:19)
#19     _CustomZone.runGuarded (dart:async/zone.dart:923:7)
#20     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:963:23)
#21     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#22     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#23     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:116:13)
#24     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:173:5)
```

## flutter doctor

```
[32m[✓][39m Flutter (Channel master, v1.10.7-pre.25, on Mac OS X 10.14.6 18G95, locale en-US)
    [32m•[39m Flutter version 1.10.7-pre.25 at /Users/donatkajtazi/Development/Flutter-SDK/flutter
    [32m•[39m Framework revision e47a1dc216 (18 hours ago), 2019-09-26 07:18:25 -0700
    [32m•[39m Engine revision 9fd35df9bb
    [32m•[39m Dart version 2.6.0 (build 2.6.0-dev.0.0 dd65f97118)

[32m[✓][39m Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    [32m•[39m Android SDK at /Users/donatkajtazi/Library/Android/sdk
    [32m•[39m Android NDK location not configured (optional; useful for native profiling support)
    [32m•[39m Platform android-29, build-tools 29.0.2
    [32m•[39m Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    [32m•[39m Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    [32m•[39m All Android licenses accepted.

[32m[✓][39m Xcode - develop for iOS and macOS (Xcode 11.0)
    [32m•[39m Xcode at /Applications/Xcode.app/Contents/Developer
    [32m•[39m Xcode 11.0, Build version 11A420a
    [32m•[39m CocoaPods version 1.7.5

[32m[✓][39m Chrome - develop for the web
    [32m•[39m Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[32m[✓][39m Android Studio (version 3.5)
    [32m•[39m Android Studio at /Applications/Android Studio.app/Contents
    [32m•[39m Flutter plugin version 39.0.3
    [32m•[39m Dart plugin version 191.8423
    [32m•[39m Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[32m[✓][39m Connected device (3 available)
    [32m•[39m macOS  • macOS  • darwin-x64     • Mac OS X 10.14.6 18G95
    [32m•[39m Chrome • chrome • web-javascript • Google Chrome 77.0.3865.90
    [32m•[39m Server • web    • web-javascript • Flutter Tools

[32m•[39m No issues found!
```

**Comment by stuartmorgan** [comment]
The `_lastBuiltMode` construction assumes `stopApp` is running from within (or after) `startApp`, which isn't a valid assumption. We need a more robust implementation of `stopApp` for macOS and Linux.

**Comment by donkii** [comment]
@stuartmorgan is there something I can do as a user to fix this?

**Comment by stuartmorgan** [comment]
Not without modifying the Flutter tool code.

**Comment by stuartmorgan** [comment]
> We need a more robust implementation

Actually, since on desktop we only want to stop instances started by the tool, we could just make it a no-op if `_lastBuiltMode` is null. In fact, I wonder if we could eliminate all the `ps` logic for macOS and Linux and instead track the PID of processes we've started via `startApp`, and using that for `stopApp`.
