### ISSUE TITLE
flutter and tools dynlib errors on ios

### ISSUE THREAD

**Issue by rbucker** [flutter/flutter#41468]
Something happened to my flutter installation. By default ios installs idevice_id and the other related libimobiledevices libraries for talking to ios devices. For some reason the tools either never get associated or they become disassociated from their libs. So when they are executed they produce exactly that output

```
$ /Users/rbucker/dev/flutter/bin/cache/artifacts/libimobiledevice/idevice_id
dyld: Library not loaded: /b/s/w/ir/k/homebrew/Cellar/libimobiledevice-flutter/HEAD-398c120_3/lib/libimobiledevice.6.dylib
  Referenced from: /Users/rbucker/dev/flutter/bin/cache/artifacts/libimobiledevice/idevice_id
  Reason: image not found
Abort trap: 6
```

[a] Nothing would repair this error... ie ```flutter upgrade```. [b] it did not produce an error just ```no devices available```.

My first repair was to delete the failing utils and rely on the system path to my ```brew``` installation. Then after a crappy night's sleep, TMI, I decided that I should just delete flutter and re-install it. That worked even though I did not remove the ```brew``` installed tools.

So, while this is meant to document an experience for others... I think there are some potential actionable items like detecting when the tool fails for system reasons separately from normal operation.

**Comment by escamoteur** [comment]
Could you please add the output of flutter doctor here?
On which ios version are you?

**Comment by jmagman** [comment]
@christopherfujino

**Comment by christopherfujino** [comment]
@rbucker can you try `rm -rf /Users/rbucker/dev/flutter/bin/cache && flutter doctor -v` and see if that detects your device? The cached idevice_id artifact was briefly broken last week, re-downloading it should fix.

**Comment by rbucker** [comment]
@christopherfujino nice idea.  I tried that, however, since the cache includes the dart-sdk the flutter command stopped working complaining that dart no longer existed.

**Comment by christopherfujino** [comment]
@rbucker the `flutter/bin/flutter` script should download the dart-sdk if it's not there. The only way that you would get an error for a missing dart sdk would be if you had no dart-sdk but you *did* have a stamp file (we generate that right after the dart sdk is successfully downloaded) at `flutter/bin/cache/engine-dart-sdk.stamp`. The logic for this you can find in `flutter/bin/internal/update_dart_sdk.sh`.

If you `rm -rf /Users/rbucker/dev/flutter/bin/cache && flutter doctor -v` it will delete both your cached artifacts AND all of the stamp files, leading the tool to re-download them. Please let me know if that works!

**Comment by rbucker** [comment]
@christopherfujino What you're recommending makes sense. however. limiting the test to the stamp file is clearly not enough. In addition, in my case I believe I deleted the entire... cache. I also tried the "precache" flag which the DOC says or implies that my problem should have been corrected.  ALSO all these flags are kinda bogus, really!! Since the flutter SDK is effectively not effected or customized per project the default repair should be delete and reinstall. But that's a separate issue.

**Comment by siliconsorcery** [comment]
Same problem
```
/Users/john/flutter/bin/cache/artifacts/libimobiledevice/idevice_id 
dyld: Library not loaded: /b/s/w/ir/k/homebrew/Cellar/libimobiledevice-flutter/HEAD-398c120_3/lib/libimobiledevice.6.dylib
  Referenced from: /Users/john/flutter/bin/cache/artifacts/libimobiledevice/idevice_id
  Reason: image not found
Abort trap: 6
```
Tried
`rm -rf /Users/john/flutter/bin/cache`
and
`flutter doctor -v`
with result
```
Downloading Dart SDK from Flutter engine 49815128157d80803da9f36c69493b2a09aacd03...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  260M  100  260M    0     0  6218k      0  0:00:42  0:00:42 --:--:-- 6387k
Building flutter tool...
Downloading Material fonts...                                       0.8s
Downloading Gradle Wrapper...                                       0.3s
Downloading android-arm-profile/darwin-x64 tools...                 0.8s
Downloading android-arm-release/darwin-x64 tools...                 0.7s
Downloading android-arm64-profile/darwin-x64 tools...               0.8s
Downloading android-arm64-release/darwin-x64 tools...               0.7s
Downloading package sky_engine...                                   0.6s
Downloading common tools...                                         1.8s
Downloading common tools...                                         1.8s
Downloading darwin-x64 tools...                                     6.3s
Downloading libimobiledevice...                                     0.2s
Downloading usbmuxd...                                              0.2s
Downloading libplist...                                             0.2s
Downloading openssl...                                              0.4s
Downloading ideviceinstaller...                                     0.2s
Downloading ios-deploy...                                           0.2s
[✓] Flutter (Channel master, v1.10.7-pre.99, on Mac OS X 10.14.4 18E226, locale en-US)
    • Flutter version 1.10.7-pre.99 at /Users/john/flutter
    • Framework revision 2de1e4f4a1 (14 hours ago), 2019-09-30 22:05:53 -0400
    • Engine revision 4981512815
    • Dart version 2.6.0 (build 2.6.0-dev.0.0 692230b484)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/john/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • ANDROID_HOME = /Users/john/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.0, Build version 11A420a
    • CocoaPods version 1.7.5

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 39.0.3
    • Dart plugin version 191.8423
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] VS Code (version 1.38.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.4.1

 
[☠] Connected device (the doctor check crashed)
    ✗ Due to an error, the doctor check did not complete. If the error message below is not helpful, please let us know about this issue at https://github.com/flutter/flutter/issues.
    ✗ Exception: ideviceinfo returned an error:
      ERROR: Could not connect to lockdownd, error code -8

    • #0      IMobileDevice.getInfoForDevice (package:flutter_tools/src/ios/mac.dart:226:9)
      <asynchronous suspension>
      #1      IOSDevice.getAttachedDevices (package:flutter_tools/src/ios/devices.dart:183:55)
      <asynchronous suspension>
      #2      IOSDevices.pollingGetDevices (package:flutter_tools/src/ios/devices.dart:114:57)
      #3      PollingDeviceDiscovery.devices (package:flutter_tools/src/device.dart:278:52)
      <asynchronous suspension>
      #4      DeviceManager.getAllConnectedDevices (package:flutter_tools/src/device.dart:138:46)
      <asynchronous suspension>
      #5      DeviceValidator.validate (package:flutter_tools/src/doctor.dart:842:54)
      <asynchronous suspension>
      #6      asyncGuard.<anonymous closure> (package:flutter_tools/src/base/async_guard.dart:111:32)
      <asynchronous suspension>
      #7      _rootRun (dart:async/zone.dart:1124:13)
      #8      _CustomZone.run (dart:async/zone.dart:1021:19)
      #9      _runZoned (dart:async/zone.dart:1516:10)
      #10     runZoned (dart:async/zone.dart:1500:12)
      #11     asyncGuard (package:flutter_tools/src/base/async_guard.dart:109:3)
      #12     Doctor.startValidatorTasks (package:flutter_tools/src/doctor.dart:158:9)
      #13     Doctor.diagnose (package:flutter_tools/src/doctor.dart:252:41)
      #14     _AsyncAwaitCompleter.start (dart:async-patch/async_patch.dart:43:6)
      #15     Doctor.diagnose (package:flutter_tools/src/doctor.dart:241:24)
      #16     DoctorCommand.runCommand (package:flutter_tools/src/commands/doctor.dart:59:39)
      #17     _AsyncAwaitCompleter.start (dart:async-patch/async_patch.dart:43:6)
      #18     DoctorCommand.runCommand (package:flutter_tools/src/commands/doctor.dart:45:42)
      #19     FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:553:18)
      #20     _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:71:64)
      #21     _rootRunUnary (dart:async/zone.dart:1132:38)
      #22     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
      #23     _FutureListener.handleValue (dart:async/future_impl.dart:137:18)
      #24     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:678:45)
      #25     Future._propagateToListeners (dart:async/future_impl.dart:707:32)
      #26     Future._completeWithValue (dart:async/future_impl.dart:522:5)
      #27     Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:552:7)
      #28     _rootRun (dart:async/zone.dart:1124:13)
      #29     _CustomZone.run (dart:async/zone.dart:1021:19)
      #30     _CustomZone.runGuarded (dart:async/zone.dart:923:7)
      #31     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:963:23)
      #32     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
      #33     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
      #34     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:391:30)
      #35     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:416:5)
      #36     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:12)


! Doctor found issues in 1 category.
```

**Comment by siliconsorcery** [comment]
Reinstalled flutter from instructions 
`https://flutter.dev/docs/get-started/install/macos`

ran
`flutter doctor -v`

with result
```
[✓] Flutter (Channel stable, v1.9.1+hotfix.4, on Mac OS X 10.14.4 18E226, locale en-US)
    • Flutter version 1.9.1+hotfix.4 at /Users/john/flutter
    • Framework revision cc949a8e8b (4 days ago), 2019-09-27 15:04:59 -0700
    • Engine revision b863200c37
    • Dart version 2.5.0

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/john/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • ANDROID_HOME = /Users/john/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.0, Build version 11A420a
    • CocoaPods version 1.7.5

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 39.0.3
    • Dart plugin version 191.8423
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] VS Code (version 1.38.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.4.1

ideviceinfo returned an error:
ERROR: Could not connect to lockdownd, error code -8



#0      IMobileDevice.getInfoForDevice (package:flutter_tools/src/ios/mac.dart:228:9)
<asynchronous suspension>
#1      IOSDevice.getAttachedDevices (package:flutter_tools/src/ios/devices.dart:184:55)
<asynchronous suspension>
#2      IOSDevices.pollingGetDevices (package:flutter_tools/src/ios/devices.dart:117:57)
#3      PollingDeviceDiscovery.devices (package:flutter_tools/src/device.dart:270:52)
<asynchronous suspension>
#4      DeviceManager.getAllConnectedDevices (package:flutter_tools/src/device.dart:136:46)
<asynchronous suspension>
#5      DeviceValidator.validate (package:flutter_tools/src/doctor.dart:760:54)
<asynchronous suspension>
#6      Doctor.startValidatorTasks (package:flutter_tools/src/doctor.dart:140:52)
#7      Doctor.diagnose (package:flutter_tools/src/doctor.dart:211:41)
#8      _AsyncAwaitCompleter.start (dart:async-patch/async_patch.dart:43:6)
#9      Doctor.diagnose (package:flutter_tools/src/doctor.dart:201:24)
#10     DoctorCommand.runCommand (package:flutter_tools/src/commands/doctor.dart:59:39)
#11     _AsyncAwaitCompleter.start (dart:async-patch/async_patch.dart:43:6)
#12     DoctorCommand.runCommand (package:flutter_tools/src/commands/doctor.dart:45:42)
#13     FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:490:18)
#14     _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:71:64)
#15     _rootRunUnary (dart:async/zone.dart:1132:38)
#16     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#17     _FutureListener.handleValue (dart:async/future_impl.dart:137:18)
#18     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:678:45)
#19     Future._propagateToListeners (dart:async/future_impl.dart:707:32)
#20     Future._completeWithValue (dart:async/future_impl.dart:522:5)
#21     Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:552:7)
#22     _rootRun (dart:async/zone.dart:1124:13)
#23     _CustomZone.run (dart:async/zone.dart:1021:19)
#24     _CustomZone.runGuarded (dart:async/zone.dart:923:7)
#25     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:963:23)
#26     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#27     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#28     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:116:13)
#29     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:173:5)
```

**Comment by christopherfujino** [comment]
@siliconsorcery I believe that error means that you have not trusted your host device from your phone. There should be a dialog on the phone that says something like, "trust this device?". There is an outstanding issue to have the doctor give a more friendly error....

**Comment by christopherfujino** [comment]
@rbucker I re-read your original issue and I see that you were able to get back to a stable state. I agree that we can improve error messaging from the tool when these kinds of errors occur.
