### ISSUE TITLE
Flutter tool crash when spawning debug extension

### ISSUE THREAD

**Issue by mdebbar** [flutter/flutter#41512]
I have hit this flutter tool crash multiple times so far. Here are the logs I got:

## command

`flutter run -d chrome --no-web-browser-launch --local-engine=host_debug_unopt --web-port=8080`

## exception

StateError: Bad state: Cannot add event after closing

```
#0      _StreamController.add (dart:async/stream_controller.dart:585:24)
#1      _StreamSinkWrapper.add (dart:async/stream_controller.dart:858:13)
#2      AppConnection.runMain (package:dwds/src/connections/app_connection.dart:25:22)
#3      WebFs.runAndDebug.<anonymous closure> (package:flutter_tools/src/build_runner/web_fs.dart:125:21)
<asynchronous suspension>
#4      _rootRunUnary (dart:async/zone.dart:1132:38)
#5      _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#6      _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
#7      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#8      _DelayedData.perform (dart:async/stream_impl.dart:591:14)
#9      _StreamImplEvents.handleNext (dart:async/stream_impl.dart:707:11)
#10     _PendingEvents.schedule.<anonymous closure> (dart:async/stream_impl.dart:667:7)
#11     _rootRun (dart:async/zone.dart:1120:38)
#12     _CustomZone.run (dart:async/zone.dart:1021:19)
#13     _CustomZone.runGuarded (dart:async/zone.dart:923:7)
#14     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:963:23)
#15     _rootRun (dart:async/zone.dart:1124:13)
#16     _CustomZone.run (dart:async/zone.dart:1021:19)
#17     _CustomZone.runGuarded (dart:async/zone.dart:923:7)
#18     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:963:23)
#19     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#20     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#21     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:116:13)
#22     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:173:5)
```

## flutter doctor

```
[✓] Flutter (Channel web_keymap, v1.10.6-pre.91, on Linux, locale en_US.UTF-8)
    • Flutter version 1.10.6-pre.91 at /usr/local/google/home/mdebbar/github/flutter
    • Framework revision 5a238f730f (3 days ago), 2019-09-24 14:55:48 -0700
    • Engine revision 1060cfc7da
    • Dart version 2.6.0 (build 2.6.0-dev.2.0 dd65f97118)

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /usr/local/google/home/mdebbar/Android/Sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /opt/android-studio-with-blaze-3.5/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Android Studio (version 3.5)
    • Android Studio at /opt/android-studio-with-blaze-3.5
    • Flutter plugin version 39.0.3
    • Dart plugin version 191.8423
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] IntelliJ IDEA Ultimate Edition (version 2019.1)
    • IntelliJ at /opt/intellij-ue-2019.1
    • Flutter plugin version 39.0.2
    • Dart plugin version 191.8423

[✓] IntelliJ IDEA Ultimate Edition (version 2018.3)
    • IntelliJ at /opt/intellij-ue-2018.3
    • Flutter plugin version 36.1.1
    • Dart plugin version 183.6270

[✓] VS Code (version 1.38.1)
    • VS Code at /usr/share/code
    • Flutter extension version 3.4.1

[✓] Connected device (2 available)
    • Chrome • chrome • web-javascript • Google Chrome 77.0.3865.90
    • Server • web    • web-javascript • Flutter Tools

• No issues found!
```

**Comment by mdebbar** [comment]
I don't use `-d chrome` anymore, and the `--no-web-browser-launch` is gone. Closing.
