### ISSUE TITLE
flutter run android,ProcessException: ProcessException: Permission denied.

### ISSUE THREAD

**Issue by huiqun922** [flutter/flutter#41526]
## command

flutter run

## exception

ProcessException: ProcessException: Permission denied
  Command: /Users/huanghuiqun750/Desktop/PingAn Works/EPV/EPMonitor-Flutter/android/gradlew -v

```
#0      runAsync (package:flutter_tools/src/base/process.dart:242:35)
<asynchronous suspension>
#1      runCheckedAsync (package:flutter_tools/src/base/process.dart:329:34)
<asynchronous suspension>
#2      _initializeGradle (package:flutter_tools/src/android/gradle.dart:297:9)
<asynchronous suspension>
#3      _ensureGradle (package:flutter_tools/src/android/gradle.dart:278:37)
<asynchronous suspension>
#4      _readGradleProject (package:flutter_tools/src/android/gradle.dart:192:31)
<asynchronous suspension>
#5      _gradleAppProject (package:flutter_tools/src/android/gradle.dart:112:37)
<asynchronous suspension>
#6      getGradleAppOut (package:flutter_tools/src/android/gradle.dart:106:29)
<asynchronous suspension>
#7      AndroidApk.fromAndroidProject (package:flutter_tools/src/application_package.dart:164:23)
<asynchronous suspension>
#8      ApplicationPackageFactory.getPackageForPlatform (package:flutter_tools/src/application_package.dart:46:32)
<asynchronous suspension>
#9      FlutterDevice.runHot (package:flutter_tools/src/resident_runner.dart:359:56)
<asynchronous suspension>
#10     HotRunner.run (package:flutter_tools/src/run_hot.dart:252:39)
<asynchronous suspension>
#11     RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:460:37)
<asynchronous suspension>
#12     FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:490:18)
#13     _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:71:64)
#14     _rootRunUnary (dart:async/zone.dart:1132:38)
#15     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#16     _FutureListener.handleValue (dart:async/future_impl.dart:137:18)
#17     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:678:45)
#18     Future._propagateToListeners (dart:async/future_impl.dart:707:32)
#19     Future._completeWithValue (dart:async/future_impl.dart:522:5)
#20     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:30:15)
#21     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:288:13)
#22     RunCommand.usageValues (package:flutter_tools/src/commands/run.dart)
#23     _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:71:64)
#24     _rootRunUnary (dart:async/zone.dart:1132:38)
#25     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#26     _FutureListener.handleValue (dart:async/future_impl.dart:137:18)
#27     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:678:45)
#28     Future._propagateToListeners (dart:async/future_impl.dart:707:32)
#29     Future._completeWithValue (dart:async/future_impl.dart:522:5)
#30     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:30:15)
#31     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:288:13)
#32     AndroidDevice.isLocalEmulator (package:flutter_tools/src/android/android_device.dart)
#33     _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:71:64)
#34     _rootRunUnary (dart:async/zone.dart:1132:38)
#35     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#36     _FutureListener.handleValue (dart:async/future_impl.dart:137:18)
#37     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:678:45)
#38     Future._propagateToListeners (dart:async/future_impl.dart:707:32)
#39     Future._completeWithValue (dart:async/future_impl.dart:522:5)
#40     Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:552:7)
#41     _rootRun (dart:async/zone.dart:1124:13)
#42     _CustomZone.run (dart:async/zone.dart:1021:19)
#43     _CustomZone.runGuarded (dart:async/zone.dart:923:7)
#44     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:963:23)
#45     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#46     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#47     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:116:13)
#48     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:173:5)
```

## flutter doctor

```
[32m[✓][39m Flutter (Channel master, v1.9.8-pre.79, on Mac OS X 10.14.4 18E226, locale zh-Hans-CN)
    [32m•[39m Flutter version 1.9.8-pre.79 at /Users/huanghuiqun750/development/flutter
    [32m•[39m Framework revision 72cacb4040 (3 weeks ago), 2019-09-03 18:00:45 -0700
    [32m•[39m Engine revision e7f9ef6aa0
    [32m•[39m Dart version 2.5.0 (build 2.5.0-dev.4.0 36985859e4)

[32m[✓][39m Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    [32m•[39m Android SDK at /Users/huanghuiqun750/Library/Android/sdk
    [32m•[39m Android NDK location not configured (optional; useful for native profiling support)
    [32m•[39m Platform android-28, build-tools 28.0.3
    [32m•[39m ANDROID_HOME = /Users/huanghuiqun750/Library/Android/sdk
    [32m•[39m Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    [32m•[39m Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
    [32m•[39m All Android licenses accepted.

[32m[✓][39m Xcode - develop for iOS and macOS (Xcode 10.2.1)
    [32m•[39m Xcode at /Applications/Xcode.app/Contents/Developer
    [32m•[39m Xcode 10.2.1, Build version 10E1001
    [32m•[39m CocoaPods version 1.7.0.beta.3

[32m[✓][39m Android Studio (version 3.4)
    [32m•[39m Android Studio at /Applications/Android Studio.app/Contents
    [32m•[39m Flutter plugin version 38.2.1
    [32m•[39m Dart plugin version 183.6270
    [32m•[39m Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

[32m[✓][39m VS Code (version 1.27.1)
    [32m•[39m VS Code at /Applications/Visual Studio Code.app/Contents
    [32m•[39m Flutter extension version 2.21.1

[32m[✓][39m Connected device (1 available)
    [32m•[39m Android SDK built for x86 • emulator-5554 • android-x86 • Android 7.0 (API 24) (emulator)

[32m•[39m No issues found!
```

**Comment by escamoteur** [comment]
Hi, you are using a pretty old flutter version on master.
Could you please upgrade?
Does this also happen with a newly created project?

**Comment by rbucker** [comment]
Mine is new and same problem.

It's getting really boring constantly running into problems that are clearly configuration or compatibility. The flutter team would do themselves a HUGE favor by testing this... keep in mind that flutter is meant to deploy on multiple platforms, ideally without changes, therefore the shim layer between ios and flutter and android and flutter should have an ideal configuration or starting point.


```
[✓] Flutter (Channel stable, v1.9.1+hotfix.4, on Mac OS X 10.14.6 18G95, locale en-US)
    • Flutter version 1.9.1+hotfix.4 at /Users/rbucker/dev/flutter
    • Framework revision cc949a8e8b (9 days ago), 2019-09-27 15:04:59 -0700
    • Engine revision b863200c37
    • Dart version 2.5.0

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/rbucker/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.0, Build version 11A420a
    • CocoaPods version 1.8.1

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 40.0.2
    • Dart plugin version 191.8423
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] VS Code (version 1.38.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.4.1

[✓] Connected device (1 available)
    • Pixel 3a • 98BAY13YKL • android-arm64 • Android 10 (API 29)

• No issues found!
```

**Comment by rbucker** [comment]
for good measure I did a ```flutter upgrade``` etc... and still no joy.

```
[✓] Flutter (Channel stable, v1.9.1+hotfix.4, on Mac OS X 10.14.6 18G95, locale en-US)
    • Flutter version 1.9.1+hotfix.4 at /Users/rbucker/dev/flutter
    • Framework revision cc949a8e8b (9 days ago), 2019-09-27 15:04:59 -0700
    • Engine revision b863200c37
    • Dart version 2.5.0

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/rbucker/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.0, Build version 11A420a
    • CocoaPods version 1.8.1

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 40.0.2
    • Dart plugin version 191.8423
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] VS Code (version 1.38.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.4.1

[✓] Connected device (1 available)
    • Pixel 3a • 98BAY13YKL • android-arm64 • Android 10 (API 29)

• No issues found!
```

**Comment by ngoan98tv** [comment]
Hi, I just resolved the same problem by running `chmod +x android/gradlew`
The relative issue can be find at https://stackoverflow.com/questions/17668265/gradlew-permission-denied/17669566

**Comment by huiqun922** [comment]
flutter upgrade . Flutter 1.7.8+hotfix.4 • channel stable

resolved the problem

**Comment by JonnyBorges** [comment]
> Olá, Acabei de resolver o mesmo problema executando `chmod +x android/gradlew`
> O problema relativo pode ser encontrado em https://stackoverflow.com/questions/17668265/gradlew-permission-denied/17669566

It fix to me
