### ISSUE TITLE
WEB: "flutter run -d chrome" crashes when using package with protobuf in dependencies

### ISSUE THREAD

**Issue by PavelPZ** [flutter/flutter#41544]
I am playing with flutter web (master channel version **1.10.7-pre.70**) in vs code.

When my application **app_io** is using package **app_main**, which has **protobuf** reference in app_main/pubspec.yaml:
```
dependencies:
  protobuf:
```
than ```flutter run -d chrome``` crashes.

It is curious, that:
- **protobuf** is not used in **app_main** package code, just referenced in app_main/pubspec.yaml
- when I reference (or even use **protobuf** code) in **app_io** application, all is OK.

You can evoke an error in https://github.com/PavelPZ/protobuf_problem 
- uncomment **protobuf:** line in https://github.com/PavelPZ/protobuf_problem/blob/master/app_main/pubspec.yaml 
- run ```flutter run -d chrome``` again.
- following error raise:
```
flutter run -d chrome
Launching lib\main.dart on Chrome in debug mode...
Unhandled exception:
NoSuchMethodError: The getter 'name' was called on null.
Receiver: null
Tried calling: name
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:51:5)
#1      _packageBuildConfig.<anonymous closure> (package:build_runner_core/src/package_graph/target_graph.dart:85:61)
#2      MappedListIterable.elementAt (dart:_internal/iterable.dart:415:29)
#3      ListIterable.toList (dart:_internal/iterable.dart:219:19)
#4      new BuildConfig.useDefault (package:build_config/src/build_config.dart:90:34)
#5      BuildConfig.fromBuildConfigDir (package:build_config/src/build_config.dart:52:26)
<asynchronous suspension>
#6      _packageBuildConfig (package:build_runner_core/src/package_graph/target_graph.dart:90:30)
<asynchronous suspension>
#7      TargetGraph.forPackageGraph (package:build_runner_core/src/package_graph/target_graph.dart:37:17)
<asynchronous suspension>
#8      BuildOptions.create (package:build_runner_core/src/generate/options.dart:107:39)
<asynchronous suspension>
#9      BuildRunnerDaemonBuilder.create (package:build_runner/src/daemon/daemon_builder.dart:182:43)
<asynchronous suspension>
#10     DaemonCommand.run (package:build_runner/src/entrypoint/daemon.dart:83:48)
<asynchronous suspension>
#11     CommandRunner.runCommand (package:args/command_runner.dart:197:27)
<asynchronous suspension>
#12     CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:112:25)
#13     new Future.sync (dart:async/future.dart:224:31)
#14     CommandRunner.run (package:args/command_runner.dart:112:14)
#15     run (package:build_runner/src/entrypoint/run.dart:24:31)
<asynchronous suspension>
#16     main (package:flutter_tools/src/build_runner/build_script.dart:200:28)
<asynchronous suspension>
#17     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:301:32)
#18     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:12)
Building application for the web...                                24.7s
Failed to build application for the web.
```

**Comment by escamoteur** [comment]
Thanks for reporting. It's an interesting observation. But you are not blocked, right?

**Comment by jonahwilliams** [comment]
I'm not able to reproduce your example on the latest master. Please include `flutter doctor -v`. Also ensure that you've run `flutter packages get` after adding the new dependency, or try running `flutter clean`

**Comment by PavelPZ** [comment]
Of course, I ran all things you suggest. 
Basically, my github example is result of 3 days of investigation of why is my large project build crash.

Now, if I add **protobuf** reference to app_io/pubspec.yaml too, it helps. When I remove it (and delete protobuf record from pubspec.lock and from .packages files) error raises again.

I suspect that the error is related to protobuf version. In one of my attempts I solved version collision between protobuf-0.14.4 x protobuf-0.14.3 x protobuf-0.13.?.  

Attached is flutter doctor result :
```
PS C:\protobuf_problem\app_io> flutter doctor -v
[√] Flutter (Channel master, v1.10.7-pre.70, on Microsoft Windows [Version 10.0.17134.1006], locale en-US)
    • Flutter version 1.10.7-pre.70 at c:\flutter
    • Framework revision 25f2399ba3 (25 hours ago), 2019-09-28 00:22:37 -0700
    • Engine revision 5b952f286f
    • Dart version 2.6.0 (build 2.6.0-dev.3.0 6ff8d2199d)

[!] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at C:\Users\pzika\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    X No Java Development Kit (JDK) found; You must have the environment variable JAVA_HOME set and the java binary in your      PATH. You can download the JDK from https://www.oracle.com/technetwork/java/javase/downloads/.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.4.0 Preview 1.0)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Preview
    • Visual Studio Community 2019 version 16.4.29319.158
    • The current Visual Studio installation is a pre-release version. It may not be supported by Flutter yet.

[!] Android Studio (version 3.5)
    • Android Studio at C:\Program Files\Android\Android Studio
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
    X Unable to determine bundled Java version.
    • Try updating or re-installing Android Studio.

[√] VS Code (version 1.38.1)
    • VS Code at C:\Users\pzika\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.4.1

[√] Connected device (3 available)
    • Windows • Windows • windows-x64    • Microsoft Windows [Version 10.0.17134.1006]
    • Chrome  • chrome  • web-javascript • Google Chrome 77.0.3865.90
    • Server  • web     • web-javascript • Flutter Tools

! Doctor found issues in 2 categories.
```

**Comment by escamoteur** [comment]
If it really depends on the version, best to raise an issue at the protobuf repository too and reference this issue.

**Comment by yjbanov** [comment]
This was reported again here: https://github.com/flutter/flutter/issues/42218. We need to look into it. Adding to near-term goals.

**Comment by PavelPZ** [comment]
Problem raised again in another context. In this case I cannot find workaround.

I suspect that problem is related with importing packages, which has more that single version in c:\Users\<username>\AppData\Roaming\Pub\Cache\hosted\pub.dartlang.org\

I have to stop development web version of my app.

**Comment by yjbanov** [comment]
Neither @PavelPZ's nor @decker deckerst sample apps reproduce the issue for me on a Linux computer and on a Mac computer as of dd43da71febaafc58852000a61a6bc1ac4fb57ef. I did see the CLI get stuck on "Attempting to connect to browser instance" but that seems unrelated.

What else am I missing?

**Comment by PavelPZ** [comment]
I have tried to add ```-v``` to ```flutter test --platform chrome``` and found this notice:
```
Unable to read module information for package:convert, make sure you have a dependency on it in your pubspec
``` 

It is curious that:
- test for ```package_a``` (with missing package:convert) runs well and does not show any error
- test build for ```package_b``` (which uses ```package_a```) crashes (and does not show any error)
- adding ```-v``` shows info about missing dependency

I apologize for reporting it in this issue. 

Console:

```
Windows PowerShell
Copyright (C) Microsoft Corporation. All rights reserved.

Try the new cross-platform PowerShell https://aka.ms/pscore6

PS C:\wikibulary\dart\utils\utils_auth> flutter test --platform chrome -v
[  +52 ms] executing: [c:\flutter\] git -c log.showSignature=false log -n 1 --pretty=format:%H
[ +158 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[   +4 ms] 9423a01204ba9abf2e4b26fda3d5ef06d6897ef9
[   +1 ms] executing: [c:\flutter\] git describe --match v*.*.* --first-parent --long --tags
[ +185 ms] Exit code 0 from: git describe --match v*.*.* --first-parent --long --tags
[   +1 ms] v1.10.14-95-g9423a0120
[  +24 ms] executing: [c:\flutter\] git rev-parse --abbrev-ref --symbolic @{u}
[ +103 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[   +1 ms] origin/master
[        ] executing: [c:\flutter\] git ls-remote --get-url origin
[  +96 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[ +206 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.  
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[  +25 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.   
[   +1 ms] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.     
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.     
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update. 
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update. 
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[+16175 ms] Starting daemon...
[ +384 ms] Initializing inputs
[ +619 ms] Building new asset graph...
[+2767 ms] Building new asset graph completed, took 2.8s

[   +1 ms] Checking for unexpected pre-existing outputs....
[   +1 ms] Checking for unexpected pre-existing outputs. completed, took 2ms

[  +20 ms] Initializing inputs
[   +8 ms] Building new asset graph...
[   +1 ms] Building new asset graph completed, took 2.8s
[   +1 ms] Checking for unexpected pre-existing outputs....
[   +1 ms] Checking for unexpected pre-existing outputs. completed, took 2ms
[+1869 ms] About to build [web, test]...
[  +24 ms] Running build...
[ +311 ms] building for target test/auth_test.dart.browser_test.dart
[+1037 ms] 1.4s elapsed, 87/105 actions completed.
[+1095 ms] 2.5s elapsed, 219/223 actions completed.
[+1004 ms] 3.5s elapsed, 390/405 actions completed.
[+1001 ms] 4.5s elapsed, 557/565 actions completed.
[+1098 ms] 5.6s elapsed, 713/733 actions completed.
[+1099 ms] 6.7s elapsed, 861/877 actions completed.
[+1095 ms] 7.8s elapsed, 1010/1014 actions completed.
[+1017 ms] 8.8s elapsed, 1148/1165 actions completed.
[+1083 ms] 9.9s elapsed, 1282/1287 actions completed.
[+1098 ms] 11.0s elapsed, 1441/1445 actions completed.
[+1001 ms] 12.0s elapsed, 1529/1531 actions completed.
[  +63 ms] Unable to read module information for package:convert, make sure you have a dependency on it in your pubspec.
[  +72 ms] Unable to read module information for package:convert, make sure you have a dependency on it in your pubspec.
[ +454 ms] Unable to read module information for package:convert, make sure you have a dependency on it in your pubspec.
[ +396 ms] Unable to find modules for some sources, this is usually the result of either a
                    bad import, a missing dependency in a package (or possibly a dev_dependency
                    needs to move to a real dependency), or a build failure (if importing a
                    generated file).

                    Please check the following imports:


[ +296 ms] AssetNotFoundException: utils|lib/guid_small.ddc.dill
[  +44 ms] #0      ScratchSpace.ensureAssets.<anonymous closure> (package:scratch_space/src/scratch_space.dart:94:20)
           <asynchronous suspension>
           #1      MappedIterator.moveNext (dart:_internal/iterable.dart:393:18)
           #2      new List.from (dart:core-patch/array_patch.dart:33:29)
           #3      Iterable.toList (dart:core/iterable.dart:398:5)
           #4      ScratchSpace.ensureAssets (package:scratch_space/src/scratch_space.dart:116:8)
           #5      _createDevCompilerModule.<anonymous closure> (package:build_web_compilers/src/dev_compiler_builder.dart:121:42)        
           #6      _NoOpBuilderActionTracker.trackStage (package:build_runner_core/src/generate/performance_tracker.dart:300:15)
           #7      BuildStepImpl.trackStage (package:build/src/builder/build_step_impl.dart:146:21)
           #8      _createDevCompilerModule (package:build_web_compilers/src/dev_compiler_builder.dart:120:19)
           #9      _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:71:64)
           #10     _rootRunUnary (dart:async/zone.dart:1132:38)
           #11     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
           #12     _FutureListener.handleValue (dart:async/future_impl.dart:137:18)
           #13     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:678:45)
           #14     Future._propagateToListeners (dart:async/future_impl.dart:707:32)
           #15     Future._completeWithValue (dart:async/future_impl.dart:522:5)
           #16     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:30:15)
           #17     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:288:13)
           #18     Resource._fetch.<anonymous closure> (package:build/src/resource/resource.dart)
           #19     _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:71:64)
           #20     _rootRunUnary (dart:async/zone.dart:1132:38)
           #21     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
           #22     _FutureListener.handleValue (dart:async/future_impl.dart:137:18)
           #23     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:678:45)
           #24     Future._propagateToListeners (dart:async/future_impl.dart:707:32)
           #25     Future._addListener.<anonymous closure> (dart:async/future_impl.dart:387:9)
           #26     _rootRun (dart:async/zone.dart:1124:13)
           #27     _CustomZone.run (dart:async/zone.dart:1021:19)
           #28     _CustomZone.runGuarded (dart:async/zone.dart:923:7)
           #29     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:963:23)
           #30     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
           #31     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
           #32     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:116:13)
           #33     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:173:5)

[+1745 ms] 14.2s elapsed, 1580/1652 actions completed.
[ +630 ms] 15.3s elapsed, 1580/1652 actions completed.
[ +972 ms] 16.5s elapsed, 1580/1652 actions completed.
[ +873 ms] 17.5s elapsed, 1585/1657 actions completed.
[ +322 ms] BuildStepCompletedException: Attempt to use a BuildStep after is has completed
[   +2 ms] #0      BuildStepImpl.readAsBytes (package:build/src/builder/build_step_impl.dart:93:22)
           #1      ScratchSpace.ensureAssets.<anonymous closure>.<anonymous closure>.<anonymous closure>
           (package:scratch_space/src/scratch_space.dart:111:56)
           <asynchronous suspension>
           #2      Pool.withResource (package:pool/pool.dart:127:28)
           <asynchronous suspension>
           #3      ScratchSpace.ensureAssets.<anonymous closure>.<anonymous closure> (package:scratch_space/src/scratch_space.dart:105:35)           #4      _LinkedHashMapMixin.putIfAbsent (dart:collection-patch/compact_hash.dart:291:23)
           #5      ScratchSpace.ensureAssets.<anonymous closure> (package:scratch_space/src/scratch_space.dart:103:30)
           <asynchronous suspension>
           #6      MappedIterator.moveNext (dart:_internal/iterable.dart:393:18)
           #7      new List.from (dart:core-patch/array_patch.dart:33:29)
           #8      Iterable.toList (dart:core/iterable.dart:398:5)
           #9      ScratchSpace.ensureAssets (package:scratch_space/src/scratch_space.dart:116:8)
           #10     _createDevCompilerModule.<anonymous closure> (package:build_web_compilers/src/dev_compiler_builder.dart:121:42)        
           #11     _NoOpBuilderActionTracker.trackStage (package:build_runner_core/src/generate/performance_tracker.dart:300:15)
           #12     BuildStepImpl.trackStage (package:build/src/builder/build_step_impl.dart:146:21)
           #13     _createDevCompilerModule (package:build_web_compilers/src/dev_compiler_builder.dart:120:19)
           #14     _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:71:64)
           #15     _rootRunUnary (dart:async/zone.dart:1132:38)
           #16     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
           #17     _FutureListener.handleValue (dart:async/future_impl.dart:137:18)
           #18     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:678:45)
           #19     Future._propagateToListeners (dart:async/future_impl.dart:707:32)
           #20     Future._completeWithValue (dart:async/future_impl.dart:522:5)
           #21     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:30:15)
           #22     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:288:13)
           #23     Resource._fetch.<anonymous closure> (package:build/src/resource/resource.dart)
           #24     _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:71:64)
           #25     _rootRunUnary (dart:async/zone.dart:1132:38)
           #26     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
           #27     _FutureListener.handleValue (dart:async/future_impl.dart:137:18)
           #28     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:678:45)
           #29     Future._propagateToListeners (dart:async/future_impl.dart:707:32)
           #30     Future._addListener.<anonymous closure> (dart:async/future_impl.dart:387:9)
           #31     _rootRun (dart:async/zone.dart:1124:13)
           #32     _CustomZone.run (dart:async/zone.dart:1021:19)
           #33     _CustomZone.runGuarded (dart:async/zone.dart:923:7)
           #34     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:963:23)
           #35     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
           #36     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
           #37     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:116:13)
           #38     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:173:5)

[+1651 ms] BuildStepCompletedException: Attempt to use a BuildStep after is has completed
[ +378 ms] #0      BuildStepImpl.readAsBytes (package:build/src/builder/build_step_impl.dart:93:22)
                    #1      ScratchSpace.ensureAssets.<anonymous closure>.<anonymous closure>.<anonymous closure>
                    (package:scratch_space/src/scratch_space.dart:111:56)
                    <asynchronous suspension>
                    #2      Pool.withResource (package:pool/pool.dart:127:28)
                    <asynchronous suspension>
                    #3      ScratchSpace.ensureAssets.<anonymous closure>.<anonymous closure>
                    (package:scratch_space/src/scratch_space.dart:105:35)
                    #4      _LinkedHashMapMixin.putIfAbsent (dart:collection-patch/compact_hash.dart:291:23)
                    #5      ScratchSpace.ensureAssets.<anonymous closure> (package:scratch_space/src/scratch_space.dart:103:30)
                    <asynchronous suspension>
                    #6      MappedIterator.moveNext (dart:_internal/iterable.dart:393:18)
                    #7      new List.from (dart:core-patch/array_patch.dart:33:29)
                    #8      Iterable.toList (dart:core/iterable.dart:398:5)
                    #9      ScratchSpace.ensureAssets (package:scratch_space/src/scratch_space.dart:116:8)
                    #10     _createDevCompilerModule.<anonymous closure>
                    (package:build_web_compilers/src/dev_compiler_builder.dart:121:42)
                    #11     _NoOpBuilderActionTracker.trackStage (package:build_runner_core/src/generate/performance_tracker.dart:300:15) 
                    #12     BuildStepImpl.trackStage (package:build/src/builder/build_step_impl.dart:146:21)
                    #13     _createDevCompilerModule (package:build_web_compilers/src/dev_compiler_builder.dart:120:19)
                    #14     _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:71:64)
                    #15     _rootRunUnary (dart:async/zone.dart:1132:38)
                    #16     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
                    #17     _FutureListener.handleValue (dart:async/future_impl.dart:137:18)
                    #18     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:678:45)
                    #19     Future._propagateToListeners (dart:async/future_impl.dart:707:32)
                    #20     Future._completeWithValue (dart:async/future_impl.dart:522:5)
                    #21     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:30:15)
                    #22     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:288:13)
                    #23     Resource._fetch.<anonymous closure> (package:build/src/resource/resource.dart)
                    #24     _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:71:64)
                    #25     _rootRunUnary (dart:async/zone.dart:1132:38)
                    #26     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
                    #27     _FutureListener.handleValue (dart:async/future_impl.dart:137:18)
                    #28     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:678:45)
                    #29     Future._propagateToListeners (dart:async/future_impl.dart:707:32)
                    #30     Future._addListener.<anonymous closure> (dart:async/future_impl.dart:387:9)
                    #31     _rootRun (dart:async/zone.dart:1124:13)
                    #32     _CustomZone.run (dart:async/zone.dart:1021:19)
                    #33     _CustomZone.runGuarded (dart:async/zone.dart:923:7)
                    #34     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:963:23)
                    #35     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
                    #36     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
                    #37     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:116:13)
                    #38     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:173:5)

^CTerminate batch job (Y/N)? 
```

**Comment by cbracken** [comment]
Wondering if this may be Windows-specific. @yjbanov if you need help reproing on Windows, swing by one of the usual suspects :-)

**Comment by PavelPZ** [comment]
For sure I'm adding this link: https://github.com/flutter/flutter/issues/44583

**Comment by deisold** [comment]
I'm having the same problem with flutter web when importing own packages.
Is there anyone looking into it?

**Comment by agordeev** [comment]
I'm getting the same issue when using my package. I'm building on Mac. The error message is:

```
$ flutter run -d chrome
Launching lib/main.dart on Chrome in debug mode...
Unhandled exception:                                                    
NoSuchMethodError: The getter 'name' was called on null.                
Receiver: null                                                          
Tried calling: name                                                     
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:53:5)    
#1      _packageBuildConfig.<anonymous closure> (package:build_runner_core/src/package_graph/target_graph.dart:85:61)
#2      MappedListIterable.elementAt (dart:_internal/iterable.dart:417:29)
#3      ListIterable.toList (dart:_internal/iterable.dart:221:19)       
#4      new BuildConfig.fromMap (package:build_config/src/build_config.dart:120:35)
#5      new BuildConfig.parse.<anonymous closure> (package:build_config/src/build_config.dart:107:25)
#6      checkedYamlDecode (package:checked_yaml/checked_yaml.dart:47:23)
#7      new BuildConfig.parse (package:build_config/src/build_config.dart:104:14)
#8      BuildConfig.fromBuildConfigDir (package:build_config/src/build_config.dart:45:26)
<asynchronous suspension>                                               
#9      _packageBuildConfig (package:build_runner_core/src/package_graph/target_graph.dart:90:30)
#10     TargetGraph.forPackageGraph (package:build_runner_core/src/package_graph/target_graph.dart:37:17)
<asynchronous suspension>                                               
#11     BuildOptions.create (package:build_runner_core/src/generate/options.dart:167:39)
#12     BuildRunnerDaemonBuilder.create (package:build_runner/src/daemon/daemon_builder.dart:194:43)
<asynchronous suspension>                                               
#13     DaemonCommand.run (package:build_runner/src/entrypoint/daemon.dart:83:48)
#14     CommandRunner.runCommand (package:args/command_runner.dart:197:27)
#15     CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:112:25)
#16     new Future.sync (dart:async/future.dart:224:31)                 
#17     CommandRunner.run (package:args/command_runner.dart:112:14)     
#18     run (package:build_runner/src/entrypoint/run.dart:24:31)        
#19     main (package:flutter_tools/src/build_runner/build_script.dart:181:28)
#20     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:297:32)
#21     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:168:12)
Building application for the web...                                 6.7s
Failed to start build daemon. The process might have exited unexpectedly during startup. Try running the application again.
```

Few observations:
1. `flutter build web` works fine.
2. The error occurs only when I specify `json_annotation` package in my subpackage.
