### ISSUE TITLE
Android crash  when use sougou input menthod 

### ISSUE THREAD

**Issue by liaobushi520** [flutter/flutter#41557]
## Steps to Reproduce
 Device : 360 1607-A01 Android 7.1.1 API 25
1: use sougou input method ,
2.write a simple demo 
3.debug app 
crash
 
## Logs

2019-09-29 15:58:57.177 543-543/com.qiaofang.flutter.qf_flutter.host E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.qiaofang.flutter.qf_flutter.host, PID: 543
    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.qiaofang.flutter.qf_flutter.host/com.qiaofang.flutter.qf_flutter.host.MainActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String android.view.inputmethod.InputMethodSubtype.getLanguageTag()' on a null object reference
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2722)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2783)
        at android.app.ActivityThread.-wrap12(ActivityThread.java)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1516)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:154)
        at android.app.ActivityThread.main(ActivityThread.java:6259)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:913)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:803)
     Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String android.view.inputmethod.InputMethodSubtype.getLanguageTag()' on a null object reference
        at io.flutter.plugin.editing.TextInputPlugin.isRestartAlwaysRequired(TextInputPlugin.java:325)
        at io.flutter.plugin.editing.TextInputPlugin.<init>(TextInputPlugin.java:93)
        at io.flutter.view.FlutterView.<init>(FlutterView.java:216)
        at io.flutter.app.FlutterActivityDelegate.onCreate(FlutterActivityDelegate.java:150)
        at io.flutter.app.FlutterActivity.onCreate(FlutterActivity.java:89)
        at com.qiaofang.flutter.qf_flutter.host.MainActivity.onCreate(MainActivity.java:10)
        at android.app.Activity.performCreate(Activity.java:6731)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1119)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2675)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2783) 
        at android.app.ActivityThread.-wrap12(ActivityThread.java) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1516) 
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:154) 
        at android.app.ActivityThread.main(ActivityThread.java:6259) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:913) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:803)

**Comment by escamoteur** [comment]
Could you please add the output of flutter doctor - v here?
When exactly does it crash?

**Comment by liaobushi520** [comment]
> Could you please add the output of flutter doctor - v here?
> When exactly does it crash?
[✓] Flutter (Channel master, v1.10.7-pre.53, on Mac OS X 10.14.6 18G95, locale zh-Hans-CN)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[✗] Xcode - develop for iOS and macOS
    ✗ Xcode installation is incomplete; a full installation is necessary for iOS development.
      Download at: https://developer.apple.com/xcode/download/
      Or install Xcode via the App Store.
      Once installed, run:
        sudo xcode-select --switch /Applications/Xcode.app/Contents/Developer
    ✗ CocoaPods not installed.
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To install:
        sudo gem install cocoapods
        pod setup
[✓] Chrome - develop for the web
[✓] Android Studio (version 3.5)
[✓] Connected device (2 available)

**Comment by liaobushi520** [comment]
> > Could you please add the output of flutter doctor - v here?
> > When exactly does it crash?
> > [✓] Flutter (Channel master, v1.10.7-pre.53, on Mac OS X 10.14.6 18G95, locale zh-Hans-CN)
> 
> [✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
> [✗] Xcode - develop for iOS and macOS
> ✗ Xcode installation is incomplete; a full installation is necessary for iOS development.
> Download at: https://developer.apple.com/xcode/download/
> Or install Xcode via the App Store.
> Once installed, run:
> sudo xcode-select --switch /Applications/Xcode.app/Contents/Developer
> ✗ CocoaPods not installed.
> CocoaPods is used to retrieve the iOS and macOS platform side's plugin code that responds to your plugin usage on the Dart side.
> Without CocoaPods, plugins will not work on iOS or macOS.
> For more info, see https://flutter.dev/platform-plugins
> To install:
> sudo gem install cocoapods
> pod setup
> [✓] Chrome - develop for the web
> [✓] Android Studio (version 3.5)
> [✓] Connected device (2 available)



> Could you please add the output of flutter doctor - v here?
> When exactly does it crash?

```
 @SuppressLint({"NewApi"})
    private boolean isRestartAlwaysRequired() {
        String language = VERSION.SDK_INT >= 24 ? this.mImm.getCurrentInputMethodSubtype().getLanguageTag() : this.mImm.getCurrentInputMethodSubtype().getLocale();
        return Build.MANUFACTURER.equals("samsung") && language.equals("ko");
    }
```
on some device ,if I use sougou input method, this.mImm.getCurrentInputMethodSubtype() will be null

**Comment by damengzai** [comment]
same issue,when I start my app,crashed. No sougou input method. System version android 9.
[✓] Flutter (Channel master, v1.10.7-pre.48, on Mac OS X 10.14.5 18F132, locale zh-Hans-CN)
    • Flutter version 1.10.7-pre.48 at /Users/shumengma/flutter
    • Framework revision b07056b107 (3 days ago), 2019-09-26 22:01:41 -0400
    • Engine revision ce6ab8ce25
    • Dart version 2.6.0 (build 2.6.0-dev.0.0 327bc451f8)


[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/shumengma/Library/Android/sdk
    • Android NDK at /Users/shumengma/Library/Android/sdk/ndk-bundle
    • Platform android-29, build-tools 28.0.3
    • ANDROID_HOME = /Users/shumengma/Library/Android/sdk
    • Java binary at: /Applications/Android Studio 2.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[!] Xcode - develop for iOS and macOS (Xcode 10.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.0, Build version 10A255
    ! CocoaPods 1.5.3 out of date (1.6.0 is recommended).
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin code that responds to
        your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To upgrade:
        sudo gem install cocoapods
        pod setup

[!] Android Studio (version 2.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[!] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio 2.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] IntelliJ IDEA Community Edition (version 2019.2.2)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 39.0.5
    • Dart plugin version 192.6603.23

[!] VS Code (version 1.38.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    ✗ Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (2 available)
    • PCT AL10 • 5ENDU19326005234 • android-arm64 • Android 9 (API 28)
    • 1807 A01 • 9b224a6          • android-arm64 • Android 8.1.0 (API 27)

**Comment by wakakajp** [comment]
on HUAWEI PAR AL00, Android 9,level 28,  if I use iFLY input method, 
this.mImm.getCurrentInputMethodSubtype() will be null
hope there will be a solution soon.

**Comment by yhrun** [comment]
same issue
