### ISSUE TITLE
[image_picker] crash when use aar  as dependence from 'flutter build aar' 

### ISSUE THREAD

**Issue by liujingtech** [flutter/flutter#41558]
add image_picker as module to android project is work.But aar has many advantages.
## Steps to Reproduce
1. create new flutter module.
2. create new android application.
3. add 'image_picker: 0.6.1+4' to pubspec.yaml
4. run flutter build aar.
5. use [Add-Flutter-to-existing-apps](https://github.com/flutter/flutter/wiki/Add-Flutter-to-existing-apps) to add aar to android project.
6. add `debugImplementation ('io.flutter.plugins.imagepicker:imagepicker_debug:1.0@aar')` 
7. gradle sync and run.
8. app open and crash
## Logs
> 2019-09-29 15:49:46.296 5122-5122/? E/g.myapplicatio: Unknown bits set in runtime_flags: 0x8000
2019-09-29 15:49:46.632 5122-5122/org.liujing.myapplication E/AndroidRuntime: FATAL EXCEPTION: main
    Process: org.liujing.myapplication, PID: 5122
    java.lang.RuntimeException: Unable to start activity ComponentInfo{org.liujing.myapplication/org.liujing.myapplication.MainActivity}: java.lang.RuntimeException: Failed to call observer method
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3270)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3409)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2016)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7356)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
     Caused by: java.lang.RuntimeException: Failed to call observer method
        at androidx.lifecycle.ClassesInfoCache$MethodReference.invokeCallback(ClassesInfoCache.java:226)
        at androidx.lifecycle.ClassesInfoCache$CallbackInfo.invokeMethodsForEvent(ClassesInfoCache.java:194)
        at androidx.lifecycle.ClassesInfoCache$CallbackInfo.invokeCallbacks(ClassesInfoCache.java:185)
        at androidx.lifecycle.ReflectiveGenericLifecycleObserver.onStateChanged(ReflectiveGenericLifecycleObserver.java:36)
        at androidx.lifecycle.LifecycleRegistry$ObserverWithState.dispatchEvent(LifecycleRegistry.java:361)
        at androidx.lifecycle.LifecycleRegistry.forwardPass(LifecycleRegistry.java:300)
        at androidx.lifecycle.LifecycleRegistry.sync(LifecycleRegistry.java:339)
        at androidx.lifecycle.LifecycleRegistry.moveToState(LifecycleRegistry.java:145)
        at androidx.lifecycle.LifecycleRegistry.handleLifecycleEvent(LifecycleRegistry.java:131)
        at androidx.lifecycle.ReportFragment.dispatch(ReportFragment.java:123)
        at androidx.lifecycle.ReportFragment.onActivityCreated(ReportFragment.java:76)
        at android.app.Fragment.performActivityCreated(Fragment.java:2543)
        at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1323)
        at android.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1581)
        at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1642)
        at android.app.FragmentManagerImpl.dispatchMoveToState(FragmentManager.java:3052)
        at android.app.FragmentManagerImpl.dispatchActivityCreated(FragmentManager.java:3004)
        at android.app.FragmentController.dispatchActivityCreated(FragmentController.java:184)
        at android.app.Activity.performCreate(Activity.java:7809)
        at android.app.Activity.performCreate(Activity.java:7791)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1306)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3245)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3409) 
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83) 
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2016) 
        at android.os.Handler.dispatchMessage(Handler.java:107) 
        at android.os.Looper.loop(Looper.java:214) 
        at android.app.ActivityThread.main(ActivityThread.java:7356) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930) 
     Caused by: java.lang.ClassCastException: org.liujing.myapplication.MainActivity cannot be cast to android.app.Application
        at io.flutter.plugins.imagepicker.ImagePickerPlugin.<init>(ImagePickerPlugin.java:94)
        at io.flutter.plugins.imagepicker.ImagePickerPlugin.registerWith(ImagePickerPlugin.java:53)
        at io.flutter.plugins.GeneratedPluginRegistrant.registerWith(GeneratedPluginRegistrant.java:14)
        at io.flutter.facade.Flutter$2.onCreate(Flutter.java:98)
        at java.lang.reflect.Method.invoke(Native Method)
        at androidx.lifecycle.ClassesInfoCache$MethodReference.invokeCallback(ClassesInfoCache.java:216)
        at androidx.lifecycle.ClassesInfoCache$CallbackInfo.invokeMethodsForEvent(ClassesInfoCache.java:194) 
        at androidx.lifecycle.ClassesInfoCache$CallbackInfo.invokeCallbacks(ClassesInfoCache.java:185) 
        at androidx.lifecycle.ReflectiveGenericLifecycleObserver.onStateChanged(ReflectiveGenericLifecycleObserver.java:36) 
        at androidx.lifecycle.LifecycleRegistry$ObserverWithState.dispatchEvent(LifecycleRegistry.java:361) 
        at androidx.lifecycle.LifecycleRegistry.forwardPass(LifecycleRegistry.java:300) 
        at androidx.lifecycle.LifecycleRegistry.sync(LifecycleRegistry.java:339) 
        at androidx.lifecycle.LifecycleRegistry.moveToState(LifecycleRegistry.java:145) 
        at androidx.lifecycle.LifecycleRegistry.handleLifecycleEvent(LifecycleRegistry.java:131) 
        at androidx.lifecycle.ReportFragment.dispatch(ReportFragment.java:123) 
        at androidx.lifecycle.ReportFragment.onActivityCreated(ReportFragment.java:76) 
        at android.app.Fragment.performActivityCreated(Fragment.java:2543) 
        at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1323) 
        at android.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1581) 
        at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1642) 
        at android.app.FragmentManagerImpl.dispatchMoveToState(FragmentManager.java:3052) 
        at android.app.FragmentManagerImpl.dispatchActivityCreated(FragmentManager.java:3004) 
        at android.app.FragmentController.dispatchActivityCreated(FragmentController.java:184) 
        at android.app.Activity.performCreate(Activity.java:7809) 
        at android.app.Activity.performCreate(Activity.java:7791) 
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1306) 
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3245) 
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3409) 
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83) 
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2016) 
        at android.os.Handler.dispatchMessage(Handler.java:107) 
        at android.os.Looper.loop(Looper.java:214) 
        at android.app.ActivityThread.main(ActivityThread.java:7356) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930) 

## .

>  Caused by: java.lang.ClassCastException: org.liujing.myapplication.MainActivity cannot be cast to android.app.Application

`io.flutter.plugins.imagepicker.ImagePickerPlugin`:
```java
ImagePickerPlugin(final Registrar registrar, final ImagePickerDelegate delegate) {
        // ...
        if (this.registrar != null) {
            ((Application)this.registrar.context()).registerActivityLifecycleCallbacks(this.activityLifecycleCallbacks);
        }

    }
```
`((Application)this.registrar.context())` may need to be changed to `this.registrar.context().getApplicationContext()`

**Comment by amirh** [comment]
cc @blasten

**Comment by blasten** [comment]
Did you build debug or release? It looks like you need to add the release variant as well.

**Comment by liujingtech** [comment]
Both debug and release depend have been added and both buildtype failed to run .

committing a pullrequets and it seems to have been fixed.flutter/plugins#2120

**Comment by liujingtech** [comment]
Both debug and release depend have been added and both buildtype failed to run .

committing a pullrequets and it seems to have been fixed.flutter/plugins#2120

**Comment by cyanglaz** [comment]
Seems fixed in https://github.com/flutter/plugins/pull/2120. Closing the issue.
