### ISSUE TITLE
PlatformException (PlatformException(photo _access_denied, The user did not allow photo access., null))

### ISSUE THREAD

**Issue by dinethnarada** [flutter/flutter#41566]
## Steps to Reproduce

1. I faced with an problem while running my flutter application. I used a 'Image_picker' and put it into my dependencies. Then above exception is shown to me. I created a new flutter project and run a example of image_picker. It worked!!. In my application it doesn't work. It shows above exception.
```
These are my dependancies
  cupertino_icons: ^0.1.2
  cloud_firestore:
  firebase_auth:
  firebase_core:
  carousel_pro: 
  fluttertoast:
  uuid:
  flutter_typeahead:
  flutter_search_panel:
  image_picker: 0.6.1+4 
```
```
File _image1;
File _image2;
File _image3;
Expanded(
                    child: Padding(
                      padding: const EdgeInsets.all(8.0),
                      child: OutlineButton(
                          borderSide: BorderSide(
                              color: grey.withOpacity(0.5), width: 2.5),
                          onPressed: () {
                            _selectImage(
                                ImagePicker.pickImage(
                                    source: ImageSource.gallery),
                                2);
                          },
                          child: _displayChild2()),
                    ),
                  ),
void _selectImage(Future<File> pickImage, int imageNumber) async {
    File tempImg = await pickImage;
    switch (imageNumber) {
      case 1:
        setState(() => _image1 = tempImg);
        break;
      case 2:
        setState(() => _image2 = tempImg);
        break;
      case 3:
        setState(() => _image3 = tempImg);
        break;
    }
  }

  Widget _displayChild1() {
    if (_image1 == null) {
      return Padding(
        padding: const EdgeInsets.fromLTRB(14, 70, 14, 70),
        child: new Icon(
          Icons.add,
          color: grey,
        ),
      );
    } else {
      return Image.file(
        _image1,
        fit: BoxFit.fill,
        width: double.infinity,
      );
    }
  }
```
## Logs

```
[  +12 ms] executing: [C:\flutter\flutter\] git log -n 1 --pretty=format:%H
[  +63 ms] Exit code 0 from: git log -n 1 --pretty=format:%H
[        ] 2d2a1ffec95cc70a3218872a2cd3f8de4933c42f
[   +2 ms] executing: [C:\flutter\flutter\] git describe --match v*.*.* --first-parent --long --tags
[  +54 ms] Exit code 0 from: git describe --match v*.*.* --first-parent --long --tags
[   +1 ms] v1.9.1+hotfix.2-0-g2d2a1ff
[   +8 ms] executing: [C:\flutter\flutter\] git rev-parse --abbrev-ref --symbolic @{u}
[  +77 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/stable
[        ] executing: [C:\flutter\flutter\] git ls-remote --get-url origin
[  +44 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[ +223 ms] executing: [C:\flutter\flutter\] git rev-parse --abbrev-ref HEAD
[  +58 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] stable
[  +37 ms] "flutter run" took 89ms.
Error: No pubspec.yaml file found.
This command should be run from the root of your Flutter project.
Do not run this command from the root of your git clone of Flutter.

#0      FlutterCommand.validateCommand (package:flutter_tools/src/runner/flutter_command.dart:568:9)
<asynchronous suspension>
#1      RunCommand.validateCommand (package:flutter_tools/src/commands/run.dart:278:19)
<asynchronous suspension>
#2      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:465:11)
<asynchronous suspension>
#3      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:407:33)
<asynchronous suspension>
#4      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:154:29)
<asynchronous suspension>
#5      _rootRun (dart:async/zone.dart:1124:13)
#6      _CustomZone.run (dart:async/zone.dart:1021:19)
#7      _runZoned (dart:async/zone.dart:1516:10)
#8      runZoned (dart:async/zone.dart:1463:12)
#9      AppContext.run (package:flutter_tools/src/base/context.dart:153:18)
<asynchronous suspension>
#10     FlutterCommand.run (package:flutter_tools/src/runner/flutter_command.dart:397:20)
#11     CommandRunner.runCommand (package:args/command_runner.dart:197:27)
<asynchronous suspension>
#12     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:402:21)
<asynchronous suspension>
#13     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:154:29)
<asynchronous suspension>
#14     _rootRun (dart:async/zone.dart:1124:13)
#15     _CustomZone.run (dart:async/zone.dart:1021:19)
#16     _runZoned (dart:async/zone.dart:1516:10)
#17     runZoned (dart:async/zone.dart:1463:12)
#18     AppContext.run (package:flutter_tools/src/base/context.dart:153:18)
<asynchronous suspension>
#19     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:356:19)
<asynchronous suspension>
#20     CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:112:25)
#21     new Future.sync (dart:async/future.dart:224:31)
#22     CommandRunner.run (package:args/command_runner.dart:112:14)
#23     FlutterCommandRunner.run (package:flutter_tools/src/runner/flutter_command_runner.dart:242:18)
#24     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:63:22)
<asynchronous suspension>
#25     _rootRun (dart:async/zone.dart:1124:13)
#26     _CustomZone.run (dart:async/zone.dart:1021:19)
#27     _runZoned (dart:async/zone.dart:1516:10)
#28     runZoned (dart:async/zone.dart:1500:12)
#29     run.<anonymous closure> (package:flutter_tools/runner.dart:61:18)
<asynchronous suspension>
#30     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:154:29)
<asynchronous suspension>
#31     _rootRun (dart:async/zone.dart:1124:13)
#32     _CustomZone.run (dart:async/zone.dart:1021:19)
#33     _runZoned (dart:async/zone.dart:1516:10)
#34     runZoned (dart:async/zone.dart:1463:12)
#35     AppContext.run (package:flutter_tools/src/base/context.dart:153:18)
<asynchronous suspension>
#36     runInContext (package:flutter_tools/src/context_runner.dart:58:24)
<asynchronous suspension>
#37     run (package:flutter_tools/runner.dart:50:10)
#38     main (package:flutter_tools/executable.dart:65:9)
<asynchronous suspension>
#39     main (file:///C:/flutter/flutter/packages/flutter_tools/bin/flutter_tools.dart:8:3)
#40     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:303:32)
#41     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:12)
```

```info - Name types using UpperCamelCase - admin\lib\Admin\Util\colors_util.dart:1:7 - camel_case_types
   info - This method overrides a method annotated as @mustCallSuper in 'State', but doesn't invoke the overridden method - admin\lib\Admin\add_product.dart:37:8 -
          must_call_super
   info - This function has a return type of 'String', but doesn't end with a return statement - admin\lib\Admin\add_product.dart:158:30 - missing_return
   info - This function has a return type of 'String', but doesn't end with a return statement - admin\lib\Admin\add_product.dart:207:30 - missing_return
   info - The value of the local variable 'imageUrl' isn't used - admin\lib\Admin\add_product.dart:432:18 - unused_local_variable
   info - The value of the local variable 'picture' isn't used - admin\lib\Admin\add_product.dart:433:24 - unused_local_variable
   info - This function has a return type of 'String', but doesn't end with a return statement - admin\lib\Admin\admin.dart:253:22 - missing_return
   info - This function has a return type of 'String', but doesn't end with a return statement - admin\lib\Admin\admin.dart:288:22 - missing_return
   info - Unused import: 'dart:convert' - admin\lib\Admin\db\brand.dart:3:8 - unused_import

9 issues found. (ran in 20.6s)
```

```[√] Flutter (Channel stable, v1.9.1+hotfix.2, on Microsoft Windows [Version 10.0.17134.885], locale en-US)
    • Flutter version 1.9.1+hotfix.2 at C:\flutter\flutter
    • Framework revision 2d2a1ffec9 (3 weeks ago), 2019-09-06 18:39:49 -0700
    • Engine revision b863200c37
    • Dart version 2.5.0


[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at C:\Users\Dineth Narada\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
    • All Android licenses accepted.

[√] Android Studio (version 3.4)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 38.2.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

[√] VS Code (version 1.38.1)
    • VS Code at C:\Users\Dineth Narada\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.4.1

[√] Connected device (1 available)
    • SM G965F • 22d5d794990b7ece • android-arm64 • Android 9 (API 28)

• No issues found!
```

**Comment by BondarenkoStas** [comment]
@dinethnarada Are you sure you run it from the project dir and pubspec.yaml doesn't contain any typos or wrong tabs/spaces?

**Comment by dinethnarada** [comment]
yes.I'm sure

**Comment by jonahwilliams** [comment]
Without a response we're unable to make any progress. I'm closing the issue, but don't hesitate to file a new one if you have the time.
