### ISSUE TITLE
[Camera] Camera plugin throwing CameraAccessException

### ISSUE THREAD

**Issue by steven2947** [flutter/flutter#41589]
When I use the `takePicture` method, it throws `CameraAccessException:The camera device has encountered a serious error`

## Logs
```
09-30 10:25:34.067 10951-10951/com.xxz.android I/CameraManager: Using legacy camera HAL.
09-30 10:25:34.092 10951-11002/com.xxz.android D/mmk: onStatusChangedLocked.+++++++
09-30 10:25:34.092 10951-11002/com.xxz.android E/CameraManagerGlobal: Camera id 0 has status changed to 0x80000000
09-30 10:25:34.124 10951-10951/com.xxz.android I/CameraDeviceState: Legacy camera service transitioning to state CONFIGURING
09-30 10:25:34.124 10951-11270/com.xxz.android I/RequestThread-0: Configure outputs: 2 surfaces configured.
09-30 10:25:34.124 10951-11270/com.xxz.android D/Camera: app passed NULL surface
09-30 10:25:34.126 10951-11270/com.xxz.android I/RequestThread-0: configureOutputs - set take picture size to 320x240
09-30 10:25:34.131 10951-10951/com.xxz.android I/CameraDeviceState: Legacy camera service transitioning to state IDLE
09-30 10:25:34.135 10951-10951/com.xxz.android I/RequestQueue: Repeating capture request set.
09-30 10:25:34.138 10951-11270/com.xxz.android W/LegacyRequestMapper: convertRequestMetadata - control.awbRegions setting is not supported, ignoring value
09-30 10:25:34.139 10951-11270/com.xxz.android W/LegacyRequestMapper: convertRequestToMetadata - Ignoring android.lens.focusDistance false, only 0.0f is supported
09-30 10:25:34.145 10951-10951/com.xxz.android I/RequestQueue: Repeating capture request cancelled.
09-30 10:25:35.865 10951-11271/com.xxz.android I/CameraDeviceState: Legacy camera service transitioning to state CAPTURING
09-30 10:25:35.872 10951-11270/com.xxz.android I/CameraDeviceState: Legacy camera service transitioning to state IDLE
09-30 10:25:35.873 10951-10951/com.xxz.android I/CameraDeviceState: Legacy camera service transitioning to state CONFIGURING
09-30 10:25:35.873 10951-11270/com.xxz.android I/RequestThread-0: Configure outputs: 3 surfaces configured.
09-30 10:25:35.915 10951-11270/com.xxz.android D/Camera: app passed NULL surface
09-30 10:25:35.918 10951-11270/com.xxz.android I/RequestThread-0: configureOutputs - set take picture size to 320x240
09-30 10:25:35.924 10951-10951/com.xxz.android I/CameraDeviceState: Legacy camera service transitioning to state IDLE
09-30 10:25:35.925 10951-10951/com.xxz.android I/Choreographer: Skipped 106 frames!  The application may be doing too much work on its main thread.
09-30 10:25:35.928 10951-10951/com.xxz.android I/RequestQueue: Repeating capture request set.
09-30 10:25:35.931 10951-11270/com.xxz.android W/LegacyRequestMapper: convertRequestMetadata - control.awbRegions setting is not supported, ignoring value
09-30 10:25:35.931 10951-11270/com.xxz.android W/LegacyRequestMapper: convertRequestToMetadata - Ignoring android.lens.focusDistance false, only 0.0f is supported
09-30 10:25:37.718 10951-11271/com.xxz.android I/CameraDeviceState: Legacy camera service transitioning to state CAPTURING
09-30 10:25:41.069 10951-10966/com.xxz.android W/art: Suspending all threads took: 5.621ms
09-30 10:25:41.095 10951-10966/com.xxz.android I/art: Background sticky concurrent mark sweep GC freed 5744(260KB) AllocSpace objects, 90(6MB) LOS objects, 31% free, 13MB/19MB, paused 7.600ms total 41.720ms
09-30 10:25:43.022 10951-11270/com.xxz.android W/LegacyRequestMapper: convertRequestMetadata - control.awbRegions setting is not supported, ignoring value
09-30 10:25:43.032 10951-11270/com.xxz.android W/LegacyMetadataMapper: convertAfModeToLegacy - ignoring unsupported mode 4, defaulting to fixed
09-30 10:25:43.032 10951-11270/com.xxz.android W/LegacyRequestMapper: convertRequestToMetadata - Ignoring android.lens.focusDistance false, only 0.0f is supported
09-30 10:25:44.851 10951-10951/com.xxz.android D/ViewRootImpl: onAttachToWindow register content observer attrs=WM.LayoutParams{(0,0)(wrapxwrap)mPosX=0mPosY=0mHScale=1.0mVScale=1.0 align=UNDEFINE taskId=-1 gr=#11 ty=2005 fl=#1000098 fmt=-3 wanim=0x1030004 surfaceInsets=Rect(0, 0 - 0, 0)packageName=com.xxz.androidtoken=null}
09-30 10:25:44.871 10951-10951/com.xxz.android D/ViewRootImpl: 74<<<<<< BACK FROM relayoutWM.LayoutParams{(0,0)(wrapxwrap)mPosX=0mPosY=0mHScale=1.0mVScale=1.0 align=UNDEFINE taskId=-1 gr=#11 sim=#20 ty=2005 fl=#1000098 fmt=-3 wanim=0x1030004 surfaceInsets=Rect(0, 0 - 0, 0)packageName=com.xxz.androidtoken=null}
09-30 10:25:45.502 10951-11251/com.xxz.android I/RequestThread-0: Received jpeg.
09-30 10:25:45.502 10951-11251/com.xxz.android I/RequestThread-0: Producing jpeg buffer...
09-30 10:25:45.504 10951-10951/com.xxz.android D/ImageReader_JNI: ImageReader_imageSetup: Receiving JPEG in HAL_PIXEL_FORMAT_RGBA_8888 buffer.
09-30 10:25:45.507 10951-11270/com.xxz.android W/LegacyRequestMapper: convertRequestMetadata - control.awbRegions setting is not supported, ignoring value
09-30 10:25:45.507 10951-11270/com.xxz.android W/LegacyRequestMapper: convertRequestToMetadata - Ignoring android.lens.focusDistance false, only 0.0f is supported
09-30 10:25:48.110 10951-11251/com.xxz.android E/Camera: Error 100
09-30 10:25:48.110 10951-11251/com.xxz.android E/RequestThread-0: Received error 100 from the Camera1 ErrorCallback
09-30 10:25:48.110 10951-11251/com.xxz.android I/CameraDeviceState: Legacy camera service transitioning to state ERROR
09-30 10:25:48.111 10951-10951/com.xxz.android E/CameraCaptureSession: Session 1: Exception while stopping repeating: 
    android.hardware.camera2.CameraAccessException: The camera device has encountered a serious error
        at android.hardware.camera2.impl.CameraDeviceImpl.checkIfCameraClosedOrInError(CameraDeviceImpl.java:1478)
        at android.hardware.camera2.impl.CameraDeviceImpl.stopRepeating(CameraDeviceImpl.java:677)
        at android.hardware.camera2.impl.CameraCaptureSessionImpl.close(CameraCaptureSessionImpl.java:328)
        at io.flutter.plugins.camera.Camera.closeCaptureSession(Camera.java:527)
        at io.flutter.plugins.camera.Camera.close(Camera.java:533)
        at io.flutter.plugins.camera.Camera$3.onError(Camera.java:213)
        at android.hardware.camera2.impl.CameraDeviceImpl$CameraDeviceCallbacks$1.run(CameraDeviceImpl.java:1207)
        at android.os.Handler.handleCallback(Handler.java:739)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:135)
        at android.app.ActivityThread.main(ActivityThread.java:5321)
        at java.lang.reflect.Method.invoke(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:372)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:963)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:758)
09-30 10:25:49.561 10951-11270/com.xxz.android E/RequestThread-0: Timed out while waiting for request to complete.
09-30 10:25:49.561 10951-11270/com.xxz.android W/RequestHolder: Capture failed for request: 1
09-30 10:25:49.561 10951-11270/com.xxz.android I/CameraDeviceState: Legacy camera service transitioning to state CAPTURING
09-30 10:25:49.562 10951-11270/com.xxz.android E/CameraDeviceState: Cannot call capture while in state: 0
09-30 10:25:49.567 10951-11082/com.xxz.android E/BufferQueueProducer: [unnamed-10951-4] cancelBuffer: BufferQueue has been abandoned
09-30 10:25:49.569 10951-10968/com.xxz.android E/BufferQueueProducer: [unnamed-10951-4] cancelBuffer: BufferQueue has been abandoned
09-30 10:25:49.570 10951-10984/com.xxz.android E/BufferQueueProducer: [unnamed-10951-4] cancelBuffer: BufferQueue has been abandoned
09-30 10:25:49.572 10951-10967/com.xxz.android E/BufferQueueProducer: [unnamed-10951-4] cancelBuffer: BufferQueue has been abandoned
09-30 10:25:49.613 10951-11002/com.xxz.android D/mmk: onStatusChangedLocked.+++++++
09-30 10:25:49.613 10951-11002/com.xxz.android E/CameraManagerGlobal: Camera id 0 has status changed to 0x1
09-30 10:25:49.619 10951-10951/com.xxz.android D/ViewRootImpl: onDetachedFromWindow ungister contentObserver
09-30 10:25:52.620 10951-10951/com.xxz.android E/MethodChannel#plugins.flutter.io/camera: Failed to handle method call
    java.lang.NullPointerException: Attempt to invoke virtual method 'void android.media.ImageReader.setOnImageAvailableListener(android.media.ImageReader$OnImageAvailableListener, android.os.Handler)' on a null object reference
        at io.flutter.plugins.camera.Camera.takePicture(Camera.java:261)
        at io.flutter.plugins.camera.CameraPlugin.onMethodCall(CameraPlugin.java:96)
        at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:222)
        at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:96)
        at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:656)
        at android.os.MessageQueue.nativePollOnce(Native Method)
        at android.os.MessageQueue.next(MessageQueue.java:143)
        at android.os.Looper.loop(Looper.java:122)
        at android.app.ActivityThread.main(ActivityThread.java:5321)
        at java.lang.reflect.Method.invoke(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:372)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:963)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:758)
09-30 10:25:52.635 10951-11085/com.xxz.android E/flutter: [ERROR:flutter/lib/ui/ui_dart_state.cc(148)] Unhandled Exception: CameraException(error, Attempt to invoke virtual method 'void android.media.ImageReader.setOnImageAvailableListener(android.media.ImageReader$OnImageAvailableListener, android.os.Handler)' on a null object reference)
    #0      CameraController.takePicture (package:camera/camera.dart:363:7)
    <asynchronous suspension>
    #1      FaceCamera.takePhoto (package:goldlok_brand/component/face_camera.dart:50:11)
    <asynchronous suspension>
    #2      FaceRegisterBloc._takePicture (package:goldlok_brand/blocs/face_register/face_register_bloc.dart:150:24)
    <asynchronous suspension>
    #3      FaceRegisterBloc.mapEventToState (package:goldlok_brand/blocs/face_register/face_register_bloc.dart:87:34)
    <asynchronous suspension>
    #4      Bloc._bindStateSubject.<anonymous closure> (package:bloc/src/bloc.dart:136:14)
    #5      Stream.asyncExpand.onListen.<anonymous closure> (dart:async/stream.dart:572:30)
    #6      _rootRunUnary (dart:async/zone.dart:1132:38)
    #7      _CustomZone.runUnary (dart:async/zone.dart:1029:19)
    #8      _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
    #9      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
    #10     _DelayedData.perform (dart:async/stream_impl.dart:591:14)
    #11     _StreamImplEvents.handleNext (dart:async/stream_impl.dart:707:11)
    #12     _PendingEvents.schedule.<anonymous closure> (dart:async/stream_impl.dart:667:7)
    #13     _rootRun (dart:async/zone.dart:1120:38)
    #14     _CustomZone.run (dart:async/zone.dart:1021:19)
    #15     _CustomZone.runGuarded (dart:async/zone.dart:923:7)
    #16     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:963:23)
    #17     _rootRun (dart:async/zone.dart:1124:13)
    #18     _CustomZone.run (dart:async/zone.dart:1021:19)
    #19     _CustomZone.runGuarded (dart:async/zone.dart:923:7)
    #20     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:963:23)
    #21     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
    #22     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
```

## flutter doctor
```
[✓] Flutter (Channel stable, v1.9.1+hotfix.2, on Mac OS X 10.14.6 18G95, locale zh-Hans-CN)
    • Flutter version 1.9.1+hotfix.2 at /Users/steven/Tools/sdk/flutter
    • Framework revision 2d2a1ffec9 (3 weeks ago), 2019-09-06 18:39:49 -0700
    • Engine revision b863200c37
    • Dart version 2.5.0

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/steven/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • ANDROID_HOME = /Users/steven/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 10.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.3, Build version 10G8
    • CocoaPods version 1.6.1

[✓] Android Studio (version 3.4)
    • Android Studio at /Applications/Android Studio 3.4 Preview.app/Contents
    • Flutter plugin version 38.2.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 39.0.3
    • Dart plugin version 191.8423
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] VS Code (version 1.38.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.4.1

[✓] Connected device (1 available)
    • 3288 • 4ZRV45UQ77 • android-arm • Android 5.1.1 (API 22)

Process finished with exit code 0
```

**Comment by TahaTesser** [comment]
Hi @steven2947 
Are you still experiencing this issue?
if so, can you please provide your `flutter doctor -v` and `flutter run --verbose`? 
Also, to better address the issue, would be helpful if you could post a minimal code sample to reproduce the problem
Thank you

**Comment by VladyslavBondarenko** [comment]
Could everyone who still has this problem please file a new issue with logs, complete minimal reproducible code sample and the output of `flutter doctor -v` please.
