### ISSUE TITLE
[Semantics] tester.getSemantics(...) returning unexpected merged semantics node.

### ISSUE THREAD

**Issue by johnsonmh** [flutter/flutter#41645]
I have a custom class that wraps a `FloatingActionButton`. I have a widget test for this class, and I check the semantics of my custom button using `tester.getSemantics(find.byType(MyButton))`. The `SemanticsNode` returned by this method is not the one I would expect to be returned. 

Here is an example of a test I would expect to pass:

```dart
import 'package:flutter/material.dart';
import 'package:flutter_test/flutter_test.dart';

void main() {
  testWidgets('MyButton has correct semantics', (WidgetTester tester) async {
    await tester.pumpWidget(
      MaterialApp(
        home: Scaffold(
          body: Center(
            child: MyButton(),
          ),
        ),
      ),
    );

    expect(
      tester.getSemantics(find.byType(MyButton)),
      matchesSemantics(
        isButton: true,
        isEnabled: true,
        isImage: false,
        hasEnabledState: true,
        hasTapAction: true,
        label: 'foo',
      ),
    );
  });
}

class MyButton extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Padding(
      padding: const EdgeInsets.all(8),
      child: FloatingActionButton(
        tooltip: 'foo',
        onPressed: () {},
      ),
    );
  }
}
```

But when I replace the line 
```dart
tester.getSemantics(find.byType(MyButton)),
```
With:
```dart
tester.getSemantics(
  find.descendant(
    of: find.byType(MyButton),
    matching: find.byType(Semantics),
  ).first,
),
```

The test passes. 

### Flutter Doctor Output

```
[✓] Flutter (Channel fix-textFieldRipple, v1.10.2-pre.165, on Mac OS X 10.14.6 18G87, locale en-US)
    • Flutter version 1.10.2-pre.165 at /Users/<my username>/mdc/flutter
    • Framework revision 8912259b0a (3 days ago), 2019-09-27 15:03:48 -0400
    • Engine revision 18bc0b2596
    • Dart version 2.6.0 (build 2.6.0-dev.0.0 403c4af720)


[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/<my username>/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 10.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.3, Build version 10G8
    • CocoaPods version 1.7.5

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio with Blaze.app/Contents
    • Flutter plugin version 38.2.3
    • Dart plugin version 191.8423
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 39.0.3
    • Dart plugin version 191.8423
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] Connected device (4 available)
    ...

• No issues found!
```

cc @jonahwilliams

**Comment by escamoteur** [comment]
Could you please add the output of your `flutter doctor -v`.

**Comment by johnsonmh** [comment]
@escamoteur Done, amended to issue description.

**Comment by escamoteur** [comment]
@johnsonmh You know that this isn't the latest master? Perhaps an upgrade solves your problem

**Comment by markusaksli-nc** [comment]
Reproducible on the latest master `1.22.0-2.0.pre.78`.
<details>
 <summary>flutter doctor -v</summary>

```
[√] Flutter (Channel master, 1.22.0-2.0.pre.78, on Microsoft Windows [Version 10.0.19041.450], locale en-US)
    • Flutter version 1.22.0-2.0.pre.78 at C:\Development\flutter_master
    • Framework revision d0596582fe (2 hours ago), 2020-08-25 23:26:06 -0700
    • Engine revision b1d9f863db
    • Dart version 2.10.0 (build 2.10.0-56.0.dev)

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
    • Android SDK at C:\Users\marku\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.1
    • Java binary at: C:\Users\marku\AppData\Local\JetBrains\Toolbox\apps\AndroidStudio\ch-0\193.6626763\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.6.5)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.6.30320.27
    • Windows 10 SDK version 10.0.18362.0

[√] Android Studio (version 4.0)
    • Android Studio at C:\Users\marku\AppData\Local\JetBrains\Toolbox\apps\AndroidStudio\ch-0\193.6626763
    • Flutter plugin version 47.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] Connected device (5 available)
    • SM G950F (mobile)           • ce12171c51cc001c03 • android-arm64  • Android 9 (API 28)
    • sdk gphone x86 arm (mobile) • emulator-5554      • android-x86    • Android 11 (API 30) (emulator)
    • Windows (desktop)           • windows            • windows-x64    • Microsoft Windows [Version 10.0.19041.450]
    • Web Server (web)            • web-server         • web-javascript • Flutter Tools
    • Chrome (web)                • chrome             • web-javascript • Google Chrome 84.0.4147.135

• No issues found!
```
</details>



<details>
 <summary>Logs</summary>

```
══╡ EXCEPTION CAUGHT BY FLUTTER TEST FRAMEWORK ╞════════════════════════════════════════════════════
The following TestFailure object was thrown running a test:
  Expected: has semantics with label: foo with actions: [SemanticsAction:SemanticsAction.tap] with
flags: [
            SemanticsFlag:SemanticsFlag.isButton,
            SemanticsFlag:SemanticsFlag.hasEnabledState,
            SemanticsFlag:SemanticsFlag.isEnabled
          ]
  Actual: SemanticsNode:<SemanticsNode#3(Rect.fromLTRB(0.0, 0.0, 800.0, 600.0), flags:
[scopesRoute])>
   Which: label was:

When the exception was thrown, this was the stack:
#4      main.<anonymous closure> (file:///C:/Users/marku/Desktop/triage/master/test/widget_test.dart:16:5)
<asynchronous suspension>
#5      main.<anonymous closure> (file:///C:/Users/marku/Desktop/triage/master/test/widget_test.dart)
#6      testWidgets.<anonymous closure>.<anonymous closure> (package:flutter_test/src/widget_tester.dart:146:29)
<asynchronous suspension>
#7      testWidgets.<anonymous closure>.<anonymous closure> (package:flutter_test/src/widget_tester.dart)
#8      TestWidgetsFlutterBinding._runTestBody (package:flutter_test/src/binding.dart:784:19)
<asynchronous suspension>
#11     TestWidgetsFlutterBinding._runTest (package:flutter_test/src/binding.dart:764:14)
#12     AutomatedTestWidgetsFlutterBinding.runTest.<anonymous closure> (package:flutter_test/src/binding.dart:1173:24)
#13     FakeAsync.run.<anonymous closure>.<anonymous closure> (package:fake_async/fake_async.dart:178:54)
#18     withClock (package:clock/src/default.dart:48:10)
#19     FakeAsync.run.<anonymous closure> (package:fake_async/fake_async.dart:178:22)
#24     FakeAsync.run (package:fake_async/fake_async.dart:178:7)
#25     AutomatedTestWidgetsFlutterBinding.runTest (package:flutter_test/src/binding.dart:1170:15)
#26     testWidgets.<anonymous closure> (package:flutter_test/src/widget_tester.dart:138:24)
#27     Declarer.test.<anonymous closure>.<anonymous closure> (package:test_api/src/backend/declarer.dart:175:19)
<asynchronous suspension>
#28     Declarer.test.<anonymous closure>.<anonymous closure> (package:test_api/src/backend/declarer.dart)
#33     Declarer.test.<anonymous closure> (package:test_api/src/backend/declarer.dart:173:13)
#34     Invoker.waitForOutstandingCallbacks.<anonymous closure> (package:test_api/src/backend/invoker.dart:231:15)
#39     Invoker.waitForOutstandingCallbacks (package:test_api/src/backend/invoker.dart:228:5)
#40     Invoker._onRun.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:test_api/src/backend/invoker.dart:383:17)
<asynchronous suspension>
#41     Invoker._onRun.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:test_api/src/backend/invoker.dart)
#46     Invoker._onRun.<anonymous closure>.<anonymous closure> (package:test_api/src/backend/invoker.dart:370:9)
#47     Invoker._guardIfGuarded (package:test_api/src/backend/invoker.dart:415:15)
#48     Invoker._onRun.<anonymous closure> (package:test_api/src/backend/invoker.dart:369:7)
#55     Invoker._onRun (package:test_api/src/backend/invoker.dart:368:11)
#56     LiveTestController.run (package:test_api/src/backend/live_test_controller.dart:153:11)
#57     RemoteListener._runLiveTest.<anonymous closure> (package:test_api/src/remote_listener.dart:256:16)
#62     RemoteListener._runLiveTest (package:test_api/src/remote_listener.dart:255:5)
#63     RemoteListener._serializeTest.<anonymous closure> (package:test_api/src/remote_listener.dart:208:7)
#81     _GuaranteeSink.add (package:stream_channel/src/guarantee_channel.dart:125:12)
#82     new _MultiChannel.<anonymous closure> (package:stream_channel/src/multi_channel.dart:159:31)
#86     CastStreamSubscription._onData (dart:_internal/async_cast.dart:85:11)
#120    new _WebSocketImpl._fromSocket.<anonymous closure> (dart:_http/websocket_impl.dart:1145:21)
#128    _WebSocketProtocolTransformer._messageFrameEnd (dart:_http/websocket_impl.dart:338:23)
#129    _WebSocketProtocolTransformer.add (dart:_http/websocket_impl.dart:232:46)
#139    _Socket._onData (dart:io-patch/socket_patch.dart:2044:41)
#148    new _RawSocket.<anonymous closure> (dart:io-patch/socket_patch.dart:1580:33)
#149    _NativeSocket.issueReadEvent.issue (dart:io-patch/socket_patch.dart:1076:14)
(elided 111 frames from dart:async and package:stack_trace)

This was caught by the test expectation on the following line:
  file:///C:/Users/marku/Desktop/triage/master/test/widget_test.dart line 16
The test description was:
  MyButton has correct semantics
════════════════════════════════════════════════════════════════════════════════════════════════════
```
</details>
<details>
 <summary>Semantics tree</summary>

```
I/flutter (10733): SemanticsNode#0
I/flutter (10733):  │ Rect.fromLTRB(0.0, 0.0, 1080.0, 2028.0)
I/flutter (10733):  │
I/flutter (10733):  └─SemanticsNode#1
I/flutter (10733):    │ Rect.fromLTRB(0.0, 0.0, 392.7, 737.5) scaled by 2.8x
I/flutter (10733):    │ textDirection: ltr
I/flutter (10733):    │
I/flutter (10733):    └─SemanticsNode#2
I/flutter (10733):      │ Rect.fromLTRB(0.0, 0.0, 392.7, 737.5)
I/flutter (10733):      │ sortKey: OrdinalSortKey#697a5(order: 0.0)
I/flutter (10733):      │
I/flutter (10733):      └─SemanticsNode#3
I/flutter (10733):        │ Rect.fromLTRB(0.0, 0.0, 392.7, 737.5)
I/flutter (10733):        │ flags: scopesRoute
I/flutter (10733):        │
I/flutter (10733):        └─SemanticsNode#4
I/flutter (10733):          │ merge boundary ⛔️
I/flutter (10733):          │ Rect.fromLTRB(168.4, 340.7, 224.4, 396.7)
I/flutter (10733):          │ label: "foo"
I/flutter (10733):          │ textDirection: ltr
I/flutter (10733):          │
I/flutter (10733):          └─SemanticsNode#5
I/flutter (10733):              merged up ⬆️
I/flutter (10733):              Rect.fromLTRB(0.0, 0.0, 56.0, 56.0)
I/flutter (10733):              actions: tap
I/flutter (10733):              flags: isButton, hasEnabledState, isEnabled, isFocusable
I/flutter (10733):              thickness: 6.0
I/flutter (10733):
```
</details>

**Comment by TahaTesser** [comment]
Reproducible steps https://github.com/flutter/flutter/issues/83572#issuecomment-851852722

Reproduced on the following channels
|  `stable`  | `master` |
| :---: |:---: |
|  ❌  |   ❌  | 

Check `flutter doctor -v` outputs for each channel below

<details> 
<summary>flutter doctor -v</summary> 
	
```console
[✓] Flutter (Channel stable, 2.2.1, on Microsoft Windows [Version 10.0.19043.1023], locale en-US)
    • Flutter version 2.2.1 at C:\Users\Taha\Code\flutter_stable
    • Framework revision 02c026b03c (5 days ago), 2021-05-27 12:24:44 -0700
    • Engine revision 0fdb562ac8
    • Dart version 2.13.1

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Users\Taha\Code\SDK
    • Platform android-30, build-tools 30.0.3
    • ANDROID_SDK_ROOT = C:\Users\Taha\Code\SDK
    • Java binary at: C:\Users\Taha\Code\openjdk\bin\java.exe
    • Java version OpenJDK Runtime Environment (build 1.8.0-262-b10)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[✓] Visual Studio - develop for Windows (Visual Studio Community 2019 16.10.0)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.10.31321.278
    • Windows 10 SDK version 10.0.19041.0

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/windows#android-setup for detailed instructions).

[✓] IntelliJ IDEA Community Edition (version 2021.1)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2021.1.1
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.56.2)
    • VS Code at C:\Users\Taha\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.22.0

[✓] Connected device (4 available)
    • AOSP on IA Emulator (mobile) • emulator-5554 • android-x86    • Android 9 (API 28) (emulator)
    • Windows (desktop)            • windows       • windows-x64    • Microsoft Windows [Version 10.0.19043.1023]
    • Chrome (web)                 • chrome        • web-javascript • Google Chrome 90.0.4430.212
    • Edge (web)                   • edge          • web-javascript • Microsoft Edge 91.0.864.37

! Doctor found issues in 1 category.
```

```console
[✓] Flutter (Channel master, 2.3.0-17.0.pre.121, on Microsoft Windows [Version 10.0.19043.1023], locale en-US)
    • Flutter version 2.3.0-17.0.pre.121 at C:\Users\Taha\Code\flutter_master
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 71e711547f (32 hours ago), 2021-05-30 19:31:03 -0700
    • Engine revision 73fe3dd31c
    • Dart version 2.14.0 (build 2.14.0-165.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Users\Taha\Code\SDK
    • Platform android-30, build-tools 30.0.3
    • ANDROID_SDK_ROOT = C:\Users\Taha\Code\SDK
    • Java binary at: C:\Users\Taha\Code\android-studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6842174)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[✓] Visual Studio - develop for Windows (Visual Studio Community 2019 16.10.0)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.10.31321.278
    • Windows 10 SDK version 10.0.19041.0

[✓] Android Studio (version 4.2.0)
    • Android Studio at C:\Users\Taha\Code\android-studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6842174)

[✓] IntelliJ IDEA Community Edition (version 2021.1)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2021.1.1
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.56.2)
    • VS Code at C:\Users\Taha\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.22.0

[✓] Connected device (5 available)
    • AOSP on IA Emulator (mobile) • emulator-5554 • android-x86     • Android 9 (API 28) (emulator)
    • Windows (desktop)            • windows       • windows-x64     • Microsoft Windows [Version 10.0.19043.1023]
    • Windows (UWP) (desktop)      • winuwp        • windows-uwp-x64 •
    • Chrome (web)                 • chrome        • web-javascript  • Google Chrome 90.0.4430.212
    • Edge (web)                   • edge          • web-javascript  • Microsoft Edge 91.0.864.37

• No issues found!
```
		
</details>

✅ : No Issue ❌: has Issue
