### ISSUE TITLE
Need better error message when pushing a route name that's not recognized

### ISSUE THREAD

**Issue by HansMuller** [flutter/flutter#4172]
I didn't really find it confusing but I think some developers might.  The failure is reported like this:
 `config.onUnknownRoute != null' is not true`

I think it would be clearer if the reported error indicated that pushNamed had failed because it didn't recognize the the route's name which was '...'.

```
I/flutter : ══╡ EXCEPTION CAUGHT BY GESTURE LIBRARY ╞═══════════════════════════════════════════════════════════
I/flutter : The following assertion was thrown while dispatching a pointer event:
I/flutter : 'package:flutter/src/widgets/navigator.dart': Failed assertion: line 339: 'config.onUnknownRoute !=
I/flutter : null' is not true.
I/flutter : Either the assertion indicates an error in the framework itself, or we should provide substantially
I/flutter : more information in this error message to help you determine and fix the underlying cause.
I/flutter : In either case, please report this assertion by filing a bug on GitHub:
I/flutter :   https://github.com/flutter/flutter/issues/new
I/flutter : When the exception was thrown, this was the stack:
I/flutter : #0      _AssertionError._throwNew (dart:core-patch/errors_patch.dart:27)
I/flutter : #1      NavigatorState._pushNamed (package:flutter/src/widgets/navigator.dart:339)
I/flutter : #2      NavigatorTransaction.pushNamed (package:flutter/src/widgets/navigator.dart:514)
I/flutter : #3      Navigator.pushNamed.<anonymous closure> (package:flutter/src/widgets/navigator.dart:181)
I/flutter : #4      NavigatorState.openTransaction.<anonymous closure> (package:flutter/src/widgets/navigator.dart:483)
I/flutter : #5      State.setState (package:flutter/src/widgets/framework.dart:419)
I/flutter : #6      NavigatorState.openTransaction (package:flutter/src/widgets/navigator.dart:482)
I/flutter : #7      Navigator.openTransaction (package:flutter/src/widgets/navigator.dart:272)
I/flutter : #8      Navigator.pushNamed (package:flutter/src/widgets/navigator.dart:180)
I/flutter : #9      GalleryItem.build.<anonymous closure> (/builds/dev/flutter/examples/flutter_gallery/lib/gallery/item.dart:31)
I/flutter : #10     _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:161)
I/flutter : #11     TapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:116)
I/flutter : #12     TapGestureRecognizer.acceptGesture (package:flutter/src/gestures/tap.dart:87)
I/flutter : #13     GestureArenaManager.sweep (package:flutter/src/gestures/arena.dart:107)
I/flutter : #14     BindingBase&SchedulerBinding&GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:119)
I/flutter : #15     BindingBase&SchedulerBinding&GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:93)
I/flutter : #16     BindingBase&SchedulerBinding&GestureBinding._handlePointerEvent (package:flutter/src/gestures/binding.dart:70)
I/flutter : #17     BindingBase&SchedulerBinding&GestureBinding._handlePointerPacket (package:flutter/src/gestures/binding.dart:42)
I/flutter : #18     _dispatchPointerPacket (file:///b/build/slave/Linux_Engine/build/src/out/android_debug/gen/sky/bindings/hooks.dart:43)
I/flutter : Event:
I/flutter :   PointerUpEvent(Point(125.3, 357.3))
I/flutter : Target:
I/flutter :   <WidgetsFlutterBinding>
I/flutter : ════════════════════════════════════════════════════════════════════════════════════════════════════
```

**Comment by chunhtai** [comment]
the navigator has changed a lot since and i expect https://github.com/flutter/flutter/blob/77ea848c462eb0eafa9a01d76a678317d7470890/packages/flutter/lib/src/widgets/navigator.dart#L3141 to produce a better error message now
