### ISSUE TITLE
Improve error message on "Gradle task assembleDebug failed with exit code 1"

### ISSUE THREAD

**Issue by leemuljadi** [flutter/flutter#41766]
I want to run my app while using the latest download of Android Studio in a new machine, but couldn't run because of Graddle issue.

**Flutter Doctor**
```
[√] Flutter (Channel stable, v1.9.1+hotfix.4, on Microsoft Windows [Version 10.0.17763.107], locale en-US)
    • Flutter version 1.9.1+hotfix.4 at C:\Flutter\flutter
    • Framework revision cc949a8e8b (4 days ago), 2019-09-27 15:04:59 -0700
    • Engine revision b863200c37
    • Dart version 2.5.0

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at C:\Users\bluesky\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)
    • All Android licenses accepted.

[√] Android Studio (version 3.5)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 40.0.2
    • Dart plugin version 191.8423
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)

[√] Connected device (1 available)
    • Redmi 4X • 2be0bae7d630 • android-arm64 • Android 7.1.2 (API 25)

• No issues found!
Process finished with exit code 0
```

**Flutter Run**
```
Initializing gradle...                                              0.8s
Resolving dependencies...                                          13.8s
Running Gradle task 'assembleDebug'...
Running Gradle task 'assembleDebug'... Done                        11.2s
Gradle task assembleDebug failed with exit code 1
```

**Flutter Run -V**
```
Gradle task assembleDebug failed with exit code 1

#0      throwToolExit (package:flutter_tools/src/base/common.dart:28:3)
#1      _buildGradleProjectV2 (package:flutter_tools/src/android/gradle.dart:751:5)
<asynchronous suspension>
#2      buildGradleProject (package:flutter_tools/src/android/gradle.dart:494:14)
<asynchronous suspension>
#3      buildApk (package:flutter_tools/src/android/apk.dart:34:9)
<asynchronous suspension>
#4      AndroidDevice.startApp (package:flutter_tools/src/android/android_device.dart:486:13)
<asynchronous suspension>
#5      FlutterDevice.runHot (package:flutter_tools/src/resident_runner.dart:378:54)
<asynchronous suspension>
#6      HotRunner.run (package:flutter_tools/src/run_hot.dart:254:39)
<asynchronous suspension>
#7      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:472:37)
<asynchronous suspension>
#8      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:490:18)
#9      _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:71:64)
#10     _rootRunUnary (dart:async/zone.dart:1132:38)
#11     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#12     _FutureListener.handleValue (dart:async/future_impl.dart:137:18)
#13     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:678:45)
#14     Future._propagateToListeners (dart:async/future_impl.dart:707:32)
#15     Future._completeWithValue (dart:async/future_impl.dart:522:5)
#16     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:30:15)
#17     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:288:13)
#18     RunCommand.usageValues (package:flutter_tools/src/commands/run.dart)
#19     _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:71:64)
#20     _rootRunUnary (dart:async/zone.dart:1132:38)
#21     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#22     _FutureListener.handleValue (dart:async/future_impl.dart:137:18)
#23     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:678:45)
#24     Future._propagateToListeners (dart:async/future_impl.dart:707:32)
#25     Future._completeWithValue (dart:async/future_impl.dart:522:5)
#26     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:30:15)
#27     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:288:13)
#28     AndroidDevice.isLocalEmulator (package:flutter_tools/src/android/android_device.dart)
#29     _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:71:64)
#30     _rootRunUnary (dart:async/zone.dart:1132:38)
#31     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#32     _FutureListener.handleValue (dart:async/future_impl.dart:137:18)
#33     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:678:45)
#34     Future._propagateToListeners (dart:async/future_impl.dart:707:32)
#35     Future._completeWithValue (dart:async/future_impl.dart:522:5)
#36     Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:552:7)
#37     _rootRun (dart:async/zone.dart:1124:13)
#38     _CustomZone.run (dart:async/zone.dart:1021:19)
#39     _CustomZone.runGuarded (dart:async/zone.dart:923:7)
#40     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:963:23)
#41     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#42     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#43     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:116:13)
#44     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:173:5)

```

**Comment by escamoteur** [comment]
Hi,
thanks for reporting. This seems similar to https://github.com/flutter/flutter/issues/31289

Maybe this here could help https://github.com/flutter/flutter/issues/27234

**Comment by jaumard** [comment]
I get this sometimes,  to have the real cause of the problem I have to open the android project and try to run it to have the real errors. 

Might be nice to have it directly instead of "...failed with exit code 1" but at least it's not a blocker generally

**Comment by leemuljadi** [comment]
Hi @escamoteur @jaumard ,

Thanks so much for your help!
I follow the instruction here: 
![image](https://user-images.githubusercontent.com/48749437/66120099-6e458280-e61d-11e9-86c3-dcdca98f61c6.png)

Then it showing more detailed console message that I'm missing the google-services.json file from firebase since didn't cloned from my remote repo.

I changed back the gradle-wrapper.properties to distributionUrl=https\://services.gradle.org/distributions/gradle-5.4.1-all.zip
and project level build.gradle to 
dependencies {
        classpath 'com.android.tools.build:gradle:3.5.0'
    }
again and this still works fine.

Do you recommend just use the latest one or downgrade according to the instruction on the image?

Thanks so much for the help!

**Comment by escamoteur** [comment]
Even if this case was solved, can we do actively something against it or at least show a better error message instead of `with exit code 1`

**Comment by githubbfw** [comment]
你这个帮我解决了这个问题，就是原来的别人的项目，里面gradle的插件版本太低了，就会出现这个问题。

**Comment by escamoteur** [comment]
@githubbfw Please be so kind and write in English which all can understand.

**Comment by fredgrott** [comment]
what I notice thus far ins using flutter a few months is I get exit 1 codes if there is a problem between the gradle plugin  flutter uses and the one android studio uses ..right now going through updating gradle version to the one android studio uses to get around the exit 1 error..the gist is we have no warning when this occurs...

**Comment by prashant-shahi** [comment]
I got something similar while running the sample example app:

```
  Launching lib/main.dart on GM1901 in debug mode...
  Running Gradle task 'assembleDebug'...
  
  FAILURE: Build failed with an exception.
  
  * What went wrong:
  Execution failed for task ':app:desugarDebugFileDependencies'.
  > A failure occurred while executing com.android.build.gradle.internal.tasks.Workers$ActionFacade
  > /Users/codegeas/Library/Android/sdk/build-tools/28.0.3/core-lambda-stubs.jar
  
  * Try:
  Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
  
  * Get more help at https://help.gradle.org
  
  BUILD FAILED in 15s
  Finished with error: Gradle task assembleDebug failed with exit code 1
```

Making changes to the build.gradle worked out for me, from `classpath com.android.tools.build:gradle:3.5.0` to `classpath com.android.tools.build:gradle:3.4.2`.

**Comment by jonahwilliams** [comment]
We show a lot more information by default now, closing:

```
jonahwilliams-macbookpro2:hello_world jonahwilliams$ flutter build apk
                                                                        
Compiler message:                                                       
lib/main.dart:12:11: Error: Expected ',' before this.                   
          key: Key('title'),                                            
          ^^^                                                           
Target kernel_snapshot failed: Exception: Errors during snapshot creation: null
build failed.                                                           
                                                                        
FAILURE: Build failed with an exception.                                
                                                                        
* Where:                                                                
Script '/Users/jonahwilliams/Documents/flutter/packages/flutter_tools/gradle/flutter.gradle' line: 883
                                                                        
* What went wrong:                                                      
Execution failed for task ':app:compileFlutterBuildRelease'.            
> Process 'command '/Users/jonahwilliams/Documents/flutter/bin/flutter'' finished with non-zero exit value 1
                                                                        
* Try:                                                                  
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
                                                                        
* Get more help at https://help.gradle.org                              
                                                                        
BUILD FAILED in 5s                                                      
Running Gradle task 'assembleRelease'...                                
Running Gradle task 'assembleRelease'... Done                       5.7s
Gradle task assembleRelease failed with exit code 1
```
