### ISSUE TITLE
Exception on scrollController.animateTo

### ISSUE THREAD

**Issue by kaina404** [flutter/flutter#41783]
```dart
//update datas
dataList.clear();
 dataList.addAll(issuesList.sublist(0, commentIndex - 1));
setState(() {});
//scroll to bottom,and exception from here
 scrollController.animateTo(scrollController.position.maxScrollExtent, duration: Duration(microseconds: 1400), curve: Curves.easeInCubic);
```

**Exception Detail**

```dart
[ERROR:flutter/lib/ui/ui_dart_state.cc(148)] Unhandled Exception: 'package:flutter/src/rendering/box.dart': Failed assertion: line 1692 pos 18: 'debugDoingThisResize || debugDoingThisLayout ||
E/flutter (16271):                  (RenderObject.debugActiveLayout == parent && _size._canBeUsedByParent)': is not true.
E/flutter (16271): #0      _AssertionError._doThrowNew (dart:core-patch/errors_patch.dart:40:39)
E/flutter (16271): #1      _AssertionError._throwNew (dart:core-patch/errors_patch.dart:36:5)
E/flutter (16271): #2      RenderBox.size.<anonymous closure> (package:flutter/src/rendering/box.dart:1692:18)
E/flutter (16271): #3      RenderBox.size (package:flutter/src/rendering/box.dart:1698:6)
E/flutter (16271): #4      RenderAndroidView._sizePlatformView (package:flutter/src/rendering/platform_view.dart:179:14)
E/flutter (16271): <asynchronous suspension>
E/flutter (16271): #5      RenderAndroidView.performResize (package:flutter/src/rendering/platform_view.dart:155:5)
E/flutter (16271): #6      RenderObject.layout (package:flutter/src/rendering/object.dart:1686:9)
E/flutter (16271): #7      RenderConstrainedBox.performLayout (package:flutter/src/rendering/proxy_box.dart:259:13)
E/flutter (16271): #8      RenderObject.layout (package:flutter/src/rendering/object.dart:1701:7)
E/flutter (16271): #9      RenderFlex.performLayout (package:flutter/src/rendering/flex.dart:744:15)
E/flutter (16271): #10     RenderObject.layout (package:flutter/src/rendering/object.dart:1701:7)
E/flutter (16271): #11     RenderPadding.performLayout (package:flutter/src/rendering/shifted_box.dart:206:11)
E/flutter (16271): #12     RenderObject.layout (package:flutter/src/rendering/object.dart:1701:7)
E/flutter (16271): #13     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
E/flutter (16271): #14     RenderObject.layout (package:flutter/src/rendering/object.dart:1701:7)
E/flutter (16271): #15     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
E/flutter (16271): #16     RenderObject.layout (package:flutter/src/rendering/object.dart:1701:7)
E/flutter (16271): #17     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
E/flutter (16271): #18     RenderObject.layout (package:flutter/src/rendering/object.dart:1701:7)
E/flutter (16271): #19     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
E/flutter (16271): #20     RenderObject.layout (package:flutter/src/rendering/object.dart:1701:7)
E/flutter (16271): #21     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
E/flutter (16271): #22     RenderObject.layout (package:flutter/src/rendering/object.dart:1701:7)
E/flutter (16271): #23     RenderSliverMultiBoxAdaptor.insertAndLayoutChild (package:flutter/src/rendering/sliver_multi_box_adaptor.dart:492:13)
E/flutter (16271): #24     RenderSliverList.performLayout.advance (package:flutter/src/rendering/sliver_list.dart:195:19)
E/flutter (16271): #25     RenderSliverList.performLayout (package:flutter/src/rendering/sliver_list.dart:238:19)
E/flutter (16271): #26     RenderObject.layout (package:flutter/src/rendering/object.dart:1701:7)
E/flutter (16271): #27     RenderSliverPadding.performLayout (package:flutter/src/rendering/sliver_padding.dart:181:11)
E/flutter (16271): #28     RenderObject.layout (package:flutter/src/rendering/object.dart:1701:7)
E/flutter (16271): #29     RenderViewportBase.layoutChildSequence (package:flutter/src/rendering/viewport.dart:406:13)
E/flutter (16271): #30     RenderViewport._attemptLayout (package:flutter/src/rendering/viewport.dart:1352:12)
E/flutter (16271): #31     RenderViewport.performLayout (package:flutter/src/rendering/viewport.dart:1270:20)
E/flutter (16271): #32     RenderObject.layout (package:flutter/src/rendering/object.dart:1701:7)
E/flutter (16271): #33     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
E/flutter (16271): #34     RenderObject.layout (package:flutter/src/rendering/object.dart:1701:7)
E/flutter (16271): #35     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
E/flutter (16271): #36     RenderObject.layout (package:flutter/src/rendering/object.dart:1701:7)
E/flutter (16271): #37     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
E/flutter (16271): #38     RenderObject.layout (package:flutter/src/rendering/object.dart:1701:7)
E/flutter (16271): #39     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
E/flutter (16271): #40     RenderObject.layout (package:flutter/src/rendering/object.dart:1701:7)
E/flutter (16271): #41     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
E/flutter (16271): #42     RenderObje
````

**flutter doctor**
```dart

Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, v1.9.1+hotfix.2, on Mac OS X 10.14.6 18G95, locale zh-Hans-CN)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 11.0)
[✓] Android Studio (version 3.5)
[✓] Connected device (1 available)

• No issues found!

```

**Comment by HansMuller** [comment]
Please provide the output of `flutter doctor -v` and a small self-contained app that demonstrates the problem. Note also: https://gist.github.com/ is a useful way to share the code.
