### ISSUE TITLE
[web] flutter web build fails with internal class issue

### ISSUE THREAD

**Issue by tapeo** [flutter/flutter#41904]
After `flutter build web`:

```
#0      Dart2JSTarget.build                                             
(package:flutter_tools/src/build_system/targets/web.dart:150:7)
<asynchronous suspension>
#1      _BuildInstance._invokeInternal
(package:flutter_tools/src/build_system/build_system.dart:527:25)
<asynchronous suspension>
#2      _BuildInstance.invokeTarget.<anonymous closure>
(package:flutter_tools/src/build_system/build_system.dart:482:35)
#3      new Future.sync (dart:async/future.dart:224:31)
#4      AsyncMemoizer.runOnce (package:async/src/async_memoizer.dart:43:45)
#5      _BuildInstance.invokeTarget
(package:flutter_tools/src/build_system/build_system.dart:482:21)
<asynchronous suspension>
<asynchronous suspension>
#6      BuildSystem.build
(package:flutter_tools/src/build_system/build_system.dart:420:36)
#7      _AsyncAwaitCompleter.start (dart:async-patch/async_patch.dart:43:6)
#8      BuildSystem.build
(package:flutter_tools/src/build_system/build_system.dart:401:28)
#9      buildWeb (package:flutter_tools/src/web/compile.dart:32:56)
#10     _AsyncAwaitCompleter.start (dart:async-patch/async_patch.dart:43:6)
#11     buildWeb (package:flutter_tools/src/web/compile.dart:24:22)
#12     BuildWebCommand.runCommand
(package:flutter_tools/src/commands/build_web.dart:56:11)
#13     _AsyncAwaitCompleter.start (dart:async-patch/async_patch.dart:43:6)
#14     BuildWebCommand.runCommand
(package:flutter_tools/src/commands/build_web.dart:46:42)
#15     FlutterCommand.verifyThenRunCommand
(package:flutter_tools/src/runner/flutter_command.dart:553:18)
#16     _asyncThenWrapperHelper.<anonymous closure>
(dart:async-patch/async_patch.dart:71:64)
#17     _rootRunUnary (dart:async/zone.dart:1132:38)
#18     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#19     _FutureListener.handleValue (dart:async/future_impl.dart:137:18)
#20     Future._propagateToListeners.handleValueCallback
(dart:async/future_impl.dart:678:45)
#21     Future._propagateToListeners (dart:async/future_impl.dart:707:32)
#22     Future._completeWithValue (dart:async/future_impl.dart:522:5)
#23     Future._asyncComplete.<anonymous closure>
(dart:async/future_impl.dart:552:7)
#24     _rootRun (dart:async/zone.dart:1124:13)
#25     _CustomZone.run (dart:async/zone.dart:1021:19)
#26     _CustomZone.runGuarded (dart:async/zone.dart:923:7)
#27     _CustomZone.bindCallbackGuarded.<anonymous closure>
(dart:async/zone.dart:963:23)
#28     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#29     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#30     _runPendingImmediateCallback
(dart:isolate-patch/isolate_patch.dart:116:13)
#31     _RawReceivePortImpl._handleMessage
(dart:isolate-patch/isolate_patch.dart:173:5)


Exception: lib/main.dart:92:12:                                         
Error: The argument type 'LocalStorage/*1*/' can't be assigned to the parameter
type 'LocalStorage/*2*/'.
 - 'LocalStorage/*1*/' is from 'lib/model/storage.dart'.
 - 'LocalStorage/*2*/' is from 'package:project/model/storage.dart'
 ('lib/model/storage.dart').
  Log.send(prefs, "6", error.toString()).then((data) {
           ^
Error: Compilation failed.
```

flutter doctor -v :
```
[✓] Flutter (Channel master, v1.10.8-pre.21, on Mac OS X 10.14.6 18G103, locale
    it-IT)
    • Flutter version 1.10.8-pre.21 at /Users/matteo/development/flutter
    • Framework revision fa7340a328 (11 hours ago), 2019-10-02 19:04:50 -0400
    • Engine revision 73dd5a33d9
    • Dart version 2.6.0 (build 2.6.0-dev.0.0 eaf1c308ab)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/matteo/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling
      support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.0, Build version 11A420a
    • CocoaPods version 1.7.5

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 39.0.3
    • Dart plugin version 191.8423
    • Java version OpenJDK Runtime Environment (build
      1.8.0_202-release-1483-b49-5587405)

[!] VS Code (version 1.38.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    ✗ Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (2 available)
    • Chrome          • chrome          • web-javascript • Google Chrome
      77.0.3865.90
    • Headless Server • headless-server • web-javascript • Flutter Tools

! Doctor found issues in 1 category.
```

**Comment by jonahwilliams** [comment]
This looks like a type error in your code?

```
Exception: lib/main.dart:92:12:                                         
Error: The argument type 'LocalStorage/*1*/' can't be assigned to the parameter
type 'LocalStorage/*2*/'.
 - 'LocalStorage/*1*/' is from 'lib/model/storage.dart'.
 - 'LocalStorage/*2*/' is from 'package:project/model/storage.dart'
 ('lib/model/storage.dart').
  Log.send(prefs, "6", error.toString()).then((data) {
```

**Comment by tapeo** [comment]
I check it on my project and the IDE doesn't shows warning about that. Is the `*2*` that it sounds strange to me.

**Comment by jonahwilliams** [comment]
`lib/model/storage.dart` is your project right?

**Comment by tapeo** [comment]
yes it is

**Comment by jonahwilliams** [comment]
What is probably happening is that you are importing this `LocalStorage` from both a relative and package uri, which will technically make them different classes. If you fix the imports to be only relative or only package imports that should fix the problem. 

Closing because this is not a flutter issue.
