### ISSUE TITLE
flutter\packages\flutter_tools\gradle\flutter.gradle' line: 27 Error while doing Flutter Run command

### ISSUE THREAD

**Issue by code-utk** [flutter/flutter#41925]
Tried to Run flutter run command but got the following error please help

## LOG
```
Initializing gradle...                                              1.2s
Resolving dependencies...
* Error running Gradle:
ProcessException: Process "D:\Download's
FireFox\How-to-Build-a-Biomedical-Startup-master\How-to-Build-a-Biomedical-Startup-maste
r\android\gradlew.bat" exited abnormally:
NDK is missing a "platforms" directory.
If you are using NDK, verify the ndk.dir is set to a valid NDK directory.  It is
currently set to C:\Users\utkar\AppData\Local\Android\sdk\ndk-bundle.
If you are not using NDK, unset the NDK variable from ANDROID_NDK_HOME or
local.properties to remove this warning.


BUILD FAILED

Total time: 1.64 secs

Failed to notify ProjectEvaluationListener.afterEvaluate(), but primary configuration
failure takes precedence.
java.lang.IllegalStateException: buildToolsVersion is not specified.
        at com.google.common.base.Preconditions.checkState(Preconditions.java:173)
        at com.android.build.gradle.BasePlugin.createAndroidTasks(BasePlugin.java:558)
        at com.android.build.gradle.BasePlugin.lambda$null$4(BasePlugin.java:526)
        at com.android.builder.profile.ThreadRecorder.record(ThreadRecorder.java:81)
        at com.android.build.gradle.BasePlugin.lambda$createTasks$5(BasePlugin.java:522)
        at
        org.gradle.internal.event.BroadcastDispatch$ActionInvocationHandler.dispatch(BroadcastD
        ispatch.java:93)
        at
        org.gradle.internal.event.BroadcastDispatch$ActionInvocationHandler.dispatch(BroadcastD
        ispatch.java:82)
        at
        org.gradle.internal.event.AbstractBroadcastDispatch.dispatch(AbstractBroadcastDispatch.
        java:44)
        at org.gradle.internal.event.BroadcastDispatch.dispatch(BroadcastDispatch.java:79)
        at org.gradle.internal.event.BroadcastDispatch.dispatch(BroadcastDispatch.java:30)
        at
        org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(P
        roxyDispatchAdapter.java:93)
        at com.sun.proxy.$Proxy16.afterEvaluate(Unknown Source)
        at
        org.gradle.configuration.project.LifecycleProjectEvaluator.notifyAfterEvaluate(Lifecycl
        eProjectEvaluator.java:82)
        at
        org.gradle.configuration.project.LifecycleProjectEvaluator.doConfigure(LifecycleProject
        Evaluator.java:76)
        at
        org.gradle.configuration.project.LifecycleProjectEvaluator.access$000(LifecycleProjectE
        valuator.java:33)
        at
        org.gradle.configuration.project.LifecycleProjectEvaluator$1.execute(LifecycleProjectEv
        aluator.java:53)
        at
        org.gradle.configuration.project.LifecycleProjectEvaluator$1.execute(LifecycleProjectEv
        aluator.java:50)
        at org.gradle.internal.Transformers$4.transform(Transformers.java:169)
        at
        org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExe
        cutor.java:106)
        at
        org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExe
        cutor.java:61)
        at
        org.gradle.configuration.project.LifecycleProjectEvaluator.evaluate(LifecycleProjectEva
        luator.java:50)
        at org.gradle.api.internal.project.DefaultProject.evaluate(DefaultProject.java:628)
        at
        org.gradle.api.internal.project.DefaultProject.evaluationDependsOn(DefaultProject.java:
        699)
        at
        org.gradle.api.internal.project.DefaultProject.evaluationDependsOn(DefaultProject.java:
        691)
        at org.gradle.api.Project$evaluationDependsOn.call(Unknown Source)
        at build_d0sn1lellexnujernafbcwql1$_run_closure2.doCall(D:\Download's
        FireFox\How-to-Build-a-Biomedical-Startup-master\How-to-Build-a-Biomedical-Startup-mast
        er\android\build.gradle:20)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at
        sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:93)
        at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
        at
        org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.ja
        va:294)
        at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1024)
        at groovy.lang.Closure.call(Closure.java:414)
        at groovy.lang.Closure.call(Closure.java:430)
        at org.gradle.api.internal.ClosureBackedAction.execute(ClosureBackedAction.java:70)
        at org.gradle.util.ConfigureUtil.configureTarget(ConfigureUtil.java:160)
        at org.gradle.util.ConfigureUtil.configure(ConfigureUtil.java:106)
        at org.gradle.api.internal.project.DefaultProject.configure(DefaultProject.java:983)
        at org.gradle.api.internal.project.DefaultProject.configure(DefaultProject.java:988)
        at org.gradle.api.internal.project.DefaultProject.subprojects(DefaultProject.java:971)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at
        sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:93)
        at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
        at
        org.gradle.internal.metaobject.BeanDynamicObject$MetaClassAdapter.invokeMethod(BeanDyna
        micObject.java:382)
        at
        org.gradle.internal.metaobject.BeanDynamicObject.invokeMethod(BeanDynamicObject.java:17
        0)
        at
        org.gradle.internal.metaobject.CompositeDynamicObject.invokeMethod(CompositeDynamicObje
        ct.java:96)
        at
        org.gradle.internal.metaobject.MixInClosurePropertiesAsMethodsDynamicObject.invokeMetho
        d(MixInClosurePropertiesAsMethodsDynamicObject.java:30)
        at
        org.gradle.internal.metaobject.AbstractDynamicObject.invokeMethod(AbstractDynamicObject
        .java:163)
        at org.gradle.groovy.scripts.BasicScript.methodMissing(BasicScript.java:83)
        at sun.reflect.GeneratedMethodAccessor22.invoke(Unknown Source)
        at
        sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:93)
        at groovy.lang.MetaClassImpl.invokeMissingMethod(MetaClassImpl.java:941)
        at groovy.lang.MetaClassImpl.invokePropertyOrMissing(MetaClassImpl.java:1264)
        at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1217)
        at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1024)
        at
        org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.callCurrent(PogoMetaClassSite.ja
        va:69)
        at
        org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java
        :166)
        at build_d0sn1lellexnujernafbcwql1.run(D:\Download's
        FireFox\How-to-Build-a-Biomedical-Startup-master\How-to-Build-a-Biomedical-Startup-mast
        er\android\build.gradle:18)
        at
        org.gradle.groovy.scripts.internal.DefaultScriptRunnerFactory$ScriptRunnerImpl.run(Defa
        ultScriptRunnerFactory.java:90)
        at
        org.gradle.configuration.DefaultScriptPluginFactory$ScriptPluginImpl$2.run(DefaultScrip
        tPluginFactory.java:176)
        at
        org.gradle.configuration.ProjectScriptTarget.addConfiguration(ProjectScriptTarget.java:
        77)
        at
        org.gradle.configuration.DefaultScriptPluginFactory$ScriptPluginImpl.apply(DefaultScrip
        tPluginFactory.java:181)
        at
        org.gradle.configuration.project.BuildScriptProcessor.execute(BuildScriptProcessor.java
        :39)
        at
        org.gradle.configuration.project.BuildScriptProcessor.execute(BuildScriptProcessor.java
        :26)
        at
        org.gradle.configuration.project.ConfigureActionsProjectEvaluator.evaluate(ConfigureAct
        ionsProjectEvaluator.java:34)
        at
        org.gradle.configuration.project.LifecycleProjectEvaluator.doConfigure(LifecycleProject
        Evaluator.java:70)
        at
        org.gradle.configuration.project.LifecycleProjectEvaluator.access$000(LifecycleProjectE
        valuator.java:33)
        at
        org.gradle.configuration.project.LifecycleProjectEvaluator$1.execute(LifecycleProjectEv
        aluator.java:53)
        at
        org.gradle.configuration.project.LifecycleProjectEvaluator$1.execute(LifecycleProjectEv
        aluator.java:50)
        at org.gradle.internal.Transformers$4.transform(Transformers.java:169)
        at
        org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExe
        cutor.java:106)
        at
        org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExe
        cutor.java:61)
        at
        org.gradle.configuration.project.LifecycleProjectEvaluator.evaluate(LifecycleProjectEva
        luator.java:50)
        at org.gradle.api.internal.project.DefaultProject.evaluate(DefaultProject.java:628)
        at org.gradle.api.internal.project.DefaultProject.evaluate(DefaultProject.java:129)
        at
        org.gradle.execution.TaskPathProjectEvaluator.configure(TaskPathProjectEvaluator.java:3
        5)
        at
        org.gradle.execution.TaskPathProjectEvaluator.configureHierarchy(TaskPathProjectEvaluat
        or.java:60)
        at
        org.gradle.configuration.DefaultBuildConfigurer.configure(DefaultBuildConfigurer.java:3
        8)
        at
        org.gradle.initialization.DefaultGradleLauncher$1.execute(DefaultGradleLauncher.java:16
        1)
        at
        org.gradle.initialization.DefaultGradleLauncher$1.execute(DefaultGradleLauncher.java:15
        8)
        at org.gradle.internal.Transformers$4.transform(Transformers.java:169)
        at
        org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExe
        cutor.java:106)
        at
        org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExe
        cutor.java:56)
        at
        org.gradle.initialization.DefaultGradleLauncher.doBuildStages(DefaultGradleLauncher.jav
        a:158)
        at
        org.gradle.initialization.DefaultGradleLauncher.doBuild(DefaultGradleLauncher.java:119)
        at org.gradle.initialization.DefaultGradleLauncher.run(DefaultGradleLauncher.java:102)
        at org.gradle.launcher.exec.GradleBuildController.run(GradleBuildController.java:71)
        at
        org.gradle.tooling.internal.provider.ExecuteBuildActionRunner.run(ExecuteBuildActionRun
        ner.java:28)
        at
        org.gradle.launcher.exec.ChainingBuildActionRunner.run(ChainingBuildActionRunner.java:3
        5)
        at
        org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecu
        ter.java:41)
        at
        org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecu
        ter.java:26)
        at
        org.gradle.tooling.internal.provider.ContinuousBuildActionExecuter.execute(ContinuousBu
        ildActionExecuter.java:75)
        at
        org.gradle.tooling.internal.provider.ContinuousBuildActionExecuter.execute(ContinuousBu
        ildActionExecuter.java:49)
        at
        org.gradle.tooling.internal.provider.ServicesSetupBuildActionExecuter.execute(ServicesS
        etupBuildActionExecuter.java:44)
        at
        org.gradle.tooling.internal.provider.ServicesSetupBuildActionExecuter.execute(ServicesS
        etupBuildActionExecuter.java:29)
        at org.gradle.launcher.daemon.server.exec.ExecuteBuild.doBuild(ExecuteBuild.java:67)
        at
        org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:3
        6)
        at
        org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecu
        tion.java:120)
        at
        org.gradle.launcher.daemon.server.exec.WatchForDisconnection.execute(WatchForDisconnect
        ion.java:47)
        at
        org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecu
        tion.java:120)
        at
        org.gradle.launcher.daemon.server.exec.ResetDeprecationLogger.execute(ResetDeprecationL
        ogger.java:26)
        at
        org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecu
        tion.java:120)
        at
        org.gradle.launcher.daemon.server.exec.RequestStopIfSingleUsedDaemon.execute(RequestSto
        pIfSingleUsedDaemon.java:34)
        at
        org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecu
        tion.java:120)
        at
        org.gradle.launcher.daemon.server.exec.ForwardClientInput$2.call(ForwardClientInput.jav
        a:74)
        at
        org.gradle.launcher.daemon.server.exec.ForwardClientInput$2.call(ForwardClientInput.jav
        a:72)
        at org.gradle.util.Swapper.swap(Swapper.java:38)
        at
        org.gradle.launcher.daemon.server.exec.ForwardClientInput.execute(ForwardClientInput.ja
        va:72)
        at
        org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecu
        tion.java:120)
        at
        org.gradle.launcher.daemon.server.exec.LogAndCheckHealth.execute(LogAndCheckHealth.java
        :55)
        at
        org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecu
        tion.java:120)
        at org.gradle.launcher.daemon.server.exec.LogToClient.doBuild(LogToClient.java:60)
        at
        org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:3
        6)
        at
        org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecu
        tion.java:120)
        at
        org.gradle.launcher.daemon.server.exec.EstablishBuildEnvironment.doBuild(EstablishBuild
        Environment.java:72)
        at
        org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:3
        6)
        at
        org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecu
        tion.java:120)
        at
        org.gradle.launcher.daemon.server.exec.StartBuildOrRespondWithBusy$1.run(StartBuildOrRe
        spondWithBusy.java:50)
        at
        org.gradle.launcher.daemon.server.DaemonStateCoordinator$1.run(DaemonStateCoordinator.j
        ava:297)
        at
        org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(Executor
        Policy.java:54)
        at
        org.gradle.internal.concurrent.StoppableExecutorImpl$1.run(StoppableExecutorImpl.java:4
        0)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)

FAILURE: Build failed with an exception.

* Where:
Script 'D:\flutter\packages\flutter_tools\gradle\flutter.gradle' line: 27

* What went wrong:
A problem occurred evaluating script.
> Could not find method google() for arguments [] on repository container.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option
to get more log output.
  Command: D:\Download's
  FireFox\How-to-Build-a-Biomedical-Startup-master\How-to-Build-a-Biomedical-Startup-mas
  ter\android\gradlew.bat app:properties


Please review your Gradle project setup in the android/ folder
```

**Comment by BondarenkoStas** [comment]
@code-utk Please provide your flutter doctor -v output and build.gradle.
