### ISSUE TITLE
Textspan does not support MultiTapGestureRecognizer

### ISSUE THREAD

**Issue by chunhtai** [flutter/flutter#41923]
## Steps to Reproduce

```dart
import 'package:flutter/gestures.dart';
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key key, this.title}) : super(key: key);

  final String title;

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {

  @override
  Widget build(BuildContext context) {

    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: Center(
        child: Column(

          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            RichText(
              text: TextSpan(
                text: 'You have pushed the button this many times:',
                recognizer: MultiTapGestureRecognizer(),
              ),
            ),
          ],
        ),
      ), // This trailing comma makes auto-formatting nicer for build methods.
    );
  }
}
```
It will crash if the accessibility feature is turned on

## Logs

```
```

```
```

**Comment by dnfield** [comment]
The fundamentla problem is that gesture recognizers should support setting up semantics configuration for you, rather than needing to switch over all the known types of recognizers to set up the object in render paragraph.  See also https://github.com/flutter/flutter/issues/40480#issuecomment-577501713

**Comment by goderbauer** [comment]
This is tagged accessibility because using anything but a few approved gesture detectors throws when we try to generate the semantics node for the text span.

**Comment by markusaksli-nc** [comment]
Reproducible on the latest master `1.22.0-2.0.pre.93`.
<details>
 <summary>Minimal reproducible code sample</summary>

```dart
import 'package:flutter/gestures.dart';
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      theme: ThemeData.dark(),
      title: 'Sample',
      home: Scaffold(
        appBar: AppBar(
          title: Text('Sample'),
        ),
        body: Center(
          child: RichText(
            text: TextSpan(
              text: 'You have pushed the button this many times:',
              recognizer: MultiTapGestureRecognizer(),
            ),
          ),
        ),
      ),
    );
  }
}
```
</details>
<details>
 <summary>flutter doctor -v</summary>

```
[√] Flutter (Channel master, 1.22.0-2.0.pre.93, on Microsoft Windows [Version 10.0.19041.450], locale en-US)
    • Flutter version 1.22.0-2.0.pre.93 at C:\Development\flutter_master
    • Framework revision f35a8b7470 (4 hours ago), 2020-08-26 21:33:03 -0700
    • Engine revision 388193a67b
    • Dart version 2.10.0 (build 2.10.0-62.0.dev)

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
    • Android SDK at C:\Users\marku\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.1
    • Java binary at: C:\Users\marku\AppData\Local\JetBrains\Toolbox\apps\AndroidStudio\ch-0\193.6626763\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.6.5)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.6.30320.27
    • Windows 10 SDK version 10.0.18362.0

[√] Android Studio (version 4.0)
    • Android Studio at C:\Users\marku\AppData\Local\JetBrains\Toolbox\apps\AndroidStudio\ch-0\193.6626763
    • Flutter plugin version 47.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] Connected device (4 available)
    • sdk gphone x86 arm (mobile) • emulator-5554 • android-x86    • Android 11 (API 30) (emulator)
    • Windows (desktop)           • windows       • windows-x64    • Microsoft Windows [Version 10.0.19041.450]
    • Web Server (web)            • web-server    • web-javascript • Flutter Tools
    • Chrome (web)                • chrome        • web-javascript • Google Chrome 84.0.4147.135

• No issues found!
```
</details>
<details>
 <summary>Logs</summary>

```
════════ Exception caught by scheduler library ═════════════════════════════════════════════════════
The following assertion was thrown during a scheduler callback:
MultiTapGestureRecognizer is not supported.
'package:flutter/src/rendering/paragraph.dart':
Failed assertion: line 939 pos 20: 'false'


Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=BUG.md

When the exception was thrown, this was the stack: 
#2      RenderParagraph.assembleSemanticsNode (package:flutter/src/rendering/paragraph.dart:939:20)
#3      _SwitchableSemanticsFragment.compileChildren.<anonymous closure> (package:flutter/src/rendering/object.dart:3723:13)
#4      _SyncIterator.moveNext (dart:core-patch/core_patch.dart:165:25)
#5      ExpandIterator.moveNext (dart:_internal/iterable.dart:481:32)
#6      new List.from (dart:core-patch/array_patch.dart:50:19)
...
════════════════════════════════════════════════════════════════════════════════════════════════════
```
</details>

**Comment by darshankawar** [comment]
Replicable on latest versions. 

<details>
<summary> console log error </summary>

```

======== Exception caught by scheduler library =====================================================
The following assertion was thrown during a scheduler callback:
MultiTapGestureRecognizer is not supported.
'package:flutter/src/rendering/paragraph.dart':
Failed assertion: line 1147 pos 20: 'false'


Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=2_bug.md

When the exception was thrown, this was the stack: 
#2      RenderParagraph.assembleSemanticsNode (package:flutter/src/rendering/paragraph.dart:1147:20)
#3      _SwitchableSemanticsFragment.compileChildren (package:flutter/src/rendering/object.dart:4243:13)
#4      _SwitchableSemanticsFragment.compileChildren (package:flutter/src/rendering/object.dart:4235:16)
#5      _SwitchableSemanticsFragment.compileChildren (package:flutter/src/rendering/object.dart:4235:16)
#6      _SwitchableSemanticsFragment.compileChildren (package:flutter/src/rendering/object.dart:4188:18)
#7      _SwitchableSemanticsFragment.compileChildren (package:flutter/src/rendering/object.dart:4188:18)
#8      _SwitchableSemanticsFragment.compileChildren (package:flutter/src/rendering/object.dart:4188:18)
#9      _SwitchableSemanticsFragment.compileChildren (package:flutter/src/rendering/object.dart:4188:18)
#10     _SwitchableSemanticsFragment.compileChildren (package:flutter/src/rendering/object.dart:4235:16)
#11     _RootSemanticsFragment.compileChildren (package:flutter/src/rendering/object.dart:4113:16)
#12     RenderObject._updateSemantics (package:flutter/src/rendering/object.dart:3159:25)
#13     PipelineOwner.flushSemantics (package:flutter/src/rendering/object.dart:1221:16)
#14     RendererBinding.drawFrame (package:flutter/src/rendering/binding.dart:518:21)
#15     WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:884:13)
#16     RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:378:5)
#17     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1175:15)
#18     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1104:9)
#19     SchedulerBinding.scheduleWarmUpFrame.<anonymous closure> (package:flutter/src/scheduler/binding.dart:881:7)
(elided 6 frames from class _AssertionError, class _RawReceivePortImpl, class _Timer, and dart:async-patch)
====================================================================================================
fopen failed for data file: errno = 2 (No such file or directory)
Errors found! Invalidating cache...

======== Exception caught by Flutter framework =====================================================
The following StateError was thrown while executing callbacks for FrameTiming:
Bad state: Future already completed

When the exception was thrown, this was the stack: 
#1      WidgetsBinding.drawFrame.<anonymous closure> (package:flutter/src/widgets/binding.dart:872:30)
#2      SchedulerBinding._executeTimingsCallbacks (package:flutter/src/scheduler/binding.dart:300:19)
#3      _invoke1 (dart:ui/hooks.dart:167:13)
#4      PlatformDispatcher._reportTimings (dart:ui/platform_dispatcher.dart:510:5)
#5      _reportTimings (dart:ui/hooks.dart:110:31)
(elided one frame from dart:async)
The TimingsCallback that gets executed was: Closure: (List<FrameTiming>) => void
====================================================================================================

```

</details>

<details>
<summary> stable, master flutter doctor -v </summary>

```
[✓] Flutter (Channel stable, 3.3.7, on macOS 12.2.1 21D62 darwin-x64, locale
    en-GB)
    • Flutter version 3.3.7 on channel stable at
      /Users/dhs/documents/fluttersdk/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision e99c9c7cd9 (2 days ago), 2022-11-01 16:59:00 -0700
    • Engine revision 857bd6b74c
    • Dart version 2.18.4
    • DevTools version 2.15.0

[!] Xcode - develop for iOS and macOS (Xcode 12.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    ! Flutter recommends a minimum Xcode version of 13.
      Download the latest version or update via the Mac App Store.
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] VS Code (version 1.62.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.21.0

[✓] Connected device (5 available)
    • SM G975F (mobile)       • RZ8M802WY0X • android-arm64   • Android 11 (API 30)
    • Darshan's iphone (mobile)  • 21150b119064aecc249dfcfe05e259197461ce23 •
      ios            • iOS 14.4.1 18D61
    • iPhone 12 Pro Max (mobile) • A5473606-0213-4FD8-BA16-553433949729     •
      ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-3 (simulator)
    • macOS (desktop)            • macos                                    •
      darwin-x64     • Mac OS X 10.15.4 19E2269 darwin-x64
    • Chrome (web)               • chrome                                   •
      web-javascript • Google Chrome 98.0.4758.80

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.

[!] Flutter (Channel master, 3.5.0-12.0.pre.105, on macOS 12.2.1 21D62
    darwin-x64, locale en-GB)
    • Flutter version 3.5.0-12.0.pre.105 on channel master at
      /Users/dhs/documents/fluttersdk/flutter
    ! Warning: `flutter` on your path resolves to
      /Users/dhs/Documents/Fluttersdk/flutter/bin/flutter, which is not inside
      your current Flutter SDK checkout at
      /Users/dhs/documents/fluttersdk/flutter. Consider adding
      /Users/dhs/documents/fluttersdk/flutter/bin to the front of your path.
    ! Warning: `dart` on your path resolves to
      /Users/dhs/Documents/Fluttersdk/flutter/bin/dart, which is not inside your
      current Flutter SDK checkout at /Users/dhs/documents/fluttersdk/flutter.
      Consider adding /Users/dhs/documents/fluttersdk/flutter/bin to the front
      of your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 44b6cd2ec7 (2 hours ago), 2022-11-03 23:02:22 -0400
    • Engine revision fb7cde6970
    • Dart version 2.19.0 (build 2.19.0-370.0.dev)
    • DevTools version 2.19.0
    • If those were intentional, you can disregard the above warnings; however
      it is recommended to use "git" directly to perform update checks and
      upgrades.
    
[!] Xcode - develop for iOS and macOS (Xcode 12.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    ! Flutter recommends a minimum Xcode version of 13.
      Download the latest version or update via the Mac App Store.
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] VS Code (version 1.62.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.21.0

[✓] Connected device (5 available)
    • SM G975F (mobile)       • RZ8M802WY0X • android-arm64   • Android 11 (API 30)
    • Darshan's iphone (mobile)  • 21150b119064aecc249dfcfe05e259197461ce23 •
      ios            • iOS 14.4.1 18D61
    • iPhone 12 Pro Max (mobile) • A5473606-0213-4FD8-BA16-553433949729     •
      ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-3 (simulator)
    • macOS (desktop)            • macos                                    •
      darwin-x64     • Mac OS X 10.15.4 19E2269 darwin-x64
    • Chrome (web)               • chrome                                   •
      web-javascript • Google Chrome 98.0.4758.80

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.



```

</details>
