### ISSUE TITLE
Unable to build, `xcrun xcodebuild -showBuildSettings` times out

### ISSUE THREAD

**Issue by knarfamlap** [flutter/flutter#41956]
I recently updated to the latest version of flutter and it is unable to run.  
I get the same result when I attempt to run in an IOS simulator and in a physical iPhone. 

Although when creating a new flutter project using:

```bash
flutter create foo
```

and later run it with 

```bash
flutter run
```

 it successfully builds. 

## command

flutter run

## exception
```
ProcessException: ProcessException: Process timed out:

  Command: /usr/bin/env xcrun xcodebuild -configuration Debug -quiet -workspace Runner.xcworkspace -scheme Runner BUILD_DIR=/Users/frankpalma/Desktop/my_app/build/ios -sdk iphonesimulator -arch x86_64 SCRIPT_OUTPUT_STREAM_FILE=/var/folders/wz/97fqg1dd0w1dbl41cdrw87d00000gn/T/flutter_build_log_pipe.rDSA8Z/pipe_to_stdout FLUTTER_SUPPRESS_ANALYTICS=true COMPILER_INDEX_STORE_ENABLE=NO -showBuildSettings
```
```
#0      RunResult.throwException (package:flutter_tools/src/base/process.dart:141:5)
#1      _DefaultProcessUtils.run (package:flutter_tools/src/base/process.dart:346:19)
<asynchronous suspension>
#2      buildXcodeProject (package:flutter_tools/src/ios/mac.dart:506:66)
#3      _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:71:64)
#4      _rootRunUnary (dart:async/zone.dart:1132:38)
#5      _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#6      _FutureListener.handleValue (dart:async/future_impl.dart:137:18)
#7      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:678:45)
#8      Future._propagateToListeners (dart:async/future_impl.dart:707:32)
#9      Future._completeWithValue (dart:async/future_impl.dart:522:5)
#10     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:30:15)
#11     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:288:13)
#12     _DefaultProcessUtils.run (package:flutter_tools/src/base/process.dart)
#13     _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:71:64)
#14     _rootRunUnary (dart:async/zone.dart:1132:38)
#15     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#16     _FutureListener.handleValue (dart:async/future_impl.dart:137:18)
#17     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:678:45)
#18     Future._propagateToListeners (dart:async/future_impl.dart:707:32)
#19     Future._completeWithValue (dart:async/future_impl.dart:522:5)
#20     Future.wait.<anonymous closure> (dart:async/future.dart:400:22)
#21     _rootRunUnary (dart:async/zone.dart:1132:38)
#22     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#23     _FutureListener.handleValue (dart:async/future_impl.dart:137:18)
#24     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:678:45)
#25     Future._propagateToListeners (dart:async/future_impl.dart:707:32)
#26     Future._completeWithValue (dart:async/future_impl.dart:522:5)
#27     Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:552:7)
#28     _rootRun (dart:async/zone.dart:1124:13)
#29     _CustomZone.run (dart:async/zone.dart:1021:19)
#30     _CustomZone.runGuarded (dart:async/zone.dart:923:7)
#31     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:963:23)
#32     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#33     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#34     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:116:13)
#35     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:173:5)
```

## flutter doctor

```
[32m[✓][39m Flutter (Channel master, v1.10.9-pre.22, on Mac OS X 10.14.6 18G87, locale en-US)
    [32m•[39m Flutter version 1.10.9-pre.22 at /Users/frankpalma/flutter
    [32m•[39m Framework revision 6048b62e21 (56 minutes ago), 2019-10-03 18:56:25 -0700
    [32m•[39m Engine revision 62e58c5d9f
    [32m•[39m Dart version 2.6.0 (build 2.6.0-dev.0.0 7376167b2a)

[31m[✗][39m Android toolchain - develop for Android devices
    [31m✗[39m Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/setup/#android-setup for detailed instructions).
      If the Android SDK has been installed to a custom location, set ANDROID_HOME to that location.
      You may also want to add it to your PATH environment variable.


[32m[✓][39m Xcode - develop for iOS and macOS (Xcode 10.3)
    [32m•[39m Xcode at /Applications/Xcode.app/Contents/Developer
    [32m•[39m Xcode 10.3, Build version 10G8
    [32m•[39m CocoaPods version 1.7.5

[33m[!][39m Android Studio (not installed)
    [32m•[39m Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/setup/#android-setup for detailed instructions).

[32m[✓][39m VS Code (version 1.38.1)
    [32m•[39m VS Code at /Applications/Visual Studio Code.app/Contents
    [32m•[39m Flutter extension version 3.5.1

[32m[✓][39m Connected device (1 available)
    [32m•[39m iPhone Xs Max • 9ABBCE7C-640B-414F-988F-4123BDA25A9B • ios •
      com.apple.CoreSimulator.SimRuntime.iOS-12-2 (simulator)

[33m![39m Doctor found issues in 2 categories.
```

**Comment by jmagman** [comment]
Hm, `flutter doctor` shows the version could be parsed from xcodebuild, and that timeout seems to be just getting build settings (not actually trying to build).
Are you able to open /Users/frankpalma/Desktop/my_app/ios/Runner.xcworkspace in Xcode and successfully build there?

**Comment by knarfamlap** [comment]
I'm able to successfully build in Xcode but it doesn't build with the most up to date files on the project. 

After successfully building in XCode, I decided to go ahead and run

```bash
flutter clean
``` 

to see if any changes occur. I reran the application using

```bash
flutter run
``` 

and it successfully builds but now every time I try to hot reload, flutter loses connection with my device. I can also confirm that flutter loses connection when using a simulator.

**Comment by jmagman** [comment]
> every time I try to hot reload, flutter loses connection with my device. I can also confirm that flutter loses connection when using a simulator.

That sounds like another issue, could you file a new issue if you're still seeing this?

I'm not sure what else Flutter tooling could do about this timing out--it's totally dependent on getting xcodebuild build settings.
