### ISSUE TITLE
Cannot copy file to 'linux/flutter/ephemeral/libflutter_linux_glfw.so'   Failed to unpack desktop artifacts.                                     

### ISSUE THREAD

**Issue by lucaszanella** [flutter/flutter#41971]
Im running flutter master and after building the SDK and everything, I try to compile my project with

`flutter --local-engine-src ../engine/src --local-engine=host_debug_unopt run `

and I get

```
user@orwell:~/orwell/orwell_flutter$ ./flutter_run.sh 
Launching lib/main.dart on Linux in debug mode...
#0      _File.throwIfError (dart:io/file_impl.dart:643:7)               
#1      _File.copySync (dart:io/file_impl.dart:348:5)                   
#2      ForwardingFile.copySync (package:file/src/forwarding/forwarding_file.dart:30:50)
#3      ArtifactUnpacker._copyArtifactFiles (package:flutter_tools/src/commands/unpack.dart:230:16)
#4      ArtifactUnpacker.copyLocalBuildArtifacts (package:flutter_tools/src/commands/unpack.dart:189:10)
#5      UnpackCommand.runCommand (package:flutter_tools/src/commands/unpack.dart:103:40)
<asynchronous suspension>                                               
#6      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:553:18)
<asynchronous suspension>                                               
#7      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:457:33)
<asynchronous suspension>                                               
#8      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:157:29)
<asynchronous suspension>                                               
#9      _rootRun (dart:async/zone.dart:1124:13)                         
#10     _CustomZone.run (dart:async/zone.dart:1021:19)                  
#11     _runZoned (dart:async/zone.dart:1516:10)                        
#12     runZoned (dart:async/zone.dart:1463:12)                         
#13     AppContext.run (package:flutter_tools/src/base/context.dart:156:18)
<asynchronous suspension>                                               
#14     FlutterCommand.run (package:flutter_tools/src/runner/flutter_command.dart:446:20)
#15     CommandRunner.runCommand (package:args/command_runner.dart:197:27)
<asynchronous suspension>                                               
#16     FlutterCommandRunner.runCommand.<anonymous closure>             
(package:flutter_tools/src/runner/flutter_command_runner.dart:416:21)
<asynchronous suspension>                                               
#17     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:157:29)
<asynchronous suspension>                                               
#18     _rootRun (dart:async/zone.dart:1124:13)                         
#19     _CustomZone.run (dart:async/zone.dart:1021:19)                  
#20     _runZoned (dart:async/zone.dart:1516:10)                        
#21     runZoned (dart:async/zone.dart:1463:12)                         
#22     AppContext.run (package:flutter_tools/src/base/context.dart:156:18)
<asynchronous suspension>                                               
#23     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:367:19)
<asynchronous suspension>                                               
#24     CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:112:25)
#25     new Future.sync (dart:async/future.dart:224:31)                 
#26     CommandRunner.run (package:args/command_runner.dart:112:14)     
#27     FlutterCommandRunner.run (package:flutter_tools/src/runner/flutter_command_runner.dart:251:18)
#28     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:63:22)
<asynchronous suspension>                                               
#29     _rootRun (dart:async/zone.dart:1124:13)                         
#30     _CustomZone.run (dart:async/zone.dart:1021:19)                  
#31     _runZoned (dart:async/zone.dart:1516:10)                        
#32     runZoned (dart:async/zone.dart:1500:12)                         
#33     run.<anonymous closure> (package:flutter_tools/runner.dart:61:18)
<asynchronous suspension>                                               
#34     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:157:29)
<asynchronous suspension>                                               
#35     _rootRun (dart:async/zone.dart:1124:13)                         
#36     _CustomZone.run (dart:async/zone.dart:1021:19)                  
#37     _runZoned (dart:async/zone.dart:1516:10)                        
#38     runZoned (dart:async/zone.dart:1463:12)                         
#39     AppContext.run (package:flutter_tools/src/base/context.dart:156:18)
<asynchronous suspension>                                               
#40     runInContext (package:flutter_tools/src/context_runner.dart:63:24)
<asynchronous suspension>                                               
#41     run (package:flutter_tools/runner.dart:50:10)                   
#42     main (package:flutter_tools/executable.dart:65:9)               
<asynchronous suspension>                                               
#43     main (file:///home/user/development/flutter/packages/flutter_tools/bin/flutter_tools.dart:8:3)
#44     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:303:32)
#45     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:12)
                                                                        
Cannot copy file to 'linux/flutter/ephemeral/libflutter_linux_glfw.so'  
Failed to unpack desktop artifacts.                                     
make: *** [sync] Error 1                                                
Building Linux application...                                           
Build process failed
```

**Comment by lucaszanella** [comment]
`flutter run` works, but `flutter --local-engine-src ../engine/src --local-engine=host_debug_unopt run`  not

**Comment by lucaszanella** [comment]
turns out the local engine folder was owned by root. I thought it was only rading from there but apparently it writes too
