### ISSUE TITLE
Generating build_script fails in Flutter 1.10.7 (channel Dev)

### ISSUE THREAD

**Issue by GregorySech** [flutter/flutter#42003]
## Steps to Reproduce

1. Create a new application with the default template `flutter create example`
2. Add functional_widget and functional_widget_annotation to pubspec.yaml
```
dependencies:
  flutter:
    sdk: flutter
  functional_widget_annotation: ^0.5.1

builders:
  functional_widget: ^0.7.1
```
3. Run the application. It will fail with: `Error generating build_script snapshot: Could not find a file named "pubspec.yaml" in "/Users/gregorysech/.pub-cache/hosted/pub.dartlang.org/functional_widget-0.7.1"`. The same happens with `flutter generate`

## Logs

I've not added all the output from `flutter run --verbose`, only the exception.

```
[ +288 ms] generating build script... (completed in 11.9s)
[   +3 ms] "flutter run" took 16,008ms.
Error generating build_script snapshot: Could not find a file named "pubspec.yaml" in "/Users/gregorysech/.pub-cache/hosted/pub.dartlang.org/functional_widget-0.7.1".



#0      throwToolExit (package:flutter_tools/src/base/common.dart:28:3)
#1      BuildRunner.generateBuildScript (package:flutter_tools/src/build_runner/build_runner.dart:119:9)
<asynchronous suspension>
#2      BuildRunner.daemon (package:flutter_tools/src/build_runner/build_runner.dart:146:11)
<asynchronous suspension>
#3      CodeGeneratingResidentCompiler.create (package:flutter_tools/src/codegen.dart:188:61)
<asynchronous suspension>
#4      FlutterDevice.create (package:flutter_tools/src/resident_runner.dart:68:56)
<asynchronous suspension>
#5      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:405:29)
<asynchronous suspension>
#6      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:553:18)
#7      _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:71:64)
#8      _rootRunUnary (dart:async/zone.dart:1132:38)
#9      _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#10     _FutureListener.handleValue (dart:async/future_impl.dart:137:18)
#11     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:678:45)
#12     Future._propagateToListeners (dart:async/future_impl.dart:707:32)
#13     Future._completeWithValue (dart:async/future_impl.dart:522:5)
#14     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:30:15)
#15     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:288:13)
#16     RunCommand.usageValues (package:flutter_tools/src/commands/run.dart)
#17     _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:71:64)
#18     _rootRunUnary (dart:async/zone.dart:1132:38)
#19     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#20     _FutureListener.handleValue (dart:async/future_impl.dart:137:18)
#21     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:678:45)
#22     Future._propagateToListeners (dart:async/future_impl.dart:707:32)
#23     Future._completeWithValue (dart:async/future_impl.dart:522:5)
#24     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:30:15)
#25     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:288:13)
#26     IosProject.isSwift (package:flutter_tools/src/project.dart)
#27     _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:71:64)
#28     _rootRunUnary (dart:async/zone.dart:1132:38)
#29     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#30     _FutureListener.handleValue (dart:async/future_impl.dart:137:18)
#31     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:678:45)
#32     Future._propagateToListeners (dart:async/future_impl.dart:707:32)
#33     Future._completeWithValue (dart:async/future_impl.dart:522:5)
#34     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:30:15)
#35     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:288:13)
#36     IosProject.buildSettings (package:flutter_tools/src/project.dart)
#37     _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:71:64)
#38     _rootRunUnary (dart:async/zone.dart:1132:38)
#39     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#40     _FutureListener.handleValue (dart:async/future_impl.dart:137:18)
#41     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:678:45)
#42     Future._propagateToListeners (dart:async/future_impl.dart:707:32)
#43     Future._completeWithValue (dart:async/future_impl.dart:522:5)
#44     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:30:15)
#45     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:288:13)
#46     XcodeProjectInterpreter.getBuildSettings (package:flutter_tools/src/ios/xcodeproj.dart)
#47     _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:71:64)
#48     _rootRunUnary (dart:async/zone.dart:1132:38)
#49     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#50     _FutureListener.handleValue (dart:async/future_impl.dart:137:18)
#51     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:678:45)
#52     Future._propagateToListeners (dart:async/future_impl.dart:707:32)
#53     Future._completeWithValue (dart:async/future_impl.dart:522:5)
#54     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:30:15)
#55     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:288:13)
#56     _DefaultProcessUtils.run (package:flutter_tools/src/base/process.dart)
#57     _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:71:64)
#58     _rootRunUnary (dart:async/zone.dart:1132:38)
#59     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#60     _FutureListener.handleValue (dart:async/future_impl.dart:137:18)
#61     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:678:45)
#62     Future._propagateToListeners (dart:async/future_impl.dart:707:32)
#63     Future._completeWithValue (dart:async/future_impl.dart:522:5)
#64     Future.wait.<anonymous closure> (dart:async/future.dart:400:22)
#65     _rootRunUnary (dart:async/zone.dart:1132:38)
#66     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#67     _FutureListener.handleValue (dart:async/future_impl.dart:137:18)
#68     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:678:45)
#69     Future._propagateToListeners (dart:async/future_impl.dart:707:32)
#70     Future._complete (dart:async/future_impl.dart:512:7)
#71     _BufferingStreamSubscription.asFuture.<anonymous closure> (dart:async/stream_impl.dart:204:14)
#72     _rootRun (dart:async/zone.dart:1120:38)
#73     _CustomZone.run (dart:async/zone.dart:1021:19)
#74     _CustomZone.runGuarded (dart:async/zone.dart:923:7)
#75     _BufferingStreamSubscription._sendDone.sendDone (dart:async/stream_impl.dart:389:13)
#76     _BufferingStreamSubscription._sendDone (dart:async/stream_impl.dart:399:15)
#77     _BufferingStreamSubscription._close (dart:async/stream_impl.dart:283:7)
#78     _SinkTransformerStreamSubscription._close (dart:async/stream_transformers.dart:96:11)
#79     _EventSinkWrapper.close (dart:async/stream_transformers.dart:23:11)
#80     _StringAdapterSink.close (dart:convert/string_conversion.dart:249:11)
#81     _Utf8ConversionSink.close (dart:convert/string_conversion.dart:300:20)
#82     _ConverterStreamEventSink.close (dart:convert/chunked_conversion.dart:80:18)
#83     _SinkTransformerStreamSubscription._handleDone (dart:async/stream_transformers.dart:141:24)
#84     _rootRun (dart:async/zone.dart:1120:38)
#85     _CustomZone.run (dart:async/zone.dart:1021:19)
#86     _CustomZone.runGuarded (dart:async/zone.dart:923:7)
#87     _BufferingStreamSubscription._sendDone.sendDone (dart:async/stream_impl.dart:389:13)
#88     _BufferingStreamSubscription._sendDone (dart:async/stream_impl.dart:399:15)
#89     _BufferingStreamSubscription._close (dart:async/stream_impl.dart:283:7)
#90     _SyncStreamControllerDispatch._sendDone (dart:async/stream_controller.dart:772:19)
#91     _StreamController._closeUnchecked (dart:async/stream_controller.dart:629:7)
#92     _StreamController.close (dart:async/stream_controller.dart:622:5)
#93     _Socket._onData (dart:io-patch/socket_patch.dart:1836:21)
#94     _rootRunUnary (dart:async/zone.dart:1136:13)
#95     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#96     _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
#97     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#98     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#99     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:764:19)
#100    _StreamController._add (dart:async/stream_controller.dart:640:7)
#101    _StreamController.add (dart:async/stream_controller.dart:586:5)
#102    new _RawSocket.<anonymous closure> (dart:io-patch/socket_patch.dart:1384:35)
#103    _NativeSocket.issueReadEvent.issue (dart:io-patch/socket_patch.dart:890:18)
#104    _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#105    _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#106    _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:116:13)
#107    _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:173:5)
```

```
Analyzing example...                                                    
No issues found! (ran in 3.4s)
```

In stable `flutter run` works as intended but in dev it does not.
```
[✓] Flutter (Channel dev, v1.10.7, on Mac OS X 10.14.6 18G87, locale en-GB)
    • Flutter version 1.10.7 at /Users/gregorysech/flutter
    • Framework revision e70236e36c (27 hours ago), 2019-10-02 09:32:30 -0700
    • Engine revision 9e6314d348
    • Dart version 2.6.0 (build 2.6.0-dev.0.0 1103600280)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/gregorysech/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 28.0.3
    • Java binary at: /Volumes/SD/IDEs/apps/AndroidStudio/ch-0/191.5791312/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 10.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.2.1, Build version 10E1001
    • CocoaPods version 1.7.5

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 3.5)
    • Android Studio at /Volumes/SD/IDEs/apps/AndroidStudio/ch-0/191.5791312/Android Studio.app/Contents
    • Flutter plugin version 39.0.3
    • Dart plugin version 191.8423
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] VS Code (version 1.38.1)
    • VS Code at /Users/gregorysech/Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.4.1

[✓] Connected device (3 available)
    • iPhone Xʀ       • AE87AF8A-D548-4345-BE9A-81D64DDF453A • ios            • com.apple.CoreSimulator.SimRuntime.iOS-12-2 (simulator)
    • Chrome          • chrome                               • web-javascript • Google Chrome 77.0.3865.90
    • Headless Server • headless-server                      • web-javascript • Flutter Tools

• No issues found!

```
It works on Stable
```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, v1.9.1+hotfix.4, on Mac OS X 10.14.6 18G87, locale en-GB)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 10.2.1)
[✓] Android Studio (version 3.5)
[✓] VS Code (version 1.38.1)
[✓] Connected device (1 available)

• No issues found!
Gregorys-MBP:example gregorysech$ flutter doctor -v
[✓] Flutter (Channel stable, v1.9.1+hotfix.4, on Mac OS X 10.14.6 18G87, locale en-GB)
    • Flutter version 1.9.1+hotfix.4 at /Users/gregorysech/flutter
    • Framework revision cc949a8e8b (6 days ago), 2019-09-27 15:04:59 -0700
    • Engine revision b863200c37
    • Dart version 2.5.0

 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/gregorysech/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 28.0.3
    • Java binary at: /Volumes/SD/IDEs/apps/AndroidStudio/ch-0/191.5791312/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 10.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.2.1, Build version 10E1001
    • CocoaPods version 1.7.5

[✓] Android Studio (version 3.5)
    • Android Studio at /Volumes/SD/IDEs/apps/AndroidStudio/ch-0/191.5791312/Android Studio.app/Contents
    • Flutter plugin version 39.0.3
    • Dart plugin version 191.8423
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] VS Code (version 1.38.1)
    • VS Code at /Users/gregorysech/Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.4.1

[✓] Connected device (1 available)
    • iPhone Xʀ • AE87AF8A-D548-4345-BE9A-81D64DDF453A • ios • com.apple.CoreSimulator.SimRuntime.iOS-12-2 (simulator)

• No issues found!

```
# Notes
I've already posted this issue on the package where I got confirmation that is was a tooling issue. https://github.com/rrousselGit/functional_widget/issues/55

**Comment by hmayer00** [comment]
For what it's worth, I fixed this in less-stable branches by going back to `build_runner` code generation, instead of the newer `builders` pubspec syntax. A pain but I needed a fix that hasn't hit stable yet.

**Comment by maks** [comment]
Yes and just to add my data point, I have it working on stable but the breakage has gotten all the way thru to beta channel (1.10.7). Also in case it helps when I try to use it on beta channel with `json_serializable` the error I get is:
```
Could not find a file named "pubspec.yaml" in "/home/maks/.pub-cache/hosted/pub.dartlang.org/built_value-6.8.2".
```

**Comment by hmayer00** [comment]
This is still the case in version `1.12.13+hotfix.3`. Am I missing something here? I feel like this should be affecting a lot of people, but maybe not that many had moved over from build_runner to the `builders` syntax.

**Comment by maks** [comment]
@hmayer00 I agree, for me the builder in pubspec functionality was what made it convienent enough tto start using code gen tooling in my Flutter apps, so I sorely miss it to, but in the end its more of a (very big) annoynace vs a showstopper. 
Main thing I'm concerned about is that this is very likely to hit the stable channel shortly and then it *will* affect alot more people since I suspect most work on stable not beta, dev or master.

**Comment by maks** [comment]
So now unfortunately the bug has made it all the way into stable :disappointed: 

Trying to use `builders` with a new builder package of my own (`string_res`) I now get:
```
generating build script...                                         27.5s
Error generating build_script snapshot: Could not find a file named "pubspec.yaml" in "/home/maks/.pub-cache/hosted/pub.dartlang.org/build_daemon-2.1.0".
``` 
which is a little surprising given I dont actually have `build_daemon` anywhere in my `pubpsec.lock`
This is on:
```
Flutter (Channel stable, v1.12.13+hotfix.5, on Linux, locale en_AU.UTF-8)
```

**Comment by maks** [comment]
So looking at the verbose outputs exception:
```
#0      throwToolExit (package:flutter_tools/src/base/common.dart:28:3)
#1      BuildRunner.generateBuildScript (package:flutter_tools/src/build_runner/build_runner.dart:119:9)
<asynchronous suspension>
#2      BuildRunner.daemon (package:flutter_tools/src/build_runner/build_runner.dart:145:11)
#3      CodeGeneratingResidentCompiler.create (package:flutter_tools/src/codegen.dart:202:61)
#4      FlutterDevice.create (package:flutter_tools/src/resident_runner.dart:97:56)
<asynchronous suspension>
#5      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:425:29)
<asynchronous suspension>
```

and then at https://github.com/flutter/flutter/blob/master/packages/flutter_tools/lib/src/build_runner/build_runner.dart#L119
the code thats producing the error is:
```
final ProcessResult generateResult = await processManager.run(<String>[
        sdkBinaryName('pub'), 'run', 'build_runner', 'generate-build-script',
      ], workingDirectory: syntheticPubspec.parent.path);
      if (generateResult.exitCode != 0) {
        throwToolExit('Error generating build_script snapshot: ${generateResult.stderr}');
      }
```
but looking at: https://github.com/flutter/flutter/blob/master/packages/flutter_tools/pubspec.yaml#L54
`build_daemon` is listed in the depenedencies under the comment `# Code generation dependencies` so I wonder if somethign is going wrong with how flutter_tools is fetching its deps, as `build_daemon` is, as the error reports, definitely *not* in my `.pub-cache`

**Comment by maks** [comment]
Sorry to keep barraging this issue but I hope this may help with pointing to the cause of this issue:
```
$ pub run build_runner generate-build-script
Could not find a file named "pubspec.yaml" in "/home/maks/.pub-cache/hosted/pub.dartlang.org/analyzer-0.36.4".
$ flutter pub run build_runner generate-build-script
/home/maks/work/.dart_tool/build/entrypoint/build.dart
   $ pub run build_runner generate-build-script
/home/maks/work/.dart_tool/build/entrypoint/build.dart
   $ flutter run --flavor dev
generating build script...                                         28.1s
Error generating build_script snapshot: Could not find a file named "pubspec.yaml" in
"/home/maks/.pub-cache/hosted/pub.dartlang.org/build_daemon-2.1.0".


 $ pub run build_runner generate-build-script
No .dart_tool/package_config.json file found, please run "pub get" first.

Starting with Dart 2.7 this file configures the resolution of package import URIs. Running "pub get" will generate this file.
 $ flutter pub get
Running "flutter pub get" in flutter-app...                    0.5s
 $ pub run build_runner generate-build-script
Could not find a file named "pubspec.yaml" in "/home/maks/.pub-cache/hosted/pub.dartlang.org/analyzer-0.36.4".
$ flutter pub run build_runner generate-build-script
/home/maks/work/.dart_tool/build/entrypoint/build.dart
$ pub run build_runner generate-build-script
/home/maks/work/.dart_tool/build/entrypoint/build.dart
$ flutter run --flavor dev
generating build script...                                         27.2s
Error generating build_script snapshot: Could not find a file named "pubspec.yaml" in
"/home/maks/.pub-cache/hosted/pub.dartlang.org/build_daemon-2.1.0".
```
ps. I edited path names above which contain name of app project Im working on for privacy reasons.

**Comment by iskarian** [comment]
Did a quick test replacing the suspect code
```dart
final ProcessResult generateResult = await processManager.run(<String>[
        sdkBinaryName('pub'), 'run', 'build_runner', 'generate-build-script',
      ], workingDirectory: syntheticPubspec.parent.path);
```
with
```dart
final ProcessResult generateResult = await processManager.run(<String>[
        'flutter', 'pub', 'run', 'build_runner', 'generate-build-script',
      ], workingDirectory: syntheticPubspec.parent.path);
```
and (after regenerating the flutter_tools binaries) it worked correctly. So it seems that the command does need to be be run in a flutter context, whether that is through calling the flutter command or using `pub.interactively`.

**Comment by iskarian** [comment]
This seems to be working for me as of 1d3fcfd, perhaps PR #50988 fixed it? Can someone else test?

**Comment by maks** [comment]
I just tested using: `Channel master, v1.15.4-pre.241, on Linux` and I'm afraid its still broken for me. @iskarian could you post a minimal repo that you are using to test that its working for you?

**Comment by maks** [comment]
@iskarian I just tried using your code from Jan 26 comment, editing `packages/flutter_tools/lib/src/build_runner/build_runner.dart` in an install of stable channel and then running flutter_tools "from src" using:
`~/apps/flutter/bin/cache/dart-sdk/bin/dart ~/apps/flutter/packages/flutter_tools/bin/flutter_tools.dart  run`

and while its does stop the error from Flutter during the `generating build script...`  it also doesn't actually seem to actually run my example apps builder package (`json_serializable`) either as when I make a change in a dart model file, its not regenerating the part file.

**Comment by iskarian** [comment]
@maks It seems you *must* have a `build.yaml` that specifies your runner *as well as an options dict*, even if you do not specify any options. Like so:

```yaml build.yaml
targets:
  $default:
    builders:
      json_serializable:
        options:
```

I have not tested this with code generators other than `json_serializable`, though.

**Comment by EmmanuelAmet** [comment]
I was facing this same issue and what I did to resolve it was, I re-run flutter pub get and this error was gone.

**Comment by jonahwilliams** [comment]
Superseded by https://github.com/flutter/flutter/issues/61508
