### ISSUE TITLE
[web] Unable to run flutter web with a hostname

### ISSUE THREAD

**Issue by mdebbar** [flutter/flutter#42164]
On a corp-provided macbook, I'm trying to run the flutter_gallery:
```
flutter run -d headless-server --web-hostname=`hostname` --web-port=8080 --local-engine=host_debug_unopt --profile -v
```

It fails and prints the following:
```
Failed to build application for the web.

#0      throwToolExit (package:flutter_tools/src/base/common.dart:28:3)
#1      ResidentWebRunner.run (package:flutter_tools/src/build_runner/resident_web_runner.dart:198:7)
<asynchronous suspension>
#2      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:481:37)
<asynchronous suspension>
#3      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:557:18)
<asynchronous suspension>
#4      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:457:33)
<asynchronous suspension>
#5      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:157:29)
<asynchronous suspension>
#6      _rootRun (dart:async/zone.dart:1124:13)
#7      _CustomZone.run (dart:async/zone.dart:1021:19)
#8      _runZoned (dart:async/zone.dart:1516:10)
#9      runZoned (dart:async/zone.dart:1463:12)
#10     AppContext.run (package:flutter_tools/src/base/context.dart:156:18)
<asynchronous suspension>
#11     FlutterCommand.run (package:flutter_tools/src/runner/flutter_command.dart:446:20)
#12     CommandRunner.runCommand (package:args/command_runner.dart:197:27)
<asynchronous suspension>
#13     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:416:21)
<asynchronous suspension>
#14     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:157:29)
<asynchronous suspension>
#15     _rootRun (dart:async/zone.dart:1124:13)
#16     _CustomZone.run (dart:async/zone.dart:1021:19)
#17     _runZoned (dart:async/zone.dart:1516:10)
#18     runZoned (dart:async/zone.dart:1463:12)
#19     AppContext.run (package:flutter_tools/src/base/context.dart:156:18)
<asynchronous suspension>
#20     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:367:19)
<asynchronous suspension>
#21     CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:112:25)
#22     new Future.sync (dart:async/future.dart:224:31)
#23     CommandRunner.run (package:args/command_runner.dart:112:14)
#24     FlutterCommandRunner.run (package:flutter_tools/src/runner/flutter_command_runner.dart:251:18)
#25     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:63:22)
<asynchronous suspension>
#26     _rootRun (dart:async/zone.dart:1124:13)
#27     _CustomZone.run (dart:async/zone.dart:1021:19)
#28     _runZoned (dart:async/zone.dart:1516:10)
#29     runZoned (dart:async/zone.dart:1500:12)
#30     run.<anonymous closure> (package:flutter_tools/runner.dart:61:18)
<asynchronous suspension>
#31     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:157:29)
<asynchronous suspension>
#32     _rootRun (dart:async/zone.dart:1124:13)
#33     _CustomZone.run (dart:async/zone.dart:1021:19)
#34     _runZoned (dart:async/zone.dart:1516:10)
#35     runZoned (dart:async/zone.dart:1463:12)
#36     AppContext.run (package:flutter_tools/src/base/context.dart:156:18)
<asynchronous suspension>
#37     runInContext (package:flutter_tools/src/context_runner.dart:63:24)
<asynchronous suspension>
#38     run (package:flutter_tools/runner.dart:50:10)
#39     main (package:flutter_tools/executable.dart:65:9)
<asynchronous suspension>
#40     main (file:///Users/mdebbar/github/flutter/packages/flutter_tools/bin/flutter_tools.dart:8:3)
#41     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:303:32)
#42     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:12)
```

**Comment by elibwhittle** [comment]
I have this same problem. I cannot run `flutter run --release -d chrome -v`. Running `flutter run -d chrome` builds but I just see a blank screen. Help!

**Comment by jonahwilliams** [comment]
@elibwhittle  that is a completely unrelated issue. Please file a new bug with all of the requisite information, including logs and browser console

**Comment by mdebbar** [comment]
@jonahwilliams a clarification that I forgot to mention when I filed the issue: when I set the hostname to an IP address, it works fine. It only fails when I set it to a string.

**Comment by msndvlpr** [comment]
@mdebbar  I used your command and it worked greatly on IP address, what I was urgently searching for. Thank you

**Comment by DenisBarzanov** [comment]
@mdebbar This command saved my project deadline. Had I not seen it, I would have been stuck with the `webdev` command not wanting to work. Thanks
