### ISSUE TITLE
CFRunLoopSource in MessageLoopDarwin not being collected.

### ISSUE THREAD

**Issue by chinmaygarde** [flutter/flutter#42175]
A source added to the CFRunLoop is indicated as being leaked by leak sanitizer. The message loop itself is being released though. Possible false positive.

```
Indirect leak of 32 byte(s) in 1 object(s) allocated from:
    #0 0x11a772393 in wrap_malloc (libclang_rt.asan_osx_dynamic.dylib:x86_64+0x59393)
    #1 0x7fff7c8f3b10 in _Block_object_assign (libsystem_blocks.dylib:x86_64+0xb10)
    #2 0x7fff7c8f39f2 in _Block_copy (libsystem_blocks.dylib:x86_64+0x9f2)
    #3 0x7fff7c8f3a94 in _Block_object_assign (libsystem_blocks.dylib:x86_64+0xa94)
    #4 0x7fff7c8f39f2 in _Block_copy (libsystem_blocks.dylib:x86_64+0x9f2)
    #5 0x7fff7c85c5cf in _dispatch_Block_copy (libdispatch.dylib:x86_64+0x25cf)
    #6 0x7fff7c86e20d in _dispatch_source_set_handler (libdispatch.dylib:x86_64+0x1420d)
    #7 0x11a771909 in wrap_dispatch_source_set_event_handler (libclang_rt.asan_osx_dynamic.dylib:x86_64+0x58909)
    #8 0x7fff50931b7c in __CFRunLoopFindMode (CoreFoundation:x86_64h+0x38b7c)
    #9 0x7fff5093188b in __CFRunLoopCreate (CoreFoundation:x86_64h+0x3888b)
    #10 0x7fff509315e6 in _CFRunLoopGet0 (CoreFoundation:x86_64h+0x385e6)
    #11 0x10e303330 in fml::MessageLoopDarwin::MessageLoopDarwin() message_loop_darwin.mm:17
    #12 0x10e303e92 in fml::MessageLoopDarwin::MessageLoopDarwin() message_loop_darwin.mm:17
    #13 0x10e2b9459 in fml::RefPtr<fml::MessageLoopDarwin> fml::internal::MakeRefCountedHelper<fml::MessageLoopDarwin>::MakeRefCounted<>() ref_ptr_internal.h:31
    #14 0x10e2b6d11 in fml::RefPtr<fml::MessageLoopDarwin> fml::MakeRefCounted<fml::MessageLoopDarwin>() ref_ptr.h:231
    #15 0x10e2b6c61 in fml::MessageLoopImpl::Create() message_loop_impl.cc:30
    #16 0x10e2b5226 in fml::MessageLoop::MessageLoop() message_loop.cc:40
    #17 0x10e2b5032 in fml::MessageLoop::MessageLoop() message_loop.cc:41
    #18 0x10e2b4f76 in fml::MessageLoop::EnsureInitializedForCurrentThread() message_loop.cc:32
    #19 0x111ece7a3 in flutter::testing::ThreadTest::SetUp() thread_test.cc:14
    #20 0x10cb23365 in flutter::testing::EmbedderTest::SetUp() embedder_test.cc:30
    #21 0x1121d7ed2 in void testing::internal::HandleSehExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) gtest.cc:2447
    #22 0x1121837e9 in void testing::internal::HandleExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) gtest.cc:2502
    #23 0x1121831db in testing::Test::Run() gtest.cc:2517
    #24 0x1121854c9 in testing::TestInfo::Run() gtest.cc:2698
    #25 0x112187ab9 in testing::TestSuite::Run() gtest.cc:2828
    #26 0x1121a0861 in testing::internal::UnitTestImpl::RunAllTests() gtest.cc:5285
    #27 0x1121e4fc2 in bool testing::internal::HandleSehExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) gtest.cc:2447
    #28 0x11219fb40 in bool testing::internal::HandleExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) gtest.cc:2502
    #29 0x11219f68c in testing::UnitTest::Run() gtest.cc:4873

```

**Comment by pedromassangocode** [comment]
Wondering if this is still happening.
