### ISSUE TITLE
Font families on are leaked when launching the shell.

### ISSUE THREAD

**Issue by chinmaygarde** [flutter/flutter#42179]
Caught by leak sanitizer in the `shell_unittests` harness.

```
Direct leak of 8192 byte(s) in 8 object(s) allocated from:
    #0 0x1188a4393 in wrap_malloc (libclang_rt.asan_osx_dynamic.dylib:x86_64+0x59393)
    #1 0x7fff4efd4616 in SetUpProgramPtrs(fsg_SplineKey*) (libTrueTypeScaler.dylib:x86_64+0x4616)
    #2 0x7fff4efd623b in TTGetStrikeSpecs (libTrueTypeScaler.dylib:x86_64+0x623b)
    #3 0x7fff4ee438b4 in TConcreteFontScaler::GetFontInfo(FPFontInfo*) const (libFontParser.dylib:x86_64+0x278b4)
    #4 0x7fff4ee73db1 in TFPFont::FillFontInfo(FPFontInfo&) const (libFontParser.dylib:x86_64+0x57db1)
    #5 0x7fff4ee21cb7 in TFPFont::GetFontInfo() const (libFontParser.dylib:x86_64+0x5cb7)
    #6 0x7fff4ee74dd0 in FPFontGetFontInfo (libFontParser.dylib:x86_64+0x58dd0)
    #7 0x7fff50d4d3df in get_font_info (CoreGraphics:x86_64h+0xe3df)
    #8 0x7fff510ff208 in get_font_info (CoreGraphics:x86_64h+0x3c0208)
    #9 0x7fff50d4d39a in CGFontGetNumberOfGlyphs (CoreGraphics:x86_64h+0xe39a)
    #10 0x7fff52539ee7 in TBaseFont::CopyGraphicsFont() const (CoreText:x86_64+0x13ee7)
    #11 0x7fff52592ca1 in TSplicedFont::CopyGraphicsFont() const (CoreText:x86_64+0x6cca1)
    #12 0x7fff52539e8f in TBaseFont::GetParserFont() const (CoreText:x86_64+0x13e8f)
    #13 0x7fff5253225f in TFont::InitVariationValues() (CoreText:x86_64+0xc25f)
    #14 0x7fff52531515 in TFont::FinishConstruction(CGFont*) (CoreText:x86_64+0xb515)
    #15 0x7fff5252fbf5 in CTFontCreateWithFontDescriptor (CoreText:x86_64+0x9bf5)
    #16 0x10ca4f92f in create_from_desc(__CTFontDescriptor const*) SkFontHost_mac.cpp:794
    #17 0x10ca4f217 in SkFontStyleSet_Mac::createTypeface(int) SkFontHost_mac.cpp:2527
    #18 0x10eabffbc in txt::FontCollection::CreateMinikinFontFamily(sk_sp<SkFontMgr> const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) font_collection.cc:216
    #19 0x10eabe090 in txt::FontCollection::FindFontFamilyInManagers(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) font_collection.cc:193
    #20 0x10eabd256 in txt::FontCollection::GetMinikinFontCollectionForFamilies(std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) font_collection.cc:155
    #21 0x10b2b7faa in flutter::testing::ShellTest_ReloadSystemFonts_Test::TestBody() shell_unittests.cc:539
    #22 0x11062d6b2 in void testing::internal::HandleSehExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) gtest.cc:2447
    #23 0x1105d84a9 in void testing::internal::HandleExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) gtest.cc:2502
    #24 0x1105d7ffc in testing::Test::Run() gtest.cc:2522
    #25 0x1105da189 in testing::TestInfo::Run() gtest.cc:2698
    #26 0x1105dc779 in testing::TestSuite::Run() gtest.cc:2828
    #27 0x1105f5521 in testing::internal::UnitTestImpl::RunAllTests() gtest.cc:5285
    #28 0x11063a7a2 in bool testing::internal::HandleSehExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) gtest.cc:2447
    #29 0x1105f4800 in bool testing::internal::HandleExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) gtest.cc:2502
```

**Comment by eseidelGoogle** [comment]
I suspect these bugs are likely to go obsolete over time and it may make more sense to simply have a bug tracking getting sanitizer leaks to zero and setting up a sanitizer test which confirms they stay zero. :)

**Comment by chifandeyu** [comment]
Encounter this stack crash in version 2.10.3 but no way to fix it.
![image](https://user-images.githubusercontent.com/15946864/170224953-f771d709-6491-4212-8beb-5108b5821cbf.png)
