### ISSUE TITLE
Unable to run app at step 12 of the codelab

### ISSUE THREAD

**Issue by a14n** [flutter/flutter#4218]
## Steps to Reproduce

Run the app on my Nexus 4 at the end of [step 12 of the codelab](https://codelabs.developers.google.com/codelabs/flutter/index.html?index=..%2F..%2Findex#11).

## Flutter Doctor

```
[✓] Flutter (on Linux, channel codelab)
    • Flutter at xxx
    • Framework revision b4313b04b0 (il y a 9 jours), engine revision a1f4a12baa

[✓] Android toolchain - develop for Android devices (Android SDK 23.0.3)
    • Android SDK at xxx
    • Platform android-23, build-tools 23.0.3
    • Java(TM) SE Runtime Environment (build 1.8.0_91-b14)

[✓] Atom - a lightweight development environment for Flutter
    • Atom installed; Flutter plugin version 0.2.2
```

## Logs and Crash Reports

```
--------- beginning of system
W/ActivityManager: Unable to start service Intent { act=com.google.firebase.auth.api.gms.service.START pkg=com.yourcompany.myfirechat } U=0: not found
W/ActivityManager: Unbind failed: could not find connection for android.os.BinderProxy@2d18cb84
W/ActivityManager: Unable to start service Intent { act=com.google.firebase.auth.api.gms.service.START pkg=com.yourcompany.myfirechat } U=0: not found
W/ActivityManager: Unbind failed: could not find connection for android.os.BinderProxy@2da90f6d
E/flutter : [ERROR:dart_error.cc(17)] Unhandled exception:
E/flutter : Error(code: 0, message: API: InternalFirebaseAuth.FIREBASE_AUTH_API is not available on this device.)
E/flutter : #0      _rootHandleUncaughtError.<anonymous closure> (dart:async/zone.dart:938)
E/flutter : #1      _microtaskLoop (dart:async/schedule_microtask.dart:41)
E/flutter : #2      _startMicrotaskLoop (dart:async/schedule_microtask.dart:50)
```

**Comment by a14n** [comment]
Switched to my Nexus 5X and this error disappeared (with the same code).

**Comment by eseidelGoogle** [comment]
@collinjackson @sethladd @qchong is this the error from not having a new enough GMSCore?

**Comment by sethladd** [comment]
I wonder what we can do to better detect certain versions of dependencies like GMS core. Will this get better when we're building through gradle?    cc @abarth

**Comment by collinjackson** [comment]
This will get better when we're building through gradle.

**Comment by sethladd** [comment]
Thanks @collinjackson 

I'm going to close this, but definitely appreciate the feedback, @a14n !

**Comment by kroikie** [comment]
@a14n

This issue has been moved to https://github.com/FirebaseExtended/flutterfire/issues/1028. Any further collaboration will be done there.
