### ISSUE TITLE
App using new Android embedding crashes during start up.

### ISSUE THREAD

**Issue by blasten** [flutter/flutter#42205]
This is the stacktrace:
```
10-07 20:17:22.924  6956  6956 E AndroidRuntime: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.example.android_embedding_2/com.example.android_embedding_2.MainActivity}: java.lang.IllegalStateException: ensureInitializationComplete must be called after startInitialization
10-07 20:17:22.924  6956  6956 E AndroidRuntime: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2913)
10-07 20:17:22.924  6956  6956 E AndroidRuntime: 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3048)
10-07 20:17:22.924  6956  6956 E AndroidRuntime: 	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
10-07 20:17:22.924  6956  6956 E AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
10-07 20:17:22.924  6956  6956 E AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
10-07 20:17:22.924  6956  6956 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1808)
10-07 20:17:22.924  6956  6956 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:106)
10-07 20:17:22.924  6956  6956 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:193)
10-07 20:17:22.924  6956  6956 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6669)
10-07 20:17:22.924  6956  6956 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
10-07 20:17:22.924  6956  6956 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
10-07 20:17:22.924  6956  6956 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
10-07 20:17:22.924  6956  6956 E AndroidRuntime: Caused by: java.lang.IllegalStateException: ensureInitializationComplete must be called after startInitialization
10-07 20:17:22.924  6956  6956 E AndroidRuntime: 	at io.flutter.view.FlutterMain.ensureInitializationComplete(FlutterMain.java:168)
10-07 20:17:22.924  6956  6956 E AndroidRuntime: 	at io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.initializeFlutter(FlutterActivityAndFragmentDelegate.java:182)
10-07 20:17:22.924  6956  6956 E AndroidRuntime: 	at io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.onAttach(FlutterActivityAndFragmentDelegate.java:145)
10-07 20:17:22.924  6956  6956 E AndroidRuntime: 	at io.flutter.embedding.android.FlutterActivity.onCreate(FlutterActivity.java:401)
10-07 20:17:22.924  6956  6956 E AndroidRuntime: 	at android.app.Activity.performCreate(Activity.java:7136)
10-07 20:17:22.924  6956  6956 E AndroidRuntime: 	at android.app.Activity.performCreate(Activity.java:7127)
10-07 20:17:22.924  6956  6956 E AndroidRuntime: 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1271)
10-07 20:17:22.924  6956  6956 E AndroidRuntime: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2893)
10-07 20:17:22.924  6956  6956 E AndroidRuntime: 	... 11 more
10-07 20:17:22.930  1865  3647 W ActivityManager:   Force finishing activity com.example.android_embedding_2/.MainActivity
```

**MainActivity.kt**

```kt
package com.example.android_embedding_2

import androidx.annotation.NonNull;
import dev.flutter.plugins.GeneratedPluginRegistrant
import io.flutter.embedding.android.FlutterActivity
import io.flutter.embedding.engine.FlutterEngine

class MainActivity: FlutterActivity() {
  override fun configureFlutterEngine(@NonNull flutterEngine: FlutterEngine) {
    GeneratedPluginRegistrant.registerWith(flutterEngine);
  }
}

```

**GeneratedPluginRegistrant.java**

```java
package dev.flutter.plugins;

import androidx.annotation.NonNull;
import io.flutter.embedding.engine.FlutterEngine;

/**
 * Generated file. Do not edit.
 * This file is generated by the Flutter tool based on the
 * plugins that support the Android platform.
 */
public final class GeneratedPluginRegistrant {
  public static void registerWith(@NonNull FlutterEngine flutterEngine) {
  }
}
```

**AndroidManifest.xml**:
```xml
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    package="com.example.android_embedding_2">
    <!-- io.flutter.app.FlutterApplication is an android.app.Application that
         calls FlutterMain.startInitialization(this); in its onCreate method.
         In most cases you can leave this as-is, but you if you want to provide
         additional functionality it is fine to subclass or reimplement
         FlutterApplication and put your custom class here. -->
    <application
        android:label="android_embedding_2"
        android:icon="@mipmap/ic_launcher">
        <activity
            android:name="com.example.android_embedding_2.MainActivity"
            android:theme="@style/LaunchTheme"
            android:configChanges="orientation|keyboardHidden|keyboard|screenSize|locale|layoutDirection"
            android:hardwareAccelerated="true"
            android:windowSoftInputMode="adjustResize">
            <intent-filter>
                <action android:name="android.intent.action.MAIN"/>
                <category android:name="android.intent.category.LAUNCHER"/>
            </intent-filter>
        </activity>
        <!-- Don't delete the meta-data below.
             This is used by the Flutter tool to generate GeneratedPluginRegistrant.java -->
        <meta-data
            android:name="flutterEmbedding"
            android:value="2" />
    </application>
</manifest>
```

**Comment by matthew-carroll** [comment]
The crash says that you need to invoke `startInitialization()` and then `ensureInitializationComplete()`. The example code doesn't seem to indicate that either one is being called. I'm going to assign back to @blasten until the issue clarified or resolved.

**Comment by blasten** [comment]
This issue is fixed now. We have an smoke test running on Firebase device lab: https://github.com/flutter/flutter/tree/master/dev/integration_tests/android_embedding_2
