### ISSUE TITLE
Add fonts in pubspec.yaml and generate log logs as follows

### ISSUE THREAD

**Issue by yfrflash** [flutter/flutter#42219]
Flutter crash report; please file at https://github.com/flutter/flutter/issues.

## command

flutter --no-color run --machine --track-widget-creation --device-id=c92032d5 lib/main.dart

## exception

_TypeError: type 'String' is not a subtype of type 'YamlMap'

```
#0      _validateFonts (package:flutter_tools/src/flutter_manifest.dart:409:5)
#1      _validateFlutter (package:flutter_tools/src/flutter_manifest.dart:354:9)
#2      _validate (package:flutter_tools/src/flutter_manifest.dart:312:9)
<asynchronous suspension>
#3      FlutterManifest._createFromYaml (package:flutter_tools/src/flutter_manifest.dart:45:40)
<asynchronous suspension>
#4      FlutterManifest.createFromString (package:flutter_tools/src/flutter_manifest.dart:40:12)
<asynchronous suspension>
#5      FlutterManifest.createFromPath (package:flutter_tools/src/flutter_manifest.dart:34:12)
<asynchronous suspension>
#6      FlutterProject._readManifest (package:flutter_tools/src/project.dart:153:60)
<asynchronous suspension>
#7      FlutterProject.fromDirectory (package:flutter_tools/src/project.dart:44:44)
<asynchronous suspension>
#8      FlutterProject.current (package:flutter_tools/src/project.dart:55:46)
#9      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:477:59)
<asynchronous suspension>
#10     FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:424:33)
<asynchronous suspension>
#11     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:142:29)
<asynchronous suspension>
#12     _rootRun (dart:async/zone.dart:1124:13)
#13     _CustomZone.run (dart:async/zone.dart:1021:19)
#14     _runZoned (dart:async/zone.dart:1516:10)
#15     runZoned (dart:async/zone.dart:1463:12)
#16     AppContext.run (package:flutter_tools/src/base/context.dart:141:18)
<asynchronous suspension>
#17     FlutterCommand.run (package:flutter_tools/src/runner/flutter_command.dart:415:20)
#18     CommandRunner.runCommand (package:args/command_runner.dart:196:27)
<asynchronous suspension>
#19     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:396:21)
<asynchronous suspension>
#20     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:142:29)
<asynchronous suspension>
#21     _rootRun (dart:async/zone.dart:1124:13)
#22     _CustomZone.run (dart:async/zone.dart:1021:19)
#23     _runZoned (dart:async/zone.dart:1516:10)
#24     runZoned (dart:async/zone.dart:1463:12)
#25     AppContext.run (package:flutter_tools/src/base/context.dart:141:18)
<asynchronous suspension>
#26     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:356:19)
<asynchronous suspension>
#27     CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:111:29)
#28     new Future.sync (dart:async/future.dart:224:31)
#29     CommandRunner.run (package:args/command_runner.dart:111:11)
#30     FlutterCommandRunner.run (package:flutter_tools/src/runner/flutter_command_runner.dart:242:18)
#31     run.<anonymous closure> (package:flutter_tools/runner.dart:60:20)
<asynchronous suspension>
#32     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:142:29)
<asynchronous suspension>
#33     _rootRun (dart:async/zone.dart:1124:13)
#34     _CustomZone.run (dart:async/zone.dart:1021:19)
#35     _runZoned (dart:async/zone.dart:1516:10)
#36     runZoned (dart:async/zone.dart:1463:12)
#37     AppContext.run (package:flutter_tools/src/base/context.dart:141:18)
<asynchronous suspension>
#38     runInContext (package:flutter_tools/src/context_runner.dart:50:24)
<asynchronous suspension>
#39     run (package:flutter_tools/runner.dart:51:10)
#40     main (package:flutter_tools/executable.dart:60:9)
<asynchronous suspension>
#41     main (file:///Users/yangfan/flutter/packages/flutter_tools/bin/flutter_tools.dart:8:3)
#42     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:298:32)
#43     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:171:12)
```

## flutter doctor

```
[✓] Flutter (Channel dev, v1.5.8, on Mac OS X 10.14.5 18F132, locale zh-Hans-CN)
    • Flutter version 1.5.8 at /Users/yangfan/flutter
    • Framework revision 0ba67226ee (6 months ago), 2019-04-24 17:18:28 -0700
    • Engine revision c63d1cf9c9
    • Dart version 2.3.0 (build 2.3.0-dev.0.1 1f1592edce)

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/yangfan/SDK
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 28.0.3
    • ANDROID_HOME = /Users/yangfan/SDK
    • Java binary at: /Applications/Android Studio3.1.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✗] iOS toolchain - develop for iOS devices
    ✗ Xcode installation is incomplete; a full installation is necessary for iOS development.
      Download at: https://developer.apple.com/xcode/download/
      Or install Xcode via the App Store.
      Once installed, run:
        sudo xcode-select --switch /Applications/Xcode.app/Contents/Developer
    ✗ libimobiledevice and ideviceinstaller are not installed. To install with Brew, run:
        brew update
        brew install --HEAD usbmuxd
        brew link usbmuxd
        brew install --HEAD libimobiledevice
        brew install ideviceinstaller
    ✗ ios-deploy not installed. To install:
        brew install ios-deploy
    ✗ CocoaPods not installed.
        CocoaPods is used to retrieve the iOS platform side's plugin code that responds to your plugin usage on the Dart side.
        Without resolving iOS dependencies with CocoaPods, plugins will not work on iOS.
        For more info, see https://flutter.dev/platform-plugins
      To install:
        brew install cocoapods
        pod setup

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio3.1.app/Contents
    • Flutter plugin version 40.0.2
    • Dart plugin version 191.8423
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[!] IntelliJ IDEA Ultimate Edition (version 2017.3.3)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.dev/intellij-setup/#installing-the-plugins

[✓] Connected device (1 available)
    • ONEPLUS A5010 • c92032d5 • android-arm64 • Android 9 (API 28)

! Doctor found issues in 2 categories.
```

**Comment by mikhail-tokarev** [comment]
hi @yfrflash,
can you please post a self contained app on github to better address the issue,
thank you

**Comment by yfrflash** [comment]
我搞定了。
wrong：

fonts:
  - family: iconfont
    fonts:
      - assets/icons/iconfont.ttf


right：
fonts:
  - family: iconfont
    fonts:
      - asset: assets/icons/iconfont.ttf
pub spec.yaml 文件没有语法提示，好容易出错。


------------------ 原始邮件 ------------------
发件人: "Mikhail Tokarev"<notifications@github.com>;
发送时间: 2019年10月8日(星期二) 下午5:24
收件人: "flutter/flutter"<flutter@noreply.github.com>;
抄送: "R.flash"<2511562742@qq.com>;"Mention"<mention@noreply.github.com>;
主题: Re: [flutter/flutter] Add fonts in pubspec.yaml and generate log logsas follows (#42219)




hi @yfrflash,
 can you please post a self contained app on github to better address the issue,
 thank you

**Comment by mikhail-tokarev** [comment]
@yfrflash  
I'm glad to hear that you fixed the problem
I feel safe to close this issue;
if you disagree please write in the comments
and I will reopen it
