### ISSUE TITLE
Release of Flutter app dont works like in debug

### ISSUE THREAD

**Issue by Kassan424kh** [flutter/flutter#42237]
Hy everybody I trying to release my finished app with flutter, but the release dont work currently like on debugging mode.

what should i do to fix this pug?

```LOG
2019-10-08 14:50:48.723 22519-22519/? E/MethodChannel#com.example.example/p-times-updater: Failed to handle method call
    d.d
        at com.example.example.e.a$a.a(Unknown Source:38)
        at com.example.example.MainActivity$a.onMethodCall(Unknown Source:74)
        at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(Unknown Source:17)
        at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(Unknown Source:57)
        at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(Unknown Source:4)
        at android.os.MessageQueue.nativePollOnce(Native Method)
        at android.os.MessageQueue.next(MessageQueue.java:326)
        at android.os.Looper.loop(Looper.java:181)
        at android.app.ActivityThread.main(ActivityThread.java:6990)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1445)
```
```Log
I/flutter (22519): PlatformException(error, null, null)
```

```KOTLIN
        private val CHANNEL_UPDATER = "com.example.example/p-times-updater"

        MethodChannel(flutterView, CHANNEL_UPDATER).setMethodCallHandler { call, result ->
            when {
                call.method == "updatePTimesAfterNewPlaceData" -> {
                    RestServerFactory.getDataFromServer(this, true)
                    result.success(true)
                }
                call.method == "updateTodayPTimes" -> {
                    Executors.newSingleThreadScheduledExecutor().schedule({
                        JsonFilesServices.getTodayDatesFromJsonFile(this, true)
                    }, 1500, TimeUnit.MILLISECONDS)
                    result.success(true)
                }
                else -> {
                    result.notImplemented()
                    Toast.makeText(this, "pTimes not updated", Toast.LENGTH_LONG).show()
                }
            }
        }
```

```Dart
static const android = const MethodChannel('com.example.example/p-times-updater');
```

**Comment by Kassan424kh** [comment]
```bash
$ flutter doctor -v
```

```LOG
✓] Flutter (Channel master, v1.10.14-pre.12, on Mac OS X 10.15 19A583, locale en-GB)
    • Flutter version 1.10.14-pre.12 at /Users/kkhalil/flutter
    • Framework revision cdc2d9901d (15 hours ago), 2019-10-07 16:43:04 -0700
    • Engine revision 1d62160fdb
    • Dart version 2.6.0 (build 2.6.0-dev.1.0 d6c6d12ebf)


[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/kkhalil/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = /Users/kkhalil/Library/Android/sdk
    • Java binary at: /Users/kkhalil/Library/Application
      Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/191.5900203/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[!] Xcode - develop for iOS and macOS (Xcode 11.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.1, Build version 11A1027
    ✗ CocoaPods installed but not working.
        You appear to have CocoaPods installed but it is not working.
        This can happen if the version of Ruby that CocoaPods was installed with is different from the one being used
        to invoke it.
        This can usually be fixed by re-installing CocoaPods. For more info, see
        https://github.com/flutter/flutter/issues/14293.
      To re-install CocoaPods, run:
        sudo gem install cocoapods

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 40.0.2
    • Dart plugin version 191.8423
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] Android Studio (version 3.5)
    • Android Studio at /Users/kkhalil/Library/Application
      Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/191.5900203/Android Studio.app/Contents
    • Flutter plugin version 40.0.2
    • Dart plugin version 191.8423
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[!] IntelliJ IDEA Ultimate Edition (version 2019.1.2)
    • IntelliJ at /Users/kkhalil/Applications/JetBrains Toolbox/IntelliJ IDEA Ultimate.app
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    • Dart plugin version 191.8423
    • For information about installing plugins, see
      https://flutter.dev/intellij-setup/#installing-the-plugins

[✓] VS Code (version 1.38.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.5.1

[✓] Connected device (1 available)
    • SM N960F • 254a9fa0431c7ece • android-arm64 • Android 9 (API 28)

! Doctor found issues in 2 categories.
```

**Comment by Kassan424kh** [comment]
I found the log coming from _MethodChannel.class_ file.
It looks like: 
```JAVA
        @UiThread
        public void onMessage(ByteBuffer message, final BinaryReply reply) {
            MethodCall call = MethodChannel.this.codec.decodeMethodCall(message);

            try {
                this.handler.onMethodCall(call, new MethodChannel.Result() {
                    public void success(Object result) {
                        reply.reply(MethodChannel.this.codec.encodeSuccessEnvelope(result));
                    }

                    public void error(String errorCode, String errorMessage, Object errorDetails) {
                        reply.reply(MethodChannel.this.codec.encodeErrorEnvelope(errorCode, errorMessage, errorDetails));
                    }

                    public void notImplemented() {
                        reply.reply((ByteBuffer)null);
                    }
                });
            } catch (RuntimeException var5) {
                Log.e("MethodChannel#" + MethodChannel.this.name, "Failed to handle method call", var5);
                reply.reply(MethodChannel.this.codec.encodeErrorEnvelope("error", var5.getMessage(), (Object)null));
            }

        }
```

**Comment by Kassan424kh** [comment]
I solved the problem ☝🏻.
I should only modify parameter on release config in the build.gradle file:

```GRADLE
▶ // OLD
buildTypes {
        release {
            signingConfig signingConfigs.release

            minifyEnabled true
            useProguard true

            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'

        }
    }
```

```GRADLE
▶ // Now
buildTypes {
        release {
            signingConfig signingConfigs.release

            shrinkResources false
            minifyEnabled false
            useProguard false

            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
```
