### ISSUE TITLE
Crash on launching debug web from VSCode

### ISSUE THREAD

**Issue by NicolasDionB** [flutter/flutter#42231]
## Steps to Reproduce
1. Open my flutter project in VS Code
2. Hit F5 to start debugging in Chrome
3. Then I get the error:

```
Sending crash report to Google.
Crash report sent (report ID: 7a408835d5afbf3d)
Oops; flutter has exited unexpectedly.
Crash report written to D:\Dev_Git\ClientApps\live_app\flutter_03.log;
please let us know at https://github.com/flutter/flutter/issues.
```

I'm using Windows 10 Pro v1809, Chrome 77.0.3865.90 64 bits, VSCode 1.38.1, Flutter master channel 10.10.6-pre.61

### command
flutter run --machine --target lib\main.dart -d chrome --track-widget-creation --start-paused

### exception

NoSuchMethodError: NoSuchMethodError: The method 'toJson' was called on null.
Receiver: null
Tried calling: toJson()

```
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:51:5)
#1      SourceLocation.toJson (package:vm_service/vm_service.dart:5306:24)
#2      Frame.toJson (package:vm_service/vm_service.dart:3501:47)
#3      Event.toJson (package:vm_service/vm_service.dart:3227:47)
#4      VmServerConnection._delegateRequest.<anonymous closure> (package:vm_service/vm_service.dart:1174:28)
#5      _rootRunUnary (dart:async/zone.dart:1132:38)
#6      _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#7      _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
#8      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#9      _DelayedData.perform (dart:async/stream_impl.dart:591:14)
#10     _StreamImplEvents.handleNext (dart:async/stream_impl.dart:707:11)
#11     _PendingEvents.schedule.<anonymous closure> (dart:async/stream_impl.dart:667:7)
#12     _rootRun (dart:async/zone.dart:1120:38)
#13     _CustomZone.run (dart:async/zone.dart:1021:19)
#14     _CustomZone.runGuarded (dart:async/zone.dart:923:7)
#15     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:963:23)
#16     _rootRun (dart:async/zone.dart:1124:13)
#17     _CustomZone.run (dart:async/zone.dart:1021:19)
#18     _CustomZone.runGuarded (dart:async/zone.dart:923:7)
#19     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:963:23)
#20     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#21     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#22     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:116:13)
#23     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:173:5)
```

### Flutter analyze
```
Analyzing live_app...

   info - The value of the field '_iceServers' isn't used - lib\managers\stream\webrtc\base_webrtc_peer.dart:29:17 - unused_field
   info - This function has a return type of 'Map<String, dynamic>', but doesn't end with a return statement - lib\util\webrtc\webrtc.dart:45:10 - missing_return
   info - `Future` results in `async` function bodies must be `await`ed or marked `unawaited` using `package:pedantic` - test\main_test.dart:19:7 - unawaited_futures
   info - `Future` results in `async` function bodies must be `await`ed or marked `unawaited` using `package:pedantic` - test_driver\app_test.dart:21:9 - unawaited_futures

4 issues found. (ran in 2.0s)
```

### Flutter doctor
```
[√] Flutter (Channel master, v1.10.6-pre.61, on Microsoft Windows [Version 10.0.17763.775], locale fr-CA)
    • Flutter version 1.10.6-pre.61 at D:\_utils\Flutter
    • Framework revision 7bf9aea254 (13 days ago), 2019-09-25 00:37:12 -0700
    • Engine revision 63949eb0fd
    • Dart version 2.6.0 (build 2.6.0-dev.2.0 69b5681546)

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.0)
    • Android SDK at C:\Users\nicolas.dion\AppData\Local\Android\Sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.0
    • ANDROID_HOME = C:\Users\nicolas.dion\AppData\Local\Android\Sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[!] Android Studio (version 3.4)
    • Android Studio at C:\Program Files\Android\Android Studio
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

[!] IntelliJ IDEA Ultimate Edition (version 2016.3)
    • IntelliJ at C:\Program Files (x86)\JetBrains\IntelliJ IDEA 2016.3.8
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.dev/intellij-setup/#installing-the-plugins
    X This install is older than the minimum recommended version of 2017.1.0.

[!] IntelliJ IDEA Ultimate Edition (version 2019.2)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA 2019.2
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.dev/intellij-setup/#installing-the-plugins

[√] VS Code, 64-bit edition (version 1.38.1)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Flutter extension version 3.5.0

[√] Connected device (2 available)
    • Chrome • chrome • web-javascript • Google Chrome 77.0.3865.90
    • Server • web    • web-javascript • Flutter Tools

! Doctor found issues in 3 categories.
```

**Comment by mikhail-tokarev** [comment]
Hi @NicolasDionB 
can you please post a self contained app on github to better address the issue,
thank you

**Comment by jonahwilliams** [comment]
We should have fixed a lot of these issues with the latest update to the web tooling. I recommend upgrading to see if that fixes the issue

**Comment by NicolasDionB** [comment]
> We should have fixed a lot of these issues with the latest update to the web tooling. I recommend upgrading to see if that fixes the issue

Indeed, it all works now. Thanks!

**Comment by mikhail-tokarev** [comment]
Thanks for your feedback @NicolasDionB 
I feel safe to close this issue,
if you disagree please write in the comments
and I will reopen it
