### ISSUE TITLE
Unable to consistently run from Atom on Samsung

### ISSUE THREAD

**Issue by AsturaPhoenix** [flutter/flutter#4227]
While Atom/Flutter works consistently on my test Nexus, on my personal Samsung it sometimes works but often shows only a black screen, dumping errors with `Unable to connect to the Observatory at port 16196.`

On both devices, using `flutter run` from the command line works consistently.

On both devices, tapping the test app opens the initial demo state or some other earlier state.
## Steps to Reproduce
1. Starting with the "flutter create" demo app, run it on a Samsung Galaxy S6 Marshmallow.
2. It may run as expected. Make some arbitrary change like app bar color, and run again.
3. On my device, it errors and freezes on a black screen.
4. Forcing the app to stop and clicking the installed icon starts the app in a far earlier state, possibly the original demo app.
5. Uninstalling and reinstalling the app does not change 3-4.
6. Rebooting the device without the app installed brings us back to 1.
## Flutter Doctor

```
[✓] Flutter (on Linux, channel alpha)
    • Flutter at /usr/local/google/home/rosswang/flutter
    • Framework revision d5e3ea2f9c (4 days ago), engine revision 7fab0c350b

[✓] Android toolchain - develop for Android devices (Android SDK 23.0.1)
    • Android SDK at /usr/local/google/home/rosswang/Android/Sdk
    • Platform android-23, build-tools 23.0.1
    • OpenJDK Runtime Environment (build 1.8.0-google-v7-122278751-122271652)

[✓] Atom - a lightweight development environment for Flutter
    • Atom installed; Flutter plugin version 0.2.2
```
## Logs and Crash Reports

```
flutter run --debug-port=16227 --start-paused --device-id 05157df530fbb53b • flutter logs
multichat/ • debug
Installing app.apk to SM G920V...
Running lib/main.dart on SM G920V...
Observatory listening on http://127.0.0.1:16227
Diagnostic server listening on http://127.0.0.1:8109
Unable to connect to the Observatory at port 16227.
Showing SM G920V logs:
--------- beginning of main
W/System.err: remove failed: ENOTEMPTY (Directory not empty) : /data/user/0/com.target.socsav/cache/com.parse
W/System.err: remove failed: ENOTEMPTY (Directory not empty) : /data/user/0/com.target.socsav/cache/picasso-cache
W/System.err: remove failed: ENOENT (No such file or directory) : /data/app/vmdl1671399593.tmp/lib
W/System.err: remove failed: ENOENT (No such file or directory) : /data/app/vmdl1671399593.tmp/lib/arm64
W/System.err: remove failed: ENOENT (No such file or directory) : /data/system/users/0/package-restrictions.xml.bak
W/System.err: remove failed: ENOENT (No such file or directory) : /data/system/users/0/package-restrictions.xml.bak
W/System.err: remove failed: ENOENT (No such file or directory) : /data/user/0/com.sec.spp.push/files/pushLog0.txt
W/System.err: remove failed: ENOENT (No such file or directory) : /data/user/0/com.sec.spp.push/files/pushLog1.txt
W/System.err: remove failed: ENOENT (No such file or directory) : /data/system/sync/pending.xml.bak
W/System.err: remove failed: ENOENT (No such file or directory) : /data/system/sync/pending.xml.bak
W/System.err: remove failed: ENOENT (No such file or directory) : /data/system/sync/pending.xml.bak
W/System.err: stat failed: ENOENT (No such file or directory) : /data/user/0/com.policydm/app_log/policydm_session0.log
W/System.err: remove failed: ENOENT (No such file or directory) : /data/user/0/com.google.android.gms/databases/copresence_state.db
W/System.err: remove failed: ENOENT (No such file or directory) : /data/user/0/com.google.android.gms/databases/copresence_state.db-journal
W/System.err: remove failed: ENOENT (No such file or directory) : /data/user/0/com.google.android.gms/databases/copresence_state.db-shm
W/System.err: remove failed: ENOENT (No such file or directory) : /data/user/0/com.google.android.gms/databases/copresence_state.db-wal
E/ActivityManager: Values are ::2 true false
E/ActivityManager: Values are ::2 true false
E/ActivityManager: Values are ::2 true false
W/System.err: remove failed: ENOENT (No such file or directory) : /data/user/0/com.google.android.talk/databases/babel5.db
W/System.err: remove failed: ENOENT (No such file or directory) : /data/user/0/com.google.android.talk/databases/babel5.db-journal
W/System.err: remove failed: ENOENT (No such file or directory) : /data/user/0/com.google.android.talk/databases/babel5.db-shm
W/System.err: remove failed: ENOENT (No such file or directory) : /data/user/0/com.google.android.talk/databases/babel5.db-wal
W/System.err: remove failed: ENOENT (No such file or directory) : /data/system/sync/pending.xml.bak
W/System.err: remove failed: ENOENT (No such file or directory) : /data/system/sync/pending.xml.bak
W/System.err: remove failed: ENOENT (No such file or directory) : /data/system/sync/pending.xml.bak
W/System.err: mkdir failed: EEXIST (File exists) : /data/user/0/com.google.android.apps.inbox/app_cumulusIdb/IDX-595182330
W/System.err: mkdir failed: EEXIST (File exists) : /data/user/0/com.google.android.apps.inbox/app_cumulusIdb/IDX-343817336
W/System.err: SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
W/System.err: SLF4J: Defaulting to no-operation (NOP) logger implementation
W/System.err: SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
W/System.err: mkdir failed: EEXIST (File exists) : /storage/emulated/0/Android/data/com.google.android.apps.maps/testdata
W/System.err: mkdir failed: EEXIST (File exists) : /data/user/0/com.google.android.apps.maps/app_/testdata
W/System.err: mkdir failed: EEXIST (File exists) : /storage/emulated/0/Android/data/com.google.android.apps.maps/cache
W/System.err: remove failed: ENOENT (No such file or directory) : /data/user/0/com.amazon.mShop.android/cache/http/journal.tmp
W/System.err: remove failed: ENOENT (No such file or directory) : /data/user/0/com.amazon.mShop.android/files/databases/assets
W/System.err: remove failed: ENOENT (No such file or directory) : /data/user/0/com.amazon.mShop.android/files/databases/assets-journal
W/System.err: remove failed: ENOENT (No such file or directory) : /data/user/0/com.amazon.mShop.android/files/databases/assets-shm
W/System.err: remove failed: ENOENT (No such file or directory) : /data/user/0/com.amazon.mShop.android/files/databases/assets-wal
W/System.err: remove failed: ENOENT (No such file or directory) : /data/user/0/com.amazon.mShop.android/files/databases/wifiaccesspoints
W/System.err: remove failed: ENOENT (No such file or directory) : /data/user/0/com.amazon.mShop.android/files/databases/wifiaccesspoints-journal
W/System.err: remove failed: ENOENT (No such file or directory) : /data/user/0/com.amazon.mShop.android/files/databases/wifiaccesspoints-shm
W/System.err: remove failed: ENOENT (No such file or directory) : /data/user/0/com.amazon.mShop.android/files/databases/wifiaccesspoints-wal
W/System.err: mkdir failed: EEXIST (File exists) : /data/user/0/com.google.android.apps.inbox/app_cumulusIdb/IDX-353579651
F/Adjust  : PRODUCTION: Adjust is running in Production mode. Use this setting only for the build that you want to publish. Set the environment to `sandbox` if you want to test your app!
W/System.err: remove failed: ENOENT (No such file or directory) : /data/system/sync/pending.xml.bak
W/System.err: remove failed: ENOENT (No such file or directory) : /data/system/sync/pending.xml.bak
W/System.err: remove failed: ENOENT (No such file or directory) : /data/system/packages.xml.bak
W/System.err: remove failed: ENOENT (No such file or directory) : /data/system/users/0/package-restrictions.xml.bak
W/System.err: remove failed: ENOENT (No such file or directory) : /data/user/0/com.android.vending/cache/safe_mode806712
W/System.err: remove failed: ENOENT (No such file or directory) : /storage/emulated/0/.mtp
W/System.err: remove failed: ENOENT (No such file or directory) : /data/system/sync/pending.xml.bak
W/System.err: remove failed: ENOENT (No such file or directory) : /data/system/sync/pending.xml.bak
W/System.err: remove failed: ENOTEMPTY (Directory not empty) : /data/user/0/com.google.android.gms/app_fb
W/System.err: remove failed: ENOTEMPTY (Directory not empty) : /data/user/0/com.target.socsav/cache/com.parse
W/System.err: remove failed: ENOTEMPTY (Directory not empty) : /data/user/0/com.target.socsav/cache/picasso-cache
W/System.err: remove failed: ENOENT (No such file or directory) : /data/user/0/com.google.android.talk/databases/babel5.db
W/System.err: remove failed: ENOENT (No such file or directory) : /data/user/0/com.google.android.talk/databases/babel5.db-journal
W/System.err: remove failed: ENOENT (No such file or directory) : /data/user/0/com.google.android.talk/databases/babel5.db-shm
W/System.err: remove failed: ENOENT (No such file or directory) : /data/user/0/com.google.android.talk/databases/babel5.db-wal
W/System.err: remove failed: ENOENT (No such file or directory) : /data/user/0/com.google.android.gms/databases/history_query.db
W/System.err: remove failed: ENOENT (No such file or directory) : /data/user/0/com.google.android.gms/databases/history_query.db-journal
W/System.err: remove failed: ENOENT (No such file or directory) : /data/user/0/com.google.android.gms/databases/history_query.db-shm
W/System.err: remove failed: ENOENT (No such file or directory) : /data/user/0/com.google.android.gms/databases/history_query.db-wal
W/System.err: remove failed: ENOENT (No such file or directory) : /data/app/vmdl1057781259.tmp/lib
W/System.err: remove failed: ENOENT (No such file or directory) : /data/app/vmdl1057781259.tmp/lib/arm
W/System.err: remove failed: ENOENT (No such file or directory) : /data/system/sync/pending.xml.bak
W/System.err: remove failed: ENOENT (No such file or directory) : /data/system/sync/pending.xml.bak
W/System.err: remove failed: ENOENT (No such file or directory) : /data/system/sync/pending.xml.bak
W/System.err: remove failed: ENOENT (No such file or directory) : /data/system/users/0/package-restrictions.xml.bak
W/System.err: remove failed: ENOENT (No such file or directory) : /data/system/packages.xml.bak
W/System.err: remove failed: ENOENT (No such file or directory) : /data/system/users/0/package-restrictions.xml.bak
I/flutter : Observatory listening on http://127.0.0.1:43251
I/flutter : Diagnostic server listening on http://127.0.0.1:45638
W/System.err: remove failed: ENOENT (No such file or directory) : /data/system/recent_tasks/15182_task.xml.bak
W/System.err: remove failed: ENOENT (No such file or directory) : /data/user/0/com.android.vending/cache/safe_mode806712
W/System.err: mkdir failed: EEXIST (File exists) : /data/user/0/com.google.android.apps.docs/files/shiny_blobs/blobs
W/System.err: mkdir failed: EEXIST (File exists) : /data/user/0/com.google.android.apps.docs/files/shiny_blobs/blobs_in_construction
W/System.err: remove failed: ENOENT (No such file or directory) : /data/user/0/com.google.android.apps.docs/databases/ClientFlag.db
W/System.err: remove failed: ENOENT (No such file or directory) : /data/user/0/com.google.android.apps.docs/databases/ClientFlag.db-journal
W/System.err: remove failed: ENOENT (No such file or directory) : /data/user/0/com.google.android.apps.docs/databases/ClientFlag.db-shm
W/System.err: remove failed: ENOENT (No such file or directory) : /data/user/0/com.google.android.apps.docs/databases/ClientFlag.db-wal
W/System.err: remove failed: ENOENT (No such file or directory) : /data/app/vmdl2020054104.tmp/lib
W/System.err: remove failed: ENOENT (No such file or directory) : /data/app/vmdl2020054104.tmp/lib/arm
W/System.err: remove failed: ENOENT (No such file or directory) : /data/user/0/com.google.android.gms/safe_browsing/snet_safe_browsing_logs
W/System.err: remove failed: ENOTEMPTY (Directory not empty) : /data/user/0/com.google.android.gms/app_fb
W/System.err: remove failed: ENOENT (No such file or directory) : /data/system/packages.xml.bak
W/System.err: remove failed: ENOENT (No such file or directory) : /data/system/users/0/package-restrictions.xml.bak
W/System.err: remove failed: ENOENT (No such file or directory) : /data/system/packages.xml.bak
W/System.err: remove failed: ENOENT (No such file or directory) : /data/system/users/0/package-restrictions.xml.bak
W/System.err: remove failed: ENOENT (No such file or directory) : /data/system/users/0/package-restrictions.xml.bak
W/System.err: remove failed: ENOENT (No such file or directory) : /data/user/0/com.google.android.gms/databases/history_query.db
W/System.err: remove failed: ENOENT (No such file or directory) : /data/user/0/com.google.android.gms/databases/history_query.db-journal
W/System.err: remove failed: ENOENT (No such file or directory) : /data/user/0/com.google.android.gms/databases/history_query.db-shm
W/System.err: remove failed: ENOENT (No such file or directory) : /data/user/0/com.google.android.gms/databases/history_query.db-wal
W/System.err: remove failed: ENOENT (No such file or directory) : /data/system/recent_tasks/15183_task.xml.bak
W/System.err: remove failed: ENOENT (No such file or directory) : /data/user/0/com.android.vending/cache/safe_mode806712
W/System.err: remove failed: ENOENT (No such file or directory) : /data/app/vmdl1189081970.tmp/lib
W/System.err: remove failed: ENOENT (No such file or directory) : /data/app/vmdl1189081970.tmp/lib/arm64
I/flutter : Observatory listening on http://127.0.0.1:58494
I/flutter : Diagnostic server listening on http://127.0.0.1:47159
W/System.err: remove failed: ENOENT (No such file or directory) : /data/system/recent_tasks/15184_task.xml.bak
W/System.err: mkdir failed: EEXIST (File exists) : /data/data/com.sec.android.app.sns3/cache/logs
W/System.err: org.json.JSONException: No value for formattedName
W/System.err:   at org.json.JSONObject.get(JSONObject.java:389)
W/System.err:   at org.json.JSONObject.getString(JSONObject.java:550)
W/System.err:   at com.sec.android.app.sns3.svc.sp.linkedin.parser.SnsLiParserPeopleLookUp.parserPeopleLookup(SnsLiParserPeopleLookUp.java:106)
W/System.err:   at com.sec.android.app.sns3.svc.sp.linkedin.parser.SnsLiParserPeopleLookUp.parse(SnsLiParserPeopleLookUp.java:81)
W/System.err:   at com.sec.android.app.sns3.svc.sp.linkedin.request.SnsLiReqGetPeopleLookUp.parse(SnsLiReqGetPeopleLookUp.java:97)
W/System.err:   at com.sec.android.app.sns3.svc.request.AbstractSnsRequest$2.onResponse(AbstractSnsRequest.java:183)
W/System.err:   at com.sec.android.app.sns3.svc.http.SnsHttpThread.run(SnsHttpThread.java:172)
W/System.err: android.database.sqlite.SQLiteException: no such column: private (code 1): , while compiling: SELECT picture_url, large_picture_url FROM people_lookup WHERE (member_id = private)
W/System.err: #################################################################
W/System.err: Error Code : 1 (SQLITE_ERROR)
W/System.err: Caused By : SQL(query) error or missing database.
W/System.err:   (no such column: private (code 1): , while compiling: SELECT picture_url, large_picture_url FROM people_lookup WHERE (member_id = private))
W/System.err: #################################################################
W/System.err:   at android.database.sqlite.SQLiteConnection.nativePrepareStatement(Native Method)
W/System.err:   at android.database.sqlite.SQLiteConnection.acquirePreparedStatement(SQLiteConnection.java:1058)
W/System.err:   at android.database.sqlite.SQLiteConnection.prepare(SQLiteConnection.java:623)
W/System.err:   at android.database.sqlite.SQLiteSession.prepare(SQLiteSession.java:588)
W/System.err:   at android.database.sqlite.SQLiteProgram.<init>(SQLiteProgram.java:59)
W/System.err:   at android.database.sqlite.SQLiteQuery.<init>(SQLiteQuery.java:37)
W/System.err:   at android.database.sqlite.SQLiteDirectCursorDriver.query(SQLiteDirectCursorDriver.java:44)
W/System.err:   at android.database.sqlite.SQLiteDatabase.rawQueryWithFactory(SQLiteDatabase.java:1454)
W/System.err:   at android.database.sqlite.SQLiteQueryBuilder.query(SQLiteQueryBuilder.java:400)
W/System.err:   at android.database.sqlite.SQLiteQueryBuilder.query(SQLiteQueryBuilder.java:294)
W/System.err:   at com.sec.android.app.sns3.agent.sp.linkedin.db.SnsLinkedInContentProvider.query(SnsLinkedInContentProvider.java:316)
W/System.err:   at android.content.ContentProvider.query(ContentProvider.java:1058)
W/System.err:   at android.content.ContentProvider$Transport.query(ContentProvider.java:245)
W/System.err:   at android.content.ContentResolver.query(ContentResolver.java:502)
W/System.err:   at android.content.ContentResolver.query(ContentResolver.java:445)
W/System.err:   at com.sec.android.app.sns3.agent.sp.linkedin.command.SnsLiCmdGetPeopleLookUp$1.onReqRespond(SnsLiCmdGetPeopleLookUp.java:104)
W/System.err:   at com.sec.android.app.sns3.svc.sp.linkedin.request.SnsLiReqGetPeopleLookUp.respond(SnsLiReqGetPeopleLookUp.java:102)
W/System.err:   at com.sec.android.app.sns3.svc.request.SnsRequestMgr.processResponse(SnsRequestMgr.java:323)
W/System.err:   at com.sec.android.app.sns3.svc.request.SnsRequestMgr.access$700(SnsRequestMgr.java:38)
W/System.err:   at com.sec.android.app.sns3.svc.request.SnsRequestMgr$1.handleMessage(SnsRequestMgr.java:118)
W/System.err:   at android.os.Handler.dispatchMessage(Handler.java:102)
W/System.err:   at android.os.Looper.loop(Looper.java:158)
W/System.err:   at com.sec.android.app.sns3.svc.request.SnsRequestMgr.run(SnsRequestMgr.java:171)
W/System.err: mkdir failed: EEXIST (File exists) : /data/data/com.sec.android.app.sns3/cache/logs
W/System.err: mkdir failed: EEXIST (File exists) : /data/data/com.sec.android.app.sns3/cache/logs
W/System.err: mkdir failed: EEXIST (File exists) : /data/data/com.sec.android.app.sns3/cache/logs
W/System.err: org.json.JSONException: No value for formattedName
W/System.err:   at org.json.JSONObject.get(JSONObject.java:389)
W/System.err:   at org.json.JSONObject.getString(JSONObject.java:550)
W/System.err:   at com.sec.android.app.sns3.svc.sp.linkedin.parser.SnsLiParserPeopleLookUp.parserPeopleLookup(SnsLiParserPeopleLookUp.java:106)
W/System.err:   at com.sec.android.app.sns3.svc.sp.linkedin.parser.SnsLiParserPeopleLookUp.parse(SnsLiParserPeopleLookUp.java:81)
W/System.err:   at com.sec.android.app.sns3.svc.sp.linkedin.request.SnsLiReqGetPeopleLookUp.parse(SnsLiReqGetPeopleLookUp.java:97)
W/System.err:   at com.sec.android.app.sns3.svc.request.AbstractSnsRequest$2.onResponse(AbstractSnsRequest.java:183)
W/System.err:   at com.sec.android.app.sns3.svc.http.SnsHttpThread.run(SnsHttpThread.java:172)
W/System.err: mkdir failed: EEXIST (File exists) : /data/data/com.sec.android.app.sns3/cache/logs
W/System.err: android.database.sqlite.SQLiteException: no such column: private (code 1): , while compiling: SELECT picture_url, large_picture_url FROM people_lookup WHERE (member_id = private)
W/System.err: #################################################################
W/System.err: Error Code : 1 (SQLITE_ERROR)
W/System.err: Caused By : SQL(query) error or missing database.
W/System.err:   (no such column: private (code 1): , while compiling: SELECT picture_url, large_picture_url FROM people_lookup WHERE (member_id = private))
W/System.err: #################################################################
W/System.err:   at android.database.sqlite.SQLiteConnection.nativePrepareStatement(Native Method)
W/System.err:   at android.database.sqlite.SQLiteConnection.acquirePreparedStatement(SQLiteConnection.java:1058)
W/System.err:   at android.database.sqlite.SQLiteConnection.prepare(SQLiteConnection.java:623)
W/System.err:   at android.database.sqlite.SQLiteSession.prepare(SQLiteSession.java:588)
W/System.err:   at android.database.sqlite.SQLiteProgram.<init>(SQLiteProgram.java:59)
W/System.err:   at android.database.sqlite.SQLiteQuery.<init>(SQLiteQuery.java:37)
W/System.err:   at android.database.sqlite.SQLiteDirectCursorDriver.query(SQLiteDirectCursorDriver.java:44)
W/System.err:   at android.database.sqlite.SQLiteDatabase.rawQueryWithFactory(SQLiteDatabase.java:1454)
W/System.err:   at android.database.sqlite.SQLiteQueryBuilder.query(SQLiteQueryBuilder.java:400)
W/System.err:   at android.database.sqlite.SQLiteQueryBuilder.query(SQLiteQueryBuilder.java:294)
W/System.err:   at com.sec.android.app.sns3.agent.sp.linkedin.db.SnsLinkedInContentProvider.query(SnsLinkedInContentProvider.java:316)
W/System.err:   at android.content.ContentProvider.query(ContentProvider.java:1058)
W/System.err:   at android.content.ContentProvider$Transport.query(ContentProvider.java:245)
W/System.err:   at android.content.ContentResolver.query(ContentResolver.java:502)
W/System.err:   at android.content.ContentResolver.query(ContentResolver.java:445)
W/System.err:   at com.sec.android.app.sns3.agent.sp.linkedin.command.SnsLiCmdGetPeopleLookUp$1.onReqRespond(SnsLiCmdGetPeopleLookUp.java:104)
W/System.err:   at com.sec.android.app.sns3.svc.sp.linkedin.request.SnsLiReqGetPeopleLookUp.respond(SnsLiReqGetPeopleLookUp.java:102)
W/System.err:   at com.sec.android.app.sns3.svc.request.SnsRequestMgr.processResponse(SnsRequestMgr.java:323)
W/System.err:   at com.sec.android.app.sns3.svc.request.SnsRequestMgr.access$700(SnsRequestMgr.java:38)
W/System.err:   at com.sec.android.app.sns3.svc.request.SnsRequestMgr$1.handleMessage(SnsRequestMgr.java:118)
W/System.err:   at android.os.Handler.dispatchMessage(Handler.java:102)
W/System.err:   at android.os.Looper.loop(Looper.java:158)
W/System.err:   at com.sec.android.app.sns3.svc.request.SnsRequestMgr.run(SnsRequestMgr.java:171)
W/System.err: mkdir failed: EEXIST (File exists) : /data/data/com.sec.android.app.sns3/cache/logs
W/System.err: remove failed: ENOENT (No such file or directory) : /data/system/packages.xml.bak
W/System.err: remove failed: ENOENT (No such file or directory) : /data/system/users/0/package-restrictions.xml.bak
W/System.err: remove failed: ENOENT (No such file or directory) : /data/system/packages.xml.bak
W/System.err: remove failed: ENOENT (No such file or directory) : /data/system/users/0/package-restrictions.xml.bak
W/System.err: remove failed: ENOENT (No such file or directory) : /data/system/users/0/package-restrictions.xml.bak
W/System.err: remove failed: ENOENT (No such file or directory) : /data/user/0/com.google.android.gms/databases/history_query.db
W/System.err: remove failed: ENOENT (No such file or directory) : /data/user/0/com.google.android.gms/databases/history_query.db-journal
W/System.err: remove failed: ENOENT (No such file or directory) : /data/user/0/com.google.android.gms/databases/history_query.db-shm
W/System.err: remove failed: ENOENT (No such file or directory) : /data/user/0/com.google.android.gms/databases/history_query.db-wal
W/System.err: remove failed: ENOENT (No such file or directory) : /data/user/0/com.linkedin.android/files/flagship-disk-cache
W/System.err: stat failed: ENOENT (No such file or directory) : /data/local/chrome-command-line
W/System.err: remove failed: ENOENT (No such file or directory) : /data/system/packages.xml.bak
W/System.err: remove failed: ENOENT (No such file or directory) : /data/system/users/0/package-restrictions.xml.bak
W/System.err: remove failed: ENOENT (No such file or directory) : /storage/emulated/0/Android/data/io.baku.multichat
W/System.err: remove failed: ENOENT (No such file or directory) : /storage/emulated/0/Android/media/io.baku.multichat
W/System.err: remove failed: ENOENT (No such file or directory) : /storage/emulated/0/Android/obb/io.baku.multichat
W/System.err: mkdir failed: EEXIST (File exists) : /data/system/users/0
W/System.err: remove failed: ENOENT (No such file or directory) : /data/user/0/com.google.android.gms/databases/history_query.db
W/System.err: remove failed: ENOENT (No such file or directory) : /data/user/0/com.google.android.gms/databases/history_query.db-journal
W/System.err: remove failed: ENOENT (No such file or directory) : /data/user/0/com.google.android.gms/databases/history_query.db-shm
W/System.err: remove failed: ENOENT (No such file or directory) : /data/user/0/com.google.android.gms/databases/history_query.db-wal
W/System.err: remove failed: ENOENT (No such file or directory) : /data/system/sync/pending.xml.bak
W/System.err: remove failed: ENOENT (No such file or directory) : /data/system/sync/pending.xml.bak
W/System.err: mkdir failed: EEXIST (File exists) : /data/user/0/com.google.android.apps.inbox/app_cumulusIdb/IDX-353579651
--------- beginning of system
W/System.err: remove failed: ENOENT (No such file or directory) : /data/app/vmdl1694873364.tmp/lib
W/System.err: remove failed: ENOENT (No such file or directory) : /data/app/vmdl1694873364.tmp/lib/arm
W/System.err: remove failed: ENOTEMPTY (Directory not empty) : /data/user/0/com.google.android.gms/app_fb
W/System.err: remove failed: ENOENT (No such file or directory) : /data/system/users/0/package-restrictions.xml.bak
W/System.err: remove failed: ENOENT (No such file or directory) : /data/system/packages.xml.bak
W/System.err: remove failed: ENOENT (No such file or directory) : /data/system/users/0/package-restrictions.xml.bak
W/System.err: remove failed: ENOENT (No such file or directory) : /data/system/users/0/package-restrictions.xml.bak
W/ActivityManager: Permission Denial: Accessing service ComponentInfo{com.google.android.music/com.google.android.music.dial.DialMediaRouteProviderService} from pid=11631, uid=10200 that is not exported from uid 10144
W/ActivityManager: Permission Denial: Accessing service ComponentInfo{com.google.android.music/com.google.android.music.dial.DialMediaRouteProviderService} from pid=11631, uid=10200 that is not exported from uid 10144
I/flutter : Observatory listening on http://127.0.0.1:48454
I/flutter : Diagnostic server listening on http://127.0.0.1:50706
W/System.err: remove failed: ENOENT (No such file or directory) : /data/system/recent_tasks/15187_task.xml.bak
W/System.err: mkdir failed: EEXIST (File exists) : /data/user/0/com.google.android.apps.docs/files/shiny_blobs/blobs
W/System.err: mkdir failed: EEXIST (File exists) : /data/user/0/com.google.android.apps.docs/files/shiny_blobs/blobs_in_construction
W/System.err: remove failed: ENOENT (No such file or directory) : /data/user/0/com.google.android.apps.docs/databases/ClientFlag.db
W/System.err: remove failed: ENOENT (No such file or directory) : /data/user/0/com.google.android.apps.docs/databases/ClientFlag.db-journal
W/System.err: remove failed: ENOENT (No such file or directory) : /data/user/0/com.google.android.apps.docs/databases/ClientFlag.db-shm
W/System.err: remove failed: ENOENT (No such file or directory) : /data/user/0/com.google.android.apps.docs/databases/ClientFlag.db-wal
W/System.err: remove failed: ENOTEMPTY (Directory not empty) : /data/user/0/com.google.android.apps.docs/cache/diskCache
W/System.err: remove failed: ENOTEMPTY (Directory not empty) : /data/user/0/com.google.android.apps.docs/cache/docs_glide
W/System.err: remove failed: ENOTEMPTY (Directory not empty) : /data/user/0/com.google.android.apps.docs/cache/org.chromium.android_webview
W/System.err: remove failed: ENOENT (No such file or directory) : /data/system/users/0/package-restrictions.xml.bak
I/flutter : Observatory listening on http://127.0.0.1:51329
I/flutter : Diagnostic server listening on http://127.0.0.1:50211
W/System.err: remove failed: ENOENT (No such file or directory) : /data/system/recent_tasks/15188_task.xml.bak
W/System.err: remove failed: ENOTEMPTY (Directory not empty) : /data/user/0/com.target.socsav/cache/com.parse
W/System.err: remove failed: ENOTEMPTY (Directory not empty) : /data/user/0/com.target.socsav/cache/picasso-cache
W/System.err: remove failed: ENOENT (No such file or directory) : /data/user/0/com.amazon.avod.thirdpartyclient/files/databases/assets
W/System.err: remove failed: ENOENT (No such file or directory) : /data/user/0/com.amazon.avod.thirdpartyclient/files/databases/assets-journal
W/System.err: remove failed: ENOENT (No such file or directory) : /data/user/0/com.amazon.avod.thirdpartyclient/files/databases/assets-shm
W/System.err: remove failed: ENOENT (No such file or directory) : /data/user/0/com.amazon.avod.thirdpartyclient/files/databases/assets-wal
W/System.err: remove failed: ENOENT (No such file or directory) : /data/user/0/com.amazon.avod.thirdpartyclient/files/databases/wifiaccesspoints
W/System.err: remove failed: ENOENT (No such file or directory) : /data/user/0/com.amazon.avod.thirdpartyclient/files/databases/wifiaccesspoints-journal
W/System.err: remove failed: ENOENT (No such file or directory) : /data/user/0/com.amazon.avod.thirdpartyclient/files/databases/wifiaccesspoints-shm
W/System.err: remove failed: ENOENT (No such file or directory) : /data/user/0/com.amazon.avod.thirdpartyclient/files/databases/wifiaccesspoints-wal
W/System.err: SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
W/System.err: SLF4J: Defaulting to no-operation (NOP) logger implementation
W/System.err: SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
W/System.err: remove failed: ENOENT (No such file or directory) : /data/user/0/com.amazon.mp3/databases/downloads.db
W/System.err: remove failed: ENOENT (No such file or directory) : /data/user/0/com.amazon.mp3/databases/downloads.db-journal
W/System.err: remove failed: ENOENT (No such file or directory) : /data/user/0/com.amazon.mp3/databases/downloads.db-shm
W/System.err: remove failed: ENOENT (No such file or directory) : /data/user/0/com.amazon.mp3/databases/downloads.db-wal
W/ActivityManager: Unable to start service Intent { act=com.urbanairship.richpush.USER_UPDATE cmp=com.amazon.mp3/com.urbanairship.richpush.RichPushUpdateService (has extras) } U=0: not found
W/ActivityManager: Unable to start service Intent { act=com.urbanairship.location.ACTION_CHECK_LOCATION_UPDATES cmp=com.amazon.mp3/com.urbanairship.location.LocationService (has extras) } U=0: not found
W/ActivityManager: Permission Denial: Accessing service ComponentInfo{com.google.android.music/com.google.android.music.dial.DialMediaRouteProviderService} from pid=11631, uid=10200 that is not exported from uid 10144
W/ActivityManager: Permission Denial: Accessing service ComponentInfo{com.google.android.music/com.google.android.music.dial.DialMediaRouteProviderService} from pid=11631, uid=10200 that is not exported from uid 10144
I/flutter : Observatory listening on http://127.0.0.1:47476
I/flutter : Diagnostic server listening on http://127.0.0.1:47428
W/System.err: remove failed: ENOENT (No such file or directory) : /data/system/recent_tasks/15189_task.xml.bak
no errors1 processlib/multichat/contacts.dart17:18
LFUTF-8Dart
```

> For more information about diagnosing and reporting Flutter bugs, please see [https://flutter.io/bug-reports/](https://flutter.io/bug-reports/).

**Comment by eseidelGoogle** [comment]
I don't see a log about the Diagnostic server starting on 16227 anywhere in that log, which I would expect if the tool were to find it to connect to it.  This could be another case of `adb logcat -c` not working as we expect, or the log-since-time-x is not working in adb log.

The behavior of using an old version of the app when launching from the launcher is expected, but confusing.  Every time your app's runner changes (engine changes, flutter upgrades, etc) we build a new .apk and install it.  That .apk includes a copy of your dart code.  When launching from the homescreen we use that (likely old) copy of your dart code.  Subsequent `flutter run` calls upload a new copy of your dart, but don't place it inside the APK.  Your'e not the only one to be confused by this behavior.

CC @devoncarew @jason-simmons

**Comment by Hixie** [comment]
Atom -> WONTFIX

**Comment by eseidelGoogle** [comment]
This is unlikely to be an Atom specific issue.  But I agree we can/should close this and re-open if it's still occurring.

IntelliJ is now our main supported IDE, with the Atom Flutter plugin (still in use by many but) being community maintained.
