### ISSUE TITLE
Flutter Web (1.9+) + Docker -> Failure to launch

### ISSUE THREAD

**Issue by zeromaro** [flutter/flutter#42284]
Hello Flutter community,

I've a question regarding Flutter Web (1.9+) version and Docker.

### Problem
I get an error that `No devices found with name or id matching 'chrome'`.

### Background
Previously I was running Flutter (1.7+) on Docker via `webdev` and it used to work like a charm (`webdev serve --release`). 
Now I updated my Flutter to latest version (Web was merged into flutter master). And started to face issues while trying to deploy it on my server (`flutter run -d chrome --release`).

### Setup
My `Dockerfile` content.

```
<...>
RUN curl -L https://storage.googleapis.com/flutter_infra/releases/stable/linux/flutter_linux_v1.9.1+hotfix.4-stable.tar.xz | tar -C /opt -xJ

RUN apt-get install -y lib32stdc++6

WORKDIR ${PROJECT_DIR}
COPY ./ ./

RUN flutter channel master
RUN flutter upgrade
RUN flutter config --enable-web
RUN flutter doctor
```

`flutter doctor` output:
```
Flutter 1.10.15-pre.16 • channel master • https://github.com/flutter/flutter.git
Framework • revision 14c1c211d5 (3 hours ago) • 2019-10-08 14:53:55 -0700
Engine • revision c635d70c72
Tools • Dart 2.6.0 (build 2.6.0-dev.6.0 f4a72bfc64)
Running flutter doctor...
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel master, v1.10.15-pre.16, on Linux, locale en_US)
[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/setup/#android-setup for detailed instructions).
      If the Android SDK has been installed to a custom location, set ANDROID_HOME to that location.
      You may also want to add it to your PATH environment variable.
[!] Android Studio (not installed)
[!] Connected device
    ! No devices available
```
After running `flutter doctor` I can see my Flutter version is `1.10.15-pre.16` and I'm on `master`. However, I can also see 
```
[!] Connected device
    ! No devices available
```
Which is weird, because I should see Chrome as one of the devices?

Any help is appreciated!

**Comment by jonahwilliams** [comment]
What is the output of `flutter config` (with no arguments) ?

**Comment by zeromaro** [comment]
As discussed on other channels, here's the log for `flutter config`
```
Settings:
    enable-web: true
```

FYI docker runs on ubuntu:18.04.

**Comment by yjbanov** [comment]
How is Chrome installed in the docker image? We use [this method](https://github.com/flutter/flutter/blob/master/dev/ci/docker_linux/Dockerfile#L30-L63) in our CI and it runs successfully for us.

**Comment by zeromaro** [comment]
Sorry for late reply,
I tried installing chrome too, but it gives me same error.

Chrome installation as follows:
```
RUN curl https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb -o /chrome.deb
RUN apt-get install dpkg || RUN dpkg -i /chrome.deb || apt-get -f install
RUN rm /chrome.deb
```

**Comment by zeromaro** [comment]
Little update.
I've switched to Dev branch. Current version is `v1.10.14`.

`flutter doctor`

```
[✓] Flutter (Channel dev, v1.10.14, on Linux, locale en_US)
[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/setup/#android-setup for detailed instructions).
      If the Android SDK has been installed to a custom location, set ANDROID_HOME to that location.
      You may also want to add it to your PATH environment variable.
[✗] Chrome - develop for the web (Cannot find chrome executable at google-chrome)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.
[!] Android Studio (not installed)
[✓] Connected device (1 available)
! Doctor found issues in 3 categories.
```

`flutter devices`

```
1 connected device:
Headless Server • headless-server • web-javascript • Flutter Tools
```

Therefore I tried running now not on `chrome` but `headless-server`.
I tried running `flutter run -d headless-server`
Output
```
Downloading Web SDK...                                              1.5s
Running "flutter pub get" in api...                             
! flutter_web 0.0.0 from git https://github.com/flutter/flutter_web at c04fb5 in packages/flutter_web

! flutter_web_ui 0.0.0 from git https://github.com/flutter/flutter_web at c04fb5 in packages/flutter_web_ui
Running "flutter pub get" in api...                                35.5s
Launching lib/main.dart on Headless Server in release mode...
Building application for the web...                                68.5s
Attempting to connect to browser instance..                     
lib/main.dart is being served at http://localhost:5001/
Attempting to connect to browser instance..                         0.0s

👻 👻 👻 👻 👻 👻 👻 👻 👻 👻 👻 👻 👻 👻 👻 👻 👻 👻 👻 👻 
Warning: Flutter's support for building web applications is highly experimental.
For more information see https://github.com/flutter/flutter/issues/34082.
👻 👻 👻 👻 👻 👻 👻 👻 👻 👻 👻 👻 👻 👻 👻 👻 👻 👻 👻 👻 

🔥  To hot restart (and rebuild state), press "r" or "R".
For a more detailed help message, press "h". To quit, press "q".

Sending crash report to Google.
Crash report sent (report ID: 0988b583d4caec2c)
Oops; flutter has exited unexpectedly.
Crash report written to /srv/api/flutter_01.log;
please let us know at https://github.com/flutter/flutter/issues.
```

I was happy to see it working but it crashed a little while after.

I think it's getting better but still needs little help!

**Comment by yjbanov** [comment]
Wow, a tool crash is something different entirely. I can't help but think that there's something wrong with your OS image. From the crash report:

```
#0      Stdin.echoMode= (dart:io-patch/stdio_patch.dart:84:7)
#1      AnsiTerminal.singleCharMode= (package:flutter_tools/src/base/terminal.dart:162:15)
#2      TerminalHandler.setupTerminal (package:flutter_tools/src/resident_runner.dart:992:14)
```

I've seen this ages ago. I think this happens when you use certain terminals. @jonahwilliams does this ring a bell? Anything we can do about it?

As for the issue with the Chrome installation, I'd recommend checking manually that you are able to run `google-chrome`. If it's not in the `PATH` but is launchable, then perhaps setting `CHROME_EXECUTABLE` is the solution.

Currently I can't think of anything we can do in Flutter itself.

**Comment by zeromaro** [comment]
Please do let me know if you need any information about it.
I'm running on Google Cloud - `GNU/Linux 4.18.0-1015-gcp x86_64` OS.
Docker is under `ubuntu:18.04`.


I tried running `google-chrome` but it seems it's not possible.
```
tep 8/16 : RUN google-chrome
 ---> Running in e6fa19e6b1cc
/bin/sh: 1: google-chrome: not found
```

I actually tried installing chromium too - same outcome. Tried running without `--release` tag - still crashed.

Please do let me know if you need any additional info! Can't wait to have it fixed.

**Comment by zeromaro** [comment]
@yjbanov , is there anything I can do from my side to make it run?

**Comment by jonahwilliams** [comment]
Try patching in the PR https://github.com/flutter/flutter/pull/42892 and see if that helps

**Comment by zeromaro** [comment]
I had my hopes up! However.
After switching to your PR
```
tep 9/15 : RUN git clone https://github.com/jonahwilliams/flutter.git
 ---> Running in 4e5be304384c
Cloning into 'flutter'...
Checking out files: 100% (2916/2916), done.
Removing intermediate container 4e5be304384c
 ---> abb9555e809e
Step 10/15 : RUN cd flutter && git checkout ensure_terminal_available
 ---> Running in 81e27c19d136
Switched to a new branch 'ensure_terminal_available'
Branch 'ensure_terminal_available' set up to track remote branch 'ensure_terminal_available' from 'origin'.
```
I tried running same thing again.

Flutter doctor
```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, v1.9.1+hotfix.4, on Linux, locale en_US)
[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/setup/#android-setup for detailed instructions).
      If the Android SDK has been installed to a custom location, set ANDROID_HOME to that location.
      You may also want to add it to your PATH environment variable.
[!] Android Studio (not installed)
[!] Connected device
    ! No devices available
! Doctor found issues in 3 categories.
```
Of course it failed because I can't see any devices anymore again.
```
Unable to locate a development device; please run 'flutter doctor' for information about installing additional components.
```

🤨

**Comment by zeromaro** [comment]
😡🤬🤯
I had a mistake in Dockerfile for installation of google chrome - that's why it was not detected before.
Now I can run successfully on chrome. However, crash still happens.

Showing crash part in logs while running it in `release` mode.
```
rentmi-web-gateway-flutter | [        ] Building application for the web...
rentmi-web-gateway-flutter | [ +506 ms] Found plugin path_provider at /opt/flutter/.pub-cache/hosted/pub.dartlang.org/path_provider-1.4.0/
rentmi-web-gateway-flutter | [  +18 ms] Found plugin sqflite at /opt/flutter/.pub-cache/hosted/pub.dartlang.org/sqflite-1.1.7+1/
rentmi-web-gateway-flutter | [   +4 ms] Found plugin url_launcher at /opt/flutter/.pub-cache/hosted/pub.dartlang.org/url_launcher-5.2.3/
rentmi-web-gateway-flutter | [  +38 ms] Found plugin path_provider at /opt/flutter/.pub-cache/hosted/pub.dartlang.org/path_provider-1.4.0/
rentmi-web-gateway-flutter | [  +13 ms] Found plugin sqflite at /opt/flutter/.pub-cache/hosted/pub.dartlang.org/sqflite-1.1.7+1/
rentmi-web-gateway-flutter | [   +9 ms] Found plugin url_launcher at /opt/flutter/.pub-cache/hosted/pub.dartlang.org/url_launcher-5.2.3/
rentmi-web-gateway-flutter | [   +4 ms] Generating /srv/api/android/app/src/main/java/io/flutter/plugins/GeneratedPluginRegistrant.java
rentmi-web-gateway-flutter | [   +4 ms] Compiling lib/main.dart for the Web...
rentmi-web-gateway-flutter | [  +11 ms] Initializing file store
rentmi-web-gateway-flutter | [ +505 ms] web_entrypoint: Starting due to {InvalidedReason.inputChanged}
rentmi-web-gateway-flutter | [   +1 ms] web_entrypoint: Complete
rentmi-web-gateway-flutter | [+16753 ms] dart2js: Starting due to {InvalidedReason.inputChanged}
rentmi-web-gateway-flutter | [+51170 ms] dart2js: Complete
rentmi-web-gateway-flutter | [ +336 ms] web_release_bundle: Starting due to {InvalidedReason.inputChanged}
rentmi-web-gateway-flutter | [ +208 ms] web_release_bundle: Complete
rentmi-web-gateway-flutter | [ +205 ms] Persisting file store
rentmi-web-gateway-flutter | [  +64 ms] Done persisting file store
rentmi-web-gateway-flutter | [  +51 ms] Compiling lib/main.dart for the Web... (completed in 69.3s)
rentmi-web-gateway-flutter | [  +14 ms] Building application for the web... (completed in 69.9s)
rentmi-web-gateway-flutter | [        ] Attempting to connect to browser instance..
rentmi-web-gateway-flutter | [ +121 ms] Attempting to connect to browser instance.. (completed in 0.1s)
rentmi-web-gateway-flutter | [   +3 ms] "flutter run" took 116,271ms.
rentmi-web-gateway-flutter | Failed to build application for the web.
rentmi-web-gateway-flutter | 
rentmi-web-gateway-flutter | #0      throwToolExit (package:flutter_tools/src/base/common.dart:28:3)
rentmi-web-gateway-flutter | #1      ResidentWebRunner.run (package:flutter_tools/src/build_runner/resident_web_runner.dart:198:7)
rentmi-web-gateway-flutter | <asynchronous suspension>
rentmi-web-gateway-flutter | #2      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:481:37)
rentmi-web-gateway-flutter | <asynchronous suspension>
rentmi-web-gateway-flutter | #3      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:557:18)
rentmi-web-gateway-flutter | #4      _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:71:64)
rentmi-web-gateway-flutter | #5      _rootRunUnary (dart:async/zone.dart:1132:38)
rentmi-web-gateway-flutter | #6      _CustomZone.runUnary (dart:async/zone.dart:1029:19)
rentmi-web-gateway-flutter | #7      _FutureListener.handleValue (dart:async/future_impl.dart:137:18)
rentmi-web-gateway-flutter | #8      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:678:45)
rentmi-web-gateway-flutter | #9      Future._propagateToListeners (dart:async/future_impl.dart:707:32)
rentmi-web-gateway-flutter | #10     Future._completeWithValue (dart:async/future_impl.dart:522:5)
rentmi-web-gateway-flutter | #11     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:30:15)
rentmi-web-gateway-flutter | #12     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:288:13)
rentmi-web-gateway-flutter | #13     RunCommand.usageValues (package:flutter_tools/src/commands/run.dart)
rentmi-web-gateway-flutter | #14     _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:71:64)
rentmi-web-gateway-flutter | #15     _rootRunUnary (dart:async/zone.dart:1132:38)
rentmi-web-gateway-flutter | #16     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
rentmi-web-gateway-flutter | #17     _FutureListener.handleValue (dart:async/future_impl.dart:137:18)
rentmi-web-gateway-flutter | #18     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:678:45)
rentmi-web-gateway-flutter | #19     Future._propagateToListeners (dart:async/future_impl.dart:707:32)
rentmi-web-gateway-flutter | #20     Future._completeWithValue (dart:async/future_impl.dart:522:5)
rentmi-web-gateway-flutter | #21     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:30:15)
rentmi-web-gateway-flutter | #22     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:288:13)
rentmi-web-gateway-flutter | #23     IosProject.isSwift (package:flutter_tools/src/project.dart)
rentmi-web-gateway-flutter | #24     _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:71:64)
rentmi-web-gateway-flutter | #25     _rootRunUnary (dart:async/zone.dart:1132:38)
rentmi-web-gateway-flutter | #26     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
rentmi-web-gateway-flutter | #27     _FutureListener.handleValue (dart:async/future_impl.dart:137:18)
rentmi-web-gateway-flutter | #28     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:678:45)
rentmi-web-gateway-flutter | #29     Future._propagateToListeners (dart:async/future_impl.dart:707:32)
rentmi-web-gateway-flutter | #30     Future._completeWithValue (dart:async/future_impl.dart:522:5)
rentmi-web-gateway-flutter | #31     Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:552:7)
rentmi-web-gateway-flutter | #32     _rootRun (dart:async/zone.dart:1124:13)
rentmi-web-gateway-flutter | #33     _CustomZone.run (dart:async/zone.dart:1021:19)
rentmi-web-gateway-flutter | #34     _CustomZone.runGuarded (dart:async/zone.dart:923:7)
rentmi-web-gateway-flutter | #35     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:963:23)
rentmi-web-gateway-flutter | #36     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
rentmi-web-gateway-flutter | #37     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
rentmi-web-gateway-flutter | #38     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:116:13)
rentmi-web-gateway-flutter | #39     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:173:5)
rentmi-web-gateway-flutter | 
```

We are nearly there guys!

**Comment by zeromaro** [comment]
Do you have any further suggestions on this @jonahwilliams @yjbanov ?

**Comment by zeromaro** [comment]
It failed. While running `-d chrome`.  `Exception: Unable to connect to Chrome debug port: 54686`. However, I tried running `-d web` and **it worked**! Seems newer version of Flutter indeed solved the issue.

Thank you guys for help!
