### ISSUE TITLE
Not able to deploy app to phone

### ISSUE THREAD

**Issue by Ayush1325** [flutter/flutter#42327]
`Flutter crash report; please file at https://github.com/flutter/flutter/issues.

## command

flutter run

## exception

ProcessException: ProcessException: Permission denied
  Command: /mnt/work/Programming/Projects/RaspberryPiControl/ControllerApp/rpi_controller/android/gradlew -v

```
#0      runAsync (package:flutter_tools/src/base/process.dart:232:33)
<asynchronous suspension>
#1      runCheckedAsync (package:flutter_tools/src/base/process.dart:251:34)
<asynchronous suspension>
#2      _initializeGradle (package:flutter_tools/src/android/gradle.dart:300:9)
<asynchronous suspension>
#3      _ensureGradle (package:flutter_tools/src/android/gradle.dart:281:37)
<asynchronous suspension>
#4      _readGradleProject (package:flutter_tools/src/android/gradle.dart:192:31)
<asynchronous suspension>
#5      _gradleAppProject (package:flutter_tools/src/android/gradle.dart:112:37)
<asynchronous suspension>
#6      getGradleAppOut (package:flutter_tools/src/android/gradle.dart:106:29)
<asynchronous suspension>
#7      AndroidApk.fromAndroidProject (package:flutter_tools/src/application_package.dart:164:23)
<asynchronous suspension>
#8      ApplicationPackageFactory.getPackageForPlatform (package:flutter_tools/src/application_package.dart:46:32)
<asynchronous suspension>
#9      FlutterDevice.runHot (package:flutter_tools/src/resident_runner.dart:359:56)
<asynchronous suspension>
#10     HotRunner.run (package:flutter_tools/src/run_hot.dart:254:39)
<asynchronous suspension>
#11     RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:472:37)
<asynchronous suspension>
#12     FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:490:18)
#13     _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:71:64)
#14     _rootRunUnary (dart:async/zone.dart:1132:38)
#15     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#16     _FutureListener.handleValue (dart:async/future_impl.dart:137:18)
#17     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:678:45)
#18     Future._propagateToListeners (dart:async/future_impl.dart:707:32)
#19     Future._completeWithValue (dart:async/future_impl.dart:522:5)
#20     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:30:15)
#21     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:288:13)
#22     RunCommand.usageValues (package:flutter_tools/src/commands/run.dart)
#23     _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:71:64)
#24     _rootRunUnary (dart:async/zone.dart:1132:38)
#25     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#26     _FutureListener.handleValue (dart:async/future_impl.dart:137:18)
#27     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:678:45)
#28     Future._propagateToListeners (dart:async/future_impl.dart:707:32)
#29     Future._completeWithValue (dart:async/future_impl.dart:522:5)
#30     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:30:15)
#31     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:288:13)
#32     AndroidDevice.isLocalEmulator (package:flutter_tools/src/android/android_device.dart)
#33     _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:71:64)
#34     _rootRunUnary (dart:async/zone.dart:1132:38)
#35     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#36     _FutureListener.handleValue (dart:async/future_impl.dart:137:18)
#37     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:678:45)
#38     Future._propagateToListeners (dart:async/future_impl.dart:707:32)
#39     Future._completeWithValue (dart:async/future_impl.dart:522:5)
#40     Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:552:7)
#41     _rootRun (dart:async/zone.dart:1124:13)
#42     _CustomZone.run (dart:async/zone.dart:1021:19)
#43     _CustomZone.runGuarded (dart:async/zone.dart:923:7)
#44     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:963:23)
#45     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#46     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#47     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:116:13)
#48     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:173:5)
```

## flutter doctor

```
[32m[✓][39m Flutter (Channel stable, v1.9.1+hotfix.4, on Linux, locale en_IN.UTF-8)
    [32m•[39m Flutter version 1.9.1+hotfix.4 at /home/ayush/flutter
    [32m•[39m Framework revision cc949a8e8b (12 days ago), 2019-09-27 15:04:59 -0700
    [32m•[39m Engine revision b863200c37
    [32m•[39m Dart version 2.5.0

[32m[✓][39m Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    [32m•[39m Android SDK at /home/ayush/Android/Sdk
    [32m•[39m Android NDK location not configured (optional; useful for native profiling support)
    [32m•[39m Platform android-29, build-tools 29.0.2
    [32m•[39m Java binary at: /home/ayush/.local/share/JetBrains/Toolbox/apps/AndroidStudio/ch-0/191.5900203/jre/bin/java
    [32m•[39m Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    [32m•[39m All Android licenses accepted.

[32m[✓][39m Android Studio (version 3.5)
    [32m•[39m Android Studio at /home/ayush/.local/share/JetBrains/Toolbox/apps/AndroidStudio/ch-0/191.5900203
    [32m•[39m Flutter plugin version 40.1.2
    [32m•[39m Dart plugin version 191.8423
    [32m•[39m Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[33m[!][39m IntelliJ IDEA Ultimate Edition (version 2019.2)
    [32m•[39m IntelliJ at /home/ayush/.local/share/JetBrains/Toolbox/apps/IDEA-U/ch-0/192.6817.14
    [31m✗[39m Flutter plugin not installed; this adds Flutter specific functionality.
    [31m✗[39m Dart plugin not installed; this adds Dart specific functionality.
    [32m•[39m For information about installing plugins, see
      https://flutter.dev/intellij-setup/#installing-the-plugins

[32m[✓][39m Connected device (1 available)
    [32m•[39m XT1686 • ZY223XN2V7 • android-arm64 • Android 9 (API 28)

[33m![39m Doctor found issues in 1 category.
```
`

**Comment by iapicca** [comment]
Hi @Ayush1325 
to better address the issue, would be helpful
if you could post a self contained app on github
or the steps to reproduce it.
Thank you

**Comment by Ayush1325** [comment]
> Hi @Ayush1325
> to better address the issue, would be helpful
> if you could post a self contained app on github
> or the steps to reproduce it.
> Thank you

Well, it's the app that is autogenerated by flutter. Haven't changed a word.

**Comment by Ayush1325** [comment]
Ok, the porblem was with the mount permissions of my external partition.
Set `umask=0022` in fstab
