### ISSUE TITLE
When internationalization is supported, the cursor and input field of TextFormField cannot be aligned

### ISSUE THREAD

**Issue by vvkkhjt** [flutter/flutter#42324]
## Steps to Reproduce

1. set supportedLocales
2. add const Locale('zh','CH')
3. problem

**Target Platform:** Android
**Target OS version/browser:** 9
**Devices:** GM1910

## Code
```dart

@override
  Widget build(BuildContext context) {
    return StoreProvider<AppState>(
      store: AppConfig.of(context).store,
      child: MaterialApp(
        home: SplashPage(),
        routes: <String, WidgetBuilder>{
          '/HomeScreen': (BuildContext context) => firstTime ? One() : LoginComponent()
        },
        localizationsDelegates: [
          GlobalMaterialLocalizations.delegate,
          GlobalWidgetsLocalizations.delegate
        ],
        supportedLocales: [
          const Locale('en','US'),
          const Locale('zh','CH'),
        ],
        theme: ThemeData(
          platform: TargetPlatform.android,
        ),
      ),
    );
  }
```

## Results
1,support Locale('zh','CH')
![TIM图片20191009210159](https://user-images.githubusercontent.com/12765476/66483651-16ed5980-ead8-11e9-87a4-162ff047d6d2.jpg)

2,not support Locale('zh','CH')
![TIM图片20191009210204](https://user-images.githubusercontent.com/12765476/66483654-181e8680-ead8-11e9-84a7-1c7972a102c5.jpg)

## Question
Is that a Bug?

## Logs

```
[  +28 ms] executing: [G:\flutter\] git log -n 1 --pretty=format:%H
[  +52 ms] Exit code 0 from: git log -n 1 --pretty=format:%H
[        ] cc949a8e8b9cf394b9290a8e80f87af3e207dce5
[        ] executing: [G:\flutter\] git describe --match v*.*.* --first-parent --long --tags
[  +25 ms] Exit code 0 from: git describe --match v*.*.* --first-parent --long --tags
[        ] v1.9.1+hotfix.4-0-gcc949a8e8
[   +8 ms] executing: [G:\flutter\] git rev-parse --abbrev-ref --symbolic @{u}
[  +25 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/stable
[        ] executing: [G:\flutter\] git ls-remote --get-url origin
[  +22 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[  +60 ms] executing: [G:\flutter\] git rev-parse --abbrev-ref HEAD
[  +21 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] stable
[  +32 ms] "flutter run" took 49ms.
Target file "lib\main.dart" not found.

#0      FlutterCommand.validateCommand (package:flutter_tools/src/runner/flutter_command.dart:586:9)
<asynchronous suspension>
#1      RunCommand.validateCommand (package:flutter_tools/src/commands/run.dart:278:19)
<asynchronous suspension>
#2      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:465:11)
<asynchronous suspension>
#3      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:407:33)
<asynchronous suspension>
#4      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:154:29)
<asynchronous suspension>
#5      _rootRun (dart:async/zone.dart:1124:13)
#6      _CustomZone.run (dart:async/zone.dart:1021:19)
#7      _runZoned (dart:async/zone.dart:1516:10)
#8      runZoned (dart:async/zone.dart:1463:12)
#9      AppContext.run (package:flutter_tools/src/base/context.dart:153:18)
<asynchronous suspension>
#10     FlutterCommand.run (package:flutter_tools/src/runner/flutter_command.dart:397:20)
#11     CommandRunner.runCommand (package:args/command_runner.dart:197:27)
<asynchronous suspension>
#12     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:402:21)
<asynchronous suspension>
#13     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:154:29)
<asynchronous suspension>
#14     _rootRun (dart:async/zone.dart:1124:13)
#15     _CustomZone.run (dart:async/zone.dart:1021:19)
#16     _runZoned (dart:async/zone.dart:1516:10)
#17     runZoned (dart:async/zone.dart:1463:12)
#18     AppContext.run (package:flutter_tools/src/base/context.dart:153:18)
<asynchronous suspension>
#19     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:356:19)
<asynchronous suspension>
#20     CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:112:25)
#21     new Future.sync (dart:async/future.dart:224:31)
#22     CommandRunner.run (package:args/command_runner.dart:112:14)
#23     FlutterCommandRunner.run (package:flutter_tools/src/runner/flutter_command_runner.dart:242:18)
#24     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:63:22)
<asynchronous suspension>
#25     _rootRun (dart:async/zone.dart:1124:13)
#26     _CustomZone.run (dart:async/zone.dart:1021:19)
#27     _runZoned (dart:async/zone.dart:1516:10)
#28     runZoned (dart:async/zone.dart:1500:12)
#29     run.<anonymous closure> (package:flutter_tools/runner.dart:61:18)
<asynchronous suspension>
#30     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:154:29)
<asynchronous suspension>
#31     _rootRun (dart:async/zone.dart:1124:13)
#32     _CustomZone.run (dart:async/zone.dart:1021:19)
#33     _runZoned (dart:async/zone.dart:1516:10)
#34     runZoned (dart:async/zone.dart:1463:12)
#35     AppContext.run (package:flutter_tools/src/base/context.dart:153:18)
<asynchronous suspension>
#36     runInContext (package:flutter_tools/src/context_runner.dart:59:24)
<asynchronous suspension>
#37     run (package:flutter_tools/runner.dart:50:10)
#38     main (package:flutter_tools/executable.dart:65:9)
<asynchronous suspension>
#39     main (file:///C:/b/s/w/ir/k/archive/flutter/packages/flutter_tools/bin/flutter_tools.dart:8:3)
#40     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:303:32)
#41     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:12)
```

```
None
```

```
[√] Flutter (Channel stable, v1.9.1+hotfix.4, on Microsoft Windows [Version 10.0.16299.371], locale zh-CN)
    • Flutter version 1.9.1+hotfix.4 at G:\flutter
    • Framework revision cc949a8e8b (12 days ago), 2019-09-27 15:04:59 -0700
    • Engine revision b863200c37
    • Dart version 2.5.0


[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at D:\Android\Sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = D:\Android\Sdk
    • Java binary at: C:\Program Files\Android\Android Studio1\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)
    • All Android licenses accepted.

[√] Android Studio (version 3.3)
    • Android Studio at C:\Program Files\Android\Android Studio1
    • Flutter plugin version 33.4.1
    • Dart plugin version 182.5215
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)

[√] IntelliJ IDEA Ultimate Edition (version 2018.2)
    • IntelliJ at G:\IntelliJ IDEA 2018.2.1
    • Flutter plugin version 31.3.2
    • Dart plugin version 182.3911.37

[√] Connected device (1 available)
    • GM1910 • 3cb359ef • android-arm64 • Android 9 (API 28)

• No issues found!
```

**Comment by missXb** [comment]
Hello, I have encountered a similar problem. Can you solve it?

**Comment by vvkkhjt** [comment]
@missXb no i cant solve it, wait flutter offcial callback

**Comment by missXb** [comment]
> @missXb no i cant solve it, wait flutter offcial callback

ok，But I have to find a way to solve this problem, the project is waiting to go online.

**Comment by vvkkhjt** [comment]
@missXb can you tell me ,how to solve it?

**Comment by missXb** [comment]
> @missXb can you tell me ,how to solve it?
I haven't found a method yet, but I think I have found the reason for the problem because "GlobalWidgetsLocalizations.delegate" and "GlobalMaterialLocalizations.delegate" cause this problem. I wonder if I can add these two delegates to achieve international chemical.

**Comment by missXb** [comment]
> @missXb can you tell me ,how to solve it?

I haven't found a method yet, but I think I have found the reason for the problem because "GlobalWidgetsLocalizations.delegate" and "GlobalMaterialLocalizations.delegate" cause this problem. I wonder if I can not adding these two delegates to achieve international chemical.

**Comment by vvkkhjt** [comment]
> > @missXb can you tell me ,how to solve it?
> 
> I haven't found a method yet, but I think I have found the reason for the problem because "GlobalWidgetsLocalizations.delegate" and "GlobalMaterialLocalizations.delegate" cause this problem. I wonder if I can not adding these two delegates to achieve international chemical.

I delete "Locale('zh','CH')" yet.

**Comment by missXb** [comment]
> > > @missXb can you tell me ,how to solve it?
> > 
> > 
> > I haven't found a method yet, but I think I have found the reason for the problem because "GlobalWidgetsLocalizations.delegate" and "GlobalMaterialLocalizations.delegate" cause this problem. I wonder if I can not adding these two delegates to achieve international chemical.
> 
> I delete "Locale('zh','CH')" yet.

You are correct, but this way the initial locale can't be set.

**Comment by vvkkhjt** [comment]
> > > > @missXb can you tell me ,how to solve it?
> > > 
> > > 
> > > I haven't found a method yet, but I think I have found the reason for the problem because "GlobalWidgetsLocalizations.delegate" and "GlobalMaterialLocalizations.delegate" cause this problem. I wonder if I can not adding these two delegates to achieve international chemical.
> > 
> > 
> > I delete "Locale('zh','CH')" yet.
> 
> You are correct, but this way the initial locale can't be set.

just for now.

**Comment by TahaTesser** [comment]
Hi @vvkkhjt 
Are you still experiencing this issue with latest `stable` channel?
If yes, can you please provide your `flutter doctor -v` and `flutter run --verbose`? 
Also, to better address the issue, would be helpful if you could post a minimal code sample to reproduce the problem
Thank you

**Comment by vvkkhjt** [comment]
@TahaTesser its already repair,thks.
