### ISSUE TITLE
BackgroundTask failure iOS causes bad state

### ISSUE THREAD

**Issue by EPNW** [flutter/flutter#42323]
If I minimize my app on iOS and open it up again I get several problems with `BackgroundTask`.
As a result, my widgets seem to be in a bad state, for example flutter complains I'm evaluating on a null-boolean, which should have been initalized in the initState method of the widget.
This problem started to appear two weeks ago or so, before that everything worked fine.
Also, the problem does not appear on Android

**Target Platform: iOS**
**Target OS version/browser: 13.1.2, 12.4.1**
**Devices: iPhone X, iPhone 7**

## Logs

```
2019-10-06 19:52:47.651095+0200 Runner[2731:767028] Metal API Validation Enabled
2019-10-06 19:52:47.864435+0200 Runner[2731:767206] flutter: Observatory listening on http://127.0.0.1:54370/kCNYYQ2aYWc=/
2019-10-06 19:52:59.780227+0200 Runner[2731:767028] Can't end BackgroundTask: no background task exists with identifier 2 (0x2), or it may have already been ended. Break in UIApplicationEndBackgroundTaskError() to debug.
2019-10-06 19:53:11.932669+0200 Runner[2731:767028] Can't end BackgroundTask: no background task exists with identifier 7 (0x7), or it may have already been ended. Break in UIApplicationEndBackgroundTaskError() to debug.
2019-10-06 19:53:24.836118+0200 Runner[2731:767028] Can't end BackgroundTask: no background task exists with identifier 12 (0xc), or it may have already been ended. Break in UIApplicationEndBackgroundTaskError() to debug.
2019-10-06 19:53:46.469472+0200 Runner[2731:767193] flutter: ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
2019-10-06 19:53:46.469668+0200 Runner[2731:767193] flutter: The following NoSuchMethodError was thrown building ShorttestPage(dirty, dependencies:
2019-10-06 19:53:46.469716+0200 Runner[2731:767193] flutter: [_LocalizationsScope-[GlobalKey#62374], InheritedTheme], state: ShorttestPageState#6d65c(tickers:
2019-10-06 19:53:46.469749+0200 Runner[2731:767193] flutter: tracking 1 ticker)):
2019-10-06 19:53:46.469779+0200 Runner[2731:767193] flutter: The method '_subFromInteger' was called on null.
2019-10-06 19:53:46.469805+0200 Runner[2731:767193] flutter: Receiver: null
2019-10-06 19:53:46.469831+0200 Runner[2731:767193] flutter: Tried calling: _subFromInteger(0)
2019-10-06 19:53:46.469857+0200 Runner[2731:767193] flutter:
2019-10-06 19:53:46.470088+0200 Runner[2731:767193] flutter: User-created ancestor of the error-causing widget was:
2019-10-06 19:53:46.470348+0200 Runner[2731:767193] flutter:   MaterialApp file:///Users/Nils/Documents/GITRepositories/EPNW/ert_shorttest_app/lib/main.dart:45:16
2019-10-06 19:53:46.470541+0200 Runner[2731:767193] flutter:
2019-10-06 19:53:46.470670+0200 Runner[2731:767193] flutter: When the exception was thrown, this was the stack:
2019-10-06 19:53:46.470784+0200 Runner[2731:767193] flutter: #0      Object.noSuchMethod (dart:core-patch/object_patch.dart:51:5)
2019-10-06 19:53:46.470943+0200 Runner[2731:767193] flutter: #1      int.- (dart:core-patch/integers.dart:13:38)
2019-10-06 19:53:46.471102+0200 Runner[2731:767193] flutter: #2      ShorttestController.forAnimating (package:ert_shorttest_app/framework/shorttest_controller.dart:140:33)
2019-10-06 19:53:46.471219+0200 Runner[2731:767193] flutter: #3      _ShorttestPageState.build (package:ert_shorttest_app/framework/shorttest_page.dart:110:46)
2019-10-06 19:53:46.471379+0200 Runner[2731:767193] flutter: #4      StatefulElement.build (package:flutter/src/widgets/framework.dart:4064:27)
2019-10-06 19:53:46.471525+0200 Runner[2731:767193] flutter: #5      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3958:15)
2019-10-06 19:53:46.471676+0200 Runner[2731:767193] flutter: #6      Element.rebuild (package:flutter/src/widgets/framework.dart:3755:5)
2019-10-06 19:53:46.471789+0200 Runner[2731:767193] flutter: #7      BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2347:33)
2019-10-06 19:53:46.471954+0200 Runner[2731:767193] flutter: #8      WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:776:20)
2019-10-06 19:53:46.472006+0200 Runner[2731:767193] flutter: #9      RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:283:5)
2019-10-06 19:53:46.472049+0200 Runner[2731:767193] flutter: #10     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1043:15)
2019-10-06 19:53:46.472114+0200 Runner[2731:767193] flutter: #11     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:982:9)
2019-10-06 19:53:46.472174+0200 Runner[2731:767193] flutter: #12     SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:898:5)
2019-10-06 19:53:46.472205+0200 Runner[2731:767193] flutter: #16     _invoke (dart:ui/hooks.dart:259:10)
2019-10-06 19:53:46.472266+0200 Runner[2731:767193] flutter: #17     _drawFrame (dart:ui/hooks.dart:217:3)
2019-10-06 19:53:46.472296+0200 Runner[2731:767193] flutter: (elided 3 frames from package dart:async)
2019-10-06 19:53:46.472338+0200 Runner[2731:767193] flutter:
2019-10-06 19:53:46.472407+0200 Runner[2731:767193] flutter: ════════════════════════════════════════════════════════════════════════════════════════════════════
```

```
info • Unnecessary cast • include/epnw_about_page/lib/epnw_about_page.dart:101:23 • unnecessary_cast
  error • Undefined name 'required' used as an annotation • include/epnw_about_page/lib/epnw_about_page.dart:175:7 • undefined_annotation
  error • Target of URI doesn't exist: 'package:shared_preferences/shared_preferences.dart' •
         include/extended_shared_preferences/lib/extended_shared_preferences.dart:2:8 • uri_does_not_exist
   info • Method doesn't override an inherited method • include/extended_shared_preferences/lib/extended_shared_preferences.dart:28:16 •
          override_on_non_overriding_method
   info • Method doesn't override an inherited method • include/extended_shared_preferences/lib/extended_shared_preferences.dart:34:16 •
          override_on_non_overriding_method
   info • Method doesn't override an inherited method • include/extended_shared_preferences/lib/extended_shared_preferences.dart:39:8 •
          override_on_non_overriding_method
   info • Method doesn't override an inherited method • include/extended_shared_preferences/lib/extended_shared_preferences.dart:44:3 •
          override_on_non_overriding_method
   info • Method doesn't override an inherited method • include/extended_shared_preferences/lib/extended_shared_preferences.dart:49:8 •
          override_on_non_overriding_method
   info • Method doesn't override an inherited method • include/extended_shared_preferences/lib/extended_shared_preferences.dart:54:10 •
          override_on_non_overriding_method
   info • Method doesn't override an inherited method • include/extended_shared_preferences/lib/extended_shared_preferences.dart:59:7 •
          override_on_non_overriding_method
   info • Method doesn't override an inherited method • include/extended_shared_preferences/lib/extended_shared_preferences.dart:64:15 •
          override_on_non_overriding_method
   info • Method doesn't override an inherited method • include/extended_shared_preferences/lib/extended_shared_preferences.dart:69:10 •
          override_on_non_overriding_method
   info • Method doesn't override an inherited method • include/extended_shared_preferences/lib/extended_shared_preferences.dart:74:16 •
          override_on_non_overriding_method
   info • Method doesn't override an inherited method • include/extended_shared_preferences/lib/extended_shared_preferences.dart:79:16 •
          override_on_non_overriding_method
   info • Method doesn't override an inherited method • include/extended_shared_preferences/lib/extended_shared_preferences.dart:82:16 •
          override_on_non_overriding_method
   info • Method doesn't override an inherited method • include/extended_shared_preferences/lib/extended_shared_preferences.dart:88:16 •
          override_on_non_overriding_method
   info • Method doesn't override an inherited method • include/extended_shared_preferences/lib/extended_shared_preferences.dart:93:16 •
          override_on_non_overriding_method
   info • Method doesn't override an inherited method • include/extended_shared_preferences/lib/extended_shared_preferences.dart:98:16 •
          override_on_non_overriding_method
   info • Method doesn't override an inherited method • include/extended_shared_preferences/lib/extended_shared_preferences.dart:103:16 •
          override_on_non_overriding_method
   info • Method doesn't override an inherited method • include/extended_shared_preferences/lib/extended_shared_preferences.dart:108:16 •
          override_on_non_overriding_method
   info • The declaration '_onlyForward' isn't referenced • include/math_text/lib/src/parser.dart:113:6 • unused_element
   info • 'ButtonTheme.bar' is deprecated and shouldn't be used • lib/borderlessdialog.dart:120:20 • deprecated_member_use
   info • Don't explicitly initialize variables to null • lib/ertshorttestlocalizationshelper.dart:48:30 • avoid_init_to_null
   info • Don't import implementation files from another package • lib/framework/shorttest_container.dart:7:8 • implementation_imports
   info • This method overrides a method annotated as @mustCallSuper in 'AutomaticKeepAliveClientMixin', but doesn't invoke the overridden
          method • lib/homepage.dart:333:10 • must_call_super
   info • The exception variable 'e' isn't used, so the 'catch' clause can be removed • lib/refresh_dialog.dart:80:27 • unused_catch_clause
   info • Avoid using braces in interpolation when not needed • scripts/LocalizationsReader.dart:14:25 • unnecessary_brace_in_string_interps
   info • Avoid using braces in interpolation when not needed • scripts/LocalizationsReader.dart:32:7 • unnecessary_brace_in_string_interps
   info • Avoid using braces in interpolation when not needed • scripts/LocalizationsReader.dart:36:10 • unnecessary_brace_in_string_interps
   info • Avoid using braces in interpolation when not needed • scripts/LocalizationsReader.dart:37:29 • unnecessary_brace_in_string_interps
   info • Avoid using braces in interpolation when not needed • scripts/LocalizationsReader.dart:37:53 • unnecessary_brace_in_string_interps
   info • Avoid using braces in interpolation when not needed • scripts/LocalizationsReader.dart:42:10 • unnecessary_brace_in_string_interps
   info • Avoid using braces in interpolation when not needed • scripts/LocalizationsReader.dart:49:59 • unnecessary_brace_in_string_interps
   info • Avoid using braces in interpolation when not needed • scripts/LocalizationsReader.dart:53:38 • unnecessary_brace_in_string_interps
   info • Avoid using braces in interpolation when not needed • scripts/LocalizationsReader.dart:56:10 • unnecessary_brace_in_string_interps
   info • Avoid using braces in interpolation when not needed • scripts/LocalizationsReader.dart:57:34 • unnecessary_brace_in_string_interps
   info • Avoid using braces in interpolation when not needed • scripts/LocalizationsReader.dart:57:53 • unnecessary_brace_in_string_interps
```

```
flutter doctor -v
[✓] Flutter (Channel dev, v1.10.14, on Mac OS X 10.14.6 18G103, locale de-DE)
    • Flutter version 1.10.14 at /Users/Nils/development/flutter
    • Framework revision 1946fc4da0 (2 days ago), 2019-10-07 15:23:31 -0700
    • Engine revision 1d62160fdb
    • Dart version 2.6.0 (build 2.6.0-dev.1.0 d6c6d12ebf)

[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/setup/#android-setup for detailed instructions).
      If the Android SDK has been installed to a custom location, set ANDROID_HOME to that location.
      You may also want to add it to your PATH environment variable.


[✓] Xcode - develop for iOS and macOS (Xcode 11.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.1, Build version 11A1027
    • CocoaPods version 1.7.4

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/setup/#android-setup for detailed instructions).

[✓] VS Code (version 1.38.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.5.1

[!] Connected device
    ! No devices available

! Doctor found issues in 3 categories.
```

**Comment by iapicca** [comment]
Hi @EPNW 
tobetter address the issue, would be helpful
if you could post a self contained app on github
or the steps to reproduce it.
Thank you

**Comment by rodrigocanepa** [comment]
Same problem here, the notifications from FCM are not working well when the app is in background and only I can receive the notification when the app is in foreground, did you resolve this problem?

**Comment by janmoppel** [comment]
Hello @EPNW !

Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the issue, if you have any more information for us; we will reopen it right away!

Thank you for your contribution.

P.S. If anyone still experience the same problem, please file a new issue with the information required in the template.
All system setups can be slightly different so it’s always better to open new issues and reference related issues.
