### ISSUE TITLE
app release

### ISSUE THREAD

**Issue by mahmooooud** [flutter/flutter#42329]
when i release app on google play store 
there is a limit device can download app 3376 device 
when i use 'flutter build appbundle --release --target-platform=android-arm64' or 'flutter build apk --release --target-platform=android-arm64'
the number inceress to 11360 device but this version crash

**Comment by BondarenkoStas** [comment]
@mahmooooud In which way it crashes? Can you provide any logs?

**Comment by mahmooooud** [comment]
crash when open app 


2019-10-10 10:19:33.082 1810-3715/? E/NetworkStatsNative: [1058483] iface is wlan0, use elder API for tcp packets.
2019-10-10 10:19:33.082 1810-3715/? E/NetworkStatsNative: [1058483] iface is wlan0, use elder API for tcp packets.
2019-10-10 10:19:34.681 785-828/? E/ANDR-PERF-MPCTL: Invalid profile no. 0, total profiles 0 only
2019-10-10 10:19:34.683 1810-5035/? E/ANDR-PERF-JNI: Iop tryGetService failed
2019-10-10 10:19:34.686 785-828/? E/ANDR-PERF-OPTSHANDLER: Perflock resource /sys/class/devfreq/soc:qcom,llccbw/min_freq not supported
2019-10-10 10:19:34.686 785-828/? E/ANDR-PERF-RESOURCEQS: Failed to apply optimization [12, 0]
2019-10-10 10:19:34.791 20440-20440/? E/ider.anamehani: Not starting debugger since process cannot load the jdwp agent.
2019-10-10 10:19:34.861 9866-9866/? E/PhoneState: iconId is 0android.widget.ImageView{a4ec5b6 G.ED..... ......I. 0,0-15,42 #7f0a0119 app:id/data_inout}
2019-10-10 10:19:34.862 9866-9866/? E/PhoneState: iconId is 0android.widget.ImageView{3c5998d G.ED..... ......I. 0,0-0,0 #7f0a0119 app:id/data_inout}
2019-10-10 10:19:35.029 20482-20482/? E/facebook.katan: Not starting debugger since process cannot load the jdwp agent.
2019-10-10 10:19:35.083 1810-3715/? E/NetworkStatsNative: [1058483] iface is wlan0, use elder API for tcp packets.
2019-10-10 10:19:35.083 1810-3715/? E/NetworkStatsNative: [1058483] iface is wlan0, use elder API for tcp packets.
2019-10-10 10:19:35.134 20440-20440/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.anaprovider.anamehani2, PID: 20440
    java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/system/framework/org.apache.http.legacy.boot.jar", zip file "/data/app/com.anaprovider.anamehani2-SzdNbeqrKNeWQF6qkrTqeg==/base.apk"],nativeLibraryDirectories=[/data/app/com.anaprovider.anamehani2-SzdNbeqrKNeWQF6qkrTqeg==/lib/arm64, /system/lib64]]] couldn't find "libflutter.so"
        at java.lang.Runtime.loadLibrary0(Runtime.java:1012)
        at java.lang.System.loadLibrary(System.java:1669)
        at io.flutter.view.FlutterMain.startInitialization(FlutterMain.java:156)
        at io.flutter.view.FlutterMain.startInitialization(FlutterMain.java:133)
        at io.flutter.app.FlutterApplication.onCreate(FlutterApplication.java:22)
        at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1155)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6291)
        at android.app.ActivityThread.access$1400(ActivityThread.java:219)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1835)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:227)
        at android.app.ActivityThread.main(ActivityThread.java:7199)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:575)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:903)
2019-10-10 10:19:35.271 9866-9866/? E/PhoneState: iconId is 0android.widget.ImageView{a4ec5b6 G.ED..... ......I. 0,0-15,42 #7f0a0119 app:id/data_inout}
2019-10-10 10:19:35.271 9866-9866/? E/PhoneState: iconId is 0android.widget.ImageView{3c5998d G.ED..... ......I. 0,0-0,0 #7f0a0119 app:id/data_inout}
2019-10-10 10:19:35.655 20482-20482/? E/ACRA: Initializing ANR detector for process: com.facebook.katana
2019-10-10 10:19:35.802 1212-1212/? E/OPPO_KEVENT_RECORD: oppo_kevent Receive message from kernel, event_type=3
2019-10-10 10:19:35.802 1212-1212/? E/OPPO_KEVENT_RECORD: OPPO_KEVENT payload:10154,path@@/data/data/com.facebook.katana/lib-xzs/libwatcher_binary.so
2019-10-10 10:19:35.817 20482-20482/? E/dalvik-internals: attempting to hook OatFileManager::HasCollisions
2019-10-10 10:19:35.818 20482-20482/? E/dalvik-internals: attempting to hook OatFileAssistant::IsUpToDate
2019-10-10 10:19:35.819 20482-20482/? E/dalvik-internals: attempting to hook OatFileAssistant::IsUpToDate
2019-10-10 10:19:35.821 20482-20482/? E/dalvik-internals: could not hook _ZN3art16OatFileAssistant17OatFileIsUpToDateEv
2019-10-10 10:19:35.821 20482-20482/? E/dalvik-internals: attempting to hook OatFileAssistant::IsUpToDate
2019-10-10 10:19:35.823 20482-20482/? E/dalvik-internals: could not hook _ZN3art16OatFileAssistant18OdexFileIsUpToDateEv
2019-10-10 10:19:35.823 20482-20482/? E/dalvik-internals: attempting to hook OatFileAssistant::IsUpToDate
2019-10-10 10:19:35.825 20482-20482/? E/dalvik-internals: could not hook _ZN3art16OatFileAssistant22GivenOatFileIsUpToDateERKNS_7OatFileE
2019-10-10 10:19:36.174 20482-20482/? E/dalvik-internals: skipping IsUpToDate check for incoming dex file
2019-10-10 10:19:36.259 16743-16756/? E/ProfiloMultiProcessTraceListenerImpl: UID of caller is different from UID of listener
2019-10-10 10:19:36.474 26759-27014/? E/Parcel: Reading a NULL string not supported here.
2019-10-10 10:19:36.474 26759-27156/? E/Parcel: Reading a NULL string not supported here.
2019-10-10 10:19:36.489 26759-27156/? E/Parcel: Reading a NULL string not supported here.
2019-10-10 10:19:36.493 26759-27014/? E/Parcel: Reading a NULL string not supported here.
2019-10-10 10:19:36.496 26759-27014/? E/Parcel: Reading a NULL string not supported here.
2019-10-10 10:19:36.548 20482-20562/? E/fb4a.FbTrafficStats: Unable to parse data usage from system file
    X.2ET: java.io.FileNotFoundException: /proc/net/xt_qtaguid/stats (Permission denied)
        at X.10K.A00(:235)
        at X.12F.A04(:32)
        at X.12G.run(:10)
        at X.0bc.run(:2)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at X.0bi.run(:3)
        at X.0bj.run(:12)
        at java.lang.Thread.run(Thread.java:764)
     Caused by: java.io.FileNotFoundException: /proc/net/xt_qtaguid/stats (Permission denied)
        at java.io.FileInputStream.open0(Native Method)
        at java.io.FileInputStream.open(FileInputStream.java:231)
        at java.io.FileInputStream.<init>(FileInputStream.java:165)
        at X.10K.A00(:16)
        at X.12F.A04(:32) 
        at X.12G.run(:10) 
        at X.0bc.run(:2) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) 
        at X.0bi.run(:3) 
        at X.0bj.run(:12) 
        at java.lang.Thread.run(Thread.java:764) 
2019-10-10 10:19:36.548 20482-20562/? E/fb4a.FbTrafficStats: Unable to parse data usage from system file
    X.2ET: java.io.FileNotFoundException: /proc/net/xt_qtaguid/stats (Permission denied)
        at X.10K.A00(:235)
        at X.12F.A04(:55)
        at X.12G.run(:10)
        at X.0bc.run(:2)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at X.0bi.run(:3)
        at X.0bj.run(:12)
        at java.lang.Thread.run(Thread.java:764)
     Caused by: java.io.FileNotFoundException: /proc/net/xt_qtaguid/stats (Permission denied)
        at java.io.FileInputStream.open0(Native Method)
        at java.io.FileInputStream.open(FileInputStream.java:231)
        at java.io.FileInputStream.<init>(FileInputStream.java:165)
        at X.10K.A00(:16)
        at X.12F.A04(:55) 
        at X.12G.run(:10) 
        at X.0bc.run(:2) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) 
        at X.0bi.run(:3) 
        at X.0bj.run(:12) 
        at java.lang.Thread.run(Thread.java:764) 
2019-10-10 10:19:36.743 20482-20562/? E/CompactDiskManagerImpl.cpp: Failed to remove new folder structure directories: No such file or directory
2019-10-10 10:19:36.839 20482-20563/? E/Parcel: Reading a NULL string not supported here.
2019-10-10 10:19:36.851 20482-20563/? E/Parcel: Reading a NULL string not supported here.
2019-10-10 10:19:37.084 1810-3715/? E/NetworkStatsNative: [1058483] iface is wlan0, use elder API for tcp packets.
2019-10-10 10:19:37.085 1810-3715/? E/NetworkStatsNative: [1058483] iface is wlan0, use elder API for tcp packets.
2019-10-10 10:19:37.279 20482-20560/? E/MobileConfigAdapter.cpp: MobileConfigAdapter: create path: /data/user/0/com.facebook.katana/files/mobileconfig/componentscript
2019-10-10 10:19:37.350 20482-20560/? E/MobileConfigAdapter.cpp: [MobileConfigAdapter] Attempted to get a value before initial fetch is complete, you might get the default value instead. with name: qe_marketplace_lazy_fetch_pdp_universe:lazy_fetch_pdp
2019-10-10 10:19:37.374 20482-20482/? E/Parcel: Reading a NULL string not supported here.
2019-10-10 10:19:37.382 20482-20482/? E/Parcel: Reading a NULL string not supported here.
2019-10-10 10:19:37.395 20482-20548/? E/CheckPermission: _bluetooth code = 1 
2019-10-10 10:19:37.398 20482-20548/? E/fb4a.PassiveBleCollector: Couldn't start passive BLE scanning
    X.3FU: Ble scan error: USER_DISABLED
        at X.3ES.A00(:29)
        at X.3ES.BdM(:4)
        at X.3Eq.A00(:4)
        at X.I7X.run(:435)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:227)
        at android.os.HandlerThread.run(HandlerThread.java:65)
        at X.0YQ.run(:0)
2019-10-10 10:19:37.503 20482-20482/? E/Parcel: Reading a NULL string not supported here.
2019-10-10 10:19:37.510 20482-20482/? E/Parcel: Reading a NULL string not supported here.
2019-10-10 10:19:37.645 20622-20622/? E/book.appmanage: Not starting debugger since process cannot load the jdwp agent.
2019-10-10 10:19:37.814 20622-20622/? E/ACRA: Initializing ANR detector for process: com.facebook.appmanager
2019-10-10 10:19:37.843 20622-20622/? E/SQLiteLog: (14) cannot open file at line 36667 of [c255889bd9]
2019-10-10 10:19:37.843 20622-20622/? E/SQLiteLog: (14) os_unix.c:36667: (2) open(/data/user/0/com.facebook.appmanager/databases/androidx.work.workdb) - 
2019-10-10 10:19:37.844 20622-20622/? E/SQLiteDatabase: Failed to open database '/data/user/0/com.facebook.appmanager/databases/androidx.work.workdb'.
    android.database.sqlite.SQLiteCantOpenDatabaseException: unknown error (code 14 SQLITE_CANTOPEN): Could not open database
        at android.database.sqlite.SQLiteConnection.nativeOpen(Native Method)
        at android.database.sqlite.SQLiteConnection.open(SQLiteConnection.java:211)
        at android.database.sqlite.SQLiteConnection.open(SQLiteConnection.java:195)
        at android.database.sqlite.SQLiteConnectionPool.openConnectionLocked(SQLiteConnectionPool.java:503)
        at android.database.sqlite.SQLiteConnectionPool.open(SQLiteConnectionPool.java:204)
        at android.database.sqlite.SQLiteConnectionPool.open(SQLiteConnectionPool.java:196)
        at android.database.sqlite.SQLiteDatabase.openInner(SQLiteDatabase.java:880)
        at android.database.sqlite.SQLiteDatabase.open(SQLiteDatabase.java:865)
        at android.database.sqlite.SQLiteDatabase.openDatabase(SQLiteDatabase.java:766)
        at android.database.sqlite.SQLiteDatabase.openDatabase(SQLiteDatabase.java:714)
        at com.facebook.oxygen.common.androidx.workmanager.initializer.b.a(WorkManagerDatabase.java:20)
        at com.facebook.oxygen.appmanager.app.c.b(AppManagerApplicationImpl.java:19)
        at com.facebook.oxygen.common.f.b.d.onCreate(OxpDelegatingApplication.java:68)
        at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1155)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6291)
        at android.app.ActivityThread.access$1400(ActivityThread.java:219)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1835)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:227)
        at android.app.ActivityThread.main(ActivityThread.java:7199)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:575)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:903)
2019-10-10 10:19:37.941 20622-20649/? E/ActivityThread: Failed to find provider info for com.facebook.appmanager.nekodirect
2019-10-10 10:19:37.979 1810-6474/? E/OppoPackageManager: parserFilterAppList() xml empty, return.
2019-10-10 10:19:37.985 20622-20646/? E/Parcel: Reading a NULL string not supported here.
2019-10-10 10:19:37.989 20622-20646/? E/Parcel: Reading a NULL string not supported here.
2019-10-10 10:19:37.999 20622-20646/? E/Parcel: Reading a NULL string not supported here.
2019-10-10 10:19:38.002 20622-20646/? E/Parcel: Reading a NULL string not supported here.
2019-10-10 10:19:38.010 20622-20646/? E/Parcel: Reading a NULL string not supported here.
2019-10-10 10:19:38.204 1810-3951/? E/TaskPersister: File error accessing recents directory (directory doesn't exist?).
2019-10-10 10:19:39.085 1810-3715/? E/NetworkStatsNative: [1058483] iface is wlan0, use elder API for tcp packets.
2019-10-10 10:19:39.086 1810-3715/? E/NetworkStatsNative: [1058483] iface is wlan0, use elder API for tcp packets.
2019-10-10 10:19:41.089 1810-3715/? E/NetworkStatsNative: [1058483] iface is wlan0, use elder API for tcp packets.
2019-10-10 10:19:41.090 1810-3715/? E/NetworkStatsNative: [1058483] iface is wlan0, use elder API for tcp packets.
2019-10-10 10:19:43.093 1810-3715/? E/NetworkStatsNative: [1058483] iface is wlan0, use elder API for tcp packets.
2019-10-10 10:19:45.096 1810-3715/? E/NetworkStatsNative: [1058483] iface is wlan0, use elder API for tcp packets.
2019-10-10 10:19:47.098 1810-3715/? E/NetworkStatsNative: [1058483] iface is wlan0, use elder API for tcp packets.
2019-10-10 10:19:47.099 1810-3715/? E/NetworkStatsNative: [1058483] iface is wlan0, use elder API for tcp packets.
2019-10-10 10:19:47.691 6906-6909/? E/rutils: releaseProcess gCount = 4
2019-10-10 10:19:49.101 1810-3715/? E/NetworkStatsNative: [1058483] iface is wlan0, use elder API for tcp packets.
2019-10-10 10:19:49.102 1810-3715/? E/NetworkStatsNative: [1058483] iface is wlan0, use elder API for tcp packets.
2019-10-10 10:19:49.692 785-828/? E/ANDR-PERF-RESOURCEQS: Failed to reset optimization [3, 0]

**Comment by mahmooooud** [comment]
2019-10-10 10:36:25.217 23806-23806/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.anaprovider.anamehani2, PID: 23806
    java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/system/framework/org.apache.http.legacy.boot.jar", zip file "/data/app/com.anaprovider.anamehani2-SzdNbeqrKNeWQF6qkrTqeg==/base.apk"],nativeLibraryDirectories=[/data/app/com.anaprovider.anamehani2-SzdNbeqrKNeWQF6qkrTqeg==/lib/arm64, /system/lib64]]] couldn't find "libflutter.so"
        at java.lang.Runtime.loadLibrary0(Runtime.java:1012)
        at java.lang.System.loadLibrary(System.java:1669)
        at io.flutter.view.FlutterMain.startInitialization(FlutterMain.java:156)
        at io.flutter.view.FlutterMain.startInitialization(FlutterMain.java:133)
        at io.flutter.app.FlutterApplication.onCreate(FlutterApplication.java:22)
        at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1155)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6291)
        at android.app.ActivityThread.access$1400(ActivityThread.java:219)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1835)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:227)
        at android.app.ActivityThread.main(ActivityThread.java:7199)
        at java.lang.reflect.Method.invoke(Native Method)

**Comment by BondarenkoStas** [comment]
Will just leave it here as it looks similar https://github.com/flutter/flutter/issues/33637.
Please provide your flutter doctor -v output.

**Comment by mahmooooud** [comment]
thank you for your effort 
i solve it <3

**Comment by iapicca** [comment]
Hi @mahmooooud 
are you still experiencing this issue with the latest stable version of flutter?
If so could you please provide your updated `flutter doctor -v` 
and your `flutter build apk --verbose` and a reproducible minimal code sample
or the steps to reproduce the problem.
Thank you
