### ISSUE TITLE
OS Error: Inappropriate ioctl for device - Running Flutter from Docker

### ISSUE THREAD

**Issue by rubencg195** [flutter/flutter#42384]
My pipeline requires to utilize docker to build apps utilizing different versions of flutter. It compiles and installs the APK successfully but after a couple of seconds after, it stops with the following error. The device is a Nexus 5 emulator connected by SSH to the docker container.

**Command**
```
sudo docker -i -v /projects/app1:/projects rubencg195/flutter-android-sdk bash -c "cd /projects && flutter run --pid-file ./pid.txt --observatory-port 8000 --disable-service-auth-codes lib/main.dart --enable-software-rendering"
```

_**StdinException: StdinException: Error setting terminal echo mode, OS Error: Inappropriate ioctl for device, errno = 25**_

The complete log is the following:

**Build Log**
```
Running Gradle task 'assembleDebug'...                          
flutter dependency
flutter dependency
flutter dependency
Running Gradle task 'assembleDebug'...                          
 31.5s
Built build/app/outputs/apk/debug/app-debug.apk.
Installing build/app/outputs/apk/app.apk...                     
12.7s
Syncing files to device Android SDK built for x86...            
D/EGL_emulation( 4460): eglMakeCurrent: 0xed88d800: ver 2 0 (tinfo 0xd022c810)
Syncing files to device Android SDK built for x86...            
7,953ms
 To hot reload changes while running, press "r". To hot restart (and rebuild state), press "R".
An Observatory debugger and profiler on Android SDK built for x86 is available at: http://127.0.0.1:8000/

For a more detailed help message, press "h". To detach, press "d"; to quit, press "q".
Sending crash report to Google.
Crash report sent (report ID: c3950bca910106ca)
Oops; flutter has exited unexpectedly.
Crash report written to /projects/flutter_02.log;
please let us know at https://github.com/flutter/flutter/issues.
```

**Output Error File**

```
Flutter crash report; please file at https://github.com/flutter/flutter/issues.

## command

flutter run --pid-file ./pid.txt --observatory-port 8000 --disable-service-auth-codes lib/main.dart --enable-software-rendering

## exception

StdinException: StdinException: Error setting terminal echo mode, OS Error: Inappropriate ioctl for device, errno = 25


#0      Stdin.echoMode= (dart:io-patch/stdio_patch.dart:84:7)
#1      AnsiTerminal.singleCharMode= (package:flutter_tools/src/base/terminal.dart:162:15)
#2      TerminalHandler.setupTerminal (package:flutter_tools/src/resident_runner.dart:992:14)
#3      RunCommand.runCommand.<anonymous closure> (package:flutter_tools/src/commands/run.dart:475:15)
#4      _rootRunUnary (dart:async/zone.dart:1132:38)
#5      _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#6      _FutureListener.handleValue (dart:async/future_impl.dart:137:18)
#7      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:678:45)
#8      Future._propagateToListeners (dart:async/future_impl.dart:707:32)
#9      Future._complete (dart:async/future_impl.dart:512:7)
#10     _SyncCompleter.complete (dart:async/future_impl.dart:51:12)
#11     HotRunner.attach (package:flutter_tools/src/run_hot.dart:208:26)
<asynchronous suspension>
#12     HotRunner.run (package:flutter_tools/src/run_hot.dart:267:12)
<asynchronous suspension>
#13     RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:481:37)
<asynchronous suspension>
#14     FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:557:18)
#15     _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:71:64)
#16     _rootRunUnary (dart:async/zone.dart:1132:38)
#17     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#18     _FutureListener.handleValue (dart:async/future_impl.dart:137:18)
#19     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:678:45)
#20     Future._propagateToListeners (dart:async/future_impl.dart:707:32)
#21     Future._completeWithValue (dart:async/future_impl.dart:522:5)
#22     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:30:15)
#23     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:288:13)
#24     RunCommand.usageValues (package:flutter_tools/src/commands/run.dart)
#25     _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:71:64)
#26     _rootRunUnary (dart:async/zone.dart:1132:38)
#27     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#28     _FutureListener.handleValue (dart:async/future_impl.dart:137:18)
#29     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:678:45)
#30     Future._propagateToListeners (dart:async/future_impl.dart:707:32)
#31     Future._completeWithValue (dart:async/future_impl.dart:522:5)
#32     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:30:15)
#33     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:288:13)
#34     IosProject.isSwift (package:flutter_tools/src/project.dart)
#35     _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:71:64)
#36     _rootRunUnary (dart:async/zone.dart:1132:38)
#37     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#38     _FutureListener.handleValue (dart:async/future_impl.dart:137:18)
#39     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:678:45)
#40     Future._propagateToListeners (dart:async/future_impl.dart:707:32)
#41     Future._completeWithValue (dart:async/future_impl.dart:522:5)
#42     Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:552:7)
#43     _rootRun (dart:async/zone.dart:1124:13)
#44     _CustomZone.run (dart:async/zone.dart:1021:19)
#45     _CustomZone.runGuarded (dart:async/zone.dart:923:7)
#46     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:963:23)
#47     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#48     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#49     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:391:30)
#50     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:416:5)
#51     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:12)
```

## flutter doctor

```
[✓] Flutter (Channel master, v1.10.15-pre.39, on Linux, locale en_US.UTF-8)
    • Flutter version 1.10.15-pre.39 at /opt/flutter
    • Framework revision 2adda80c10 (2 hours ago), 2019-10-09 16:58:41 -0700
    • Engine revision e693192167
    • Dart version 2.6.0 (build 2.6.0-dev.6.0 41d13f0ffe)

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /opt/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = /opt/sdk
    • Java binary at: /usr/local/openjdk-8/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_222-b10)
    • All Android licenses accepted.

[✗] Chrome - develop for the web (Cannot find chrome executable at google-chrome)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/setup/#android-setup for detailed instructions).

[✓] Connected device (2 available)
    • Android SDK built for x86 • localhost:6000  • android-x86    • Android 8.1.0 (API 27) (emulator)
    • Headless Server           • headless-server • web-javascript • Flutter Tools

! Doctor found issues in 2 categories.
```

**Comment by jonahwilliams** [comment]
@rubencg195 could you try patching in the PR at https://github.com/flutter/flutter/pull/42892 to see if that helps you?
