### ISSUE TITLE
When changing file or folder name (in Vs Code) dart gives error: 'not found old_folder/xxx.dart'

### ISSUE THREAD

**Issue by mrcndn** [flutter/flutter#42411]
**Error**: Flutter or dart caches filenames in `.dart_tool` folder, then renaming any file causes this error.
Workaround: Deleting `.dart_tool` folder and rerun

## Steps to Reproduce
* Change a folder or file's name
* Run debug
type some text

## Logs
```
Launching lib/main.dart on SM N920C in debug mode...
/Users/emre/Projects/story_saver/lib/screens/instagram_list/insta_list_screen.dart were declared as an inputs, but did not exist. Check the definition of target:kernel_snapshot for errors
[38;5;248m#0      Node.computeChanges  (package:flutter_tools/src/build_system/build_system.dart:777:7)[39;49m
[38;5;244m<asynchronous suspension>[39;49m
[38;5;248m#1      _BuildInstance._invokeInternal  (package:flutter_tools/src/build_system/build_system.dart:517:20)[39;49m
[38;5;244m<asynchronous suspension>[39;49m
[38;5;248m#2      _BuildInstance.invokeTarget.<anonymous closure>  (package:flutter_tools/src/build_system/build_system.dart:481:35)[39;49m
[38;5;244m#3      new Future.sync  (dart:async/future.dart:224:31)[39;49m
[38;5;248m#4      AsyncMemoizer.runOnce[39;49m
[38;5;248m#5      _BuildInstance.invokeTarget  (package:flutter_tools/src/build_system/build_system.dart:481:21)[39;49m
[38;5;244m<asynchronous suspension>[39;49m
[38;5;244m<asynchronous suspension>[39;49m
[38;5;248m#6      BuildSystem.build  (package:flutter_tools/src/build_system/build_system.dart:419:36)[39;49m

[38;5;244m#7      _AsyncAwaitCompleter.start  (dart:async-patch/async_patch.dart:43:6)[39;49m
[38;5;248m#8      BuildSystem.build  (package:flutter_tools/src/build_system/build_system.dart:400:28)[39;49m
[38;5;248m#9      buildWithAssemble  (package:flutter_tools/src/bundle.dart:172:48)[39;49m
[38;5;244m#10     _AsyncAwaitCompleter.start  (dart:async-patch/async_patch.dart:43:6)[39;49m
[38;5;248m#11     buildWithAssemble  (package:flutter_tools/src/bundle.dart:148:31)[39;49m
[38;5;248m#12     BundleBuilder.build  (package:flutter_tools/src/bundle.dart:85:13)[39;49m
[38;5;244m#13     _AsyncAwaitCompleter.start  (dart:async-patch/async_patch.dart:43:6)[39;49m
[38;5;248m#14     BundleBuilder.build  (package:flutter_tools/src/bundle.dart:58:21)[39;49m
[38;5;248m#15     BuildBundleCommand.runCommand  (package:flutter_tools/src/commands/build_bundle.dart:126:25)[39;49m
[38;5;244m#16     _AsyncAwaitCompleter.start  (dart:async-patch/async_patch.dart:43:6)[39;49m
[38;5;248m#17     BuildBundleCommand.runCommand  (package:flutter_tools/src/commands/build_bundle.dart:97:42)[39;49m
[38;5;248m#18     FlutterCommand.verifyThenRunCommand  (package:flutter_tools/src/runner/flutter_command.dart:557:18)[39;49m
[38;5;244m#19     _asyncThenWrapperHelper.<anonymous closure>  (dart:async-patch/async_patch.dart:71:64)[39;49m
[38;5;244m#20     _rootRunUnary  (dart:async/zone.dart:1132:38)[39;49m
[38;5;244m#21     _CustomZone.runUnary  (dart:async/zone.dart:1029:19)[39;49m
[38;5;244m#22     _FutureListener.handleValue  (dart:async/future_impl.dart:137:18)[39;49m
[38;5;244m#23     Future._propagateToListeners.handleValueCallback  (dart:async/future_impl.dart:678:45)[39;49m
[38;5;244m#24     Future._propagateToListeners  (dart:async/future_impl.dart:707:32)[39;49m
[38;5;244m#25     Future._completeWithValue  (dart:async/future_impl.dart:522:5)[39;49m
[38;5;244m#26     Future._asyncComplete.<anonymous closure>  (dart:async/future_impl.dart:552:7)[39;49m
[38;5;244m#27     _rootRun  (dart:async/zone.dart:1124:13)[39;49m
[38;5;244m#28     _CustomZone.run  (dart:async/zone.dart:1021:19)[39;49m
[38;5;244m#29     _CustomZone.runGuarded  (dart:async/zone.dart:923:7)[39;49m
[38;5;244m#30     _CustomZone.bindCallbackGuarded.<anonymous closure>  (dart:async/zone.dart:963:23)[39;49m
[38;5;244m#31     _microtaskLoop  (dart:async/schedule_microtask.dart:41:21)[39;49m
[38;5;244m#32     _startMicrotaskLoop  (dart:async/schedule_microtask.dart:50:5)[39;49m
[38;5;244m#33     _runPendingImmediateCallback  (dart:isolate-patch/isolate_patch.dart:116:13)[39;49m
[38;5;244m#34     _RawReceivePortImpl._handleMessage  (dart:isolate-patch/isolate_patch.dart:173:5)[39;49m


Failed to build bundle.

FAILURE: Build failed with an exception.
* Where:
Script '/Users/emre/development/flutter/packages/flutter_tools/gradle/flutter.gradle' line: 788

* What went wrong:
Execution failed for task ':app:compileFlutterBuildDebugArm64'.
> Process 'command '/Users/emre/development/flutter/bin/flutter'' finished with non-zero exit value 1
* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
* Get more help at https://help.gradle.org
BUİLD FAILED in 16s
Gradle task assembleDebug failed with exit code 1
Exited (sigterm)
```
----

Environment: flutter dev (1.10.12 and newer versions, not sure about previous versions), running debug in real Android device.
----
```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel dev, v1.10.14, on Mac OS X 10.15 19A582a, locale tr-TR)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[!] Xcode - develop for iOS and macOS (Xcode 11.0)
    ✗ CocoaPods installed but not initialized.
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin code that responds to your plugin usage on the
        Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To initialize CocoaPods, run:
        pod setup
      once to finalize CocoaPods' installation.
[✓] Android Studio (version 3.5)
[✓] VS Code (version 1.39.0)
[✓] Connected device (1 available)
```

**Comment by codeyeStartup** [comment]
I had the same issue. My solution was delete the folder **.dart_tool**

**Comment by clicksrv** [comment]
Same issue. I deleted some files with some classes, while there are no compiler errors, the gradleAssembleDebug step fails with a similar error. Deleting the **.dart_tool** worked for me as well.

**Comment by jonahwilliams** [comment]
I have a fix for this pending

**Comment by matrixnl** [comment]
Just delete the .dart_tool folder and rerun

**Comment by l00natyc** [comment]
thanks, deleting the .dart_tool folder did the trick for me too

**Comment by dop3ch3f** [comment]
you can run flutter clean

**Comment by christopherpaulino** [comment]
Delete .dart_tool works

**Comment by SnowyTusk** [comment]
I had this after refactoring the directory name. It was not enough to delete only **.dart_tool**.
This may be due to another problem: the constant creation of temporary **flutter_tools.*** folders in **C:\Temp**.

![image](https://user-images.githubusercontent.com/6566940/129805932-95246d47-e8ea-49e4-93a5-e1f0a72ca4b4.png)

**Solution**: Delete all temporary **flutter_tools** folders in **C:\Temp** and **.dart_tool** in the project workspace. Restart the IDE.

**Comment by jacob314** [comment]
This is close to being implemented. Related VSCode issue. https://github.com/Dart-Code/Dart-Code/issues/2483
