### ISSUE TITLE
External USB  camera

### ISSUE THREAD

**Issue by Hamid811394** [flutter/flutter#42413]
## Use case
Not recognizing external USB camera 

## Proposal

Hi,  I want to use my external usb camera but flutter does not recognize it, it just finds my rear and my front cameras. Please take a look at it .

Thank you

**Comment by haamaanaa** [comment]
Hi! Is there plans to add support for external cameras in next camera library version?

https://github.com/flutter/flutter/issues/31225 does not answer this directly....

**Comment by AshwinPrabhuB** [comment]
Is external camera access a vendor/device dependant feature?

**Comment by moeiscool** [comment]
this and SD card support would be golden 🙏

**Comment by iakrevetkho** [comment]
Hi!
Do you have any updates about this feature?
I need this for my app and one way it is Flutter + Kotlin code for Android

**Comment by josephjmanavalan** [comment]
Do we have an update on this issue? Can we access use camera using flutter?

**Comment by khalidlionel** [comment]
Anything new about this issue ?

**Comment by aponski** [comment]
I'm also interested if Flutter supports external usb camera

**Comment by mcemkilinc** [comment]
I also need this feature, thanks

**Comment by Artespecialist** [comment]
+1

**Comment by hariangr** [comment]
Any update on this issue?

**Comment by m-lecomte** [comment]
Take a look at this plugin, I haven't tested it yet, but it may help.

https://pub.dev/packages/flir_plugin

**Comment by jerossh** [comment]
+1

**Comment by Chance212** [comment]
case CameraLensDirection.back:
      return Icons.camera_rear;
    case CameraLensDirection.front:
      return Icons.camera_front;
    case CameraLensDirection.external:
      return Icons.camera;

/// External camera which may not be mounted to the device.

I see there is a case for external but is it working i tried with different apps for USB camera and it didnt for me :( any luck someone else ?

**Comment by behzodfaiziev** [comment]
@Hamid811394 @josephjmanavalan @khalidlionel @aponski  @mcemkilinc @Artespecialist @hariangr @Chance212 

There is a package [here](https://pub.dev/packages/usb_device), which can detect usb devices. I haven't yet tested it. Also this version(0.0.3) supports only web platform.

**Comment by vrichv** [comment]
Any update on this issue? I also need this feature on android , thanks

**Comment by RomanIvn** [comment]
Very dissapointing :( 
I have to learn an entire new framework now

**Comment by unoravi** [comment]
Is there any update or alternate solution to recognise external USB camera ?

**Comment by m-lecomte** [comment]
I'm currently trying to design a Flutter plugin for controlling external UVC cameras (webcams), using the Android libraries described in this article : [external usb cameras](https://source.android.com/devices/camera/external-usb-cameras)

Nevertheless, one should keep in mind that even on native Android the use of external USB cameras is quite limited.

**Comment by takutoikoshi** [comment]
Xperia1 and 5 will recognize the external camera in Flutter's Camera API.
However, it was only recognized, and connection and communication were not possible.

**Comment by venkatapathiraj** [comment]
Any update on this issue, I’m also trying to use usb camera in my application. Any solution for this issue

**Comment by Leterax** [comment]
Any news on this? Im still unable to recognize or view an external USB camera

**Comment by unoravi** [comment]
Any update on this ?

**Comment by Jingjingsixgod** [comment]
Any update on this ?

**Comment by NickDatLe** [comment]
Any update on this? Or will we never have official external webcam support?

**Comment by m-lecomte** [comment]
There is a line of research around the [libVLC project](https://www.videolan.org/vlc/libvlc.html). VLC is one of the best solution to decode, transcode, and convert any video format. 
And it turns out that the latter is totally crossplaform. So I continue to investigate.

**Comment by NickDatLe** [comment]
> 

are you planning on using libVLC with the camera plugin API to get USB cameras working with flutter?

**Comment by amirr-dotcom** [comment]
Please if any one implemented the usb camera please give me some hint i am not able to implement usb camera I have tried with native library to but failed in implementing it.

**Comment by RomanIvn** [comment]
I was forced to move to a native java fork from this repo eventualy
https://github.com/ConvergenceSoftware/ExCamera

**Comment by amirr-dotcom** [comment]
> I was forced to move to a native java fork from this repo eventualy https://github.com/ConvergenceSoftware/ExCamera

thankyou  @RomanIvn  I will try it.

**Comment by RomanIvn** [comment]
Note that there are restrictions and issues with external cameras on Android 10+,
And ofc this is not applicable for iOS

**Comment by WxqKb** [comment]
Please help me implementing usb camera using flutter its important

**Comment by alt-Pranav** [comment]
I am currently using the following packages from pub.dev for building a windows desktop application using Flutter.
`  camera: ^0.9.4+16
  camera_windows: ^0.1.0`
It detects my laptop's webcam as IntegratedCamera on running the 
`cameras = await CameraPlatform.instance.availableCameras();` method. 
Using `print(cameras.length); print(cameras.toString());` I know that it doesn't detect my phone when connected to the laptop via USB, is there any fix available for the same?


You can refer the code I'm using [here](https://github.com/alt-Pranav/desktop-camera-app/blob/master/lib/useCamera.dart)

**Comment by WriteCodeEveryday** [comment]
So I'm personally stuck on this one with a Skydroid unit. It mounts as a hardware camera, but needs to be turned on after it's plugged in, I can trigger the intent to go to my app but it won't actually show up on the valid camera list.

**Comment by Taverz** [comment]
Please, help!!
Do you need to urgently solve the problem, even if it is some kind of temporary solution or workaround?
Is it possible to somehow hardcode certain parameters or data to make the plugin work?

Device Feature:
- Android 12
- Android SDK 32
- Does not have cameras
- Lots of USB ports

Android Studio from M1-Apple

<details>
  <summary>  flutter doctor -v</summary>
  flutter doctor -v
[✓] Flutter (Channel stable, 3.7.1, on macOS 13.2 22D49 darwin-arm64, locale ru-RU)
     • Flutter version 3.7.1 on channel stable at /Users/User/Documents/devflutter/flutter
     • Upstream repository https://github.com/flutter/flutter.git
     • Framework revision 7048ed95a5 (2 weeks ago), 2023-02-01 09:07:31 -0800
     • Engine revision 800594f1f4
     • Dart version 2.19.1
     • DevTools version 2.20.1

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
     • Android SDK at /Users/User/Library/Android/sdk
     • Platform android-33, build-tools 30.0.3
     • ANDROID_HOME = /Users/User/Library/Android/sdk
     • Java binary at: /Users/User/.sdkman/candidates/java/current/bin/java
     • Java version OpenJDK Runtime Environment Zulu11.52+13-CA (build 11.0.13+8-LTS)
     • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.1)
     • Xcode at /Applications/Xcode.app/Contents/Developer
     • Build 14B47b
     • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
     • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[!] Android Studio (version 2022.1)
     • Android Studio at /Applications/Android Studio.app/Contents
     • Flutter plugin can be installed from:
       🔨 https://plugins.jetbrains.com/plugin/9212-flutter
     • Dart plugin can be installed from:
       🔨 https://plugins.jetbrains.com/plugin/6351-dart
     ✗ Unable to find bundled Java version.
     • Try updating or re-installing Android Studio.

[✓] VS Code (version 1.75.0)
     • VS Code at /Users/User/Documents/Visual Studio Code.app/Contents
     • Flutter extension version 3.58.0

[✓] Connected device (3 available)
     • rk3588 (mobile) • ISCH6N81SS • android-arm64 • Android 12 (API 32)
     • macOS (desktop) • macos • darwin-arm64 • macOS 13.2 22D49 darwin-arm64
     • Chrome (web) • chrome • web-javascript • Google Chrome 109.0.5414.119

[✓] HTTP Host Availability
     • All required HTTP hosts are available

! Doctor found issues in 1 category.

</details>


1. I connected an external camera via USB.
2. I checked that the camera is working: I went into the system application camera, camera !! works.
3. Tried a simple android.hardware.camera2 example (run android code): !! works (external camera success): the camera sees and successfully displays the image from it.
4. I took the last sample code from branch=main https://github.com/flutter/plugins/tree/main/packages/camera/camera
5. Launched as Flutter debug
6. Application started successfully
7. Clicked on select EXTERNAL camera (connect via USB).
8. ERRORE : !!!!!!! android.media.CamcorderProfile.getAll // android.media.CamcorderProfile.native_get_camcorder_profiles

(I tried to change the java code but without success)

<details>
  <summary>Log errore</summary>

Launching lib/main.dart on rk3588 in debug mode...
✓ Built build/app/outputs/flutter-apk/app-debug.apk.
Connecting to VM Service at ws://127.0.0.1:56408/dxxd9TAdu50=/ws
I/CameraManagerGlobal(16481): Connecting to camera service
E/MediaProfiles(16481): The given camcorder profile camera 101 quality 0 is not found

After tap select camera EXTERNAL
-> ->
E/MethodChannel#plugins.flutter.io/camera(16481): Failed to handle method call
E/MethodChannel#plugins.flutter.io/camera(16481): java.lang.RuntimeException: Error retrieving camcorder profile params
E/MethodChannel#plugins.flutter.io/camera(16481): at android.media.CamcorderProfile.native_get_camcorder_profiles(Native Method)
E/MethodChannel#plugins.flutter.io/camera(16481): at android.media.CamcorderProfile.getAll(CamcorderProfile.java:605)
E/MethodChannel#plugins.flutter.io/camera(16481): at io.flutter.plugins.camera.features.resolution.ResolutionFeature.getBestAvailableCamcorderProfileForResolutionPreset(ResolutionFeature.java:231)
E/MethodChannel#plugins.flutter.io/camera(16481): at io.flutter.plugins.camera.features.resolution.ResolutionFeature.configureResolution(ResolutionFeature.java:278)
E/MethodChannel#plugins.flutter.io/camera(16481): at io.flutter.plugins.camera.features.resolution.ResolutionFeature.<init>(ResolutionFeature.java:53)
E/MethodChannel#plugins.flutter.io/camera(16481): at io.flutter.plugins.camera.features.CameraFeatureFactoryImpl.createResolutionFeature(CameraFeatureFactoryImpl.java:58)
E/MethodChannel#plugins.flutter.io/camera(16481): at io.flutter.plugins.camera.features.CameraFeatures.init(CameraFeatures.java:71)
E/MethodChannel#plugins.flutter.io/camera(16481): at io.flutter.plugins.camera.Camera.<init>(Camera.java:215)
E/MethodChannel#plugins.flutter.io/camera(16481): at io.flutter.plugins.camera.MethodCallHandlerImpl.instantiateCamera(MethodCallHandlerImpl.java:385)
E/MethodChannel#plugins.flutter.io/camera(16481): at io.flutter.plugins.camera.MethodC

</details>

**Comment by Taverz** [comment]
<img width="960" alt="Снимок экрана 2023-02-16 в 10 13 36" src="https://user-images.githubusercontent.com/55701501/219294165-38db7495-720e-44e3-baaa-d44e31d5dd29.png">
When testing the latest version of the example, on a tablet without cameras, I attached an external camera. The external ka recognizes.
@Hamid811394

**Comment by Taverz** [comment]
android 12 external camera recognizes

**Comment by Taverz** [comment]
!!!!!!!!!!!!!!!!!   After it recognizes the camera, the application works with it and crashes.

**Comment by Taverz** [comment]
#120776. https://github.com/flutter/flutter/issues/120776

**Comment by Taverz** [comment]
<img width="1401" alt="Снимок экрана 2023-02-16 в 10 37 55" src="https://user-images.githubusercontent.com/55701501/219298905-4f52845a-b118-40be-a845-d833ed12a346.png">

**Comment by Taverz** [comment]
## Solution errore: retrieving camcorder profile params. 

## This file redacted:   
- MediaRecorderBuilder.java  
- Camera.java. 
- ResolutionFeature.java. 

## Delete field:  
- CamcorderProfile. 
- EncoderProfiles. 


## Method editing. 

```
  public MediaRecorder build() throws IOException, NullPointerException, IndexOutOfBoundsException {
    MediaRecorder mediaRecorder = recorderFactory.makeMediaRecorder();

    // There's a fixed order that mediaRecorder expects. Only change these functions accordingly.
    // You can find the specifics here: https://developer.android.com/reference/android/media/MediaRecorder.
    if (enableAudio) mediaRecorder.setAudioSource(MediaRecorder.AudioSource.MIC);
    mediaRecorder.setVideoSource(MediaRecorder.VideoSource.SURFACE);

    if (Build.VERSION.SDK_INT >= 31) {
//      EncoderProfiles.VideoProfile videoProfile = encoderProfiles.getVideoProfiles().get(0);
//      EncoderProfiles.AudioProfile audioProfile = encoderProfiles.getAudioProfiles().get(0);
      String vvvww =" WIN == " ;
//      vvvww = vvvww + " getRecommendedFileFormat "+ encoderProfiles.getRecommendedFileFormat() ;
//      if (enableAudio) {
//        vvvww = vvvww + " getCodec "+ audioProfile.getCodec();
//        vvvww = vvvww + " getBitrate "+ audioProfile.getBitrate();
//        vvvww = vvvww + " getSampleRate "+ audioProfile.getSampleRate();
//      }
//      vvvww = vvvww + " videoProfile.getCodec "+ videoProfile.getCodec();
//      vvvww = vvvww + " videoProfile.getBitrate "+ videoProfile.getBitrate();
//      vvvww = vvvww + " videoProfile.getFrameRate "+ videoProfile.getFrameRate();
//
//      vvvww = vvvww + " videoProfile.getWidth "+ videoProfile.getWidth();
//      vvvww = vvvww + " videoProfile.getHeight "+ videoProfile.getHeight();


      Log.e("EncoderProfilesWWWW", vvvww);

//      MediaRecorder.OutputFormat.DEFAULT  // encoderProfiles.getRecommendedFileFormat()
      mediaRecorder.setOutputFormat(MediaRecorder.OutputFormat.DEFAULT);
//      if (enableAudio) {
//        // 0 - 7 // 2
//        mediaRecorder.setAudioEncoder(MediaRecorder.AudioEncoder.DEFAULT); //audioProfile.getCodec());
////        mediaRecorder.setAudioEncodingBitRate(audioProfile.getBitrate());
////        mediaRecorder.setAudioSamplingRate(audioProfile.getSampleRate());
//      }
      // 0 - 5 // 3
      mediaRecorder.setVideoEncoder(MediaRecorder.VideoEncoder.DEFAULT); // mediaRecorder.setVideoEncoder(videoProfile.getCodec());
      // ??
//      mediaRecorder.setVideoEncodingBitRate(videoProfile.getBitrate());
      // 0 , 90, ...
//      mediaRecorder.setVideoFrameRate(videoProfile.getFrameRate());
      // me size
      mediaRecorder.setVideoSize(600, 600); // videoProfile.getWidth(), videoProfile.getHeight());
      mediaRecorder.setVideoSize(600, 600);
    } else {
      /// MediaRecorder.OutputFormat.RAW_AMR
      // mediaRecorder.setOutputFormat(MediaRecorder.OutputFormat.THREE_GPP);  //camcorderProfile.fileFormat);
      // if (enableAudio) {
      //   mediaRecorder.setAudioEncoder(MediaRecorder.AudioEncoder.AMR_NB);  //camcorderProfile.audioCodec);
      //   mediaRecorder.setAudioEncodingBitRate(16); //camcorderProfile.audioBitRate
      //   mediaRecorder.setAudioSamplingRate(camcorderProfile.audioSampleRate);
      // }
      // mediaRecorder.setVideoEncoder(camcorderProfile.videoCodec);
      // mediaRecorder.setVideoEncodingBitRate(camcorderProfile.videoBitRate);
      // mediaRecorder.setVideoFrameRate(camcorderProfile.videoFrameRate);
      // mediaRecorder.setVideoSize(
      //     camcorderProfile.videoFrameWidth, camcorderProfile.videoFrameHeight);
    }

    mediaRecorder.setOutputFile(outputFilePath);
    mediaRecorder.setOrientationHint(this.mediaOrientation);

    mediaRecorder.prepare();

    return mediaRecorder;
  }
```

**Comment by KennyTC** [comment]
finally, is this any update on this? 
I can not use my webcam as a camera of my Pixel 5 Simulator.

**Comment by Taverz** [comment]
@KennyTC  Hello. I'm not sure if an external camera will work on the emulator. Another problem is that if there is an internal chamber, the external chamber may not open.

**Comment by ZateLabClients** [comment]
@Taverz 
Hi @Taverz , can u please help me with this error?

In android 12, external camera works well in system camera app.
In flutter package, shows "No capture session available for current capture session"

When i inspect ResolutionFeature.java, i found the following condition is **not met**:
        if (CamcorderProfile.hasProfile(cameraId, CamcorderProfile.QUALITY_480P)) {
          return CamcorderProfile.get(cameraId, CamcorderProfile.QUALITY_480P);
        }

Then i tried to return "return CamcorderProfile.get(cameraId, CamcorderProfile.QUALITY_480P);" without checking the above condition, following error shows:

E/MediaProfiles(15037): The given camcorder profile camera 100 quality 0 is not found
E/MethodChannel#plugins.flutter.io/camera_android(15037): Failed to handle method call
E/MethodChannel#plugins.flutter.io/camera_android(15037): java.lang.RuntimeException: Error retrieving camcorder profile params
E/MethodChannel#plugins.flutter.io/camera_android(15037): 	at android.media.CamcorderProfile.native_get_camcorder_profiles(Native Method)
E/MethodChannel#plugins.flutter.io/camera_android(15037): 	at android.media.CamcorderProfile.getAll(CamcorderProfile.java:605)
E/MethodChannel#plugins.flutter.io/camera_android(15037): 	at io.flutter.plugins.camera.features.resolution.ResolutionFeature.getBestAvailableCamcorderProfileForResolutionPreset(ResolutionFeature.java:254)
E/MethodChannel#plugins.flutter.io/camera_android(15037): 	at io.flutter.plugins.camera.features.resolution.ResolutionFeature.configureResolution(ResolutionFeature.java:281)
E/MethodChannel#plugins.flutter.io/camera_android(15037): 	at io.flutter.plugins.camera.features.resolution.ResolutionFeature.<init>(ResolutionFeature.java:55)
E/MethodChannel#plugins.flutter.io/camera_android(15037): 	at io.flutter.plugins.camera.features.CameraFeatureFactoryImpl.createResolutionFeature(CameraFeatureFactoryImpl.java:62)
E/MethodChannel#plugins.flutter.io/camera_android(15037): 	at io.flutter.plugins.camera.features.CameraFeatures.init(CameraFeatures.java:74)
E/MethodChannel#plugins.flutter.io/camera_android(15037): 	at io.flutter.plugins.camera.Camera.<init>(Camera.java:210)
E/MethodChannel#plugins.flutter.io/camera_android(15037): 	at io.flutter.plugins.camera.MethodCallHandlerImpl.instantiateCamera(MethodCallHandlerImpl.java:401)
E/MethodChannel#plugins.flutter.io/camera_android(15037): 	at io.flutter.plugins.camera.MethodCallHandlerImpl.lambda$onMethodCall$0$io-flutter-plugins-camera-MethodCallHandlerImpl(MethodCallHandlerImpl.java:82)
E/MethodChannel#plugins.flutter.io/camera_android(15037): 	at io.flutter.plugins.camera.MethodCallHandlerImpl$$ExternalSyntheticLambda0.onResult(Unknown Source:6)
E/MethodChannel#plugins.flutter.io/camera_android(15037): 	at io.flutter.plugins.camera.CameraPermissions.requestPermissions(CameraPermissions.java:69)
E/MethodChannel#plugins.flutter.io/camera_android(15037): 	at io.flutter.plugins.camera.MethodCallHandlerImpl.onMethodCall(MethodCallHandlerImpl.java:75)
E/MethodChannel#plugins.flutter.io/camera_android(15037): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:258)
E/MethodChannel#plugins.flutter.io/camera_android(15037): 	at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:295)
E/MethodChannel#plugins.flutter.io/camera_android(15037): 	at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$io-flutter-embedding-engine-dart-DartMessenger(DartMessenger.java:322)
E/MethodChannel#plugins.flutter.io/camera_android(15037): 	at io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0.run(Unknown Source:12)
E/MethodChannel#plugins.flutter.io/camera_android(15037): 	at android.os.Handler.handleCallback(Handler.java:938)
E/MethodChannel#plugins.flutter.io/camera_android(15037): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/MethodChannel#plugins.flutter.io/camera_android(15037): 	at android.os.Looper.loopOnce(Looper.java:201)
E/MethodChannel#plugins.flutter.io/camera_android(15037): 	at android.os.Looper.loop(Looper.java:288)
E/MethodChannel#plugins.flutter.io/camera_android(15037): 	at android.app.ActivityThread.main(ActivityThread.java:7870)
E/MethodChannel#plugins.flutter.io/camera_android(15037): 	at java.lang.reflect.Method.invoke(Native Method)
E/MethodChannel#plugins.flutter.io/camera_android(15037): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
E/MethodChannel#plugins.flutter.io/camera_android(15037): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
I/flutter (15037): Error: error
I/flutter (15037): Error Message: Error retrieving camcorder profile params


I tried @Taverz  your solution but no luck.
Can you help me please.

**Comment by Taverz** [comment]
I can give you my working code for you to try, I can't help you with anything else.   


1. Whether the camera device is detected:   

   - Open system camera app and see   
   - Or request a connected list of connected devices via starrony   

2. Download and unpack the folder by placing it in the root directory.   
https://drive.google.com/file/d/1niY4Pkuijs-EV7Sfzt_x6ks6HfN3GE-4/view?usp=share_link   

3. Specify dependencies on the file like this:   

    camera:   
   ㅤpath: camera # or this path ./camera   


4. Test

**Comment by Taverz** [comment]
@stuartmorgan

**Comment by stuartmorgan** [comment]
@Taverz Please do not ping people with no explanation; spamming contributors is not consistent with our code of conduct.

**Comment by ZateLabClients** [comment]
> I can give you my working code for you to try, I can't help you with anything else.
> 
> 1. Whether the camera device is detected:
>    
>    * Open system camera app and see
>    * Or request a connected list of connected devices via starrony
> 2. Download and unpack the folder by placing it in the root directory.
>    https://drive.google.com/file/d/1niY4Pkuijs-EV7Sfzt_x6ks6HfN3GE-4/view?usp=share_link
> 3. Specify dependencies on the file like this:
>    camera:
>    ㅤpath: camera # or this path ./camera
> 4. Test

Thankyou very much

**Comment by arunsinger** [comment]
> > I can give you my working code for you to try, I can't help you with anything else.
> > 
> > 1. Whether the camera device is detected:
> >    
> >    * Open system camera app and see
> >    * Or request a connected list of connected devices via starrony
> > 2. Download and unpack the folder by placing it in the root directory.
> >    https://drive.google.com/file/d/1niY4Pkuijs-EV7Sfzt_x6ks6HfN3GE-4/view?usp=share_link
> > 3. Specify dependencies on the file like this:
> >    camera:
> >    ㅤpath: camera # or this path ./camera
> > 4. Test
> 
> Thankyou very much

Did it worked ? 
I am still Struggling on this

**Comment by Hassanmrwt** [comment]
They have clearly mentioned that " A Flutter plugin for iOS, Android and Web allowing access to the **device** **cameras.** " then how it access external cameras.

**Comment by ethandvaughan** [comment]
Any updates on this issue?

**Comment by rahulbroadview** [comment]
> here

Hi Pranav,
Did you get the solution for that?

**Comment by djensen47** [comment]
If the Flutter team needs a use case for this: embedded systems. Particularly kiosks. But this could be used for infotainment systems and so on.

**Comment by balaji101010** [comment]
Hi @Taverz can you please add your working code as a git repo? is it possible for you?

**Comment by Joao-Peterson** [comment]
tested the [flutter camera example project ](https://github.com/flutter/plugins/blob/main/packages/camera/camera/example/lib/main.dart) and one i made myself and could't get any of the apps to even list the OTG Camera with `availableCameras()`.

Tested with Physical Android 9 and 13.

`flutter doctor -v`:
```log
[✓] Flutter (Channel , 3.19.5, on Linux 6.8.1-arch1-1, locale en_US.UTF-8)
    • Flutter version 3.19.5 on channel  at /usr/lib/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision archlinuxaur (unknown (arch linux aur package)), 2038-01-19 03:14:08
    • Engine revision e76c95649884
    • Dart version 3.3.2
    • DevTools version 2.31.1

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /opt/android-sdk
    • Platform android-34, build-tools 34.0.0
    • ANDROID_HOME = /opt/android-sdk
    • ANDROID_SDK_ROOT = /opt/android-sdk
    • Java binary at: /usr/bin/java
    • Java version OpenJDK Runtime Environment (build 21.0.2+13)
    • All Android licenses accepted.

[✗] Chrome - develop for the web (Cannot find Chrome executable at google-chrome)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.

[✓] Linux toolchain - develop for Linux desktop
    • clang version 17.0.6
    • cmake version 3.28.3
    • ninja version 1.11.1
    • pkg-config version 2.1.1

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/linux#android-setup for detailed instructions).

[✓] Connected device (2 available)
    • ASUS X01AD (mobile) • 192.168.0.101:5555 • android-arm64 • Android 9 (API 28)
    • Linux (desktop)     • linux              • linux-x64     • Linux 6.8.1-arch1-1

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 2 categories.
```

**Comment by eleminer** [comment]
any solutions for that

**Comment by yx-design** [comment]
This issue should not be ignored

**Comment by eleminer** [comment]
is there any solution?

**Comment by balaji101010** [comment]
The only way is you need to manually write code in Android and using MethodChannel you can pass the result to Flutter

**Comment by hxmeie** [comment]
I also encountered the same problem

✓ Built build/app/outputs/flutter-apk/app-debug.apk
Debug service listening on ws://127.0.0.1:55579/rtOHkVZf0Zk=/ws
Syncing files to device HYTF...
I/CameraManagerGlobal( 7431): Connecting to camera service
D/CameraRepository( 7431): Added camera: 3
I/Camera2CameraInfo( 7431): Device Level: INFO_SUPPORTED_HARDWARE_LEVEL_EXTERNAL
D/CameraValidator( 7431): Verifying camera lens facing on sc138, lensFacingInteger: null
E/CameraValidator( 7431): Camera LensFacing verification failed, existing cameras: [Camera@78cdddb[id=3]]
W/CameraX ( 7431): Retry init. Start time 653815 current time 653919
W/CameraX ( 7431): androidx.camera.core.impl.CameraValidator$CameraIdListIncorrectException: Expected camera missing from device.
W/CameraX ( 7431): 	at androidx.camera.core.impl.CameraValidator.validateCameras(CameraValidator.java:97)
W/CameraX ( 7431): 	at androidx.camera.core.CameraX.lambda$initAndRetryRecursively$2$androidx-camera-core-CameraX(CameraX.java:334)
W/CameraX ( 7431): 	at androidx.camera.core.CameraX$$ExternalSyntheticLambda3.run(Unknown Source:10)
W/CameraX ( 7431): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
W/CameraX ( 7431): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
W/CameraX ( 7431): 	at java.lang.Thread.run(Thread.java:1012)
W/CameraX ( 7431): Caused by: java.lang.IllegalArgumentException: No available camera can be found
W/CameraX ( 7431): 	at androidx.camera.core.CameraSelector.select(CameraSelector.java:94)
W/CameraX ( 7431): 	at androidx.camera.core.impl.CameraValidator.validateCameras(CameraValidator.java:83)
W/CameraX ( 7431): 	... 5 more
D/CameraRepository( 7431): Added camera: 3
I/Camera2CameraInfo( 7431): Device Level: INFO_SUPPORTED_HARDWARE_LEVEL_EXTERNAL
D/CameraValidator( 7431): Verifying camera lens facing on sc138, lensFacingInteger: null
E/CameraValidator( 7431): Camera LensFacing verification failed, existing cameras: [Camera@6b7278e[id=3]]
W/CameraX ( 7431): Retry init. Start time 653815 current time 654435

**Comment by hxmeie** [comment]
The v0.11.0 version I used encountered the same problem. After I added the following code, it can be used normally.
<img width="1601" alt="iShot_2024-05-28_14 00 25" src="https://github.com/flutter/flutter/assets/16347352/d8eea991-21e9-493c-a400-3090eca9555f">

**Comment by vritravaibhav** [comment]
U can use this package and can   also check this repo "https://github.com/vritravaibhav/usbwebcamera"

**Comment by eleminer** [comment]
> U can use this package and can also check this repo "https://github.com/vritravaibhav/usbwebcamera"

wow, awesome, i will test it. :)

**Comment by miklz** [comment]
> The v0.11.0 version I used encountered the same problem. After I added the following code, it can be used normally. <img alt="iShot_2024-05-28_14 00 25" width="1601" src="https://private-user-images.githubusercontent.com/16347352/334286813-d8eea991-21e9-493c-a400-3090eca9555f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQyNjc5MzcsIm5iZiI6MTcyNDI2NzYzNywicGF0aCI6Ii8xNjM0NzM1Mi8zMzQyODY4MTMtZDhlZWE5OTEtMjFlOS00OTNjLWE0MDAtMzA5MGVjYTk1NTVmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODIxVDE5MTM1N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRjMzhiOGNlMzg0NGVlMDJhMzFlMzZhZmI2MzlhNzVmM2RkYzdjOWJkZjk2NDUxNjg4NWViNWY3ZTg1NTg1OTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.jpa8U8e52nJ4oyIfB4a27D1bAVKVWoru31OCsVp_En0">

What am I missing, couldn't we open a PR to add external camera support?

**Comment by Fudal** [comment]
Is it possible to make that work?

**Comment by mock1328** [comment]
There are several packages for android (`flutter_uvc_camera`, `uvccamera `) and for Windows/MacOS (`uvc`), but is there any solution for iOS? Or does it work out-of-box, since it seems to be supported in iOS itself since [ios 17](https://developer.apple.com/documentation/avfoundation/avcapturedevice/devicetype-swift.struct/external)?

**Comment by yuuk** [comment]
> The v0.11.0 version I used encountered the same problem. After I added the following code, it can be used normally. <img alt="iShot_2024-05-28_14 00 25" width="1601" src="https://private-user-images.githubusercontent.com/16347352/334286813-d8eea991-21e9-493c-a400-3090eca9555f.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Njc5MjYzOTQsIm5iZiI6MTc2NzkyNjA5NCwicGF0aCI6Ii8xNjM0NzM1Mi8zMzQyODY4MTMtZDhlZWE5OTEtMjFlOS00OTNjLWE0MDAtMzA5MGVjYTk1NTVmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNjAxMDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjYwMTA5VDAyMzQ1NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRhMmY5Yzg2OGFlYTc0MGIxODI5NDc5ODZlNWJjYTdlNDZmNzEzYjcwNjUzMmVjMWY4ZjIwNjJmMTA0ZGNhZTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.O9Cxvd0GAgFoEIeiSq_6Nn5rCAyMZJ-VeYkvx2k4Qpo">

what kind of usb camera did you use?  usb plug-in camera or built-in camera?
 I tried this but not working
