### ISSUE TITLE
Flutter driver timeout cause test to fail

### ISSUE THREAD

**Issue by bitsydarel** [flutter/flutter#42433]
Flutter driver timeout cause test to fail on linux emulator, docker android emulator and macos mojave android emulator and real android device

## Steps to Reproduce
Follow the steps on https://flutter.dev/docs/cookbook/testing/integration/introduction

**Target Platform: Android **
**Target OS version/browser: 25++**
**Devices: Emulator**

## Logs

flutter drive --debug --target=test_driver/app.dart

Using device Android SDK built for x86 64.
Starting application: test_driver/app.dart
Initializing gradle...                                             10.7s
Resolving dependencies...                                          59.7s
"build/app/outputs/apk/app.apk" does not exist.
Running Gradle task 'assembleDebug'...                             47.1s
Built build/app/outputs/apk/debug/app-debug.apk.
Installing build/app/outputs/apk/app.apk...                       408.9s (!)
I/flutter ( 5096): Observatory listening on http://127.0.0.1:42379/LdGM3IHbn2o=/
00:00 [32m+0[0m: Counter App (setUpAll)[0m
[info ] FlutterDriver: Connecting to Flutter application at http://127.0.0.1:33749/LdGM3IHbn2o=/
[trace] FlutterDriver: Isolate found with number: 2862227988220383
[warning] FlutterDriver: Unknown pause event type VMNoneEvent. Assuming application is ready.
00:15 [32m+0[0m[31m -1[0m: Counter App (setUpAll) [1m[31m[E][0m[0m
  JSON-RPC error -32601 (method not found): Method not found
  package:json_rpc_2/src/client.dart 110:64          Client.sendRequest
  package:json_rpc_2/src/peer.dart 79:15             Peer.sendRequest
  package:vm_service_client/src/scope.dart 64:23     Scope.sendRequestRaw
  ===== asynchronous gap ===========================
  dart:async/zone.dart 1053:19                       _CustomZone.registerUnaryCallback
  dart:async-patch/async_patch.dart 71:23            _asyncThenWrapperHelper
  package:flutter_driver/src/driver/driver.dart      FlutterDriver.connect
  test_driver/app_test.dart 18:36                    main.<fn>.<fn>
  ===== asynchronous gap ===========================
  dart:async/zone.dart 1053:19                       _CustomZone.registerUnaryCallback
  dart:async/zone.dart 967:22                        _CustomZone.bindUnaryCallbackGuarded
  dart:async/future.dart 530:34                      Future.doWhile
  dart:async/future.dart 490:12                      Future.forEach
  package:test_api/src/backend/declarer.dart 291:36  Declarer._setUpAll.<fn>.<fn>
  dart:async/zone.dart 1124:13                       _rootRun
  dart:async/zone.dart 1021:19                       _CustomZone.run
  dart:async/zone.dart 1516:10                       _runZoned
  dart:async/zone.dart 1463:12                       runZoned
  package:test_api/src/backend/declarer.dart 291:14  Declarer._setUpAll.<fn>
  package:test_api/src/backend/invoker.dart 400:25   Invoker._onRun.<fn>.<fn>.<fn>.<fn>
  ===== asynchronous gap ===========================
  dart:async/zone.dart 1045:19                       _CustomZone.registerCallback
  dart:async/zone.dart 962:22                        _CustomZone.bindCallbackGuarded
  dart:async/timer.dart 52:45                        new Timer
  dart:async/timer.dart 87:9                         Timer.run
  dart:async/future.dart 174:11                      new Future
  package:test_api/src/backend/invoker.dart 399:21   Invoker._onRun.<fn>.<fn>.<fn>

  DriverError: Failed to fulfill GetHealth due to remote error
  Original error: JSON-RPC error -32601 (method not found): Method not found
  Original stack trace:
  package:json_rpc_2/src/client.dart 110:64          Client.sendRequest
  package:json_rpc_2/src/peer.dart 79:15             Peer.sendRequest
  package:vm_service_client/src/scope.dart 64:23     Scope.sendRequestRaw
  ===== asynchronous gap ===========================
  dart:async/zone.dart 1053:19                       _CustomZone.registerUnaryCallback
  dart:async-patch/async_patch.dart 71:23            _asyncThenWrapperHelper
  package:flutter_driver/src/driver/driver.dart      FlutterDriver.connect
  test_driver/app_test.dart 18:36                    main.<fn>.<fn>
  ===== asynchronous gap ===========================
  dart:async/zone.dart 1053:19                       _CustomZone.registerUnaryCallback
  dart:async/zone.dart 967:22                        _CustomZone.bindUnaryCallbackGuarded
  dart:async/future.dart 530:34                      Future.doWhile
  dart:async/future.dart 490:12                      Future.forEach
  package:test_api/src/backend/declarer.dart 291:36  Declarer._setUpAll.<fn>.<fn>
  dart:async/zone.dart 1124:13                       _rootRun
  dart:async/zone.dart 1021:19                       _CustomZone.run
  dart:async/zone.dart 1516:10                       _runZoned
  dart:async/zone.dart 1463:12                       runZoned
  package:test_api/src/backend/declarer.dart 291:14  Declarer._setUpAll.<fn>
  package:test_api/src/backend/invoker.dart 400:25   Invoker._onRun.<fn>.<fn>.<fn>.<fn>
  ===== asynchronous gap ===========================
  dart:async/zone.dart 1045:19                       _CustomZone.registerCallback
  dart:async/zone.dart 962:22                        _CustomZone.bindCallbackGuarded
  dart:async/timer.dart 52:45                        new Timer
  dart:async/timer.dart 87:9                         Timer.run
  dart:async/future.dart 174:11                      new Future
  package:test_api/src/backend/invoker.dart 399:21   Invoker._onRun.<fn>.<fn>.<fn>

  package:flutter_driver/src/driver/driver.dart 448:7           FlutterDriver._sendCommand
  ===== asynchronous gap ===========================
  dart:async/zone.dart 1062:19                                  _CustomZone.registerBinaryCallback
  dart:async-patch/async_patch.dart 80:23                       _asyncErrorWrapperHelper
  package:test_api/src/backend/invoker.dart                     Invoker._onRun.<fn>.<fn>.<fn>.<fn>
  dart:async/future.dart 176:37                                 new Future.<fn>
  package:stack_trace/src/stack_zone_specification.dart 209:15  StackZoneSpecification._run
  package:stack_trace/src/stack_zone_specification.dart 119:48  StackZoneSpecification._registerCallback.<fn>
  dart:async/zone.dart 1120:38                                  _rootRun
  dart:async/zone.dart 1021:19                                  _CustomZone.run
  dart:async/zone.dart 923:7                                    _CustomZone.runGuarded
  dart:async/zone.dart 963:23                                   _CustomZone.bindCallbackGuarded.<fn>
  package:stack_trace/src/stack_zone_specification.dart 209:15  StackZoneSpecification._run
  package:stack_trace/src/stack_zone_specification.dart 119:48  StackZoneSpecification._registerCallback.<fn>
  dart:async/zone.dart 1124:13                                  _rootRun
  dart:async/zone.dart 1021:19                                  _CustomZone.run
  dart:async/zone.dart 947:23                                   _CustomZone.bindCallback.<fn>
  dart:async-patch/timer_patch.dart 21:15                       Timer._createTimer.<fn>
  dart:isolate-patch/timer_impl.dart 382:19                     _Timer._runTimers
  dart:isolate-patch/timer_impl.dart 416:5                      _Timer._handleMessage
  dart:isolate-patch/isolate_patch.dart 172:12                  _RawReceivePortImpl._handleMessage
  ===== asynchronous gap ===========================
  dart:async/zone.dart 1045:19                                  _CustomZone.registerCallback
  dart:async/zone.dart 962:22                                   _CustomZone.bindCallbackGuarded
  dart:async/timer.dart 52:45                                   new Timer
  dart:async/timer.dart 87:9                                    Timer.run
  dart:async/future.dart 174:11                                 new Future
  package:test_api/src/backend/invoker.dart 399:21              Invoker._onRun.<fn>.<fn>.<fn>

00:15 [32m+0[0m[31m -1[0m: Counter App (tearDownAll)[0m
00:15 [32m+0[0m[31m -1[0m: [31mSome tests failed.[0m

Unhandled exception:
Dummy exception to set exit code.
#0      _rootHandleUncaughtError.<anonymous closure> (dart:async/zone.dart:1112:29)
#1      _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#2      _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#3      _Timer._runTimers (dart:isolate-patch/timer_impl.dart:391:30)
#4      _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:416:5)
#5      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:12)
Stopping application instance.
Driver tests failed: 255

**Comment by bitsydarel** [comment]
This does not happen for ios simulator

**Comment by mmcc007** [comment]
A simple test runs on
```
API=29 ABI=x86_64 GOO=default
```
https://travis-ci.org/mmcc007/test_emulators/jobs/609536065

but fails with above error on
```
API=29 ABI=x86 GOO=google_apis
```
https://travis-ci.org/mmcc007/test_emulators/jobs/609536064#L980 (plus lots of other flaky behavior during test)

Everything else is exactly the same

**Comment by mmcc007** [comment]
For more strange behavior:
```
API=28 ABI=x86 GOO=google_apis_playstore
```
https://travis-ci.org/mmcc007/test_emulators/jobs/609536069
(fails on first and second run of test with above error, succeeds on third run. May be related to startup time of emulator)
https://cirrus-ci.com/task/6224900657774592
(fails on creating the avd)

Source:
https://github.com/mmcc007/test_emulators

**Comment by jonsamwell** [comment]
Seeing this consistently since upgrading to Flutter 1.17.0 on our build server with the Android image `system-images;android-29;google_apis_playstore;x86` by changing to `system-images;android-29;default;x86_64` the driver can consistently connect.

**Comment by darshankawar** [comment]
Hi @bitsydarel 
Is this still an issue on latest version?
If so, can you provide latest `flutter doctor -v` ?
Thanks

**Comment by zoechi** [comment]
I'm still seeing this in GitHub actions. Works on iOS fails on Android. Works on s real Android device.

**Comment by tomrozb** [comment]
@darshankawar yes it still fails on the latest 1.22.1 version. Work locally on Android and iOS, work fine on Codemagic CI for iOS fails for Android

**Comment by agustinventura** [comment]
@tomrozb same here. Did you find any workaround?

**Comment by tomrozb** [comment]
> @tomrozb same here. Did you find any workaround?

Nope

**Comment by HerrNiklasRaab** [comment]
@zoechi Can you remove the "waiting for customer respones" or do you need something to fix this?

**Comment by zoechi** [comment]
@HerrNiklasRaab I did. 
@darshankawar I hope it's ok for you.

**Comment by VeArnold** [comment]
We have been getting quite a few users in Codemagic who have been experiencing this issue for the past month. We'd be happy to see developments in solving this issue. For our users this usually happens randomly - sometimes Flutter driver tests work, sometimes they fail with this issue - builds just time out. We've tried to look for the cause, but we've not been able to lay down a pattern or reproduce it properly. Any information or help is much appreciated. Recently I've had someone reporting this almost every day.

**Comment by tomrozb** [comment]
A workaround that I've found. It's not perfect, but works 99% of time

```
import 'package:vm_service_client/vm_service_client.dart';


// This is how you get the driver in your test
  final mainIsolate = await getMainIsolate();
  await mainIsolate.loadRunnable();
  FlutterDriver driver = await FlutterDriver.connect(
      isolateNumber: mainIsolate.number, printCommunication: true, timeout: Duration(minutes: 1));


Future<VMIsolateRef> getMainIsolate() async {
  final dartVmServiceUrl = Platform.environment['VM_SERVICE_URL'];
  final VMServiceClientConnection connection = await vmServiceConnectFunction(
    dartVmServiceUrl,
    headers: <String, dynamic>{},
  );
  final VMServiceClient client = connection.client;
  final VM vm = await client.getVM();
  print("Available isolates:");
  vm.isolates.forEach((element) {
    print("Isolate: ${element.name} ${element.number}");
  });
  return Future.value(vm.isolates.firstWhere((VMIsolateRef isolate) => isolate.name == "main"));
}

```

**Comment by asifnawaz2311** [comment]
I was having same error in codemagic, to resolve this error you have to simply launch the emulator before the test start, as due to this your driver unable to connect:

1. For android:

`flutter emulators --launch emulator`

2. For IOS:

`flutter emulators --launch emulator`

List of devices on codemagic are as follow:
•emulator            • emulator      • Google • android
•apple_ios_simulator • iOS Simulator • Apple  • ios

**Comment by asifnawaz2311** [comment]
@tomrozb @tomrozb Your solution has worked partially for me as after adding it now flutter driver is connecting but test are still failing as after the test has passed, I am unable to stop application instance and it get stuck here.
![images](https://user-images.githubusercontent.com/60880538/100587375-47aed480-3312-11eb-91ca-8aefedf804b7.PNG)

**Comment by asifnawaz1123** [comment]
> @tomrozb Your solution has worked partially for me as after adding it now flutter driver is connecting but test are still failing as after the test has passed, I am unable to stop application instance and it get stuck here and don't end the test execution.
> 
> ![images](https://user-images.githubusercontent.com/60880538/100587375-47aed480-3312-11eb-91ca-8aefedf804b7.PNG)

any solution?

**Comment by tomrozb** [comment]
@asifnawaz2311 it's not really related to the workaround I posted. It some other issue I also have with flutter driver. I think we should report it as a separate ticket, so it got resolved in the driver.

As a quick workaround I added to `tearDownAll`:

    await Future.delayed(Duration(seconds: 1), () => exit(0));

But that will mark all your builds as passes, because it returns 0. To implement it properly the logic is going to be much more complicated, that's a wrong thread to discuss it

**Comment by tomrozb** [comment]
@jonahwilliams can we mark it P3?

**Comment by jonahwilliams** [comment]
P3 is an issue designation for something that is about to be worked on. p4 is the default for bugs

**Comment by golane-august** [comment]
Anyone has a hint, how to solve this properly? @jonahwilliams open since two years and already 20 upvotes, can we do something to push this, open since 3 years? Also using flutter driver in Github CI with macos (pixel_4, google_apis, x86_64).

**Comment by bartekpacia** [comment]
The cause of this problem might be fixed by #113969.
