### ISSUE TITLE
[google_maps_flutter] Sometimes requires the WAKE_LOCK permission

### ISSUE THREAD

**Issue by mklim** [flutter/flutter#42451]
This was uncovered as part of debugging #42349. 

Occasionally Maps requests the WAKE_LOCK permission when the virtual display is resized with a default `GoogleMap`. It's most likely coming from the Google Maps SDK, but there isn't any obvious reason why this should be. There are a few cases I could find in maps that require that permission, but none of them seem to be related to a default map being resized. 

- There's a wearable version of maps that allows for an "ambient mode" that requires WAKE_LOCK.
- I'm also seeing a [`GeoFenceHadrwareImpl`](https://android.googlesource.com/platform/frameworks/base/+/master/core/java/android/hardware/location/GeofenceHardwareImpl.java) class in AOSP that also requires a wake lock, but I don't know if that itself is referenced anywhere with Maps. I don't think our plugin should be using either of those, but we are deferring to the SDK so it's hard to really tell.

In addition this reproduces extremely flakily, around 2% of the time in my testing. It's also only seen on Q, implying that it's the Maps SDK interacting with Android somehow.

The plugin should ideally avoid whatever code path requires this permission or at least alert developers to it and ask them to add it to their manifests.

**Comment by Martibis** [comment]
I love you.

My application (going live in two weeks) with multiple usages of GoogleMap was crashing all the time on me and I couldn't figure out why, adding WAKE_LOCK permission fixed it.

I want to add that in my case I don't resize the map anywhere, so I don't think it's only to do with resizing. I do use Geolocator to center my map on the users location, it might be related to that.

**Comment by luckyhandler** [comment]
I'm also experiencing the bug.
Using Geolocator as well to get the user location:

`E/flutter (12227): [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: PlatformException(error, Neither user 10266 nor current process has android.permission.WAKE_LOCK., null)
E/flutter (12227): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:569:7)
E/flutter (12227): #1      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:321:33)
E/flutter (12227): <asynchronous suspension>
E/flutter (12227): #2      AndroidViewController.setSize (package:flutter/src/services/platform_views.dart:559:41)
E/flutter (12227): #3      RenderAndroidView._sizePlatformView (package:flutter/src/rendering/platform_view.dart:174:29)
E/flutter (12227): #4      RenderAndroidView.performResize (package:flutter/src/rendering/platform_view.dart:155:5)
E/flutter (12227): #5      RenderObject.layout (package:flutter/src/rendering/object.dart:1703:9)
E/flutter (12227): #6      RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
E/flutter (12227): #7      RenderObject.layout (package:flutter/src/rendering/object.dart:1724:7)
E/flutter (12227): #8      RenderFlex.performLayout (package:flutter/src/rendering/flex.dart:806:17)
E/flutter (12227): #9      RenderObject.layout (package:flutter/src/rendering/object.dart:1724:7)
E/flutter (12227): #10     RenderStack.performLayout (package:flutter/src/rendering/stack.dart:505:15)
E/flutter (12227): #11     RenderObject.layout (package:flutter/src/rendering/object.dart:1724:7)
E/flutter (12227): #12     MultiChildLayoutDelegate.layoutChild (package:flutter/src/rendering/custom_layout.dart:163:11)
E/flutter (12227): #13     _ScaffoldLayout.performLayout (package:flutter/src/material/scaffold.dart:477:7)
E/flutter (12227): #14     MultiChildLayoutDelegate._callPerformLayout (package:flutter/src/rendering/custom_layout.dart:232:7)
E/flutter (12227): #15     RenderCustomMultiChildLayoutBox.performLayout (package:flutter/src/rendering/custom_layout.dart:391:14)
E/flutter (12227): #16     RenderObject._layoutWithoutResize (package:flutter/src/rendering/object.dart:1584:7)
E/flutter (12227): #17     PipelineOwner.flushLayout (package:flutter/src/rendering/object.dart:844:18)
E/flutter (12227): #18     RendererBinding.drawFrame (package:flutter/src/rendering/binding.dart:344:19)
E/flutter (12227): #19     WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:774:13)
E/flutter (12227): #20     RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:283:5)
E/flutter (12227): #21     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1102:15)
E/flutter (12227): #22     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1041:9)
E/flutter (12227): #23     SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:957:5)
E/flutter (12227): #24     _rootRun (dart:async/zone.dart:1126:13)
E/flutter (12227): #25     _CustomZone.run (dart:async/zone.dart:1023:19)
E/flutter (12227): #26     _CustomZone.runGuarded (dart:async/zone.dart:925:7)
E/flutter (12227): #27     _invoke (dart:ui/hooks.dart:259:10)
E/flutter (12227): #28     _drawFrame (dart:ui/hooks.dart:217:3)`

**Comment by tomrozb** [comment]
Still present in ^0.5.25+3

**Comment by phanirithvij** [comment]
This also occurs in webview_flutter I think that should give an idea on which code is shared b/w these? might be the Android PlatformView.

**Comment by akshay-rirev** [comment]
I didn't understand, I have been working on a production app from 5 months as per now and we were not using WAKE_LOCK permission and our Google Map never crashed or gave this error. But now when I am replicating the same Google map code in a new application with very similar UI design, I am getting this wake lock exception.
In both of my apps while opening the text field the keyboard resizes the map, But I am getting exception in one app, not in another.
How do I explain my senior why I am adding this extra permission in-app because he is asking me again and again if we have not used this in the previous app why do you want to add it in a new one.

**Comment by Cayke** [comment]
I am having the same issue, but using a camera package. The problem causing these errors is probably on **PlatformView**.

With my tests i have found that the problem actually happens when opening a **PlatformView after the PlatformException** is raised. 

For reproducing, i opened and closed my camera widget (that uses PlatformView) many times. Sooner or later the error happens when i try to open the widget after the exception was raised. It seems that the flutter app creates an **"invisible view or a touch listener" that blocks all clicks through the phone**, including on the lock screen. The device becomes unusable and you must hard reset it.

```
flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 1.20.1, on Mac OS X 10.15.6 19G73, locale pt-BR)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 11.6)
[✓] Android Studio (version 3.6)
[✓] VS Code (version 1.48.0)
[✓] Connected device (1 available)

• No issues found!
```

I caught the error on firebase crashlytics, here are some infos. It says it is a non fatal exception, but this is obviously **much worse than a fatal exception, causes it turns the device into a rock until a hard reset.**

```
Non-fatal Exception: java.lang.Exception: PlatformException(error, Neither user 10305 nor current process has android.permission.WAKE_LOCK., null)
       at StandardMethodCodec.decodeEnvelope(message_codecs.dart:572)
       at MethodChannel._invokeMethod(platform_channel.dart:161)
       at TextureAndroidViewController.setSize(platform_views.dart:1004)
       at RenderAndroidView._sizePlatformView(platform_view.dart:176)
```

PS: The error occorus mostly on SAMSUNG devices and Android 10, but i have logs of others devices / SO. 
**Check the firebase infos [here](https://imgur.com/a/F39vdPJ).**

**Comment by ckt0** [comment]
Facing the same issue (on SAMSUNG). Thank you for the detailed explanation. 
I tried adding wakelock permissions but the problem persists. Does anyone have a different workaround? 

If the issue is what @Cayke described, then is there a way to close and rebuild the Maps (PlatformView) widget once the Platform Exception is raised?

**Comment by readyiman** [comment]
I encountered this a lot since update to `google_maps_flutter: 2.0.1` on emulator, it always happen after hot restart (never happen on run start). Often when opens keyboard (on child route), like from TextField.

```
Exception has occurred.
PlatformException (PlatformException(error, Neither user 10134 nor current process has android.permission.WAKE_LOCK., null, java.lang.SecurityException: Neither user 10134 nor current process has android.permission.WAKE_LOCK.
	at android.os.Parcel.createException(Parcel.java:2071)
	at android.os.Parcel.readException(Parcel.java:2039)
	at android.os.Parcel.readException(Parcel.java:1987)
	at android.view.IWindowSession$Stub$Proxy.addToDisplay(IWindowSession.java:1242)
	at android.view.ViewRootImpl.setView(ViewRootImpl.java:864)
	at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:387)
	at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:95)
	at android.app.Dialog.show(Dialog.java:342)
	at android.app.Presentation.show(Presentation.java:250)
	at io.flutter.plugin.platform.l.a(:161)
	at io.flutter.plugin.platform.k$a.a(:285)
	at io.flutter.embedding.engine.i.j$a.e(:138)
	at io.flutter.embedding.engine.i.j$a.a(:65)
	at d.a.c.a.j$a.a(:233)
	at io.flutter.embedding.engine.e.b.a(:85)
	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(:818)
	at android.os.MessageQueue.nativePollOnce(Native Method)
	at android.os.MessageQueue.next(MessageQueue.java:336)
	at android.os.Looper.loop(Looper.java:174)
	at android.app.ActivityThread.main(ActivityThread.java:7356)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
Caused by: android.os.RemoteException: Remote stack trace:
	at android.app.ContextImpl.enforce(ContextImpl.java:1896)
	at android.app.ContextImpl.enforceCallingOrSelfPermission(ContextImpl.java:1924)
	at com.android.server.power.PowerManagerService$BinderService.acquireWakeLock(PowerManagerService.java:4270)
	at android.os.PowerManager$WakeLock.acquireLocked(PowerManager.java:2186)
	at android.os.PowerManager$WakeLock.acquire(PowerManager.java:2152)
))
```

**Comment by readyiman** [comment]
I'm able to reproduce this just by making Stack widget with Google Map and TextField.

```
void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: MyHomePage(),
    );
  }}

class MyHomePage extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Stack(
        children: [
          GoogleMap(
            initialCameraPosition: CameraPosition(target: LatLng(0, 0)),
          ),
          Center(
            child: TextField(),
          ),
        ],),);}}
```
Write that, run, then play around TextField. Tap it to open keyboard, then close it, do few of this and it will crash with Wake Lock permission exception.

**Comment by readyiman** [comment]
The solution for now just by add 
```
<uses-permission android:name="android.permission.WAKE_LOCK" />
```
on  Android `manifest`.
Note: this is not needed in my project with version `google_maps_flutter:  1.2.0`

also

> I encountered this a lot since update to google_maps_flutter: 2.0.1 on emulator, it always happen after hot restart (never happen on run start).

does happen on run start.
