### ISSUE TITLE
Can not Listen udp:80 port

### ISSUE THREAD

**Issue by FourLeafTec** [flutter/flutter#42499]
1. When my app listen udp:80 port , got a **SocketException: Failed to create datagram socket (OS Error: Permission denied, errno = 13), address = 0.0.0.0, port = 80**
2. I have sign my app as a System app and check it is run as root

**Target Platform:Android**
**Target OS version/browser:Android 7.0**
**Devices:Orange Pi One plus**

## AndroidManifest.xml
```
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    package="com.uc.hcu_station"
    android:sharedUserId="android.uid.system">

    <uses-permission android:name="android.permission.INTERNET"/>
    <application 
          ...
    ></application>
</manifest>
```
## Logs
```
Launching lib/main.dart on molly in debug mode...
Initializing gradle...
Resolving dependencies...
Running Gradle task 'assembleDebug'...
Built build/app/outputs/apk/debug/app-debug.apk.
Installing build/app/outputs/apk/app.apk...
Syncing files to device molly...
I/flutter (15149): hcu station init.
I/flutter (15149): Creating new copy from asset
I/flutter (15149): Is root:true
I/flutter (15149): udp init error:SocketException: Failed to create datagram socket (OS Error: Permission denied, errno = 13), address = 0.0.0.0, port = 100
I/flutter (15149): udp init error:#0      _NativeSocket.bindDatagram (dart:io-patch/socket_patch.dart:629:7)
I/flutter (15149): <asynchronous suspension>
I/flutter (15149): #1      _RawDatagramSocket.bind (dart:io-patch/socket_patch.dart:1904:26)
I/flutter (15149): #2      RawDatagramSocket.bind (dart:io-patch/socket_patch.dart:1862:31)
I/flutter (15149): #3      new HcuServer (package:hcu_socket/src/hcu/hcu_server.dart:13:23)
I/flutter (15149): #4      HcuServer.bind.<anonymous closure> (package:hcu_socket/src/hcu/hcu_server.dart:22:25)
I/flutter (15149): #5      new Future.<anonymous closure> (dart:async/future.dart:176:37)
I/flutter (15149): #6      _rootRun (dart:async/zone.dart:1120:38)
I/flutter (15149): #7      _CustomZone.run (dart:async/zone.dart:1021:19)
I/flutter (15149): #8      _CustomZone.runGuarded (dart:async/zone.dart:923:7)
I/flutter (15149): #9      _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:963:23)
I/flutter (15149): #10     _rootRun (dart:async/zone.dart:1124:13)
I/flutter (15149): #11     _CustomZone.run (dart:async/zone.dart:1021:19)
I/flutter (15149): #12     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:947:23)
I/flutter (15149): #13     Timer._createTimer.<anonymous closure> (dart:async-patch/timer_patch.dart:2
```

```
Analyzing hcu_station...                                                

   info • The declaration '_$CommonResponseToJson' isn't referenced • lib/api/common_msg.g.dart:15:22 • unused_element
   info • Unused import: 'dart:io' • lib/api/http_client.dart:2:8 • unused_import
   info • This function has a return type of 'List<Map>', but doesn't end with a return statement • lib/db/dao/KhUpsDao.dart:17:53 • missing_return
   info • This function has a return type of 'List<KhUpsEntry>', but doesn't end with a return statement • lib/db/dao/KhUpsDao.dart:34:39 • missing_return
   info • Name non-constant identifiers using lowerCamelCase • lib/db/db.g.dart:4247:16 • non_constant_identifier_names
   info • Name non-constant identifiers using lowerCamelCase • lib/db/db.g.dart:4248:16 • non_constant_identifier_names
   info • Name non-constant identifiers using lowerCamelCase • lib/db/db.g.dart:4258:22 • non_constant_identifier_names
   info • Name non-constant identifiers using lowerCamelCase • lib/db/db.g.dart:4259:22 • non_constant_identifier_names
   info • Name non-constant identifiers using lowerCamelCase • lib/db/db.g.dart:4358:18 • non_constant_identifier_names
   info • Name non-constant identifiers using lowerCamelCase • lib/db/db.g.dart:4359:18 • non_constant_identifier_names
   info • Name non-constant identifiers using lowerCamelCase • lib/db/db.g.dart:4431:23 • non_constant_identifier_names
   info • Name non-constant identifiers using lowerCamelCase • lib/db/db.g.dart:4432:23 • non_constant_identifier_names
   info • Name non-constant identifiers using lowerCamelCase • lib/db/db.g.dart:4442:10 • non_constant_identifier_names
   info • Name non-constant identifiers using lowerCamelCase • lib/db/db.g.dart:4443:10 • non_constant_identifier_names
   info • Name non-constant identifiers using lowerCamelCase • lib/db/db.g.dart:4454:21 • non_constant_identifier_names
   info • Name non-constant identifiers using lowerCamelCase • lib/db/db.g.dart:4455:21 • non_constant_identifier_names
   info • Name non-constant identifiers using lowerCamelCase • lib/db/db.g.dart:4552:26 • non_constant_identifier_names
   info • Name non-constant identifiers using lowerCamelCase • lib/db/db.g.dart:4553:23 • non_constant_identifier_names
   info • Name non-constant identifiers using lowerCamelCase • lib/db/db.g.dart:4555:27 • non_constant_identifier_names
   info • Name non-constant identifiers using lowerCamelCase • lib/db/db.g.dart:4564:26 • non_constant_identifier_names
   info • Name non-constant identifiers using lowerCamelCase • lib/db/db.g.dart:4566:23 • non_constant_identifier_names
   info • Name non-constant identifiers using lowerCamelCase • lib/db/db.g.dart:4568:27 • non_constant_identifier_names
   info • Name non-constant identifiers using lowerCamelCase • lib/db/table/LogEventTable.dart:20:18 • non_constant_identifier_names
   info • Name non-constant identifiers using lowerCamelCase • lib/db/table/LogEventTable.dart:22:18 • non_constant_identifier_names
   info • Unused import: 'api/http_api_server.dart' • lib/main.dart:21:8 • unused_import
   info • Unused import: 'package:hcu_station/db/db_util.dart' • lib/view/aircon/System.dart:3:8 • unused_import
   info • Unused import: 'package:hcu_station/view/env/THLine.dart' • lib/view/aircon/System.dart:5:8 • unused_import
   info • Unused import: 'package:hcu_station/db/db_util.dart' • lib/view/aircon/Temperature.dart:3:8 • unused_import
   info • Unused import: 'package:hcu_station/view/env/THLine.dart' • lib/view/aircon/Temperature.dart:5:8 • unused_import
   info • Unused import: 'package:hcu_station/db/db_util.dart' • lib/view/aircon/Warning.dart:3:8 • unused_import
   info • Unused import: 'package:hcu_station/view/env/THLine.dart' • lib/view/aircon/Warning.dart:5:8 • unused_import
   info • Unused import: 'package:hcu_socket/hcu_socket.dart' • lib/view/ctrl/Ctrl.dart:3:8 • unused_import
   info • Unused import: 'package:hcu_station/api/hcu.dart' • lib/view/ctrl/Ctrl.dart:4:8 • unused_import
   info • The value of the local variable 'textStyle' isn't used • lib/view/ctrl/Ctrl.dart:12:21 • unused_local_variable
   info • Unused import: 'package:hcu_socket/hcu_socket.dart' • lib/view/ctrl/CtrlContainer.dart:2:8 • unused_import
   info • Unused import: 'package:hcu_station/view/env/EnvSingle.dart' • lib/view/ctrl/CtrlContainer.dart:6:8 • unused_import
   info • Unused import: 'package:hcu_station/view/theft/DoorHis.dart' • lib/view/ctrl/CtrlContainer.dart:7:8 • unused_import
   info • Unused import: 'package:hcu_station/view/theft/DoorStatus.dart' • lib/view/ctrl/CtrlContainer.dart:8:8 • unused_import
   info • Unused import: 'package:hcu_station/view/theft/Move.dart' • lib/view/ctrl/CtrlContainer.dart:9:8 • unused_import
   info • Unused import: 'package:hcu_station/view/theft/RoundPic.dart' • lib/view/ctrl/CtrlContainer.dart:10:8 • unused_import
   info • Unused import: 'package:rxdart/subjects.dart' • lib/view/ctrl/CtrlContainer.dart:11:8 • unused_import
   info • The value of the local variable 'width' isn't used • lib/view/ctrl/CtrlContainer.dart:18:18 • unused_local_variable
   info • The value of the local variable 'height' isn't used • lib/view/ctrl/CtrlContainer.dart:19:18 • unused_local_variable
   info • The value of the local variable 'textStyle' isn't used • lib/view/ctrl/CtrlContainer.dart:20:21 • unused_local_variable
   info • Unused import: 'package:hcu_socket/hcu_socket.dart' • lib/view/env/Env.dart:3:8 • unused_import
   info • Unused import: 'package:hcu_station/api/hcu.dart' • lib/view/env/Env.dart:4:8 • unused_import
   info • Equality operator `==` invocation with references of unrelated types • lib/view/env/THLine.dart:53:11 • unrelated_type_equality_checks
   info • This class (or a class which this class inherits from) is marked as '@immutable', but one or more of its instance fields are not final: Header.color, Header.title, Header.envTemperature,
          Header.humidity • lib/view/his/Header.dart:3:7 • must_be_immutable
   info • The value of the local variable 'textStyle' isn't used • lib/view/his/HisList.dart:10:21 • unused_local_variable
   info • Unused import: 'package:hcu_station/view/compents/WidthText.dart' • lib/view/home/Guard.dart:4:8 • unused_import
   info • The value of the local variable 'textStyle' isn't used • lib/view/home/Home.dart:10:21 • unused_local_variable
   info • The value of the local variable 'textStyle' isn't used • lib/view/home/HomeContainer.dart:17:21 • unused_local_variable
   info • The value of the local variable 'textStyle' isn't used • lib/view/power/PowerContainer.dart:15:21 • unused_local_variable
   info • Equality operator `==` invocation with references of unrelated types • lib/view/power/PowerLine.dart:50:11 • unrelated_type_equality_checks
   info • Unused import: 'package:hcu_socket/hcu_socket.dart' • lib/view/setting/Setting.dart:3:8 • unused_import
   info • Unused import: 'package:hcu_station/api/hcu.dart' • lib/view/setting/Setting.dart:4:8 • unused_import
   info • The value of the local variable 'textStyle' isn't used • lib/view/setting/Setting.dart:12:21 • unused_local_variable
   info • Unused import: 'package:hcu_station/view/compents/WidthText.dart' • lib/view/theft/RoundPic.dart:2:8 • unused_import
   info • Unused import: 'package:hcu_socket/hcu_socket.dart' • lib/view/theft/TheftContainer.dart:2:8 • unused_import
```

```
[✓] Flutter (Channel stable, v1.9.1+hotfix.4, on Mac OS X 10.15 19A583, locale zh-Hans-CN)
    • Flutter version 1.9.1+hotfix.4 at /Users/flt/tools/flutter
    • Framework revision cc949a8e8b (13 days ago), 2019-09-27 15:04:59 -0700
    • Engine revision b863200c37
    • Dart version 2.5.0

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/flt/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • ANDROID_HOME = /Users/flt/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[!] Xcode - develop for iOS and macOS (Xcode 11.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.1, Build version 11A1027
    ✗ CocoaPods not installed.
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To install:
        sudo gem install cocoapods
        pod setup

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 40.1.2
    • Dart plugin version 191.8423
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[!] IntelliJ IDEA Community Edition (version 2019.2.2)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.dev/intellij-setup/#installing-the-plugins

[✓] VS Code (version 1.38.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.5.1

[✓] Connected device (1 available)
    • molly • 192.168.1.112:5555 • android-arm • Android 7.0 (API 24)

! Doctor found issues in 2 categories.
```

**Comment by Hixie** [comment]
On Unix you can't listen to ports less than 1024 unless you're root, so this is working as intended.
