### ISSUE TITLE
 [ERROR:flutter/lib/ui/ui_dart_state.cc(148)] Unhandled Exception: Exception: operation failed

### ISSUE THREAD

**Issue by SwainZhang** [flutter/flutter#42490]
The error occurred when I tried to take a screenshot.

```
E/flutter (27671): [ERROR:flutter/lib/ui/ui_dart_state.cc(148)] Unhandled Exception: Exception: operation failed
E/flutter (27671): #0      OffsetLayer.toImage (package:flutter/src/rendering/layer.dart:948:14)
E/flutter (27671): <asynchronous suspension>
E/flutter (27671): #1      RenderRepaintBoundary.toImage (package:flutter/src/rendering/proxy_box.dart:2814:18)
E/flutter (27671): #2      _LongImagePreviewPageState.build.<anonymous closure> (package:duideren/home/recommend/LongImagePreviewPage.dart:97:50)
E/flutter (27671): <asynchronous suspension>
E/flutter (27671): #3      _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:635:14)
E/flutter (27671): #4      _InkResponseState.build.<anonymous closure> (package:flutter/src/material/ink_well.dart:711:32)
E/flutter (27671): #5      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:182:24)
E/flutter (27671): #6      TapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:365:11)
E/flutter (27671): #7      TapGestureRecognizer.handlePrimaryPointer (package:flutter/src/gestures/tap.dart:275:7)
E/flutter (27671): #8      PrimaryPointerGestureRecognizer.handleEvent (package:flutter/src/gestures/recognizer.dart:455:9)
E/flutter (27671): #9      PointerRouter._dispatch (package:flutter/src/gestures/pointer_router.dart:75:13)
E/flutter (27671): #10     PointerRouter.route (package:flutter/src/gestures/pointer_router.dart:102:11)
E/flutter (27671): #11     _WidgetsFlutterBinding&BindingBase&GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:218:19)
E/flutter (27671): #12     _WidgetsFlutterBinding&BindingBase&GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:198:22)
E/flutter (27671): #13     _WidgetsFlutterBinding&BindingBase&GestureBinding._handlePointerEvent (package:flutter/src/gestures/binding.dart:156:7)
E/flutter (27671): #14     _WidgetsFlutterBinding&BindingBase&GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:102:7)
E/flutter (27671): #15     _WidgetsFlutterBinding&BindingBase&GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:86:7)
E/flutter (27671): #16     _rootRunUnary (dart:async/zone.dart:1136:13)
E/flutter (27671): #17     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
E/flutter (27671): #18     _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
E/flutter (27671): #19     _invoke1 (dart:ui/hooks.dart:250:10)
E/flutter (27671): #20     _dispatchPointerDataPacket (dart:ui/hooks.dart:159:5)
E/flutter (27671): 



```

**Comment by BondarenkoStas** [comment]
@SwainZhang Please provide more information, your flutter doctor -v output, what the device/emulator you use, if possible the code example that reproduces the issue.

**Comment by janmoppel** [comment]
Hello @SwainZhang !

Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!

Thanks for your contribution.

P.S. Could everyone who still experience the same problem please file a new issue with the information required in the template.
All system setups can be slightly different so it’s always better to open new issues and reference related issues.
