### ISSUE TITLE
Exception Caught By gesture

### ISSUE THREAD

**Issue by HappyGhostz** [flutter/flutter#42504]
```
The following assertion was thrown while handling a gesture:
'package:flutter/src/widgets/scrollable.dart': Failed assertion: line 503 pos 12: '_hold == null || _drag == null': is not true.

Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=BUG.md

When the exception was thrown, this was the stack: 
#2      ScrollableState._handleDragEnd (package:flutter/src/widgets/scrollable.dart:503:12)
#3      DragGestureRecognizer._checkEnd.<anonymous closure> (package:flutter/src/gestures/monodrag.dart:419:41)
#4      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:182:24)
#5      DragGestureRecognizer._checkEnd (package:flutter/src/gestures/monodrag.dart:419:5)
#6      DragGestureRecognizer.didStopTrackingLastPointer (package:flutter/src/gestures/monodrag.dart:338:9)
...
Handler: "onEnd"
Recognizer: VerticalDragGestureRecognizer#f34f7
  start behavior: start
```

**Comment by BondarenkoStas** [comment]
@HappyGhostz Please provide more information, your flutter doctor -v output, what the device/emulator you use, steps taken or if possible the code example that reproduces the issue.

**Comment by HappyGhostz** [comment]
Thank you, have been avoided by some means

**Comment by bhallaramdhatarwal** [comment]
open

I am also facing similar problem but on Share.share(); like bellow 

ListTile(
                  title: Text(S.of(context).share, textAlign: TextAlign.center),
                  onTap: () {
                    Navigator.of(context).pop();
                    final RenderBox box = context.findRenderObject();
                    Share.share(product.name,sharePositionOrigin:box.localToGlobal(Offset.zero) & box.size);
                  })

Thanks in advance
