### ISSUE TITLE
RenderFractionallySizedOverflowBox intrinsic protocol violation

### ISSUE THREAD

**Issue by Tregan** [flutter/flutter#42527]
During widget tests (works fine otherwise), the following test will generate an intrinsic protocol violation:

```
import 'package:flutter/material.dart';
import 'package:flutter_test/flutter_test.dart';

void main() {
    testWidgets('test', (tester) async {
      await tester.pumpWidget(FractionallySizedBox(
        heightFactor: 0.0,
      ));
    });
}
```

The same happens when the widthFactor is set to 0.0.
Might be related to https://github.com/flutter/flutter/issues/7900 , since the same workaround (setting the factor to like 0.000001) works here.

Log:
```
══╡ EXCEPTION CAUGHT BY RENDERING LIBRARY ╞═════════════════════════════════════════════════════════
The following assertion was thrown during performLayout():
The intrinsic dimension methods of the RenderFractionallySizedOverflowBox class returned values that
violate the intrinsic protocol contract.
The following failures was detected:
 * getMinIntrinsicHeight(Infinity) returned a non-finite value: NaN
 * getMaxIntrinsicHeight(Infinity) returned a non-finite value: NaN
 * getMinIntrinsicHeight(800.0) returned a non-finite value: NaN
 * getMaxIntrinsicHeight(800.0) returned a non-finite value: NaN
If you are not writing your own RenderBox subclass, then this is not
your fault. Contact support: https://github.com/flutter/flutter/issues/new?template=BUG.md

Widget creation tracking is currently disabled. Enabling it enables improved error messages. It can
be enabled by passing `--track-widget-creation` to `flutter run` or `flutter test`.

When the exception was thrown, this was the stack:
#0      RenderBox.debugAssertDoesMeetConstraints.<anonymous closure> (package:flutter/src/rendering/box.dart:2009:11)
#1      RenderBox.debugAssertDoesMeetConstraints (package:flutter/src/rendering/box.dart:2021:6)
#2      RenderBox.size=.<anonymous closure> (package:flutter/src/rendering/box.dart:1738:7)
#3      RenderBox.size= (package:flutter/src/rendering/box.dart:1740:6)
#4      RenderFractionallySizedOverflowBox.performLayout (package:flutter/src/rendering/shifted_box.dart:938:7)
#5      RenderObject.layout (package:flutter/src/rendering/object.dart:1701:7)
#6      RenderView.performLayout (package:flutter/src/rendering/view.dart:152:13)
#7      RenderObject._layoutWithoutResize (package:flutter/src/rendering/object.dart:1578:7)
#8      PipelineOwner.flushLayout (package:flutter/src/rendering/object.dart:844:18)
#9      AutomatedTestWidgetsFlutterBinding.drawFrame (package:flutter_test/src/binding.dart:943:23)
#10     RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:280:5)
#11     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1033:15)
#12     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:975:9)
#13     AutomatedTestWidgetsFlutterBinding.pump.<anonymous closure> (package:flutter_test/src/binding.dart:853:9)
#16     TestAsyncUtils.guard (package:flutter_test/src/test_async_utils.dart:69:41)
#17     AutomatedTestWidgetsFlutterBinding.pump (package:flutter_test/src/binding.dart:840:27)
#18     WidgetTester.pumpWidget.<anonymous closure> (package:flutter_test/src/widget_tester.dart:318:22)
#21     TestAsyncUtils.guard (package:flutter_test/src/test_async_utils.dart:69:41)
#22     WidgetTester.pumpWidget (package:flutter_test/src/widget_tester.dart:315:27)
#23     main.<anonymous closure>.<anonymous closure> (file:///D:/IC3D%20Media/app_flutter/test/widget/widgets/filled_widget_test.dart:46:20)
<asynchronous suspension>
#24     testWidgets.<anonymous closure>.<anonymous closure> (package:flutter_test/src/widget_tester.dart:119:25)
<asynchronous suspension>
#25     TestWidgetsFlutterBinding._runTestBody (package:flutter_test/src/binding.dart:648:19)
<asynchronous suspension>
#28     TestWidgetsFlutterBinding._runTest (package:flutter_test/src/binding.dart:631:14)
#29     AutomatedTestWidgetsFlutterBinding.runTest.<anonymous closure> (package:flutter_test/src/binding.dart:1016:24)
#35     AutomatedTestWidgetsFlutterBinding.runTest (package:flutter_test/src/binding.dart:1013:15)
#36     testWidgets.<anonymous closure> (package:flutter_test/src/widget_tester.dart:116:22)
#37     Declarer.test.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:test_api/src/backend/declarer.dart:168:27)
<asynchronous suspension>
#38     Invoker.waitForOutstandingCallbacks.<anonymous closure> (package:test_api/src/backend/invoker.dart:250:15)
<asynchronous suspension>
#43     Invoker.waitForOutstandingCallbacks (package:test_api/src/backend/invoker.dart:247:5)
#44     Declarer.test.<anonymous closure>.<anonymous closure> (package:test_api/src/backend/declarer.dart:166:33)
#49     Declarer.test.<anonymous closure> (package:test_api/src/backend/declarer.dart:165:13)
<asynchronous suspension>
#50     Invoker._onRun.<anonymous closure>.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:test_api/src/backend/invoker.dart:400:25)
<asynchronous suspension>
#64     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:382:19)
#65     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:416:5)
#66     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:12)
(elided 32 frames from class _FakeAsync, package dart:async, package dart:async-patch, and package stack_trace)

The following RenderObject was being processed when the exception was fired: RenderFractionallySizedOverflowBox#8355d:
  creator: FractionallySizedBox ← [root]
  parentData: <none>
  constraints: BoxConstraints(w=800.0, h=600.0)
  size: Size(800.0, 600.0)
  alignment: center
  widthFactor: pass-through
  heightFactor: 0.0
This RenderObject has no descendants.
```

```
[√] Flutter (Channel master, v1.10.15-pre.79, on Microsoft Windows [Version 10.0.18362.418], locale nl-NL)
    • Flutter version 1.10.15-pre.79 at D:\flutter
    • Framework revision 72d5c1c805 (6 hours ago), 2019-10-11 03:58:43 -0400
    • Engine revision 8dabfb90a1
    • Dart version 2.6.0 (build 2.6.0-dev.7.0 965b8cb1d8)

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at D:\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • ANDROID_SDK_ROOT = D:\Android\sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)
    • All Android licenses accepted.

[√] Android Studio (version 3.5)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 40.1.2
    • Dart plugin version 191.8423
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)

[√] VS Code (version 1.39.1)
    • VS Code at C:\Users\Bas Rops\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.5.1

[√] Connected device (1 available)
    • SM G930F • 98862741393346434b • android-arm64 • Android 8.0.0 (API 26)

• No issues found!
```

**Comment by NearHuscarl** [comment]
Same on version `v1.12.13+hotfix.6`

You can also replace `0.00001` with `double.minPositive` as a workaround

**Comment by markusaksli-nc** [comment]
Reproducible on the latest master `1.22.0-2.0.pre.59`.
<details>
 <summary>flutter doctor -v</summary>

```
[√] Flutter (Channel master, 1.22.0-2.0.pre.59, on Microsoft Windows [Version 10.0.19041.450], locale en-US)
    • Flutter version 1.22.0-2.0.pre.59 at C:\Development\flutter_master
    • Framework revision be7c7faee6 (7 hours ago), 2020-08-24 22:31:02 -0400
    • Engine revision 8107b36c7b
    • Dart version 2.10.0 (build 2.10.0-56.0.dev)

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
    • Android SDK at C:\Users\marku\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.1
    • Java binary at: C:\Users\marku\AppData\Local\JetBrains\Toolbox\apps\AndroidStudio\ch-0\193.6626763\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.6.5)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.6.30320.27
    • Windows 10 SDK version 10.0.18362.0

[√] Android Studio (version 4.0)
    • Android Studio at C:\Users\marku\AppData\Local\JetBrains\Toolbox\apps\AndroidStudio\ch-0\193.6626763
    • Flutter plugin version 47.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] Connected device (4 available)
    • sdk gphone x86 arm (mobile) • emulator-5554 • android-x86    • Android 11 (API 30) (emulator)
    • Windows (desktop)           • windows       • windows-x64    • Microsoft Windows [Version 10.0.19041.450]
    • Web Server (web)            • web-server    • web-javascript • Flutter Tools
    • Chrome (web)                • chrome        • web-javascript • Google Chrome 84.0.4147.135

• No issues found!
```
</details>

**Comment by darshankawar** [comment]
Verified on latest master version and observed that issue is not replicable anymore.

```
dhs@Dhss-MacBook-Pro test_app % flutter test test/widget_test.dart                                        
00:02 +1: All tests passed!                                                                                                                                                              
dhs@Dhss-MacBook-Pro test_app % 

```

<details>
<summary> master flutter doctor -v </summary>

```


[!] Flutter (Channel master, 3.5.0-12.0.pre.45, on macOS 12.2.1 21D62
    darwin-x64, locale en-GB)
    • Flutter version 3.5.0-12.0.pre.45 on channel master at
      /Users/dhs/documents/fluttersdk/flutter
    ! Warning: `flutter` on your path resolves to
      /Users/dhs/Documents/Fluttersdk/flutter/bin/flutter, which is not inside
      your current Flutter SDK checkout at
      /Users/dhs/documents/fluttersdk/flutter. Consider adding
      /Users/dhs/documents/fluttersdk/flutter/bin to the front of your path.
    ! Warning: `dart` on your path resolves to
      /Users/dhs/Documents/Fluttersdk/flutter/bin/dart, which is not inside your
      current Flutter SDK checkout at /Users/dhs/documents/fluttersdk/flutter.
      Consider adding /Users/dhs/documents/fluttersdk/flutter/bin to the front
      of your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision c2edb20f3d (53 minutes ago), 2022-10-31 21:18:37 -0700
    • Engine revision f721db653d
    • Dart version 2.19.0 (build 2.19.0-356.0.dev)
    • DevTools version 2.18.0
    • If those were intentional, you can disregard the above warnings; however
      it is recommended to use "git" directly to perform update checks and
      upgrades.
    
[!] Xcode - develop for iOS and macOS (Xcode 12.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    ! Flutter recommends a minimum Xcode version of 13.
      Download the latest version or update via the Mac App Store.
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] VS Code (version 1.62.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.21.0

[✓] Connected device (5 available)
    • SM G975F (mobile)       • RZ8M802WY0X • android-arm64   • Android 11 (API 30)
    • Darshan's iphone (mobile)  • 21150b119064aecc249dfcfe05e259197461ce23 •
      ios            • iOS 14.4.1 18D61
    • iPhone 12 Pro Max (mobile) • A5473606-0213-4FD8-BA16-553433949729     •
      ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-3 (simulator)
    • macOS (desktop)            • macos                                    •
      darwin-x64     • Mac OS X 10.15.4 19E2269 darwin-x64
    • Chrome (web)               • chrome                                   •
      web-javascript • Google Chrome 98.0.4758.80

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.



```

</details>

Closing as fixed.
