### ISSUE TITLE
Flutter Android crashes if the splash screen resource ID isn't found

### ISSUE THREAD

**Issue by TheEnbyperor** [flutter/flutter#42663]
## Steps to Reproduce

I'm trying to start a flutter app from a `AccountManager` service (in a flutter plugin) on android such that the user can login. If I make the activity a subclass of `io.flutter.app.FlutterActivity` it loads the main app, and with `io.flutter.embedding.android.FlutterActivity` I get a `RuntimeException`.

**Target Platform:** Android
**Target OS version/browser:** 8.1
**Devices:** EVA L09

## Logs

```
[+9678 ms] I/FlutterKeycloakService( 8790): Service created
[  +27 ms] I/FlutterKeycloakService( 8790): Service destroyed
[ +115 ms] W/ResourceType( 8790): No package identifier when getting value for resource number 0x00000000
[  +19 ms] E/AndroidRuntime( 8790): FATAL EXCEPTION: main
[        ] E/AndroidRuntime( 8790): Process: uk.cardifftec.flutter_keycloak_example, PID: 8790
[        ] E/AndroidRuntime( 8790): java.lang.RuntimeException: Unable to start activity ComponentInfo{uk.cardifftec.flutter_keycloak_example/uk.cardifftec.flutter_keycloak.LoginActivity}:
android.content.res.Resources$NotFoundException: Resource ID #0x0
[   +1 ms] E/AndroidRuntime( 8790): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2793)
[        ] E/AndroidRuntime( 8790): 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2864)
[        ] E/AndroidRuntime( 8790): 	at android.app.ActivityThread.-wrap12(ActivityThread.java)
[        ] E/AndroidRuntime( 8790): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1567)
[        ] E/AndroidRuntime( 8790): 	at android.os.Handler.dispatchMessage(Handler.java:105)
[        ] E/AndroidRuntime( 8790): 	at android.os.Looper.loop(Looper.java:156)
[        ] E/AndroidRuntime( 8790): 	at android.app.ActivityThread.main(ActivityThread.java:6517)
[        ] E/AndroidRuntime( 8790): 	at java.lang.reflect.Method.invoke(Native Method)
[        ] E/AndroidRuntime( 8790): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:942)
[        ] E/AndroidRuntime( 8790): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:832)
[        ] E/AndroidRuntime( 8790): Caused by: android.content.res.Resources$NotFoundException: Resource ID #0x0
[        ] E/AndroidRuntime( 8790): 	at android.content.res.ResourcesImpl.getValue(ResourcesImpl.java:255)
[        ] E/AndroidRuntime( 8790): 	at android.content.res.Resources.getDrawable(Resources.java:833)
[        ] E/AndroidRuntime( 8790): 	at io.flutter.embedding.android.FlutterActivity.getSplashScreenFromManifest(FlutterActivity.java:482)
[        ] E/AndroidRuntime( 8790): 	at io.flutter.embedding.android.FlutterActivity.provideSplashScreen(FlutterActivity.java:455)
[        ] E/AndroidRuntime( 8790): 	at io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.onCreateView(FlutterActivityAndFragmentDelegate.java:255)
[        ] E/AndroidRuntime( 8790): 	at io.flutter.embedding.android.FlutterActivity.createFlutterView(FlutterActivity.java:511)
[        ] E/AndroidRuntime( 8790): 	at io.flutter.embedding.android.FlutterActivity.onCreate(FlutterActivity.java:404)
[        ] E/AndroidRuntime( 8790): 	at uk.cardifftec.flutter_keycloak.LoginActivity.onCreate(LoginActivity.kt:12)
[        ] E/AndroidRuntime( 8790): 	at android.app.Activity.performCreate(Activity.java:6915)
[        ] E/AndroidRuntime( 8790): 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1123)
[        ] E/AndroidRuntime( 8790): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2746)
[        ] E/AndroidRuntime( 8790): 	... 9 more
[   +3 ms] I/Process ( 8790): Sending signal. PID: 8790 SIG: 9
[ +180 ms] Service protocol connection closed.
[        ] Lost connection to device.
```

```
[✓] Flutter (Channel master, v1.10.15-pre.103, on Linux, locale en_GB.UTF-8)
    • Flutter version 1.10.15-pre.103 at /media/data/flutter
    • Framework revision dd43da71fe (22 minutes ago), 2019-10-15 01:00:00 +0800
    • Engine revision eed171ff35
    • Dart version 2.6.0 (build 2.6.0-dev.7.0 965b8cb1d8)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /home/q/Android/Sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /media/data/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b16-5323222)
    • All Android licenses accepted.

[✓] Android Studio (version 3.4)
    • Android Studio at /media/data/android-studio
    • Flutter plugin version 37.0.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b16-5323222)

[!] Android Studio
    • Android Studio at /home/q/android-studio
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b16-5323222)

[✓] Connected device (1 available)
    • EVA L09 • MWS0217214001912 • android-arm64 • Android 7.0 (API 24)

! Doctor found issues in 1 category.
```

**Comment by chinmaygarde** [comment]
@xster seems to have a fix pending for this in https://github.com/flutter/engine/pull/17894

**Comment by pedromassangocode** [comment]
Removing label since the PR wasn't merged.

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
