### ISSUE TITLE
Animations throws a11y assert error

### ISSUE THREAD

**Issue by Addictorator** [flutter/flutter#42713]
## Steps to Reproduce
Not sure why this happens, but on every page in the app, whether it be an animated container automatically resizing itself, or scrollable widgets such as slivers, listviews and drawers, any adjustment to their position logs dozens of assertion errors stating the above error. I believe this is a similar problem as [#32210](https://github.com/flutter/flutter/issues/32210) except it does not crash due to merging [#8881](https://github.com/flutter/engine/pull/8881)?

This was tested and observed on android after upgrading from flutter v1.9.1+hotfix.2 to v1.10.7 due to a bug with heros that was fixed on a latter version, on a Huawei Mate 20 pro running EMUI 9.1.0 (Android v9), **but this assertion did not throw on Samsung Note 8, One UI v1.0, Android v9**. Prior to the flutter upgrade, there was no assertion warning or crash, with no changes to the code.

## Logs

flutter run --verbose:

```
[ +138 ms] E/AccessibilityBridge(30443): VirtualView node must not be the root node.
[ +128 ms] E/AccessibilityBridge(30443): VirtualView node must not be the root node.
[  +57 ms] E/AccessibilityBridge(30443): VirtualView node must not be the root node.
[  +31 ms] E/AccessibilityBridge(30443): VirtualView node must not be the root node.
[   +8 ms] W/libEGL  (30443): EGLNativeWindowType 0x716e947010 disconnect failed
[        ] I/SurfaceView(30443): delay destroy surface control
[   +4 ms] D/HwAppInnerBoostImpl(30443): asyncReportData mv.adt.location,2,1,1,0 interval=511
[        ] E/SurfaceView(30443): surfacePositionLost_uiRtSync  mSurfaceControl = null
[        ] W/libEGL  (30443): EGLNativeWindowType 0x71a1d89010 disconnect failed
[+3126 ms] W/HiTouch_PressGestureDetector(30443): Touch pointer move a lot. The moving distance of X is:25.5, limit is:60The moving distance of Y is:62.25, limit is:60
[  +63 ms] E/AccessibilityBridge(30443): VirtualView node must not be the root node.
[  +40 ms] E/AccessibilityBridge(30443): VirtualView node must not be the root node.
[  +65 ms] I/chatty  (30443): uid=10397(mv.adt.location) identical 1 line
[   +1 ms] E/AccessibilityBridge(30443): VirtualView node must not be the root node.
[  +28 ms] E/AccessibilityBridge(30443): VirtualView node must not be the root node.
[ +176 ms] I/chatty  (30443): uid=10397(mv.adt.location) identical 3 lines
[   +1 ms] E/AccessibilityBridge(30443): VirtualView node must not be the root node.
[   +9 ms] E/AccessibilityBridge(30443): VirtualView node must not be the root node.
[ +382 ms] E/AccessibilityBridge(30443): VirtualView node must not be the root node.
[  +28 ms] E/AccessibilityBridge(30443): VirtualView node must not be the root node.
[  +27 ms] E/AccessibilityBridge(30443): VirtualView node must not be the root node.
[ +196 ms] I/chatty  (30443): uid=10397(mv.adt.location) identical 6 lines
[   +1 ms] E/AccessibilityBridge(30443): VirtualView node must not be the root node.
[  +16 ms] E/AccessibilityBridge(30443): VirtualView node must not be the root node.
[  +41 ms] E/AccessibilityBridge(30443): VirtualView node must not be the root node.
[  +22 ms] E/AccessibilityBridge(30443): VirtualView node must not be the root node.
[ +122 ms] I/chatty  (30443): uid=10397(mv.adt.location) identical 2 lines
[   +1 ms] E/AccessibilityBridge(30443): VirtualView node must not be the root node.
[  +38 ms] E/AccessibilityBridge(30443): VirtualView node must not be the root node.
[ +163 ms] I/chatty  (30443): uid=10397(mv.adt.location) identical 3 lines
[   +1 ms] E/AccessibilityBridge(30443): VirtualView node must not be the root node.
[   +1 ms] E/AccessibilityBridge(30443): VirtualView node must not be the root node.
[  +42 ms] E/AccessibilityBridge(30443): VirtualView node must not be the root node.
[  +15 ms] E/AccessibilityBridge(30443): VirtualView node must not be the root node.
[  +84 ms] I/chatty  (30443): uid=10397(mv.adt.location) identical 1 line
[   +1 ms] E/AccessibilityBridge(30443): VirtualView node must not be the root node.
[  +16 ms] E/AccessibilityBridge(30443): VirtualView node must not be the root node.
[  +57 ms] E/AccessibilityBridge(30443): VirtualView node must not be the root node.
[   +6 ms] E/AccessibilityBridge(30443): VirtualView node must not be the root node.
[ +119 ms] I/chatty  (30443): uid=10397(mv.adt.location) identical 2 lines
[        ] E/AccessibilityBridge(30443): VirtualView node must not be the root node.
[   +3 ms] E/AccessibilityBridge(30443): VirtualView node must not be the root node.
[  +21 ms] E/AccessibilityBridge(30443): VirtualView node must not be the root node.
[  +31 ms] E/AccessibilityBridge(30443): VirtualView node must not be the root node.
[        ] E/AccessibilityBridge(30443): VirtualView node must not be the root node.
[  +35 ms] E/AccessibilityBridge(30443): VirtualView node must not be the root node.
[ +164 ms] I/chatty  (30443): uid=10397(mv.adt.location) identical 4 lines
[   +1 ms] E/AccessibilityBridge(30443): VirtualView node must not be the root node.
[  +25 ms] E/AccessibilityBridge(30443): VirtualView node must not be the root node.
[  +32 ms] E/AccessibilityBridge(30443): VirtualView node must not be the root node.
[ +192 ms] I/chatty  (30443): uid=10397(mv.adt.location) identical 4 lines
[        ] E/AccessibilityBridge(30443): VirtualView node must not be the root node.
[   +4 ms] E/AccessibilityBridge(30443): VirtualView node must not be the root node.
[  +32 ms] E/AccessibilityBridge(30443): VirtualView node must not be the root node.
[  +99 ms] I/chatty  (30443): uid=10397(mv.adt.location) identical 1 line
[        ] E/AccessibilityBridge(30443): VirtualView node must not be the root node.
[   +5 ms] E/AccessibilityBridge(30443): VirtualView node must not be the root node.
[  +36 ms] E/AccessibilityBridge(30443): VirtualView node must not be the root node.
[  +15 ms] E/AccessibilityBridge(30443): VirtualView node must not be the root node.
[  +18 ms] E/AccessibilityBridge(30443): VirtualView node must not be the root node.
[  +32 ms] E/AccessibilityBridge(30443): VirtualView node must not be the root node.
[ +177 ms] I/chatty  (30443): uid=10397(mv.adt.location) identical 6 lines
[        ] E/AccessibilityBridge(30443): VirtualView node must not be the root node.
[  +18 ms] E/AccessibilityBridge(30443): VirtualView node must not be the root node.
[  +65 ms] E/AccessibilityBridge(30443): VirtualView node must not be the root node.
[  +51 ms] E/AccessibilityBridge(30443): VirtualView node must not be the root node.
[  +72 ms] I/chatty  (30443): uid=10397(mv.adt.location) identical 1 line
[   +1 ms] E/AccessibilityBridge(30443): VirtualView node must not be the root node.
[  +23 ms] E/AccessibilityBridge(30443): VirtualView node must not be the root node.
[  +84 ms] I/chatty  (30443): uid=10397(mv.adt.location) identical 1 line
[   +3 ms] E/AccessibilityBridge(30443): VirtualView node must not be the root node.
[  +13 ms] E/AccessibilityBridge(30443): VirtualView node must not be the root node.
[  +38 ms] E/AccessibilityBridge(30443): VirtualView node must not be the root node.
[  +22 ms] E/AccessibilityBridge(30443): VirtualView node must not be the root node.
[  +33 ms] E/AccessibilityBridge(30443): VirtualView node must not be the root node.
[ +105 ms] I/chatty  (30443): uid=10397(mv.adt.location) identical 2 lines
[        ] E/AccessibilityBridge(30443): VirtualView node must not be the root node.
[   +8 ms] E/AccessibilityBridge(30443): VirtualView node must not be the root node.
[  +75 ms] I/chatty  (30443): uid=10397(mv.adt.location) identical 1 line
[   +1 ms] E/AccessibilityBridge(30443): VirtualView node must not be the root node.
[  +17 ms] E/AccessibilityBridge(30443): VirtualView node must not be the root node.
[  +38 ms] E/AccessibilityBridge(30443): VirtualView node must not be the root node.
[  +35 ms] E/AccessibilityBridge(30443): VirtualView node must not be the root node.
[  +26 ms] E/AccessibilityBridge(30443): VirtualView node must not be the root node.
[  +40 ms] E/AccessibilityBridge(30443): VirtualView node must not be the root node.
[  +16 ms] E/AccessibilityBridge(30443): VirtualView node must not be the root node.
[  +28 ms] E/AccessibilityBridge(30443): VirtualView node must not be the root node.
[  +10 ms] E/AccessibilityBridge(30443): VirtualView node must not be the root node.
[ +155 ms] I/chatty  (30443): uid=10397(mv.adt.location) identical 7 lines
[        ] E/AccessibilityBridge(30443): VirtualView node must not be the root node.
[   +4 ms] E/AccessibilityBridge(30443): VirtualView node must not be the root node.
[  +41 ms] I/chatty  (30443): uid=10397(mv.adt.location) identical 1 line
[        ] E/AccessibilityBridge(30443): VirtualView node must not be the root node.
[   +8 ms] E/AccessibilityBridge(30443): VirtualView node must not be the root node.
[ +194 ms] I/chatty  (30443): uid=10397(mv.adt.location) identical 10 lines
[   +1 ms] E/AccessibilityBridge(30443): VirtualView node must not be the root node.
[   +9 ms] E/AccessibilityBridge(30443): VirtualView node must not be the root node.
[ +200 ms] I/chatty  (30443): uid=10397(mv.adt.location) identical 10 lines
[        ] E/AccessibilityBridge(30443): VirtualView node must not be the root node.
[        ] E/AccessibilityBridge(30443): VirtualView node must not be the root node.
[  +10 ms] E/AccessibilityBridge(30443): VirtualView node must not be the root node.
[  +74 ms] I/chatty  (30443): uid=10397(mv.adt.location) identical 3 lines
[   +1 ms] E/AccessibilityBridge(30443): VirtualView node must not be the root node.
[   +4 ms] E/AccessibilityBridge(30443): VirtualView node must not be the root node.
[  +49 ms] E/AccessibilityBridge(30443): VirtualView node must not be the root node.
[  +58 ms] E/AccessibilityBridge(30443): VirtualView node must not be the root node.
[+4078 ms] V/AudioManager(30443): playSoundEffect   effectType: 0
[        ] V/AudioManager(30443): querySoundEffectsEnabled...
[ +196 ms] E/AccessibilityBridge(30443): VirtualView node must not be the root node.
[  +46 ms] E/AccessibilityBridge(30443): VirtualView node must not be the root node.
[  +59 ms] I/chatty  (30443): uid=10397(mv.adt.location) identical 1 line
[   +2 ms] E/AccessibilityBridge(30443): VirtualView node must not be the root node.
[  +78 ms] E/AccessibilityBridge(30443): VirtualView node must not be the root node.
[ +424 ms] E/AccessibilityBridge(30443): VirtualView node must not be the root node.
[ +503 ms] E/AccessibilityBridge(30443): VirtualView node must not be the root node.
[  +99 ms] E/AccessibilityBridge(30443): VirtualView node must not be the root node.
[ +515 ms] W/HiTouch_PressGestureDetector(30443): Touch pointer move a lot. The moving distance of X is:18.75, limit is:60The moving distance of Y is:63.75, limit is:60
```

No issues on `flutter analyze`

flutter doctor -v:

```
[√] Flutter (Channel beta, v1.10.7, on Microsoft Windows [Version 10.0.18362.418], locale en-US)
    • Flutter version 1.10.7 at D:\flutter
    • Framework revision e70236e36c (13 days ago), 2019-10-02 09:32:30 -0700
    • Engine revision 9e6314d348
    • Dart version 2.6.0 (build 2.6.0-dev.4.0 1103600280)

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.0)
    • Android SDK at D:\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.0
    • ANDROID_HOME = D:\Android\sdk
    • Java binary at: D:\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)
    • All Android licenses accepted.

[√] Android Studio (version 3.5)
    • Android Studio at D:\Android\Android Studio
    • Flutter plugin version 40.1.2
    • Dart plugin version 191.8423
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)
```

**Comment by Addictorator** [comment]
I'd like to note that the app doesn't crash on the device, just logs a11y assertion errors to the terminal, constantly. The application operates just fine, other than marginal (possibly imagined) lag, and making it hard to debug as it sweeps all other prints and logs under the rug.

**Comment by kleyos** [comment]
I encountered the same issue after upgrading flutter

**Comment by Mehedi50200** [comment]
Me too. I encountered the same issue after upgrading flutter

**Comment by dedvalson** [comment]
Me too.

**Comment by dedvalson** [comment]
This only happens on Beta, not on Stable.

**Comment by santiihoyos** [comment]
We have this issue after change to master.

**Comment by goderbauer** [comment]
@dnfield Recently fixed this issue. Can you please update to the latest master and try again?

**Comment by dnfield** [comment]
This was a bad log.  It was fixed flutter/engine@e3e2a38 - which should be in the framework by now.

**Comment by vip20** [comment]
@goderbauer I am facing this issue and after some time the app crashes saying stackoverflowerror
`I/chatty  ( 2987): uid=10628(com.example.whats_happening) identical 10 lines
E/AccessibilityBridge( 2987): VirtualView node must not be the root node.
D/ViewRootImpl@36f1a5[MainActivity]( 2987): ViewPostIme pointer 0
E/AccessibilityBridge( 2987): VirtualView node must not be the root node.
I/chatty  ( 2987): uid=10628(com.example.whats_happening) identical 1 line
E/AccessibilityBridge( 2987): VirtualView node must not be the root node.
D/ViewRootImpl@36f1a5[MainActivity]( 2987): ViewPostIme pointer 1
E/AccessibilityBridge( 2987): VirtualView node must not be the root node.
E/AccessibilityBridge( 2987): VirtualView node must not be the root node.
I/chatty  ( 2987): uid=10628(com.example.whats_happening) identical 5 lines
E/AccessibilityBridge( 2987): VirtualView node must not be the root node.
I/<app_Name>( 2987): Background concurrent copying GC freed 684230(16MB) AllocSpace objects, 0(0B) LOS objects, 41% free, 33MB/57MB, paused 962us total 279.112ms
D/AndroidRuntime( 2987): Shutting down VM
E/AndroidRuntime( 2987): FATAL EXCEPTION: main
E/AndroidRuntime( 2987): Process: com.example.whats_happening, PID: 2987
E/AndroidRuntime( 2987): java.lang.StackOverflowError: stack size 8MB
E/AndroidRuntime( 2987): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime( 2987): 	at io.flutter.view.AccessibilityViewEmbedder$ReflectionAccessors.getChildId(AccessibilityViewEmbedder.java:513)
E/AndroidRuntime( 2987): 	at io.flutter.view.AccessibilityViewEmbedder$ReflectionAccessors.access$500(AccessibilityViewEmbedder.java:413)
E/AndroidRuntime( 2987): 	at io.flutter.view.AccessibilityViewEmbedder.addChildrenToFlutterNode(AccessibilityViewEmbedder.java:174)
E/AndroidRuntime( 2987): 	at io.flutter.view.AccessibilityViewEmbedder.convertToFlutterNode(AccessibilityViewEmbedder.java:145)
E/AndroidRuntime( 2987): 	at io.flutter.view.AccessibilityViewEmbedder.getRootNode(AccessibilityViewEmbedder.java:91)
E/AndroidRuntime( 2987): 	at io.flutter.view.AccessibilityBridge.createAccessibilityNodeInfo(AccessibilityBridge.java:521)
E/AndroidRuntime( 2987): 	at android.view.View.populateVirtualStructure(View.java:9377)
E/AndroidRuntime( 2987): 	at android.view.View.populateVirtualStructure(View.java:9380)
E/AndroidRuntime( 2987): 	at android.view.View.populateVirtualStructure(View.java:9380)

`

**Comment by stephantual** [comment]
Nope, still there running on an physical device - it's so bad that chatty gets involved to suppress the flood of "VirtualView node must not be the root node." messages. 

[√] Flutter (Channel stable, v1.12.13+hotfix.9, on Microsoft Windows [Version 10.0.18363.752], locale en-US)
    • Flutter version 1.12.13+hotfix.9 at C:\Users\steph\githubapps\flutter
    • Framework revision f139b11009 (12 days ago), 2020-03-30 13:57:30 -0700
    • Engine revision af51afceb8
    • Dart version 2.7.2


[√] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at C:\Users\steph\AppData\Local\Android\Sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)
    • All Android licenses accepted.

[√] Android Studio (version 3.6)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 45.0.1
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)

[√] VS Code (version 1.43.2)
    • VS Code at C:\Users\steph\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.8.1

[√] Connected device (1 available)
    • EVR L29 • BEV5T18C08003222 • android-arm64 • Android 10 (API 29)
