### ISSUE TITLE
hot reload problem, on latest version of flutter on master channel

### ISSUE THREAD

**Issue by DJafari** [flutter/flutter#42801]
after updating to latest version of flutter on channel master, when i press hot reload button, this error returned 

```
Hot Reload java.io.IOException: error from app.restart: "type 'LocalDirectory' is not a subtype of type 'File'" "
#0 _ManifestAssetBundle.needsBuild (package:flutter_tools/src/asset.dart:97:7)
#1 HotRunner._updateDevFS (package:flutter_tools/src/run_hot.dart:288:44)
#2 HotRunner._reloadSources (package:flutter_tools/src/run_hot.dart:692:47)
#3 HotRunner._hotReloadHelper (package:flutter_tools/src/run_hot.dart:632:22)
#4 HotRunner.restart (package:flutter_tools/src/run_hot.dart:555:42)
#5 AppInstance.restart (package:flutter_tools/src/commands/daemon.dart:914:19)
#6 AppDomain.restart.  (package:flutter_tools/src/commands/daemon.dart:568:18)
#7 AppContext.run.  (package:flutter_tools/src/base/context.dart:157:29)
#8 _rootRun (dart:async/zone.dart:1124:13)
#9 _CustomZone.run (dart:async/zone.dart:1021:19)
#10 _runZoned (dart:async/zone.dart:1516:10)
#11 runZoned (dart:async/zone.dart:1463:12)
#12 AppContext.run (package:flutter_tools/src/base/context.dart:156:18)
#13 AppInstance._runInZone (package:flutter_tools/src/commands/daemon.dart:927:20)
#14 AppDomain.restart (package:flutter_tools/src/commands/daemon.dart:567:32)
#15 Domain.handleCommand.  (package:flutter_tools/src/commands/daemon.dart:195:34)
#16 new Future.sync (dart:async/future.dart:224:31)
#17 Domain.handleCommand (package:flutter_tools/src/commands/daemon.dart:192:77)
#18 Daemon._handleRequest (package:flutter_tools/src/commands/daemon.dart:149:26)
#19 _rootRunUnary (dart:async/zone.dart:1132:38)
#20 _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#21 _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
#22 _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#23 _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#24 _ForwardingStreamSubscription._add (dart:async/stream_pipe.dart:132:11)
#25 _MapStream._handleData (dart:async/stream_pipe.dart:232:10)
#26 _ForwardingStreamSubscription._handleData (dart:async/stream_pipe.dart:164:13)
#27 _rootRunUnary (dart:async/zone.dart:1132:38)
#28 _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#29 _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
#30 _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#31 _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#32 _ForwardingStreamSubscription._add (dart:async/stream_pipe.dart:132:11)
#33 _WhereStream._handleData (dart:async/stream_pipe.dart:207:12)
#34 _ForwardingStreamSubscription._handleData (dart:async/stream_pipe.dart:164:13)
#35 _rootRunUnary (dart:async/zone.dart:1132:38)
#36 _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#37 _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
#38 _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#39 _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#40 _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:68:11)
#41 _EventSinkWrapper.add (dart:async/stream_transformers.dart:15:11)
#42 _StringAdapterSink.add (dart:convert/string_conversion.dart:236:11)
#43 _LineSplitterSink._addLines (dart:convert/line_splitter.dart:150:13)
#44 _LineSplitterSink.addSlice (dart:convert/line_splitter.dart:125:5)
#45 StringConversionSinkMixin.add (dart:convert/string_conversion.dart:163:5)
#46 _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:120:24)
#47 _rootRunUnary (dart:async/zone.dart:1132:38)
#48 _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#49 _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
#50 _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#51 _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#52 _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:68:11)
#53 _EventSinkWrapper.add (dart:async/stream_transformers.dart:15:11)
#54 _StringAdapterSink.add (dart:convert/string_conversion.dart:236:11)
#55 _StringAdapterSink.addSlice (dart:convert/string_conversion.dart:241:7)
#56 _Utf8ConversionSink.addSlice (dart:convert/string_conversion.dart:312:20)
#57 _Utf8ConversionSink.add (dart:convert/string_conversion.dart:305:5)
#58 _ConverterStreamEventSink.add (dart:convert/chunked_conversion.dart:72:18)
#59 _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:120:24)
#60 _rootRunUnary (dart:async/zone.dart:1132:38)
#61 _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#62 _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
#63 _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#64 _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#65 _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:764:19)
#66 _StreamController._add (dart:async/stream_controller.dart:640:7)
#67 _StreamController.add (dart:async/stream_controller.dart:586:5)
#68 _Socket._onData (dart:io-patch/socket_patch.dart:1829:41)
#69 _rootRunUnary (dart:async/zone.dart:1136:13)
#70 _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#71 _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
#72 _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#73 _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#74 _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:764:19)
#75 _StreamController._add (dart:async/stream_controller.dart:640:7)
#76 _StreamController.add (dart:async/stream_controller.dart:586:5)
#77 new _RawSocket.  (dart:io-patch/socket_patch.dart:1377:33)
#78 _NativeSocket.issueReadEvent.issue (dart:io-patch/socket_patch.dart:897:14)
#79 _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#80 _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#81 _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:116:13)
#82 _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:173:5)
"
```

when i pressed normal reload, hangs on performing reload and don't work without any error

**Comment by DJafari** [comment]
for reproduced this error create a folder with name `assets` and create another folder in `assets` folder with `test` name

```
.
.
lib
assets
-- test
android
ios
...
```

and in your `pubspec.yml` 

```
flutter:
  uses-material-design: true
  assets:
    - assets/
```

run app, and pressend on hot reload!

**Comment by jonahwilliams** [comment]
Fixed with https://github.com/flutter/flutter/pull/42791
