### ISSUE TITLE
NoSuchMethodError: The getter 'height' was called on null. Receiver: null Tried calling: height

### ISSUE THREAD

**Issue by fightingLT** [flutter/flutter#42818]
deviceInfo: 
systemName: iOS, 
systemVersion: 12.4.1,
model: iPhone

## Logs

```
sliver_multi_box_adaptor.dart in RenderSliverMultiBoxAdaptor.paint at line 639
object.dart in RenderObject._paintWithContext at line 2193
object.dart in PaintingContext.paintChild at line 184
sliver_padding.dart in RenderSliverPadding.paint at line 322
object.dart in RenderObject._paintWithContext at line 2193
object.dart in PaintingContext.paintChild at line 184
viewport.dart in RenderViewportBase._paintContents at line 527
object.dart in PaintingContext.pushLayer at line 384
object.dart in PaintingContext.pushClipRect at line 426
viewport.dart in RenderViewportBase.paint at line 518
object.dart in RenderObject._paintWithContext at line 2193
object.dart in PaintingContext._repaintCompositedChild at line 135
object.dart in PaintingContext.repaintCompositedChild at line 95
object.dart in PaintingContext._compositeChild at line 201
object.dart in PaintingContext.paintChild at line 182
proxy_box.dart in RenderProxyBoxMixin.paint at line 123
object.dart in RenderObject._paintWithContext at line 2193
object.dart in PaintingContext.paintChild at line 184
proxy_box.dart in RenderProxyBoxMixin.paint at line 123
object.dart in RenderObject._paintWithContext at line 2193
object.dart in PaintingContext.paintChild at line 184
proxy_box.dart in RenderProxyBoxMixin.paint at line 123
object.dart in RenderObject._paintWithContext at line 2193
object.dart in PaintingContext.paintChild at line 184
proxy_box.dart in RenderProxyBoxMixin.paint at line 123
object.dart in RenderObject._paintWithContext at line 2193
object.dart in PaintingContext.paintChild at line 184
proxy_box.dart in RenderProxyBoxMixin.paint at line 123
object.dart in RenderObject._paintWithContext at line 2193
object.dart in PaintingContext.paintChild at line 184
proxy_box.dart in RenderProxyBoxMixin.paint at line 123
object.dart in RenderObject._paintWithContext at line 2193
object.dart in PaintingContext.paintChild at line 184
box.dart in RenderBoxContainerDefaultsMixin.defaultPaint at line 2501
flex.dart in RenderFlex.paint at line 948
object.dart in RenderObject._paintWithContext at line 2193
object.dart in PaintingContext.paintChild at line 184
shifted_box.dart in RenderShiftedBox.paint at line 70
object.dart in RenderObject._paintWithContext at line 2193
object.dart in PaintingContext.paintChild at line 184
box.dart in RenderBoxContainerDefaultsMixin.defaultPaint at line 2501
custom_layout.dart in RenderCustomMultiChildLayoutBox.paint at line 361
object.dart in RenderObject._paintWithContext at line 2193
object.dart in PaintingContext.paintChild at line 184
proxy_box.dart in RenderProxyBoxMixin.paint at line 123
material.dart in _RenderInkFeatures.paint at line 548
object.dart in RenderObject._paintWithContext at line 2193
object.dart in PaintingContext.paintChild at line 184
proxy_box.dart in RenderProxyBoxMixin.paint at line 123
object.dart in PaintingContext.pushLayer at line 384
proxy_box.dart in RenderPhysicalModel.paint at line 1749
object.dart in RenderObject._paintWithContext at line 2193
object.dart in PaintingContext.paintChild at line 184
shifted_box.dart in RenderShiftedBox.paint at line 70
object.dart in RenderObject._paintWithContext at line 2193
object.dart in PaintingContext.paintChild at line 184
proxy_box.dart in RenderProxyBoxMixin.paint at line 123
proxy_box.dart in RenderDecoratedBox.paint at line 1989
object.dart in RenderObject._paintWithContext at line 2193
object.dart in PaintingContext.paintChild at line 184
box.dart in RenderBoxContainerDefaultsMixin.defaultPaint at line 2501
stack.dart in RenderStack.paintStack at line 594
stack.dart in RenderStack.paint at line 602
object.dart in RenderObject._paintWithContext at line 2193
object.dart in PaintingContext.paintChild at line 184
box.dart in RenderBoxContainerDefaultsMixin.defaultPaint at line 2501
custom_layout.dart in RenderCustomMultiChildLayoutBox.paint at line 361
object.dart in RenderObject._paintWithContext at line 2193
object.dart in PaintingContext.paintChild at line 184
proxy_box.dart in RenderProxyBoxMixin.paint at line 123
material.dart in _RenderInkFeatures.paint at line 548
object.dart in RenderObject._paintWithContext at line 2193
object.dart in PaintingContext.paintChild at line 184
proxy_box.dart in RenderProxyBoxMixin.paint at line 123
object.dart in PaintingContext.pushLayer at line 384
proxy_box.dart in RenderPhysicalModel.paint at line 1749
object.dart in RenderObject._paintWithContext at line 2193
object.dart in PaintingContext.paintChild at line 184
proxy_box.dart in RenderProxyBoxMixin.paint at line 123
object.dart in RenderObject._paintWithContext at line 2193
object.dart in PaintingContext._repaintCompositedChild at line 135
object.dart in PaintingContext.repaintCompositedChild at line 95
object.dart in PaintingContext._compositeChild at line 201
object.dart in PaintingContext.paintChild at line 182
proxy_box.dart in RenderProxyBoxMixin.paint at line 123
object.dart in RenderObject._paintWithContext at line 2193
object.dart in PaintingContext.paintChild at line 184
proxy_box.dart in RenderAnimatedOpacity.paint at line 919
object.dart in RenderObject._paintWithContext at line 2193
object.dart in PaintingContext.paintChild at line 184
proxy_box.dart in RenderProxyBoxMixin.paint at line 123
object.dart in RenderObject._paintWithContext at line 2193
object.dart in PaintingContext._repaintCompositedChild at line 135
object.dart in PaintingContext.repaintCompositedChild at line 95
object.dart in PaintingContext._compositeChild at line 201
object.dart in PaintingContext.paintChild at line 182
proxy_box.dart in RenderProxyBoxMixin.paint at line 123
object.dart in RenderObject._paintWithContext at line 2193
object.dart in PaintingContext.paintChild at line 184
proxy_box.dart in RenderProxyBoxMixin.paint at line 123
proxy_box.dart in RenderOffstage.paint at line 3153
object.dart in RenderObject._paintWithContext at line 2193
object.dart in PaintingContext.paintChild at line 184
box.dart in RenderBoxContainerDefaultsMixin.defaultPaint at line 2501
stack.dart in RenderStack.paintStack at line 594
stack.dart in RenderStack.paint at line 602
object.dart in RenderObject._paintWithContext at line 2193
object.dart in PaintingContext.paintChild at line 184
proxy_box.dart in RenderProxyBoxMixin.paint at line 123
object.dart in RenderObject._paintWithContext at line 2193
object.dart in PaintingContext.paintChild at line 184
proxy_box.dart in RenderProxyBoxMixin.paint at line 123
object.dart in RenderObject._paintWithContext at line 2193
object.dart in PaintingContext.paintChild at line 184
proxy_box.dart in RenderProxyBoxMixin.paint at line 123
object.dart in RenderObject._paintWithContext at line 2193
object.dart in PaintingContext.paintChild at line 184
proxy_box.dart in RenderProxyBoxMixin.paint at line 123
object.dart in RenderObject._paintWithContext at line 2193
object.dart in PaintingContext.paintChild at line 184
proxy_box.dart in RenderProxyBoxMixin.paint at line 123
object.dart in RenderObject._paintWithContext at line 2193
object.dart in PaintingContext.paintChild at line 184
box.dart in RenderBoxContainerDefaultsMixin.defaultPaint at line 2501
stack.dart in RenderStack.paintStack at line 594
stack.dart in RenderStack.paint at line 602
object.dart in RenderObject._paintWithContext at line 2193
object.dart in PaintingContext.paintChild at line 184
proxy_box.dart in RenderProxyBoxMixin.paint at line 123
object.dart in RenderObject._paintWithContext at line 2193
object.dart in PaintingContext.paintChild at line 184
box.dart in RenderBoxContainerDefaultsMixin.defaultPaint at line 2501
stack.dart in RenderStack.paintStack at line 594
stack.dart in RenderStack.paint at line 602
object.dart in RenderObject._paintWithContext at line 2193
object.dart in PaintingContext.paintChild at line 184
view.dart in RenderView.paint at line 196
object.dart in RenderObject._paintWithContext at line 2193
object.dart in PaintingContext._repaintCompositedChild at line 135
object.dart in PaintingContext.repaintCompositedChild at line 95
object.dart in PipelineOwner.flushPaint at line 937
binding.dart in RendererBinding.drawFrame at line 343
binding.dart in WidgetsBinding.drawFrame at line 761
binding.dart in RendererBinding._handlePersistentFrameCallback at line 280
binding.dart in SchedulerBinding._invokeFrameCallback at line 1033
binding.dart in SchedulerBinding.handleDrawFrame at line 975
binding.dart in SchedulerBinding._handleDrawFrame at line 891
```

```
[✓] Flutter (Channel stable, v1.9.1+hotfix.4, on Mac OS X 10.14.5 18F132, locale en-CN)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 11.0)
[✓] Android Studio (version 3.4)
[✓] VS Code (version 1.39.0)
```

**Comment by BondarenkoStas** [comment]
@fightingLT Please provide  a small self-contained app that reproduces the problem. You can include small examples [inline if they're enclosed by backticks](https://help.github.com/en/articles/creating-and-highlighting-code-blocks), or just provide a public link to a github "gist" - https://gist.github.com/.

**Comment by lizhangqu** [comment]
I meet this problem also, but I can't reproduce it. It happened in production environment.
![https://si.geilicdn.com/img-41ec0000016e68f828ff0a2064e0-unadjust_1262_1094.png](https://si.geilicdn.com/img-41ec0000016e68f828ff0a2064e0-unadjust_1262_1094.png)

**Comment by lizhangqu** [comment]
```
NoSuchMethodError: The getter 'height' was called on null. Receiver: null Tried calling: height

1 #0 RenderSliverMultiBoxAdaptor.paintExtentOf (package:flutter/src/rendering/sliver_multi_box_adaptor.dart:554)
2 #1 RenderSliverMultiBoxAdaptor.paint (package:flutter/src/rendering/sliver_multi_box_adaptor.dart:639)
3 #2 RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2193)
4 #3 PaintingContext.paintChild (package:flutter/src/rendering/object.dart:184)
5 #4 RenderViewportBase._paintContents (package:flutter/src/rendering/viewport.dart:527)
6 #5 PaintingContext.pushLayer (package:flutter/src/rendering/object.dart:384)
7 #6 PaintingContext.pushClipRect (package:flutter/src/rendering/object.dart:426)
8 #7 RenderViewportBase.paint (package:flutter/src/rendering/viewport.dart:518)
9 #8 RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2193)
10 #9 PaintingContext._repaintCompositedChild (package:flutter/src/rendering/object.dart:135)
11 #10 PaintingContext.repaintCompositedChild (package:flutter/src/rendering/object.dart:95)
12 #11 PipelineOwner.flushPaint (package:flutter/src/rendering/object.dart:937)
13 #12 RendererBinding.drawFrame (package:flutter/src/rendering/binding.dart:343)
14 #13 WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:761)
15 #14 RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:280)
16 #15 SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1033)
17 #16 SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:975)
18 #17 SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:891)
19 #18 _rootRun (dart:async/zone.dart:1124)
20 #19 _CustomZone.run (dart:async/zone.dart:1021)
21 #20 _CustomZone.runGuarded (dart:async/zone.dart:923)
22 #21 _invoke (dart:ui/hooks.dart:249)
23 #22 _drawFrame (dart:ui/hooks.dart:207)


```

**Comment by kuhnroyal** [comment]
I am having the same issue reported in Sentry, I am sure it is my own fault but I can not pinpoint it. From the error/stacktraces above, how could one possibly determine the containing widget that caused this?

**Comment by yashmittalJTG** [comment]
> I am having the same issue reported in Sentry, I am sure it is my own fault but I can not pinpoint it. From the error/stacktraces above, how could one possibly determine the containing widget that caused this when running in release mode?

same issue i am facing let me know if you fixed it
