### ISSUE TITLE
flutter doctor  git: error: unable to find utility "git", not a developer tool or in PATH

### ISSUE THREAD

**Issue by xuzheng94** [flutter/flutter#42821]
Xcode 11,  sudo xcode-select --switch /Applications/Xcode.app/Contents/Developer

## command

flutter doctor

## exception

VersionCheckError: VersionCheckError: Command exited with code 72: git log -n 1 --pretty=format:%ad --date=iso
Standard error: git: error: sh -c '/Applications/Xcode11.app/Contents/Developer/usr/bin/xcodebuild -sdk /Applications/Xcode11.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk -find git 2> /dev/null' failed with exit code 17664: (null) (errno=Invalid argument)
git: error: unable to find utility "git", not a developer tool or in PATH

```
#0      _runSync (package:flutter_tools/src/version.dart:525:5)
#1      FlutterVersion._latestGitCommitDate (package:flutter_tools/src/version.dart:145:12)
#2      FlutterVersion.frameworkCommitDate (package:flutter_tools/src/version.dart:133:37)
#3      FlutterVersion.frameworkDate (package:flutter_tools/src/version.dart:95:31)
#4      FlutterValidator.validate (package:flutter_tools/src/doctor.dart:518:127)
<asynchronous suspension>
#5      Doctor.startValidatorTasks (package:flutter_tools/src/doctor.dart:140:52)
#6      Doctor.diagnose (package:flutter_tools/src/doctor.dart:211:41)
<asynchronous suspension>
#7      DoctorCommand.runCommand (package:flutter_tools/src/commands/doctor.dart:59:39)
<asynchronous suspension>
#8      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:490:18)
<asynchronous suspension>
#9      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:407:33)
<asynchronous suspension>
#10     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:154:29)
<asynchronous suspension>
#11     _rootRun (dart:async/zone.dart:1124:13)
#12     _CustomZone.run (dart:async/zone.dart:1021:19)
#13     _runZoned (dart:async/zone.dart:1516:10)
#14     runZoned (dart:async/zone.dart:1463:12)
#15     AppContext.run (package:flutter_tools/src/base/context.dart:153:18)
<asynchronous suspension>
#16     FlutterCommand.run (package:flutter_tools/src/runner/flutter_command.dart:397:20)
#17     CommandRunner.runCommand (package:args/command_runner.dart:197:27)
<asynchronous suspension>
#18     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:402:21)
<asynchronous suspension>
#19     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:154:29)
<asynchronous suspension>
#20     _rootRun (dart:async/zone.dart:1124:13)
#21     _CustomZone.run (dart:async/zone.dart:1021:19)
#22     _runZoned (dart:async/zone.dart:1516:10)
#23     runZoned (dart:async/zone.dart:1463:12)
#24     AppContext.run (package:flutter_tools/src/base/context.dart:153:18)
<asynchronous suspension>
#25     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:356:19)
<asynchronous suspension>
#26     CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:112:25)
#27     new Future.sync (dart:async/future.dart:224:31)
#28     CommandRunner.run (package:args/command_runner.dart:112:14)
#29     FlutterCommandRunner.run (package:flutter_tools/src/runner/flutter_command_runner.dart:242:18)
#30     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:63:22)
<asynchronous suspension>
#31     _rootRun (dart:async/zone.dart:1124:13)
#32     _CustomZone.run (dart:async/zone.dart:1021:19)
#33     _runZoned (dart:async/zone.dart:1516:10)
#34     runZoned (dart:async/zone.dart:1500:12)
#35     run.<anonymous closure> (package:flutter_tools/runner.dart:61:18)
<asynchronous suspension>
#36     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:154:29)
<asynchronous suspension>
#37     _rootRun (dart:async/zone.dart:1124:13)
#38     _CustomZone.run (dart:async/zone.dart:1021:19)
#39     _runZoned (dart:async/zone.dart:1516:10)
#40     runZoned (dart:async/zone.dart:1463:12)
#41     AppContext.run (package:flutter_tools/src/base/context.dart:153:18)
<asynchronous suspension>
#42     runInContext (package:flutter_tools/src/context_runner.dart:58:24)
<asynchronous suspension>
#43     run (package:flutter_tools/runner.dart:50:10)
#44     main (package:flutter_tools/executable.dart:65:9)
<asynchronous suspension>
#45     main (file:///Users/Sunny/Desktop/Flutter/flutter/packages/flutter_tools/bin/flutter_tools.dart:8:3)
#46     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:303:32)
#47     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:12)
```

## flutter doctor

```
encountered exception: VersionCheckError: Command exited with code 72: git log -n 1 --pretty=format:%ad --date=iso
Standard error: git: error: sh -c '/Applications/Xcode11.app/Contents/Developer/usr/bin/xcodebuild -sdk /Applications/Xcode11.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk -find git 2> /dev/null' failed with exit code 17664: (null) (errno=Invalid argument)
git: error: unable to find utility "git", not a developer tool or in PATH


#0      _runSync (package:flutter_tools/src/version.dart:525:5)
#1      FlutterVersion._latestGitCommitDate (package:flutter_tools/src/version.dart:145:12)
#2      FlutterVersion.frameworkCommitDate (package:flutter_tools/src/version.dart:133:37)
#3      FlutterVersion.frameworkDate (package:flutter_tools/src/version.dart:95:31)
#4      FlutterValidator.validate (package:flutter_tools/src/doctor.dart:518:127)
<asynchronous suspension>
#5      Doctor.startValidatorTasks (package:flutter_tools/src/doctor.dart:140:52)
#6      Doctor.diagnose (package:flutter_tools/src/doctor.dart:211:41)
<asynchronous suspension>
#7      _doctorText.<anonymous closure> (package:flutter_tools/runner.dart:202:26)
#8      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:154:29)
<asynchronous suspension>
#9      _rootRun (dart:async/zone.dart:1124:13)
#10     _CustomZone.run (dart:async/zone.dart:1021:19)
#11     _runZoned (dart:async/zone.dart:1516:10)
#12     runZoned (dart:async/zone.dart:1463:12)
#13     AppContext.run (package:flutter_tools/src/base/context.dart:153:18)
<asynchronous suspension>
#14     _doctorText (package:flutter_tools/runner.dart:201:19)
<asynchronous suspension>
#15     _createLocalCrashReport (package:flutter_tools/runner.dart:179:32)
<asynchronous suspension>
#16     _handleToolError (package:flutter_tools/runner.dart:134:33)
<asynchronous suspension>
#17     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:68:22)
<asynchronous suspension>
#18     _rootRun (dart:async/zone.dart:1124:13)
#19     _CustomZone.run (dart:async/zone.dart:1021:19)
#20     _runZoned (dart:async/zone.dart:1516:10)
#21     runZoned (dart:async/zone.dart:1500:12)
#22     run.<anonymous closure> (package:flutter_tools/runner.dart:61:18)
<asynchronous suspension>
#23     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:154:29)
<asynchronous suspension>
#24     _rootRun (dart:async/zone.dart:1124:13)
#25     _CustomZone.run (dart:async/zone.dart:1021:19)
#26     _runZoned (dart:async/zone.dart:1516:10)
#27     runZoned (dart:async/zone.dart:1463:12)
#28     AppContext.run (package:flutter_tools/src/base/context.dart:153:18)
<asynchronous suspension>
#29     runInContext (package:flutter_tools/src/context_runner.dart:58:24)
<asynchronous suspension>
#30     run (package:flutter_tools/runner.dart:50:10)
#31     main (package:flutter_tools/executable.dart:65:9)
<asynchronous suspension>
#32     main (file:///Users/Sunny/Desktop/Flutter/flutter/packages/flutter_tools/bin/flutter_tools.dart:8:3)
#33     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:303:32)
#34     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:12)
```

**Comment by BondarenkoStas** [comment]
@xuzheng94 are you sure git is in the path? can you run git from terminal?

**Comment by xuzheng94** [comment]
> @xuzheng94 are you sure git is in the path? can you run git from terminal?

Yes I'm sure.  I just changed my IDE to Xcode11 ( I run "sudo xcode-select --switch /Applications/Xcode11.app/Contents/Developer"), then it happened.  before this, it was always succeed.
![image](https://user-images.githubusercontent.com/15907568/66913289-eb71ee00-f046-11e9-8fb1-df512a18ee50.png)

**Comment by BondarenkoStas** [comment]
@xuzheng94 please try if `xcode-select --install` will fix it

**Comment by xuzheng94** [comment]
> @xuzheng94 please try if `xcode-select --install` will fix it. can you run git from terminal?

it works， thank u

**Comment by BondarenkoStas** [comment]
Cool, I found it here https://davidwalsh.name/fix-git-high-sierra-upgrade. It seems to have nothing to do with flutter. I'm glad it's solved, now closing the issue.
