### ISSUE TITLE
[all Firebase plugins] no permissions in Iran 

### ISSUE THREAD

**Issue by aliyazdi75** [flutter/flutter#42840]
It's not fair, 
We are all humans.
Don't treat us like an animal!

Since this morning:
Your client does not have permission to get URL `/identitytoolkit/v3/relyingparty/verifyAssertion` from this server. That’s all we know.`
```E/flutter (14498): [ERROR:flutter/lib/ui/ui_dart_state.cc(148)] Unhandled Exception: PlatformException(FirebaseException, An internal error has occurred. [ <!DOCTYPE html>
E/flutter (14498): <html lang=en>
E/flutter (14498):   <meta charset=utf-8>
E/flutter (14498):   <meta name=viewport content="initial-scale=1, minimum-scale=1, width=device-width">
E/flutter (14498):   <title>Error 403 (Forbidden)!!1</title>
E/flutter (14498):   <style>
E/flutter (14498):     *{margin:0;padding:0}html,code{font:15px/22px arial,sans-serif}html{background:#fff;color:#222;padding:15px}body{margin:7% auto 0;max-width:390px;min-height:180px;padding:30px 0 15px}* > body{background:url(//www.google.com/images/errors/robot.png) 100% 5px no-repeat;padding-right:205px}p{margin:11px 0 22px;overflow:hidden}ins{color:#777;text-decoration:none}a img{border:0}@media screen and (max-width:772px){body{background:none;margin-top:0;max-width:none;padding-right:0}}#logo{background:url(//www.google.com/images/branding/googlelogo/1x/googlelogo_color_150x54dp.png) no-repeat;margin-left:-5px}@media only screen and (min-resolution:192dpi){#logo{background:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) no-repeat 0% 0%/100% 100%;-moz-border-image:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) 0}}@media only screen and (-webkit-min-device-pixel-ratio:2){#logo{background:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) no-repeat;-webkit-background-size:100% 100%}}#logo{display:inline-block;height:54px;width:150px}
E/flutter (14498):   </style>
E/flutter (14498):   <a href=//www.google.com/><span id=logo aria-label=Google></span></a>
E/flutter (14498):   <p><b>403.</b> <ins>That’s an error.</ins>
E/flutter (14498):   <p>Your client does not have permission to get URL <code>/identitytoolkit/v3/relyingparty/verifyAssertion</code> from this server.  <ins>That’s all we know.</ins> ], null)
E/flutter (14498): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:569:7)
E/flutter (14498): #1      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:316:33)
E/flutter (14498): <asynchronous suspension>
E/flutter (14498): #2      MethodChannel.invokeMapMethod (package:flutter/src/services/platform_channel.dart:344:48)
E/flutter (14498): <asynchronous suspension>
E/flutter (14498): #3      FirebaseAuth.signInWithCredential (package:firebase_auth/src/firebase_auth.dart:257:23)
E/flutter (14498): <asynchronous suspension>
E/flutter (14498): #4      AuthState._signInWithGoogle (package:ceit94/screens/auth.dart:226:22)
E/flutter (14498): <asynchronous suspension>
E/flutter (14498): #5      AuthState.build.<anonymous closure>.<anonymous closure> (package:ceit94/screens/auth.dart:115:25)
E/flutter (14498): <asynchronous suspension>
E/flutter (14498): #6      _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:654:14)
E/flutter (14498): #7      _InkResponseState.build.<anonymous closure> (package:flutter/src/material/ink_well.dart:729:32)
E/flutter (14498): #8      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:182:24)
E/flutter (14498): #9      TapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:365:11)
E/flutter (14498): #10     TapGestureRecognizer.handlePrimaryPointer (package:flutter/src/gestures/tap.dart:275:7)
E/flutter (14498): #11     PrimaryPointerGestureRecognizer.handleEvent (package:flutter/src/gestures/recognizer.dart:455:9)
E/flutter (14498): #12     PointerRouter._dispatch (package:flutter/src/gestures/pointer_router.dart:75:13)
E/flutter (14498): #13     PointerRouter.route (package:flutter/src/gestures/pointer_router.dart:102:11)
E/flutter (14498): #14     GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:218:19)
E/flutter (14498): #15     GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:198:22)
E/flutter (14498): #16     GestureBinding._handlePointerEvent (package:flutter/src/gestures/binding.dart:156:7)
E/flutter (14498): #17     GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:102:7)
E/flutter (14498): #18     GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:86:7)
E/flutter (14498): #19     _rootRunUnary (dart:async/zone.dart:1136:13)
E/flutter (14498): #20     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
E/flutter (14498): #21     _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
E/flutter (14498): #22     _invoke1 (dart:ui/hooks.dart:263:10)
E/flutter (14498): #23     _dispatchPointerDataPacket (dart:ui/hooks.dart:172:5)
```

**Comment by BondarenkoStas** [comment]
@aliyazdi75 Please file this issue to https://github.com/FirebaseExtended/flutterfire/issues as they are being managed there, and close the issue here.

**Comment by aliyazdi75** [comment]
@BondarenkoStas 
I did, but don't wanna close this for your wrong policy about our people.

**Comment by stuartmorgan** [comment]
The Flutter team does not control Firebase services or servers, so this is unrelated to Flutter.
