### ISSUE TITLE
 The following assertion was thrown while dispatching notifications for FocusNode: I/flutter (27495): RenderBox was not laid out: RenderEditable#6bcc3 NEEDS-LAYOUT NEEDS-PAINT

### ISSUE THREAD

**Issue by Troublebreaker** [flutter/flutter#42908]
The following assertion was thrown while dispatching notifications for FocusNode: I/flutter (27495): RenderBox was not laid out: RenderEditable#6bcc3 NEEDS-LAYOUT NEEDS-PAINT

**Comment by BondarenkoStas** [comment]
@Troublebreaker please provide your flutter doctor -v output. Please provide  a small self-contained app that demonstrates the problem. You can include small examples [inline if they're enclosed by backticks](https://help.github.com/en/articles/creating-and-highlighting-code-blocks), or just provide a public link to a github "gist" - https://gist.github.com/.
Probably it's an implementation error.

**Comment by Hixie** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
  
Thanks for your contribution.

**Comment by 0xfeb** [comment]
I have the same problem. 

Exception tree:
2020-02-11 12:04:37.442899+0800 Runner[627:821570] flutter: ══╡ EXCEPTION CAUGHT BY FOUNDATION LIBRARY ╞════════════════════════════════════════════════════════
2020-02-11 12:04:37.443027+0800 Runner[627:821570] flutter: The following assertion was thrown while dispatching notifications for FocusNode:
2020-02-11 12:04:37.443077+0800 Runner[627:821570] flutter: RenderBox was not laid out: RenderEditable#63c00 NEEDS-LAYOUT NEEDS-PAINT
2020-02-11 12:04:37.443121+0800 Runner[627:821570] flutter: 'package:flutter/src/rendering/box.dart':
2020-02-11 12:04:37.443163+0800 Runner[627:821570] flutter: Failed assertion: line 1687 pos 12: 'hasSize'
2020-02-11 12:04:37.443201+0800 Runner[627:821570] flutter:
2020-02-11 12:04:37.447333+0800 Runner[627:821570] flutter: Either the assertion indicates an error in the framework itself, or we should provide substantially
2020-02-11 12:04:37.447409+0800 Runner[627:821570] flutter: more information in this error message to help you determine and fix the underlying cause.
2020-02-11 12:04:37.447451+0800 Runner[627:821570] flutter: In either case, please report this assertion by filing a bug on GitHub:
2020-02-11 12:04:37.447501+0800 Runner[627:821570] flutter:   https://github.com/flutter/flutter/issues/new?template=BUG.md
2020-02-11 12:04:37.447539+0800 Runner[627:821570] flutter:
2020-02-11 12:04:37.447576+0800 Runner[627:821570] flutter: When the exception was thrown, this was the stack:
2020-02-11 12:04:37.448877+0800 Runner[627:821570] flutter: #2      RenderBox.size (package:flutter/src/rendering/box.dart:1687:12)
2020-02-11 12:04:37.448924+0800 Runner[627:821570] flutter: #3      EditableTextState._updateSizeAndTransform (package:flutter/src/widgets/editable_text.dart:1729:40)
2020-02-11 12:04:37.448963+0800 Runner[627:821570] flutter: #4      EditableTextState._openInputConnection (package:flutter/src/widgets/editable_text.dart:1415:7)
2020-02-11 12:04:37.449002+0800 Runner[627:821570] flutter: #5      EditableTextState._openOrCloseInputConnectionIfNeeded (package:flutter/src/widgets/editable_text.dart:1441:7)
2020-02-11 12:04:37.449040+0800 Runner[627:821570] flutter: #6      EditableTextState._handleFocusChanged (package:flutter/src/widgets/editable_text.dart:1707:5)
2020-02-11 12:04:37.449078+0800 Runner[627:821570] flutter: #7      ChangeNotifier.notifyListeners (package:flutter/src/foundation/change_notifier.dart:206:21)
2020-02-11 12:04:37.450750+0800 Runner[627:821570] flutter: #8      FocusNode._notify (package:flutter/src/widgets/focus_manager.dart:808:5)
2020-02-11 12:04:37.450810+0800 Runner[627:821570] flutter: #9      FocusManager._applyFocusChange (package:flutter/src/widgets/focus_manager.dart:1401:12)
2020-02-11 12:04:37.450856+0800 Runner[627:821570] flutter: (elided 12 frames from class _AssertionError and package dart:async)
2020-02-11 12:04:37.450898+0800 Runner[627:821570] flutter:
2020-02-11 12:04:37.450938+0800 Runner[627:821570] flutter: The FocusNode sending notification was:
2020-02-11 12:04:37.450978+0800 Runner[627:821570] flutter:   FocusNode#d9873
2020-02-11 12:04:37.452350+0800 Runner[627:821570] flutter: ════════════════════════════════════════════════════════════════════════════════════════════════════



Flutter doctor information:
[✓] Flutter (Channel stable, v1.12.13+hotfix.5, on Mac OS X 10.15.4 19E224g, locale zh-Hans-CN)
    • Flutter version 1.12.13+hotfix.5 at /Users/wangyuanou/Documents/flutter
    • Framework revision 27321ebbad (9 weeks ago), 2019-12-10 18:15:01 -0800
    • Engine revision 2994f7e1e6
    • Dart version 2.7.0

 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/wangyuanou/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.3.1, Build version 11C504
    • CocoaPods version 1.9.0.beta.2

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 42.1.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] VS Code (version 1.42.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.8.1

[✓] Connected device (1 available)
    • 王渊鸥的iPhone • 35e57e864e553ce162a008165d86060c8d0dab91 • ios • iOS 13.3.1

• No issues found!

**Comment by MeshkaniMohammad** [comment]
@0xfeb try this one, just tried and worked for me.
https://stackoverflow.com/questions/59382235/flutter-throws-an-error-when-i-use-text-field-with-auto-focus

**Comment by KrishnaPravin** [comment]
@MeshkaniMohammad 's link to StackOverflow answer [https://stackoverflow.com/questions/59382235/flutter-throws-an-error-when-i-use-text-field-with-auto-focus](https://stackoverflow.com/a/59384270/5947136) works for me too.

**Comment by KrishnaPravin** [comment]
@MeshkaniMohammad 's link to the StackOverflow question has an answer that **perfectly works for me** too.

[https://stackoverflow.com/questions/59382235/flutter-throws-an-error-when-i-use-text-field-with-auto-focus](https://stackoverflow.com/a/59384270/5947136)
