### ISSUE TITLE
android_alarm_manager plugin app closed when open

### ISSUE THREAD

**Issue by analyzer-y** [flutter/flutter#42907]
I am using android_alarm_manager 0.4.4 plugin but when I open my app it closed instantly, and nothing showing in the log. I thought this is the problem of plugin setPluginRegistrant method.

I am also using flutter_exoplayer plugin which also uses application context so maybe conflict in these, please help me if anyone faced same issue.

this is my application class

```
public class MainApplication extends FlutterApplication implements PluginRegistry.PluginRegistrantCallback {
@Override
public void onCreate() {
    super.onCreate();
    AudioServicePlugin.setPluginRegistrantCallback(this);
    AlarmService.setPluginRegistrant(this);
}

@Override
public void registerWith(PluginRegistry registry) {
   GeneratedPluginRegistrant.registerWith(registry);

}}
```

**Comment by BondarenkoStas** [comment]
@analyzer-y please provide your flutter doctor -v output. Can you please paste the log if to run it will --verbose flag, or there are still no any error/warning messages?

**Comment by analyzer-y** [comment]
Thank you @BondarenkoStas .. here is the flutter doctor output:
```
flutter doctor -v
[✓] Flutter (Channel stable, v1.9.1+hotfix.2, on Mac OS X 10.14.6 18G84, locale en-GB)
    • Flutter version 1.9.1+hotfix.2 at /Users/mac/Documents/FlutterSdk/flutter
    • Framework revision 2d2a1ffec9 (6 weeks ago), 2019-09-06 18:39:49 -0700
    • Engine revision b863200c37
    • Dart version 2.5.0

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/mac/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 10.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.3, Build version 10G8
    • CocoaPods version 1.7.5

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 39.0.3
    • Dart plugin version 191.8423
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] Connected device (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 8.1.0 (API 27) (emulator)

• No issues found!
```

flutter run --verbose
```
 DevFS: HttpException:
Connection closed before full header was received, uri = http://127.0.0.1:63088/tEkKfeVit2M=/
[        ] Could not update files on device: HttpException: Connection closed before full header was
received, uri =
           http://127.0.0.1:63088/tEkKfeVit2M=/
[   +1 ms] Syncing files to device Android SDK built for x86... (completed in 3,690ms, longer than expected)
[   +1 ms] "flutter run" took 45,059ms.

#0      throwToolExit (package:flutter_tools/src/base/common.dart:28:3)
#1      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:477:7)
<asynchronous suspension>
#2      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:490:18)
#3      _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:71:64)
#4      _rootRunUnary (dart:async/zone.dart:1132:38)
#5      _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#6      _FutureListener.handleValue (dart:async/future_impl.dart:137:18)
#7      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:678:45)
#8      Future._propagateToListeners (dart:async/future_impl.dart:707:32)
#9      Future._completeWithValue (dart:async/future_impl.dart:522:5)
#10     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:30:15)
#11     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:288:13)
#12     RunCommand.usageValues (package:flutter_tools/src/commands/run.dart)
#13     _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:71:64)
#14     _rootRunUnary (dart:async/zone.dart:1132:38)
#15     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#16     _FutureListener.handleValue (dart:async/future_impl.dart:137:18)
#17     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:678:45)
#18     Future._propagateToListeners (dart:async/future_impl.dart:707:32)
#19     Future._completeWithValue (dart:async/future_impl.dart:522:5)
#20     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:30:15)
#21     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:288:13)
#22     AndroidDevice.isLocalEmulator (package:flutter_tools/src/android/android_device.dart)
#23     _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:71:64)
#24     _rootRunUnary (dart:async/zone.dart:1132:38)
#25     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#26     _FutureListener.handleValue (dart:async/future_impl.dart:137:18)
#27     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:678:45)
#28     Future._propagateToListeners (dart:async/future_impl.dart:707:32)
#29     Future._completeWithValue (dart:async/future_impl.dart:522:5)
#30     Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:552:7)
#31     _rootRun (dart:async/zone.dart:1124:13)
#32     _CustomZone.run (dart:async/zone.dart:1021:19)
#33     _CustomZone.runGuarded (dart:async/zone.dart:923:7)
#34     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:963:23)
#35     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#36     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#37     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:116:13)
#38     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:173:5)
```

**Comment by analyzer-y** [comment]
@BondarenkoStas or anyone to help in this please.

**Comment by friebetill** [comment]
I have the same error and as far as I could locate the bug, the error occurs when I run a HTTP request in the background and then start the alarm manager.

**Comment by stuartmorgan** [comment]
Closing as `android_alarm_manager` is deprecated in favor of [`android_alarm_manager_plus`](https://pub.dev/packages/android_alarm_manager_plus).
