### ISSUE TITLE
[image_picker] Android build failed

### ISSUE THREAD

**Issue by rockingelevator** [flutter/flutter#42910]
After adding **image_picker**(latest version: 0.6.1+8) dependency app has stopped building on Android with error message: 

> Gradle task assembleDebug failed with exit code 1

Without **image_picker** dependency everything works fine.

### dependecies

```
...

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  redux: ^3.0.0
  flutter_redux: ^0.5.3
  redux_logging: ^0.3.0
  shared_preferences: ^0.5.3+4
  validate: ^1.7.0
  graphql_flutter: ^2.1.0
  http: ^0.12.0+2
  intl: ^0.16.0
  page_transition: "^1.1.4"
  flutter_spinkit: ^4.0.0
  flutter_datetime_picker:
    git:
      url: git@github.com:rockingelevator/flutter_datetime_picker.git
  flutter_slidable: "^0.5.4"
  firebase_core: ^0.4.0+9
  firebase_auth: ^0.14.0+5
  google_sign_in: ^4.0.7
  flushbar: ^1.9.0
  image_picker: ^0.6.1+8
  # image_cropper: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.7.2+1
...
```

### run
```
...

[  +87 ms] Building APK
[  +14 ms] Running Gradle task 'assembleDebug'...
[   +2 ms] executing: [/Users/rockingelevator/projects/apps/wooico/android/]
/Users/rockingelevator/projects/apps/wooico/android/gradlew -Pverbose=true
-Ptarget=/Users/rockingelevator/projects/apps/wooico/lib/main.dart -Ptrack-widget-creation=false
-Pfilesystem-scheme=org-dartlang-root -Ptarget-platform=android-x86 assembleDebug
[+1428 ms] > Configure project :app
[        ] WARNING: API 'variant.getMergeResources()' is obsolete and has been replaced with
'variant.getMergeResourcesProvider()'.
[        ] It will be removed at the end of 2019.
[        ] For more information, see https://d.android.com/r/tools/task-configuration-avoidance.
[        ] To determine what is calling variant.getMergeResources(), use -Pandroid.debug.obsoleteApi=true on the command line
to display more information.
[        ] WARNING: API 'variant.getMergeAssets()' is obsolete and has been replaced with 'variant.getMergeAssetsProvider()'.
[        ] It will be removed at the end of 2019.
[        ] For more information, see https://d.android.com/r/tools/task-configuration-avoidance.
[        ] To determine what is calling variant.getMergeAssets(), use -Pandroid.debug.obsoleteApi=true on the command line to
display more information.
[        ] WARNING: API 'variantOutput.getProcessResources()' is obsolete and has been replaced with
'variantOutput.getProcessResourcesProvider()'.
[        ] It will be removed at the end of 2019.
[        ] For more information, see https://d.android.com/r/tools/task-configuration-avoidance.
[        ] To determine what is calling variantOutput.getProcessResources(), use -Pandroid.debug.obsoleteApi=true on the
command line to display more information.
[ +771 ms] > Task :app:compileFlutterBuildDebugX86 UP-TO-DATE
[        ] > Task :app:packLibsflutterBuildDebug UP-TO-DATE
[        ] > Task :app:preBuild UP-TO-DATE
[        ] > Task :app:preDebugBuild UP-TO-DATE
[        ] > Task :firebase_auth:preBuild UP-TO-DATE
[        ] > Task :firebase_auth:preDebugBuild UP-TO-DATE
[  +98 ms] > Task :firebase_auth:compileDebugAidl NO-SOURCE
[        ] > Task :firebase_core:preBuild UP-TO-DATE
[        ] > Task :firebase_core:preDebugBuild UP-TO-DATE
[        ] > Task :firebase_core:compileDebugAidl NO-SOURCE
[        ] > Task :google_sign_in:preBuild UP-TO-DATE
[   +1 ms] > Task :google_sign_in:preDebugBuild UP-TO-DATE
[        ] > Task :google_sign_in:compileDebugAidl NO-SOURCE
[        ] > Task :image_picker:preBuild UP-TO-DATE
[        ] > Task :image_picker:preDebugBuild UP-TO-DATE
[        ] > Task :image_picker:compileDebugAidl NO-SOURCE
[        ] > Task :path_provider:preBuild UP-TO-DATE
[        ] > Task :path_provider:preDebugBuild UP-TO-DATE
[        ] > Task :path_provider:compileDebugAidl NO-SOURCE
[        ] > Task :shared_preferences:preBuild UP-TO-DATE
[        ] > Task :shared_preferences:preDebugBuild UP-TO-DATE
[        ] > Task :shared_preferences:compileDebugAidl NO-SOURCE
[        ] > Task :app:compileDebugAidl NO-SOURCE
[        ] > Task :firebase_auth:packageDebugRenderscript NO-SOURCE
[        ] > Task :firebase_core:packageDebugRenderscript NO-SOURCE
[        ] > Task :google_sign_in:packageDebugRenderscript NO-SOURCE
[   +2 ms] > Task :image_picker:packageDebugRenderscript NO-SOURCE
[   +1 ms] > Task :path_provider:packageDebugRenderscript NO-SOURCE
[        ] > Task :shared_preferences:packageDebugRenderscript NO-SOURCE
[        ] > Task :app:compileDebugRenderscript NO-SOURCE
[        ] > Task :app:checkDebugManifest UP-TO-DATE
[        ] > Task :app:generateDebugBuildConfig UP-TO-DATE
[        ] > Task :firebase_auth:compileDebugRenderscript NO-SOURCE
[        ] > Task :firebase_auth:checkDebugManifest UP-TO-DATE
[        ] > Task :firebase_auth:generateDebugBuildConfig UP-TO-DATE
[        ] > Task :firebase_auth:generateDebugResValues UP-TO-DATE
[        ] > Task :firebase_auth:generateDebugResources UP-TO-DATE
[        ] > Task :firebase_auth:packageDebugResources UP-TO-DATE
[        ] > Task :firebase_auth:parseDebugLibraryResources UP-TO-DATE
[        ] > Task :firebase_auth:processDebugManifest UP-TO-DATE
[ +192 ms] > Task :firebase_auth:generateDebugRFile UP-TO-DATE
[  +98 ms] > Task :firebase_auth:javaPreCompileDebug UP-TO-DATE
[        ] > Task :firebase_auth:compileDebugJavaWithJavac UP-TO-DATE
[        ] > Task :firebase_auth:bundleLibCompileDebug UP-TO-DATE
[        ] > Task :firebase_core:compileDebugRenderscript NO-SOURCE
[        ] > Task :firebase_core:checkDebugManifest UP-TO-DATE
[        ] > Task :firebase_core:generateDebugBuildConfig UP-TO-DATE
[        ] > Task :firebase_core:generateDebugResValues UP-TO-DATE
[        ] > Task :firebase_core:generateDebugResources UP-TO-DATE
[ +100 ms] > Task :firebase_core:packageDebugResources UP-TO-DATE
[        ] > Task :firebase_core:parseDebugLibraryResources UP-TO-DATE
[        ] > Task :firebase_core:processDebugManifest UP-TO-DATE
[  +95 ms] > Task :firebase_core:generateDebugRFile UP-TO-DATE
[ +103 ms] > Task :firebase_core:javaPreCompileDebug UP-TO-DATE
[        ] > Task :firebase_core:compileDebugJavaWithJavac UP-TO-DATE
[        ] > Task :firebase_core:bundleLibCompileDebug UP-TO-DATE
[        ] > Task :google_sign_in:compileDebugRenderscript NO-SOURCE
[        ] > Task :google_sign_in:checkDebugManifest UP-TO-DATE
[        ] > Task :google_sign_in:generateDebugBuildConfig UP-TO-DATE
[        ] > Task :google_sign_in:generateDebugResValues UP-TO-DATE
[        ] > Task :google_sign_in:generateDebugResources UP-TO-DATE
[        ] > Task :google_sign_in:packageDebugResources UP-TO-DATE
[        ] > Task :google_sign_in:parseDebugLibraryResources UP-TO-DATE
[        ] > Task :google_sign_in:processDebugManifest UP-TO-DATE
[  +98 ms] > Task :google_sign_in:generateDebugRFile UP-TO-DATE
[        ] > Task :google_sign_in:javaPreCompileDebug UP-TO-DATE
[        ] > Task :google_sign_in:compileDebugJavaWithJavac UP-TO-DATE
[        ] > Task :google_sign_in:bundleLibCompileDebug UP-TO-DATE
[        ] > Task :image_picker:compileDebugRenderscript NO-SOURCE
[        ] > Task :image_picker:checkDebugManifest UP-TO-DATE
[        ] > Task :image_picker:generateDebugBuildConfig UP-TO-DATE
[        ] > Task :image_picker:generateDebugResValues UP-TO-DATE
[        ] > Task :image_picker:generateDebugResources UP-TO-DATE
[        ] > Task :image_picker:packageDebugResources UP-TO-DATE
[        ] > Task :image_picker:parseDebugLibraryResources UP-TO-DATE
[        ] > Task :image_picker:processDebugManifest UP-TO-DATE
[  +99 ms] > Task :image_picker:generateDebugRFile UP-TO-DATE
[        ] > Task :image_picker:javaPreCompileDebug UP-TO-DATE
[        ] > Task :image_picker:compileDebugJavaWithJavac UP-TO-DATE
[        ] > Task :image_picker:bundleLibCompileDebug UP-TO-DATE
[        ] > Task :path_provider:compileDebugRenderscript NO-SOURCE
[        ] > Task :path_provider:checkDebugManifest UP-TO-DATE
[        ] > Task :path_provider:generateDebugBuildConfig UP-TO-DATE
[  +97 ms] > Task :path_provider:generateDebugResValues UP-TO-DATE
[        ] > Task :path_provider:generateDebugResources UP-TO-DATE
[        ] > Task :path_provider:packageDebugResources UP-TO-DATE
[        ] > Task :path_provider:parseDebugLibraryResources UP-TO-DATE
[        ] > Task :path_provider:processDebugManifest UP-TO-DATE
[        ] > Task :path_provider:generateDebugRFile UP-TO-DATE
[        ] > Task :path_provider:javaPreCompileDebug UP-TO-DATE
[        ] > Task :path_provider:compileDebugJavaWithJavac UP-TO-DATE
[        ] > Task :path_provider:bundleLibCompileDebug UP-TO-DATE
[        ] > Task :shared_preferences:compileDebugRenderscript NO-SOURCE
[        ] > Task :shared_preferences:checkDebugManifest UP-TO-DATE
[        ] > Task :shared_preferences:generateDebugBuildConfig UP-TO-DATE
[        ] > Task :shared_preferences:generateDebugResValues UP-TO-DATE
[        ] > Task :shared_preferences:generateDebugResources UP-TO-DATE
[        ] > Task :shared_preferences:packageDebugResources UP-TO-DATE
[        ] > Task :shared_preferences:parseDebugLibraryResources UP-TO-DATE
[        ] > Task :shared_preferences:processDebugManifest UP-TO-DATE
[        ] > Task :shared_preferences:generateDebugRFile UP-TO-DATE
[        ] > Task :shared_preferences:javaPreCompileDebug UP-TO-DATE
[        ] > Task :shared_preferences:compileDebugJavaWithJavac UP-TO-DATE
[        ] > Task :shared_preferences:bundleLibCompileDebug UP-TO-DATE
[  +94 ms] > Task :app:javaPreCompileDebug UP-TO-DATE
[        ] > Task :app:cleanMergeDebugAssets
[        ] > Task :app:mergeDebugShaders UP-TO-DATE
[        ] > Task :app:compileDebugShaders UP-TO-DATE
[ +101 ms] > Task :app:generateDebugAssets UP-TO-DATE
[        ] > Task :firebase_auth:mergeDebugShaders UP-TO-DATE
[        ] > Task :firebase_auth:compileDebugShaders UP-TO-DATE
[        ] > Task :firebase_auth:generateDebugAssets UP-TO-DATE
[        ] > Task :firebase_auth:packageDebugAssets UP-TO-DATE
[        ] > Task :firebase_core:mergeDebugShaders UP-TO-DATE
[        ] > Task :firebase_core:compileDebugShaders UP-TO-DATE
[        ] > Task :firebase_core:generateDebugAssets UP-TO-DATE
[        ] > Task :firebase_core:packageDebugAssets UP-TO-DATE
[        ] > Task :google_sign_in:mergeDebugShaders UP-TO-DATE
[        ] > Task :google_sign_in:compileDebugShaders UP-TO-DATE
[        ] > Task :google_sign_in:generateDebugAssets UP-TO-DATE
[        ] > Task :google_sign_in:packageDebugAssets UP-TO-DATE
[        ] > Task :image_picker:mergeDebugShaders UP-TO-DATE
[        ] > Task :image_picker:compileDebugShaders UP-TO-DATE
[        ] > Task :image_picker:generateDebugAssets UP-TO-DATE
[        ] > Task :image_picker:packageDebugAssets UP-TO-DATE
[        ] > Task :path_provider:mergeDebugShaders UP-TO-DATE
[        ] > Task :path_provider:compileDebugShaders UP-TO-DATE
[        ] > Task :path_provider:generateDebugAssets UP-TO-DATE
[        ] > Task :path_provider:packageDebugAssets UP-TO-DATE
[        ] > Task :shared_preferences:mergeDebugShaders UP-TO-DATE
[        ] > Task :shared_preferences:compileDebugShaders UP-TO-DATE
[        ] > Task :shared_preferences:generateDebugAssets UP-TO-DATE
[        ] > Task :shared_preferences:packageDebugAssets UP-TO-DATE
[  +94 ms] > Task :app:mergeDebugAssets
[ +700 ms] > Task :app:copyFlutterAssetsDebug
[        ] > Task :app:mainApkListPersistenceDebug UP-TO-DATE
[        ] > Task :app:generateDebugResValues UP-TO-DATE
[        ] > Task :app:generateDebugResources UP-TO-DATE
[        ] > Task :app:processDebugGoogleServices UP-TO-DATE
[  +99 ms] > Task :app:mergeDebugResources UP-TO-DATE
[        ] > Task :app:createDebugCompatibleScreenManifests UP-TO-DATE
[        ] > Task :app:processDebugManifest UP-TO-DATE
[  +99 ms] > Task :app:processDebugResources UP-TO-DATE
[        ] > Task :app:compileDebugJavaWithJavac UP-TO-DATE
[        ] > Task :app:compileDebugSources UP-TO-DATE
[        ] > Task :app:processDebugJavaRes NO-SOURCE
[        ] > Task :firebase_auth:processDebugJavaRes NO-SOURCE
[        ] > Task :firebase_auth:bundleLibResDebug UP-TO-DATE
[        ] > Task :firebase_core:processDebugJavaRes NO-SOURCE
[        ] > Task :firebase_core:bundleLibResDebug UP-TO-DATE
[        ] > Task :google_sign_in:processDebugJavaRes NO-SOURCE
[        ] > Task :google_sign_in:bundleLibResDebug UP-TO-DATE
[        ] > Task :image_picker:processDebugJavaRes NO-SOURCE
[        ] > Task :image_picker:bundleLibResDebug UP-TO-DATE
[        ] > Task :path_provider:processDebugJavaRes NO-SOURCE
[        ] > Task :path_provider:bundleLibResDebug UP-TO-DATE
[        ] > Task :shared_preferences:processDebugJavaRes NO-SOURCE
[        ] > Task :shared_preferences:bundleLibResDebug UP-TO-DATE
[ +100 ms] > Task :app:mergeDebugJavaResource UP-TO-DATE
[  +96 ms] > Task :app:checkDebugDuplicateClasses FAILED
[        ]          *********************************************************
[        ] WARNING: This version of firebase_auth will break your Android build if it or its dependencies aren't compatible
with AndroidX.
[        ]          See https://goo.gl/CP92wY for more information on the problem and how to fix it.
[        ]          This warning prints for all Android build failures. The real root cause of the error may be unrelated.
[        ]          *********************************************************
[        ] 104 actionable tasks: 4 executed, 100 up-to-date
[ +483 ms] Running Gradle task 'assembleDebug'... (completed in 5.1s)
[   +4 ms] "flutter run" took 15,076ms.
Gradle task assembleDebug failed with exit code 1

#0      throwToolExit (package:flutter_tools/src/base/common.dart:28:3)
#1      _buildGradleProjectV2 (package:flutter_tools/src/android/gradle.dart:751:5)
<asynchronous suspension>
#2      buildGradleProject (package:flutter_tools/src/android/gradle.dart:494:14)
<asynchronous suspension>
#3      buildApk (package:flutter_tools/src/android/apk.dart:34:9)
<asynchronous suspension>
#4      AndroidDevice.startApp (package:flutter_tools/src/android/android_device.dart:486:13)
<asynchronous suspension>
#5      FlutterDevice.runHot (package:flutter_tools/src/resident_runner.dart:378:54)
<asynchronous suspension>
#6      HotRunner.run (package:flutter_tools/src/run_hot.dart:254:39)
<asynchronous suspension>
#7      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:472:37)
<asynchronous suspension>
#8      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:490:18)
#9      _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:71:64)
#10     _rootRunUnary (dart:async/zone.dart:1132:38)
#11     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#12     _FutureListener.handleValue (dart:async/future_impl.dart:137:18)
#13     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:678:45)
#14     Future._propagateToListeners (dart:async/future_impl.dart:707:32)
#15     Future._completeWithValue (dart:async/future_impl.dart:522:5)
#16     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:30:15)
#17     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:288:13)
#18     RunCommand.usageValues (package:flutter_tools/src/commands/run.dart)
#19     _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:71:64)
#20     _rootRunUnary (dart:async/zone.dart:1132:38)
#21     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#22     _FutureListener.handleValue (dart:async/future_impl.dart:137:18)
#23     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:678:45)
#24     Future._propagateToListeners (dart:async/future_impl.dart:707:32)
#25     Future._completeWithValue (dart:async/future_impl.dart:522:5)
#26     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:30:15)
#27     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:288:13)
#28     AndroidDevice.isLocalEmulator (package:flutter_tools/src/android/android_device.dart)
#29     _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:71:64)
#30     _rootRunUnary (dart:async/zone.dart:1132:38)
#31     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#32     _FutureListener.handleValue (dart:async/future_impl.dart:137:18)
#33     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:678:45)
#34     Future._propagateToListeners (dart:async/future_impl.dart:707:32)
#35     Future._completeWithValue (dart:async/future_impl.dart:522:5)
#36     Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:552:7)
#37     _rootRun (dart:async/zone.dart:1124:13)
#38     _CustomZone.run (dart:async/zone.dart:1021:19)
#39     _CustomZone.runGuarded (dart:async/zone.dart:923:7)
#40     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:963:23)
#41     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#42     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#43     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:116:13)
#44     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:173:5)
```

### doctor
```
[✓] Flutter (Channel stable, v1.9.1+hotfix.4, on Mac OS X 10.14.6 18G87, locale en-UA)
    • Flutter version 1.9.1+hotfix.4 at /Users/rockingelevator/dev/flutter
    • Framework revision cc949a8e8b (3 weeks ago), 2019-09-27 15:04:59 -0700
    • Engine revision b863200c37
    • Dart version 2.5.0

 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/rockingelevator/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 10.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.3, Build version 10G8
    • CocoaPods version 1.7.5

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 40.1.2
    • Dart plugin version 191.8423
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] VS Code (version 1.39.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.5.1

[✓] Connected device (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 8.1.0 (API 27) (emulator)

• No issues found!

```

**Comment by MostafaKhalile** [comment]
You Should Better Use That :

[image_picker_modern ](https://pub.dev/packages/image_picker_modern )

It Should be Working Good 👍

**Comment by georgezlei** [comment]
It seems that the problem can only be reproduced in legacy projects. When I created a new Flutter project and copied the codes in, this issue disappeared.

**Comment by rockingelevator** [comment]
@georgezlei didn't worked for me. I created new project and ive got: 

```
D8: Program type already present: android.support.v4.app.INotificationSideChannel
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:transformDexArchiveWithExternalLibsDexMergerForDebug'.
...
Program type already present: android.support.v4.app.INotificationSideChannel
...
Gradle task assembleDebug failed with exit code 1
*******************************************************************************************
The Gradle failure may have been because of AndroidX incompatibilities in this Flutter app.
See https://goo.gl/CP92wY for more information on the problem and how to fix it.
*******************************************************************************************
```
I don't know, maybe there is some conflict in dependencies or compatibility or ...
Without image_picker everything still works fine.

**Comment by kunit1** [comment]
You need to migrate your project to AndroidX. The stable channel doesn't have AndroidX enabled by default. Follow the instructions in the error message:
*******************************************************************************************
The Gradle failure may have been because of AndroidX incompatibilities in this Flutter app.
See https://goo.gl/CP92wY for more information on the problem and how to fix it.
*******************************************************************************************

**Comment by rockingelevator** [comment]
1) I added manualy this to _android/gradle.properties_:
```
android.useAndroidX=true
android.enableJetifier=true
```
2) then sync project in android studio
3) got an error with different androidx versions (i believe i had an old gradle version) and here is a solution: [stackoverflow](https://stackoverflow.com/questions/54872814/all-the-androidx-versions-different-from-the-compile)
4) clean and rebuild. Voila.

**Comment by Losspost** [comment]
I have the same problem and followed your steps but I am still getting the same error message. Anyone have an idea why?

**Comment by shinriyo** [comment]
Because image_picker >=0.6.7 depends on image_picker_platform_interface ^1.1.0 which depends on http ^0.12.1, image_picker >=0.6.7 requires http ^0.12.1.
