### ISSUE TITLE
MaxTileWidthGrid assert

### ISSUE THREAD

**Issue by mpcomplete** [flutter/flutter#4297]
I'm hitting an assert[1] using MaxTileWidthGrid. My usage is as follows:
```dart
new MaxTileWidthGrid(
                maxTileWidth: 500.0,
                children: recipes.map(
                  (Recipe r) => _buildCard(context, r)
                ).toList()
)

_buildCard() returns a Widget, the outer layers of which look like:

  return new Padding(
      padding: const EdgeInsets.all(4.0),
      child: new GestureDetector(
        child: new Card(...)
      )
  )

[1] The assert text:

I/flutter : ══╡ EXCEPTION CAUGHT BY RENDERING LIBRARY ╞═════════════════════════════════════════════════════════
I/flutter : The following assertion was thrown during performLayout():
I/flutter : 'package:flutter/src/rendering/grid.dart': Failed assertion: line 345: 'constraints.maxWidth <
I/flutter : double.INFINITY' is not true.
I/flutter : Either the assertion indicates an error in the framework itself, or we should provide substantially
I/flutter : more information in this error message to help you determine and fix the underlying cause.
I/flutter : In either case, please report this assertion by filing a bug on GitHub:
I/flutter :   https://github.com/flutter/flutter/issues/new
I/flutter : When the exception was thrown, this was the stack:
I/flutter : #0      _AssertionError._throwNew (dart:core-patch/errors_patch.dart:27)
I/flutter : #1      MaxTileWidthGridDelegate.getGridSpecification (package:flutter/src/rendering/grid.dart:345)
I/flutter : #2      GridDelegate._getGridSize (package:flutter/src/rendering/grid.dart:179)
I/flutter : #3      GridDelegate.getMinIntrinsicHeight (package:flutter/src/rendering/grid.dart:203)
I/flutter : #4      RenderGrid.getMinIntrinsicHeight (package:flutter/src/rendering/grid.dart:492)
I/flutter : #5      RenderBox.debugAssertDoesMeetConstraints.<anonymous closure>.testIntrinsic (package:flutter/src/rendering/box.dart:907)
I/flutter : #6      RenderBox.debugAssertDoesMeetConstraints.<anonymous closure> (package:flutter/src/rendering/box.dart:925)
I/flutter : #7      RenderBox.debugAssertDoesMeetConstraints (package:flutter/src/rendering/box.dart:835)
I/flutter : #8      RenderBox.size=.<anonymous closure> (package:flutter/src/rendering/box.dart:739)
I/flutter : #9      RenderBox.size= (package:flutter/src/rendering/box.dart:739)
I/flutter : #10     RenderGrid.performLayout (package:flutter/src/rendering/grid.dart:528)
... <snip>
```

**Comment by abarth** [comment]
How much width do you have available for the grid?  We probably need a better error message here, but the issue is that you've put the grid in a location that has an unbounded amount of width.

/cc @Hixie

**Comment by Hixie** [comment]
The immediate problem here is with the grid intrinsics logic. I have a fix.

**Comment by Hixie** [comment]
Fix in https://github.com/flutter/flutter/pull/4299
