### ISSUE TITLE
On Windows, build bundle fails when building APK if a flavor is defined.

### ISSUE THREAD

**Issue by blasten** [flutter/flutter#42985]
This is the log: https://api.cirrus-ci.com/v1/task/6380156054142976/logs/test.log

Do you know what could be going on @jonahwilliams? I have confirmed that this only happen when the flavor is defined.

```
FileSystemException: Cannot copy file to 'C:\Users\ContainerAdministrator\AppData\Local\Temp\flutter_devicelab_gradle_plugin_test.3994aaac-f150-11e9-aad5-c8150419f7aa\hello\build\app\intermediates\flutter\productionRelease\android-arm64/flutter_assets\packages/cupertino_icons/assets/CupertinoIcons.ttf', path = 'C:\Users\ContainerAdministrator\AppData\Roaming\Pub\Cache\hosted\pub.dartlang.org\cupertino_icons-0.1.2\assets\CupertinoIcons.ttf' (OS Error: The system cannot find the path specified.
[gradle_plugin_bundle_test] [STDOUT] 
[gradle_plugin_bundle_test] [STDOUT] , errno = 3)
[gradle_plugin_bundle_test] [STDOUT] #0      _File.copy.<anonymous closure> (dart:io/file_impl.dart:336:9)
[gradle_plugin_bundle_test] [STDOUT] #1      _rootRunUnary (dart:async/zone.dart:1132:38)
[gradle_plugin_bundle_test] [STDOUT] #2      _CustomZone.runUnary (dart:async/zone.dart:1029:19)
[gradle_plugin_bundle_test] [STDOUT] #3      _FutureListener.handleValue (dart:async/future_impl.dart:137:18)
[gradle_plugin_bundle_test] [STDOUT] #4      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:678:45)
[gradle_plugin_bundle_test] [STDOUT] #5      Future._propagateToListeners (dart:async/future_impl.dart:707:32)
[gradle_plugin_bundle_test] [STDOUT] #6      Future._completeWithValue (dart:async/future_impl.dart:522:5)
[gradle_plugin_bundle_test] [STDOUT] #7      Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:552:7)
[gradle_plugin_bundle_test] [STDOUT] #8      _rootRun (dart:async/zone.dart:1124:13)
[gradle_plugin_bundle_test] [STDOUT] #9      _CustomZone.run (dart:async/zone.dart:1021:19)
[gradle_plugin_bundle_test] [STDOUT] #10     _CustomZone.runGuarded (dart:async/zone.dart:923:7)
[gradle_plugin_bundle_test] [STDOUT] #11     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:963:23)
[gradle_plugin_bundle_test] [STDOUT] #12     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
[gradle_plugin_bundle_test] [STDOUT] #13     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
[gradle_plugin_bundle_test] [STDOUT] #14     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:116:13)
[gradle_plugin_bundle_test] [STDOUT] #15     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:173:5)
[gradle_plugin_bundle_test] [STDOUT] 
[gradle_plugin_bundle_test] [STDOUT] Failed to build bundle.

```

**Comment by jonahwilliams** [comment]
What test is this? I can run it locally to double check. My guess is that the subdirectory `productionRelease\android-arm64` is missing for some reason

**Comment by jmagman** [comment]
@blasten Do you remember the test this was for?  That log is long gone.

**Comment by blasten** [comment]
I don't have the log unfortunately. Let's just close this bug.
