### ISSUE TITLE
Using cmake instead of makefile in flutter desktop example

### ISSUE THREAD

**Issue by lucaszanella** [flutter/flutter#42983]
I'm trying to replace the Makefile in Flutter's desktop example by a cmake generated Makefile. Here's my CMakeLists.txt:

```
cmake_minimum_required(VERSION 3.10)
project (flutter_desktop_example)
set(CMAKE_VERBOSE_MAKEFILE ON)
add_subdirectory(../../myRtspClient _myRtspClient)

set(BUILD debug)
set(FLUTTER_ROOT /home/dev/development/flutter)
set(PROJECT_DIR /home/dev/orwell/orwell_flutter)
set(FLUTTER_TARGET /home/dev/orwell/orwell_flutter/lib/main.dart)
set(TRACK_WIDGET_CREATION false)
set(FLUTTER_ENGINE ../engine/src)
set(LOCAL_ENGINE host_debug_unopt)

#SET (CMAKE_C_COMPILER             "/usr/bin/clang")
SET (CMAKE_C_FLAGS                "-std=c99 ")


#SET (CMAKE_CXX_COMPILER             "/usr/bin/clang++")
SET (CMAKE_CXX_FLAGS                "-std=c++14")
set (CMAKE_MODULE_LINKER_FLAGS      "-Wl,-rpath=\$$ORIGIN/lib")

find_package(OpenGL REQUIRED)
#-lGLEW -lGLU -lGL -lX11
#sudo apt-get install libglew-dev #will install everything below
find_library(GLEW_LIBRARY GLEW) 
find_library(GLU_LIBRARY GLU)
find_library(GL_LIBRARY GL)
find_library(X11_LIBRARY X11)
find_library(ZLIB_LIBRARY z)
find_library(MLIB_LIBRARY m)
find_library(LIBDL_LIBRARY dl)
find_library(LIBDRM_LIBRARY drm)
find_library(LIB_SSL ssl)
find_library(LIB_CRYPTO crypto)

#These driver libraries are only available for x86 or x86_64, arm libs are not compiled with them
if (CMAKE_SYSTEM_PROCESSOR STREQUAL x86_64 OR CMAKE_SYSTEM_PROCESSOR STREQUAL x86)
find_library(LIB_VDPAU vdpau) #sudo apt install libvdpau-dev
find_library(LIB_VA va)
find_library(LIB_VA_DRM va-drm)
find_library(LIB_VA_X11 va-x11)
endif()


include_directories(../common/include ../../engine/src/flutter/third_party/glad/include 
../../engine/src/third_party/glfw/include ../../engine/src/third_party/glfw/include
../../cpp/common ../../deps/ffmpeg/build/desktop/x86_64/include
../../deps/ZLMediaKit/src ../../deps/ZLMediaKit/3rdpart/ZLToolKit/src
../../myRtspClient/myRtspClient/include)
add_subdirectory(../../deps/ZLMediaKit _ZLMediaKit)

find_library(FLUTTER_LIBRARY flutter_linux_glfw PATHS ${CMAKE_CURRENT_SOURCE_DIR}/flutter/ephemeral)
add_library(LIBORWELL STATIC IMPORTED)

set(FFMPEG_LIB_DIR ${CMAKE_CURRENT_SOURCE_DIR}/../../deps/ffmpeg/build/desktop/x86_64_generic/lib)
add_library(AVDEVICE_LIB STATIC IMPORTED)
set_target_properties(AVDEVICE_LIB PROPERTIES IMPORTED_LOCATION ${FFMPEG_LIB_DIR}/libavdevice.a)
add_library(AVFILTER_LIB STATIC IMPORTED)
set_target_properties(AVFILTER_LIB PROPERTIES IMPORTED_LOCATION ${FFMPEG_LIB_DIR}/libavfilter.a)
add_library(AVFORMAT_LIB STATIC IMPORTED)
set_target_properties(AVFORMAT_LIB PROPERTIES IMPORTED_LOCATION ${FFMPEG_LIB_DIR}/libavformat.a)
add_library(AVUTIL_LIB STATIC IMPORTED)
set_target_properties(AVUTIL_LIB PROPERTIES IMPORTED_LOCATION ${FFMPEG_LIB_DIR}/libavutil.a)
add_library(AVCODEC_LIB STATIC IMPORTED)
set_target_properties(AVCODEC_LIB PROPERTIES IMPORTED_LOCATION ${FFMPEG_LIB_DIR}/libavcodec.a)
add_library(SWS_SCALE_LIB STATIC IMPORTED)
set_target_properties(SWS_SCALE_LIB PROPERTIES IMPORTED_LOCATION ${FFMPEG_LIB_DIR}/libswscale.a)
add_library(SWRESAMPLE_LIB STATIC IMPORTED)
set_target_properties(SWRESAMPLE_LIB PROPERTIES IMPORTED_LOCATION ${FFMPEG_LIB_DIR}/libswresample.a)
set(FFMPEG_INCLUDE_DIR ${CMAKE_CURRENT_SOURCE_DIR}/../../deps/ffmpeg/build/desktop/x86_64_generic/include)

set_target_properties(LIBORWELL PROPERTIES IMPORTED_LOCATION ../../gtk/build/desktoplinux/liborwell.a)
set(RUNTIME_OUTPUT_DIRECTORY "${CMAKE_CURRENT_SOURCE_DIR}/../build/linux/debug")
SET(CMAKE_INSTALL_RPATH "$ORIGIN/lib")
include_directories(flutter/ephemeral flutter/ephemeral/cpp_client_wrapper_glfw flutter/ephemeral/cpp_client_wrapper_glfw/include)
file(GLOB SOURCES main.cc 
flutter/generated_plugin_registrant.cc 
"../common/src/*.cc" 
flutter/ephemeral/cpp_client_wrapper_glfw/flutter_window_controller.cc
flutter/ephemeral/cpp_client_wrapper_glfw/plugin_registrar.cc
flutter/ephemeral/cpp_client_wrapper_glfw/engine_method_result.cc
flutter/ephemeral/cpp_client_wrapper_glfw/standard_codec.cc
../../engine/src/flutter/third_party/glad/src/gl.c)

add_custom_target(sync COMMAND FLUTTER_ROOT=${FLUTTER_ROOT} PROJECT_DIR=${PROJECT_DIR} FLUTTER_TARGET=${FLUTTER_TARGET}
TRACK_WIDGET_CREATION=${TRACK_WIDGET_CREATION} FLUTTER_ENGINE=${FLUTTER_ENGINE} LOCAL_ENGINE=${LOCAL_ENGINE}
${FLUTTER_ROOT}/packages/flutter_tools/bin/tool_backend.sh linux-x64 ${BUILD} COMMENT "sync running")
add_executable(flutter_desktop_example ${SOURCES})
add_dependencies(flutter_desktop_example sync myRtspClient-static zlmediakit zltoolkit)
set_target_properties(flutter_desktop_example
    PROPERTIES
    ARCHIVE_OUTPUT_DIRECTORY "${CMAKE_CURRENT_SOURCE_DIR}/../build/linux/debug"
    LIBRARY_OUTPUT_DIRECTORY "${CMAKE_CURRENT_SOURCE_DIR}/../build/linux/debug"
    RUNTIME_OUTPUT_DIRECTORY "${CMAKE_CURRENT_SOURCE_DIR}/../build/linux/debug"
    INSTALL_RPATH "\$ORIGIN/lib"
    BUILD_WITH_INSTALL_RPATH TRUE
)
#${LIB_VDPAU} ${LIB_VA} ${LIB_VA_DRM} ${LIB_VA_X11}
target_link_libraries(flutter_desktop_example PRIVATE LIBORWELL ${FLUTTER_LIBRARY} PRIVATE 
AVCODEC_LIB AVUTIL_LIB SWS_SCALE_LIB SWRESAMPLE_LIB 
${ZLIB_LIBRARY} ${LIBDL_LIBRARY} ${X11_LIBRARY} 
myRtspClient-static pthread -lstdc++fs ${GL_LIBRARY} zlmediakit zltoolkit)
```

I generated a Makefile from it and then when I do flutter run, I get:

```
root@fc1b880841da:/home/dev/orwell/orwell_flutter# flutter --local-engine-src-path ../engine/src --local-engine=host_debug_unopt run
Launching lib/main.dart on Linux in debug mode...
Building Linux application...                                           

Oops; flutter has exited unexpectedly.
Crash report written to /home/dev/orwell/orwell_flutter/flutter_02.log;
please let us know at https://github.com/flutter/flutter/issues.

```

Here's what the log says:

```
## command

flutter --local-engine-src-path ../engine/src --local-engine=host_debug_unopt run

## exception

ArgumentError: Invalid argument(s): Cannot find executable for build/linux/debug.


#0      _getExecutable (package:process/src/interface/local_process_manager.dart:127:5)
#1      LocalProcessManager.start (package:process/src/interface/local_process_manager.dart:43:30)
#2      LinuxDevice.startApp (package:flutter_tools/src/linux/linux_device.dart:89:50)
<asynchronous suspension>
#3      FlutterDevice.runHot (package:flutter_tools/src/resident_runner.dart:378:54)
<asynchronous suspension>
#4      HotRunner.run (package:flutter_tools/src/run_hot.dart:258:39)
<asynchronous suspension>
#5      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:481:37)
<asynchronous suspension>
#6      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:557:18)
<asynchronous suspension>
#7      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:457:33)
<asynchronous suspension>
#8      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:157:29)
<asynchronous suspension>
#9      _rootRun (dart:async/zone.dart:1124:13)
#10     _CustomZone.run (dart:async/zone.dart:1021:19)
#11     _runZoned (dart:async/zone.dart:1516:10)
#12     runZoned (dart:async/zone.dart:1463:12)
#13     AppContext.run (package:flutter_tools/src/base/context.dart:156:18)
<asynchronous suspension>
#14     FlutterCommand.run (package:flutter_tools/src/runner/flutter_command.dart:446:20)
#15     CommandRunner.runCommand (package:args/command_runner.dart:197:27)
<asynchronous suspension>
#16     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:416:21)
<asynchronous suspension>
#17     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:157:29)
<asynchronous suspension>
#18     _rootRun (dart:async/zone.dart:1124:13)
#19     _CustomZone.run (dart:async/zone.dart:1021:19)
#20     _runZoned (dart:async/zone.dart:1516:10)
#21     runZoned (dart:async/zone.dart:1463:12)
#22     AppContext.run (package:flutter_tools/src/base/context.dart:156:18)
<asynchronous suspension>
#23     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:367:19)
<asynchronous suspension>
#24     CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:112:25)
#25     new Future.sync (dart:async/future.dart:224:31)
#26     CommandRunner.run (package:args/command_runner.dart:112:14)
#27     FlutterCommandRunner.run (package:flutter_tools/src/runner/flutter_command_runner.dart:251:18)
#28     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:63:22)
<asynchronous suspension>
#29     _rootRun (dart:async/zone.dart:1124:13)
#30     _CustomZone.run (dart:async/zone.dart:1021:19)
#31     _runZoned (dart:async/zone.dart:1516:10)
#32     runZoned (dart:async/zone.dart:1500:12)
#33     run.<anonymous closure> (package:flutter_tools/runner.dart:61:18)
<asynchronous suspension>
#34     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:157:29)
<asynchronous suspension>
#35     _rootRun (dart:async/zone.dart:1124:13)
#36     _CustomZone.run (dart:async/zone.dart:1021:19)
#37     _runZoned (dart:async/zone.dart:1516:10)
#38     runZoned (dart:async/zone.dart:1463:12)
#39     AppContext.run (package:flutter_tools/src/base/context.dart:156:18)
<asynchronous suspension>
#40     runInContext (package:flutter_tools/src/context_runner.dart:63:24)
<asynchronous suspension>
#41     run (package:flutter_tools/runner.dart:50:10)
#42     main (package:flutter_tools/executable.dart:65:9)
<asynchronous suspension>
#43     main (file:///home/dev/development/flutter/packages/flutter_tools/bin/flutter_tools.dart:8:3)
#44     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:303:32)
#45     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:12)


## flutter doctor


[!] Flutter (Channel unknown, v1.10.13-pre.11, on Linux, locale en_US.utf8)
     Flutter version 1.10.13-pre.11 at /home/dev/development/flutter
     Framework revision 1196f91f71 (11 days ago), 2019-10-06 14:38:17 -0700
     Engine revision 7d90779bb6
     Dart version 2.6.0 (build 2.6.0-dev.5.0 d6c6d12ebf)
    ✗ Downloaded executables cannot execute on host.
      See https://github.com/flutter/flutter/issues/6207 for more information
      On Debian/Ubuntu/Mint: sudo apt-get install lib32stdc++6
      On Fedora: dnf install libstdc++.i686
      On Arch: pacman -S lib32-gcc-libs


[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/setup/#android-setup for detailed instructions).
      If the Android SDK has been installed to a custom location, set ANDROID_HOME to that location.
      You may also want to add it to your PATH environment variable.


[✓] Linux toolchain - develop for Linux desktop
     clang++ 6.0.0
     GNU Make 4.1

[!] Android Studio (not installed)
     Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/setup/#android-setup for detailed instructions).

[✓] Connected device (1 available)
     Linux  Linux  linux-x64  Linux

! Doctor found issues in 3 categories.
```

As you can see that in the CMakeLists I setted `RUNTIME_OUTPUT_DIRECTORY` to `"${CMAKE_CURRENT_SOURCE_DIR}/../build/linux/debug"` which is exactly the path that the  log complained: ArgumentError: Invalid argument(s): Cannot find executable for build/linux/debug.

The archive is indeed there

**Comment by stuartmorgan** [comment]
> As you can see that in the CMakeLists I setted RUNTIME_OUTPUT_DIRECTORY to "${CMAKE_CURRENT_SOURCE_DIR}/../build/linux/debug" which is exactly the path that the log complained: ArgumentError: Invalid argument(s): Cannot find executable for build/linux/debug.

That is a directory, not an executable. The fact that it's trying to execute a directory rather than something in that directory means the path isn't correct. Looking at your code above I don't see 
 `BINARY_NAME` anywhere in your code above, which will break [this code](https://github.com/flutter/flutter/blob/fe9512fa7275452a0622ac70bb2475bd62b12c74/packages/flutter_tools/lib/src/linux/makefile.dart#L13), so that makes sense.

Closing, since this isn't a Flutter bug. The only thing the Linux build currently supports is exactly the structure used in the FDE example; if you are doing something different that's not compatible, it's up to you to alter Flutter locally to match what you are doing. There are plans to eventually move to something more flexible, but the current code isn't intended to support arbitrary build systems.

**Comment by stuartmorgan** [comment]
Stepping back a bit: I would encourage you not to do this. As flutter.dev/desktop says, this change is all subject to change without warning; any time you update Flutter your code may break, and you'll need to reverse-engineer things again and rework your build.

It will be much easier for you to maintain if you use CMake for all the other libraries you are building, create a dylibr from that, and then add that dylib to the existing makefile so that you are using the stock makefile with minimal changes that can be easily re-applied to a fresh copy pulled from FDE any time you update Flutter.

**Comment by muchirajunior** [comment]
help me configure cmake for flutter linux
