### ISSUE TITLE
shell_unittests flaky segfault

### ISSUE THREAD

**Issue by cbracken** [flutter/flutter#43018]
Seeing the following flaky failure on the host_mac_debug run of shell_unittests, which appears to be terminating with segfault (-11). This occurred on the LUCI bots on commit https://github.com/flutter/engine/commit/67de0bf44b80dda972fb8cecbdf1f48f4fa57aac.

```
[----------] 31 tests from ShellTest
[ RUN      ] ShellTest.FixturesAreFunctional
[       OK ] ShellTest.FixturesAreFunctional (71 ms)
[ RUN      ] ShellTest.InitializeWithSingleThread
[       OK ] ShellTest.InitializeWithSingleThread (38 ms)
[ RUN      ] ShellTest.WaitForFirstFrameInlined
[       OK ] ShellTest.WaitForFirstFrameInlined (70 ms)
[ RUN      ] ShellTest.InitializeWithGPUAndPlatformThreadsTheSame
[       OK ] ShellTest.InitializeWithGPUAndPlatformThreadsTheSame (39 ms)
[ RUN      ] ShellTest.InitializeWithInvalidThreads
[       OK ] ShellTest.InitializeWithInvalidThreads (5 ms)
[ RUN      ] ShellTest.WaitForFirstFrameTimeout
[       OK ] ShellTest.WaitForFirstFrameTimeout (111 ms)
[ RUN      ] ShellTest.ReloadSystemFonts
[       OK ] ShellTest.ReloadSystemFonts (39 ms)
[ RUN      ] ShellTest.SetResourceCacheSizeEarly
[       OK ] ShellTest.SetResourceCacheSizeEarly (69 ms)
[ RUN      ] ShellTest.WaitForFirstFrame
[       OK ] ShellTest.WaitForFirstFrame (72 ms)
[ RUN      ] ShellTest.BlacklistedDartVMFlag
[       OK ] ShellTest.BlacklistedDartVMFlag (26 ms)
[ RUN      ] ShellTest.ReportTimingsIsCalled
Traceback (most recent call last):
  File "/b/s/w/ir/cache/builder/src/flutter/testing/run_tests.py", line 344, in <module>
    sys.exit(main())
  File "/b/s/w/ir/cache/builder/src/flutter/testing/run_tests.py", line 323, in main
    RunCCTests(build_dir, engine_filter)
  File "/b/s/w/ir/cache/builder/src/flutter/testing/run_tests.py", line 104, in RunCCTests
    RunEngineExecutable(build_dir, 'shell_unittests', filter, shuffle_flags)
  File "/b/s/w/ir/cache/builder/src/flutter/testing/run_tests.py", line 67, in RunEngineExecutable
    subprocess.check_call(test_command, cwd=cwd)
  File "/b/s/w/ir/cipd_bin_packages/cpython/lib/python2.7/subprocess.py", line 190, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/b/s/w/ir/cache/builder/src/out/host_debug_unopt/shell_unittests', '--gtest_shuffle', '--gtest_repeat=2']' returned non-zero exit status -11
```

/cc @chinmaygarde for any thoughts he might have.

**Comment by chinmaygarde** [comment]
Can we do a tsan sanitizer pass over the same.

**Comment by chinmaygarde** [comment]
Duplicate https://github.com/flutter/flutter/issues/43192
