### ISSUE TITLE
video_player driver test failing on Cirrus CI iOS simulator.

### ISSUE THREAD

**Issue by cyanglaz** [flutter/flutter#43012]
The driver test in video_player (`'Push a page contains video and pop back, do not crash.'`) is currently failing on CI with some weird time-out. It seems to hang indefinitely. However, the test runs successfully in local.
This test is introduced in https://github.com/flutter/plugins/pull/2124 and it is a fix for the issue https://github.com/flutter/flutter/issues/41125

Failing log: 

```
if [[ "$CHANNEL" -eq "stable" ]]; then find . | grep _web$ | xargs rm -rf; fi
flutter channel $CHANNEL
Switching to flutter channel 'master'...
git: Already on 'master'
git: Your branch is up to date with 'origin/master'.
./script/incremental_build.sh build-examples --ipa
Checking for changed packages from b1488e6636471ec29a696275c56081bd7be71087
Detected changes in the following 1 package(s):
video_player
running build-examples --ipa
BUILDING IPA for video_player/example
Running "flutter pub get" in example...                            28.6s
Warning: Building for device with codesigning disabled. You will have to manually codesign before deploying to device.
Building io.flutter.videoPlayerExample for device (ios-release)...
Warning: Missing build name (CFBundleShortVersionString).
Warning: Missing build number (CFBundleVersion).
Action Required: You must set a build name and number in the pubspec.yaml file version field before submitting to the App Store.
Running pod install...                                              5.3s
Running Xcode build...                                          
Xcode build done.                                           76.1s
Built /private/var/folders/sy/2x5qvs0n4lg18fry9jz4y21m0000gn/T/cirrus-ci-build/packages/video_player/example/build/ios/iphoneos/Runner.app.
All builds successful!
Running version check for changed packages
No version check errors found!
./script/incremental_build.sh drive-examples
Checking for changed packages from b1488e6636471ec29a696275c56081bd7be71087
Detected changes in the following 1 package(s):
video_player
running drive-examples
RUNNING DRIVER TEST for video_player/example/test_driver/video_player.dart
Using device Flutter-iPhone.
Starting application: test_driver/video_player.dart
Warning: Missing build name (CFBundleShortVersionString).
Warning: Missing build number (CFBundleVersion).
Action Required: You must set a build name and number in the pubspec.yaml file version field before submitting to the App Store.
Running pod install...                                              2.4s
Running Xcode build...                                          
Xcode build done.                                           37.4s
flutter: Observatory listening on http://127.0.0.1:50239/00vaWPpV0X8=/
[info ] FlutterDriver: Connecting to Flutter application at http://127.0.0.1:50239/00vaWPpV0X8=/
[trace] FlutterDriver: Isolate found with number: 476564475618995
[trace] FlutterDriver: Isolate is paused at start.
[trace] FlutterDriver: Attempting to resume isolate
[trace] FlutterDriver: Waiting for service extension
        [x86_64] libnetcore-1229.250.15
    0   libnetwork.dylib                    0x000000010a7493b8 __nw_create_backtrace_string + 120
    1   libnetwork.dylib                    0x000000010a6a34b9 nw_dictionary_set_value + 265
    2   libnetwork.dylib                    0x000000010a6f4436 nw_path_evaluator_cancel + 582
    3   MediaToolbox                        0x000000011791c744 FigNWPathEvaluatorCreate + 886
    4   MediaToolbox                        0x00000001179b2a24 AttemptNetworkMonitorSetup + 214
    5   MediaToolbox                        0x00000001179b264f segPumpSendIndexFileRequest + 865
    6   MediaToolbox                        0x00000001179ccdef segPumpRequestIndexForStream + 810
    7   MediaToolbox                        0x00000001179c9fb1 segPumpLoadInformation + 106
    8   MediaToolbox                        0x0000000117a0e619 EnsureBytePump + 478
    9   MediaToolbox                        0x0000000117a05e5a PerformTransferBytePumpAsync + 46
 <…>
[info ] FlutterDriver: Connected to Flutter application.
00:00 
+0
: Push a page contains video and pop back, do not crash.
TX and TY are 0. Rotation: 0. Natural width,height: 1280.000000, 720.000000
[warning] FlutterDriver: waitFor message is taking a long time to complete...
    "LocalDataTask <70A17996-C10F-49E9-B1A7-861A23893CE3>.<1>"
), _NSURLErrorFailingURLSessionTaskErrorKey=LocalDataTask <70A17996-C10F-49E9-B1A7-861A23893CE3>.<1>, NSLocalizedDescription=cancelled} [-999]
flutter: Failed to load video: resource unavailable
10:00 
+0
 -1
: Push a page contains video and pop back, do not crash. 
[E]
  TimeoutException after 0:10:00.000000: Test timed out after 10 minutes.
  package:test_api/src/backend/invoker.dart 332:28              Invoker._handleError.<fn>
  dart:async/zone.dart 1120:38                                  _rootRun
  dart:async/zone.dart 1021:19                                  _CustomZone.run
  package:test_api/src/backend/invoker.dart 330:10              Invoker._handleError
  package:test_api/src/backend/invoker.dart 283:9               Invoker.heartbeat.<fn>.<fn>
  dart:async/zone.dart 1124:13                                  _rootRun
  dart:async/zone.dart 1021:19                                  _CustomZone.run
  package:test_api/src/backend/invoker.dart 281:38              Invoker.heartbeat.<fn>
  package:stack_trace/src/stack_zone_specification.dart 209:15  StackZoneSpecification._run
  package:stack_trace/src/stack_zone_specification.dart 119:48  StackZoneSpecification._registerCallback.<fn>
  dart:async/zone.dart 1124:13                                  _rootRun
  dart:async/zone.dart 1021:19                                  _CustomZone.run
  dart:async/zone.dart 947:23                                   _CustomZone.bindCallback.<fn>
  dart:async-patch/timer_patch.dart 21:15                       Timer._createTimer.<fn>
  dart:isolate-patch/timer_impl.dart 382:19                     _Timer._runTimers
  dart:isolate-patch/timer_impl.dart 416:5                      _Timer._handleMessage
  dart:isolate-patch/isolate_patch.dart 172:12                  _RawReceivePortImpl._handleMessage
  ===== asynchronous gap ===========================
  dart:async/zone.dart 1045:19                                  _CustomZone.registerCallback
  dart:async/zone.dart 946:22                                   _CustomZone.bindCallback
  dart:async/zone.dart 1191:21                                  _rootCreateTimer
  dart:async/zone.dart 1088:19                                  _CustomZone.createTimer
  package:test_api/src/backend/invoker.dart 280:34              Invoker.heartbeat
  package:test_api/src/backend/invoker.dart 243:5               Invoker.waitForOutstandingCallbacks
  package:test_api/src/backend/declarer.dart 166:33             Declarer.test.<fn>.<fn>
  dart:async/zone.dart 1124:13                                  _rootRun
  dart:async/zone.dart 1021:19                                  _CustomZone.run
  dart:async/zone.dart 1516:10                                  _runZoned
  dart:async/zone.dart 1463:12                                  runZoned
  package:test_api/src/backend/declarer.dart 165:13             Declarer.test.<fn>
  ===== asynchronous gap ===========================
  dart:async/zone.dart 1045:19                                  _CustomZone.registerCallback
  dart:async/zone.dart 962:22                                   _CustomZone.bindCallbackGuarded
  dart:async/timer.dart 52:45                                   new Timer
  dart:async/timer.dart 87:9                                    Timer.run
  dart:async/future.dart 174:11                                 new Future
  package:test_api/src/backend/invoker.dart 399:21              Invoker._onRun.<fn>.<fn>.<fn>
10:00 
+0
 -1
: (tearDownAll)
10:00 
+0
 -1
: Push a page contains video and pop back, do not crash. 
[E]
  DriverError: Failed to fulfill WaitFor due to remote error
  Original error: Bad state: The client closed with pending request "ext.flutter.driver".
  Original stack trace:
  #0      new Client.withoutJson.<anonymous closure> (package:json_rpc_2/src/client.dart:70:24)
  #1      _RootZone.run (dart:async/zone.dart:1374:54)
  #2      _FutureListener.handleWhenComplete (dart:async/future_impl.dart:161:18)
  #3      Future._propagateToListeners.handleWhenCompleteCallback (dart:async/future_impl.dart:648:39)
  #4      Future._propagateToListeners (dart:async/future_impl.dart:704:37)
  #5      Future._propagateToListeners (dart:async/future_impl.dart:605:9)
  #6      Future._completeWithValue (dart:async/future_impl.dart:522:5)
  #7      Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:552:7)
  #8      _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
  #9      _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
  #10     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:391:30)
  #11     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:416:5)
  #12     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:12)
  package:flutter_driver/src/driver/driver.dart 449:7  FlutterDriver._sendCommand
  ===== asynchronous gap ===========================
  dart:async/zone.dart 1062:19                         _CustomZone.registerBinaryCallback
  dart:async-patch/async_patch.dart 80:23              _asyncErrorWrapperHelper
  package:test_api/src/backend/invoker.dart            Invoker.waitForOutstandingCallbacks.<fn>
  dart:async/zone.dart 1124:13                         _rootRun
  dart:async/zone.dart 1021:19                         _CustomZone.run
  dart:async/zone.dart 1516:10                         _runZoned
  dart:async/zone.dart 1463:12                         runZoned
  package:test_api/src/backend/invoker.dart 247:5      Invoker.waitForOutstandingCallbacks
  package:test_api/src/backend/declarer.dart 166:33    Declarer.test.<fn>.<fn>
  dart:async/zone.dart 1124:13                         _rootRun
  dart:async/zone.dart 1021:19                         _CustomZone.run
  dart:async/zone.dart 1516:10                         _runZoned
  dart:async/zone.dart 1463:12                         runZoned
  package:test_api/src/backend/declarer.dart 165:13    Declarer.test.<fn>
  ===== asynchronous gap ===========================
  dart:async/zone.dart 1045:19                         _CustomZone.registerCallback
  dart:async/zone.dart 962:22                          _CustomZone.bindCallbackGuarded
  dart:async/timer.dart 52:45                          new Timer
  dart:async/timer.dart 87:9                           Timer.run
  dart:async/future.dart 174:11                        new Future
  package:test_api/src/backend/invoker.dart 399:21     Invoker._onRun.<fn>.<fn>.<fn>
10:00 
+0
 -1
: 
Some tests failed.
Unhandled exception:
Dummy exception to set exit code.
#0      _rootHandleUncaughtError.<anonymous closure> (dart:async/zone.dart:1112:29)
#1      _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#2      _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#3      _Timer._runTimers (dart:isolate-patch/timer_impl.dart:391:30)
#4      _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:416:5)
#5      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:12)
Stopping application instance.
Driver tests failed: 255
The following driver tests are failing (see above for details):
 * video_player/example/test_driver/video_player.dart
 * video_player/example/test_driver/video_player.dart
```

**Comment by cyanglaz** [comment]
The issue is due to the CI's iphone simulator not able to access local video assets. We should be able to resolve this when we move our tests to firebase device lab. @collinjackson

**Comment by cyanglaz** [comment]
cc @fkorotkov

**Comment by cyanglaz** [comment]
@fkorotkov Are there any news on this?

**Comment by fkorotkov** [comment]
@cyanglaz VMs are ready but initial testing on networking for the new infrastructure failed. It wouldn't handle the load from all the potentials nodes and won't scale. I've re-implemented it during the weekend and going to configure and test everything again this week. I'll keep you posted! 🙌

**Comment by cyanglaz** [comment]
Looks like this is fixed, closing.
