### ISSUE TITLE
Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'android.view.inputmethod.InputConnection android.view.View.onCreateInputConnection(android.view.inputmethod.EditorInfo)' on a null object reference

### ISSUE THREAD

**Issue by matthewlloyd** [flutter/flutter#43043]
## Steps to Reproduce

Unknown steps to reproduce. I'm seeing about 5 of these per day from Crashlytics on a wide variety of Android devices with various Android versions. It's similar to #40659, #36441, and others, but does not seem to have the same cause.

## Logs
```
Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'android.view.inputmethod.InputConnection android.view.View.onCreateInputConnection(android.view.inputmethod.EditorInfo)' on a null object reference
       at io.flutter.plugin.editing.TextInputPlugin.createInputConnection(TextInputPlugin.java:195)
       at io.flutter.view.FlutterView.onCreateInputConnection(FlutterView.java:397)
       at android.view.inputmethod.InputMethodManager.startInputInner(InputMethodManager.java:1763)
       at android.view.inputmethod.InputMethodManager.onPostWindowFocus(InputMethodManager.java:2223)
       at android.view.ViewRootImpl.handleWindowFocusChanged(ViewRootImpl.java:3153)
       at android.view.ViewRootImpl.access$1900(ViewRootImpl.java:198)
       at android.view.ViewRootImpl$ViewRootHandler.handleMessage(ViewRootImpl.java:4951)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:214)
       at android.app.ActivityThread.main(ActivityThread.java:6986)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1445)
```

Doctor summary (to see all details, run flutter doctor -v):
```
[✓] Flutter (Channel stable, v1.9.1+hotfix.4, on Mac OS X 10.15 19A602, locale en-US)

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[!] Xcode - develop for iOS and macOS (Xcode 11.1)
    ✗ CocoaPods not installed.
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To install:
        sudo gem install cocoapods
        pod setup
[✓] Android Studio (version 3.4)
[✓] IntelliJ IDEA Ultimate Edition (version 2019.2.3)
[✓] IntelliJ IDEA Community Edition (version 2019.1.3)
[✓] VS Code (version 1.36.1)
[!] Connected device
    ! No devices available
```

**Comment by changshasha** [comment]
hey, what is the progress about this issue? I  also encountered this problem. and the device is Redmi 4x

**Comment by wurenzhijing** [comment]
This problem has occurred In many times ,  I use Flutter WebView .

**Comment by GaryQian** [comment]
The invocation in the crash no longer seems to be in the codebase, is anyone still seeing this issue?

**Comment by darshankawar** [comment]
@matthewlloyd 
Is this still a valid issue using latest Flutter version ?

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
