### ISSUE TITLE
exception from https://flutter-dashboard.appspot.com/benchmarks.html

### ISSUE THREAD

**Issue by devoncarew** [flutter/flutter#43100]
When I open the history overview for a benchmark from https://flutter-dashboard.appspot.com/benchmarks.html, I see the following exception in the console:

```
FormatException: SyntaxError: Unexpected token h in JSON at position 1
STACKTRACE: 
FormatException: SyntaxError: Unexpected token h in JSON at position 1
    at Object.b (https://flutter-dashboard.appspot.com/benchmarks.dart.js:267:3)
    at Object.q4 (https://flutter-dashboard.appspot.com/benchmarks.dart.js:1630:9)
    at iZ.am (https://flutter-dashboard.appspot.com/benchmarks.dart.js:5659:26)
    at https://flutter-dashboard.appspot.com/benchmarks.dart.js:8714:7
    at nq.a (https://flutter-dashboard.appspot.com/benchmarks.dart.js:1076:72)
    at nq.$2 (https://flutter-dashboard.appspot.com/benchmarks.dart.js:4526:23)
    at n7.$1 (https://flutter-dashboard.appspot.com/benchmarks.dart.js:4518:30)
    at jF.$1 (https://flutter-dashboard.appspot.com/benchmarks.dart.js:8034:10)
    at kr.nm [as $2$5] (https://flutter-dashboard.appspot.com/benchmarks.dart.js:1216:18)
    at bx.eq (https://flutter-dashboard.appspot.com/benchmarks.dart.js:7993:12)
```

And, the info in the history overview doesn't populate.

**Comment by keyonghan** [comment]
Done.
