### ISSUE TITLE
Firestore plugin throws java.lang.ArrayIndexOutOfBoundsException when using collection.startAfterDocument(...)

### ISSUE THREAD

**Issue by JSANL** [flutter/flutter#43116]
## Steps to Reproduce
1. Create a new Flutter project.
2. Create a new Firestore project.
3. Integrate the Firestore-Plugin into the flutter app ( `cloud_firestore: ^0.12.9+5`).
4. Add the following documents into the Collection "myCollection":
`/myCollection/1` - title: "1"
`/myCollection/2` - title: "2"
`/myCollection/3` - title: "3"
`/myCollection/4` - title: "4"
![image](https://user-images.githubusercontent.com/29028262/67164430-bdf4af80-f37a-11e9-9c5c-85b8c9328d89.png)
5. Execute the following code in the flutter app:

```dart
void main() {
  showBug();
  runApp(MyApp());
}

Future<void> showBug() async {
  final firestore = Firestore();
  final myCollection = firestore.collection("myCollection");
  final doc = await myCollection.document("2").get();
  final docs = await myCollection.startAfterDocument(doc).getDocuments();
  final output = docs.documents
      .map((doc) => "${doc.documentID} - title: ${doc.data['title']}");
  print(output);
}
```

**Target Platform:** Only tested on Android (emulator), unsure about IOS.

## Logs

```
Launching lib/main.dart on Android SDK built for x86 in debug mode...
Built build/app/outputs/apk/debug/app-debug.apk.
I/ent_start_afte(17824): Rejecting re-init on previously-failed class java.lang.Class<com.google.firebase.firestore.core.ActivityScope$StopListenerSupportFragment>: java.lang.NoClassDefFoundError: Failed resolution of: Landroid/support/v4/app/Fragment;
I/ent_start_afte(17824):   at com.google.firebase.firestore.ListenerRegistration com.google.firebase.firestore.core.ActivityScope.bind(android.app.Activity, com.google.firebase.firestore.ListenerRegistration) (com.google.firebase:firebase-firestore@@19.0.0:189)
I/ent_start_afte(17824):   at com.google.firebase.firestore.ListenerRegistration com.google.firebase.firestore.DocumentReference.addSnapshotListenerInternal(java.util.concurrent.Executor, com.google.firebase.firestore.core.EventManager$ListenOptions, android.app.Activity, com.google.firebase.firestore.EventListener) (com.google.firebase:firebase-firestore@@19.0.0:533)
I/ent_start_afte(17824):   at com.google.android.gms.tasks.Task com.google.firebase.firestore.DocumentReference.getViaSnapshotListener(com.google.firebase.firestore.Source) (com.google.firebase:firebase-firestore@@19.0.0:317)
I/ent_start_afte(17824):   at com.google.android.gms.tasks.Task com.google.firebase.firestore.DocumentReference.get(com.google.firebase.firestore.Source) (com.google.firebase:firebase-firestore@@19.0.0:302)
I/ent_start_afte(17824):   at void io.flutter.plugins.firebase.cloudfirestore.CloudFirestorePlugin.onMethodCall(io.flutter.plugin.common.MethodCall, io.flutter.plugin.common.MethodChannel$Result) (CloudFirestorePlugin.java:745)
I/ent_start_afte(17824):   at void io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(java.nio.ByteBuffer, io.flutter.plugin.common.BinaryMessenger$BinaryReply) (MethodChannel.java:222)
I/ent_start_afte(17824):   at void io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(java.lang.String, byte[], int) (DartMessenger.java:96)
I/ent_start_afte(17824):   at void io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(java.lang.String, byte[], int) (FlutterJNI.java:656)
I/ent_start_afte(17824):   at void android.os.MessageQueue.nativePollOnce(long, int) (MessageQueue.java:-2)
I/ent_start_afte(17824):   at android.os.Message android.os.MessageQueue.next() (MessageQueue.java:326)
I/ent_start_afte(17824):   at void android.os.Looper.loop() (Looper.java:160)
I/ent_start_afte(17824):   at void android.app.ActivityThread.main(java.lang.String[]) (ActivityThread.java:6669)
I/ent_start_afte(17824):   at java.lang.Object java.lang.reflect.Method.invoke(java.lang.Object, java.lang.Object[]) (Method.java:-2)
I/ent_start_afte(17824):   at void com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run() (RuntimeInit.java:493)
I/ent_start_afte(17824):   at void com.android.internal.os.ZygoteInit.main(java.lang.String[]) (ZygoteInit.java:858)
I/ent_start_afte(17824): Caused by: java.lang.ClassNotFoundException: Didn't find class "android.support.v4.app.Fragment" on path: DexPathList[[zip file "/data/app/com.example.firestore_document_start_after-GemTGGfLzNeeAtf5KnwVFw==/base.apk"],nativeLibraryDirectories=[/data/app/com.example.firestore_document_start_after-GemTGGfLzNeeAtf5KnwVFw==/lib/x86, /data/app/com.example.firestore_document_start_after-GemTGGfLzNeeAtf5KnwVFw==/base.apk!/lib/x86, /system/lib]]
I/ent_start_afte(17824):   at java.lang.Class dalvik.system.BaseDexClassLoader.findClass(java.lang.String) (BaseDexClassLoader.java:134)
I/ent_start_afte(17824):   at java.lang.Class java.lang.ClassLoader.loadClass(java.lang.String, boolean) (ClassLoader.java:379)
I/ent_start_afte(17824):   at java.lang.Class java.lang.ClassLoader.loadClass(java.lang.String) (ClassLoader.java:312)
I/ent_start_afte(17824):   at com.google.firebase.firestore.ListenerRegistration com.google.firebase.firestore.core.ActivityScope.bind(android.app.Activity, com.google.firebase.firestore.ListenerRegistration) (com.google.firebase:firebase-firestore@@19.0.0:189)
I/ent_start_afte(17824):   at com.google.firebase.firestore.ListenerRegistration com.google.firebase.firestore.DocumentReference.addSnapshotListenerInternal(java.util.concurrent.Executor, com.google.firebase.firestore.core.EventManager$ListenOptions, android.app.Activity, com.google.firebase.firestore.EventListener) (com.google.firebase:firebase-firestore@@19.0.0:533)
I/ent_start_afte(17824):   at com.google.android.gms.tasks.Task com.google.firebase.firestore.DocumentReference.getViaSnapshotListener(com.google.firebase.firestore.Source) (com.google.firebase:firebase-firestore@@19.0.0:317)
I/ent_start_afte(17824):   at com.google.android.gms.tasks.Task com.google.firebase.firestore.DocumentReference.get(com.google.firebase.firestore.Source) (com.google.firebase:firebase-firestore@@19.0.0:302)
I/ent_start_afte(17824):   at void io.flutter.plugins.firebase.cloudfirestore.CloudFirestorePlugin.onMethodCall(io.flutter.plugin.common.MethodCall, io.flutter.plugin.common.MethodChannel$Result) (CloudFirestorePlugin.java:745)
I/ent_start_afte(17824):   at void io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(java.nio.ByteBuffer, io.flutter.plugin.common.BinaryMessenger$BinaryReply) (MethodChannel.java:222)
I/ent_start_afte(17824):   at void io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(java.lang.String, byte[], int) (DartMessenger.java:96)
I/ent_start_afte(17824):   at void io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(java.lang.String, byte[], int) (FlutterJNI.java:656)
I/ent_start_afte(17824):   at void android.os.MessageQueue.nativePollOnce(long, int) (MessageQueue.java:-2)
I/ent_start_afte(17824):   at android.os.Message android.os.MessageQueue.next() (MessageQueue.java:326)
I/ent_start_afte(17824):   at void android.os.Looper.loop() (Looper.java:160)
I/ent_start_afte(17824):   at void android.app.ActivityThread.main(java.lang.String[]) (ActivityThread.java:6669)
I/ent_start_afte(17824):   at java.lang.Object java.lang.reflect.Method.invoke(java.lang.Object, java.lang.Object[]) (Method.java:-2)
I/ent_start_afte(17824):   at void com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run() (RuntimeInit.java:493)
I/ent_start_afte(17824):   at void com.android.internal.os.ZygoteInit.main(java.lang.String[]) (ZygoteInit.java:858)
I/ent_start_afte(17824):
I/ent_start_afte(17824): Rejecting re-init on previously-failed class java.lang.Class<com.google.firebase.firestore.core.ActivityScope$StopListenerSupportFragment>: java.lang.NoClassDefFoundError: Failed resolution of: Landroid/support/v4/app/Fragment;
I/ent_start_afte(17824):   at com.google.firebase.firestore.ListenerRegistration com.google.firebase.firestore.core.ActivityScope.bind(android.app.Activity, com.google.firebase.firestore.ListenerRegistration) (com.google.firebase:firebase-firestore@@19.0.0:189)
I/ent_start_afte(17824):   at com.google.firebase.firestore.ListenerRegistration com.google.firebase.firestore.DocumentReference.addSnapshotListenerInternal(java.util.concurrent.Executor, com.google.firebase.firestore.core.EventManager$ListenOptions, android.app.Activity, com.google.firebase.firestore.EventListener) (com.google.firebase:firebase-firestore@@19.0.0:533)
I/ent_start_afte(17824):   at com.google.android.gms.tasks.Task com.google.firebase.firestore.DocumentReference.getViaSnapshotListener(com.google.firebase.firestore.Source) (com.google.firebase:firebase-firestore@@19.0.0:317)
I/ent_start_afte(17824):   at com.google.android.gms.tasks.Task com.google.firebase.firestore.DocumentReference.get(com.google.firebase.firestore.Source) (com.google.firebase:firebase-firestore@@19.0.0:302)
I/ent_start_afte(17824):   at void io.flutter.plugins.firebase.cloudfirestore.CloudFirestorePlugin.onMethodCall(io.flutter.plugin.common.MethodCall, io.flutter.plugin.common.MethodChannel$Result) (CloudFirestorePlugin.java:745)
I/ent_start_afte(17824):   at void io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(java.nio.ByteBuffer, io.flutter.plugin.common.BinaryMessenger$BinaryReply) (MethodChannel.java:222)
I/ent_start_afte(17824):   at void io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(java.lang.String, byte[], int) (DartMessenger.java:96)
I/ent_start_afte(17824):   at void io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(java.lang.String, byte[], int) (FlutterJNI.java:656)
I/ent_start_afte(17824):   at void android.os.MessageQueue.nativePollOnce(long, int) (MessageQueue.java:-2)
I/ent_start_afte(17824):   at android.os.Message android.os.MessageQueue.next() (MessageQueue.java:326)
I/ent_start_afte(17824):   at void android.os.Looper.loop() (Looper.java:160)
I/ent_start_afte(17824):   at void android.app.ActivityThread.main(java.lang.String[]) (ActivityThread.java:6669)
I/ent_start_afte(17824):   at java.lang.Object java.lang.reflect.Method.invoke(java.lang.Object, java.lang.Object[]) (Method.java:-2)
I/ent_start_afte(17824):   at void com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run() (RuntimeInit.java:493)
I/ent_start_afte(17824):   at void com.android.internal.os.ZygoteInit.main(java.lang.String[]) (ZygoteInit.java:858)
I/ent_start_afte(17824): Caused by: java.lang.ClassNotFoundException: Didn't find class "android.support.v4.app.Fragment" on path: DexPathList[[zip file "/data/app/com.example.firestore_document_start_after-GemTGGfLzNeeAtf5KnwVFw==/base.apk"],nativeLibraryDirectories=[/data/app/com.example.firestore_document_start_after-GemTGGfLzNeeAtf5KnwVFw==/lib/x86, /data/app/com.example.firestore_document_start_after-GemTGGfLzNeeAtf5KnwVFw==/base.apk!/lib/x86, /system/lib]]
I/ent_start_afte(17824):   at java.lang.Class dalvik.system.BaseDexClassLoader.findClass(java.lang.String) (BaseDexClassLoader.java:134)
I/ent_start_afte(17824):   at java.lang.Class java.lang.ClassLoader.loadClass(java.lang.String, boolean) (ClassLoader.java:379)
I/ent_start_afte(17824):   at java.lang.Class java.lang.ClassLoader.loadClass(java.lang.String) (ClassLoader.java:312)
I/ent_start_afte(17824):   at com.google.firebase.firestore.ListenerRegistration com.google.firebase.firestore.core.ActivityScope.bind(android.app.Activity, com.google.firebase.firestore.ListenerRegistration) (com.google.firebase:firebase-firestore@@19.0.0:189)
I/ent_start_afte(17824):   at com.google.firebase.firestore.ListenerRegistration com.google.firebase.firestore.DocumentReference.addSnapshotListenerInternal(java.util.concurrent.Executor, com.google.firebase.firestore.core.EventManager$ListenOptions, android.app.Activity, com.google.firebase.firestore.EventListener) (com.google.firebase:firebase-firestore@@19.0.0:533)
I/ent_start_afte(17824):   at com.google.android.gms.tasks.Task com.google.firebase.firestore.DocumentReference.getViaSnapshotListener(com.google.firebase.firestore.Source) (com.google.firebase:firebase-firestore@@19.0.0:317)
I/ent_start_afte(17824):   at com.google.android.gms.tasks.Task com.google.firebase.firestore.DocumentReference.get(com.google.firebase.firestore.Source) (com.google.firebase:firebase-firestore@@19.0.0:302)
I/ent_start_afte(17824):   at void io.flutter.plugins.firebase.cloudfirestore.CloudFirestorePlugin.onMethodCall(io.flutter.plugin.common.MethodCall, io.flutter.plugin.common.MethodChannel$Result) (CloudFirestorePlugin.java:745)
I/ent_start_afte(17824):   at void io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(java.nio.ByteBuffer, io.flutter.plugin.common.BinaryMessenger$BinaryReply) (MethodChannel.java:222)
I/ent_start_afte(17824):   at void io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(java.lang.String, byte[], int) (DartMessenger.java:96)
I/ent_start_afte(17824):   at void io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(java.lang.String, byte[], int) (FlutterJNI.java:656)
I/ent_start_afte(17824):   at void android.os.MessageQueue.nativePollOnce(long, int) (MessageQueue.java:-2)
I/ent_start_afte(17824):   at android.os.Message android.os.MessageQueue.next() (MessageQueue.java:326)
I/ent_start_afte(17824):   at void android.os.Looper.loop() (Looper.java:160)
I/ent_start_afte(17824):   at void android.app.ActivityThread.main(java.lang.String[]) (ActivityThread.java:6669)
I/ent_start_afte(17824):   at java.lang.Object java.lang.reflect.Method.invoke(java.lang.Object, java.lang.Object[]) (Method.java:-2)
I/ent_start_afte(17824):   at void com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run() (RuntimeInit.java:493)
I/ent_start_afte(17824):   at void com.android.internal.os.ZygoteInit.main(java.lang.String[]) (ZygoteInit.java:858)
I/ent_start_afte(17824):
W/DynamiteModule(17824): Local module descriptor class for providerinstaller not found.
I/DynamiteModule(17824): Considering local module providerinstaller:0 and remote module providerinstaller:0
W/ProviderInstaller(17824): Failed to load providerinstaller module: No acceptable module found. Local version is 0 and remote version is 0.
I/ent_start_afte(17824): The ClassLoaderContext is a special shared library.
I/chatty  (17824): uid=10105(com.example.firestore_document_start_after) FirestoreWorker identical 1 line
I/ent_start_afte(17824): The ClassLoaderContext is a special shared library.
V/NativeCrypto(17824): Registering com/google/android/gms/org/conscrypt/NativeCrypto's 284 native methods...
W/ent_start_afte(17824): Accessing hidden method Ljava/security/spec/ECParameterSpec;->getCurveName()Ljava/lang/String; (light greylist, reflection)
D/NetworkSecurityConfig(17824): No Network Security Config specified, using platform default
I/ProviderInstaller(17824): Installed default security provider GmsCore_OpenSSL
W/ent_start_afte(17824): Accessing hidden field Ljava/nio/Buffer;->address:J (light greylist, reflection)
W/ent_start_afte(17824): Accessing hidden field Ljava/net/Socket;->impl:Ljava/net/SocketImpl; (light greylist, reflection)
W/ent_start_afte(17824): Accessing hidden method Ldalvik/system/CloseGuard;->get()Ldalvik/system/CloseGuard; (light greylist, linking)
W/ent_start_afte(17824): Accessing hidden method Ldalvik/system/CloseGuard;->open(Ljava/lang/String;)V (light greylist, linking)
W/ent_start_afte(17824): Accessing hidden field Ljava/io/FileDescriptor;->descriptor:I (light greylist, JNI)
W/ent_start_afte(17824): Accessing hidden method Ljava/security/spec/ECParameterSpec;->setCurveName(Ljava/lang/String;)V (light greylist, reflection)
W/ent_start_afte(17824): Accessing hidden method Ldalvik/system/BlockGuard;->getThreadPolicy()Ldalvik/system/BlockGuard$Policy; (light greylist, linking)
W/ent_start_afte(17824): Accessing hidden method Ldalvik/system/BlockGuard$Policy;->onNetwork()V (light greylist, linking)
D/EGL_emulation(17824): eglMakeCurrent: 0xdf6faa80: ver 3 0 (tinfo 0xdf713650)
E/MethodChannel#plugins.flutter.io/cloud_firestore(17824): Failed to handle method call
E/MethodChannel#plugins.flutter.io/cloud_firestore(17824): java.lang.ArrayIndexOutOfBoundsException: length=0; index=-1
E/MethodChannel#plugins.flutter.io/cloud_firestore(17824): 	at java.util.ArrayList.get(ArrayList.java:439)
E/MethodChannel#plugins.flutter.io/cloud_firestore(17824): 	at io.flutter.plugins.firebase.cloudfirestore.CloudFirestorePlugin.getQuery(CloudFirestorePlugin.java:262)
E/MethodChannel#plugins.flutter.io/cloud_firestore(17824): 	at io.flutter.plugins.firebase.cloudfirestore.CloudFirestorePlugin.onMethodCall(CloudFirestorePlugin.java:694)
E/MethodChannel#plugins.flutter.io/cloud_firestore(17824): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:222)
E/MethodChannel#plugins.flutter.io/cloud_firestore(17824): 	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:96)
E/MethodChannel#plugins.flutter.io/cloud_firestore(17824): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:656)
E/MethodChannel#plugins.flutter.io/cloud_firestore(17824): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/MethodChannel#plugins.flutter.io/cloud_firestore(17824): 	at android.os.MessageQueue.next(MessageQueue.java:326)
E/MethodChannel#plugins.flutter.io/cloud_firestore(17824): 	at android.os.Looper.loop(Looper.java:160)
E/MethodChannel#plugins.flutter.io/cloud_firestore(17824): 	at android.app.ActivityThread.main(ActivityThread.java:6669)
E/MethodChannel#plugins.flutter.io/cloud_firestore(17824): 	at java.lang.reflect.Method.invoke(Native Method)
E/MethodChannel#plugins.flutter.io/cloud_firestore(17824): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
E/MethodChannel#plugins.flutter.io/cloud_firestore(17824): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
E/flutter (17824): [ERROR:flutter/lib/ui/ui_dart_state.cc(148)] Unhandled Exception: PlatformException(error, length=0; index=-1, null)
[38;5;244mE/flutter (17824): #0      StandardMethodCodec.decodeEnvelope[39;49m
[38;5;244mE/flutter (17824): #1      MethodChannel.invokeMethod[39;49m
E/flutter (17824): <asynchronous suspension>
[38;5;244mE/flutter (17824): #2      MethodChannel.invokeMapMethod[39;49m
E/flutter (17824): <asynchronous suspension>
[38;5;248mE/flutter (17824): #3      Query.getDocuments[39;49m
E/flutter (17824): <asynchronous suspension>
[38;5;248mE/flutter (17824): #4      showBug[39;49m
E/flutter (17824): <asynchronous suspension>
[38;5;248mE/flutter (17824): #5      main[39;49m
[38;5;244mE/flutter (17824): #6      _runMainZoned.<anonymous closure>.<anonymous closure>  (dart:ui/hooks.dart:229:25)[39;49m
[38;5;244mE/flutter (17824): #7      _rootRun  (dart:async/zone.dart:1124:13)[39;49m
[38;5;244mE/flutter (17824): #8      _CustomZone.run  (dart:async/zone.dart:1021:19)[39;49m
[38;5;244mE/flutter (17824): #9      _runZoned  (dart:async/zone.dart:1516:10)[39;49m
[38;5;244mE/flutter (17824): #10     runZoned  (dart:async/zone.dart:1500:12)[39;49m
[38;5;244mE/flutter (17824): #11     _runMainZoned.<anonymous closure>  (dart:ui/hooks.dart:221:5)[39;49m
[38;5;244mE/flutter (17824): #12     _startIsolate.<anonymous closure>  (dart:isolate-patch/isolate_patch.dart:305:19)[39;49m
[38;5;244mE/flutter (17824): #13     _RawReceivePortImpl._handleMessage  (dart:isolate-patch/isolate_patch.dart:172:12)[39;49m
E/flutter (17824):
Application finished.
Exited (sigterm)
```

flutter doctor -v:
```
[✓] Flutter (Channel unknown, v1.9.1+hotfix.4, on Mac OS X 10.14.6 18G103, locale de-DE)
    • Flutter version 1.9.1+hotfix.4 at /Users/jonassander/development/flutter
    • Framework revision cc949a8e8b (3 weeks ago), 2019-09-27 15:04:59 -0700
    • Engine revision b863200c37
    • Dart version 2.5.0

 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/jonassander/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 10.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.2.1, Build version 10E1001
    • CocoaPods version 1.6.0

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 40.1.2
    • Dart plugin version 191.8423
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] VS Code (version 1.39.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.5.1

[✓] Connected device (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 9 (API 28) (emulator)
```

**Comment by JSANL** [comment]
I copied the issue to https://github.com/FirebaseExtended/flutterfire/issues/1287 so feel free to close this if this is now the wrong repo (I'm unsure).

**Comment by iapicca** [comment]
Hi @JSANL 
Please follow up on the issue you  linked above,
I'm closing the current one as duplicate.
If you disagree please write in the comments
and I will reopen it.
Thank you
