### ISSUE TITLE
cocoon_agent doesn't log output of some initialization commands on failure

### ISSUE THREAD

**Issue by jcollins-g** [flutter/flutter#43135]
Because the agent doesn't log the output of the failing flutter doctor command, I'm faced with a rather daunting task debugging it.  It would be nice if this logged output.

```
Task failed with the following reason:
ERROR: Command "/home/linux2/.cocoon/flutter/bin/flutter doctor" failed with exit code 1.
#0      fail (package:cocoon_agent/src/utils.dart:80:3)
flutter/cocoon#1      exec (package:cocoon_agent/src/utils.dart:256:5)

flutter/cocoon#2      flutter (package:cocoon_agent/src/utils.dart:283:10)
flutter/cocoon#3      getFlutter (package:cocoon_agent/src/utils.dart:436:9)

flutter/cocoon#4      getFlutterAt (package:cocoon_agent/src/utils.dart:196:9)

flutter/cocoon#5      ContinuousIntegrationCommand.run. (package:cocoon_agent/src/commands/ci.dart:94:21)

flutter/cocoon#6      _rootRun (dart:async/zone.dart:1120)
flutter/cocoon#7      _CustomZone.run (dart:async/zone.dart:1001)
flutter/cocoon#8      _CustomZone.runGuarded (dart:async/zone.dart:901)
flutter/cocoon#9      runZoned (dart:async/zone.dart:1463)
flutter/cocoon#10     ContinuousIntegrationCommand.run (package:cocoon_agent/src/commands/ci.dart:54:11)

flutter/cocoon#11     main (file:///home/linux2/cocoon/agent/bin/agent.dart:61:17)

flutter/cocoon#12     _startIsolate. (dart:isolate-patch/isolate_patch.dart:263)
flutter/cocoon#13     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:151)
```

See full log data [here](https://flutter-dashboard.appspot.com/api/get-log?ownerKey=ahNzfmZsdXR0ZXItZGFzaGJvYXJkclgLEglDaGVja2xpc3QiOGZsdXR0ZXIvZmx1dHRlci9mZDUxNmQ5NTM4ZTIzZGNmZWJmNDhkZGMwZWZkNzA0MWZlODA2OGNkDAsSBFRhc2sYgICAgIDkqQsM).

**Comment by iapicca** [comment]
Hi @jcollins-g is this issue still meant to be open?

**Comment by CaseyHillers** [comment]
This will be obsolete after the devicelab migration to LUCI
