### ISSUE TITLE
"Flutter build aar" command not include flutter's dependencies 

### ISSUE THREAD

**Issue by Huyamin150** [flutter/flutter#43161]
Got the ARR file with the execution of "flutter build aar". When an android native project depends on this dependency, it crashed. we have two flutter plugins in our flutter module. but I can't find it in ARR file

## Logs:

`catch exception:java.lang.NoClassDefFoundError: Failed resolution of: Lcom/github/adee42/keyboardvisibility/KeyboardVisibilityPlugin;
        at io.flutter.plugins.GeneratedPluginRegistrant.registerWith(GeneratedPluginRegistrant.java:15)
        at cn.yonghui.hyd.appframe.flutter.FlutterBaseActivity.onCreate(FlutterBaseActivity.java:57)
        at android.app.Activity.performCreate(Activity.java:7815)
        at android.app.Activity.performCreate(Activity.java:7804)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1318)
        at com.qiyukf.unicorn.i.a.callActivityOnCreate(Unknown Source:2)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3347)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3511)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2109)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7537)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:530)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:948)
     Caused by: java.lang.ClassNotFoundException: Didn't find class "com.github.adee42.keyboardvisibility.KeyboardVisibilityPlugin" on path: DexPathList[[zip file "/data/app/cn.yonghui.hyd-R7tQQrwqH9F3fpVc6Sssng==/base.apk"],nativeLibraryDirectories=[/data/app/cn.yonghui.hyd-R7tQQrwqH9F3fpVc6Sssng==/lib/arm, /data/app/cn.yonghui.hyd-R7tQQrwqH9F3fpVc6Sssng==/base.apk!/lib/armeabi-v7a, /system/lib, /system/product/lib]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:196)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at io.flutter.plugins.GeneratedPluginRegistrant.registerWith(GeneratedPluginRegistrant.java:15) 
        at cn.yonghui.hyd.appframe.flutter.FlutterBaseActivity.onCreate(FlutterBaseActivity.java:57) 
        at android.app.Activity.performCreate(Activity.java:7815) 
        at android.app.Activity.performCreate(Activity.java:7804) 
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1318) 
        at com.qiyukf.unicorn.i.a.callActivityOnCreate(Unknown Source:2) 
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3347) 
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3511) 
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83) 
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2109) 
        at android.os.Handler.dispatchMessage(Handler.java:107) 
        at android.os.Looper.loop(Looper.java:214) 
        at android.app.ActivityThread.main(ActivityThread.java:7537) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:530) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:948) 
2019-10-21 17:38:59.017 1680-3293/? W/ActivityTaskManager:   Force finishing activity cn.yonghui.hyd/.lab.flutter.FlutterHostActivity`

[✓] Flutter (Channel stable, v1.9.1+hotfix.5, on Mac OS X 10.14.5 18F132, locale zh-Hans-CN)
    • Flutter version 1.9.1+hotfix.5 at /Users/nickhu/Documents/WorkSpace/Flutter/flutter
    • Framework revision 1aedbb1835 (4 days ago), 2019-10-17 08:37:27 -0700
    • Engine revision b863200c37
    • Dart version 2.5.0

 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/nickhu/Documents/WorkSpace/AndroidSdk
    • Android NDK at /Users/nickhu/Documents/WorkSpace/AndroidSdk/ndk-bundle
    • Platform android-29, build-tools 28.0.3
    • ANDROID_HOME = /Users/nickhu/Documents/WorkSpace/AndroidSdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.1, Build version 11A1027
    • CocoaPods version 1.7.2

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 39.0.3
    • Dart plugin version 191.8423
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] VS Code (version 1.39.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.5.1

[✓] Connected device (1 available)
    • ONEPLUS A6000 • 49bb105f • android-arm64 • Android 10 (API 29)

```
```

**Comment by iapicca** [comment]
Hi @Huyamin150 
to better address the issue, would be helpful
if you could post a self contained app on github
or the steps to reproduce it.
The error you are reporting appears to be correlated to the use of a plugin

> catch exception:java.lang.NoClassDefFoundError: Failed resolution of: Lcom/github/adee42/keyboardvisibility/KeyboardVisibilityPlugin; at io.flutter.plugins.GeneratedPluginRegistrant.registerWith(GeneratedPluginRegistrant.java:15) at cn.yonghui.hyd.appframe.flutter.FlutterBaseActivity.onCreate(FlutterBaseActivity.java:57) at 

could you please share your` pubspec.yaml` as well? 

Thank you

**Comment by Huyamin150** [comment]
Here are my pubspec.yaml of my flutter package
when I execute `flutter build AAR`, it can output Multiple aars. but plugin code not be contained in `flutter_release-1.0.aar`. How can I solve the problem with one aar file can contain all the plugins that I depend on it.


![image](https://user-images.githubusercontent.com/9206069/67254573-593b7100-f4b0-11e9-86e9-3f38367b5fca.png)



`name: core
description: Base Plugin for flutter-yhstore
version: 0.0.1
author:
homepage:

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  dio: 1.0.13
  flutter_spinkit: 3.1.0
  shared_preferences: 0.4.3
  keyboard_visibility: 0.5.6
  oktoast: ^2.2.0
dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:`

**Comment by askarsyzdykov** [comment]
@Huyamin150 I use https://github.com/kezong/fat-aar-android for building aar that includes the plugins code

**Comment by kapilkarda** [comment]
I am unable to generate fat-aar can anyone help me with the process or some sort of documentation?

**Comment by david-kooi** [comment]
Having the same issue:
I have a Android library using NDK and that's packaged in a .aar and
I'd like to import this into my Flutter plugin. The build works, but during runtime I get a `java.lang.NoClassDefFoundError` when calling my import library.

Is there a way to do this without relying on 3rd party software?
Another question is whether this is a Flutter issue or a Gradle issue or something else.

Thanks

**Comment by OlegNovosad** [comment]
I have the same issue. Flutter engine is not included itself, so no `libflutter.so` for any ABI found in resulting .aar (built with fat-aar). I does contain `flutter_assets` though, but no engine.

<img width="999" alt="Screenshot 2023-11-03 at 13 58 58" src="https://github.com/flutter/flutter/assets/6299150/9392882f-0404-4d95-b8a3-59ac3d55fcec">
