### ISSUE TITLE
OOM exception when selecting a 10m picture with image_picker 0.6.0 + 8

### ISSUE THREAD

**Issue by ZhouZhiMin1** [flutter/flutter#43231]
FATAL EXCEPTION: main
Process: com.example.im_flutter, PID: 25575
java.lang.OutOfMemoryError: Failed to allocate a 207667212 byte allocation with 4194128 free bytes and 120MB until OOM
at dalvik.system.VMRuntime.newNonMovableArray(Native Method)
at android.graphics.BitmapFactory.nativeDecodeStream(Native Method)
at android.graphics.BitmapFactory.decodeStreamInternal(BitmapFactory.java:677)
at android.graphics.BitmapFactory.decodeStream(BitmapFactory.java:653)
at android.graphics.BitmapFactory.decodeFile(BitmapFactory.java:433)
at android.graphics.BitmapFactory.decodeFile(BitmapFactory.java:459)
at io.flutter.plugins.imagepicker.ImageResizer.resizedImage(ImageResizer.java:51)
at io.flutter.plugins.imagepicker.ImageResizer.resizeImageIfNeeded(ImageResizer.java:40)
at io.flutter.plugins.imagepicker.ImagePickerDelegate.handleImageResult(ImagePickerDelegate.java:530)
at io.flutter.plugins.imagepicker.ImagePickerDelegate.handleChooseImageResult(ImagePickerDelegate.java:463)
at io.flutter.plugins.imagepicker.ImagePickerDelegate.onActivityResult(ImagePickerDelegate.java:442)
at io.flutter.app.FlutterPluginRegistry.onActivityResult(FlutterPluginRegistry.java:204)
at io.flutter.app.FlutterActivityDelegate.onActivityResult(FlutterActivityDelegate.java:132)
at io.flutter.app.FlutterActivity.onActivityResult(FlutterActivity.java:142)
at android.app.Activity.dispatchActivityResult(Activity.java:6476)
at android.app.ActivityThread.deliverResults(ActivityThread.java:3975)
at android.app.ActivityThread.handleSendResult(ActivityThread.java:4022)
at android.app.ActivityThread.access$1500(ActivityThread.java:195)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1582)
at android.os.Handler.dispatchMessage(Handler.java:111)
at android.os.Looper.loop(Looper.java:207)
at android.app.ActivityThread.main(ActivityThread.java:5856)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1026)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:887)

**Comment by iapicca** [comment]
Hi @ZhouZhiMin1 
can you please provide your `flutter doctor -v`?
Thank you

**Comment by ZhouZhiMin1** [comment]
hi @iapicca 
Thank you for your reply!

This is the case with shuttle doctor -v

C:\Users\Administrator>flutter doctor -v
[√] Flutter (Channel stable, v1.9.1+hotfix.4, on Microsoft Windows [Version 10.0.17763.737], locale zh-CN)
    • Flutter version 1.9.1+hotfix.4 at G:\flutterSDK\flutter
    • Framework revision cc949a8e8b (4 weeks ago), 2019-09-27 15:04:59 -0700
    • Engine revision b863200c37
    • Dart version 2.5.0


[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at C:\Users\Administrator\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: G:\android\Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)
    • All Android licenses accepted.

[√] Android Studio (version 3.5)
    • Android Studio at G:\android\Studio
    • Flutter plugin version 39.0.3
    • Dart plugin version 191.8423
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)

[√] Connected device (1 available)
    • vivo Y67A • 99RSR8EASOVSLFDA • android-arm64 • Android 6.0 (API 23)

• No issues found!

C:\Users\Administrator>

**Comment by iapicca** [comment]
Hello again @ZhouZhiMin1 
I apologize for not noticing before; your error states
`java.lang.OutOfMemoryError: Failed to allocate a 207667212 byte allocation with 4194128 free bytes and 120MB until OOM`
So the issue it appears to be the attempt of allocating a file much larger than
10mb and of your free space.
Please consider try again verifying in advance the file size and the available space.
Closing, as this isn't an issue with Flutter itself,
if you disagree please write in the comments and I will reopen it

**Comment by ZhouZhiMin1** [comment]
@iapicca 
Thank you for your reply!

Execute  
File image = await ImagePicker.pickImage(source: ImageSource.gallery)
when I try to find a picture file

When I open the album and find a 10MB photo
It will prompt the OOMexception described above.

When selecting a 2MB photo, it can be executed normally.

I see that when pick_image selects a relatively large photo file, there is an oom exception.
