### ISSUE TITLE
`ShellTest.ReportTimingsIsCalled` is flakey

### ISSUE THREAD

**Issue by gaaclarke** [flutter/flutter#43278]
Committing and reverting a patch left LUCI with a failing test.  `ShellTest.ReportTimingsIsCalled` appears to be flakey

https://logs.chromium.org/logs/flutter/buildbucket/cr-buildbucket.appspot.com/8898879572880645808/+/steps/Host_Tests_for_host_debug_unopt/0/stdout?format=raw

```
Running Engine Unit-tests.
Running client_wrapper_glfw_unittests in /b/s/w/ir/cache/builder/src
/b/s/w/ir/cache/builder/src/out/host_debug_unopt/client_wrapper_glfw_unittests --gtest_shuffle --gtest_repeat=2
...
[ RUN      ] ShellTest.ReportTimingsIsCalled
Traceback (most recent call last):
  File "/b/s/w/ir/cache/builder/src/flutter/testing/run_tests.py", line 344, in <module>
    sys.exit(main())
  File "/b/s/w/ir/cache/builder/src/flutter/testing/run_tests.py", line 323, in main
    RunCCTests(build_dir, engine_filter)
  File "/b/s/w/ir/cache/builder/src/flutter/testing/run_tests.py", line 104, in RunCCTests
    RunEngineExecutable(build_dir, 'shell_unittests', filter, shuffle_flags)
  File "/b/s/w/ir/cache/builder/src/flutter/testing/run_tests.py", line 67, in RunEngineExecutable
    subprocess.check_call(test_command, cwd=cwd)
  File "/b/s/w/ir/cipd_bin_packages/cpython/lib/python2.7/subprocess.py", line 190, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/b/s/w/ir/cache/builder/src/out/host_debug_unopt/shell_unittests', '--gtest_shuffle', '--gtest_repeat=2']' returned non-zero exit status -11
```

**Comment by gaaclarke** [comment]
duplicate https://github.com/flutter/flutter/issues/43192
