### ISSUE TITLE
[ios13]iPhone crashed and restarted automatically while debuging.

### ISSUE THREAD

**Issue by Leafyyuki** [flutter/flutter#43320]
Recently，I updated my iPhone system version to 13.1.2.
I run flutter upgrade to update flutter to the latest stable channel, then i used my iPhone debug my flutter project, when run "flutter run" at terminal，the app can launch on my phone normally, but once the phone screen locked, probably lost connection to device. The worst thing is that my iPhone crashed and restarted automatically several times while debuging.

I tried to checkout flutter channel to dev, but the app is always black screen without any errors.
I also tried to checkout flutter channel to master, but it throwed an exception.
![image](https://user-images.githubusercontent.com/33211658/67361749-1c4ca880-f59c-11e9-8abb-b99dde94ec87.png)

**Target Platform:macOS Mojave 10.14.3 Xcode10.3**
**Target OS version:ios13.1.2**
**Devices:iphone7**

```
vpmaxx-app git:(feature-wxLogin-yuki) flutter doctor -v
[✓] Flutter (Channel stable, v1.9.1+hotfix.5, on Mac OS X 10.14.3 18D109, locale zh-Hans-CN)
    • Flutter version 1.9.1+hotfix.5 at /Users/leafyyuki/Documents/Development/flutter
    • Framework revision 1aedbb1835 (6 days ago), 2019-10-17 08:37:27 -0700
    • Engine revision b863200c37
    • Dart version 2.5.0

[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/setup/#android-setup for detailed instructions).
      If the Android SDK has been installed to a custom location, set ANDROID_HOME to that location.
      You may also want to add it to your PATH environment variable.


[✓] Xcode - develop for iOS and macOS (Xcode 10.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.3, Build version 10G8
    • CocoaPods version 1.7.5

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/setup/#android-setup for detailed instructions).

[!] IntelliJ IDEA Ultimate Edition (version 2017.3.5)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.dev/intellij-setup/#installing-the-plugins

[✓] VS Code (version 1.23.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 2.14.0
```

**Comment by iapicca** [comment]
Hi @Leafyyuki 
I noticed a reference to [cached_network_image](https://pub.dev/packages/cached_network_image) package in your error, is that correct?
Could you please provide your `flutter run --verbose`/`flutter build --verbose` ?
Also, to better address the issue, would be helpful
if you could post a self contained app on github
or the steps to reproduce it.
Please refrain 
from posting pictures if not necessary.
Thank you

**Comment by Leafyyuki** [comment]
Yes, we use package cached_network_image v1.1.1, it has error with flutter channel master.

I can reproduce the crash with flutter channel stable.
```
vpmaxx-app git:(feature-wxLogin-yuki) flutter run --verbose
[  +30 ms] executing: [/Users/leafyyuki/Documents/Development/flutter/] git log -n 1 --pretty=format:%H
[  +66 ms] Exit code 0 from: git log -n 1 --pretty=format:%H
[        ] 1aedbb1835bd6eb44550293d57d4d124f19901f0
[        ] executing: [/Users/leafyyuki/Documents/Development/flutter/] git describe --match v*.*.* --first-parent --long --tags
[  +63 ms] Exit code 0 from: git describe --match v*.*.* --first-parent --long --tags
[        ] v1.9.1+hotfix.5-0-g1aedbb183
[  +12 ms] executing: [/Users/leafyyuki/Documents/Development/flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[   +7 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/stable
[        ] executing: [/Users/leafyyuki/Documents/Development/flutter/] git ls-remote --get-url origin
[   +8 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[  +63 ms] executing: [/Users/leafyyuki/Documents/Development/flutter/] git rev-parse --abbrev-ref HEAD
[   +9 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] stable
[ +472 ms] Unable to locate an Android SDK.
[  +12 ms] Unable to locate an Android SDK.
[  +17 ms] executing: /Users/leafyyuki/Documents/Development/flutter/bin/cache/artifacts/libimobiledevice/idevice_id -h
[+5091 ms] "flutter run" took 5,603ms.
ideviceinfo returned an error:
ERROR: Could not connect to lockdownd, error code -8



#0      IMobileDevice.getInfoForDevice (package:flutter_tools/src/ios/mac.dart:228:9)
<asynchronous suspension>
#1      IOSDevice.getAttachedDevices (package:flutter_tools/src/ios/devices.dart:184:55)
<asynchronous suspension>
#2      IOSDevices.pollingGetDevices (package:flutter_tools/src/ios/devices.dart:117:57)
#3      PollingDeviceDiscovery.devices (package:flutter_tools/src/device.dart:270:52)
<asynchronous suspension>
#4      DeviceManager.getAllConnectedDevices (package:flutter_tools/src/device.dart:136:46)
<asynchronous suspension>
#5      DeviceManager.getDevices (package:flutter_tools/src/device.dart:126:11)
#6      DeviceManager.findTargetDevices (package:flutter_tools/src/device.dart:169:34)
<asynchronous suspension>
#7      FlutterCommand.findAllTargetDevices (package:flutter_tools/src/runner/flutter_command.dart:515:48)
<asynchronous suspension>
#8      RunCommand.validateCommand (package:flutter_tools/src/commands/run.dart:279:21)
<asynchronous suspension>
#9      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:465:11)
<asynchronous suspension>
#10     FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:407:33)
<asynchronous suspension>
#11     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:154:29)
<asynchronous suspension>
#12     _rootRun (dart:async/zone.dart:1124:13)
#13     _CustomZone.run (dart:async/zone.dart:1021:19)
#14     _runZoned (dart:async/zone.dart:1516:10)
#15     runZoned (dart:async/zone.dart:1463:12)
#16     AppContext.run (package:flutter_tools/src/base/context.dart:153:18)
<asynchronous suspension>
#17     FlutterCommand.run (package:flutter_tools/src/runner/flutter_command.dart:397:20)
#18     CommandRunner.runCommand (package:args/command_runner.dart:197:27)
<asynchronous suspension>
#19     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:402:21)
<asynchronous suspension>
#20     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:154:29)
<asynchronous suspension>
#21     _rootRun (dart:async/zone.dart:1124:13)
#22     _CustomZone.run (dart:async/zone.dart:1021:19)
#23     _runZoned (dart:async/zone.dart:1516:10)
#24     runZoned (dart:async/zone.dart:1463:12)
#25     AppContext.run (package:flutter_tools/src/base/context.dart:153:18)
<asynchronous suspension>
#26     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:356:19)
<asynchronous suspension>
#27     CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:112:25)
#28     new Future.sync (dart:async/future.dart:224:31)
#29     CommandRunner.run (package:args/command_runner.dart:112:14)
#30     FlutterCommandRunner.run (package:flutter_tools/src/runner/flutter_command_runner.dart:242:18)
#31     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:63:22)
<asynchronous suspension>
#32     _rootRun (dart:async/zone.dart:1124:13)
#33     _CustomZone.run (dart:async/zone.dart:1021:19)
#34     _runZoned (dart:async/zone.dart:1516:10)
#35     runZoned (dart:async/zone.dart:1500:12)
#36     run.<anonymous closure> (package:flutter_tools/runner.dart:61:18)
<asynchronous suspension>
#37     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:154:29)
<asynchronous suspension>
#38     _rootRun (dart:async/zone.dart:1124:13)
#39     _CustomZone.run (dart:async/zone.dart:1021:19)
#40     _runZoned (dart:async/zone.dart:1516:10)
#41     runZoned (dart:async/zone.dart:1463:12)
#42     AppContext.run (package:flutter_tools/src/base/context.dart:153:18)
<asynchronous suspension>
#43     runInContext (package:flutter_tools/src/context_runner.dart:59:24)
<asynchronous suspension>
#44     run (package:flutter_tools/runner.dart:50:10)
#45     main (package:flutter_tools/executable.dart:65:9)
<asynchronous suspension>
#46     main (file:///Users/leafyyuki/Documents/Development/flutter/packages/flutter_tools/bin/flutter_tools.dart:8:3)
#47     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:303:32)
#48     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:12)

```
Then my phone crashed and began to restart a minute later. It probably happened when my phone screen locked automatically.

Sorry I can't post the app on github cause it's an enterprise application.

Thank you!

**Comment by Leafyyuki** [comment]
It didn't happened before updating ios13, I'm not sure maybe it's the issue of ios13.

**Comment by iapicca** [comment]
Hi again @Leafyyuki 
thank you for providing the necessary information.
I see there's an open [issue ](https://github.com/flutter/flutter/issues/42129)addressing the case you described.
Please follow up on that issue,
I'm closing the current one as duplicate.
If you disagree please write in the comments
and I will reopen it.
Thank you

[https://github.com/flutter/flutter/issues/41911]
