### ISSUE TITLE
Adding Duplicate items to the Dropdown widget fails to provide helpful error message.

### ISSUE THREAD

**Issue by ckartik** [flutter/flutter#43333]
## Steps to Reproduce

1. Set   final XXXController = TextEditingController(text: "XXX");
2. In the items, 
```
<String>['XXX', 'YYY', 'ZZZ', 'XXX'] // XXX is repeated.
                            .map<DropdownMenuItem<String>>((String value) {
                          return DropdownMenuItem<String>(
                            value: value,
                            child: Text(value),
                          );
```
3. Run and the test error is not very descriptive at describing, that the issue is a result of non-unique items.

**Target Platform:**
- Only tested on IOS Emulator
**Target OS version/browser:**
-  Built on Darwin (Mac MacOS Mojave)
**Devices:**

## Logs
```
flutter: ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
flutter: The following assertion was thrown building XXXForm(dirty, state: XXXFormState#45fd5):
flutter: 'package:flutter/src/material/dropdown.dart': Failed assertion: line 620 pos 15: 'items == null ||
flutter: items.isEmpty || value == null || items.where((DropdownMenuItem<T> item) => item.value ==
flutter: value).length == 1': is not true.
flutter:
flutter: Either the assertion indicates an error in the framework itself, or we should provide substantially
flutter: more information in this error message to help you determine and fix the underlying cause.
flutter: In either case, please report this assertion by filing a bug on GitHub:
flutter:   https://github.com/flutter/flutter/issues/new?template=BUG.md
flutter:
flutter: User-created ancestor of the error-causing widget was:
flutter:   Center file:///Users/krishchopra/src/XXX/lib/XXXform.dart:17:13
flutter:
flutter: When the exception was thrown, this was the stack:
flutter: #2      new DropdownButton (package:flutter/src/material/dropdown.dart:620:15)
flutter: #3      XXXFormState.build (package:XXX_billing/XXXform.dart:285:23)
flutter: #4      StatefulElement.build (package:flutter/src/widgets/framework.dart:4047:27)
flutter: #5      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3941:15)
flutter: #6      Element.rebuild (package:flutter/src/widgets/framework.dart:3738:5)
flutter: #7      ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3924:5)
flutter: #8      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4088:11)
flutter: #9      ComponentElement.mount (package:flutter/src/widgets/framework.dart:3919:5)
flutter: #10     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3101:14)
flutter: #11     Element.updateChild (package:flutter/src/widgets/framework.dart:2904:12)
flutter: #12     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5127:14)
flutter: #13     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3101:14)
flutter: #14     Element.updateChild (package:flutter/src/widgets/framework.dart:2904:12)
flutter: #15     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3961:16)
flutter: #16     Element.rebuild (package:flutter/src/widgets/framework.dart:3738:5)
flutter: #17     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3924:5)
flutter: #18     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3919:5)
flutter: #19     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3101:14)
flutter: #20     Element.updateChild (package:flutter/src/widgets/framework.dart:2904:12)
flutter: #21     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3961:16)
flutter: #22     Element.rebuild (package:flutter/src/widgets/framework.dart:3738:5)
flutter: #23     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3924:5)
flutter: #24     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3919:5)
flutter: #25     ParentDataElement.mount (package:flutter/src/widgets/framework.dart:4314:11)
flutter: #26     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3101:14)
flutter: #27     MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5233:32)
flutter: #28     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3101:14)
flutter: #29     Element.updateChild (package:flutter/src/widgets/framework.dart:2904:12)
flutter: #30     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3961:16)
flutter: #31     Element.rebuild (package:flutter/src/widgets/framework.dart:3738:5)
flutter: #32     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3924:5)
flutter: #33     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4088:11)
flutter: #34     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3919:5)
flutter: #35     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3101:14)
flutter: #36     Element.updateChild (package:flutter/src/widgets/framework.dart:2904:12)
flutter: #37     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3961:16)
flutter: #38     Element.rebuild (package:flutter/src/widgets/framework.dart:3738:5)
flutter: #39     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3924:5)
flutter: #40     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3919:5)
flutter: #41     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3101:14)
flutter: #42     Element.updateChild (package:flutter/src/widgets/framework.dart:2904:12)
flutter: #43     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3961:16)
flutter: #44     Element.rebuild (package:flutter/src/widgets/framework.dart:3738:5)
flutter: #45     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3924:5)
flutter: #46     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4088:11)
flutter: #47     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3919:5)
flutter: #48     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3101:14)
flutter: #49     Element.updateChild (package:flutter/src/widgets/framework.dart:2904:12)
flutter: #50     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5127:14)
flutter: #51     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3101:14)
flutter: #52     Element.updateChild (package:flutter/src/widgets/framework.dart:2904:12)
flutter: #53     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3961:16)
flutter: #54     Element.rebuild (package:flutter/src/widgets/framework.dart:3738:5)
flutter: #55     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3924:5)
flutter: #56     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3919:5)
flutter: #57     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3101:14)
flutter: #58     Element.updateChild (package:flutter/src/widgets/framework.dart:2904:12)
flutter: #59     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5127:14)
flutter: #60     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3101:14)
flutter: #61     Element.updateChild (package:flutter/src/widgets/framework.dart:2904:12)
flutter: #62     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3961:16)
flutter: #63     Element.rebuild (package:flutter/src/widgets/framework.dart:3738:5)
flutter: #64     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3924:5)
flutter: #65     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4088:11)
flutter: #66     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3919:5)
flutter: #67     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3101:14)
flutter: #68     Element.updateChild (package:flutter/src/widgets/framework.dart:2904:12)
flutter: #69     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3961:16)
flutter: #70     Element.rebuild (package:flutter/src/widgets/framework.dart:3738:5)
flutter: #71     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3924:5)
flutter: #72     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4088:11)
flutter: #73     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3919:5)
flutter: #74     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3101:14)
flutter: #75     Element.updateChild (package:flutter/src/widgets/framework.dart:2904:12)
flutter: #76     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3961:16)
flutter: #77     Element.rebuild (package:flutter/src/widgets/framework.dart:3738:5)
flutter: #78     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3924:5)
flutter: #79     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3919:5)
flutter: #80     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3101:14)
flutter: #81     Element.updateChild (package:flutter/src/widgets/framework.dart:2904:12)
flutter: #82     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3961:16)
flutter: #83     Element.rebuild (package:flutter/src/widgets/framework.dart:3738:5)
flutter: #84     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3924:5)
flutter: #85     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3919:5)
flutter: #86     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3101:14)
flutter: #87     Element.updateChild (package:flutter/src/widgets/framework.dart:2904:12)
flutter: #88     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3961:16)
flutter: #89     Element.rebuild (package:flutter/src/widgets/framework.dart:3738:5)
flutter: #90     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3924:5)
flutter: #91     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4088:11)
flutter: #92     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3919:5)
flutter: #93     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3101:14)
flutter: #94     Element.updateChild (package:flutter/src/widgets/framework.dart:2904:12)
flutter: #95     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3961:16)
flutter: #96     Element.rebuild (package:flutter/src/widgets/framework.dart:3738:5)
flutter: #97     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3924:5)
flutter: #98     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3919:5)
flutter: #99     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3101:14)
flutter: #100    Element.updateChild (package:flutter/src/widgets/framework.dart:2904:12)
flutter: #101    SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5127:14)
flutter: #102    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3101:14)
flutter: #103    Element.updateChild (package:flutter/src/widgets/framework.dart:2904:12)
flutter: #104    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3961:16)
flutter: #105    Element.rebuild (package:flutter/src/widgets/framework.dart:3738:5)
flutter: #106    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3924:5)
flutter: #107    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3919:5)
flutter: #108    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3101:14)
flutter: #109    Element.updateChild (package:flutter/src/widgets/framework.dart:2904:12)
flutter: #110    SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5127:14)
flutter: #111    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3101:14)
flutter: #112    Element.updateChild (package:flutter/src/widgets/framework.dart:2904:12)
flutter: #113    SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5127:14)
flutter: #114    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3101:14)
flutter: #115    MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5233:32)
flutter: #116    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3101:14)
flutter: #117    Element.updateChild (package:flutter/src/widgets/framework.dart:2904:12)
flutter: #118    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3961:16)
flutter: #119    Element.rebuild (package:flutter/src/widgets/framework.dart:3738:5)
flutter: #120    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3924:5)
flutter: #121    StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4088:11)
flutter: #122    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3919:5)
flutter: #123    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3101:14)
flutter: #124    Element.updateChild (package:flutter/src/widgets/framework.dart:2904:12)
flutter: #125    SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5127:14)
flutter: #126    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3101:14)
flutter: #127    Element.updateChild (package:flutter/src/widgets/framework.dart:2904:12)
flutter: #128    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3961:16)
flutter: #129    Element.rebuild (package:flutter/src/widgets/framework.dart:3738:5)
flutter: #130    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3924:5)
flutter: #131    StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4088:11)
flutter: #132    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3919:5)
flutter: #133    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3101:14)
flutter: #134    Element.updateChild (package:flutter/src/widgets/framework.dart:2904:12)
flutter: #135    SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5127:14)
flutter: #136    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3101:14)
flutter: #137    Element.updateChild (package:flutter/src/widgets/framework.dart:2904:12)
flutter: #138    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3961:16)
flutter: #139    Element.rebuild (package:flutter/src/widgets/framework.dart:3738:5)
flutter: #140    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3924:5)
flutter: #141    StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4088:11)
flutter: #142    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3919:5)
flutter: #143    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3101:14)
flutter: #144    Element.updateChild (package:flutter/src/widgets/framework.dart:2904:12)
flutter: #145    SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5127:14)
flutter: #146    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3101:14)
flutter: #147    Element.updateChild (package:flutter/src/widgets/framework.dart:2904:12)
flutter: #148    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3961:16)
flutter: #149    Element.rebuild (package:flutter/src/widgets/framework.dart:3738:5)
flutter: #150    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3924:5)
flutter: #151    StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4088:11)
flutter: #152    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3919:5)
flutter: #153    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3101:14)
flutter: #154    Element.updateChild (package:flutter/src/widgets/framework.dart:2904:12)
flutter: #155    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3961:16)
flutter: #156    Element.rebuild (package:flutter/src/widgets/framework.dart:3738:5)
flutter: #157    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3924:5)
flutter: #158    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3919:5)
flutter: #159    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3101:14)
flutter: #160    Element.updateChild (package:flutter/src/widgets/framework.dart:2904:12)
flutter: #161    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3961:16)
flutter: #162    Element.rebuild (package:flutter/src/widgets/framework.dart:3738:5)
flutter: #163    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3924:5)
flutter: #164    StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4088:11)
flutter: #165    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3919:5)
flutter: #166    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3101:14)
flutter: #167    Element.updateChild (package:flutter/src/widgets/framework.dart:2904:12)
flutter: #168    SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5127:14)
flutter: #169    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3101:14)
flutter: #170    Element.updateChild (package:flutter/src/widgets/framework.dart:2904:12)
flutter: #171    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3961:16)
flutter: #172    Element.rebuild (package:flutter/src/widgets/framework.dart:3738:5)
flutter: #173    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3924:5)
flutter: #174    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3919:5)
flutter: #175    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3101:14)
flutter: #176    Element.updateChild (package:flutter/src/widgets/framework.dart:2904:12)
flutter: #177    SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5127:14)
flutter: #178    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3101:14)
flutter: #179    Element.updateChild (package:flutter/src/widgets/framework.dart:2904:12)
flutter: #180    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3961:16)
flutter: #181    Element.rebuild (package:flutter/src/widgets/framework.dart:3738:5)
flutter: #182    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3924:5)
flutter: #183    StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4088:11)
flutter: #184    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3919:5)
flutter: #185    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3101:14)
flutter: #186    Element.updateChild (package:flutter/src/widgets/framework.dart:2904:12)
flutter: #187    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3961:16)
flutter: #188    Element.rebuild (package:flutter/src/widgets/framework.dart:3738:5)
flutter: #189    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3924:5)
flutter: #190    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3919:5)
flutter: #191    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3101:14)
flutter: #192    Element.updateChild (package:flutter/src/widgets/framework.dart:2904:12)
flutter: #193    SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5127:14)
flutter: #194    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3101:14)
flutter: #195    Element.updateChild (package:flutter/src/widgets/framework.dart:2904:12)
flutter: #196    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3961:16)
flutter: #197    Element.rebuild (package:flutter/src/widgets/framework.dart:3738:5)
flutter: #198    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3924:5)
flutter: #199    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3919:5)
flutter: #200    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3101:14)
flutter: #201    Element.updateChild (package:flutter/src/widgets/framework.dart:2904:12)
flutter: #202    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3961:16)
flutter: #203    Element.rebuild (package:flutter/src/widgets/framework.dart:3738:5)
flutter: #204    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3924:5)
flutter: #205    StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4088:11)
flutter: #206    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3919:5)
flutter: #207    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3101:14)
flutter: #208    Element.updateChild (package:flutter/src/widgets/framework.dart:2904:12)
flutter: #209    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3961:16)
flutter: #210    Element.rebuild (package:flutter/src/widgets/framework.dart:3738:5)
flutter: #211    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3924:5)
flutter: #212    StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4088:11)
flutter: #213    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3919:5)
flutter: #214    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3101:14)
flutter: #215    Element.updateChild (package:flutter/src/widgets/framework.dart:2904:12)
flutter: #216    RenderObjectElement.updateChildren (package:flutter/src/widgets/framework.dart:4910:32)
flutter: #217    MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:5243:17)
flutter: #218    Element.updateChild (package:flutter/src/widgets/framework.dart:2893:15)
flutter: #219    _TheatreElement.update (package:flutter/src/widgets/overlay.dart:607:16)
flutter: #220    Element.updateChild (package:flutter/src/widgets/framework.dart:2893:15)
flutter: #221    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3961:16)
flutter: #222    Element.rebuild (package:flutter/src/widgets/framework.dart:3738:5)
flutter: #223    StatefulElement.update (package:flutter/src/widgets/framework.dart:4120:5)
flutter: #224    Element.updateChild (package:flutter/src/widgets/framework.dart:2893:15)
flutter: #225    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3961:16)
flutter: #226    Element.rebuild (package:flutter/src/widgets/framework.dart:3738:5)
flutter: #227    ProxyElement.update (package:flutter/src/widgets/framework.dart:4254:5)
flutter: #228    _InheritedNotifierElement.update (package:flutter/src/widgets/inherited_notifier.dart:94:11)
flutter: #229    Element.updateChild (package:flutter/src/widgets/framework.dart:2893:15)
flutter: #230    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:5134:14)
flutter: #231    Element.updateChild (package:flutter/src/widgets/framework.dart:2893:15)
flutter: #232    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3961:16)
flutter: #233    Element.rebuild (package:flutter/src/widgets/framework.dart:3738:5)
flutter: #234    StatefulElement.update (package:flutter/src/widgets/framework.dart:4120:5)
flutter: #235    Element.updateChild (package:flutter/src/widgets/framework.dart:2893:15)
flutter: #236    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:5134:14)
flutter: #237    Element.updateChild (package:flutter/src/widgets/framework.dart:2893:15)
flutter: #238    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:5134:14)
flutter: #239    Element.updateChild (package:flutter/src/widgets/framework.dart:2893:15)
flutter: #240    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3961:16)
flutter: #241    Element.rebuild (package:flutter/src/widgets/framework.dart:3738:5)
flutter: #242    StatelessElement.update (package:flutter/src/widgets/framework.dart:4016:5)
flutter: #243    Element.updateChild (package:flutter/src/widgets/framework.dart:2893:15)
flutter: #244    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3961:16)
flutter: #245    Element.rebuild (package:flutter/src/widgets/framework.dart:3738:5)
flutter: #246    BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2348:33)
flutter: #247    WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:760:20)
flutter: #248    RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:280:5)
flutter: #249    SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1033:15)
flutter: #250    SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:975:9)
flutter: #251    SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:891:5)
flutter: #255    _invoke (dart:ui/hooks.dart:249:10)
flutter: #256    _drawFrame (dart:ui/hooks.dart:207:3)
flutter: (elided 5 frames from class _AssertionError and package dart:async)
flutter:
flutter: ════════════════════════════════════════════════════════════════════════════════════════════════════

Lost connection to device.
```

##flutter run --verbose logs

```

```

```
Analyzing app...                                    

   info • The value of the field '_biggerFont' isn't used • lib/main.dart:31:9 • unused_field
   info • The declaration '_buildRow' isn't referenced • lib/main.dart:33:10 • unused_element
   info • The type parameter 'submit' is annotated with @required but only named parameters without default value can be annotated with it • lib/form.dart:7:15 • invalid_required_param
   info • The type parameter 'submit' is annotated with @required but only named parameters without default value can be annotated with it • lib/XXX.dart:26:15 • invalid_required_param
   info • The type parameter 'submit' is annotated with @required but only named parameters without default value can be annotated with it • lib/XXX.dart:48:20 • invalid_required_param
   info • The value of the local variable 'selectedDate' isn't used • lib/XXX.dart:194:22 • unused_local_variable


```

```
[✓] Flutter (Channel beta, v1.9.1+hotfix.4, on Mac OS X 10.14.5 18F132, locale en-CA)
    • Flutter version 1.9.1+hotfix.4 at /Users/krishchopra/flutter
    • Framework revision cc949a8e8b (4 weeks ago), 2019-09-27 15:04:59 -0700
    • Engine revision b863200c37
    • Dart version 2.5.0

[!] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/krishchopra/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 28.0.3
    ✗ Android SDK file not found: /Users/krishchopra/Library/Android/sdk/platforms/android-29/android.jar.
    • Try re-installing or updating your Android SDK,
      visit https://flutter.dev/setup/#android-setup for detailed instructions.

[!] Xcode - develop for iOS and macOS (Xcode 11.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.1, Build version 11A1027
    ✗ CocoaPods not installed.
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin code that responds to your plugin usage on the Dart
        side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To install:
        sudo gem install cocoapods
        pod setup

[✓] Android Studio (version 3.4)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 36.1.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

[✓] Connected device (1 available)
    • iPhone 11 Pro Max • CC908883-8525-47A2
```

**Comment by ckartik** [comment]
I've fixed the issue on my end, just wanted to put out an issue because they error message could have been better.
