### ISSUE TITLE
Flutter ImagePicker Plugin (MissingPluginException - No implementation found for method pickImage)

### ISSUE THREAD

**Issue by hashirabdulbasheer** [flutter/flutter#43336]
I am using image_picker 0.6.1+8 . I am getting the following exception:
```
_[VERBOSE-2:ui_dart_state.cc(148)] Unhandled Exception: MissingPluginException(No implementation found for method pickImage on channel plugins.flutter.io/image_picker)
#0      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:319:7)
<asynchronous suspension>
#1      ImagePicker.pickImage (package:image_picker/image_picker.dart:62:40)
<asynchronous suspension>_
```
**Here are my observations**:

1) Happens only on iOS. The plugin works perfectly on android.

2) I debugged the plugin a little bit and found its "registerWithRegistrar" method to be called correctly inside the plugin. However, the "handleMethodCall" never gets invoked in the plugin. The exception gets thrown when InvokeMethod is called.

3) A handler in our appdelegate.m gets called if we register a handler using the plugin channel there. However, the plugin "handleMethodCall" is not invoked. 

4) Other plugins like shared_preferences also have the same issue. 

**My flutter doctor output**
```
flutter doctor -v
[✓] Flutter (Channel beta, v1.10.7, on Mac OS X 10.14.3 18D109, locale en-SA)
    • Flutter version 1.10.7 at /Users/hashir/Developer/flutter
    • Framework revision e70236e36c (3 weeks ago), 2019-10-02 09:32:30 -0700
    • Engine revision 9e6314d348
    • Dart version 2.6.0 (build 2.6.0-dev.0.0 1103600280)

[!] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/hashir/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 28.0.3
    ✗ Android SDK file not found: /Users/hashir/Library/Android/sdk/platforms/android-29/android.jar.
    • Try re-installing or updating your Android SDK,
      visit https://flutter.dev/setup/#android-setup for detailed instructions.

 
[✓] Xcode - develop for iOS and macOS (Xcode 10.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.3, Build version 10G8
    • CocoaPods version 1.8.0

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 39.0.3
    • Dart plugin version 191.8423
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] Connected device (1 available)
    • iPhone Xʀ • 4A93D602-957E-4BE2-8E5E-2F5B931590CB • ios • com.apple.CoreSimulator.SimRuntime.iOS-12-4 (simulator)

```

**Comment by hashirabdulbasheer** [comment]
we had converted an existing iOS app into flutter. We did it long time back and it was not as per the guidelines specified in https://github.com/flutter/flutter/wiki/Add-Flutter-to-existing-apps.

Following the guidelines mentioned in the wiki to convert existing ios app into flutter solves the missing plugin exceptions.

**Comment by suthishan** [comment]
MissingPluginException(No implementation found for method  pickImage on channel plugins.flutter.io/image_picker)
