### ISSUE TITLE
Flutter HTTP post [ERROR:flutter/lib/ui/ui_dart_state.cc(148)] Unhandled Exception: SocketException: Failed host lookup: 'api.qrmoney.ml' (OS Error: No address associated with hostname, errno = 7)

### ISSUE THREAD

**Issue by Abdusin** [flutter/flutter#43357]
```
static Future postLogin(String mail, String sifre) async {
    String url = 'http://api.qrmoney.ml/UserCheck.php';
    Map<String, String> headers = {"Content-type": "application/x-www-form-urlencoded"};
    String bodyJson = '{"email": "$mail", "password": "$sifre"}';
    Response response= await http.post(url, headers: headers, body: bodyJson);
    String body = response.body;
    return json.decode(body);
  }
```
I add this
`<uses-permission android:name="android.permission.INTERNET"/>`
but problem not solved

```
>[ERROR:flutter/lib/ui/ui_dart_state.cc(148)] Unhandled Exception: SocketException: Failed host lookup: 'api.qrmoney.ml' (OS Error: No address associated with hostname, errno = 7)
>E/flutter ( 8536): #0      IOClient.send (package:http/src/io_client.dart:33:23)
>E/flutter ( 8536): <asynchronous suspension>
E/flutter ( 8536): #1      BaseClient._sendUnstreamed (package:http/src/base_client.dart:169:38)
E/flutter ( 8536): <asynchronous suspension>
E/flutter ( 8536): #2      BaseClient.post (package:http/src/base_client.dart:54:7)
E/flutter ( 8536): #3      post.<anonymous closure> (package:http/http.dart:70:16)
E/flutter ( 8536): #4      _withClient (package:http/http.dart:166:20)
E/flutter ( 8536): <asynchronous suspension>
E/flutter ( 8536): #5      post (package:http/http.dart:69:5)
E/flutter ( 8536): #6      JsonApi.postLogin (package:flutter_ui_collections/utils/json.dart:27:24)
E/flutter ( 8536): <asynchronous suspension>
E/flutter ( 8536): #7      _LoginPageState._loginButtonWidget.<anonymous closure> (package:flutter_ui_collections/ui/page_login.dart:193:21)
E/flutter ( 8536): #17     GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:102:7)
E/flutter ( 8536): #18     GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:86:7)
E/flutter ( 8536): #19     _rootRunUnary (dart:async/zone.dart:1136:13)
E/flutter ( 8536): #20     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
E/flutter ( 8536): #21     _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
E/flutter ( 8536): #22     _invoke1 (dart:ui/hooks.dart:263:10)
E/flutter ( 8536): #23     _dispatchPointerDataPacket (dart:ui/hooks.dart:172:5) 
```

Flutter doctor
```
>[√] Flutter (Channel stable, v1.9.1+hotfix.5, on Microsoft Windows [Version 10.0.18362.295], locale >tr-TR)
>
>[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
>[√] Android Studio (version 3.5)
>[√] VS Code (version 1.39.2)
>[√] Connected device (1 available)
>
>• No issues found!
```
flutter analyze
```
>Analyzing qrMoney...
>No issues found! (ran in 24.1s)
```

**Comment by Hixie** [comment]
This would happen when the DNS server can't be reached or when the host in question is not in DNS. I don't think this is a Flutter problem. Can you elaborate on what you are seeing, @Abdusin ?

**Comment by Abdusin** [comment]
> This would happen when the DNS server can't be reached or when the host in question is not in DNS. I don't think this is a Flutter problem. Can you elaborate on what you are seeing, @Abdusin ?

we switched to a different DNS server and the system is running

**Comment by aliazimoshan** [comment]
I solved my problem by turning off my VPN.

**Comment by sheheryarkhan501** [comment]
add internet permissions to your android manifest
