### ISSUE TITLE
PopupMenuButton/PopupMenuItem broken (in the AppBar)

### ISSUE THREAD

**Issue by drewwarren** [flutter/flutter#4336]
## Steps to Reproduce

I have only tested this on the iOS simulator within an AppBar. Things work fine on the alpha branch.

on master run the flutter_gallery, open the grid demo, and click the ellipsis menu in the top right of the app bar.

## Flutter Doctor

```
flutter_gallery (master %)$ flutter doctor
[✓] Flutter (on Mac OS, channel master)
    • Flutter at /Users/drewwarren/flutter
    • Framework revision d8d0d6b31b (64 minutes ago), engine revision a943c732d5

[x] Android toolchain - develop for Android devices
    x Android Studio / Android SDK not found. Download from https://developer.android.com/sdk/
      (or visit https://flutter.io/setup/#android-setup for detailed instructions).

[✓] iOS toolchain - develop for iOS devices (Xcode 7.3.1)
    • XCode at /Applications/Xcode.app/Contents/Developer
    • Xcode 7.3.1, Build version 7D1014

[✓] Atom - a lightweight development environment for Flutter
    • flutter plugin version 0.2.2
    • dartlang plugin version 0.6.12
```

## Logs and Crash Reports

```
══╡ EXCEPTION CAUGHT BY RENDERING LIBRARY ╞═════════════════════════════════════════════════════════
The following assertion was thrown during performLayout():
'package:flutter/src/rendering/proxy_box.dart': Failed assertion: line 543 pos 12: 'width ==
constraints.constrainWidth(width)' is not true.
Either the assertion indicates an error in the framework itself, or we should provide substantially
more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new
When the exception was thrown, this was the stack:
#0      _AssertionError._throwNew (dart:core-patch/errors_patch.dart:27)
#1      RenderIntrinsicWidth._getInnerConstraints (package:flutter/src/rendering/proxy_box.dart:543:12)
#2      RenderIntrinsicWidth.performLayout (package:flutter/src/rendering/proxy_box.dart:582:41)
#3      RenderObject.layout (package:flutter/src/rendering/object.dart:1425:21)
#4      RenderConstrainedBox.performLayout (package:flutter/src/rendering/proxy_box.dart:232:13)
#5      RenderObject.layout (package:flutter/src/rendering/object.dart:1425:21)
#6      RenderPositionedBox.performLayout (package:flutter/src/rendering/shifted_box.dart:336:13)
#7      RenderObject.layout (package:flutter/src/rendering/object.dart:1425:21)
#8      RenderProxyBox.performLayout (package:flutter/src/rendering/proxy_box.dart:82:13)
#9      RenderObject.layout (package:flutter/src/rendering/object.dart:1425:21)
#10     RenderProxyBox.performLayout (package:flutter/src/rendering/proxy_box.dart:82:13)
#11     RenderObject.layout (package:flutter/src/rendering/object.dart:1425:21)
#12     RenderProxyBox.performLayout (package:flutter/src/rendering/proxy_box.dart:82:13)
#13     RenderObject.layout (package:flutter/src/rendering/object.dart:1425:21)
#14     RenderProxyBox.performLayout (package:flutter/src/rendering/proxy_box.dart:82:13)
#15     RenderObject.layout (package:flutter/src/rendering/object.dart:1425:21)
#16     RenderProxyBox.performLayout (package:flutter/src/rendering/proxy_box.dart:82:13)
#17     RenderObject.layout (package:flutter/src/rendering/object.dart:1425:21)
#18     RenderCustomSingleChildLayoutBox.performLayout (package:flutter/src/rendering/shifted_box.dart:833:13)
#19     RenderObject.layout (package:flutter/src/rendering/object.dart:1425:21)
#20     RenderProxyBox.performLayout (package:flutter/src/rendering/proxy_box.dart:82:13)
#21     RenderObject.layout (package:flutter/src/rendering/object.dart:1425:21)
#22     RenderProxyBox.performLayout (package:flutter/src/rendering/proxy_box.dart:82:13)
#23     RenderObject.layout (package:flutter/src/rendering/object.dart:1425:21)
#24     RenderProxyBox.performLayout (package:flutter/src/rendering/proxy_box.dart:82:13)
#25     RenderObject.layout (package:flutter/src/rendering/object.dart:1425:21)
#26     RenderStack.performLayout (package:flutter/src/rendering/stack.dart:328:15)
#27     RenderObject._layoutWithoutResize (package:flutter/src/rendering/object.dart:1303:21)
#28     PipelineOwner.flushLayout (package:flutter/src/rendering/object.dart:822:18)
#29     BindingBase&SchedulerBinding&GestureBinding&ServicesBinding&RendererBinding.beginFrame (package:flutter/src/rendering/binding.dart:152:19)
#30     BindingBase&SchedulerBinding&GestureBinding&ServicesBinding&RendererBinding&WidgetsBinding.beginFrame (package:flutter/src/widgets/binding.dart:205:21)
#31     BindingBase&SchedulerBinding&GestureBinding&ServicesBinding&RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:144:5)
#32     BindingBase&SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:428:15)
#33     BindingBase&SchedulerBinding.handleBeginFrame (package:flutter/src/scheduler/binding.dart:388:7)
#34     _beginFrame (file:///b/build/slave/Mac_Engine/build/src/out/ios_debug_sim/gen/sky/bindings/hooks.dart:48)
The following RenderObject was being processed when the exception was fired:
  RenderIntrinsicWidth relayoutSubtreeRoot=up8 NEEDS-LAYOUT
This RenderObject had the following creator information:
  IntrinsicWidth ← ConstrainedBox ← Align ← DefaultTextStyle ← AnimatedDefaultTextStyle ←
  _InkFeatures-[GlobalKey ink renderer] ← NotificationListener<LayoutChangedNotification> ←
  ClipRRect ← DecoratedBox ← Container ← ⋯
This RenderObject had the following descendants (showing up to depth 5):
  RenderSemanticsGestureHandler NEEDS-LAYOUT
    RenderPointerListener NEEDS-LAYOUT
      RenderViewport NEEDS-LAYOUT
        RenderPadding NEEDS-LAYOUT
          RenderBlock NEEDS-LAYOUT
════════════════════════════════════════════════════════════════════════════════════════════════════
Another exception was thrown: 'package:flutter/src/rendering/box.dart': Failed assertion: line 673 pos 12: 'hasSize' is not true.
(last message repeated 16 times)
Another exception was thrown: 'package:flutter/src/rendering/object.dart': Failed assertion: line 1371 pos 12: '!_debugDoingThisLayout' is not true.
Another exception was thrown: 'package:flutter/src/rendering/box.dart': Failed assertion: line 673 pos 12: 'hasSize' is not true.
(last message repeated 7 times)
Another exception was thrown: 'package:flutter/src/rendering/object.dart': Failed assertion: line 1371 pos 12: '!_debugDoingThisLayout' is not true.
Another exception was thrown: 'package:flutter/src/rendering/box.dart': Failed assertion: line 673 pos 12: 'hasSize' is not true.
(last message repeated 7 times)
Another exception was thrown: 'package:flutter/src/rendering/object.dart': Failed assertion: line 1371 pos 12: '!_debugDoingThisLayout' is not true.
Another exception was thrown: 'package:flutter/src/rendering/box.dart': Failed assertion: line 673 pos 12: 'hasSize' is not true.
(last message repeated 7 times)
Another exception was thrown: 'package:flutter/src/rendering/object.dart': Failed assertion: line 1371 pos 12: '!_debugDoingThisLayout' is not true.
Another exception was thrown: 'package:flutter/src/rendering/box.dart': Failed assertion: line 673 pos 12: 'hasSize' is not true.
(last message repeated 7 times)
Another exception was thrown: 'package:flutter/src/rendering/object.dart': Failed assertion: line 1371 pos 12: '!_debugDoingThisLayout' is not true.
Another exception was thrown: 'package:flutter/src/rendering/box.dart': Failed assertion: line 673 pos 12: 'hasSize' is not true.
(last message repeated 8 times)
Another exception was thrown: 'package:flutter/src/rendering/object.dart': Failed assertion: line 1949 pos 14: '_semantics != null' is not true.
```

**Comment by Hixie** [comment]
Oops. This is mine.

**Comment by Hixie** [comment]
I have a fix but I still need to write a test.

**Comment by Hixie** [comment]
Fix landed. Let me know if this isn't fixed for you. Thanks!

**Comment by Hixie** [comment]
...or not
