### ISSUE TITLE
Can't create new flutter project

### ISSUE THREAD

**Issue by FloP1398** [flutter/flutter#43431]
Hi,

I wanted to create a new flutter project on Android Studio but instead of a flutter project, a text file have created with this error : 
```## command

flutter --no-color create --template app --description A new Flutter application. --org com.florian test5

## exception

TemplateException: Value was missing for variable tag: macosIdentifier. (11:29)
PRODUCT_BUNDLE_IDENTIFIER = {{macosIdentifier}}
                            ^

#0      Renderer.visitVariable (package:mustache/src/renderer.dart:101:9)
#1      VariableNode.accept (package:mustache/src/node.dart:45:43)
#2      Renderer.render.<anonymous closure> (package:mustache/src/renderer.dart:58:30)
#3      List.forEach (dart:core-patch/growable_array.dart:283:8)
#4      Renderer.render (package:mustache/src/renderer.dart:58:13)
#5      Template.render (package:mustache/src/template.dart:40:14)
#6      Template.renderString (package:mustache/src/template.dart:33:5)
#7      Template.render.<anonymous closure> (package:flutter_tools/src/template.dart:172:77)
#8      _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:377:8)
#9      Template.render (package:flutter_tools/src/template.dart:124:24)
#10     CreateCommand._renderTemplate (package:flutter_tools/src/commands/create.dart:623:21)
#11     CreateCommand._generateApp (package:flutter_tools/src/commands/create.dart:546:23)
<asynchronous suspension>
#12     CreateCommand.runCommand (package:flutter_tools/src/commands/create.dart:397:37)
<asynchronous suspension>
#13     FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:490:18)
#14     _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:71:64)
#15     _rootRunUnary (dart:async/zone.dart:1132:38)
#16     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#17     _FutureListener.handleValue (dart:async/future_impl.dart:137:18)
#18     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:678:45)
#19     Future._propagateToListeners (dart:async/future_impl.dart:707:32)
#20     Future._completeWithValue (dart:async/future_impl.dart:522:5)
#21     Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:552:7)
#22     _rootRun (dart:async/zone.dart:1124:13)
#23     _CustomZone.run (dart:async/zone.dart:1021:19)
#24     _CustomZone.runGuarded (dart:async/zone.dart:923:7)
#25     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:963:23)
#26     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#27     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#28     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:116:13)
#29     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:173:5)
```

then flutter doctor says : 

```
[✓] Flutter (Channel stable, v1.9.1+hotfix.5, on Microsoft Windows [version 10.0.18362.418], locale fr-FR)
    • Flutter version 1.9.1+hotfix.5 at C:\src\flutter\flutter
    • Framework revision 1aedbb1835 (7 days ago), 2019-10-17 08:37:27 -0700
    • Engine revision b863200c37
    • Dart version 2.5.0

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at C:\Users\flopi\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)
    • All Android licenses accepted.

[✓] Android Studio (version 3.5)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 40.2.2
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)

[✓] Connected device (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 7.1.1 (API 25) (emulator)

• No issues found!
```

I found nothing useful on github or anywhere else.
Do you have an idea about what's going wrong?

Thanks
Florian

**Comment by stuartmorgan** [comment]
That error suggests that parts of your Flutter tree are at different versions. For instance, perhaps your last `upgrade` failed part way through.

Does your Flutter tree show any local changes?

**Comment by FloP1398** [comment]
> Flutter tree show any local changes ?
I don't think so. How can I check that?

To be sure it wasn't problem with flutter, I just erased and reinstalled flutter's files and it still the same problem. I'm gonna delete Android Studio and reinstall it.

**Comment by stuartmorgan** [comment]
`git status` in your Flutter tree.

How are you installing? Via `git clone`, or a download?

**Comment by FloP1398** [comment]
Flutter tree is normal.
I installed via a download.

**Comment by stuartmorgan** [comment]
I just downloaded the 1.9.1+hotfix.5 for Windows and verified that it does *not* contain `packages/flutter_tools/templates/app/macos.tmpl`, which is the file that would cause this error (and which should not existing in 1.9.1, only on more recent channels).

Are you certain that the Flutter tree you are checking/replacing is the one being used by Android Studio?

**Comment by FloP1398** [comment]
When I use ```git status``` in the terminal of my last flutter project, I had this : 
```
On branch master
Your branch is up to date with 'test4-versionjspjenaimarre/master'.

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
        modified:   android/gradle.properties
        modified:   lib/components/CustomRadioButton.dart
        modified:   lib/components/ListeVilles.dart
        modified:   lib/components/TileDetailProduit.dart
        modified:   lib/components/TileResultatProduitBoutique.dart
        modified:   lib/components/TileResultatRecherche.dart
        modified:   lib/components/my_drawer.dart
        modified:   lib/constantes.dart
        modified:   lib/main.dart
        modified:   lib/screens/boutique_screen.dart
        modified:   lib/screens/fullscreen_image_screen.dart
        modified:   lib/screens/login_screen.dart
        modified:   lib/screens/mon_profil_screen.dart
        modified:   lib/screens/produit_detail_screen.dart
        modified:   lib/screens/recherche_screen.dart
        modified:   lib/screens/registration_screen.dart
        modified:   "lib/screens/resultat_recherche-screen.dart"
        modified:   lib/screens/welcome_screen.dart
        modified:   lib/services/networking.dart
        modified:   pubspec.yaml
        modified:   test/widget_test.dart

no changes added to commit (use "git add" and/or "git commit -a")

```

components, screens, services, main and constantes are files/folders that I created for my project.
Is-it a normal result?

**Comment by stuartmorgan** [comment]
That's your project, not Flutter itself. You'll need to run `git status` in `C:\src\flutter\flutter`.

**Comment by FloP1398** [comment]
Ok then I got this :

```
C:\src\flutter\flutter>git status
On branch stable
Your branch is up to date with 'origin/stable'.

nothing to commit, working tree clean
```

**Comment by stuartmorgan** [comment]
Going back to my question above then, are you sure you don't have a different copy of Flutter that Android Studio is using? I don't see how you could possibly be getting that error from a clean tree.

E.g., does running `flutter create` from the same command prompt where you ran `doctor` above fail with the same error?

**Comment by FloP1398** [comment]
I just checked and I have only flutter copy that Android Studio is using.

When I ran ```flutter doctor``` , I don't have any trouble, contrary to ```flutter create``` .

**Comment by stuartmorgan** [comment]
To clarify, I was asking if `flutter create` from the command line fails with the same error you are seeing in Android Studio. I understand that `doctor` works

**Comment by FloP1398** [comment]
I'm sorry.
Well, I got this message at the end, with no error before : 
```
Wrote 65 files.

All done!
[√] Flutter is fully installed. (Channel stable, v1.9.1+hotfix.6, on Microsoft Windows [version 10.0.18362.418], locale
    fr-FR)
[√] Android toolchain - develop for Android devices is fully installed. (Android SDK version 29.0.2)
[√] Android Studio is fully installed. (version 3.5)
[!] Connected device is not available.

Run "flutter doctor" for information about installing additional components.

In order to run your application, type:

  $ cd create_test
  $ flutter run

Your application code is in create_test\lib\main.dart.
```

This way works to create a new flutter project obviously.

**Comment by stuartmorgan** [comment]
I don't see any explanation here other than that Android Studio is not using that Flutter tree, and instead has a different copy that is in a bad state.

It's impossible to get that error without a file that you don't have in that tree, and if somehow you did have it without git reporting it your command-line `create` would have had the same error.

**Comment by FloP1398** [comment]
Impossible seems to follow me for years XD

Anyway, I have deleted Android Studio and Flutter files, turned off my PC, re-installed both and, miracle, now it looks working nicely.

Thanks a lot for your help, @stuartmorgan 👍

**Comment by FloP1398** [comment]
Impossible seems to follow me for years XD

Anyway, I have deleted Android Studio and Flutter files, turned off my PC, re-installed both and, miracle, now it looks working nicely.

Thanks a lot for your help, @stuartmorgan 👍
