### ISSUE TITLE
[Add2App] App crashes when orientation changes while Recent Apps list is open on Android

### ISSUE THREAD

**Issue by dannyvalentesonos** [flutter/flutter#43459]
Using the new embedding API for Android to embed Flutter in an existing app, it is possible for the app to crash when bringing up the Recent Apps List.

1. Simply launch an activity with a Flutter embedding fragment
2. With app (and flutter view) in foreground, bring up the Recent Apps list
3. Change the orientation of the device with the Recent Apps list showing
4. Come back to the app

A crash happens at this point. Here is the crash log:

```
--------- beginning of crash
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.sonos.acr, PID: 5757
    java.lang.NullPointerException: Attempt to invoke virtual method 'io.flutter.embedding.engine.systemchannels.LocalizationChannel io.flutter.embedding.engine.FlutterEngine.getLocalizationChannel()' on a null object reference
        at io.flutter.embedding.android.FlutterView.sendLocalesToFlutter(FlutterView.java:737)
        at io.flutter.embedding.android.FlutterView.onConfigurationChanged(FlutterView.java:262)
        at android.view.View.dispatchConfigurationChanged(View.java:10498)
        at android.view.ViewGroup.dispatchConfigurationChanged(ViewGroup.java:1312)
        at android.view.ViewGroup.dispatchConfigurationChanged(ViewGroup.java:1316)
        at android.view.ViewGroup.dispatchConfigurationChanged(ViewGroup.java:1316)
        at android.view.ViewGroup.dispatchConfigurationChanged(ViewGroup.java:1316)
        at android.view.ViewGroup.dispatchConfigurationChanged(ViewGroup.java:1316)
        at android.view.ViewGroup.dispatchConfigurationChanged(ViewGroup.java:1316)
        at android.view.ViewRootImpl.updateConfiguration(ViewRootImpl.java:3341)
        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1771)
        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1254)
        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6337)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:874)
        at android.view.Choreographer.doCallbacks(Choreographer.java:686)
        at android.view.Choreographer.doFrame(Choreographer.java:621)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:860)
        at android.os.Handler.handleCallback(Handler.java:751)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:154)
        at android.app.ActivityThread.main(ActivityThread.java:6119)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
```

**Comment by xster** [comment]
Can you paste the `flutter doctor` output?`

**Comment by dannyvalentesonos** [comment]
```
[✓] Flutter (Channel dev, v1.10.14, on Mac OS X 10.14.6 18G103, locale en-US)
    • Flutter version 1.10.14 at /Users/danny.valente/Library/flutter/1.10.14-dev
    • Framework revision 1946fc4da0 (3 weeks ago), 2019-10-07 15:23:31 -0700
    • Engine revision 1d62160fdb
    • Dart version 2.6.0 (build 2.6.0-dev.1.0 d6c6d12ebf)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/danny.valente/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.0, Build version 11A420a
    • CocoaPods version 1.7.5

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 40.2.2
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
```

**Comment by dnfield** [comment]
I'm able to reproduce this.

**Comment by dnfield** [comment]
Issue appears to be that we get disconnected from the engine when going to the background, then we come to the foreground and get the `onConfigurationChanged` before we're reattached to the FlutterEngine, and then we get an NPE.

/cc @matthew-carroll  - any thoughts on this?

**Comment by matthew-carroll** [comment]
I can try to repro, but the engine should be attached in `onCreate()` and I can't imagine that `onConfigurationChanged()` is called before `onCreate()`, is it?

**Comment by dnfield** [comment]
`onConfigurationChanged()` is indeed getting called before `onCreate`.

**Comment by matthew-carroll** [comment]
Hm, ok. I'll add this ticket to the refactor project and add it to the code freeze priority list. Hopefully I can take a crack at it today or tomorrow.

**Comment by dnfield** [comment]
Actually trying to validate that still.. I thought it was in the log clearly but now I'm not so sure.

**Comment by matthew-carroll** [comment]
Actually, does onConfigurationChanged() even execute in a normal activity that doesn't override config changes? Does the Activity in question override orientation change?

**Comment by dannyvalentesonos** [comment]
Thanks for looking into this @dnfield. Any chance that #35054 is related to this too?
@matthew-carroll any chance you can get it added to the refactor project too, seeing users lose the ability to type in a text field.
Thanks!

**Comment by dnfield** [comment]
onConfigurationChanged is in the FlutterView

**Comment by matthew-carroll** [comment]
From Android docs for `View` for `onConfigurationChanged()`: 

> You only need to use this if you are not relying on the normal Activity mechanism of recreating the activity instance upon a configuration change.

So is the containing Activity overriding configuration changes?

**Comment by matthew-carroll** [comment]
CC @xster for @dannyvalentesonos above question about adding #35054 to the code freeze priority list.

**Comment by xster** [comment]
We should fix it for phase 1. Can @dnfield help you propose a solution?

**Comment by matthew-carroll** [comment]
For #35054 we should loop in @collinjackson for related testing infra, @gspencergoog for visibility, and @nturgut for web visibility.

**Comment by dnfield** [comment]
Matt and I worked this out - patch will be incoming momentarily.

**Comment by dannyvalentesonos** [comment]
@dnfield Thanks for fixing this. Will this be in the next Dev build?

**Comment by dnfield** [comment]
Probably not the next one, maybe the one after.
