### ISSUE TITLE
Unhandled exception when using of Listener

### ISSUE THREAD

**Issue by micrcx** [flutter/flutter#43483]
I've found a strange error when using Listener, namely **unhandled exception**:

```
I/flutter (13076): result.put("onMove  ",  25522233, 12, new Point<double>(174.0, 531.0}));
I/flutter (13076): result.put("onMove  ",  25522241, 9, new Point<double>(112.0, 690.0}));
I/flutter (13076): result.put("onMove  ",  25522241, 10, new Point<double>(332.0, 467.0}));
I/flutter (13076): result.put("onMove  ",  25522241, 11, new Point<double>(396.0, 539.0}));
I/flutter (13076): result.put("onMove  ",  25522241, 12, new Point<double>(182.0, 533.0}));
I/flutter (13076): result.put("onMove  ",  25522249, 9, new Point<double>(120.0, 691.0}));
I/flutter (13076): result.put("onMove  ",  25522249, 10, new Point<double>(349.0, 471.0}));
I/flutter (13076): result.put("onMove  ",  25522249, 11, new Point<double>(409.0, 542.0}));
I/flutter (13076): result.put("onMove  ",  25522249, 12, new Point<double>(189.0, 535.0}));
I/flutter (13076): result.put("onMove  ",  25522256, 9, new Point<double>(129.0, 692.0}));
I/flutter (13076): result.put("onMove  ",  25522256, 10, new Point<double>(359.0, 473.0}));
I/flutter (13076): result.put("onMove  ",  25522256, 11, new Point<double>(419.0, 543.0}));
I/flutter (13076): result.put("onMove  ",  25522256, 12, new Point<double>(198.0, 535.0}));
I/ViewRootImpl(13076): ViewRoot's Touch Event : ACTION_POINTER_UP(3)
I/flutter (13076): result.put("onMove  ",  25522265, 9, new Point<double>(139.0, 692.0}));
I/flutter (13076): result.put("onMove  ",  25522265, 10, new Point<double>(367.0, 473.0}));
I/flutter (13076): result.put("onMove  ",  25522265, 11, new Point<double>(429.0, 544.0}));
I/flutter (13076): result.put("onUp    ",  25522265, 12, new Point<double>(198.0, 535.0}));
I/flutter (13076): result.put("onMove  ",  25522265, 9, new Point<double>(139.0, 692.0}));
I/flutter (13076): result.put("onMove  ",  25522265, 10, new Point<double>(367.0, 473.0}));
I/flutter (13076): result.put("onMove  ",  25522265, 11, new Point<double>(429.0, 544.0}));
I/ViewRootImpl(13076): ViewRoot's Touch Event : ACTION_POINTER_UP(0)
I/ViewRootImpl(13076): ViewRoot's Touch Event : ACTION_POINTER_UP(0)
W/InputEventReceiver(13076): Attempted to finish an input event that is not in progress.
I/ViewRootImpl(13076): ViewRoot's Touch Event : ACTION_UP
I/flutter (13076): result.put("onMove  ",  25522274, 10, new Point<double>(367.0, 473.0}));
I/flutter (13076): result.put("onMove  ",  25522274, 11, new Point<double>(429.0, 544.0}));
I/flutter (13076): result.put("onUp    ",  25522274, 9, new Point<double>(139.0, 692.0}));
E/flutter (13076): [ERROR:flutter/lib/ui/ui_dart_state.cc(148)] Unhandled Exception: 'package:flutter/src/gestures/converter.dart': Failed assertion: line 280 pos 20: 'state.down': is not true.
E/flutter (13076): #0      _AssertionError._doThrowNew (dart:core-patch/errors_patch.dart:40:39)
E/flutter (13076): #1      _AssertionError._throwNew (dart:core-patch/errors_patch.dart:36:5)
E/flutter (13076): #2      PointerEventConverter.expand (package:flutter/src/gestures/converter.dart:280:20)
E/flutter (13076): #3      _SyncIterator.moveNext (dart:core-patch/core_patch.dart:144:12)
E/flutter (13076): #4      ListQueue.addAll (dart:collection/queue.dart:655:25)
E/flutter (13076): #5      GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:84:27)
E/flutter (13076): #6      _rootRunUnary (dart:async/zone.dart:1136:13)
E/flutter (13076): #7      _CustomZone.runUnary (dart:async/zone.dart:1029:19)
E/flutter (13076): #8      _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
E/flutter (13076): #9      _invoke1 (dart:ui/hooks.dart:263:10)
E/flutter (13076): #10     _dispatchPointerDataPacket (dart:ui/hooks.dart:172:5)
E/flutter (13076): 
I/flutter (13076): result.put("onDown  ",  25522274, 15, new Point<double>(367.0, 473.0}));
E/flutter (13076): [ERROR:flutter/lib/ui/ui_dart_state.cc(148)] Unhandled Exception: 'package:flutter/src/gestures/converter.dart': Failed assertion: line 176 pos 20: '!state.down': is not true.
E/flutter (13076): #0      _AssertionError._doThrowNew (dart:core-patch/errors_patch.dart:40:39)
E/flutter (13076): #1      _AssertionError._throwNew (dart:core-patch/errors_patch.dart:36:5)
E/flutter (13076): #2      PointerEventConverter.expand (package:flutter/src/gestures/converter.dart:176:20)
E/flutter (13076): #3      _SyncIterator.moveNext (dart:core-patch/core_patch.dart:144:12)
E/flutter (13076): #4      ListQueue.addAll (dart:collection/queue.dart:655:25)
E/flutter (13076): #5      GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:84:27)
E/flutter (13076): #6      _rootRunUnary (dart:async/zone.dart:1136:13)
E/flutter (13076): #7      _CustomZone.runUnary (dart:async/zone.dart:1029:19)
E/flutter (13076): #8      _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
E/flutter (13076): #9      _invoke1 (dart:ui/hooks.dart:263:10)
E/flutter (13076): #10     _dispatchPointerDataPacket (dart:ui/hooks.dart:172:5)
E/flutter (13076): 
I/flutter (13076): result.put("onCancel",  25522274, 11, new Point<double>(429.0, 544.0}));

```
I can only notice that the error appears only in **debug** mode, in **release** mode no problems arise.
Below is a piece of code:

```
class _GestureHomePageState extends State<GestureHomePage>
{
  @override
  Widget build(BuildContext context) {

    AppBar _appBar = AppBar(
      title: Text(widget.title),
    );

    double _appBarHight    = _appBar.preferredSize.height;

    return Scaffold(
      appBar:  _appBar,
      body: new Listener(
        onPointerDown: (e) {
          double x = e.position.dx.round().toDouble();
          double y = (e.position.dy - _appBarHight - _statusBarHeight).round().toDouble();
          print(
              'result.put("onDown  ",  ${e.timeStamp.inMilliseconds}, ${e.pointer}, new Point<double>($x, $y}));'
          );
        },
        onPointerMove: (e) {
          double x = e.position.dx.round().toDouble();
          double y = (e.position.dy - _appBarHight - _statusBarHeight).round().toDouble();
          print(
              'result.put("onMove  ",  ${e.timeStamp.inMilliseconds}, ${e.pointer}, new Point<double>($x, $y}));'
          );
        },
        onPointerUp: (e) {
          double x = e.position.dx.round().toDouble();
          double y = (e.position.dy - _appBarHight - _statusBarHeight).round().toDouble();
          print(
              'result.put("onUp    ",  ${e.timeStamp.inMilliseconds}, ${e.pointer}, new Point<double>($x, $y}));'
          );
        },
        onPointerCancel: (e) {
          double x = e.position.dx.round().toDouble();
          double y = (e.position.dy - _appBarHight - _statusBarHeight).round().toDouble();
          print(
              'result.put("onCancel",  ${e.timeStamp.inMilliseconds}, ${e.pointer}, new Point<double>($x, $y}));'
          );
        },
        child: new CustomPaint(
          //painter: new PathPainter.Bundle(hash, taps, longs, _movementType, _downPoints, _lastPoints, _parameter),
          child: new Container(
            decoration: new BoxDecoration(
              color: Colors.white70,
              gradient: new LinearGradient(
                  colors: <Color>[Colors.lightBlue, Colors.white30]),
              border: new Border.all(
                color: Colors.blueGrey,
                width: 1.0,
              ),
            ),
          ),
        ),
      ),
    );
  }
}

```
Flutter doctor:

```
/home/micrcx/flutter/bin/flutter doctor --verbose
[✓] Flutter (Channel stable, v1.9.1+hotfix.6, on Linux, locale en_IL)
    • Flutter version 1.9.1+hotfix.6 at /home/micrcx/flutter
    • Framework revision 68587a0916 (6 weeks ago), 2019-09-13 19:46:58 -0700
    • Engine revision b863200c37
    • Dart version 2.5.0

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /home/micrcx/Android/Sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /home/micrcx/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Android Studio (version 3.5)
    • Android Studio at /home/micrcx/android-studio
    • Flutter plugin version 40.2.2
    • Dart plugin version 191.8580
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] IntelliJ IDEA Community Edition (version 2019.2)
    • IntelliJ at /home/micrcx/idea-IC-191.6707.61
    • Flutter plugin version 40.2.4
    • Dart plugin version 192.7402

[✓] VS Code (version 1.39.2)
    • VS Code at /usr/share/code
    • Flutter extension version 3.5.1

[✓] Connected device (1 available)
    • LG V520 • LGV5203c426e47 • android-arm • Android 7.0 (API 24)

• No issues found!
Process finished with exit code 0

```

**Comment by iapicca** [comment]
Hi @micrcx 
I've tried your code in debug, but I'm not getting your error.
Are you experiencing this on an emulated device or on a physical one?
<details>
  <summary>Code</summary>

```
import 'package:flutter/material.dart';

void main() => runApp(MaterialApp(
  home: MyHomePage(),
));

class MyHomePage extends StatelessWidget {

  Widget build(BuildContext context) => Scaffold(
    body:  Listener(
      onPointerDown: (e) {
        double x = e.position.dx.round().toDouble();
        double y = (e.position.dy).round().toDouble();
        print(
            'result.put("onDown  ",  ${e.timeStamp.inMilliseconds}, ${e.pointer}, new Point<double>($x, $y}));'
        );
      },
      onPointerMove: (e) {
        double x = e.position.dx.round().toDouble();
        double y = (e.position.dy).round().toDouble();
        print(
            'result.put("onMove  ",  ${e.timeStamp.inMilliseconds}, ${e.pointer}, new Point<double>($x, $y}));'
        );
      },
      onPointerUp: (e) {
        double x = e.position.dx.round().toDouble();
        double y = (e.position.dy ).round().toDouble();
        print(
            'result.put("onUp    ",  ${e.timeStamp.inMilliseconds}, ${e.pointer}, new Point<double>($x, $y}));'
        );
      },
      onPointerCancel: (e) {
        double x = e.position.dx.round().toDouble();
        double y = (e.position.dy ).round().toDouble();
        print(
            'result.put("onCancel",  ${e.timeStamp.inMilliseconds}, ${e.pointer}, new Point<double>($x, $y}));'
        );
      },
      child: CustomPaint(
        child: Container(
          decoration: BoxDecoration(
            color: Colors.white70,
            gradient: LinearGradient(colors: [Colors.lightBlue, Colors.white30]),
            border: Border.all(color: Colors.blueGrey, width: 1.0,),
      ),),),),);
}
```

</details>

**Comment by micrcx** [comment]
Physical device: tablet LG V520.

**Comment by micrcx** [comment]
This effect doesn't appear immediately. Try a few sessions, i.e.:
1) Run the app.
2) Use several fingers to perform operation: three or four fingers: perform simultaneously touch down, move and up gestures.
3) Repeat the step 2 several times.
4) At one of the stages you will receive an error.

**Comment by micrcx** [comment]
I've additionally check the application on the LG G5, LG G6, Xiaomi Mi A2 and Galaxy S6 edge, devices. The error doesn't appear.

**Comment by micrcx** [comment]
I've checked the application in the updated version:
```
[✓] Flutter (Channel stable, v1.12.13+hotfix.5, on Linux, locale en_IL)
    • Flutter version 1.12.13+hotfix.5 at /home/micrcx/flutter
    • Framework revision 27321ebbad (4 weeks ago), 2019-12-10 18:15:01 -0800
    • Engine revision 2994f7e1e6
    • Dart version 2.7.0
```
And I couldn't reproduce the error. With a high degree of probability the problem is solved. 
Но если она снова появится, я вам об этом сообщу, не волнуйтесь.
