### ISSUE TITLE
Flutter: SocketException: OS Error: No route to host, errno = 113, address = 192.168.43.33, port = 40991

### ISSUE THREAD

**Issue by Parrotmk** [flutter/flutter#43530]
```
D/SettingsInterface(19480):  from settings cache , name = sound_effects_enabled , value = 0
D/libc-netbsd(19480): [getaddrinfo]: hostname=192.168.43.33; servname=(null); netid=0; mark=0
D/libc-netbsd(19480): [getaddrinfo]: ai_addrlen=0; ai_canonname=(null); ai_flags=1024; ai_family=0
E/flutter (19480): [ERROR:flutter/lib/ui/ui_dart_state.cc(148)] Unhandled Exception: **SocketException: OS Error: No route to host, errno = 113, address = 192.168.43.33, port = 40991**
E/flutter (19480): #0      IOClient.send (package:http/src/io_client.dart:33:23)
E/flutter (19480): <asynchronous suspension>
E/flutter (19480): #1      BaseClient._sendUnstreamed (package:http/src/base_client.dart:169:38)
E/flutter (19480): <asynchronous suspension>
E/flutter (19480): #2      BaseClient.post (package:http/src/base_client.dart:54:7)
E/flutter (19480): #3      post.<anonymous closure> (package:http/http.dart:70:16)
E/flutter (19480): #4      _withClient (package:http/http.dart:166:20)
E/flutter (19480): <asynchronous suspension>
E/flutter (19480): #5      post (package:http/http.dart:69:5)
E/flutter (19480): #6      UsersUtils.updateUser (package:domesticjobs/utils/users_utils.dart:244:28)
E/flutter (19480): <asynchronous suspension>
E/flutter (19480): #7      EditProfileState._save (package:domesticjobs/pages/edit_profile_page.dart:37:20)
E/flutter (19480): #8     EditProfileState.build.<anonymous closure> (package:domesticjobs/pages/edit_profile_page.dart:113:25)
E/flutter (19480): #9      _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:654:14)
E/flutter (19480): #10     _InkResponseState.build.<anonymous closure> (package:flutter/src/material/ink_well.dart:729:32)
E/flutter (19480): #11     GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:182:24)
E/flutter (19480): #12     TapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:365:11)
E/flutter (19480): #13     TapGestureRecognizer.handlePrimaryPointer (package:flutter/src/gestures/tap.dart:275:7)
E/flutter (19480): #14     PrimaryPointerGestureRecognizer.handleEvent (package:flutter/src/gestures/recognizer.dart:455:9)
E/flutter (19480): #15     PointerRouter._dispatch (package:flutter/src/gestures/pointer_router.dart:75:13)
E/flutter (19480): #16     PointerRouter.route (package:flutter/src/gestures/pointer_router.dart:102:11)
E/flutter (19480): #17     GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:218:19)
E/flutter (19480): #18     GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:198:22)
E/flutter (19480): #19     GestureBinding._handlePointerEvent (package:flutter/src/gestures/binding.dart:156:7)
E/flutter (19480): #20     GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:102:7)
E/flutter (19480): #21     GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:86:7)
E/flutter (19480): #22     _rootRunUnary (dart:async/zone.dart:1136:13)
E/flutter (19480): #23     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
E/flutter (19480): #24     _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
E/flutter (19480): #25     _invoke1 (dart:ui/hooks.dart:263:10)
E/flutter (19480): #26     _dispatchPointerDataPacket (dart:ui/hooks.dart:172:5)
E/flutter (19480): 
```

I got "192.168.43.33" address when I executed this command on MACOS : ifconfig.
API is on my localhost and I can access it using this URL
http://192.168.43.33/users/edit_profile

Doctor command for flutters fine.
I am connection with wifi of my real device and I am testing it on same real device (Android).

Please help

**Comment by BondarenkoStas** [comment]
@Parrotmk can you access the url from your phone browser?

**Comment by awafL** [comment]
I would suggest to add the extension of the file to the url. For example, if that is a .php file, change it like this: http://192.168.43.33/users/edit_profile.php <-.

**Comment by awafL** [comment]
Could you the code that you are using so we could troubleshoot?

**Comment by VladyslavBondarenko** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution
