### ISSUE TITLE
ReorderableListView fails inside PageView with controller.viewportFraction < 1.0

### ISSUE THREAD

**Issue by maksi** [flutter/flutter#43540]
## Steps to Reproduce

1. Put **ReordableListView** inside **PageView** where **controller: PageController( viewportFraction: 0.8 )**
2. Start up the screen and try to drag any of the list items.
3. Fails with 

```
ScrollController attached to multiple scroll views. 'package:flutter/src/widgets/scroll_controller.dart': Failed assertion: line 111 pos 12: '_positions.length == 1'
```

4. Changing viewportFraction to 1.0 or removing it fixes the issue.

**Target Platform:** iOS
**Target OS version/browser:** iOS 13.1
**Devices:** iPhone 8 Simulator
 (but it seems it affects any platform/OS/device)

## Logs

```
[+1900 ms] [DEVICE LOG] 2019-10-25 14:50:06.714898-0700  localhost Runner[71299]: (Flutter) flutter: ══╡ EXCEPTION CAUGHT BY GESTURE
╞═══════════════════════════════════════════════════════════════════
[   +1 ms] [DEVICE LOG] 2019-10-25 14:50:06.715041-0700  localhost Runner[71299]: (Flutter) flutter: The following assertion was thrown while handling a gesture:
[        ] [DEVICE LOG] 2019-10-25 14:50:06.715155-0700  localhost Runner[71299]: (Flutter) flutter: ScrollController attached to multiple scroll views.
[        ] [DEVICE LOG] 2019-10-25 14:50:06.715264-0700  localhost Runner[71299]: (Flutter) flutter: 'package:flutter/src/widgets/scroll_controller.dart':
[        ] flutter: ══╡ EXCEPTION CAUGHT BY GESTURE ╞═══════════════════════════════════════════════════════════════════
[        ] flutter: The following assertion was thrown while handling a gesture:
[        ] flutter: ScrollController attached to multiple scroll views.
[        ] flutter: 'package:flutter/src/widgets/scroll_controller.dart':
[        ] [DEVICE LOG] 2019-10-25 14:50:06.715615-0700  localhost Runner[71299]: (Flutter) flutter: Failed assertion: line 111 pos 12: '_positions.length == 1'
[        ] [DEVICE LOG] 2019-10-25 14:50:06.716184-0700  localhost Runner[71299]: (Flutter) flutter:
[        ] [DEVICE LOG] 2019-10-25 14:50:06.716354-0700  localhost Runner[71299]: (Flutter) flutter: Either the assertion indicates an error in the framework itself, or we should provide
substantially
[        ] [DEVICE LOG] 2019-10-25 14:50:06.717015-0700  localhost Runner[71299]: (Flutter) flutter: more information in this error message to help you determine and fix the underlying cause.
[        ] [DEVICE LOG] 2019-10-25 14:50:06.717126-0700  localhost Runner[71299]: (Flutter) flutter: In either case, please report this assertion by filing a bug on GitHub:
[        ] [DEVICE LOG] 2019-10-25 14:50:06.717247-0700  localhost Runner[71299]: (Flutter) flutter:   https://github.com/flutter/flutter/issues/new?template=BUG.md
[        ] [DEVICE LOG] 2019-10-25 14:50:06.717485-0700  localhost Runner[71299]: (Flutter) flutter:
[        ] [DEVICE LOG] 2019-10-25 14:50:06.718018-0700  localhost Runner[71299]: (Flutter) flutter: When the exception was thrown, this was the stack:
[        ] [DEVICE LOG] 2019-10-25 14:50:06.718291-0700  localhost Runner[71299]: (Flutter) flutter: #2      ScrollController.position (package:flutter/src/widgets/scroll_controller.dart:111:12)
[        ] [DEVICE LOG] 2019-10-25 14:50:06.718380-0700  localhost Runner[71299]: (Flutter) flutter: #3      ScrollController.offset (package:flutter/src/widgets/scroll_controller.dart:118:24)
[   +1 ms] flutter: Failed assertion: line 111 pos 12: '_positions.length == 1'
[        ] flutter:
[        ] flutter: Either the assertion indicates an error in the framework itself, or we should provide substantially
[        ] flutter: more information in this error message to help you determine and fix the underlying cause.
[        ] flutter: In either case, please report this assertion by filing a bug on GitHub:
[        ] flutter:   https://github.com/flutter/flutter/issues/new?template=BUG.md
[        ] flutter:
[        ] flutter: When the exception was thrown, this was the stack:
[        ] flutter: #2      ScrollController.position (package:flutter/src/widgets/scroll_controller.dart:111:12)
[        ] flutter: #3      ScrollController.offset (package:flutter/src/widgets/scroll_controller.dart:118:24)
[   +5 ms] [DEVICE LOG] 2019-10-25 14:50:06.718666-0700  localhost Runner[71299]: (Flutter) flutter: #4      _ReorderableListContentState._scrollTo
(package:flutter/src/material/reorderable_list.dart:305:51)
[        ] [DEVICE LOG] 2019-10-25 14:50:06.718973-0700  localhost Runner[71299]: (Flutter) flutter: #5      _ReorderableListContentState._wrap.<anonymous closure>.<anonymous closure>
(package:flutter/src/material/reorderable_list.dart:526:11)
[        ] [DEVICE LOG] 2019-10-25 14:50:06.719271-0700  localhost Runner[71299]: (Flutter) flutter: #6      _DragTargetState.didEnter (package:flutter/src/widgets/drag_target.dart)
[        ] [DEVICE LOG] 2019-10-25 14:50:06.719518-0700  localhost Runner[71299]: (Flutter) flutter: #7      _DragAvatar.updateDrag.<anonymous closure>
(package:flutter/src/widgets/drag_target.dart:658:23)
[        ] [DEVICE LOG] 2019-10-25 14:50:06.719737-0700  localhost Runner[71299]: (Flutter) flutter: #8      ListMixin.firstWhere (dart:collection/list.dart:138:15)
[   +1 ms] [DEVICE LOG] 2019-10-25 14:50:06.719969-0700  localhost Runner[71299]: (Flutter) flutter: #9      _DragAvatar.updateDrag (package:flutter/src/widgets/drag_target.dart:655:51)
[        ] [DEVICE LOG] 2019-10-25 14:50:06.720051-0700  localhost Runner[71299]: (Flutter) flutter: #10     new _DragAvatar (package:flutter/src/widgets/drag_target.dart:591:5)
[        ] [DEVICE LOG] 2019-10-25 14:50:06.720227-0700  localhost Runner[71299]: (Flutter) flutter: #11     _DraggableState._startDrag (package:flutter/src/widgets/drag_target.dart:381:35)
[        ] [DEVICE LOG] 2019-10-25 14:50:06.720376-0700  localhost Runner[71299]: (Flutter) flutter: #12     LongPressDraggable.createRecognizer.<anonymous closure>
(package:flutter/src/widgets/drag_target.dart:319:36)
[        ] [DEVICE LOG] 2019-10-25 14:50:06.720506-0700  localhost Runner[71299]: (Flutter) flutter: #13     MultiDragGestureRecognizer._startDrag.<anonymous closure>
(package:flutter/src/gestures/multidrag.dart:266:52)
[  +20 ms] [DEVICE LOG] 2019-10-25 14:50:06.720674-0700  localhost Runner[71299]: (Flutter) flutter: #14     GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:182:24)
[        ] [DEVICE LOG] 2019-10-25 14:50:06.720764-0700  localhost Runner[71299]: (Flutter) flutter: #15     MultiDragGestureRecognizer._startDrag
(package:flutter/src/gestures/multidrag.dart:266:14)
[        ] [DEVICE LOG] 2019-10-25 14:50:06.720871-0700  localhost Runner[71299]: (Flutter) flutter: #16     MultiDragGestureRecognizer.acceptGesture.<anonymous closure>
(package:flutter/src/gestures/multidrag.dart:256:48)
[        ] [DEVICE LOG] 2019-10-25 14:50:06.720987-0700  localhost Runner[71299]: (Flutter) flutter: #17     _DelayedPointerState.accepted (package:flutter/src/gestures/multidrag.dart:485:14)
[        ] [DEVICE LOG] 2019-10-25 14:50:06.721491-0700  localhost Runner[71299]: (Flutter) flutter: #18     MultiDragGestureRecognizer.acceptGesture
(package:flutter/src/gestures/multidrag.dart:256:11)
[   +4 ms] [DEVICE LOG] 2019-10-25 14:50:06.721820-0700  localhost Runner[71299]: (Flutter) flutter: #19     GestureArenaManager._resolveInFavorOf (package:flutter/src/gestures/arena.dart:263:12)
[        ] [DEVICE LOG] 2019-10-25 14:50:06.721933-0700  localhost Runner[71299]: (Flutter) flutter: #20     GestureArenaManager._resolve (package:flutter/src/gestures/arena.dart:222:9)
[        ] [DEVICE LOG] 2019-10-25 14:50:06.722089-0700  localhost Runner[71299]: (Flutter) flutter: #21     GestureArenaEntry.resolve (package:flutter/src/gestures/arena.dart:52:12)
[        ] [DEVICE LOG] 2019-10-25 14:50:06.722195-0700  localhost Runner[71299]: (Flutter) flutter: #22     MultiDragPointerState.resolve (package:flutter/src/gestures/multidrag.dart:62:17)
[        ] [DEVICE LOG] 2019-10-25 14:50:06.722298-0700  localhost Runner[71299]: (Flutter) flutter: #23     _DelayedPointerState._delayPassed (package:flutter/src/gestures/multidrag.dart:471:7)
[        ] [DEVICE LOG] 2019-10-25 14:50:06.722776-0700  localhost Runner[71299]: (Flutter) flutter: #32     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:382:19)
[   +3 ms] [DEVICE LOG] 2019-10-25 14:50:06.723105-0700  localhost Runner[71299]: (Flutter) flutter: #33     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:416:5)
[        ] [DEVICE LOG] 2019-10-25 14:50:06.723346-0700  localhost Runner[71299]: (Flutter) flutter: #34     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:12)
[        ] [DEVICE LOG] 2019-10-25 14:50:06.723515-0700  localhost Runner[71299]: (Flutter) flutter: (elided 10 frames from class _AssertionError, package dart:async, and package dart:async-patch)
[        ] [DEVICE LOG] 2019-10-25 14:50:06.723809-0700  localhost Runner[71299]: (Flutter) flutter:
[        ] [DEVICE LOG] 2019-10-25 14:50:06.723974-0700  localhost Runner[71299]: (Flutter) flutter: Handler: "onStart"
[        ] [DEVICE LOG] 2019-10-25 14:50:06.724126-0700  localhost Runner[71299]: (Flutter) flutter: Recognizer:
[        ] [DEVICE LOG] 2019-10-25 14:50:06.724210-0700  localhost Runner[71299]: (Flutter) flutter:   DelayedMultiDragGestureRecognizer#16cd5
[   +5 ms] [DEVICE LOG] 2019-10-25 14:50:06.724285-0700  localhost Runner[71299]: (Flutter) flutter:
════════════════════════════════════════════════════════════════════════════════════════════════════
[        ] flutter: #4      _ReorderableListContentState._scrollTo (package:flutter/src/material/reorderable_list.dart:305:51)
[        ] flutter: #5      _ReorderableListContentState._wrap.<anonymous closure>.<anonymous closure> (package:flutter/src/material/reorderable_list.dart:526:11)
[        ] flutter: #6      _DragTargetState.didEnter (package:flutter/src/widgets/drag_target.dart)
[        ] flutter: #7      _DragAvatar.updateDrag.<anonymous closure> (package:flutter/src/widgets/drag_target.dart:658:23)
[        ] flutter: #8      ListMixin.firstWhere (dart:collection/list.dart:138:15)
[        ] flutter: #9      _DragAvatar.updateDrag (package:flutter/src/widgets/drag_target.dart:655:51)
[        ] flutter: #10     new _DragAvatar (package:flutter/src/widgets/drag_target.dart:591:5)
[        ] flutter: #11     _DraggableState._startDrag (package:flutter/src/widgets/drag_target.dart:381:35)
[        ] flutter: #12     LongPressDraggable.createRecognizer.<anonymous closure> (package:flutter/src/widgets/drag_target.dart:319:36)
[        ] flutter: #13     MultiDragGestureRecognizer._startDrag.<anonymous closure> (package:flutter/src/gestures/multidrag.dart:266:52)
[        ] flutter: #14     GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:182:24)
[        ] flutter: #15     MultiDragGestureRecognizer._startDrag (package:flutter/src/gestures/multidrag.dart:266:14)
[   +4 ms] flutter: #16     MultiDragGestureRecognizer.acceptGesture.<anonymous closure> (package:flutter/src/gestures/multidrag.dart:256:48)
[        ] flutter: #17     _DelayedPointerState.accepted (package:flutter/src/gestures/multidrag.dart:485:14)
[        ] flutter: #18     MultiDragGestureRecognizer.acceptGesture (package:flutter/src/gestures/multidrag.dart:256:11)
[        ] flutter: #19     GestureArenaManager._resolveInFavorOf (package:flutter/src/gestures/arena.dart:263:12)
[        ] flutter: #20     GestureArenaManager._resolve (package:flutter/src/gestures/arena.dart:222:9)
[        ] flutter: #21     GestureArenaEntry.resolve (package:flutter/src/gestures/arena.dart:52:12)
[        ] flutter: #22     MultiDragPointerState.resolve (package:flutter/src/gestures/multidrag.dart:62:17)
[        ] flutter: #23     _DelayedPointerState._delayPassed (package:flutter/src/gestures/multidrag.dart:471:7)
[  +14 ms] flutter: #32     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:382:19)
[        ] flutter: #33     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:416:5)
[        ] flutter: #34     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:12)
[        ] flutter: (elided 10 frames from class _AssertionError, package dart:async, and package dart:async-patch)
[        ] flutter:
[        ] flutter: Handler: "onStart"
[        ] flutter: Recognizer:
[        ] flutter:   DelayedMultiDragGestureRecognizer#16cd5
[     
```
```
[✓] Flutter (Channel stable, v1.9.1+hotfix.6, on Mac OS X 10.15 19A602, locale en-UA)
    • Flutter version 1.9.1+hotfix.6 at /Users/mi/Soft/flutter
    • Framework revision 68587a0916 (6 weeks ago), 2019-09-13 19:46:58 -0700
    • Engine revision b863200c37
    • Dart version 2.5.0

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/mi/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.1, Build version 11A1027
    • CocoaPods version 1.8.3

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 39.0.3
    • Dart plugin version 191.8423
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] IntelliJ IDEA Ultimate Edition (version 2019.2.3)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 40.1.4
    • Dart plugin version 192.6817.14

[✓] VS Code (version 1.38.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.4.1

• No issues found!
```

**Comment by TahaTesser** [comment]
Hi @maksi 

Here i tried to reproduce the issue for  `ReorderableListView` insidePageView with controller.viewportFraction < 1.0. It seems to work fine

<details>
 <summary>Summary Goes Here</summary>

```
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      debugShowCheckedModeBanner: false,
      home: Scaffold(
        body: Padding(
          padding: const EdgeInsets.symmetric(vertical: 50, horizontal: 20),
          child: PageViewDemo(),
        ),
      ),
    );
  }
}

class PageViewDemo extends StatefulWidget {
  @override
  _PageViewDemoState createState() => _PageViewDemoState();
}

class _PageViewDemoState extends State<PageViewDemo> {
  PageController _controller =
      PageController(initialPage: 0, viewportFraction: 0.8);

  @override
  void dispose() {
    _controller.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return PageView(
      controller: _controller,
      children: [MyPage1Widget()],
    );
  }
}

class MyPage1Widget extends StatefulWidget {
  @override
  _MyPage1WidgetState createState() => _MyPage1WidgetState();
}

class _MyPage1WidgetState extends State<MyPage1Widget> {
  List<String> _list = List.generate(5, (i) => "${i}");

  @override
  Widget build(BuildContext context) {
    return ReorderableListView(
      padding: EdgeInsets.symmetric(horizontal: 40),
      children: _list
          .map((String string) => ListTile(
              key: Key(_list[_list.indexOf(string)]), title: Text(string)))
          .toList(),
      onReorder: (oldIndex, newIndex) {
        String old = _list[oldIndex];
        if (oldIndex > newIndex) {
          for (int i = oldIndex; i > newIndex; i--) {
            _list[i] = _list[i - 1];
          }
          _list[newIndex] = old;
        } else {
          for (int i = oldIndex; i < newIndex - 1; i++) {
            _list[i] = _list[i + 1];
          }
          _list[newIndex - 1] = old;
        }
        setState(() {});
      },
    );
  }
}

```

</details>


<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel dev, v1.18.0-dev.5.0, on Mac OS X 10.15.4 19E287, locale
    en-GB)
    • Flutter version 1.18.0-dev.5.0 at /Users/taha/Code/flutter_dev
    • Framework revision 7f56b53de4 (8 days ago), 2020-04-12 12:00:01 -0400
    • Engine revision beb8a7ec48
    • Dart version 2.8.0 (build 2.8.0-dev.20.0 89b0f67261)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/taha/Code/sdk
    • Platform android-29, build-tools 29.0.3
    • ANDROID_HOME = /Users/taha/Code/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.
[✓] Xcode - develop for iOS and macOS (Xcode 11.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.4.1, Build version 11E503a
    • CocoaPods version 1.9.1
[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome
[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build
      1.8.0_212-release-1586-b4-5784211)
[✓] VS Code (version 1.44.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.9.1
[✓] Connected device (4 available)
    • iPhone 11  • 41EB2A85-7EB4-4FD2-8978-FBBE2A681D74 • ios            •
      com.apple.CoreSimulator.SimRuntime.iOS-13-4 (simulator)
    • macOS      • macOS                                • darwin-x64     • Mac
      OS X 10.15.4 19E287
    • Chrome     • chrome                               • web-javascript •
      Google Chrome 81.0.4044.113
    • Web Server • web-server                           • web-javascript •
      Flutter Tools
• No issues found!
```

</details>

f you're still experiencing this problem, please create a new issue and provide the information
required in the template.
Thank you
