### ISSUE TITLE
[image_picker] Camera Error Can't connect to the camera

### ISSUE THREAD

**Issue by awhitford** [flutter/flutter#43552]
Using Android Emulator, calling the `ImagePicker.pickImage` results in an error pop up saying:

> Camera Error
> 
> Can't connect to the camera.
>
> Report | Dismiss

Clicking _Dismiss_ returns _null_ from `pickImage`.

This was working, and I think I did something, but now I am at a loss as to what is wrong and how to fix it.

From AVD Manager, the Virtual Device has _Front Camera_ set to _Emulator_.

I noticed the following in the device logs that is likely related:
```
10-25 16:25:57.236  1425  1549 E EmulatedCamera_FakeCamera3: doFakeAF: Front camera doesn't support AF mode 4
10-25 16:25:57.236  1425  1549 E CamDevSession@3.2-impl: processOneCaptureRequest: HAL process_capture_request call failed!
10-25 16:25:57.236  1524  6029 E Camera3-Device: Camera 1: sendRequestsBatch: RequestThread: Unable to submit capture request 5 to HAL device: Function not implemented (-38)
10-25 16:25:57.233     0     0 D ieee80211 phy0: hw scan 2462 MHz
10-25 16:25:57.236  4075  6023 E CAM_FatalErrorHandler: Handling Camera Access Failure:
10-25 16:25:57.236  4075  6023 E CAM_FatalErrorHandler: java.lang.Exception
10-25 16:25:57.236  4075  6023 E CAM_FatalErrorHandler: 	at com.android.camera.FatalErrorHandlerImpl.onGenericCameraAccessFailure(FatalErrorHandlerImpl.java:84)
10-25 16:25:57.236  4075  6023 E CAM_FatalErrorHandler: 	at com.android.camera.one.v2.Camera2OneCameraOpenerImpl$1.onError(Camera2OneCameraOpenerImpl.java:154)
10-25 16:25:57.236  4075  6023 E CAM_FatalErrorHandler: 	at android.hardware.camera2.impl.CameraDeviceImpl$CameraDeviceCallbacks$1.run(CameraDeviceImpl.java:1756)
10-25 16:25:57.236  4075  6023 E CAM_FatalErrorHandler: 	at android.os.Handler.handleCallback(Handler.java:790)
10-25 16:25:57.236  4075  6023 E CAM_FatalErrorHandler: 	at android.os.Handler.dispatchMessage(Handler.java:99)
10-25 16:25:57.236  4075  6023 E CAM_FatalErrorHandler: 	at android.os.Looper.loop(Looper.java:164)
10-25 16:25:57.236  4075  6023 E CAM_FatalErrorHandler: 	at android.os.HandlerThread.run(HandlerThread.java:65)
10-25 16:25:57.236  4075  6023 E CAM_CameraUtil: Show fatal error dialog
```

I am using Flutter 1.9.1+hotfix.6 and Dart 2.5.0 on MacOS 10.15.

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, v1.9.1+hotfix.6, on Mac OS X 10.15 19A602, locale en-US)
[!] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    ✗ Android license status unknown.
      Try re-installing or updating your Android SDK Manager.
      See https://developer.android.com/studio/#downloads or visit https://flutter.dev/setup/#android-setup for detailed instructions.
[✓] Xcode - develop for iOS and macOS (Xcode 11.1)
[✓] Android Studio (version 3.5)
[✓] VS Code (version 1.39.2)
[✓] Connected device (1 available)

! Doctor found issues in 1 category.
```

**Comment by BondarenkoStas** [comment]
@awhitford can you try maybe that's the cause https://stackoverflow.com/a/11857261/12268368? If both front and back are set to the same.

**Comment by awhitford** [comment]
Front camera is set to _Emulated_, and back camera is set to _Virtual Scene_ (and disabled).

I think I accidentally hit the button to swap cameras from front to back (or vice versa), and now I am stuck with the `Can't connect to the camera` error.

**Comment by awhitford** [comment]
I was finally able to restore the camera by using the **Wipe Data** feature from the AVD (Android Virtual Device) tool.  It is like a factory reset.

**Comment by BondarenkoStas** [comment]
Good to know, so does it work as expected now?`

**Comment by awhitford** [comment]
The image picker is working as expected; it is just that I am concerned that it is too easy to lose the camera access and then you're stuck.  I can only hope that this is a simulator only problem, and not something that happens with an actual device.
