### ISSUE TITLE
flutter doctor -v not running

### ISSUE THREAD

**Issue by rifleman89** [flutter/flutter#43571]
I cannot get my flutter and dart to work in VS code. I attempted creating a new project after installing dart, flutter and VS code. All versions are up to date. The progress bar keeps moving but its not able to complete the task and this goes on for hours till i close the VS code. I aslo noticed that flutter doctor does not work aswell.
Please find attached image below;
![image](https://user-images.githubusercontent.com/50912334/67624249-1f5ac980-f826-11e9-84d1-370012ccf496.png)

**Comment by rifleman89** [comment]
![Capture526](https://user-images.githubusercontent.com/50912334/67624276-782a6200-f826-11e9-8255-e18c53494d8b.PNG)

**Comment by DanTup** [comment]
@rifleman89 to clarify - does this happen only from VS Code, or also if you run manually from the terminal?

**Comment by rifleman89** [comment]
both in teThis occurs both in terminal and VS Code. It attempts to create a new project but never seems to create it.

**Comment by rifleman89** [comment]
find attached
![CapturenNEW](https://user-images.githubusercontent.com/50912334/67674459-6d7de300-f974-11e9-83e9-6378e3e4fa15.PNG)
 image;

**Comment by DanTup** [comment]
Thanks! How did you install Flutter - from Git, or the zip file? What location did you install it to? Are you using the same user to run it as you installed it as?

**Comment by rifleman89** [comment]
Thanks for your response. _I first downloaded dart, I then installed Flutter from the the zip file on https://dart.dev/get-dart . I then saved it in my C drive before unziping it in there. both Dart and Flutter folders are on my C drive.

**Comment by DanTup** [comment]
@rifleman89 where about on your C drive? Some folders (like Program Files) are protected in Windows, which could cause permissions errors.

For what it's worth, you don't need to download/install Dart if you're only doing Flutter, as the Flutter SDK includes its own version of the Dart SDK.

**Comment by rifleman89** [comment]
@DanTup I have it installed on the main C drive, as I am aware of the permission issues with program files folder.
as per the screenshot attached, I seem to be missing all the detailed libraries on the left that I have circled in red. I believe this is not happening because its failing to load.
![Capturewertyuiopoiuhyg](https://user-images.githubusercontent.com/50912334/67683181-d5d6bf80-f988-11e9-92e5-deff44fd1e48.PNG)

**Comment by BondarenkoStas** [comment]
@rifleman89 sorry, I don't know

**Comment by yannduran** [comment]
I just installed Flutter to Windows 10 Pro v1809 (build 17763.864) by unzipping to _c:\dev\flutter_, and and adding _c:\dev\flutter\bin_ to my user's path variables as described in the section on installing to Windows.. 

Flutter doctor, as suggested in the docs, shows this error:

events.js:167
      throw er; // Unhandled 'error' event
      ^
Error: spawn C:\Users\Yann\AppData\Roaming\npm\node_modules\flutter-cli\bin/../flutter/bin/flutter ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:229:19)
    at onErrorNT (internal/child_process.js:406:16)
    at process._tickCallback (internal/process/next_tick.js:63:19)
    at Function.Module.runMain (internal/modules/cjs/loader.js:745:11)
    at startup (internal/bootstrap/node.js:266:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:596:3)
Emitted 'error' event at:
    at Process.ChildProcess._handle.onexit (internal/child_process.js:235:12)
    at onErrorNT (internal/child_process.js:406:16)
    [... lines matching original stack trace ...]
    at bootstrapNodeJSCore (internal/bootstrap/node.js:596:3)

I also tried executing in an elevated command prompt, same error.

I read somewhere to try:

`flutter.bat update-packages`

All of the `flutter pub get`'s ran successfully, but `flutter doctor` still shows the same error.

Last time I wanted to try out Flutter I had problems then too and gave up. Seems like things haven't improved since. Very disappointing!

**Comment by DanTup** [comment]
@yannduran I don't think that's related to this issue, but you appear to have an NPM package named [flutter-cli](https://www.npmjs.com/package/flutter-cli) installed which is on your `PATH`. The VS Code extension is finding the executable from this package and thinks it is the real Flutter, so it's looking for other SDK files relative to its location.

You could fix this by setting `dart.flutterSdkPath` in your VS Code settings, or removing the Flutter-CLI npm package and just adding Flutter to your `PATH` directly. I'd recommend the second - having someone elses binary named `flutter` in your `PATH` doesn't seem like a good idea.

**Comment by DanTup** [comment]
@rifleman89 are you still having this issue? Could you try the steps in https://github.com/flutter/flutter/issues/43571#issuecomment-548016724? Thanks!

**Comment by yannduran** [comment]
@DanTup thanks for your help!

Removing the `flutter-cli` package seems to have worked. Running `flutter doctor` no longer produces an error.

Happy holidays!

**Comment by dnfield** [comment]
I'm closing this since it's had no activity for > 21 days and has the waiting label.  I believe the bot is just backlogged and missing a bunch of these.  Please feel free to add more details if you want this re-opened.
