### ISSUE TITLE
flutter_webview can not show keyboard on Android 10

### ISSUE THREAD

**Issue by GitTradWang** [flutter/flutter#43614]
**downLoad  example  and run code on Android 10 on text filed in web view can not pop keyBoard**
```
[✓] Flutter (Channel stable, v1.9.1+hotfix.6, on Mac OS X 10.14.6 18G103, locale zh-Hans-CN)
    • Flutter version 1.9.1+hotfix.6 at /Users/tradwang/Library/Flutter/sdk
    • Framework revision 68587a0916 (6 weeks ago), 2019-09-13 19:46:58 -0700
    • Engine revision b863200c37
    • Dart version 2.5.0

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.0)
    • Android SDK at /Users/tradwang/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.0
    • ANDROID_HOME = /Users/tradwang/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.1, Build version 11A1027
    • CocoaPods version 1.7.2

[!] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] IntelliJ IDEA Community Edition (version 2019.2.3)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 40.2.4
    • Dart plugin version 192.7402

[✓] VS Code (version 1.39.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.5.1

[✓] Connected device (1 available)
    • ONEPLUS A6000 • d2466909 • android-arm64 • Android 10 (API 29)

! Doctor found issues in 1 category.
```

**Comment by BondarenkoStas** [comment]
@GitTradWang Did you mean webview_flutter plugin? https://github.com/luanpotter/flutter_webview is not supported.

are there any errors when you run it with --verbose flag?

**Comment by GitTradWang** [comment]
> @GitTradWang Did you mean webview_flutter plugin? https://github.com/luanpotter/flutter_webview is not supported.
> 
> are there any errors when you run it with --verbose flag?

yes

**Comment by GitTradWang** [comment]
**some error occurred when touch text filed**

2019-10-29 09:10:42.097 11192-11192/io.flutter.plugins.webviewflutterexample W/InputMethodManager: b/117267690: Display ID mismatch found. ViewRootImpl displayId=36 InputMethodManager displayId=35. Use the right InputMethodManager instance to avoid performance overhead.
    java.lang.Throwable
        at android.view.inputmethod.InputMethodManager.getFallbackInputMethodManagerIfNecessary(InputMethodManager.java:550)
        at android.view.inputmethod.InputMethodManager.isActive(InputMethodManager.java:1191)
        at LM.a(PG:2)
        at org.chromium.content.browser.input.ImeAdapterImpl.n(PG:230)
        at org.chromium.content.browser.input.ImeAdapterImpl.updateState(PG:186)
        at android.os.MessageQueue.nativePollOnce(Native Method)
        at android.os.MessageQueue.next(MessageQueue.java:336)
        at android.os.Looper.loop(Looper.java:174)
        at android.app.ActivityThread.main(ActivityThread.java:7682)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:516)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)
2019-10-29 09:10:43.225 11192-11192/io.flutter.plugins.webviewflutterexample W/cr_AwAutofillManager: WebView autofill is disabled because WebView isn't created with activity context.

**Comment by liuguoping981** [comment]
duplicated? https://github.com/flutter/flutter/issues/43000

**Comment by GitTradWang** [comment]
i think this is the same issue #38375 ,so i will close it soon

**Comment by GitTradWang** [comment]
> duplicated? #43000

thanks for your remind ,i think this is the same problem ,so i colsed it

**Comment by BondarenkoStas** [comment]
Good to know, to ensure please try it on master channel.
