### ISSUE TITLE
Flutter web doesn't work with the `builders:` pubspec.yaml option

### ISSUE THREAD

**Issue by jakemac53** [flutter/flutter#43639]
Root cause has already been diagnosed, see https://github.com/dart-lang/build/issues/2516.

Filing here for tracking purposes, feel free to close if you want to.

## Steps to Reproduce

1. Enable web config `flutter config --enable-web`
2. Add a builders key to your pubspec.yaml, for example:

```yaml
builders:
  json_serializable: any
```

3. Run with the chrome device `flutter run -d chrome`.

## Logs

```
[  +17 ms] executing: [/usr/local/google/home/jakemac/flutter/] git -c log.showSignature=false log -n 1
--pretty=format:%H
[  +31 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[        ] dd39f5f76438b8a9be35b6b12b4fa7baf93c6fd6
[        ] executing: [/usr/local/google/home/jakemac/flutter/] git describe --match v*.*.*
--first-parent --long --tags
[  +25 ms] Exit code 0 from: git describe --match v*.*.* --first-parent --long --tags
[        ] v1.10.14-273-gdd39f5f76
[   +8 ms] executing: [/usr/local/google/home/jakemac/flutter/] git rev-parse --abbrev-ref --symbolic
@{u}
[   +8 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] jonah/web_compiler
[        ] executing: [/usr/local/google/home/jakemac/flutter/] git ls-remote --get-url jonah
[   +4 ms] Exit code 0 from: git ls-remote --get-url jonah
[        ] https://github.com/jonahwilliams/flutter.git
[  +10 ms] executing: [/usr/local/google/home/jakemac/flutter/] git rev-parse --abbrev-ref HEAD
[   +5 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] jonah-hot-reload
[  +71 ms] executing: /usr/local/google/home/jakemac/android-sdk/platform-tools/adb devices -l
[   +7 ms] Exit code 0 from: /usr/local/google/home/jakemac/android-sdk/platform-tools/adb devices -l
[        ] List of devices attached
[  +21 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[  +31 ms] Found plugin connectivity at
/usr/local/google/home/jakemac/.pub-cache/hosted/pub.dartlang.org/connectivity-0.4.5+1/
[   +6 ms] Found plugin device_info at
/usr/local/google/home/jakemac/.pub-cache/hosted/pub.dartlang.org/device_info-0.4.1/
[  +44 ms] Found plugin url_launcher at
/usr/local/google/home/jakemac/.pub-cache/hosted/pub.dartlang.org/url_launcher-5.2.3/
[   +1 ms] Found plugin video_player at
/usr/local/google/home/jakemac/.pub-cache/hosted/pub.dartlang.org/video_player-0.10.2+5/
[  +29 ms] Found plugin connectivity at
/usr/local/google/home/jakemac/.pub-cache/hosted/pub.dartlang.org/connectivity-0.4.5+1/
[   +2 ms] Found plugin device_info at
/usr/local/google/home/jakemac/.pub-cache/hosted/pub.dartlang.org/device_info-0.4.1/
[  +27 ms] Found plugin url_launcher at
/usr/local/google/home/jakemac/.pub-cache/hosted/pub.dartlang.org/url_launcher-5.2.3/
[        ] Found plugin video_player at
/usr/local/google/home/jakemac/.pub-cache/hosted/pub.dartlang.org/video_player-0.10.2+5/
[  +31 ms] Generating
/usr/local/google/home/jakemac/flutter/examples/flutter_gallery/android/app/src/main/java/io/flutter/plug
ins/GeneratedPluginRegistrant.java
[ +113 ms] starting build daemon...
[ +158 ms] Starting daemon...
[ +137 ms] Initializing inputs
[   +8 ms] Reading cached asset graph...
[  +89 ms] Reading cached asset graph completed, took 87ms

[ +180 ms] Checking for updates since last build...
[ +474 ms] Checking for updates since last build completed, took 474ms

[   +8 ms] Initializing inputs
[   +1 ms] Reading cached asset graph...
[        ] Reading cached asset graph completed, took 87ms
[        ] Checking for updates since last build...
[        ] Checking for updates since last build completed, took 474ms
[  +27 ms] Setting up file watchers...
[        ] Setting up file watchers completed, took 3ms
[  +30 ms] starting build daemon... (completed in 1.1s)
[ +113 ms] About to build [lib, test]...
[   +6 ms] Running build...
[  +56 ms] Running build completed, took 24ms

[        ] Caching finalized dependency graph...
[  +11 ms] Caching finalized dependency graph completed, took 66ms

[   +3 ms] Succeeded after 95ms with 0 outputs (0 actions)

[  +20 ms] Launching lib/main.dart on Chrome in debug mode...
[        ] Building application for the web...
[ +298 ms] Found plugin connectivity at
/usr/local/google/home/jakemac/.pub-cache/hosted/pub.dartlang.org/connectivity-0.4.5+1/
[   +1 ms] Found plugin device_info at
/usr/local/google/home/jakemac/.pub-cache/hosted/pub.dartlang.org/device_info-0.4.1/
[  +10 ms] Found plugin url_launcher at
/usr/local/google/home/jakemac/.pub-cache/hosted/pub.dartlang.org/url_launcher-5.2.3/
[        ] Found plugin video_player at
/usr/local/google/home/jakemac/.pub-cache/hosted/pub.dartlang.org/video_player-0.10.2+5/
[+5682 ms] Running Options: {--skip-build-script-check, --delete-conflicting-outputs,
--build-mode=BuildMode.Auto}
[        ] Requested Options: {--skip-build-script-check, --define,
flutter_tools:ddc=flutterWebSdk=/usr/local/google/home/jakemac/flutter/bin/cache/flutter_web_sdk,
flutter_tools:entrypoint=flutterWebSdk=/usr/local/google/home/jakemac/flutter/bin/cache/flutter_web_sdk,
flutter_tools:entrypoint=release=false, flutter_tools:entrypoint=profile=false,
flutter_tools:shell=flutterWebSdk=/usr/local/google/home/jakemac/flutter/bin/cache/flutter_web_sdk,
flutter_tools:shell=hasPlugins=false, flutter_tools:shell=initializePlatform=true,
--build-mode=BuildMode.Manual}
[   +7 ms] Building application for the web... (completed in 6.0s)
[   +2 ms] "flutter run" took 7,733ms.
Incompatible options with current running build daemon.

Please stop other flutter_tool instances running in this directory before starting a new instance with
these options.

#0      throwToolExit (package:flutter_tools/src/base/common.dart:28:3)
#1      BuildDaemonCreator.startBuildDaemon (package:flutter_tools/src/build_runner/web_fs.dart:575:7)
<asynchronous suspension>
#2      WebFs.start (package:flutter_tools/src/build_runner/web_fs.dart:247:10)
<asynchronous suspension>
#3      ResidentWebRunner.run.<anonymous closure>
(package:flutter_tools/src/build_runner/resident_web_runner.dart:193:36)
<asynchronous suspension>
#4      asyncGuard.<anonymous closure> (package:flutter_tools/src/base/async_guard.dart:112:32)
<asynchronous suspension>
#5      _rootRun (dart:async/zone.dart:1124:13)
#6      _CustomZone.run (dart:async/zone.dart:1021:19)
#7      _runZoned (dart:async/zone.dart:1516:10)
#8      runZoned (dart:async/zone.dart:1500:12)
#9      asyncGuard (package:flutter_tools/src/base/async_guard.dart:110:3)
#10     ResidentWebRunner.run (package:flutter_tools/src/build_runner/resident_web_runner.dart:192:32)
<asynchronous suspension>
#11     RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:492:37)
<asynchronous suspension>
#12     FlutterCommand.verifyThenRunCommand
(package:flutter_tools/src/runner/flutter_command.dart:557:18)
<asynchronous suspension>
#13     FlutterCommand.run.<anonymous closure>
(package:flutter_tools/src/runner/flutter_command.dart:457:33)
<asynchronous suspension>
#14     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:157:29)
<asynchronous suspension>
#15     _rootRun (dart:async/zone.dart:1124:13)
#16     _CustomZone.run (dart:async/zone.dart:1021:19)
#17     _runZoned (dart:async/zone.dart:1516:10)
#18     runZoned (dart:async/zone.dart:1463:12)
#19     AppContext.run (package:flutter_tools/src/base/context.dart:156:18)
<asynchronous suspension>
#20     FlutterCommand.run (package:flutter_tools/src/runner/flutter_command.dart:446:20)
#21     CommandRunner.runCommand (package:args/command_runner.dart:197:27)
<asynchronous suspension>
#22     FlutterCommandRunner.runCommand.<anonymous closure>
(package:flutter_tools/src/runner/flutter_command_runner.dart:416:21)
<asynchronous suspension>
#23     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:157:29)
<asynchronous suspension>
#24     _rootRun (dart:async/zone.dart:1124:13)
#25     _CustomZone.run (dart:async/zone.dart:1021:19)
#26     _runZoned (dart:async/zone.dart:1516:10)
#27     runZoned (dart:async/zone.dart:1463:12)
#28     AppContext.run (package:flutter_tools/src/base/context.dart:156:18)
<asynchronous suspension>
#29     FlutterCommandRunner.runCommand
(package:flutter_tools/src/runner/flutter_command_runner.dart:367:19)
<asynchronous suspension>
#30     CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:112:25)
#31     new Future.sync (dart:async/future.dart:222:31)
#32     CommandRunner.run (package:args/command_runner.dart:112:14)
#33     FlutterCommandRunner.run (package:flutter_tools/src/runner/flutter_command_runner.dart:251:18)
#34     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:63:22)
<asynchronous suspension>
#35     _rootRun (dart:async/zone.dart:1124:13)
#36     _CustomZone.run (dart:async/zone.dart:1021:19)
#37     _runZoned (dart:async/zone.dart:1516:10)
#38     runZoned (dart:async/zone.dart:1500:12)
#39     run.<anonymous closure> (package:flutter_tools/runner.dart:61:18)
<asynchronous suspension>
#40     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:157:29)
<asynchronous suspension>
#41     _rootRun (dart:async/zone.dart:1124:13)
#42     _CustomZone.run (dart:async/zone.dart:1021:19)
#43     _runZoned (dart:async/zone.dart:1516:10)
#44     runZoned (dart:async/zone.dart:1463:12)
#45     AppContext.run (package:flutter_tools/src/base/context.dart:156:18)
<asynchronous suspension>
#46     runInContext (package:flutter_tools/src/context_runner.dart:64:24)
<asynchronous suspension>
#47     run (package:flutter_tools/runner.dart:50:10)
#48     main (package:flutter_tools/executable.dart:65:9)
<asynchronous suspension>
#49     main
(file:///usr/local/google/home/jakemac/flutter/packages/flutter_tools/bin/flutter_tools.dart:8:3)
#50     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:303:32)
#51     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:12)
```

**Comment by jakemac53** [comment]
cc @jonahwilliams @grouma

**Comment by kf6gpe** [comment]
Touching for the purposes of triage.

**Comment by jonahwilliams** [comment]
This will be fixed by moving the flutter_web build to using the frontend server, so it might not be worth pursuing a fix independently

**Comment by jakemac53** [comment]
Re-opening as this still doesn't work but I am sending out a PR to enable it.
