### ISSUE TITLE
Cannot debug flutter application on Visual Studio Code

### ISSUE THREAD

**Issue by Maosalas** [flutter/flutter#43655]
#39821 @jmagman 
I was working on a application and I was getting this annoying error
```
Could not find the built application bundle at build/ios/iphonesimulator/Runner.app.
```
So I looked up in Google and din't find my solution. So I thought that making a backup of my .dart files and re-create my flutter application will solve my problem, but din't do anything.
 I can normally build my app by going to Xcode->Product->Run

## Logs
Output of `flutter run --verbose`
```
throwToolExit (package:flutter_tools/src/base/common.dart:28:3)
#1      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:477:7)
<asynchronous suspension>
#2      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:490:18)
#3      _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:71:64)
#4      _rootRunUnary (dart:async/zone.dart:1132:38)
#5      _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#6      _FutureListener.handleValue (dart:async/future_impl.dart:137:18)
#7      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:678:45)
#8      Future._propagateToListeners (dart:async/future_impl.dart:707:32)
#9      Future._completeWithValue (dart:async/future_impl.dart:522:5)
#10     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:30:15)
#11     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:288:13)
#12     RunCommand.usageValues (package:flutter_tools/src/commands/run.dart)
#13     _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:71:64)
#14     _rootRunUnary (dart:async/zone.dart:1132:38)
#15     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#16     _FutureListener.handleValue (dart:async/future_impl.dart:137:18)
#17     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:678:45)
#18     Future._propagateToListeners (dart:async/future_impl.dart:707:32)
#19     Future._completeWithValue (dart:async/future_impl.dart:522:5)
#20     Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:552:7)
#21     _rootRun (dart:async/zone.dart:1124:13)
#22     _CustomZone.run (dart:async/zone.dart:1021:19)
#23     _CustomZone.runGuarded (dart:async/zone.dart:923:7)
#24     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:963:23)
#25     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#26     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#27     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:116:13)
#28     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:173:5)
```

Output`flutter analyze` 

```
 info • Name non-constant identifiers using lowerCamelCase • lib/PruebaScan.dart:30:8 • non_constant_identifier_names
   info • Unused import: 'package:pay_id/Screens/testScan.dart' • lib/Screens/dashboard.dart:3:8 • unused_import
   info • Unused import: 'package:flutter/material.dart' • lib/cobros.dart:1:8 • unused_import
   info • Unused import: 'RegistroTrajetaOCedulaWidget.dart' • lib/main.dart:2:8 • unused_import
   info • Unused import: 'package:pay_id/Screens/testScan.dart' • lib/main.dart:3:8 • unused_import
   info • Unused import: 'Screens/dashboard.dart' • lib/main.dart:4:8 • unused_import
   info • Unused import: 'tests/maps.dart' • lib/main.dart:6:8 • unused_import
```

Output `flutter doctor -v`

```
[✓] Flutter (Channel stable, v1.9.1+hotfix.6, on Mac OS X 10.14.6 18G103, locale en-US)
    • Flutter version 1.9.1+hotfix.6 at /Users/maosalas/Documents/DEVELOPMENT/flutter
    • Framework revision 68587a0916 (6 weeks ago), 2019-09-13 19:46:58 -0700
    • Engine revision b863200c37
    • Dart version 2.5.0

[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/setup/#android-setup for detailed instructions).
      If the Android SDK has been installed to a custom location, set ANDROID_HOME to that location.
      You may also want to add it to your PATH environment variable.



[✓] Xcode - develop for iOS and macOS (Xcode 11.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.2, Build version 11B44
    • CocoaPods version 1.8.4

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/setup/#android-setup for detailed instructions).

[✓] Connected device (1 available)
    • iPhone 11 Pro Max • AA9259DC-C751-4FAD-8246-1985A93E7733 • ios • com.apple.CoreSimulator.SimRuntime.iOS-13-2
      (simulator)

! Doctor found issues in 2 categories.
```

**Comment by jmagman** [comment]
Did it write out a log somewhere you can include?  Or give some more info before the stack.  The logs you pasted don't include the reason error message from throwToolExit.

**Comment by iapicca** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact descriptions what happens, logs and the output of 'flutter doctor -v'  please.
All system setups can be slightly different so its always better to open new issues and reference related issues.
