### ISSUE TITLE
Flutter tool Spinner tests are flaky again

### ISSUE THREAD

**Issue by jonahwilliams** [flutter/flutter#43754]
```
03:05 +1298 ~5: test/general.shard/base/logger_test.dart: Spinners Stdout startProgress on colored terminal pauses on linux                                                                            Expected: 'Knock Knock, Who\'s There             \b\b\b\b\b\b\b\b       ⣽\b\b\b\b\b\b\b\b        \b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b                             \b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\bRude Interrupting Cow\n'
            'Knock Knock, Who\'s There             \b\b\b\b\b\b\b\b       ⣻\b\b\b\b\b\b\b\b        \b\b\b\b\b\b\b\b    0.0s\n'
            ''
  Actual: 'Knock Knock, Who\'s There             \b\b\b\b\b\b\b\b       ⣽\b\b\b\b\b\b\b\b        \b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b                             \b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\bRude Interrupting Cow\n'
            'Knock Knock, Who\'s There             \b\b\b\b\b\b\b\b       ⣻\b\b\b\b\b\b\b\b        \b\b\b\b\b\b\b\b    0.1s\n'
            ''
   Which: is different.
          Expected: ... \b\b    0.0s\n
            Actual: ... \b\b    0.1s\n
                                  ^
           Differ at offset 376
#0      fail (package:test_api/src/frontend/expect.dart:152:30)
#1      _expect (package:test_api/src/frontend/expect.dart:146:3)
#2      expect (package:test_api/src/frontend/expect.dart:59:3)
#3      main.<anonymous closure>.<anonymous closure>.<anonymous closure> (org-dartlang-app:///test/general.shard/base/logger_test.dart:202:11)
#4      _FakeAsync.run.<anonymous closure> (package:quiver/testing/src/async/fake_async.dart:199:24)
#5      _rootRun (dart:async/zone.dart:1124:13)
#6      _CustomZone.run (dart:async/zone.dart:1021:19)
#7      _CustomZone.runGuarded (dart:async/zone.dart:923:7)
#8      _FakeAsync.run (package:quiver/testing/src/async/fake_async.dart:198:11)
#9      main.<anonymous closure>.<anonymous closure> (org-dartlang-app:///test/general.shard/base/logger_test.dart:191:21)
<asynchronous suspension>
#10     testUsingContext.<anonymous closure>.<anonymous closure>.<anonymous closure>.<anonymous closure>.<anonymous closure> (org-dartlang-app:///test/src/context.dart:123:42)
<asynchronous suspension>
#11     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:157:29)
<asynchronous suspension>
#12     _rootRun (dart:async/zone.dart:1124:13)
#13     _CustomZone.run (dart:async/zone.dart:1021:19)
#14     _runZoned (dart:async/zone.dart:1516:10)
#15     runZoned (dart:async/zone.dart:1463:12)
#16     AppContext.run (package:flutter_tools/src/base/context.dart:156:18)
<asynchronous suspension>
#17     testUsingContext.<anonymous closure>.<anonymous closure>.<anonymous closure>.<anonymous closure> (org-dartlang-app:///test/src/context.dart:112:30)
#18     _rootRun (dart:async/zone.dart:1124:13)
#19     _CustomZone.run (dart:async/zone.dart:1021:19)
#20     _runZoned (dart:async/zone.dart:1516:10)
#21     runZoned (dart:async/zone.dart:1500:12)
#22     testUsingContext.<anonymous closure>.<anonymous closure>.<anonymous closure> (org-dartlang-app:///test/src/context.dart:110:18)
#23     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:157:29)
<asynchronous suspension>
#24     _rootRun (dart:async/zone.dart:1124:13)
#25     _CustomZone.run (dart:async/zone.dart:1021:19)
#26     _runZoned (dart:async/zone.dart:1516:10)
#27     runZoned (dart:async/zone.dart:1463:12)
#28     AppContext.run (package:flutter_tools/src/base/context.dart:156:18)
<asynchronous suspension>
#29     testUsingContext.<anonymous closure>.<anonymous closure> (org-dartlang-app:///test/src/context.dart:83:22)
#30     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:157:29)
<asynchronous suspension>
#31     _rootRun (dart:async/zone.dart:1124:13)
#32     _CustomZone.run (dart:async/zone.dart:1021:19)
#33     _runZoned (dart:async/zone.dart:1516:10)
#34     runZoned (dart:async/zone.dart:1463:12)
#35     AppContext.run (package:flutter_tools/src/base/context.dart:156:18)
<asynchronous suspension>
#36     runInContext (package:flutter_tools/src/context_runner.dart:64:24)
<asynchronous suspension>
#37     testUsingContext.<anonymous closure> (org-dartlang-app:///test/src/context.dart:82:11)
<asynchronous suspension>
#38     Declarer.test.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:test_api/src/backend/declarer.dart:168:27)
<asynchronous suspension>
#39     Invoker.waitForOutstandingCallbacks.<anonymous closure> (package:test_api/src/backend/invoker.dart:250:15)
<asynchronous suspension>
#40     _rootRun (dart:async/zone.dart:1124:13)
#41     _CustomZone.run (dart:async/zone.dart:1021:19)
#42     _runZoned (dart:async/zone.dart:1516:10)
#43     runZoned (dart:async/zone.dart:1463:12)
#44     Invoker.waitForOutstandingCallbacks (package:test_api/src/backend/invoker.dart:247:5)
#45     Declarer.test.<anonymous closure>.<anonymous closure> (package:test_api/src/backend/declarer.dart:166:33)
#46     _rootRun (dart:async/zone.dart:1124:13)
#47     _CustomZone.run (dart:async/zone.dart:1021:19)
#48     _runZoned (dart:async/zone.dart:1516:10)
#49     runZoned (dart:async/zone.dart:1463:12)
#50     Declarer.test.<anonymous closure> (package:test_api/src/backend/declarer.dart:165:13)
<asynchronous suspension>
#51     Invoker._onRun.<anonymous closure>.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:test_api/src/backend/invoker.dart:400:25)
<asynchronous suspension>
#52     new Future.<anonymous closure> (dart:async/future.dart:174:37)
#53     StackZoneSpecification._run (package:stack_trace/src/stack_zone_specification.dart:209:15)
#54     StackZoneSpecification._registerCallback.<anonymous closure> (package:stack_trace/src/stack_zone_specification.dart:119:48)
#55     _rootRun (dart:async/zone.dart:1120:38)
#56     _CustomZone.run (dart:async/zone.dart:1021:19)
#57     _CustomZone.runGuarded (dart:async/zone.dart:923:7)
#58     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:963:23)
#59     StackZoneSpecification._run (package:stack_trace/src/stack_zone_specification.dart:209:15)
#60     StackZoneSpecification._registerCallback.<anonymous closure> (package:stack_trace/src/stack_zone_specification.dart:119:48)
#61     _rootRun (dart:async/zone.dart:1124:13)
#62     _CustomZone.run (dart:async/zone.dart:1021:19)
#63     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:947:23)
#64     Timer._createTimer.<anonymous closure> (dart:async-patch/timer_patch.dart:21:15)
#65     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:382:19)
#66     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:416:5)
#67     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:12)
```

**Comment by Hixie** [comment]
uh, I thought those tests ran in a FakeAsync zone. Oops.

**Comment by Hixie** [comment]
That test _is_ in a FakeAsync zone. o_O

https://github.com/flutter/flutter/blob/master/packages/flutter_tools/test/general.shard/base/logger_test.dart#L189

**Comment by jonahwilliams** [comment]
It's possible there is some state leaking though. Zones are weird

**Comment by Hixie** [comment]
Maybe it uses Stopwatch and Stopwatch doesn't get mocked by FakeAsync or something.

**Comment by jonahwilliams** [comment]
Yup, this test is missing a MockStopwatch injection. I'll send a PR to fix it
