### ISSUE TITLE
Cocoon Cache.get occasionally fails due to race condition where a write is happening at the same time as get

### ISSUE THREAD

**Issue by CaseyHillers** [flutter/flutter#43762]
```
Bad state: StreamSink is bound to a stream
#0      _StreamSinkImpl._controller (dart:io/io_sink.dart:236:7)
#1      _StreamSinkImpl.add (dart:io/io_sink.dart:156:5)
#2      _Socket.add (dart:io-patch/socket_patch.dart:1674:38)
#3      Connection.send (package:dartis/src/client/connection.dart:101:13)
#4      DispatcherBase.send (package:dartis/src/client/dispatcher.dart:29:17)
#5      _ClientDispatcher.dispatch (package:dartis/src/client/client.dart:199:5)
#6      Client.run (package:dartis/src/client/client.dart:171:50)
#7      ModuleBase.execute (package:dartis/src/command/module.dart:57:20)
#8      ModuleBase.run (package:dartis/src/command/module.dart:50:12)
#9      Commands.get (package:dartis/src/command/commands.dart:1146:27)
#10     RedisCacheProvider.get.<anonymous closure> (package:neat_cache/src/providers/redis.dart:145:68)
#11     RedisCacheProvider._withRedis (package:neat_cache/src/providers/redis.dart:115:22)
<asynchronous suspension>
#12     RedisCacheProvider.get (package:neat_cache/src/providers/redis.dart:145:40)
#13     _Entry.get (package:neat_cache/neat_cache.dart:163:38)
<asynchronous suspension>
#14     CacheRequestHandler.get (package:cocoon_service/src/request_handling/cache_request_handler.dart:46:71)
<asynchronous suspension>
#15     RequestHandler.service.<anonymous closure> (package:cocoon_service/src/request_handling/request_handler.dart:46:28)
<asynchronous suspension>
#16     _rootRun (dart:async/zone.dart:1124:13)
#17     _CustomZone.run (dart:async/zone.dart:1021:19)
#18     _runZoned (dart:async/zone.dart:1516:10)
#19     runZoned (dart:async/zone.dart:1463:12)
#20     RequestHandler.service (package:cocoon_service/src/request_handling/request_handler.dart:39:12)
#21     main.<anonymous closure>.<anonymous closure> (file:///app/bin/server.dart:95:23)
<asynchronous suspension>
#22     runAppEngine.<anonymous closure> (package:appengine/appengine.dart:80:12)
#23     runAppEngine.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:appengine/src/appengine_internal.dart:57:18)
#24     _ServiceScope._fork.<anonymous closure> (package:gcloud/service_scope.dart:209:19)
#25     _rootRun (dart:async/zone.dart:1124:13)
#26     _CustomZone.run (dart:async/zone.dart:1021:19)
#27     _runZoned (dart:async/zone.dart:1516:10)
#28     runZoned (dart:async/zone.dart:1500:12)
#29     _ServiceScope._fork (package:gcloud/service_scope.dart:208:12)
#30     fork (package:gcloud/service_scope.dart:104:30)
#31     runAppEngine.<anonymous closure>.<anonymous closure> (package:appengine/src/appengine_internal.dart:55:9)
#32     AppEngineHttpServer.run.<anonymous closure>.<anonymous closure> (package:appengine/src/server/server.dart:83:16)
#33     _rootRunUnary (dart:async/zone.dart:1132:38)
#34     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#35     _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
#36     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#37     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#38     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:764:19)
#39     _StreamController._add (dart:async/stream_controller.dart:640:7)
#40     _StreamController.add (dart:async/stream_controller.dart:586:5)
#41     _HttpServer._handleRequest (dart:_http/http_impl.dart:2726:19)
#42     new _HttpConnection.<anonymous closure> (dart:_http/http_impl.dart:2484:19)
#43     _rootRunUnary (dart:async/zone.dart:1132:38)
#44     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#45     _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
#46     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#47     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#48     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:764:19)
#49     _StreamController._add (dart:async/stream_controller.dart:640:7)
#50     _StreamController.add (dart:async/stream_controller.dart:586:5)
#51     _HttpParser._headersEnd (dart:_http/http_parser.dart:372:19)
#52     _HttpParser._doParse (dart:_http/http_parser.dart:701:15)
#53     _HttpParser._parse (dart:_http/http_parser.dart:318:7)
#54     _HttpParser._onData (dart:_http/http_parser.dart:810:5)
#55     _rootRunUnary (dart:async/zone.dart:1132:38)
#56     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#57     _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
#58     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#59     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#60     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:764:19)
#61     _StreamController._add (dart:async/stream_controller.dart:640:7)
#62     _StreamController.add (dart:async/stream_controller.dart:586:5)
#63     _Socket._onData (dart:io-patch/socket_patch.dart:1791:41)
#64     _rootRunUnary (dart:async/zone.dart:1136:13)
#65     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#66     _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
#67     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#68     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#69     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:764:19)
#70     _StreamController._add (dart:async/stream_controller.dart:640:7)
#71     _StreamController.add (dart:async/stream_controller.dart:586:5)
#72     new _RawSocket.<anonymous closure> (dart:io-patch/socket_patch.dart:1339:33)
#73     _NativeSocket.issueReadEvent.issue (dart:io-patch/socket_patch.dart:860:14)
#74     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#75     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#76     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:116:13)
#77     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:173:5)
```

**Comment by CaseyHillers** [comment]
Slightly related to https://github.com/flutter/flutter/issues/43762 as the TV version of the dashboard will *randomly* give the red error screen.

**Comment by CaseyHillers** [comment]
The PR helped mitigate the issue, but there are still some stream sink errors happening.

**Comment by keyonghan** [comment]
Reopen due to: https://github.com/flutter/flutter/issues/54863

**Comment by godofredoc** [comment]
I haven't seen this issue recently. Closing as obsolete.
