### ISSUE TITLE
Using initialRoute on WidgetsApp can cause exception

### ISSUE THREAD

**Issue by dannyvalentesonos** [flutter/flutter#43810]
When building a WidgetsApp or MaterialApp widget like so:

```
return MaterialApp(
      title: 'title',
      initialRoute: '/someroute',
      routes: {'/someroute': (context) => Container() }
    );
```

the following exception happens because the initial route is a TransitionRoute and it tries to set the opaque value on an overlay entry before it's built.

```
flutter: When the exception was thrown, this was the stack:
flutter: #2      OverlayEntry.opaque= (package:flutter/src/widgets/overlay.dart:89:12)
flutter: #3      TransitionRoute._handleStatusChanged (package:flutter/src/widgets/routes.dart:152:32)
flutter: #4      AnimationLocalStatusListenersMixin.notifyStatusListeners (package:flutter/src/animation/listener_helpers.dart:193:19)
flutter: #5      AnimationController._checkStatusChanged (package:flutter/src/animation/animation_controller.dart:769:7)
flutter: #6      AnimationController._animateToInternal (package:flutter/src/animation/animation_controller.dart:585:7)
flutter: #7      AnimationController.forward (package:flutter/src/animation/animation_controller.dart:458:12)
flutter: #8      TransitionRoute.didPush (package:flutter/src/widgets/routes.dart:189:24)
flutter: #9      ModalRoute.didPush (package:flutter/src/widgets/routes.dart:933:18)
flutter: #10     NavigatorState.push (package:flutter/src/widgets/navigator.dart:1791:11)
flutter: #11     Iterable.forEach (dart:core/iterable.dart:277:30)
flutter: #12     NavigatorState.initState (package:flutter/src/widgets/navigator.dart:1558:77)
```

**Comment by dannyvalentesonos** [comment]
I had onGenerateRoute set also, and it wasn't returning null for /, which was causing this problem. I'm closing this as it's not an issue.
