### ISSUE TITLE
Build failing when using extension method

### ISSUE THREAD

**Issue by cirediew** [flutter/flutter#43811]
## Steps to Reproduce

I've written an extension method on a class to get a `Color` based on its id.
But when building/running it I get a compiler error telling me I'm passing arguments from the wrong libraries.

My code:
``` dart
//file name: extensions.dart
import 'package:my_app/database/database.dart';
import 'package:flutter/material.dart';

extension CategoryX on Category {
  Color getColor({
    Color defaultColor = ColorUtil.myGreen,
    Brightness brightness = Brightness.light,
  }) {
    switch (categoryId) {
      // more cases
      case Category.BUILDING_RELATED:
        return brightness == Brightness.light
            ? ColorUtil.buildingRelatedColor
            : ColorUtil.buildingRelatedColorLight;
      default:
        return defaultColor ?? ColorUtil.greenPrimary;
    }
  }
}
```

``` dart
import 'package:my_app/database/database.dart';
import 'package:my_app/database/extensions.dart';
import 'package:flutter/material.dart';

class BundleChartCard{

  myFunction(BuildContext context){
    //calling my extension
    var _c = category.getColor(
          defaultColor: Theme.of(context).accentColor,
          brightness: Theme.of(context).brightness,
        );
  }
}
```

I've tried removing the default values `defaultColor` and `brightness`, but the same error occurs.

When running without passing any optional parameters it does compile without errors.
When removing the parameters from `getColor` it does compile without errors.

**Target Platform:** Android
**Target OS version/browser:** Android 10 (api 29)
**Devices:** any, emulator and Android device

## Logs

I get the following compiler error when using the new extension methods:
Compiler message:
```
14:06:34.651 11 info flutter.tools 
14:06:34.652 12 info flutter.tools Compiler message:
14:06:34.652 13 info flutter.tools 
14:06:34.657 14 info flutter.tools  - 'Category' is from 'package:my_app/database/database.dart' ('lib/database/database.dart').
14:06:34.657 15 info flutter.tools  - 'Color' is from 'dart:ui'.
14:06:34.657 16 info flutter.tools           defaultColor: Theme.of(context).accentColor,
14:06:34.657 17 info flutter.tools                                           ^
14:06:34.660 18 info flutter.tools  - 'Category' is from 'package:my_app/database/database.dart' ('lib/database/database.dart').
14:06:34.660 19 info flutter.tools  - 'Brightness' is from 'dart:ui'.
14:06:34.660 20 info flutter.tools           brightness: Theme.of(context).brightness,
14:06:34.660 21 info flutter.tools                                         ^
14:06:38.448 22 info flutter.tools Exception: Errors during snapshot creation: null
14:06:38.448 23 info flutter.tools #0      KernelSnapshot.build (package:flutter_tools/src/build_system/targets/dart.dart:225:7)
14:06:38.448 24 info flutter.tools <asynchronous suspension>
14:06:38.448 25 info flutter.tools #1      _BuildInstance._invokeInternal (package:flutter_tools/src/build_system/build_system.dart:527:25)
14:06:38.448 26 info flutter.tools <asynchronous suspension>
14:06:38.449 27 info flutter.tools #2      _BuildInstance.invokeTarget.<anonymous closure> (package:flutter_tools/src/build_system/build_system.dart:482:35)
14:06:38.449 28 info flutter.tools #3      new Future.sync (dart:async/future.dart:224:31)
14:06:38.449 29 info flutter.tools 
14:06:38.449 30 info flutter.tools #4      AsyncMemoizer.runOnce (package:async/src/async_memoizer.dart:43:45)
14:06:38.449 31 info flutter.tools 
14:06:38.451 32 info flutter.tools #5      _BuildInstance.invokeTarget (package:flutter_tools/src/build_system/build_system.dart:482:21)
14:06:38.451 33 info flutter.tools 
14:06:38.451 34 info flutter.tools <asynchronous suspension>
14:06:38.451 35 info flutter.tools <asynchronous suspension>
14:06:38.451 36 info flutter.tools 
14:06:38.452 37 info flutter.tools #6      BuildSystem.build (package:flutter_tools/src/build_system/build_system.dart:420:36)
14:06:38.452 38 info flutter.tools #7      _AsyncAwaitCompleter.start (dart:async-patch/async_patch.dart:43:6)
14:06:38.452 39 info flutter.tools 
14:06:38.452 40 info flutter.tools #8      BuildSystem.build (package:flutter_tools/src/build_system/build_system.dart:401:28)
14:06:38.452 41 info flutter.tools 
14:06:38.452 42 info flutter.tools #9      buildWithAssemble (package:flutter_tools/src/bundle.dart:171:48)
14:06:38.452 43 info flutter.tools 
14:06:38.452 44 info flutter.tools #10     _AsyncAwaitCompleter.start (dart:async-patch/async_patch.dart:43:6)
14:06:38.452 45 info flutter.tools 
14:06:38.452 46 info flutter.tools #11     buildWithAssemble (package:flutter_tools/src/bundle.dart:147:31)
14:06:38.452 47 info flutter.tools #12     BundleBuilder.build (package:flutter_tools/src/bundle.dart:85:13)
14:06:38.453 48 info flutter.tools 
14:06:38.453 49 info flutter.tools #13     _AsyncAwaitCompleter.start (dart:async-patch/async_patch.dart:43:6)
14:06:38.453 50 info flutter.tools 
14:06:38.454 51 info flutter.tools #14     BundleBuilder.build (package:flutter_tools/src/bundle.dart:58:21)
14:06:38.454 52 info flutter.tools 
14:06:38.455 53 info flutter.tools #15     BuildBundleCommand.runCommand (package:flutter_tools/src/commands/build_bundle.dart:126:25)
14:06:38.455 54 info flutter.tools #16     _AsyncAwaitCompleter.start (dart:async-patch/async_patch.dart:43:6)
14:06:38.455 55 info flutter.tools 
14:06:38.455 56 info flutter.tools #17     BuildBundleCommand.runCommand (package:flutter_tools/src/commands/build_bundle.dart:97:42)
14:06:38.455 57 info flutter.tools #18     FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:553:18)
14:06:38.455 58 info flutter.tools 
14:06:38.455 59 info flutter.tools #19     _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:71:64)
14:06:38.456 60 info flutter.tools #20     _rootRunUnary (dart:async/zone.dart:1132:38)
14:06:38.457 61 info flutter.tools #21     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
14:06:38.459 62 info flutter.tools #22     _FutureListener.handleValue (dart:async/future_impl.dart:137:18)
14:06:38.461 63 info flutter.tools #23     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:678:45)
14:06:38.461 64 info flutter.tools 
14:06:38.463 65 info flutter.tools #24     Future._propagateToListeners (dart:async/future_impl.dart:707:32)
14:06:38.463 66 info flutter.tools #25     Future._completeWithValue (dart:async/future_impl.dart:522:5)
14:06:38.464 67 info flutter.tools #26     Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:552:7)
14:06:38.464 68 info flutter.tools 
14:06:38.465 69 info flutter.tools #27     _rootRun (dart:async/zone.dart:1124:13)
14:06:38.465 70 info flutter.tools 
14:06:38.465 71 info flutter.tools #28     _CustomZone.run (dart:async/zone.dart:1021:19)
14:06:38.465 72 info flutter.tools 
14:06:38.465 73 info flutter.tools #29     _CustomZone.runGuarded (dart:async/zone.dart:923:7)
14:06:38.465 74 info flutter.tools #30     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:963:23)
14:06:38.465 75 info flutter.tools #31     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
14:06:38.466 76 info flutter.tools #32     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
14:06:38.466 77 info flutter.tools 
14:06:38.466 78 info flutter.tools #33     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:116:13)
14:06:38.466 79 info flutter.tools 
14:06:38.466 80 info flutter.tools #34     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:173:5)
14:06:38.467 81 info flutter.tools 
14:06:38.468 82 info flutter.tools 
14:06:38.471 83 info flutter.tools Failed to build bundle.
14:06:38.472 84 info flutter.tools 
14:06:38.474 85 info flutter.tools 
14:06:38.474 86 info flutter.tools FAILURE: Build failed with an exception.
14:06:38.474 87 info flutter.tools 
14:06:38.474 88 info flutter.tools 
14:06:38.477 89 info flutter.tools * Where:
14:06:38.477 90 info flutter.tools 
14:06:38.478 91 info flutter.tools Script 'C:\flutter\packages\flutter_tools\gradle\flutter.gradle' line: 787
14:06:38.478 92 info flutter.tools 
14:06:38.478 93 info flutter.tools 
14:06:38.478 94 info flutter.tools * What went wrong:
14:06:38.478 95 info flutter.tools 
14:06:38.478 96 info flutter.tools Execution failed for task ':app:compileFlutterBuildStagingDebugX86'.
14:06:38.479 97 info flutter.tools 
14:06:38.479 98 info flutter.tools > Process 'command 'C:\flutter\bin\flutter.bat'' finished with non-zero exit value 1
14:06:38.479 99 info flutter.tools 
14:06:38.479 100 info flutter.tools 
14:06:38.479 101 info flutter.tools * Try:
14:06:38.479 102 info flutter.tools 
14:06:38.482 103 info flutter.tools Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
14:06:38.482 104 info flutter.tools 
14:06:38.482 105 info flutter.tools 
14:06:38.482 106 info flutter.tools * Get more help at https://help.gradle.org
14:06:38.482 107 info flutter.tools 
14:06:38.482 108 info flutter.tools 
14:06:38.482 109 info flutter.tools BUILD FAILED in 17s
```

```
[√] Flutter (Channel beta, v1.10.7, on Microsoft Windows [Version 10.0.18362.418], locale en-US)
    • Flutter version 1.10.7 at C:\flutter
    • Framework revision e70236e36c (4 weeks ago), 2019-10-02 09:32:30 -0700
    • Engine revision 9e6314d348
    • Dart version 2.6.0 (build 2.6.0-dev.4.0 1103600280)


[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at F:\SDK
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • ANDROID_HOME = F:\SDK
    • Java binary at: C:\Users\Me\AppData\Local\JetBrains\Toolbox\apps\AndroidStudio\ch-1\192.5959023\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)
    • All Android licenses accepted.

[√] Android Studio (version 4.0)
    • Android Studio at C:\Users\Me\AppData\Local\JetBrains\Toolbox\apps\AndroidStudio\ch-1\192.5959023
    • Flutter plugin version 40.2.4
    • Dart plugin version 192.7402
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)

[√] Connected device (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 10 (API 29) (emulator)

• No issues found!

```
EDIT:

Some additional logs when running the extension in a test:
```
Exception: the Dart compiler exited unexpectedly.
  package:flutter_tools/src/base/common.dart 28:3               throwToolExit
  package:flutter_tools/src/compile.dart 621:9                  ResidentCompiler._compile.<fn>
  package:stack_trace/src/stack_zone_specification.dart 129:26  StackZoneSpecification._registerUnaryCallback.<fn>.<fn>
  package:stack_trace/src/stack_zone_specification.dart 209:15  StackZoneSpecification._run
  package:stack_trace/src/stack_zone_specification.dart 129:14  StackZoneSpecification._registerUnaryCallback.<fn>
  dart:async/zone.dart 1132:38                                  _rootRunUnary
  dart:async/zone.dart 1029:19                                  _CustomZone.runUnary
  dart:async/future_impl.dart 137:18                            _FutureListener.handleValue
  dart:async/future_impl.dart 678:45                            Future._propagateToListeners.handleValueCallback
  dart:async/future_impl.dart 707:32                            Future._propagateToListeners
  dart:async/future_impl.dart 605:9                             Future._propagateToListeners
  dart:async/future_impl.dart 522:5                             Future._completeWithValue
  dart:async/future_impl.dart 552:7                             Future._asyncComplete.<fn>
  package:stack_trace/src/stack_zone_specification.dart 209:15  StackZoneSpecification._run
  package:stack_trace/src/stack_zone_specification.dart 119:48  StackZoneSpecification._registerCallback.<fn>
  dart:async/zone.dart 1124:13                                  _rootRun
  dart:async/zone.dart 1021:19                                  _CustomZone.run
  dart:async/zone.dart 923:7                                    _CustomZone.runGuarded
  dart:async/zone.dart 963:23                                   _CustomZone.bindCallbackGuarded.<fn>
  dart:async/schedule_microtask.dart 41:21                      _microtaskLoop
  dart:async/schedule_microtask.dart 50:5                       _startMicrotaskLoop
  dart:isolate-patch/isolate_patch.dart 116:13                  _runPendingImmediateCallback
  dart:isolate-patch/isolate_patch.dart 173:5                   _RawReceivePortImpl._handleMessage
  ===== asynchronous gap ===========================
  dart:async/zone.dart 1053:19                                  _CustomZone.registerUnaryCallback
  dart:async/future_impl.dart 273:23                            Future.then
  package:flutter_tools/src/compile.dart 619:32                 ResidentCompiler._compile
  ===== asynchronous gap ===========================
  dart:async/zone.dart 1053:19                                  _CustomZone.registerUnaryCallback
  dart:async-patch/async_patch.dart 71:23                       _asyncThenWrapperHelper
  package:flutter_tools/src/compile.dart                        ResidentCompiler._compile
  package:flutter_tools/src/compile.dart 513:14                 ResidentCompiler._recompile
  ===== asynchronous gap ===========================
  dart:async/zone.dart 1053:19                                  _CustomZone.registerUnaryCallback
  dart:async/stream_impl.dart 139:21                            _BufferingStreamSubscription.onData
  dart:async/stream_impl.dart 112:10                            new _BufferingStreamSubscription
  dart:async/stream_controller.dart 838:9                       new _ControllerSubscription
  dart:async/stream_controller.dart 670:51                      _StreamController._subscribe
  dart:async/stream_controller.dart 818:19                      _ControllerStream._createSubscription
  dart:async/stream_impl.dart 472:9                             _StreamImpl.listen
  package:flutter_tools/src/compile.dart 485:26                 ResidentCompiler.recompile
  ===== asynchronous gap ===========================
  dart:async/zone.dart 1053:19                                  _CustomZone.registerUnaryCallback
  dart:async-patch/async_patch.dart 71:23                       _asyncThenWrapperHelper
  package:flutter_tools/src/test/test_compiler.dart             TestCompiler._onCompilationRequest
  package:stack_trace/src/stack_zone_specification.dart 129:26  StackZoneSpecification._registerUnaryCallback.<fn>.<fn>
  package:stack_trace/src/stack_zone_specification.dart 209:15  StackZoneSpecification._run
  package:stack_trace/src/stack_zone_specification.dart 129:14  StackZoneSpecification._registerUnaryCallback.<fn>
  dart:async/zone.dart 1132:38                                  _rootRunUnary
  dart:async/zone.dart 1029:19                                  _CustomZone.runUnary
  dart:async/zone.dart 931:7                                    _CustomZone.runUnaryGuarded
  dart:async/stream_impl.dart 336:11                            _BufferingStreamSubscription._sendData
  dart:async/stream_impl.dart 591:14                            _DelayedData.perform
  dart:async/stream_impl.dart 707:11                            _StreamImplEvents.handleNext
  dart:async/stream_impl.dart 667:7                             _PendingEvents.schedule.<fn>
  package:stack_trace/src/stack_zone_specification.dart 209:15  StackZoneSpecification._run
  package:stack_trace/src/stack_zone_specification.dart 119:48  StackZoneSpecification._registerCallback.<fn>
  dart:async/zone.dart 1120:38                                  _rootRun
  dart:async/zone.dart 1021:19                                  _CustomZone.run
  dart:async/zone.dart 923:7                                    _CustomZone.runGuarded
  dart:async/zone.dart 963:23                                   _CustomZone.bindCallbackGuarded.<fn>
  package:stack_trace/src/stack_zone_specification.dart 209:15  StackZoneSpecification._run
  package:stack_trace/src/stack_zone_specification.dart 119:48  StackZoneSpecification._registerCallback.<fn>
  dart:async/zone.dart 1124:13                                  _rootRun
  dart:async/zone.dart 1021:19                                  _CustomZone.run
  dart:async/zone.dart 923:7                                    _CustomZone.runGuarded
  dart:async/zone.dart 963:23                                   _CustomZone.bindCallbackGuarded.<fn>
  dart:async/schedule_microtask.dart 41:21                      _microtaskLoop
  dart:async/schedule_microtask.dart 50:5                       _startMicrotaskLoop
  dart:isolate-patch/timer_impl.dart 391:30                     _Timer._runTimers
  dart:isolate-patch/timer_impl.dart 416:5                      _Timer._handleMessage
  dart:isolate-patch/isolate_patch.dart 172:12                  _RawReceivePortImpl._handleMessage
  ===== asynchronous gap ===========================
  dart:async/zone.dart 1053:19                                  _CustomZone.registerUnaryCallback
  dart:async/stream_impl.dart 139:21                            _BufferingStreamSubscription.onData
  dart:async/stream_impl.dart 112:10                            new _BufferingStreamSubscription
  dart:async/stream_controller.dart 838:9                       new _ControllerSubscription
  dart:async/stream_controller.dart 670:51                      _StreamController._subscribe
  dart:async/stream_controller.dart 818:19                      _ControllerStream._createSubscription
  dart:async/stream_impl.dart 472:9                             _StreamImpl.listen
  package:flutter_tools/src/test/test_compiler.dart 53:31       new TestCompiler
  package:flutter_tools/src/test/flutter_platform.dart 454:22   FlutterPlatform._startTest
  ===== asynchronous gap ===========================
  dart:async/zone.dart 1053:19                                  _CustomZone.registerUnaryCallback
  dart:async-patch/async_patch.dart 71:23                       _asyncThenWrapperHelper
  package:flutter_tools/src/test/flutter_platform.dart          FlutterPlatform._startTest
  package:flutter_tools/src/test/flutter_platform.dart 363:36   FlutterPlatform.loadChannel
  package:flutter_tools/src/test/flutter_platform.dart 316:46   FlutterPlatform.load
  ===== asynchronous gap ===========================
  dart:async/zone.dart 1053:19                                  _CustomZone.registerUnaryCallback
  dart:async-patch/async_patch.dart 71:23                       _asyncThenWrapperHelper
  package:test_core/src/runner/loader.dart                      Loader.loadFile.<fn>
  package:test_core/src/runner/load_suite.dart 98:31            new LoadSuite.<fn>.<fn>
  ===== asynchronous gap ===========================
  dart:async/zone.dart 1045:19                                  _CustomZone.registerCallback
  dart:async/zone.dart 962:22                                   _CustomZone.bindCallbackGuarded
  dart:async/timer.dart 52:45                                   new Timer
  dart:async/timer.dart 87:9                                    Timer.run
  dart:async/future.dart 174:11                                 new Future
  package:test_api/src/backend/invoker.dart 399:21              Invoker._onRun.<fn>.<fn>.<fn>
```

**Comment by jmagman** [comment]
This is a dart compilation bug and should be filed against https://github.com/dart-lang/sdk/issues.  Closing.
