### ISSUE TITLE
iOS system task bar does not display correctly on physical device.

### ISSUE THREAD

**Issue by jcairo** [flutter/flutter#43987]
## Steps to Reproduce
[main.dart.zip](https://github.com/flutter/flutter/files/3798423/main.dart.zip)

iOS physical device will not display the system task bar in black. 

The color changes as expected on iOS emulators using the ```AppBar.brightness = Brightness.light```. However, no matter how one attempts to change the color on the physical device it always displays in white. I've attempted to set the task bar color using the method outlined in the docs (AppBar.brightness = Brightness.light). I've attempted to simply set the theme of the app to a color which uses a dark accent color by trying ThemeData.primarySwatch = Colors.amber and still the physical device only displays in white. I've also tried using the SystemOverlay method which also fails.

1. Create a new flutter project
2. Set the AppBar.brightness to Brightness.light

```
    return Scaffold(
      appBar: AppBar(
        brightness: Brightness.light,
        title: Text(widget.title),
      )...
```

**Target Platform: iOS **
**Target OS version/browser: iOS 13.1.3**
**Devices: iPhone X**

## Logs

```
#0      throwToolExit (package:flutter_tools/src/base/common.dart:28:3)
#1      RunCommand.validateCommand (package:flutter_tools/src/commands/run.dart:287:7)
<asynchronous suspension>
#2      FlutterCommand.verifyThenRunCommand
(package:flutter_tools/src/runner/flutter_command.dart:532:11)
<asynchronous suspension>
#3      FlutterCommand.run.<anonymous closure>
(package:flutter_tools/src/runner/flutter_command.dart:457:33)
<asynchronous suspension>
#4      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:157:29)
<asynchronous suspension>
#5      _rootRun (dart:async/zone.dart:1124:13)
#6      _CustomZone.run (dart:async/zone.dart:1021:19)
#7      _runZoned (dart:async/zone.dart:1516:10)
#8      runZoned (dart:async/zone.dart:1463:12)
#9      AppContext.run (package:flutter_tools/src/base/context.dart:156:18)
<asynchronous suspension>
#10     FlutterCommand.run (package:flutter_tools/src/runner/flutter_command.dart:446:20)
#11     CommandRunner.runCommand (package:args/command_runner.dart:197:27)
<asynchronous suspension>
#12     FlutterCommandRunner.runCommand.<anonymous closure>
(package:flutter_tools/src/runner/flutter_command_runner.dart:416:21)
<asynchronous suspension>
#13     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:157:29)
<asynchronous suspension>
#14     _rootRun (dart:async/zone.dart:1124:13)
#15     _CustomZone.run (dart:async/zone.dart:1021:19)
#16     _runZoned (dart:async/zone.dart:1516:10)
#17     runZoned (dart:async/zone.dart:1463:12)
#18     AppContext.run (package:flutter_tools/src/base/context.dart:156:18)
<asynchronous suspension>
#19     FlutterCommandRunner.runCommand
(package:flutter_tools/src/runner/flutter_command_runner.dart:367:19)
<asynchronous suspension>
#20     CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:112:25)
#21     new Future.sync (dart:async/future.dart:222:31)
#22     CommandRunner.run (package:args/command_runner.dart:112:14)
#23     FlutterCommandRunner.run
(package:flutter_tools/src/runner/flutter_command_runner.dart:251:18)
#24     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:63:22)
<asynchronous suspension>
#25     _rootRun (dart:async/zone.dart:1124:13)
#26     _CustomZone.run (dart:async/zone.dart:1021:19)
#27     _runZoned (dart:async/zone.dart:1516:10)
#28     runZoned (dart:async/zone.dart:1500:12)
#29     run.<anonymous closure> (package:flutter_tools/runner.dart:61:18)
<asynchronous suspension>
#30     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:157:29)
<asynchronous suspension>
#31     _rootRun (dart:async/zone.dart:1124:13)
#32     _CustomZone.run (dart:async/zone.dart:1021:19)
#33     _runZoned (dart:async/zone.dart:1516:10)
#34     runZoned (dart:async/zone.dart:1463:12)
#35     AppContext.run (package:flutter_tools/src/base/context.dart:156:18)
<asynchronous suspension>
#36     runInContext (package:flutter_tools/src/context_runner.dart:64:24)
<asynchronous suspension>
#37     run (package:flutter_tools/runner.dart:50:10)
#38     main (package:flutter_tools/executable.dart:65:9)
<asynchronous suspension>
#39     main
(file:///Users/jon/Desktop/dev.nosync/flutter/packages/flutter_tools/bin/flutter_tools.dart:8:3)
#40     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:303:32)
#41     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:12)
```

```
Analyzing appbartest...                                                 

   info • Avoid empty statements • lib/main.dart:63:5 • empty_statements
```

```
[✓] Flutter (Channel master, v1.10.15-pre.368, on Mac OS X 10.15.1 19B88, locale en-US)
    • Flutter version 1.10.15-pre.368 at /Users/jon/Desktop/dev.nosync/flutter
    • Framework revision 3cd8c3142c (13 hours ago), 2019-10-31 19:35:52 -0700
    • Engine revision 8ea19b1c76
    • Dart version 2.6.0 (build 2.6.0-dev.8.2 bbe2ac28c9)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/jon/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.2, Build version 11B52
    • CocoaPods version 1.8.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 40.1.2
    • Dart plugin version 191.8423
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] VS Code (version 1.39.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.5.1

[✓] Connected device (4 available)
    • Jon's iPhone      • a43c511942e827a5caf34b8aee15bfd074cb356b • ios            • iOS 13.1.3
    • iPhone 11 Pro Max • 6A1F9F24-FF8A-4B71-8352-1F307EEE6BC1     • ios            •
      com.apple.CoreSimulator.SimRuntime.iOS-13-2 (simulator)
    • Chrome            • chrome                                   • web-javascript • Google
      Chrome 78.0.3904.87
    • Web Server        • web-server                               • web-javascript • Flutter
      Tools

• No issues found!
```

**Comment by iapicca** [comment]
Hi @jcairo 
does this [solution](https://github.com/flutter/flutter/issues/26578#issuecomment-468320201) solve your issue?

**Comment by jcairo** [comment]
Hi. Thanks for your response.

I'm not seeing how this is different from what I've implemented. 

To me it looks like he is saying to set the brightness property on the AppBar which is what i've already done.

**Comment by LongCatIsLooong** [comment]
Is this a dup of https://github.com/flutter/flutter/issues/41067?

**Comment by jcairo** [comment]
> Is this a dup of #41067?

Yup. Didn't see this. Still an issue, not sure why it was closed.
