### ISSUE TITLE
flutter build apk: permission denied error

### ISSUE THREAD

**Issue by m1narul** [flutter/flutter#44041]
Flutter crash report; please file at https://github.com/flutter/flutter/issues.

## command

flutter --no-color build apk

## exception

ProcessException: ProcessException: Permission denied
  Command: /home/meaww/flutter/.pub-cache/git/plugins_flutter_file_picker-c5e23c434d3ee4a3bdf6c59f90680e4b49fae076/android/gradlew -I=/home/meaww/flutter/packages/flutter_tools/gradle/aar_init_script.gradle -Pflutter-root=/home/meaww/flutter -Poutput-dir=/home/meaww/Projects/Cure Mantra/curemantra_doctor_android/build/app -Pis-plugin=true -Ptarget-platform=android-arm,android-arm64,android-x64 assembleAarRelease

```
#0      _DefaultProcessUtils.run (package:flutter_tools/src/base/process.dart:266:37)
<asynchronous suspension>
#1      buildGradleAar (package:flutter_tools/src/android/gradle.dart:522:33)
<asynchronous suspension>
#2      buildPluginsAsAar (package:flutter_tools/src/android/gradle.dart:629:13)
<asynchronous suspension>
#3      buildGradleApp (package:flutter_tools/src/android/gradle.dart:255:11)
#4      _AsyncAwaitCompleter.start (dart:async-patch/async_patch.dart:43:6)
#5      buildGradleApp (package:flutter_tools/src/android/gradle.dart:217:28)
#6      buildGradleApp (package:flutter_tools/src/android/gradle.dart:395:19)
#7      _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:71:64)
#8      _rootRunUnary (dart:async/zone.dart:1132:38)
#9      _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#10     _FutureListener.handleValue (dart:async/future_impl.dart:137:18)
#11     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:678:45)
#12     Future._propagateToListeners (dart:async/future_impl.dart:707:32)
#13     Future._completeWithValue (dart:async/future_impl.dart:522:5)
#14     Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:552:7)
#15     _rootRun (dart:async/zone.dart:1124:13)
#16     _CustomZone.run (dart:async/zone.dart:1021:19)
#17     _CustomZone.runGuarded (dart:async/zone.dart:923:7)
#18     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:963:23)
#19     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#20     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#21     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:116:13)
#22     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:173:5)
```

## flutter doctor

```
[✓] Flutter (Channel master, v1.10.15-pre.368, on Linux, locale en_IN)
    • Flutter version 1.10.15-pre.368 at /home/meaww/flutter
    • Framework revision 3cd8c3142c (31 hours ago), 2019-10-31 19:35:52 -0700
    • Engine revision 8ea19b1c76
    • Dart version 2.6.0 (build 2.6.0-dev.8.2 bbe2ac28c9)

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /home/meaww/Android/Sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /snap/android-studio/80/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Android Studio (version 3.5)
    • Android Studio at /snap/android-studio/80/android-studio
    • Flutter plugin version 40.2.2
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] Connected device (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 9 (API 28) (emulator)

• No issues found!
```

**Comment by iapicca** [comment]
Hi @m1narul 
the error you are reporting appear to be related to a 3rd party [plugin](https://pub.dev/packages/file_picker)
If so please consider to open an issue in the dedicated github [page](https://github.com/miguelpruivo/flutter_file_picker/issues);
if you are experiencing the same issue without that plugin, 
please provide your `flutter doctor -v`
and your your `flutter build --verbose`?
Thank you

**Comment by jonahwilliams** [comment]
It appears that building plugins as AARs requires executable permission on contents in the pub-cache. That isn't necessarily the case, so the tool will need to gracefully handle only given write permissions.

cc @blasten

**Comment by blasten** [comment]
@jonahwilliams that isn't the case anymore. Plugins are built in the app's `build/` directory.

**Comment by jonahwilliams** [comment]
`/home/meaww/flutter/.pub-cache/git/plugins_flutter_file_picker-c5e23c434d3ee4a3bdf6c59f90680e4b49fae076/android/gradlew` looks like it is invoking the gradlewrapper in the pub cache

**Comment by yannbarrault** [comment]
@blasten we have the same pb. Is it related to a plugin ? It could be file_picker plugin in our case...

**Comment by jonahwilliams** [comment]
We're tracking project permission issues in https://github.com/flutter/flutter/issues/50880
