### ISSUE TITLE
Gradle task bundleRelease failed with exit code 1

### ISSUE THREAD

**Issue by ShadiOssaili** [flutter/flutter#44082]
can't build my app bundle, I've tried flutter clean and I upgraded my flutter through the master channel with no luck.

```
Compiler message:
/E:/flutter/.pub-cache/hosted/pub.dartlang.org/cached_network_image-1.1.2+1/lib/src/cached_network_image_provider.dart:53:24: Error: The method 'CachedNetworkImageProvider.load' has fewer positional arguments than those of overridden method 'ImageProvider.load'.
  ImageStreamCompleter load(CachedNetworkImageProvider key) {
                       ^
/E:/flutter/packages/flutter/lib/src/painting/image_provider.dart:403:24: Context: This is the overridden method ('load').
  ImageStreamCompleter load(T key, DecoderCallback decode);
                       ^
/E:/flutter/.pub-cache/hosted/pub.dartlang.org/cached_network_image-1.1.2+1/lib/src/scaled_file_image.dart:45:24: Error: The method 'ScaledFileImage.load' has fewer positional arguments 
than those of overridden method 'ImageProvider.load'.
  ImageStreamCompleter load(ScaledFileImage key) {
                       ^
/E:/flutter/packages/flutter/lib/src/painting/image_provider.dart:403:24: Context: This is the overridden method ('load').
  ImageStreamCompleter load(T key, DecoderCallback decode);
                       ^
Exception: Errors during snapshot creation: null                        
#0      KernelSnapshot.build (package:flutter_tools/src/build_system/targets/dart.dart:221:7)
<asynchronous suspension>
#1      _BuildInstance._invokeInternal (package:flutter_tools/src/build_system/build_system.dart:526:25)
<asynchronous suspension>
#2      _BuildInstance.invokeTarget.<anonymous closure> (package:flutter_tools/src/build_system/build_system.dart:481:35)
#3      new Future.sync (dart:async/future.dart:222:31)
#4      AsyncMemoizer.runOnce (package:async/src/async_memoizer.dart:43:45)
#5      _BuildInstance.invokeTarget (package:flutter_tools/src/build_system/build_system.dart:481:21)
<asynchronous suspension>
<asynchronous suspension>
<asynchronous suspension>
#6      BuildSystem.build (package:flutter_tools/src/build_system/build_system.dart:419:36)
<asynchronous suspension>
#7      BuildAotCommand._buildWithAssemble (package:flutter_tools/src/commands/build_aot.dart:260:50)
<asynchronous suspension>
#8      BuildAotCommand.runCommand (package:flutter_tools/src/commands/build_aot.dart:86:13)
<asynchronous suspension>
#9      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:557:18)
<asynchronous suspension>
#10     FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:457:33)
<asynchronous suspension>
#11     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:157:29)
<asynchronous suspension>
#12     _rootRun (dart:async/zone.dart:1124:13)
#13     _CustomZone.run (dart:async/zone.dart:1021:19)
#14     _runZoned (dart:async/zone.dart:1516:10)
#15     runZoned (dart:async/zone.dart:1463:12)
#16     AppContext.run (package:flutter_tools/src/base/context.dart:156:18)
<asynchronous suspension>
#17     FlutterCommand.run (package:flutter_tools/src/runner/flutter_command.dart:446:20)
#18     CommandRunner.runCommand (package:args/command_runner.dart:197:27)
<asynchronous suspension>
#19     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:416:21)
<asynchronous suspension>
#20     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:157:29)
<asynchronous suspension>
#21     _rootRun (dart:async/zone.dart:1124:13)
#22     _CustomZone.run (dart:async/zone.dart:1021:19)
#23     _runZoned (dart:async/zone.dart:1516:10)
#24     runZoned (dart:async/zone.dart:1463:12)
#25     AppContext.run (package:flutter_tools/src/base/context.dart:156:18)
<asynchronous suspension>
#26     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:367:19)
<asynchronous suspension>
#27     CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:112:25)
#28     new Future.sync (dart:async/future.dart:222:31)
#29     CommandRunner.run (package:args/command_runner.dart:112:14)     
#30     FlutterCommandRunner.run (package:flutter_tools/src/runner/flutter_command_runner.dart:251:18)
#31     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:63:22)
<asynchronous suspension>
#32     _rootRun (dart:async/zone.dart:1124:13)
#33     _CustomZone.run (dart:async/zone.dart:1021:19)
#34     _runZoned (dart:async/zone.dart:1516:10)
#35     runZoned (dart:async/zone.dart:1500:12)                         
#36     run.<anonymous closure> (package:flutter_tools/runner.dart:61:18)
<asynchronous suspension>
#37     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:157:29)
<asynchronous suspension>
#38     _rootRun (dart:async/zone.dart:1124:13)
#39     _CustomZone.run (dart:async/zone.dart:1021:19)
#40     _runZoned (dart:async/zone.dart:1516:10)
#41     runZoned (dart:async/zone.dart:1463:12)
#42     AppContext.run (package:flutter_tools/src/base/context.dart:156:18)
<asynchronous suspension>
#43     runInContext (package:flutter_tools/src/context_runner.dart:64:24)
<asynchronous suspension>
#44     run (package:flutter_tools/runner.dart:50:10)
#45     main (package:flutter_tools/executable.dart:65:9)
<asynchronous suspension>
#46     main (file:///E:/flutter/packages/flutter_tools/bin/flutter_tools.dart:8:3)
#47     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:303:32)
#48     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:12)

Failed to build aot.

FAILURE: Build failed with an exception.

* Where:
Script 'E:\flutter\packages\flutter_tools\gradle\flutter.gradle' line: 759

* What went wrong:
Execution failed for task ':app:compileFlutterBuildReleaseArm'.
> Process 'command 'E:\flutter\bin\flutter.bat'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 15s
Running Gradle task 'bundleRelease'...
Running Gradle task 'bundleRelease'... Done                        17.9s
Gradle task bundleRelease failed with exit code 1

```

**Comment by fauzipadlaw** [comment]
@ShadiOssaili i think you need to upgrade your `cached_network_image` to 2.0.0-rc 
https://github.com/renefloor/flutter_cached_network_image/issues/272

**Comment by iapicca** [comment]
Hi @ShadiOssaili 
I hope the proposed solution fix the issue,
if it doesn't please consider opening this issue
on the github page of the related 3rd party [plugin](https://pub.dev/packages/cached_network_image).
Closing, as this isn't an issue with Flutter itself,
if you disagree please write in the comments and I will reopen it
Thank you

**Comment by ShadiOssaili** [comment]
@fauzipadlaw  , it solved ! , thank you
