### ISSUE TITLE
http request return statusCode 200 in test function, but return statusCode 400 in testWidgets function 

### ISSUE THREAD

**Issue by tbm98** [flutter/flutter#44099]
in testWidgets function
```
Testing started at 17:48 ...
/home/tbm98/Documents/flutter-sdk/flutter/bin/flutter --no-color test --machine --plain-name "parses item.json over a network" test/hn_app.dart
══╡ EXCEPTION CAUGHT BY FLUTTER TEST FRAMEWORK ╞════════════════════════════════════════════════════
The following TestFailure object was thrown running a test:
  Expected: <0>
  Actual: <400>

When the exception was thrown, this was the stack:
#4      main.<anonymous closure> (file:///home/tbm98/Documents/mobile-projects/student-social/test/hn_app.dart:11:5)
<asynchronous suspension>
#5      testWidgets.<anonymous closure>.<anonymous closure> (package:flutter_test/src/widget_tester.dart:119:25)
<asynchronous suspension>
#6      TestWidgetsFlutterBinding._runTestBody (package:flutter_test/src/binding.dart:648:19)
<asynchronous suspension>
#9      TestWidgetsFlutterBinding._runTest (package:flutter_test/src/binding.dart:631:14)
#10     AutomatedTestWidgetsFlutterBinding.runTest.<anonymous closure> (package:flutter_test/src/binding.dart:1016:24)
#16     AutomatedTestWidgetsFlutterBinding.runTest (package:flutter_test/src/binding.dart:1013:15)
#17     testWidgets.<anonymous closure> (package:flutter_test/src/widget_tester.dart:116:22)
#18     Declarer.test.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:test_api/src/backend/declarer.dart:168:27)
<asynchronous suspension>
#19     Invoker.waitForOutstandingCallbacks.<anonymous closure> (package:test_api/src/backend/invoker.dart:250:15)
<asynchronous suspension>
#24     Invoker.waitForOutstandingCallbacks (package:test_api/src/backend/invoker.dart:247:5)
#25     Declarer.test.<anonymous closure>.<anonymous closure> (package:test_api/src/backend/declarer.dart:166:33)
#30     Declarer.test.<anonymous closure> (package:test_api/src/backend/declarer.dart:165:13)
<asynchronous suspension>
#31     Invoker._onRun.<anonymous closure>.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:test_api/src/backend/invoker.dart:400:25)
<asynchronous suspension>
#45     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:382:19)
#46     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:416:5)
#47     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:12)
(elided 28 frames from class _FakeAsync, package dart:async, package dart:async-patch, and package stack_trace)

This was caught by the test expectation on the following line:
  file:///home/tbm98/Documents/mobile-projects/student-social/test/hn_app.dart line 11
The test description was:
  parses item.json over a network
════════════════════════════════════════════════════════════════════════════════════════════════════

Test failed. See exception logs above.
The test description was: parses item.json over a network


```

in test function
```
Testing started at 17:54 ...
/home/tbm98/Documents/flutter-sdk/flutter/bin/flutter --no-color test --machine --plain-name "parses item.json over a network" test/hn_app.dart
package:test_api                                   expect
package:flutter_test/src/widget_tester.dart 229:3  expect
test/hn_app.dart 11:5                              main.<fn>

Expected: <0>
  Actual: <200>

```

**Comment by iapicca** [comment]
Hi @tbm98 
can you please provide your `flutter doctor -v`?
Also, to better address the issue, would be helpful
if you could post a self contained app on github
or the steps to reproduce it.
Thank you

**Comment by tbm98** [comment]
doctor -v
```
[✓] Flutter (Channel stable, v1.9.1+hotfix.6, on Linux, locale en_US.UTF-8)
    • Flutter version 1.9.1+hotfix.6 at
      /home/tbm98/Documents/flutter-sdk/flutter
    • Framework revision 68587a0916 (8 weeks ago), 2019-09-13 19:46:58 -0700
    • Engine revision b863200c37
    • Dart version 2.5.0

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /home/tbm98/Android/Sdk
    • Android NDK location not configured (optional; useful for native profiling
      support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /home/tbm98/Documents/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Android Studio (version 3.5)
    • Android Studio at /home/tbm98/Documents/android-studio
    • Flutter plugin version 41.0.2
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build
      1.8.0_202-release-1483-b49-5587405)

[!] IntelliJ IDEA Community Edition (version 2019.2)
    • IntelliJ at /home/tbm98/Documents/idea-IC-192.6817.14
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.dev/intellij-setup/#installing-the-plugins

[!] VS Code (version 1.39.2)
    • VS Code at /usr/share/code
    ✗ Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[!] Connected device
    ! No devices available

! Doctor found issues in 3 categories.
```
any file contain testWidgets , it make all test to be fail when request http(status code = 400).
```
void main() {

  test('testcase 1', () async {
    final url = 'https://hacker-news.firebaseio.com/v0/beststories.json';
    final res = await http.get(url);
    expect(res.statusCode, 0);
  });

  testWidgets("parses item.json over a network", (WidgetTester tester) async {
    final url = 'https://hacker-news.firebaseio.com/v0/beststories.json';
    final res = await http.get(url);
    expect(res.statusCode, 0);
  });

  test('testcase 3', () async {
    final url = 'https://hacker-news.firebaseio.com/v0/beststories.json';
    final res = await http.get(url);
    expect(res.statusCode, 0);
  });
}
```
above this code , all of them got `statusCode = 400`. but if I remove `testWidgets` function => all `test` function worked fine with `statusCode = 200`.

**Comment by VladyslavBondarenko** [comment]
Possibly related to https://github.com/flutter/flutter/issues/21870

**Comment by goderbauer** [comment]
This is working as indented, but we should document this better and provide better exceptions. This is covered by issue https://github.com/flutter/flutter/pull/35318. Please follow along there for updates.
