### ISSUE TITLE
Using Video_player to report an error in listview

### ISSUE THREAD

**Issue by Tumbler0809** [flutter/flutter#44091]
<details>
  <summary>LOGS</summary>

```
E/ExoPlayerImplInternal(20546): Source error.
E/ExoPlayerImplInternal(20546): com.google.android.exoplayer2.upstream.HttpDataSource$HttpDataSourceException: Unable to connect to http://www.sampl
e-videos.com/video123/mp4/720/big_buck_bunny_720p_20mb.mp4
E/ExoPlayerImplInternal(20546):         at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.open(DefaultHttpDataSource.java:281)
E/ExoPlayerImplInternal(20546):         at com.google.android.exoplayer2.upstream.StatsDataSource.open(StatsDataSource.java:83)
E/ExoPlayerImplInternal(20546):         at com.google.android.exoplayer2.source.ExtractorMediaPeriod$ExtractingLoadable.load(ExtractorMediaPeriod.ja
va:885)
E/ExoPlayerImplInternal(20546):         at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:381)
E/ExoPlayerImplInternal(20546):         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
E/ExoPlayerImplInternal(20546):         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
E/ExoPlayerImplInternal(20546):         at java.lang.Thread.run(Thread.java:764)
E/ExoPlayerImplInternal(20546): Caused by: java.net.SocketTimeoutException: timeout
E/ExoPlayerImplInternal(20546):         at com.android.okhttp.okio.Okio$3.newTimeoutException(Okio.java:212)
E/ExoPlayerImplInternal(20546):         at com.android.okhttp.okio.AsyncTimeout.exit(AsyncTimeout.java:261)
E/ExoPlayerImplInternal(20546):         at com.android.okhttp.okio.AsyncTimeout$2.read(AsyncTimeout.java:215)
E/ExoPlayerImplInternal(20546):         at com.android.okhttp.okio.RealBufferedSource.indexOf(RealBufferedSource.java:306)
E/ExoPlayerImplInternal(20546):         at com.android.okhttp.okio.RealBufferedSource.indexOf(RealBufferedSource.java:300)
E/ExoPlayerImplInternal(20546):         at com.android.okhttp.okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.java:196)
E/ExoPlayerImplInternal(20546):         at com.android.okhttp.internal.http.Http1xStream.readResponse(Http1xStream.java:186)
E/ExoPlayerImplInternal(20546):         at com.android.okhttp.internal.http.Http1xStream.readResponseHeaders(Http1xStream.java:127)
E/ExoPlayerImplInternal(20546):         at com.android.okhttp.internal.http.HttpEngine.readNetworkResponse(HttpEngine.java:737)
E/ExoPlayerImplInternal(20546):         at com.android.okhttp.internal.http.HttpEngine.readResponse(HttpEngine.java:609)
E/ExoPlayerImplInternal(20546):         at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:471)
E/ExoPlayerImplInternal(20546):         at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:407)
E/ExoPlayerImplInternal(20546):         at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponseCode(HttpURLConnectionImpl.java:538)
E/ExoPlayerImplInternal(20546):         at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.makeConnection(DefaultHttpDataSource.java:44
6)
E/ExoPlayerImplInternal(20546):         at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.open(DefaultHttpDataSource.java:279)
E/ExoPlayerImplInternal(20546):         ... 6 more
E/ExoPlayerImplInternal(20546): Caused by: java.net.SocketException: Socket closed
E/ExoPlayerImplInternal(20546):         at java.net.SocketInputStream.read(SocketInputStream.java:209)
E/ExoPlayerImplInternal(20546):         at java.net.SocketInputStream.read(SocketInputStream.java:144)
E/ExoPlayerImplInternal(20546):         at com.android.okhttp.okio.Okio$2.read(Okio.java:136)
E/ExoPlayerImplInternal(20546):         at com.android.okhttp.okio.AsyncTimeout$2.read(AsyncTimeout.java:211)
E/ExoPlayerImplInternal(20546):         ... 18 more
E/ExoPlayerImplInternal(20546): Source error.
E/ExoPlayerImplInternal(20546): com.google.android.exoplayer2.upstream.HttpDataSource$HttpDataSourceException: Unable to connect to http://www.sampl
e-videos.com/video123/mp4/720/big_buck_bunny_720p_20mb.mp4
E/ExoPlayerImplInternal(20546):         at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.open(DefaultHttpDataSource.java:281)
E/ExoPlayerImplInternal(20546):         at com.google.android.exoplayer2.upstream.StatsDataSource.open(StatsDataSource.java:83)
E/ExoPlayerImplInternal(20546):         at com.google.android.exoplayer2.source.ExtractorMediaPeriod$ExtractingLoadable.load(ExtractorMediaPeriod.ja
va:885)
E/ExoPlayerImplInternal(20546):         at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:381)
E/ExoPlayerImplInternal(20546):         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
E/ExoPlayerImplInternal(20546):         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
E/ExoPlayerImplInternal(20546):         at java.lang.Thread.run(Thread.java:764)
E/ExoPlayerImplInternal(20546): Caused by: java.net.SocketTimeoutException: timeout
E/ExoPlayerImplInternal(20546):         at com.android.okhttp.okio.Okio$3.newTimeoutException(Okio.java:212)
E/ExoPlayerImplInternal(20546):         at com.android.okhttp.okio.AsyncTimeout.exit(AsyncTimeout.java:261)
E/ExoPlayerImplInternal(20546):         at com.android.okhttp.okio.AsyncTimeout$2.read(AsyncTimeout.java:215)
E/ExoPlayerImplInternal(20546):         at com.android.okhttp.okio.RealBufferedSource.indexOf(RealBufferedSource.java:306)
E/ExoPlayerImplInternal(20546):         at com.android.okhttp.okio.RealBufferedSource.indexOf(RealBufferedSource.java:300)
E/ExoPlayerImplInternal(20546):         at com.android.okhttp.okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.java:196)
E/ExoPlayerImplInternal(20546):         at com.android.okhttp.internal.http.Http1xStream.readResponse(Http1xStream.java:186)
E/ExoPlayerImplInternal(20546):         at com.android.okhttp.internal.http.Http1xStream.readResponseHeaders(Http1xStream.java:127)
E/ExoPlayerImplInternal(20546):         at com.android.okhttp.internal.http.HttpEngine.readNetworkResponse(HttpEngine.java:737)
E/ExoPlayerImplInternal(20546):         at com.android.okhttp.internal.http.HttpEngine.readResponse(HttpEngine.java:609)
E/ExoPlayerImplInternal(20546):         at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:471)
E/ExoPlayerImplInternal(20546):         at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:407)
E/ExoPlayerImplInternal(20546):         at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponseCode(HttpURLConnectionImpl.java:538)
E/ExoPlayerImplInternal(20546):         at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.makeConnection(DefaultHttpDataSource.java:44
6)
E/ExoPlayerImplInternal(20546):         at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.open(DefaultHttpDataSource.java:279)
E/ExoPlayerImplInternal(20546):         ... 6 more
E/ExoPlayerImplInternal(20546): Caused by: java.net.SocketException: Socket closed
E/ExoPlayerImplInternal(20546):         at java.net.SocketInputStream.read(SocketInputStream.java:209)
E/ExoPlayerImplInternal(20546):         at java.net.SocketInputStream.read(SocketInputStream.java:144)
E/ExoPlayerImplInternal(20546):         at com.android.okhttp.okio.Okio$2.read(Okio.java:136)
E/ExoPlayerImplInternal(20546):         at com.android.okhttp.okio.AsyncTimeout$2.read(AsyncTimeout.java:211)
E/ExoPlayerImplInternal(20546):         ... 18 more
D/SurfaceUtils(20546): disconnecting from surface 0x7948c9d010, reason disconnectFromSurface


```

</details>

**Comment by Tumbler0809** [comment]
video_player: ^0.10.2+5

**Comment by Tumbler0809** [comment]
import 'package:video_player/video_player.dart';
import 'package:flutter/material.dart';


class VideoApp extends StatefulWidget {
  final String url;

  VideoApp(this.url);

  @override
  _VideoAppState createState() => _VideoAppState();
}

class _VideoAppState extends State<VideoApp> {
  VideoPlayerController _controller;

  @override
  void initState() {
    super.initState();
    _controller = VideoPlayerController.network(
        widget.url)
      ..initialize().then((_) {
        // Ensure the first frame is shown after the video is initialized, even before the play button has been pressed.
        setState(() {});
      });
  }

  @override
  Widget build(BuildContext context) {
    return AspectRatio(
      aspectRatio: 279.0/139.0,
      child: Container(
        decoration: BoxDecoration(
          color: Color(0xFF9C9C9C),
          borderRadius: BorderRadius.all(Radius.circular(7)),
        ),
        child:Stack(
          alignment:AlignmentDirectional.center,
          children: <Widget>[
            _controller.value.initialized
                ? AspectRatio(
              aspectRatio: _controller.value.aspectRatio,
              child: VideoPlayer(_controller),
            )
                : Container(),
            FlatButton(
              child: Image.asset(_controller.value.isPlaying ? "images/btn_stop.png" :"images/btn_play.png",width: 56,height: 56,),
              onPressed: (){
                setState(() {
                  _controller.value.isPlaying
                      ? _controller.pause()
                      : _controller.play();
                });
              },
            )
          ],
        ),
      ),
    ) ;
  }

  @override
  void dispose() {
    super.dispose();
    _controller.dispose();
  }
}

**Comment by iapicca** [comment]
Hi @Tumbler0809 
I've noticed from your logs that you are using the [url ](http://www.sampl
e-videos.com/video123/mp4/720/big_buck_bunny_720p_20mb.mp4)suggested in the [sample app](https://pub.dev/packages/video_player#-readme-tab-), 
as you can see that link doesn't work anymore.
You might want to try with a different url,
let me know if this fix the issue?
Thank you

**Comment by Tumbler0809** [comment]
Thank you, it is indeed the reason for the url of the video.
