### ISSUE TITLE
BoxEdge - Unsupported operation: Infinity or NaN toInt

### ISSUE THREAD

**Issue by bartektartanus** [flutter/flutter#44114]
After upgrading flutter to v1.9.1+hotfix.6 one of my user reported that app is not working (previous version was working). App does not load, only shows black screen. I've found him in firebase crashlytics and this is the stacktrace:
```
Non-fatal Exception: java.lang.Exception: Unsupported operation: Infinity or NaN toInt
       at _BoxEdge.compareTo(semantics.dart:2221)
       at ._childrenInDefaultOrder(semantics.dart:2416)
       at SemanticsNode._childrenInTraversalOrder(semantics.dart:2004)
       at SemanticsNode._addToUpdate(semantics.dart:1944)
       at SemanticsOwner.sendSemanticsUpdate(semantics.dart:2545)
       at PipelineOwner.flushSemantics(object.dart:1039)
       at RendererBinding.drawFrame(binding.dart:345)
       at WidgetsBinding.drawFrame(binding.dart:761)
       at RendererBinding._handlePersistentFrameCallback(binding.dart:280)
       at SchedulerBinding._invokeFrameCallback(binding.dart:1033)
       at SchedulerBinding.handleDrawFrame(binding.dart:975)
       at SchedulerBinding._handleDrawFrame(binding.dart:891)
```

Android 9, LG Q60.

**Comment by iapicca** [comment]
Hi @bartektartanus 
can you please provide your `flutter doctor -v`
and your `flutter run --verbose`?
Also, to better address the issue, would be helpful
if you could post a self contained app on github
or the steps to reproduce it.
Thank you

**Comment by iapicca** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact descriptions what happens, logs and the output of 'flutter doctor -v'  please.
All system setups can be slightly different so its always better to open new issues and reference related issues.

**Comment by bartektartanus** [comment]
Sorry for the late reply! I've upgraded flutter to 1.10.7 and error disappeared (hopefully for good).

**Comment by stevenspiel** [comment]
One of my users experienced this on stable `v1.12.13+hotfix.8` with iPhone 11

```
Error: 
Unsupported operation: Infinity or NaN toInt
Stack trace: 
#0   _Double.toInt (dart:core-patch/double.dart:194)
#1   _BoxEdge.compareTo (package:flutter/src/semantics/semantics.dart:2327)
#2   Comparable.compare (dart:core/comparable.dart:95)
#3   ListMixin._compareAny (dart:collection/list.dart:347)
#4   Sort._insertionSort (dart:_internal/sort.dart:71)
#5   Sort._doSort (dart:_internal/sort.dart:60)
#6   Sort.sort (dart:_internal/sort.dart:35)
#7   ListMixin.sort (dart:collection/list.dart:341)
#8   _childrenInDefaultOrder (package:flutter/src/semantics/semantics.dart:2522)
#9   SemanticsNode._childrenInTraversalOrder (package:flutter/src/semantics/semantics.dart:2108)
#10   SemanticsNode._addToUpdate (package:flutter/src/semantics/semantics.dart:2046)
#11   SemanticsOwner.sendSemanticsUpdate (package:flutter/src/semantics/semantics.dart:2650)
#12   PipelineOwner.flushSemantics (package:flutter/src/rendering/object.dart:1042)
#13   RendererBinding.drawFrame (package:flutter/src/rendering/binding.dart:348)
#14   WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:774)
#15   RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:283)
#16   SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1102)
#17   SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1041)
#18   SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:957)
#19   _rootRun (dart:async/zone.dart:1126)
#20   _CustomZone.run (dart:async/zone.dart:1023)
#21   _CustomZone.runGuarded (dart:async/zone.dart:925)
#22   _invoke (dart:ui/hooks.dart:259)
#23   _drawFrame (dart:ui/hooks.dart:217)
```

**Comment by passsy** [comment]
Still seeing this in `Flutter 1.21.0-9.2.pre • channel beta`
