### ISSUE TITLE
Crash in example app when migrating crashlytics to new Plugins API

### ISSUE THREAD

**Issue by gaaclarke** [flutter/flutter#44131]
Reproduction steps:
1) Run upgrade script [found here](https://github.com/gaaclarke/upgrade_flutter_plugin) on the repository [found here](https://github.com/FirebaseExtended/flutterfire/tree/master/packages/firebase_crashlytics).  
2) Run the example app on an android phone

Crash log:
```
11-04 12:49:57.831 17830 17830 D FlutterActivityAndFragmentDelegate: Attaching FlutterEngine to the Activity that owns this Fragment.
11-04 12:49:57.843 17830 17830 E shlyticsexampl: Invalid ID 0x00000000.
11-04 12:49:57.844 17830 17830 D AndroidRuntime: Shutting down VM
11-04 12:49:57.845 17830 17830 E AndroidRuntime: FATAL EXCEPTION: main
11-04 12:49:57.845 17830 17830 E AndroidRuntime: Process: io.flutter.plugins.firebase.crashlytics.firebasecrashlyticsexample, PID: 17830
11-04 12:49:57.845 17830 17830 E AndroidRuntime: java.lang.RuntimeException: Unable to start activity ComponentInfo{io.flutter.plugins.firebase.crashlytics.firebasecrashlyticsexample/io.flutter.plugins.firebase.crashlytics.firebasecrashlyticsexample.MainActivity}: android.content.res.Resources$NotFoundException: Resource ID #0x0
11-04 12:49:57.845 17830 17830 E AndroidRuntime: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2946)
11-04 12:49:57.845 17830 17830 E AndroidRuntime: 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3081)
11-04 12:49:57.845 17830 17830 E AndroidRuntime: 	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
11-04 12:49:57.845 17830 17830 E AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
11-04 12:49:57.845 17830 17830 E AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
11-04 12:49:57.845 17830 17830 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1831)
11-04 12:49:57.845 17830 17830 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:106)
11-04 12:49:57.845 17830 17830 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:201)
11-04 12:49:57.845 17830 17830 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6806)
11-04 12:49:57.845 17830 17830 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
11-04 12:49:57.845 17830 17830 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
11-04 12:49:57.845 17830 17830 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:873)
11-04 12:49:57.845 17830 17830 E AndroidRuntime: Caused by: android.content.res.Resources$NotFoundException: Resource ID #0x0
11-04 12:49:57.845 17830 17830 E AndroidRuntime: 	at android.content.res.ResourcesImpl.getValueForDensity(ResourcesImpl.java:225)
11-04 12:49:57.845 17830 17830 E AndroidRuntime: 	at android.content.res.Resources.getDrawableForDensity(Resources.java:901)
11-04 12:49:57.845 17830 17830 E AndroidRuntime: 	at android.content.res.Resources.getDrawable(Resources.java:841)
11-04 12:49:57.845 17830 17830 E AndroidRuntime: 	at io.flutter.embedding.android.FlutterActivity.getSplashScreenFromManifest(FlutterActivity.java:483)
11-04 12:49:57.845 17830 17830 E AndroidRuntime: 	at io.flutter.embedding.android.FlutterActivity.provideSplashScreen(FlutterActivity.java:456)
11-04 12:49:57.845 17830 17830 E AndroidRuntime: 	at io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.onCreateView(FlutterActivityAndFragmentDelegate.java:246)
11-04 12:49:57.845 17830 17830 E AndroidRuntime: 	at io.flutter.embedding.android.FlutterActivity.createFlutterView(FlutterActivity.java:512)
11-04 12:49:57.845 17830 17830 E AndroidRuntime: 	at io.flutter.embedding.android.FlutterActivity.onCreate(FlutterActivity.java:405)
11-04 12:49:57.845 17830 17830 E AndroidRuntime: 	at android.app.Activity.performCreate(Activity.java:7224)
11-04 12:49:57.845 17830 17830 E AndroidRuntime: 	at android.app.Activity.performCreate(Activity.java:7213)
11-04 12:49:57.845 17830 17830 E AndroidRuntime: 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1272)
11-04 12:49:57.845 17830 17830 E AndroidRuntime: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2926)
11-04 12:49:57.845 17830 17830 E AndroidRuntime: 	... 11 more
```

**Comment by xster** [comment]
Not a P1 but we should fix it at some point. 

https://github.com/flutter/engine/blob/fe0838e94860d30ea68a2f3dda52be17ca20411a/shell/platform/android/io/flutter/embedding/android/FlutterActivity.java#L498

This line looks like it isn't right. If an activity has any <meta-data> but not the right key of "io.flutter.embedding.android.SplashScreenDrawable" such as with a typo or an incomplete manual migration from V1, https://developer.android.com/reference/android/os/BaseBundle.html#getInt(java.lang.String) should be checked against 0 rather than null.

**Comment by xster** [comment]
Will be fixed in the next engine roll.
