### ISSUE TITLE
Hot reload failure on web: ProcessException: Too many open files

### ISSUE THREAD

**Issue by DaveShuckerow** [flutter/flutter#44141]
This occurs after hot reloading several times.

```
ProcessException: Too many open files
  Command: /Applications/Google Chrome.app/Contents/MacOS/Google Chrome --version
#0      ChromeDevice.sdkNameAndVersion (package:flutter_tools/src/web/web_device.dart:110:36)
<asynchronous suspension>
#1      ResidentWebRunner.restart (package:flutter_tools/src/build_runner/resident_web_runner.dart:371:33)
<asynchronous suspension>
#2      TerminalHandler._commonTerminalInputHandler (package:flutter_tools/src/resident_runner.dart:1140:61)
<asynchronous suspension>
#3      TerminalHandler.processTerminalInput (package:flutter_tools/src/resident_runner.dart:1192:13)
<asynchronous suspension>
#4      _rootRunUnary (dart:async/zone.dart:1132:38)
#5      _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#6      _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
#7      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#8      _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#9      _SyncBroadcastStreamController._sendData (dart:async/broadcast_stream_controller.dart:375:20)
#10     _BroadcastStreamController.add (dart:async/broadcast_stream_controller.dart:250:5)
#11     _AsBroadcastStreamController.add (dart:async/broadcast_stream_controller.dart:474:11)
#12     _rootRunUnary (dart:async/zone.dart:1132:38)
#13     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#14     _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
#15     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#16     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#17     _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:68:11)
#18     _EventSinkWrapper.add (dart:async/stream_transformers.dart:15:11)
#19     _StringAdapterSink.add (dart:convert/string_conversion.dart:236:11)
#20     _StringAdapterSink.addSlice (dart:convert/string_conversion.dart:241:7)
#21     _Utf8ConversionSink.addSlice (dart:convert/string_conversion.dart:312:20)
#22     _ErrorHandlingAsciiDecoderSink.addSlice (dart:convert/ascii.dart:252:17)
#23     _ErrorHandlingAsciiDecoderSink.add (dart:convert/ascii.dart:238:5)
#24     _ConverterStreamEventSink.add (dart:convert/chunked_conversion.dart:72:18)
#25     _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:120:24)
#26     _rootRunUnary (dart:async/zone.dart:1132:38)
#27     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#28     _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
#29     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#30     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#31     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:764:19)
#32     _StreamController._add (dart:async/stream_controller.dart:640:7)
#33     _StreamController.add (dart:async/stream_controller.dart:586:5)
#34     _Socket._onData (dart:io-patch/socket_patch.dart:1829:41)
#35     _rootRunUnary (dart:async/zone.dart:1136:13)
#36     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#37     _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
#38     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#39     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#40     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:764:19)
#41     _StreamController._add (dart:async/stream_controller.dart:640:7)
#42     _StreamController.add (dart:async/stream_controller.dart:586:5)
#43     new _RawSocket.<anonymous closure> (dart:io-patch/socket_patch.dart:1377:33)
#44     _NativeSocket.issueReadEvent.issue (dart:io-patch/socket_patch.dart:897:14)
#45     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#46     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#47     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:116:13)
#48     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:173:5)
```

doctor

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel master, v1.10.15-pre.344, on Mac OS X 10.14.6 18G87, locale en-US)
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[✓] Chrome - develop for the web
[✓] Android Studio
[✓] Android Studio (version 3.5)
[✓] Android Studio
[✓] IntelliJ IDEA Community Edition (version 2019.1.3)
[✓] Connected device (4 available)
```

**Comment by jonahwilliams** [comment]
This should have been fixed by my change to cache sdkNameAndVersion from Chrome: https://github.com/flutter/flutter/commit/e2361960373c1eb804d251fcbb73ce1a944b8ee2

Fixed by https://github.com/flutter/flutter/pull/45145
