### ISSUE TITLE
Three finger swipe crashes Android device

### ISSUE THREAD

**Issue by HansMuller** [flutter/flutter#44144]
This is not the same issue as https://github.com/flutter/flutter/issues/20517. In this case the problem isn't specific to a OnePlus phone, it's triggered by a swipe, not a tap, and the failure is different.

Swiping downwards with three fingers causes a crash on a 

```dart
import 'package:flutter/material.dart';

class Home extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: GestureDetector(
        onTap: () {
          print("TAP");
        },
      ),
    );
  }
}

void main() {
  runApp(MaterialApp(home: Home()));
}
```

```dart
E/flutter ( 6338): [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: NoSuchMethodError: The getter 'position' was called on null.
E/flutter ( 6338): Receiver: null
E/flutter ( 6338): Tried calling: position
E/flutter ( 6338): #0      Object.noSuchMethod (dart:core-patch/object_patch.dart:51:5)
E/flutter ( 6338): #1      TapGestureRecognizer.handleTapDown (package:flutter/src/gestures/tap.dart:456:28)
E/flutter ( 6338): #2      BaseTapGestureRecognizer._checkDown (package:flutter/src/gestures/tap.dart:256:5)
E/flutter ( 6338): #3      BaseTapGestureRecognizer.didExceedDeadline (package:flutter/src/gestures/tap.dart:227:5)
E/flutter ( 6338): #4      PrimaryPointerGestureRecognizer.didExceedDeadlineWithEvent (package:flutter/src/gestures/recognizer.dart:493:5)
E/flutter ( 6338): #5      PrimaryPointerGestureRecognizer.addAllowedPointer.<anonymous closure> (package:flutter/src/gestures/recognizer.dart:446:40)
E/flutter ( 6338): #6      _rootRun (dart:async/zone.dart:1120:38)
E/flutter ( 6338): #7      _CustomZone.run (dart:async/zone.dart:1021:19)
E/flutter ( 6338): #8      _CustomZone.runGuarded (dart:async/zone.dart:923:7)
E/flutter ( 6338): #9      _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:963:23)
E/flutter ( 6338): #10     _rootRun (dart:async/zone.dart:1124:13)
E/flutter ( 6338): #11     _CustomZone.run (dart:async/zone.dart:1021:19)
E/flutter ( 6338): #12     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:947:23)
E/flutter ( 6338): #13     Timer._createTimer.<anonymous closure> (dart:async-patch/timer_patch.dart:21:15)
E/flutter ( 6338): #14     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:382:19)
E/flutter ( 6338): #15     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:416:5)
E/flutter ( 6338): #16     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:12)
E/flutter ( 6338): 
```

```
[✓] Flutter (Channel master, v1.10.15-pre.387, on Linux, locale en_US.UTF-8)
    • Flutter version 1.10.15-pre.387 at /usr/local/google/home/hansmuller/github/flutter
    • Framework revision 3422540bc4 (6 hours ago), 2019-11-04 09:09:20 -0800
    • Engine revision 8ea19b1c76
    • Dart version 2.6.0 (build 2.6.0-dev.8.2 bbe2ac28c9)

[!] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /usr/local/google/home/hansmuller/Android/Sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /usr/local/google/home/hansmuller/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_112-release-b06)
    ✗ Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses

[!] Android Studio
    • Android Studio at /usr/local/google/home/hansmuller/android-studio
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[✓] Connected device (1 available)
    • Pixel 2 • FA79D1A03597 • android-arm64 • Android 10 (API 29)
```

**Comment by goderbauer** [comment]
The stack trace in https://github.com/flutter/flutter/issues/43310 looks very similar. The two issues may be related.

/cc @dkwingsmt When you have a fix for that issue, can you check if it also fixes this one?

**Comment by dkwingsmt** [comment]
Yes, I'll take a look after I finish that one.

**Comment by goderbauer** [comment]
Thanks, I assigned this issue to you.

**Comment by iapicca** [comment]
Tested with `master` seams to be fixed

<details>
  <summary>flutter doctor -v</summary>
  
```bash
[√] Flutter (Channel master, v1.13.1-pre.80, on Microsoft Windows [Version 10.0.19013.1122], locale en-US)
    • Flutter version 1.13.1-pre.80 at C:\src\flutter
    • Framework revision 2fe9623c36 (2 hours ago), 2019-12-10 04:22:32 -0500
    • Engine revision 12bf95fd49
    • Dart version 2.7.0 (build 2.7.0-dev.2.1 8b8894648f)

 
[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at C:\Users\iapic\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 28.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)        
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 3.5)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 41.1.2
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)

[√] VS Code, 64-bit edition (version 1.40.2)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Flutter extension version 3.7.0

[√] Connected device (3 available)
    • Pixel 3a   • 965AY0WP5C • android-arm64  • Android 10 (API 29)
    • Chrome     • chrome     • web-javascript • Google Chrome 78.0.3904.108
    • Web Server • web-server • web-javascript • Flutter Tools

• No issues found!
```
</details>

<details>
  <summary>logs</summary>

```bash
D/FlutterActivity(10858): Using the launch theme as normal theme.
D/FlutterActivityAndFragmentDelegate(10858): Setting up FlutterEngine.
D/FlutterActivityAndFragmentDelegate(10858): No preferred FlutterEngine was provided. Creating a new FlutterEngine for this FlutterFragment.
D/FlutterActivityAndFragmentDelegate(10858): Attaching FlutterEngine to the Activity that owns this Fragment.
D/FlutterView(10858): Attaching to a FlutterEngine: io.flutter.embedding.engine.FlutterEngine@ff2822c
D/FlutterActivityAndFragmentDelegate(10858): Executing Dart entrypoint: main, and sending initial route: /
Reloaded 1 of 478 libraries in 502ms.
I/flutter (10858): TAP
I/chatty  (10858): uid=10170(com.example.nineth_december) Thread-2 identical 2 lines
I/flutter (10858): TAP
I/flutter (10858): TAP
I/flutter (10858): TAP
I/flutter (10858): TAP
I/chatty  (10858): uid=10170(com.example.nineth_december) Thread-2 identical 16 lines
I/flutter (10858): TAP
I/flutter (10858): TAP
I/flutter (10858): TAP
I/chatty  (10858): uid=10170(com.example.nineth_december) Thread-2 identical 2 lines
I/flutter (10858): TAP
W/IInputConnectionWrapper(10858): getExtractedText on inactive InputConnection
W/IInputConnectionWrapper(10858): getTextBeforeCursor on inactive InputConnection
D/FlutterView(10858): Detaching from a FlutterEngine: io.flutter.embedding.engine.FlutterEngine@ff2822c
```
</details>

**Comment by goderbauer** [comment]
Closed as fixed per comment above.
