### ISSUE TITLE
Build screen blank.

### ISSUE THREAD

**Issue by daVinci13** [flutter/flutter#44145]
## Short descrption

App compiles, but it gives blank page.
Tried switching channels, reverting flutter version.
Went trough [Upgrading from package:flutter_web to the Flutter SDK](https://github.com/flutter/flutter/wiki/Upgrading-from-package:flutter_web-to-the-Flutter-SDK) guide.
## web/main.dart

```
import 'dart:ui' as ui;
import 'package:xxxxxx/main.dart' as app;

Future<void> main() async {
  await ui.webOnlyInitializePlatform();
  app.main();
}
```

## ERROR

```
The function 'webOnlyInitializePlatform' isn't defined.
Try importing the library that defines 'webOnlyInitializePlatform', correcting the name to the name of an existing function, or defining a function named 'webOnlyInitializePlatform'.dart(undefined_function)

```

## flutter run --verbose

```
[  +33 ms] executing: [C:\flutter\] git -c log.showSignature=false log -n 1 --pretty=format:%H
[ +101 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[   +4 ms] b94c1a41ca63df3b2efb41ea6c8ed0f9bcf669af
[   +1 ms] executing: [C:\flutter\] git describe --match v*.*.* --first-parent --long --tags
[ +115 ms] Exit code 0 from: git describe --match v*.*.* --first-parent --long --tags
[   +1 ms] v1.10.14-389-gb94c1a41c
[  +11 ms] executing: [C:\flutter\] git rev-parse --abbrev-ref --symbolic @{u}
[  +86 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[   +1 ms] origin/master
[        ] executing: [C:\flutter\] git ls-remote --get-url origin
[  +80 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[ +128 ms] executing: [C:\flutter\] git rev-parse --abbrev-ref HEAD
[  +76 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[   +1 ms] master
[ +151 ms] executing: C:\Users\neman\AppData\Local\Android\sdk\platform-tools\adb.exe devices -l
[  +47 ms] Exit code 0 from: C:\Users\neman\AppData\Local\Android\sdk\platform-tools\adb.exe devices -l
[   +1 ms] List of devices attached
[  +42 ms] More than one device connected; please specify a device with the '-d <deviceId>' flag, or use '-d all' to act on all devices.
[  +56 ms] Chrome     • chrome     • web-javascript • Google Chrome 78.0.3904.70
[   +2 ms] Web Server • web-server • web-javascript • Flutter Tools
[  +14 ms] "flutter run" took 390ms.

#0      throwToolExit (package:flutter_tools/src/base/common.dart:28:3)
#1      RunCommand.validateCommand (package:flutter_tools/src/commands/run.dart:287:7)
<asynchronous suspension>
#2      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:532:11)
<asynchronous suspension>
#3      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:457:33)
<asynchronous suspension>
#4      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:157:29)
<asynchronous suspension>
#5      _rootRun (dart:async/zone.dart:1124:13)
#6      _CustomZone.run (dart:async/zone.dart:1021:19)
#7      _runZoned (dart:async/zone.dart:1516:10)
#8      runZoned (dart:async/zone.dart:1463:12)
#9      AppContext.run (package:flutter_tools/src/base/context.dart:156:18)
<asynchronous suspension>
#10     FlutterCommand.run (package:flutter_tools/src/runner/flutter_command.dart:446:20)
#11     CommandRunner.runCommand (package:args/command_runner.dart:197:27)
<asynchronous suspension>
#12     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:416:21)
<asynchronous suspension>
#13     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:157:29)
<asynchronous suspension>
#14     _rootRun (dart:async/zone.dart:1124:13)
#15     _CustomZone.run (dart:async/zone.dart:1021:19)
#16     _runZoned (dart:async/zone.dart:1516:10)
#17     runZoned (dart:async/zone.dart:1463:12)
#18     AppContext.run (package:flutter_tools/src/base/context.dart:156:18)
<asynchronous suspension>
#19     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:367:19)
<asynchronous suspension>
#20     CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:112:25)
#21     new Future.sync (dart:async/future.dart:222:31)
#22     CommandRunner.run (package:args/command_runner.dart:112:14)
#23     FlutterCommandRunner.run (package:flutter_tools/src/runner/flutter_command_runner.dart:251:18)
#24     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:63:22)
<asynchronous suspension>
#25     _rootRun (dart:async/zone.dart:1124:13)
#26     _CustomZone.run (dart:async/zone.dart:1021:19)
#27     _runZoned (dart:async/zone.dart:1516:10)
#28     runZoned (dart:async/zone.dart:1500:12)
#29     run.<anonymous closure> (package:flutter_tools/runner.dart:61:18)
<asynchronous suspension>
#30     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:157:29)
<asynchronous suspension>
#31     _rootRun (dart:async/zone.dart:1124:13)
#32     _CustomZone.run (dart:async/zone.dart:1021:19)
#33     _runZoned (dart:async/zone.dart:1516:10)
#34     runZoned (dart:async/zone.dart:1463:12)
#35     AppContext.run (package:flutter_tools/src/base/context.dart:156:18)
<asynchronous suspension>
#36     runInContext (package:flutter_tools/src/context_runner.dart:64:24)
<asynchronous suspension>
#37     run (package:flutter_tools/runner.dart:50:10)
#38     main (package:flutter_tools/executable.dart:65:9)
<asynchronous suspension>
#39     main (file:///C:/flutter/packages/flutter_tools/bin/flutter_tools.dart:8:3)
#40     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:303:32)
#41     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:12)
```

## flutter analyze

```
info - Unused import: 'package:flutter/foundation.dart' - lib\app_localization.dart:1:8 - unused_import
   info - Avoid using web-only libraries outside Flutter web plugin packages - lib\utils\utils.dart:1:1 - avoid_web_libraries_in_flutter
   info - Avoid using web-only libraries outside Flutter web plugin packages - lib\utils\utils.dart:2:1 - avoid_web_libraries_in_flutter
   info - Avoid using web-only libraries outside Flutter web plugin packages - lib\utils\ux_utils.dart:1:1 - avoid_web_libraries_in_flutter
   info - Avoid using web-only libraries outside Flutter web plugin packages - lib\utils\ux_utils.dart:2:1 - avoid_web_libraries_in_flutter
   info - Unused import: 'dart:js' - lib\utils\ux_utils.dart:2:8 - unused_import
   info - Unused import: 'package:xxxxxx/models/config.dart' - lib\utils\ux_utils.dart:7:8 - unused_import
   info - Unused import: 'package:xxxxxx/theme.dart' - lib\ux\sections\welcome\highlights_list.dart:3:8 - unused_import
   info - Unused import: 'package:xxxxxx/utils/utils.dart' - lib\ux\sections\welcome\highlights_list.dart:4:8 - unused_import
   info - Unused import: 'package:xxxxxx/utils/utils.dart' - lib\ux\sections\welcome\socials_row.dart:2:8 - unused_import
   info - Unused import: 'package:flutter/material.dart' - lib\ux\widgets\info_block.dart:1:8 - unused_import
   info - Unused import: 'package:flutter/gestures.dart' - lib\ux\widgets\interactable.dart:1:8 - unused_import
   info - 'onPointerEnter' is deprecated and shouldn't be used. Use MouseRegion.onEnter instead. See MouseRegion.opaque for behavioral difference. -
          lib\ux\widgets\interactable.dart:50:7 - deprecated_member_use
   info - 'onPointerExit' is deprecated and shouldn't be used. Use MouseRegion.onExit instead. See MouseRegion.opaque for behavioral difference. -
          lib\ux\widgets\interactable.dart:51:7 - deprecated_member_use
   info - 'onPointerEnter' is deprecated and shouldn't be used. Use MouseRegion.onEnter instead. See MouseRegion.opaque for behavioral difference. -
          lib\ux\widgets\jfk_icon_button.dart:59:7 - deprecated_member_use
   info - 'onPointerExit' is deprecated and shouldn't be used. Use MouseRegion.onExit instead. See MouseRegion.opaque for behavioral difference. -
          lib\ux\widgets\jfk_icon_button.dart:60:7 - deprecated_member_use
   info - 'onPointerEnter' is deprecated and shouldn't be used. Use MouseRegion.onEnter instead. See MouseRegion.opaque for behavioral difference. -
          lib\ux\widgets\language_switcher.dart:31:7 - deprecated_member_use
   info - 'onPointerExit' is deprecated and shouldn't be used. Use MouseRegion.onExit instead. See MouseRegion.opaque for behavioral difference. -
          lib\ux\widgets\language_switcher.dart:32:7 - deprecated_member_use
  error - The function 'webOnlyInitializePlatform' isn't defined - web\main.dart:8:12 - undefined_function
```

## flutter doctor -v
```
[√] Flutter (Channel master, v1.10.15-pre.389, on Microsoft Windows [Version 10.0.18362.418], locale en-US)
    • Flutter version 1.10.15-pre.389 at C:\flutter
    • Framework revision b94c1a41ca (2 hours ago), 2019-11-04 13:37:51 -0800
    • Engine revision 8ea19b1c76
    • Dart version 2.6.0 (build 2.6.0-dev.8.2 bbe2ac28c9)

 
[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at C:\Users\neman\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: D:\Program Files\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[!] Android Studio (version 3.5)
    • Android Studio at D:\Program Files
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)

[√] VS Code (version 1.39.2)
    • VS Code at C:\Users\neman\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.6.0

[√] Connected device (2 available)
    • Chrome     • chrome     • web-javascript • Google Chrome 78.0.3904.70
    • Web Server • web-server • web-javascript • Flutter Tools
```

**Comment by jonahwilliams** [comment]
Please remove the `web/main.dart` file. now that flutter web has been merged back into flutter. See https://github.com/flutter/flutter/wiki/Upgrading-from-package:flutter_web-to-the-Flutter-SDK#clean-up-the-web-directory
