### ISSUE TITLE
Camera application is crashing and throws an exception

### ISSUE THREAD

**Issue by janardhanmupparaju** [flutter/flutter#44178]
i am using camera in my app. the app have two tabs, in two tabs i am using camera. 
i am disposing the CameraController like this
```
@override
  void dispose() {
 super.dispose();
 cameraController.dispose();
  }
```

but when i move to one tab to another tab, app is crashing and showing this error:

<details>
  <summary>error</summary>

```
E/BufferQueueProducer(14499): [SurfaceTexture-1-14499-15] cancelBuffer: BufferQueue has been abandoned
I/chatty  (14499): uid=10251(com.example.sentry_mobile_app) Binder:14499_1 identical 6 lines
E/BufferQueueProducer(14499): [SurfaceTexture-1-14499-15] cancelBuffer: BufferQueue has been abandoned
E/BufferQueueProducer(14499): [SurfaceTexture-1-14499-15] connect: BufferQueue has been abandoned
E/BufferQueueProducer(14499): [SurfaceTexture-1-14499-15] setMaxDequeuedBufferCount: BufferQueue has been abandoned
E/libc    (14499): Access denied finding property "vendor.camera.aux.packagelist"
E/libc    (14499): Access denied finding property "persist.vendor.camera.privapp.list"
I/CameraManager(14499): Using legacy camera HAL.
E/libc    (14499): Access denied finding property "vendor.camera.hal1.packagelist"
E/libc    (14499): Access denied finding property "vendor.camera.aux.packagelist"
E/libc    (14499): Access denied finding property "vendor.camera.aux.packagelist"
W/ntry_mobile_app(14499): type=1400 audit(0.0:59108): avc: denied { read } for name="u:object_r:vendor_camera_prop:s0" dev="tmpfs" ino=13461 scontext=u:r:untrusted_app:s0:c251,c256,c512,c768 tcontext=u:object_r:vendor_camera_prop:s0 tclass=file permissive=0
E/libc    (14499): Access denied finding property "persist.vendor.camera.privapp.list"
I/CameraManager(14499): Using legacy camera HAL.
W/Thread-29(14499): type=1400 audit(0.0:59109): avc: denied { read } for name="u:object_r:vendor_default_prop:s0" dev="tmpfs" ino=13469 scontext=u:r:untrusted_app:s0:c251,c256,c512,c768 tcontext=u:object_r:vendor_default_prop:s0 tclass=file permissive=0
E/libc    (14499): Access denied finding property "vendor.camera.hal1.packagelist"
E/Camera  (14499): Error 2
I/RequestThread-1(14499): Flushing all pending requests.
E/RequestQueue(14499): cancel failed: no repeating request exists.
I/CameraDeviceState(14499): Legacy camera service transitioning to state ERROR
W/Binder:14499_1(14499): type=1400 audit(0.0:59111): avc: denied { read } for name="u:object_r:vendor_camera_prop:s0" dev="tmpfs" ino=13461 scontext=u:r:untrusted_app:s0:c251,c256,c512,c768 tcontext=u:object_r:vendor_camera_prop:s0 tclass=file permissive=0
E/libc    (14499): Access denied finding property "vendor.camera.aux.packagelist"
E/libc    (14499): Access denied finding property "vendor.camera.aux.packagelist"
E/libc    (14499): Access denied finding property "vendor.camera.aux.packagelist"
D/AndroidRuntime(14499): Shutting down VM
E/AndroidRuntime(14499): FATAL EXCEPTION: main
E/AndroidRuntime(14499): Process: com.example.sentry_mobile_app, PID: 14499
E/AndroidRuntime(14499): java.lang.NullPointerException: Attempt to invoke virtual method 'android.view.Surface android.media.ImageReader.getSurface()' on a null object reference
E/AndroidRuntime(14499):        at io.flutter.plugins.camera.Camera.startPreview(Camera.java:424)
E/AndroidRuntime(14499):        at io.flutter.plugins.camera.Camera$2.onOpened(Camera.java:160)
E/AndroidRuntime(14499):        at android.hardware.camera2.impl.CameraDeviceImpl$1.run(CameraDeviceImpl.java:149)
E/AndroidRuntime(14499):        at android.os.Handler.handleCallback(Handler.java:873)
E/AndroidRuntime(14499):        at android.os.Handler.dispatchMessage(Handler.java:99)
E/AndroidRuntime(14499):        at android.os.Looper.loop(Looper.java:201)
E/AndroidRuntime(14499):        at android.app.ActivityThread.main(ActivityThread.java:6810)
E/AndroidRuntime(14499):        at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(14499):        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
E/AndroidRuntime(14499):        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:873)
I/Process (14499): Sending signal. PID: 14499 SIG: 9
Lost connection to device.
```

</details>

**Comment by iapicca** [comment]
Hi @janardhanmupparaju 
can you please provide your updated  `flutter doctor -v` ?
Also, to better address the issue, would be helpful
if you could show a bit more of your code,
maybe posting a self contained app on github
or the steps to reproduce it.
Thank you

**Comment by iapicca** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact descriptions what happens, logs and the output of 'flutter doctor -v'  please.
All system setups can be slightly different so its always better to open new issues and reference related issues.

**Comment by haamaanaa** [comment]
stumbled upon same issue: 

https://github.com/flutter/flutter/issues/46952
