### ISSUE TITLE
Can't run "flutter doctor" command. Crashes with ArgumentError.

### ISSUE THREAD

**Issue by Parth198** [flutter/flutter#44336]
![Capture](https://user-images.githubusercontent.com/57165671/68375828-90c34200-016d-11ea-8a1c-4c4a0838510d.JPG)

I'm using Windows 7 Ultimate , 32bit 

What i can do for this error.....

## command

flutter doctor

## exception

ArgumentError: Invalid argument(s): join(null, "Microsoft VS Code"): part 0 was null, but part 1 was not.

```
#0      _validateArgList (package:path/src/context.dart:1087:5)
#1      Context.join (package:path/src/context.dart:231:5)
#2      VsCode._installedWindows (package:flutter_tools/src/vscode/vscode.dart:157:17)
#3      VsCode.allInstalled (package:flutter_tools/src/vscode/vscode.dart:92:14)
#4      VsCodeValidator.installedValidators (package:flutter_tools/src/vscode/vscode_validator.dart:19:10)
#5      _DefaultDoctorValidatorsProvider.validators (package:flutter_tools/src/doctor.dart:65:28)
#6      Doctor.validators (package:flutter_tools/src/doctor.dart:132:46)
#7      Doctor.startValidatorTasks (package:flutter_tools/src/doctor.dart:139:39)
#8      Doctor.diagnose (package:flutter_tools/src/doctor.dart:211:41)
<asynchronous suspension>
#9      DoctorCommand.runCommand (package:flutter_tools/src/commands/doctor.dart:59:39)
<asynchronous suspension>
#10     FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:490:18)
<asynchronous suspension>
#11     FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:407:33)
<asynchronous suspension>
#12     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:154:29)
<asynchronous suspension>
#13     _rootRun (dart:async/zone.dart:1124:13)
#14     _CustomZone.run (dart:async/zone.dart:1021:19)
#15     _runZoned (dart:async/zone.dart:1516:10)
#16     runZoned (dart:async/zone.dart:1463:12)
#17     AppContext.run (package:flutter_tools/src/base/context.dart:153:18)
<asynchronous suspension>
#18     FlutterCommand.run (package:flutter_tools/src/runner/flutter_command.dart:397:20)
#19     CommandRunner.runCommand (package:args/command_runner.dart:197:27)
<asynchronous suspension>
#20     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:402:21)
<asynchronous suspension>
#21     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:154:29)
<asynchronous suspension>
#22     _rootRun (dart:async/zone.dart:1124:13)
#23     _CustomZone.run (dart:async/zone.dart:1021:19)
#24     _runZoned (dart:async/zone.dart:1516:10)
#25     runZoned (dart:async/zone.dart:1463:12)
#26     AppContext.run (package:flutter_tools/src/base/context.dart:153:18)
<asynchronous suspension>
#27     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:356:19)
<asynchronous suspension>
#28     CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:112:25)
#29     new Future.sync (dart:async/future.dart:224:31)
#30     CommandRunner.run (package:args/command_runner.dart:112:14)
#31     FlutterCommandRunner.run (package:flutter_tools/src/runner/flutter_command_runner.dart:242:18)
#32     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:63:22)
<asynchronous suspension>
#33     _rootRun (dart:async/zone.dart:1124:13)
#34     _CustomZone.run (dart:async/zone.dart:1021:19)
#35     _runZoned (dart:async/zone.dart:1516:10)
#36     runZoned (dart:async/zone.dart:1500:12)
#37     run.<anonymous closure> (package:flutter_tools/runner.dart:61:18)
<asynchronous suspension>
#38     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:154:29)
<asynchronous suspension>
#39     _rootRun (dart:async/zone.dart:1124:13)
#40     _CustomZone.run (dart:async/zone.dart:1021:19)
#41     _runZoned (dart:async/zone.dart:1516:10)
#42     runZoned (dart:async/zone.dart:1463:12)
#43     AppContext.run (package:flutter_tools/src/base/context.dart:153:18)
<asynchronous suspension>
#44     runInContext (package:flutter_tools/src/context_runner.dart:59:24)
<asynchronous suspension>
#45     run (package:flutter_tools/runner.dart:50:10)
#46     main (package:flutter_tools/executable.dart:65:9)
<asynchronous suspension>
#47     main (file:///C:/b/s/w/ir/k/archive/flutter/packages/flutter_tools/bin/flutter_tools.dart:8:3)
#48     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:303:32)
#49     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:12)
```

## flutter doctor

```
encountered exception: Invalid argument(s): join(null, "Microsoft VS Code"): part 0 was null, but part 1 was not.

#0      _validateArgList (package:path/src/context.dart:1087:5)
#1      Context.join (package:path/src/context.dart:231:5)
#2      VsCode._installedWindows (package:flutter_tools/src/vscode/vscode.dart:157:17)
#3      VsCode.allInstalled (package:flutter_tools/src/vscode/vscode.dart:92:14)
#4      VsCodeValidator.installedValidators (package:flutter_tools/src/vscode/vscode_validator.dart:19:10)
#5      _DefaultDoctorValidatorsProvider.validators (package:flutter_tools/src/doctor.dart:65:28)
#6      Doctor.validators (package:flutter_tools/src/doctor.dart:132:46)
#7      Doctor.startValidatorTasks (package:flutter_tools/src/doctor.dart:139:39)
#8      Doctor.diagnose (package:flutter_tools/src/doctor.dart:211:41)
<asynchronous suspension>
#9      _doctorText.<anonymous closure> (package:flutter_tools/runner.dart:202:26)
#10     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:154:29)
<asynchronous suspension>
#11     _rootRun (dart:async/zone.dart:1124:13)
#12     _CustomZone.run (dart:async/zone.dart:1021:19)
#13     _runZoned (dart:async/zone.dart:1516:10)
#14     runZoned (dart:async/zone.dart:1463:12)
#15     AppContext.run (package:flutter_tools/src/base/context.dart:153:18)
<asynchronous suspension>
#16     _doctorText (package:flutter_tools/runner.dart:201:19)
<asynchronous suspension>
#17     _createLocalCrashReport (package:flutter_tools/runner.dart:179:32)
<asynchronous suspension>
#18     _handleToolError (package:flutter_tools/runner.dart:134:33)
<asynchronous suspension>
#19     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:68:22)
<asynchronous suspension>
#20     _rootRun (dart:async/zone.dart:1124:13)
#21     _CustomZone.run (dart:async/zone.dart:1021:19)
#22     _runZoned (dart:async/zone.dart:1516:10)
#23     runZoned (dart:async/zone.dart:1500:12)
#24     run.<anonymous closure> (package:flutter_tools/runner.dart:61:18)
<asynchronous suspension>
#25     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:154:29)
<asynchronous suspension>
#26     _rootRun (dart:async/zone.dart:1124:13)
#27     _CustomZone.run (dart:async/zone.dart:1021:19)
#28     _runZoned (dart:async/zone.dart:1516:10)
#29     runZoned (dart:async/zone.dart:1463:12)
#30     AppContext.run (package:flutter_tools/src/base/context.dart:153:18)
<asynchronous suspension>
#31     runInContext (package:flutter_tools/src/context_runner.dart:59:24)
<asynchronous suspension>
#32     run (package:flutter_tools/runner.dart:50:10)
#33     main (package:flutter_tools/executable.dart:65:9)
<asynchronous suspension>
#34     main (file:///C:/b/s/w/ir/k/archive/flutter/packages/flutter_tools/bin/flutter_tools.dart:8:3)
#35     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:303:32)
#36     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:12)
```

**Comment by janmoppel** [comment]
Hello @Parth198 !

Thank you for posting an issue.
What Flutter version do you use?

**Comment by janmoppel** [comment]
Your issue also seems to be similar to the one here: #23909. Can you please check whether the solution proposed here works for you: https://github.com/flutter/flutter/issues/23909#issuecomment-435604189?

**Comment by Parth198** [comment]
> Hello @Parth198 !
> 
> Thank you for posting an issue.
> What Flutter version do you use?

**Comment by Parth198** [comment]
> > Hello @Parth198 !
> > Thank you for posting an issue.
> > What Flutter version do you use?

flutter version : 1.9.1+hotfix.6

**Comment by Parth198** [comment]
> Your issue also seems to be similar to the one here: #23909. Can you please check whether the solution proposed here works for you: [#23909 (comment)](https://github.com/flutter/flutter/issues/23909#issuecomment-435604189)?

i seen this : #2309 
but can't solve this error

**Comment by sldsrg** [comment]
Since Flutter SDK supports only 64-bit Windows, flutter tools assumes that the system has a folder `Program Files (x86)`, but in Windows 32-bit there is no such folder, which leads to an error.
As workaround this issue can be fixed with follow assignment (in PowerShell console):
`${env:ProgramFiles(x86)} = $env:ProgramFiles`

**Comment by christopherfujino** [comment]
Closing this as the Flutter SDK requires 64-bit Windows (see https://flutter.dev/docs/get-started/install/windows). See https://github.com/flutter/flutter/issues/44336#issuecomment-559796492 for a potential workaround on 32-bit Windows.

**Comment by xdedeone** [comment]
> Since Flutter SDK supports only 64-bit Windows, flutter tools assumes that the system has a folder `Program Files (x86)`, but in Windows 32-bit there is no such folder, which leads to an error.
> As workaround this issue can be fixed with following assignment (in PowerShell console):
> `${env:ProgramFiles(x86)} = $env:ProgramFiles`

Tested in 32 bits. It Works!!!!

**Comment by Parth198** [comment]
> > Since Flutter SDK supports only 64-bit Windows, flutter tools assumes that the system has a folder `Program Files (x86)`, but in Windows 32-bit there is no such folder, which leads to an error.
> > As workaround this issue can be fixed with following assignment (in PowerShell console):
> > `${env:ProgramFiles(x86)} = $env:ProgramFiles`
> 
> Tested in 32 bits. It Works!!!!

ok can tried this code but didn't works for me.
error -> 
C:\>${env:ProgramFiles(x86)} = $env:ProgramFiles

The filename, directory name, or volume label syntax is incorrect.
