### ISSUE TITLE
[catalina] after workaround for  "idevice_id" run returns ProcessException: ProcessException: No such file or directory

### ISSUE THREAD

**Issue by cfchris** [flutter/flutter#44406]
Mac updated to Catalina. Ended up with a bunch of permission errors with "idevice_id" etc. Think I got those fixed. But, now I just can't flutter run from terminal or VS Code.

## command

flutter run

## exception

ProcessException: ProcessException: No such file or directory
  Command: /usr/local/bin/pod install --verbose

```
#0      CocoaPods._runPodInstall (package:flutter_tools/src/macos/cocoapods.dart:283:34)
<asynchronous suspension>
#1      CocoaPods.processPods (package:flutter_tools/src/macos/cocoapods.dart:133:15)
<asynchronous suspension>
#2      processPodsIfNeeded (package:flutter_tools/src/macos/cocoapod_utils.dart:37:46)
<asynchronous suspension>
#3      buildXcodeProject (package:flutter_tools/src/ios/mac.dart:339:9)
<asynchronous suspension>
#4      IOSDevice.startApp (package:flutter_tools/src/ios/devices.dart:276:50)
<asynchronous suspension>
#5      FlutterDevice.runHot (package:flutter_tools/src/resident_runner.dart:378:54)
<asynchronous suspension>
#6      HotRunner.run (package:flutter_tools/src/run_hot.dart:254:39)
<asynchronous suspension>
#7      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:472:37)
<asynchronous suspension>
#8      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:490:18)
#9      _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:71:64)
#10     _rootRunUnary (dart:async/zone.dart:1132:38)
#11     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#12     _FutureListener.handleValue (dart:async/future_impl.dart:137:18)
#13     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:678:45)
#14     Future._propagateToListeners (dart:async/future_impl.dart:707:32)
#15     Future._completeWithValue (dart:async/future_impl.dart:522:5)
#16     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:30:15)
#17     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:288:13)
#18     RunCommand.usageValues (package:flutter_tools/src/commands/run.dart)
#19     _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:71:64)
#20     _rootRunUnary (dart:async/zone.dart:1132:38)
#21     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#22     _FutureListener.handleValue (dart:async/future_impl.dart:137:18)
#23     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:678:45)
#24     Future._propagateToListeners (dart:async/future_impl.dart:707:32)
#25     Future._completeWithValue (dart:async/future_impl.dart:522:5)
#26     Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:552:7)
#27     _rootRun (dart:async/zone.dart:1124:13)
#28     _CustomZone.run (dart:async/zone.dart:1021:19)
#29     _CustomZone.runGuarded (dart:async/zone.dart:923:7)
#30     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:963:23)
#31     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#32     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#33     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:116:13)
#34     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:173:5)
```

## flutter doctor

```
[32m[✓][39m Flutter (Channel stable, v1.9.1+hotfix.6, on Mac OS X 10.15.1 19B88, locale en-US)
    [32m•[39m Flutter version 1.9.1+hotfix.6 at /Users/chrisp/development/flutter
    [32m•[39m Framework revision 68587a0916 (8 weeks ago), 2019-09-13 19:46:58 -0700
    [32m•[39m Engine revision b863200c37
    [32m•[39m Dart version 2.5.0

[31m[✗][39m Android toolchain - develop for Android devices
    [31m✗[39m Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/setup/#android-setup for detailed instructions).
      If the Android SDK has been installed to a custom location, set ANDROID_HOME to that location.
      You may also want to add it to your PATH environment variable.


[33m[!][39m Xcode - develop for iOS and macOS (Xcode 11.2.1)
    [32m•[39m Xcode at /Applications/Xcode.app/Contents/Developer
    [32m•[39m Xcode 11.2.1, Build version 11B53
    [31m✗[39m CocoaPods installed but not working.
        You appear to have CocoaPods installed but it is not working.
        This can happen if the version of Ruby that CocoaPods was installed with is different from the one being used to invoke it.
        This can usually be fixed by re-installing CocoaPods. For more info, see https://github.com/flutter/flutter/issues/14293.
      To re-install CocoaPods, run:
        sudo gem install cocoapods

[33m[!][39m Android Studio (not installed)
    [32m•[39m Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/setup/#android-setup for detailed instructions).

[32m[✓][39m VS Code (version 1.40.0)
    [32m•[39m VS Code at /Applications/Visual Studio Code.app/Contents
    [32m•[39m Flutter extension version 3.6.0

[32m[✓][39m Connected device (1 available)
    [32m•[39m Chris Phillips’s iPhone • e0714682ad79fb485922d5a2fe31e510d907bb99 • ios • iOS 13.2

[33m![39m Doctor found issues in 3 categories.
```

**Comment by iapicca** [comment]
Hi @cfchris 
did you follow this [workaround ](https://github.com/flutter/flutter/issues/42969#issuecomment-545597222)to fix the `idevice_id` issue?
thank you

**Comment by truonghoangduy** [comment]
If you has an opened dialog saying somethings about security.

**Comment by cfchris** [comment]
> Hi @cfchris
> did you follow this [workaround ](https://github.com/flutter/flutter/issues/42969#issuecomment-545597222)to fix the `idevice_id` issue?
> Is it the whole log?
> thank you

I have followed the workaround. And that is the whole log. I just repeated the steps of the workaround and then did `flutter run` again. Here is what I get in the terminal (which points to a log record like the on I submitted).

```
Chriss-MBP:classic-crm chrisp$ flutter run
Launching lib/main.dart on Chris Phillips's iPhone in debug mode...
Automatically signing iOS for device deployment using specified development team in Xcode project: LX58R5EUTX
Running pod install...                                                 ⣽
Sending crash report to Google.                                 
Crash report sent (report ID: 73ec7e8729315b66)                         
Running pod install...                                                 ⣽Oops; flutter has exited unexpectedly.
       Crash report written to /Users/chrisp/development/flutter_projects/classic-crm/flutter_05.log;
please let us know at https://github.com/flutter/flutter/issues.
       ⢿Chriss-MBP:classic-crm chrisp$ 
```

**Comment by cfchris** [comment]
I am going to attempt to delete flutter, and re-install. If that doesn't fix it, I will attempt to delete and re-clone our repository (for the app).

**Comment by cfchris** [comment]
OK. After re-installing flutter (rm -rf && unzip), and running `flutter doctor`, I got the security prompts again. So, I cancelled and ran the attribute update fix. Then, I ran flutter doctor and got a more helpful error.

```
[!] Xcode - develop for iOS and macOS (Xcode 11.2.1)
    ✗ CocoaPods installed but not working.
        You appear to have CocoaPods installed but it is not working.
        This can happen if the version of Ruby that CocoaPods was installed with is different from the one being used to invoke it.
        This can usually be fixed by re-installing CocoaPods. For more info, see https://github.com/flutter/flutter/issues/14293.
      To re-install CocoaPods, run:
        sudo gem install cocoapods
```

So, then I ran `sudo gem install cocoapods`. That went fine. So, I tried `flutter run` again. That failed. But, I just needed to run `flutter pub get`.

And now finally, I can run the app again. Hope this info helps someone else that get's stuck.

To summarize, after installing Catalina, you may want to:

1. Re-install flutter (just `rm -rf ~/development/flutter/` and unzip fresh zip)
2. Run the attribute update thing (will post below)
3. Run `flutter pub get` in your project directory
4. (Should be back up and running.)

```
# For "idevice_id" error:
sudo xattr -d com.apple.quarantine /Users/Your_User/Your_Dev_Folder/flutter/bin/cache/artifacts/libimobiledevice/idevice_id
# For "ideviceinfo" error:
sudo xattr -d com.apple.quarantine /Users/Your_User/Your_Dev_Folder/flutter/bin/cache/artifacts/libimobiledevice/ideviceinfo
# For "idevicesyslog" error:
sudo xattr -d com.apple.quarantine /Users/Your_User/Your_Dev_Folder/flutter/bin/cache/artifacts/libimobiledevice/idevicesyslog
# For "iproxy" error:
sudo xattr -d com.apple.quarantine /Users/Your_User/Your_Dev_Folder/flutter/bin/cache/artifacts/usbmuxd/iproxy
```

**Comment by cfchris** [comment]
To summarize, after installing Catalina, you may want to:

1. Re-install flutter (just `rm -rf ~/development/flutter/` and unzip fresh zip)
2. Run the attribute update thing (will post below)
3. Run `flutter pub get` in your project directory
4. (Should be back up and running.)

```
# For "idevice_id" error:
sudo xattr -d com.apple.quarantine /Users/Your_User/Your_Dev_Folder/flutter/bin/cache/artifacts/libimobiledevice/idevice_id
# For "ideviceinfo" error:
sudo xattr -d com.apple.quarantine /Users/Your_User/Your_Dev_Folder/flutter/bin/cache/artifacts/libimobiledevice/ideviceinfo
# For "idevicesyslog" error:
sudo xattr -d com.apple.quarantine /Users/Your_User/Your_Dev_Folder/flutter/bin/cache/artifacts/libimobiledevice/idevicesyslog
# For "iproxy" error:
sudo xattr -d com.apple.quarantine /Users/Your_User/Your_Dev_Folder/flutter/bin/cache/artifacts/usbmuxd/iproxy
```
