### ISSUE TITLE
NPE in serveDevTools

### ISSUE THREAD

**Issue by jonahwilliams** [flutter/flutter#44459]
This happened with `run -d chrome` on Windows with the latest dev branch 1.10.15. The issue might be in devtools @DaveShuckerow or in dwds handling of devtools @grouma 

```
NoSuchMethodError: The method 'toFilePath' was called on null.
Receiver: null
Tried calling: toFilePath()

  | at Object.noSuchMethod | (object_patch.dart:51 )
-- | -- | --
  | at defaultHandler | (handlers.dart:28 )
  | at <asynchronous gap> | (async )
  | at serveDevTools | (server.dart:143 )
  | at <asynchronous gap> | (async )
  | at DevTools.start | (devtools.dart:27 )
  | at <asynchronous gap> | (async )
  | at Dwds.start | (dwds.dart:99 )
  | at <asynchronous gap> | (async )
  | at WebFs.start | (web_fs.dart:287 )
  | at <asynchronous gap> | (async )
  | at ResidentWebRunner.run.<anonymous closure> | (resident_web_runner.dart:184 )
  | at <asynchronous gap> | (async )
  | at asyncGuard.<anonymous closure> | (async_guard.dart:111 )
  | at <asynchronous gap> | (async )
  | at _rootRun | (zone.dart:1124 )
  | at _CustomZone.run | (zone.dart:1021 )
  | at _runZoned | (zone.dart:1516 )
  | at runZoned | (zone.dart:1500 )
  | at asyncGuard | (async_guard.dart:109 )
  | at ResidentWebRunner.run | (resident_web_runner.dart:183 )
  | at <asynchronous gap> | (async )
  | at RunCommand.runCommand | (run.dart:494 )
  | at <asynchronous gap> | (async )
  | at FlutterCommand.verifyThenRunCommand | (flutter_command.dart:557 )
  | at _asyncThenWrapperHelper.<anonymous closure> | (async_patch.dart:71 )
  | at _rootRunUnary | (zone.dart:1132 )
  | at _CustomZone.runUnary | (zone.dart:1029 )
  | at _FutureListener.handleValue | (future_impl.dart:137 )
  | at Future._propagateToListeners.handleValueCallback | (future_impl.dart:678 )
  | at Future._propagateToListeners | (future_impl.dart:707 )
  | at Future._completeWithValue | (future_impl.dart:522 )
  | at _AsyncAwaitCompleter.complete | (async_patch.dart:30 )
  | at _completeOnAsyncReturn | (async_patch.dart:288 )
  | at RunCommand.usageValues | (run.dart )
  | at _asyncThenWrapperHelper.<anonymous closure> | (async_patch.dart:71 )
  | at _rootRunUnary | (zone.dart:1132 )
  | at _CustomZone.runUnary | (zone.dart:1029 )
  | at _FutureListener.handleValue | (future_impl.dart:137 )
  | at Future._propagateToListeners.handleValueCallback | (future_impl.dart:678 )
  | at Future._propagateToListeners | (future_impl.dart:707 )
  | at Future._completeWithValue | (future_impl.dart:522 )
  | at _AsyncAwaitCompleter.complete | (async_patch.dart:30 )
  | at _completeOnAsyncReturn | (async_patch.dart:288 )
  | at IosProject.isSwift | (project.dart )
  | at _asyncThenWrapperHelper.<anonymous closure> | (async_patch.dart:71 )
  | at _rootRunUnary | (zone.dart:1132 )
  | at _CustomZone.runUnary | (zone.dart:1029 )
  | at _FutureListener.handleValue | (future_impl.dart:137 )
  | at Future._propagateToListeners.handleValueCallback | (future_impl.dart:678 )
  | at Future._propagateToListeners | (future_impl.dart:707 )
  | at Future._completeWithValue | (future_impl.dart:522 )
  | at Future._asyncComplete.<anonymous closure> | (future_impl.dart:552 )
  | at _rootRun | (zone.dart:1124 )
  | at _CustomZone.run | (zone.dart:1021 )
  | at _CustomZone.runGuarded | (zone.dart:923 )
  | at _CustomZone.bindCallbackGuarded.<anonymous closure> | (zone.dart:963 )
  | at _microtaskLoop | (schedule_microtask.dart:41 )
  | at _startMicrotaskLoop | (schedule_microtask.dart:50 )
  | at _runPendingImmediateCallback | (isolate_patch.dart:116 )
  | at _RawReceivePortImpl._handleMessage | (isolate_patch.dart:173 )
```

**Comment by grouma** [comment]
The only place we call that in `package:dwds` is here:
https://github.com/dart-lang/webdev/blob/master/dwds/lib/src/handlers/injected_handler.dart#L35

For the null issue to happen, `package:dwds` would not be able to read the injected client file which would be extremely weird given that it ships with the package.

**Comment by jonahwilliams** [comment]
I wonder if that returns null if the Isolate.resolvePackageUri fails? IIRC there were some issues with something similar that I hacked around a while back. I'll see if I can repro again

**Comment by tianna1121** [comment]
have similar issue when I run "flutter run -d web-server". 
flutter --verison

> Flutter 1.12.1 • channel dev • https://github.com/flutter/flutter.git
Framework • revision 86c91b12d8 (4 days ago) • 2019-11-11 13:29:46 -0800
Engine • revision 31cd2dfca2
Tools • Dart 2.7.0 

> Flutter crash report; please file at https://github.com/flutter/flutter/issues.

## command

flutter run -d web-server

## exception

NoSuchMethodError: NoSuchMethodError: The method 'toFilePath' was called on null.
Receiver: null
Tried calling: toFilePath()

```
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:51:5)
#1      defaultHandler (package:devtools_server/src/handlers.dart:28:60)
<asynchronous suspension>
#2      serveDevTools (package:devtools_server/src/server.dart:143:21)
<asynchronous suspension>
#3      DevTools.start (package:dwds/src/servers/devtools.dart:27:15)
<asynchronous suspension>
#4      Dwds.start (package:dwds/dwds.dart:105:33)
<asynchronous suspension>
#5      WebFs.start (package:flutter_tools/src/build_runner/web_fs.dart:291:33)
<asynchronous suspension>
#6      _DwdsResidentWebRunner.run.<anonymous closure> (package:flutter_tools/src/build_runner/resident_web_runner.dart:598:36)
<asynchronous suspension>
....

**Comment by tianna1121** [comment]
Have similar issues when executing "flutter run -d web-server" in the docker environment (flutter dev v1.12.1). However when I rerun the same command, it works. I've tried several times already. Pretty strange.

> odoo13@master-node:~/docker/dart_flutter_web$ sudo docker run -p 8443:8443 -p 8080:8080 -it flutter bash
root@56bffc611146:/works/dweb# flutter run -d web-server
Downloading Web SDK...                                              0.5s
Launching lib/main.dart on Web Server in debug mode...
Building application for the web...                                13.3s

Sending crash report to Google.
Crash report sent (report ID: 6676d4e0ac21fce0)
Oops; flutter has exited unexpectedly.
Crash report written to /works/dweb/flutter_01.log;
please let us know at https://github.com/flutter/flutter/issues.

**root@56bffc611146:/works/dweb# flutter run -d web-server**
Launching lib/main.dart on Web Server in debug mode...
Building application for the web...                                35.7s
lib/main.dart is being served at http://localhost:44537/

Warning: Flutter's support for web development is not stable yet and hasn't
been thoroughly tested in production environments.
For more information see https://flutter.dev/web

🔥  To hot restart changes while running, press "r". To hot restart (and refresh the browser), press "R".
For a more detailed help message, press "h". To quit, press "q".

**Comment by GameSquatch** [comment]
Having a similar issue with `flutter run -d Chrome`

```
Launching lib/main.dart on Chrome in debug mode...
Unhandled exception:                                                    
NoSuchMethodError: The method '[]' was called on null.                  
Receiver: null                                                          
Tried calling: []("packages")                                           
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:53:5)    
#1      _parseDependencyTypes                                           
(package:build_runner_core/src/package_graph/package_graph.dart:194:41)
#2      new PackageGraph.forPath                                        
(package:build_runner_core/src/package_graph/package_graph.dart:70:29)
#3      new PackageGraph.forThisPackage                                 
(package:build_runner_core/src/package_graph/package_graph.dart:98:57)
#4      new BuildCommandRunner (package:build_runner/src/entrypoint/runner.dart:27:37)
#5      run (package:build_runner/src/entrypoint/run.dart:22:16)        
#6      main (package:flutter_tools/src/build_runner/build_script.dart:181:28)
#7      _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:303:32)
#8      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:174:12)
Building application for the web...                                12.7s
Failed to start build daemon. The process might have exited unexpectedly during startup.
Try running the application again.
```

**Comment by grouma** [comment]
@jonahwilliams what's the status here? Can we close?

**Comment by jonahwilliams** [comment]
I haven't seen this in forever, we can close it

**Comment by jaysephjw** [comment]
I am running into this on `1.20.0-7.2.pre` when target web from this machine for the first time.


From freshly created app: 

```
➜  myapp flutter run -d chrome
Launching lib/main.dart on Chrome in debug mode...
Syncing files to device Chrome...                                       
11,001ms (!)                                       
ERROR - 2020-07-21 16:25:49.135748
GET /dwds/src/injected/client.js
Error thrown by handler.
NoSuchMethodError: The method 'toFilePath' was called on null.
Receiver: null
Tried calling: toFilePath()
dart:core                                      Object.noSuchMethod
package:dwds/src/handlers/injector.dart 51:41  DwdsInjector.middleware.<fn>.<fn>
```

<details>
<p>

```
➜  temp flutter upgrade
Flutter is already up to date on channel beta
Flutter 1.20.0-7.2.pre • channel beta • https://github.com/flutter/flutter.git
Framework • revision a2bde82fbd (3 days ago) • 2020-07-18 15:16:35 -0700
Engine • revision 60b269d898
Tools • Dart 2.9.0 (build 2.9.0-21.2.beta)
```

```
➜  temp flutter config --enable-web
Setting "enable-web" value to "true".
You may need to restart any open editors for them to read new settings.
```

```
➜  temp flutter devices
2 connected devices:

Web Server (web) • web-server • web-javascript • Flutter Tools
Chrome (web)     • chrome     • web-javascript • Google Chrome 84.0.4147.89
```

```
➜  temp flutter create myapp
Creating project myapp...
  myapp/ios/Runner.xcworkspace/contents.xcworkspacedata (created)
  myapp/ios/Runner.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist (created)
  myapp/ios/Runner.xcworkspace/xcshareddata/WorkspaceSettings.xcsettings (created)
  myapp/ios/Runner/Info.plist (created)
  myapp/ios/Runner/Assets.xcassets/LaunchImage.imageset/LaunchImage@2x.png (created)
  myapp/ios/Runner/Assets.xcassets/LaunchImage.imageset/LaunchImage@3x.png (created)
  myapp/ios/Runner/Assets.xcassets/LaunchImage.imageset/README.md (created)
  myapp/ios/Runner/Assets.xcassets/LaunchImage.imageset/Contents.json (created)
  myapp/ios/Runner/Assets.xcassets/LaunchImage.imageset/LaunchImage.png (created)
  myapp/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-76x76@2x.png (created)
  myapp/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-29x29@1x.png (created)
  myapp/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-40x40@1x.png (created)
  myapp/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-20x20@1x.png (created)
  myapp/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-1024x1024@1x.png (created)
  myapp/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-83.5x83.5@2x.png (created)
  myapp/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-20x20@3x.png (created)
  myapp/ios/Runner/Assets.xcassets/AppIcon.appiconset/Contents.json (created)
  myapp/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-20x20@2x.png (created)
  myapp/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-29x29@3x.png (created)
  myapp/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-40x40@2x.png (created)
  myapp/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-60x60@3x.png (created)
  myapp/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-60x60@2x.png (created)
  myapp/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-76x76@1x.png (created)
  myapp/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-40x40@3x.png (created)
  myapp/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-29x29@2x.png (created)
  myapp/ios/Runner/Base.lproj/LaunchScreen.storyboard (created)
  myapp/ios/Runner/Base.lproj/Main.storyboard (created)
  myapp/ios/Runner.xcodeproj/project.xcworkspace/contents.xcworkspacedata (created)
  myapp/ios/Runner.xcodeproj/project.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist (created)
  myapp/ios/Runner.xcodeproj/project.xcworkspace/xcshareddata/WorkspaceSettings.xcsettings (created)
  myapp/ios/Runner.xcodeproj/xcshareddata/xcschemes/Runner.xcscheme (created)
  myapp/ios/Flutter/Debug.xcconfig (created)
  myapp/ios/Flutter/Release.xcconfig (created)
  myapp/ios/Flutter/AppFrameworkInfo.plist (created)
  myapp/ios/.gitignore (created)
  myapp/test/widget_test.dart (created)
  myapp/myapp.iml (created)
  myapp/.gitignore (created)
  myapp/web/favicon.png (created)
  myapp/web/index.html (created)
  myapp/web/manifest.json (created)
  myapp/web/icons/Icon-192.png (created)
  myapp/web/icons/Icon-512.png (created)
  myapp/.metadata (created)
  myapp/android/app/src/profile/AndroidManifest.xml (created)
  myapp/android/app/src/main/res/mipmap-mdpi/ic_launcher.png (created)
  myapp/android/app/src/main/res/mipmap-hdpi/ic_launcher.png (created)
  myapp/android/app/src/main/res/drawable/launch_background.xml (created)
  myapp/android/app/src/main/res/mipmap-xxxhdpi/ic_launcher.png (created)
  myapp/android/app/src/main/res/mipmap-xxhdpi/ic_launcher.png (created)
  myapp/android/app/src/main/res/values/styles.xml (created)
  myapp/android/app/src/main/res/mipmap-xhdpi/ic_launcher.png (created)
  myapp/android/app/src/main/AndroidManifest.xml (created)
  myapp/android/app/src/debug/AndroidManifest.xml (created)
  myapp/android/gradle/wrapper/gradle-wrapper.properties (created)
  myapp/android/gradle.properties (created)
  myapp/android/.gitignore (created)
  myapp/android/settings.gradle (created)
  myapp/android/app/build.gradle (created)
  myapp/android/app/src/main/kotlin/com/example/myapp/MainActivity.kt (created)
  myapp/android/build.gradle (created)
  myapp/android/myapp_android.iml (created)
  myapp/pubspec.yaml (created)
  myapp/README.md (created)
  myapp/ios/Runner/Runner-Bridging-Header.h (created)
  myapp/ios/Runner/AppDelegate.swift (created)
  myapp/ios/Runner.xcodeproj/project.pbxproj (created)
  myapp/lib/main.dart (created)
  myapp/.idea/runConfigurations/main_dart.xml (created)
  myapp/.idea/libraries/Dart_SDK.xml (created)
  myapp/.idea/libraries/KotlinJavaRuntime.xml (created)
  myapp/.idea/modules.xml (created)
  myapp/.idea/workspace.xml (created)
Running "flutter pub get" in myapp...                                  1.2s
Wrote 76 files.

All done!
myapp
[✓] Flutter: is fully installed. (Channel beta, 1.20.0-7.2.pre, on Mac OS X 10.15.2 19C57, locale en-US)
[!] Android toolchain - develop for Android devices: is partially installed; more components are available. (Android SDK
    version 30.0.0)
[✓] Xcode - develop for iOS and macOS: is fully installed. (Xcode 11.4)
[✓] Chrome - develop for the web: is fully installed.
[✓] Android Studio: is fully installed. (version 4.0)
[!] IntelliJ IDEA Ultimate Edition: is partially installed; more components are available. (version 2020.1.3)
[✓] Connected device: is fully installed. (2 available)
```

```
➜  temp cd myapp
➜  myapp flutter run -d chrome
Launching lib/main.dart on Chrome in debug mode...
Syncing files to device Chrome...                                       
11,001ms (!)                                       
ERROR - 2020-07-21 16:25:49.135748
GET /dwds/src/injected/client.js
Error thrown by handler.
NoSuchMethodError: The method 'toFilePath' was called on null.
Receiver: null
Tried calling: toFilePath()
dart:core                                      Object.noSuchMethod
package:dwds/src/handlers/injector.dart 51:41  DwdsInjector.middleware.<fn>.<fn>
```

</p>
</details>

**Comment by grouma** [comment]
This implies the prebuilt [client.js](https://github.com/dart-lang/webdev/blob/master/dwds/lib/src/injected/client.js) isn't resolved [here](https://github.com/dart-lang/webdev/blob/caba0d766759150b8c7a63c3be3ee2a61519f6f9/dwds/lib/src/handlers/injector.dart#L51).

I'm not sure why the package resolver would not be able to load that file if `package:dwds` is a dependency of Flutter Tools. @jonahwilliams thoughts?

**Comment by jaysephjw** [comment]
Update: I tried it out on dev, ` 1.21.0-1.0.pre`, and it worked. Now when I switch back to beta, beta works. Beta also now works from a fresh project.

If I then delete the flutter install, and re-install on beta, beta is broken again.  So building from dev cached something in the flutter dir to make it happy.

```
Flutter 1.21.0-1.0.pre • channel dev • https://github.com/flutter/flutter.git
Framework • revision f25bd9c55c (7 days ago) • 2020-07-14 20:26:01 -0400
Engine • revision 99c2b3a245
Tools • Dart 2.9.0 (build 2.9.0-21.0.dev 20bf2fcf56)
```

**Comment by DeepStyles** [comment]
I had same issue on new project not working on web... Even added dwds package not solved anyone know anything???


Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel dev, 1.21.0-1.0.pre, on Microsoft Windows [Version 10.0.18363.959], locale en-US)

[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[√] Chrome - develop for the web
[√] Android Studio (version 4.0)
[√] VS Code (version 1.47.3)
[√] Connected device (4 available)

Launching lib\main.dart on Chrome in debug mode...
ERROR - 2020-08-08 06:49:05.954007
GET /dwds/src/injected/client.js
Error thrown by handler.
NoSuchMethodError: The method 'toFilePath' was called on null.
Receiver: null
Tried calling: toFilePath()
dart:core                                      Object.noSuchMethod
DwdsInjector.middleware.<fn>.<fn>
package:dwds/…/handlers/injector.dart:51

**Comment by DeepStyles** [comment]
> I had same issue on new project not working on web... Even added dwds package not solved anyone know anything???
> 
> Doctor summary (to see all details, run flutter doctor -v):
> [√] Flutter (Channel dev, 1.21.0-1.0.pre, on Microsoft Windows [Version 10.0.18363.959], locale en-US)
> 
> [√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
> [√] Chrome - develop for the web
> [√] Android Studio (version 4.0)
> [√] VS Code (version 1.47.3)
> [√] Connected device (4 available)
> 
> Launching lib\main.dart on Chrome in debug mode...
> ERROR - 2020-08-08 06:49:05.954007
> GET /dwds/src/injected/client.js
> Error thrown by handler.
> NoSuchMethodError: The method 'toFilePath' was called on null.
> Receiver: null
> Tried calling: toFilePath()
> dart:core Object.noSuchMethod
> DwdsInjector.middleware..
> package:dwds/…/handlers/injector.dart:51

ok flutter packages-update solved it

**Comment by markusaksli-nc** [comment]
@jonahwilliams It seems like the recent comments here and https://github.com/flutter/flutter/issues/58110, https://github.com/flutter/flutter/issues/58944, and https://github.com/flutter/flutter/issues/63896 (Aug 16) warrant opening this up again.

All of these are getting an error with [client.js](https://github.com/dart-lang/webdev/blob/master/dwds/lib/src/injected/client.js) after upgrading/enabling.

```
GET /dwds/src/injected/client.js
Error thrown by handler.
NoSuchMethodError: The method 'toFilePath' was called on null.
Receiver: null
Tried calling: toFilePath()
dart:core                                              Object.noSuchMethod
package:dwds/src/handlers/injected_handler.dart 35:39  createInjectedHandler.<fn>.<fn>
```

**Comment by jadedResearcher** [comment]
It was happening to me previously, then I added   dwds: ^7.1.1 to my dependencies and it resolved. now its back.
