### ISSUE TITLE
"node._relayoutBoundary == _relayoutBoundary" opening Gallery

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#44475]
If you start the gallery with your screen locked, then unlock your screen:

```
D/FlutterView(19821): Attaching to a FlutterEngine: io.flutter.embedding.engine.FlutterEngine@1da3524
D/FlutterView(19821): Already attached to this engine. Doing nothing.
I/flutter (19821): ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
I/flutter (19821): The following assertion was thrown building LayoutBuilder:
I/flutter (19821): 'package:flutter/src/rendering/object.dart': Failed assertion: line 1435 pos 14:
I/flutter (19821): 'node._relayoutBoundary == _relayoutBoundary': is not true.
I/flutter (19821): 
I/flutter (19821): Either the assertion indicates an error in the framework itself, or we should provide substantially
I/flutter (19821): more information in this error message to help you determine and fix the underlying cause.
I/flutter (19821): In either case, please report this assertion by filing a bug on GitHub:
I/flutter (19821):   https://github.com/flutter/flutter/issues/new?template=BUG.md
I/flutter (19821): 
I/flutter (19821): The relevant error-causing widget was:
I/flutter (19821):   LayoutBuilder
I/flutter (19821):   file:///usr/local/google/home/ianh/dev/flutter/examples/flutter_gallery/lib/gallery/home.dart:122:16
I/flutter (19821): 
I/flutter (19821): When the exception was thrown, this was the stack:
I/flutter (19821): #2      RenderObject._debugSubtreeRelayoutRootAlreadyMarkedNeedsLayout (package:flutter/src/rendering/object.dart:1435:14)
I/flutter (19821): #3      RenderObject.markNeedsLayout (package:flutter/src/rendering/object.dart:1486:14)
I/flutter (19821): #4      RenderBox.markNeedsLayout (package:flutter/src/rendering/box.dart:2047:11)
I/flutter (19821): #5      RenderObject.markParentNeedsLayout (package:flutter/src/rendering/object.dart:1520:14)
I/flutter (19821): #6      RenderObject.markNeedsLayout (package:flutter/src/rendering/object.dart:1491:7)
I/flutter (19821): #7      RenderBox.markNeedsLayout (package:flutter/src/rendering/box.dart:2047:11)
I/flutter (19821): #8      RenderConstrainedBox.additionalConstraints= (package:flutter/src/rendering/proxy_box.dart:209:5)
I/flutter (19821): #9      SizedBox.updateRenderObject (package:flutter/src/widgets/basic.dart:2088:18)
I/flutter (19821): #10     RenderObjectElement.update (package:flutter/src/widgets/framework.dart:4790:12)
I/flutter (19821): #11     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:5170:11)
I/flutter (19821): #12     Element.updateChild (package:flutter/src/widgets/framework.dart:2892:15)
I/flutter (19821): #13     RenderObjectElement.updateChildren (package:flutter/src/widgets/framework.dart:4881:32)
I/flutter (19821): #14     MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:5281:17)
I/flutter (19821): #15     Element.updateChild (package:flutter/src/widgets/framework.dart:2892:15)
I/flutter (19821): #16     RenderObjectElement.updateChildren (package:flutter/src/widgets/framework.dart:4881:32)
I/flutter (19821): #17     MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:5281:17)
I/flutter (19821): #18     Element.updateChild (package:flutter/src/widgets/framework.dart:2892:15)
I/flutter (19821): #19     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:5172:14)
I/flutter (19821): #20     Element.updateChild (package:flutter/src/widgets/framework.dart:2892:15)
I/flutter (19821): #21     _LayoutBuilderElement._layout.<anonymous closure> (package:flutter/src/widgets/layout_builder.dart:115:18)
I/flutter (19821): #22     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2327:19)
I/flutter (19821): #23     _LayoutBuilderElement._layout (package:flutter/src/widgets/layout_builder.dart:95:11)
I/flutter (19821): #24     RenderObject.invokeLayoutCallback.<anonymous closure> (package:flutter/src/rendering/object.dart:1815:58)
I/flutter (19821): #25     PipelineOwner._enableMutationsToDirtySubtrees (package:flutter/src/rendering/object.dart:875:15)
I/flutter (19821): #26     RenderObject.invokeLayoutCallback (package:flutter/src/rendering/object.dart:1815:13)
I/flutter (19821): #27     RenderConstrainedLayoutBuilder.layoutAndBuildChild (package:flutter/src/widgets/layout_builder.dart:173:5)
I/flutter (19821): #28     _RenderLayoutBuilder.performLayout (package:flutter/src/widgets/layout_builder.dart:240:5)
I/flutter (19821): #29     RenderObject.layout (package:flutter/src/rendering/object.dart:1716:7)
I/flutter (19821): #30     _RenderSingleChildViewport.performLayout (package:flutter/src/widgets/single_child_scroll_view.dart:497:13)
I/flutter (19821): #31     RenderObject.layout (package:flutter/src/rendering/object.dart:1716:7)
I/flutter (19821): #32     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter (19821): #33     RenderObject.layout (package:flutter/src/rendering/object.dart:1716:7)
I/flutter (19821): #34     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter (19821): #35     RenderObject.layout (package:flutter/src/rendering/object.dart:1716:7)
I/flutter (19821): #36     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter (19821): #37     RenderObject.layout (package:flutter/src/rendering/object.dart:1716:7)
I/flutter (19821): #38     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter (19821): #39     RenderObject.layout (package:flutter/src/rendering/object.dart:1716:7)
I/flutter (19821): #40     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter (19821): #41     RenderObject.layout (package:flutter/src/rendering/object.dart:1716:7)
I/flutter (19821): #42     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter (19821): #43     RenderObject.layout (package:flutter/src/rendering/object.dart:1716:7)
I/flutter (19821): #44     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter (19821): #45     RenderObject.layout (package:flutter/src/rendering/object.dart:1716:7)
I/flutter (19821): #46     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter (19821): #47     RenderObject.layout (package:flutter/src/rendering/object.dart:1716:7)
I/flutter (19821): #48     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter (19821): #49     RenderObject.layout (package:flutter/src/rendering/object.dart:1716:7)
I/flutter (19821): #50     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter (19821): #51     RenderObject.layout (package:flutter/src/rendering/object.dart:1716:7)
I/flutter (19821): #52     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter (19821): #53     RenderObject.layout (package:flutter/src/rendering/object.dart:1716:7)
I/flutter (19821): #54     RenderStack.performLayout (package:flutter/src/rendering/stack.dart:505:15)
I/flutter (19821): #55     RenderObject.layout (package:flutter/src/rendering/object.dart:1716:7)
I/flutter (19821): #56     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter (19821): #57     RenderObject.layout (package:flutter/src/rendering/object.dart:1716:7)
I/flutter (19821): #58     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter (19821): #59     RenderObject.layout (package:flutter/src/rendering/object.dart:1716:7)
I/flutter (19821): #60     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter (19821): #61     _RenderCustomClip.performLayout (package:flutter/src/rendering/proxy_box.dart:1234:11)
I/flutter (19821): #62     RenderObject.layout (package:flutter/src/rendering/object.dart:1716:7)
I/flutter (19821): #63     RenderStack.performLayout (package:flutter/src/rendering/stack.dart:544:15)
I/flutter (19821): #64     RenderObject.layout (package:flutter/src/rendering/object.dart:1716:7)
I/flutter (19821): #65     _RenderLayoutBuilder.performLayout (package:flutter/src/widgets/layout_builder.dart:242:13)
I/flutter (19821): #66     RenderObject.layout (package:flutter/src/rendering/object.dart:1716:7)
I/flutter (19821): #67     RenderPadding.performLayout (package:flutter/src/rendering/shifted_box.dart:206:11)
I/flutter (19821): #68     RenderObject.layout (package:flutter/src/rendering/object.dart:1716:7)
I/flutter (19821): #69     MultiChildLayoutDelegate.layoutChild (package:flutter/src/rendering/custom_layout.dart:163:11)
I/flutter (19821): #70     _ScaffoldLayout.performLayout (package:flutter/src/material/scaffold.dart:477:7)
I/flutter (19821): #71     MultiChildLayoutDelegate._callPerformLayout (package:flutter/src/rendering/custom_layout.dart:232:7)
I/flutter (19821): #72     RenderCustomMultiChildLayoutBox.performLayout (package:flutter/src/rendering/custom_layout.dart:391:14)
I/flutter (19821): #73     RenderObject.layout (package:flutter/src/rendering/object.dart:1716:7)
I/flutter (19821): #74     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter (19821): #75     RenderObject.layout (package:flutter/src/rendering/object.dart:1716:7)
I/flutter (19821): #76     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter (19821): #77     _RenderCustomClip.performLayout (package:flutter/src/rendering/proxy_box.dart:1234:11)
I/flutter (19821): #78     RenderObject.layout (package:flutter/src/rendering/object.dart:1716:7)
I/flutter (19821): #79     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter (19821): #80     RenderObject.layout (package:flutter/src/rendering/object.dart:1716:7)
I/flutter (19821): #81     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter (19821): #82     RenderObject.layout (package:flutter/src/rendering/object.dart:1716:7)
I/flutter (19821): #83     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter (19821): #84     RenderObject.layout (package:flutter/src/rendering/object.dart:1716:7)
I/flutter (19821): #85     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter (19821): #86     RenderObject.layout (package:flutter/src/rendering/object.dart:1716:7)
I/flutter (19821): #87     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter (19821): #88     RenderObject.layout (package:flutter/src/rendering/object.dart:1716:7)
I/flutter (19821): #89     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter (19821): #90     RenderObject.layout (package:flutter/src/rendering/object.dart:1716:7)
I/flutter (19821): #91     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter (19821): #92     RenderObject.layout (package:flutter/src/rendering/object.dart:1716:7)
I/flutter (19821): #93     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter (19821): #94     RenderObject.layout (package:flutter/src/rendering/object.dart:1716:7)
I/flutter (19821): #95     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter (19821): #96     RenderOffstage.performLayout (package:flutter/src/rendering/proxy_box.dart:3161:13)
I/flutter (19821): #97     RenderObject.layout (package:flutter/src/rendering/object.dart:1716:7)
I/flutter (19821): #98     RenderStack.performLayout (package:flutter/src/rendering/stack.dart:505:15)
I/flutter (19821): #99     RenderObject.layout (package:flutter/src/rendering/object.dart:1716:7)
I/flutter (19821): #100    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter (19821): #101    RenderObject.layout (package:flutter/src/rendering/object.dart:1716:7)
I/flutter (19821): #102    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter (19821): #103    RenderObject.layout (package:flutter/src/rendering/object.dart:1716:7)
I/flutter (19821): #104    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter (19821): #105    RenderObject.layout (package:flutter/src/rendering/object.dart:1716:7)
I/flutter (19821): #106    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter (19821): #107    RenderObject.layout (package:flutter/src/rendering/object.dart:1716:7)
I/flutter (19821): #108    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter (19821): #109    RenderObject.layout (package:flutter/src/rendering/object.dart:1716:7)
I/flutter (19821): #110    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter (19821): #111    RenderObject.layout (package:flutter/src/rendering/object.dart:1716:7)
I/flutter (19821): #112    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter (19821): #113    RenderObject.layout (package:flutter/src/rendering/object.dart:1716:7)
I/flutter (19821): #114    RenderView.performLayout (package:flutter/src/rendering/view.dart:164:13)
I/flutter (19821): #115    RenderObject._layoutWithoutResize (package:flutter/src/rendering/object.dart:1584:7)
I/flutter (19821): #116    PipelineOwner.flushLayout (package:flutter/src/rendering/object.dart:844:18)
I/flutter (19821): #117    RendererBinding.drawFrame (package:flutter/src/rendering/binding.dart:344:19)
I/flutter (19821): #118    WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:774:13)
I/flutter (19821): #119    RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:283:5)
I/flutter (19821): #120    SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1097:15)
I/flutter (19821): #121    SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1036:9)
I/flutter (19821): #122    SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:952:5)
I/flutter (19821): #126    _invoke (dart:ui/hooks.dart:259:10)
I/flutter (19821): #127    _drawFrame (dart:ui/hooks.dart:217:3)
I/flutter (19821): (elided 5 frames from class _AssertionError and package dart:async)
I/flutter (19821): 
I/flutter (19821): ════════════════════════════════════════════════════════════════════════════════════════════════════
```

There's a bunch of bugs that have this assert:
https://github.com/flutter/flutter/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+%22node._relayoutBoundary+%3D%3D+_relayoutBoundary%22

cc @goderbauer @HansMuller

**Comment by Hixie** [comment]
dupe of https://github.com/flutter/flutter/issues/39151
