### ISSUE TITLE
_describeRelevantUserCode crash

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#44485]
testWidgets('Does Text', (WidgetTester tester) async {
    await tester.pumpWidget(const Text('tight'));
    await tester.pumpWidget(const SizedBox(child: Text('loose')));
  });

I expected three exceptions, one from each pump, plus a third saying that I hadn't caught the first exception (you're supposed to call takeException after pump if pump throws).

However, one of those exceptions triggered a cascade of other exceptions because of some problem in _describeRelevantUserCode:

```
══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
The following assertion was thrown attaching to the render tree:
Looking up a deactivated widget's ancestor is unsafe.
At this point the state of the widget's element tree is no longer stable.
To safely refer to a widget's ancestor in its dispose() method, save a reference to the ancestor by
calling inheritFromWidgetOfExactType() in the widget's didChangeDependencies() method.

When the exception was thrown, this was the stack:
#0      Element._debugCheckStateIsActiveForAncestorLookup.<anonymous closure> (package:flutter/src/widgets/framework.dart:3423:9)
#1      Element._debugCheckStateIsActiveForAncestorLookup (package:flutter/src/widgets/framework.dart:3437:6)
#2      Element.visitAncestorElements (package:flutter/src/widgets/framework.dart:3524:12)
#3      _describeRelevantUserCode (package:flutter/src/widgets/widget_inspector.dart:2827:13)
#4      _parseDiagnosticsNode (package:flutter/src/widgets/widget_inspector.dart:2794:10)
#5      transformDebugCreator (package:flutter/src/widgets/widget_inspector.dart:2774:14)
#6      _SyncIterator.moveNext (dart:core-patch/core_patch.dart:144:12)
#7      new List.from (dart:core-patch/array_patch.dart:45:19)
#8      Iterable.toList (dart:core/iterable.dart:398:5)
#9      _FlutterErrorDetailsNode.builder (package:flutter/src/foundation/assertions.dart:840:66)
#10     DiagnosticableNode.getProperties (package:flutter/src/foundation/diagnostics.dart:2914:87)
#11     TextTreeRenderer.render (package:flutter/src/foundation/diagnostics.dart:1225:63)
#12     FlutterError.dumpErrorToConsole (package:flutter/src/foundation/assertions.dart:647:11)
#13     TestWidgetsFlutterBinding._runTest.<anonymous closure> (package:flutter_test/src/binding.dart:577:24)
#14     FlutterError.reportError (package:flutter/src/foundation/assertions.dart:736:14)
#15     _debugReportException (package:flutter/src/widgets/framework.dart:5314:16)
#16     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3982:9)
#17     Element.rebuild (package:flutter/src/widgets/framework.dart:3755:5)
#18     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3941:5)
#19     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3936:5)
#20     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3109:14)
#21     Element.updateChild (package:flutter/src/widgets/framework.dart:2903:12)
#22     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5165:14)
#23     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3109:14)
#24     Element.updateChild (package:flutter/src/widgets/framework.dart:2903:12)
#25     RenderObjectToWidgetElement._rebuild (package:flutter/src/widgets/binding.dart:1028:16)
#26     RenderObjectToWidgetElement.update (package:flutter/src/widgets/binding.dart:1006:5)
#27     RenderObjectToWidgetElement.performRebuild (package:flutter/src/widgets/binding.dart:1020:7)
#28     Element.rebuild (package:flutter/src/widgets/framework.dart:3755:5)
#29     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2347:33)
#30     AutomatedTestWidgetsFlutterBinding.drawFrame (package:flutter_test/src/binding.dart:975:18)
#31     RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:283:5)
#32     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1097:15)
#33     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1036:9)
#34     AutomatedTestWidgetsFlutterBinding.pump.<anonymous closure> (package:flutter_test/src/binding.dart:873:9)
#37     TestAsyncUtils.guard (package:flutter_test/src/test_async_utils.dart:69:41)
#38     AutomatedTestWidgetsFlutterBinding.pump (package:flutter_test/src/binding.dart:860:27)
#39     WidgetTester.pumpWidget.<anonymous closure> (package:flutter_test/src/widget_tester.dart:320:22)
#42     TestAsyncUtils.guard (package:flutter_test/src/test_async_utils.dart:69:41)
#43     WidgetTester.pumpWidget (package:flutter_test/src/widget_tester.dart:317:27)
#44     main.<anonymous closure> (/usr/local/google/home/ianh/dev/flutter/packages/flutter/test/rendering/repaint_boundary_2_test.dart:12:18)
<asynchronous suspension>
#45     testWidgets.<anonymous closure>.<anonymous closure> (package:flutter_test/src/widget_tester.dart:121:25)
<asynchronous suspension>
#46     TestWidgetsFlutterBinding._runTestBody (package:flutter_test/src/binding.dart:695:19)
<asynchronous suspension>
#49     TestWidgetsFlutterBinding._runTest (package:flutter_test/src/binding.dart:678:14)
#50     AutomatedTestWidgetsFlutterBinding.runTest.<anonymous closure> (package:flutter_test/src/binding.dart:1051:24)
#56     AutomatedTestWidgetsFlutterBinding.runTest (package:flutter_test/src/binding.dart:1048:15)
#57     testWidgets.<anonymous closure> (package:flutter_test/src/widget_tester.dart:118:22)
#58     Declarer.test.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:test_api/src/backend/declarer.dart:168:27)
<asynchronous suspension>
#59     Invoker.waitForOutstandingCallbacks.<anonymous closure> (package:test_api/src/backend/invoker.dart:250:15)
<asynchronous suspension>
#64     Invoker.waitForOutstandingCallbacks (package:test_api/src/backend/invoker.dart:247:5)
#65     Declarer.test.<anonymous closure>.<anonymous closure> (package:test_api/src/backend/declarer.dart:166:33)
#70     Declarer.test.<anonymous closure> (package:test_api/src/backend/declarer.dart:165:13)
<asynchronous suspension>
#71     Invoker._onRun.<anonymous closure>.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:test_api/src/backend/invoker.dart:400:25)
<asynchronous suspension>
#85     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:382:19)
#86     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:416:5)
#87     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:12)
(elided 32 frames from class _FakeAsync, package dart:async, package dart:async-patch, and package stack_trace)
════════════════════════════════════════════════════════════════════════════════════════════════════
...
```

cc @chunhtai @goderbauer @jacob314

**Comment by chunhtai** [comment]
I cannot reproduce it
Here is my code
```dart
import 'package:flutter/material.dart';
import 'package:flutter_test/flutter_test.dart';

void main() {
  testWidgets('Does Text', (WidgetTester tester) async {
    await tester.pumpWidget(const Text('tight'));
    await tester.pumpWidget(const SizedBox(child: Text('loose')));
  });
}
```

Here is the error message, which looks correct to me
```
══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
The following assertion was thrown building Text("tight"):
No Directionality widget found.
RichText widgets require a Directionality widget ancestor.
The specific widget that could not find a Directionality ancestor was:
  RichText
The ownership chain for the affected widget is: "RichText ← Text ← [root]"
Typically, the Directionality widget is introduced by the MaterialApp or WidgetsApp widget at the
top of your application widget tree. It determines the ambient reading direction and is used, for
example, to determine how to lay out text, how to interpret "start" and "end" values, and to resolve
EdgeInsetsDirectional, AlignmentDirectional, and other *Directional objects.

The relevant error-causing widget was:
  Text file:///Users/chtai/apps/draw/test/widget_test.dart:13:35

When the exception was thrown, this was the stack:
#0      debugCheckHasDirectionality.<anonymous closure> (package:flutter/src/widgets/debug.dart:243:7)
#1      debugCheckHasDirectionality (package:flutter/src/widgets/debug.dart:259:4)
#2      RichText.createRenderObject (package:flutter/src/widgets/basic.dart:5113:37)
#3      RenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4772:28)
#4      MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5267:11)
#5      Element.inflateWidget (package:flutter/src/widgets/framework.dart:3109:14)
#6      Element.updateChild (package:flutter/src/widgets/framework.dart:2903:12)
#7      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3978:16)
#8      Element.rebuild (package:flutter/src/widgets/framework.dart:3755:5)
#9      ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3941:5)
#10     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3936:5)
#11     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3109:14)
#12     Element.updateChild (package:flutter/src/widgets/framework.dart:2903:12)
#13     RenderObjectToWidgetElement._rebuild (package:flutter/src/widgets/binding.dart:1028:16)
#14     RenderObjectToWidgetElement.update (package:flutter/src/widgets/binding.dart:1006:5)
#15     RenderObjectToWidgetElement.performRebuild (package:flutter/src/widgets/binding.dart:1020:7)
#16     Element.rebuild (package:flutter/src/widgets/framework.dart:3755:5)
#17     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2347:33)
#18     AutomatedTestWidgetsFlutterBinding.drawFrame (package:flutter_test/src/binding.dart:975:18)
#19     RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:283:5)
#20     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1097:15)
#21     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1036:9)
#22     AutomatedTestWidgetsFlutterBinding.pump.<anonymous closure> (package:flutter_test/src/binding.dart:873:9)
#25     TestAsyncUtils.guard (package:flutter_test/src/test_async_utils.dart:69:41)
#26     AutomatedTestWidgetsFlutterBinding.pump (package:flutter_test/src/binding.dart:860:27)
#27     WidgetTester.pumpWidget.<anonymous closure> (package:flutter_test/src/widget_tester.dart:320:22)
#30     TestAsyncUtils.guard (package:flutter_test/src/test_async_utils.dart:69:41)
#31     WidgetTester.pumpWidget (package:flutter_test/src/widget_tester.dart:317:27)
#32     main.<anonymous closure> (file:///Users/chtai/apps/draw/test/widget_test.dart:13:18)
<asynchronous suspension>
#33     testWidgets.<anonymous closure>.<anonymous closure> (package:flutter_test/src/widget_tester.dart:121:25)
<asynchronous suspension>
#34     TestWidgetsFlutterBinding._runTestBody (package:flutter_test/src/binding.dart:695:19)
<asynchronous suspension>
#37     TestWidgetsFlutterBinding._runTest (package:flutter_test/src/binding.dart:678:14)
#38     AutomatedTestWidgetsFlutterBinding.runTest.<anonymous closure> (package:flutter_test/src/binding.dart:1051:24)
#44     AutomatedTestWidgetsFlutterBinding.runTest (package:flutter_test/src/binding.dart:1048:15)
#45     testWidgets.<anonymous closure> (package:flutter_test/src/widget_tester.dart:118:22)
#46     Declarer.test.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:test_api/src/backend/declarer.dart:168:27)
<asynchronous suspension>
#47     Invoker.waitForOutstandingCallbacks.<anonymous closure> (package:test_api/src/backend/invoker.dart:250:15)
<asynchronous suspension>
#52     Invoker.waitForOutstandingCallbacks (package:test_api/src/backend/invoker.dart:247:5)
#53     Declarer.test.<anonymous closure>.<anonymous closure> (package:test_api/src/backend/declarer.dart:166:33)
#58     Declarer.test.<anonymous closure> (package:test_api/src/backend/declarer.dart:165:13)
<asynchronous suspension>
#59     Invoker._onRun.<anonymous closure>.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:test_api/src/backend/invoker.dart:400:25)
<asynchronous suspension>
#73     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:382:19)
#74     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:416:5)
#75     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:12)
(elided 32 frames from class _FakeAsync, package dart:async, package dart:async-patch, and package stack_trace)

════════════════════════════════════════════════════════════════════════════════════════════════════
══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
The following assertion was thrown building Text("loose"):
No Directionality widget found.
RichText widgets require a Directionality widget ancestor.
The specific widget that could not find a Directionality ancestor was:
  RichText
The ownership chain for the affected widget is: "RichText ← Text ← SizedBox ← [root]"
Typically, the Directionality widget is introduced by the MaterialApp or WidgetsApp widget at the
top of your application widget tree. It determines the ambient reading direction and is used, for
example, to determine how to lay out text, how to interpret "start" and "end" values, and to resolve
EdgeInsetsDirectional, AlignmentDirectional, and other *Directional objects.

The relevant error-causing widget was:
  Text file:///Users/chtai/apps/draw/test/widget_test.dart:14:51

When the exception was thrown, this was the stack:
#0      debugCheckHasDirectionality.<anonymous closure> (package:flutter/src/widgets/debug.dart:243:7)
#1      debugCheckHasDirectionality (package:flutter/src/widgets/debug.dart:259:4)
#2      RichText.createRenderObject (package:flutter/src/widgets/basic.dart:5113:37)
#3      RenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4772:28)
#4      MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5267:11)
#5      Element.inflateWidget (package:flutter/src/widgets/framework.dart:3109:14)
#6      Element.updateChild (package:flutter/src/widgets/framework.dart:2903:12)
#7      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3978:16)
#8      Element.rebuild (package:flutter/src/widgets/framework.dart:3755:5)
#9      ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3941:5)
#10     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3936:5)
#11     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3109:14)
#12     Element.updateChild (package:flutter/src/widgets/framework.dart:2903:12)
#13     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5165:14)
#14     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3109:14)
#15     Element.updateChild (package:flutter/src/widgets/framework.dart:2903:12)
#16     RenderObjectToWidgetElement._rebuild (package:flutter/src/widgets/binding.dart:1028:16)
#17     RenderObjectToWidgetElement.update (package:flutter/src/widgets/binding.dart:1006:5)
#18     RenderObjectToWidgetElement.performRebuild (package:flutter/src/widgets/binding.dart:1020:7)
#19     Element.rebuild (package:flutter/src/widgets/framework.dart:3755:5)
#20     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2347:33)
#21     AutomatedTestWidgetsFlutterBinding.drawFrame (package:flutter_test/src/binding.dart:975:18)
#22     RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:283:5)
#23     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1097:15)
#24     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1036:9)
#25     AutomatedTestWidgetsFlutterBinding.pump.<anonymous closure> (package:flutter_test/src/binding.dart:873:9)
#28     TestAsyncUtils.guard (package:flutter_test/src/test_async_utils.dart:69:41)
#29     AutomatedTestWidgetsFlutterBinding.pump (package:flutter_test/src/binding.dart:860:27)
#30     WidgetTester.pumpWidget.<anonymous closure> (package:flutter_test/src/widget_tester.dart:320:22)
#33     TestAsyncUtils.guard (package:flutter_test/src/test_async_utils.dart:69:41)
#34     WidgetTester.pumpWidget (package:flutter_test/src/widget_tester.dart:317:27)
#35     main.<anonymous closure> (file:///Users/chtai/apps/draw/test/widget_test.dart:14:18)
<asynchronous suspension>
#36     testWidgets.<anonymous closure>.<anonymous closure> (package:flutter_test/src/widget_tester.dart:121:25)
<asynchronous suspension>
#37     TestWidgetsFlutterBinding._runTestBody (package:flutter_test/src/binding.dart:695:19)
<asynchronous suspension>
#40     TestWidgetsFlutterBinding._runTest (package:flutter_test/src/binding.dart:678:14)
#41     AutomatedTestWidgetsFlutterBinding.runTest.<anonymous closure> (package:flutter_test/src/binding.dart:1051:24)
#47     AutomatedTestWidgetsFlutterBinding.runTest (package:flutter_test/src/binding.dart:1048:15)
#48     testWidgets.<anonymous closure> (package:flutter_test/src/widget_tester.dart:118:22)
#49     Declarer.test.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:test_api/src/backend/declarer.dart:168:27)
<asynchronous suspension>
#50     Invoker.waitForOutstandingCallbacks.<anonymous closure> (package:test_api/src/backend/invoker.dart:250:15)
<asynchronous suspension>
#55     Invoker.waitForOutstandingCallbacks (package:test_api/src/backend/invoker.dart:247:5)
#56     Declarer.test.<anonymous closure>.<anonymous closure> (package:test_api/src/backend/declarer.dart:166:33)
#61     Declarer.test.<anonymous closure> (package:test_api/src/backend/declarer.dart:165:13)
<asynchronous suspension>
#62     Invoker._onRun.<anonymous closure>.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:test_api/src/backend/invoker.dart:400:25)
<asynchronous suspension>
#76     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:382:19)
#77     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:416:5)
#78     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:12)
(elided 32 frames from class _FakeAsync, package dart:async, package dart:async-patch, and package stack_trace)

════════════════════════════════════════════════════════════════════════════════════════════════════
══╡ EXCEPTION CAUGHT BY FLUTTER TEST FRAMEWORK ╞════════════════════════════════════════════════════
The following message was thrown:
Multiple exceptions (2) were detected during the running of the current test, and at least one was
unexpected.
════════════════════════════════════════════════════════════════════════════════════════════════════

```

**Comment by Hixie** [comment]
Odd...

**Comment by Hixie** [comment]
My steps to reproduce:
1. check out tip of tree flutter/flutter (I was on 076bea38f2).
2. create `packages/flutter/test/widgets/44485_test.dart` and fill it with the exact text from @chunhtai's comment above.
3. from the packages/flutter directory, run `flutter test test/widgets/44485_test.dart`.

(I have `FLUTTER_TOOL_ARGS=--enable-asserts` set in my environment, though that doesn't seem to affect anything here.)

**Comment by goderbauer** [comment]
This is re-producing for me as well on HEAD.

@chunhtai Where you running this on HEAD?

**Comment by goderbauer** [comment]
I am a little concerned about this one: We are crashing while generating an error message. That crash is swallowing the actual error.

**Comment by chunhtai** [comment]
I can reproduce it, I was testing it outside the flutter package. If the test is in flutter package, it will run on a different code path

**Comment by goderbauer** [comment]
@chunhtai is not actually working on this right now due to other priorities.

**Comment by chunhtai** [comment]
@InMatrix Is there any data or survey on whether the debug message is useful or not? It might affect if we want to solve this issue or revert the functionality entirely

**Comment by InMatrix** [comment]
Identifying the relevant widget is certainly useful and we had this request from several important customers. Reverting the functionality entirely seems to be an extreme response? How much work would it take to fix the crash?

**Comment by chunhtai** [comment]
It might take some time to fix this crasher. We just would like to some information from you to see if it worth the fix. It seems like this functionality is still relevant and we should keep maintaining it.

**Comment by InMatrix** [comment]
Yes, this feature is important. If the crash rate crosses a line that
affects many users, I'd be fine with temporarily disabling this feature
until the crash is fixed.

Tao
