### ISSUE TITLE
Flutter run crashes while initializing gradle

### ISSUE THREAD

**Issue by Binabh** [flutter/flutter#44541]
## Steps to Reproduce

1. Just made a new project with flutter
2. flutter doctor executed with no issues
3. flutter run would crash at initializing gradle

**Target Platform:**Android
**Target OS version/browser:**Android Pie
**Devices:** Redmi 6

## Logs

Log of `flutter run --verbose`
```The system cannot find the path specified.
The system cannot find the path specified.
[  +27 ms] executing: [D:\Softwares\flutter\] git log -n 1 --pretty=format:%H
[ +131 ms] Exit code 0 from: git log -n 1 --pretty=format:%H
[   +3 ms] 68587a0916366e9512a78df22c44163d041dd5f3
[   +1 ms] executing: [D:\Softwares\flutter\] git describe --match v*.*.* --first-parent --long --tags
[ +213 ms] Exit code 0 from: git describe --match v*.*.* --first-parent --long --tags
[   +1 ms] v1.9.1+hotfix.6-0-g68587a091
[  +47 ms] executing: [D:\Softwares\flutter\] git rev-parse --abbrev-ref --symbolic @{u}
[ +171 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[   +1 ms] origin/stable
[        ] executing: [D:\Softwares\flutter\] git ls-remote --get-url origin
[  +88 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[ +134 ms] executing: [D:\Softwares\flutter\] git rev-parse --abbrev-ref HEAD
[  +98 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] stable
[ +139 ms] executing: C:\Users\binab\AppData\Local\Android\sdk\platform-tools\adb.exe devices -l
[  +55 ms] Exit code 0 from: C:\Users\binab\AppData\Local\Android\sdk\platform-tools\adb.exe devices -l
[        ] List of devices attached
           176898367d26           device product:cereus model:Redmi_6 device:cereus transport_id:3
[  +16 ms] C:\Users\binab\AppData\Local\Android\sdk\platform-tools\adb.exe -s 176898367d26 shell getprop
[ +268 ms] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +5 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[   +2 ms] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[ +142 ms] ro.hardware = mt6765
[        ] ro.build.characteristics = default
[  +62 ms] Launching lib\main.dart on Redmi 6 in debug mode...
[  +17 ms] Initializing gradle...
[   +2 ms] Using gradle from D:\Projects\flutter_app3\android\gradlew.bat.
[ +161 ms] executing: D:\Projects\flutter_app3\android\gradlew.bat -v
[+1066 ms]
                    ------------------------------------------------------------
                    Gradle 4.10.2
                    ------------------------------------------------------------

                    Build time:   2018-09-19 18:10:15 UTC
                    Revision:     b4d8d5d170bb4ba516e88d7fe5647e2323d791dd

                    Kotlin DSL:   1.0-rc-6
                    Kotlin:       1.2.61
                    Groovy:       2.4.15
                    Ant:          Apache Ant(TM) version 1.9.11 compiled on March 23 2018
                    JVM:          1.8.0_202-release (JetBrains s.r.o 25.202-b03)
                    OS:           Windows 10 10.0 amd64


                    The system cannot find the path specified.
[  +12 ms] "flutter run" took 2,057ms.

Sending crash report to Google.
Crash report sent (report ID: 09f56e5c76fb66cf)
Oops; flutter has exited unexpectedly.

Crash report written to D:\Projects\flutter_app3\flutter_02.log;
please let us know at https://github.com/flutter/flutter/issues.
```

Log of `flutter analyze`
```The system cannot find the path specified.
The system cannot find the path specified.
Analyzing flutter_app3...
No issues found! (ran in 36.8s)
```

Log of `flutter doctor -v`
```The system cannot find the path specified.
The system cannot find the path specified.
[√] Flutter (Channel stable, v1.9.1+hotfix.6, on Windows, locale en-US)
    • Flutter version 1.9.1+hotfix.6 at D:\Softwares\flutter
    • Framework revision 68587a0916 (8 weeks ago), 2019-09-13 19:46:58 -0700
    • Engine revision b863200c37
    • Dart version 2.5.0


[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at C:\Users\binab\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)
    • All Android licenses accepted.

[√] Android Studio (version 3.5)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 41.0.2
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)

[√] VS Code, 64-bit edition (version 1.39.2)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Flutter extension version 3.6.0

[√] Connected device (1 available)
    • Redmi 6 • 176898367d26 • android-arm • Android 9 (API 28)

• No issues found!
```
Here is the log of file flutter_01.log while trying `flutter run` from terminal
`Flutter crash report; please file at https://github.com/flutter/flutter/issues.

## command

flutter run

## exception

ProcessException: ProcessException: Process "D:\Projects\flutter_app3\android\gradlew.bat" exited abnormally:

------------------------------------------------------------
Gradle 4.10.2
------------------------------------------------------------

Build time:   2018-09-19 18:10:15 UTC
Revision:     b4d8d5d170bb4ba516e88d7fe5647e2323d791dd

Kotlin DSL:   1.0-rc-6
Kotlin:       1.2.61
Groovy:       2.4.15
Ant:          Apache Ant(TM) version 1.9.11 compiled on March 23 2018
JVM:          1.8.0_202-release (JetBrains s.r.o 25.202-b03)
OS:           Windows 10 10.0 amd64

The system cannot find the path specified.
  Command: D:\Projects\flutter_app3\android\gradlew.bat -v

```
#0      runCheckedAsync (package:flutter_tools/src/base/process.dart:259:7)
<asynchronous suspension>
#1      _initializeGradle (package:flutter_tools/src/android/gradle.dart:300:9)
<asynchronous suspension>
#2      _ensureGradle (package:flutter_tools/src/android/gradle.dart:281:37)
<asynchronous suspension>
#3      _readGradleProject (package:flutter_tools/src/android/gradle.dart:192:31)
<asynchronous suspension>
#4      _gradleAppProject (package:flutter_tools/src/android/gradle.dart:112:37)
<asynchronous suspension>
#5      getGradleAppOut (package:flutter_tools/src/android/gradle.dart:106:29)
<asynchronous suspension>
#6      AndroidApk.fromAndroidProject (package:flutter_tools/src/application_package.dart:164:23)
<asynchronous suspension>
#7      ApplicationPackageFactory.getPackageForPlatform (package:flutter_tools/src/application_package.dart:46:32)
<asynchronous suspension>
#8      FlutterDevice.runHot (package:flutter_tools/src/resident_runner.dart:359:56)
<asynchronous suspension>
#9      HotRunner.run (package:flutter_tools/src/run_hot.dart:254:39)
<asynchronous suspension>
#10     RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:472:37)
<asynchronous suspension>
#11     FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:490:18)
#12     _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:71:64)
#13     _rootRunUnary (dart:async/zone.dart:1132:38)
#14     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#15     _FutureListener.handleValue (dart:async/future_impl.dart:137:18)
#16     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:678:45)
#17     Future._propagateToListeners (dart:async/future_impl.dart:707:32)
#18     Future._completeWithValue (dart:async/future_impl.dart:522:5)
#19     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:30:15)
#20     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:288:13)
#21     RunCommand.usageValues (package:flutter_tools/src/commands/run.dart)
#22     _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:71:64)
#23     _rootRunUnary (dart:async/zone.dart:1132:38)
#24     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#25     _FutureListener.handleValue (dart:async/future_impl.dart:137:18)
#26     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:678:45)
#27     Future._propagateToListeners (dart:async/future_impl.dart:707:32)
#28     Future._completeWithValue (dart:async/future_impl.dart:522:5)
#29     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:30:15)
#30     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:288:13)
#31     AndroidDevice.isLocalEmulator (package:flutter_tools/src/android/android_device.dart)
#32     _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:71:64)
#33     _rootRunUnary (dart:async/zone.dart:1132:38)
#34     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#35     _FutureListener.handleValue (dart:async/future_impl.dart:137:18)
#36     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:678:45)
#37     Future._propagateToListeners (dart:async/future_impl.dart:707:32)
#38     Future._completeWithValue (dart:async/future_impl.dart:522:5)
#39     Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:552:7)
#40     _rootRun (dart:async/zone.dart:1124:13)
#41     _CustomZone.run (dart:async/zone.dart:1021:19)
#42     _CustomZone.runGuarded (dart:async/zone.dart:923:7)
#43     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:963:23)
#44     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#45     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#46     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:116:13)
#47     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:173:5)
```

## flutter doctor

```
[32m[✓][39m Flutter (Channel stable, v1.9.1+hotfix.6, on Windows, locale en-US)
    [32m•[39m Flutter version 1.9.1+hotfix.6 at D:\Softwares\flutter
    [32m•[39m Framework revision 68587a0916 (8 weeks ago), 2019-09-13 19:46:58 -0700
    [32m•[39m Engine revision b863200c37
    [32m•[39m Dart version 2.5.0

[32m[✓][39m Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    [32m•[39m Android SDK at C:\Users\binab\AppData\Local\Android\sdk
    [32m•[39m Android NDK location not configured (optional; useful for native profiling support)
    [32m•[39m Platform android-29, build-tools 29.0.2
    [32m•[39m Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    [32m•[39m Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)
    [32m•[39m All Android licenses accepted.

[32m[✓][39m Android Studio (version 3.5)
    [32m•[39m Android Studio at C:\Program Files\Android\Android Studio
    [32m•[39m Flutter plugin version 41.0.2
    [32m•[39m Dart plugin version 191.8593
    [32m•[39m Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)

[32m[✓][39m VS Code, 64-bit edition (version 1.39.2)
    [32m•[39m VS Code at C:\Program Files\Microsoft VS Code
    [32m•[39m Flutter extension version 3.6.0

[32m[✓][39m Connected device (1 available)
    [32m•[39m Redmi 6 • 176898367d26 • android-arm • Android 9 (API 28)

[32m•[39m No issues found!
````

**Comment by joaovictorpsantos** [comment]
@Binabh , I already had problems with gradle, I would recommend you to use the latest version of AndroidStudio and create your Flutter project through it.

**Comment by Binabh** [comment]
@joaovictorpsantos Thank you for replying.
I am using latest android studio to build and run flutter project. I have even uninstalled and installed everything including the Java, flutter, android studio, sdk etc. But no luck at all. It has been like week and I was compelled to post here in search of any help.

**Comment by jonahwilliams** [comment]
It looks like ` D:\Projects\flutter_app3\android\gradlew.bat` is missing according to the error message, can you confirm that this is the case?

**Comment by iapicca** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact descriptions what happens, logs and the output of 'flutter doctor -v'  please.
All system setups can be slightly different so its always better to open new issues and reference related issues.

**Comment by Binabh** [comment]
Unfortunately I had to change my OS due to some other issue. Along with my installed apps everything was deleted and while reinstalling everything again I worked.
Also never received notification about the discussion in this issue so, replying this late.
Thanks to everyone for the support.
