### ISSUE TITLE
EXCEPTION CAUGHT BY WIDGETS LIBRARY

### ISSUE THREAD

**Issue by ldco2016** [flutter/flutter#44547]
## Steps to Reproduce

You can download a reproducible copy here:
https://github.com/ldco2016/news

The error occurs as soon as you run `flutter run`, this is the exact error:

```
                                     ⡿I/flutter (19044): ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
I/flutter (19044): The following assertion was thrown building App(dirty):
I/flutter (19044): type '(RouteSettings) => dynamic' is not a subtype of type '(RouteSettings) => Route<dynamic>'
```

## Logs

```
+25 ms] D/EGL_emulation(20689): eglMakeCurrent: 0xec5eed80: ver 3 0 (tinfo 0xf26cbd50)
[ +304 ms] I/flutter (20689): ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
[        ] I/flutter (20689): The following assertion was thrown building App(dirty):
[        ] I/flutter (20689): type '(RouteSettings) => dynamic' is not a subtype of type '(RouteSettings) => Route<dynamic>'
[        ] I/flutter (20689):
[        ] I/flutter (20689): Either the assertion indicates an error in the framework itself, or we should provide substantially
[        ] I/flutter (20689): more information in this error message to help you determine and fix the underlying cause.
[        ] I/flutter (20689): In either case, please report this assertion by filing a bug on GitHub:
[        ] I/flutter (20689):   https://github.com/flutter/flutter/issues/new?template=BUG.md
[        ] I/flutter (20689):
[        ] I/flutter (20689): Widget creation tracking is currently disabled. Enabling it enables improved error messages. It can
[        ] I/flutter (20689): be enabled by passing `--track-widget-creation` to `flutter run` or `flutter test`.
[        ] I/flutter (20689):
[        ] I/flutter (20689): When the exception was thrown, this was the stack:
[        ] I/flutter (20689): #0      App.build (package:news/src/app.dart:11:26)
[        ] I/flutter (20689): #1      StatelessElement.build (package:flutter/src/widgets/framework.dart:4009:28)
[        ] I/flutter (20689): #2      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3941:15)
[        ] I/flutter (20689): #3      Element.rebuild (package:flutter/src/widgets/framework.dart:3738:5)
[        ] I/flutter (20689): #4      ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3924:5)
[        ] I/flutter (20689): #5      ComponentElement.mount (package:flutter/src/widgets/framework.dart:3919:5)
[        ] I/flutter (20689): #6      Element.inflateWidget (package:flutter/src/widgets/framework.dart:3101:14)
[        ] I/flutter (20689): #7      Element.updateChild (package:flutter/src/widgets/framework.dart:2904:12)
[        ] I/flutter (20689): #8      RenderObjectToWidgetElement._rebuild (package:flutter/src/widgets/binding.dart:998:16)
[        ] I/flutter (20689): #9      RenderObjectToWidgetElement.mount (package:flutter/src/widgets/binding.dart:969:5)
[        ] I/flutter (20689): #10     RenderObjectToWidgetAdapter.attachToRenderTree.<anonymous closure> (package:flutter/src/widgets/binding.dart:915:17)
[        ] I/flutter (20689): #11     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2328:19)
[        ] I/flutter (20689): #12     RenderObjectToWidgetAdapter.attachToRenderTree (package:flutter/src/widgets/binding.dart:914:13)
[        ] I/flutter (20689): #13     WidgetsBinding.attachRootWidget (package:flutter/src/widgets/binding.dart:795:7)
[        ] I/flutter (20689): #14     runApp (package:flutter/src/widgets/binding.dart:845:7)
[        ] I/flutter (20689): #15     main (package:news/main.dart:5:3)
[        ] I/flutter (20689): #16     _runMainZoned.<anonymous closure>.<anonymous closure> (dart:ui/hooks.dart:229:25)
[        ] I/flutter (20689): #21     _runMainZoned.<anonymous closure> (dart:ui/hooks.dart:221:5)
[        ] I/flutter (20689): #22     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:305:19)
[        ] I/flutter (20689): #23     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:12)
[        ] I/flutter (20689): (elided 4 frames from package dart:async)
[        ] I/flutter (20689):
[        ] I/flutter (20689): ════════════════════════════════════════════════════════════════════════════════════════════════════
[  +31 ms] I/Choreographer(20689): Skipped 32 frames!  The application may be doing too much work on its main thread.
[  +14 ms] D/EGL_emulation(20689): eglMakeCurrent: 0xec985900: ver 3 0 (tinfo 0xd644de90)
[ +193 ms] D/EGL_emulation(20689): eglMakeCurrent: 0xec5eed80: ver 3 0 (tinfo 0xf26cbd50)
```

```
   info • Unused import: 'package:news/main.dart' • test/widget_test.dart:11:8 • unused_import
  error • The function 'MyApp' isn't defined • test/widget_test.dart:16:29 • undefined_function

2 issues found. (ran in 1.9s)
```

```
[✓] Flutter (Channel stable, v1.9.1+hotfix.4, on Mac OS X 10.14.5 18F132, locale en-US)
    • Flutter version 1.9.1+hotfix.4 at /Users/luiscortes/Projects/flutter
    • Framework revision cc949a8e8b (6 weeks ago), 2019-09-27 15:04:59 -0700
    • Engine revision b863200c37
    • Dart version 2.5.0


[!] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/luiscortes/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses

[!] Xcode - develop for iOS and macOS (Xcode 11.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.2, Build version 11B52
    ✗ CocoaPods not installed.
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To install:
        sudo gem install cocoapods
        pod setup

[!] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] Connected device (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 9 (API 28) (emulator)

! Doctor found issues in 3 categories.
```

**Comment by ldco2016** [comment]
Nevermind, I was missing `Route` in `Route routes(RouteSettings settings) {`,  flutter was pointing at line 11 at `onGenerateRoute: routes,`, but I eventually found it.
