### ISSUE TITLE
[web] Cannot run widget test for flutter web

### ISSUE THREAD

**Issue by PavelPZ** [flutter/flutter#44566]
I am trying to run widget test (for ```vm``` and ```chrome```). I found many informations how to run tests. **But I cannot find any solution how to run widget test for ```chrome```**.

Result of my exploration follows:

# my test sources
### *A variant*
```
import 'package:flutter_test/flutter_test.dart';

void main() {
    testWidgets('fake', (tester) {
      expect(0, 0);
      return Future.value(0);
    });
}
```
### *B variant*
```
import 'package:test/test.dart';

void main() {
    test('fake', () async {
      expect(0, 0);
      return Future.value();
  });
}
```
# running tests
### both A,B variant
as per documentation, running ````chrome``` tests from vs code IDE is not supported. For ```vm```, it is running well.

### both A,B variant
**OK**

### both A,B variant
**ERROR**
```
starting build daemon...                                           38.2s
Incompatible options with current running build daemon.

Please stop other flutter_tool instances running in this directory before starting a new instance with these options.
```

### A variant
**ERROR**
```
 Unable to spawn isolate: Crash when compiling package:test/bootstrap/vm.dart,
  at character offset null:
  Unhandled type: InvalidType
  #0      Types.performNullabilityAwareSubtypeCheck (package:front_end/src/fasta/kernel/types.dart:221:7)
  #1      Types.areTypeArgumentsOfSubtypeKernel (package:front_end/src/fasta/kernel/types.dart:247:29)
  #2      IsInterfaceSubtypeOf.isInterfaceRelated (package:front_end/src/fasta/kernel/types.dart:358:10)
```

### B variant
**OK**

### A variant
**ERROR**
```
Running tests...

00:00 +0: compiling test\streamProvider2_test.dart
00:00 +0 -1: compiling test\streamProvider2_test.dart [E]
  Failed to load "test\streamProvider2_test.dart": Failed to load script at http://localhost:61490/7lVl85%2Bv7Kt8r5Yhr%2FetBvRQf2BTWIqw/test/streamProvider2_test.dart.browser_test.dart.js.
00:00 +0 -1: Some tests failed.
pub finished with exit code 1
```
### B variant
**OK**

### both A,B variant
**ERROR**
```
The Flutter SDK is not available.
```
# Environment
flutter doctor:
```
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel master, v1.10.16-pre.113, on Microsoft Windows [Version 10.0.18362.418], locale en-US)
[!] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    X No Java Development Kit (JDK) found; You must have the environment variable JAVA_HOME set and the java binary in your PATH. You can download the JDK from
      https://www.oracle.com/technetwork/java/javase/downloads/.
[√] Chrome - develop for the web
[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.4.0 Preview 2.0)
[!] Android Studio (version 3.5)
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
    X Unable to determine bundled Java version.
[√] VS Code (version 1.40.0)
[√] Connected device (3 available)

! Doctor found issues in 2 categories.
```

**Comment by PavelPZ** [comment]
I tried:
- changed flutter channel to DEV
- created new flutter project (by ```flutter create temp```)
- run ```flutter test --platform chrome -v```

Than this error appeared:
```
c:\wikibulary\dart\algorithm\temp>flutter test --platform chrome -v
[  +43 ms] executing: [c:\flutter\] git -c log.showSignature=false log -n 1 --pretty=format:%H
[ +148 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[  +12 ms] fbabb264e0ab3e090d6ec056e0744aaeb1586735
[   +3 ms] executing: [c:\flutter\] git describe --match v*.*.* --first-parent --long --tags
[ +156 ms] Exit code 0 from: git describe --match v*.*.* --first-parent --long --tags
[   +4 ms] v1.10.15-0-gfbabb264e
[  +63 ms] executing: [c:\flutter\] git rev-parse --abbrev-ref --symbolic @{u}
[  +95 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[   +4 ms] origin/dev
[   +2 ms] executing: [c:\flutter\] git ls-remote --get-url origin
[  +82 ms] Exit code 0 from: git ls-remote --get-url origin
[   +4 ms] https://github.com/flutter/flutter.git
[ +189 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[   +6 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[   +2 ms] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[   +2 ms] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[  +16 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[   +7 ms] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[   +5 ms] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[+16009 ms] Starting daemon...
[ +258 ms] Initializing inputs
[  +29 ms] Reading cached asset graph...
[ +369 ms] Reading cached asset graph completed, took 363ms

[ +530 ms] Checking for updates since last build...
[ +804 ms] Checking for updates since last build completed, took 804ms

[  +19 ms] Initializing inputs
[   +6 ms] Reading cached asset graph...
[   +5 ms] Reading cached asset graph completed, took 363ms
[   +2 ms] Checking for updates since last build...
[   +1 ms] Checking for updates since last build completed, took 804ms
[+1837 ms] About to build [web, test]...
[  +20 ms] Running build...
[   +2 ms] Running build completed, took 127ms

[  +10 ms] Caching finalized dependency graph...
[   +9 ms] Caching finalized dependency graph completed, took 190ms

[   +4 ms] Succeeded after 336ms with 0 outputs (0 actions)

00:00 +0: compiling c:\wikibulary\dart\algorithm\temp\test\widget_test.dart                                                                                                [+20798 ms] Serving tests at http://localhost:61718/static/index.html?managerUrl=ws%3A%2F%2Flocalhost%3A61718%2F0&debug=false
[ +925 ms] Did not find anything for request: widget_test.dart.browser_test.dart.js
00:01 +0 -1: compiling c:\wikibulary\dart\algorithm\temp\test\widget_test.dart [E]
  Failed to load "c:\wikibulary\dart\algorithm\temp\test\widget_test.dart": Failed to load script at http://localhost:61718/widget_test.dart.browser_test.dart.js.
00:01 +0 -1: Some tests failed.

#0      throwToolExit (package:flutter_tools/src/base/common.dart:28:3)
#1      TestCommand.runCommand (package:flutter_tools/src/commands/test.dart:258:7)
<asynchronous suspension>
#2      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:157:29)
<asynchronous suspension>
#3      _rootRun (dart:async/zone.dart:1124:13)
#4      _CustomZone.run (dart:async/zone.dart:1021:19)
#5      _runZoned (dart:async/zone.dart:1516:10)
#6      runZoned (dart:async/zone.dart:1463:12)
#7      AppContext.run (package:flutter_tools/src/base/context.dart:156:18)
<asynchronous suspension>
#8      FastFlutterCommand.run (package:flutter_tools/src/runner/flutter_command.dart:750:20)
#9      CommandRunner.runCommand (package:args/command_runner.dart:197:27)
<asynchronous suspension>
#10     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:416:21)
<asynchronous suspension>
#11     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:157:29)
<asynchronous suspension>
#12     _rootRun (dart:async/zone.dart:1124:13)
#13     _CustomZone.run (dart:async/zone.dart:1021:19)
#14     _runZoned (dart:async/zone.dart:1516:10)
#15     runZoned (dart:async/zone.dart:1463:12)
#16     AppContext.run (package:flutter_tools/src/base/context.dart:156:18)
<asynchronous suspension>
#17     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:367:19)
<asynchronous suspension>
#18     CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:112:25)
#19     new Future.sync (dart:async/future.dart:222:31)
#20     CommandRunner.run (package:args/command_runner.dart:112:14)
#21     FlutterCommandRunner.run (package:flutter_tools/src/runner/flutter_command_runner.dart:251:18)
#22     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:63:22)
<asynchronous suspension>
#23     _rootRun (dart:async/zone.dart:1124:13)
#24     _CustomZone.run (dart:async/zone.dart:1021:19)
#25     _runZoned (dart:async/zone.dart:1516:10)
#26     runZoned (dart:async/zone.dart:1500:12)
#27     run.<anonymous closure> (package:flutter_tools/runner.dart:61:18)
<asynchronous suspension>
#28     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:157:29)
<asynchronous suspension>
#29     _rootRun (dart:async/zone.dart:1124:13)
#30     _CustomZone.run (dart:async/zone.dart:1021:19)
#31     _runZoned (dart:async/zone.dart:1516:10)
#32     runZoned (dart:async/zone.dart:1463:12)
#33     AppContext.run (package:flutter_tools/src/base/context.dart:156:18)
<asynchronous suspension>
#34     runInContext (package:flutter_tools/src/context_runner.dart:64:24)
<asynchronous suspension>
#35     run (package:flutter_tools/runner.dart:50:10)
#36     main (package:flutter_tools/executable.dart:65:9)
<asynchronous suspension>
#37     main (file:///c:/flutter/packages/flutter_tools/bin/flutter_tools.dart:8:3)
#38     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:303:32)
#39     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:12)
```

**Comment by jonahwilliams** [comment]
The issue for that is tracked in https://github.com/flutter/flutter/issues/43639
