### ISSUE TITLE
Windows 10: it is confirmed that "flutter test --platform chrome" does not work

### ISSUE THREAD

**Issue by PavelPZ** [flutter/flutter#44583]
Running ```flutter test --platform chrome -v```
on new flutter project (created by ```flutter create temp```)
raised following error (both ```flutter test``` and ```flutter run -d chrome``` work well):

<details>
  <summary>logs</summary>

```
c:\wikibulary\dart\algorithm\temp>flutter test --platform chrome -v
[  +43 ms] executing: [c:\flutter\] git -c log.showSignature=false log -n 1 --pretty=format:%H
[ +148 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[  +12 ms] fbabb264e0ab3e090d6ec056e0744aaeb1586735
[   +3 ms] executing: [c:\flutter\] git describe --match v*.*.* --first-parent --long --tags
[ +156 ms] Exit code 0 from: git describe --match v*.*.* --first-parent --long --tags
[   +4 ms] v1.10.15-0-gfbabb264e
[  +63 ms] executing: [c:\flutter\] git rev-parse --abbrev-ref --symbolic @{u}
[  +95 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[   +4 ms] origin/dev
[   +2 ms] executing: [c:\flutter\] git ls-remote --get-url origin
[  +82 ms] Exit code 0 from: git ls-remote --get-url origin
[   +4 ms] https://github.com/flutter/flutter.git
[ +189 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[   +6 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[   +2 ms] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[   +2 ms] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[  +16 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[   +7 ms] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[   +5 ms] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[+16009 ms] Starting daemon...
[ +258 ms] Initializing inputs
[  +29 ms] Reading cached asset graph...
[ +369 ms] Reading cached asset graph completed, took 363ms

[ +530 ms] Checking for updates since last build...
[ +804 ms] Checking for updates since last build completed, took 804ms

[  +19 ms] Initializing inputs
[   +6 ms] Reading cached asset graph...
[   +5 ms] Reading cached asset graph completed, took 363ms
[   +2 ms] Checking for updates since last build...
[   +1 ms] Checking for updates since last build completed, took 804ms
[+1837 ms] About to build [web, test]...
[  +20 ms] Running build...
[   +2 ms] Running build completed, took 127ms

[  +10 ms] Caching finalized dependency graph...
[   +9 ms] Caching finalized dependency graph completed, took 190ms

[   +4 ms] Succeeded after 336ms with 0 outputs (0 actions)

00:00 +0: compiling c:\wikibulary\dart\algorithm\temp\test\widget_test.dart                                                                                                [+20798 ms] Serving tests at http://localhost:61718/static/index.html?managerUrl=ws%3A%2F%2Flocalhost%3A61718%2F0&debug=false
[ +925 ms] Did not find anything for request: widget_test.dart.browser_test.dart.js
00:01 +0 -1: compiling c:\wikibulary\dart\algorithm\temp\test\widget_test.dart [E]
  Failed to load "c:\wikibulary\dart\algorithm\temp\test\widget_test.dart": Failed to load script at http://localhost:61718/widget_test.dart.browser_test.dart.js.
00:01 +0 -1: Some tests failed.

#0      throwToolExit (package:flutter_tools/src/base/common.dart:28:3)
#1      TestCommand.runCommand (package:flutter_tools/src/commands/test.dart:258:7)
<asynchronous suspension>
#2      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:157:29)
<asynchronous suspension>
#3      _rootRun (dart:async/zone.dart:1124:13)
#4      _CustomZone.run (dart:async/zone.dart:1021:19)
#5      _runZoned (dart:async/zone.dart:1516:10)
#6      runZoned (dart:async/zone.dart:1463:12)
#7      AppContext.run (package:flutter_tools/src/base/context.dart:156:18)
<asynchronous suspension>
#8      FastFlutterCommand.run (package:flutter_tools/src/runner/flutter_command.dart:750:20)
#9      CommandRunner.runCommand (package:args/command_runner.dart:197:27)
<asynchronous suspension>
#10     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:416:21)
<asynchronous suspension>
#11     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:157:29)
<asynchronous suspension>
#12     _rootRun (dart:async/zone.dart:1124:13)
#13     _CustomZone.run (dart:async/zone.dart:1021:19)
#14     _runZoned (dart:async/zone.dart:1516:10)
#15     runZoned (dart:async/zone.dart:1463:12)
#16     AppContext.run (package:flutter_tools/src/base/context.dart:156:18)
<asynchronous suspension>
#17     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:367:19)
<asynchronous suspension>
#18     CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:112:25)
#19     new Future.sync (dart:async/future.dart:222:31)
#20     CommandRunner.run (package:args/command_runner.dart:112:14)
#21     FlutterCommandRunner.run (package:flutter_tools/src/runner/flutter_command_runner.dart:251:18)
#22     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:63:22)
<asynchronous suspension>
#23     _rootRun (dart:async/zone.dart:1124:13)
#24     _CustomZone.run (dart:async/zone.dart:1021:19)
#25     _runZoned (dart:async/zone.dart:1516:10)
#26     runZoned (dart:async/zone.dart:1500:12)
#27     run.<anonymous closure> (package:flutter_tools/runner.dart:61:18)
<asynchronous suspension>
#28     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:157:29)
<asynchronous suspension>
#29     _rootRun (dart:async/zone.dart:1124:13)
#30     _CustomZone.run (dart:async/zone.dart:1021:19)
#31     _runZoned (dart:async/zone.dart:1516:10)
#32     runZoned (dart:async/zone.dart:1463:12)
#33     AppContext.run (package:flutter_tools/src/base/context.dart:156:18)
<asynchronous suspension>
#34     runInContext (package:flutter_tools/src/context_runner.dart:64:24)
<asynchronous suspension>
#35     run (package:flutter_tools/runner.dart:50:10)
#36     main (package:flutter_tools/executable.dart:65:9)
<asynchronous suspension>
#37     main (file:///c:/flutter/packages/flutter_tools/bin/flutter_tools.dart:8:3)
#38     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:303:32)
#39     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:12)

```

</details>

flutter doctor:

```
[√] Flutter (Channel dev, v1.10.15, on Microsoft Windows [Version 10.0.18362.418], locale en-US)
    • Flutter version 1.10.15 at c:\flutter
    • Framework revision fbabb264e0 (10 days ago), 2019-11-02 01:36:07 +0300
    • Engine revision 8ea19b1c76
    • Dart version 2.6.0 (build 2.6.0-dev.8.2 bbe2ac28c9)

[!] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at C:\Users\pzika\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    X No Java Development Kit (JDK) found; You must have the environment variable JAVA_HOME set and the java binary in
      your PATH. You can download the JDK from https://www.oracle.com/technetwork/java/javase/downloads/.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[!] Android Studio (version 3.5)
    • Android Studio at C:\Program Files\Android\Android Studio
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
    X Unable to determine bundled Java version.
    • Try updating or re-installing Android Studio.

[√] VS Code (version 1.40.0)
    • VS Code at C:\Users\pzika\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.6.0

[√] Connected device (2 available)
    • Chrome     • chrome     • web-javascript • Google Chrome 78.0.3904.97
    • Web Server • web-server • web-javascript • Flutter Tools

! Doctor found issues in 2 categories.
```

**Comment by PavelPZ** [comment]
Running ```flutter pub run build_runner test -- -p "chrome"```

produces similar error (```Failed to load "test\widget_test.dart": Failed to load script at http://localhost:49276/i4iMyBxuEn8Ccr9WnZH3i%2FzZv8B%2BvRLP/test/widget_test.dart.browser_test.dart.js.```):
```
c:\wikibulary\dart\algorithm\temp>flutter pub run build_runner test -- -p "chrome"
Could not find package "build_runner". Did you forget to add a dependency?
pub finished with exit code 65

c:\wikibulary\dart\algorithm\temp>flutter pub run build_runner test -- -p "chrome"
[INFO] Generating build script...
[INFO] Generating build script completed, took 734ms

[INFO] Creating build script snapshot......
[INFO] Creating build script snapshot... completed, took 16.7s

[INFO] Initializing inputs
[INFO] Building new asset graph...
[INFO] Building new asset graph completed, took 2.8s

[INFO] Checking for unexpected pre-existing outputs....
[INFO] Checking for unexpected pre-existing outputs. completed, took 6ms

[INFO] Running build...
[INFO] 1.1s elapsed, 33/53 actions completed.
[INFO] 2.2s elapsed, 101/121 actions completed.
[INFO] 3.2s elapsed, 133/137 actions completed.
[INFO] 4.3s elapsed, 188/193 actions completed.
[INFO] 5.3s elapsed, 228/248 actions completed.
[INFO] 6.3s elapsed, 264/273 actions completed.
[INFO] 7.4s elapsed, 297/308 actions completed.
[INFO] 8.4s elapsed, 352/356 actions completed.
[INFO] 9.5s elapsed, 383/387 actions completed.
[INFO] 10.5s elapsed, 466/478 actions completed.
[INFO] 11.5s elapsed, 507/521 actions completed.
[INFO] 12.6s elapsed, 530/543 actions completed.
[INFO] 13.8s elapsed, 555/569 actions completed.
[INFO] 14.8s elapsed, 582/597 actions completed.
[INFO] 15.9s elapsed, 660/678 actions completed.
[INFO] 17.0s elapsed, 684/688 actions completed.
[INFO] 18.0s elapsed, 699/703 actions completed.
[INFO] 19.1s elapsed, 758/762 actions completed.
[INFO] 20.2s elapsed, 774/794 actions completed.
[INFO] 21.2s elapsed, 806/825 actions completed.
[INFO] 22.2s elapsed, 835/843 actions completed.
[INFO] 23.3s elapsed, 859/876 actions completed.
[INFO] 24.3s elapsed, 889/902 actions completed.
[INFO] 25.3s elapsed, 910/927 actions completed.
[INFO] 26.4s elapsed, 1046/1055 actions completed.
[INFO] 27.4s elapsed, 1105/1109 actions completed.
[INFO] 28.4s elapsed, 1131/1151 actions completed.
[INFO] 29.5s elapsed, 1168/1172 actions completed.
[INFO] 30.6s elapsed, 1195/1215 actions completed.
[INFO] 31.7s elapsed, 1237/1246 actions completed.
[INFO] 32.8s elapsed, 1267/1278 actions completed.
[INFO] 34.0s elapsed, 1293/1309 actions completed.
[INFO] 35.0s elapsed, 1322/1339 actions completed.
[INFO] 36.1s elapsed, 1352/1365 actions completed.
[INFO] 37.1s elapsed, 1401/1414 actions completed.
[INFO] 38.1s elapsed, 1498/1518 actions completed.
[INFO] 39.2s elapsed, 1530/1539 actions completed.
[INFO] 40.6s elapsed, 1552/1556 actions completed.
[INFO] 41.7s elapsed, 1604/1623 actions completed.
[INFO] 42.8s elapsed, 1636/1653 actions completed.
[INFO] 44.1s elapsed, 1659/1671 actions completed.
[INFO] 45.2s elapsed, 1669/1686 actions completed.
[INFO] 46.3s elapsed, 1726/1737 actions completed.
[INFO] 47.3s elapsed, 1779/1785 actions completed.
[INFO] 48.3s elapsed, 1797/1817 actions completed.
[INFO] 49.4s elapsed, 1829/1841 actions completed.
[INFO] 50.6s elapsed, 1845/1864 actions completed.
[INFO] 51.6s elapsed, 1896/1906 actions completed.
[INFO] 52.7s elapsed, 2005/2009 actions completed.
[INFO] 53.8s elapsed, 2214/2217 actions completed.
[WARNING] build_web_compilers:entrypoint on test/widget_test.dart.browser_test.dart:
Skipping compiling temp|test/widget_test.dart.browser_test.dart with ddc because some of its
transitive libraries have sdk dependencies that not supported on this platform:

flutter_test|lib/src/event_simulation.dart
flutter_test|lib/src/window.dart
flutter_test|lib/src/matchers.dart
flutter_test|lib/src/test_pointer.dart
flutter_test|lib/src/accessibility.dart
flutter_test|lib/src/binding.dart
flutter_test|lib/src/platform.dart
flutter|lib/src/rendering/error.dart
flutter|lib/src/rendering/box.dart
flutter|lib/src/rendering/stack.dart
flutter|lib/src/rendering/editable.dart
flutter|lib/src/rendering/image.dart
flutter|lib/src/rendering/debug_overflow_indicator.dart
flutter|lib/src/rendering/view.dart
flutter|lib/src/rendering/platform_view.dart
flutter|lib/src/rendering/proxy_box.dart
flutter|lib/src/rendering/layer.dart
flutter|lib/src/rendering/paragraph.dart
flutter|lib/src/rendering/object.dart
flutter|lib/src/animation/tween.dart
flutter|lib/src/animation/animation_controller.dart
flutter|lib/painting.dart
flutter|lib/src/painting/_network_image_web.dart
flutter|lib/src/painting/image_decoder.dart
flutter|lib/src/painting/alignment.dart
flutter|lib/src/painting/edge_insets.dart
flutter|lib/src/painting/gradient.dart
flutter|lib/src/painting/image_stream.dart
flutter|lib/src/painting/image_resolution.dart
flutter|lib/src/painting/binding.dart
flutter|lib/src/painting/decoration_image.dart
flutter|lib/src/painting/stadium_border.dart
flutter|lib/src/painting/text_span.dart
flutter|lib/src/painting/image_provider.dart
flutter|lib/src/painting/basic_types.dart
flutter|lib/src/painting/placeholder_span.dart
flutter|lib/src/painting/flutter_logo.dart
flutter|lib/src/painting/debug.dart
flutter|lib/src/painting/shader_warm_up.dart
flutter|lib/src/painting/text_painter.dart
flutter|lib/src/painting/rounded_rectangle_border.dart
flutter|lib/src/painting/colors.dart
flutter|lib/src/painting/fractional_offset.dart
flutter|lib/src/painting/inline_span.dart
flutter|lib/src/painting/borders.dart
flutter|lib/src/painting/text_style.dart
flutter|lib/src/painting/box_shadow.dart
flutter|lib/src/painting/clip.dart
flutter|lib/src/widgets/focus_traversal.dart
flutter|lib/src/widgets/basic.dart
flutter|lib/src/widgets/app.dart
flutter|lib/src/widgets/localizations.dart
flutter|lib/src/widgets/image.dart
flutter|lib/src/widgets/binding.dart
flutter|lib/src/widgets/media_query.dart
flutter|lib/src/widgets/focus_manager.dart
flutter|lib/src/widgets/editable_text.dart
flutter|lib/src/widgets/framework.dart
flutter|lib/src/widgets/icon_data.dart
flutter|lib/src/widgets/color_filter.dart
flutter|lib/src/widgets/scrollable.dart
flutter|lib/src/widgets/bottom_navigation_bar_item.dart
flutter|lib/src/widgets/semantics_debugger.dart
flutter|lib/src/widgets/widget_inspector.dart
flutter|lib/src/widgets/widget_span.dart
flutter|lib/src/widgets/icon_theme_data.dart
flutter|lib/src/cupertino/slider.dart
flutter|lib/src/cupertino/text_selection.dart
flutter|lib/src/cupertino/route.dart
flutter|lib/src/cupertino/action_sheet.dart
flutter|lib/src/cupertino/switch.dart
flutter|lib/src/cupertino/nav_bar.dart
flutter|lib/src/cupertino/bottom_tab_bar.dart
flutter|lib/src/cupertino/colors.dart
flutter|lib/src/cupertino/dialog.dart
flutter|lib/src/material/button_bar_theme.dart
flutter|lib/src/material/dialog_theme.dart
flutter|lib/src/material/mergeable_material.dart
flutter|lib/src/material/snack_bar_theme.dart
flutter|lib/src/material/input_border.dart
flutter|lib/src/material/bottom_sheet_theme.dart
flutter|lib/src/material/chip_theme.dart
flutter|lib/src/material/about.dart
flutter|lib/src/material/theme_data.dart
flutter|lib/src/material/app_bar_theme.dart
flutter|lib/src/material/material_button.dart
flutter|lib/src/material/popup_menu_theme.dart
flutter|lib/src/material/time.dart
flutter|lib/src/material/tabs.dart
flutter|lib/src/material/dropdown.dart
flutter|lib/src/material/range_slider.dart
flutter|lib/src/material/arc.dart
flutter|lib/src/material/material_state.dart
flutter|lib/src/material/divider_theme.dart
flutter|lib/src/material/card_theme.dart
flutter|lib/src/material/input_decorator.dart
flutter|lib/src/material/bottom_app_bar_theme.dart
flutter|lib/src/material/slider_theme.dart
flutter|lib/src/material/floating_action_button_theme.dart
flutter|lib/src/material/toggle_buttons_theme.dart
flutter|lib/src/material/colors.dart
flutter|lib/src/material/tooltip_theme.dart
flutter|lib/src/material/app.dart
flutter|lib/src/material/shadows.dart
flutter|lib/src/material/animated_icons.dart
flutter|lib/src/semantics/binding.dart
flutter|lib/src/semantics/semantics_service.dart
flutter|lib/src/semantics/semantics.dart
flutter|lib/src/services/platform_views.dart
flutter|lib/src/scheduler/binding.dart
flutter|lib/src/gestures/mouse_tracking.dart
flutter|lib/src/services/system_chrome.dart
flutter|lib/src/services/text_editing.dart
flutter|lib/src/services/binary_messenger.dart
flutter|lib/src/gestures/recognizer.dart
flutter|lib/src/gestures/multidrag.dart
flutter|lib/src/gestures/binding.dart
flutter|lib/src/services/system_channels.dart
flutter|lib/src/gestures/velocity_tracker.dart
flutter|lib/src/gestures/converter.dart
flutter|lib/src/gestures/force_press.dart
flutter|lib/src/gestures/drag_details.dart
flutter|lib/src/services/font_loader.dart
flutter|lib/src/gestures/events.dart
flutter|lib/src/services/platform_messages.dart
flutter|lib/src/services/text_input.dart
flutter|lib/src/gestures/multitap.dart
flutter|lib/src/services/asset_bundle.dart
flutter|lib/src/services/binding.dart
flutter|lib/src/foundation/key.dart
flutter|lib/src/foundation/consolidate_response.dart
flutter|lib/src/foundation/binding.dart
flutter|lib/src/foundation/basic_types.dart

https://github.com/dart-lang/build/blob/master/docs/faq.md#how-can-i-resolve-skipped-compiling-warnings

[INFO] Running build completed, took 54.9s

[INFO] Caching finalized dependency graph...
[INFO] Caching finalized dependency graph completed, took 264ms

[INFO] Creating merged output dir `C:\Users\pzika\AppData\Local\Temp\build_runner_test60f11734-04a4-11ea-931f-8a44ae3dc50f\`...
[INFO] Creating merged output dir `C:\Users\pzika\AppData\Local\Temp\build_runner_test60f11734-04a4-11ea-931f-8a44ae3dc50f\` completed, took 1m 2s

[INFO] Writing asset manifest...
[INFO] Writing asset manifest completed, took 29ms

[INFO] Succeeded after 1m 58s with 2096 outputs (7119 actions)

Running tests...

00:00 +0: compiling test\widget_test.dart
00:00 +0 -1: compiling test\widget_test.dart [E]
  Failed to load "test\widget_test.dart": Failed to load script at http://localhost:49276/i4iMyBxuEn8Ccr9WnZH3i%2FzZv8B%2BvRLP/test/widget_test.dart.browser_test.dart.js.
00:00 +0 -1: Some tests failed.
pub finished with exit code 1
```

**Comment by iapicca** [comment]
Hi @PavelPZ  
about `flutter pub run build_runner test -- -p "chrome"` 
there's an [issue]( https://github.com/flutter/flutter/issues/43639) currently open that addresses the problem with runners on `web `

**Comment by PavelPZ** [comment]
Hi @iapicca

```futter test --platform chrome -v``` on newly created flutter project should work?

Thanks for info

**Comment by PavelPZ** [comment]
@iapicca, you mentioned https://github.com/flutter/flutter/issues/43639 issue. I think it is not relevant because newly created flutter project has no
```
builders:
  json_serializable: any
```
in pubspec.yaml.

**Comment by PavelPZ** [comment]
For all who try to do a flutter web test, here is official @jonahwilliams [statement](https://github.com/dart-lang/test/issues/1111#issuecomment-557299240).

**Comment by yjbanov** [comment]
@jonahwilliams @grouma wasn't the transitive dependency issue fixed? (assuming this is because of that issue)

**Comment by PavelPZ** [comment]
Based on the [explanation](https://github.com/dart-lang/test/issues/1111#issuecomment-557314229) of @jakemac53 I am copying the modified issue description from wrong repository:

1. **install newest flutter (in dev channel), create new project and run the flutter web test**:
```
> flutter channel dev
> flutter upgrade
> flutter create pom
> cd pom
> pub run test -p chrome**
```
2. **thousands of error lines have appeared**, e.g.
```
00:09 +0: compiling test\widget_test.dart

...
/c:/flutter/packages/flutter/lib/src/rendering/stack.dart:675:42:
Error: 'Offset' isn't a type.
      hitTest: (BoxHitTestResult result, Offset transformed) {
...
/c:/flutter/packages/flutter/lib/src/painting/text_painter.dart:721:16:
Error: Getter not found: 'TextDirection'.
          case TextDirection.ltr:
....
```

**Comment by PavelPZ** [comment]
## So are those statement correct?
- **the only correct flutter web testing command is ```flutter test --platform chrome```** (although someone claims something else [here](https://github.com/flutter/flutter/issues/36035#issuecomment-531323820) and [here](https://github.com/flutter/flutter/issues/36035#issuecomment-557340807)).
- **this command is lightly supported and is still highly experimental (https://github.com/dart-lang/test/issues/1111#issuecomment-557299240)**
- **perhaps the main reason why testing doesn't work is [transitive dependency issue](https://github.com/flutter/flutter/issues/44583#issuecomment-557315038)**
- **flutter web testing does not work on ```flutter dev channel``` even for newly created flutter project**
- **I tested it on ```flutter master channel```, but it doesn't work either.**

I apologize for one comment at the end.

I like flutter very much. I have been developing a large language eLearning project in Dart and Flutter for almost a year. I keep watching information on the flutter repo and it's amazing how fast the development goes forward. The only thing is bad: status of 5.000+ not well maintained issues and sometimes fragmented and outdated information and documentation.

Try to read following issues
- https://github.com/flutter/flutter/issues/36035
- https://github.com/dart-lang/test/issues/1111
- this one

These can show how difficult is to get relevant and up-to-date information (some claims conflict with others). One of the reasons may be my bad English, but is it the main one?

**Comment by yjbanov** [comment]
We run hundreds of tests like this in the flutter/flutter repo. Two things to check:

- Is it possible that this is a Windows issue?
- Could it be happening when running tests inside a Flutter app project (`package:flutter` is a plain Dart package, not an app)

**Comment by obshksw** [comment]
@yjbanov 
I've been scratching my head for a while about how to run my tests for web.

This rang a bell for me:

> Is it possible that this is a Windows issue?

I was actually trying to run my tests on windows and was getting the same errors mentioned here and elsewhere (Failed to load script something.browser_test.dart.js.)

I switched to a Mac and running `flutter test --platform=chrome` actually works!

So it is really a Windows related issue.

**Comment by obshksw** [comment]
Somewhat related question, is it supposed to handle conditional imports?

How would I be able to test specific code with these for example:
import 'package:live_app/util/client/platform.dart' if (dart.library.html) 'package:live_app/util/client/platform_web.dart';

**Comment by PavelPZ** [comment]
I tried a simple test (not a widget test) with the same result:

```
import 'package:test/test.dart';
void main() {
  test('Simple', () {
    expect(0, 0);
  });
}
```
**flutter test --platform chrome** ends with
```
  Failed to load "C:\wikibulary\web\test\widget_test.dart": Failed to load script at http://localhost:64600/widget_test.dart.browser_test.dart.js.
00:00 +0 -1: Some tests failed.
```

**pubspec.yaml:**
```
name: web
description: A new Flutter project.
version: 1.0.0+1
environment:
  sdk: ">=2.1.0 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
dev_dependencies:
  test:
```

**Comment by yjbanov** [comment]
Thanks for confirming! This does look like a Windows issue. We are ramping up our test infrastructure across platforms throughout this quarter, and we'll have to address this along the way.

Having said that we're not yet sure whether this test mode is something we'll recommend developers to use. Ideally, there should be no discrepancy between running `flutter test` and `flutter test --platform=chrome`, and so `flutter test` should be sufficient. We use this mode in the framework to make sure that Flutter behaves the same everywhere.

**Comment by obshksw** [comment]
@yjbanov Thanks for the follow-up! I understand your point in saying `flutter test` should be sufficient, but how could I test conditional imports that are platform specific? I have code that runs only on the web but I can't test it adequately (at all) right now.

Example:
import 'package:live_app/util/client/platform.dart' if (dart.library.html) 'package:live_app/util/client/platform_web.dart';

My main issue is that I have to use webrtc features on the web (amongst other APIs like web audio), but for native it would not work exactly the same, so I have different classes for that, which is why I need to to do platform specific tests!

**Comment by PavelPZ** [comment]
The only workaround I found is to divide all my libraries into two parts: 
- pure dart (data models, algorithms, services etc.) that do not require flutter dependency.
  There is possible to test web libraries too (e.g. dart:indexeddb), but without flutter gui, just javascript and html.
- flutter part, where I test some view specific code. For this, I am using flutter embeded for windows.

**Comment by yjbanov** [comment]
@obshksw It sounds like you want to run a test in a real environment. `flutter test` is very much mocked out by design. It is only meant to test pure Dart logic that does not depend on functionality provided by the browser (or Android, or iOS). For your use-case you might want to write a FlutterDriver integration test. Unfortunately that support is not ready yet. We're working on adding Web support to FlutterDriver. Sadly, our last attempt [got rolled back](https://github.com/flutter/flutter/pull/47389). We'll have to try again.

**Comment by obshksw** [comment]
@yjbanov Yep, it is indeed integration tests that I want to make. I never dove into FlutterDriver, I'll take a look into it!

Thank you!

**Comment by jamesblasco** [comment]
It is happening to me too on MacOS:
flutter test  test/test.dart  
00:05 +1: All tests passed!                   
flutter test --platform chrome test/test.dart 
Failed to load script at http://localhost:55852/test.dart.browser_test.dart.js.
