### ISSUE TITLE
Container with DecorationImage does not honor Blendmode

### ISSUE THREAD

**Issue by NicolasDionB** [flutter/flutter#44585]
I'm using the master channel. My code was working great last week but since the latest update, my rendered image has changed. I'm using a `Container` with a `BoxDecoration` that includes a color with opacity and an image. The blend mode applied is `BlendMode.color`. 

![image](https://user-images.githubusercontent.com/25512495/68603782-003f7700-0477-11ea-9b1a-f63b618cd2aa.png)

## Steps to Reproduce

1. Update Flutter SDK to the latest master version
2. See the difference (screenshot)
3. Code:

``` dart
Container(
    decoration: BoxDecoration(
    color: Colors.black.withOpacity(0.6),
    backgroundBlendMode: BlendMode.color,
    image: DecorationImage(
            image: NetworkImage(VRoomConfig.activityCoverUrl),
            fit: BoxFit.cover,
        ),
    ),
    child: ...
```

**Target Platform: Web**
**Target OS version/browser: Chrome 78.0.3904.97 (64 bits)**

### flutter run --verbose
```
[  +22 ms] executing: [D:\_utils\Flutter\] git -c log.showSignature=false log -n 1 --pretty=format:%H
[  +65 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[        ] e7073f9a1f5c40398f589ae45956b489b1f3ab10
[        ] executing: [D:\_utils\Flutter\] git describe --match v*.*.* --first-parent --long --tags
[  +68 ms] Exit code 0 from: git describe --match v*.*.* --first-parent --long --tags
[        ] v1.10.15-113-ge7073f9a1
[   +5 ms] executing: [D:\_utils\Flutter\] git rev-parse --abbrev-ref --symbolic @{u}
[  +46 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/master
[        ] executing: [D:\_utils\Flutter\] git ls-remote --get-url origin
[  +43 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[  +73 ms] executing: [D:\_utils\Flutter\] git rev-parse --abbrev-ref HEAD
[  +45 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] master
[  +83 ms] executing: C:\Users\nicolas.dion\AppData\Local\Android\Sdk\platform-tools\adb.exe devices -l
[  +97 ms] Exit code 0 from: C:\Users\nicolas.dion\AppData\Local\Android\Sdk\platform-tools\adb.exe devices -l
[        ] List of devices attached
[   +8 ms] More than one device connected; please specify a device with the '-d <deviceId>' flag, or use '-d all' to act on all devices.
[  +37 ms] Chrome     • chrome     • web-javascript • Google Chrome 78.0.3904.97
[   +1 ms] Web Server • web-server • web-javascript • Flutter Tools
[   +7 ms] "flutter run" took 281ms.

#0      throwToolExit (package:flutter_tools/src/base/common.dart:28:3)
#1      RunCommand.validateCommand (package:flutter_tools/src/commands/run.dart:289:7)
<asynchronous suspension>
#2      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:545:11)
<asynchronous suspension>
#3      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:470:33)
<asynchronous suspension>
#4      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:146:29)
<asynchronous suspension>
#5      _rootRun (dart:async/zone.dart:1124:13)
#6      _CustomZone.run (dart:async/zone.dart:1021:19)
#7      _runZoned (dart:async/zone.dart:1516:10)
#8      runZoned (dart:async/zone.dart:1463:12)
#9      AppContext.run (package:flutter_tools/src/base/context.dart:145:18)
<asynchronous suspension>
#10     FlutterCommand.run (package:flutter_tools/src/runner/flutter_command.dart:460:20)
#11     CommandRunner.runCommand (package:args/command_runner.dart:197:27)
<asynchronous suspension>
#12     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:416:21)
<asynchronous suspension>
#13     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:146:29)
<asynchronous suspension>
#14     _rootRun (dart:async/zone.dart:1124:13)
#15     _CustomZone.run (dart:async/zone.dart:1021:19)
#16     _runZoned (dart:async/zone.dart:1516:10)
#17     runZoned (dart:async/zone.dart:1463:12)
#18     AppContext.run (package:flutter_tools/src/base/context.dart:145:18)
<asynchronous suspension>
#19     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:367:19)
<asynchronous suspension>
#20     CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:112:25)
#21     new Future.sync (dart:async/future.dart:222:31)
#22     CommandRunner.run (package:args/command_runner.dart:112:14)
#23     FlutterCommandRunner.run (package:flutter_tools/src/runner/flutter_command_runner.dart:251:18)
#24     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:63:22)
<asynchronous suspension>
#25     _rootRun (dart:async/zone.dart:1124:13)
#26     _CustomZone.run (dart:async/zone.dart:1021:19)
#27     _runZoned (dart:async/zone.dart:1516:10)
#28     runZoned (dart:async/zone.dart:1500:12)
#29     run.<anonymous closure> (package:flutter_tools/runner.dart:61:18)
<asynchronous suspension>
#30     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:146:29)
<asynchronous suspension>
#31     _rootRun (dart:async/zone.dart:1124:13)
#32     _CustomZone.run (dart:async/zone.dart:1021:19)
#33     _runZoned (dart:async/zone.dart:1516:10)
#34     runZoned (dart:async/zone.dart:1463:12)
#35     AppContext.run (package:flutter_tools/src/base/context.dart:145:18)
<asynchronous suspension>
#36     runInContext (package:flutter_tools/src/context_runner.dart:65:24)
<asynchronous suspension>
#37     run (package:flutter_tools/runner.dart:50:10)
#38     main (package:flutter_tools/executable.dart:65:9)
<asynchronous suspension>
#39     main (file:///D:/_utils/Flutter/packages/flutter_tools/bin/flutter_tools.dart:8:3)
#40     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:303:32)
#41     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:12)
```

### flutter analyse
```
   info - Unused import: 'package:live_app/widgets/icons/app_icons_cheatsheet.dart' - lib\app\vroom\vroom_app.dart:10:8 - unused_import
   info - The value of the field '_iceServers' isn't used - lib\managers\stream\webrtc\base_webrtc_peer.dart:30:17 - unused_field
   info - The value of the field '_mediaConstraints' isn't used - lib\managers\stream\webrtc\base_webrtc_peer.dart:58:24 - unused_field
   info - The declaration '_onGetStreamSuccess' isn't referenced - lib\managers\stream\webrtc\base_webrtc_peer.dart:117:8 - unused_element
   info - The declaration '_getDisplayMedia' isn't referenced - lib\managers\stream\webrtc\base_webrtc_peer.dart:273:8 - unused_element
   info - The declaration '_PanelHeader' isn't referenced - lib\screens\vroom\panels\panel_base.dart:293:7 - unused_element
   info - This function has a return type of 'Map<String, dynamic>', but doesn't end with a return statement - lib\util\webrtc\webrtc.dart:45:31 - missing_return
   info - This function has a return type of 'Map<String, dynamic>', but doesn't end with a return statement - lib\util\webrtc\webrtc.dart:46:31 - missing_return
   info - This function has a return type of 'Future<List>', but doesn't end with a return statement - lib\util\webrtc\webrtc.dart:49:32 - missing_return
   info - This function has a return type of 'Future<List>', but doesn't end with a return statement - lib\util\webrtc\webrtc.dart:50:32 - missing_return
   info - This function has a return type of 'Future<List>', but doesn't end with a return statement - lib\util\webrtc\webrtc.dart:51:32 - missing_return
   info - Unused import: 'package:live_app/managers/network/connection_status.dart' - test\app\vroom\vroom_app_test.dart:5:8 - unused_import
   info - Unused import: 'package:live_app/core/base_core.dart' - test\core\base_core_test.dart:1:8 - unused_import
   info - Unused import: 'package:live_app/managers/chat/chat_manager.dart' - test\core\base_core_test.dart:2:8 - unused_import
   info - Unused import: 'package:live_app/managers/login/server_info_step.dart' - test\core\base_core_test.dart:3:8 - unused_import
   info - Unused import: 'package:live_app/managers/network/hub_error.dart' - test\core\base_core_test.dart:5:8 - unused_import
   info - Unused import: 'package:test/test.dart' - test\core\base_core_test.dart:9:8 - unused_import
   info - `Future` results in `async` function bodies must be `await`ed or marked `unawaited` using `package:pedantic` - test\main_test.dart:19:7 - unawaited_futures
   info - `Future` results in `async` function bodies must be `await`ed or marked `unawaited` using `package:pedantic` - test_driver\app_test.dart:21:9 - unawaited_futures
```

### flutter doctor
```
[√] Flutter (Channel master, v1.10.16-pre.113, on Microsoft Windows [version 10.0.18362.418], locale fr-CA)
    • Flutter version 1.10.16-pre.113 at D:\_utils\Flutter
    • Framework revision e7073f9a1f (2 days ago), 2019-11-09 17:08:53 -0800
    • Engine revision 31cd2dfca2
    • Dart version 2.7.0

[!] Android toolchain - develop for Android devices (Android SDK version 29.0.0)
    • Android SDK at C:\Users\nicolas.dion\AppData\Local\Android\Sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.0
    • ANDROID_HOME = C:\Users\nicolas.dion\AppData\Local\Android\Sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[!] Android Studio (version 3.4)
    • Android Studio at C:\Program Files\Android\Android Studio
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

[!] IntelliJ IDEA Ultimate Edition (version 2016.3)
    • IntelliJ at C:\Program Files (x86)\JetBrains\IntelliJ IDEA 2016.3.8
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.dev/intellij-setup/#installing-the-plugins
    X This install is older than the minimum recommended version of 2017.1.0.

[!] IntelliJ IDEA Ultimate Edition (version 2019.2)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA 2019.2
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.dev/intellij-setup/#installing-the-plugins

[√] VS Code, 64-bit edition (version 1.39.2)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Flutter extension version 3.6.0

[√] Connected device (2 available)
    • Chrome     • chrome     • web-javascript • Google Chrome 78.0.3904.97
    • Web Server • web-server • web-javascript • Flutter Tools

! Doctor found issues in 4 categories.
```

**Comment by eliezerbasubi** [comment]
Hey @NicolasDionB, can you try the following approach, I’ve ever used it in flutter mobile development.
`Container(
    decoration: BoxDecoration(
    color: Colors.black.withOpacity(0.6),
    image: DecorationImage(
            image: NetworkImage(VRoomConfig.activityCoverUrl),
            fit: BoxFit.cover,
            blendMode: BlendMode.color
        ),
    ),`


Hope it’ll work for you.

**Comment by NicolasDionB** [comment]
> Hey @NicolasDionB, can you try the following approach, I’ve ever used it in flutter mobile development.
> `Container( decoration: BoxDecoration( color: Colors.black.withOpacity(0.6), image: DecorationImage( image: NetworkImage(VRoomConfig.activityCoverUrl), fit: BoxFit.cover, blendMode: BlendMode.color ), ),`
> 
> Hope it’ll work for you.

@eliezerbasubi I get an error with the blendMode, it seems it's not a valid parameter for `DecorationImage`...

**Comment by NicolasDionB** [comment]
I noticed that every decoration with background color that is above the image is not visible anymore. You may notice it also in my original screenshot as the white bar is totally invisible in the buggy example screenshot. Any update on this?

**Comment by eliezerbasubi** [comment]
I’ve no updates bro.
I recently I don’t have a PC, so working on your issue will be difficult
for me.

Sorry about that.
Hope someone will fix it soon or I will as soon as I get a new computer.

**Comment by NicolasDionB** [comment]
@ferhatb seems to be working on it... Hope he'll find a fix! I can't imagine I'm the only one having issues with this! It's kind of a major problem on web!

**Comment by eliezerbasubi** [comment]
You are not the only one. Issues are part of a project development.
Hope he’ll fix it soon.

**Comment by NicolasDionB** [comment]
Great news! Is the fixed in 1.13.8-pre.58? I guess not (because the bug is still there). Looking forward to try it. Cheers

**Comment by ferhatb** [comment]
@NicolasDionB : It landed in master.

**Comment by NicolasDionB** [comment]
> @NicolasDionB : It landed in master.

I just tried again with the latest master version and I still have the problem. 😞 

```
Flutter (Channel master, v1.13.9-pre.82, on Microsoft Windows [version 10.0.18362.535], locale fr-CA)
```

**Comment by ferhatb** [comment]
@NicolasDionB , we have multiple reports of issue being resolved. We tried your sample code above as well. It must be an edge case we are not able to repro. Any chance of sharing a full repro case?

**Comment by NicolasDionB** [comment]
@ferhatb You're right. I was incorrectly using the `Container` with a `BoxDecoration` which included both an image and a color. I intended the color to be on top of the image but reading the documentation again for the `image` option, I understand that it is rendered on top of the color. It used to work before but I think that was indeed a bug! So problem solved. I will use a stack with 2 containers instead. Thanks!

**Comment by ferhatb** [comment]
@NicolasDionB no worries, glad issue resolved, thx for checking.

**Comment by eliezerbasubi** [comment]
Thanks for solving that issue.
