### ISSUE TITLE
image_picker error Permission Denial

### ISSUE THREAD

**Issue by yousaywhat** [flutter/flutter#44663]
<details>
  <summary>Logs</summary>

```
E/AndroidRuntime(19384): java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=2352, result=-1, data=Intent { dat=content://com.estrongs.files/storage/emulated/0/._android.dat }} to activity {com.startiasoft.secure_samba_3/com.startiasoft.secure_samba_3.MainActivity}: java.lang.SecurityException: Permission Denial: opening provider com.estrongs.android.pop.app.FileContentProvider from ProcessRecord{574a9c4 19384:com.startiasoft.secure_samba_3/u0a2255} (pid=19384, uid=12255) that is not exported from UID 10270
E/AndroidRuntime(19384): 	at android.app.ActivityThread.deliverResults(ActivityThread.java:4489)
E/AndroidRuntime(19384): 	at android.app.ActivityThread.handleSendResult(ActivityThread.java:4532)
E/AndroidRuntime(19384): 	at android.app.ActivityThread.-wrap20(Unknown Source:0)
E/AndroidRuntime(19384): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1752)
E/AndroidRuntime(19384): 	at android.os.Handler.dispatchMessage(Handler.java:105)
E/AndroidRuntime(19384): 	at android.os.Looper.loop(Looper.java:164)
E/AndroidRuntime(19384): 	at android.app.ActivityThread.main(ActivityThread.java:6938)
E/AndroidRuntime(19384): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(19384): 	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
E/AndroidRuntime(19384): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)
E/AndroidRuntime(19384): Caused by: java.lang.SecurityException: Permission Denial: opening provider com.estrongs.android.pop.app.FileContentProvider from ProcessRecord{574a9c4 19384:com.startiasoft.secure_samba_3/u0a2255} (pid=19384, uid=12255) that is not exported from UID 10270
E/AndroidRuntime(19384): 	at android.os.Parcel.readException(Parcel.java:1967)
E/AndroidRuntime(19384): 	at android.os.Parcel.readException(Parcel.java:1913)
E/AndroidRuntime(19384): 	at android.app.IActivityManager$Stub$Proxy.getContentProvider(IActivityManager.java:5290)
E/AndroidRuntime(19384): 	at android.app.ActivityThread.acquireProvider(ActivityThread.java:6158)
E/AndroidRuntime(19384): 	at android.app.ContextImpl$ApplicationContentResolver.acquireUnstableProvider(ContextImpl.java:2559)
E/AndroidRuntime(19384): 	at android.content.ContentResolver.acquireUnstableProvider(ContentResolver.java:1786)
E/AndroidRuntime(19384): 	at android.content.ContentResolver.query(ContentResolver.java:744)
E/AndroidRuntime(19384): 	at android.content.ContentResolver.query(ContentResolver.java:710)
E/AndroidRuntime(19384): 	at android.content.ContentResolver.query(ContentResolver.java:668)
E/AndroidRuntime(19384): 	at io.flutter.plugins.imagepicker.FileUtils.getDataColumn(FileUtils.java:121)
E/AndroidRuntime(19384): 	at io.flutter.plugins.imagepicker.FileUtils.getPathFromLocalUri(FileUtils.java:105)
E/AndroidRuntime(19384): 	at io.flutter.plugins.imagepicker.FileUtils.getPathFromUri(FileUtils.java:45)
E/AndroidRuntime(19384): 	at io.flutter.plugins.imagepicker.ImagePickerDelegate.handleChooseVideoResult(ImagePickerDelegate.java:473)
E/AndroidRuntime(19384): 	at io.flutter.plugins.imagepicker.ImagePickerDelegate.onActivityResult(ImagePickerDelegate.java:448)
E/AndroidRuntime(19384): 	at io.flutter.app.FlutterPluginRegistry.onActivityResult(FlutterPluginRegistry.java:204)
E/AndroidRuntime(19384): 	at io.flutter.app.FlutterActivityDelegate.onActivityResult(FlutterActivityDelegate.java:132)
E/AndroidRuntime(19384): 	at io.flutter.app.FlutterActivity.onActivityResult(FlutterActivity.java:142)
E/AndroidRuntime(19384): 	at android.app.Activity.dispatchActivityResult(Activity.java:7548)
E/AndroidRuntime(19384): 	at android.app.ActivityThread.deliverResults(ActivityThread.java:4485)
E/AndroidRuntime(19384): 	... 9 more

```

</details>

**Comment by iapicca** [comment]
Hi @yousaywhat 
could you please provide your updated  `flutter doctor -v`
and a minimal code sample to reproduce the problem?
Thank you
