### ISSUE TITLE
[web] build error: AssetNotFoundException

### ISSUE THREAD

**Issue by pd4d10** [flutter/flutter#44698]
## Steps to Reproduce

1. Clone [pd4d10/highlight](https://github.com/pd4d10/highlight) repo's `debug` branch:
    `git clone --branch debug https://github.com/pd4d10/highlight.git`
2. Open it with VSCode and wait until dependencies installed
3. Start debugging (F5), which will launch `flutter_highlight/example/lib/main.dart`

It works correctly at iOS or Android devices. But if we select `chrome` as device it shows errors as follows:

```sh
AssetNotFoundException: flutter_highlight|lib/flutter_highlight.ddc.js
Error compiling dartdevc module:flutter_highlight|lib/flutter_highlight.ddc.js

packages/flutter_highlight/flutter_highlight.dart:95:30: Error: The getter 'highlight' isn't defined for the class 'HighlightView'.
 - 'HighlightView' is from 'package:flutter_highlight/flutter_highlight.dart' ('packages/flutter_highlight/flutter_highlight.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'highlight'.
          children: _convert(highlight.parse(source, language: language).nodes),
                             ^^^^^^^^^
```

Seems some `ddc.js` are not generated correctly.

**Target Platform:** macOS
**Target OS version/browser:** 10.15
**Devices:** Chrome 78.0.3904.87

## Logs

```
[        ] Running build...
[ +396 ms] Unable to read flutter_highlight|lib/flutter_highlight.ddc.js, check your console or the `.dart_tool/build/generated/flutter_highlight/lib/flutter_highlight.ddc.js.errors` log file.
[  +17 ms] AssetNotFoundException: flutter_highlight|lib/flutter_highlight.ddc.js
[   +1 ms] #0      bootstrapDdc (package:build_web_compilers/src/dev_compiler_bootstrap.dart:147:34)
           <asynchronous suspension>
           #1      FlutterWebEntrypointBuilder.build (package:flutter_tools/src/build_runner/build_script.dart:232:11)
           <asynchronous suspension>
           #2      runBuilder.buildForInput (package:build/src/generate/run_builder.dart:55:21)
           <asynchronous suspension>
           #3      MappedListIterable.elementAt (dart:_internal/iterable.dart:415:29)
           #4      ListIterator.moveNext (dart:_internal/iterable.dart:344:26)
           #5      Future.wait (dart:async/future.dart:391:26)
           #6      runBuilder.<anonymous closure> (package:build/src/generate/run_builder.dart:61:36)
           #7      _rootRun (dart:async/zone.dart:1124:13)
           #8      _CustomZone.run (dart:async/zone.dart:1021:19)
           #9      _runZoned (dart:async/zone.dart:1516:10)
           #10     runZoned (dart:async/zone.dart:1500:12)
           #11     scopeLogAsync (package:build/src/builder/logging.dart:22:3)
           #12     runBuilder (package:build/src/generate/run_builder.dart:61:9)
           <asynchronous suspension>
           #13     _SingleBuild._runForInput.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:build_runner_core/src/generate/build_impl.dart:478:19)
           #14     _NoOpBuilderActionTracker.trackStage (package:build_runner_core/src/generate/performance_tracker.dart:300:15)
           #15     _SingleBuild._runForInput.<anonymous closure>.<anonymous closure> (package:build_runner_core/src/generate/build_impl.dart:476:23)
           <asynchronous suspension>
           #16     NoOpTimeTracker.track (package:timing/src/timing.dart:222:44)
           #17     _SingleBuild._runForInput.<anonymous closure> (package:build_runner_core/src/generate/build_impl.dart:434:22)
           #18     Pool.withResource (package:pool/pool.dart:127:28)
           <asynchronous suspension>
           #19     _SingleBuild._runForInput (package:build_runner_core/src/generate/build_impl.dart:430:17)
           #20     _SingleBuild._runBuilder.<anonymous closure> (package:build_runner_core/src/generate/build_impl.dart:378:38)
           #21     MappedIterator.moveNext (dart:_internal/iterable.dart:393:18)
           #22     Future.wait (dart:async/future.dart:391:26)
           #23     _SingleBuild._runBuilder (package:build_runner_core/src/generate/build_impl.dart:377:36)
           <asynchronous suspension>
           #24     _SingleBuild._runPhases.<anonymous closure>.<anonymous closure> (package:build_runner_core/src/generate/build_impl.dart:323:20)
           <asynchronous suspension>
           #25     _NoOpBuildPerformanceTracker.trackBuildPhase (package:build_runner_core/src/generate/performance_tracker.dart:184:15)
           #26     _SingleBuild._runPhases.<anonymous closure> (package:build_runner_core/src/generate/build_impl.dart:319:47)
           <asynchronous suspension>
           #27     NoOpTimeTracker.track (package:timing/src/timing.dart:222:44)
           #28     _SingleBuild._runPhases (package:build_runner_core/src/generate/build_impl.dart:313:32)
           #29     logTimedAsync (package:build_runner_core/src/logging/logging.dart:25:30)
           <asynchronous suspension>
           #30     _SingleBuild._safeBuild.<anonymous closure> (package:build_runner_core/src/generate/build_impl.dart:270:26)
           <asynchronous suspension>
           #31     _rootRun (dart:async/zone.dart:1124:13)
           #32     _CustomZone.run (dart:async/zone.dart:1021:19)
           #33     _runZoned (dart:async/zone.dart:1516:10)
           #34     runZoned (dart:async/zone.dart:1500:12)
           #35     _SingleBuild._safeBuild (package:build_runner_core/src/generate/build_impl.dart:265:5)
           #36     _SingleBuild.run (package:build_runner_core/src/generate/build_impl.dart:212:24)
           <asynchronous suspension>
           #37     BuildImpl.run (package:build_runner_core/src/generate/build_impl.dart:97:56)
           #38     BuildRunnerDaemonBuilder.build (package:build_runner/src/daemon/daemon_builder.dart:111:35)
           <asynchronous suspension>
           #39     Server._build.<anonymous closure> (package:build_daemon/src/server.dart:122:25)
           #40     Pool.withResource (package:pool/pool.dart:127:28)
           <asynchronous suspension>
           #41     Server._build (package:build_daemon/src/server.dart:119:13)
           #42     Server.listen.<anonymous closure>.<anonymous closure> (package:build_daemon/src/server.dart:85:17)
           <asynchronous suspension>
           #43     _rootRunUnary (dart:async/zone.dart:1132:38)
           #44     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
           #45     _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
           #46     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
           #47     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
           #48     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:764:19)
           #49     _StreamController._add (dart:async/stream_controller.dart:640:7)
           #50     _StreamController.add (dart:async/stream_controller.dart:586:5)
           #51     new WebSocketImpl.fromSocket.<anonymous closure> (package:web_socket_channel/src/copy/web_socket_impl.dart:719:21)
           #52     _rootRunUnary (dart:async/zone.dart:1132:38)
           #53     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
           #54     _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
           #55     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
           #56     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
           #57     _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:68:11)
           #58     _EventSinkWrapper.add (dart:async/stream_transformers.dart:15:11)
           #59     _WebSocketProtocolTransformer._messageFrameEnd (package:web_socket_channel/src/copy/web_socket_impl.dart:316:22)
           #60     _WebSocketProtocolTransformer.add (package:web_socket_channel/src/copy/web_socket_impl.dart:214:46)
           #61     _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:120:24)
           #62     _rootRunUnary (dart:async/zone.dart:1132:38)
           #63     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
           #64     _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
           #65     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
           #66     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
           #67     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:764:19)
           #68     _StreamController._add (dart:async/stream_controller.dart:640:7)
           #69     _StreamController.add (dart:async/stream_controller.dart:586:5)
           #70     _Socket._onData (dart:io-patch/socket_patch.dart:1829:41)
           #71     _rootRunUnary (dart:async/zone.dart:1136:13)
           #72     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
           #73     _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
           #74     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
           #75     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
           #76     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:764:19)
           #77     _StreamController._add (dart:async/stream_controller.dart:640:7)
           #78     _StreamController.add (dart:async/stream_controller.dart:586:5)
           #79     new _RawSocket.<anonymous closure> (dart:io-patch/socket_patch.dart:1377:33)
           #80     _NativeSocket.issueReadEvent.issue (dart:io-patch/socket_patch.dart:897:14)
           #81     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
           #82     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
           #83     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:116:13)
           #84     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:173:5)

[  +93 ms] Running build completed, took 464ms

[        ] Caching finalized dependency graph...
[   +4 ms] Caching finalized dependency graph completed, took 60ms

[   +2 ms] Error compiling dartdevc module:flutter_highlight|lib/flutter_highlight.ddc.js

           packages/flutter_highlight/flutter_highlight.dart:95:30: Error: The getter 'highlight' isn't defined for the class 'HighlightView'.
            - 'HighlightView' is from 'package:flutter_highlight/flutter_highlight.dart' ('packages/flutter_highlight/flutter_highlight.dart').
           Try correcting the name to the name of an existing getter, or defining a getter or field named 'highlight'.
                     children: _convert(highlight.parse(source, language: language).nodes),
                                        ^^^^^^^^^

[   +1 ms] Failed after 533ms
[  +15 ms] Building application for the web... (completed in 8.3s)
[   +1 ms] "flutter run" took 13,029ms.
Failed to build application for the Web.

#0      throwToolExit (package:flutter_tools/src/base/common.dart:28:3)
#1      ResidentWebRunner.run (package:flutter_tools/src/build_runner/resident_web_runner.dart:244:7)
<asynchronous suspension>
#2      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:496:37)
<asynchronous suspension>
#3      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:556:18)
<asynchronous suspension>
#4      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:456:33)
<asynchronous suspension>
#5      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:157:29)
<asynchronous suspension>
#6      _rootRun (dart:async/zone.dart:1124:13)
#7      _CustomZone.run (dart:async/zone.dart:1021:19)
#8      _runZoned (dart:async/zone.dart:1516:10)
#9      runZoned (dart:async/zone.dart:1463:12)
#10     AppContext.run (package:flutter_tools/src/base/context.dart:156:18)
<asynchronous suspension>
#11     FlutterCommand.run (package:flutter_tools/src/runner/flutter_command.dart:446:20)
#12     CommandRunner.runCommand (package:args/command_runner.dart:197:27)
<asynchronous suspension>
#13     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:416:21)
<asynchronous suspension>
#14     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:157:29)
<asynchronous suspension>
#15     _rootRun (dart:async/zone.dart:1124:13)
#16     _CustomZone.run (dart:async/zone.dart:1021:19)
#17     _runZoned (dart:async/zone.dart:1516:10)
#18     runZoned (dart:async/zone.dart:1463:12)
#19     AppContext.run (package:flutter_tools/src/base/context.dart:156:18)
<asynchronous suspension>
#20     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:367:19)
<asynchronous suspension>
#21     CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:112:25)
#22     new Future.sync (dart:async/future.dart:222:31)
#23     CommandRunner.run (package:args/command_runner.dart:112:14)
#24     FlutterCommandRunner.run (package:flutter_tools/src/runner/flutter_command_runner.dart:251:18)
#25     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:63:22)
<asynchronous suspension>
#26     _rootRun (dart:async/zone.dart:1124:13)
#27     _CustomZone.run (dart:async/zone.dart:1021:19)
#28     _runZoned (dart:async/zone.dart:1516:10)
#29     runZoned (dart:async/zone.dart:1500:12)
#30     run.<anonymous closure> (package:flutter_tools/runner.dart:61:18)
<asynchronous suspension>
#31     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:157:29)
<asynchronous suspension>
#32     _rootRun (dart:async/zone.dart:1124:13)
#33     _CustomZone.run (dart:async/zone.dart:1021:19)
#34     _runZoned (dart:async/zone.dart:1516:10)
#35     runZoned (dart:async/zone.dart:1463:12)
#36     AppContext.run (package:flutter_tools/src/base/context.dart:156:18)
<asynchronous suspension>
#37     runInContext (package:flutter_tools/src/context_runner.dart:65:24)
<asynchronous suspension>
#38     run (package:flutter_tools/runner.dart:50:10)
#39     main (package:flutter_tools/executable.dart:65:9)
<asynchronous suspension>
#40     main (file:///Users/z/github/flutter/packages/flutter_tools/bin/flutter_tools.dart:8:3)
#41     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:303:32)
#42     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:12)
```

```

```

```
[✓] Flutter (Channel dev, v1.10.16, on Mac OS X 10.15 19A583, locale zh-Hans-CN)
    • Flutter version 1.10.16 at /Users/z/github/flutter
    • Framework revision 798e4272a2 (5 天前), 2019-11-06 21:04:17 -0500
    • Engine revision 34a40cfbfd
    • Dart version 2.7.0


[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/z/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.2, Build version 11B52
    • CocoaPods version 1.8.4

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 39.0.3
    • Dart plugin version 191.8423
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] VS Code (version 1.40.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.6.0

[✓] Connected device (3 available)
    • iPhone 11 Pro • 5E6E3EA5-220F-4737-897E-4CAB0043079E • ios            • com.apple.CoreSimulator.SimRuntime.iOS-13-2 (simulator)
    • Chrome        • chrome                               • web-javascript • Google Chrome 78.0.3904.97
    • Web Server    • web-server                           • web-javascript • Flutter Tools

• No issues found!
```

**Comment by yjbanov** [comment]
@jonahwilliams It looks like we keep on trucking even though there is a compiler error, which is why there's an `AssetNotFoundException`.

**Comment by vsmenon** [comment]
Note, the error on `flutter_highlight` in the original comment looks a valid error.   Has that been routed appropriately?

The tool stack trace and `AssetNotFoundException` aren't useful here.  They just obscure the actual error.
