### ISSUE TITLE
Crash when embedding with io.flutter.embedding.android.FlutterActivity on Android 4.4.2: SecurityException: uid # does not have android.permission.UPDATE_DEVICE_STATS

### ISSUE THREAD

**Issue by bDev10** [flutter/flutter#44766]
## Steps to Reproduce

1. Create embedded flutter app for Android as described in [Add Flutter to existing apps](https://github.com/flutter/flutter/wiki/Add-Flutter-to-existing-apps) docs.

2. Use [Flutter's new Android embedding](https://github.com/flutter/flutter/wiki/Add-Flutter-to-existing-apps#flutters-new-android-embedding) with embedding in Activity.

3. Create flutter engine in app's MainActivity.kt and show flutter activity when tapped on fab:
```
override fun onCreate(savedInstanceState: Bundle?) {
    super.onCreate(savedInstanceState)
    setContentView(R.layout.activity_main)
    setSupportActionBar(toolbar)

    // Instantiate your FlutterEngine.
    FlutterMain.startInitialization(applicationContext)
    FlutterMain.ensureInitializationComplete(applicationContext, null)

    val flutterEngine = FlutterEngine(applicationContext)

    // Pre-warm your FlutterEngine by starting Dart execution.
    flutterEngine
        .dartExecutor
        .executeDartEntrypoint(
            DartExecutor.DartEntrypoint.createDefault()
        )
    FlutterEngineCache
        .getInstance()
        .put(MyApplication.MAIN_FLUTTER_ENGINE_ID, flutterEngine);

    fab.setOnClickListener { view ->
        val defaultFlutter = BaseFlutterActivity.createDefaultIntent(this)
        startActivity(defaultFlutter)
    }
}
```
4. Create BaseFlutterActivity class:
```
class BaseFlutterActivity : FlutterActivity() {
    companion object {
        fun createDefaultIntent(launchContext: Context): Intent {
            val intent = Intent(launchContext, BaseFlutterActivity::class.java)
            intent.putExtra("initial_route", "/")
            intent.putExtra("destroy_engine_with_activity", false)
            return intent
        }
    }

    override fun provideFlutterEngine(context: Context): FlutterEngine? {
        return FlutterEngineCache.getInstance().get(MyApplication.MAIN_FLUTTER_ENGINE_ID)
    }
}
```
5. Start app on a device with Android 4.4.2.
6. Show flutter Activity by tapping floating action button.
7. Crash:
```
11-12 22:40:37.619 10980-10980/com.example.embedflutter E/flutter: [ERROR:flutter/shell/platform/android/platform_view_android_jni.cc(39)] java.lang.SecurityException: uid 10184 does not have android.permission.UPDATE_DEVICE_STATS.
        at android.os.Parcel.readException(Parcel.java:1465)
        at android.os.Parcel.readException(Parcel.java:1419)
        at android.app.ActivityManagerProxy.reportActivityFullyDrawn(ActivityManagerNative.java:5607)
        at android.app.Activity.reportFullyDrawn(Activity.java:1577)
        at io.flutter.embedding.android.FlutterActivity.onFlutterUiDisplayed(FlutterActivity.java:942)
        at io.flutter.embedding.android.FlutterActivityAndFragmentDelegate$1.onFlutterUiDisplayed(FlutterActivityAndFragmentDelegate.java:90)
        at io.flutter.embedding.android.FlutterView$2.onFlutterUiDisplayed(FlutterView.java:119)
        at io.flutter.embedding.engine.FlutterJNI.onFirstFrame(FlutterJNI.java:262)
        at android.os.MessageQueue.nativePollOnce(Native Method)
        at android.os.MessageQueue.next(MessageQueue.java:138)
        at android.os.Looper.loop(Looper.java:131)
        at android.app.ActivityThread.main(ActivityThread.java:5653)
        at java.lang.reflect.Method.invokeNative(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:515)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1291)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1107)
        at dalvik.system.NativeStart.main(Native Method)
```

**Target Platform:**
Android
**Target OS version/browser:**
4.4.2
**Devices:**
Samsung Galaxy Tab 3 10"
**Flutter channels:**
Tested on beta and master - both crashes.

## flutter doctor -v

```
[√] Flutter (Channel master, v1.10.17-pre.60, on Microsoft Windows [Version 10.0.18362.418], locale pl-PL)
    • Flutter version 1.10.17-pre.60 at c:\Users\BB\AppData\Local\Android\flutter
    • Framework revision 99055c754a (6 hours ago), 2019-11-12 08:04:48 -0800
    • Engine revision 31cd2dfca2
    • Dart version 2.7.0


[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at C:\Users\BB\AppData\Local\Android\Sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • ANDROID_HOME = C:\Users\BB\AppData\Local\Android\Sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)
    • All Android licenses accepted.

[√] Android Studio (version 3.5)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 40.2.2
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)

[√] Connected device (1 available)
    • GT P5210 • 3200488ab56dc000 • android-x86 • Android 4.4.2 (API 19)

• No issues found!
```

## Workaround
I managed to workaround this issue by overriding onFlutterUiDisplayed() method in my flutter activity and not calling super on API 19:
```
override fun onFlutterUiDisplayed() {
    if (Build.VERSION.SDK_INT == Build.VERSION_CODES.KITKAT) {
        return
    }
    super.onFlutterUiDisplayed()
}
```

**Comment by sufidu** [comment]
I got the same error 
`E/flutter ( 8735): [ERROR:flutter/shell/platform/android/platform_view_android_jni.cc(39)] java.lang.SecurityException: uid 10467 does not have android.permission.UPDATE_DEVICE_STATS`
even for new flutter project in `Ubuntu 18.04.3` with Samsung S3 (android 4.4.2).

If anybody knows the solution please help us. Thanks.

**Comment by sososdk** [comment]
@sufidu Override `io.flutter.embedding.android.FlutterActivity.onFlutterUiDisplayed`

```kotlin
  override fun onFlutterUiDisplayed() {
    // Notifies Android that we're fully drawn so that performance metrics can be collected by
    // Flutter performance tests.
    if (VERSION.SDK_INT > VERSION_CODES.KITKAT) {
      reportFullyDrawn()
    }
  }
```

**Comment by bDev10** [comment]
@sososdk I think calling super.onFlutterUiDisplayed() above KitKat would be more safe. 
@sufidu See the proposed workaround in my original post at the top. This works, however it should be fixed in Flutter, since there might be added some more important functionality in super.onFlutterUiDisplayed() and avoiding calling it on Android 4.4 may cause problems then.

**Comment by Xgamefactory** [comment]
Thanks @bDev10  for workaround !

Here is our MainActivity.java override.
```
@Override
    public void onFlutterUiDisplayed() {
      if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.LOLLIPOP) {
        super.onFlutterUiDisplayed();
      }
    }
```

**Comment by davieduardo94** [comment]
```
...
import android.os.Build

....
override fun onFlutterUiDisplayed() {
        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.LOLLIPOP) {
            reportFullyDrawn();
        }
    }

This is a dupe of #[46172 ](https://github.com/flutter/flutter/issues/46172) and should be fixed on master now.
```

**Comment by VladyslavBondarenko** [comment]
Given [the workaround](https://github.com/flutter/flutter/issues/46172#issuecomment-569525397) I feel safe to close this issue,
if you disagree please write in the comments
and I will reopen it. 
Thank you
