### ISSUE TITLE
 The following assertion was thrown building GZXDropDownHeader

### ISSUE THREAD

**Issue by houyongfeng1984** [flutter/flutter#44902]
I/flutter ( 8117): The following assertion was thrown building GZXDropDownHeader(dirty, dependencies:
I/flutter ( 8117): [_LocalizationsScope-[GlobalKey#dfd37], MediaQuery, _InheritedTheme], state:
I/flutter ( 8117): _GZXDropDownHeaderState#d634c):
I/flutter ( 8117): 'package:flutter/src/rendering/sliver_grid.dart': Failed assertion: line 303 pos 15:
I/flutter ( 8117): 'childAspectRatio != null && childAspectRatio > 0': is not true.
I/flutter ( 8117): Either the assertion indicates an error in the framework itself, or we should provide substantially
I/flutter ( 8117): more information in this error message to help you determine and fix the underlying cause.
I/flutter ( 8117): In either case, please report this assertion by filing a bug on GitHub:
I/flutter ( 8117):   https://github.com/flutter/flutter/issues/new?template=BUG.md
I/flutter ( 8117): User-created ancestor of the error-causing widget was:
I/flutter ( 8117):   Container file:///D:/project/dktec/znms_app/znms_app/lib/pages/home/home_page.dart:358:18
I/flutter ( 8117): When the exception was thrown, this was the stack:
I/flutter ( 8117): #2      new SliverGridDelegateWithFixedCrossAxisCount (package:flutter/src/rendering/sliver_grid.dart:303:15)
I/flutter ( 8117): #3      new GridView.count (package:flutter/src/widgets/scroll_view.dart:1583:23)
I/flutter ( 8117): #4      _GZXDropDownHeaderState.build (package:gzx_dropdown_menu/src/gzx_dropdown_header.dart:80:29)
I/flutter ( 8117): #5      StatefulElement.build (package:flutter/src/widgets/framework.dart:4064:27)
I/flutter ( 8117): #6      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3958:15)
I/flutter ( 8117): #7      Element.rebuild (package:flutter/src/widgets/framework.dart:3755:5)
I/flutter ( 8117): #8      ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3941:5)
I/flutter ( 8117): #9      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4111:11)
I/flutter ( 8117): #10     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3936:5)
I/flutter ( 8117): #11     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3109:14)
I/flutter ( 8117): #12     Element.updateChild (package:flutter/src/widgets/framework.dart:2903:12)
I/flutter ( 8117): #13     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5165:14)
I/flutter ( 8117): #14     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3109:14)
I/flutter ( 8117): #15     Element.updateChild (package:flutter/src/widgets/framework.dart:2903:12)
I/flutter ( 8117): #16     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3978:16)
I/flutter ( 8117): #17     Element.rebuild (package:flutter/src/widgets/framework.dart:3755:5)
I/flutter ( 8117): #18     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3941:5)
I/flutter ( 8117): #19     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3936:5)
I/flutter ( 8117): #20     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3109:14)
I/flutter ( 8117): #21     Element.updateChild (package:flutter/src/widgets/framework.dart:2903:12)
I/flutter ( 8117): #22     _SliverPersistentHeaderElement._build.<anonymous closure> (package:flutter/src/widgets/sliver_persistent_header.dart:198:15)
I/flutter ( 8117): #23     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2327:19)
I/flutter ( 8117): #24     _SliverPersistentHeaderElement._build (package:flutter/src/widgets/sliver_persistent_header.dart:197:11)
I/flutter ( 8117): #25     _RenderSliverPersistentHeaderForWidgetsMixin.updateChild (package:flutter/src/widgets/sliver_persistent_header.dart:265:14)
I/flutter ( 8117): #26     RenderSliverPersistentHeader.layoutChild.<anonymous closure> (package:flutter/src/rendering/sliver_persistent_header.dart:125:9)
I/flutter ( 8117): #27     RenderObject.invokeLayoutCallback.<anonymous closure> (package:flutter/src/rendering/object.dart:1815:58)
I/flutter ( 8117): #28     PipelineOwner._enableMutationsToDirtySubtrees (package:flutter/src/rendering/object.dart:875:15)
I/flutter ( 8117): #29     RenderObject.invokeLayoutCallback (package:flutter/src/rendering/object.dart:1815:13)
I/flutter ( 8117): #30     RenderSliverPersistentHeader.layoutChild (package:flutter/src/rendering/sliver_persistent_header.dart:123:7)
I/flutter ( 8117): #31     RenderSliverFloatingPersistentHeader.performLayout (package:flutter/src/rendering/sliver_persistent_header.dart:480:5)
I/flutter ( 8117): #32     RenderObject.layout (package:flutter/src/rendering/object.dart:1716:7)
I/flutter ( 8117): #33     RenderViewportBase.layoutChildSequence (package:flutter/src/rendering/viewport.dart:406:13)
I/flutter ( 8117): #34     RenderViewport._attemptLayout (package:flutter/src/rendering/viewport.dart:1355:12)
I/flutter ( 8117): #35     RenderViewport.performLayout (package:flutter/src/rendering/viewport.dart:1273:20)
I/flutter ( 8117): #36     RenderObject.layout (package:flutter/src/rendering/object.dart:1716:7)
I/flutter ( 8117): #37     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter ( 8117): #38     RenderObject.layout (package:flutter/src/rendering/object.dart:1716:7)
I/flutter ( 8117): #39     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter ( 8117): #40     RenderObject.layout (package:flutter/src/rendering/object.dart:1716:7)
I/flutter ( 8117): #41     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter ( 8117): #42     RenderObject.layout (package:flutter/src/rendering/object.dart:1716:7)
I/flutter ( 8117): #43     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter ( 8117): #44     RenderObject.layout (package:flutter/src/rendering/object.dart:1716:7)
I/flutter ( 8117): #45     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter ( 8117): #46     RenderObject.layout (package:flutter/src/rendering/object.dart:1716:7)
I/flutter ( 8117): #47     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter ( 8117): #48     RenderObject.layout (package:flutter/src/rendering/object.dart:1716:7)
I/flutter ( 8117): #49     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter ( 8117): #50     RenderObject.layout (package:flutter/src/rendering/object.dart:1716:7)
I/flutter ( 8117): #51     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter ( 8117): #52     RenderObject.layout (package:flutter/src/rendering/object.dart:1716:7)
I/flutter ( 8117): #53     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter ( 8117): #54     RenderObject.layout (package:flutter/src/rendering/object.dart:1716:7)
I/flutter ( 8117): #55     RenderStack.performLayout (package:flutter/src/rendering/stack.dart:505:15)
I/flutter ( 8117): #56     RenderObject.layout (package:flutter/src/rendering/object.dart:1716:7)
I/flutter ( 8117): #57     RenderStack.performLayout (package:flutter/src/rendering/stack.dart:505:15)
I/flutter ( 8117): #58     RenderObject.layout (package:flutter/src/rendering/object.dart:1716:7)
I/flutter ( 8117): #59     MultiChildLayoutDelegate.layoutChild (package:flutter/src/rendering/custom_layout.dart:161:11)
I/flutter ( 8117): #60     _ScaffoldLayout.performLayout (package:flutter/src/material/scaffold.dart:477:7)
I/flutter ( 8117): #61     MultiChildLayoutDelegate._callPerformLayout (package:flutter/src/rendering/custom_layout.dart:231:7)
I/flutter ( 8117): #62     RenderCustomMultiChildLayoutBox.performLayout (package:flutter/src/rendering/custom_layout.dart:392:14)
I/flutter ( 8117): #63     RenderObject.layout (package:flutter/src/rendering/object.dart:1716:7)
I/flutter ( 8117): #64     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter ( 8117): #65     RenderObject.layout (package:flutter/src/rendering/object.dart:1716:7)
I/flutter ( 8117): #66     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter ( 8117): #67     _RenderCustomClip.performLayout (package:flutter/src/rendering/proxy_box.dart:1232:11)
I/flutter ( 8117): #68     RenderObject.layout (package:flutter/src/rendering/object.dart:1716:7)
I/flutter ( 8117): #69     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter ( 8117): #70     RenderObject.layout (package:flutter/src/rendering/object.dart:1716:7)
I/flutter ( 8117): #71     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter ( 8117): #72     RenderObject.layout (package:flutter/src/rendering/object.dart:1716:7)
I/flutter ( 8117): #73     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter ( 8117): #74     RenderObject.layout (package:flutter/src/rendering/object.dart:1716:7)
I/flutter ( 8117): #75     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter ( 8117): #76     RenderObject.layout (package:flutter/src/rendering/object.dart:1716:7)
I/flutter ( 8117): #77     RenderSliverFixedExtentBoxAdaptor.performLayout (package:flutter/src/rendering/sliver_fixed_extent_list.dart:245:18)
I/flutter ( 8117): #78     RenderObject.layout (package:flutter/src/rendering/object.dart:1716:7)
I/flutter ( 8117): #79     RenderSliverPadding.performLayout (package:flutter/src/rendering/sliver_padding.dart:181:11)
I/flutter ( 8117): #80     RenderObject.layout (package:flutter/src/rendering/object.dart:1716:7)
I/flutter ( 8117): #81     _RenderSliverLayoutBuilder.performLayout (package:flutter/src/widgets/sliver_layout_builder.dart:56:12)
I/flutter ( 8117): #82     RenderObject.layout (package:flutter/src/rendering/object.dart:1716:7)
I/flutter ( 8117): #83     RenderViewportBase.layoutChildSequence (package:flutter/src/rendering/viewport.dart:406:13)
I/flutter ( 8117): #84     RenderViewport._attemptLayout (package:flutter/src/rendering/viewport.dart:1355:12)
I/flutter ( 8117): #85     RenderViewport.performLayout (package:flutter/src/rendering/viewport.dart:1273:20)
I/flutter ( 8117): #86     RenderObject.layout (package:flutter/src/rendering/object.dart:1716:7)
I/flutter ( 8117): #87     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter ( 8117): #88     RenderObject.layout (package:flutter/src/rendering/object.dart:1716:7)
I/flutter ( 8117): #89     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter ( 8117): #90     RenderObject.layout (package:flutter/src/rendering/object.dart:1716:7)
I/flutter ( 8117): #91     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter ( 8117): #92     RenderObject.layout (package:flutter/src/rendering/object.dart:1716:7)
I/flutter ( 8117): #93     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter ( 8117): #94     RenderObject.layout (package:flutter/src/rendering/object.dart:1716:7)
I/flutter ( 8117): #95     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter ( 8117): #96     RenderObject.layout (package:flutter/src/rendering/object.dart:1716:7)
I/flutter ( 8117): #97     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter ( 8117): #98     RenderObject.layout (package:flutter/src/rendering/object.dart:1716:7)
I/flutter ( 8117): #99     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter ( 8117): #100    RenderObject.layout (package:flutter/src/rendering/object.dart:1716:7)
I/flutter ( 8117): #101    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter ( 8117): #102    RenderObject.layout (package:flutter/src/rendering/object.dart:1716:7)
I/flutter ( 8117): #103    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter ( 8117): #104    RenderObject.layout (package:flutter/src/rendering/object.dart:1716:7)
I/flutter ( 8117): #105    MultiChildLayoutDelegate.layoutChild (package:flutter/src/rendering/custom_layout.dart:161:11)
I/flutter ( 8117): #106    _ScaffoldLayout.performLayout (package:flutter/src/material/scaffold.dart:477:7)
I/flutter ( 8117): #107    MultiChildLayoutDelegate._callPerformLayout (package:flutter/src/rendering/custom_layout.dart:231:7)
I/flutter ( 8117): #108    RenderCustomMultiChildLayoutBox.performLayout (package:flutter/src/rendering/custom_layout.dart:392:14)
I/flutter ( 8117): #109    RenderObject.layout (package:flutter/src/rendering/object.dart:1716:7)
I/flutter ( 8117): #110    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter ( 8117): #111    RenderObject.layout (package:flutter/src/rendering/object.dart:1716:7)
I/flutter ( 8117): #112    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter ( 8117): #113    _RenderCustomClip.performLayout (package:flutter/src/rendering/proxy_box.dart:1232:11)
I/flutter ( 8117): #114    RenderObject.layout (package:flutter/src/rendering/object.dart:1716:7)
I/flutter ( 8117): #115    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter ( 8117): #116    RenderObject.layout (package:flutter/src/rendering/object.dart:1716:7)
I/flutter ( 8117): #117    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter ( 8117): #118    RenderObject.layout (package:flutter/src/rendering/object.dart:1716:7)
I/flutter ( 8117): #119    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter ( 8117): #120    RenderObject.layout (package:flutter/src/rendering/object.dart:1716:7)
I/flutter ( 8117): #121    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter ( 8117): #122    RenderObject.layout (package:flutter/src/rendering/object.dart:1716:7)
I/flutter ( 8117): #123    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter ( 8117): #124    RenderObject.layout (package:flutter/src/rendering/object.dart:1716:7)
I/flutter ( 8117): #125    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter ( 8117): #126    RenderObject.layout (package:flutter/src/rendering/object.dart:1716:7)
I/flutter ( 8117): #127    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/Choreographer( 8117): Skipped 110 frames!  The application may be doing too much work on its main thread.
I/flutter ( 8117): #128    RenderObject.layout (package:flutter/src/rendering/object.dart:1716:7)
I/flutter ( 8117): #129    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter ( 8117): #130    RenderOffstage.performLayout (package:flutter/src/rendering/proxy_box.dart:3140:13)
I/flutter ( 8117): #131    RenderObject.layout (package:flutter/src/rendering/object.dart:1716:7)
I/flutter ( 8117): #132    RenderStack.performLayout (package:flutter/src/rendering/stack.dart:505:15)
I/flutter ( 8117): #133    RenderObject.layout (package:flutter/src/rendering/object.dart:1716:7)
I/flutter ( 8117): #134    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter ( 8117): #135    RenderObject.layout (package:flutter/src/rendering/object.dart:1716:7)
I/flutter ( 8117): #136    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter ( 8117): #137    RenderObject.layout (package:flutter/src/rendering/object.dart:1716:7)
I/flutter ( 8117): #138    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter ( 8117): #139    RenderObject.layout (package:flutter/src/rendering/object.dart:1716:7)
I/flutter ( 8117): #140    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter ( 8117): #141    RenderObject.layout (package:flutter/src/rendering/object.dart:1716:7)
I/flutter ( 8117): #142    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter ( 8117): #143    RenderObject.layout (package:flutter/src/rendering/object.dart:1716:7)
I/flutter ( 8117): #144    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
I/flutter ( 8117): #145    RenderObject.layout (package:flutter/src/rendering/object.dart:1716:7)
I/flutter ( 8117): #146    RenderView.performLayout (package:flutter/src/rendering/view.dart:164:13)
I/flutter ( 8117): #147    RenderObject._layoutWithoutResize (package:flutter/src/rendering/object.dart:1584:7)
I/flutter ( 8117): #148    PipelineOwner.flushLayout (package:flutter/src/rendering/object.dart:844:18)
I/flutter ( 8117): #149    RendererBinding.drawFrame (package:flutter/src/rendering/binding.dart:344:19)
I/flutter ( 8117): #150    WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:777:13)
I/flutter ( 8117): #151    RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:283:5)
I/flutter ( 8117): #152    SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1043:15)
I/flutter ( 8117): #153    SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:982:9)
I/flutter ( 8117): #154    SchedulerBinding.scheduleWarmUpFrame.<anonymous closure> (package:flutter/src/scheduler/binding.dart:791:7)
I/flutter ( 8117): #163    _Timer._runTimers (dart:isolate-patch/timer_impl.dart:382:19)
I/flutter ( 8117): #164    _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:416:5)
I/flutter ( 8117): #165    _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:12)
I/flutter ( 8117): (elided 10 frames from class _AssertionError, package dart:async, and package dart:async-patch)
I/flutter ( 8117):

**Comment by janmoppel** [comment]
Hello @houyongfeng1984 !

Thank you for posting a stack trace here.

Can you please also provide additional information such as an output of the `flutter doctor -v` command and minimal steps to reproduce this issue?

Thank you.

**Comment by houyongfeng1984** [comment]
assert(childAspectRatio != null && childAspectRatio > 0);

**Comment by houyongfeng1984** [comment]
const SliverGridDelegateWithFixedCrossAxisCount({
    @required this.crossAxisCount,
    this.mainAxisSpacing = 0.0,
    this.crossAxisSpacing = 0.0,
    this.childAspectRatio = 1.0,
  }) : assert(crossAxisCount != null && crossAxisCount > 0),
       assert(mainAxisSpacing != null && mainAxisSpacing >= 0),
       assert(crossAxisSpacing != null && crossAxisSpacing >= 0),
       assert(childAspectRatio != null && childAspectRatio > 0); this assert throw

**Comment by goderbauer** [comment]
Do you still have a minimal sample that reproduces the problem so we can debug it?
