### ISSUE TITLE
Invalid value: Not in range 0..1207, inclusive: 7359

### ISSUE THREAD

**Issue by andredealmei** [flutter/flutter#44919]
when i try to use flutter build apk

> [√] Flutter (Channel master, v1.11.1-pre.49, on Microsoft Windows [versÃ£o 10.0.17763.805], locale pt-BR)
[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[√] Chrome - develop for the web
[!] Android Studio (version 4.0)
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
[√] VS Code (version 1.40.0)
[√] Connected device (2 available)

****

<details>
  <summary>file_helper.dart</summary>

```

import 'package:universal_html/html.dart' as html;

import 'package:flutter/foundation.dart';

class FileHelper {
  void startWebFilePicker(Function onStartSelect, Function onSelectEnd) {
    if (kIsWeb) {
      final html.InputElement uploadInput = html.FileUploadInputElement();
      // abre dialogo para selecionar arquivo para upload
      uploadInput.click();

      // listener para quando ouver um evento no [uploadInput]
      uploadInput.onChange.listen(
        (e) {
          final files = uploadInput.files;

          //verifica se existem arquivos no evento
          if (files.length == 1) {
            // aciciona o indicador de arquivo carregando
            if (onStartSelect != null) {
              onStartSelect();
            }
            final file = files[0];

            final reader = html.FileReader();

            reader.onLoadEnd.listen(
              (e) {
                if (onSelectEnd != null) {
                  onSelectEnd({'file': reader.result, 'fileName': file.name});
                }
              },
            );
            reader.readAsDataUrl(file);
          }
        },
      );
    }
  }
}
```
</details>

<details>
  <summary>full error</summary>

```
Unhandled exception:
Crash when compiling file:///C:/Users/usuario/Documents/flutter/the_office/lib/helpers/file_helper.dart,
a
t character offset 206:
RangeError (offset): Invalid value: Not in range 0..1207, inclusive: 7359
#0      RangeError.checkValueInInterval (dart:core/errors.dart:281:7)
#1      Source.getLocation (package:kernel/ast.dart:7113:16)
#2      getLocation (package:front_end/src/fasta/messages.dart:16:52)
#3      ProcessedOptions.format (package:front_end/src/base/processed_options.dart:205:47)
#4      ProcessedOptions.report (package:front_end/src/base/processed_options.dart:228:29)
#5     
 CompilerContext.report (package:front_end/src/fasta/compiler_context.dart:69:13)
#6      Loader.addMessage
 (package:front_end/src/fasta/loader.dart:325:20)
#7      Loader.addProblem (package:front_end/src/fasta/loader.dart:287:12)
#8      LibraryBuilderImpl.a
ddProblem (package:front_end/src/fasta/builder/library_builder.dart:283:19)
#9      SourceLibraryBuilder.addProblem (packag
e:front_end/src/fasta/source/source_library_builder.dart:1239:47)
#10     BodyBuilder.addProblem (package:front_end/src/fasta/kernel/body_builder.dart:5497:20)
#11     BodyBuilder.addProblemErrorIfConst (package:front_end/src/fasta/kernel/body_builder.dart:5511:5)
#12     BodyBuilder.buildAbstractClassInstantiationError 
(package:front_end/src/fasta/kernel/body_builder.dart:5190:5)
#13     BodyBuild
er.resolveRedirectingFactoryTargets (package:front_end/src/fasta/kernel/body_builder.dart:1088:13)
#14     BodyBuilder.finishFunction (package:front_end/src
/fasta/kernel/body_builder.dart:946:5)
#15     DietListener.listenerFinishFunction (package:front_end/src/fasta/source/diet_listener.dart:904:14)
#16     D
ietListener.buildFunctionBody (package:front_end/src/fasta/source/diet_listener.dart:937:7)
#17     DietListener.en
dClassMethod (package:front_end/src/fasta/source/diet_listener.dart:664:5)
#18     Parser.parseMethod (package:_fe_anal
yzer_shared/src/parser/parser_impl.dart:3480:20)
#19     Parser.parseClassOrMixinOrExtensionMemberImpl (package:_fe_
analyzer_shared/src/parser/parser_impl.dart:3241:15)
#20     Parser.parseClassOrMixinOrExtensionBody (package:_fe
_analyzer_shared/src/parser/parser_impl.dart:2974:15)
#21     Parser.parseClass (package:_fe_analyzer_shared/src/
parser/parser_impl.dart:1820:13)
#22     Parser.parseClassOrNamedMixinApplication (package:_fe_analyzer_shared/src/parser/parser_impl.d
art:1779:14)
#23     Parser.parseTopLevelKeywordDeclaration (package:_fe_analyzer_shared/src/parser/parser_impl.dart:5
74:14)
#24     Parser.parseTopLevelDeclarationImpl (package:_fe_analyzer_shared/src/parser/parser_impl.dart:470:14)
#25     Parser
.parseUnit (package:_fe_analyzer_shared/src/parser/parser_impl.dart:352:15)
#26     SourceLoader.buildBody (package:fron
t_end/src/fasta/source/source_loader.dart:309:14)
<asynchronous suspension>
#27     Loader.buildBodies (package:front_end/src/fa
sta/loader.dart:243:15)
<asynchronous suspension>
#28     KernelTarget.buildComponent.<anonymous closure> (package:front_end/src/fasta/kernel/kernel_targ
et.dart:302:20)
<asynchronous suspension>
#29     withCrashReporting (package:front_end/src/fasta/crash.dart:122:24)
<as
ynchronous suspension>
#30     KernelTarget.buildComponent (package:front_end/src/fasta/kernel/kernel_target.dart:300:12)

<asynchronous suspension>
#31     generateKernelInternal.<anonymous closure> (package:front_end/src/kernel_generator_impl.dart:
166:38)
<asynchronous suspension>
#32     withCrashReporting (package:front_end/src/fasta/crash.dart:122:24)
<asynchronous 
suspension>
#33     generateKernelInternal (package:front_end/src/kernel_generator_impl.dart:70:10)
<asynchronous s
uspension>
#34     kernelForProgramInternal.<anonymous closure> (package:front_end/src/api_prototype/kernel_generator.dart:6
1:35)
<asynchronous suspension>
#35     CompilerContext.runWithOptions.<anonymous closure> (package:fr
ont_end/src/fasta/compiler_context.dart:135:20)
<asynchronous suspension>
#36     CompilerContext.runInContext.<anonymo
us closure>.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart:123:46)
#37     new Future.sync (dart:async/future.dart:222:31)
#38    
 CompilerContext.runInContext.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart:123:19)
#39     _rootRun 
(dart:async/zone.dart:1124:13)
#40     _CustomZone.run (dart:async/zone.dart:1021:19)
#41     _runZoned (dart:async/zone.dart:1516
:10)
#42     runZoned (dart:async/zone.dart:1463:12)
#43     CompilerContext.runInContext (package:front_end/src/fasta/compiler_c
ontext.dart:122:12)
#44     CompilerContext.runWithOptions (package:front_end/src/fasta/compiler_context.dart:133:10)
#45    
 kernelForProgramInternal (package:front_end/src/api_prototype/kernel_generator.dart:60:32)
<asynchronous suspension>
#46     
kernelForProgram (package:front_end/src/api_prototype/kernel_generator.dart:52:17)
<asynchronous suspension>
#47     compi
leToKernel (package:vm/kernel_front_end.dart:316:41)
<asynchronous suspension>
#48     FrontendCompiler.compile.<anonymous closure
> (package:frontend_server/frontend_server.dart:445:54)
#49     new Future.<anonymous closure> (dart:async/future.dart:174:37)
#50
     _rootRun (dart:async/zone.dart:1120:38)
#51     _CustomZone.run (dart:async/zone.dart:1021:19)
#52     _CustomZone.runG
uarded (dart:async/zone.dart:923:7)
#53     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:9
63:23)
#54     _rootRun (dart:async/zone.dart:1124:13)
#55     _CustomZone.run (dart:async/zone.dart:1021:19)
#56     _Cus
tomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:947:23)
#57     Timer._createTimer.<anonymous
 closure> (dart:async-patch/timer_patch.dart:21:15)
#58     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:382:19)
#59 
    _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:416:5)
#60     _RawReceivePortImpl._handleMessage (dart
:isolate-patch/isolate_patch.dart:172:12)


#0      DietListener.buildFunctionBody (package:front_end/src/fasta/source/diet_listener.dar
t:942:7)
#1      DietListener.endClassMethod (package:front_end/src/fasta/source/diet_listener.dart:664:5)
#2      Pa
rser.parseMethod (package:_fe_analyzer_shared/src/parser/parser_impl.dart:3480:20)
#3      Parser.parseClassOrMixinOrExte
nsionMemberImpl (package:_fe_analyzer_shared/src/parser/parser_impl.dart:3241:15)
#4      Parser.parseClassOrMixinOrExtensi
onBody (package:_fe_analyzer_shared/src/parser/parser_impl.dart:2974:15)
#5      Parser.parseClass (package:_fe_analyz
er_shared/src/parser/parser_impl.dart:1820:13)
#6      Parser.parseClassOrNamedMixinApplication (package:_fe_analyze
r_shared/src/parser/parser_impl.dart:1779:14)
#7      Parser.parseTopLevelKeywordDeclaration (package:_fe_analyzer_sha
red/src/parser/parser_impl.dart:574:14)
#8      Parser.parseTopLevelDeclarationImpl (package:_fe_analyzer_shared/src/parser/parser_i
mpl.dart:470:14)
#9      Parser.parseUnit (package:_fe_analyzer_shared/src/parser/parser_impl.dart:352:15)
#10     Sou
rceLoader.buildBody (package:front_end/src/fasta/source/source_loader.dart:309:14)
<asynchronous suspension>
#11     Loader.buildBodies (package:front_end/src/f
asta/loader.dart:243:15)
<asynchronous suspension>
#12     KernelTarget.buildComponent.<anonymous closure> (package:front_e
nd/src/fasta/kernel/kernel_target.dart:302:20)
<asynchronous suspension>
#13     withCrashReporting (package:front_end/src/
fasta/crash.dart:122:24)
<asynchronous suspension>
#14     KernelTarget.buildComponent (package:front_end/src/fasta/kernel/k
ernel_target.dart:300:12)
<asynchronous suspension>
#15     generateKernelInternal.<anonymous closure> (package:fron
t_end/src/kernel_generator_impl.dart:166:38)
<asynchronous suspension>
#16     withCrashReporting (package:front_end/src/fasta/crash.dart:122:24)
<asynchronous 
suspension>
#17     generateKernelInternal (package:front_end/src/kernel_generator_impl.dart:70:10)
<asynchronous su
spension>
#18     kernelForProgramInternal.<anonymous closure> (package:front_end/src/api_prototype/kernel_generator.dart:
61:35)
<asynchronous suspension>
#19     CompilerContext.runWithOptions.<anonymous closure> (package:front_end/src/fasta/c
ompiler_context.dart:135:20)
<asynchronous suspension>
#20     CompilerContext.runInContext.<anonymous closure>.
<anonymous closure> (package:front_end/src/fasta/compiler_context.dart:123:46)
#21     new Future.sync (dart:async/future.
dart:222:31)
#22     CompilerContext.runInContext.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart:1
23:19)
#23     _rootRun (dart:async/zone.dart:1124:13)
#24     _CustomZone.run (dart:async/zone.dart:1021:19)
#25 
    _runZoned (dart:async/zone.dart:1516:10)
#26     runZoned (dart:async/zone.dart:1463:12)
#27     CompilerContext.runInContext (package:front_end/src/fasta/compiler_contex
t.dart:122:12)
#28     CompilerContext.runWithOptions (package:front_end/src/fasta/compiler_context.dart:133:10)
#29     k
ernelForProgramInternal (package:front_end/src/api_prototype/kernel_generator.dart:60:32)
<asynchronous suspension>
#30 
    kernelForProgram (package:front_end/src/api_prototype/kernel_generator.dart:52:17)
<asynchronous suspension>
#31     compileToKernel (package:vm/kernel_front_end.dart:316:41)
<asynchronous suspension>
#32     FrontendCompiler.compile.<anonymous closure> (package:frontend_server/frontend_se
rver.dart:445:54)
#33     new Future.<anonymous closure> (dart:async/f
uture.dart:174:37)
#34     _rootRun (dart:async/zone.dart:1120:38)
#35     _CustomZone.run (dart:async/zone.dart:1021:19)
#36     _CustomZone.runGu
arded (dart:async/zone.dart:923:7)
#37     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.da
rt:963:23)
#38     _rootRun (dart:async/zone.dart:1124:13)
#39     _CustomZone.run (dart:async/zone.dart:1021:19)
#40     _CustomZone.bindCallback.<anonymous closure> (dar
t:async/zone.dart:947:23)
#41     Timer._createTimer.<anonymous closure> (dart:async-patch/timer_patch.dart
:21:15)
#42     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:382:19)
#43     _Timer._handleMessage (dart:iso
late-patch/timer_impl.dart:416:5)
#44     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.
dart:172:12)

Target kernel_snapshot failed: Exception: Errors during snapshot creation: null
#0      KernelSnapshot.build (package:flutter_tools/src/build_system/targets/dart.dart:231:7)
<asynchronous suspension>
#1      _BuildInstance._invokeInternal (package:flutter_tools/src/build_system/build_system.dart:526:25)
<asynchronous suspension>
#2      _BuildInstance.invokeTarget.<anonymous closure> (package:flutter_tools/src/build_system/build_system.dart:481:35)
#3      new Future.sync (dart:async/future.dart:222:31)
#4      AsyncMemoizer.runOnce (package:async/src/async_memoizer.dart:43:45)
#5      _BuildInstance.invokeTarget (package:flutter_tools/src/build_system/build_system.dart:481:21)
<asynchronous suspension>
<asynchronous suspension>
<asynchronous suspension>
#6      BuildSystem.build (package:flutter_tools/src/build_system/build_system.dart:419:36)
<asynchronous suspension>
#7      AssembleCommand.runCommand (package:flutter_tools/src/commands/assemble.dart:154:50)
<asynchronous suspension>
#8      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:607:18)
<asynchronous suspension>
#9      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:507:33)
<asynchronous suspension>
#10     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:146:29)
<asynchronous suspension>
#11     _rootRun (dart:async/zone.dart:1124:13)
#12     _CustomZone.run (dart:async/zone.dart:1021:19)
#13     _runZoned (dart:async/zone.dart:1516:10)
#14     runZoned (dart:async/zone.dart:1463:12)
#15     AppContext.run (package:flutter_tools/src/base/context.dart:145:18)
<asynchronous suspension>
#16     FlutterCommand.run (package:flutter_tools/src/runner/flutter_command.dart:497:20)
#17     CommandRunner.runCommand (package:args/command_runner.dart:197:27)
<asynchronous suspension>
#18     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:416:21)
<asynchronous suspension>
#19     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:146:29)
<asynchronous suspension>
#20     _rootRun (dart:async/zone.dart:1124:13)
#21     _CustomZone.run (dart:async/zone.dart:1021:19)
#22     _runZoned (dart:async/zone.dart:1516:10)
#23     runZoned (dart:async/zone.dart:1463:12)
#24     AppContext.run (package:flutter_tools/src/base/context.dart:145:18)
<asynchronous suspension>
#25     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:367:19)
<asynchronous suspension>
#26     CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:112:25)
#27     new Future.sync (dart:async/future.dart:222:31)
#28     CommandRunner.run (package:args/command_runner.dart:112:14)
#29     FlutterCommandRunner.run (package:flutter_tools/src/runner/flutter_command_runner.dart:251:18)
#30     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:63:22)
<asynchronous suspension>
#31     _rootRun (dart:async/zone.dart:1124:13)
#32     _CustomZone.run (dart:async/zone.dart:1021:19)
#33     _runZoned (dart:async/zone.dart:1516:10)
#34     runZoned (dart:async/zone.dart:1500:12)
#35     run.<anonymous closure> (package:flutter_tools/runner.dart:61:18)
<asynchronous suspension>
#36     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:146:29)
<asynchronous suspension>
#37     _rootRun (dart:async/zone.dart:1124:13)
#38     _CustomZone.run (dart:async/zone.dart:1021:19)
#39     _runZoned (dart:async/zone.dart:1516:10)
#40     runZoned (dart:async/zone.dart:1463:12)
#41     AppContext.run (package:flutter_tools/src/base/context.dart:145:18)
<asynchronous suspension>
#42     runInContext (package:flutter_tools/src/context_runner.dart:65:24)
<asynchronous suspension>
#43     run (package:flutter_tools/runner.dart:50:10)
#44     main (package:flutter_tools/executable.dart:65:9)
<asynchronous suspension>
#45     main (file:///C:/flutter/packages/flutter_tools/bin/flutter_tools.dart:8:3)
#46     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:303:32)
#47     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:12)

build failed.

FAILURE: Build failed with an exception.

* Where:
Script 'C:\flutter\packages\flutter_tools\gradle\flutter.gradle' line: 716

* What went wrong:
Execution failed for task ':app:compileFlutterBuildReleaseArm'.
> Process 'command 'C:\flutter\bin\flutter.bat'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 6s
Running Gradle task 'assembleRelease'...
Running Gradle task 'assembleRelease'... Done                       7,4s
Gradle task assembleRelease failed with exit code 1

```

</details>

**Comment by TahaTesser** [comment]
Hi @andredealmei 
The is a tool crash, this is most likely, if the issue persists, please file a new issue with all the details
