### ISSUE TITLE
[image_picker] Plugin crash when picking an svg

### ISSUE THREAD

**Issue by ezfuncreations** [flutter/flutter#44981]
Environment: 
Windows 10,
Android Studio 3.5.2,
image_picker 0.6.1+11,
Flutter (Channel stable, v1.9.1+hotfix.6)

After opening the image picker in order to select an image, svg files are selectable. Upon selection of any one of them following exception occurs and the application crashes:

```
> E/AndroidRuntime(23644): java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=2342, result=-1, data=Intent { dat=content://com.android.providers.downloads.documents/document/raw:/storage/emulated/0/Download/rysunek-1.svg flg=0x1 }} to activity {com.vobacom.ems_project/com.vobacom.ems_project.MainActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'int android.graphics.Bitmap.getWidth()' on a null object reference
> E/AndroidRuntime(23644): 	at android.app.ActivityThread.deliverResults(ActivityThread.java:4643)
> E/AndroidRuntime(23644): 	at android.app.ActivityThread.handleSendResult(ActivityThread.java:4685)
> E/AndroidRuntime(23644): 	at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:49)
> E/AndroidRuntime(23644): 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
> E/AndroidRuntime(23644): 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
> E/AndroidRuntime(23644): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1970)
> E/AndroidRuntime(23644): 	at android.os.Handler.dispatchMessage(Handler.java:106)
> E/AndroidRuntime(23644): 	at android.os.Looper.loop(Looper.java:214)
> E/AndroidRuntime(23644): 	at android.app.ActivityThread.main(ActivityThread.java:7156)
> E/AndroidRuntime(23644): 	at java.lang.reflect.Method.invoke(Native Method)
> E/AndroidRuntime(23644): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
> E/AndroidRuntime(23644): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:975)
> E/AndroidRuntime(23644): Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'int android.graphics.Bitmap.getWidth()' on a null object reference
> E/AndroidRuntime(23644): 	at io.flutter.plugins.imagepicker.ImageResizer.resizedImage(ImageResizer.java:52)
> E/AndroidRuntime(23644): 	at io.flutter.plugins.imagepicker.ImageResizer.resizeImageIfNeeded(ImageResizer.java:40)
> E/AndroidRuntime(23644): 	at io.flutter.plugins.imagepicker.ImagePickerDelegate.handleImageResult(ImagePickerDelegate.java:530)
> E/AndroidRuntime(23644): 	at io.flutter.plugins.imagepicker.ImagePickerDelegate.handleChooseImageResult(ImagePickerDelegate.java:463)
> E/AndroidRuntime(23644): 	at io.flutter.plugins.imagepicker.ImagePickerDelegate.onActivityResult(ImagePickerDelegate.java:442)
> E/AndroidRuntime(23644): 	at io.flutter.app.FlutterPluginRegistry.onActivityResult(FlutterPluginRegistry.java:204)
> E/AndroidRuntime(23644): 	at io.flutter.app.FlutterActivityDelegate.onActivityResult(FlutterActivityDelegate.java:132)
> E/AndroidRuntime(23644): 	at io.flutter.app.FlutterActivity.onActivityResult(FlutterActivity.java:142)
> E/AndroidRuntime(23644): 	at android.app.Activity.dispatchActivityResult(Activity.java:7791)
> E/AndroidRuntime(23644): 	at android.app.ActivityThread.deliverResults(ActivityThread.java:4636)
> E/AndroidRuntime(23644): 	... 11 more
```

**Comment by iapicca** [comment]
Hi @ezfuncreations 
from you logs looks like that `getWidth() `was called on `null `
```
E/AndroidRuntime(23644): Caused by: java.lang.NullPointerException: 
Attempt to invoke virtual method 'int android.graphics.Bitmap.getWidth()' on a null object reference
```

could you please provide your updated  `flutter doctor -v`
and a minimal code sample to reproduce the problem
Thank you

**Comment by ezfuncreations** [comment]
sure, here's the flutter doctor: 

> [√] Flutter (Channel stable, v1.9.1+hotfix.6, on Microsoft Windows [Version 10.0.18362.418], locale pl-PL)
>     • Flutter version 1.9.1+hotfix.6 at C:\src\flutter
>     • Framework revision 68587a0916 (9 weeks ago), 2019-09-13 19:46:58 -0700
>     • Engine revision b863200c37
>     • Dart version 2.5.0
> 
> 
> [√] Android toolchain - develop for Android devices (Android SDK version 29.0.1)
>     • Android SDK at C:\Users\admin\AppData\Local\Android\sdk
>     • Android NDK location not configured (optional; useful for native profiling support)
>     • Platform android-29, build-tools 29.0.1
>     • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
>     • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)
>     • All Android licenses accepted.
> 
> [√] Android Studio (version 3.5)
>     • Android Studio at C:\Program Files\Android\Android Studio
>     • Flutter plugin version 41.1.2
>     • Dart plugin version 191.8593
>     • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)
> 
> [√] Connected device (1 available)
>     • SM J730F • 5200dcce5a5f9409 • android-arm • Android 9 (API 28)
> 
> • No issues found!
> 

and minimal code sample would be a simple line: 
`File image = await ImagePicker.pickImage(source: ImageSource.gallery);`
Then in the picker, you'd want to select any kind of SVG file which upon selection will cause the above mentioned exception.

**Comment by friebetill** [comment]
I can confirm the crashes, so I've changed the code to **make SVG images selectable**, see [here](https://github.com/friebetill/plugins/commit/4b63ac60c43e1722c4e18055e640a3b0936a0ffa). The code change is currently hacky, I replaced the entire file [FileUtils](https://github.com/flutter/plugins/blob/master/packages/image_picker/android/src/main/java/io/flutter/plugins/imagepicker/FileUtils.java) with [FileUtils](https://github.com/miguelpruivo/flutter_file_picker/blob/master/android/src/main/java/com/mr/flutter/plugin/filepicker/FileUtils.java) from the plugin [file_picker](https://pub.dev/packages/file_picker), because selecting a SVG worked there. I would minimize the changes if it has a chance to be merged.

I find the feature to select SVG files (and GIFs also) should be supported. 
Currently one could use [file_picker](https://pub.dev/packages/file_picker) instead, but I noticed that when I select a file there and then compress it with [flutter_image_compress](https://pub.dev/packages/flutter_image_compress), it takes a noticeable time longer than doing the compression directly with `image_picker`.

**Comment by timsneath** [comment]
Adding @mklim -- is this a change we would consider, Michael?

**Comment by mklim** [comment]
@timsneath I think this is a totally reasonable request and makes sense for the plugin to support, but there's a problem with prioritization. Adding even simple features to the plugins is deceptively expensive since it's not just the cost of writing and merging one patch, but an addition to the ongoing maintenance burden of the plugin since each new feature adds to the plugins' complexity. If this becomes a widely requested feature I would prioritize it. But given our other incoming requests I unfortunately don't think this can be justified for the Flutter team to work on right now. However, I would be happy to land a well tested PR that implemented this feature.
