### ISSUE TITLE
flutter does not support GBK encoding.

### ISSUE THREAD

**Issue by monkingame** [flutter/flutter#45014]
## Steps to Reproduce
flutter does not support GBK encoding.
We wish gbk supporting coming soon.

1. put gbk encoding file in the assets dir.
the attachment file is here.
[gbk.txt](https://github.com/flutter/flutter/files/3853512/gbk.txt)
file content is:
```
# this file should be opened by encoding GBK or GB2312.
测试中文
如果有问题就报错
GBK及GB2312编码
加入标点符号，。测试
中英文ppp混杂-@abc测试
flutter能否支持GBK？
很多文件都在使用
```

2. load file content.
codes are here:
```
_readContentByString() async {
    final content = await rootBundle.loadString('assets/gbk.txt');
    print(content);
  }

  _readContentByBytes() async {
    final bytes = await rootBundle.load('assets/gbk.txt');
    final array = bytes.buffer.asUint8List();
    final str = String.fromCharCodes(array);
    print(str);
  }
```

3. Sample codes link here:
[sample project](https://gist.github.com/monkingame/271a7ce45b66c08bd930fa2922bfa4bf)
Note: gbk.txt must be in [assets] directory.

4. Run the project
If run _readContentByString,then exception occured:
Unhandled Exception: FormatException: Bad UTF-8 encoding 0xb2 (at offset 56)

If run _readContentByBytes,then file content shows:
`
flutter: # this file should be opened by encoding GBK or GB2312.
²âÊÔÖÐÎÄ
Èç¹ûÓÐÎÊÌâ¾Í±¨´í
GBK¼°GB2312±àÂë
¼ÓÈë±êµã·ûºÅ£¬¡£²âÊÔ
ÖÐÓ¢ÎÄppp»ìÔÓ-@abc²âÊÔ
flutterÄÜ·ñÖ§³ÖGBK£¿
ºÜ¶àÎÄ¼þ¶¼ÔÚÊ¹ÓÃ
`

**Target Platform:**
iOS
**Target OS version/browser:**
13.2
**Devices:**
Simulator or physics iphone

## Exception Logs
```
[VERBOSE-2:ui_dart_state.cc(148)] Unhandled Exception: FormatException: Bad UTF-8 encoding 0xb2 (at offset 56)
[38;5;244m#0      _Utf8Decoder.convert  (dart:convert/utf.dart:530:13)[39;49m
[38;5;244m#1      Utf8Decoder.convert  (dart:convert/utf.dart:327:13)[39;49m
[38;5;244m#2      Utf8Codec.decode  (dart:convert/utf.dart:59:56)[39;49m
[38;5;244m#3      AssetBundle.loadString[39;49m
<asynchronous suspension>
[38;5;244m#4      CachingAssetBundle.loadString.<anonymous closure>[39;49m
[38;5;244m#5      _LinkedHashMapMixin.putIfAbsent  (dart:collection-patch/compact_hash.dart:291:23)[39;49m
[38;5;244m#6      CachingAssetBundle.loadString[39;49m
[38;5;248m#7      MyApp._readContentByString[39;49m
<asynchronous suspension>
[38;5;244m#8      _InkResponseState._handleTap[39;49m
[38;5;244m#9      _InkResponseState.build.<anonymous closure>[39;49m
#10     GestureRecognizer<…>
```

## flutter analyze
```
No issues found! (ran in 2.1s)
```

## flutter doctor -v
```
No issues found!
```

**Comment by iapicca** [comment]
Hi @monkingame 
I'm quite sure there are already 3rd party pub repository that provide that functionality,
you might want to try searching [here](https://pub.dev/)
nevertheless it might be an improvement to dart's [crypto](https://pub.dev/packages/crypto)
Thank you for your contribution

**Comment by monkingame** [comment]
@iapicca  Thanks for the guide.
I found several 3rd party libs for GBK encoding.
But it had some bugs with special characters and cannot used in release version.
I wish gbk official support by flutter.
In China,there are so many many many old servers running with GBK encoding.
Now I  am developing  such an old server.
If GBK encoding is offical support, I think flutter user amount will improve.

**Comment by GaryQian** [comment]
cc @HansMuller @shihaohong Do you guys know what it would take to support this? Apparently, about 3.6% of chinese websites use GBK encoding.

**Comment by shihaohong** [comment]
@monkingame I filed a Dart issue (https://github.com/dart-lang/convert/issues/37), since it seems more like a feature request for Dart support for GBK. As for the issues with the third-party packages, have you tried filing issues to the library maintainers? What kind of bugs are you seeing with those packages?
