### ISSUE TITLE
Uncaught exception when running iOS app and screen is locked

### ISSUE THREAD

**Issue by christopherfujino** [flutter/flutter#45010]
## Logs

```
Thread 0 main thread CRASHED IOSDeviceNotFoundError: ideviceinfo could not find device:

ideviceinfo could not find device:
No device found with udid 8b45b19f8c4890c91869e3e20b4b492a004e0d13, is it plugged in?
. Try unlocking attached devices.

#0 IMobileDevice.getInfoForDevice (package:flutter_tools/src/ios/mac.dart:207:9)
<asynchronous suspension>
#1 IOSDevice.startApp (package:flutter_tools/src/ios/devices.dart:285:58)
<asynchronous suspension>
#2 FlutterDevice.runHot (package:flutter_tools/src/resident_runner.dart:416:54)
<asynchronous suspension>
#3 HotRunner.run (package:flutter_tools/src/run_hot.dart:266:39)
<asynchronous suspension>
#4 RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:499:37)
<asynchronous suspension>
#5 FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:570:18)
#6 _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:71:64)
#7 _rootRunUnary (dart:async/zone.dart:1132:38)
#8 _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#9 _FutureListener.handleValue (dart:async/future_impl.dart:137:18)
#10 Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:678:45)
#11 Future._propagateToListeners (dart:async/future_impl.dart:707:32)
#12 Future._completeWithValue (dart:async/future_impl.dart:522:5)
#13 _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:30:15)
#14 _completeOnAsyncReturn (dart:async-patch/async_patch.dart:288:13)
#15 RunCommand.usageValues (package:flutter_tools/src/commands/run.dart)
#16 _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:71:64)
#17 _rootRunUnary (dart:async/zone.dart:1132:38)
#18 _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#19 _FutureListener.handleValue (dart:async/future_impl.dart:137:18)
#20 Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:678:45)
#21 Future._propagateToListeners (dart:async/future_impl.dart:707:32)
#22 Future._completeWithValue (dart:async/future_impl.dart:522:5)
#23 _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:30:15)
#24 _completeOnAsyncReturn (dart:async-patch/async_patch.dart:288:13)
#25 IosProject.isSwift (package:flutter_tools/src/project.dart)
#26 _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:71:64)
#27 _rootRunUnary (dart:async/zone.dart:1132:38)
#28 _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#29 _FutureListener.handleValue (dart:async/future_impl.dart:137:18)
#30 Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:678:45)
#31 Future._propagateToListeners (dart:async/future_impl.dart:707:32)
#32 Future._completeWithValue (dart:async/future_impl.dart:522:5)
#33 _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:30:15)
#34 _completeOnAsyncReturn (dart:async-patch/async_patch.dart:288:13)
#35 IosProject.buildSettings (package:flutter_tools/src/project.dart)
#36 _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:71:64)
#37 _rootRunUnary (dart:async/zone.dart:1132:38)
#38 _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#39 _FutureListener.handleValue (dart:async/future_impl.dart:137:18)
#40 Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:678:45)
#41 Future._propagateToListeners (dart:async/future_impl.dart:707:32)
#42 Future._completeWithValue (dart:async/future_impl.dart:522:5)
#43 _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:30:15)
#44 _completeOnAsyncReturn (dart:async-patch/async_patch.dart:288:13)
#45 XcodeProjectInterpreter.getBuildSettings (package:flutter_tools/src/ios/xcodeproj.dart)
#46 _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:71:64)
#47 _rootRunUnary (dart:async/zone.dart:1132:38)
#48 _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#49 _FutureListener.handleValue (dart:async/future_impl.dart:137:18)
#50 Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:678:45)
#51 Future._propagateToListeners (dart:async/future_impl.dart:707:32)
#52 Future._completeWithValue (dart:async/future_impl.dart:522:5)
#53 _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:30:15)
#54 _completeOnAsyncReturn (dart:async-patch/async_patch.dart:288:13)
#55 _DefaultProcessUtils.run (package:flutter_tools/src/base/process.dart)
#56 _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:71:64)
#57 _rootRunUnary (dart:async/zone.dart:1132:38)
#58 _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#59 _FutureListener.handleValue (dart:async/future_impl.dart:137:18)
#60 Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:678:45)
#61 Future._propagateToListeners (dart:async/future_impl.dart:707:32)
#62 Future._completeWithValue (dart:async/future_impl.dart:522:5)
#63 Future.wait.<anonymous closure> (dart:async/future.dart:398:22)
#64 _rootRunUnary (dart:async/zone.dart:1132:38)
#65 _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#66 _FutureListener.handleValue (dart:async/future_impl.dart:137:18)
#67 Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:678:45)
#68 Future._propagateToListeners (dart:async/future_impl.dart:707:32)
#69 Future._complete (dart:async/future_impl.dart:512:7)
#70 _BufferingStreamSubscription.asFuture.<anonymous closure> (dart:async/stream_impl.dart:204:14)
#71 _rootRun (dart:async/zone.dart:1120:38)
#72 _CustomZone.run (dart:async/zone.dart:1021:19)
#73 _CustomZone.runGuarded (dart:async/zone.dart:923:7)
#74 _BufferingStreamSubscription._sendDone.sendDone (dart:async/stream_impl.dart:389:13)
#75 _BufferingStreamSubscription._sendDone (dart:async/stream_impl.dart:399:15)
#76 _BufferingStreamSubscription._close (dart:async/stream_impl.dart:283:7)
#77 _SinkTransformerStreamSubscription._close (dart:async/stream_transformers.dart:96:11)
#78 _EventSinkWrapper.close (dart:async/stream_transformers.dart:23:11)
#79 _StringAdapterSink.close (dart:convert/string_conversion.dart:249:11)
#80 _Utf8ConversionSink.close (dart:convert/string_conversion.dart:300:20)
#81 _ConverterStreamEventSink.close (dart:convert/chunked_conversion.dart:80:18)
#82 _SinkTransformerStreamSubscription._handleDone (dart:async/stream_transformers.dart:141:24)
#83 _rootRun (dart:async/zone.dart:1120:38)
#84 _CustomZone.run (dart:async/zone.dart:1021:19)
#85 _CustomZone.runGuarded (dart:async/zone.dart:923:7)
#86 _BufferingStreamSubscription._sendDone.sendDone (dart:async/stream_impl.dart:389:13)
#87 _BufferingStreamSubscription._sendDone (dart:async/stream_impl.dart:399:15)
#88 _BufferingStreamSubscription._close (dart:async/stream_impl.dart:283:7)
#89 _SyncStreamControllerDispatch._sendDone (dart:async/stream_controller.dart:772:19)
#90 _StreamController._closeUnchecked (dart:async/stream_controller.dart:629:7)
#91 _StreamController.close (dart:async/stream_controller.dart:622:5)
#92 _Socket._onData (dart:io-patch/socket_patch.dart:1836:21)
#93 _rootRunUnary (dart:async/zone.dart:1136:13)
#94 _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#95 _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
#96 _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#97 _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#98 _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:764:19)
#99 _StreamController._add (dart:async/stream_controller.dart:640:7)
#100 _StreamController.add (dart:async/stream_controller.dart:586:5)
#101 new _RawSocket.<anonymous closure> (dart:io-patch/socket_patch.dart:1384:35)
#102 _NativeSocket.issueReadEvent.issue (dart:io-patch/socket_patch.dart:890:18)
#103 _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#104 _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#105 _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:116:13)
#106 _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:173:5)
```

**Comment by christopherfujino** [comment]
Fixed by https://github.com/flutter/flutter/pull/45011
