### ISSUE TITLE
flutter run failed with "domain=NSOSStatusErrorDomain, code=-54" during xcrun simctl install, after updating to Xcode 11.2.1

### ISSUE THREAD

**Issue by ahmedmehanna** [flutter/flutter#45077]
I get a crash report when running my application on iOS Simulator only
This happened after updating Xcode today to version 11.2.1

## Terminal Logs
```
Launching lib/main.dart on iPhone 11 Pro Max in debug mode...
Running Xcode build...                                                  
 ├─Assembling Flutter resources...                           7.0s
 └─Compiling, linking and signing...                         4.4s
Xcode build done.                                           13.3s

Sending crash report to Google.
Crash report sent (report ID: 352fd5eb36ef704a)
Oops; flutter has exited unexpectedly.
Crash report written to /Users/ahmedmehanna/development/projects/gnib/flutter_04.log;
please let us know at https://github.com/flutter/flutter/issues
```
## Crash report

Flutter crash report; please file at https://github.com/flutter/flutter/issues.

 **command**

`flutter run -d 1BAE79D2-D4F8-4FA6-9DCF-3ADBEF610C46`

**exception**

ProcessException: ProcessException: Process "/usr/bin/xcrun" exited abnormally:
An error was encountered processing the command (domain=NSOSStatusErrorDomain, code=-54):
The operation couldn’t be completed. (OSStatus error -54.)
  Command: /usr/bin/xcrun simctl install 1BAE79D2-D4F8-4FA6-9DCF-3ADBEF610C46 /Users/ahmedmehanna/development/projects/gnib/build/ios/iphonesimulator/Runner.app

```
#0      runCheckedAsync (package:flutter_tools/src/base/process.dart:259:7)
<asynchronous suspension>
#1      SimControl.install (package:flutter_tools/src/ios/simulators.dart:145:16)
#2      IOSSimulator._setupUpdatedApplicationBundle (package:flutter_tools/src/ios/simulators.dart:437:31)
<asynchronous suspension>
#3      IOSSimulator.startApp (package:flutter_tools/src/ios/simulators.dart:339:15)
<asynchronous suspension>
#4      FlutterDevice.runHot (package:flutter_tools/src/resident_runner.dart:378:54)
#5      _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:71:64)
#6      _rootRunUnary (dart:async/zone.dart:1132:38)
#7      _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#8      _FutureListener.handleValue (dart:async/future_impl.dart:137:18)
#9      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:678:45)
#10     Future._propagateToListeners (dart:async/future_impl.dart:707:32)
#11     Future._completeWithValue (dart:async/future_impl.dart:522:5)
#12     Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:552:7)
#13     _rootRun (dart:async/zone.dart:1124:13)
#14     _CustomZone.run (dart:async/zone.dart:1021:19)
#15     _CustomZone.runGuarded (dart:async/zone.dart:923:7)
#16     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:963:23)
#17     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#18     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#19     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:116:13)
#20     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:173:5)
```

**flutter doctor**

```
[32m[✓][39m Flutter (Channel stable, v1.9.1+hotfix.6, on Mac OS X 10.15.1 19B88, locale en-IE)
    [32m•[39m Flutter version 1.9.1+hotfix.6 at /Users/ahmedmehanna/development/tools/flutter
    [32m•[39m Framework revision 68587a0916 (9 weeks ago), 2019-09-13 19:46:58 -0700
    [32m•[39m Engine revision b863200c37
    [32m•[39m Dart version 2.5.0

[32m[✓][39m Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    [32m•[39m Android SDK at /Users/ahmedmehanna/Library/Android/sdk
    [32m•[39m Android NDK location not configured (optional; useful for native profiling support)
    [32m•[39m Platform android-28, build-tools 28.0.3
    [32m•[39m Java binary at: /Applications/Android Studio 2.app/Contents/jre/jdk/Contents/Home/bin/java
    [32m•[39m Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)
    [32m•[39m All Android licenses accepted.

[32m[✓][39m Xcode - develop for iOS and macOS (Xcode 11.2.1)
    [32m•[39m Xcode at /Applications/Xcode.app/Contents/Developer
    [32m•[39m Xcode 11.2.1, Build version 11B500
    [32m•[39m CocoaPods version 1.8.4

[32m[✓][39m Android Studio (version 3.3)
    [32m•[39m Android Studio at /Applications/Android Studio 2.app/Contents
    [32m•[39m Flutter plugin version 32.0.1
    [32m•[39m Dart plugin version 182.5124
    [32m•[39m Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)

[32m[✓][39m IntelliJ IDEA Community Edition (version 2019.2.3)
    [32m•[39m IntelliJ at /Applications/IntelliJ IDEA CE.app
    [32m•[39m Flutter plugin version 41.1.3
    [32m•[39m Dart plugin version 192.7402

[32m[✓][39m VS Code (version 1.40.1)
    [32m•[39m VS Code at /Applications/Visual Studio Code.app/Contents
    [32m•[39m Flutter extension version 3.6.0

[32m[✓][39m Connected device (2 available)
    [32m•[39m Android SDK built for x86 • emulator-5554                        • android-x86 • Android 10 (API 29) (emulator)
    [32m•[39m iPhone 11 Pro Max         • 1BAE79D2-D4F8-4FA6-9DCF-3ADBEF610C46 • ios         • com.apple.CoreSimulator.SimRuntime.iOS-13-2 (simulator)

[32m•[39m No issues found!
```

**Comment by janmoppel** [comment]
Hello @ahmedmehanna !

Thank you for posting an issue.
This issue also looks like a duplicate of the one reported here: #44813. 
If you try to follow the steps written in the thread I attached, do you get the same error?

**Comment by ahmedmehanna** [comment]
Hi @janmoppel I opened the project with Xcode, the project built successfully but couldn't run
I got the following error 
```
Details

The operation couldn’t be completed. (OSStatus error -54.)
Domain: NSOSStatusErrorDomain
Code: -54
User Info: {
    NSDebugDescription = installForLaunchServices;
    "_LSFunction" = "-[_LSInstaller installApplication:atURL:withOptions:installType:reply:]";
    "_LSLine" = 717;
}
```
I tried to run old flutter project, I am sure it's working perfect, I got the same error
I can't run the project via iOS Simlulator, it is running only via android emulator

## Note
I got this error after updating Xcode to v11.2.1

**Comment by jmagman** [comment]
Can you create a new project in Xcode without any Flutter bits and run it on the simulator?  
If not, you are hitting a Xcode or Xcode installation issue, and there's not much Flutter can really do...

**Comment by ahmedmehanna** [comment]
Hi @jmagman 
I have created a new project by Xcode and run it on Simulator successfully.
After that, I run the flutter app again on the Simulator and it runs successfully finally.
I don't have any idea how the issue is fixed.

So I think you can close the issue. 
Thanks
