### ISSUE TITLE
Gradle task assembleRelease failed with exit code 1

### ISSUE THREAD

**Issue by nimeacuerdo** [flutter/flutter#45078]
Hi,

I'm not being able to build a release apk or bundle of my app.

## Steps to Reproduce

`flutter build apk --release -v` causes the problem whereas `flutter build apk --debug -v` works fine

## Logs

```
...
[   +1 ms] Running Gradle task 'assembleRelease'...
[   +3 ms] executing: [/Users/david/dev/flutter-ladder-client/android/] /Users/david/dev/flutter-ladder-client/android/gradlew -Pverbose=true -Ptarget=lib/main.dart
-Ptrack-widget-creation=false -Ptarget-platform=android-arm,android-arm64 assembleRelease
[+1037 ms] > Configure project :app
[        ] WARNING: API 'variant.getMergeAssets()' is obsolete and has been replaced with 'variant.getMergeAssetsProvider()'.
[        ] It will be removed at the end of 2019.
[        ] For more information, see https://d.android.com/r/tools/task-configuration-avoidance.
[        ] To determine what is calling variant.getMergeAssets(), use -Pandroid.debug.obsoleteApi=true on the command line to display more information.
[   +1 ms] WARNING: API 'variantOutput.getProcessResources()' is obsolete and has been replaced with 'variantOutput.getProcessResourcesProvider()'.
[        ] It will be removed at the end of 2019.
[        ] For more information, see https://d.android.com/r/tools/task-configuration-avoidance.
[        ] To determine what is calling variantOutput.getProcessResources(), use -Pandroid.debug.obsoleteApi=true on the command line to display more information.
[ +706 ms] Running Gradle task 'assembleRelease'... (completed in 1.8s)
[   +6 ms] "flutter apk" took 7,884ms.
Gradle task assembleRelease failed with exit code 1

#0      throwToolExit (package:flutter_tools/src/base/common.dart:28:3)
#1      _buildGradleProjectV2 (package:flutter_tools/src/android/gradle.dart:751:5)
<asynchronous suspension>
#2      buildGradleProject (package:flutter_tools/src/android/gradle.dart:494:14)
<asynchronous suspension>
#3      buildApk (package:flutter_tools/src/android/apk.dart:34:9)
<asynchronous suspension>
#4      BuildApkCommand.runCommand (package:flutter_tools/src/commands/build_apk.dart:79:11)
<asynchronous suspension>
#5      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:490:18)
#6      _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:71:64)
#7      _rootRunUnary (dart:async/zone.dart:1132:38)
#8      _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#9      _FutureListener.handleValue (dart:async/future_impl.dart:137:18)
#10     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:678:45)
#11     Future._propagateToListeners (dart:async/future_impl.dart:707:32)
#12     Future._completeWithValue (dart:async/future_impl.dart:522:5)
#13     Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:552:7)
#14     _rootRun (dart:async/zone.dart:1124:13)
#15     _CustomZone.run (dart:async/zone.dart:1021:19)
#16     _CustomZone.runGuarded (dart:async/zone.dart:923:7)
#17     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:963:23)
#18     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#19     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#20     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:116:13)
#21     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:173:5)
```

If I try to build a bundle if fails too.

```
[        ] > Task :app:configureReleaseDependencies UP-TO-DATE
[  +96 ms] > Task :app:packageReleaseBundle UP-TO-DATE
[        ] > Task :app:validateSigningRelease UP-TO-DATE
[        ] > Task :app:signingConfigWriterRelease UP-TO-DATE
[  +95 ms] > Task :app:signReleaseBundle UP-TO-DATE
[        ] > Task :app:bundleRelease UP-TO-DATE
[        ] 77 actionable tasks: 5 executed, 72 up-to-date
[ +381 ms] Running Gradle task 'bundleRelease'... (completed in 74.0s)
[   +4 ms] "flutter appbundle" took 80,461ms.
Gradle build failed to produce an Android bundle package.

#0      throwToolExit (package:flutter_tools/src/base/common.dart:28:3)
#1      _buildGradleProjectV2 (package:flutter_tools/src/android/gradle.dart:780:7)
#2      _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:71:64)
#3      _rootRunUnary (dart:async/zone.dart:1132:38)
#4      _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#5      _FutureListener.handleValue (dart:async/future_impl.dart:137:18)
#6      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:678:45)
#7      Future._propagateToListeners (dart:async/future_impl.dart:707:32)
#8      Future._completeWithValue (dart:async/future_impl.dart:522:5)
#9      _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:30:15)
#10     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:288:13)
#11     runCommandAndStreamOutput (package:flutter_tools/src/base/process.dart)
#12     _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:71:64)
#13     _rootRunUnary (dart:async/zone.dart:1132:38)
#14     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#15     _FutureListener.handleValue (dart:async/future_impl.dart:137:18)
#16     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:678:45)
#17     Future._propagateToListeners (dart:async/future_impl.dart:707:32)
#18     Future._completeWithValue (dart:async/future_impl.dart:522:5)
#19     Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:552:7)
#20     _rootRun (dart:async/zone.dart:1124:13)
#21     _CustomZone.run (dart:async/zone.dart:1021:19)
#22     _CustomZone.runGuarded (dart:async/zone.dart:923:7)
#23     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:963:23)
#24     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#25     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#26     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:116:13)
#27     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:173:5)
```

## Flutter doctor
`flutter analyze` reports that everything is fine and `doctor` too.

```
[✓] Flutter (Channel stable, v1.9.1+hotfix.6, on Mac OS X 10.15 19A602, locale en-ES)
    • Flutter version 1.9.1+hotfix.6 at /Users/david/dev/flutter
    • Framework revision 68587a0916 (9 weeks ago), 2019-09-13 19:46:58 -0700
    • Engine revision b863200c37
    • Dart version 2.5.0


[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/david/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.0, Build version 11A420a
    • CocoaPods version 1.8.4

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 41.1.2
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] VS Code (version 1.39.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.6.0

[!] Connected device
    ! No devices available

! Doctor found issues in 1 category.
```

## Some other info:

* Dependencies
````
dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  firebase_core: ^0.4.0+9
  cloud_firestore: ^0.12.9+5
  intl: ^0.16.0
  jiffy: ^2.1.1
```

```
buildscript {
    ext.kotlin_version = '1.3.50'
    repositories {
        google()
        jcenter()
    }

    dependencies {
        classpath 'com.android.tools.build:gradle:3.5.2'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
        classpath 'com.google.gms:google-services:4.3.3'
    }
}
```

**Comment by nimeacuerdo** [comment]
More on this...

I got this working after reverting several sdk updates I had done:

Kotlin from 1.3.50 to 1.2.71
Gradle build plugin from 3.5.2 to 3.2.1
google-services from 4.3.3 to 4.3.2
Gradle from 5.4.1 to 4.10.2

Sooo... these are the possible culprits :)

**Comment by julianbraasch** [comment]
No need to go that low on the Gradle versions. I currently have v5.1.1 with Android Gradle plugin v3.4.2 running, those are the most recent correct versions for me.

**Comment by ginuxone** [comment]
@nimeacuerdo I'm facing the same problem since i added the keystore to my app . It was working before but while migrating to androidX i updated all my sdks as you've done! 
I'll downgrade now and let you know.

**Comment by nimeacuerdo** [comment]
@ginuxone Looks like related to that, yup.

Starting from my previous (working fine), setup and changing only to gradle 5.1.1 and plugin 3.4.2 breaks with this message:

```
           > Configure project :app
           WARNING: API 'variant.getJavaCompile()' is obsolete and has been replaced with 'variant.getJavaCompileProvider()'.
           It will be removed at the end of 2019.
           For more information, see https://d.android.com/r/tools/task-configuration-avoidance.
           To determine what is calling variant.getJavaCompile(), use -Pandroid.debug.obsoleteApi=true on the command line to display more information.
           WARNING: API 'variant.getMergeAssets()' is obsolete and has been replaced with 'variant.getMergeAssetsProvider()'.
           It will be removed at the end of 2019.
           For more information, see https://d.android.com/r/tools/task-configuration-avoidance.
           To determine what is calling variant.getMergeAssets(), use -Pandroid.debug.obsoleteApi=true on the command line to display more information.
           WARNING: API 'variantOutput.getProcessResources()' is obsolete and has been replaced with 'variantOutput.getProcessResourcesProvider()'.
           It will be removed at the end of 2019.
           For more information, see https://d.android.com/r/tools/task-configuration-avoidance.
           To determine what is calling variantOutput.getProcessResources(), use -Pandroid.debug.obsoleteApi=true on the command line to display more information.
                    *********************************************************
           WARNING: This version of firebase_core will break your Android build if it or its dependencies aren't compatible with AndroidX.
                    See https://goo.gl/CP92wY for more information on the problem and how to fix it.
                    This warning prints for all Android build failures. The real root cause of the error may be unrelated.
                    *********************************************************
```

**Comment by blasten** [comment]
I wasn't able to repro this error. @nimeacuerdo is the app migrated to AndroidX? The guide is available on https://flutter.dev/docs/development/androidx-migration

**Comment by ginuxone** [comment]
I was able to "Fix" this error on my case just by adding 
`-ignorewarnings` 
to my proguard file.
And that's it, everything runned smooth

**Comment by nimeacuerdo** [comment]
I ended up re-recreating the project with `--androidx` and copying dart files there.

Now release builds are working with the following setup:

`distributionUrl=https\://services.gradle.org/distributions/gradle-5.4.1-all.zip`


```
    ext.kotlin_version = '1.3.61'
        classpath 'com.android.tools.build:gradle:3.5.2'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
        classpath 'com.google.gms:google-services:4.3.3'
        classpath 'io.fabric.tools:gradle:1.31.2'
```

```
    implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk7:$kotlin_version"
    implementation 'com.google.firebase:firebase-analytics:17.2.1'
    implementation 'com.crashlytics.sdk.android:crashlytics:2.10.1'

    testImplementation 'junit:junit:4.12'
    androidTestImplementation 'androidx.test:runner:1.2.0'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.2.0'
```

```
  firebase_core: ^0.4.0+9
  cloud_firestore: ^0.12.9+5
  intl: ^0.16.0
  jiffy: ^2.1.1
```

**Comment by iapicca** [comment]
possibly related to 
https://github.com/flutter/flutter/issues/46771
https://github.com/flutter/flutter/issues/46686

**Comment by Hixie** [comment]
To resolve this we will need precise steps to reproduce, starting with a Flutter version to start from, followed by a "flutter create" command line, followed by all the changes and command lines that are needed to actually reproduce the issue with today's master build. Without that level of detail it's really not something we can actually resolve because we're not sure how to reproduce it.

**Comment by nimeacuerdo** [comment]
Makes sense, @Hixie, and I already did that when I posted the issue.

Given I haven't run into this problem after https://github.com/flutter/flutter/issues/45078#issuecomment-562546743 I'm gonna close this for now.
