### ISSUE TITLE
Crash: This Flutter engine instance is already running an application

### ISSUE THREAD

**Issue by askarsyzdykov** [flutter/flutter#45095]
## Steps to Reproduce

1. Create Flutter module
2. Build aar
3. Add aar as dependency to target project and run it
4. Also add `implementation 'androidx.lifecycle:lifecycle-extensions:2.1.0'`

Without `lifecycle-extensions` works perfect

**Target Platform:** Android
**Target OS version:** 9.0
**Devices:** Xiaomi A1

## Logs

```
2019-11-18 16:45:47.153 10016-10016/kz.team.myapplication E/AndroidRuntime: FATAL EXCEPTION: main
    Process: kz.team.myapplication, PID: 10016
    java.lang.RuntimeException: Unable to start activity ComponentInfo{kz.team.myapplication/my.app.IdActivity}: java.lang.RuntimeException: Failed to call observer method
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2925)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3060)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1818)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6762)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
     Caused by: java.lang.RuntimeException: Failed to call observer method
        at androidx.lifecycle.ClassesInfoCache$MethodReference.invokeCallback(ClassesInfoCache.java:226)
        at androidx.lifecycle.ClassesInfoCache$CallbackInfo.invokeMethodsForEvent(ClassesInfoCache.java:194)
        at androidx.lifecycle.ClassesInfoCache$CallbackInfo.invokeCallbacks(ClassesInfoCache.java:185)
        at androidx.lifecycle.ReflectiveGenericLifecycleObserver.onStateChanged(ReflectiveGenericLifecycleObserver.java:36)
        at androidx.lifecycle.LifecycleRegistry$ObserverWithState.dispatchEvent(LifecycleRegistry.java:361)
        at androidx.lifecycle.LifecycleRegistry.forwardPass(LifecycleRegistry.java:300)
        at androidx.lifecycle.LifecycleRegistry.sync(LifecycleRegistry.java:339)
        at androidx.lifecycle.LifecycleRegistry.moveToState(LifecycleRegistry.java:145)
        at androidx.lifecycle.LifecycleRegistry.handleLifecycleEvent(LifecycleRegistry.java:131)
        at androidx.lifecycle.ReportFragment.dispatch(ReportFragment.java:123)
        at androidx.lifecycle.ReportFragment.onActivityCreated(ReportFragment.java:76)
        at android.app.Fragment.performActivityCreated(Fragment.java:2531)
        at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1318)
        at android.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1576)
        at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1637)
        at android.app.FragmentManagerImpl.dispatchMoveToState(FragmentManager.java:3046)
        at android.app.FragmentManagerImpl.dispatchActivityCreated(FragmentManager.java:2998)
        at android.app.FragmentController.dispatchActivityCreated(FragmentController.java:182)
        at android.app.Activity.performCreate(Activity.java:7143)
        at android.app.Activity.performCreate(Activity.java:7127)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1272)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2905)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3060) 
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78) 
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1818) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:193) 
        at android.app.ActivityThread.main(ActivityThread.java:6762) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858) 
     Caused by: java.lang.AssertionError: This Flutter engine instance is already running an application
        at io.flutter.view.FlutterNativeView.runFromBundle(FlutterNativeView.java:103)
        at io.flutter.view.FlutterView.runFromBundle(FlutterView.java:646)
        at io.flutter.facade.Flutter$2.onCreate(Flutter.java:97)
        at java.lang.reflect.Method.invoke(Native Method)
        at androidx.lifecycle.ClassesInfoCache$MethodReference.invokeCallback(ClassesInfoCache.java:216)
        at androidx.lifecycle.ClassesInfoCache$CallbackInfo.invokeMethodsForEvent(ClassesInfoCache.java:194) 
        at androidx.lifecycle.ClassesInfoCache$CallbackInfo.invokeCallbacks(ClassesInfoCache.java:185) 
        at androidx.lifecycle.ReflectiveGenericLifecycleObserver.onStateChanged(ReflectiveGenericLifecycleObserver.java:36) 
        at androidx.lifecycle.LifecycleRegistry$ObserverWithState.dispatchEvent(LifecycleRegistry.java:361) 
        at androidx.lifecycle.LifecycleRegistry.forwardPass(LifecycleRegistry.java:300) 
        at androidx.lifecycle.LifecycleRegistry.sync(LifecycleRegistry.java:339) 
        at androidx.lifecycle.LifecycleRegistry.moveToState(LifecycleRegistry.java:145) 
        at androidx.lifecycle.LifecycleRegistry.handleLifecycleEvent(LifecycleRegistry.java:131) 
        at androidx.lifecycle.ReportFragment.dispatch(ReportFragment.java:123) 
        at androidx.lifecycle.ReportFragment.onActivityCreated(ReportFragment.java:76) 
        at android.app.Fragment.performActivityCreated(Fragment.java:2531) 
        at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1318) 
        at android.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1576) 
        at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1637) 
        at android.app.FragmentManagerImpl.dispatchMoveToState(FragmentManager.java:3046) 
        at android.app.FragmentManagerImpl.dispatchActivityCreated(FragmentManager.java:2998) 
        at android.app.FragmentController.dispatchActivityCreated(FragmentController.java:182) 
        at android.app.Activity.performCreate(Activity.java:7143) 
        at android.app.Activity.performCreate(Activity.java:7127) 
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1272) 
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2905) 
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3060) 
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78) 
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1818) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:193) 
        at android.app.ActivityThread.main(ActivityThread.java:6762) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858) 

```

```
$ flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel unknown, v1.10.3, on Mac OS X 10.14.6 18G95, locale en-RU)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 10.2)
[✓] Android Studio (version 3.5)
[!] IntelliJ IDEA Community Edition (version 2018.3.5)
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
[✓] VS Code (version 1.39.2)
[✓] Connected device (1 available)
```

**Comment by askarsyzdykov** [comment]
I've created the repo with example https://github.com/askarsyzdykov/flutter_crash_lifecycle

**Comment by tvolkert** [comment]
FYI @xster

**Comment by xster** [comment]
Please see https://github.com/flutter/flutter/wiki/Adding-Flutter-to-Android for our updated guide for adding to existing app on Android with new APIs

See https://flutter.dev/go/android-project-migration for a step by step migration guide from your existing project. Please let us know if you run into issues with the migration. 

We'd also love to hear more about the premise. It seems like the intent to run multiple Flutter instances per app is intentional? Can you describe your use case a bit? Also the use case for lifecycle-extensions if you could.

**Comment by askarsyzdykov** [comment]
@xster I'll try.

>Can you describe your use case a bit? Also the use case for lifecycle-extensions if you could.

I have a Flutter project, that used as SDK for my clients. 
Dependency flow:
My Flutter module <- My Android native lib (aka SDK) <- Client's app that uses lifecycle-extensions.

- My Android native lib is common Android module that has FlutterActivity and starts Flutter module
- The clients add my Android native lib as gradle dependency.
If a client app contains `lifecycle-extensions` then my native lib is crashed in runtime with `This Flutter engine instance is already running an application`

**Comment by askarsyzdykov** [comment]
@xster 

Flutter version is upgraded:
```
flutter --version
Flutter 1.12.4 • channel unknown • unknown source
Framework • revision 2461c75600 (2 days ago) • 2019-11-18 12:26:51 -0500
Engine • revision 5fb7eb753b
Tools • Dart 2.7.0
```

I created PR to compare changes: https://github.com/askarsyzdykov/flutter_crash_lifecycle/pull/1/files. Now the app crashes with following logs:

```
2019-11-20 16:21:12.598 20346-20346/kz.test.myapp E/kz.test.myapp: No implementation found for long io.flutter.embedding.engine.FlutterJNI.nativeAttach(io.flutter.embedding.engine.FlutterJNI, boolean) (tried Java_io_flutter_embedding_engine_FlutterJNI_nativeAttach and Java_io_flutter_embedding_engine_FlutterJNI_nativeAttach__Lio_flutter_embedding_engine_FlutterJNI_2Z)
2019-11-20 16:21:12.598 20346-20346/kz.test.myapp D/AndroidRuntime: Shutting down VM
2019-11-20 16:21:12.617 20346-20346/kz.test.myapp E/AndroidRuntime: FATAL EXCEPTION: main
    Process: kz.test.myapp, PID: 20346
    java.lang.UnsatisfiedLinkError: No implementation found for long io.flutter.embedding.engine.FlutterJNI.nativeAttach(io.flutter.embedding.engine.FlutterJNI, boolean) (tried Java_io_flutter_embedding_engine_FlutterJNI_nativeAttach and Java_io_flutter_embedding_engine_FlutterJNI_nativeAttach__Lio_flutter_embedding_engine_FlutterJNI_2Z)
        at io.flutter.embedding.engine.FlutterJNI.nativeAttach(Native Method)
        at io.flutter.embedding.engine.FlutterJNI.attachToNative(FlutterJNI.java:196)
        at io.flutter.embedding.engine.FlutterEngine.attachToJni(FlutterEngine.java:164)
        at io.flutter.embedding.engine.FlutterEngine.<init>(FlutterEngine.java:133)
        at kz.test.myapp.MainActivity.onCreate(MainActivity.kt:17)
        at android.app.Activity.performCreate(Activity.java:7136)
        at android.app.Activity.performCreate(Activity.java:7127)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1272)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2905)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3060)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1818)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6762)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
2019-11-20 16:21:12.629 20346-20346/kz.test.myapp I/Process: Sending signal. PID: 20346 SIG: 9
```

**Comment by askarsyzdykov** [comment]
I changed Flutter version to 1.12.3

The app works incorrect:
```
E/flutter: [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: MissingPluginException(No implementation found for method availableCameras on channel plugins.flutter.io/camera)
    #0      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:319:7)
    <asynchronous suspension>
    #1      MethodChannel.invokeListMethod (package:flutter/src/services/platform_channel.dart:335:40)
    #2      availableCameras (package:camera/camera.dart:80:10)
    #3      Camera.prepare (package:did/utils/camera.dart:8:46)
    #4      DeviceFeatures.prepareDevice (package:did/device_features.dart:20:18)
    #5      InitializationService.init (package:did/services/initializationService.dart:22:26)
    #6      _AsyncAwaitCompleter.start (dart:async-patch/async_patch.dart:45:6)
    #7      InitializationService.init (package:did/services/initializationService.dart:18:7)
    #8      SplashModel._init (package:did/screens/splash/splash_model.dart:20:34)
    #9      _AsyncAwaitCompleter.start (dart:async-patch/async_patch.dart:45:6)
    #10     SplashModel._init (package:did/screens/splash/splash_model.dart:19:8)
    #11     new SplashModel (package:did/screens/splash/splash_model.dart:16:5)
    #12     _SplashScreenState.initState (package:did/screens/splash/splash_screen.dart:17:5)
    #13     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4090:58)
    #14     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3936:5)
    #15     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3109:14)
    #16     Element.updateChild (package:flutter/src/widgets/framework.dart:2903:12)
    #17     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5170:14)
    #18     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3109:14)
    #19     Element.updateChild (package:flutter/src/widgets/framework.dart:2903:12)
    #20     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3978:16)
    #21     Element.rebuild (package:flutter/src/widgets/framework.dart:3755:5)
    #22     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3941:5)
    #23     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3936:5)
    #24     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3109:14)
    #25     Element.updateChild (package:flutter/src/widgets/framework.dart:2903:12)
    #26     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5170:14)
    #27     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3109:14)
    #28     Element.updateChild (package:flutter/src/widgets/framework.dart:2903:12)
    #29     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5170:14)
    #30     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3109:14)
    #31     Element.updateChild (package:flutter/src/widgets/framework.dart:2903:12)
    #32     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3978:16)
    #33     Element.rebuild (package:flutter/src/widgets/framework.dart:3755:5)
    #34     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3941:5)
    #35     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4116:11)
    #36     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3936:5)
    #37     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3109:14)
    #38     MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5276:32)
    #39     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3109:14)
    #40     Element.updateChild (package:flutter/src/widgets/framework.dart:2903:12)
    #41     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3978:16)
    #42     Element.rebuild (package:flutter/src/widgets/framework.dart:3755:5)
    #43     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3941:5)
    #44     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4116:11)
    #45     ComponentElement.mount (package:flutter/src/widget
```

I've tried apply this code https://github.com/flutter/flutter/wiki/Experimental:-Use-old-plugins-with-new-embedding. But it is not working

![image](https://user-images.githubusercontent.com/3222305/69239851-5cb43c00-0bc5-11ea-976e-bc4279b2d8c7.png)

**Comment by blasten** [comment]
As far as I can tell, this issue doesn't involve the flutter tool.

**Comment by matthew-carroll** [comment]
@askarsyzdykov would you mind posting an example project to GitHub using the v2 Android embedding that demonstrates the problem?

**Comment by askarsyzdykov** [comment]
@matthew-carroll i have no problem after migration, i'll close the issue. Thank you all!
