### ISSUE TITLE
Structured logging sometimes doesn't contain sufficient information

### ISSUE THREAD

**Issue by maks** [flutter/flutter#45123]
## Steps to Reproduce

I really like structured errors, but recently I got an error message on a red-screen-of-death, with structured errors turned-on, it looked like this on the debug console:
```

════════ Exception caught by widgets library ═══════════════════════════════════
'package:flutter/src/widgets/framework.dart': Failed assertion: line 1779 pos 12: '_elements.contains(element)': is not true.
The relevant error-causing widget was
    MaterialApp 
lib/[REDACTED].dart:130
════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by widgets library ═══════════════════════════════════
'package:flutter/src/widgets/framework.dart': Failed assertion: line 1779 pos 12: '_elements.contains(element)': is not true.
The relevant error-causing widget was
    MaterialApp 
lib/[REDACTED]dart:130
════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by widgets library ═══════════════════════════════════
The getter 'userGestureInProgress' was called on null.
Receiver: null
Tried calling: userGestureInProgress
The relevant error-causing widget was
    MaterialApp 
lib/[REDACTED].dart:130
════════════════════════════════════════════════════════════════════════════════
```
It was not very helpful in tracking down the problem compared to the output without structured errors. This log very clearly pointed to the culprit of my forgetting to dispose a animation controller:

```
I/flutter (10841): ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
I/flutter (10841): The following assertion was thrown while finalizing the widget tree:
I/flutter (10841): _ProfileSwitchState#04b1c(ticker active but muted) was disposed with an active Ticker.
I/flutter (10841): _ProfileSwitchState created a Ticker via its SingleTickerProviderStateMixin, but at the time
I/flutter (10841): dispose() was called on the mixin, that Ticker was still active. The Ticker must be disposed before
I/flutter (10841): calling super.dispose().
I/flutter (10841): Tickers used by AnimationControllers should be disposed by calling dispose() on the
I/flutter (10841): AnimationController itself. Otherwise, the ticker will leak.
I/flutter (10841): The offending ticker was:
I/flutter (10841):   Ticker(created by _ProfileSwitchState#04b1c(lifecycle state: created))
I/flutter (10841):   The stack trace when the Ticker was actually created was:
I/flutter (10841):   #0      new Ticker.<anonymous closure> 
package:flutter/…/scheduler/ticker.dart:66
I/flutter (10841):   #1      new Ticker 
package:flutter/…/scheduler/ticker.dart:68
I/flutter (10841):   #2      SingleTickerProviderStateMixin.createTicker
I/flutter (10841):   (package:flutter/src/widgets/ticker_provider.dart:95:15)
I/flutter (10841):   #3      new AnimationController 
package:flutter/…/animation/animation_controller.dart:245
I/flutter (10841):   #4      _ProfileSwitchState.initState
I/flutter (10841):   (package:[REDACTED].dart:42:18)
I/flutter (10841):   #5      StatefulElement._firstBuild 
package:flutter/…/widgets/framework.dart:4085
I/flutter (10841):   #6      ComponentElement.mount 
package:flutter/…/widgets/framework.dart:3936
I/flutter (10841):   #7      Element.inflateWidget 
package:flutter/…/widgets/framework.dart:3109
I/flutter (10841):   #8      Element.updateChild 
package:flutter/…/widgets/framework.dart:2903
I/flutter (10841):   #9      ComponentElement.performRebuild 
package:flutter/…/widgets/framework.dart:3978
I/flutter (10841):   #10     Element.rebuild 
package:flutter/…/widgets/framework.dart:3755
I/flutter (10841):   #11     BuildOwner.buildScope 
package:flutter/…/widgets/framework.dart:2347
I/flutter (10841):   #12     WidgetsBinding.drawFrame 
package:flutter/…/widgets/binding.dart:773
I/flutter (10841):   #13     RendererBinding._handlePersistentFrameCallback
I/flutter (10841):   (package:flutter/src/rendering/binding.dart:283:5)
I/flutter (10841):   #14     SchedulerBinding._invokeFrameCallback 
package:flutter/…/scheduler/binding.dart:1100
I/flutter (10841):   #15     SchedulerBinding.handleDrawFrame 
package:flutter/…/scheduler/binding.dart:1039
I/flutter (10841):   #16     SchedulerBinding._handleDrawFrame 
package:flutter/…/scheduler/binding.dart:955
I/flutter (10841):   #20     _invoke  (dart:ui/hooks.dart:259:10)
I/flutter (10841):   #21     _drawFrame  (dart:ui/hooks.dart:217:3)
I/flutter (10841):   (elided 3 frames from package dart:async)
I/flutter (10841):
I/flutter (10841): When the exception was thrown, this was the stack:
I/flutter (10841): #0      SingleTickerProviderStateMixin.dispose.<anonymous closure> 
package:flutter/…/widgets/ticker_provider.dart:108
I/flutter (10841): #1      SingleTickerProviderStateMixin.dispose 
package:flutter/…/widgets/ticker_provider.dart:122
I/flutter (10841): #2      StatefulElement.unmount 
package:flutter/…/widgets/framework.dart:4165
I/flutter (10841): #3      _InactiveElements._unmount 
package:flutter/…/widgets/framework.dart:1741
I/flutter (10841): #4      _InactiveElements._unmount.<anonymous closure> 
package:flutter/…/widgets/framework.dart:1739
I/flutter (10841): #5      ComponentElement.visitChildren 
package:flutter/…/widgets/framework.dart:4007
I/flutter (10841): #6      _InactiveElements._unmount 
package:flutter/…/widgets/framework.dart:1737
I/flutter (10841): #7      _InactiveElements._unmount.<anonymous closure> 
package:flutter/…/widgets/framework.dart:1739
I/flutter (10841): #8      MultiChildRenderObjectElement.visitChildren 
package:flutter/…/widgets/framework.dart:5254
I/flutter (10841): #9      _InactiveElements._unmount 
package:flutter/…/widgets/framework.dart:1737
I/flutter (10841): #10     _InactiveElements._unmount.<anonymous closure> 
package:flutter/…/widgets/framework.dart:1739
I/flutter (10841): #11     SingleChildRenderObjectElement.visitChildren 
package:flutter/…/widgets/framework.dart:5153
I/flutter (10841): #12     _InactiveElements._unmount 
package:flutter/…/widgets/framework.dart:1737
I/flutter (10841): #13     _InactiveElements._unmount.<anonymous closure> 
package:flutter/…/widgets/framework.dart:1739
I/flutter (10841): #14     SingleChildRenderObjectElement.visitChildren 
package:flutter/…/widgets/framework.dart:5153
I/flutter (10841): #15     _InactiveElements._unmount 
package:flutter/…/widgets/framework.dart:1737
I/flutter (10841): #16     _InactiveElements._unmount.<anonymous closure> 
package:flutter/…/widgets/framework.dart:1739
I/flutter (10841): #17     SingleChildRenderObjectElement.visitChildren 
package:flutter/…/widgets/framework.dart:5153
I/flutter (10841): #18     _InactiveElements._unmount 
package:flutter/…/widgets/framework.dart:1737
I/flutter (10841): #19     _InactiveElements._unmount.<anonymous closure> 
package:flutter/…/widgets/framework.dart:1739
I/flutter (10841): #20     MultiChildRenderObjectElement.visitChildren 
package:flutter/…/widgets/framework.dart:5254
I/flutter (10841): #21     _InactiveElements._unmount 
package:flutter/…/widgets/framework.dart:1737
I/flutter (10841): #22     _InactiveElements._unmount.<anonymous closure> 
package:flutter/…/widgets/framework.dart:1739
I/flutter (10841): #23     ComponentElement.visitChildren 
package:flutter/…/widgets/framework.dart:4007
I/flutter (10841): #24     _InactiveElements._unmount 
package:flutter/…/widgets/framework.dart:1737
I/flutter (10841): #25     ListIterable.forEach  (dart:_internal/iterable.dart:39:13)
I/flutter (10841): #26     _InactiveElements._unmountAll 
package:flutter/…/widgets/framework.dart:1750
I/flutter (10841): #27     BuildOwner.finalizeTree.<anonymous closure> 
package:flutter/…/widgets/framework.dart:2434
I/flutter (10841): #28     BuildOwner.lockState 
package:flutter/…/widgets/framework.dart:2265
I/flutter (10841): #29     BuildOwner.finalizeTree 
package:flutter/…/widgets/framework.dart:2433
I/flutter (10841): #30     WidgetsBinding.drawFrame 
package:flutter/…/widgets/binding.dart:775
I/flutter (10841): #31     RendererBinding._handlePersistentFrameCallback 
package:flutter/…/rendering/binding.dart:283
I/flutter (10841): #32     SchedulerBinding._invokeFrameCallback 
package:flutter/…/scheduler/binding.dart:1100
I/flutter (10841): #33     SchedulerBinding.handleDrawFrame 
package:flutter/…/scheduler/binding.dart:1039
I/flutter (10841): #34     SchedulerBinding._handleDrawFrame 
package:flutter/…/scheduler/binding.dart:955
I/flutter (10841): #38     _invoke  (dart:ui/hooks.dart:259:10)
I/flutter (10841): #39     _drawFrame  (dart:ui/hooks.dart:217:3)
I/flutter (10841): (elided 3 frames from package dart:async)
I/flutter (10841): ════════════════════════════════════════════════════════════════════════════════════════════════════
```

## Flutter doctor
I'm on dev from about a week ago:
```
flutter doctor -v
[✓] Flutter (Channel dev, v1.10.16, on Linux, locale en_AU.UTF-8)
    • Flutter version 1.10.16 at /home/maks/apps/flutter
    • Framework revision 798e4272a2 (12 days ago), 2019-11-06 21:04:17 -0500
    • Engine revision 34a40cfbfd
    • Dart version 2.7.0
```

**Comment by VladyslavBondarenko** [comment]
Hi @maks 
I see there's an open issue addressing the case you described.
Please follow up on https://github.com/flutter/flutter/issues/40260
I'm closing the current one as duplicate.
If you disagree please write in the comments
and I will reopen it.
Thank you
