### ISSUE TITLE
Video player plugin not working when i run the video multiple times this gives the mentioned log

### ISSUE THREAD

**Issue by amitted** [flutter/flutter#45159]
<details>
  <summary>logs</summary>

```
I/ExoPlayerImpl( 6272): Init c6f7c47 [ExoPlayerLib/2.9.6] [shamu, Nexus 6, motorola, 25]
I/ExoPlayerImpl( 6272): Init fc62a12 [ExoPlayerLib/2.9.6] [shamu, Nexus 6, motorola, 25]
I/OMXClient( 6272): MuxOMX ctor
W/ACodec  ( 6272): Allocating component 'OMX.qcom.video.decoder.avc' failed, try next one.
E/ACodec  ( 6272): Unable to instantiate codec 'OMX.qcom.video.decoder.avc' with err 0xfffffff4.
E/ACodec  ( 6272): signalError(omxError 0xfffffff4, internalError -12)
E/MediaCodec( 6272): Codec reported err 0xfffffff4, actionCode 0, while in state 1
I/OMXClient( 6272): MuxOMX ctor
W/ACodec  ( 6272): Allocating component 'OMX.qcom.video.decoder.avc' failed, try next one.
E/ACodec  ( 6272): Unable to instantiate codec 'OMX.qcom.video.decoder.avc' with err 0xfffffff4.
E/ACodec  ( 6272): signalError(omxError 0xfffffff4, internalError -12)
E/MediaCodec( 6272): Codec reported err 0xfffffff4, actionCode 0, while in state 1
W/MediaCodec-JNI( 6272): try to release MediaCodec from JMediaCodec::~JMediaCodec()...
W/MediaCodec-JNI( 6272): try to release MediaCodec from JMediaCodec::~JMediaCodec()...
W/MediaCodec-JNI( 6272): done releasing MediaCodec from JMediaCodec::~JMediaCodec().
W/MediaCodec-JNI( 6272): done releasing MediaCodec from JMediaCodec::~JMediaCodec().
W/MediaCodecRenderer( 6272): Failed to initialize decoder: OMX.qcom.video.decoder.avc
W/MediaCodecRenderer( 6272): android.media.MediaCodec$CodecException: Failed to initialize OMX.qcom.video.decoder.avc, error 0xfffffff4
W/MediaCodecRenderer( 6272): 	at android.media.MediaCodec.native_setup(Native Method)
W/MediaCodecRenderer( 6272): 	at android.media.MediaCodec.<init>(MediaCodec.java:1776)
W/MediaCodecRenderer( 6272): 	at android.media.MediaCodec.createByCodecName(MediaCodec.java:1757)
W/MediaCodecRenderer( 6272): 	at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.initCodec(MediaCodecRenderer.java:802)
W/MediaCodecRenderer( 6272): 	at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.initCodecWithFallback(MediaCodecRenderer.java:745)
W/MediaCodecRenderer( 6272): 	at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.maybeInitCodec(MediaCodecRenderer.java:474)
W/MediaCodecRenderer( 6272): 	at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.reinitializeCodec(MediaCodecRenderer.java:1261)
W/MediaCodecRenderer( 6272): 	at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.onInputFormatChanged(MediaCodecRenderer.java:1111)
W/MediaCodecRenderer( 6272): 	at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.onInputFormatChanged(MediaCodecVideoRenderer.java:552)
W/MediaCodecRenderer( 6272): 	at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:647)
W/MediaCodecRenderer( 6272): 	at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:529)
W/MediaCodecRenderer( 6272): 	at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:300)
W/MediaCodecRenderer( 6272): 	at android.os.Handler.dispatchMessage(Handler.java:98)
W/MediaCodecRenderer( 6272): 	at android.os.Looper.loop(Looper.java:154)
W/MediaCodecRenderer( 6272): 	at android.os.HandlerThread.run(HandlerThread.java:61)
W/MediaCodecRenderer( 6272): Failed to initialize decoder: OMX.qcom.video.decoder.avc
W/MediaCodecRenderer( 6272): android.media.MediaCodec$CodecException: Failed to initialize OMX.qcom.video.decoder.avc, error 0xfffffff4
W/MediaCodecRenderer( 6272): 	at android.media.MediaCodec.native_setup(Native Method)
W/MediaCodecRenderer( 6272): 	at android.media.MediaCodec.<init>(MediaCodec.java:1776)
W/MediaCodecRenderer( 6272): 	at android.media.MediaCodec.createByCodecName(MediaCodec.java:1757)
W/MediaCodecRenderer( 6272): 	at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.initCodec(MediaCodecRenderer.java:802)
W/MediaCodecRenderer( 6272): 	at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.initCodecWithFallback(MediaCodecRenderer.java:745)
W/MediaCodecRenderer( 6272): 	at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.maybeInitCodec(MediaCodecRenderer.java:474)
W/MediaCodecRenderer( 6272): 	at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.reinitializeCodec(MediaCodecRenderer.java:1261)
W/MediaCodecRenderer( 6272): 	at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.onInputFormatChanged(MediaCodecRenderer.java:1111)
W/MediaCodecRenderer( 6272): 	at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.onInputFormatChanged(MediaCodecVideoRenderer.java:552)
W/MediaCodecRenderer( 6272): 	at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:647)
W/MediaCodecRenderer( 6272): 	at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:529)
W/MediaCodecRenderer( 6272): 	at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:300)
W/MediaCodecRenderer( 6272): 	at android.os.Handler.dispatchMessage(Handler.java:98)
W/MediaCodecRenderer( 6272): 	at android.os.Looper.loop(Looper.java:154)
W/MediaCodecRenderer( 6272): 	at android.os.HandlerThread.run(HandlerThread.java:61)
E/ExoPlayerImplInternal( 6272): Playback error.
E/ExoPlayerImplInternal( 6272): com.google.android.exoplayer2.ExoPlaybackException: com.google.android.exoplayer2.mediacodec.MediaCodecRenderer$DecoderInitializationException: Decoder init failed: OMX.qcom.video.decoder.avc, Format(1, null, null, video/avc, null, -1, null, [1920, 1080, -1.0], [-1, -1])
E/ExoPlayerImplInternal( 6272): 	at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.maybeInitCodec(MediaCodecRenderer.java:479)
E/ExoPlayerImplInternal( 6272): 	at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.reinitializeCodec(MediaCodecRenderer.java:1261)
E/ExoPlayerImplInternal( 6272): 	at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.onInputFormatChanged(MediaCodecRenderer.java:1111)
E/ExoPlayerImplInternal( 6272): 	at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.onInputFormatChanged(MediaCodecVideoRenderer.java:552)
E/ExoPlayerImplInternal( 6272): 	at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:647)
E/ExoPlayerImplInternal( 6272): 	at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:529)
E/ExoPlayerImplInternal( 6272): 	at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:300)
E/ExoPlayerImplInternal( 6272): 	at android.os.Handler.dispatchMessage(Handler.java:98)
E/ExoPlayerImplInternal( 6272): 	at android.os.Looper.loop(Looper.java:154)
E/ExoPlayerImplInternal( 6272): 	at android.os.HandlerThread.run(HandlerThread.java:61)
E/ExoPlayerImplInternal( 6272): Caused by: com.google.android.exoplayer2.mediacodec.MediaCodecRenderer$DecoderInitializationException: Decoder init failed: OMX.qcom.video.decoder.avc, Format(1, null, null, video/avc, null, -1, null, [1920, 1080, -1.0], [-1, -1])
E/ExoPlayerImplInternal( 6272): 	at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.initCodecWithFallback(MediaCodecRenderer.java:753)
E/ExoPlayerImplInternal( 6272): 	at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.maybeInitCodec(MediaCodecRenderer.java:474)
E/ExoPlayerImplInternal( 6272): 	... 9 more
E/ExoPlayerImplInternal( 6272): Caused by: android.media.MediaCodec$CodecException: Failed to initialize OMX.qcom.video.decoder.avc, error 0xfffffff4
E/ExoPlayerImplInternal( 6272): 	at android.media.MediaCodec.native_setup(Native Method)
E/ExoPlayerImplInternal( 6272): 	at android.media.MediaCodec.<init>(MediaCodec.java:1776)
E/ExoPlayerImplInternal( 6272): 	at android.media.MediaCodec.createByCodecName(MediaCodec.java:1757)
E/ExoPlayerImplInternal( 6272): 	at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.initCodec(MediaCodecRenderer.java:802)
E/ExoPlayerImplInternal( 6272): 	at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.initCodecWithFallback(MediaCodecRenderer.java:745)
E/ExoPlayerImplInternal( 6272): 	... 10 more
E/ExoPlayerImplInternal( 6272): Playback error.
E/ExoPlayerImplInternal( 6272): com.google.android.exoplayer2.ExoPlaybackException: com.google.android.exoplayer2.mediacodec.MediaCodecRenderer$DecoderInitializationException: Decoder init failed: OMX.qcom.video.decoder.avc, Format(1, null, null, video/avc, null, -1, null, [1920, 1080, -1.0], [-1, -1])
E/ExoPlayerImplInternal( 6272): 	at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.maybeInitCodec(MediaCodecRenderer.java:479)
E/ExoPlayerImplInternal( 6272): 	at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.reinitializeCodec(MediaCodecRenderer.java:1261)
E/ExoPlayerImplInternal( 6272): 	at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.onInputFormatChanged(MediaCodecRenderer.java:1111)
E/ExoPlayerImplInternal( 6272): 	at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.onInputFormatChanged(MediaCodecVideoRenderer.java:552)
E/ExoPlayerImplInternal( 6272): 	at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:647)
E/ExoPlayerImplInternal( 6272): 	at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:529)
E/ExoPlayerImplInternal( 6272): 	at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:300)
E/ExoPlayerImplInternal( 6272): 	at android.os.Handler.dispatchMessage(Handler.java:98)
E/ExoPlayerImplInternal( 6272): 	at android.os.Looper.loop(Looper.java:154)
E/ExoPlayerImplInternal( 6272): 	at android.os.HandlerThread.run(HandlerThread.java:61)
E/ExoPlayerImplInternal( 6272): Caused by: com.google.android.exoplayer2.mediacodec.MediaCodecRenderer$DecoderInitializationException: Decoder init failed: OMX.qcom.video.decoder.avc, Format(1, null, null, video/avc, null, -1, null, [1920, 1080, -1.0], [-1, -1])
E/ExoPlayerImplInternal( 6272): 	at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.initCodecWithFallback(MediaCodecRenderer.java:753)
E/ExoPlayerImplInternal( 6272): 	at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.maybeInitCodec(MediaCodecRenderer.java:474)
E/ExoPlayerImplInternal( 6272): 	... 9 more
E/ExoPlayerImplInternal( 6272): Caused by: android.media.MediaCodec$CodecException: Failed to initialize OMX.qcom.video.decoder.avc, error 0xfffffff4
E/ExoPlayerImplInternal( 6272): 	at android.media.MediaCodec.native_setup(Native Method)
E/ExoPlayerImplInternal( 6272): 	at android.media.MediaCodec.<init>(MediaCodec.java:1776)
E/ExoPlayerImplInternal( 6272): 	at android.media.MediaCodec.createByCodecName(MediaCodec.java:1757)
E/ExoPlayerImplInternal( 6272): 	at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.initCodec(MediaCodecRenderer.java:802)
E/ExoPlayerImplInternal( 6272): 	at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.initCodecWithFallback(MediaCodecRenderer.java:745)
E/ExoPlayerImplInternal( 6272): 	... 10 more
I/ExoPlayerImpl( 6272): Init c75de5b [ExoPlayerLib/2.9.6] [shamu, Nexus 6, motorola, 25]
I/ExoPlayerImpl( 6272): Init 8143236 [ExoPlayerLib/2.9.6] [shamu, Nexus 6, motorola, 25]
I/OMXClient( 6272): MuxOMX ctor
W/ACodec  ( 6272): Allocating component 'OMX.qcom.video.decoder.avc' failed, try next one.
E/ACodec  ( 6272): Unable to instantiate codec 'OMX.qcom.video.decoder.avc' with err 0xfffffff4.
E/ACodec  ( 6272): signalError(omxError 0xfffffff4, internalError -12)
E/MediaCodec( 6272): Codec reported err 0xfffffff4, actionCode 0, while in state 1
I/flutter ( 6272): {status: SUCCESS, message: Feed Info status found succesfully., data: {isLiked: 1, isFollowed: 0}}
I/OMXClient( 6272): MuxOMX ctor
W/ACodec  ( 6272): Allocating component 'OMX.qcom.video.decoder.avc' failed, try next one.
E/ACodec  ( 6272): Unable to instantiate codec 'OMX.qcom.video.decoder.avc' with err 0xfffffff4.
E/ACodec  ( 6272): signalError(omxError 0xfffffff4, internalError -12)
E/MediaCodec( 6272): Codec reported err 0xfffffff4, actionCode 0, while in state 1
W/MediaCodec-JNI( 6272): try to release MediaCodec from JMediaCodec::~JMediaCodec()...
W/MediaCodec-JNI( 6272): done releasing MediaCodec from JMediaCodec::~JMediaCodec().
W/MediaCodecRenderer( 6272): Failed to initialize decoder: OMX.qcom.video.decoder.avc
W/MediaCodecRenderer( 6272): android.media.MediaCodec$CodecException: Failed to initialize OMX.qcom.video.decoder.avc, error 0xfffffff4
W/MediaCodecRenderer( 6272): 	at android.media.MediaCodec.native_setup(Native Method)
W/MediaCodecRenderer( 6272): 	at android.media.MediaCodec.<init>(MediaCodec.java:1776)
W/MediaCodecRenderer( 6272): 	at android.media.MediaCodec.createByCodecName(MediaCodec.java:1757)
W/MediaCodecRenderer( 6272): 	at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.initCodec(MediaCodecRenderer.java:802)
W/MediaCodecRenderer( 6272): 	at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.initCodecWithFallback(MediaCodecRenderer.java:745)
W/MediaCodecRenderer( 6272): 	at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.maybeInitCodec(MediaCodecRenderer.java:474)
W/MediaCodecRenderer( 6272): 	at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.reinitializeCodec(MediaCodecRenderer.java:1261)
W/MediaCodecRenderer( 6272): 	at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.onInputFormatChanged(MediaCodecRenderer.java:1111)
W/MediaCodecRenderer( 6272): 	at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.onInputFormatChanged(MediaCodecVideoRenderer.java:552)
W/MediaCodecRenderer( 6272): 	at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:647)
W/MediaCodecRenderer( 6272): 	at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:529)
W/MediaCodecRenderer( 6272): 	at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:300)
W/MediaCodecRenderer( 6272): 	at android.os.Handler.dispatchMessage(Handler.java:98)
W/MediaCodecRenderer( 6272): 	at android.os.Looper.loop(Looper.java:154)
W/MediaCodecRenderer( 6272): 	at android.os.HandlerThread.run(HandlerThread.java:61)
E/ExoPlayerImplInternal( 6272): Playback error.
E/ExoPlayerImplInternal( 6272): com.google.android.exoplayer2.ExoPlaybackException: com.google.android.exoplayer2.mediacodec.MediaCodecRenderer$DecoderInitializationException: Decoder init failed: OMX.qcom.video.decoder.avc, Format(1, null, null, video/avc, null, -1, null, [1920, 1080, -1.0], [-1, -1])
E/ExoPlayerImplInternal( 6272): 	at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.maybeInitCodec(MediaCodecRenderer.java:479)
E/ExoPlayerImplInternal( 6272): 	at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.reinitializeCodec(MediaCodecRenderer.java:1261)
E/ExoPlayerImplInternal( 6272): 	at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.onInputFormatChanged(MediaCodecRenderer.java:1111)
E/ExoPlayerImplInternal( 6272): 	at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.onInputFormatChanged(MediaCodecVideoRenderer.java:552)
E/ExoPlayerImplInternal( 6272): 	at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:647)
E/ExoPlayerImplInternal( 6272): 	at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:529)
E/ExoPlayerImplInternal( 6272): 	at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:300)
E/ExoPlayerImplInternal( 6272): 	at android.os.Handler.dispatchMessage(Handler.java:98)
E/ExoPlayerImplInternal( 6272): 	at android.os.Looper.loop(Looper.java:154)
E/ExoPlayerImplInternal( 6272): 	at android.os.HandlerThread.run(HandlerThread.java:61)
E/ExoPlayerImplInternal( 6272): Caused by: com.google.android.exoplayer2.mediacodec.MediaCodecRenderer$DecoderInitializationException: Decoder init failed: OMX.qcom.video.decoder.avc, Format(1, null, null, video/avc, null, -1, null, [1920, 1080, -1.0], [-1, -1])
E/ExoPlayerImplInternal( 6272): 	at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.initCodecWithFallback(MediaCodecRenderer.java:753)
E/ExoPlayerImplInternal( 6272): 	at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.maybeInitCodec(MediaCodecRenderer.java:474)
E/ExoPlayerImplInternal( 6272): 	... 9 more
E/ExoPlayerImplInternal( 6272): Caused by: android.media.MediaCodec$CodecException: Failed to initialize OMX.qcom.video.decoder.avc, error 0xfffffff4
E/ExoPlayerImplInternal( 6272): 	at android.media.MediaCodec.native_setup(Native Method)
E/ExoPlayerImplInternal( 6272): 	at android.media.MediaCodec.<init>(MediaCodec.java:1776)
E/ExoPlayerImplInternal( 6272): 	at android.media.MediaCodec.createByCodecName(MediaCodec.java:1757)
E/ExoPlayerImplInternal( 6272): 	at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.initCodec(MediaCodecRenderer.java:802)
E/ExoPlayerImplInternal( 6272): 	at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.initCodecWithFallback(MediaCodecRenderer.java:745)
E/ExoPlayerImplInternal( 6272): 	... 10 more
W/MediaCodec-JNI( 6272): try to release MediaCodec from JMediaCodec::~JMediaCodec()...
W/MediaCodec-JNI( 6272): done releasing MediaCodec from JMediaCodec::~JMediaCodec().
W/MediaCodecRenderer( 6272): Failed to initialize decoder: OMX.qcom.video.decoder.avc
W/MediaCodecRenderer( 6272): android.media.MediaCodec$CodecException: Failed to initialize OMX.qcom.video.decoder.avc, error 0xfffffff4
W/MediaCodecRenderer( 6272): 	at android.media.MediaCodec.native_setup(Native Method)
W/MediaCodecRenderer( 6272): 	at android.media.MediaCodec.<init>(MediaCodec.java:1776)
W/MediaCodecRenderer( 6272): 	at android.media.MediaCodec.createByCodecName(MediaCodec.java:1757)
W/MediaCodecRenderer( 6272): 	at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.initCodec(MediaCodecRenderer.java:802)
W/MediaCodecRenderer( 6272): 	at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.initCodecWithFallback(MediaCodecRenderer.java:745)
W/MediaCodecRenderer( 6272): 	at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.maybeInitCodec(MediaCodecRenderer.java:474)
W/MediaCodecRenderer( 6272): 	at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.reinitializeCodec(MediaCodecRenderer.java:1261)
W/MediaCodecRenderer( 6272): 	at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.onInputFormatChanged(MediaCodecRenderer.java:1111)
W/MediaCodecRenderer( 6272): 	at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.onInputFormatChanged(MediaCodecVideoRenderer.java:552)
W/MediaCodecRenderer( 6272): 	at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:647)
W/MediaCodecRenderer( 6272): 	at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:529)
W/MediaCodecRenderer( 6272): 	at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:300)
W/MediaCodecRenderer( 6272): 	at android.os.Handler.dispatchMessage(Handler.java:98)
W/MediaCodecRenderer( 6272): 	at android.os.Looper.loop(Looper.java:154)
W/MediaCodecRenderer( 6272): 	at android.os.HandlerThread.run(HandlerThread.java:61)
E/ExoPlayerImplInternal( 6272): Playback error.
E/ExoPlayerImplInternal( 6272): com.google.android.exoplayer2.ExoPlaybackException: com.google.android.exoplayer2.mediacodec.MediaCodecRenderer$DecoderInitializationException: Decoder init failed: OMX.qcom.video.decoder.avc, Format(1, null, null, video/avc, null, -1, null, [1920, 1080, -1.0], [-1, -1])
E/ExoPlayerImplInternal( 6272): 	at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.maybeInitCodec(MediaCodecRenderer.java:479)
E/ExoPlayerImplInternal( 6272): 	at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.reinitializeCodec(MediaCodecRenderer.java:1261)
E/ExoPlayerImplInternal( 6272): 	at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.onInputFormatChanged(MediaCodecRenderer.java:1111)
E/ExoPlayerImplInternal( 6272): 	at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.onInputFormatChanged(MediaCodecVideoRenderer.java:552)
E/ExoPlayerImplInternal( 6272): 	at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:647)
E/ExoPlayerImplInternal( 6272): 	at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:529)
E/ExoPlayerImplInternal( 6272): 	at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:300)
E/ExoPlayerImplInternal( 6272): 	at android.os.Handler.dispatchMessage(Handler.java:98)
E/ExoPlayerImplInternal( 6272): 	at android.os.Looper.loop(Looper.java:154)
E/ExoPlayerImplInternal( 6272): 	at android.os.HandlerThread.run(HandlerThread.java:61)
E/ExoPlayerImplInternal( 6272): Caused by: com.google.android.exoplayer2.mediacodec.MediaCodecRenderer$DecoderInitializationException: Decoder init failed: OMX.qcom.video.decoder.avc, Format(1, null, null, video/avc, null, -1, null, [1920, 1080, -1.0], [-1, -1])
E/ExoPlayerImplInternal( 6272): 	at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.initCodecWithFallback(MediaCodecRenderer.java:753)
E/ExoPlayerImplInternal( 6272): 	at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.maybeInitCodec(MediaCodecRenderer.java:474)
E/ExoPlayerImplInternal( 6272): 	... 9 more
E/ExoPlayerImplInternal( 6272): Caused by: android.media.MediaCodec$CodecException: Failed to initialize OMX.qcom.video.decoder.avc, error 0xfffffff4
E/ExoPlayerImplInternal( 6272): 	at android.media.MediaCodec.native_setup(Native Method)
E/ExoPlayerImplInternal( 6272): 	at android.media.MediaCodec.<init>(MediaCodec.java:1776)
E/ExoPlayerImplInternal( 6272): 	at android.media.MediaCodec.createByCodecName(MediaCodec.java:1757)
E/ExoPlayerImplInternal( 6272): 	at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.initCodec(MediaCodecRenderer.java:802)
E/ExoPlayerImplInternal( 6272): 	at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.initCodecWithFallback(MediaCodecRenderer.java:745)
E/ExoPlayerImplInternal( 6272): 	... 10 more

```

</details>

**Comment by amitted** [comment]
![2019-11-19](https://user-images.githubusercontent.com/43950908/69145794-789bdd00-0af4-11ea-9854-9eb0be727c57.png)

**Comment by iapicca** [comment]
Hi @amitted 
could you please provide your updated  `flutter doctor -v`
and a minimal code sample to reproduce the problem?
Thank you

**Comment by iapicca** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact descriptions what happens, logs and the output of 'flutter doctor -v'  please.
All system setups can be slightly different so its always better to open new issues and reference related issues.
