### ISSUE TITLE
CupertinoNavigationBar Exception caught by gesture  Failed assertion: line 635 pos 14: 'manifest.fromHero != newManifest.fromHero': is not true.

### ISSUE THREAD

**Issue by designofadecade** [flutter/flutter#45169]
## Steps to Reproduce

I'm only able to replicate this issues on device.

Try quickly switching between the second and first screen. If the timing is right you will get flutter ```'manifest.fromHero != newManifest.fromHero': is not true```, the back button will stop working. You have to restart the app.

This happens in debug mode and release version. 

I thought my testing might have been unrealistic, but users that never used an iPhone where able to  replicate the issue by casually navigating around the app,

For now set transitionBetweenRoutes on CupertinoNavigationBar to false. Turns off the hero animations and problem goes away.

## Example

```import 'package:flutter/cupertino.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return CupertinoApp(
      title: 'Flutter Demo',
      home: FirstPage(),
    );
  }
}

// First Page
class FirstPage extends StatefulWidget {
  @override
  _FirstPageState createState() => _FirstPageState();
}

class _FirstPageState extends State<FirstPage> {
  @override
  Widget build(BuildContext context) {
    return CupertinoPageScaffold(
      navigationBar: CupertinoNavigationBar(
        middle: Text('First Page'),
      ),
      resizeToAvoidBottomInset: true,
      child: Column(
        children: <Widget>[
          Expanded(
            child: Container(
              alignment: Alignment.center,
              child: CupertinoButton(
                padding: EdgeInsets.fromLTRB(0, 0, 20, 3),
                onPressed: () {
                  Navigator.push(
                      context,
                      CupertinoPageRoute(
                        builder: (BuildContext context) => SecondPage(),
                      ));
                },
                child: Text(
                  'Go To Second Page',
                  style: TextStyle(fontSize: 30),
                ),
              ),
            ),
          ),
        ],
      ),
    );
  }
}

// Second Page
class SecondPage extends StatefulWidget {
  @override
  _SecondPageState createState() => _SecondPageState();
}

class _SecondPageState extends State<SecondPage> {
  @override
  Widget build(BuildContext context) {
    return CupertinoPageScaffold(
      navigationBar: CupertinoNavigationBar(
        leading: CupertinoButton(
          padding: EdgeInsets.fromLTRB(0, 0, 20, 3),
          onPressed: () {
            Navigator.pop(context);
          },
          child: Icon(
            CupertinoIcons.left_chevron,
            color: CupertinoColors.black,
            size: 34,
          ),
        ),
        middle: Text('Second Page'),
      ),
      resizeToAvoidBottomInset: true,
      child: Container(),
    );
  }
}
```

**Target Platform:** IOS
**Target OS version/browser:** 12.4.3
**Devices:** iPhone 11, iPhone 5

## Logs

```
[+50806 ms] flutter: ══╡ EXCEPTION CAUGHT BY GESTURE ╞═══════════════════════════════════════════════════════════════════
[   +1 ms] flutter: The following assertion was thrown while handling a gesture:
[   +1 ms] flutter: 'package:flutter/src/widgets/heroes.dart': Failed assertion: line 635 pos 14: 'manifest.fromHero !=
[        ] flutter: newManifest.fromHero': is not true.
[        ] flutter:
[   +1 ms] flutter: Either the assertion indicates an error in the framework itself, or we should provide substantially
[        ] flutter: more information in this error message to help you determine and fix the underlying cause.
[        ] flutter: In either case, please report this assertion by filing a bug on GitHub:
[        ] flutter:   https://github.com/flutter/flutter/issues/new?template=BUG.md
[        ] flutter:
[   +1 ms] flutter: When the exception was thrown, this was the stack:
[   +1 ms] flutter: #2      _HeroFlight.divert (package:flutter/src/widgets/heroes.dart:635:14)
[   +1 ms] flutter: #3      HeroController._startHeroTransition (package:flutter/src/widgets/heroes.dart:825:25)
[   +1 ms] flutter: #4      HeroController._maybeStartHeroTransition (package:flutter/src/widgets/heroes.dart:762:9)
[        ] flutter: #5      HeroController.didStartUserGesture (package:flutter/src/widgets/heroes.dart:728:5)
[   +1 ms] flutter: #6      NavigatorState.didStartUserGesture (package:flutter/src/widgets/navigator.dart:2202:18)
[   +1 ms] flutter: #7      new _CupertinoBackGestureController (package:flutter/src/cupertino/route.dart:593:15)
[        ] flutter: #8      CupertinoPageRoute._startPopGesture (package:flutter/src/cupertino/route.dart:273:12)
[   +1 ms] flutter: #9      CupertinoPageRoute.buildPageTransitions.<anonymous closure> (package:flutter/src/cupertino/route.dart:317:36)
[   +1 ms] flutter: #10     _CupertinoBackGestureDetectorState._handleDragStart (package:flutter/src/cupertino/route.dart:505:37)
[   +1 ms] flutter: #11     DragGestureRecognizer._checkStart.<anonymous closure> (package:flutter/src/gestures/monodrag.dart:370:45)
[   +1 ms] flutter: #12     GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:182:24)
[   +1 ms] flutter: #13     DragGestureRecognizer._checkStart (package:flutter/src/gestures/monodrag.dart:370:7)
[        ] flutter: #14     DragGestureRecognizer.acceptGesture (package:flutter/src/gestures/monodrag.dart:304:7)
[        ] flutter: #15     GestureArenaManager._resolveByDefault (package:flutter/src/gestures/arena.dart:250:25)
[   +1 ms] flutter: #16     GestureArenaManager._tryToResolveArena.<anonymous closure> (package:flutter/src/gestures/arena.dart:231:31)
[        ] flutter: (elided 12 frames from class _AssertionError and package dart:async)
[        ] flutter:
[        ] flutter: Handler: "onStart"
[        ] flutter: Recognizer:
[        ] flutter:   HorizontalDragGestureRecognizer#893ed
[   +3 ms] flutter: ════════════════════════════════════════════════════════════════════════════════════════════════════
[  +11 ms] flutter: Another exception was thrown: 'package:flutter/src/cupertino/route.dart': Failed assertion: line 510 pos 12: '_backGestureController != null': is not true.

```

```
Analyzing cupertinonavigationbardebug...                                
No issues found! (ran in 2.0s)

```

```
[✓] Flutter (Channel stable, v1.9.1+hotfix.6, on Mac OS X 10.15.1 19B88, locale en-CA)
    • Flutter version 1.9.1+hotfix.6 at /Users/studio/development/flutter
    • Framework revision 68587a0916 (10 weeks ago), 2019-09-13 19:46:58 -0700
    • Engine revision b863200c37
    • Dart version 2.5.0

 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/studio/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.2.1, Build version 11B53
    • CocoaPods version 1.8.4

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 41.0.2
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] VS Code (version 1.39.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.6.0

[✓] Connected device (1 available)
    • iPhone • 9bd21186950cb446e04517b193ea81fe9137a55d • ios • iOS 12.3.1

• No issues found!

```

**Comment by iapicca** [comment]
Hi @designofadecade 
thank you for your contribution

**Comment by LongCatIsLooong** [comment]
I managed to get the same stacktrace on stable once but wasn't able to reproduce the bug at all on master. @designofadecade could you try switching to master and see if the bug is still reproducible?

**Comment by VladyslavBondarenko** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.
Could everyone who still has this problem please file a new issue with the exact descriptions what happens, logs and the output of 'flutter doctor -v'  please.
All system setups can be slightly different so its always better to open new issues and reference related issues.
