### ISSUE TITLE
[web] To what extent is instantiateImageCodec supported?

### ISSUE THREAD

**Issue by creativecreatorormaybenot** [flutter/flutter#45190]
I am having a hard time debugging what parts of my app do not work correctly in Flutter web because errors are rarely logged to the terminal but sometimes to the Chrome console.

The Chrome console reports [this all the time](https://gist.github.com/creativecreatorormaybenot/77830bf175172ea6a4149928cd56f2d3). The short version of this 20k lines stack trace is "EncodingError: The source image cannot be decoded."  
Additionally, all canvases that should show images encoded using the image codec are blank. Hence, I was wondering if image codecs are supported.

**Comment by yjbanov** [comment]
What image format are you using? Does it work if you use it in a plain HTML page in an `<img>` tag?

**Comment by creativecreatorormaybenot** [comment]
@yjbanov I am passing the pixels to [`decodeImageFromPixels`](https://api.flutter.dev/flutter/dart-ui/decodeImageFromPixels.html) and it works on mobile. That would be `rgba8888`.

**Comment by HedgeHao** [comment]
Having the same problem. I wrote a function to generate random pixel value and use `decodeImageFromPixels()` to have the Image instance then set to RawImage. Works fine on desktop and mobile but not on web (chrome).

Here's my code

```
class MyImage extends StatefulWidget {
  MyImageState createState() => MyImageState();
}

class MyImageState extends State<MyImage> {
  ui.Image img;

  void makeImage() {
  int len = 256 * 256 * 4;
  final pixels = Uint8List(len);
  for (int i = 0; i < pixels.length; i++) {
    pixels[i] = Random().nextInt(255);
  }
  ui.decodeImageFromPixels(pixels, 256, 256, ui.PixelFormat.rgba8888, setImg);
}

  void setImg(ui.Image data) {
    setState(() {
      this.img = data;
    });
  }

  @override
  void initState() {
    img = null;
    super.initState();
  }

  @override
  Widget build(BuildContext context) {
    return Column(
      children: <Widget>[
        RawImage(image: this.img),
        RaisedButton(
          child: Text("Generate"),
          onPressed: () {
            makeImage();
          },
        )
      ],
    );
  }
}
```

flutter doctor
```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel master, v1.13.3-pre.23, on Mac OS X 10.15.1 19B88, locale en-TW)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 10.3)
[✓] Chrome - develop for the web
[✓] Android Studio (version 3.1)
[✓] VS Code (version 1.41.0)
[✓] Connected device (3 available)

• No issues found!
```

**Comment by D-Jeremie** [comment]
Any updates on this ?

**Comment by deakjahn** [comment]
Please, change the labels. This isn't a documentation issue. It's a bug all right.

**Comment by deakjahn** [comment]
@yjbanov Started to experiment with workarounds.

    final codec = await ui.instantiateImageCodec(pixels, targetWidth: width, targetHeight: height);
    print(codec.toString());
    final frame = await codec.getNextFrame();
    completer.complete(frame.image);

The print says it's a [HtmlBlobCodec.](https://github.com/flutter/engine/blob/master/lib/web_ui/lib/src/engine/html_image_codec.dart)

In this scenario it's `codec.getNextFrame()` that never ever returns.

**Comment by lukaslihotzki** [comment]
To show raw image data on the web, I think the options are canvas.putImageData or creating a Bitmap Blob. The code as is assumes image elements and not canvas elements in HtmlImage. Additionally, cloneImageElement and similar uses are inefficient for canvas elements because image data would need to be copied.

Therefore, creating a Blob with bitmap header seems the easiest and most efficient way. The blob can be constructed out of parts, so no additional data copies are needed.

I have implemented that in https://github.com/lukaslihotzki/engine/commits/web-pixels. The bmpHeader part is based on the flutter_blurhash workaround. The code isn't tested in this context, just in a small separate project.

**Comment by markusaksli-nc** [comment]
Reproducible on the latest master `1.22.0-10.0.pre.221`.
<details>
 <summary>flutter doctor -v</summary>

```
[√] Flutter (Channel master, 1.22.0-10.0.pre.221, on Microsoft Windows [Version 10.0.19041.508], locale en-US)
    • Flutter version 1.22.0-10.0.pre.221 at C:\Development\flutter_master
    • Framework revision fa646339d6 (8 hours ago), 2020-09-16 17:47:04 -0700
    • Engine revision 933f811d94
    • Dart version 2.10.0 (build 2.10.0-135.0.dev)

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
    • Android SDK at C:\Users\marku\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.1
    • Java binary at: C:\Users\marku\AppData\Local\JetBrains\Toolbox\apps\AndroidStudio\ch-0\193.6626763\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.6.5)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.6.30320.27
    • Windows 10 SDK version 10.0.18362.0

[√] Android Studio (version 4.0)
    • Android Studio at C:\Users\marku\AppData\Local\JetBrains\Toolbox\apps\AndroidStudio\ch-0\193.6626763
    • Flutter plugin version 47.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] Connected device (6 available)
    • SM G950F (mobile)           • ce12171c51cc001c03 • android-arm64  • Android 9 (API 28)
    • sdk gphone x86 arm (mobile) • emulator-5554      • android-x86    • Android 11 (API 30) (emulator)
    • Windows (desktop)           • windows            • windows-x64    • Microsoft Windows [Version 10.0.19041.508]
    • Web Server (web)            • web-server         • web-javascript • Flutter Tools
    • Chrome (web)                • chrome             • web-javascript • Google Chrome 85.0.4183.102
    • Edge (web)                  • edge               • web-javascript • Microsoft Edge 85.0.564.44

• No issues found!
```
</details>
<details>
 <summary>Minimal reproducible code sample</summary>

```dart
import 'dart:math';
import 'dart:typed_data';
import 'dart:ui' as ui;

import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Sample',
      home: Scaffold(
        appBar: AppBar(
          title: Text('Sample'),
        ),
        body: Center(
          child: MyImage(),
        ),
      ),
    );
  }
}

class MyImage extends StatefulWidget {
  MyImageState createState() => MyImageState();
}

class MyImageState extends State<MyImage> {
  ui.Image img;

  void makeImage() {
    int len = 256 * 256 * 4;
    final pixels = Uint8List(len);
    for (int i = 0; i < pixels.length; i++) {
      pixels[i] = Random().nextInt(255);
    }
    ui.decodeImageFromPixels(pixels, 256, 256, ui.PixelFormat.rgba8888, setImg);
  }

  void setImg(ui.Image data) {
    setState(() {
      this.img = data;
    });
  }

  @override
  void initState() {
    img = null;
    super.initState();
  }

  @override
  Widget build(BuildContext context) {
    return Column(
      children: <Widget>[
        RawImage(image: this.img),
        RaisedButton(
          child: Text("Generate"),
          onPressed: () {
            makeImage();
          },
        )
      ],
    );
  }
}
```
</details>

Removing documentation label since this is just a web implementation issue.

**Comment by deakjahn** [comment]
@yjbanov Yegor, in the `blurhash` plugin a simple workaround was added, generating a BMP on the fly. Not necessarily the cleanest of all solutions but if you don't have anything more straightforward coming, maybe it can serve in the general case, too? See https://github.com/fluttercommunity/flutter_blurhash/pull/19/files

**Comment by rootext** [comment]
Hello! Any updates on this issue?

**Comment by deakjahn** [comment]
@rootext Looking into the source code, it seems to me that this has been already implemented. Not the very same code I mentioned above but the same general idea, only in a bit more universal way (it supports both bgra and rgba, so it needs to fill the bitmap data manually into the buffers).

Both -beta and -dev seem to have it already.

**Comment by rootext** [comment]
@deakjahn Thank you for checking this but it still doesn't work on web with latest dev.
The same code works fine on desktop.

<details>
<summary>logs</summary>
```
Error: ImageCodecException: Failed to decode image data.
Image source: encoded image bytes
    at Object.throw_ [as throw] (http://localhost:65166/dart_sdk.js:5336:11)
    at _engine.CkAnimatedImage.decodeFromBytes.createDefault (http://localhost:65166/dart_sdk.js:140187:19)
    at _engine.CkAnimatedImage.decodeFromBytes.ManagedSkiaObject.new (http://localhost:65166/dart_sdk.js:138641:65)
    at new _engine.CkAnimatedImage.decodeFromBytes (http://localhost:65166/dart_sdk.js:140237:43)
    at Object.skiaInstantiateImageCodec (http://localhost:65166/dart_sdk.js:181412:12)
    at Object.decodeImageFromPixels (http://localhost:65166/dart_sdk.js:134435:15)
    at _createImage (http://localhost:65166/packages/opend2_editor/loaders/ff_loader.dart.lib.js:80:12)
    at _createImage.next (<anonymous>)
```
</details>

flutter doctor
```
[√] Flutter (Channel dev, 1.26.0-17.1.pre, on Microsoft Windows [Version 10.0.19042.746], locale en-US)
```

**Comment by deakjahn** [comment]
Do you have a small sample to test? It would be easier to run that than to craft one myself. I'm curious now.

**Comment by rootext** [comment]
Here is example.
<details>
import 'dart:async';
import 'dart:typed_data';
import 'dart:ui';

import 'package:flutter/material.dart' hide Image;

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key key, this.title}) : super(key: key);

  final String title;

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {

  void _decode() async {
    var pixels = new Uint8List.fromList([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]);
    Completer completer = Completer<Image>();
    decodeImageFromPixels(pixels, 2, 2, PixelFormat.rgba8888, (image) => completer.complete(image)); 
    var image = await completer.future;
    print('image decoded ${image.width}x${image.height}');
  }

  @override
  Widget build(BuildContext context) {
    return Center(child: ElevatedButton(onPressed: _decode, child: Text('Decode image')));
  }
}

</details>

**Comment by deakjahn** [comment]
And you get a "failed to decode image" exception, but only in CanvasKit, not in DomCanvas, don't you?

Yes, I only checked that the source code seems to call the logically appropriate functions, not that they actually work. :-)

**Comment by deakjahn** [comment]
Well, it went on quite a lot since I last looked into it with my PR of yesteryear, so I'm not sure any more but this looks like it:

    void decodeImageFromPixels(
      Uint8List pixels,
      int width,
      int height,
      PixelFormat format,
      ImageDecoderCallback callback, {
      int? rowBytes,
      int? targetWidth,
      int? targetHeight,
      bool allowUpscaling = true,
    }) {
      if (engine.useCanvasKit) {
        engine.skiaInstantiateImageCodec(
          pixels,
          width,
          height,
          format.index,
          rowBytes,
        ).getNextFrame().then((FrameInfo info) {
          callback(info.image);
        });
        return;
      }
    
      void Function(Codec) callbacker = (Codec codec) {
        codec.getNextFrame().then((FrameInfo frameInfo) {
          callback(frameInfo.image);
        });
      };
      _createBmp(pixels, width, height, rowBytes ?? width, format).then(callbacker);
    }

It tries an alternate route with CanvasKit, calling `engine.skiaInstantiateImageCodec()` and that only passes the bytes on, nothing else. No size, no format. That suggests to me that it doesn't actually support _rbga8888_ or _bgra8888_ because those can't live without the extra data. This call probably only supports encoded images like PNG or JPG that are self-contained and self-describing.

@yjbanov could really answer this but I have a hunch that this `if` should only be called if `engine.useCanvasKit` **and** the format isn't either of these direct pixel data formats, rgba or bgra. If they are, it should be left to `_createBmp()` to create the image. If it's PNG or JPG or anything else, it can go to Skia all right.

**Comment by rootext** [comment]
@deakjahn You are right. I use CanvasKit `--web-renderer canvaskit` because otherwise performance of `Canvas` is unacceptable.

**Comment by deakjahn** [comment]
There's no doubt about that. I moved to CanvasKit only quite a few months ago and never looked back...

**Comment by JakubNeukirch** [comment]
Same problem here, any new workarounds?
