### ISSUE TITLE
Flutter WebView JVM crash when height is large/ wrapped within ListView or CustomScrollView

### ISSUE THREAD

**Issue by VadimOsovsky** [flutter/flutter#45243]
## Steps to Reproduce

1. Create Listview
2. Put Container(height: 10000.0, child: WebView( ... )) to the Listview's children
3. Run
4. Enjoy JVM shutdown and device reboot

**Target Platform:**
Android
**Target OS version/browser:**
api 28
**Devices:**
Xiaomi MI8

<details>
  <summary>logs</summary>
 
```
E/MethodChannel#flutter/platform_views(25723): Failed to handle method call
E/MethodChannel#flutter/platform_views(25723): java.lang.RuntimeException: InputChannel is not initialized.
E/MethodChannel#flutter/platform_views(25723): 	at android.view.InputEventReceiver.nativeInit(Native Method)
E/MethodChannel#flutter/platform_views(25723): 	at android.view.InputEventReceiver.<init>(InputEventReceiver.java:80)
E/MethodChannel#flutter/platform_views(25723): 	at android.view.ViewRootImpl$WindowInputEventReceiver.<init>(ViewRootImpl.java:7457)
E/MethodChannel#flutter/platform_views(25723): 	at android.view.ViewRootImpl.setView(ViewRootImpl.java:917)
E/MethodChannel#flutter/platform_views(25723): 	at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:356)
E/MethodChannel#flutter/platform_views(25723): 	at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:94)
E/MethodChannel#flutter/platform_views(25723): 	at android.app.Dialog.show(Dialog.java:329)
E/MethodChannel#flutter/platform_views(25723): 	at android.app.Presentation.show(Presentation.java:249)
E/MethodChannel#flutter/platform_views(25723): 	at io.flutter.plugin.platform.VirtualDisplayController.<init>(VirtualDisplayController.java:92)
E/MethodChannel#flutter/platform_views(25723): 	at io.flutter.plugin.platform.VirtualDisplayController.create(VirtualDisplayController.java:52)
E/MethodChannel#flutter/platform_views(25723): 	at io.flutter.plugin.platform.PlatformViewsController$1.createPlatformView(PlatformViewsController.java:97)
E/MethodChannel#flutter/platform_views(25723): 	at io.flutter.embedding.engine.systemchannels.PlatformViewsChannel$1.create(PlatformViewsChannel.java:87)
E/MethodChannel#flutter/platform_views(25723): 	at io.flutter.embedding.engine.systemchannels.PlatformViewsChannel$1.onMethodCall(PlatformViewsChannel.java:51)
E/MethodChannel#flutter/platform_views(25723): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:222)
E/MethodChannel#flutter/platform_views(25723): 	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:96)
E/MethodChannel#flutter/platform_views(25723): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:656)
E/MethodChannel#flutter/platform_views(25723): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/MethodChannel#flutter/platform_views(25723): 	at android.os.MessageQueue.next(MessageQueue.java:326)
E/MethodChannel#flutter/platform_views(25723): 	at android.os.Looper.loop(Looper.java:165)
E/MethodChannel#flutter/platform_views(25723): 	at android.app.ActivityThread.main(ActivityThread.java:6806)
E/MethodChannel#flutter/platform_views(25723): 	at java.lang.reflect.Method.invoke(Native Method)
E/MethodChannel#flutter/platform_views(25723): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
E/MethodChannel#flutter/platform_views(25723): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:873)
E/flutter (25723): [ERROR:flutter/lib/ui/ui_dart_state.cc(148)] Unhandled Exception: PlatformException(error, InputChannel is not initialized., null)
E/flutter (25723): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:569:7)
E/flutter (25723): #1      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:316:33)
E/flutter (25723): <asynchronous suspension>
E/flutter (25723): #2      AndroidViewController._create (package:flutter/src/services/platform_views.dart:640:54)
E/flutter (25723): <asynchronous suspension>
E/flutter (25723): #3      AndroidViewController.setSize (package:flutter/src/services/platform_views.dart:557:14)
E/flutter (25723): <asynchronous suspension>
E/flutter (25723): #4      RenderAndroidView._sizePlatformView (package:flutter/src/rendering/platform_view.dart:174:29)
E/flutter (25723): <asynchronous suspension>
E/flutter (25723): #5      RenderAndroidView.performResize (package:flutter/src/rendering/platform_view.dart:155:5)
E/flutter (25723): #6      RenderObject.layout (package:flutter/src/rendering/object.dart:1686:9)
E/flutter (25723): #7      RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
E/flutter (25723): #8      RenderObject.layout (package:flutter/src/rendering/object.dart:1701:7)
E/flutter (25723): #9      RenderConstrainedBox.performLayout (package:flutter/src/rendering/proxy_box.dart:259:13)
E/flutter (25723): #10     RenderObject.layout (package:flutter/src/rendering/object.dart:1701:7)
E/flutter (25723): #11     RenderStack.performLayout (package:flutter/src/rendering/stack.dart:510:15)
E/flutter (25723): #12     RenderObject.layout (package:flutter/src/rendering/object.dart:1701:7)
E/flutter (25723): #13     RenderFlex.performLayout (package:flutter/src/rendering/flex.dart:744:15)
E/flutter (25723): #14     RenderObject.layout (package:flutter/src/rendering/object.dart:1701:7)
E/flutter (25723): #15     RenderPadding.performLayout (package:flutter/src/rendering/shifted_box.dart:206:11)
E/flutter (25723): #16     RenderObject.layout (package:flutter/src/rendering/object.dart:1701:7)
E/flutter (25723): #17     _RenderSingleChildViewport.performLayout (package:flutter/src/widgets/single_child_scroll_view.dart:497:13)
E/flutter (25723): #18     RenderObject.layout (package:flutter/src/rendering/object.dart:1701:7)
E/flutter (25723): #19     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
E/flutter (25723): #20     RenderObject.layout (package:flutter/src/rendering/object.dart:1701:7)
E/flutter (25723): #21     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
E/flutter (25723): #22     RenderObject.layout (package:flutter/src/rendering/object.dart:1701:7)
E/flutter (25723): #23     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
E/flutter (25723): #24     RenderObject.layout (package:flutter/src/rendering/object.dart:1701:7)
E/flutter (25723): #25     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
E/flutter (25723): #26     RenderObject.layout (package:flutter/src/rendering/object.dart:1701:7)
E/flutter (25723): #27     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
E/flutter (25723): #28     RenderObject.layout (package:flutter/src/rendering/object.dart:1701:7)
E/flutter (25723): #29     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
E/flutter (25723): #30     RenderObject.layout (package:flutter/src/rendering/object.dart:1701:7)
E/flutter (25723): #31     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
E/flutter (25723): #32     RenderObject.layout (package:flutter/src/rendering/object.dart:1701:7)
E/flutter (25723): #33     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
E/flutter (25723): #34     RenderObject.layout (package:flutter/src/rendering/object.dart:1701:7)
E/flutter (25723): #35     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
E/flutter (25723): #36     RenderObject.layout (package:flutter/src/rendering/object.dart:1701:7)
E/flutter (25723): #37     MultiChildLayoutDelegate.layoutChild (package:flutter/src/rendering/custom_layout.dart:142:11)
E/flutter (25723): #38     _ScaffoldLayout.performLayout (package:flutter/src/material/scaffold.dart:444:7)
E/flutter (25723): #39     MultiChildLayoutDelegate._callPerformLayout (package:flutter/src/rendering/custom_layout.dart:212:7)
E/flutter (25723): #40     RenderCustomMultiChildLayoutBox.performLayout (package:flutter/src/rendering/custom_layout.dart:356:14)
E/flutter (25723): #41     RenderObject.layout (package:flutter/src/rendering/object.dart:1701:7)
E/flutter (25723): #42     RenderProxyBoxMixin.performLayout (package
Lost connection to device.

```

</details>

```
Analyzing mail_client...                                                

warning • The parameter 'darkThemeEnabled' is required • lib/modules/auth/repository/auth_api.dart:37:18 • missing_required_param
   info • Avoid using braces in interpolation when not needed • lib/modules/mail/screens/message_view/components/message_body.dart:74:25 • unnecessary_brace_in_string_interps
   info • Avoid using braces in interpolation when not needed • lib/modules/mail/screens/message_view/components/message_body.dart:75:23 • unnecessary_brace_in_string_interps
   info • Duplicate import • lib/modules/mail/screens/message_view/components/message_view_app_bar.dart:2:8 • duplicate_import
   info • Duplicate import • lib/modules/mail/screens/message_view/components/message_view_app_bar.dart:3:8 • duplicate_import
   info • The value of the field '_pageCtrl' isn't used • lib/modules/mail/screens/message_view/message_view_android.dart:39:18 • unused_field
   info • The declaration '_getWebColor' isn't referenced • lib/utils/mail_utils.dart:173:17 • unused_element

7 issues found. (ran in 7.0s)
```

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, v1.9.1+hotfix.6, on Mac OS X 10.15 19A583, locale en-RU)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 11.1)
[!] Android Studio (version 3.5)
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
[✓] IntelliJ IDEA Ultimate Edition (version 2019.2.4)
[✓] VS Code (version 1.38.1)
[✓] Connected device (1 available)

! Doctor found issues in 1 category.
```

**Comment by iapicca** [comment]
<details>
  <summary>error</summary>

`W/PlatformViewsController(13326): Creating a virtual display of size: [1080, 27500] may result in problems(https://github.com/flutter/flutter/issues/2897).It is larger than the device screen size: [1080, 2088].`

</details>

<details>
  <summary>code sample</summary>

```
import 'package:flutter/material.dart';
import 'package:webview_flutter/webview_flutter.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        // This is the theme of your application.
        //
        // Try running your application with "flutter run". You'll see the
        // application has a blue toolbar. Then, without quitting the app, try
        // changing the primarySwatch below to Colors.green and then invoke
        // "hot reload" (press "r" in the console where you ran "flutter run",
        // or simply save your changes to "hot reload" in a Flutter IDE).
        // Notice that the counter didn't reset back to zero; the application
        // is not restarted.
        primarySwatch: Colors.blue,
      ),
      home: HomePage(),
    );
  }
}

class HomePage extends StatefulWidget {
  @override
  _HomePageState createState() => _HomePageState();
}

const double _height =  10000;

class _HomePageState extends State<HomePage> {
  @override
  Widget build(BuildContext context) => Scaffold(
    appBar: AppBar(
      title: Text(_height.toString()),
    ),
    body: ListView(
      children: <Widget>[
        Container(
          height: _height,
          child: WebView(
            initialUrl: 'https://flutter.io',
            javascriptMode: JavascriptMode.unrestricted,
          ),
        ),
      ],
    ),
  );
}
```

</details>

**Comment by ozyl** [comment]
How to deal with it?

**Comment by yangming1009** [comment]
same too.

**Comment by TahaTesser** [comment]
<details> 
<summary>logs</summary> 

``` 
Launching lib/main.dart on SM M305F in debug mode...
✓ Built build/app/outputs/flutter-apk/app-debug.apk.
Connecting to VM Service at ws://127.0.0.1:56612/DrMp2auMAns=/ws
D/Dialog  (16760): mIsSamsungBasicInteraction = false
D/Dialog  (16760): mIsSamsungBasicInteraction = false, isMetaDataInActivity = false
I/WebViewFactory(16760): Loading com.google.android.webview version 84.0.4147.111 (code 414711183)
W/Gralloc3(16760): allocator 3.x is not supported
I/cr_LibraryLoader(16760): Loaded native library version number "84.0.4147.111"
I/cr_CachingUmaRecorder(16760): Flushed 5 samples from 5 histograms.
W/chromium(16760): [WARNING:dns_config_service_posix.cc(342)] Failed to read DnsConfig.
W/ple.dev_flutte(16760): Accessing hidden method Landroid/media/AudioManager;->getOutputLatency(I)I (greylist, reflection, allowed)
W/cr_media(16760): Requires BLUETOOTH permission
I/MultiWindowDecorSupport(16760): updateCaptionType >> DecorView@1e0636f[], isFloating: false, isApplication: false, hasWindowDecorCaption: false, hasWindowControllerCallback: false
D/MultiWindowDecorSupport(16760): setCaptionType = 0, DecorView = DecorView@1e0636f[]
D/ViewRootImpl@78e8c81[MainActivity](16760): setView = com.android.internal.policy.DecorView@1e0636f TM=true MM=false
V/InputMethodManager(16760): Not IME target window, ignoring
D/ViewRootImpl@78e8c81[MainActivity](16760): Relayout returned: old=(0,0,1080,3) new=(0,0,1080,3) req=(1080,3)0 dur=16 res=0x7 s={true 526379294720} ch=true
D/OpenGLRenderer(16760): createReliableSurface : 0x7b0b54c280, 0x7a8ea6a000
D/mali_winsys(16760): EGLint new_window_surface(egl_winsys_display *, void *, EGLSurface, EGLConfig, egl_winsys_surface **, EGLBoolean) returns 0x3000
E/DecorView(16760): mWindow.mActivityCurrentConfig is null
D/ViewRootImpl@78e8c81[MainActivity](16760): MSG_RESIZED: frame=(0,0,1080,3) ci=(0,0,0,0) vi=(0,0,0,0) or=2
D/NetworkSecurityConfig(16760): No Network Security Config specified, using platform default
I/chromium(16760): [INFO:CONSOLE(144)] "JQMIGRATE: Migrate is installed with logging active, version 3.1.0", source: https://en.m.wikipedia.org/w/load.php?lang=en&modules=jquery%2Coojs-ui-core%2Coojs-ui-widgets&skin=minerva&version=1wn7i (144)
I/chromium(16760): [INFO:CONSOLE(343)] "This page is using the deprecated ResourceLoader module "jquery.throttle-debounce".
I/chromium(16760): Please use OO.ui.throttle/debounce instead. See https://phabricator.wikimedia.org/T213426", source:  (343)
W/PlatformViewsController(16760): Creating a virtual display of size: [1080, 12813] may result in problems(https://github.com/flutter/flutter/issues/2897).It is larger than the device screen size: [1080, 2218].
E/InputMethodManager(16760): b/117267690: Failed to get fallback IMM with expected displayId=4 actual IMM#displayId=0 view=io.flutter.plugins.webviewflutter.InputAwareWebView{11d0ae1 VFEDHVC.. ........ 0,0-1080,3}
D/Dialog  (16760): mIsSamsungBasicInteraction = false
D/Dialog  (16760): mIsSamsungBasicInteraction = false, isMetaDataInActivity = false
I/MultiWindowDecorSupport(16760): updateCaptionType >> DecorView@fe741d[], isFloating: false, isApplication: false, hasWindowDecorCaption: false, hasWindowControllerCallback: false
D/MultiWindowDecorSupport(16760): setCaptionType = 0, DecorView = DecorView@fe741d[]
D/ViewRootImpl@2ffe7bf[MainActivity](16760): setView = com.android.internal.policy.DecorView@fe741d TM=true MM=false
W/libEGL  (16760): EGLNativeWindowType 0x7b0b54c290 disconnect failed
D/ViewRootImpl@78e8c81[MainActivity](16760): dispatchDetachedFromWindow
D/InputTransport(16760): Input channel destroyed: '2a2f9a2', fd=162
V/InputMethodManager(16760): Not IME target window, ignoring
Lost connection to device.
Exited (sigterm)

``` 

</details> 


<details> 
<summary>flutter doctor -v</summary> 

```
[✓] Flutter (Channel dev, 1.21.0-1.0.pre, on Mac OS X 10.15.6 19G73, locale
    en-GB)
    • Flutter version 1.21.0-1.0.pre at /Users/taha/Code/flutter_dev
    • Framework revision f25bd9c55c (3 weeks ago), 2020-07-14 20:26:01 -0400
    • Engine revision 99c2b3a245
    • Dart version 2.9.0 (build 2.9.0-21.0.dev 20bf2fcf56)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
    • Android SDK at /Users/taha/Code/sdk
    • Platform android-30, build-tools 30.0.1
    • ANDROID_HOME = /Users/taha/Code/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.6)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.6, Build version 11E708
    • CocoaPods version 1.9.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 48.0.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.47.3)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.13.1

[✓] Connected device (4 available)
    • SM M305F (mobile) • 32003c30dc19668f • android-arm64  • Android 10 (API
      29)
    • macOS (desktop)   • macos            • darwin-x64     • Mac OS X 10.15.6
      19G73
    • Web Server (web)  • web-server       • web-javascript • Flutter Tools
    • Chrome (web)      • chrome           • web-javascript • Google Chrome
      84.0.4147.105

• No issues found!

```

</details>

**Comment by chinmaygarde** [comment]
Removing the engine tag as this is a plugin implementation issue.

**Comment by DFelten** [comment]
For the sake of completeness, here is an example app with the reproducible code. It works for small pages, but not for large ones. The height when it crashes depends on the device. You could for example set the height manually to a value like 13000:

```dart
import 'package:flutter/material.dart';
import 'package:webview_flutter/webview_flutter.dart';

void main() => runApp(MaterialApp(home: CrashingWebViewExample()));

class CrashingWebViewExample extends StatefulWidget {
  @override
  _CrashingWebViewExampleState createState() => _CrashingWebViewExampleState();
}

class _CrashingWebViewExampleState extends State<CrashingWebViewExample> {
  WebViewController _webViewController;
  double _webViewHeight = 1;

  @override
  Widget build(BuildContext context) {
    return SingleChildScrollView(
      child: Column(
        children: <Widget>[
          Container(height: 100, color: Colors.green),
          Container(
            height: _webViewHeight,
            child: WebView(
              initialUrl: 'https://en.wikipedia.org/wiki/Cephalopod_size',
              javascriptMode: JavascriptMode.unrestricted,
              onPageFinished: (String url) => _onPageFinished(context, url),
              onWebViewCreated: (controller) async {
                _webViewController = controller;
              },
            ),
          ),
          Container(height: 100, color: Colors.yellow),
        ],
      ),
    );
  }

  Future<void> _onPageFinished(BuildContext context, String url) async {
    double newHeight = double.parse(
      await _webViewController.evaluateJavascript("document.documentElement.scrollHeight;"),
    );
    setState(() {
      _webViewHeight = newHeight;
    });
  }
}
```

The code is also available [on GitHub][2].

**Comment by gabrielferreir** [comment]
The alternative for me was to develop the rest of the page in html and use navigationDelegate to control the actions


```
WebView(
  initialUrl: new Uri.dataFromString(
    state.html ?? '',
    mimeType: 'text/html',
    encoding: Encoding.getByName('utf-8'),
  ).toString(),
  navigationDelegate: (v) {
    if (v.url == 'back') {
      Navigator.pop(context);
    }
    return NavigationDecision.prevent;
  },
 debuggingEnabled: true,
 javascriptMode: JavascriptMode.unrestricted,
  ...
```

**Comment by uc-ach** [comment]
Did you tried SingleChildScrollView ?

**Comment by gingerJY** [comment]
same here.Are there practical solutions? I used flutter_inappwebview.

**Comment by cyanglaz** [comment]
Is it still reproducible if you use `SurfaceAndroidWebView`?

**Comment by danagbemava-nc** [comment]
After testing with `SurfaceAndroidWebView` on the latest `stable version of flutter (2.2.3)` and `webview_flutter: ^2.0.10`, the issue cannot be reproduced so I will be closing this issue and marking it as fixed. If anybody disagrees of thinks it should be kept open, post a comment and I will reopen it. For reference, find the updated sample code below.

<details>
<summary>Code sample using SurfaceAndroidWebView</summary>

```dart
import 'dart:io';

import 'package:flutter/material.dart';
import 'package:webview_flutter/webview_flutter.dart';

void main() => runApp(MaterialApp(home: CrashingWebViewExample()));

class CrashingWebViewExample extends StatefulWidget {
  @override
  _CrashingWebViewExampleState createState() => _CrashingWebViewExampleState();
}

class _CrashingWebViewExampleState extends State<CrashingWebViewExample> {
  late WebViewController _webViewController;
  // [1] the webview height was set to this because the webpage might not have been large enough to verify
  double _webViewHeight = 100000;

  @override
  void initState() {
    super.initState();
    if (Platform.isAndroid) {
      WebView.platform = SurfaceAndroidWebView();
    }
  }

  @override
  Widget build(BuildContext context) {
    return SingleChildScrollView(
      child: Column(
        children: <Widget>[
          Container(height: 100, color: Colors.green),
          Container(
            height: _webViewHeight,
            child: WebView(
              initialUrl: 'https://en.wikipedia.org/wiki/Cephalopod_size',
              javascriptMode: JavascriptMode.unrestricted,
              onPageFinished: (String url) => _onPageFinished(context, url),
              onWebViewCreated: (controller) async {
                _webViewController = controller;
              },
            ),
          ),
          Container(height: 100, color: Colors.yellow),
        ],
      ),
    );
  }

  Future<void> _onPageFinished(BuildContext context, String url) async {
    double newHeight = double.parse(
      await _webViewController
          .evaluateJavascript("document.documentElement.scrollHeight;"),
    );
    // commented out because of [1]
    // setState(() {
    //   _webViewHeight = newHeight;
    // });
  }
}
```
</details>
