### ISSUE TITLE
New project, open flutter debug run, then open android debug run, then open flutter debug run will not find "libflutter.so"?

### ISSUE THREAD

**Issue by Aaron009** [flutter/flutter#45314]
flutter version:    Flutter 1.10.15-pre.384
dart version: 2.7.0

The error message is as follows:
```shell
2019-11-21 10:54:30.651 13439-13439/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.example.flutter_test_demo, PID: 13439
    java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.example.flutter_test_demo-fbcmF1aZ9LxzdBmL7WssdQ==/base.apk"],nativeLibraryDirectories=[/data/app/com.example.flutter_test_demo-fbcmF1aZ9LxzdBmL7WssdQ==/lib/arm64, /system/lib64, /vendor/lib64, /product/lib64]]] couldn't find "libflutter.so"
        at java.lang.Runtime.loadLibrary0(Runtime.java:1011)
        at java.lang.System.loadLibrary(System.java:1660)
        at io.flutter.embedding.engine.loader.FlutterLoader.startInitialization(FlutterLoader.java:122)
        at io.flutter.embedding.engine.loader.FlutterLoader.startInitialization(FlutterLoader.java:93)
        at io.flutter.view.FlutterMain.startInitialization(FlutterMain.java:45)
        at io.flutter.app.FlutterApplication.onCreate(FlutterApplication.java:22)
        at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1122)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6619)
        at android.app.ActivityThread.-wrap2(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2066)
        at android.os.Handler.dispatchMessage(Handler.java:108)
        at android.os.Looper.loop(Looper.java:166)
        at android.app.ActivityThread.main(ActivityThread.java:7529)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:245)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:921)
```

I don't know if you have ever encountered this situation. I don't know if the description is clear. If you need me to record a video, please leave a message below.

**Comment by askarsyzdykov** [comment]
`Build -> Clean project` helped me

**Comment by iapicca** [comment]
Hi @Aaron009 
did the proposed solution fix your issue? (thank you @askarsyzdykov )
If it didn't could you please provide your`flutter build --verbose` ?
Also, to better address the issue, would be helpful
if you could post a minimal code sample to reproduce the problem
Thank you

**Comment by Aaron009** [comment]
> `Build -> Clean project` helped me

@iapicca @askarsyzdykov

Successfully resolved.
When you open the android project debug, you need to clean up the project.
Then open the flutter project to debug it properly.

**Comment by iapicca** [comment]
Hi again @Aaron009 
I'm glad that you fixed the issue,
thank you for letting me know
