### ISSUE TITLE
Flutter crash, After a while, the problem disappeared again

### ISSUE THREAD

**Issue by dumplings** [flutter/flutter#45323]
Flutter crash report; please file at https://github.com/flutter/flutter/issues.

## command

flutter build bundle --target /Users/zhaozhihui/FlutterProjects/ireadabc_student_zzh/lib/main.dart --target-platform android-x86 --filesystem-scheme org-dartlang-root --track-widget-creation --depfile /Users/zhaozhihui/FlutterProjects/ireadabc_student_zzh/build/app/intermediates/flutter/debug/android-x86/snapshot_blob.bin.d --asset-dir /Users/zhaozhihui/FlutterProjects/ireadabc_student_zzh/build/app/intermediates/flutter/debug/android-x86/flutter_assets --debug

## exception

NoSuchMethodError: NoSuchMethodError: The getter 'length' was called on null.
Receiver: null
Tried calling: length

```
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:51:5)
#1      _Uri._uriEncode (dart:core-patch/uri_patch.dart:44:23)
#2      Uri.encodeFull (dart:core/uri.dart:1148:17)
#3      MappedListIterable.elementAt (dart:_internal/iterable.dart:415:29)
#4      MappedListIterable.elementAt (dart:_internal/iterable.dart:415:40)
#5      ListIterable.toList (dart:_internal/iterable.dart:219:19)
#6      FlutterManifest.assets (package:flutter_tools/src/flutter_manifest.dart:187:11)
#7      _parseAssets (package:flutter_tools/src/asset.dart:557:40)
#8      _ManifestAssetBundle.build (package:flutter_tools/src/asset.dart:143:53)
<asynchronous suspension>
#9      buildAssets (package:flutter_tools/src/bundle.dart:137:40)
<asynchronous suspension>
#10     BundleBuilder.build (package:flutter_tools/src/bundle.dart:106:38)
<asynchronous suspension>
#11     BuildBundleCommand.runCommand (package:flutter_tools/src/commands/build_bundle.dart:119:25)
<asynchronous suspension>
#12     FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:490:18)
<asynchronous suspension>
#13     FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:407:33)
<asynchronous suspension>
#14     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:154:29)
<asynchronous suspension>
#15     _rootRun (dart:async/zone.dart:1124:13)
#16     _CustomZone.run (dart:async/zone.dart:1021:19)
#17     _runZoned (dart:async/zone.dart:1516:10)
#18     runZoned (dart:async/zone.dart:1463:12)
#19     AppContext.run (package:flutter_tools/src/base/context.dart:153:18)
<asynchronous suspension>
#20     FlutterCommand.run (package:flutter_tools/src/runner/flutter_command.dart:397:20)
#21     CommandRunner.runCommand (package:args/command_runner.dart:197:27)
<asynchronous suspension>
#22     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:402:21)
<asynchronous suspension>
#23     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:154:29)
<asynchronous suspension>
#24     _rootRun (dart:async/zone.dart:1124:13)
#25     _CustomZone.run (dart:async/zone.dart:1021:19)
#26     _runZoned (dart:async/zone.dart:1516:10)
#27     runZoned (dart:async/zone.dart:1463:12)
#28     AppContext.run (package:flutter_tools/src/base/context.dart:153:18)
<asynchronous suspension>
#29     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:356:19)
<asynchronous suspension>
#30     CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:112:25)
#31     new Future.sync (dart:async/future.dart:224:31)
#32     CommandRunner.run (package:args/command_runner.dart:112:14)
#33     FlutterCommandRunner.run (package:flutter_tools/src/runner/flutter_command_runner.dart:242:18)
#34     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:63:22)
<asynchronous suspension>
#35     _rootRun (dart:async/zone.dart:1124:13)
#36     _CustomZone.run (dart:async/zone.dart:1021:19)
#37     _runZoned (dart:async/zone.dart:1516:10)
#38     runZoned (dart:async/zone.dart:1500:12)
#39     run.<anonymous closure> (package:flutter_tools/runner.dart:61:18)
<asynchronous suspension>
#40     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:154:29)
<asynchronous suspension>
#41     _rootRun (dart:async/zone.dart:1124:13)
#42     _CustomZone.run (dart:async/zone.dart:1021:19)
#43     _runZoned (dart:async/zone.dart:1516:10)
#44     runZoned (dart:async/zone.dart:1463:12)
#45     AppContext.run (package:flutter_tools/src/base/context.dart:153:18)
<asynchronous suspension>
#46     runInContext (package:flutter_tools/src/context_runner.dart:59:24)
<asynchronous suspension>
#47     run (package:flutter_tools/runner.dart:50:10)
#48     main (package:flutter_tools/executable.dart:65:9)
<asynchronous suspension>
#49     main (file:///Users/zhaozhihui/development/flutter/packages/flutter_tools/bin/flutter_tools.dart:8:3)
#50     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:303:32)
#51     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:12)
```

## flutter doctor

```
[✓] Flutter (Channel stable, v1.9.1+hotfix.6, on Mac OS X 10.15.1 19B88, locale zh-Hans-CN)
    • Flutter version 1.9.1+hotfix.6 at /Users/zhaozhihui/development/flutter
    • Framework revision 68587a0916 (10 weeks ago), 2019-09-13 19:46:58 -0700
    • Engine revision b863200c37
    • Dart version 2.5.0

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/zhaozhihui/Library/Android/sdk
    • Android NDK at /Users/zhaozhihui/Library/Android/sdk/ndk-bundle
    • Platform android-29, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
    • All Android licenses accepted.

[✗] Xcode - develop for iOS and macOS
    ✗ Xcode installation is incomplete; a full installation is necessary for iOS development.
      Download at: https://developer.apple.com/xcode/download/
      Or install Xcode via the App Store.
      Once installed, run:
        sudo xcode-select --switch /Applications/Xcode.app/Contents/Developer
    ✗ CocoaPods installed but not working.
        You appear to have CocoaPods installed but it is not working.
        This can happen if the version of Ruby that CocoaPods was installed with is different from the one being used to invoke it.
        This can usually be fixed by re-installing CocoaPods. For more info, see https://github.com/flutter/flutter/issues/14293.
      To re-install CocoaPods, run:
        sudo gem install cocoapods

[✓] Android Studio (version 3.4)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 38.2.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

[✓] VS Code (version 1.40.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.2.0

[✓] Connected device (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 8.1.0 (API 27) (emulator)

! Doctor found issues in 1 category.
```

**Comment by iapicca** [comment]
Hi @dumplings 

this error might depend from your code
```
NoSuchMethodError: NoSuchMethodError: The getter 'length' was called on null.
Receiver: null
Tried calling: length
```

could you please provide a minimal code sample to reproduce the problem?
Thank you

**Comment by jmagman** [comment]
Can you paste your pubspec so we can see your assets section?

**Comment by Hixie** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
  
Thanks for your contribution.
