### ISSUE TITLE
WEB - AssetNotFoundException: flutter|lib/src/gestures/arena.ddc.js

### ISSUE THREAD

**Issue by FindtheTreasure** [flutter/flutter#45331]
## Steps to Reproduce

Flutter web was compiling fine on web master channel. Ran flutter upgrade then error in title was thrown and failed to compile --> AssetNotFoundException: flutter|lib/src/gestures/arena.ddc.js

## Logs

```
PS C:\App Development\Flutter\Find The Treasure CMS\ftt_cms> flutter run -d chrome  --verbose
[  +19 ms] executing: [C:\flutter\] git -c log.showSignature=false log -n 1 --pretty=format:%H
[  +38 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[        ] 0b502b1f8bb512370924e1dffb776cc17312e951
[        ] executing: [C:\flutter\] git describe --match v*.*.* --first-parent --long --tags
[  +46 ms] Exit code 0 from: git describe --match v*.*.* --first-parent --long --tags
[        ] v1.12.5-13-g0b502b1f8
[   +5 ms] executing: [C:\flutter\] git rev-parse --abbrev-ref --symbolic @{u}
[  +24 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/master
[        ] executing: [C:\flutter\] git ls-remote --get-url origin
[  +20 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[  +51 ms] executing: [C:\flutter\] git rev-parse --abbrev-ref HEAD
[  +23 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] master
[  +77 ms] executing: C:\Users\Gareth\AppData\Local\Android\sdk\platform-tools\adb.exe devices -l
[  +15 ms] Exit code 0 from: C:\Users\Gareth\AppData\Local\Android\sdk\platform-tools\adb.exe devices -l
[        ] List of devices attached
[  +12 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[   +3 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[ +131 ms] Generating C:\App Development\Flutter\Find The Treasure
CMS\ftt_cms\android\app\src\main\java\io\flutter\plugins\GeneratedPluginRegistrant.java
[  +76 ms] Launching lib\main.dart on Chrome in debug mode...
[        ] Building application for the web...
[+5672 ms] Daemon is already running.
[ +110 ms] Serving DevTools at http://127.0.0.1:55008

[ +367 ms] About to build [web]...
[   +3 ms] Updating asset graph...
[   +3 ms] Updating asset graph completed, took 0ms

[        ] Running build...
[        ] Running build completed, took 18ms

[        ] Caching finalized dependency graph...
[   +1 ms] Caching finalized dependency graph completed, took 47ms

[   +5 ms] AssetNotFoundException: flutter|lib/src/gestures/arena.ddc.js
[   +1 ms] #0      bootstrapDdc (package:build_web_compilers/src/dev_compiler_bootstrap.dart:147:34)
           <asynchronous suspension>
           #1      FlutterWebEntrypointBuilder.build (package:flutter_tools/src/build_runner/build_script.dart:232:11)
           #2      runBuilder.buildForInput (package:build/src/generate/run_builder.dart:55:21)
           <asynchronous suspension>
           #3      MappedListIterable.elementAt (dart:_internal/iterable.dart:417:29)
           #4      ListIterator.moveNext (dart:_internal/iterable.dart:346:26)
           #5      Future.wait (dart:async/future.dart:393:26)
           #6      runBuilder.<anonymous closure> (package:build/src/generate/run_builder.dart:61:36)
           #7      _rootRun (dart:async/zone.dart:1126:13)
           #8      _CustomZone.run (dart:async/zone.dart:1023:19)
           #9      _runZoned (dart:async/zone.dart:1518:10)
           #10     runZoned (dart:async/zone.dart:1502:12)
           #11     scopeLogAsync (package:build/src/builder/logging.dart:22:3)
           #12     runBuilder (package:build/src/generate/run_builder.dart:61:9)
           <asynchronous suspension>
           #13     _SingleBuild._runForInput.<anonymous closure>.<anonymous closure>.<anonymous closure>
           (package:build_runner_core/src/generate/build_impl.dart:478:19)
           #14     _NoOpBuilderActionTracker.trackStage (package:build_runner_core/src/generate/performance_tracker.dart:300:15)       
           #15     _SingleBuild._runForInput.<anonymous closure>.<anonymous closure>
           (package:build_runner_core/src/generate/build_impl.dart:476:23)
           <asynchronous suspension>
           #16     NoOpTimeTracker.track (package:timing/src/timing.dart:222:44)
           #17     _SingleBuild._runForInput.<anonymous closure> (package:build_runner_core/src/generate/build_impl.dart:434:22)       
           #18     Pool.withResource (package:pool/pool.dart:127:28)
           <asynchronous suspension>
           #19     _SingleBuild._runForInput (package:build_runner_core/src/generate/build_impl.dart:430:17)
           #20     _SingleBuild._runBuilder.<anonymous closure> (package:build_runner_core/src/generate/build_impl.dart:378:38)        
           #21     MappedIterator.moveNext (dart:_internal/iterable.dart:395:18)
           #22     Future.wait (dart:async/future.dart:393:26)
           #23     _SingleBuild._runBuilder (package:build_runner_core/src/generate/build_impl.dart:377:36)
           #24     _SingleBuild._runPhases.<anonymous closure>.<anonymous closure>
           (package:build_runner_core/src/generate/build_impl.dart:323:20)
           <asynchronous suspension>
           #25     _NoOpBuildPerformanceTracker.trackBuildPhase
           (package:build_runner_core/src/generate/performance_tracker.dart:184:15)
           #26     _SingleBuild._runPhases.<anonymous closure> (package:build_runner_core/src/generate/build_impl.dart:319:47)
           <asynchronous suspension>
           #27     NoOpTimeTracker.track (package:timing/src/timing.dart:222:44)
           #28     _SingleBuild._runPhases (package:build_runner_core/src/generate/build_impl.dart:313:32)
           #29     logTimedAsync (package:build_runner_core/src/logging/logging.dart:25:30)
           #30     _SingleBuild._safeBuild.<anonymous closure> (package:build_runner_core/src/generate/build_impl.dart:270:26)
           <asynchronous suspension>
           #31     _rootRun (dart:async/zone.dart:1126:13)
           #32     _CustomZone.run (dart:async/zone.dart:1023:19)
           #33     _runZoned (dart:async/zone.dart:1518:10)
           #34     runZoned (dart:async/zone.dart:1502:12)
           #35     _SingleBuild._safeBuild (package:build_runner_core/src/generate/build_impl.dart:265:5)
           #36     _SingleBuild.run (package:build_runner_core/src/generate/build_impl.dart:212:24)
           #37     BuildImpl.run (package:build_runner_core/src/generate/build_impl.dart:97:56)
           #38     BuildRunnerDaemonBuilder.build (package:build_runner/src/daemon/daemon_builder.dart:111:35)
           #39     Server._build.<anonymous closure> (package:build_daemon/src/server.dart:122:25)
           #40     Pool.withResource (package:pool/pool.dart:127:28)
           <asynchronous suspension>
           #41     Server._build (package:build_daemon/src/server.dart:119:13)
           #42     Server.listen.<anonymous closure>.<anonymous closure> (package:build_daemon/src/server.dart:85:17)
           <asynchronous suspension>
           #43     _rootRunUnary (dart:async/zone.dart:1134:38)
           #44     _CustomZone.runUnary (dart:async/zone.dart:1031:19)
           #45     _CustomZone.runUnaryGuarded (dart:async/zone.dart:933:7)
           #46     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:338:11)
           #47     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:265:7)
           #48     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:766:19)
           #49     _StreamController._add (dart:async/stream_controller.dart:642:7)
           #50     _StreamController.add (dart:async/stream_controller.dart:588:5)
           #51     new WebSocketImpl.fromSocket.<anonymous closure> (package:web_socket_channel/src/copy/web_socket_impl.dart:719:21)  
           #52     _rootRunUnary (dart:async/zone.dart:1134:38)
           #53     _CustomZone.runUnary (dart:async/zone.dart:1031:19)
           #54     _CustomZone.runUnaryGuarded (dart:async/zone.dart:933:7)
           #55     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:338:11)
           #56     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:265:7)
           #57     _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:70:11)
           #58     _EventSinkWrapper.add (dart:async/stream_transformers.dart:17:11)
           #59     _WebSocketProtocolTransformer._messageFrameEnd (package:web_socket_channel/src/copy/web_socket_impl.dart:316:22)    
           #60     _WebSocketProtocolTransformer.add (package:web_socket_channel/src/copy/web_socket_impl.dart:214:46)
           #61     _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:122:24)
           #62     _rootRunUnary (dart:async/zone.dart:1134:38)
           #63     _CustomZone.runUnary (dart:async/zone.dart:1031:19)
           #64     _CustomZone.runUnaryGuarded (dart:async/zone.dart:933:7)
           #65     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:338:11)
           #66     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:265:7)
           #67     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:766:19)
           #68     _StreamController._add (dart:async/stream_controller.dart:642:7)
           #69     _StreamController.add (dart:async/stream_controller.dart:588:5)
           #70     _Socket._onData (dart:io-patch/socket_patch.dart:1831:41)
           #71     _rootRunUnary (dart:async/zone.dart:1138:13)
           #72     _CustomZone.runUnary (dart:async/zone.dart:1031:19)
           #73     _CustomZone.runUnaryGuarded (dart:async/zone.dart:933:7)
           #74     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:338:11)
           #75     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:265:7)
           #76     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:766:19)
           #77     _StreamController._add (dart:async/stream_controller.dart:642:7)
           #78     _StreamController.add (dart:async/stream_controller.dart:588:5)
           #79     new _RawSocket.<anonymous closure> (dart:io-patch/socket_patch.dart:1379:33)
           #80     _NativeSocket.issueReadEvent.issue (dart:io-patch/socket_patch.dart:899:14)
           #81     _microtaskLoop (dart:async/schedule_microtask.dart:43:21)
           #82     _startMicrotaskLoop (dart:async/schedule_microtask.dart:52:5)
           #83     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
           #84     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:175:5)

[  +19 ms] Failed after 68ms
[   +8 ms] Building application for the web... (completed in 6.2s)
[   +3 ms] "flutter run" took 6,547ms.
Failed to build application for the Web.

#0      throwToolExit (package:flutter_tools/src/base/common.dart:28:3)
#1      _DwdsResidentWebRunner.run (package:flutter_tools/src/build_runner/resident_web_runner.dart:659:7)
<asynchronous suspension>
#2      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:499:37)
<asynchronous suspension>
#3      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:600:18)
#4      _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:73:64)
#5      _rootRunUnary (dart:async/zone.dart:1134:38)
#6      _CustomZone.runUnary (dart:async/zone.dart:1031:19)
#7      _FutureListener.handleValue (dart:async/future_impl.dart:139:18)
#8      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:680:45)
#9      Future._propagateToListeners (dart:async/future_impl.dart:709:32)
#10     Future._completeWithValue (dart:async/future_impl.dart:524:5)
#11     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:32:15)
#12     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:290:13)
#13     RunCommand.usageValues (package:flutter_tools/src/commands/run.dart)
#14     _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:73:64)
#15     _rootRunUnary (dart:async/zone.dart:1134:38)
#16     _CustomZone.runUnary (dart:async/zone.dart:1031:19)
#17     _FutureListener.handleValue (dart:async/future_impl.dart:139:18)
#18     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:680:45)
#19     Future._propagateToListeners (dart:async/future_impl.dart:709:32)
#20     Future._completeWithValue (dart:async/future_impl.dart:524:5)
#21     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:32:15)
#22     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:290:13)
#23     IosProject.isSwift (package:flutter_tools/src/project.dart)
#24     _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:73:64)
#25     _rootRunUnary (dart:async/zone.dart:1134:38)
#26     _CustomZone.runUnary (dart:async/zone.dart:1031:19)
#27     _FutureListener.handleValue (dart:async/future_impl.dart:139:18)
#28     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:680:45)
#29     Future._propagateToListeners (dart:async/future_impl.dart:709:32)
#30     Future._completeWithValue (dart:async/future_impl.dart:524:5)
#31     Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:554:7)
#32     _rootRun (dart:async/zone.dart:1126:13)
#33     _CustomZone.run (dart:async/zone.dart:1023:19)
#34     _CustomZone.runGuarded (dart:async/zone.dart:925:7)
#35     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:965:23)
#36     _microtaskLoop (dart:async/schedule_microtask.dart:43:21)
#37     _startMicrotaskLoop (dart:async/schedule_microtask.dart:52:5)
#38     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
#39     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:175:5)
```

```
Nil issues found
```

```
[√] Flutter (Channel master, v1.12.6-pre.13, on Microsoft Windows [Version 10.0.18362.476], locale en-AU)
    • Flutter version 1.12.6-pre.13 at C:\flutter
    • Framework revision 0b502b1f8b (6 hours ago), 2019-11-20 22:11:51 -0500
    • Engine revision 7a77e3625d
    • Dart version 2.7.0

 
[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at C:\Users\Gareth\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 3.5)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 40.2.2
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)

[√] VS Code (version 1.40.1)
    • VS Code at C:\Users\Gareth\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.6.0

[√] Connected device (2 available)
    • Chrome     • chrome     • web-javascript • Google Chrome 78.0.3904.97
    • Web Server • web-server • web-javascript • Flutter Tools

• No issues found!
```

**Comment by FindtheTreasure** [comment]
Downgrading to v1.12.5 fixed the issue

**Comment by jonahwilliams** [comment]
@FindtheTreasure can you consistently reproduce the issue on a particular version? If so, can you create a minimal sample that reproduces the issue?
