### ISSUE TITLE
image cropper issue

### ISSUE THREAD

**Issue by Dhanush623** [flutter/flutter#45352]
Flutter crash report; please file at https://github.com/flutter/flutter/issues.

## command

flutter build apk --release

## exception

ProcessException: ProcessException: Permission denied
  Command: /home/atribs/Home/flutter/.pub-cache/hosted/pub.dartlang.org/image_cropper-1.1.0/android/gradlew -I=/home/atribs/Home/flutter/packages/flutter_tools/gradle/aar_init_script.gradle -Pflutter-root=/home/atribs/Home/flutter -Poutput-dir=/home/atribs/Home/WorkSpace/Flutter/empolyee_atribs/build/app -Pis-plugin=true -Ptarget-platform=android-arm,android-arm64,android-x64 assembleAarRelease

```
#0      _DefaultProcessUtils.run (package:flutter_tools/src/base/process.dart:266:37)
<asynchronous suspension>
#1      buildGradleAar (package:flutter_tools/src/android/gradle.dart:542:33)
<asynchronous suspension>
#2      buildPluginsAsAar (package:flutter_tools/src/android/gradle.dart:690:13)
<asynchronous suspension>
#3      buildGradleApp (package:flutter_tools/src/android/gradle.dart:258:11)
#4      _AsyncAwaitCompleter.start (dart:async-patch/async_patch.dart:43:6)
#5      buildGradleApp (package:flutter_tools/src/android/gradle.dart:219:28)
#6      buildGradleApp (package:flutter_tools/src/android/gradle.dart:407:19)
#7      _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:71:64)
#8      _rootRunUnary (dart:async/zone.dart:1132:38)
#9      _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#10     _FutureListener.handleValue (dart:async/future_impl.dart:137:18)
#11     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:678:45)
#12     Future._propagateToListeners (dart:async/future_impl.dart:707:32)
#13     Future._completeWithValue (dart:async/future_impl.dart:522:5)
#14     Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:552:7)
#15     _rootRun (dart:async/zone.dart:1124:13)
#16     _CustomZone.run (dart:async/zone.dart:1021:19)
#17     _CustomZone.runGuarded (dart:async/zone.dart:923:7)
#18     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:963:23)
#19     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#20     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#21     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:116:13)
#22     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:173:5)
```

## flutter doctor

```
[32m[✓][39m Flutter (Channel master, v1.10.16-pre.113, on Linux, locale en_GB.UTF-8)
    [32m•[39m Flutter version 1.10.16-pre.113 at /home/atribs/Home/flutter
    [32m•[39m Framework revision e7073f9a1f (12 days ago), 2019-11-09 17:08:53 -0800
    [32m•[39m Engine revision 31cd2dfca2
    [32m•[39m Dart version 2.7.0

[32m[✓][39m Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    [32m•[39m Android SDK at /home/atribs/Android/Sdk
    [32m•[39m Android NDK location not configured (optional; useful for native profiling support)
    [32m•[39m Platform android-29, build-tools 28.0.3
    [32m•[39m ANDROID_HOME = /home/atribs/Android/Sdk
    [32m•[39m Java binary at: /home/atribs/Home/android-studio-ide-183.5452501-linux/android-studio/jre/bin/java
    [32m•[39m Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b16-5323222)
    [32m•[39m All Android licenses accepted.

[32m[✓][39m Chrome - develop for the web
    [32m•[39m Chrome at google-chrome

[32m[✓][39m Android Studio (version 3.4)
    [32m•[39m Android Studio at /home/atribs/Home/android-studio-ide-183.5452501-linux/android-studio
    [32m•[39m Flutter plugin version 37.0.1
    [32m•[39m Dart plugin version 183.6270
    [32m•[39m Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b16-5323222)

[32m[✓][39m VS Code (version 1.39.2)
    [32m•[39m VS Code at /usr/share/code
    [32m•[39m Flutter extension version 3.6.0

[32m[✓][39m Connected device (2 available)
    [32m•[39m Chrome     • chrome     • web-javascript • Google Chrome 78.0.3904.87
    [32m•[39m Web Server • web-server • web-javascript • Flutter Tools

[32m•[39m No issues found!
```

**Comment by Hixie** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
  
Thanks for your contribution.
