### ISSUE TITLE
[image_picker] gifs from image_picker lose animation property

### ISSUE THREAD

**Issue by glennWang** [flutter/flutter#45388]
As the title say.

This gif can be used to test
https://n.sinaimg.cn/tech/transform/538/w344h194/20191121/afce-iipztff9620974.gif

The error is the followings:
```
D/ImageResizer: image_picker: compressing is not supported for type PNG. Returning the image with original quality
E/ExifDataCopier: Error preserving Exif data on selected image: java.io.IOException: ExifInterface only supports saving attributes on JPEG formats.
```

Using the latest version:
```
  image_picker: ^0.6.2+1
  video_player: ^0.10.3+1
```

And my env is :

```
[✓] Flutter (Channel stable, v1.9.1+hotfix.6, on Mac OS X 10.15.1 19B88, locale zh-Hans-CN)
    • Flutter version 1.9.1+hotfix.6 at /Users/glenn/depend/flutter/flutter
    • Framework revision 68587a0916 (10 weeks ago), 2019-09-13 19:46:58 -0700
    • Engine revision b863200c37
    • Dart version 2.5.0


[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/glenn/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • ANDROID_HOME = /Users/glenn/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.2.1, Build version 11B500
    • CocoaPods version 1.8.4

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 41.1.2
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] IntelliJ IDEA Ultimate Edition (version 2019.2.4)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 41.1.4
    • Dart plugin version 192.7761

[✓] VS Code (version 1.40.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.6.0

[✓] Connected device (1 available)
    • MI 5X • 902a97930604 • android-arm64 • Android 8.1.0 (API 27)

• No issues found!
```

**Comment by iapicca** [comment]
Hi @glennWang 
I believe the problem is within your `gif` 's `url` 

I tried a random gif using your same version and works just fine
<details>
  <summary>sample</summary>

```
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) => MaterialApp(
    home: MyHomePage(),
  );
}

class MyHomePage extends StatefulWidget {
  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {

  static const _url = 'https://media.giphy.com/media/5NPhdqmyRxn8I/giphy.gif';

  @override
  Widget build(BuildContext context)=> Scaffold(
    body: Center(
      child: Image.network(_url),
    ),
  );
}
```
```
[√] Flutter (Channel stable, v1.9.1+hotfix.6, on Microsoft Windows [Version 10.0.19013.1122], locale en-US)
    • Flutter version 1.9.1+hotfix.6 at C:\src\flutter
    • Framework revision 68587a0916 (10 weeks ago), 2019-09-13 19:46:58 -0700
    • Engine revision b863200c37
    • Dart version 2.5.0

 
[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at C:\Users\iapic\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)        
    • All Android licenses accepted.

[√] Android Studio (version 3.5)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 41.1.2
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)        

[√] VS Code, 64-bit edition (version 1.40.1)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Flutter extension version 3.6.0

[√] Connected device (1 available)
    • Pixel 3a • 965AY0WP5C • android-arm64 • Android 10 (API 29)

• No issues found!
```

</details>

are you experiencing this issue with other gif's?
thank you

**Comment by glennWang** [comment]
To be clear, my proble is that:

Firstly , I download the gif file into my Android phone.

Then, I use your image_picker plugin example pick the gif file.

The result is that , the image is displayed on screen, but lossing animation meanwhile, and has the error abrove.

**Comment by iapicca** [comment]
HI again @glennWang 
I apologize for the misunderstanding,
thank for the clarification

**Comment by ozzy1873** [comment]
The version 0.6.0+17 seems to work ok, but any later version I've tried loses animation.
I break out in a cold sweat everytime I have to touch this control :(

**Comment by huntrist** [comment]
same issue
when picking gif from gallery, will have following error:
```
W/ExifInterface(25424): Invalid image: ExifInterface got an unsupported image format file(ExifInterface supports JPEG and some RAW image formats only) or a corrupted JPEG file to ExifInterface.
W/ExifInterface(25424): java.io.IOException: Invalid byte order: 4749
W/ExifInterface(25424): 	at io.flutter.plugins.imagepicker.ImagePickerDelegate.handleImageResult(ImagePickerDelegate.java:527)
W/ExifInterface(25424): 	at io.flutter.plugins.imagepicker.ImagePickerDelegate.handleChooseImageResult(ImagePickerDelegate.java:463)
W/ExifInterface(25424): 	at io.flutter.plugins.imagepicker.ImagePickerDelegate.onActivityResult(ImagePickerDelegate.java:442)
W/ExifInterface(25424): 	at io.flutter.app.FlutterPluginRegistry.onActivityResult(FlutterPluginRegistry.java:204)
W/ExifInterface(25424): 	at io.flutter.app.FlutterActivityDelegate.onActivityResult(FlutterActivityDelegate.java:132)
W/ExifInterface(25424): 	at io.flutter.app.FlutterActivity.onActivityResult(FlutterActivity.java:142)
W/ExifInterface(25424): 	at android.app.Activity.dispatchActivityResult(Activity.java:8110)
W/ExifInterface(25424): 	at android.app.ActivityThread.deliverResults(ActivityThread.java:4838)
W/ExifInterface(25424): 	at android.app.ActivityThread.handleSendResult(ActivityThread.java:4886)
W/ExifInterface(25424): 	at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:51)
W/ExifInterface(25424): 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
W/ExifInterface(25424): 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
W/ExifInterface(25424): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2016)
W/ExifInterface(25424): 	at android.os.Handler.dispatchMessage(Handler.java:107)
W/ExifInterface(25424): 	at android.os.Looper.loop(Looper.java:214)
W/ExifInterface(25424): 	at android.app.ActivityThread.main(ActivityThread.java:7356)
W/ExifInterface(25424): 	at java.lang.reflect.Method.invoke(Native Method)
W/ExifInterface(25424): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
W/ExifInterface(25424): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
```

flutter doctor:
```
[√] Flutter (Channel stable, v1.9.1+hotfix.6, on Microsoft Windows [Version 10.0.18362.476], locale zh-CN)
    • Flutter version 1.9.1+hotfix.6 at D:\Env\flutter
    • Framework revision 68587a0916 (3 months ago), 2019-09-13 19:46:58 -0700
    • Engine revision b863200c37
    • Dart version 2.5.0

 
[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at D:\Env\Android\SDK
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • ANDROID_HOME = D:\Env\Android\SDK
    • Java binary at: D:\Executable\Android\AndroidStudio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)
    • All Android licenses accepted.

[√] Android Studio (version 3.5)
    • Android Studio at D:\Executable\Android\AndroidStudio
    • Flutter plugin version 40.1.2
    • Dart plugin version 191.8423
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)

[√] Connected device (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 10 (API 29) (emulator)
```

**Comment by Ahmadre** [comment]
I am using the actual ```0.6.2+3``` version and my GIFS are working without any problems 👍

**Comment by glennWang** [comment]
> I am using the actual `0.6.2+3` version and I am also picking images via `image_picker` and my GIFS are working without any problems 👍

What is your platform ?
iOS or Android ？

**Comment by Ahmadre** [comment]
@glennWang both! It works on all of my costumers mobile devices

**Comment by TahaTesser** [comment]
Hi @glennWang 
Please check this [comment](https://github.com/flutter/flutter/issues/45388#issuecomment-573918305)
if you're still experiencing this problem, please create a new issue and provide the information required in the template.
Thank you
