### ISSUE TITLE
[VideoPlayer Plugin] java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.String.endsWith(java.lang.String)' on a null object reference 

### ISSUE THREAD

**Issue by shriharip** [flutter/flutter#45428]
## Steps to Reproduce

1.  Have VideoPlayer dependency in your pubspec file ( Mine is video_player: ^0.10.3+1) 
2. https://gist.github.com/shriharip/d2113fd4eab1a922919c281a903d759d
![Screenshot_1574460199](https://user-images.githubusercontent.com/3909110/69463606-54eac800-0d7c-11ea-9466-8470de4a5bd9.png)

3.

**Target Platform:**
Android emulator

**Devices:**
not tested on real devices

## Logs

```
 Restarted application in 1,839ms.
I/ExoPlayerImpl( 5495): Release 8fda49b [ExoPlayerLib/2.9.6] [generic_x86, Android SDK built for x86, Google, 27] [goog.exo.core]
D/SurfaceUtils( 5495): disconnecting from surface 0x8618b808, reason disconnectFromSurface
I/ExoPlayerImpl( 5495): Release 210bbdc [ExoPlayerLib/2.9.6] [generic_x86, Android SDK built for x86, Google, 27] [goog.exo.core]
I/ExoPlayerImpl( 5495): Release eedf9e0 [ExoPlayerLib/2.9.6] [generic_x86, Android SDK built for x86, Google, 27] [goog.exo.core]
D/SurfaceUtils( 5495): disconnecting from surface 0x70579008, reason disconnectFromSurface
I/ExoPlayerImpl( 5495): Release 785ac3b [ExoPlayerLib/2.9.6] [generic_x86, Android SDK built for x86, Google, 27] [goog.exo.core]
I/ExoPlayerImpl( 5495): Release 53a49c [ExoPlayerLib/2.9.6] [generic_x86, Android SDK built for x86, Google, 27] [goog.exo.core]
I/ExoPlayerImpl( 5495): Release 1a3a3 [ExoPlayerLib/2.9.6] [generic_x86, Android SDK built for x86, Google, 27] [goog.exo.core]
I/ExoPlayerImpl( 5495): Release 5b2d7d0 [ExoPlayerLib/2.9.6] [generic_x86, Android SDK built for x86, Google, 27] [goog.exo.core]
D/SurfaceUtils( 5495): disconnecting from surface 0x786fd008, reason disconnectFromSurface
I/ExoPlayerImpl( 5495): Release b2769eb [ExoPlayerLib/2.9.6] [generic_x86, Android SDK built for x86, Google, 27] [goog.exo.core]
I/ExoPlayerImpl( 5495): Init 7c8f4d5 [ExoPlayerLib/2.9.6] [generic_x86, Android SDK built for x86, Google, 27]
I/ExoPlayerImpl( 5495): Init 7e6ae78 [ExoPlayerLib/2.9.6] [generic_x86, Android SDK built for x86, Google, 27]
E/MethodChannel#flutter.io/videoPlayer( 5495): Failed to handle method call
E/MethodChannel#flutter.io/videoPlayer( 5495): java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.String.endsWith(java.lang.String)' on a null object reference
E/MethodChannel#flutter.io/videoPlayer( 5495): 	at com.google.android.exoplayer2.util.Util.inferContentType(Util.java:1406)
E/MethodChannel#flutter.io/videoPlayer( 5495): 	at io.flutter.plugins.videoplayer.VideoPlayer.buildMediaSource(VideoPlayer.java:106)
E/MethodChannel#flutter.io/videoPlayer( 5495): 	at io.flutter.plugins.videoplayer.VideoPlayer.<init>(VideoPlayer.java:88)
E/MethodChannel#flutter.io/videoPlayer( 5495): 	at io.flutter.plugins.videoplayer.VideoPlayerPlugin.onMethodCall(VideoPlayerPlugin.java:133)
E/MethodChannel#flutter.io/videoPlayer( 5495): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:231)
E/MethodChannel#flutter.io/videoPlayer( 5495): 	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:93)
E/MethodChannel#flutter.io/videoPlayer( 5495): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:642)
E/MethodChannel#flutter.io/videoPlayer( 5495): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/MethodChannel#flutter.io/videoPlayer( 5495): 	at android.os.MessageQueue.next(MessageQueue.java:325)
E/MethodChannel#flutter.io/videoPlayer( 5495): 	at android.os.Looper.loop(Looper.java:142)
E/MethodChannel#flutter.io/videoPlayer( 5495): 	at android.app.ActivityThread.main(ActivityThread.java:6494)
E/MethodChannel#flutter.io/videoPlayer( 5495): 	at java.lang.reflect.Method.invoke(Native Method)
E/MethodChannel#flutter.io/videoPlayer( 5495): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
E/MethodChannel#flutter.io/videoPlayer( 5495): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
I/ExoPlayerImpl( 5495): Init e5dd5b6 [ExoPlayerLib/2.9.6] [generic_x86, Android SDK built for x86, Google, 27]
E/MethodChannel#flutter.io/videoPlayer( 5495): Failed to handle method call
E/MethodChannel#flutter.io/videoPlayer( 5495): java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.String.endsWith(java.lang.String)' on a null object reference
E/MethodChannel#flutter.io/videoPlayer( 5495): 	at com.google.android.exoplayer2.util.Util.inferContentType(Util.java:1406)
E/MethodChannel#flutter.io/videoPlayer( 5495): 	at io.flutter.plugins.videoplayer.VideoPlayer.buildMediaSource(VideoPlayer.java:106)
E/MethodChannel#flutter.io/videoPlayer( 5495): 	at io.flutter.plugins.videoplayer.VideoPlayer.<init>(VideoPlayer.java:88)
E/MethodChannel#flutter.io/videoPlayer( 5495): 	at io.flutter.plugins.videoplayer.VideoPlayerPlugin.onMethodCall(VideoPlayerPlugin.java:133)
E/MethodChannel#flutter.io/videoPlayer( 5495): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:231)
E/MethodChannel#flutter.io/videoPlayer( 5495): 	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:93)
E/MethodChannel#flutter.io/videoPlayer( 5495): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:642)
E/MethodChannel#flutter.io/videoPlayer( 5495): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/MethodChannel#flutter.io/videoPlayer( 5495): 	at android.os.MessageQueue.next(MessageQueue.java:325)
E/MethodChannel#flutter.io/videoPlayer( 5495): 	at android.os.Looper.loop(Looper.java:142)
E/MethodChannel#flutter.io/videoPlayer( 5495): 	at android.app.ActivityThread.main(ActivityThread.java:6494)
E/MethodChannel#flutter.io/videoPlayer( 5495): 	at java.lang.reflect.Method.invoke(Native Method)
E/MethodChannel#flutter.io/videoPlayer( 5495): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
E/MethodChannel#flutter.io/videoPlayer( 5495): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
E/flutter ( 5495): [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: PlatformException(error, Attempt to invoke virtual method 'boolean java.lang.String.endsWith(java.lang.String)' on a null object reference, null)
E/flutter ( 5495): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:569:7)
E/flutter ( 5495): #1      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:321:33)
E/flutter ( 5495): <asynchronous suspension>
E/flutter ( 5495): #2      MethodChannel.invokeMapMethod (package:flutter/src/services/platform_channel.dart:349:48)
E/flutter ( 5495): #3      VideoPlayerController.initialize (package:video_player/video_player.dart:220:24)
E/flutter ( 5495): #4      _NewsListFollowingState.videoInit (package:minlandsby/ui/pages/news/widgets/newsListFollowing.dart:51:9)
E/flutter ( 5495): #5      _NewsListFollowingState.buildList.<anonymous closure> (package:minlandsby/ui/pages/news/widgets/newsListFollowing.dart:102:9)
E/flutter ( 5495): #6      SliverChildBuilderDelegate.build (package:flutter/src/widgets/sliver.dart:446:15)
E/flutter ( 5495): #7      SliverMultiBoxAdaptorElement._build.<anonymous closure> (package:flutter/src/widgets/sliver.dart:1161:67)
E/flutter ( 5495): #8      _HashMap.putIfAbsent (dart:collection-patch/collection_patch.dart:139:29)
E/flutter ( 5495): #9      SliverMultiBoxAdaptorElement._build (package:flutter/src/widgets/sliver.dart:1161:26)
E/flutter ( 5495): #10     SliverMultiBoxAdaptorElement.createChild.<anonymous closure> (package:flutter/src/widgets/sliver.dart:1174:55)
E/flutter ( 5495): #11     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2327:19)
E/flutter ( 5495): #12     SliverMultiBoxAdaptorElement.createChild (package:flutter/src/widgets/sliver.dart:1167:11)
E/flutter ( 5495): #13     RenderSliverMultiBoxAdaptor._createOrObtainChild.<anonymous closure> (package:flutter/src/rendering/sliver_multi_box_adaptor.dart:354:23)
E/flutter ( 5495): #14     RenderObject.invokeLayoutCallback.<anonymous closure> (package:flutter/src/rendering/object.dart:1823:58)
E/flutter ( 5495): #15     PipelineOwner._enableMutationsToDirtySubtrees (package:flutter/src/rendering/object.dart:875:15)
E/flutter ( 5495): #16     RenderObject.invokeLayoutCallback (package:flutter/src/rendering/object.dart:1823:13)
E/flutter ( 5495): #17     RenderSliverMultiBoxAdaptor._createOrObtainChild (package:flutter/src/rendering/sliver_multi_box_adaptor.dart:343:5)
E/flutter ( 5495): #18     RenderSliverMultiBoxAdaptor.insertAndLayoutChild (package:flutter/src/rendering/sliver_multi_box_adaptor.dart:489:5)
E/flutter ( 5495): #19     RenderSliverList.performLayout.advance (package:flutter/src/rendering/sliver_list.dart:195:19)
E/flutter ( 5495): #20     RenderSliverList.performLayout (package:flutter/src/rendering/sliver_list.dart:238:19)
E/flutter ( 5495): #21     RenderObject.layout (package:flutter/src/rendering/object.dart:1724:7)
E/flutter ( 5495): #22     RenderSliverPadding.performLayout (package:flutter/src/rendering/sliver_padding.dart:181:11)
E/flutter ( 5495): #23     RenderObject.layout (package:flutter/src/rendering/object.dart:1724:7)
E/flutter ( 5495): #24     RenderViewportBase.layoutChildSequence (package:flutter/src/rendering/viewport.dart:410:13)
E/flutter ( 5495): #25     RenderViewport._attemptLayout (package:flutter/src/rendering/viewport.dart:1367:12)
E/flutter ( 5495): #26     RenderViewport.performLayout (package:flutter/src/rendering/viewport.dart:1285:20)
E/flutter ( 5495): #27     RenderObject.layout (package:flutter/src/rendering/object.dart:1724:7)
E/flutter ( 5495): #28     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
E/flutter ( 5495): #29     RenderObject.layout (package:flutter/src/rendering/object.dart:1724:7)
E/flutter ( 5495): #30     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
E/flutter ( 5495): #31     RenderObject.layout (package:flutter/src/rendering/object.dart:1724:7)
E/flutter ( 5495): #32     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
E/flutter ( 5495): #33     RenderObject.layout (package:flutter/src/rendering/object.dart:1724:7)
E/flutter ( 5495): #34     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
E/flutter ( 5495): #35     RenderObject.layout (package:flutter/src/rendering/object.dart:1724:7)
E/flutter ( 5495): #36     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
E/flutter ( 5495): #37     RenderObject.layout (package:flutter/src/rendering/object.dart:1724:7)
E/flutter ( 5495): #38     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
E/flutter ( 5495): #39     Ren
E/flutter ( 5495): [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: PlatformException(error, Attempt to invoke virtual method 'boolean java.lang.String.endsWith(java.lang.String)' on a null object reference, null)
E/flutter ( 5495): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:569:7)
E/flutter ( 5495): #1      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:321:33)
E/flutter ( 5495): <asynchronous suspension>
E/flutter ( 5495): #2      MethodChannel.invokeMapMethod (package:flutter/src/services/platform_channel.dart:349:48)
E/flutter ( 5495): #3      VideoPlayerController.initialize (package:video_player/video_player.dart:220:24)
E/flutter ( 5495): #4      _NewsListFollowingState.videoInit (package:minlandsby/ui/pages/news/widgets/newsListFollowing.dart:51:9)
E/flutter ( 5495): #5      _NewsListFollowingState.buildList.<anonymous closure> (package:minlandsby/ui/pages/news/widgets/newsListFollowing.dart:102:9)
E/flutter ( 5495): #6      SliverChildBuilderDelegate.build (package:flutter/src/widgets/sliver.dart:446:15)
E/flutter ( 5495): #7      SliverMultiBoxAdaptorElement._build.<anonymous closure> (package:flutter/src/widgets/sliver.dart:1161:67)
E/flutter ( 5495): #8      _HashMap.putIfAbsent (dart:collection-patch/collection_patch.dart:139:29)
E/flutter ( 5495): #9      SliverMultiBoxAdaptorElement._build (package:flutter/src/widgets/sliver.dart:1161:26)
E/flutter ( 5495): #10     SliverMultiBoxAdaptorElement.createChild.<anonymous closure> (package:flutter/src/widgets/sliver.dart:1174:55)
E/flutter ( 5495): #11     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2327:19)
E/flutter ( 5495): #12     SliverMultiBoxAdaptorElement.createChild (package:flutter/src/widgets/sliver.dart:1167:11)
E/flutter ( 5495): #13     RenderSliverMultiBoxAdaptor._createOrObtainChild.<anonymous closure> (package:flutter/src/rendering/sliver_multi_box_adaptor.dart:354:23)
E/flutter ( 5495): #14     RenderObject.invokeLayoutCallback.<anonymous closure> (package:flutter/src/rendering/object.dart:1823:58)
E/flutter ( 5495): #15     PipelineOwner._enableMutationsToDirtySubtrees (package:flutter/src/rendering/object.dart:875:15)
E/flutter ( 5495): #16     RenderObject.invokeLayoutCallback (package:flutter/src/rendering/object.dart:1823:13)
E/flutter ( 5495): #17     RenderSliverMultiBoxAdaptor._createOrObtainChild (package:flutter/src/rendering/sliver_multi_box_adaptor.dart:343:5)
E/flutter ( 5495): #18     RenderSliverMultiBoxAdaptor.insertAndLayoutChild (package:flutter/src/rendering/sliver_multi_box_adaptor.dart:489:5)
E/flutter ( 5495): #19     RenderSliverList.performLayout.advance (package:flutter/src/rendering/sliver_list.dart:195:19)
E/flutter ( 5495): #20     RenderSliverList.performLayout (package:flutter/src/rendering/sliver_list.dart:238:19)
E/flutter ( 5495): #21     RenderObject.layout (package:flutter/src/rendering/object.dart:1724:7)
E/flutter ( 5495): #22     RenderSliverPadding.performLayout (package:flutter/src/rendering/sliver_padding.dart:181:11)
E/flutter ( 5495): #23     RenderObject.layout (package:flutter/src/rendering/object.dart:1724:7)
E/flutter ( 5495): #24     RenderViewportBase.layoutChildSequence (package:flutter/src/rendering/viewport.dart:410:13)
E/flutter ( 5495): #25     RenderViewport._attemptLayout (package:flutter/src/rendering/viewport.dart:1367:12)
E/flutter ( 5495): #26     RenderViewport.performLayout (package:flutter/src/rendering/viewport.dart:1285:20)
E/flutter ( 5495): #27     RenderObject.layout (package:flutter/src/rendering/object.dart:1724:7)
E/flutter ( 5495): #28     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
E/flutter ( 5495): #29     RenderObject.layout (package:flutter/src/rendering/object.dart:1724:7)
E/flutter ( 5495): #30     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
E/flutter ( 5495): #31     RenderObject.layout (package:flutter/src/rendering/object.dart:1724:7)
E/flutter ( 5495): #32     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
E/flutter ( 5495): #33     RenderObject.layout (package:flutter/src/rendering/object.dart:1724:7)
E/flutter ( 5495): #34     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
E/flutter ( 5495): #35     RenderObject.layout (package:flutter/src/rendering/object.dart:1724:7)
E/flutter ( 5495): #36     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
E/flutter ( 5495): #37     RenderObject.layout (package:flutter/src/rendering/object.dart:1724:7)
E/flutter ( 5495): #38     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
E/flutter ( 5495): #39     Ren
I/OMXClient( 5495): Treble IOmx obtained
D/SurfaceUtils( 5495): connecting to surface 0x84ec2008, reason connectToSurface
I/MediaCodec( 5495): [OMX.google.h264.decoder] setting surface generation to 5626884
D/SurfaceUtils( 5495): disconnecting from surface 0x84ec2008, reason connectToSurface(reconnect)
D/SurfaceUtils( 5495): connecting to surface 0x84ec2008, reason connectToSurface(reconnect)
E/ACodec  ( 5495): [OMX.google.h264.decoder] setPortMode on output to DynamicANWBuffer failed w/ err -1010
I/ACodec  ( 5495): codec does not support config priority (err -1010)
I/OMXClient( 5495): Treble IOmx obtained
I/ACodec  ( 5495): codec does not support config priority (err -2147483648)
I/ACodec  ( 5495): codec does not support config operating rate (err -2147483648)
D/AudioTrack( 5495): Client defaulted notificationFrames to 6000 for frameCount 12000
D/MediaCodec( 5495): [OMX.google.h264.decoder] setting dataspace on output surface to #104
W/GrallocMapperPassthrough( 5495): buffer descriptor with invalid usage bits 0x2000
D/        ( 5495): HostConnection::get() New Host Connection established 0x84edd8c0, tid 6202
D/SoftwareRenderer( 5495): setting dataspace on output surface to #104
I/flutter ( 5495): inside the videoInit false
I/ExoPlayerImpl( 5495): Init 5f4ce3e [ExoPlayerLib/2.9.6] [generic_x86, Android SDK built for x86, Google, 27]
I/ExoPlayerImpl( 5495): Init 8d581b5 [ExoPlayerLib/2.9.6] [generic_x86, Android SDK built for x86, Google, 27]
E/MethodChannel#flutter.io/videoPlayer( 5495): F


```

```
```

```
[✓] Flutter (Channel dev, v1.12.6, on Mac OS X 10.14.6 18G103, locale en-DK)
    • Flutter version 1.12.6 at /Users/hari/flutter
    • Framework revision 6eb0a0e371 (2 days ago), 2019-11-20 20:18:51 -0500
    • Engine revision 6bf311f1d6
    • Dart version 2.7.0

 
[!] Android toolchain - develop for Android devices (Android SDK version 29.0.1)
    • Android SDK at /Users/hari/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.1
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses

[✓] Xcode - develop for iOS and macOS (Xcode 10.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.3, Build version 10G8
    • CocoaPods version 1.7.5

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 41.0.2
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] VS Code (version 1.40.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.6.0

[✓] Connected device (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 8.1.0 (API 27) (emulator)


```

I have had this issue for long. Since it is an important feature in app I tried to shift to channel dev. but still facing issues.

**Comment by shriharip** [comment]
It had to do with the way I was initializing. Closing this issue.

**Comment by stevanus1997** [comment]
i have some problem with u, can u tell me how i can resolve that?
