### ISSUE TITLE
Intellij Flutter plugin not installed; this adds Flutter specific functionality.

### ISSUE THREAD

**Issue by guqh** [flutter/flutter#45528]
Flutter crash report; please file at https://github.com/flutter/flutter/issues.

## command

flutter doctor

## exception

FileSystemException: FileSystemException: Cannot delete file, path = 'D:\Android\flutter\bin\cache\downloads\storage.flutter-io.cn\flutter_infra\flutter\af04338413c3ed73316350f64248a152433073b6\flutter_patched_sdk_product.zip' (OS Error: 另一个程序正在使用此文件，进程无法访问。
, errno = 32)

```
#0      _File.throwIfError (dart:io/file_impl.dart:643:7)
#1      _File._deleteSync (dart:io/file_impl.dart:306:5)
#2      FileSystemEntity.deleteSync (dart:io/file_system_entity.dart:464:47)
#3      ForwardingFileSystemEntity.deleteSync (package:file/src/forwarding/forwarding_file_system_entity.dart:72:16)
#4      CachedArtifact._removeDownloadedFiles (package:flutter_tools/src/cache.dart:469:9)
#5      CachedArtifact.update (package:flutter_tools/src/cache.dart:463:5)
<asynchronous suspension>
#6      Cache.updateAll (package:flutter_tools/src/cache.dart:360:24)
<asynchronous suspension>
#7      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:536:19)
<asynchronous suspension>
#8      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:456:33)
<asynchronous suspension>
#9      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:146:29)
<asynchronous suspension>
#10     _rootRun (dart:async/zone.dart:1124:13)
#11     _CustomZone.run (dart:async/zone.dart:1021:19)
#12     _runZoned (dart:async/zone.dart:1516:10)
#13     runZoned (dart:async/zone.dart:1463:12)
#14     AppContext.run (package:flutter_tools/src/base/context.dart:145:18)
<asynchronous suspension>
#15     FlutterCommand.run (package:flutter_tools/src/runner/flutter_command.dart:446:20)
#16     CommandRunner.runCommand (package:args/command_runner.dart:197:27)
<asynchronous suspension>
#17     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:416:21)
<asynchronous suspension>
#18     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:146:29)
<asynchronous suspension>
#19     _rootRun (dart:async/zone.dart:1124:13)
#20     _CustomZone.run (dart:async/zone.dart:1021:19)
#21     _runZoned (dart:async/zone.dart:1516:10)
#22     runZoned (dart:async/zone.dart:1463:12)
#23     AppContext.run (package:flutter_tools/src/base/context.dart:145:18)
<asynchronous suspension>
#24     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:367:19)
<asynchronous suspension>
#25     CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:112:25)
#26     new Future.sync (dart:async/future.dart:222:31)
#27     CommandRunner.run (package:args/command_runner.dart:112:14)
#28     FlutterCommandRunner.run (package:flutter_tools/src/runner/flutter_command_runner.dart:251:18)
#29     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:63:22)
<asynchronous suspension>
#30     _rootRun (dart:async/zone.dart:1124:13)
#31     _CustomZone.run (dart:async/zone.dart:1021:19)
#32     _runZoned (dart:async/zone.dart:1516:10)
#33     runZoned (dart:async/zone.dart:1500:12)
#34     run.<anonymous closure> (package:flutter_tools/runner.dart:61:18)
<asynchronous suspension>
#35     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:146:29)
<asynchronous suspension>
#36     _rootRun (dart:async/zone.dart:1124:13)
#37     _CustomZone.run (dart:async/zone.dart:1021:19)
#38     _runZoned (dart:async/zone.dart:1516:10)
#39     runZoned (dart:async/zone.dart:1463:12)
#40     AppContext.run (package:flutter_tools/src/base/context.dart:145:18)
<asynchronous suspension>
#41     runInContext (package:flutter_tools/src/context_runner.dart:65:24)
<asynchronous suspension>
#42     run (package:flutter_tools/runner.dart:50:10)
#43     main (package:flutter_tools/executable.dart:65:9)
<asynchronous suspension>
#44     main (file:///D:/Android/flutter/packages/flutter_tools/bin/flutter_tools.dart:8:3)
#45     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:303:32)
#46     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:12)
```

## flutter doctor

```
[32m[✓][39m Flutter (Channel beta, v1.11.0, on Microsoft Windows [Version 10.0.17763.864], locale zh-CN)
    [32m•[39m Flutter version 1.11.0 at D:\Android\flutter
    [32m•[39m Framework revision 856a90e67c (2 weeks ago), 2019-11-08 18:00:01 -0800
    [32m•[39m Engine revision af04338413
    [32m•[39m Dart version 2.7.0

[32m[✓][39m Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    [32m•[39m Android SDK at D:\Android\Android Sdk
    [32m•[39m Android NDK location not configured (optional; useful for native profiling support)
    [32m•[39m Platform android-29, build-tools 29.0.2
    [32m•[39m ANDROID_HOME = D:\Android\Android Sdk
    [32m•[39m Java binary at: D:\Android\Android Studio\jre\bin\java
    [32m•[39m Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)
    [32m•[39m All Android licenses accepted.

[32m[✓][39m Android Studio (version 3.5)
    [32m•[39m Android Studio at D:\Android\Android Studio
    [32m•[39m Flutter plugin version 41.1.2
    [32m•[39m Dart plugin version 191.8593
    [32m•[39m Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)

[33m[!][39m IntelliJ IDEA Ultimate Edition (version 2018.3)
    [32m•[39m IntelliJ at D:\Android\idea
    [31m✗[39m Flutter plugin not installed; this adds Flutter specific functionality.
    [31m✗[39m Dart plugin not installed; this adds Dart specific functionality.
    [32m•[39m For information about installing plugins, see
      https://flutter.dev/intellij-setup/#installing-the-plugins

[32m[✓][39m Connected device (1 available)
    [32m•[39m D3 • NJD3X505191200042 • android-arm • Android 7.1.2 (API 25)

[33m![39m Doctor found issues in 1 category.
```

**Comment by guqh** [comment]
![image](https://user-images.githubusercontent.com/17330238/69524886-ff900000-0fa1-11ea-89d5-7f6081a00192.png)

**Comment by iapicca** [comment]
Hi @guqh 
the warnings you reported in the title 

`X Flutter plugin not installed; this adds Flutter specific functionality. X Dart plugin not installed; this adds Dart specific functionality.`

are referred to  Intellij's plugins for [dart ](https://plugins.jetbrains.com/plugin/6351-dart/) and [flutter](https://plugins.jetbrains.com/plugin/9212-flutter)

but the error reported in your issue appears to be unrelated

```
FileSystemException: FileSystemException: Cannot delete file, path = 'D:\Android\flutter\bin\cache\downloads\storage.flutter-io.cn\flutter_infra\flutter\af04338413c3ed73316350f64248a152433073b6\flutter_patched_sdk_product.zip' (OS Error: 另一个程序正在使用此文件，进程无法访问。
, errno = 32)
```
the error translates in  `Another program is using this file and the process is inaccessible.`
it's possible that you tried to build, run or perform some other command while
another operation was still in progress, possible from the IDE.

You may want to install the plugins  I have linked 
and try to use perform one command at the time.

Let me know if this solves your issue.
thank you

**Comment by guqh** [comment]
![image](https://user-images.githubusercontent.com/17330238/69589227-5dfec200-1026-11ea-8879-b8aea3788311.png)


The plug-in has been installed, but it still has the same problem

**Comment by guqh** [comment]
I can change the channel to stable
It's no problem

**Comment by kf6gpe** [comment]
@guqh, if I understand you correctly, you're working around this problem by switching to stable. Out of curiosity, do you still see this if you switch back to the beta channel with something like 1.13 in beta? Thanks!

**Comment by rayk** [comment]
can confirm this problem is present in `Channel beta, v1.12.13+hotfix.6, on Mac OS X 10.15.2 19C57,`

**Comment by descifrador** [comment]
Hey @guqh I had the same problem which you are facing.
I had open the IntelliJ IDE and then Configure the Plugins of Flutter and Dart in it after that error get solved.
![image](https://user-images.githubusercontent.com/33203503/73974330-28d9ee80-494a-11ea-9f45-91cc72ca9468.png)

**Comment by iapicca** [comment]
Hi @guqh  
following the indication of [jetbrains' Flutter plugin](https://plugins.jetbrains.com/plugin/9212-flutter) 
the correct way to address the problem
is to open an issue on the dedicated [github](https://github.com/flutter/flutter-intellij/issues)

Closing, as this isn't an issue with Flutter itself,
if you disagree please write in the comments and I will reopen it.
Thank you for your understanding

**Comment by rabs-developer** [comment]
I have same issue and fixed it now. Just open any flutter project in IntelliJ IDE, it will ask you to configure or download any missing dependencies.  Then proceed to configure or download. It will be fine after that.

**Comment by HeroBarry** [comment]
Plugin Dart is not unload-safe because of extension to non-dynamic EP com.intellij.console.folding
