### ISSUE TITLE
There is a bug in line 308 of the TextField class.

### ISSUE THREAD

**Issue by PennHan** [flutter/flutter#45534]
Run the project error every time you pass the toolbarOptions property to the TextField Widget

```dart
TextField(
  toolbarOptions: ToolbarOptions(
    copy: true,
    cut: true,
    selectAll: true,
    paste: true,
  ),
),
```
Error message：

```log
════════ Exception caught by widgets library ═══════════════════════════════════════════════════════
The following assertion was thrown building ClearableTextField(dirty, state: _ClearableTextFieldState#6726b):
type 'ToolbarOptions' is not a subtype of type 'bool'


Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=BUG.md

User-created ancestor of the error-causing widget was: 
  Column file:///Users/hanpeidong/WorkSpaces/AndroidSpace/JDSpace/flutter_appframework_demo/lib/tech_share/flutter_base/login/login_page.dart:33:22
When the exception was thrown, this was the stack: 
#0      new TextField (package:flutter/src/material/text_field.dart:308:40)
#1      _ClearableTextFieldState.build (package:appframework_demo/tech_share/flutter_base/login/clearable_text_field.dart:164:16)
#2      StatefulElement.build (package:flutter/src/widgets/framework.dart:4047:27)
#3      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3941:15)
#4      Element.rebuild (package:flutter/src/widgets/framework.dart:3738:5)
...
════════════════════════════════════════════════════════════════════════════════════════════════════
```

The error occurred in the following location：
```dart
// TextField line 308
toolbarOptions = toolbarOptions ?? obscureText ?
         const ToolbarOptions(
           selectAll: true,
           paste: true,
         ) :
         const ToolbarOptions(
           copy: true,
           cut: true,
           selectAll: true,
           paste: true,
         ),
```

I think this is an operator priority issue, and it's okay to write as follows.
```dart
toolbarOptions = toolbarOptions ?? (obscureText ?
         const ToolbarOptions(
           selectAll: true,
           paste: true,
         ) :
         const ToolbarOptions(
           copy: true,
           cut: true,
           selectAll: true,
           paste: true,
         )),
```
my flutter doctor:

```shell
JRMWD3RDHTD5:~ hanpeidong$ flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, v1.9.1+hotfix.6, on Mac OS X 10.14.6 18G84, locale
    zh-Hans-CN)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 10.3)
[✓] Android Studio (version 3.2)
[✓] Android Studio (version 3.5)
[✓] VS Code (version 1.40.1)
[✓] Connected device (2 available)

• No issues found!

```

**Comment by iapicca** [comment]
Hi @PennHan 
does this [code ](https://gist.github.com/iapicca/da86f1bd2129f56eb7a71b84c84daebf)represent the issue you are describing?
I've experienced the error 
`type 'ToolbarOptions' is not a subtype of type 'bool'`
thank you

**Comment by PennHan** [comment]
Yes

**Comment by LongCatIsLooong** [comment]
This looks like a dup of https://github.com/flutter/flutter/issues/40664, and if that's the case it's already been patched on master: https://github.com/flutter/flutter/commit/b730a993c1e6dd2774b270fb2e0253a26e69cf39.

**Comment by gaaclarke** [comment]
See @LongCatIsLooong's comment, closing because it's a dup.
