### ISSUE TITLE
Enum without dot? Not enough information in error message.

### ISSUE THREAD

**Issue by marcglasberg** [flutter/flutter#45552]
If  I use EnumProperty and that's not an enum:

    properties.add(EnumProperty<String>('name', name, defaultValue: null));

I get this:

```
════════ Exception caught by Flutter framework════════════════════
The following assertion was thrown during a service extension callback for "ext.flutter.inspector.getChildrenDetailsSubtree":
'package:flutter/src/foundation/diagnostics.dart': Failed assertion: line 2882 pos 10: 'indexOfDot != -1 && indexOfDot < description.length - 1': is not true.


Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=BUG.md

When the exception was thrown, this was the stack: 
#2      describeEnum (package:flutter/src/foundation/diagnostics.dart:2882:10)
#3      EnumProperty.valueToString (package:flutter/src/foundation/diagnostics.dart:2298:12)
#4      DiagnosticsProperty.toDescription (package:flutter/src/foundation/diagnostics.dart:2605:21)
#5      DiagnosticsNode.toJsonMap (package:flutter/src/foundation/diagnostics.dart:1546:22)
#6      DiagnosticsProperty.toJsonMap (package:flutter/src/foundation/diagnostics.dart:2549:44)
...
════════════════════════════════════════════════════════
```

This error message is useless. I suggest this method should explain the error with a message like: "The property 'name' should be an enum."

Or it should not throw, and should still print the object, like this:

    String describeEnum(Object enumEntry) {
        final String description = enumEntry.toString();
        final int indexOfDot = description.indexOf('.');
        if (indexOfDot == -1)
          return description;
        else
          return description.substring(indexOfDot + 1);
      }

**Comment by marcglasberg** [comment]
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, v1.9.1+hotfix.6, on Microsoft Windows [Version 10.0.17763.864], locale pt-BR)

[!] Android toolchain - develop for Android devices (Android SDK version 29.0.0)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses
[√] Android Studio (version 3.5)
[√] IntelliJ IDEA Ultimate Edition (version 2018.3)
[√] IntelliJ IDEA Ultimate Edition (version 2019.2)
[√] Connected device (1 available)

! Doctor found issues in 1 category.
