### ISSUE TITLE
flutter app cannot handle detached life cycle.

### ISSUE THREAD

**Issue by chunhtai** [flutter/flutter#45575]
Engine add to app starts sending detached message to framework. However, framework side change is pending on desktop embedding.

to reproduce
1, run flutter/sample/experiment add to app with ios full screen
2, launch the flutter screen and close it

```
I/flutter (16072): The following assertion was thrown during a platform message callback:
I/flutter (16072): 'package:flutter/src/scheduler/binding.dart': Failed assertion: line 326 pos 12: 'state != null': is
I/flutter (16072): not true.                                            
I/flutter (16072):                                                      
I/flutter (16072): Either the assertion indicates an error in the framework itself, or we should provide substantially
I/flutter (16072): more information in this error message to help you determine and fix the underlying cause.
I/flutter (16072): In either case, please report this assertion by filing a bug on GitHub:
I/flutter (16072):   https://github.com/flutter/flutter/issues/new?template=BUG.md
I/flutter (16072):                                                      
I/flutter (16072): When the exception was thrown, this was the stack:   
I/flutter (16072): #2      SchedulerBinding.handleAppLifecycleStateChanged (package:flutter/src/scheduler/binding.dart:326:12)
I/flutter (16072): #3      WidgetsBinding.handleAppLifecycleStateChanged (package:flutter/src/widgets/binding.dart:543:11)
I/flutter (16072): #4      SchedulerBinding._handleLifecycleMessage (package:flutter/src/scheduler/binding.dart:342:5)
I/flutter (16072): #5      BasicMessageChannel.setMessageHandler.<anonymous closure> (package:flutter/src/services/platform_channel.dart:74:49)
I/flutter (16072): #6      _DefaultBinaryMessenger.handlePlatformMessage (package:flutter/src/services/binding.dart:200:33)
I/flutter (16072): #7      _invoke3.<anonymous closure> (dart:ui/hooks.dart:303:15)
I/flutter (16072): #11     _invoke3 (dart:ui/hooks.dart:302:10)         
I/flutter (16072): #12     _dispatchPlatformMessage (dart:ui/hooks.dart:162:5)
I/flutter (16072): (elided 5 frames from class _AssertionError and package dart:async)
```

**Comment by karim-8** [comment]
Hello, Did anyone find a solution for detached state to recognize!

**Comment by karim-8** [comment]
In Application Lifecycle cant check if user closed the application or not, i think detatched in ApplicationState Should handle this.

**Comment by chunhtai** [comment]
This depends on whether the app is just in the background or the activity is destroyed. If the app is just in the background (pressing home screen), it will be in `AppLifecycleState.paused`. If the activity is destroyed (android back button), it will be in `AppLifecycleState.detached`

**Comment by karim-8** [comment]
@chunhtai okay but what if the application in background and i dragged it to destroy? i tried this but the last state was paused, and my state require to do action before App destroyed!

**Comment by chunhtai** [comment]
I don't think there is a way to listen to drags to destroy. Maybe @xster knows more.
May I know what is your use case?
