### ISSUE TITLE
Running a driver test on Fuchsia fails with NoSuchMethod exception

### ISSUE THREAD

**Issue by iskakaushik** [flutter/flutter#45624]
Repro instructions:

1. Apply the patch: https://github.com/flutter/flutter/pull/45623
2. In the folder: `flutter/examples/stocks`, run `flutter drive -v -d $FUCHSIA_DEVICE_ID --target=test_driver/scroll_perf.dart`

You should see the following errors:

```
[+1219 ms] Unhandled exception:
[   +2 ms] NoSuchMethodError: The method 'group' was called on null.
[        ] Receiver: null
[        ] Tried calling: group("scrolling performance test", Closure: () => Null, onPlatform: null, retry: null, skip: null, solo: false, tags: null, testOn: null, timeout: null)
[        ] #0      Object.noSuchMethod (dart:core-patch/object_patch.dart:53:5)
[        ] #1      group (package:test_api/test_api.dart:183:13)
[        ] #2      main (file:///usr/local/google/home/kaushikiska/Code/flutter/flutter/examples/stocks/test_driver/scroll_perf_test.dart:12:3)
[        ] #3      _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:307:19)
[        ] #4      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:174:12)
[  +32 ms] Stopping application instance.
[        ] Stopping application.
[        ] executing: ssh -F /usr/local/google/home/kaushikiska/Code/fuchsia/out/default/ssh-keys/ssh_config 192.168.42.51 tiles_ctl list
[  +85 ms] Found 1 tiles:
           Tile key 2 url fuchsia-pkg://flutter_tool/stocks#meta/stocks.cmx size 1333.3x882.2x1000.0 (unfocusable)
[   +2 ms] executing: ssh -F /usr/local/google/home/kaushikiska/Code/fuchsia/out/default/ssh-keys/ssh_config 192.168.42.51 tiles_ctl remove 2
[  +55 ms] "flutter drive" took 18,235ms.
Driver tests failed: 255

#0      throwToolExit (package:flutter_tools/src/base/common.dart:28:3)
#1      _runTests (package:flutter_tools/src/commands/drive.dart:316:5)
<asynchronous suspension>
#2      DriveCommand.runCommand (package:flutter_tools/src/commands/drive.dart:137:23)
<asynchronous suspension>
#3      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:615:18)
<asynchronous suspension>
#4      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:515:33)
<asynchronous suspension>
#5      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:146:29)
#6      _rootRun (dart:async/zone.dart:1126:13)
#7      _CustomZone.run (dart:async/zone.dart:1023:19)
#8      _runZoned (dart:async/zone.dart:1518:10)
#9      runZoned (dart:async/zone.dart:1465:12)
#10     AppContext.run (package:flutter_tools/src/base/context.dart:145:18)
#11     FlutterCommand.run (package:flutter_tools/src/runner/flutter_command.dart:505:20)
#12     CommandRunner.runCommand (package:args/command_runner.dart:197:27)
#13     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:413:21)
<asynchronous suspension>
#14     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:146:29)
#15     _rootRun (dart:async/zone.dart:1126:13)
#16     _CustomZone.run (dart:async/zone.dart:1023:19)
#17     _runZoned (dart:async/zone.dart:1518:10)
#18     runZoned (dart:async/zone.dart:1465:12)
#19     AppContext.run (package:flutter_tools/src/base/context.dart:145:18)
#20     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:364:19)
#21     CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:112:25)
#22     new Future.sync (dart:async/future.dart:224:31)
#23     CommandRunner.run (package:args/command_runner.dart:112:14)
#24     FlutterCommandRunner.run (package:flutter_tools/src/runner/flutter_command_runner.dart:250:18)
#25     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:63:22)
#26     _rootRun (dart:async/zone.dart:1126:13)
#27     _CustomZone.run (dart:async/zone.dart:1023:19)
#28     _runZoned (dart:async/zone.dart:1518:10)
#29     runZoned (dart:async/zone.dart:1502:12)
#30     run.<anonymous closure> (package:flutter_tools/runner.dart:61:18)
<asynchronous suspension>
#31     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:146:29)
#32     _rootRun (dart:async/zone.dart:1126:13)
#33     _CustomZone.run (dart:async/zone.dart:1023:19)
#34     _runZoned (dart:async/zone.dart:1518:10)
#35     runZoned (dart:async/zone.dart:1465:12)
#36     AppContext.run (package:flutter_tools/src/base/context.dart:145:18)
#37     runInContext (package:flutter_tools/src/context_runner.dart:64:24)
#38     run (package:flutter_tools/runner.dart:50:10)
#39     main (package:flutter_tools/executable.dart:65:9)
#40     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:305:32)
#41     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:174:12)

```

cc: @zanderso , @blasten , @gw280

**Comment by iskakaushik** [comment]
Seems like I hit https://github.com/flutter/flutter/issues/35940

**Comment by zanderso** [comment]
Did a fix similar to the one for https://github.com/flutter/flutter/issues/35940 not work?

**Comment by iskakaushik** [comment]
I only realized that this was not Fuchsia specific after I found the error. I fixed it in the same PR.
