### ISSUE TITLE
CanvasKit backend crashing with unknown fontFamily

### ISSUE THREAD

**Issue by hterkelsen** [flutter/flutter#45636]
CanvasKit backend crashes when rendering text when the `fontFamily` is unrecognized.

This can happen when a `null` `fontFamily` is passed, or when the `fontFamily` given to Flutter is different from the `fontFamily` in the font file (this is quite often).

```
RuntimeError: memory access out of bounds
main.dart.js:4740     at wasm-function[10700]:0x441ac4
main.dart.js:4740     at wasm-function[10721]:0x4433ea
main.dart.js:4740     at wasm-function[10724]:0x4436e3
main.dart.js:4740     at wasm-function[10658]:0x43ec93
main.dart.js:4740     at wasm-function[4278]:0x1f3cf8
main.dart.js:4740     at wasm-function[2102]:0xbe2d4
main.dart.js:4740     at wasm-function[11274]:0x45df14
main.dart.js:4740     at h.dynCall_viif (https://particles.skia.org/static/canvaskit.js:349:311)
main.dart.js:4740     at dynCall_viif_22 (eval at K (https://particles.skia.org/static/canvaskit.js:166:473), <anonymous>:2:12)
main.dart.js:4740     at ParagraphImpl$layout [as layout] (eval at Hd (https://particles.skia.org/static/canvaskit.js:168:242), <anonymous>:8:1)
```

**Comment by hterkelsen** [comment]
This was fixed in https://github.com/flutter/engine/pull/16504
