### ISSUE TITLE
Gradle build failed to produce an .apk file.

### ISSUE THREAD

**Issue by sujithTSR** [flutter/flutter#45671]
I am building an application with flavors and splits. The apks are generated at build/outputs/apk/flavor-name/debug/*.apk

The apk name is in this [format](https://github.com/blasten/flutter/blob/e372641789e0ec9403607f97eb92b7c21120b8a7/packages/flutter_tools/lib/src/android/gradle.dart#L1199).

I get an error
```
Gradle build failed to produce an .apk file. It's likely that this file was generated under /Users/sujith/<repo>/build,
but the tool couldn't find it.

#0      throwToolExit (package:flutter_tools/src/base/common.dart:28:3)
#1      _exitWithExpectedFileNotFound (package:flutter_tools/src/android/gradle.dart:827:3)
#2      findApkFiles (package:flutter_tools/src/android/gradle.dart:765:5)
#3      buildGradleApp (package:flutter_tools/src/android/gradle.dart:451:35)
#4      _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:73:64)
#5      _rootRunUnary (dart:async/zone.dart:1134:38)
#6      _CustomZone.runUnary (dart:async/zone.dart:1031:19)
#7      _FutureListener.handleValue (dart:async/future_impl.dart:139:18)
#8      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:680:45)
#9      Future._propagateToListeners (dart:async/future_impl.dart:709:32)
#10     Future._completeWithValue (dart:async/future_impl.dart:524:5)
#11     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:32:15)
#12     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:290:13)
#13     _DefaultProcessUtils.stream (package:flutter_tools/src/base/process.dart)
#14     _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:73:64)
#15     _rootRunUnary (dart:async/zone.dart:1134:38)
#16     _CustomZone.runUnary (dart:async/zone.dart:1031:19)
#17     _FutureListener.handleValue (dart:async/future_impl.dart:139:18)
#18     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:680:45)
#19     Future._propagateToListeners (dart:async/future_impl.dart:709:32)
#20     Future._completeWithValue (dart:async/future_impl.dart:524:5)
#21     Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:554:7)
#22     _rootRun (dart:async/zone.dart:1126:13)
#23     _CustomZone.run (dart:async/zone.dart:1023:19)
#24     _CustomZone.runGuarded (dart:async/zone.dart:925:7)
#25     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:965:23)
#26     _microtaskLoop (dart:async/schedule_microtask.dart:43:21)
#27     _startMicrotaskLoop (dart:async/schedule_microtask.dart:52:5)
#28     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
#29     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:175:5)
```
I am able to see all the apks inside build/app/outputs/apk/flavor/release-type-debug/*.apk
The apks are exactly are in the same specified [format](https://github.com/blasten/flutter/blob/e372641789e0ec9403607f97eb92b7c21120b8a7/packages/flutter_tools/lib/src/android/gradle.dart#L1199).

Flutter analyze
```
No issues found! (ran in 3.9s)
```

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel master, v1.12.15-pre.6, on Mac OS X 10.14.5 18F203, locale en-IN)

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 11.0)
[✓] Android Studio (version 3.5)
[✓] Connected device (1 available)

• No issues found!
Sujiths-MacBook-Pro% flutter doctor -v
[✓] Flutter (Channel master, v1.12.15-pre.6, on Mac OS X 10.14.5 18F203, locale en-IN)
    • Flutter version 1.12.15-pre.6 at /Users/sujith_tsr/flutter
    • Framework revision 92b0ceaaa6 (24 hours ago), 2019-11-26 01:19:51 -0500
    • Engine revision 05f8c8b24b
    • Dart version 2.7.0

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/sujith_tsr/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • ANDROID_HOME = /Users/sujith_tsr/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.0, Build version 11A420a
    • CocoaPods version 1.7.5

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 40.2.2
    • Dart plugin version 191.8580
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] Connected device (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 8.1.0 (API 27) (emulator)

• No issues found!
```

**Comment by sujithTSR** [comment]
Just a hunch.! 
Why isn't the flavor and build type directory not considered [here](https://github.com/flutter/flutter/blob/1b835a722b77769ef34f1c0233e58d82641d18ec/packages/flutter_tools/lib/src/android/gradle.dart#L740)? 

Maybe that might be the reason for the `Iterable<File> apks` being empty.

**Comment by sujithTSR** [comment]
Hi,
I've realized that I was using splits to generate separate apks for "x86", "x86_64", "arm64-v8a", "armeabi-v7a"

By removing the splits, The build was running fine. 
But I need to generate apks for all splits. Any help here ?

**Comment by sujithTSR** [comment]
Okay. 
Found a much convenient way. 
Rather than having the target-platforms specifying in the build.gradle of android. 
It is better to create separate apks for the target platforms while building the release apks. 

`flutter build apk --release --flavor=my_flavor --target-platform android-arm,android-arm64 --split-per-abi`

**Comment by ArtfulDodgerB92** [comment]
Is there any real solution to this?  I am getting this error when I try to just run my perfectly working app on my device. 

Here is how to recreate this issue: 
1) Be in the stable channel
2) Have a perfectly functioning and working flutter app
3) Move to the master channel
4) Try to run the exact same app with 0 changes

That's it.   That's all it takes.   You might say the fix is simple, just stay in the stable channel, right?   Except I can't because that channel is also completely broken.   It has a known issue with the running app behaving totally differently to the app resulting from the appbundle.   The "stable" channel indeed.    Absolute morons.

**Comment by saber2coder** [comment]
1.12.13+hotfix.5  app/build.gradle  add buildDir = new File(rootProject.projectDir, "../build/host")

**Comment by AlirezaDaryani** [comment]
> 1.12.13+hotfix.5 app/build.gradle add buildDir = new File(rootProject.projectDir, "../build/host")

can you explain this comment?
