### ISSUE TITLE
[url_launcher] Trying to call the phone causes the page to freeze

### ISSUE THREAD

**Issue by chenxianqi** [flutter/flutter#45672]
## Steps to Reproduce

Try to use launch ('tel:') to make a call. The system will pop up a sheet. The card will crash when you click the page a few times.

I think it should be caused by url_launcher

**Target Platform: IOS
**Target OS version/browser: 13.2.2
**Devices: iphone 6s plus

```
```

```
 Flutter (Channel stable, v1.9.1+hotfix.6, on Mac OS X 10.15.1 19B88, locale zh-Hans-CN)
    • Flutter version 1.9.1+hotfix.6 at /Users/chenxianqi/flutter
    • Framework revision 68587a0916 (2 months ago), 2019-09-13 19:46:58 -0700
    • Engine revision b863200c37
    • Dart version 2.5.0

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/chenxianqi/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.2.1, Build version 11B500
    • CocoaPods version 1.8.4

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 41.1.2
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] VS Code (version 1.40.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.6.0

[✓] Connected device (2 available)
    • Redmi Note 7 • 2f49c4ea                                 • android-arm64 • Android 9 (API 28)
    • Keith iPhone • af47b4c63dc2cad49a1672e7494dcded7224937e • ios           • iOS 13.2.2

```

**Comment by chenxianqi** [comment]
![image](https://user-images.githubusercontent.com/27764334/69699024-e615c200-1121-11ea-8e19-4910c06cb015.png)
Then switch the app to the background and then back to the foreground, and work again

**Comment by helinanever** [comment]
Hi @chenxianqi,

Could you, please, provide logs and code simple to reproduce the issue?

Thank you.

**Comment by chenxianqi** [comment]
@helinanever yes ，I can provide the smallest reproduction code and the reproduction steps
[https://github.com/chenxianqi/flutter_url_launcher_test](https://github.com/chenxianqi/flutter_url_launcher_test)

**Comment by chenxianqi** [comment]
> 嗨@chenxianqi，
> 
> 您能否提供日志和代码示例来重现该问题？
> 
> 谢谢。

Sorry，The current ios device cannot print the log and Xcode Without any errors

**Comment by chenxianqi** [comment]
> Hi @chenxianqi,
> 
> Could you please provide logs and code sample to reproduce the issue?
> 
> Thank you.

Sorry，The current ios device cannot print the log and Xcode Without any errors

**Comment by iapicca** [comment]
> Sorry，The current ios device cannot print the log and Xcode Without any errors

Hi @chenxianqi 
could you please run `flutter run --verbose`?
thank you for the info you provided

**Comment by chenxianqi** [comment]
> > Sorry，The current ios device cannot print the log and Xcode Without any errors
> 
> Hi @chenxianqi
> could you please run `flutter run --verbose`?
> thank you for the info you provided

The report is as follows
```
chenxianqideMBP:flutter_url_launcher_test chenxianqi$ flutter run --verbose
[  +39 ms] executing: [/Users/chenxianqi/flutter/] git log -n 1 --pretty=format:%H
[  +64 ms] Exit code 0 from: git log -n 1 --pretty=format:%H
[        ] 68587a0916366e9512a78df22c44163d041dd5f3
[        ] executing: [/Users/chenxianqi/flutter/] git describe --match v*.*.* --first-parent --long --tags
[  +21 ms] Exit code 0 from: git describe --match v*.*.* --first-parent --long --tags
[   +1 ms] v1.9.1+hotfix.6-0-g68587a091
[  +20 ms] executing: [/Users/chenxianqi/flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[  +15 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/stable
[        ] executing: [/Users/chenxianqi/flutter/] git ls-remote --get-url origin
[  +21 ms] Exit code 0 from: git ls-remote --get-url origin
[   +1 ms] https://github.com/flutter/flutter.git
[ +171 ms] executing: [/Users/chenxianqi/flutter/] git rev-parse --abbrev-ref HEAD
[  +55 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] stable
[+2289 ms] executing: /Users/chenxianqi/Library/Android/sdk/platform-tools/adb devices -l
[  +13 ms] Exit code 0 from: /Users/chenxianqi/Library/Android/sdk/platform-tools/adb devices -l
[        ] List of devices attached
           2f49c4ea               device usb:338690048X product:lavender model:Redmi_Note_7 device:lavender transport_id:2
[  +30 ms] executing: /Users/chenxianqi/flutter/bin/cache/artifacts/libimobiledevice/idevice_id -h
[ +506 ms] /usr/bin/xcrun simctl list --json devices
[ +234 ms] More than one device connected; please specify a device with the '-d <deviceId>' flag, or use '-d all' to act on all devices.
[  +10 ms] /Users/chenxianqi/Library/Android/sdk/platform-tools/adb -s 2f49c4ea shell getprop
[  +85 ms] ro.hardware = qcom
[   +8 ms] Redmi Note 7 • 2f49c4ea                                 • android-arm64 • Android 9 (API 28)
[   +2 ms] Keith iPhone • af47b4c63dc2cad49a1672e7494dcded7224937e • ios           • iOS 13.2.2
[  +23 ms] "flutter run" took 3,251ms.

#0      throwToolExit (package:flutter_tools/src/base/common.dart:28:3)
#1      RunCommand.validateCommand (package:flutter_tools/src/commands/run.dart:281:7)
<asynchronous suspension>
#2      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:465:11)
<asynchronous suspension>
#3      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:407:33)
<asynchronous suspension>
#4      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:154:29)
<asynchronous suspension>
#5      _rootRun (dart:async/zone.dart:1124:13)
#6      _CustomZone.run (dart:async/zone.dart:1021:19)
#7      _runZoned (dart:async/zone.dart:1516:10)
#8      runZoned (dart:async/zone.dart:1463:12)
#9      AppContext.run (package:flutter_tools/src/base/context.dart:153:18)
<asynchronous suspension>
#10     FlutterCommand.run (package:flutter_tools/src/runner/flutter_command.dart:397:20)
#11     CommandRunner.runCommand (package:args/command_runner.dart:197:27)
<asynchronous suspension>
#12     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:402:21)
<asynchronous suspension>
#13     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:154:29)
<asynchronous suspension>
#14     _rootRun (dart:async/zone.dart:1124:13)
#15     _CustomZone.run (dart:async/zone.dart:1021:19)
#16     _runZoned (dart:async/zone.dart:1516:10)
#17     runZoned (dart:async/zone.dart:1463:12)
#18     AppContext.run (package:flutter_tools/src/base/context.dart:153:18)
<asynchronous suspension>
#19     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:356:19)
<asynchronous suspension>
#20     CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:112:25)
#21     new Future.sync (dart:async/future.dart:224:31)
#22     CommandRunner.run (package:args/command_runner.dart:112:14)
#23     FlutterCommandRunner.run (package:flutter_tools/src/runner/flutter_command_runner.dart:242:18)
#24     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:63:22)
<asynchronous suspension>
#25     _rootRun (dart:async/zone.dart:1124:13)
#26     _CustomZone.run (dart:async/zone.dart:1021:19)
#27     _runZoned (dart:async/zone.dart:1516:10)
#28     runZoned (dart:async/zone.dart:1500:12)
#29     run.<anonymous closure> (package:flutter_tools/runner.dart:61:18)
<asynchronous suspension>
#30     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:154:29)
<asynchronous suspension>
#31     _rootRun (dart:async/zone.dart:1124:13)
#32     _CustomZone.run (dart:async/zone.dart:1021:19)
#33     _runZoned (dart:async/zone.dart:1516:10)
#34     runZoned (dart:async/zone.dart:1463:12)
#35     AppContext.run (package:flutter_tools/src/base/context.dart:153:18)
<asynchronous suspension>
#36     runInContext (package:flutter_tools/src/context_runner.dart:59:24)
<asynchronous suspension>
#37     run (package:flutter_tools/runner.dart:50:10)
#38     main (package:flutter_tools/executable.dart:65:9)
<asynchronous suspension>
#39     main (file:///b/s/w/ir/k/archive/flutter/packages/flutter_tools/bin/flutter_tools.dart:8:3)
#40     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:303:32)
#41     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:12)


```

**Comment by chenxianqi** [comment]
@helinanever Hi， Is it a problem with url_launcher?

**Comment by chenxianqi** [comment]
The problem v1.12.13 + hotfix.8, url_launcher: 5.4.2 still exists

**Comment by iapicca** [comment]
Hi @chenxianqi 
could you please try running this [code](https://gist.github.com/iapicca/687a2838b1d93c691653e0ef84a6bea5)
if you are still experiencing the issue please provide your `flutter doctor -v` , 
your `flutter run --verbose` 
Thank you

**Comment by TahaTesser** [comment]
Hi @chenxianqi 
Without additional information, we are unfortunately not sure how to resolve this issue. We are
therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the
bug if you have any more information for us; we will reopen it right away!
Thanks for your contribution.
