### ISSUE TITLE
[web] Flutter stays on "Attempting to connect to browser instance"

### ISSUE THREAD

**Issue by FolksyTitan** [flutter/flutter#45700]
## Steps to Reproduce

1. Trying to launch the Flutter app for the web.
2. After connecting to the browser (Chrome opens no problem), terminal indicates "Attempting to connect to browser instance", then "(this is taking an unexpectedly long time.)".

![screenshot_bug_flutter](https://user-images.githubusercontent.com/48334238/69737649-c15e2200-1102-11ea-8d2b-d9aa9f368b85.PNG)

**Target Platform: Web**
**Target OS version/browser: Chrome v78.0.3904.108**
**Devices: Windows**

#### flutter run --verbose
```
[  +27 ms] executing: [C:\Users\<user>\Documents\DEV\FLUTTER\flutter\] git -c log.showSignature=false log -n 1 --pretty=format:%H
[ +100 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[   +2 ms] 7726910a5bc4135a9f1fd497c872c9e5cb1e51b5
[        ] executing: [C:\Users\<user>\Documents\DEV\FLUTTER\flutter\] git describe --match v*.*.* --first-parent --long --tags
[  +83 ms] Exit code 0 from: git describe --match v*.*.* --first-parent --long --tags
[   +1 ms] v1.12.14-0-g7726910a5
[   +6 ms] executing: [C:\Users\<user>\Documents\DEV\FLUTTER\flutter\] git rev-parse --abbrev-ref --symbolic @{u}
[  +60 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/dev
[        ] executing: [C:\Users\<user>\Documents\DEV\FLUTTER\flutter\] git ls-remote --get-url origin
[  +54 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[  +96 ms] executing: [C:\Users\<user>\Documents\DEV\FLUTTER\flutter\] git rev-parse --abbrev-ref HEAD
[  +55 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] dev
[ +114 ms] executing: C:\Users\<user>\AppData\Local\Android\Sdk\platform-tools\adb.exe devices -l
[  +35 ms] Exit code 0 from: C:\Users\<user>\AppData\Local\Android\Sdk\platform-tools\adb.exe devices -l
[        ] List of devices attached
[  +12 ms] More than one device connected; please specify a device with the '-d <deviceId>' flag, or use '-d all' to act on all devices.
[  +43 ms] Chrome     • chrome     • web-javascript • Google Chrome 78.0.3904.108
[   +1 ms] Web Server • web-server • web-javascript • Flutter Tools
[  +10 ms] "flutter run" took 273ms.

#0      throwToolExit (package:flutter_tools/src/base/common.dart:28:3)
#1      RunCommand.validateCommand (package:flutter_tools/src/commands/run.dart:289:7)
<asynchronous suspension>
#2      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:590:11)
#3      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:515:33)
<asynchronous suspension>
#4      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:146:29)
#5      _rootRun (dart:async/zone.dart:1126:13)
#6      _CustomZone.run (dart:async/zone.dart:1023:19)
#7      _runZoned (dart:async/zone.dart:1518:10)
#8      runZoned (dart:async/zone.dart:1465:12)
#9      AppContext.run (package:flutter_tools/src/base/context.dart:145:18)
#10     FlutterCommand.run (package:flutter_tools/src/runner/flutter_command.dart:505:20)
#11     CommandRunner.runCommand (package:args/command_runner.dart:197:27)
#12     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:413:21)
<asynchronous suspension>
#13     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:146:29)
#14     _rootRun (dart:async/zone.dart:1126:13)
#15     _CustomZone.run (dart:async/zone.dart:1023:19)
#16     _runZoned (dart:async/zone.dart:1518:10)
#17     runZoned (dart:async/zone.dart:1465:12)
#18     AppContext.run (package:flutter_tools/src/base/context.dart:145:18)
#19     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:364:19)
#20     CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:112:25)
#21     new Future.sync (dart:async/future.dart:224:31)
#22     CommandRunner.run (package:args/command_runner.dart:112:14)
#23     FlutterCommandRunner.run (package:flutter_tools/src/runner/flutter_command_runner.dart:250:18)
#24     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:63:22)
#25     _rootRun (dart:async/zone.dart:1126:13)
#26     _CustomZone.run (dart:async/zone.dart:1023:19)
#27     _runZoned (dart:async/zone.dart:1518:10)
#28     runZoned (dart:async/zone.dart:1502:12)
#29     run.<anonymous closure> (package:flutter_tools/runner.dart:61:18)
<asynchronous suspension>
#30     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:146:29)
#31     _rootRun (dart:async/zone.dart:1126:13)
#32     _CustomZone.run (dart:async/zone.dart:1023:19)
#33     _runZoned (dart:async/zone.dart:1518:10)
#34     runZoned (dart:async/zone.dart:1465:12)
#35     AppContext.run (package:flutter_tools/src/base/context.dart:145:18)
#36     runInContext (package:flutter_tools/src/context_runner.dart:64:24)
#37     run (package:flutter_tools/runner.dart:50:10)
#38     main (package:flutter_tools/executable.dart:65:9)
#39     main (file:///C:/Users/<user>/Documents/DEV/FLUTTER/flutter/packages/flutter_tools/bin/flutter_tools.dart:8:3)
#40     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:305:32)
#41     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:174:12)
```

#### flutter analyze
```
Analyzing <project>...
No issues found! (ran in 9.4s)
```

#### flutter doctor -v
```
[√] Flutter (Channel dev, v1.12.14, on Microsoft Windows [Version 10.0.17763.864], locale en-CA)
    • Flutter version 1.12.14 at C:\Users\<user>\Documents\DEV\FLUTTER\flutter
    • Framework revision 7726910a5b (2 days ago), 2019-11-25 16:47:51 -0500
    • Engine revision c89ac6347b
    • Dart version 2.7.0

[!] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at C:\Users\<user>\AppData\Local\Android\Sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-Q, build-tools 28.0.3
    • ANDROID_HOME = C:\Users\<user>\AppData\Local\Android\Sdk
    • Java binary at: C:\Program Files\Android\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
    X Android license status unknown.
      Try re-installing or updating your Android SDK Manager.
      See https://developer.android.com/studio/#downloads or visit https://flutter.dev/setup/#android-setup for detailed instructions.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 3.4)
    • Android Studio at C:\Program Files\Android
    • Flutter plugin version 35.0.1
    • Dart plugin version 183.5901
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

[√] IntelliJ IDEA Community Edition (version 2019.1)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2019.1
    • Flutter plugin version 35.0.2
    • Dart plugin version 191.6183.88

[√] VS Code (version 1.40.2)
    • VS Code at C:\Users\<user>\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.6.0

[√] Connected device (2 available)
    • Chrome     • chrome     • web-javascript • Google Chrome 78.0.3904.108
    • Web Server • web-server • web-javascript • Flutter Tools

! Doctor found issues in 1 category.
```

New to the flutter world, so I'd be more than happy for feedback on anything I should've done differently!

Thanks 🤘🏻

**Comment by iapicca** [comment]
Hi @FolksyTitan 
could you please attach your `flutter run -d chrome --verbose` as well
thank you

**Comment by FolksyTitan** [comment]
@iapicca Here ya go!

#### `flutter run -d chrome --verbose`

```
[  +27 ms] executing: [C:\Users\<user>\Documents\DEV\FLUTTER\flutter\] git -c log.showSignature=false log -n 1 --pretty=format:%H
[  +84 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[   +1 ms] 7726910a5bc4135a9f1fd497c872c9e5cb1e51b5
[        ] executing: [C:\Users\<user>\Documents\DEV\FLUTTER\flutter\] git describe --match v*.*.* --first-parent --long --tags
[  +82 ms] Exit code 0 from: git describe --match v*.*.* --first-parent --long --tags
[   +1 ms] v1.12.14-0-g7726910a5
[   +6 ms] executing: [C:\Users\<user>\Documents\DEV\FLUTTER\flutter\] git rev-parse --abbrev-ref --symbolic @{u}
[  +60 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/dev
[        ] executing: [C:\Users\<user>\Documents\DEV\FLUTTER\flutter\] git ls-remote --get-url origin
[  +55 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[  +95 ms] executing: [C:\Users\<user>\Documents\DEV\FLUTTER\flutter\] git rev-parse --abbrev-ref HEAD
[  +59 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] dev
[ +120 ms] executing: C:\Users\<user>\AppData\Local\Android\Sdk\platform-tools\adb.exe devices -l
[  +38 ms] Exit code 0 from: C:\Users\<user>\AppData\Local\Android\Sdk\platform-tools\adb.exe devices -l
[        ] List of devices attached
[  +17 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[   +5 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[ +166 ms] Generating C:\Users\<user>\Documents\<folder>\<folder>\<project_folder>\android\app\src\main\java\io\flutter\plugins\GeneratedPluginRegistrant.java
[ +124 ms] Launching lib\main.dart on Chrome in debug mode...
[   +1 ms] Building application for the web...
[+7848 ms] Starting daemon...
[ +155 ms] Initializing inputs
[  +12 ms] Reading cached asset graph...
[ +154 ms] Reading cached asset graph completed, took 152ms

[ +228 ms] Checking for updates since last build...
[ +531 ms] Checking for updates since last build completed, took 531ms

[  +10 ms] Initializing inputs
[   +4 ms] Reading cached asset graph...
[        ] Reading cached asset graph completed, took 152ms
[        ] Checking for updates since last build...
[        ] Checking for updates since last build completed, took 531ms
[ +152 ms] Serving DevTools at http://127.0.0.1:54450

[ +641 ms] About to build [web]...
[ +161 ms] Running build...
[   +1 ms] Running build completed, took 79ms

[        ] Caching finalized dependency graph...
[   +1 ms] Caching finalized dependency graph completed, took 101ms

[   +2 ms] Succeeded after 187ms with 0 outputs (0 actions)

[   +9 ms] Building application for the web... (completed in 9.9s)
[   +1 ms] Attempting to connect to browser instance..
```

**Comment by jonahwilliams** [comment]
@FolksyTitan can you share the verbose logs after doing a flutter clean ?

**Comment by dnfield** [comment]
I'm closing this since it's had no activity for > 21 days and has the waiting label.  I believe the bot is just backlogged and missing a bunch of these.  Please feel free to add more details if you want this re-opened.

**Comment by theindianappguy** [comment]
I am facing this problem

**Comment by theindianappguy** [comment]
I resolved it by moving my main in lib directly rather than another folder inside it

**Comment by iapicca** [comment]
Could everyone who still has this problem please file a new issue with the exact descriptions what happens, logs and the output of 'flutter doctor -v'  please.
All system setups can be slightly different so it's always better to open new issues and reference related issues.

**Comment by klokoleva** [comment]
i had same issued, antivirus is disabled. but still attempting. anybody resolve this probllm?
`[   +3 ms] Caching finalized dependency graph...
[ +109 ms] Caching finalized dependency graph completed, took 286ms

[   +7 ms] Succeeded after 1m 31s with 1967 outputs (3687 actions)

[  +11 ms] Building application for the web... (completed in 132.6s)
[   +1 ms] Attempting to connect to browser instance..`

**Comment by zanderso** [comment]
@klokoleva Please file a new issue with full details.
