### ISSUE TITLE
flutter has exited unexpectedly.

### ISSUE THREAD

**Issue by basha97** [flutter/flutter#45753]
When i install flutter in windows and run flutter doctor command it sending crash report that flutter has exited unexpectedly i tried with flutter upgrade command also but same error occurs . please give a clear solution for this to install in windows.
![flutterissue](https://user-images.githubusercontent.com/44155715/69780208-97733100-11d0-11ea-9ee9-e8d06641d680.PNG)

**Comment by jonahwilliams** [comment]
We need the error log at `flutter_01.log` in order to help.

**Comment by basha97** [comment]
[flutter_07.log](https://github.com/flutter/flutter/files/3900264/flutter_07.log)

**Comment by basha97** [comment]
@jonahwilliams  please check it and give me a good solution

**Comment by jonahwilliams** [comment]
The crash stack trace is:

 flutter doctor

```
encountered exception: FormatException: Unexpected character (at character 1)
...
^


#0      _ChunkedJsonParser.fail (dart:convert-patch/convert_patch.dart:1392:5)
#1      _ChunkedJsonParser.parseNumber (dart:convert-patch/convert_patch.dart:1259:9)
#2      _ChunkedJsonParser.parse (dart:convert-patch/convert_patch.dart:924:22)
#3      _parseJson (dart:convert-patch/convert_patch.dart:29:10)
#4      JsonDecoder.convert (dart:convert/json.dart:493:36)
#5      JsonCodec.decode (dart:convert/json.dart:151:41)
#6      VsCode._getVersionFromPackageJson (package:flutter_tools/src/vscode/vscode.dart:222:50)
#7      new VsCode.fromDirectory (package:flutter_tools/src/vscode/vscode.dart:67:34)
#8      VsCode._findInstalled (package:flutter_tools/src/vscode/vscode.dart:207:28)
#9      VsCode._installedWindows (package:flutter_tools/src/vscode/vscode.dart:179:12)
#10     VsCode.allInstalled (package:flutter_tools/src/vscode/vscode.dart:92:14)
#11     VsCodeValidator.installedValidators (package:flutter_tools/src/vscode/vscode_validator.dart:19:10)
#12     _DefaultDoctorValidatorsProvider.validators (package:flutter_tools/src/doctor.dart:65:28)
#13     Doctor.validators (package:flutter_tools/src/doctor.dart:132:46)
#14     Doctor.startValidatorTasks (package:flutter_tools/src/doctor.dart:139:39)
#15     Doctor.diagnose (package:flutter_tools/src/doctor.dart:211:41)
<asynchronous suspension>
#16     _doctorText.<anonymous closure> (package:flutter_tools/runner.dart:202:26)
#17     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:154:29)
<asynchronous suspension>
#18     _rootRun (dart:async/zone.dart:1124:13)
#19     _CustomZone.run (dart:async/zone.dart:1021:19)
#20     _runZoned (dart:async/zone.dart:1516:10)
#21     runZoned (dart:async/zone.dart:1463:12)
#22     AppContext.run (package:flutter_tools/src/base/context.dart:153:18)
<asynchronous suspension>
#23     _doctorText (package:flutter_tools/runner.dart:201:19)
<asynchronous suspension>
#24     _createLocalCrashReport (package:flutter_tools/runner.dart:179:32)
<asynchronous suspension>
#25     _handleToolError (package:flutter_tools/runner.dart:134:33)
<asynchronous suspension>
#26     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:68:22)
<asynchronous suspension>
#27     _rootRun (dart:async/zone.dart:1124:13)
#28     _CustomZone.run (dart:async/zone.dart:1021:19)
#29     _runZoned (dart:async/zone.dart:1516:10)
#30     runZoned (dart:async/zone.dart:1500:12)
#31     run.<anonymous closure> (package:flutter_tools/runner.dart:61:18)
<asynchronous suspension>
#32     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:154:29)
<asynchronous suspension>
#33     _rootRun (dart:async/zone.dart:1124:13)
#34     _CustomZone.run (dart:async/zone.dart:1021:19)
#35     _runZoned (dart:async/zone.dart:1516:10)
#36     runZoned (dart:async/zone.dart:1463:12)
#37     AppContext.run (package:flutter_tools/src/base/context.dart:153:18)
<asynchronous suspension>
#38     runInContext (package:flutter_tools/src/context_runner.dart:59:24)
<asynchronous suspension>
#39     run (package:flutter_tools/runner.dart:50:10)
#40     main (package:flutter_tools/executable.dart:65:9)
<asynchronous suspension>
#41     main (file:///C:/src/flutter/packages/flutter_tools/bin/flutter_tools.dart:8:3)
#42     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:303:32)
#43     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:12)
```

**Comment by jonahwilliams** [comment]
This code is attempting to read the version string for a vscode install at `???\resources\app\package.json` (I don't know where it is installed).

We definitely shouldn't crash here, but you might be able to work around the issue by figuring out where this file is and why it is corrupted.

**Comment by basha97** [comment]
is vscode is the problem for crashing

**Comment by jonahwilliams** [comment]
A malformed config in vscode might be the issue, yes.

**Comment by DanTup** [comment]
We look in several locations for a VS Code installation:

- %localappdata%\Programs\Microsoft VS Code
- %programfiles(x86)%\Microsoft VS Code
- %programfiles%\Microsoft VS Code
- %localappdata%\Programs\Microsoft VS Code Insiders
- %programfiles(x86)%\Microsoft VS Code Insiders
- %programfiles%\Microsoft VS Code Insiders 

We then try to read the version number from the JSON file at `\resources\app\package.json`. It seems like we found this file on your machine, but the JSON wasn't valid. I'd be interested in know if you look in each of those folders (if they exist) at that file and see what the JSON file looks like.

(Jonah has comitted a fix to prevent the crash, but it'd be good to understand what's happened)

**Comment by basha97** [comment]
Yeah sure i will check it .
