### ISSUE TITLE
'flutter build web' works, but 'flutter run -d chrome' fails 

### ISSUE THREAD

**Issue by prujohn** [flutter/flutter#45846]
## Steps to Reproduce
UPDATE:  The only workaround for this I have found is to delete my local project directory and then pull down a fresh copy from repo.  Something must get corrupted in the flutter's working files (or perhaps vscode, not sure).

This one is difficult to repro, until your project gets complex.  In my case I am building a series of apps which sit on a common framework of libraries.  I reference the libraries via pub as path references for now.  Here's my current pubspec dependencies of one such app:

```
dependencies:
  flutter:
    sdk: flutter
  provider: 3.1.0+1
  get_it: ^3.0.3
  firebase: ^6.0.0
  logging: ^0.11.3+2
  term_glyph: ^1.1.0
  pdf: ^1.3.24
  image: ^2.1.4
  aces_core:
    path: ../aces_core
  aces_js_firebase:
    path: ../aces_js_firebase
  aces_data_access_provider:
    path: ../aces_data_provider
```
The problem arises when I add a new library reference to one of the framework libs such as "aces_core".  Most recently, I added the uuid library to "aces_core".  Since then `flutter run -d chrome`  complains that some dependency references are not valid.   I've tried deleting \build folder, and running commands such as `flutter pub cache repair` on all the libs, to no avail.   Here's an example of the error I am currently getting when attempting `flutter run -d chrome`

```
flutter run -d chrome
Launching lib\main.dart on Chrome in debug mode...

Unable to find modules for some sources, this is usually the result of either a
bad import, a missing dependency in a package (or possibly a dev_dependency
needs to move to a real dependency), or a build failure (if importing a
generated file).

Please check the following imports:

`import 'package:uuid/uuid.dart';` from aces_core|lib/utils.dart at 4:1


Failed after 296ms
```
However this command compiles the app with no complaints:

```
flutter build web
```

And the app runs fine with no issues.  This is really just a tooling complaint, as it slows me down for iterative development.  I have to recompile each time with `flutter build web` and then use `firebase serve` to work with the app.

Another important bit of information:  This issue is project specific.  If I create a new app, and reference the same libraries such as "aces_core", then `flutter run -d chrome` will run in that app with no issues.  This suggests to me that some sort of caching system is becoming out of sync in certain situations, such as the one I describe.

Is there something I can do to "reset" the flutter debug tooling in a project in order to avoid this?

**Target Platform:**
Web
**Target OS version/browser:**
Chrome/Web
**Devices:**
All

## Logs

```
C:\Users\john\dev\aces>flutter run -d chrome --verbose
[  +24 ms] executing: [c:\src\flutter\] git -c log.showSignature=false log -n 1 --pretty=format:%H
[  +74 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[        ] b9a56b9f48462d897101284f5f57b8568ef683c6
[        ] executing: [c:\src\flutter\] git describe --match v*.*.* --first-parent --long --tags
[  +87 ms] Exit code 0 from: git describe --match v*.*.* --first-parent --long --tags
[        ] v1.12.15-35-gb9a56b9f4
[   +7 ms] executing: [c:\src\flutter\] git rev-parse --abbrev-ref --symbolic @{u}
[  +45 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/master
[        ] executing: [c:\src\flutter\] git ls-remote --get-url origin
[  +40 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[  +92 ms] executing: [c:\src\flutter\] git rev-parse --abbrev-ref HEAD
[  +38 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[   +1 ms] master
[  +39 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +4 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +38 ms] executing: C:\Users\john\AppData\Local\Android\sdk\platform-tools\adb.exe devices -l
[  +25 ms] Exit code 0 from: C:\Users\john\AppData\Local\Android\sdk\platform-tools\adb.exe devices -l
[        ] List of devices attached
[  +13 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[   +3 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +86 ms] Found plugin google_sign_in at c:\src\flutter\.pub-cache\hosted\pub.dartlang.org\google_sign_in-4.0.14\
[  +85 ms] Found plugin google_sign_in at c:\src\flutter\.pub-cache\hosted\pub.dartlang.org\google_sign_in-4.0.14\
[  +68 ms] Generating C:\Users\john\dev\aces\android\app\src\main\java\io\flutter\plugins\GeneratedPluginRegistrant.java
[  +96 ms] Launching lib\main.dart on Chrome in debug mode...
[   +2 ms] Building application for the web...
[ +176 ms] Found plugin google_sign_in at c:\src\flutter\.pub-cache\hosted\pub.dartlang.org\google_sign_in-4.0.14\
[+8365 ms] Daemon is already running.
[ +713 ms] About to build [web]...
[   +4 ms] Updating asset graph...
[   +2 ms] Updating asset graph completed, took 4ms

[        ] Running build...
[  +93 ms] Running build completed, took 39ms

[   +1 ms] Caching finalized dependency graph...
[  +10 ms] Caching finalized dependency graph completed, took 77ms

[  +10 ms] Unable to find modules for some sources, this is usually the result of either a
           bad import, a missing dependency in a package (or possibly a dev_dependency
           needs to move to a real dependency), or a build failure (if importing a
           generated file).
           
           Please check the following imports:
           
           `import 'package:uuid/uuid.dart';` from aces_core|lib/utils.dart at 4:1
           
[   +3 ms] #0      Module.computeTransitiveDependencies (package:build_modules/src/modules.dart:172:7)
           <asynchronous suspension>
           #1      _ensureTransitiveJsModules (package:build_web_compilers/src/dev_compiler_bootstrap.dart:166:37)
           #2      bootstrapDdc (package:build_web_compilers/src/dev_compiler_bootstrap.dart:57:33)
           <asynchronous suspension>
           #3      FlutterWebEntrypointBuilder.build (package:flutter_tools/src/build_runner/build_script.dart:232:11)
           #4      runBuilder.buildForInput (package:build/src/generate/run_builder.dart:55:21)
           #5      MappedListIterable.elementAt (dart:_internal/iterable.dart:417:29)
           #6      ListIterator.moveNext (dart:_internal/iterable.dart:346:26)
           #7      Future.wait (dart:async/future.dart:393:26)
           #8      runBuilder.<anonymous closure> (package:build/src/generate/run_builder.dart:61:36)
           #9      _rootRun (dart:async/zone.dart:1126:13)
           #10     _CustomZone.run (dart:async/zone.dart:1023:19)
           #11     _runZoned (dart:async/zone.dart:1518:10)
           #12     runZoned (dart:async/zone.dart:1502:12)
           #13     scopeLogAsync (package:build/src/builder/logging.dart:22:3)
           #14     runBuilder (package:build/src/generate/run_builder.dart:61:9)
           #15     _SingleBuild._runForInput.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:build_runner_core/src/generate/build_impl.dart:478:19)
           #16     _NoOpBuilderActionTracker.trackStage (package:build_runner_core/src/generate/performance_tracker.dart:300:15)
           #17     _SingleBuild._runForInput.<anonymous closure>.<anonymous closure> (package:build_runner_core/src/generate/build_impl.dart:476:23)
           <asynchronous suspension>
           #18     NoOpTimeTracker.track (package:timing/src/timing.dart:222:44)
           #19     _SingleBuild._runForInput.<anonymous closure> (package:build_runner_core/src/generate/build_impl.dart:434:22)
           #20     Pool.withResource (package:pool/pool.dart:127:28)
           <asynchronous suspension>
           #21     _SingleBuild._runForInput (package:build_runner_core/src/generate/build_impl.dart:430:17)
           #22     _SingleBuild._runBuilder.<anonymous closure> (package:build_runner_core/src/generate/build_impl.dart:378:38)
           #23     MappedIterator.moveNext (dart:_internal/iterable.dart:395:18)
           #24     Future.wait (dart:async/future.dart:393:26)
           #25     _SingleBuild._runBuilder (package:build_runner_core/src/generate/build_impl.dart:377:36)
           #26     _SingleBuild._runPhases.<anonymous closure>.<anonymous closure> (package:build_runner_core/src/generate/build_impl.dart:323:20)
           <asynchronous suspension>
           #27     _NoOpBuildPerformanceTracker.trackBuildPhase (package:build_runner_core/src/generate/performance_tracker.dart:184:15)
           #28     _SingleBuild._runPhases.<anonymous closure> (package:build_runner_core/src/generate/build_impl.dart:319:47)
           <asynchronous suspension>
           #29     NoOpTimeTracker.track (package:timing/src/timing.dart:222:44)
           #30     _SingleBuild._runPhases (package:build_runner_core/src/generate/build_impl.dart:313:32)
           #31     logTimedAsync (package:build_runner_core/src/logging/logging.dart:25:30)
           #32     _SingleBuild._safeBuild.<anonymous closure> (package:build_runner_core/src/generate/build_impl.dart:270:26)
           <asynchronous suspension>
           #33     _rootRun (dart:async/zone.dart:1126:13)
           #34     _CustomZone.run (dart:async/zone.dart:1023:19)
           #35     _runZoned (dart:async/zone.dart:1518:10)
           #36     runZoned (dart:async/zone.dart:1502:12)
           #37     _SingleBuild._safeBuild (package:build_runner_core/src/generate/build_impl.dart:265:5)
           #38     _SingleBuild.run (package:build_runner_core/src/generate/build_impl.dart:212:24)
           #39     BuildImpl.run (package:build_runner_core/src/generate/build_impl.dart:97:56)
           #40     BuildRunnerDaemonBuilder.build (package:build_runner/src/daemon/daemon_builder.dart:111:35)
           #41     Server._build.<anonymous closure> (package:build_daemon/src/server.dart:122:25)
           #42     Pool.withResource (package:pool/pool.dart:127:28)
           <asynchronous suspension>
           #43     Server._build (package:build_daemon/src/server.dart:119:13)
           #44     Server.listen.<anonymous closure>.<anonymous closure> (package:build_daemon/src/server.dart:85:17)
           <asynchronous suspension>
           #45     _rootRunUnary (dart:async/zone.dart:1134:38)
           #46     _CustomZone.runUnary (dart:async/zone.dart:1031:19)
           #47     _CustomZone.runUnaryGuarded (dart:async/zone.dart:933:7)
           #48     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:338:11)
           #49     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:265:7)
           #50     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:766:19)
           #51     _StreamController._add (dart:async/stream_controller.dart:642:7)
           #52     _StreamController.add (dart:async/stream_controller.dart:588:5)
           #53     new WebSocketImpl.fromSocket.<anonymous closure> (package:web_socket_channel/src/copy/web_socket_impl.dart:719:21)
           #54     _rootRunUnary (dart:async/zone.dart:1134:38)
           #55     _CustomZone.runUnary (dart:async/zone.dart:1031:19)
           #56     _CustomZone.runUnaryGuarded (dart:async/zone.dart:933:7)
           #57     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:338:11)
           #58     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:265:7)
           #59     _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:70:11)
           #60     _EventSinkWrapper.add (dart:async/stream_transformers.dart:17:11)
           #61     _WebSocketProtocolTransformer._messageFrameEnd (package:web_socket_channel/src/copy/web_socket_impl.dart:316:22)
           #62     _WebSocketProtocolTransformer.add (package:web_socket_channel/src/copy/web_socket_impl.dart:214:46)
           #63     _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:122:24)
           #64     _rootRunUnary (dart:async/zone.dart:1134:38)
           #65     _CustomZone.runUnary (dart:async/zone.dart:1031:19)
           #66     _CustomZone.runUnaryGuarded (dart:async/zone.dart:933:7)
           #67     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:338:11)
           #68     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:265:7)
           #69     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:766:19)
           #70     _StreamController._add (dart:async/stream_controller.dart:642:7)
           #71     _StreamController.add (dart:async/stream_controller.dart:588:5)
           #72     _Socket._onData (dart:io-patch/socket_patch.dart:1831:41)
           #73     _rootRunUnary (dart:async/zone.dart:1138:13)
           #74     _CustomZone.runUnary (dart:async/zone.dart:1031:19)
           #75     _CustomZone.runUnaryGuarded (dart:async/zone.dart:933:7)
           #76     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:338:11)
           #77     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:265:7)
           #78     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:766:19)
           #79     _StreamController._add (dart:async/stream_controller.dart:642:7)
           #80     _StreamController.add (dart:async/stream_controller.dart:588:5)
           #81     new _RawSocket.<anonymous closure> (dart:io-patch/socket_patch.dart:1379:33)
           #82     _NativeSocket.issueReadEvent.issue (dart:io-patch/socket_patch.dart:899:14)
           #83     _microtaskLoop (dart:async/schedule_microtask.dart:43:21)
           #84     _startMicrotaskLoop (dart:async/schedule_microtask.dart:52:5)
           #85     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
           #86     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:175:5)

[  +10 ms] Failed after 126ms
[  +11 ms] Building application for the web... (completed in 9.4s)
[   +1 ms] "flutter run" took 9,927ms.
Failed to build application for the Web.

#0      throwToolExit (package:flutter_tools/src/base/common.dart:28:3)
#1      _DwdsResidentWebRunner.run (package:flutter_tools/src/build_runner/resident_web_runner.dart:660:7)
<asynchronous suspension>
#2      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:505:37)
<asynchronous suspension>
#3      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:620:18)
#4      _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:74:64)
#5      _rootRunUnary (dart:async/zone.dart:1134:38)
#6      _CustomZone.runUnary (dart:async/zone.dart:1031:19)
#7      _FutureListener.handleValue (dart:async/future_impl.dart:140:18)
#8      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:682:45)
#9      Future._propagateToListeners (dart:async/future_impl.dart:711:32)
#10     Future._completeWithValue (dart:async/future_impl.dart:526:5)
#11     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:33:15)
#12     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:291:13)
#13     RunCommand.usageValues (package:flutter_tools/src/commands/run.dart)
#14     _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:74:64)
#15     _rootRunUnary (dart:async/zone.dart:1134:38)
#16     _CustomZone.runUnary (dart:async/zone.dart:1031:19)
#17     _FutureListener.handleValue (dart:async/future_impl.dart:140:18)
#18     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:682:45)
#19     Future._propagateToListeners (dart:async/future_impl.dart:711:32)
#20     Future._completeWithValue (dart:async/future_impl.dart:526:5)
#21     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:33:15)
#22     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:291:13)
#23     IosProject.isSwift (package:flutter_tools/src/project.dart)
#24     _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:74:64)
#25     _rootRunUnary (dart:async/zone.dart:1134:38)
#26     _CustomZone.runUnary (dart:async/zone.dart:1031:19)
#27     _FutureListener.handleValue (dart:async/future_impl.dart:140:18)
#28     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:682:45)
#29     Future._propagateToListeners (dart:async/future_impl.dart:711:32)
#30     Future._completeWithValue (dart:async/future_impl.dart:526:5)
#31     Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:556:7)
#32     _rootRun (dart:async/zone.dart:1126:13)
#33     _CustomZone.run (dart:async/zone.dart:1023:19)
#34     _CustomZone.runGuarded (dart:async/zone.dart:925:7)
#35     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:965:23)
#36     _microtaskLoop (dart:async/schedule_microtask.dart:43:21)
#37     _startMicrotaskLoop (dart:async/schedule_microtask.dart:52:5)
#38     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
#39     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:175:5)
```

```
C:\Users\john\dev\aces>flutter analyze
Analyzing aces...

   info - The declaration '_logger' isn't referenced - lib\ui\pages\appliances_only_assessment_page.dart:17:8 - unused_element
   info - The declaration '_logger' isn't referenced - lib\ui\pages\appliances_only_summary_page.dart:16:8 - unused_element
   info - The declaration '_logger' isn't referenced - lib\ui\pages\assessment_page.dart:17:8 - unused_element
   info - The declaration '_logger' isn't referenced - lib\ui\pages\consult_page.dart:16:8 - unused_element
   info - The declaration '_logger' isn't referenced - lib\ui\pages\enable_page.dart:19:8 - unused_element
   info - The value of the field '_logger' isn't used - lib\ui\views\app_view.dart:12:9 - unused_field
   info - The value of the field '_logger' isn't used - lib\ui\views\app_view.dart:24:9 - unused_field
   info - Unused import: 'package:flutter/material.dart' - test\widget_test.dart:8:8 - unused_import

8 issues found. (ran in 2.1s)
```

```
C:\Users\john\dev\aces>flutter doctor -v
[√] Flutter (Channel master, v1.12.16-pre.35, on Microsoft Windows [Version 10.0.17763.864], locale en-US)
    • Flutter version 1.12.16-pre.35 at c:\src\flutter
    • Framework revision b9a56b9f48 (21 hours ago), 2019-11-29 20:40:44 -0500
    • Engine revision 8672e79af8
    • Dart version 2.7.0


[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at C:\Users\john\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 3.5)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 40.1.2
    • Dart plugin version 191.8423
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)

[√] VS Code (version 1.40.2)
    • VS Code at C:\Users\john\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.6.0

[√] Connected device (2 available)
    • Chrome     • chrome     • web-javascript • Google Chrome 78.0.3904.108
    • Web Server • web-server • web-javascript • Flutter Tools

• No issues found!
```

**Comment by iapicca** [comment]
Hi @prujohn 
from your update I understand that the issue is resolved, correct?
thank you

**Comment by prujohn** [comment]
@iapicca Correct.  The workaround is doable.  I still think there is an outstanding issue with flutter where this situation can arise when referencing path package dependencies (or let's say non-versioned dependencies.  When something in those dependencies changes (such as adding a new dependency to them), flutter's tracking mechanisms sometimes in the parent project get into a bad state and the project files have to be put into a "clean" flutter project in order for `flutter run ...` to work again.

Not a huge deal, but wanted to document it at least.

**Comment by iapicca** [comment]
Hi again @prujohn 
thanks for letting me know
