### ISSUE TITLE
[iOS] semantics - Failed assertion: line 1245 pos 12: 'value.isFinite'

### ISSUE THREAD

**Issue by Greatcallie** [flutter/flutter#45866]
When the exception was thrown, this was the stack: 
```
#2      SemanticsNode.rect= (package:flutter/src/semantics/semantics.dart:1245:12)
#3      _SwitchableSemanticsFragment.compileChildren (package:flutter/src/rendering/object.dart:3588:11)
#4      _SyncIterator.moveNext (dart:core-patch/core_patch.dart:144:12)
#5      _SyncIterator.moveNext (dart:core-patch/core_patch.dart:137:32)
#6      ExpandIterator.moveNext (dart:_internal/iterable.dart:476:31)
...
════════════════════════════════════════════════════════════════════════════════════════════════════

════════ (2) Exception caught by scheduler library ═════════════════════════════════════════════════
SemanticsNode#54(Rect.fromLTRB(0.0, 0.0, 280.7, 93.6), tags: [RenderViewport.twoPane]) (with SemanticsOwner#6fef9) tried to set a non-finite rect.
'package:flutter/src/semantics/semantics.dart':
Failed assertion: line 1245 pos 12: 'value.isFinite'

```

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel beta, v1.11.0, on Mac OS X 10.15.1 19B88, locale en-US)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 11.2.1)
[✓] Android Studio (version 3.5)
[✓] VS Code (version 1.36.1)
[✓] Connected device (1 available)

• No issues found!
```

**Comment by Greatcallie** [comment]
Sorry i cant really tell what caused it since i get no information where the bug is coming from. It just happens while i scroll back up

**Comment by iapicca** [comment]
Hi @Greatcallie 
could you please describe the issue in details and
provide a minimal code sample to reproduce the problem?
Thank you

**Comment by Greatcallie** [comment]
I will see what I can do. But let's note one thing. This error only happens
on iOS. It works perfectly on Android

**Comment by Greatcallie** [comment]
And the lastest flutter update broke the code - it worked perfectly on iOS before the last update a few days ago.

Try dragging at the bottom

 class BugClass extends StatelessWidget {
  final List<String> interests = ["chatting", "gisting", "joking"];
  final List<String> hobbies = ["laughing", "cooking", "playing"];
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        body: CustomScrollView(
          slivers: <Widget>[
            SliverAppBar(
              expandedHeight: 0,
              flexibleSpace: Padding(
                  padding: const EdgeInsets.all(2.0), child: SizedBox()),
              title: Text('Sample text'),
            ),
            SliverFillRemaining(
              hasScrollBody: false,
              child: new Column(
                crossAxisAlignment: CrossAxisAlignment.start,
                children: <Widget>[
                  Center(
                    child: IconButton(
                      icon: Icon(
                        Icons.star,
                        color: Colors.amber,
                      ),
                    ),
                  ),
                  new Padding(
                      padding: const EdgeInsets.all(24.0),
                      child: Column(
                        crossAxisAlignment: CrossAxisAlignment.start,
                        children: <Widget>[
                          new Text(
                            'Sample text',
                            style: Theme.of(context).textTheme.headline,
                          ),
                          new Padding(
                            padding: const EdgeInsets.only(top: 4.0),
                            child: Text(
                              'Sample text',
                              style: Theme.of(context).textTheme.title,
                            ),
                          ),
                          new Text(
                            'Sample text',
                            style: Theme.of(context).textTheme.headline,
                          ),
                          new Padding(
                            padding: const EdgeInsets.only(top: 4.0),
                            child: Text(
                              'Sample text',
                              style: Theme.of(context).textTheme.title,
                            ),
                          ),
                          new Padding(
                            padding: const EdgeInsets.only(top: 4.0),
                            child: SizedBox(
                              height: 100,
                              width: 400,
                            ),
                          ),
                          new Padding(
                            padding: const EdgeInsets.only(top: 20.0),
                            child: new Text("About",
                                style: Theme.of(context).textTheme.title),
                          ),
                          new Padding(
                            padding: const EdgeInsets.only(top: 10.0),
                            child: new Text(
                              'Sample text',
                              style: Theme.of(context).textTheme.body1,
                            ),
                          ),
                          new Padding(
                            padding: const EdgeInsets.only(top: 20.0),
                            child: interests.length > 0
                                ? new Text("Interests",
                                    style: Theme.of(context).textTheme.title)
                                : SizedBox(),
                          ),
                          new GridView.builder(
                            shrinkWrap: true,
                            itemCount: interests.length,
                            gridDelegate:
                                SliverGridDelegateWithFixedCrossAxisCount(
                                    crossAxisCount: 3,
                                    childAspectRatio: 3,
                                    mainAxisSpacing: 3,
                                    crossAxisSpacing: 3),
                            itemBuilder: (BuildContext context, int index) {
                              return _createPillText(interests[index]);
                            },
                          ),
                          new Padding(
                            padding: const EdgeInsets.only(top: 20.0),
                            child: hobbies.length > 0
                                ? new Text("Hobbies",
                                    style: Theme.of(context).textTheme.title)
                                : SizedBox(),
                          ),
                          new GridView.builder(
                            shrinkWrap: true,
                            itemCount: hobbies.length,
                            gridDelegate:
                                SliverGridDelegateWithFixedCrossAxisCount(
                                    crossAxisCount: 3,
                                    childAspectRatio: 3,
                                    mainAxisSpacing: 3,
                                    crossAxisSpacing: 3),
                            itemBuilder: (BuildContext context, int index) {
                              return _createPillText(hobbies[index]);
                            },
                          )
                        ],
                      )),
                ],
              ),
            )
          ],
        ),
      ),
    );
  }

  Widget _createPillText(
    String text, {
    Color backgroundColor = Colors.amber,
  }) {
    return new ClipRRect(
      borderRadius: new BorderRadius.circular(10.0),
      child: new MaterialButton(
        onPressed: () {},
        color: backgroundColor,
        child: new Text(text),
      ),
    );
  }
}

**Comment by Greatcallie** [comment]
drag on top of the texts in yellow and you will get the error

**Comment by gaaclarke** [comment]
I got a similar error when trying to reproduce the sample code in this issue: https://github.com/flutter/flutter/issues/45902#issuecomment-562539612

**Comment by gaaclarke** [comment]
> And the lastest flutter update broke the code - it worked perfectly on iOS before the last update a few days ago.
> 
> Try dragging at the bottom
> 
> code sample

@Greatcallie This sample code isn't complete.  There isn't a main function for one thing.  Can you please post a complete example.

**Comment by Greatcallie** [comment]
Just add a main function. It's a MaterialApp...

**Comment by dnfield** [comment]
@Greatcallie - when I try to run your app on an iOS Simulator I get a different exceptoin and a blank white screen...

**Comment by Greatcallie** [comment]
You are not running the code properly.
void main() => runApp(BugClass())

**Comment by dnfield** [comment]
I had that :)  But I get exceptions:

```
flutter: ══╡ EXCEPTION CAUGHT BY RENDERING LIBRARY ╞═════════════════════════════════════════════════════════
flutter: The following assertion was thrown during performLayout():
flutter: RenderShrinkWrappingViewport does not support returning intrinsic dimensions.
flutter: Calculating the intrinsic dimensions would require instantiating every child of the viewport, which
flutter: defeats the point of viewports being lazy.
flutter: If you are merely trying to shrink-wrap the viewport in the main axis direction, you should be able
flutter: to achieve that effect by just giving the viewport loose constraints, without needing to measure its
flutter: intrinsic dimensions.
flutter:
flutter: The relevant error-causing widget was:
flutter:   SliverFillRemaining file:///Users/dnfield/src/flutter_projects/textfield/lib/main.dart:20:12
flutter:
flutter: When the exception was thrown, this was the stack:
flutter: #0      RenderShrinkWrappingViewport.debugThrowIfNotCheckingIntrinsics.<anonymous closure> (package:flutter/src/rendering/viewport.dart:1667:9)
flutter: #1      RenderShrinkWrappingViewport.debugThrowIfNotCheckingIntrinsics (package:flutter/src/rendering/viewport.dart:1681:6)
flutter: #2      RenderViewportBase.computeMaxIntrinsicHeight (package:flutter/src/rendering/viewport.dart:378:12)
flutter: #3      RenderBox._computeIntrinsicDimension.<anonymous closure> (package:flutter/src/rendering/box.dart:1298:23)
flutter: #4      _LinkedHashMapMixin.putIfAbsent (dart:collection-patch/compact_hash.dart:293:23)
flutter: #5      RenderBox._computeIntrinsicDimension (package:flutter/src/rendering/box.dart:1296:41)
flutter: #6      RenderBox.getMaxIntrinsicHeight (package:flutter/src/rendering/box.dart:1641:12)
flutter: #7      RenderProxyBoxMixin.computeMaxIntrinsicHeight (package:flutter/src/rendering/proxy_box.dart:91:20)
flutter: #8      RenderBox._computeIntrinsicDimension.<anonymous closure> (package:flutter/src/rendering/box.dart:1298:23)
flutter: #9      _LinkedHashMapMixin.putIfAbsent (dart:collection-patch/compact_hash.dart:293:23)
flutter: #10     RenderBox._computeIntrinsicDimension (package:flutter/src/rendering/box.dart:1296:41)
flutter: #11     RenderBox.getMaxIntrinsicHeight (package:flutter/src/rendering/box.dart:1641:12)
flutter: #12     RenderProxyBoxMixin.computeMaxIntrinsicHeight (package:flutter/src/rendering/proxy_box.dart:91:20)
flutter: #13     RenderBox._computeIntrinsicDimension.<anonymous closure> (package:flutter/src/rendering/box.dart:1298:23)
flutter: #14     _LinkedHashMapMixin.putIfAbsent (dart:collection-patch/compact_hash.dart:293:23)
flutter: #15     RenderBox._computeIntrinsicDimension (package:flutter/src/rendering/box.dart:1296:41)
flutter: #16     RenderBox.getMaxIntrinsicHeight (package:flutter/src/rendering/box.dart:1641:12)
flutter: #17     RenderProxyBoxMixin.computeMaxIntrinsicHeight (package:flutter/src/rendering/proxy_box.dart:91:20)
flutter: #18     RenderBox._computeIntrinsicDimension.<anonymous closure> (package:flutter/src/rendering/box.dart:1298:23)
flutter: #19     _LinkedHashMapMixin.putIfAbsent (dart:collection-patch/compact_hash.dart:293:23)
flutter: #20     RenderBox._computeIntrinsicDimension (package:flutter/src/rendering/box.dart:1296:41)
flutter: #21     RenderBox.getMaxIntrinsicHeight (package:flutter/src/rendering/box.dart:1641:12)
flutter: #22     RenderProxyBoxMixin.computeMaxIntrinsicHeight (package:flutter/src/rendering/proxy_box.dart:91:20)
flutter: #23     RenderBox._computeIntrinsicDimension.<anonymous closure> (package:flutter/src/rendering/box.dart:1298:23)
flutter: #24     _LinkedHashMapMixin.putIfAbsent (dart:collection-patch/compact_hash.dart:293:23)
flutter: #25     RenderBox._computeIntrinsicDimension (package:flutter/src/rendering/box.dart:1296:41)
flutter: #26     RenderBox.getMaxIntrinsicHeight (package:flutter/src/rendering/box.dart:1641:12)
flutter: #27     RenderProxyBoxMixin.computeMaxIntrinsicHeight (package:flutter/src/rendering/proxy_box.dart:91:20)
flutter: #28     RenderBox._computeIntrinsicDimension.<anonymous closure> (package:flutter/src/rendering/box.dart:1298:23)
flutter: #29     _LinkedHashMapMixin.putIfAbsent (dart:collection-patch/compact_hash.dart:293:23)
flutter: #30     RenderBox._computeIntrinsicDimension (package:flutter/src/rendering/box.dart:1296:41)
flutter: #31     RenderBox.getMaxIntrinsicHeight (package:flutter/src/rendering/box.dart:1641:12)
flutter: #32     RenderProxyBoxMixin.computeMaxIntrinsicHeight (package:flutter/src/rendering/proxy_box.dart:91:20)
flutter: #33     RenderBox._computeIntrinsicDimension.<anonymous closure> (package:flutter/src/rendering/box.dart:1298:23)
flutter: #34     _LinkedHashMapMixin.putIfAbsent (dart:collection-patch/compact_hash.dart:293:23)
flutter: #35     RenderBox._computeIntrinsicDimension (package:flutter/src/rendering/box.dart:1296:41)
flutter: #36     RenderBox.getMaxIntrinsicHeight (package:flutter/src/rendering/box.dart:1641:12)
flutter: #37     RenderFlex.computeMaxIntrinsicHeight.<anonymous closure> (package:flutter/src/rendering/flex.dart:595:60)
flutter: #38     RenderFlex._getIntrinsicSize (package:flutter/src/rendering/flex.dart:503:39)
flutter: #39     RenderFlex.computeMaxIntrinsicHeight (package:flutter/src/rendering/flex.dart:592:12)
flutter: #40     RenderBox._computeIntrinsicDimension.<anonymous closure> (package:flutter/src/rendering/box.dart:1298:23)
flutter: #41     _LinkedHashMapMixin.putIfAbsent (dart:collection-patch/compact_hash.dart:293:23)
flutter: #42     RenderBox._computeIntrinsicDimension (package:flutter/src/rendering/box.dart:1296:41)
flutter: #43     RenderBox.getMaxIntrinsicHeight (package:flutter/src/rendering/box.dart:1641:12)
flutter: #44     RenderPadding.computeMaxIntrinsicHeight (package:flutter/src/rendering/shifted_box.dart:190:20)
flutter: #45     RenderBox._computeIntrinsicDimension.<anonymous closure> (package:flutter/src/rendering/box.dart:1298:23)
flutter: #46     _LinkedHashMapMixin.putIfAbsent (dart:collection-patch/compact_hash.dart:293:23)
flutter: #47     RenderBox._computeIntrinsicDimension (package:flutter/src/rendering/box.dart:1296:41)
flutter: #48     RenderBox.getMaxIntrinsicHeight (package:flutter/src/rendering/box.dart:1641:12)
flutter: #49     RenderFlex.computeMaxIntrinsicHeight.<anonymous closure> (package:flutter/src/rendering/flex.dart:595:60)
flutter: #50     RenderFlex._getIntrinsicSize (package:flutter/src/rendering/flex.dart:503:39)
flutter: #51     RenderFlex.computeMaxIntrinsicHeight (package:flutter/src/rendering/flex.dart:592:12)
flutter: #52     RenderBox._computeIntrinsicDimension.<anonymous closure> (package:flutter/src/rendering/box.dart:1298:23)
flutter: #53     _LinkedHashMapMixin.putIfAbsent (dart:collection-patch/compact_hash.dart:293:23)
flutter: #54     RenderBox._computeIntrinsicDimension (package:flutter/src/rendering/box.dart:1296:41)
flutter: #55     RenderBox.getMaxIntrinsicHeight (package:flutter/src/rendering/box.dart:1641:12)
flutter: #56     RenderSliverFillRemaining.performLayout (package:flutter/src/rendering/sliver_fill.dart:130:31)
flutter: #57     RenderObject.layout (package:flutter/src/rendering/object.dart:1767:7)
flutter: #58     RenderViewportBase.layoutChildSequence (package:flutter/src/rendering/viewport.dart:451:13)
flutter: #59     RenderViewport._attemptLayout (package:flutter/src/rendering/viewport.dart:1434:12)
flutter: #60     RenderViewport.performLayout (package:flutter/src/rendering/viewport.dart:1343:20)
flutter: #61     RenderObject.layout (package:flutter/src/rendering/object.dart:1767:7)
flutter: #62     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
flutter: #63     RenderObject.layout (package:flutter/src/rendering/object.dart:1767:7)
flutter: #64     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
flutter: #65     RenderObject.layout (package:flutter/src/rendering/object.dart:1767:7)
flutter: #66     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
flutter: #67     RenderObject.layout (package:flutter/src/rendering/object.dart:1767:7)
flutter: #68     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
flutter: #69     RenderObject.layout (package:flutter/src/rendering/object.dart:1767:7)
flutter: #70     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
flutter: #71     RenderObject.layout (package:flutter/src/rendering/object.dart:1767:7)
flutter: #72     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
flutter: #73     RenderObject.layout (package:flutter/src/rendering/object.dart:1767:7)
flutter: #74     MultiChildLayoutDelegate.layoutChild (package:flutter/src/rendering/custom_layout.dart:163:11)
flutter: #75     _ScaffoldLayout.performLayout (package:flutter/src/material/scaffold.dart:477:7)
flutter: #76     MultiChildLayoutDelegate._callPerformLayout (package:flutter/src/rendering/custom_layout.dart:232:7)
flutter: #77     RenderCustomMultiChildLayoutBox.performLayout (package:flutter/src/rendering/custom_layout.dart:391:14)
flutter: #78     RenderObject.layout (package:flutter/src/rendering/object.dart:1767:7)
flutter: #79     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
flutter: #80     RenderObject.layout (package:flutter/src/rendering/object.dart:1767:7)
flutter: #81     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
flutter: #82     _RenderCustomClip.performLayout (package:flutter/src/rendering/proxy_box.dart:1235:11)
flutter: #83     RenderObject.layout (package:flutter/src/rendering/object.dart:1767:7)
flutter: #84     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
flutter: #85     RenderObject.layout (package:flutter/src/rendering/object.dart:1767:7)
flutter: #86     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
flutter: #87     RenderObject.layout (package:flutter/src/rendering/object.dart:1767:7)
flutter: #88     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
flutter: #89     RenderObject.layout (package:flutter/src/rendering/object.dart:1767:7)
flutter: #90     RenderStack.performLayout (package:flutter/src/rendering/stack.dart:503:15)
flutter: #91     RenderObject.layout (package:flutter/src/rendering/object.dart:1767:7)
flutter: #92     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
flutter: #93     RenderObject.layout (package:flutter/src/rendering/object.dart:1767:7)
flutter: #94     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
flutter: #95     RenderObject.layout (package:flutter/src/rendering/object.dart:1767:7)
flutter: #96     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
flutter: #97     RenderObject.layout (package:flutter/src/rendering/object.dart:1767:7)
flutter: #98     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
flutter: #99     RenderObject.layout (package:flutter/src/rendering/object.dart:1767:7)
flutter: #100    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
flutter: #101    RenderObject.layout (package:flutter/src/rendering/object.dart:1767:7)
flutter: #102    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
flutter: #103    RenderOffstage.performLayout (package:flutter/src/rendering/proxy_box.dart:3207:13)
flutter: #104    RenderObject.layout (package:flutter/src/rendering/object.dart:1767:7)
flutter: #105    RenderStack.performLayout (package:flutter/src/rendering/stack.dart:503:15)
flutter: #106    RenderObject.layout (package:flutter/src/rendering/object.dart:1767:7)
flutter: #107    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
flutter: #108    RenderObject.layout (package:flutter/src/rendering/object.dart:1767:7)
flutter: #109    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
flutter: #110    RenderObject.layout (package:flutter/src/rendering/object.dart:1767:7)
flutter: #111    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
flutter: #112    RenderObject.layout (package:flutter/src/rendering/object.dart:1767:7)
flutter: #113    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
flutter: #114    RenderObject.layout (package:flutter/src/rendering/object.dart:1767:7)
flutter: #115    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
flutter: #116    RenderObject.layout (package:flutter/src/rendering/object.dart:1767:7)
flutter: #117    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
flutter: #118    RenderObject.layout (package:flutter/src/rendering/object.dart:1767:7)
flutter: #119    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
flutter: #120    RenderObject.layout (package:flutter/src/rendering/object.dart:1767:7)
flutter: #121    RenderView.performLayout (package:flutter/src/rendering/view.dart:167:13)
flutter: #122    RenderObject._layoutWithoutResize (package:flutter/src/rendering/object.dart:1628:7)
flutter: #123    PipelineOwner.flushLayout (package:flutter/src/rendering/object.dart:888:18)
flutter: #124    RendererBinding.drawFrame (package:flutter/src/rendering/binding.dart:401:19)
flutter: #125    WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:776:13)
flutter: #126    RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:283:5)
flutter: #127    SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1108:15)
flutter: #128    SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1047:9)
flutter: #129    SchedulerBinding.scheduleWarmUpFrame.<anonymous closure> (package:flutter/src/scheduler/binding.dart:856:7)
flutter: #138    _Timer._runTimers (dart:isolate-patch/timer_impl.dart:384:19)
flutter: #139    _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:418:5)
flutter: #140    _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:174:12)
flutter: (elided 8 frames from package dart:async and package dart:async-patch)
flutter:
flutter: The following RenderObject was being processed when the exception was fired: RenderSliverFillRemaining#9dd8e relayoutBoundary=up1 NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE:
flutter:   creator: SliverFillRemaining ← Viewport ← IgnorePointer-[GlobalKey#a57a7] ← Semantics ←
flutter:     _PointerListener ← Listener ← _GestureSemantics ←
flutter:     RawGestureDetector-[LabeledGlobalKey<RawGestureDetectorState>#b7dfb] ← _PointerListener ← Listener
flutter:     ← _ScrollableScope ← _ScrollSemantics-[GlobalKey#b318f] ← ⋯
flutter:   parentData: paintOffset=Offset(0.0, 0.0) (can use size)
flutter:   constraints: SliverConstraints(AxisDirection.down, GrowthDirection.forward, ScrollDirection.idle,
flutter:     scrollOffset: 0.0, remainingPaintExtent: 796.0, crossAxisExtent: 414.0, crossAxisDirection:
flutter:     AxisDirection.right, viewportMainAxisExtent: 896.0, remainingCacheExtent: 1046.0 cacheOrigin: 0.0
flutter:     )
flutter:   geometry: null
flutter: This RenderObject had the following descendants (showing up to depth 5):
flutter:     child: RenderFlex#d9aae NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
flutter:       child 1: RenderPositionedBox#d40f8 NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
flutter:         child: RenderSemanticsAnnotations#172e2 NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
flutter:           child: RenderSemanticsAnnotations#1ad9b NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
flutter:             child: RenderMouseRegion#ad25a NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
flutter:       child 2: RenderPadding#c47f8 NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
flutter:         child: RenderFlex#adf95 NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
flutter:           child 1: RenderParagraph#9efe8 NEEDS-LAYOUT NEEDS-PAINT
flutter:             text: TextSpan
flutter:           child 2: RenderPadding#9fe1e NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
flutter:             child: RenderParagraph#c855a NEEDS-LAYOUT NEEDS-PAINT
flutter:           child 3: RenderParagraph#3f083 NEEDS-LAYOUT NEEDS-PAINT
flutter:             text: TextSpan
flutter:           child 4: RenderPadding#2c4a8 NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
flutter:             child: RenderParagraph#61958 NEEDS-LAYOUT NEEDS-PAINT
flutter:           child 5: RenderPadding#2d4ae NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
flutter:             child: RenderConstrainedBox#23302 NEEDS-LAYOUT NEEDS-PAINT
flutter:           child 6: RenderPadding#1697e NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
flutter:             child: RenderParagraph#2a3e6 NEEDS-LAYOUT NEEDS-PAINT
flutter:           child 7: RenderPadding#5d1f3 NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
flutter:             child: RenderParagraph#a96bc NEEDS-LAYOUT NEEDS-PAINT
flutter:           child 8: RenderPadding#28959 NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
flutter:             child: RenderParagraph#155b2 NEEDS-LAYOUT NEEDS-PAINT
flutter:           child 9: _RenderScrollSemantics#a4e15 NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
flutter:             child: RenderPointerListener#d54b8 NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
flutter:           child 10: RenderPadding#d9559 NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
flutter:             child: RenderParagraph#7fa42 NEEDS-LAYOUT NEEDS-PAINT
flutter:           child 11: _RenderScrollSemantics#43551 NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
flutter:             child: RenderPointerListener#cdf7b NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
flutter: ════════════════════════════════════════════════════════════════════════════════════════════════════
flutter: Another exception was thrown: NoSuchMethodError: The method 'debugAssertIsValid' was called on null.
flutter: Another exception was thrown: NoSuchMethodError: The getter 'visible' was called on null.
```

**Comment by dnfield** [comment]
Ok, if I remove `hasScrollBody: false` it renders now.  But then I'm not able to reproduce any other errors.

**Comment by Greatcallie** [comment]
Yes that depends on flutter version. But the error is when you try
scrolling on top of the yellow text, up and down.

**Comment by dnfield** [comment]
Ah! I see it now.

**Comment by dnfield** [comment]
Uh.  Something very strange is going on here.

I have a `Rect` that is finite.  I call another method and the rect suddenly has NaN in it....

**Comment by dnfield** [comment]
Ah! User error.  

The issue is that we have infinite constraints here.  We end up trying to subtract infinity from infinity and get NaN and then we're all in a tizzy.

**Comment by danghoang-dev** [comment]
I also have that issue like you, I've solved that by use Expended wrap Listview.builder
