### ISSUE TITLE
Exception caught by rendering library

### ISSUE THREAD

**Issue by ddukesterman** [flutter/flutter#45875]
## Steps to Reproduce

I am following along https://jap.alekhin.io/scoring-storage-sound-tutorial-flame-flutter-part-4. I am at the part where we are supposed to render the Callout for the Fly. It says to do the following in the render method:

```
@override
void render(Canvas c) {
  sprite.renderRect(c, rect);
  tp.paint(c, textOffset);
}
```

If I do so, I get the error below. If I wrap it with a null check like so it goes away:

```
@override
void render(Canvas c) {
  if(rect != null) {
    sprite.renderRect(c, rect);
    tp.paint(c, textOffset);
  }
 }
```

I wasn't sure if a simple null check is the answer or some deeper issue.

**Target Platform:Android**
**Target OS version/browser: API 28**
**Devices: Emulator**

## Logs

Seen on IntelliJ console output:
```
════════ Exception caught by rendering library ═════════════════════════════════════════════════════
The following assertion was thrown during paint():
Rect argument was null.
'dart:ui/painting.dart':
Failed assertion: line 25: '<optimized out>'


Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=BUG.md

When the exception was thrown, this was the stack: 
#2      _rectIsValid (dart:ui/painting.dart:25:10)
#3      Canvas.drawImageRect (dart:ui/painting.dart:3717:12)
#4      Sprite.renderRect (package:flame/sprite.dart:130:12)
#5      Callout.render (package:galaxy_shooter/flies/Callout.dart:35:12)
#6      Fly.render (package:galaxy_shooter/flies/Fly.dart:42:17)
...
The following RenderObject was being processed when the exception was fired: GameRenderBox#ce5a8
...  parentData: <none> (can use size)
...  constraints: BoxConstraints(w=360.0, h=640.0)
...  size: Size(360.0, 640.0)
RenderObject: GameRenderBox#ce5a8
  parentData: <none> (can use size)
  constraints: BoxConstraints(w=360.0, h=640.0)
  size: Size(360.0, 640.0)
════════════════════════════════════════════════════════════════════════════════════════════════════
```

Seen on `flutter run --verbose`:
```
[+3086 ms] I/flutter (11882): ══╡ EXCEPTION CAUGHT BY RENDERING LIBRARY ╞═════════════════════════════════════════════════════════
[        ] I/flutter (11882): The following assertion was thrown during paint():
[        ] I/flutter (11882): Rect argument was null.
[        ] I/flutter (11882): 'dart:ui/painting.dart':
[        ] I/flutter (11882): Failed assertion: line 25: '<optimized out>'
[        ] I/flutter (11882): 
[        ] I/flutter (11882): Either the assertion indicates an error in the framework itself, or we should provide substantially
[        ] I/flutter (11882): more information in this error message to help you determine and fix the underlying cause.
[        ] I/flutter (11882): In either case, please report this assertion by filing a bug on GitHub:
[        ] I/flutter (11882):   https://github.com/flutter/flutter/issues/new?template=BUG.md
[        ] I/flutter (11882): 
[        ] I/flutter (11882): When the exception was thrown, this was the stack:
[        ] I/flutter (11882): #2      _rectIsValid (dart:ui/painting.dart:25:10)
[        ] I/flutter (11882): #3      Canvas.drawImageRect (dart:ui/painting.dart:3717:12)
[        ] I/flutter (11882): #4      Sprite.renderRect (package:flame/sprite.dart:130:12)
[        ] I/flutter (11882): #5      Callout.render (package:galaxy_shooter/flies/Callout.dart:35:12)
[        ] I/flutter (11882): #6      Fly.render (package:galaxy_shooter/flies/Fly.dart:42:17)
[        ] I/flutter (11882): #7      BaseGame.renderComponent (package:flame/game.dart:314:7)
[        ] I/flutter (11882): #8      BaseGame.render.<anonymous closure> (package:flame/game.dart:299:34)
[        ] I/flutter (11882): #9      IterableMixin.forEach (dart:collection/iterable.dart:46:30)
[        ] I/flutter (11882): #10     BaseGame.render (package:flame/game.dart:299:16)
[        ] I/flutter (11882): #11     MyGame.render (package:galaxy_shooter/MyGame.dart:61:11)
[        ] I/flutter (11882): #12     GameRenderBox.paint (package:flame/game.dart:496:10)
[        ] I/flutter (11882): #13     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2263:7)
[        ] I/flutter (11882): #14     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:184:13)
[        ] I/flutter (11882): #15     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:123:15)
[        ] I/flutter (11882): #16     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2263:7)
[        ] I/flutter (11882): #17     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:184:13)
[        ] I/flutter (11882): #18     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:123:15)
[        ] I/flutter (11882): #19     RenderDecoratedBox.paint (package:flutter/src/rendering/proxy_box.dart:1998:11)
[        ] I/flutter (11882): #20     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2263:7)
[        ] I/flutter (11882): #21     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:184:13)
[        ] I/flutter (11882): #22     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:123:15)
[        ] I/flutter (11882): #23     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2263:7)
[        ] I/flutter (11882): #24     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:184:13)
[        ] I/flutter (11882): #25     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:123:15)
[   +1 ms] I/flutter (11882): #26     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2263:7)
[        ] I/flutter (11882): #27     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:184:13)
[        ] I/flutter (11882): #28     RenderView.paint (package:flutter/src/rendering/view.dart:213:15)
[        ] I/flutter (11882): #29     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2263:7)
[        ] I/flutter (11882): #30     PaintingContext._repaintCompositedChild (package:flutter/src/rendering/object.dart:135:11)
[        ] I/flutter (11882): #31     PaintingContext.repaintCompositedChild (package:flutter/src/rendering/object.dart:95:5)
[        ] I/flutter (11882): #32     PipelineOwner.flushPaint (package:flutter/src/rendering/object.dart:981:29)
[        ] I/flutter (11882): #33     RendererBinding.drawFrame (package:flutter/src/rendering/binding.dart:346:19)
[        ] I/flutter (11882): #34     WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:776:13)
[        ] I/flutter (11882): #35     RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:283:5)
[        ] I/flutter (11882): #36     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1102:15)
[        ] I/flutter (11882): #37     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1041:9)
[        ] I/flutter (11882): #38     SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:957:5)
[        ] I/flutter (11882): #42     _invoke (dart:ui/hooks.dart:259:10)
[        ] I/flutter (11882): #43     _drawFrame (dart:ui/hooks.dart:217:3)
[        ] I/flutter (11882): (elided 5 frames from class _AssertionError and package dart:async)
[        ] I/flutter (11882): 
[        ] I/flutter (11882): The following RenderObject was being processed when the exception was fired: GameRenderBox#e6e4e:
[        ] I/flutter (11882):   parentData: <none> (can use size)
[        ] I/flutter (11882):   constraints: BoxConstraints(w=360.0, h=640.0)
[        ] I/flutter (11882):   size: Size(360.0, 640.0)
[        ] I/flutter (11882): This RenderObject has no descendants.
[        ] I/flutter (11882): ════════════════════════════════════════════════════════════════════════════════════════════════════
```

```
No issues found! (ran in 2.3s)
```

```
[✓] Flutter (Channel master, v1.12.16-pre.34, on Mac OS X 10.13.6 17G65, locale en-US)
    • Flutter version 1.12.16-pre.34 at /Users/trentonduke/path/flutter
    • Framework revision 1e50db60ad (3 days ago), 2019-11-29 09:17:52 -0500
    • Engine revision 6c605f8a96
    • Dart version 2.7.0

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/trentonduke/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)
    • All Android licenses accepted.

[✗] Xcode - develop for iOS and macOS
    ✗ Xcode installation is incomplete; a full installation is necessary for iOS development.
      Download at: https://developer.apple.com/xcode/download/
      Or install Xcode via the App Store.
      Once installed, run:
        sudo xcode-select --switch /Applications/Xcode.app/Contents/Developer
        sudo xcodebuild -runFirstLaunch
    ✗ CocoaPods not installed.
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To install:
        sudo gem install cocoapods

[✓] Android Studio (version 3.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 34.0.1
    • Dart plugin version 182.5215
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)

[✓] IntelliJ IDEA Community Edition (version 2019.3)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 41.1.5
    • Dart plugin version 193.5233.116

[✓] Connected device (1 available)
    • AOSP on IA Emulator • emulator-5554 • android-x86 • Android 9 (API 28) (emulator)

! Doctor found issues in 1 category.
```

**Comment by VladyslavBondarenko** [comment]
Hi @ddukesterman 
Closing, as this isn't an issue with Flutter itself,
if you disagree please write in the comments and I will reopen it
Thank you
