### ISSUE TITLE
Image is not loading from the assets folder. (Exception caught by Image Resource Service)

### ISSUE THREAD

**Issue by chauhannaman98** [flutter/flutter#45891]
## Minimal Reproduction

```
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatefulWidget {
  @override
  State<StatefulWidget> createState() {
    return _MyAppState();
  }
}

class _MyAppState extends State<MyApp> {
  List<String> _products = ['Food Tester'];

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        appBar: AppBar(
          title: Text('EasyList'),
        ),
        body: Column(
          children: [
            Container(
              margin: EdgeInsets.all(10.0),
              child: RaisedButton(
                onPressed: () {
                  setState(() {
                    _products.add('Advanced Food Tester');
                  });
                },
                child: Text('Add Product'),
              ),
            ),
            Column(
              children: _products
                  .map((element) => Card(
                        child: Column(
                          children: <Widget>[
                            Image.asset('assets/food.jpeg'),
                            Text(element)
                          ],
                        ),
                      ))
                  .toList(),
            ),
          ],
        ),
      ),
    );
  }
}

```

I am hot reloading it on my ASUS running on Android Pie.

## Logs

```
I/flutter (10487): ══╡ EXCEPTION CAUGHT BY IMAGE RESOURCE SERVICE ╞════════════════════════════════════════════════════
I/flutter (10487): The following assertion was thrown resolving an image codec:
I/flutter (10487): Unable to load asset: assets/food.jpeg
I/flutter (10487): 
I/flutter (10487): When the exception was thrown, this was the stack:
I/flutter (10487): #0      PlatformAssetBundle.load (package:flutter/src/services/asset_bundle.dart:221:7)
I/flutter (10487): <asynchronous suspension>
I/flutter (10487): #1      AssetBundleImageProvider._loadAsync (package:flutter/src/painting/image_provider.dart:464:44)
I/flutter (10487): <asynchronous suspension>
I/flutter (10487): #2      AssetBundleImageProvider.load (package:flutter/src/painting/image_provider.dart:449:14)
I/flutter (10487): #3      ImageProvider.resolve.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:flutter/src/painting/image_provider.dart:316:48)
I/flutter (10487): #4      ImageCache.putIfAbsent (package:flutter/src/painting/image_cache.dart:160:22)
I/flutter (10487): #5      ImageProvider.resolve.<anonymous closure>.<anonymous closure> (package:flutter/src/painting/image_provider.dart:316:25)
I/flutter (10487): (elided 13 frames from package dart:async)
I/flutter (10487): 
I/flutter (10487): Image provider: AssetImage(bundle: null, name: "assets/food.jpeg")
I/flutter (10487): Image key: AssetBundleImageKey(bundle: PlatformAssetBundle#d96b0(), name: "assets/food.jpeg", scale:
I/flutter (10487):   1.0)
I/flutter (10487): ════════════════════════════════════════════════════════════════════════════════════════════════════
```

## flutter analyze
```
Analyzing first_app...                                                  
No issues found! (ran in 6.4s)
```

## flutter doctor -v

```
[✓] Flutter (Channel stable, v1.9.1+hotfix.6, on Linux, locale en_US.UTF-8)
    • Flutter version 1.9.1+hotfix.6 at /home/techmirtz/flutter
    • Framework revision 68587a0916 (3 months ago), 2019-09-13 19:46:58 -0700
    • Engine revision b863200c37
    • Dart version 2.5.0

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /home/techmirtz/Android/Sdk
    • Android NDK location not configured (optional; useful for native profiling
      support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /home/techmirtz/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Android Studio (version 3.5)
    • Android Studio at /home/techmirtz/android-studio
    • Flutter plugin version 41.1.2
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build
      1.8.0_202-release-1483-b49-5587405)

[!] IntelliJ IDEA Ultimate Edition (version 2019.2)
    • IntelliJ at /snap/intellij-idea-ultimate/181
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.dev/intellij-setup/#installing-the-plugins

[✓] Connected device (1 available)
    • ASUS X00TD • J7AAGF06T826H7Z • android-arm64 • Android 9 (API 28)

```

**Comment by iapicca** [comment]
Hi @chauhannaman98 
the logs indicates that flutter was  `Unable to load asset: assets/food.jpeg`
could you please double check that the path of the folders and the one on `pubspec.yaml` match?
thank you

**Comment by chauhannaman98** [comment]
> Hi @chauhannaman98
> the logs indicates that flutter was `Unable to load asset: assets/food.jpeg`
> could you please double check
> that the path of the folders
> and the one on `pubspec.yaml` match?
> thank you

I have checked the path of the file `food.jpeg`
Also, the `pubspec.yaml` file has been updated but the exception remains there.
Here is the repository if you need: https://github.com/chauhannaman98/flutterApp/tree/StatefulWidgets

**Comment by iapicca** [comment]
Thank you @chauhannaman98

**Comment by jonahwilliams** [comment]
The formatting of your asset key is incorrect:

```
assets:
- assets/food.jpeg
```
There are no items under `assets`

**Comment by chauhannaman98** [comment]
> The formatting of your asset key is incorrect:
> 
> ```
> assets:
> - assets/food.jpeg
> ```
> 
> There are no items under `assets`

@jonahwilliams Thanks for pointing out that silly mistake.
My bad!

**Comment by jonahwilliams** [comment]
Don't worry about it @chauhannaman98, yaml is very difficult to format correctly and you're certainly not the first person to make that mistake

**Comment by akaannsh** [comment]
Facing the same error

**Comment by chauhannaman98** [comment]
> Facing the same error

@akaannsh Have you tried to resolve the issue using the methods mentioned above?

**Comment by samisnotinsane** [comment]
I faced the same error and I checked the formatting of `pubspec.yaml`. Fixed the issue by totally stopping the app (not hot reload/restart) and relaunching it.
