### ISSUE TITLE
Windows Controlled Folder Access on - FileSystemException: writeFrom failed, path = '...\flutter-plugins' (OS Error: Access is denied. , errno = 5)

### ISSUE THREAD

**Issue by yasinelabe** [flutter/flutter#45964]
Flutter crash report; please file at https://github.com/flutter/flutter/issues.

## command

flutter run --machine --target lib\main.dart -d emulator-5554 --track-widget-creation --start-paused

## exception

FileSystemException: FileSystemException: writeFrom failed, path = 'C:\Users\Yasin\Desktop\adeegsame\.flutter-plugins' (OS Error: Access is denied.
, errno = 5)

```
#0      _RandomAccessFile.writeFromSync (dart:io/file_impl.dart:879:7)
#1      _File.writeAsBytesSync (dart:io/file_impl.dart:614:14)
#2      _File.writeAsStringSync (dart:io/file_impl.dart:636:5)
#3      _LocalFile&LocalFileSystemEntity&ForwardingFile.writeAsStringSync (package:file/src/forwarding/forwarding_file.dart:152:16)
#4      _writeFlutterPluginsList (package:flutter_tools/src/plugins.dart:107:17)
#5      refreshPluginsList (package:flutter_tools/src/plugins.dart:341:24)
#6      FlutterProject.ensureReadyForPlatformSpecificTooling (package:flutter_tools/src/project.dart:187:5)
<asynchronous suspension>
#7      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:473:21)
<asynchronous suspension>
#8      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:383:33)
<asynchronous suspension>
#9      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:29)
<asynchronous suspension>
#10     _rootRun (dart:async/zone.dart:1124:13)
#11     _CustomZone.run (dart:async/zone.dart:1021:19)
#12     _runZoned (dart:async/zone.dart:1516:10)
#13     runZoned (dart:async/zone.dart:1463:12)
#14     AppContext.run (package:flutter_tools/src/base/context.dart:152:18)
<asynchronous suspension>
#15     FlutterCommand.run (package:flutter_tools/src/runner/flutter_command.dart:375:20)
#16     CommandRunner.runCommand (package:args/command_runner.dart:197:27)
<asynchronous suspension>
#17     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:396:21)
<asynchronous suspension>
#18     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:29)
<asynchronous suspension>
#19     _rootRun (dart:async/zone.dart:1124:13)
#20     _CustomZone.run (dart:async/zone.dart:1021:19)
#21     _runZoned (dart:async/zone.dart:1516:10)
#22     runZoned (dart:async/zone.dart:1463:12)
#23     AppContext.run (package:flutter_tools/src/base/context.dart:152:18)
<asynchronous suspension>
#24     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:356:19)
<asynchronous suspension>
#25     CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:112:25)
#26     new Future.sync (dart:async/future.dart:224:31)
#27     CommandRunner.run (package:args/command_runner.dart:112:14)
#28     FlutterCommandRunner.run (package:flutter_tools/src/runner/flutter_command_runner.dart:242:18)
#29     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:62:22)
<asynchronous suspension>
#30     _rootRun (dart:async/zone.dart:1124:13)
#31     _CustomZone.run (dart:async/zone.dart:1021:19)
#32     _runZoned (dart:async/zone.dart:1516:10)
#33     runZoned (dart:async/zone.dart:1500:12)
#34     run.<anonymous closure> (package:flutter_tools/runner.dart:60:18)
<asynchronous suspension>
#35     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:29)
<asynchronous suspension>
#36     _rootRun (dart:async/zone.dart:1124:13)
#37     _CustomZone.run (dart:async/zone.dart:1021:19)
#38     _runZoned (dart:async/zone.dart:1516:10)
#39     runZoned (dart:async/zone.dart:1463:12)
#40     AppContext.run (package:flutter_tools/src/base/context.dart:152:18)
<asynchronous suspension>
#41     runInContext (package:flutter_tools/src/context_runner.dart:56:24)
<asynchronous suspension>
#42     run (package:flutter_tools/runner.dart:51:10)
#43     main (package:flutter_tools/executable.dart:62:9)
<asynchronous suspension>
#44     main (file:///C:/b/s/w/ir/k/archive/flutter/packages/flutter_tools/bin/flutter_tools.dart:8:3)
#45     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:299:32)
#46     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:12)
```

## flutter doctor

```
[✓] Flutter (Channel stable, v1.7.8+hotfix.4, on Microsoft Windows [Version 10.0.17763.805], locale en-US)
    • Flutter version 1.7.8+hotfix.4 at C:\flutter
    • Framework revision 20e59316b8 (5 months ago), 2019-07-18 20:04:33 -0700
    • Engine revision fee001c93f
    • Dart version 2.4.0

[!] Android toolchain - develop for Android devices (Android SDK version 29.0.0)
    • Android SDK at C:\Users\Yasin\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.0
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses

[!] Android Studio (version 3.4)
    • Android Studio at C:\Program Files\Android\Android Studio
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

[✓] VS Code (version 1.40.0)
    • VS Code at C:\Users\Yasin\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.6.0

[✓] Connected device (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 8.1.0 (API 27) (emulator)

! Doctor found issues in 2 categories.
```

**Comment by janmoppel** [comment]
Hello @yasinelabe !

Thank you for posting an issue.
Can you please check the solution proposed in this thread, and comment, whether it helps you: #15711?

**Comment by jmagman** [comment]
Why is `adeegsame.flutter-plugins` missing a `\`?
```dart
  /// The `.flutter-plugins` file of this project.
  File get flutterPluginsFile => directory.childFile('.flutter-plugins');
```

**Comment by jonahwilliams** [comment]
Could be a formatting error in the message itself

**Comment by yasinelabe** [comment]
![solution](https://user-images.githubusercontent.com/29584844/70116156-ed355680-1672-11ea-8531-181fe9141622.PNG)

i figured out this lately and it turns out
that Windows Controlled Folder Access was turned ON

and it was denying everything that flutter tries writing on the disk 

FileSystemException: FileSystemException: writeFrom failed, path = 'C:\Users\Yasin\Desktop\adeegsame.flutter-plugins' (OS Error: Access is denied.
, errno = 5)

**Comment by paulogalindo** [comment]
This Work to me!!!!!Fine,Fine!!!!!
Thanks!!!1
