### ISSUE TITLE
I/flutter (21224): NoSuchMethodError: The getter 'length' was called on null. While calling put api ?

### ISSUE THREAD

**Issue by Henry667** [flutter/flutter#45981]
Greeting dev team.

I have one issue while working on flutter, whenever i tried to calling the **http.put request** strange issue occurred.

```
Exception has occurred.
NoSuchMethodError (NoSuchMethodError: The getter 'length' was called on null.
Receiver: null
Tried calling: length)
```

## Here is my main code.

```dart
saveBookMarksLogin(id) async {
    final prefs = await SharedPreferences.getInstance();
    var bookmarkData = {
      "userId": userId,
      "newsFeedId": id,
    };
    try {
      final response = await http.put(
        Uri(
          scheme: 'http',
          host: host,
          port: 3000,
          path: '/v1/saveBookmark',
        ),
        body: bookmarkData,
        headers: {'Content-Type': 'application/x-www-form-urlencoded'},
      );

      if (response.body != null) {
        prefs.setStringList("bookmarkIds", [id]);
        return json.decode(response.body);
      }
    } on SocketException {
      Fluttertoast.showToast(
        msg: "No internet connection",
        toastLength: Toast.LENGTH_SHORT,
        gravity: ToastGravity.BOTTOM,
        timeInSecForIos: 1,
        textColor: Colors.white,
        fontSize: 16.0,
        backgroundColor: Colors.black,
      );
    }
  }
```

## Stack trace of issue while debugging..

```
I/flutter (23979): error NoSuchMethodError: The getter 'length' was called on null.
I/flutter (23979): Receiver: null
I/flutter (23979): Tried calling: length
I/flutter (23979): stacktrace #0      Object.noSuchMethod  (dart:core-patch/object_patch.dart:51:5)
I/flutter (23979): #1      _Uri._uriEncode  (dart:core-patch/uri_patch.dart:44:23)
I/flutter (23979): #2      Uri.encodeQueryComponent  (dart:core/uri.dart:1103:17)
I/flutter (23979): #3      mapToQuery.<anonymous closure> 
package:http/src/utils.dart:19
I/flutter (23979): #4      CastMap.forEach.<anonymous closure>  (dart:_internal/cast.dart:286:8)
I/flutter (23979): #5      _LinkedHashMapMixin.forEach  (dart:collection-patch/compact_hash.dart:377:8)
I/flutter (23979): #6      CastMap.forEach  (dart:_internal/cast.dart:285:13)
I/flutter (23979): #7      mapToQuery 
package:http/src/utils.dart:17
I/flutter (23979): #8      Request.bodyFields= 
package:http/src/request.dart:128
I/flutter (23979): #9      BaseClient._sendUnstreamed 
package:http/src/base_client.dart:163
I/flutter (23979): <asynchronous suspension>
I/flutter (23979): #10     BaseClient.put 
package:http/src/base_client.dart:76
I/flutter (23979): #11     put.<anonymous closure> 
package:http/http.dart:94
I/flutter (23979): #12     _withClient 
package:http/http.dart:166
I/flutter (23979): <asynchronous suspension>
I/flutter (23979): #13     put 
package:http/http.dart:93
I/flutter (23979): #14     _NewsPageState.saveBookMarksLogin (package:i
```

## Flutter doctor -v

```
[✓] Flutter (Channel stable, v1.9.1+hotfix.6, on Linux, locale en_IN)
    • Flutter version 1.9.1+hotfix.6 at /home/sunnynegi/Downloads/flutter
    • Framework revision 68587a0916 (3 months ago), 2019-09-13 19:46:58 -0700
    • Engine revision b863200c37
    • Dart version 2.5.0

 
[!] Android toolchain - develop for Android devices (Android SDK version 29.0.1)
    • Android SDK at /home/sunnynegi/Android/Sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.1
    • ANDROID_HOME = /home/sunnynegi/Android/Sdk
    • Java binary at: /mnt/c68c209d-730c-47ba-a53e-a4f027ef29cf/android-studio-ide-183.5692245-linux/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b16-5323222)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses

[✓] Android Studio (version 3.4)
    • Android Studio at /mnt/c68c209d-730c-47ba-a53e-a4f027ef29cf/android-studio-ide-183.5692245-linux/android-studio
    • Flutter plugin version 39.0.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b16-5323222)

[✓] VS Code (version 1.37.1)
    • VS Code at /usr/share/code
    • Flutter extension version 3.4.1

[✓] Connected device (1 available)
    • Redmi Note 6 Pro • 6222e236 • android-arm64 • Android 9 (API 28)

! Doctor found issues in 1 category.
```

Hope you can help me

**Comment by Henry667** [comment]
![Screenshot from 2019-12-03 12-53-45](https://user-images.githubusercontent.com/30168424/70046618-68075e80-15ec-11ea-87bb-24b9fb93e927.png)

**Comment by Henry667** [comment]
This issue arise when you try to send a null value in http request flutter automaticaly convert into a string. That's why it's give error

**Comment by lkrjangid1** [comment]
i have same this issue in my app.
