### ISSUE TITLE
showDialog could not show LayoutBuilder widget on Android

### ISSUE THREAD

**Issue by guanggenzhang** [flutter/flutter#46063]
Steps to Reproduce

1. create a flutter app and set TestPage as home page

<details>
  <summary>code sample</summary>

```
class TestPage extends StatelessWidget {
  const TestPage({Key key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      resizeToAvoidBottomInset: false,
      body: SafeArea(
        child: Center(
          child: RaisedButton(
            onPressed: () async {
              await showDialog<void>(
                  context: context,
                  builder: (BuildContext context) {
                    return AlertDialog(
                      content: LayoutBuilder(
                        builder:
                            (BuildContext context, BoxConstraints constraints) {
                          return const Text('you should see me');
                        },
                      ),
                    );
                  });
            },
            child: const Text('press me to show an alert dialog'),
          ),
        ),
      ),
    );
  }
}
```

</details>

2. run the app on android device
3. after app launch, press the button to show a dialog

expected:  dialog show
actual: no dialog show

I also try same thing on ios platform, the dialog show correctly

**Target Platform:**
android
**Target OS version/browser:**
**Devices:**
xiaomi 8

flutter run --verbose:
```
I/nture.ps.clien(17924): ProcessProfilingInfo new_methods=1039 is saved saved_to_disk=1 resolve_classes_delay=8000
I/flutter (17924): FlutterError.onError
I/flutter (17924): Another exception was thrown: LayoutBuilder does not support returning intrinsic dimensions.
I/flutter (17924): FlutterError.onError
I/flutter (17924): Another exception was thrown: RenderBox was not laid out: RenderIntrinsicWidth#86875 relayoutBoundary=up6 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
I/flutter (17924): FlutterError.onError
I/flutter (17924): Another exception was thrown: RenderBox was not laid out: RenderSemanticsAnnotations#7592a relayoutBoundary=up5 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
I/flutter (17924): FlutterError.onError
I/flutter (17924): Another exception was thrown: RenderBox was not laid out: _RenderInkFeatures#250cb relayoutBoundary=up4 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
I/flutter (17924): FlutterError.onError
I/flutter (17924): Another exception was thrown: RenderBox was not laid out: RenderCustomPaint#29950 relayoutBoundary=up3 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
I/flutter (17924): FlutterError.onError
I/flutter (17924): Another exception was thrown: RenderBox was not laid out: RenderPhysicalShape#0f784 relayoutBoundary=up2 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
I/flutter (17924): FlutterError.onError
I/flutter (17924): Another exception was thrown: 'package:flutter/src/rendering/shifted_box.dart': Failed assertion: line 321 pos 12: 'child.hasSize': is not true.
I/flutter (17924): FlutterError.onError
I/flutter (17924): Another exception was thrown: RenderBox was not laid out: RenderPhysicalShape#0f784 relayoutBoundary=up2
I/flutter (17924): Another exception was thrown: Cannot hit test a render box with no size.

```

flutter doctor -v:

```
[✓] Flutter (Channel stable, v1.9.1+hotfix.6, on Mac OS X 10.15.1 19B88, locale en-CN)
    • Flutter version 1.9.1+hotfix.6 at /Applications/flutter
    • Framework revision 68587a0916 (3 months ago), 2019-09-13 19:46:58 -0700
    • Engine revision b863200c37
    • Dart version 2.5.0
```

**Comment by iapicca** [comment]
Hi @guanggenzhang 
I'm experiencing the issue as you described
even passing the `BoxConstraints`

<details>
  <summary>code sample</summary>

```
import 'package:flutter/material.dart';

Future<void> _showDialog(BuildContext context, BoxConstraints constraints) async => 
  await showDialog<void>(
    context: context,
    barrierDismissible: true,
    builder: (BuildContext context) => AlertDialog(
      content: LayoutBuilder(
        builder: (BuildContext context, constraints) => Center(
          child: FlutterLogo(),
    ),),
),);

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) => MaterialApp(
    home: HomePage(),
  );
}

class HomePage extends StatelessWidget {

  @override
  Widget build(BuildContext context)=> Scaffold(
    body: LayoutBuilder(
      builder: (BuildContext context, BoxConstraints constraints)=> GestureDetector(
        onTap: ()=> _showDialog(context, constraints),
        child: Center(
          child:Text('tap me',),
  ),),),);
}
```

</details>

**Comment by TahaTesser** [comment]
Issue still exist

<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel dev, v1.18.0-6.0.pre, on Mac OS X 10.15.4 19E287, locale
    en-GB)
    • Flutter version 1.18.0-6.0.pre at /Users/taha/Code/flutter_dev
    • Framework revision 84c84fb249 (3 days ago), 2020-04-20 21:35:01 -0400
    • Engine revision 2bde4f0ae4
    • Dart version 2.9.0 (build 2.9.0-1.0.dev a12c36dd97)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/taha/Code/sdk
    • Platform android-29, build-tools 29.0.3
    • ANDROID_HOME = /Users/taha/Code/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.
[✓] Xcode - develop for iOS and macOS (Xcode 11.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.4.1, Build version 11E503a
    • CocoaPods version 1.9.1
[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome
[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build
      1.8.0_212-release-1586-b4-5784211)
[✓] VS Code (version 1.44.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.9.1
[✓] Connected device (4 available)
    • Android SDK built for x86 • emulator-5554 • android-x86    • Android 10
      (API 29) (emulator)
    • macOS                     • macOS         • darwin-x64     • Mac OS X
      10.15.4 19E287
    • Chrome                    • chrome        • web-javascript • Google Chrome
      81.0.4044.122
    • Web Server                • web-server    • web-javascript • Flutter Tools
• No issues found!
```

</details>

**Comment by TahaTesser** [comment]
<details> 
<summary>code sample</summary> 

```dart
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Material App',
      theme: ThemeData.dark(),
      home: TestPage(),
    );
  }
}

class TestPage extends StatelessWidget {
  const TestPage({Key key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      resizeToAvoidBottomInset: false,
      body: SafeArea(
        child: Center(
          child: RaisedButton(
            onPressed: () async {
              await showDialog<void>(
                  context: context,
                  builder: (BuildContext context) {
                    return AlertDialog(
                      content: LayoutBuilder(
                        builder:
                            (BuildContext context, BoxConstraints constraints) {
                          return const Text('you should see me');
                        },
                      ),
                    );
                  });
            },
            child: const Text('press me to show an alert dialog'),
          ),
        ),
      ),
    );
  }
}

``` 

</details>


<details> 
<summary>flutter doctor -v</summary> 

```bash
[✓] Flutter (Channel stable, 1.22.5, on Microsoft Windows [Version 10.0.19042.685], locale en-US)
    • Flutter version 1.22.5 at C:\Code\flutter_stable
    • Framework revision 7891006299 (3 weeks ago), 2020-12-10 11:54:40 -0800
    • Engine revision ae90085a84
    • Dart version 2.10.4


[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Code\sdk
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = C:\Code\sdk
    • Java binary at: C:\Code\android-studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[!] Android Studio (version 4.1.0)
    • Android Studio at C:\Code\android-studio
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[✓] VS Code (version 1.52.1)
    • VS Code at C:\Users\Taha\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.18.0

[✓] Connected device (1 available)
    • Android SDK built for x86 (mobile) • emulator-5554 • android-x86 • Android 10 (API 29) (emulator)

! Doctor found issues in 1 category.
```

```bash
[✓] Flutter (Channel master, 1.26.0-2.0.pre.157, on Microsoft Windows [Version 10.0.19042.685], locale en-US)
    • Flutter version 1.26.0-2.0.pre.157 at C:\Code\flutter_master
    • Framework revision 4b83be6c23 (5 hours ago), 2020-12-30 02:09:03 -0500
    • Engine revision 0e5a25d779
    • Dart version 2.12.0 (build 2.12.0-179.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Code\sdk
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = C:\Code\sdk
    • Java binary at: C:\Code\android-studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[✓] Visual Studio - develop for Windows (Visual Studio Community 2019 16.8.3)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.8.30804.86
    • Windows 10 SDK version 10.0.18362.0

[✓] Android Studio (version 4.1.0)
    • Android Studio at C:\Code\android-studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[✓] VS Code (version 1.52.1)
    • VS Code at C:\Users\Taha\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.18.0

[✓] Connected device (4 available)
    • Android SDK built for x86 (mobile) • emulator-5554 • android-x86    • Android 10 (API 29) (emulator)
    • Windows (desktop)                  • windows       • windows-x64    • Microsoft Windows [Version 10.0.19042.685]
    • Chrome (web)                       • chrome        • web-javascript • Google Chrome 87.0.4280.88
    • Edge (web)                         • edge          • web-javascript • Microsoft Edge 87.0.664.66

• No issues found!
```

</details>

**Comment by maheshmnj** [comment]
I am able to reproduce the issue on the stable and master channel the dialog doesn't show up and fails with exception, I think that this is working as intended, Labeling for further insights from the team.

<details>
<summary>logs</summary>

```dart
Restarted application in 361ms.
══╡ EXCEPTION CAUGHT BY RENDERING LIBRARY ╞═════════════════════════════════════════════════════════
The following assertion was thrown during performLayout():
LayoutBuilder does not support returning intrinsic dimensions.
Calculating the intrinsic dimensions would require running the layout callback speculatively, which
might mutate the live render object tree.

The relevant error-causing widget was:
  AlertDialog AlertDialog:file:///Users/mahesh/Desktop/flutter_issue/lib/main.dart:30:28

When the exception was thrown, this was the stack:
#0      _RenderLayoutBuilder._debugThrowIfNotCheckingIntrinsics.<anonymous closure> (package:flutter/src/widgets/layout_builder.dart:345:9)
#1      _RenderLayoutBuilder._debugThrowIfNotCheckingIntrinsics (package:flutter/src/widgets/layout_builder.dart:352:6)
#2      _RenderLayoutBuilder.computeMaxIntrinsicWidth (package:flutter/src/widgets/layout_builder.dart:285:12)
#3      RenderBox._computeIntrinsicDimension.<anonymous closure> (package:flutter/src/rendering/box.dart:1424:23)
#4      _LinkedHashMapMixin.putIfAbsent (dart:collection-patch/compact_hash.dart:535:23)
#5      RenderBox._computeIntrinsicDimension (package:flutter/src/rendering/box.dart:1422:57)
#6      RenderBox.getMaxIntrinsicWidth (package:flutter/src/rendering/box.dart:1624:12)
#7      RenderProxyBoxMixin.computeMaxIntrinsicWidth (package:flutter/src/rendering/proxy_box.dart:80:21)
#8      RenderBox._computeIntrinsicDimension.<anonymous closure> (package:flutter/src/rendering/box.dart:1424:23)
#9      _LinkedHashMapMixin.putIfAbsent (dart:collection-patch/compact_hash.dart:535:23)
#10     RenderBox._computeIntrinsicDimension (package:flutter/src/rendering/box.dart:1422:57)
#11     RenderBox.getMaxIntrinsicWidth (package:flutter/src/rendering/box.dart:1624:12)
#12     RenderPadding.computeMaxIntrinsicWidth (package:flutter/src/rendering/shifted_box.dart:180:21)
#13     RenderBox._computeIntrinsicDimension.<anonymous closure> (package:flutter/src/rendering/box.dart:1424:23)
#14     _LinkedHashMapMixin.putIfAbsent (dart:collection-patch/compact_hash.dart:535:23)
#15     RenderBox._computeIntrinsicDimension (package:flutter/src/rendering/box.dart:1422:57)
#16     RenderBox.getMaxIntrinsicWidth (package:flutter/src/rendering/box.dart:1624:12)
#17     RenderFlex.computeMaxIntrinsicWidth.<anonymous closure> (package:flutter/src/rendering/flex.dart:618:60)
#18     RenderFlex._getIntrinsicSize (package:flutter/src/rendering/flex.dart:594:58)
#19     RenderFlex.computeMaxIntrinsicWidth (package:flutter/src/rendering/flex.dart:615:12)
#20     RenderBox._computeIntrinsicDimension.<anonymous closure> (package:flutter/src/rendering/box.dart:1424:23)
#21     _LinkedHashMapMixin.putIfAbsent (dart:collection-patch/compact_hash.dart:535:23)
#22     RenderBox._computeIntrinsicDimension (package:flutter/src/rendering/box.dart:1422:57)
#23     RenderBox.getMaxIntrinsicWidth (package:flutter/src/rendering/box.dart:1624:12)
#24     RenderIntrinsicWidth._computeSize (package:flutter/src/rendering/proxy_box.dart:733:37)
#25     RenderIntrinsicWidth.performLayout (package:flutter/src/rendering/proxy_box.dart:758:12)
#26     RenderObject.layout (package:flutter/src/rendering/object.dart:2189:7)
#27     RenderBox.layout (package:flutter/src/rendering/box.dart:2430:11)
#28     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:120:14)
#29     RenderObject.layout (package:flutter/src/rendering/object.dart:2189:7)
#30     RenderBox.layout (package:flutter/src/rendering/box.dart:2430:11)
#31     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:120:14)
#32     RenderCustomPaint.performLayout (package:flutter/src/rendering/custom_paint.dart:552:11)
#33     RenderObject.layout (package:flutter/src/rendering/object.dart:2189:7)
#34     RenderBox.layout (package:flutter/src/rendering/box.dart:2430:11)
#35     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:120:14)
#36     _RenderCustomClip.performLayout (package:flutter/src/rendering/proxy_box.dart:1467:11)
#37     RenderObject.layout (package:flutter/src/rendering/object.dart:2189:7)
#38     RenderBox.layout (package:flutter/src/rendering/box.dart:2430:11)
#39     RenderConstrainedBox.performLayout (package:flutter/src/rendering/proxy_box.dart:297:14)
#40     RenderObject.layout (package:flutter/src/rendering/object.dart:2189:7)
#41     RenderBox.layout (package:flutter/src/rendering/box.dart:2430:11)
#42     RenderPositionedBox.performLayout (package:flutter/src/rendering/shifted_box.dart:442:14)
#43     RenderObject.layout (package:flutter/src/rendering/object.dart:2189:7)
#44     RenderBox.layout (package:flutter/src/rendering/box.dart:2430:11)
#45     RenderPadding.performLayout (package:flutter/src/rendering/shifted_box.dart:240:12)
#46     RenderObject.layout (package:flutter/src/rendering/object.dart:2189:7)
#47     RenderBox.layout (package:flutter/src/rendering/box.dart:2430:11)
#48     RenderPadding.performLayout (package:flutter/src/rendering/shifted_box.dart:240:12)
#49     RenderObject.layout (package:flutter/src/rendering/object.dart:2189:7)
#50     RenderBox.layout (package:flutter/src/rendering/box.dart:2430:11)
#51     RenderPadding.performLayout (package:flutter/src/rendering/shifted_box.dart:240:12)
#52     RenderObject.layout (package:flutter/src/rendering/object.dart:2189:7)
#53     RenderBox.layout (package:flutter/src/rendering/box.dart:2430:11)
#54     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:120:14)
#55     RenderObject.layout (package:flutter/src/rendering/object.dart:2189:7)
#56     RenderBox.layout (package:flutter/src/rendering/box.dart:2430:11)
#57     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:120:14)
#58     RenderObject.layout (package:flutter/src/rendering/object.dart:2189:7)
#59     RenderBox.layout (package:flutter/src/rendering/box.dart:2430:11)
#60     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:120:14)
#61     RenderObject.layout (package:flutter/src/rendering/object.dart:2189:7)
#62     RenderBox.layout (package:flutter/src/rendering/box.dart:2430:11)
#63     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:120:14)
#64     RenderObject.layout (package:flutter/src/rendering/object.dart:2189:7)
#65     RenderBox.layout (package:flutter/src/rendering/box.dart:2430:11)
#66     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:120:14)
#67     RenderObject.layout (package:flutter/src/rendering/object.dart:2189:7)
#68     RenderBox.layout (package:flutter/src/rendering/box.dart:2430:11)
#69     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:120:14)
#70     RenderObject.layout (package:flutter/src/rendering/object.dart:2189:7)
#71     RenderBox.layout (package:flutter/src/rendering/box.dart:2430:11)
#72     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:120:14)
#73     RenderOffstage.performLayout (package:flutter/src/rendering/proxy_box.dart:3815:13)
#74     RenderObject.layout (package:flutter/src/rendering/object.dart:2189:7)
#75     RenderBox.layout (package:flutter/src/rendering/box.dart:2430:11)
#76     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:120:14)
#77     RenderObject.layout (package:flutter/src/rendering/object.dart:2189:7)
#78     RenderBox.layout (package:flutter/src/rendering/box.dart:2430:11)
#79     _RenderTheatre.performLayout (package:flutter/src/widgets/overlay.dart:856:15)
#80     RenderObject._layoutWithoutResize (package:flutter/src/rendering/object.dart:2027:7)
#81     PipelineOwner.flushLayout (package:flutter/src/rendering/object.dart:1020:18)
#82     RendererBinding.drawFrame (package:flutter/src/rendering/binding.dart:516:19)
#83     WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:865:13)
#84     RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:381:5)
#85     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1289:15)
#86     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1218:9)
#87     SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:1076:5)
#88     _invoke (dart:ui/hooks.dart:145:13)
#89     PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:338:5)
#90     _drawFrame (dart:ui/hooks.dart:112:31)

The following RenderObject was being processed when the exception was fired: RenderIntrinsicWidth#19324 relayoutBoundary=up5 NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE:
  creator: IntrinsicWidth ← DefaultTextStyle ← AnimatedDefaultTextStyle ←
    _InkFeatures-[GlobalKey#7aed0 ink renderer] ← NotificationListener<LayoutChangedNotification> ←
    CustomPaint ← _ShapeBorderPaint ← PhysicalShape ← _MaterialInterior ← Material ← ConstrainedBox ←
    Align ← ⋯
  parentData: <none> (can use size)
  constraints: BoxConstraints(280.0<=w<=310.0, 0.0<=h<=715.0)
  size: MISSING
  stepWidth: null
  stepHeight: null
This RenderObject had the following descendants (showing up to depth 5):
    child: RenderFlex#20e2d NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
      child 1: RenderPadding#a5503 NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
        child: RenderSemanticsAnnotations#8cc4d NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
          child: _RenderLayoutBuilder#75c6b NEEDS-LAYOUT NEEDS-PAINT
════════════════════════════════════════════════════════════════════════════════════════════════════
Another exception was thrown: RenderBox was not laid out: RenderIntrinsicWidth#19324 relayoutBoundary=up5 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
Another exception was thrown: RenderBox was not laid out: _RenderInkFeatures#a724b relayoutBoundary=up4 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
Another exception was thrown: RenderBox was not laid out: RenderCustomPaint#aabf7 relayoutBoundary=up3 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
Another exception was thrown: RenderBox was not laid out: RenderPhysicalShape#16642 relayoutBoundary=up2 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
Another exception was thrown: 'package:flutter/src/rendering/shifted_box.dart': Failed assertion: line 352 pos 12: 'child!.hasSize': is not true.
Another exception was thrown: RenderBox was not laid out: RenderPhysicalShape#16642 relayoutBoundary=up2
Another exception was thrown: Updated layout information required for RenderFlex#20e2d NEEDS-LAYOUT NEEDS-PAINT to calculate semantics.
```
</details> 

<details>
<summary>flutter doctor -v (mac)</summary>

```
[✓] Flutter (Channel master, 3.7.0-3.0.pre.33, on macOS 12.6 21G115 darwin-arm64, locale en-IN)
    • Flutter version 3.7.0-3.0.pre.33 on channel master 
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 5201856805 (38 minutes ago), 2022-12-05 18:27:21 -0800
    • Engine revision a309d239c4
    • Dart version 2.19.0 (build 2.19.0-463.0.dev)
    • DevTools version 2.20.0
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly
      to perform update checks and upgrades.

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0-rc4)
    • Android SDK at /Users/mahesh/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0-rc4
    • ANDROID_HOME = /Users/mahesh/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14A400
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] IntelliJ IDEA Community Edition (version 2021.2.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 61.2.4
    • Dart plugin version 212.5080.8

[✓] VS Code (version 1.70.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.55.20221129

[✓] Connected device (3 available)
    • iPhone 12 Pro (mobile) • 026D5789-9E78-4AD5-B1B2-3F8D4E7F65E4 • ios            •
      com.apple.CoreSimulator.SimRuntime.iOS-14-5 (simulator)
    • macOS (desktop)        • macos                                • darwin-arm64   • macOS 12.6 21G115 darwin-arm64
    • Chrome (web)           • chrome                               • web-javascript • Google Chrome 108.0.5359.94

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```
```
[✓] Flutter (Channel stable, 3.3.9, on macOS 12.6 21G115 darwin-arm, locale en-IN)
    • Flutter version 3.3.9 on channel stable at /Users/mahesh/Development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision b8f7f1f986 (24 hours ago), 2022-11-23 06:43:51 +0900
    • Engine revision 8f2221fbef
    • Dart version 2.18.5
    • DevTools version 2.15.0

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0-rc4)
    • Android SDK at /Users/mahesh/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0-rc4
    • ANDROID_HOME = /Users/mahesh/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14A400
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] IntelliJ IDEA Community Edition (version 2021.2.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 61.2.4
    • Dart plugin version 212.5080.8

[✓] VS Code (version 1.70.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.53.20221101

[✓] Connected device (3 available)
    • iPhone 12 Pro (mobile) • 026D5789-9E78-4AD5-B1B2-3F8D4E7F65E4 • ios            •
      com.apple.CoreSimulator.SimRuntime.iOS-14-5 (simulator)
    • macOS (desktop)        • macos                                • darwin-arm64   • macOS 12.6 21G115 darwin-arm
    • Chrome (web)           • chrome                               • web-javascript • Google Chrome 107.0.5304.110

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```
</details>

cc: @goderbauer

**Comment by felipecastrosales** [comment]
hey, any news about this or workarounds?

**Comment by Cloud3886** [comment]
use this workaround, 

` final double width =MediaQuery.of(context).size.width;`

Depending on ui you might need to calculate padding seprately like

` final double width = (MediaQuery.of(context).size.width - 80) / 2;`
