### ISSUE TITLE
[image_picker] plugin causes app crash when parent directory does not exist

### ISSUE THREAD

**Issue by yapcwed** [flutter/flutter#46079]
## Steps to Reproduce

1. Invoke image_picker plugin
```dart
final image = await ImagePicker.pickImage(
  source: ImageSource.gallery,
  maxWidth: 640,
  imageQuality: 80,
);
```
2. Select image from phone gallery (internal storage)

**Target Platform: Android**
**Target OS version/browser: 9**
**Devices: Xiaomi Mi 9T**

## Logs

```
[+5570 ms] I/Timeline(15068): Timeline: Activity_launch_request time:352772209
[+5040 ms] D/AndroidRuntime(15068): Shutting down VM
[   +2 ms] E/AndroidRuntime(15068): FATAL EXCEPTION: main
[        ] E/AndroidRuntime(15068): Process: com.yapeal.security.sandbox, PID: 15068
[        ] E/AndroidRuntime(15068): java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=2342, result=-1, data=Intent {
dat=content://com.android.providers.media.documents/document/image:26886 flg=0x1 }} to activity {com.yapeal.security.sandbox/com.yapeal.security.MainActivity}:
java.lang.RuntimeException: java.io.FileNotFoundException:
/storage/emulated/0/Android/data/com.yapeal.security.sandbox/files/Pictures/scaled_IMG_20191203_140653.jpg (No such file or directory)
[        ] E/AndroidRuntime(15068):     at android.app.ActivityThread.deliverResults(ActivityThread.java:4458)
[        ] E/AndroidRuntime(15068):     at android.app.ActivityThread.handleSendResult(ActivityThread.java:4500)
[        ] E/AndroidRuntime(15068):     at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:49)
[  +24 ms] E/AndroidRuntime(15068):     at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
[        ] E/AndroidRuntime(15068):     at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
[        ] E/AndroidRuntime(15068):     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1839)
[        ] E/AndroidRuntime(15068):     at android.os.Handler.dispatchMessage(Handler.java:106)
[        ] E/AndroidRuntime(15068):     at android.os.Looper.loop(Looper.java:201)
[        ] E/AndroidRuntime(15068):     at android.app.ActivityThread.main(ActivityThread.java:6861)
[        ] E/AndroidRuntime(15068):     at java.lang.reflect.Method.invoke(Native Method)
[        ] E/AndroidRuntime(15068):     at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
[        ] E/AndroidRuntime(15068):     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:873)
[        ] E/AndroidRuntime(15068): Caused by: java.lang.RuntimeException: java.io.FileNotFoundException:
/storage/emulated/0/Android/data/com.yapeal.security.sandbox/files/Pictures/scaled_IMG_20191203_140653.jpg (No such file or directory)
[        ] E/AndroidRuntime(15068):     at io.flutter.plugins.imagepicker.ImageResizer.resizeImageIfNeeded(ImageResizer.java:54)
[        ] E/AndroidRuntime(15068):     at io.flutter.plugins.imagepicker.ImagePickerDelegate.handleImageResult(ImagePickerDelegate.java:527)
[        ] E/AndroidRuntime(15068):     at io.flutter.plugins.imagepicker.ImagePickerDelegate.handleChooseImageResult(ImagePickerDelegate.java:463)
[        ] E/AndroidRuntime(15068):     at io.flutter.plugins.imagepicker.ImagePickerDelegate.onActivityResult(ImagePickerDelegate.java:442)
[        ] E/AndroidRuntime(15068):     at io.flutter.app.FlutterPluginRegistry.onActivityResult(FlutterPluginRegistry.java:204)
[        ] E/AndroidRuntime(15068):     at io.flutter.app.FlutterActivityDelegate.onActivityResult(FlutterActivityDelegate.java:132)
[        ] E/AndroidRuntime(15068):     at io.flutter.app.FlutterFragmentActivity.onActivityResult(FlutterFragmentActivity.java:137)
[        ] E/AndroidRuntime(15068):     at android.app.Activity.dispatchActivityResult(Activity.java:7598)
[        ] E/AndroidRuntime(15068):     at android.app.ActivityThread.deliverResults(ActivityThread.java:4451)
[        ] E/AndroidRuntime(15068):     ... 11 more
[        ] E/AndroidRuntime(15068): Caused by: java.io.FileNotFoundException:
/storage/emulated/0/Android/data/com.yapeal.security.sandbox/files/Pictures/scaled_IMG_20191203_140653.jpg (No such file or directory)
[        ] E/AndroidRuntime(15068):     at java.io.FileOutputStream.open0(Native Method)
[        ] E/AndroidRuntime(15068):     at java.io.FileOutputStream.open(FileOutputStream.java:308)
[        ] E/AndroidRuntime(15068):     at java.io.FileOutputStream.<init>(FileOutputStream.java:238)
[        ] E/AndroidRuntime(15068):     at java.io.FileOutputStream.<init>(FileOutputStream.java:180)
[  +23 ms] E/AndroidRuntime(15068):     at io.flutter.plugins.imagepicker.ImageResizer.createOutputStream(ImageResizer.java:114)
[        ] E/AndroidRuntime(15068):     at io.flutter.plugins.imagepicker.ImageResizer.createImageOnExternalDirectory(ImageResizer.java:147)
[        ] E/AndroidRuntime(15068):     at io.flutter.plugins.imagepicker.ImageResizer.resizedImage(ImageResizer.java:105)
[        ] E/AndroidRuntime(15068):     at io.flutter.plugins.imagepicker.ImageResizer.resizeImageIfNeeded(ImageResizer.java:49)
[        ] E/AndroidRuntime(15068):     ... 19 more
[        ] I/Process (15068): Sending signal. PID: 15068 SIG: 9
[  +56 ms] Service protocol connection closed.
[        ] Lost connection to device.
[   +1 ms] DevFS: Deleting filesystem on the device (file:///data/user/0/com.yapeal.security.sandbox/code_cache/mobile-securityXSIKGQ/mobile-security/)
[        ] Sending to VM service: _deleteDevFS({fsName: mobile-security})
[ +259 ms] Ignored error while cleaning up DevFS: TimeoutException after 0:00:00.250000: Future not completed
[   +3 ms] "flutter run" took 179,910ms.
```

```
[✓] Flutter (Channel stable, v1.9.1+hotfix.6, on Mac OS X 10.14.6 18G95, locale en-CH)
    • Flutter version 1.9.1+hotfix.6 at /Users/wederchr/Library/flutter
    • Framework revision 68587a0916 (3 months ago), 2019-09-13 19:46:58 -0700
    • Engine revision b863200c37
    • Dart version 2.5.0

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/wederchr/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.2.1, Build version 11B500
    • CocoaPods version 1.7.3

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 39.0.3
    • Dart plugin version 191.8423
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] IntelliJ IDEA Community Edition (version 2018.3.5)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 33.3.2
    • Dart plugin version 183.5912.23

[✓] VS Code (version 1.40.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 2.22.2

[✓] Connected device (1 available)
    • Pixel 3 XL • 8BFY0YLHC • android-arm64 • Android 10 (API 29)

• No issues found!
```

**Comment by cyanglaz** [comment]
@yapcwed Does this issue occur every time you pick an image with the XIAOMI phone?

**Comment by yapcwed** [comment]
No only the first time after a fresh installation of the app. After that the directory seems to be created and it doesn't occur anymore.

**Comment by iapicca** [comment]
Hi @yapcwed 
are you still experiencing the issue 
with the latest stable version of flutter
and the latest version of `image_picker`?

If so,
could you please provide your update`flutter doctor -v` ,
your `flutter run --verbose`,
your `pubspec.yaml` 
and if possible a reproducible minimal code sample.
Thank you

**Comment by cyanglaz** [comment]
I think this is fixed by https://github.com/flutter/plugins/pull/2341. Closing the issue.
