### ISSUE TITLE
Path w/ char '&' recognized on Android Studio, causes crash on VScode

### ISSUE THREAD

**Issue by Hassan-Fa** [flutter/flutter#46166]
this is autoGenerated by flutter when I tried running it on vs code
it works pretty good on android studio though
I need vs code for this live share feature it provides

## command

flutter run

## exception
```
ProcessException: ProcessException: Process "C:\Users\H&M\AndroidStudioProjects\code_01\android\gradlew.bat" exited abnormally:
'C:\Users\H' is not recognized as an internal or external command,
operable program or batch file.
The system cannot find the path specified.
  Command: C:\Users\H&M\AndroidStudioProjects\code_01\android\gradlew.bat -v
```
<details>
  <summary>logs</summary>

```
#0      runCheckedAsync (package:flutter_tools/src/base/process.dart:259:7)
<asynchronous suspension>
#1      _initializeGradle (package:flutter_tools/src/android/gradle.dart:300:9)
<asynchronous suspension>
#2      _ensureGradle (package:flutter_tools/src/android/gradle.dart:281:37)
<asynchronous suspension>
#3      _readGradleProject (package:flutter_tools/src/android/gradle.dart:192:31)
<asynchronous suspension>
#4      _gradleAppProject (package:flutter_tools/src/android/gradle.dart:112:37)
<asynchronous suspension>
#5      getGradleAppOut (package:flutter_tools/src/android/gradle.dart:106:29)
<asynchronous suspension>
#6      AndroidApk.fromAndroidProject (package:flutter_tools/src/application_package.dart:164:23)
<asynchronous suspension>
#7      ApplicationPackageFactory.getPackageForPlatform (package:flutter_tools/src/application_package.dart:46:32)
<asynchronous suspension>
#8      FlutterDevice.runHot (package:flutter_tools/src/resident_runner.dart:359:56)
<asynchronous suspension>
#9      HotRunner.run (package:flutter_tools/src/run_hot.dart:254:39)
<asynchronous suspension>
#10     RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:472:37)
<asynchronous suspension>
#11     FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:490:18)
#12     _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:71:64)
#13     _rootRunUnary (dart:async/zone.dart:1132:38)
#14     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#15     _FutureListener.handleValue (dart:async/future_impl.dart:137:18)
#16     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:678:45)
#17     Future._propagateToListeners (dart:async/future_impl.dart:707:32)
#18     Future._completeWithValue (dart:async/future_impl.dart:522:5)
#19     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:30:15)
#20     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:288:13)
#21     RunCommand.usageValues (package:flutter_tools/src/commands/run.dart)
#22     _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:71:64)
#23     _rootRunUnary (dart:async/zone.dart:1132:38)
#24     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#25     _FutureListener.handleValue (dart:async/future_impl.dart:137:18)
#26     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:678:45)
#27     Future._propagateToListeners (dart:async/future_impl.dart:707:32)
#28     Future._completeWithValue (dart:async/future_impl.dart:522:5)
#29     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:30:15)
#30     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:288:13)
#31     AndroidDevice.isLocalEmulator (package:flutter_tools/src/android/android_device.dart)
#32     _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:71:64)
#33     _rootRunUnary (dart:async/zone.dart:1132:38)
#34     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#35     _FutureListener.handleValue (dart:async/future_impl.dart:137:18)
#36     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:678:45)
#37     Future._propagateToListeners (dart:async/future_impl.dart:707:32)
#38     Future._completeWithValue (dart:async/future_impl.dart:522:5)
#39     Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:552:7)
#40     _rootRun (dart:async/zone.dart:1124:13)
#41     _CustomZone.run (dart:async/zone.dart:1021:19)
#42     _CustomZone.runGuarded (dart:async/zone.dart:923:7)
#43     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:963:23)
#44     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#45     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#46     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:116:13)
#47     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:173:5)
```

</details>

## flutter doctor

```
[32m[✓][39m Flutter (Channel stable, v1.9.1+hotfix.6, on Microsoft Windows [Version 10.0.18362.116], locale en-US)
    [32m•[39m Flutter version 1.9.1+hotfix.6 at C:\flutter_files\SDK\flutter
    [32m•[39m Framework revision 68587a0916 (3 months ago), 2019-09-13 19:46:58 -0700
    [32m•[39m Engine revision b863200c37
    [32m•[39m Dart version 2.5.0

[32m[✓][39m Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    [32m•[39m Android SDK at C:\ANDROID_HOME
    [32m•[39m Android NDK location not configured (optional; useful for native profiling support)
    [32m•[39m Platform android-29, build-tools 29.0.2
    [32m•[39m ANDROID_HOME = C:\ANDROID_HOME
    [32m•[39m Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    [32m•[39m Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)
    [32m•[39m All Android licenses accepted.

[32m[✓][39m Android Studio (version 3.2)
    [32m•[39m Android Studio at C:\Program Files\Android\Android Studio
    [32m•[39m Flutter plugin version 31.3.1
    [32m•[39m Dart plugin version 181.5656
    [32m•[39m Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)

[32m[✓][39m VS Code (version 1.40.2)
    [32m•[39m VS Code at C:\Users\H&M\AppData\Local\Programs\Microsoft VS Code
    [32m•[39m Flutter extension version 3.6.0

[32m[✓][39m Connected device (1 available)
    [32m•[39m LG M700 • LGM70056ba4f7 • android-arm • Android 8.1.0 (API 27)

[32m•[39m No issues found!
```

**Comment by phanirithvij** [comment]
This is my suggestion as I've faced the same problem:

The problem is with your username H&M. If possible change it to something with no spaces and `!@#$%^&*()_-\|/?<>;':"+` characters. That would help you avoid many issues in the future on windows.

Another solution is to re-install flutter, android studio etc.. in another drive eg. `D:\` and not have any spaces and non-windows friendly characters. And changing the username is not easy to do on windows.

**Comment by Hassan-Fa** [comment]
@phanirithvij yup did that ❤️

**Comment by phanirithvij** [comment]
You may close this issue and don't forget to explain how you were able to solve it before closing this.

**Comment by Hassan-Fa** [comment]
[Solved]

the problem was with the weird character (&) in the Windows Account Name (username) as @phanirithvij mentioned

Steps to resolve :

- since even after changing the username from the control panel , C:\Users\<"username"> folder's name won't change , created another user.

- made it admin.

- copied SDK folders to another Drive so that IDE could access them without admin permits (even opening IDE as admin didn't give admin privileges to it's terminal smh).

- now VSCode works perfect like AS.

thanks @phanirithvij ❤️ for pointing that out
