### ISSUE TITLE
[china] Failed to send crash report due to a network error: ...

### ISSUE THREAD

**Issue by kinmoLun** [flutter/flutter#46164]
## Steps to Reproduce

1. Create a new flutter test project

2. Run the ‘flutter run’ command

3. These errors occur ‘ Sending crash report to Google.
Failed to send crash report due to a network error: SocketException: OS Error:
Operation timed out, errno = 60, address = clients2.google.com, port = 65240
Oops; flutter has exited unexpectedly.
⣽
Sending crash report to Google.
 
Crash report written to /Users/kimz/flutterApp/test01/flutter_07.log;
please let us know at https://github.com/flutter/flutter/issues. ’

**/Users/kimz/flutterApp/test01/flutter_07.log Content:**

`Flutter crash report; please file at https://github.com/flutter/flutter/issues.

## command

flutter run

## exception

`ArgumentError: Invalid argument(s): Cannot find executable for /Users/kimz/flutter/bin/cache/artifacts/libimobiledevice/ideviceinfo.`

<details>
  <summary>logs</summary>

```
#0      _getExecutable (package:process/src/interface/local_process_manager.dart:127:5)
#1      LocalProcessManager.run (package:process/src/interface/local_process_manager.dart:68:30)
#2      IMobileDevice.getInfoForDevice (package:flutter_tools/src/ios/mac.dart:199:57)
<asynchronous suspension>
#3      IOSDevice.getAttachedDevices (package:flutter_tools/src/ios/devices.dart:184:55)
<asynchronous suspension>
#4      IOSDevices.pollingGetDevices (package:flutter_tools/src/ios/devices.dart:117:57)
#5      PollingDeviceDiscovery.devices (package:flutter_tools/src/device.dart:270:52)
<asynchronous suspension>
#6      DeviceManager.getAllConnectedDevices (package:flutter_tools/src/device.dart:136:46)
<asynchronous suspension>
#7      DeviceManager.getDevices (package:flutter_tools/src/device.dart:126:11)
#8      DeviceManager.findTargetDevices (package:flutter_tools/src/device.dart:169:34)
<asynchronous suspension>
#9      FlutterCommand.findAllTargetDevices (package:flutter_tools/src/runner/flutter_command.dart:515:48)
<asynchronous suspension>
#10     RunCommand.validateCommand (package:flutter_tools/src/commands/run.dart:279:21)
<asynchronous suspension>
#11     FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:465:11)
<asynchronous suspension>
#12     FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:407:33)
<asynchronous suspension>
#13     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:154:29)
<asynchronous suspension>
#14     _rootRun (dart:async/zone.dart:1124:13)
#15     _CustomZone.run (dart:async/zone.dart:1021:19)
#16     _runZoned (dart:async/zone.dart:1516:10)
#17     runZoned (dart:async/zone.dart:1463:12)
#18     AppContext.run (package:flutter_tools/src/base/context.dart:153:18)
<asynchronous suspension>
#19     FlutterCommand.run (package:flutter_tools/src/runner/flutter_command.dart:397:20)
#20     CommandRunner.runCommand (package:args/command_runner.dart:197:27)
<asynchronous suspension>
#21     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:402:21)
<asynchronous suspension>
#22     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:154:29)
<asynchronous suspension>
#23     _rootRun (dart:async/zone.dart:1124:13)
#24     _CustomZone.run (dart:async/zone.dart:1021:19)
#25     _runZoned (dart:async/zone.dart:1516:10)
#26     runZoned (dart:async/zone.dart:1463:12)
#27     AppContext.run (package:flutter_tools/src/base/context.dart:153:18)
<asynchronous suspension>
#28     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:356:19)
<asynchronous suspension>
#29     CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:112:25)
#30     new Future.sync (dart:async/future.dart:224:31)
#31     CommandRunner.run (package:args/command_runner.dart:112:14)
#32     FlutterCommandRunner.run (package:flutter_tools/src/runner/flutter_command_runner.dart:242:18)
#33     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:63:22)
<asynchronous suspension>
#34     _rootRun (dart:async/zone.dart:1124:13)
#35     _CustomZone.run (dart:async/zone.dart:1021:19)
#36     _runZoned (dart:async/zone.dart:1516:10)
#37     runZoned (dart:async/zone.dart:1500:12)
#38     run.<anonymous closure> (package:flutter_tools/runner.dart:61:18)
<asynchronous suspension>
#39     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:154:29)
<asynchronous suspension>
#40     _rootRun (dart:async/zone.dart:1124:13)
#41     _CustomZone.run (dart:async/zone.dart:1021:19)
#42     _runZoned (dart:async/zone.dart:1516:10)
#43     runZoned (dart:async/zone.dart:1463:12)
#44     AppContext.run (package:flutter_tools/src/base/context.dart:153:18)
<asynchronous suspension>
#45     runInContext (package:flutter_tools/src/context_runner.dart:59:24)
<asynchronous suspension>
#46     run (package:flutter_tools/runner.dart:50:10)
#47     main (package:flutter_tools/executable.dart:65:9)
<asynchronous suspension>
#48     main (file:///b/s/w/ir/k/archive/flutter/packages/flutter_tools/bin/flutter_tools.dart:8:3)
#49     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:303:32)
#50     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:12)
```

</details>

<details>
  <summary>logs</summary>

```
encountered exception: Invalid argument(s): Cannot find executable for /Users/kimz/flutter/bin/cache/artifacts/libimobiledevice/ideviceinfo.

#0      _getExecutable (package:process/src/interface/local_process_manager.dart:127:5)
#1      LocalProcessManager.run (package:process/src/interface/local_process_manager.dart:68:30)
#2      IMobileDevice.getInfoForDevice (package:flutter_tools/src/ios/mac.dart:199:57)
<asynchronous suspension>
#3      IOSDevice.getAttachedDevices (package:flutter_tools/src/ios/devices.dart:184:55)
<asynchronous suspension>
#4      IOSDevices.pollingGetDevices (package:flutter_tools/src/ios/devices.dart:117:57)
#5      PollingDeviceDiscovery.devices (package:flutter_tools/src/device.dart:270:52)
<asynchronous suspension>
#6      DeviceManager.getAllConnectedDevices (package:flutter_tools/src/device.dart:136:46)
<asynchronous suspension>
#7      DeviceValidator.validate (package:flutter_tools/src/doctor.dart:760:54)
<asynchronous suspension>
#8      Doctor.startValidatorTasks (package:flutter_tools/src/doctor.dart:140:52)
#9      Doctor.diagnose (package:flutter_tools/src/doctor.dart:211:41)
#10     _AsyncAwaitCompleter.start (dart:async-patch/async_patch.dart:43:6)
#11     Doctor.diagnose (package:flutter_tools/src/doctor.dart:201:24)
#12     _doctorText.<anonymous closure> (package:flutter_tools/runner.dart:202:26)
#13     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:154:29)
#14     _AsyncAwaitCompleter.start (dart:async-patch/async_patch.dart:43:6)
#15     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:154:7)
#16     _rootRun (dart:async/zone.dart:1124:13)
#17     _CustomZone.run (dart:async/zone.dart:1021:19)
#18     _runZoned (dart:async/zone.dart:1516:10)
#19     runZoned (dart:async/zone.dart:1463:12)
#20     AppContext.run (package:flutter_tools/src/base/context.dart:153:18)
#21     _AsyncAwaitCompleter.start (dart:async-patch/async_patch.dart:43:6)
#22     AppContext.run (package:flutter_tools/src/base/context.dart:140:19)
#23     _doctorText (package:flutter_tools/runner.dart:201:19)
#24     _AsyncAwaitCompleter.start (dart:async-patch/async_patch.dart:43:6)
#25     _doctorText (package:flutter_tools/runner.dart:197:27)
#26     _createLocalCrashReport (package:flutter_tools/runner.dart:179:32)
#27     _AsyncAwaitCompleter.start (dart:async-patch/async_patch.dart:43:6)
#28     _createLocalCrashReport (package:flutter_tools/runner.dart:164:37)
#29     _handleToolError (package:flutter_tools/runner.dart:134:33)
#30     _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:71:64)
#31     _rootRunUnary (dart:async/zone.dart:1132:38)
#32     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#33     _FutureListener.handleValue (dart:async/future_impl.dart:137:18)
#34     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:678:45)
#35     Future._propagateToListeners (dart:async/future_impl.dart:707:32)
#36     Future._completeWithValue (dart:async/future_impl.dart:522:5)
#37     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:30:15)
#38     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:288:13)
#39     CrashReportSender.sendReport (package:flutter_tools/src/reporting/crash_reporting.dart)
#40     _asyncErrorWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:78:45)
#41     _rootRunBinary (dart:async/zone.dart:1144:38)
#42     _CustomZone.runBinary (dart:async/zone.dart:1037:19)
#43     _FutureListener.handleError (dart:async/future_impl.dart:151:20)
#44     Future._propagateToListeners.handleError (dart:async/future_impl.dart:690:47)
#45     Future._propagateToListeners (dart:async/future_impl.dart:711:24)
#46     Future._completeError (dart:async/future_impl.dart:530:5)
#47     _AsyncAwaitCompleter.completeError (dart:async-patch/async_patch.dart:36:15)
#48     IOClient.send (package:http/src/io_client.dart)
#49     _asyncErrorWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:78:45)
#50     _rootRunBinary (dart:async/zone.dart:1144:38)
#51     _CustomZone.runBinary (dart:async/zone.dart:1037:19)
#52     _FutureListener.handleError (dart:async/future_impl.dart:151:20)
#53     Future._propagateToListeners.handleError (dart:async/future_impl.dart:690:47)
#54     Future._propagateToListeners (dart:async/future_impl.dart:711:24)
#55     Future._completeError (dart:async/future_impl.dart:530:5)
#56     Future._asyncCompleteError.<anonymous closure> (dart:async/future_impl.dart:578:7)
#57     _rootRun (dart:async/zone.dart:1124:13)
#58     _CustomZone.run (dart:async/zone.dart:1021:19)
#59     _CustomZone.runGuarded (dart:async/zone.dart:923:7)
#60     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:963:23)
#61     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#62     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#63     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:116:13)
#64     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:173:5)
```

</details>

4. ps: This problem occurs for a period of time every day, and then returns to normal without any modification.

<details>
  <summary>logs</summary>

```
 ⣻
Sending crash report to Google.
Failed to send crash report due to a network error: SocketException: OS Error: Operation timed out, errno = 60, address =
clients2.google.com, port = 65355
Oops; flutter has exited unexpectedly.
⣻Unhandled exception:
Invalid argument(s): Cannot find executable for /Users/kimz/flutter/bin/cache/artifacts/libimobiledevice/ideviceinfo.
#0      _getExecutable (package:process/src/interface/local_process_manager.dart:127:5)
#1      LocalProcessManager.run (package:process/src/interface/local_process_manager.dart:68:30)
#2      IMobileDevice.getInfoForDevice (package:flutter_tools/src/ios/mac.dart:199:57)
<asynchronous suspension>
#3      IOSDevice.getAttachedDevices (package:flutter_tools/src/ios/devices.dart:184:55)
<asynchronous suspension>
#4      IOSDevices.pollingGetDevices (package:flutter_tools/src/ios/devices.dart:117:57)
#5      PollingDeviceDiscovery.devices (package:flutter_tools/src/device.dart:270:52)
<asynchronous suspension>
#6      DeviceManager.getAllConnectedDevices (package:flutter_tools/src/device.dart:136:46)
<asynchronous suspension>
#7      DeviceValidator.validate (package:flutter_tools/src/doctor.dart:760:54)
<asynchronous suspension>
#8      Doctor.startValidatorTasks (package:flutter_tools/src/doctor.dart:140:52)
#9      Doctor.diagnose (package:flutter_tools/src/doctor.dart:211:41)
#10     _AsyncAwaitCompleter.start (dart:async-patch/async_patch.dart:43:6)
#11     Doctor.diagnose (package:flutter_tools/src/doctor.dart:201:24)
#12     _doctorText.<anonymous closure> (package:flutter_tools/runner.dart:202:26)
#13     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:154:29)
#14     _AsyncAwaitCompleter.start (dart:async-patch/async_patch.dart:43:6)
#15     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:154:7)
#16     _rootRun (dart:async/zone.dart:1124:13)
#17     _CustomZone.run (dart:async/zone.dart:1021:19)
#18     _runZoned (dart:async/zone.dart:1516:10)
#19     runZoned (dart:async/zone.dart:1463:12)
#20     AppContext.run (package:flutter_tools/src/base/context.dart:153:18)
#21     _AsyncAwaitCompleter.start (dart:async-patch/async_patch.dart:43:6)
#22     AppContext.run (package:flutter_tools/src/base/context.dart:140:19)
#23     _doctorText (package:flutter_tools/runner.dart:201:19)
#24     _AsyncAwaitCompleter.start (dart:async-patch/async_patch.dart:43:6)
#25     _doctorText (package:flutter_tools/runner.dart:197:27)
#26     _createLocalCrashReport (package:flutter_tools/runner.dart:179:32)
#27     _AsyncAwaitCompleter.start (dart:async-patch/async_patch.dart:43:6)
#28     _createLocalCrashReport (package:flutter_tools/runner.dart:164:37)
#29     _handleToolError (package:flutter_tools/runner.dart:134:33)
#30     _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:71:64)
#31     _rootRunUnary (dart:async/zone.dart:1132:38)
#32     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#33     _FutureListener.handleValue (dart:async/future_impl.dart:137:18)
#34     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:678:45)
#35     Future._propagateToListeners (dart:async/future_impl.dart:707:32)
#36     Future._completeWithValue (dart:async/future_impl.dart:522:5)
#37     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:30:15)
#38     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:288:13)
#39     CrashReportSender.sendReport (package:flutter_tools/src/reporting/crash_reporting.dart)
#40     _asyncErrorWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:78:45)
#41     _rootRunBinary (dart:async/zone.dart:1144:38)
#42     _CustomZone.runBinary (dart:async/zone.dart:1037:19)
#43     _FutureListener.handleError (dart:async/future_impl.dart:151:20)
#44     Future._propagateToListeners.handleError (dart:async/future_impl.dart:690:47)
#45     Future._propagateToListeners (dart:async/future_impl.dart:711:24)
#46     Future._completeError (dart:async/future_impl.dart:530:5)
#47     _AsyncAwaitCompleter.completeError (dart:async-patch/async_patch.dart:36:15)
#48     IOClient.send (package:http/src/io_client.dart)
#49     _asyncErrorWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:78:45)
#50     _rootRunBinary (dart:async/zone.dart:1144:38)
#51     _CustomZone.runBinary (dart:async/zone.dart:1037:19)
#52     _FutureListener.handleError (dart:async/future_impl.dart:151:20)
#53     Future._propagateToListeners.handleError (dart:async/future_impl.dart:690:47)
#54     Future._propagateToListeners (dart:async/future_impl.dart:711:24)
#55     Future._completeError (dart:async/future_impl.dart:530:5)
#56     Future._asyncCompleteError.<anonymous closure> (dart:async/future_impl.dart:578:7)
#57     _rootRun (dart:async/zone.dart:1124:13)
#58     _CustomZone.run (dart:async/zone.dart:1021:19)
#59     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:947:23)
#60     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#61     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#62     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:116:13)
#63     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:173:5)
```
</details>

<details>
  <summary>flutter doctor -v</summary>

```

[✓] Flutter (Channel stable, v1.9.1+hotfix.6, on Mac OS X 10.15.1 19B88, locale
    zh-Hans-CN)
    • Flutter version 1.9.1+hotfix.6 at /Users/kimz/flutter
    • Framework revision 68587a0916 (3 months ago), 2019-09-13 19:46:58 -0700
    • Engine revision b863200c37
    • Dart version 2.5.0
 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/kimz/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.2.1, Build version 11B500
    • CocoaPods version 1.8.4

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 41.1.2
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] VS Code (version 1.40.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.6.0
```

</details>

**Comment by iapicca** [comment]
Hi @kinmoLun 
are you behind a proxy, a firewall
or connected from China?
thank  you

**Comment by kinmoLun** [comment]
> Hi @kinmoLun
> are you behind a proxy, a firewall
> or connected from China?
> thank you

I am in China and use a proxy service

**Comment by zuherabud** [comment]
did anyone find a solution

**Comment by iapicca** [comment]
Hi @kinmoLun 
please look at this [documentation](https://flutter.dev/community/china),
does this solution work for you?
thank you

**Comment by kinmoLun** [comment]
> Hi @kinmoLun
> please look at this [documentation](https://flutter.dev/community/china),
> does this solution work for you?
> thank you

After I reinstalled, the issue was resolved.

**Comment by iapicca** [comment]
Hi @kinmoLun 
I'm glad that you solved the issue
thank you for letting me know
