### ISSUE TITLE
googleSignIn.signIn() crash on IOS after Flutter upgrade

### ISSUE THREAD

**Issue by pazhut** [flutter/flutter#46190]
using this line of code:
`final GoogleSignInAccount account = await googleSignIn.signIn();`

my app crash and i am getting the following console output:

```
flutter: onTransition: Transition { currentState: AuthStarted, event: ClickedGoogleSignIn, nextState: AuthInProgress }
flutter: BlocBuilder: AuthInProgress
flutter: #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:569:7)
#1      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:321:33)
<asynchronous suspension>
#2      MethodChannel.invokeMapMethod (package:flutter/src/services/platform_channel.dart:349:48)
#3      MethodChannelGoogleSignIn.signIn (package:google_sign_in_platform_interface/src/method_channel_google_sign_in.dart:43:10)
#4      GoogleSignIn._callMethod (package:google_sign_in/google_sign_in.dart:212:42)
<asynchronous suspension>
#5      GoogleSignIn._addMethodCall (package:google_sign_in/google_sign_in.dart:266:18)
#6      GoogleSignIn.signIn (package:google_sign_in/google_sign_in.dart:336:9)
#7      AuthenticationProvider.signInWithGoogle (package:jobs_on_the_go/providers/AuthenticationProvider.dart:60:60)
#8      AuthenticationRepository.signInWithGoogle (package:jobs_on_the_go/repositories/AuthenticationRepository.dart:16:77)
#9      AuthenticationBloc.mapCl<…>
flutter: onTransition: Transition { currentState: AuthInProgress, event: ClickedGoogleSignIn, nextState: UnAuthenticated }
Lost connection to device.

flutter: BlocBuilder: UnAuthenticated
```

*** First throw call stack:
```
(
	0   CoreFoundation                      0x00000001103aa02e __exceptionPreprocess + 350
	1   libobjc.A.dylib                     0x000000010fd7bb20 objc_exception_throw + 48
	2   CoreFoundation                      0x00000001103a9e6c +[NSException raise:format:] + 188
	3   Runner                              0x0000000109b11321 -[GIDSignIn signInWithOptions:] + 276
	4   Runner                              0x0000000109b10c56 -[GIDSignIn signIn] + 64
	5   Runner                              0x000000010964a40a -[FLTGoogleSignInPlugin handleMethodCall:result:] + 2410
	6   Flutter                             0x000000010cce3f95 __45-[FlutterMethodChannel setMethodCallHandler:]_block_invoke + 104
	7   Flutter                             0x000000010cc77d80 _ZNK7flu<…>
```

this is working OK on Android

Flutter doctor output:
```
[✓] Flutter (Channel beta, v1.12.13+hotfix.1, on Mac OS X 10.15.1 19B88, locale en-CA)
    • Flutter version 1.12.13+hotfix.1 at /Users/pazhutmann/Work/flutter
    • Framework revision 5b07015393 (3 days ago), 2019-12-03 00:12:02 -0800
    • Engine revision c1e322b685
    • Dart version 2.7.0

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/pazhutmann/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.2.1, Build version 11B500
    • CocoaPods version 1.8.3

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 41.1.2
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] Connected device (1 available)
    • iPhone 8 • 69D1F18B-87C4-45A6-9722-4B0580828A17 • ios • com.apple.CoreSimulator.SimRuntime.iOS-13-2 (simulator)

• No issues found!
```

i am using latest plugin version (google_sign_in: ^4.0.14)

**Comment by iapicca** [comment]
Hi @pazhut 
can you please provide your  your `flutter run --verbose`?
Also, to better address the issue, would be helpful
if you could post  a minimal code sample
or the steps to reproduce the problem.
Thank you

**Comment by pazhut** [comment]
Hi

the steps to reproduce are simple, just call the API i mentioned, i would like to add that this used to work until a day ago, i would be happy to provide you with the log you are asking for, as i am running inside Android studio can you please provide me instructions on how to produce it?

Thanks much

**Comment by pazhut** [comment]
issues solved, turned out that integrating both Google signin and Facebook one required some careful editing of the plist.info file to have both URL bundles

Thanks much

**Comment by jlund24** [comment]
@pazhut Thank you so much, this was driving me insane. My issue came when I swapped firebase projects and was using a new GoogleInfo.plist. The url bundle did not get transferred correctly over to the plist.info and I had to do this manually
