### ISSUE TITLE
flutter drive error message problem on master channel

### ISSUE THREAD

**Issue by iptton** [flutter/flutter#46215]
# Steps to Reproduce
1. run `flutter drive --target=xxx -v`

```
**Target Platform: any(iOS simulator or Android real device)
**Target OS version/browser: MacOS 10.15.1
**Devices:**
```

<details>
  <summary>logs</summary>

```
[  +73 ms] No devices found.
[   +9 ms] "flutter drive" took 574ms.

#0      throwToolExit (package:flutter_tools/src/base/common.dart:28:3)
#1      DriveCommand.runCommand
(package:flutter_tools/src/commands/drive.dart:103:7)
<asynchronous suspension>
#2      FlutterCommand.verifyThenRunCommand
(package:flutter_tools/src/runner/flutter_command.dart:620:18)
#3      _asyncThenWrapperHelper.<anonymous closure>
(dart:async-patch/async_patch.dart:74:64)
#4      _rootRunUnary (dart:async/zone.dart:1134:38)
#5      _CustomZone.runUnary (dart:async/zone.dart:1031:19)
#6      _FutureListener.handleValue (dart:async/future_impl.dart:140:18)
#7      Future._propagateToListeners.handleValueCallback
(dart:async/future_impl.dart:682:45)
#8      Future._propagateToListeners (dart:async/future_impl.dart:711:32)
#9      Future._completeWithValue (dart:async/future_impl.dart:526:5)
#10     Future._asyncComplete.<anonymous closure>
(dart:async/future_impl.dart:556:7)
#11     _rootRun (dart:async/zone.dart:1126:13)
#12     _CustomZone.run (dart:async/zone.dart:1023:19)
#13     _CustomZone.runGuarded (dart:async/zone.dart:925:7)
#14     _CustomZone.bindCallbackGuarded.<anonymous closure>
(dart:async/zone.dart:965:23)
#15     _microtaskLoop (dart:async/schedule_microtask.dart:43:21)
#16     _startMicrotaskLoop (dart:async/schedule_microtask.dart:52:5)
#17     _runPendingImmediateCallback
(dart:isolate-patch/isolate_patch.dart:118:13)
#18     _RawReceivePortImpl._handleMessage
(dart:isolate-patch/isolate_patch.dart:175:5)
```

</details>

<details>
  <summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel master, v1.13.1-pre.47, on Mac OS X 10.15.1 19B88, locale zh-Hans-CN)
    • Flutter version 1.13.1-pre.47 at /Users/flutter
    • Framework revision ad20d368ff (3 hours ago), 2019-12-05 19:33:01 -0800
    • Engine revision 0506c65f59
    • Dart version 2.7.0 (build 2.7.0-dev.2.1 a9c77229c2)

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.0-rc3)
    • Android SDK at /Users/Library/Android/sdk/
    • Android NDK at /Users/Library/Android/sdk/ndk-bundle
    • Platform android-29, build-tools 29.0.0-rc3
    • ANDROID_HOME = /Users/Library/Android/sdk/
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.2.1, Build version 11B500
    • CocoaPods version 1.8.4

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 41.1.2
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] Connected device (2 available)
    • VOG AL00 • MQSGL19614000092 • android-arm64 • Android 10 (API 29)
    • macOS    • macOS            • darwin-x64    • Mac OS X 10.15.1 19B88

• No issues found!
```

</details>

**Comment by iptton** [comment]
Flutter crash report; please file at https://github.com/flutter/flutter/issues.

## command

flutter drive --target=test_driver/app.dart -v

## exception

NoSuchMethodError: NoSuchMethodError: The getter 'id' was called on null.
Receiver: null
Tried calling: id

```
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:51:5)
#1      IOSSimulator.isAppInstalled (package:flutter_tools/src/ios/simulators.dart:270:52)
#2      _startApp (package:flutter_tools/src/commands/drive.dart:243:30)
<asynchronous suspension>
#3      DriveCommand.runCommand (package:flutter_tools/src/commands/drive.dart:121:51)
<asynchronous suspension>
#4      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:490:18)
#5      _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:71:64)
#6      _rootRunUnary (dart:async/zone.dart:1132:38)
#7      _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#8      _FutureListener.handleValue (dart:async/future_impl.dart:137:18)
#9      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:678:45)
#10     Future._propagateToListeners (dart:async/future_impl.dart:707:32)
#11     Future._completeWithValue (dart:async/future_impl.dart:522:5)
#12     Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:552:7)
#13     _rootRun (dart:async/zone.dart:1124:13)
#14     _CustomZone.run (dart:async/zone.dart:1021:19)
#15     _CustomZone.runGuarded (dart:async/zone.dart:923:7)
#16     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:963:23)
#17     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#18     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#19     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:116:13)
#20     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:173:5)
```

## flutter doctor

```
[32m[✓][39m Flutter (Channel stable, v1.9.1+hotfix.6, on Mac OS X 10.15.1 19B88, locale zh-Hans-CN)
    [32m•[39m Flutter version 1.9.1+hotfix.6 at /Users/ippan/Documents/flutter
    [32m•[39m Framework revision 68587a0916 (3 months ago), 2019-09-13 19:46:58 -0700
    [32m•[39m Engine revision b863200c37
    [32m•[39m Dart version 2.5.0

[32m[✓][39m Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    [32m•[39m Android SDK at /Users/ippan/Library/Android/sdk
    [32m•[39m Android NDK location not configured (optional; useful for native profiling support)
    [32m•[39m Platform android-29, build-tools 29.0.2
    [32m•[39m ANDROID_HOME = /Users/ippan/Library/Android/sdk
    [32m•[39m Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    [32m•[39m Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    [32m•[39m All Android licenses accepted.

[32m[✓][39m Xcode - develop for iOS and macOS (Xcode 11.2.1)
    [32m•[39m Xcode at /Applications/Xcode.app/Contents/Developer
    [32m•[39m Xcode 11.2.1, Build version 11B500
    [32m•[39m CocoaPods version 1.8.4

[32m[✓][39m Android Studio (version 3.5)
    [32m•[39m Android Studio at /Applications/Android Studio.app/Contents
    [32m•[39m Flutter plugin version 41.1.2
    [32m•[39m Dart plugin version 191.8593
    [32m•[39m Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[32m[✓][39m Android Studio
    [32m•[39m Android Studio at /Applications/Android Studio 4.0 Preview.app/Contents
    [32m•[39m Flutter plugin version 41.2.3
    [32m•[39m Dart plugin version 192.7761
    [32m•[39m Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)

[33m[!][39m IntelliJ IDEA Ultimate Edition (version 2019.2.4)
    [32m•[39m IntelliJ at /Applications/IntelliJ IDEA.app
    [31m✗[39m Flutter plugin not installed; this adds Flutter specific functionality.
    [31m✗[39m Dart plugin not installed; this adds Dart specific functionality.
    [32m•[39m For information about installing plugins, see
      https://flutter.dev/intellij-setup/#installing-the-plugins

[33m[!][39m IntelliJ IDEA Community Edition (version 2019.2)
    [32m•[39m IntelliJ at /Applications/IntelliJ IDEA CE.app
    [31m✗[39m Flutter plugin not installed; this adds Flutter specific functionality.
    [31m✗[39m Dart plugin not installed; this adds Dart specific functionality.
    [32m•[39m For information about installing plugins, see
      https://flutter.dev/intellij-setup/#installing-the-plugins

[32m[✓][39m VS Code (version 1.40.2)
    [32m•[39m VS Code at /Applications/Visual Studio Code.app/Contents
    [32m•[39m Flutter extension version 3.7.0

[32m[✓][39m Connected device (1 available)
    [32m•[39m iPhone 11 Pro Max • 77601539-763A-4C42-BCC2-9BFB44B48727 • ios • com.apple.CoreSimulator.SimRuntime.iOS-13-2 (simulator)

[33m![39m Doctor found issues in 2 categories.
```

**Comment by iapicca** [comment]
Hi @iptton 
i see you are describing two different issues;
in the first, using `flutter channel master` your logs show 
```
[  +73 ms] No devices found.
[   +9 ms] "flutter drive" took 574ms.
```
in the second, using `flutter channel stable` 
appear to be an error from the code.

Could you please describe the issue in details an provide
a minimal code sample or the steps to reproduce the problem?
Thank you

**Comment by iptton** [comment]
@ianloic sorry for that confuse , It may be two issues at the same codebase.
issue 1 : cannot found devices, but actually flutter devices can find my phone
issue 2 : same as https://github.com/flutter/flutter/issues/43258

**Comment by iptton** [comment]
@ianloic trying to reproduce the problem in other computer. found something:
Maybe I'm doing wrong with `flutter drive`: 
code puts here: https://github.com/iptton/inview_notifier_list

when using stable branch: the same code with `flutter drive --target=test_drive/main.dart`: output:
> AndroidManifest.xml could not be found
but in master branch, the output is :

> [  +73 ms] No devices found.
> [   +9 ms] "flutter drive" took 574ms.
> 
> #0      throwToolExit (package:flutter_tools/src/base/common.dart:28:3)
> #1      DriveCommand.runCommand

**Comment by iptton** [comment]
**solved**
I do two things wrong about flutter drive:
1. test_driver must under a dir that has android or iOS dir. so testing an extension should be in the example?
2. in test_driver/xxx_test.dart file **must not** contains any widget imports. In my case, I've import a dart file for a const value.
