### ISSUE TITLE
[cocoon] update agent health increased 500ing since HealthDetails is longer than 1500 bytes

### ISSUE THREAD

**Issue by CaseyHillers** [flutter/flutter#46239]
```
ApplicationError: The value of property "HealthDetails" is longer than 1500 bytes.
#0      GrpcDatastoreImpl.commit (package:appengine/src/grpc_api_impl/datastore_impl.dart:113:9)
<asynchronous suspension>
#1      _commitHelper (package:gcloud/src/db/db.dart:409:8)
#2      DatastoreDB.commit (package:gcloud/src/db/db.dart:374:12)
#3      UpdateAgentHealth.post (package:cocoon_service/src/request_handlers/update_agent_health.dart:57:24)
<asynchronous suspension>
#4      RequestHandler.service.<anonymous closure> (package:cocoon_service/src/request_handling/request_handler.dart:49:28)
<asynchronous suspension>
#5      _rootRun (dart:async/zone.dart:1124:13)
#6      _CustomZone.run (dart:async/zone.dart:1021:19)
#7      _runZoned (dart:async/zone.dart:1516:10)
#8      runZoned (dart:async/zone.dart:1463:12)
#9      RequestHandler.service (package:cocoon_service/src/request_handling/request_handler.dart:39:12)
#10     ApiRequestHandler.service.<anonymous closure> (package:cocoon_service/src/request_handling/api_request_handler.dart:130:19)
<asynchronous suspension>
#11     _rootRun (dart:async/zone.dart:1124:13)
#12     _CustomZone.run (dart:async/zone.dart:1021:19)
#13     _runZoned (dart:async/zone.dart:1516:10)
#14     runZoned (dart:async/zone.dart:1463:12)
#15     ApiRequestHandler.service (package:cocoon_service/src/request_handling/api_request_handler.dart:129:11)
<asynchronous suspension>
#16     main.<anonymous closure>.<anonymous closure> (file:///app/bin/server.dart:67:23)
<asynchronous suspension>
#17     runAppEngine.<anonymous closure> (package:appengine/appengine.dart:80:12)
#18     runAppEngine.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:appengine/src/appengine_internal.dart:57:18)
#19     _ServiceScope._fork.<anonymous closure> (package:gcloud/service_scope.dart:209:19)
#20     _rootRun (dart:async/zone.dart:1124:13)
#21     _CustomZone.run (dart:async/zone.dart:1021:19)
#22     _runZoned (dart:async/zone.dart:1516:10)
#23     runZoned (dart:async/zone.dart:1500:12)
#24     _ServiceScope._fork (package:gcloud/service_scope.dart:208:12)
#25     fork (package:gcloud/service_scope.dart:104:30)
#26     runAppEngine.<anonymous closure>.<anonymous closure> (package:appengine/src/appengine_internal.dart:55:9)
#27     AppEngineHttpServer.run.<anonymous closure>.<anonymous closure> (package:appengine/src/server/server.dart:83:16)
#28     _rootRunUnary (dart:async/zone.dart:1132:38)
#29     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#30     _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
#31     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#32     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#33     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:764:19)
#34     _StreamController._add (dart:async/stream_controller.dart:640:7)
#35     _StreamController.add (dart:async/stream_controller.dart:586:5)
#36     _HttpServer._handleRequest (dart:_http/http_impl.dart:2730:19)
#37     new _HttpConnection.<anonymous closure> (dart:_http/http_impl.dart:2488:19)
#38     _rootRunUnary (dart:async/zone.dart:1132:38)
#39     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#40     _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
#41     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#42     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#43     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:764:19)
#44     _StreamController._add (dart:async/stream_controller.dart:640:7)
#45     _StreamController.add (dart:async/stream_controller.dart:586:5)
#46     _HttpParser._headersEnd (dart:_http/http_parser.dart:386:17)
#47     _HttpParser._doParse (dart:_http/http_parser.dart:701:15)
#48     _HttpParser._parse (dart:_http/http_parser.dart:318:7)
#49     _HttpParser._onData (dart:_http/http_parser.dart:810:5)
#50     _rootRunUnary (dart:async/zone.dart:1132:38)
#51     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#52     _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
#53     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#54     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#55     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:764:19)
#56     _StreamController._add (dart:async/stream_controller.dart:640:7)
#57     _StreamController.add (dart:async/stream_controller.dart:586:5)
#58     _Socket._onData (dart:io-patch/socket_patch.dart:1829:41)
#59     _rootRunUnary (dart:async/zone.dart:1136:13)
#60     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#61     _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
#62     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#63     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#64     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:764:19)
#65     _StreamController._add (dart:async/stream_controller.dart:640:7)
#66     _StreamController.add (dart:async/stream_controller.dart:586:5)
#67     new _RawSocket.<anonymous closure> (dart:io-patch/socket_patch.dart:1377:33)
#68     _NativeSocket.issueReadEvent.issue (dart:io-patch/socket_patch.dart:897:14)
#69     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#70     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#71     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:116:13)
#72     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:173:5)
```

**Comment by keyonghan** [comment]
One possible [workaround](https://stackoverflow.com/questions/44373051/google-datastore-1500-byte-property-limit-for-embedded-entities) is to disable index for that property.

**Comment by keyonghan** [comment]
Problem seems to be solved. Closing the issue for now.
