### ISSUE TITLE
Mystery test failure that doesn't manifest on the bots

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#4639]
@abarth and I have both seen this when running tests locally:
```
01:06 +448: /usr/local/google/home/ianh/dev/flutter/packages/flutter/test/animation/animation_controller_test.dart: Can fling to upper and lower bounds
══╡ EXCEPTION CAUGHT BY SCHEDULER LIBRARY ╞═════════════════════════════════════════════════════════
The following assertion was thrown during a scheduler callback:
'package:flutter/src/animation/animation_controller.dart': Failed assertion: line 278 pos 12:
'timeInSeconds >= 0.0' is not true.

When the exception was thrown, this was the stack:
#0      _AssertionError._throwNew (dart:core-patch/errors_patch.dart:27)
#1      _AssertionError._checkAssertion (dart:core-patch/errors_patch.dart:34)
#2      _InterpolationSimulation.x (package:flutter/src/animation/animation_controller.dart:278:12)
#3      AnimationController._tick (package:flutter/src/animation/animation_controller.dart:247:26)
#4      Ticker._tick (package:flutter/src/scheduler/ticker.dart:77:12)
#5      BindingBase&SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:428:15)
#6      BindingBase&SchedulerBinding._invokeTransientFrameCallbacks.<anonymous closure> (package:flutter/src/scheduler/binding.dart:411:9)
#7      _HashVMBase&MapMixin&&_LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:345)
#8      BindingBase&SchedulerBinding._invokeTransientFrameCallbacks (package:flutter/src/scheduler/binding.dart:409:15)
#9      BindingBase&SchedulerBinding.handleBeginFrame (package:flutter/src/scheduler/binding.dart:385:5)
#10     main.<anonymous closure> (///usr/local/google/home/ianh/dev/flutter/packages/flutter/test/animation/animation_controller_test.dart:140:29)
#11     Declarer.test.<anonymous closure>.<<anonymous closure>_async_body>.<anonymous closure>.<<anonymous closure>_async_body> (package:test/src/backend/declarer.dart:88:19)
#23     Declarer._runSetUps.<_runSetUps_async_body> (package:test/src/backend/declarer.dart:167:3)
(elided 47 frames from package dart:async, package dart:async-patch, and package stack_trace)


This exception was thrown in the context of a scheduler callback. When the scheduler callback was
_registered_ (as opposed to when the exception was thrown), this was the stack:
#0      _FrameCallbackEntry._FrameCallbackEntry.<anonymous closure> (package:flutter/src/scheduler/binding.dart:65:28)
#1      _AssertionError._checkAssertion (dart:core-patch/errors_patch.dart:31)
#2      _FrameCallbackEntry._FrameCallbackEntry (package:flutter/src/scheduler/binding.dart:47:12)
#3      BindingBase&SchedulerBinding.addFrameCallback (package:flutter/src/scheduler/binding.dart:239:53)
#4      BindingBase&SchedulerBinding.scheduleFrameCallback (package:flutter/src/scheduler/binding.dart:208:12)
#5      Ticker._scheduleTick (package:flutter/src/scheduler/ticker.dart:87:46)
#6      Ticker.start (package:flutter/src/scheduler/ticker.dart:42:5)
#7      AnimationController._startSimulation (package:flutter/src/animation/animation_controller.dart:217:35)
#8      AnimationController.animateTo (package:flutter/src/animation/animation_controller.dart:182:12)
#9      AnimationController.forward (package:flutter/src/animation/animation_controller.dart:154:12)
#10     main.<anonymous closure> (///usr/local/google/home/ianh/dev/flutter/packages/flutter/test/animation/animation_controller_test.dart:127:16)
#11     Declarer.test.<anonymous closure>.<<anonymous closure>_async_body>.<anonymous closure>.<<anonymous closure>_async_body> (package:test/src/backend/declarer.dart:88:19)
#23     Declarer._runSetUps.<_runSetUps_async_body> (package:test/src/backend/declarer.dart:167:3)
(elided 47 frames from package dart:async, package dart:async-patch, and package stack_trace)

════════════════════════════════════════════════════════════════════════════════════════════════════
```

**Comment by Hixie** [comment]
Closing this now. I haven't seen it in a while.
