### ISSUE TITLE
[tool_crash] NoSuchMethodError: The getter 'httpUri' was called on null.Receiver: nullTried calling: httpUri

### ISSUE THREAD

**Issue by pese-git** [flutter/flutter#46574]
## Command
  ```
  flutter --no-color run --machine --track-widget-creation --device-id=web-server --start-paused lib/main.dart
  ```

  ## Steps to Reproduce
  1. ...
  2. ...
  3. ...

  ## Logs
  NoSuchMethodError: NoSuchMethodError: The getter 'httpUri' was called on null.
Receiver: null
Tried calling: httpUri
  ```
  #0      Object.noSuchMethod (dart:core-patch/object_patch.dart:53:5)
#1      AppDomain.launch.<anonymous closure> (package:flutter_tools/src/commands/daemon.dart:522:26)
#2      _rootRunUnary (dart:async/zone.dart:1134:38)
#3      _CustomZone.runUnary (dart:async/zone.dart:1031:19)
#4      _FutureListener.handleValue (dart:async/future_impl.dart:140:18)
#5      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:682:45)
#6      Future._propagateToListeners (dart:async/future_impl.dart:711:32)
#7      Future._completeWithValue (dart:async/future_impl.dart:526:5)
#8      Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:556:7)
#9      _rootRun (dart:async/zone.dart:1126:13)
#10     _CustomZone.run (dart:async/zone.dart:1023:19)
#11     _CustomZone.runGuarded (dart:async/zone.dart:925:7)
#12     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:965:23)
#13     _microtaskLoop (dart:async/schedule_microtask.dart:43:21)
#14     _startMicrotaskLoop (dart:async/schedule_microtask.dart:52:5)
#15     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
#16     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:175:5)
  ```
  ```
  [✓] Flutter (Channel dev, v1.13.0, on Linux, locale ru_BY.UTF-8)
    • Flutter version 1.13.0 at /home/sergey/SDK/flutter
    • Framework revision 09126abb22 (5 days ago), 2019-12-03 17:43:00 -0800
    • Engine revision 6179380243
    • Dart version 2.7.0 (build 2.7.0-dev.2.1 a4d799c402)

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /home/sergey/Android/Sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /home/sergey/IDE/android-studio-3.6/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✗] Chrome - develop for the web (Cannot find chrome executable at google-chrome)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.

[✓] Android Studio (version 3.5)
    • Android Studio at /home/sergey/IDE/android-studio
    • Flutter plugin version 40.2.2
    • Dart plugin version 191.8423
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] Android Studio (version 3.6)
    • Android Studio at /home/sergey/IDE/android-studio-3.6
    • Flutter plugin version 42.0.2
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)

[✓] IntelliJ IDEA Community Edition (version 2019.2)
    • IntelliJ at /home/sergey/IDE/idea-IC-183.5912.21
    • Flutter plugin version 39.0.5
    • Dart plugin version 192.6603.23

[✓] Connected device (1 available)
    • Web Server • web-server • web-javascript • Flutter Tools

! Doctor found issues in 1 category.

  ```

  ## Flutter Application Metadata
  **Version**: 1.0.0+1
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null

**Comment by iapicca** [comment]
Hi @pese-git 
Could you please provide you `flutter run --verbose`?
Also given the error
`NoSuchMethodError: The getter 'httpUri' was called on null.Receiver: null`
could you provide a minimal code sample_
Thank you

**Comment by Mravuri96** [comment]
@pese-git  A temporary fix is to run this command
 ``` flutter config --no-enable-web-incremental-compiler;```

**Comment by jonahwilliams** [comment]
@iapicca this is not necessary

**Comment by pese-git** [comment]
> Hi @pese-git
> Could you please provide you `flutter run --verbose`?
> Also given the error
> `NoSuchMethodError: The getter 'httpUri' was called on null.Receiver: null`
> could you provide a minimal code sample_
> Thank you

If I run command "flutter run --verbose" then my web app working

**Comment by pese-git** [comment]
> @pese-git A temporary fix is to run this command
> ` flutter config --no-enable-web-incremental-compiler;`

Thanks it helped me
