### ISSUE TITLE
Exception caught by gesture: A ticker was started twice.

### ISSUE THREAD

**Issue by Den163** [flutter/flutter#46588]
I have a screen with a nested scroll view, sliver headers and PageView body with ListView inside. And I use an AnimatedCrossFade widget to create smooth animation between placeholder list and data list (which comes from the StreamBuilder). When I try to change page and scrolling it up or down i catch `Exception caught by gesture: A ticker was started twice` error . The problem is appear only when I'm using AnimatedCrossFade. If i remove it - there is no exception
So, my code: 
``` dart
import 'dart:collection';

import 'package:edaux_temp/blocs/items_bloc.dart';
import 'package:edaux_temp/models/main_catalog_models.dart';
import 'package:edaux_temp/utils/rx_controllers/rx_controllers.dart';
import 'package:edaux_temp/widgets/categories_sliver.dart';
import 'package:edaux_temp/widgets/item_view.dart';
import 'package:flutter/material.dart';

class MainCatalog extends StatefulWidget {
  final ItemsBloc itemsBloc;

  const MainCatalog({Key key, @required this.itemsBloc}) : super(key: key);

  @override
  _MainCatalogState createState() => _MainCatalogState();
}

class _MainCatalogState extends State<MainCatalog>
    with TickerProviderStateMixin {
  RxTabController _tabController;
  final _pageController = PageController();
  final _scrollController = new ScrollController();

  @override
  void initState() {
    _init();
    super.initState();
  }

  void _init() async {
    widget.itemsBloc.fetchCategories();

    final categories =
        await widget.itemsBloc.categories.where((c) => c != null).first;
    widget.itemsBloc.fetchCategoryItems(categories[0].id);
    _tabController = RxTabController(
        tabController: TabController(vsync: this, length: categories.length));
  }

  @override
  void dispose() {
    _tabController.dispose();
    _pageController.dispose();
    _scrollController.dispose();
    

    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return StreamBuilder<List<CategoryModel>>(
      stream: widget.itemsBloc.categories,
      builder: (context, snapshot) {
        final categories = snapshot.data;
        if (categories == null)
          return Center(child: CircularProgressIndicator());

        return Scaffold(
          drawer: Drawer(),
          body: NestedScrollView(
            controller: _scrollController,
            headerSliverBuilder: (_, __) => <Widget>[
              SliverAppBar(
                elevation: 0,
                pinned: true,
                actions: <Widget>[
                  IconButton(
                    icon: Icon(Icons.search),
                    onPressed: () {},
                  ),
                ],
                title: Text('Eda.Go'),
              ),
              CategoriesSliver(
                categories: categories,
                pageController: _pageController,
                tabController: _tabController,
              ),
            ],
            body: _pageView(categories),
          ),
        );
      },
    );
  }

  Widget _pageView(List<CategoryModel> categories) {
    final loadingList = ListView.builder(
      padding: EdgeInsets.all(0),
      shrinkWrap: true,
      itemCount: 3,
      itemBuilder: (_, __) => LoadingItemView()
    );

    return PageView.builder(
      itemCount: categories.length,
      controller: _pageController,
      onPageChanged: (page) {
        _tabController.index = page;
        widget.itemsBloc.fetchCategoryItems(page);
      },
      itemBuilder: (context, i) =>
          GestureDetector(
            behavior: HitTestBehavior.translucent,
        child: StreamBuilder<UnmodifiableListView<CategoryItemModel>>(
        stream: widget.itemsBloc.items,
        builder: (context, snapshot) {
          

            return AnimatedCrossFade(
              crossFadeState: snapshot.data == null
                  ? CrossFadeState.showFirst
                  : CrossFadeState.showSecond,
              duration: Duration(seconds: 1),
              firstChild: loadingList,
              secondChild: snapshot.data == null
                  ? loadingList
                  : ListView.builder(
                      padding: EdgeInsets.all(0),
                      shrinkWrap: true,
                      itemCount: snapshot.data.length,
                      itemBuilder: (context, i) => DataItemView(),
                    ),
            );
        },
      ),
          ),
    );
  }
}

```

Stacktrace: 
``` 
Restarted application in 1 438ms.
Reloaded 2 of 733 libraries in 516ms.

[38;5;248m════════ Exception caught by gesture ═══════════════════════════════════════════[39;49m
[38;5;244mThe following assertion was thrown while handling a gesture:[39;49m
A ticker was started twice.

[38;5;244mA ticker that is already active cannot be started again without first stopping it.[39;49m
[38;5;244mThe affected ticker was: _WidgetTicker(created by _GlowingOverscrollIndicatorState#a722c(lifecycle state: created, tickers: tracking 3 tickers))[39;49m
[38;5;244mThe stack trace when the _WidgetTicker was actually created was:[39;49m
[38;5;244m#0      new Ticker.<anonymous closure>[39;49m
[38;5;244m#1      new Ticker[39;49m
[38;5;244m#2      new _WidgetTicker[39;49m
[38;5;244m#3      TickerProviderStateMixin.createTicker[39;49m
[38;5;244m#4      new _GlowController[39;49m
[38;5;244m#5      _GlowingOverscrollIndicatorState.initState[39;49m
[38;5;244m#6      StatefulElement._firstBuild[39;49m
[38;5;244m#7      ComponentElement.mount[39;49m
[38;5;244m#8      Element.inflateWidget[39;49m
[38;5;244m#9      Element.updateChild[39;49m
[38;5;244m#10     ComponentElement.performRebuild[39;49m
[38;5;244m#11     Element.rebuild[39;49m
[38;5;244m#12     ComponentElement._firstBuild[39;49m
[38;5;244m#13     StatefulElement._firstBuild[39;49m
[38;5;244m#14     ComponentElement.mount[39;49m
[38;5;244m#15     Element.inflateWidget[39;49m
[38;5;244m#16     Element.updateChild[39;49m
[38;5;244m#17     ComponentElement.performRebuild[39;49m
[38;5;244m#18     Element.rebuild[39;49m
[38;5;244m#19     ComponentElement._firstBuild[39;49m
[38;5;244m#20     ComponentElement.mount[39;49m
[38;5;244m#21     Element.inflateWidget[39;49m
[38;5;244m#22     Element.updateChild[39;49m
[38;5;244m#23     ComponentElement.performRebuild[39;49m
[38;5;244m#24     Element.rebuild[39;49m
[38;5;244m#25     ComponentElement._firstBuild[39;49m
[38;5;244m#26     ComponentElement.mount[39;49m
[38;5;244m#27     Element.inflateWidget[39;49m
[38;5;244m#28     Element.updateChild[39;49m
[38;5;244m#29     SingleChildRenderObjectElement.mount[39;49m
[38;5;244m#30     Element.inflateWidget[39;49m
[38;5;244m#31     Element.updateChild[39;49m
[38;5;244m#32     SingleChildRenderObjectElement.mount[39;49m
[38;5;244m#33     Element.inflateWidget[39;49m
[38;5;244m#34     Element.updateChild[39;49m
[38;5;244m#35     ComponentElement.performRebuild[39;49m
[38;5;244m#36     Element.rebuild[39;49m
[38;5;244m#37     ComponentElement._firstBuild[39;49m
[38;5;244m#38     ComponentElement.mount[39;49m
[38;5;244m#39     Element.inflateWidget[39;49m
[38;5;244m#40     Element.updateChild[39;49m
[38;5;244m#41     ComponentElement.performRebuild[39;49m
[38;5;244m#42     Element.rebuild[39;49m
[38;5;244m#43     ComponentElement._firstBuild[39;49m
[38;5;244m#44     ComponentElement.mount[39;49m
[38;5;244m#45     ParentDataElement.mount[39;49m
[38;5;244m#46     Element.inflateWidget[39;49m
[38;5;244m#47     MultiChildRenderObjectElement.mount[39;49m
[38;5;244m#48     Element.inflateWidget[39;49m
[38;5;244m#49     Element.updateChild[39;49m
[38;5;244m#50     SingleChildRenderObjectElement.mount[39;49m
[38;5;244m#51     Element.inflateWidget[39;49m
[38;5;244m#52     Element.updateChild[39;49m
[38;5;244m#53     SingleChildRenderObjectElement.mount[39;49m
[38;5;244m#54     Element.inflateWidget[39;49m
[38;5;244m#55     Element.updateChild[39;49m
[38;5;244m#56     ComponentElement.performRebuild[39;49m
[38;5;244m#57     Element.rebuild[39;49m
[38;5;244m#58     ComponentElement._firstBuild[39;49m
[38;5;244m#59     StatefulElement._firstBuild[39;49m
[38;5;244m#60     ComponentElement.mount[39;49m
[38;5;244m#61     Element.inflateWidget[39;49m
[38;5;244m#62     Element.updateChild[39;49m
[38;5;244m#63     ComponentElement.performRebuild[39;49m
[38;5;244m#64     Element.rebuild[39;49m
[38;5;244m#65     ComponentElement._firstBuild[39;49m
[38;5;244m#66     StatefulElement._firstBuild[39;49m
[38;5;244m#67     ComponentElement.mount[39;49m
[38;5;244m#68     Element.inflateWidget[39;49m
[38;5;244m#69     Element.updateChild[39;49m
[38;5;244m#70     SingleChildRenderObjectElement.mount[39;49m
[38;5;244m#71     Element.inflateWidget[39;49m
[38;5;244m#72     Element.updateChild[39;49m
[38;5;244m#73     ComponentElement.performRebuild[39;49m
[38;5;244m#74     Element.rebuild[39;49m
[38;5;244m#75     ComponentElement._firstBuild[39;49m
[38;5;244m#76     ComponentElement.mount[39;49m
[38;5;244m#77     Element.inflateWidget[39;49m
[38;5;244m#78     Element.updateChild[39;49m
[38;5;244m#79     SingleChildRenderObjectElement.mount[39;49m
[38;5;244m#80     Element.inflateWidget[39;49m
[38;5;244m#81     Element.updateChild[39;49m
[38;5;244m#82     ComponentElement.performRebuild[39;49m
[38;5;244m#83     Element.rebuild[39;49m
[38;5;244m#84     ComponentElement._firstBuild[39;49m
[38;5;244m#85     StatefulElement._firstBuild[39;49m
[38;5;244m#86     ComponentElement.mount[39;49m
[38;5;244m#87     Element.inflateWidget[39;49m
[38;5;244m#88     Element.updateChild[39;49m
[38;5;244m#89     ComponentElement.performRebuild[39;49m
[38;5;244m#90     Element.rebuild[39;49m
[38;5;244m#91     ComponentElement._firstBuild[39;49m
[38;5;244m#92     ComponentElement.mount[39;49m
[38;5;244m#93     Element.inflateWidget[39;49m
[38;5;244m#94     Element.updateChild[39;49m
[38;5;244m#95     SingleChildRenderObjectElement.mount[39;49m
[38;5;244m#96     Element.inflateWidget[39;49m
[38;5;244m#97     Element.updateChild[39;49m
[38;5;244m#98     SingleChildRenderObjectElement.mount[39;49m
[38;5;244m#99     Element.inflateWidget[39;49m
[38;5;244m#100    Element.updateChild[39;49m
[38;5;244m#101    ComponentElement.performRebuild[39;49m
[38;5;244m#102    Element.rebuild[39;49m
[38;5;244m#103    ComponentElement._firstBuild[39;49m
[38;5;244m#104    ComponentElement.mount[39;49m
[38;5;244m#105    Element.inflateWidget[39;49m
[38;5;244m#106    Element.updateChild[39;49m
[38;5;244m#107    ComponentElement.performRebuild[39;49m
[38;5;244m#108    Element.rebuild[39;49m
[38;5;244m#109    ComponentElement._firstBuild[39;49m
[38;5;244m#110    ComponentElement.mount[39;49m
[38;5;244m#111    ParentDataElement.mount[39;49m
[38;5;244m#112    Element.inflateWidget[39;49m
[38;5;244m#113    Element.updateChild[39;49m
[38;5;244m#114    ComponentElement.performRebuild[39;49m
[38;5;244m#115    Element.rebuild[39;49m
[38;5;244m#116    ComponentElement._firstBuild[39;49m
[38;5;244m#117    StatefulElement._firstBuild[39;49m
[38;5;244m#118    ComponentElement.mount[39;49m
[38;5;244m#119    Element.inflateWidget[39;49m
[38;5;244m#120    Element.updateChild[39;49m
[38;5;244m#121    ComponentElement.performRebuild[39;49m
[38;5;244m#122    Element.rebuild[39;49m
[38;5;244m#123    ComponentElement._firstBuild[39;49m
[38;5;244m#124    ComponentElement.mount[39;49m
[38;5;244m#125    Element.inflateWidget[39;49m
[38;5;244m#126    Element.updateChild[39;49m
[38;5;244m#127    SliverMultiBoxAdaptorElement.updateChild[39;49m
[38;5;244m#128    SliverMultiBoxAdaptorElement.createChild.<anonymous closure>[39;49m
[38;5;244m#129    BuildOwner.buildScope[39;49m
[38;5;244m#130    SliverMultiBoxAdaptorElement.createChild[39;49m
[38;5;244m#131    RenderSliverMultiBoxAdaptor._createOrObtainChild.<anonymous closure>[39;49m
[38;5;244m#132    RenderObject.invokeLayoutCallback.<anonymous closure>[39;49m
[38;5;244m#133    PipelineOwner._enableMutationsToDirtySubtrees[39;49m
[38;5;244m#134    RenderObject.invokeLayoutCallback[39;49m
[38;5;244m#135    RenderSliverMultiBoxAdaptor._createOrObtainChild[39;49m
[38;5;244m#136    RenderSliverMultiBoxAdaptor.insertAndLayoutChild[39;49m
[38;5;244m#137    RenderSliverFixedExtentBoxAdaptor.performLayout[39;49m
[38;5;244m#138    RenderObject.layout[39;49m
[38;5;244m#139    RenderViewportBase.layoutChildSequence[39;49m
[38;5;244m#140    RenderViewport._attemptLayout[39;49m
[38;5;244m#141    RenderViewport.performLayout[39;49m
[38;5;244m#142    RenderObject._layoutWithoutResize[39;49m
[38;5;244m#143    PipelineOwner.flushLayout[39;49m
[38;5;244m#144    RendererBinding.drawFrame[39;49m
[38;5;244m#145    WidgetsBinding.drawFrame[39;49m
[38;5;244m#146    RendererBinding._handlePersistentFrameCallback[39;49m
[38;5;244m#147    SchedulerBinding._invokeFrameCallback[39;49m
[38;5;244m#148    SchedulerBinding.handleDrawFrame[39;49m
[38;5;244m#149    SchedulerBinding._handleDrawFrame[39;49m
[38;5;244m#153    _invoke  (dart:ui/hooks.dart:249:10)[39;49m
[38;5;244m#154    _drawFrame  (dart:ui/hooks.dart:207:3)[39;49m
[38;5;244m(elided 3 frames from package dart:async)[39;49m
[38;5;244m
[39;49m[38;5;244mWhen the exception was thrown, this was the stack[39;49m
[38;5;244m#0      Ticker.start.<anonymous closure>[39;49m
[38;5;244m#1      Ticker.start[39;49m
[38;5;244m#2      _GlowController.pull[39;49m
[38;5;244m#3      _GlowingOverscrollIndicatorState._handleScrollNotification[39;49m
[38;5;244m#4      NotificationListener._dispatch[39;49m
[38;5;244m...[39;49m
[38;5;244mHandler: "onUpdate"[39;49m
[38;5;244mRecognizer: VerticalDragGestureRecognizer#7ed40[39;49m
    [38;5;244mstart behavior: start[39;49m
[38;5;248m════════════════════════════════════════════════════════════════════════════════[39;49m
```
Flutter Doctor: 

``` flutter doctor 
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, v1.9.1+hotfix.6, on Microsoft Windows [Version 10.0.18362.476], locale ru-RU)

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.0-rc2)
[√] Android Studio (version 3.5)
[√] IntelliJ IDEA Community Edition (version 2019.2)
[√] VS Code, 64-bit edition (version 1.40.2)
[√] Connected device (1 available)

• No issues found!
```

**Comment by iapicca** [comment]
Hi @Den163 
as you presented it the issue you are describing 
seems to be specific to your code rather than Flutter itself,
could  you please post a minimal code sample or the steps to reproduce the problem,
that doesn't involve 3rd party packages like [RxDart](https://pub.dev/packages/rxdart) or [BLoC](https://pub.dev/packages/bloc)?
thank you

**Comment by Den163** [comment]
Hi @iapicca. Thanks for answering. Sorry, maybe it looks like I'm using some third party packages. But something I call Bloc - it's just a pattern - store of the streams with async data and not a package. So, I wrote code with reproducing the same problem in a 'pure' Flutter without any external sources. 

Imagine, you have a list of some data and a list of placeholders when the data is not ready. The second needs to transition to the first smoothly with opacity animation. In this case, I'm using AnimatedCrossFade. And the widget is causing of described issue, because if I remove it - the exception will not be thrown
``` dart
import 'dart:async';

import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';

void main(List<String> args) => runApp(App());

class App extends StatefulWidget {
  const App({Key key}) : super(key: key);

  @override
  _AppState createState() => _AppState();
}

class _AppState extends State<App> {
  static const itemHeight = 100.0;

  final _streamController = StreamController<String>.broadcast();
  Timer _timer;

  @override
  void initState() {
    // It's just to add some asynchronous data to the stream builder
    _timer = new Timer(
      Duration(seconds: 4),
      () => _streamController.add("Hello world")
    ); 

    super.initState();
  }

  @override
  void dispose() {
    _timer.cancel();
    _streamController.close();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        body: NestedScrollView(
          headerSliverBuilder: (context, _) => [
            SliverAppBar(
              title: Text('Title'),
            )
          ],
          body: _body(),
        ),
      ),
    );
  }

  Widget _body() {
    final loadingList = ListView.builder(
      shrinkWrap: true,
      itemCount: 5,
      itemBuilder: (context, i) => _loadingItem(),
    );

    return StreamBuilder<String>(
      stream: _streamController.stream,
      builder: (context, snapshot) {
        return AnimatedCrossFade(
          crossFadeState: snapshot.data == null 
            ? CrossFadeState.showFirst
            : CrossFadeState.showSecond,
          duration: Duration(seconds: 2),
          firstChild: loadingList,
          secondChild: _dataItemsList(snapshot)
        );         
      },
    );
  }

  ListView _dataItemsList(AsyncSnapshot<String> snapshot) {
    return ListView.builder(
      shrinkWrap: true,
      itemCount: 10,
      itemBuilder: (BuildContext context, int index) => 
        _dataItem(snapshot.data)
    );
  }

  Widget _loadingItem() {
    return Container(
      height: itemHeight,
      color: Colors.red,
      child: Center(child: Text('Loading'),),
    );
  }

  Widget _dataItem(String data) {
    return Container(
      height: itemHeight,
      color: Colors.blueAccent,
      child: Center(child: Text('Data: $data'),),
    );
  }
}
```

**Comment by iapicca** [comment]
Hi @Den163 
I tried running a simplified [version of your code](https://dartpad.dev/4a801b887a1ecf03caf65bb579b97ab8)
and I cannot reproduce the issue you are describing with the latest stable (and above)
are you still experiencing the crash?
Thank you
