### ISSUE TITLE
Atom: Flutter repo refactor/rename hangs

### ISSUE THREAD

**Issue by HansMuller** [flutter/flutter#4660]
I tried renaming the mainAxisSize parameter in packages/flutter/lib/src/widgets/basic.dart. Atom hung for 5+ minutes, and so I restarted.

On the second attempt Atom declared victory but 30 seconds later the analyzer crashed:

```
**Atom Version**: 1.5.3
**System**: Ubuntu 14.04
**Thrown From**: [dartlang](https://github.com/dart-atom/dartlang) package, v0.6.26


### Stack Trace

Uncaught [Analyzer RequestError method: analysis.setSubscriptions, code: SERVER_ERROR, message: AnalysisException: Cannot compute RESOLVED_UNIT for /builds/dev/flutter/packages/flutter/lib/src/widgets/basic.dart in /builds/dev/flutter/packages/flutter/lib/src/widgets/basic.dart
Caused by Infinite loop while performing task PropagateVariableTypesInUnitTask for /builds/dev/flutter/packages/flutter/lib/src/widgets/framework.dart in /builds/dev/flutter/packages/flutter/lib/src/widgets/framework.dart
  Dependency Cycle:
    Run PropagateVariableTypesInUnitTask on /builds/dev/flutter/packages/flutter/lib/src/widgets/framework.dart in /builds/dev/flutter/packages/flutter/lib/src/widgets/framework.dart
    Run PartiallyResolveUnitReferencesTask on /builds/dev/flutter/packages/flutter/lib/src/widgets/framework.dart in /builds/dev/flutter/packages/flutter/lib/src/widgets/framework.dart
    Run InferInstanceMembersInUnitTask on /builds/dev/flutter/packages/flutter/lib/src/widgets/basic.dart in /builds/dev/flutter/packages/flutter/lib/src/widgets/basic.dart
    Run ResolveInstanceFieldsInUnitTask on /builds/dev/flutter/packages/flutter/lib/src/widgets/basic.dart in /builds/dev/flutter/packages/flutter/lib/src/widgets/basic.dart
    Run InferStaticVariableTypesInUnitTask on /builds/dev/flutter/packages/flutter/lib/src/widgets/image.dart in /builds/dev/flutter/packages/flutter/lib/src/widgets/image.dart
    Run PartiallyResolveUnitReferencesTask on /builds/dev/flutter/packages/flutter/lib/src/widgets/image.dart in /builds/dev/flutter/packages/flutter/lib/src/widgets/image.dart
    Run PropagateVariableTypesInUnitTask on /builds/dev/flutter/packages/flutter/lib/src/widgets/image.dart in /builds/dev/flutter/packages/flutter/lib/src/widgets/image.dart
    Run InferStaticVariableTypesInUnitTask on /builds/dev/flutter/packages/flutter/lib/src/widgets/table.dart in /builds/dev/flutter/packages/flutter/lib/src/widgets/table.dart
    Run PartiallyResolveUnitReferencesTask on /builds/dev/flutter/packages/flutter/lib/src/widgets/table.dart in /builds/dev/flutter/packages/flutter/lib/src/widgets/table.dart
    Run PropagateVariableTypesInUnitTask on /builds/dev/flutter/packages/flutter/lib/src/widgets/table.dart in /builds/dev/flutter/packages/flutter/lib/src/widgets/table.dart
    Run InferStaticVariableTypesInUnitTask on /builds/dev/flutter/packages/flutter/lib/src/widgets/debug.dart in /builds/dev/flutter/packages/flutter/lib/src/widgets/debug.dart
    Run PartiallyResolveUnitReferencesTask on /builds/dev/flutter/packages/flutter/lib/src/widgets/debug.dart in /builds/dev/flutter/packages/flutter/lib/src/widgets/debug.dart
    Run PropagateVariableTypesInUnitTask on /builds/dev/flutter/packages/flutter/lib/src/widgets/debug.dart in /builds/dev/flutter/packages/flutter/lib/src/widgets/debug.dart
    Run InferStaticVariableTypesInUnitTask on /builds/dev/flutter/packages/flutter/lib/src/widgets/framework.dart in /builds/dev/flutter/packages/flutter/lib/src/widgets/framework.dart
    Run ResolveInstanceFieldsInUnitTask on /builds/dev/flutter/packages/flutter/lib/src/widgets/media_query.dart in /builds/dev/flutter/packages/flutter/lib/src/widgets/media_query.dart
    Run ResolveInstanceFieldsInUnitTask on /builds/dev/flutter/packages/flutter/lib/src/widgets/image.dart in /builds/dev/flutter/packages/flutter/lib/src/widgets/image.dart
    Run ResolveInstanceFieldsInUnitTask on /builds/dev/flutter/packages/flutter/lib/src/widgets/table.dart in /builds/dev/flutter/packages/flutter/lib/src/widgets/table.dart
    Run ResolveInstanceFieldsInUnitTask on /builds/dev/flutter/packages/flutter/lib/src/widgets/debug.dart in /builds/dev/flutter/packages/flutter/lib/src/widgets/debug.dart
    Run ResolveInstanceFieldsInUnitTask on /builds/dev/flutter/packages/flutter/lib/src/widgets/framework.dart in /builds/dev/flutter/packages/flutter/lib/src/widgets/framework.dart
  Cyclic Path:
    CREATED_RESOLVED_UNIT11 for /builds/dev/flutter/packages/flutter/lib/src/widgets/basic.dart in /builds/dev/flutter/packages/flutter/lib/src/widgets/basic.dart
    INFERABLE_STATIC_VARIABLES_IN_UNIT for /builds/dev/flutter/packages/flutter/lib/src/widgets/image.dart in /builds/dev/flutter/packages/flutter/lib/src/widgets/image.dart
    CREATED_RESOLVED_UNIT9 for /builds/dev/flutter/packages/flutter/lib/src/widgets/image.dart in /builds/dev/flutter/packages/flutter/lib/src/widgets/image.dart
    CREATED_RESOLVED_UNIT10 for /builds/dev/flutter/packages/flutter/lib/src/widgets/media_query.dart in /builds/dev/flutter/packages/flutter/lib/src/widgets/media_query.dart
    CREATED_RESOLVED_UNIT11 for /builds/dev/flutter/packages/flutter/lib/src/widgets/basic.dart in /builds/dev/flutter/packages/flutter/lib/src/widgets/basic.dart
    PROPAGABLE_VARIABLES_IN_UNIT for /builds/dev/flutter/packages/flutter/lib/src/widgets/framework.dart in /builds/dev/flutter/packages/flutter/lib/src/widgets/framework.dart

#0      AnalysisTask._safelyPerform (package:analyzer/task/model.dart:326)
#1      AnalysisTask.perform (package:analyzer/task/model.dart:229)
#2      AnalysisDriver.performWorkItem (package:analyzer/src/task/driver.dart:276)
#3      AnalysisDriver.performAnalysisTask (package:analyzer/src/task/driver.dart:251)
#4      AnalysisContextImpl.performAnalysisTask.<anonymous closure> (package:analyzer/src/context/context.dart:1176)
#5      _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:212)
#6      AnalysisContextImpl.performAnalysisTask (package:analyzer/src/context/context.dart:1174)
#7      PerformAnalysisOperation.perform (package:analysis_server/src/operation/operation_analysis.dart:371)
#8      AnalysisServer.performOperation (package:analysis_server/src/analysis_server.dart:876)
#9      Future.Future.<anonymous closure> (dart:async/future.dart:118)
#10     _rootRun (dart:async/zone.dart:946)
#11     _CustomZone.run (dart:async/zone.dart:826)
#12     _CustomZone.runGuarded (dart:async/zone.dart:724)
#13     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:751)
#14     _rootRun (dart:async/zone.dart:950)
#15     _CustomZone.run (dart:async/zone.dart:826)
#16     _CustomZone.runGuarded (dart:async/zone.dart:724)
#17     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:751)
#18     Timer._createTimer.<anonymous closure> (dart:async-patch/timer_patch.dart:16)
#19     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:385)
#20     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:414)
#21     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:148)

]

At /usr/local/google/home/hansmuller/.atom/packages/dartlang/web/entry.dart.js:27230

[Analyzer RequestError method: analysis.setSubscriptions, code: SERVER_ERROR, message: AnalysisException: Cannot compute RESOLVED_UNIT for /builds/dev/flutter/packages/flutter/lib/src/widgets/basic.dart in /builds/dev/flutter/packages/flutter/lib/src/widgets/basic.dart
Caused by Infinite loop while performing task PropagateVariableTypesInUnitTask for /builds/dev/flutter/packages/flutter/lib/src/widgets/framework.dart in /builds/dev/flutter/packages/flutter/lib/src/widgets/framework.dart
  Dependency Cycle:
    Run PropagateVariableTypesInUnitTask on /builds/dev/flutter/packages/flutter/lib/src/widgets/framework.dart in /builds/dev/flutter/packages/flutter/lib/src/widgets/framework.dart
    Run PartiallyResolveUnitReferencesTask on /builds/dev/flutter/packages/flutter/lib/src/widgets/framework.dart in /builds/dev/flutter/packages/flutter/lib/src/widgets/framework.dart
    Run InferInstanceMembersInUnitTask on /builds/dev/flutter/packages/flutter/lib/src/widgets/basic.dart in /builds/dev/flutter/packages/flutter/lib/src/widgets/basic.dart
    Run ResolveInstanceFieldsInUnitTask on /builds/dev/flutter/packages/flutter/lib/src/widgets/basic.dart in /builds/dev/flutter/packages/flutter/lib/src/widgets/basic.dart
    Run InferStaticVariableTypesInUnitTask on /builds/dev/flutter/packages/flutter/lib/src/widgets/image.dart in /builds/dev/flutter/packages/flutter/lib/src/widgets/image.dart
    Run PartiallyResolveUnitReferencesTask on /builds/dev/flutter/packages/flutter/lib/src/widgets/image.dart in /builds/dev/flutter/packages/flutter/lib/src/widgets/image.dart
    Run PropagateVariableTypesInUnitTask on /builds/dev/flutter/packages/flutter/lib/src/widgets/image.dart in /builds/dev/flutter/packages/flutter/lib/src/widgets/image.dart
    Run InferStaticVariableTypesInUnitTask on /builds/dev/flutter/packages/flutter/lib/src/widgets/table.dart in /builds/dev/flutter/packages/flutter/lib/src/widgets/table.dart
    Run PartiallyResolveUnitReferencesTask on /builds/dev/flutter/packages/flutter/lib/src/widgets/table.dart in /builds/dev/flutter/packages/flutter/lib/src/widgets/table.dart
    Run PropagateVariableTypesInUnitTask on /builds/dev/flutter/packages/flutter/lib/src/widgets/table.dart in /builds/dev/flutter/packages/flutter/lib/src/widgets/table.dart
    Run InferStaticVariableTypesInUnitTask on /builds/dev/flutter/packages/flutter/lib/src/widgets/debug.dart in /builds/dev/flutter/packages/flutter/lib/src/widgets/debug.dart
    Run PartiallyResolveUnitReferencesTask on /builds/dev/flutter/packages/flutter/lib/src/widgets/debug.dart in /builds/dev/flutter/packages/flutter/lib/src/widgets/debug.dart
    Run PropagateVariableTypesInUnitTask on /builds/dev/flutter/packages/flutter/lib/src/widgets/debug.dart in /builds/dev/flutter/packages/flutter/lib/src/widgets/debug.dart
    Run InferStaticVariableTypesInUnitTask on /builds/dev/flutter/packages/flutter/lib/src/widgets/framework.dart in /builds/dev/flutter/packages/flutter/lib/src/widgets/framework.dart
    Run ResolveInstanceFieldsInUnitTask on /builds/dev/flutter/packages/flutter/lib/src/widgets/media_query.dart in /builds/dev/flutter/packages/flutter/lib/src/widgets/media_query.dart
    Run ResolveInstanceFieldsInUnitTask on /builds/dev/flutter/packages/flutter/lib/src/widgets/image.dart in /builds/dev/flutter/packages/flutter/lib/src/widgets/image.dart
    Run ResolveInstanceFieldsInUnitTask on /builds/dev/flutter/packages/flutter/lib/src/widgets/table.dart in /builds/dev/flutter/packages/flutter/lib/src/widgets/table.dart
    Run ResolveInstanceFieldsInUnitTask on /builds/dev/flutter/packages/flutter/lib/src/widgets/debug.dart in /builds/dev/flutter/packages/flutter/lib/src/widgets/debug.dart
    Run ResolveInstanceFieldsInUnitTask on /builds/dev/flutter/packages/flutter/lib/src/widgets/framework.dart in /builds/dev/flutter/packages/flutter/lib/src/widgets/framework.dart
  Cyclic Path:
    CREATED_RESOLVED_UNIT11 for /builds/dev/flutter/packages/flutter/lib/src/widgets/basic.dart in /builds/dev/flutter/packages/flutter/lib/src/widgets/basic.dart
    INFERABLE_STATIC_VARIABLES_IN_UNIT for /builds/dev/flutter/packages/flutter/lib/src/widgets/image.dart in /builds/dev/flutter/packages/flutter/lib/src/widgets/image.dart
    CREATED_RESOLVED_UNIT9 for /builds/dev/flutter/packages/flutter/lib/src/widgets/image.dart in /builds/dev/flutter/packages/flutter/lib/src/widgets/image.dart
    CREATED_RESOLVED_UNIT10 for /builds/dev/flutter/packages/flutter/lib/src/widgets/media_query.dart in /builds/dev/flutter/packages/flutter/lib/src/widgets/media_query.dart
    CREATED_RESOLVED_UNIT11 for /builds/dev/flutter/packages/flutter/lib/src/widgets/basic.dart in /builds/dev/flutter/packages/flutter/lib/src/widgets/basic.dart
    PROPAGABLE_VARIABLES_IN_UNIT for /builds/dev/flutter/packages/flutter/lib/src/widgets/framework.dart in /builds/dev/flutter/packages/flutter/lib/src/widgets/framework.dart

#0      AnalysisTask._safelyPerform (package:analyzer/task/model.dart:326)
#1      AnalysisTask.perform (package:analyzer/task/model.dart:229)
#2      AnalysisDriver.performWorkItem (package:analyzer/src/task/driver.dart:276)
#3      AnalysisDriver.performAnalysisTask (package:analyzer/src/task/driver.dart:251)
#4      AnalysisContextImpl.performAnalysisTask.<anonymous closure> (package:analyzer/src/context/context.dart:1176)
#5      _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:212)
#6      AnalysisContextImpl.performAnalysisTask (package:analyzer/src/context/context.dart:1174)
#7      PerformAnalysisOperation.perform (package:analysis_server/src/operation/operation_analysis.dart:371)
#8      AnalysisServer.performOperation (package:analysis_server/src/analysis_server.dart:876)
#9      Future.Future.<anonymous closure> (dart:async/future.dart:118)
#10     _rootRun (dart:async/zone.dart:946)
#11     _CustomZone.run (dart:async/zone.dart:826)
#12     _CustomZone.runGuarded (dart:async/zone.dart:724)
#13     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:751)
#14     _rootRun (dart:async/zone.dart:950)
#15     _CustomZone.run (dart:async/zone.dart:826)
#16     _CustomZone.runGuarded (dart:async/zone.dart:724)
#17     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:751)
#18     Timer._createTimer.<anonymous closure> (dart:async-patch/timer_patch.dart:16)
#19     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:385)
#20     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:414)
#21     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:148)

]
    at [object Object].dart.wrapException (/usr/local/google/home/hansmuller/.atom/packages/dartlang/web/entry.dart.js:28304:17)
    at _rootHandleUncaughtError_closure.dart._rootHandleUncaughtError_closure.call$0 (/usr/local/google/home/hansmuller/.atom/packages/dartlang/web/entry.dart.js:48862:19)
    at [object Object].dart._microtaskLoop (/usr/local/google/home/hansmuller/.atom/packages/dartlang/web/entry.dart.js:46091:27)
    at [object Object].dart._startMicrotaskLoop (/usr/local/google/home/hansmuller/.atom/packages/dartlang/web/entry.dart.js:46097:11)
    at TimerImpl_internalCallback0.dart.TimerImpl_internalCallback0.call$0 (/usr/local/google/home/hansmuller/.atom/packages/dartlang/web/entry.dart.js:27610:23)
    at invokeClosure_closure.dart.invokeClosure_closure.call$0 (/usr/local/google/home/hansmuller/.atom/packages/dartlang/web/entry.dart.js:29489:29)
    at _IsolateContext.dart._IsolateContext.eval$1 (/usr/local/google/home/hansmuller/.atom/packages/dartlang/web/entry.dart.js:27221:25)
    at [object Object].dart._callInIsolate (/usr/local/google/home/hansmuller/.atom/packages/dartlang/web/entry.dart.js:26863:28)
    at dart.invokeClosure (/usr/local/google/home/hansmuller/.atom/packages/dartlang/web/entry.dart.js:28452:20)
    at /usr/local/google/home/hansmuller/.atom/packages/dartlang/web/entry.dart.js:28473:18
```

### Commands

```
     -1:52.5.0 dartlang:refactor-rename (atom-text-editor.editor.is-focused)
     -1:43.8.0 core:confirm (atom-text-editor.editor.mini.is-focused)
  2x -0:16.6.0 tree-view:reveal-active-file (atom-workspace.workspace.scrollbars-visible-always.theme-atom-light-syntax.theme-atom-light-ui)
```

### Config

```json
{
  "core": {
    "autoHideMenuBar": true,
    "followSymlinks": false,
    "themes": [
      "atom-light-ui",
      "atom-light-syntax"
    ]
  },
  "dartlang": {
    "sdkLocation": "/builds/dev/flutter/bin/cache/dart-sdk",
    "showOutlineView": false
  }
}
```

### Installed Packages

```coffee
# User
atom-toolbar, v0.1.6
dartlang, v0.6.26
flutter, v0.2.3
linter, v1.11.11
synced-sidebar, v0.4.3

# Dev
No dev packages
```

**Comment by sethladd** [comment]
cc @brianwilkerson @devoncarew

**Comment by sethladd** [comment]
Going to close in favor of IntelliJ plugin work.

Sorry you ran into this, and thanks for the feedback.
