### ISSUE TITLE
Undefined symbols for architecture armv7 - Failed to build iOS app

### ISSUE THREAD

**Issue by niravt07** [flutter/flutter#46610]
```bash
Xcode's output:
↳
    Undefined symbols for architecture armv7:
      "_OBJC_CLASS_$_FlutterStandardMessageCodec", referenced from:
          objc-class-ref in FlutterWebView.o
      "_OBJC_CLASS_$_FlutterError", referenced from:
          objc-class-ref in FLTWKNavigationDelegate.o
          objc-class-ref in FlutterWebView.o
      "_FlutterMethodNotImplemented", referenced from:
          -[FLTCookieManager handleMethodCall:result:] in FLTCookieManager.o
          ___83-[FLTWKNavigationDelegate webView:decidePolicyForNavigationAction:decisionHandler:]_block_invoke in FLTWKNavigationDelegate.o
          -[FLTWebViewController onMethodCall:result:] in FlutterWebView.o
      "_OBJC_CLASS_$_FlutterMethodChannel", referenced from:
          objc-class-ref in FLTCookieManager.o
          objc-class-ref in FlutterWebView.o
    ld: symbol(s) not found for architecture armv7
    clang: error: linker command failed with exit code 1 (use -v to see invocation)
    note: Using new build system
    note: Planning build
    note: Constructing build description
```

Flutter doctor -v
```bash
[✓] Flutter (Channel master, v1.13.1-pre.59, on Mac OS X 10.15 19A602, locale en-IN)
    • Flutter version 1.13.1-pre.59 at /Users/nirav/Public/flutter
    • Framework revision e58dc16d7b (3 days ago), 2019-12-06 18:21:52 -0800
    • Engine revision e7b69ced2e
    • Dart version 2.7.0 (build 2.7.0-dev.2.1 a9c77229c2)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/nirav/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.2, Build version 11B44
    • CocoaPods version 1.8.4

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 39.0.3
    • Dart plugin version 191.8423
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] IntelliJ IDEA Community Edition (version 2019.2.4)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 41.0.4
    • Dart plugin version 192.7402

[✓] Connected device (1 available)
    • iPhone 11 • 78905D80-8B3C-4D86-B692-0930F48E6858 • ios • com.apple.CoreSimulator.SimRuntime.iOS-13-2 (simulator)

• No issues found!
```

Highly appreciate your help and support. Thank You.

**Comment by jmagman** [comment]
How are you trying to archive the build?  Can we get your reproduction steps?

Note that Flutter does not support building against the simulator in Release mode.

**Comment by niravt07** [comment]
By running "flutter build ios" as well as Archive option from Xcode.
Both are giving the same error

**Comment by jmagman** [comment]
Are you building against the simulator?  Both `flutter build ios` and Archiving from Xcode would do so in Release, which doesn't work in the simulator.

**Comment by niravt07** [comment]
I am building it for the App Store. Please check below steps

Xcode's output:
↳
    Undefined symbols for architecture armv7:
      "_OBJC_CLASS_$_FlutterStandardMessageCodec", referenced from:
          objc-class-ref in FlutterWebView.o
      "_OBJC_CLASS_$_FlutterError", referenced from:
          objc-class-ref in FLTWKNavigationDelegate.o
          objc-class-ref in FlutterWebView.o
      "_FlutterMethodNotImplemented", referenced from:
          -[FLTCookieManager handleMethodCall:result:] in FLTCookieManager.o
          ___83-[FLTWKNavigationDelegate webView:decidePolicyForNavigationAction:decisionHandler:]_block_invoke in FLTWKNavigationDelegate.o
          -[FLTWebViewController onMethodCall:result:] in FlutterWebView.o
      "_OBJC_CLASS_$_FlutterMethodChannel", referenced from:
          objc-class-ref in FLTCookieManager.o
          objc-class-ref in FlutterWebView.o
    ld: symbol(s) not found for architecture armv7
    clang: error: linker command failed with exit code 1 (use -v to see invocation)
    note: Using new build system
    note: Planning build
    note: Constructing build description

Encountered error while building for device.

**Comment by warriorCoder** [comment]
I had the exact problem with my project since upgrading to flutter 1.12.13.hotfix-5 and was able to get a successful build AND archive. I used the terminal command in vscode after following these instructions to create the build.
From.. https://github.com/flutter/flutter/issues/23556#issuecomment-433817284
- Delete the `ios/` folder
- Run `flutter create .`
- Merge back in any specific settings you had made to the plist or other ios specific files.

One thing I didn't do was merge back in my pod file, I just let the pods get recreated.

**Comment by babaosoftware** [comment]
> I had the exact problem with my project since upgrading to flutter 1.12.13.hotfix-5 and was able to get a successful build AND archive. I used the terminal command in vscode after following these instructions to create the build.
> From.. [#23556 (comment)](https://github.com/flutter/flutter/issues/23556#issuecomment-433817284)
> 
> * Delete the `ios/` folder
> * Run `flutter create .`
> * Merge back in any specific settings you had made to the plist or other ios specific files.
> 
> One thing I didn't do was merge back in my pod file, I just let the pods get recreated.

This saved me a lot of time. Thanks

**Comment by jmagman** [comment]
That linker error means it wasn't finding the Flutter.framework.  Duplicating to https://github.com/flutter/flutter/issues/37850 and friends.

The workaround is to let the tool re-copy the framework by running:
```
rm -rf ios/Flutter/Flutter.framework
```

Ideally `flutter clean` would do this for you.  See https://github.com/flutter/flutter/issues/12631.

**Comment by deveshgarg-max** [comment]
Hey still I am getting the same error any solution?

**Comment by jmagman** [comment]
@deveshgarg-max Please file a new issue and completely fill out the template.  Include a `-v` verbose log of it reproducing.

**Comment by xmany** [comment]
Log:

```
               ld: symbol(s) not found for architecture armv7
               clang: error: linker command failed with exit code 1 (use -v to see invocation)
           
           
[ +206 ms] "flutter ios" took 11,331ms.
[  +18 ms] Encountered error while building for device.
[   +2 ms] 
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
           #1      _BuildIOSSubCommand.runCommand (package:flutter_tools/src/commands/build_ios.dart:256:7)
           <asynchronous suspension>
           #2      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:1157:12)
           <asynchronous suspension>
           #3      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1009:27)
           <asynchronous suspension>
           #4      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #5      AppContext.run (package:flutter_tools/src/base/context.dart:149:12)
           <asynchronous suspension>
           #6      CommandRunner.runCommand (package:args/command_runner.dart:197:13)
           <asynchronous suspension>
           #7      FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:278:9)
           <asynchronous suspension>
           #8      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #9      AppContext.run (package:flutter_tools/src/base/context.dart:149:12)
           <asynchronous suspension>
           #10     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:234:5)
           <asynchronous suspension>
           #11     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:64:9)
           <asynchronous suspension>
           #12     run.<anonymous closure> (package:flutter_tools/runner.dart:62:12)
           <asynchronous suspension>
           #13     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #14     AppContext.run (package:flutter_tools/src/base/context.dart:149:12)
           <asynchronous suspension>
           #15     runInContext (package:flutter_tools/src/context_runner.dart:73:10)
           <asynchronous suspension>
           #16     main (package:flutter_tools/executable.dart:90:3)
           <asynchronous suspension>
```

flutter doctor:

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.0.2, on macOS 11.2 20D64 darwin-arm, locale en-AU)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[✓] Xcode - develop for iOS and macOS
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.1)
[✓] VS Code (version 1.54.3)
[✓] Connected device (2 available)

• No issues found!
```
