### ISSUE TITLE
'(targetState flutter: == null) == (targetEvent is PointerAddedEvent)': is not true.

### ISSUE THREAD

**Issue by ThinkDigitalSoftware** [flutter/flutter#46646]
## Steps to Reproduce

The error happens immediately upon running

link to project: https://github.com/ThinkDigitalSoftware/multiple_navigators

**Target Platform:** macOS
**Target OS version/browser:** Catalina
**Devices: Macbook Pro**

## Logs

```
flutter: ══╡ EXCEPTION CAUGHT BY GESTURE LIBRARY ╞═══════════════════════════════════════════════════════════
flutter: The following assertion was thrown while routing a pointer event:
flutter: 'package:flutter/src/gestures/mouse_tracking.dart': Failed assertion: line 388 pos 14: '(targetState
flutter: == null) == (targetEvent is PointerAddedEvent)': is not true.
flutter: 
flutter: Either the assertion indicates an error in the framework itself, or we should provide substantially
flutter: more information in this error message to help you determine and fix the underlying cause.
flutter: In either case, please report this assertion by filing a bug on GitHub:
flutter:   https://github.com/flutter/flutter/issues/new?template=BUG.md
flutter: 
flutter: When the exception was thrown, this was the stack:
flutter: #2      MouseTracker._updateDevices (package:flutter/src/gestures/mouse_tracking.dart:388:14)
flutter: #3      MouseTracker._handleEvent (package:flutter/src/gestures/mouse_tracking.dart:292:5)
flutter: #4      PointerRouter._dispatch (package:flutter/src/gestures/pointer_router.dart:76:12)
flutter: #5      PointerRouter._dispatchEventToRoutes.<anonymous closure> (package:flutter/src/gestures/pointer_router.dart:117:9)
flutter: #6      _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:379:8)
flutter: #7      PointerRouter._dispatchEventToRoutes (package:flutter/src/gestures/pointer_router.dart:115:18)
flutter: #8      PointerRouter.route (package:flutter/src/gestures/pointer_router.dart:107:5)
flutter: #9      GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:180:23)
flutter: #10     GestureBinding._handlePointerEvent (package:flutter/src/gestures/binding.dart:156:7)
flutter: #11     GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:102:7)
flutter: #12     GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:86:7)
flutter: #16     _invoke1 (dart:ui/hooks.dart:273:10)
flutter: #17     _dispatchPointerDataPacket (dart:ui/hooks.dart:182:5)
flutter: (elided 5 frames from class _AssertionError and package dart:async)
flutter: 
flutter: Event:
flutter:   PointerHoverEvent#346f1(position: Offset(406.3, 122.2), delta: Offset(0.0, -0.5), timeStamp:
flutter:   85:48:38.337944, pointer: 0, kind: mouse, down: false, pressure: 0.0, pressureMin: 0.0,
flutter:   pressureMax: 0.0)
flutter: ════════════════════════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by gesture library ═══════════════════════════════════════════════════════
The following assertion was thrown while routing a pointer event:
'package:flutter/src/gestures/mouse_tracking.dart': Failed assertion: line 388 pos 14: '(targetState == null) == (targetEvent is PointerAddedEvent)': is not true.


```

```
```

```
[✓] Flutter (Channel master, v1.13.1-pre.58, on Mac OS X 10.15.2 19C46a, locale en-US)
    • Flutter version 1.13.1-pre.58 at /Users/thinkdigital/development/flutter
    • Framework revision 3d1e796be4 (3 days ago), 2019-12-06 18:31:33 -0500
    • Engine revision e7b69ced2e
    • Dart version 2.7.0 (build 2.7.0-dev.2.1 a9c77229c2)

```

**Comment by jonahwilliams** [comment]
FYI @dkwingsmt

**Comment by dkwingsmt** [comment]
This should have been fixed by https://github.com/flutter/flutter/pull/46285, which was merged this morning. Can you see if it still happens in the latest master?

**Comment by ThinkDigitalSoftware** [comment]
I'll check. I haven't updated to the latest master yet

**Comment by ThinkDigitalSoftware** [comment]
Yes, it's gone now, thanks!
