### ISSUE TITLE
shared_preferences ^0.5.4+9 causing errors during pub get

### ISSUE THREAD

**Issue by 2ZeroSix** [flutter/flutter#46663]
## Steps to Reproduce
Last shared_preferences update require Flutter SDK 1.10.0 or greater. This causing errors during pub get. ^0.5.4+8 works fine.
1. `flutter channel stable`
2. `flutter upgrade` 
3. set shared_preferences version to ^0.5.4+9
4. `flutter pub get`
```
The current Flutter SDK version is 1.9.1+hotfix.6.



Because app_name depends on shared_preferences >=0.5.4+9 which requires Flutter SDK version >=1.10.0 <2.0.0, version solving failed.
pub get failed (1)
```

**Comment by 2ZeroSix** [comment]
same with camera ^0.5.7+2

**Comment by iapicca** [comment]
Hi @2ZeroSix 
can you please provide your updated  `flutter doctor -v`
and your `flutter run --verbose`?
Thank you

**Comment by 2ZeroSix** [comment]
`flutter doctor -v`
```
[✓] Flutter (Channel stable, v1.9.1+hotfix.6, on Linux, locale en_US.UTF-8)
    • Flutter version 1.9.1+hotfix.6 at /home/dzs/flutter
    • Framework revision 68587a0916 (3 months ago), 2019-09-13 19:46:58 -0700
    • Engine revision b863200c37
    • Dart version 2.5.0

 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /home/dzs/Android/Sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 28.0.3
    • Java binary at: /home/dzs/.local/share/JetBrains/Toolbox/apps/AndroidStudio/ch-0/191.6010548/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Android Studio (version 3.5)
    • Android Studio at /home/dzs/.local/share/JetBrains/Toolbox/apps/AndroidStudio/ch-0/191.6010548
    • Flutter plugin version 42.0.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] Android Studio (version 3.3)
    • Android Studio at /home/dzs/.local/share/JetBrains/Toolbox/apps/AndroidStudio/ch-0/182.5314842
    • Flutter plugin version 33.4.1
    • Dart plugin version 182.5215
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)

[✓] Connected device (2 available)
    • WAS LX1             • PMF4C17429005536 • android-arm64 • Android 8.0.0 (API 26)
    • AOSP on IA Emulator • emulator-5554    • android-x86   • Android 9 (API 28) (emulator)

• No issues found!
```
`flutter run --verbose`
```
[  +34 ms] executing: [/home/user/flutter/] git log -n 1 --pretty=format:%H
[  +44 ms] Exit code 0 from: git log -n 1 --pretty=format:%H
[        ] 68587a0916366e9512a78df22c44163d041dd5f3
[        ] executing: [/home/user/flutter/] git describe --match v*.*.* --first-parent --long --tags
[  +13 ms] Exit code 0 from: git describe --match v*.*.* --first-parent --long --tags
[        ] v1.9.1+hotfix.6-0-g68587a091
[  +14 ms] executing: [/home/user/flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[  +10 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/stable
[        ] executing: [/home/user/flutter/] git ls-remote --get-url origin
[   +8 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[  +61 ms] executing: [/home/user/flutter/] git rev-parse --abbrev-ref HEAD
[  +10 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] stable
[ +103 ms] executing: /home/user/Android/Sdk/platform-tools/adb devices -l
[  +13 ms] Exit code 0 from: /home/user/Android/Sdk/platform-tools/adb devices -l
[        ] List of devices attached
           PMF4C17429005536       device usb:1-5 product:WAS-LX1 model:WAS_LX1 device:HWWAS-H transport_id:4
           emulator-5554          device product:sdk_gphone_x86_arm model:AOSP_on_IA_Emulator device:generic_x86_arm transport_id:3
[  +35 ms] /home/user/Android/Sdk/platform-tools/adb -s emulator-5554 shell getprop
[  +84 ms] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +4 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[   +8 ms] Running "flutter pub get" in app_name...
[   +3 ms] Using /home/user/flutter/.pub-cache for the pub cache.
[   +1 ms] executing: [/home/user/Projects/vendor/tclub/app_name/] /home/user/flutter/bin/cache/dart-sdk/bin/pub --verbose get --no-precompile
[  +95 ms] FINE: Pub 2.5.0
[ +143 ms] MSG : Resolving dependencies...
[  +12 ms] SLVR: fact: app_name is 1.0.0+1
[   +4 ms] SLVR: derived: app_name
[  +21 ms] SLVR: fact: app_name depends on provider ^3.2.0
[        ] SLVR: fact: app_name depends on fluro ^1.5.1
[        ] SLVR: fact: app_name depends on cloud_firestore ^0.12.11
[        ] SLVR: fact: app_name depends on flutter_localizations any from sdk
[        ] SLVR: fact: app_name depends on firebase_crashlytics ^0.1.2+2
[        ] SLVR: fact: app_name depends on flutter_translate ^1.5.7
[        ] SLVR: fact: app_name depends on firebase_core ^0.4.2+1
[        ] SLVR: fact: app_name depends on rxdart ^0.22.6
[        ] SLVR: fact: app_name depends on firebase_analytics ^5.0.6
[        ] SLVR: fact: app_name depends on shared_preferences ^0.5.4+9
[        ] SLVR: fact: app_name depends on dio ^3.0.7
[        ] SLVR: fact: app_name depends on firebase_database ^3.1.0
[        ] SLVR: fact: app_name depends on flutter any from sdk
[        ] SLVR: fact: app_name depends on firebase_dynamic_links ^0.5.0+8
[        ] SLVR: fact: app_name depends on path ^1.6.4
[        ] SLVR: fact: app_name depends on camera ^0.5.7+1
[        ] SLVR: fact: app_name depends on keyboard_avoider ^0.1.2
[        ] SLVR: fact: app_name depends on cupertino_icons ^0.1.3
[        ] SLVR: fact: app_name depends on graphql ^2.1.0
[        ] SLVR: fact: app_name depends on flutter_cupertino_localizations ^1.0.1
[        ] SLVR: fact: app_name depends on permission_handler ^4.0.0
[        ] SLVR: fact: app_name depends on flutter_svg ^0.15.0
[        ] SLVR: fact: app_name depends on build_runner ^1.7.0
[        ] SLVR: fact: app_name depends on flutter_test any from sdk
[        ] SLVR: fact: app_name depends on flutter_translate_gen ^1.2.4
[        ] SLVR: fact: app_name depends on intl ^0.16.0
[        ] SLVR:   selecting app_name
[        ] SLVR:   derived: intl ^0.16.0
[        ] SLVR:   derived: flutter_translate_gen ^1.2.4
[        ] SLVR:   derived: flutter_test any from sdk
[        ] SLVR:   derived: build_runner ^1.7.0
[        ] SLVR:   derived: flutter_svg ^0.15.0
[        ] SLVR:   derived: permission_handler ^4.0.0
[        ] SLVR:   derived: flutter_cupertino_localizations ^1.0.1
[        ] SLVR:   derived: graphql ^2.1.0
[        ] SLVR:   derived: cupertino_icons ^0.1.3
[        ] SLVR:   derived: keyboard_avoider ^0.1.2
[        ] SLVR:   derived: camera ^0.5.7+1
[        ] SLVR:   derived: path ^1.6.4
[        ] SLVR:   derived: firebase_dynamic_links ^0.5.0+8
[        ] SLVR:   derived: flutter any from sdk
[        ] SLVR:   derived: firebase_database ^3.1.0
[        ] SLVR:   derived: dio ^3.0.7
[        ] SLVR:   derived: shared_preferences ^0.5.4+9
[        ] SLVR:   derived: firebase_analytics ^5.0.6
[        ] SLVR:   derived: rxdart ^0.22.6
[        ] SLVR:   derived: firebase_core ^0.4.2+1
[        ] SLVR:   derived: flutter_translate ^1.5.7
[        ] SLVR:   derived: firebase_crashlytics ^0.1.2+2
[        ] SLVR:   derived: flutter_localizations any from sdk
[        ] SLVR:   derived: cloud_firestore ^0.12.11
[        ] SLVR:   derived: fluro ^1.5.1
[        ] SLVR:   derived: provider ^3.2.0
[   +5 ms] IO  : Get versions from https://pub.dartlang.org/api/packages/shared_preferences.
[  +30 ms] IO  : HTTP GET https://pub.dartlang.org/api/packages/shared_preferences
[        ]     | Accept: application/vnd.pub.v2+json
[        ]     | X-Pub-OS: linux
[        ]     | X-Pub-Command: get
[        ]     | X-Pub-Session-ID: 70A4CA18-2A79-4EF0-9FC5-7EC2B4345117
[        ]     | X-Pub-Environment: flutter_cli:verify:run
[        ]     | X-Pub-Reason: direct
[        ]     | user-agent: Dart pub 2.5.0
[ +494 ms] IO  : HTTP response 200 OK for GET https://pub.dartlang.org/api/packages/shared_preferences
[        ]     | took 0:00:00.495811
[        ]     | transfer-encoding: chunked
[   +1 ms]     | date: Tue, 10 Dec 2019 12:52:37 GMT
[        ]     | content-encoding: gzip
[        ]     | vary: Accept-Encoding
[        ]     | strict-transport-security: max-age=31536000; preload
[        ]     | via: 1.1 google
[        ]     | content-type: application/json
[        ]     | x-frame-options: SAMEORIGIN
[        ]     | x-xss-protection: 1; mode=block
[        ]     | x-content-type-options: nosniff
[        ]     | server: dart:io with Shelf
[  +47 ms] SLVR:   fact: intl 0.16.0 depends on path >=0.9.0 <2.0.0
[        ] SLVR:     selecting intl 0.16.0
[   +6 ms] SLVR:     fact: flutter_translate_gen 1.2.4 depends on code_builder ^3.2.0
[        ] SLVR:     fact: flutter_translate_gen 1.2.4 depends on source_gen >=0.9.4 <1.0.0
[        ] SLVR:     fact: flutter_translate_gen 1.2.4 depends on build ^1.2.1
[        ] SLVR:     fact: flutter_translate_gen 1.2.4 depends on dart_utils ^1.0.2
[        ] SLVR:     fact: flutter_translate_gen 1.2.4 depends on dart_casing ^1.0.1
[        ] SLVR:     fact: flutter_translate_gen 1.2.4 depends on flutter_translate_annotations ^1.0.1
[        ] SLVR:     fact: flutter_translate_gen 1.2.4 depends on glob ^1.2.0
[        ] SLVR:     fact: flutter_translate_gen 1.2.4 depends on analyzer >=0.36.4 <1.0.0
[        ] SLVR:       selecting flutter_translate_gen 1.2.4
[        ] SLVR:       derived: analyzer >=0.36.4 <1.0.0
[        ] SLVR:       derived: glob ^1.2.0
[        ] SLVR:       derived: flutter_translate_annotations ^1.0.1
[        ] SLVR:       derived: dart_casing ^1.0.1
[        ] SLVR:       derived: dart_utils ^1.0.2
[        ] SLVR:       derived: build ^1.2.1
[        ] SLVR:       derived: source_gen >=0.9.4 <1.0.0
[        ] SLVR:       derived: code_builder ^3.2.0
[   +7 ms] SLVR:       fact: flutter_test 0.0.0 from sdk depends on quiver 2.0.5
[        ] SLVR:       fact: flutter_test 0.0.0 from sdk depends on async 2.3.0
[        ] SLVR:       fact: flutter_test 0.0.0 from sdk depends on collection 1.14.11
[        ] SLVR:       fact: flutter_test 0.0.0 from sdk depends on typed_data 1.1.6
[        ] SLVR:       fact: flutter_test 0.0.0 from sdk depends on meta 1.1.7
[        ] SLVR:       fact: flutter_test 0.0.0 from sdk depends on charcode 1.1.2
[        ] SLVR:       fact: flutter_test 0.0.0 from sdk depends on matcher 0.12.5
[        ] SLVR:       fact: flutter_test 0.0.0 from sdk depends on stack_trace 1.9.3
[        ] SLVR:       fact: flutter_test 0.0.0 from sdk depends on pedantic 1.8.0+1
[        ] SLVR:       fact: flutter_test 0.0.0 from sdk depends on term_glyph 1.1.0
[        ] SLVR:       fact: flutter_test 0.0.0 from sdk depends on stream_channel 2.0.0
[        ] SLVR:       fact: flutter_test 0.0.0 from sdk depends on path 1.6.4
[        ] SLVR:       fact: flutter_test 0.0.0 from sdk depends on flutter any from sdk
[        ] SLVR:       fact: flutter_test 0.0.0 from sdk depends on boolean_selector 1.0.5
[        ] SLVR:       fact: flutter_test 0.0.0 from sdk depends on test_api 0.2.5
[        ] SLVR:       fact: flutter_test 0.0.0 from sdk depends on source_span 1.5.5
[        ] SLVR:       fact: flutter_test 0.0.0 from sdk depends on vector_math 2.0.8
[        ] SLVR:       fact: flutter_test 0.0.0 from sdk depends on string_scanner 1.0.5
[        ] SLVR:         selecting flutter_test 0.0.0 from sdk
[        ] SLVR:         derived: string_scanner 1.0.5
[        ] SLVR:         derived: vector_math 2.0.8
[        ] SLVR:         derived: source_span 1.5.5
[        ] SLVR:         derived: test_api 0.2.5
[        ] SLVR:         derived: boolean_selector 1.0.5
[        ] SLVR:         derived: path 1.6.4
[        ] SLVR:         derived: stream_channel 2.0.0
[        ] SLVR:         derived: term_glyph 1.1.0
[        ] SLVR:         derived: pedantic 1.8.0+1
[        ] SLVR:         derived: stack_trace 1.9.3
[        ] SLVR:         derived: matcher 0.12.5
[        ] SLVR:         derived: charcode 1.1.2
[        ] SLVR:         derived: meta 1.1.7
[        ] SLVR:         derived: typed_data 1.1.6
[        ] SLVR:         derived: collection 1.14.11
[        ] SLVR:         derived: async 2.3.0
[        ] SLVR:         derived: quiver 2.0.5
[   +8 ms] SLVR:         fact: build_runner 1.7.1 depends on dart_style ^1.0.0
[        ] SLVR:         fact: build_runner 1.7.1 depends on async >=1.13.3 <3.0.0
[        ] SLVR:         fact: build_runner 1.7.1 depends on web_socket_channel ^1.0.9
[        ] SLVR:         fact: build_runner 1.7.1 depends on build_config >=0.4.1 <0.4.2
[        ] SLVR:         fact: build_runner 1.7.1 depends on meta ^1.1.0
[        ] SLVR:         fact: build_runner 1.7.1 depends on io ^0.3.0
[        ] SLVR:         fact: build_runner 1.7.1 depends on shelf_web_socket ^0.2.2+4
[        ] SLVR:         fact: build_runner 1.7.1 depends on build_runner_core ^4.0.0
[        ] SLVR:         fact: build_runner 1.7.1 depends on pedantic ^1.0.0
[        ] SLVR:         fact: build_runner 1.7.1 depends on shelf >=0.6.5 <0.8.0
[        ] SLVR:         fact: build_runner 1.7.1 depends on js ^0.6.1+1
[        ] SLVR:         fact: build_runner 1.7.1 depends on mime ^0.9.3+3
[        ] SLVR:         fact: build_runner 1.7.1 depends on code_builder >2.3.0 <4.0.0
[        ] SLVR:         fact: build_runner 1.7.1 depends on watcher ^0.9.7
[        ] SLVR:         fact: build_runner 1.7.1 depends on args ^1.4.0
[        ] SLVR:         fact: build_runner 1.7.1 depends on collection ^1.14.0
[        ] SLVR:         fact: build_runner 1.7.1 depends on build_daemon ^2.1.0
[        ] SLVR:         fact: build_runner 1.7.1 depends on crypto >=0.9.2 <3.0.0
[        ] SLVR:         fact: build_runner 1.7.1 depends on build_resolvers ^1.0.0
[        ] SLVR:         fact: build_runner 1.7.1 depends on pool ^1.0.0
[        ] SLVR:         fact: build_runner 1.7.1 depends on glob ^1.1.0
[        ] SLVR:         fact: build_runner 1.7.1 depends on pubspec_parse ^0.1.0
[        ] SLVR:         fact: build_runner 1.7.1 depends on stack_trace ^1.9.0
[        ] SLVR:         fact: build_runner 1.7.1 depends on pub_semver ^1.4.0
[        ] SLVR:         fact: build_runner 1.7.1 depends on path ^1.1.0
[        ] SLVR:         fact: build_runner 1.7.1 depends on build >=1.0.0 <1.3.0
[        ] SLVR:         fact: build_runner 1.7.1 depends on stream_transform ^0.0.9
[        ] SLVR:         fact: build_runner 1.7.1 depends on timing ^0.1.1
[        ] SLVR:         fact: build_runner 1.7.1 depends on graphs ^0.2.0
[        ] SLVR:         fact: build_runner 1.7.1 depends on logging ^0.11.2
[        ] SLVR:         fact: build_runner 1.7.1 depends on yaml ^2.1.0
[        ] SLVR:         fact: build_runner 1.7.1 depends on http_multi_server ^2.1.0
[        ] SLVR:           selecting build_runner 1.7.1
[        ] SLVR:           derived: http_multi_server ^2.1.0
[        ] SLVR:           derived: yaml ^2.1.0
[        ] SLVR:           derived: logging ^0.11.2
[        ] SLVR:           derived: graphs ^0.2.0
[        ] SLVR:           derived: timing ^0.1.1
[        ] SLVR:           derived: stream_transform ^0.0.9
[        ] SLVR:           derived: build >=1.0.0 <1.3.0
[        ] SLVR:           derived: pub_semver ^1.4.0
[        ] SLVR:           derived: pubspec_parse ^0.1.0
[        ] SLVR:           derived: pool ^1.0.0
[        ] SLVR:           derived: build_resolvers ^1.0.0
[        ] SLVR:           derived: crypto >=0.9.2 <3.0.0
[        ] SLVR:           derived: build_daemon ^2.1.0
[        ] SLVR:           derived: args ^1.4.0
[        ] SLVR:           derived: watcher ^0.9.7
[        ] SLVR:           derived: mime ^0.9.3+3
[        ] SLVR:           derived: js ^0.6.1+1
[        ] SLVR:           derived: shelf >=0.6.5 <0.8.0
[        ] SLVR:           derived: build_runner_core ^4.0.0
[        ] SLVR:           derived: shelf_web_socket ^0.2.2+4
[        ] SLVR:           derived: io ^0.3.0
[        ] SLVR:           derived: build_config >=0.4.1 <0.4.2
[        ] SLVR:           derived: web_socket_channel ^1.0.9
[        ] SLVR:           derived: dart_style ^1.0.0
[   +7 ms] SLVR:           fact: flutter_svg 0.15.0 depends on vector_math ^2.0.4
[        ] SLVR:           fact: flutter_svg 0.15.0 depends on xml ^3.3.1
[        ] SLVR:           fact: flutter_svg 0.15.0 depends on flutter any from sdk
[        ] SLVR:           fact: flutter_svg 0.15.0 depends on path_drawing ^0.4.1
[        ] SLVR:           fact: flutter_svg 0.15.0 depends on meta ^1.1.2
[        ] SLVR:             selecting flutter_svg 0.15.0
[        ] SLVR:             derived: path_drawing ^0.4.1
[        ] SLVR:             derived: xml ^3.3.1
[   +7 ms] SLVR:             fact: permission_handler 4.0.0 depends on flutter any from sdk
[        ] SLVR:             fact: permission_handler 4.0.0 depends on meta ^1.1.6
[        ] SLVR:               selecting permission_handler 4.0.0
[   +7 ms] SLVR:               fact: flutter_cupertino_localizations 1.0.1 depends on flutter_localizations any from sdk
[        ] SLVR:               fact: flutter_cupertino_localizations 1.0.1 depends on flutter any from sdk
[        ] SLVR:                 selecting flutter_cupertino_localizations 1.0.1
[   +7 ms] SLVR:                 fact: graphql 2.1.0 depends on websocket ^0.0.5
[        ] SLVR:                 fact: graphql 2.1.0 depends on path ^1.6.2
[        ] SLVR:                 fact: graphql 2.1.0 depends on uuid_enhanced ^3.0.2
[        ] SLVR:                 fact: graphql 2.1.0 depends on meta ^1.1.6
[        ] SLVR:                 fact: graphql 2.1.0 depends on rxdart ^0.22.0
[        ] SLVR:                 fact: graphql 2.1.0 depends on http_parser ^3.1.3
[        ] SLVR:                 fact: graphql 2.1.0 depends on graphql_parser ^1.1.3
[        ] SLVR:                 fact: graphql 2.1.0 depends on http ^0.12.0+2
[        ] SLVR:                 fact: graphql 2.1.0 depends on mime ^0.9.6+2
[        ] SLVR:                   selecting graphql 2.1.0
[        ] SLVR:                   derived: mime ^0.9.6+2
[        ] SLVR:                   derived: http ^0.12.0+2
[        ] SLVR:                   derived: graphql_parser ^1.1.3
[        ] SLVR:                   derived: http_parser ^3.1.3
[        ] SLVR:                   derived: uuid_enhanced ^3.0.2
[        ] SLVR:                   derived: websocket ^0.0.5
[   +5 ms] SLVR:                     selecting cupertino_icons 0.1.3
[   +8 ms] SLVR:                     fact: keyboard_avoider 0.1.2 depends on flutter any from sdk
[        ] SLVR:                       selecting keyboard_avoider 0.1.2
[   +7 ms] SLVR:                       fact: camera 0.5.7+1 depends on flutter any from sdk
[        ] SLVR:                         selecting camera 0.5.7+1
[   +6 ms] SLVR:                           selecting path 1.6.4
[   +7 ms] SLVR:                           fact: firebase_dynamic_links 0.5.0+8 depends on flutter any from sdk
[        ] SLVR:                             selecting firebase_dynamic_links 0.5.0+8
[   +7 ms] SLVR:                             fact: flutter 0.0.0 from sdk depends on sky_engine any from sdk
[        ] SLVR:                             fact: flutter 0.0.0 from sdk depends on vector_math 2.0.8
[        ] SLVR:                             fact: flutter 0.0.0 from sdk depends on collection 1.14.11
[        ] SLVR:                             fact: flutter 0.0.0 from sdk depends on typed_data 1.1.6
[        ] SLVR:                             fact: flutter 0.0.0 from sdk depends on meta 1.1.7
[        ] SLVR:                               selecting flutter 0.0.0 from sdk
[        ] SLVR:                               derived: sky_engine any from sdk
[   +6 ms] SLVR:                               fact: firebase_database 3.1.0 depends on flutter any from sdk
[        ] SLVR:                               fact: firebase_database 3.1.0 depends on firebase_core ^0.4.0
[        ] SLVR:                                 selecting firebase_database 3.1.0
[   +6 ms] SLVR:                                 fact: dio 3.0.7 depends on http_parser >=0.0.1 <4.0.0
[        ] SLVR:                                 fact: dio 3.0.7 depends on path ^1.6.4
[        ] SLVR:                                   selecting dio 3.0.7
[  +12 ms] SLVR:                                   fact: shared_preferences >=0.5.4+9 requires Flutter SDK version >=1.10.0 <2.0.0
[   +3 ms] SLVR:                                   conflict: shared_preferences >=0.5.4+9 requires Flutter SDK version >=1.10.0 <2.0.0
[   +2 ms] SLVR:                                   ! shared_preferences >=0.5.4+9 is satisfied by shared_preferences ^0.5.4+9
[        ] SLVR:                                   ! which is caused by "app_name depends on shared_preferences ^0.5.4+9"
[        ] SLVR:                                   ! thus: version solving failed
[   +1 ms] SLVR: Version solving took 0:00:00.786136 seconds.
[        ]     | Tried 1 solutions.
[   +1 ms] FINE: Resolving dependencies finished (0.797s).
[  +14 ms] ERR : The current Flutter SDK version is 1.9.1+hotfix.6.
[        ]     | 
[        ]     | Because app_name depends on shared_preferences >=0.5.4+9 which requires Flutter SDK version >=1.10.0 <2.0.0, version solving failed.
[        ] FINE: Exception type: SolveFailure
[  +17 ms] FINE: package:pub/src/solver/version_solver.dart 308:5   VersionSolver._resolveConflict
[        ]     | package:pub/src/solver/version_solver.dart 131:27  VersionSolver._propagate
[        ]     | package:pub/src/solver/version_solver.dart 96:9    VersionSolver.solve
[        ]     | ===== asynchronous gap ===========================
[        ]     | dart:async                                         Future.catchError
[        ]     | package:pub/src/utils.dart 109:52                  captureErrors.<fn>
[        ]     | package:stack_trace                                Chain.capture
[        ]     | package:pub/src/utils.dart 122:11                  captureErrors
[        ]     | package:pub/src/command_runner.dart 171:13         PubCommandRunner.runCommand
[  +25 ms] Running "flutter pub get" in app_name... (completed in 1.1s)
[   +1 ms] "flutter run" took 1,369ms.
pub get failed (1)

#0      throwToolExit (package:flutter_tools/src/base/common.dart:28:3)
#1      pub (package:flutter_tools/src/dart/pub.dart:174:5)
<asynchronous suspension>
#2      pubGet (package:flutter_tools/src/dart/pub.dart:106:13)
<asynchronous suspension>
#3      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:474:13)
<asynchronous suspension>
#4      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:407:33)
<asynchronous suspension>
#5      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:154:29)
<asynchronous suspension>
#6      _rootRun (dart:async/zone.dart:1124:13)
#7      _CustomZone.run (dart:async/zone.dart:1021:19)
#8      _runZoned (dart:async/zone.dart:1516:10)
#9      runZoned (dart:async/zone.dart:1463:12)
#10     AppContext.run (package:flutter_tools/src/base/context.dart:153:18)
<asynchronous suspension>
#11     FlutterCommand.run (package:flutter_tools/src/runner/flutter_command.dart:397:20)
#12     CommandRunner.runCommand (package:args/command_runner.dart:197:27)
<asynchronous suspension>
#13     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:402:21)
<asynchronous suspension>
#14     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:154:29)
<asynchronous suspension>
#15     _rootRun (dart:async/zone.dart:1124:13)
#16     _CustomZone.run (dart:async/zone.dart:1021:19)
#17     _runZoned (dart:async/zone.dart:1516:10)
#18     runZoned (dart:async/zone.dart:1463:12)
#19     AppContext.run (package:flutter_tools/src/base/context.dart:153:18)
<asynchronous suspension>
#20     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:356:19)
<asynchronous suspension>
#21     CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:112:25)
#22     new Future.sync (dart:async/future.dart:224:31)
#23     CommandRunner.run (package:args/command_runner.dart:112:14)
#24     FlutterCommandRunner.run (package:flutter_tools/src/runner/flutter_command_runner.dart:242:18)
#25     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:63:22)
<asynchronous suspension>
#26     _rootRun (dart:async/zone.dart:1124:13)
#27     _CustomZone.run (dart:async/zone.dart:1021:19)
#28     _runZoned (dart:async/zone.dart:1516:10)
#29     runZoned (dart:async/zone.dart:1500:12)
#30     run.<anonymous closure> (package:flutter_tools/runner.dart:61:18)
<asynchronous suspension>
#31     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:154:29)
<asynchronous suspension>
#32     _rootRun (dart:async/zone.dart:1124:13)
#33     _CustomZone.run (dart:async/zone.dart:1021:19)
#34     _runZoned (dart:async/zone.dart:1516:10)
#35     runZoned (dart:async/zone.dart:1463:12)
#36     AppContext.run (package:flutter_tools/src/base/context.dart:153:18)
<asynchronous suspension>
#37     runInContext (package:flutter_tools/src/context_runner.dart:59:24)
<asynchronous suspension>
#38     run (package:flutter_tools/runner.dart:50:10)
#39     main (package:flutter_tools/executable.dart:65:9)
<asynchronous suspension>
#40     main (file:///home/user/flutter/packages/flutter_tools/bin/flutter_tools.dart:8:3)
#41     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:303:32)
#42     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:12)


```

**Comment by jrmarkham** [comment]
And  ^0.4.6+1

**Comment by ejprok** [comment]
I'm getting the same issue with shared_preferences: ^0.5.4+9

**Comment by jrmarkham** [comment]
And in_app_purchase >=0.2.2+4

From a quick look it appears that the plugins were all updated today (12/10/2019).

**Comment by dhakadv06** [comment]
And for url_launcher(5.3.0) as well

**Comment by rakeshparveen5** [comment]
I am getting the same error when upgrading the versions of path_provider: ^1.5.1  & firebase_analytics: ^5.0.9

**Comment by imtoori** [comment]
Same error here ✋

**Comment by AntoniPD** [comment]
same here

**Comment by doitwithdk** [comment]
Same error:

`pub get failed (1)
exit code 1
[time_flutter] flutter packages get
Running "flutter pub get" in time_flutter...                    
The current Flutter SDK version is 1.9.1+hotfix.6.

Because app_name depends on shared_preferences >=0.5.4+9 which requires Flutter SDK version >=1.10.0 <2.0.0, version solving failed.`

**Comment by kiranbhagannavar** [comment]
Try installing shared_preferences: ^0.5.4. I solved the problem by degrading to this version.

**Comment by boyfox** [comment]
And also with shared_preferences: ^0.5.6 same issue

**Comment by boyfox** [comment]
also with firebase_messaging >=6.0.7 which requires Flutter SDK version >=1.10.0 <2.0.0, version solving failed.

**Comment by boyfox** [comment]
also with android_intent: ^0.3.4+8

**Comment by DomingoMG** [comment]
Same error here! :(

**Comment by kiranbhagannavar** [comment]
@boyfox I think upgrading your flutter will help in solving this problem

**Comment by zigang93** [comment]
Any Solution ?

**Comment by 2ZeroSix** [comment]
> Any Solution ?

solved in current stable release (I hope it was a preparation for flutter interact 1.12 announce)
run `flutter upgrade` to fix this

**Comment by Maxbee** [comment]
> ## Steps to Reproduce
> Last shared_preferences update require Flutter SDK 1.10.0 or greater. This causing errors during pub get. ^0.5.4+8 works fine.
> 
> 1. `flutter channel stable`
> 2. `flutter upgrade`
> 3. set shared_preferences version to ^0.5.4+9
> 4. `flutter pub get`
> 
> ```
> The current Flutter SDK version is 1.9.1+hotfix.6.
> 
> 
> 
> Because app_name depends on shared_preferences >=0.5.4+9 which requires Flutter SDK version >=1.10.0 <2.0.0, version solving failed.
> pub get failed (1)
> ```

super nice!
