### ISSUE TITLE
Bug Switch camera constantly and crash the app

### ISSUE THREAD

**Issue by VNAPNIC** [flutter/flutter#46749]
I switch the camera constantly and crash the app

**Log**

```bash
    java.lang.NullPointerException: Attempt to invoke virtual method 'android.view.Surface android.media.ImageReader.getSurface()' on a null object reference
        at io.flutter.plugins.camera.Camera.startPreview(Camera.java:424)
        at io.flutter.plugins.camera.Camera$2.onOpened(Camera.java:160)
        at android.hardware.camera2.impl.CameraDeviceImpl$1.run(CameraDeviceImpl.java:148)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:6981)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1445)

```
**code switch camera**

```dart
if (cameraController != null) {
      if (cameraController.value.isInitialized ||
          cameraController.value.isRecordingPaused ||
          cameraController.value.isRecordingVideo ||
          cameraController.value.isStreamingImages ||
          cameraController.value.isTakingPicture)
        await cameraController.dispose();
    }
    cameraController = CameraController(
      cameraDescription,
      ResolutionPreset.high,
      enableAudio: true,
    );
    // If the controller is updated then update the UI.
    cameraController.addListener(() {
      if (cameraController.value.hasError) {}
    });
    try {
      await cameraController.initialize();
    } on CameraException catch (e) {
      print(e);
    }
    setState(() {
      isCameraReady = true;
    });
```

**Comment by iapicca** [comment]
Hi @VNAPNIC 
can you please provide your updated  `flutter doctor -v`
and your `flutter run --verbose`?
Also the sample code you provide doesn't tell much,
maybe you are calling those `async `inside a `void`,
could you show a more detailed example?
Thank you

**Comment by VladyslavBondarenko** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.
Could everyone who still has this problem please file a new issue with the exact descriptions what happens, logs and the output of 'flutter doctor -v'  please.
All system setups can be slightly different so its always better to open new issues and reference related issues.
