### ISSUE TITLE
Dismissible widget not working in Cupertino application

### ISSUE THREAD

**Issue by FedericoMatera** [flutter/flutter#46766]
`Dismissible` widget with a setted `confirmDismiss` doesn't work on iOS/Cupertino app with `CupertinoTabScaffold`, the `onDismissed` function is not event called. 
If `confirmDismiss` is not provided,  the `onDismissed` function is called but the `Dismissible` item is not removed from the list.
In Android/Material app or in an iOS/CupertinoPageScaffold the exactly same code works fine.

Android widget stack:
```
MaterialApp
  StatefulWidget
    Scaffold
      StatefulWidget
        ListView
          Dismissible
```

iOS widgets stack:
```
CupertinoApp
  StatefulWidget
    CupertinoTabScaffold
      CupertinoPageScaffold
        StatefulWidget
          ListView
            Dismissible
```

Full example code
```dart
import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return CupertinoApp(
      title: 'Flutter Demo',
      home: MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key key, this.title}) : super(key: key);

  final String title;

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  List<String> list = ['aaa', 'bbb', 'ccc'];

  Future<bool> _onItemDismissed() async {
    return await showCupertinoDialog(
      context: context,
      builder: (context) => CupertinoAlertDialog(
        title: Text('Dismiss'),
        content: Text('Confirm?'),
        actions: [
          CupertinoButton(
            child: Text('Yes'),
            onPressed: () => Navigator.pop(context, true),
          ),
          CupertinoButton(
            child: Text('No'),
            onPressed: () => Navigator.pop(context, false),
          ),
        ],
      ),
    );
  }

  @override
  Widget build(BuildContext context) {
    return CupertinoTabScaffold(
      tabBuilder: (context, index) {
        return CupertinoPageScaffold(
          navigationBar: CupertinoNavigationBar(
            middle: Text('Title'),
          ),
          child: CupertinoPageScaffold(
            child: ListView.builder(
              itemCount: list.length,
              itemBuilder: (context, i) {
                return Dismissible(
                  key: UniqueKey(),
                  background: Container(color: Color.fromARGB(255, 255, 0, 0)),
                  onDismissed: (direction) => debugPrint('done'),
                  confirmDismiss: (direction) => _onItemDismissed(),
                  direction: DismissDirection.endToStart,
                  child: Padding(
                    padding: const EdgeInsets.all(32),
                    child: Text(list[i]),
                  ),
                );
              },
            ),
          ),
        );
      },
      tabBar: CupertinoTabBar(
        items: [
          BottomNavigationBarItem(
            title: Text('Button'),
            icon: Icon(CupertinoIcons.home),
          ),
          BottomNavigationBarItem(
            title: Text('Button'),
            icon: Icon(CupertinoIcons.home),
          ),
        ],
      ),
    );
  }
}

```

## Steps to reproduce
1. create a new application and paste the code above 
2. dismiss a Dismissible item

**Target Platform:**
iOS
**Target OS version/browser:**
13.1.2
**Devices:**
iPhone 6s plus

## Logs

```
flutter: The following NoSuchMethodError was thrown while notifying listeners for AnimationController:
flutter: The method 'dependOnInheritedWidgetOfExactType' was called on null.
flutter: Receiver: null
flutter: Tried calling: dependOnInheritedWidgetOfExactType<Directionality>()
flutter:
flutter: When the exception was thrown, this was the stack:
flutter: #0      Object.noSuchMethod (dart:core-patch/object_patch.dart:53:5)
flutter: #1      Directionality.of (package:flutter/src/widgets/basic.dart:110:43)
flutter: #2      _DismissibleState._extentToDirection (package:flutter/src/widgets/dismissible.dart:268:30)
flutter: #3      _DismissibleState._dismissDirection (package:flutter/src/widgets/dismissible.dart:280:45)
flutter: #4      _DismissibleState._handleResizeProgressChanged (package:flutter/src/widgets/dismissible.dart:498:44)
flutter: #5      AnimationLocalListenersMixin.notifyListeners (package:flutter/src/animation/listener_helpers.dart:124:19)
flutter: #6      AnimationController._tick (package:flutter/src/animation/animation_controller.dart:788:5)
flutter: #7      Ticker._tick (package:flutter/src/scheduler/ticker.dart:237:5)
flutter: #8      SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1102:15)
flutter: #9      SchedulerBinding.handleBeginFrame.<anonymous closure> (package:flutter/src/scheduler/binding.dart:1017:11)
flutter: #10     _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:379:8)
flutter: #11     SchedulerBinding.handleBeginFrame (package:flutter/src/scheduler/binding.dart:1015:17)
flutter: #12     SchedulerBinding._handleBeginFrame (package:flutter/src/scheduler/binding.dart:949:5)
flutter: #16     _invoke1 (dart:ui/hooks.dart:273:10)
flutter: #17     _beginFrame (dart:ui/hooks.dart:200:3)
flutter: (elided 3 frames from package dart:async)
flutter:
flutter: The AnimationController notifying listeners was:
flutter:   AnimationController#fd18d(⏭ 1.000; paused)
flutter: ════════════════════════════════════════════════════════════════════════════════════════════════════
```

```
flutter analyze:
No issues found! (ran in 3.7s)
```

```
flutter doctor -v
[✓] Flutter (Channel beta, v1.12.13+hotfix.5, on Mac OS X 10.15.1 19B88, locale it-IT)
    • Flutter version 1.12.13+hotfix.5 at /Users/federico/flutter
    • Framework revision 27321ebbad (7 hours ago), 2019-12-10 18:15:01 -0800
    • Engine revision 2994f7e1e6
    • Dart version 2.7.0

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.0)
    • Android SDK at /Users/federico/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.2.1, Build version 11B500
    • CocoaPods version 1.8.3

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 41.1.2
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] VS Code (version 1.40.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.6.0

[✓] Connected device (2 available)
    • Nexus 6        • 192.168.1.32:5555                        • android-arm • Android 7.1.1 (API 25)
    • iPhone 6s Plus • 93f04d2c0815e8d7143f04aaa0899242e0575255 • ios         • iOS 13.1.2
```

**Comment by justinmc** [comment]
There may be an error in your Dismissible code, so I want to make sure that your code is as you intend.  Maybe you just skipped this part for now, but `onDismiss` should remove the current item from `list`, and you should use a proper key, like this:

```dart
                return Dismissible(
                  key: ValueKey(list[i]), // A key that corresponds to this list item.
                  background: Container(color: Color.fromARGB(255, 255, 0, 0)),
                  onDismissed: (direction) {
                    // Remove this item from the list when dismissed.
                    setState(() {
                      list.remove(list[i]);
                    });
                    debugPrint('done');
                  },
                  confirmDismiss: (direction) => _onItemDismissed(),
                  direction: DismissDirection.endToStart,
                  child: Padding(
                    padding: const EdgeInsets.all(32),
                    child: Text(list[i]),
                  ),
                );
```

When you do this, does it work or do you still see a bug?

**Comment by FedericoMatera** [comment]
It works.
In MaterialApp stack there is no need to manually remove the item from the list, is this a desired behavior?

**Comment by justinmc** [comment]
I believe you need to manually remove the item when it is part of a list.  I don't think there should be a difference in this between Material and Cupertino, but in your code above it seems like it does have to manually remove the Dismissible.  The docs talk about this a little bit: https://master-api.flutter.dev/flutter/widgets/Dismissible-class.html

I'm going to close this, but let me know if you do see anything that we should make consistent here.
