### ISSUE TITLE
Error At installing package google_maps_flutter

### ISSUE THREAD

**Issue by zgramming** [flutter/flutter#46776]
I have some problem at installing package google_maps_flutter, after i run in my device i got this error :
```
* Error running Gradle:
ProcessException: Process "C:\Project Flutter\Udemy\great_place_app\android\gradlew.bat" exited abnormally:

> Configure project :app
WARNING: API 'variant.getMergeAssets()' is obsolete and has been replaced with 'variant.getMergeAssetsProvider()'.
It will be removed at the end of 2019.
For more information, see https://d.android.com/r/tools/task-configuration-avoidance.
To determine what is calling variant.getMergeAssets(), use -Pandroid.debug.obsoleteApi=true on the command line to display a stack trace.
WARNING: API 'variantOutput.getProcessResources()' is obsolete and has been replaced with 'variantOutput.getProcessResourcesProvider()'.
It will be removed at the end of 2019.
For more information, see https://d.android.com/r/tools/task-configuration-avoidance.
To determine what is calling variantOutput.getProcessResources(), use -Pandroid.debug.obsoleteApi=true on the command line to display a stack trace.

> Configure project :google_maps_flutter

Project evaluation failed including an error in afterEvaluate {}. Run with --stacktrace for details of the afterEvaluate {} error.

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':google_maps_flutter'.
> Could not resolve all artifacts for configuration ':google_maps_flutter:classpath'.
   > Could not download gradle.jar (com.android.tools.build:gradle:3.3.2)
      > Could not get resource 'https://dl.google.com/dl/android/maven2/com/android/tools/build/gradle/3.3.2/gradle-3.3.2.jar'.
         > Read timed out
   > Could not download builder.jar (com.android.tools.build:builder:3.3.2)
      > Could not get resource 'https://dl.google.com/dl/android/maven2/com/android/tools/build/builder/3.3.2/builder-3.3.2.jar'.
         > Read timed out
   > Could not download sdklib.jar (com.android.tools:sdklib:26.3.2)
      > Could not get resource 'https://dl.google.com/dl/android/maven2/com/android/tools/sdklib/26.3.2/sdklib-26.3.2.jar'.
         > Read timed out

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 2m 6s
  Command: C:\Project Flutter\Udemy\great_place_app\android\gradlew.bat app:properties
Please review your Gradle project setup in the android/ folder.

Exited (sigterm)
```
After i search same issue , i look similiar issue with me https://github.com/flutter/flutter/issues/26544, But not work .

### Flutter run doctor -v
```
PS C:\Project Flutter\Udemy\great_place_app> flutter doctor -v
[√] Flutter (Channel stable, v1.9.1+hotfix.6, on Microsoft Windows [Version 10.0.18362.476], locale en-US)
    • Flutter version 1.9.1+hotfix.6 at C:\flutter\flutter
    • Framework revision 68587a0916 (3 months ago), 2019-09-13 19:46:58 -0700
    • Engine revision b863200c37
    • Dart version 2.5.0
 
[√] Android toolchain - develop for Android devices (Android SDK version 29.0.0)
    • Android SDK at C:\Users\user\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.0
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)
    • All Android licenses accepted.

[√] Android Studio (version 3.5)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 39.0.3
    • Dart plugin version 191.8423
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)

[√] VS Code (version 1.40.2)
    • VS Code at C:\Users\user\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.7.0

[√] Connected device (1 available)
    • Redmi Note 4 • 1a96d23a9904 • android-arm64 • Android 7.0 (API 24)

• No issues found!
```
### Flutter run --verbose
```
PS C:\Project Flutter\Udemy\great_place_app> flutter run --verbose
[  +40 ms] executing: [C:\flutter\flutter\] git log -n 1 --pretty=format:%H
[  +97 ms] Exit code 0 from: git log -n 1 --pretty=format:%H
[   +7 ms] 68587a0916366e9512a78df22c44163d041dd5f3
[   +1 ms] executing: [C:\flutter\flutter\] git describe --match v*.*.* --first-parent --long --tags
[  +84 ms] Exit code 0 from: git describe --match v*.*.* --first-parent --long --tags
[  +12 ms] v1.9.1+hotfix.6-0-g68587a091
[  +11 ms] executing: [C:\flutter\flutter\] git rev-parse --abbrev-ref --symbolic @{u}
[ +116 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[  +29 ms] origin/stable
[        ] executing: [C:\flutter\flutter\] git ls-remote --get-url origin
[  +99 ms] Exit code 0 from: git ls-remote --get-url origin
[  +53 ms] https://github.com/flutter/flutter.git
[ +165 ms] executing: [C:\flutter\flutter\] git rev-parse --abbrev-ref HEAD
[  +56 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[  +32 ms] stable
[ +155 ms] executing: C:\Users\user\AppData\Local\Android\sdk\platform-tools\adb.exe devices -l
[  +37 ms] Exit code 0 from: C:\Users\user\AppData\Local\Android\sdk\platform-tools\adb.exe devices -l
[  +40 ms] List of devices attached
           1a96d23a9904           device product:mido model:Redmi_Note_4 device:mido transport_id:1
[  +19 ms] C:\Users\user\AppData\Local\Android\sdk\platform-tools\adb.exe -s 1a96d23a9904 shell getprop
[ +173 ms] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +6 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[  +45 ms] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[   +4 ms] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[  +51 ms] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[  +60 ms] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[   +4 ms] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[ +107 ms] Found plugin google_maps_flutter at C:\flutter\flutter\.pub-cache\hosted\pub.dartlang.org\google_maps_flutter-0.5.21+14\
[  +36 ms] Found plugin image_picker at C:\flutter\flutter\.pub-cache\hosted\pub.dartlang.org\image_picker-0.6.2+1\
[   +2 ms] Found plugin location at C:\flutter\flutter\.pub-cache\hosted\pub.dartlang.org\location-2.3.5\
[  +10 ms] Found plugin path_provider at C:\flutter\flutter\.pub-cache\hosted\pub.dartlang.org\path_provider-1.4.5\
[  +73 ms] Found plugin sqflite at C:\flutter\flutter\.pub-cache\hosted\pub.dartlang.org\sqflite-1.1.7+3\
[ +101 ms] Found plugin google_maps_flutter at C:\flutter\flutter\.pub-cache\hosted\pub.dartlang.org\google_maps_flutter-0.5.21+14\
[ +129 ms] Found plugin image_picker at C:\flutter\flutter\.pub-cache\hosted\pub.dartlang.org\image_picker-0.6.2+1\
[   +5 ms] Found plugin location at C:\flutter\flutter\.pub-cache\hosted\pub.dartlang.org\location-2.3.5\
[  +78 ms] Found plugin sqflite at C:\flutter\flutter\.pub-cache\hosted\pub.dartlang.org\sqflite-1.1.7+3\
[ +120 ms] ro.hardware = qcom
[ +133 ms] Launching lib\main.dart on Redmi Note 4 in debug mode...
[  +48 ms] Initializing gradle...
[  +74 ms] Using gradle from C:\Project Flutter\Udemy\great_place_app\android\gradlew.bat.
[ +303 ms] executing: C:\Project Flutter\Udemy\great_place_app\android\gradlew.bat -v
[ +997 ms]
                    ------------------------------------------------------------
                    Gradle 4.10.2
                    ------------------------------------------------------------

                    Build time:   2018-09-19 18:10:15 UTC
                    Revision:     b4d8d5d170bb4ba516e88d7fe5647e2323d791dd

                    Kotlin DSL:   1.0-rc-6
                    Kotlin:       1.2.61
                    Groovy:       2.4.15
                    Ant:          Apache Ant(TM) version 1.9.11 compiled on March 23 2018
                    JVM:          1.8.0_202-release (JetBrains s.r.o 25.202-b03)
                    OS:           Windows 10 10.0 amd64
[  +94 ms] Initializing gradle... (completed in 1.4s)
[  +43 ms] Resolving dependencies...
[  +47 ms] executing: [C:\Project Flutter\Udemy\great_place_app\android\] C:\Project Flutter\Udemy\great_place_app\android\gradlew.bat app:properties                                                                                                                                 properties
[+828562 ms] 
                      > Configure project :app
                      WARNING: API 'variant.getMergeAssets()' is obsolete and has been replaced with 'variant.getMergeAssetsProvider()'.   
                      It will be removed at the end of 2019.
                      For more information, see https://d.android.com/r/tools/task-configuration-avoidance.
                      To determine what is calling variant.getMergeAssets(), use -Pandroid.debug.obsoleteApi=true on the command line to   
                      display a stack trace.
                      WARNING: API 'variantOutput.getProcessResources()' is obsolete and has been replaced with
                      'variantOutput.getProcessResourcesProvider()'.
                      It will be removed at the end of 2019.
                      For more information, see https://d.android.com/r/tools/task-configuration-avoidance.
                      To determine what is calling variantOutput.getProcessResources(), use -Pandroid.debug.obsoleteApi=true on the command                      line to display a stack trace.

                      > Configure project :google_maps_flutter

                      Project evaluation failed including an error in afterEvaluate {}. Run with --stacktrace for details of the
                      afterEvaluate {} error.

                      FAILURE: Build failed with an exception.

                      * What went wrong:
                      A problem occurred configuring project ':google_maps_flutter'.
                      > Could not resolve all artifacts for configuration ':google_maps_flutter:classpath'.
                         > Could not download builder.jar (com.android.tools.build:builder:3.3.2)
                            > Could not get resource
                            'https://dl.google.com/dl/android/maven2/com/android/tools/build/builder/3.3.2/builder-3.3.2.jar'.
                               > Read timed out

                      * Try:
                      Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run   
                      with --scan to get full insights.

                      * Get more help at https://help.gradle.org

                      BUILD FAILED in 13m 48s
[  +16 ms] Resolving dependencies... (completed in 828.6s, longer than expected)
[   +4 ms] * Error running Gradle:
           ProcessException: Process "C:\Project Flutter\Udemy\great_place_app\android\gradlew.bat" exited abnormally:

           > Configure project :app
           WARNING: API 'variant.getMergeAssets()' is obsolete and has been replaced with 'variant.getMergeAssetsProvider()'.
           It will be removed at the end of 2019.
           For more information, see https://d.android.com/r/tools/task-configuration-avoidance.
           To determine what is calling variant.getMergeAssets(), use -Pandroid.debug.obsoleteApi=true on the command line to display a    
stack trace.
           WARNING: API 'variantOutput.getProcessResources()' is obsolete and has been replaced with
'variantOutput.getProcessResourcesProvider()'.
           It will be removed at the end of 2019.
           For more information, see https://d.android.com/r/tools/task-configuration-avoidance.
           To determine what is calling variantOutput.getProcessResources(), use -Pandroid.debug.obsoleteApi=true on the command line to   
display a
           stack trace.

           > Configure project :google_maps_flutter

           Project evaluation failed including an error in afterEvaluate {}. Run with --stacktrace for details of the afterEvaluate {}     
error.

           FAILURE: Build failed with an exception.

           * What went wrong:
           A problem occurred configuring project ':google_maps_flutter'.
           > Could not resolve all artifacts for configuration ':google_maps_flutter:classpath'.
              > Could not download builder.jar (com.android.tools.build:builder:3.3.2)
                 > Could not get resource
'https://dl.google.com/dl/android/maven2/com/android/tools/build/builder/3.3.2/builder-3.3.2.jar'.
                    > Read timed out

           * Try:
           Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan  
to get full
           insights.

           * Get more help at https://help.gradle.org

           BUILD FAILED in 13m 48s
             Command: C:\Project Flutter\Udemy\great_place_app\android\gradlew.bat app:properties

[ +110 ms] "flutter run" took 831,870ms.
Please review your Gradle project setup in the android/ folder.

#0      throwToolExit (package:flutter_tools/src/base/common.dart:28:3)
#1      _readGradleProject (package:flutter_tools/src/android/gradle.dart:233:7)
<asynchronous suspension>
#2      _gradleAppProject (package:flutter_tools/src/android/gradle.dart:112:37)
<asynchronous suspension>
#3      getGradleAppOut (package:flutter_tools/src/android/gradle.dart:106:29)
<asynchronous suspension>
#4      AndroidApk.fromAndroidProject (package:flutter_tools/src/application_package.dart:164:23)
<asynchronous suspension>
#5      ApplicationPackageFactory.getPackageForPlatform (package:flutter_tools/src/application_package.dart:46:32)
<asynchronous suspension>
#6      FlutterDevice.runHot (package:flutter_tools/src/resident_runner.dart:359:56)
<asynchronous suspension>
#7      HotRunner.run (package:flutter_tools/src/run_hot.dart:254:39)
<asynchronous suspension>
#8      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:472:37)
<asynchronous suspension>
#9      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:490:18)
#10     _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:71:64)
#11     _rootRunUnary (dart:async/zone.dart:1132:38)
#12     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#13     _FutureListener.handleValue (dart:async/future_impl.dart:137:18)
#14     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:678:45)
#15     Future._propagateToListeners (dart:async/future_impl.dart:707:32)
#16     Future._completeWithValue (dart:async/future_impl.dart:522:5)
#17     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:30:15)
#18     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:288:13)
#19     RunCommand.usageValues (package:flutter_tools/src/commands/run.dart)
#20     _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:71:64)
#21     _rootRunUnary (dart:async/zone.dart:1132:38)
#22     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#23     _FutureListener.handleValue (dart:async/future_impl.dart:137:18)
#24     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:678:45)
#25     Future._propagateToListeners (dart:async/future_impl.dart:707:32)
#26     Future._completeWithValue (dart:async/future_impl.dart:522:5)
#27     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:30:15)
#28     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:288:13)
#29     AndroidDevice.isLocalEmulator (package:flutter_tools/src/android/android_device.dart)
#30     _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:71:64)
#31     _rootRunUnary (dart:async/zone.dart:1132:38)
#32     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#33     _FutureListener.handleValue (dart:async/future_impl.dart:137:18)
#34     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:678:45)
#35     Future._propagateToListeners (dart:async/future_impl.dart:707:32)
#36     Future._completeWithValue (dart:async/future_impl.dart:522:5)
#37     Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:552:7)
#38     _rootRun (dart:async/zone.dart:1124:13)
#39     _CustomZone.run (dart:async/zone.dart:1021:19)
#40     _CustomZone.runGuarded (dart:async/zone.dart:923:7)
#41     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:963:23)
#42     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#43     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#44     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:116:13)
#45     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:173:5)
```

**Comment by iapicca** [comment]
Hi ... 
could you please run 
`
 flutter channel stable
`
`
 flutter upgrade
`
let me know if the issue persists
thank you

**Comment by zgramming** [comment]
After re-upgrade the flutter with `flutter upgrade --force` resolved my problem.

**Comment by iapicca** [comment]
Hi @zgramming 
I'm glad to hear that you solved the issue
thank you for letting me know
