### ISSUE TITLE
Not works `pub global run flutter_plugin_tools format --plugins video_player`

### ISSUE THREAD

**Issue by otopba** [flutter/flutter#46811]
```
pub global run flutter_plugin_tools format --plugins video_player
Formatting all .dart files...
Unchanged /Users/yuriy.dorofeev/it/terra/new/plugins/packages/video_player/video_player/test/video_player_test.dart
Unchanged /Users/yuriy.dorofeev/it/terra/new/plugins/packages/video_player/video_player/example/test_driver/video_player.dart
Unchanged /Users/yuriy.dorofeev/it/terra/new/plugins/packages/video_player/video_player/example/test_driver/video_player_e2e.dart
Unchanged /Users/yuriy.dorofeev/it/terra/new/plugins/packages/video_player/video_player/example/test_driver/video_player_test.dart
Unchanged /Users/yuriy.dorofeev/it/terra/new/plugins/packages/video_player/video_player/example/test_driver/video_player_e2e_test.dart
Unchanged /Users/yuriy.dorofeev/it/terra/new/plugins/packages/video_player/video_player/example/lib/main.dart
Unchanged /Users/yuriy.dorofeev/it/terra/new/plugins/packages/video_player/video_player/lib/video_player.dart
Unchanged /Users/yuriy.dorofeev/it/terra/new/plugins/packages/video_player/video_player_platform_interface/test/method_channel_video_player_test.dart
Unchanged /Users/yuriy.dorofeev/it/terra/new/plugins/packages/video_player/video_player_platform_interface/lib/video_player_platform_interface.dart
Unchanged /Users/yuriy.dorofeev/it/terra/new/plugins/packages/video_player/video_player_platform_interface/lib/method_channel_video_player.dart
Unchanged /Users/yuriy.dorofeev/it/terra/new/plugins/packages/video_player/video_player_web/test/video_player_web_test.dart
Unchanged /Users/yuriy.dorofeev/it/terra/new/plugins/packages/video_player/video_player_web/lib/video_player_web.dart
Formatting all .java files...
Formatting all .m and .h files...
Unhandled exception:
ProcessException: No such file or directory
  Command: clang-format -i --style=Google /Users/yuriy.dorofeev/it/terra/new/plugins/packages/video_player/video_player/example/ios/Runner/AppDelegate.h /Users/yuriy.dorofeev/it/terra/new/plugins/packages/video_player/video_player/example/ios/Runner/GeneratedPluginRegistrant.h /Users/yuriy.dorofeev/it/terra/new/plugins/packages/video_player/video_player/example/ios/Flutter/Flutter.framework/Headers/FlutterEngine.h /Users/yuriy.dorofeev/it/terra/new/plugins/packages/video_player/video_player/example/ios/Flutter/Flutter.framework/Headers/FlutterChannels.h /Users/yuriy.dorofeev/it/terra/new/plugins/packages/video_player/video_player/example/ios/Flutter/Flutter.framework/Headers/FlutterPlugin.h /Users/yuriy.dorofeev/it/terra/new/plugins/packages/video_player/video_player/example/ios/Flutter/Flutter.framework/Headers/FlutterAppDelegate.h /Users/yuriy.dorofeev/it/terra/new/plugins/packages/video_player/video_player/example/ios/Flutter/Flutter.framework/Headers/FlutterTexture.h /Users/yuriy.dorofeev/it/terra/new/plugins/packages/video_player/video_player/example/ios/Flutter/Flutter.framework/Headers/FlutterPlatformViews.h /Users/yuriy.dorofeev/it/terra/new/plugins/packages/video_player/video_player/example/ios/Flutter/Flutter.framework/Headers/FlutterHeadlessDartRunner.h /Users/yuriy.dorofeev/it/terra/new/plugins/packages/video_player/video_player/example/ios/Flutter/Flutter.framework/Headers/FlutterCodecs.h /Users/yuriy.dorofeev/it/terra/new/plugins/packages/video_player/video_player/example/ios/Flutter/Flutter.framework/Headers/Flutter.h /Users/yuriy.dorofeev/it/terra/new/plugins/packages/video_player/video_player/example/ios/Flutter/Flutter.framework/Headers/FlutterViewController.h /Users/yuriy.dorofeev/it/terra/new/plugins/packages/video_player/video_player/example/ios/Flutter/Flutter.framework/Headers/FlutterMacros.h /Users/yuriy.dorofeev/it/terra/new/plugins/packages/video_player/video_player/example/ios/Flutter/Flutter.framework/Headers/FlutterDartProject.h /Users/yuriy.dorofeev/it/terra/new/plugins/packages/video_player/video_player/example/ios/Flutter/Flutter.framework/Headers/FlutterPluginAppLifeCycleDelegate.h /Users/yuriy.dorofeev/it/terra/new/plugins/packages/video_player/video_player/example/ios/Flutter/Flutter.framework/Headers/FlutterBinaryMessenger.h /Users/yuriy.dorofeev/it/terra/new/plugins/packages/video_player/video_player/example/ios/Flutter/Flutter.framework/Headers/FlutterCallbackCache.h /Users/yuriy.dorofeev/it/terra/new/plugins/packages/video_player/video_player/example/ios/Pods/Target Support Files/video_player/video_player-umbrella.h /Users/yuriy.dorofeev/it/terra/new/plugins/packages/video_player/video_player/example/ios/Pods/Target Support Files/e2e/e2e-umbrella.h /Users/yuriy.dorofeev/it/terra/new/plugins/packages/video_player/video_player/ios/Classes/VideoPlayerPlugin.h /Users/yuriy.dorofeev/it/terra/new/plugins/packages/video_player/video_player/example/ios/Runner/main.m /Users/yuriy.dorofeev/it/terra/new/plugins/packages/video_player/video_player/example/ios/Runner/AppDelegate.m /Users/yuriy.dorofeev/it/terra/new/plugins/packages/video_player/video_player/example/ios/Runner/GeneratedPluginRegistrant.m /Users/yuriy.dorofeev/it/terra/new/plugins/packages/video_player/video_player/example/ios/Pods/Target Support Files/video_player/video_player-dummy.m /Users/yuriy.dorofeev/it/terra/new/plugins/packages/video_player/video_player/example/ios/Pods/Target Support Files/Pods-Runner/Pods-Runner-dummy.m /Users/yuriy.dorofeev/it/terra/new/plugins/packages/video_player/video_player/example/ios/Pods/Target Support Files/e2e/e2e-dummy.m /Users/yuriy.dorofeev/it/terra/new/plugins/packages/video_player/video_player/ios/Classes/VideoPlayerPlugin.m
#0      ProcessRunner.runAndStream (package:flutter_plugin_tools/src/common.dart:302:32)
<asynchronous suspension>
#1      FormatCommand._formatObjectiveC (package:flutter_plugin_tools/src/format_command.dart:97:27)
<asynchronous suspension>
#2      FormatCommand.run (package:flutter_plugin_tools/src/format_command.dart:47:11)
<asynchronous suspension>
#3      CommandRunner.runCommand (package:args/command_runner.dart:197:27)
#4      CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:112:25)
#5      new Future.sync (dart:async/future.dart:224:31)
#6      CommandRunner.run (package:args/command_runner.dart:112:14)
#7      main (package:flutter_plugin_tools/src/main.dart:57:17)
#8      _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:305:32)
#9      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:174:12)
```

**Comment by otopba** [comment]
Sorry. I just have to install `clang-format`
