### ISSUE TITLE
Weird app running even before it is actually installed.

### ISSUE THREAD

**Issue by pepsighan** [flutter/flutter#46849]
## Steps to Reproduce

After upgrading to `v1.12.13+hotfix.5` the build began to crash and the app not running saying I need to use `WidgetsFlutterBinding.ensureInitialized()`, which upon reading the docs could not understand why?

Still after fixing that issue, the build began throwing the following error and the app starts to run.

The weird thing is that the app even before running on the mobile started hitting the API server with our internal error `{error: unauthorized, status: 401, timestamp: 2019-12-12T07:12:17.144Z, details: The user is not authorized to access the API.}`. 

The app seems to be running in some context on the desktop itself before actually running on the mobile.

**Target Platform:** Ubuntu
**Target OS version/browser:** Android
**Devices:** Mi A2 Lite

## Logs

On running `flutter run --flavor development -t lib/main.dart`, I got the following.
```
Launching lib/main.dart on Mi A2 Lite in debug mode...
I/flutter ( 8831): ServicesBinding.defaultBinaryMessenger was accessed before the binding was initialized.
I/flutter ( 8831): If you're running an application and need to access the binary messenger before `runApp()` has been called (for example, during plugin initialization), then you need to explicitly call the `WidgetsFlutterBinding.ensureInitialized()` first.
I/flutter ( 8831): If you're running a test, you can call the `TestWidgetsFlutterBinding.ensureInitialized()` as the first line in your test's `main()` method to initialize the binding.
I/flutter ( 8831): Error caught by Crashlytics plugin <recordError>:    
I/flutter ( 8831): ServicesBinding.defaultBinaryMessenger was accessed before the binding was initialized.
I/flutter ( 8831): If you're running an application and need to access the binary messenger before `runApp()` has been called (for example, during plugin initialization), then you need to explicitly call the `WidgetsFlutterBinding.ensureInitialized()` first.
I/flutter ( 8831): If you're running a test, you can call the `TestWidgetsFlutterBinding.ensureInitialized()` as the first line in your test's `main()` method to initialize the binding.
I/flutter ( 8831):                                                      
I/flutter ( 8831): #0      defaultBinaryMessenger.<anonymous closure> (package:flutter/src/services/binary_messenger.dart:76:7)
I/flutter ( 8831): #1      defaultBinaryMessenger (package:flutter/src/services/binary_messenger.dart:89:4)
I/flutter ( 8831): #2      MethodChannel.binaryMessenger (package:flutter/src/services/platform_channel.dart:140:62)
I/flutter ( 8831): #3      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:314:35)
I/flutter ( 8831): #4      MethodChannel.invokeMapMethod (package:flutter/src/services/platform_channel.dart:349:48)
I/flutter ( 8831): #5      SharedPreferences._getSharedPreferencesMap (package:shared_preferences/shared_preferences.dart:158:25)
I/flutter ( 8831): #6      SharedPreferences.getInstance (package:shared_preferences/shared_preferences.dart:25:17)
I/flutter ( 8831): #7      main.<anonymous closure> (package:cprepay/start.dart:32:48)
I/flutter ( 8831): #8      _rootRun (dart:async/zone.dart:1126:13)      
I/flutter ( 8831): #9      _CustomZone.run (dart:async/zone.dart:1023:19)
I/flutter ( 8831): #10     _runZoned (dart:async/zone.dart:1518:10)     
I/flutter ( 8831): #11     runZoned (dart:async/zone.dart:1502:12)      
I/flutter ( 8831): #12     main (package:cprepay/start.dart:31:3)       
I/flutter ( 8831): #13     ma                                           
I/flutter (10942): ServicesBinding.defaultBinaryMessenger was accessed before the binding was initialized.
I/flutter (10942): If you're running an application and need to access the binary messenger before `runApp()` has been called (for example, during plugin initialization), then you need to explicitly call the `WidgetsFlutterBinding.ensureInitialized()` first.
I/flutter (10942): If you're running a test, you can call the `TestWidgetsFlutterBinding.ensureInitialized()` as the first line in your test's `main()` method to initialize the binding.
I/flutter (10942): Error caught by Crashlytics plugin <recordError>:    
I/flutter (10942): ServicesBinding.defaultBinaryMessenger was accessed before the binding was initialized.
I/flutter (10942): If you're running an application and need to access the binary messenger before `runApp()` has been called (for example, during plugin initialization), then you need to explicitly call the `WidgetsFlutterBinding.ensureInitialized()` first.
I/flutter (10942): If you're running a test, you can call the `TestWidgetsFlutterBinding.ensureInitialized()` as the first line in your test's `main()` method to initialize the binding.
I/flutter (10942):                                                      
I/flutter (10942): #0      defaultBinaryMessenger.<anonymous closure> (package:flutter/src/services/binary_messenger.dart:76:7)
I/flutter (10942): #1      defaultBinaryMessenger (package:flutter/src/services/binary_messenger.dart:89:4)
I/flutter (10942): #2      MethodChannel.binaryMessenger (package:flutter/src/services/platform_channel.dart:140:62)
I/flutter (10942): #3      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:314:35)
I/flutter (10942): #4      MethodChannel.invokeMapMethod (package:flutter/src/services/platform_channel.dart:349:48)
I/flutter (10942): #5      SharedPreferences._getSharedPreferencesMap (package:shared_preferences/shared_preferences.dart:158:25)
I/flutter (10942): #6      SharedPreferences.getInstance (package:shared_preferences/shared_preferences.dart:25:17)
I/flutter (10942): #7      main.<anonymous closure> (package:cprepay/start.dart:32:48)
I/flutter (10942): #8      _rootRun (dart:async/zone.dart:1126:13)      
I/flutter (10942): #9      _CustomZone.run (dart:async/zone.dart:1023:19)
I/flutter (10942): #10     _runZoned (dart:async/zone.dart:1518:10)     
I/flutter (10942): #11     runZoned (dart:async/zone.dart:1502:12)      
I/flutter (10942): #12     main (package:cprepay/start.dart:31:3)       
I/flutter (10942): #13     ma                                           
I/flutter (13768): ServicesBinding.defaultBinaryMessenger was accessed before the binding was initialized.
I/flutter (13768): If you're running an application and need to access the binary messenger before `runApp()` has been called (for example, during plugin initialization), then you need to explicitly call the `WidgetsFlutterBinding.ensureInitialized()` first.
I/flutter (13768): If you're running a test, you can call the `TestWidgetsFlutterBinding.ensureInitialized()` as the first line in your test's `main()` method to initialize the binding.
I/flutter (13768): Error caught by Crashlytics plugin <recordError>:    
I/flutter (13768): ServicesBinding.defaultBinaryMessenger was accessed before the binding was initialized.
I/flutter (13768): If you're running an application and need to access the binary messenger before `runApp()` has been called (for example, during plugin initialization), then you need to explicitly call the `WidgetsFlutterBinding.ensureInitialized()` first.
I/flutter (13768): If you're running a test, you can call the `TestWidgetsFlutterBinding.ensureInitialized()` as the first line in your test's `main()` method to initialize the binding.
I/flutter (13768):                                                      
I/flutter (13768): #0      defaultBinaryMessenger.<anonymous closure> (package:flutter/src/services/binary_messenger.dart:76:7)
I/flutter (13768): #1      defaultBinaryMessenger (package:flutter/src/services/binary_messenger.dart:89:4)
I/flutter (13768): #2      MethodChannel.binaryMessenger (package:flutter/src/services/platform_channel.dart:140:62)
I/flutter (13768): #3      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:314:35)
I/flutter (13768): #4      MethodChannel.invokeMapMethod (package:flutter/src/services/platform_channel.dart:349:48)
I/flutter (13768): #5      SharedPreferences._getSharedPreferencesMap (package:shared_preferences/shared_preferences.dart:158:25)
I/flutter (13768): #6      SharedPreferences.getInstance (package:shared_preferences/shared_preferences.dart:25:17)
I/flutter (13768): #7      main.<anonymous closure> (package:cprepay/start.dart:32:48)
I/flutter (13768): #8      _rootRun (dart:async/zone.dart:1126:13)      
I/flutter (13768): #9      _CustomZone.run (dart:async/zone.dart:1023:19)
I/flutter (13768): #10     _runZoned (dart:async/zone.dart:1518:10)     
I/flutter (13768): #11     runZoned (dart:async/zone.dart:1502:12)      
I/flutter (13768): #12     main (package:cprepay/start.dart:31:3)       
I/flutter (13768): #13     ma                                           
I/flutter (15132): ServicesBinding.defaultBinaryMessenger was accessed before the binding was initialized.
I/flutter (15132): If you're running an application and need to access the binary messenger before `runApp()` has been called (for example, during plugin initialization), then you need to explicitly call the `WidgetsFlutterBinding.ensureInitialized()` first.
I/flutter (15132): If you're running a test, you can call the `TestWidgetsFlutterBinding.ensureInitialized()` as the first line in your test's `main()` method to initialize the binding.
I/flutter (15132): Error caught by Crashlytics plugin <recordError>:    
I/flutter (15132): ServicesBinding.defaultBinaryMessenger was accessed before the binding was initialized.
I/flutter (15132): If you're running an application and need to access the binary messenger before `runApp()` has been called (for example, during plugin initialization), then you need to explicitly call the `WidgetsFlutterBinding.ensureInitialized()` first.
I/flutter (15132): If you're running a test, you can call the `TestWidgetsFlutterBinding.ensureInitialized()` as the first line in your test's `main()` method to initialize the binding.
I/flutter (15132):                                                      
I/flutter (15132): #0      defaultBinaryMessenger.<anonymous closure> (package:flutter/src/services/binary_messenger.dart:76:7)
I/flutter (15132): #1      defaultBinaryMessenger (package:flutter/src/services/binary_messenger.dart:89:4)
I/flutter (15132): #2      MethodChannel.binaryMessenger (package:flutter/src/services/platform_channel.dart:140:62)
I/flutter (15132): #3      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:314:35)
I/flutter (15132): #4      MethodChannel.invokeMapMethod (package:flutter/src/services/platform_channel.dart:349:48)
I/flutter (15132): #5      SharedPreferences._getSharedPreferencesMap (package:shared_preferences/shared_preferences.dart:158:25)
I/flutter (15132): #6      SharedPreferences.getInstance (package:shared_preferences/shared_preferences.dart:25:17)
I/flutter (15132): #7      main.<anonymous closure> (package:cprepay/start.dart:32:48)
I/flutter (15132): #8      _rootRun (dart:async/zone.dart:1126:13)      
I/flutter (15132): #9      _CustomZone.run (dart:async/zone.dart:1023:19)
I/flutter (15132): #10     _runZoned (dart:async/zone.dart:1518:10)     
I/flutter (15132): #11     runZoned (dart:async/zone.dart:1502:12)      
I/flutter (15132): #12     main (package:cprepay/start.dart:31:3)       
I/flutter (15132): #13     ma                                           
I/flutter (15606): ServicesBinding.defaultBinaryMessenger was accessed before the binding was initialized.
I/flutter (15606): If you're running an application and need to access the binary messenger before `runApp()` has been called (for example, during plugin initialization), then you need to explicitly call the `WidgetsFlutterBinding.ensureInitialized()` first.
I/flutter (15606): If you're running a test, you can call the `TestWidgetsFlutterBinding.ensureInitialized()` as the first line in your test's `main()` method to initialize the binding.
I/flutter (15606): Error caught by Crashlytics plugin <recordError>:    
I/flutter (15606): ServicesBinding.defaultBinaryMessenger was accessed before the binding was initialized.
I/flutter (15606): If you're running an application and need to access the binary messenger before `runApp()` has been called (for example, during plugin initialization), then you need to explicitly call the `WidgetsFlutterBinding.ensureInitialized()` first.
I/flutter (15606): If you're running a test, you can call the `TestWidgetsFlutterBinding.ensureInitialized()` as the first line in your test's `main()` method to initialize the binding.
I/flutter (15606):                                                      
I/flutter (15606): #0      defaultBinaryMessenger.<anonymous closure> (package:flutter/src/services/binary_messenger.dart:76:7)
I/flutter (15606): #1      defaultBinaryMessenger (package:flutter/src/services/binary_messenger.dart:89:4)
I/flutter (15606): #2      MethodChannel.binaryMessenger (package:flutter/src/services/platform_channel.dart:140:62)
I/flutter (15606): #3      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:314:35)
I/flutter (15606): #4      MethodChannel.invokeMapMethod (package:flutter/src/services/platform_channel.dart:349:48)
I/flutter (15606): #5      SharedPreferences._getSharedPreferencesMap (package:shared_preferences/shared_preferences.dart:158:25)
I/flutter (15606): #6      SharedPreferences.getInstance (package:shared_preferences/shared_preferences.dart:25:17)
I/flutter (15606): #7      main.<anonymous closure> (package:cprepay/start.dart:32:48)
I/flutter (15606): #8      _rootRun (dart:async/zone.dart:1126:13)      
I/flutter (15606): #9      _CustomZone.run (dart:async/zone.dart:1023:19)
I/flutter (15606): #10     _runZoned (dart:async/zone.dart:1518:10)     
I/flutter (15606): #11     runZoned (dart:async/zone.dart:1502:12)      
I/flutter (15606): #12     main (package:cprepay/start.dart:31:3)       
I/flutter (15606): #13     ma                                           
I/flutter (16064): ServicesBinding.defaultBinaryMessenger was accessed before the binding was initialized.
I/flutter (16064): If you're running an application and need to access the binary messenger before `runApp()` has been called (for example, during plugin initialization), then you need to explicitly call the `WidgetsFlutterBinding.ensureInitialized()` first.
I/flutter (16064): If you're running a test, you can call the `TestWidgetsFlutterBinding.ensureInitialized()` as the first line in your test's `main()` method to initialize the binding.
I/flutter (16064): Error caught by Crashlytics plugin <recordError>:    
I/flutter (16064): ServicesBinding.defaultBinaryMessenger was accessed before the binding was initialized.
I/flutter (16064): If you're running an application and need to access the binary messenger before `runApp()` has been called (for example, during plugin initialization), then you need to explicitly call the `WidgetsFlutterBinding.ensureInitialized()` first.
I/flutter (16064): If you're running a test, you can call the `TestWidgetsFlutterBinding.ensureInitialized()` as the first line in your test's `main()` method to initialize the binding.
I/flutter (16064):                                                      
I/flutter (16064): #0      defaultBinaryMessenger.<anonymous closure> (package:flutter/src/services/binary_messenger.dart:76:7)
I/flutter (16064): #1      defaultBinaryMessenger (package:flutter/src/services/binary_messenger.dart:89:4)
I/flutter (16064): #2      MethodChannel.binaryMessenger (package:flutter/src/services/platform_channel.dart:140:62)
I/flutter (16064): #3      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:314:35)
I/flutter (16064): #4      MethodChannel.invokeMapMethod (package:flutter/src/services/platform_channel.dart:349:48)
I/flutter (16064): #5      SharedPreferences._getSharedPreferencesMap (package:shared_preferences/shared_preferences.dart:158:25)
I/flutter (16064): #6      SharedPreferences.getInstance (package:shared_preferences/shared_preferences.dart:25:17)
I/flutter (16064): #7      main.<anonymous closure> (package:cprepay/start.dart:32:48)
I/flutter (16064): #8      _rootRun (dart:async/zone.dart:1126:13)      
I/flutter (16064): #9      _CustomZone.run (dart:async/zone.dart:1023:19)
I/flutter (16064): #10     _runZoned (dart:async/zone.dart:1518:10)     
I/flutter (16064): #11     runZoned (dart:async/zone.dart:1502:12)      
I/flutter (16064): #12     main (package:cprepay/start.dart:31:3)       
I/flutter (16064): #13     ma                                           
I/flutter (16477): {error: unauthorized, status: 401, timestamp: 2019-12-12T07:12:17.144Z, details: The user is not authorized to access the API.}
I/flutter (17428): {error: unauthorized, status: 401, timestamp: 2019-12-12T07:14:38.459Z, details: The user is not authorized to access the API.}
Running Gradle task 'assembleDevelopmentDebug'...                       
Running Gradle task 'assembleDevelopmentDebug'... Done             17.4s
✓ Built build/app/outputs/apk/development/debug/app-development-debug.apk.
Installing build/app/outputs/apk/app.apk...                         6.5s
Syncing files to device Mi A2 Lite...                                   
I/flutter (20264): {error: unauthorized, status: 401, timestamp: 2019-12-12T07:24:17.175Z, details: The user is not authorized to access the API.}
Syncing files to device Mi A2 Lite...                            6,294ms (!)     
```

**Comment by huntrist** [comment]
experienced similar issue on an Android Emulator,
after wipe the Emulator data, everything worked fine.

**Comment by RuedigerMoeller** [comment]
similar here after update 
error:
`E/flutter ( 4812): [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: ServicesBinding.defaultBinaryMessenger was accessed before the binding was initialized.
E/flutter ( 4812): If you're running an application and need to access the binary messenger before `runApp()` has been called (for example, during plugin initialization), then you need to explicitly call the `WidgetsFlutterBinding.ensureInitialized()` first.
`
Error is sticky although i added the line. also it looks like the build is running in the background, so app starts before build is finished.

**Comment by akarabach** [comment]
```
void main() {
  WidgetsFlutterBinding.ensureInitialized();
  runApp(TrainingsDairyApp());
}
```
```

Running Gradle task 'assembleDebug'...
E/flutter ( 6301): [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: ServicesBinding.defaultBinaryMessenger was accessed before the binding was initialized.
E/flutter ( 6301): If you're running an application and need to access the binary messenger before `runApp()` has been called (for example, during plugin initialization), then you need to explicitly call the `WidgetsFlutterBinding.ensureInitialized()` first.
E/flutter ( 6301): If you're running a test, you can call the `TestWidgetsFlutterBinding.ensureInitialized()` as the first line in your test's `main()` method to initialize the binding.
```

Still see this error, but project run on my emulator. `1.12.13+hotfix.5 • channel stable`

@adazh

**Comment by Leafyyuki** [comment]
Same issue on ios platform:
```
[VERBOSE-2:ui_dart_state.cc(157)] Unhandled Exception: ServicesBinding.defaultBinaryMessenger was accessed before the binding was initialized.
If you're running an application and need to access the binary messenger before `runApp()` has been called (for example, during plugin initialization), then you need to explicitly call the `WidgetsFlutterBinding.ensureInitialized()` first.
If you're running a test, you can call the `TestWidgetsFlutterBinding.ensureInitialized()` as the first line in your test's `main()` method to initialize the binding.
#0      defaultBinaryMessenger.<anonymous closure> (package:flutter/src/services/binary_messenger.dart:76:7)
#1      defaultBinaryMessenger (package:flutter/src/services/binary_messenger.dart:89:4)
#2      MethodChannel.binaryMessenger (package:flutter/src/services/platform_channel.dart:140:62)
#3      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:314:35)
#4      MethodChannel.invokeMapMethod (package:flutter/src/services/platfo<…>
```

**Comment by akarabach** [comment]
> Same issue on ios platform:
> 
> ```
> [VERBOSE-2:ui_dart_state.cc(157)] Unhandled Exception: ServicesBinding.defaultBinaryMessenger was accessed before the binding was initialized.
> If you're running an application and need to access the binary messenger before `runApp()` has been called (for example, during plugin initialization), then you need to explicitly call the `WidgetsFlutterBinding.ensureInitialized()` first.
> If you're running a test, you can call the `TestWidgetsFlutterBinding.ensureInitialized()` as the first line in your test's `main()` method to initialize the binding.
> #0      defaultBinaryMessenger.<anonymous closure> (package:flutter/src/services/binary_messenger.dart:76:7)
> #1      defaultBinaryMessenger (package:flutter/src/services/binary_messenger.dart:89:4)
> #2      MethodChannel.binaryMessenger (package:flutter/src/services/platform_channel.dart:140:62)
> #3      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:314:35)
> #4      MethodChannel.invokeMapMethod (package:flutter/src/services/platfo<…>
> ```
> 
> and my app stuck on black screen.

Have you added at the top of main function this code ?

`  WidgetsFlutterBinding.ensureInitialized();`

**Comment by AbdelbakiBoukerche** [comment]
I had the same issue.
First i added `WidgetsFlutterBinding.ensureInitialized();` **before** `runApp()`  nothing happend then i moved `WidgetsFlutterBinding.ensureInitialized();` to the **first line in** **`main()`** then i opend my AVD manager **wiped the data of my emulator**, and it worked!

**Comment by wangwanchao** [comment]
Adding `WidgetsFlutterBinding.ensureInitialized();` before `runApp()` and make `main()`  `async`  all worked for me.

**Comment by akarabach** [comment]
> Adding `WidgetsFlutterBinding.ensureInitialized();` before `runApp()` and make `main()` `async` all worked for me.

Where have you found that main should be async ?

**Comment by pepsighan** [comment]
Mine was already async to begin with. The issue is something else imo.

**Comment by kriticalflare** [comment]
Avd has no relation with this issue , atleast in my case as i dont use avd. +1 on adding ```WidgetsFlutterBinding.ensureInitialized();``` as first line in main() fixing the issue.

**Comment by kriticalflare** [comment]
I could fix the issue without using ```WidgetsFlutterBinding.ensureInitialized();```

The issue seems to be in having code that uses platform channels inside ``` main() ```
The main method is being run even before build finishes and to prevent the error we need to have ```WidgetsFlutterBinding.ensureInitialized();```, which does what it says on the label. 
In my case it was the path_provider package

**Comment by wangwanchao** [comment]
> > Adding `WidgetsFlutterBinding.ensureInitialized();` before `runApp()` and make `main()` `async` all worked for me.
> 
> Where have you found that main should be async ?

[#47033](https://github.com/flutter/flutter/issues/47033)

**Comment by wangwanchao** [comment]
> I could fix the issue without using `WidgetsFlutterBinding.ensureInitialized();`
> 
> The issue seems to be in having code that uses platform channels inside `main()`
> The main method is being run even before build finishes and to prevent the error we need to have `WidgetsFlutterBinding.ensureInitialized();`, which does what it says on the label.
> In my case it was the path_provider package

what you said is the main method must be finished before something is called? but my project was build by  flutter 1.0.0+1, I built it yesterday, this error occured.

**Comment by karlito40** [comment]
I'm experiencing the same issue after upgrading my flutter sdk to `v1.12.13+hotfix.5`.

`WidgetsFlutterBinding.ensureInitialized ()` partially resolved this problem. I can now access my application (no black screen anymore) but I still have errors during the building stage.

```
[+2023 ms] E/flutter (29561): [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception:
ServicesBinding.defaultBinaryMessenger was accessed before the binding was initialized.
```

My flutter doctor:
```
✓] Flutter (Channel stable, v1.12.13+hotfix.5, on Linux, locale fr_FR.UTF-8)
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
```

My main:
```
Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized();
  cameras = await availableCameras();
  runApp(CameraApp());
}
// ... and everything next come from the camera plugin example
```

**Comment by Hixie** [comment]
This bug report lacks sufficient information for us to address the problem(s).

Please file new bugs. In each bug, please include the following information:
* How to reproduce the problem, starting from `flutter create` and including the full source code of a demo application showing the problem.
* What you expected, and what you got.
* Details such as which device you are seeing this problem on.
