### ISSUE TITLE
Web: Getting error in pointer_converter.dart on checkbox click, button click and selecting textbox to type

### ISSUE THREAD

**Issue by Dinesh2703** [flutter/flutter#46852]
Getting below like errors on checkbox click, button click selecting textbox to type-
```bash
Flutter version - v1.12.13+hotfix.6
chrome version - Version 78.0.3904.108 (Official Build) (64-bit)

```
```bash
errors.dart:147 Uncaught Error: Assertion failed: org-dartlang-sdk:///flutter_web_sdk/lib/_engine/engine/pointer_converter.dart:366:18
!_locationHasChanged(device, physicalX, physicalY)
is not true
    at Object.throw_ [as throw] (errors.dart:196)
    at Object.assertFailed (errors.dart:26)
    at _engine.PointerDataConverter.new.convert (pointer_converter.dart:366)
    at _engine.PointerAdapter.new.[_convertEventToPointerData] (pointer_binding.dart:366)
    at pointer_binding.dart:306
    at HTMLElement.<anonymous> (pointer_binding.dart:183)
DartError @ errors.dart:147
throw_ @ errors.dart:196
assertFailed @ errors.dart:26
convert @ pointer_converter.dart:366
[_convertEventToPointerData] @ pointer_binding.dart:366
(anonymous) @ pointer_binding.dart:306
(anonymous) @ pointer_binding.dart:183
---------------------------------------------------------
errors.dart:147 Uncaught Error: Assertion failed: org-dartlang-sdk:///flutter_web_sdk/lib/_engine/engine/pointer_converter.dart:435:18
state.down
is not true
    at Object.throw_ [as throw] (errors.dart:196)
    at Object.assertFailed (errors.dart:26)
    at _engine.PointerDataConverter.new.convert (pointer_converter.dart:435)
    at _engine.PointerAdapter.new.[_convertEventToPointerData] (pointer_binding.dart:366)
    at pointer_binding.dart:334
    at HTMLElement.<anonymous> (pointer_binding.dart:183)
===================================================
- flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel beta, v1.12.13+hotfix.6, on Microsoft Windows [Version 10.0.18362.476], locale en-IN)

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[√] Chrome - develop for the web
[√] Android Studio (version 3.5)
[√] VS Code (version 1.40.2)
[√] Connected device (2 available)

• No issues found!
====================================
flutter run --verbose

[  +23 ms] executing: [C:\Repos\flutter\] git -c log.showSignature=false log -n 1 --pretty=format:%H
[  +63 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[   +1 ms] 18cd7a3601bcffb36fdf2f679f763b5e827c2e8e
[        ] executing: [C:\Repos\flutter\] git describe --match v*.*.* --first-parent --long --tags
[  +62 ms] Exit code 0 from: git describe --match v*.*.* --first-parent --long --tags
[   +1 ms] v1.12.13+hotfix.6-0-g18cd7a360
[   +7 ms] executing: [C:\Repos\flutter\] git rev-parse --abbrev-ref --symbolic @{u}
[  +43 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/beta
[        ] executing: [C:\Repos\flutter\] git ls-remote --get-url origin
[  +38 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[  +82 ms] executing: [C:\Repos\flutter\] git rev-parse --abbrev-ref HEAD
[  +41 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] beta
[ +112 ms] executing: C:\Users\Dinesh\AppData\Local\Android\sdk\platform-tools\adb.exe devices -l
[  +23 ms] Exit code 0 from: C:\Users\Dinesh\AppData\Local\Android\sdk\platform-tools\adb.exe devices -l
[        ] List of devices attached
[  +13 ms] More than one device connected; please specify a device with the '-d <deviceId>' flag, or use '-d all' to act on all devices.
[  +48 ms] Chrome     • chrome     • web-javascript • Google Chrome 79.0.3945.79
[   +1 ms] Web Server • web-server • web-javascript • Flutter Tools
[   +9 ms] "flutter run" took 249ms.

#0      throwToolExit (package:flutter_tools/src/base/common.dart:28:3)
#1      RunCommand.validateCommand (package:flutter_tools/src/commands/run.dart:289:7)
<asynchronous suspension>
#2      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:590:11)
#3      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:515:33)
<asynchronous suspension>
#4      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:146:29)
#5      _rootRun (dart:async/zone.dart:1126:13)
#6      _CustomZone.run (dart:async/zone.dart:1023:19)
#7      _runZoned (dart:async/zone.dart:1518:10)
#8      runZoned (dart:async/zone.dart:1465:12)
#9      AppContext.run (package:flutter_tools/src/base/context.dart:145:18)
#10     FlutterCommand.run (package:flutter_tools/src/runner/flutter_command.dart:505:20)
#11     CommandRunner.runCommand (package:args/command_runner.dart:197:27)
#12     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:413:21)
<asynchronous suspension>
#13     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:146:29)
#14     _rootRun (dart:async/zone.dart:1126:13)
#15     _CustomZone.run (dart:async/zone.dart:1023:19)
#16     _runZoned (dart:async/zone.dart:1518:10)
#17     runZoned (dart:async/zone.dart:1465:12)
#18     AppContext.run (package:flutter_tools/src/base/context.dart:145:18)
#19     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:364:19)
#20     CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:112:25)
#21     new Future.sync (dart:async/future.dart:224:31)
#22     CommandRunner.run (package:args/command_runner.dart:112:14)
#23     FlutterCommandRunner.run (package:flutter_tools/src/runner/flutter_command_runner.dart:250:18)
#24     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:63:22)
#25     _rootRun (dart:async/zone.dart:1126:13)
#26     _CustomZone.run (dart:async/zone.dart:1023:19)
#27     _runZoned (dart:async/zone.dart:1518:10)
#28     runZoned (dart:async/zone.dart:1502:12)
#29     run.<anonymous closure> (package:flutter_tools/runner.dart:61:18)
<asynchronous suspension>
#30     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:146:29)
#31     _rootRun (dart:async/zone.dart:1126:13)
#32     _CustomZone.run (dart:async/zone.dart:1023:19)
#33     _runZoned (dart:async/zone.dart:1518:10)
#34     runZoned (dart:async/zone.dart:1465:12)
#35     AppContext.run (package:flutter_tools/src/base/context.dart:145:18)
#36     runInContext (package:flutter_tools/src/context_runner.dart:64:24)
#37     run (package:flutter_tools/runner.dart:50:10)
#38     main (package:flutter_tools/executable.dart:65:9)
#39     main (file:///C:/Repos/flutter/packages/flutter_tools/bin/flutter_tools.dart:8:3)
#40     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:305:32)
#41     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:174:12)



```

**Comment by iapicca** [comment]
Hi @Dinesh2703 
can you please provide a minimal code sample
or the steps to reproduce the problem.
Thank you

**Comment by Dinesh2703** [comment]
> Hi @Dinesh2703
> please follow the [docs ](https://flutter.dev/docs/get-started/web#create-a-new-project-with-web-support)for creating a web project;
> 
Yes I have followed all steps. Please check my flutter doctor and flutter run --verbose results
Thankyou
> ` flutter channel beta`
> ` flutter upgrade`
> ` flutter config --enable-web`
> 
> if the issue persists,
> can you please provide your updated `flutter doctor -v`
> and your `flutter run --verbose`?
> Also, to better address the issue, would be helpful
> if you could post a minimal code sample
> or the steps to reproduce the problem.
> Thank you

**Comment by yjbanov** [comment]
@dkwingsmt I think you are working on a fix for this, right?

**Comment by Dinesh2703** [comment]
> @dkwingsmt I think you are working on a fix for this, right?

No sir, I posted this error to get the solution.

**Comment by dkwingsmt** [comment]
@yjbanov For now it doesn't look like my fix will solve this error. I can take a look at this though.

**Comment by yjbanov** [comment]
Cool. Thanks! Feel free to reassign to me if you think this is outside your domain.

**Comment by prujohn** [comment]
@yjbanov I also get this error, but only when running in debug mode (beta channel).  `flutter build web` compiled versions of my apps do not throw this error.

I can work around the error, by moving the mouse in and out of the browser frame before making a click, but this is inconsistent at best and definitely slows down testing cycles.

**Comment by dkwingsmt** [comment]
> @yjbanov I also get this error, but only when running in debug mode (beta channel). `flutter build web` compiled versions of my apps do not throw this error.
> 
> I can work around the error, by moving the mouse pointer in and out of the browser frame before making a click, but this is inconsistent at best and definitely slows down testing cycles.

Can you confirm that this error still exist on master? A patch landed about 8 days ago and I wonder if it fixes this.

**Comment by miketheman** [comment]
I commented with a current stack on the linked issue. I can confirm the beta release `build` output does not contain the errors, but running the develop/debug mode does.

**Comment by prujohn** [comment]
I also noticed one other thing about this problem:  I do not get any errors, when I put the browser into a device view (such as Pixel2XL, etc) so I'm using this as a workaround for now.  I think when using a device view, it's triggering tap events instead of click events, which may be a contributing factor.

**Comment by mdebbar** [comment]
@Dinesh2703 @miketheman @prujohn Similar errors have been fixed in https://github.com/flutter/engine/pull/15103. Could you please check if you are still experiencing the same issue on master?

**Comment by agyimr** [comment]
I just stumbled into this problem. Sometimes the problem occurs on regular left-clicks, at these occasions, the onTap function does not get executed. But it also happens on every right-click.
