### ISSUE TITLE
Unable to build android after upgrading to 1.12

### ISSUE THREAD

**Issue by RemeJuan** [flutter/flutter#46873]
Flutter crash report; please file at https://github.com/flutter/flutter/issues.

## command

flutter build apk --split-per-abi

## exception

ProcessException: ProcessException: Permission denied
  Command: /Users/remelehane/flutter/.pub-cache/hosted/pub.dartlang.org/file_picker-1.4.3+1/android/gradlew -I=/Users/remelehane/flutter/packages/flutter_tools/gradle/aar_init_script.gradle -Pflutter-root=/Users/remelehane/flutter -Poutput-dir=/Users/remelehane/Documents/wyzetalk/member-ui-flutter/build/app -Pis-plugin=true -Ptarget-platform=android-arm,android-arm64,android-x64 assembleAarRelease

```
#0      _DefaultProcessUtils.run (package:flutter_tools/src/base/process.dart:266:37)
<asynchronous suspension>
#1      buildGradleAar (package:flutter_tools/src/android/gradle.dart:548:33)
#2      buildPluginsAsAar (package:flutter_tools/src/android/gradle.dart:711:13)
<asynchronous suspension>
#3      buildGradleApp (package:flutter_tools/src/android/gradle.dart:257:11)
#4      _AsyncAwaitCompleter.start (dart:async-patch/async_patch.dart:45:6)
#5      buildGradleApp (package:flutter_tools/src/android/gradle.dart:218:28)
#6      buildGradleApp (package:flutter_tools/src/android/gradle.dart:415:19)
#7      _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:73:64)
#8      _rootRunUnary (dart:async/zone.dart:1134:38)
#9      _CustomZone.runUnary (dart:async/zone.dart:1031:19)
#10     _FutureListener.handleValue (dart:async/future_impl.dart:139:18)
#11     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:680:45)
#12     Future._propagateToListeners (dart:async/future_impl.dart:709:32)
#13     Future._completeWithValue (dart:async/future_impl.dart:524:5)
#14     Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:554:7)
#15     _rootRun (dart:async/zone.dart:1126:13)
#16     _CustomZone.run (dart:async/zone.dart:1023:19)
#17     _CustomZone.runGuarded (dart:async/zone.dart:925:7)
#18     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:965:23)
#19     _microtaskLoop (dart:async/schedule_microtask.dart:43:21)
#20     _startMicrotaskLoop (dart:async/schedule_microtask.dart:52:5)
#21     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
#22     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:175:5)
```

## flutter doctor

```
[32m[✓][39m Flutter (Channel stable, v1.12.13+hotfix.5, on Mac OS X 10.15.2 19C56a, locale en-ZA)
    [32m•[39m Flutter version 1.12.13+hotfix.5 at /Users/remelehane/flutter
    [32m•[39m Framework revision 27321ebbad (33 hours ago), 2019-12-10 18:15:01 -0800
    [32m•[39m Engine revision 2994f7e1e6
    [32m•[39m Dart version 2.7.0

[32m[✓][39m Android toolchain - develop for Android devices (Android SDK version 29.0.0)
    [32m•[39m Android SDK at /Users/remelehane/Library/Android/sdk
    [32m•[39m Android NDK location not configured (optional; useful for native profiling support)
    [32m•[39m Platform android-29, build-tools 29.0.0
    [32m•[39m ANDROID_HOME = /Users/remelehane/Library/Android/sdk
    [32m•[39m ANDROID_SDK_ROOT = /usr/local/share/android-sdk
    [32m•[39m Java binary at: /Users/remelehane/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/191.6010548/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    [32m•[39m Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    [32m•[39m All Android licenses accepted.

[32m[✓][39m Xcode - develop for iOS and macOS (Xcode 11.0)
    [32m•[39m Xcode at /Applications/Xcode.app/Contents/Developer
    [32m•[39m Xcode 11.0, Build version 11A420a
    [32m•[39m CocoaPods version 1.7.5

[32m[✓][39m Android Studio (version 3.5)
    [32m•[39m Android Studio at /Users/remelehane/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/191.6010548/Android Studio.app/Contents
    [32m•[39m Flutter plugin version 42.1.1
    [32m•[39m Dart plugin version 191.8593
    [32m•[39m Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[33m[!][39m IntelliJ IDEA Ultimate Edition (version 2019.3)
    [32m•[39m IntelliJ at /Users/remelehane/Applications/JetBrains Toolbox/IntelliJ IDEA Ultimate.app
    [31m✗[39m Flutter plugin not installed; this adds Flutter specific functionality.
    [31m✗[39m Dart plugin not installed; this adds Dart specific functionality.
    [32m•[39m For information about installing plugins, see
      https://flutter.dev/intellij-setup/#installing-the-plugins

[32m[✓][39m VS Code (version 1.40.2)
    [32m•[39m VS Code at /Applications/Visual Studio Code.app/Contents
    [32m•[39m Flutter extension version 3.7.0

[32m[✓][39m Connected device (1 available)
    [32m•[39m iPhone 5s • DE9EF75F-9B46-4A6A-969F-99B9DF29F154 • ios • com.apple.CoreSimulator.SimRuntime.iOS-12-4 (simulator)

[33m![39m Doctor found issues in 1 category.
```

**Comment by iapicca** [comment]
Hi @RemeJuan 
could you please run
`flutter clean`
`flutter pub cache repair`
let me know if the issue persists
thank you

**Comment by RemeJuan** [comment]
Thanks @iapicca 

> `flutter pub cache repair`

resulted in:

```
Reactivating devtools 0.1.6...
Precompiling executables...
Precompiled devtools:devtools.
Installed executable devtools.
Reactivating dartdoc 0.28.7...
Precompiling executables...
Failed to precompile dartdoc:dartdoc:
Error: Could not resolve the package 'dartdoc' in 'package:dartdoc/dartdoc.dart'.
Error: Could not resolve the package 'dartdoc' in 'package:dartdoc/src/html/html_generator.dart'.
Error: Could not resolve the package 'dartdoc' in 'package:dartdoc/src/logging.dart'.
Error: Could not resolve the package 'dartdoc' in 'package:dartdoc/src/tool_runner.dart'.
../../../flutter/.pub-cache/hosted/pub.dartlang.org/dartdoc-0.28.7/bin/dartdoc.dart:11:8: Error: Not found: 'package:dartdoc/dartdoc.dart'
import 'package:dartdoc/dartdoc.dart';
       ^
../../../flutter/.pub-cache/hosted/pub.dartlang.org/dartdoc-0.28.7/bin/dartdoc.dart:12:8: Error: Not found: 'package:dartdoc/src/html/html_generator.dart'
import 'package:dartdoc/src/html/html_generator.dart';
       ^
../../../flutter/.pub-cache/hosted/pub.dartlang.org/dartdoc-0.28.7/bin/dartdoc.dart:13:8: Error: Not found: 'package:dartdoc/src/logging.dart'
import 'package:dartdoc/src/logging.dart';
       ^
../../../flutter/.pub-cache/hosted/pub.dartlang.org/dartdoc-0.28.7/bin/dartdoc.dart:14:8: Error: Not found: 'package:dartdoc/src/tool_runner.dart'
import 'package:dartdoc/src/tool_runner.dart';
       ^
../../../flutter/.pub-cache/hosted/pub.dartlang.org/dartdoc-0.28.7/bin/dartdoc.dart:17:43: Error: Type 'DartdocGeneratorOptionContext' not found.
class DartdocProgramOptionContext extends DartdocGeneratorOptionContext
                                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
../../../flutter/.pub-cache/hosted/pub.dartlang.org/dartdoc-0.28.7/bin/dartdoc.dart:18:10: Error: Type 'LoggingContext' not found.
    with LoggingContext {
         ^^^^^^^^^^^^^^
Failed to reactivate dartdoc 0.28.7: Failed to precompile dartdoc:dartdoc:
Error: Could not resolve the package 'dartdoc' in 'package:dartdoc/dartdoc.dart'.
Error: Could not resolve the package 'dartdoc' in 'package:dartdoc/src/html/html_generator.dart'.
Error: Could not resolve the package 'dartdoc' in 'package:dartdoc/src/logging.dart'.
Error: Could not resolve the package 'dartdoc' in 'package:dartdoc/src/tool_runner.dart'.
../../../flutter/.pub-cache/hosted/pub.dartlang.org/dartdoc-0.28.7/bin/dartdoc.dart:11:8: Error: Not found: 'package:dartdoc/dartdoc.dart'
import 'package:dartdoc/dartdoc.dart';
       ^
../../../flutter/.pub-cache/hosted/pub.dartlang.org/dartdoc-0.28.7/bin/dartdoc.dart:12:8: Error: Not found: 'package:dartdoc/src/html/html_generator.dart'
import 'package:dartdoc/src/html/html_generator.dart';
       ^
../../../flutter/.pub-cache/hosted/pub.dartlang.org/dartdoc-0.28.7/bin/dartdoc.dart:13:8: Error: Not found: 'package:dartdoc/src/logging.dart'
import 'package:dartdoc/src/logging.dart';
       ^
../../../flutter/.pub-cache/hosted/pub.dartlang.org/dartdoc-0.28.7/bin/dartdoc.dart:14:8: Error: Not found: 'package:dartdoc/src/tool_runner.dart'
import 'package:dartdoc/src/tool_runner.dart';
       ^
../../../flutter/.pub-cache/hosted/pub.dartlang.org/dartdoc-0.28.7/bin/dartdoc.dart:17:43: Error: Type 'DartdocGeneratorOptionContext' not found.
class DartdocProgramOptionContext extends DartdocGeneratorOptionContext
                                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
../../../flutter/.pub-cache/hosted/pub.dartlang.org/dartdoc-0.28.7/bin/dartdoc.dart:18:10: Error: Type 'LoggingContext' not found.
    with LoggingContext {
         ^^^^^^^^^^^^^^
Reactivating webdev 2.1.0...
Precompiling executables...
Failed to precompile webdev:webdev:
Error: Could not resolve the package 'webdev' in 'package:webdev/src/command/configuration.dart'.
Error: Could not resolve the package 'webdev' in 'package:webdev/src/webdev_command_runner.dart'.
../../../flutter/.pub-cache/hosted/pub.dartlang.org/webdev-2.1.0/bin/webdev.dart:12:8: Error: Not found: 'package:webdev/src/command/configuration.dart'
import 'package:webdev/src/command/configuration.dart';
       ^
../../../flutter/.pub-cache/hosted/pub.dartlang.org/webdev-2.1.0/bin/webdev.dart:13:8: Error: Not found: 'package:webdev/src/webdev_command_runner.dart'
import 'package:webdev/src/webdev_command_runner.dart';
       ^
../../../flutter/.pub-cache/hosted/pub.dartlang.org/webdev-2.1.0/bin/webdev.dart:17:22: Error: Method not found: 'run'.
    exitCode = await run(args);
                     ^^^
../../../flutter/.pub-cache/hosted/pub.dartlang.org/webdev-2.1.0/bin/webdev.dart:30:8: Error: 'PackageException' isn't a type.
  } on PackageException catch (e) {
       ^^^^^^^^^^^^^^^^
../../../flutter/.pub-cache/hosted/pub.dartlang.org/webdev-2.1.0/bin/webdev.dart:47:8: Error: 'InvalidConfiguration' isn't a type.
  } on InvalidConfiguration catch (e) {
       ^^^^^^^^^^^^^^^^^^^^
../../../flutter/.pub-cache/hosted/pub.dartlang.org/webdev-2.1.0/bin/webdev.dart:53:39: Error: Getter not found: 'appName'.
String get _boldApp => styleBold.wrap(appName);
                                      ^^^^^^^
Failed to reactivate webdev 2.1.0: Failed to precompile webdev:webdev:
Error: Could not resolve the package 'webdev' in 'package:webdev/src/command/configuration.dart'.
Error: Could not resolve the package 'webdev' in 'package:webdev/src/webdev_command_runner.dart'.
../../../flutter/.pub-cache/hosted/pub.dartlang.org/webdev-2.1.0/bin/webdev.dart:12:8: Error: Not found: 'package:webdev/src/command/configuration.dart'
import 'package:webdev/src/command/configuration.dart';
       ^
../../../flutter/.pub-cache/hosted/pub.dartlang.org/webdev-2.1.0/bin/webdev.dart:13:8: Error: Not found: 'package:webdev/src/webdev_command_runner.dart'
import 'package:webdev/src/webdev_command_runner.dart';
       ^
../../../flutter/.pub-cache/hosted/pub.dartlang.org/webdev-2.1.0/bin/webdev.dart:17:22: Error: Method not found: 'run'.
    exitCode = await run(args);
                     ^^^
../../../flutter/.pub-cache/hosted/pub.dartlang.org/webdev-2.1.0/bin/webdev.dart:30:8: Error: 'PackageException' isn't a type.
  } on PackageException catch (e) {
       ^^^^^^^^^^^^^^^^
../../../flutter/.pub-cache/hosted/pub.dartlang.org/webdev-2.1.0/bin/webdev.dart:47:8: Error: 'InvalidConfiguration' isn't a type.
  } on InvalidConfiguration catch (e) {
       ^^^^^^^^^^^^^^^^^^^^
../../../flutter/.pub-cache/hosted/pub.dartlang.org/webdev-2.1.0/bin/webdev.dart:53:39: Error: Getter not found: 'appName'.
String get _boldApp => styleBold.wrap(appName);
                                      ^^^^^^^
Binstubs exist for non-activated packages:
  From dartdoc: dartdoc
  From webdev: webdev
Reactivated 1 package.
Failed to reactivate 2 packages:
- dartdoc
- webdev
pub finished with exit code 69
```

Next build:

```
flutter build apk --split-per-abi
Note: /Users/remelehane/flutter/.pub-cache/hosted/pub.dartlang.org/appcenter-0.2.1/android/src/main/java/com/aloisdeniel/flutter/appcenter/AppcenterPlugin.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.                      
Note: /Users/remelehane/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_crashlytics-0.1.2+3/android/src/main/java/io/flutter/plugins/firebase/crashlytics/firebasecrashlytics/FirebaseCrashlyticsPlugin.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.                    
Note: /Users/remelehane/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_messaging-6.0.8/android/src/main/java/io/flutter/plugins/firebasemessaging/FirebaseMessagingPlugin.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.                    
Note: Some input files use unchecked or unsafe operations.              
Note: Recompile with -Xlint:unchecked for details.                      
Note: /Users/remelehane/flutter/.pub-cache/hosted/pub.dartlang.org/path_provider-1.5.1/android/src/main/java/io/flutter/plugins/pathprovider/PathProviderPlugin.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.                    
Note: Some input files use or override a deprecated API.                
Note: Recompile with -Xlint:deprecation for details.                    
Note: /Users/remelehane/flutter/.pub-cache/hosted/pub.dartlang.org/video_player-0.10.4+2/android/src/main/java/io/flutter/plugins/videoplayer/VideoPlayerPlugin.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.                    
                                                                        
FAILURE: Build failed with an exception.                                
                                                                        
* What went wrong:                                                      
Execution failed for task ':appcenter:verifyReleaseResources'.          
> A failure occurred while executing com.android.build.gradle.internal.tasks.Workers$ActionFacade
   > Android resource linking failed                                    
     /Users/remelehane/.gradle/caches/transforms-2/files-2.1/7e74e9ed6da95b1a5ceef83c79a4fea0/core-1.0.0/res/values/values.xml:57:5-88:25: AAPT: error: resource android:attr/fontVariationSettings not found.
                                                                        
     /Users/remelehane/.gradle/caches/transforms-2/files-2.1/7e74e9ed6da95b1a5ceef83c79a4fea0/core-1.0.0/res/values/values.xml:57:5-88:25: AAPT: error: resource android:attr/ttcIndex not found.
                                                                        
                                                                        
* Try:                                                                  
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
                                                                        
* Get more help at https://help.gradle.org                              
                                                                        
BUILD FAILED in 1m 27s    
```

As well as pretty much the same error log as above.

**Comment by fryette** [comment]
@RemeJuan I have same issue on stable channel, but after switching to master everything seems to work.

**Comment by RemeJuan** [comment]
@fryette are you sure there was not something else as well, as the only thing switching to master did was make it take twice as long to fail.

**Comment by munnadroid** [comment]
Same issue while running 
`flutter pub cache repair` command.

Flutter 2.2.2 • channel stable • https://github.com/flutter/flutter.git
Framework • revision d79295af24 (12 days ago) • 2021-06-11 08:56:01 -0700
Engine • revision 91c9fc8fe0
Tools • Dart 2.13.3
