### ISSUE TITLE
Unable to find a matching configuration of project :url_launcher_macos

### ISSUE THREAD

**Issue by NTMS2017** [flutter/flutter#46905]
After upgrading to new stable version **1.12.13+hotfix.5** my app can't build. I am using  url_launcher: ^5.4.1 and my flutter doctor is:

```
**flutter doctor --verbose**
[✓] Flutter (Channel stable, v1.12.13+hotfix.5, on Mac OS X 10.15.2 19C57, locale en-CY)
    • Flutter version 1.12.13+hotfix.5 at /Users/************/flutter
    • Framework revision 27321ebbad (2 days ago), 2019-12-10 18:15:01 -0800
    • Engine revision 2994f7e1e6
    • Dart version 2.7.0

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/************/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.3, Build version 11C29
    • CocoaPods version 1.8.4

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 42.1.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] IntelliJ IDEA Community Edition (version 2019.3)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 41.1.5
    • Dart plugin version 193.5233.116

[✓] Connected device (1 available)
    • SM G935F • ce12160c0d86152e01 • android-arm64 • Android 8.0.0 (API 26)

```

```

**FAILURE: Build failed with an exception.**

* What went wrong:
Could not determine the dependencies of task ':url_launcher:compileDebugAidl'.
> Could not resolve all task dependencies for configuration ':url_launcher:debugCompileClasspath'.
   > Could not resolve project :url_launcher_macos.
     Required by:
         project :url_launcher
      > Unable to find a matching configuration of project :url_launcher_macos:
          - None of the consumable configurations have attributes.
```

**Comment by amirh** [comment]
Duplicate of: https://github.com/flutter/flutter/issues/46898

We've published workarounds, can you try upgrading the plugins by running `flutter pub upgrade` and see if it fixes the issue?

**Comment by NTMS2017** [comment]
I download today new stable version of sdk. I run my app and my app shows only splash screen and can't run further.


```
E/flutter ( 8701): 
✓ Built build/app/outputs/apk/debug/app-debug.apk.
Installing build/app/outputs/apk/app.apk...
Syncing files to device Android SDK built for x86...
E/flutter ( 8888): [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: ServicesBinding.defaultBinaryMessenger was accessed before the binding was initialized.
E/flutter ( 8888): If you're running an application and need to access the binary messenger before `runApp()` has been called (for example, during plugin initialization), then you need to explicitly call the `WidgetsFlutterBinding.ensureInitialized()` first.
E/flutter ( 8888): If you're running a test, you can call the `TestWidgetsFlutterBinding.ensureInitialized()` as the first line in your test's `main()` method to initialize the binding.
E/flutter ( 8888): #0      defaultBinaryMessenger.<anonymous closure> (package:flutter/src/services/binary_messenger.dart:76:7)
E/flutter ( 8888): #1      defaultBinaryMessenger (package:flutter/src/services/binary_messenger.dart:89:4)
E/flutter ( 8888): #2      MethodChannel.binaryMessenger (package:flutter/src/services/platform_channel.dart:140:62)
E/flutter ( 8888): #3      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:314:35)
E/flutter ( 8888): #4      OptionalMethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:429:36)
E/flutter ( 8888): #5      SystemChrome.setEnabledSystemUIOverlays (package:flutter/src/services/system_chrome.dart:280:35)
E/flutter ( 8888): #6      main (package:capital_cep/main.dart:34:22)
E/flutter ( 8888): #7      _runMainZoned.<anonymous closure>.<anonymous closure> (dart:ui/hooks.dart:239:25)
E/flutter ( 8888): #8      _rootRun (dart:async/zone.dart:1126:13)
E/flutter ( 8888): #9      _CustomZone.run (dart:async/zone.dart:1023:19)
E/flutter ( 8888): #10     _runZoned (dart:async/zone.dart:1518:10)
E/flutter ( 8888): #11     runZoned (dart:async/zone.dart:1502:12)
E/flutter ( 8888): #12     _runMainZoned.<anonymous closure> (dart:ui/hooks.dart:231:5)
E/flutter ( 8888): #13     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:307:19)
E/flutter ( 8888): #14     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:174:12)
E/flutter ( 8888): 
Error -32601 received from application: Method not found
Application finished.
```


**flutter doctor -v**
```
[✓] Flutter (Channel stable, v1.12.13+hotfix.5, on Mac OS X 10.15.2 19C57, locale en-CY)
    • Flutter version 1.12.13+hotfix.5 at /Users/********/flutter
    • Framework revision 27321ebbad (3 days ago), 2019-12-10 18:15:01 -0800
    • Engine revision 2994f7e1e6
    • Dart version 2.7.0

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/********/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.3, Build version 11C29
    • CocoaPods version 1.8.4

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 42.1.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] IntelliJ IDEA Community Edition (version 2019.3)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 41.1.5
    • Dart plugin version 193.5233.116

[✓] Connected device (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 10 (API 29) (emulator)

• No issues found!




```

**Comment by NTMS2017** [comment]
My void main is shown below. I add WidgetsFlutterBinding.ensureInitialized(); and still getting same error. I run flutter clean and Inavalidate Cashes and restart and still getting same error.


```
void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await SystemChrome.setEnabledSystemUIOverlays([]);
  await SystemChrome.setPreferredOrientations([DeviceOrientation.portraitUp]);
  runApp(new CapitalApp());
}
```

**Comment by iapicca** [comment]
Hi @NTMS2017 
does the proposed [solution ](https://github.com/flutter/flutter/issues/46767#issuecomment-565533292)works for you?
thank you

**Comment by NTMS2017** [comment]
yes @iapicca solution worked for me, thanks
