### ISSUE TITLE
[tool_crash] NoSuchMethodError: The getter 'port' was called on null.Receiver: nullTried calling: port

### ISSUE THREAD

**Issue by NexisHunter** [flutter/flutter#46914]
## Command
  ```
  flutter run --machine --target lib/main.dart -d chrome --track-widget-creation --start-paused
  ```

  ## Steps to Reproduce
  1. Run default debug action in vs code (Flutter is defaulted)

  ## Logs
  NoSuchMethodError: NoSuchMethodError: The getter 'port' was called on null.
Receiver: null
Tried calling: port
  ```
  #0      Object.noSuchMethod (dart:core-patch/object_patch.dart:53:5)
#1      AppDomain.launch.<anonymous closure> (package:flutter_tools/src/commands/daemon.dart:573:54)
#2      _rootRunUnary (dart:async/zone.dart:1134:38)
#3      _CustomZone.runUnary (dart:async/zone.dart:1031:19)
#4      _FutureListener.handleValue (dart:async/future_impl.dart:140:18)
#5      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:682:45)
#6      Future._propagateToListeners (dart:async/future_impl.dart:711:32)
#7      Future._completeWithValue (dart:async/future_impl.dart:526:5)
#8      Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:556:7)
#9      _rootRun (dart:async/zone.dart:1126:13)
#10     _CustomZone.run (dart:async/zone.dart:1023:19)
#11     _CustomZone.runGuarded (dart:async/zone.dart:925:7)
#12     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:965:23)
#13     _microtaskLoop (dart:async/schedule_microtask.dart:43:21)
#14     _startMicrotaskLoop (dart:async/schedule_microtask.dart:52:5)
#15     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
#16     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:175:5)
  ```
  ```
  [✓] Flutter (Channel master, v1.13.2-pre.19, on Linux, locale en_CA.UTF-8)
    • Flutter version 1.13.2-pre.19 at /home/nexis/.local/sdks/flutter
    • Framework revision 8ca55605c8 (31 minutes ago), 2019-12-12 13:55:42 -0800
    • Engine revision 12bf95fd49
    • Dart version 2.7.0 (build 2.7.0-dev.2.1 8b8894648f)

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /home/nexis/Android/Sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /home/nexis/.local/share/JetBrains/Toolbox/apps/AndroidStudio/ch-0/191.6010548/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Linux toolchain - develop for Linux desktop
    • clang++ 9.0.0
    • GNU Make 4.2.1

[!] Android Studio (version 3.5)
    • Android Studio at /home/nexis/.local/share/JetBrains/Toolbox/apps/AndroidStudio/ch-0/191.6010548
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] Connected device (3 available)
    • Linux      • Linux      • linux-x64      • Linux
    • Chrome     • chrome     • web-javascript • Google Chrome 79.0.3945.79
    • Web Server • web-server • web-javascript • Flutter Tools

! Doctor found issues in 1 category.

  ```

  ## Flutter Application Metadata
  **Version**: 1.0.0+1
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
### Plugins
path_providerurl_launcherurl_launcher_macosurl_launcher_web

The application launches, but the debugger drops the connection.

**Comment by Mravuri96** [comment]
Getting this same error. after doing 
``` 
flutter config --enable-web-incremental-compiler; 
```

Doing 
```
flutter config --no-enable-web-incremental-compiler; 
```
fixes this.

**Comment by jonahwilliams** [comment]
If you have the experimental compiler enabled, I recommend disabling it if you want debugging support

**Comment by NexisHunter** [comment]
I don't have it enabled, unfortunately.

**Comment by NexisHunter** [comment]
If that is something that is turned on automatically, that should be displayed/changed so that consumers are aware of the option being on.

**Comment by jonahwilliams** [comment]
The setting is not turned on automatically

**Comment by NexisHunter** [comment]
> The setting is not turned on automatically

Hmm ok, then I'm not 100% sure as to why it was turned on. But thanks for the assist everyone :smile:
