### ISSUE TITLE
hot-reload crashed when there are ffi/native codes

### ISSUE THREAD

**Issue by zjw1918** [flutter/flutter#46935]
First run ok, but when I edit something like 
```
   setState(() {
      _counter += 1; // edit this to _counter += 10;
    });
```
Then enter `r` or `R`, it crashed.

flutter doctor
```
[✓] Flutter (Channel stable, v1.12.13+hotfix.5, on Mac OS X 10.15 19A583, locale
    zh-Hans-CN)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 11.2.1)
[✓] Android Studio (version 3.5)
[✓] VS Code (version 1.41.0)
[✓] Connected device (1 available)
```

some codes:
```
class _MyHomePageState extends State<MyHomePage> {
  int _counter = 0;
  void _incrementCounter() {
    // It won't crash if I comment these 3 lines out
    Pointer<Utf8> name = Utf8.toUtf8('hello world'); 
    Pointer<Stu> s1 = createStu(name, 10, 99);
    print('stu: ${s1.ref.name.ref} ${s1.ref.height} ${s1.ref.weight}');

    setState(() {
      _counter += 1;
    });
  }
```

```
import 'dart:ffi';
import 'dart:io';
import 'dart:typed_data';
import 'package:ffi/ffi.dart';

class Stu extends Struct {
  Pointer<Utf8> name;

  @Int32()
  int height;

  @Int32()
  int weight;

  factory Stu.allocate(Pointer<Utf8> name, int height, int weight) =>
      allocate<Stu>().ref
        ..name = name
        ..height = height
        ..weight = weight;

  @override
  String toString() {
    return 'height: $height, weight: $weight';
  }
}
```

logs:
```
Unhandled exception:                                                    
Crash when compiling                                                    
file:///Users/xxx/demo/lib/main.dart,
at character offset 777:                                                
NoSuchMethodError: The getter 'typeParameters' was called on null.      
Receiver: null                                                          
Tried calling: typeParameters                                           
#0      TypeInferrerImpl.getGetterTypeForMemberTarget                   
(package:front_end/src/fasta/type_inference/type_inferrer.dart:1007:21)
#1      TypeInferrerImpl.getGetterType                                  
(package:front_end/src/fasta/type_inference/type_inferrer.dart:948:16)
#2      InferenceVisitor._computePropertyGet                            
(package:front_end/src/fasta/kernel/inference_visitor.dart:3682:34)
#3      InferenceVisitor.visitPropertyGet                               
(package:front_end/src/fasta/kernel/inference_visitor.dart:4578:44)
#4      PropertyGet.accept1 (package:kernel/ast.dart:2742:9)            
#5      TypeInferrerImpl.inferExpression                                
(package:front_end/src/fasta/type_inference/type_inferrer.dart:1477:27)
#6      InferenceVisitor.visitStringConcatenation                       
(package:front_end/src/fasta/kernel/inference_visitor.dart:4777:53)
#7      StringConcatenation.accept1 (package:kernel/ast.dart:3661:9)    
#8      TypeInferrerImpl.inferExpression                                
(package:front_end/src/fasta/type_inference/type_inferrer.dart:1477:27)
#9      TypeInferrerImpl._inferInvocation                               
(package:front_end/src/fasta/type_inference/type_inferrer.dart:1726:44)
#10     TypeInferrerImpl.inferInvocation                                
(package:front_end/src/fasta/type_inference/type_inferrer.dart:1562:12)
#11     InferenceVisitor.visitStaticInvocation                          
(package:front_end/src/fasta/kernel/inference_visitor.dart:4760:38)
#12     StaticInvocation.accept1 (package:kernel/ast.dart:3415:9)       
#13     TypeInferrerImpl.inferExpression                                
(package:front_end/src/fasta/type_inference/type_inferrer.dart:1477:27)
#14     InferenceVisitor.visitExpressionStatement                       
(package:front_end/src/fasta/kernel/inference_visitor.dart:726:49)
#15     ExpressionStatement.accept (package:kernel/ast.dart:4491:43)    
#16     TypeInferrerImpl.inferStatement                                 
(package:front_end/src/fasta/type_inference/type_inferrer.dart:2646:22)
#17     InferenceVisitor._visitStatements                               
(package:front_end/src/fasta/kernel/inference_visitor.dart:306:20)
#18     InferenceVisitor.visitBlock                                     
(package:front_end/src/fasta/kernel/inference_visitor.dart:327:30)
#19     Block.accept (package:kernel/ast.dart:4519:43)                  
#20     TypeInferrerImpl.inferStatement                                 
(package:front_end/src/fasta/type_inference/type_inferrer.dart:2646:22)
#21     TypeInferrerImpl.inferFunctionBody                              
(package:front_end/src/fasta/type_inference/type_inferrer.dart:1525:39)
#22     BodyBuilder.finishFunction                                      
(package:front_end/src/fasta/kernel/body_builder.dart:910:28)
#23     DietListener.listenerFinishFunction                             
(package:front_end/src/fasta/source/diet_listener.dart:904:14)
#24     DietListener.buildFunctionBody                                  
(package:front_end/src/fasta/source/diet_listener.dart:937:7)
#25     DietListener.endClassMethod                                     
(package:front_end/src/fasta/source/diet_listener.dart:664:5)
#26     Parser.parseMethod                                              
(package:_fe_analyzer_shared/src/parser/parser_impl.dart:3480:20)
#27     Parser.parseClassOrMixinOrExtensionMemberImpl                   
(package:_fe_analyzer_shared/src/parser/parser_impl.dart:3241:15)
#28     Parser.parseClassOrMixinOrExtensionBody                         
(package:_fe_analyzer_shared/src/parser/parser_impl.dart:2974:15)
#29     Parser.parseClass                                               
(package:_fe_analyzer_shared/src/parser/parser_impl.dart:1820:13)
#30     Parser.parseClassOrNamedMixinApplication                        
(package:_fe_analyzer_shared/src/parser/parser_impl.dart:1779:14)
#31     Parser.parseTopLevelKeywordDeclaration                          
(package:_fe_analyzer_shared/src/parser/parser_impl.dart:574:14)
#32     Parser.parseTopLevelDeclarationImpl                             
(package:_fe_analyzer_shared/src/parser/parser_impl.dart:470:14)
#33     Parser.parseUnit                                                
(package:_fe_analyzer_shared/src/parser/parser_impl.dart:352:15)
#34     SourceLoader.buildBody                                          
(package:front_end/src/fasta/source/source_loader.dart:312:14)
<asynchronous suspension>                                               
#35     Loader.buildBodies (package:front_end/src/fasta/loader.dart:243:15)
#36     KernelTarget.buildComponent.<anonymous closure>                 
(package:front_end/src/fasta/kernel/kernel_target.dart:307:20)
#37     withCrashReporting (package:front_end/src/fasta/crash.dart:122:24)
#38     KernelTarget.buildComponent                                     
(package:front_end/src/fasta/kernel/kernel_target.dart:305:12)
#39     IncrementalCompiler.computeDelta.<anonymous closure>            
(package:front_end/src/fasta/incremental_compiler.dart:483:28)
<asynchronous suspension>                                               
#40     CompilerContext.runInContext.<anonymous closure>.<anonymous closure>
(package:front_end/src/fasta/compiler_context.dart:123:46)
#41     new Future.sync (dart:async/future.dart:224:31)                 
#42     CompilerContext.runInContext.<anonymous closure>                
(package:front_end/src/fasta/compiler_context.dart:123:19)
#43     _rootRun (dart:async/zone.dart:1126:13)                         
#44     _CustomZone.run (dart:async/zone.dart:1023:19)                  
#45     _runZoned (dart:async/zone.dart:1518:10)                        
#46     runZoned (dart:async/zone.dart:1465:12)                         
#47     CompilerContext.runInContext                                    
(package:front_end/src/fasta/compiler_context.dart:122:12)
#48     IncrementalCompiler.computeDelta                                
(package:front_end/src/fasta/incremental_compiler.dart:156:20)
#49     IncrementalCompiler.compile (package:vm/incremental_compiler.dart:58:46)
#50     FrontendCompiler.recompileDelta                                 
(package:frontend_server/frontend_server.dart:780:47)
<asynchronous suspension>                                               
#51     _FlutterFrontendCompiler.recompileDelta                         
(package:flutter_frontend_server/server.dart:43:22)
#52     listenAndCompile.<anonymous closure>                            
(package:frontend_server/frontend_server.dart:1070:20)
#53     _RootZone.runUnaryGuarded (dart:async/zone.dart:1316:10)        
#54     _BufferingStreamSubscription._sendData                          
(dart:async/stream_impl.dart:338:11)
#55     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:265:7)
#56     _SinkTransformerStreamSubscription._add                         
(dart:async/stream_transformers.dart:70:11)
#57     _EventSinkWrapper.add (dart:async/stream_transformers.dart:17:11)
#58     _StringAdapterSink.add (dart:convert/string_conversion.dart:238:11)
#59     _LineSplitterSink._addLines (dart:convert/line_splitter.dart:152:13)
#60     _LineSplitterSink.addSlice (dart:convert/line_splitter.dart:127:5)
#61     StringConversionSinkMixin.add                                   
(dart:convert/string_conversion.dart:165:5)
#62     _SinkTransformerStreamSubscription._handleData                  
(dart:async/stream_transformers.dart:122:24)
#63     _RootZone.runUnaryGuarded (dart:async/zone.dart:1316:10)        
#64     _BufferingStreamSubscription._sendData                          
(dart:async/stream_impl.dart:338:11)
#65     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:265:7)
#66     _SinkTransformerStreamSubscription._add                         
(dart:async/stream_transformers.dart:70:11)
#67     _EventSinkWrapper.add (dart:async/stream_transformers.dart:17:11)
#68     _StringAdapterSink.add (dart:convert/string_conversion.dart:238:11)
#69     _StringAdapterSink.addSlice (dart:convert/string_conversion.dart:243:7)
#70     _Utf8ConversionSink.addSlice                                    
(dart:convert/string_conversion.dart:314:20)
#71     _Utf8ConversionSink.add (dart:convert/string_conversion.dart:307:5)
#72     _ConverterStreamEventSink.add                                   
(dart:convert/chunked_conversion.dart:74:18)
#73     _SinkTransformerStreamSubscription._handleData                  
(dart:async/stream_transformers.dart:122:24)
#74     _RootZone.runUnaryGuarded (dart:async/zone.dart:1316:10)        
#75     _BufferingStreamSubscription._sendData                          
(dart:async/stream_impl.dart:338:11)
#76     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:265:7)
#77     _SyncStreamControllerDispatch._sendData                         
(dart:async/stream_controller.dart:766:19)
#78     _StreamController._add (dart:async/stream_controller.dart:642:7)
#79     _StreamController.add (dart:async/stream_controller.dart:588:5) 
#80     _Socket._onData (dart:io-patch/socket_patch.dart:1831:41)       
#81     _RootZone.runUnaryGuarded (dart:async/zone.dart:1316:10)        
#82     _BufferingStreamSubscription._sendData                          
(dart:async/stream_impl.dart:338:11)
#83     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:265:7)
#84     _SyncStreamControllerDispatch._sendData                         
(dart:async/stream_controller.dart:766:19)
#85     _StreamController._add (dart:async/stream_controller.dart:642:7)
#86     _StreamController.add (dart:async/stream_controller.dart:588:5) 
#87     new _RawSocket.<anonymous closure>                              
(dart:io-patch/socket_patch.dart:1379:33)
#88     _NativeSocket.issueReadEvent.issue                              
(dart:io-patch/socket_patch.dart:899:14)
#89     _microtaskLoop (dart:async/schedule_microtask.dart:43:21)       
#90     _startMicrotaskLoop (dart:async/schedule_microtask.dart:52:5)   
#91     _runPendingImmediateCallback                                    
(dart:isolate-patch/isolate_patch.dart:118:13)
#92     _RawReceivePortImpl._handleMessage                              
(dart:isolate-patch/isolate_patch.dart:175:5)
                                                                        
                                                                        
#0      DietListener.buildFunctionBody                                  
(package:front_end/src/fasta/source/diet_listener.dart:942:7)
#1      DietListener.endClassMethod                                     
(package:front_end/src/fasta/source/diet_listener.dart:664:5)
#2      Parser.parseMethod                                              
(package:_fe_analyzer_shared/src/parser/parser_impl.dart:3480:20)
#3      Parser.parseClassOrMixinOrExtensionMemberImpl                   
(package:_fe_analyzer_shared/src/parser/parser_impl.dart:3241:15)
#4      Parser.parseClassOrMixinOrExtensionBody                         
(package:_fe_analyzer_shared/src/parser/parser_impl.dart:2974:15)
#5      Parser.parseClass                                               
(package:_fe_analyzer_shared/src/parser/parser_impl.dart:1820:13)
#6      Parser.parseClassOrNamedMixinApplication                        
(package:_fe_analyzer_shared/src/parser/parser_impl.dart:1779:14)
#7      Parser.parseTopLevelKeywordDeclaration                          
(package:_fe_analyzer_shared/src/parser/parser_impl.dart:574:14)
#8      Parser.parseTopLevelDeclarationImpl                             
(package:_fe_analyzer_shared/src/parser/parser_impl.dart:470:14)
#9      Parser.parseUnit                                                
(package:_fe_analyzer_shared/src/parser/parser_impl.dart:352:15)
#10     SourceLoader.buildBody                                          
(package:front_end/src/fasta/source/source_loader.dart:312:14)
<asynchronous suspension>                                               
#11     Loader.buildBodies (package:front_end/src/fasta/loader.dart:243:15)
#12     KernelTarget.buildComponent.<anonymous closure>                 
(package:front_end/src/fasta/kernel/kernel_target.dart:307:20)
#13     withCrashReporting (package:front_end/src/fasta/crash.dart:122:24)
#14     KernelTarget.buildComponent                                     
(package:front_end/src/fasta/kernel/kernel_target.dart:305:12)
#15     IncrementalCompiler.computeDelta.<anonymous closure>            
(package:front_end/src/fasta/incremental_compiler.dart:483:28)
<asynchronous suspension>                                               
#16     CompilerContext.runInContext.<anonymous closure>.<anonymous closure>
(package:front_end/src/fasta/compiler_context.dart:123:46)
#17     new Future.sync (dart:async/future.dart:224:31)                 
#18     CompilerContext.runInContext.<anonymous closure>                
(package:front_end/src/fasta/compiler_context.dart:123:19)
#19     _rootRun (dart:async/zone.dart:1126:13)                         
#20     _CustomZone.run (dart:async/zone.dart:1023:19)                  
#21     _runZoned (dart:async/zone.dart:1518:10)                        
#22     runZoned (dart:async/zone.dart:1465:12)                         
#23     CompilerContext.runInContext                                    
(package:front_end/src/fasta/compiler_context.dart:122:12)
#24     IncrementalCompiler.computeDelta                                
(package:front_end/src/fasta/incremental_compiler.dart:156:20)
#25     IncrementalCompiler.compile (package:vm/incremental_compiler.dart:58:46)
#26     FrontendCompiler.recompileDelta                                 
(package:frontend_server/frontend_server.dart:780:47)
<asynchronous suspension>                                               
#27     _FlutterFrontendCompiler.recompileDelta                         
(package:flutter_frontend_server/server.dart:43:22)
#28     listenAndCompile.<anonymous closure>                            
(package:frontend_server/frontend_server.dart:1070:20)
#29     _RootZone.runUnaryGuarded (dart:async/zone.dart:1316:10)        
#30     _BufferingStreamSubscription._sendData                          
(dart:async/stream_impl.dart:338:11)
#31     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:265:7)
#32     _SinkTransformerStreamSubscription._add                         
(dart:async/stream_transformers.dart:70:11)
#33     _EventSinkWrapper.add (dart:async/stream_transformers.dart:17:11)
#34     _StringAdapterSink.add (dart:convert/string_conversion.dart:238:11)
#35     _LineSplitterSink._addLines (dart:convert/line_splitter.dart:152:13)
#36     _LineSplitterSink.addSlice (dart:convert/line_splitter.dart:127:5)
#37     StringConversionSinkMixin.add                                   
(dart:convert/string_conversion.dart:165:5)
#38     _SinkTransformerStreamSubscription._handleData                  
(dart:async/stream_transformers.dart:122:24)
#39     _RootZone.runUnaryGuarded (dart:async/zone.dart:1316:10)        
#40     _BufferingStreamSubscription._sendData                          
(dart:async/stream_impl.dart:338:11)
#41     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:265:7)
#42     _SinkTransformerStreamSubscription._add                         
(dart:async/stream_transformers.dart:70:11)
#43     _EventSinkWrapper.add (dart:async/stream_transformers.dart:17:11)
#44     _StringAdapterSink.add (dart:convert/string_conversion.dart:238:11)
#45     _StringAdapterSink.addSlice (dart:convert/string_conversion.dart:243:7)
#46     _Utf8ConversionSink.addSlice                                    
(dart:convert/string_conversion.dart:314:20)
#47     _Utf8ConversionSink.add (dart:convert/string_conversion.dart:307:5)
#48     _ConverterStreamEventSink.add                                   
(dart:convert/chunked_conversion.dart:74:18)
#49     _SinkTransformerStreamSubscription._handleData                  
(dart:async/stream_transformers.dart:122:24)
#50     _RootZone.runUnaryGuarded (dart:async/zone.dart:1316:10)        
#51     _BufferingStreamSubscription._sendData                          
(dart:async/stream_impl.dart:338:11)
#52     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:265:7)
#53     _SyncStreamControllerDispatch._sendData                         
(dart:async/stream_controller.dart:766:19)
#54     _StreamController._add (dart:async/stream_controller.dart:642:7)
#55     _StreamController.add (dart:async/stream_controller.dart:588:5) 
#56     _Socket._onData (dart:io-patch/socket_patch.dart:1831:41)       
#57     _RootZone.runUnaryGuarded (dart:async/zone.dart:1316:10)        
#58     _BufferingStreamSubscription._sendData                          
(dart:async/stream_impl.dart:338:11)
#59     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:265:7)
#60     _SyncStreamControllerDispatch._sendData                         
(dart:async/stream_controller.dart:766:19)
#61     _StreamController._add (dart:async/stream_controller.dart:642:7)
#62     _StreamController.add (dart:async/stream_controller.dart:588:5) 
#63     new _RawSocket.<anonymous closure>                              
(dart:io-patch/socket_patch.dart:1379:33)
#64     _NativeSocket.issueReadEvent.issue                              
(dart:io-patch/socket_patch.dart:899:14)
#65     _microtaskLoop (dart:async/schedule_microtask.dart:43:21)       
#66     _startMicrotaskLoop (dart:async/schedule_microtask.dart:52:5)   
#67     _runPendingImmediateCallback                                    
(dart:isolate-patch/isolate_patch.dart:118:13)
#68     _RawReceivePortImpl._handleMessage                              
(dart:isolate-patch/isolate_patch.dart:175:5)
the Dart compiler exited unexpectedly.                                  
Initializing hot reload...                                              
Try again after fixing the above error(s).
the Dart compiler exited unexpectedly.
```

**Comment by jonahwilliams** [comment]
cc @johnniwinther @stefantsov @sjindel-google

**Comment by zjw1918** [comment]
c code:
```
typedef struct
{
    char *name;
    int height;
    int weight;
} Stu;

Stu *makeStu(char *name, int height, int weight); // a simple method
```

**Comment by dcharkes** [comment]
Related issue https://github.com/dart-lang/sdk/issues/36748.

> at character offset 777:                                                
> NoSuchMethodError: The getter 'typeParameters' was called on null.     

What is the at that character offset?

Is it a getter/setter of a struct field? If so, we're looking at https://github.com/dart-lang/sdk/issues/39840.

**Comment by zjw1918** [comment]
Almost the same.

**Comment by dcharkes** [comment]
> Almost the same.

Okay, let's wait on a fix for that issue to see if that resolves it.

**Comment by axilesoft** [comment]
Alomst same issue, it seems will "Crash when compiling" when I add a debugPrint( some ffi data ) in main.dart, but when put to other place, it will not crash...

**Comment by axilesoft** [comment]
I think I know what cause this.  May be because the dart which defines the ffi class (extends Struct) is not directly imported by the hot-reload-crash dart file.

**Comment by dcharkes** [comment]
We are aware of the issue, see https://github.com/dart-lang/sdk/issues/39840.

cc @jensjoha (assigned to that issue)

**Comment by dcharkes** [comment]
Update:

> This should have been fixed with https://github.com/dart-lang/sdk/commit/d21c4e4fa5ef8ab7e8dc1423f15c2fb1966be3e8.

_Originally posted by @jensjoha in https://github.com/dart-lang/sdk/issues/39840#issuecomment-579765236_

With the next Dart roll, this should be fixed on Flutter-master.

**Comment by chinmaygarde** [comment]
Closing as the cross-referenced issue has been fixed.
