### ISSUE TITLE
ProcessException: ProcessException: Permission denied ?

### ISSUE THREAD

**Issue by aboutmydreams** [flutter/flutter#46947]
## command

`flutter build apk --target-platform android-arm,android-arm64 --split-per-abi`

## exception

<details>
  <summary>logs</summary>

```bash

ProcessException: ProcessException: Permission denied
  Command: /Users/dengwenhao/.pub-cache/hosted/pub.flutter-io.cn/liquid_swipe-1.3.0/android/gradlew -I=/Users/dengwenhao/Library/flutter/packages/flutter_tools/gradle/aar_init_script.gradle -Pflutter-root=/Users/dengwenhao/Library/flutter -Poutput-dir=/Users/dengwenhao/Desktop/coding/project/doorapp/doorapp/build/app -Pis-plugin=true -Ptarget-platform=android-arm,android-arm64,android-x64 assembleAarRelease


#0      _DefaultProcessUtils.run (package:flutter_tools/src/base/process.dart:266:37)
<asynchronous suspension>
#1      buildGradleAar (package:flutter_tools/src/android/gradle.dart:548:33)
#2      buildPluginsAsAar (package:flutter_tools/src/android/gradle.dart:711:13)
<asynchronous suspension>
#3      buildGradleApp (package:flutter_tools/src/android/gradle.dart:257:11)
#4      _AsyncAwaitCompleter.start (dart:async-patch/async_patch.dart:45:6)
#5      buildGradleApp (package:flutter_tools/src/android/gradle.dart:218:28)
#6      buildGradleApp (package:flutter_tools/src/android/gradle.dart:415:19)
#7      _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:73:64)
#8      _rootRunUnary (dart:async/zone.dart:1134:38)
#9      _CustomZone.runUnary (dart:async/zone.dart:1031:19)
#10     _FutureListener.handleValue (dart:async/future_impl.dart:139:18)
#11     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:680:45)
#12     Future._propagateToListeners (dart:async/future_impl.dart:709:32)
#13     Future._completeWithValue (dart:async/future_impl.dart:524:5)
#14     Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:554:7)
#15     _rootRun (dart:async/zone.dart:1126:13)
#16     _CustomZone.run (dart:async/zone.dart:1023:19)
#17     _CustomZone.runGuarded (dart:async/zone.dart:925:7)
#18     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:965:23)
#19     _microtaskLoop (dart:async/schedule_microtask.dart:43:21)
#20     _startMicrotaskLoop (dart:async/schedule_microtask.dart:52:5)
#21     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
#22     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:175:5)
```
</details>

## flutter doctor

```bash
[32m[✓][39m Flutter (Channel stable, v1.12.13+hotfix.6, on Mac OS X 10.15.2 19C57, locale zh-Hans-CN)
    [32m•[39m Flutter version 1.12.13+hotfix.6 at /Users/dengwenhao/Library/flutter
    [32m•[39m Framework revision 18cd7a3601 (2 days ago), 2019-12-11 06:35:39 -0800
    [32m•[39m Engine revision 2994f7e1e6
    [32m•[39m Dart version 2.7.0

[32m[✓][39m Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    [32m•[39m Android SDK at /Users/dengwenhao/Library/Android/sdk
    [32m•[39m Android NDK location not configured (optional; useful for native profiling support)
    [32m•[39m Platform android-29, build-tools 29.0.2
    [32m•[39m ANDROID_HOME = /Users/dengwenhao/Library/Android/sdk
    [32m•[39m Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    [32m•[39m Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    [32m•[39m All Android licenses accepted.

[32m[✓][39m Xcode - develop for iOS and macOS (Xcode 11.2.1)
    [32m•[39m Xcode at /Applications/Xcode.app/Contents/Developer
    [32m•[39m Xcode 11.2.1, Build version 11B500
    [32m•[39m CocoaPods version 1.8.4

[32m[✓][39m Android Studio (version 3.5)
    [32m•[39m Android Studio at /Applications/Android Studio.app/Contents
    [32m•[39m Flutter plugin version 41.1.2
    [32m•[39m Dart plugin version 191.8593
    [32m•[39m Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[32m[✓][39m VS Code (version 1.40.2)
    [32m•[39m VS Code at /Applications/Visual Studio Code.app/Contents
    [32m•[39m Flutter extension version 3.7.1

[32m[✓][39m Connected device (1 available)
    [32m•[39m iPhone 11 Pro Max • F6E771FC-3AE3-4621-894E-3490EAB0604F • ios •
      com.apple.CoreSimulator.SimRuntime.iOS-13-2 (simulator)

[32m•[39m No issues found!
```

```bash
cmd:
git:(master) ✗ flutter build apk --target-platform android-arm,android-arm64 --split-per-abi
注: /Users/dengwenhao/.pub-cache/hosted/pub.flutter-io.cn/fluttertoast-3.0.4/android/src/main/java/io/github/ponnamkarthik/toast/fluttertoast/FluttertoastPlugin.java使用或覆盖了已过时的 API。
注: 有关详细信息, 请使用 -Xlint:deprecation 重新编译。                  
注: 某些输入文件使用或覆盖了已过时的 API。                              
注: 有关详细信息, 请使用 -Xlint:deprecation 重新编译。                  
注: 某些输入文件使用或覆盖了已过时的 API。                              
注: 有关详细信息, 请使用 -Xlint:deprecation 重新编译。                  
Removed unused resources: Binary resource data reduced from 80KB to 67KB: Removed 16%
Removed unused resources: Binary resource data reduced from 80KB to 67KB: Removed 16%
                                                                        
FAILURE: Build failed with an exception.                                
                                                                        
* What went wrong:                                                      
Execution failed for task ':shared_preferences:verifyReleaseResources'. 
> java.util.concurrent.ExecutionException: com.android.builder.internal.aapt.v2.Aapt2Exception: Android resource linking failed
  Output:  /Users/dengwenhao/Desktop/coding/project/doorapp/doorapp/build/shared_preferences/intermediates/res/merged/release/values/values.xml:186: error: resource android:attr/fontVariationSettings not found.
  /Users/dengwenhao/Desktop/coding/project/doorapp/doorapp/build/shared_preferences/intermediates/res/merged/release/values/values.xml:187: error: resource android:attr/ttcIndex not found.
  error: failed linking references.                                     
                                                                        
  Command: /Users/dengwenhao/.gradle/caches/transforms-1/files-1.1/aapt2-3.2.1-4818971-osx.jar/067c550bab45744a730d55ac6d07bb79/aapt2-3.2.1-4818971-osx/aapt2 link -I\
          /Users/dengwenhao/Library/Android/sdk/platforms/android-27/android.jar\
          --manifest\                                                   
          /Users/dengwenhao/Desktop/coding/project/doorapp/doorapp/build/shared_preferences/intermediates/aapt_friendly_merged_manifests/release/processReleaseManifest/aapt/AndroidManifest.xml\
          -o\                                                           
          /var/folders/h4/94xy6zt91b199zlxqmnwtf880000gn/T/aapt-5036295586410791987-out\
          -R\                                                           
          /Users/dengwenhao/Desktop/coding/project/doorapp/doorapp/build/shared_preferences/intermediates/res/compiled/release/layout_notification_action_tombstone.xml.flat\
          -R\                                                           
          /Users/dengwenhao/Desktop/coding/project/doorapp/doorapp/build/shared_preferences/intermediates/res/compiled/release/values-ur_values-ur.arsc.flat\
          -R\                                                           
          /Users/dengwenhao/Desktop/coding/project/doorapp/doorapp/build/shared_preferences/intermediates/res/compiled/release/drawable_notification_icon_background.xml.flat\
          -R\                                                           
          /Users/dengwenhao/Desktop/coding/project/doorapp/doorapp/build/shared_preferences/intermediates/res/compiled/release/values-pa_values-pa.arsc.flat\
          -R\                                                           
          /Users/dengwenhao/Desktop/coding/project/doorapp/doorapp/build/shared_preferences/intermediates/res/compiled/release/values-pt-rBR_values-pt-rBR.arsc.flat\
          -R\                                                           
          /Users/dengwenhao/Desktop/coding/project/doorapp/doorapp/build/shared_preferences/intermediates/res/compiled/release/values-as_values-as.arsc.flat\
          -R\                                                           
          /Users/dengwenhao/Desktop/coding/project/doorapp/doorapp/build/shared_preferences/intermediates/res/compiled/release/values-fi_values-fi.arsc.flat\
          -R\                                                           
          /Users/dengwenhao/Desktop/coding/project/doorapp/doorapp/build/shared_preferences/intermediates/res/compiled/release/values-uk_values-uk.arsc.flat\
          -R\                                                           
          /Users/dengwenhao/Desktop/coding/project/doorapp/doorapp/build/shared_preferences/intermediates/res/compiled/release/layout_notification_template_part_time.xml.flat\
          -R\                                                           
          /Users/dengwenhao/Desktop/coding/project/doorapp/doorapp/build/shared_preferences/intermediates/res/compiled/release/values-ka_values-ka.arsc.flat\
          -R\                                                           
          /Users/dengwenhao/Desktop/coding/project/doorapp/doorapp/build/shared_preferences/intermediates/res/compiled/release/values-iw_values-iw.arsc.flat\
          -R\                                                           
          /Users/dengwenhao/Desktop/coding/project/doorapp/doorapp/build/shared_preferences/intermediates/res/compiled/release/drawable-mdpi-v4_notify_panel_notification_icon_bg.png.flat\
          -R\                                                           
          /Users/dengwenhao/Desktop/coding/project/doorapp/doorapp/build/shared_preferences/intermediates/res/compiled/release/values-bs_values-bs.arsc.flat\
          -R\                                                           
          /Users/dengwenhao/Desktop/coding/project/doorapp/doorapp/build/shared_preferences/intermediates/res/compiled/release/values-mk_values-mk.arsc.flat\
          -R\                                                           
          /Users/dengwenhao/Desktop/coding/project/doorapp/doorapp/build/shared_preferences/intermediates/res/compiled/release/drawable_notification_bg_low.xml.flat\
          -R\                                                           
          /Users/dengwenhao/Desktop/coding/project/doorapp/doorapp/build/shared_preferences/intermediates/res/compiled/release/values-in_values-in.arsc.flat\
          -R\                                                           
          /Users/dengwenhao/Desktop/coding/project/doorapp/doorapp/build/shared_preferences/intermediates/res/compiled/release/values-zu_values-zu.arsc.flat\
          -R\                                                           
          /Users/dengwenhao/Desktop/coding/project/doorapp/doorapp/build/shared_preferences/intermediates/res/compiled/release/values-mr_values-mr.arsc.flat\
          -R\                                                           
          /Users/dengwenhao/Desktop/coding/project/doorapp/doorapp/build/shared_preferences/intermediates/res/compiled/release/drawable-xhdpi-v4_notification_bg_low_normal.9.png.flat\
          -R\                                                           
          /Users/dengwenhao/Desktop/coding/project/doorapp/doorapp/build/shared_preferences/intermediates/res/compiled/release/values-hr_values-hr.arsc.flat\
          -R\                                                           
          /Users/dengwenhao/Desktop/coding/project/doorapp/doorapp/build/shared_preferences/intermediates/res/compiled/release/values-en-rAU_values-en-rAU.arsc.flat\
          -R\                                                           
          /Users/dengwenhao/Desktop/coding/project/doorapp/doorapp/build/shared_preferences/intermediates/res/compiled/release/values-sk_values-sk.arsc.flat\
          -R\                                                           
          /Users/dengwenhao/Desktop/coding/project/doorapp/doorapp/build/shared_preferences/intermediates/res/compiled/release/layout_notification_action.xml.flat\
          -R\                                                           
          /Users/dengwenhao/Desktop/coding/project/doorapp/doorapp/build/shared_preferences/intermediates/res/compiled/release/drawable-v21_notification_action_background.xml.flat\
          -R\                                                           
          /Users/dengwenhao/Desktop/coding/project/doorapp/doorapp/build/shared_preferences/intermediates/res/compiled/release/values-th_values-th.arsc.flat\
          -R\                                                           
          /Users/dengwenhao/Desktop/coding/project/doorapp/doorapp/build/shared_preferences/intermediates/res/compiled/release/values-sr_values-sr.arsc.flat\
          -R\                                                           
          /Users/dengwenhao/Desktop/coding/project/doorapp/doorapp/build/shared_preferences/intermediates/res/compiled/release/values-km_values-km.arsc.flat\
          -R\                                                           
          /Users/dengwenhao/Desktop/coding/project/doorapp/doorapp/build/shared_preferences/intermediates/res/compiled/release/values-af_values-af.arsc.flat\
          -R\                                                           
          /Users/dengwenhao/Desktop/coding/project/doorapp/doorapp/build/shared_preferences/intermediates/res/compiled/release/values-pt_values-pt.arsc.flat\
          -R\                                                           
          /Users/dengwenhao/Desktop/coding/project/doorapp/doorapp/build/shared_preferences/intermediates/res/compiled/release/values-es-rUS_values-es-rUS.arsc.flat\
          -R\                                                           
          /Users/dengwenhao/Desktop/coding/project/doorapp/doorapp/build/shared_preferences/intermediates/res/compiled/release/values-fr-rCA_values-fr-rCA.arsc.flat\
          -R\                                                           
          /Users/dengwenhao/Desktop/coding/project/doorapp/doorapp/build/shared_preferences/intermediates/res/compiled/release/values-gl_values-gl.arsc.flat\
          -R\                                                           
          /Users/dengwenhao/Desktop/coding/project/doorapp/doorapp/build/shared_preferences/intermediates/res/compiled/release/layout-v21_notification_action_tombstone.xml.flat\
          -R\                                                           
          /Users/dengwenhao/Desktop/coding/project/doorapp/doorapp/build/shared_preferences/intermediates/res/compiled/release/values-gu_values-gu.arsc.flat\
          -R\                                                           
          /Users/dengwenhao/Desktop/coding/project/doorapp/doorapp/build/shared_preferences/intermediates/res/compiled/release/values-kk_values-kk.arsc.flat\
          -R\                                                           
          /Users/dengwenhao/Desktop/coding/project/doorapp/doorapp/build/shared_preferences/intermediates/res/compiled/release/values-zh-rHK_values-zh-rHK.arsc.flat\
          -R\                                                           
          /Users/dengwenhao/Desktop/coding/project/doorapp/doorapp/build/shared_preferences/intermediates/res/compiled/release/values-te_values-te.arsc.flat\
          -R\                                                           
          /Users/dengwenhao/Desktop/coding/project/doorapp/doorapp/build/shared_preferences/intermediates/res/compiled/release/values-ml_values-ml.arsc.flat\
          -R\                                                           
          /Users/dengwenhao/Desktop/coding/project/doorapp/doorapp/build/shared_preferences/intermediates/res/compiled/release/values-ky_values-ky.arsc.flat\
          -R\                                                           
          /Users/dengwenhao/Desktop/coding/project/doorapp/doorapp/build/shared_preferences/intermediates/res/compiled/release/values-ar_values-ar.arsc.flat\
          -R\                                                           
          /Users/dengwenhao/Desktop/coding/project/doorapp/doorapp/build/shared_preferences/intermediates/res/compiled/release/drawable-xhdpi-v4_notify_panel_notification_icon_bg.png.flat\
          -R\                                                           
          /Users/dengwenhao/Desktop/coding/project/doorapp/doorapp/build/shared_preferences/intermediates/res/compiled/release/values-en-rIN_values-en-rIN.arsc.flat\
          -R\                                                           
          /Users/dengwenhao/Desktop/coding/project/doorapp/doorapp/build/shared_preferences/intermediates/res/compiled/release/values-da_values-da.arsc.flat\
          -R\                                                           
          /Users/dengwenhao/Desktop/coding/project/doorapp/doorapp/build/shared_preferences/intermediates/res/compiled/release/values-am_values-am.arsc.flat\
          -R\                                                           
          /Users/dengwenhao/Desktop/coding/project/doorapp/doorapp/build/shared_preferences/intermediates/res/compiled/release/values-ms_values-ms.arsc.flat\
          -R\                                                           
          /Users/dengwenhao/Desktop/coding/project/doorapp/doorapp/build/shared_preferences/intermediates/res/compiled/release/values-zh-rTW_values-zh-rTW.arsc.flat\
          -R\                                                           
          /Users/dengwenhao/Desktop/coding/project/doorapp/doorapp/build/shared_preferences/intermediates/res/compiled/release/values-en-rGB_values-en-rGB.arsc.flat\
          -R\                                                           
          /Users/dengwenhao/Desktop/coding/project/doorapp/doorapp/build/shared_preferences/intermediates/res/compiled/release/values-hy_values-hy.arsc.flat\
          -R\                                                           
          /Users/dengwenhao/Desktop/coding/project/doorapp/doorapp/build/shared_preferences/intermediates/res/compiled/release/values-zh-rCN_values-zh-rCN.arsc.flat\
          -R\                                                           
          /Users/dengwenhao/Desktop/coding/project/doorapp/doorapp/build/shared_preferences/intermediates/res/compiled/release/values-nl_values-nl.arsc.flat\
          -R\                                                           
          /Users/dengwenhao/Desktop/coding/project/doorapp/doorapp/build/shared_preferences/intermediates/res/compiled/release/layout_notification_template_part_chronometer.xml.flat\
          -R\                                                           
          /Users/dengwenhao/Desktop/coding/project/doorapp/doorapp/build/shared_preferences/intermediates/res/compiled/release/values-ro_values-ro.arsc.flat\
          -R\                                                           
          /Users/dengwenhao/Desktop/coding/project/doorapp/doorapp/build/shared_preferences/intermediates/res/compiled/release/layout-v21_notification_template_icon_group.xml.flat\
          -R\                                                           
          /Users/dengwenhao/Desktop/coding/project/doorapp/doorapp/build/shared_preferences/intermediates/res/compiled/release/values-my_values-my.arsc.flat\
          -R\                                                           
          /Users/dengwenhao/Desktop/coding/project/doorapp/doorapp/build/shared_preferences/intermediates/res/compiled/release/values-lv_values-lv.arsc.flat\
          -R\                                                           
          /Users/dengwenhao/Desktop/coding/project/doorapp/doorapp/build/shared_preferences/intermediates/res/compiled/release/values-pl_values-pl.arsc.flat\
          -R\                                                           
          /Users/dengwenhao/Desktop/coding/project/doorapp/doorapp/build/shared_preferences/intermediates/res/compiled/release/values-lo_values-lo.arsc.flat\
          -R\                                                           
          /Users/dengwenhao/Desktop/coding/project/doorapp/doorapp/build/shared_preferences/intermediates/res/compiled/release/values_values.arsc.flat\
          -R\                                                           
          /Users/dengwenhao/Desktop/coding/project/doorapp/doorapp/build/shared_preferences/intermediates/res/compiled/release/values-bg_values-bg.arsc.flat\
          -R\                                                           
          /Users/dengwenhao/Desktop/coding/project/doorapp/doorapp/build/shared_preferences/intermediates/res/compiled/release/values-sl_values-sl.arsc.flat\
          -R\                                                           
          /Users/dengwenhao/Desktop/coding/project/doorapp/doorapp/build/shared_preferences/intermediates/res/compiled/release/values-v21_values-v21.arsc.flat\
          -R\                                                           
          /Users/dengwenhao/Desktop/coding/project/doorapp/doorapp/build/shared_preferences/intermediates/res/compiled/release/values-en-rCA_values-en-rCA.arsc.flat\
          -R\                                                           
          /Users/dengwenhao/Desktop/coding/project/doorapp/doorapp/build/shared_preferences/intermediates/res/compiled/release/values-hu_values-hu.arsc.flat\
          -R\                                                           
          /Users/dengwenhao/Desktop/coding/project/doorapp/doorapp/build/shared_preferences/intermediates/res/compiled/release/values-vi_values-vi.arsc.flat\
          -R\                                                           
          /Users/dengwenhao/Desktop/coding/project/doorapp/doorapp/build/shared_preferences/intermediates/res/compiled/release/values-en-rXC_values-en-rXC.arsc.flat\
          -R\                                                           
          /Users/dengwenhao/Desktop/coding/project/doorapp/doorapp/build/shared_preferences/intermediates/res/compiled/release/values-ru_values-ru.arsc.flat\
          -R\                                                           
          /Users/dengwenhao/Desktop/coding/project/doorapp/doorapp/build/shared_preferences/intermediates/res/compiled/release/layout-v21_notification_template_custom_big.xml.flat\
          -R\                                                           
          /Users/dengwenhao/Desktop/coding/project/doorapp/doorapp/build/shared_preferences/intermediates/res/compiled/release/drawable-hdpi-v4_notification_bg_normal.9.png.flat\
          -R\                                                           
          /Users/dengwenhao/Desktop/coding/project/doorapp/doorapp/build/shared_preferences/intermediates/res/compiled/release/values-pt-rPT_values-pt-rPT.arsc.flat\
          -R\                                                           
          /Users/dengwenhao/Desktop/coding/project/doorapp/doorapp/build/shared_preferences/intermediates/res/compiled/release/values-fr_values-fr.arsc.flat\
          -R\                                                           
          /Users/dengwenhao/Desktop/coding/project/doorapp/doorapp/build/shared_preferences/intermediates/res/compiled/release/values-et_values-et.arsc.flat\
          -R\                                                           
          /Users/dengwenhao/Desktop/coding/project/doorapp/doorapp/build/shared_preferences/intermediates/res/compiled/release/values-bn_values-bn.arsc.flat\
          -R\                                                           
          /Users/dengwenhao/Desktop/coding/project/doorapp/doorapp/build/shared_preferences/intermediates/res/compiled/release/values-ca_values-ca.arsc.flat\
          -R\                                                           
          /Users/dengwenhao/Desktop/coding/project/doorapp/doorapp/build/shared_preferences/intermediates/res/compiled/release/drawable-xhdpi-v4_notification_bg_low_pressed.9.png.flat\
          -R\                                                           
          /Users/dengwenhao/Desktop/coding/project/doorapp/doorapp/build/shared_preferences/intermediates/res/compiled/release/values-is_values-is.arsc.flat\
          -R\                                                           
          /Users/dengwenhao/Desktop/coding/project/doorapp/doorapp/build/shared_preferences/intermediates/res/compiled/release/drawable-hdpi-v4_notification_bg_normal_pressed.9.png.flat\
          -R\                                                           
          /Users/dengwenhao/Desktop/coding/project/doorapp/doorapp/build/shared_preferences/intermediates/res/compiled/release/values-sv_values-sv.arsc.flat\
          -R\                                                           
          /Users/dengwenhao/Desktop/coding/project/doorapp/doorapp/build/shared_preferences/intermediates/res/compiled/release/values-tl_values-tl.arsc.flat\
          -R\                                                           
          /Users/dengwenhao/Desktop/coding/project/doorapp/doorapp/build/shared_preferences/intermediates/res/compiled/release/layout_notification_template_icon_group.xml.flat\
          -R\                                                           
          /Users/dengwenhao/Desktop/coding/project/doorapp/doorapp/build/shared_preferences/intermediates/res/compiled/release/values-fa_values-fa.arsc.flat\
          -R\                                                           
          /Users/dengwenhao/Desktop/coding/project/doorapp/doorapp/build/shared_preferences/intermediates/res/compiled/release/values-uz_values-uz.arsc.flat\
          -R\                                                           
          /Users/dengwenhao/Desktop/coding/project/doorapp/doorapp/build/shared_preferences/intermediates/res/compiled/release/values-ko_values-ko.arsc.flat\
          -R\                                                           
          /Users/dengwenhao/Desktop/coding/project/doorapp/doorapp/build/shared_preferences/intermediates/res/compiled/release/drawable-hdpi-v4_notify_panel_notification_icon_bg.png.flat\
          -R\                                                           
          /Users/dengwenhao/Desktop/coding/project/doorapp/doorapp/build/shared_preferences/intermediates/res/compiled/release/values-hi_values-hi.arsc.flat\
          -R\                                                           
          /Users/dengwenhao/Desktop/coding/project/doorapp/doorapp/build/shared_preferences/intermediates/res/compiled/release/drawable-mdpi-v4_notification_bg_normal_pressed.9.png.flat\
          -R\                                                           
          /Users/dengwenhao/Desktop/coding/project/doorapp/doorapp/build/shared_preferences/intermediates/res/compiled/release/values-b+sr+Latn_values-b+sr+Latn.arsc.flat\
          -R\                                                           
          /Users/dengwenhao/Desktop/coding/project/doorapp/doorapp/build/shared_preferences/intermediates/res/compiled/release/drawable-xhdpi-v4_notification_bg_normal.9.png.flat\
          -R\                                                           
          /Users/dengwenhao/Desktop/coding/project/doorapp/doorapp/build/shared_preferences/intermediates/res/compiled/release/values-si_values-si.arsc.flat\
          -R\                                                           
          /Users/dengwenhao/Desktop/coding/project/doorapp/doorapp/build/shared_preferences/intermediates/res/compiled/release/values-ne_values-ne.arsc.flat\
          -R\                                                           
          /Users/dengwenhao/Desktop/coding/project/doorapp/doorapp/build/shared_preferences/intermediates/res/compiled/release/values-it_values-it.arsc.flat\
          -R\                                                           
          /Users/dengwenhao/Desktop/coding/project/doorapp/doorapp/build/shared_preferences/intermediates/res/compiled/release/values-de_values-de.arsc.flat\
          -R\                                                           
          /Users/dengwenhao/Desktop/coding/project/doorapp/doorapp/build/shared_preferences/intermediates/res/compiled/release/layout-v21_notification_action.xml.flat\
          -R\                                                           
          /Users/dengwenhao/Desktop/coding/project/doorapp/doorapp/build/shared_preferences/intermediates/res/compiled/release/values-ta_values-ta.arsc.flat\
          -R\                                                           
          /Users/dengwenhao/Desktop/coding/project/doorapp/doorapp/build/shared_preferences/intermediates/res/compiled/release/values-es_values-es.arsc.flat\
          -R\                                                           
          /Users/dengwenhao/Desktop/coding/project/doorapp/doorapp/build/shared_preferences/intermediates/res/compiled/release/drawable_notification_bg.xml.flat\
          -R\                                                           
          /Users/dengwenhao/Desktop/coding/project/doorapp/doorapp/build/shared_preferences/intermediates/res/compiled/release/values-el_values-el.arsc.flat\
          -R\                                                           
          /Users/dengwenhao/Desktop/coding/project/doorapp/doorapp/build/shared_preferences/intermediates/res/compiled/release/drawable-hdpi-v4_notification_bg_low_pressed.9.png.flat\
          -R\                                                           
          /Users/dengwenhao/Desktop/coding/project/doorapp/doorapp/build/shared_preferences/intermediates/res/compiled/release/values-mn_values-mn.arsc.flat\
          -R\                                                           
          /Users/dengwenhao/Desktop/coding/project/doorapp/doorapp/build/shared_preferences/intermediates/res/compiled/release/layout-v16_notification_template_custom_big.xml.flat\
          -R\                                                           
          /Users/dengwenhao/Desktop/coding/project/doorapp/doorapp/build/shared_preferences/intermediates/res/compiled/release/values-eu_values-eu.arsc.flat\
          -R\                                                           
          /Users/dengwenhao/Desktop/coding/project/doorapp/doorapp/build/shared_preferences/intermediates/res/compiled/release/drawable_notification_tile_bg.xml.flat\
          -R\                                                           
          /Users/dengwenhao/Desktop/coding/project/doorapp/doorapp/build/shared_preferences/intermediates/res/compiled/release/values-cs_values-cs.arsc.flat\
          -R\                                                           
          /Users/dengwenhao/Desktop/coding/project/doorapp/doorapp/build/shared_preferences/intermediates/res/compiled/release/values-nb_values-nb.arsc.flat\
          -R\                                                           
          /Users/dengwenhao/Desktop/coding/project/doorapp/doorapp/build/shared_preferences/intermediates/res/compiled/release/drawable-mdpi-v4_notification_bg_low_normal.9.png.flat\
          -R\                                                           
          /Users/dengwenhao/Desktop/coding/project/doorapp/doorapp/build/shared_preferences/intermediates/res/compiled/release/values-az_values-az.arsc.flat\
          -R\                                                           
          /Users/dengwenhao/Desktop/coding/project/doorapp/doorapp/build/shared_preferences/intermediates/res/compiled/release/values-v16_values-v16.arsc.flat\
          -R\                                                           
          /Users/dengwenhao/Desktop/coding/project/doorapp/doorapp/build/shared_preferences/intermediates/res/compiled/release/values-be_values-be.arsc.flat\
          -R\                                                           
          /Users/dengwenhao/Desktop/coding/project/doorapp/doorapp/build/shared_preferences/intermediates/res/compiled/release/values-sw_values-sw.arsc.flat\
          -R\                                                           
          /Users/dengwenhao/Desktop/coding/project/doorapp/doorapp/build/shared_preferences/intermediates/res/compiled/release/drawable-mdpi-v4_notification_bg_normal.9.png.flat\
          -R\                                                           
          /Users/dengwenhao/Desktop/coding/project/doorapp/doorapp/build/shared_preferences/intermediates/res/compiled/release/values-tr_values-tr.arsc.flat\
          -R\                                                           
          /Users/dengwenhao/Desktop/coding/project/doorapp/doorapp/build/shared_preferences/intermediates/res/compiled/release/drawable-mdpi-v4_notification_bg_low_pressed.9.png.flat\
          -R\                                                           
          /Users/dengwenhao/Desktop/coding/project/doorapp/doorapp/build/shared_preferences/intermediates/res/compiled/release/values-or_values-or.arsc.flat\
          -R\                                                           
          /Users/dengwenhao/Desktop/coding/project/doorapp/doorapp/build/shared_preferences/intermediates/res/compiled/release/values-sq_values-sq.arsc.flat\
          -R\                                                           
          /Users/dengwenhao/Desktop/coding/project/doorapp/doorapp/build/shared_preferences/intermediates/res/compiled/release/values-kn_values-kn.arsc.flat\
          -R\                                                           
          /Users/dengwenhao/Desktop/coding/project/doorapp/doorapp/build/shared_preferences/intermediates/res/compiled/release/values-lt_values-lt.arsc.flat\
          -R\                                                           
          /Users/dengwenhao/Desktop/coding/project/doorapp/doorapp/build/shared_preferences/intermediates/res/compiled/release/drawable-hdpi-v4_notification_bg_low_normal.9.png.flat\
          -R\                                                           
          /Users/dengwenhao/Desktop/coding/project/doorapp/doorapp/build/shared_preferences/intermediates/res/compiled/release/values-ja_values-ja.arsc.flat\
          -R\                                                           
          /Users/dengwenhao/Desktop/coding/project/doorapp/doorapp/build/shared_preferences/intermediates/res/compiled/release/drawable-xhdpi-v4_notification_bg_normal_pressed.9.png.flat\
          --auto-add-overlay\                                           
          --non-final-ids\                                              
          -0\                                                           
          apk\                                                          
          --no-version-vectors                                          
  Daemon:  AAPT2 aapt2-3.2.1-4818971-osx Daemon #0                      
                                                                        
* Try:                                                                  
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
                                                                        
* Get more help at https://help.gradle.org                              
                                                                        
BUILD FAILED in 57s                                                     
Running Gradle task 'assembleRelease'...                                
Running Gradle task 'assembleRelease'... Done                      58.0s
The built failed likely due to AndroidX incompatibilities in a plugin. The tool is about to try
using Jetfier to solve the incompatibility.
Building plugin fluttertoast...
Running Gradle task 'assembleAarRelease'...                             
Running Gradle task 'assembleAarRelease'... Done                    1.2s
✓ Built build/app/outputs/repo.
Building plugin liquid_swipe...
Running Gradle task 'assembleAarRelease'...                             
Running Gradle task 'assembleAarRelease'... Done                    0.0s

Sending crash report to Google.
Crash report sent (report ID: f5f1eca8949d44d3)
Oops; flutter has exited unexpectedly.
Crash report written to /Users/dengwenhao/Desktop/coding/project/doorapp/doorapp/flutter_02.log;
please let us know at https://github.com/flutter/flutter/issues.

```

**Comment by agersea** [comment]
Similar error with App Settings:
ProcessException: ProcessException: Permission denied
  Command: /Users/nathanagersea/.pub-cache/hosted/pub.dartlang.org/app_settings-3.0.0+1/android/gradlew -I=/Users/nathanagersea/Development/flutter/packages/flutter_tools/gradle/aar_init_script.gradle -Pflutter-root=/Users/nathanagersea/Development/flutter -Poutput-dir=/Users/nathanagersea/Projects/myhownd/build/app -Pis-plugin=true -Ptarget-platform=android-arm,android-arm64,android-x64 assembleAarRelease

**Comment by pearlmaknun** [comment]
@agersea did it solve already? my friend get the same error

**Comment by agersea** [comment]
@pearlmaknun , yes, I found the issue with the App Availability package.  
I changed the entry in pubspec to be
`flutter_appavailability:
    git:
      url: "https://github.com/bwhiteTP/flutter_appavailability.git"
      ref: "26461d5296cd8c0a58da1d9c5f1e960643ebb323"`

Here's a link to the issues log where I found the work around:
[App Availability Issue](https://github.com/pichillilorenzo/flutter_appavailability/issues/12)

**Comment by stuartmorgan** [comment]
Is this still reproducible in current versions? If so, please provide a minimal test case.

**Comment by TahaTesser** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
