### ISSUE TITLE
i haven't touched app it was like this when i started my app by flutter create 

### ISSUE THREAD

**Issue by f12developers** [flutter/flutter#46989]
<details>
  <summary>logs</summary>

```bash 
Launching lib\main.dart on Android SDK built for x86 in debug mode...
I/flutter ( 4399): ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
I/flutter ( 4399): The following assertion was thrown building IconTheme(color: Color(0xdd000000)):
I/flutter ( 4399): Could not find a generator for route RouteSettings("/", null) in the _WidgetsAppState.
I/flutter ( 4399): Generators for routes are searched for in the following order:
I/flutter ( 4399):  1. For the "/" route, the "home" property, if non-null, is used.
I/flutter ( 4399):  2. Otherwise, the "routes" table is used, if it has an entry for the route.
I/flutter ( 4399):  3. Otherwise, onGenerateRoute is called. It should return a non-null value for any valid route not
I/flutter ( 4399): handled by "home" and "routes".
I/flutter ( 4399):  4. Finally if all else fails onUnknownRoute is called.
I/flutter ( 4399): Unfortunately, onUnknownRoute was not set.
I/flutter ( 4399):
I/flutter ( 4399): The relevant error-causing widget was:
[38;5;248mI/flutter ( 4399):   MaterialApp[39;49m
I/flutter ( 4399):
I/flutter ( 4399): When the exception was thrown, this was the stack:
[38;5;244mI/flutter ( 4399): #0      _WidgetsAppState._onUnknownRoute.<anonymous closure>[39;49m
[38;5;244mI/flutter ( 4399): #1      _WidgetsAppState._onUnknownRoute[39;49m
[38;5;244mI/flutter ( 4399): #2      NavigatorState._routeNamed[39;49m
[38;5;244mI/flutter ( 4399): #3      NavigatorState.initState[39;49m
[38;5;244mI/flutter ( 4399): #4      StatefulElement._firstBuild[39;49m
[38;5;244mI/flutter ( 4399): #5      ComponentElement.mount[39;49m
[38;5;244mI/flutter ( 4399): #6      Element.inflateWidget[39;49m
[38;5;244mI/flutter ( 4399): #7      Element.updateChild[39;49m
[38;5;244mI/flutter ( 4399): #8      ComponentElement.performRebuild[39;49m
[38;5;244mI/flutter ( 4399): #9      Element.rebuild[39;49m
[38;5;244mI/flutter ( 4399): #10     ComponentElement._firstBuild[39;49m
[38;5;244mI/flutter ( 4399): #11     ComponentElement.mount[39;49m
[38;5;244mI/flutter ( 4399): #12     Element.inflateWidget[39;49m
[38;5;244mI/flutter ( 4399): #13     Element.updateChild[39;49m
[38;5;244mI/flutter ( 4399): #14     ComponentElement.performRebuild[39;49m
[38;5;244mI/flutter ( 4399): #15     Element.rebuild[39;49m
[38;5;244mI/flutter ( 4399): #16     ComponentElement._firstBuild[39;49m
[38;5;244mI/flutter ( 4399): #17     ComponentElement.mount[39;49m
[38;5;244mI/flutter ( 4399): #18     Element.inflateWidget[39;49m
[38;5;244mI/flutter ( 4399): #19     Element.updateChild[39;49m
[38;5;244mI/flutter ( 4399): #20     ComponentElement.performRebuild[39;49m
[38;5;244mI/flutter ( 4399): #21     Element.rebuild[39;49m
[38;5;244mI/flutter ( 4399): #22     ComponentElement._firstBuild[39;49m
[38;5;244mI/flutter ( 4399): #23     ComponentElement.mount[39;49m
[38;5;244mI/flutter ( 4399): #24     Element.inflateWidget[39;49m
[38;5;244mI/flutter ( 4399): #25     Element.updateChild[39;49m
[38;5;244mI/flutter ( 4399): #26     ComponentElement.performRebuild[39;49m
[38;5;244mI/flutter ( 4399): #27     Element.rebuild[39;49m
[38;5;244mI/flutter ( 4399): #28     ComponentElement._firstBuild[39;49m
[38;5;244mI/flutter ( 4399): #29     ComponentElement.mount[39;49m
[38;5;244mI/flutter ( 4399): #30     Element.inflateWidget[39;49m
[38;5;244mI/flutter ( 4399): #31     Element.updateChild[39;49m
[38;5;244mI/flutter ( 4399): #32     ComponentElement.performRebuild[39;49m
[38;5;244mI/flutter ( 4399): #33     Element.rebuild[39;49m
[38;5;244mI/flutter ( 4399): #34     ComponentElement._firstBuild[39;49m
[38;5;244mI/flutter ( 4399): #35     ComponentElement.mount[39;49m
[38;5;244mI/flutter ( 4399): #36     Element.inflateWidget[39;49m
[38;5;244mI/flutter ( 4399): #37     Element.updateChild[39;49m
[38;5;244mI/flutter ( 4399): #38     ComponentElement.performRebuild[39;49m
[38;5;244mI/flutter ( 4399): #39     Element.rebuild[39;49m
[38;5;244mI/flutter ( 4399): #40     ComponentElement._firstBuild[39;49m
[38;5;244mI/flutter ( 4399): #41     ComponentElement.mount[39;49m
[38;5;244mI/flutter ( 4399): #42     Element.inflateWidget[39;49m
[38;5;244mI/flutter ( 4399): #43     Element.updateChild[39;49m
[38;5;244mI/flutter ( 4399): #44     ComponentElement.performRebuild[39;49m
[38;5;244mI/flutter ( 4399): #45     Element.rebuild[39;49m
[38;5;244mI/flutter ( 4399): #46     ComponentElement._firstBuild[39;49m
[38;5;244mI/flutter ( 4399): #47     StatefulElement._firstBuild[39;49m
[38;5;244mI/flutter ( 4399): #48     ComponentElement.mount[39;49m
[38;5;244mI/flutter ( 4399): #49     Element.inflateWidget[39;49m
[38;5;244mI/flutter ( 4399): #50     Element.updateChild[39;49m
[38;5;244mI/flutter ( 4399): #51     ComponentElement.performRebuild[39;49m
[38;5;244mI/flutter ( 4399): #52     Element.rebuild[39;49m
[38;5;244mI/flutter ( 4399): #53     ComponentElement._firstBuild[39;49m
[38;5;244mI/flutter ( 4399): #54     ComponentElement.mount[39;49m
[38;5;244mI/flutter ( 4399): #55     Element.inflateWidget[39;49m
[38;5;244mI/flutter ( 4399): #56     Element.updateChild[39;49m
[38;5;244mI/flutter ( 4399): #57     ComponentElement.performRebuild[39;49m
[38;5;244mI/flutter ( 4399): #58     Element.rebuild[39;49m
[38;5;244mI/flutter ( 4399): #59     ComponentElement._firstBuild[39;49m
[38;5;244mI/flutter ( 4399): #60     ComponentElement.mount[39;49m
[38;5;244mI/flutter ( 4399): #61     Element.inflateWidget[39;49m
[38;5;244mI/flutter ( 4399): #62     Element.updateChild[39;49m
[38;5;244mI/flutter ( 4399): #63     SingleChildRenderObjectElement.mount[39;49m
[38;5;244mI/flutter ( 4399): #64     Element.inflateWidget[39;49m
[38;5;244mI/flutter ( 4399): #65     Element.updateChild[39;49m
[38;5;244mI/flutter ( 4399): #66     ComponentElement.performRebuild[39;49m
[38;5;244mI/flutter ( 4399): #67     Element.rebuild[39;49m
[38;5;244mI/flutter ( 4399): #68     ComponentElement._firstBuild[39;49m
[38;5;244mI/flutter ( 4399): #69     ComponentElement.mount[39;49m
[38;5;244mI/flutter ( 4399): #70     Element.inflateWidget[39;49m
[38;5;244mI/flutter ( 4399): #71     Element.updateChild[39;49m
[38;5;244mI/flutter ( 4399): #72     ComponentElement.performRebuild[39;49m
[38;5;244mI/flutter ( 4399): #73     Element.rebuild[39;49m
[38;5;244mI/flutter ( 4399): #74     ComponentElement._firstBuild[39;49m
[38;5;244mI/flutter ( 4399): #75     ComponentElement.mount[39;49m
[38;5;244mI/flutter ( 4399): #76     Element.inflateWidget[39;49m
[38;5;244mI/flutter ( 4399): #77     Element.updateChild[39;49m
[38;5;244mI/flutter ( 4399): #78     ComponentElement.performRebuild[39;49m
[38;5;244mI/flutter ( 4399): #79     Element.rebuild[39;49m
[38;5;244mI/flutter ( 4399): #80     ComponentElement._firstBuild[39;49m
[38;5;244mI/flutter ( 4399): #81     ComponentElement.mount[39;49m
[38;5;244mI/flutter ( 4399): #82     Element.inflateWidget[39;49m
[38;5;244mI/flutter ( 4399): #83     Element.updateChild[39;49m
[38;5;244mI/flutter ( 4399): #84     ComponentElement.performRebuild[39;49m
[38;5;244mI/flutter ( 4399): #85     Element.rebuild[39;49m
[38;5;244mI/flutter ( 4399): #86     ComponentElement._firstBuild[39;49m
[38;5;244mI/flutter ( 4399): #87     ComponentElement.mount[39;49m
[38;5;244mI/flutter ( 4399): #88     Element.inflateWidget[39;49m
[38;5;244mI/flutter ( 4399): #89     Element.updateChild[39;49m
[38;5;244mI/flutter ( 4399): #90     ComponentElement.performRebuild[39;49m
[38;5;244mI/flutter ( 4399): #91     Element.rebuild[39;49m
[38;5;244mI/flutter ( 4399): #92     ComponentElement._firstBuild[39;49m
[38;5;244mI/flutter ( 4399): #93     ComponentElement.mount[39;49m
[38;5;244mI/flutter ( 4399): #94     Element.inflateWidget[39;49m
[38;5;244mI/flutter ( 4399): #95     Element.updateChild[39;49m
[38;5;244mI/flutter ( 4399): #96     SingleChildRenderObjectElement.mount[39;49m
[38;5;244mI/flutter ( 4399): #97     Element.inflateWidget[39;49m
[38;5;244mI/flutter ( 4399): #98     Element.updateChild[39;49m
[38;5;244mI/flutter ( 4399): #99     ComponentElement.performRebuild[39;49m
[38;5;244mI/flutter ( 4399): #100    Element.rebuild[39;49m
[38;5;244mI/flutter ( 4399): #101    ComponentElement._firstBuild[39;49m
[38;5;244mI/flutter ( 4399): #102    StatefulElement._firstBuild[39;49m
[38;5;244mI/flutter ( 4399): #103    ComponentElement.mount[39;49m
[38;5;244mI/flutter ( 4399): #104    Element.inflateWidget[39;49m
[38;5;244mI/flutter ( 4399): #105    Element.updateChild[39;49m
[38;5;244mI/flutter ( 4399): #106    ComponentElement.performRebuild[39;49m
[38;5;244mI/flutter ( 4399): #107    Element.rebuild[39;49m
[38;5;244mI/flutter ( 4399): #108    ComponentElement._firstBuild[39;49m
[38;5;244mI/flutter ( 4399): #109    ComponentElement.mount[39;49m
[38;5;244mI/flutter ( 4399): #110    Element.inflateWidget[39;49m
[38;5;244mI/flutter ( 4399): #111    Element.updateChild[39;49m
[38;5;244mI/flutter ( 4399): #112    ComponentElement.performRebuild[39;49m
[38;5;244mI/flutter ( 4399): #113    Element.rebuild[39;49m
[38;5;244mI/flutter ( 4399): #114    ComponentElement._firstBuild[39;49m
[38;5;244mI/flutter ( 4399): #115    StatefulElement._firstBuild[39;49m
[38;5;244mI/flutter ( 4399): #116    ComponentElement.mount[39;49m
[38;5;244mI/flutter ( 4399): #117    Element.inflateWidget[39;49m
[38;5;244mI/flutter ( 4399): #118    Element.updateChild[39;49m
[38;5;244mI/flutter ( 4399): #119    ComponentElement.performRebuild[39;49m
[38;5;244mI/flutter ( 4399): #120    Element.rebuild[39;49m
[38;5;244mI/flutter ( 4399): #121    ComponentElement._firstBuild[39;49m
[38;5;244mI/flutter ( 4399): #122    ComponentElement.mount[39;49m
[38;5;244mI/flutter ( 4399): #123    Element.inflateWidget[39;49m
[38;5;244mI/flutter ( 4399): #124    Element.updateChild[39;49m
[38;5;244mI/flutter ( 4399): #125    ComponentElement.performRebuild[39;49m
[38;5;244mI/flutter ( 4399): #126    Element.rebuild[39;49m
[38;5;244mI/flutter ( 4399): #127    ComponentElement._firstBuild[39;49m
[38;5;244mI/flutter ( 4399): #128    ComponentElement.mount[39;49m
[38;5;244mI/flutter ( 4399): #129    Element.inflateWidget[39;49m
[38;5;244mI/flutter ( 4399): #130    Element.updateChild[39;49m
[38;5;244mI/flutter ( 4399): #131    ComponentElement.performRebuild[39;49m
[38;5;244mI/flutter ( 4399): #132    Element.rebuild[39;49m
[38;5;244mI/flutter ( 4399): #133    ComponentElement._firstBuild[39;49m
[38;5;244mI/flutter ( 4399): #134    ComponentElement.mount[39;49m
[38;5;244mI/flutter ( 4399): #135    Element.inflateWidget[39;49m
[38;5;244mI/flutter ( 4399): #136    Element.updateChild[39;49m
[38;5;244mI/flutter ( 4399): #137    SingleChildRenderObjectElement.mount[39;49m
[38;5;244mI/flutter ( 4399): #138    Element.inflateWidget[39;49m
[38;5;244mI/flutter ( 4399): #139    Element.updateChild[39;49m
[38;5;244mI/flutter ( 4399): #140    ComponentElement.performRebuild[39;49m
[38;5;244mI/flutter ( 4399): #141    Element.rebuild[39;49m
[38;5;244mI/flutter ( 4399): #142    ComponentElement._firstBuild[39;49m
[38;5;244mI/flutter ( 4399): #143    ComponentElement.mount[39;49m
[38;5;244mI/flutter ( 4399): #144    Element.inflateWidget[39;49m
[38;5;244mI/flutter ( 4399): #145    Element.updateChild[39;49m
[38;5;244mI/flutter ( 4399): #146    ComponentElement.performRebuild[39;49m
[38;5;244mI/flutter ( 4399): #147    Element.rebuild[39;49m
[38;5;244mI/flutter ( 4399): #148    ComponentElement._firstBuild[39;49m
[38;5;244mI/flutter ( 4399): #149    StatefulElement._firstBuild[39;49m
[38;5;244mI/flutter ( 4399): #150    ComponentElement.mount[39;49m
[38;5;244mI/flutter ( 4399): #151    Element.inflateWidget[39;49m
[38;5;244mI/flutter ( 4399): #152    Element.updateChild[39;49m
[38;5;244mI/flutter ( 4399): #153    ComponentElement.performRebuild[39;49m
[38;5;244mI/flutter ( 4399): #154    Element.rebuild[39;49m
[38;5;244mI/flutter ( 4399): #155    ComponentElement._firstBuild[39;49m
[38;5;244mI/flutter ( 4399): #156    StatefulElement._firstBuild[39;49m
[38;5;244mI/flutter ( 4399): #157    ComponentElement.mount[39;49m
[38;5;244mI/flutter ( 4399): #158    Element.inflateWidget[39;49m
[38;5;244mI/flutter ( 4399): #159    Element.updateChild[39;49m
[38;5;244mI/flutter ( 4399): #160    ComponentElement.performRebuild[39;49m
[38;5;244mI/flutter ( 4399): #161    Element.rebuild[39;49m
[38;5;244mI/flutter ( 4399): #162    ComponentElement._firstBuild[39;49m
[38;5;244mI/flutter ( 4399): #163    StatefulElement._firstBuild[39;49m
[38;5;244mI/flutter ( 4399): #164    ComponentElement.mount[39;49m
[38;5;244mI/flutter ( 4399): #165    Element.inflateWidget[39;49m
[38;5;244mI/flutter ( 4399): #166    Element.updateChild[39;49m
[38;5;244mI/flutter ( 4399): #167    ComponentElement.performRebuild[39;49m
[38;5;244mI/flutter ( 4399): #168    Element.rebuild[39;49m
[38;5;244mI/flutter ( 4399): #169    ComponentElement._firstBuild[39;49m
[38;5;244mI/flutter ( 4399): #170    ComponentElement.mount[39;49m
[38;5;244mI/flutter ( 4399): #171    Element.inflateWidget[39;49m
[38;5;244mI/flutter ( 4399): #172    Element.updateChild[39;49m
[38;5;244mI/flutter ( 4399): #173    ComponentElement.performRebuild[39;49m
[38;5;244mI/flutter ( 4399): #174    Element.rebuild[39;49m
[38;5;244mI/flutter ( 4399): #175    ComponentElement._firstBuild[39;49m
[38;5;244mI/flutter ( 4399): #176    StatefulElement._firstBuild[39;49m
[38;5;244mI/flutter ( 4399): #177    ComponentElement.mount[39;49m
[38;5;244mI/flutter ( 4399): #178    Element.inflateWidget[39;49m
[38;5;244mI/flutter ( 4399): #179    Element.updateChild[39;49m
[38;5;244mI/flutter ( 4399): #180    ComponentElement.performRebuild[39;49m
[38;5;244mI/flutter ( 4399): #181    Element.rebuild[39;49m
[38;5;244mI/flutter ( 4399): #182    ComponentElement._firstBuild[39;49m
[38;5;244mI/flutter ( 4399): #183    ComponentElement.mount[39;49m
[38;5;244mI/flutter ( 4399): #184    Element.inflateWidget[39;49m
[38;5;244mI/flutter ( 4399): #185    Element.updateChild[39;49m
[38;5;244mI/flutter ( 4399): #186    RenderObjectToWidgetElement._rebuild[39;49m
[38;5;244mI/flutter ( 4399): #187    RenderObjectToWidgetElement.mount[39;49m
[38;5;244mI/flutter ( 4399): #188    RenderObjectToWidgetAdapter.attachToRenderTree.<anonymous closure>[39;49m
[38;5;244mI/flutter ( 4399): #189    BuildOwner.buildScope[39;49m
[38;5;244mI/flutter ( 4399): #190    RenderObjectToWidgetAdapter.attachToRenderTree[39;49m
[38;5;244mI/flutter ( 4399): #191    WidgetsBinding.attachRootWidget[39;49m
[38;5;244mI/flutter ( 4399): #192    WidgetsBinding.scheduleAttachRootWidget.<anonymous closure>[39;49m
[38;5;244mI/flutter ( 4399): #201    _Timer._runTimers  (dart:isolate-patch/timer_impl.dart:384:19)[39;49m
[38;5;244mI/flutter ( 4399): #202    _Timer._handleMessage  (dart:isolate-patch/timer_impl.dart:418:5)[39;49m
[38;5;244mI/flutter ( 4399): #203    _RawReceivePortImpl._handleMessage  (dart:isolate-patch/isolate_patch.dart:174:12)[39;49m
I/flutter ( 4399): (elided 8 frames from package dart:async and package dart:async-patch)
I/flutter ( 4399):
I/flutter ( 4399): ════════════════════════════════════════════════════════════════════════════════════════════════════
√ Built build\app\outputs\apk\debug\app-debug.apk.

```

</details>

**Comment by f12developers** [comment]
�🔥  To hot reload changes while running, press "r". To hot restart (and rebuild state), press "R".
An Observatory debugger and profiler on Android SDK built for x86 is available at: http://127.0.0.1:60628/QG6fFBwZXvY=/
For a more detailed help message, press "h". To detach, press "d"; to quit, press "q".
Lost connection to device.

**Comment by iapicca** [comment]
Hi @f12developers 
can you please provide your updated  `flutter doctor -v`
and your `flutter run --verbose`?
Also, to better address the issue, would be helpful
if you could post  a minimal code sample
or the steps to reproduce the problem.
Thank you

**Comment by f12developers** [comment]
It was solved

**Comment by iapicca** [comment]
Hi @f12developers 
thank you for letting me know
