### ISSUE TITLE
flutter build apk ; ProcessException: ProcessException: Permission denied

### ISSUE THREAD

**Issue by bitores** [flutter/flutter#47038]
Flutter crash report; please file at https://github.com/flutter/flutter/issues.

## command

flutter build apk

## exception

```bash
ProcessException: ProcessException: Permission denied
  Command: /Users/huangzhengjie/env/flutter/.pub-cache/hosted/pub.flutter-io.cn/file_picker-1.4.3+1/android/gradlew -I=/Users/huangzhengjie/env/flutter/packages/flutter_tools/gradle/aar_init_script.gradle -Pflutter-root=/Users/huangzhengjie/env/flutter -Poutput-dir=/Users/huangzhengjie/workspace/flutterws/demo/build/app -Pis-plugin=true -Ptarget-platform=android-arm,android-arm64,android-x64 assembleAarRelease
```

```bash
#0      _DefaultProcessUtils.run (package:flutter_tools/src/base/process.dart:266:37)
<asynchronous suspension>
#1      buildGradleAar (package:flutter_tools/src/android/gradle.dart:548:33)
#2      buildPluginsAsAar (package:flutter_tools/src/android/gradle.dart:711:13)
<asynchronous suspension>
#3      buildGradleApp (package:flutter_tools/src/android/gradle.dart:257:11)
#4      _AsyncAwaitCompleter.start (dart:async-patch/async_patch.dart:45:6)
#5      buildGradleApp (package:flutter_tools/src/android/gradle.dart:218:28)
#6      buildGradleApp (package:flutter_tools/src/android/gradle.dart:415:19)
#7      _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:73:64)
#8      _rootRunUnary (dart:async/zone.dart:1134:38)
#9      _CustomZone.runUnary (dart:async/zone.dart:1031:19)
#10     _FutureListener.handleValue (dart:async/future_impl.dart:139:18)
#11     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:680:45)
#12     Future._propagateToListeners (dart:async/future_impl.dart:709:32)
#13     Future._completeWithValue (dart:async/future_impl.dart:524:5)
#14     Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:554:7)
#15     _rootRun (dart:async/zone.dart:1126:13)
#16     _CustomZone.run (dart:async/zone.dart:1023:19)
#17     _CustomZone.runGuarded (dart:async/zone.dart:925:7)
#18     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:965:23)
#19     _microtaskLoop (dart:async/schedule_microtask.dart:43:21)
#20     _startMicrotaskLoop (dart:async/schedule_microtask.dart:52:5)
#21     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
#22     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:175:5)
```

## flutter doctor

```bash
[32m[✓][39m Flutter (Channel stable, v1.12.13+hotfix.5, on Mac OS X 10.15.1 19B88, locale zh-Hans-CN)
    [32m•[39m Flutter version 1.12.13+hotfix.5 at /Users/huangzhengjie/env/flutter
    [32m•[39m Framework revision 27321ebbad (3 days ago), 2019-12-10 18:15:01 -0800
    [32m•[39m Engine revision 2994f7e1e6
    [32m•[39m Dart version 2.7.0

[32m[✓][39m Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    [32m•[39m Android SDK at /Users/huangzhengjie/Library/Android/sdk
    [32m•[39m Android NDK location not configured (optional; useful for native profiling support)
    [32m•[39m Platform android-29, build-tools 28.0.3
    [32m•[39m ANDROID_HOME = /Users/huangzhengjie/Library/Android/sdk
    [32m•[39m Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    [32m•[39m Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    [32m•[39m All Android licenses accepted.

[32m[✓][39m Xcode - develop for iOS and macOS (Xcode 11.2.1)
    [32m•[39m Xcode at /Applications/Xcode.app/Contents/Developer
    [32m•[39m Xcode 11.2.1, Build version 11B500
    [32m•[39m CocoaPods version 1.8.4

[32m[✓][39m Android Studio (version 3.5)
    [32m•[39m Android Studio at /Applications/Android Studio.app/Contents
    [32m•[39m Flutter plugin version 40.2.2
    [32m•[39m Dart plugin version 191.8593
    [32m•[39m Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[32m[✓][39m VS Code (version 1.41.0)
    [32m•[39m VS Code at /Applications/Visual Studio Code.app/Contents
    [32m•[39m Flutter extension version 3.7.1

[32m[✓][39m Connected device (1 available)
    [32m•[39m Android SDK built for x86 • emulator-5554 • android-x86 • Android 10 (API 29) (emulator)

[32m•[39m No issues found!
```

**Comment by rahuldange09** [comment]
Try with sudo

**Comment by bitores** [comment]
when i try with sudo
```
Woah! You appear to be trying to run flutter as root.
   We strongly recommend running the flutter tool without superuser privileges.
```

**Comment by redsolver** [comment]
Same issue here on Linux.

**Comment by iapicca** [comment]
HI @bitores 
does this [solution](https://github.com/flutter/flutter/issues/49542#issuecomment-578765793) works for you?
thank you

**Comment by agersea** [comment]
Same issue

**Comment by jonahwilliams** [comment]
We're tracking issues with project permissions in https://github.com/flutter/flutter/issues/50880
