### ISSUE TITLE
1.12.13+hotfix.5 Unhandled Exception: ServicesBinding.defaultBinaryMessenger was accessed before the binding was initialized

### ISSUE THREAD

**Issue by NTMS2017** [flutter/flutter#47033]
I download new stable version 1.12.13+hotfix.5 flutter sdk and I have an issues. My app not running.

```
E/flutter ( 8701): 
✓ Built build/app/outputs/apk/debug/app-debug.apk.
Installing build/app/outputs/apk/app.apk...
Syncing files to device Android SDK built for x86...
E/flutter ( 8888): [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: ServicesBinding.defaultBinaryMessenger was accessed before the binding was initialized.
E/flutter ( 8888): If you're running an application and need to access the binary messenger before `runApp()` has been called (for example, during plugin initialization), then you need to explicitly call the `WidgetsFlutterBinding.ensureInitialized()` first.
E/flutter ( 8888): If you're running a test, you can call the `TestWidgetsFlutterBinding.ensureInitialized()` as the first line in your test's `main()` method to initialize the binding.
E/flutter ( 8888): #0      defaultBinaryMessenger.<anonymous closure> (package:flutter/src/services/binary_messenger.dart:76:7)
E/flutter ( 8888): #1      defaultBinaryMessenger (package:flutter/src/services/binary_messenger.dart:89:4)
E/flutter ( 8888): #2      MethodChannel.binaryMessenger (package:flutter/src/services/platform_channel.dart:140:62)
E/flutter ( 8888): #3      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:314:35)
E/flutter ( 8888): #4      OptionalMethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:429:36)
E/flutter ( 8888): #5      SystemChrome.setEnabledSystemUIOverlays (package:flutter/src/services/system_chrome.dart:280:35)
E/flutter ( 8888): #6      main (package:capital_cep/main.dart:34:22)
E/flutter ( 8888): #7      _runMainZoned.<anonymous closure>.<anonymous closure> (dart:ui/hooks.dart:239:25)
E/flutter ( 8888): #8      _rootRun (dart:async/zone.dart:1126:13)
E/flutter ( 8888): #9      _CustomZone.run (dart:async/zone.dart:1023:19)
E/flutter ( 8888): #10     _runZoned (dart:async/zone.dart:1518:10)
E/flutter ( 8888): #11     runZoned (dart:async/zone.dart:1502:12)
E/flutter ( 8888): #12     _runMainZoned.<anonymous closure> (dart:ui/hooks.dart:231:5)
E/flutter ( 8888): #13     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:307:19)
E/flutter ( 8888): #14     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:174:12)
E/flutter ( 8888): 
Error -32601 received from application: Method not found
Application finished.
```

**flutter doctor -v**
```
[✓] Flutter (Channel stable, v1.12.13+hotfix.5, on Mac OS X 10.15.2 19C57, locale en-CY)
    • Flutter version 1.12.13+hotfix.5 at /Users/********/flutter
    • Framework revision 27321ebbad (3 days ago), 2019-12-10 18:15:01 -0800
    • Engine revision 2994f7e1e6
    • Dart version 2.7.0

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/********/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.3, Build version 11C29
    • CocoaPods version 1.8.4

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 42.1.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] IntelliJ IDEA Community Edition (version 2019.3)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 41.1.5
    • Dart plugin version 193.5233.116

[✓] Connected device (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 10 (API 29) (emulator)

• No issues found!

```

**Comment by AlexVincent525** [comment]
Add `WidgetsFlutterBinding.ensureInitialized()` before `runApp()`.

**Comment by NTMS2017** [comment]
My void main is shown below. I add WidgetsFlutterBinding.ensureInitialized(); and still getting same error. I run flutter clean and Inavalidate Cashes and restart and still getting same error.


```
void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await SystemChrome.setEnabledSystemUIOverlays([]);
  await SystemChrome.setPreferredOrientations([DeviceOrientation.portraitUp]);
  runApp(new CapitalApp());
}
```

**Comment by mimicode** [comment]
我也遇到了相同的问题，不管我如何修改main ，即使代码被我删除，依然会在app安装到我手机前 运行之前的旧代码 而 该情况在 1.9上没有问题
I have the same problem. No matter how I modify the main, even if the code is deleted by me, it will still run the old code before the app is installed on my phone, which is no problem on 1.9

**Comment by mimicode** [comment]
The flutter compiler seems to run the old code specially, but the new code will not take effect completely. Even if I execute the flutter clean before recompilation, it is still invalid

**Comment by iapicca** [comment]
Hi @NTMS2017 
I see there's an open [issue ](https://github.com/flutter/flutter/issues/46849)addressing the case you described.
Please follow up on that issue,
I'm closing the current one as duplicate.
If you disagree please write in the comments
and I will reopen it.
Thank you

**Comment by wangwanchao** [comment]
> My void main is shown below. I add WidgetsFlutterBinding.ensureInitialized(); and still getting same error. I run flutter clean and Inavalidate Cashes and restart and still getting same error.
> 
> ```
> void main() async {
>   WidgetsFlutterBinding.ensureInitialized();
>   await SystemChrome.setEnabledSystemUIOverlays([]);
>   await SystemChrome.setPreferredOrientations([DeviceOrientation.portraitUp]);
>   runApp(new CapitalApp());
> }
> ```

thank you.It works normally.but I dont know why async? Do you have some API Reference?

**Comment by cyber-noob** [comment]
Even this demo app gets error. To be sure, I downloaded the latest version but didn't solve this error. Although I make a call to WigetsFlutterBinding.ensureInitialized(); above runApp();
it still gets error :cry:  

```

import 'package:flutter/material.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        // This is the theme of your application.
        //
        // Try running your application with "flutter run". You'll see the
        // application has a blue toolbar. Then, without quitting the app, try
        // changing the primarySwatch below to Colors.green and then invoke
        // "hot reload" (press "r" in the console where you ran "flutter run",
        // or simply save your changes to "hot reload" in a Flutter IDE).
        // Notice that the counter didn't reset back to zero; the application
        // is not restarted.
        primarySwatch: Colors.blue,
      ),
      home: MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key key, this.title}) : super(key: key);

  // This widget is the home page of your application. It is stateful, meaning
  // that it has a State object (defined below) that contains fields that affect
  // how it looks.

  // This class is the configuration for the state. It holds the values (in this
  // case the title) provided by the parent (in this case the App widget) and
  // used by the build method of the State. Fields in a Widget subclass are
  // always marked "final".

  final String title;

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  int _counter = 0;

  void _incrementCounter() {
    setState(() {
      // This call to setState tells the Flutter framework that something has
      // changed in this State, which causes it to rerun the build method below
      // so that the display can reflect the updated values. If we changed
      // _counter without calling setState(), then the build method would not be
      // called again, and so nothing would appear to happen.
      _counter++;
    });
  }

  @override
  Widget build(BuildContext context) {
    // This method is rerun every time setState is called, for instance as done
    // by the _incrementCounter method above.
    //
    // The Flutter framework has been optimized to make rerunning build methods
    // fast, so that you can just rebuild anything that needs updating rather
    // than having to individually change instances of widgets.
    return Scaffold(
      appBar: AppBar(
        // Here we take the value from the MyHomePage object that was created by
        // the App.build method, and use it to set our appbar title.
        title: Text(widget.title),
      ),
      body: Center(
        // Center is a layout widget. It takes a single child and positions it
        // in the middle of the parent.
        child: Column(
          // Column is also a layout widget. It takes a list of children and
          // arranges them vertically. By default, it sizes itself to fit its
          // children horizontally, and tries to be as tall as its parent.
          //
          // Invoke "debug painting" (press "p" in the console, choose the
          // "Toggle Debug Paint" action from the Flutter Inspector in Android
          // Studio, or the "Toggle Debug Paint" command in Visual Studio Code)
          // to see the wireframe for each widget.
          //
          // Column has various properties to control how it sizes itself and
          // how it positions its children. Here we use mainAxisAlignment to
          // center the children vertically; the main axis here is the vertical
          // axis because Columns are vertical (the cross axis would be
          // horizontal).
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            Text(
              'You have pushed the button this many times:',
            ),
            Text(
              '$_counter',
              style: Theme.of(context).textTheme.display1,
            ),
          ],
        ),
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: _incrementCounter,
        tooltip: 'Increment',
        child: Icon(Icons.add),
      ), // This trailing comma makes auto-formatting nicer for build methods.
    );
  }
}

```

**Comment by AlexVincent525** [comment]
Please be aware that when you started to run `main.dart`, sometimes you'll get a couple lines of log, which comes from last time you run the dart file. No matter what project you have run.

For example, when you click run and get this error, terminate the process then rerun, you'll see the error again immediately. That doesn't point to the current process, take a closer look to the log and you may found it came from last time you run this. `flutter clean` may help.

**Comment by cyber-noob** [comment]
Yes bro, It may come from the last time I run `flutter clean` didn't solve my problem. 
Now I am reuse flutter_v1.9.1. It is totally fine  but not flutter_v1.12.13+hotfix.5. Even it comes from the last run time, that is so confusing for me.

**Comment by master11641** [comment]
> Yes bro, It may come from the last time I run `flutter clean` didn't solve my problem.
> Now I am reuse flutter_v1.9.1. It is totally fine but not flutter_v1.12.13+hotfix.5. Even the error comes from the last run time, that is so confusing for me.

You must add WidgetsFlutterBinding.ensureInitialized() as first line in main() method

**Comment by NTMS2017** [comment]
@wangwanchao sorry for late reply. Then reason I use async because for SystemChrome I use **await**. 

```
await SystemChrome.setEnabledSystemUIOverlays([]);
await SystemChrome.setPreferredOrientations([DeviceOrientation.portraitUp]);
```

**SystemChrome:** Controls specific aspects of the operating system's graphical interface and how it interacts with the application.

**Comment by hanslissi** [comment]
Ok so, I had the same problem with the flutter version v1.12.13+hotfix.5. Now I switched to version v1.14.4 and it works fine.

**Comment by mcalooosh** [comment]
I had the same problem, after trying and testing all of your comments, the issue was solved by:
Running "**flutter clean**" FIRST
and then do "**flutter run**" again.

Somehow, Android studio still caches the main.dart code even with doing "Invalidate Caches/Restart".
