### ISSUE TITLE
[web] - Uncaught Assertion failed - Failing to load Generated JavaScript files - White Screen and error in console when running Flutter for Web app

### ISSUE THREAD

**Issue by marvinIsSacul** [flutter/flutter#47115]
Hi. I am able to fully build and run the flutter web app on my local using `flutter run -d chrome`.

The problem occurs **only** when I'm building the web app for release mode. I have tried everything that I can to resolve this... but without success. This is my last resort.

I've discovered that this happens because the built JavaScript files are failing to be loaded. When I look at the local (debug) build... I see that one of these files are getting loaded...

`http://localhost:57344/packages/SiyakhulaDevelopmentAcademy/main_web_entrypoint.ddc.js`

So my question is how do I get my release build to be able to successfully load the generated JavaScript files ???

Please help.

## Steps to Reproduce

1. ... `flutter channel beta` or `flutter channel dev` or `flutter channel master`
2. ... `flutter build web`
3. ... start server in `web` directory.

**Target OS version/browser: *Web*
**Devices: *chrome*

## Flutter Doctor

```
[√] Flutter (Channel beta, v1.12.13+hotfix.6, on Microsoft Windows [Version 10.0.10240], locale en-ZA)
    • Flutter version 1.12.13+hotfix.6 at C:\flutter
    • Framework revision 18cd7a3601 (5 days ago), 2019-12-11 06:35:39 -0800
    • Engine revision 2994f7e1e6
    • Dart version 2.7.0

[X] Android toolchain - develop for Android devices
    X Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/setup/#android-setup for detailed instructions).
      If the Android SDK has been installed to a custom location, set ANDROID_HOME to that location.
      You may also want to add it to your PATH environment variable.


[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/setup/#android-setup for detailed instructions).

[√] VS Code (version 1.41.0)
    • VS Code at C:\Users\Marvin\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.7.1

[√] Connected device (2 available)
    • Chrome     • chrome     • web-javascript • Google Chrome 79.0.3945.79
    • Web Server • web-server • web-javascript • Flutter Tools

! Doctor found issues in 2 categories.
```

## Console Output

```
js_helper.dart:1342 Uncaught Assertion failed
    at Object.d (localhost:8080/main.dart.js:1744:3)
    at Object.U (localhost:8080/main.dart.js:1750:23)
    at localhost:8080/main.dart.js:7403:3
    at OT.a (localhost:8080/main.dart.js:2557:72)
    at OT.$2 (localhost:8080/main.dart.js:18265:23)
    at Object.ac (localhost:8080/main.dart.js:2544:20)
    at Object.w6 (localhost:8080/main.dart.js:7422:10)
    at localhost:8080/main.dart.js:42009:8
    at localhost:8080/main.dart.js:42004:55
    at dartProgram (localhost:8080/main.dart.js:42007:84)
```

## More Errors
```
Could not load content for org-dartlang-sdk:///sdk/lib/collection/iterable.dart : HTTP status code: 404
```

**Comment by iapicca** [comment]
Hi @marvinIsSacul 
can you please provide your `flutter run --verbose`?
Thank you

**Comment by marvinIsSacul** [comment]
Hi @iapicca 

I have even managed to run `flutter run --profile -d wed-server`  with success.

I'm thinking its probably because i used the `web-server` device instead of `chrome`.

`flutter run --verbose` produces:

```
[  +63 ms] executing: [C:\flutter\] git -c log.showSignature=false log -n 1 --pretty=format:%H
[ +280 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[   +1 ms] 4944622b5d8e7a8ee5dbf658b0d0e8ab94b8efd3
[        ] executing: [C:\flutter\] git describe --match v*.*.* --first-parent --long --tags
[ +322 ms] Exit code 0 from: git describe --match v*.*.* --first-parent --long --tags
[        ] v1.13.2-0-g4944622b5
[  +10 ms] executing: [C:\flutter\] git rev-parse --abbrev-ref --symbolic @{u}
[  +43 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/dev
[        ] executing: [C:\flutter\] git ls-remote --get-url origin
[  +39 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[  +99 ms] executing: [C:\flutter\] git rev-parse --abbrev-ref HEAD
[  +20 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] dev
[ +192 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[   +4 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[  +49 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[   +8 ms] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[  +11 ms] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[ +247 ms] Unable to locate an Android SDK.
[ +132 ms] Unable to locate an Android SDK.
[  +81 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[   +6 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[ +150 ms] More than one device connected; please specify a device with the '-d <deviceId>' flag, or use '-d all' to act on all devices.
[ +133 ms] Chrome     • chrome     • web-javascript • Google Chrome 79.0.3945.79
[        ] Web Server • web-server • web-javascript • Flutter Tools
[  +10 ms] "flutter run" took 1 057ms.

#0      throwToolExit (package:flutter_tools/src/base/common.dart:28:3)
#1      RunCommand.validateCommand (package:flutter_tools/src/commands/run.dart:302:7)
<asynchronous suspension>
#2      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:607:11)
<asynchronous suspension>
#3      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:522:33)
<asynchronous suspension>
#4      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:146:29)
#5      _rootRun (dart:async/zone.dart:1126:13)
#6      _CustomZone.run (dart:async/zone.dart:1023:19)
#7      _runZoned (dart:async/zone.dart:1518:10)
#8      runZoned (dart:async/zone.dart:1465:12)
#9      AppContext.run (package:flutter_tools/src/base/context.dart:145:18)
#10     FlutterCommand.run (package:flutter_tools/src/runner/flutter_command.dart:512:20)
#11     CommandRunner.runCommand (package:args/command_runner.dart:197:27)
#12     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:333:21)
<asynchronous suspension>
#13     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:146:29)
#14     _rootRun (dart:async/zone.dart:1126:13)
#15     _CustomZone.run (dart:async/zone.dart:1023:19)
#16     _runZoned (dart:async/zone.dart:1518:10)
#17     runZoned (dart:async/zone.dart:1465:12)
#18     AppContext.run (package:flutter_tools/src/base/context.dart:145:18)
#19     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:284:19)
#20     CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:112:25)
#21     new Future.sync (dart:async/future.dart:224:31)
#22     CommandRunner.run (package:args/command_runner.dart:112:14)
#23     FlutterCommandRunner.run (package:flutter_tools/src/runner/flutter_command_runner.dart:227:18)
#24     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:64:22)
#25     _rootRun (dart:async/zone.dart:1126:13)
#26     _CustomZone.run (dart:async/zone.dart:1023:19)
#27     _runZoned (dart:async/zone.dart:1518:10)
#28     runZoned (dart:async/zone.dart:1502:12)
#29     run.<anonymous closure> (package:flutter_tools/runner.dart:62:18)
<asynchronous suspension>
#30     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:146:29)
#31     _rootRun (dart:async/zone.dart:1126:13)
#32     _CustomZone.run (dart:async/zone.dart:1023:19)
#33     _runZoned (dart:async/zone.dart:1518:10)
#34     runZoned (dart:async/zone.dart:1465:12)
#35     AppContext.run (package:flutter_tools/src/base/context.dart:145:18)
#36     runInContext (package:flutter_tools/src/context_runner.dart:64:24)
#37     run (package:flutter_tools/runner.dart:51:10)
#38     main (package:flutter_tools/executable.dart:65:9)
#39     main (file:///C:/flutter/packages/flutter_tools/bin/flutter_tools.dart:8:3)
#40     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:305:32)
#41     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:174:12)
```

**Comment by iapicca** [comment]
`[ +150 ms] More than one device connected; please specify a device with the '-d <deviceId>' flag, or use '-d all' to act on all devices.`
Hi again @marvinIsSacul 
seems that the terminal didn't select the device
can you please run `flutter run -d chrome --verbose `
thank you

**Comment by marvinIsSacul** [comment]
yep, I've even managed to build for release using `flutter run --release -d web-server`. So the probably is definitely using the `chrome` device.

**Comment by marvinIsSacul** [comment]
`flutter run -d chrome --verbose`

```
flutter run -d chrome --verbose
[  +30 ms] executing: [C:\flutter\] git -c log.showSignature=false log -n 1 --pretty=format:%H
[ +208 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[   +1 ms] 4944622b5d8e7a8ee5dbf658b0d0e8ab94b8efd3
[        ] executing: [C:\flutter\] git describe --match v*.*.* --first-parent --long --tags
[ +149 ms] Exit code 0 from: git describe --match v*.*.* --first-parent --long --tags
[        ] v1.13.2-0-g4944622b5
[   +9 ms] executing: [C:\flutter\] git rev-parse --abbrev-ref --symbolic @{u}
[  +23 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/dev
[        ] executing: [C:\flutter\] git ls-remote --get-url origin
[  +24 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[  +76 ms] executing: [C:\flutter\] git rev-parse --abbrev-ref HEAD
[  +47 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] dev
[ +124 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[  +52 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[ +187 ms] Unable to locate an Android SDK.
[ +165 ms] Unable to locate an Android SDK.
[  +76 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[   +5 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[ +193 ms] Found plugin url_launcher at C:\flutter\.pub-cache\hosted\pub.dartlang.org\url_launcher-5.4.1\
[   +8 ms] Found plugin url_launcher_macos at C:\flutter\.pub-cache\hosted\pub.dartlang.org\url_launcher_macos-0.0.1+2\
[   +4 ms] Found plugin url_launcher_web at C:\flutter\.pub-cache\hosted\pub.dartlang.org\url_launcher_web-0.1.0+2\
[+1318 ms] Found plugin url_launcher at C:\flutter\.pub-cache\hosted\pub.dartlang.org\url_launcher-5.4.1\
[   +2 ms] Found plugin url_launcher_macos at C:\flutter\.pub-cache\hosted\pub.dartlang.org\url_launcher_macos-0.0.1+2\
[   +2 ms] Found plugin url_launcher_web at C:\flutter\.pub-cache\hosted\pub.dartlang.org\url_launcher_web-0.1.0+2\
[ +412 ms] Generating C:\Users\Marvin\Documents\code\sda_frontend\android\app\src\main\java\io\flutter\plugins\GeneratedPluginRegistrant.java
[ +563 ms] Launching lib\main.dart on Chrome in debug mode...
[        ] Building application for the web...
[ +752 ms] Found plugin url_launcher at C:\flutter\.pub-cache\hosted\pub.dartlang.org\url_launcher-5.4.1\
[   +1 ms] Found plugin url_launcher_macos at C:\flutter\.pub-cache\hosted\pub.dartlang.org\url_launcher_macos-0.0.1+2\
[   +1 ms] Found plugin url_launcher_web at C:\flutter\.pub-cache\hosted\pub.dartlang.org\url_launcher_web-0.1.0+2\
[+42982 ms] Starting daemon...
[ +474 ms] Initializing inputs
[  +30 ms] Reading cached asset graph...
[ +264 ms] Throwing away cached asset graph because the build phases have changed. This most commonly would happen as a result of adding a new dependency or
updating your dependencies.
[  +53 ms] Cleaning up outputs from previous builds....
[+8878 ms] Cleaning up outputs from previous builds. completed, took 8.9s

[        ] Reading cached asset graph completed, took 9.2s

[+5734 ms] Building new asset graph...
[+26368 ms] Building new asset graph completed, took 26.4s

[   +1 ms] Checking for unexpected pre-existing outputs....
[        ] Checking for unexpected pre-existing outputs. completed, took 1ms

[   +8 ms] Initializing inputs
[  +26 ms] Reading cached asset graph...
[  +28 ms] Throwing away cached asset graph because the build phases have changed. This most commonly would happen as a result of adding a new dependency or
updating your
           dependencies.
[   +4 ms] Cleaning up outputs from previous builds....
[        ] Cleaning up outputs from previous builds. completed, took 8.9s
[        ] Reading cached asset graph completed, took 9.2s
[        ] Building new asset graph...
[        ] Building new asset graph completed, took 26.4s
[        ] Checking for unexpected pre-existing outputs....
[        ] Checking for unexpected pre-existing outputs. completed, took 1ms
[+8019 ms] About to build [web]...
[ +203 ms] Running build...
[ +799 ms] 1.0s elapsed, 29/49 actions completed.
[+1085 ms] 2.1s elapsed, 128/148 actions completed.
[ +982 ms] 3.1s elapsed, 221/233 actions completed.
[+1105 ms] 4.1s elapsed, 342/362 actions completed.
[+1016 ms] 5.2s elapsed, 465/485 actions completed.
[+1001 ms] 6.2s elapsed, 571/575 actions completed.
[+1078 ms] 7.3s elapsed, 692/697 actions completed.
[+1011 ms] 8.3s elapsed, 802/822 actions completed.
[+1060 ms] 9.3s elapsed, 929/949 actions completed.
[+1041 ms] 10.4s elapsed, 954/959 actions completed.
[+1087 ms] 11.5s elapsed, 989/1009 actions completed.
[+1026 ms] 12.5s elapsed, 1033/1042 actions completed.
[+1085 ms] 13.6s elapsed, 1086/1106 actions completed.
[+1009 ms] 14.6s elapsed, 1187/1195 actions completed.
[+1087 ms] 15.7s elapsed, 1245/1250 actions completed.
[+1003 ms] 16.7s elapsed, 1304/1362 actions completed.
[+1024 ms] 17.7s elapsed, 1304/1362 actions completed.
[+1072 ms] 18.8s elapsed, 1304/1362 actions completed.
[+1026 ms] 19.8s elapsed, 1306/1364 actions completed.
[+1063 ms] 20.9s elapsed, 1308/1365 actions completed.
[+1009 ms] 21.9s elapsed, 1312/1368 actions completed.
[+1102 ms] 23.0s elapsed, 1314/1370 actions completed.
[+1001 ms] 24.0s elapsed, 1318/1371 actions completed.
[+1092 ms] 25.1s elapsed, 1319/1371 actions completed.
[+1054 ms] 26.2s elapsed, 1323/1372 actions completed.
[+1039 ms] 27.2s elapsed, 1326/1372 actions completed.
[+1108 ms] 28.3s elapsed, 1326/1372 actions completed.
[+1022 ms] 29.3s elapsed, 1326/1372 actions completed.
[+1069 ms] 30.4s elapsed, 1332/1378 actions completed.
[+1098 ms] 31.5s elapsed, 1332/1378 actions completed.
[+1001 ms] 32.5s elapsed, 1333/1379 actions completed.
[+1014 ms] 33.5s elapsed, 1333/1379 actions completed.
[+1085 ms] 34.6s elapsed, 1333/1379 actions completed.
[+1001 ms] 35.6s elapsed, 1333/1379 actions completed.
[+1117 ms] 36.7s elapsed, 1333/1379 actions completed.
[+1021 ms] 37.7s elapsed, 1333/1379 actions completed.
[+1062 ms] 38.8s elapsed, 1334/1380 actions completed.
[+1026 ms] 39.8s elapsed, 1334/1380 actions completed.
[+1070 ms] 40.9s elapsed, 1334/1380 actions completed.
[+1100 ms] 42.0s elapsed, 1336/1380 actions completed.
[+1000 ms] 43.0s elapsed, 1337/1381 actions completed.
[+1099 ms] 44.1s elapsed, 1337/1381 actions completed.
[+1000 ms] 45.1s elapsed, 1337/1381 actions completed.
[+1000 ms] 46.1s elapsed, 1338/1381 actions completed.
[+1100 ms] 47.2s elapsed, 1339/1382 actions completed.
[+1035 ms] 48.2s elapsed, 1339/1382 actions completed.
[+1063 ms] 49.3s elapsed, 1339/1382 actions completed.
[+1099 ms] 50.4s elapsed, 1339/1382 actions completed.
[+1102 ms] 51.5s elapsed, 1339/1382 actions completed.
[+1098 ms] 52.6s elapsed, 1339/1382 actions completed.
[+1108 ms] 53.7s elapsed, 1339/1382 actions completed.
[+1093 ms] 54.8s elapsed, 1339/1382 actions completed.
[+1099 ms] 55.9s elapsed, 1339/1382 actions completed.
[+1099 ms] 57.0s elapsed, 1339/1382 actions completed.
[+1098 ms] 58.1s elapsed, 1339/1382 actions completed.
[ +999 ms] 59.1s elapsed, 1339/1382 actions completed.
[+1101 ms] 1m 0s elapsed, 1340/1382 actions completed.
[+1099 ms] 1m 1s elapsed, 1340/1382 actions completed.
[+1099 ms] 1m 2s elapsed, 1340/1382 actions completed.
[+1001 ms] 1m 3s elapsed, 1340/1382 actions completed.
[+1099 ms] 1m 4s elapsed, 1340/1382 actions completed.
[+1099 ms] 1m 5s elapsed, 1341/1382 actions completed.
[+1101 ms] 1m 6s elapsed, 1342/1383 actions completed.
[+1102 ms] 1m 7s elapsed, 1342/1383 actions completed.
[+1098 ms] 1m 8s elapsed, 1345/1383 actions completed.
[+1103 ms] 1m 10s elapsed, 1347/1385 actions completed.
[+1099 ms] 1m 11s elapsed, 1349/1386 actions completed.
[+1096 ms] 1m 12s elapsed, 1351/1388 actions completed.
[+1019 ms] 1m 13s elapsed, 1354/1391 actions completed.
[+1081 ms] 1m 14s elapsed, 1355/1391 actions completed.
[ +999 ms] 1m 15s elapsed, 1355/1391 actions completed.
[+1099 ms] 1m 16s elapsed, 1355/1391 actions completed.
[+1002 ms] 1m 17s elapsed, 1355/1391 actions completed.
[+1098 ms] 1m 18s elapsed, 1355/1391 actions completed.
[+1019 ms] 1m 19s elapsed, 1355/1391 actions completed.
[+1079 ms] 1m 20s elapsed, 1355/1391 actions completed.
[+1000 ms] 1m 21s elapsed, 1355/1391 actions completed.
[+1099 ms] 1m 22s elapsed, 1356/1392 actions completed.
[+1000 ms] 1m 23s elapsed, 1357/1393 actions completed.
[+1009 ms] 1m 24s elapsed, 1357/1393 actions completed.
[+1090 ms] 1m 25s elapsed, 1357/1393 actions completed.
[+1004 ms] 1m 26s elapsed, 1357/1393 actions completed.
[ +998 ms] 1m 27s elapsed, 1357/1393 actions completed.
[+1096 ms] 1m 28s elapsed, 1358/1393 actions completed.
[+1098 ms] 1m 30s elapsed, 1358/1393 actions completed.
[+1002 ms] 1m 31s elapsed, 1358/1393 actions completed.
[+1002 ms] 1m 32s elapsed, 1360/1394 actions completed.
[+1097 ms] 1m 33s elapsed, 1361/1394 actions completed.
[ +998 ms] 1m 34s elapsed, 1361/1394 actions completed.
[+1102 ms] 1m 35s elapsed, 1361/1394 actions completed.
[ +999 ms] 1m 36s elapsed, 1361/1394 actions completed.
[+1098 ms] 1m 37s elapsed, 1361/1394 actions completed.
[+1006 ms] 1m 38s elapsed, 1361/1394 actions completed.
[+1091 ms] 1m 39s elapsed, 1362/1394 actions completed.
[+1000 ms] 1m 40s elapsed, 1362/1394 actions completed.
[+1100 ms] 1m 41s elapsed, 1362/1394 actions completed.
[+1101 ms] 1m 42s elapsed, 1364/1394 actions completed.
[+1099 ms] 1m 43s elapsed, 1364/1394 actions completed.
[+1001 ms] 1m 44s elapsed, 1364/1394 actions completed.
[+1098 ms] 1m 45s elapsed, 1364/1394 actions completed.
[+1098 ms] 1m 46s elapsed, 1364/1394 actions completed.
[+1100 ms] 1m 48s elapsed, 1364/1394 actions completed.
[+1000 ms] 1m 49s elapsed, 1364/1394 actions completed.
[ +999 ms] 1m 50s elapsed, 1364/1394 actions completed.
[+1001 ms] 1m 51s elapsed, 1364/1394 actions completed.
[+1101 ms] 1m 52s elapsed, 1364/1394 actions completed.
[+1097 ms] 1m 53s elapsed, 1364/1394 actions completed.
[+1099 ms] 1m 54s elapsed, 1364/1394 actions completed.
[+1100 ms] 1m 55s elapsed, 1364/1394 actions completed.
[+1099 ms] 1m 56s elapsed, 1364/1394 actions completed.
[ +504 ms] No actions completed for 15.0s, waiting on:
             - flutter_tools:ddc on package:flutter/widgets.flutter_web.module
             - flutter_tools:ddc on package:flutter/cupertino.flutter_web.module
             - flutter_tools:ddc on package:flutter/material.flutter_web.module
             - flutter_tools:ddc on package:flutter/src/cupertino/action_sheet.flutter_web.module
             - flutter_tools:ddc on package:flutter/cupertino.flutter_web.module
             .. and 25 more

[+1094 ms] 1m 58s elapsed, 1364/1394 actions completed.
[+1001 ms] 1m 59s elapsed, 1364/1394 actions completed.
[+1006 ms] 2m 0s elapsed, 1364/1394 actions completed.
[+1093 ms] 2m 1s elapsed, 1364/1394 actions completed.
[+1006 ms] 2m 2s elapsed, 1364/1394 actions completed.
[+1102 ms] 2m 3s elapsed, 1364/1394 actions completed.
[+1090 ms] 2m 4s elapsed, 1364/1394 actions completed.
[+1099 ms] 2m 5s elapsed, 1364/1394 actions completed.
[+1099 ms] 2m 6s elapsed, 1364/1394 actions completed.
[+1100 ms] 2m 7s elapsed, 1365/1394 actions completed.
[+1012 ms] 2m 8s elapsed, 1365/1394 actions completed.
[+1088 ms] 2m 9s elapsed, 1365/1394 actions completed.
[+1098 ms] 2m 10s elapsed, 1367/1394 actions completed.
[+1000 ms] 2m 11s elapsed, 1367/1394 actions completed.
[+1006 ms] 2m 12s elapsed, 1367/1394 actions completed.
[+1092 ms] 2m 14s elapsed, 1367/1394 actions completed.
[+1000 ms] 2m 15s elapsed, 1367/1394 actions completed.
[+1101 ms] 2m 16s elapsed, 1367/1394 actions completed.
[+1096 ms] 2m 17s elapsed, 1367/1394 actions completed.
[+1002 ms] 2m 18s elapsed, 1367/1394 actions completed.
[+1012 ms] 2m 19s elapsed, 1367/1394 actions completed.
[+1086 ms] 2m 20s elapsed, 1368/1394 actions completed.
[+1099 ms] 2m 21s elapsed, 1368/1394 actions completed.
[+1039 ms] 2m 22s elapsed, 1368/1394 actions completed.
[+1060 ms] 2m 23s elapsed, 1368/1394 actions completed.
[+1006 ms] 2m 24s elapsed, 1368/1394 actions completed.
[+1093 ms] 2m 25s elapsed, 1368/1394 actions completed.
[+1099 ms] 2m 26s elapsed, 1368/1394 actions completed.
[ +999 ms] 2m 27s elapsed, 1368/1394 actions completed.
[+1000 ms] 2m 28s elapsed, 1368/1394 actions completed.
[+1098 ms] 2m 29s elapsed, 1368/1394 actions completed.
[+1005 ms] 2m 30s elapsed, 1368/1394 actions completed.
[+1004 ms] 2m 31s elapsed, 1368/1394 actions completed.
[+1092 ms] 2m 32s elapsed, 1368/1394 actions completed.
[+1098 ms] 2m 34s elapsed, 1368/1394 actions completed.
[ +700 ms] No actions completed for 15.1s, waiting on:
             - flutter_tools:ddc on package:flutter/material.flutter_web.module
             - flutter_tools:ddc on package:flutter/material.flutter_web.module
             - flutter_tools:ddc on package:url_launcher_platform_interface/method_channel_url_launcher.flutter_web.module
             - flutter_tools:ddc on package:flutter_web_plugins/flutter_web_plugins.flutter_web.module
             - flutter_tools:ddc on package:url_launcher_web/url_launcher_web.flutter_web.module
             .. and 21 more

[+1099 ms] 2m 35s elapsed, 1368/1394 actions completed.
[+1133 ms] 2m 36s elapsed, 1369/1394 actions completed.
[+1075 ms] 2m 38s elapsed, 1369/1394 actions completed.
[+1090 ms] 2m 39s elapsed, 1369/1394 actions completed.
[+1000 ms] 2m 40s elapsed, 1369/1394 actions completed.
[ +999 ms] 2m 41s elapsed, 1369/1394 actions completed.
[+1099 ms] 2m 42s elapsed, 1369/1394 actions completed.
[+1103 ms] 2m 43s elapsed, 1369/1394 actions completed.
[+1112 ms] 2m 44s elapsed, 1371/1394 actions completed.
[+1082 ms] 2m 45s elapsed, 1375/1394 actions completed.
[+1001 ms] 2m 46s elapsed, 1377/1394 actions completed.
[+1097 ms] 2m 47s elapsed, 1385/1394 actions completed.
[+1211 ms] 2m 48s elapsed, 1394/1394 actions completed.
[ +184 ms] Running build completed, took 2m 48s

[   +1 ms] Caching finalized dependency graph...
[ +903 ms] 2m 49s elapsed, 2559/2559 actions completed.
[  +51 ms] Caching finalized dependency graph completed, took 1.1s

[   +1 ms] Succeeded after 2m 49s with 1304 outputs (2559 actions)

[  +48 ms] Building application for the web... (completed in 263,6s)
[   +1 ms] Attempting to connect to browser instance..
[+43751 ms] Debug service listening on ws://127.0.0.1:59159/FbqvvxF0cz8=

[ +639 ms]       Failed to load asset at path: packages/build_web_compilers/src/dev_compiler/dart_sdk.js.

                 Status code: 404

                 Headers:
                 {
             "date": "Mon, 16 Dec 2019 13:51:36 GMT",
             "content-length": "9",
             "x-frame-options": "SAMEORIGIN",
             "content-type": "text/plain; charset=utf-8",
             "x-xss-protection": "1; mode=block",
             "x-content-type-options": "nosniff",
             "server": "dart:io with Shelf",
             "via": "1.1 shelf_proxy"
           }

                 Content:
                 Not Found}

[ +674 ms] Attempting to connect to browser instance.. (completed in 45,1s, longer than expected)
[   +1 ms] Warning: Flutter's support for web development is not stable yet and hasn't
[        ] been thoroughly tested in production environments.
[        ] For more information see https://flutter.dev/web
[        ] 🔥  To hot restart changes while running, press "r". To hot restart (and refresh the browser), press "R".
[        ] For a more detailed help message, press "h". To quit, press "q".
[   +8 ms] Debug service listening on ws://127.0.0.1:59159/FbqvvxF0cz8=
```

**Comment by iapicca** [comment]
Thank you for the logs @marvinIsSacul

**Comment by JoeEarly** [comment]
Am getting a very similar log output when just trying a normal `flutter run -d chrome --verbose`


```
 Failed to load asset at path: packages/build_web_compilers/src/dev_compiler/dart_sdk.js.

Status code: 404
 Headers:
                          {
                      "date": "Sat, 28 Dec 2019 00:02:54 GMT",
                      "content-length": "9",
                      "x-frame-options": "SAMEORIGIN",
                      "content-type": "text/plain; charset=utf-8",
                      "x-xss-protection": "1; mode=block",
                      "x-content-type-options": "nosniff",
                      "server": "dart:io with Shelf",
                      "via": "1.1 shelf_proxy"
                    }

                          Content:
                          Not Found}

```

**Comment by marvinIsSacul** [comment]
@JoeEarly  I am not longer getting this error (well at least not after changing my `pubspec.yaml` file).

Please paste your `pubspec.yaml` contents so I can have a look.

**Comment by marcusgregory** [comment]
I am also getting this error in the release version, but in the debug version it works perfectly.
Does anyone know how to solve this problem?

**Comment by R3NL3N** [comment]
> @JoeEarly I am not longer getting this error (well at least not after changing my `pubspec.yaml` file).
> 
> Please paste your `pubspec.yaml` contents so I can have a look.

What did you change in your `pubsec.yaml` file ?

**Comment by R3NL3N** [comment]
After updating Flutter ´flutter upgrade´ and all the packages ´flutter pub upgrade´, the problem seems to be resolved. I'm able to build a web version of my app.

**Comment by svongripp** [comment]
Any updates or suggestions for this? I'm getting error: 

Could not load content for org-dartlang-sdk:///sdk/lib/_internal/js_runtime/lib/js_helper.dart : HTTP status code: 404

Flutter and packages all up to date. On beta channel.

**Comment by JoeEarly** [comment]
@R3NL3N @marvinIsSacul Once I did upgrade all was ok again

**Comment by yjbanov** [comment]
This message `Failed to load asset at path: packages/build_web_compilers/src/dev_compiler/dart_sdk.js.` is not fatal. I filed https://github.com/flutter/flutter/issues/49002 for us to stop printing it. It's been a source of confusion lately.

The `Uncaught Assertion failed` error and `Could not load content for org-dartlang-sdk:...` are more concerning.
