### ISSUE TITLE
Android license status unknown.

### ISSUE THREAD

**Issue by anandrajak2** [flutter/flutter#47118]
using flutter doctor on cmd it given this type of error

 ```bash
Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    X Android license status unknown.
      Try re-installing or updating your Android SDK Manager.
      See https://developer.android.com/studio/#downloads or visit https://flutter.dev/setup/#android-setup for detailed
      instructions.


i tried flutter doctor --android-licenses command but it given new error like

A newer version of the Android SDK is required. To update, run:
/Users/eric/Library/Android/sdk/tools/bin/sdkmanager --update
```

after i run these command
C:\Users\Kratos\AppData\Local\Android\sdk\tools\bin\sdkmanager --update
it gives me these errror

```bash
Exception in thread "main" java.lang.NoClassDefFoundError: javax/xml/bind/annotation/XmlSchema
        at com.android.repository.api.SchemaModule$SchemaModuleVersion.<init>(SchemaModule.java:156)
        at com.android.repository.api.SchemaModule.<init>(SchemaModule.java:75)
        at com.android.sdklib.repository.AndroidSdkHandler.<clinit>(AndroidSdkHandler.java:81)
        at com.android.sdklib.tool.sdkmanager.SdkManagerCli.main(SdkManagerCli.java:73)
        at com.android.sdklib.tool.sdkmanager.SdkManagerCli.main(SdkManagerCli.java:48)
Caused by: java.lang.ClassNotFoundException: javax.xml.bind.annotation.XmlSchema
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:602)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
```

![image](https://user-images.githubusercontent.com/16650399/70891114-9a618480-200c-11ea-9879-25e4d8756cc0.png)

**Comment by iapicca** [comment]
Hi @anandrajak2 
the `doctor` suggested:
`Try re-installing or updating your Android SDK Manager.`.

As the update failed you may want to try reinstalling the sdk;
let me know if the issue persists
thank you

**Comment by chenzong24635** [comment]
same problem

**Comment by Hixie** [comment]
Did you try re-installing or updating your Android SDK Manager?

Without clear steps for how to reproduce this there's not really much we can do.
