### ISSUE TITLE
Flutter build failing after upgrading to 

### ISSUE THREAD

**Issue by CoderJerry** [flutter/flutter#47126]
<details>
  <summary>logs</summary>

```bash
D8: Program type already present: io.flutter.BuildConfig                
com.android.builder.dexing.DexArchiveMergerException: Error while merging dex archives: 
Learn how to resolve the issue at https://developer.android.com/studio/build/dependencies#duplicate_classes.
Program type already present: io.flutter.BuildConfig
        at com.android.builder.dexing.D8DexArchiveMerger.getExceptionToRethrow(D8DexArchiveMerger.java:131)
        at com.android.builder.dexing.D8DexArchiveMerger.mergeDexArchives(D8DexArchiveMerger.java:118)
        at com.android.build.gradle.internal.transforms.DexMergerTransformCallable.call(DexMergerTransformCallable.java:102)
        at com.android.build.gradle.internal.tasks.DexMergingTaskRunnable.run(DexMergingTask.kt:444)
        at com.android.build.gradle.internal.tasks.Workers$ActionFacade.run(Workers.kt:335)
        at org.gradle.workers.internal.AdapterWorkAction.execute(AdapterWorkAction.java:50)
        at org.gradle.workers.internal.DefaultWorkerServer.execute(DefaultWorkerServer.java:47)
        at org.gradle.workers.internal.NoIsolationWorkerFactory$1$1$1.create(NoIsolationWorkerFactory.java:65)
        at org.gradle.workers.internal.NoIsolationWorkerFactory$1$1$1.create(NoIsolationWorkerFactory.java:61)
        at org.gradle.internal.classloader.ClassLoaderUtils.executeInClassloader(ClassLoaderUtils.java:98)
        at org.gradle.workers.internal.NoIsolationWorkerFactory$1$1.execute(NoIsolationWorkerFactory.java:61)
        at org.gradle.workers.internal.AbstractWorker$1.call(AbstractWorker.java:44)
        at org.gradle.workers.internal.AbstractWorker$1.call(AbstractWorker.java:41)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$CallableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:416)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$CallableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:406)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$1.execute(DefaultBuildOperationExecutor.java:165)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:250)  
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:158)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.call(DefaultBuildOperationExecutor.java:102)     
        at org.gradle.internal.operations.DelegatingBuildOperationExecutor.call(DelegatingBuildOperationExecutor.java:36)
        at org.gradle.workers.internal.AbstractWorker.executeWrappedInBuildOperation(AbstractWorker.java:41)
        at org.gradle.workers.internal.NoIsolationWorkerFactory$1.execute(NoIsolationWorkerFactory.java:56)
        at org.gradle.workers.internal.DefaultWorkerExecutor$3.call(DefaultWorkerExecutor.java:215)        
        at org.gradle.workers.internal.DefaultWorkerExecutor$3.call(DefaultWorkerExecutor.java:210)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)     
        at org.gradle.internal.work.DefaultConditionalExecutionQueue$ExecutionRunner.runExecution(DefaultConditionalExecutionQueue.java:215)
        at org.gradle.internal.work.DefaultConditionalExecutionQueue$ExecutionRunner.runBatch(DefaultConditionalExecutionQueue.java:164)
        at org.gradle.internal.work.DefaultConditionalExecutionQueue$ExecutionRunner.run(DefaultConditionalExecutionQueue.java:131)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
        at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:48)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:56)
        at java.lang.Thread.run(Thread.java:745)
Caused by: com.android.tools.r8.CompilationFailedException: Compilation failed to complete
        at com.android.tools.r8.utils.t.a(:55)
        at com.android.tools.r8.D8.run(:11)
        at com.android.builder.dexing.D8DexArchiveMerger.mergeDexArchives(D8DexArchiveMerger.java:116)
        ... 34 more
Caused by: com.android.tools.r8.utils.AbortException: Error: Program type already present: io.flutter.BuildConfig
        at com.android.tools.r8.utils.Reporter.a(:21)
        at com.android.tools.r8.utils.Reporter.a(:7)
        at com.android.tools.r8.utils.t.a(:36)
        ... 36 more


FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:mergeExtDexDebug'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.Workers$ActionFacade
   > com.android.builder.dexing.DexArchiveMergerException: Error while merging dex archives: 
     Learn how to resolve the issue at https://developer.android.com/studio/build/dependencies#duplicate_classes.
     Program type already present: io.flutter.BuildConfig

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 40s
Running Gradle task 'assembleDebug'...
Running Gradle task 'assembleDebug'... Done                        42.5s
[!] The shrinker may have failed to optimize the Java bytecode.
    To disable the shrinker, pass the `--no-shrink` flag to this command.
    To learn more, see: https://developer.android.com/studio/build/shrink-code
Gradle task assembleDebug failed with exit code 1
```

</details>

flutter doctor -v
```bash
[√] Flutter (Channel stable, v1.12.13+hotfix.5, on Microsoft Windows [Version 10.0.18362.535], locale en-IN)

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[√] Android Studio (version 3.4)
[√] VS Code, 64-bit edition (version 1.40.2)
[√] Connected device (2 available)
```

**Comment by iapicca** [comment]
Hi @CoderJerry 
could you please run
`flutter clean`
`flutter pub cache repair`
if the issue persists,
can you please provide your `flutter doctor -v`
and your `flutter run --verbose`?
Thank you

**Comment by Xgamefactory** [comment]
hi @iapicca 
we did flutter clean and pub cache  repair.
here is the output for flutter doctor -v

we can flutter run but getting error when trying to build android app bundle for playstore.


```
FAILURE: Build failed with an exception.                                
                                                                        
* Where:                                                                
Build file '/Users/fersmart/Projects_all/markod_mobile/android/build.gradle' line: 41
                                                                        
* What went wrong:                                                      
A problem occurred evaluating root project 'android'.                   
> A problem occurred configuring project ':app'.                        
   > Removing unused resources requires unused code shrinking to be turned on. See http://d.android.com/r/tools/shrink-resources.html for more information.
                                                                        
* Try:                                                                  
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
                                                                        
* Get more help at https://help.gradle.org                              
                                                                        
BUILD FAILED in 0s                                                      
Running Gradle task 'bundleRelease'...                                  
Running Gradle task 'bundleRelease'... Done                         2.0s
Gradle task bundleRelease failed with exit code 1
```

```

[✓] Flutter (Channel stable, v1.12.13+hotfix.5, on Mac OS X 10.14.6 18G103, locale en-TR)
    • Flutter version 1.12.13+hotfix.5 at /Users/fersmart/SDK_all/flutter
    • Framework revision 27321ebbad (6 days ago), 2019-12-10 18:15:01 -0800
    • Engine revision 2994f7e1e6
    • Dart version 2.7.0

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/fersmart/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.3, Build version 11C29
    • CocoaPods version 1.7.5

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 42.1.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] VS Code (version 1.41.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.7.1

[✓] Connected device (2 available)
    • SM G965F        • 24194f98b60c7ece          • android-arm64 • Android 9 (API 28)
    • iPhone Fersmart • 00008020-000E49DA0CD8003A • ios           • iOS 13.2.2

• No issues found!
```

**Comment by Xgamefactory** [comment]
after completing migration steps here https://github.com/flutter/flutter/wiki/Upgrading-pre-1.12-Android-projects

getting different errors.

```
Note: /Users/fersmart/SDK_all/flutter/.pub-cache/hosted/pub.dartlang.org/package_info-0.4.0+10/android/src/main/java/io/flutter/plugins/packageinfo/PackageInfoPlugin.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
/Users/fersmart/SDK_all/flutter/.pub-cache/hosted/pub.dartlang.org/shared_preferences-0.5.6/android/src/main/java/io/flutter/plugins/sharedpreferences/SharedPreferencesPlugin.java:25: warning: [deprecation] getFlutterEngine() in FlutterPluginBinding has been deprecated
    setupChannel(binding.getFlutterEngine().getDartExecutor(), binding.getApplicationContext());
                        ^
1 warning
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:processDebugResources'.
> Android resource linking failed
  /Users/fersmart/Projects_all/markod_mobile/build/app/intermediates/merged_manifests/debug/AndroidManifest.xml:66: AAPT: error: resource style/LaunchTheme (aka com.fersmart.markod:style/LaunchTheme) not found.

  error: failed processing manifest.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 18s
The built failed likely due to AndroidX incompatibilities in a plugin. The tool is about to try using Jetfier to solve the incompatibility.
[!] Flutter tried to create the file `android/settings_aar.gradle`, but failed.
To manually update `settings.gradle`, follow these steps:
    1. Copy `settings.gradle` as `settings_aar.gradle`
    2. Remove the following code from `settings_aar.gradle`:
            def flutterProjectRoot = rootProject.projectDir.parentFile.toPath()
            def plugins = new Properties()
            def pluginsFile = new File(flutterProjectRoot.toFile(), '.flutter-plugins')
            if (pluginsFile.exists()) {
                pluginsFile.withReader('UTF-8') { reader -> plugins.load(reader) }
            }
            plugins.each { name, path ->
                def pluginDirectory = flutterProjectRoot.resolve(path).resolve('android').toFile()
                include ":$name"
                project(":$name").projectDir = pluginDirectory
            }
Please create the file and run this command again.
```

**Comment by CoderJerry** [comment]
issue got resolved for me after doing
flutter clean
flutter pub cache repair

**Comment by iapicca** [comment]
Hi  @CoderJerry 
I'm glad to hear that!
thank you for letting me know

@Xgamefactory is yours an "add_to_app" project?

**Comment by Xgamefactory** [comment]
@iapicca it is pure flutter mobile app project.

**Comment by nihalreddy33** [comment]
@iapicca is the issue resolved for you? flutter pub cache repair didn't work for me

**Comment by iapicca** [comment]
Hi @Xgamefactory  @nihalreddy33 
you may post here  your `flutter doctor -v` ,
your `flutter run --verbose` and possibly
a minimal code sample
or open a separate issue, as you wish.
Thank you

**Comment by jonahwilliams** [comment]
@tvolkert possibly another update android issue bug

**Comment by jonahwilliams** [comment]
Without a response we're unable to make any progress. I'm closing the issue, but don't hesitate to file a new one if you have the time.

**Comment by AdvaitKale01** [comment]
> Hi @CoderJerry
> could you please run
> `flutter clean`
> `flutter pub cache repair`
> if the issue persists,
> can you please provide your `flutter doctor -v`
> and your `flutter run --verbose`?
> Thank you

THat worked for me too.

**Comment by namanawasthi** [comment]
If none of the above technique works simple downgrade your gradle build level. This will solve your problem.

dependencies {
        classpath 'com.android.tools.build:gradle:3.5.0'
    }

**Comment by Mereep** [comment]
I had the problem right now also. I did two things BEFORE the error: Refactored to Android X (using Android Studio Refactor) & added some keys to the Android Manifest.

All cleaning cache like described didn't help, *However, removing the added keys from the Android Manifest did*. It seems this error can be triggered by a Manifest having unexpected keys.

**Comment by iapicca** [comment]
@Mereep @namanawasthi 
this issue is very old and refers to an obsolete version of flutter
I recommend to open a new issue providing your `flutter doctor -v`, your logs and the steps to reproduce the issue

**Comment by Mereep** [comment]
This happened right now on `Channel stable, 2.0.6, on macOS 11.2.3 20D91 darwin-x64, locale de-DE)` which, according to flutter doctor is a 3 Week old revision. 

And I already fixed it as described.
