### ISSUE TITLE
[tool_crash] NoSuchMethodError: The method 'reinitialize' was called on null.Receiver: nullTried calling: reinitialize()

### ISSUE THREAD

**Issue by ebbyferguson** [flutter/flutter#47121]
## Command
  ```
  flutter build apk
  ```

  ## Logs
  ```bash
  NoSuchMethodError: NoSuchMethodError: The method 'reinitialize' was called on null.
Receiver: null
Tried calling: reinitialize()
  ```

  ```bash
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:53:5)
#1      _AndroidBuilderImpl.buildApk (package:flutter_tools/src/android/android_builder.dart:109:18)
<asynchronous suspension>
#2      BuildApkCommand.runCommand (package:flutter_tools/src/commands/build_apk.dart:105:26)
#3      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:626:18)
#4      _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:74:64)
#5      _rootRunUnary (dart:async/zone.dart:1134:38)
#6      _CustomZone.runUnary (dart:async/zone.dart:1031:19)
#7      _FutureListener.handleValue (dart:async/future_impl.dart:140:18)
#8      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:682:45)
#9      Future._propagateToListeners (dart:async/future_impl.dart:711:32)
#10     Future._completeWithValue (dart:async/future_impl.dart:526:5)
#11     Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:556:7)
#12     _rootRun (dart:async/zone.dart:1126:13)
#13     _CustomZone.run (dart:async/zone.dart:1023:19)
#14     _CustomZone.runGuarded (dart:async/zone.dart:925:7)
#15     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:965:23)
#16     _microtaskLoop (dart:async/schedule_microtask.dart:43:21)
#17     _startMicrotaskLoop (dart:async/schedule_microtask.dart:52:5)
#18     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
  ```
  ```bash
  [✓] Flutter (Channel master, v1.13.3-pre.23, on Mac OS X 10.15.1 19B88, locale en-US)
    • Flutter version 1.13.3-pre.23 at /Users/ferguson/flutter
    • Framework revision c06bf6503a (2 days ago), 2019-12-13 17:42:35 -0500
    • Engine revision e0e0ac0a68
    • Dart version 2.8.0 (build 2.8.0-dev.0.0 45db297095)

[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/setup/#android-setup for detailed instructions).
      If the Android SDK has been installed to a custom location, set ANDROID_HOME to that location.
      You may also want to add it to your PATH environment variable.


[✓] Xcode - develop for iOS and macOS (Xcode 11.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.3, Build version 11C29
    • CocoaPods version 1.8.4

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 41.0.2
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] VS Code (version 1.41.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.7.1

[✓] Connected device (3 available)
    • iPhone 11  • 45BAA160-124F-4DCC-854A-478B62DED189 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-13-3 (simulator)
    • Chrome     • chrome                               • web-javascript • Google Chrome 78.0.3904.108
    • Web Server • web-server                           • web-javascript • Flutter Tools

! Doctor found issues in 1 category.

  ```

  ## Flutter Application Metadata
  **Version**: 1.0.0+1
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
### Plugins

```yaml
google_maps_flutter
image_picker
shared_preferences
url_launcher
```

**Comment by jonahwilliams** [comment]
We definitely shouldn't crash here, but looking at your flutter doctor it looks like the Android SDK cannot be located.  Have you installed and configured this correctly?

**Comment by ebbyferguson** [comment]
Yes the Android SDK was installed and configure. I had been working on the project for a while and for some reason it wasn't working this time. I will close the project now. I was able to fix by by setting the SDK platform tool in android studio for the project.
