### ISSUE TITLE
Can't load flutter

### ISSUE THREAD

**Issue by elrondliu** [flutter/flutter#47129]
After upgrade flutter sdk to 1.12, start my flutter activity, it's black.

```bash
#0      _AssertionError._doThrowNew (dart:core-patch/errors_patch.dart:42:39)
#1      _AssertionError._throwNew (dart:core-patch/errors_patch.dart:38:5)
#2      SchedulerBinding.addTimingsCallback (package:flutter/src/scheduler/binding.dart:232:12)
#3      WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:768:33)
#4      RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:283:5)
#5      SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1102:15)
#6      SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1041:9)
#7      SchedulerBinding.scheduleWarmUpFrame.<anonymous closure> (package:flutter/src/scheduler/binding.dart:850:7)
#8      _rootRun (dart:async/zone.dart:1122:38)
#9      _CustomZone.run (dart:async/zone.dart:1023:19)
#10     _CustomZone.runGuarded (dart:async/zone.dart:925:7)
#11     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:965:23)
#12     _rootRun (dart:async/zone.dart:1126:13)
#13     _CustomZone.run (dart:async/zone.dart:1023:19)
#14     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:949:23)
#15     Timer._createTimer.<anonymous closure> (dart:async-patch/timer_patch.dart:23:15)
#16     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:384:19)
#17     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:418:5)
#18     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:174:12)
```

Doctor summary (to see all details, run flutter doctor -v):
```bash
[✓] Flutter (Channel stable, v1.12.13+hotfix.5, on Mac OS X 10.15.2 19C57, locale zh-Hans-CN)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 11.3)
[✓] Android Studio (version 3.5)
[✓] VS Code (version 1.40.2)
[✓] Connected device (1 available)

• No issues found!
```

**Comment by iapicca** [comment]
Hi @elrondliu 
could you please run 
`flutter clean`
`flutter pub cache repair`
If the issue persist please provide your updated 
`flutter doctor -v` and `flutter run --verbose`
together with a a minimal code sample to reproduce the problem.

Are you using [add-to-app](https://flutter.dev/docs/development/add-to-app)?
thank you

**Comment by elrondliu** [comment]
I'm sorry I have found our bug, thank you.
