### ISSUE TITLE
Flutter should warn when attempting to flutter install to simulator

### ISSUE THREAD

**Issue by PedroTheRealOne** [flutter/flutter#47147]
I try install my app in any IOS device (Simulator and real device) get's me this error. I'm using flavors in this project, but when i build and install for android everything works fine.
Using ios debug and ``` flutter run ``` works fine as well

Flutter install error:
```
Install failed

#0      throwToolExit (package:flutter_tools/src/base/common.dart:28:3)
#1      InstallCommand.runCommand (package:flutter_tools/src/commands/install.dart:44:7)
<asynchronous suspension>
#2      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:478:18)
<asynchronous suspension>
#3      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:383:33)
<asynchronous suspension>
#4      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:29)
<asynchronous suspension>
#5      _rootRun (dart:async/zone.dart:1124:13)
#6      _CustomZone.run (dart:async/zone.dart:1021:19)
#7      _runZoned (dart:async/zone.dart:1516:10)
#8      runZoned (dart:async/zone.dart:1463:12)
#9      AppContext.run (package:flutter_tools/src/base/context.dart:152:18)
<asynchronous suspension>
#10     FlutterCommand.run (package:flutter_tools/src/runner/flutter_command.dart:375:20)
#11     CommandRunner.runCommand (package:args/command_runner.dart:197:27)
<asynchronous suspension>
#12     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:396:21)
<asynchronous suspension>
#13     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:29)
<asynchronous suspension>
#14     _rootRun (dart:async/zone.dart:1124:13)
#15     _CustomZone.run (dart:async/zone.dart:1021:19)
#16     _runZoned (dart:async/zone.dart:1516:10)
#17     runZoned (dart:async/zone.dart:1463:12)
#18     AppContext.run (package:flutter_tools/src/base/context.dart:152:18)
<asynchronous suspension>
#19     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:356:19)
<asynchronous suspension>
#20     CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:112:25)
#21     new Future.sync (dart:async/future.dart:224:31)
#22     CommandRunner.run (package:args/command_runner.dart:112:14)
#23     FlutterCommandRunner.run (package:flutter_tools/src/runner/flutter_command_runner.dart:242:18)
#24     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:62:22)
<asynchronous suspension>
#25     _rootRun (dart:async/zone.dart:1124:13)
#26     _CustomZone.run (dart:async/zone.dart:1021:19)
#27     _runZoned (dart:async/zone.dart:1516:10)
#28     runZoned (dart:async/zone.dart:1500:12)
#29     run.<anonymous closure> (package:flutter_tools/runner.dart:60:18)
<asynchronous suspension>
#30     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:29)
<asynchronous suspension>
#31     _rootRun (dart:async/zone.dart:1124:13)
#32     _CustomZone.run (dart:async/zone.dart:1021:19)
#33     _runZoned (dart:async/zone.dart:1516:10)
#34     runZoned (dart:async/zone.dart:1463:12)
#35     AppContext.run (package:flutter_tools/src/base/context.dart:152:18)
<asynchronous suspension>
#36     runInContext (package:flutter_tools/src/context_runner.dart:56:24)
<asynchronous suspension>
#37     run (package:flutter_tools/runner.dart:51:10)
#38     main (package:flutter_tools/executable.dart:62:9)
<asynchronous suspension>
#39     main (file:///Users/pedro_myeong/Desktop/flutter/packages/flutter_tools/bin/flutter_tools.dart:8:3)
#40     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:299:32)
#41     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:12)
```

Flutter doctor -v:
```
[✓] Flutter (Channel stable, v1.7.8+hotfix.3, on Mac OS X 10.14.6 18G103, locale en-US)
    • Flutter version 1.7.8+hotfix.3 at /Users/pedro_myeong/Desktop/flutter
    • Framework revision b712a172f9 (5 months ago), 2019-07-09 13:14:38 -0700
    • Engine revision 54ad777fd2
    • Dart version 2.4.0

[!] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/pedro_myeong/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Library/Java/JavaVirtualMachines/jdk-10.0.1.jdk/Contents/Home/bin/java
    • Java version Java(TM) SE Runtime Environment 18.3 (build 10.0.1+10)
    ✗ Android license status unknown.
      Try re-installing or updating your Android SDK Manager.
      See https://developer.android.com/studio/#downloads or visit https://flutter.dev/setup/#android-setup for detailed instructions.

[✓] Xcode - develop for iOS and macOS (Xcode 10.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.3, Build version 10G8
    • CocoaPods version 1.7.5

[✓] iOS tools - develop for iOS devices
    • ios-deploy 1.9.4

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/setup/#android-setup for detailed instructions).

[✓] Connected device (1 available)
    • iPhone de Pedro • f6de5020e89defb2cb58089bb965423ada8d2054 • ios • iOS 13.1.3

! Doctor found issues in 2 categories.
```

**Comment by iapicca** [comment]
Hi @PedroTheRealOne 
does this [solution ](https://github.com/flutter/flutter/issues/47158) works for you?
thank you

**Comment by PedroTheRealOne** [comment]
> Hi @PedroTheRealOne
> does this [solution ](https://github.com/flutter/flutter/issues/47158) works for you?
> thank you

Doesn't work for me

**Comment by PedroTheRealOne** [comment]
In `flutter install` :
```
[   +1 ms] $(PRODUCT_BUNDLE_IDENTIFIER)
[   +7 ms] Installing br.com.nexusoficial.lojista to iPhone 7...
[   +1 ms] executing: /usr/bin/xcrun simctl get_app_container 52D0E992-73E0-4E1E-A6A4-87D6710C6E5A br.com.nexusoficial.lojista
[ +347 ms] executing: /usr/bin/xcrun simctl install 52D0E992-73E0-4E1E-A6A4-87D6710C6E5A build/ios/iphonesimulator/Runner.app
[ +242 ms] An error was encountered processing the command (domain=NSPOSIXErrorDomain, code=2):
                    lstat of /Users/pedro_myeong/Documents/Quantum/Projects/nexus/nexus-lojista/build/ios/iphonesimulator/Runner.app failed: No
                    such file or directory
                    No such file or directory
```
Not finding the correct bundle. In the flavors i change the app bundles to .dev, .hmg. I suppose he is not changing my app bundle

**Comment by PedroTheRealOne** [comment]
I build and install in a real device and works fine.
This problems only occurs when i try to install in a simulator.
My build doesn't generate this path: `build/ios/iphonesimulator/Runner.app`, generate this path: `build/ios/iphoneos/Runner.app`
There is any config that change this?

**Comment by jonahwilliams** [comment]
You can't install an application to a phone with flutter install, and build iOS does not build for a simulator. We should provide a better error message here

**Comment by LouiseHsu** [comment]
Closed as obsolete
