### ISSUE TITLE
attempt to use RotoColorEmoji.ttf causes crash on iOS simulator

### ISSUE THREAD

**Issue by corymalcolmtaylor** [flutter/flutter#47148]
I downloaded RotoColorEmoji.ttf from the https://www.google.com/get/noto/ and included it in my Flutter app.  It seems to work ok in the Android emulator but attempts to run the app in the iOS simulator crash on app load.
 
I get this message in the debug console:
 Launching lib/main.dart on iPhone 11 in debug mode...
Xcode build done.                                           118.3s
[VERBOSE-2:FontFamily.cpp(184)] Could not get cmap table size!
[VERBOSE-3:FontCollection.cpp(95)] nTypefaces == 0
Lost connection to device.
Exited (sigterm)
## Steps to Reproduce

1. git clone app at https://github.com/corymalcolmtaylor/game_maze.git 
(as of commit   f109cf606f8371ba072fe9411654a209fdec446a  )
2. run the app in an iOS simulator
3. app will crash and the following message will be in the debug console:
```
[VERBOSE-2:FontFamily.cpp(184)] Could not get cmap table size!
[VERBOSE-3:FontCollection.cpp(95)] nTypefaces == 0
Lost connection to device.

```
 

So far i have observed this on iOS simulators for iOS 13.2.  It does not seem to affect android emulators.
 
**Target Platform:**  iOS
**Target OS version/browser:**  iOS 13.2
**Devices:**  iOS simulator iPhone 8 and 11 tested

## Logs

```
flutter run --verbose
[  +41 ms] executing: [/Volumes/macex/flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[ +130 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[   +4 ms] 27321ebbad34b0a3fafe99fac037102196d655ff
[   +1 ms] executing: [/Volumes/macex/flutter/] git describe --match v*.*.* --first-parent --long --tags
[ +301 ms] Exit code 0 from: git describe --match v*.*.* --first-parent --long --tags
[        ] v1.12.13+hotfix.5-0-g27321ebba
[  +53 ms] executing: [/Volumes/macex/flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[  +15 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/stable
[        ] executing: [/Volumes/macex/flutter/] git ls-remote --get-url origin
[  +20 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[ +184 ms] executing: [/Volumes/macex/flutter/] git rev-parse --abbrev-ref HEAD
[  +23 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] stable
[  +31 ms] executing: sw_vers -productName
[  +45 ms] Exit code 0 from: sw_vers -productName
[        ] Mac OS X
[        ] executing: sw_vers -productVersion
[  +37 ms] Exit code 0 from: sw_vers -productVersion
[        ] 10.15.2
[        ] executing: sw_vers -buildVersion
[  +34 ms] Exit code 0 from: sw_vers -buildVersion
[        ] 19C57
[ +113 ms] executing: /usr/bin/xcode-select --print-path
[  +41 ms] Exit code 0 from: /usr/bin/xcode-select --print-path
[        ] /Applications/Xcode.app/Contents/Developer
[   +4 ms] executing: /usr/bin/xcodebuild -version
[+1668 ms] Exit code 0 from: /usr/bin/xcodebuild -version
[        ] Xcode 11.2.1
           Build version 11B500
[ +156 ms] executing: /Volumes/macex/androidSDK/platform-tools/adb devices -l
[  +32 ms] Exit code 0 from: /Volumes/macex/androidSDK/platform-tools/adb devices -l
[        ] List of devices attached
           emulator-5554          device product:sdk_gphone_x86_64 model:Android_SDK_built_for_x86_64 device:generic_x86_64
           transport_id:1
[  +98 ms] executing: /Volumes/macex/flutter/bin/cache/artifacts/libimobiledevice/idevice_id -h
[ +127 ms] /usr/bin/xcrun simctl list --json devices
[ +216 ms] More than one device connected; please specify a device with the '-d <deviceId>' flag, or use '-d all' to act on all
devices.
[  +10 ms] /Volumes/macex/androidSDK/platform-tools/adb -s emulator-5554 shell getprop
[ +805 ms] ro.hardware = ranchu
[  +11 ms] Android SDK built for x86 64 • emulator-5554                        • android-x64 • Android 10 (API 29) (emulator)
[   +7 ms] iPhone 11                    • 161A8CFA-781E-4952-B4A2-6EBB19664920 • ios         •
com.apple.CoreSimulator.SimRuntime.iOS-13-2
           (simulator)
[  +39 ms] "flutter run" took 3,530ms.

#0      throwToolExit (package:flutter_tools/src/base/common.dart:28:3)
#1      RunCommand.validateCommand (package:flutter_tools/src/commands/run.dart:289:7)
<asynchronous suspension>
#2      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:590:11)
#3      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:515:33)
<asynchronous suspension>
#4      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:146:29)
#5      _rootRun (dart:async/zone.dart:1126:13)
#6      _CustomZone.run (dart:async/zone.dart:1023:19)
#7      _runZoned (dart:async/zone.dart:1518:10)
#8      runZoned (dart:async/zone.dart:1465:12)
#9      AppContext.run (package:flutter_tools/src/base/context.dart:145:18)
#10     FlutterCommand.run (package:flutter_tools/src/runner/flutter_command.dart:505:20)
#11     CommandRunner.runCommand (package:args/command_runner.dart:197:27)
#12     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:413:21)
<asynchronous suspension>
#13     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:146:29)
#14     _rootRun (dart:async/zone.dart:1126:13)
#15     _CustomZone.run (dart:async/zone.dart:1023:19)
#16     _runZoned (dart:async/zone.dart:1518:10)
#17     runZoned (dart:async/zone.dart:1465:12)
#18     AppContext.run (package:flutter_tools/src/base/context.dart:145:18)
#19     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:364:19)
#20     CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:112:25)
#21     new Future.sync (dart:async/future.dart:224:31)
#22     CommandRunner.run (package:args/command_runner.dart:112:14)
#23     FlutterCommandRunner.run (package:flutter_tools/src/runner/flutter_command_runner.dart:250:18)
#24     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:63:22)
#25     _rootRun (dart:async/zone.dart:1126:13)
#26     _CustomZone.run (dart:async/zone.dart:1023:19)
#27     _runZoned (dart:async/zone.dart:1518:10)
#28     runZoned (dart:async/zone.dart:1502:12)
#29     run.<anonymous closure> (package:flutter_tools/runner.dart:61:18)
<asynchronous suspension>
#30     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:146:29)
#31     _rootRun (dart:async/zone.dart:1126:13)
#32     _CustomZone.run (dart:async/zone.dart:1023:19)
#33     _runZoned (dart:async/zone.dart:1518:10)
#34     runZoned (dart:async/zone.dart:1465:12)
#35     AppContext.run (package:flutter_tools/src/base/context.dart:145:18)
#36     runInContext (package:flutter_tools/src/context_runner.dart:64:24)
#37     run (package:flutter_tools/runner.dart:50:10)
#38     main (package:flutter_tools/executable.dart:65:9)
#39     main (file:///Volumes/macex/flutter/packages/flutter_tools/bin/flutter_tools.dart:8:3)
#40     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:305:32)
#41     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:174:12)
```

```
flutter analyze
Analyzing game_maze...                                                  
No issues found! (ran in 10.4s)
```

```
flutter doctor -v
[✓] Flutter (Channel stable, v1.12.13+hotfix.5, on Mac OS X 10.15.2 19C57, locale en-CA)
    • Flutter version 1.12.13+hotfix.5 at /Volumes/macex/flutter
    • Framework revision 27321ebbad (6 days ago), 2019-12-10 18:15:01 -0800
    • Engine revision 2994f7e1e6
    • Dart version 2.7.0

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Volumes/macex/androidSDK
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.2.1, Build version 11B500
    • CocoaPods version 1.7.1

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 39.0.3
    • Dart plugin version 191.8423
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] VS Code (version 1.40.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.7.1

[✓] Connected device (2 available)
    • Android SDK built for x86 64 • emulator-5554                        • android-x64 • Android 10 (API 29) (emulator)
    • iPhone 11                    • 161A8CFA-781E-4952-B4A2-6EBB19664920 • ios         • com.apple.CoreSimulator.SimRuntime.iOS-13-2
      (simulator)

• No issues found!
```

**Comment by corymalcolmtaylor** [comment]
I guess that particular ttf uses a special format not compatible with macOS/iOS.

**Comment by kf6gpe** [comment]
Based on your comment, @corymalcolmtaylor , I'm going to close this as not a Flutter bug. Thanks for letting us know!
