### ISSUE TITLE
'Dart Analyzer has been terminated' with crash

### ISSUE THREAD

**Issue by Heitorpsoa** [flutter/flutter#47167]
I was getting the 'Dart Analyzer has been terminated' issue, so I follow some recommendations and deleted the 'cache' folder within the flutter bin folder and tried to flutter doctor. Then i got the following crash:

Flutter crash report; please file at https://github.com/flutter/flutter/issues.

## command

flutter doctor

## exception
```bash
ProcessException: ProcessException: The command failed
  Command: unzip -o -q /home/heitor/Desktop/dev/flutter/bin/cache/downloads/storage.googleapis.com/flutter_infra/flutter/2994f7e1e682039464cb25e31a78b86a3c59b695/linux-x64/artifacts.zip -d /home/heitor/Desktop/dev/flutter/bin/cache/artifacts/engine/linux-x64
```
<details>
  <summary>logs</summary>

```bash
#0      RunResult.throwException (package:flutter_tools/src/base/process.dart:141:5)
#1      _DefaultProcessUtils.runSync (package:flutter_tools/src/base/process.dart:399:17)
#2      _PosixUtils.unzip (package:flutter_tools/src/base/os.dart:170:18)
#3      CachedArtifact._downloadArchive.<anonymous closure> (package:flutter_tools/src/cache.dart:526:16)
<asynchronous suspension>
#4      CachedArtifact._withDownloadFile (package:flutter_tools/src/cache.dart:545:26)
#5      CachedArtifact._downloadArchive (package:flutter_tools/src/cache.dart:512:12)
#6      CachedArtifact._downloadZipArchive (package:flutter_tools/src/cache.dart:532:12)
#7      EngineCachedArtifact.updateInner (package:flutter_tools/src/cache.dart:680:13)
<asynchronous suspension>
#8      CachedArtifact.update (package:flutter_tools/src/cache.dart:462:11)
#9      Cache.updateAll (package:flutter_tools/src/cache.dart:360:24)
<asynchronous suspension>
#10     FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:595:19)
<asynchronous suspension>
#11     FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:515:33)
<asynchronous suspension>
#12     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:146:29)
#13     _rootRun (dart:async/zone.dart:1126:13)
#14     _CustomZone.run (dart:async/zone.dart:1023:19)
#15     _runZoned (dart:async/zone.dart:1518:10)
#16     runZoned (dart:async/zone.dart:1465:12)
#17     AppContext.run (package:flutter_tools/src/base/context.dart:145:18)
#18     FlutterCommand.run (package:flutter_tools/src/runner/flutter_command.dart:505:20)
#19     CommandRunner.runCommand (package:args/command_runner.dart:197:27)
#20     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:413:21)
<asynchronous suspension>
#21     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:146:29)
#22     _rootRun (dart:async/zone.dart:1126:13)
#23     _CustomZone.run (dart:async/zone.dart:1023:19)
#24     _runZoned (dart:async/zone.dart:1518:10)
#25     runZoned (dart:async/zone.dart:1465:12)
#26     AppContext.run (package:flutter_tools/src/base/context.dart:145:18)
#27     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:364:19)
#28     CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:112:25)
#29     new Future.sync (dart:async/future.dart:224:31)
#30     CommandRunner.run (package:args/command_runner.dart:112:14)
#31     FlutterCommandRunner.run (package:flutter_tools/src/runner/flutter_command_runner.dart:250:18)
#32     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:63:22)
#33     _rootRun (dart:async/zone.dart:1126:13)
#34     _CustomZone.run (dart:async/zone.dart:1023:19)
#35     _runZoned (dart:async/zone.dart:1518:10)
#36     runZoned (dart:async/zone.dart:1502:12)
#37     run.<anonymous closure> (package:flutter_tools/runner.dart:61:18)
<asynchronous suspension>
#38     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:146:29)
#39     _rootRun (dart:async/zone.dart:1126:13)
#40     _CustomZone.run (dart:async/zone.dart:1023:19)
#41     _runZoned (dart:async/zone.dart:1518:10)
#42     runZoned (dart:async/zone.dart:1465:12)
#43     AppContext.run (package:flutter_tools/src/base/context.dart:145:18)
#44     runInContext (package:flutter_tools/src/context_runner.dart:64:24)
#45     run (package:flutter_tools/runner.dart:50:10)
#46     main (package:flutter_tools/executable.dart:65:9)
#47     main (file:///home/heitor/Desktop/dev/flutter/packages/flutter_tools/bin/flutter_tools.dart:8:3)
#48     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:305:32)
#49     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:174:12)
```
</details>

## flutter doctor

```console
[32m[✓][39m Flutter (Channel stable, v1.12.13+hotfix.5, on Linux, locale en_US.UTF-8)
    [32m•[39m Flutter version 1.12.13+hotfix.5 at /home/heitor/Desktop/dev/flutter
    [32m•[39m Framework revision 27321ebbad (6 days ago), 2019-12-10 18:15:01 -0800
    [32m•[39m Engine revision 2994f7e1e6
    [32m•[39m Dart version 2.7.0

[32m[✓][39m Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    [32m•[39m Android SDK at /home/heitor/Android/Sdk
    [32m•[39m Android NDK location not configured (optional; useful for native profiling
      support)
    [32m•[39m Platform android-29, build-tools 29.0.2
    [32m•[39m Java binary at: /home/heitor/Desktop/dev/android-studio/jre/bin/java
    [32m•[39m Java version OpenJDK Runtime Environment (build
      1.8.0_202-release-1483-b49-5587405)
    [32m•[39m All Android licenses accepted.

[32m[✓][39m Android Studio (version 3.5)
    [32m•[39m Android Studio at /home/heitor/Desktop/dev/android-studio
    [32m•[39m Flutter plugin version 41.1.2
    [32m•[39m Dart plugin version 191.8593
    [32m•[39m Java version OpenJDK Runtime Environment (build
      1.8.0_202-release-1483-b49-5587405)

[33m[!][39m Connected device
    [33m![39m No devices available

[33m![39m Doctor found issues in 1 category.
```

**Comment by Heitorpsoa** [comment]
I also got this message while flutter doctor was running:

/home/heitor/Desktop/dev/flutter/bin/cache/artifacts/engine/linux-x64/frontend_s
erver.dart.snapshot  bad CRC f491d90c  (should be d31aa53d)

Sending crash report to Google.
Crash report sent (report ID: 906bdbddb9345986)
Oops; flutter has exited unexpectedly.

**Comment by anupamutrade** [comment]
Same Problem,
I am able to produce ios release Builds, android debug build but failing to create android Release APK  with flutter SDK version 1.12.13+hotfix.5

Sending crash report to Google.
Crash report sent (report ID: c1d6207630fd5cfc)
Oops; flutter has exited unexpectedly.


Flutter crash report; please file at https://github.com/flutter/flutter/issues.

## command

flutter build apk --split-per-abi

## exception

ProcessException: ProcessException: Permission denied
  Command: /Users/macbookpro/Documents/Flutter/.pub-cache/hosted/pub.dartlang.org/clipboard_manager-0.0.4/android/gradlew -I=/Users/macbookpro/Documents/Flutter/packages/flutter_tools/gradle/aar_init_script.gradle -Pflutter-root=/Users/macbookpro/Documents/Flutter -Poutput-dir=/Users/macbookpro/Documents/Projects/AndroidStudioProjects/flutter_hashtrade/hashtrade_flutter/build/app -Pis-plugin=true -Ptarget-platform=android-arm,android-arm64,android-x64 assembleAarRelease

```
#0      _DefaultProcessUtils.run (package:flutter_tools/src/base/process.dart:266:37)
<asynchronous suspension>
#1      buildGradleAar (package:flutter_tools/src/android/gradle.dart:548:33)
#2      buildPluginsAsAar (package:flutter_tools/src/android/gradle.dart:711:13)
#3      buildGradleApp (package:flutter_tools/src/android/gradle.dart:257:11)
#4      _AsyncAwaitCompleter.start (dart:async-patch/async_patch.dart:45:6)
#5      buildGradleApp (package:flutter_tools/src/android/gradle.dart:218:28)
#6      buildGradleApp (package:flutter_tools/src/android/gradle.dart:415:19)
#7      _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:73:64)
#8      _rootRunUnary (dart:async/zone.dart:1134:38)
#9      _CustomZone.runUnary (dart:async/zone.dart:1031:19)
#10     _FutureListener.handleValue (dart:async/future_impl.dart:139:18)
#11     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:680:45)
#12     Future._propagateToListeners (dart:async/future_impl.dart:709:32)
#13     Future._completeWithValue (dart:async/future_impl.dart:524:5)
#14     Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:554:7)
#15     _rootRun (dart:async/zone.dart:1126:13)
#16     _CustomZone.run (dart:async/zone.dart:1023:19)
#17     _CustomZone.runGuarded (dart:async/zone.dart:925:7)
#18     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:965:23)
#19     _microtaskLoop (dart:async/schedule_microtask.dart:43:21)
#20     _startMicrotaskLoop (dart:async/schedule_microtask.dart:52:5)
#21     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
#22     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:175:5)
```

## flutter doctor

```
[32m[✓][39m Flutter (Channel stable, v1.12.13+hotfix.5, on Mac OS X 10.15.1 19B88, locale en-US)
    [32m•[39m Flutter version 1.12.13+hotfix.5 at /Users/macbookpro/Documents/Flutter
    [32m•[39m Framework revision 27321ebbad (6 days ago), 2019-12-10 18:15:01 -0800
    [32m•[39m Engine revision 2994f7e1e6
    [32m•[39m Dart version 2.7.0

[32m[✓][39m Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    [32m•[39m Android SDK at /Users/macbookpro/Library/Android/sdk
    [32m•[39m Android NDK location not configured (optional; useful for native profiling support)
    [32m•[39m Platform android-29, build-tools 29.0.2
    [32m•[39m Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    [32m•[39m Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    [32m•[39m All Android licenses accepted.

[32m[✓][39m Xcode - develop for iOS and macOS (Xcode 11.2.1)
    [32m•[39m Xcode at /Applications/Xcode.app/Contents/Developer
    [32m•[39m Xcode 11.2.1, Build version 11B500
    [32m•[39m CocoaPods version 1.8.3

[32m[✓][39m Android Studio (version 3.5)
    [32m•[39m Android Studio at /Applications/Android Studio.app/Contents
    [32m•[39m Flutter plugin version 42.1.1
    [32m•[39m Dart plugin version 191.8593
    [32m•[39m Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[32m[✓][39m VS Code (version 1.41.0)
    [32m•[39m VS Code at /Applications/Visual Studio Code.app/Contents
    [32m•[39m Flutter extension version 3.7.1

[32m[✓][39m Connected device (2 available)
    [32m•[39m Lenovo K33a42     • 95976a7b                                 • android-arm • Android 7.0 (API 24)
    [32m•[39m Kunal's iPhone 6s • c88840c58bc3f7f501fbc8ca9642c17c1a831027 • ios         • iOS 13.1

[32m•[39m No issues found!
```

**Comment by marcos930807** [comment]
"Dart analyzer has stopped " This is happening to me since I updated to the stable version 1.12.13hotfix5, i already reinstall visual code and the problem persits.
Flutter Doctor outputs:
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, v1.12.13+hotfix.5, on Microsoft Windows [VersiÃ³n 10.0.18362.535], locale es-CU)
[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[√] Android Studio (version 3.5)
[√] VS Code, 64-bit edition (version 1.41.0)
[√] Connected device (1 available)

• No issues found!

Daemon:
Starting device daemon...
[{"event":"daemon.connected","params":{"version":"0.5.3","pid":8376}}]

The error in the Log is the same:
[11:51:17 pm] [General] [Error] Cannot call write after a stream was destroyed
Error [ERR_STREAM_DESTROYED]: Cannot call write after a strdeam was destroye

**Comment by VladyslavBondarenko** [comment]
Hi @Heitorpsoa 
I see there's an open issue addressing the case you described.
Please follow up on https://github.com/flutter/flutter/issues/43620
I'm closing the current one as duplicate.
If you disagree please write in the comments
and I will reopen it.
Thank you
