### ISSUE TITLE
Device go to Offline after start the App in  VS code - Ubuntu

### ISSUE THREAD

**Issue by doob09** [flutter/flutter#47179]
**Steps to Reproduce**

I have installed VS code in Ubuntu 18.04.3 LTS to run flutter . When I try to run the counter app on my physical device:
- It starts and stops.
- No Device shows up (It shows up before I hit run).

<details>
  <summary>logs</summary>

```bash
pv@pv-desktop:/media/pv/My Book/Projects/Flutter/test2$ flutter run --verbose
[  +17 ms] executing: [/home/pv/Documents/flutter/] git -c log.showSignature=false log -n 1
--pretty=format:%H
[  +29 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[        ] 27321ebbad34b0a3fafe99fac037102196d655ff
[        ] executing: [/home/pv/Documents/flutter/] git describe --match v*.*.* --first-parent --long
--tags
[   +6 ms] Exit code 0 from: git describe --match v*.*.* --first-parent --long --tags
[        ] v1.12.13+hotfix.5-0-g27321ebba
[   +6 ms] executing: [/home/pv/Documents/flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[   +4 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/stable
[        ] executing: [/home/pv/Documents/flutter/] git ls-remote --get-url origin
[   +4 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[  +37 ms] executing: [/home/pv/Documents/flutter/] git rev-parse --abbrev-ref HEAD
[   +4 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] stable
[  +72 ms] executing: /home/pv/Android/Sdk/platform-tools/adb devices -l
[   +5 ms] Exit code 0 from: /home/pv/Android/Sdk/platform-tools/adb devices -l
[        ] List of devices attached
           LGK550f40848c          device usb:1-5.2 product:ph2n_tmo_us model:LG_K550 device:ph2n
           transport_id:1
[  +26 ms] /home/pv/Android/Sdk/platform-tools/adb -s LGK550f40848c shell getprop
[ +113 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[   +3 ms] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +1 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[ +101 ms] Generating /media/pv/My
Book/Projects/Flutter/test2/android/app/src/main/java/io/flutter/plugins/GeneratedPluginRegistrant.java
[  +21 ms] ro.hardware = ph2n
[        ] ro.build.characteristics = default
[  +42 ms] Launching lib/main.dart on LG K550 in debug mode...
[   +8 ms] executing: /home/pv/Android/Sdk/platform-tools/adb -s LGK550f40848c shell -x logcat -v time
-s flutter
[   +5 ms] executing: /home/pv/Android/Sdk/platform-tools/adb version
[  +18 ms] Android Debug Bridge version 1.0.41
           Version 29.0.5-5949299
           Installed as /home/pv/Android/Sdk/platform-tools/adb
[   +2 ms] executing: /home/pv/Android/Sdk/platform-tools/adb start-server
[  +14 ms] Building APK
[  +15 ms] Running Gradle task 'assembleDebug'...
[   +1 ms] gradle.properties already sets `android.enableR8`
[   +1 ms] Using gradle from /media/pv/My Book/Projects/Flutter/test2/android/gradlew.
[   +5 ms] executing: /snap/android-studio/81/android-studio/jre/bin/java -version
[ +654 ms] Exit code 0 from: /snap/android-studio/81/android-studio/jre/bin/java -version
[        ] openjdk version "1.8.0_202-release"
           OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
           OpenJDK 64-Bit Server VM (build 25.202-b49-5587405, mixed mode)
[   +3 ms] executing: [/media/pv/My Book/Projects/Flutter/test2/android/] /media/pv/My
Book/Projects/Flutter/test2/android/gradlew -Pverbose=true -Ptarget=/media/pv/My
Book/Projects/Flutter/test2/lib/main.dart -Ptrack-widget-creation=true
-Pfilesystem-scheme=org-dartlang-root -Ptarget-platform=android-arm assembleDebug
[ +584 ms] Welcome to Gradle 5.6.2!
[        ] Here are the highlights of this release:
[        ]  - Incremental Groovy compilation
[        ]  - Groovy compile avoidance
[        ]  - Test fixtures for Java projects
[        ]  - Manage plugin versions via settings script
[        ] For more details see https://docs.gradle.org/5.6.2/release-notes.html
[  +87 ms] Starting a Gradle Daemon (subsequent builds will be faster)
[+8701 ms] > Task :app:compileFlutterBuildDebug
[        ] [  +17 ms] executing: [/home/pv/Documents/flutter/] git -c log.showSignature=false log -n 1
--pretty=format:%H
[        ] [  +24 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[        ] [        ] 27321ebbad34b0a3fafe99fac037102196d655ff
[        ] [        ] executing: [/home/pv/Documents/flutter/] git describe --match v*.*.*
--first-parent --long --tags
[        ] [   +5 ms] Exit code 0 from: git describe --match v*.*.* --first-parent --long --tags
[        ] [        ] v1.12.13+hotfix.5-0-g27321ebba
[        ] [   +8 ms] executing: [/home/pv/Documents/flutter/] git rev-parse --abbrev-ref --symbolic
@{u}
[        ] [   +4 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] [        ] origin/stable
[        ] [        ] executing: [/home/pv/Documents/flutter/] git ls-remote --get-url origin
[        ] [   +3 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] [        ] https://github.com/flutter/flutter.git
[        ] [  +47 ms] executing: [/home/pv/Documents/flutter/] git rev-parse --abbrev-ref HEAD
[        ] [   +4 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] [        ] stable
[        ] [  +20 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping
update.
[        ] [        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping
update.
[        ] [        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[        ] [   +2 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping
update.
[        ] [        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping
update.
[        ] [  +83 ms] Initializing file store
[        ] [  +16 ms] kernel_snapshot: Starting due to {}
[        ] [   +9 ms] /home/pv/Documents/flutter/bin/cache/dart-sdk/bin/dart
/home/pv/Documents/flutter/bin/cache/artifacts/engine/linux-x64/frontend_server.dart.snapshot
--sdk-root /home/pv/Documents/flutter/bin/cache/artifacts/engine/common/flutter_patched_sdk/
--target=flutter -Ddart.developer.causal_async_stacks=true -Ddart.vm.profile=false
-Ddart.vm.product=false
--bytecode-options=source-positions,local-var-info,debugger-stops,instance-field-initializers,keep-unre
achable-code,avoid-closure-call-instructions --enable-asserts --track-widget-creation
--no-link-platform --packages /media/pv/My Book/Projects/Flutter/test2/.packages --output-dill
/media/pv/My
Book/Projects/Flutter/test2/.dart_tool/flutter_build/7bf3893d7fe3a4b0e73c98075091f427/app.dill
--depfile /media/pv/My
Book/Projects/Flutter/test2/.dart_tool/flutter_build/7bf3893d7fe3a4b0e73c98075091f427/kernel_snapshot.d
package:test2/main.dart
[+3090 ms] [+4561 ms] kernel_snapshot: Complete
[ +999 ms] [ +947 ms] debug_android_application: Starting due to {}
[ +200 ms] [ +246 ms] debug_android_application: Complete
[ +199 ms] [ +211 ms] Persisting file store
[ +100 ms] [   +6 ms] Done persisting file store
[        ] [   +3 ms] build succeeded.
[        ] [  +10 ms] "flutter assemble" took 6,123ms.
[  +99 ms] > Task :app:packLibsflutterBuildDebug
[        ] > Task :app:preBuild UP-TO-DATE
[        ] > Task :app:preDebugBuild UP-TO-DATE
[        ] > Task :app:compileDebugAidl NO-SOURCE
[  +99 ms] > Task :app:checkDebugManifest
[        ] > Task :app:compileDebugRenderscript NO-SOURCE
[        ] > Task :app:generateDebugBuildConfig
[        ] > Task :app:cleanMergeDebugAssets UP-TO-DATE
[  +99 ms] > Task :app:mergeDebugShaders
[        ] > Task :app:compileDebugShaders
[        ] > Task :app:generateDebugAssets
[  +99 ms] > Task :app:mergeDebugAssets
[ +299 ms] > Task :app:copyFlutterAssetsDebug
[        ] > Task :app:mainApkListPersistenceDebug
[  +99 ms] > Task :app:generateDebugResValues
[        ] > Task :app:generateDebugResources
[+2499 ms] > Task :app:createDebugCompatibleScreenManifests
[ +299 ms] > Task :app:processDebugManifest
[ +100 ms] > Task :app:mergeDebugResources
[ +499 ms] > Task :app:processDebugResources
[+4299 ms] > Task :app:compileDebugKotlin
[        ] > Task :app:processDebugJavaRes NO-SOURCE
[        ] > Task :app:javaPreCompileDebug
[+1399 ms] > Task :app:compileDebugJavaWithJavac
[        ] > Task :app:compileDebugSources
[  +99 ms] > Task :app:checkDebugDuplicateClasses
[+1099 ms] > Task :app:transformClassesWithDexBuilderForDebug
[ +100 ms] > Task :app:validateSigningDebug
[        ] > Task :app:signingConfigWriterDebug
[  +99 ms] > Task :app:mergeDebugJavaResource
[        ] > Task :app:desugarDebugFileDependencies
[        ] > Task :app:mergeDebugJniLibFolders
[ +999 ms] > Task :app:mergeExtDexDebug
[ +599 ms] > Task :app:mergeDexDebug
[+4200 ms] > Task :app:mergeDebugNativeLibs
[        ] Unable to strip library '/media/pv/My
Book/Projects/Flutter/test2/build/app/intermediates/merged_native_libs/debug/out/lib/x86_64/libflutter.
so' due to missing strip tool for ABI 'X86_64'. Packaging it as is.
[  +99 ms] Unable to strip library '/media/pv/My
Book/Projects/Flutter/test2/build/app/intermediates/merged_native_libs/debug/out/lib/armeabi-v7a/libflu
tter.so' due to missing strip tool for ABI 'ARMEABI_V7A'. Packaging it as is.
[        ] Unable to strip library '/media/pv/My
Book/Projects/Flutter/test2/build/app/intermediates/merged_native_libs/debug/out/lib/x86/libflutter.so'
due to missing strip tool for ABI 'X86'. Packaging it as is.
[ +299 ms] > Task :app:stripDebugDebugSymbols
[        ] Compatible side by side NDK version was not found.
[+3299 ms] > Task :app:packageDebug
[        ] > Task :app:assembleDebug
[  +64 ms] BUILD SUCCESSFUL in 34s
[        ] 30 actionable tasks: 29 executed, 1 up-to-date
[ +331 ms] Running Gradle task 'assembleDebug'... (completed in 35.8s)
[ +176 ms] calculateSha: LocalDirectory: '/media/pv/My
Book/Projects/Flutter/test2/build/app/outputs/apk'/app.apk
[  +40 ms] calculateSha: reading file took 39us
[ +424 ms] calculateSha: computing sha took 424us
[   +8 ms] ✓ Built build/app/outputs/apk/debug/app-debug.apk.
[   +3 ms] executing: /home/pv/Android/Sdk/build-tools/29.0.2/aapt dump xmltree /media/pv/My
Book/Projects/Flutter/test2/build/app/outputs/apk/app.apk AndroidManifest.xml
[  +19 ms] Exit code 0 from: /home/pv/Android/Sdk/build-tools/29.0.2/aapt dump xmltree /media/pv/My
Book/Projects/Flutter/test2/build/app/outputs/apk/app.apk AndroidManifest.xml
[        ] N: android=http://schemas.android.com/apk/res/android
             E: manifest (line=2)
               A: android:versionCode(0x0101021b)=(type 0x10)0x1
               A: android:versionName(0x0101021c)="1.0.0" (Raw: "1.0.0")
               A: android:compileSdkVersion(0x01010572)=(type 0x10)0x1c
               A: android:compileSdkVersionCodename(0x01010573)="9" (Raw: "9")
               A: package="com.example.test2" (Raw: "com.example.test2")
               A: platformBuildVersionCode=(type 0x10)0x1c
               A: platformBuildVersionName=(type 0x10)0x9
               E: uses-sdk (line=7)
                 A: android:minSdkVersion(0x0101020c)=(type 0x10)0x10
                 A: android:targetSdkVersion(0x01010270)=(type 0x10)0x1c
               E: uses-permission (line=14)
                 A: android:name(0x01010003)="android.permission.INTERNET" (Raw:
                 "android.permission.INTERNET")
               E: application (line=22)
                 A: android:label(0x01010001)="test2" (Raw: "test2")
                 A: android:icon(0x01010002)=@0x7f080000
                 A: android:name(0x01010003)="io.flutter.app.FlutterApplication" (Raw:
                 "io.flutter.app.FlutterApplication")
                 A: android:debuggable(0x0101000f)=(type 0x12)0xffffffff
                 A: android:appComponentFactory(0x0101057a)="androidx.core.app.CoreComponentFactory"
                 (Raw: "androidx.core.app.CoreComponentFactory")
                 E: activity (line=28)
                   A: android:theme(0x01010000)=@0x7f0a0000
                   A: android:name(0x01010003)="com.example.test2.MainActivity" (Raw:
                   "com.example.test2.MainActivity")
                   A: android:launchMode(0x0101001d)=(type 0x10)0x1
                   A: android:configChanges(0x0101001f)=(type 0x11)0x40003fb4
                   A: android:windowSoftInputMode(0x0101022b)=(type 0x11)0x10
                   A: android:hardwareAccelerated(0x010102d3)=(type 0x12)0xffffffff
                   E: intent-filter (line=35)
                     E: action (line=36)
                       A: android:name(0x01010003)="android.intent.action.MAIN" (Raw:
                       "android.intent.action.MAIN")
                     E: category (line=38)
                       A: android:name(0x01010003)="android.intent.category.LAUNCHER" (Raw:
                       "android.intent.category.LAUNCHER")
                 E: meta-data (line=45)
                   A: android:name(0x01010003)="flutterEmbedding" (Raw: "flutterEmbedding")
                   A: android:value(0x01010024)=(type 0x10)0x2
[   +6 ms] Stopping app 'app.apk' on LG K550.
[        ] executing: /home/pv/Android/Sdk/platform-tools/adb -s LGK550f40848c shell am force-stop
com.example.test2
[+2585 ms] executing: /home/pv/Android/Sdk/platform-tools/adb -s LGK550f40848c shell pm list packages
com.example.test2
[+1274 ms] Installing APK.
[   +1 ms] executing: /home/pv/Android/Sdk/platform-tools/adb version
[   +7 ms] Android Debug Bridge version 1.0.41
           Version 29.0.5-5949299
           Installed as /home/pv/Android/Sdk/platform-tools/adb
[        ] executing: /home/pv/Android/Sdk/platform-tools/adb start-server
[   +8 ms] Installing build/app/outputs/apk/app.apk...
[        ] executing: /home/pv/Android/Sdk/platform-tools/adb -s LGK550f40848c install -t -r
/media/pv/My Book/Projects/Flutter/test2/build/app/outputs/apk/app.apk
[+6705 ms] Performing Streamed Install

                    adb: failed to install /media/pv/My
                    Book/Projects/Flutter/test2/build/app/outputs/apk/app.apk:
[        ] Installing build/app/outputs/apk/app.apk... (completed in 6.7s)
[   +1 ms] Error: ADB exited with exit code 1
[        ] Performing Streamed Install
           
           adb: failed to install /media/pv/My
Book/Projects/Flutter/test2/build/app/outputs/apk/app.apk:
[        ] Warning: Failed to install APK.
[        ] Error launching application on LG K550.
[   +3 ms] "flutter run" took 47,571ms.
```

```bash
#0      throwToolExit (package:flutter_tools/src/base/common.dart:28:3)
#1      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:509:7)
<asynchronous suspension>
#2      FlutterCommand.verifyThenRunCommand
(package:flutter_tools/src/runner/flutter_command.dart:615:18)
#3      _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:73:64)
#4      _rootRunUnary (dart:async/zone.dart:1134:38)
#5      _CustomZone.runUnary (dart:async/zone.dart:1031:19)
#6      _FutureListener.handleValue (dart:async/future_impl.dart:139:18)
#7      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:680:45)
#8      Future._propagateToListeners (dart:async/future_impl.dart:709:32)
#9      Future._completeWithValue (dart:async/future_impl.dart:524:5)
#10     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:32:15)
#11     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:290:13)
#12     RunCommand.usageValues (package:flutter_tools/src/commands/run.dart)
#13     _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:73:64)
#14     _rootRunUnary (dart:async/zone.dart:1134:38)
#15     _CustomZone.runUnary (dart:async/zone.dart:1031:19)
#16     _FutureListener.handleValue (dart:async/future_impl.dart:139:18)
#17     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:680:45)
#18     Future._propagateToListeners (dart:async/future_impl.dart:709:32)
#19     Future._completeWithValue (dart:async/future_impl.dart:524:5)
#20     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:32:15)
#21     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:290:13)
#22     IosProject.isSwift (package:flutter_tools/src/project.dart)
#23     _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:73:64)
#24     _rootRunUnary (dart:async/zone.dart:1134:38)
#25     _CustomZone.runUnary (dart:async/zone.dart:1031:19)
#26     _FutureListener.handleValue (dart:async/future_impl.dart:139:18)
#27     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:680:45)
#28     Future._propagateToListeners (dart:async/future_impl.dart:709:32)
#29     Future._completeWithValue (dart:async/future_impl.dart:524:5)
#30     Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:554:7)
#31     _rootRun (dart:async/zone.dart:1126:13)
#32     _CustomZone.run (dart:async/zone.dart:1023:19)
#33     _CustomZone.runGuarded (dart:async/zone.dart:925:7)
#34     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:965:23)
#35     _microtaskLoop (dart:async/schedule_microtask.dart:43:21)
#36     _startMicrotaskLoop (dart:async/schedule_microtask.dart:52:5)
#37     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
#38     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:175:5)
```

</details>

pv@pv-desktop:~/test1$ flutter doctor -v
```console
[✓] Flutter (Channel stable, v1.12.13+hotfix.5, on Linux, locale en_US.UTF-8)
    • Flutter version 1.12.13+hotfix.5 at /home/pv/Documents/flutter
    • Framework revision 27321ebbad (6 days ago), 2019-12-10 18:15:01 -0800
    • Engine revision 2994f7e1e6
    • Dart version 2.7.0

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /home/pv/Android/Sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • ANDROID_HOME = /home/pv/Android/Sdk
    • Java binary at: /snap/android-studio/81/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[!] Android Studio (version 3.5)
    • Android Studio at /snap/android-studio/81/android-studio
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[!] Connected device
    • Device LGK550f40848c is offline.

! Doctor found issues in 2 categories.
```

**Comment by iapicca** [comment]
Hi @doob09 
I'm not sure that the issue you are describing depends from flutter,
are you experiencing the same problem with a virtual device?
thank you

**Comment by doob09** [comment]
I see. I think it could caused by android sdk not by flutter. I have not tried any virtual device yet. thanks for help!

**Comment by doob09** [comment]
I see. I think it could caused by android sdk not by flutter. I have not tried any virtual device yet. Let me ask on stackoverflow. thanks for help!

**Comment by doob09** [comment]
Never Mind !! I have made a change in  app/build.grade: 
-compileSdkVersion 28 to 29
- targetSdkVersion 28 to 29

And it works now. The compatible sdk version cause this issue.

**Comment by iapicca** [comment]
Hi @doob09 
I'm glad you fixed the issue,
thank you for letting me know
