### ISSUE TITLE
[web] [CanvasKit] NullError was thrown during paint() when using Image.network

### ISSUE THREAD

**Issue by cbenhagen** [flutter/flutter#47215]
/cc @hterkelsen

```dart
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        appBar: AppBar(
          title: Text('Image.network test'),
        ),
        body: Center(
          child: Image.network('http://localhost:8000/test.png'),
        ),
      ),
    );
  }
}
```

```
══╡ EXCEPTION CAUGHT BY RENDERING LIBRARY ╞═════════════════════════════════════════════════════════
js_primitives.dart:49 The following NullError was thrown during paint():
js_primitives.dart:49 NoSuchMethodError: method not found: 'Sk' on null
js_primitives.dart:49 
js_primitives.dart:49 When the exception was thrown, this was the stack:
js_primitives.dart:49 TypeError: Cannot read property 'Sk' of undefined
js_primitives.dart:49     at zd.sd [as toWireType] (https://unpkg.com/canvaskit-wasm@0.10.0/bin/canvaskit.js:163:152)
js_primitives.dart:49     at SkCanvas$drawImageRect [as drawImageRect] (eval at Gd (https://unpkg.com/canvaskit-wasm@0.10.0/bin/canvaskit.js:170:242), <anonymous>:9:26)
js_primitives.dart:49     at JsObject.callMethod$2 (http://localhost:8000/main.dart.js:34906:42)
js_primitives.dart:49     at CanvasKitCanvas.drawImageRect$4 (http://localhost:8000/main.dart.js:20254:38)
js_primitives.dart:49     at Object.paintImage (http://localhost:8000/main.dart.js:10237:16)
js_primitives.dart:49     at RenderImage.paint$2 (http://localhost:8000/main.dart.js:50055:9)
js_primitives.dart:49     at RenderImage._paintWithContext$2 (http://localhost:8000/main.dart.js:51158:15)
js_primitives.dart:49     at PaintingContext.paintChild$2 (http://localhost:8000/main.dart.js:50620:15)
js_primitives.dart:49     at RenderSemanticsAnnotations.paint$2 (http://localhost:8000/main.dart.js:52594:17)
js_primitives.dart:49     at RenderSemanticsAnnotations._paintWithContext$2 (http://localhost:8000/main.dart.js:51158:15)
js_primitives.dart:49 
js_primitives.dart:49 The following RenderObject was being processed when the exception was fired: RenderImage#1be1a relayoutBoundary=up3:
js_primitives.dart:49   parentData: <none>
js_primitives.dart:49   constraints: BoxConstraints(0.0<=w<=256.0, 0.0<=h<=1282.0)
js_primitives.dart:49   size: Size(256.0, 256.0)
js_primitives.dart:49   image: Instance of 'HtmlImage'
js_primitives.dart:49   alignment: center
js_primitives.dart:49   invertColors: false
js_primitives.dart:49   filterQuality: low
js_primitives.dart:49 This RenderObject has no descendants.
js_primitives.dart:49 ════════════════════════════════════════════════════════════════════════════════════════════════════
```

```
[✓] Flutter (Channel master, v1.13.3-pre.42, on Mac OS X 10.15.1 19B88, locale en-CH)
    • Flutter version 1.13.3-pre.42 at /Users/ben/flutter
    • Framework revision a82a399733 (6 hours ago), 2019-12-16 23:28:02 -0800
    • Engine revision e0e0ac0a68
    • Dart version 2.8.0 (build 2.8.0-dev.0.0 45db297095)


[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/ben/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.2.1, Build version 11B53
    • CocoaPods version 1.8.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 42.1.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] VS Code (version 1.40.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.7.0

[✓] Connected device (3 available)
    • macOS      • macOS      • darwin-x64     • Mac OS X 10.15.1 19B88
    • Chrome     • chrome     • web-javascript • Google Chrome 79.0.3945.79
    • Web Server • web-server • web-javascript • Flutter Tools

• No issues found!
```

**Comment by cbenhagen** [comment]
The error is gone but still no image is displayed. I am closing this in favor of https://github.com/flutter/flutter/issues/49725.
