### ISSUE TITLE
[path_provider] [url_launcher] in Channel beta, v1.12.13+hotfix.6 "FlutterPluginBinding has been deprecated"

### ISSUE THREAD

**Issue by abaker2010** [flutter/flutter#47226]
Hey everyone, I was wondering if I could get some help with this issue. 

Plugin Used: path_provider
Version: 1.5.1

Plugin Used: url_launcher
Version: 5.4.1

Android Version Used: 29

The error that is being thrown when I try to compile for Android is this.

## Path_Provider
```bash
> /.pub-cache/hosted/pub.dartlang.org/path_provider-1.5.1/android/src/main/java/io/flutter/plugins/pathprovider/PathProviderPlugin.java:40: warning: [deprecation] getFlutterEngine() in FlutterPluginBinding has been deprecated
            binding.getFlutterEngine().getDartExecutor(), "plugins.flutter.io/path_provider");
```

## Url_Launcher

```bash
> /Users/zedo/.pub-cache/hosted/pub.dartlang.org/url_launcher-5.4.1/android/src/main/java/io/flutter/plugins/urllauncher/WebViewActivity.java:42: warning: [deprecation] shouldOverrideUrlLoading(WebView,String) in WebViewClient has been deprecated
        public boolean shouldOverrideUrlLoading(WebView view, String url) {
                       ^
/Users/zedo/.pub-cache/hosted/pub.dartlang.org/url_launcher-5.4.1/android/src/main/java/io/flutter/plugins/urllauncher/WebViewActivity.java:47: warning: [deprecation] shouldOverrideUrlLoading(WebView,String) in WebViewClient has been deprecated
          return super.shouldOverrideUrlLoading(view, url);
                      ^
/Users/zedo/.pub-cache/hosted/pub.dartlang.org/url_launcher-5.4.1/android/src/main/java/io/flutter/plugins/urllauncher/UrlLauncherPlugin.java:38: warning: [deprecation] getFlutterEngine() in FlutterPluginBinding has been deprecated
    methodCallHandler.startListening(binding.getFlutterEngine().getDartExecutor());
```

## Logs

`flutter run --verbose`

```bash
> flutter run --verbose
[  +22 ms] executing: [/Users/zedo/DevelopmentTools/flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[  +29 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[        ] 18cd7a3601bcffb36fdf2f679f763b5e827c2e8e
[        ] executing: [/Users/zedo/DevelopmentTools/flutter/] git describe --match v*.*.* --first-parent --long --tags
[  +22 ms] Exit code 0 from: git describe --match v*.*.* --first-parent --long --tags
[        ] v1.12.13+hotfix.6-0-g18cd7a360
[   +6 ms] executing: [/Users/zedo/DevelopmentTools/flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[   +4 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/beta
[        ] executing: [/Users/zedo/DevelopmentTools/flutter/] git ls-remote --get-url origin
[   +4 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[  +44 ms] executing: [/Users/zedo/DevelopmentTools/flutter/] git rev-parse --abbrev-ref HEAD
[   +5 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] beta
[   +5 ms] executing: sw_vers -productName
[  +14 ms] Exit code 0 from: sw_vers -productName
[        ] Mac OS X
[        ] executing: sw_vers -productVersion
[  +12 ms] Exit code 0 from: sw_vers -productVersion
[        ] 10.15.1
[        ] executing: sw_vers -buildVersion
[  +12 ms] Exit code 0 from: sw_vers -buildVersion
[        ] 19B88
[  +23 ms] executing: /usr/bin/xcode-select --print-path
[   +7 ms] Exit code 0 from: /usr/bin/xcode-select --print-path
[        ] /Applications/Xcode.app/Contents/Developer
[   +1 ms] executing: /usr/bin/xcodebuild -version
[ +426 ms] Exit code 0 from: /usr/bin/xcodebuild -version
[   +2 ms] Xcode 11.3
           Build version 11C29
[  +56 ms] executing: /Users/zedo/Library/Android/sdk/platform-tools/adb devices -l
[   +5 ms] Exit code 0 from: /Users/zedo/Library/Android/sdk/platform-tools/adb devices -l
[        ] List of devices attached
           emulator-5554          device product:sdk_gphone_x86 model:Android_SDK_built_for_x86 device:generic_x86 transport_id:8
[  +16 ms] executing: /Users/zedo/DevelopmentTools/flutter/bin/cache/artifacts/libimobiledevice/idevice_id -h
[  +44 ms] /usr/bin/xcrun simctl list --json devices
[  +90 ms] More than one device connected; please specify a device with the '-d <deviceId>' flag, or use '-d all' to act on all devices.
[   +2 ms] /Users/zedo/Library/Android/sdk/platform-tools/adb -s emulator-5554 shell getprop
[  +26 ms] ro.hardware = ranchu
[   +5 ms] Android SDK built for x86 • emulator-5554                        • android-x86 • Android 10 (API 29) (emulator)
[        ] iPhone 11 Pro Max         • 11AE2AB1-C2C4-42A7-B3DC-C8C79F758633 • ios         • com.apple.CoreSimulator.SimRuntime.iOS-13-3 (simulator)
[  +10 ms] "flutter run" took 771ms.
#0      throwToolExit (package:flutter_tools/src/base/common.dart:28:3)
#1      RunCommand.validateCommand (package:flutter_tools/src/commands/run.dart:289:7)
<asynchronous suspension>#2      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:590:11)
#3      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:515:33)
<asynchronous suspension>#4      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:146:29)
#5      _rootRun (dart:async/zone.dart:1126:13)
#6      _CustomZone.run (dart:async/zone.dart:1023:19)
#7      _runZoned (dart:async/zone.dart:1518:10)
#8      runZoned (dart:async/zone.dart:1465:12)
#9      AppContext.run (package:flutter_tools/src/base/context.dart:145:18)
#10     FlutterCommand.run (package:flutter_tools/src/runner/flutter_command.dart:505:20)
#11     CommandRunner.runCommand (package:args/command_runner.dart:197:27)
#12     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:413:21)
<asynchronous suspension>#13     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:146:29)
#14     _rootRun (dart:async/zone.dart:1126:13)
#15     _CustomZone.run (dart:async/zone.dart:1023:19)
#16     _runZoned (dart:async/zone.dart:1518:10)
#17     runZoned (dart:async/zone.dart:1465:12)
#18     AppContext.run (package:flutter_tools/src/base/context.dart:145:18)
#19     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:364:19)
#20     CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:112:25)
#21     new Future.sync (dart:async/future.dart:224:31)
#22     CommandRunner.run (package:args/command_runner.dart:112:14)
#23     FlutterCommandRunner.run (package:flutter_tools/src/runner/flutter_command_runner.dart:250:18)
#24     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:63:22)
#25     _rootRun (dart:async/zone.dart:1126:13)
#26     _CustomZone.run (dart:async/zone.dart:1023:19)
#27     _runZoned (dart:async/zone.dart:1518:10)
#28     runZoned (dart:async/zone.dart:1502:12)
#29     run.<anonymous closure> (package:flutter_tools/runner.dart:61:18)
<asynchronous suspension>#30     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:146:29)
#31     _rootRun (dart:async/zone.dart:1126:13)
#32     _CustomZone.run (dart:async/zone.dart:1023:19)
#33     _runZoned (dart:async/zone.dart:1518:10)
#34     runZoned (dart:async/zone.dart:1465:12)
#35     AppContext.run (package:flutter_tools/src/base/context.dart:145:18)
#36     runInContext (package:flutter_tools/src/context_runner.dart:64:24)
#37     run (package:flutter_tools/runner.dart:50:10)
#38     main (package:flutter_tools/executable.dart:65:9)
#39     main (file:///Users/zedo/DevelopmentTools/flutter/packages/flutter_tools/bin/flutter_tools.dart:8:3)
#40     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:305:32)
#41     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:174:12)
```

`flutter doctor`

> Doctor summary (to see all details, run flutter doctor -v):
```console
[✓] Flutter (Channel beta, v1.12.13+hotfix.6, on Mac OS X 10.15.1 19B88, locale en-US)
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 11.3)
[✓] Android Studio (version 3.5)
[✓] Connected device (2 available)
• No issues found!

```

**Comment by iapicca** [comment]
Hi @abaker2010 
if you recently upgraded you flutter version
and your app was initially built with the previous stable
you may try to run 
`flutter clean`
`flutter pub cache repair`
let me know if this removes the warnings
thank you

**Comment by abaker2010** [comment]
Hey @iapicca, thank you for the response. I tried this fix and after repairing the cache I still received the same errors as before. Do I need to manually remove the cache folder? 

Thank you

**Comment by iapicca** [comment]
Hi @abaker2010 
as stated [here](https://github.com/flutter/flutter/issues/44070#issuecomment-549947493) this is a temporary situation, but in was worth a try;
here are the specific issues for [url_launcher](https://github.com/flutter/flutter/issues/44070) and [shared_preferences](https://github.com/flutter/flutter/issues/44569)
I'm closing the current one as duplicate.
If you disagree please write in the comments
and I will reopen it.
Thank you

**Comment by abaker2010** [comment]
Hey @iapicca, oh okay awesome. Thank you for your help and the clarification about the issue!
