### ISSUE TITLE
Exception sometimes when moving the camera in Google Map widget

### ISSUE THREAD

**Issue by ahmaducg** [flutter/flutter#47241]
When I try to move the camera with 

```
await controller.moveCamera(
      CameraUpdate.newLatLngBounds(
        LatLngBounds(
          southwest: LatLng(minLat, minLng),
          northeast: LatLng(maxLat, maxLng),
        ),
        10,
      ),
    );
```
Sometimes this exception is thrown, and the camera doesn't move.

```
E/flutter (16192): [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: PlatformException(error, Error using newLatLngBounds(LatLngBounds, int): Map size can't be 0. Most likely, layout has not yet occured for the map view.  Either wait until layout has occurred or use newLatLngBounds(LatLngBounds, int, int, int) which allows you to specify the map's dimensions., null)
E/flutter (16192): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:569:7)
E/flutter (16192): #1      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:321:33)
E/flutter (16192): <asynchronous suspension>
E/flutter (16192): #2      GoogleMapController.moveCamera (package:google_maps_flutter/src/controller.dart:182:19)
E/flutter (16192): #3      TransitRouteProvider.setMapController (package:alyamin/provider/TransitRouteProvider.dart:106:22)
E/flutter (16192): #4      TransitRoutePage.initMap (package:alyamin/page/TransitRoutePage.dart:138:16)
E/flutter (16192): #5      TransitRoutePage.buildLayout.<anonymous closure> (package:alyamin/page/TransitRoutePage.dart:76:17)
E/flutter (16192): #6      _GoogleMapState.onPlatformViewCreated (package:google_maps_flutter/src/google_map.dart:317:14)
E/flutter (16192): <asynchronous suspension>
E/flutter (16192): #7      AndroidViewController._create (package:flutter/src/services/platform_views.dart:643:15)
E/flutter (16192): <asynchronous suspension>
E/flutter (16192): #8      AndroidViewController.setSize (package:flutter/src/services/platform_views.dart:557:14)
E/flutter (16192): #9      RenderAndroidView._sizePlatformView (package:flutter/src/rendering/platform_view.dart:174:29)
E/flutter (16192): #10     RenderAndroidView.performResize (package:flutter/src/rendering/platform_view.dart:155:5)
E/flutter (16192): #11     RenderObject.layout (package:flutter/src/rendering/object.dart:1703:9)
E/flutter (16192): #12     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
E/flutter (16192): #13     RenderObject.layout (package:flutter/src/rendering/object.dart:1724:7)
E/flutter (16192): #14     RenderPadding.performLayout (package:flutter/src/rendering/shifted_box.dart:206:11)
E/flutter (16192): #15     RenderObject.layout (package:flutter/src/rendering/object.dart:1724:7)
E/flutter (16192): #16     RenderStack.performLayout (package:flutter/src/rendering/stack.dart:505:15)
E/flutter (16192): #17     RenderObject.layout (package:flutter/src/rendering/object.dart:1724:7)
E/flutter (16192): #18     MultiChildLayoutDelegate.layoutChild (package:flutter/src/rendering/custom_layout.dart:163:11)
E/flutter (16192): #19     _ScaffoldLayout.performLayout (package:flutter/src/material/scaffold.dart:477:7)
E/flutter (16192): #20     MultiChildLayoutDelegate._callPerformLayout (package:flutter/src/rendering/custom_layout.dart:232:7)
E/flutter (16192): #21     RenderCustomMultiChildLayoutBox.performLayout (package:flutter/src/rendering/custom_layout.dart:391:14)
E/flutter (16192): #22     RenderObject._layoutWithoutResize (package:flutter/src/rendering/object.dart:1584:7)
E/flutter (16192): #23     PipelineOwner.flushLayout (package:flutter/src/rendering/object.dart:844:18)
E/flutter (16192): #24     RendererBinding.drawFrame (package:flutter/src/rendering/binding.dart:344:19)
E/flutter (16192): #25     WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:774:13)
E/flutter (16192): #26     RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:283:5)
E/flutter (16192): #27     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1102:15)
E/flutter (16192): #28     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1041:9)
E/flutter (16192): #29     SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:957:5)
E/flutter (16192): #30     _rootRun (dart:async/zone.dart:1126:13)
E/flutter (16192): #31     _CustomZone.run (dart:async/zone.dart:1023:19)
E/flutter (16192): #32     _CustomZone.runGuarded (dart:async/zone.dart:925:7)
E/flutter (16192): #33     _invoke (dart:ui/hooks.dart:259:10)
E/flutter (16192): #34     _drawFrame (dart:ui/hooks.dart:217:3)
E/flutter (16192): 

```

In Android that happened to me when trying to move the camera before changing the visibility of the map. But I'm only moving the camera after the onMapCreated is called, and I believe that's only called if the map is visible and loaded.

It does work when I make the function sleep for some little time, but that's not a real solution.

**Comment by ahmaducg** [comment]
Flutter Doctor
```
[√] Flutter (Channel stable, v1.12.13+hotfix.5, on Microsoft Windows [Version 10.0.18362.535], locale en-US)
    • Flutter version 1.12.13+hotfix.5 at C:\Programming\Flutter\Flutter_SDK
    • Framework revision 27321ebbad (7 days ago), 2019-12-10 18:15:01 -0800
    • Engine revision 2994f7e1e6
    • Dart version 2.7.0


[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at C:\Programming\Android_SDK
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • ANDROID_HOME = C:\Programming\Android_SDK
    • Java binary at: C:\Programming\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)
    • All Android licenses accepted.

[√] Android Studio (version 3.5)
    • Android Studio at C:\Programming\Android Studio
    • Flutter plugin version 42.1.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)

[√] IntelliJ IDEA Community Edition (version 2019.3)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2019.3
    • Flutter plugin version 42.1.4
    • Dart plugin version 193.5731

[!] VS Code, 64-bit edition (version 1.39.2)
    • VS Code at C:\Program Files\Microsoft VS Code
    X Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[√] Connected device (1 available)
    • SM G973F • 192.168.1.100:5555 • android-arm64 • Android 10 (API 29)

! Doctor found issues in 1 category.
```

**Comment by iapicca** [comment]
Hi @ahmaducg 
given the error from your logs

```bash
E/flutter (16192): [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception:
PlatformException(error, Error using newLatLngBounds(LatLngBounds, int): 
Map size can't be 0. Most likely, layout has not yet occured for the map view.  
Either wait until layout has occurred or use newLatLngBounds(LatLngBounds, int, int, int) 
which allows you to specify the map's dimensions., null)
```
the issue might depend from your apps code rather than flutter or google maps plugin itself
can you provide a code sample or the steps to reproduce the issue_
thank you

**Comment by ahmaducg** [comment]
The error only happens when I change the map's visibility. If the map is already visible, moving it doesn't trigger the error.

Note that I'm moving the camera right after "onMapCreated" is called, since by then the map should be fully loaded and visible. Making the message of the exception unlogical.

**Comment by iapicca** [comment]
Hi @ahmaducg 
it might depends from the logic ("when" and "where")
the async function you sampled is called;

as is my previous answer,
could you please provide a reproducible minimal code sample?
thank you

**Comment by iapicca** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact descriptions what happens, logs and the output of 'flutter doctor -v'  please.
All system setups can be slightly different so it's always better to open new issues and reference related issues.

**Comment by eyewritecode** [comment]
If you end up here with this same error, here's how i fixed it. Note that the issue comes from trying to draw markers, polylines, etc... on the map before it has "fully loaded"

```dart
GoogleMap(
  onMapCreated: (mapCon) {
    WidgetsBinding.instance.addPostFrameCallback((_) {
         // your code that moves the camera
     });
  }
)
```

**Comment by amatkivskiy** [comment]
@iapicca 
I've reproduced this issue on Android. 

I have a `StatelessWidget` that contains `GoogleMap`. It is rendered every time user clicks on bottom tab. 
Code: 
```
 @override
  Widget build(BuildContext context) {
    final bounds = _calculateBounds(markers);

    return GoogleMap(
      markers: markers,
      myLocationEnabled: true,
      mapToolbarEnabled: false,
      onMapCreated: (GoogleMapController controller) async {
        _controller.complete(controller);

        await controller.animateCamera(CameraUpdate.newLatLngBounds(bounds, 50));
      },
      initialCameraPosition: CameraPosition(
        target: _center,
        zoom: 11.0,
      ),
    );
  }
```

`flutter doctor -v`
```
[✓] Flutter (Channel stable, v1.17.5, on Mac OS X 10.15.5 19F101, locale en-GB)
    • Flutter version 1.17.5 at /Users/andrii/flutter
    • Framework revision 8af6b2f038 (6 weeks ago), 2020-06-30 12:53:55 -0700
    • Engine revision ee76268252
    • Dart version 2.8.4

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/andrii/Library/Android/sdk
    • Platform android-29, build-tools 29.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.6)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.6, Build version 11E708
    • CocoaPods version 1.9.3

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 47.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.47.3)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.13.2

[✓] Connected device (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 10 (API 29) (emulator)

• No issues found!
```
