### ISSUE TITLE
[url_launcher] Result doesn't fire on early dismissal (iOS)

### ISSUE THREAD

**Issue by jklint-g** [flutter/flutter#47271]
If you launch a URL on iOS and hit the Done button before the initial load completes, the FlutterResult never fires back to the caller.

I think the SafariVC delegate method which fires the FlutterResult does not get called in this case.

**Comment by iapicca** [comment]
Hi @jklint-g 
can you please provide your updated  `flutter doctor -v`
and a minimal code sample to reproduce the problem?
Thank you

**Comment by jklint-g** [comment]
Here's a test sequence. If you have trouble reproing, try substituting a different URL that takes longer to load or maybe use a slower network:
```
print('awaiting URL launch');
await UrlLauncher().launch('https://www.google.com');

// On iOS, if you hit the Done button in the native browser UI before the
// page finishes loading, then this line will never execute since the
// launcher future never completes.
print('URL future complete');
```

[✓] Flutter (Channel google3, vnull, on Mac OS X 10.14.6 18G1012, locale en-US)
    • Flutter version null at //third_party/dart/flutter
    • Framework revision a3bbdfb23a (6 days ago), 2020-01-03T00:00:00.000
    • Engine revision eb139936eb
    • Dart version 2f57602411

**Comment by VladyslavBondarenko** [comment]
Related to https://github.com/flutter/flutter/issues/45900

**Comment by iapicca** [comment]
<details>
  <summary>code</summary>

```dart 
import 'dart:async';
import 'package:flutter/material.dart';
import 'package:url_launcher/url_launcher.dart';

class ZonedUrl {
  final String url;
  const ZonedUrl({this.url});
  Future<bool> get lauch => runZoned(
    () async => await canLaunch(url)
      ? _launch.then((b) {
        print('done');
        return b;
      })
      : throw FlutterError("couldn't launch $url"),
    onError: (Object object, StackTrace stack) =>
      print('runZoned cought... \n object: $object \n stack: $stack',),
  );

  Future<bool> get _launch async => runZoned(
  () async {
      bool _b = await launch(url);
      if(_b != true && _b != false) throw('launch returned $_b');
      return _b;
    },
    onError: (Object object, StackTrace stack) =>
      print('runZoned cought... \n object: $object \n stack: $stack',),
  );
}

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  Widget build(BuildContext context) => MaterialApp(
    home: MyHomePage(),
  );
}

class MyHomePage extends StatefulWidget {
  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  static const String _url = 'https://flutter.dev';
 
  @override
  Widget build(BuildContext context) => Scaffold(
     floatingActionButton: FloatingActionButton(
       onPressed: () => ZonedUrl(url: _url).lauch,
       child: Icon(Icons.open_in_browser)),
  );
}
```

</details>

<details>
  <summary>logs</summary>


```bash
[   +4 ms] 🔥  To hot reload changes while running, press "r". To hot restart (and rebuild state), press "R".
[   +1 ms] An Observatory debugger and profiler on iPhone 8 is available at: http://127.0.0.1:63911/bH0wD1h44Sg=/
[        ] For a more detailed help message, press "h". To detach, press "d"; to quit, press "q".
[+17170 ms] [DEVICE LOG] 2020-03-13 15:08:34.866184+0200  localhost Runner[33997]: (FrontBoardServices) [com.apple.FrontBoard:Common] Creating service facility connection with <BSServiceConnectionEndpoint: 0x6000031d3300; target:
com.apple.frontboard.systemappservices; service: com.apple.frontboard.system-service>
[  +40 ms] [DEVICE LOG] 2020-03-13 15:08:34.867482+0200  localhost Runner[33997]: (FrontBoardServices) [com.apple.FrontBoard:Common] [FBSSystemService][0x3854] Sending request to open "com.apple.SafariViewService"
[  +10 ms] [DEVICE LOG] 2020-03-13 15:08:34.867876+0200  localhost Runner[33997]: (FrontBoardServices) [com.apple.FrontBoard:Common] [FBSSystemAppProxy:0x600000fe6ca0] Service facility connection invalidated
[  +47 ms] [DEVICE LOG] 2020-03-13 15:08:34.875563+0200  localhost Runner[33997]: (FrontBoardServices) [com.apple.FrontBoard:Common] [FBSSystemService][0x3854] Request successful: <BSProcessHandle: 0x6000031dad40; SafariViewServi:32587;
valid: YES>
[  +50 ms] [DEVICE LOG] 2020-03-13 15:08:34.977264+0200  localhost Runner[33997]: (ManagedConfiguration) [com.apple.ManagedConfiguration:MC] Got system group container path from MCM for systemgroup.com.apple.configurationprofiles:
/Users/nevercode/Library/Developer/CoreSimulator/Devices/D5F70F31-B488-4454-9539-320B5551D92A/data/Containers/Shared/SystemGroup/systemgroup.com.apple.configurationprofiles
[+5306 ms] [DEVICE LOG] 2020-03-13 15:08:40.320780+0200  localhost Runner[33997]: (Flutter) flutter: runZoned cought...
[        ] [DEVICE LOG]  object: launch returned null
[  +19 ms] [DEVICE LOG]  stack: #0      ZonedUrl._launch.<anonymous closure> (package:thirteen_march/main.dart:22:37)
[   +1 ms] [DEVICE LOG] <asynchronous suspension>
[        ] [DEVICE LOG] #1      _rootRun (dart:async/zone.dart:1126:13)
[        ] [DEVICE LOG] #2      _CustomZone.run (dart:async/zone.dart:1023:19)
[        ] [DEVICE LOG] #3      _runZoned (dart:async/zone.dart:1518:10)
[        ] [DEVICE LOG] #4      runZoned (dart:async/zone.dart:1502:12)
[        ] [DEVICE LOG] #5      ZonedUrl._launch (package:thirteen_march/main.dart:19:37)
[   +3 ms] [DEVICE LOG] #6      ZonedUrl.lauch.<anonymous closure> (package:thirteen_march/main.dart:10:9)
[        ] [DEVICE LOG] <asynchronous suspension>
[        ] [DEVICE LOG] #7      _rootRun (dart:async/zone.dart:1126:13)
[        ] [DEVICE LOG] #8      _CustomZone.run (dart:async/zone.dart:1023:19)
[        ] [DEVICE LOG] #9      _runZoned (dart:async/zone.dart:1518:10)
[        ] [DEVICE LOG] #10     runZoned (dart:async/zone.dart:1502:12)
[        ] [DEVICE LOG] #11     ZonedUrl.lauch (package:thirteen_march/main.dart:8:29)
[        ] [DEVICE LOG] #12     _MyHomePageState.build.<anonymous closure> (package:thirteen_march/main.dart:49:45)
[        ] [DEVICE LOG] #13     _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:706:14)
[        ] [DEVICE LOG] #14     _I<…>
[  +89 ms] flutter: runZoned cought...
[        ]  object: launch returned null
[        ]  stack: #0      ZonedUrl._launch.<anonymous closure> (package:thirteen_march/main.dart:22:37)
[        ] <asynchronous suspension>
[        ] #1      _rootRun (dart:async/zone.dart:1126:13)
[        ] #2      _CustomZone.run (dart:async/zone.dart:1023:19)
[        ] #3      _runZoned (dart:async/zone.dart:1518:10)
[   +1 ms] #4      runZoned (dart:async/zone.dart:1502:12)
[        ] #5      ZonedUrl._launch (package:thirteen_march/main.dart:19:37)
[   +4 ms] #6      ZonedUrl.lauch.<anonymous closure> (package:thirteen_march/main.dart:10:9)
[        ] <asynchronous suspension>
[        ] #7      _rootRun (dart:async/zone.dart:1126:13)
[        ] #8      _CustomZone.run (dart:async/zone.dart:1023:19)
[        ] #9      _runZoned (dart:async/zone.dart:1518:10)
[        ] #10     runZoned (dart:async/zone.dart:1502:12)
[        ] #11     ZonedUrl.lauch (package:thirteen_march/main.dart:8:29)
[        ] #12     _MyHomePageState.build.<anonymous closure> (package:thirteen_march/main.dart:49:45)
[        ] #13     _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:706:14)
[        ] #14     _I<…>
[+25601 ms] DevFS: Deleting filesystem on the device
(file:///Users/nevercode/Library/Developer/CoreSimulator/Devices/D5F70F31-B488-4454-9539-320B5551D92A/data/Containers/Data/Application/F32786F9-E94E-4182-8E6D-01C343D276FD/tmp/thirteen_marchWQ7uJW/thirteen_march/)
[   +2 ms] Sending to VM service: _deleteDevFS({fsName: thirteen_march})
[  +11 ms] Result: {type: Success}
[        ] DevFS: Deleted filesystem on the device
(file:///Users/nevercode/Library/Developer/CoreSimulator/Devices/D5F70F31-B488-4454-9539-320B5551D92A/data/Containers/Data/Application/F32786F9-E94E-4182-8E6D-01C343D276FD/tmp/thirteen_marchWQ7uJW/thirteen_march/)
[   +6 ms] Sending to VM service: ext.flutter.exit({isolateId: isolates/867966743721335})
[  +46 ms] Service protocol connection closed.
[+1960 ms] Application finished.
[   +7 ms] "flutter run" took 121,110ms.
```

</details>

<details>
  <summary>doctor</summary>

```console
 nevercode@Nevercodes-MacBook-Air  ~/Desktop/projects/thirteen_march  flutter doctor -v                                                                                                                               ✔  637  15:09:08
[✓] Flutter (Channel stable, v1.12.13+hotfix.8, on Mac OS X 10.15.3 19D76, locale en-EE)
    • Flutter version 1.12.13+hotfix.8 at /Users/nevercode/development/flutter
    • Framework revision 0b8abb4724 (4 weeks ago), 2020-02-11 11:44:36 -0800
    • Engine revision e1e6ced81d
    • Dart version 2.7.0


[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/nevercode/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.3.1, Build version 11C504
    • CocoaPods version 1.9.0

[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 43.0.1
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)

[✓] VS Code
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.8.1

[✓] Connected device (1 available)
    • iPhone 8 • D5F70F31-B488-4454-9539-320B5551D92A • ios • com.apple.CoreSimulator.SimRuntime.iOS-13-3 (simulator)

• No issues found!
```

</details>
