### ISSUE TITLE
The method '>' is called on null

### ISSUE THREAD

**Issue by RJSD3V** [flutter/flutter#47327]
I am receiving this error for a while now, and all I try to do is make a container inside another container. I am certain that I'm using the right syntax, although the code and the stack trace are posted below. Also, can someone suggest a way which makes reading Flutter Stack traces Easier?

```dart
import 'package:flutter/material.dart';



void main() {runApp(MyApp());}
class MyApp extends StatelessWidget{

  Widget build(BuildContext context){
    return Container(
      alignment: Alignment.topLeft,
      height: 50,
      width:50,
      decoration: BoxDecoration(
        color:Colors.white,


      ),

      child: Row(
        children:<Widget>[
          Container(
            width: 50,
            height:50,
            decoration: BoxDecoration(color:Colors.deepOrange[400]),)
        ],
      ),

    ) ;
  }
}

```

`Performing hot reload...
```bash
Syncing files to device Android SDK built for x86...

════════ Exception caught by rendering library ═════════════════════════════════════════════════════
The following assertion was thrown during performLayout():
Horizontal RenderFlex with MainAxisAlignment.start has a null textDirection, so the alignment cannot be resolved.
'package:flutter/src/rendering/flex.dart':
Failed assertion: line 450 pos 18: 'textDirection != null'


Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=BUG.md

User-created ancestor of the error-causing widget was: 
  Container file:///C:/Users/rjsod/AndroidStudioProjects/flutter_app/lib/main.dart:9:12
When the exception was thrown, this was the stack: 
#2      RenderFlex._debugHasNecessaryDirections (package:flutter/src/rendering/flex.dart:450:18)
#3      RenderFlex.performLayout (package:flutter/src/rendering/flex.dart:638:12)
#4      RenderObject.layout (package:flutter/src/rendering/object.dart:1701:7)
#5      RenderPositionedBox.performLayout (package:flutter/src/rendering/shifted_box.dart:392:13)
#6      RenderObject.layout (package:flutter/src/rendering/object.dart:1701:7)
...
The following RenderObject was being processed when the exception was fired: RenderFlex#b62d3 relayoutBoundary=up1 NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
...  parentData: offset=Offset(0.0, 0.0) (can use size)
...  constraints: BoxConstraints(0.0<=w<=360.0, 0.0<=h<=592.0)
...  size: MISSING
...  direction: horizontal
...  mainAxisAlignment: start
...  mainAxisSize: max
...  crossAxisAlignment: center
...  verticalDirection: down
RenderObject: RenderFlex#b62d3 relayoutBoundary=up1 NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
  parentData: offset=Offset(0.0, 0.0) (can use size)
  constraints: BoxConstraints(0.0<=w<=360.0, 0.0<=h<=592.0)
  size: MISSING
  direction: horizontal
  mainAxisAlignment: start
  mainAxisSize: max
  crossAxisAlignment: center
  verticalDirection: down
...  child 1: RenderConstrainedBox#2da87 NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
...    parentData: offset=Offset(0.0, 0.0); flex=null; fit=null
...    constraints: MISSING
...    size: MISSING
...    additionalConstraints: BoxConstraints(w=50.0, h=50.0)
...    child: RenderDecoratedBox#bd1c7 NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
...      parentData: <none>
...      constraints: MISSING
...      size: MISSING
...      decoration: BoxDecoration
...        color: Color(0xffff7043)
...      configuration: ImageConfiguration(bundle: PlatformAssetBundle#f3ee4(), devicePixelRatio: 1.0, platform: android)
════════════════════════════════════════════════════════════════════════════════════════════════════

════════ (2) Exception caught by rendering library ═════════════════════════════════════════════════
'package:flutter/src/rendering/shifted_box.dart': Failed assertion: line 321 pos 12: 'child.hasSize': is not true.
User-created ancestor of the error-causing widget was: 
  Container file:///C:/Users/rjsod/AndroidStudioProjects/flutter_app/lib/main.dart:9:12
════════════════════════════════════════════════════════════════════════════════════════════════════
Reloaded 1 of 468 libraries in 386ms.

════════ (3) Exception caught by rendering library ═════════════════════════════════════════════════
The method '>' was called on null.
Receiver: null
Tried calling: >(1e-10)
User-created ancestor of the error-causing widget was: 
  Container file:///C:/Users/rjsod/AndroidStudioProjects/flutter_app/lib/main.dart:9:12
════════════════════════════════════════════════════════════════════════════════════════════════════
`
```

**Comment by HansMuller** [comment]
Your app needs to be within a MaterialApp (or a WidgetsApp or a CupertinoApp). The App widgets set up some basic inherited widgets, like https://api.flutter.dev/flutter/widgets/Directionality-class.html

The app generated by `Flutter create` is set up this way.

**Comment by TahaTesser** [comment]
Hi @RJSD3V 

### Code Sample
```
import 'package:flutter/material.dart';

void main() {
  runApp(MaterialApp(home: MyApp()));
}

class MyApp extends StatelessWidget {
  Widget build(BuildContext context) {
    return Scaffold(
      body: Center(
        child: Container(
          alignment: Alignment.topLeft,
          height: 50,
          width: 50,
          decoration: BoxDecoration(
            color: Colors.white,
          ),
          child: Row(
            children: <Widget>[
              Container(
                width: 50,
                height: 50,
                decoration: BoxDecoration(color: Colors.deepOrange[400]),
              )
            ],
          ),
        ),
      ),
    );
  }
}

```

Closing, as this isn't an issue with Flutter itself,
if you disagree please write in the comments and I will reopen it 
Thank you
