### ISSUE TITLE
Build APK Error - Flutter 1.12.13 + hotfix.5 - Channel stable

### ISSUE THREAD

**Issue by phcaraujo** [flutter/flutter#47337]
### **flutter doctor -v**

```
[√] Flutter (Channel stable, v1.12.13+hotfix.5, on Microsoft Windows [versÃ£o 10.0.17763.914], locale pt-BR)
    • Flutter version 1.12.13+hotfix.5 at C:\flutter
    • Framework revision 27321ebbad (8 days ago), 2019-12-10 18:15:01 -0800
    • Engine revision 2994f7e1e6
    • Dart version 2.7.0


[√] Android toolchain - develop for Android devices (Android SDK version 29.0.1)
    • Android SDK at C:\Users\Pedro\AppData\Local\Android\Sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.1
    • ANDROID_HOME = C:\Users\Pedro\AppData\Local\Android\Sdk
    • Java binary at: C:\Program Files (x86)\Common Files\Oracle\Java\javapath\java.exe
    • Java version Java(TM) SE Runtime Environment (build 1.8.0_231-b11)
    • All Android licenses accepted.

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/setup/#android-setup for detailed instructions).

[√] VS Code (version 1.41.0)
    • VS Code at C:\Users\Pedro\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.7.1
```

### **flutter run --verbose**

```
[  +55 ms] executing: [C:\flutter\] git -c log.showSignature=false log -n 1 --pretty=format:%H
[ +105 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[   +3 ms] 27321ebbad34b0a3fafe99fac037102196d655ff
[   +1 ms] executing: [C:\flutter\] git describe --match v*.*.* --first-parent --long --tags
[ +111 ms] Exit code 0 from: git describe --match v*.*.* --first-parent --long --tags
[   +1 ms] v1.12.13+hotfix.5-0-g27321ebba
[  +11 ms] executing: [C:\flutter\] git rev-parse --abbrev-ref --symbolic @{u}
[  +75 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[   +1 ms] origin/stable
[        ] executing: [C:\flutter\] git ls-remote --get-url origin
[  +71 ms] Exit code 0 from: git ls-remote --get-url origin
[   +1 ms] https://github.com/flutter/flutter.git
[ +144 ms] executing: [C:\flutter\] git rev-parse --abbrev-ref HEAD
[  +80 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[   +1 ms] stable
[ +198 ms] executing: C:\Users\Pedro\AppData\Local\Android\Sdk\platform-tools\adb.exe devices -l
[  +43 ms] Exit code 0 from: C:\Users\Pedro\AppData\Local\Android\Sdk\platform-tools\adb.exe devices -l
[   +1 ms] List of devices attached
[  +15 ms] No supported devices connected.
[  +17 ms] "flutter run" took 355ms.

#0      throwToolExit (package:flutter_tools/src/base/common.dart:28:3)
#1      RunCommand.validateCommand (package:flutter_tools/src/commands/run.dart:289:7)
<asynchronous suspension>
#2      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:590:11)
#3      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:515:33)
<asynchronous suspension>
#4      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:146:29)
#5      _rootRun (dart:async/zone.dart:1126:13)
#6      _CustomZone.run (dart:async/zone.dart:1023:19)
#7      _runZoned (dart:async/zone.dart:1518:10)
#8      runZoned (dart:async/zone.dart:1465:12)
#9      AppContext.run (package:flutter_tools/src/base/context.dart:145:18)
#10     FlutterCommand.run (package:flutter_tools/src/runner/flutter_command.dart:505:20)
#11     CommandRunner.runCommand (package:args/command_runner.dart:197:27)
#12     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:413:21)
<asynchronous suspension>
#13     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:146:29)
#14     _rootRun (dart:async/zone.dart:1126:13)
#15     _CustomZone.run (dart:async/zone.dart:1023:19)
#16     _runZoned (dart:async/zone.dart:1518:10)
#17     runZoned (dart:async/zone.dart:1465:12)
#18     AppContext.run (package:flutter_tools/src/base/context.dart:145:18)
#19     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:364:19)
#20     CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:112:25)
#21     new Future.sync (dart:async/future.dart:224:31)
#22     CommandRunner.run (package:args/command_runner.dart:112:14)
#23     FlutterCommandRunner.run (package:flutter_tools/src/runner/flutter_command_runner.dart:250:18)
#24     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:63:22)
#25     _rootRun (dart:async/zone.dart:1126:13)
#26     _CustomZone.run (dart:async/zone.dart:1023:19)
#27     _runZoned (dart:async/zone.dart:1518:10)
#28     runZoned (dart:async/zone.dart:1502:12)
#29     run.<anonymous closure> (package:flutter_tools/runner.dart:61:18)
<asynchronous suspension>
#30     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:146:29)
#31     _rootRun (dart:async/zone.dart:1126:13)
#32     _CustomZone.run (dart:async/zone.dart:1023:19)
#33     _runZoned (dart:async/zone.dart:1518:10)
#34     runZoned (dart:async/zone.dart:1465:12)
#35     AppContext.run (package:flutter_tools/src/base/context.dart:145:18)
#36     runInContext (package:flutter_tools/src/context_runner.dart:64:24)
#37     run (package:flutter_tools/runner.dart:50:10)
#38     main (package:flutter_tools/executable.dart:65:9)
#39     main (file:///C:/flutter/packages/flutter_tools/bin/flutter_tools.dart:8:3)
#40     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:305:32)
#41     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:174:12)
```

### **local.properties**

```
sdk.dir=C:\\Users\\Pedro\\AppData\\Local\\Android\\Sdk
flutter.sdk=C:\\flutter
flutter.buildMode=release
flutter.versionName=1.6.0
flutter.versionCode=1
```

### **build.gradle**

```
compileSdkVersion 28
...
minSdkVersion 21
targetSdkVersion 28
```

### **gradle.properties**

```
org.gradle.jvmargs=-Xmx1536M
android.useAndroidX=true
android.enableJetifier=true
android.enableR8=true
```

![image1](https://user-images.githubusercontent.com/20992411/71093159-68286200-2187-11ea-9eda-a76ede827d12.jpg)
![image2](https://user-images.githubusercontent.com/20992411/71093161-68286200-2187-11ea-9b23-29e1f911cc85.jpg)

**Comment by nivla360** [comment]
I have the same issue. I'm able to build profile apk as well as debug but I get the same error when I try to build release apk

**Comment by phcaraujo** [comment]
> I have the same issue. I'm able to build profile apk as well as debug but I get the same error when I try to build release apk

Yes, i can also debug.
But i cant create the release.

**Comment by Icyoung** [comment]
same with you

**Comment by opensourcegps** [comment]
"fontVariationSettings not found" issue is fixable by this: https://github.com/flutter/flutter/issues/27226#issuecomment-567018039

**Comment by phcaraujo** [comment]
> "fontVariationSettings not found" issue is fixable by this: [#27226 (comment)](https://github.com/flutter/flutter/issues/27226#issuecomment-567018039)

Looks like you didnt read it, my build.gradle file is already with this version.

**Comment by phcaraujo** [comment]
I solved my problem
https://github.com/flutter/flutter/issues/46881#issuecomment-565055083
and
https://github.com/adee42/flutter_keyboard_visibility/issues/42#issuecomment-566656630

**Comment by nivla360** [comment]
Well, I guess the only option I'm left with is to downgrade my flutter SDK because building a release apk was working fine until I upgraded and I also have to release this app asap

**Comment by iapicca** [comment]
Hi @phcaraujo 
I'm glad that you solved the issue
thank you for letting me know

**Comment by nivla360** [comment]
> Hi @phcaraujo
> I'm glad that you solved the issue
> thank you for letting me know

I think he means he solved his other two problems 
#46881 (comment) and this
adee42/flutter_keyboard_visibility#42 (comment)
Not this issue (Build ApK Error)

**Comment by phcaraujo** [comment]
> > Hi @phcaraujo
> > I'm glad that you solved the issue
> > thank you for letting me know
> 
> I think he means he solved his other two problems
> #46881 (comment) and this
> [adee42/flutter_keyboard_visibility#42](https://github.com/adee42/flutter_keyboard_visibility/issues/42) (comment)
> Not this issue (Build ApK Error)

i meant that i solved my problem through the two topics i mentioned.
