### ISSUE TITLE
[E2E] Crashed on startup on device 32 bit android

### ISSUE THREAD

**Issue by duongtruong12** [flutter/flutter#47402]
I just downloaded example of E2E and android alarm manager and build debug for test, but the app crashed on startup on my SamSung A5, my SamSung s8 was ok through.
Here is the logs:

> 12-19 09:15:11.851 17393 17393 W FlutterEngine: Tried to automatically register plugins with FlutterEngine (io.flutter.embedding.engine.FlutterEngine@f779415) but could not find and invoke the GeneratedPluginRegistrant.
12-19 09:15:11.851 17393 17393 D FlutterActivityAndFragmentDelegate: Attaching FlutterEngine to the Activity that owns this Fragment.
12-19 09:15:11.861 17393 17393 D AndroidRuntime: Shutting down VM
12-19 09:15:11.861 17393 17393 E AndroidRuntime: FATAL EXCEPTION: main
12-19 09:15:11.861 17393 17393 E AndroidRuntime: Process: com.example.e2e_example, PID: 17393
12-19 09:15:11.861 17393 17393 E AndroidRuntime: java.lang.NoClassDefFoundError: Failed resolution of: Ljava/util/concurrent/CompletableFuture;
12-19 09:15:11.861 17393 17393 E AndroidRuntime: 	at dev.flutter.plugins.e2e.E2EPlugin.<clinit>(E2EPlugin.java:22)
12-19 09:15:11.861 17393 17393 E AndroidRuntime: 	at com.example.e2e_example.MainActivity.configureFlutterEngine(MainActivity.java:14)
12-19 09:15:11.861 17393 17393 E AndroidRuntime: 	at io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.onAttach(FlutterActivityAndFragmentDelegate.java:185)
12-19 09:15:11.861 17393 17393 E AndroidRuntime: 	at io.flutter.embedding.android.FlutterActivity.onCreate(FlutterActivity.java:418)
12-19 09:15:11.861 17393 17393 E AndroidRuntime: 	at android.app.Activity.performCreate(Activity.java:6904)
12-19 09:15:11.861 17393 17393 E AndroidRuntime: 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1136)
12-19 09:15:11.861 17393 17393 E AndroidRuntime: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3266)
12-19 09:15:11.861 17393 17393 E AndroidRuntime: 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3415)
12-19 09:15:11.861 17393 17393 E AndroidRuntime: 	at android.app.ActivityThread.access$1100(ActivityThread.java:229)
12-19 09:15:11.861 17393 17393 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1821)
12-19 09:15:11.861 17393 17393 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:102)
12-19 09:15:11.861 17393 17393 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:148)
12-19 09:15:11.861 17393 17393 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7331)
12-19 09:15:11.861 17393 17393 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
12-19 09:15:11.861 17393 17393 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
12-19 09:15:11.861 17393 17393 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)
12-19 09:15:11.861 17393 17393 E AndroidRuntime: Caused by: java.lang.ClassNotFoundException: Didn't find class "java.util.concurrent.CompletableFuture" on path: DexPathList[[zip file "/data/app/com.example.e2e_example-1/base.apk"],nativeLibraryDirectories=[/data/app/com.example.e2e_example-1/lib/arm, /data/app/com.example.e2e_example-1/base.apk!/lib/armeabi-v7a, /vendor/lib, /system/lib]]
12-19 09:15:11.861 17393 17393 E AndroidRuntime: 	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
12-19 09:15:11.861 17393 17393 E AndroidRuntime: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
12-19 09:15:11.861 17393 17393 E AndroidRuntime: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
12-19 09:15:11.861 17393 17393 E AndroidRuntime: 	... 16 more
12-19 09:15:11.861 17393 17393 E AndroidRuntime: 	Suppressed: java.lang.ClassNotFoundException: java.util.concurrent.CompletableFuture
12-19 09:15:11.861 17393 17393 E AndroidRuntime: 		at java.lang.Class.classForName(Native Method)
12-19 09:15:11.861 17393 17393 E AndroidRuntime: 		at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
12-19 09:15:11.861 17393 17393 E AndroidRuntime: 		at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
12-19 09:15:11.861 17393 17393 E AndroidRuntime: 		at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
12-19 09:15:11.861 17393 17393 E AndroidRuntime: 		... 17 more
12-19 09:15:11.861 17393 17393 E AndroidRuntime: 	Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack trace available
12-19 09:15:11.861  1775  1798 W ActivityManager:   Force finishing activity com.example.e2e_example/.MainActivity

**Comment by duongtruong12** [comment]
found the problem, it is because of CompletableFuture of java only support java 8 and api 24 above. So i download the plugin and customize by using 

>         implementation 'net.sourceforge.streamsupport:streamsupport-cfuture:1.7.0'

and import

> import java8.util.concurrent.CompletableFuture;
 the problem is solved with device below api 24
