### ISSUE TITLE
Textfield enable property bug

### ISSUE THREAD

**Issue by awaik** [flutter/flutter#47412]
Hello, after updating Flutter my package is experiencing issue and I can't fix it.

```console
[✓] Flutter (Channel stable, v1.12.13+hotfix.5, on Mac OS X 10.15.2 19C57, locale en-RU)
    • Flutter version 1.12.13+hotfix.5 at /Users/macbook/development/flutter
    • Framework revision 27321ebbad (8 days ago), 2019-12-10 18:15:01 -0800
    • Engine revision 2994f7e1e6
    • Dart version 2.7.0

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.1)
    • Android SDK at /Users/macbook/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.1
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.0, Build version 11A420a
    • CocoaPods version 1.8.4

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 42.1.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] Connected device (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 10 (API 29) (emulator)

• No issues found!
```

## Steps to Reproduce

Run example of the package https://pub.dev/packages/flutter_verification_code 
There are four text fields and when focusNode & enabled changing

```dart
    return TextField(
      key: UniqueKey(),
      keyboardType: widget.keyboardType,
      maxLines: 1,
      maxLength: 2,
      enabled: _currentIndex == index,
      focusNode: _listFocusNode[index],
```

Flutter throws errors

<details>
  <summary>logs</summary>

```bash
I/flutter ( 9209): ══╡ EXCEPTION CAUGHT BY FOUNDATION LIBRARY ╞════════════════════════════════════════════════════════
I/flutter ( 9209): The following assertion was thrown while dispatching notifications for FocusNode:
I/flutter ( 9209): RenderBox was not laid out: RenderEditable#effd1 NEEDS-LAYOUT NEEDS-PAINT
I/flutter ( 9209): 'package:flutter/src/rendering/box.dart':
I/flutter ( 9209): Failed assertion: line 1687 pos 12: 'hasSize'
I/flutter ( 9209): 
I/flutter ( 9209): Either the assertion indicates an error in the framework itself, or we should provide substantially
I/flutter ( 9209): more information in this error message to help you determine and fix the underlying cause.
I/flutter ( 9209): In either case, please report this assertion by filing a bug on GitHub:
I/flutter ( 9209):   https://github.com/flutter/flutter/issues/new?template=BUG.md
I/flutter ( 9209): 
I/flutter ( 9209): When the exception was thrown, this was the stack:
I/flutter ( 9209): #2      RenderBox.size (package:flutter/src/rendering/box.dart:1687:12)
I/flutter ( 9209): #3      EditableTextState._updateSizeAndTransform (package:flutter/src/widgets/editable_text.dart:1729:40)
I/flutter ( 9209): #4      EditableTextState._openInputConnection (package:flutter/src/widgets/editable_text.dart:1415:7)
I/flutter ( 9209): #5      EditableTextState._openOrCloseInputConnectionIfNeeded (package:flutter/src/widgets/editable_text.dart:1441:7)
I/flutter ( 9209): #6      EditableTextState._handleFocusChanged (package:flutter/src/widgets/editable_text.dart:1707:5)
I/flutter ( 9209): #7      ChangeNotifier.notifyListeners (package:flutter/src/foundation/change_notifier.dart:206:21)
I/flutter ( 9209): #8      FocusNode._notify (package:flutter/src/widgets/focus_manager.dart:808:5)
I/flutter ( 9209): #9      FocusManager._applyFocusChange (package:flutter/src/widgets/focus_manager.dart:1401:12)
I/flutter ( 9209): (elided 12 frames from class _AssertionError and package dart:async)
I/flutter ( 9209): 
I/flutter ( 9209): The FocusNode sending notification was:
I/flutter ( 9209):   FocusNode#61d4e
I/flutter ( 9209): ════════════════════════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by rendering library ═════════════════════════════════════════════════════
The following assertion was thrown during paint():
'dart:ui/text.dart': Failed assertion: line 1372: '<optimized out>': is not true.


Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=BUG.md

The relevant error-causing widget was: 
  TextField-[#c09bb] file:///Users/macbook/projects/flutter_verification_code/lib/src/flutter_verification_code.dart:63:12
When the exception was thrown, this was the stack: 
#2      new TextPosition (dart:ui/text.dart:1372:15)
#3      RenderEditable._updateSelectionExtentsVisibility (package:flutter/src/rendering/editable.dart:367:7)
#4      RenderEditable._paintContents (package:flutter/src/rendering/editable.dart:1956:7)
#5      RenderEditable.paint (package:flutter/src/rendering/editable.dart:2012:7)
#6      RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2219:7)
...
The following RenderObject was being processed when the exception was fired: RenderEditable#3e34b relayoutBoundary=up11
...  parentData: <none> (can use size)
...  constraints: BoxConstraints(w=30.0, 0.0<=h<=10.9)
...  size: Size(30.0, 10.9)
...  cursorColor: Color(0x004285f4)
...  showCursor: ValueNotifier<bool>#b393e(true)
...  maxLines: 1
...  minLines: null
...  selectionColor: Color(0xff90caf9)
...  textScaleFactor: 1.0
...  locale: en_US
...  selection: TextSelection(baseOffset: 1, extentOffset: 1, affinity: null, isDirectional: false)
...  offset: ScrollPositionWithSingleContext#bd304(offset: 0.0, range: 0.0..0.0, viewport: 30.0, ScrollableState, ClampingScrollPhysics, IdleScrollActivity#7118c, ScrollDirection.idle)
  text: TextSpan
    debugLabel: ((englishLike subhead 2014).merge(blackMountainView subhead)).merge(unknown)
    inherit: false
    color: Color(0xff000000)
    family: Roboto
    size: 25.0
    weight: 400
    baseline: alphabetic
    decoration: TextDecoration.none
    "1"
RenderObject: RenderEditable#3e34b relayoutBoundary=up11
  parentData: <none> (can use size)
  constraints: BoxConstraints(w=30.0, 0.0<=h<=10.9)
  size: Size(30.0, 10.9)
  cursorColor: Color(0x004285f4)
  showCursor: ValueNotifier<bool>#b393e(true)
  maxLines: 1
  minLines: null
  selectionColor: Color(0xff90caf9)
  textScaleFactor: 1.0
  locale: en_US
  selection: TextSelection(baseOffset: 1, extentOffset: 1, affinity: null, isDirectional: false)
  offset: ScrollPositionWithSingleContext#bd304(offset: 0.0, range: 0.0..0.0, viewport: 30.0, ScrollableState, ClampingScrollPhysics, IdleScrollActivity#7118c, ScrollDirection.idle)
  text: TextSpan
    debugLabel: ((englishLike subhead 2014).merge(blackMountainView subhead)).merge(unknown)
    inherit: false
    color: Color(0xff000000)
    family: Roboto
    size: 25.0
    weight: 400
    baseline: alphabetic
    decoration: TextDecoration.none
    "1"
════════════════════════════════════════════════════════════════════════════════════════════════════
```

</details>

**Comment by iapicca** [comment]
Hi @awaik 
if you just upgrade flutter you may want to run
`flutter clean`
`flutter pub cache repair`
let me know if the issue persists
thank you

**Comment by awaik** [comment]
Hi @iapicca 
I wiped out data from emulator and ran that you suggested
`flutter clean`
`flutter pub cache repair`
sorry, but no any effects, the same error.

**Comment by awaik** [comment]
Hello, any news?

**Comment by awaik** [comment]
Finally found the reason of this bug. I used 
`enabled: true,`
simultaneously with    
```
TextField(
  focusNode: _listFocusNode[index],
```
when I disabled it bug disappeared.
