### ISSUE TITLE
these issues come after flutter upgrade to 12

### ISSUE THREAD

**Issue by gajendrabhati** [flutter/flutter#47445]
```bash
Launching lib/main.dart on CPH1723 in debug mode...
E/flutter (15750): [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: PlatformException(error, Unable to find explicit activity class {com.harshtechnology.player_auction/com.yalantis.ucrop.UCropActivity}; have you declared this activity in your AndroidManifest.xml?, null)
E/flutter (15750): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:569:7)
E/flutter (15750): #1      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:321:33)
E/flutter (15750): <asynchronous suspension>                            
E/flutter (15750): #2      ImageCropper.cropImage (package:image_cropper/src/cropper.dart:103:24)
E/flutter (15750): <asynchronous suspension>                            
E/flutter (15750): #3      _AddPlayerState.cropImage (package:player_auction/myauction/add_player.dart:335:38)
E/flutter (15750): #4      _AddPlayerState.getImageGallery (package:player_auction/myauction/add_player.dart:324:5)
E/flutter (15750): <asynchronous suspension>                            
E/flutter (15750): #5      _AddPlayerState.uploadImageDiaog.<anonymous closure>.<anonymous closure> (package:player_auction/myauction/add_player.dart:1381:25)
E/flutter (15750): #6      _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:706:14)
E/flutter (15750): #7      _InkResponseState.build.<anonymous closure> (package:flutter/src/material/ink_well.dart:789:36)
E/flutter (15750): #8      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:182:24)
E/flutter (15750): #9      TapGestureRecognizer.handleTapUp (package:flutter/src/gestures/tap.dart:486:11)
E/flutter (15750): #10     BaseTapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:264:5)
E/flutter (15750): #11     BaseTapGestureRecognizer.handlePrimaryPointer (package:flutter/src/gestures/tap.dart:199:7)
E/flutter (15750): #12     PrimaryPointerGestureRecognizer.handleEvent (package:flutter/src/gestures/recognizer.dart:467:9)
E/flutter (15750): #13     PointerRouter._dispatch (package:flutter/src/gestures/pointer_router.dart:76:12)
E/flutter (15750): #14     PointerRouter._dispatchEventToRoutes.<anonymous closure> (package:flutter/src/gestures/pointer_router.dart:117:9)
E/flutter (15750): #15     _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:379:8)
E/flutter (15750): #16     PointerRouter._dispatchEventToRoutes (package:flutter/src/gestures/pointer_router.dart:115:18)
E/flutter (15750): #17     PointerRouter.route (package:flutter/src/gestures/pointer_router.dart:101:7)
E/flutter (15750): #18     GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:218:19)
E/flutter (15750): #19     GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:198:22)
E/flutter (15750): #20     GestureBinding._handlePointerEvent (package:flutter/src/gestures/binding.dart:156:7)
E/flutter (15750): #21     GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:102:7)
E/flutter (15750): #22     GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:86:7)
E/flutter (15750): #23     _rootRunUnary (dart:async/zone.dart:1138:13) 
E/flutter (15750): #24     _CustomZone.runUnary (dart:async/zone.dart:1031:19)
E/flutter (15750): #25     _CustomZone.runUnaryGuarded (dart:async/zone.dart:933:7)
E/flutter (15750): #26     _invoke1 (dart:ui/hooks.dart:273:10)         
E/flutter (15750): #27     _dispatchPointerDataPacket (dart:ui/hooks.dart:182:5)
E/flutter (15750):                                                      
                                                                        
FAILURE: Build failed with an exception.                                
                                                                        
* What went wrong:                                                      
Execution failed for task ':app:processDebugResources'.                 
> A failure occurred while executing com.android.build.gradle.internal.tasks.Workers$ActionFacade
   > Android resource linking failed                                    
     /Users/madhosingh/mukesh/flutter/player_auction/android/app/src/main/AndroidManifest.xml:31:5-34:67: AAPT: error: unexpected element <activity> found in <manifest>.
                                                                        
                                                                        
* Try:                                                                  
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
                                                                        
* Get more help at https://help.gradle.org                              
                                                                        
BUILD FAILED in 21s                                                     
Running Gradle task 'assembleDebug'...                                  
Running Gradle task 'assembleDebug'... Done                        23.1s
The built failed likely due to AndroidX incompatibilities in a plugin. The tool is about to try using Jetfier to solve the
incompatibility.
✏️  Creating `android/settings_aar.gradle`...                        4ms
✓ `android/settings_aar.gradle` created successfully.
Building plugin fluttertoast...
Running Gradle task 'assembleAarRelease'...                             
Running Gradle task 'assembleAarRelease'... Done                   10.9s
✓ Built build/app/outputs/repo.
Building plugin image_cropper...
Running Gradle task 'assembleAarRelease'...                             
Running Gradle task 'assembleAarRelease'... Done                    0.0s

Sending crash report to Google.
Crash report sent (report ID: b67ee67409c713a2)
Oops; flutter has exited unexpectedly.
 
Crash report written to /Users/madhosingh/mukesh/flutter/player_auction/flutter_02.log;
please let us know at https://github.com/flutter/flutter/issues.
```

## command

flutter run

## exception

```bash
ProcessException: ProcessException: Permission denied
  Command: /Users/madhosingh/Library/Android/sdk/flutter/.pub-cache/hosted/pub.dartlang.org/image_cropper-1.1.2/android/gradlew -I=/Users/madhosingh/Library/Android/sdk/flutter/packages/flutter_tools/gradle/aar_init_script.gradle -Pflutter-root=/Users/madhosingh/Library/Android/sdk/flutter -Poutput-dir=/Users/madhosingh/mukesh/flutter/player_auction/build/app -Pis-plugin=true -Ptarget-platform=android-arm,android-arm64,android-x64 assembleAarRelease


#0      _DefaultProcessUtils.run (package:flutter_tools/src/base/process.dart:266:37)
<asynchronous suspension>
#1      buildGradleAar (package:flutter_tools/src/android/gradle.dart:548:33)
#2      buildPluginsAsAar (package:flutter_tools/src/android/gradle.dart:711:13)
<asynchronous suspension>
#3      buildGradleApp (package:flutter_tools/src/android/gradle.dart:257:11)
#4      _AsyncAwaitCompleter.start (dart:async-patch/async_patch.dart:45:6)
#5      buildGradleApp (package:flutter_tools/src/android/gradle.dart:218:28)
#6      buildGradleApp (package:flutter_tools/src/android/gradle.dart:415:19)
#7      _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:73:64)
#8      _rootRunUnary (dart:async/zone.dart:1134:38)
#9      _CustomZone.runUnary (dart:async/zone.dart:1031:19)
#10     _FutureListener.handleValue (dart:async/future_impl.dart:139:18)
#11     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:680:45)
#12     Future._propagateToListeners (dart:async/future_impl.dart:709:32)
#13     Future._completeWithValue (dart:async/future_impl.dart:524:5)
#14     Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:554:7)
#15     _rootRun (dart:async/zone.dart:1126:13)
#16     _CustomZone.run (dart:async/zone.dart:1023:19)
#17     _CustomZone.runGuarded (dart:async/zone.dart:925:7)
#18     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:965:23)
#19     _microtaskLoop (dart:async/schedule_microtask.dart:43:21)
#20     _startMicrotaskLoop (dart:async/schedule_microtask.dart:52:5)
#21     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
#22     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:175:5)

```

## flutter doctor

```console
[32m[✓][39m Flutter (Channel stable, v1.12.13+hotfix.5, on Mac OS X 10.15.2 19C57, locale en-IN)
    [32m•[39m Flutter version 1.12.13+hotfix.5 at /Users/madhosingh/Library/Android/sdk/flutter
    [32m•[39m Framework revision 27321ebbad (8 days ago), 2019-12-10 18:15:01 -0800
    [32m•[39m Engine revision 2994f7e1e6
    [32m•[39m Dart version 2.7.0

[32m[✓][39m Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    [32m•[39m Android SDK at /Users/madhosingh/Library/Android/sdk
    [32m•[39m Android NDK location not configured (optional; useful for native profiling support)
    [32m•[39m Platform android-29, build-tools 29.0.2
    [32m•[39m ANDROID_HOME = /Users/madhosingh/Library/Android/sdk
    [32m•[39m Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    [32m•[39m Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    [32m•[39m All Android licenses accepted.

[32m[✓][39m Xcode - develop for iOS and macOS (Xcode 11.3)
    [32m•[39m Xcode at /Applications/Xcode.app/Contents/Developer
    [32m•[39m Xcode 11.3, Build version 11C29
    [32m•[39m CocoaPods version 1.8.4

[32m[✓][39m Android Studio (version 3.5)
    [32m•[39m Android Studio at /Applications/Android Studio.app/Contents
    [32m•[39m Flutter plugin version 40.2.2
    [32m•[39m Dart plugin version 191.8593
    [32m•[39m Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[32m[✓][39m Connected device (1 available)
    [32m•[39m CPH1723 • SS5T5SSGBM89CMYD • android-arm64 • Android 7.1.1 (API 25)

[32m•[39m No issues found!
```

**Comment by iapicca** [comment]
Hi @gajendrabhati 
could you please run 
`flutter clean`
`flutter pub cache repair`

If the issue persist please provide your `flutter run --verbose`
together with a a minimal code sample to reproduce the problem
thank you

**Comment by VladyslavBondarenko** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.
Could everyone who still has this problem please file a new issue with the exact descriptions what happens, logs and the output of 'flutter doctor -v'  please.
All system setups can be slightly different so its always better to open new issues and reference related issues.
