### ISSUE TITLE
[cocoon] append-log occasionally fails to commit as key already exists

### ISSUE THREAD

**Issue by CaseyHillers** [flutter/flutter#47453]
This was introduced in https://github.com/flutter/cocoon/pull/564 where the change to `LogChunk` key should have only been made visible for testing. This has resulted in an increased amount of 500s from `/api/append-log` which makes the agent fail to finish the task.

```
The transaction was aborted.
#0      GrpcDatastoreImpl.commit (package:appengine/src/grpc_api_impl/datastore_impl.dart:111:9)
<asynchronous suspension>
#1      _commitHelper (package:gcloud/src/db/db.dart:409:8)
#2      Transaction.commit (package:gcloud/src/db/db.dart:104:14)
#3      AppendLog.post.<anonymous closure> (package:cocoon_service/src/request_handlers/append_log.dart:67:25)
#4      DatastoreDB.withTransaction.<anonymous closure> (package:gcloud/src/db/db.dart:302:32)
#5      _rootRunUnary (dart:async/zone.dart:1134:38)
#6      _CustomZone.runUnary (dart:async/zone.dart:1031:19)
#7      _FutureListener.handleValue (dart:async/future_impl.dart:139:18)
#8      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:680:45)
#9      Future._propagateToListeners (dart:async/future_impl.dart:709:32)
#10     Future._completeWithValue (dart:async/future_impl.dart:524:5)
#11     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:32:15)
#12     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:290:13)
#13     GrpcDatastoreImpl.beginTransaction (package:appengine/src/grpc_api_impl/datastore_impl.dart)
<asynchronous suspension>
#14     DatastoreDB.withTransaction (package:gcloud/src/db/db.dart:299:10)
#15     AppendLog.post (package:cocoon_service/src/request_handlers/append_log.dart:65:21)
<asynchronous suspension>
#16     RequestHandler.service.<anonymous closure> (package:cocoon_service/src/request_handling/request_handler.dart:49:28)
<asynchronous suspension>
#17     _rootRun (dart:async/zone.dart:1126:13)
#18     _CustomZone.run (dart:async/zone.dart:1023:19)
#19     _runZoned (dart:async/zone.dart:1518:10)
#20     runZoned (dart:async/zone.dart:1465:12)
#21     RequestHandler.service (package:cocoon_service/src/request_handling/request_handler.dart:39:12)
#22     ApiRequestHandler.service.<anonymous closure> (package:cocoon_service/src/request_handling/api_request_handler.dart:139:19)
<asynchronous suspension>
#23     _rootRun (dart:async/zone.dart:1126:13)
#24     _CustomZone.run (dart:async/zone.dart:1023:19)
#25     _runZoned (dart:async/zone.dart:1518:10)
#26     runZoned (dart:async/zone.dart:1465:12)
#27     ApiRequestHandler.service (package:cocoon_service/src/request_handling/api_request_handler.dart:138:11)
<asynchronous suspension>
#28     main.<anonymous closure>.<anonymous closure> (file:///app/bin/server.dart:76:23)
<asynchronous suspension>
#29     runAppEngine.<anonymous closure> (package:appengine/appengine.dart:80:12)
#30     runAppEngine.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:appengine/src/appengine_internal.dart:57:18)
#31     _ServiceScope._fork.<anonymous closure> (package:gcloud/service_scope.dart:209:19)
#32     _rootRun (dart:async/zone.dart:1126:13)
#33     _CustomZone.run (dart:async/zone.dart:1023:19)
#34     _runZoned (dart:async/zone.dart:1518:10)
#35     runZoned (dart:async/zone.dart:1502:12)
#36     _ServiceScope._fork (package:gcloud/service_scope.dart:208:12)
#37     fork (package:gcloud/service_scope.dart:104:30)
#38     runAppEngine.<anonymous closure>.<anonymous closure> (package:appengine/src/appengine_internal.dart:55:9)
#39     AppEngineHttpServer.run.<anonymous closure>.<anonymous closure> (package:appengine/src/server/server.dart:83:16)
#40     _rootRunUnary (dart:async/zone.dart:1134:38)
#41     _CustomZone.runUnary (dart:async/zone.dart:1031:19)
#42     _CustomZone.runUnaryGuarded (dart:async/zone.dart:933:7)
#43     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:338:11)
#44     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:265:7)
#45     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:766:19)
#46     _StreamController._add (dart:async/stream_controller.dart:642:7)
#47     _StreamController.add (dart:async/stream_controller.dart:588:5)
#48     _HttpServer._handleRequest (dart:_http/http_impl.dart:2828:19)
#49     new _HttpConnection.<anonymous closure> (dart:_http/http_impl.dart:2586:19)
#50     _rootRunUnary (dart:async/zone.dart:1134:38)
#51     _CustomZone.runUnary (dart:async/zone.dart:1031:19)
#52     _CustomZone.runUnaryGuarded (dart:async/zone.dart:933:7)
#53     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:338:11)
#54     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:265:7)
#55     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:766:19)
#56     _StreamController._add (dart:async/stream_controller.dart:642:7)
#57     _StreamController.add (dart:async/stream_controller.dart:588:5)
#58     _HttpParser._headersEnd (dart:_http/http_parser.dart:388:17)
#59     _HttpParser._doParse (dart:_http/http_parser.dart:703:15)
#60     _HttpParser._parse (dart:_http/http_parser.dart:320:7)
#61     _HttpParser._onData (dart:_http/http_parser.dart:812:5)
#62     _rootRunUnary (dart:async/zone.dart:1134:38)
#63     _CustomZone.runUnary (dart:async/zone.dart:1031:19)
#64     _CustomZone.runUnaryGuarded (dart:async/zone.dart:933:7)
#65     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:338:11)
#66     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:265:7)
#67     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:766:19)
#68     _StreamController._add (dart:async/stream_controller.dart:642:7)
#69     _StreamController.add (dart:async/stream_controller.dart:588:5)
#70     _Socket._onData (dart:io-patch/socket_patch.dart:1831:41)
#71     _rootRunUnary (dart:async/zone.dart:1138:13)
#72     _CustomZone.runUnary (dart:async/zone.dart:1031:19)
#73     _CustomZone.runUnaryGuarded (dart:async/zone.dart:933:7)
#74     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:338:11)
#75     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:265:7)
#76     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:766:19)
#77     _StreamController._add (dart:async/stream_controller.dart:642:7)
#78     _StreamController.add (dart:async/stream_controller.dart:588:5)
#79     new _RawSocket.<anonymous closure> (dart:io-patch/socket_patch.dart:1379:33)
#80     _NativeSocket.issueReadEvent.issue (dart:io-patch/socket_patch.dart:899:14)
#81     _microtaskLoop (dart:async/schedule_microtask.dart:43:21)
#82     _startMicrotaskLoop (dart:async/schedule_microtask.dart:52:5)
#83     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
#84     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:175:5)
```

**Comment by CaseyHillers** [comment]
`LogChunk`'s parent key (for those from a `Task`) should be the `Checklist` key. Instead, they were being set as the `Task` key.
