### ISSUE TITLE
FocusNode change notifier not called when focused TextField is removed

### ISSUE THREAD

**Issue by krisgiesing** [flutter/flutter#47458]
The following test will fail the final expect:

```
import 'package:flutter/material.dart';
import 'package:flutter_test/flutter_test.dart';

Widget buildApp(Widget body) {
  return MaterialApp(
    home: Scaffold(
      body: body,
    ),
  );
}

TextField buildTextField(FocusNode focus) {
  return TextField(
    focusNode: focus,
    autofocus: true,
  );
}

main() {
  testWidgets('Focus node dispose', (WidgetTester tester) async {
    final FocusNode focus = FocusNode();
    bool isFocused = focus.hasFocus;
    final VoidCallback focusChanged = () => isFocused = focus.hasFocus;
    focus.addListener(focusChanged);
    expect(isFocused, isFalse);

    await tester.pumpWidget(buildApp(buildTextField(focus)));
    expect(focus.hasFocus, isTrue);
    expect(isFocused, isTrue);

    await tester.pumpWidget(buildApp(Text('No focus')));
    expect(focus.hasFocus, isFalse);
    expect(isFocused, isFalse);
  });
}
```

I believe this violates the contract established by FocusNode's ChangeNotifier interface, since clearly the FocusNode no longer has focus after its TextField is removed.

In our app we expect the change notifier to be called so that we can manage the focus change cleanly. Without this, we need to manage the focus change by chasing down every logic path that can cause the app to rebuild without the text field, which leads to error-prone duplication of code.

**Comment by gspencergoog** [comment]
This is because if the focus system notified listeners of a focus change after a focus node was no longer in the widget tree, it would often end up calling `setState` on widgets that were unmounted.

I agree that it's not ideal.  Ideally, we'd be able to notify about focus changes synchronously, but that has its own problems: if a node is then simply moved from one place in the tree to another, it would notify about losing and gaining focus, even when it didn't technically do either. Sending focus changes between frames solves this problem, but creates the one you mention above.

**Comment by krisgiesing** [comment]
I would propose an API change wherein the focus change notification includes a reason for the focus change. This reason can specify that focus was lost because the node was unmounted. Client code can then deal with the focus change appropriately, including avoiding a setState() call on an unmounted node.

I can think of a few different ways this API change could be done with a soft migration, if the general approach is approved.

**Comment by gspencergoog** [comment]
I think in general that it is a good proposal.

**Comment by TahaTesser** [comment]
<details> 
<summary>logs</summary> 

``` 
00:08 +0: Focus node dispose                                                                                     
══╡ EXCEPTION CAUGHT BY FLUTTER TEST FRAMEWORK ╞════════════════════════════════════════════════════
The following TestFailure object was thrown running a test:
  Expected: false
  Actual: <true>

When the exception was thrown, this was the stack:
#4      main.<anonymous closure> (file:///Users/taha/AndroidStudioProjects/dev_flutter/test/widget_test.dart:64:5)
<asynchronous suspension>
#5      main.<anonymous closure> (file:///Users/taha/AndroidStudioProjects/dev_flutter/test/widget_test.dart)
#6      testWidgets.<anonymous closure>.<anonymous closure> (package:flutter_test/src/widget_tester.dart:144:29)
<asynchronous suspension>
#7      testWidgets.<anonymous closure>.<anonymous closure> (package:flutter_test/src/widget_tester.dart)
#8      TestWidgetsFlutterBinding._runTestBody (package:flutter_test/src/binding.dart:744:19)
<asynchronous suspension>
#11     TestWidgetsFlutterBinding._runTest (package:flutter_test/src/binding.dart:724:14)
#12     AutomatedTestWidgetsFlutterBinding.runTest.<anonymous closure> (package:flutter_test/src/binding.dart:1124:24)
#13     FakeAsync.run.<anonymous closure>.<anonymous closure> (package:fake_async/fake_async.dart:177:54)
#18     withClock (package:clock/src/default.dart:46:10)
#19     FakeAsync.run.<anonymous closure> (package:fake_async/fake_async.dart:177:22)
#24     FakeAsync.run (package:fake_async/fake_async.dart:177:7)
#25     AutomatedTestWidgetsFlutterBinding.runTest (package:flutter_test/src/binding.dart:1121:15)
#26     testWidgets.<anonymous closure> (package:flutter_test/src/widget_tester.dart:137:24)
#27     Declarer.test.<anonymous closure>.<anonymous closure> (package:test_api/src/backend/declarer.dart:171:19)
<asynchronous suspension>
#28     Declarer.test.<anonymous closure>.<anonymous closure> (package:test_api/src/backend/declarer.dart)
#33     Declarer.test.<anonymous closure> (package:test_api/src/backend/declarer.dart:169:13)
#34     Invoker.waitForOutstandingCallbacks.<anonymous closure> (package:test_api/src/backend/invoker.dart:235:15)
#39     Invoker.waitForOutstandingCallbacks (package:test_api/src/backend/invoker.dart:232:5)
#40     Invoker._onRun.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:test_api/src/backend/invoker.dart:388:17)
<asynchronous suspension>
#41     Invoker._onRun.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:test_api/src/backend/invoker.dart)
#46     Invoker._onRun.<anonymous closure>.<anonymous closure> (package:test_api/src/backend/invoker.dart:374:9)
#47     Invoker._guardIfGuarded (package:test_api/src/backend/invoker.dart:420:15)
#48     Invoker._onRun.<anonymous closure> (package:test_api/src/backend/invoker.dart:373:7)
#55     Invoker._onRun (package:test_api/src/backend/invoker.dart:372:11)
#56     LiveTestController.run (package:test_api/src/backend/live_test_controller.dart:152:11)
#57     RemoteListener._runLiveTest.<anonymous closure> (package:test_api/src/remote_listener.dart:259:16)
#62     RemoteListener._runLiveTest (package:test_api/src/remote_listener.dart:258:5)
#63     RemoteListener._serializeTest.<anonymous closure> (package:test_api/src/remote_listener.dart:211:7)
#81     _GuaranteeSink.add (package:stream_channel/src/guarantee_channel.dart:124:12)
#82     new _MultiChannel.<anonymous closure> (package:stream_channel/src/multi_channel.dart:159:31)
#116    new _WebSocketImpl._fromSocket.<anonymous closure> (dart:_http/websocket_impl.dart:1145:21)
#124    _WebSocketProtocolTransformer._messageFrameEnd (dart:_http/websocket_impl.dart:338:23)
#125    _WebSocketProtocolTransformer.add (dart:_http/websocket_impl.dart:232:46)
#135    _Socket._onData (dart:io-patch/socket_patch.dart:2020:41)
#144    new _RawSocket.<anonymous closure> (dart:io-patch/socket_patch.dart:1556:33)
#145    _NativeSocket.issueReadEvent.issue (dart:io-patch/socket_patch.dart:1052:14)
(elided 108 frames from dart:async and package:stack_trace)

This was caught by the test expectation on the following line:
  file:///Users/taha/AndroidStudioProjects/dev_flutter/test/widget_test.dart line 64
The test description was:
  Focus node dispose
════════════════════════════════════════════════════════════════════════════════════════════════════
00:08 +0 -1: Focus node dispose [E]                                                                              
  Test failed. See exception logs above.
  The test description was: Focus node dispose
  
00:08 +0 -1: Some tests failed.      
``` 

</details> 

<details> 
<summary>flutter doctor -v</summary> 

```
[✓] Flutter (Channel dev, 1.20.0-3.0.pre, on Mac OS X 10.15.5 19F101, locale
    en-GB)
    • Flutter version 1.20.0-3.0.pre at /Users/taha/Code/flutter_dev
    • Framework revision 0af027f805 (5 days ago), 2020-07-04 12:19:20 -0700
    • Engine revision a751393804
    • Dart version 2.9.0 (build 2.9.0-20.0.dev 22da8934ac)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
    • Android SDK at /Users/taha/Code/sdk
    • Platform android-30, build-tools 30.0.0
    • ANDROID_HOME = /Users/taha/Code/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.5, Build version 11E608c
    • CocoaPods version 1.9.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 47.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.46.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.12.1

[✓] Connected device (4 available)
    • SM M305F (mobile)      • 32003c30dc19668f          • android-arm64  •
      Android 10 (API 29)
    • Taha’s iPhone (mobile) • 00008020-001059882212002E • ios            • iOS
      13.5.1
    • Web Server (web)       • web-server                • web-javascript •
      Flutter Tools
    • Chrome (web)           • chrome                    • web-javascript •
      Google Chrome 83.0.4103.116

• No issues found!
``` 

</details>
