### ISSUE TITLE
ProcessException

### ISSUE THREAD

**Issue by imrudra09** [flutter/flutter#47463]
Launching lib\main.dart on Redmi 5 in debug mode...
Initializing gradle...
Finished with error: ProcessException: Process "C:\Users\SHIVA\statelesswidget\android\gradlew.bat" exited abnormally:
Exception in thread "main" java.lang.RuntimeException: Timeout of 120000 reached waiting for exclusive access to file: C:\Users\SHIVA\.gradle\wrapper\dists\gradle-4.10.2-all\9fahxiiecdb76a5g3aw9oi8rv\gradle-4.10.2-all.zip
	at org.gradle.wrapper.ExclusiveFileAccessManager.access(ExclusiveFileAccessManager.java:61)
	at org.gradle.wrapper.Install.createDist(Install.java:48)
	at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:128)
	at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:61)
  Command: C:\Users\SHIVA\statelesswidget\android\gradlew.bat -v

**Comment by janmoppel** [comment]
Hello @imrudra09 !

Thank you for posting an issue.
This problem has been already reported here: #34210

Therefore, closing this thread for now. You can follow the discussion in the mentioned ticket.
