### ISSUE TITLE
!_debugLocked': is not true. on hot reload

### ISSUE THREAD

**Issue by jrutley** [flutter/flutter#47504]
## The Problem

Once this error occurs, you have to stop the app before performing any more hot reloads:
![image](https://user-images.githubusercontent.com/771365/71230349-504ffb80-22b7-11ea-9aaa-899f9f27f125.png)

## Steps to Reproduce

I've been going through the Flutter tutorial at this point (https://codelabs.developers.google.com/codelabs/first-flutter-app-pt2/#5)

Dart file here: [Rename to main.dart](https://github.com/flutter/flutter/files/3986722/main.dart.txt)

1. Run main.dart using either Android emulator or iOS emulator
2. Verify that it's working
3. Uncomment lines 71-82
4. Save file (hot reload)
5. Observe that the code fails. (I don't yet know why this doesn't work, but I digress)
6. Comment lines 71-82
7. Save file

**Target Platform: Android and iOS**
**Target OS version/browser: Android API 29 x86**
**Devices: Nexus 5X emulator, iPhone 11 Pro Max emulator**

## Logs

Sorry it's not verbose, but it looks like it's related to hot reload.

```Initializing hot reload...
Syncing files to device Android SDK built for x86...

════════ Exception caught by widgets library ═══════════════════════════════════════════════════════
The following assertion was thrown building Navigator-[GlobalObjectKey<NavigatorState> _WidgetsAppState#5e8f2](dirty, state: NavigatorState#90e6e(tickers: tracking 2 tickers)):
'package:flutter/src/widgets/navigator.dart': Failed assertion: line 2330 pos 12: '!_debugLocked': is not true.


Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=BUG.md

The relevant error-causing widget was: 
  MaterialApp file:///Users/jeramy/Projects/flutter/car_games/lib/main.dart:10:12
When the exception was thrown, this was the stack: 
#2      NavigatorState.build (package:flutter/src/widgets/navigator.dart:2330:12)
#3      StatefulElement.build (package:flutter/src/widgets/framework.dart:4334:27)
#4      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4223:15)
#5      Element.rebuild (package:flutter/src/widgets/framework.dart:3947:5)
#6      StatefulElement.update (package:flutter/src/widgets/framework.dart:4413:5)
...
════════════════════════════════════════════════════════════════════════════════════════════════════
Reloaded 1 of 531 libraries in 2,062ms.
```

```
```

```
jeramy@Jeramys-MacBook-Pro car_games $ flutter analyze
Analyzing car_games...                                                  
No issues found! (ran in 4.4s)
```

```
[✓] Flutter (Channel stable, v1.12.13+hotfix.5, on Mac OS X 10.14.6 18G87, locale en-CA)
    • Flutter version 1.12.13+hotfix.5 at /Users/jeramy/flutter
    • Framework revision 27321ebbad (9 days ago), 2019-12-10 18:15:01 -0800
    • Engine revision 2994f7e1e6
    • Dart version 2.7.0

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/jeramy/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • ANDROID_HOME = /Users/jeramy/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.3, Build version 11C29
    • CocoaPods version 1.8.4

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 42.1.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] VS Code (version 1.40.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.7.1

[✓] Connected device (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 9 (API 28) (emulator)

• No issues found!```

**Comment by alishashaw439** [comment]
This is the changed part of code in main.dart file 
------------
import 'package:flutter/material.dart';
import 'package:english_words/english_words.dart';
import 'second_page.dart';


  @override
  Widget build(BuildContext context) {
    return Scaffold(
        appBar: AppBar(
          title: Text('My WTF list scroller'),
          actions: <Widget>[
            IconButton(
              icon: Icon(Icons.list),
              onPressed: () {
                _pushSaved();
              },
            )
          ],
        ),
        body: _buildSuggestions());
  }

  _pushSaved() {
    Navigator.push(
      context,
      MaterialPageRoute(builder: (context) {
        return SecondPage();
      }),
    );
  }
}

----------
This is the dart file I have created for second_page
---------
import 'package:flutter/material.dart';

class SecondPage extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('Second page'),
      ),
      body: Text('This is text'),
    );
  }
}
----------------

**Comment by alishashaw439** [comment]
Hey! I tried to solve your issue and here is the working code. I have made the following changes:
>You were missing the bracket in onPressed() button.
>Few changes in _pushSaved() function. 
--------------------------

@override
  Widget build(BuildContext context) {
    return Scaffold(
        appBar: AppBar(
          title: Text('My WTF list scroller'),
          actions: <Widget>[
            IconButton(
              icon: Icon(Icons.list),
              onPressed: () {
                _pushSaved();
              },
            )
          ],
        ),
        body: _buildSuggestions());
  }

  _pushSaved() {
    Navigator.push(
      context,
      MaterialPageRoute(builder: (context) {
        return Scaffold(
          appBar: AppBar(
            title: Text('Second page'),
          ),
          body: Text('This is text'),
        );
      }),
    );
  }
}
----------------------------------

**Comment by alishashaw439** [comment]
> Hey! I tried to solve your issue and here is the working code. I have made the following changes:
> 
> 1. You were missing the bracket in onPressed() button.
>  2.Few changes in _pushSaved() function.
> 
> > 
> 
> @override
> Widget build(BuildContext context) {
> return Scaffold(
> appBar: AppBar(
> title: Text('My WTF list scroller'),
> actions: [
> IconButton(
> icon: Icon(Icons.list),
> onPressed: () {
> _pushSaved();
> },
> )
> ],
> ),
> body: _buildSuggestions());
> }
> 
> > 
> 
> ## _pushSaved() {
> Navigator.push(
> context,
> MaterialPageRoute(builder: (context) {
> return Scaffold(
> appBar: AppBar(
> title: Text('Second page'),
> ),
> body: Text('This is text'),
> );
> }),
> );
> }
> }

**Comment by jrutley** [comment]
@alishashaw439 yes that fixed my problem. Thank you!

@iapicca I'm confused why this is marked as documentation. This is almost a deal breaking bug for me.  

As a beginner, I'm prone to making mistakes while trying to use Flutter, and if I'm forced to stop and reload every time I cause the app to fall into a bad state, it ceases to be fun. On my slow MacBook, it's a 60 second turnaround time instead of 5.

**Comment by iapicca** [comment]
Hi @jrutley 
the goal of this platform is **not** to provide assistance on personal code,
but rather improve the quality of flutter with contribution, proposal, bug fixing and
in your case pointing out a difficulty that a developer might experience
following flutter's codelabs.

Thank you @alishashaw439 for fixing the problem within the code.

I'd like to keep the issue open for now
until codelabs material get reviewed.

Thank you for your contribution @jrutley

**Comment by jrutley** [comment]
I was not directly looking for a solution to my code error, though I got
one.

The reason I logged the bug is because the hot reload became unusable after
reverting the code to a known, good state

**Comment by kf6gpe** [comment]
I'm moving this over to the samples repository. I don't think this is a widespread issue, but it's worth keeping track of.
