### ISSUE TITLE
 flutter run : Error generating build_script snapshot

### ISSUE THREAD

**Issue by kinmoLun** [flutter/flutter#47507]
## Steps to Reproduce

1. flutter run
2. generating build script...                                          3.5s
3. Error generating build_script snapshot: Could not find a file named "pubspec.yaml" in
"/Users/xxx/.pub-cache/hosted/pub.flutter-io.cn/analyzer-0.38.5".

**Target Platform:**
**Target OS version/browser:**
**Devices:**

## Logs

```
[  +17 ms] executing: [/Users/kimz/flutter/] git -c log.showSignature=false log
-n 1 --pretty=format:%H
[  +60 ms] Exit code 0 from: git -c log.showSignature=false log -n 1
--pretty=format:%H
[   +1 ms] 27321ebbad34b0a3fafe99fac037102196d655ff
[        ] executing: [/Users/kimz/flutter/] git describe --match v*.*.*
--first-parent --long --tags
[  +22 ms] Exit code 0 from: git describe --match v*.*.* --first-parent --long
--tags
[        ] v1.12.13+hotfix.5-0-g27321ebba
[  +10 ms] executing: [/Users/kimz/flutter/] git rev-parse --abbrev-ref
--symbolic @{u}
[  +18 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/stable
[        ] executing: [/Users/kimz/flutter/] git ls-remote --get-url origin
[  +14 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[  +75 ms] executing: [/Users/kimz/flutter/] git rev-parse --abbrev-ref HEAD
[  +15 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] stable
[   +9 ms] executing: sw_vers -productName
[  +27 ms] Exit code 0 from: sw_vers -productName
[        ] Mac OS X
[        ] executing: sw_vers -productVersion
[  +21 ms] Exit code 0 from: sw_vers -productVersion
[        ] 10.15.2
[        ] executing: sw_vers -buildVersion
[  +20 ms] Exit code 0 from: sw_vers -buildVersion
[   +1 ms] 19C57
[  +44 ms] "flutter run" took 134ms.
Error: No pubspec.yaml file found.
This command should be run from the root of your Flutter project.
Do not run this command from the root of your git clone of Flutter.

#0      FlutterCommand.validateCommand
(package:flutter_tools/src/runner/flutter_command.dart:690:9)
#1      RunCommand.validateCommand
(package:flutter_tools/src/commands/run.dart:285:19)
#2      FlutterCommand.verifyThenRunCommand
(package:flutter_tools/src/runner/flutter_command.dart:590:11)
#3      FlutterCommand.run.<anonymous closure>
(package:flutter_tools/src/runner/flutter_command.dart:515:33)
<asynchronous suspension>
#4      AppContext.run.<anonymous closure>
(package:flutter_tools/src/base/context.dart:146:29)
#5      _rootRun (dart:async/zone.dart:1126:13)
#6      _CustomZone.run (dart:async/zone.dart:1023:19)
#7      _runZoned (dart:async/zone.dart:1518:10)
#8      runZoned (dart:async/zone.dart:1465:12)
#9      AppContext.run (package:flutter_tools/src/base/context.dart:145:18)
#10     FlutterCommand.run
(package:flutter_tools/src/runner/flutter_command.dart:505:20)
#11     CommandRunner.runCommand (package:args/command_runner.dart:197:27)
#12     FlutterCommandRunner.runCommand.<anonymous closure>
(package:flutter_tools/src/runner/flutter_command_runner.dart:413:21)
<asynchronous suspension>
#13     AppContext.run.<anonymous closure>
(package:flutter_tools/src/base/context.dart:146:29)
#14     _rootRun (dart:async/zone.dart:1126:13)
#15     _CustomZone.run (dart:async/zone.dart:1023:19)
#16     _runZoned (dart:async/zone.dart:1518:10)
#17     runZoned (dart:async/zone.dart:1465:12)
#18     AppContext.run (package:flutter_tools/src/base/context.dart:145:18)
#19     FlutterCommandRunner.runCommand
(package:flutter_tools/src/runner/flutter_command_runner.dart:364:19)
#20     CommandRunner.run.<anonymous closure>
(package:args/command_runner.dart:112:25)
#21     new Future.sync (dart:async/future.dart:224:31)
#22     CommandRunner.run (package:args/command_runner.dart:112:14)
#23     FlutterCommandRunner.run
(package:flutter_tools/src/runner/flutter_command_runner.dart:250:18)
#24     run.<anonymous closure>.<anonymous closure>
(package:flutter_tools/runner.dart:63:22)
#25     _rootRun (dart:async/zone.dart:1126:13)
#26     _CustomZone.run (dart:async/zone.dart:1023:19)
#27     _runZoned (dart:async/zone.dart:1518:10)
#28     runZoned (dart:async/zone.dart:1502:12)
#29     run.<anonymous closure> (package:flutter_tools/runner.dart:61:18)
<asynchronous suspension>
#30     AppContext.run.<anonymous closure>
(package:flutter_tools/src/base/context.dart:146:29)
#31     _rootRun (dart:async/zone.dart:1126:13)
#32     _CustomZone.run (dart:async/zone.dart:1023:19)
#33     _runZoned (dart:async/zone.dart:1518:10)
#34     runZoned (dart:async/zone.dart:1465:12)
#35     AppContext.run (package:flutter_tools/src/base/context.dart:145:18)
#36     runInContext (package:flutter_tools/src/context_runner.dart:64:24)
#37     run (package:flutter_tools/runner.dart:50:10)
#38     main (package:flutter_tools/executable.dart:65:9)
#39     main
(file:///Users/kimz/flutter/packages/flutter_tools/bin/flutter_tools.dart:8:3)
#40     _startIsolate.<anonymous closure>
(dart:isolate-patch/isolate_patch.dart:305:32)
#41     _RawReceivePortImpl._handleMessage
(dart:isolate-patch/isolate_patch.dart:174:12)
```

```
```

```
[✓] Flutter (Channel stable, v1.12.13+hotfix.5, on Mac OS X 10.15.2 19C57,
    locale zh-Hans-CN)
    • Flutter version 1.12.13+hotfix.5 at /Users/kimz/flutter
    • Framework revision 27321ebbad (9 days ago), 2019-12-10 18:15:01 -0800
    • Engine revision 2994f7e1e6
    • Dart version 2.7.0

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/kimz/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling
      support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.3, Build version 11C29
    • CocoaPods version 1.8.4

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 42.1.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build
      1.8.0_202-release-1483-b49-5587405)

[✓] VS Code (version 1.41.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.7.1

[✓] Connected device (1 available)
    • V1732T • N7WWVGGE6HDQB68P • android-arm64 • Android 8.1.0 (API 27)

• No issues found!
```

**Comment by iapicca** [comment]
Hi @kinmoLun 
I see there's an open [issue](https://github.com/flutter/flutter/issues/47505) addressing the case you described.
Please follow up on that issue,
I'm closing the current one as duplicate.
If you disagree please write in the comments
and I will reopen it.
Thank you

**Comment by jmagman** [comment]
Re-opening, the other issue is on `flutter create` which should create the pubspec.yaml.

What directory are you in when you call `flutter run`?  From the message is looks like you're in /Users/xxx/.pub-cache/hosted/pub.flutter-io.cn/analyzer-0.38.5, which isn't a flutter app...

**Comment by kinmoLun** [comment]
> Hi @kinmoLun
> I see there's an open [issue](https://github.com/flutter/flutter/issues/47505) addressing the case you described.
> Please follow up on that issue,
> I'm closing the current one as duplicate.
> If you disagree please write in the comments
> and I will reopen it.
> Thank you

This does not solve my problem

**Comment by kinmoLun** [comment]
> Re-opening, the other issue is on `flutter create` which should create the pubspec.yaml.
> 
> What directory are you in when you call `flutter run`? From the message is looks like you're in /Users/xxx/.pub-cache/hosted/pub.flutter-io.cn/analyzer-0.38.5, which isn't a flutter app...

I execute flutter run in the root directory of the project

**Comment by jmagman** [comment]
Re-reading again, the analyzer-0.38.5 is missing its pubspec.yaml.  What is in that directory?
```
ls -la /Users/xxx/.pub-cache/hosted/pub.flutter-io.cn/analyzer-0.38.5
```

**Comment by dnfield** [comment]
I'm closing this since it's had no activity for > 21 days and has the waiting label.  I believe the bot is just backlogged and missing a bunch of these.  Please feel free to add more details if you want this re-opened.

**Comment by kollesnica-power** [comment]
For those who faced this error:
In my case this happened after upgrading .pub-cache from **v1.9.1+hotfix.6** to **v1.12.13+hotfix.5**. So I just deleted **flutter** directory with **.pub-cache** and installed again. Looks like after upgrade, flutter looked for a wrong **.pub-cache** directory.

**Comment by sghael** [comment]
For those still fighting this issue, the symlink solution suggested here is the only thing that worked for me https://github.com/fluttercommunity/flutter_launcher_icons/issues/50

**Comment by jmagman** [comment]
@sghael You're saying you had to symlink `.../flutter/.pub-cache` to `~/.pub-cache`?  How did you set up your pub cache?  https://dart.dev/tools/pub/cmd/pub-get#the-system-package-cache
What's your `PUB_CACHE` environment variable? https://dart.dev/tools/pub/environment-variables
