### ISSUE TITLE
"Exception caught by rendering library: The relevant error-causing widget was: Theme." Flutter issue when I called showTimePicker() in IOS build

### ISSUE THREAD

**Issue by avldabade** [flutter/flutter#47516]
### My flutter --version

```console
Flutter 1.12.13+hotfix.5 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 27321ebbad (9 days ago) • 2019-12-10 18:15:01 -0800
Engine • revision 2994f7e1e6
Tools • Dart 2.7.0
```

### Source Code:
```dart
Future<Null> selectTime(BuildContext context, String startOrEnd) async {
    final TimeOfDay picked = await showTimePicker(
      context: context,
      initialTime: selectedTime,
      builder: (context, child) {
        return FittedBox(
          child: Theme(
            child: child,
            data: ThemeData(
              primaryColor: const Color(0xff1c4598),
              accentColor: const Color(0xff2761d6),
              // Define the default Font Family
              fontFamily: 'Ebrima',
            ),
          ),
        );
      },
    );
    if (picked != null) {
      var timeSelectedArr = picked.toString().split('('); //TimeOfDay(15:43)
      var timeSelected1 = timeSelectedArr[1].toString().split(')');
      timeSelected = timeSelected1[0] + ':00';
      //String formattedDate = DateFormat('yyyy-MM-dd – kk:mm').format(picked);
    } else {
      timeSelected = '00:00:00';
    }
    print('timeSelected:::::>  $timeSelected ');
    setState(() {
      if (startOrEnd == 'start') {
        startDateTime = startDateTime + ' ' + timeSelected;
        print('After selection startDateTime: $startDateTime');
      } else {
        endDateTime = endDateTime + ' ' + timeSelected;
        print('After selection startDateTime: $startDateTime');
      }
      print(
          'timeSelected below:::::>  $timeSelected \nstartDateTime: $startDateTime \n endDateTime: $endDateTime');
      //popBottomSheet();
    });
  }
```

### **Error:**
<details>
  <summary>error</summary>

```bash
════════ Exception caught by rendering library ═════════════════════════════════════════════════════
The following NoSuchMethodError was thrown during performLayout():
The method 'copyWith' was called on null.
Receiver: null
Tried calling: copyWith(maxWidth: Infinity)

The relevant error-causing widget was: 
  Theme file:///Users/apurva/Documents/Apurva%20Dabade/demo_app/lib/screens/pole_reports_page_new.dart:915:20
When the exception was thrown, this was the stack: 
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:53:5)
#1      _RenderButtonBarRow.constraints (package:flutter/src/material/button_bar.dart:292:30)
#2      RenderObject.debugFillProperties (package:flutter/src/rendering/object.dart:2791:68)
#3      RenderBox.debugFillProperties (package:flutter/src/rendering/box.dart:2417:11)
#4      RenderFlex.debugFillProperties (package:flutter/src/rendering/flex.dart:1015:11)
...
The following RenderObject was being processed when the exception was fired: _RenderInkFeatures#60fd9 relayoutBoundary=up6 NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
...  parentData: <none> (can use size)
...  constraints: BoxConstraints(280.0<=w<=Infinity, 0.0<=h<=Infinity)
...  size: MISSING
RenderObject: _RenderInkFeatures#60fd9 relayoutBoundary=up6 NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
  parentData: <none> (can use size)
  constraints: BoxConstraints(280.0<=w<=Infinity, 0.0<=h<=Infinity)
  size: MISSING
...  child: _RenderLayoutBuilder#0fa3d relayoutBoundary=up7 NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
...    parentData: <none> (can use size)
...    constraints: BoxConstraints(280.0<=w<=Infinity, 0.0<=h<=Infinity)
...    size: MISSING
...    child: RenderDecoratedBox#34502 relayoutBoundary=up8 NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
...      parentData: offset=Offset(0.0, 0.0) (can use size)
...      constraints: BoxConstraints(280.0<=w<=Infinity, 0.0<=h<=Infinity)
...      size: MISSING
...      decoration: BoxDecoration
...        color: Color(0xffffffff)
...      configuration: ImageConfiguration(bundle: PlatformAssetBundle#7fe33(), devicePixelRatio: 2.0, locale: en_US, textDirection: TextDirection.ltr, platform: iOS)
...      child: RenderFlex#57a71 relayoutBoundary=up9 NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
...        parentData: <none> (can use size)
...        constraints: BoxConstraints(280.0<=w<=Infinity, 0.0<=h<=Infinity)
...        size: MISSING
...        direction: vertical
...        mainAxisAlignment: start
...        mainAxisSize: min
...        crossAxisAlignment: stretch
...        verticalDirection: down
...        child 1: RenderDecoratedBox#4f3bd NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
...          parentData: offset=Offset(0.0, 0.0); flex=null; fit=null
...          constraints: MISSING
...          size: MISSING
...          decoration: BoxDecoration
...            color: Color(0xff1c4598)
...          configuration: ImageConfiguration(bundle: PlatformAssetBundle#7fe33(), devicePixelRatio: 2.0, locale: en_US, textDirection: TextDirection.ltr, platform: iOS)
...        child 2: RenderConstrainedBox#5a8fe NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
...          parentData: offset=Offset(0.0, 0.0); flex=1; fit=FlexFit.loose
...          constraints: MISSING
...          size: MISSING
...          additionalConstraints: BoxConstraints(0.0<=w<=Infinity, h=336.0)
...        child 3: RenderPadding#a773d NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
...          parentData: offset=Offset(0.0, 0.0); flex=null; fit=null
...          constraints: MISSING
...          size: MISSING
...          padding: EdgeInsets(4.0, 8.0, 4.0, 8.0)
...          textDirection: ltr
════════════════════════════════════════════════════════════════════════════════════════════════════

════════ (2) Exception caught by rendering library ═════════════════════════════════════════════════
RenderBox was not laid out: _RenderInkFeatures#60fd9 relayoutBoundary=up6 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
'package:flutter/src/rendering/box.dart':
Failed assertion: line 1687 pos 12: 'hasSize'
The relevant error-causing widget was: 
  Theme file:///Users/apurva/Documents/Apurva%20Dabade/demo_app/lib/screens/pole_reports_page_new.dart:915:20
════════════════════════════════════════════════════════════════════════════════════════════════════

════════ (3) Exception caught by rendering library ═════════════════════════════════════════════════
RenderBox was not laid out: RenderCustomPaint#c3ea7 relayoutBoundary=up5 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
'package:flutter/src/rendering/box.dart':
Failed assertion: line 1687 pos 12: 'hasSize'
The relevant error-causing widget was: 
  Theme file:///Users/apurva/Documents/Apurva%20Dabade/demo_app/lib/screens/pole_reports_page_new.dart:915:20
════════════════════════════════════════════════════════════════════════════════════════════════════

════════ (4) Exception caught by rendering library ═════════════════════════════════════════════════
RenderBox was not laid out: RenderPhysicalShape#8803d relayoutBoundary=up4 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
'package:flutter/src/rendering/box.dart':
Failed assertion: line 1687 pos 12: 'hasSize'
The relevant error-causing widget was: 
  Theme file:///Users/apurva/Documents/Apurva%20Dabade/demo_app/lib/screens/pole_reports_page_new.dart:915:20
════════════════════════════════════════════════════════════════════════════════════════════════════

════════ (5) Exception caught by rendering library ═════════════════════════════════════════════════
RenderBox was not laid out: RenderConstrainedBox#35310 relayoutBoundary=up3 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
'package:flutter/src/rendering/box.dart':
Failed assertion: line 1687 pos 12: 'hasSize'
The relevant error-causing widget was: 
  Theme file:///Users/apurva/Documents/Apurva%20Dabade/demo_app/lib/screens/pole_reports_page_new.dart:915:20
════════════════════════════════════════════════════════════════════════════════════════════════════

════════ (6) Exception caught by rendering library ═════════════════════════════════════════════════
RenderBox was not laid out: RenderPositionedBox#4d0f8 relayoutBoundary=up2 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
'package:flutter/src/rendering/box.dart':
Failed assertion: line 1687 pos 12: 'hasSize'
The relevant error-causing widget was: 
  Theme file:///Users/apurva/Documents/Apurva%20Dabade/demo_app/lib/screens/pole_reports_page_new.dart:915:20
════════════════════════════════════════════════════════════════════════════════════════════════════

════════ (7) Exception caught by rendering library ═════════════════════════════════════════════════
RenderBox was not laid out: RenderPadding#d9a4d relayoutBoundary=up1 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
'package:flutter/src/rendering/box.dart':
Failed assertion: line 1687 pos 12: 'hasSize'
The relevant error-causing widget was: 
  FittedBox file:///Users/apurva/Documents/Apurva%20Dabade/demo_app/lib/screens/pole_reports_page_new.dart:914:16
════════════════════════════════════════════════════════════════════════════════════════════════════

════════ (8) Exception caught by rendering library ═════════════════════════════════════════════════
RenderBox was not laid out: RenderFittedBox#a4dad NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
'package:flutter/src/rendering/box.dart':
Failed assertion: line 1687 pos 12: 'hasSize'
The relevant error-causing widget was: 
  MaterialApp file:///Users/apurva/Documents/Apurva%20Dabade/demo_app/lib/main.dart:32:10
════════════════════════════════════════════════════════════════════════════════════════════════════

════════ (9) Exception caught by rendering library ═════════════════════════════════════════════════
RenderBox was not laid out: RenderPadding#4f87a NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
'package:flutter/src/rendering/box.dart':
Failed assertion: line 1687 pos 12: 'hasSize'
The relevant error-causing widget was: 
  MaterialApp file:///Users/apurva/Documents/Apurva%20Dabade/demo_app/lib/main.dart:32:10
════════════════════════════════════════════════════════════════════════════════════════════════════

════════ (10) Exception caught by rendering library ════════════════════════════════════════════════
RenderBox was not laid out: RenderSemanticsAnnotations#b48fb NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
'package:flutter/src/rendering/box.dart':
Failed assertion: line 1687 pos 12: 'hasSize'
The relevant error-causing widget was: 
  MaterialApp file:///Users/apurva/Documents/Apurva%20Dabade/demo_app/lib/main.dart:32:10
════════════════════════════════════════════════════════════════════════════════════════════════════

════════ (11) Exception caught by rendering library ════════════════════════════════════════════════
RenderBox was not laid out: RenderRepaintBoundary#420e8 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
'package:flutter/src/rendering/box.dart':
Failed assertion: line 1687 pos 12: 'hasSize'
The relevant error-causing widget was: 
  MaterialApp file:///Users/apurva/Documents/Apurva%20Dabade/demo_app/lib/main.dart:32:10
════════════════════════════════════════════════════════════════════════════════════════════════════

════════ (12) Exception caught by rendering library ════════════════════════════════════════════════
RenderBox was not laid out: RenderIgnorePointer#bb270 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
'package:flutter/src/rendering/box.dart':
Failed assertion: line 1687 pos 12: 'hasSize'
The relevant error-causing widget was: 
  MaterialApp file:///Users/apurva/Documents/Apurva%20Dabade/demo_app/lib/main.dart:32:10
════════════════════════════════════════════════════════════════════════════════════════════════════

════════ (13) Exception caught by rendering library ════════════════════════════════════════════════
RenderBox was not laid out: RenderAnimatedOpacity#42828 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
'package:flutter/src/rendering/box.dart':
Failed assertion: line 1687 pos 12: 'hasSize'
The relevant error-causing widget was: 
  MaterialApp file:///Users/apurva/Documents/Apurva%20Dabade/demo_app/lib/main.dart:32:10
════════════════════════════════════════════════════════════════════════════════════════════════════

════════ (14) Exception caught by rendering library ════════════════════════════════════════════════
RenderBox was not laid out: RenderRepaintBoundary#91c7a NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
'package:flutter/src/rendering/box.dart':
Failed assertion: line 1687 pos 12: 'hasSize'
The relevant error-causing widget was: 
  MaterialApp file:///Users/apurva/Documents/Apurva%20Dabade/demo_app/lib/main.dart:32:10
════════════════════════════════════════════════════════════════════════════════════════════════════

════════ (15) Exception caught by rendering library ════════════════════════════════════════════════
RenderBox was not laid out: RenderSemanticsAnnotations#6c535 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
'package:flutter/src/rendering/box.dart':
Failed assertion: line 1687 pos 12: 'hasSize'
The relevant error-causing widget was: 
  MaterialApp file:///Users/apurva/Documents/Apurva%20Dabade/demo_app/lib/main.dart:32:10
════════════════════════════════════════════════════════════════════════════════════════════════════

════════ (16) Exception caught by rendering library ════════════════════════════════════════════════
RenderBox was not laid out: RenderOffstage#96571 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
'package:flutter/src/rendering/box.dart':
Failed assertion: line 1687 pos 12: 'hasSize'
The relevant error-causing widget was: 
  MaterialApp file:///Users/apurva/Documents/Apurva%20Dabade/demo_app/lib/main.dart:32:10
════════════════════════════════════════════════════════════════════════════════════════════════════

════════ (17) Exception caught by rendering library ════════════════════════════════════════════════
RenderBox was not laid out: RenderRepaintBoundary#91c7a NEEDS-PAINT
'package:flutter/src/rendering/box.dart':
Failed assertion: line 1687 pos 12: 'hasSize'
The relevant error-causing widget was: 
  MaterialApp file:///Users/apurva/Documents/Apurva%20Dabade/demo_app/lib/main.dart:32:10
════════════════════════════════════════════════════════════════════════════════════════════════════

════════ (18) Exception caught by rendering library ════════════════════════════════════════════════
RenderBox was not laid out: RenderRepaintBoundary#91c7a NEEDS-PAINT
'package:flutter/src/rendering/box.dart':
Failed assertion: line 1687 pos 12: 'hasSize'
The relevant error-causing widget was: 
  MaterialApp file:///Users/apurva/Documents/Apurva%20Dabade/SPMS%20Project/demo_app/lib/main.dart:32:10
════════════════════════════════════════════════════════════════════════════════════════════════════

════════ (19) Exception caught by Flutter framework ════════════════════════════════════════════════
The method 'copyWith' was called on null.
Receiver: null
Tried calling: copyWith(maxWidth: Infinity)
```

</details>

**Comment by HansMuller** [comment]
CC @darrenaustin

**Comment by darrenaustin** [comment]
This might be related to some work that Shi Hao was doing with the button bar layout. @shihaohong can you take a look and let me know if this is the case? If not I will dive into this. Thx.

**Comment by shihaohong** [comment]
I cannot reproduce the issue. I edited the original issue with a minimal reproducible sample app based on the code provided by the original poster.

**Comment by avldabade** [comment]
I solved this issue by adding SizedBox() widget as parent of Theme() widget and child of FittedBox() widget.

```
Future<Null> selectTime(BuildContext context, String startOrEnd) async {
    final TimeOfDay picked = await showTimePicker(
      context: context,
      initialTime: selectedTime,
      builder: (context, child) {
        return FittedBox(
          child: SizedBox(
            height: MediaQuery.of(context).size.height,
            width: MediaQuery.of(context).size.width,
            child: Theme(
              child: child,
              data: ThemeData(
                primaryColor: const Color(0xff1c4598),
                accentColor: const Color(0xff2761d6),
                // Define the default Font Family
                fontFamily: 'Ebrima',
              ),
            ),
          ),
        );
      },
    );
    if (picked != null) {
      var timeSelectedArr = picked.toString().split('('); //TimeOfDay(15:43)
      var timeSelected1 = timeSelectedArr[1].toString().split(')');
      timeSelected = timeSelected1[0] + ':00';
      //String formattedDate = DateFormat('yyyy-MM-dd – kk:mm').format(picked);
    } else {
      timeSelected = '00:00:00';
    }
    print('timeSelected:::::>  $timeSelected ');
    setState(() {
      if (startOrEnd == 'start') {
        startDateTime = startDateTime + ' ' + timeSelected;
        print('After selection startDateTime: $startDateTime');
      } else {
        endDateTime = endDateTime + ' ' + timeSelected;
        print('After selection startDateTime: $startDateTime');
      }
      print(
          'timeSelected below:::::>  $timeSelected \nstartDateTime: $startDateTime \n endDateTime: $endDateTime');
      //popBottomSheet();
    });
  }
```

**Comment by shihaohong** [comment]
Good to know you found a workaround :) 

Since there is no minimal reproduction of the issue, I will close out this out for now, but please do not hesitate to reopen this issue if there anybody can provide a minimal test case to replicate the crash!

**Comment by jatinjain001** [comment]
this is not helpful for me .any different way
