### ISSUE TITLE
Run 'flutter build apk' then app crash.

### ISSUE THREAD

**Issue by chinachen01** [flutter/flutter#47527]
I upgraded flutter this morning, but when I use `flutter build apk` to build the app, the app crash. Then I try to use `./gradlw assembleRelease` to build app, the app runs well. This problem only happened after I upgraded flutter.
I compared the two apps and found that the latter app is larger than the previous one. I guess `flutter build apk` may remove some used resources.
You can add this plugin on your `pubspec.yarml`, so you can reproduce this problem.
```
dependencies:
  fijkplayer: ^0.2.3
```
crash logs:
```
12-20 18:10:04.768 12794 12794 D AndroidRuntime: Shutting down VM
12-20 18:10:04.771 12794 12794 E AndroidRuntime: FATAL EXCEPTION: main
12-20 18:10:04.771 12794 12794 E AndroidRuntime: Process: com.rootcloud.crp, PID: 12794
12-20 18:10:04.771 12794 12794 E AndroidRuntime: java.lang.UnsatisfiedLinkError: JNI_ERR returned from JNI_OnLoad in "/data/app/com.rootcloud.crp-CcNlXLHC-p3qKUclwvQcrQ==/lib/arm64/libijksdl.so"
12-20 18:10:04.771 12794 12794 E AndroidRuntime: 	at java.lang.Runtime.loadLibrary0(Runtime.java:1016)
12-20 18:10:04.771 12794 12794 E AndroidRuntime: 	at java.lang.System.loadLibrary(System.java:1672)
12-20 18:10:04.771 12794 12794 E AndroidRuntime: 	at tv.danmaku.ijk.media.player.e.a(:197)
12-20 18:10:04.771 12794 12794 E AndroidRuntime: 	at tv.danmaku.ijk.media.player.IjkMediaPlayer.a(:209)
12-20 18:10:04.771 12794 12794 E AndroidRuntime: 	at tv.danmaku.ijk.media.player.IjkMediaPlayer.b(:249)
12-20 18:10:04.771 12794 12794 E AndroidRuntime: 	at tv.danmaku.ijk.media.player.IjkMediaPlayer.<init>(:245)
12-20 18:10:04.771 12794 12794 E AndroidRuntime: 	at tv.danmaku.ijk.media.player.IjkMediaPlayer.<init>(:236)
12-20 18:10:04.771 12794 12794 E AndroidRuntime: 	at c.b.a.b.<init>(:99)
12-20 18:10:04.771 12794 12794 E AndroidRuntime: 	at c.b.a.d.a(:64)
12-20 18:10:04.771 12794 12794 E AndroidRuntime: 	at d.a.c.a.a(:26)
12-20 18:10:04.771 12794 12794 E AndroidRuntime: 	at com.rootcloud.crp.MainActivity.onCreate(:12)
12-20 18:10:04.771 12794 12794 E AndroidRuntime: 	at android.app.Activity.performCreate(Activity.java:7458)
12-20 18:10:04.771 12794 12794 E AndroidRuntime: 	at android.app.Activity.performCreate(Activity.java:7448)
12-20 18:10:04.771 12794 12794 E AndroidRuntime: 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1286)
12-20 18:10:04.771 12794 12794 E AndroidRuntime: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3409)
12-20 18:10:04.771 12794 12794 E AndroidRuntime: 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3614)
12-20 18:10:04.771 12794 12794 E AndroidRuntime: 	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:86)
12-20 18:10:04.771 12794 12794 E AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
12-20 18:10:04.771 12794 12794 E AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
12-20 18:10:04.771 12794 12794 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2199)
12-20 18:10:04.771 12794 12794 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:112)
12-20 18:10:04.771 12794 12794 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:216)
12-20 18:10:04.771 12794 12794 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7625)
12-20 18:10:04.771 12794 12794 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
12-20 18:10:04.771 12794 12794 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524)
12-20 18:10:04.771 12794 12794 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:987)
```

flutter doctor -v:
```
[✓] Flutter (Channel stable, v1.12.13+hotfix.5, on Mac OS X 10.14.6 18G103, locale zh-Hans-CN)
    • Flutter version 1.12.13+hotfix.5 at /Users/sghl/Documents/workspace/flutter-project/flutter
    • Framework revision 27321ebbad (9 days ago), 2019-12-10 18:15:01 -0800
    • Engine revision 2994f7e1e6
    • Dart version 2.7.0

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/sghl/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.3, Build version 11C29
    • CocoaPods version 1.8.4

[!] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[!] Android Studio
    • Android Studio at /Applications/Android Studio 4.0 Preview.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)

[✓] VS Code (version 1.41.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.7.1

[✓] Connected device (2 available)
    • JSN AL00a         • 7XBRX19411003667                     • android-arm64 • Android 9 (API
      28)
    • iPhone 11 Pro Max • A510D8A6-4AA9-47DE-A552-C881972D6175 • ios           •
      com.apple.CoreSimulator.SimRuntime.iOS-13-3 (simulator)

! Doctor found issues in 2 categories.
```

**Comment by iapicca** [comment]
Hi @chinachen01
please try to run
`flutter clean`
`flutter pub cache repair`

also [fijkplayer](https://pub.dev/packages/fijkplayer) is a 3rd party plugin
and you  want to open an issue in the dedicated [github](https://github.com/befovy/fijkplayer/issues)
Closing, as this isn't an issue with Flutter itself,
if you disagree please write in the comments and I will reopen it
Thank you

**Comment by chinachen01** [comment]
The point is if I run `./gradlew assembleRelease` in android directory, the app works well. but if I run `flutter build apk`, the app crash.
In the last version of flutter, my project works well.  And  I notice when  I  run `flutter build apk`, flutter will remove some unused resources before run `gradlew assembleRelease`, this is the difference. So I think flutter may remove some necessary resources(or there are other errors).
PS: Tomorrow I'll try to run `flutter clean and flutter pub cache repair`

**Comment by chinachen01** [comment]
@iapicca 
`flutter clean`
`flutter pub cache repair`
it doesn't work~
By the way, if I run `flutter run --release`, the apk works fine.

**Comment by chinachen01** [comment]
I try to let flutter doesn't remove the resources before running `assembleRelease`.
```
flutter build apk
If you are deploying the app to the Play Store, it's recommended to use app
bundles or split the APK to reduce the APK size.
    To generate an app bundle, run:
        flutter build appbundle --target-platform
        android-arm,android-arm64,android-x64
        Learn more on: https://developer.android.com/guide/app-bundle
    To split the APKs per ABI, run:
        flutter build apk --target-platform
        android-arm,android-arm64,android-x64 --split-per-abi
        Learn more on:
        https://developer.android.com/studio/build/configure-apk-splits#configur
        e-abi-split
注: /Users/sghl/Documents/workspace/flutter-project/flutter/.pub-cache/hosted/pub.dartlang.org/fijkplayer-0.2.3/android/src/main/java/com/befovy/fijkplayer/FijkPlugin.java使用或覆盖了已过时的 API。
注: 有关详细信息, 请使用 -Xlint:deprecation 重新编译。
Removed unused resources: Binary resource data reduced from 44KB to 35KB: Removed 20%
Running Gradle task 'assembleRelease'...
Running Gradle task 'assembleRelease'... Done                      59.4s
✓ Built build/app/outputs/apk/release/app-release.apk (29.9MB).
```
So I add `shrinkResources false minifyEnabled false` in build.gradle.
```
    buildTypes {
        release {
            // TODO: Add your own signing config for the release build.
            // Signing with the debug keys for now, so `flutter run --release` works.
            signingConfig signingConfigs.debug

            shrinkResources false
            minifyEnabled false
        }
    }
```
Then run `flutter build apk`,
```
You are building a fat APK that includes binaries for android-arm,
android-arm64, android-x64.
If you are deploying the app to the Play Store, it's recommended to use app
bundles or split the APK to reduce the APK size.
    To generate an app bundle, run:
        flutter build appbundle --target-platform
        android-arm,android-arm64,android-x64
        Learn more on: https://developer.android.com/guide/app-bundle
    To split the APKs per ABI, run:
        flutter build apk --target-platform
        android-arm,android-arm64,android-x64 --split-per-abi
        Learn more on:
        https://developer.android.com/studio/build/configure-apk-splits#configur
        e-abi-split
Running Gradle task 'assembleRelease'...
Running Gradle task 'assembleRelease'... Done                      39.3s
✓ Built build/app/outputs/apk/release/app-release.apk (30.7MB).
```
 No `Removed unused resources: Binary resource data reduced from 44KB to 35KB: Removed 20%` anymore, and the apk increased by about 1M. At last run the apk, it works well.

**Comment by nogoodbay** [comment]
👍
