### ISSUE TITLE
Cupertino nav bar hero transition bug

### ISSUE THREAD

**Issue by VadimOsovsky** [flutter/flutter#47577]
![ezgif com-resize](https://user-images.githubusercontent.com/39897981/71306238-f94d4200-23ee-11ea-8d05-29b53e0e5d67.gif)

**Target Platform: Android**
**Target OS version/browser: api 28**
**Devices: Mi 8**

## Logs

```
flutter run --verbose
[  +38 ms] executing: [/Users/vadim/Documents/flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[  +73 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[        ] 27321ebbad34b0a3fafe99fac037102196d655ff
[        ] executing: [/Users/vadim/Documents/flutter/] git describe --match v*.*.* --first-parent --long --tags
[  +45 ms] Exit code 0 from: git describe --match v*.*.* --first-parent --long --tags
[        ] v1.12.13+hotfix.5-0-g27321ebba
[   +9 ms] executing: [/Users/vadim/Documents/flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[  +17 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[   +1 ms] origin/stable
[   +1 ms] executing: [/Users/vadim/Documents/flutter/] git ls-remote --get-url origin
[  +23 ms] Exit code 0 from: git ls-remote --get-url origin
[   +1 ms] https://github.com/flutter/flutter.git
[  +87 ms] executing: [/Users/vadim/Documents/flutter/] git rev-parse --abbrev-ref HEAD
[  +25 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] stable
[   +8 ms] executing: sw_vers -productName
[  +32 ms] Exit code 0 from: sw_vers -productName
[   +1 ms] Mac OS X
[        ] executing: sw_vers -productVersion
[  +38 ms] Exit code 0 from: sw_vers -productVersion
[   +4 ms] 10.15
[   +1 ms] executing: sw_vers -buildVersion
[  +23 ms] Exit code 0 from: sw_vers -buildVersion
[        ] 19A583
[ +100 ms] executing: /usr/bin/xcode-select --print-path
[ +125 ms] Exit code 0 from: /usr/bin/xcode-select --print-path
[        ] /Applications/Xcode.app/Contents/Developer
[   +1 ms] executing: /usr/bin/xcodebuild -version
[ +862 ms] Exit code 0 from: /usr/bin/xcodebuild -version
[        ] Xcode 11.1
           Build version 11A1027
[  +90 ms] executing: /Users/vadim/Library/Android/sdk/platform-tools/adb devices -l
[   +9 ms] Exit code 0 from: /Users/vadim/Library/Android/sdk/platform-tools/adb devices -l
[        ] List of devices attached
           37e8152b               device usb:337641472X product:dipper model:MI_8 device:dipper transport_id:24
[  +42 ms] executing: /Users/vadim/Documents/flutter/bin/cache/artifacts/libimobiledevice/idevice_id -h
[  +91 ms] /usr/bin/xcrun simctl list --json devices
[ +176 ms] More than one device connected; please specify a device with the '-d <deviceId>' flag, or use '-d all' to act on all devices.
[   +9 ms] /Users/vadim/Library/Android/sdk/platform-tools/adb -s 37e8152b shell getprop
[  +95 ms] ro.hardware = qcom
[   +6 ms] MI 8              • 37e8152b                             • android-arm64 • Android 9 (API 28)
[   +1 ms] iPhone 11 Pro Max • F5001749-D92B-4E77-8B65-E1B3F0A34848 • ios           • com.apple.CoreSimulator.SimRuntime.iOS-13-1 (simulator)
[  +17 ms] "flutter run" took 1,762ms.

#0      throwToolExit (package:flutter_tools/src/base/common.dart:28:3)
#1      RunCommand.validateCommand (package:flutter_tools/src/commands/run.dart:289:7)
<asynchronous suspension>
#2      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:590:11)
#3      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:515:33)
<asynchronous suspension>
#4      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:146:29)
#5      _rootRun (dart:async/zone.dart:1126:13)
#6      _CustomZone.run (dart:async/zone.dart:1023:19)
#7      _runZoned (dart:async/zone.dart:1518:10)
#8      runZoned (dart:async/zone.dart:1465:12)
#9      AppContext.run (package:flutter_tools/src/base/context.dart:145:18)
#10     FlutterCommand.run (package:flutter_tools/src/runner/flutter_command.dart:505:20)
#11     CommandRunner.runCommand (package:args/command_runner.dart:197:27)
#12     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:413:21)
<asynchronous suspension>
#13     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:146:29)
#14     _rootRun (dart:async/zone.dart:1126:13)
#15     _CustomZone.run (dart:async/zone.dart:1023:19)
#16     _runZoned (dart:async/zone.dart:1518:10)
#17     runZoned (dart:async/zone.dart:1465:12)
#18     AppContext.run (package:flutter_tools/src/base/context.dart:145:18)
#19     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:364:19)
#20     CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:112:25)
#21     new Future.sync (dart:async/future.dart:224:31)
#22     CommandRunner.run (package:args/command_runner.dart:112:14)
#23     FlutterCommandRunner.run (package:flutter_tools/src/runner/flutter_command_runner.dart:250:18)
#24     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:63:22)
#25     _rootRun (dart:async/zone.dart:1126:13)
#26     _CustomZone.run (dart:async/zone.dart:1023:19)
#27     _runZoned (dart:async/zone.dart:1518:10)
#28     runZoned (dart:async/zone.dart:1502:12)
#29     run.<anonymous closure> (package:flutter_tools/runner.dart:61:18)
<asynchronous suspension>
#30     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:146:29)
#31     _rootRun (dart:async/zone.dart:1126:13)
#32     _CustomZone.run (dart:async/zone.dart:1023:19)
#33     _runZoned (dart:async/zone.dart:1518:10)
#34     runZoned (dart:async/zone.dart:1465:12)
#35     AppContext.run (package:flutter_tools/src/base/context.dart:145:18)
#36     runInContext (package:flutter_tools/src/context_runner.dart:64:24)
#37     run (package:flutter_tools/runner.dart:50:10)
#38     main (package:flutter_tools/executable.dart:65:9)
#39     main (file:///Users/vadim/Documents/flutter/packages/flutter_tools/bin/flutter_tools.dart:8:3)
#40     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:305:32)
#41     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:174:12)

```

```
flutter analyze
Analyzing cupertino_chat...                                             
No issues found! (ran in 4.6s)
```

```
flutter doctor -v
[✓] Flutter (Channel stable, v1.12.13+hotfix.5, on Mac OS X 10.15 19A583, locale en-RU)
    • Flutter version 1.12.13+hotfix.5 at /Users/vadim/Documents/flutter
    • Framework revision 27321ebbad (10 days ago), 2019-12-10 18:15:01 -0800
    • Engine revision 2994f7e1e6
    • Dart version 2.7.0

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/vadim/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • ANDROID_HOME = /Users/vadim/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.1, Build version 11A1027
    • CocoaPods version 1.8.3

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 42.1.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] IntelliJ IDEA Ultimate Edition (version 2019.3)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 42.0.4
    • Dart plugin version 193.5731

[✓] VS Code (version 1.40.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.7.1

[✓] Connected device (2 available)
    • MI 8              • 37e8152b                             • android-arm64 • Android 9 (API 28)
    • iPhone 11 Pro Max • F5001749-D92B-4E77-8B65-E1B3F0A34848 • ios           • com.apple.CoreSimulator.SimRuntime.iOS-13-1 (simulator)

• No issues found!
```

**Comment by VadimOsovsky** [comment]
P.S. this issue isn't app specific, the bug can be reproduced in the Gallery App as well.

**Comment by haidarcorp** [comment]
This bug is massive imo and should really be a top priority. There's so many issues I'm having with this pop back ("Hero") gesture that it's the only thing disturbing me since switching to Flutter. Everything else is unbelievably great but I really hope they get around to the issues with the navigation controller asap.

**Comment by pedromassangocode** [comment]
Hi @VadimOsovsky 
Are you still facing this issue? If yes, can you please provide your `flutter doctor -v`, your `flutter run --verbose` and a minimal complete reproducible code sample?
Thank you

**Comment by VadimOsovsky** [comment]
I downloaded the gallery app and tested it there, and it seems to be fixed
