### ISSUE TITLE
[tool_crash] ProcessException: Process exited abnormally:emulator

### ISSUE THREAD

**Issue by Sounak123** [flutter/flutter#47574]
## Command
  ```console
  flutter emulator --launch pixel
  ```

  ## Logs
  ```bash
  ProcessException: ProcessException: Process exited abnormally:
emulator: ERROR: x86_64 emulation currently requires hardware acceleration!
Please ensure KVM is properly installed and usable.
CPU acceleration status: /dev/kvm is not found: VT disabled in BIOS or KVM kernel module not loaded
More info on configuring VM acceleration on Linux:
https://developer.android.com/studio/run/emulator-acceleration#vm-linux
General information on acceleration: https://developer.android.com/studio/run/emulator-acceleration.
  Command: /usr/lib/Android/emulator/emulator -avd pixel
  #0      RunResult.throwException (package:flutter_tools/src/base/process.dart:141:5)
#1      _DefaultProcessUtils.run (package:flutter_tools/src/base/process.dart:275:19)
<asynchronous suspension>
#2      AndroidEmulator.launch (package:flutter_tools/src/android/android_emulator.dart:52:52)
#3      EmulatorsCommand._launchEmulator (package:flutter_tools/src/commands/emulators.dart:74:31)
<asynchronous suspension>
#4      EmulatorsCommand.runCommand (package:flutter_tools/src/commands/emulators.dart:47:13)
#5      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:626:18)
#6      _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:74:64)
#7      _rootRunUnary (dart:async/zone.dart:1134:38)
#8      _CustomZone.runUnary (dart:async/zone.dart:1031:19)
#9      _FutureListener.handleValue (dart:async/future_impl.dart:140:18)
#10     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:682:45)
#11     Future._propagateToListeners (dart:async/future_impl.dart:711:32)
#12     Future._completeWithValue (dart:async/future_impl.dart:526:5)
#13     Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:556:7)
#14     _rootRun (dart:async/zone.dart:1126:13)
#15     _CustomZone.run (dart:async/zone.dart:1023:19)
#16     _CustomZone.runGuarded (dart:async/zone.dart:925:7)
#17     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:965:23)
  ```

  ```console
  [✓] Flutter (Channel dev, v1.13.2, on Linux, locale en_IN)
    • Flutter version 1.13.2 at /usr/lib/flutter
    • Framework revision 4944622b5d (9 days ago), 2019-12-12 18:43:58 +0000
    • Engine revision 12bf95fd49
    • Dart version 2.7.0 (build 2.7.0-dev.2.1 8b8894648f)

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /usr/lib/Android
    • Android NDK location not configured (optional; useful for native profiling
      support)
    • Platform android-29, build-tools 29.0.2
    • ANDROID_HOME = /usr/lib/Android
    • ANDROID_SDK_ROOT = /usr/lib/Android
    • Java binary at: /home/sounak/Downloads/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_152-release-1136-b06)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[!] Android Studio (version 3.2)
    • Android Studio at /home/sounak/Downloads/android-studio
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build
      1.8.0_152-release-1136-b06)

[✓] VS Code (version 1.27.2)
    • VS Code at /usr/share/code
    • Flutter extension version 2.21.1

[✓] Connected device (2 available)
    • Chrome     • chrome     • web-javascript • Google Chrome 69.0.3497.92
    • Web Server • web-server • web-javascript • Flutter Tools

! Doctor found issues in 1 category.

  ```

  ## Flutter Application Metadata
  No pubspec in working directory.

**Comment by iapicca** [comment]
Hi @Sounak123 
did you try the resolution offered by the logs?
```console
Please ensure KVM is properly installed and usable.
CPU acceleration status: /dev/kvm is not found: VT disabled in BIOS or KVM kernel module not loaded
```
Is `VT` enabled in your BIOS? 
Please take a look to the docs in the link provided by the logs
https://developer.android.com/studio/run/emulator-acceleration#vm-linux

Let me know if this solves your issue
thank you

**Comment by Sounak123** [comment]
Hi, I was trying to run it without android studio and it didn't work out. It worked fine after I used android studio. Thanks
