### ISSUE TITLE
Emulator: PANIC: Broken AVD system path. Check your ANDROID_SDK_ROOT value [C:\android]!

### ISSUE THREAD

**Issue by sy8044** [flutter/flutter#47587]
Hi. I'm trying to open emulator on android studio.
but somehow it isn't working...

```bash
오후 9:28	* daemon not running; starting now at tcp:5037
오후 9:28	* daemon started successfully
오후 9:28	Emulator: PANIC: Broken AVD system path. Check your ANDROID_SDK_ROOT value [C:\android]!
오후 9:28	Emulator: Process finished with exit code 1
This is what I got from event log
```

## Logs

```bash
C:\Users\김수영>echo $ANDROID_HOME
$ANDROID_HOME

C:\Users\김수영>flutter emulators --create --name Pixel-test
Emulator 'Pixel-test' created successfully.

C:\Users\김수영>flutter emulators --launch Pixel-test

Sending crash report to Google.
Crash report sent (report ID: 1851581013c0a82a)
Oops; flutter has exited unexpectedly.

Crash report written to C:\Users\김수영\flutter_01.log;
please let us know at https://github.com/flutter/flutter/issues.
```

```bash
#0      RunResult.throwException (package:flutter_tools/src/base/process.dart:141:5)
#1      _DefaultProcessUtils.run (package:flutter_tools/src/base/process.dart:275:19)
<asynchronous suspension>
#2      AndroidEmulator.launch (package:flutter_tools/src/android/android_emulator.dart:52:52)
#3      EmulatorsCommand._launchEmulator (package:flutter_tools/src/commands/emulators.dart:74:31)
<asynchronous suspension>
#4      EmulatorsCommand.runCommand (package:flutter_tools/src/commands/emulators.dart:47:13)
#5      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:615:18)
#6      _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:73:64)
#7      _rootRunUnary (dart:async/zone.dart:1134:38)
#8      _CustomZone.runUnary (dart:async/zone.dart:1031:19)
#9      _FutureListener.handleValue (dart:async/future_impl.dart:139:18)
#10     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:680:45)
#11     Future._propagateToListeners (dart:async/future_impl.dart:709:32)
#12     Future._completeWithValue (dart:async/future_impl.dart:524:5)
#13     Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:554:7)
#14     _rootRun (dart:async/zone.dart:1126:13)
#15     _CustomZone.run (dart:async/zone.dart:1023:19)
#16     _CustomZone.runGuarded (dart:async/zone.dart:925:7)
#17     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:965:23)
#18     _microtaskLoop (dart:async/schedule_microtask.dart:43:21)
#19     _startMicrotaskLoop (dart:async/schedule_microtask.dart:52:5)
#20     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
#21     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:175:5)
```

C:\Users\김수영>echo $ANDROID_HOME && flutter doctor -v
```console
$ANDROID_HOME
[√] Flutter (Channel stable, v1.12.13+hotfix.5, on Microsoft Windows [Version 10.0.18362.535], locale ko-KR)
    • Flutter version 1.12.13+hotfix.5 at C:\Users\김수영\flutter
    • Framework revision 27321ebbad (10 days ago), 2019-12-10 18:15:01 -0800
    • Engine revision 2994f7e1e6
    • Dart version 2.7.0


[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at C:\android
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • ANDROID_HOME = C:\android
    • ANDROID_SDK_ROOT = C:\android
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)
    • All Android licenses accepted.

[√] Android Studio (version 3.5)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 42.1.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)

[√] VS Code (version 1.41.1)
    • VS Code at C:\Users\김수영\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.7.1

[!] Connected device
    ! No devices available
```

**Comment by sy8044** [comment]
[flutter_01.log](https://github.com/flutter/flutter/files/3991391/flutter_01.log)
This is log file from crash report

**Comment by JonathanMonga** [comment]
Try to recreate an other avd and retry to launch it...

**Comment by sy8044** [comment]
@JonathanMonga 
you mean create another one in avd manager?
it isn't working either....

**Comment by iapicca** [comment]
Hi @sy8044 
the emulator doesn't show up in your doctor either,
could you please double-check the steps to create an emulator in the [docs](https://flutter.dev/docs/get-started/install/windows#set-up-the-android-emulator)
thank you

**Comment by dnfield** [comment]
I'm closing this since it's had no activity for > 21 days and has the waiting label.  I believe the bot is just backlogged and missing a bunch of these.  Please feel free to add more details if you want this re-opened.

**Comment by liyuqian** [comment]
@sy8044 : I had the same issue on Mac and fixed it by correcting the ANDROID_HOME environment variable. Correcting ANDROID_SDK_ROOT environment variable won't fix the problem so this seems to be a bug in Android's error messaging.

This ANDROID_HOME fix was originally suggested by https://blog.csdn.net/qq_44257240/article/details/99060873.
