### ISSUE TITLE
Running Gradle task 'assembleDebug'...   Takes to Much time and didn't run

### ISSUE THREAD

**Issue by natneal** [flutter/flutter#47603]
<details>
	<summary>logs</summary>

```bash
Exception in thread "main" java.net.UnknownHostException: downloads.gradle-dn.com
        at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:184)
        at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:172)
        at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
        at java.net.Socket.connect(Socket.java:589)
        at sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:666)
        at sun.security.ssl.BaseSSLSocketImpl.connect(BaseSSLSocketImpl.java:173)
        at sun.net.NetworkClient.doConnect(NetworkClient.java:180)
        at sun.net.www.http.HttpClient.openServer(HttpClient.java:463)
        at sun.net.www.http.HttpClient.openServer(HttpClient.java:558)
        at sun.net.www.protocol.https.HttpsClient.<init>(HttpsClient.java:264)
        at sun.net.www.protocol.https.HttpsClient.New(HttpsClient.java:367)
        at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(AbstractDelegateHttpsURLConnection.java:191)
        at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1156)
        at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1050)
        at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:177)
        at sun.net.www.protocol.http.HttpURLConnection.followRedirect0(HttpURLConnection.java:2729)
        at sun.net.www.protocol.http.HttpURLConnection.followRedirect(HttpURLConnection.java:2641)
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1824)
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1492)
        at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:263)
        at org.gradle.wrapper.Download.downloadInternal(Download.java:58)
        at org.gradle.wrapper.Download.download(Download.java:44)
        at org.gradle.wrapper.Install$1.call(Install.java:61)
        at org.gradle.wrapper.Install$1.call(Install.java:48)
        at org.gradle.wrapper.ExclusiveFileAccessManager.access(ExclusiveFileAccessManager.java:65)
        at org.gradle.wrapper.Install.createDist(Install.java:48)
        at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:128)
        at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:61)
Running Gradle task 'assembleRelease'...
Running Gradle task 'assembleRelease'... Done                       7.6s
Gradle task assembleRelease failed with exit code 1
```

</details>

**Comment by natneal** [comment]
[√] Flutter (Channel stable, v1.12.13+hotfix.5, on Microsoft Windows [Version 10.0.16299.19], locale en-US)

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[√] Android Studio (version 3.5)
[√] VS Code (version 1.41.0)
[√] Connected device (1 available)

• No issues found!

C:\Windows\System32>flutter doctor -v
[√] Flutter (Channel stable, v1.12.13+hotfix.5, on Microsoft Windows [Version 10.0.16299.19], locale en-US)
    • Flutter version 1.12.13+hotfix.5 at C:\src\flutter
    • Framework revision 27321ebbad (12 days ago), 2019-12-10 18:15:01 -0800
    • Engine revision 2994f7e1e6
    • Dart version 2.7.0


[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at C:\Users\Nati~\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)
    • All Android licenses accepted.

[√] Android Studio (version 3.5)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 42.1.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)

[√] VS Code (version 1.41.0)
    • VS Code at C:\Users\Nati~\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.7.1

[√] Connected device (1 available)
    • HUAWEI KII L05 • 2WMDU16A15000897 • android-arm64 • Android 6.0.1 (API 23)

**Comment by iapicca** [comment]
Hi @natneal  
can you please provide your `flutter run --verbose`?
Also, to better address the issue, would be helpful
if you could post  a minimal code sample
or the steps to reproduce the problem.
Thank you

**Comment by natneal** [comment]
> Hi @natneal
> can you please provide your `flutter run --verbose`?
> Also, to better address the issue, would be helpful
> if you could post a minimal code sample
> or the steps to reproduce the problem.
> Thank you

**Comment by natneal** [comment]
@iapicca Thank you for your response! the problem happend when i update flutter sdk to (v1.12.13+hotfix.5) but before i its working on (v1.9.1+hotfix.6).  on v1.12.13 doesnt Initializing gradle.  by the way i try to downgrade to v1.9.1+hotfix.6) but the same problem happens ....


aunching lib\main.dart on HUAWEI KII L05 in debug mode...
Initializing gradle...                                 Sending crash report to Google.
Crash report sent (report ID: ec8ed77ca7426e8a)
Initializing gradle...                                                 -Oops; flutter has exited unexpectedly.
                                                                                                                              \Crash report written to G:\flutNew\apphell\flutter_01.log;
please let us know at https://github.com/flutter/flutter/issues.                                                              /PS G:\flutNew\apphell> flutter clean
Deleting 'build\'.
Deleting 'G:\flutNew\apphell\.dart_tool\'.
Deleting 'G:\flutNew\apphell\.android\'.
Deleting 'G:\flutNew\apphell\.ios\'.
PS G:\flutNew\apphell> flutter run
Launching lib\main.dart on HUAWEI KII L05 in debug mode...
Initializing gradle...
(This is taking an unexpectedly long time.)       |^CTerminate batch job (Y/N)? y
PS G:\flutNew\apphell> flutter run --verbose
[  +28 ms] executing: [C:\src\flutter\flutter\] git log -n 1 --pretty=format:%H
[  +67 ms] Exit code 0 from: git log -n 1 --pretty=format:%H
[        ] 68587a0916366e9512a78df22c44163d041dd5f3
[        ] executing: [C:\src\flutter\flutter\] git describe --match v*.*.* --first-parent --long --tags
[  +31 ms] Exit code 0 from: git describe --match v*.*.* --first-parent --long --tags
[        ] v1.9.1+hotfix.6-0-g68587a091
[  +12 ms] executing: [C:\src\flutter\flutter\] git rev-parse --abbrev-ref --symbolic @{u}
[  +40 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/stable
[        ] executing: [C:\src\flutter\flutter\] git ls-remote --get-url origin
[  +39 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[  +89 ms] executing: [C:\src\flutter\flutter\] git rev-parse --abbrev-ref HEAD
[  +35 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] stable
[ +140 ms] executing: C:\Users\Nati~\AppData\Local\Android\sdk\platform-tools\adb.exe devices -l
[  +45 ms] Exit code 0 from: C:\Users\Nati~\AppData\Local\Android\sdk\platform-tools\adb.exe devices -l
[        ] List of devices attached
           2WMDU16A15000897       device product:KII-L05 model:HUAWEI_KII_L05 device:HWKII-Q transport_id:2
[  +27 ms] C:\Users\Nati~\AppData\Local\Android\sdk\platform-tools\adb.exe -s 2WMDU16A15000897 shell getprop
[ +149 ms] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +5 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[ +159 ms] ro.hardware = qcom
[  +76 ms] Launching lib\main.dart on HUAWEI KII L05 in debug mode...
[  +18 ms] Initializing gradle...
[   +2 ms] Using gradle from G:\flutNew\apphell\android\gradlew.bat.
[ +221 ms] executing: G:\flutNew\apphell\android\gradlew.bat -v

**Comment by jonahwilliams** [comment]
The failure you've posted is a failure by Gradle to either self-update or download dependencies. Unfortunately this requires network access, and there is nothing flutter can do here.
