### ISSUE TITLE
ArgumentError: Invalid argument(s): Cannot find executable for /.../flutter/bin/cache/artifacts/libimobiledevice/ideviceinfo.

### ISSUE THREAD

**Issue by tzt1994** [flutter/flutter#47644]
Flutter crash report; please file at https://github.com/flutter/flutter/issues.

## command

flutter --no-color run --machine --track-widget-creation --device-id=4996BA5F-3BC2-48DD-A008-59F0CC3276B8 lib/main.dart

## exception

ArgumentError: Invalid argument(s): Cannot find executable for /Users/tangzhentao/flutter/bin/cache/artifacts/libimobiledevice/ideviceinfo.

```
#0      _getExecutable (package:process/src/interface/local_process_manager.dart:127:5)
#1      LocalProcessManager.run (package:process/src/interface/local_process_manager.dart:68:30)
#2      IMobileDevice.getInfoForDevice (package:flutter_tools/src/ios/mac.dart:199:57)
<asynchronous suspension>
#3      IOSDevice.getAttachedDevices (package:flutter_tools/src/ios/devices.dart:184:55)
<asynchronous suspension>
#4      IOSDevices.pollingGetDevices (package:flutter_tools/src/ios/devices.dart:117:57)
#5      PollingDeviceDiscovery.devices (package:flutter_tools/src/device.dart:270:52)
<asynchronous suspension>
#6      DeviceManager.getAllConnectedDevices (package:flutter_tools/src/device.dart:136:46)
<asynchronous suspension>
#7      DeviceManager.getDevicesById (package:flutter_tools/src/device.dart:101:40)
<asynchronous suspension>
#8      DeviceManager.getDevices (package:flutter_tools/src/device.dart:125:11)
#9      DeviceManager.findTargetDevices (package:flutter_tools/src/device.dart:169:34)
<asynchronous suspension>
#10     FlutterCommand.findAllTargetDevices (package:flutter_tools/src/runner/flutter_command.dart:515:48)
<asynchronous suspension>
#11     RunCommand.validateCommand (package:flutter_tools/src/commands/run.dart:279:21)
<asynchronous suspension>
#12     FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:465:11)
<asynchronous suspension>
#13     FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:407:33)
<asynchronous suspension>
#14     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:154:29)
<asynchronous suspension>
#15     _rootRun (dart:async/zone.dart:1124:13)
#16     _CustomZone.run (dart:async/zone.dart:1021:19)
#17     _runZoned (dart:async/zone.dart:1516:10)
#18     runZoned (dart:async/zone.dart:1463:12)
#19     AppContext.run (package:flutter_tools/src/base/context.dart:153:18)
<asynchronous suspension>
#20     FlutterCommand.run (package:flutter_tools/src/runner/flutter_command.dart:397:20)
#21     CommandRunner.runCommand (package:args/command_runner.dart:197:27)
<asynchronous suspension>
#22     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:402:21)
<asynchronous suspension>
#23     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:154:29)
<asynchronous suspension>
#24     _rootRun (dart:async/zone.dart:1124:13)
#25     _CustomZone.run (dart:async/zone.dart:1021:19)
#26     _runZoned (dart:async/zone.dart:1516:10)
#27     runZoned (dart:async/zone.dart:1463:12)
#28     AppContext.run (package:flutter_tools/src/base/context.dart:153:18)
<asynchronous suspension>
#29     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:356:19)
<asynchronous suspension>
#30     CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:112:25)
#31     new Future.sync (dart:async/future.dart:224:31)
#32     CommandRunner.run (package:args/command_runner.dart:112:14)
#33     FlutterCommandRunner.run (package:flutter_tools/src/runner/flutter_command_runner.dart:242:18)
#34     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:63:22)
<asynchronous suspension>
#35     _rootRun (dart:async/zone.dart:1124:13)
#36     _CustomZone.run (dart:async/zone.dart:1021:19)
#37     _runZoned (dart:async/zone.dart:1516:10)
#38     runZoned (dart:async/zone.dart:1500:12)
#39     run.<anonymous closure> (package:flutter_tools/runner.dart:61:18)
<asynchronous suspension>
#40     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:154:29)
<asynchronous suspension>
#41     _rootRun (dart:async/zone.dart:1124:13)
#42     _CustomZone.run (dart:async/zone.dart:1021:19)
#43     _runZoned (dart:async/zone.dart:1516:10)
#44     runZoned (dart:async/zone.dart:1463:12)
#45     AppContext.run (package:flutter_tools/src/base/context.dart:153:18)
<asynchronous suspension>
#46     runInContext (package:flutter_tools/src/context_runner.dart:59:24)
<asynchronous suspension>
#47     run (package:flutter_tools/runner.dart:50:10)
#48     main (package:flutter_tools/executable.dart:65:9)
<asynchronous suspension>
#49     main (file:///b/s/w/ir/k/archive/flutter/packages/flutter_tools/bin/flutter_tools.dart:8:3)
#50     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:303:32)
#51     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:12)
```

## flutter doctor

```
encountered exception: Invalid argument(s): Cannot find executable for /Users/tangzhentao/flutter/bin/cache/artifacts/libimobiledevice/ideviceinfo.

#0      _getExecutable (package:process/src/interface/local_process_manager.dart:127:5)
#1      LocalProcessManager.run (package:process/src/interface/local_process_manager.dart:68:30)
#2      IMobileDevice.getInfoForDevice (package:flutter_tools/src/ios/mac.dart:199:57)
<asynchronous suspension>
#3      IOSDevice.getAttachedDevices (package:flutter_tools/src/ios/devices.dart:184:55)
<asynchronous suspension>
#4      IOSDevices.pollingGetDevices (package:flutter_tools/src/ios/devices.dart:117:57)
#5      PollingDeviceDiscovery.devices (package:flutter_tools/src/device.dart:270:52)
<asynchronous suspension>
#6      DeviceManager.getAllConnectedDevices (package:flutter_tools/src/device.dart:136:46)
<asynchronous suspension>
#7      DeviceValidator.validate (package:flutter_tools/src/doctor.dart:760:54)
<asynchronous suspension>
#8      Doctor.startValidatorTasks (package:flutter_tools/src/doctor.dart:140:52)
#9      Doctor.diagnose (package:flutter_tools/src/doctor.dart:211:41)
#10     _AsyncAwaitCompleter.start (dart:async-patch/async_patch.dart:43:6)
#11     Doctor.diagnose (package:flutter_tools/src/doctor.dart:201:24)
#12     _doctorText.<anonymous closure> (package:flutter_tools/runner.dart:202:26)
#13     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:154:29)
#14     _AsyncAwaitCompleter.start (dart:async-patch/async_patch.dart:43:6)
#15     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:154:7)
#16     _rootRun (dart:async/zone.dart:1124:13)
#17     _CustomZone.run (dart:async/zone.dart:1021:19)
#18     _runZoned (dart:async/zone.dart:1516:10)
#19     runZoned (dart:async/zone.dart:1463:12)
#20     AppContext.run (package:flutter_tools/src/base/context.dart:153:18)
#21     _AsyncAwaitCompleter.start (dart:async-patch/async_patch.dart:43:6)
#22     AppContext.run (package:flutter_tools/src/base/context.dart:140:19)
#23     _doctorText (package:flutter_tools/runner.dart:201:19)
#24     _AsyncAwaitCompleter.start (dart:async-patch/async_patch.dart:43:6)
#25     _doctorText (package:flutter_tools/runner.dart:197:27)
#26     _createLocalCrashReport (package:flutter_tools/runner.dart:179:32)
#27     _AsyncAwaitCompleter.start (dart:async-patch/async_patch.dart:43:6)
#28     _createLocalCrashReport (package:flutter_tools/runner.dart:164:37)
#29     _handleToolError (package:flutter_tools/runner.dart:134:33)
#30     _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:71:64)
#31     _rootRunUnary (dart:async/zone.dart:1132:38)
#32     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#33     _FutureListener.handleValue (dart:async/future_impl.dart:137:18)
#34     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:678:45)
#35     Future._propagateToListeners (dart:async/future_impl.dart:707:32)
#36     Future._completeWithValue (dart:async/future_impl.dart:522:5)
#37     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:30:15)
#38     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:288:13)
#39     CrashReportSender.sendReport (package:flutter_tools/src/reporting/crash_reporting.dart)
#40     _asyncErrorWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:78:45)
#41     _rootRunBinary (dart:async/zone.dart:1144:38)
#42     _CustomZone.runBinary (dart:async/zone.dart:1037:19)
#43     _FutureListener.handleError (dart:async/future_impl.dart:151:20)
#44     Future._propagateToListeners.handleError (dart:async/future_impl.dart:690:47)
#45     Future._propagateToListeners (dart:async/future_impl.dart:711:24)
#46     Future._completeError (dart:async/future_impl.dart:530:5)
#47     _AsyncAwaitCompleter.completeError (dart:async-patch/async_patch.dart:36:15)
#48     IOClient.send (package:http/src/io_client.dart)
#49     _asyncErrorWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:78:45)
#50     _rootRunBinary (dart:async/zone.dart:1144:38)
#51     _CustomZone.runBinary (dart:async/zone.dart:1037:19)
#52     _FutureListener.handleError (dart:async/future_impl.dart:151:20)
#53     Future._propagateToListeners.handleError (dart:async/future_impl.dart:690:47)
#54     Future._propagateToListeners (dart:async/future_impl.dart:711:24)
#55     Future._completeError (dart:async/future_impl.dart:530:5)
#56     Future._asyncCompleteError.<anonymous closure> (dart:async/future_impl.dart:578:7)
#57     _rootRun (dart:async/zone.dart:1124:13)
#58     _CustomZone.run (dart:async/zone.dart:1021:19)
#59     _CustomZone.runGuarded (dart:async/zone.dart:923:7)
#60     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:963:23)
#61     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#62     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#63     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:116:13)
#64     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:173:5)
```

**Comment by janmoppel** [comment]
Hello @tzt1994 !

Thank you for posting an issue.
 
It seems like there was a similar behaviour reported before and Flutter team has been already informed about this: #43398. You can find some proposed solutions there as well.

As similar problem was reported before, closing this thread for now.
 
Thank you.
