### ISSUE TITLE
[Dart version 2.7] Not able to build application since update: Unhandled Exception: ServicesBinding.defaultBinaryMessenger was accessed before the binding was initialized.

### ISSUE THREAD

**Issue by EmperorB** [flutter/flutter#47642]
I have updated to latest version of flutter and after troubleshooting came to know that I need to add `WidgetsFlutterBinding.ensureInitialized()` before anything else in main method. Still I am getting exceptions.

## Steps to Reproduce

**main.dart file**
```dart
import 'package:flutter/material.dart';

void main() async {
//  await SystemChrome.setPreferredOrientations([DeviceOrientation.portraitUp]);
  WidgetsFlutterBinding.ensureInitialized();
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        // This is the theme of your application.
        //
        // Try running your application with "flutter run". You'll see the
        // application has a blue toolbar. Then, without quitting the app, try
        // changing the primarySwatch below to Colors.green and then invoke
        // "hot reload" (press "r" in the console where you ran "flutter run",
        // or simply save your changes to "hot reload" in a Flutter IDE).
        // Notice that the counter didn't reset back to zero; the application
        // is not restarted.
        primarySwatch: Colors.blue,
      ),
      home: Text('ds'),
    );
  }
}
```

**pubsec.yaml**
```yaml
dependencies:
  flutter:
    sdk: flutter
  sqflite: ^1.2.0
```

This problem occurs on iOS and android simulator and physical devices.

## Logs

```
[  +65 ms] E/flutter (30833): [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: ServicesBinding.defaultBinaryMessenger was accessed before the binding was initialized.
[        ] E/flutter (30833): If you're running an application and need to access the binary messenger before `runApp()` has been called (for example, during plugin initialization), then you need
to explicitly call the `WidgetsFlutterBinding.ensureInitialized()` first.
[   +1 ms] E/flutter (30833): If you're running a test, you can call the `TestWidgetsFlutterBinding.ensureInitialized()` as the first line in your test's `main()` method to initialize the binding.
[        ] E/flutter (30833): #0      defaultBinaryMessenger.<anonymous closure> (package:flutter/src/services/binary_messenger.dart:76:7)
[        ] E/flutter (30833): #1      defaultBinaryMessenger (package:flutter/src/services/binary_messenger.dart:89:4)
[        ] E/flutter (30833): #2      MethodChannel.binaryMessenger (package:flutter/src/services/platform_channel.dart:140:62)
[   +2 ms] E/flutter (30833): #3      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:314:35)
[        ] E/flutter (30833): #4      OptionalMethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:429:36)
[        ] E/flutter (30833): #5      SystemChrome.setPreferredOrientations (package:flutter/src/services/system_chrome.dart:236:35)
[        ] E/flutter (30833): #6      main (package:e_sports/main.dart:6:22)
[        ] E/flutter (30833): #7      _runMainZoned.<anonymous closure>.<anonymous closure> (dart:ui/hooks.dart:239:25)
[        ] E/flutter (30833): #8      _rootRun (dart:async/zone.dart:1126:13)
[        ] E/flutter (30833): #9      _CustomZone.run (dart:async/zone.dart:1023:19)
[        ] E/flutter (30833): #10     _runZoned (dart:async/zone.dart:1518:10)
[        ] E/flutter (30833): #11     runZoned (dart:async/zone.dart:1502:12)
[        ] E/flutter (30833): #12     _runMainZoned.<anonymous closure> (dart:ui/hooks.dart:231:5)
[        ] E/flutter (30833): #13     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:307:19)
[        ] E/flutter (30833): #14     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:174:12)
[  +13 ms] E/flutter (30833): 
[ +149 ms] E/flutter (32241): [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: ServicesBinding.defaultBinaryMessenger was accessed before the binding was initialized.
[        ] E/flutter (32241): If you're running an application and need to access the binary messenger before `runApp()` has been called (for example, during plugin initialization), then you need
to explicitly call the `WidgetsFlutterBinding.ensureInitialized()` first.
[        ] E/flutter (32241): If you're running a test, you can call the `TestWidgetsFlutterBinding.ensureInitialized()` as the first line in your test's `main()` method to initialize the binding.
[        ] E/flutter (32241): #0      defaultBinaryMessenger.<anonymous closure> (package:flutter/src/services/binary_messenger.dart:76:7)
[        ] E/flutter (32241): #1      defaultBinaryMessenger (package:flutter/src/services/binary_messenger.dart:89:4)
[        ] E/flutter (32241): #2      MethodChannel.binaryMessenger (package:flutter/src/services/platform_channel.dart:140:62)
[        ] E/flutter (32241): #3      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:314:35)
[        ] E/flutter (32241): #4      OptionalMethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:429:36)
[        ] E/flutter (32241): #5      SystemChrome.setPreferredOrientations (package:flutter/src/services/system_chrome.dart:236:35)
[        ] E/flutter (32241): #6      main (package:e_sports/main.dart:6:22)
[        ] E/flutter (32241): #7      _runMainZoned.<anonymous closure>.<anonymous closure> (dart:ui/hooks.dart:239:25)
[        ] E/flutter (32241): #8      _rootRun (dart:async/zone.dart:1126:13)
[        ] E/flutter (32241): #9      _CustomZone.run (dart:async/zone.dart:1023:19)
[        ] E/flutter (32241): #10     _runZoned (dart:async/zone.dart:1518:10)
[        ] E/flutter (32241): #11     runZoned (dart:async/zone.dart:1502:12)
[        ] E/flutter (32241): #12     _runMainZoned.<anonymous closure> (dart:ui/hooks.dart:231:5)
[        ] E/flutter (32241): #13     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:307:19)
[        ] E/flutter (32241): #14     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:174:12)
[        ] E/flutter (32241): 
[  +54 ms] E/flutter (32437): [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: ServicesBinding.defaultBinaryMessenger was accessed before the binding was initialized.
[        ] E/flutter (32437): If you're running an application and need to access the binary messenger before `runApp()` has been called (for example, during plugin initialization), then you need
to explicitly call the `WidgetsFlutterBinding.ensureInitialized()` first.
[        ] E/flutter (32437): If you're running a test, you can call the `TestWidgetsFlutterBinding.ensureInitialized()` as the first line in your test's `main()` method to initialize the binding.
[        ] E/flutter (32437): #0      defaultBinaryMessenger.<anonymous closure> (package:flutter/src/services/binary_messenger.dart:76:7)
[        ] E/flutter (32437): #1      defaultBinaryMessenger (package:flutter/src/services/binary_messenger.dart:89:4)
[        ] E/flutter (32437): #2      MethodChannel.binaryMessenger (package:flutter/src/services/platform_channel.dart:140:62)
[        ] E/flutter (32437): #3      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:314:35)
[        ] E/flutter (32437): #4      OptionalMethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:429:36)
[        ] E/flutter (32437): #5      SystemChrome.setPreferredOrientations (package:flutter/src/services/system_chrome.dart:236:35)
[        ] E/flutter (32437): #6      main (package:e_sports/main.dart:6:22)
[        ] E/flutter (32437): #7      _runMainZoned.<anonymous closure>.<anonymous closure> (dart:ui/hooks.dart:239:25)
[        ] E/flutter (32437): #8      _rootRun (dart:async/zone.dart:1126:13)
[        ] E/flutter (32437): #9      _CustomZone.run (dart:async/zone.dart:1023:19)
[        ] E/flutter (32437): #10     _runZoned (dart:async/zone.dart:1518:10)
[        ] E/flutter (32437): #11     runZoned (dart:async/zone.dart:1502:12)
[        ] E/flutter (32437): #12     _runMainZoned.<anonymous closure> (dart:ui/hooks.dart:231:5)
[        ] E/flutter (32437): #13     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:307:19)
[        ] E/flutter (32437): #14     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:174:12)
[   +1 ms] E/flutter (32437): 
[ +176 ms] E/flutter ( 1042): [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: ServicesBinding.defaultBinaryMessenger was accessed before the binding was initialized.
[        ] E/flutter ( 1042): If you're running an application and need to access the binary messenger before `runApp()` has been called (for example, during plugin initialization), then you need
to explicitly call the `WidgetsFlutterBinding.ensureInitialized()` first.
[   +1 ms] E/flutter ( 1042): If you're running a test, you can call the `TestWidgetsFlutterBinding.ensureInitialized()` as the first line in your test's `main()` method to initialize the binding.
[   +1 ms] E/flutter ( 1042): #0      defaultBinaryMessenger.<anonymous closure> (package:flutter/src/services/binary_messenger.dart:76:7)
[   +2 ms] E/flutter ( 1042): #1      defaultBinaryMessenger (package:flutter/src/services/binary_messenger.dart:89:4)
[        ] E/flutter ( 1042): #2      MethodChannel.binaryMessenger (package:flutter/src/services/platform_channel.dart:140:62)
[        ] E/flutter ( 1042): #3      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:314:35)
[        ] E/flutter ( 1042): #4      OptionalMethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:429:36)
[        ] E/flutter ( 1042): #5      SystemChrome.setPreferredOrientations (package:flutter/src/services/system_chrome.dart:236:35)
[        ] E/flutter ( 1042): #6      main (package:e_sports/main.dart:6:22)
[        ] E/flutter ( 1042): #7      _runMainZoned.<anonymous closure>.<anonymous closure> (dart:ui/hooks.dart:239:25)
[        ] E/flutter ( 1042): #8      _rootRun (dart:async/zone.dart:1126:13)
[        ] E/flutter ( 1042): #9      _CustomZone.run (dart:async/zone.dart:1023:19)
[  +11 ms] E/flutter ( 1042): #10     _runZoned (dart:async/zone.dart:1518:10)
[        ] E/flutter ( 1042): #11     runZoned (dart:async/zone.dart:1502:12)
[        ] E/flutter ( 1042): #12     _runMainZoned.<anonymous closure> (dart:ui/hooks.dart:231:5)
[        ] E/flutter ( 1042): #13     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:307:19)
[        ] E/flutter ( 1042): #14     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:174:12)
[        ] E/flutter ( 1042): 

```

## Flutter doctor

```
[✓] Flutter (Channel stable, v1.12.13+hotfix.5, on Mac OS X 10.15 19A583, locale en-IN)
    • Flutter version 1.12.13+hotfix.5 at /Users/rajeshbudhiraja/Desktop/flutter
    • Framework revision 27321ebbad (12 days ago), 2019-12-10 18:15:01 -0800
    • Engine revision 2994f7e1e6
    • Dart version 2.7.0

 
[!] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/rajeshbudhiraja/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses

[✓] Xcode - develop for iOS and macOS (Xcode 11.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.1, Build version 11A1027
    • CocoaPods version 1.8.4

[✓] Android Studio (version 3.4)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 37.1.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

[✓] IntelliJ IDEA Community Edition (version 2019.3)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 42.0.4
    • Dart plugin version 193.5731

[✓] Connected device (1 available)
    • Lenovo K33a42 • 1e2fd626 • android-arm • Android 7.0 (API 24)


```

**Comment by janmoppel** [comment]
Hello @EmperorB !

Thank you for posting an issue.
Seems like a similar case to the #47197

**Comment by EmperorB** [comment]
hi @janmoppel 
Thanks for your help. This fixed my issue.
