### ISSUE TITLE
Stream execution freezes if nested exception is catched 

### ISSUE THREAD

**Issue by Onein** [flutter/flutter#47674]
This is only reproducible in Flutter (web) for me, I couldn't reproduce it with an dart cli only app. When you have an async stream pipeline and inside that stream an exception which is nested inside another async function, dart catches the exception, but only executes the very first line of code inside the catch clause and afterwards stops the stream execution.

## Steps to Reproduce

I've tried to give a simple example where this can be observed. When you click the FAB the first time it will print only the yielded value and none of the "hello world" prints. Any subsequent click on the FAB will result in no further stream execution.
```dart
import 'dart:async';

import 'package:flutter/cupertino.dart';
import 'package:flutter/foundation.dart';
import 'package:flutter/material.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatefulWidget {
  MyApp({Key key}) : super(key: key);

  @override
  _MyAppState createState() => _MyAppState();
}

class _MyAppState extends State<MyApp> {
  var controller = StreamController<String>();

  @override
  void initState() {
    super.initState();
    controller.stream.asyncExpand(testStream).listen((data) => print(data));
  }

  @override
  Widget build(BuildContext context) {
    final title = 'Test';
    return MaterialApp(
      title: title,
      home: Scaffold(
        appBar: AppBar(
          title: Text(title),
        ),
        body: Container(),
        floatingActionButton: FloatingActionButton(
          onPressed: () {
            controller.add("Test1");
          },
        ),
      ),
    );
  }

  Stream<String> testStream(String test) async* {
    try {
      await testFunction();
      yield test;
    } catch (e) {
      yield test;
      print('Hello, World!');
      print('Hello, World!');
      print('Hello, World!');
    }
  }

  Future<String> testFunction() async {
    await testFunctio2();
    return "";
  }

  Future<String> testFunctio2() async {
    throw Exception("test");
  }
}

```

**Target Platform:** WEB
**Target OS version/browser:** Linux/Chrome
**Devices:**

## Logs

Got this one on some occasions.
```
Invalid argument (isolateId): Unrecognized isolate id: "11"
#0      ChromeProxyService._getIsolate (package:dwds/src/services/chrome_proxy_service.dart:335:5)
#1      ChromeProxyService.callServiceExtension (package:dwds/src/services/chrome_proxy_service.dart:263:28)
#2      VmServerConnection._delegateRequest (package:vm_service/vm_service.dart:1195:53)
#3      _rootRunUnary (dart:async/zone.dart:1138:13)
#4      _CustomZone.runUnary (dart:async/zone.dart:1031:19)
#5      _CustomZone.runUnaryGuarded (dart:async/zone.dart:933:7)
#6      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11)
#7      _DelayedData.perform (dart:async/stream_impl.dart:594:14)
#8      _StreamImplEvents.handleNext (dart:async/stream_impl.dart:710:11)
#9      _PendingEvents.schedule.<anonymous closure> (dart:async/stream_impl.dart:670:7)
#10     _rootRun (dart:async/zone.dart:1122:38)
#11     _CustomZone.run (dart:async/zone.dart:1023:19)
#12     _CustomZone.runGuarded (dart:async/zone.dart:925:7)
#13     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:965:23)
#14     _rootRun (dart:async/zone.dart:1126:13)
#15     _CustomZone.run (dart:async/zone.dart:1023:19)
#16     _CustomZone.runGuarded (dart:async/zone.dart:925:7)
#17     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:965:23)
#18     _microtaskLoop (dart:async/schedule_microtask.dart:43:21)
#19     _startMicrotaskLoop (dart:async/schedule_microtask.dart:52:5)
#20     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
#21     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:175:5)
 (-32603) from ext.flutter.inspector.setPubRootDirectories()
```

## Flutter analyze

```
Analyzing test_listview...                                              
No issues found! (ran in 1.3s)
```

## Flutter doctor

```
[✓] Flutter (Channel master, v1.13.6-pre.16, on Linux, locale en_US.UTF-8)
    • Flutter version 1.13.6-pre.16 at /home/user/source/flutter/flutter_sdk/flutter
    • Framework revision fcaf9c4070 (2 days ago), 2019-12-21 14:03:01 -0800
    • Engine revision 33813929e3
    • Dart version 2.8.0 (build 2.8.0-dev.0.0 886615d0f9)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.0)
    • Android SDK at /home/user/Android/Sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.0
    • Java binary at: /usr/local/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b16-5323222)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Linux toolchain - develop for Linux desktop
    • clang++ 7.0.1
    • GNU Make 4.2.1

[!] Android Studio (version 3.4)
    • Android Studio at /usr/local/android-studio
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b16-5323222)

[✓] VS Code (version 1.41.1)
    • VS Code at /usr/share/code
    • Flutter extension version 3.3.0

[✓] Connected device (3 available)
    • Linux      • Linux      • linux-x64      • Linux
    • Chrome     • chrome     • web-javascript • Google Chrome 79.0.3945.88
    • Web Server • web-server • web-javascript • Flutter Tools

! Doctor found issues in 1 category.
```

**Comment by Onein** [comment]
This seems to be only an issue in debug mode (web). Should I open an issue @dart-lang/webdev?

**Comment by vsmenon** [comment]
Looks like a dartdevc bug.  Filed:

https://github.com/dart-lang/sdk/issues/39994

**Comment by goderbauer** [comment]
Looks like an upstream issue has been filed for this and there's no action for Flutter. I am going to close this issue.
