### ISSUE TITLE
(flutter doctor) ProcessException: ProcessException: Permission denied

### ISSUE THREAD

**Issue by vineetdikonia** [flutter/flutter#47672]
I have setting up flutter on my linux machine. But when trying to run flutter doctor command I got below output on terminal. Can someone please help me to get rid from this issue?

# Output
Doctor summary (to see all details, run flutter doctor -v):

Sending crash report to Google.
Crash report sent (report ID: 21c35ab811155cbc)
Oops; flutter has exited unexpectedly.
Crash report written to /home/emp/flutter_11.log;
please let us know at https://github.com/flutter/flutter/issues.

Then I have checked the logs and found
## command

flutter doctor

## exception

ProcessException: ProcessException: Permission denied
Command: /opt/android-studio/jre/bin/java -version

**Comment by janmoppel** [comment]
Hello @vineetdikonia !

Thank you for posting an issue.
Seems like similar behaviour has been already seen discussed here: #27368. In your case, looks like this is a problem with Java installation and not Flutter related: https://github.com/flutter/flutter/issues/27368#issuecomment-461532373

**Comment by dnfield** [comment]
I'm closing this since it's had no activity for > 21 days and has the waiting label.  I believe the bot is just backlogged and missing a bunch of these.  Please feel free to add more details if you want this re-opened.

**Comment by GULERTOLGA** [comment]
i am still getting same error.

Flutter crash report; please file at https://github.com/flutter/flutter/issues.

## command

flutter run

## exception

ProcessException: ProcessException: Operation not permitted
  Command: /Users/tolgaguler/Documents/Tolga.nosynch/git/netigma_mobile/android/gradlew -q -Ptarget=/Users/tolgaguler/Documents/Tolga.nosynch/git/netigma_mobile/lib/main.dart -Ptrack-widget-creation=true -Pfilesystem-scheme=org-dartlang-root -Ptarget-platform=android-arm64 assembleDebug

```
#0      _DefaultProcessUtils.stream (package:flutter_tools/src/base/process.dart:431:29)
<asynchronous suspension>
#1      buildGradleApp (package:flutter_tools/src/android/gradle.dart:364:35)
#2      _AsyncAwaitCompleter.start (dart:async-patch/async_patch.dart:45:6)
#3      buildGradleApp (package:flutter_tools/src/android/gradle.dart:218:28)
#4      _AndroidBuilderImpl.buildApk (package:flutter_tools/src/android/android_builder.dart:97:13)
#5      _AsyncAwaitCompleter.start (dart:async-patch/async_patch.dart:45:6)
#6      _AndroidBuilderImpl.buildApk (package:flutter_tools/src/android/android_builder.dart:91:24)
#7      AndroidDevice.startApp (package:flutter_tools/src/android/android_device.dart:522:28)
#8      _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:73:64)
#9      _rootRunUnary (dart:async/zone.dart:1134:38)
#10     _CustomZone.runUnary (dart:async/zone.dart:1031:19)
#11     _FutureListener.handleValue (dart:async/future_impl.dart:139:18)
#12     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:680:45)
#13     Future._propagateToListeners (dart:async/future_impl.dart:709:32)
#14     Future._completeWithValue (dart:async/future_impl.dart:524:5)
#15     Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:554:7)
#16     _rootRun (dart:async/zone.dart:1126:13)
#17     _CustomZone.run (dart:async/zone.dart:1023:19)
#18     _CustomZone.runGuarded (dart:async/zone.dart:925:7)
#19     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:965:23)
#20     _microtaskLoop (dart:async/schedule_microtask.dart:43:21)
#21     _startMicrotaskLoop (dart:async/schedule_microtask.dart:52:5)
#22     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
#23     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:175:5)
```

## flutter doctor

```
[32m[✓][39m Flutter (Channel stable, v1.12.13+hotfix.8, on Mac OS X 10.15.3 19D76, locale en)
    [32m•[39m Flutter version 1.12.13+hotfix.8 at /Users/tolgaguler/flutter
    [32m•[39m Framework revision 0b8abb4724 (10 days ago), 2020-02-11 11:44:36 -0800
    [32m•[39m Engine revision e1e6ced81d
    [32m•[39m Dart version 2.7.0

[32m[✓][39m Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    [32m•[39m Android SDK at /Users/tolgaguler/Library/Android/sdk
    [32m•[39m Android NDK location not configured (optional; useful for native profiling support)
    [32m•[39m Platform android-29, build-tools 29.0.2
    [32m•[39m Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    [32m•[39m Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
    [32m•[39m All Android licenses accepted.

[33m[!][39m Xcode - develop for iOS and macOS (Xcode 11.3.1)
    [32m•[39m Xcode at /Applications/Xcode.app/Contents/Developer
    [32m•[39m Xcode 11.3.1, Build version 11C504
    [31m✗[39m CocoaPods installed but not working.
        You appear to have CocoaPods installed but it is not working.
        This can happen if the version of Ruby that CocoaPods was installed with is different from the one being used to invoke it.
        This can usually be fixed by re-installing CocoaPods. For more info, see https://github.com/flutter/flutter/issues/14293.
      To re-install CocoaPods, run:
        sudo gem install cocoapods

[32m[✓][39m Android Studio (version 3.4)
    [32m•[39m Android Studio at /Applications/Android Studio.app/Contents
    [32m•[39m Flutter plugin version 38.2.1
    [32m•[39m Dart plugin version 183.6270
    [32m•[39m Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

[32m[✓][39m IntelliJ IDEA Community Edition (version 2019.2.4)
    [32m•[39m IntelliJ at /Applications/IntelliJ IDEA CE.app
    [32m•[39m Flutter plugin version 42.2.2
    [32m•[39m Dart plugin version 192.7761

[32m[✓][39m VS Code (version 1.41.1)
    [32m•[39m VS Code at /Applications/Visual Studio Code.app/Contents
    [32m•[39m Flutter extension version 3.8.0

[32m[✓][39m Connected device (1 available)
    [32m•[39m Mi A3 • 53f8cafbc337 • android-arm64 • Android 9 (API 28)

[33m![39m Doctor found issues in 1 category.
```
