### ISSUE TITLE
Exception in thread "main" java.util.zip.ZipException: error in opening zip file

### ISSUE THREAD

**Issue by mosbahali59** [flutter/flutter#47725]
Can't able to build the first app on VS.code using run Flutter

```bash
Launching lib\main.dart on SM A320F in debug mode...
Exception in thread "main" java.util.zip.ZipException: error in opening zip file
	at java.util.zip.ZipFile.open(Native Method)
	at java.util.zip.ZipFile.<init>(ZipFile.java:219)
	at java.util.zip.ZipFile.<init>(ZipFile.java:149)
	at java.util.zip.ZipFile.<init>(ZipFile.java:163)
	at org.gradle.wrapper.Install.unzip(Install.java:214)
	at org.gradle.wrapper.Install.access$600(Install.java:27)
	at org.gradle.wrapper.Install$1.call(Install.java:74)
	at org.gradle.wrapper.Install$1.call(Install.java:48)
	at org.gradle.wrapper.ExclusiveFileAccessManager.access(ExclusiveFileAccessManager.java:65)
	at org.gradle.wrapper.Install.createDist(Install.java:48)
	at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:128)
	at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:61)
[!] Gradle threw an error while trying to update itself. Retrying the update...
Exception in thread "main" java.util.zip.ZipException: error in opening zip file
```

**Comment by iapicca** [comment]
Hi @mosbahali59 
I see there's an open [issue](https://github.com/flutter/flutter/issues/40517) addressing the case you described.
Please follow up on that issue,
I'm closing the current one as duplicate.
If you disagree please write in the comments
and I will reopen it.
Thank you

**Comment by khankumail** [comment]
can't able to build the app in android studio using run flutter
Exception in thread "main" java.util.zip.ZipException: error in opening zip file
	at java.util.zip.ZipFile.open(Native Method)
	at java.util.zip.ZipFile.<init>(ZipFile.java:225)
	at java.util.zip.ZipFile.<init>(ZipFile.java:155)
	at java.util.zip.ZipFile.<init>(ZipFile.java:169)
	at org.gradle.wrapper.Install.unzip(Install.java:214)
	at org.gradle.wrapper.Install.access$600(Install.java:27)
	at org.gradle.wrapper.Install$1.call(Install.java:74)
	at org.gradle.wrapper.Install$1.call(Install.java:48)
	at org.gradle.wrapper.ExclusiveFileAccessManager.access(ExclusiveFileAccessManager.java:65)
	at org.gradle.wrapper.Install.createDist(Install.java:48)
	at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:128)
	at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:61)
[!] Gradle threw an error while trying to update itself. Retrying the update...
Running Gradle task 'assembleDebug'...
Exception in thread "main" java.util.zip.ZipException: error in opening zip file
	at java.util.zip.ZipFile.open(Native Method)
	at java.util.zip.ZipFile.<init>(ZipFile.java:225)
	at java.util.zip.ZipFile.<init>(ZipFile.java:155)
	at java.util.zip.ZipFile.<init>(ZipFile.java:169)
	at org.gradle.wrapper.Install.unzip(Install.java:214)
	at org.gradle.wrapper.Install.access$600(Install.java:27)
	at org.gradle.wrapper.Install$1.call(Install.java:74)
	at org.gradle.wrapper.Install$1.call(Install.java:48)
	at org.gradle.wrapper.ExclusiveFileAccessManager.access(ExclusiveFileAccessManager.java:65)
	at org.gradle.wrapper.Install.createDist(Install.java:48)
	at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:128)
	at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:61)
[!] Gradle threw an error while trying to update itself. Retrying the update...

**Comment by khankumail** [comment]
Android simulator showing error but IOS simulator runs fine

**Comment by pokou2020** [comment]
> Impossible de créer la première application sur VS.code à l'aide de l'exécution Flutter
> 
> ```shell
> Lancement de lib \ m ain.dart sur SM A320F en mode débogage ...
> Exception dans le thread " principal " java.util.zip.ZipException: erreur lors de l' ouverture du fichier zip
> 	sur java.util.zip.ZipFile.open (méthode native)
> 	à java.util.zip.ZipFile. < init > ( ZipFile.java:219 ) 
> 	sur java.util.zip.ZipFile. < init > ( ZipFile.java:149 ) 
> 	sur java.util.zip.ZipFile. < init > ( ZipFile.java:163 )
> 	sur org.gradle.wrapper.Install.unzip (Install.java:214)
> 	à org.gradle.wrapper.Install.access $ 6 00 (Install.java:27)
> 	sur org.gradle.wrapper.Install $ 1 .call (Install.java:74)
> 	sur org.gradle.wrapper.Install $ 1 .call (Install.java:48)
> 	sur org.gradle.wrapper.ExclusiveFileAccessManager.access (ExclusiveFileAccessManager.java:65)
> 	sur org.gradle.wrapper.Install.createDist (Install.java:48)
> 	sur org.gradle.wrapper.WrapperExecutor.execute (WrapperExecutor.java:128)
> 	sur org.gradle.wrapper.GradleWrapperMain.main (GradleWrapperMain.java:61)
> [ ! ] Gradle a lancé une erreur en essayant de se mettre à jour. Nouvelle tentative de mise à jour ...
> Exception dans le thread " principal " java.util.zip.ZipException: erreur lors de l' ouverture du fichier zip
> ```

bonjour j'ai le meme probleme est ce que vous avez pu resoufre le votre si oui vous l'avez fait

**Comment by pokou2020** [comment]
comment vous avez proccedé pour le resoudre

**Comment by waylife** [comment]
most likely the gradlew is not installed
copy gradle files from another project to the one you are running
<img width="441" alt="图片" src="https://user-images.githubusercontent.com/3348620/90207064-e7099380-de17-11ea-8e0a-56cb77ee9516.png">

**Comment by lonewarrior18** [comment]
Exception in thread "main" java.util.zip.ZipException: zip END header not found
	at java.base/java.util.zip.ZipFile$Source.zerror(ZipFile.java:1502)
	at java.base/java.util.zip.ZipFile$Source.findEND(ZipFile.java:1397)
	at java.base/java.util.zip.ZipFile$Source.initCEN(ZipFile.java:1404)
	at java.base/java.util.zip.ZipFile$Source.<init>(ZipFile.java:1209)
	at java.base/java.util.zip.ZipFile$Source.get(ZipFile.java:1172)
	at java.base/java.util.zip.ZipFile$CleanableResource.<init>(ZipFile.java:717)
	at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:237)
	at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:167)
	at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:181)
	at org.gradle.wrapper.Install.unzip(Install.java:214)
	at org.gradle.wrapper.Install.access$600(Install.java:27)
	at org.gradle.wrapper.Install$1.call(Install.java:74)
	at org.gradle.wrapper.Install$1.call(Install.java:48)
	at org.gradle.wrapper.ExclusiveFileAccessManager.access(ExclusiveFileAccessManager.java:65)
	at org.gradle.wrapper.Install.createDist(Install.java:48)
	at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:128)
	at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:61)
Exception: Gradle task assembleDebug failed with exit code 1
Exited (sigterm)

**Comment by lonewarrior18** [comment]
I have gradle version 6.7.1

**Comment by kusal123123** [comment]
same issue

**Comment by proXDhiya** [comment]
same issue here with gradle version 6.7.1

**Comment by Souhaila49** [comment]
Same issue here with gradle version 6.7.1
