### ISSUE TITLE
ProcessException: ProcessException: No such file or directory

### ISSUE THREAD

**Issue by Zaynex** [flutter/flutter#47736]
## command

`flutter run
`
## exception

`ProcessException: ProcessException: No such file or directory`
  Command: /usr/local/bin/pod install --verbose

```bash 
#0      CocoaPods._runPodInstall (package:flutter_tools/src/macos/cocoapods.dart:300:34)
<asynchronous suspension>
#1      CocoaPods.processPods (package:flutter_tools/src/macos/cocoapods.dart:145:15)
<asynchronous suspension>
#2      processPodsIfNeeded (package:flutter_tools/src/macos/cocoapod_utils.dart:36:46)
<asynchronous suspension>
#3      buildXcodeProject (package:flutter_tools/src/ios/mac.dart:357:9)
<asynchronous suspension>
#4      IOSSimulator._setupUpdatedApplicationBundle (package:flutter_tools/src/ios/simulators.dart:436:48)
<asynchronous suspension>
#5      IOSSimulator.startApp (package:flutter_tools/src/ios/simulators.dart:354:15)
#6      FlutterDevice.runHot (package:flutter_tools/src/resident_runner.dart:450:54)
#7      _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:73:64)
#8      _rootRunUnary (dart:async/zone.dart:1134:38)
#9      _CustomZone.runUnary (dart:async/zone.dart:1031:19)
#10     _FutureListener.handleValue (dart:async/future_impl.dart:139:18)
#11     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:680:45)
#12     Future._propagateToListeners (dart:async/future_impl.dart:709:32)
#13     Future._completeWithValue (dart:async/future_impl.dart:524:5)
#14     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:32:15)
#15     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:290:13)
#16     ApplicationPackageFactory.getPackageForPlatform (package:flutter_tools/src/application_package.dart)
#17     _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:73:64)
#18     _rootRunUnary (dart:async/zone.dart:1134:38)
#19     _CustomZone.runUnary (dart:async/zone.dart:1031:19)
#20     _FutureListener.handleValue (dart:async/future_impl.dart:139:18)
#21     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:680:45)
#22     Future._propagateToListeners (dart:async/future_impl.dart:709:32)
#23     Future._completeWithValue (dart:async/future_impl.dart:524:5)
#24     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:32:15)
#25     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:290:13)
#26     BuildableIOSApp.fromProject (package:flutter_tools/src/application_package.dart)
#27     _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:73:64)
#28     _rootRunUnary (dart:async/zone.dart:1134:38)
#29     _CustomZone.runUnary (dart:async/zone.dart:1031:19)
#30     _FutureListener.handleValue (dart:async/future_impl.dart:139:18)
#31     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:680:45)
#32     Future._propagateToListeners (dart:async/future_impl.dart:709:32)
#33     Future._completeWithValue (dart:async/future_impl.dart:524:5)
#34     Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:554:7)
#35     _rootRun (dart:async/zone.dart:1126:13)
#36     _CustomZone.run (dart:async/zone.dart:1023:19)
#37     _CustomZone.runGuarded (dart:async/zone.dart:925:7)
#38     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:965:23)
#39     _microtaskLoop (dart:async/schedule_microtask.dart:43:21)
#40     _startMicrotaskLoop (dart:async/schedule_microtask.dart:52:5)
#41     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
#42     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:175:5)
```

## flutter doctor

```console
[32m[✓][39m Flutter (Channel beta, v1.12.13+hotfix.6, on Mac OS X 10.15 19A583, locale zh-Hans-CN)
    [32m•[39m Flutter version 1.12.13+hotfix.6 at /Users/xiwz/playground/new/flutter
    [32m•[39m Framework revision 18cd7a3601 (13 days ago), 2019-12-11 06:35:39 -0800
    [32m•[39m Engine revision 2994f7e1e6
    [32m•[39m Dart version 2.7.0

[33m[!][39m Android toolchain - develop for Android devices (Android SDK version 28.0.2)
    [32m•[39m Android SDK at /Users/xiwz/Library/Android/sdk
    [32m•[39m Android NDK location not configured (optional; useful for native profiling support)
    [31m✗[39m Flutter requires Android SDK 28 and the Android BuildTools 28.0.3
      To update using sdkmanager, run:
        "/Users/xiwz/Library/Android/sdk/tools/bin/sdkmanager" "platforms;android-28" "build-tools;28.0.3"
      or visit https://flutter.dev/setup/#android-setup for detailed instructions.
    [33m![39m Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses

[33m[!][39m Xcode - develop for iOS and macOS (Xcode 10.3)
    [32m•[39m Xcode at /Applications/Xcode.app/Contents/Developer
    [32m•[39m Xcode 10.3, Build version 10G8
    [31m✗[39m CocoaPods installed but not working.
        You appear to have CocoaPods installed but it is not working.
        This can happen if the version of Ruby that CocoaPods was installed with is different from the one being used to invoke it.
        This can usually be fixed by re-installing CocoaPods. For more info, see https://github.com/flutter/flutter/issues/14293.
      To re-install CocoaPods, run:
        sudo gem install cocoapods

[32m[✓][39m Android Studio (version 3.1)
    [32m•[39m Android Studio at /Applications/Android Studio.app/Contents
    [32m•[39m Flutter plugin version 28.0.1
    [32m•[39m Dart plugin version 173.4700
    [32m•[39m Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)

[32m[✓][39m VS Code (version 1.41.1)
    [32m•[39m VS Code at /Applications/Visual Studio Code.app/Contents
    [32m•[39m Flutter extension version 3.7.1

[32m[✓][39m Connected device (1 available)
    [32m•[39m iPhone Xʀ • 506B0475-A2E5-4FC6-A63B-2E1D88DF1A89 • ios • com.apple.CoreSimulator.SimRuntime.iOS-12-4 (simulator)

[33m![39m Doctor found issues in 2 categories.
```

**Comment by giansegato** [comment]
I had the exact same issue, right after upgrading Mac OS to Catalina (10.15.2) and Xcode from 11.0 to 11.3.

Re-installing CocoaPods with `sudo gem install cocoapods` fixed the problem.

**Comment by Zaynex** [comment]
it works.  @giansegato

**Comment by AliShubbar** [comment]
> I had the exact same issue, right after upgrading Mac OS to Catalina (10.15.2) and Xcode from 11.0 to 11.3.
> 
> Re-installing CocoaPods with `sudo gem install cocoapods` fixed the problem.

thank you, it's work

**Comment by jmagman** [comment]
Closing.
