### ISSUE TITLE
Problem after running a new project created by flutter (Failed to find target with hash string 'android-28')

### ISSUE THREAD

**Issue by tupizz** [flutter/flutter#47746]
Hello guys,
Yesterday I was configuring flutter and Android in my new laptop, but I had a few problems when I finish the configuration and run `flutter run`, which gives me message 

```
(...)
Build file '/home/tupizz/Desktop/work/flutter/test_project/android/build.gradle' line: 26
[        ] * What went wrong:
[        ] A problem occurred evaluating root project 'android'.
 > Failed to find target with hash string 'android-28' in: /home/tupizz/Android/Sdk
(...)
```

I already intalled all sdk version in android 28, and android 29, as follows the image description:

![Screenshot from 2019-12-24 13-22-30](https://user-images.githubusercontent.com/15824865/71419846-80e5bb80-2650-11ea-9e60-212e77d26a08.png)

**Target Platform:** Linux

## Logs

```
[  +20 ms] executing: [/home/tupizz/dev/flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[  +27 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[        ] d874596e38d3a63cc9a35e4b0615eb08396451d0
[        ] executing: [/home/tupizz/dev/flutter/] git describe --match v*.*.* --first-parent --long --tags
[  +14 ms] Exit code 0 from: git describe --match v*.*.* --first-parent --long --tags
[        ] v1.13.5-22-gd874596e3
[   +7 ms] executing: [/home/tupizz/dev/flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[   +4 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/master
[        ] executing: [/home/tupizz/dev/flutter/] git ls-remote --get-url origin
[   +4 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[  +51 ms] executing: [/home/tupizz/dev/flutter/] git rev-parse --abbrev-ref HEAD
[   +6 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] master
[  +28 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +3 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +26 ms] executing: /home/tupizz/Android/Sdk/platform-tools/adb devices -l
[   +8 ms] Exit code 0 from: /home/tupizz/Android/Sdk/platform-tools/adb devices -l
[        ] List of devices attached
           emulator-5554          device product:sdk_gphone_x86 model:Android_SDK_built_for_x86 device:generic_x86 transport_id:1
[  +22 ms] /home/tupizz/Android/Sdk/platform-tools/adb -s emulator-5554 shell getprop
[  +61 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[   +4 ms] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +2 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[ +193 ms] Generating /home/tupizz/Desktop/work/flutter/test_project/android/app/src/main/java/io/flutter/plugins/GeneratedPluginRegistrant.java
[  +25 ms] ro.hardware = ranchu
[  +24 ms] Using hardware rendering with device Android SDK built for x86. If you get graphics artifacts, consider enabling software rendering with "--enable-software-rendering".
[  +13 ms] Launching lib/main.dart on Android SDK built for x86 in debug mode...
[  +12 ms] executing: /home/tupizz/Android/Sdk/platform-tools/adb -s emulator-5554 shell -x logcat -v time -t 1
[  +20 ms] Exit code 0 from: /home/tupizz/Android/Sdk/platform-tools/adb -s emulator-5554 shell -x logcat -v time -t 1
[        ] --------- beginning of main
           12-24 13:18:01.768 E/GnssHAL_GnssInterface( 1752): gnssSvStatusCb: b: input svInfo.flags is 8
[   +1 ms] executing: /home/tupizz/Android/Sdk/platform-tools/adb -s emulator-5554 logcat -v time -T 12-24 13:18:01.768
[   +5 ms] executing: /home/tupizz/Android/Sdk/platform-tools/adb version
[  +17 ms] Android Debug Bridge version 1.0.41
           Version 29.0.5-5949299
           Installed as /home/tupizz/Android/Sdk/platform-tools/adb
[   +3 ms] executing: /home/tupizz/Android/Sdk/platform-tools/adb start-server
[   +7 ms] Building APK
[  +17 ms] Running Gradle task 'assembleDebug'...
[   +2 ms] gradle.properties already sets `android.enableR8`
[   +3 ms] Using gradle from /home/tupizz/Desktop/work/flutter/test_project/android/gradlew.
[   +1 ms] /home/tupizz/Desktop/work/flutter/test_project/android/gradlew mode: 33261 rwxr-xr-x.
[   +9 ms] executing: /opt/android-studio/jre/bin/java -version
[  +61 ms] Exit code 0 from: /opt/android-studio/jre/bin/java -version
[        ] openjdk version "1.8.0_202-release"
           OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
           OpenJDK 64-Bit Server VM (build 25.202-b49-5587405, mixed mode)
[   +3 ms] executing: [/home/tupizz/Desktop/work/flutter/test_project/android/] /home/tupizz/Desktop/work/flutter/test_project/android/gradlew -Pverbose=true -Ptarget=/home/tupizz/Desktop/work/flutter/test_project/lib/main.dart
-Ptrack-widget-creation=true -Pfilesystem-scheme=org-dartlang-root -Ptarget-platform=android-x86 assembleDebug
[+1632 ms] FAILURE: Build failed with an exception.
[   +3 ms] * Where:
[        ] Build file '/home/tupizz/Desktop/work/flutter/test_project/android/build.gradle' line: 26
[        ] * What went wrong:
[        ] A problem occurred evaluating root project 'android'.
[        ] > A problem occurred configuring project ':app'.
[        ]    > Failed to find target with hash string 'android-28' in: /home/tupizz/Android/Sdk
[        ] * Try:
[        ] Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
[        ] * Get more help at https://help.gradle.org
[        ] BUILD FAILED in 1s
[ +329 ms] Running Gradle task 'assembleDebug'... (completed in 2.0s)
[   +5 ms] "flutter run" took 2,574ms.
Gradle task assembleDebug failed with exit code 1

#0      throwToolExit (package:flutter_tools/src/base/common.dart:28:3)
#1      buildGradleApp (package:flutter_tools/src/android/gradle.dart:394:7)
#2      _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:75:64)
#3      _rootRunUnary (dart:async/zone.dart:1134:38)
#4      _CustomZone.runUnary (dart:async/zone.dart:1031:19)
#5      _FutureListener.handleValue (dart:async/future_impl.dart:140:18)
#6      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:682:45)
#7      Future._propagateToListeners (dart:async/future_impl.dart:711:32)
#8      Future._completeWithValue (dart:async/future_impl.dart:526:5)
#9      _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:34:15)
#10     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:293:13)
#11     _DefaultProcessUtils.stream (package:flutter_tools/src/base/process.dart)
#12     _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:75:64)
#13     _rootRunUnary (dart:async/zone.dart:1134:38)
#14     _CustomZone.runUnary (dart:async/zone.dart:1031:19)
#15     _FutureListener.handleValue (dart:async/future_impl.dart:140:18)
#16     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:682:45)
#17     Future._propagateToListeners (dart:async/future_impl.dart:711:32)
#18     Future._completeWithValue (dart:async/future_impl.dart:526:5)
#19     Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:556:7)
#20     _rootRun (dart:async/zone.dart:1126:13)
#21     _CustomZone.run (dart:async/zone.dart:1023:19)
#22     _CustomZone.runGuarded (dart:async/zone.dart:925:7)
#23     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:965:23)
#24     _microtaskLoop (dart:async/schedule_microtask.dart:43:21)
#25     _startMicrotaskLoop (dart:async/schedule_microtask.dart:52:5)
#26     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
#27     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:175:5)

```

```
Analyzing test_project...                                               
No issues found! (ran in 2.4s)
```

```
[✓] Flutter (Channel master, v1.13.6-pre.22, on Linux, locale en_US.UTF-8)
    • Flutter version 1.13.6-pre.22 at /home/tupizz/dev/flutter
    • Framework revision d874596e38 (16 hours ago), 2019-12-23 16:16:43 -0800
    • Engine revision 33813929e3
    • Dart version 2.8.0 (build 2.8.0-dev.0.0 886615d0f9)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /home/tupizz/Android/Sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • ANDROID_HOME = /home/tupizz/Android/Sdk
    • Java binary at: /opt/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Android Studio (version 3.5)
    • Android Studio at /opt/android-studio
    • Flutter plugin version 42.1.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] Connected device (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 10 (API 29) (emulator)

```

**Comment by wiseminds** [comment]
I would suggest checking out this stackoverflow post.
https://stackoverflow.com/questions/53886919/how-to-solve-failed-to-find-target-with-hash-string-android-27-in-c-users-ia

**Comment by jonahwilliams** [comment]
This is Gradle issue is not really flutter specific, and could happen if you have multiple Android SDKs installed or are have caches that are out of date.

for more information see issues https://stackoverflow.com/questions/33417537/failed-to-find-target-with-hash-string-android-23
