### ISSUE TITLE
Crash on Xcode 11.3 

### ISSUE THREAD

**Issue by AaydenGoh** [flutter/flutter#47786]
Hi,
i just installed the android studio with flutter in mac(10.14.6), created default flutter project and would like run in xcode 11.3, end up with exception.

also, i tried using terminal to create flutter project and run, it causes exception too
below is the flutter log. 

## command

flutter run

## exception

ProcessException: ProcessException: Process exited abnormally:
2019-12-25 21:31:48.480 xcodebuild[2266:33147] [MT] DVTPlugInLoading: Failed to load code for plug-in com.apple.dt.IDE.IDESwiftPackageSupport (/Applications/Xcode.app/Contents/PlugIns/IDESwiftPackageSupport.ideplugin), error = Error Domain=NSCocoaErrorDomain Code=3587 "dlopen_preflight(/Applications/Xcode.app/Contents/PlugIns/IDESwiftPackageSupport.ideplugin/Contents/MacOS/IDESwiftPackageSupport): Library not loaded: @rpath/libSwiftPM.dylib
  Referenced from: /Applications/Xcode.app/Contents/PlugIns/IDESwiftPackageSupport.ideplugin/Contents/Frameworks/SwiftPM.framework/Versions/A/SwiftPM
  Reason: no suitable image found.  Did find:
	/Applications/Xcode.app/Contents/PlugIns/IDESwiftPackageSupport.ideplugin/Contents/Frameworks/SwiftPM.framework/Versions/A/Libraries/libSwiftPM.dylib: unknown file type, first eight bytes: 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00" UserInfo={NSLocalizedFailureReason=The bundle is damaged or missing necessary resources., NSLocalizedRecoverySuggestion=Try reinstalling the bundle., NSFilePath=/Applications/Xcode.app/Contents/PlugIns/IDESwiftPackageSupport.ideplugin/Contents/MacOS/IDESwiftPackageSupport, NSDebugDescription=dlopen_preflight(/Applications/Xcode.app/Contents/PlugIns/IDESwiftPackageSupport.ideplugin/Contents/MacOS/IDESwiftPackageSupport): Library not loaded: @rpath/libSwiftPM.dylib
  Referenced from: /Applications/Xcode.app/Contents/PlugIns/IDESwiftPackageSupport.ideplugin/Contents/Frameworks/SwiftPM.framework/Versions/A/SwiftPM
  Reason: no suitable image found.  Did find:
	/Applications/Xcode.app/Contents/PlugIns/IDESwiftPackageSupport.ideplugin/Contents/Frameworks/SwiftPM.framework/Versions/A/Libraries/libSwiftPM.dylib: unknown file type, first eight bytes: 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00, NSBundlePath=/Applications/Xcode.app/Contents/PlugIns/IDESwiftPackageSupport.ideplugin, NSLocalizedDescription=The bundle “IDESwiftPackageSupport” couldn’t be loaded because it is damaged or missing necessary resources.}, dyldError = dlopen(/Applications/Xcode.app/Contents/PlugIns/IDESwiftPackageSupport.ideplugin/Contents/MacOS/IDESwiftPackageSupport, 0): Library not loaded: @rpath/libSwiftPM.dylib
  Referenced from: /Applications/Xcode.app/Contents/PlugIns/IDESwiftPackageSupport.ideplugin/Contents/Frameworks/SwiftPM.framework/Versions/A/SwiftPM
  Reason: no suitable image found.  Did find:
	/Applications/Xcode.app/Contents/PlugIns/IDESwiftPackageSupport.ideplugin/Contents/Frameworks/SwiftPM.framework/Versions/A/Libraries/libSwiftPM.dylib: unknown file type, first eight bytes: 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00
2019-12-25 21:31:48.480 xcodebuild[2266:33147] [MT] DVTPlugInExtensionFaulting: Failed to fire fault for extension Xcode.FileDataTypeDetector.SwiftPackageFileTypeDetector: Error Domain=DVTPlugInErrorDomain Code=2 "Loading a plug-in failed." UserInfo={DVTPlugInIdentifierErrorKey=com.apple.dt.IDE.IDESwiftPackageSupport, DVTPlugInExecutablePathErrorKey=/Applications/Xcode.app/Contents/PlugIns/IDESwiftPackageSupport.ideplugin/Contents/MacOS/IDESwiftPackageSupport, NSLocalizedRecoverySuggestion=The plug-in or one of its prerequisite plug-ins may be missing or damaged and may need to be reinstalled., DVTPlugInDYLDErrorMessageErrorKey=dlopen(/Applications/Xcode.app/Contents/PlugIns/IDESwiftPackageSupport.ideplugin/Contents/MacOS/IDESwiftPackageSupport, 0): Library not loaded: @rpath/libSwiftPM.dylib
  Referenced from: /Applications/Xcode.app/Contents/PlugIns/IDESwiftPackageSupport.ideplugin/Contents/Frameworks/SwiftPM.framework/Versions/A/SwiftPM
  Reason: no suitable image found.  Did find:
	/Applications/Xcode.app/Contents/PlugIns/IDESwiftPackageSupport.ideplugin/Contents/Frameworks/SwiftPM.framework/Versions/A/Libraries/libSwiftPM.dylib: unknown file type, first eight bytes: 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00, NSLocalizedDescription=Loading a plug-in failed., NSFilePath=/Applications/Xcode.app/Contents/PlugIns/IDESwiftPackageSupport.ideplugin, NSLocalizedFailureReason=The plug-in “com.apple.dt.IDE.IDESwiftPackageSupport” at path “/Applications/Xcode.app/Contents/PlugIns/IDESwiftPackageSupport.ideplugin” could not be loaded.  The plug-in or one of its prerequisite plug-ins may be missing or damaged., NSUnderlyingError=0x7f944a668350 {Error Domain=NSCocoaErrorDomain Code=3587 "dlopen_preflight(/Applications/Xcode.app/Contents/PlugIns/IDESwiftPackageSupport.ideplugin/Contents/MacOS/IDESwiftPackageSupport): Library not loaded: @rpath/libSwiftPM.dylib
  Referenced from: /Applications/Xcode.app/Contents/PlugIns/IDESwiftPackageSupport.ideplugin/Contents/Frameworks/SwiftPM.framework/Versions/A/SwiftPM
  Reason: no suitable image found.  Did find:
	/Applications/Xcode.app/Contents/PlugIns/IDESwiftPackageSupport.ideplugin/Contents/Frameworks/SwiftPM.framework/Versions/A/Libraries/libSwiftPM.dylib: unknown file type, first eight bytes: 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00" UserInfo={NSLocalizedFailureReason=The bundle is damaged or missing necessary resources., NSLocalizedRecoverySuggestion=Try reinstalling the bundle., NSFilePath=/Applications/Xcode.app/Contents/PlugIns/IDESwiftPackageSupport.ideplugin/Contents/MacOS/IDESwiftPackageSupport, NSDebugDescription=dlopen_preflight(/Applications/Xcode.app/Contents/PlugIns/IDESwiftPackageSupport.ideplugin/Contents/MacOS/IDESwiftPackageSupport): Library not loaded: @rpath/libSwiftPM.dylib
  Referenced from: /Applications/Xcode.app/Contents/PlugIns/IDESwiftPackageSupport.ideplugin/Contents/Frameworks/SwiftPM.framework/Versions/A/SwiftPM
  Reason: no suitable image found.  Did find:
	/Applications/Xcode.app/Contents/PlugIns/IDESwiftPackageSupport.ideplugin/Contents/Frameworks/SwiftPM.framework/Versions/A/Libraries/libSwiftPM.dylib: unknown file type, first eight bytes: 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00, NSBundlePath=/Applications/Xcode.app/Contents/PlugIns/IDESwiftPackageSupport.ideplugin, NSLocalizedDescription=The bundle “IDESwiftPackageSupport” couldn’t be loaded because it is damaged or missing necessary resources.}}}
** INTERNAL ERROR: Uncaught exception **
Uncaught Exception: Error getting value for key 'detectorClass' of extension 'Xcode.FileDataTypeDetector.SwiftPackageFileTypeDetector' in plug-in 'com.apple.dt.IDE.IDESwiftPackageSupport': Error Domain=DVTPlugInErrorDomain Code=2 "Loading a plug-in failed." UserInfo={DVTPlugInIdentifierErrorKey=com.apple.dt.IDE.IDESwiftPackageSupport, DVTPlugInExecutablePathErrorKey=/Applications/Xcode.app/Contents/PlugIns/IDESwiftPackageSupport.ideplugin/Contents/MacOS/IDESwiftPackageSupport, NSLocalizedRecoverySuggestion=The plug-in or one of its prerequisite plug-ins may be missing or damaged and may need to be reinstalled., DVTPlugInDYLDErrorMessageErrorKey=dlopen(/Applications/Xcode.app/Contents/PlugIns/IDESwiftPackageSupport.ideplugin/Contents/MacOS/IDESwiftPackageSupport, 0): Library not loaded: @rpath/libSwiftPM.dylib
  Referenced from: /Applications/Xcode.app/Contents/PlugIns/IDESwiftPackageSupport.ideplugin/Contents/Frameworks/SwiftPM.framework/Versions/A/SwiftPM
  Reason: no suitable image found.  Did find:
	/Applications/Xcode.app/Contents/PlugIns/IDESwiftPackageSupport.ideplugin/Contents/Frameworks/SwiftPM.framework/Versions/A/Libraries/libSwiftPM.dylib: unknown file type, first eight bytes: 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00, NSLocalizedDescription=Loading a plug-in failed., NSFilePath=/Applications/Xcode.app/Contents/PlugIns/IDESwiftPackageSupport.ideplugin, NSLocalizedFailureReason=The plug-in “com.apple.dt.IDE.IDESwiftPackageSupport” at path “/Applications/Xcode.app/Contents/PlugIns/IDESwiftPackageSupport.ideplugin” could not be loaded.  The plug-in or one of its prerequisite plug-ins may be missing or damaged., NSUnderlyingError=0x7f944a668350 {Error Domain=NSCocoaErrorDomain Code=3587 "dlopen_preflight(/Applications/Xcode.app/Contents/PlugIns/IDESwiftPackageSupport.ideplugin/Contents/MacOS/IDESwiftPackageSupport): Library not loaded: @rpath/libSwiftPM.dylib
  Referenced from: /Applications/Xcode.app/Contents/PlugIns/IDESwiftPackageSupport.ideplugin/Contents/Frameworks/SwiftPM.framework/Versions/A/SwiftPM
  Reason: no suitable image found.  Did find:
	/Applications/Xcode.app/Contents/PlugIns/IDESwiftPackageSupport.ideplugin/Contents/Frameworks/SwiftPM.framework/Versions/A/Libraries/libSwiftPM.dylib: unknown file type, first eight bytes: 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00" UserInfo={NSLocalizedFailureReason=The bundle is damaged or missing necessary resources., NSLocalizedRecoverySuggestion=Try reinstalling the bundle., NSFilePath=/Applications/Xcode.app/Contents/PlugIns/IDESwiftPackageSupport.ideplugin/Contents/MacOS/IDESwiftPackageSupport, NSDebugDescription=dlopen_preflight(/Applications/Xcode.app/Contents/PlugIns/IDESwiftPackageSupport.ideplugin/Contents/MacOS/IDESwiftPackageSupport): Library not loaded: @rpath/libSwiftPM.dylib
  Referenced from: /Applications/Xcode.app/Contents/PlugIns/IDESwiftPackageSupport.ideplugin/Contents/Frameworks/SwiftPM.framework/Versions/A/SwiftPM
  Reason: no suitable image found.  Did find:
	/Applications/Xcode.app/Contents/PlugIns/IDESwiftPackageSupport.ideplugin/Contents/Frameworks/SwiftPM.framework/Versions/A/Libraries/libSwiftPM.dylib: unknown file type, first eight bytes: 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00, NSBundlePath=/Applications/Xcode.app/Contents/PlugIns/IDESwiftPackageSupport.ideplugin, NSLocalizedDescription=The bundle “IDESwiftPackageSupport” couldn’t be loaded because it is damaged or missing necessary resources.}}}
Stack:
  0   __exceptionPreprocess (in CoreFoundation)
  1   objc_exception_throw (in libobjc.A.dylib)
  2   -[DVTExtension valueForKey:error:] (in DVTFoundation)
  3   +[DVTFileDataType _findMatchingTypeUsingDetectors:givenCurrentMatchingType:filePath:allowCustomDetectors:error:] (in DVTFoundation)
  4   +[DVTFileDataType _fileDataTypeForFileAtPath:consideringFileContent:error:] (in DVTFoundation)
  5   +[DVTFileDataType fileDataTypeForFilePath:error:] (in DVTFoundation)
  6   -[Xcode3CommandLineBuildTool _resolveInputOptionsWithTimingSection:] (in Xcode3Core)
  7   -[Xcode3CommandLineBuildTool run] (in Xcode3Core)
  8   main (in xcodebuild)
  9   start (in libdyld.dylib)
  Command: /usr/bin/xcodebuild -list

```
#0      RunResult.throwException (package:flutter_tools/src/base/process.dart:141:5)
#1      _DefaultProcessUtils.run (package:flutter_tools/src/base/process.dart:275:19)
<asynchronous suspension>
#2      XcodeProjectInterpreter.getInfo (package:flutter_tools/src/ios/xcodeproj.dart:342:49)
#3      buildXcodeProject (package:flutter_tools/src/ios/mac.dart:281:70)
#4      IOSSimulator._setupUpdatedApplicationBundle (package:flutter_tools/src/ios/simulators.dart:436:48)
<asynchronous suspension>
#5      IOSSimulator.startApp (package:flutter_tools/src/ios/simulators.dart:354:15)
#6      FlutterDevice.runHot (package:flutter_tools/src/resident_runner.dart:450:54)
#7      _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:73:64)
#8      _rootRunUnary (dart:async/zone.dart:1134:38)
#9      _CustomZone.runUnary (dart:async/zone.dart:1031:19)
#10     _FutureListener.handleValue (dart:async/future_impl.dart:139:18)
#11     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:680:45)
#12     Future._propagateToListeners (dart:async/future_impl.dart:709:32)
#13     Future._completeWithValue (dart:async/future_impl.dart:524:5)
#14     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:32:15)
#15     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:290:13)
#16     ApplicationPackageFactory.getPackageForPlatform (package:flutter_tools/src/application_package.dart)
#17     _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:73:64)
#18     _rootRunUnary (dart:async/zone.dart:1134:38)
#19     _CustomZone.runUnary (dart:async/zone.dart:1031:19)
#20     _FutureListener.handleValue (dart:async/future_impl.dart:139:18)
#21     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:680:45)
#22     Future._propagateToListeners (dart:async/future_impl.dart:709:32)
#23     Future._completeWithValue (dart:async/future_impl.dart:524:5)
#24     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:32:15)
#25     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:290:13)
#26     BuildableIOSApp.fromProject (package:flutter_tools/src/application_package.dart)
#27     _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:73:64)
#28     _rootRunUnary (dart:async/zone.dart:1134:38)
#29     _CustomZone.runUnary (dart:async/zone.dart:1031:19)
#30     _FutureListener.handleValue (dart:async/future_impl.dart:139:18)
#31     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:680:45)
#32     Future._propagateToListeners (dart:async/future_impl.dart:709:32)
#33     Future._completeWithValue (dart:async/future_impl.dart:524:5)
#34     Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:554:7)
#35     _rootRun (dart:async/zone.dart:1126:13)
#36     _CustomZone.run (dart:async/zone.dart:1023:19)
#37     _CustomZone.runGuarded (dart:async/zone.dart:925:7)
#38     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:965:23)
#39     _microtaskLoop (dart:async/schedule_microtask.dart:43:21)
#40     _startMicrotaskLoop (dart:async/schedule_microtask.dart:52:5)
#41     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
#42     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:175:5)
```

## flutter doctor

```
[32m[✓][39m Flutter (Channel stable, v1.12.13+hotfix.5, on Mac OS X 10.14.6 18G103,
    locale en-GB)
    [32m•[39m Flutter version 1.12.13+hotfix.5 at /Users/macbook/Developer/flutter
    [32m•[39m Framework revision 27321ebbad (2 weeks ago), 2019-12-10 18:15:01 -0800
    [32m•[39m Engine revision 2994f7e1e6
    [32m•[39m Dart version 2.7.0

[32m[✓][39m Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    [32m•[39m Android SDK at /Users/macbook/Library/Android/sdk
    [32m•[39m Android NDK location not configured (optional; useful for native profiling
      support)
    [32m•[39m Platform android-29, build-tools 29.0.2
    [32m•[39m Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    [32m•[39m Java version OpenJDK Runtime Environment (build
      1.8.0_202-release-1483-b49-5587405)
    [32m•[39m All Android licenses accepted.

[32m[✓][39m Xcode - develop for iOS and macOS (Xcode 11.3)
    [32m•[39m Xcode at /Applications/Xcode.app/Contents/Developer
    [32m•[39m Xcode 11.3, Build version 11C29
    [32m•[39m CocoaPods version 1.8.4

[32m[✓][39m Android Studio (version 3.5)
    [32m•[39m Android Studio at /Applications/Android Studio.app/Contents
    [32m•[39m Flutter plugin version 42.1.1
    [32m•[39m Dart plugin version 191.8593
    [32m•[39m Java version OpenJDK Runtime Environment (build
      1.8.0_202-release-1483-b49-5587405)

[32m[✓][39m Connected device (1 available)
    [32m•[39m iPhone 11 Pro Max • 4B0618E4-B9D1-43E1-BF18-164349F4244B • ios •
      com.apple.CoreSimulator.SimRuntime.iOS-13-3 (simulator)

[32m•[39m No issues found!
```

**Comment by AaydenGoh** [comment]
Issue no longer happens in my mac, after i re-install everything again.

Thanks.
