### ISSUE TITLE
'dart:ui/text.dart': Failed assertion: line 1372: '<optimized out>': is not true. is fired repeatedtly every second

### ISSUE THREAD

**Issue by marcelser** [flutter/flutter#47790]
## Steps to Reproduce
I have a Widget an asyncloader which shows a listview with search field of type TextField with a debounce static method that fires update of listView which causes the following error when the debounce fires `'dart:ui/text.dart': Failed assertion: line 1372: '<optimized out>': is not true.` every 1  
 second.

Here are the relevant parts.

stateful class with relevant parts (I can post complete class if desired but I have removed editing widget as it's not connected to this error):
<details>
	<summary>code sample</summary>

 ```dart 
class ProductsScreenState extends State<ProductsScreen> {
  final GlobalKey<AsyncLoaderState> asyncLoaderState =
      new GlobalKey<AsyncLoaderState>();

  String searchFilter = null;

  TextEditingController editingController = TextEditingController();
   void _onSearchChanged(String searchValue) {
    setState(() {
      searchFilter = searchValue;
    });
    asyncLoaderState.currentState.reloadState();
  }

  @override
  Widget build(BuildContext context) {
    var _asyncLoader = new AsyncLoader(
      key: asyncLoaderState,
      initState: () async => await getProducts(context, filter: searchFilter),
      renderLoad: () => Center(child: new CircularProgressIndicator()),
      renderError: ([error]) => getNoConnectionWidget(),
      renderSuccess: ({data}) => getListView(
          data != null ? data.asMap() : new Map<int, Product>(), context),
    );

    return new PlatformScaffold(
      appBar: buildAppBar("Produkte", context),
      body: GestureDetector(
          onTap: () {
            FocusScope.of(context).unfocus();
          },
          child: new Center(child: _asyncLoader)
      ),
    );
  } 

 Widget getListView(Map<int, Product> products, BuildContext context) {
    return Stack(children: <Widget>[
      Container(
          child: Column(
        children: <Widget>[
          TextField(
            autofocus: true,
            controller: editingController,
            decoration: InputDecoration(
                labelText: "Suche",
                hintText: "Suche",
                prefixIcon: Icon(Icons.search)),

                onChanged: (val) => debounce(const Duration(milliseconds: 1000), _onSearchChanged, [val]),
          ),
          Expanded(child: ListView.builder(
            itemCount: products.length,
            itemBuilder: (context, index) {
              return Slidable(
                child: Card(
                  //                           <-- Card widget
                  child: ListTile(
                      title: Text(products[index].getName),
                      trailing: Icon(Icons.edit),
                      onTap: () async {
                        await Navigator.push(
                            context,
                            MaterialPageRoute(
                              builder: (context) => ProductEditScreen(),
                              settings:
                                  RouteSettings(arguments: products[index]),
                            ));
                        asyncLoaderState.currentState.reloadState();
                      }),
                ),
                actionPane: SlidableDrawerActionPane(),
                actionExtentRatio: 0.18,
                actions: <Widget>[
                  IconSlideAction(
                    caption: 'Löschen',
                    color: Colors.red,
                    icon: Icons.delete,
                    onTap: () async {
                      if (await confirmDialog(context, "Warnung", "Möchten Sie das Produkt und allen Vorräte dieses Produkts wirklich löschen?")) {
                        await deleteProduct(products[index], context);
                        asyncLoaderState.currentState.reloadState();
                      }
                    },
                  ),
                ],
              );
            },
          )),
        ],
      )),
      Container(
        alignment: Alignment.bottomRight,
        padding: EdgeInsets.all(20.0),
        width: MediaQuery.of(context).size.width,
        height: MediaQuery.of(context).size.height,
        child: FloatingActionButton(
          onPressed: () async {
            await Navigator.push(
                context,
                MaterialPageRoute(
                  builder: (context) => ProductEditScreen(),
                  settings:
                      RouteSettings(arguments: new Product(id: 0, name: '')),
                ));
            asyncLoaderState.currentState.reloadState();
          },
          tooltip: 'Neues Produkt erstellen',
          child: Icon(Icons.add),
        ),
      )
    ]);
  }
}
```

</details>

debounce static class:
<details>
	<summary>code sample</summary>

```dart
Map<Function, Timer> _timeouts = {};
void debounce(Duration timeout, Function target, [List arguments = const []]) {
  if (_timeouts.containsKey(target)) {
    _timeouts[target].cancel();
  }

  Timer timer = Timer(timeout, () {
    Function.apply(target, arguments);
  });

  _timeouts[target] = timer;
}

```

</details>

1. create widget like above
2. type some search value in TextField
3. when debounce fires, the following error appears every 1 sec (probably debounce value) and TextField content is not showing. When you click on TextField to get focus the text appears but the repeating error firing goes on.

**Target Platform:** Android API 28 and up
**Target OS version/browser:** Windows 10 Pro on latest flutter stable with Android studio
**Devices:** AVD AOSP API 28 Virtual Device

## Logs
<details>
	<summary>logs</summary>

```bash

════════ Exception caught by rendering library ═════════════════════════════════════════════════════
The following assertion was thrown during paint():
'dart:ui/text.dart': Failed assertion: line 1372: '<optimized out>': is not true.


Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=BUG.md

The relevant error-causing widget was: 
  TextField file:///C:/Users/marc_laptop/StudioProjects/cupboard_manager_ui/lib/ui/productScreen.dart:66:11
When the exception was thrown, this was the stack: 
#2      new TextPosition (dart:ui/text.dart:1372:15)
#3      RenderEditable._updateSelectionExtentsVisibility (package:flutter/src/rendering/editable.dart:367:7)
#4      RenderEditable._paintContents (package:flutter/src/rendering/editable.dart:1956:7)
#5      RenderEditable.paint (package:flutter/src/rendering/editable.dart:2012:7)
#6      RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2219:7)
...
The following RenderObject was being processed when the exception was fired: RenderEditable#a286b relayoutBoundary=up21
...  parentData: <none> (can use size)
...  constraints: BoxConstraints(w=312.0, 0.0<=h<=Infinity)
...  size: Size(312.0, 19.0)
...  cursorColor: Color(0x004285f4)
...  showCursor: ValueNotifier<bool>#df665(true)
...  maxLines: 1
...  minLines: null
...  selectionColor: Color(0xff90caf9)
...  textScaleFactor: 1.0
...  locale: en_US
...  selection: TextSelection(baseOffset: 3, extentOffset: 3, affinity: null, isDirectional: false)
...  offset: ScrollPositionWithSingleContext#869a0(offset: 0.0, range: 0.0..0.0, viewport: 312.0, ScrollableState, ClampingScrollPhysics, IdleScrollActivity#9f8b5, ScrollDirection.idle)
RenderObject: RenderEditable#a286b relayoutBoundary=up21
  parentData: <none> (can use size)
  constraints: BoxConstraints(w=312.0, 0.0<=h<=Infinity)
  size: Size(312.0, 19.0)
  cursorColor: Color(0x004285f4)
  showCursor: ValueNotifier<bool>#df665(true)
  maxLines: 1
  minLines: null
  selectionColor: Color(0xff90caf9)
  textScaleFactor: 1.0
  locale: en_US
  selection: TextSelection(baseOffset: 3, extentOffset: 3, affinity: null, isDirectional: false)
  offset: ScrollPositionWithSingleContext#869a0(offset: 0.0, range: 0.0..0.0, viewport: 312.0, ScrollableState, ClampingScrollPhysics, IdleScrollActivity#9f8b5, ScrollDirection.idle)
...  text: TextSpan
...    debugLabel: (englishLike subhead 2014).merge(blackMountainView subhead)
...    inherit: false
...    color: Color(0xdd000000)
...    family: Roboto
...    size: 16.0
...    weight: 400
...    baseline: alphabetic
...    decoration: TextDecoration.none
...    : TextSpan
...      ""
...    : TextSpan
...      debugLabel: ((englishLike subhead 2014).merge(blackMountainView subhead)).merge(unknown)
...      inherit: false
...      color: Color(0xdd000000)
...      family: Roboto
...      size: 16.0
...      weight: 400
...      baseline: alphabetic
...      decoration: TextDecoration.underline
...      "emm"
...    : TextSpan
...      ""
════════════════════════════════════════════════════════════════════════════════════════════════════

════════ (2) Exception caught by rendering library ═════════════════════════════════════════════════
'dart:ui/text.dart': Failed assertion: line 1372: '<optimized out>': is not true.
The relevant error-causing widget was: 
  TextField file:///C:/Users/marc_laptop/StudioProjects/cupboard_manager_ui/lib/ui/productScreen.dart:66:11
════════════════════════════════════════════════════════════════════════════════════════════════════

════════ (3) Exception caught by rendering library ═════════════════════════════════════════════════
'dart:ui/text.dart': Failed assertion: line 1372: '<optimized out>': is not true.
The relevant error-causing widget was: 
  TextField file:///C:/Users/marc_laptop/StudioProjects/cupboard_manager_ui/lib/ui/productScreen.dart:66:11
════════════════════════════════════════════════════════════════════════════════════════════════════

════════ (4) Exception caught by rendering library ═════════════════════════════════════════════════
'dart:ui/text.dart': Failed assertion: line 1372: '<optimized out>': is not true.
The relevant error-causing widget was: 
  TextField file:///C:/Users/marc_laptop/StudioProjects/cupboard_manager_ui/lib/ui/productScreen.dart:66:11
════════════════════════════════════════════════════════════════════════════════════════════════════

════════ (5) Exception caught by rendering library ═════════════════════════════════════════════════
'dart:ui/text.dart': Failed assertion: line 1372: '<optimized out>': is not true.
The relevant error-causing widget was: 
  TextField file:///C:/Users/marc_laptop/StudioProjects/cupboard_manager_ui/lib/ui/productScreen.dart:66:11
════════════════════════════════════════════════════════════════════════════════════════════════════
```

</details>

flutter doctor -v
```console
[√] Flutter (Channel stable, v1.12.13+hotfix.5, on Microsoft Windows [Version 10.0.18362.535], locale de-CH)
    • Flutter version 1.12.13+hotfix.5 at C:\src\flutter
    • Framework revision 27321ebbad (2 weeks ago), 2019-12-10 18:15:01 -0800
    • Engine revision 2994f7e1e6
    • Dart version 2.7.0


[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at C:\Users\marc_laptop\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)
    • All Android licenses accepted.

[√] Android Studio (version 3.5)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 42.1.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)

[√] Connected device (1 available)
    • AOSP on IA Emulator • emulator-5554 • android-x86 • Android 9 (API 28) (emulator)

• No issues found!

```

**Comment by jonahwilliams** [comment]
The failing assertion is a null text affinity: https://github.com/flutter/engine/blob/master/lib/ui/text.dart#L1372

This could happen if the text selection has a null affinity in https://github.com/flutter/flutter/blob/b011ea546827330c785fce56a10189230bcb334e/packages/flutter/lib/src/rendering/editable.dart#L383



> stateful class with relevant parts (I can post complete class if desired but I have removed editing widget as it's not connected to this error):

It seems like it would be given the errors above, specifically: file:///C:/Users/marc_laptop/StudioProjects/cupboard_manager_ui/lib/ui/productScreen.dart:66:11

Are you creating a text selection manually with a null affinity?

**Comment by defint** [comment]
Widget that reproduces the problem: https://gist.github.com/defint/7c42ff3c4149d3345c84c32bbe6abd05

Steps:
1) input "aa"
2) lost focus from the input
3) validation message "xxx" should be shown
4) tap on the textfield
5) have a message: 'dart:ui/text.dart': Failed assertion: line 1372: '<optimized out>': is not true.

**Comment by marcelser** [comment]
> Widget that reproduces the problem: https://gist.github.com/defint/7c42ff3c4149d3345c84c32bbe6abd05
> 
> Steps:
> 
> 1. input "aa"
> 2. lost focus from the input
> 3. validation message "xxx" should be shown
> 4. tap on the textfield
> 5. have a message: 'dart:ui/text.dart': Failed assertion: line 1372: '': is not true.

Thanks for your widget It's much simpler then mine but I think it shows same problem as my widget also looses focus when debounce static is fired and then I get the message from Step 5 every second repeatedly. In my case it even seems to have some neverending loop from the debounce (although I don't see how it could happen) maybe when.

**Comment by marcelser** [comment]
> Widget that reproduces the problem: https://gist.github.com/defint/7c42ff3c4149d3345c84c32bbe6abd05
> 
> Steps:
> 
> 1. input "aa"
> 2. lost focus from the input
> 3. validation message "xxx" should be shown
> 4. tap on the textfield
> 5. have a message: 'dart:ui/text.dart': Failed assertion: line 1372: '': is not true.

**Comment by marcelser** [comment]
> It seems like it would be given the errors above, specifically: file:///C:/Users/marc_laptop/StudioProjects/cupboard_manager_ui/lib/ui/productScreen.dart:66:11 
> Are you creating a text selection manually with a null affinity?

I'm not doing anything with text selection or affinity at all. I don't even know what affinity was until now.  The error happens inside the Textfield of getListView clicking on the error message
file:///C:/Users/marc_laptop/StudioProjects/cupboard_manager_ui/lib/ui/productScreen.dart:66:11 in android studio shows the line which starts with "TextField(" actually this part here:
```
TextField(
           autofocus: true,
           controller: editingController,
           decoration: InputDecoration(
               labelText: "Suche",
               hintText: "Suche",
               prefixIcon: Icon(Icons.search)),

               onChanged: (val) => debounce(const Duration(milliseconds: 1000), _onSearchChanged, [val]),
         ),
```

**Comment by iapicca** [comment]
Hi @marcelser 
I see there's an open [issue ](47343) addressing the case you described.
Please follow up on that issue,
I'm closing the current one as duplicate.
If you disagree please write in the comments
and I will reopen it.
Thank you
