### ISSUE TITLE
'dart:ui/text.dart': Failed assertion: line 1372: '<optimized out>': is not true error 

### ISSUE THREAD

**Issue by Maheshkumar660** [flutter/flutter#47810]
## Steps to Reproduce

```
 final mobileNumberField=TextField(
      controller: myPhoneNumberController,
      obscureText: false,
      style: style,
      decoration: InputDecoration(
          contentPadding: EdgeInsets.fromLTRB(20.0, 15.0, 20.0, 15.0),
          hintText: "Mobile number",
          border: OutlineInputBorder(borderRadius: BorderRadius.circular(32.0))),
    );
```

**Target Platform:**
**Target OS version/browser:**
**Devices:**

## Logs
The relevant error-causing widget was: 
```
  TextField file:///F:/Flutter_bookkizee/bookkizee/bookkizee/lib/login_page.dart:66:29
When the exception was thrown, this was the stack: 
#2      new TextPosition (dart:ui/text.dart:1372:15)
#3      RenderEditable._updateSelectionExtentsVisibility (package:flutter/src/rendering/editable.dart:367:7)
#4      RenderEditable._paintContents (package:flutter/src/rendering/editable.dart:1956:7)
#5      RenderEditable.paint (package:flutter/src/rendering/editable.dart:2012:7)
#6      RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2219:7)
...
The following RenderObject was being processed when the exception was fired: RenderEditable#0e9ab relayoutBoundary=up31
...  parentData: <none> (can use size)
...  constraints: BoxConstraints(w=210.8, 0.0<=h<=15.0)
...  size: Size(210.8, 15.0)
...  cursorColor: Color(0x004285f4)
...  showCursor: ValueNotifier<bool>#6359f(true)
...  maxLines: 1
...  minLines: null
...  selectionColor: Color(0xff90caf9)
...  textScaleFactor: 1.0
...  locale: en_US
...  selection: TextSelection(baseOffset: 10, extentOffset: 10, affinity: null, isDirectional: false)
...  offset: ScrollPositionWithSingleContext#10a4c(offset: 0.0, range: 0.0..0.0, viewport: 210.8, ScrollableState, ClampingScrollPhysics, IdleScrollActivity#e8b58, ScrollDirection.idle)
  text: TextSpan
    debugLabel: ((englishLike subhead 2014).merge(blackMountainView subhead)).merge(unknown)
    inherit: false
    color: Color(0xdd000000)
    family: Montserrat
    size: 20.0
    weight: 400
    baseline: alphabetic
    decoration: TextDecoration.none
    "1234567890"
RenderObject: RenderEditable#0e9ab relayoutBoundary=up31
  parentData: <none> (can use size)
  constraints: BoxConstraints(w=210.8, 0.0<=h<=15.0)
  size: Size(210.8, 15.0)
  cursorColor: Color(0x004285f4)
  showCursor: ValueNotifier<bool>#6359f(true)
  maxLines: 1
  minLines: null
  selectionColor: Color(0xff90caf9)
  textScaleFactor: 1.0
  locale: en_US
  selection: TextSelection(baseOffset: 10, extentOffset: 10, affinity: null, isDirectional: false)
  offset: ScrollPositionWithSingleContext#10a4c(offset: 0.0, range: 0.0..0.0, viewport: 210.8, ScrollableState, ClampingScrollPhysics, IdleScrollActivity#e8b58, ScrollDirection.idle)
  text: TextSpan
    debugLabel: ((englishLike subhead 2014).merge(blackMountainView subhead)).merge(unknown)
    inherit: false
    color: Color(0xdd000000)
    family: Montserrat
    size: 20.0
    weight: 400
    baseline: alphabetic
    decoration: TextDecoration.none
    "1234567890"
```

**Comment by iapicca** [comment]
Hi @Maheshkumar660 
I see there's an open [issue ](47790) addressing the case you described.
Please follow up on that issue,
I'm closing the current one as duplicate.
If you disagree please write in the comments
and I will reopen it.
Thank you
