### ISSUE TITLE
flutter local notification null error 

### ISSUE THREAD

**Issue by ernestsheldon** [flutter/flutter#47844]
Using `createScheduledNotification()` and `showNotification()` works but using 
`createDailyNotification() `gives the following error.

<details>
	<summary>logs</summary>

```bash 
Performing hot reload...
Syncing files to device Android SDK built for x86...
Reloaded 5 of 558 libraries in 333ms.
E/MethodChannel#dexterous.com/flutter/local_notifications( 6909): Failed to handle method call
E/MethodChannel#dexterous.com/flutter/local_notifications( 6909): java.lang.NullPointerException: Attempt to invoke virtual method 'long java.lang.Long.longValue()' on a null object reference
E/MethodChannel#dexterous.com/flutter/local_notifications( 6909): 	at com.dexterous.flutterlocalnotifications.FlutterLocalNotificationsPlugin.repeatNotification(FlutterLocalNotificationsPlugin.java:305)
E/MethodChannel#dexterous.com/flutter/local_notifications( 6909): 	at com.dexterous.flutterlocalnotifications.FlutterLocalNotificationsPlugin.repeat(FlutterLocalNotificationsPlugin.java:743)
E/MethodChannel#dexterous.com/flutter/local_notifications( 6909): 	at com.dexterous.flutterlocalnotifications.FlutterLocalNotificationsPlugin.onMethodCall(FlutterLocalNotificationsPlugin.java:700)
E/MethodChannel#dexterous.com/flutter/local_notifications( 6909): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:231)
E/MethodChannel#dexterous.com/flutter/local_notifications( 6909): 	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:93)
E/MethodChannel#dexterous.com/flutter/local_notifications( 6909): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:642)
E/MethodChannel#dexterous.com/flutter/local_notifications( 6909): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/MethodChannel#dexterous.com/flutter/local_notifications( 6909): 	at android.os.MessageQueue.next(MessageQueue.java:336)
E/MethodChannel#dexterous.com/flutter/local_notifications( 6909): 	at android.os.Looper.loop(Looper.java:174)
E/MethodChannel#dexterous.com/flutter/local_notifications( 6909): 	at android.app.ActivityThread.main(ActivityThread.java:7356)
E/MethodChannel#dexterous.com/flutter/local_notifications( 6909): 	at java.lang.reflect.Method.invoke(Native Method)
E/MethodChannel#dexterous.com/flutter/local_notifications( 6909): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
E/MethodChannel#dexterous.com/flutter/local_notifications( 6909): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
I/flutter ( 6909): PlatformException(error, Attempt to invoke virtual method 'long java.lang.Long.longValue()' on a null object reference, null)
I/flutter ( 6909): Instance of 'Time'Instance of 'AndroidNotificationDetails'Instance of 'IOSNotificationDetails'Instance of 'NotificationDetails'
I/flutter ( 6909): notification payload: 

See code below and I have no errors running flutter doctor -v!
```

</details>

<details>
	<summary>code sample</summary>

```dart 
import 'dart:async';
import 'dart:ui';
import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';
import 'package:flutter_local_notifications/flutter_local_notifications.dart';
FlutterLocalNotificationsPlugin flutterLocalNotificationsPlugin;
class NotificationHomePage extends StatefulWidget {
  @override
  _NotificationHomePageState createState() => _NotificationHomePageState();
}
class _NotificationHomePageState extends State<NotificationHomePage> {
  FlutterLocalNotificationsPlugin flutterLocalNotificationsPlugin =
      FlutterLocalNotificationsPlugin();
  var initializationSettingsAndroid;
  var initializationSettingsIOS;
  var initializationSettings;
  var androidPlatformChannelSpecifics = AndroidNotificationDetails(
      'repeatDailyAtTime_channel_id_ielts',
      'repeatDailyAtTime_channel_name_ielts',
      'repeatDailyAtTime_description_ielts');
  var iOSPlatformChannelSpecifics = IOSNotificationDetails();
  var platformChannelSpecifics;
  @override
  void initState() {
    // TODO: implement initState
    super.initState();
    initializationSettingsAndroid = AndroidInitializationSettings('app_icon');
    initializationSettingsIOS = IOSInitializationSettings(
        onDidReceiveLocalNotification: onDidReceiveLocalNotification);
    initializationSettings = InitializationSettings(
        initializationSettingsAndroid, initializationSettingsIOS);
    platformChannelSpecifics = NotificationDetails(
        androidPlatformChannelSpecifics, iOSPlatformChannelSpecifics);
    flutterLocalNotificationsPlugin
        .initialize(
      initializationSettings,
      onSelectNotification: onSelectNotification,
    )
        .then((init) {
      setupNotification();
    });
  }
  Future onSelectNotification(String payload) async {
    if (payload != null) {
      debugPrint('notification payload: ' + payload);
    } else {
      print('null payload');
    }
  }
  Future onDidReceiveLocalNotification(
      int id, String title, String body, String payload) async {
    // display a dialog with the notification details, tap ok to go to another page
    showDialog(
        context: context,
        builder: (context) => AlertDialog(
              content: Text('dont forget'),
              actions: [
                FlatButton(
                  child: Text('Ok'),
                  onPressed: () {
                    Navigator.of(context).pop();
                  },
                ),
              ],
            ));
  }
  String _toTwoDigitString(int value) {
    return value.toString().padLeft(2, '0');
  }
  Future<void> createNotifications() async {
    var time = Time(20, 15, 10);
    var time2 = Time(21, 00, 10);
    await flutterLocalNotificationsPlugin.showDailyAtTime(
        0, 'IELTS ', 'Time to learn', time, platformChannelSpecifics);
    await flutterLocalNotificationsPlugin.showDailyAtTime(
        1, 'IELTS', 'Time to learn', time2, platformChannelSpecifics);
  }
  Future<void> createDailyNotification() async {
    var time = new Time(01, 08, 00);
    try {
      await flutterLocalNotificationsPlugin.showDailyAtTime(
          1,
          'show daily title',
          'Daily notification shown at approximately ${_toTwoDigitString(time.hour)}:${_toTwoDigitString(time.minute)}:${_toTwoDigitString(time.second)}',
          time,
          platformChannelSpecifics);
    } catch (e) {
      print(e.toString());
    }
    print(time.toString() +
        androidPlatformChannelSpecifics.toString() +
        iOSPlatformChannelSpecifics.toString() +
        platformChannelSpecifics.toString());
  }
  Future<void> createWeeklyNotification() async {
    var time = new Time(10, 0, 0);
    await flutterLocalNotificationsPlugin.showWeeklyAtDayAndTime(
        0,
        'show weekly title',
        'Weekly notification shown on Monday at approximately ${_toTwoDigitString(time.hour)}:${_toTwoDigitString(time.minute)}:${_toTwoDigitString(time.second)}',
        Day.Monday,
        time,
        platformChannelSpecifics);
  }
  Future<void> createScheduledNotification() async {
    var scheduledNotificationDateTime =
        new DateTime.now().add(new Duration(seconds: 5));
    var androidPlatformChannelSpecifics = new AndroidNotificationDetails(
        'your other channel id',
        'your other channel name',
        'your other channel description');
    var iOSPlatformChannelSpecifics = new IOSNotificationDetails(
        presentAlert: true, presentBadge: true, presentSound: true);
    NotificationDetails platformChannelSpecifics = new NotificationDetails(
        androidPlatformChannelSpecifics, iOSPlatformChannelSpecifics);
    await flutterLocalNotificationsPlugin.schedule(
        0,
        'Minerva Time',
        'Minerva Time!!!',
        scheduledNotificationDateTime,
        platformChannelSpecifics);
  }
  Future<void> createPerNotification() async {
    // Show a notification every minute with the first appearance happening a minute after invoking the method
    await flutterLocalNotificationsPlugin.periodicallyShow(0, 'repeating title',
        'repeating body', RepeatInterval.EveryMinute, platformChannelSpecifics);
  }
  showNotification() async {
    await flutterLocalNotificationsPlugin.show(
        0, 'plain title', 'plain body', platformChannelSpecifics,
        payload: 'item x');
  }
  Future<void> setupNotification() async {
    try {
      await createScheduledNotification();
      //await createDailyNotification();
      //await showNotification();
      //await createNotifications();
    } catch (e) {
      print(e.toString());
    }
    createDailyNotification();
    //createWeeklyNotification();
    createScheduledNotification();
  }
  cancellAllNotifications() async {
    await flutterLocalNotificationsPlugin.cancelAll();
  }
  @override
  Widget build(BuildContext context) {
    return Container(
      child: Center(
        child: Column(
          children: <Widget>[
            Text(
              'hello world notifi',
              style: TextStyle(fontSize: 25),
            ),
            FlatButton(
              child: Text('press'),
              onPressed: () {
                cancellAllNotifications();
              },
            )
          ],
        ),
      ),
    );
  }
}

```

</details>

**Comment by ernestsheldon** [comment]
Sorry about bad format i put in between code ''

**Comment by iapicca** [comment]
Hi @ernestsheldon 
can you please provide your `flutter doctor -v` 
and your `flutter run --verbose`?
Thank you

**Comment by ernestsheldon** [comment]
[✓] Flutter (Channel dev, v1.12.2, on Linux, locale en_US.UTF-8)
    • Flutter version 1.12.2 at /home/ndragonx/development/flutter
    • Framework revision 6de6267942 (6 weeks ago), 2019-11-13 14:37:20 -0800
    • Engine revision b358dc58fb
    • Dart version 2.7.0

[✓] Android toolchain - develop for Android devices (Android SDK version
29.0.0)
    • Android SDK at /home/ndragonx/Android/Sdk
    • Android NDK location not configured (optional; useful for native
profiling support)
    • Platform android-29, build-tools 29.0.0
    • Java binary at:
/home/ndragonx/.local/share/JetBrains/Toolbox/apps/AndroidStudio/ch-0/191.6010548/jre/bin/java
    • Java version OpenJDK Runtime Environment (build
1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Android Studio (version 3.5)
    • Android Studio at
/home/ndragonx/.local/share/JetBrains/Toolbox/apps/AndroidStudio/ch-0/191.6010548
    • Flutter plugin version 37.0.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build
1.8.0_202-release-1483-b49-5587405)

[✓] IntelliJ IDEA Community Edition (version 2019.2)
    • IntelliJ at
/home/ndragonx/.local/share/JetBrains/Toolbox/apps/IDEA-C/ch-0/192.7142.36
    • Flutter plugin version 37.1.4
    • Dart plugin version 192.5728.98

[✓] VS Code (version 1.41.0)
    • VS Code at /usr/share/code
    • Flutter extension version 3.6.0

[✓] Connected device (3 available)
    • Android SDK built for x86 • emulator-5554 • android-x86    • Android
10 (API 29) (emulator)
    • Chrome                    • chrome        • web-javascript • Google
Chrome 79.0.3945.79
    • Web Server                • web-server    • web-javascript • Flutter
Tools

• No issues found!
Process finished with exit code 0

**Comment by iapicca** [comment]
Hi @ernestsheldon 
I apologize for realizing this only now,
[flutter_local_notifications](https://github.com/MaikuB/flutter_local_notifications) is a 3rd party plugin
you might want to open an issue in the dedicated [github](https://github.com/MaikuB/flutter_local_notifications).

Closing, as this isn't an issue with Flutter itself,
if you disagree please write in the comments and I will reopen it
Thank you
