### ISSUE TITLE
Using NestedScrollView with ScrollView in body throws an error: type '_NestedScrollMetrics' is not a subtype of type 'ScrollPosition')

### ISSUE THREAD

**Issue by GensaGames** [flutter/flutter#47850]
## Steps to Reproduce
Using next `NestedScrollView`. 

```dart
NestedScrollView(
        physics: ScrollPhysics(parent: PageScrollPhysics()),
        headerSliverBuilder: (BuildContext context, bool innerBoxIsScrolled) {
          return <Widget>[
            SliverList(
              delegate: SliverChildListDelegate([
                Container(height: 300, color: Colors.blue),
              ],
              ),
            ),
          ];
        },
        body: ListView.builder(itemBuilder: (context, index) {
          return Container(
            height: 100,
            color: index.isOdd ? Colors.green : Colors.orange,
          );
        },
        itemCount: 12,)
      );
```

Please refer to the documentation inside Flutter source. **What body can be** from the `NestedScrollView`: 
> The [body] is built in a context that provides a [PrimaryScrollController]
> that interacts with the [NestedScrollView]'s scroll controller. Any
> [ListView] or other [Scrollable]-based widget inside the [body] ...

**Target Platform:** NA
**Target OS version/browser:** NA
**Devices:** NA

## Logs

```
I/flutter (31995): ══╡ EXCEPTION CAUGHT BY GESTURE ╞═══════════════════════════════════════════════════════════════════
I/flutter (31995): The following assertion was thrown while handling a gesture:
I/flutter (31995): type '_NestedScrollMetrics' is not a subtype of type 'ScrollPosition'
I/flutter (31995): 
I/flutter (31995): Either the assertion indicates an error in the framework itself, or we should provide substantially
I/flutter (31995): more information in this error message to help you determine and fix the underlying cause.
I/flutter (31995): In either case, please report this assertion by filing a bug on GitHub:
I/flutter (31995):   https://github.com/flutter/flutter/issues/new?template=BUG.md
I/flutter (31995): 
I/flutter (31995): When the exception was thrown, this was the stack:
I/flutter (31995): #0      PageScrollPhysics.createBallisticSimulation (package:flutter/src/widgets/page_view.dart:483:44)
I/flutter (31995): #1      ScrollPhysics.createBallisticSimulation (package:flutter/src/widgets/scroll_physics.dart:193:19)
I/flutter (31995): #2      _NestedScrollCoordinator.createOuterBallisticScrollActivity (package:flutter/src/widgets/nested_scroll_view.dart:603:30)
I/flutter (31995): #3      _NestedScrollCoordinator.goBallistic (package:flutter/src/widgets/nested_scroll_view.dart:558:7)
I/flutter (31995): #4      ScrollDragController.end (package:flutter/src/widgets/scroll_activity.dart:389:14)
I/flutter (31995): #5      ScrollableState._handleDragEnd (package:flutter/src/widgets/scrollable.dart:508:12)
I/flutter (31995): #6      DragGestureRecognizer._checkEnd.<anonymous closure> (package:flutter/src/gestures/monodrag.dart:439:41)
I/flutter (31995): #7      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:182:24)
I/flutter (31995): #8      DragGestureRecognizer._checkEnd (package:flutter/src/gestures/monodrag.dart:439:5)
I/flutter (31995): #9      DragGestureRecognizer.didStopTrackingLastPointer (package:flutter/src/gestures/monodrag.dart:348:9)
I/flutter (31995): #10     OneSequenceGestureRecognizer.stopTrackingPointer (package:flutter/src/gestures/recognizer.dart:336:9)
I/flutter (31995): #11     DragGestureRecognizer._giveUpPointer (package:flutter/src/gestures/monodrag.dart:357:5)
I/flutter (31995): #12     DragGestureRecognizer.handleEvent (package:flutter/src/gestures/monodrag.dart:281:7)
I/flutter (31995): #13     PointerRouter._dispatch (package:flutter/src/gestures/pointer_router.dart:76:12)
I/flutter (31995): #14     PointerRouter._dispatchEventToRoutes.<anonymous closure> (package:flutter/src/gestures/pointer_router.dart:117:9)
I/flutter (31995): #15     _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:379:8)
I/flutter (31995): #16     PointerRouter._dispatchEventToRoutes (package:flutter/src/gestures/pointer_router.dart:115:18)
I/flutter (31995): #17     PointerRouter.route (package:flutter/src/gestures/pointer_router.dart:101:7)
I/flutter (31995): #18     GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:218:19)
I/flutter (31995): #19     GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:198:22)
I/flutter (31995): #20     GestureBinding._handlePointerEvent (package:flutter/src/gestures/binding.dart:156:7)
I/flutter (31995): #21     GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:102:7)
I/flutter (31995): #22     GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:86:7)
I/flutter (31995): #26     _invoke1 (dart:ui/hooks.dart:273:10)
I/flutter (31995): #27     _dispatchPointerDataPacket (dart:ui/hooks.dart:182:5)
I/flutter (31995): (elided 3 frames from package dart:async)
I/flutter (31995): 
I/flutter (31995): Handler: "onEnd"
I/flutter (31995): Recognizer:
I/flutter (31995):   VerticalDragGestureRecognizer#a7fa7
I/flutter (31995): ════════════════════════════════════════════════════════════════════════════════════════════════════
I/flutter (31995): Another exception was thrown: 'package:flutter/src/widgets/scrollable.dart': Failed assertion: line 484 pos 12: '_drag == null': is not true.
I/flutter (31995): Another exception was thrown: 'package:flutter/src/widgets/scrollable.dart': Failed assertion: line 493 pos 12: '_drag == null': is not true.
I/flutter (31995): Another exception was thrown: type '_NestedScrollMetrics' is not a subtype of type 'ScrollPosition'
```

## Flutter doctor
```

/Users/tkma2zi/Library/Flutter/bin/flutter doctor --verbose
[✓] Flutter (Channel stable, v1.12.13+hotfix.5, on Mac OS X 10.14.6 18G2022, locale en-US)
    • Flutter version 1.12.13+hotfix.5 at /Users/tkma2zi/Library/Flutter
    • Framework revision 27321ebbad (2 weeks ago), 2019-12-10 18:15:01 -0800
    • Engine revision 2994f7e1e6
    • Dart version 2.7.0

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/tkma2zi/Library/Android/sdk/
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • ANDROID_HOME = /Users/tkma2zi/Library/Android/sdk/
    • Java binary at: /Users/tkma2zi/Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[!] Xcode - develop for iOS and macOS (Xcode 11.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.1, Build version 11A1027
    ✗ CocoaPods not installed.
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To install:
        sudo gem install cocoapods

[✓] Android Studio (version 3.5)
    • Android Studio at /Users/tkma2zi/Applications/Android Studio.app/Contents
    • Flutter plugin version 42.1.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[!] IntelliJ IDEA Community Edition (version 2019.2.4)
    • IntelliJ at /Users/tkma2zi/Applications/IntelliJ IDEA CE.app
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.dev/intellij-setup/#installing-the-plugins

[✓] Connected device (1 available)
    • AOSP on IA Emulator • emulator-5554 • android-x86 • Android 9 (API 28) (emulator)

! Doctor found issues in 2 categories.
Process finished with exit code 0

```

**Comment by Piinks** [comment]
Hi @GensaGames, thanks for opening this issue!
I have reproduced this on master. Thanks for all of the detailed information!
