### ISSUE TITLE
Authentication Error

### ISSUE THREAD

**Issue by VISHCH0646** [flutter/flutter#47877]
Hey I am getting this error even after signing into the application:

```
E/flutter (18080): [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: PlatformException(-3, Permission denied, )
E/flutter (18080): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:569:7)
E/flutter (18080): #1      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:321:33)
E/flutter (18080): <asynchronous suspension>
E/flutter (18080): #2      DatabaseReference.set (package:firebase_database/src/database_reference.dart:73:31)
E/flutter (18080): #3      _HomeState._drawerItems.<anonymous closure> (package:flutter_app_pg/ui/home.dart:195:44)
E/flutter (18080): <asynchronous suspension>
E/flutter (18080): #4      _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:706:14)
E/flutter (18080): #5      _InkResponseState.build.<anonymous closure> (package:flutter/src/material/ink_well.dart:789:36)
E/flutter (18080): #6      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:182:24)
E/flutter (18080): #7      TapGestureRecognizer.handleTapUp (package:flutter/src/gestures/tap.dart:486:11)
E/flutter (18080): #8      BaseTapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:264:5)
E/flutter (18080): #9      BaseTapGestureRecognizer.acceptGesture (package:flutter/src/gestures/tap.dart:236:7)
E/flutter (18080): #10     GestureArenaManager.sweep (package:flutter/src/gestures/arena.dart:156:27)
E/flutter (18080): #11     GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:222:20)
E/flutter (18080): #12     GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:198:22)
E/flutter (18080): #13     GestureBinding._handlePointerEvent (package:flutter/src/gestures/binding.dart:156:7)
E/flutter (18080): #14     GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:102:7)
E/flutter (18080): #15     GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:86:7)
E/flutter (18080): #16     _rootRunUnary (dart:async/zone.dart:1138:13)
E/flutter (18080): #17     _CustomZone.runUnary (dart:async/zone.dart:1031:19)
E/flutter (18080): #18     _CustomZone.runUnaryGuarded (dart:async/zone.dart:933:7)
E/flutter (18080): #19     _invoke1 (dart:ui/hooks.dart:273:10)
E/flutter (18080): #20     _dispatchPointerDataPacket (dart:ui/hooks.dart:182:5)
E/flutter (18080): 
```

**Comment by BondarenkoStas** [comment]
Hi @VISHCH0646 
can you please provide your `flutter doctor -v` 
and `flutter run --verbose`?
Also, to better address the issue, would be helpful
if you could post a minimal code sample to reproduce the problem
Thank you

**Comment by VladyslavBondarenko** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.
Could everyone who still has this problem please file a new issue with the exact descriptions what happens, logs and the output of 'flutter doctor -v'  please.
All system setups can be slightly different so its always better to open new issues and reference related issues.
