### ISSUE TITLE
Sdkmanger crushes with java 12

### ISSUE THREAD

**Issue by ArkhipovK** [flutter/flutter#47883]
## Steps to Reproduce

1. Hello, i'm trying to create Flutter Desktop app on Win7 sp1, so first of all I've switched channel to master and run `flutter upgrade`
2. Now i'm trying to fix 'license status unknown' via `flutter doctor --android-licenses` but it tells that 'A newer version of the Android SDK is required.'
3. Updating sdk manger `C:\Users\Admin\AppData\Local\Android\Sdk\tools\bin\sdkmanager --update` crushes with
```
Error: Could not find or load main class com.android.sdklib.tool.sdkmanager.SdkManagerCli
Caused by: java.lang.ClassNotFoundException: com.android.sdklib.tool.sdkmanager.SdkManagerCli
```
4. Following the [instructions](https://medium.com/@parsher/flutter-android-sdkmanager-update-with-jdk-12-ad8098165472) i've added nessesary packages. It crushes with this now

```
Warning: Found corrupted package.xml at C:\Users\Admin\AppData\Local\Android\Sdk\build-tools\29.0.2\package.xml
Exception in thread "main" java.lang.NullPointerException
        at com.android.repository.impl.meta.SchemaModuleUtil.marshal(SchemaModuleUtil.java:265)
        at com.android.repository.impl.manager.LocalRepoLoaderImpl.writePackage(LocalRepoLoaderImpl.java:275)
        at com.android.repository.impl.manager.LocalRepoLoaderImpl.parsePackages(LocalRepoLoaderImpl.java:169)
        at com.android.repository.impl.manager.LocalRepoLoaderImpl.getPackages(LocalRepoLoaderImpl.java:124)
        at com.android.repository.impl.manager.RepoManagerImpl$LoadTask.run(RepoManagerImpl.java:518)
        at com.android.repository.api.RepoManager$DummyProgressRunner.runSyncWithProgress(RepoManager.java:397)
        at com.android.repository.impl.manager.RepoManagerImpl.load(RepoManagerImpl.java:365)
        at com.android.repository.api.RepoManager.loadSynchronously(RepoManager.java:290)
        at com.android.sdklib.repository.AndroidSdkHandler$RepoConfig.createRepoManager(AndroidSdkHandler.java:725)
        at com.android.sdklib.repository.AndroidSdkHandler.getSdkManager(AndroidSdkHandler.java:296)
        at com.android.sdklib.tool.sdkmanager.SdkManagerCliSettings.setSdkHandler(SdkManagerCliSettings.java:101)
        at com.android.sdklib.tool.sdkmanager.SdkManagerCli.<init>(SdkManagerCli.java:95)
        at com.android.sdklib.tool.sdkmanager.SdkManagerCli.main(SdkManagerCli.java:74)
        at com.android.sdklib.tool.sdkmanager.SdkManagerCli.main(SdkManagerCli.java:48)
```

## Flutter doctor

```
[√] Flutter (Channel master, v1.13.3-pre.60, on Microsoft Windows [Version 6.1.7601], locale ru-RU)
[!] Android toolchain - develop for Android devices (ndroid SDK version 29.0.2)
    • Android SDK at C:\Users\Admin\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)
    X Android license status unknown.
      Try re-installing or updating your Android SDK Manager.
      See https://developer.android.com/studio/#downloads or visit https://flutter.dev/setup/#android-setup for detailed instructions.
```

**Comment by jonahwilliams** [comment]
@ArkhipovK if you're looking to create a desktop application you do not need the Android SDK. If you have android studio installed, I would recommend using that to accept licenses/update
