### ISSUE TITLE
Unable to import 'packages' from pubspec.yaml

### ISSUE THREAD

**Issue by davide-tech** [flutter/flutter#47900]
After runnning 'flutter pud upgrade' all my imports are throwing an error. 
```'error • Target of URI doesn't exist: 'package:provider/provider.dart' • lib/main.dart:2:8 • uri_does_not_exist``` i thought it was an error with my app, but i am able to reproduce using the counter app.

![image](https://user-images.githubusercontent.com/20322844/71537811-3c6b5180-28d6-11ea-9d57-c4504a9fda73.png)

## Steps to Reproduce

1. Added package to dependencies in pubspec.yaml
2. imported on main.dart
3. Using Macbook Pro with Android Studio 3.0

## Logs

'flutter run --verbose' output
```
descobar@davids-mbp flutter_app_123 % flutter run --verbose
[  +19 ms] executing: [/Users/descobar/Downloads/flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[  +33 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[        ] 27321ebbad34b0a3fafe99fac037102196d655ff
[        ] executing: [/Users/descobar/Downloads/flutter/] git describe --match v*.*.* --first-parent --long --tags
[  +14 ms] Exit code 0 from: git describe --match v*.*.* --first-parent --long --tags
[        ] v1.12.13+hotfix.5-0-g27321ebba
[   +7 ms] executing: [/Users/descobar/Downloads/flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[  +12 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/stable
[        ] executing: [/Users/descobar/Downloads/flutter/] git ls-remote --get-url origin
[  +11 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[  +65 ms] executing: [/Users/descobar/Downloads/flutter/] git rev-parse --abbrev-ref HEAD
[  +15 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] stable
[   +6 ms] executing: sw_vers -productName
[  +16 ms] Exit code 0 from: sw_vers -productName
[        ] Mac OS X
[        ] executing: sw_vers -productVersion
[  +17 ms] Exit code 0 from: sw_vers -productVersion
[        ] 10.15.2
[        ] executing: sw_vers -buildVersion
[  +19 ms] Exit code 0 from: sw_vers -buildVersion
[        ] 19C57
[  +37 ms] executing: /usr/bin/xcode-select --print-path
[   +8 ms] Exit code 0 from: /usr/bin/xcode-select --print-path
[        ] /Applications/Xcode.app/Contents/Developer
[   +1 ms] executing: /usr/bin/xcodebuild -version
[ +106 ms] Exit code 0 from: /usr/bin/xcodebuild -version
[   +2 ms] Xcode 11.3
           Build version 11C29
[  +56 ms] executing: /Users/descobar/Library/Android/sdk/platform-tools/adb devices -l
[   +6 ms] Exit code 0 from: /Users/descobar/Library/Android/sdk/platform-tools/adb devices -l
[        ] List of devices attached
[  +18 ms] executing: /Users/descobar/Downloads/flutter/bin/cache/artifacts/libimobiledevice/idevice_id -h
[  +54 ms] /usr/bin/xcrun simctl list --json devices
[  +94 ms] No supported devices connected.
[   +9 ms] "flutter run" took 473ms.

#0      throwToolExit (package:flutter_tools/src/base/common.dart:28:3)
#1      RunCommand.validateCommand (package:flutter_tools/src/commands/run.dart:289:7)
<asynchronous suspension>
#2      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:590:11)
#3      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:515:33)
<asynchronous suspension>
#4      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:146:29)
#5      _rootRun (dart:async/zone.dart:1126:13)
#6      _CustomZone.run (dart:async/zone.dart:1023:19)
#7      _runZoned (dart:async/zone.dart:1518:10)
#8      runZoned (dart:async/zone.dart:1465:12)
#9      AppContext.run (package:flutter_tools/src/base/context.dart:145:18)
#10     FlutterCommand.run (package:flutter_tools/src/runner/flutter_command.dart:505:20)
#11     CommandRunner.runCommand (package:args/command_runner.dart:197:27)
#12     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:413:21)
<asynchronous suspension>
#13     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:146:29)
#14     _rootRun (dart:async/zone.dart:1126:13)
#15     _CustomZone.run (dart:async/zone.dart:1023:19)
#16     _runZoned (dart:async/zone.dart:1518:10)
#17     runZoned (dart:async/zone.dart:1465:12)
#18     AppContext.run (package:flutter_tools/src/base/context.dart:145:18)
#19     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:364:19)
#20     CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:112:25)
#21     new Future.sync (dart:async/future.dart:224:31)
#22     CommandRunner.run (package:args/command_runner.dart:112:14)
#23     FlutterCommandRunner.run (package:flutter_tools/src/runner/flutter_command_runner.dart:250:18)
#24     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:63:22)
#25     _rootRun (dart:async/zone.dart:1126:13)
#26     _CustomZone.run (dart:async/zone.dart:1023:19)
#27     _runZoned (dart:async/zone.dart:1518:10)
#28     runZoned (dart:async/zone.dart:1502:12)
#29     run.<anonymous closure> (package:flutter_tools/runner.dart:61:18)
<asynchronous suspension>
#30     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:146:29)
#31     _rootRun (dart:async/zone.dart:1126:13)
#32     _CustomZone.run (dart:async/zone.dart:1023:19)
#33     _runZoned (dart:async/zone.dart:1518:10)
#34     runZoned (dart:async/zone.dart:1465:12)
#35     AppContext.run (package:flutter_tools/src/base/context.dart:145:18)
#36     runInContext (package:flutter_tools/src/context_runner.dart:64:24)
#37     run (package:flutter_tools/runner.dart:50:10)
#38     main (package:flutter_tools/executable.dart:65:9)
#39     main (file:///Users/descobar/Downloads/flutter/packages/flutter_tools/bin/flutter_tools.dart:8:3)
#40     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:305:32)
#41     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:174:12)


```

```
descobar@davids-mbp flutter_app_123 % flutter analyze
Analyzing flutter_app_123...                                            

  error • Target of URI doesn't exist: 'package:provider/provider.dart' • lib/main.dart:2:8 • uri_does_not_exist
  error • Target of URI doesn't exist: 'package:device_info/device_info.dart' • lib/main.dart:3:8 • uri_does_not_exist
  error • Target of URI doesn't exist: 'package:flutter_app_123/main.dart' • test/widget_test.dart:11:8 • uri_does_not_exist
  error • The function 'MyApp' isn't defined • test/widget_test.dart:16:29 • undefined_function

4 issues found. (ran in 1.2s)

```

```
descobar@davids-mbp flutter_app_123 % flutter doctor -v
[✓] Flutter (Channel stable, v1.12.13+hotfix.5, on Mac OS X 10.15.2 19C57, locale en-US)
    • Flutter version 1.12.13+hotfix.5 at /Users/descobar/Downloads/flutter
    • Framework revision 27321ebbad (2 weeks ago), 2019-12-10 18:15:01 -0800
    • Engine revision 2994f7e1e6
    • Dart version 2.7.0

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/descobar/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Users/descobar/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-1/192.6071332/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.3, Build version 11C29
    • CocoaPods version 1.8.4

[✓] Android Studio (version 3.6)
    • Android Studio at /Users/descobar/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-1/192.6071332/Android Studio.app/Contents
    • Flutter plugin version 42.2.2
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)

[✓] Android Studio (version 3.5)
    • Android Studio at /Users/descobar/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/191.6010548/Android Studio.app/Contents
    • Flutter plugin version 42.1.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[!] Connected device
    ! No devices available

! Doctor found issues in 1 category.
descobar@davids-mbp flutter_app_123 % 
```

**Comment by jonahwilliams** [comment]
The logs you've posted don't contain any sort of error message. FWIW, the command is `flutter pub get`, running that should resolve all dependencies that are in your pubspec.yaml.

If that is not the case, it is likely that the dependencies section is ill-formatted. I recommend taking a look at an example pubspec.yaml in the flutter repo and comparing: https://github.com/flutter/flutter/blob/master/packages/flutter/pubspec.yaml
