### ISSUE TITLE
'dart:ui/text.dart': Failed assertion: line 1372: '<optimized out>': is not true

### ISSUE THREAD

**Issue by dheeraj2dj** [flutter/flutter#47955]
Have an issue with a text field. Please help! Struggling for almost a week now! 😭 

### Error log: 
```
I/flutter (13657): ════════════════════════════════════════════════════════════════════════════════════════════════════
I/flutter (13657): ══╡ EXCEPTION CAUGHT BY RENDERING LIBRARY ╞═════════════════════════════════════════════════════════
I/flutter (13657): The following assertion was thrown during paint():
I/flutter (13657): 'dart:ui/text.dart': Failed assertion: line 1372: '<optimized out>': is not true.
I/flutter (13657): Either the assertion indicates an error in the framework itself, or we should provide substantially
I/flutter (13657): more information in this error message to help you determine and fix the underlying cause.
I/flutter (13657): In either case, please report this assertion by filing a bug on GitHub:
I/flutter (13657):   https://github.com/flutter/flutter/issues/new?template=BUG.md
I/flutter (13657): The relevant error-causing widget was:
I/flutter (13657):   _Editable-[GlobalKey#da011]
I/flutter (13657):   file:///Users/dheeraj2dj/.pub-cache/hosted/pub.dartlang.org/extended_text_field-0.4.6/lib/src/extended_editable_text.dart:1552:20
I/flutter (13657): When the exception was thrown, this was the stack:
I/flutter (13657): #2      new TextPosition (dart:ui/text.dart:1372:15)
I/flutter (13657): #3      ExtendedRenderEditable._updateSelectionExtentsVisibility (package:extended_text_field/src/extended_render_editable.dart:283:7)
I/flutter (13657): #4      ExtendedRenderEditable._paintContents (package:extended_text_field/src/extended_render_editable.dart:1871:7)
I/flutter (13657): #5      ExtendedRenderEditable.paint (package:extended_text_field/src/extended_render_editable.dart:1930:7)
I/flutter (13657): #6      RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2219:7)
I/flutter (13657): #7      PaintingContext.paintChild (package:flutter/src/rendering/object.dart:184:13)
I/flutter (13657): #8      RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:123:15)
I/flutter (13657): #9      RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2219:7)
I/flutter (13657): #10     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:184:13)
I/flutter (13657): #11     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:123:15)
I/flutter (13657): #12     PaintingContext.pushLayer (package:flutter/src/rendering/object.dart:384:12)
I/flutter (13657): #13     RenderLeaderLayer.paint (package:flutter/src/rendering/proxy_box.dart:4796:13)
I/flutter (13657): #14     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2219:7)
I/flutter (13657): #15     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:184:13)
I/flutter (13657): #16     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:123:15)
I/flutter (13657): #17     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2219:7)
I/flutter (13657): #18     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:184:13)
I/flutter (13657): #19     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:123:15)
I/flutter (13657): #20     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2219:7)
I/flutter (13657): #21     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:184:13)
I/flutter (13657): #22     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:123:15)
I/flutter (13657): #23     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2219:7)
I/flutter (13657): #24     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:184:13)
I/flutter (13657): #25     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:123:15)
I/flutter (13657): #26     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2219:7)
I/flutter (13657): #27     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:184:13)
I/flutter (13657): #28     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:123:15)
I/flutter (13657): #29     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2219:7)
I/flutter (13657): #30     PaintingContext._repaintCompositedChild (package:flutter/src/rendering/object.dart:135:11)
I/flutter (13657): #31     PaintingContext.repaintCompositedChild (package:flutter/src/rendering/object.dart:95:5)
I/flutter (13657): #32     PipelineOwner.flushPaint (package:flutter/src/rendering/object.dart:937:29)
I/flutter (13657): #33     RendererBinding.drawFrame (package:flutter/src/rendering/binding.dart:346:19)
I/flutter (13657): #34     WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:774:13)
I/flutter (13657): #35     RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:283:5)
I/flutter (13657): #36     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1102:15)
I/flutter (13657): #37     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1041:9)
I/flutter (13657): #38     SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:957:5)
I/flutter (13657): #42     _invoke (dart:ui/hooks.dart:259:10)
I/flutter (13657): #43     _drawFrame (dart:ui/hooks.dart:217:3)
I/flutter (13657): (elided 5 frames from class _AssertionError and package dart:async)
I/flutter (13657): The following RenderObject was being processed when the exception was fired: ExtendedRenderEditable#aa1e2 relayoutBoundary=up30:
I/flutter (13657):   creator: _Editable-[GlobalKey#da011] ← Semantics ← CompositedTransformTarget ←
I/flutter (13657): Flutter error caught by Crashlytics plugin:
I/flutter (13657): Flutter error caught by Crashlytics plugin:
I/flutter (13657):     IgnorePointer-[GlobalKey#2d809] ← Semantics ← _PointerListener ← Listener ←
I/flutter (13657):     RawGestureDetector-[LabeledGlobalKey<RawGestureDetectorState>#22694] ← _PointerListener ← Listener
I/flutter (13657):     ← _ScrollableScope ← RepaintBoundary ← ⋯
I/flutter (13657):   parentData: <none> (can use size)
I/flutter (13657):   constraints: BoxConstraints(w=288.0, 0.0<=h<=Infinity)
I/flutter (13657):   size: Size(288.0, 80.0)
I/flutter (13657):   cursorColor: Color(0x004285f4)
I/flutter (13657):   showCursor: ValueNotifier<bool>#18e61(false)
I/flutter (13657):   maxLines: 8
I/flutter (13657):   minLines: 5
I/flutter (13657):   selectionColor: Color(0xff9fa8da)
I/flutter (13657):   textScaleFactor: 1.0
I/flutter (13657):   locale: en_US
I/flutter (13657):   selection: TextSelection(baseOffset: 0, extentOffset: 0, affinity: null, isDirectional: false)
I/flutter (13657):   offset: ScrollPositionWithSingleContext#06edf(offset: 0.0, range: 0.0..0.0, viewport: 80.0,
I/flutter (13657):     ScrollableState, ClampingScrollPhysics, IdleScrollActivity#370b7, ScrollDirection.idle)
I/flutter (13657): This RenderObject had the following descendants (showing up to depth 5):
I/flutter (13657):     text: TextSpan
I/flutter (13657):       TextSpan
```

### Flutter Doctor:
```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, v1.12.13+hotfix.5, on Mac OS X 10.15.2 19C57, locale en-IN)

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 11.2.1)
[✓] Android Studio (version 3.5)
[✓] VS Code (version 1.36.1)
[✓] Connected device (1 available)

• No issues found!
```

**Comment by dheeraj2dj** [comment]
Found the issue

Had to add `affinity: TextAffinity.downstream` to `TextPosition` widget
