### ISSUE TITLE
“Failed to handle method call” en Google Maps

### ISSUE THREAD

**Issue by holaperdedores** [flutter/flutter#47983]
> Estoy tratando de usar el Widget GoogleMap. Utilizo los pasos detallados en "google_maps_flutter" y realizo toda la configuración que se solicita. Creo la APIKey de GoogleMaps y agrego la clave en los archivos AndroidManefest y AppDelegate.swift. Cuando ejecuto en Android me funciona correctamente pero cuando cambio a iOS en el "flutter Inspector" me aparece el error que detallo mas abajo. 

I am trying to use the GoogleMap Widget. I use the steps detailed in "google_maps_flutter" and perform all the requested configuration. I create the GoogleMaps APIKey and add the key in the AndroidManefest and AppDelegate.swift files. When I run on Android it works correctly but when I switch to iOS in the "flutter Inspector" I get the error that I detail below.

```bash
 Failed to handle method call
java.lang.NullPointerException: Attempt to invoke virtual method 'double java.lang.Double.doubleValue()' on a null object reference
at io.flutter.embedding.engine.systemchannels.PlatformViewsChannel$1.create(PlatformViewsChannel.java:78)
at io.flutter.embedding.engine.systemchannels.PlatformViewsChannel$1.onMethodCall(PlatformViewsChannel.java:51)
at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:222)
at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:96)
at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:656)
at android.os.MessageQueue.nativePollOnce(Native Method)
at android.os.MessageQueue.next(MessageQueue.java:336)
at android.os.Looper.loop(Looper.java:174)
at android.app.ActivityThread.main(ActivityThread.java:7356)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
[ERROR:flutter/lib/ui/ui_dart_state.cc(148)] Unhandled Exception: PlatformException(error, Attempt to invoke virtual method 'double java.lang.Double.doubleValue()' on a null object reference, null)
#0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:569:7)
#1      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:316:33)
<asynchronous suspension>
#2      PlatformViewsService.initUiKitView (package:flutter/src/services/platform_views.dart:168:41)
<asynchronous suspension>
#3      _UiKitViewState._createNewUiKitView (package:flutter/src/widgets/platform_view.dart:503:71)
<asynchronous suspension>
#4      _UiKitViewState._initializeOnce (package:flutter/src/widgets/platform_view.dart:453:5)
#5      _UiKitViewState.didChangeDependencies (package:flutter/src/widgets/platform_view.dart:463:5)
#6      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4086:12)
#7      ComponentElement.mount (package:flutter/src/widgets/framework.dart:3919:5)
#8      Element.inflateWidget (package:flutter/src/widgets/framework.dart:3101:14)
#9      Element.updateChild (package:flutter/src/widgets/framework.dart:2904:12)
#10     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3961:16)
#11     Element.rebuild (package:flutter/src/widgets/framework.dart:3738:5)
#12     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3924:5)
#13     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4088:11)
#14     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3919:5)
#15     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3101:14)
#16     Element.updateChild (package:flutter/src/widgets/framework.dart:2904:12)
#17     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3961:16)
#18     Element.rebuild (package:flutter/src/widgets/framework.dart:3738:5)
#19     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3924:5)
#20     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3919:5)
#21     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3101:14)
#22     Element.updateChild (package:flutter/src/widgets/framework.dart:2904:12)
#23     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3961:16)
#24     Element.rebuild (package:flutter/src/widgets/framework.dart:3738:5)
#25     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3924:5)
#26     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3919:5)
#27     ParentDataElement.mount (package:flutter/src/widgets/framework.dart:4314:11)
#28     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3101:14)
#29     MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5233:32)
#30     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3101:14)
#31     Element.updateChild (package:flutter/src/widgets/framework.dart:2904:12)
#32     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3961:16)
#33     Element.rebuild (package:flutter/src/widgets/framework.dart:3738:5)
#34     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3924:5)
#35     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4088:11)
#36     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3919:5)
#37     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3101:14)
#38     Element.updateChild (package:flutter/src/widgets/framework.dart:2904:12)
#39     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3961:16)
#40     Element.rebuild (package:flutter/src/widgets/framework.dart:3738:5)
#41     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3924:5)
#42     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3919:5)
#43     Element.inflateWidget (package:flutter/src
```

> El metodo build de clase_MyAppState que extiende de State es:

The build method of MyAppState_class that extends from State is:

```dart
Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        appBar: AppBar(
          title: Text('MyApp'),
          leading: IconButton(
            tooltip: 'Atras',
            icon: const Icon(Icons.arrow_back),
            onPressed: () {
              Navigator.pop(context);
            },
          ),
        ),
        body: GoogleMap(
          onMapCreated: onMapCreated,
          initialCameraPosition: _initialPosition,
          markers: _markers,
          zoomGesturesEnabled: true,
        ),
      ),
    );
  }
```

> Los metodos onMapCreated, _initialPosition y _markers

The onMapCreated, _initialPosition and _markers methods

```dart
void onMapCreated(GoogleMapController controller) {
    mapController = controller;
  }

CameraPosition _initialPosition = CameraPosition(target: LatLng(-33.4726900, -70.6472400),zoom: 16.0);

final Set<Marker> _markers = Set();
```

**Comment by VladyslavBondarenko** [comment]
HI @holaperdedores 
are you experiencing the issue with the last google_maps_flutter plugin and flutter sdk versions?

**Comment by holaperdedores** [comment]
hey @VladyslavBondarenko, yeah same issue when I switch to iOS in the "flutter Inspector" .

**Comment by shamwairock** [comment]
Does anybody has updates on this?

**Comment by manuel25cauich** [comment]
yo también tengo ese error, ¡aun no hay forma de corregirlo?

**Comment by darshankawar** [comment]
@holaperdedores 
I tried below code sample using latest master version and plugin version and changed to ios in flutter inspector, with which I didn't observe the said issue.

<details>
<summary> code sample </summary>

```
import 'package:flutter/material.dart';
import 'package:google_maps_flutter/google_maps_flutter.dart';

void main() {
  runApp(MaterialApp(
    home: MapPage(),
  ));
}

class MapPage extends StatefulWidget {
  @override
  MapPageState createState() => MapPageState();
}

class MapPageState extends State<MapPage> {
  GoogleMapController _controller;

  final Set<Marker> _markers = Set();

  GoogleMapController mapController;

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('Carte'),
        leading: IconButton(
          tooltip: 'Atras',
          icon: const Icon(Icons.arrow_back),
          onPressed: () {
            Navigator.pop(context);
          },
        ),
      ),
      body: GoogleMap(
        initialCameraPosition: CameraPosition(
          target: LatLng(45.5, -71),
          zoom: 10,
        ),
        markers: _markers,
        // onMapCreated: _onMapCreated(),
        onCameraMove: (cameraPosition) =>
            print('MAPPP MOVEEE: $cameraPosition'),
      ),
    );
    // );
  }

  void onMapCreated(GoogleMapController controller) {
    mapController = controller;
  }
}



```

</details>

<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel master, 2.3.0-1.0.pre.143, on Mac OS X 10.15.4 19E2269
    darwin-x64, locale en-GB)
    • Flutter version 2.3.0-1.0.pre.143 at
      /Users/dhs/documents/fluttersdk/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision aecd5e0302 (10 hours ago), 2021-04-28 00:53:57 -0300
    • Engine revision 92ef7b59c8
    • Dart version 2.14.0 (build 2.14.0-48.0.dev)

[!] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.3, Build version 12C33
    ! CocoaPods 1.9.3 out of date (1.10.0 is recommended).
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin
        code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To upgrade see
      https://guides.cocoapods.org/using/getting-started.html#installation for
      instructions.

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] VS Code (version 1.55.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.21.0

[✓] Connected device (3 available)
    • iPhone 12 Pro Max (mobile) • A5473606-0213-4FD8-BA16-553433949729 • ios
      • com.apple.CoreSimulator.SimRuntime.iOS-14-3 (simulator)
    • macOS (desktop)            • macos                                •
      darwin-x64     • Mac OS X 10.15.4 19E2269 darwin-x64
    • Chrome (web)               • chrome                               •
      web-javascript • Google Chrome 90.0.4430.85

! Doctor found issues in 1 category.
```

</details>

Since this is more than a year old issue and plugin has gone through lot of updates and may have been fixed during the course.
I am going ahead and closing this as not replicable and probably fixed. If you disagree, write in comments and I'll reopen it.
Thanks.
