### ISSUE TITLE
[tool_crash] During cache unzip: RangeError (index): Index out of range: no indices are valid: 0

### ISSUE THREAD

**Issue by MohammedZ666** [flutter/flutter#48014]
## Command
  ```
  flutter doctor
  ```

  ## Steps to Reproduce
  1. ...
  2. ...
  3. ...

  ## Logs
  IndexError: RangeError (index): Index out of range: no indices are valid: 0
  ```
  #0      Uint8List.[] (dart:typed_data-patch/typed_data_patch.dart:2209:7)
#1      InputStream.readUint16 (package:archive/src/util/input_stream.dart:190:20)
#2      GZipDecoder._readHeader (package:archive/src/gzip_decoder.dart:89:27)
#3      GZipDecoder.decodeBuffer (package:archive/src/gzip_decoder.dart:26:5)
#4      GZipDecoder.decodeBytes (package:archive/src/gzip_decoder.dart:17:12)
#5      _WindowsUtils.verifyGzip (package:flutter_tools/src/base/os.dart:294:21)
#6      CachedArtifact._downloadArchive.<anonymous closure> (package:flutter_tools/src/cache.dart:531:20)
#7      CachedArtifact._withDownloadFile (package:flutter_tools/src/cache.dart:563:26)
#8      CachedArtifact._downloadArchive (package:flutter_tools/src/cache.dart:530:12)
#9      CachedArtifact._downloadZippedTarball (package:flutter_tools/src/cache.dart:555:12)
#10     GradleWrapper.updateInner (package:flutter_tools/src/cache.dart:992:12)
#11     CachedArtifact.update (package:flutter_tools/src/cache.dart:496:11)
#12     Cache.updateAll (package:flutter_tools/src/cache.dart:394:24)
#13     FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:602:19)
#14     FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:522:33)
<asynchronous suspension>
#15     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:29)
#16     _rootRun (dart:async/zone.dart:1126:13)
#17     _CustomZone.run (dart:async/zone.dart:1023:19)
#18     _runZoned (dart:async/zone.dart:1518:10)
  ```
  ```
  [!] Flutter (Channel master, v1.13.6-pre.44, on Microsoft Windows [Version 10.0.17763.914], locale en-US)
    • Flutter version 1.13.6-pre.44 at D:\flutter
    • Framework revision e768c92fbc (10 hours ago), 2019-12-30 17:12:19 -0800
    • Engine revision bdc9708d23
    • Dart version 2.8.0 (build 2.8.0-dev.0.0 c547f5d933)
    ✗ Downloaded executables cannot execute on host.
      See https://github.com/flutter/flutter/issues/6207 for more information


[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/setup/#android-setup for detailed instructions).
      If the Android SDK has been installed to a custom location, set ANDROID_HOME to that location.
      You may also want to add it to your PATH environment variable.


[!] Android Studio (version 3.5)
    • Android Studio at D:\Android studio
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)

[!] Connected device
    ! No devices available

! Doctor found issues in 4 categories.

  ```

  ## Flutter Application Metadata
  No pubspec in working directory.

**Comment by jonahwilliams** [comment]
We think that this is fixed via additional debug checks added to tool downloads https://github.com/flutter/flutter/commit/23032d772d80d531fdbc483de131f066a783f75c
