### ISSUE TITLE
TextField value has not been shown

### ISSUE THREAD

**Issue by doandinh** [flutter/flutter#48011]
## Steps to Reproduce

1. I have a list of options
2. When I click a specific option (ex: the last one), a TextField will be shown
3. When the TextField is shown, type something
4. Click on other option, hide the TextField (render other Widget instead of this TextField)
5. Click on the specific option on Step 2, a TextField will be shown again
6. TextField is empty until I make a focus (touch) on it

**Target Platform:** Android
**Target OS version/browser:** 7.0
**Devices:** Huawei (EVA-L19)

## Logs
════════ Exception caught by rendering library ═════════════════════════════════════════════════════
The following assertion was thrown during paint():
'dart:ui/text.dart': Failed assertion: line 1372: '<optimized out>': is not true.

Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=BUG.md

The relevant error-causing widget was: 
  TextField file:///D:/work/VNO/vno/lib/ui/widgets/register_panel_widget.dart:649:18
When the exception was thrown, this was the stack: 
#2      new TextPosition (dart:ui/text.dart:1372:15)
#3      RenderEditable._updateSelectionExtentsVisibility (package:flutter/src/rendering/editable.dart:367:7)
#4      RenderEditable._paintContents (package:flutter/src/rendering/editable.dart:1956:7)
#5      RenderEditable.paint (package:flutter/src/rendering/editable.dart:2012:7)
#6      RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2219:7)
...
The following RenderObject was being processed when the exception was fired: RenderEditable#d7010 relayoutBoundary=up34
...  parentData: <none> (can use size)
...  constraints: BoxConstraints(w=280.0, 0.0<=h<=Infinity)
...  size: Size(280.0, 19.0)
...  cursorColor: Color(0x000c2d3c)
...  showCursor: ValueNotifier<bool>#fe5a3(true)
...  maxLines: 1
...  minLines: null
...  selectionColor: Color(0xff90caf9)
...  textScaleFactor: 1.0
...  locale: vi_
...  selection: TextSelection(baseOffset: 7, extentOffset: 7, affinity: null, isDirectional: false)
...  offset: ScrollPositionWithSingleContext#45478(offset: 0.0, range: 0.0..0.0, viewport: 280.0, ScrollableState, ClampingScrollPhysics, IdleScrollActivity#2c1f9, ScrollDirection.idle)
  text: TextSpan
    debugLabel: ((englishLike subhead 2014).merge(blackMountainView subhead)).merge(unknown)
    inherit: false
    color: Color(0xff0c2d3c)
    family: Roboto
    size: 16.0
    weight: 400
    baseline: alphabetic
    decoration: TextDecoration.none
    "tyyyyyy"
RenderObject: RenderEditable#d7010 relayoutBoundary=up34
  parentData: <none> (can use size)
  constraints: BoxConstraints(w=280.0, 0.0<=h<=Infinity)
  size: Size(280.0, 19.0)
  cursorColor: Color(0x000c2d3c)
  showCursor: ValueNotifier<bool>#fe5a3(true)
  maxLines: 1
  minLines: null
  selectionColor: Color(0xff90caf9)
  textScaleFactor: 1.0
  locale: vi_
  selection: TextSelection(baseOffset: 7, extentOffset: 7, affinity: null, isDirectional: false)
  offset: ScrollPositionWithSingleContext#45478(offset: 0.0, range: 0.0..0.0, viewport: 280.0, ScrollableState, ClampingScrollPhysics, IdleScrollActivity#2c1f9, ScrollDirection.idle)
  text: TextSpan
    debugLabel: ((englishLike subhead 2014).merge(blackMountainView subhead)).merge(unknown)
    inherit: false
    color: Color(0xff0c2d3c)
    family: Roboto
    size: 16.0
    weight: 400
    baseline: alphabetic
    decoration: TextDecoration.none
    "tyyyyyy"
════════════════════════════════════════════════════════════════════════════════════════════════════

```
```

[√] Flutter (Channel stable, v1.12.13+hotfix.5, on Microsoft Windows [Version 10.0.18362.535], locale en-US)
    • Flutter version 1.12.13+hotfix.5 at D:\flutter
    • Framework revision 27321ebbad (3 weeks ago), 2019-12-10 18:15:01 -0800
    • Engine revision 2994f7e1e6
    • Dart version 2.7.0

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at D:\android_sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • ANDROID_HOME = D:\android_sdk
    • Java binary at: D:\android_studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)
    • All Android licenses accepted.

[√] Android Studio (version 3.5)
    • Android Studio at D:\android_studio
    • Flutter plugin version 42.1.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)

[√] Connected device (1 available)
    • EVA L19 • XVV7N16B18005562 • android-arm64 • Android 7.0 (API 24)

• No issues found!

**Comment by doandinh** [comment]
Solved by added FocusNode into TextField
