### ISSUE TITLE
Exception thrown when scrolling list

### ISSUE THREAD

**Issue by KieranCTaylor** [flutter/flutter#48043]
I am getting an exception thrown that suggests opening a bug -> "Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause."

I have a ListView.builder as the second element of the children of a Column(). When I scroll upwards it is fine but when I try scroll downwards it throws "Failed assertion: line 1245 pos 12: 'value.isFinite'".

When I first tried to add multiple children that could both scroll I got an error that the viewports were unbounded, adding shrinkWrap fixed it but now the console throws this error.

## Steps to Reproduce

The widget causing the problem: https://gist.github.com/KieranCTaylor/3cd86db289b3bbf1ef349bb290450ef2

Once loaded, scrolling upwards throws the exception.

**Target Platform:** iOS
**Target OS version/browser:** iOS 13.3
**Devices:** Simulator (not tested on physical device)

## Logs

```
flutter: ══╡ EXCEPTION CAUGHT BY SCHEDULER LIBRARY ╞═════════════════════════════════════════════════════════
flutter: The following assertion was thrown during a scheduler callback:
flutter: SemanticsNode#25(Rect.fromLTRB(0.0, 0.0, 414.0, 80.0), tags: [RenderViewport.twoPane]) (with
flutter: SemanticsOwner#40a5d) tried to set a non-finite rect.
flutter: 'package:flutter/src/semantics/semantics.dart':
flutter: Failed assertion: line 1245 pos 12: 'value.isFinite'
flutter:
flutter: Either the assertion indicates an error in the framework itself, or we should provide substantially
flutter: more information in this error message to help you determine and fix the underlying cause.
flutter: In either case, please report this assertion by filing a bug on GitHub:
flutter:   https://github.com/flutter/flutter/issues/new?template=BUG.md
flutter:
flutter: When the exception was thrown, this was the stack:
flutter: #2      SemanticsNode.rect= (package:flutter/src/semantics/semantics.dart:1245:12)
flutter: #3      _SwitchableSemanticsFragment.compileChildren (package:flutter/src/rendering/object.dart:3596:11)
flutter: #4      _SyncIterator.moveNext (dart:core-patch/core_patch.dart:146:12)
flutter: #5      _SyncIterator.moveNext (dart:core-patch/core_patch.dart:139:32)
flutter: #6      ExpandIterator.moveNext (dart:_internal/iterable.dart:478:31)
flutter: #7      new List.from (dart:core-patch/array_patch.dart:47:19)
flutter: #8      Iterable.toList (dart:core/iterable.dart:400:5)
flutter: #9      _SwitchableSemanticsFragment.compileChildren (package:flutter/src/rendering/object.dart:3612:8)
flutter: #10     _SyncIterator.moveNext (dart:core-patch/core_patch.dart:146:12)
flutter: #11     ExpandIterator.moveNext (dart:_internal/iterable.dart:478:31)
flutter: #12     new List.from (dart:core-patch/array_patch.dart:47:19)
flutter: #13     Iterable.toList (dart:core/iterable.dart:400:5)
flutter: #14     _SwitchableSemanticsFragment.compileChildren (package:flutter/src/rendering/object.dart:3612:8)
flutter: #15     _SyncIterator.moveNext (dart:core-patch/core_patch.dart:146:12)
flutter: #16     _SyncIterator.moveNext (dart:core-patch/core_patch.dart:139:32)
flutter: #17     ExpandIterator.moveNext (dart:_internal/iterable.dart:478:31)
flutter: #18     new List.from (dart:core-patch/array_patch.dart:47:19)
flutter: #19     Iterable.toList (dart:core/iterable.dart:400:5)
flutter: #20     _SwitchableSemanticsFragment.compileChildren (package:flutter/src/rendering/object.dart:3612:8)
flutter: #21     _SyncIterator.moveNext (dart:core-patch/core_patch.dart:146:12)
flutter: #22     ExpandIterator.moveNext (dart:_internal/iterable.dart:478:31)
flutter: #23     new List.from (dart:core-patch/array_patch.dart:47:19)
flutter: #24     Iterable.toList (dart:core/iterable.dart:400:5)
flutter: #25     _RootSemanticsFragment.compileChildren (package:flutter/src/rendering/object.dart:3493:8)
flutter: #26     _SyncIterator.moveNext (dart:core-patch/core_patch.dart:146:12)
flutter: #27     Iterable.single (dart:core/iterable.dart:554:13)
flutter: #28     RenderObject._updateSemantics (package:flutter/src/rendering/object.dart:2539:7)
flutter: #29     PipelineOwner.flushSemantics (package:flutter/src/rendering/object.dart:1040:16)
flutter: #30     RendererBinding.drawFrame (package:flutter/src/rendering/binding.dart:348:19)
flutter: #31     WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:774:13)
flutter: #32     RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:283:5)
flutter: #33     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1102:15)
flutter: #34     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1041:9)
flutter: #35     SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:957:5)
flutter: #39     _invoke (dart:ui/hooks.dart:259:10)
flutter: #40     _drawFrame (dart:ui/hooks.dart:217:3)
flutter: (elided 5 frames from class _AssertionError and package dart:async)
flutter: ════════════════════════════════════════════════════════════════════════════════════════════════════
```

**Comment by iapicca** [comment]
Hi @KieranCTaylor 
does this code represent the issue you are describing?

<details>
	<summary>code sample</summary>

```dart 
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) => MaterialApp(
    home: MyHomePage(),
  );
}

class MyHomePage extends StatelessWidget {
  @override
  Widget build(BuildContext context)=> Scaffold(
      body: Column(
        children: <Widget>[
          Container(
              color: Colors.yellow,
              height: 80,
            ),
          Container(
            height: MediaQuery.of(context).size.height - 80,
            child:ListView(
              children: <Widget> [for (int i = 0; i <100; ++i) Center(
                  child: Text(
                    '$i',
                    textScaleFactor: 3,
              ),),],
          ),),
        ], 
  ),);
}
```

</details>

**Comment by KieranCTaylor** [comment]
@iapicca It does if the listview.builder isn't wrapped in Expanded(). When it is wrapped in Expanded() it doesn't throw the same error.

**Comment by iapicca** [comment]
Hi @KieranCTaylor 
doesn't need to be an `Expanded` you can also use a `Container`
```dart
children: <Widget>[
          Container(
              color: Colors.yellow,
              height: 80,
            ),
          Container(
            height: MediaQuery.of(context).size.height-80,
            child: ListView.builder(
              itemCount: _list.length,
              itemBuilder: (BuildContext context, int index) => _list[index],
          ),),
        ], 
```
I believe the point is to wrap the list into a widget
that "constrains" the listview to be able to use it into a `column`;
does this answer your question?
thank you

**Comment by VladyslavBondarenko** [comment]
I hope the last comment helped, closing the issue.
Could everyone who still has this problem please file a new issue with the exact descriptions what happens, minimal reproducible sample code (if related), logs and the output of 'flutter doctor -v'  please.

**Comment by KieranCTaylor** [comment]
@VladyslavBondarenko  Sorry I never  responded, yes that fixed the issue! Thanks
