### ISSUE TITLE
[FlutterDaemon] [Error] Unable to retrieve device list!

### ISSUE THREAD

**Issue by EliasDeuss** [flutter/flutter#48057]
```
Dart Code extension: 3.7.1
Flutter extension: 3.7.1 (activated)
VS Code: 1.41.1
Platform: mac
HTTP_PROXY: undefined
NO_PROXY: undefined

Wed Jan 01 2020 [22:38:21 GMT-0800 (Pacific Standard Time)] Log file started
[10:38:21 PM] [General] [Info] Searching for SDKs...
[10:38:21 PM] [General] [Info] Environment PATH:
[10:38:21 PM] [General] [Info]     /usr/local/bin
[10:38:21 PM] [General] [Info]     /usr/bin
[10:38:21 PM] [General] [Info]     /bin
[10:38:21 PM] [General] [Info]     /usr/sbin
[10:38:21 PM] [General] [Info]     /sbin
[10:38:21 PM] [General] [Info]     /usr/local/go/bin
[10:38:21 PM] [General] [Info]     /Users/elias/flutter/bin
[10:38:21 PM] [General] [Info] Done!
[10:38:21 PM] [General] [Info] Found Flutter project at /Users/elias/Documents/GitHub/isontic-Education:
			Mobile? true
			Web? false
			Create Trigger? false
			Flutter Repo? false
[10:38:21 PM] [General] [Info] Searching for flutter
[10:38:21 PM] [General] [Info]     Looking for flutter in:
[10:38:21 PM] [General] [Info]         /Users/elias/Documents/GitHub/isontic-Education
[10:38:21 PM] [General] [Info]         /Users/elias/Documents/GitHub/isontic-Education/bin
[10:38:21 PM] [General] [Info]         /Users/elias/flutter/bin/
[10:38:21 PM] [General] [Info]         /Users/elias/Documents/GitHub/isontic-Education/.flutter
[10:38:21 PM] [General] [Info]         /Users/elias/Documents/GitHub/isontic-Education/.flutter/bin
[10:38:21 PM] [General] [Info]         /Users/elias/Documents/GitHub/isontic-Education/vendor/flutter
[10:38:21 PM] [General] [Info]         /Users/elias/Documents/GitHub/isontic-Education/vendor/flutter/bin
[10:38:21 PM] [General] [Info]         /usr/local/bin
[10:38:21 PM] [General] [Info]         /usr/bin
[10:38:21 PM] [General] [Info]         /bin
[10:38:21 PM] [General] [Info]         /usr/sbin
[10:38:21 PM] [General] [Info]         /sbin
[10:38:21 PM] [General] [Info]         /usr/local/go/bin
[10:38:21 PM] [General] [Info]         /Users/elias/flutter/bin
[10:38:21 PM] [General] [Info]     Found at:
[10:38:21 PM] [General] [Info]         /Users/elias/flutter/bin/
[10:38:21 PM] [General] [Info]         /Users/elias/flutter/bin
[10:38:21 PM] [General] [Info]     Candidate paths to be post-filtered:
[10:38:21 PM] [General] [Info]         /Users/elias/flutter
[10:38:21 PM] [General] [Info]         /Users/elias/flutter
[10:38:21 PM] [General] [Info]     Found at /Users/elias/flutter
[10:38:21 PM] [General] [Info]     Returning SDK path /Users/elias/flutter for flutter
[10:38:21 PM] [General] [Info] Searching for dart
[10:38:21 PM] [General] [Info]     Looking for dart in:
[10:38:21 PM] [General] [Info]         /Users/elias/flutter/bin/cache/dart-sdk
[10:38:21 PM] [General] [Info]         /Users/elias/flutter/bin/cache/dart-sdk/bin
[10:38:21 PM] [General] [Info]         /usr/local/bin
[10:38:21 PM] [General] [Info]         /usr/bin
[10:38:21 PM] [General] [Info]         /bin
[10:38:21 PM] [General] [Info]         /usr/sbin
[10:38:21 PM] [General] [Info]         /sbin
[10:38:21 PM] [General] [Info]         /usr/local/go/bin
[10:38:21 PM] [General] [Info]         /Users/elias/flutter/bin
[10:38:21 PM] [General] [Info]         /Users/elias/flutter/bin/cache/dart-sdk
[10:38:21 PM] [General] [Info]         /Users/elias/flutter/bin/cache/dart-sdk/bin
[10:38:21 PM] [General] [Info]     Found at:
[10:38:21 PM] [General] [Info]         /Users/elias/flutter/bin/cache/dart-sdk/bin
[10:38:21 PM] [General] [Info]         /Users/elias/flutter/bin/cache/dart-sdk/bin
[10:38:21 PM] [General] [Info]     Candidate paths to be post-filtered:
[10:38:21 PM] [General] [Info]         /Users/elias/flutter/bin/cache/dart-sdk
[10:38:21 PM] [General] [Info]         /Users/elias/flutter/bin/cache/dart-sdk
[10:38:21 PM] [General] [Info]     Found at /Users/elias/flutter/bin/cache/dart-sdk
[10:38:21 PM] [General] [Info]     Returning SDK path /Users/elias/flutter/bin/cache/dart-sdk for dart
[10:38:21 PM] [General] [Info] Activating Flutter extension for Dart, Flutter project...
[10:38:21 PM] [General] [Info] Extension:Startup timing: 48ms
[10:38:21 PM] [General] [Info] Analyzer:Startup timing: 366ms
[10:38:26 PM] [General] [Info] Returning cached promise for getSupportedPlatforms()
[10:38:26 PM] [General] [Info] Checking 2 projects for supported platforms
[10:38:26 PM] [General] [Info] Returning cached promise for getSupportedPlatforms()
[10:38:26 PM] [General] [Info] Supported platforms for the workspace are ios, android, web
[10:38:26 PM] [FlutterDaemon] [Error] idevice_id returned an error:
ERROR: Unable to retrieve device list!
[10:38:28 PM] [General] [Info] Analyzer:FirstAnalysis timing: 4737ms
```

flutter doctor

```
[✓] Flutter (Channel dev, v1.13.5, on Mac OS X 10.15.2 19C57, locale en-US)
    • Flutter version 1.13.5 at /Users/elias/flutter
    • Framework revision 41a911099b (13 days ago), 2019-12-19 13:48:02 -0800
    • Engine revision 0f90e6546b
    • Dart version 2.8.0 (build 2.8.0-dev.0.0 aa6709974d)

 
[!] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/elias/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses

[✓] Xcode - develop for iOS and macOS (Xcode 11.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.3, Build version 11C29
    • CocoaPods version 1.7.5

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 42.1.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] VS Code (version 1.41.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.7.1

[☠] Connected device (the doctor check crashed)
    ✗ Due to an error, the doctor check did not complete. If the error message below is not helpful, please let us know about this issue at https://github.com/flutter/flutter/issues.
    ✗ Exception: idevice_id returned an error:
      ERROR: Unable to retrieve device list!

    • #0      IMobileDevice.getAvailableDeviceIDs (package:flutter_tools/src/ios/mac.dart:184:9)
      <asynchronous suspension>
      #1      IOSDevice.getAttachedDevices (package:flutter_tools/src/ios/devices.dart:183:44)
      #2      IOSDevices.pollingGetDevices (package:flutter_tools/src/ios/devices.dart:115:57)
      #3      PollingDeviceDiscovery.devices (package:flutter_tools/src/device.dart:285:52)
      #4      DeviceManager.getAllConnectedDevices (package:flutter_tools/src/device.dart:140:46)
      <asynchronous suspension>
      #5      DeviceValidator.validate (package:flutter_tools/src/doctor.dart:860:54)
      #6      asyncGuard.<anonymous closure> (package:flutter_tools/src/base/async_guard.dart:111:32)
      #7      _rootRun (dart:async/zone.dart:1126:13)
      #8      _CustomZone.run (dart:async/zone.dart:1023:19)
      #9      _runZoned (dart:async/zone.dart:1518:10)
      #10     runZoned (dart:async/zone.dart:1502:12)
      #11     asyncGuard (package:flutter_tools/src/base/async_guard.dart:109:3)
      #12     Doctor.startValidatorTasks (package:flutter_tools/src/doctor.dart:158:9)
      #13     Doctor.diagnose (package:flutter_tools/src/doctor.dart:252:41)
      #14     _AsyncAwaitCompleter.start (dart:async-patch/async_patch.dart:47:6)
      #15     Doctor.diagnose (package:flutter_tools/src/doctor.dart:241:24)
      #16     DoctorCommand.runCommand (package:flutter_tools/src/commands/doctor.dart:58:39)
      #17     _AsyncAwaitCompleter.start (dart:async-patch/async_patch.dart:47:6)
      #18     DoctorCommand.runCommand (package:flutter_tools/src/commands/doctor.dart:44:42)
      #19     FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:626:18)
      #20     _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:75:64)
      #21     _rootRunUnary (dart:async/zone.dart:1134:38)
      #22     _CustomZone.runUnary (dart:async/zone.dart:1031:19)
      #23     _FutureListener.handleValue (dart:async/future_impl.dart:140:18)
      #24     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:682:45)
      #25     Future._propagateToListeners (dart:async/future_impl.dart:711:32)
      #26     Future._completeWithValue (dart:async/future_impl.dart:526:5)
      #27     Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:556:7)
      #28     _rootRun (dart:async/zone.dart:1126:13)
      #29     _CustomZone.run (dart:async/zone.dart:1023:19)
      #30     _CustomZone.runGuarded (dart:async/zone.dart:925:7)
      #31     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:965:23)
      #32     _microtaskLoop (dart:async/schedule_microtask.dart:43:21)
      #33     _startMicrotaskLoop (dart:async/schedule_microtask.dart:52:5)
      #34     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
      #35     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:175:5)


! Doctor found issues in 2 categories.
```

**Comment by cydestiny** [comment]
One or more of the connections might be faulty, have you tried disconnecting all connected devices? 

(i.e. everything including re-installing/updating the x-code simulator and/or physical devices which are connected either **pragmatically**, **physically** or **wireless-ly**).

**Comment by iapicca** [comment]
Hi @EliasDeuss 
are you experiencing this issue with` virtual devices`, `physical devices` or both?
thank you

**Comment by EliasDeuss** [comment]
I was having an issue with both, I had to restart my computer. It’s crashed originally when I had the app running on a connected iPhone, then it would crash every time I would try to select or search for physical or virtual device’s.

**Comment by Kraci** [comment]
> I was having an issue with both, I had to restart my computer. It’s crashed originally when I had the app running on a connected iPhone, then it would crash every time I would try to select or search for physical or virtual device’s. @iapicca

I have exactly same issue right now. Don't know what to do.

**Comment by jmagman** [comment]
https://github.com/flutter/flutter/pull/50252  is in [1.15.2]( https://flutter.dev/docs/development/tools/sdk/releases?tab=macos), so currently [master, dev, and beta](https://github.com/flutter/flutter/wiki/Flutter-build-release-channels).

**Comment by R3ll36** [comment]
[✓] Flutter (Channel unknown, v1.12.13+hotfix.8, on Mac OS X 10.14.5 18F132, locale en-IT)
    • Flutter version 1.12.13+hotfix.8 at /Users/cosminrus/Utils/flutter
    • Framework revision 0b8abb4724 (8 weeks ago), 2020-02-11 11:44:36 -0800
    • Engine revision e1e6ced81d
    • Dart version 2.7.0

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/cosminrus/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.3.1, Build version 11C504
    • CocoaPods version 1.8.4

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 44.0.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] VS Code (version 1.43.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.9.1

[☠] Connected device (the doctor check crashed)
    ✗ Due to an error, the doctor check did not complete. If the error message below is not helpful, please let us know about this issue at https://github.com/flutter/flutter/issues.
    ✗ Exception: idevice_id returned an error:
      ERROR: Unable to retrieve device list!

    • #0      IMobileDevice.getAvailableDeviceIDs (package:flutter_tools/src/ios/mac.dart:184:9)
      <asynchronous suspension>
      #1      IOSDevice.getAttachedDevices (package:flutter_tools/src/ios/devices.dart:183:44)
      #2      IOSDevices.pollingGetDevices (package:flutter_tools/src/ios/devices.dart:115:57)
      #3      PollingDeviceDiscovery.devices (package:flutter_tools/src/device.dart:285:52)
      #4      DeviceManager.getAllConnectedDevices (package:flutter_tools/src/device.dart:140:46)
      <asynchronous suspension>
      #5      DeviceValidator.validate (package:flutter_tools/src/doctor.dart:851:54)
      #6      asyncGuard.<anonymous closure> (package:flutter_tools/src/base/async_guard.dart:111:32)
      #7      _rootRun (dart:async/zone.dart:1126:13)
      #8      _CustomZone.run (dart:async/zone.dart:1023:19)
      #9      _runZoned (dart:async/zone.dart:1518:10)
      #10     runZoned (dart:async/zone.dart:1502:12)
      #11     asyncGuard (package:flutter_tools/src/base/async_guard.dart:109:3)
      #12     Doctor.startValidatorTasks (package:flutter_tools/src/doctor.dart:158:9)
      #13     Doctor.diagnose (package:flutter_tools/src/doctor.dart:252:41)
      #14     _AsyncAwaitCompleter.start (dart:async-patch/async_patch.dart:45:6)
      #15     Doctor.diagnose (package:flutter_tools/src/doctor.dart:241:24)
      #16     DoctorCommand.runCommand (package:flutter_tools/src/commands/doctor.dart:59:39)
      #17     _AsyncAwaitCompleter.start (dart:async-patch/async_patch.dart:45:6)
      #18     DoctorCommand.runCommand (package:flutter_tools/src/commands/doctor.dart:45:42)
      #19     FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:615:18)
      #20     _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:73:64)
      #21     _rootRunUnary (dart:async/zone.dart:1134:38)
      #22     _CustomZone.runUnary (dart:async/zone.dart:1031:19)
      #23     _FutureListener.handleValue (dart:async/future_impl.dart:139:18)
      #24     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:680:45)
      #25     Future._propagateToListeners (dart:async/future_impl.dart:709:32)
      #26     Future._completeWithValue (dart:async/future_impl.dart:524:5)
      #27     Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:554:7)
      #28     _rootRun (dart:async/zone.dart:1126:13)
      #29     _CustomZone.run (dart:async/zone.dart:1023:19)
      #30     _CustomZone.runGuarded (dart:async/zone.dart:925:7)
      #31     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:965:23)
      #32     _microtaskLoop (dart:async/schedule_microtask.dart:43:21)
      #33     _startMicrotaskLoop (dart:async/schedule_microtask.dart:52:5)
      #34     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
      #35     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:175:5)


! Doctor found issues in 1 category.

**Comment by jmagman** [comment]
> Thoughts?
> 
> [✓] Flutter (Channel unknown, v1.12.13+hotfix.8, on Mac OS X 10.14.5 18F132, locale en-IT)

> #50252 is in [v1.15.2](https://flutter.dev/docs/development/tools/sdk/releases?tab=macos), so currently [master, dev, and beta](https://github.com/flutter/flutter/wiki/Flutter-build-release-channels).
