### ISSUE TITLE
Atom bug with newest Flutter upgrade?

### ISSUE THREAD

**Issue by emshack** [flutter/flutter#4809]
## Steps to Reproduce

I just ran flutter upgrade, and my app no longer runs correctly in Atom. When I run it in Atom, the device screen stays dark and never populates with my app contents. However, if I run the app through terminal, it works. This is true when running on both a physical Android tablet and the iOS emulator.

## Flutter Doctor

[✓] Flutter (on Mac OS, channel alpha)
    • Flutter at /Users/emshack/vanadium/flutter
    • Framework revision 9c0c0225a6 (7 days ago), engine revision bb9865538b
[✓] Android toolchain - develop for Android devices (Android SDK 23.0.2)
    • Android SDK at /Users/emshack/Library/Android/sdk
    • Platform android-23, build-tools 23.0.2
    • Java(TM) SE Runtime Environment (build 1.8.0_60-b27)
[✓] iOS toolchain - develop for iOS devices (Xcode 7.3.1)
    • XCode at /Applications/Xcode.app/Contents/Developer
    • Xcode 7.3.1, Build version 7D1014
    x ideviceinstaller not available; this is used to discover connected iOS devices.
      Install via 'brew install ideviceinstaller'.
    x ios-deploy not available; this is used to deploy to connected iOS devices.
      Install via 'brew install ios-deploy'.
[✓] Atom - a lightweight development environment for Flutter
    • flutter plugin version 0.2.3
    • dartlang plugin version 0.6.30

## Logs and Crash Reports

When running on iOS emulator from Atom:
```
Waiting to be able to obtain lock of Flutter binary artifacts directory...
Running lib/main.dart on iPhone 6s Plus...
com.apple.CoreSimulator.SimDevice.8CB7B336-B87F-4B71-A3A8-007995205A51.launchd_sim[22112] (UIKitApplication:com.yourcompany.testapp[0x6bd]: Service exited due to signal: Terminated: 15
CoreSimulatorBridge: Requesting launch of com.yourcompany.testapp with options: {
	    arguments =     (
	        "--flx=/Users/emshack/vanadium/experimental/users/emshack/EmGen/build/app.flx",
	        "--dart-main=/Users/emshack/vanadium/experimental/users/emshack/EmGen/lib/main.dart",
	        "--packages=/Users/emshack/vanadium/experimental/users/emshack/EmGen/.packages",
	        "--enable-checked-mode",
	        "--start-paused",
	        "--observatory-port=16192"
	    );
	    environment =     {
	    };
	}
SpringBoard: Application 'UIKitApplication:com.yourcompany.testapp[0x6bd]' exited abnormally via signal.
backboardd: SecTaskLoadEntitlements failed error=22 cs_flags=200, task->pid_self=-1
backboardd: SecTaskCopyDebugDescription: Runner[51258]
backboardd: SecTaskLoadEntitlements failed error=22 cs_flags=200, task->pid_self=-1
backboardd: SecTaskCopyDebugDescription: Runner[51258]
backboardd: SecTaskLoadEntitlements failed error=22 cs_flags=200, task->pid_self=-1
backboardd: SecTaskCopyDebugDescription: Runner[51258]
backboardd: SecTaskLoadEntitlements failed error=22 cs_flags=200, task->pid_self=-1
backboardd: SecTaskCopyDebugDescription: Runner[51258]
backboardd: SecTaskLoadEntitlements failed error=22 cs_flags=200, task->pid_self=-1
backboardd: SecTaskCopyDebugDescription: Runner[51258]
assertion failed: 15F34 13E230: libxpc.dylib + 57882 [66C28065-C9DB-3C8E-926F-5A40210A6D1B]: 0x7d
Observatory listening on http://127.0.0.1:16192
SpringBoard: [MPUSystemMediaControls] Updating supported commands for now playing application.
Application running.
Type "h" or F1 for help and "q", F10, or ctrl-c to quit.
[INFO:FlutterDynamicServiceLoader.mm(107)] 0 custom service definitions registered
```
When running on iOS emulator from terminal:
```
Running lib/main.dart on iPhone 6s Plus...
SpringBoard: HW kbd: Failed to set (null) as keyboard focus
com.apple.CoreSimulator.SimDevice.8CB7B336-B87F-4B71-A3A8-007995205A51.launchd_sim[22112] (UIKitApplication:com.yourcompany.testapp[0xb151]: Service exited due to signal: Terminated: 15
CoreSimulatorBridge: Requesting launch of com.yourcompany.testapp with options: {
	    arguments =     (
	        "--flx=/Users/emshack/vanadium/experimental/users/emshack/EmGen/build/app.flx",
	        "--dart-main=/Users/emshack/vanadium/experimental/users/emshack/EmGen/lib/main.dart",
	        "--packages=/Users/emshack/vanadium/experimental/users/emshack/EmGen/.packages",
	        "--enable-checked-mode",
	        "--observatory-port=8100"
	    );
	    environment =     {
	    };
	}
SpringBoard: Application 'UIKitApplication:com.yourcompany.testapp[0xb151]' exited abnormally via signal.
assertiond: notify_suspend_pid() failed with error 7
backboardd: SecTaskLoadEntitlements failed error=22 cs_flags=200, task->pid_self=-1
backboardd: SecTaskCopyDebugDescription: Runner[51993]
backboardd: SecTaskLoadEntitlements failed error=22 cs_flags=200, task->pid_self=-1
backboardd: SecTaskCopyDebugDescription: Runner[51993]
backboardd: SecTaskLoadEntitlements failed error=22 cs_flags=200, task->pid_self=-1
backboardd: SecTaskCopyDebugDescription: Runner[51993]
backboardd: SecTaskLoadEntitlements failed error=22 cs_flags=200, task->pid_self=-1
backboardd: SecTaskCopyDebugDescription: Runner[51993]
backboardd: SecTaskLoadEntitlements failed error=22 cs_flags=200, task->pid_self=-1
backboardd: SecTaskCopyDebugDescription: Runner[51993]
assertion failed: 15F34 13E230: libxpc.dylib + 57882 [66C28065-C9DB-3C8E-926F-5A40210A6D1B]: 0x7d
SpringBoard: [MPUSystemMediaControls] Updating supported commands for now playing application.
Observatory listening on http://127.0.0.1:8100
[INFO:FlutterDynamicServiceLoader.mm(107)] 0 custom service definitions registered
Application running.
Type "h" or F1 for help and "q", F10, or ctrl-c to quit.
```
When running on Nexus 9 tablet from Atom:
```
Waiting to be able to obtain lock of Flutter binary artifacts directory...
Running lib/main.dart on Nexus 9...
--------- beginning of main
W/ActivityManager: Activity pause timeout for ActivityRecord{b682908 u0 com.example.emgen/org.domokit.sky.shell.SkyActivity t3556}
Observatory listening on http://127.0.0.1:16172
Diagnostic server listening on http://127.0.0.1:56168
Application running.
Type "h" or F1 for help, "r" or F5 to restart the app, and "q", F10, or ctrl-c to quit.
```
When running on Nexus 9 tablet from terminal:
```
Running lib/main.dart on Nexus 9...
--------- beginning of system
Observatory listening on http://127.0.0.1:52191
Diagnostic server listening on http://127.0.0.1:52194
Application running.
Type "h" or F1 for help, "r" or F5 to restart the app, and "q", F10, or ctrl-c to quit.
I/flutter : ══╡ EXCEPTION CAUGHT BY NETWORKING HTTP LIBRARY ╞═══════════════════════════════════════════════════
I/flutter : The following MojoInternalError object was thrown while sending bytes to the Mojo network library:
I/flutter : MojoInternalError: Failed to register the MojoHandle.
I/flutter : When the exception was thrown, this was the stack:
I/flutter : #0      MojoEventSubscription.MojoEventSubscription (package:mojo/src/event_subscription.dart:31)
I/flutter : #1      DataPipeDrainer.DataPipeDrainer (package:mojo/src/drain_data.dart:15)
I/flutter : #2      DataPipeDrainer.drainHandle (package:mojo/src/drain_data.dart:67)
I/flutter : #3      MojoClient._send.<anonymous closure>.<<anonymous closure>_async_body> (package:flutter/src/http/mojo_client.dart:186)
I/flutter : (elided 3 frames from package dart:async)
I/flutter : ════════════════════════════════════════════════════════════════════════════════════════════════════
```

**Comment by devoncarew** [comment]
Can you re-start atom to see if that helps? It runs the flutter tool as a background process - restarting atom will restart the flutter daemon, and pick up the new code from the flutter upgrade.

And can you open devtools in atom (View > Developer > Toggle Developer Tools), change to the devtools console, and see if there are any exceptions or errors listed there? I'm not sure what's going on so any other diagnostic info you can give is much appreciated :)

**Comment by emshack** [comment]
Ah, thanks, restarting atom worked! After restarting I opened devtools, but did not see any exceptions or errors.
