### ISSUE TITLE
Gradle task assembleRelease failed with exit code 1 - after change package name

### ISSUE THREAD

**Issue by isadoraoliv** [flutter/flutter#48146]
Note: before changing the package name was working normally, but the application is large and I can't publish it without changing it

## Steps to Reproduce

1. I'm trying to run my app using command...
flutter run

2. The process fails and generates the following error

Gradle task assembleDebug failed with exit code 1

## Logs

`flutter run --verbose`
<details>
	<summary>logs</summary>

```bash
#0      throwToolExit (package:flutter_tools/src/base/common.dart:28:3)
#1      _buildGradleProjectV2 (package:flutter_tools/src/android/gradle.dart:751:5)
<asynchronous suspension>
#2      buildGradleProject (package:flutter_tools/src/android/gradle.dart:494:14)
<asynchronous suspension>
#3      buildApk (package:flutter_tools/src/android/apk.dart:34:9)
<asynchronous suspension>
#4      AndroidDevice.startApp (package:flutter_tools/src/android/android_device.dart:486:13)
<asynchronous suspension>
#5      FlutterDevice.runHot (package:flutter_tools/src/resident_runner.dart:378:54)
<asynchronous suspension>
#6      HotRunner.run (package:flutter_tools/src/run_hot.dart:254:39)
<asynchronous suspension>
#7      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:472:37)
<asynchronous suspension>
#8      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:490:18)
#9      _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:71:64)
#10     _rootRunUnary (dart:async/zone.dart:1132:38)
#11     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#12     _FutureListener.handleValue (dart:async/future_impl.dart:137:18)
#13     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:678:45)
#14     Future._propagateToListeners (dart:async/future_impl.dart:707:32)
#15     Future._completeWithValue (dart:async/future_impl.dart:522:5)
#16     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:30:15)
#17     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:288:13)
#18     RunCommand.usageValues (package:flutter_tools/src/commands/run.dart)
#19     _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:71:64)
#20     _rootRunUnary (dart:async/zone.dart:1132:38)
#21     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#22     _FutureListener.handleValue (dart:async/future_impl.dart:137:18)
#23     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:678:45)
#24     Future._propagateToListeners (dart:async/future_impl.dart:707:32)
#25     Future._completeWithValue (dart:async/future_impl.dart:522:5)
#26     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:30:15)
#27     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:288:13)
#28     AndroidDevice.isLocalEmulator (package:flutter_tools/src/android/android_device.dart)
#29     _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:71:64)
#30     _rootRunUnary (dart:async/zone.dart:1132:38)
#31     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#32     _FutureListener.handleValue (dart:async/future_impl.dart:137:18)
#33     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:678:45)
#34     Future._propagateToListeners (dart:async/future_impl.dart:707:32)
#35     Future._completeWithValue (dart:async/future_impl.dart:522:5)
#36     Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:552:7)
#37     _rootRun (dart:async/zone.dart:1124:13)
#38     _CustomZone.run (dart:async/zone.dart:1021:19)
#39     _CustomZone.runGuarded (dart:async/zone.dart:923:7)
#40     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:963:23)
#41     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#42     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#43     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:116:13)
#44     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:173:5)

```

</details>

`flutter analyze` 
<details>
	<summary>logs</summary>

```bash
 info • Unused import: 'package:flutter/foundation.dart' • lib/config/text_link.dart:2:8 • unused_import
   info • The value of the local variable 'tutorial' isn't used • lib/pages/completa_cadastro.page.dart:480:17 • unused_local_variable
   info • This class (or a class which this class inherits from) is marked as '@immutable', but one or more of its instance fields are not final:
          DetalhesGamificacaoPage.ranking • lib/pages/detalhes_gamificacoes.page.dart:19:7 • must_be_immutable
   info • Name non-constant identifiers using lowerCamelCase • lib/pages/domain/configs/app_configs.dart:8:10 • non_constant_identifier_names
   info • Name non-constant identifiers using lowerCamelCase • lib/pages/domain/configs/app_configs.dart:10:78 • non_constant_identifier_names
   info • Name non-constant identifiers using lowerCamelCase • lib/pages/domain/usuario.dart:29:9 • non_constant_identifier_names
   info • Name non-constant identifiers using lowerCamelCase • lib/pages/domain/usuario.dart:30:9 • non_constant_identifier_names
   info • Name non-constant identifiers using lowerCamelCase • lib/pages/domain/usuario.dart:34:101 • non_constant_identifier_names
   info • Name non-constant identifiers using lowerCamelCase • lib/pages/domain/usuario.dart:34:119 • non_constant_identifier_names
   info • This class (or a class which this class inherits from) is marked as '@immutable', but one or more of its instance fields are not final: GamificacaoRanking.ranking •
          lib/pages/gamificacao_ranking.page.dart:18:7 • must_be_immutable
   info • The value of the field '_firebaseMessaging' isn't used • lib/pages/home.page.dart:58:29 • unused_field
   info • The value of the field '_appConfigsService' isn't used • lib/pages/home.page.dart:59:36 • unused_field
   info • This function has a return type of 'Future<bool>', but doesn't end with a return statement • lib/pages/home.page.dart:114:20 • missing_return
   info • Await only futures • lib/pages/home.page.dart:136:13 • await_only_futures
   info • Await only futures • lib/pages/home.page.dart:928:25 • await_only_futures
   info • This function has a return type of 'Container', but doesn't end with a return statement • lib/pages/minhas_ofertas.page.dart:411:46 • missing_return
   info • This function has a return type of 'Container', but doesn't end with a return statement • lib/pages/ofertas_em_cache.page.dart:316:46 • missing_return
   info • The value of the field '_storageController' isn't used • lib/pages/reportar_erro.page.dart:21:8 • unused_field
   info • The value of the local variable 'deviceWidth' isn't used • lib/pages/reportar_erro.page.dart:174:12 • unused_local_variable
   info • The value of the local variable 'deviceHeight' isn't used • lib/pages/reportar_erro.page.dart:175:12 • unused_local_variable
   info • The value of the field '_pushService' isn't used • lib/pages/settings.page.dart:30:21 • unused_field
   info • The value of the field '_listHeight' isn't used • lib/plugins/edicao_oferta_card.dart:68:12 • unused_field
   info • The value of the field '_listHeight2' isn't used • lib/plugins/edicao_oferta_card.dart:69:12 • unused_field
   info • Don't explicitly initialize variables to null • lib/plugins/gamificacoes_list_card.dart:35:9 • avoid_init_to_null
   info • This function has a return type of 'bool', but doesn't end with a return statement • lib/plugins/gamificacoes_list_card.dart:59:102 • missing_return
warning • The parameter 'onPressed' is required • lib/plugins/item_card.dart:428:21 • missing_required_param
   info • This function has a return type of 'bool', but doesn't end with a return statement • lib/plugins/stateful_list_view.dart:58:23 • missing_return
   info • Avoid using braces in interpolation when not needed • lib/services/database.service.dart:97:17 • unnecessary_brace_in_string_interps
   info • Avoid using braces in interpolation when not needed • lib/services/database.service.dart:118:17 • unnecessary_brace_in_string_interps
   info • Avoid using braces in interpolation when not needed • lib/services/generic.service.dart:409:59 • unnecessary_brace_in_string_interps
   info • Avoid using braces in interpolation when not needed • lib/services/generic.service.dart:409:66 • unnecessary_brace_in_string_interps
   info • Avoid using braces in interpolation when not needed • lib/services/generic.service.dart:411:36 • unnecessary_brace_in_string_interps
   info • Avoid using braces in interpolation when not needed • lib/services/generic.service.dart:411:43 • unnecessary_brace_in_string_interps
   info • The value of the field '_storageService' isn't used • lib/services/geofencing.service.dart:25:31 • unused_field
   info • The value of the field '_appConfigsService' isn't used • lib/services/geofencing.service.dart:26:34 • unused_field
   info • Name non-constant identifiers using lowerCamelCase • lib/services/geofencing.service.dart:27:19 • non_constant_identifier_names
   info • Name non-constant identifiers using lowerCamelCase • lib/services/geofencing.service.dart:132:25 • non_constant_identifier_names
   info • Unused import: '../config/app_config.dart' • lib/services/places_search_api.dart:7:8 • unused_import
   info • Name non-constant identifiers using lowerCamelCase • lib/services/push.service.dart:443:29 • non_constant_identifier_names
   info • Name non-constant identifiers using lowerCamelCase • lib/services/push.service.dart:443:51 • non_constant_identifier_names
   info • Name non-constant identifiers using lowerCamelCase • lib/services/push.service.dart:443:71 • non_constant_identifier_names
   info • The value of the local variable 'tipo' isn't used • lib/services/push.service.dart:533:12 • unused_local_variable

42 issues found. (ran in 12.5s)
```

</details>

`flutter doctor -v`

```console
[✓] Flutter (Channel stable, v1.9.1+hotfix.2, on Mac OS X 10.13.6 17G8037, locale pt-BR)
    • Flutter version 1.9.1+hotfix.2 at /opt/flutter
    • Framework revision 2d2a1ffec9 (4 months ago), 2019-09-06 18:39:49 -0700
    • Engine revision b863200c37
    • Dart version 2.5.0

 
[!] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/feliciano/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses

[✓] Xcode - develop for iOS and macOS (Xcode 10.1)
    • Xcode at /Applications/Xcode10.1.app/Contents/Developer
    • Xcode 10.1, Build version 10B61
    • CocoaPods version 1.8.1

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 40.0.2
    • Dart plugin version 191.8423
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[!] VS Code (version 1.41.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    ✗ Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 10 (API 29) (emulator)

! Doctor found issues in 2 categories.
```

<details>
	<summary>android/build.gradle </summary>

```gradle
buildscript {
    ext.kotlin_version = '1.2.31'

    repositories {
        google()
        jcenter()
    }

    dependencies {

        classpath 'com.google.gms:google-services:4.3.2'

        classpath 'com.android.tools.build:gradle:3.5.0'

        classpath 'org.jetbrains.kotlin:kotlin-gradle-plugin:1.3.10'
        
    }
}

allprojects {
    repositories {
        google()
        jcenter()
    }
}

rootProject.buildDir = '../build'
subprojects {
    project.buildDir = "${rootProject.buildDir}/${project.name}"
}
subprojects {
    project.configurations.all {
        resolutionStrategy.eachDependency { details ->
            if (details.requested.group == 'com.android.support'
                    && !details.requested.name.contains('multidex') ) {
                details.useVersion "27.0.3"
            }
        }
    }
}

task clean(type: Delete) {
    delete rootProject.buildDir
}
```

</details>

<details>
	<summary>android/app/build.gradle</summary>

```gradle
def localProperties = new Properties()
def localPropertiesFile = rootProject.file('local.properties')
if (localPropertiesFile.exists()) {
    localPropertiesFile.withReader('UTF-8') { reader ->
        localProperties.load(reader)
    }
}

def flutterRoot = localProperties.getProperty('flutter.sdk')
if (flutterRoot == null) {
    throw new GradleException("Flutter SDK not found. Define location with flutter.sdk in the local.properties file.")
}

def flutterVersionCode = localProperties.getProperty('flutter.versionCode')
if (flutterVersionCode == null) {
    flutterVersionCode = '1'
}

def flutterVersionName = localProperties.getProperty('flutter.versionName')
if (flutterVersionName == null) {
    flutterVersionName = '1.0'
}

def keystoreProperties = new Properties()
def keystorePropertiesFile = rootProject.file('key.properties')
if (keystorePropertiesFile.exists()) {
    keystoreProperties.load(new FileInputStream(keystorePropertiesFile))
}

apply plugin: 'com.android.application'
apply from: "$flutterRoot/packages/flutter_tools/gradle/flutter.gradle"

apply plugin: 'kotlin-android'

android {
    compileSdkVersion 28


    lintOptions {
        disable 'InvalidPackage'
    }
    aaptOptions {
        noCompress 'tflite'
    }

    defaultConfig {
        // TODO: Specify your own unique Application ID (https://developer.android.com/studio/build/application-id.html).
        applicationId "br.com.mercado_mineiro"
        minSdkVersion 21
        targetSdkVersion 28
        versionCode flutterVersionCode.toInteger()
        versionName flutterVersionName
        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"


        /*splits {
            abi {
                // Enables building multiple APKs per ABI.

                enable true
                // By default all ABIs are included, so use reset() and include to specify that we only
                // want APKs for armeabi-v7a and arm64-v8a.

                // Resets the list of ABIs that Gradle should create APKs for to none.
                reset()

                // Specifies a list of ABIs that Gradle should create APKs for.
                include "armeabi-v7a", "arm64-v8a"

                // Specifies that we do not want to also generate a universal APK that includes all ABIs.
                universalApk false
            }
        }*/

        /*ndk {
            abiFilters 'armeabi-v7a','arm64-v8a','x86','x86_64' //atualizado, deve ser compativel com as versoes anteriores (android build apk --release)
        }*/
    }

    //ativar a reducao, ofuscacao e otimizacao
    buildTypes {
        release {

            minifyEnabled true

            shrinkResources true

            proguardFiles getDefaultProguardFile(
                    'proguard-android-optimize.txt'),
                    'proguard-rules.pro'
        }
    }

    signingConfigs {
        release {
            keyAlias keystoreProperties['keyAlias']
            keyPassword keystoreProperties['keyPassword']
            storeFile file(keystoreProperties['storeFile'])
            storePassword keystoreProperties['storePassword']
        }
    }
    
    buildTypes {
        release {
            signingConfig signingConfigs.release
        }
    }
}

flutter {
    source '../..'
}

dependencies {
    def work_version = "1.0.0-alpha08"
    implementation "android.arch.work:work-runtime:$work_version"
    implementation "android.arch.work:work-firebase:$work_version"
    testImplementation 'junit:junit:4.12'
    androidTestImplementation 'androidx.test:runner:1.1.0-alpha4'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.1.0-alpha4'
    implementation "org.jetbrains.kotlin:kotlin-stdlib-jre7:$kotlin_version"
    implementation 'com.google.firebase:firebase-core:16.0.4'
    implementation 'com.google.firebase:firebase-messaging:17.4.0'
    //androidTestImplementation 'com.google.firebase:firebase-ml-model-interpreter:16.2.4'
    implementation 'com.android.volley:volley:1.1.1'
}

apply plugin: com.google.gms.googleservices.GoogleServicesPlugin
```

</details>

<details>
	<summary>gradle-wrapper.properties</summary>

```console
distributionBase=GRADLE_USER_HOME
distributionPath=wrapper/dists
zipStoreBase=GRADLE_USER_HOME
zipStorePath=wrapper/dists
distributionUrl=https\://services.gradle.org/distributions/gradle-5.4.1-all.zip
```

</details>

**Comment by jonahwilliams** [comment]
` exit code 1` just means the task failed, it is not itself an error. The verbose Gradle logs should contain the actual exception, but this is cut off in your logs.

**Comment by jmagman** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!

Thanks for your contribution.
