### ISSUE TITLE
flutter doctor not working.am new to flutter

### ISSUE THREAD

**Issue by munene5470** [flutter/flutter#48144]
[flutter_03.log](https://github.com/flutter/flutter/files/4020550/flutter_03.log)

## Steps to Reproduce

1. ...
2. ...
3. ...

## Logs

```
```

```
```

**Comment by jonahwilliams** [comment]
The command:

Flutter crash report; please file at https://github.com/flutter/flutter/issues.

## command

flutter doctor

## exception

ProcessException: ProcessException: Permission denied
  Command: /opt/android-studio-ide-191.5977832-linux/android-studio/jre/bin/java -version

```
#0      _ProcessImpl._runAndWait (dart:io-patch/process_patch.dart:498:7)
#1      _runNonInteractiveProcessSync (dart:io-patch/process_patch.dart:643:18)
#2      Process.runSync (dart:io-patch/process_patch.dart:68:12)
#3      LocalProcessManager.runSync (package:process/src/interface/local_process_manager.dart:93:20)
#4      _DefaultProcessUtils.runSync (package:flutter_tools/src/base/process.dart:368:50)
#5      AndroidStudio._init (package:flutter_tools/src/android/android_studio.dart:299:45)
#6      new AndroidStudio (package:flutter_tools/src/android/android_studio.dart:40:5)
#7      new AndroidStudio.fromHomeDot (package:flutter_tools/src/android/android_studio.dart:97:14)
#8      AndroidStudio._allLinuxOrWindows (package:flutter_tools/src/android/android_studio.dart:243:54)
#9      AndroidStudio.allInstalled (package:flutter_tools/src/android/android_studio.dart:174:40)
#10     AndroidStudioValidator.allValidators (package:flutter_tools/src/android/android_studio_validator.dart:20:55)
#11     _DefaultDoctorValidatorsProvider.validators (package:flutter_tools/src/doctor.dart:67:33)
#12     Doctor.validators (package:flutter_tools/src/doctor.dart:145:46)
#13     Doctor.startValidatorTasks (package:flutter_tools/src/doctor.dart:151:39)
#14     Doctor.diagnose (package:flutter_tools/src/doctor.dart:252:41)
#15     DoctorCommand.runCommand (package:flutter_tools/src/commands/doctor.dart:59:39)
#16     FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:615:18)
#17     _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:73:64)
#18     _rootRunUnary (dart:async/zone.dart:1134:38)
#19     _CustomZone.runUnary (dart:async/zone.dart:1031:19)
#20     _FutureListener.handleValue (dart:async/future_impl.dart:139:18)
#21     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:680:45)
#22     Future._propagateToListeners (dart:async/future_impl.dart:709:32)
#23     Future._completeWithValue (dart:async/future_impl.dart:524:5)
#24     Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:554:7)
#25     _rootRun (dart:async/zone.dart:1126:13)
#26     _CustomZone.run (dart:async/zone.dart:1023:19)
#27     _CustomZone.runGuarded (dart:async/zone.dart:925:7)
#28     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:965:23)
#29     _microtaskLoop (dart:async/schedule_microtask.dart:43:21)
#30     _startMicrotaskLoop (dart:async/schedule_microtask.dart:52:5)
#31     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
#32     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:175:5)
```

## flutter doctor

**Comment by munene5470** [comment]
i was just following the steps in the documentation about flutter installation only to find myself in this dead end.whats the way out?

**Comment by jonahwilliams** [comment]
It looks like your installed android studio doesn't have execute permissions, which means flutter can't actually use it. Did you follow the instructions at https://flutter.dev/docs/get-started/install/linux ?

**Comment by VladyslavBondarenko** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore going to close it. 
Could everyone who still has this problem please file a new issue with the exact descriptions what happens, logs and the output of `flutter doctor -v`  please.
