### ISSUE TITLE
"/Users/flutter/.cocoon/flutter/bin/flutter build ios" failed with exit code 1

### ISSUE THREAD

**Issue by keyonghan** [flutter/flutter#48157]
Multiple agents are hitting "/Users/flutter/.cocoon/flutter/bin/flutter build ios" failed with exit code 1.

When directly running from helloWorld: `flutter build ios` OR running devicelab test:

> ├─Building Dart code...                                    15.0s
 ├─Generating dSYM file...                                   0.1s
 ├─Stripping debug symbols...                                0.0s
 ├─Assembling Flutter resources...                           0.8s
 └─Compiling, linking and signing...                         0.6s
Xcode build done.                                           18.8s
Failed to build iOS app
Error output from Xcode build:
↳
    ** BUILD FAILED **
Xcode's output:
↳ /var/folders/s3/87ghg_l11tg2w5_hbdz2ssj80000gn/T/tmp.Bs9sXptw/hellowworld/ios/Runner/GeneratedPluginRegistrant.h:8:9: note: while building module 'Flutter' imported from
>  /var/folders/s3/87ghg_l11tg2w5_hbdz2ssj80000gn/T/tmp.Bs9sXptw/hellowworld/ios/Runner/GeneratedPluginRegistrant.h:8:
    #import <Flutter/Flutter.h>
            ^
    <module-includes>:1:9: note: in file included from <module-includes>:1:
    #import "Headers/Flutter.h"
            ^
    >/var/folders/s3/87ghg_l11tg2w5_hbdz2ssj80000gn/T/tmp.Bs9sXptw/hellowworld/ios/Flutter/Flutter.framework/Headers/Flutter.h:54:10: note: in file included from
    /var/folders/s3/87ghg_l11tg2w5_hbdz2ssj80000gn/T/tmp.Bs9sXptw/hellowworld/ios/Flutter/Flutter.framework/Headers/Flutter.h:54:
    #include "FlutterAppDelegate.h"
             ^
    /var/folders/s3/87ghg_l11tg2w5_hbdz2ssj80000gn/T/tmp.Bs9sXptw/hellowworld/ios/Flutter/Flutter.framework/Headers/FlutterAppDelegate.h:11:10: note: in file included from
    /var/folders/s3/87ghg_l11tg2w5_hbdz2ssj80000gn/T/tmp.Bs9sXptw/hellowworld/ios/Flutter/Flutter.framework/Headers/FlutterAppDelegate.h:11:
    #include "FlutterPlugin.h"
...
It appears that your application still contains the default signing identifier.
Try replacing 'com.example' with your signing id in Xcode:
WARN   open ios/Runner.xcworkspace
WARN Encountered error while building for device.

Following @jmagman suggestion to remove: `~/Library/Developer/Xcode/DerivedData/`
Then from hellowWorld `flutter build ios` passed.
However when running devicelab test:
`dart bin/agent.dart run -r HEAD -t flutter_gallery_ios__start_up`

> 2020-01-03T16:28:23.617452: INFO able-to-perform-health-check: succeeded
2020-01-03T16:28:23.619936: INFO 
2020-01-03T16:28:23.620022: INFO ••• Get Flutter! •••
2020-01-03T16:28:24.355367: ERROR ERROR: FileSystemException: Deletion failed, path = '/Users/flutter/.cocoon/flutter' (OS Error: Directory not empty, errno = 66)
#0      _Directory._deleteSync (dart:io/directory_impl.dart:206:7)
#1      FileSystemEntity.deleteSync (dart:io/file_system_entity.dart:464:47)
#2      rrm (package:cocoon_agent/src/utils.dart:149:35)
#3      getFlutter (package:cocoon_agent/src/utils.dart:530:5)
asynchronous suspension
#4      getFlutterAt (package:cocoon_agent/src/utils.dart:278:9)
asynchronous suspension
#5      RunCommand.run (package:cocoon_agent/src/commands/run.dart:60:15)
asynchronous suspension
#6      main (file:///Users/flutter/cocoon/agent/bin/agent.dart:63:19)
asynchronous suspension
#7      _startIsolate. anonymous closure (dart:isolate-patch/isolate_patch.dart:303:32)
#8      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:12)

If running one more time:

> 2020-01-03T16:28:55.497372: INFO ssh-connectivity: succeeded
2020-01-03T16:28:55.497437: INFO Last known IP address: 192.168.1.226
2020-01-03T16:28:55.497479: INFO ios-device-b4873f14ffb248dfcb00c8cb7fdd4cdcff87f1f0: succeeded
2020-01-03T16:28:55.497521: INFO has-healthy-devices: succeeded
2020-01-03T16:28:55.499569: INFO Found 1 healthy devices
2020-01-03T16:28:55.499634: INFO cocoon-authentication: succeeded
2020-01-03T16:28:55.499669: INFO cocoon-connection: succeeded
2020-01-03T16:28:55.499706: INFO ios: failed
2020-01-03T16:28:55.499738: INFO ERROR: Invalid argument(s): Cannot find executable for /Users/flutter/.cocoon/flutter/bin/flutter.
2020-01-03T16:28:55.499776: INFO #0      _getExecutable (package:process/src/interface/local_process_manager.dart:127:5)
2020-01-03T16:28:55.499813: INFO #1      LocalProcessManager.start (package:process/src/interface/local_process_manager.dart:43:30)
2020-01-03T16:28:55.499852: INFO #2      startProcess (package:cocoon_agent/src/utils.dart:285:40)
2020-01-03T16:28:55.499887: INFO <asynchronous suspension>
2020-01-03T16:28:55.499922: INFO #3      exec (package:cocoon_agent/src/utils.dart:326:13)
2020-01-03T16:28:55.499956: INFO <asynchronous suspension>
2020-01-03T16:28:55.499991: INFO #4      flutter (package:cocoon_agent/src/utils.dart:369:10)
2020-01-03T16:28:55.500026: INFO #5      performHealthChecks.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:cocoon_agent/src/health.dart:54:19)
2020-01-03T16:28:55.500182: INFO <asynchronous suspension>
2020-01-03T16:28:55.500219: INFO #6      inDirectory (package:cocoon_agent/src/utils.dart:382:24)
2020-01-03T16:28:55.500254: INFO <asynchronous suspension>
2020-01-03T16:28:55.500288: INFO #7      performHealthChecks.<anonymous closure>.<anonymous closure> (package:cocoon_agent/src/health.dart:53:17)
2020-01-03T16:28:55.500323: INFO <asynchronous suspension>
2020-01-03T16:28:55.500358: INFO #8      _captureErrors (package:cocoon_agent/src/health.dart:90:47)
2020-01-03T16:28:55.500391: INFO <asynchronous suspension>
2020-01-03T16:28:55.500424: INFO #9      performHealthChecks.<anonymous closure> (package:cocoon_agent/src/health.dart:47:30)
2020-01-03T16:28:55.500457: INFO <asynchronous suspension>
2020-01-03T16:28:55.500490: INFO #10     _captureErrors (package:cocoon_agent/src/health.dart:90:47)
2020-01-03T16:28:55.500522: INFO <asynchronous suspension>
2020-01-03T16:28:55.500554: INFO #11     performHealthChecks (package:cocoon_agent/src/health.dart:20:51)
2020-01-03T16:28:55.500587: INFO <asynchronous suspension>
2020-01-03T16:28:55.500624: INFO #12     RunCommand.run (package:cocoon_agent/src/commands/run.dart:31:32)
2020-01-03T16:28:55.500661: INFO <asynchronous suspension>
2020-01-03T16:28:55.500692: INFO #13     main (file:///Users/flutter/cocoon/agent/bin/agent.dart:63:19)
2020-01-03T16:28:55.500729: INFO <asynchronous suspension>
2020-01-03T16:28:55.500759: INFO #14     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:303:32)
2020-01-03T16:28:55.500796: INFO #15     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:12)
2020-01-03T16:28:55.500830: INFO able-to-perform-health-check: succeeded

**Comment by keyonghan** [comment]
Seems to be a bug in the agent code. Will look into it.

**Comment by keyonghan** [comment]
Retried `~/Library/Developer/Xcode/DerivedData/`, and problem was solved.
So it should be not issue related to agent code. Closing it for now.
