### ISSUE TITLE
flutter command fails on fresh install - idevice_id not signed

### ISSUE THREAD

**Issue by london11** [flutter/flutter#48150]
Hello everyone, 

I  am having an issue with installing flutter, I download the SDK zip on flutter website, also placed the folder in $home/developer/flutter, after that I opened up vim editor ZSH

I put in a  (**flutter --version**)  and enter I get this error as below
```
dyld: Symbol not found: _OBJC_IVAR_$_NSFont._fFlags
  Referenced from: /Applications/Xcode.app/Contents/Frameworks/IDEFoundation.framework/Versions/A/../../../../SharedFrameworks/DVTKit.framework/Versions/A/DVTKit
  Expected in: /System/Library/Frameworks/AppKit.framework/Versions/C/AppKit
 in /Applications/Xcode.app/Contents/Frameworks/IDEFoundation.framework/Versions/A/../../../../SharedFrameworks/DVTKit.framework/Versions/A/DVTKit
git: error: unable to locate xcodebuild, please make sure the path to the Xcode folder is set correctly!
git: error: You can set the path to the Xcode folder using /usr/bin/xcode-select -switch
```
Then I get a pop up saying, idevice-id can not be opened because the developer cannot be verified
so i cancel the popup and close vim

This time i go on to security and privacy on settings, unlock the padlock  and open vim
flutter  --version 
this time on the security and privacy i am able to allow it 
so redo it again 
but get this popup again but saying 
MacOS cannot verify the developer of the idevice_id 
are you sure you want to open it 
i open it 

then get this error on vim

Oops; flutter has exited unexpectedly.
crash report 

## Logs--- crash report 

Flutter crash report; please file at https://github.com/flutter/flutter/issues.

## command

flutter --version

## exception

VersionCheckError: VersionCheckError: Command exited with code 71: git -c log.showSignature=false log -n 1 --pretty=format:%ad --date=iso
Standard error: dyld: Symbol not found: _OBJC_IVAR_$_NSFont._fFlags
  Referenced from: /Applications/Xcode.app/Contents/Frameworks/IDEFoundation.framework/Versions/A/../../../../SharedFrameworks/DVTKit.framework/Versions/A/DVTKit
  Expected in: /System/Library/Frameworks/AppKit.framework/Versions/C/AppKit
 in /Applications/Xcode.app/Contents/Frameworks/IDEFoundation.framework/Versions/A/../../../../SharedFrameworks/DVTKit.framework/Versions/A/DVTKit
git: error: unable to locate xcodebuild, please make sure the path to the Xcode folder is set correctly!
git: error: You can set the path to the Xcode folder using /usr/bin/xcode-select -switch

```
#0      _runSync (package:flutter_tools/src/version.dart:543:5)
#1      FlutterVersion._latestGitCommitDate (package:flutter_tools/src/version.dart:143:12)
#2      FlutterVersion.frameworkCommitDate (package:flutter_tools/src/version.dart:133:37)
#3      FlutterVersion.toString (package:flutter_tools/src/version.dart:110:99)
#4      FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:404:46)
<asynchronous suspension>
#5      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:146:29)
#6      _rootRun (dart:async/zone.dart:1126:13)
#7      _CustomZone.run (dart:async/zone.dart:1023:19)
#8      _runZoned (dart:async/zone.dart:1518:10)
#9      runZoned (dart:async/zone.dart:1465:12)
#10     AppContext.run (package:flutter_tools/src/base/context.dart:145:18)
#11     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:364:19)
#12     CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:112:25)
#13     new Future.sync (dart:async/future.dart:224:31)
#14     CommandRunner.run (package:args/command_runner.dart:112:14)
#15     FlutterCommandRunner.run (package:flutter_tools/src/runner/flutter_command_runner.dart:250:18)
#16     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:63:22)
#17     _rootRun (dart:async/zone.dart:1126:13)
#18     _CustomZone.run (dart:async/zone.dart:1023:19)
#19     _runZoned (dart:async/zone.dart:1518:10)
#20     runZoned (dart:async/zone.dart:1502:12)
#21     run.<anonymous closure> (package:flutter_tools/runner.dart:61:18)
<asynchronous suspension>
#22     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:146:29)
#23     _rootRun (dart:async/zone.dart:1126:13)
#24     _CustomZone.run (dart:async/zone.dart:1023:19)
#25     _runZoned (dart:async/zone.dart:1518:10)
#26     runZoned (dart:async/zone.dart:1465:12)
#27     AppContext.run (package:flutter_tools/src/base/context.dart:145:18)
#28     runInContext (package:flutter_tools/src/context_runner.dart:64:24)
#29     run (package:flutter_tools/runner.dart:50:10)
#30     main (package:flutter_tools/executable.dart:65:9)
#31     main (file:///Users/omerelobied/Developer/flutter/packages/flutter_tools/bin/flutter_tools.dart:8:3)
#32     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:305:32)
#33     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:174:12)
```

## flutter doctor

```
[33m[!][39m Flutter (Channel unknown, v0.0.0-unknown, on Mac OS X 10.15.2 19C57, locale
    en-GB)
    [32m•[39m Flutter version 0.0.0-unknown at /Users/omerelobied/Developer/flutter
    [31m✗[39m Command exited with code 71: git -c log.showSignature=false log -n 1
      --pretty=format:%ad --date=iso
      Standard error: dyld: Symbol not found: _OBJC_IVAR_$_NSFont._fFlags
        Referenced from:
        /Applications/Xcode.app/Contents/Frameworks/IDEFoundation.framework/Vers
        ions/A/../../../../SharedFrameworks/DVTKit.framework/Versions/A/DVTKit
        Expected in:
        /System/Library/Frameworks/AppKit.framework/Versions/C/AppKit
       in
       /Applications/Xcode.app/Contents/Frameworks/IDEFoundation.framework/Versi
       ons/A/../../../../SharedFrameworks/DVTKit.framework/Versions/A/DVTKit
      git: error: unable to locate xcodebuild, please make sure the path to the
      Xcode folder is set correctly!
      git: error: You can set the path to the Xcode folder using
      /usr/bin/xcode-select -switch


[31m[✗][39m Android toolchain - develop for Android devices
    [31m✗[39m Unable to locate Android SDK.
      Install Android Studio from:
      https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK
      components.
      (or visit https://flutter.dev/setup/#android-setup for detailed
      instructions).
      If the Android SDK has been installed to a custom location, set
      ANDROID_HOME to that location.
      You may also want to add it to your PATH environment variable.


[31m[✗][39m Xcode - develop for iOS and macOS
    [31m✗[39m Xcode installation is incomplete; a full installation is necessary for iOS
      development.
      Download at: https://developer.apple.com/xcode/download/
      Or install Xcode via the App Store.
      Once installed, run:
        sudo xcode-select --switch /Applications/Xcode.app/Contents/Developer
        sudo xcodebuild -runFirstLaunch
    [31m✗[39m CocoaPods not installed.
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin
        code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To install:
        sudo gem install cocoapods

[33m[!][39m Android Studio (not installed)
    [32m•[39m Android Studio not found; download from
      https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/setup/#android-setup for detailed
      instructions).

[33m[!][39m Connected device
    [33m![39m No devices available

[33m![39m Doctor found issues in 5 categories.
```

Does anyone know how to solve this issue, please  

Thanks

**Comment by dnfield** [comment]
It sounds like you don't have Xcode installed.  Can you install Xcode and try again?

**Comment by dnfield** [comment]
(or, maybe you have Xcode installed, but the installation is corrupted?)

**Comment by dnfield** [comment]
Sorry, looking again at this, it sounds like you somehow got a bundle that has an unsigned idevice_id.  @christopherfujino might know.

**Comment by london11** [comment]
Hi, thanks for getting back to me 
@dnfield 
The issue was with the Xcode when i upgrade to  MAC OS Catalina, i had an old version of the Xcode which was not compatible, after downloading the Xcode  and going back on vim i am not getting

Flutter 1.12.13+hotfix.5 • channel stable •
https://github.com/flutter/flutter.git
Framework • revision 27321ebbad (3 weeks ago) • 2019-12-10 18:15:01 -0800
Engine • revision 2994f7e1e6
Tools • Dart 2.7.0

  
  ║                 Welcome to Flutter! - https://flutter.dev                  ║
  ║                                                                            ║
  ║ The Flutter tool uses Google Analytics to anonymously report feature usage ║
  ║ statistics and basic crash reports. This data is used to help improve      ║
  ║ Flutter tools over time.  


issue now resolved thanks guys and thanks @dnfield
