### ISSUE TITLE
I have a new problem after I update the flutter from 1.5.4 to 1.12.13

### ISSUE THREAD

**Issue by weizhenzhao** [flutter/flutter#48178]
<details>
	<summary>logs</summary>

```bash

Launching lib\main.dart on Android SDK built for x86 in debug mode...
Running Gradle task 'assembleDebug'...
I/flutter ( 4773): MaterialColor(primary value: Color(0xff607d8b))
I/flutter ( 4773): MaterialColor(primary value: Color(0xff607d8b))
I/flutter ( 4773): Color(0xfff1f3f4)
I/flutter ( 4773): Color(0xffffffff)
I/flutter ( 4773): 'package:firebase_auth/src/firebase_auth.dart': Failed assertion: line 223 pos 12: 'email != null': is not true.
I/flutter ( 5882): MaterialColor(primary value: Color(0xff607d8b))
I/flutter ( 5882): MaterialColor(primary value: Color(0xff607d8b))
I/flutter ( 5882): Color(0xffa7b7bf)
I/flutter ( 5882): Color(0xffc9d2d7)
I/flutter ( 5882): Color(0xfff8f9fa)
I/flutter ( 5882): Color(0xfffbfcfc)
I/flutter ( 5882): Color(0xffffffff)
I/flutter ( 6437): MaterialColor(primary value: Color(0xff607d8b))
I/flutter ( 6437): MaterialColor(primary value: Color(0xff607d8b))
I/flutter ( 6437): Color(0xffc7d1d6)
I/flutter ( 6437): Color(0xffe9edef)
I/flutter ( 6437): Color(0xffffffff)
I/flutter ( 6437): ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
I/flutter ( 6437): The following assertion was thrown building Title(color: MaterialColor(primary value:
I/flutter ( 6437): Color(0xff2196f3))):
I/flutter ( 6437): 'package:flutter/src/widgets/widget_inspector.dart': Failed assertion: line 2183 pos 12:
I/flutter ( 6437): 'WidgetInspectorService.instance.selectionChangedCallback == null': is not true.
I/flutter ( 6437): 
I/flutter ( 6437): Either the assertion indicates an error in the framework itself, or we should provide substantially
I/flutter ( 6437): more information in this error message to help you determine and fix the underlying cause.
I/flutter ( 6437): In either case, please report this assertion by filing a bug on GitHub:
I/flutter ( 6437):   https://github.com/flutter/flutter/issues/new?template=BUG.md
I/flutter ( 6437): 
I/flutter ( 6437): When the exception was thrown, this was the stack:
I/flutter ( 6437): #2      _WidgetInspectorState.initState (package:flutter/src/widgets/widget_inspector.dart:2183:12)
I/flutter ( 6437): #3      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3846:58)
I/flutter ( 6437): #4      ComponentElement.mount (package:flutter/src/widgets/framework.dart:3717:5)
I/flutter ( 6437): #5      Element.inflateWidget (package:flutter/src/widgets/framework.dart:2961:14)
I/flutter ( 6437): #6      Element.updateChild (package:flutter/src/widgets/framework.dart:2764:12)
I/flutter ( 6437): #7      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3750:16)
I/flutter ( 6437): #8      Element.rebuild (package:flutter/src/widgets/framework.dart:3565:5)
I/flutter ( 6437): #9      StatelessElement.update (package:flutter/src/widgets/framework.dart:3796:5)
I/flutter ( 6437): #10     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:15)
I/flutter ( 6437): #11     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3750:16)
I/flutter ( 6437): #12     Element.rebuild (package:flutter/src/widgets/framework.dart:3565:5)
I/flutter ( 6437): #13     ProxyElement.update (package:flutter/src/widgets/framework.dart:4006:5)
I/flutter ( 6437): #14     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:15)
I/flutter ( 6437): #15     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3750:16)
I/flutter ( 6437): #16     Element.rebuild (package:flutter/src/widgets/framework.dart:3565:5)
I/flutter ( 6437): #17     ProxyElement.update (package:flutter/src/widgets/framework.dart:4006:5)
I/flutter ( 6437): #18     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:15)
I/flutter ( 6437): #19     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4883:14)
I/flutter ( 6437): #20     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:15)
I/flutter ( 6437): #21     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3750:16)
I/flutter ( 6437): #22     Element.rebuild (package:flutter/src/widgets/framework.dart:3565:5)
I/flutter ( 6437): #23     StatefulElement.update (package:flutter/src/widgets/framework.dart:3894:5)
I/flutter ( 6437): #24     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:15)
I/flutter ( 6437): #25     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3750:16)
I/flutter ( 6437): #26     Element.rebuild (package:flutter/src/widgets/framework.dart:3565:5)
I/flutter ( 6437): #27     ProxyElement.update (package:flutter/src/widgets/framework.dart:4006:5)
I/flutter ( 6437): #28     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:15)
I/flutter ( 6437): #29     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3750:16)
I/flutter ( 6437): #30     Element.rebuild (package:flutter/src/widgets/framework.dart:3565:5)
I/flutter ( 6437): #31     StatefulElement.update (package:flutter/src/widgets/framework.dart:3894:5)
I/flutter ( 6437): #32     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:15)
I/flutter ( 6437): #33     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3750:16)
I/flutter ( 6437): #34     Element.rebuild (package:flutter/src/widgets/framework.dart:3565:5)
I/flutter ( 6437): #35     ProxyElement.update (package:flutter/src/widgets/framework.dart:4006:5)
I/flutter ( 6437): #36     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:15)
I/flutter ( 6437): #37     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3750:16)
I/flutter ( 6437): #38     Element.rebuild (package:flutter/src/widgets/framework.dart:3565:5)
I/flutter ( 6437): #39     StatefulElement.update (package:flutter/src/widgets/framework.dart:3894:5)
I/flutter ( 6437): #40     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:15)
I/flutter ( 6437): #41     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3750:16)
I/flutter ( 6437): #42     Element.rebuild (package:flutter/src/widgets/framework.dart:3565:5)
I/flutter ( 6437): #43     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2278:33)
I/flutter ( 6437): #44     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding&WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:700:20)
I/flutter ( 6437): #45     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:286:5)
I/flutter ( 6437): #46     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1012:15)
I/flutter ( 6437): #47     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:952:9)
I/flutter ( 6437): #48     _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:864:5)
I/flutter ( 6437): #52     _invoke (dart:ui/hooks.dart:219:10)
I/flutter ( 6437): #53     _drawFrame (dart:ui/hooks.dart:178:3)
I/flutter ( 6437): (elided 5 frames from class _AssertionError and package dart:async)
I/flutter ( 6437): ════════════════════════════════════════════════════════════════════════════════════════════════════
I/flutter ( 6437): Color(0xff617e8c)
I/flutter ( 6437): Color(0xff627e8c)
I/flutter ( 6437): Color(0xff637f8d)
I/flutter ( 6437): Color(0xff65818e)
I/flutter ( 6437): Color(0xff66828f)
I/flutter ( 6437): Color(0xff668290)
I/flutter ( 6437): Color(0xff688390)
I/flutter ( 6437): Color(0xff698491)
I/flutter ( 6437): Color(0xff6a8592)
I/flutter ( 6437): Color(0xff6b8693)
I/flutter ( 6437): Color(0xff6c8794)
I/flutter ( 6437): Color(0xff6d8895)
I/flutter ( 6437): Color(0xff6e8995)
I/flutter ( 6437): Color(0xff708a96)
I/flutter ( 6437): Color(0xff718b97)
I/flutter ( 6437): Color(0xff728b98)
I/flutter ( 6437): Color(0xff738c99)
I/flutter ( 6437): Color(0xff748d9a)
I/flutter ( 6437): Color(0xff758e9a)
I/flutter ( 6437): Color(0xff768f9b)
I/flutter ( 6437): Color(0xff78909c)
I/flutter ( 6437): Color(0xff79919d)
I/flutter ( 6437): Color(0xff7a929e)
I/flutter ( 6437): Color(0xff7b939f)
I/flutter ( 6437): Color(0xff7c949f)
I/flutter ( 6437): Color(0xff7d95a0)
I/flutter ( 6437): Color(0xff7e96a1)
I/flutter ( 6437): Color(0xff8097a2)
I/flutter ( 6437): Color(0xff8198a3)
I/flutter ( 6437): Color(0xff8299a4)
I/flutter ( 6437): Color(0xff8399a4)
I/flutter ( 6437): Color(0xff849aa5)
I/flutter ( 6437): Color(0xff859ba6)
I/flutter ( 6437): Color(0xff869ca7)
I/flutter ( 6437): Color(0xff889da8)
I/flutter ( 6437): Color(0xff8a9fa9)
I/flutter ( 6437): Color(0xff8ba0aa)
I/flutter ( 6437): Color(0xff8da1ab)
I/flutter ( 6437): Color(0xff8ea2ac)
I/flutter ( 6437): Color(0xff8fa3ad)
I/flutter ( 6437): Color(0xff91a5ae)
I/flutter ( 6437): Color(0xff92a6af)
I/flutter ( 6437): Color(0xff92a6b0)
I/flutter ( 6437): Color(0xff94a7b0)
I/flutter ( 6437): Color(0xff94a8b1)
I/flutter ( 6437): Color(0xff95a8b1)
I/flutter ( 6437): Color(0xff96a9b2)
I/flutter ( 6437): Color(0xff97aab3)
I/flutter ( 6437): Color(0xff98abb4)
I/flutter ( 6437): Color(0xff99acb5)
I/flutter ( 6437): Color(0xff9aadb5)
I/flutter ( 6437): Color(0xff9badb6)
I/flutter ( 6437): Color(0xff9caeb7)
I/flutter ( 6437): Color(0xff9dafb8)
I/flutter ( 6437): Color(0xff9eb0b8)
I/flutter ( 6437): Color(0xffa0b1b9)
I/flutter ( 6437): Color(0xffa0b1ba)
I/flutter ( 6437): Color(0xffa1b2ba)
I/flutter ( 6437): Color(0xffa2b3bb)
I/flutter ( 6437): Color(0xffa4b4bc)
I/flutter ( 6437): Color(0xffa5b5bd)
I/flutter ( 6437): Color(0xffa5b6bd)
I/flutter ( 6437): Color(0xffa7b7bf)
I/flutter ( 6437): Color(0xffa8b8bf)
I/flutter ( 6437): Color(0xffa9b9c0)
I/flutter ( 6437): Color(0xffaabac1)
I/flutter ( 6437): Color(0xffacbbc2)
I/flutter ( 6437): Color(0xffadbcc3)
I/flutter ( 6437): Color(0xffaebdc4)
I/flutter ( 6437): Color(0xffafbdc4)
I/flutter ( 6437): Color(0xffb0bec5)
I/flutter ( 6437): Color(0xffb1bfc6)
I/flutter ( 6437): Color(0xffb2c0c7)
I/flutter ( 6437): Color(0xffb3c1c7)
I/flutter ( 6437): Color(0xffb4c1c8)
I/flutter ( 6437): Color(0xffb5c2c9)
I/flutter ( 6437): Color(0xffb6c3ca)
I/flutter ( 6437): Color(0xffb7c4ca)
I/flutter ( 6437): Color(0xffb8c5cb)
I/flutter ( 6437): Color(0xffb9c5cc)
I/flutter ( 6437): Color(0xffbac6cc)
I/flutter ( 6437): Color(0xffbac7cd)
I/flutter ( 6437): Color(0xffbcc8ce)
I/flutter ( 6437): Color(0xffbdc9cf)
I/flutter ( 6437): Color(0xffbdc9cf)
I/flutter ( 6437): Color(0xffbecacf)
I/flutter ( 6437): Color(0xffbfcbd0)
I/flutter ( 6437): Color(0xffc0cbd1)
I/flutter ( 6437): Color(0xffc0ccd1)
I/flutter ( 6437): Color(0xffc1ccd2)
I/flutter ( 6437): Color(0xffc2cdd2)
I/flutter ( 6437): Color(0xffc2cdd3)
I/flutter ( 6437): Color(0xffc4ced4)
I/flutter ( 6437): Color(0xffc5cfd4)
I/flutter ( 6437): Color(0xffc6d0d5)
I/flutter ( 6437): Color(0xffc8d2d6)
I/flutter ( 6437): Color(0xffc9d3d8)
I/flutter ( 6437): Color(0xffccd5d9)
I/flutter ( 6437): Color(0xffcdd6db)
I/flutter ( 6437): Color(0xffcfd8dc)
I/flutter ( 6437): Color(0xffd1d9dd)
I/flutter ( 6437): Color(0xffd2dade)
I/flutter ( 6437): Color(0xffd3dbdf)
I/flutter ( 6437): Color(0xffd4dce0)
I/flutter ( 6437): Color(0xffd6dde1)
I/flutter ( 6437): Color(0xffd8dfe2)
I/flutter ( 6437): Color(0xffd9e0e3)
I/flutter ( 6437): Color(0xffdae1e4)
I/flutter ( 6437): Color(0xffdce2e5)
I/flutter ( 6437): Color(0xffdde3e6)
I/flutter ( 6437): Color(0xffdee4e7)
I/flutter ( 6437): Color(0xffe0e6e8)
I/flutter ( 6437): Color(0xffe1e7e9)
I/flutter ( 6437): Color(0xffe2e8ea)
I/flutter ( 6437): Color(0xffe4e9eb)
I/flutter ( 6437): Color(0xffe5e9ec)
I/flutter ( 6437): Color(0xffe5eaec)
I/flutter ( 6437): Color(0xffe6ebed)
I/flutter ( 6437): Color(0xffe8ecee)
I/flutter ( 6437): Color(0xffe9edef)
I/flutter ( 6437): Color(0xffeaeeef)
I/flutter ( 6437): Color(0xffeceff1)
I/flutter ( 6437): Color(0xffedf0f2)
I/flutter ( 6437): Color(0xffeff2f3)
I/flutter ( 6437): Color(0xfff0f3f4)
I/flutter ( 6437): Color(0xfff2f4f5)
I/flutter ( 6437): Color(0xfff3f5f6)
I/flutter ( 6437): Color(0xfff4f6f7)
I/flutter ( 6437): Color(0xfff6f7f8)
I/flutter ( 6437): Color(0xfff8f9f9)
I/flutter ( 6437): Color(0xfff9fafa)
I/flutter ( 6437): Color(0xfffafbfb)
I/flutter ( 6437): Color(0xfffbfcfc)
I/flutter ( 6437): Color(0xfffefefe)
I/flutter ( 6437): Color(0xffffffff)
I/flutter ( 6437): Another exception was thrown: Id does not exist.

FAILURE: Build failed with an exception.

* Where:
Build file 'D:\GitHub\flash-chat-flutter\android\app\build.gradle' line: 25

* What went wrong:
A problem occurred evaluating project ':app'.
> ASCII

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 3s
Finished with error: Gradle task assembleDebug failed with exit code 1

```

</details>

**Comment by iapicca** [comment]
Hi @weizhenzhao 
could you please run 
`flutter channel stable`
`flutter upgrade --force`
`flutter clean`
`flutter pub cache repair`
If the issue persist please provide your updated 
`flutter doctor -v` and `flutter run --verbose`
together with a a minimal code sample to reproduce the problem
thank you

**Comment by weizhenzhao** [comment]
android sdk compile version wrong in build.gradle file .  and I solved the issue by changing the version right
