### ISSUE TITLE
FileSystemException: Cannot delete file, path = '/storage/emulated/0/DCIM/Camera/IMG_20200107_213857.jpg' (OS Error: Owner died, errno = 130)

### ISSUE THREAD

**Issue by Tumbler0809** [flutter/flutter#48298]
<details>
<summary>log</summary>

```
2020-01-07 21:39:18.844 1857-1887/com.ainirobot.aicampus.teacher E/flutter: [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: FileSystemException: Cannot delete file, path = '/storage/emulated/0/DCIM/Camera/IMG_20200107_213857.jpg' (OS Error: Owner died, errno = 130)
#0 _File._delete. (dart:io/file_impl.dart:293:9)
#1 _rootRunUnary (dart:async/zone.dart:1134:38)
#2 _CustomZone.runUnary (dart:async/zone.dart:1031:19)
#3 _FutureListener.handleValue (dart:async/future_impl.dart:139:18)
#4 Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:680:45)
#5 Future._propagateToListeners (dart:async/future_impl.dart:709:32)
#6 Future._completeWithValue (dart:async/future_impl.dart:524:5)
#7 Future._asyncComplete. (dart:async/future_impl.dart:554:7)
#8 _rootRun (dart:async/zone.dart:1126:13)
#9 _CustomZone.run (dart:async/zone.dart:1023:19)
#10 _CustomZone.runGuarded (dart:async/zone.dart:925:7)
#11 _CustomZone.bindCallbackGuarded. (dart:async/zone.dart:965:23)
#12 _microtaskLoop (dart:async/schedule_microtask.dart:43:21)
#13 _startMicrotaskLoop (dart:async/schedule_microtask.dart:52:5)
2020-01-07 21:39:18.845 1857-1887/com.ainirobot.aicampus.teacher E/flutter: [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: FileSystemException: Cannot delete file, path = '/storage/emulated/0/DCIM/Camera/IMG_20200107_213855.jpg' (OS Error: Owner died, errno = 130)
#0 _File._delete. (dart:io/file_impl.dart:293:9)
#1 _rootRunUnary (dart:async/zone.dart:1134:38)
#2 _CustomZone.runUnary (dart:async/zone.dart:1031:19)
#3 _FutureListener.handleValue (dart:async/future_impl.dart:139:18)
#4 Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:680:45)
#5 Future._propagateToListeners (dart:async/future_impl.dart:709:32)
#6 Future._completeWithValue (dart:async/future_impl.dart:524:5)
#7 Future._asyncComplete. (dart:async/future_impl.dart:554:7)
#8 _rootRun (dart:async/zone.dart:1126:13)
#9 _CustomZone.run (dart:async/zone.dart:1023:19)
#10 _CustomZone.runGuarded (dart:async/zone.dart:925:7)
#11 _CustomZone.bindCallbackGuarded. (dart:async/zone.dart:965:23)
#12 _microtaskLoop (dart:async/schedule_microtask.dart:43:21)
#13 _startMicrotaskLoop (dart:async/schedule_microtask.dart:52:5)
```

</details>

**Comment by Tumbler0809** [comment]
File(it).delete();

**Comment by Tumbler0809** [comment]
App has storage permissions and delete file permissions

**Comment by VladyslavBondarenko** [comment]
Hi @Tumbler0809 
despite 'WRITE_EXTERNAL_STORAGE' permission, android will not allow you to write (delete) files outside of the directory of your application.
Closing, as this isn't an issue with Flutter itself,
if you disagree please write in the comments and I will reopen it.
Thank you

**Comment by KabluBR** [comment]
I disagree on this, there are other applications on the play store like SLIDEBOX that move files from library to other folders without any issue.

**Comment by KabluBR** [comment]
Even If I try to move the file from default photo library to other folder, it moves but the original image will still appear in the gallery, but there with an error... it is like it is not on disk anymore but some internal cache is still there.

**Comment by VladyslavBondarenko** [comment]
Related to https://github.com/flutter/flutter/issues/40498

**Comment by darshankawar** [comment]
Hi @Tumbler0809 
Is this still an issue ?
If so, can you please provide `flutter doctor -v` and a minimal complete reproducible code sample that shows the issue ?
Thanks.

**Comment by markusaksli-nc** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.
