### ISSUE TITLE
[web]: Error on click on button control while signing in from google/facebook

### ISSUE THREAD

**Issue by Dinesh2703** [flutter/flutter#48392]
Getting below error on click on any control like any button or textformfield.

<details>
	<summary>error</summary>

```bash
Describe your issue and include the commerrors.dart:147 Uncaught Error: Assertion failed: org-dartlang-sdk:///flutter_web_sdk/lib/_engine/engine/pointer_converter.dart:366:18
!_locationHasChanged(device, physicalX, physicalY)
is not true
    at Object.throw_ [as throw] (errors.dart:196)
    at Object.assertFailed (errors.dart:26)
    at _engine.PointerDataConverter.new.convert (pointer_converter.dart:366)
    at _engine.PointerAdapter.new.[_convertEventToPointerData] (pointer_binding.dart:366)
    at pointer_binding.dart:306
    at HTMLElement.<anonymous> (pointer_binding.dart:183)and you're running, flutter_web 

errors.dart:147 Uncaught (in promise) Error: Assertion failed: org-dartlang-app:///packages/google_sign_in_web/google_sign_in_web.dart:64:9
appClientId != null
"ClientID not set. Either set it on a <meta name=\"google-signin-client_id\" content=\"CLIENT_ID\" /> tag, or pass clientId when calling init()"
    at Object.throw_ [as throw] (errors.dart:196)
    at Object.assertFailed (errors.dart:26)
    at google_sign_in_web.GoogleSignInPlugin.new.init (google_sign_in_web.dart:64)
    at init.next (<anonymous>)
    at runBody (async_patch.dart:86)
    at Object._async [as async] (async_patch.dart:125)
    at google_sign_in_web.GoogleSignInPlugin.new.init (google_sign_in_web.dart:57)
    at google_sign_in.GoogleSignIn.new.[_ensureInitialized] (google_sign_in.dart:243)
    at google_sign_in.GoogleSignIn.new._callMethod (google_sign_in.dart:225)
    at _callMethod.next (<anonymous>)
    at runBody (async_patch.dart:86)
    at Object._async [as async] (async_patch.dart:125)
    at google_sign_in.GoogleSignIn.new.[_callMethod] (google_sign_in.dart:224)
    at google_sign_in.GoogleSignIn.new._addMethodCall (google_sign_in.dart:282)
    at _addMethodCall.next (<anonymous>)
    at runBody (async_patch.dart:86)
    at Object._async [as async] (async_patch.dart:125)
    at google_sign_in.GoogleSignIn.new.[_addMethodCall] (google_sign_in.dart:276)
    at google_sign_in.GoogleSignIn.new.signIn (google_sign_in.dart:352)
    at login_screen._LoginPageState.new.signInWithGoogle (login_screen.dart:190)
    at signInWithGoogle.next (<anonymous>)
    at runBody (async_patch.dart:86)
    at Object._async [as async] (async_patch.dart:125)
    at login_screen._LoginPageState.new.signInWithGoogle (login_screen.dart:189)
    at _InkResponseState.new.[_handleTap] (ink_well.dart:706)
    at ink_well.dart:789
    at tap.TapGestureRecognizer.new.invokeCallback (recognizer.dart:182)
    at tap.TapGestureRecognizer.new.handleTapUp (tap.dart:486)
    at tap.TapGestureRecognizer.new.[_checkUp] (tap.dart:264)
    at tap.TapGestureRecognizer.new.handlePrimaryPointer (tap.dart:199)
    at tap.TapGestureRecognizer.new.handleEvent (recognizer.dart:467)
    at pointer_router.PointerRouter.new.[_dispatch] (pointer_router.dart:76)
    at pointer_router.dart:117
    at LinkedMap.new.forEach (linked_hash_map.dart:23)
    at pointer_router.PointerRouter.new.[_dispatchEventToRoutes] (pointer_router.dart:115)
    at pointer_router.PointerRouter.new.route (pointer_router.dart:101)
    at binding$5.WidgetsFlutterBinding.new.handleEvent (binding.dart:218)
    at binding$5.WidgetsFlutterBinding.new.dispatchEvent (binding.dart:198)
    at binding$5.WidgetsFlutterBinding.new.[_handlePointerEvent] (binding.dart:156)
    at binding$5.WidgetsFlutterBinding.new.[_flushPointerEventQueue] (binding.dart:102)
    at binding$5.WidgetsFlutterBinding.new.[_handlePointerDataPacket] (binding.dart:86)
    at _engine.PointerBinding.new.[_onPointerData] (pointer_binding.dart:83)
    at pointer_binding.dart:334
    at HTMLElement.<anonymous> (pointer_binding.dart:183)

version, browser version-
Version 79.0.3945.88 (Official Build) (64-bit)

```

</details>

```console
[√] Flutter (Channel beta, v1.12.13+hotfix.6, on Microsoft Windows [Version 10.0.18362.535], locale en-IN)
 
[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[√] Chrome - develop for the web
[√] Android Studio (version 3.5)
[√] VS Code (version 1.41.1)
[√] Connected device (2 available)

• No issues found!
```

<details>
	<summary>flutter run --verbose</summary>

```bash
[  +22 ms] executing: [C:\Repos\flutter\] git -c log.showSignature=false log -n 1 --pretty=format:%H
[  +59 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[        ] 18cd7a3601bcffb36fdf2f679f763b5e827c2e8e
[        ] executing: [C:\Repos\flutter\] git describe --match v*.*.* --first-parent --long --tags
[  +53 ms] Exit code 0 from: git describe --match v*.*.* --first-parent --long --tags
[        ] v1.12.13+hotfix.6-0-g18cd7a360
[   +7 ms] executing: [C:\Repos\flutter\] git rev-parse --abbrev-ref --symbolic @{u}
[  +44 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[   +1 ms] origin/beta
[        ] executing: [C:\Repos\flutter\] git ls-remote --get-url origin
[  +41 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[  +91 ms] executing: [C:\Repos\flutter\] git rev-parse --abbrev-ref HEAD
[  +39 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] beta
[ +108 ms] executing: C:\Users\Dinesh\AppData\Local\Android\sdk\platform-tools\adb.exe devices -l
[  +24 ms] Exit code 0 from: C:\Users\Dinesh\AppData\Local\Android\sdk\platform-tools\adb.exe devices -l
[   +1 ms] List of devices attached
[  +30 ms] More than one device connected; please specify a device with the '-d <deviceId>' flag, or use '-d all' to act on all devices.
[  +50 ms] Chrome     • chrome     • web-javascript • Google Chrome 79.0.3945.117
[   +3 ms] Web Server • web-server • web-javascript • Flutter Tools
[  +17 ms] "flutter run" took 272ms.

#0      throwToolExit (package:flutter_tools/src/base/common.dart:28:3)
#1      RunCommand.validateCommand (package:flutter_tools/src/commands/run.dart:289:7)
<asynchronous suspension>
#2      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:590:11)
#3      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:515:33)
<asynchronous suspension>
#4      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:146:29)
#5      _rootRun (dart:async/zone.dart:1126:13)
#6      _CustomZone.run (dart:async/zone.dart:1023:19)
#7      _runZoned (dart:async/zone.dart:1518:10)
#8      runZoned (dart:async/zone.dart:1465:12)
#9      AppContext.run (package:flutter_tools/src/base/context.dart:145:18)
#10     FlutterCommand.run (package:flutter_tools/src/runner/flutter_command.dart:505:20)
#11     CommandRunner.runCommand (package:args/command_runner.dart:197:27)
#12     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:413:21)
<asynchronous suspension>
#13     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:146:29)
#14     _rootRun (dart:async/zone.dart:1126:13)
#15     _CustomZone.run (dart:async/zone.dart:1023:19)
#16     _runZoned (dart:async/zone.dart:1518:10)
#17     runZoned (dart:async/zone.dart:1465:12)
#18     AppContext.run (package:flutter_tools/src/base/context.dart:145:18)
#19     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:364:19)
#20     CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:112:25)
#21     new Future.sync (dart:async/future.dart:224:31)
#22     CommandRunner.run (package:args/command_runner.dart:112:14)
#23     FlutterCommandRunner.run (package:flutter_tools/src/runner/flutter_command_runner.dart:250:18)
#24     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:63:22)
#25     _rootRun (dart:async/zone.dart:1126:13)
#26     _CustomZone.run (dart:async/zone.dart:1023:19)
#27     _runZoned (dart:async/zone.dart:1518:10)
#28     runZoned (dart:async/zone.dart:1502:12)
#29     run.<anonymous closure> (package:flutter_tools/runner.dart:61:18)
<asynchronous suspension>
#30     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:146:29)
#31     _rootRun (dart:async/zone.dart:1126:13)
#32     _CustomZone.run (dart:async/zone.dart:1023:19)
#33     _runZoned (dart:async/zone.dart:1518:10)
#34     runZoned (dart:async/zone.dart:1465:12)
#35     AppContext.run (package:flutter_tools/src/base/context.dart:145:18)
#36     runInContext (package:flutter_tools/src/context_runner.dart:64:24)
#37     run (package:flutter_tools/runner.dart:50:10)
#38     main (package:flutter_tools/executable.dart:65:9)
#39     main (file:///C:/Repos/flutter/packages/flutter_tools/bin/flutter_tools.dart:8:3)
#40     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:305:32)
#41     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:174:12)

```

</details>

**Comment by iapicca** [comment]
Hi @Dinesh2703 
can you please provide your `flutter doctor -v` 
and your `flutter run --verbose`?
Also, to better address the issue, would be helpful
if you could post a reproducible minimal code sample
or the steps to reproduce the problem.
Thank you

**Comment by Dinesh2703** [comment]
Hi @iapicca I have included one more error i am getting and also included flutter doctor and flutter verbose result.

**Comment by iapicca** [comment]
<details>
	<summary>flutter run -d chrome --verbose</summary>

```bash

[  +25 ms] executing: [C:\src\flutter\] git -c log.showSignature=false log -n 1 --pretty=format:%H
[  +71 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[        ] 18cd7a3601bcffb36fdf2f679f763b5e827c2e8e
[        ] executing: [C:\src\flutter\] git describe --match v*.*.* --first-parent --long --tags
[  +61 ms] Exit code 0 from: git describe --match v*.*.* --first-parent --long --tags
[        ] v1.12.13+hotfix.6-0-g18cd7a360
[  +13 ms] executing: [C:\src\flutter\] git rev-parse --abbrev-ref --symbolic @{u}
[  +40 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/beta
[        ] executing: [C:\src\flutter\] git ls-remote --get-url origin
[  +35 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[  +88 ms] executing: [C:\src\flutter\] git rev-parse --abbrev-ref HEAD
[  +40 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[   +1 ms] beta
[ +108 ms] executing: C:\Users\iapic\AppData\Local\Android\sdk\platform-tools\adb.exe devices -l
[  +29 ms] Exit code 0 from: C:\Users\iapic\AppData\Local\Android\sdk\platform-tools\adb.exe devices -l
[        ] List of devices attached
[  +18 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[   +4 ms] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[   +6 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +54 ms] Found plugin google_sign_in at
C:\Users\iapic\AppData\Roaming\Pub\Cache\hosted\pub.dartlang.org\google_sign_in-4.1.1\
[  +15 ms] Found plugin google_sign_in_web at
C:\Users\iapic\AppData\Roaming\Pub\Cache\hosted\pub.dartlang.org\google_sign_in_web-0.8.2+1\
[  +66 ms] Found plugin google_sign_in at
C:\Users\iapic\AppData\Roaming\Pub\Cache\hosted\pub.dartlang.org\google_sign_in-4.1.1\
[   +6 ms] Found plugin google_sign_in_web at
C:\Users\iapic\AppData\Roaming\Pub\Cache\hosted\pub.dartlang.org\google_sign_in_web-0.8.2+1\
[  +69 ms] Generating
C:\Users\iapic\Documents\Code\Nevercode\nineth_january\android\app\src\main\java\io\flutter\plugins\GeneratedPluginRegis
trant.java
[ +155 ms] Launching lib\main.dart on Chrome in debug mode...
[   +2 ms] Building application for the web...
[ +135 ms] Found plugin google_sign_in at
C:\Users\iapic\AppData\Roaming\Pub\Cache\hosted\pub.dartlang.org\google_sign_in-4.1.1\
[   +4 ms] Found plugin google_sign_in_web at
C:\Users\iapic\AppData\Roaming\Pub\Cache\hosted\pub.dartlang.org\google_sign_in_web-0.8.2+1\
[+9375 ms] Starting daemon...
[ +203 ms] Initializing inputs
[  +18 ms] Reading cached asset graph...
[ +231 ms] Reading cached asset graph completed, took 226ms

[ +388 ms] Checking for updates since last build...
[ +663 ms] Checking for updates since last build completed, took 663ms

[  +12 ms] Initializing inputs
[   +3 ms] Reading cached asset graph...
[   +1 ms] Reading cached asset graph completed, took 226ms
[   +1 ms] Checking for updates since last build...
[        ] Checking for updates since last build completed, took 663ms
[ +191 ms] Serving DevTools at http://127.0.0.1:51495

[ +938 ms] About to build [web]...
[   +7 ms] Running build...
[   +2 ms] Running build completed, took 83ms

[   +1 ms] Caching finalized dependency graph...
[        ] Caching finalized dependency graph completed, took 113ms

[   +1 ms] Succeeded after 204ms with 0 outputs (0 actions)

[  +11 ms] Building application for the web... (completed in 12.2s)
[   +1 ms] Attempting to connect to browser instance..
[+10025 ms] Debug service listening on ws://127.0.0.1:51526/gFjFa9sMF-M=

[ +535 ms]       Failed to load asset at path: packages/build_web_compilers/src/dev_compiler/dart_sdk.js.

                          Status code: 404

                          Headers:
                          {
                      "date": "Thu, 09 Jan 2020 06:43:26 GMT",
                      "content-length": "9",
                      "x-frame-options": "SAMEORIGIN",
                      "content-type": "text/plain; charset=utf-8",
                      "x-xss-protection": "1; mode=block",
                      "x-content-type-options": "nosniff",
                      "server": "dart:io with Shelf",
                      "via": "1.1 shelf_proxy"
                    }

                          Content:
                          Not Found}

[  +66 ms] Attempting to connect to browser instance.. (completed in 10.6s)
[   +4 ms] Warning: Flutter's support for web development is not stable yet and hasn't
[   +1 ms] been thoroughly tested in production environments.
[   +2 ms] For more information see https://flutter.dev/web
[   +2 ms] 🔥  To hot restart changes while running, press "r". To hot restart (and refresh the browser), press "R".
[   +5 ms] For a more detailed help message, press "h". To quit, press "q".
[  +17 ms] Debug service listening on ws://127.0.0.1:51526/gFjFa9sMF-M=
[+4675 ms] Assertion failed: org-dartlang-app:///packages/google_sign_in_web/google_sign_in_web.dart:64:9
                    appClientId != null
                    "ClientID not set. Either set it on a <meta name=\"google-signin-client_id\" content=\"CLIENT_ID\"
/> tag, or pass
                    clientId when calling init()"
[+7210 ms] Assertion failed: org-dartlang-app:///packages/google_sign_in_web/google_sign_in_web.dart:64:9
                    appClientId != null
                    "ClientID not set. Either set it on a <meta name=\"google-signin-client_id\" content=\"CLIENT_ID\"
/> tag, or pass
                    clientId when calling init()"
[+1013 ms] Assertion failed: org-dartlang-app:///packages/google_sign_in_web/google_sign_in_web.dart:64:9
                    appClientId != null
                    "ClientID not set. Either set it on a <meta name=\"google-signin-client_id\" content=\"CLIENT_ID\"
/> tag, or pass
                    clientId when calling init()"
[+22519 ms] Stopped debug service on ws://127.0.0.1:51526

[  +21 ms] Application finished.
Terminate batch job (Y/N)? y

```

</details>

<details>
	<summary>code sample</summary>
```dart
/// https://github.com/flutter/plugins/blob/master/packages/google_sign_in/google_sign_in/example/lib/main.dart

// name: nineth_january
// description: A new Flutter project.
// version: 1.0.0+1

// environment:
//   sdk: ">=2.7.0 <3.0.0"

// dependencies:
//   http: ^0.12.0+4
//   google_sign_in: ^4.1.1
//   flutter:
//     sdk: flutter
// flutter:
//   uses-material-design: true

import 'dart:async';
import 'dart:convert' show json;

import "package:http/http.dart" as http;
import 'package:flutter/material.dart';
import 'package:google_sign_in/google_sign_in.dart';

GoogleSignIn _googleSignIn = GoogleSignIn(
  scopes: <String>[
    'email',
    'https://www.googleapis.com/auth/contacts.readonly',
  ],
);

void main() {
  runApp(
    MaterialApp(
      title: 'Google Sign In',
      home: SignInDemo(),
    ),
  );
}

class SignInDemo extends StatefulWidget {
  @override
  State createState() => SignInDemoState();
}

class SignInDemoState extends State<SignInDemo> {
  GoogleSignInAccount _currentUser;
  String _contactText;

  @override
  void initState() {
    super.initState();
    _googleSignIn.onCurrentUserChanged.listen((GoogleSignInAccount account) {
      setState(() {
        _currentUser = account;
      });
      if (_currentUser != null) {
        _handleGetContact();
      }
    });
    _googleSignIn.signInSilently();
  }

  Future<void> _handleGetContact() async {
    setState(() {
      _contactText = "Loading contact info...";
    });
    final http.Response response = await http.get(
      'https://people.googleapis.com/v1/people/me/connections'
      '?requestMask.includeField=person.names',
      headers: await _currentUser.authHeaders,
    );
    if (response.statusCode != 200) {
      setState(() {
        _contactText = "People API gave a ${response.statusCode} "
            "response. Check logs for details.";
      });
      print('People API ${response.statusCode} response: ${response.body}');
      return;
    }
    final Map<String, dynamic> data = json.decode(response.body);
    final String namedContact = _pickFirstNamedContact(data);
    setState(() {
      if (namedContact != null) {
        _contactText = "I see you know $namedContact!";
      } else {
        _contactText = "No contacts to display.";
      }
    });
  }

  String _pickFirstNamedContact(Map<String, dynamic> data) {
    final List<dynamic> connections = data['connections'];
    final Map<String, dynamic> contact = connections?.firstWhere(
      (dynamic contact) => contact['names'] != null,
      orElse: () => null,
    );
    if (contact != null) {
      final Map<String, dynamic> name = contact['names'].firstWhere(
        (dynamic name) => name['displayName'] != null,
        orElse: () => null,
      );
      if (name != null) {
        return name['displayName'];
      }
    }
    return null;
  }

  Future<void> _handleSignIn() async {
    try {
      await _googleSignIn.signIn();
    } catch (error) {
      print(error);
    }
  }

  Future<void> _handleSignOut() => _googleSignIn.disconnect();

  Widget _buildBody() {
    if (_currentUser != null) {
      return Column(
        mainAxisAlignment: MainAxisAlignment.spaceAround,
        children: <Widget>[
          ListTile(
            leading: GoogleUserCircleAvatar(
              identity: _currentUser,
            ),
            title: Text(_currentUser.displayName ?? ''),
            subtitle: Text(_currentUser.email ?? ''),
          ),
          const Text("Signed in successfully."),
          Text(_contactText ?? ''),
          RaisedButton(
            child: const Text('SIGN OUT'),
            onPressed: _handleSignOut,
          ),
          RaisedButton(
            child: const Text('REFRESH'),
            onPressed: _handleGetContact,
          ),
        ],
      );
    } else {
      return Column(
        mainAxisAlignment: MainAxisAlignment.spaceAround,
        children: <Widget>[
          const Text("You are not currently signed in."),
          RaisedButton(
            child: const Text('SIGN IN'),
            onPressed: _handleSignIn,
          ),
        ],
      );
    }
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
        appBar: AppBar(
          title: const Text('Google Sign In'),
        ),
        body: ConstrainedBox(
          constraints: const BoxConstraints.expand(),
          child: _buildBody(),
        ));
  }
}
```
</details>

<details>
	<summary>flutter doctor -v</summary>

```console
[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at C:\Users\iapic\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 28.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 3.5)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 41.1.2
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)

[√] VS Code, 64-bit edition (version 1.41.1)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Flutter extension version 3.7.1

[√] Connected device (2 available)
    • Chrome     • chrome     • web-javascript • Google Chrome 79.0.3945.117
    • Web Server • web-server • web-javascript • Flutter Tools

• No issues found!
```

</details>

**Comment by ditman** [comment]
Hey @Dinesh2703, I see an error message on your logs about the `google_sign_in` plugin not being correctly configured for web:

`ClientID not set. Either set it on a <meta name="google-signin-client_id" content="CLIENT_ID" /> tag, or pass clientId when calling init()`

Can you try to address that first, and see if that solves the issue?

There's setup documentation in the [README of the google_sign_in_web package](https://github.com/flutter/plugins/blob/master/packages/google_sign_in/google_sign_in_web/README.md#web-integration).

**Comment by Dinesh2703** [comment]
thanks @ditman its working now.
