### ISSUE TITLE
Exception on app startup running a macos app

### ISSUE THREAD

**Issue by DaveShuckerow** [flutter/flutter#48442]
```
flutter: ══╡ EXCEPTION CAUGHT BY SERVICES LIBRARY ╞══════════════════════════════════════════════════════════
flutter: The following assertion was thrown during a platform message callback:
flutter: 'package:flutter/src/widgets/shortcuts.dart': Failed assertion: line 76 pos 16: 'keys.isNotEmpty':
flutter: is not true.
flutter: 
flutter: Either the assertion indicates an error in the framework itself, or we should provide substantially
flutter: more information in this error message to help you determine and fix the underlying cause.
flutter: In either case, please report this assertion by filing a bug on GitHub:
flutter:   https://github.com/flutter/flutter/issues/new?template=BUG.md
flutter: 
flutter: When the exception was thrown, this was the stack:
flutter: #2      new KeySet.fromSet (package:flutter/src/widgets/shortcuts.dart:76:16)
flutter: #3      new LogicalKeySet.fromSet (package:flutter/src/widgets/shortcuts.dart:138:63)
flutter: #4      ShortcutManager.handleKeypress (package:flutter/src/widgets/shortcuts.dart:192:63)
flutter: #5      _ShortcutsState._handleOnKey (package:flutter/src/widgets/shortcuts.dart:344:20)
flutter: #6      FocusManager._handleRawKeyEvent (package:flutter/src/widgets/focus_manager.dart:1326:38)
flutter: #7      RawKeyboard._handleKeyEvent (package:flutter/src/services/raw_keyboard.dart:528:17)
flutter: #8      BasicMessageChannel.setMessageHandler.<anonymous closure> (package:flutter/src/services/platform_channel.dart:74:49)
flutter: #9      _DefaultBinaryMessenger.handlePlatformMessage (package:flutter/src/services/binding.dart:200:33)
flutter: #10     _invoke3.<anonymous closure> (dart:ui/hooks.dart:303:15)
flutter: #14     _invoke3 (dart:ui/hooks.dart:302:10)
flutter: #15     _dispatchPlatformMessage (dart:ui/hooks.dart:162:5)
flutter: (elided 5 frames from class _AssertionError and package dart:async)
flutter: ════════════════════════════════════════════════════════════════════════════════════════════════════
```

Doctor:
```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel unknown, v1.13.6-pre.30, on Mac OS X 10.14.6 18G1012, locale en-US)
[✓] Xcode - develop for iOS and macOS (Xcode 11.3)
[✓] Chrome - develop for the web
[✓] Android Studio
[✓] Android Studio
[✓] IntelliJ IDEA Community Edition (version 2019.1.3)
[✓] Connected device (4 available)

```

**Comment by stuartmorgan** [comment]
This came up in https://github.com/google/flutter-desktop-embedding/issues/604 as well, but nobody who was seeing it followed up with a report here as far as I can tell.

Is there public code that can reproduce this (or something internal you can share offline) so that we can isolate the trigger?

**Comment by gspencergoog** [comment]
This is happening because we're getting a key down event, but when the code asks for the set of keys that are down, the set is empty, which shouldn't be possible. My suspicion is that the platform is not setting the modifier bits properly when a modifier is pressed at app startup, or some kind of bogus key event is being sent when the app starts (which doesn't have the modifier bits properly set).

**Comment by DaveShuckerow** [comment]
> This came up in [google/flutter-desktop-embedding#604](https://github.com/google/flutter-desktop-embedding/issues/604) as well, but nobody who was seeing it followed up with a report here as far as I can tell.
> 
> Is there public code that can reproduce this (or something internal you can share offline) so that we can isolate the trigger?

I'm seeing this with the Flutter build of github.com/flutter/devtools.

I'm not able to reliably see it, and the error seems to disappear on hot reloads.

I haven't seen the error since upgrading from `v1.13.6-pre.30` to `v1.13.8-pre.53`.

**Comment by yupi** [comment]
I can confirm the error still pops up from time to time.
Flutter (Channel dev, v1.15.3, on Mac OS X 10.15.3 19D76, locale en-GB)

**Comment by modulovalue** [comment]
I'm also experiencing this issue.

One way to reproduce it is:
- run any macOS Flutter desktop app
- focus on a different macOS application e.g. Safari
- close the other application with cmd+q with the mouse pointer inside of the Safari window and the Flutter application (with the flutter application behind the Safari window).
- now macOS should move focus to the flutter application and this exception will be thrown.

**Comment by limbouser** [comment]
Flutter Engine : Stable

I am running flutter using an embedder API, a more advanced version of flutter_wayland on ARM and has an engine compiled for ARM. I run the app by running
flutter_wayland flutter_assets
and the following exception is available when Down or Left buttons are used

```
flutter: ══╡ EXCEPTION CAUGHT BY SERVICES LIBRARY ╞══════════════════════════════════════════════════════════
flutter: The following assertion was thrown during a platform message callback:
flutter: 'package:flutter/src/widgets/shortcuts.dart': Failed assertion: line 76 pos 16: 'keys.isNotEmpty':
flutter: is not true.
flutter: 
flutter: Either the assertion indicates an error in the framework itself, or we should provide substantially
flutter: more information in this error message to help you determine and fix the underlying cause.
flutter: In either case, please report this assertion by filing a bug on GitHub:
flutter:   https://github.com/flutter/flutter/issues/new?template=BUG.md
flutter: 
flutter: When the exception was thrown, this was the stack:
flutter: #2      new KeySet.fromSet (package:flutter/src/widgets/shortcuts.dart:76:16)
flutter: #3      new _LogicalKeySet&KeySet&Diagnosticable.fromSet (package:flutter/src/widgets/shortcuts.dart)
flutter: #4      new LogicalKeySet.fromSet (package:flutter/src/widgets/shortcuts.dart:178:63)
flutter: #5      ShortcutManager.handleKeypress (package:flutter/src/widgets/shortcuts.dart:297:63)
flutter: #6      _ShortcutsState._handleOnKey (package:flutter/src/widgets/shortcuts.dart:459:20)
flutter: #7      FocusManager._handleRawKeyEvent (package:flutter/src/widgets/focus_manager.dart:1536:43)
flutter: #8      RawKeyboard._handleKeyEvent (package:flutter/src/services/raw_keyboard.dart:531:17)
flutter: #9      BasicMessageChannel.setMessageHandler.<anonymous closure> (package:flutter/src/services/platform_channel.dart:74:49)
flutter: #10     _DefaultBinaryMessenger.handlePlatformMessage (package:flutter/src/services/binding.dart:199:33)
flutter: #11     _invoke3.<anonymous closure> (dart:ui/hooks.dart:290:15)
flutter: #15     _invoke3 (dart:ui/hooks.dart:289:10)
flutter: #16     _dispatchPlatformMessage (dart:ui/hooks.dart:164:5)
flutter: (elided 5 frames from class _AssertionError and dart:async)
flutter: ════════════════════════════════════════════════════════════════════════════════════════════════════
```

Can this be related to #48442 ? How do I solve this?

**Comment by stuartmorgan** [comment]
@limbouser Key event code is embedding-specific. If you have this exception with another embedding, you need to file a bug against that embedding.

**Comment by limbouser** [comment]
@stuartmorgan Right and Up are working fine and I had an assets directory which I compiled using flutter 1.12.3 stable version, the assets of flutter gallery from v1.12.13 and there all the keyss are working fine, I'm having issues using assets compiled from latest stable release

**Comment by eseidel** [comment]
I think I'm reproducing this by running Flutter Desktop full-screen and then using capslock (remapped to ctrl) plus left-arrow/right-arrow to switch over to a different fullscreen view (where my editor is).   I see this consistently and happy to try and track down more if needed?

**Comment by stuartmorgan** [comment]
Under the current implementation if you switch app focus away using the keyboard, you're definitely going to have a bad time. It's a known issue with the way keys are currently managed, and there's a project underway to restructure it.

**Comment by ydotmalik** [comment]
I observe this issue on Flutter mobile. To reproduce:
* run any flutter mobile app through Android Studio. Set the device to the Bluestacks emulator
* with the Bluestacks window focused, switch away from the workspace containing Bluestacks to another workspace using Ctrl+Win+Left/Right

This doesn't cause any problems but it clutters my run window and prevents me from clearly seeing my own prints. This didn't happen in a prior version of flutter.

As a workaround, I commented out the assertion, package:flutter/src/widgets/shortcuts.dart:77.

**Comment by alexisbg** [comment]
If I debug a web app in Chrome from VSCode and I hold down Alt Gr key, the following message is printed to the Debug Console:
```
════════ Exception caught by services library ══════════════════════════════════
Assertion failed: 
..\…\widgets\shortcuts.dart:77
keys.isNotEmpty
is not true

════════════════════════════════════════════════════════════════════════════════
```

**Comment by gspencergoog** [comment]
I haven't investigated this, but I suspect that we don't have a proper mapping for `AltGr`. Chrome doesn't have a mapping for this either, judging by the [comment in their header](https://chromium.googlesource.com/codesearch/chromium/src/+/refs/heads/master/ui/events/keycodes/dom/dom_code_data.inc#121).

**Comment by gspencergoog** [comment]
@alexisbg, could you file a separate issue for that?  I don't think it's related to this problem on macos.

**Comment by cbracken** [comment]
Assigning to @dkwingsmt since we belive this will be fixed by https://github.com/flutter/flutter/issues/44918

**Comment by cbracken** [comment]
@dkwingsmt is this still an issue?
