### ISSUE TITLE
Exception caught by rendering library

### ISSUE THREAD

**Issue by ysoofiyani** [flutter/flutter#48448]
The following assertion was thrown during paint():

```
'dart:ui/text.dart': Failed assertion: line 1372: '<optimized out>': is not true.


Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=BUG.md

The relevant error-causing widget was: 
  TextField-[<'email_address'>] file:///Users/yassersoofiyani/Desktop/RenoRun/RenoRunCustomerApp/lib/widgets/fragments/text_boxes.dart:361:19
When the exception was thrown, this was the stack: 
#2      new TextPosition (dart:ui/text.dart:1372:15)
#3      RenderEditable._updateSelectionExtentsVisibility (package:flutter/src/rendering/editable.dart:367:7)
#4      RenderEditable._paintContents (package:flutter/src/rendering/editable.dart:1956:7)
#5      RenderEditable.paint (package:flutter/src/rendering/editable.dart:2012:7)
#6      RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2219:7)
...
The following RenderObject was being processed when the exception was fired: RenderEditable#245a2 relayoutBoundary=up22
...  parentData: <none> (can use size)
...  constraints: BoxConstraints(w=314.7, 0.0<=h<=Infinity)
...  size: Size(314.7, 21.0)
...  cursorColor: Color(0x00000000)
...  showCursor: ValueNotifier<bool>#27255(true)
...  maxLines: 1
...  minLines: null
...  selectionColor: Color(0xff90caf9)
...  textScaleFactor: 1.0
...  locale: en_US
...  selection: TextSelection(baseOffset: 11, extentOffset: 11, affinity: null, isDirectional: false)
...  offset: ScrollPositionWithSingleContext#a4875(offset: 0.0, range: 0.0..0.0, viewport: 314.7, ScrollableState, ClampingScrollPhysics, IdleScrollActivity#70a4d, ScrollDirection.idle)
  text: TextSpan
    debugLabel: ((englishLike subhead 2014).merge(blackMountainView subhead)).merge(unknown)
    inherit: false
    color: Color(0xff000000)
    family: Roboto
    size: 18.0
    weight: 400
    style: normal
    baseline: alphabetic
    decoration: TextDecoration.none
    "hgj@kskh.jh"
RenderObject: RenderEditable#245a2 relayoutBoundary=up22
  parentData: <none> (can use size)
  constraints: BoxConstraints(w=314.7, 0.0<=h<=Infinity)
  size: Size(314.7, 21.0)
  cursorColor: Color(0x00000000)
  showCursor: ValueNotifier<bool>#27255(true)
  maxLines: 1
  minLines: null
  selectionColor: Color(0xff90caf9)
  textScaleFactor: 1.0
  locale: en_US
  selection: TextSelection(baseOffset: 11, extentOffset: 11, affinity: null, isDirectional: false)
  offset: ScrollPositionWithSingleContext#a4875(offset: 0.0, range: 0.0..0.0, viewport: 314.7, ScrollableState, ClampingScrollPhysics, IdleScrollActivity#70a4d, ScrollDirection.idle)
  text: TextSpan
    debugLabel: ((englishLike subhead 2014).merge(blackMountainView subhead)).merge(unknown)
    inherit: false
    color: Color(0xff000000)
    family: Roboto
    size: 18.0
    weight: 400
    style: normal
    baseline: alphabetic
    decoration: TextDecoration.none
    "hgj@kskh.jh"

```

**Comment by VladyslavBondarenko** [comment]
Hi @ysoofiyani 
I see there's an issue addressing the case you described.
Please follow up on that issue [#25396](https://github.com/flutter/flutter/issues/25396),
I'm closing the current one as duplicate.
If you disagree please write in the comments
and I will reopen it.
Thank you
