### ISSUE TITLE
Connectivity 0.4.6+2 crashes if Proguard is applied.

### ISSUE THREAD

**Issue by appstute-pratik** [flutter/flutter#48466]
I'm using **connectivity 0.4.6+2** listen to connectivity changes, release app crashes on wifi connection restored. Debug works well.

Crash log:
`Fatal Exception: java.lang.NullPointerException: throw with null exception
       at com.pubnub.api.models.server.SubscribeMetadata.getTimetoken(SubscribeMetadata.java:3)
       at com.pubnub.api.managers.SubscriptionManager$5.a(SubscriptionManager.java:201)
       at com.pubnub.api.managers.SubscriptionManager$5.a(SubscriptionManager.java:2)
       at com.pubnub.api.endpoints.Endpoint$1.a(Endpoint.java:45)
       at retrofit2.ExecutorCallAdapterFactory$ExecutorCallbackCall$1$1.run(ExecutorCallAdapterFactory.java:37)
       at android.os.Handler.handleCallback(Handler.java:873)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:193)
       at android.app.ActivityThread.main(ActivityThread.java:6715)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:911)`

Flutter version:
Flutter 1.12.13+hotfix.5 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 27321ebbad (4 weeks ago) • 2019-12-10 18:15:01 -0800
Engine • revision 2994f7e1e6
Tools • Dart 2.7.0

**Comment by VladyslavBondarenko** [comment]
Hi @appstute-pratik 
In your logs I see that it is an pubnub issue.
It [should be fixed](https://github.com/Ingenio/flutter_pubnub/issues/12) for master channel.
Try to update this plugin.
If the problem persists, consider to write issue to the [flutter_pubnub](https://github.com/Ingenio/flutter_pubnub/issues) repository.
Closing, as this isn't an issue with Flutter itself,
if you disagree please write in the comments and I will reopen it
Thank you

**Comment by appstute-pratik** [comment]
Thanks
