### ISSUE TITLE
upgrading flutter version v1.9.1+hotfix.6 TO v1.10.15 crashing

### ISSUE THREAD

**Issue by idoroiengel** [flutter/flutter#48475]
1. downloaded flutter v1.9.1+hotfix.6
2. tried to upgrade to v1.10.15

## Logs

```
```
## command

flutter version v1.10.15

## exception

VersionCheckError: VersionCheckError: Command exited with code -9: git log -n 1 --pretty=format:%ad --date=iso
Standard error: 

```
#0      _runSync (package:flutter_tools/src/version.dart:525:5)
#1      FlutterVersion._latestGitCommitDate (package:flutter_tools/src/version.dart:145:12)
#2      FlutterVersion.frameworkCommitDate (package:flutter_tools/src/version.dart:133:37)
#3      FlutterVersion.toString (package:flutter_tools/src/version.dart:110:99)
#4      VersionCommand.runCommand (package:flutter_tools/src/commands/version.dart:111:32)
<asynchronous suspension>
#5      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:490:18)
<asynchronous suspension>
#6      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:407:33)
<asynchronous suspension>
#7      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:154:29)
<asynchronous suspension>
#8      _rootRun (dart:async/zone.dart:1124:13)
#9      _CustomZone.run (dart:async/zone.dart:1021:19)
#10     _runZoned (dart:async/zone.dart:1516:10)
#11     runZoned (dart:async/zone.dart:1463:12)
#12     AppContext.run (package:flutter_tools/src/base/context.dart:153:18)
<asynchronous suspension>
#13     FlutterCommand.run (package:flutter_tools/src/runner/flutter_command.dart:397:20)
#14     CommandRunner.runCommand (package:args/command_runner.dart:197:27)
<asynchronous suspension>
#15     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:402:21)
<asynchronous suspension>
#16     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:154:29)
<asynchronous suspension>
#17     _rootRun (dart:async/zone.dart:1124:13)
#18     _CustomZone.run (dart:async/zone.dart:1021:19)
#19     _runZoned (dart:async/zone.dart:1516:10)
#20     runZoned (dart:async/zone.dart:1463:12)
#21     AppContext.run (package:flutter_tools/src/base/context.dart:153:18)
<asynchronous suspension>
#22     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:356:19)
<asynchronous suspension>
#23     CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:112:25)
#24     new Future.sync (dart:async/future.dart:224:31)
#25     CommandRunner.run (package:args/command_runner.dart:112:14)
#26     FlutterCommandRunner.run (package:flutter_tools/src/runner/flutter_command_runner.dart:242:18)
#27     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:63:22)
<asynchronous suspension>
#28     _rootRun (dart:async/zone.dart:1124:13)
#29     _CustomZone.run (dart:async/zone.dart:1021:19)
#30     _runZoned (dart:async/zone.dart:1516:10)
#31     runZoned (dart:async/zone.dart:1500:12)
#32     run.<anonymous closure> (package:flutter_tools/runner.dart:61:18)
<asynchronous suspension>
#33     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:154:29)
<asynchronous suspension>
#34     _rootRun (dart:async/zone.dart:1124:13)
#35     _CustomZone.run (dart:async/zone.dart:1021:19)
#36     _runZoned (dart:async/zone.dart:1516:10)
#37     runZoned (dart:async/zone.dart:1463:12)
#38     AppContext.run (package:flutter_tools/src/base/context.dart:153:18)
<asynchronous suspension>
#39     runInContext (package:flutter_tools/src/context_runner.dart:59:24)
<asynchronous suspension>
#40     run (package:flutter_tools/runner.dart:50:10)
#41     main (package:flutter_tools/executable.dart:65:9)
<asynchronous suspension>
#42     main (file:///Users/idoroiengel/Public/flutter/packages/flutter_tools/bin/flutter_tools.dart:8:3)
#43     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:303:32)
#44     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:12)
```

## flutter doctor

```
encountered exception: VersionCheckError: Command exited with code -9: git log -n 1 --pretty=format:%ad --date=iso
Standard error: 

#0      _runSync (package:flutter_tools/src/version.dart:525:5)
#1      FlutterVersion._latestGitCommitDate (package:flutter_tools/src/version.dart:145:12)
#2      FlutterVersion.frameworkCommitDate (package:flutter_tools/src/version.dart:133:37)
#3      FlutterVersion.frameworkDate (package:flutter_tools/src/version.dart:95:31)
#4      FlutterValidator.validate (package:flutter_tools/src/doctor.dart:518:127)
<asynchronous suspension>
#5      Doctor.startValidatorTasks (package:flutter_tools/src/doctor.dart:140:52)
#6      Doctor.diagnose (package:flutter_tools/src/doctor.dart:211:41)
<asynchronous suspension>
#7      _doctorText.<anonymous closure> (package:flutter_tools/runner.dart:202:26)
#8      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:154:29)
<asynchronous suspension>
#9      _rootRun (dart:async/zone.dart:1124:13)
#10     _CustomZone.run (dart:async/zone.dart:1021:19)
#11     _runZoned (dart:async/zone.dart:1516:10)
#12     runZoned (dart:async/zone.dart:1463:12)
#13     AppContext.run (package:flutter_tools/src/base/context.dart:153:18)
<asynchronous suspension>
#14     _doctorText (package:flutter_tools/runner.dart:201:19)
<asynchronous suspension>
#15     _createLocalCrashReport (package:flutter_tools/runner.dart:179:32)
<asynchronous suspension>
#16     _handleToolError (package:flutter_tools/runner.dart:134:33)
<asynchronous suspension>
#17     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:68:22)
<asynchronous suspension>
#18     _rootRun (dart:async/zone.dart:1124:13)
#19     _CustomZone.run (dart:async/zone.dart:1021:19)
#20     _runZoned (dart:async/zone.dart:1516:10)
#21     runZoned (dart:async/zone.dart:1500:12)
#22     run.<anonymous closure> (package:flutter_tools/runner.dart:61:18)
<asynchronous suspension>
#23     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:154:29)
<asynchronous suspension>
#24     _rootRun (dart:async/zone.dart:1124:13)
#25     _CustomZone.run (dart:async/zone.dart:1021:19)
#26     _runZoned (dart:async/zone.dart:1516:10)
#27     runZoned (dart:async/zone.dart:1463:12)
#28     AppContext.run (package:flutter_tools/src/base/context.dart:153:18)
<asynchronous suspension>
#29     runInContext (package:flutter_tools/src/context_runner.dart:59:24)
<asynchronous suspension>
#30     run (package:flutter_tools/runner.dart:50:10)
#31     main (package:flutter_tools/executable.dart:65:9)
<asynchronous suspension>
#32     main (file:///Users/idoroiengel/Public/flutter/packages/flutter_tools/bin/flutter_tools.dart:8:3)
#33     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:303:32)
#34     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:12)
```
[✓] Flutter (Channel unknown, v1.10.15, on Mac OS X 10.15.2 19C57, locale en)
    • Flutter version 1.10.15 at /Users/idoroiengel/Public/flutter
    • Framework revision fbabb264e0 (10 weeks ago), 2019-11-02 01:36:07 +0300
    • Engine revision 8ea19b1c76
    • Dart version 2.6.0 (build 2.6.0-dev.8.2 bbe2ac28c9)

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/idoroiengel/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.3, Build version 11C29
    • CocoaPods version 1.8.4

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 42.1.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] Connected device (1 available)
    • SM T390 • 192.168.1.197:5555 • android-arm • Android 9 (API 28)

• No issues found!

```
```

**Comment by idoroiengel** [comment]
flutter tool was upgraded according to `flutter --version`

**Comment by iapicca** [comment]
Hi @idoroiengel
if you wish to use the latest stable version
you may want to run 
```console
flutter channel stable
flutter upgrade --force
```

regardless the version you choose to upgrade to
please run 
```console
flutter pub cache repair
cd <YOUR APP FOLDER>
flutter clean
```
If the issue persist please provide your updated 
`flutter doctor -v` and `flutter run --verbose`
thank you

**Comment by idoroiengel** [comment]
when I upgraded again to flutter v1.12.13+hotfix.5 it behaved the same, i.e. returned an error, but did in fact upgraded flutter and dart.

**Comment by VladyslavBondarenko** [comment]
Hi @idoroiengel 
given your last message I feel safe to close this issue,
if you disagree please write in the comments
and I will reopen it. 
Thank you
