### ISSUE TITLE
Getting the error "type 'Future<dynamic>' is not a subtype of type '() => FutureOr<dynamic>'"

### ISSUE THREAD

**Issue by subsbhatt** [flutter/flutter#48477]
Tried calling async method getRestaurantDataAPI() from sync method getRestaurantData()
using Lock from synchronized 2.1.1 package to make getRestaurantData() wait for the result....

## Steps to Reproduce

```
Widget build(BuildContext context) {
    return BaseView<HomeModel>(onModelReady: (model) {
      **model.getRestaurantData();**
    }, builder: (context, model, child) {
      return Scaffold(
        appBar: appBar(context),
        backgroundColor: Colors.white,
        body: model.state == ViewState.Busy
            ? Center(
                // child: CircularProgressIndicator(),
                child: SpinKitChasingDots(color: Color(0xfffd5f00)),
              )
            : SafeArea(
                child: Column(
                  children: <Widget>[
                    //Search Bar
                    Padding(
                      padding: const EdgeInsets.all(20.0),
                      child: TextField(
                        style: TextStyle(fontSize: 18),

                        //controller: _textFieldController,
                        decoration: InputDecoration(
                          contentPadding: EdgeInsets.fromLTRB(15, 17, 15, 15),
                          prefixIcon: Icon(
                            Icons.search,
                          ),

                          //Add th Hint text here.
                          hintText: "Search for Restaurants, Cuisine",
                          hintStyle: TextStyle(fontSize: 18),

                          focusedBorder: OutlineInputBorder(
                            borderRadius: BorderRadius.all(Radius.circular(10)),
                            borderSide:
                                BorderSide(color: Colors.black, width: 1.5),
                          ),

                          enabledBorder: OutlineInputBorder(
                            borderRadius: BorderRadius.all(Radius.circular(10)),
                            borderSide: BorderSide(
                                color: Colors.black.withOpacity(0.4),
                                width: 1.5),
                          ),
                        ),
                      ),
                    ),

                    //Restaurant Cards

                    Expanded(
                      child: ListView(
                        padding: const EdgeInsets.all(8.0),
                        children: <Widget>[
                           //strings.map((item) => new Text(item)).toList()
                           for(var data in model.homeDataJson)
                            restaurantCard(context, data),

                          // model.homeDataJson.map((data){
                          //   return restaurantCard();
                          // }).toList(),
                          
                      
                       
                        ],
                      ),
                    )
                  ],
                ),
              ),
      );
    });
  }



class HomeModel extends BaseModel{
  //Api _api = locator<Api>();
    Api get _api => locator<Api>();
    
  // final JsonDecoder _decoder = new JsonDecoder();

  List<RestaurantData> _homeDataJson;


  get homeDataJson => _homeDataJson;

  set homeDataJson(a){
    _homeDataJson = a;
  }

  dynamic getRestaurantData(){
    var lock = Lock();
    lock.synchronized(getRestaurantDataAPI());
  }

  dynamic getRestaurantDataAPI() async{
    
    setViewState(ViewState.Busy);

    //await Future.delayed(Duration(seconds: 3));
    
    //var response = await _api.get("/qeats/restaurants?latitude=28.50&longitude=70.50&token=wearegoingtorockit");
    var response = await _api.get("/catalog/foo");
    
    
    if (response['success']) {
      if(_homeDataJson == null) {
        print('*****getRestaurantData _homeDataJson is null');
        _homeDataJson = List<RestaurantData>();
      }

      for (var data in response['data']) {
        print('*****Type is ${data.runtimeType}');
        RestaurantData restData = RestaurantData.fromJson(data);
        print('*****Type is ${restData.runtimeType}');
        print('*****Type is ${restData.name}');
        _homeDataJson.add(restData);
      }
      //homeDataJson = restaurantData;
    }

    setViewState(ViewState.Idle);
    return true;

  }
}

```

**Snippet from yaml file**

```
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  simple_animations: ^1.3.0
  http: ^0.12.0+4
  get_it: ^3.1.0
  provider: ^2.0.1
  fluttertoast: ^3.1.0
  synchronized: ^2.1.1
  email_validator: ^1.0.0
  shared_preferences: ^0.5.3+1
  flutter_spinkit: ^3.1.0

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

```

**## Logs**

```
Installing build\app\outputs\apk\app.apk...                         2.6s
I/flutter ( 4446): Inside setupLocation                                 
Syncing files to device Android SDK built for x86...                    
I/flutter ( 4446): Inside initState of _SplashScreenState       
I/flutter ( 4446): Inside navigationPage of _SplashScreenState
I/flutter ( 4446): ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
I/flutter ( 4446): The following assertion was thrown building HomeScreen:
I/flutter ( 4446): type 'Future<dynamic>' is not a subtype of type '() => FutureOr<dynamic>'
I/flutter ( 4446):
I/flutter ( 4446): Either the assertion indicates an error in the framework itself, or we should provide substantially
I/flutter ( 4446): more information in this error message to help you determine and fix the underlying cause.      
I/flutter ( 4446): In either case, please report this assertion by filing a bug on GitHub:
I/flutter ( 4446):   https://github.com/flutter/flutter/issues/new?template=BUG.md
I/flutter ( 4446):
I/flutter ( 4446): The relevant error-causing widget was:
I/flutter ( 4446):   HomeScreen file:///D:/app_development/Food-Ordering-App/lib/ui/views/spash.dart:22:59
I/flutter ( 4446):
I/flutter ( 4446): When the exception was thrown, this was the stack:
I/flutter ( 4446): #0      HomeModel.getRestaurantData (package:food_delivery_app_crio/core/viewmodels/home_model.dart:25:23)
I/flutter ( 4446): #1      HomeScreen.build.<anonymous closure> (package:food_delivery_app_crio/ui/views/home.dart:16:13)
I/flutter ( 4446): #2      _BaseViewState.initState (package:food_delivery_app_crio/ui/views/base_view.dart)       
I/flutter ( 4446): #3      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4355:58)        
I/flutter ( 4446): #4      ComponentElement.mount (package:flutter/src/widgets/framework.dart:4201:5)
I/flutter ( 4446): #5      Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194:14)
I/flutter ( 4446): #6      Element.updateChild (package:flutter/src/widgets/framework.dart:2988:12)
I/flutter ( 4446): #7      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4243:16)
I/flutter ( 4446): #8      Element.rebuild (package:flutter/src/widgets/framework.dart:3947:5)
I/flutter ( 4446): #9      ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4206:5)        
I/flutter ( 4446): #10     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4201:5)
I/flutter ( 4446): #11     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194:14)

```

**the output of running `flutter doctor -v` here. -->**
```

PS D:\app_development\Food-Ordering-App> flutter doctor -v
[√] Flutter (Channel stable, v1.12.13+hotfix.5, on Microsoft Windows [Version 10.0.18362.535], locale en-IN)
    • Flutter version 1.12.13+hotfix.5 at D:\flutter
    • Framework revision 27321ebbad (4 weeks ago), 2019-12-10 18:15:01 -0800
    • Engine revision 2994f7e1e6
    • Dart version 2.7.0

 
[!] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at C:\Users\subsb\AppData\Local\Android\Sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • ANDROID_HOME = C:\Users\subsb\AppData\Local\Android\Sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses

[√] Android Studio (version 3.5)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 42.1.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)

[!] IntelliJ IDEA Community Edition (version 2019.3)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2019.2.3
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.dev/intellij-setup/#installing-the-plugins

[√] VS Code (version 1.41.1)
    • VS Code at C:\Users\subsb\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.7.1

[√] Connected device (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 8.1.0 (API 27) (emulator)
```

**Comment by iapicca** [comment]
Hi @subsbhatt 
the error you are reporting seems related to the 3rd party plugin [synchronized](https://pub.dev/packages/synchronized)
you may want to open an issue in the dedicated [github](https://github.com/tekartik/synchronized.dart/issues)

Closing, as this isn't an issue with Flutter itself,
if you disagree please write in the comments and I will reopen it
Thank you
