### ISSUE TITLE
[web]: Error on button click to send OTP to mobile

### ISSUE THREAD

**Issue by Dinesh2703** [flutter/flutter#48495]
I am using flutter_otp package to send otp. Its for web also but giving below error.
---------------
```
Uncaught (in promise) Error: MissingPluginException(No implementation found for method sendSMS on channel plugins.babariviere.com/sendSMS)
    at Object.throw_ [as throw] (errors.dart:196)
    at MethodChannel.invokeMethod (platform_channel.dart:319)
    at invokeMethod.next (<anonymous>)
    at onValue (async_patch.dart:47)
    at _RootZone.runUnary (zone.dart:1381)
    at _FutureListener.thenAwait.handleValue (future_impl.dart:139)
    at handleValueCallback (future_impl.dart:680)
    at Function._propagateToListeners (future_impl.dart:709)
    at _Future.new.[_completeWithValue] (future_impl.dart:524)
    at async._AsyncCallbackEntry.new.callback (future_impl.dart:554)
    at Object._microtaskLoop (schedule_microtask.dart:43)
    at _startMicrotaskLoop (schedule_microtask.dart:52)
    at async_patch.dart:168
```

flutter doctor
```
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel beta, v1.12.13+hotfix.6, on Microsoft Windows [Version 10.0.18362.535], locale en-IN)
 
[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[√] Chrome - develop for the web
[√] Android Studio (version 3.5)
[√] VS Code (version 1.41.1)
[√] Connected device (2 available)

• No issues found!
```
---------------------------
flutter run --verbose ---
```
[  +22 ms] executing: [C:\Repos\flutter\] git -c log.showSignature=false log -n 1 --pretty=format:%H
[  +59 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[        ] 18cd7a3601bcffb36fdf2f679f763b5e827c2e8e
[        ] executing: [C:\Repos\flutter\] git describe --match v*.*.* --first-parent --long --tags
[  +53 ms] Exit code 0 from: git describe --match v*.*.* --first-parent --long --tags
[        ] v1.12.13+hotfix.6-0-g18cd7a360
[   +7 ms] executing: [C:\Repos\flutter\] git rev-parse --abbrev-ref --symbolic @{u}
[  +44 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[   +1 ms] origin/beta
[        ] executing: [C:\Repos\flutter\] git ls-remote --get-url origin
[  +41 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[  +91 ms] executing: [C:\Repos\flutter\] git rev-parse --abbrev-ref HEAD
[  +39 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] beta
[ +108 ms] executing: C:\Users\Dinesh\AppData\Local\Android\sdk\platform-tools\adb.exe devices -l
[  +24 ms] Exit code 0 from: C:\Users\Dinesh\AppData\Local\Android\sdk\platform-tools\adb.exe devices -l
[   +1 ms] List of devices attached
[  +30 ms] More than one device connected; please specify a device with the '-d <deviceId>' flag, or use '-d all' to act on all devices.
[  +50 ms] Chrome     • chrome     • web-javascript • Google Chrome 79.0.3945.117
[   +3 ms] Web Server • web-server • web-javascript • Flutter Tools
[  +17 ms] "flutter run" took 272ms.

#0      throwToolExit (package:flutter_tools/src/base/common.dart:28:3)
#1      RunCommand.validateCommand (package:flutter_tools/src/commands/run.dart:289:7)
<asynchronous suspension>
#2      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:590:11)
#3      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:515:33)
<asynchronous suspension>
#4      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:146:29)
#5      _rootRun (dart:async/zone.dart:1126:13)
#6      _CustomZone.run (dart:async/zone.dart:1023:19)
#7      _runZoned (dart:async/zone.dart:1518:10)
#8      runZoned (dart:async/zone.dart:1465:12)
#9      AppContext.run (package:flutter_tools/src/base/context.dart:145:18)
#10     FlutterCommand.run (package:flutter_tools/src/runner/flutter_command.dart:505:20)
#11     CommandRunner.runCommand (package:args/command_runner.dart:197:27)
#12     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:413:21)
<asynchronous suspension>
#13     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:146:29)
#14     _rootRun (dart:async/zone.dart:1126:13)
#15     _CustomZone.run (dart:async/zone.dart:1023:19)
#16     _runZoned (dart:async/zone.dart:1518:10)
#17     runZoned (dart:async/zone.dart:1465:12)
#18     AppContext.run (package:flutter_tools/src/base/context.dart:145:18)
#19     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:364:19)
#20     CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:112:25)
#21     new Future.sync (dart:async/future.dart:224:31)
#22     CommandRunner.run (package:args/command_runner.dart:112:14)
#23     FlutterCommandRunner.run (package:flutter_tools/src/runner/flutter_command_runner.dart:250:18)
#24     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:63:22)
#25     _rootRun (dart:async/zone.dart:1126:13)
#26     _CustomZone.run (dart:async/zone.dart:1023:19)
#27     _runZoned (dart:async/zone.dart:1518:10)
#28     runZoned (dart:async/zone.dart:1502:12)
#29     run.<anonymous closure> (package:flutter_tools/runner.dart:61:18)
<asynchronous suspension>
#30     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:146:29)
#31     _rootRun (dart:async/zone.dart:1126:13)
#32     _CustomZone.run (dart:async/zone.dart:1023:19)
#33     _runZoned (dart:async/zone.dart:1518:10)
#34     runZoned (dart:async/zone.dart:1465:12)
#35     AppContext.run (package:flutter_tools/src/base/context.dart:145:18)
#36     runInContext (package:flutter_tools/src/context_runner.dart:64:24)
#37     run (package:flutter_tools/runner.dart:50:10)
#38     main (package:flutter_tools/executable.dart:65:9)
#39     main (file:///C:/Repos/flutter/packages/flutter_tools/bin/flutter_tools.dart:8:3)
#40     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:305:32)
#41     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:174:12)
```

**Comment by VladyslavBondarenko** [comment]
Hi @Dinesh2703 
`MissingPluginException` could be thrown if a plugin was not yet injected into your project.
Have you rebuilt your project after adding `flutter_otp` to your `pubspec.yaml` and running `flutter pub get`?
Thank you

**Comment by jonahwilliams** [comment]
The error is caused by whatever plugin has a "method sendSMS" method not supporting the web. This is not an issue with flutter, and should instead be raised on whatever issue tracker that plugin uses

**Comment by Dinesh2703** [comment]
thanks @VladyslavBondarenko , using flutter_otp was my mistake.
thanks @jonahwilliams  for help. issue was the same that you mentioned.
