### ISSUE TITLE
Popup menu in Stocks throws exception

### ISSUE THREAD

**Issue by abarth** [flutter/flutter#485]
The Positioned inside the menu isn't a direct child of the stack anymore.

```
android: I/flutter : ------------------------------------------------------------------------
android: I/flutter : Exception caught while building _ModalScope-[GlobalKey 623944407]
android: I/flutter : 'packages/flutter/src/widgets/basic.dart': Failed assertion: line 765: '() {
android: I/flutter :           "Positioned must placed inside a Stack";
android: I/flutter :           return ancestor is Stack;
android: I/flutter :         }' is not true.
android: I/flutter : Stack trace:
android: I/flutter : #0      _AssertionError._throwNew (dart:core-patch/errors_patch.dart:27)
android: I/flutter : #1      Positioned.debugValidateAncestor (packages/flutter/src/widgets/basic.dart:765)
android: I/flutter : #2      ParentDataElement.mount.<anonymous closure> (packages/flutter/src/widgets/framework.dart:1223)
android: I/flutter : #3      ParentDataElement.mount (packages/flutter/src/widgets/framework.dart:1213)
android: I/flutter : #4      Element._inflateWidget (packages/flutter/src/widgets/framework.dart:767)
android: I/flutter : #5      Element.updateChild (packages/flutter/src/widgets/framework.dart:646)
android: I/flutter : #6      ComponentElement.performRebuild (packages/flutter/src/widgets/framework.dart:1079)
android: I/flutter : #7      BuildableElement.rebuild (packages/flutter/src/widgets/framework.dart:1008)
android: I/flutter : #8      ComponentElement._firstBuild (packages/flutter/src/widgets/framework.dart:1054)
android: I/flutter : #9      StatefulComponentElement._firstBuild (packages/flutter/src/widgets/framework.dart:1148)
android: I/flutter : #10     ComponentElement.mount (packages/flutter/src/widgets/framework.dart:1049)
android: I/flutter : #11     Element._inflateWidget (packages/flutter/src/widgets/framework.dart:767)
android: I/flutter : #12     Element.updateChild (packages/flutter/src/widgets/framework.dart:646)
```

**Comment by abarth** [comment]
This is because I added a `ForcedLayer` in the overlay.
