### ISSUE TITLE
When building iOS app, fetching could not build the precompiled application for the device 

### ISSUE THREAD

**Issue by bipinvaylu** [flutter/flutter#48501]
## Steps to Reproduce
Just created build new simple flutter app using Android Studio and getting this error.

**Target Platform: iOS**
**Target OS version/browser: 12.4.3**
**Devices:iPhone 6**

## Logs
flutter run --debug --verbose

```
[   +5 ms] Could not build the precompiled application for the device.
[   +7 ms] Error launching application on Bipin’s iPhone.
[   +5 ms] "flutter run" took 23,915ms.

#0      throwToolExit (package:flutter_tools/src/base/common.dart:27:3)
#1      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:559:7)
<asynchronous suspension>
#2      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:625:18)
#3      _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:75:64)
#4      _rootRunUnary (dart:async/zone.dart:1134:38)
#5      _CustomZone.runUnary (dart:async/zone.dart:1031:19)
#6      _FutureListener.handleValue (dart:async/future_impl.dart:140:18)
#7      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:682:45)
#8      Future._propagateToListeners (dart:async/future_impl.dart:711:32)
#9      Future._completeWithValue (dart:async/future_impl.dart:526:5)
#10     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:34:15)
#11     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:293:13)
#12     RunCommand.usageValues (package:flutter_tools/src/commands/run.dart)
#13     _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:75:64)
#14     _rootRunUnary (dart:async/zone.dart:1134:38)
#15     _CustomZone.runUnary (dart:async/zone.dart:1031:19)
#16     _FutureListener.handleValue (dart:async/future_impl.dart:140:18)
#17     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:682:45)
#18     Future._propagateToListeners (dart:async/future_impl.dart:711:32)
#19     Future._completeWithValue (dart:async/future_impl.dart:526:5)
#20     Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:556:7)
#21     _rootRun (dart:async/zone.dart:1126:13)
#22     _CustomZone.run (dart:async/zone.dart:1023:19)
#23     _CustomZone.runGuarded (dart:async/zone.dart:925:7)
#24     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:965:23)
#25     _microtaskLoop (dart:async/schedule_microtask.dart:43:21)
#26     _startMicrotaskLoop (dart:async/schedule_microtask.dart:52:5)
#27     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
#28     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:175:5)
```
flutter doctor

```
Running flutter doctor...
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel master, v1.13.8-pre.58, on Mac OS X 10.15.2 19C57, locale en-IN)
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 11.2)
[✓] Android Studio (version 3.5)
[✓] VS Code (version 1.41.1)
[✓] Connected device (1 available)

• No issues found!
```
flutter --version
```
Flutter 1.13.8-pre.58 • channel master • https://github.com/flutter/flutter.git
Framework • revision fabf4e3d0d (15 hours ago) • 2020-01-08 15:28:02 -0800
Engine • revision 46adf73d51
Tools • Dart 2.8.0 (build 2.8.0-dev.0.0 c0ca187f26)
```

It's happening for me with each app.

**Comment by bipinvaylu** [comment]
Finally, I am able to fix this issue with help of this SO answer: https://stackoverflow.com/a/59338807/722683
