### ISSUE TITLE
Can't showModalBottomSheet inside of RouteObserver.didPop

### ISSUE THREAD

**Issue by sanekyy** [flutter/flutter#48564]
I am listen Navigetor navigatorObservers and when user exist form some screens I want to show modal popup. I call showModalBottomSheet inside MyRouteObserver.didPop method and have error.

**Target Platform:** Android
**Target OS version/browser:** Android 8.1.0, MINU 10.2

## Logs

```
[   +8 ms] V/FA      (29143): Setting current screen to name, class: /, Flutter
[   +1 ms] I/flutter (29143): 10-01-2020–14:35:44:3544 [feedback_bloc]: didPop: previousRouteName - /, routeName - /place
[        ] I/flutter (29143): 10-01-2020–14:35:44:3544 [feedback_bloc]: place card closed -> show feedback bottom sheet
[        ] I/flutter (29143): 10-01-2020–14:35:44:3544 [feedback_bloc]: showFeedbackBottomSheet
[        ] V/FA      (29143): Recording user engagement, ms: 5406
[   +5 ms] I/flutter (29143): Flutter error caught by Crashlytics plugin:
[   +6 ms] D/FA      (29143): Logging event (FE): screen_view(_vs), Bundle[{firebase_event_origin(_o)=auto, firebase_previous_class(_pc)=Flutter, firebase_previous_id(_pi)=-6308074188998608129,
firebase_previous_screen(_pn)=/place, firebase_screen_class(_sc)=Flutter, firebase_screen_id(_si)=-6308074188998608128, firebase_screen(_sn)=/}]
[  +43 ms] I/flutter (29143): ══╡ EXCEPTION CAUGHT BY FOUNDATION LIBRARY ╞════════════════════════════════════════════════════════
[        ] I/flutter (29143): The following assertion was thrown while dispatching notifications for ValueNotifier<RefreshStatus>:
[        ] I/flutter (29143): 'package:flutter/src/widgets/navigator.dart': Failed assertion: line 1782 pos 12: '!_debugLocked':
[        ] I/flutter (29143): is not true.
[        ] I/flutter (29143): 
[   +2 ms] I/flutter (29143): Either the assertion indicates an error in the framework itself, or we should provide substantially
[        ] I/flutter (29143): more information in this error message to help you determine and fix the underlying cause.
[        ] I/flutter (29143): In either case, please report this assertion by filing a bug on GitHub:
[        ] I/flutter (29143):   https://github.com/flutter/flutter/issues/new?template=BUG.md
[   +3 ms] I/flutter (29143): 
[        ] I/flutter (29143): When the exception was thrown, this was the stack:
[        ] I/flutter (29143): #2      NavigatorState.push (package:flutter/src/widgets/navigator.dart:1782:12)
[        ] I/flutter (29143): #3      showModalBottomSheet (package:flutter/src/material/bottom_sheet.dart:532:65)
[        ] I/flutter (29143): #4      FeedbackBloc.showFeedbackBottomSheet (package:gohere/domain/feedback_bloc.dart:119:5)
[        ] I/flutter (29143): #5      FeedbackBloc.didPop (package:gohere/domain/feedback_bloc.dart:90:7)
[        ] I/flutter (29143): #6      NavigatorState.pop (package:flutter/src/widgets/navigator.dart:2136:20)
[        ] I/flutter (29143): #7      Navigator.pop (package:flutter/src/widgets/navigator.dart:1387:34)
[        ] I/flutter (29143): #8      _PlacePageState._exit (package:gohere/ui/page/place_page.dart:330:15)
[        ] I/flutter (29143): #9      RefreshIndicatorState._handleModeChange (package:pull_to_refresh/src/internals/indicator_wrap.dart:275:50)
[        ] I/flutter (29143): #10     ChangeNotifier.notifyListeners (package:flutter/src/foundation/change_notifier.dart:206:21)
[        ] I/flutter (29143): #11     ValueNotifier.value= (package:flutter/src/foundation/change_notifier.dart:273:5)
[        ] I/flutter (29143): #12     IndicatorStateMixin.mode= (package:pull_to_refresh/src/internals/indicator_wrap.dart:552:28)
[        ] I/flutter (29143): #13     RefreshIndicatorState._dispatchModeByOffset.<anonymous closure> (package:pull_to_refresh/src/internals/indicator_wrap.dart:218:11)
[        ] I/flutter (29143): (elided 15 frames from class _AssertionError and package dart:async)
[        ] I/flutter (29143): 
[        ] I/flutter (29143): The ValueNotifier<RefreshStatus> sending notification was:
[        ] I/flutter (29143):   ValueNotifier<RefreshStatus>#61913(RefreshStatus.refreshing)
[        ] I/flutter (29143): ════════════════════════════════════════════════════════════════════════════════════════════════════
[  +18 ms] D/FA      (29143): Logging event (FE): user_engagement(_e), Bundle[{firebase_event_origin(_o)=auto, engagement_time_msec(_et)=5406, firebase_screen_class(_sc)=Flutter,
firebase_screen_id(_si)=-6308074188998608129, firebase_screen(_sn)=/place}]
[  +32 ms] I/flutter (29143): 10-01-2020–14:35:44:3544 [video_service]: setVideoUrl called for: https://api.terra-incognita.tk/static/d38cd2ae-22ef-4618-9e0b-1f4da8eb0a8f
[        ] I/flutter (29143): 10-01-2020–14:35:44:3544 [video_service]: Same vide
```

```
flutter doctor -v
[✓] Flutter (Channel dev, v1.13.7, on Mac OS X 10.15.2 19C57, locale en-RU)
    • Flutter version 1.13.7 at /Users/sanekyy/Programs/flutter
    • Framework revision a3bbdfb23a (7 days ago), 2020-01-03 16:19:11 -0500
    • Engine revision eb139936eb
    • Dart version 2.8.0 (build 2.8.0-dev.0.0 2f57602411)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/sanekyy/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Users/sanekyy/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/191.6010548/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.3, Build version 11C29
    • CocoaPods version 1.8.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 3.5)
    • Android Studio at /Users/sanekyy/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/191.6010548/Android Studio.app/Contents
    • Flutter plugin version 42.1.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[!] IntelliJ IDEA Ultimate Edition (version 2019.3.1)
    • IntelliJ at /Users/sanekyy/Applications/JetBrains Toolbox/IntelliJ IDEA Ultimate.app
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.dev/intellij-setup/#installing-the-plugins

[!] VS Code (version 1.41.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    ✗ Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (4 available)
    • Redmi Note 6 Pro • 3193ac21   • android-arm64  • Android 8.1.0 (API 27)
    • macOS            • macOS      • darwin-x64     • Mac OS X 10.15.2 19C57
    • Chrome           • chrome     • web-javascript • Google Chrome 79.0.3945.117
    • Web Server       • web-server • web-javascript • Flutter Tools

! Doctor found issues in 2 categories.
```

**Comment by VladyslavBondarenko** [comment]
Hi @sanekyy 
To better address the issue, would be helpful
if you could post a minimal code sample to reproduce the problem
Thank you

**Comment by sanekyy** [comment]
Hello. 
Here is sample code for reproduce error:

```dart

import 'package:flutter/material.dart';

void main() => runApp(MyApp());

MyNavigatorObserver myNavigatorObserver = MyNavigatorObserver();

class MyApp extends StatelessWidget {
  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Show modal bottom sheet inside didPop error sample',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: FirstPage(),
      routes: {
        SecondPage.routeName: (_) => SecondPage(),
      },
      navigatorObservers: [myNavigatorObserver],
    );
  }
}

class FirstPage extends StatefulWidget {
  FirstPage({Key key}) : super(key: key);

  @override
  _FirstPageState createState() => _FirstPageState();
}

class _FirstPageState extends State<FirstPage> {
  @override
  Widget build(BuildContext context) {
    myNavigatorObserver.setContext(context);
    return Scaffold(
      appBar: AppBar(
        title: Text('First page'),
      ),
      body: Center(
          child: RaisedButton(
        child: Text("Open second page"),
        onPressed: () => Navigator.pushNamed(context, SecondPage.routeName),
      )),
    );
  }
}

class SecondPage extends StatefulWidget {
  static const routeName = '/secondPage';

  SecondPage({Key key}) : super(key: key);

  @override
  _SecondPageState createState() => _SecondPageState();
}

class _SecondPageState extends State<SecondPage> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('Second page'),
      ),
      body: Center(
          child: RaisedButton(
        child: Text(
          "Back to first page and try to show modal bottom sheet",
        ),
        onPressed: () => Navigator.pop(context),
      )),
    );
  }
}

class MyNavigatorObserver extends NavigatorObserver {
  BuildContext _context;

  void setContext(BuildContext context) {
    _context = context;
  }

  @override
  void didPop(Route route, Route previousRoute) {
    super.didPop(route, previousRoute);

    showModalBottomSheet(
      context: _context,
      builder: (_) => Container(color: Colors.blue),
    );
  }
}

```

**Comment by darshankawar** [comment]
Issue replicable on latest dev.

**Comment by huycozy** [comment]
This issue is reproducible on the latest `stable` and `master` channels.

<details>
<summary>Exception logs</summary>

```bash
══╡ EXCEPTION CAUGHT BY GESTURE ╞═══════════════════════════════════════════════════════════════════
The following assertion was thrown while handling a gesture:
Assertion failed:
file:///Users/huynq/Documents/GitHub/flutter/packages/flutter/lib/src/widgets/navigator.dart:4475:12
!_debugLocked
is not true

When the exception was thrown, this was the stack:
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 266:49      throw_
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 29:3        assertFailed
packages/flutter/src/widgets/navigator.dart 4475:13                               [_pushEntry]
packages/flutter/src/widgets/navigator.dart 4412:5                                push
packages/flutter/src/material/bottom_sheet.dart 707:19                            showModalBottomSheet
packages/reproduce_issues/pre2.0/modelbottomsheet_48564.dart 88:5                 didPop
packages/flutter/src/widgets/navigator.dart 3158:13                               notify
dart-sdk/lib/_internal/js_dev_runtime/private/js_array.dart 201:8                 forEach]
packages/flutter/src/widgets/navigator.dart 4006:27                               [_flushObserverNotifications]
packages/flutter/src/widgets/navigator.dart 3958:5                                [_flushHistoryUpdates]
packages/flutter/src/widgets/navigator.dart 4967:7                                pop
packages/flutter/src/widgets/navigator.dart 2433:25                               pop
packages/reproduce_issues/pre2.0/modelbottomsheet_48564.dart 71:40                <fn>
packages/flutter/src/material/ink_well.dart 1072:21                               handleTap
packages/flutter/src/gestures/recognizer.dart 253:24                              invokeCallback
packages/flutter/src/gestures/tap.dart 627:11                                     handleTapUp
packages/flutter/src/gestures/tap.dart 306:5                                      [_checkUp]
packages/flutter/src/gestures/tap.dart 239:7                                      handlePrimaryPointer
packages/flutter/src/gestures/recognizer.dart 615:9                               handleEvent
packages/flutter/src/gestures/pointer_router.dart 98:12                           [_dispatch]
packages/flutter/src/gestures/pointer_router.dart 143:9                           <fn>
dart-sdk/lib/_internal/js_dev_runtime/private/linked_hash_map.dart 21:13          forEach
packages/flutter/src/gestures/pointer_router.dart 141:17                          [_dispatchEventToRoutes]
packages/flutter/src/gestures/pointer_router.dart 127:7                           route
packages/flutter/src/gestures/binding.dart 460:19                                 handleEvent
packages/flutter/src/gestures/binding.dart 440:14                                 dispatchEvent
packages/flutter/src/rendering/binding.dart 337:11                                dispatchEvent
packages/flutter/src/gestures/binding.dart 395:7                                  [_handlePointerEventImmediately]
packages/flutter/src/gestures/binding.dart 357:5                                  handlePointerEvent
packages/flutter/src/gestures/binding.dart 314:7                                  [_flushPointerEventQueue]
packages/flutter/src/gestures/binding.dart 295:7                                  [_handlePointerDataPacket]
lib/_engine/engine/platform_dispatcher.dart 1183:13                               invoke1
lib/_engine/engine/platform_dispatcher.dart 244:5                                 invokeOnPointerDataPacket
lib/_engine/engine/pointer_binding.dart 147:39                                    [_onPointerData]
lib/_engine/engine/pointer_binding.dart 653:20                                    <fn>
lib/_engine/engine/pointer_binding.dart 594:14                                    <fn>
lib/_engine/engine/pointer_binding.dart 288:16                                    loggedHandler
lib/_engine/engine/pointer_binding.dart 179:80                                    <fn>
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/operations.dart 334:14  _checkAndCall
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/operations.dart 339:39  dcall

Handler: "onTap"
Recognizer:
  TapGestureRecognizer#24d65
════════════════════════════════════════════════════════════════════════════════════════════════════

```
</details>

<details>
<summary>flutter doctor -v (stable and master)</summary>

```bash
[✓] Flutter (Channel stable, 3.3.5, on macOS 12.6 21G115 darwin-x64, locale en-VN)
    • Flutter version 3.3.5 on channel stable at /Users/huynq/Documents/GitHub/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision d9111f6402 (9 hours ago), 2022-10-19 12:27:13 -0700
    • Engine revision 3ad69d7be3
    • Dart version 2.18.2
    • DevTools version 2.15.0

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/huynq/Library/Android/sdk
    • Platform android-33, build-tools 31.0.0
    • ANDROID_HOME = /Users/huynq/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.0.1)
    • Xcode at /Applications/Xcode14.0.1.app/Contents/Developer
    • Build 14A400
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[✓] IntelliJ IDEA Community Edition (version 2022.2.2)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 70.0.5
    • Dart plugin version 222.4167.21

[✓] IntelliJ IDEA Community Edition (version 2022.1.1)
    • IntelliJ at /Users/huynq/Library/Application Support/JetBrains/Toolbox/apps/IDEA-C/ch-0/221.5591.52/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.72.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.50.0

[✓] Connected device (3 available)
    • iPhone 14 Pro Max (mobile) • 332079AF-E895-4685-910E-7B1E18B0C6B8 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-16-0 (simulator)
    • macOS (desktop)            • macos                                • darwin-x64     • macOS 12.6 21G115 darwin-x64
    • Chrome (web)               • chrome                               • web-javascript • Google Chrome 106.0.5249.119

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!

```

```bash
[✓] Flutter (Channel master, 3.5.0-9.0.pre.28, on macOS 12.6 21G115 darwin-x64, locale en-VN)
    • Flutter version 3.5.0-9.0.pre.28 on channel master at /Users/huynq/Documents/GitHub/flutter_master
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 49405135d7 (2 hours ago), 2022-10-19 20:23:12 -0700
    • Engine revision 563b8e830c
    • Dart version 2.19.0 (build 2.19.0-317.0.dev)
    • DevTools version 2.18.0

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/huynq/Library/Android/sdk
    • Platform android-33, build-tools 31.0.0
    • ANDROID_HOME = /Users/huynq/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.0.1)
    • Xcode at /Applications/Xcode14.0.1.app/Contents/Developer
    • Build 14A400
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[✓] IntelliJ IDEA Community Edition (version 2022.2.2)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 70.0.5
    • Dart plugin version 222.4167.21

[✓] IntelliJ IDEA Community Edition (version 2022.1.1)
    • IntelliJ at /Users/huynq/Library/Application Support/JetBrains/Toolbox/apps/IDEA-C/ch-0/221.5591.52/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.72.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.50.0

[✓] Connected device (3 available)
    • iPhone 14 Pro Max (mobile) • 332079AF-E895-4685-910E-7B1E18B0C6B8 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-16-0 (simulator)
    • macOS (desktop)            • macos                                • darwin-x64     • macOS 12.6 21G115 darwin-x64
    • Chrome (web)               • chrome                               • web-javascript • Google Chrome 106.0.5249.119

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!

```
</details>
