### ISSUE TITLE
Can't Test with mockObserver navigation in an app with Multiprovider. 

### ISSUE THREAD

**Issue by belaad** [flutter/flutter#48628]
This worked when I had just one provider but doesn't when I do setup with Multiprovider.

```dart
// Mock class
class MockNavigatorObserver extends Mock implements NavigatorObserver {}

class MockAuthProvider extends Mock implements AuthProvider {}

class MockUserProfileProvider extends Mock implements UserProfileProvider {}

NavigatorObserver mockNavigatorObserver;
MockAuthProvider mockAuthProvider;
MockUserProfileProvider mockUserProfileProvider;

void main() {
 setUp(() {
    mockNavigatorObserver = MockNavigatorObserver();
    mockAuthProvider = MockAuthProvider();
    mockUserProfileProvider = MockUserProfileProvider();
  });

Future<Null> buildWidget({
  WidgetTester tester,
  Widget widgetToBuild,
}) async {
  await tester.pumpWidget(
    MultiProvider(
    providers: [
      ChangeNotifierProvider<AuthProvider>(create: (BuildContext context) {
        return mockAuthProvider;
      }),
      ChangeNotifierProvider<UserProfileProvider>(
          create: (BuildContext context) {
        return mockUserProfileProvider;
      }),
    ],
    child: MaterialApp(
      // the non-config bit next line
      home: widgetToBuild,
      //more config below
      routes: RouteConfig.routes,
      navigatorObservers: [mockNavigatorObserver],
    ),
  ));

  tester.pumpAndSettle();

  verify(mockNavigatorObserver.didPush(any, any));
}

Future<Null> navigateToPageByButtonKey(
    WidgetTester tester, String buttonKey) async {
  Finder buttonFinder = find.byKey(Key(buttonKey));
  expect(buttonFinder, findsOneWidget);

  await tester.tap(buttonFinder);
  await tester.pumpAndSettle();
}

testWidgets('CreateProfile .. NextButton -> CalendarScreen',
      (WidgetTester tester) async {
    await buildWidget(
      widgetToBuild: CreateProfileScreen(),
      tester: tester,
    );

    var userNameField =
        find.byKey(Key(CREATE_PROFILE_SCREEN_USERNAME_FORM_FIELD_KEY));
    await tester.enterText(userNameField, 'testUserName');
    await navigateToPageByButtonKey(
        tester, CREATE_PROFILE_SCREEN_NEXT_BUTTON_KEY);
    // verify(mockNavigatorObserver.didPush(any, any));
    expect(find.byKey(Key(CALENDAR_SCREEN_KEY)), findsOneWidget);
  });
}

```

run output:
```bash
══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
The following assertion was thrown building MultiProvider:
Failed assertion: boolean expression must not be null

Either the assertion indicates an error in the framework itself, or we should provide substantially
more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=BUG.md

The relevant error-causing widget was:
  MultiProvider
  file:///Users/derga002/Projects/flutter/nanny_share/nanny_share/test/test_helper.dart:33:5

When the exception was thrown, this was the stack:
#0      _ListenableDelegateMixin.debugCheckIsNewlyCreatedListenable (package:provider/src/listenable_provider.dart:140:26)
#1      _BuilderListenableDelegate.startListening (package:provider/src/listenable_provider.dart:128:12)
#2      _ListenableDelegateMixin.initDelegate (package:provider/src/listenable_provider.dart:169:24)
#3      _DelegateWidgetState._initDelegate (package:provider/src/delegate_widget.dart:118:21)
#4      _DelegateWidgetState.initState (package:provider/src/delegate_widget.dart:110:5)
#5      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4355:58)
#6      ComponentElement.mount (package:flutter/src/widgets/framework.dart:4201:5)
#7      Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194:14)
#8      Element.updateChild (package:flutter/src/widgets/framework.dart:2988:12)
#9      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4243:16)
#10     Element.rebuild (package:flutter/src/widgets/framework.dart:3947:5)
#11     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4206:5)
#12     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4201:5)
#13     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194:14)
#14     Element.updateChild (package:flutter/src/widgets/framework.dart:2988:12)
#15     RenderObjectToWidgetElement._rebuild (package:flutter/src/widgets/binding.dart:1028:16)
#16     RenderObjectToWidgetElement.update (package:flutter/src/widgets/binding.dart:1006:5)
#17     RenderObjectToWidgetElement.performRebuild (package:flutter/src/widgets/binding.dart:1020:7)
#18     Element.rebuild (package:flutter/src/widgets/framework.dart:3947:5)
#19     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2432:33)
#20     AutomatedTestWidgetsFlutterBinding.drawFrame (package:flutter_test/src/binding.dart:974:18)
#21     RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:283:5)
#22     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1102:15)
#23     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1041:9)
#24     AutomatedTestWidgetsFlutterBinding.pump.<anonymous closure> (package:flutter_test/src/binding.dart:872:9)
#27     TestAsyncUtils.guard (package:flutter_test/src/test_async_utils.dart:69:41)
#28     AutomatedTestWidgetsFlutterBinding.pump (package:flutter_test/src/binding.dart:859:27)
#29     WidgetTester.pumpWidget.<anonymous closure> (package:flutter_test/src/widget_tester.dart:323:22)
#32     TestAsyncUtils.guard (package:flutter_test/src/test_async_utils.dart:69:41)
#33     WidgetTester.pumpWidget (package:flutter_test/src/widget_tester.dart:320:27)
#34     buildWidget (file:///Users/derga002/Projects/flutter/nanny_share/nanny_share/test/test_helper.dart:32:16)
#35     main.<anonymous closure> (file:///Users/derga002/Projects/flutter/nanny_share/nanny_share/test/create_profile_screen_test.dart:13:11)
#36     testWidgets.<anonymous closure>.<anonymous closure> (package:flutter_test/src/widget_tester.dart:124:25)
#37     TestWidgetsFlutterBinding._runTestBody (package:flutter_test/src/binding.dart:696:19)
<asynchronous suspension>
#40     TestWidgetsFlutterBinding._runTest (package:flutter_test/src/binding.dart:679:14)
#41     AutomatedTestWidgetsFlutterBinding.runTest.<anonymous closure> (package:flutter_test/src/binding.dart:1050:24)
#47     AutomatedTestWidgetsFlutterBinding.runTest (package:flutter_test/src/binding.dart:1047:15)
#48     testWidgets.<anonymous closure> (package:flutter_test/src/widget_tester.dart:121:22)
#49     Declarer.test.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:test_api/src/backend/declarer.dart:171:27)
<asynchronous suspension>
#50     Invoker.waitForOutstandingCallbacks.<anonymous closure> (package:test_api/src/backend/invoker.dart:242:15)
#55     Invoker.waitForOutstandingCallbacks (package:test_api/src/backend/invoker.dart:239:5)
#56     Declarer.test.<anonymous closure>.<anonymous closure> (package:test_api/src/backend/declarer.dart:169:33)
#61     Declarer.test.<anonymous closure> (package:test_api/src/backend/declarer.dart:168:13)
#62     Invoker._onRun.<anonymous closure>.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:test_api/src/backend/invoker.dart:392:25)
#76     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:384:19)
#77     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:418:5)
#78     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:174:12)
(elided 32 frames from class _FakeAsync, package dart:async, package dart:async-patch, and package stack_trace)

════════════════════════════════════════════════════════════════════════════════════════════════════
══╡ EXCEPTION CAUGHT BY FLUTTER TEST FRAMEWORK ╞════════════════════════════════════════════════════
The following TestFailure object was thrown running a test:
  No matching calls (actually, no calls at all).
(If you called `verify(...).called(0);`, please instead use `verifyNever(...);`.)

When the exception was thrown, this was the stack:
#0      fail (package:test_api/src/frontend/expect.dart:153:30)
#1      _VerifyCall._checkWith (package:mockito/src/mock.dart:648:7)
#2      _makeVerify.<anonymous closure> (package:mockito/src/mock.dart:935:18)
#3      buildWidget (file:///Users/derga002/Projects/flutter/nanny_share/nanny_share/test/test_helper.dart:54:9)
#17     AutomatedTestWidgetsFlutterBinding.runTest.<anonymous closure> (package:flutter_test/src/binding.dart:1066:17)
#19     AutomatedTestWidgetsFlutterBinding.runTest.<anonymous closure> (package:flutter_test/src/binding.dart:1054:35)
(elided 29 frames from class _FakeAsync, package dart:async, package dart:async-patch, and package stack_trace)

The test description was:
  CreateProfile .. NextButton -> CalendarScreen
════════════════════════════════════════════════════════════════════════════════════════════════════
══╡ EXCEPTION CAUGHT BY FLUTTER TEST FRAMEWORK ╞════════════════════════════════════════════════════
The following message was thrown:
Multiple exceptions (2) were detected during the running of the current test, and at least one was
unexpected.
════════════════════════════════════════════════════════════════════════════════════════════════════
00:02 +0 -1: CreateProfile .. NextButton -> CalendarScreen [E]                                                                                                     
  Test failed. See exception logs above.
  The test description was: CreateProfile .. NextButton -> CalendarScreen
  
00:02 +0 -1: Some tests failed.                                    
```

flutter doctor output:

```bash
~/Projects/flutter/nanny_share/nanny_share [fix_tests] $ flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, v1.12.13+hotfix.5, on Mac OS X 10.15.2 19C57, locale en-US)
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 11.3)
[✓] Android Studio (version 3.5)
[✓] IntelliJ IDEA Ultimate Edition (version 2019.2.4)
[✓] VS Code
[✓] Connected device (1 available)

• No issues found!
```

**Comment by iapicca** [comment]
Hi @belaad 
[provider](https://pub.dev/packages/provider) is without doubt an excellent package,
but it's a 3rd party package nevertheless.
You may want to open an issue in the dedicated [github](https://github.com/rrousselGit/provider/issues)

Closing, as this isn't an issue with Flutter itself,
if you disagree please write in the comments and I will reopen it
Thank you
