### ISSUE TITLE
NoSuchMethodError: null object does not have a getter 'context'.

### ISSUE THREAD

**Issue by mikejurka** [flutter/flutter#4863]
## Steps to Reproduce

Ran a flutter app on mojo.

Get an exception on startup (red screen with yellow text). The exception disappears when I rotate the orientation of the screen.

The app worked without any exceptions when using the version of flutter before https://github.com/flutter/flutter/commit/e071f0b

## Flutter Doctor

Paste the output of running `flutter doctor` here.
```
[✓] Flutter (on Mac OS, channel unknown)
    • Flutter at /Users/mikejurka/code/sysui/src/third_party/flutter
    • Framework revision e071f0bafd (3 weeks ago), engine revision c69d907b49

[✓] Android toolchain - develop for Android devices (Android SDK 23.0.3)
    • Android SDK at /Users/mikejurka/Library/Android/sdk
    • Platform android-23, build-tools 23.0.3
    • Java(TM) SE Runtime Environment (build 1.8.0_91-b14)

[✓] iOS toolchain - develop for iOS devices (Xcode 7.3.1)
    • XCode at /Applications/Xcode.app/Contents/Developer
    • Xcode 7.3.1, Build version 7D1014

[✓] Atom - a lightweight development environment for Flutter
    • flutter plugin version 0.2.3
    • dartlang plugin version 0.6.29
```

## Logs and Crash Reports

```
══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════

The following NoSuchMethodError was thrown building Title:

The null object does not have a getter 'context'.


NoSuchMethodError: method not found: 'context'
Receiver: null
Arguments: []



When the exception was thrown, this was the stack:

#0      Object._noSuchMethod (dart:core-patch/object_patch.dart:42)

#1      Object.noSuchMethod (dart:core-patch/object_patch.dart:45)

#2      ModalRoute.didPush (package:flutter/src/widgets/routes.dart:528)

#3      NavigatorState._push.<anonymous closure> (package:flutter/src/widgets/navigator.dart:392)
#4      State.setState (package:flutter/src/widgets/framework.dart:433)

#5      NavigatorState._push (package:flutter/src/widgets/navigator.dart:387)

#6      NavigatorState.initState (package:flutter/src/widgets/navigator.dart:325)

#7      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:1659)
#8      ComponentElement.mount (package:flutter/src/widgets/framework.dart:1551)

#9      Element.inflateWidget (package:flutter/src/widgets/framework.dart:1127)

#10     Element.updateChild (package:flutter/src/widgets/framework.dart:1004)

#11     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:1582)
#12     BuildableElement.rebuild (package:flutter/src/widgets/framework.dart:1484)
#13     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:1556)

#14     ComponentElement.mount (package:flutter/src/widgets/framework.dart:1551)

#15     Element.inflateWidget (package:flutter/src/widgets/framework.dart:1127)
#16     Element.updateChild (package:flutter/src/widgets/framework.dart:1004)
#17     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:1582)

#18     BuildableElement.rebuild (package:flutter/src/widgets/framework.dart:1484)

#19     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:1556)
#20     ComponentElement.mount (package:flutter/src/widgets/framework.dart:1551)

#21     Element.inflateWidget (package:flutter/src/widgets/framework.dart:1127)

#22     Element.updateChild (package:flutter/src/widgets/framework.dart:1004)
#23     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:1582)
#24     BuildableElement.rebuild (package:flutter/src/widgets/framework.dart:1484)
#25     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:1556)

#26     ComponentElement.mount (package:flutter/src/widgets/framework.dart:1551)

#27     Element.inflateWidget (package:flutter/src/widgets/framework.dart:1127)

#28     Element.updateChild (package:flutter/src/widgets/framework.dart:1004)
#29     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:1582)

#30     BuildableElement.rebuild (package:flutter/src/widgets/framework.dart:1484)

#31     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:1556)

#32     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:1673)

#33     ComponentElement.mount (package:flutter/src/widgets/framework.dart:1551)

#34     Element.inflateWidget (package:flutter/src/widgets/framework.dart:1127)

#35     Element.updateChild (package:flutter/src/widgets/framework.dart:1004)

#36     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:1582)
#37     BuildableElement.rebuild (package:flutter/src/widgets/framework.dart:1484)

#38     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:1556)

#39     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:1673)

#40     ComponentElement.mount (package:flutter/src/widgets/framework.dart:1551)

#41     Element.inflateWidget (package:flutter/src/widgets/framework.dart:1127)
#42     Element.updateChild (package:flutter/src/widgets/framework.dart:1004)

#43     RenderObjectToWidgetElement.mount (package:flutter/src/widgets/binding.dart:352)

#44     RenderObjectToWidgetAdapter.attachToRenderTree.<anonymous closure> (package:flutter/src/widgets/binding.dart:305)

#45     BuildOwner.lockState (package:flutter/src/widgets/framework.dart:794)
#46     RenderObjectToWidgetAdapter.attachToRenderTree (package:flutter/src/widgets/binding.dart:301)

#47     BindingBase&SchedulerBinding&GestureBinding&ServicesBinding&RendererBinding&WidgetsBinding._runApp (package:flutter/src/widgets/binding.dart:230)

#48     runApp (package:flutter/src/widgets/binding.dart:245)
#49     main.<main_async_body> (lib/main.dart:32)

(elided 3 frames from package dart:async)
```

> For more information about diagnosing and reporting Flutter bugs, please see [https://flutter.io/bug-reports/](https://flutter.io/bug-reports/).

**Comment by mikejurka** [comment]
When running in checked mode, I see the following message:
```
The following assertion was thrown building Title:

Unable to find the BuildContext for the Navigator's overlay.

Did you remember to pass the settings object to the route's constructor in your onGenerateRoute
callback?
```

**Comment by abarth** [comment]
Did you remember to pass the settings object to the route's constructor in your onGenerateRoute callback?

**Comment by mikejurka** [comment]
:-)

Looking into it, trying to grok the relevant code...

**Comment by mikejurka** [comment]
ok, i believe that fixes it. must have missed this change in a previous flutter sync.
