### ISSUE TITLE
Very weird error messages compiling simple apps

### ISSUE THREAD

**Issue by ctenov** [flutter/flutter#48655]
=====================================================
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, v1.12.13+hotfix.5, on Microsoft Windows [versÃ£o 10.0.18363.535], locale pt-BR)

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[√] Android Studio (version 3.5)
[√] Connected device (1 available)

• No issues found!
=====================================================
Hi, I have made this very simple app below to learn Flutter:

import 'package:flutter/material.dart';
import 'dart:math';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        backgroundColor: Colors.red,
        appBar: AppBar(
          title: Text('Dicee'),
          backgroundColor: Colors.red,
        ),
        body: DicePage(),
      ),
    );
  }
}

class DicePage extends StatefulWidget {
  @override
  _DicePageState createState() => _DicePageState();
}

class _DicePageState extends State<DicePage> {
  int leftDiceNumber = 1;
  int rightDiceNumber = 1;

  @override
  Widget build(BuildContext context) {
    return Center(
      child: Row(
        children: <Widget>[
          Expanded(
            child: FlatButton(
              onPressed: () {
                changeDice();
              },
              child: Image.asset('images/dice$leftDiceNumber.png'),
            ),
          ),
          Expanded(
            child: FlatButton(
              onPressed: () {
                changeDice();
              },
              child: Image.asset('images/dice$rightDiceNumber.png'),
            ),
          ),
        ],
      ),
    );
  }

  void changeDice() {
    setState(() {
      leftDiceNumber = Random().nextInt(6) + 1;
      rightDiceNumber = Random().nextInt(6) + 1;
    });
  }
}

==========================================
then when I compile it a lot or error messages appear:

Launching lib\main.dart on Android SDK built for x86 in debug mode...
Running Gradle task 'assembleDebug'...
I/flutter ( 8056): ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
I/flutter ( 8056): The following assertion was thrown building DicePage(dirty):
I/flutter ( 8056): 'package:flutter/src/widgets/basic.dart': Failed assertion: line 3786 pos 15: 'direction != null':
I/flutter ( 8056): is not true.
I/flutter ( 8056): 
I/flutter ( 8056): Either the assertion indicates an error in the framework itself, or we should provide substantially
I/flutter ( 8056): more information in this error message to help you determine and fix the underlying cause.
I/flutter ( 8056): In either case, please report this assertion by filing a bug on GitHub:
I/flutter ( 8056):   https://github.com/flutter/flutter/issues/new?template=BUG.md
I/flutter ( 8056): 
I/flutter ( 8056): The relevant error-causing widget was:
I/flutter ( 8056):   DicePage file:///C:/Dados/Android/Projetos/dice/lib/main.dart:16:15
I/flutter ( 8056): 
I/flutter ( 8056): When the exception was thrown, this was the stack:
I/flutter ( 8056): #2      new Flex (package:flutter/src/widgets/basic.dart:3786:15)
I/flutter ( 8056): #3      DicePage.build (package:dice/main.dart:28:14)
I/flutter ( 8056): #4      StatelessElement.build (package:flutter/src/widgets/framework.dart:4291:28)
I/flutter ( 8056): #5      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4223:15)
I/flutter ( 8056): #6      Element.rebuild (package:flutter/src/widgets/framework.dart:3947:5)
I/flutter ( 8056): #7      ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4206:5)
I/flutter ( 8056): #8      ComponentElement.mount (package:flutter/src/widgets/framework.dart:4201:5)
I/flutter ( 8056): #9      Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194:14)
I/flutter ( 8056): #10     Element.updateChild (package:flutter/src/widgets/framework.dart:2988:12)
I/flutter ( 8056): #11     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4243:16)
I/flutter ( 8056): #12     Element.rebuild (package:flutter/src/widgets/framework.dart:3947:5)
I/flutter ( 8056): #13     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4206:5)
I/flutter ( 8056): #14     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4201:5)
I/flutter ( 8056): #15     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194:14)
I/flutter ( 8056): #16     Element.updateChild (package:flutter/src/widgets/framework.dart:2988:12)
I/flutter ( 8056): #17     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4243:16)
I/flutter ( 8056): #18     Element.rebuild (package:flutter/src/widgets/framework.dart:3947:5)
I/flutter ( 8056): #19     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4206:5)
I/flutter ( 8056): #20     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4201:5)

=== SEVERAL OMMITTED LINES ===

I/flutter ( 8759): The following assertion was thrown during layout:
I/flutter ( 8759): A RenderFlex overflowed by 133 pixels on the right.
I/flutter ( 8759): 
I/flutter ( 8759): The relevant error-causing widget was:
I/flutter ( 8759):   Row file:///C:/Dados/Android/Projetos/dice/lib/main.dart:34:14
I/flutter ( 8759): 
I/flutter ( 8759): The overflowing RenderFlex has an orientation of Axis.horizontal.
I/flutter ( 8759): The edge of the RenderFlex that is overflowing has been marked in the rendering with a yellow and
I/flutter ( 8759): black striped pattern. This is usually caused by the contents being too big for the RenderFlex.
I/flutter ( 8759): Consider applying a flex factor (e.g. using an Expanded widget) to force the children of the
I/flutter ( 8759): RenderFlex to fit within the available space instead of being sized to their natural size.
I/flutter ( 8759): This is considered an error condition because it indicates that there is content that cannot be
I/flutter ( 8759): seen. If the content is legitimately bigger than the available space, consider clipping it with a
I/flutter ( 8759): ClipRect widget before putting it in the flex, or using a scrollable container rather than a Flex,
I/flutter ( 8759): like a ListView.
I/flutter ( 8759): The specific RenderFlex in question is: RenderFlex#85aac relayoutBoundary=up2 OVERFLOWING:
I/flutter ( 8759):   creator: Row ← Center ← DicePage ← _BodyBuilder ← MediaQuery ← LayoutId-[<_ScaffoldSlot.body>] ←
I/flutter ( 8759):     CustomMultiChildLayout ← AnimatedBuilder ← DefaultTextStyle ← AnimatedDefaultTextStyle ←
I/flutter ( 8759):     _InkFeatures-[GlobalKey#0dcbd ink renderer] ← NotificationListener<LayoutChangedNotification> ← ⋯
I/flutter ( 8759):   parentData: offset=Offset(0.0, 45.7) (can use size)
I/flutter ( 8759):   constraints: BoxConstraints(0.0<=w<=411.4, 0.0<=h<=603.4)
I/flutter ( 8759):   size: Size(411.4, 512.0)
I/flutter ( 8759):   direction: horizontal
I/flutter ( 8759):   mainAxisAlignment: start
I/flutter ( 8759):   mainAxisSize: max
I/flutter ( 8759):   crossAxisAlignment: center
I/flutter ( 8759):   textDirection: ltr
I/flutter ( 8759):   verticalDirection: down
I/flutter ( 8759): 

--------------------
I/flutter ( 8971): The following assertion was thrown building DicePage(state: _DicePageState#e0b87):
I/flutter ( 8971): Incorrect use of ParentDataWidget.
I/flutter ( 8971): Flexible widgets must be placed inside Flex widgets.
I/flutter ( 8971): Flexible(no depth, flex: 1, dirty) has no Flex ancestor at all.
I/flutter ( 8971): The ownership chain for the parent of the offending Flexible was:
I/flutter ( 8971):   Center ← DicePage ← _BodyBuilder ← MediaQuery ← LayoutId-[<_ScaffoldSlot.body>] ←
I/flutter ( 8971): CustomMultiChildLayout ← AnimatedBuilder ← DefaultTextStyle ← AnimatedDefaultTextStyle ←
I/flutter ( 8971): _InkFeatures-[GlobalKey#c11fc ink renderer] ← ⋯
I/flutter ( 8971): 
I/flutter ( 8971): The relevant error-causing widget was:
I/flutter ( 8971):   DicePage file:///C:/Dados/Android/Projetos/dice/lib/main.dart:16:15
I/flutter ( 8971): 
I/flutter ( 8971): When the exception was thrown, this was the stack:
I/flutter ( 8971): #0      ParentDataElement.mount.<anonymous closure> (package:flutter/src/widgets/framework.dart:4606:7)
I/flutter ( 8971): #1      ParentDataElement.mount (package:flutter/src/widgets/framework.dart:4616:6)
I/flutter ( 8971): #2      Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194:14)
I/flutter ( 8971): #3      Element.updateChild (package:flutter/src/widgets/framework.dart:2988:12)
I/flutter ( 8971): #4      SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5445:14)
I/flutter ( 8971): #5      Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194:14)
I/flutter ( 8971): #6      Element.updateChild (package:flutter/src/widgets/framework.dart:2988:12)
I/flutter ( 8971): #7      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4243:16)
I/flutter ( 8971): #8      Element.rebuild (package:flutter/src/widgets/framework.dart:3947:5)
I/flutter ( 8971): #9      ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4206:5)
I/flutter ( 8971): #10     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4381:11)
I/flutter ( 8971): #11     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4201:5)
I/flutter ( 8971): #12     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194:14)
I/flutter ( 8971): #13     Element.updateChild (package:flutter/src/widgets/framework.dart:2988:12)
I/flutter ( 8971): #14     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4243:16)
I/flutter ( 8971): #15     Element.rebuild (package:flutter/src/widgets/framework.dart:3947:5)
I/flutter ( 8971): #16     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4206:5)
I/flutter ( 8971): #17     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4201:5)
I/flutter ( 8971): #18     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194:14)
I/flutter ( 8971): #19     Element.updateChild (package:flutter/src/widgets/framework.dart:2988:12)
I/flutter ( 8971): #20     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4243:16)
I/flutter ( 8971): #21     Element.rebuild (package:flutter/src/widgets/framework.dart:3947:5)
I/flutter ( 8971): #22     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4206:5)
I/flutter ( 8971): #23     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4201:5)
I/flutter ( 8971): #24     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194:14)
I/flutter ( 8971): #25     Element.updateChild (package:flutter/src/widgets/framework.dart:2988:12)
I/flutter ( 8971): #26     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4243:16)
I/flutter ( 8971): #27     Element.rebuild (package:flutter/src/widgets/framework.dart:3947:5)
I/flutter ( 8971): #28     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4206:5)
I/flutter ( 8971): #29     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4201:5)
I/flutter ( 8971): #30     ParentDataElement.mount (package:flutter/src/widgets/framework.dart:4617:11)

=== SEVERAL OMMITED LINES ===

I/flutter ( 8971): Another exception was thrown: Each child must be laid out exactly once.
√ Built build\app\outputs\apk\debug\app-debug.apk.
Installing build\app\outputs\apk\app.apk...
Syncing files to device Android SDK built for x86...

=============================================================
But most weird is that if I create a very new Flutter App and accepts the Flutter Sample Code that is in main.dart without ANY changes the compilation of this brand new App shows THE SAME messages, including the reference to 'dice' project that I have closed to start this new one...

Other relevante details:
- Although compilation errors the process is very sucessfull and the behavior of app is nice without any issues (Dice and Sample Code are both ok)
- I have made Flutter clean several times. No changes...
- I have checked the file 'basic.dart' to see if Flex class have any typos and I have seen nothing.

Many thanks for your help !

**Comment by ctenov** [comment]
Moving on my studies of Flutter I realized that messages I printed on console are persisting too !!!
Then I found this issue: https://github.com/flutter/flutter/issues/34876 and follow the advice here:
'For Android Studio:
Tools -> AVD Manager -> Emulator actions -> wipe data'
The old logs vanish like a charm !!!
Thanks !
