### ISSUE TITLE
ScrollController attached to multiple scroll views.

### ISSUE THREAD

**Issue by victoriest** [flutter/flutter#48668]
## Steps to Reproduce

**Environment**:
```console
Flutter (Channel beta, v1.12.13+hotfix.6, on Microsoft Windows [Version 10.0.18362.535], locale zh-CN)
    • Flutter version 1.12.13+hotfix.6 at E:\_IDEs\apps\FlutterSDK\flutter
    • Framework revision 18cd7a3601 (4 weeks ago), 2019-12-11 06:35:39 -0800
    • Engine revision 2994f7e1e6
    • Dart version 2.7.0
```

I create a TabBarView contains multi ScrollView(7 in this sample).  I switch the index of TabBarView to 6 or 5 then get the offset of ScrollView (`_scrollController.offset`, onTapUp in this sample ). An exception occur:

<details>
	<summary>logs</summary>

```bash
════════ Exception caught by gesture ═══════════════════════════════════════════════════════════════
The following assertion was thrown while handling a gesture:
ScrollController attached to multiple scroll views.
'package:flutter/src/widgets/scroll_controller.dart':
Failed assertion: line 111 pos 12: '_positions.length == 1'


Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=BUG.md

When the exception was thrown, this was the stack: 
#2      ScrollController.position (package:flutter/src/widgets/scroll_controller.dart:111:12)
#3      ScrollController.offset (package:flutter/src/widgets/scroll_controller.dart:118:24)
#4      _BugTesterState.build.<anonymous closure> (package:timeline_flutter/main.dart:68:61)
#5      TapGestureRecognizer.handleTapUp.<anonymous closure> (package:flutter/src/gestures/tap.dart:484:49)
#6      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:182:24)
...
Handler: "onTapUp"
Recognizer: TapGestureRecognizer#9179c
  debugOwner: GestureDetector
  state: ready
  won arena
  finalPosition: Offset(215.6, 241.5)
  finalLocalPosition: Offset(215.6, 113.5)
  button: 1
  sent tap down
════════════════════════════════════════════════════════════════════════════════════════════════════
```

</details>

<details>
	<summary>sample app</summary>

```dart
import 'package:flutter/material.dart';
import 'global.dart';

void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  Global.init().then((e) {
    print("main after init global");
    runApp(TimelineApp());
  });
}

class TimelineApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Timeline Demo',
      home: BugTesterWidget(),
    );
  }
}

class BugTesterWidget extends StatefulWidget {
  @override
  _BugTesterState createState() => _BugTesterState();
}

class _BugTesterState extends State<BugTesterWidget>
    with SingleTickerProviderStateMixin {
  TabController _tabController;

  ScrollController _scrollController;

  @override
  void initState() {
    super.initState();
    _tabController = new TabController(vsync: this, length: 7, initialIndex: 0);
    _scrollController = new ScrollController(
    );
  }

  @override
  Widget build(BuildContext context) {
    List<Widget> timeLines = [];
    List<Widget> tabs = [];
    for (int i = 0; i < 7; i++) {
      var item = Tab(
          child: Column(children: <Widget>[
        Text("${i + 1}"),
      ]));
      tabs.add(item);
      SingleChildScrollView _timeLine = SingleChildScrollView(
        controller: _scrollController,
      );
      timeLines.add(_timeLine);
    }

    TabBarView tabBarView = TabBarView(
      children: timeLines,
      controller: _tabController,
    );

    Expanded gestureDetector = Expanded(
        child: GestureDetector(
      child: tabBarView,
      onTapUp: (TapUpDetails details) {
        print("${_tabController.index}, ${_scrollController.offset}");
      },
    ));

    var center = Scaffold(
      resizeToAvoidBottomInset: false,
      appBar: AppBar(
        title: Text("Test"),
        bottom: new TabBar(
          tabs: tabs,
          controller: _tabController,
        ),
      ),
      body: Column(
        children: <Widget>[
          gestureDetector,
        ],
      ),
    );

    return center;
  }
}

```

</details>

**Comment by VladyslavBondarenko** [comment]
@victoriest 
See the solution here https://stackoverflow.com/questions/53824944/flutter-exception-scrollcontroller-attached-to-multiple-scroll-views

<details>
 <summary>edited code sample</summary>

```
import 'package:flutter/material.dart';

void main() async {
    runApp(TimelineApp());
}

class TimelineApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Timeline Demo',
      home: BugTesterWidget(),
    );
  }
}

class BugTesterWidget extends StatefulWidget {
  @override
  _BugTesterState createState() => _BugTesterState();
}

class _BugTesterState extends State<BugTesterWidget>
    with SingleTickerProviderStateMixin {
  TabController _tabController;

  ScrollController _scrollController;
  double offset = 0.0 ;

  @override
  void initState() {
    super.initState();
    _tabController = new TabController(vsync: this, length: 7, initialIndex: 0);
    _scrollController = ScrollController() //keepScrollOffset: false removed
      ..addListener(() {
        setState(() {
          //<-----------------------------
          offset = _scrollController.offset;
          // force a refresh so the app bar can be updated
        });
      });
  }

  @override
  Widget build(BuildContext context) {
    List<Widget> timeLines = [];
    List<Widget> tabs = [];
    for (int i = 0; i < 7; i++) {
      var item = Tab(
          child: Column(children: <Widget>[
            Text("${i + 1}"),
          ]));
      tabs.add(item);
      SingleChildScrollView _timeLine = SingleChildScrollView(
        controller: _scrollController,
      );
      timeLines.add(_timeLine);
    }

    TabBarView tabBarView = TabBarView(
      children: timeLines,
      controller: _tabController,
    );

    Expanded gestureDetector = Expanded(
        child: GestureDetector(
          child: tabBarView,
          onTapUp: (TapUpDetails details) {
            print("${_tabController.index}, ${_scrollController.offset}");
          },
        ));

    var center = Scaffold(
      resizeToAvoidBottomInset: false,
      appBar: AppBar(
        title: Text("Test"),
        bottom: new TabBar(
          tabs: tabs,
          controller: _tabController,
        ),
      ),
      body: Column(
        children: <Widget>[
          gestureDetector,
        ],
      ),
    );

    return center;
  }
}
```

</details>

Closing as solved,
If you disagree please write in the comments and I will reopen it.
Thank you
