### ISSUE TITLE
Android Alarm Manager error

### ISSUE THREAD

**Issue by iso57** [flutter/flutter#48689]
Flutter doctor

```
[√] Flutter (Channel unknown, v1.13.2-pre.7, on Microsoft Windows [version 10.0.18362.535], locale
    fr-FR)

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[√] Chrome - develop for the web
[√] Visual Studio - develop for Windows (Visual Studio Professional 2017 15.9.18)
[√] Android Studio (version 3.4)
[√] IntelliJ IDEA Ultimate Edition (version 2018.3)
[√] VS Code (version 1.41.1)
[√] Connected device (3 available)

• No issues found!
```

(Channel master)

```
I/FlutterBackgroundExecutor(13665): Starting AlarmService...
W/FlutterEngine(13665): Tried to automatically register plugins with FlutterEngine (io.flutter.embedding.engine.FlutterEngine@f0a4ad9) but could not find and invoke the GeneratedPluginRegistrant.
E/MethodChannel#plugins.flutter.io/android_alarm_manager(13665): Failed to handle method call
E/MethodChannel#plugins.flutter.io/android_alarm_manager(13665): java.lang.NullPointerException: Attempt to invoke virtual method 'android.app.Application android.app.Activity.getApplication()' on a null object reference
E/MethodChannel#plugins.flutter.io/android_alarm_manager(13665): 	at com.github.adee42.keyboardvisibility.KeyboardVisibilityPlugin.registerWith(KeyboardVisibilityPlugin.java:107)
E/MethodChannel#plugins.flutter.io/android_alarm_manager(13665): 	at io.flutter.plugins.GeneratedPluginRegistrant.registerWith(GeneratedPluginRegistrant.java:46)
E/MethodChannel#plugins.flutter.io/android_alarm_manager(13665): 	at fr.****.****.Application.registerWith(Application.java:18)
E/MethodChannel#plugins.flutter.io/android_alarm_manager(13665): 	at io.flutter.plugins.androidalarmmanager.FlutterBackgroundExecutor.startBackgroundIsolate(FlutterBackgroundExecutor.java:179)
E/MethodChannel#plugins.flutter.io/android_alarm_manager(13665): 	at io.flutter.plugins.androidalarmmanager.AlarmService.startBackgroundIsolate(AlarmService.java:64)
E/MethodChannel#plugins.flutter.io/android_alarm_manager(13665): 	at io.flutter.plugins.androidalarmmanager.AndroidAlarmManagerPlugin.onMethodCall(AndroidAlarmManagerPlugin.java:120)
E/MethodChannel#plugins.flutter.io/android_alarm_manager(13665): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:231)
E/MethodChannel#plugins.flutter.io/android_alarm_manager(13665): 	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:93)
E/MethodChannel#plugins.flutter.io/android_alarm_manager(13665): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:642)
E/MethodChannel#plugins.flutter.io/android_alarm_manager(13665): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/MethodChannel#plugins.flutter.io/android_alarm_manager(13665): 	at android.os.MessageQueue.next(MessageQueue.java:336)
E/MethodChannel#plugins.flutter.io/android_alarm_manager(13665): 	at android.os.Looper.loop(Looper.java:178)
E/MethodChannel#plugins.flutter.io/android_alarm_manager(13665): 	at android.app.ActivityThread.main(ActivityThread.java:7520)
E/MethodChannel#plugins.flutter.io/android_alarm_manager(13665): 	at java.lang.reflect.Method.invoke(Native Method)
E/MethodChannel#plugins.flutter.io/android_alarm_manager(13665): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
E/MethodChannel#plugins.flutter.io/android_alarm_manager(13665): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)
E/flutter (13665): [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: PlatformException(error, Attempt to invoke virtual method 'android.app.Application android.app.Activity.getApplication()' on a null object reference, null)
E/flutter (13665): #0      JSONMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:149:7)
E/flutter (13665): #1      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:321:33)
E/flutter (13665): <asynchronous suspension>
E/flutter (13665): #2      AndroidAlarmManager.initialize (package:android_alarm_manager/android_alarm_manager.dart:96:35)
E/flutter (13665): #3      main (package:***/main.dart:49:29)
E/flutter (13665): #4      _AsyncAwaitCompleter.start (dart:async-patch/async_patch.dart:46:6)
E/flutter (13665): #5      main (package:***/main.dart:46:18)
E/flutter (13665): #6      _runMainZoned.<anonymous closure>.<anonymous closure> (dart:ui/hooks.dart:239:25)
E/flutter (13665): #7      _rootRun (dart:async/zone.dart:1126:13)
E/flutter (13665): #8      _CustomZone.run (dart:async/zone.dart:1023:19)
E/flutter (13665): #9      _runZoned (dart:async/zone.dart:1518:10)
E/flutter (13665): #10     runZoned (dart:async/zone.dart:1502:12)
E/flutter (13665): #11     _runMainZoned.<anonymous closure> (dart:ui/hooks.dart:231:5)
E/flutter (13665): #12     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:307:19)
E/flutter (13665): #13     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:174:12)
E/flutter (13665): 
E/flutter (13665): [ERROR:flutter/shell/common/shell.cc(199)] Dart Error: Dart_LookupLibrary: library 'package:android_alarm_manager/android_alarm_manager.dart' not found.
E/flutter (13665): [ERROR:flutter/runtime/dart_isolate.cc(461)] Could not resolve main entrypoint function.
E/flutter (13665): [ERROR:flutter/shell/common/engine.cc(212)] Could not run the isolate.
E/flutter (13665): [ERROR:flutter/shell/common/engine.cc(137)] Engine not prepare and launch isolate.
E/flutter (13665): [ERROR:flutter/shell/common/shell.cc(437)] Could not launch engine with configuration.
```

**Comment by VladyslavBondarenko** [comment]
Hi @iso57 ,
To better address this issue, could you explain how to reproduce it?
Thank you

**Comment by iapicca** [comment]
Hi @iso57 
I see you are using an older version of `master`,
even the latest `dev` is more up-to-date
you may want to consider running
`flutter channel dev` or `flutter channel master` 
`flutter upgrade --force`
`flutter pub cache repair`
`cd <YOUR APP FOLDER>`
`flutter clean`

If the issue persist please provide your updated 
`flutter doctor -v` and `flutter run --verbose`
together with a reproducible minimal code sample
thank you

**Comment by dkobia** [comment]
@iso57 was this an older project that got upgraded to +v1.12? If so, have you looked at this? https://github.com/flutter/flutter/wiki/Upgrading-pre-1.12-Android-projects

**Comment by iapicca** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact descriptions what happens, logs and the output of 'flutter doctor -v'  please.
All system setups can be slightly different so it's always better to open new issues and reference related issues.
