### ISSUE TITLE
Execution failed for task ':app:transformClassesWithDexBuilderForDebug'

### ISSUE THREAD

**Issue by komputerboy** [flutter/flutter#48694]
## Steps to Reproduce 

1. Create new project
2. Run it (F5) to my smartphone device

This is my Error:

```bash
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:transformClassesWithDexBuilderForDebug'.
> java.lang.StackOverflowError (no error message)

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 6m 45s
Gradle task assembleDebug failed with exit code 1
Exited (sigterm)
```

<details>
  <summary>Logs</summary>

```bash
[  +92 ms] executing: [C:\Android\flutter\] git -c log.showSignature=false log -n 1 --pretty=format:%H
[ +141 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[   +4 ms] 27321ebbad34b0a3fafe99fac037102196d655ff
[   +1 ms] executing: [C:\Android\flutter\] git describe --match v*.*.* --first-parent --long --tags
[  +55 ms] Exit code 0 from: git describe --match v*.*.* --first-parent --long --tags
[        ] v1.12.13+hotfix.5-0-g27321ebba
[  +21 ms] executing: [C:\Android\flutter\] git rev-parse --abbrev-ref --symbolic @{u}
[  +58 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/stable
[        ] executing: [C:\Android\flutter\] git ls-remote --get-url origin
[  +67 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[ +231 ms] executing: [C:\Android\flutter\] git rev-parse --abbrev-ref HEAD
[ +106 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] stable
[ +429 ms] executing: C:\Android\platform-tools\adb.exe devices -l
[ +109 ms] Exit code 0 from: C:\Android\platform-tools\adb.exe devices -l
[        ] List of devices attached
           a96a6a717d93           device product:santoni model:Redmi_4X device:santoni transport_id:1
[  +52 ms] C:\Android\platform-tools\adb.exe -s a96a6a717d93 shell getprop
[ +216 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[  +51 ms] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +9 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[ +661 ms] Generating
C:\Users\Samsung\Documents\flutter\tes\android\app\src\main\java\io\flutter\plugins\GeneratedPluginRegistrant.java
[  +99 ms] ro.hardware = qcom
[ +306 ms] Launching lib\main.dart on Redmi 4X in debug mode...
[  +38 ms] executing: C:\Android\platform-tools\adb.exe -s a96a6a717d93 shell -x logcat -v time -s flutter
[  +57 ms] executing: C:\Android\platform-tools\adb.exe version
[ +157 ms] Android Debug Bridge version 1.0.41
           Version 29.0.5-5949299
           Installed as C:\Android\platform-tools\adb.exe
[  +14 ms] executing: C:\Android\platform-tools\adb.exe start-server
[ +141 ms] Building APK
[ +101 ms] Running Gradle task 'assembleDebug'...
[   +5 ms] gradle.properties already sets `android.enableR8`
[  +20 ms] Using gradle from C:\Users\Samsung\Documents\flutter\tes\android\gradlew.bat.
[  +18 ms] executing: [C:\Users\Samsung\Documents\flutter\tes\android\]
C:\Users\Samsung\Documents\flutter\tes\android\gradlew.bat -Pverbose=true
-Ptarget=C:\Users\Samsung\Documents\flutter\tes\lib\main.dart -Ptrack-widget-creation=true -Pfilesystem-scheme=org-dartlang-root
-Ptarget-platform=android-arm64 assembleDebug
[+2256 ms] Welcome to Gradle 5.6.2!
[        ] Here are the highlights of this release:
[        ]  - Incremental Groovy compilation
[        ]  - Groovy compile avoidance
[        ]  - Test fixtures for Java projects
[        ]  - Manage plugin versions via settings script
[        ] For more details see https://docs.gradle.org/5.6.2/release-notes.html
[+12550 ms] > Task :app:compileFlutterBuildDebug
[   +6 ms] [  +88 ms] executing: [C:\Android\flutter\] git -c log.showSignature=false log -n 1 --pretty=format:%H
[ +263 ms] [ +416 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[        ] [   +4 ms] 27321ebbad34b0a3fafe99fac037102196d655ff
[        ] [   +1 ms] executing: [C:\Android\flutter\] git describe --match v*.*.* --first-parent --long --tags
[ +110 ms] [  +67 ms] Exit code 0 from: git describe --match v*.*.* --first-parent --long --tags
[        ] [   +1 ms] v1.12.13+hotfix.5-0-g27321ebba
[        ] [  +22 ms] executing: [C:\Android\flutter\] git rev-parse --abbrev-ref --symbolic @{u}
[ +106 ms] [  +68 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[   +1 ms] [   +1 ms] origin/stable
[   +3 ms] [   +1 ms] executing: [C:\Android\flutter\] git ls-remote --get-url origin
[ +224 ms] [ +199 ms] Exit code 0 from: git ls-remote --get-url origin
[   +1 ms] [   +1 ms] https://github.com/flutter/flutter.git
[ +167 ms] [ +233 ms] executing: [C:\Android\flutter\] git rev-parse --abbrev-ref HEAD
[ +185 ms] [ +232 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[   +1 ms] [   +2 ms] stable
[ +240 ms] [ +100 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[   +5 ms] [   +5 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] [   +1 ms] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] [   +1 ms] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] [   +1 ms] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[        ] [  +12 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] [  +28 ms] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] [   +1 ms] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] [   +1 ms] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] [   +1 ms] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] [   +1 ms] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[ +264 ms] [ +344 ms] Initializing file store
[ +219 ms] [ +132 ms] Done initializing file store
[+4654 ms] [+4752 ms] Skipping target: kernel_snapshot
[ +200 ms] [ +204 ms] debug_android_application: Starting due to {InvalidatedReason.outputMissing}
[ +399 ms] [ +432 ms] debug_android_application: Complete
[ +119 ms] [  +62 ms] Persisting file store
[   +1 ms] [  +33 ms] Done persisting file store
[  +82 ms] [  +29 ms] build succeeded.
[        ] [  +44 ms] "flutter assemble" took 6,414ms.
[ +305 ms] > Task :app:packLibsflutterBuildDebug UP-TO-DATE
[+1520 ms] > Task :app:preBuild UP-TO-DATE
[   +1 ms] > Task :app:preDebugBuild UP-TO-DATE
[        ] > Task :app:compileDebugAidl NO-SOURCE
[        ] > Task :app:compileDebugRenderscript NO-SOURCE
[        ] > Task :app:checkDebugManifest UP-TO-DATE
[        ] > Task :app:generateDebugBuildConfig UP-TO-DATE
[        ] > Task :app:cleanMergeDebugAssets
[        ] > Task :app:mergeDebugShaders UP-TO-DATE
[        ] > Task :app:compileDebugShaders UP-TO-DATE
[        ] > Task :app:generateDebugAssets UP-TO-DATE
[        ] > Task :app:mergeDebugAssets
[        ] > Task :app:copyFlutterAssetsDebug
[        ] > Task :app:mainApkListPersistenceDebug UP-TO-DATE
[+1916 ms] > Task :app:generateDebugResValues UP-TO-DATE
[   +2 ms] > Task :app:generateDebugResources UP-TO-DATE
[        ] > Task :app:mergeDebugResources UP-TO-DATE
[        ] > Task :app:createDebugCompatibleScreenManifests UP-TO-DATE
[        ] > Task :app:processDebugManifest UP-TO-DATE
[        ] > Task :app:processDebugResources UP-TO-DATE
[        ] > Task :app:compileDebugKotlin UP-TO-DATE
[        ] > Task :app:javaPreCompileDebug UP-TO-DATE
[  +32 ms] > Task :app:compileDebugJavaWithJavac UP-TO-DATE
[        ] > Task :app:compileDebugSources UP-TO-DATE
[        ] > Task :app:processDebugJavaRes NO-SOURCE
[        ] > Task :app:mergeDebugJavaResource UP-TO-DATE
[+33281 ms] FAILURE: Build failed with an exception.
[  +24 ms] * What went wrong:
[        ] Could not dispatch a message to the daemon.
[  +39 ms] * Try:
[        ] Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run
with --scan to get full insights.
[   +2 ms] * Get more help at https://help.gradle.org
[ +206 ms] Running Gradle task 'assembleDebug'... (completed in 59.4s)
[  +48 ms] "flutter run" took 62,099ms.
Gradle task assembleDebug failed with exit code 1

#0      throwToolExit (package:flutter_tools/src/base/common.dart:28:3)
#1      buildGradleApp (package:flutter_tools/src/android/gradle.dart:387:7)
#2      _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:73:64)
#3      _rootRunUnary (dart:async/zone.dart:1134:38)
#4      _CustomZone.runUnary (dart:async/zone.dart:1031:19)
#5      _FutureListener.handleValue (dart:async/future_impl.dart:139:18)
#6      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:680:45)
#7      Future._propagateToListeners (dart:async/future_impl.dart:709:32)
#8      Future._completeWithValue (dart:async/future_impl.dart:524:5)
#9      _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:32:15)
#10     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:290:13)
#11     _DefaultProcessUtils.stream (package:flutter_tools/src/base/process.dart)
#12     _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:73:64)
#13     _rootRunUnary (dart:async/zone.dart:1134:38)
#14     _CustomZone.runUnary (dart:async/zone.dart:1031:19)
#15     _FutureListener.handleValue (dart:async/future_impl.dart:139:18)
#16     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:680:45)
#17     Future._propagateToListeners (dart:async/future_impl.dart:709:32)
#18     Future._completeWithValue (dart:async/future_impl.dart:524:5)
#19     Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:554:7)
#20     _rootRun (dart:async/zone.dart:1126:13)
#21     _CustomZone.run (dart:async/zone.dart:1023:19)
#22     _CustomZone.runGuarded (dart:async/zone.dart:925:7)
#23     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:965:23)
#24     _microtaskLoop (dart:async/schedule_microtask.dart:43:21)
#25     _startMicrotaskLoop (dart:async/schedule_microtask.dart:52:5)
#26     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
#27     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:175:5)
```

</details>

```bash
Analyzing tes...
No issues found! (ran in 7.9s)
```

```console
[√] Flutter (Channel stable, v1.12.13+hotfix.5, on Microsoft Windows [Version 6.1.7601], locale en-US)
    • Flutter version 1.12.13+hotfix.5 at C:\Android\flutter
    • Framework revision 27321ebbad (5 weeks ago), 2019-12-10 18:15:01 -0800
    • Engine revision 2994f7e1e6
    • Dart version 2.7.0

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at C:\Android
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • ANDROID_HOME = C:\Android
    • ANDROID_SDK_ROOT = C:\Android\sdk
    • Java binary at: C:\Android\openjdk\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_232-b09)
    • All Android licenses accepted.

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/setup/#android-setup for detailed instructions).

[√] VS Code (version 1.41.1)
    • VS Code at C:\Users\Samsung\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.7.1

[√] Connected device (1 available)
    • Redmi 4X • a96a6a717d93 • android-arm64 • Android 6.0.1 (API 23)
```

**Comment by jonahwilliams** [comment]
I found some tidbits in https://stackoverflow.com/questions/34940056/could-not-dispatch-a-message-to-the-daemon , but I'm not sure whether that will help here.


Is this a persistent issue, or was it a one-off?

**Comment by komputerboy** [comment]
I try to use `gradle --stop && gradle clean build` in terminal, and then i got this:

```
Stopping Daemon(s)
1 Daemon stopped
Starting a Gradle Daemon, 1 stopped Daemon could not be reused, use --status for details

FAILURE: Build failed with an exception.

* What went wrong:
Task 'clean' not found in root project 'hello'.

* Try:
Run gradle tasks to get a list of available tasks. Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 11s
<-------------> 0% WAITING
> IDLE

```

**Comment by komputerboy** [comment]
Okay, now my problem is solved.

I just download gradle 5.6.2 then add it to my environment variables
