### ISSUE TITLE
New project with 'image_picker' and 'flutter_native_web' plugins give error ''Minimum supported Gradle version is 5.4.1. Current version is 4.10.2." when running `flutter build apk`

### ISSUE THREAD

**Issue by Dancovich** [flutter/flutter#48724]
When creating a new flutter project with `flutter create` (Flutter 1.12.13+hotfix.5 on channel stable), editing pubspec.yaml to add dependencies to `flutter_native_web: ^1.0.3` and `image_picker: ^0.6.3` (and running `flutter pub get` to update the dependencies) and running `flutter build apk` the build fails with the following error:

```
FAILURE: Build failed with an exception.

* Where:
Build file '/home/81986912515/Desenvolvimento/Ferramentas/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_plugin_android_lifecycle-1.0.3/android/build.gradle' line: 22

* What went wrong:
A problem occurred evaluating root project 'flutter_plugin_android_lifecycle'.
> Failed to apply plugin [id 'com.android.library']
   > Minimum supported Gradle version is 5.4.1. Current version is 4.10.2. If using the gradle wrapper, try editing the distributionUrl in /home/81986912515/Desenvolvimento/Ferramentas/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_plugin_android_lifecycle-1.0.3/android/gradle/wrapper/gradle-wrapper.properties to gradle-5.4.1-all.zip

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 0s


The plugin flutter_plugin_android_lifecycle could not be built due to the issue above.
```

This issue is based on #42082 and gives an example of this bug still happening in a specific project configuration.

**STEPS TO REPRODUCE**

- Create a new project with `flutter create a_new_project`
- Edit pubspec.yaml to add dependencies to `flutter_native_web: ^1.0.3` and `image_picker: ^0.6.3`
- Run `flutter pub get`
- Run `flutter build apk`
- Build will fail
- Remove any of the two dependencies above and run `flutter pub get` again
- Build now succeeds

Here's a sample project with the issue happening: https://github.com/Dancovich/gradle_error_sample

Here's the result of flutter doctor
```
flutter doctor -v
[✓] Flutter (Channel stable, v1.12.13+hotfix.5, on Linux, locale pt_BR.UTF-8)
    • Flutter version 1.12.13+hotfix.5 at /home/81986912515/Desenvolvimento/Ferramentas/flutter
    • Framework revision 27321ebbad (5 weeks ago), 2019-12-10 18:15:01 -0800
    • Engine revision 2994f7e1e6
    • Dart version 2.7.0

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /home/81986912515/Desenvolvimento/Ferramentas/android-sdk-linux
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • ANDROID_HOME = /home/81986912515/Desenvolvimento/Ferramentas/android-sdk-linux
    • Java binary at: /home/81986912515/Desenvolvimento/Ferramentas/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Android Studio (version 3.2)
    • Android Studio at /home/81986912515/Desenvolvimento/Ferramentas/android-studio-3.2.1/android-studio
    • Flutter plugin version 31.3.1
    • Dart plugin version 181.5656
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)

[✓] Android Studio (version 3.5)
    • Android Studio at /home/81986912515/Desenvolvimento/Ferramentas/android-studio
    • Flutter plugin version 42.1.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[!] IntelliJ IDEA Ultimate Edition (version 2019.1)
    • IntelliJ at /home/81986912515/Desenvolvimento/Ferramentas/intellij-idea
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.dev/intellij-setup/#installing-the-plugins

[✓] Connected device (1 available)
    • SM G950F • ce11182b72a0ba3a02 • android-arm64 • Android 9 (API 28)

! Doctor found issues in 1 category.
```

**Comment by ardenn** [comment]
I'm having a similar issue too and it seems to appear only after adding `image_picker` to my dependencies.

Here's my `flutter doctor -v` output:


```
[✓] Flutter (Channel stable, v1.12.13+hotfix.5, on Linux, locale en_US.UTF-8)
    • Flutter version 1.12.13+hotfix.5 at /home/skia/flutter
    • Framework revision 27321ebbad (5 weeks ago), 2019-12-10 18:15:01 -0800
    • Engine revision 2994f7e1e6
    • Dart version 2.7.0

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /home/skia/android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • ANDROID_HOME = /home/skia/android/sdk
    • Java binary at: /opt/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[!] Android Studio (version 3.5)
    • Android Studio at /opt/android-studio
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] VS Code (version 1.41.1)
    • VS Code at /usr/share/code
    • Flutter extension version 3.7.1

[✓] Connected device (1 available)
    • Nokia 6 1 • PL2GAR98B0224387 • android-arm64 • Android 9 (API 28)

! Doctor found issues in 1 category.
```

**Comment by dnfield** [comment]
@blasten 

Looks like the android lifecycle plugin isn't selecting the right version of gradle?

**Comment by ardenn** [comment]
@dnfield Just out of curiosity, how is it that the lifecycle plugin picks the wrong version of gradle when you add `image_picker` to the dependencies, but picks the right version when you remove the dependency? It's a bit confusing for me.

**Comment by dnfield** [comment]
My guess is that when you don't add image_picker, nothing requiring Gradle > 4.10.x gets involved, and it works. But when you add image_picker, something requiring a higher version of Gradle gets involved and it doesn't.  But @blasten knows more about how this area works :)

**Comment by lorenzOliveto** [comment]
I have the same issue, adding the `image_picker` plugin I can't build with the same error.

**Comment by ardenn** [comment]
I managed to solve this for myself by upgrading gradle to the needed `5.4.1`. To do this, I opened my project's `andoid` directory in Android Studio and let the IDE do its thing. When it was done, the sync had an error with a link to fix it. Clicking the link upgraded my project's gradle version and solved the issue.

**Comment by JillyTaboga** [comment]
Same error here, probabily android lifecycle plugin is the problem.

**Comment by AlexEAA** [comment]
Same error here, probabily android lifecycle plugin is the problem.

**Comment by AlexEAA** [comment]
try to change the compileSdkVersion to: compileSdkVersion 28

via android, the studio updated Gradle to 5.4.1 but the assembly failed, in android studio I opened the plugin and dependency settings there were different versions and sdk I set all sdk 28

**Comment by peterson-umoke** [comment]
same issue here, but if i try to build the app i get this result instead

C:\tools\flutter\.pub-cache\hosted\pub.dartlang.org\flutter_plugin_android_lifecycle-1.0.5\android\src\main\java\io\flutter\embedding\engine\plugins\lifecycle\FlutterLifecycleAdapter.java:8: error: package androidx.lifecycle does not exist
import androidx.lifecycle.Lifecycle;
                         ^
C:\tools\flutter\.pub-cache\hosted\pub.dartlang.org\flutter_plugin_android_lifecycle-1.0.5\android\src\main\java\io\flutter\embedding\engine\plugins\lifecycle\FlutterLifecycleAdapter.java:22: error: cannot find symbol
  public static Lifecycle getActivityLifecycle(
                ^
  symbol:   class Lifecycle
  location: class FlutterLifecycleAdapter
2 errors

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileReleaseJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 2s


The plugin flutter_plugin_android_lifecycle could not be built due to the issue above.

But if i remove the image picker library, it compiles just fine.

**Comment by mayurdhurpate** [comment]
Faced the same but in my case, the app worked in development and when I updated it to Play Store it started crashing on all the devices updating/installing. Reverting back now. Please check for a hotfix for this if possible.

**Comment by ahawlitschek** [comment]
Same issued here, but without image picker.

```
FAILURE: Build failed with an exception.

* Where:
Build file '/Users/adrian/Development/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_plugin_android_lifecycle-1.0.5/android/build.gradle' line: 22

* What went wrong:
A problem occurred evaluating root project 'flutter_plugin_android_lifecycle'.
> Failed to apply plugin [id 'com.android.library']
   > Minimum supported Gradle version is 5.4.1. Current version is 4.10.2. If using the gradle wrapper, try editing the distributionUrl in /Users/adrian/Development/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_plugin_android_lifecycle-1.0.5/android/gradle/wrapper/gradle-wrapper.properties to gradle-5.4.1-all.zip

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1s


The plugin flutter_plugin_android_lifecycle could not be built due to the issue above.
```

**Comment by zzlhr** [comment]
now, How to build?

**Comment by yjouyang** [comment]
now, How to build?

**Comment by srburton** [comment]
*pubspec*

```
environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_cupertino_localizations: ^1.0.1
  cupertino_icons: ^0.1.2
  http: ^0.12.0+2
  dson: any
  flutter_secure_storage: ^3.3.1+1
  shared_preferences: ^0.5.6+2
  localstorage: 3.0.1+4
  flushbar: ^1.9.1
  progress_dialog: ^1.2.0
  google_maps_flutter: ^0.5.21+15
  flutter_spinkit: ^2.1.0
  sliding_up_panel: ^0.3.4
  network_image_to_byte: ^0.0.1
  image_cropper: ^1.2.1
  file_picker: ^1.4.3+2
  dio: 2.1.16
  flare_flutter: ^1.6.4
  line_icons: ^0.2.0
  cached_network_image: ^2.0.0-rc
  new_geolocation: ^1.0.0
  permission_handler: '^4.2.0+hotfix.2'
  badges: ^1.1.0
  intl: 0.16.0
  flutter_swiper: ^1.1.6
  provider: ^2.0.0
  share: ^0.6.3+5
  toast: ^0.1.5
  animated_text_kit: ^2.0.0
  video_player: ^0.10.5+2
  story_view: ^0.11.2
  flutter_i18n: ^0.8.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: any
  build_web_compilers: any

```





*fluter --version*
```
Flutter 1.12.13+hotfix.8 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 0b8abb4724 (11 days ago) • 2020-02-11 11:44:36 -0800
Engine • revision e1e6ced81d
Tools • Dart 2.7.0
```


*build*

`flutter build apk --release -v`

*output*

```
[   +3 ms] Running Gradle task 'assembleAarRelease'... (completed in 4,2s)
[   +6 ms] √ Built build\app\outputs\repo.
[   +1 ms] Building plugin flutter_plugin_android_lifecycle...
[   +8 ms] Running Gradle task 'assembleAarRelease'...
[   +7 ms] gradle.properties already sets `android.enableR8`
[  +25 ms] Using gradle from C:\\Users\\srburton\\AppData\\Roaming\\Pub\\Cache\\hosted\\pub.dartlang.org\\flutter_plugin_android_lifecycle-1.0.6\\android\gradlew.bat.
[   +1 ms] executing: [C:\\Users\\srburton\\AppData\\Roaming\\Pub\\Cache\\hosted\\pub.dartlang.org\\flutter_plugin_android_lifecycle-1.0.6\\android\]
C:\\Users\\srburton\\AppData\\Roaming\\Pub\\Cache\\hosted\\pub.dartlang.org\\flutter_plugin_android_lifecycle-1.0.6\\android\gradlew.bat -I=C:\src\flutter\packages\flutter_tools\gradle\aar_init_script.gradle -Pflutter-root=C:\src\flutter
-Poutput-dir=C:\Users\srburton\Documents\Projetos\waygo.app\build\app -Pis-plugin=true -Ptarget-platform=android-arm,android-arm64,android-x64 assembleAarRelease
[+2543 ms]
                    FAILURE: Build failed with an exception.

                    * Where:
                    Build file 'C:\Users\srburton\AppData\Roaming\Pub\Cache\hosted\pub.dartlang.org\flutter_plugin_android_lifecycle-1.0.6\android\build.gradle' line: 22

                    * What went wrong:
                    A problem occurred evaluating root project 'flutter_plugin_android_lifecycle'.
                    > Failed to apply plugin [id 'com.android.library']
                       > Minimum supported Gradle version is 5.4.1. Current version is 4.10.2. If using the gradle wrapper, try editing the distributionUrl in
                       C:\Users\srburton\AppData\Roaming\Pub\Cache\hosted\pub.dartlang.org\flutter_plugin_android_lifecycle-1.0.6\android\gradle\wrapper\gradle-wrapper.properties to gradle-5.4.1-all.zip

                    * Try:
                    Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

                    * Get more help at https://help.gradle.org

                    BUILD FAILED in 2s
[   +3 ms] Running Gradle task 'assembleAarRelease'... (completed in 2,6s)
[   +1 ms] 
           FAILURE: Build failed with an exception.
           
           * Where:
           Build file 'C:\Users\srburton\AppData\Roaming\Pub\Cache\hosted\pub.dartlang.org\flutter_plugin_android_lifecycle-1.0.6\android\build.gradle' line: 22
           
           * What went wrong:
           A problem occurred evaluating root project 'flutter_plugin_android_lifecycle'.
           > Failed to apply plugin [id 'com.android.library']
              > Minimum supported Gradle version is 5.4.1. Current version is 4.10.2. If using the gradle wrapper, try editing the distributionUrl in
C:\Users\srburton\AppData\Roaming\Pub\Cache\hosted\pub.dartlang.org\flutter_plugin_android_lifecycle-1.0.6\android\gradle\wrapper\gradle-wrapper.properties to gradle-5.4.1-all.zip
           
           * Try:
           Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
           
           * Get more help at https://help.gradle.org
           
           BUILD FAILED in 2s
           
[  +10 ms] "flutter apk" took 98.213ms.
The plugin flutter_plugin_android_lifecycle could not be built due to the issue above.

#0      throwToolExit (package:flutter_tools/src/base/common.dart:28:3)
#1      buildPluginsAsAar (package:flutter_tools/src/android/gradle.dart:726:7)
#2      _asyncErrorWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:80:45)
#3      _rootRunBinary (dart:async/zone.dart:1146:38)
#4      _CustomZone.runBinary (dart:async/zone.dart:1039:19)
#5      _FutureListener.handleError (dart:async/future_impl.dart:153:20)
#6      Future._propagateToListeners.handleError (dart:async/future_impl.dart:692:47)
#7      Future._propagateToListeners (dart:async/future_impl.dart:713:24)
#8      Future._completeError (dart:async/future_impl.dart:532:5)
#9      _AsyncAwaitCompleter.completeError (dart:async-patch/async_patch.dart:38:15)
#10     buildGradleAar (package:flutter_tools/src/android/gradle.dart)
#11     _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:73:64)
#12     _rootRunUnary (dart:async/zone.dart:1134:38)
#13     _CustomZone.runUnary (dart:async/zone.dart:1031:19)
#14     _FutureListener.handleValue (dart:async/future_impl.dart:139:18)
#15     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:680:45)
#16     Future._propagateToListeners (dart:async/future_impl.dart:709:32)
#17     Future._completeWithValue (dart:async/future_impl.dart:524:5)
#18     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:32:15)
#19     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:290:13)
#20     _DefaultProcessUtils.run (package:flutter_tools/src/base/process.dart)
#21     _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:73:64)
#22     _rootRunUnary (dart:async/zone.dart:1134:38)
#23     _CustomZone.runUnary (dart:async/zone.dart:1031:19)
#24     _FutureListener.handleValue (dart:async/future_impl.dart:139:18)
#25     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:680:45)
#26     Future._propagateToListeners (dart:async/future_impl.dart:709:32)
#27     Future._completeWithValue (dart:async/future_impl.dart:524:5)
#28     Future.wait.<anonymous closure> (dart:async/future.dart:400:22)
#29     _rootRunUnary (dart:async/zone.dart:1134:38)
#30     _CustomZone.runUnary (dart:async/zone.dart:1031:19)
#31     _FutureListener.handleValue (dart:async/future_impl.dart:139:18)
#32     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:680:45)
#33     Future._propagateToListeners (dart:async/future_impl.dart:709:32)
#34     Future._completeWithValue (dart:async/future_impl.dart:524:5)
#35     Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:554:7)
#36     _rootRun (dart:async/zone.dart:1126:13)
#37     _CustomZone.run (dart:async/zone.dart:1023:19)
#38     _CustomZone.runGuarded (dart:async/zone.dart:925:7)
#39     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:965:23)
#40     _microtaskLoop (dart:async/schedule_microtask.dart:43:21)
#41     _startMicrotaskLoop (dart:async/schedule_microtask.dart:52:5)
#42     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
#43     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:175:5)
```

**Comment by huhuang03** [comment]
> same issue here, but if i try to build the app i get this result instead
> 
> C:\tools\flutter.pub-cache\hosted\pub.dartlang.org\flutter_plugin_android_lifecycle-1.0.5\android\src\main\java\io\flutter\embedding\engine\plugins\lifecycle\FlutterLifecycleAdapter.java:8: error: package androidx.lifecycle does not exist
> import androidx.lifecycle.Lifecycle;
> ^
> C:\tools\flutter.pub-cache\hosted\pub.dartlang.org\flutter_plugin_android_lifecycle-1.0.5\android\src\main\java\io\flutter\embedding\engine\plugins\lifecycle\FlutterLifecycleAdapter.java:22: error: cannot find symbol
> public static Lifecycle getActivityLifecycle(
> ^
> symbol: class Lifecycle
> location: class FlutterLifecycleAdapter
> 2 errors
> 
> FAILURE: Build failed with an exception.
> 
> * What went wrong:
>   Execution failed for task ':compileReleaseJavaWithJavac'.
> 
> > Compilation failed; see the compiler error output for details.
> 
> * Try:
>   Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
> * Get more help at https://help.gradle.org
> 
> BUILD FAILED in 2s
> 
> The plugin flutter_plugin_android_lifecycle could not be built due to the issue above.
> 
> But if i remove the image picker library, it compiles just fine.

Same issue, but I want use image_picker...

**Comment by huhuang03** [comment]
Hello, After change the gradle version to 5.4.1. The new error comes:
```
/Users/th/source/flutter/.pub-cache/git/plugins-93a1c9b1a700baa9a06a9663dc9b428fe50b1b4b/packages/flutter_plugin_android_lifecycle/android/src/main/java/io/flutter/embedding/engine/plugins/lifecycle/FlutterLifecycleAdapter.java:8: 错误: 程序包androidx.lifecycle不存在
import androidx.lifecycle.Lifecycle;
                         ^
/Users/th/source/flutter/.pub-cache/git/plugins-93a1c9b1a700baa9a06a9663dc9b428fe50b1b4b/packages/flutter_plugin_android_lifecycle/android/src/main/java/io/flutter/embedding/engine/plugins/lifecycle/FlutterLifecycleAdapter.java:22: 错误: 找不到符号
  public static Lifecycle getActivityLifecycle(
                ^
  符号:   类 Lifecycle
  位置: 类 FlutterLifecycleAdapter
2 个错误

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileReleaseJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 10s


The plugin flutter_plugin_android_lifecycle could not be built due to the issue
above.
```

**Comment by huhuang03** [comment]
Then add the 
```
android {
    def lifecycle_version = "2.2.0"
    ....
    dependencies {
        implementation "androidx.lifecycle:lifecycle-runtime:$lifecycle_version"
    }
}
```

to `flutter_plugin_android_lifecycle/android/build.gradle`

Now everything goes fine~

Btw, you can use 
```
  flutter_plugin_android_lifecycle:
    git:
      url: http://some_repo/flutter/plugins
      path: packages/flutter_plugin_android_lifecycle
```
to use the modified plugin.

**Comment by omarsawalhah** [comment]
> Then add the
> 
> ```
> android {
>     def lifecycle_version = "2.2.0"
>     ....
>     dependencies {
>         implementation "androidx.lifecycle:lifecycle-runtime:$lifecycle_version"
>     }
> }
> ```
> 
> to `flutter_plugin_android_lifecycle/android/build.gradle`
> 
> Now everything goes fine~
> 
> Btw, you can use
> 
> ```
>   flutter_plugin_android_lifecycle:
>     git:
>       url: http://some_repo/flutter/plugins
>       path: packages/flutter_plugin_android_lifecycle
> ```
> 
> to use the modified plugin.

Where to put these settings, I am not an Android developer, is it "android/build.gradle" ? 
Thanks in advance

**Comment by huhuang03** [comment]
Sorry for my poor english.
1. Fork the `https://github.com/flutter/plugins`
2. Edit your fork, edit the `packages/flutter_plugin_android_lifecycle/android/build.gradle` file, Add the content to correspond block. 

```
android {
    def lifecycle_version = "2.2.0"
    ....
    dependencies {
        implementation "androidx.lifecycle:lifecycle-runtime:$lifecycle_version"
    }
}
```

The worked line is 
```
def lifecycle_version = "2.2.0"
```
and
```
implementation "androidx.lifecycle:lifecycle-runtime:$lifecycle_version"
```

other is for the corresponding structure.

3. Edit the `pubspec.yaml`, let flutter use your fork.
```
  flutter_plugin_android_lifecycle:
    git:
      url: http://some_repo/flutter/plugins
      path: packages/flutter_plugin_android_lifecycle
```

**Comment by zzlhr** [comment]
> 对不起，我英语不好。
> 
> 1. 前叉 `https://github.com/flutter/plugins`
> 2. 编辑您的fork，编辑`packages/flutter_plugin_android_lifecycle/android/build.gradle`文件，将内容添加到对应的块。
> 
> ```
> android {
>     def lifecycle_version = "2.2.0"
>     ....
>     dependencies {
>         implementation "androidx.lifecycle:lifecycle-runtime:$lifecycle_version"
>     }
> }
> ```
> 
> 工作线是
> 
> ```
> def lifecycle_version = "2.2.0"
> ```
> 
> 和
> 
> ```
> implementation "androidx.lifecycle:lifecycle-runtime:$lifecycle_version"
> ```
> 
> 其他是对应的结构。
> 
> 1. 编辑`pubspec.yaml`，让flutter使用叉子。
> 
> ```
>   flutter_plugin_android_lifecycle:
>     git:
>       url: path-to-your-fork
>       path: packages/flutter_plugin_android_lifecycle
> ```

I got this error after modifying it according to your scheme
```
✓ Built build/app/outputs/repo.
Building plugin image_picker...
Running Gradle task 'assembleAarRelease'...                             
Running Gradle task 'assembleAarRelease'... Done                    1.5s
> Task :assembleAarRelease UP-TO-DATE
> Task :preBuild UP-TO-DATE
> Task :preReleaseBuild UP-TO-DATE
> Task :compileReleaseAidl NO-SOURCE
> Task :compileReleaseRenderscript
> Task :checkReleaseManifest
> Task :generateReleaseBuildConfig
> Task :generateReleaseResValues
> Task :generateReleaseResources
> Task :packageReleaseResources
> Task :processReleaseManifest
> Task :generateReleaseRFile
> Task :prepareLintJar
> Task :generateReleaseSources
> Task :javaPreCompileRelease

> Task :compileReleaseJavaWithJavac FAILED

> Task :mergeReleaseConsumerProguardFiles
> Task :mergeReleaseShaders
> Task :compileReleaseShaders
> Task :generateReleaseAssets
> Task :packageReleaseAssets
> Task :packageReleaseRenderscript NO-SOURCE
> Task :processReleaseJavaRes NO-SOURCE
> Task :compileReleaseNdk NO-SOURCE
> Task :mergeReleaseJniLibFolders
> Task :transformNativeLibsWithMergeJniLibsForRelease
> Task :transformNativeLibsWithStripDebugSymbolForRelease
> Task :transformNativeLibsWithSyncJniLibsForRelease
18 actionable tasks: 18 executed

/Users/haoranliu/flutter/.pub-cache/git/plugins-385ec603b52d1687197b588fb85cc99daf98ee58/packages/image_picker/android/src/main/java/io/flutter/plugins/imagepicker/ImagePickerPlugin.java:15: 错误: 找不到符号
import androidx.lifecycle.DefaultLifecycleObserver;
                         ^
  符号:   类 DefaultLifecycleObserver
  位置: 程序包 androidx.lifecycle
/Users/haoranliu/flutter/.pub-cache/git/plugins-385ec603b52d1687197b588fb85cc99daf98ee58/packages/image_picker/android/src/main/java/io/flutter/plugins/imagepicker/ImagePickerPlugin.java:21: 错误: 找不到符号
import io.flutter.embedding.engine.plugins.lifecycle.FlutterLifecycleAdapter;
                                                    ^
  符号:   类 FlutterLifecycleAdapter
  位置: 程序包 io.flutter.embedding.engine.plugins.lifecycle
/Users/haoranliu/flutter/.pub-cache/git/plugins-385ec603b52d1687197b588fb85cc99daf98ee58/packages/image_picker/android/src/main/java/io/flutter/plugins/imagepicker/ImagePickerPlugin.java:33: 错误: 找不到符号
      implements Application.ActivityLifecycleCallbacks, DefaultLifecycleObserver {
                                                         ^
  符号:   类 DefaultLifecycleObserver
  位置: 类 ImagePickerPlugin
/Users/haoranliu/flutter/.pub-cache/git/plugins-385ec603b52d1687197b588fb85cc99daf98ee58/packages/image_picker/android/src/main/java/io/flutter/plugins/imagepicker/ImagePickerPlugin.java:40: 错误: 方法不会覆盖或实现超类型的方法
    @Override
    ^
/Users/haoranliu/flutter/.pub-cache/git/plugins-385ec603b52d1687197b588fb85cc99daf98ee58/packages/image_picker/android/src/main/java/io/flutter/plugins/imagepicker/ImagePickerPlugin.java:43: 错误: 方法不会覆盖或实现超类型的方法
    @Override
    ^
/Users/haoranliu/flutter/.pub-cache/git/plugins-385ec603b52d1687197b588fb85cc99daf98ee58/packages/image_picker/android/src/main/java/io/flutter/plugins/imagepicker/ImagePickerPlugin.java:46: 错误: 方法不会覆盖或实现超类型的方法
    @Override
    ^
/Users/haoranliu/flutter/.pub-cache/git/plugins-385ec603b52d1687197b588fb85cc99daf98ee58/packages/image_picker/android/src/main/java/io/flutter/plugins/imagepicker/ImagePickerPlugin.java:49: 错误: 方法不会覆盖或实现超类型的方法
    @Override
    ^
/Users/haoranliu/flutter/.pub-cache/git/plugins-385ec603b52d1687197b588fb85cc99daf98ee58/packages/image_picker/android/src/main/java/io/flutter/plugins/imagepicker/ImagePickerPlugin.java:52: 错误: 方法不会覆盖或实现超类型的方法
    @Override
    ^
/Users/haoranliu/flutter/.pub-cache/git/plugins-385ec603b52d1687197b588fb85cc99daf98ee58/packages/image_picker/android/src/main/java/io/flutter/plugins/imagepicker/ImagePickerPlugin.java:57: 错误: 方法不会覆盖或实现超类型的方法
    @Override
    ^
/Users/haoranliu/flutter/.pub-cache/git/plugins-385ec603b52d1687197b588fb85cc99daf98ee58/packages/image_picker/android/src/main/java/io/flutter/plugins/imagepicker/ImagePickerPlugin.java:199: 错误: 找不到符号
      lifecycle = FlutterLifecycleAdapter.getActivityLifecycle(activityBinding);
                  ^
  符号:   变量 FlutterLifecycleAdapter
  位置: 类 ImagePickerPlugin
/Users/haoranliu/flutter/.pub-cache/git/plugins-385ec603b52d1687197b588fb85cc99daf98ee58/packages/image_picker/android/src/main/java/io/flutter/plugins/imagepicker/ImagePickerPlugin.java:200: 错误: 不兼容的类型: ImagePickerPlugin.LifeCycleObserver无cycleObserver
      lifecycle.addObserver(observer);
                            ^
/Users/haoranliu/flutter/.pub-cache/git/plugins-385ec603b52d1687197b588fb85cc99daf98ee58/packages/image_picker/android/src/main/java/io/flutter/plugins/imagepicker/ImagePickerPlugin.java:208: 错误: 不兼容的类型: ImagePickerPlugin.LifeCycleObserver无cycleObserver
    lifecycle.removeObserver(observer);
                             ^
注: 某些消息已经过简化; 请使用 -Xdiags:verbose 重新编译以获得完整输出
12 个错误

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileReleaseJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1s


The plugin image_picker could not be built due to the issue above.
```

**Comment by huhuang03** [comment]
你看下你是不是改错package了。修改的是`flutter_plugin_android_lifecycle`，但是我看你报错的是`image_picker`。。好像不涉及到去修改image_picker。

**Comment by zzlhr** [comment]
> 你看下你是不是改错package了。修改的是`flutter_plugin_android_lifecycle`，但是我看你报错的是`image_picker`。。好像不涉及到去修改image_picker。

image_picker 引用了 flutter_plugin_android_lifecycle，所以报错的最终还是在flutter_plugin_android_lifecycle中

**Comment by huhuang03** [comment]
我觉得是你修改错了你的主项目的pubspec.yaml。

现在的错误好像是image_picker找不到flutter_plugin_android_lifecycle。一般应该不会发生。

你可以尝试一下保持image_picker不变。而只是修改flutter_plugin_android_lifecycle。

这样你的的主项目中的pubspec.yaml大概像这样：

```
image_picker:
flutter_plugin_android_lifecycle:
  git:
    url: path-to-your-fork
    path: packages/flutter_plugin_android_lifecycle
```

不用修改image_picker。这样配置之后。flutter可以正确选择flutter_plugin_android_lifecycle。

**Comment by roticagas** [comment]
I solved this problem with

```
flutter build appbundle
```

https://github.com/flutter/flutter/issues/42082#issuecomment-603216482

**Comment by mohamed31195** [comment]
Replacing `image_picker` with `image_picker_saver` solved the problem for me
