### ISSUE TITLE
[Catalina] Cannot set file modification time to .packages (file located in ~/Desktop)

### ISSUE THREAD

**Issue by guyueping** [flutter/flutter#48774]
## command

flutter build ios --release

## exception

```
FileSystemException: FileSystemException: Failed to set file modification time, path = '/Users/gyp/Desktop/myWeb/training/flutter/flutterdemo1/.packages' (OS Error: Operation not permitted, errno = 1)

#0      _File.setLastModifiedSync (dart:io/file_impl.dart:473:7)
#1      ForwardingFile.setLastModifiedSync (package:file/src/forwarding/forwarding_file.dart:62:55)
#2      _DefaultPub.get (package:flutter_tools/src/dart/pub.dart:211:19)
#3      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:599:17)
<asynchronous suspension>
#4      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:515:33)
<asynchronous suspension>
#5      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:146:29)
#6      _rootRun (dart:async/zone.dart:1126:13)
#7      _CustomZone.run (dart:async/zone.dart:1023:19)
#8      _runZoned (dart:async/zone.dart:1518:10)
#9      runZoned (dart:async/zone.dart:1465:12)
#10     AppContext.run (package:flutter_tools/src/base/context.dart:145:18)
#11     FlutterCommand.run (package:flutter_tools/src/runner/flutter_command.dart:505:20)
#12     CommandRunner.runCommand (package:args/command_runner.dart:197:27)
#13     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:413:21)
<asynchronous suspension>
#14     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:146:29)
#15     _rootRun (dart:async/zone.dart:1126:13)
#16     _CustomZone.run (dart:async/zone.dart:1023:19)
#17     _runZoned (dart:async/zone.dart:1518:10)
#18     runZoned (dart:async/zone.dart:1465:12)
#19     AppContext.run (package:flutter_tools/src/base/context.dart:145:18)
#20     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:364:19)
#21     CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:112:25)
#22     new Future.sync (dart:async/future.dart:224:31)
#23     CommandRunner.run (package:args/command_runner.dart:112:14)
#24     FlutterCommandRunner.run (package:flutter_tools/src/runner/flutter_command_runner.dart:250:18)
#25     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:63:22)
#26     _rootRun (dart:async/zone.dart:1126:13)
#27     _CustomZone.run (dart:async/zone.dart:1023:19)
#28     _runZoned (dart:async/zone.dart:1518:10)
#29     runZoned (dart:async/zone.dart:1502:12)
#30     run.<anonymous closure> (package:flutter_tools/runner.dart:61:18)
<asynchronous suspension>
#31     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:146:29)
#32     _rootRun (dart:async/zone.dart:1126:13)
#33     _CustomZone.run (dart:async/zone.dart:1023:19)
#34     _runZoned (dart:async/zone.dart:1518:10)
#35     runZoned (dart:async/zone.dart:1465:12)
#36     AppContext.run (package:flutter_tools/src/base/context.dart:145:18)
#37     runInContext (package:flutter_tools/src/context_runner.dart:64:24)
#38     run (package:flutter_tools/runner.dart:50:10)
#39     main (package:flutter_tools/executable.dart:65:9)
#40     main (file:///b/s/w/ir/k/archive/flutter/packages/flutter_tools/bin/flutter_tools.dart:8:3)
#41     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:305:32)
#42     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:174:12)
```

## flutter doctor

```
[32m[✓][39m Flutter (Channel stable, v1.12.13+hotfix.5, on Mac OS X 10.15.2 19C57, locale zh-Hans-CN)
    [32m•[39m Flutter version 1.12.13+hotfix.5 at /Users/gyp/flutter_mac/flutter
    [32m•[39m Framework revision 27321ebbad (5 weeks ago), 2019-12-10 18:15:01 -0800
    [32m•[39m Engine revision 2994f7e1e6
    [32m•[39m Dart version 2.7.0

[32m[✓][39m Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    [32m•[39m Android SDK at /Users/gyp/Library/Android/sdk
    [32m•[39m Android NDK location not configured (optional; useful for native profiling support)
    [32m•[39m Platform android-28, build-tools 28.0.3
    [32m•[39m ANDROID_HOME = /Users/gyp/Library/Android/sdk
    [32m•[39m Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    [32m•[39m Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)
    [32m•[39m All Android licenses accepted.

[32m[✓][39m Xcode - develop for iOS and macOS (Xcode 11.3)
    [32m•[39m Xcode at /Applications/Xcode.app/Contents/Developer
    [32m•[39m Xcode 11.3, Build version 11C29
    [32m•[39m CocoaPods version 1.8.4

[33m[!][39m Android Studio (version 3.3)
    [32m•[39m Android Studio at /Applications/Android Studio.app/Contents
    [31m✗[39m Flutter plugin not installed; this adds Flutter specific functionality.
    [31m✗[39m Dart plugin not installed; this adds Dart specific functionality.
    [32m•[39m Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)

[33m[!][39m Connected device
    [33m![39m No devices available

[33m![39m Doctor found issues in 2 categories.
```

**Comment by dnfield** [comment]
Catalina has special permissions around the `Desktop` folder.

Were you prompted to give `dart` access to the `Desktop` folder?

Or maybe it thinks it's something else because we're shelling out to pub for that?

/cc @christopherfujino

**Comment by dnfield** [comment]
Also: does the problem go away if you move the Flutter project to some non-priviledged folder on Catalina, like just moving it to `~/src` or `~/projects`?

**Comment by guyueping** [comment]
@dnfield, i move the project to ~/projects, but  it didn't works, any other possible causes  ？
## command

flutter build bundle --target-platform=ios --target=lib/main.dart --debug --depfile=build/snapshot_blob.bin.d --asset-dir=/Users/gyp/projects/flutter_demo1/ios/Flutter/App.framework/flutter_assets

## exception

FileSystemException: FileSystemException: Failed to set file modification time, path = '/Users/gyp/projects/flutter_demo1/.packages' (OS Error: Operation not permitted, errno = 1)

**Comment by dnfield** [comment]
Who is the owner of that .packages file?  Did you perhaps chown it to root somehow?

**Comment by guyueping** [comment]
yes, you are right, i chown it to root , and i change it back, and it works！ thank dnfield so much!!

**Comment by zhaoyunyi** [comment]
Should not run this command to create project, which command is "sudo flutter create xxxx", use flutter create xxxx
