### ISSUE TITLE
Atom cannot connect to observatory

### ISSUE THREAD

**Issue by abarth** [flutter/flutter#4878]
```
vm-service: Error: Unhandled exception:
	Failed assertion: boolean expression must not be null
	#0      Server._originCheck (server.dart:133:9)
	#1      Server._requestHandler (server.dart:156:10)
	#2      _RootZone.runUnaryGuarded (dart:async/zone.dart:1417)
	#3      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:334)
	#4      _BufferingStreamSubscription._add (dart:async/stream_impl.dart:261)
	#5      _StreamController&&_SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:768)
	#6      _StreamController._add (dart:async/stream_controller.dart:635)
	#7      _StreamController.add (dart:async/stream_controller.dart:581)
	#8      _HttpServer._handleRequest (http_impl.dart:2385)
	#9      _HttpConnection._HttpConnection.<anonymous closure> (http_impl.dart:2139)
	#10     _RootZone.runUnaryGuarded (dart:async/zone.dart:1417)
	#11     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:334)
	#12     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:261)
	#13     _StreamController&&_SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:768)
	#14     _StreamController._add (dart:async/stream_controller.dart:635)
	#15     _StreamController.add (dart:async/stream_controller.dart:581)
	#16     _HttpParser._headersEnd (http_parser.dart:381)
	#17     _HttpParser._doParse (http_parser.dart:711)
	#18     _HttpParser._parse (http_parser.dart:332)
	#19     _HttpParser._onData (http_parser.dart:821)
	#20     _RootZone.runUnaryGuarded (dart:async/zone.dart:1417)
	#21     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:334)
	#22     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:261)
	#23     _StreamController&&_SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:768)
	#24     _StreamController._add (dart:async/stream_controller.dart:635)
	#25     _StreamController.add (dart:async/stream_controller.dart:581)
	#26     _Socket._onData (dart:io-patch/socket_patch.dart:1659)
	#27     _RootZone.runUnaryGuarded (dart:async/zone.dart:1417)
	#28     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:334)
	#29     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:261)
	#30     _StreamController&&_SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:768)
	#31     _StreamController._add (dart:async/stream_controller.dart:635)
	#32     _StreamController.add (dart:async/stream_controller.dart:581)
	#33     _RawSocket._RawSocket.<anonymous closure> (dart:io-patch/socket_patch.dart:1226)
	#34     _NativeSocket.issueReadEvent.issue (dart:io-patch/socket_patch.dart:760)
	#35     _microtaskLoop (dart:async/schedule_microtask.dart:41)
	#36     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50)
	#37     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:96)
	#38     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:149)
```

Maybe a recently added security check?  /cc @eseidelGoogle @johnmccutchan

**Comment by abarth** [comment]
Related https://github.com/dart-lang/sdk/issues/26848

**Comment by tain335** [comment]
FlutterView remote debugger is not work.
