### ISSUE TITLE
webview_flutter shows white screen on Android 5.1.1 devices when resumed app second time

### ISSUE THREAD

**Issue by WeiCongcong** [flutter/flutter#48867]
## Steps to Reproduce

I'm using flutter v1.10.12 and plugins tag video_player-v0.10.3+3.
- Why do you use these versions ? 
- I have to avoid #47164

1. Create an app with webview_flutter
2. Run on an Android 5.1.1 device
3. Navigate to the webview page.
4. Press `Home` button and the app become background, then press the app icon to resume the app.
5. Do step `4` again

**Expected results:** 
The web content should be there.

**Actual results:** 
Only white screen with the app bar. The web content was gone. And I can't find anything abnormal in the logcat.
<details>
  <summary>Logs</summary>

```
```

```
```

```
[✓] Flutter (Channel unknown, v1.10.12, on Mac OS X 10.15.1 19B88, locale en-CN)
    • Flutter version 1.10.12 at /Users/zhanglei/Library/flutter
    • Framework revision 0e605cc4dd (3 months ago), 2019-10-04 07:52:15 -0700
    • Engine revision 759d3dba25
    • Dart version 2.6.0 (build 2.6.0-dev.0.0 7a7dcd1ed9)

[!] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/zhanglei/Android/sdk/android-sdk-macosx
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses

[✓] Xcode - develop for iOS and macOS (Xcode 11.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.3.1, Build version 11C504
    • CocoaPods version 1.8.4

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 40.1.2
    • Dart plugin version 191.8423
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] VS Code (version 1.32.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 2.21.1

[!] Connected device
    ! No devices available

```

</details>

**Comment by Vanethos** [comment]
Is it possible to provide a minimal code example for us to test it?

**Comment by WeiCongcong** [comment]
> Is it possible to provide a minimal code example for us to test it?
> 
> And also, do you see any logs either from:
> 
> `flutter logs`
> 
> Or directly from `adb`?
> 
> `adb logcat`

You can use the webview_flutter example follow these steps:
1.  checkout flutter version v1.10.12 and use this version.
2. checkout plugins tag tag video_player-v0.10.3+3 and use this version.
3. cd into the `path of plugins//packages/webview_flutter/example`
4. run `flutter clean; flutter build apk --target-platform android-arm;`
5. install and run the output apk on an android 5.1.1 device.

I've none Android 5.1.1 device here. And I have to test on some remote debugging platforms.  Currently I'm using [utest](https://newtest.21kunpeng.com/) There's only `adb logcat` output.

**Comment by WeiCongcong** [comment]
I'm trying the latest master channel. However, I can't determine whether this problem exists or not. There're tons of exceptions, which scared me. So I checked whether I was using the latest version of flutter master channel and the latest version of plugins master branch several times. And the answer was yes. I'm using flutter channel master with commit `6852605c4f76498925e2bb74d896c17b9ae79faa` and plugins master branch with commit `a36882509e7b146d4d1ae69611eea17f51e9d332`.

I built a debug version apk and tested on two devices, both of them show me a white screen.

On Lollipop devices, I got the #25714
And on Android P, I got the following exceptions:

<details>
<summary>logs</summary>

```
D/FlutterActivity( 9841): Using the launch theme as normal theme.
D/FlutterActivityAndFragmentDelegate( 9841): Setting up FlutterEngine.
D/FlutterActivityAndFragmentDelegate( 9841): No preferred FlutterEngine was provided. Creating a new FlutterEngine for this FlutterFragment.
D/FlutterActivityAndFragmentDelegate( 9841): Attaching FlutterEngine to the Activity that owns this Fragment.
W/FlutterView( 9841): Tried to send viewport metrics from Android to Flutter but this FlutterView was not attached to a FlutterEngine.
W/FlutterView( 9841): Tried to send viewport metrics from Android to Flutter but this FlutterView was not attached to a FlutterEngine.
D/FlutterView( 9841): Attaching to a FlutterEngine: io.flutter.embedding.engine.FlutterEngine@ebad817
D/FlutterActivityAndFragmentDelegate( 9841): Executing Dart entrypoint: main, and sending initial route: /
E/flutter ( 9841): [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: PlatformException(error, Attempt to invoke virtual method 'android.content.res.Resources android.content.Context.getResources()' on a null object reference, null)
E/flutter ( 9841): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:569:7)
E/flutter ( 9841): #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:156:18)
E/flutter ( 9841): <asynchronous suspension>
E/flutter ( 9841): #2      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:329:12)
E/flutter ( 9841): #3      AndroidViewController._create (package:flutter/src/services/platform_views.dart:633:54)
E/flutter ( 9841): #4      AndroidViewController.setSize (package:flutter/src/services/platform_views.dart:550:14)
E/flutter ( 9841): #5      RenderAndroidView._sizePlatformView (package:flutter/src/rendering/platform_view.dart:175:29)
E/flutter ( 9841): #6      RenderAndroidView.performResize (package:flutter/src/rendering/platform_view.dart:156:5)
E/flutter ( 9841): #7      RenderObject.layout (package:flutter/src/rendering/object.dart:1746:9)
E/flutter ( 9841): #8      RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:110:13)
E/flutter ( 9841): #9      RenderObject.layout (package:flutter/src/rendering/object.dart:1767:7)
E/flutter ( 9841): #10     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:110:13)
E/flutter ( 9841): #11     RenderObject.layout (package:flutter/src/rendering/object.dart:1767:7)
E/flutter ( 9841): #12     MultiChildLayoutDelegate.layoutChild (package:flutter/src/rendering/custom_layout.dart:171:11)
E/flutter ( 9841): #13     _ScaffoldLayout.performLayout (package:flutter/src/material/scaffold.dart:477:7)
E/flutter ( 9841): #14     MultiChildLayoutDelegate._callPerformLayout (package:flutter/src/rendering/custom_layout.dart:240:7)
E/flutter ( 9841): #15     RenderCustomMultiChildLayoutBox.performLayout (package:flutter/src/rendering/custom_layout.dart:399:14)
E/flutter ( 9841): #16     RenderObject.layout (package:flutter/src/rendering/object.dart:1767:7)
E/flutter ( 9841): #17     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:110:13)
E/flutter ( 9841): #18     RenderObject.layout (package:flutter/src/rendering/object.dart:1767:7)
E/flutter ( 9841): #19     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:110:13)
E/flutter ( 9841): #20     _RenderCustomClip.performLayout (package:flutter/src/rendering/proxy_box.dart:1247:11)
E/flutter ( 9841): #21     RenderObject.layout (package:flutter/src/rendering/object.dart:1767:7)
E/flutter ( 9841): #22     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:110:13)
E/flutter ( 9841): #23     RenderObject.layout (package:flutter/src/rendering/object.dart:1767:7)
E/flutter ( 9841): #24     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:110:13)
E/flutter ( 9841): #25     RenderObject.layout (package:flutter/src/rendering/object.dart:1767:7)
E/flutter ( 9841): #26     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:110:13)
E/flutter ( 9841): #27     RenderObject.layout (package:flutter/src/rendering/object.dart:1767:7)
E/flutter ( 9841): #28     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:110:13)
E/flutter ( 9841): #29     RenderObject.layout (package:flutter/src/rendering/object.dart:1767:7)
E/flutter ( 9841): #30     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:110:13)
E/flutter ( 9841): #31     RenderObject.layout (package:flutter/src/rendering/object.dart:1767:7)
E/flutter ( 9841): #32     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:110:13)
E/flutter ( 9841): #33     RenderObject.layout (package:flutter/src/rendering/object.dart:1767:7)
E/flutter ( 9841): #34     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:110:13)
E/flutter ( 9841): #35     RenderObject.layout (package:flutter/src/rendering/object.dart:1767:7)
E/flutter ( 9841): #36     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:110:13)
E/flutter ( 9841): #37     RenderOffstage.performLayout (package:flutter/src/rendering/proxy_box.dart:3219:13)
E/flutter ( 9841): #38     RenderObject.layout (package:flutter/src/rendering/object.dart:1767:7)
E/flutter ( 9841): #39     RenderStack.performLayout (package:flutter/src/rendering/stack.dart:503:15)
E/flutter ( 9841): #40     RenderObject.layout (package:flutter/src/rendering/object.dart:1767:7)
E/flutter ( 9841): #41     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:110:13)
E/flutter ( 9841): #42 
```
</details>

**Comment by bringogo** [comment]
same problem i encountered.

Scenario:
android5.1.1 device, open H5 in webview, h5 requests a image or contact from flutter client through JavascriptChannel, client use image_picker or easy_contact_picker (or self implement code) to request the image or contact, i take a picture, then returned the pic path to H5, up to now, everything is fine. 
But if i redo the operation, after i take a pic and confirm to return it, the webview's content is gone with white appearance, leaving only the title unchanged, at this time, press the BACK key will pop the webview and back to MainActivity, but when in the 'white appearance' moment, i print the top activity which is com.android.contacts/.activities.ContactSelectionActivity not MainActivity.

Code intenting to select contact:
public void intentToContact() {
        Intent intent = new Intent();
        intent.setAction("android.intent.action.PICK");
        intent.addCategory("android.intent.category.DEFAULT");
        intent.setType("vnd.android.cursor.dir/phone_v2");
        startActivityForResult(intent, 2000);
    }

Environment:
	device: vivo android5.1.1
	flutter: 1.12.13+hotfix.5
	webview_flutter: 0.3.19+5
	image_picker: 0.6.3



Adb log:
	
[log.txt](https://github.com/flutter/flutter/files/4084865/log.txt)

**Comment by TryLoveCatch** [comment]
same problem, but i used mapview
`Flutter 1.9.1+hotfix.105-pre.4 • channel unknown • unknown source
Framework • revision 7c7d9a910f (2 months ago) • 2020-02-06 18:45:31 +0800
Engine • revision 9b92c0d7d8
Tools • Dart 2.5.0
`

**Comment by TryLoveCatch** [comment]
android 5.1.1、5.0 all have this problem
Besides，after show white screen，swith screen to landscape，platformView will display again 😂

**Comment by darshankawar** [comment]
@WeiCongcong 
Since I don't have Android 5.0 or 5.1 device to replicate this issue to see if it's still valid using latest Flutter version, I tried the official `webview_flutter` plugin example on Android Emulators 5.0 and 5.1 and didn't notice white screen while putting the app in background and then resuming the app by bringing it to foreground in debug and release mode.

[48867_5.0.mov.zip](https://github.com/flutter/flutter/files/5653052/48867_5.0.mov.zip)

[48867_5.1.mov.zip](https://github.com/flutter/flutter/files/5653056/48867_5.1.mov.zip)


<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel stable, 1.22.4, on Mac OS X 10.15.4 19E2269 darwin-x64,
    locale en-IN)
    • Flutter version 1.22.4 at /Users/dhs/documents/Fluttersdk/flutter
    • Framework revision 1aafb3a8b9 (3 weeks ago), 2020-11-13 09:59:28 -0800
    • Engine revision 2c956a31c0
    • Dart version 2.10.4

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
    • Android SDK at /Users/dhs/Library/Android/sdk
    • Platform android-30, build-tools 30.0.0
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.0.1, Build version 12A7300
    • CocoaPods version 1.9.3

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 46.0.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.51.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.16.0

[✓] Connected device (2 available)
    • Android SDK built for x86 64 (mobile) • emulator-5554
      • android-x64 • Android 5.1.1 (API 22) (emulator)
    • iPhone SE (2nd generation) (mobile)   •
      6C85835D-FBFD-4AB3-8DE8-B4FAD35E5367 • ios         •
      com.apple.CoreSimulator.SimRuntime.iOS-14-0 (simulator)

• No issues found!


```

</details>

With the issue not replicable, I am going ahead and closing this as fixed. If you disagree, write in comments and I'll reopen it.
Thanks.

**Comment by WeiCongcong** [comment]
@darshankawar 
I've been using my own WebView plugin on Android devices for a year.  The problem might be fixed in the recent flutter or plugin versions. Thank you for your information.
