### ISSUE TITLE
java.lang.RuntimeException: Methods marked with @UiThread must be executed on the main thread. Current thread: Binder:25975_4

### ISSUE THREAD

**Issue by liuweichn** [flutter/flutter#48877]
_choiceFrom = ImageSource.camera;
Flutter (Channel stable, v1.9.1+hotfix.6, on Mac OS X 10.15.2 19C57, locale zh-Hans-CN)
image_picker: ^0.4.5
```
java.lang.RuntimeException: Methods marked with @UiThread must be executed on the main thread. Current thread: Binder:25975_4
        at io.flutter.embedding.engine.FlutterJNI.ensureRunningOnMainThread(FlutterJNI.java:807)
        at io.flutter.embedding.engine.FlutterJNI.invokePlatformMessageResponseCallback(FlutterJNI.java:740)
        at io.flutter.embedding.engine.dart.DartMessenger$Reply.reply(DartMessenger.java:156)
        at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler$1.success(MethodChannel.java:225)
        at io.flutter.plugins.imagepicker.ImagePickerDelegate.finishWithSuccess(ImagePickerDelegate.java:481)
        at io.flutter.plugins.imagepicker.ImagePickerDelegate.handleImageResult(ImagePickerDelegate.java:455)
        at io.flutter.plugins.imagepicker.ImagePickerDelegate.access$000(ImagePickerDelegate.java:65)
        at io.flutter.plugins.imagepicker.ImagePickerDelegate$4.onPathReady(ImagePickerDelegate.java:422)
        at io.flutter.plugins.imagepicker.ImagePickerDelegate$3$1.onScanCompleted(ImagePickerDelegate.java:152)
        at android.media.MediaScannerConnection$ClientProxy.onScanCompleted(MediaScannerConnection.java:204)
        at android.media.MediaScannerConnection$1.scanCompleted(MediaScannerConnection.java:53)
        at android.media.IMediaScannerListener$Stub.onTransact(IMediaScannerListener.java:97)
        at android.os.Binder.execTransactInternal(Binder.java:1021)
        at android.os.Binder.execTransact(Binder.java:994)
```

**Comment by iapicca** [comment]
Hi @liuweichn 
I see you are using an older version of flutter 
and a 6 months old version of image_picker

Please consider 
updating [image_picker](https://pub.dev/packages/image_picker) to `^0.6.3+1`
and run
`flutter channel stable`
`flutter upgrade --force`
`flutter pub cache repair`
`cd <YOUR APP FOLDER>`
`flutter clean`
If the issue persist please provide your updated 
`flutter doctor -v` and `flutter run --verbose`
together with a minimal code sample to reproduce the problem
thank you

**Comment by dnfield** [comment]
This was fixed in https://pub.dev/packages/image_picker#0603

**Comment by dnfield** [comment]
(IOW - you have to upgrade to at least image_picker v0.6.0+3 to avoid this)
