### ISSUE TITLE
[image_picker] and [flutter_plugin_android_lifecycle] crash

### ISSUE THREAD

**Issue by PiN73** [flutter/flutter#48906]
## Problem

It seems [image_picker](https://pub.dev/packages/image_picker) 0.6.3 causes startup crash in Android in release mode if used with [flutter_plugin_android_lifecycle](https://pub.dev/packages/flutter_plugin_android_lifecycle) 1.0.3

## Steps to reproduce

* Create new app
* Add this dependencies:
```
image_picker: 0.6.3
flutter_plugin_android_lifecycle: 1.0.3
```
*Note: 1.0.3 is used explicitly to force exactly this version. While omitting this dependency will now make 1.0.4 used and work well, some users may have `version: "1.0.3"` in pubspec.lock and see strange crash*
* Make release build for Android
* Install and launch app

[Example app](https://github.com/PiN73/test_image_picker)

## Logs

```
01-15 21:32:59.971 19324 19324 E AndroidRuntime: FATAL EXCEPTION: main
01-15 21:32:59.971 19324 19324 E AndroidRuntime: Process: com.example.test_image_picker, PID: 19324
01-15 21:32:59.971 19324 19324 E AndroidRuntime: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.example.test_image_picker/com.example.test_image_picker.MainActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'void androidx.lifecycle.f.a(androidx.lifecycle.g)' on a null object reference
01-15 21:32:59.971 19324 19324 E AndroidRuntime:        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2914)
01-15 21:32:59.971 19324 19324 E AndroidRuntime:        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3049)
01-15 21:32:59.971 19324 19324 E AndroidRuntime:        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
01-15 21:32:59.971 19324 19324 E AndroidRuntime:        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
01-15 21:32:59.971 19324 19324 E AndroidRuntime:        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
01-15 21:32:59.971 19324 19324 E AndroidRuntime:        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1809)
01-15 21:32:59.971 19324 19324 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:106)
01-15 21:32:59.971 19324 19324 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:193)
01-15 21:32:59.971 19324 19324 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:6692)
01-15 21:32:59.971 19324 19324 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
01-15 21:32:59.971 19324 19324 E AndroidRuntime:        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
01-15 21:32:59.971 19324 19324 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
01-15 21:32:59.971 19324 19324 E AndroidRuntime: Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void androidx.lifecycle.f.a(androidx.lifecycle.g)' on a null object reference
01-15 21:32:59.971 19324 19324 E AndroidRuntime:        at io.flutter.plugins.imagepicker.ImagePickerPlugin.a(Unknown Source:69)
01-15 21:32:59.971 19324 19324 E AndroidRuntime:        at io.flutter.plugins.imagepicker.ImagePickerPlugin.a(Unknown Source:27)
01-15 21:32:59.971 19324 19324 E AndroidRuntime:        at io.flutter.embedding.engine.c.a(Unknown Source:106)
01-15 21:32:59.971 19324 19324 E AndroidRuntime:        at b.a.b.a.e.a(Unknown Source:57)
01-15 21:32:59.971 19324 19324 E AndroidRuntime:        at b.a.b.a.d.onCreate(Unknown Source:22)
01-15 21:32:59.971 19324 19324 E AndroidRuntime:        at android.app.Activity.performCreate(Activity.java:7136)
01-15 21:32:59.971 19324 19324 E AndroidRuntime:        at android.app.Activity.performCreate(Activity.java:7127)
01-15 21:32:59.971 19324 19324 E AndroidRuntime:        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1272)
01-15 21:32:59.971 19324 19324 E AndroidRuntime:        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2894)
01-15 21:32:59.971 19324 19324 E AndroidRuntime:        ... 11 more
```

## Proposed solution

As the issue is fixed in flutter_plugin_android_lifecycle 1.0.4, make image_picker depend on
```
flutter_plugin_android_lifecycle: ^1.0.4
```

**Comment by dnfield** [comment]
This is a duplicate of #48622

**Comment by PiN73** [comment]
@dnfield thanks, now I see the dup. But shouldn't we make image_picker depend on flutter_plugin_android_lifecycle: ^1.0.4 now?

**Comment by mklim** [comment]
Yes, that's reasonable. It already has a fuzzy requirement so people should be able to get `1.0.4` if they clean and then re-run pub get. But we should set that as the lower bound to update any cached `pubspec.lock`'s and make sure we avoid this bug.

**Comment by PiN73** [comment]
I've made PR that updates dependency to `^1.0.4`: https://github.com/flutter/plugins/pull/2506
