### ISSUE TITLE
Exception (red screen) from gallery home after reassemble

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#4891]
Steps to repro:

* Start gallery onto iOS simulator with `flutter run --reload-sources`
* Scroll up and down
* Make a change to home.dart (e.g change the text from Flutter gallery to "Flutter gallery!!")
* Go to the console of the flutter tool
* hit `r`
* Go back to the simulator
* Notice how the reload completed and you see the text change
* Click anywhere in the gallery home

See:

![screen shot 2016-07-11 at 4 26 57 pm](https://cloud.githubusercontent.com/assets/5479/16750137/516c68e4-4784-11e6-819c-dfcaa52a0a9e.png)

Output from console:

```
[INFO:FlutterDynamicServiceLoader.mm(107)] 0 custom service definitions registered
Observatory listening on http://127.0.0.1:8100
Application running.
Type "h" or F1 for help, "r" or F5 to restart the app, and "q", F10, or ctrl-c to quit.
Type "w" to print the widget hierarchy of the app, and "t" for the render tree.
backboardd: CoreAnimation: updates deferred for too long
SpringBoard: [MPUSystemMediaControls] Updating supported commands for now playing application.
rRe-starting application...                           0.6s
══╡ EXCEPTION CAUGHT BY GESTURE LIBRARY ╞═══════════════════════════════════════════════════════════
The following assertion was thrown while dispatching a pointer event:
'package:flutter/src/widgets/framework.dart': Failed assertion: line 232 pos 12: 'removed' is not
true.
When the exception was thrown, this was the stack:
#0      _AssertionError._throwNew (dart:core-patch/errors_patch.dart:27)
#1      _AssertionError._checkAssertion (dart:core-patch/errors_patch.dart:34)
#2      GlobalKey.unregisterRemoveListener (package:flutter/src/widgets/framework.dart:232:12)
#3      _FocusState._updateScopeRemovalListener (package:flutter/src/widgets/focus.dart:346:19)
#4      _FocusState._setFocusedScope (package:flutter/src/widgets/focus.dart:331:5)
#5      Focus.moveScopeTo (package:flutter/src/widgets/focus.dart:222:29)
#6      ModalRoute.didPush (package:flutter/src/widgets/routes.dart:539:13)
#7      NavigatorState.push.<anonymous closure> (package:flutter/src/widgets/navigator.dart:365:13)
#8      State.setState (package:flutter/src/widgets/framework.dart:775:24)
#9      NavigatorState.push (package:flutter/src/widgets/navigator.dart:360:5)
#10     NavigatorState.pushNamed (package:flutter/src/widgets/navigator.dart:352:5)
#11     Navigator.pushNamed (package:flutter/src/widgets/navigator.dart:214:27)
#12     GalleryItem.build.<anonymous closure> (/Users/sethladd/Code/flutter/examples/flutter_gallery/lib/gallery/item.dart:38:21)
#13     _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:161:14)
#14     TapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:148:14)
#15     TapGestureRecognizer.acceptGesture (package:flutter/src/gestures/tap.dart:119:7)
#16     GestureArenaManager.sweep (package:flutter/src/gestures/arena.dart:107:27)
#17     BindingBase&SchedulerBinding&GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:137:20)
#18     BindingBase&SchedulerBinding&GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:111:22)
#19     BindingBase&SchedulerBinding&GestureBinding._handlePointerEvent (package:flutter/src/gestures/binding.dart:92:7)
#20     BindingBase&SchedulerBinding&GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:51:7)
#21     BindingBase&SchedulerBinding&GestureBinding._handlePointerPacket (package:flutter/src/gestures/binding.dart:44:5)
#22     _dispatchPointerPacket (file:///b/build/slave/Mac_Engine/build/src/out/ios_debug_sim/gen/sky/bindings/dart_ui/hooks.dart:43)
Event:
  PointerUpEvent(Point(326.0, 272.3))
Target:
  <WidgetsFlutterBinding>
════════════════════════════════════════════════════════════════════════════════════════════════════
Another exception was thrown: 'package:flutter/src/widgets/routes.dart': Failed assertion: line 608 pos 12: 'animation.status != AnimationStatus.dismissed' is not true.
```

(note: reload seems to work OK from the starter app. I'm able to start the starter app, make a change, reload, and then click on the starter app without a crash.)

Note: I do not trigger the crash if I change item.dart's GalleryItem titles and reload. Seems to be specific to changing the title in home.dart and then reloading (instead of changing anything and reloading).

**Comment by sethladd** [comment]
cc @johnmccutchan @Hixie

**Comment by johnmccutchan** [comment]
@Hixie Looks like an assert is blowing up during/after a reassemble?

**Comment by Hixie** [comment]
That stack suggests it's happening in response to user input. I don't think it's related to hot reload.

**Comment by johnmccutchan** [comment]
@Hixie Could the reassemble command leave things in a weird state that could lead to this?

**Comment by sethladd** [comment]
@Hixie thanks for taking a look. I'm able to click all around the app before I reload. I only get the crash after I edit home.dart's title, reload, and then click.

**Comment by Hixie** [comment]
Weird.

I'm sure something is broken that the reload is tickling, then. Maybe the currently focus object is being recreated with a new key but Focus isn't being notified?

**Comment by johnmccutchan** [comment]
Hans is trying out reload now and we hit some exceptions on our first try (the second try was successful):

NOTE: This is both after a reload and a reassemble.

```
I/flutter : Another exception was thrown: 'package:flutter/src/widgets/framework.dart': Failed assertion: line 232 pos 12: 'removed' is not true.
I/flutter : Another exception was thrown: 'package:flutter/src/widgets/routes.dart': Failed assertion: line 608 pos 12: 'animation.status != AnimationStatus.dismissed' is not true.
E/flutter : [ERROR:dart_error.cc(17)] Unhandled exception:
E/flutter : 'package:flutter/src/widgets/navigator.dart': Failed assertion: line 436 pos 12: '!_debugLocked' is not true.
E/flutter : #0      _AssertionError._throwNew (dart:core-patch/errors_patch.dart:27)
E/flutter : #1      _AssertionError._checkAssertion (dart:core-patch/errors_patch.dart:34)
E/flutter : #2      NavigatorState.pop (package:flutter/src/widgets/navigator.dart:436:12)
E/flutter : #3      _WidgetsAppState.didPopRoute (package:flutter/src/widgets/app.dart:134:22)
E/flutter : #4      BindingBase&SchedulerBinding&GestureBinding&ServicesBinding&RendererBinding&WidgetsBinding.handlePopRoute (package:flutter/src/widgets/binding.dart:163:20)
E/flutter : #5      _popRoute (file:///b/build/slave/Linux_Engine/build/src/out/android_debug/gen/sky/bindings/dart_ui/hooks.dart:38)
E/flutter : [ERROR:dart_error.cc(17)] Unhandled exception:
E/flutter : 'package:flutter/src/widgets/navigator.dart': Failed assertion: line 436 pos 12: '!_debugLocked' is not true.
E/flutter : #0      _AssertionError._throwNew (dart:core-patch/errors_patch.dart:27)
E/flutter : #1      _AssertionError._checkAssertion (dart:core-patch/errors_patch.dart:34)
E/flutter : #2      NavigatorState.pop (package:flutter/src/widgets/navigator.dart:436:12)
E/flutter : #3      _WidgetsAppState.didPopRoute (package:flutter/src/widgets/app.dart:134:22)
E/flutter : #4      BindingBase&SchedulerBinding&GestureBinding&ServicesBinding&RendererBinding&WidgetsBinding.handlePopRoute (package:flutter/src/widgets/binding.dart:163:20)
```

**Comment by johnmccutchan** [comment]
I've been testing with just sending a reassemble (not a load from sources):

```
I/flutter : Another exception was thrown: scheduleBuildFor() called for a widget for which a build was already scheduled.
I/flutter : Another exception was thrown: 'package:flutter/src/widgets/framework.dart': Failed assertion: line 1442 pos 12: '_debugLifecycleState == _ElementLifecycle.active' is not true.
I/flutter : Another exception was thrown: 'package:flutter/src/widgets/framework.dart': Failed assertion: line 2253 pos 14: '_dependents.isEmpty' is not true.
I/flutter : Another exception was thrown: 'package:flutter/src/widgets/framework.dart': Failed assertion: line 2004 pos 12: 'child == _child' is not true.
I/flutter : Another exception was thrown: 'package:flutter/src/widgets/framework.dart': Failed assertion: line 2004 pos 12: 'child == _child' is not true.
```

**Comment by johnmccutchan** [comment]
more:

```
I/flutter : Another exception was thrown: 'package:flutter/src/widgets/framework.dart': Failed assertion: line 232 pos 12: 'removed' is not true.
I/flutter : Another exception was thrown: 'package:flutter/src/widgets/navigator.dart': Failed assertion: line 89 pos 12: '_navigator._history.contains(this)' is not true.
I/flutter : Another exception was thrown: setState() called after dispose(): _AnimatedState(53493709; _StateLifecycle.defunct; not mounted)
E/flutter : [ERROR:dart_error.cc(17)] Unhandled exception:
E/flutter : 'package:flutter/src/widgets/focus.dart': Failed assertion: line 335 pos 12: '_focusedScope == key' is not true.
E/flutter : #0      _AssertionError._throwNew (dart:core-patch/errors_patch.dart:27)
E/flutter : #1      _AssertionError._checkAssertion (dart:core-patch/errors_patch.dart:34)
E/flutter : #2      _FocusState._scopeRemoved (package:flutter/src/widgets/focus.dart:335:12)
E/flutter : #3      GlobalKey._notifyListeners (package:flutter/src/widgets/framework.dart:258:21)
E/flutter : #4      _microtaskLoop (dart:async/schedule_microtask.dart:41)
E/flutter : #5      _startMicrotaskLoop (dart:async/schedule_microtask.dart:50)
^Chansmuller@chumley:/builds/dev/flutter$ 
```

**Comment by Hixie** [comment]
All the dumps above that start with `'removed' is not true` are triggered by closures changing identity during a hot reload. That's all of them except the `scheduleBuildFor` case, but I haven't seen that one. I've submitted a PR which will cause the first error after a reload to include a full stack which should make error reports more useful in the future.

**Comment by Hixie** [comment]
@johnmccutchan - I've assigned this to you for the closure identity issue; please feel free to reassign to me once you've decided what to do on that one. Thanks!

**Comment by johnmccutchan** [comment]
@Hixie Once https://github.com/flutter/engine/pull/2838 is pulled in the tear off closure equality problem is fixed.

**Comment by Hixie** [comment]
Last remaining known issue is with loading assets in hot reload mode. I'm going to close this bug since we have no longer any unknown issues. Please file new bugs if there's new problems with hot reload.

**Comment by sethladd** [comment]
Thanks for the help here!
