### ISSUE TITLE
[google_maps_flutter] Unhandled Exception after Flutter Upgrade to v1.12.x

### ISSUE THREAD

**Issue by workerbee22** [flutter/flutter#48927]
Steps to reproduce in an existing Flutter project that has had the google_maps_flutter plugin working for over 6 months.

1. Upgrade to Flutter v1.12.x
2. Unhandled Exception thrown
3. Checked Google APi console and confirmed Google Maps API SDK for Android is enabled and API key in AndroidManifest.xml is correct.
4. google_maps_flutter ^0.5.21+15

Unhandled Exception:

```
[ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: PlatformException(error, java.lang.IllegalStateException: Trying to create a platform view of unregistered type: plugins.flutter.io/google_maps
E/flutter (21307): 	at io.flutter.plugin.platform.PlatformViewsController$1.createPlatformView(PlatformViewsController.java:91)
E/flutter (21307): 	at io.flutter.embedding.engine.systemchannels.PlatformViewsChannel$1.create(PlatformViewsChannel.java:96)
E/flutter (21307): 	at io.flutter.embedding.engine.systemchannels.PlatformViewsChannel$1.onMethodCall(PlatformViewsChannel.java:60)
E/flutter (21307): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:231)
E/flutter (21307): 	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:93)
E/flutter (21307): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:642)
E/flutter (21307): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/flutter (21307): 	at android.os.MessageQueue.next(MessageQueue.java:336)
E/flutter (21307): 	at android.os.Looper.loop(Looper.java:174)
E/flutter (21307): 	at android.app.ActivityThread.main(ActivityThread.java:7356)
E/flutter (21307): 	at java.lang.reflect.Method.invoke(Native Method)
E/flutter (21307): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
E/flutter (21307): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
E/flutter (21307): , null)
E/flutter (21307): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:569)
E/flutter (21307): #1      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:321)
E/flutter (21307): <asynchronous suspension>
E/flutter (21307): #2      AndroidViewController._create (package:flutter/src/services/platform_views.dart:640)
E/flutter (21307): #3      AndroidViewController.setSize (package:flutter/src/services/platform_views.dart:557)
E/flutter (21307): #4      RenderAndroidView._sizePlatformView (package:flutter/src/rendering/platform_view.dart:174)
E/flutter (21307): #5      RenderAndroidView.performResize (package:flutter/src/rendering/platform_view.dart:155)
E/flutter (21307): #6      RenderObject.layout (package:flutter/src/rendering/object.dart:1703)
E/flutter (21307): #7      RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105)
E/flutter (21307): #8      RenderObject.layout (package:flutter/src/rendering/object.dart:1724)
E/flutter (21307): #9      RenderStack.performLayout (package:flutter/src/rendering/stack.dart:505)
E/flutter (21307): #10     RenderObject.layout (package:flutter/src/rendering/object.dart:1724)
E/flutter (21307): #11     MultiChildLayoutDelegate.layoutChild (package:flutter/src/rendering/custom_layout.dart:163)
E/flutter (21307): #12     _ScaffoldLayout.performLayout (package:flutter/src/material/scaffold.dart:477)
E/flutter (21307): #13     MultiChildLayoutDelegate._callPerformLayout (package:flutter/src/rendering/custom_layout.dart:232)
E/flutter (21307): #14     RenderCustomMultiChildLayoutBox.performLayout (package:flutter/src/rendering/custom_layout.dart:391)
E/flutter (21307): #15     RenderObject.layout (package:flutter/src/rendering/object.dart:1724)
E/flutter (21307): #16     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105)
E/flutter (21307): #17     RenderObject.layout (package:flutter/src/rendering/object.dart:1724)
E/flutter (21307): #18     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105)
E/flutter (21307): #19     _RenderCustomClip.performLayout (package:flutter/src/rendering/proxy_box.dart:1232)
E/flutter (21307): #20     RenderObject.layout (package:flutter/src/rendering/object.dart:1724)
E/flutter (21307): #21     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105)
E/flutter (21307): #22     RenderObject.layout (package:flutter/src/rendering/object.dart:1724)
E/flutter (21307): #23     MultiChildLayoutDelegate.layoutChild (package:flutter/src/rendering/custom_layout.dart:163)
E/flutter (21307): #24     _ScaffoldLayout.performLayout (package:flutter/src/material/scaffold.dart:477)
E/flutter (21307): #25     MultiChildLayoutDelegate._callPerformLayout (package:flutter/src/rendering/custom_layout.dart:232)
E/flutter (21307): #26     RenderCustomMultiChildLayoutBox.performLayout (package:flutter/src/rendering/custom_layout.dart:391)
E/flutter (21307): #27     RenderObject._layoutWithoutResize (package:flutter/src/rendering/object.dart:1584)
E/flutter (21307): #28     PipelineOwner.flushLayout (package:flutter/src/rendering/object.dart:844)
E/flutter (21307): #29     RendererBinding.drawFrame (package:flutter/src/rendering/binding.dart:344)
E/flutter (21307): #30     WidgetsBinding.drawFrame (package:flutter/src/widgets/
```

Flutter Doctor output:

```
[✓] Flutter (Channel beta, v1.12.13+hotfix.6, on Mac OS X 10.14.6 18G2022, locale en-AU)
    • Flutter version 1.12.13+hotfix.6 at /Users/gamma/Documents/flutter
    • Framework revision 18cd7a3601 (5 weeks ago), 2019-12-11 06:35:39 -0800
    • Engine revision 2994f7e1e6
    • Dart version 2.7.0

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/gamma/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • ANDROID_HOME = /Users/gamma/Library/Android/sdk
    • Java binary at: /Applications/Android Studio 3.5 Preview.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.3.1, Build version 11C504
    • CocoaPods version 1.8.4

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio 3.5 Preview.app/Contents
    • Flutter plugin version 42.1.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] VS Code (version 1.41.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.7.1

[✓] Connected device (1 available)
    • Pixel 3 XL • 8A4Y0F6ED • android-arm64 • Android 10 (API 29)

• No issues found!
```

Also noticed other people getting this like: 
- 
https://stackoverflow.com/questions/59511692/google-maps-trying-to-create-a-platform-view-of-unregistered-type
- This issue also closed, but the author is not sure of the fix: https://github.com/flutter/flutter/issues/34860

**Comment by workerbee22** [comment]
Have also performed ```flutter clean``` and ```flutter pub cache repair``` with Unhandled Exception still being thrown.

**Comment by workerbee22** [comment]
Provided a simple sample code to @mklim in this other issue here: https://github.com/flutter/flutter/issues/47921

**Comment by workerbee22** [comment]
Now tracking this issue which is where root cause fixes/solutions are being worked on: https://github.com/flutter/flutter/issues/47921

**Comment by workerbee22** [comment]
Fix as per issue here: https://github.com/flutter/flutter/issues/47921

Backed out and re applied NEW updated instructions here: https://github.com/flutter/flutter/wiki/Upgrading-pre-1.12-Android-projects

Updated Migration page instructions (which now specify changes to MainActivity file rather than deleting it) seem to work correctly for java projects and the ```google_maps_flutter``` package.
