### ISSUE TITLE
flutter pub global activate devtools failed

### ISSUE THREAD

**Issue by hyx0408** [flutter/flutter#48937]
flutter pub global activate devtools
failed

## Logs
D:\Projects\flutter\flutter_app001>flutter packages get
Running "flutter pub get" in flutter_app001...                      0.6s

D:\Projects\flutter\flutter_app001>flutter pub global activate devtools -v
FINE: Pub 2.7.0
IO  : Spawning "cmd /c ver" in D:\Projects\flutter\flutter_app001\.
IO  : Finished ver. Exit code 0.
    | stdout:
    | |
    | | Microsoft Windows [Version 10.0.17763.678]
    | Nothing output on stderr.
MSG : Resolving dependencies...
SLVR: fact: pub global activate is 0.0.0
SLVR: derived: pub global activate
SLVR: fact: pub global activate depends on devtools any
SLVR:   selecting pub global activate
SLVR:   derived: devtools any
IO  : Get versions from https://pub.dartlang.org/api/packages/devtools.
IO  : HTTP GET https://pub.dartlang.org/api/packages/devtools
    | Accept: application/vnd.pub.v2+json
    | X-Pub-OS: windows
    | X-Pub-Command: global activate
    | X-Pub-Session-ID: CE11F758-2320-4F75-B0E2-785245396BF9
    | X-Pub-Environment: flutter_cli:interactive
    | user-agent: Dart pub 2.7.0
IO  : HTTP error:
    | SocketException: OS Error: 由于套接字没有连接并且(当使用一个 sendto 调用发送数据报套接字时)没有提供地址，发送或接收数据的请求没有被接受。
    | , errno = 10057, address = xxx.xxx.xxx, port = 53434
    |
    | dart:_http                                           _HttpClient.openUrl
    | package:http/src/io_client.dart 33:36                IOClient.send
    | package:pub/src/http.dart 68:39                      _PubHttpClient.send
    | package:http_retry/http_retry.dart 97:33             RetryClient.send
    | package:pub/src/http.dart 194:43                     _ThrowingClient.send
    | package:http_throttle/http_throttle.dart 33:31       ThrottleClient.send
    | ===== asynchronous gap ===========================
    | dart:async                                           _asyncThenWrapperHelper
    | package:http_throttle/http_throttle.dart             ThrottleClient.send
    | package:http/src/base_client.dart 169:38             BaseClient._sendUnstreamed
    | package:http/src/base_client.dart 32:7               BaseClient.get
    | package:http/src/base_client.dart 117:12             BaseClient.read
    | package:pub/src/source/hosted.dart 160:31            BoundHostedSource.doGetVersions
    | package:pub/src/source.dart 167:12                   BoundSource.getVersions
    | package:pub/src/solver/package_lister.dart 76:44     PackageLister._versions.<fn>.<fn>
    | package:pub/src/http.dart 271:51                     withDependencyType
    | package:pub/src/solver/package_lister.dart 75:33     PackageLister._versions.<fn>
    | dart:async                                           new Future.sync
    | package:async/src/async_memoizer.dart 43:42          AsyncMemoizer.runOnce
    | package:pub/src/solver/package_lister.dart 74:58     PackageLister._versions
    | package:pub/src/solver/package_lister.dart 111:21    PackageLister.countVersions
    | package:pub/src/solver/version_solver.dart 354:44    VersionSolver._choosePackageVersion.<fn>
    | package:pub/src/utils.dart 301:39                    minByAsync
    | package:pub/src/solver/version_solver.dart 350:25    VersionSolver._choosePackageVersion
    | package:pub/src/solver/version_solver.dart 97:22     VersionSolver.solve
    | ===== asynchronous gap ===========================
    | dart:async                                           _asyncThenWrapperHelper
    | package:pub/src/solver/version_solver.dart           VersionSolver.solve
    | package:pub/src/solver.dart 35:10                    resolveVersions.<fn>
    | package:pub/src/log.dart 378:18                      progress
    | package:pub/src/solver.dart 32:10                    resolveVersions
    | package:pub/src/global_packages.dart 183:22          GlobalPackages._installInCache
    | package:pub/src/global_packages.dart 125:11          GlobalPackages.activateHosted
    | package:pub/src/command/global_activate.dart 114:24  GlobalActivateCommand.run
    | package:args/command_runner.dart 197:27              CommandRunner.runCommand
    | package:pub/src/command_runner.dart 171:39           PubCommandRunner.runCommand.<fn>
    | dart:async                                           new Future.sync
    | package:pub/src/utils.dart 109:12                    captureErrors.<fn>
    | package:stack_trace                                  Chain.capture
    | package:pub/src/utils.dart 122:11                    captureErrors
    | package:pub/src/command_runner.dart 171:13           PubCommandRunner.runCommand
IO  : Retry #1 for GET https://pub.dartlang.org/api/packages/devtools...
IO  : HTTP GET https://pub.dartlang.org/api/packages/devtools
    | Accept: application/vnd.pub.v2+json
    | X-Pub-OS: windows
    | X-Pub-Command: global activate
    | X-Pub-Session-ID: CE11F758-2320-4F75-B0E2-785245396BF9
    | X-Pub-Environment: flutter_cli:interactive
    | user-agent: Dart pub 2.7.0
IO  : HTTP error:
    | SocketException: OS Error: 由于套接字没有连接并且(当使用一个 sendto 调用发送数据报套接字时)没有提供地址，发送或接收数据的请求没有被接受。
    | , errno = 10057, address = xxx.xxx.xxx, port = 53440
    |
    | dart:_http                                           _HttpClient.openUrl
    | package:http/src/io_client.dart 33:36                IOClient.send
    | package:pub/src/http.dart 68:39                      _PubHttpClient.send
    | package:http_retry/http_retry.dart 97:33             RetryClient.send
    | ===== asynchronous gap ===========================
    | dart:async                                           _asyncThenWrapperHelper
    | package:http_retry/http_retry.dart                   RetryClient.send
    | package:pub/src/http.dart 194:43                     _ThrowingClient.send
    | package:http_throttle/http_throttle.dart 33:31       ThrottleClient.send
    | ===== asynchronous gap ===========================
    | dart:async                                           _asyncThenWrapperHelper
    | package:http_throttle/http_throttle.dart             ThrottleClient.send
    | package:http/src/base_client.dart 169:38             BaseClient._sendUnstreamed
    | package:http/src/base_client.dart 32:7               BaseClient.get
    | package:http/src/base_client.dart 117:12             BaseClient.read
    | package:pub/src/source/hosted.dart 160:31            BoundHostedSource.doGetVersions
    | package:pub/src/source.dart 167:12                   BoundSource.getVersions
    | package:pub/src/solver/package_lister.dart 76:44     PackageLister._versions.<fn>.<fn>
    | package:pub/src/http.dart 271:51                     withDependencyType
    | package:pub/src/solver/package_lister.dart 75:33     PackageLister._versions.<fn>
    | dart:async                                           new Future.sync
    | package:async/src/async_memoizer.dart 43:42          AsyncMemoizer.runOnce
    | package:pub/src/solver/package_lister.dart 74:58     PackageLister._versions
    | package:pub/src/solver/package_lister.dart 111:21    PackageLister.countVersions
    | package:pub/src/solver/version_solver.dart 354:44    VersionSolver._choosePackageVersion.<fn>
    | package:pub/src/utils.dart 301:39                    minByAsync
    | package:pub/src/solver/version_solver.dart 350:25    VersionSolver._choosePackageVersion
    | package:pub/src/solver/version_solver.dart 97:22     VersionSolver.solve
    | ===== asynchronous gap ===========================
    | dart:async                                           _asyncThenWrapperHelper
    | package:pub/src/solver/version_solver.dart           VersionSolver.solve
    | package:pub/src/solver.dart 35:10                    resolveVersions.<fn>
    | package:pub/src/log.dart 378:18                      progress
    | package:pub/src/solver.dart 32:10                    resolveVersions
    | package:pub/src/global_packages.dart 183:22          GlobalPackages._installInCache
    | package:pub/src/global_packages.dart 125:11          GlobalPackages.activateHosted
    | package:pub/src/command/global_activate.dart 114:24  GlobalActivateCommand.run
    | package:args/command_runner.dart 197:27              CommandRunner.runCommand
    | package:pub/src/command_runner.dart 171:39           PubCommandRunner.runCommand.<fn>
    | dart:async                                           new Future.sync
    | package:pub/src/utils.dart 109:12                    captureErrors.<fn>
    | package:stack_trace                                  Chain.capture
    | package:pub/src/utils.dart 122:11                    captureErrors
    | package:pub/src/command_runner.dart 171:13           PubCommandRunner.runCommand
IO  : Retry #2 for GET https://pub.dartlang.org/api/packages/devtools...
IO  : HTTP GET https://pub.dartlang.org/api/packages/devtools
    | Accept: application/vnd.pub.v2+json
    | X-Pub-OS: windows
    | X-Pub-Command: global activate
    | X-Pub-Session-ID: CE11F758-2320-4F75-B0E2-785245396BF9
    | X-Pub-Environment: flutter_cli:interactive
    | user-agent: Dart pub 2.7.0
IO  : HTTP error:
    | SocketException: OS Error: 由于套接字没有连接并且(当使用一个 sendto 调用发送数据报套接字时)没有提供地址，发送或接收数据的请求没有被接受。
    | , errno = 10057, address = xxx.xxx.xxx, port = 53452
    |
    | dart:_http                                           _HttpClient.openUrl
    | package:http/src/io_client.dart 33:36                IOClient.send
    | package:pub/src/http.dart 68:39                      _PubHttpClient.send
    | package:http_retry/http_retry.dart 97:33             RetryClient.send
    | ===== asynchronous gap ===========================
    | dart:async                                           _asyncThenWrapperHelper
    | package:http_retry/http_retry.dart                   RetryClient.send
    | package:pub/src/http.dart 194:43                     _ThrowingClient.send
    | package:http_throttle/http_throttle.dart 33:31       ThrottleClient.send
    | ===== asynchronous gap ===========================
    | dart:async                                           _asyncThenWrapperHelper
    | package:http_throttle/http_throttle.dart             ThrottleClient.send
    | package:http/src/base_client.dart 169:38             BaseClient._sendUnstreamed
    | package:http/src/base_client.dart 32:7               BaseClient.get
    | package:http/src/base_client.dart 117:12             BaseClient.read
    | package:pub/src/source/hosted.dart 160:31            BoundHostedSource.doGetVersions
    | package:pub/src/source.dart 167:12                   BoundSource.getVersions
    | package:pub/src/solver/package_lister.dart 76:44     PackageLister._versions.<fn>.<fn>
    | package:pub/src/http.dart 271:51                     withDependencyType
    | package:pub/src/solver/package_lister.dart 75:33     PackageLister._versions.<fn>
    | dart:async                                           new Future.sync
    | package:async/src/async_memoizer.dart 43:42          AsyncMemoizer.runOnce
    | package:pub/src/solver/package_lister.dart 74:58     PackageLister._versions
    | package:pub/src/solver/package_lister.dart 111:21    PackageLister.countVersions
    | package:pub/src/solver/version_solver.dart 354:44    VersionSolver._choosePackageVersion.<fn>
    | package:pub/src/utils.dart 301:39                    minByAsync
    | package:pub/src/solver/version_solver.dart 350:25    VersionSolver._choosePackageVersion
    | package:pub/src/solver/version_solver.dart 97:22     VersionSolver.solve
    | ===== asynchronous gap ===========================
    | dart:async                                           _asyncThenWrapperHelper
    | package:pub/src/solver/version_solver.dart           VersionSolver.solve
    | package:pub/src/solver.dart 35:10                    resolveVersions.<fn>
    | package:pub/src/log.dart 378:18                      progress
    | package:pub/src/solver.dart 32:10                    resolveVersions
    | package:pub/src/global_packages.dart 183:22          GlobalPackages._installInCache
    | package:pub/src/global_packages.dart 125:11          GlobalPackages.activateHosted
    | package:pub/src/command/global_activate.dart 114:24  GlobalActivateCommand.run
    | package:args/command_runner.dart 197:27              CommandRunner.runCommand
    | package:pub/src/command_runner.dart 171:39           PubCommandRunner.runCommand.<fn>
    | dart:async                                           new Future.sync
    | package:pub/src/utils.dart 109:12                    captureErrors.<fn>
    | package:stack_trace                                  Chain.capture
    | package:pub/src/utils.dart 122:11                    captureErrors
    | package:pub/src/command_runner.dart 171:13           PubCommandRunner.runCommand
IO  : Retry #3 for GET https://pub.dartlang.org/api/packages/devtools...
IO  : HTTP GET https://pub.dartlang.org/api/packages/devtools
    | Accept: application/vnd.pub.v2+json
    | X-Pub-OS: windows
    | X-Pub-Command: global activate
    | X-Pub-Session-ID: CE11F758-2320-4F75-B0E2-785245396BF9
    | X-Pub-Environment: flutter_cli:interactive
    | user-agent: Dart pub 2.7.0
IO  : HTTP error:
    | SocketException: OS Error: 由于套接字没有连接并且(当使用一个 sendto 调用发送数据报套接字时)没有提供地址，发送或接收数据的请求没有被接受。
    | , errno = 10057, address = xxx.xxx.xxx, port = 53474
    |
    | dart:_http                                           _HttpClient.openUrl
    | package:http/src/io_client.dart 33:36                IOClient.send
    | package:pub/src/http.dart 68:39                      _PubHttpClient.send
    | package:http_retry/http_retry.dart 97:33             RetryClient.send
    | ===== asynchronous gap ===========================
    | dart:async                                           _asyncThenWrapperHelper
    | package:http_retry/http_retry.dart                   RetryClient.send
    | package:pub/src/http.dart 194:43                     _ThrowingClient.send
    | package:http_throttle/http_throttle.dart 33:31       ThrottleClient.send
    | ===== asynchronous gap ===========================
    | dart:async                                           _asyncThenWrapperHelper
    | package:http_throttle/http_throttle.dart             ThrottleClient.send
    | package:http/src/base_client.dart 169:38             BaseClient._sendUnstreamed
    | package:http/src/base_client.dart 32:7               BaseClient.get
    | package:http/src/base_client.dart 117:12             BaseClient.read
    | package:pub/src/source/hosted.dart 160:31            BoundHostedSource.doGetVersions
    | package:pub/src/source.dart 167:12                   BoundSource.getVersions
    | package:pub/src/solver/package_lister.dart 76:44     PackageLister._versions.<fn>.<fn>
    | package:pub/src/http.dart 271:51                     withDependencyType
    | package:pub/src/solver/package_lister.dart 75:33     PackageLister._versions.<fn>
    | dart:async                                           new Future.sync
    | package:async/src/async_memoizer.dart 43:42          AsyncMemoizer.runOnce
    | package:pub/src/solver/package_lister.dart 74:58     PackageLister._versions
    | package:pub/src/solver/package_lister.dart 111:21    PackageLister.countVersions
    | package:pub/src/solver/version_solver.dart 354:44    VersionSolver._choosePackageVersion.<fn>
    | package:pub/src/utils.dart 301:39                    minByAsync
    | package:pub/src/solver/version_solver.dart 350:25    VersionSolver._choosePackageVersion
    | package:pub/src/solver/version_solver.dart 97:22     VersionSolver.solve
    | ===== asynchronous gap ===========================
    | dart:async                                           _asyncThenWrapperHelper
    | package:pub/src/solver/version_solver.dart           VersionSolver.solve
    | package:pub/src/solver.dart 35:10                    resolveVersions.<fn>
    | package:pub/src/log.dart 378:18                      progress
    | package:pub/src/solver.dart 32:10                    resolveVersions
    | package:pub/src/global_packages.dart 183:22          GlobalPackages._installInCache
    | package:pub/src/global_packages.dart 125:11          GlobalPackages.activateHosted
    | package:pub/src/command/global_activate.dart 114:24  GlobalActivateCommand.run
    | package:args/command_runner.dart 197:27              CommandRunner.runCommand
    | package:pub/src/command_runner.dart 171:39           PubCommandRunner.runCommand.<fn>
    | dart:async                                           new Future.sync
    | package:pub/src/utils.dart 109:12                    captureErrors.<fn>
    | package:stack_trace                                  Chain.capture
    | package:pub/src/utils.dart 122:11                    captureErrors
    | package:pub/src/command_runner.dart 171:13           PubCommandRunner.runCommand
IO  : MSG : Retry #4 for GET https://pub.dartlang.org/api/packages/devtools...
It looks like pub.dartlang.org is having some trouble.
    | Pub will wait for a while before trying to connect again.
IO  : HTTP GET https://pub.dartlang.org/api/packages/devtools
    | Accept: application/vnd.pub.v2+json
    | X-Pub-OS: windows
    | X-Pub-Command: global activate
    | X-Pub-Session-ID: CE11F758-2320-4F75-B0E2-785245396BF9
    | X-Pub-Environment: flutter_cli:interactive
    | user-agent: Dart pub 2.7.0
IO  : HTTP error:
    | SocketException: OS Error: 由于套接字没有连接并且(当使用一个 sendto 调用发送数据报套接字时)没有提供地址，发送或接收数据的请求没有被接受。
    | , errno = 10057, address = xxx.xxx.xxx, port = 53538
    |
    | dart:_http                                           _HttpClient.openUrl
    | package:http/src/io_client.dart 33:36                IOClient.send
    | package:pub/src/http.dart 68:39                      _PubHttpClient.send
    | package:http_retry/http_retry.dart 97:33             RetryClient.send
    | ===== asynchronous gap ===========================
    | dart:async                                           _asyncThenWrapperHelper
    | package:http_retry/http_retry.dart                   RetryClient.send
    | package:pub/src/http.dart 194:43                     _ThrowingClient.send
    | package:http_throttle/http_throttle.dart 33:31       ThrottleClient.send
    | ===== asynchronous gap ===========================
    | dart:async                                           _asyncThenWrapperHelper
    | package:http_throttle/http_throttle.dart             ThrottleClient.send
    | package:http/src/base_client.dart 169:38             BaseClient._sendUnstreamed
    | package:http/src/base_client.dart 32:7               BaseClient.get
    | package:http/src/base_client.dart 117:12             BaseClient.read
    | package:pub/src/source/hosted.dart 160:31            BoundHostedSource.doGetVersions
    | package:pub/src/source.dart 167:12                   BoundSource.getVersions
    | package:pub/src/solver/package_lister.dart 76:44     PackageLister._versions.<fn>.<fn>
    | package:pub/src/http.dart 271:51                     withDependencyType
    | package:pub/src/solver/package_lister.dart 75:33     PackageLister._versions.<fn>
    | dart:async                                           new Future.sync
    | package:async/src/async_memoizer.dart 43:42          AsyncMemoizer.runOnce
    | package:pub/src/solver/package_lister.dart 74:58     PackageLister._versions
    | package:pub/src/solver/package_lister.dart 111:21    PackageLister.countVersions
    | package:pub/src/solver/version_solver.dart 354:44    VersionSolver._choosePackageVersion.<fn>
    | package:pub/src/utils.dart 301:39                    minByAsync
    | package:pub/src/solver/version_solver.dart 350:25    VersionSolver._choosePackageVersion
    | package:pub/src/solver/version_solver.dart 97:22     VersionSolver.solve
    | ===== asynchronous gap ===========================
    | dart:async                                           _asyncThenWrapperHelper
    | package:pub/src/solver/version_solver.dart           VersionSolver.solve
    | package:pub/src/solver.dart 35:10                    resolveVersions.<fn>
    | package:pub/src/log.dart 378:18                      progress
    | package:pub/src/solver.dart 32:10                    resolveVersions
    | package:pub/src/global_packages.dart 183:22          GlobalPackages._installInCache
    | package:pub/src/global_packages.dart 125:11          GlobalPackages.activateHosted
    | package:pub/src/command/global_activate.dart 114:24  GlobalActivateCommand.run
    | package:args/command_runner.dart 197:27              CommandRunner.runCommand
    | package:pub/src/command_runner.dart 171:39           PubCommandRunner.runCommand.<fn>
    | dart:async                                           new Future.sync
    | package:pub/src/utils.dart 109:12                    captureErrors.<fn>
    | package:stack_trace                                  Chain.capture
    | package:pub/src/utils.dart 122:11                    captureErrors
    | package:pub/src/command_runner.dart 171:13           PubCommandRunner.runCommand
IO  : Retry #5 for GET https://pub.dartlang.org/api/packages/devtools...
IO  : HTTP GET https://pub.dartlang.org/api/packages/devtools
    | Accept: application/vnd.pub.v2+json
    | X-Pub-OS: windows
    | X-Pub-Command: global activate
    | X-Pub-Session-ID: CE11F758-2320-4F75-B0E2-785245396BF9
    | X-Pub-Environment: flutter_cli:interactive
    | user-agent: Dart pub 2.7.0
SLVR: Version solving took 0:01:03.494272 seconds.
    | Tried 1 solutions.
FINE: Resolving dependencies finished (1:03.497s).
ERR : Got socket error trying to find package devtools at https://pub.dartlang.org.
FINE: Exception type: WrappedException
FINE: package:pub/src/utils.dart 569:5            fail
    | package:pub/src/source/hosted.dart 355:7    BoundHostedSource._throwFriendlyError
    | package:pub/src/source/hosted.dart 163:7    BoundHostedSource.doGetVersions
    | ===== asynchronous gap ===========================
    | dart:async                                  Future.catchError
    | package:pub/src/utils.dart 109:52           captureErrors.<fn>
    | package:stack_trace                         Chain.capture
    | package:pub/src/utils.dart 122:11           captureErrors
    | package:pub/src/command_runner.dart 171:13  PubCommandRunner.runCommand
    | dart:async                                  _completeOnAsyncReturn
    | package:pub/src/command_runner.dart         PubCommandRunner._validatePlatform
    | dart:async                                  _completeOnAsyncReturn
    | package:pub/src/io.dart                     runProcess.<fn>
FINE: Wrapped exception: SocketException: OS Error: 由于套接字没有连接并且(当使用一个 sendto 调用发送数据报套接字时)没有提供地址，发送或接收数据的请求没有被接受。
    | , errno = 10057, address = xxx.xxx.xxx, port = 53573
    | dart:async/future.dart 276:45                                 new Future.error
    | dart:_http/http_impl.dart 2396:43                             _HttpClient._getConnection.connect
    | package:stack_trace/src/stack_zone_specification.dart 129:26  StackZoneSpecification._registerUnaryCallback.<fn>.<fn>
    | package:stack_trace/src/stack_zone_specification.dart 209:15  StackZoneSpecification._run
    | package:stack_trace/src/stack_zone_specification.dart 129:14  StackZoneSpecification._registerUnaryCallback.<fn>
    | dart:async/zone.dart 1134:38                                  _rootRunUnary
    | dart:async/zone.dart 1031:19                                  _CustomZone.runUnary
    | dart:async/future_impl.dart 157:20                            _FutureListener.handleError
    | dart:async/future_impl.dart 692:47                            Future._propagateToListeners.handleError
    | dart:async/future_impl.dart 713:24                            Future._propagateToListeners
    | dart:async/future_impl.dart 532:5                             Future._completeError
    | dart:async/future_impl.dart 580:7                             Future._asyncCompleteError.<fn>
    | package:stack_trace/src/stack_zone_specification.dart 209:15  StackZoneSpecification._run
    | package:stack_trace/src/stack_zone_specification.dart 119:48  StackZoneSpecification._registerCallback.<fn>
    | dart:async/zone.dart 1126:13                                  _rootRun
    | dart:async/zone.dart 1023:19                                  _CustomZone.run
    | dart:async/zone.dart 925:7                                    _CustomZone.runGuarded
    | dart:async/zone.dart 965:23                                   _CustomZone.bindCallbackGuarded.<fn>
    | dart:async/schedule_microtask.dart 43:21                      _microtaskLoop
    | dart:async/schedule_microtask.dart 52:5                       _startMicrotaskLoop
    | dart:isolate-patch/isolate_patch.dart 118:13                  _runPendingImmediateCallback
    | dart:isolate-patch/isolate_patch.dart 175:5                   _RawReceivePortImpl._handleMessage
    | ===== asynchronous gap ===========================
    | dart:async/zone.dart 1055:19                                  _CustomZone.registerUnaryCallback
    | dart:async/future_impl.dart 807:17                            _registerErrorHandler
    | dart:async/future_impl.dart 304:17                            Future.catchError
    | dart:_http/http_impl.dart 2403:12                             _HttpClient._getConnection.connect
    | dart:_http/http_impl.dart 2406:19                             _HttpClient._getConnection
    | dart:_http/http_impl.dart 2306:12                             _HttpClient._openUrl
    | dart:_http/http_impl.dart 2192:7                              _HttpClient.openUrl
    | package:http/src/io_client.dart 33:36                         IOClient.send
    | package:pub/src/http.dart 68:39                               _PubHttpClient.send
    | package:http_retry/http_retry.dart 97:33                      RetryClient.send
    | ===== asynchronous gap ===========================
    | dart:async/zone.dart 1055:19                                  _CustomZone.registerUnaryCallback
    | dart:async-patch/async_patch.dart 73:23                       _asyncThenWrapperHelper
    | package:http_retry/http_retry.dart                            RetryClient.send
    | package:pub/src/http.dart 194:43                              _ThrowingClient.send
    | package:http_throttle/http_throttle.dart 33:31                ThrottleClient.send
    | ===== asynchronous gap ===========================
    | dart:async/zone.dart 1055:19                                  _CustomZone.registerUnaryCallback
    | dart:async-patch/async_patch.dart 73:23                       _asyncThenWrapperHelper
    | package:http_throttle/http_throttle.dart                      ThrottleClient.send
    | package:http/src/base_client.dart 169:38                      BaseClient._sendUnstreamed
    | package:http/src/base_client.dart 32:7                        BaseClient.get
    | package:http/src/base_client.dart 117:12                      BaseClient.read
    | package:pub/src/source/hosted.dart 160:31                     BoundHostedSource.doGetVersions
    | package:pub/src/source.dart 167:12                            BoundSource.getVersions
    | package:pub/src/solver/package_lister.dart 76:44              PackageLister._versions.<fn>.<fn>
    | package:pub/src/http.dart 271:51                              withDependencyType
    | package:pub/src/solver/package_lister.dart 75:33              PackageLister._versions.<fn>
    | dart:async/future.dart 224:31                                 new Future.sync
    | package:async/src/async_memoizer.dart 43:42                   AsyncMemoizer.runOnce
    | package:pub/src/solver/package_lister.dart 74:58              PackageLister._versions
    | package:pub/src/solver/package_lister.dart 111:21             PackageLister.countVersions
    | package:pub/src/solver/version_solver.dart 354:44             VersionSolver._choosePackageVersion.<fn>
    | package:pub/src/utils.dart 301:39                             minByAsync
    | package:pub/src/solver/version_solver.dart 350:25             VersionSolver._choosePackageVersion
    | package:pub/src/solver/version_solver.dart 97:22              VersionSolver.solve
    | ===== asynchronous gap ===========================
    | dart:async/zone.dart 1055:19                                  _CustomZone.registerUnaryCallback
    | dart:async-patch/async_patch.dart 73:23                       _asyncThenWrapperHelper
    | package:pub/src/solver/version_solver.dart                    VersionSolver.solve
    | package:pub/src/solver.dart 35:10                             resolveVersions.<fn>
    | package:pub/src/log.dart 378:18                               progress
    | package:pub/src/solver.dart 32:10                             resolveVersions
    | package:pub/src/global_packages.dart 183:22                   GlobalPackages._installInCache
    | package:pub/src/global_packages.dart 125:11                   GlobalPackages.activateHosted
    | package:pub/src/command/global_activate.dart 114:24           GlobalActivateCommand.run
    | package:args/command_runner.dart 197:27                       CommandRunner.runCommand
    | package:pub/src/command_runner.dart 171:39                    PubCommandRunner.runCommand.<fn>
    | dart:async/future.dart 224:31                                 new Future.sync
    | package:pub/src/utils.dart 109:12                             captureErrors.<fn>
    | package:stack_trace/src/chain.dart 101:24                     Chain.capture.<fn>
    | dart:async/zone.dart 1126:13                                  _rootRun
    | dart:async/zone.dart 1023:19                                  _CustomZone.run
    | dart:async/zone.dart 1518:10                                  _runZoned
    | dart:async/zone.dart 1465:12                                  runZoned
    | package:stack_trace/src/chain.dart 99:12                      Chain.capture
    | package:pub/src/utils.dart 122:11                             captureErrors
    | package:pub/src/command_runner.dart 171:13                    PubCommandRunner.runCommand
pub finished with exit code 69

#0      throwToolExit (package:flutter_tools/src/base/common.dart:28:3)
#1      _DefaultPub.interactively (package:flutter_tools/src/dart/pub.dart:323:7)
<asynchronous suspension>
#2      PackagesForwardCommand.runCommand (package:flutter_tools/src/commands/packages.dart:241:15)
#3      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:615:18)
#4      _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:73:64)
#5      _rootRunUnary (dart:async/zone.dart:1134:38)
#6      _CustomZone.runUnary (dart:async/zone.dart:1031:19)
#7      _FutureListener.handleValue (dart:async/future_impl.dart:139:18)
#8      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:680:45)
#9      Future._propagateToListeners (dart:async/future_impl.dart:709:32)
#10     Future._completeWithValue (dart:async/future_impl.dart:524:5)
#11     Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:554:7)
#12     _rootRun (dart:async/zone.dart:1126:13)
#13     _CustomZone.run (dart:async/zone.dart:1023:19)
#14     _CustomZone.runGuarded (dart:async/zone.dart:925:7)
#15     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:965:23)
#16     _microtaskLoop (dart:async/schedule_microtask.dart:43:21)
#17     _startMicrotaskLoop (dart:async/schedule_microtask.dart:52:5)
#18     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
#19     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:175:5)

D:\Projects\flutter\flutter_app001>flutter doctor -v
[√] Flutter (Channel stable, v1.12.13+hotfix.5, on Microsoft Windows [Version 10.0.17763.678], locale zh-CN)
    • Flutter version 1.12.13+hotfix.5 at D:\flutter\flutter
    • Framework revision 27321ebbad (5 weeks ago), 2019-12-10 18:15:01 -0800
    • Engine revision 2994f7e1e6
    • Dart version 2.7.0

[!] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at C:\Users\h00423788\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: D:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)
    X Android license status unknown.
      Try re-installing or updating your Android SDK Manager.
      See https://developer.android.com/studio/#downloads or visit https://flutter.dev/setup/#android-setup for detailed instructions.

[√] Android Studio (version 3.5)
    • Android Studio at D:\Program Files\Android\Android Studio
    • Flutter plugin version 42.1.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)

[√] VS Code (version 1.41.1)
    • VS Code at C:\Users\h00423788\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.7.1

[√] Connected device (1 available)
    • VOG AL00 • TWH7N19108000016 • android-arm64 • Android 9 (API 28)

! Doctor found issues in 1 category.

**Comment by hyx0408** [comment]
I modify add two line on top of pub.bat
set http_proxy=name:password@myproxy:port
set https_proxy=name:password@myproxy:port

**Comment by jonahwilliams** [comment]
Are you using the PUB_HOSTED_URL? See https://flutter.dev/community/china#configuring-flutter-to-use-a-mirror-site
