### ISSUE TITLE
'attached': is not true.

### ISSUE THREAD

**Issue by viratshukla** [flutter/flutter#48956]
<details>
	<summary>logs</summary>

```bash
I/flutter (12804): ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
I/flutter (12804): The following assertion was thrown building InputDecorator(decoration: InputDecoration(icon:
I/flutter (12804): SvgPicture, hintText: "Username", hintMaxLines: "1", border: _NoInputBorder(), alignLabelWithHint:
I/flutter (12804): false), isFocused: false, isEmpty: true, dependencies: [_InheritedTheme,
I/flutter (12804): _LocalizationsScope-[GlobalKey#c529b], Directionality, MediaQuery], state:
I/flutter (12804): _InputDecoratorState#ce7d4(tickers: tracking 2 tickers)):
I/flutter (12804): 'package:flutter/src/services/text_input.dart': Failed assertion: line 745 pos 12: 'attached': is
I/flutter (12804): not true.
I/flutter (12804): 
I/flutter (12804): Either the assertion indicates an error in the framework itself, or we should provide substantially
I/flutter (12804): more information in this error message to help you determine and fix the underlying cause.
I/flutter (12804): In either case, please report this assertion by filing a bug on GitHub:
I/flutter (12804):   https://github.com/flutter/flutter/issues/new?template=BUG.md
I/flutter (12804): 
I/flutter (12804): The relevant error-causing widget was:
I/flutter (12804):   TextFormField
I/flutter (12804):   file:///D:/Studio/fork/mobily_b2b_virat/lib/core/reusable_widget/text_field_widgets.dart:79:11
I/flutter (12804): 
I/flutter (12804): When the exception was thrown, this was the stack:
I/flutter (12804): #2      TextInputConnection.setStyle (package:flutter/src/services/text_input.dart:745:12)
I/flutter (12804): #3      EditableTextState.didUpdateWidget (package:flutter/src/widgets/editable_text.dart:1162:29)
I/flutter (12804): #4      StatefulElement.update (package:flutter/src/widgets/framework.dart:4396:58)
I/flutter (12804): #5      Element.updateChild (package:flutter/src/widgets/framework.dart:2977:15)
I/flutter (12804): #6      SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:5452:14)
I/flutter (12804): #7      Element.updateChild (package:flutter/src/widgets/framework.dart:2977:15)
I/flutter (12804): #8      _RenderDecorationElement._updateChild (package:flutter/src/material/input_decorator.dart:1536:30)
I/flutter (12804): #9      _RenderDecorationElement.update (package:flutter/src/material/input_decorator.dart:1552:5)
I/flutter (12804): #10     Element.updateChild (package:flutter/src/widgets/framework.dart:2977:15)
I/flutter (12804): #11     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4243:16)
I/flutter (12804): #12     Element.rebuild (package:flutter/src/widgets/framework.dart:3947:5)
I/flutter (12804): #13     StatefulElement.update (package:flutter/src/widgets/framework.dart:4413:5)
I/flutter (12804): #14     Element.updateChild (package:flutter/src/widgets/framework.dart:2977:15)
I/flutter (12804): #15     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4243:16)
I/flutter (12804): #16     Element.rebuild (package:flutter/src/widgets/framework.dart:3947:5)
I/flutter (12804): #17     StatefulElement.update (package:flutter/src/widgets/framework.dart:4413:5)
I/flutter (12804): #18     Element.updateChild (package:flutter/src/widgets/framework.dart:2977:15)
I/flutter (12804): #19     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:5452:14)
I/flutter (12804): #20     Element.updateChild (package:flutter/src/widgets/framework.dart:2977:15)
I/flutter (12804): #21     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4243:16)
I/flutter (12804): #22     Element.rebuild (package:flutter/src/widgets/framework.dart:3947:5)
I/flutter (12804): #23     StatelessElement.update (package:flutter/src/widgets/framework.dart:4298:5)
I/flutter (12804): #24     Element.updateChild (package:flutter/src/widgets/framework.dart:2977:15)
I/flutter (12804): #25     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4243:16)
I/flutter (12804): #26     Element.rebuild (package:flutter/src/widgets/framework.dart:3947:5)
I/flutter (12804): #27     StatefulElement.update (package:flutter/src/widgets/framework.dart:4413:5)
I/flutter (12804): #28     Element.updateChild (package:flutter/src/widgets/framework.dart:2977:15)
I/flutter (12804): #29     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4243:16)
I/flutter (12804): #30     Element.rebuild (package:flutter/src/widgets/framework.dart:3947:5)
I/flutter (12804): #31     StatefulElement.update (package:flutter/src/widgets/framework.dart:4413:5)
I/flutter (12804): #32     Element.updateChild (package:flutter/src/widgets/framework.dart:2977:15)
I/flutter (12804): #33     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:5452:14)
I/flutter (12804): #34     Element.updateChild (package:flutter/src/widgets/framework.dart:2977:15)
I/flutter (12804): #35     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4243:16)
I/flutter (12804): #36     Element.rebuild (package:flutter/src/widgets/framework.dart:3947:5)
I/flutter (12804): #37     StatefulElement.update (package:flutter/src/widgets/framework.dart:4413:5)
I/flutter (12804): #38     Element.updateChild (package:flutter/src/widgets/framework.dart:2977:15)
I/flutter (12804): #39     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:5452:14)
I/flutter (12804): #40     Element.updateChild (package:flutter/src/widgets/framework.dart:2977:15)
I/flutter (12804): #41     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:5452:14)
I/flutter (12804): #42     Element.updateChild (package:flutter/src/widgets/framework.dart:2977:15)
I/flutter (12804): #43     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4243:16)
I/flutter (12804): #44     Element.rebuild (package:flutter/src/widgets/framework.dart:3947:5)
I/flutter (12804): #45     StatefulElement.update (package:flutter/src/widgets/framework.dart:4413:5)
I/flutter (12804): #46     Element.updateChild (package:flutter/src/widgets/framework.dart:2977:15)
I/flutter (12804): #47     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4243:16)
I/flutter (12804): #48     Element.rebuild (package:flutter/src/widgets/framework.dart:3947:5)
I/flutter (12804): #49     StatefulElement.update (package:flutter/src/widgets/framework.dart:4413:5)
I/flutter (12804): #50     Element.updateChild (package:flutter/src/widgets/framework.dart:2977:15)
I/flutter (12804): #51     RenderObjectElement.updateChildren (package:flutter/src/widgets/framework.dart:5161:32)
I/flutter (12804): #52     MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:5561:17)
I/flutter (12804): #53     Element.updateChild (package:flutter/src/widgets/framework.dart:2977:15)
I/flutter (12804): #54     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:5452:14)
I/flutter (12804): #55     Element.updateChild (package:flutter/src/widgets/framework.dart:2977:15)
I/flutter (12804): #56     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:5452:14)
I/flutter (12804): #57     Element.updateChild (package:flutter/src/widgets/framework.dart:2977:15)
I/flutter (12804): #58     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:5452:14)
I/flutter (12804): #59     Element.updateChild (package:flutter/src/widgets/framework.dart:2977:15)
I/flutter (12804): #60     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4243:16)
I/flutter (12804): #61     Element.rebuild (package:flutter/src/widgets/framework.dart:3947:5)
I/flutter (12804): #62     StatelessElement.update (package:flutter/src/widgets/framework.dart:4298:5)
I/flutter (12804): #63     Element.updateChild (package:flutter/src/widgets/framework.dart:2977:15)
I/flutter (12804): #64     RenderObjectElement.updateChildren (package:flutter/src/widgets/framework.dart:5161:32)
I/flutter (12804): #65     MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:5561:17)
I/flutter (12804): #66     Element.updateChild (package:flutter/src/widgets/framework.dart:2977:15)
I/flutter (12804): #67     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:5452:14)
I/flutter (12804): #68     Element.updateChild (package:flutter/src/widgets/framework.dart:2977:15)
I/flutter (12804): #69     RenderObjectElement.updateChildren (package:flutter/src/widgets/framework.dart:5161:32)
I/flutter (12804): #70     MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:5561:17)
I/flutter (12804): #71     Element.updateChild (package:flutter/src/widgets/framework.dart:2977:15)
I/flutter (12804): #72     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:5452:14)
I/flutter (12804): #73     Element.updateChild (package:flutter/src/widgets/framework.dart:2977:15)
I/flutter (12804): #74     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4243:16)
I/flutter (12804): #75     Element.rebuild (package:flutter/src/widgets/framework.dart:3947:5)
I/flutter (12804): #76     StatelessElement.update (package:flutter/src/widgets/framework.dart:4298:5)
I/flutter (12804): #77     Element.updateChild (package:flutter/src/widgets/framework.dart:2977:15)
I/flutter (12804): #78     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:5452:14)
I/flutter (12804): #79     Element.updateChild (package:flutter/src/widgets/framework.dart:2977:15)
I/flutter (12804): #80     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:5452:14)
I/flutter (12804): #81     Element.updateChild (package:flutter/src/widgets/framework.dart:2977:15)
I/flutter (12804): #82     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:5452:14)
I/flutter (12804): #83     Element.updateChild (package:flutter/src/widgets/framework.dart:2977:15)
I/flutter (12804): #84     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:5452:14)
I/flutter (12804): #85     Element.updateChild (package:flutter/src/widgets/framework.dart:2977:15)
I/flutter (12804): #86     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:5452:14)
I/flutter (12804): #87     Element.updateChild (package:flutter/src/widgets/framework.dart:2977:15)
I/flutter (12804): #88     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4243:16)
I/flutter (12804): #89     Element.rebuild (package:flutter/src/widgets/framework.dart:3947:5)
I/flutter (12804): #90     StatelessElement.update (package:flutter/src/widgets/framework.dart:4298:5)
I/flutter (12804): #91     Element.updateChild (package:flutter/src/widgets/framework.dart:2977:15)
I/flutter (12804): #92     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:5452:14)
I/flutter (12804): #93     Element.updateChild (package:flutter/src/widgets/framework.dart:2977:15)
I/flutter (12804): #94     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4243:16)
I/flutter (12804): #95     Element.rebuild (package:flutter/src/widgets/framework.dart:3947:5)
I/flutter (12804): #96     StatefulElement.update (package:flutter/src/widgets/framework.dart:4413:5)
I/flutter (12804): #97     Element.updateChild (package:flutter/src/widgets/framework.dart:2977:15)
I/flutter (12804): #98     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:5452:14)
I/flutter (12804): #99     Element.updateChild (package:flutter/src/widgets/framework.dart:2977:15)
I/flutter (12804): #100    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4243:16)
I/flutter (12804): #101    Element.rebuild (package:flutter/src/widgets/framework.dart:3947:5)
I/flutter (12804): #102    StatelessElement.update (package:flutter/src/widgets/framework.dart:4298:5)
I/flutter (12804): #103    Element.updateChild (package:flutter/src/widgets/framework.dart:2977:15)
I/flutter (12804): #104    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4243:16)
I/flutter (12804): #105    Element.rebuild (package:flutter/src/widgets/framework.dart:3947:5)
I/flutter (12804): #106    ProxyElement.update (package:flutter/src/widgets/framework.dart:4557:5)
I/flutter (12804): #107    Element.updateChild (package:flutter/src/widgets/framework.dart:2977:15)
I/flutter (12804): #108    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:5452:14)
I/flutter (12804): #109    Element.updateChild (package:flutter/src/widgets/framework.dart:2977:15)
I/flutter (12804): #110    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:5452:14)
I/flutter (12804): #111    Element.updateChild (package:flutter/src/widgets/framework.dart:2977:15)
I/flutter (12804): #112    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:5452:14)
I/flutter (12804): #113    Element.updateChild (package:flutter/src/widgets/framework.dart:2977:15)
I/flutter (12804): #114    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:5452:14)
I/flutter (12804): #115    Element.updateChild (package:flutter/src/widgets/framework.dart:2977:15)
I/flutter (12804): #116    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4243:16)
I/flutter (12804): #117    Element.rebuild (package:flutter/src/widgets/framework.dart:3947:5)
I/flutter (12804): #118    StatelessElement.update (package:flutter/src/widgets/framework.dart:4298:5)
I/flutter (12804): #119    Element.updateChild (package:flutter/src/widgets/framework.dart:2977:15)
I/flutter (12804): #120    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4243:16)
I/flutter (12804): #121    Element.rebuild (package:flutter/src/widgets/framework.dart:3947:5)
I/flutter (12804): #122    StatefulElement.update (package:flutter/src/widgets/framework.dart:4413:5)
I/flutter (12804): #123    Element.updateChild (package:flutter/src/widgets/framework.dart:2977:15)
I/flutter (12804): #124    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4243:16)
I/flutter (12804): #125    Element.rebuild (package:flutter/src/widgets/framework.dart:3947:5)
I/flutter (12804): #126    StatefulElement.update (package:flutter/src/widgets/framework.dart:4413:5)
I/flutter (12804): #127    Element.updateChild (package:flutter/src/widgets/framework.dart:2977:15)
I/flutter (12804): #128    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4243:16)
I/flutter (12804): #129    Element.rebuild (package:flutter/src/widgets/framework.dart:3947:5)
I/flutter (12804): #130    ProxyElement.update (package:flutter/src/widgets/framework.dart:4557:5)
I/flutter (12804): #131    Element.updateChild (package:flutter/src/widgets/framework.dart:2977:15)
I/flutter (12804): #132    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4243:16)
I/flutter (12804): #133    Element.rebuild (package:flutter/src/widgets/framework.dart:3947:5)
I/flutter (12804): #134    StatelessElement.update (package:flutter/src/widgets/framework.dart:4298:5)
I/flutter (12804): #135    Element.updateChild (package:flutter/src/widgets/framework.dart:2977:15)
I/flutter (12804): #136    RenderObjectElement.updateChildren (package:flutter/src/widgets/framework.dart:5161:32)
I/flutter (12804): #137    MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:5561:17)
I/flutter (12804): #138    Element.updateChild (package:flutter/src/widgets/framework.dart:2977:15)
I/flutter (12804): #139    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4243:16)
I/flutter (12804): #140    Element.rebuild (package:flutter/src/widgets/framework.dart:3947:5)
I/flutter (12804): #141    ProxyElement.update (package:flutter/src/widgets/framework.dart:4557:5)
I/flutter (12804): #142    Element.updateChild (package:flutter/src/widgets/framework.dart:2977:15)
I/flutter (12804): #143    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:5452:14)
I/flutter (12804): #144    Element.updateChild (package:flutter/src/widgets/framework.dart:2977:15)
I/flutter (12804): #145    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4243:16)
I/flutter (12804): #146    Element.rebuild (package:flutter/src/widgets/framework.dart:3947:5)
I/flutter (12804): #147    StatelessElement.update (package:flutter/src/widgets/framework.dart:4298:5)
I/flutter (12804): #148    Element.updateChild (package:flutter/src/widgets/framework.dart:2977:15)
I/flutter (12804): #149    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4243:16)
I/flutter (12804): #150    Element.rebuild (package:flutter/src/widgets/framework.dart:3947:5)
I/flutter (12804): #151    StatelessElement.update (package:flutter/src/widgets/framework.dart:4298:5)
I/flutter (12804): #152    Element.updateChild (package:flutter/src/widgets/framework.dart:2977:15)
I/flutter (12804): #153    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4243:16)
I/flutter (12804): #154    Element.rebuild (package:flutter/src/widgets/framework.dart:3947:5)
I/flutter (12804): #155    ProxyElement.update (package:flutter/src/widgets/framework.dart:4557:5)
I/flutter (12804): #156    Element.updateChild (package:flutter/src/widgets/framework.dart:2977:15)
I/flutter (12804): #157    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4243:16)
I/flutter (12804): #158    Element.rebuild (package:flutter/src/widgets/framework.dart:3947:5)
I/flutter (12804): #159    ProxyElement.update (package:flutter/src/widgets/framework.dart:4557:5)
I/flutter (12804): #160    Element.updateChild (package:flutter/src/widgets/framework.dart:2977:15)
I/flutter (12804): #161    RenderObjectElement.updateChildren (package:flutter/src/widgets/framework.dart:5161:32)
I/flutter (12804): #162    MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:5561:17)
I/flutter (12804): #163    Element.updateChild (package:flutter/src/widgets/framework.dart:2977:15)
I/flutter (12804): #164    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4243:16)
I/flutter (12804): #165    Element.rebuild (package:flutter/src/widgets/framework.dart:3947:5)
I/flutter (12804): #166    StatefulElement.update (package:flutter/src/widgets/framework.dart:4413:5)
I/flutter (12804): #167    Element.updateChild (package:flutter/src/widgets/framework.dart:2977:15)
I/flutter (12804): #168    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4243:16)
I/flutter (12804): #169    Element.rebuild (package:flutter/src/widgets/framework.dart:3947:5)
I/flutter (12804): #170    ProxyElement.update (package:flutter/src/widgets/framework.dart:4557:5)
I/flutter (12804): #171    Element.updateChild (package:flutter/src/widgets/framework.dart:2977:15)
I/flutter (12804): #172    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4243:16)
I/flutter (12804): #173    Element.rebuild (package:flutter/src/widgets/framework.dart:3947:5)
I/flutter (12804): #174    StatefulElement.update (package:flutter/src/widgets/framework.dart:4413:5)
I/flutter (12804): #175    Element.updateChild (package:flutter/src/widgets/framework.dart:2977:15)
I/flutter (12804): #176    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:5452:14)
I/flutter (12804): #177    Element.updateChild (package:flutter/src/widgets/framework.dart:2977:15)
I/flutter (12804): #178    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4243:16)
I/flutter (12804): #179    Element.rebuild (package:flutter/src/widgets/framework.dart:3947:5)
I/flutter (12804): #180    StatelessElement.update (package:flutter/src/widgets/framework.dart:4298:5)
I/flutter (12804): #181    Element.updateChild (package:flutter/src/widgets/framework.dart:2977:15)
I/flutter (12804): #182    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:5452:14)
I/flutter (12804): #183    Element.updateChild (package:flutter/src/widgets/framework.dart:2977:15)
I/flutter (12804): #184    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4243:16)
I/flutter (12804): #185    Element.rebuild (package:flutter/src/widgets/framework.dart:3947:5)
I/flutter (12804): #186    StatefulElement.update (package:flutter/src/widgets/framework.dart:4413:5)
I/flutter (12804): #187    Element.updateChild (package:flutter/src/widgets/framework.dart:2977:15)
I/flutter (12804): #188    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4243:16)
I/flutter (12804): #189    Element.rebuild (package:flutter/src/widgets/framework.dart:3947:5)
I/flutter (12804): #190    StatefulElement.update (package:flutter/src/widgets/framework.dart:4413:5)
I/flutter (12804): #191    Element.updateChild (package:flutter/src/widgets/framework.dart:2977:15)
I/flutter (12804): #192    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4243:16)
I/flutter (12804): #193    Element.rebuild (package:flutter/src/widgets/framework.dart:3947:5)
I/flutter (12804): #194    ProxyElement.update (package:flutter/src/widgets/framework.dart:4557:5)
I/flutter (12804): #195    Element.updateChild (package:flutter/src/widgets/framework.dart:2977:15)
I/flutter (12804): #196    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4243:16)
I/flutter (12804): #197    Element.rebuild (package:flutter/src/widgets/framework.dart:3947:5)
I/flutter (12804): #198    ProxyElement.update (package:flutter/src/widgets/framework.dart:4557:5)
I/flutter (12804): #199    Element.updateChild (package:flutter/src/widgets/framework.dart:2977:15)
I/flutter (12804): #200    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4243:16)
I/flutter (12804): #201    Element.rebuild (package:flutter/src/widgets/framework.dart:3947:5)
I/flutter (12804): #202    StatefulElement.update (package:flutter/src/widgets/framework.dart:4413:5)
I/flutter (12804): #203    Element.updateChild (package:flutter/src/widgets/framework.dart:2977:15)
I/flutter (12804): #204    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4243:16)
I/flutter (12804): #205    Element.rebuild (package:flutter/src/widgets/framework.dart:3947:5)
I/flutter (12804): #206    StatefulElement.update (package:flutter/src/widgets/framework.dart:4413:5)
I/flutter (12804): #207    Element.updateChild (package:flutter/src/widgets/framework.dart:2977:15)
I/flutter (12804): #208    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:5452:14)
I/flutter (12804): #209    Element.updateChild (package:flutter/src/widgets/framework.dart:2977:15)
I/flutter (12804): #210    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4243:16)
I/flutter (12804): #211    Element.rebuild (package:flutter/src/widgets/framework.dart:3947:5)
I/flutter (12804): #212    StatelessElement.update (package:flutter/src/widgets/framework.dart:4298:5)
I/flutter (12804): #213    Element.updateChild (package:flutter/src/widgets/framework.dart:2977:15)
I/flutter (12804): #214    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:5452:14)
I/flutter (12804): #215    Element.updateChild (package:flutter/src/widgets/framework.dart:2977:15)
I/flutter (12804): #216    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:5452:14)
I/flutter (12804): #217    Element.updateChild (package:flutter/src/widgets/framework.dart:2977:15)
I/flutter (12804): #218    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4243:16)
I/flutter (12804): #219    Element.rebuild (package:flutter/src/widgets/framework.dart:3947:5)
I/flutter (12804): #220    StatefulElement.update (package:flutter/src/widgets/framework.dart:4413:5)
I/flutter (12804): #221    Element.updateChild (package:flutter/src/widgets/framework.dart:2977:15)
I/flutter (12804): #222    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:5452:14)
I/flutter (12804): #223    Element.updateChild (package:flutter/src/widgets/framework.dart:2977:15)
I/flutter (12804): #224    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:5452:14)
I/flutter (12804): #225    Element.updateChild (package:flutter/src/widgets/framework.dart:2977:15)
I/flutter (12804): #226    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4243:16)
I/flutter (12804): #227    Element.rebuild (package:flutter/src/widgets/framework.dart:3947:5)
I/flutter (12804): #228    StatefulElement.update (package:flutter/src/widgets/framework.dart:4413:5)
I/flutter (12804): #229    Element.updateChild (package:flutter/src/widgets/framework.dart:2977:15)
I/flutter (12804): #230    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4243:16)
I/flutter (12804): #231    Element.rebuild (package:flutter/src/widgets/framework.dart:3947:5)
I/flutter (12804): #232    StatelessElement.update (package:flutter/src/widgets/framework.dart:4298:5)
I/flutter (12804): #233    Element.updateChild (package:flutter/src/widgets/framework.dart:2977:15)
I/flutter (12804): #234    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4243:16)
I/flutter (12804): #235    Element.rebuild (package:flutter/src/widgets/framework.dart:3947:5)
I/flutter (12804): #236    StatefulElement.update (package:flutter/src/widgets/framework.dart:4413:5)
I/flutter (12804): #237    Element.updateChild (package:flutter/src/widgets/framework.dart:2977:15)
I/flutter (12804): #238    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:5452:14)
I/flutter (12804): #239    Element.updateChild (package:flutter/src/widgets/framework.dart:2977:15)
I/flutter (12804): #240    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4243:16)
I/flutter (12804): #241    Element.rebuild (package:flutter/src/widgets/framework.dart:3947:5)
I/flutter (12804): #242    ProxyElement.update (package:flutter/src/widgets/framework.dart:4557:5)
I/flutter (12804): #243    _InheritedNotifierElement.update (package:flutter/src/widgets/inherited_notifier.dart:94:11)
I/flutter (12804): #244    Element.updateChild (package:flutter/src/widgets/framework.dart:2977:15)
I/flutter (12804): #245    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:5452:14)
I/flutter (12804): #246    Element.updateChild (package:flutter/src/widgets/framework.dart:2977:15)
I/flutter (12804): #247    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4243:16)
I/flutter (12804): #248    Element.rebuild (package:flutter/src/widgets/framework.dart:3947:5)
I/flutter (12804): #249    StatefulElement.update (package:flutter/src/widgets/framework.dart:4413:5)
I/flutter (12804): #250    Element.updateChild (package:flutter/src/widgets/framework.dart:2977:15)
I/flutter (12804): #251    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4243:16)
I/flutter (12804): #252    Element.rebuild (package:flutter/src/widgets/framework.dart:3947:5)
I/flutter (12804): #253    StatelessElement.update (package:flutter/src/widgets/framework.dart:4298:5)
I/flutter (12804): #254    Element.updateChild (package:flutter/src/widgets/framework.dart:2977:15)
I/flutter (12804): #255    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:5452:14)
I/flutter (12804): #256    Element.updateChild (package:flutter/src/widgets/framework.dart:2977:15)
I/flutter (12804): #257    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4243:16)
I/flutter (12804): #258    Element.rebuild (package:flutter/src/widgets/framework.dart:3947:5)
I/flutter (12804): #259    ProxyElement.update (package:flutter/src/widgets/framework.dart:4557:5)
I/flutter (12804): #260    Element.updateChild (package:flutter/src/widgets/framework.dart:2977:15)
I/flutter (12804): #261    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4243:16)
I/flutter (12804): #262    Element.rebuild (package:flutter/src/widgets/framework.dart:3947:5)
I/flutter (12804): #263    BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2432:33)
I/flutter (12804): #264    WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:773:20)
I/flutter (12804): #265    RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:283:5)
I/flutter (12804): #266    SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1102:15)
I/flutter (12804): #267    SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1041:9)
I/flutter (12804): #268    SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:957:5)
I/flutter (12804): #272    _invoke (dart:ui/hooks.dart:259:10)
I/flutter (12804): #273    _drawFrame (dart:ui/hooks.dart:217:3)
I/flutter (12804): (elided 5 frames from class _AssertionError and package dart:async)
I/flutter (12804): 
I/flutter (12804): ════════════════════════════════════════════════════════════════════════════════════════════════════
I/flutter (12804): Another exception was thrown: 'package:flutter/src/widgets/framework.dart': Failed assertion: line 4701 pos 14: '_dependents.isEmpty': is not true.
```

</details>

**Comment by viratshukla** [comment]
Its 100% reproducible
I created 1 TextFormField, and put a change button language.

First click multiple times on TextFormField , then change language from English to Arabic.
Now again click multiple times, then re change the language.
Repeat this 4-5 times, and we get red screen saying -> 'attached' : is not true.

**Comment by iapicca** [comment]
Hi @viratshukla 
can you please provide your `flutter doctor -v` ,
and a reproducible minimal code sample.
Thank you

**Comment by TahaTesser** [comment]
Hi @viratshukla 
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.
