### ISSUE TITLE
Windows desktop Compile failed on 1.13.10-pre.64@master channel

### ISSUE THREAD

**Issue by ShiinaManatsu** [flutter/flutter#48961]
## What's going on

Build [flutter-desktop-embedding\example](https://github.com/google/flutter-desktop-embedding) to windows desktop with `1.13.10-pre.64` `master channel` and failed

It works before 1.13 😂, in the end of the log, what dose `error C2039: 'GetNativeWindow': is not a member of 'flutter::FlutterViewController'` means, and how to fix?

Thanks for your helps~

## Logs

<details>
  <summary>
flutter run -d windows -v
</summary>

```
PS D:\Project.Flutter\Github\flutter-desktop-embedding\example> flutter run -d windows -v
[  +21 ms] executing: [D:\Program_Files\flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[  +55 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[        ] 72561cd41b7b43512b5fd21824f696d5ba666de6
[        ] executing: [D:\Program_Files\flutter/] git describe --match v*.*.* --first-parent --long --tags
[  +54 ms] Exit code 0 from: git describe --match v*.*.* --first-parent --long --tags
[   +1 ms] v1.13.9-64-g72561cd41
[   +5 ms] executing: [D:\Program_Files\flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[  +37 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/master
[        ] executing: [D:\Program_Files\flutter/] git ls-remote --get-url origin
[  +28 ms] Exit code 0 from: git ls-remote --get-url origin
[   +2 ms] https://github.com/flutter/flutter.git
[  +69 ms] executing: [D:\Program_Files\flutter/] git rev-parse --abbrev-ref HEAD
[  +32 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] master
[  +37 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +4 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +33 ms] executing: D:\Program_Files\Android\AndroidSDK\platform-tools\adb.exe devices -l
[  +22 ms] Exit code 0 from: D:\Program_Files\Android\AndroidSDK\platform-tools\adb.exe devices -l
[        ] List of devices attached
[  +13 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +5 ms] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[   +8 ms] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[ +190 ms] Launching lib\main.dart on Windows in debug mode...
[  +28 ms] executing: C:\Program Files (x86)\Microsoft Visual Studio\Installer\vswhere.exe -format json -utf8 -latest -requires Microsoft.Component.MSBuild Microsoft.VisualStudio.Component.VC.Tools.x86.x64 Microsoft.VisualStudio.Component.Windows10SDK.17763
[  +31 ms] Exit code 0 from: C:\Program Files (x86)\Microsoft Visual Studio\Installer\vswhere.exe -format json -utf8 -latest -requires Microsoft.Component.MSBuild Microsoft.VisualStudio.Component.VC.Tools.x86.x64 Microsoft.VisualStudio.Component.Windows10SDK.17763
[   +4 ms] [
             {
               "instanceId": "c8211aed",
               "installDate": "2019-04-05T02:43:08Z",
               "installationName": "VisualStudio/16.4.2+29613.14",
               "installationPath": "C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Enterprise",
               "installationVersion": "16.4.29613.14",
               "productId": "Microsoft.VisualStudio.Product.Enterprise",
               "productPath": "C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Enterprise\\Common7\\IDE\\devenv.exe",
               "state": 4294967295,
               "isComplete": true,
               "isLaunchable": true,
               "isPrerelease": false,
               "isRebootRequired": false,
               "displayName": "Visual Studio Enterprise 2019",
               "description": "Scalable, end-to-end solution for teams of any size",
               "channelId": "VisualStudio.16.Release",
               "channelUri": "https://aka.ms/vs/16/release/channel",
               "enginePath": "C:\\program files (x86)\\microsoft visual studio\\installer\\resources\\app\\ServiceHub\\Services\\Microsoft.VisualStudio.Setup.Service",
               "releaseNotes": "https://go.microsoft.com/fwlink/?LinkId=660893#16.4.2",
               "thirdPartyNotices": "https://go.microsoft.com/fwlink/?LinkId=660909",
               "updateDate": "2019-12-19T02:15:53.0798129Z",
               "catalog": {
                 "buildBranch": "d16.4",
                 "buildVersion": "16.4.29613.14",
                 "id": "VisualStudio/16.4.2+29613.14",
                 "localBuild": "build-lab",
                 "manifestName": "VisualStudio",
                 "manifestType": "installer",
                 "productDisplayVersion": "16.4.2",
                 "productLine": "Dev16",
                 "productLineVersion": "2019",
                 "productMilestone": "RTW",
                 "productMilestoneIsPreRelease": "False",
                 "productName": "Visual Studio",
                 "productPatchVersion": "2",
                 "productPreReleaseMilestoneSuffix": "1.0",
                 "productSemanticVersion": "16.4.2+29613.14",
                 "requiredEngineVersion": "2.4.1111.43337"
               },
               "properties": {
                 "campaignId": "1286231557.1529740537",
                 "canceled": "0",
                 "channelManifestId": "VisualStudio.16.Release/16.4.2+29613.14",
                 "nickname": "",
                 "setupEngineFilePath": "C:\\Program Files (x86)\\Microsoft Visual Studio\\Installer\\vs_installershell.exe"
               }
             }
           ]
[  +11 ms] Building Windows application...
[   +1 ms] executing: [D:\Project.Flutter\Github\flutter-desktop-embedding\example\windows/] D:\Program_Files\flutter\packages\flutter_tools\bin\vs_build.bat C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvars64.bat Runner.sln Debug      
[ +179 ms] **********************************************************************
[        ] ** Visual Studio 2019 Developer Command Prompt v16.4.2
[        ] ** Copyright (c) 2019 Microsoft Corporation
[        ] **********************************************************************
[ +662 ms] [vcvarsall.bat] Environment initialized for: 'x64'
[ +104 ms] Microsoft (R) Build Engine version 16.4.0+e901037fe for .NET Framework
[        ] Copyright (C) Microsoft Corporation. All rights reserved.
[  +11 ms] Building the projects in this solution one at a time. To enable parallel build, please add the "-m" switch.
[ +198 ms] Build started 1/16/2020 8:40:19 PM.
[ +677 ms] Project "D:\Project.Flutter\Github\flutter-desktop-embedding\example\windows\Runner.sln" on node 1 (default targets).
[   +2 ms] ValidateSolutionConfiguration:
[   +9 ms]   Building solution configuration "Debug|x64".
[ +356 ms] Project "D:\Project.Flutter\Github\flutter-desktop-embedding\example\windows\Runner.sln" (1) is building "D:\Project.Flutter\Github\flutter-desktop-embedding\example\windows\Runner.vcxproj.metaproj" (2) on node 1 (default targets).
[        ] Project "D:\Project.Flutter\Github\flutter-desktop-embedding\example\windows\Runner.vcxproj.metaproj" (2) is building "D:\Project.Flutter\Github\flutter-desktop-embedding\example\windows\FlutterBuild.vcxproj" (3) on node 1 (default targets).
[        ] InitializeBuildStatus:
[        ]   Creating "x64\Debug\Flutter Build.tlog\unsuccessfulbuild" because "AlwaysCreate" was specified.
[  +53 ms] CustomBuildStep:
[        ]   Running Flutter backend build
[  +16 ms]   "D:\Project.Flutter\Github\flutter-desktop-embedding\example\windows\scripts\prepare_dependencies" Debug
[   +5 ms]   :VCEnd
[+10020 ms] FinalizeBuildStatus:
[   +1 ms]   Deleting file "x64\Debug\Flutter Build.tlog\unsuccessfulbuild".
[        ]   Touching "x64\Debug\Flutter Build.tlog\Flutter Build.lastbuildstate".
[   +3 ms] Done Building Project "D:\Project.Flutter\Github\flutter-desktop-embedding\example\windows\FlutterBuild.vcxproj" (default targets).
[  +63 ms] Project "D:\Project.Flutter\Github\flutter-desktop-embedding\example\windows\Runner.vcxproj.metaproj" (2) is building "D:\Project.Flutter\Github\flutter-desktop-embedding\example\windows\Runner.vcxproj" (4) on node 1 (default targets).
[        ] InitializeBuildStatus:
[        ]   Touching "D:\Project.Flutter\Github\flutter-desktop-embedding\example\windows\..\build\windows\intermediates\x64\Debug\Runner\Runner.tlog\unsuccessfulbuild".
[ +100 ms] ClCompile:
[        ]   C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Tools\MSVC\14.24.28314\bin\HostX86\x64\CL.exe /c /ZI /JMC /nologo /W3 /WX- /diagnostics:column /sdl /Od /D _MBCS /D _UNICODE /D UNICODE /Gm- /EHsc /RTC1 /MDd /GS /fp:precise /permissive-
/Zc:wchar_t /Zc:forScope /Zc:inline /Fo"D:\Project.Flutter\Github\flutter-desktop-embedding\example\windows\..\build\windows\intermediates\x64\Debug\Runner\\"
/Fd"D:\Project.Flutter\Github\flutter-desktop-embedding\example\windows\..\build\windows\intermediates\x64\Debug\Runner\vc142.pdb" /Gd /TP /FC /errorReport:queue main.cpp flutter\generated_plugin_registrant.cc
[  +63 ms]   main.cpp
[ +814 ms] D:\Project.Flutter\Github\flutter-desktop-embedding\example\windows\main.cpp(86,60): error C2039: 'GetNativeWindow': is not a member of 'flutter::FlutterViewController' [D:\Project.Flutter\Github\flutter-desktop-embedding\example\windows\Runner.vcxproj]
[   +2 ms] D:\Project.Flutter\Github\flutter-desktop-embedding\example\windows\flutter\ephemeral\cpp_client_wrapper\include\flutter\flutter_view_controller.h(25): message : see declaration of 'flutter::FlutterViewController'
[D:\Project.Flutter\Github\flutter-desktop-embedding\example\windows\Runner.vcxproj]
[ +122 ms]   generated_plugin_registrant.cc
[ +268 ms]   Generating Code...
[  +86 ms] Done Building Project "D:\Project.Flutter\Github\flutter-desktop-embedding\example\windows\Runner.vcxproj" (default targets) -- FAILED.
[        ] Done Building Project "D:\Project.Flutter\Github\flutter-desktop-embedding\example\windows\Runner.vcxproj.metaproj" (default targets) -- FAILED.
[        ] Done Building Project "D:\Project.Flutter\Github\flutter-desktop-embedding\example\windows\Runner.sln" (default targets) -- FAILED.
[  +16 ms] Build FAILED.
[   +9 ms] "D:\Project.Flutter\Github\flutter-desktop-embedding\example\windows\Runner.sln" (default target) (1) ->
[        ] "D:\Project.Flutter\Github\flutter-desktop-embedding\example\windows\Runner.vcxproj.metaproj" (default target) (2) ->
[        ] "D:\Project.Flutter\Github\flutter-desktop-embedding\example\windows\Runner.vcxproj" (default target) (4) ->
[        ] (ClCompile target) ->
[        ]   D:\Project.Flutter\Github\flutter-desktop-embedding\example\windows\main.cpp(86,60): error C2039: 'GetNativeWindow': is not a member of 'flutter::FlutterViewController' [D:\Project.Flutter\Github\flutter-desktop-embedding\example\windows\Runner.vcxproj]
[        ]     0 Warning(s)
[        ]     1 Error(s)
[        ] Time Elapsed 00:00:12.69
[  +52 ms] Building Windows application... (completed in 13.9s)
[  +34 ms] "flutter run" took 14,385ms.
Build process failed. To view the stack trace, please run `flutter run -d windows -v`.

#0      throwToolExit (package:flutter_tools/src/base/common.dart:27:3)
#1      buildWindows (package:flutter_tools/src/windows/build_windows.dart:88:5)
<asynchronous suspension>
#2      WindowsDevice.buildForDevice (package:flutter_tools/src/windows/windows_device.dart:46:11)
#3      DesktopDevice.startApp (package:flutter_tools/src/desktop_device.dart:86:13)
#4      FlutterDevice.runHot (package:flutter_tools/src/resident_runner.dart:434:54)
<asynchronous suspension>
#5      HotRunner.run (package:flutter_tools/src/run_hot.dart:333:39)
#6      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:555:37)
<asynchronous suspension>
#7      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:637:18)
#8      _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:75:64)
#9      _rootRunUnary (dart:async/zone.dart:1134:38)
#10     _CustomZone.runUnary (dart:async/zone.dart:1031:19)
#11     _FutureListener.handleValue (dart:async/future_impl.dart:140:18)
#12     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:682:45)
#13     Future._propagateToListeners (dart:async/future_impl.dart:711:32)
#14     Future._completeWithValue (dart:async/future_impl.dart:526:5)
#15     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:34:15)
#16     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:293:13)
#17     RunCommand.usageValues (package:flutter_tools/src/commands/run.dart)
#18     _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:75:64)
#19     _rootRunUnary (dart:async/zone.dart:1134:38)
#20     _CustomZone.runUnary (dart:async/zone.dart:1031:19)
#21     _FutureListener.handleValue (dart:async/future_impl.dart:140:18)
#22     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:682:45)
#23     Future._propagateToListeners (dart:async/future_impl.dart:711:32)
#24     Future._completeWithValue (dart:async/future_impl.dart:526:5)
#25     Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:556:7)
#26     _rootRun (dart:async/zone.dart:1126:13)
#27     _CustomZone.run (dart:async/zone.dart:1023:19)
#28     _CustomZone.runGuarded (dart:async/zone.dart:925:7)
#29     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:965:23)
#31     _startMicrotaskLoop (dart:async/schedule_microtask.dart:52:5)
#32     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
#33     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:175:5)
```
</details>

<details>
  <summary>
flutter doctor -v
</summary>

```
[√] Flutter (Channel master, v1.13.10-pre.64, on Microsoft Windows [Version 10.0.18363.592], locale en-US)
    • Flutter version 1.13.10-pre.64 at D:\Program_Files\flutter
    • Framework revision 72561cd41b (33 hours ago), 2020-01-14 22:14:05 -0500
    • Engine revision bc41ab5139
    • Dart version 2.8.0 (build 2.8.0-dev.1.0 fe666ce592)

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at D:\Program_Files\Android\AndroidSDK
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • ANDROID_HOME = D:\Program_Files\Android\AndroidSDK
    • Java binary at: D:\Program_Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise
    • Visual Studio Enterprise 2019 version 16.4.29613.14

[!] Android Studio (version 3.5)
    • Android Studio at D:\Program_Files\Android\Android Studio
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)

[!] IntelliJ IDEA Community Edition (version 2018.2)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2018.2.3
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.dev/intellij-setup/#installing-the-plugins

[√] VS Code, 64-bit edition (version 1.41.1)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Flutter extension version 3.7.1

[√] Connected device (3 available)
    • Windows    • Windows    • windows-x64    • Microsoft Windows [Version 10.0.18363.592]
    • Chrome     • chrome     • web-javascript • Google Chrome 79.0.3945.117
    • Web Server • web-server • web-javascript • Flutter Tools

! Doctor found issues in 2 categories.
```

</details>

**Comment by stuartmorgan** [comment]
Your flutter-desktop-embedding checkout is too old, and doesn't contain https://github.com/google/flutter-desktop-embedding/pull/634

As the FDE readme says:
> This project is closely tied to changes in the Flutter repository, so you must be on the latest version of the Flutter master channel. You should always update this repository and Flutter at the same time, as breaking changes for desktop happen frequently.
