### ISSUE TITLE
flutter listen fails on Mac OS X

### ISSUE THREAD

**Issue by IvBaranov** [flutter/flutter#49]
* OS X
* fswatch installed
* moto x. android 5.1

1. cd into hello world app directory
2. start the hello world app with `flutter start --checked`
3. start listen with `flutter listen --checked`

adb log:
```
11-07 13:08:49.544 30092-30092/? D/AndroidRuntime: >>>>>> START com.android.internal.os.RuntimeInit uid 2000 <<<<<<
11-07 13:08:49.547 30092-30092/? D/AndroidRuntime: CheckJNI is OFF
11-07 13:08:49.590 30092-30092/? E/cutils-trace: Error opening trace file: Permission denied (13)
11-07 13:08:49.668 30092-30092/? D/AndroidRuntime: Calling main entry com.android.commands.am.Am
11-07 13:08:49.676 925-1403/? I/ActivityManager: START u0 {act=android.intent.action.VIEW dat=http://localhost:9888/lib/main.dart?rand=0.8416346927957559 flg=0x10000000 cmp=org.domokit.sky.shell/.SkyActivity (has extras)} from uid 2000 on display 0
11-07 13:08:49.685 925-1403/? V/WindowManager: addAppToken: AppWindowToken{28a1d68a token=Token{29fbf8f5 ActivityRecord{976c62c u0 org.domokit.sky.shell/.SkyActivity t2424}}} to stack=1 task=2424 at 1
11-07 13:08:49.690 30092-30092/? D/AndroidRuntime: Shutting down VM
11-07 13:08:49.723 925-3947/? V/WindowManager: Adding window Window{1b5b85d7 u0 org.domokit.sky.shell/org.domokit.sky.shell.SkyActivity} at 13 of 19 (after Window{31ae72a6 u0 org.domokit.sky.shell/org.domokit.sky.shell.SkyActivity})
11-07 13:08:49.774 925-939/? V/WindowManager: Adding window Window{3af751ad u0 SurfaceView} at 13 of 20 (before Window{1b5b85d7 u0 org.domokit.sky.shell/org.domokit.sky.shell.SkyActivity})
11-07 13:08:49.781 30037-30037/? W/art: Attempt to remove local handle scope entry from IRT, ignoring
11-07 13:08:49.808 1362-1362/? I/Keyboard.Facilitator: onFinishInput()
11-07 13:08:49.818 925-949/? I/LaunchCheckinHandler: Displayed org.domokit.sky.shell/.SkyActivity,wp,ca,128
11-07 13:08:49.818 925-949/? I/ActivityManager: Displayed org.domokit.sky.shell/.SkyActivity: +128ms
11-07 13:08:49.848 30037-30110/? W/UrlLoaderImpl: Network failure loading http://localhost:9888/lib/main.dart?rand=0.8416346927957559
11-07 13:08:49.850 30037-30058/? E/chromium: [ERROR:dart_library_loader.cc(299)] Library Load failed: http://localhost:9888/lib/main.dart?rand=0.8416346927957559
11-07 13:08:49.874 30037-30058/? E/chromium: [ERROR:dart_error.cc(16)] Dart_LookupLibrary: library 'http://localhost:9888/lib/main.dart?rand=0.8416346927957559' not found.
11-07 13:08:49.924 925-1097/? W/InputDispatcher: channel '31ae72a6 org.domokit.sky.shell/org.domokit.sky.shell.SkyActivity (server)' ~ Consumer closed input channel or an error occurred.  events=0x9
11-07 13:08:49.924 925-1097/? E/InputDispatcher: channel '31ae72a6 org.domokit.sky.shell/org.domokit.sky.shell.SkyActivity (server)' ~ Channel is unrecoverably broken and will be disposed!
11-07 13:08:49.924 925-1097/? W/InputDispatcher: channel '1b5b85d7 org.domokit.sky.shell/org.domokit.sky.shell.SkyActivity (server)' ~ Consumer closed input channel or an error occurred.  events=0x9
11-07 13:08:49.924 925-1097/? E/InputDispatcher: channel '1b5b85d7 org.domokit.sky.shell/org.domokit.sky.shell.SkyActivity (server)' ~ Channel is unrecoverably broken and will be disposed!
11-07 13:08:49.963 270-270/? I/Zygote: Process 30037 exited cleanly (1)
11-07 13:08:49.985 925-4769/? I/WindowState: WIN DEATH: Window{3e6cf894 u0 SurfaceView}
11-07 13:08:50.005 925-3947/? W/WindowManager: Failed looking up window
                                               java.lang.IllegalArgumentException: Requested window android.os.BinderProxy@209994e7 does not exist
                                                   at com.android.server.wm.WindowManagerService.windowForClientLocked(WindowManagerService.java:8594)
                                                   at com.android.server.wm.WindowManagerService.windowForClientLocked(WindowManagerService.java:8585)
                                                   at com.android.server.wm.WindowManagerService.relayoutWindow(WindowManagerService.java:3040)
                                                   at com.android.server.wm.Session.relayout(Session.java:197)
                                                   at android.view.IWindowSession$Stub.onTransact(IWindowSession.java:273)
                                                   at com.android.server.wm.Session.onTransact(Session.java:130)
                                                   at android.os.Binder.execTransact(Binder.java:446)
11-07 13:08:50.006 925-1647/? I/WindowState: WIN DEATH: Window{1b5b85d7 u0 org.domokit.sky.shell/org.domokit.sky.shell.SkyActivity}
11-07 13:08:50.006 925-1647/? W/InputDispatcher: Attempted to unregister already unregistered input channel '1b5b85d7 org.domokit.sky.shell/org.domokit.sky.shell.SkyActivity (server)'
11-07 13:08:50.006 925-1647/? W/WindowManager: Force-removing child win Window{3af751ad u0 SurfaceView} from container Window{1b5b85d7 u0 org.domokit.sky.shell/org.domokit.sky.shell.SkyActivity}
11-07 13:08:50.014 925-939/? W/WindowManager: Failed looking up window
                                              java.lang.IllegalArgumentException: Requested window android.os.BinderProxy@2409aec4 does not exist
                                                  at com.android.server.wm.WindowManagerService.windowForClientLocked(WindowManagerService.java:8594)
                                                  at com.android.server.wm.WindowManagerService.windowForClientLocked(WindowManagerService.java:8585)
                                                  at com.android.server.wm.WindowState$DeathRecipient.binderDied(WindowState.java:1152)
                                                  at android.os.BinderProxy.sendDeathNotice(Binder.java:551)
11-07 13:08:50.014 925-939/? I/WindowState: WIN DEATH: null
11-07 13:08:50.014 925-1403/? I/WindowState: WIN DEATH: Window{31ae72a6 u0 org.domokit.sky.shell/org.domokit.sky.shell.SkyActivity}
11-07 13:08:50.014 925-1403/? W/InputDispatcher: Attempted to unregister already unregistered input channel '31ae72a6 org.domokit.sky.shell/org.domokit.sky.shell.SkyActivity (server)'
11-07 13:08:50.042 925-4909/? I/ActivityManager: Process org.domokit.sky.shell (pid 30037) has died
11-07 13:08:50.044 925-4909/? W/ActivityManager: Force removing ActivityRecord{976c62c u0 org.domokit.sky.shell/.SkyActivity t2424}: app died, no saved state
11-07 13:08:50.044 925-4909/? W/ActivityManager: Force removing ActivityRecord{3ee01ff6 u0 org.domokit.sky.shell/.SkyActivity t2424}: app died, no saved state
```

**Comment by abarth** [comment]
@chinmaygarde We should think about the dev workflow we want on iOS now that we have precompilation.  I believe `flutter` tool still uses the ARM simulator.

**Comment by IvBaranov** [comment]
I meant OS X as operation system, not iOS.
Why platform-ios tag?

**Comment by abarth** [comment]
@IvBaranov Oh, sorry.  I misread the bug report.  Hopefully fixed the title and tags.

**Comment by abarth** [comment]
Now that I read what you've written more closely, I believe I've fixed this issue already.  The fix should be in the next release, which should happen on Monday.  Thanks!
