### ISSUE TITLE
Airplane mode restart the app Android

### ISSUE THREAD

**Issue by amorenew** [flutter/flutter#49057]
Airplane mode toggle off restart the app
## Steps to Reproduce
1-Download Flutter gallery or any flutter app on play store.
2-Go to second page or any page just to see restart effect later.
3-Slide the top notification and make Airplane mode on.
4-Wait a seconds then Slide again and make Airplane off.
5-Wait 10 seconds you will go to the first page again.

Use a real device, not an emulator.

Flutter version Any I tried with the master branch too

**Comment by Zazo032** [comment]
Couldn't reproduce the issue, could you provide a video showing how to reproduce it? Also, in which device and OS version are you facing this issue?

**Comment by dnfield** [comment]
Can you also share logs during the crash?

**Comment by amorenew** [comment]
@Zazo032 
The video of Flutter gallery on Playstore
My phone is Android 5.1 Huawei Y6 Pro
Tested on Android 7 too.
[device-2020-01-17-193148.zip](https://github.com/flutter/flutter/files/4077493/device-2020-01-17-193148.zip)

**Comment by amorenew** [comment]
@dnfield No crash actually I spent a full working day to figure out what is the issue but Logs in VS or AS didn't help me.
but I think it may be related to issue W/art: Native thread exiting without having called DetachCurrentThread (maybe it's going to use a pthread_key_create destructor?)
https://github.com/flutter/flutter/issues/29757

**Comment by amorenew** [comment]
It will never happen on the emulator I tried AS emulator and genymotion.
It didn't happen on Android 8 or powerful devices.
Happened on my Huawei 5.1 y 6 pro.

**Comment by amorenew** [comment]
Toggle Airplane mode makes it but Toggle Wifi didn't make it.

**Comment by dnfield** [comment]
Can you share the output of adb logcat during the run?

**Comment by jonahwilliams** [comment]
Sounds like something is missing in your android manifest for: https://developer.android.com/guide/topics/manifest/activity-element#config

**Comment by amorenew** [comment]
@dnfield  
Logs between aireplane on and off
@jonahwilliams 
I think manifest is ok

```
 <activity
            android:name="mydomain.MainActivity"
            android:configChanges="orientation|keyboardHidden|keyboard|screenSize|locale|layoutDirection|fontScale|screenLayout|density|uiMode"
            android:hardwareAccelerated="true"
            android:launchMode="singleTop"
            android:theme="@style/LaunchTheme"
            android:windowSoftInputMode="adjustResize">
```
```
01-17 20:38:23.137 22052-22052/ae.abudhabi.wathiq.supervisor D/MALI: eglDestroyContext:559: [MALI] eglDestroyContext display 0x7faa05f7c0, context 0x7f9d5a0940 here.
01-17 20:38:23.140 22052-22052/ae.abudhabi.wathiq.supervisor D/MALI: gles_context_delete:435: Destroy GLES ctx 0x7f9d5b3008 successfully
01-17 20:38:23.140 22052-22052/ae.abudhabi.wathiq.supervisor D/MALI: eglDestroyContext:559: [MALI] eglDestroyContext display 0x7faa05f7c0, context 0x7fa31aff80 here.
01-17 20:38:23.142 22052-22052/ae.abudhabi.wathiq.supervisor D/MALI: gles_context_delete:435: Destroy GLES ctx 0x7fa31de008 successfully
01-17 20:38:23.142 22052-22052/ae.abudhabi.wathiq.supervisor D/Surface: Surface::disconnect(this=0x7faa229e00,api=1)
01-17 20:38:23.142 22052-22052/ae.abudhabi.wathiq.supervisor D/GraphicBuffer: unregister, handle(0x7f846d2c40) (w:720 h:1184 s:720 f:0x1 u:0x000b00)
01-17 20:38:23.143 22052-22052/ae.abudhabi.wathiq.supervisor D/GraphicBuffer: unregister, handle(0x7f846d2b00) (w:720 h:1184 s:720 f:0x1 u:0x000b00)
01-17 20:38:23.143 22052-22052/ae.abudhabi.wathiq.supervisor D/GraphicBuffer: unregister, handle(0x7f820be420) (w:720 h:1184 s:720 f:0x1 u:0x000b00)
01-17 20:38:23.149 22052-22190/ae.abudhabi.wathiq.supervisor W/art: Native thread exiting without having called DetachCurrentThread (maybe it's going to use a pthread_key_create destructor?): Thread[18,tid=22190,Native,Thread*=0x7faa0ab000,peer=0x12f421c0,"Thread-6580"]
01-17 20:38:23.184 22052-22219/ae.abudhabi.wathiq.supervisor D/OpenGLRenderer: Flushing caches (mode 0)
01-17 20:38:23.187 22052-22219/ae.abudhabi.wathiq.supervisor D/Surface: Surface::disconnect(this=0x7faa229000,api=1)
01-17 20:38:23.187 22052-22219/ae.abudhabi.wathiq.supervisor D/GraphicBuffer: unregister, handle(0x7fa33785c0) (w:720 h:1280 s:720 f:0x1 u:0x000b00)
01-17 20:38:23.187 22052-22219/ae.abudhabi.wathiq.supervisor D/GraphicBuffer: unregister, handle(0x7f9d53a020) (w:720 h:1280 s:720 f:0x1 u:0x000b00)
01-17 20:38:23.188 22052-22219/ae.abudhabi.wathiq.supervisor D/GraphicBuffer: unregister, handle(0x7fa33b8a20) (w:720 h:1280 s:720 f:0x1 u:0x000b00)
01-17 20:38:23.193 22052-22219/ae.abudhabi.wathiq.supervisor D/OpenGLRenderer: Flushing caches (mode 0)
01-17 20:38:23.263 22052-22052/ae.abudhabi.wathiq.supervisor D/MALI: eglCreateContext:206: [MALI] eglCreateContext display 0x7faa05f7c0, share context 0x0 here.
01-17 20:38:23.264 22052-22052/ae.abudhabi.wathiq.supervisor D/MALI: gles_context_new:248: Create GLES ctx 0x7fa31de008 successfully
01-17 20:38:23.264 22052-22052/ae.abudhabi.wathiq.supervisor D/MALI: eglCreateContext:543: [MALI] eglCreateContext end. Created context 0x7fa3251f50 here.
01-17 20:38:23.460 22052-22052/ae.abudhabi.wathiq.supervisor V/PhoneWindow: DecorView setVisiblity: visibility = 4 ,Parent =null, this =com.android.internal.policy.impl.PhoneWindow$DecorView{1123cf8d I.E..... R.....ID 0,0-0,0}
01-17 20:38:23.464 22052-22052/ae.abudhabi.wathiq.supervisor D/ViewRootImpl: hardware acceleration is enabled, this = ViewRoot{1a077a9a ae.abudhabi.wathiq.supervisor/ae.abudhabi.wathiq.supervisor.MainActivity,ident = 1}
01-17 20:38:23.473 22052-22052/ae.abudhabi.wathiq.supervisor V/PhoneWindow: DecorView setVisiblity: visibility = 0 ,Parent =ViewRoot{1a077a9a ae.abudhabi.wathiq.supervisor/ae.abudhabi.wathiq.supervisor.MainActivity,ident = 1}, this =com.android.internal.policy.impl.PhoneWindow$DecorView{1123cf8d V.E..... R.....ID 0,0-0,0}
01-17 20:38:24.393 22052-22052/ae.abudhabi.wathiq.supervisor D/MALI: eglDestroyContext:559: [MALI] eglDestroyContext display 0x7faa05f7c0, context 0x7fa3251f50 here.
01-17 20:38:24.394 22052-22052/ae.abudhabi.wathiq.supervisor D/MALI: gles_context_delete:435: Destroy GLES ctx 0x7fa31de008 successfully
01-17 20:38:24.397 22052-23335/ae.abudhabi.wathiq.supervisor W/art: Native thread exiting without having called DetachCurrentThread (maybe it's going to use a pthread_key_create destructor?): Thread[18,tid=23335,Native,Thread*=0x7faa0a7800,peer=0x12fa20a0,"Thread-6581"]
01-17 20:38:24.399 22052-22219/ae.abudhabi.wathiq.supervisor D/OpenGLRenderer: Flushing caches (mode 0)
01-17 20:38:24.399 22052-22219/ae.abudhabi.wathiq.supervisor D/OpenGLRenderer: Flushing caches (mode 0)
01-17 20:38:24.619 22052-22052/ae.abudhabi.wathiq.supervisor D/MALI: eglCreateContext:206: [MALI] eglCreateContext display 0x7faa05f7c0, share context 0x0 here.
01-17 20:38:24.619 22052-22052/ae.abudhabi.wathiq.supervisor D/MALI: gles_context_new:248: Create GLES ctx 0x7fa31de008 successfully
01-17 20:38:24.619 22052-22052/ae.abudhabi.wathiq.supervisor D/MALI: eglCreateContext:543: [MALI] eglCreateContext end. Created context 0x7fa3251f50 here.
01-17 20:38:24.891 22052-22052/ae.abudhabi.wathiq.supervisor V/PhoneWindow: DecorView setVisiblity: visibility = 4 ,Parent =null, this =com.android.internal.policy.impl.PhoneWindow$DecorView{324eed43 I.E..... R.....ID 0,0-0,0}
01-17 20:38:24.955 22052-22052/ae.abudhabi.wathiq.supervisor D/ViewRootImpl: hardware acceleration is enabled, this = ViewRoot{2219a7b5 ae.abudhabi.wathiq.supervisor/ae.abudhabi.wathiq.supervisor.MainActivity,ident = 2}
01-17 20:38:25.113 22052-22052/ae.abudhabi.wathiq.supervisor V/PhoneWindow: DecorView setVisiblity: visibility = 0 ,Parent =ViewRoot{2219a7b5 ae.abudhabi.wathiq.supervisor/ae.abudhabi.wathiq.supervisor.MainActivity,ident = 2}, this =com.android.internal.policy.impl.PhoneWindow$DecorView{324eed43 V.E..... R.....ID 0,0-0,0}
01-17 20:38:25.172 22052-22219/ae.abudhabi.wathiq.supervisor D/OpenGLRenderer: CanvasContext() 0x7fa3028340 initialize 0x7faa229010
01-17 20:38:25.172 22052-22219/ae.abudhabi.wathiq.supervisor D/Surface: Surface::connect(this=0x7faa229000,api=1)
01-17 20:38:25.191 22052-22219/ae.abudhabi.wathiq.supervisor D/mali_winsys: new_window_surface returns 0x3000
01-17 20:38:25.191 22052-22219/ae.abudhabi.wathiq.supervisor D/Surface: Surface::allocateBuffers(this=0x7faa229000)
01-17 20:38:25.253 22052-23382/ae.abudhabi.wathiq.supervisor D/MALI: eglCreateContext:206: [MALI] eglCreateContext display 0x7faa05f7c0, share context 0x7fa3251f50 here.
01-17 20:38:25.254 22052-23382/ae.abudhabi.wathiq.supervisor D/MALI: gles_context_new:248: Create GLES ctx 0x7f9d5b3008 successfully
01-17 20:38:25.254 22052-23382/ae.abudhabi.wathiq.supervisor D/MALI: eglCreateContext:543: [MALI] eglCreateContext end. Created context 0x7f9d637f60 here.
01-17 20:38:25.257 22052-23382/ae.abudhabi.wathiq.supervisor D/Surface: Surface::connect(this=0x7faa22e400,api=1)
01-17 20:38:25.258 22052-23382/ae.abudhabi.wathiq.supervisor D/mali_winsys: new_window_surface returns 0x3000
01-17 20:38:25.862 22052-22219/ae.abudhabi.wathiq.supervisor D/GraphicBuffer: register, handle(0x7f820bd0c0) (w:720 h:1280 s:720 f:0x1 u:0x000b00)
01-17 20:38:25.884 22052-22219/ae.abudhabi.wathiq.supervisor D/GraphicBuffer: register, handle(0x7f89be5880) (w:720 h:1280 s:720 f:0x1 u:0x000b00)
01-17 20:38:28.898 22052-22219/ae.abudhabi.wathiq.supervisor D/GraphicBuffer: register, handle(0x7f820beec0) (w:720 h:1280 s:720 f:0x1 u:0x000b00)
01-17 20:38:33.046 22052-23382/ae.abudhabi.wathiq.supervisor D/GraphicBuffer: register, handle(0x7f88bd22e0) (w:720 h:1184 s:720 f:0x1 u:0x000b00)
01-17 20:38:33.206 22052-22219/ae.abudhabi.wathiq.supervisor W/MALI: glDrawArrays:714: [MALI] glDrawArrays takes more than 5ms here. Total elapse time(us): 5940
01-17 20:38:33.341 22052-22219/ae.abudhabi.wathiq.supervisor W/MALI: glDrawArrays:714: [MALI] glDrawArrays takes more than 5ms here. Total elapse time(us): 5866
01-17 20:38:33.398 22052-23382/ae.abudhabi.wathiq.supervisor D/GraphicBuffer: register, handle(0x7f89a40d80) (w:720 h:1184 s:720 f:0x1 u:0x000b00)
01-17 20:38:33.447 22052-23382/ae.abudhabi.wathiq.supervisor D/GraphicBuffer: register, handle(0x7f89978840) (w:720 h:1184 s:720 f:0x1 u:0x000b00)
01-17 20:38:34.940 22052-23381/ae.abudhabi.wathiq.supervisor I/flutter: LoginBloc Transition>>Transition { currentState: LoginInitialState, event: LoginAutoEvent, nextState: LoginLoadingState }
01-17 20:38:35.009 22052-23381/ae.abudhabi.wathiq.supervisor I/flutter: LoginBloc Transition>>Transition { currentState: LoginLoadingState, event: LoginAutoEvent, nextState: LoginFailedState }
01-17 20:38:36.555 22052-23381/ae.abudhabi.wathiq.supervisor I/flutter: d

```

**Comment by dnfield** [comment]
It looks like you're missing some of the logs :)  The last line of that log looks truncated, and I'd expect to see more lines after it.

**Comment by amorenew** [comment]
@dnfield Full video here
With my Huawei version in logcat and Flutter:d at the end
Try Android 7 or less and it is better to be 2 gb ram or less
[Untitled2.zip](https://github.com/flutter/flutter/files/4078302/Untitled2.zip)

**Comment by dnfield** [comment]
Instead of using AndroidStudio to do it, which is probably cutting out the logging as soon as it sees your app has died, run `adb logcat` from the command line.  Alternatively, try changing the drop down on `show only selected application` to the option for showing all logs.

**Comment by amorenew** [comment]
@dnfield 8000 lines that are
[logs.txt](https://github.com/flutter/flutter/files/4078447/logs.txt)
 why I filter by my app only real device has a lot of logs

**Comment by dnfield** [comment]
The only thing I can see in there that makes any sense for a crash is 
```
3402 01-17 22:55:26.160 838-1579/? D/WifiService: getWifiServiceMessenger, pid:25288, uid:10024
3403 01-17 22:55:26.160 838-1579/? W/System.err: java.lang.SecurityException: WifiService: Neither user 10024 nor current process has android.permission.CHANGE_WIFI_STATE.
3404 01-17 22:55:26.160 838-1579/? W/System.err:     at android.app.ContextImpl.enforce(ContextImpl.java:2061)
3405 01-17 22:55:26.160 838-1579/? W/System.err:     at android.app.ContextImpl.enforceCallingOrSelfPermission(ContextImpl.java:2090)
3406 01-17 22:55:26.160 838-1579/? W/System.err:     at com.android.server.wifi.WifiServiceImpl.enforceChangePermission(WifiServiceImpl.java:751)
3407 01-17 22:55:26.160 838-1579/? W/System.err:     at com.android.server.wifi.WifiServiceImpl.getWifiServiceMessenger(WifiServiceImpl.java:1511)
3408 01-17 22:55:26.160 838-1579/? W/System.err:     at android.net.wifi.IWifiManager$Stub.onTransact(IWifiManager.java:483)
3409 01-17 22:55:26.160 838-1579/? W/System.err:     at android.os.Binder.execTransact(Binder.java:451)
```

Is your app using a plugin that tries to change wifi state? I believe Flutter Gallery does (connectivity), which could explain a crash, but haven't tested that myself.

Also, your new log doesn't seem to have any output from flutter at all.  Are you sure it was running when the Flutter app was running?

**Comment by amorenew** [comment]
@dnfield I made a new flutter project and it happened too
I found the issue I removed the sim card and tried again but no app restart

> The fix was removing the SIM card from the device completely.
quote from https://github.com/flutter/flutter/issues/29757

So this issue is duplicate of https://github.com/flutter/flutter/issues/29757 or I should leave it open?

**Comment by dnfield** [comment]
That is very strange :)  That issue is very vague.  If you really believe this is a dupe we can close it, but it's hard to tell from either issue right now what code is actually causing the crash.

**Comment by amorenew** [comment]
@joshuaferguson @matthew-carroll
 is this a duplicate of issue https://github.com/flutter/flutter/issues/29757?

**Comment by amorenew** [comment]
@dnfield more details
I found that with 1 sim card no issue
It only happens with 2 sim cards. My Huawei y6 pro has 2 sim cards Etisalat and Vodafone
So my guess Turning On 2 sim card is an expensive memory process on old devices.

**Comment by amorenew** [comment]
@dnfield I tried youtube native app and the same happen so it is not Flutter issue.
As it is a memory issue so I will close it. I hope when Flutter faces a memory issue it restart to the same dart page, not Activity.

**Comment by amreniouinnovent** [comment]
@dnfield One more thing can at least we get a proper crash error when we get out of memory

**Comment by dnfield** [comment]
OOM is a tricky one. Does YouTube give you a better stack trace when it dies than a Flutter app?

**Comment by amreniouinnovent** [comment]
@dnfield No, useless logs
but it is not important that much.No customer will use Airplane mode in my case mostly.
so no need to investigate more except if others want to the same dart page after activity recreated.

**Comment by dnfield** [comment]
You'll want to follow https://github.com/flutter/flutter/issues/6827

You may also want to file an upstream Android bug about your case.  It sounds like a bug in Android.

**Comment by amreniouinnovent** [comment]
@dnfield cool, it is mentioned there that save state is the 4th most requested feature.
