### ISSUE TITLE
flutter build APK crashes with "Bad CPU type in executable"

### ISSUE THREAD

**Issue by Waye** [flutter/flutter#49137]
weiyihu@weiyihus-MacBook-Pro xishuipang-android-app % flutter build apk
Initializing gradle...                                              0.7s
Resolving dependencies...                                           1.5s
                                                                        
Oops; flutter has exited unexpectedly.                                  
Crash report written to /Users/weiyihu/StudioProjects/xishuipang-android-app/flutter_08.log;
please let us know at https://github.com/flutter/flutter/issues.        
Running Gradle task 'assembleRelease'...                                
Running Gradle task 'assembleRelease'... Done                       9.0s
Gradle task assembleRelease failed with exit code 1

Flutter crash report; please file at https://github.com/flutter/flutter/issues.

## command

flutter build aot --suppress-analytics --quiet --target lib/main.dart --target-platform android-arm --output-dir /Users/weiyihu/StudioProjects/xishuipang-android-app/build/app/intermediates/flutter/release --target-platform android-arm --release

## exception

ProcessException: ProcessException: Bad CPU type in executable
  Command: /Users/weiyihu/Documents/flutter/bin/cache/artifacts/engine/android-arm-release/darwin-x64/gen_snapshot --causal_async_stacks --deterministic --snapshot_kind=app-aot-blobs --vm_snapshot_data=/Users/weiyihu/StudioProjects/xishuipang-android-app/build/app/intermediates/flutter/release/vm_snapshot_data --isolate_snapshot_data=/Users/weiyihu/StudioProjects/xishuipang-android-app/build/app/intermediates/flutter/release/isolate_snapshot_data --vm_snapshot_instructions=/Users/weiyihu/StudioProjects/xishuipang-android-app/build/app/intermediates/flutter/release/vm_snapshot_instr --isolate_snapshot_instructions=/Users/weiyihu/StudioProjects/xishuipang-android-app/build/app/intermediates/flutter/release/isolate_snapshot_instr --no-sim-use-hardfp --no-use-integer-division /Users/weiyihu/StudioProjects/xishuipang-android-app/build/app/intermediates/flutter/release/app.dill

```
#0      runCommandAndStreamOutput (package:flutter_tools/src/base/process.dart:142:27)
<asynchronous suspension>
#1      GenSnapshot.run (package:flutter_tools/src/base/build.dart:68:12)
#2      AOTSnapshotter.build.<anonymous closure> (package:flutter_tools/src/base/build.dart:207:88)
#3      AOTSnapshotter._timedStep (package:flutter_tools/src/base/build.dart:363:33)
<asynchronous suspension>
#4      AOTSnapshotter.build (package:flutter_tools/src/base/build.dart:207:43)
<asynchronous suspension>
#5      BuildAotCommand.runCommand (package:flutter_tools/src/commands/build_aot.dart:143:56)
<asynchronous suspension>
#6      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:559:18)
<asynchronous suspension>
#7      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:495:33)
<asynchronous suspension>
#8      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:142:29)
<asynchronous suspension>
#9      _rootRun (dart:async/zone.dart:1124:13)
#10     _CustomZone.run (dart:async/zone.dart:1021:19)
#11     _runZoned (dart:async/zone.dart:1516:10)
#12     runZoned (dart:async/zone.dart:1463:12)
#13     AppContext.run (package:flutter_tools/src/base/context.dart:141:18)
<asynchronous suspension>
#14     FlutterCommand.run (package:flutter_tools/src/runner/flutter_command.dart:486:20)
#15     CommandRunner.runCommand (package:args/command_runner.dart:196:27)
<asynchronous suspension>
#16     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:396:21)
<asynchronous suspension>
#17     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:142:29)
<asynchronous suspension>
#18     _rootRun (dart:async/zone.dart:1124:13)
#19     _CustomZone.run (dart:async/zone.dart:1021:19)
#20     _runZoned (dart:async/zone.dart:1516:10)
#21     runZoned (dart:async/zone.dart:1463:12)
#22     AppContext.run (package:flutter_tools/src/base/context.dart:141:18)
<asynchronous suspension>
#23     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:356:19)
<asynchronous suspension>
#24     CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:111:29)
#25     new Future.sync (dart:async/future.dart:224:31)
#26     CommandRunner.run (package:args/command_runner.dart:111:11)
#27     FlutterCommandRunner.run (package:flutter_tools/src/runner/flutter_command_runner.dart:242:18)
#28     run.<anonymous closure> (package:flutter_tools/runner.dart:60:20)
<asynchronous suspension>
#29     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:142:29)
<asynchronous suspension>
#30     _rootRun (dart:async/zone.dart:1124:13)
#31     _CustomZone.run (dart:async/zone.dart:1021:19)
#32     _runZoned (dart:async/zone.dart:1516:10)
#33     runZoned (dart:async/zone.dart:1463:12)
#34     AppContext.run (package:flutter_tools/src/base/context.dart:141:18)
<asynchronous suspension>
#35     runInContext (package:flutter_tools/src/context_runner.dart:50:24)
<asynchronous suspension>
#36     run (package:flutter_tools/runner.dart:51:10)
#37     main (package:flutter_tools/executable.dart:60:9)
<asynchronous suspension>
#38     main (file:///b/s/w/ir/k/archive/flutter/packages/flutter_tools/bin/flutter_tools.dart:8:3)
#39     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:298:32)
#40     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:171:12)
```

## flutter doctor

```
[!] Flutter (Channel beta, v1.5.4, on Mac OS X 10.15.2 19C57, locale en-CA)
    • Flutter version 1.5.4 at /Users/weiyihu/Documents/flutter
    • Framework revision b593f5167b (9 months ago), 2019-04-22 07:51:33 -0700
    • Engine revision ca31a7c57b
    • Dart version 2.3.0 (build 2.3.0-dev.0.1 cf4444b803)
    ✗ Downloaded executables cannot execute on host.
      See https://github.com/flutter/flutter/issues/6207 for more information


[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.1)
    • Android SDK at /Users/weiyihu/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.1
    • ANDROID_HOME = /Users/weiyihu/Library/Android/sdk
    • ANDROID_SDK_ROOT = /Users/weiyihu/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 11.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.3.1, Build version 11C504
    • ios-deploy 1.9.4
    • CocoaPods version 1.8.4

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 42.1.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] VS Code (version 1.41.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.7.1

[!] Connected device
    ! No devices available

! Doctor found issues in 2 categories.

**Comment by jonahwilliams** [comment]
Is there a particular reason you're on a 9 month old beta branch?

**Comment by Waye** [comment]
> Is there a particular reason you're on a 9 month old beta branch?
Hi Jonah,
I used the framework one year ago for a project, still, I am a student and don't really have time to update my code to the latest flutter version. If there is an incompatibility that can't fix, I will change my code later.

**Comment by jonahwilliams** [comment]
I understand, updating is definitely work and if you're busy there are probably other things you should worry about. That said, you are still on a beta branch instead of a stable branch, which is not a great choice if you don't plan to upgrade for many months at a time.

I believe particular error you've reported has been long since fixed, but we won't be able to patch such an old version. You might try switching to the stable channel release that is close in version number to your current version. This could be done by visiting https://flutter.dev/docs/development/tools/sdk/releases and picking a close version. Then you would be able to download this in addition to your current flutter checkout to see if it works

**Comment by Waye** [comment]
> I understand, updating is definitely work and if you're busy there are probably other things you should worry about. That said, you are still on a beta branch instead of a stable branch, which is not a great choice if you don't plan to upgrade for many months at a time.
> 
> I believe the particular error you've reported has been long since fixed, but we won't be able to patch such an old version. You might try switching to the stable channel release that is close in version number to your current version. This could be done by visiting https://flutter.dev/docs/development/tools/sdk/releases and picking a close version. Then you would be able to download this in addition to your current flutter checkout to see if it works

I tried  v1.5.4-hotfix.2 | 7a4c334 | 5/7/2019 at macos stable channel
-- | -- | --

Flutter crash report; please file at https://github.com/flutter/flutter/issues.

## command

flutter build aot --suppress-analytics --quiet --target lib/main.dart --target-platform android-arm --output-dir /Users/weiyihu/StudioProjects/xishuipang-android-app/build/app/intermediates/flutter/release --target-platform android-arm --release

## exception

ProcessException: ProcessException: Bad CPU type in executable
  Command: /Users/weiyihu/Documents/flutter/bin/cache/artifacts/engine/android-arm-release/darwin-x64/gen_snapshot --causal_async_stacks --deterministic --snapshot_kind=app-aot-blobs --vm_snapshot_data=/Users/weiyihu/StudioProjects/xishuipang-android-app/build/app/intermediates/flutter/release/vm_snapshot_data --isolate_snapshot_data=/Users/weiyihu/StudioProjects/xishuipang-android-app/build/app/intermediates/flutter/release/isolate_snapshot_data --vm_snapshot_instructions=/Users/weiyihu/StudioProjects/xishuipang-android-app/build/app/intermediates/flutter/release/vm_snapshot_instr --isolate_snapshot_instructions=/Users/weiyihu/StudioProjects/xishuipang-android-app/build/app/intermediates/flutter/release/isolate_snapshot_instr --no-sim-use-hardfp --no-use-integer-division /Users/weiyihu/StudioProjects/xishuipang-android-app/build/app/intermediates/flutter/release/app.dill

```
#0      runCommandAndStreamOutput (package:flutter_tools/src/base/process.dart:142:27)
<asynchronous suspension>
#1      GenSnapshot.run (package:flutter_tools/src/base/build.dart:68:12)
#2      AOTSnapshotter.build.<anonymous closure> (package:flutter_tools/src/base/build.dart:207:88)
#3      AOTSnapshotter._timedStep (package:flutter_tools/src/base/build.dart:363:33)
<asynchronous suspension>
#4      AOTSnapshotter.build (package:flutter_tools/src/base/build.dart:207:43)
<asynchronous suspension>
#5      BuildAotCommand.runCommand (package:flutter_tools/src/commands/build_aot.dart:143:56)
<asynchronous suspension>
#6      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:559:18)
<asynchronous suspension>
#7      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:495:33)
<asynchronous suspension>
#8      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:142:29)
<asynchronous suspension>
#9      _rootRun (dart:async/zone.dart:1124:13)
#10     _CustomZone.run (dart:async/zone.dart:1021:19)
#11     _runZoned (dart:async/zone.dart:1516:10)
#12     runZoned (dart:async/zone.dart:1463:12)
#13     AppContext.run (package:flutter_tools/src/base/context.dart:141:18)
<asynchronous suspension>
#14     FlutterCommand.run (package:flutter_tools/src/runner/flutter_command.dart:486:20)
#15     CommandRunner.runCommand (package:args/command_runner.dart:196:27)
<asynchronous suspension>
#16     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:396:21)
<asynchronous suspension>
#17     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:142:29)
<asynchronous suspension>
#18     _rootRun (dart:async/zone.dart:1124:13)
#19     _CustomZone.run (dart:async/zone.dart:1021:19)
#20     _runZoned (dart:async/zone.dart:1516:10)
#21     runZoned (dart:async/zone.dart:1463:12)
#22     AppContext.run (package:flutter_tools/src/base/context.dart:141:18)
<asynchronous suspension>
#23     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:356:19)
<asynchronous suspension>
#24     CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:111:29)
#25     new Future.sync (dart:async/future.dart:224:31)
#26     CommandRunner.run (package:args/command_runner.dart:111:11)
#27     FlutterCommandRunner.run (package:flutter_tools/src/runner/flutter_command_runner.dart:242:18)
#28     run.<anonymous closure> (package:flutter_tools/runner.dart:60:20)
<asynchronous suspension>
#29     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:142:29)
<asynchronous suspension>
#30     _rootRun (dart:async/zone.dart:1124:13)
#31     _CustomZone.run (dart:async/zone.dart:1021:19)
#32     _runZoned (dart:async/zone.dart:1516:10)
#33     runZoned (dart:async/zone.dart:1463:12)
#34     AppContext.run (package:flutter_tools/src/base/context.dart:141:18)
<asynchronous suspension>
#35     runInContext (package:flutter_tools/src/context_runner.dart:50:24)
<asynchronous suspension>
#36     run (package:flutter_tools/runner.dart:51:10)
#37     main (package:flutter_tools/executable.dart:60:9)
<asynchronous suspension>
#38     main (file:///b/s/w/ir/k/archive/flutter/packages/flutter_tools/bin/flutter_tools.dart:8:3)
#39     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:298:32)
#40     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:171:12)
```

## flutter doctor

```
[!] Flutter (Channel stable, v1.5.4-hotfix.2, on Mac OS X 10.15.2 19C57, locale en-CA)
    • Flutter version 1.5.4-hotfix.2 at /Users/weiyihu/Documents/flutter
    • Framework revision 7a4c33425d (9 months ago), 2019-04-29 11:05:24 -0700
    • Engine revision 52c7a1e849
    • Dart version 2.3.0 (build 2.3.0-dev.0.5 a1668566e5)
    ✗ Downloaded executables cannot execute on host.
      See https://github.com/flutter/flutter/issues/6207 for more information


[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.1)
    • Android SDK at /Users/weiyihu/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.1
    • ANDROID_HOME = /Users/weiyihu/Library/Android/sdk
    • ANDROID_SDK_ROOT = /Users/weiyihu/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 11.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.3.1, Build version 11C504
    • ios-deploy 1.9.4
    • CocoaPods version 1.8.4

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 42.1.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] VS Code (version 1.41.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.7.1

[✓] Connected device (1 available)
    • BLA AL00 • 5EF0217C01015013 • android-arm64 • Android 9 (API 28)

! Doctor found issues in 1 category.
```

**Comment by Waye** [comment]
https://github.com/flutter/flutter/issues/44597#issuecomment-552625147
Thank you, I get it. If you run Mac OS catalina, use Flutter stable OS v1.9.1
