### ISSUE TITLE
[flutter driver] driver.scroll not working for SingleChildScrollView within WillPopScope

### ISSUE THREAD

**Issue by Xavjer** [flutter/flutter#49141]
## Steps to Reproduce

1. Create the sample below with the test.
2. Run flutter drive --target=test_driver/app.dart

**Expected results:** 
The scrollView should scroll, but the scroll times out. Scrolling by using the ListTile byValueKey (shortText) works.

**Actual results:** 
Scroll times out.
I also tried this with various alternate find (ancestor / descendant), but only if the find returns the ListTile it will work.
Without the WillPopScope, the scrollview works as expected.

<details>
  <summary>Code</summary>

```
import 'dart:async';
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {

    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: WillPopScope(
        onWillPop: () {
          final Completer<bool> completer = new Completer<bool>();
          completer.complete(true);
          return completer.future;
        },
        child: Scaffold(
          appBar: AppBar(),
          body: SingleChildScrollView(
              key: ValueKey("detailScreenStateScrollView"),
              child: Column(children: [
                ListTile(key: ValueKey('shortText'), title: Text('Bla')),
                ListTile(title: Text('Bla')),
                ListTile(title: Text('Bla')),
                ListTile(title: Text('Bla')),
                ListTile(title: Text('Bla')),
                ListTile(title: Text('Bla')),
                ListTile(title: Text('Bla')),
                ListTile(title: Text('Bla')),
                ListTile(title: Text('Bla')),
                ListTile(title: Text('Bla')),
                ListTile(title: Text('Bla')),
                ListTile(title: Text('Bla')),
                ListTile(title: Text('Bla')),
                ListTile(title: Text('Bla')),
                ListTile(title: Text('Bla')),
                ListTile(title: Text('Bla')),
                ListTile(title: Text('Bla')),
                ListTile(title: Text('Bla')),
                ListTile(title: Text('Bla')),
                ListTile(title: Text('Bla'))
              ])
          )
      )
      )
    );
  }
}
```
```
    test('Test', () async {
      await driver.runUnsynchronized(() async {
        await driver.waitFor(find.byType('SingleChildScrollView'));

        final detailScreenStateScrollView = find.byValueKey('detailScreenStateScrollViewReport');
        final shortText = find.byValueKey('shortText');
        await driver.scroll(shortText, -3000.0, -3000.0, Duration(seconds: 5));
      });
    });
```

```
```

```
[✓] Flutter (Channel beta, v1.12.13+hotfix.6, on Mac OS X 10.14.5 18F132, locale en-CH)
    • Flutter version 1.12.13+hotfix.6 at /Users/c.wyss/Documents/Projects/flutter
    • Framework revision 18cd7a3601 (6 weeks ago), 2019-12-11 06:35:39 -0800
    • Engine revision 2994f7e1e6
    • Dart version 2.7.0


[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/c.wyss/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.3.1, Build version 11C504
    • CocoaPods version 1.8.4

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 3.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 32.0.1
    • Dart plugin version 182.5124
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)

[✓] IntelliJ IDEA Ultimate Edition (version 2019.3)
    • IntelliJ at /Users/c.wyss/Applications/JetBrains Toolbox/IntelliJ IDEA Ultimate.app
    • Flutter plugin version 41.1.5
    • Dart plugin version 193.5233.116

[✓] Connected device (3 available)
    • Android SDK built for x86 • emulator-5554 • android-x86    • Android 10 (API 29) (emulator)
    • Chrome                    • chrome        • web-javascript • Google Chrome 79.0.3945.130
    • Web Server                • web-server    • web-javascript • Flutter Tools

• No issues found!
```

</details>

**Comment by endritgojani** [comment]
you have to scroll in only one direction if you wanna scroll vertically use this
`await driver.scroll(shortText, 0, -3000.0, Duration(seconds: 5));
`
and if you wanna scroll horizontally use this
`await driver.scroll(shortText, -3000.0, 0, Duration(seconds: 5));
`

**Comment by Xavjer** [comment]
@endritgojani This has nothing to do with the issue described above, this was just a sample code. Behaviour does not change when scrolling only vertically or horizontally.

**Comment by TahaTesser** [comment]
<details> 
<summary>logs</summary> 

```bash
Starting application: test_driver/example.dart
"build/app/outputs/flutter-apk/app.apk" does not exist.
Running Gradle task 'assembleDebug'...                                  
Running Gradle task 'assembleDebug'... Done                        22.6s
✓ Built build/app/outputs/flutter-apk/app-debug.apk.
Installing build/app/outputs/flutter-apk/app.apk...                 4.4s
I/flutter (17591): Observatory listening on http://127.0.0.1:43091/2krBRfwsg4o=/
00:00 +0: (setUpAll)

VMServiceFlutterDriver: Connecting to Flutter application at http://127.0.0.1:52013/fPB_L-Lon_8=/
VMServiceFlutterDriver: Isolate found with number: 3151813448149699
VMServiceFlutterDriver: Isolate is paused at start.
VMServiceFlutterDriver: Attempting to resume isolate
VMServiceFlutterDriver: Connected to Flutter application.
00:01 +0: Test

VMServiceFlutterDriver: scroll message is taking a long time to complete...
I/flutter (17591): ══╡ EXCEPTION CAUGHT BY GESTURE ╞═══════════════════════════════════════════════════════════════════
I/flutter (17591): The following assertion was thrown while handling a gesture:
I/flutter (17591): A ticker was started twice.
I/flutter (17591): A ticker that is already active cannot be started again without first stopping it.
I/flutter (17591): The affected ticker was:
I/flutter (17591):   _WidgetTicker(created by _GlowingOverscrollIndicatorState#ba854(lifecycle state: created, tickers:
I/flutter (17591):   tracking 3 tickers))
I/flutter (17591):   The stack trace when the _WidgetTicker was actually created was:
I/flutter (17591):   #0      new Ticker.<anonymous closure> (package:flutter/src/scheduler/ticker.dart:67:40)
I/flutter (17591):   #1      new Ticker (package:flutter/src/scheduler/ticker.dart:69:6)
I/flutter (17591):   #2      new _WidgetTicker (package:flutter/src/widgets/ticker_provider.dart:271:81)
I/flutter (17591):   #3      TickerProviderStateMixin.createTicker
I/flutter (17591):   (package:flutter/src/widgets/ticker_provider.dart:202:34)
I/flutter (17591):   #4      new _GlowController (package:flutter/src/widgets/overscroll_indicator.dart:370:33)
I/flutter (17591):   #5      _GlowingOverscrollIndicatorState.initState
I/flutter (17591):   (package:flutter/src/widgets/overscroll_indicator.dart:227:27)
I/flutter (17591):   #6      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4778:57)
I/flutter (17591):   #7      ComponentElement.mount (package:flutter/src/widgets/framework.dart:4615:5)
I/flutter (17591):   ...     Normal element mounting (39 frames)
I/flutter (17591):   #46     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3581:14)
I/flutter (17591):   #47     MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6248:32)
I/flutter (17591):   ...     Normal element mounting (210 frames)
I/flutter (17591):   #257    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3581:14)
I/flutter (17591):   #258    MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6248:32)
I/flutter (17591):   ...     Normal element mounting (273 frames)
I/flutter (17591):   #531    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3581:14)
I/flutter (17591):   #532    Element.updateChild (package:flutter/src/widgets/framework.dart:3346:18)
I/flutter (17591):   #533    RenderObjectToWidgetElement._rebuild (package:flutter/src/widgets/binding.dart:1215:16)
I/flutter (17591):   #534    RenderObjectToWidgetElement.mount (package:flutter/src/widgets/binding.dart:1186:5)
I/flutter (17591):   #535    RenderObjectToWidgetAdapter.attachToRenderTree.<anonymous closure>
I/flutter (17591):   (package:flutter/src/widgets/binding.dart:1128:18)
I/flutter (17591):   #536    BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2696:19)
I/flutter (17591):   #537    RenderObjectToWidgetAdapter.attachToRenderTree
I/flutter (17591):   (package:flutter/src/widgets/binding.dart:1127:13)
I/flutter (17591):   #538    WidgetsBinding.attachRootWidget (package:flutter/src/widgets/binding.dart:967:7)
I/flutter (17591):   #539    WidgetsBinding.scheduleAttachRootWidget.<anonymous closure>
I/flutter (17591):   (package:flutter/src/widgets/binding.dart:948:7)
I/flutter (17591):   (elided 11 frames from class _RawReceivePortImpl, class _Timer, dart:async, and dart:async-patch)
I/flutter (17591): 
I/flutter (17591): When the exception was thrown, this was the stack:
I/flutter (17591): #0      Ticker.start.<anonymous closure> (package:flutter/src/scheduler/ticker.dart:151:9)
I/flutter (17591): #1      Ticker.start (package:flutter/src/scheduler/ticker.dart:158:6)
I/flutter (17591): #2      _GlowController.pull (package:flutter/src/widgets/overscroll_indicator.dart:480:29)
I/flutter (17591): #3      _GlowingOverscrollIndicatorState._handleScrollNotification
(package:flutter/src/widgets/overscroll_indicator.dart:302:29)
I/flutter (17591): #4      NotificationListener._dispatch (package:flutter/src/widgets/notification_listener.dart:131:42)
I/flutter (17591): #5      Notification.visitAncestor (package:flutter/src/widgets/notification_listener.dart:47:20)
I/flutter (17591): #6      ViewportNotificationMixin.visitAncestor
(package:flutter/src/widgets/scroll_notification.dart:31:18)
I/flutter (17591): #7      Element.visitAncestorElements (package:flutter/src/widgets/framework.dart:4112:39)
I/flutter (17591): #8      Notification.dispatch (package:flutter/src/widgets/notification_listener.dart:63:13)
I/flutter (17591): #9      DragScrollActivity.dispatchOverscrollNotification
(package:flutter/src/widgets/scroll_activity.dart:460:135)
I/flutter (17591): #10     ScrollPosition.didOverscrollBy (package:flutter/src/widgets/scroll_position.dart:858:15)
I/flutter (17591): #11     ScrollPosition.setPixels (package:flutter/src/widgets/scroll_position.dart:280:9)
I/flutter (17591): #12     ScrollPositionWithSingleContext.setPixels
(package:flutter/src/widgets/scroll_position_with_single_context.dart:81:18)
I/flutter (17591): #13     ScrollPositionWithSingleContext.applyUserOffset
(package:flutter/src/widgets/scroll_position_with_single_context.dart:123:5)
I/flutter (17591): #14     ScrollDragController.update (package:flutter/src/widgets/scroll_activity.dart:382:14)
I/flutter (17591): #15     ScrollableState._handleDragUpdate (package:flutter/src/widgets/scrollable.dart:587:12)
I/flutter (17591): #16     DragGestureRecognizer._checkUpdate.<anonymous closure>
(package:flutter/src/gestures/monodrag.dart:431:55)
I/flutter (17591): #17     GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:183:24)
I/flutter (17591): #18     DragGestureRecognizer._checkUpdate (package:flutter/src/gestures/monodrag.dart:431:7)
I/flutter (17591): #19     DragGestureRecognizer.handleEvent (package:flutter/src/gestures/monodrag.dart:286:9)
I/flutter (17591): #20     PointerRouter._dispatch (package:flutter/src/gestures/pointer_router.dart:77:12)
I/flutter (17591): #21     PointerRouter._dispatchEventToRoutes.<anonymous closure>
(package:flutter/src/gestures/pointer_router.dart:122:9)
I/flutter (17591): #22     _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:377:8)
I/flutter (17591): #23     PointerRouter._dispatchEventToRoutes (package:flutter/src/gestures/pointer_router.dart:120:18)
I/flutter (17591): #24     PointerRouter.route (package:flutter/src/gestures/pointer_router.dart:106:7)
I/flutter (17591): #25     GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:370:19)
I/flutter (17591): #26     GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:350:22)
I/flutter (17591): #27     RendererBinding.dispatchEvent (package:flutter/src/rendering/binding.dart:269:11)
I/flutter (17591): #28     GestureBinding.handlePointerEvent (package:flutter/src/gestures/binding.dart:305:7)
I/flutter (17591): #29     FlutterDriverExtension._scroll (package:flutter_driver/src/extension/extension.dart:607:23)
I/flutter (17591): <asynchronous suspension>
I/flutter (17591): #30     FlutterDriverExtension.call (package:flutter_driver/src/extension/extension.dart:274:53)
I/flutter (17591): #31     BindingBase.registerServiceExtension.<anonymous closure>
(package:flutter/src/foundation/binding.dart:546:32)
I/flutter (17591): <asynchronous suspension>
I/flutter (17591): #32     BindingBase.registerServiceExtension.<anonymous closure>
(package:flutter/src/foundation/binding.dart)
I/flutter (17591): #33     _runExtension (dart:developer-patch/developer.dart:84:23)
I/flutter (17591): 
I/flutter (17591): Handler: "onUpdate"
I/flutter (17591): Recognizer:
I/flutter (17591):   VerticalDragGestureRecognizer#29932
I/flutter (17591): ════════════════════════════════════════════════════════════════════════════════════════════════════
I/flutter (17591): Another exception was thrown: A ticker was started twice.
00:08 +1: (tearDownAll)

00:08 +1: All tests passed!

Stopping application instance.
```

</details> 

<details> 
<summary>flutter doctor -v</summary> 

```bash
[✓] Flutter (Channel master, 1.22.0-10.0.pre.358, on Mac OS X 10.15.6 19G2021
    x86_64, locale en-GB)
    • Flutter version 1.22.0-10.0.pre.358 at
      /Users/tahatesser/Code/flutter_master
    • Framework revision 4898a42b0a (2 hours ago), 2020-09-25 05:42:04 -0400
    • Engine revision 62b5a53b10
    • Dart version 2.11.0 (build 2.11.0-161.0.dev)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/tahatesser/Code/sdk
    • Platform android-30, build-tools 30.0.2
    • ANDROID_HOME = /Users/tahatesser/Code/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.0.1, Build version 12A7300
    • CocoaPods version 1.9.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 49.0.2
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.49.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.14.1

[✓] Connected device (4 available)
    • RMX2001 (mobile) • EUYTFEUSQSRGDA6D • android-arm64  • Android 10 (API 29)
    • macOS (desktop)  • macos            • darwin-x64     • Mac OS X 10.15.6
      19G2021 x86_64
    • Web Server (web) • web-server       • web-javascript • Flutter Tools
    • Chrome (web)     • chrome           • web-javascript • Google Chrome
      85.0.4183.121

• No issues found!

```

</details>

**Comment by darshankawar** [comment]
Since `WillPopScope` has been deprecated https://api.flutter.dev/flutter/widgets/WillPopScope/WillPopScope.html, I'll close this issue as not valid anymore and obsolete.

<img width="904" alt="Screenshot 2024-03-20 at 5 50 41 PM" src="https://github.com/flutter/flutter/assets/67046386/92c17850-f27b-4ec9-9d00-2aa6849470a9">


If anybody sees reported issue using latest stable version with flutter driver / integration test, please open new issue with relevant details.
