### ISSUE TITLE
[url_launcher] - PlatformException on ios 13.3 when opening a docx file

### ISSUE THREAD

**Issue by lukaszdebowski** [flutter/flutter#49162]
## Steps to Reproduce

Steps to reproduce:
1. install url_launcher plugin
2. try to open a url that points to an uploaded docx file somewhere
3. native view opens up and PlatformException is thrown

**Expected results:** 
No exception is thrown (maybe I can open the file also?)

**Actual results:** 
iOS opens to following view, while the lib still throws an exception:

<img width="307" alt="Screenshot 2020-01-20 at 09 37 03" src="https://user-images.githubusercontent.com/39137870/72710968-6e37a700-3b68-11ea-9191-e1f5f6c75578.png">

On ios 11 everything works just fine. I'm asking about this because we are using Sentry to report every exception that occurs, and this I think should not be an exception 

<details>
  <summary>Logs</summary>

```
flutter: Caught error: PlatformException(Error, Error while launching {{url_here}}, null)
flutter: inDebugMode
flutter: #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:569:7)
#1      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:316:33)
<asynchronous suspension>
#2      MethodChannelUrlLauncher.launch (package:url_launcher_platform_interface/method_channel_url_launcher.dart:39:21)
#3      launch (package:url_launcher/url_launcher.dart:86:58)
<asynchronous suspension>
#4      tryOpenLink (package:{{package_name_here}}/widgets/chat_view/utils/link_tools.dart:8:11)
<asynchronous suspension>
#5      AttachmentMessage._handleLinkOpen.<anonymous closure> (package:{{package_name_here}}/widgets/chat_view/widgets/messages/attachment_message.dart:33:13)
#6      _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:654:14)
#7      _InkResponseState.build.<anonymous closure> (package:flutter/src/material/ink_well.dart:729:32)
#8      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:182:24)
#9      TapGestureRe<…>
```

```
Flutter doctor: 

[✓] Flutter (Channel unknown, v1.9.1+hotfix.6, on Mac OS X 10.14.6 18G2022, locale en-GB) 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 11.3.1)
[✓] Android Studio (version 3.5)
[✓] IntelliJ IDEA Community Edition (version 2019.1.3)
[✓] VS Code (version 1.41.0)
[✓] Connected device (2 available)
```
</details>

**Comment by coredeveloper** [comment]
Can confirm, I am having the same behaviour.

**Comment by ItzNotABug** [comment]
Not only just `docx` files, happens for `zip` too.
In most cases, if the URI does not lead to a Web Page or a Media Type File then the exception is thrown even when the supplied url loads just fine in Safari.

**Comment by memishood** [comment]
same issue here..
