### ISSUE TITLE
NoSuchMethodError: method not found: 'dispose'

### ISSUE THREAD

**Issue by jimbeveridge** [flutter/flutter#492]
I'm running a hacked up version of the Flutter tutorial and I'm getting the error below in my logs. I'm not explicitly using a Scene object, so it's something under the covers.

This was running at commit f97a125eeebc1b4fe804fd590be4d71227e0758c.

```
I/sky     ( 9597): -- EXCEPTION IN SCHEDULER CALLBACK --
I/sky     ( 9597): Class 'Scene' has no instance method 'dispose'.
I/sky     ( 9597): 
I/sky     ( 9597): NoSuchMethodError: method not found: 'dispose'
I/sky     ( 9597): Receiver: Instance of 'Scene'
I/sky     ( 9597): Arguments: []
I/sky     ( 9597): Stack trace:
I/sky     ( 9597): #0      Object._noSuchMethod (dart:core-patch/object_patch.dart:42)
I/sky     ( 9597): #1      Object.noSuchMethod (dart:core-patch/object_patch.dart:45)
I/sky     ( 9597): #2      RenderView.compositeFrame (packages/flutter/src/rendering/view.dart:128)
I/sky     ( 9597): #3      FlutterBinding.beginFrame (packages/flutter/src/rendering/binding.dart:192)
I/sky     ( 9597): #4      WidgetFlutterBinding.beginFrame (packages/flutter/src/widgets/binding.dart:29)
I/sky     ( 9597): #5      FlutterBinding._handlePersistentFrameCallback (packages/flutter/src/rendering/binding.dart:184)
I/sky     ( 9597): #6      Scheduler.invokeCallback (packages/flutter/src/animation/scheduler.dart:90)
I/sky     ( 9597): #7      Scheduler.beginFrame (packages/flutter/src/animation/scheduler.dart:75)
I/sky     ( 9597): #8      _beginFrame (file:///ssd2/sky/engine/src/out/android_Release/gen/sky/bindings/Customhooks.dart:35)
```

Here's the source code:
```
import 'package:flutter/rendering.dart';
import 'package:flutter/painting.dart';
import 'package:flutter/material.dart';

class HelloWorldApp extends StatelessComponent {
  final NavigatorState navigator;

  HelloWorldApp({this.navigator});
  @override Widget build(BuildContext build) {
    return new Center(child: new MyToolBar());
  }
}

class MyButton extends StatelessComponent {
  @override Widget build(BuildContext context) {
    return new RaisedButton(onPressed: () {
      print("-------------------onPressed");
    }, child: new Center(child: new Text('Engagand"e')));
  }
}

class MyToolBar extends ToolBar {
  @override Widget build(BuildContext context) {
    return new Container(
        decoration:
            const BoxDecoration(backgroundColor: const Color(0x000FFFFF)),
        height: 56.0,
        padding: const EdgeDims.symmetric(horizontal: 8.0),
        child: new Material(
            child: new Row([
          new MyButton(),
          new Container(
              padding: const EdgeDims.symmetric(horizontal: 8.0),
              child: new AssetImage(
                  name: 'packages/hello_world/res/menu.png',
                  width: 30.0,
                  height: 30.0)),
          new Flexible(child: new Text('My awesome toolbar')),
          new AssetImage(
              name: 'packages/hello_world/res/search.png',
              width: 25.0,
              height: 25.0),
        ])));
  }
}

void main() {
  runApp(new MaterialApp(
      title: 'Tutorial app',
      routes: {'/': (RouteArguments args) => new HelloWorldApp()}));
}
```

**Comment by abarth** [comment]
You've got an old engine.  Try running `flutter upgrade` on your app.

**Comment by jimbeveridge** [comment]
You are correct. Closing this as "not a bug".
