### ISSUE TITLE
App is closing when semantics focuses one of Android's bottom navigation buttons by drag.

### ISSUE THREAD

**Issue by SugyoIn-LBSTech** [flutter/flutter#49270]
## Steps to Reproduce
1. Turn on screen reader(Talk Back/Voice Assistance)
2. Drag semantics cursor from flutter app to Android's one of bottom navigation buttons(Overview, Home, Back)

**Expected results:**
Nothing

**Actual results:**
- App is closing.
- Device is freezing about 1 or 2 seconds.
- If do this again can see "flutter_app keeps stopping" pop up.

<details>
  <summary>Logs</summary>

```
[        ] Connected to _flutterView/0x770567a820.
[   +2 ms] �  To hot reload changes while running, press "r". To hot restart (and rebuild state), press "R".
[   +1 ms] An Observatory debugger and profiler on SM N960N is available at: http://127.0.0.1:50668/1RJWLIZc5rA=/
[        ] For a more detailed help message, press "h". To detach, press "d"; to quit, press "q".
[+13903 ms] Service protocol connection closed.
[   +1 ms] Lost connection to device.
[   +2 ms] DevFS: Deleting filesystem on the device (file:///data/user/0/rooftop.flutter_app/code_cache/flutter_appXBTDQS/flutter_app/)
[   +1 ms] Sending to VM service: _deleteDevFS({fsName: flutter_app})
[ +254 ms] Ignored error while cleaning up DevFS: TimeoutException after 0:00:00.250000: Future not completed
[   +4 ms] "flutter run" took 23,108ms.
```

**Flutter analyze has no issues.**
The project is default flutter app which creates by "flutter create ." command.

```
[√] Flutter (Channel stable, v1.12.13+hotfix.5, on Microsoft Windows [Version 10.0.18362.592], locale ko-KR)
    • Flutter version 1.12.13+hotfix.5 at C:\Users\LBSTECH\flutter
    • Framework revision 27321ebbad (6 weeks ago), 2019-12-10 18:15:01 -0800
    • Engine revision 2994f7e1e6
    • Dart version 2.7.0

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at C:\Users\LBSTECH\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)
    • All Android licenses accepted.

[√] Android Studio (version 3.5)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 42.1.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)

[√] VS Code (version 1.41.1)
    • VS Code at C:\Users\LBSTECH\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.7.1

[√] Connected device (1 available)
    • SM N960N • 2862d1eb2e017ece • android-arm64 • Android 9 (API 28)

• No issues found!
```

</details>

Device: POCO F1[xiaomi], Galaxy Note 9[Samsung]
OS: AOS

**Comment by SugyoIn-LBSTech** [comment]
Additional info.
Message from android debug console.

```
E/InputEventReceiver: Exception dispatching input event.
D/AndroidRuntime: Shutting down VM
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: kr.lbstech.spacedetect.geye, PID: 31569
    java.lang.NullPointerException: Attempt to read from field 'int io.flutter.view.AccessibilityBridge$SemanticsNode.platformViewId' on a null object reference
        at io.flutter.view.AccessibilityBridge$SemanticsNode.access$1400(AccessibilityBridge.java:1774)
        at io.flutter.view.AccessibilityBridge.onAccessibilityHoverEvent(AccessibilityBridge.java:1156)
        at io.flutter.embedding.android.FlutterView.onHoverEvent(FlutterView.java:538)
        at android.view.View.dispatchHoverEvent(View.java:13655)
        at android.view.ViewGroup.dispatchHoverEvent(ViewGroup.java:2202)
        at android.view.View.dispatchGenericMotionEvent(View.java:13563)
        at android.view.ViewGroup.dispatchTransformedGenericPointerEvent(ViewGroup.java:2531)
        at android.view.ViewGroup.dispatchHoverEvent(ViewGroup.java:2164)
        at android.view.View.dispatchGenericMotionEvent(View.java:13563)
        at android.view.ViewGroup.dispatchTransformedGenericPointerEvent(ViewGroup.java:2531)
        at android.view.ViewGroup.dispatchHoverEvent(ViewGroup.java:2164)
        at android.view.View.dispatchGenericMotionEvent(View.java:13563)
        at android.view.ViewGroup.dispatchTransformedGenericPointerEvent(ViewGroup.java:2531)
        at android.view.ViewGroup.dispatchHoverEvent(ViewGroup.java:2164)
        at android.view.View.dispatchGenericMotionEvent(View.java:13563)
        at android.view.ViewGroup.dispatchTransformedGenericPointerEvent(ViewGroup.java:2531)
        at android.view.ViewGroup.dispatchHoverEvent(ViewGroup.java:2164)
        at com.android.internal.policy.DecorView.dispatchHoverEvent(DecorView.java:3288)
        at android.view.View.dispatchGenericMotionEvent(View.java:13563)
        at com.android.internal.policy.DecorView.superDispatchGenericMotionEvent(DecorView.java:706)
        at com.android.internal.policy.PhoneWindow.superDispatchGenericMotionEvent(PhoneWindow.java:1889)
        at android.app.Activity.dispatchGenericMotionEvent(Activity.java:3522)
        at com.android.internal.policy.DecorView.dispatchGenericMotionEvent(DecorView.java:670)
        at android.view.View.dispatchPointerEvent(View.java:13713)
        at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:6116)
        at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:5894)
        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5343)
        at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:5396)
        at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:5362)
        at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:5521)
        at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:5370)
        at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:5578)
        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5343)
        at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:5396)
        at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:5362)
        at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:5370)
        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5343)
        at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:8387)
        at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:8320)
        at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:8281)
        at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:8502)
        at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:198)
        at android.view.InputEventReceiver.nativeConsumeBatchedInputEvents(Native Method)
        at android.view.InputEventReceiver.consumeBatchedInputEvents(InputEventReceiver.java:187)
        at android.view.ViewRootImpl.doConsumeBatchedInput(ViewRootImpl.java:8461)
        at android.view.ViewRootImpl$ConsumeBatchedInputRunnable.run(ViewRootImpl.java:8529)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:949)
        at android.view.Choreographer.doCallbacks(Choreographer.java:761)
        at android.view.Choreographer.doFrame(Choreographer.java:690)
E/AndroidRuntime:     at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:935)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:6990)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1445)
```

**Comment by SugyoIn-LBSTech** [comment]
Any news for this issue?

**Comment by SugyoIn-LBSTech** [comment]
Related to #34415
