### ISSUE TITLE
AlertDialog with ListView

### ISSUE THREAD

**Issue by gpibarra** [flutter/flutter#49302]
## Steps to Reproduce

1. Use this code
```
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        body: Center(
          child: MainAdjuntosWidget(),
        ),
      ),
    );
  }
}

class MainAdjuntosWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return InkWell(
      child: Padding(
        padding: const EdgeInsets.all(4.0),
        child: Container(
          color: Colors.transparent,
          child: Column(
            mainAxisAlignment: MainAxisAlignment.center,
            children: <Widget>[
              Icon(
                Icons.collections,
                size: 24.0,
                color: Colors.black54,
              ),
              SizedBox(
                height: 5.0,
              ),
              Text(
                "Attachments",
                style: TextStyle(fontSize: 10),
              ),
            ],
          ),
        ),
      ),
      onTap: () {
        _onViewAttachButton(context);
      },
    );
  }

  _onViewAttachButton(BuildContext context) async {
    try {
      showDialog(
        context: context,
        builder: (BuildContext cntx) {
          return MainAdjuntosDialog();
        },
      );
    } catch (e) {
      print("Unsupported operation" + e.toString());
      Scaffold.of(context).showSnackBar(
        SnackBar(
          content: Text("Error"),
        ),
      );
    }
  }
}

//////////////////////////////////////////////////////////
class MainAdjuntosDialog extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    Map<String, String> _files = {};
    _files["file1"] = "/path/to/file/file1";
    _files["file2"] = "/path/to/file/file2";
    return AlertDialog(
      title: Center(
        child: Text('Attachments'),
      ),
      actions: <Widget>[
        FlatButton(
          child: Text('Ok'),
          onPressed: () {
            Navigator.of(context, rootNavigator: true).pop();
          },
        ),
      ],
      content: AttachmentDialogList(_files),
    );
  }
}

class AttachmentDialogList extends StatelessWidget {
  final Map<String, String> listAttachments;

  AttachmentDialogList(this.listAttachments);
  @override
  Widget build(BuildContext context) {
    final Color colorDivider = Color.fromRGBO(75, 75, 75, 1);
    final List<String> paths = listAttachments.values.toList();
    final List<String> names = listAttachments.keys.toList();
    final int cantidadAdjuntos = listAttachments.length;
    return Scrollbar(
      child: ListView.separated(
        shrinkWrap: true,
        itemCount: cantidadAdjuntos,
        separatorBuilder: (BuildContext ctx, int index) => Divider(
          color: colorDivider,
        ),
        itemBuilder: (BuildContext ctx, int index) {
          final String path = paths[index];
          final String name = names[index];
          return _listTileWidget(context, name, path);
        },
      ),
    );
  }

  Widget _listTileWidget(BuildContext context, String name, String path) {
    final double sizeText = 14;
    return ListTile(
      contentPadding: EdgeInsets.all(2.0),
      title: Text(
        name,
        style: TextStyle(
          fontSize: sizeText,
        ),
      ),
      onTap: () {
        _vizualizarArchivo(context, path);
      },
    );
  }

  _vizualizarArchivo(BuildContext context, path) async {
    print("VIEW");
  }
}

```

2. Run the application.
3. Press the Icon Button.

**On an Android 8 device it works.
On an Android 5 device it fails (line 105)**

**Expected results:** 
AlertDialog with ListView

**Actual results:** 

<details>
  <summary>Logs</summary>

```
[        ] I/flutter (30206): The method 'copyWith' was called on null.
[        ] I/flutter (30206): Receiver: null
[        ] I/flutter (30206): Tried calling: copyWith(maxWidth: Infinity)
[        ] I/flutter (30206): The relevant error-causing widget was:
[        ] I/flutter (30206):   AlertDialog
[        ] I/flutter (30206):   file:///C:/UpgradeIT/Clientes/DefensoriaCABA/01_AppEmpleados/03_Mobile/Flutter/myapp_test_crash/lib/main.dart:77:12
[        ] I/flutter (30206): When the exception was thrown, this was the stack:
[        ] I/flutter (30206): #0      Object.noSuchMethod (dart:core-patch/object_patch.dart:53:5)
[        ] I/flutter (30206): #1      _RenderButtonBarRow.constraints (package:flutter/src/material/button_bar.dart:292:30)
[        ] I/flutter (30206): #2      RenderObject.debugFillProperties (package:flutter/src/rendering/object.dart:2791:68)
[        ] I/flutter (30206): #3      RenderBox.debugFillProperties (package:flutter/src/rendering/box.dart:2417:11)
[        ] I/flutter (30206): #4      RenderFlex.debugFillProperties (package:flutter/src/rendering/flex.dart:1015:11)
[        ] I/flutter (30206): #5      DiagnosticableNode.builder (package:flutter/src/foundation/diagnostics.dart:2900:14)
[        ] I/flutter (30206): #6      DiagnosticableNode.style (package:flutter/src/foundation/diagnostics.dart:2907:70)
[        ] I/flutter (30206): #7      DiagnosticsNode.toString (package:flutter/src/foundation/diagnostics.dart:1629:12)
[        ] I/flutter (30206): #8      _StringBase._interpolate (dart:core-patch/string_patch.dart:845:19)
[   +1 ms] I/flutter (30206): #9      TextTreeRenderer.render.visitor (package:flutter/src/foundation/diagnostics.dart:1140:69)
[        ] I/flutter (30206): #10     TextTreeRenderer.render.visitor (package:flutter/src/foundation/diagnostics.dart:1142:22)
[        ] I/flutter (30206): #11     TextTreeRenderer.render.visitor (package:flutter/src/foundation/diagnostics.dart:1142:22)
[        ] I/flutter (30206): #12     TextTreeRenderer.render.visitor (package:flutter/src/foundation/diagnostics.dart:1142:22)
[        ] I/flutter (30206): #13     TextTreeRenderer.render.visitor (package:flutter/src/foundation/diagnostics.dart:1142:22)
[        ] I/flutter (30206): #14     TextTreeRenderer.render (package:flutter/src/foundation/diagnostics.dart:1150:14)
[        ] I/flutter (30206): #15     TextTreeRenderer.render (package:flutter/src/foundation/diagnostics.dart:1294:39)
[        ] I/flutter (30206): #16     FlutterError.dumpErrorToConsole (package:flutter/src/foundation/assertions.dart:652:11)
[        ] I/flutter (30206): #17     FlutterError.reportError (package:flutter/src/foundation/assertions.dart:741:14)
[        ] I/flutter (30206): #18     RenderObject._debugReportException (package:flutter/src/rendering/object.dart:1270:18)
[        ] I/flutter (30206): #19     RenderObject.layout (package:flutter/src/rendering/object.dart:1731:7)
[        ] I/flutter (30206): #20     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
[        ] I/flutter (30206): #21     _RenderCustomClip.performLayout (package:flutter/src/rendering/proxy_box.dart:1232:11)
[        ] I/flutter (30206): #22     RenderObject.layout (package:flutter/src/rendering/object.dart:1724:7)
[        ] I/flutter (30206): #23     RenderConstrainedBox.performLayout (package:flutter/src/rendering/proxy_box.dart:259:13)
[        ] I/flutter (30206): #24     RenderObject.layout (package:flutter/src/rendering/object.dart:1724:7)
[   +1 ms] I/flutter (30206): #25     RenderPositionedBox.performLayout (package:flutter/src/rendering/shifted_box.dart:392:13)
[        ] I/flutter (30206): #26     RenderObject.layout (package:flutter/src/rendering/object.dart:1724:7)
[        ] I/flutter (30206): #27     RenderPadding.performLayout (package:flutter/src/rendering/shifted_box.dart:206:11)
[        ] I/flutter (30206): #28     RenderObject.layout (package:flutter/src/rendering/object.dart:1724:7)
[        ] I/flutter (30206): #29     RenderPadding.performLayout (package:flutter/src/rendering/shifted_box.dart:206:11)
[        ] I/flutter (30206): #30     RenderObject.layout (package:flutter/src/rendering/object.dart:1724:7)
[        ] I/flutter (30206): #31     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
[        ] I/flutter (30206): #32     RenderObject.layout (package:flutter/src/rendering/object.dart:1724:7)
[        ] I/flutter (30206): #33     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
[        ] I/flutter (30206): #34     RenderObject.layout (package:flutter/src/rendering/object.dart:1724:7)
[        ] I/flutter (30206): #35     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
[        ] I/flutter (30206): #36     RenderObject.layout (package:flutter/src/rendering/object.dart:1724:7)
[        ] I/flutter (30206): #37     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
[        ] I/flutter (30206): #38     RenderObject.layout (package:flutter/src/rendering/object.dart:1724:7)
[   +2 ms] I/flutter (30206): #39     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
[   +1 ms] I/flutter (30206): #40     RenderObject.layout (package:flutter/src/rendering/object.dart:1724:7)
[   +1 ms] I/flutter (30206): #41     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
[        ] I/flutter (30206): #42     RenderObject.layout (package:flutter/src/rendering/object.dart:1724:7)
[        ] I/flutter (30206): #43     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
[        ] I/flutter (30206): #44     RenderOffstage.performLayout (package:flutter/src/rendering/proxy_box.dart:3168:13)
[        ] I/flutter (30206): #45     RenderObject.layout (package:flutter/src/rendering/object.dart:1724:7)
[        ] I/flutter (30206): #46     RenderStack.performLayout (package:flutter/src/rendering/stack.dart:505:15)
[        ] I/flutter (30206): #47     RenderObject._layoutWithoutResize (package:flutter/src/rendering/object.dart:1584:7)
[        ] I/flutter (30206): #48     PipelineOwner.flushLayout (package:flutter/src/rendering/object.dart:844:18)
[        ] I/flutter (30206): #49     RendererBinding.drawFrame (package:flutter/src/rendering/binding.dart:344:19)
[        ] I/flutter (30206): #50     WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:774:13)
[        ] I/flutter (30206): #51     RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:283:5)
[        ] I/flutter (30206): #52     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1102:15)
[   +1 ms] I/flutter (30206): #53     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1041:9)
[        ] I/flutter (30206): #54     SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:957:5)
[        ] I/flutter (30206): #58     _invoke (dart:ui/hooks.dart:259:10)
[        ] I/flutter (30206): #59     _drawFrame (dart:ui/hooks.dart:217:3)
[        ] I/flutter (30206): (elided 3 frames from package dart:async)
[        ] I/flutter (30206): The following RenderObject was being processed when the exception was fired: RenderPhysicalShape#fcb5d relayoutBoundary=up2 NEEDS-LAYOUT NEEDS-PAINT
NEEDS-COMPOSITING-BITS-UPDATE:
[        ] I/flutter (30206):   needs compositing
[        ] I/flutter (30206):   creator: PhysicalShape ← _MaterialInterior ← Material ← ConstrainedBox ← Center ← MediaQuery ←
[   +1 ms] I/flutter (30206):     Padding ← AnimatedPadding ← Dialog ← AlertDialog ← MainAdjuntosDialog ← Builder ← ⋯
[   +1 ms] I/flutter (30206):   parentData: <none> (can use size)
[        ] I/flutter (30206):   constraints: BoxConstraints(280.0<=w<=520.9, 0.0<=h<=840.6)
[        ] I/flutter (30206):   size: MISSING
[        ] I/flutter (30206):   elevation: 24.0
[        ] I/flutter (30206):   color: Color(0xffffffff)
[   +1 ms] I/flutter (30206):   shadowColor: Color(0xffffffff)
[        ] I/flutter (30206):   clipper: ShapeBorderClipper
[        ] I/flutter (30206): This RenderObject had the following descendants (showing up to depth 5):
[        ] I/flutter (30206):     child: RenderCustomPaint#90e6b relayoutBoundary=up3 NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
[        ] I/flutter (30206):       child: _RenderInkFeatures#e79d5 relayoutBoundary=up4 NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
[        ] I/flutter (30206):         child: RenderIntrinsicWidth#e0ab3 relayoutBoundary=up5 NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
[        ] I/flutter (30206):           child: RenderFlex#f240a NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
[        ] I/flutter (30206):             child 1: RenderPadding#99e95 NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
[        ] I/flutter (30206):             child 2: RenderPadding#da5a2 NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
[        ] I/flutter (30206):             child 3: RenderPadding#eeb36 NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
[        ] I/flutter (30206): ════════════════════════════════════════════════════════════════════════════════════════════════════
[        ] I/flutter (30206): Another exception was thrown: RenderBox was not laid out: RenderPhysicalShape#fcb5d relayoutBoundary=up2 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
[        ] I/flutter (30206): Another exception was thrown: 'package:flutter/src/rendering/shifted_box.dart': Failed assertion: line 321 pos 12: 'child.hasSize': is not true.
[ +183 ms] I/flutter (30206): Another exception was thrown: RenderBox was not laid out: RenderPhysicalShape#fcb5d relayoutBoundary=up2
```

```
```

```
[√] Flutter (Channel stable, v1.12.13+hotfix.5, on Microsoft Windows [Version 10.0.17763.973], locale es-419)
    • Flutter version 1.12.13+hotfix.5 at C:\develop\flutter
    • Framework revision 27321ebbad (6 weeks ago), 2019-12-10 18:15:01 -0800
    • Engine revision 2994f7e1e6
    • Dart version 2.7.0


[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at c:\develop\android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)
    • All Android licenses accepted.

[√] Android Studio (version 3.5)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 42.1.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)

[√] VS Code (version 1.41.1)
    • VS Code at C:\Users\gibarra\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.7.1

[√] Connected device (2 available)
    • Moto G 5 • ZY32226G73        • android-arm • Android 8.1.0 (API 27)
    • 8080     • 192.168.0.14:5555 • android-arm • Android 5.0.1 (API 21)

• No issues found!
```

</details>

**Comment by VladyslavBondarenko** [comment]
Hi @gpibarra 
You can fix this with specifying width of your AlertDialog's content:

```
content: Container(
    width: MediaQuery.of(context).size.width,
    child: AttachmentDialogList(_files),
),
```
instead of
```
content: AttachmentDialogList(_files),
```

**Comment by VladyslavBondarenko** [comment]
@gpibarra can I close the iisue?

**Comment by gpibarra** [comment]
> an I close the iisue?

Yes, thanks

**Comment by Abhishek0116** [comment]
> Hi @gpibarra
> You can fix this by specifying width of your ListView:
> 
> ```
> return Scrollbar(
>       child: Container(
>         width: MediaQuery.of(context).size.width,
>         child: ListView.separated(
> ```
> 
> instead of
> 
> ```
> return Scrollbar(
>       child: ListView.separated(
> ```

Thanks It really also worked for me
