### ISSUE TITLE
Crash when resuming gallery from background on Android

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#4936]
Just tried resuming the Gallery app, from the background. When I tapped on the app from the background list, I got a "unfortunately, Flutter Gallery has stopped". The app was running under "profile" mode, on my Nexus 5X, Android M.

Output of `adb logcat`

```
07-15 14:28:55.184   491  2817 I ACDB-LOADER: ACDB AFE returned = -19
07-15 14:28:55.185   491  2817 D audio_hw_primary: enable_audio_route: apply and update mixer path: low-latency-playback
07-15 14:28:55.206  5179  5179 W Binder_D: type=1400 audit(0.0:237): avc: denied { ioctl } for path="socket:[65887]" dev="sockfs" ino=65887 ioctlcmd=7704 scontext=u:r:system_server:s0 tcontext=u:r:system_server:s0 tclass=unix_stream_socket permissive=0
07-15 14:28:55.206  5179  5179 W Binder_D: type=1400 audit(0.0:238): avc: denied { ioctl } for path="socket:[65887]" dev="sockfs" ino=65887 ioctlcmd=7704 scontext=u:r:system_server:s0 tcontext=u:r:system_server:s0 tclass=unix_stream_socket permissive=0
--------- beginning of crash
07-15 14:28:55.214  8801  8815 F libc    : Fatal signal 11 (SIGSEGV), code 1, fault addr 0x8 in tid 8815 (gpu_thread)
07-15 14:28:55.254   491  2817 D AudioFlinger: mixer(0xf3f00000) throttle end: throttle time(12)
07-15 14:28:55.281   487   487 F DEBUG   : *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
07-15 14:28:55.282   487   487 F DEBUG   : Build fingerprint: 'google/bullhead/bullhead:6.0.1/MTC19Z/2996059:user/release-keys'
07-15 14:28:55.282   487   487 F DEBUG   : Revision: 'rev_1.0'
07-15 14:28:55.283   487   487 W debuggerd: type=1400 audit(0.0:239): avc: denied { search } for name="io.flutter.gallery" dev="dm-2" ino=385058 scontext=u:r:debuggerd:s0 tcontext=u:object_r:app_data_file:s0:c512,c768 tclass=dir permissive=0
07-15 14:28:55.283   487   487 F DEBUG   : ABI: 'arm'
07-15 14:28:55.284   487   487 F DEBUG   : pid: 8801, tid: 8815, name: gpu_thread  >>> io.flutter.gallery <<<
07-15 14:28:55.284   487   487 F DEBUG   : signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x8
07-15 14:28:55.300   487   487 F DEBUG   :     r0 00000000  r1 ef8bdc00  r2 00000000  r3 e1886724
07-15 14:28:55.301   487   487 F DEBUG   :     r4 00000000  r5 dcd51e00  r6 ef8bdcc0  r7 ef8bdf48
07-15 14:28:55.302   487   487 F DEBUG   :     r8 00000000  r9 ef8bdc00  sl 00000001  fp 00000001
07-15 14:28:55.302   487   487 F DEBUG   :     ip e0db2c01  sp ef8bdba8  lr e0f14f8f  pc e0f14f9c  cpsr 600f0030
07-15 14:28:55.307   487   487 F DEBUG   : 
07-15 14:28:55.307   487   487 F DEBUG   : backtrace:
07-15 14:28:55.308   487   487 F DEBUG   :     #00 pc 0021df9c  /data/app/io.flutter.gallery-1/lib/arm/libsky_shell.so
07-15 14:28:55.308   487   487 F DEBUG   :     #01 pc 0021e0f9  /data/app/io.flutter.gallery-1/lib/arm/libsky_shell.so
07-15 14:28:55.309   487   487 F DEBUG   :     #02 pc 00289e9d  /data/app/io.flutter.gallery-1/lib/arm/libsky_shell.so
07-15 14:28:55.309   487   487 F DEBUG   :     #03 pc 0028a53d  /data/app/io.flutter.gallery-1/lib/arm/libsky_shell.so
07-15 14:28:55.310   487   487 F DEBUG   :     #04 pc 00285235  /data/app/io.flutter.gallery-1/lib/arm/libsky_shell.so
07-15 14:28:55.310   487   487 F DEBUG   :     #05 pc 000eca17  /data/app/io.flutter.gallery-1/lib/arm/libsky_shell.so
07-15 14:28:55.311   487   487 F DEBUG   :     #06 pc 000eaab1  /data/app/io.flutter.gallery-1/lib/arm/libsky_shell.so
07-15 14:28:55.311   487   487 F DEBUG   :     #07 pc 000cdb7b  /data/app/io.flutter.gallery-1/lib/arm/libsky_shell.so
07-15 14:28:55.312   487   487 F DEBUG   :     #08 pc 000cd10b  /data/app/io.flutter.gallery-1/lib/arm/libsky_shell.so
07-15 14:28:55.313   487   487 F DEBUG   :     #09 pc 000cde83  /data/app/io.flutter.gallery-1/lib/arm/libsky_shell.so
07-15 14:28:55.314   487   487 F DEBUG   :     #10 pc 000cd27b  /data/app/io.flutter.gallery-1/lib/arm/libsky_shell.so
07-15 14:28:55.315   487   487 F DEBUG   :     #11 pc 000638c9  /data/app/io.flutter.gallery-1/lib/arm/libsky_shell.so
07-15 14:28:55.315   487   487 F DEBUG   :     #12 pc 0035706f  /data/app/io.flutter.gallery-1/lib/arm/libsky_shell.so
07-15 14:28:55.316   487   487 F DEBUG   :     #13 pc 000cef03  /data/app/io.flutter.gallery-1/lib/arm/libsky_shell.so
07-15 14:28:55.317   487   487 F DEBUG   :     #14 pc 000cea93  /data/app/io.flutter.gallery-1/lib/arm/libsky_shell.so
07-15 14:28:55.317   487   487 F DEBUG   :     #15 pc 000ce519  /data/app/io.flutter.gallery-1/lib/arm/libsky_shell.so
07-15 14:28:55.318   487   487 F DEBUG   :     #16 pc 000ce6fb  /data/app/io.flutter.gallery-1/lib/arm/libsky_shell.so
07-15 14:28:55.318   487   487 F DEBUG   :     #17 pc 000ce74b  /data/app/io.flutter.gallery-1/lib/arm/libsky_shell.so
07-15 14:28:55.318   487   487 F DEBUG   :     #18 pc 002b432d  /data/app/io.flutter.gallery-1/lib/arm/libsky_shell.so
07-15 14:28:55.319   487   487 F DEBUG   :     #19 pc 002b57d1  /data/app/io.flutter.gallery-1/lib/arm/libsky_shell.so
07-15 14:28:55.319   487   487 F DEBUG   :     #20 pc 002b59f9  /data/app/io.flutter.gallery-1/lib/arm/libsky_shell.so
07-15 14:28:55.320   487   487 F DEBUG   :     #21 pc 002b5adf  /data/app/io.flutter.gallery-1/lib/arm/libsky_shell.so
07-15 14:28:55.320   487   487 F DEBUG   :     #22 pc 00083809  /data/app/io.flutter.gallery-1/lib/arm/libsky_shell.so
07-15 14:28:55.321   487   487 F DEBUG   :     #23 pc 0007ffa5  /data/app/io.flutter.gallery-1/lib/arm/libsky_shell.so
07-15 14:28:55.321   487   487 F DEBUG   :     #24 pc 0008ad31  /data/app/io.flutter.gallery-1/lib/arm/libsky_shell.so
07-15 14:28:55.322   487   487 F DEBUG   :     #25 pc 0008a219  /data/app/io.flutter.gallery-1/lib/arm/libsky_shell.so
07-15 14:28:55.322   487   487 F DEBUG   :     #26 pc 0003f883  /system/lib/libc.so (_ZL15__pthread_startPv+30)
07-15 14:28:55.323   487   487 F DEBUG   :     #27 pc 00019f75  /system/lib/libc.so (__start_thread+6)
07-15 14:28:55.650   487   487 W debuggerd: type=1400 audit(0.0:240): avc: denied { search } for name="io.flutter.gallery" dev="dm-2" ino=385058 scontext=u:r:debuggerd:s0 tcontext=u:object_r:app_data_file:s0:c512,c768 tclass=dir permissive=0
07-15 14:28:55.695   491  2817 D audio_hw_primary: disable_audio_route: reset and update mixer path: low-latency-playback
07-15 14:28:55.696   491  2817 D audio_hw_primary: disable_snd_device: snd_device(2: speaker)
07-15 14:28:55.711   491  2817 D audio_hw_primary: disable_snd_device: snd_device(71: vi-feedback)
07-15 14:28:55.711   491  2817 D audio_hw_primary: disable_audio_route: reset and update mixer path: spkr-vi-record
07-15 14:28:55.714   491  2817 I soundtrigger: audio_extn_sound_trigger_update_device_status: device 0x2 of type 0 for Event 0
07-15 14:28:55.750   487   487 F DEBUG   : 
07-15 14:28:55.750   487   487 F DEBUG   : Tombstone written to: /data/tombstones/tombstone_04
07-15 14:28:55.750   487   487 E DEBUG   : AM write failed: Broken pipe
07-15 14:28:55.773  1897  9687 W ActivityManager:   Force finishing activity io.flutter.gallery/org.domokit.sky.shell.SkyActivity
07-15 14:28:55.775  1897  2206 I BootReceiver: Copying /data/tombstones/tombstone_04 to DropBox (SYSTEM_TOMBSTONE)
07-15 14:28:55.796  1897  3160 W InputDispatcher: channel 'b5d3a69 io.flutter.gallery/org.domokit.sky.shell.SkyActivity (server)' ~ Consumer closed input channel or an error occurred.  events=0x9
07-15 14:28:55.796  1897  3160 E InputDispatcher: channel 'b5d3a69 io.flutter.gallery/org.domokit.sky.shell.SkyActivity (server)' ~ Channel is unrecoverably broken and will be disposed!
07-15 14:28:55.797  1897  1976 D GraphicsStats: Buffer count: 3
07-15 14:28:55.797  1897  4085 I WindowState: WIN DEATH: Window{b5d3a69 u0 io.flutter.gallery/org.domokit.sky.shell.SkyActivity}
07-15 14:28:55.798  1897  4085 W InputDispatcher: Attempted to unregister already unregistered input channel 'b5d3a69 io.flutter.gallery/org.domokit.sky.shell.SkyActivity (server)'
07-15 14:28:55.801  1897  5179 I WindowState: WIN DEATH: Window{86a845b u0 SurfaceView}
07-15 14:28:55.810   504   504 I Zygote  : Process 8801 exited due to signal (11)
07-15 14:28:55.821  1897  9687 W ActivityManager: Exception thrown during pause
07-15 14:28:55.821  1897  9687 W ActivityManager: android.os.DeadObjectException
07-15 14:28:55.821  1897  9687 W ActivityManager: 	at android.os.BinderProxy.transactNative(Native Method)
07-15 14:28:55.821  1897  9687 W ActivityManager: 	at android.os.BinderProxy.transact(Binder.java:503)
07-15 14:28:55.821  1897  9687 W ActivityManager: 	at android.app.ApplicationThreadProxy.schedulePauseActivity(ApplicationThreadNative.java:727)
07-15 14:28:55.821  1897  9687 W ActivityManager: 	at com.android.server.am.ActivityStack.startPausingLocked(ActivityStack.java:867)
07-15 14:28:55.821  1897  9687 W ActivityManager: 	at com.android.server.am.ActivityStack.finishActivityLocked(ActivityStack.java:2907)
07-15 14:28:55.821  1897  9687 W ActivityManager: 	at com.android.server.am.ActivityStack.finishTopRunningActivityLocked(ActivityStack.java:2763)
07-15 14:28:55.821  1897  9687 W ActivityManager: 	at com.android.server.am.ActivityStackSupervisor.finishTopRunningActivityLocked(ActivityStackSupervisor.java:2760)
07-15 14:28:55.821  1897  9687 W ActivityManager: 	at com.android.server.am.ActivityManagerService.handleAppCrashLocked(ActivityManagerService.java:12050)
07-15 14:28:55.821  1897  9687 W ActivityManager: 	at com.android.server.am.ActivityManagerService.makeAppCrashingLocked(ActivityManagerService.java:11946)
07-15 14:28:55.821  1897  9687 W ActivityManager: 	at com.android.server.am.ActivityManagerService.crashApplication(ActivityManagerService.java:12635)
07-15 14:28:55.821  1897  9687 W ActivityManager: 	at com.android.server.am.ActivityManagerService.handleApplicationCrashInner(ActivityManagerService.java:12142)
07-15 14:28:55.821  1897  9687 W ActivityManager: 	at com.android.server.am.NativeCrashListener$NativeCrashReporter.run(NativeCrashListener.java:86)
07-15 14:28:55.825   371   371 E lowmemorykiller: Error opening /proc/8801/oom_score_adj; errno=2
07-15 14:28:55.830  1897  5147 I ActivityManager: Process io.flutter.gallery (pid 8801) has died
07-15 14:28:55.896  1897  3167 I OpenGLRenderer: Initialized EGL, version 1.4
07-15 14:28:56.363  1897  2211 W WindowAnimator: Failed to dispatch window animation state change.
07-15 14:28:56.363  1897  2211 W WindowAnimator: android.os.DeadObjectException
07-15 14:28:56.363  1897  2211 W WindowAnimator: 	at android.os.BinderProxy.transactNative(Native Method)
07-15 14:28:56.363  1897  2211 W WindowAnimator: 	at android.os.BinderProxy.transact(Binder.java:503)
07-15 14:28:56.363  1897  2211 W WindowAnimator: 	at android.view.IWindow$Stub$Proxy.onAnimationStopped(IWindow.java:534)
07-15 14:28:56.363  1897  2211 W WindowAnimator: 	at com.android.server.wm.WindowAnimator.updateWindowsLocked(WindowAnimator.java:286)
07-15 14:28:56.363  1897  2211 W WindowAnimator: 	at com.android.server.wm.WindowAnimator.animateLocked(WindowAnimator.java:678)
07-15 14:28:56.363  1897  2211 W WindowAnimator: 	at com.android.server.wm.WindowAnimator.-wrap0(WindowAnimator.java)
07-15 14:28:56.363  1897  2211 W WindowAnimator: 	at com.android.server.wm.WindowAnimator$1.doFrame(WindowAnimator.java:123)
07-15 14:28:56.363  1897  2211 W WindowAnimator: 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:856)
07-15 14:28:56.363  1897  2211 W WindowAnimator: 	at android.view.Choreographer.doCallbacks(Choreographer.java:670)
07-15 14:28:56.363  1897  2211 W WindowAnimator: 	at android.view.Choreographer.doFrame(Choreographer.java:603)
07-15 14:28:56.363  1897  2211 W WindowAnimator: 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:844)
07-15 14:28:56.363  1897  2211 W WindowAnimator: 	at android.os.Handler.handleCallback(Handler.java:739)
07-15 14:28:56.363  1897  2211 W WindowAnimator: 	at android.os.Handler.dispatchMessage(Handler.java:95)
07-15 14:28:56.363  1897  2211 W WindowAnimator: 	at android.os.Looper.loop(Looper.java:148)
07-15 14:28:56.363  1897  2211 W WindowAnimator: 	at android.os.HandlerThread.run(HandlerThread.java:61)
07-15 14:28:56.363  1897  2211 W WindowAnimator: 	at com.android.server.ServiceThread.run(ServiceThread.java:46)
07-15 14:28:56.365  1897  2211 W WindowAnimator: Failed to dispatch window animation state change.
07-15 14:28:56.365  1897  2211 W WindowAnimator: android.os.DeadObjectException
07-15 14:28:56.365  1897  2211 W WindowAnimator: 	at android.os.BinderProxy.transactNative(Native Method)
07-15 14:28:56.365  1897  2211 W WindowAnimator: 	at android.os.BinderProxy.transact(Binder.java:503)
07-15 14:28:56.365  1897  2211 W WindowAnimator: 	at android.view.IWindow$Stub$Proxy.onAnimationStopped(IWindow.java:534)
07-15 14:28:56.365  1897  2211 W WindowAnimator: 	at com.android.server.wm.WindowAnimator.updateWindowsLocked(WindowAnimator.java:286)
07-15 14:28:56.365  1897  2211 W WindowAnimator: 	at com.android.server.wm.WindowAnimator.animateLocked(WindowAnimator.java:678)
07-15 14:28:56.365  1897  2211 W WindowAnimator: 	at com.android.server.wm.WindowAnimator.-wrap0(WindowAnimator.java)
07-15 14:28:56.365  1897  2211 W WindowAnimator: 	at com.android.server.wm.WindowAnimator$1.doFrame(WindowAnimator.java:123)
07-15 14:28:56.365  1897  2211 W WindowAnimator: 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:856)
07-15 14:28:56.365  1897  2211 W WindowAnimator: 	at android.view.Choreographer.doCallbacks(Choreographer.java:670)
07-15 14:28:56.365  1897  2211 W WindowAnimator: 	at android.view.Choreographer.doFrame(Choreographer.java:603)
07-15 14:28:56.365  1897  2211 W WindowAnimator: 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:844)
07-15 14:28:56.365  1897  2211 W WindowAnimator: 	at android.os.Handler.handleCallback(Handler.java:739)
07-15 14:28:56.365  1897  2211 W WindowAnimator: 	at android.os.Handler.dispatchMessage(Handler.java:95)
07-15 14:28:56.365  1897  2211 W WindowAnimator: 	at android.os.Looper.loop(Looper.java:148)
07-15 14:28:56.365  1897  2211 W WindowAnimator: 	at android.os.HandlerThread.run(HandlerThread.java:61)
07-15 14:28:56.365  1897  2211 W WindowAnimator: 	at com.android.server.ServiceThread.run(ServiceThread.java:46)
07-15 14:28:56.424  4045  4252 W OpenGLRenderer: Incorrectly called buildLayer on View: ShortcutAndWidgetContainer, destroying layer...
07-15 14:29:07.484  1897  4113 D NetlinkSocketObserver: NeighborEvent{elapsedMs=6861894, fe80::200:5eff:fe01:265, [00005E000265], RTM_NEWNEIGH, NUD_STALE}
```

**Comment by sethladd** [comment]
```
~/Code/flutter/examples/flutter_gallery[master*] $ flutter --version
Flutter on channel master (from git@github.com:flutter/flutter.git)
Framework revision 5f7b89990e (4 hours ago); engine revision 2d6510295c
```

**Comment by sethladd** [comment]
cc @jason-simmons does this look familiar?

**Comment by sethladd** [comment]
Can't repro.
