### ISSUE TITLE
Exception in Image Resource Service

### ISSUE THREAD

**Issue by apwilson** [flutter/flutter#4937]
Easy reproduce is to run my app then switch to a different app and then back.  Upon switching back I get this exception 100% of the time.

```
14:35:29.920: I/flutter : ══╡ EXCEPTION CAUGHT BY IMAGE RESOURCE SERVICE ╞════════════════════════════════════════════════════
14:35:29.923: I/flutter : The following assertion was thrown by a synchronously-called image listener:
14:35:29.926: I/flutter : 'package:flutter/src/rendering/object.dart': Failed assertion: line 1725: 'owner == null ||
14:35:29.928: I/flutter : !owner.debugDoingPaint' is not true.
14:35:29.933: I/flutter : When the exception was thrown, this was the stack:
14:35:29.953: I/flutter : #0      _AssertionError._throwNew (dart:core-patch/errors_patch.dart:27)
14:35:29.956: I/flutter : #1      _AssertionError._checkAssertion (dart:core-patch/errors_patch.dart:34)
14:35:29.959: I/flutter : #2      RenderObject.markNeedsPaint (package:flutter/src/rendering/object.dart:1725)
14:35:29.962: I/flutter : #3      _BoxDecorationPainter._imageListener (package:flutter/src/painting/box_painter.dart:1426)
14:35:29.965: I/flutter : #4      ImageStreamCompleter.addListener (package:flutter/src/services/image_stream.dart:161)
14:35:29.968: I/flutter : #5      ImageStream.addListener (package:flutter/src/services/image_stream.dart:96)
14:35:29.970: I/flutter : #6      _BoxDecorationPainter._paintBackgroundImage (package:flutter/src/painting/box_painter.dart:1405)
14:35:29.972: I/flutter : #7      _BoxDecorationPainter.paint (package:flutter/src/painting/box_painter.dart:1445)
14:35:29.975: I/flutter : #8      RenderDecoratedBox.paint (package:flutter/src/rendering/proxy_box.dart:1176)
14:35:29.977: I/flutter : #9      RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:1806)
14:35:29.980: I/flutter : #10     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:101)
14:35:29.983: I/flutter : #11     RenderBox&ContainerRenderObjectMixin&RenderBoxContainerDefaultsMixin.defaultPaint (package:flutter/src/rendering/box.dart:1434)
14:35:29.985: I/flutter : #12     RenderStack.paintStack (package:flutter/src/rendering/stack.dart:407)
14:35:29.988: I/flutter : #13     RenderStack.paint (package:flutter/src/rendering/stack.dart:415)
14:35:29.990: I/flutter : #14     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:1806)
14:35:29.993: I/flutter : #15     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:101)
14:35:29.996: I/flutter : #16     <redacted>.paint (<redacted>:30)
14:35:29.999: I/flutter : #17     <redacted>.paint.<anonymous closure> (<redacted>:366)
```

**Comment by apwilson** [comment]
Another reproduce:

If I call: SystemChrome.setEnabledSystemUIOverlays(0); In the initState of the main widget of my app I also get the above exception.

**Comment by abarth** [comment]
@Hixie Maybe we need to check in the ImageStream whether we're currently painting this object?

**Comment by Hixie** [comment]
There's several ways I can see to solve this:
- resolve it aggressively, rather than lazily, so that the synchronous callback happens before paint: bad for perf
- check to see if you're painting, and avoid calling `markNeedsPaint` if so: awkward, and we don't currently track this so we'd have to have a new bit
- remove the assert: i think it's caught some real bugs so probably not a good idea
- plumb a boolean through from `_paintBackgroundImage` all the way to `_imageListener` which tracks whether we're painting or not (aka whether it's a synchronous call or not): makes the APIs ugly

The least disruptive change would probably be tracking the "are we painting" bit just in `_BoxDecorationPainter`, not calling `onChanged` if it's set. But that'll still leave this landmine for other ImageProvider users.
