### ISSUE TITLE
Flutter Error Run: Execution failed for task ':app:compileDebugKotlin'

### ISSUE THREAD

**Issue by serpentarius-hollow** [flutter/flutter#49419]
I'm just trying to run the default flutter app that I create using **flutter create** command on my android device and it throws me an error. I attached my logs down here. Can someone help me?

<details>
  <summary>Logs</summary>

```
[  +19 ms] executing: [E:\flutter\flutter\] git -c log.showSignature=false log -n 1 --pretty=format:%H
[  +39 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[        ] 27321ebbad34b0a3fafe99fac037102196d655ff
[        ] executing: [E:\flutter\flutter\] git describe --match v*.*.* --first-parent --long --tags
[  +22 ms] Exit code 0 from: git describe --match v*.*.* --first-parent --long --tags
[        ] v1.12.13+hotfix.5-0-g27321ebba
[   +6 ms] executing: [E:\flutter\flutter\] git rev-parse --abbrev-ref --symbolic @{u}
[  +21 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/stable
[        ] executing: [E:\flutter\flutter\] git ls-remote --get-url origin
[  +17 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[  +51 ms] executing: [E:\flutter\flutter\] git rev-parse --abbrev-ref HEAD
[  +16 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] stable
[  +76 ms] executing: C:\Users\208046\AppData\Local\Android\sdk\platform-tools\adb.exe devices -l
[  +11 ms] Exit code 0 from: C:\Users\208046\AppData\Local\Android\sdk\platform-tools\adb.exe devices -l
[        ] List of devices attached
           33005566b2b5c3df       device product:on7xeltedd model:SM_G610F device:on7xelte transport_id:3
[  +12 ms] C:\Users\208046\AppData\Local\Android\sdk\platform-tools\adb.exe -s 33005566b2b5c3df shell getprop
[ +123 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[   +8 ms] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +4 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[ +135 ms] Generating E:\FRIDHO\Projects\testandroid\android\app\src\main\java\io\flutter\plugins\GeneratedPluginRegistrant.java
[  +27 ms] ro.hardware = samsungexynos7870
[  +48 ms] Launching lib\main.dart on SM G610F in debug mode...
[  +18 ms] executing: C:\Users\208046\AppData\Local\Android\sdk\platform-tools\adb.exe -s 33005566b2b5c3df shell -x logcat -v time -s flutter
[   +6 ms] executing: C:\Users\208046\AppData\Local\Android\sdk\platform-tools\adb.exe version
[  +49 ms] Android Debug Bridge version 1.0.41
           Version 29.0.5-5949299
           Installed as C:\Users\208046\AppData\Local\Android\sdk\platform-tools\adb.exe
[   +3 ms] executing: C:\Users\208046\AppData\Local\Android\sdk\platform-tools\adb.exe start-server
[  +15 ms] Building APK
[  +31 ms] Running Gradle task 'assembleDebug'...
[   +5 ms] gradle.properties already sets `android.enableR8`
[   +6 ms] Using gradle from E:\FRIDHO\Projects\testandroid\android\gradlew.bat.
[   +9 ms] executing: C:\Program Files\Android\Android Studio\jre\bin\java -version
[  +63 ms] Exit code 0 from: C:\Program Files\Android\Android Studio\jre\bin\java -version
[        ] openjdk version "1.8.0_202-release"
           OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)
           OpenJDK 64-Bit Server VM (build 25.202-b03, mixed mode)
[   +3 ms] executing: [E:\FRIDHO\Projects\testandroid\android\] E:\FRIDHO\Projects\testandroid\android\gradlew.bat -Pverbose=true
-Ptarget=E:\FRIDHO\Projects\testandroid\lib\main.dart -Ptrack-widget-creation=true -Pfilesystem-scheme=org-dartlang-root -Ptarget-platform=android-arm
assembleDebug
[+6355 ms] > Task :app:compileFlutterBuildDebug
[        ] [  +18 ms] executing: [E:\flutter\flutter\] git -c log.showSignature=false log -n 1 --pretty=format:%H
[        ] [  +39 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[        ] [        ] 27321ebbad34b0a3fafe99fac037102196d655ff
[        ] [        ] executing: [E:\flutter\flutter\] git describe --match v*.*.* --first-parent --long --tags
[        ] [  +22 ms] Exit code 0 from: git describe --match v*.*.* --first-parent --long --tags
[        ] [        ] v1.12.13+hotfix.5-0-g27321ebba
[        ] [   +6 ms] executing: [E:\flutter\flutter\] git rev-parse --abbrev-ref --symbolic @{u}
[        ] [  +19 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] [        ] origin/stable
[        ] [        ] executing: [E:\flutter\flutter\] git ls-remote --get-url origin
[        ] [  +17 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] [        ] https://github.com/flutter/flutter.git
[        ] [  +48 ms] executing: [E:\flutter\flutter\] git rev-parse --abbrev-ref HEAD
[        ] [  +17 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] [        ] stable
[   +1 ms] [  +16 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[        ] [   +2 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[        ] [  +67 ms] Initializing file store
[        ] [  +13 ms] Done initializing file store
[        ] [+1151 ms] Skipping target: kernel_snapshot
[        ] [  +49 ms] debug_android_application: Starting due to {InvalidatedReason.outputMissing}
[        ] [ +114 ms] debug_android_application: Complete
[        ] [  +14 ms] Persisting file store
[        ] [  +13 ms] Done persisting file store
[        ] [   +3 ms] build succeeded.
[  +80 ms] [  +16 ms] "flutter assemble" took 1,475ms.
[        ] > Task :app:packLibsflutterBuildDebug UP-TO-DATE
[        ] > Task :app:preBuild UP-TO-DATE
[        ] > Task :app:preDebugBuild UP-TO-DATE
[        ] > Task :app:compileDebugAidl NO-SOURCE
[        ] > Task :app:checkDebugManifest UP-TO-DATE
[   +3 ms] > Task :app:compileDebugRenderscript NO-SOURCE
[   +1 ms] > Task :app:generateDebugBuildConfig UP-TO-DATE
[  +85 ms] > Task :app:cleanMergeDebugAssets
[        ] > Task :app:mergeDebugShaders UP-TO-DATE
[        ] > Task :app:compileDebugShaders UP-TO-DATE
[        ] > Task :app:generateDebugAssets UP-TO-DATE
[        ] > Task :app:mergeDebugAssets
[ +230 ms] > Task :app:copyFlutterAssetsDebug
[   +1 ms] > Task :app:mainApkListPersistenceDebug UP-TO-DATE
[   +3 ms] > Task :app:generateDebugResValues UP-TO-DATE
[  +13 ms] > Task :app:generateDebugResources UP-TO-DATE
[  +58 ms] > Task :app:mergeDebugResources UP-TO-DATE
[   +3 ms] > Task :app:createDebugCompatibleScreenManifests UP-TO-DATE
[   +2 ms] > Task :app:processDebugManifest UP-TO-DATE
[   +3 ms] > Task :app:processDebugResources UP-TO-DATE
[   +2 ms] > Task :app:compileDebugKotlin FAILED
[   +2 ms] FAILURE: Build failed with an exception.
[   +3 ms] * What went wrong:
[        ] Execution failed for task ':app:compileDebugKotlin'.
[        ] > Could not resolve all artifacts for configuration ':app:debugCompileClasspath'.
[        ]    > Could not download flutter_embedding_debug.jar (io.flutter:flutter_embedding_debug:1.0.0-2994f7e1e682039464cb25e31a78b86a3c59b695)
[   +1 ms]       > Could not get resource
'http://download.flutter.io/io/flutter/flutter_embedding_debug/1.0.0-2994f7e1e682039464cb25e31a78b86a3c59b695/flutter_embedding_debug-1.0.0-2994f7e1e6820
39464cb25e31a78b86a3c59b695.jar'.
[  +12 ms]          > Could not GET
'http://download.flutter.io/io/flutter/flutter_embedding_debug/1.0.0-2994f7e1e682039464cb25e31a78b86a3c59b695/flutter_embedding_debug-1.0.0-2994f7e1e6820
39464cb25e31a78b86a3c59b695.jar'. Received status code 503 from server: Service Unavailable
[   +1 ms]    > Could not download armeabi_v7a_debug.jar (io.flutter:armeabi_v7a_debug:1.0.0-2994f7e1e682039464cb25e31a78b86a3c59b695)
[        ]       > Could not get resource
'http://download.flutter.io/io/flutter/armeabi_v7a_debug/1.0.0-2994f7e1e682039464cb25e31a78b86a3c59b695/armeabi_v7a_debug-1.0.0-2994f7e1e682039464cb25e31
a78b86a3c59b695.jar'.
[   +1 ms]          > Could not GET
'http://download.flutter.io/io/flutter/armeabi_v7a_debug/1.0.0-2994f7e1e682039464cb25e31a78b86a3c59b695/armeabi_v7a_debug-1.0.0-2994f7e1e682039464cb25e31
a78b86a3c59b695.jar'. Received status code 503 from server: Service Unavailable
[   +1 ms]    > Could not download x86_debug.jar (io.flutter:x86_debug:1.0.0-2994f7e1e682039464cb25e31a78b86a3c59b695)
[        ]       > Could not get resource
'http://download.flutter.io/io/flutter/x86_debug/1.0.0-2994f7e1e682039464cb25e31a78b86a3c59b695/x86_debug-1.0.0-2994f7e1e682039464cb25e31a78b86a3c59b695.
jar'.
[   +1 ms]          > Could not GET
'http://download.flutter.io/io/flutter/x86_debug/1.0.0-2994f7e1e682039464cb25e31a78b86a3c59b695/x86_debug-1.0.0-2994f7e1e682039464cb25e31a78b86a3c59b695.
jar'. Received status code 503 from server: Service Unavailable
[   +1 ms]    > Could not download x86_64_debug.jar (io.flutter:x86_64_debug:1.0.0-2994f7e1e682039464cb25e31a78b86a3c59b695)
[        ] 16 actionable tasks: 5 executed, 11 up-to-date
[        ]       > Could not get resource
'http://download.flutter.io/io/flutter/x86_64_debug/1.0.0-2994f7e1e682039464cb25e31a78b86a3c59b695/x86_64_debug-1.0.0-2994f7e1e682039464cb25e31a78b86a3c5
9b695.jar'.
[   +1 ms]          > Could not GET
'http://download.flutter.io/io/flutter/x86_64_debug/1.0.0-2994f7e1e682039464cb25e31a78b86a3c59b695/x86_64_debug-1.0.0-2994f7e1e682039464cb25e31a78b86a3c5
9b695.jar'. Received status code 503 from server: Service Unavailable
[   +1 ms] * Try:
[   +1 ms] Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full
insights.
[        ] * Get more help at https://help.gradle.org
[        ] BUILD FAILED in 6s
[ +340 ms] Running Gradle task 'assembleDebug'... (completed in 7.3s)
[   +9 ms] "flutter run" took 7,936ms.
Gradle task assembleDebug failed with exit code 1

#0      throwToolExit (package:flutter_tools/src/base/common.dart:28:3)
#1      buildGradleApp (package:flutter_tools/src/android/gradle.dart:387:7)
#2      _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:73:64)
#3      _rootRunUnary (dart:async/zone.dart:1134:38)
#4      _CustomZone.runUnary (dart:async/zone.dart:1031:19)
#5      _FutureListener.handleValue (dart:async/future_impl.dart:139:18)
#6      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:680:45)
#7      Future._propagateToListeners (dart:async/future_impl.dart:709:32)
#8      Future._completeWithValue (dart:async/future_impl.dart:524:5)
#9      _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:32:15)
#10     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:290:13)
#11     _DefaultProcessUtils.stream (package:flutter_tools/src/base/process.dart)
#12     _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:73:64)
#13     _rootRunUnary (dart:async/zone.dart:1134:38)
#14     _CustomZone.runUnary (dart:async/zone.dart:1031:19)
#15     _FutureListener.handleValue (dart:async/future_impl.dart:139:18)
#16     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:680:45)
#17     Future._propagateToListeners (dart:async/future_impl.dart:709:32)
#18     Future._completeWithValue (dart:async/future_impl.dart:524:5)
#19     Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:554:7)
#20     _rootRun (dart:async/zone.dart:1126:13)
#21     _CustomZone.run (dart:async/zone.dart:1023:19)
#22     _CustomZone.runGuarded (dart:async/zone.dart:925:7)
#23     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:965:23)
#24     _microtaskLoop (dart:async/schedule_microtask.dart:43:21)
#25     _startMicrotaskLoop (dart:async/schedule_microtask.dart:52:5)
#26     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
#27     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:175:5)
```

```
Analyzing testandroid...
No issues found! (ran in 1.4s)
```

```
[√] Flutter (Channel stable, v1.12.13+hotfix.5, on Microsoft Windows [Version 10.0.10586], locale en-US)
    • Flutter version 1.12.13+hotfix.5 at E:\flutter\flutter
    • Framework revision 27321ebbad (6 weeks ago), 2019-12-10 18:15:01 -0800
    • Engine revision 2994f7e1e6
    • Dart version 2.7.0


[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at C:\Users\208046\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)
    • All Android licenses accepted.

[√] Android Studio (version 3.5)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 42.1.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)

[√] VS Code, 64-bit edition (version 1.41.1)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Flutter extension version 3.7.1

[√] Connected device (1 available)
    • SM G610F • 33005566b2b5c3df • android-arm • Android 8.1.0 (API 27)

• No issues found!
```

</details>

**Comment by dnfield** [comment]
Are you able to access http://download.flutter.io in your browser?

If not, you may want to look at the instructions at https://flutter.dev/community/china for how to use a mirror, if one is available via your ISP.

**Comment by serpentarius-hollow** [comment]
Yes I can access it from my pc and my coworkers pc.

Actually I just tried flutter create on my coworkers pc and I can run it on android device just fine.

I haven't run my app on actual android device at all, before this I just run it on web / chrome.

**Comment by dnfield** [comment]
Perhaps you were having a temporary network issue and just need to try again then...In particular look for

```
[   +3 ms] * What went wrong:
[        ] Execution failed for task ':app:compileDebugKotlin'.
[        ] > Could not resolve all artifacts for configuration ':app:debugCompileClasspath'.
[        ]    > Could not download flutter_embedding_debug.jar (io.flutter:flutter_embedding_debug:1.0.0-2994f7e1e682039464cb25e31a78b86a3c59b695)
[   +1 ms]       > Could not get resource
'http://download.flutter.io/io/flutter/flutter_embedding_debug/1.0.0-2994f7e1e682039464cb25e31a78b86a3c59b695/flutter_embedding_debug-1.0.0-2994f7e1e6820
39464cb25e31a78b86a3c59b695.jar'.
[  +12 ms]          > Could not GET
'http://download.flutter.io/io/flutter/flutter_embedding_debug/1.0.0-2994f7e1e682039464cb25e31a78b86a3c59b695/flutter_embedding_debug-1.0.0-2994f7e1e6820
39464cb25e31a78b86a3c59b695.jar'. Received status code 503 from server: Service Unavailable
[   +1 ms]    > Could not download armeabi_v7a_debug.jar (io.flutter:armeabi_v7a_debug:1.0.0-2994f7e1e682039464cb25e31a78b86a3c59b695)
[        ]       > Could not get resource
'http://download.flutter.io/io/flutter/armeabi_v7a_debug/1.0.0-2994f7e1e682039464cb25e31a78b86a3c59b695/armeabi_v7a_debug-1.0.0-2994f7e1e682039464cb25e31
a78b86a3c59b695.jar'.
[   +1 ms]          > Could not GET
'http://download.flutter.io/io/flutter/armeabi_v7a_debug/1.0.0-2994f7e1e682039464cb25e31a78b86a3c59b695/armeabi_v7a_debug-1.0.0-2994f7e1e682039464cb25e31
a78b86a3c59b695.jar'. Received status code 503 from server: Service Unavailable
[   +1 ms]    > Could not download x86_debug.jar (io.flutter:x86_debug:1.0.0-2994f7e1e682039464cb25e31a78b86a3c59b695)
[        ]       > Could not get resource
'http://download.flutter.io/io/flutter/x86_debug/1.0.0-2994f7e1e682039464cb25e31a78b86a3c59b695/x86_debug-1.0.0-2994f7e1e682039464cb25e31a78b86a3c59b695.
jar'.
[   +1 ms]          > Could not GET
'http://download.flutter.io/io/flutter/x86_debug/1.0.0-2994f7e1e682039464cb25e31a78b86a3c59b695/x86_debug-1.0.0-2994f7e1e682039464cb25e31a78b86a3c59b695.
jar'. Received status code 503 from server: Service Unavailable
[   +1 ms]    > Could not download x86_64_debug.jar (io.flutter:x86_64_debug:1.0.0-2994f7e1e682039464cb25e31a78b86a3c59b695)
[        ] 16 actionable tasks: 5 executed, 11 up-to-date
[        ]       > Could not get resource
'http://download.flutter.io/io/flutter/x86_64_debug/1.0.0-2994f7e1e682039464cb25e31a78b86a3c59b695/x86_64_debug-1.0.0-2994f7e1e682039464cb25e31a78b86a3c5
9b695.jar'.
[   +1 ms]          > Could not GET
'http://download.flutter.io/io/flutter/x86_64_debug/1.0.0-2994f7e1e682039464cb25e31a78b86a3c59b695/x86_64_debug-1.0.0-2994f7e1e682039464cb25e31a78b86a3c5
9b695.jar'. Received status code 503 from server: Service Unavailable
[
```

There may have been a temporary network issue causing it.

I'm going to close this on the assumption that that's what it is - please feel free to ping the issue again if it's not clearing up.

**Comment by serpentarius-hollow** [comment]
We're all on the same network and I still can't run flutter app on device from my pc.

Any idea how I can check what's different between his & my setup? There should be no problem at all.

**Comment by serpentarius-hollow** [comment]
I just run it on android emulator and it gave me the same error.

**Comment by dnfield** [comment]
That seems strange, it seems like it should be some configuration issue on your machine.

I don't think this is a bug in Flutter but will leave open for now to see if any new details come up.

**Comment by serpentarius-hollow** [comment]
I finally solved it by switching to other network. Thanks.

**Comment by serpentarius-hollow** [comment]
The issue was I can't access non secured http from my workplace. That's why the gradle build failed.

**Comment by Kawambui** [comment]
I had the same issue and i ended up removing the whole .gradle folder under %HOME%:\Users\%USER_NAME%.

I later ran flutter run and it worked

**Comment by coduy96** [comment]
> I had the same issue and i ended up removing the whole .gradle folder under %HOME%:\Users%USER_NAME%.
> 
> I later ran flutter run and it worked

but it not work for me :(

**Comment by sunyongsheng** [comment]
I received the similiar issue, a very strange IP address appeared. Whatever Internet or mobile hotspot, it doesn't work. Use vpn also failed.

```
Execution failed for task ':app:compileDebugKotlin'.
> Could not resolve all artifacts for configuration ':app:debugCompileClasspath'.
   > Could not download x86_debug.jar (io.flutter:x86_debug:1.0.0-af51afceb8886cc11e25047523c4e0c7e1f5d408)
      > Could not get resource 'http://download.flutter.io/io/flutter/x86_debug/1.0.0-af51afceb8886cc11e25047523c4e0c7e1f5d408/x86_debug-1.0.0-af51afceb8886cc11e25047523c4e0c7e1f5d408.jar'.
         > Could not GET 'http://117.128.6.36/cache/download.flutter.io/io/flutter/x86_debug/1.0.0-af51afceb8886cc11e25047523c4e0c7e1f5d408/x86_debug-1.0.0-af51afceb8886cc11e25047523c4e0c7e1f5d408.jar?ich_args2=469-14200810035742_4a4fd95214f9e92d2a125477ffc75a18_10001002_9c896c2adfc5f7d19e3b518939a83798_8d1af01e118d680a7de369bbc67b99cf'.
            > Connect to 117.128.6.36:80 [/117.128.6.36] failed: Connection timed out: connect
   > Could not download x86_64_debug.jar (io.flutter:x86_64_debug:1.0.0-af51afceb8886cc11e25047523c4e0c7e1f5d408)
      > Could not get resource 'http://download.flutter.io/io/flutter/x86_64_debug/1.0.0-af51afceb8886cc11e25047523c4e0c7e1f5d408/x86_64_debug-1.0.0-af51afceb8886cc11e25047523c4e0c7e1f5d408.jar'.
         > Could not GET 'http://117.128.6.32/cache/download.flutter.io/io/flutter/x86_64_debug/1.0.0-af51afceb8886cc11e25047523c4e0c7e1f5d408/x86_64_debug-1.0.0-af51afceb8886cc11e25047523c4e0c7e1f5d408.jar?ich_args2=469-14200810035725_c6379c3b74cbe5c6510bd1dd15ff7877_10001002_9c896c2adfc5f7d19e3b518939a83798_1648250909497af7556e0012823cd639'.
            > Connect to 117.128.6.32:80 [/117.128.6.32] failed: Connection timed out: connect
```

**Comment by heibor** [comment]
My flutter is

`Flutter 1.15.17 • channel beta • https://github.com/flutter/flutter.git
Framework • revision 2294d75bfa (6 周前) • 2020-03-07 00:28:38 +0900
Engine • revision 5aff311948
Tools • Dart 2.8.0 (build 2.8.0-dev.12.0 9983424a3c)`

When I run `flutter run`, it showed me these messages:

`Launching lib/main.dart on A0001 in debug mode...
Running Gradle task 'assembleDebug'...                                  
                                                                
FAILURE: Build failed with an exception.                                                                           
                                                                                                                   
* What went wrong:                                                                                                 
Execution failed for task ':app:compileDebugKotlin'.                                                               
> Could not resolve all artifacts for configuration ':app:debugCompileClasspath'.                                  
   > Could not download armeabi_v7a_debug.jar (io.flutter:armeabi_v7a_debug:1.0.0-5aff3119480996ca014ec0f8d26d74db617b5852)
      > Could not get resource 'https://storage.googleapis.com/download.flutter.io/io/flutter/armeabi_v7a_debug/1.0.0-5aff3119480996ca014ec0f8d26d74db617b5852/armeabi_v7a_debug-1.0.0-5aff3119480996ca014ec0f8d26d74db617b5852.jar'.
         > Could not GET 'https://storage.googleapis.com/download.flutter.io/io/flutter/armeabi_v7a_debug/1.0.0-5aff3119480996ca014ec0f8d26d74db617b5852/armeabi_v7a_debug-1.0.0-5aff3119480996ca014ec0f8d26d74db617b5852.jar'.
            > Connect to storage.googleapis.com:443 [storage.googleapis.com/216.58.200.48, storage.googleapis.com/2404:f340:10:1800:0:0:0:2010] failed: No route to host (connect failed)
   > Could not download x86_debug.jar (io.flutter:x86_debug:1.0.0-5aff3119480996ca014ec0f8d26d74db617b5852)        
      > Could not get resource 'https://storage.googleapis.com/download.flutter.io/io/flutter/x86_debug/1.0.0-5aff3119480996ca014ec0f8d26d74db617b5852/x86_debug-1.0.0-5aff3119480996ca014ec0f8d26d74db617b5852.jar'.
         > Could not GET 'https://storage.googleapis.com/download.flutter.io/io/flutter/x86_debug/1.0.0-5aff3119480996ca014ec0f8d26d74db617b5852/x86_debug-1.0.0-5aff3119480996ca014ec0f8d26d74db617b5852.jar'.
            > Connect to storage.googleapis.com:443 [storage.googleapis.com/172.217.160.112, storage.googleapis.com/2404:6800:4008:802:0:0:0:2010] failed: No route to host (connect failed)
   > Could not download x86_64_debug.jar (io.flutter:x86_64_debug:1.0.0-5aff3119480996ca014ec0f8d26d74db617b5852)  
      > Could not get resource 'https://storage.googleapis.com/download.flutter.io/io/flutter/x86_64_debug/1.0.0-5aff3119480996ca014ec0f8d26d74db617b5852/x86_64_debug-1.0.0-5aff3119480996ca014ec0f8d26d74db617b5852.jar'.
         > Could not GET 'https://storage.googleapis.com/download.flutter.io/io/flutter/x86_64_debug/1.0.0-5aff3119480996ca014ec0f8d26d74db617b5852/x86_64_debug-1.0.0-5aff3119480996ca014ec0f8d26d74db617b5852.jar'.
            > Connect to storage.googleapis.com:443 [storage.googleapis.com/172.217.160.80, storage.googleapis.com/2404:6800:4008:802:0:0:0:2010] failed: No route to host (connect failed)
                                                                                                                   
* Try:                                                                                                             
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
                                                                                                                   
* Get more help at https://help.gradle.org                                                                         
                                                                                                                   
BUILD FAILED in 14m 4s                                                                                             
Running Gradle task 'assembleDebug'...                                                                             
Running Gradle task 'assembleDebug'... Done                       846.3s (!)
Exception: Gradle task assembleDebug failed with exit code 1`

But when I copy the url `https://storage.googleapis.com/download.flutter.io/io/flutter/x86_64_debug/1.0.0-5aff3119480996ca014ec0f8d26d74db617b5852/x86_64_debug-1.0.0-5aff3119480996ca014ec0f8d26d74db617b5852.jar` to browser, the browser can download the `.jar` file without any difficulty.

I am at a loss as to how to solve this problem.

**Comment by sobhanesk** [comment]
i have the same error and i can't even go to the  http://download.flutter.io  but by using vpn i can download jar file, i don't khow where shold i copy jar file  that i downloaded from http://download.flutter.io/io/flutter/x86_64_debug/1.0.0-af51afceb8886cc11e25047523c4e0c7e1f5d408/x86_64_debug-1.0.0-af51afceb8886cc11e25047523c4e0c7e1f5d408.jar can any body help me to khow

**Comment by sunyongsheng** [comment]
> I received the similiar issue, a very strange IP address appeared. Whatever Internet or mobile hotspot, it doesn't work. Use vpn also failed.
> 
> ```
> Execution failed for task ':app:compileDebugKotlin'.
> > Could not resolve all artifacts for configuration ':app:debugCompileClasspath'.
>    > Could not download x86_debug.jar (io.flutter:x86_debug:1.0.0-af51afceb8886cc11e25047523c4e0c7e1f5d408)
>       > Could not get resource 'http://download.flutter.io/io/flutter/x86_debug/1.0.0-af51afceb8886cc11e25047523c4e0c7e1f5d408/x86_debug-1.0.0-af51afceb8886cc11e25047523c4e0c7e1f5d408.jar'.
>          > Could not GET 'http://117.128.6.36/cache/download.flutter.io/io/flutter/x86_debug/1.0.0-af51afceb8886cc11e25047523c4e0c7e1f5d408/x86_debug-1.0.0-af51afceb8886cc11e25047523c4e0c7e1f5d408.jar?ich_args2=469-14200810035742_4a4fd95214f9e92d2a125477ffc75a18_10001002_9c896c2adfc5f7d19e3b518939a83798_8d1af01e118d680a7de369bbc67b99cf'.
>             > Connect to 117.128.6.36:80 [/117.128.6.36] failed: Connection timed out: connect
>    > Could not download x86_64_debug.jar (io.flutter:x86_64_debug:1.0.0-af51afceb8886cc11e25047523c4e0c7e1f5d408)
>       > Could not get resource 'http://download.flutter.io/io/flutter/x86_64_debug/1.0.0-af51afceb8886cc11e25047523c4e0c7e1f5d408/x86_64_debug-1.0.0-af51afceb8886cc11e25047523c4e0c7e1f5d408.jar'.
>          > Could not GET 'http://117.128.6.32/cache/download.flutter.io/io/flutter/x86_64_debug/1.0.0-af51afceb8886cc11e25047523c4e0c7e1f5d408/x86_64_debug-1.0.0-af51afceb8886cc11e25047523c4e0c7e1f5d408.jar?ich_args2=469-14200810035725_c6379c3b74cbe5c6510bd1dd15ff7877_10001002_9c896c2adfc5f7d19e3b518939a83798_1648250909497af7556e0012823cd639'.
>             > Connect to 117.128.6.32:80 [/117.128.6.32] failed: Connection timed out: connect
> ```
> 
> The url `http://download.flutter.io/io/flutter/x86_debug/1.0.0-af51afceb8886cc11e25047523c4e0c7e1f5d408/x86_debug-1.0.0-af51afceb8886cc11e25047523c4e0c7e1f5d408.jar` can be opened by Chrome.

I solved my question by reseting flutter version to 1.12.13hotfix+5 from 1.12.13hotfix+9. May I update version util next stable version release.

**Comment by csUsamaSarwar** [comment]
# [Solved]
1. Download **Gradle** from [here](https://gradle.org/) **OR** from [Direct link](https://services.gradle.org/distributions/gradle-6.5.1-bin.zip)
2. Unzip the downloaded file in `C://`
3.  Update the /bin path in `System Environment Variables`
*Run the program and check if the problem is fixed? Proceed next if you still got the error(s)*
4. Download **Java SE Runtime Environment 8u261** [here](https://www.oracle.com/java/technologies/javase-jre8-downloads.html)
5. Update the /bin path in `System Environment Variables`
*This will fix the issue. Lemme know if you still got errors*

**Comment by athagar** [comment]
None of this stuff worked.

**Comment by mubaroqiqbal** [comment]
in my case the compiler created another MainActivity in kotlin folder, just delete the file and it worked

**Comment by ritishsaDS** [comment]
> The issue was I can't access non secured http from my workplace. That's why the gradle build failed.

how to change it

**Comment by UnderscoreShift** [comment]
In `android/build.gradle` make sure your `ext.kotlin_version` is the same with the same version that you are using in your project. At this moment, 1.4.32 is the latest version of the plugin.

This is how to do it in Android Studio: Tools -> Kotlin -> Configure Kotlin Plugin Updates.
