### ISSUE TITLE
paytm package not installed

### ISSUE THREAD

**Issue by ruturajchavda182** [flutter/flutter#49421]
I am trying to install paytm flutter package but got "ProcessException: ProcessException: Permission denied"
You can check log below.
`
## command

flutter run

## exception

ProcessException: ProcessException: Permission denied
  Command: /Users/learniphi/development/flutter/.pub-cache/hosted/pub.dartlang.org/paytm-1.0.0/android/gradlew -I=/Users/learniphi/development/flutter/packages/flutter_tools/gradle/aar_init_script.gradle -Pflutter-root=/Users/learniphi/development/flutter -Poutput-dir=/Users/learniphi/development/online-tutoring-flutter/build/app -Pis-plugin=true -Ptarget-platform=android-arm,android-arm64,android-x64 assembleAarRelease

```
#0      _DefaultProcessUtils.run (package:flutter_tools/src/base/process.dart:266:37)
<asynchronous suspension>
#1      buildGradleAar (package:flutter_tools/src/android/gradle.dart:548:33)
#2      buildPluginsAsAar (package:flutter_tools/src/android/gradle.dart:711:13)
<asynchronous suspension>
#3      buildGradleApp (package:flutter_tools/src/android/gradle.dart:257:11)
#4      _AsyncAwaitCompleter.start (dart:async-patch/async_patch.dart:45:6)
#5      buildGradleApp (package:flutter_tools/src/android/gradle.dart:218:28)
#6      buildGradleApp (package:flutter_tools/src/android/gradle.dart:415:19)
#7      _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:73:64)
#8      _rootRunUnary (dart:async/zone.dart:1134:38)
#9      _CustomZone.runUnary (dart:async/zone.dart:1031:19)
#10     _FutureListener.handleValue (dart:async/future_impl.dart:139:18)
#11     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:680:45)
#12     Future._propagateToListeners (dart:async/future_impl.dart:709:32)
#13     Future._completeWithValue (dart:async/future_impl.dart:524:5)
#14     Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:554:7)
#15     _rootRun (dart:async/zone.dart:1126:13)
#16     _CustomZone.run (dart:async/zone.dart:1023:19)
#17     _CustomZone.runGuarded (dart:async/zone.dart:925:7)
#18     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:965:23)
#19     _microtaskLoop (dart:async/schedule_microtask.dart:43:21)
#20     _startMicrotaskLoop (dart:async/schedule_microtask.dart:52:5)
#21     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
#22     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:175:5)
```

## flutter doctor

```
[32m[✓][39m Flutter (Channel stable, v1.12.13+hotfix.5, on Mac OS X 10.15.2 19C57, locale en-GB)
    [32m•[39m Flutter version 1.12.13+hotfix.5 at /Users/learniphi/development/flutter
    [32m•[39m Framework revision 27321ebbad (6 weeks ago), 2019-12-10 18:15:01 -0800
    [32m•[39m Engine revision 2994f7e1e6
    [32m•[39m Dart version 2.7.0

[32m[✓][39m Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    [32m•[39m Android SDK at /Users/learniphi/Library/Android/sdk
    [32m•[39m Android NDK location not configured (optional; useful for native profiling support)
    [32m•[39m Platform android-29, build-tools 29.0.2
    [32m•[39m ANDROID_HOME = /Users/learniphi/Library/Android/sdk
    [32m•[39m Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    [32m•[39m Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    [32m•[39m All Android licenses accepted.

[32m[✓][39m Xcode - develop for iOS and macOS (Xcode 11.3.1)
    [32m•[39m Xcode at /Applications/Xcode.app/Contents/Developer
    [32m•[39m Xcode 11.3.1, Build version 11C504
    [32m•[39m CocoaPods version 1.8.4

[32m[✓][39m Android Studio (version 3.5)
    [32m•[39m Android Studio at /Applications/Android Studio.app/Contents
    [32m•[39m Flutter plugin version 42.1.1
    [32m•[39m Dart plugin version 191.8593
    [32m•[39m Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[32m[✓][39m VS Code (version 1.41.1)
    [32m•[39m VS Code at /Applications/Visual Studio Code.app/Contents
    [32m•[39m Flutter extension version 3.7.1

[32m[✓][39m Connected device (1 available)
    [32m•[39m A0001 • 57b4b0bb • android-arm • Android 6.0.1 (API 23)

[32m•[39m No issues found!
```
`

**Comment by VladyslavBondarenko** [comment]
Hi @ruturajchavda182 
You can run `sudo flutter run`, what is not very good idea
or became an owner of flutter folder `sudo chown -R $USER /Users/learniphi/development/flutter/` or some specific folder inside
or change permissions `chmod +x /Users/learniphi/development/flutter/.pub-cache/hosted/pub.dartlang.org/paytm-1.0.0/android/gradlew`
or search and try other options

Related to https://github.com/flutter/flutter/issues/46873, https://github.com/flutter/flutter/issues/41526

I hope this will help you

Closing, as this isn't an issue with Flutter itself,
if you disagree please write in the comments and I will reopen it
Thank you

**Comment by ruturajchavda182** [comment]
`chmod +x /Users/learniphi/development/flutter/.pub-cache/hosted/pub.dartlang.org/paytm-1.0.0/android/gradlew` This one is working well. Thank you so much.
