### ISSUE TITLE
'flutter generate' gives exception about OptionsSkew

### ISSUE THREAD

**Issue by SebTardif** [flutter/flutter#49446]
```bash
C:\repos\hotcheapdeal>flutter generate
generating build script...                                         37.6s
starting build daemon...                                            0.2s

Sending crash report to Google.
Crash report sent (report ID: 8e59f442adf107b6)
Oops; flutter has exited unexpectedly.
 
Crash report written to C:\repos\hotcheapdeal\flutter_01.log;
please let us know at https://github.com/flutter/flutter/issues.
```

**Comment by SebTardif** [comment]
The output of flutter_01.log
`
Flutter crash report; please file at https://github.com/flutter/flutter/issues.

## command

flutter generate

## exception

OptionsSkew: Instance of 'OptionsSkew'

```
#0      _handleDaemonStartup (package:build_daemon/client.dart:86:5)
<asynchronous suspension>
#1      BuildDaemonClient.connect (package:build_daemon/client.dart:183:11)
<asynchronous suspension>
#2      BuildRunner.daemon (package:flutter_tools/src/build_runner/build_runner.dart:168:51)
<asynchronous suspension>
#3      GenerateCommand.runCommand (package:flutter_tools/src/commands/generate.dart:32:61)
#4      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:615:18)
#5      _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:73:64)
#6      _rootRunUnary (dart:async/zone.dart:1134:38)
#7      _CustomZone.runUnary (dart:async/zone.dart:1031:19)
#8      _FutureListener.handleValue (dart:async/future_impl.dart:139:18)
#9      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:680:45)
#10     Future._propagateToListeners (dart:async/future_impl.dart:709:32)
#11     Future._completeWithValue (dart:async/future_impl.dart:524:5)
#12     Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:554:7)
#13     _rootRun (dart:async/zone.dart:1126:13)
#14     _CustomZone.run (dart:async/zone.dart:1023:19)
#15     _CustomZone.runGuarded (dart:async/zone.dart:925:7)
#16     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:965:23)
#17     _microtaskLoop (dart:async/schedule_microtask.dart:43:21)
#18     _startMicrotaskLoop (dart:async/schedule_microtask.dart:52:5)
#19     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
#20     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:175:5)
```

## flutter doctor

```
[32m[✓][39m Flutter (Channel beta, v1.12.13+hotfix.6, on Microsoft Windows [Version 10.0.18363.592], locale
    en-US)
    [32m•[39m Flutter version 1.12.13+hotfix.6 at C:\repos\flutter
    [32m•[39m Framework revision 18cd7a3601 (6 weeks ago), 2019-12-11 06:35:39 -0800
    [32m•[39m Engine revision 2994f7e1e6
    [32m•[39m Dart version 2.7.0

[32m[✓][39m Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    [32m•[39m Android SDK at C:\Users\sebta\AppData\Local\Android\sdk
    [32m•[39m Android NDK location not configured (optional; useful for native profiling support)
    [32m•[39m Platform android-29, build-tools 29.0.2
    [32m•[39m Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    [32m•[39m Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)
    [32m•[39m All Android licenses accepted.

[32m[✓][39m Chrome - develop for the web
    [32m•[39m Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[32m[✓][39m Android Studio (version 3.5)
    [32m•[39m Android Studio at C:\Program Files\Android\Android Studio
    [32m•[39m Flutter plugin version 42.1.1
    [32m•[39m Dart plugin version 191.8593
    [32m•[39m Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)

[32m[✓][39m VS Code (version 1.41.1)
    [32m•[39m VS Code at C:\Users\sebta\AppData\Local\Programs\Microsoft VS Code
    [32m•[39m Flutter extension version 3.7.1

[32m[✓][39m Connected device (2 available)
    [32m•[39m Chrome     • chrome     • web-javascript • Google Chrome 79.0.3945.130
    [32m•[39m Web Server • web-server • web-javascript • Flutter Tools

[32m•[39m No issues found!
```

`

**Comment by iapicca** [comment]
Hi @SebTardif 
I have to admit I'm not really familiar with the `flutter generate` command, 
are you trying code generation with `build_runner`?
Could you please run it in `--verbose` mode
and if possible could you provide a reproducible minimal code sample?
Thank you

**Comment by SebTardif** [comment]
I'm unable to reproduce right now. I would think if a crash occur, and a special crash file is generated, the developer will put what he need inside the file, and not have to rely to run again with verbose. Whatever you believe is missing for information should become an action item for crash file generation.

**Comment by jonahwilliams** [comment]
Superseded by https://github.com/flutter/flutter/issues/61508
