### ISSUE TITLE
Tapping a RaisedButton generates an error

### ISSUE THREAD

**Issue by jimbeveridge** [flutter/flutter#495]
I'm running the code below on Android using `flutter start`. When I tap the RaisedButton, I get the error below in my logs:

This was running at commit f97a125eeebc1b4fe804fd590be4d71227e0758c.

```
E/chromium(13483): [ERROR:dart_error.cc(16)] Unhandled exception:
E/chromium(13483): No constructor 'Message' with matching arguments declared in class 'Message'.
E/chromium(13483): 
E/chromium(13483): NoSuchMethodError: incorrect number of arguments passed to method named 'Message'
E/chromium(13483): Receiver: Type: class 'Message'
E/chromium(13483): Tried calling: Message(Instance of '_ByteDataView', Instance(length:0) of '_GrowableList', 128, 0)
E/chromium(13483): Found: Message(dynamic, dynamic)
E/chromium(13483): #0      NoSuchMethodError._throwNew (dart:core-patch/errors_patch.dart:188)
E/chromium(13483): #1      FlutterBinding._handlePointerPacket (packages/flutter/src/rendering/binding.dart:215)
E/chromium(13483): #2      _dispatchPointerPacket (file:///ssd2/sky/engine/src/out/android_Release/gen/sky/bindings/Customhooks.dart:30)
```

Here's the source code:
```
import 'package:flutter/rendering.dart';
import 'package:flutter/painting.dart';
import 'package:flutter/material.dart';

class HelloWorldApp extends StatelessComponent {
  final NavigatorState navigator;

  HelloWorldApp({this.navigator});
  @override Widget build(BuildContext build) {
    return new Center(child: new MyToolBar());
  }
}

class MyToolBar extends ToolBar {
  @override Widget build(BuildContext context) {
    return new RaisedButton(onPressed: () {
      print("-------------------onPressed");
    }, child: new Center(child: new Text('Nice Button')));
  }
}

void main() {
  runApp(new MaterialApp(
      title: 'Tutorial app',
      routes: {'/': (RouteArguments args) => new HelloWorldApp()}));
}
```

**Comment by jimbeveridge** [comment]
Closing: caused by old engine.
