### ISSUE TITLE
flutter has exited unexpectedly while running

### ISSUE THREAD

**Issue by ELmounikor** [flutter/flutter#49515]
Flutter crash report; please file at https://github.com/flutter/flutter/issues.

## command

flutter run

## exception

FileSystemException: FileSystemException: Failed to set file modification time, path = 'C:\Users\dell\Desktop\aidedoc_app\.packages' (OS Error: Accès refusé.
, errno = 5)

```
#0      _File.setLastModifiedSync (dart:io/file_impl.dart:473:7)
#1      ForwardingFile.setLastModifiedSync (package:file/src/forwarding/forwarding_file.dart:62:55)
#2      _DefaultPub.get (package:flutter_tools/src/dart/pub.dart:211:19)
#3      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:599:17)
<asynchronous suspension>
#4      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:515:33)
<asynchronous suspension>
#5      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:146:29)
#6      _rootRun (dart:async/zone.dart:1126:13)
#7      _CustomZone.run (dart:async/zone.dart:1023:19)
#8      _runZoned (dart:async/zone.dart:1518:10)
#9      runZoned (dart:async/zone.dart:1465:12)
#10     AppContext.run (package:flutter_tools/src/base/context.dart:145:18)
#11     FlutterCommand.run (package:flutter_tools/src/runner/flutter_command.dart:505:20)
#12     CommandRunner.runCommand (package:args/command_runner.dart:197:27)
#13     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:413:21)
<asynchronous suspension>
#14     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:146:29)
#15     _rootRun (dart:async/zone.dart:1126:13)
#16     _CustomZone.run (dart:async/zone.dart:1023:19)
#17     _runZoned (dart:async/zone.dart:1518:10)
#18     runZoned (dart:async/zone.dart:1465:12)
#19     AppContext.run (package:flutter_tools/src/base/context.dart:145:18)
#20     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:364:19)
#21     CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:112:25)
#22     new Future.sync (dart:async/future.dart:224:31)
#23     CommandRunner.run (package:args/command_runner.dart:112:14)
#24     FlutterCommandRunner.run (package:flutter_tools/src/runner/flutter_command_runner.dart:250:18)
#25     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:63:22)
#26     _rootRun (dart:async/zone.dart:1126:13)
#27     _CustomZone.run (dart:async/zone.dart:1023:19)
#28     _runZoned (dart:async/zone.dart:1518:10)
#29     runZoned (dart:async/zone.dart:1502:12)
#30     run.<anonymous closure> (package:flutter_tools/runner.dart:61:18)
<asynchronous suspension>
#31     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:146:29)
#32     _rootRun (dart:async/zone.dart:1126:13)
#33     _CustomZone.run (dart:async/zone.dart:1023:19)
#34     _runZoned (dart:async/zone.dart:1518:10)
#35     runZoned (dart:async/zone.dart:1465:12)
#36     AppContext.run (package:flutter_tools/src/base/context.dart:145:18)
#37     runInContext (package:flutter_tools/src/context_runner.dart:64:24)
#38     run (package:flutter_tools/runner.dart:50:10)
#39     main (package:flutter_tools/executable.dart:65:9)
#40     main (file:///C:/b/s/w/ir/k/archive/flutter/packages/flutter_tools/bin/flutter_tools.dart:8:3)
#41     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:305:32)
#42     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:174:12)
```

## flutter doctor

```
[32m[✓][39m Flutter (Channel stable, v1.12.13+hotfix.5, on Microsoft Windows [version 10.0.18363.592], locale fr-FR)
    [32m•[39m Flutter version 1.12.13+hotfix.5 at C:\src\flutter
    [32m•[39m Framework revision 27321ebbad (7 weeks ago), 2019-12-10 18:15:01 -0800
    [32m•[39m Engine revision 2994f7e1e6
    [32m•[39m Dart version 2.7.0

[33m[!][39m Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    [32m•[39m Android SDK at C:\Users\dell\AppData\Local\Android\sdk
    [32m•[39m Android NDK location not configured (optional; useful for native profiling support)
    [32m•[39m Platform android-28, build-tools 28.0.3
    [32m•[39m Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    [32m•[39m Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
    [33m![39m Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses

[33m[!][39m Android Studio (version 3.4)
    [32m•[39m Android Studio at C:\Program Files\Android\Android Studio
    [31m✗[39m Flutter plugin not installed; this adds Flutter specific functionality.
    [31m✗[39m Dart plugin not installed; this adds Dart specific functionality.
    [32m•[39m Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

[32m[✓][39m VS Code (version 1.41.1)
    [32m•[39m VS Code at C:\Users\dell\AppData\Local\Programs\Microsoft VS Code
    [32m•[39m Flutter extension version 3.7.1

[32m[✓][39m Connected device (1 available)
    [32m•[39m Redmi 6A • 27969bfd7d26 • android-arm • Android 9 (API 28)

[33m![39m Doctor found issues in 2 categories.
```

**Comment by iapicca** [comment]
Hi @ELmounikor 
can you please provide your `flutter run --verbose` 
and if possible a reproducible minimal code sample.
Thank you

**Comment by yunjieyj** [comment]
> Hi @ELmounikor
> can you please provide your `flutter run --verbose`
> and if possible a reproducible minimal code sample.
> Thank you

I have the same problem. I recently installed flutter and created the project. After running it in xcode, an error was reported. Same problem as above.

**Comment by iapicca** [comment]
Hi @yunjieyj 
can you please provide your `flutter run --verbose` 
and if possible a reproducible minimal code sample.
Thank you

**Comment by iapicca** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact descriptions what happens, logs and the output of 'flutter doctor -v'  please.
All system setups can be slightly different so it's always better to open new issues and reference related issues.
