### ISSUE TITLE
Flutter run ProcessException: Permission denied

### ISSUE THREAD

**Issue by KHALED-LAKEHAL** [flutter/flutter#49542]
## command

flutter run -v

## exception

> ProcessException: ProcessException: Permission denied
>   Command: /mnt/53a2a19a-a5ca-4a78-94da-9e8a3825a73d/Tools/Developer/Flutter/.pub-cache/hosted/pub.dartlang.org/aeyrium_sensor-1.0.7/android/gradlew -I=/mnt/53a2a19a-a5ca-4a78-94da-9e8a3825a73d/Tools/Developer/Flutter/packages/flutter_tools/gradle/aar_init_script.gradle -Pflutter-root=/mnt/53a2a19a-a5ca-4a78-94da-9e8a3825a73d/Tools/Developer/Flutter -Poutput-dir=/mnt/53a2a19a-a5ca-4a78-94da-9e8a3825a73d/Projects/Mobile/kchatter/build/app -Pis-plugin=true -Ptarget-platform=android-arm,android-arm64,android-x64 assembleAarRelease

```
#0      _DefaultProcessUtils.run (package:flutter_tools/src/base/process.dart:266:37)
<asynchronous suspension>
#1      buildGradleAar (package:flutter_tools/src/android/gradle.dart:548:33)
#2      buildPluginsAsAar (package:flutter_tools/src/android/gradle.dart:711:13)
#3      buildGradleApp (package:flutter_tools/src/android/gradle.dart:257:11)
#4      _AsyncAwaitCompleter.start (dart:async-patch/async_patch.dart:45:6)
#5      buildGradleApp (package:flutter_tools/src/android/gradle.dart:218:28)
#6      buildGradleApp (package:flutter_tools/src/android/gradle.dart:415:19)
#7      _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:73:64)
#8      _rootRunUnary (dart:async/zone.dart:1134:38)
#9      _CustomZone.runUnary (dart:async/zone.dart:1031:19)
#10     _FutureListener.handleValue (dart:async/future_impl.dart:139:18)
#11     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:680:45)
#12     Future._propagateToListeners (dart:async/future_impl.dart:709:32)
#13     Future._completeWithValue (dart:async/future_impl.dart:524:5)
#14     Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:554:7)
#15     _rootRun (dart:async/zone.dart:1126:13)
#16     _CustomZone.run (dart:async/zone.dart:1023:19)
#17     _CustomZone.runGuarded (dart:async/zone.dart:925:7)
#18     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:965:23)
#19     _microtaskLoop (dart:async/schedule_microtask.dart:43:21)
#20     _startMicrotaskLoop (dart:async/schedule_microtask.dart:52:5)
#21     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
#22     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:175:5)
```

## flutter doctor

```
[32m[✓][39m Flutter (Channel stable, v1.12.13+hotfix.5, on Linux, locale en_GB.UTF-8)
    [32m•[39m Flutter version 1.12.13+hotfix.5 at /mnt/53a2a19a-a5ca-4a78-94da-9e8a3825a73d/Tools/Developer/Flutter
    [32m•[39m Framework revision 27321ebbad (7 weeks ago), 2019-12-10 18:15:01 -0800
    [32m•[39m Engine revision 2994f7e1e6
    [32m•[39m Dart version 2.7.0

[32m[✓][39m Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    [32m•[39m Android SDK at /home/khadev/Android/Sdk/
    [32m•[39m Android NDK location not configured (optional; useful for native profiling support)
    [32m•[39m Platform android-29, build-tools 29.0.2
    [32m•[39m ANDROID_HOME = /home/khadev/Android/Sdk/
    [32m•[39m Java binary at: /mnt/53a2a19a-a5ca-4a78-94da-9e8a3825a73d/Tools/Developer/android-studio/jre/bin/java
    [32m•[39m Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    [32m•[39m All Android licenses accepted.

[32m[✓][39m Android Studio (version 3.5)
    [32m•[39m Android Studio at /mnt/53a2a19a-a5ca-4a78-94da-9e8a3825a73d/Tools/Developer/android-studio
    [32m•[39m Flutter plugin version 40.2.2
    [32m•[39m Dart plugin version 191.8580
    [32m•[39m Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[32m[✓][39m VS Code (version 1.41.1)
    [32m•[39m VS Code at /usr/share/code
    [32m•[39m Flutter extension version 3.7.1

[32m[✓][39m Connected device (1 available)
    [32m•[39m Google • 192.168.57.101:5555 • android-x86 • Android 5.0 (API 21)

[32m•[39m No issues found!
```

**Comment by VladyslavBondarenko** [comment]
Hi @KHALED-LAKEHAL 
`chmod +x /mnt/53a2a19a-a5ca-4a78-94da-9e8a3825a73d/Tools/Developer/Flutter/.pub-cache/hosted/pub.dartlang.org/aeyrium_sensor-1.0.7/android/gradlew`
should fix this

Related to https://github.com/flutter/flutter/issues/41526, https://github.com/flutter/flutter/issues/49421, https://github.com/flutter/flutter/issues/47038

**Comment by VladyslavBondarenko** [comment]
@KHALED-LAKEHAL 
Closing, I hope this will help you
If not, please write in the comments and I will reopen it
Thank you
