### ISSUE TITLE
Latest flutter version results in: Initial build of flutter project always throws this error, even though I wrapped the route in a Material App

### ISSUE THREAD

**Issue by cmm610** [flutter/flutter#49618]
The error (only on initial build) with the latest stable version of flutter

```
══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
I/flutter (20717): The following assertion was thrown building FirstRoute:
I/flutter (20717): MediaQuery.of() called with a context that does not contain a MediaQuery.
I/flutter (20717): No MediaQuery ancestor could be found starting from the context that was passed to MediaQuery.of().
I/flutter (20717): This can happen because you do not have a WidgetsApp or MaterialApp widget (those widgets introduce
I/flutter (20717): a MediaQuery), or it can happen if the context you use comes from a widget above those widgets.
I/flutter (20717): The context used was:
I/flutter (20717):   Scaffold
I/flutter (20717): 
I/flutter (20717): The relevant error-causing widget was:
I/flutter (20717):   FirstRoute file:///Users/mcilnayc/IdeaProjects/flut_test/lib/main.dart:7:23
I/flutter (20717): 
I/flutter (20717): When the exception was thrown, this was the stack:
I/flutter (20717): #0      MediaQuery.of (package:flutter/src/widgets/media_query.dart:798:5)
I/flutter (20717): #1      ScaffoldState.didChangeDependencies (package:flutter/src/material/scaffold.dart:1993:50)
I/flutter (20717): #2      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4376:12)
I/flutter (20717): #3      ComponentElement.mount (package:flutter/src/widgets/framework.dart:4201:5)
I/flutter (20717): #4      Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194:14)
I/flutter (20717): #5      Element.updateChild (package:flutter/src/widgets/framework.dart:2988:12)
I/flutter (20717): #6      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4243:16)
I/flutter (20717): #7      Element.rebuild (package:flutter/src/widgets/framework.dart:3947:5)
I/flutter (20717): #8      ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4206:5)
I/flutter (20717): #9      ComponentElement.mount (package:flutter/src/widgets/framework.dart:4201:5)
I/flutter (20717): #10     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194:14)
I/flutter (20717): #11     Element.updateChild (package:flutter/src/widgets/framework.dart:2988:12)
I/flutter (20717): #12     RenderObjectToWidgetElement._rebuild (package:flutter/src/widgets/binding.dart:1028:16)
I/flutter (20717): #13     RenderObjectToWidgetElement.mount (package:flutter/src/widgets/binding.dart:999:5)
I/flutter (20717): #14     RenderObjectToWidgetAdapter.attachToRenderTree.<anonymous closure> (package:flutter/src/widgets/binding.dart:942:17)
I/flutter (20717): #15     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2412:19)
I/flutter (20717): #16     RenderObjectToWidgetAdapter.attachToRenderTree (package:flutter/src/widgets/binding.dart:941:13)
I/flutter (20717): #17     WidgetsBinding.attachRootWidget (package:flutter/src/widgets/binding.dart:819:7)
I/flutter (20717): #18     WidgetsBinding.scheduleAttachRootWidget.<anonymous closure> (package:flutter/src/widgets/binding.dart:804:7)
I/flutter (20717): #27     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:384:19)
I/flutter (20717): #28     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:418:5)
I/flutter (20717): #29     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:174:12)
I/flutter (20717): (elided 8 frames from package dart:async and package dart:async-patch)
I/flutter (20717): 
I/flutter (20717): ════════════════════════════════════════════════════════════════════════════════════════════════════
✓ Built build/app/outputs/apk/debug/app-debug.apk.
Syncing files to device Android SDK built for x86...`

// Copyright 2018 The Flutter team. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

import 'package:flutter/material.dart';

void main() => runApp(myApp());

class myApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'named routes demo',
      initialRoute: '/',
      routes: {
        '/': (context) => FirstRoute(),
        '/second': (context) => SecondRoute()
      }
    );
  }
}
// #docregion FirstRoute
class FirstRoute extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('First screen'),
      ),
      body: Center(
        child: RaisedButton(
          child: Text('launch screen'),
          onPressed: () {
            Navigator.pushNamed(context, '/second');
          },
        ),
      ),
    );
  }
}

class SecondRoute extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text("Second screen"),
      ),
      body: Center(
        child: RaisedButton(
          onPressed: () {
            Navigator.pop(context);
          },
          child: Text('Go back!'),
        ),
      ),
    );
  }
}
```

Flutter version

```
Flutter 1.12.13+hotfix.5 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 27321ebbad (7 weeks ago) • 2019-12-10 18:15:01 -0800
Engine • revision 2994f7e1e6
Tools • Dart 2.7.0
```

**Comment by VladyslavBondarenko** [comment]
Hi @cmm610 
It is strange. I don't have the exception with the code and your flutter version.
You can try to stop your app, run `flutter clean` and run app again.
Please note that 1.12.13+hotfix.5 is already not the latest stable version, but v1.12.13+hotfix.7.
Do you have the exception after running the app before without MaterialApp?
Does it persist after `flutter clean`? or after upgrade?

**Comment by m-Skolnick** [comment]
@cmm610 I recently had a similar issue where old errors were being printed on initial build as well. Try creating a new emulator and see if the error shows when running it on that.

**Comment by cmm610** [comment]
I did a ```flutter upgrade``` to Flutter 1.12.13+hotfix.7 then a ```flutter clean```, but now i am getting a different issue. I also tried to swap out the  ```MaterialApp``` to the ```WidgetsApp``` and also got the same error. (see below) I'll take any other suggestions that you can.

```
Launching lib/main.dart on Android SDK built for x86 in debug mode...
Running Gradle task 'assembleDebug'...
I/flutter ( 1655): ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
I/flutter ( 1655): The following assertion was thrown building myApp(dirty):
I/flutter ( 1655): If neither builder nor onGenerateRoute are provided, the pageRouteBuilder must be specified so that
I/flutter ( 1655): the default handler will know what kind of PageRoute transition to build.
I/flutter ( 1655): 'package:flutter/src/widgets/app.dart':
I/flutter ( 1655): Failed assertion: line 210 pos 10: 'builder != null ||
I/flutter ( 1655):          onGenerateRoute != null ||
I/flutter ( 1655):          pageRouteBuilder != null'
I/flutter ( 1655): 
I/flutter ( 1655): Either the assertion indicates an error in the framework itself, or we should provide substantially
I/flutter ( 1655): more information in this error message to help you determine and fix the underlying cause.
I/flutter ( 1655): In either case, please report this assertion by filing a bug on GitHub:
I/flutter ( 1655):   https://github.com/flutter/flutter/issues/new?template=BUG.md
I/flutter ( 1655): 
I/flutter ( 1655): The relevant error-causing widget was:
I/flutter ( 1655):   myApp file:///Users/mcilnayc/IdeaProjects/flut_test/lib/main.dart:7:23
I/flutter ( 1655): 
I/flutter ( 1655): When the exception was thrown, this was the stack:
I/flutter ( 1655): #2      new WidgetsApp (package:flutter/src/widgets/app.dart:210:10)
I/flutter ( 1655): #3      myApp.build (package:flut_test/main.dart:12:12)
I/flutter ( 1655): #4      StatelessElement.build (package:flutter/src/widgets/framework.dart:4291:28)
I/flutter ( 1655): #5      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4223:15)
I/flutter ( 1655): #6      Element.rebuild (package:flutter/src/widgets/framework.dart:3947:5)
I/flutter ( 1655): #7      ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4206:5)
I/flutter ( 1655): #8      ComponentElement.mount (package:flutter/src/widgets/framework.dart:4201:5)
I/flutter ( 1655): #9      Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194:14)
I/flutter ( 1655): #10     Element.updateChild (package:flutter/src/widgets/framework.dart:2988:12)
I/flutter ( 1655): #11     RenderObjectToWidgetElement._rebuild (package:flutter/src/widgets/binding.dart:1028:16)
I/flutter ( 1655): #12     RenderObjectToWidgetElement.mount (package:flutter/src/widgets/binding.dart:999:5)
I/flutter ( 1655): #13     RenderObjectToWidgetAdapter.attachToRenderTree.<anonymous closure> (package:flutter/src/widgets/binding.dart:942:17)
I/flutter ( 1655): #14     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2412:19)
I/flutter ( 1655): #15     RenderObjectToWidgetAdapter.attachToRenderTree (package:flutter/src/widgets/binding.dart:941:13)
I/flutter ( 1655): #16     WidgetsBinding.attachRootWidget (package:flutter/src/widgets/binding.dart:819:7)
I/flutter ( 1655): #17     WidgetsBinding.scheduleAttachRootWidget.<anonymous closure> (package:flutter/src/widgets/binding.dart:804:7)
I/flutter ( 1655): #26     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:384:19)
I/flutter ( 1655): #27     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:418:5)
I/flutter ( 1655): #28     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:174:12)
I/flutter ( 1655): (elided 10 frames from class _AssertionError, package dart:async, and package dart:async-patch)
I/flutter ( 1655): 
I/flutter ( 1655): ════════════════════════════════════════════════════════════════════════════════════════════════════
```

**Comment by TahaTesser** [comment]
Hi @cmm610 
Are you still experiencing this issue with latest `stable` channel? 
if yes,  can you please provide your `flutter doctor -v` your `flutter run --verbose` 

Not using your code sample 
<details> 
<summary>flutter doctor -v</summary> 

``` 
[✓] Flutter (Channel dev, 1.20.0-2.0.pre, on Mac OS X 10.15.5 19F101, locale
    en-GB)
    • Flutter version 1.20.0-2.0.pre at /Users/tahatesser/Code/flutter_dev
    • Framework revision 15a28159bc (10 days ago), 2020-06-23 04:52:58 -0700
    • Engine revision 91a63d6a44
    • Dart version 2.9.0 (build 2.9.0-19.0.dev 7e72c9ae7e)

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/tahatesser/Code/sdk
    • Platform android-29, build-tools 29.0.3
    • ANDROID_HOME = /Users/tahatesser/Code/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.5, Build version 11E608c
    • CocoaPods version 1.9.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 47.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.46.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.12.1

 
[✓] Connected device (5 available)            
    • SM M305F      • 32003c30dc19668f          • android-arm64  • Android 10
      (API 29)
    • Taha’s iPhone • 00008020-001059882212002E • ios            • iOS 13.5.1
    • macOS desktop • macos                     • darwin-x64     • Mac OS X
      10.15.5 19F101
    • Web Server    • web-server                • web-javascript • Flutter Tools
    • Chrome        • chrome                    • web-javascript • Google Chrome
      83.0.4103.116

• No issues found!
``` 

</details> 
Thank you

**Comment by TahaTesser** [comment]
Without additional information we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.
