### ISSUE TITLE
RenderStack object was given an infinite size during layout.

### ISSUE THREAD

**Issue by robertflesch** [flutter/flutter#49631]
This occurs when trying to add a Position to a Text object in a stack. This is illustrated by stackNotWorking, I get the following exception when using it. For working example use stackWorking. Position is supposed to work in a stack, and indeed it does work for the image, but if you add a Position to the Text it causes the error.
Here is working code to reproduce the error.

```dart
import 'package:flutter/material.dart';
import 'test_list.dart';

// test_page.dart
class TestPage extends StatefulWidget {
  TestPage();

  @override
  TestPageState createState() {
    return TestPageState();
  }
}

class TestPageState extends State<TestPage> {
  void initState() {
    super.initState();
  }

  @override
  Widget build(BuildContext context) {
    var key = GlobalKey<ScaffoldState>();
    return Scaffold(
      key: key,
      body: Row(
          children: [
            Flexible(flex: 180, child: TestList()),
            Flexible(flex: 20, child: Text("test")),
          ])
    );
  }
}

// test_list.dart
// import 'package:flutter/material.dart';

class TestList extends StatelessWidget {
  final Map<int, String> aMap = { 1:'test1', 2:'test1', 3:'test1' };
  TestList();

  @override
  Widget build(BuildContext context) {
    return _buildList(context);
  }

  ListView _buildList(context) {
    return ListView(
        shrinkWrap: true,
        children: [
          for ( MapEntry entry in aMap.entries )
            stackNotWorking( entry.key ),
        ] );
  }

// This works
  Widget stackWorking( int index ) {
    return Stack(
        children: <Widget>[
          Positioned(
              left: 90,
              child: Icon(Icons.home, color: Colors.black, size: 20,) ),
          Text( 'a line of text' )
        ]
    );
  }

// This DOESN'T works
  Widget stackNotWorking( int index ) {
    return Stack(
        children: <Widget>[
        Positioned(
          left: 90,
          child: Icon(Icons.home, color: Colors.black, size: 20,) ),
        Positioned(
          left: 110,
          child: Text( 'a line of text' ) )
    ]
    );
  }
}
```

flutter doctor -v
```
[√] Flutter (Channel stable, v1.12.13+hotfix.5, on Microsoft Windows [Version 10.0.18362.592], locale en-US)

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.1)
[√] Android Studio (version 3.2)
[√] IntelliJ IDEA Community Edition (version 2019.3)
[!] IntelliJ IDEA Ultimate Edition (version 2016.3)
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
    X This install is older than the minimum recommended version of 2017.1.0.
[√] Connected device (1 available)

! Doctor found issues in 1 category.
```

<details>
 <summary>logs</summary>

```
════════ Exception caught by rendering library 
The following assertion was thrown during performLayout():
RenderStack object was given an infinite size during layout.

This probably means that it is a render object that tries to be as big as possible, but it was put inside another render object that allows its children to pick their own size.
The nearest ancestor providing an unbounded height constraint is: RenderIndexedSemantics#31bbb relayoutBoundary=up14 NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
...  parentData: index=0; layoutOffset=0.0 (can use size)
...  constraints: BoxConstraints(w=370.3, 0.0<=h<=Infinity)
...  semantic boundary
...  size: MISSING
...  index: 0
The constraints that applied to the RenderStack were: BoxConstraints(w=370.3, 0.0<=h<=Infinity)
The exact size it was given was: Size(370.3, Infinity)

See https://flutter.dev/docs/development/ui/layout/box-constraints for more information.

The relevant error-causing widget was: 
  Stack file:///E:/dev/purified/lib/test_list.dart:35:12
When the exception was thrown, this was the stack: 
#0      RenderBox.debugAssertDoesMeetConstraints.<anonymous closure> (package:flutter/src/rendering/box.dart:1960:9)
#1      RenderBox.debugAssertDoesMeetConstraints (package:flutter/src/rendering/box.dart:2028:6)
#2      RenderBox.size=.<anonymous closure> (package:flutter/src/rendering/box.dart:1745:7)
#3      RenderBox.size= (package:flutter/src/rendering/box.dart:1747:6)
#4      RenderStack.performLayout (package:flutter/src/rendering/stack.dart:520:7)
...
The following RenderObject was being processed when the exception was fired: RenderStack#98368 relayoutBoundary=up16 NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
...  parentData: <none> (can use size)
...  constraints: BoxConstraints(w=370.3, 0.0<=h<=Infinity)
...  size: Size(370.3, Infinity)
...  alignment: AlignmentDirectional.topStart
...  textDirection: ltr
...  fit: loose
...  overflow: clip
RenderObject: RenderStack#98368 relayoutBoundary=up16 NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
  parentData: <none> (can use size)
  constraints: BoxConstraints(w=370.3, 0.0<=h<=Infinity)
  size: Size(370.3, Infinity)
  alignment: AlignmentDirectional.topStart
  textDirection: ltr
  fit: loose
  overflow: clip
...  child 1: RenderSemanticsAnnotations#b53d9 NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
...    parentData: left=90.0; offset=Offset(0.0, 0.0)
...    constraints: MISSING
...    size: MISSING
...    child: RenderExcludeSemantics#a460a NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
...      parentData: <none>
...      constraints: MISSING
...      size: MISSING
...      excluding: true
...      child: RenderConstrainedBox#e7056 NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
...        parentData: <none>
...        constraints: MISSING
...        size: MISSING
...        additionalConstraints: BoxConstraints(w=20.0, h=20.0)
...        child: RenderPositionedBox#c9368 NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
...          parentData: <none>
...          constraints: MISSING
...          size: MISSING
...          alignment: center
...          textDirection: ltr
...          widthFactor: expand
...          heightFactor: expand
...  child 2: RenderParagraph#3cbd1 NEEDS-LAYOUT NEEDS-PAINT
...    parentData: left=110.0; offset=Offset(0.0, 0.0)
...    constraints: MISSING
...    size: MISSING
...    textAlign: start
...    textDirection: ltr
...    softWrap: wrapping at box width
...    overflow: clip
...    locale: en_US
...    maxLines: unlimited
...    text: TextSpan
...      debugLabel: (englishLike body1 2014).merge(blackMountainView body1)
...      inherit: false
...      color: Color(0xdd000000)
...      family: Roboto
...      size: 14.0
...      weight: 400
...      baseline: alphabetic
...      decoration: TextDecoration.none
...      "a line of text"
══════════════════════════════════════════════════════════════
════════ (2) Exception caught by rendering library 
RenderRepaintBoundary object was given an infinite size during layout.
The relevant error-causing widget was: 
  ListView file:///E:/dev/purified/lib/test_list.dart:13:12
══════════════════════════════════════════════════════════════
```

</details>

**Comment by robertflesch** [comment]
There is a work around for this, but it remains a fundamental flaw IMHO.
The work around is to add a non positioned Text field at the end of the stack.
`return Stack(
        children: <Widget>[
        Positioned(
          left: 90,
          child: Icon(Icons.home, color: Colors.black, size: 20,) ),
        Positioned(
          left: 110,
          child: Text( 'a line of text' ) ),
        Text( '' ) 
    ]`

**Comment by PixelToast** [comment]
The issue is because the stack has an unbounded height, yet has no non-positioned child to base its size on.

What you probably wanted to do instead is make the Text a non-positioned child and give it padding so that it sits 110pt from the left.

**Comment by huangyongxin1986** [comment]
I got the same error,my flutter version is 1.17.3-stable

**Comment by guyo13** [comment]
> 
> 
> I use SingleChildScrollView,its child is Stack,Stack has a child with positioned,I got the same error,my flutter version is 1.17.3-stable.
> if i add Boxconstraints to Stack or remove positioned,the error is gone.
> Because the content's height is unsure,so i use SingleChildScrollView.If i use column,and did not add Boxconstraints to column,it works well.

Pretty much the same situation for me. In my case I use a CustomScrollView with a SliverToBoxAdapter that contains a Stack.

**Comment by darshankawar** [comment]
@robertflesch 
Using https://github.com/flutter/flutter/issues/49631#issuecomment-617884531 implementation, the `RenderStack` issue isn't observed anymore:

```
// This works
  Widget stackWorking( int index ) {
    return Stack(
        children: <Widget>[
          Positioned(
              left: 90,
              child: Icon(Icons.home, color: Colors.black, size: 20,) ),
          Text( 'a line of text' )
        ]
    );
  }

// This DOESN'T works
  Widget stackNotWorking( int index ) {
    return Stack(
        children: <Widget>[
          Positioned(
              left: 90,
              child: Icon(Icons.home, color: Colors.black, size: 20,) ),
          Padding(
            padding: EdgeInsets.only(left: 110),
            child: Text( 'a line of text' ),
          )
        ]
    );
  }
}
```

<img width="333" alt="Screenshot 2021-01-28 at 5 47 51 PM" src="https://user-images.githubusercontent.com/67046386/106137625-f5aef180-6190-11eb-8677-7f98cc25c50a.png">

Does this solution resolve your issue ?

**Comment by robertflesch** [comment]
Indeed, thank you for addressing it.
