### ISSUE TITLE
Can't run starter app on windows: Could not find a file named "pubspec.yaml" in "H:\".

### ISSUE THREAD

**Issue by frosty110** [flutter/flutter#49658]
## Steps to Reproduce

When typing `flutter create my_app` into PowerShell in directory `H:\...\flutter` I'm getting a `Could not find a file named "pubspec.yaml" in "H:\".` error and it's building in the base directory.

## Logs

```
PS H:\0-Coding\flutter> flutter --verbose create my_app
fatal: not a git repository (or any of the parent directories): .git
Building flutter tool...
Running pub upgrade...
[  +11 ms] executing: [H:\src\flutter\] git -c log.showSignature=false log -n 1 --pretty=format:%H
[  +85 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[        ] 9f5ff2306bb3e30b2b98eee79cd231b1336f41f4
[        ] executing: [H:\src\flutter\] git describe --match v*.*.* --first-parent --long --tags
[  +65 ms] Exit code 0 from: git describe --match v*.*.* --first-parent --long --tags
[        ] v1.12.13+hotfix.7-0-g9f5ff2306
[   +5 ms] executing: [H:\src\flutter\] git rev-parse --abbrev-ref --symbolic @{u}
[  +63 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/stable
[        ] executing: [H:\src\flutter\] git ls-remote --get-url origin
[  +58 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[  +90 ms] executing: [H:\src\flutter\] git rev-parse --abbrev-ref HEAD
[  +62 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] stable
[  +39 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +2 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +26 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +2 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +60 ms] Recreating project H:\my_app...
[  +20 ms]   H:\my_app\.gitignore (existing - skipped)
[   +1 ms]   H:\my_app\.idea\libraries\Dart_SDK.xml (existing - skipped)
[        ]   H:\my_app\.idea\libraries\Flutter_for_Android.xml (existing - skipped)
[        ]   H:\my_app\.idea\libraries\KotlinJavaRuntime.xml (existing - skipped)
[        ]   H:\my_app\.idea\modules.xml (existing - skipped)
[        ]   H:\my_app\.idea\runConfigurations\main_dart.xml (existing - skipped)
[        ]   H:\my_app\.idea\workspace.xml (existing - skipped)
[        ]   H:\my_app\.metadata (existing - skipped)
[   +1 ms]   H:\my_app\android\app\build.gradle (existing - skipped)
[        ]   H:\my_app\android\app\src\main\kotlin\com\example\my_app\MainActivity.kt (existing - skipped)
[        ]   H:\my_app\android\build.gradle (existing - skipped)
[        ]   H:\my_app\android\my_app_android.iml (existing - skipped)
[        ]   H:\my_app\android\.gitignore (existing - skipped)
[        ]   H:\my_app\android\app\src\debug\AndroidManifest.xml (existing - skipped)
[   +1 ms]   H:\my_app\android\app\src\main\AndroidManifest.xml (existing - skipped)
[   +1 ms]   H:\my_app\android\app\src\main\res\drawable\launch_background.xml (existing - skipped)
[        ]   H:\my_app\android\app\src\main\res\mipmap-hdpi\ic_launcher.png (existing - skipped)
[   +1 ms]   H:\my_app\android\app\src\main\res\mipmap-mdpi\ic_launcher.png (existing - skipped)
[   +1 ms]   H:\my_app\android\app\src\main\res\mipmap-xhdpi\ic_launcher.png (existing - skipped)
[        ]   H:\my_app\android\app\src\main\res\mipmap-xxhdpi\ic_launcher.png (existing - skipped)
[        ]   H:\my_app\android\app\src\main\res\mipmap-xxxhdpi\ic_launcher.png (existing - skipped)
[        ]   H:\my_app\android\app\src\main\res\values\styles.xml (existing - skipped)
[        ]   H:\my_app\android\app\src\profile\AndroidManifest.xml (existing - skipped)
[        ]   H:\my_app\android\gradle\wrapper\gradle-wrapper.properties (existing - skipped)
[   +1 ms]   H:\my_app\android\gradle.properties (existing - skipped)
[        ]   H:\my_app\android\settings.gradle (existing - skipped)
[        ]   H:\my_app\ios\Runner\AppDelegate.swift (existing - skipped)
[        ]   H:\my_app\ios\Runner\Runner-Bridging-Header.h (existing - skipped)
[        ]   H:\my_app\ios\Runner.xcodeproj\project.pbxproj (existing - skipped)
[        ]   H:\my_app\ios\Runner.xcodeproj\xcshareddata\xcschemes\Runner.xcscheme (existing - skipped)
[        ]   H:\my_app\ios\.gitignore (existing - skipped)
[        ]   H:\my_app\ios\Flutter\AppFrameworkInfo.plist (existing - skipped)
[        ]   H:\my_app\ios\Flutter\Debug.xcconfig (existing - skipped)
[        ]   H:\my_app\ios\Flutter\Release.xcconfig (existing - skipped)
[        ]   H:\my_app\ios\Runner\Assets.xcassets\AppIcon.appiconset\Contents.json (existing - skipped)
[        ]   H:\my_app\ios\Runner\Assets.xcassets\AppIcon.appiconset\Icon-App-1024x1024@1x.png (existing - skipped)
[        ]   H:\my_app\ios\Runner\Assets.xcassets\AppIcon.appiconset\Icon-App-20x20@1x.png (existing - skipped)
[        ]   H:\my_app\ios\Runner\Assets.xcassets\AppIcon.appiconset\Icon-App-20x20@2x.png (existing - skipped)
[   +1 ms]   H:\my_app\ios\Runner\Assets.xcassets\AppIcon.appiconset\Icon-App-20x20@3x.png (existing - skipped)
[        ]   H:\my_app\ios\Runner\Assets.xcassets\AppIcon.appiconset\Icon-App-29x29@1x.png (existing - skipped)
[        ]   H:\my_app\ios\Runner\Assets.xcassets\AppIcon.appiconset\Icon-App-29x29@2x.png (existing - skipped)
[        ]   H:\my_app\ios\Runner\Assets.xcassets\AppIcon.appiconset\Icon-App-29x29@3x.png (existing - skipped)
[        ]   H:\my_app\ios\Runner\Assets.xcassets\AppIcon.appiconset\Icon-App-40x40@1x.png (existing - skipped)
[        ]   H:\my_app\ios\Runner\Assets.xcassets\AppIcon.appiconset\Icon-App-40x40@2x.png (existing - skipped)
[        ]   H:\my_app\ios\Runner\Assets.xcassets\AppIcon.appiconset\Icon-App-40x40@3x.png (existing - skipped)
[        ]   H:\my_app\ios\Runner\Assets.xcassets\AppIcon.appiconset\Icon-App-60x60@2x.png (existing - skipped)
[        ]   H:\my_app\ios\Runner\Assets.xcassets\AppIcon.appiconset\Icon-App-60x60@3x.png (existing - skipped)
[        ]   H:\my_app\ios\Runner\Assets.xcassets\AppIcon.appiconset\Icon-App-76x76@1x.png (existing - skipped)
[        ]   H:\my_app\ios\Runner\Assets.xcassets\AppIcon.appiconset\Icon-App-76x76@2x.png (existing - skipped)
[        ]   H:\my_app\ios\Runner\Assets.xcassets\AppIcon.appiconset\Icon-App-83.5x83.5@2x.png (existing - skipped)
[        ]   H:\my_app\ios\Runner\Assets.xcassets\LaunchImage.imageset\Contents.json (existing - skipped)
[        ]   H:\my_app\ios\Runner\Assets.xcassets\LaunchImage.imageset\LaunchImage.png (existing - skipped)
[        ]   H:\my_app\ios\Runner\Assets.xcassets\LaunchImage.imageset\LaunchImage@2x.png (existing - skipped)
[   +1 ms]   H:\my_app\ios\Runner\Assets.xcassets\LaunchImage.imageset\LaunchImage@3x.png (existing - skipped)
[        ]   H:\my_app\ios\Runner\Assets.xcassets\LaunchImage.imageset\README.md (existing - skipped)
[        ]   H:\my_app\ios\Runner\Base.lproj\LaunchScreen.storyboard (existing - skipped)
[        ]   H:\my_app\ios\Runner\Base.lproj\Main.storyboard (existing - skipped)
[        ]   H:\my_app\ios\Runner\Info.plist (existing - skipped)
[        ]   H:\my_app\ios\Runner.xcodeproj\project.xcworkspace\contents.xcworkspacedata (existing - skipped)
[        ]   H:\my_app\ios\Runner.xcodeproj\xcshareddata\xcschemes\Runner.xcscheme (existing - skipped)
[        ]   H:\my_app\ios\Runner.xcworkspace\contents.xcworkspacedata (existing - skipped)
[        ]   H:\my_app\lib\main.dart (existing - skipped)
[        ]   H:\my_app\my_app.iml (existing - skipped)
[        ]   H:\my_app\pubspec.yaml (existing - skipped)
[        ]   H:\my_app\README.md (existing - skipped)
[        ]   H:\my_app\test\widget_test.dart (existing - skipped)
[  +11 ms] Running "flutter pub get" in my_app...
[   +2 ms] Using H:\src\flutter\.pub-cache for the pub cache.
[        ] executing: [H:\my_app\] H:\src\flutter\bin\cache\dart-sdk\bin\pub.bat --verbose get --no-precompile
[ +153 ms] FINE: Pub 2.7.0
[   +2 ms] IO  : Spawning "cmd /c ver" in H:\.
[  +16 ms] IO  : Finished ver. Exit code 0.
[        ]     | stdout:
[        ]     | |
[        ]     | | Microsoft Windows [Version 10.0.18363.592]
[        ]     | Nothing output on stderr.
[   +2 ms] ERR : Could not find a file named "pubspec.yaml" in "H:\".
[        ] FINE: Exception type: FileException
[  +13 ms] FINE: package:pub/src/pubspec.dart 457:7          new Pubspec.load
[        ]     | package:pub/src/package.dart 136:27         new Package.load
[        ]     | package:pub/src/entrypoint.dart 157:24      new Entrypoint.current
[        ]     | package:pub/src/command.dart 31:59          PubCommand.entrypoint
[        ]     | package:pub/src/command/get.dart 41:12      GetCommand.run
[        ]     | package:args/command_runner.dart 197:27     CommandRunner.runCommand
[        ]     | package:pub/src/command_runner.dart 171:39  PubCommandRunner.runCommand.<fn>
[        ]     | dart:async                                  new Future.sync
[        ]     | package:pub/src/utils.dart 109:12           captureErrors.<fn>
[        ]     | package:stack_trace                         Chain.capture
[        ]     | package:pub/src/utils.dart 122:11           captureErrors
[        ]     | package:pub/src/command_runner.dart 171:13  PubCommandRunner.runCommand
[   +1 ms]     | ===== asynchronous gap ===========================
[        ]     | dart:async                                  Future.catchError
[        ]     | package:pub/src/utils.dart 109:52           captureErrors.<fn>
[        ]     | package:stack_trace                         Chain.capture
[        ]     | package:pub/src/utils.dart 122:11           captureErrors
[        ]     | package:pub/src/command_runner.dart 171:13  PubCommandRunner.runCommand
[        ]     | dart:async                                  _completeOnAsyncReturn
[        ]     | package:pub/src/command_runner.dart         PubCommandRunner._validatePlatform
[        ]     | dart:async                                  _completeOnAsyncReturn
[        ]     | package:pub/src/io.dart                     runProcess.<fn>
[  +11 ms] Running "flutter pub get" in my_app... (completed in 0.2s)
[   +1 ms] "flutter create" took 511ms.
pub get failed (66;     | package:pub/src/io.dart                     runProcess.<fn>)

#0      throwToolExit (package:flutter_tools/src/base/common.dart:28:3)
#1      _DefaultPub.batch (package:flutter_tools/src/dart/pub.dart:295:7)
#2      _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:73:64)
#3      _rootRunUnary (dart:async/zone.dart:1134:38)
#4      _CustomZone.runUnary (dart:async/zone.dart:1031:19)
#5      _FutureListener.handleValue (dart:async/future_impl.dart:139:18)
#6      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:680:45)
#7      Future._propagateToListeners (dart:async/future_impl.dart:709:32)
#8      Future._completeWithValue (dart:async/future_impl.dart:524:5)
#9      _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:32:15)
#10     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:290:13)
#11     _DefaultProcessUtils.stream (package:flutter_tools/src/base/process.dart)
#12     _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:73:64)
#13     _rootRunUnary (dart:async/zone.dart:1134:38)
#14     _CustomZone.runUnary (dart:async/zone.dart:1031:19)
#15     _FutureListener.handleValue (dart:async/future_impl.dart:139:18)
#16     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:680:45)
#17     Future._propagateToListeners (dart:async/future_impl.dart:709:32)
#18     Future._addListener.<anonymous closure> (dart:async/future_impl.dart:389:9)
#19     _rootRun (dart:async/zone.dart:1126:13)
#20     _CustomZone.run (dart:async/zone.dart:1023:19)
#21     _CustomZone.runGuarded (dart:async/zone.dart:925:7)
#22     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:965:23)
#23     _microtaskLoop (dart:async/schedule_microtask.dart:43:21)
#24     _startMicrotaskLoop (dart:async/schedule_microtask.dart:52:5)
#25     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
#26     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:175:5)
```

```
PS H:\0-Coding\flutter> flutter doctor
fatal: not a git repository (or any of the parent directories): .git
Building flutter tool...
Running pub upgrade...
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, v1.12.13+hotfix.7, on Microsoft Windows [Version 10.0.18363.592], locale en-US)

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[√] Android Studio (version 3.5)
[√] VS Code, 64-bit edition (version 1.41.1)
[√] Connected device (1 available)

• No issues found!
PS H:\0-Coding\flutter> flutter --verbose doctor
fatal: not a git repository (or any of the parent directories): .git
Building flutter tool...
Running pub upgrade...
[√] Flutter (Channel stable, v1.12.13+hotfix.7, on Microsoft Windows [Version 10.0.18363.592], locale en-US)
    • Flutter version 1.12.13+hotfix.7 at H:\src\flutter
    • Framework revision 9f5ff2306b (2 days ago), 2020-01-26 22:38:26 -0800
    • Engine revision a67792536c
    • Dart version 2.7.0

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at H:\Programs\Android\Sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • ANDROID_HOME = H:\Programs\Android\Sdk
    • Java binary at: H:\Program Files\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)
    • All Android licenses accepted.

[√] Android Studio (version 3.5)
    • Android Studio at H:\Program Files\Android Studio
    • Flutter plugin version 42.1.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)

[√] VS Code, 64-bit edition (version 1.41.1)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Flutter extension version 3.7.1

[√] Connected device (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 8.1.0 (API 27) (emulator)

• No issues found!
```

**Please note that flutter keeps rebulding flutter tool. I think this is also because of the directory issue.**

**Comment by jonahwilliams** [comment]
Your current working directory is H:\, you need to change directories to my_app

**Comment by frosty110** [comment]
If you take a look at the logs, isn't that what I'm doing? `H:\0-Coding\flutter> flutter --verbose create my_app`

**Comment by frosty110** [comment]
Hi @jonahwilliams , let me be a bit more clear. My working directory is H:/0-coding/flutter when I run the `flutter create my_app`; however, my_app is created in my root H directory. When I cd into my_app folder `H;/my_app` and run `flutter packages get`, I get the following output

```
PS H:\my_app> flutter --verbose packages get
fatal: not a git repository (or any of the parent directories): .git
Building flutter tool...
Running pub upgrade...
[  +11 ms] executing: [H:\src\flutter\] git -c log.showSignature=false log -n 1 --pretty=format:%H
[  +81 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[   +1 ms] 9f5ff2306bb3e30b2b98eee79cd231b1336f41f4
[        ] executing: [H:\src\flutter\] git describe --match v*.*.* --first-parent --long --tags
[  +60 ms] Exit code 0 from: git describe --match v*.*.* --first-parent --long --tags
[   +1 ms] v1.12.13+hotfix.7-0-g9f5ff2306
[   +6 ms] executing: [H:\src\flutter\] git rev-parse --abbrev-ref --symbolic @{u}
[  +58 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[   +1 ms] origin/stable
[        ] executing: [H:\src\flutter\] git ls-remote --get-url origin
[  +53 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[  +84 ms] executing: [H:\src\flutter\] git rev-parse --abbrev-ref HEAD
[  +56 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[   +1 ms] stable
[  +46 ms] "flutter get" took 99ms.
Error: No pubspec.yaml file found.
This command should be run from the root of your Flutter project.
Do not run this command from the root of your git clone of Flutter.

#0      FlutterCommand.validateCommand (package:flutter_tools/src/runner/flutter_command.dart:690:9)
#1      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:590:11)
#2      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:515:33)
<asynchronous suspension>
#3      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:146:29)
#4      _rootRun (dart:async/zone.dart:1126:13)
#5      _CustomZone.run (dart:async/zone.dart:1023:19)
#6      _runZoned (dart:async/zone.dart:1518:10)
#7      runZoned (dart:async/zone.dart:1465:12)
#8      AppContext.run (package:flutter_tools/src/base/context.dart:145:18)
#9      FlutterCommand.run (package:flutter_tools/src/runner/flutter_command.dart:505:20)
#10     CommandRunner.runCommand (package:args/command_runner.dart:197:27)
#11     FlutterCommandRunner.runCommand.<anonymous closure>
(package:flutter_tools/src/runner/flutter_command_runner.dart:413:21)
<asynchronous suspension>
#12     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:146:29)
#13     _rootRun (dart:async/zone.dart:1126:13)
#14     _CustomZone.run (dart:async/zone.dart:1023:19)
#15     _runZoned (dart:async/zone.dart:1518:10)
#16     runZoned (dart:async/zone.dart:1465:12)
#17     AppContext.run (package:flutter_tools/src/base/context.dart:145:18)
#18     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:364:19)
#19     CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:112:25)
#20     new Future.sync (dart:async/future.dart:224:31)
#21     CommandRunner.run (package:args/command_runner.dart:112:14)
#22     FlutterCommandRunner.run (package:flutter_tools/src/runner/flutter_command_runner.dart:250:18)
#23     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:63:22)
#24     _rootRun (dart:async/zone.dart:1126:13)
#25     _CustomZone.run (dart:async/zone.dart:1023:19)
#26     _runZoned (dart:async/zone.dart:1518:10)
#27     runZoned (dart:async/zone.dart:1502:12)
#28     run.<anonymous closure> (package:flutter_tools/runner.dart:61:18)
<asynchronous suspension>
#29     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:146:29)
#30     _rootRun (dart:async/zone.dart:1126:13)
#31     _CustomZone.run (dart:async/zone.dart:1023:19)
#32     _runZoned (dart:async/zone.dart:1518:10)
#33     runZoned (dart:async/zone.dart:1465:12)
#34     AppContext.run (package:flutter_tools/src/base/context.dart:145:18)
#35     runInContext (package:flutter_tools/src/context_runner.dart:64:24)
#36     run (package:flutter_tools/runner.dart:50:10)
#37     main (package:flutter_tools/executable.dart:65:9)
#38     main (file:///H:/src/flutter/packages/flutter_tools/bin/flutter_tools.dart:8:3)
#39     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:305:32)
#40     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:174:12)
```

**Comment by frosty110** [comment]
@jonahwilliams 
Also, no matter which method I use for creating a project: vscode, android studio, and terminal I get the same error: `Could not find a file named "pubspec.yaml" in "H:\".` I don't understand why my flutter commands are referenced from the root directory.

**Comment by frosty110** [comment]
I was able to get this working on a new user on the same PC following the same steps. So the issue is definitely only on my end.

**Comment by iapicca** [comment]
Hi @frosty110 
I see there's an open [issue](https://github.com/flutter/flutter/issues/46230) addressing the case you described.
Please follow up on that issue,
I'm closing the current one as duplicate.
If you disagree please write in the comments
and I will reopen it.
Thank you
