### ISSUE TITLE
[Devicelab] lockdownd, error code -8

### ISSUE THREAD

**Issue by digiter** [flutter/flutter#49668]
Mac6 throws this error:
```
stdout: [        ] List of devices attached
2020-01-28T18:07:15.425829: stdout: [  +12 ms] executing: /Users/flutter/.cocoon/flutter/bin/cache/artifacts/libimobiledevice/idevice_id -h
2020-01-28T18:07:15.490741: stdout: [  +64 ms] "flutter drive" took 126ms.
2020-01-28T18:07:15.495251: stderr: ideviceinfo returned an error:
stderr: ERROR: Could not connect to lockdownd, error code -8
stderr: 
2020-01-28T18:07:15.495677: stderr: 
stderr: #0      IMobileDevice.getInfoForDevice (package:flutter_tools/src/ios/mac.dart:224:9)
stderr: <asynchronous suspension>
stderr: #1      IOSDevice.getAttachedDevices (package:flutter_tools/src/ios/devices.dart:189:55)
stderr: <asynchronous suspension>
stderr: #2      IOSDevices.pollingGetDevices (package:flutter_tools/src/ios/devices.dart:114:57)
stderr: #3      PollingDeviceDiscovery.devices (package:flutter_tools/src/device.dart:285:52)
stderr: #4      DeviceManager.getAllConnectedDevices (package:flutter_tools/src/device.dart:140:52)
stderr: <asynchronous suspension>
```
Here are the things that I tried:

1. `/usr/local/bin/idevice_id -l` works, which is installed from homebrew.
1.  This command also works.
```
DYLD_LIBRARY_PATH=/Users/flutter/.cocoon/flutter/bin/cache/artifacts/libimobiledevice:/Users/flutter/.cocoon/flutter/bin/cache/artifacts/openssl:/Users/flutter/.cocoon/flutter/bin/cache/artifacts/usbmuxd:/Users/flutter/.cocoon/flutter/bin/cache/artifacts/libplist /Users/flutter/.cocoon/flutter/bin/cache/artifacts/libimobiledevice/idevice_id -l
```

/cc @jmagman @christopherfujino

**Comment by digiter** [comment]
Found that mac6 has a system update dialog.

**Comment by digiter** [comment]
Rebooting both the host and device fixed it.
