### ISSUE TITLE
[backend] 500s status /api/check-waiting-pull-requests

### ISSUE THREAD

**Issue by godofredoc** [flutter/flutter#49671]
Bad state: No element
#0      List.single (dart:core-patch/growable_array.dart:232:22)
#1      CheckForWaitingPullRequests._parseQueryData (package:cocoon_service/src/request_handlers/check_for_waiting_pull_requests.dart:160:70)
#2      CheckForWaitingPullRequests._checkPRs (package:cocoon_service/src/request_handlers/check_for_waiting_pull_requests.dart:56:47)
<asynchronous suspension>
#3      CheckForWaitingPullRequests.get (package:cocoon_service/src/request_handlers/check_for_waiting_pull_requests.dart:37:11)
<asynchronous suspension>
#4      RequestHandler.service.<anonymous closure> (package:cocoon_service/src/request_handling/request_handler.dart:46:28)
<asynchronous suspension>
#5      _rootRun (dart:async/zone.dart:1126:13)
#6      _CustomZone.run (dart:async/zone.dart:1023:19)
#7      _runZoned (dart:async/zone.dart:1518:10)
#8      runZoned (dart:async/zone.dart:1465:12)
#9      RequestHandler.service (package:cocoon_service/src/request_handling/request_handler.dart:39:12)
#10     ApiRequestHandler.service.<anonymous closure> (package:cocoon_service/src/request_handling/api_request_handler.dart:139:19)
#11     _rootRun (dart:async/zone.dart:1126:13)
#12     _CustomZone.run (dart:async/zone.dart:1023:19)
#13     _runZoned (dart:async/zone.dart:1518:10)
#14     runZoned (dart:async/zone.dart:1465:12)
#15     ApiRequestHandler.service (package:cocoon_service/src/request_handling/api_request_handler.dart:138:11)

**Comment by godofredoc** [comment]
Fixed with: 
Update remaining handlers to use service/datastore https://github.com/flutter/cocoon/pull/737.
Refactor handlers to use service/datastore https://github.com/flutter/cocoon/pull/736. 
Refactor reserve_task handler to use datastore https://github.com/flutter/cocoon/pull/732.
