### ISSUE TITLE
gen_l10n outputs unexpected diff and causes unhandled exception

### ISSUE THREAD

**Issue by perclasson** [flutter/flutter#49689]
## Steps to Reproduce

1. Clone the following repo https://github.com/shihaohong/gen_l10n_formatting
2. Run the command to generate an app_localizations.dart with flutter channel master: `~/development/flutter/bin/cache/dart-sdk/bin/dart ~/development/flutter/dev/tools/localization/bin/gen_l10n.dart --template-arb-file=app_en.arb`
3. The tool crashes and ouputs app_localizations.dart with unexpected diff (some of the values are not replaced correctly)

Error
====
```dart
Unhandled exception:
Error in <unknown source>: Expected to find ';'.

Error in <unknown source>: Expected an identifier.

Error in <unknown source>: Expected an identifier.

#0      _parseSource (package:analyzer/analyzer.dart:155:52)
#1      parseCompilationUnit (package:analyzer/analyzer.dart:58:10)
#2      MessageExtraction._parseCompilationUnit (package:intl_translation/extract_messages.dart:100:16)
#3      MessageExtraction.parseFile (package:intl_translation/extract_messages.dart:87:14)
#4      main.<anonymous closure> (file:///Users/perc/.pub-cache/hosted/pub.dartlang.org/intl_translation-0.17.7/bin/generate_from_arb.dart:98:33)
#5      MappedListIterable.elementAt (dart:_internal/iterable.dart:417:29)
#6      ListIterator.moveNext (dart:_internal/iterable.dart:346:26)
#7      main (file:///Users/perc/.pub-cache/hosted/pub.dartlang.org/intl_translation-0.17.7/bin/generate_from_arb.dart:101:23)
#8      _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:299:32)
#9      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:168:12)
pub finished with exit code 255
```

Diff
===
```diff
diff --git a/lib/l10n/app_localizations.dart b/lib/l10n/app_localizations.dart
index 89c951f..7abb1b7 100644
--- a/lib/l10n/app_localizations.dart
+++ b/lib/l10n/app_localizations.dart
@@ -56,7 +56,7 @@ import 'messages_all.dart';
 /// Select and expand the newly-created Localizations item then, for each
 /// locale your application supports, add a new item and select the locale
 /// you wish to add from the pop-up menu in the Value field. This list should
-/// be consistent with the languages listed in the AppLocalizations.supportedLocales
+/// be consistent with the languages listed in the @className.supportedLocales
 /// property.
 class AppLocalizations {
   AppLocalizations(Locale locale) : _localeName = Intl.canonicalizedLocale(locale.toString());
@@ -72,7 +72,7 @@ class AppLocalizations {
     return Localizations.of<AppLocalizations>(context, AppLocalizations);
   }

-  static const LocalizationsDelegate<AppLocalizations> delegate = _AppLocalizationsDelegate();
+  static const LocalizationsDelegate<AppLocalizations> delegate = _@(classNameDelegate)();

   /// A list of this localizations delegate along with the default localizations
   /// delegates.
@@ -97,20 +97,23 @@ class AppLocalizations {
     Locale('en'),
   ];

-  String responseDueBy(Object time, Object day) {
+  String responseDueBy(DateTime time, DateTime day) {
     final DateFormat timeDateFormat = DateFormat.Hm(_localeName);
     final String timeString = timeDateFormat.format(time);

     final DateFormat dayDateFormat = DateFormat.yMMMMEEEEd(_localeName);
     final String dayString = dayDateFormat.format(day);

-    return Intl.message(
-      'The response is due by $timeString on $dayString.',
-      locale: _localeName,
-      name: 'responseDueBy',
-      desc: r'Response due time',
-      args: <Object>[timeString, dayString]
-    );
+    String responseDueBy(Object time, Object day) {
+      return Intl.message(
+        'The response is due by $time on $day.',
+        locale: _localeName,
+        name: 'responseDueBy',
+        desc: r'Response due time',
+        args: <Object>[time, day]
+      );
+    }
+    return responseDueBy(timeString, dayString);
   }

 }

```
## Cause
It seems as if this was caused by https://github.com/flutter/flutter/pull/49357, as reverting that commit solves the issue.

<details>
  <summary>Logs</summary>

```
[✓] Flutter (Channel master, v1.14.4-pre.116, on Mac OS X 10.15.2 19C57, locale en-DE)
    • Flutter version 1.14.4-pre.116 at /Users/perc/development/flutter
    • Framework revision 4f460a932b (4 hours ago), 2020-01-29 01:17:41 -0500
    • Engine revision f4b2183f1b
    • Dart version 2.8.0 (build 2.8.0-dev.5.0 fc3af737c7)


[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/perc/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-stable, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.3.1, Build version 11C505
    • CocoaPods version 1.8.4

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[!] Android Studio
    • Android Studio at /Applications/Android Studio with Blaze.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 42.1.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[!] VS Code (version 1.41.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    ✗ Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (4 available)
    • iPhone 11 Pro Max • 81158E5C-C27D-49D1-9FD9-55EE1011FEBF • ios            • com.apple.CoreSimulator.SimRuntime.iOS-13-3 (simulator)
    • macOS             • macOS                                • darwin-x64     • Mac OS X 10.15.2 19C57
    • Chrome            • chrome                               • web-javascript • Google Chrome 79.0.3945.130
    • Web Server        • web-server                           • web-javascript • Flutter Tools
```

</details>

**Comment by perclasson** [comment]
cc @HansMuller

**Comment by HansMuller** [comment]
This is (also) fixed in https://github.com/flutter/flutter/pull/49586, which introduces real integration testing.  Once it lands, this kind of error should not happen again.

**Comment by perclasson** [comment]
Thanks. Works great now, closing the issue.
