### ISSUE TITLE
Unable to run 'adb' commands at the same time as Flutter running on an Android emulator/device

### ISSUE THREAD

**Issue by acoutts** [flutter/flutter#49696]
## Steps to Reproduce
```
Flutter 1.12.13+hotfix.7 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 9f5ff2306b (2 days ago) • 2020-01-26 22:38:26 -0800
Engine • revision a67792536c
Tools • Dart 2.7.0
```

1. `flutter start` in one terminal
2. Open a second terminal and try to run `adb logcat`
adb will fail to start and report the following:
```
adb server version (41) doesn't match this client (39); killing...
ADB server didn't ACK
Full server startup log: /tmp/adb.1000.log
Server had pid: 15880
--- adb starting (pid 15880) ---
adb I 01-29 09:14:14 15880 15880 main.cpp:57] Android Debug Bridge version 1.0.39
adb I 01-29 09:14:14 15880 15880 main.cpp:57] Version 1:8.1.0+r23-5~18.04
adb I 01-29 09:14:14 15880 15880 main.cpp:57] Installed as /usr/lib/android-sdk/platform-tools/adb
adb I 01-29 09:14:14 15880 15880 main.cpp:57] 
adb I 01-29 09:14:14 15880 15880 adb_auth_host.cpp:416] adb_auth_init...
adb I 01-29 09:14:14 15880 15880 adb_auth_host.cpp:174] read_key_file '/home/xff0c/.android/adbkey'...
adb I 01-29 09:14:14 15880 15880 adb_auth_host.cpp:391] adb_auth_inotify_init...
adb server killed by remote request

* failed to start daemon
- waiting for device -
* daemon not running; starting now at tcp:5037
ADB server didn't ACK
Full server startup log: /tmp/adb.1000.log
Server had pid: 15893
--- adb starting (pid 15893) ---
adb I 01-29 09:14:14 15892 15892 adb.cpp:110] emulator-5556: already offline
adb I 01-29 09:14:14 15893 15893 main.cpp:57] Android Debug Bridge version 1.0.39
adb I 01-29 09:14:14 15893 15893 main.cpp:57] Version 1:8.1.0+r23-5~18.04
adb I 01-29 09:14:14 15893 15893 main.cpp:57] Installed as /usr/lib/android-sdk/platform-tools/adb
adb I 01-29 09:14:14 15893 15893 main.cpp:57] 
error: could not install *smartsocket* listener: Address already in use

* failed to start daemon
error: cannot connect to daemon
```

But if you try to go the other way around (start `adb logcat` first, then flutter), then adb crashes and flutter opens. I can't get them both to run at the same time.

Without this I'm unable to view the Android system logs in realtime which makes debugging really hard. I can do this with React Native, so there must be something different in Flutter that prevents adb to work together with it.

**Expected results:** 
Should be able to run adb commands with flutter at the same time.

**Actual results:** 
Only one can run at once.

<details>
  <summary>Logs</summary>

```
...
[   +9 ms] <- compile package:bottle_app_flutter/main.dart
[+2234 ms] Service protocol connection closed.
[        ] Lost connection to device.
[+2004 ms] Updating files
[   +4 ms] Error writing "build/flutter_assets/assets/images/bolt-background.svg" to DevFS: SocketException: OS Error: Connection refused, errno = 111, address = 127.0.0.1, port = 57968
[        ] trying again in a few - 9 more attempts left
[        ] Error writing "build/flutter_assets/assets/images/bottle-logo.svg" to DevFS: SocketException: OS Error: Connection refused, errno = 111, address = 127.0.0.1, port = 57970
[        ] trying again in a few - 9 more attempts left
[        ] Error writing "build/flutter_assets/assets/images/x-icon.svg" to DevFS: SocketException: OS Error: Connection refused, errno = 111, address = 127.0.0.1, port = 57972
[        ] trying again in a few - 9 more attempts left
[        ] Error writing "build/flutter_assets/assets/images/app-icon.png" to DevFS: SocketException: OS Error: Connection refused, errno = 111, address = 127.0.0.1, port = 57974
[        ] trying again in a few - 9 more attempts left
[        ] Error writing "build/flutter_assets/assets/images/receipt.svg" to DevFS: SocketException: OS Error: Connection refused, errno = 111, address = 127.0.0.1, port = 57976
[        ] trying again in a few - 9 more attempts left
[        ] Error writing "build/flutter_assets/assets/images/question-circle.svg" to DevFS: SocketException: OS Error: Connection refused, errno = 111, address = 127.0.0.1, port = 57978
[        ] trying again in a few - 9 more attempts left
[ +502 ms] Error writing "build/flutter_assets/assets/images/bolt-background.svg" to DevFS: SocketException: OS Error: Connection refused, errno = 111, address = 127.0.0.1, port = 57998
[        ] trying again in a few - 8 more attempts left
[        ] Error writing "build/flutter_assets/assets/images/bottle-logo.svg" to DevFS: SocketException: OS Error: Connection refused, errno = 111, address = 127.0.0.1, port = 58000
[        ] trying again in a few - 8 more attempts left
[        ] Error writing "build/flutter_assets/assets/images/x-icon.svg" to DevFS: SocketException: OS Error: Connection refused, errno = 111, address = 127.0.0.1, port = 58002
[        ] trying again in a few - 8 more attempts left
[        ] Error writing "build/flutter_assets/assets/images/app-icon.png" to DevFS: SocketException: OS Error: Connection refused, errno = 111, address = 127.0.0.1, port = 58004
[        ] trying again in a few - 8 more attempts left
[        ] Error writing "build/flutter_assets/assets/images/receipt.svg" to DevFS: SocketException: OS Error: Connection refused, errno = 111, address = 127.0.0.1, port = 58006
[        ] trying again in a few - 8 more attempts left
[        ] Error writing "build/flutter_assets/assets/images/question-circle.svg" to DevFS: SocketException: OS Error: Connection refused, errno = 111, address = 127.0.0.1, port = 58008
[        ] trying again in a few - 8 more attempts left
[ +500 ms] Error writing "build/flutter_assets/assets/images/bolt-background.svg" to DevFS: SocketException: OS Error: Connection refused, errno = 111, address = 127.0.0.1, port = 58030
[        ] trying again in a few - 7 more attempts left
[   +1 ms] Error writing "build/flutter_assets/assets/images/bottle-logo.svg" to DevFS: SocketException: OS Error: Connection refused, errno = 111, address = 127.0.0.1, port = 58032
[        ] trying again in a few - 7 more attempts left
[        ] Error writing "build/flutter_assets/assets/images/x-icon.svg" to DevFS: SocketException: OS Error: Connection refused, errno = 111, address = 127.0.0.1, port = 58034
[        ] trying again in a few - 7 more attempts left
[        ] Error writing "build/flutter_assets/assets/images/app-icon.png" to DevFS: SocketException: OS Error: Connection refused, errno = 111, address = 127.0.0.1, port = 58036
[        ] trying again in a few - 7 more attempts left
[        ] Error writing "build/flutter_assets/assets/images/receipt.svg" to DevFS: SocketException: OS Error: Connection refused, errno = 111, address = 127.0.0.1, port = 58038
[        ] trying again in a few - 7 more attempts left
[        ] Error writing "build/flutter_assets/assets/images/question-circle.svg" to DevFS: SocketException: OS Error: Connection refused, errno = 111, address = 127.0.0.1, port = 58040
[        ] trying again in a few - 7 more attempts left
[ +499 ms] Error writing "build/flutter_assets/assets/images/bolt-background.svg" to DevFS: SocketException: OS Error: Connection refused, errno = 111, address = 127.0.0.1, port = 58044
[        ] trying again in a few - 6 more attempts left
[   +1 ms] Error writing "build/flutter_assets/assets/images/bottle-logo.svg" to DevFS: SocketException: OS Error: Connection refused, errno = 111, address = 127.0.0.1, port = 58046
[        ] trying again in a few - 6 more attempts left
[   +1 ms] Error writing "build/flutter_assets/assets/images/x-icon.svg" to DevFS: SocketException: OS Error: Connection refused, errno = 111, address = 127.0.0.1, port = 58048
[        ] trying again in a few - 6 more attempts left
[        ] Error writing "build/flutter_assets/assets/images/app-icon.png" to DevFS: SocketException: OS Error: Connection refused, errno = 111, address = 127.0.0.1, port = 58050
[        ] trying again in a few - 6 more attempts left
[        ] Error writing "build/flutter_assets/assets/images/receipt.svg" to DevFS: SocketException: OS Error: Connection refused, errno = 111, address = 127.0.0.1, port = 58052
[        ] trying again in a few - 6 more attempts left
[        ] Error writing "build/flutter_assets/assets/images/question-circle.svg" to DevFS: SocketException: OS Error: Connection refused, errno = 111, address = 127.0.0.1, port = 58054
[        ] trying again in a few - 6 more attempts left
[ +496 ms] Error writing "build/flutter_assets/assets/images/bolt-background.svg" to DevFS: SocketException: OS Error: Connection refused, errno = 111, address = 127.0.0.1, port = 58108
[        ] trying again in a few - 5 more attempts left
[   +1 ms] Error writing "build/flutter_assets/assets/images/bottle-logo.svg" to DevFS: SocketException: OS Error: Connection refused, errno = 111, address = 127.0.0.1, port = 58110
[        ] trying again in a few - 5 more attempts left
[   +1 ms] Error writing "build/flutter_assets/assets/images/x-icon.svg" to DevFS: SocketException: OS Error: Connection refused, errno = 111, address = 127.0.0.1, port = 58112
[        ] trying again in a few - 5 more attempts left
[   +1 ms] Error writing "build/flutter_assets/assets/images/app-icon.png" to DevFS: SocketException: OS Error: Connection refused, errno = 111, address = 127.0.0.1, port = 58116
[        ] trying again in a few - 5 more attempts left
[        ] Error writing "build/flutter_assets/assets/images/receipt.svg" to DevFS: SocketException: OS Error: Connection refused, errno = 111, address = 127.0.0.1, port = 58118
[        ] trying again in a few - 5 more attempts left
[        ] Error writing "build/flutter_assets/assets/images/question-circle.svg" to DevFS: SocketException: OS Error: Connection refused, errno = 111, address = 127.0.0.1, port = 58120
[        ] trying again in a few - 5 more attempts left
[ +495 ms] Error writing "build/flutter_assets/assets/images/bolt-background.svg" to DevFS: SocketException: OS Error: Connection refused, errno = 111, address = 127.0.0.1, port = 58148
[        ] trying again in a few - 4 more attempts left
[   +1 ms] Error writing "build/flutter_assets/assets/images/bottle-logo.svg" to DevFS: SocketException: OS Error: Connection refused, errno = 111, address = 127.0.0.1, port = 58150
[        ] trying again in a few - 4 more attempts left
[   +1 ms] Error writing "build/flutter_assets/assets/images/x-icon.svg" to DevFS: SocketException: OS Error: Connection refused, errno = 111, address = 127.0.0.1, port = 58152
[        ] trying again in a few - 4 more attempts left
[   +2 ms] Error writing "build/flutter_assets/assets/images/app-icon.png" to DevFS: SocketException: OS Error: Connection refused, errno = 111, address = 127.0.0.1, port = 58154
[        ] trying again in a few - 4 more attempts left
[        ] Error writing "build/flutter_assets/assets/images/receipt.svg" to DevFS: SocketException: OS Error: Connection refused, errno = 111, address = 127.0.0.1, port = 58156
[        ] trying again in a few - 4 more attempts left
[   +1 ms] Error writing "build/flutter_assets/assets/images/question-circle.svg" to DevFS: SocketException: OS Error: Connection refused, errno = 111, address = 127.0.0.1, port = 58158
[        ] trying again in a few - 4 more attempts left
[ +494 ms] Error writing "build/flutter_assets/assets/images/bolt-background.svg" to DevFS: SocketException: OS Error: Connection refused, errno = 111, address = 127.0.0.1, port = 58172
[        ] trying again in a few - 3 more attempts left
[   +2 ms] Error writing "build/flutter_assets/assets/images/bottle-logo.svg" to DevFS: SocketException: OS Error: Connection refused, errno = 111, address = 127.0.0.1, port = 58174
[        ] trying again in a few - 3 more attempts left
[        ] Error writing "build/flutter_assets/assets/images/x-icon.svg" to DevFS: SocketException: OS Error: Connection refused, errno = 111, address = 127.0.0.1, port = 58176
[        ] trying again in a few - 3 more attempts left
[   +2 ms] Error writing "build/flutter_assets/assets/images/app-icon.png" to DevFS: SocketException: OS Error: Connection refused, errno = 111, address = 127.0.0.1, port = 58178
[        ] trying again in a few - 3 more attempts left
[   +1 ms] Error writing "build/flutter_assets/assets/images/receipt.svg" to DevFS: SocketException: OS Error: Connection refused, errno = 111, address = 127.0.0.1, port = 58180
[        ] trying again in a few - 3 more attempts left
[        ] Error writing "build/flutter_assets/assets/images/question-circle.svg" to DevFS: SocketException: OS Error: Connection refused, errno = 111, address = 127.0.0.1, port = 58182
[        ] trying again in a few - 3 more attempts left
[ +493 ms] Error writing "build/flutter_assets/assets/images/bolt-background.svg" to DevFS: SocketException: OS Error: Connection refused, errno = 111, address = 127.0.0.1, port = 58192
[        ] trying again in a few - 2 more attempts left
[   +2 ms] Error writing "build/flutter_assets/assets/images/bottle-logo.svg" to DevFS: SocketException: OS Error: Connection refused, errno = 111, address = 127.0.0.1, port = 58196
[        ] trying again in a few - 2 more attempts left
[        ] Error writing "build/flutter_assets/assets/images/x-icon.svg" to DevFS: SocketException: OS Error: Connection refused, errno = 111, address = 127.0.0.1, port = 58198
[        ] trying again in a few - 2 more attempts left
[   +1 ms] Error writing "build/flutter_assets/assets/images/app-icon.png" to DevFS: SocketException: OS Error: Connection refused, errno = 111, address = 127.0.0.1, port = 58200
[        ] trying again in a few - 2 more attempts left
[   +1 ms] Error writing "build/flutter_assets/assets/images/receipt.svg" to DevFS: SocketException: OS Error: Connection refused, errno = 111, address = 127.0.0.1, port = 58202
[        ] trying again in a few - 2 more attempts left
[        ] Error writing "build/flutter_assets/assets/images/question-circle.svg" to DevFS: SocketException: OS Error: Connection refused, errno = 111, address = 127.0.0.1, port = 58204
[        ] trying again in a few - 2 more attempts left
[ +494 ms] Error writing "build/flutter_assets/assets/images/bolt-background.svg" to DevFS: SocketException: OS Error: Connection refused, errno = 111, address = 127.0.0.1, port = 58218
[        ] trying again in a few - 1 more attempts left
[   +3 ms] Error writing "build/flutter_assets/assets/images/bottle-logo.svg" to DevFS: SocketException: OS Error: Connection refused, errno = 111, address = 127.0.0.1, port = 58220
[        ] trying again in a few - 1 more attempts left
[        ] Error writing "build/flutter_assets/assets/images/x-icon.svg" to DevFS: SocketException: OS Error: Connection refused, errno = 111, address = 127.0.0.1, port = 58222
[        ] trying again in a few - 1 more attempts left
[   +1 ms] Error writing "build/flutter_assets/assets/images/app-icon.png" to DevFS: SocketException: OS Error: Connection refused, errno = 111, address = 127.0.0.1, port = 58224
[        ] trying again in a few - 1 more attempts left
[   +1 ms] Error writing "build/flutter_assets/assets/images/receipt.svg" to DevFS: SocketException: OS Error: Connection refused, errno = 111, address = 127.0.0.1, port = 58226
[        ] trying again in a few - 1 more attempts left
[        ] Error writing "build/flutter_assets/assets/images/question-circle.svg" to DevFS: SocketException: OS Error: Connection refused, errno = 111, address = 127.0.0.1, port = 58228
[        ] trying again in a few - 1 more attempts left
[ +493 ms] Error writing "build/flutter_assets/assets/images/bolt-background.svg" to DevFS: SocketException: OS Error: Connection refused, errno = 111, address = 127.0.0.1, port = 58240
[        ] trying again in a few - 0 more attempts left
[   +3 ms] Error writing "build/flutter_assets/assets/images/bottle-logo.svg" to DevFS: SocketException: OS Error: Connection refused, errno = 111, address = 127.0.0.1, port = 58242
[        ] trying again in a few - 0 more attempts left
[        ] Error writing "build/flutter_assets/assets/images/x-icon.svg" to DevFS: SocketException: OS Error: Connection refused, errno = 111, address = 127.0.0.1, port = 58244
[        ] trying again in a few - 0 more attempts left
[   +1 ms] Error writing "build/flutter_assets/assets/images/app-icon.png" to DevFS: SocketException: OS Error: Connection refused, errno = 111, address = 127.0.0.1, port = 58246
[        ] trying again in a few - 0 more attempts left
[   +1 ms] Error writing "build/flutter_assets/assets/images/receipt.svg" to DevFS: SocketException: OS Error: Connection refused, errno = 111, address = 127.0.0.1, port = 58248
[        ] trying again in a few - 0 more attempts left
[        ] Error writing "build/flutter_assets/assets/images/question-circle.svg" to DevFS: SocketException: OS Error: Connection refused, errno = 111, address = 127.0.0.1, port = 58250
[        ] trying again in a few - 0 more attempts left
[ +492 ms] Error writing "build/flutter_assets/assets/images/bolt-background.svg" to DevFS: SocketException: OS Error: Connection refused, errno = 111, address = 127.0.0.1, port = 58260
[        ] DevFS sync failed. Lost connection to device: SocketException: OS Error: Connection refused, errno = 111, address = 127.0.0.1, port = 58260
[   +1 ms] Syncing files to device Android SDK built for x86 64... (completed in 9,286ms, longer than expected)
[   +1 ms] "flutter run" took 12,207ms.

#0      throwToolExit (package:flutter_tools/src/base/common.dart:28:3)
#1      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:509:7)
<asynchronous suspension>
#2      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:615:18)
#3      _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:73:64)
#4      _rootRunUnary (dart:async/zone.dart:1134:38)
#5      _CustomZone.runUnary (dart:async/zone.dart:1031:19)
#6      _FutureListener.handleValue (dart:async/future_impl.dart:139:18)
#7      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:680:45)
#8      Future._propagateToListeners (dart:async/future_impl.dart:709:32)
#9      Future._completeWithValue (dart:async/future_impl.dart:524:5)
#10     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:32:15)
#11     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:290:13)
#12     RunCommand.usageValues (package:flutter_tools/src/commands/run.dart)
#13     _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:73:64)
#14     _rootRunUnary (dart:async/zone.dart:1134:38)
#15     _CustomZone.runUnary (dart:async/zone.dart:1031:19)
#16     _FutureListener.handleValue (dart:async/future_impl.dart:139:18)
#17     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:680:45)
#18     Future._propagateToListeners (dart:async/future_impl.dart:709:32)
#19     Future._completeWithValue (dart:async/future_impl.dart:524:5)
#20     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:32:15)
#21     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:290:13)
#22     IosProject.isSwift (package:flutter_tools/src/project.dart)
#23     _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:73:64)
#24     _rootRunUnary (dart:async/zone.dart:1134:38)
#25     _CustomZone.runUnary (dart:async/zone.dart:1031:19)
#26     _FutureListener.handleValue (dart:async/future_impl.dart:139:18)
#27     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:680:45)
#28     Future._propagateToListeners (dart:async/future_impl.dart:709:32)
#29     Future._completeWithValue (dart:async/future_impl.dart:524:5)
#30     Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:554:7)
#31     _rootRun (dart:async/zone.dart:1126:13)
#32     _CustomZone.run (dart:async/zone.dart:1023:19)
#33     _CustomZone.runGuarded (dart:async/zone.dart:925:7)
#34     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:965:23)
#35     _microtaskLoop (dart:async/schedule_microtask.dart:43:21)
#36     _startMicrotaskLoop (dart:async/schedule_microtask.dart:52:5)
#37     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
#38     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:175:5)



```

```
No analyze errors
```

```
[✓] Flutter (Channel stable, v1.12.13+hotfix.7, on Linux, locale en_US.UTF-8)
    • Flutter version 1.12.13+hotfix.7 at /home/xff0c/Projects/flutter
    • Framework revision 9f5ff2306b (2 days ago), 2020-01-26 22:38:26 -0800
    • Engine revision a67792536c
    • Dart version 2.7.0

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /home/xff0c/Android/Sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • ANDROID_HOME = /home/xff0c/Android/Sdk
    • Java binary at: /home/xff0c/Applications/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Android Studio (version 3.5)
    • Android Studio at /home/xff0c/Applications/android-studio
    • Flutter plugin version 42.1.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] Connected device (1 available)
    • Android SDK built for x86 64 • emulator-5556 • android-x64 • Android 10 (API 29) (emulator)

• No issues found!
```

</details>

**Comment by VladyslavBondarenko** [comment]
Hi @acoutts 
Go through [this article](https://jigneshdarji.com/solved-adb-server-version-doesnt-match-this-client-in-android/), cause and solution of the error `adb server version doesn’t match this client` is described there in details
Closing, as this isn't an issue with Flutter itself,
if you disagree or if the error is still persists please write in the comments and I will reopen it.
Thank you

**Comment by acoutts** [comment]
Aha that did it! Environmental issue- I had ran `apt install adb` in the past so my path was picking up that adb instead of the one in my android SDK used by Flutter. All good now.
