### ISSUE TITLE
local_auth ^0.6.1 failed to provide registered FaceID/Touch ID

### ISSUE THREAD

**Issue by sachindeorah** [flutter/flutter#49697]
My Flutter app was working fine with local_auth ^0.5.2+4. But Recently when we upgraded it to the latest version ^0.6.1 we are getting issues. Even the sample app with the library is also not working on the Samsung Note 9 API version 26. 

Error log:
```
E/MethodChannel#plugins.flutter.io/local_auth(22325): Failed to handle method call
E/MethodChannel#plugins.flutter.io/local_auth(22325): java.lang.IllegalStateException: You need to use a Theme.AppCompat theme (or descendant) with this activity.
E/MethodChannel#plugins.flutter.io/local_auth(22325):     at androidx.appcompat.app.AppCompatDelegateImpl.createSubDecor(AppCompatDelegateImpl.java:696)
E/MethodChannel#plugins.flutter.io/local_auth(22325):     at androidx.appcompat.app.AppCompatDelegateImpl.ensureSubDecor(AppCompatDelegateImpl.java:659)
E/MethodChannel#plugins.flutter.io/local_auth(22325):     at androidx.appcompat.app.AppCompatDelegateImpl.setContentView(AppCompatDelegateImpl.java:552)
E/MethodChannel#plugins.flutter.io/local_auth(22325):     at androidx.appcompat.app.AppCompatDialog.setContentView(AppCompatDialog.java:95)
E/MethodChannel#plugins.flutter.io/local_auth(22325):     at androidx.appcompat.app.AlertController.installContent(AlertController.java:232)
E/MethodChannel#plugins.flutter.io/local_auth(22325):     at androidx.appcompat.app.AlertDialog.onCreate(AlertDialog.java:279)
E/MethodChannel#plugins.flutter.io/local_auth(22325):     at android.app.Dialog.dispatchOnCreate(Dialog.java:494)
E/MethodChannel#plugins.flutter.io/local_auth(22325):     at android.app.Dialog.show(Dialog.java:342)
E/MethodChannel#plugins.flutter.io/local_auth(22325):     at androidx.fragment.app.DialogFragment.onStart(DialogFragment.java:486)
E/MethodChannel#plugins.flutter.io/local_auth(22325):     at androidx.fragment.app.Fragment.performStart(Fragment.java:2632)
E/MethodChannel#plugins.flutter.io/local_auth(22325):     at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:915)
E/MethodChannel#plugins.flutter.io/local_auth(22325):     at androidx.fragment.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManagerImpl.java:1238)
E/MethodChannel#plugins.flutter.io/local_auth(22325):     at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:1303)
E/MethodChannel#plugins.flutter.io/local_auth(22325):     at androidx.fragment.app.BackStackRecord.executeOps(BackStackRecord.java:439)
E/MethodChannel#plugins.flutter.io/local_auth(22325):     at androidx.fragment.app.FragmentManagerImpl.executeOps(FragmentManagerImpl.java:2079)
E/MethodChannel#plugins.flutter.io/local_auth(22325):     at androidx.fragment.app.FragmentManagerImpl.executeOpsTogether(FragmentManagerImpl.java:1869)
E/MethodChannel#plugins.flutter.io/local_auth(22325):     at androidx.fragment.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManagerImpl.java:1824)
E/MethodChannel#plugins.flutter.io/local_auth(22325):     at androidx.fragment.app.FragmentManagerImpl.execPendingActions(FragmentManagerImpl.java:1727)
E/MethodChannel#plugins.flutter.io/local_auth(22325):     at androidx.fragment.app.FragmentManagerImpl.executePendingTransactions(FragmentManagerImpl.java:183)
E/MethodChannel#plugins.flutter.io/local_auth(22325):     at androidx.biometric.BiometricPrompt.authenticateInternal(BiometricPrompt.java:797)
E/MethodChannel#plugins.flutter.io/local_auth(22325):     at androidx.biometric.BiometricPrompt.authenticate(BiometricPrompt.java:663)
E/MethodChannel#plugins.flutter.io/local_auth(22325):     at io.flutter.plugins.localauth.AuthenticationHelper.authenticate(AuthenticationHelper.java:104)
E/MethodChannel#plugins.flutter.io/local_auth(22325):     at io.flutter.plugins.localauth.LocalAuthPlugin.onMethodCall(LocalAuthPlugin.java:92)
E/MethodChannel#plugins.flutter.io/local_auth(22325):     at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:222)
E/MethodChannel#plugins.flutter.io/local_auth(22325):     at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:96)
E/MethodChannel#plugins.flutter.io/local_auth(22325):     at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:656)
E/MethodChannel#plugins.flutter.io/local_auth(22325):     at android.os.MessageQueue.nativePollOnce(Native Method)
E/MethodChannel#plugins.flutter.io/local_auth(22325):     at android.os.MessageQueue.next(MessageQueue.java:325)
E/MethodChannel#plugins.flutter.io/local_auth(22325):     at android.os.Looper.loop(Looper.java:142)
E/MethodChannel#plugins.flutter.io/local_auth(22325):     at android.app.ActivityThread.main(ActivityThread.java:6938)
E/MethodChannel#plugins.flutter.io/local_auth(22325):     at java.lang.reflect.Method.invoke(Native Method)
E/MethodChannel#plugins.flutter.io/local_auth(22325):     at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
E/MethodChannel#plugins.flutter.io/local_auth(22325):     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)
I/flutter (22325): PlatformException(error, You need to use a Theme.AppCompat theme (or descendant) with this activity., null)
```

**Comment by sachindeorah** [comment]
flutter doctor -v

Response:
[✓] Flutter (Channel unknown, v1.9.1+hotfix.6, on Mac OS X 10.14.6 18G1012, locale en-GB)
    • Flutter version 1.9.1+hotfix.6 at /HNB_Project/flutter_sdk/flutter
    • Framework revision 68587a0916 (5 months ago), 2019-09-13 19:46:58 -0700
    • Engine revision b863200c37
    • Dart version 2.5.0

 

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/hemakm/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

 

[✓] Xcode - develop for iOS and macOS (Xcode 10.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.3, Build version 10G8
    • CocoaPods version 1.8.4

 

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 38.2.3
    • Dart plugin version 191.8423
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

 

[✓] Connected device (1 available)
    • SM G960F • 2bd911ecc21c7ece • android-arm64 • Android 8.0.0 (API 26)

 

• No issues found!

**Comment by VladyslavBondarenko** [comment]
Hi @sachindeorah 
Does solution from https://github.com/flutter/flutter/issues/47602 solve your problem?

**Comment by sachindeorah** [comment]
> Hi @sachindeorah
> Does solution from #47602 solve your problem?

@VladyslavBondarenko :No. This plugin won't have any activities. I tried to change
in styles 
<style name="AlertDialogCustom" parent="@style/Theme.AppCompat.Light.Dialog.Alert">
and in build.gradle
 add implementation 'androidx.appcompat:appcompat:1.0.2'

But still getting the same response

**Comment by VladyslavBondarenko** [comment]
Hi @sachindeorah 
You can run
`flutter channel stable`
`flutter upgrade --force`
`flutter pub cache repair`
`cd <YOUR APP FOLDER>`
`flutter clean`
Does the issue persist with using latest flutter version?

**Comment by sachindeorah** [comment]
@VladyslavBondarenko  : 
Ok. In AuthenticationHelper.java file replced
 import android.app.AlertDialog;  
to
import androidx.appcompat.app.AlertDialog;

Now Sample app starts work.
