### ISSUE TITLE
[tool_crash] NoSuchMethodError: The setter 'readEventsEnabled=' was called on null.Receiver: nullTried calling: readEventsEnabled=false

### ISSUE THREAD

**Issue by violectyc** [flutter/flutter#49690]
## Logs
NoSuchMethodError: NoSuchMethodError: The setter 'readEventsEnabled=' was called on null.
Receiver: null
Tried calling: readEventsEnabled=false
```bash
#0      Net._attempt (package:flutter_tools/src/base/net.dart:108:19)
<asynchronous suspension>
#1      Net.fetchUrl (package:flutter_tools/src/base/net.dart:63:33)
#2      Cache.downloadFile (package:flutter_tools/src/cache.dart:451:16)
#3      CachedArtifact._downloadArchive.<anonymous closure> (package:flutter_tools/src/cache.dart:587:23)
#4      CachedArtifact._withDownloadFile (package:flutter_tools/src/cache.dart:616:26)
#5      CachedArtifact._downloadArchive (package:flutter_tools/src/cache.dart:583:12)
#6      CachedArtifact._downloadZipArchive (package:flutter_tools/src/cache.dart:603:12)
#7      EngineCachedArtifact.updateInner (package:flutter_tools/src/cache.dart:731:13)
#8      CachedArtifact.update (package:flutter_tools/src/cache.dart:539:11)
#9      Cache.updateAll (package:flutter_tools/src/cache.dart:417:24)
#10     FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:614:27)
#11     FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:537:33)
<asynchronous suspension>
#12     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:29)
#13     _rootRun (dart:async/zone.dart:1126:13)
#14     _CustomZone.run (dart:async/zone.dart:1023:19)
#15     _runZoned (dart:async/zone.dart:1518:10)
#16     runZoned (dart:async/zone.dart:1465:12)
#17     AppContext.run (package:flutter_tools/src/base/context.dart:149:18)
```

```
[✓] Flutter (Channel master, v1.10.13-pre.10, on Linux, locale zh_CN.UTF-8)
    • Flutter version 1.10.13-pre.10 at /home/yc/flutter
    • Framework revision f4b4616f87 (4 个月前), 2019-10-04 20:01:04 -0700
    • Engine revision c4229bfbba
    • Dart version 2.8.0 (build 2.8.0-dev.5.0 fc3af737c7)

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /home/yc/Android/Sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • ANDROID_HOME = /home/yc/Android/Sdk
    • Java binary at: /snap/android-studio/81/android-studio/jre/bin/java
    • Java version openjdk version "1.8.0_202-release"
    • All Android licenses accepted.

[✓] Android Studio (version 3.5)
    • Android Studio at /snap/android-studio/81/android-studio
    • Flutter plugin version 42.1.1
    • Dart plugin version 191.8593
    • Java version openjdk version "1.8.0_202-release"

[✓] IntelliJ IDEA Ultimate Edition (version 2019.3)
    • IntelliJ at /snap/intellij-idea-ultimate/198
    • Flutter plugin version 42.1.4
    • Dart plugin version 193.6015.9

[!] VS Code (version 1.41.1)
    • VS Code at /usr/share/code
    ✗ Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[!] Proxy Configuration
    • HTTP_PROXY is set
    • NO_PROXY is localhost,127.0.0.0/8,::1
    ! NO_PROXY does not contain 127.0.0.1
    • NO_PROXY contains localhost

[!] Connected device
    ! No devices available

! Doctor found issues in 3 categories.

```

## Flutter Application Metadata
No pubspec in working directory.

**Comment by iapicca** [comment]
Hi @violectyc 
could you please run 
`flutter channel stable`
`flutter upgrade --force`
`flutter pub cache repair`
`cd <YOUR APP FOLDER>`
`flutter clean`
If the issue persist please provide your updated 
`flutter doctor -v` and logs
thank you

**Comment by jonahwilliams** [comment]
@iapicca this is not appropriate advice for a flutter tool crash

**Comment by jonahwilliams** [comment]
@ZichangG this looks like Socket was null somewhere in the HTTP client

**Comment by christopherfujino** [comment]
@violectyc did you manually set a different engine version? The framework & engine version I see in your flutter doctor don't match what's checked in to the tool.

**Comment by wangbo4020** [comment]
Flutter crash report; please file at https://github.com/flutter/flutter/issues.

## command

flutter doctor

## exception

NoSuchMethodError: NoSuchMethodError: The setter 'readEventsEnabled=' was called on null.
Receiver: null
Tried calling: readEventsEnabled=false

```
#0      _attempt (package:flutter_tools/src/base/net.dart:87:17)
<asynchronous suspension>
#1      fetchUrl (package:flutter_tools/src/base/net.dart:44:31)
#2      _downloadFile (package:flutter_tools/src/cache.dart:1251:9)
#3      CachedArtifact._downloadArchive.<anonymous closure> (package:flutter_tools/src/cache.dart:516:17)
#4      CachedArtifact._withDownloadFile (package:flutter_tools/src/cache.dart:545:26)
#5      CachedArtifact._downloadArchive (package:flutter_tools/src/cache.dart:512:12)
#6      CachedArtifact._downloadZipArchive (package:flutter_tools/src/cache.dart:532:12)
#7      EngineCachedArtifact.updateInner (package:flutter_tools/src/cache.dart:680:13)
#8      CachedArtifact.update (package:flutter_tools/src/cache.dart:462:11)
#9      Cache.updateAll (package:flutter_tools/src/cache.dart:360:24)
#10     FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:595:19)
<asynchronous suspension>
#11     FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:515:33)
<asynchronous suspension>
#12     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:146:29)
#13     _rootRun (dart:async/zone.dart:1126:13)
#14     _CustomZone.run (dart:async/zone.dart:1023:19)
#15     _runZoned (dart:async/zone.dart:1518:10)
#16     runZoned (dart:async/zone.dart:1465:12)
#17     AppContext.run (package:flutter_tools/src/base/context.dart:145:18)
#18     FlutterCommand.run (package:flutter_tools/src/runner/flutter_command.dart:505:20)
#19     CommandRunner.runCommand (package:args/command_runner.dart:197:27)
#20     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:413:21)
<asynchronous suspension>
#21     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:146:29)
#22     _rootRun (dart:async/zone.dart:1126:13)
#23     _CustomZone.run (dart:async/zone.dart:1023:19)
#24     _runZoned (dart:async/zone.dart:1518:10)
#25     runZoned (dart:async/zone.dart:1465:12)
#26     AppContext.run (package:flutter_tools/src/base/context.dart:145:18)
#27     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:364:19)
#28     CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:112:25)
#29     new Future.sync (dart:async/future.dart:224:31)
#30     CommandRunner.run (package:args/command_runner.dart:112:14)
#31     FlutterCommandRunner.run (package:flutter_tools/src/runner/flutter_command_runner.dart:250:18)
#32     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:63:22)
#33     _rootRun (dart:async/zone.dart:1126:13)
#34     _CustomZone.run (dart:async/zone.dart:1023:19)
#35     _runZoned (dart:async/zone.dart:1518:10)
#36     runZoned (dart:async/zone.dart:1502:12)
#37     run.<anonymous closure> (package:flutter_tools/runner.dart:61:18)
<asynchronous suspension>
#38     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:146:29)
#39     _rootRun (dart:async/zone.dart:1126:13)
#40     _CustomZone.run (dart:async/zone.dart:1023:19)
#41     _runZoned (dart:async/zone.dart:1518:10)
#42     runZoned (dart:async/zone.dart:1465:12)
#43     AppContext.run (package:flutter_tools/src/base/context.dart:145:18)
#44     runInContext (package:flutter_tools/src/context_runner.dart:64:24)
#45     run (package:flutter_tools/runner.dart:50:10)
#46     main (package:flutter_tools/executable.dart:65:9)
#47     main (file:///Users/dylan/Library/Flutter/flutter/packages/flutter_tools/bin/flutter_tools.dart:8:3)
#48     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:305:32)
#49     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:174:12)
```

## flutter doctor

```
[!] Flutter (Channel stable, v1.12.13+hotfix.8, on Mac OS X 10.15.4 19E266, locale zh-Hans-CN)
    • Flutter version 1.12.13+hotfix.8 at /Users/dylan/Library/Flutter/flutter
    • Framework revision 0b8abb4724 (7 weeks ago), 2020-02-11 11:44:36 -0800
    • Engine revision e1e6ced81d
    • Dart version 2.7.0
    ✗ Downloaded executables cannot execute on host.
      See https://github.com/flutter/flutter/issues/6207 for more information


[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/dylan/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.4)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.4, Build version 11E146
    • CocoaPods version 1.8.4

[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 44.0.2
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)

[!] Proxy Configuration
    • HTTP_PROXY is set
    ! NO_PROXY is not set

[!] Connected device
    ! No devices available

! Doctor found issues in 3 categories.
```

**Comment by ZichangG** [comment]
Looks like a similar issue with https://github.com/dart-lang/sdk/issues/37808.
The fix for that was landed last week.

**Comment by markusaksli-nc** [comment]
Closing since this was [fixed](https://github.com/dart-lang/sdk/issues/37808#issuecomment-651240242) in dart `2.9.0-19.0.dev`. All of the latest flutter channels except stable use `2.9.0-21.0.dev` or newer.
