### ISSUE TITLE
Copy / Paste not working on Flutter Desktop

### ISSUE THREAD

**Issue by kenzieschmoll** [flutter/flutter#49734]
Attempting to paste text into a `TextField` widget on MacOs.

Content of my clipboard:
"http://127.0.0.1:65249/lQCwFlrKqKo=/"

Error:
```
[ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: RangeError: Value not in range: -1
#0      _StringBase.substring (dart:core-patch/string_patch.dart:388:7)
#1      TextRange.textBefore (dart:ui/text.dart:1436:17)
#2      RenderEditable._handleShortcuts (package:flutter/src/rendering/editable.dart:678:33)
<asynchronous suspension>
#3      RenderEditable._handleKeyEvent (package:flutter/src/rendering/editable.dart:493:7)
#4      RawKeyboard._handleKeyEvent (package:flutter/src/services/raw_keyboard.dart:528:17)
#5      BasicMessageChannel.setMessageHandler.<anonymous closure> (package:flutter/src/services/platform_channel.dart:74:49)
#6      _DefaultBinaryMessenger.handlePlatformMessage (package:flutter/src/services/binding.dart:200:33)
#7      _invoke3.<anonymous closure> (dart:ui/hooks.dart:304:15)
#8      _rootRun (dart:async/zone.dart:1126:13)
#9      _CustomZone.run (dart:async/zone.dart:1023:19)
#10     _CustomZone.runGuarded (dart:async/zone.dart:925:7)
#11     _invoke3 (dart:ui/hooks.dart:303:10)
#12     _dispatchPlatformMessage (dart:ui/hooks.dart:163:5)
```

flutter --version
```
Flutter 1.14.6-pre.55 • channel master • git@github.com:flutter/flutter.git
Framework • revision 3bd4c69fd8 (27 hours ago) • 2020-01-28 10:14:08 -0800
Engine • revision c4229bfbba
Tools • Dart 2.8.0 (build 2.8.0-dev.5.0 fc3af737c7)
```

**Comment by kenzieschmoll** [comment]
Upgraded to latest flutter and no longer seeing the issue. Will re-open if I see this again.
