### ISSUE TITLE
Web: Uncaught Error: Exception: webOnlyScheduleFrameCallback must be initialized first.

### ISSUE THREAD

**Issue by ansarizafar** [flutter/flutter#49765]
After upgrading flutter to latest master channel I am getting following error. Sometime I also get error 404 for not finding manifest.json and icon file.

![image](https://user-images.githubusercontent.com/5788284/73424752-8f12b000-4351-11ea-84a0-86f1ee062843.png)

Here is the output of flutter doctor -v

![image](https://user-images.githubusercontent.com/5788284/73424935-fe889f80-4351-11ea-9f07-9fca3734cc52.png)

**Comment by iapicca** [comment]
Hi @ansarizafar 
thanks for your `flutter doctor -v` ,
can you please provide also your `flutter run --verbose` 
and if possible a reproducible minimal code sample.

Please refrain from posting pictures if not necessary.
Thank you

**Comment by ansarizafar** [comment]
@iapicca  I have used flutter create command and not made any change in the code. Here is the output of flutter run --verbose command
````
zafar@home:~/projects/dart/myapp$ flutter run --verbose
[  +42 ms] executing: [/home/zafar/flutter/] git -c log.showSignature=false log
-n 1 --pretty=format:%H
[ +188 ms] Exit code 0 from: git -c log.showSignature=false log -n 1
--pretty=format:%H
[   +2 ms] 92f7e16312d9c7c396c0100dcb699458c3f10172
[        ] executing: [/home/zafar/flutter/] git describe --match v*.*.*
--first-parent --long --tags
[+1141 ms] Exit code 0 from: git describe --match v*.*.* --first-parent --long --tags
[        ] v1.14.6-38-g92f7e16
[  +10 ms] executing: [/home/zafar/flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[   +7 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/master
[        ] executing: [/home/zafar/flutter/] git ls-remote --get-url origin
[   +7 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[  +96 ms] executing: [/home/zafar/flutter/] git rev-parse --abbrev-ref HEAD
[   +8 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] master
[ +118 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[  +54 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[  +11 ms] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[ +211 ms] executing: /usr/local/opt/android-sdk-linux/platform-tools/adb devices -l
[+3133 ms] Exit code 0 from: /usr/local/opt/android-sdk-linux/platform-tools/adb devices -l
[        ] List of devices attached
           * daemon not running. starting it now at tcp:5037 *
           * daemon started successfully *
[  +26 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[  +35 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[ +137 ms] More than one device connected; please specify a device with the '-d <deviceId>' flag,
or use '-d
                    all' to act on all devices.
[ +831 ms] Chrome     • chrome     • web-javascript • Google Chrome 76.0.3809.100
[   +2 ms] Web Server • web-server • web-javascript • Flutter Tools
[  +18 ms] "flutter run" took 4,600ms.

#0      throwToolExit (package:flutter_tools/src/base/common.dart:27:3)
#1      RunCommand.validateCommand (package:flutter_tools/src/commands/run.dart:325:7)
<asynchronous suspension>
#2      FlutterCommand.verifyThenRunCommand
(package:flutter_tools/src/runner/flutter_command.dart:619:11)
<asynchronous suspension>
#3      FlutterCommand.run.<anonymous closure>
(package:flutter_tools/src/runner/flutter_command.dart:537:33)
<asynchronous suspension>
#4      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:29)
#5      _rootRun (dart:async/zone.dart:1126:13)
#6      _CustomZone.run (dart:async/zone.dart:1023:19)
#7      _runZoned (dart:async/zone.dart:1518:10)
#8      runZoned (dart:async/zone.dart:1465:12)
#9      AppContext.run (package:flutter_tools/src/base/context.dart:149:18)
#10     FlutterCommand.run (package:flutter_tools/src/runner/flutter_command.dart:527:20)
#11     CommandRunner.runCommand (package:args/command_runner.dart:197:27)
#12     FlutterCommandRunner.runCommand.<anonymous closure>
(package:flutter_tools/src/runner/flutter_command_runner.dart:338:21)
<asynchronous suspension>
#13     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:29)
#14     _rootRun (dart:async/zone.dart:1126:13)
#15     _CustomZone.run (dart:async/zone.dart:1023:19)
#16     _runZoned (dart:async/zone.dart:1518:10)
#17     runZoned (dart:async/zone.dart:1465:12)
#18     AppContext.run (package:flutter_tools/src/base/context.dart:149:18)
#19     FlutterCommandRunner.runCommand
(package:flutter_tools/src/runner/flutter_command_runner.dart:288:19)
#20     CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:112:25)
#21     new Future.sync (dart:async/future.dart:224:31)
#22     CommandRunner.run (package:args/command_runner.dart:112:14)
#23     FlutterCommandRunner.run
(package:flutter_tools/src/runner/flutter_command_runner.dart:231:18)
#24     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:64:22)
#25     _rootRun (dart:async/zone.dart:1126:13)
#26     _CustomZone.run (dart:async/zone.dart:1023:19)
#27     _runZoned (dart:async/zone.dart:1518:10)
#28     runZoned (dart:async/zone.dart:1502:12)
#29     run.<anonymous closure> (package:flutter_tools/runner.dart:62:18)
<asynchronous suspension>
#30     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:29)
#31     _rootRun (dart:async/zone.dart:1126:13)
#32     _CustomZone.run (dart:async/zone.dart:1023:19)
#33     _runZoned (dart:async/zone.dart:1518:10)
#34     runZoned (dart:async/zone.dart:1465:12)
#35     AppContext.run (package:flutter_tools/src/base/context.dart:149:18)
#36     runInContext (package:flutter_tools/src/context_runner.dart:64:24)
#37     run (package:flutter_tools/runner.dart:51:10)
#38     main (package:flutter_tools/executable.dart:65:9)
#39     main (file:///home/zafar/flutter/packages/flutter_tools/bin/flutter_tools.dart:8:3)
#40     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:299:32)
#41     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:168:12)
````

**Comment by iapicca** [comment]
Hi @ansarizafar 
could you please select a device 
in your case `flutter run -d chrome --verbose`
thank you

**Comment by ansarizafar** [comment]
@iapicca Here is the terminal and chrome browser output of flutter run -d chrome --verbose command
```
zafar@home:~/projects/dart/myapp$ flutter run -d chrome --verbose
[  +42 ms] executing: [/home/zafar/flutter/] git -c log.showSignature=false log -n 1
--pretty=format:%H
[  +62 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[        ] 92f7e16312d9c7c396c0100dcb699458c3f10172
[        ] executing: [/home/zafar/flutter/] git describe --match v*.*.* --first-parent --long
--tags
[  +28 ms] Exit code 0 from: git describe --match v*.*.* --first-parent --long --tags
[        ] v1.14.6-38-g92f7e16
[  +13 ms] executing: [/home/zafar/flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[  +10 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/master
[        ] executing: [/home/zafar/flutter/] git ls-remote --get-url origin
[  +10 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[  +96 ms] executing: [/home/zafar/flutter/] git rev-parse --abbrev-ref HEAD
[  +22 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] master
[  +80 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[  +10 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +72 ms] executing: /usr/local/opt/android-sdk-linux/platform-tools/adb devices -l
[  +23 ms] Exit code 0 from: /usr/local/opt/android-sdk-linux/platform-tools/adb devices -l
[        ] List of devices attached
[  +48 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[   +5 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[+1186 ms] Generating
/home/zafar/projects/dart/myapp/android/app/src/main/java/io/flutter/plugins/GeneratedPluginRegis
trant.java
[ +232 ms] Launching lib/main.dart on Chrome in debug mode...
[  +60 ms] Updating assets
[ +451 ms] Syncing files to device Chrome...
[ +104 ms] Generating
/home/zafar/projects/dart/myapp/android/app/src/main/java/io/flutter/plugins/GeneratedPluginRegis
trant.java
[ +508 ms] <- reset
[  +11 ms] /home/zafar/flutter/bin/cache/dart-sdk/bin/dart
/home/zafar/flutter/bin/cache/artifacts/engine/linux-x64/frontend_server.dart.snapshot --sdk-root
/home/zafar/flutter/bin/cache/flutter_web_sdk/ --incremental --target=dartdevc
-Ddart.developer.causal_async_stacks=true --output-dill /tmp/flutter_tool.LEOXLI/app.dill
--packages /home/zafar/projects/dart/myapp/.packages -Ddart.vm.profile=false
-Ddart.vm.product=false
--bytecode-options=source-positions,local-var-info,debugger-stops,instance-field-initializers,kee
p-unreachable-code,avoid-closure-call-instructions --enable-asserts --track-widget-creation
--filesystem-scheme org-dartlang-root --platform
file:///home/zafar/flutter/bin/cache/flutter_web_sdk/kernel/flutter_ddc_sdk.dill
[  +22 ms] <- compile /tmp/flutter_tools.QATYAB/web_entrypoint.dart
```
Browser Console output
````
Failed to load resource: the server responded with a status of 404 (Not Found)
:45683/manifest.json:1 Manifest: Line: 1, column: 1, Syntax error.
:45683/favicon.png:1 Failed to load resource: the server responded with a status of 404 (Not Found)
(index):1 Uncaught (in promise) TypeError: Failed to register a ServiceWorker: A bad HTTP response code (404) was received when fetching the script.
errors.dart:196 Uncaught (in promise) Error: Exception: webOnlyScheduleFrameCallback must be initialized first.
    at Object.throw_ [as throw] (errors.dart:196)
    at _engine.EngineWindow.new.scheduleFrame (window.dart:732)
    at binding$5.WidgetsFlutterBinding.new.scheduleFrame (binding.dart:786)
    at binding$5.WidgetsFlutterBinding.new.get endOfFrame [as endOfFrame] (binding.dart:686)
    at binding$5.WidgetsFlutterBinding.new.<anonymous> (binding.dart:875)
    at Generator.next (<anonymous>)
    at runBody (async_patch.dart:86)
    at Object._async [as async] (async_patch.dart:125)
    at binding.dart:874
    at binding$5.WidgetsFlutterBinding.new.lockEvents (binding.dart:223)
    at binding$5.WidgetsFlutterBinding.new.scheduleWarmUpFrame (binding.dart:874)
    at Object.runApp (binding.dart:896)
    at Object.main$ [as main] (main.dart:3)
    at main$ (web_entrypoint.dart:4)
    at main$.next (<anonymous>)
    at runBody (async_patch.dart:86)
    at Object._async [as async] (async_patch.dart:125)
    at main$ (web_entrypoint.dart:3)
    at main_module.js:25
    at Object.execCb (require.js:1696)
    at Module.check (require.js:883)
    at Module.<anonymous> (require.js:1139)
    at require.js:134
    at require.js:1189
    at each (require.js:59)
    at Module.emit (require.js:1188)
    at Module.check (require.js:938)
    at Module.<anonymous> (require.js:1139)
    at require.js:134
    at require.js:1189
    at each (require.js:59)
    at Module.emit (require.js:1188)
    at Module.check (require.js:938)
    at Module.<anonymous> (require.js:1139)
    at require.js:134
    at require.js:1189
    at each (require.js:59)
    at Module.emit (require.js:1188)
    at Module.check (require.js:938)
    at Module.<anonymous> (require.js:1139)
    at require.js:134
    at require.js:1189
    at each (require.js:59)
    at Module.emit (require.js:1188)
    at Module.check (require.js:938)
    at Module.<anonymous> (require.js:1139)
    at require.js:134
    at require.js:1189
    at each (require.js:59)
    at Module.emit (require.js:1188)
    at Module.check (require.js:938)
    at Module.<anonymous> (require.js:1139)
    at require.js:134
    at require.js:1189
    at each (require.js:59)
    at Module.emit (require.js:1188)
    at Module.check (require.js:938)
    at Module.<anonymous> (require.js:1139)
    at require.js:134
    at require.js:1189
    at each (require.js:59)
    at Module.emit (require.js:1188)
    at Module.check (require.js:938)
    at Module.<anonymous> (require.js:1139)
    at require.js:134
    at require.js:1189
    at each (require.js:59)
    at Module.emit (require.js:1188)
    at Module.check (require.js:938)
    at Module.<anonymous> (require.js:1139)
    at require.js:134
    at require.js:1189
    at each (require.js:59)
    at Module.emit (require.js:1188)
    at Module.check (require.js:938)
    at Module.<anonymous> (require.js:1139)
    at require.js:134
    at require.js:1189
    at each (require.js:59)
    at Module.emit (require.js:1188)
    at Module.check (require.js:938)
    at Module.<anonymous> (require.js:1139)
    at require.js:134
    at require.js:1189
    at each (require.js:59)
    at Module.emit (require.js:1188)
    at Module.check (require.js:938)
    at Module.<anonymous> (require.js:1139)
    at require.js:134
    at require.js:1189
    at each (require.js:59)
    at Module.emit (require.js:1188)
    at Module.check (require.js:938)
    at Module.enable (require.js:1176)
    at Module.init (require.js:788)
    at callGetModule (require.js:1203)
    at Object.completeLoad (require.js:1590)
    at HTMLScriptElement.onScriptLoad (require.js:1717)
errors.dart:196 Uncaught Error: Exception: webOnlyScheduleFrameCallback must be initialized first.
    at Object.throw_ [as throw] (errors.dart:196)
    at _engine.EngineWindow.new.scheduleFrame (window.dart:732)
    at binding$5.WidgetsFlutterBinding.new.scheduleFrame (binding.dart:786)
    at binding$5.WidgetsFlutterBinding.new.ensureVisualUpdate (binding.dart:741)
    at RenderObjectToWidgetAdapter.new.attachToRenderTree (binding.dart:972)
    at binding$5.WidgetsFlutterBinding.new.attachRootWidget (binding.dart:847)
    at binding.dart:830
    at internalCallback (isolate_helper.dart:50)
dart_stack_trace_mapper.js:261 Uncaught (in promise) Bad state: Source maps are not done loading.
    at Object.a (http://localhost:45683/home/zafar/flutter/bin/cache/dart-sdk/lib/dev_compiler/web/dart_stack_trace_mapper.js:261:3)
    at cv.k0 (http://localhost:45683/home/zafar/flutter/bin/cache/dart-sdk/lib/dev_compiler/web/dart_stack_trace_mapper.js:2620:23)
    at Object.iG (http://localhost:45683/home/zafar/flutter/bin/cache/dart-sdk/lib/dev_compiler/web/dart_stack_trace_mapper.js:218:69)
    at js (http://localhost:45683/home/zafar/flutter/bin/cache/dart-sdk/lib/dev_compiler/web/dart_stack_trace_mapper.js:2336:10)
    at Object.<anonymous> (http://localhost:45683/home/zafar/flutter/bin/cache/dart-sdk/lib/dev_compiler/web/dart_stack_trace_mapper.js:2330:42)
    at dart._StackTrace.new.toString (http://localhost:45683/dart_sdk.js:6107:29)
    at Object._toString [as toString] (http://localhost:45683/dart_sdk.js:4422:26)
    at new assertions.DiagnosticsStackTrace.new (http://localhost:45683/packages/flutter/src/foundation/debug.dart.lib.js:3163:211)
    at assertions.FlutterErrorDetails.new.debugFillProperties (http://localhost:45683/packages/flutter/src/foundation/debug.dart.lib.js:2945:24)
    at assertions._FlutterErrorDetailsNode.new.get builder (http://localhost:45683/packages/flutter/src/foundation/debug.dart.lib.js:2257:34)
    at assertions._FlutterErrorDetailsNode.new.get builder [as builder] (http://localhost:45683/packages/flutter/src/foundation/debug.dart.lib.js:3176:27)
    at assertions._FlutterErrorDetailsNode.new.getProperties (http://localhost:45683/packages/flutter/src/foundation/debug.dart.lib.js:2269:45)
    at diagnostics$.TextTreeRenderer.new.render (http://localhost:45683/packages/flutter/src/foundation/debug.dart.lib.js:1111:37)
    at Function.dumpErrorToConsole (http://localhost:45683/packages/flutter/src/foundation/debug.dart.lib.js:3053:142)
    at Function.reportError (http://localhost:45683/packages/flutter/src/foundation/debug.dart.lib.js:3104:76)
    at focus_manager.FocusScopeNode.new.notifyListeners (http://localhost:45683/packages/flutter/src/foundation/change_notifier.dart.lib.js:82:37)
    at focus_manager.FocusScopeNode.new.[_notify] (http://localhost:45683/packages/flutter/src/widgets/widget_span.dart.lib.js:29868:12)
    at focus_manager.FocusManager.new.[_applyFocusChange] (http://localhost:45683/packages/flutter/src/widgets/widget_span.dart.lib.js:36613:22)
    at Object._microtaskLoop (http://localhost:45683/dart_sdk.js:42452:13)
    at _startMicrotaskLoop (http://localhost:45683/dart_sdk.js:42458:13)
    at http://localhost:45683/dart_sdk.js:38738:9
errors.dart:196 Uncaught Error: Exception: webOnlyScheduleFrameCallback must be initialized first.
    at Object.throw_ [as throw] (errors.dart:196)
    at _engine.EngineWindow.new.scheduleFrame (window.dart:732)
    at binding$5.WidgetsFlutterBinding.new.scheduleFrame (binding.dart:786)
    at binding$5.WidgetsFlutterBinding.new.ensureVisualUpdate (binding.dart:741)
    at object$.PipelineOwner.new.requestVisualUpdate (object.dart:840)
    at view.RenderView.new.markNeedsPaint (object.dart:2122)
    at view.RenderView.new.replaceRootLayer (object.dart:2200)
    at view.RenderView.new.set configuration [as configuration] (view.dart:83)
    at binding$5.WidgetsFlutterBinding.new.handleMetricsChanged (binding.dart:175)
    at binding$5.WidgetsFlutterBinding.new.handleMetricsChanged (binding.dart:449)
    at _engine.DomRenderer.new.[_metricsDidChange] (dom_renderer.dart:475)
    at Object._checkAndCall (operations.dart:326)
    at Object.dcall (operations.dart:331)
    at VisualViewport.<anonymous> (html_dart2js.dart:35657)
````

**Comment by ansarizafar** [comment]
@iapicca Is there any solution? I am unable to use flutter because of this issue.

**Comment by ansarizafar** [comment]
I have downloaded the stable version again then changed the channel to master. After upgrading flutter I have created a new app. The app is working again but I am still getting these errors in console.

```
A bad HTTP response code (404) was received when fetching the script.
manifest.json:1 GET http://localhost:42317/manifest.json 404 (Not Found)
manifest.json:1 Manifest: Line: 1, column: 1, Syntax error.
:42317/#/:1 Uncaught (in promise) TypeError: Failed to register a ServiceWorker for scope ('http://localhost:42317/') with script ('http://localhost:42317/flutter_service_worker.js'): A bad HTTP response code (404) was received when fetching the script.
```

**Comment by jonahwilliams** [comment]
Fixed via https://github.com/flutter/flutter/pull/50036

The other issue is https://github.com/flutter/flutter/issues/49479
