### ISSUE TITLE
localizationsDelegates callback returns list of locales that is platform specific

### ISSUE THREAD

**Issue by ovestoerholt** [flutter/flutter#49775]
## Steps to Reproduce

1. Install 'Flutter Intl' plugin (I am using Android Studio)
2. Create a new Flutter project
3. Use the Flutter Intl plugin menu Tools - Flutter Intl - Initialize for this project
4. Add callback function for localeListResolutionCallback
5. Two params are required: 
locales - The locales installed on device
supported - The locales supported by app

**Expected results:** 
I wan't the list of locales to return a prioritized list of locales installed on the phone.

**Actual results:** 
On iOS the list of installed locales starts on index 1.
The index 0 ( locales[0] ) is ALWAYS english (en).

**The list of supported languages should always be consistent regardless of platform.**

```
[  +20 ms] executing: [/usr/local/Cellar/flutter/stable/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[  +36 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[        ] 27321ebbad34b0a3fafe99fac037102196d655ff
[        ] executing: [/usr/local/Cellar/flutter/stable/] git describe --match v*.*.* --first-parent --long --tags
[  +13 ms] Exit code 0 from: git describe --match v*.*.* --first-parent --long --tags
[        ] v1.12.13+hotfix.5-0-g27321eb
[   +7 ms] executing: [/usr/local/Cellar/flutter/stable/] git rev-parse --abbrev-ref --symbolic @{u}
[  +14 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/stable
[        ] executing: [/usr/local/Cellar/flutter/stable/] git ls-remote --get-url origin
[  +13 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[  +57 ms] executing: [/usr/local/Cellar/flutter/stable/] git rev-parse --abbrev-ref HEAD
[  +15 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] stable
[   +6 ms] executing: sw_vers -productName
[  +15 ms] Exit code 0 from: sw_vers -productName
[        ] Mac OS X
[        ] executing: sw_vers -productVersion
[  +15 ms] Exit code 0 from: sw_vers -productVersion
[        ] 10.15.2
[        ] executing: sw_vers -buildVersion
[  +15 ms] Exit code 0 from: sw_vers -buildVersion
[        ] 19C57
[  +27 ms] executing: /usr/bin/xcode-select --print-path
[   +8 ms] Exit code 0 from: /usr/bin/xcode-select --print-path
[        ] /Applications/Xcode.app/Contents/Developer
[   +1 ms] executing: /usr/bin/xcodebuild -version
[ +205 ms] Exit code 0 from: /usr/bin/xcodebuild -version
[   +3 ms] Xcode 11.3.1
           Build version 11C504
[  +52 ms] executing: /Users/ovestorholt/Library/Android/sdk/platform-tools/adb devices -l
[   +7 ms] Exit code 0 from: /Users/ovestorholt/Library/Android/sdk/platform-tools/adb devices -l
[        ] List of devices attached
           emulator-5554          device product:sdk_gphone_x86 model:Android_SDK_built_for_x86 device:generic_x86 transport_id:15
[  +18 ms] executing: /usr/local/Cellar/flutter/stable/bin/cache/artifacts/libimobiledevice/idevice_id -h
[  +64 ms] /usr/bin/xcrun simctl list --json devices
[  +94 ms] More than one device connected; please specify a device with the '-d <deviceId>' flag, or use '-d all' to act on all devices.
[   +3 ms] /Users/ovestorholt/Library/Android/sdk/platform-tools/adb -s emulator-5554 shell getprop
[  +31 ms] ro.hardware = ranchu
[   +5 ms] Android SDK built for x86 • emulator-5554                        • android-x86 • Android 10 (API 29) (emulator)
[        ] iPhone 11 Pro Max         • D9C0D762-E002-484B-B177-E5E529313FCE • ios         • com.apple.CoreSimulator.SimRuntime.iOS-13-3 (simulator)
[  +10 ms] "flutter run" took 603ms.

#0      throwToolExit (package:flutter_tools/src/base/common.dart:28:3)
#1      RunCommand.validateCommand (package:flutter_tools/src/commands/run.dart:289:7)
<asynchronous suspension>
#2      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:590:11)
#3      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:515:33)
<asynchronous suspension>
#4      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:146:29)
#5      _rootRun (dart:async/zone.dart:1126:13)
#6      _CustomZone.run (dart:async/zone.dart:1023:19)
#7      _runZoned (dart:async/zone.dart:1518:10)
#8      runZoned (dart:async/zone.dart:1465:12)
#9      AppContext.run (package:flutter_tools/src/base/context.dart:145:18)
#10     FlutterCommand.run (package:flutter_tools/src/runner/flutter_command.dart:505:20)
#11     CommandRunner.runCommand (package:args/command_runner.dart:197:27)
#12     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:413:21)
<asynchronous suspension>
#13     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:146:29)
#14     _rootRun (dart:async/zone.dart:1126:13)
#15     _CustomZone.run (dart:async/zone.dart:1023:19)
#16     _runZoned (dart:async/zone.dart:1518:10)
#17     runZoned (dart:async/zone.dart:1465:12)
#18     AppContext.run (package:flutter_tools/src/base/context.dart:145:18)
#19     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:364:19)
#20     CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:112:25)
#21     new Future.sync (dart:async/future.dart:224:31)
#22     CommandRunner.run (package:args/command_runner.dart:112:14)
#23     FlutterCommandRunner.run (package:flutter_tools/src/runner/flutter_command_runner.dart:250:18)
#24     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:63:22)
#25     _rootRun (dart:async/zone.dart:1126:13)
#26     _CustomZone.run (dart:async/zone.dart:1023:19)
#27     _runZoned (dart:async/zone.dart:1518:10)
#28     runZoned (dart:async/zone.dart:1502:12)
#29     run.<anonymous closure> (package:flutter_tools/runner.dart:61:18)
<asynchronous suspension>
#30     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:146:29)
#31     _rootRun (dart:async/zone.dart:1126:13)
#32     _CustomZone.run (dart:async/zone.dart:1023:19)
#33     _runZoned (dart:async/zone.dart:1518:10)
#34     runZoned (dart:async/zone.dart:1465:12)
#35     AppContext.run (package:flutter_tools/src/base/context.dart:145:18)
#36     runInContext (package:flutter_tools/src/context_runner.dart:64:24)
#37     run (package:flutter_tools/runner.dart:50:10)
#38     main (package:flutter_tools/executable.dart:65:9)
#39     main (file:///private/tmp/flutter-20191213-6374-tobl26/packages/flutter_tools/bin/flutter_tools.dart:8:3)
#40     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:305:32)
#41     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:174:12)

```

```
Analyzing mssa-flutter...                                               

   info • Name non-constant identifiers using lowerCamelCase • lib/generated/l10n.dart:41:14 • non_constant_identifier_names
   info • Name non-constant identifiers using lowerCamelCase • lib/generated/l10n.dart:50:10 • non_constant_identifier_names

2 issues found. (ran in 2.5s)
```

```
[✓] Flutter (Channel stable, v1.12.13+hotfix.5, on Mac OS X 10.15.2 19C57, locale nb-NO)
    • Flutter version 1.12.13+hotfix.5 at /usr/local/Cellar/flutter/stable
    • Framework revision 27321ebbad (7 weeks ago), 2019-12-10 18:15:01 -0800
    • Engine revision 2994f7e1e6
    • Dart version 2.7.0

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/ovestorholt/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Users/ovestorholt/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-1/192.6071332/Android Studio 3.6 Preview.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.3.1, Build version 11C504
    • CocoaPods version 1.8.4

[✓] Android Studio (version 3.6)
    • Android Studio at /Users/ovestorholt/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-1/192.6071332/Android Studio 3.6 Preview.app/Contents
    • Flutter plugin version 42.2.2
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)

[✓] Android Studio (version 3.5)
    • Android Studio at /Users/ovestorholt/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/191.6010548/Android Studio.app/Contents
    • Flutter plugin version 42.1.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] Android Studio
    • Android Studio at /Users/ovestorholt/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-2/193.6137316/Android Studio 4.0 Preview.app/Contents
    • Flutter plugin version 39.0.5
    • Dart plugin version 193.2956.37
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)

[!] IntelliJ IDEA Ultimate Edition (version 2019.3.2)
    • IntelliJ at /Users/ovestorholt/Applications/JetBrains Toolbox/IntelliJ IDEA Ultimate.app
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.dev/intellij-setup/#installing-the-plugins

[✓] VS Code (version 1.41.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.7.1

[✓] Connected device (2 available)
    • Android SDK built for x86 • emulator-5554                        • android-x86 • Android 10 (API 29) (emulator)
    • iPhone 11 Pro Max         • D9C0D762-E002-484B-B177-E5E529313FCE • ios         • com.apple.CoreSimulator.SimRuntime.iOS-13-3 (simulator)

! Doctor found issues in 1 category.

```

</details>

**Comment by HansMuller** [comment]
CC @shihaohong

**Comment by GaryQian** [comment]
Looks like this is happening due to flutter/shell/platform/darwin/ios/framework/Source/FlutterEngine.mm:763

Apparently, we are prepending NSLocale.currentLocale to the beginning as explained by the comment:

>   // Force prepend the [NSLocale currentLocale] to the front of the list
>   // to ensure we are including the full default locale. preferredLocales
>   // is not guaranteed to include anything beyond the languageCode.

We should take a look and see if this is still the correct course of action.

**Comment by pedromassangocode** [comment]
Hi @ovestoerholt 
Are you still facing this issue? If yes, can you please provide your `flutter doctor -v`, your `flutter run --verbose` and a minimal complete reproducible code sample?
Thank you

**Comment by ovestoerholt** [comment]
Hei @pedromassango 
Have done some testing and localization seems to work without me needing to skip the index 0 from the system locale callback when trying to find a supported language. 
So yeah! I think we're good.
Thanks! 👍
