### ISSUE TITLE
Running example  failed -- windows

### ISSUE THREAD

**Issue by Ali1Ammar** [flutter/flutter#49793]
Hi
I have problem 
when run  flutter-desktop-embedding  example app or any app on windows 10
I get this error

I try 
-      update flutter flutter-desktop-embedding and example to last version
-      run flutter precache --windows
-      run flutter clean

```
D:\fvm\flutter-desktop-embedding\example>flutter run -d windows -v
[  +29 ms] executing: [D:\fvm\masternew/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[  +86 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[   +1 ms] a1fa1a3d261f5cee1e8dd2e7a67132f465054d83
[        ] executing: [D:\fvm\masternew/] git describe --match v*.*.* --first-parent --long --tags
[  +87 ms] Exit code 0 from: git describe --match v*.*.* --first-parent --long --tags
[        ] v1.14.3-28-ga1fa1a3d2
[   +8 ms] executing: [D:\fvm\masternew/] git rev-parse --abbrev-ref --symbolic @{u}
[  +71 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[   +1 ms] origin/master
[        ] executing: [D:\fvm\masternew/] git ls-remote --get-url origin
[  +68 ms] Exit code 0 from: git ls-remote --get-url origin
[   +1 ms] https://github.com/flutter/flutter.git
[ +146 ms] executing: [D:\fvm\masternew/] git rev-parse --abbrev-ref HEAD
[  +78 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] master
[  +74 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[   +2 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[   +3 ms] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[  +20 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[   +9 ms] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[   +2 ms] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[ +347 ms] executing: D:\android\sdk\platform-tools\adb.exe devices -l
[  +53 ms] Exit code 0 from: D:\android\sdk\platform-tools\adb.exe devices -l
[   +3 ms] List of devices attached
[  +41 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[   +2 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[   +3 ms] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +8 ms] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[   +2 ms] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[   +6 ms] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[   +3 ms] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[ +472 ms] Launching lib\main.dart on Windows in debug mode...
[  +96 ms] executing: C:\Program Files (x86)\Microsoft Visual Studio\Installer\vswhere.exe -format json -utf8 -latest
-version 16 -requires Microsoft.Component.MSBuild Microsoft.VisualStudio.Component.VC.Tools.x86.x64
Microsoft.VisualStudio.Component.Windows10SDK.17763
[  +66 ms] Exit code 0 from: C:\Program Files (x86)\Microsoft Visual Studio\Installer\vswhere.exe -format json -utf8
-latest -version 16 -requires Microsoft.Component.MSBuild Microsoft.VisualStudio.Component.VC.Tools.x86.x64
Microsoft.VisualStudio.Component.Windows10SDK.17763
[   +6 ms] [
             {
               "instanceId": "4fb834e7",
               "installDate": "2019-12-02T23:09:25Z",
               "installationName": "VisualStudio/16.3.10+29519.87",
               "installationPath": "C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Community",
               "installationVersion": "16.3.29519.87",
               "productId": "Microsoft.VisualStudio.Product.Community",
               "productPath": "C:\\Program Files (x86)\\Microsoft Visual
               Studio\\2019\\Community\\Common7\\IDE\\devenv.exe",
               "state": 4294967295,
               "isComplete": true,
               "isLaunchable": true,
               "isPrerelease": false,
               "isRebootRequired": false,
               "displayName": "Visual Studio Community 2019",
               "description": "Powerful IDE, free for students, open-source contributors, and individuals",
               "channelId": "VisualStudio.16.Release",
               "channelUri": "https://aka.ms/vs/16/release/channel",
               "enginePath": "C:\\Program Files (x86)\\Microsoft Visual
               Studio\\Installer\\resources\\app\\ServiceHub\\Services\\Microsoft.VisualStudio.Setup.Service",
               "releaseNotes": "https://go.microsoft.com/fwlink/?LinkId=660893#16.3.10",
               "thirdPartyNotices": "https://go.microsoft.com/fwlink/?LinkId=660909",
               "updateDate": "2019-12-02T23:09:25.0605462Z",
               "catalog": {
                 "buildBranch": "d16.3",
                 "buildVersion": "16.3.29519.87",
                 "id": "VisualStudio/16.3.10+29519.87",
                 "localBuild": "build-lab",
                 "manifestName": "VisualStudio",
                 "manifestType": "installer",
                 "productDisplayVersion": "16.3.10",
                 "productLine": "Dev16",
                 "productLineVersion": "2019",
                 "productMilestone": "RTW",
                 "productMilestoneIsPreRelease": "False",
                 "productName": "Visual Studio",
                 "productPatchVersion": "10",
                 "productPreReleaseMilestoneSuffix": "1.0",
                 "productSemanticVersion": "16.3.10+29519.87",
                 "requiredEngineVersion": "2.3.2283.19382"
               },
               "properties": {
                 "campaignId": "1346216582.1575322022",
                 "channelManifestId": "VisualStudio.16.Release/16.3.10+29519.87",
                 "nickname": "",
                 "setupEngineFilePath": "C:\\Program Files (x86)\\Microsoft Visual
                 Studio\\Installer\\vs_installershell.exe"
               }
             }
           ]
[  +16 ms] Building Windows application...
[   +6 ms] executing: [D:\fvm\flutter-desktop-embedding\example\windows/]
D:\fvm\masternew\packages\flutter_tools\bin\vs_build.bat C:\Program Files (x86)\Microsoft Visual
Studio\2019\Community\VC\Auxiliary\Build\vcvars64.bat Runner.sln Debug
[ +404 ms] **********************************************************************
[   +5 ms] ** Visual Studio 2019 Developer Command Prompt v16.3.10
[   +1 ms] ** Copyright (c) 2019 Microsoft Corporation
[   +1 ms] **********************************************************************
[+7039 ms] [vcvarsall.bat] Environment initialized for: 'x64'
[ +121 ms] Microsoft (R) Build Engine version 16.3.2+e481bbf88 for .NET Framework
[   +1 ms] Copyright (C) Microsoft Corporation. All rights reserved.
[        ] Building the projects in this solution one at a time. To enable parallel build, please add the "-m" switch.
[  +45 ms] Build started 1/30/2020 6:10:31 PM.
[ +226 ms] Project "D:\fvm\flutter-desktop-embedding\example\windows\Runner.sln" on node 1 (default targets).
[   +2 ms] ValidateSolutionConfiguration:
[        ]   Building solution configuration "Debug|x64".
[ +219 ms] Project "D:\fvm\flutter-desktop-embedding\example\windows\Runner.sln" (1) is building
"D:\fvm\flutter-desktop-embedding\example\windows\Runner.vcxproj.metaproj" (2) on node 1 (default targets).
[   +2 ms] Project "D:\fvm\flutter-desktop-embedding\example\windows\Runner.vcxproj.metaproj" (2) is building
"D:\fvm\flutter-desktop-embedding\example\windows\FlutterBuild.vcxproj" (3) on node 1 (default targets).
[   +1 ms] InitializeBuildStatus:
[        ]   Creating "x64\Debug\Flutter Build.tlog\unsuccessfulbuild" because "AlwaysCreate" was specified.
[  +18 ms] CustomBuildStep:
[   +2 ms]   Running Flutter backend build
[  +24 ms]   "D:\fvm\flutter-desktop-embedding\example\windows\scripts\prepare_dependencies" Debug
[   +1 ms]   :VCEnd
[+26846 ms] FinalizeBuildStatus:
[   +2 ms]   Deleting file "x64\Debug\Flutter Build.tlog\unsuccessfulbuild".
[   +1 ms]   Touching "x64\Debug\Flutter Build.tlog\Flutter Build.lastbuildstate".
[   +2 ms] Done Building Project "D:\fvm\flutter-desktop-embedding\example\windows\FlutterBuild.vcxproj" (default
targets).
[ +129 ms] Project "D:\fvm\flutter-desktop-embedding\example\windows\Runner.vcxproj.metaproj" (2) is building
"D:\fvm\flutter-desktop-embedding\example\windows\Runner.vcxproj" (4) on node 1 (default targets).
[   +3 ms] PrepareForBuild:
[   +1 ms]   Creating directory
"D:\fvm\flutter-desktop-embedding\example\windows\..\build\windows\intermediates\x64\Debug\Runner\".
[   +2 ms]   Creating directory "D:\fvm\flutter-desktop-embedding\example\windows\..\build\windows\x64\Debug\Runner\".
[   +1 ms]   Creating directory
"D:\fvm\flutter-desktop-embedding\example\windows\..\build\windows\intermediates\x64\Debug\Runner\Runner.tlog\".
[   +2 ms] InitializeBuildStatus:
[   +1 ms]   Creating
"D:\fvm\flutter-desktop-embedding\example\windows\..\build\windows\intermediates\x64\Debug\Runner\Runner.tlog\unsuccessfulbuild" because "AlwaysCreate" was specified.
[  +61 ms] ClCompile:
[   +1 ms]   C:\Program Files (x86)\Microsoft Visual
Studio\2019\Community\VC\Tools\MSVC\14.23.28105\bin\HostX86\x64\CL.exe /c /ZI /JMC /nologo /W3 /WX- /diagnostics:column
/sdl /Od /D _MBCS /D _UNICODE /D UNICODE /Gm- /EHsc /RTC1 /MDd /GS /fp:precise /permissive- /Zc:wchar_t /Zc:forScope
/Zc:inline /Fo"D:\fvm\flutter-desktop-embedding\example\windows\..\build\windows\intermediates\x64\Debug\Runner\\"
/Fd"D:\fvm\flutter-desktop-embedding\example\windows\..\build\windows\intermediates\x64\Debug\Runner\vc142.pdb" /Gd /TP
/FC /errorReport:queue main.cpp flutter\generated_plugin_registrant.cc window_configuration.cpp win32_window.cc
"D:\fvm\flutter-desktop-embedding\example\windows\flutter\ephemeral\cpp_client_wrapper\engine_method_result.cc"
"D:\fvm\flutter-desktop-embedding\example\windows\flutter\ephemeral\cpp_client_wrapper\flutter_view_controller.cc"
"D:\fvm\flutter-desktop-embedding\example\windows\flutter\ephemeral\cpp_client_wrapper\plugin_registrar.cc"
[ +144 ms]   main.cpp
[+2291 ms]   generated_plugin_registrant.cc
[ +870 ms]   window_configuration.cpp
[ +197 ms] D:\fvm\flutter-desktop-embedding\example\windows\main.cpp(26,10): fatal error C1083: Cannot open include
file: 'window_configuration.h': No such file or directory
[D:\fvm\flutter-desktop-embedding\example\windows\Runner.vcxproj]
[   +7 ms]   win32_window.cc
[+1700 ms]   engine_method_result.cc
[+1310 ms]   flutter_view_controller.cc
[+2308 ms]   plugin_registrar.cc
[+1561 ms]   Generating Code...
[ +517 ms] D:\fvm\flutter-desktop-embedding\example\windows\window_configuration.cpp(15,10): fatal error C1083: Cannot
open include file: 'window_configuration.h': No such file or directory
[D:\fvm\flutter-desktop-embedding\example\windows\Runner.vcxproj]
[ +137 ms] Done Building Project "D:\fvm\flutter-desktop-embedding\example\windows\Runner.vcxproj" (default targets) --
FAILED.
[   +3 ms] Done Building Project "D:\fvm\flutter-desktop-embedding\example\windows\Runner.vcxproj.metaproj" (default
targets) -- FAILED.
[   +1 ms] Done Building Project "D:\fvm\flutter-desktop-embedding\example\windows\Runner.sln" (default targets) --
FAILED.
[   +2 ms] Build FAILED.
[   +6 ms] "D:\fvm\flutter-desktop-embedding\example\windows\Runner.sln" (default target) (1) ->
[   +1 ms] "D:\fvm\flutter-desktop-embedding\example\windows\Runner.vcxproj.metaproj" (default target) (2) ->
[   +1 ms] "D:\fvm\flutter-desktop-embedding\example\windows\Runner.vcxproj" (default target) (4) ->
[   +1 ms] (ClCompile target) ->
[   +1 ms]   D:\fvm\flutter-desktop-embedding\example\windows\main.cpp(26,10): fatal error C1083: Cannot open include
file: 'window_configuration.h': No such file or directory
[D:\fvm\flutter-desktop-embedding\example\windows\Runner.vcxproj]
[   +2 ms]   D:\fvm\flutter-desktop-embedding\example\windows\window_configuration.cpp(15,10): fatal error C1083: Cannotopen include file: 'window_configuration.h': No such file or directory
[D:\fvm\flutter-desktop-embedding\example\windows\Runner.vcxproj]
[   +3 ms]     0 Warning(s)
[   +1 ms]     2 Error(s)
[   +1 ms] Time Elapsed 00:00:38.61
[  +28 ms] Building Windows application... (completed in 46.3s)
[   +9 ms] "flutter run" took 47,647ms.
Build process failed. To view the stack trace, please run `flutter run -d windows -v`.

#0      throwToolExit (package:flutter_tools/src/base/common.dart:27:3)
#1      buildWindows (package:flutter_tools/src/windows/build_windows.dart:88:5)
<asynchronous suspension>
#2      WindowsDevice.buildForDevice (package:flutter_tools/src/windows/windows_device.dart:46:11)
#3      DesktopDevice.startApp (package:flutter_tools/src/desktop_device.dart:86:13)
#4      FlutterDevice.runHot (package:flutter_tools/src/resident_runner.dart:434:54)
<asynchronous suspension>
#5      HotRunner.run (package:flutter_tools/src/run_hot.dart:333:39)
#6      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:555:37)
<asynchronous suspension>
#7      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:637:18)
#8      _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:75:64)
#9      _rootRunUnary (dart:async/zone.dart:1134:38)
#10     _CustomZone.runUnary (dart:async/zone.dart:1031:19)
#11     _FutureListener.handleValue (dart:async/future_impl.dart:140:18)
#12     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:682:45)
#13     Future._propagateToListeners (dart:async/future_impl.dart:711:32)
#14     Future._completeWithValue (dart:async/future_impl.dart:526:5)
#15     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:34:15)
#16     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:293:13)
#17     RunCommand.usageValues (package:flutter_tools/src/commands/run.dart)
#18     _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:75:64)
#19     _rootRunUnary (dart:async/zone.dart:1134:38)
#20     _CustomZone.runUnary (dart:async/zone.dart:1031:19)
#21     _FutureListener.handleValue (dart:async/future_impl.dart:140:18)
#22     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:682:45)
#23     Future._propagateToListeners (dart:async/future_impl.dart:711:32)
#24     Future._completeWithValue (dart:async/future_impl.dart:526:5)
#25     Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:556:7)
#26     _rootRun (dart:async/zone.dart:1126:13)
#27     _CustomZone.run (dart:async/zone.dart:1023:19)
#28     _CustomZone.runGuarded (dart:async/zone.dart:925:7)
#29     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:965:23)
#30     _microtaskLoop (dart:async/schedule_microtask.dart:43:21)
#31     _startMicrotaskLoop (dart:async/schedule_microtask.dart:52:5)
#32     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
#33     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:169:5)
```

flutter doctor

```
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel master, v1.14.4-pre.28, on Microsoft Windows [Version 10.0.18363.592], locale en-US)

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[√] Chrome - develop for the web
[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.3.10)
[√] Android Studio (version 3.5)
[√] Connected device (3 available)

• No issues found!
```
note : I always change flutter path between stable ,master and old version folder
and this error started when I started doing it.

**Comment by stuartmorgan** [comment]
> `[ +197 ms] D:\fvm\flutter-desktop-embedding\example\windows\main.cpp(26,10): fatal error C1083: Cannot open include
file: 'window_configuration.h': No such file or directory`

You've apparently deleted a file from the `windows` directory. If you edit or delete files from the runner, it's up to you to make the changes in a way that doesn't break compilation.
