### ISSUE TITLE
Failure to run a Flutter driver test on device chrome

### ISSUE THREAD

**Issue by DaveShuckerow** [flutter/flutter#49843]
```dart
$ flutter drive -d chrome test_driver/integration/integration_app.dart
Starting application: test_driver/integration/integration.dart

Oops; flutter has exited unexpectedly: "SocketException: Connection failed (OS Error: Connection refused, errno = 61), address =
localhost, port = 4444".
 
A crash report has been written to /Users/djshuckerow/Code/github.com/DaveShuckerow/devtools/packages/devtools_app/flutter_05.log.
This crash may already be reported. Check GitHub for similar crashes.
https://git.io/JvOdn

To report your crash to the Flutter team, first read the guide to filing a bug.
https://flutter.dev/docs/resources/bug-reports

Create a new GitHub issue by pasting this link into your browser and completing the issue template. Thank you!
Unable to generate crash report due to secondary error: NoSuchMethodError: The method '[]' was called on null.
Receiver: null
Tried calling: []("package")
please let us know at https://github.com/flutter/flutter/issues.

Oops; flutter has exited unexpectedly: "SocketException: Connection failed (OS Error: Connection refused, errno = 61), address =
localhost, port = 4444".
A crash report has been written to /Users/djshuckerow/Code/github.com/DaveShuckerow/devtools/packages/devtools_app/flutter_06.log.
This crash may already be reported. Check GitHub for similar crashes.
https://git.io/JvOdn

To report your crash to the Flutter team, first read the guide to filing a bug.
https://flutter.dev/docs/resources/bug-reports

Create a new GitHub issue by pasting this link into your browser and completing the issue template. Thank you!
Unable to generate crash report due to secondary error: NoSuchMethodError: The method '[]' was called on null.
Receiver: null
Tried calling: []("package")
please let us know at https://github.com/flutter/flutter/issues.
Unhandled exception:
ProcessExit: 1
#0      _handleToolError (package:flutter_tools/runner.dart:148:7)
<asynchronous suspension>
#1      run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:78:13)
#2      _rootRunBinary (dart:async/zone.dart:1150:13)
#3      _CustomZone.runBinary (dart:async/zone.dart:1039:19)
#4      runZoned.<anonymous closure> (dart:async/zone.dart:1481:21)
#5      _CustomZone.handleUncaughtError (dart:async/zone.dart:1005:19)
#6      Future._propagateToListeners (dart:async/future_impl.dart:632:16)
#7      Future._completeError (dart:async/future_impl.dart:534:5)
#8      _AsyncAwaitCompleter.completeError (dart:async-patch/async_patch.dart:40:15)
#9      run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart)
<asynchronous suspension>
#10     _rootRun (dart:async/zone.dart:1126:13)
#11     _CustomZone.run (dart:async/zone.dart:1023:19)
#12     _runZoned (dart:async/zone.dart:1518:10)
#13     runZoned (dart:async/zone.dart:1502:12)
#14     run.<anonymous closure> (package:flutter_tools/runner.dart:62:18)
<asynchronous suspension>
#15     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:29)
#16     _rootRun (dart:async/zone.dart:1126:13)
#17     _CustomZone.run (dart:async/zone.dart:1023:19)
#18     _runZoned (dart:async/zone.dart:1518:10)
#19     runZoned (dart:async/zone.dart:1465:12)
#20     AppContext.run (package:flutter_tools/src/base/context.dart:149:18)
#21     runInContext (package:flutter_tools/src/context_runner.dart:64:24)
#22     run (package:flutter_tools/runner.dart:51:10)
#23     main (package:flutter_tools/executable.dart:65:9)
#24     main (file:///Users/djshuckerow/Code/github.com/DaveShuckerow/flutter/packages/flutter_tools/bin/flutter_tools.dart:8:3)
#25     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:299:32)
#26     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:168:12)
```

---Doctor---
```
$ flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel master, v1.14.7-pre.27, on Mac OS X 10.14.6 18G2022, locale en-US)
 
[✓] Xcode - develop for iOS and macOS (Xcode 11.3)
[✓] Chrome - develop for the web
[✓] IntelliJ IDEA Community Edition (version 2019.1.3)
[✓] Connected device (3 available)
```

Test code:
integration.dart:
```
import 'package:devtools_app/main.dart' as devtools_app;

import 'package:flutter_driver/driver_extension.dart' as flutter_driver;

void main() {
  flutter_driver.enableFlutterDriverExtension();
  devtools_app.main();
}

```

integration_test.dart:
```dart
import 'package:flutter_driver/flutter_driver.dart';
import 'package:test/test.dart';

void main() {
  group('Whole app', () {
    FlutterDriver driver;
    setUpAll(() async {
      driver = await FlutterDriver.connect();
    });
    tearDownAll(() async {
      if (driver != null) await driver.close();
    });

    test('loads', () async {
      expect(await driver.getText(find.text('Connect')), 'Connect');
    });
  });
}
```

This is part of an effort to write integration tests for the devtools Flutter app.

Related: 
- #49841 (can't run the same test as this issue on desktop)
- #49838 (can't `flutter run` a widget test on device chrome)

**Comment by JChrist** [comment]
I seem to be having the same issue, but with a slightly different error (different errno reported)
```
Oops; flutter has exited unexpectedly: "SocketException: Connection failed (OS Error: No connection could be made because the target machine actively refused it.
, errno = 10061), address = localhost, port = 4444".
```

--- Doctor ---
```
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel master, v1.14.7-pre.101, on Microsoft Windows [Version 10.0.19555.1001], locale en-US)
[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[√] Chrome - develop for the web
[!] Android Studio (not installed)
[√] IntelliJ IDEA Ultimate Edition (version 2019.3)
[√] VS Code (version 1.41.1)
[√] Connected device (2 available)
```

**Comment by solid-software** [comment]
Hi @DaveShuckerow,

can you try using WebFlutterDriver?

```dart
      setUpAll(() async {
        driver = await WebFlutterDriver.connectWeb();
      });
```

Also make sure to do other steps (selenium, etc..) from here:
https://github.com/flutter/flutter/pull/45951


> 1) Have Selenium server (https://bit.ly/2TlkRyu) and WebDriver binary (https://chromedriver.chromium.org/downloads) downloaded and placed under the same folder
> 2) Launch WebDriver Server: java -jar selenium-server-standalone-3.141.59.jar
> 3) Launch Flutter Web application: flutter run -v -d chrome --target=test_driver/scroll_perf_web.dart
> 4) Run test script: flutter drive --target=test_driver/scroll_perf.dart -v --use-existing-app=/application address/

**Comment by nturgut** [comment]
/cc @angjieli 
The steps to run a drive test with the web:

install the browser driver for the particular browser in use. (ex chrome)
install java
install selenium server standalone.
run selenium server.
flutter run -d chrome/web-server (for the application to be tested with driver. any mode is fine so one can add --profile or --release)
flutter drive --target=the_driver_test.dart -v --use-existing-app=address_of_application

we should make it simpler or give better errors, we will work on it soon. For now please follow these steps.
