### ISSUE TITLE
Flutter is not able to start when launching on Android simulator: Could not connect to lockdownd, error code -17

### ISSUE THREAD

**Issue by saschak094** [flutter/flutter#49879]
## Steps to Reproduce

1. Connect iPhone via USB-C to Mac
2. Open flutter project in VSCode 
3. Try to "Launch Flutter Emulator"

## Logs
```
[2:07:39 PM] [General] [Info] Returning cached promise for getSupportedPlatforms()
[2:07:39 PM] [General] [Info] Returning cached promise for getSupportedPlatforms()
[2:07:39 PM] [General] [Info] Checking 1 projects for supported platforms
[2:07:39 PM] [General] [Info] Supported platforms for the workspace are ios, android, web
[2:07:39 PM] [FlutterDaemon] [Error] ideviceinfo returned an error:
ERROR: Could not connect to lockdownd, error code -17
[2:07:54 PM] [General] [Info] Starting debug session...
[2:07:54 PM] [General] [Info]     workspace: /Users/username/Documents/flutter-projects/project
[2:07:54 PM] [General] [Info] Using found common entry point: /Users/username/Documents/flutter-projects/project/lib/main.dart
[2:07:54 PM] [General] [Info] Using workspace as cwd: /Users/username/Documents/flutter-projects/project
[2:07:54 PM] [General] [Info] Detected launch project as Flutter
[2:07:54 PM] [General] [Info] Using Flutter debug adapter for this session
[2:10:28 PM] [General] [Info] Starting debug session...
[2:10:28 PM] [General] [Info]     workspace: /Users/username/Documents/flutter-projects/project
[2:10:28 PM] [General] [Info] Using found common entry point: /Users/username/Documents/flutter-projects/project/lib/main.dart
[2:10:28 PM] [General] [Info] Using workspace as cwd: /Users/username/Documents/flutter-projects/project
[2:10:28 PM] [General] [Info] Detected launch project as Flutter
[2:10:28 PM] [General] [Info] Using Flutter debug adapter for this session
```

**Comment by iapicca** [comment]
Hi @saschak094 
can you please provide your `flutter doctor -v`
and your `flutter run --verbose`
Thank you

**Comment by saschak094** [comment]
```
[✓] Flutter (Channel beta, v1.13.6, on Mac OS X 10.15.2 19C57, locale en-US)
    • Flutter version 1.13.6 at /Users/username/Documents/workspace/flutter
    • Framework revision 659dc8129d (5 weeks ago), 2019-12-30 09:24:47 -0800
    • Engine revision bdc9708d23
    • Dart version 2.8.0 (build 2.8.0-dev.0.0 c547f5d933)

[!] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/username/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses

[✓] Xcode - develop for iOS and macOS (Xcode 11.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.3, Build version 11C29
    • CocoaPods version 1.8.4

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[!] Android Studio (version 3.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)

[✓] VS Code (version 1.41.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.7.1

[☠] Connected device (the doctor check crashed)
    ✗ Due to an error, the doctor check did not complete. If the error message below is not helpful, please let us know about this issue at https://github.com/flutter/flutter/issues.
    ✗ Exception: ideviceinfo returned an error:
      ERROR: Could not connect to lockdownd, error code -18

    • #0      IMobileDevice.getInfoForDevice (package:flutter_tools/src/ios/mac.dart:226:9)
      <asynchronous suspension>
      #1      IOSDevice.getAttachedDevices (package:flutter_tools/src/ios/devices.dart:190:55)
      <asynchronous suspension>
      #2      IOSDevices.pollingGetDevices (package:flutter_tools/src/ios/devices.dart:115:57)
      #3      PollingDeviceDiscovery.devices (package:flutter_tools/src/device.dart:285:52)
      #4      DeviceManager.getAllConnectedDevices (package:flutter_tools/src/device.dart:140:46)
      <asynchronous suspension>
      #5      DeviceValidator.validate (package:flutter_tools/src/doctor.dart:860:54)
      #6      asyncGuard.<anonymous closure> (package:flutter_tools/src/base/async_guard.dart:111:32)
      #7      _rootRun (dart:async/zone.dart:1126:13)
      #8      _CustomZone.run (dart:async/zone.dart:1023:19)
      #9      _runZoned (dart:async/zone.dart:1518:10)
      #10     runZoned (dart:async/zone.dart:1502:12)
      #11     asyncGuard (package:flutter_tools/src/base/async_guard.dart:109:3)
      #12     Doctor.startValidatorTasks (package:flutter_tools/src/doctor.dart:158:9)
      #13     Doctor.diagnose (package:flutter_tools/src/doctor.dart:252:41)
      #14     _AsyncAwaitCompleter.start (dart:async-patch/async_patch.dart:47:6)
      #15     Doctor.diagnose (package:flutter_tools/src/doctor.dart:241:24)
      #16     DoctorCommand.runCommand (package:flutter_tools/src/commands/doctor.dart:58:39)
      #17     _AsyncAwaitCompleter.start (dart:async-patch/async_patch.dart:47:6)
      #18     DoctorCommand.runCommand (package:flutter_tools/src/commands/doctor.dart:44:42)
      #19     FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:626:18)
      #20     _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:75:64)
      #21     _rootRunUnary (dart:async/zone.dart:1134:38)
      #22     _CustomZone.runUnary (dart:async/zone.dart:1031:19)
      #23     _FutureListener.handleValue (dart:async/future_impl.dart:140:18)
      #24     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:682:45)
      #25     Future._propagateToListeners (dart:async/future_impl.dart:711:32)
      #26     Future._completeWithValue (dart:async/future_impl.dart:526:5)
      #27     Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:556:7)
      #28     _rootRun (dart:async/zone.dart:1126:13)
      #29     _CustomZone.run (dart:async/zone.dart:1023:19)
      #30     _CustomZone.runGuarded (dart:async/zone.dart:925:7)
      #31     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:965:23)
      #32     _microtaskLoop (dart:async/schedule_microtask.dart:43:21)
      #33     _startMicrotaskLoop (dart:async/schedule_microtask.dart:52:5)
      #34     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
      #35     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:175:5
```

**Comment by jmagman** [comment]
-17 is "Could not connect to lockdownd: Password protected "

Is your device unlocked?  Does `ios/Runner.xcworkspace` run in Xcode?

**Comment by saschak094** [comment]
xCode does not run at all. 
Yes my phone is locked, but I just connected it to charge it. I wanted to run my app on the Android simulator.

**Comment by jmagman** [comment]
Did you have the emulator selected as the targeted device?  Or your plugged in, locked iOS device? https://flutter.dev/docs/get-started/test-drive?tab=vscode#vscode

**Comment by saschak094** [comment]
Yes the emulator is selected as target device.

<img width="390" alt="Screen Shot 2020-02-04 at 8 46 36 AM" src="https://user-images.githubusercontent.com/12532853/73724187-13d34480-472b-11ea-95da-32b4a24c67d4.png">

**Comment by jmagman** [comment]
It's weird you had the Android simulator selected and it was crashing on iOS discovery, but I believe this may be resolved with https://github.com/flutter/flutter/pull/50252, which made it into v1.15.2.  Can you try on the [dev channel](https://github.com/flutter/flutter/wiki/Flutter-build-release-channels#how-to-change-channels)?

**Comment by saschak094** [comment]
Tested on version 1.15.17, seems to work now
