### ISSUE TITLE
Oops; flutter has exited unexpectedly.

### ISSUE THREAD

**Issue by dharmadeveloper108** [flutter/flutter#49897]
## command

flutter run

## exception

ProcessException: ProcessException: No such file or directory
  Command: /usr/local/bin/pod install --verbose

```
#0      CocoaPods._runPodInstall (package:flutter_tools/src/macos/cocoapods.dart:300:34)
<asynchronous suspension>
#1      CocoaPods.processPods (package:flutter_tools/src/macos/cocoapods.dart:145:15)
<asynchronous suspension>
#2      processPodsIfNeeded (package:flutter_tools/src/macos/cocoapod_utils.dart:36:46)
<asynchronous suspension>
#3      buildXcodeProject (package:flutter_tools/src/ios/mac.dart:357:9)
<asynchronous suspension>
#4      IOSSimulator._setupUpdatedApplicationBundle (package:flutter_tools/src/ios/simulators.dart:436:48)
<asynchronous suspension>
#5      IOSSimulator.startApp (package:flutter_tools/src/ios/simulators.dart:354:15)
#6      FlutterDevice.runHot (package:flutter_tools/src/resident_runner.dart:450:54)
#7      _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:73:64)
#8      _rootRunUnary (dart:async/zone.dart:1134:38)
#9      _CustomZone.runUnary (dart:async/zone.dart:1031:19)
#10     _FutureListener.handleValue (dart:async/future_impl.dart:139:18)
#11     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:680:45)
#12     Future._propagateToListeners (dart:async/future_impl.dart:709:32)
#13     Future._completeWithValue (dart:async/future_impl.dart:524:5)
#14     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:32:15)
#15     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:290:13)
#16     ApplicationPackageFactory.getPackageForPlatform (package:flutter_tools/src/application_package.dart)
#17     _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:73:64)
#18     _rootRunUnary (dart:async/zone.dart:1134:38)
#19     _CustomZone.runUnary (dart:async/zone.dart:1031:19)
#20     _FutureListener.handleValue (dart:async/future_impl.dart:139:18)
#21     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:680:45)
#22     Future._propagateToListeners (dart:async/future_impl.dart:709:32)
#23     Future._completeWithValue (dart:async/future_impl.dart:524:5)
#24     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:32:15)
#25     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:290:13)
#26     BuildableIOSApp.fromProject (package:flutter_tools/src/application_package.dart)
#27     _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:73:64)
#28     _rootRunUnary (dart:async/zone.dart:1134:38)
#29     _CustomZone.runUnary (dart:async/zone.dart:1031:19)
#30     _FutureListener.handleValue (dart:async/future_impl.dart:139:18)
#31     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:680:45)
#32     Future._propagateToListeners (dart:async/future_impl.dart:709:32)
#33     Future._completeWithValue (dart:async/future_impl.dart:524:5)
#34     Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:554:7)
#35     _rootRun (dart:async/zone.dart:1126:13)
#36     _CustomZone.run (dart:async/zone.dart:1023:19)
#37     _CustomZone.runGuarded (dart:async/zone.dart:925:7)
#38     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:965:23)
#39     _microtaskLoop (dart:async/schedule_microtask.dart:43:21)
#40     _startMicrotaskLoop (dart:async/schedule_microtask.dart:52:5)
#41     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
#42     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:175:5)
```

## flutter doctor

```
[32m[✓][39m Flutter (Channel unknown, v1.12.13+hotfix.5, on Mac OS X 10.15.1 19B88, locale en-IT)
    [32m•[39m Flutter version 1.12.13+hotfix.5 at /Users/dharmadeveloper/development/flutter
    [32m•[39m Framework revision 27321ebbad (7 weeks ago), 2019-12-10 18:15:01 -0800
    [32m•[39m Engine revision 2994f7e1e6
    [32m•[39m Dart version 2.7.0

[32m[✓][39m Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    [32m•[39m Android SDK at /Users/dharmadeveloper/Library/Android/sdk
    [32m•[39m Android NDK location not configured (optional; useful for native profiling support)
    [32m•[39m Platform android-29, build-tools 29.0.2
    [32m•[39m Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    [32m•[39m Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    [32m•[39m All Android licenses accepted.

[33m[!][39m Xcode - develop for iOS and macOS (Xcode 11.3)
    [32m•[39m Xcode at /Applications/Xcode.app/Contents/Developer
    [32m•[39m Xcode 11.3, Build version 11C29
    [31m✗[39m CocoaPods installed but not working.
        You appear to have CocoaPods installed but it is not working.
        This can happen if the version of Ruby that CocoaPods was installed with is different from the one being used to invoke it.
        This can usually be fixed by re-installing CocoaPods. For more info, see https://github.com/flutter/flutter/issues/14293.
      To re-install CocoaPods, run:
        sudo gem install cocoapods

[32m[✓][39m Android Studio (version 3.5)
    [32m•[39m Android Studio at /Applications/Android Studio.app/Contents
    [32m•[39m Flutter plugin version 40.0.2
    [32m•[39m Dart plugin version 191.8423
    [32m•[39m Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[33m[!][39m IntelliJ IDEA Ultimate Edition (version 2019.3.1)
    [32m•[39m IntelliJ at /Applications/IntelliJ IDEA.app
    [31m✗[39m Flutter plugin not installed; this adds Flutter specific functionality.
    [31m✗[39m Dart plugin not installed; this adds Dart specific functionality.
    [32m•[39m For information about installing plugins, see
      https://flutter.dev/intellij-setup/#installing-the-plugins

[32m[✓][39m VS Code (version 1.41.1)
    [32m•[39m VS Code at /Applications/Visual Studio Code.app/Contents
    [32m•[39m Flutter extension version 3.7.1

[32m[✓][39m Connected device (1 available)
    [32m•[39m iPhone 11 Pro Max • 96B1DFB8-1831-4413-9164-100721878A6F • ios • com.apple.CoreSimulator.SimRuntime.iOS-13-3 (simulator)

[33m![39m Doctor found issues in 2 categories.
```

**Comment by DanTup** [comment]
There are some issues in your `flutter doctor` output that look related to this:

```
    �[31m✗�[39m CocoaPods installed but not working.
        You appear to have CocoaPods installed but it is not working.
        This can happen if the version of Ruby that CocoaPods was installed with is different from the one being used to invoke it.
        This can usually be fixed by re-installing CocoaPods. For more info, see https://github.com/flutter/flutter/issues/14293.
      To re-install CocoaPods, run:
        sudo gem install cocoapods
```

Can you try re-installing as described above and see if that resolves the issue (and/or fixes the `doctor` warning)?

**Comment by VladyslavBondarenko** [comment]
@dharmadeveloper108 
I hope this solved your issue
Closing since long time without an answer
