### ISSUE TITLE
flutter run fails after updating to the latest stable release

### ISSUE THREAD

**Issue by cherlow** [flutter/flutter#49935]
After running  flutter run in my app i get the following error  

**_NOTE: before the update everything worked_**
```
 FAILURE: Build failed with an exception.
[  +50 ms] * What went wrong:
[   +1 ms] Execution failed for task ':app:checkDebugDuplicateClasses'.
[   +1 ms] > 1 exception was raised by workers:
[   +1 ms]   java.util.zip.ZipException

```

**Here is the full output of flutter run -v**

```
[  +40 ms] executing: [C:\flutter\] git -c log.showSignature=false log -n 1 --pretty=format:%H
[ +102 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[   +3 ms] 9f5ff2306bb3e30b2b98eee79cd231b1336f41f4
[        ] executing: [C:\flutter\] git describe --match v*.*.* --first-parent --long --tags
[  +56 ms] Exit code 0 from: git describe --match v*.*.* --first-parent --long --tags
[        ] v1.12.13+hotfix.7-0-g9f5ff2306
[  +10 ms] executing: [C:\flutter\] git rev-parse --abbrev-ref --symbolic @{u}
[  +70 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/stable
[        ] executing: [C:\flutter\] git ls-remote --get-url origin
[  +50 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[ +119 ms] executing: [C:\flutter\] git rev-parse --abbrev-ref HEAD
[  +70 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] stable
[ +161 ms] executing: C:\Users\M.U.S.E.M.B.I\AppData\Local\Android\Sdk\platform-tools\adb.exe devices -l
[  +30 ms] Exit code 0 from: C:\Users\M.U.S.E.M.B.I\AppData\Local\Android\Sdk\platform-tools\adb.exe devices -l
[   +1 ms] List of devices attached
           emulator-5554          device product:sdk_gphone_x86 model:Android_SDK_built_for_x86 device:generic_x86
           transport_id:2
[  +32 ms] C:\Users\M.U.S.E.M.B.I\AppData\Local\Android\Sdk\platform-tools\adb.exe -s emulator-5554 shell getprop
[ +111 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[  +11 ms] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +5 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[   +2 ms] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[   +3 ms] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[   +3 ms] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[ +232 ms] Generating F:\flutter\gallery\android\app\src\main\java\io\flutter\plugins\GeneratedPluginRegistrant.java
[  +49 ms] ro.hardware = ranchu
[  +77 ms] Using hardware rendering with device Android SDK built for x86. If you get graphics artifacts, consider
enabling
           software rendering with "--enable-software-rendering".
[  +27 ms] Launching lib\main.dart on Android SDK built for x86 in debug mode...
[  +24 ms] executing: C:\Users\M.U.S.E.M.B.I\AppData\Local\Android\Sdk\platform-tools\adb.exe -s emulator-5554 shell -x
logcat -v time -s flutter
[  +10 ms] executing: C:\Users\M.U.S.E.M.B.I\AppData\Local\Android\Sdk\platform-tools\adb.exe version
[  +66 ms] Android Debug Bridge version 1.0.41
           Version 29.0.4-5871666
           Installed as C:\Users\M.U.S.E.M.B.I\AppData\Local\Android\Sdk\platform-tools\adb.exe
[   +8 ms] executing: C:\Users\M.U.S.E.M.B.I\AppData\Local\Android\Sdk\platform-tools\adb.exe start-server
[  +40 ms] Building APK
[  +36 ms] Running Gradle task 'assembleDebug'...
[   +8 ms] gradle.properties already sets `android.enableR8`
[  +15 ms] Using gradle from F:\flutter\gallery\android\gradlew.bat.
[  +26 ms] executing: C:\Program Files\Android\Android Studio\jre\bin\java -version
[ +222 ms] Exit code 0 from: C:\Program Files\Android\Android Studio\jre\bin\java -version
[   +2 ms] openjdk version "1.8.0_202-release"
           OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)
           OpenJDK 64-Bit Server VM (build 25.202-b03, mixed mode)
[  +13 ms] executing: [F:\flutter\gallery\android\] F:\flutter\gallery\android\gradlew.bat -Pverbose=true
-Ptarget=F:\flutter\gallery\lib\main.dart -Ptrack-widget-creation=true -Pfilesystem-scheme=org-dartlang-root
-Ptarget-platform=android-x86 assembleDebug
[+5501 ms] > Task :app:compileFlutterBuildDebug
[  +40 ms] [  +40 ms] executing: [C:\flutter\] git -c log.showSignature=false log -n 1 --pretty=format:%H
[   +3 ms] [ +171 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[   +3 ms] [   +3 ms] 9f5ff2306bb3e30b2b98eee79cd231b1336f41f4
[  +11 ms] [        ] executing: [C:\flutter\] git describe --match v*.*.* --first-parent --long --tags
[  +18 ms] [ +112 ms] Exit code 0 from: git describe --match v*.*.* --first-parent --long --tags
[   +4 ms] [        ] v1.12.13+hotfix.7-0-g9f5ff2306
[   +1 ms] [  +52 ms] executing: [C:\flutter\] git rev-parse --abbrev-ref --symbolic @{u}
[   +3 ms] [ +124 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[   +1 ms] [        ] origin/stable
[   +5 ms] [        ] executing: [C:\flutter\] git ls-remote --get-url origin
[  +73 ms] [  +75 ms] Exit code 0 from: git ls-remote --get-url origin
[   +3 ms] [        ] https://github.com/flutter/flutter.git
[ +196 ms] [ +156 ms] executing: [C:\flutter\] git rev-parse --abbrev-ref HEAD
[  +11 ms] [  +61 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[   +2 ms] [        ] stable
[  +85 ms] [  +64 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[   +3 ms] [        ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[   +4 ms] [        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[   +1 ms] [        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[   +6 ms] [        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +1 ms] [  +11 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[   +3 ms] [        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[   +2 ms] [        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[   +4 ms] [        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[   +9 ms] [        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[   +1 ms] [        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[   +4 ms] [        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[ +158 ms] [ +189 ms] Initializing file store
[   +3 ms] [  +28 ms] Done initializing file store
[+2198 ms] [+2126 ms] Skipping target: kernel_snapshot
[   +3 ms] [  +89 ms] debug_android_application: Starting due to {InvalidatedReason.outputMissing}
[ +296 ms] [ +231 ms] debug_android_application: Complete
[   +3 ms] [  +30 ms] Persisting file store
[   +3 ms] [  +27 ms] Done persisting file store
[   +1 ms] [   +5 ms] build succeeded.
[  +91 ms] [  +35 ms] "flutter assemble" took 2,899ms.
[  +99 ms] > Task :app:packLibsflutterBuildDebug UP-TO-DATE
[   +2 ms] > Task :app:preBuild UP-TO-DATE
[   +4 ms] > Task :app:preDebugBuild UP-TO-DATE
[   +1 ms] > Task :app:compileDebugAidl NO-SOURCE
[   +1 ms] > Task :app:checkDebugManifest UP-TO-DATE
[  +19 ms] > Task :app:compileDebugRenderscript NO-SOURCE
[  +71 ms] > Task :app:generateDebugBuildConfig UP-TO-DATE
[   +4 ms] > Task :app:cleanMergeDebugAssets
[   +2 ms] > Task :app:mergeDebugShaders UP-TO-DATE
[   +1 ms] > Task :app:compileDebugShaders UP-TO-DATE
[   +1 ms] > Task :app:generateDebugAssets UP-TO-DATE
[  +89 ms] > Task :app:mergeDebugAssets
[ +302 ms] > Task :app:copyFlutterAssetsDebug
[   +5 ms] > Task :app:mainApkListPersistenceDebug UP-TO-DATE
[   +3 ms] > Task :app:generateDebugResValues UP-TO-DATE
[   +1 ms] > Task :app:generateDebugResources UP-TO-DATE
[ +190 ms] > Task :app:mergeDebugResources UP-TO-DATE
[  +10 ms] > Task :app:createDebugCompatibleScreenManifests UP-TO-DATE
[ +102 ms] > Task :app:processDebugJavaRes NO-SOURCE
[ +101 ms] > Task :app:checkDebugDuplicateClasses FAILED
[  +71 ms] FAILURE: Build failed with an exception.
[  +50 ms] * What went wrong:
[   +1 ms] Execution failed for task ':app:checkDebugDuplicateClasses'.
[   +1 ms] > 1 exception was raised by workers:
[   +1 ms]   java.util.zip.ZipException
[   +4 ms] * Try:
[   +2 ms] Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log
output. Run with --scan to get full insights.
[   +3 ms] * Get more help at https://help.gradle.org
[   +5 ms] BUILD FAILED in 9s
[   +4 ms] 14 actionable tasks: 5 executed, 9 up-to-date
[ +374 ms] Running Gradle task 'assembleDebug'... (completed in 10.6s)
[  +11 ms] "flutter run" took 11,631ms.
Gradle task assembleDebug failed with exit code 1

#0      throwToolExit (package:flutter_tools/src/base/common.dart:28:3)
#1      buildGradleApp (package:flutter_tools/src/android/gradle.dart:387:7)
#2      _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:73:64)
#3      _rootRunUnary (dart:async/zone.dart:1134:38)
#4      _CustomZone.runUnary (dart:async/zone.dart:1031:19)
#5      _FutureListener.handleValue (dart:async/future_impl.dart:139:18)
#6      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:680:45)
#7      Future._propagateToListeners (dart:async/future_impl.dart:709:32)
#8      Future._completeWithValue (dart:async/future_impl.dart:524:5)
#9      _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:32:15)
#10     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:290:13)
#11     _DefaultProcessUtils.stream (package:flutter_tools/src/base/process.dart)
#12     _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:73:64)
#13     _rootRunUnary (dart:async/zone.dart:1134:38)
#14     _CustomZone.runUnary (dart:async/zone.dart:1031:19)
#15     _FutureListener.handleValue (dart:async/future_impl.dart:139:18)
#16     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:680:45)
#17     Future._propagateToListeners (dart:async/future_impl.dart:709:32)
#18     Future._completeWithValue (dart:async/future_impl.dart:524:5)
#19     Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:554:7)
#20     _rootRun (dart:async/zone.dart:1126:13)
#21     _CustomZone.run (dart:async/zone.dart:1023:19)
#22     _CustomZone.runGuarded (dart:async/zone.dart:925:7)
#23     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:965:23)
#24     _microtaskLoop (dart:async/schedule_microtask.dart:43:21)
#25     _startMicrotaskLoop (dart:async/schedule_microtask.dart:52:5)
#26     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
#27     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:175:5)
```
**flutter doctor -v output**
```
[√] Flutter (Channel stable, v1.12.13+hotfix.7, on Microsoft Windows [Version 10.0.17134.1], locale en-US)
    • Flutter version 1.12.13+hotfix.7 at C:\flutter
    • Framework revision 9f5ff2306b (5 days ago), 2020-01-26 22:38:26 -0800
    • Engine revision a67792536c
    • Dart version 2.7.0


[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at C:\Users\M.U.S.E.M.B.I\AppData\Local\Android\Sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = C:\Users\M.U.S.E.M.B.I\AppData\Local\Android\Sdk
    • ANDROID_SDK_ROOT = C:\Users\M.U.S.E.M.B.I\AppData\Local\Android\Sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)
    • All Android licenses accepted.

[√] Android Studio (version 3.5)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 39.0.3
    • Dart plugin version 191.8423
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)

[√] IntelliJ IDEA Community Edition (version 2019.2)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2019.2.3
    • Flutter plugin version 42.2.2
    • Dart plugin version 192.7761

[√] VS Code (version 1.41.1)
    • VS Code at C:\Users\M.U.S.E.M.B.I\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.6.0

[√] Connected device (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 8.1.0 (API 27) (emulator)

• No issues found!
```

**Comment by iapicca** [comment]
Hi @cherlow 
could you please run 
`flutter pub cache repair`
`cd <YOUR APP FOLDER>`
`flutter clean`
If the issue persist please provide your updated `flutter run --verbose`
together with a minimal code sample to reproduce the problem
thank you

**Comment by cherlow** [comment]
i have tried running in a newly created flutter project using `flutter create <project name>`
```
flutter channel stable
flutter upgrade --force
flutter pub cache repair
cd <YOUR APP FOLDER>
flutter clean
```
But i still get an error 

```
[  +12 ms] FAILURE: Build failed with an exception.
[   +5 ms] * What went wrong:
[   +3 ms] Execution failed for task ':app:checkDebugDuplicateClasses'.
[  +16 ms] > 1 exception was raised by workers:
[   +6 ms]   java.util.zip.ZipException
[   +2 ms] * Try:
[   +2 ms] Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log
output. Run with --scan to get full insights.
[   +6 ms] * Get more help at https://help.gradle.org
[   +1 ms] BUILD FAILED in 23s
```

**flutter doctor -v output**

```
[√] Flutter (Channel stable, v1.12.13+hotfix.7, on Microsoft Windows [Version 10.0.17134.1], locale en-US)
    • Flutter version 1.12.13+hotfix.7 at C:\flutter
    • Framework revision 9f5ff2306b (7 days ago), 2020-01-26 22:38:26 -0800
    • Engine revision a67792536c
    • Dart version 2.7.0


[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at C:\Users\M.U.S.E.M.B.I\AppData\Local\Android\Sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = C:\Users\M.U.S.E.M.B.I\AppData\Local\Android\Sdk
    • ANDROID_SDK_ROOT = C:\Users\M.U.S.E.M.B.I\AppData\Local\Android\Sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)
    • All Android licenses accepted.

[√] Android Studio (version 3.5)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 39.0.3
    • Dart plugin version 191.8423
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)

[√] IntelliJ IDEA Community Edition (version 2019.2)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2019.2.3
    • Flutter plugin version 42.2.2
    • Dart plugin version 192.7761

[√] VS Code (version 1.41.1)
    • VS Code at C:\Users\M.U.S.E.M.B.I\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.6.0

[√] Connected device (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 8.1.0 (API 27) (emulator)

• No issues found!



```

**flutter run -v output**


```
[  +32 ms] executing: [C:\flutter\] git -c log.showSignature=false log -n 1 --pretty=format:%H
[ +101 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[   +4 ms] 9f5ff2306bb3e30b2b98eee79cd231b1336f41f4
[   +2 ms] executing: [C:\flutter\] git describe --match v*.*.* --first-parent --long --tags
[  +71 ms] Exit code 0 from: git describe --match v*.*.* --first-parent --long --tags
[   +1 ms] v1.12.13+hotfix.7-0-g9f5ff2306b
[  +12 ms] executing: [C:\flutter\] git rev-parse --abbrev-ref --symbolic @{u}
[  +57 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[   +1 ms] origin/stable
[   +2 ms] executing: [C:\flutter\] git ls-remote --get-url origin
[  +49 ms] Exit code 0 from: git ls-remote --get-url origin
[   +1 ms] https://github.com/flutter/flutter.git
[ +111 ms] executing: [C:\flutter\] git rev-parse --abbrev-ref HEAD
[  +58 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[   +1 ms] stable
[ +170 ms] executing: C:\Users\M.U.S.E.M.B.I\AppData\Local\Android\Sdk\platform-tools\adb.exe devices -l
[  +36 ms] Exit code 0 from: C:\Users\M.U.S.E.M.B.I\AppData\Local\Android\Sdk\platform-tools\adb.exe devices -l
[   +1 ms] List of devices attached
           emulator-5554          device product:sdk_gphone_x86 model:Android_SDK_built_for_x86 device:generic_x86
           transport_id:1
[  +36 ms] C:\Users\M.U.S.E.M.B.I\AppData\Local\Android\Sdk\platform-tools\adb.exe -s emulator-5554 shell getprop
[  +98 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[   +8 ms] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +7 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[   +2 ms] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[ +215 ms] Generating F:\flutter\samp2\android\app\src\main\java\io\flutter\plugins\GeneratedPluginRegistrant.java
[  +42 ms] ro.hardware = ranchu
[  +51 ms] Using hardware rendering with device Android SDK built for x86. If you get graphics artifacts, consider
enabling
           software rendering with "--enable-software-rendering".
[  +25 ms] Launching lib\main.dart on Android SDK built for x86 in debug mode...
[  +24 ms] executing: C:\Users\M.U.S.E.M.B.I\AppData\Local\Android\Sdk\platform-tools\adb.exe -s emulator-5554 shell -x
logcat -v time -s flutter
[  +12 ms] executing: C:\Users\M.U.S.E.M.B.I\AppData\Local\Android\Sdk\platform-tools\adb.exe version
[  +52 ms] Android Debug Bridge version 1.0.41
           Version 29.0.4-5871666
           Installed as C:\Users\M.U.S.E.M.B.I\AppData\Local\Android\Sdk\platform-tools\adb.exe
[   +9 ms] executing: C:\Users\M.U.S.E.M.B.I\AppData\Local\Android\Sdk\platform-tools\adb.exe start-server
[  +70 ms] Building APK
[  +39 ms] Running Gradle task 'assembleDebug'...
[   +8 ms] gradle.properties already sets `android.enableR8`
[  +11 ms] Using gradle from F:\flutter\samp2\android\gradlew.bat.
[  +21 ms] executing: C:\Program Files\Android\Android Studio\jre\bin\java -version
[ +148 ms] Exit code 0 from: C:\Program Files\Android\Android Studio\jre\bin\java -version
[   +1 ms] openjdk version "1.8.0_202-release"
           OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)
           OpenJDK 64-Bit Server VM (build 25.202-b03, mixed mode)
[   +9 ms] executing: [F:\flutter\samp2\android\] F:\flutter\samp2\android\gradlew.bat -Pverbose=true
-Ptarget=F:\flutter\samp2\lib\main.dart -Ptrack-widget-creation=true -Pfilesystem-scheme=org-dartlang-root
-Ptarget-platform=android-x86 assembleDebug
[+4883 ms] > Task :app:compileFlutterBuildDebug
[   +2 ms] [  +46 ms] executing: [C:\flutter\] git -c log.showSignature=false log -n 1 --pretty=format:%H
[   +2 ms] [ +124 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[   +1 ms] [   +1 ms] 9f5ff2306bb3e30b2b98eee79cd231b1336f41f4
[   +1 ms] [        ] executing: [C:\flutter\] git describe --match v*.*.* --first-parent --long --tags
[   +1 ms] [  +69 ms] Exit code 0 from: git describe --match v*.*.* --first-parent --long --tags
[   +3 ms] [        ] v1.12.13+hotfix.7-0-g9f5ff2306b
[   +2 ms] [  +10 ms] executing: [C:\flutter\] git rev-parse --abbrev-ref --symbolic @{u}
[   +1 ms] [  +55 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[   +1 ms] [        ] origin/stable
[   +3 ms] [        ] executing: [C:\flutter\] git ls-remote --get-url origin
[   +1 ms] [  +49 ms] Exit code 0 from: git ls-remote --get-url origin
[   +1 ms] [        ] https://github.com/flutter/flutter.git
[   +1 ms] [ +112 ms] executing: [C:\flutter\] git rev-parse --abbrev-ref HEAD
[   +1 ms] [  +63 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[   +1 ms] [        ] stable
[   +4 ms] [  +35 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[   +1 ms] [        ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[   +3 ms] [        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[   +3 ms] [        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[   +1 ms] [        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +2 ms] [   +6 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[   +1 ms] [        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[   +1 ms] [        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[   +3 ms] [        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[   +1 ms] [        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[   +1 ms] [        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[   +1 ms] [        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[   +2 ms] [ +176 ms] Initializing file store
[   +3 ms] [  +31 ms] kernel_snapshot: Starting due to {}
[   +5 ms] [  +31 ms] C:\flutter\bin\cache\dart-sdk\bin\dart.exe
C:\flutter\bin\cache\artifacts\engine\windows-x64\frontend_server.dart.snapshot --sdk-root
C:\flutter\bin\cache\artifacts\engine\common\flutter_patched_sdk/ --target=flutter
-Ddart.developer.causal_async_stacks=true -Ddart.vm.profile=false -Ddart.vm.product=false
--bytecode-options=source-positions,local-var-info,debugger-stops,instance-field-initializers,keep-unreachable-code,avoi
d-closure-call-instructions --enable-asserts --track-widget-creation --no-link-platform --packages
F:\flutter\samp2\.packages --output-dill
F:\flutter\samp2\.dart_tool\flutter_build\c4bc1c1fefbac57310ffe4b65cceaae2\app.dill --depfile
F:\flutter\samp2\.dart_tool\flutter_build\c4bc1c1fefbac57310ffe4b65cceaae2\kernel_snapshot.d package:samp2/main.dart
[+13008 ms] [+13468 ms] kernel_snapshot: Complete
[+1799 ms] [+1807 ms] debug_android_application: Starting due to {}
[+1599 ms] [+1570 ms] debug_android_application: Complete
[ +400 ms] [ +411 ms] Persisting file store
[   +2 ms] [  +23 ms] Done persisting file store
[   +2 ms] [   +3 ms] build succeeded.
[  +93 ms] [  +25 ms] "flutter assemble" took 17,653ms.
[ +201 ms] > Task :app:packLibsflutterBuildDebug UP-TO-DATE
[   +3 ms] > Task :app:preBuild UP-TO-DATE
[   +2 ms] > Task :app:preDebugBuild UP-TO-DATE
[   +1 ms] > Task :app:compileDebugAidl NO-SOURCE
[   +2 ms] > Task :app:checkDebugManifest
[   +4 ms] > Task :app:compileDebugRenderscript NO-SOURCE
[  +37 ms] > Task :app:generateDebugBuildConfig
[  +55 ms] > Task :app:cleanMergeDebugAssets
[   +7 ms] > Task :app:mergeDebugShaders UP-TO-DATE
[   +1 ms] > Task :app:compileDebugShaders UP-TO-DATE
[   +1 ms] > Task :app:generateDebugAssets UP-TO-DATE
[   +1 ms] > Task :app:mergeDebugAssets
[ +376 ms] > Task :app:copyFlutterAssetsDebug
[   +2 ms] > Task :app:mainApkListPersistenceDebug
[   +2 ms] > Task :app:generateDebugResValues
[   +1 ms] > Task :app:generateDebugResources
[+1511 ms] > Task :app:createDebugCompatibleScreenManifests
[ +289 ms] > Task :app:processDebugManifest
[  +87 ms] > Task :app:processDebugJavaRes NO-SOURCE
[ +506 ms] > Task :app:checkDebugDuplicateClasses FAILED
[ +210 ms] > Task :app:mergeDebugResources
[  +98 ms] FAILURE: Build failed with an exception.
[  +12 ms] * What went wrong:
[   +1 ms] Execution failed for task ':app:checkDebugDuplicateClasses'.
[   +5 ms] > 1 exception was raised by workers:
[   +5 ms]   java.util.zip.ZipException
[  +79 ms] * Try:
[   +6 ms] Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log
output. Run with --scan to get full insights.
[   +2 ms] * Get more help at https://help.gradle.org
[   +1 ms] BUILD FAILED in 25s
[   +1 ms] 15 actionable tasks: 12 executed, 3 up-to-date
[ +370 ms] Running Gradle task 'assembleDebug'... (completed in 25.9s)
[   +9 ms] "flutter run" took 26,952ms.
Gradle task assembleDebug failed with exit code 1

#0      throwToolExit (package:flutter_tools/src/base/common.dart:28:3)
#1      buildGradleApp (package:flutter_tools/src/android/gradle.dart:387:7)
#2      _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:73:64)
#3      _rootRunUnary (dart:async/zone.dart:1134:38)
#4      _CustomZone.runUnary (dart:async/zone.dart:1031:19)
#5      _FutureListener.handleValue (dart:async/future_impl.dart:139:18)
#6      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:680:45)
#7      Future._propagateToListeners (dart:async/future_impl.dart:709:32)
#8      Future._completeWithValue (dart:async/future_impl.dart:524:5)
#9      _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:32:15)
#10     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:290:13)
#11     _DefaultProcessUtils.stream (package:flutter_tools/src/base/process.dart)
#12     _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:73:64)
#13     _rootRunUnary (dart:async/zone.dart:1134:38)
#14     _CustomZone.runUnary (dart:async/zone.dart:1031:19)
#15     _FutureListener.handleValue (dart:async/future_impl.dart:139:18)
#16     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:680:45)
#17     Future._propagateToListeners (dart:async/future_impl.dart:709:32)
#18     Future._completeWithValue (dart:async/future_impl.dart:524:5)
#19     Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:554:7)
#20     _rootRun (dart:async/zone.dart:1126:13)
#21     _CustomZone.run (dart:async/zone.dart:1023:19)
#22     _CustomZone.runGuarded (dart:async/zone.dart:925:7)
#23     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:965:23)
#24     _microtaskLoop (dart:async/schedule_microtask.dart:43:21)
#25     _startMicrotaskLoop (dart:async/schedule_microtask.dart:52:5)
#26     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
#27     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:175:5)
```

**Comment by VladyslavBondarenko** [comment]
Hi @cherlow 
Did you try this workaround? https://github.com/flutter/flutter/issues/48159#issuecomment-571513079

**Comment by cherlow** [comment]
I couldn't figure out how, but i switched from windows to linux and everything works fine...am closing this issue
