### ISSUE TITLE
Cannot run in Release mode

### ISSUE THREAD

**Issue by Symnatic** [flutter/flutter#49942]
```console
[√] Flutter (Channel stable, v1.12.13+hotfix.5, on Microsoft Windows [Version 10.0.18363.592], locale de-DE)

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[√] Android Studio (version 3.5)
[!] IntelliJ IDEA Community Edition (version 2017.2)
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
[√] VS Code (version 1.41.1)
[√] Connected device (2 available)

! Doctor found issues in 1 category.

```
**Error Log**
https://pastebin.com/xD2d0f0P

**Problem:**
Debug mode works fine but Release mode not.. when i try to fix it with the given options (--stacktrace/--info) there is a error that the options dont exist

**Comment by iapicca** [comment]
Hi @Symnatic 
are you encountering the issue you described
running the same app referenced in this [issue](https://github.com/flutter/flutter/issues/49941)?
thank you

**Comment by Symnatic** [comment]
Yes

**Comment by Symnatic** [comment]
But i had the same problem also in an other project

**Comment by iapicca** [comment]
Hi @Symnatic 
could you please run 
`flutter channel stable`
`flutter upgrade --force`
`flutter pub cache repair`
`cd <YOUR APP FOLDER>`
`flutter clean`
If the issue persist please provide your updated 
`flutter doctor -v` and `flutter run --release --verbose`
together with a minimal code sample to reproduce the problem
thank you

**Comment by Symnatic** [comment]
[runrelease.txt](https://github.com/flutter/flutter/files/4153266/runrelease.txt)
[doctorverbose.txt](https://github.com/flutter/flutter/files/4153267/doctorverbose.txt)

**Comment by iapicca** [comment]
```bash
[   +2 ms] FAILURE: Build failed with an exception.
[   +5 ms] * What went wrong:
[        ] Execution failed for task ':vibrate:verifyReleaseResources'.
[   +1 ms] > A failure occurred while executing com.android.build.gradle.internal.tasks.Workers$ActionFacade
[   +2 ms]    > Android resource linking failed
[   +1 ms]
C:\Users\besitzer\.gradle\caches\transforms-2\files-2.1\6a7ce534a9c5473feac5b076aff7f4c5\core-1.0.0\res\values\values.xm
l:57:5-88:25: AAPT: error: resource android:attr/fontStyle not found.
[   +2 ms]
C:\Users\besitzer\.gradle\caches\transforms-2\files-2.1\6a7ce534a9c5473feac5b076aff7f4c5\core-1.0.0\res\values\values.xm
l:57:5-88:25: AAPT: error: resource android:attr/font not found.
[   +2 ms]
C:\Users\besitzer\.gradle\caches\transforms-2\files-2.1\6a7ce534a9c5473feac5b076aff7f4c5\core-1.0.0\res\values\values.xm
l:57:5-88:25: AAPT: error: resource android:attr/fontWeight not found.
[   +5 ms]
C:\Users\besitzer\.gradle\caches\transforms-2\files-2.1\6a7ce534a9c5473feac5b076aff7f4c5\core-1.0.0\res\values\values.xm
l:57:5-88:25: AAPT: error: resource android:attr/fontVariationSettings not found.
[   +2 ms]
C:\Users\besitzer\.gradle\caches\transforms-2\files-2.1\6a7ce534a9c5473feac5b076aff7f4c5\core-1.0.0\res\values\values.xm
l:57:5-88:25: AAPT: error: resource android:attr/ttcIndex not found.
[   +1 ms] * Try:
[   +1 ms] Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log
output. Run with --scan to get full insights.
[   +2 ms] * Get more help at https://help.gradle.org
[   +1 ms] BUILD FAILED in 27s
[   +1 ms] 483 actionable tasks: 7 executed, 476 up-to-date
[ +405 ms] Running Gradle task 'assembleRelease'... (completed in 28,3s)
[   +3 ms] The built failed likely due to AndroidX incompatibilities in a plugin. The tool is about to try using Jetfier
to solve
           the incompatibility.
[   +6 ms] Building plugin cloud_firestore...
[  +11 ms] Running Gradle task 'assembleAarRelease'...
[   +5 ms] "flutter run" took 29.543ms.
The plugin cloud_firestore could not be built due to the issue above.

#0      throwToolExit (package:flutter_tools/src/base/common.dart:28:3)
#1      buildPluginsAsAar (package:flutter_tools/src/android/gradle.dart:726:7)
#2      _asyncErrorWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:80:45)
#3      _rootRunBinary (dart:async/zone.dart:1146:38)
#4      _CustomZone.runBinary (dart:async/zone.dart:1039:19)
#5      _FutureListener.handleError (dart:async/future_impl.dart:153:20)
#6      Future._propagateToListeners.handleError (dart:async/future_impl.dart:692:47)
#7      Future._propagateToListeners (dart:async/future_impl.dart:713:24)
#8      Future._completeError (dart:async/future_impl.dart:532:5)
#9      Future._asyncCompleteError.<anonymous closure> (dart:async/future_impl.dart:580:7)
#10     _rootRun (dart:async/zone.dart:1126:13)
#11     _CustomZone.run (dart:async/zone.dart:1023:19)
#12     _CustomZone.runGuarded (dart:async/zone.dart:925:7)
#13     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:965:23)
#14     _microtaskLoop (dart:async/schedule_microtask.dart:43:21)
#15     _startMicrotaskLoop (dart:async/schedule_microtask.dart:52:5)
#16     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
#17     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:175:5)
```

Hi again @Symnatic 
it seems like your app is not using `androidx`,
although it set by default in apps created w/ `v1.12` and above
did you update an old app?
You might want follow the [docs](https://flutter.dev/docs/development/androidx-migration) to migrate to `androidx`.
Let me know if this solution solves the issue
Thank you

**Comment by Symnatic** [comment]
I created the project only a few days (maybe one or two weeks) ago but i will try to migrate it

**Comment by Symnatic** [comment]
Okay nevermind, there happens nothing if i do refactor>migrate to anroidx -> http://prntscr.com/qxdmus 

but as you can see in the screen there are also already the lines in the gradle.properties which say that the project uses androidx (they were already there before i tried to migrate it)

**Comment by VladyslavBondarenko** [comment]
@Symnatic 
Good, if solved, then I'm closing the issue
if you disagree please write in the comments and I will reopen it. 
Thank you

**Comment by Symnatic** [comment]
noo it isnt solved, i just said that i cannot migrate it to anroidx because i have it already which means that the problem still exists

**Comment by iapicca** [comment]
Hi @Symnatic 
that's odd, new apps created w/ 1.12.13 (unless specified otherwise) are created w/ androidx
are you using `cloud_firestore: ^0.13.0+1`?
thank you

**Comment by Symnatic** [comment]
yes http://prntscr.com/qxz86x
