### ISSUE TITLE
InputDecorator cannot handle null decoration

### ISSUE THREAD

**Issue by soumya92** [flutter/flutter#49980]
## Steps to Reproduce

Add `InputDecorator(child: Container(color: Colors.yellow))` to a layout.

**Expected results:**

No errors. According to [`InputDecorator` documentation for `decoration`](https://api.flutter.dev/flutter/material/InputDecorator/decoration.html):

> If null, const InputDecoration() is used

Given that, and the fact that decoration is not marked `@required`, not specifying `decoration` seems like a supported case.

**Actual results:**

NoSuchMethod Error during rendering.  
Adding `decoration: const InputDecoration()` fixes the problem.

<details>
  <summary>Logs</summary>

```
════════ Exception caught by widgets library ═══════════════════════════════════════════════════════
The following NoSuchMethodError was thrown building Flexible(flex: 2):
The getter 'hasFloatingPlaceholder' was called on null.
Receiver: null
Tried calling: hasFloatingPlaceholder

The relevant error-causing widget was: 
  Flexible file:///...removed.../somefile.dart:129:11
When the exception was thrown, this was the stack: 
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:53:5)
#1      _InputDecoratorState.initState (package:flutter/src/material/input_decorator.dart:1877:33)
#2      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4355:58)
#3      ComponentElement.mount (package:flutter/src/widgets/framework.dart:4201:5)
#4      Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194:14)
...
════════════════════════════════════════════════════════════════════════════════════════════════════
```

```
[✓] Flutter (Channel stable, v1.12.13+hotfix.7, on Mac OS X 10.14.6 18G103, locale en-GB)
    • Flutter version 1.12.13+hotfix.7 at /...removed.../flutter
    • Framework revision 9f5ff2306b (7 days ago), 2020-01-26 22:38:26 -0800
    • Engine revision a67792536c
    • Dart version 2.7.0


[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /...removed.../sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /...removed.../Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✗] Xcode - develop for iOS and macOS
    ✗ Xcode installation is incomplete; a full installation is necessary for iOS development.
      Download at: https://developer.apple.com/xcode/download/
      Or install Xcode via the App Store.
      Once installed, run:
        sudo xcode-select --switch /Applications/Xcode.app/Contents/Developer
        sudo xcodebuild -runFirstLaunch
    ✗ CocoaPods not installed.
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To install:
        sudo gem install cocoapods

[✓] Android Studio (version 3.5)
    • Android Studio at /...removed.../Android Studio.app/Contents
    • Flutter plugin version 43.0.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[!] IntelliJ IDEA Ultimate Edition (version 2019.3.2)
    • IntelliJ at /...removed.../IntelliJ IDEA Ultimate.app
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.dev/intellij-setup/#installing-the-plugins

[✓] Connected device (2 available)
    • ...removed...                     • ...removed... • android-arm64 • Android xx (API xx)
    • Android SDK built for x86 64 • emulator-5554    • android-x64   • Android 10 (API 29) (emulator)
```

</details>

**Comment by VladyslavBondarenko** [comment]
Hi @soumya92 
it's not required in stable (`1.17.5`), but already with beta (current beta is `1.19.0-4.2.pre`) it's required https://master-api.flutter.dev/flutter/material/InputDecorator-class.html
closing since this is not an issue
