### ISSUE TITLE
Error in running "flutter build ios-framework" command in Android Studio on macOS

### ISSUE THREAD

**Issue by msndvlpr** [flutter/flutter#50007]
I have created a Flutter Plugin with Android Studio to make a .aar or .framework library for using in native Android or iOS projects. Actually I have created some dart classes in my project with a few methods but I encountered some problems:

First: when I run "flutter build ios-framework" command in Android Studio on macOS an error with following information occurs:

## command

`flutter build ios-framework`

## exception
```bash
FileSystemException: FileSystemException: Directory listing failed, path = '/Users/maleki/Documents/FlutterSource/flutter_module_pakat/build/ios/framework/Debug/iphoneos/Debug-iphoneos/' (OS Error: No such file or directory, errno = 2)
```

```bash
#0      _Directory._fillWithDirectoryListing (dart:io-patch/directory_patch.dart:39:68)
#1      _Directory.listSync (dart:io/directory_impl.dart:251:5)
#2      ForwardingDirectory.listSync (package:file/src/forwarding/forwarding_directory.dart:45:12)
#3      BuildIOSFrameworkCommand._producePlugins (package:flutter_tools/src/commands/build_ios_framework.dart:390:61)
<asynchronous suspension>
#4      BuildIOSFrameworkCommand.runCommand (package:flutter_tools/src/commands/build_ios_framework.dart:175:15)
<asynchronous suspension>
#5      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:615:18)
#6      _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:73:64)
#7      _rootRunUnary (dart:async/zone.dart:1134:38)
#8      _CustomZone.runUnary (dart:async/zone.dart:1031:19)
#9      _FutureListener.handleValue (dart:async/future_impl.dart:139:18)
#10     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:680:45)
#11     Future._propagateToListeners (dart:async/future_impl.dart:709:32)
#12     Future._completeWithValue (dart:async/future_impl.dart:524:5)
#13     Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:554:7)
#14     _rootRun (dart:async/zone.dart:1126:13)
#15     _CustomZone.run (dart:async/zone.dart:1023:19)
#16     _CustomZone.runGuarded (dart:async/zone.dart:925:7)
#17     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:965:23)
#18     _microtaskLoop (dart:async/schedule_microtask.dart:43:21)
#19     _startMicrotaskLoop (dart:async/schedule_microtask.dart:52:5)
#20     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
#21     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:175:5)
```

## flutter doctor

```console
[32m[✓][39m Flutter (Channel stable, v1.12.13+hotfix.7, on Mac OS X 10.14.6 18G84, locale en-US)
    [32m•[39m Flutter version 1.12.13+hotfix.7 at /Users/maleki/Downloads/flutter
    [32m•[39m Framework revision 9f5ff2306b (7 days ago), 2020-01-26 22:38:26 -0800
    [32m•[39m Engine revision a67792536c
    [32m•[39m Dart version 2.7.0

[33m[!][39m Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    [32m•[39m Android SDK at /Users/maleki/Library/Android/sdk
    [32m•[39m Android NDK location not configured (optional; useful for native profiling support)
    [32m•[39m Platform android-28, build-tools 28.0.3
    [32m•[39m Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    [32m•[39m Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    [33m![39m Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses

[32m[✓][39m Xcode - develop for iOS and macOS (Xcode 11.3)
    [32m•[39m Xcode at /Applications/Xcode.app/Contents/Developer
    [32m•[39m Xcode 11.3, Build version 11C29
    [32m•[39m CocoaPods version 1.7.5

[32m[✓][39m Android Studio (version 3.5)
    [32m•[39m Android Studio at /Applications/Android Studio.app/Contents
    [32m•[39m Flutter plugin version 40.2.2
    [32m•[39m Dart plugin version 191.8593
    [32m•[39m Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[32m[✓][39m Connected device (1 available)
    [32m•[39m iPhone 11 Pro Max • F80AB22B-8B96-4784-A8FA-1E64A9783DB1 • ios • com.apple.CoreSimulator.SimRuntime.iOS-13-3 (simulator)

[33m![39m Doctor found issues in 1 category.
```

Second: when I export .aar library in Android Studio on windows and import it in a native Android project, only native java written classes and methods are accessible not the dart ones.
Please help me.

**Comment by iapicca** [comment]
Hi @msndvlpr 
can you please provide your `flutter build ios-framework --verbose`
thank you

**Comment by iapicca** [comment]
Hi @msndvlpr 
I see there's an open [issue](https://github.com/flutter/flutter/issues/48859) addressing the case you described.
Please follow up on that issue,
I'm closing the current one as duplicate.
If you disagree please write in the comments
and I will reopen it.
Thank you
