### ISSUE TITLE
Flutter Will Not Run Debugging (F5) or Profile Mode in Terminal - iOS Device

### ISSUE THREAD

**Issue by danielgchap** [flutter/flutter#50059]
I attempt the following process in the Terminal:

`flutter run --profile -d (device id) -v
`
with the following output resulting in:

 ```bash
=== BUILD TARGET path_provider OF PROJECT Pods WITH CONFIGURATION Profile ===
           
               Check dependencies
           
           
[   +9 ms] Could not build the precompiled application for the device.
[   +3 ms] Error running application on iPhone (2).
[   +3 ms] "flutter run" took 11,527ms.

#0      throwToolExit (package:flutter_tools/src/base/common.dart:28:3)
#1      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:509:7)
<asynchronous suspension>
#2      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:615:18)
#3      _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:73:64)
#4      _rootRunUnary (dart:async/zone.dart:1134:38)
#5      _CustomZone.runUnary (dart:async/zone.dart:1031:19)
#6      _FutureListener.handleValue (dart:async/future_impl.dart:139:18)
#7      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:680:45)
#8      Future._propagateToListeners (dart:async/future_impl.dart:709:32)
#9      Future._completeWithValue (dart:async/future_impl.dart:524:5)
#10     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:32:15)
#11     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:290:13)
#12     RunCommand.usageValues (package:flutter_tools/src/commands/run.dart)
#13     _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:73:64)
#14     _rootRunUnary (dart:async/zone.dart:1134:38)
#15     _CustomZone.runUnary (dart:async/zone.dart:1031:19)
#16     _FutureListener.handleValue (dart:async/future_impl.dart:139:18)
#17     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:680:45)
#18     Future._propagateToListeners (dart:async/future_impl.dart:709:32)
#19     Future._completeWithValue (dart:async/future_impl.dart:524:5)
#20     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:32:15)
#21     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:290:13)
#22     IosProject.isSwift (package:flutter_tools/src/project.dart)
#23     _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:73:64)
#24     _rootRunUnary (dart:async/zone.dart:1134:38)
#25     _CustomZone.runUnary (dart:async/zone.dart:1031:19)
#26     _FutureListener.handleValue (dart:async/future_impl.dart:139:18)
#27     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:680:45)
#28     Future._propagateToListeners (dart:async/future_impl.dart:709:32)
#29     Future._completeWithValue (dart:async/future_impl.dart:524:5)
#30     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:32:15)
#31     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:290:13)
#32     IosProject.buildSettings (package:flutter_tools/src/project.dart)
#33     _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:73:64)
#34     _rootRunUnary (dart:async/zone.dart:1134:38)
#35     _CustomZone.runUnary (dart:async/zone.dart:1031:19)
#36     _FutureListener.handleValue (dart:async/future_impl.dart:139:18)
#37     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:680:45)
#38     Future._propagateToListeners (dart:async/future_impl.dart:709:32)
#39     Future._completeWithValue (dart:async/future_impl.dart:524:5)
#40     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:32:15)
#41     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:290:13)
#42     XcodeProjectInterpreter.getBuildSettings (package:flutter_tools/src/ios/xcodeproj.dart)
#43     _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:73:64)
#44     _rootRunUnary (dart:async/zone.dart:1134:38)
#45     _CustomZone.runUnary (dart:async/zone.dart:1031:19)
#46     _FutureListener.handleValue (dart:async/future_impl.dart:139:18)
#47     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:680:45)
#48     Future._propagateToListeners (dart:async/future_impl.dart:709:32)
#49     Future._completeWithValue (dart:async/future_impl.dart:524:5)
#50     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:32:15)
#51     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:290:13)
#52     _DefaultProcessUtils.run (package:flutter_tools/src/base/process.dart)
#53     _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:73:64)
#54     _rootRunUnary (dart:async/zone.dart:1134:38)
#55     _CustomZone.runUnary (dart:async/zone.dart:1031:19)
#56     _FutureListener.handleValue (dart:async/future_impl.dart:139:18)
#57     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:680:45)
#58     Future._propagateToListeners (dart:async/future_impl.dart:709:32)
#59     Future._completeWithValue (dart:async/future_impl.dart:524:5)
#60     Future.wait.<anonymous closure> (dart:async/future.dart:400:22)
#61     _rootRunUnary (dart:async/zone.dart:1134:38)
#62     _CustomZone.runUnary (dart:async/zone.dart:1031:19)
#63     _FutureListener.handleValue (dart:async/future_impl.dart:139:18)
#64     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:680:45)
#65     Future._propagateToListeners (dart:async/future_impl.dart:709:32)
#66     Future._complete (dart:async/future_impl.dart:514:7)
#67     _BufferingStreamSubscription.asFuture.<anonymous closure> (dart:async/stream_impl.dart:206:14)
#68     _rootRun (dart:async/zone.dart:1122:38)
#69     _CustomZone.run (dart:async/zone.dart:1023:19)
#70     _CustomZone.runGuarded (dart:async/zone.dart:925:7)
#71     _BufferingStreamSubscription._sendDone.sendDone (dart:async/stream_impl.dart:391:13)
#72     _BufferingStreamSubscription._sendDone (dart:async/stream_impl.dart:401:15)
#73     _BufferingStreamSubscription._close (dart:async/stream_impl.dart:285:7)
#74     _SinkTransformerStreamSubscription._close (dart:async/stream_transformers.dart:98:11)
#75     _EventSinkWrapper.close (dart:async/stream_transformers.dart:25:11)
#76     _StringAdapterSink.close (dart:convert/string_conversion.dart:251:11)
#77     _Utf8ConversionSink.close (dart:convert/string_conversion.dart:302:20)
#78     _ConverterStreamEventSink.close (dart:convert/chunked_conversion.dart:82:18)
#79     _SinkTransformerStreamSubscription._handleDone (dart:async/stream_transformers.dart:143:24)
#80     _rootRun (dart:async/zone.dart:1122:38)
#81     _CustomZone.run (dart:async/zone.dart:1023:19)
#82     _CustomZone.runGuarded (dart:async/zone.dart:925:7)
#83     _BufferingStreamSubscription._sendDone.sendDone (dart:async/stream_impl.dart:391:13)
#84     _BufferingStreamSubscription._sendDone (dart:async/stream_impl.dart:401:15)
#85     _BufferingStreamSubscription._close (dart:async/stream_impl.dart:285:7)
#86     _SyncStreamControllerDispatch._sendDone (dart:async/stream_controller.dart:774:19)
#87     _StreamController._closeUnchecked (dart:async/stream_controller.dart:631:7)
#88     _StreamController.close (dart:async/stream_controller.dart:624:5)
#89     _Socket._onData (dart:io-patch/socket_patch.dart:1838:21)
#90     _rootRunUnary (dart:async/zone.dart:1138:13)
#91     _CustomZone.runUnary (dart:async/zone.dart:1031:19)
#92     _CustomZone.runUnaryGuarded (dart:async/zone.dart:933:7)
#93     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:338:11)
#94     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:265:7)
#95     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:766:19)
#96     _StreamController._add (dart:async/stream_controller.dart:642:7)
#97     _StreamController.add (dart:async/stream_controller.dart:588:5)
#98     new _RawSocket.<anonymous closure> (dart:io-patch/socket_patch.dart:1386:35)
#99     _NativeSocket.issueReadEvent.issue (dart:io-patch/socket_patch.dart:892:18)
#100    _microtaskLoop (dart:async/schedule_microtask.dart:43:21)
#101    _startMicrotaskLoop (dart:async/schedule_microtask.dart:52:5)
#102    _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
#103    _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:175:5)
```

I am trying to get to a stage where I can use DevTools to start investigating some memory pressure issues but I can't even get a Debug session started.

If I hit F5 to run debugging, it just sits on 'Installing and Launching', device just sits on the splash screen, and never moves.

Any suggestions? Thanks!

**Comment by iapicca** [comment]
Hi @danielgchap 
I see you have this issue open
https://github.com/flutter/flutter/issues/50077
please follow up there
thank you
