### ISSUE TITLE
[tool_crash] FileSystemException: Cannot open file, path = 'C:\Users\ARPIT\Desktop\NV main\source\.flutter-plugins' (OS Error: Access is denied., errno = 5)

### ISSUE THREAD

**Issue by arpitpro47** [flutter/flutter#50117]
## Command
  ```
  flutter pub get
  ```

  ## Logs
```console
  FileSystemException: FileSystemException: Cannot open file, path = 'C:\Users\ARPIT\Desktop\NV main\source\.flutter-plugins' (OS Error: Access is denied.
, errno = 5)
```

```bash
  #0      _File.throwIfError (dart:io/file_impl.dart:645:7)
#1      _File.openSync (dart:io/file_impl.dart:489:5)
#2      _File.writeAsBytesSync (dart:io/file_impl.dart:614:31)
#3      _File.writeAsStringSync (dart:io/file_impl.dart:638:5)
#4      ForwardingFile.writeAsStringSync (package:file/src/forwarding/forwarding_file.dart:154:16)
#5      _writeFlutterPluginsList (package:flutter_tools/src/plugins.dart:339:17)
#6      refreshPluginsList (package:flutter_tools/src/plugins.dart:784:24)
#7      FlutterProject.ensureReadyForPlatformSpecificTooling (package:flutter_tools/src/project.dart:210:5)
#8      PackagesGetCommand.runCommand (package:flutter_tools/src/commands/packages.dart:125:23)
<asynchronous suspension>
#9      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:626:18)
#10     _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:75:64)
#11     _rootRunUnary (dart:async/zone.dart:1134:38)
#12     _CustomZone.runUnary (dart:async/zone.dart:1031:19)
#13     _FutureListener.handleValue (dart:async/future_impl.dart:140:18)
#14     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:682:45)
#15     Future._propagateToListeners (dart:async/future_impl.dart:711:32)
#16     Future._completeWithValue (dart:async/future_impl.dart:526:5)
#17     Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:556:7)
#18     _rootRun (dart:async/zone.dart:1126:13)
```

```bash
  [✓] Flutter (Channel beta, v1.13.6, on Microsoft Windows [Version 10.0.18363.592], locale en-US)
    • Flutter version 1.13.6 at C:\src\flutter
    • Framework revision 659dc8129d (5 weeks ago), 2019-12-30 09:24:47 -0800
    • Engine revision bdc9708d23
    • Dart version 2.8.0 (build 2.8.0-dev.0.0 c547f5d933)

[!] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at C:\Users\ARPIT\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: C:\Program Files\Android\Android Studio1\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)
    ✗ Android license status unknown.
      Try re-installing or updating your Android SDK Manager.
      See https://developer.android.com/studio/#downloads or visit https://flutter.dev/setup/#android-setup for detailed instructions.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[!] Android Studio (version 3.1)
    • Android Studio at C:\Program Files\Android\Android Studio
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    ✗ Unable to determine bundled Java version.
    • Try updating or re-installing Android Studio.

[✓] Android Studio (version 3.5)
    • Android Studio at C:\Program Files\Android\Android Studio1
    • Flutter plugin version 42.1.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)

[✓] VS Code (version 1.41.1)
    • VS Code at C:\Users\ARPIT\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.8.0

[✓] Connected device (3 available)
    • SM J701F   • 52005384e28e645b • android-arm    • Android 9 (API 28)
    • Chrome     • chrome           • web-javascript • Google Chrome 79.0.3945.130
    • Web Server • web-server       • web-javascript • Flutter Tools

! Doctor found issues in 2 categories.

  ```

  ## Flutter Application Metadata
  **Version**: 1.4.4+2
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
### Plugins
`cloud_firestoreconnectivitydevice_appsfirebase_analyticsfirebase_authfirebase_corefirebase_messagingfirebase_storageflutter_account_kitflutter_facebook_loginflutter_webview_pluginfluttertoastgoogle_maps_flutterimage_pickerintercom_flutterlocationnotification_permissionspath_providerrate_my_appshareshared_preferencessqfliteuni_linksurl_launchervideo_playerwebview_flutter
  `

**Comment by iapicca** [comment]
HI @arpitpro47 
does this [solution](https://github.com/flutter/flutter/issues/49518#issuecomment-578579010) work for you ?
thank you

**Comment by iapicca** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact descriptions what happens, logs and the output of 'flutter doctor -v'  please.
All system setups can be slightly different so it's always better to open new issues and reference related issues.
