### ISSUE TITLE
Flutter Web: JavaScript history.pushState raises an exception in Release Build.

### ISSUE THREAD

**Issue by gladimdim** [flutter/flutter#50269]
## Steps to Reproduce

1. Clone repo: https://github.com/gladimdim/push_history_bug.

2. Switch to Flutter beta channel & enable web
```
flutter channel beta
flutter upgrade
flutter doctor
flutter config --enable-web
```
3. Run the *debug* mode:
```
flutter run -d chrome
```
It will show an app with the button. Clicking on the button will add 'google.com' at the end of the URL in address bar. js.history.pushState works OK in debug mode.

4. Run the *release* build :
```
flutter run --release -d chrome
```

**Expected results:** the url is updated via js.history.pushState bindings from dart:js.

**Actual results:**: the url is not updated. Exception is thrown in the Chrome console: Another exception was thrown: Instance of 'minified:ar<void>'

<details>
  <summary>Logs</summary>

```
flutter run --verbose -d chrome --release
[  +28 ms] executing: [/Users/i501633/progs/flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[  +48 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[        ] fabeb2a16f1d008ab8230f450c49141d35669798
[        ] executing: [/Users/i501633/progs/flutter/] git describe --match v*.*.* --first-parent --long --tags
[  +39 ms] Exit code 0 from: git describe --match v*.*.* --first-parent --long --tags
[        ] v1.14.6-0-gfabeb2a16
[   +7 ms] executing: [/Users/i501633/progs/flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[  +10 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/beta
[        ] executing: [/Users/i501633/progs/flutter/] git ls-remote --get-url origin
[   +9 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[  +45 ms] executing: [/Users/i501633/progs/flutter/] git rev-parse --abbrev-ref HEAD
[  +11 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] beta
[   +6 ms] executing: sw_vers -productName
[  +16 ms] Exit code 0 from: sw_vers -productName
[        ] Mac OS X
[        ] executing: sw_vers -productVersion
[  +16 ms] Exit code 0 from: sw_vers -productVersion
[        ] 10.15.3
[        ] executing: sw_vers -buildVersion
[  +16 ms] Exit code 0 from: sw_vers -buildVersion
[        ] 19D76
[  +33 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +3 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +36 ms] executing: /Users/i501633/Library/Android/sdk/platform-tools/adb devices -l
[   +7 ms] Exit code 0 from: /Users/i501633/Library/Android/sdk/platform-tools/adb devices -l
[        ] List of devices attached
[  +15 ms] executing: /Users/i501633/progs/flutter/bin/cache/artifacts/libimobiledevice/idevice_id -h
[  +63 ms] executing: /usr/bin/xcode-select --print-path
[   +8 ms] Exit code 0 from: /usr/bin/xcode-select --print-path
[        ] /Applications/Xcode.app/Contents/Developer
[        ] executing: /usr/bin/xcodebuild -version
[ +595 ms] Exit code 0 from: /usr/bin/xcodebuild -version
[   +3 ms] Xcode 11.3.1
           Build version 11C504
[   +4 ms] /usr/bin/xcrun simctl list --json devices
[ +113 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[   +2 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[ +216 ms] Generating /Users/i501633/projects/history_push_error/android/app/src/main/java/io/flutter/plugins/GeneratedPluginRegistrant.java
[ +117 ms] Launching lib/main.dart on Chrome in release mode...
[        ] Building application for the web...
[ +185 ms] Generating /Users/i501633/projects/history_push_error/android/app/src/main/java/io/flutter/plugins/GeneratedPluginRegistrant.java
[   +4 ms] Compiling lib/main.dart for the Web...
[  +13 ms] Initializing file store
[  +10 ms] Done initializing file store
[  +72 ms] invalidated build due to missing files: /Users/i501633/projects/history_push_error/packages/flutter_tools/lib/src/build_system/targets/web.dart
[  +16 ms] web_entrypoint: Starting due to {InvalidatedReason.inputMissing}
[   +2 ms] web_entrypoint: Complete
[+1827 ms] dart2js: Starting due to {InvalidatedReason.inputChanged}
[+17424 ms] dart2js: Complete
[  +66 ms] web_release_bundle: Starting due to {InvalidatedReason.inputChanged}
[  +63 ms] web_release_bundle: Complete
[  +72 ms] web_service_worker: Starting due to {InvalidatedReason.inputChanged}
[  +31 ms] web_service_worker: Complete
[   +2 ms] Persisting file store
[   +5 ms] Done persisting file store
[  +15 ms] Compiling lib/main.dart for the Web... (completed in 19.6s)
[  +13 ms] Building application for the web... (completed in 19.8s)
[ +874 ms] Warning: Flutter's support for web development is not stable yet and hasn't
[        ] been thoroughly tested in production environments.
[        ] For more information see https://flutter.dev/web
[        ] 🔥  To hot restart changes while running, press "r". To hot restart (and refresh the browser), press "R".
[   +2 ms] For a more detailed help message, press "h". To quit, press "q".
```

```
flutter analyze
Analyzing history_push_error...                                         

   info • Avoid using web-only libraries outside Flutter web plugin packages • lib/main.dart:3:1 • avoid_web_libraries_in_flutter

1 issue found. (ran in 8.2s)
```

```
flutter doctor -v
[✓] Flutter (Channel beta, v1.14.6, on Mac OS X 10.15.3 19D76, locale en)
    • Flutter version 1.14.6 at /Users/i501633/progs/flutter
    • Framework revision fabeb2a16f (9 days ago), 2020-01-28 07:56:51 -0800
    • Engine revision c4229bfbba
    • Dart version 2.8.0 (build 2.8.0-dev.5.0 fc3af737c7)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/i501633/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.3.1, Build version 11C504
    • CocoaPods version 1.8.4

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 43.0.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] VS Code (version 1.41.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.8.0

[✓] Connected device (2 available)
    • Chrome     • chrome     • web-javascript • Google Chrome 80.0.3987.87
    • Web Server • web-server • web-javascript • Flutter Tools

• No issues found!
```

</details>

**Comment by yjbanov** [comment]
Can you please run the app in `--profile` mode instead of `--release`, and provide the exception stacktrace?

**Comment by gladimdim** [comment]
@yjbanov ,

I ran 

```
flutter run --profile -d chrome
```

here is a console log from Chrome dev tools:

Uncaught TypeError: Cannot read property '_match' of undefined
    at Object.StackFrame_fromStackTraceLine (stack_frame.dart:103)
    at Object.FlutterError_defaultStackFilter (assertions.dart:681)
    at Object.DiagnosticsStackTrace$ (assertions.dart:780)
    at FlutterErrorDetailsForPointerEventDispatcher.debugFillProperties$1 (assertions.dart:448)
    at _FlutterErrorDetailsNode.get$builder (diagnostics.dart:2900)
    at _FlutterErrorDetailsNode.get$builder (assertions.dart:818)
    at _FlutterErrorDetailsNode.getProperties$0 (diagnostics.dart:2914)
    at TextTreeRenderer.render$4$parentConfiguration$prefixLineOne$prefixOtherLines (diagnostics.dart:1224)
    at TextTreeRenderer.render$1 (diagnostics.dart:1107)
    at Object.FlutterError_dumpErrorToConsole (assertions.dart:648)

**Comment by cyberpwnn** [comment]
Same issue here

```
stack_frame.dart:103 Uncaught TypeError: Cannot read property '_match' of undefined
    at Object.StackFrame_fromStackTraceLine (stack_frame.dart:103)
    at Object.FlutterError_defaultStackFilter (assertions.dart:681)
    at Object.DiagnosticsStackTrace$ (assertions.dart:780)
    at FlutterErrorDetails.debugFillProperties$1 (assertions.dart:448)
    at _FlutterErrorDetailsNode.get$builder (diagnostics.dart:2900)
    at _FlutterErrorDetailsNode.get$builder (assertions.dart:818)
    at _FlutterErrorDetailsNode.getProperties$0 (diagnostics.dart:2914)
    at TextTreeRenderer.render$4$parentConfiguration$prefixLineOne$prefixOtherLines (diagnostics.dart:1224)
    at TextTreeRenderer.render$1 (diagnostics.dart:1107)
    at Object.FlutterError_dumpErrorToConsole (assertions.dart:648)
```

```
Could not load content for https://app.myguide.care/flutter/packages/flutter/lib/src/foundation/stack_frame.dart : HTTP status code: 404
```

Not sure why it's asking for `/flutter/packages/flutter/lib/src/foundation/stack_frame.dart`

**Comment by yjbanov** [comment]
This is a bug in our stack trace parsing logic. I merged a fix a few days back. Can you please try again on the latest master channel and provide the stack trace?

**Comment by gladimdim** [comment]
Hi, @yjbanov ,

I used latest master. 

```
 flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel master, v1.15.4-pre.129, on Mac OS X 10.15.3 19D76, locale en)
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 11.3.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 3.5)
[✓] VS Code (version 1.42.1)
[✓] Connected device (3 available)

• No issues found!
```

Running in profile mode

```
flutter run --profile -d chrome
```
Error stack trace in chrome console:

before push state: http://localhost:49850/#/
js_primitives.dart:49 ══╡ EXCEPTION CAUGHT BY GESTURE ╞═══════════════════════════════════════════════════════════════════
js_primitives.dart:49 The following DomException object was thrown while handling a gesture:
js_primitives.dart:49   DataCloneError: Failed to execute 'pushState' on 'History': function(object) {
js_primitives.dart:49       var testRti;
js_primitives.dart:49       if (object == null)
js_primitives.dart:49         return object;
js_primitives.dart:49       testRti = this;
js_primitives.dart:49   ...<omitted>... } could not be cloned.
js_primitives.dart:49 
js_primitives.dart:49 When the exception was thrown, this was the stack:
js_primitives.dart:49     at JsObject.callMethod$2 (http://localhost:49850/main.dart.js:39910:42)
js_primitives.dart:49     at _UrlChangerState_build_closure.call$0 (http://localhost:49850/main.dart.js:70201:31)
js_primitives.dart:49     at InkWell.onTap$0 (http://localhost:49850/main.dart.js:47716:25)
js_primitives.dart:49     at _InkResponseState._handleTap$1 (http://localhost:49850/main.dart.js:47949:21)
js_primitives.dart:49     at _InkResponseState_build_closure.call$0 (http://localhost:49850/main.dart.js:48066:25)
js_primitives.dart:49     at TapGestureRecognizer.invokeCallback$1$3$debugReport (http://localhost:49850/main.dart.js:45861:27)
js_primitives.dart:49     at TapGestureRecognizer.invokeCallback$2 (http://localhost:49850/main.dart.js:45871:19)
js_primitives.dart:49     at TapGestureRecognizer.handleTapUp$2$down$up (http://localhost:49850/main.dart.js:46213:18)
js_primitives.dart:49     at TapGestureRecognizer._checkUp$0 (http://localhost:49850/main.dart.js:46138:13)
js_primitives.dart:49     at TapGestureRecognizer.handlePrimaryPointer$1 (http://localhost:49850/main.dart.js:46087:15)
js_primitives.dart:49 
js_primitives.dart:49 Handler: "onTap"
js_primitives.dart:49 Recognizer:
js_primitives.dart:49   <optimized out>#a6dcc
js_primitives.dart:49 ════════════════════════════════════════════════════════════════════════════════════════════════════

**Comment by yjbanov** [comment]
/cc @vsmenon @DaveShuckerow is this the RTI problem that you mentioned before? The offending code seems to be this:

```dart
       var href = js.context['location']['href'];
          print('before push state: $href');
          js.context['history']
              .callMethod('pushState', [{}, '', '$href/google.com']);
          print('after pushstate');
          setState(() {
            url = js.context['location']['href'];
          });
```

The error implies we're somehow trying to pass a function as an argument to `pushState`.

**Comment by vsmenon** [comment]
@rakudrama - do you think this is the same rti issue?

**Comment by rakudrama** [comment]
The code
```dart
   js.context['history']
      .callMethod('pushState', [{}, '', '$href/google.com']);
```
is passing a Dart map `{}` to JavaScript and the Dart Map has a type (Rti) which contains function which is not serializable by the HTML Standard StructuredSerializeInternal operation.

The old Rti would have been `[null,null]` which is by serializable by dumb luck. If you had used `<String,dynamic>{}`, or had any interesting data in the map, it would have failed in the old Rti.

The right thing to do is pass something you know is a JavaScript object.

You can use js_utils to convert the map to a JavaScript object:
```dart
   js.context['history']
      .callMethod('pushState', [js.jsify({}), '', '$href/google.com']);
```
or use package:js to declare an anonymous `@JS` class with a constructor, and use 
```dart
@JS()
@anonymous
class EmptyObject {
  external EmptyObject();
}
...
   js.context['history']
      .callMethod('pushState', [EmptyObject(), '', '$href/google.com']);
```

Since some conversion is involved in serializing the 'state' parameter to `pushState` via the somewhat limited HTML Standard StructuredSerializeInternal operation, you might consider taking responsibility for the serialization, e.g. converting the state to a JSON string and parsing the JSON from the `onpopstate` handler. In this case you could pass the pre-converted JSON string since you know it is `'{}'`.

Taking responsibility for the conversion means you could change to a different state representation or serialization, e.g. protocol buffers, or some system of State objects with their own ad-hoc serialization.

**Comment by pedromassangocode** [comment]
Reproducible with the latest master channel.

![Screen Shot 2020-09-24 at 11 49 08](https://user-images.githubusercontent.com/67424416/94135947-15897e00-fe5c-11ea-84fa-098107b82003.png)

<details><summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel master, 1.22.0-10.0.pre.340, on Mac OS X 10.15.6 19G2021 x86_64, locale en)
    • Flutter version 1.22.0-10.0.pre.340 at /Users/pedromassango/dev/SDKs/flutter_master
    • Framework revision 1fef5912cf (6 hours ago), 2020-09-23 21:37:08 -0700
    • Engine revision dd35b5b659
    • Dart version 2.10.0 (build 2.10.0-156.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
    • Android SDK at /Users/pedromassango/Library/Android/sdk
    • Platform android-30, build-tools 30.0.1
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.0, Build version 12A7209
    • CocoaPods version 1.9.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[!] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] IntelliJ IDEA Community Edition (version 2020.2.2)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 49.0.4
    • Dart plugin version 202.7319.5

[✓] VS Code (version 1.48.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.14.1

[✓] Connected device (4 available)
    • sdk gphone x86 arm (mobile) • emulator-5554 • android-x86    • Android 11 (API 30) (emulator)
    • macOS (desktop)             • macos         • darwin-x64     • Mac OS X 10.15.6 19G2021 x86_64
    • Web Server (web)            • web-server    • web-javascript • Flutter Tools
    • Chrome (web)                • chrome        • web-javascript • Google Chrome 85.0.4183.121

! Doctor found issues in 1 category.
Process finished with exit code 0
```
</details>

**Comment by darshankawar** [comment]
Verified this issue using latest versions and observed that the behavior is still replicable.

<img width="1197" alt="Screenshot 2022-11-08 at 4 45 00 PM" src="https://user-images.githubusercontent.com/67046386/200550570-57f79e19-7933-4d4d-94b5-7b72ebda6f9b.png">

<details>
<summary> stable, master flutter doctor -v </summary>

```
[✓] Flutter (Channel stable, 3.3.7, on macOS 12.2.1 21D62 darwin-x64, locale
    en-GB)
    • Flutter version 3.3.7 on channel stable at
      /Users/dhs/documents/fluttersdk/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision e99c9c7cd9 (2 days ago), 2022-11-01 16:59:00 -0700
    • Engine revision 857bd6b74c
    • Dart version 2.18.4
    • DevTools version 2.15.0

[!] Xcode - develop for iOS and macOS (Xcode 12.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    ! Flutter recommends a minimum Xcode version of 13.
      Download the latest version or update via the Mac App Store.
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] VS Code (version 1.62.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.21.0

[✓] Connected device (5 available)
    • SM G975F (mobile)       • RZ8M802WY0X • android-arm64   • Android 11 (API 30)
    • Darshan's iphone (mobile)  • 21150b119064aecc249dfcfe05e259197461ce23 •
      ios            • iOS 14.4.1 18D61
    • iPhone 12 Pro Max (mobile) • A5473606-0213-4FD8-BA16-553433949729     •
      ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-3 (simulator)
    • macOS (desktop)            • macos                                    •
      darwin-x64     • Mac OS X 10.15.4 19E2269 darwin-x64
    • Chrome (web)               • chrome                                   •
      web-javascript • Google Chrome 98.0.4758.80

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.

[!] Flutter (Channel master, 3.5.0-12.0.pre.168, on macOS 12.2.1 21D62
    darwin-x64, locale en-GB)
    • Flutter version 3.5.0-12.0.pre.168 on channel master at
      /Users/dhs/documents/fluttersdk/flutter
    ! Warning: `flutter` on your path resolves to
      /Users/dhs/Documents/Fluttersdk/flutter/bin/flutter, which is not inside
      your current Flutter SDK checkout at
      /Users/dhs/documents/fluttersdk/flutter. Consider adding
      /Users/dhs/documents/fluttersdk/flutter/bin to the front of your path.
    ! Warning: `dart` on your path resolves to
      /Users/dhs/Documents/Fluttersdk/flutter/bin/dart, which is not inside your
      current Flutter SDK checkout at /Users/dhs/documents/fluttersdk/flutter.
      Consider adding /Users/dhs/documents/fluttersdk/flutter/bin to the front
      of your path.
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision a1432a9c5d (4 hours ago), 2022-11-07 19:17:03 -0600
    • Engine revision e7d7edab98
    • Dart version 2.19.0 (build 2.19.0-374.0.dev)
    • DevTools version 2.19.0
    • If those were intentional, you can disregard the above warnings; however
      it is recommended to use "git" directly to perform update checks and
      upgrades.
    
[!] Xcode - develop for iOS and macOS (Xcode 12.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    ! Flutter recommends a minimum Xcode version of 13.
      Download the latest version or update via the Mac App Store.
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] VS Code (version 1.62.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.21.0

[✓] Connected device (5 available)
    • SM G975F (mobile)       • RZ8M802WY0X • android-arm64   • Android 11 (API 30)
    • Darshan's iphone (mobile)  • 21150b119064aecc249dfcfe05e259197461ce23 •
      ios            • iOS 14.4.1 18D61
    • iPhone 12 Pro Max (mobile) • A5473606-0213-4FD8-BA16-553433949729     •
      ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-3 (simulator)
    • macOS (desktop)            • macos                                    •
      darwin-x64     • Mac OS X 10.15.4 19E2269 darwin-x64
    • Chrome (web)               • chrome                                   •
      web-javascript • Google Chrome 98.0.4758.80

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.



```

</details>
