### ISSUE TITLE
Error when handling list in for loop in debug mode, no error in release apk

### ISSUE THREAD

**Issue by lalo-vergel** [flutter/flutter#50279]
Hi. I have a method that takes a List from a provider, uses a for loop that compares it to another list in the same provider, and deletes the strings that exist in both lists from one of them. After this for loop, I see if the list ends up empty, and if so, perform a specific action:

```
// provider.selection is a group of photos selected in the app ui
// provider.album is a list of photo ids, for photos stored in an album

for (var photo in provider.selection['selected']) {
    provider.album['image_list'].remove(photo);
  }
// IF no images are left, delete photo album
if (provider.album['image_list'].isEmpty) {
await provider.deleteAlbum(albumId);
                          }
```
The issue is that I get the following error when trying to perform the operation when in debug mode (using Android Studio, both in android emulator and plugged device):
```
[ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: Concurrent modification during iteration: Instance(length:1) of '_GrowableList'.
```
However, when I build a release .apk and perform the same action, there is no error and everything works great.

In my head it makes no sense that an exception happens in this case because the List used to feed the for loop is not the list being edited inside the loop. But what happens in this case, in debug mode, is that the action occurs for the first item of the loop, and then the exception is thrown. In the release .apk, the loop performs as expected and the action occurs for all items in the list. 

Full error:
```
E/flutter (20488): [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: Concurrent modification during iteration: Instance(length:1) of '_GrowableList'.
E/flutter (20488): #0      ListIterator.moveNext (dart:_internal/iterable.dart:340:7)
E/flutter (20488): #1      groupIntoAlbum (package:my_surgery_local/screens/waiting_room_single.dart:385:46)
E/flutter (20488): #2      _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:73:64)
E/flutter (20488): #3      _rootRunUnary (dart:async/zone.dart:1134:38)
E/flutter (20488): #4      _CustomZone.runUnary (dart:async/zone.dart:1031:19)
E/flutter (20488): #5      _FutureListener.handleValue (dart:async/future_impl.dart:139:18)
E/flutter (20488): #6      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:680:45)
E/flutter (20488): #7      Future._propagateToListeners (dart:async/future_impl.dart:709:32)
E/flutter (20488): #8      Future._completeWithValue (dart:async/future_impl.dart:524:5)
E/flutter (20488): #9      _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:32:15)
E/flutter (20488): #10     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:290:13)
E/flutter (20488): #11     MainProvider.createAlbum (package:my_surgery_local/providers/storage_provider.dart)
E/flutter (20488): #12     _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:73:64)
E/flutter (20488): #13     _rootRunUnary (dart:async/zone.dart:1134:38)
E/flutter (20488): #14     _CustomZone.runUnary (dart:async/zone.dart:1031:19)
E/flutter (20488): #15     _FutureListener.handleValue (dart:async/future_impl.dart:139:18)
E/flutter (20488): #16     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:680:45)
E/flutter (20488): #17     Future._propagateToListeners (dart:async/future_impl.dart:709:32)
E/flutter (20488): #18     Future._completeWithValue (dart:async/future_impl.dart:524:5)
E/flutter (20488): #19     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:32:15)
E/flutter (20488): #20     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:290:13)
E/flutter (20488): #21     BoxImpl._writeFrames (package:hive/src/box/box_impl.dart)
E/flutter (20488): #22     _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:73:64)
E/flutter (20488): #23     _rootRunUnary (dart:async/zone.dart:1134:38)
E/flutter (20488): #24     _CustomZone.runUnary (dart:async/zone.dart:1031:19)
E/flutter (20488): #25     _FutureListener.handleValue (dart:async/future_impl.dart:139:18)
E/flutter (20488): #26     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:680:45)
E/flutter (20488): #27     Future._propagateToListeners (dart:async/future_impl.dart:709:32)
E/flutter (20488): #28     Future._completeWithValue (dart:async/future_impl.dart:524:5)
E/flutter (20488): #29     Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:554:7)
E/flutter (20488): #30     _rootRun (dart:async/zone.dart:1126:13)
E/flutter (20488): #31     _CustomZone.run (dart:async/zone.dart:1023:19)
E/flutter (20488): #32     _CustomZone.runGuarded (dart:async/zone.dart:925:7)
E/flutter (20488): #33     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:965:23)
E/flutter (20488): #34     _microtaskLoop (dart:async/schedule_microtask.dart:43:21)
E/flutter (20488): #35     _startMicrotaskLoop (dart:async/schedule_microtask.dart:52:5)
```

**Comment by lalo-vergel** [comment]
Tested this issue in a different setting, without using the provider package, the same thing happens:
```
List album = ['aaa', 'bbb', 'ccc', 'ddd', 'eee'];
  List selected = ['ccc', 'eee'];
  testListIssue() async {
    for (var photo in selected) {
      selected.remove(photo);
      print('REMOVED $photo');
    }
  }
//
[ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: Concurrent modification during iteration: Instance(length:1) of '_GrowableList'.
```

**Comment by lalo-vergel** [comment]
Also tested in a different setting, without the provider package, same error happens:
```
List album = ['aaa', 'bbb', 'ccc', 'ddd', 'eee'];
List selected = ['ccc', 'eee'];
  testListIssue() async {
    for (var photo in selected) {
      selected.remove(photo);
      print('REMOVED $photo');
    }
  }

// ERROR:
I/flutter ( 8697): REMOVED ccc
E/flutter ( 8697): [ERROR:flutter/shell/common/shell.cc(199)] Dart Error: Unhandled exception:
E/flutter ( 8697): Concurrent modification during iteration: Instance(length:1) of '_GrowableList'.
```
