### ISSUE TITLE
[tool_crash] FileSystemException: Cannot open file, path = 'C:\Users\admin\AppData\Local\Temp\flutter_gradle_wrapper.79eba4ea-497d-11ea-8935-fcaa141ecdaa\gradle\wrapper\gradle-wrapper.jar' (OS Error: Access is denied., errno = 5)

### ISSUE THREAD

**Issue by GAM3RG33K** [flutter/flutter#50321]
## Command
```console
flutter --no-color precache
```

## Logs
```bash
FileSystemException: FileSystemException: Cannot open file, path = 'C:\Users\admin\AppData\Local\Temp\flutter_gradle_wrapper.79eba4ea-497d-11ea-8935-fcaa141ecdaa\gradle\wrapper\gradle-wrapper.jar' (OS Error: Access is denied.
, errno = 5)
```

```bash
#0      _File.throwIfError (dart:io/file_impl.dart:645:7)
#1      _File.openSync (dart:io/file_impl.dart:489:5)
#2      _File.writeAsBytesSync (dart:io/file_impl.dart:614:31)
#3      ForwardingFile.writeAsBytesSync (package:file/src/forwarding/forwarding_file.dart:131:16)
#4      copyDirectorySync (package:flutter_tools/src/base/file_system.dart:52:15)
#5      copyDirectorySync (package:flutter_tools/src/base/file_system.dart:55:7)
#6      copyDirectorySync (package:flutter_tools/src/base/file_system.dart:55:7)
#7      GradleUtils.injectGradleWrapperIfNeeded (package:flutter_tools/src/android/gradle_utils.dart:101:5)
#8      AndroidMavenArtifacts.update (package:flutter_tools/src/cache.dart:906:17)
#9      Cache.updateAll (package:flutter_tools/src/cache.dart:390:24)
#10     PrecacheCommand.runCommand (package:flutter_tools/src/commands/precache.dart:87:27)
#11     FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:625:18)
<asynchronous suspension>
#12     FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:521:33)
<asynchronous suspension>
#13     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:29)
#14     _rootRun (dart:async/zone.dart:1126:13)
#15     _CustomZone.run (dart:async/zone.dart:1023:19)
#16     _runZoned (dart:async/zone.dart:1518:10)
#17     runZoned (dart:async/zone.dart:1465:12)
```

```console
[✓] Flutter (Channel unknown, v1.13.9, on Microsoft Windows [Version 6.1.7601], locale en-US)
    • Flutter version 1.13.9 at C:\SDK\FlutterSDK\flutter
    • Framework revision d291de086c (4 weeks ago), 2020-01-09 10:25:58 -0800
    • Engine revision f001ea29f1
    • Dart version 2.8.0 (build 2.8.0-dev.0.0 c0ca187f26)

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at C:\SDK\Android_SDK
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • ANDROID_HOME = C:\SDK\Android_SDK
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[✓] Android Studio (version 3.5)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 43.0.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)

[✓] VS Code (version 1.41.1)
    • VS Code at C:\Users\admin\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.8.0

[✓] Connected device (2 available)
    • Chrome     • chrome     • web-javascript • Google Chrome 79.0.3945.130
    • Web Server • web-server • web-javascript • Flutter Tools

• No issues found!

```

## Flutter Application Metadata
No pubspec in working directory.

**Comment by iapicca** [comment]
Hi @GAM3RG33K 
I see there's an open [issue](https://github.com/flutter/flutter/issues/50117) addressing the case you described.
Please follow up on that issue,
I'm closing the current one as duplicate.
If you disagree please write in the comments
and I will reopen it.
Thank you
