### ISSUE TITLE
Unable to start flutter due to security on macos Catalina

### ISSUE THREAD

**Issue by tomasbaran** [flutter/flutter#50334]
Flutter crash report; please file at https://github.com/flutter/flutter/issues.

## command

flutter --version

## exception

VersionCheckError: VersionCheckError: Command exited with code 69: git -c log.showSignature=false log -n 1 --pretty=format:%ad --date=iso
Standard error: 

Agreeing to the Xcode/iOS license requires admin privileges, please run “sudo xcodebuild -license” and then retry this command.

```
#0      _runSync (package:flutter_tools/src/version.dart:543:5)
#1      FlutterVersion._latestGitCommitDate (package:flutter_tools/src/version.dart:143:12)
#2      FlutterVersion.frameworkCommitDate (package:flutter_tools/src/version.dart:133:37)
#3      FlutterVersion.toString (package:flutter_tools/src/version.dart:110:99)
#4      FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:404:46)
<asynchronous suspension>
#5      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:146:29)
#6      _rootRun (dart:async/zone.dart:1126:13)
#7      _CustomZone.run (dart:async/zone.dart:1023:19)
#8      _runZoned (dart:async/zone.dart:1518:10)
#9      runZoned (dart:async/zone.dart:1465:12)
#10     AppContext.run (package:flutter_tools/src/base/context.dart:145:18)
#11     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:364:19)
#12     CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:112:25)
#13     new Future.sync (dart:async/future.dart:224:31)
#14     CommandRunner.run (package:args/command_runner.dart:112:14)
#15     FlutterCommandRunner.run (package:flutter_tools/src/runner/flutter_command_runner.dart:250:18)
#16     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:63:22)
#17     _rootRun (dart:async/zone.dart:1126:13)
#18     _CustomZone.run (dart:async/zone.dart:1023:19)
#19     _runZoned (dart:async/zone.dart:1518:10)
#20     runZoned (dart:async/zone.dart:1502:12)
#21     run.<anonymous closure> (package:flutter_tools/runner.dart:61:18)
<asynchronous suspension>
#22     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:146:29)
#23     _rootRun (dart:async/zone.dart:1126:13)
#24     _CustomZone.run (dart:async/zone.dart:1023:19)
#25     _runZoned (dart:async/zone.dart:1518:10)
#26     runZoned (dart:async/zone.dart:1465:12)
#27     AppContext.run (package:flutter_tools/src/base/context.dart:145:18)
#28     runInContext (package:flutter_tools/src/context_runner.dart:64:24)
#29     run (package:flutter_tools/runner.dart:50:10)
#30     main (package:flutter_tools/executable.dart:65:9)
#31     main (file:///Users/tomas/Developer/flutter/packages/flutter_tools/bin/flutter_tools.dart:8:3)
#32     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:305:32)
#33     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:174:12)
```

## flutter doctor

```
[33m[!][39m Flutter (Channel unknown, v0.0.0-unknown, on Mac OS X 10.15.3 19D76, locale
    es-ES)
    [32m•[39m Flutter version 0.0.0-unknown at /Users/tomas/Developer/flutter
    [31m✗[39m Command exited with code 69: git -c log.showSignature=false log -n 1
      --pretty=format:%ad --date=iso
      Standard error: 

      Agreeing to the Xcode/iOS license requires admin privileges, please run
      “sudo xcodebuild -license” and then retry this command.




[31m[✗][39m Android toolchain - develop for Android devices
    [31m✗[39m Unable to locate Android SDK.
      Install Android Studio from:
      https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK
      components.
      (or visit https://flutter.dev/setup/#android-setup for detailed
      instructions).
      If the Android SDK has been installed to a custom location, set
      ANDROID_HOME to that location.
      You may also want to add it to your PATH environment variable.


[33m[!][39m Xcode - develop for iOS and macOS (Xcode 11.3.1)
    [32m•[39m Xcode at /Applications/Xcode.app/Contents/Developer
    [32m•[39m Xcode 11.3.1, Build version 11C504
    [31m✗[39m Xcode end user license agreement not signed; open Xcode or run the command
      'sudo xcodebuild -license'.
    [31m✗[39m Xcode requires additional components to be installed in order to run.
      Launch Xcode and install additional required components when prompted or
      run:
        sudo xcodebuild -runFirstLaunch
    [31m✗[39m CocoaPods not installed.
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin
        code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To install:
        sudo gem install cocoapods

[33m[!][39m Android Studio (version 3.5)
    [32m•[39m Android Studio at /Applications/Android Studio.app/Contents
    [31m✗[39m Flutter plugin not installed; this adds Flutter specific functionality.
    [31m✗[39m Dart plugin not installed; this adds Dart specific functionality.
    [32m•[39m Java version OpenJDK Runtime Environment (build
      1.8.0_202-release-1483-b49-5587405)

[33m[!][39m Connected device
    [33m![39m No devices available

[33m![39m Doctor found issues in 5 categories.
```

**Comment by VladyslavBondarenko** [comment]
Hi @tomasbaran 
Have you run this proposed command `sudo xcodebuild -license`?

**Comment by tomasbaran** [comment]
Thanks @VladyslavBondarenko. Nope, I didn't. but I did sudo flutter doctor --android-licenses. Maybe that helped, too.

I solved it by running this command: flutter doctor and fixing everything it needed.
