### ISSUE TITLE
AssertionError hot reloading completed 'Image.network'

### ISSUE THREAD

**Issue by zacps** [flutter/flutter#50391]
In my application I have a widget that looks like this:

```dart
class HutCard extends StatelessWidget {
  final Hut hut;

  const HutCard({Key key, this.hut}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return SizedBox(
      width: double.infinity,
      child: ListTile(
        leading: FutureBuilder(
          future: hut.detail,
          builder: (context, snapshot) => snapshot.hasData
              ? Image.network(
                  (snapshot.data).introductionThumbnail,
                  width: 220,
                  height: 140,
                )
              : CircularProgressIndicator(),
        ),
        title: Text(hut.name),
        contentPadding: EdgeInsets.all(8.0),
      ),
    );
  }
}
```

On hot reloading an assertion fails:
https://github.com/flutter/flutter/blob/169529c37064568a17b634968c73a7ff79029dfb/packages/flutter/lib/src/painting/image_stream.dart#L233

Commenting the assertion fixes the problem, and I haven't observed any adverse behaviour, but I also haven't spent enough time reading the code to know why it was there in the first place.

I attempted to create a minimal reproduction case, but wasn't able to replicate it with the code below. If I have some time I'll make another attempt at narrowing down the problem, suggestions for what might be happening are welcome.

```dart
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter network image repro',
      home: FutureBuilder(
        future: Future.delayed(
            Duration(seconds: 5),
            () =>
                'https://www.doc.govt.nz/thumbs/large/link/de41667cfe3d400c9327cf318609e81c.aspx'),
        builder: (context, snapshot) => snapshot.hasData
            ? Image.network(
                snapshot.data,
              )
            : CircularProgressIndicator(),
      ),
    );
  }
}
```

<details>
  <summary>Call stack</summary>

```
_AssertionError._doThrowNew (dart:core-patch/errors_patch.dart:42)
_AssertionError._throwNew (dart:core-patch/errors_patch.dart:38)
ImageStream.setCompleter (c:\tools\flutter\packages\flutter\lib\src\painting\image_stream.dart:230)
ImageProvider._createErrorHandlerAndKey.handleError (c:\tools\flutter\packages\flutter\lib\src\painting\image_provider.dart:347)
<asynchronous gap> (Unknown Source:0)
_Closure.call (dart:core-patch/function.dart:0)
ImageProvider._createErrorHandlerAndKey.<anonymous closure>.<anonymous closure> (c:\tools\flutter\packages\flutter\lib\src\painting\image_provider.dart:389)
SynchronousFuture.then (c:\tools\flutter\packages\flutter\lib\src\foundation\synchronous_future.dart:41)
ImageProvider._createErrorHandlerAndKey.<anonymous closure> (c:\tools\flutter\packages\flutter\lib\src\painting\image_provider.dart:384)
_rootRun (dart:async/zone.dart:1126)
_rootRun (dart:async/zone.dart:0)
_CustomZone.run (dart:async/zone.dart:1023)
_CustomZone.runGuarded (dart:async/zone.dart:925)
ImageProvider._createErrorHandlerAndKey (c:\tools\flutter\packages\flutter\lib\src\painting\image_provider.dart:376)
ImageProvider.resolve (c:\tools\flutter\packages\flutter\lib\src\painting\image_provider.dart:321)
_ImageState._resolveImage (c:\tools\flutter\packages\flutter\lib\src\widgets\image.dart:1019)
_ImageState.reassemble (c:\tools\flutter\packages\flutter\lib\src\widgets\image.dart:1004)
StatefulElement.reassemble (c:\tools\flutter\packages\flutter\lib\src\widgets\framework.dart:4607)
Element.reassemble.<anonymous closure> (c:\tools\flutter\packages\flutter\lib\src\widgets\framework.dart:2974)
_Closure.call (dart:core-patch/function.dart:0)
ComponentElement.visitChildren (c:\tools\flutter\packages\flutter\lib\src\widgets\framework.dart:4526)
Element.reassemble (c:\tools\flutter\packages\flutter\lib\src\widgets\framework.dart:2973)
StatefulElement.reassemble (c:\tools\flutter\packages\flutter\lib\src\widgets\framework.dart:4608)
Element.reassemble.<anonymous closure> (c:\tools\flutter\packages\flutter\lib\src\widgets\framework.dart:2974)
_Closure.call (dart:core-patch/function.dart:0)
ComponentElement.visitChildren (c:\tools\flutter\packages\flutter\lib\src\widgets\framework.dart:4526)
Element.reassemble (c:\tools\flutter\packages\flutter\lib\src\widgets\framework.dart:2973)
Element.reassemble.<anonymous closure> (c:\tools\flutter\packages\flutter\lib\src\widgets\framework.dart:2974)
_Closure.call (dart:core-patch/function.dart:0)
ComponentElement.visitChildren (c:\tools\flutter\packages\flutter\lib\src\widgets\framework.dart:4526)
Element.reassemble (c:\tools\flutter\packages\flutter\lib\src\widgets\framework.dart:2973)
Element.reassemble.<anonymous closure> (c:\tools\flutter\packages\flutter\lib\src\widgets\framework.dart:2974)
Iterable.forEach (dart:core/iterable.dart:279)
_ListTileElement.visitChildren (c:\tools\flutter\packages\flutter\lib\src\material\list_tile.dart:985)
Element.reassemble (c:\tools\flutter\packages\flutter\lib\src\widgets\framework.dart:2973)
Element.reassemble.<anonymous closure> (c:\tools\flutter\packages\flutter\lib\src\widgets\framework.dart:2974)
_Closure.call (dart:core-patch/function.dart:0)
ComponentElement.visitChildren (c:\tools\flutter\packages\flutter\lib\src\widgets\framework.dart:4526)
Element.reassemble (c:\tools\flutter\packages\flutter\lib\src\widgets\framework.dart:2973)
Element.reassemble.<anonymous closure> (c:\tools\flutter\packages\flutter\lib\src\widgets\framework.dart:2974)
_Closure.call (dart:core-patch/function.dart:0)
SingleChildRenderObjectElement.visitChildren (c:\tools\flutter\packages\flutter\lib\src\widgets\framework.dart:5730)
Element.reassemble (c:\tools\flutter\packages\flutter\lib\src\widgets\framework.dart:2973)
Element.reassemble.<anonymous closure> (c:\tools\flutter\packages\flutter\lib\src\widgets\framework.dart:2974)
_Closure.call (dart:core-patch/function.dart:0)
ComponentElement.visitChildren (c:\tools\flutter\packages\flutter\lib\src\widgets\framework.dart:4526)
Element.reassemble (c:\tools\flutter\packages\flutter\lib\src\widgets\framework.dart:2973)
Element.reassemble.<anonymous closure> (c:\tools\flutter\packages\flutter\lib\src\widgets\framework.dart:2974)
_Closure.call (dart:core-patch/function.dart:0)
SingleChildRenderObjectElement.visitChildren (c:\tools\flutter\packages\flutter\lib\src\widgets\framework.dart:5730)
Element.reassemble (c:\tools\flutter\packages\flutter\lib\src\widgets\framework.dart:2973)
Element.reassemble.<anonymous closure> (c:\tools\flutter\packages\flutter\lib\src\widgets\framework.dart:2974)
_Closure.call (dart:core-patch/function.dart:0)
SingleChildRenderObjectElement.visitChildren (c:\tools\flutter\packages\flutter\lib\src\widgets\framework.dart:5730)
Element.reassemble (c:\tools\flutter\packages\flutter\lib\src\widgets\framework.dart:2973)
Element.reassemble.<anonymous closure> (c:\tools\flutter\packages\flutter\lib\src\widgets\framework.dart:2974)
_Closure.call (dart:core-patch/function.dart:0)
ComponentElement.visitChildren (c:\tools\flutter\packages\flutter\lib\src\widgets\framework.dart:4526)
Element.reassemble (c:\tools\flutter\packages\flutter\lib\src\widgets\framework.dart:2973)
```

</details>

<details>
  <summary><code>flutter doctor -v</code></summary>

```
[√] Flutter (Channel master, v1.14.7-pre.78, on Microsoft Windows [Version 10.0.18362.592], locale en-NZ)
    • Flutter version 1.14.7-pre.78 at C:\tools\flutter
    • Framework revision 306c23fd36 (7 days ago), 2020-02-01 00:38:02 +0100
    • Engine revision 6b8c150639
    • Dart version 2.8.0 (build 2.8.0-dev.6.0 162d6c5634)


[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at C:\Users\Zac\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 28.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b02)
    • All Android licenses accepted.

[√] Android Studio (version 3.1)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 28.0.1
    • Dart plugin version 173.4700
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b02)

[√] VS Code, 64-bit edition (version 1.41.1)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Flutter extension version 3.8.1

[√] Connected device (1 available)
    • ONEPLUS A6000 • a21aff4f • android-arm64 • Android 10 (API 29)
```

</p></details>

**Comment by iapicca** [comment]
Hi @zacps 
would be helpful to know  what `introductionThumbnail` do?
thank you

**Comment by dnfield** [comment]
This appears to be happening when some error occurs when making the key.

**Comment by dnfield** [comment]
I've tried a few things that I thought might recreate this but I'm not able to.

The bug is that we shouldn't be trying to set the completer twice - it seems like this is happening where the completer gets set once fine, and then in an error handler tries to set it again to the error compelter and fails.

**Comment by dnfield** [comment]
@zacps if you're ever able to reproduce this, could you please add something like `print(exception); print(stackTrace)` before line 347 on image_provider.dart?  That should give some indication of how to recreate this.

**Comment by zacps** [comment]
I can reproduce it reliably with my real app, but haven't found a minimal case.

It now raises an exception without a reload.

```dart
I/flutter (18137): [image_provider] Exception: 'package:flutter/src/painting/image_stream.dart': Failed assertion: line 230 pos 12: '_completer == null': is not true.
I/flutter (18137): [image_provider] Stack: #0      _AssertionError._doThrowNew  (dart:core-patch/errors_patch.dart:42:39)
I/flutter (18137): #1      _AssertionError._throwNew  (dart:core-patch/errors_patch.dart:38:5)
I/flutter (18137): #2      ImageStream.setCompleter 
package:flutter/…/painting/image_stream.dart:230
I/flutter (18137): #3      ImageProvider.resolveStreamForKey 
package:flutter/…/painting/image_provider.dart:420
I/flutter (18137): #4      ScrollAwareImageProvider.resolveStreamForKey 
package:flutter/…/widgets/scroll_aware_image_provider.dart:101
I/flutter (18137): #5      ImageProvider._createErrorHandlerAndKey.<anonymous closure>.<anonymous closure> 
package:flutter/…/painting/image_provider.dart:385
I/flutter (18137): #6      SynchronousFuture.then 
package:flutter/…/foundation/synchronous_future.dart:41
I/flutter (18137): #7      ImageProvider._createErrorHandlerAndKey.<anonymous closure> 
package:flutter/…/painting/image_provider.dart:382
I/flutter (18137): #8      _rootRun  (dart:async/zone.dart:1126:13)
I/flutter (18137): #9      _CustomZone.run  (dart:async/zone.dart:1023:19)
I/flutter (18137): #10     _CustomZone.runGuarded  (dart:async/zone.dart:925:7)
```

Interestingly if I turn off breaking on uncaught exceptions the images load fine.

**Comment by dnfield** [comment]
@zacps can you try adding the lines I suggested to `image_provider.dart` in the Flutter framework?

That would help identify exactly what error is happening, and should help creating a new test case for this.

**Comment by zacps** [comment]
Those lines **were** from those print statements.

**Comment by dnfield** [comment]
Ahh haha sorry.

It looks like you're very slightly behind master - would you mind bumping up to the latest master?  There's a relevant code change that might be related to this and might have fixed you.  Specifically, https://github.com/flutter/flutter/blob/f769bcc5c4dbecd7058a157188c36c5a7247143d/packages/flutter/lib/src/painting/image_provider.dart#L414-L425

**Comment by zacps** [comment]
Upgrading to latest master seems to have fixed it, thanks!
