### ISSUE TITLE
[desktop]: cann't build windows

### ISSUE THREAD

**Issue by Kassan424kh** [flutter/flutter#50402]
```YAML
name: flutter_app
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  provider: ^4.0.1
  google_fonts: ^0.3.2
  outline_material_icons: ^0.1.1
  path_provider: ^1.5.1
  flutter_datetime_picker: ^1.3.4
  intl: ^0.16.1
  http: ^0.12.0+4
  sqflite: ^1.2.0
  path: ^1.6.4

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/bh_logo_dark.png
    - assets/images/bh_logo_hell.png
    - assets/avatars/avatar_dark.png
    - assets/avatars/avatar_hell.png
```

```LOG
$ flutter run
More than one device connected; please specify a device with the '-d <deviceId>' flag, or use '-d all' to act on all
devices.

Windows    • Windows    • windows-x64    • Microsoft Windows [Version 10.0.18363.592]
Chrome     • chrome     • web-javascript • Google Chrome 79.0.3945.130
Web Server • web-server • web-javascript • Flutter Tools

C:\Users\GaminKh\Desktop\bh_app\flutter_berichtsheft_app>flutter run -d Windows
Launching lib\main.dart on Windows in debug mode...
No Windows desktop project configured. See https://github.com/flutter/flutter/wiki/Desktop-shells#create to learn about
adding Windows support to a project.

C:\Users\GaminKh\Desktop\bh_app\flutter_berichtsheft_app>flutter run -d Windows -v
[  +20 ms] executing: [C:\src\flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[  +60 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[   +1 ms] 49be146953b7a115af5e765ea9f792f110fcb007
[        ] executing: [C:\src\flutter/] git describe --match v*.*.* --first-parent --long --tags
[  +49 ms] Exit code 0 from: git describe --match v*.*.* --first-parent --long --tags
[        ] v1.14.6-138-g49be146
[   +6 ms] executing: [C:\src\flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[  +41 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/master
[        ] executing: [C:\src\flutter/] git ls-remote --get-url origin
[  +37 ms] Exit code 0 from: git ls-remote --get-url origin
[   +1 ms] https://github.com/flutter/flutter.git
[  +68 ms] executing: [C:\src\flutter/] git rev-parse --abbrev-ref HEAD
[  +40 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] master
[  +33 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +3 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +35 ms] executing: C:\Users\GaminKh\AppData\Local\Android\sdk\platform-tools\adb.exe devices -l
[  +20 ms] Exit code 0 from: C:\Users\GaminKh\AppData\Local\Android\sdk\platform-tools\adb.exe devices -l
[        ] List of devices attached
[  +10 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +3 ms] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +79 ms] Found plugin path_provider at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\path_provider-1.6.0\
[  +11 ms] Found plugin sqflite at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\sqflite-1.2.0\
[  +49 ms] Found plugin path_provider at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\path_provider-1.6.0\
[   +5 ms] Found plugin sqflite at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\sqflite-1.2.0\
[  +36 ms] Generating
C:\Users\GaminKh\Desktop\bh_app\flutter_berichtsheft_app\android\app\src\main\java\io\flutter\plugins\GeneratedPluginReg
istrant.java
[  +67 ms] Launching lib\main.dart on Windows in debug mode...
[  +17 ms] "flutter run" took 427ms.
No Windows desktop project configured. See https://github.com/flutter/flutter/wiki/Desktop-shells#create to learn about
adding Windows support to a project.

#0      throwToolExit (package:flutter_tools/src/base/common.dart:14:3)
#1      buildWindows (package:flutter_tools/src/windows/build_windows.dart:20:5)
#2      WindowsDevice.buildForDevice (package:flutter_tools/src/windows/windows_device.dart:46:11)
#3      DesktopDevice.startApp (package:flutter_tools/src/desktop_device.dart:85:13)
#4      FlutterDevice.runHot (package:flutter_tools/src/resident_runner.dart:434:54)
<asynchronous suspension>
#5      HotRunner.run (package:flutter_tools/src/run_hot.dart:333:39)
#6      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:548:37)
<asynchronous suspension>
#7      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:669:18)
#8      _rootRunUnary (dart:async/zone.dart:1134:38)
#9      _CustomZone.runUnary (dart:async/zone.dart:1031:19)
#10     _FutureListener.handleValue (dart:async/future_impl.dart:140:18)
#11     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:682:45)
#12     Future._propagateToListeners (dart:async/future_impl.dart:711:32)
#13     Future._completeWithValue (dart:async/future_impl.dart:526:5)
#14     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:34:15)
#15     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:293:13)
#16     RunCommand.usageValues (package:flutter_tools/src/commands/run.dart)
#17     _rootRunUnary (dart:async/zone.dart:1134:38)
#18     _CustomZone.runUnary (dart:async/zone.dart:1031:19)
#19     _FutureListener.handleValue (dart:async/future_impl.dart:140:18)
#20     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:682:45)
#21     Future._propagateToListeners (dart:async/future_impl.dart:711:32)
#22     Future._completeWithValue (dart:async/future_impl.dart:526:5)
#23     Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:556:7)
#24     _rootRun (dart:async/zone.dart:1126:13)
#25     _CustomZone.run (dart:async/zone.dart:1023:19)
#26     _CustomZone.runGuarded (dart:async/zone.dart:925:7)
#27     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:965:23)
#28     _microtaskLoop (dart:async/schedule_microtask.dart:43:21)
#29     _startMicrotaskLoop (dart:async/schedule_microtask.dart:52:5)
#30     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
#31     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:169:5)
```

```LOG
$ flutter doctor -v
[√] Flutter (Channel master, v1.14.7-pre.138, on Microsoft Windows [Version 10.0.18363.592], locale de-DE)
    • Flutter version 1.14.7-pre.138 at C:\src\flutter
    • Framework revision 49be146953 (2 days ago), 2020-02-05 18:02:20 -0800
    • Engine revision 81dffd1241
    • Dart version 2.8.0 (build 2.8.0-dev.7.0 c8ed304e97)

[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at C:\Users\GaminKh\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.4.3)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.4.29709.97

[√] Android Studio (version 3.5)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 42.1.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)

[!] IntelliJ IDEA Ultimate Edition (version 2018.3)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA 2018.3.2
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.dev/intellij-setup/#installing-the-plugins

[√] VS Code (version 1.39.2)
    • VS Code at C:\Users\GaminKh\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.5.1

[√] Connected device (3 available)
    • Windows    • Windows    • windows-x64    • Microsoft Windows [Version 10.0.18363.592]
    • Chrome     • chrome     • web-javascript • Google Chrome 79.0.3945.130
    • Web Server • web-server • web-javascript • Flutter Tools

! Doctor found issues in 1 category.
```

**Comment by stuartmorgan** [comment]
What is the bug you are trying to report? Have you manually configured your project to have a Windows runner as the link in the failure message explains you need to do, and that's not working? If so, please providing a listing of the `windows` directory that you add your project folder, and details of where you obtained it.

**Comment by Kassan424kh** [comment]
Yes, I configured my project to have windows runner, but the problem everytime I try to do `flutter create .` he doesn't create any windows project folder in my project, this problem cover my all projects not only one.
My projects I has created, are all in Desktop directory.

Steps I did:

1. 
```CMD
flutter channel
Flutter channels:
* master
  dev
  beta
  stable
```
2.
```CMD
flutter config --enable-windows-desktop
Setting "enable-windows-desktop" value to "true".

You may need to restart any open editors for them to read new settings.
```

```CMD
flutter create -v  .
[  +17 ms] executing: [C:\src\flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[  +49 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[        ] 49be146953b7a115af5e765ea9f792f110fcb007
[        ] executing: [C:\src\flutter/] git describe --match v*.*.* --first-parent --long --tags
[  +42 ms] Exit code 0 from: git describe --match v*.*.* --first-parent --long --tags
[        ] v1.14.6-138-g49be146
[   +5 ms] executing: [C:\src\flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[  +35 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/master
[        ] executing: [C:\src\flutter/] git ls-remote --get-url origin
[  +30 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[  +60 ms] executing: [C:\src\flutter/] git rev-parse --abbrev-ref HEAD
[  +33 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[   +1 ms] master
[  +27 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +2 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +19 ms] Artifact Instance of 'MaterialFonts' is not required, skipping update.
[        ] Artifact Instance of 'GradleWrapper' is not required, skipping update.
[        ] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[        ] Artifact Instance of 'FlutterSdk' is not required, skipping update.
[        ] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FontSubsetArtifacts' is not required, skipping update.
[  +76 ms] Recreating project ....
[  +20 ms]   .gitignore (existing - skipped)
[   +1 ms]   .idea\libraries\Dart_SDK.xml (existing - skipped)
[        ]   .idea\libraries\Flutter_for_Android.xml (existing - skipped)
[        ]   .idea\libraries\KotlinJavaRuntime.xml (existing - skipped)
[        ]   .idea\modules.xml (existing - skipped)
[        ]   .idea\runConfigurations\main_dart.xml (existing - skipped)
[        ]   .idea\workspace.xml (existing - skipped)
[        ]   .metadata (existing - skipped)
[        ]   android\app\build.gradle (existing - skipped)
[        ]   android\app\src\main\kotlin\com\example\flutter_berichtsheft_app\MainActivity.kt (existing - skipped)
[        ]   android\build.gradle (existing - skipped)
[        ]   android\flutter_berichtsheft_app_android.iml (existing - skipped)
[        ]   android\.gitignore (existing - skipped)
[        ]   android\app\src\debug\AndroidManifest.xml (existing - skipped)
[        ]   android\app\src\main\AndroidManifest.xml (existing - skipped)
[        ]   android\app\src\main\res\drawable\launch_background.xml (existing - skipped)
[   +1 ms]   android\app\src\main\res\mipmap-hdpi\ic_launcher.png (existing - skipped)
[        ]   android\app\src\main\res\mipmap-mdpi\ic_launcher.png (existing - skipped)
[        ]   android\app\src\main\res\mipmap-xhdpi\ic_launcher.png (existing - skipped)
[        ]   android\app\src\main\res\mipmap-xxhdpi\ic_launcher.png (existing - skipped)
[        ]   android\app\src\main\res\mipmap-xxxhdpi\ic_launcher.png (existing - skipped)
[        ]   android\app\src\main\res\values\styles.xml (existing - skipped)
[        ]   android\app\src\profile\AndroidManifest.xml (existing - skipped)
[        ]   android\gradle\wrapper\gradle-wrapper.properties (existing - skipped)
[        ]   android\gradle.properties (existing - skipped)
[        ]   android\settings.gradle (existing - skipped)
[        ]   ios\Runner\AppDelegate.swift (existing - skipped)
[        ]   ios\Runner\Runner-Bridging-Header.h (existing - skipped)
[        ]   ios\Runner.xcodeproj\project.pbxproj (existing - skipped)
[        ]   ios\Runner.xcodeproj\xcshareddata\xcschemes\Runner.xcscheme (existing - skipped)
[        ]   ios\.gitignore (existing - skipped)
[   +1 ms]   ios\Flutter\AppFrameworkInfo.plist (existing - skipped)
[        ]   ios\Flutter\Debug.xcconfig (existing - skipped)
[        ]   ios\Flutter\Release.xcconfig (existing - skipped)
[        ]   ios\Runner\Assets.xcassets\AppIcon.appiconset\Contents.json (existing - skipped)
[        ]   ios\Runner\Assets.xcassets\AppIcon.appiconset\Icon-App-1024x1024@1x.png (existing - skipped)
[        ]   ios\Runner\Assets.xcassets\AppIcon.appiconset\Icon-App-20x20@1x.png (existing - skipped)
[        ]   ios\Runner\Assets.xcassets\AppIcon.appiconset\Icon-App-20x20@2x.png (existing - skipped)
[        ]   ios\Runner\Assets.xcassets\AppIcon.appiconset\Icon-App-20x20@3x.png (existing - skipped)
[        ]   ios\Runner\Assets.xcassets\AppIcon.appiconset\Icon-App-29x29@1x.png (existing - skipped)
[        ]   ios\Runner\Assets.xcassets\AppIcon.appiconset\Icon-App-29x29@2x.png (existing - skipped)
[        ]   ios\Runner\Assets.xcassets\AppIcon.appiconset\Icon-App-29x29@3x.png (existing - skipped)
[        ]   ios\Runner\Assets.xcassets\AppIcon.appiconset\Icon-App-40x40@1x.png (existing - skipped)
[        ]   ios\Runner\Assets.xcassets\AppIcon.appiconset\Icon-App-40x40@2x.png (existing - skipped)
[        ]   ios\Runner\Assets.xcassets\AppIcon.appiconset\Icon-App-40x40@3x.png (existing - skipped)
[        ]   ios\Runner\Assets.xcassets\AppIcon.appiconset\Icon-App-60x60@2x.png (existing - skipped)
[   +1 ms]   ios\Runner\Assets.xcassets\AppIcon.appiconset\Icon-App-60x60@3x.png (existing - skipped)
[        ]   ios\Runner\Assets.xcassets\AppIcon.appiconset\Icon-App-76x76@1x.png (existing - skipped)
[        ]   ios\Runner\Assets.xcassets\AppIcon.appiconset\Icon-App-76x76@2x.png (existing - skipped)
[        ]   ios\Runner\Assets.xcassets\AppIcon.appiconset\Icon-App-83.5x83.5@2x.png (existing - skipped)
[        ]   ios\Runner\Assets.xcassets\LaunchImage.imageset\Contents.json (existing - skipped)
[        ]   ios\Runner\Assets.xcassets\LaunchImage.imageset\LaunchImage.png (existing - skipped)
[        ]   ios\Runner\Assets.xcassets\LaunchImage.imageset\LaunchImage@2x.png (existing - skipped)
[        ]   ios\Runner\Assets.xcassets\LaunchImage.imageset\LaunchImage@3x.png (existing - skipped)
[        ]   ios\Runner\Assets.xcassets\LaunchImage.imageset\README.md (existing - skipped)
[        ]   ios\Runner\Base.lproj\LaunchScreen.storyboard (existing - skipped)
[        ]   ios\Runner\Base.lproj\Main.storyboard (existing - skipped)
[        ]   ios\Runner\Info.plist (existing - skipped)
[        ]   ios\Runner.xcodeproj\project.xcworkspace\contents.xcworkspacedata (existing - skipped)
[        ]   ios\Runner.xcodeproj\project.xcworkspace\xcshareddata\IDEWorkspaceChecks.plist (existing - skipped)
[        ]   ios\Runner.xcodeproj\project.xcworkspace\xcshareddata\WorkspaceSettings.xcsettings (existing - skipped)
[        ]   ios\Runner.xcodeproj\xcshareddata\xcschemes\Runner.xcscheme (existing - skipped)
[   +1 ms]   ios\Runner.xcworkspace\contents.xcworkspacedata (existing - skipped)
[        ]   ios\Runner.xcworkspace\xcshareddata\IDEWorkspaceChecks.plist (existing - skipped)
[        ]   ios\Runner.xcworkspace\xcshareddata\WorkspaceSettings.xcsettings (existing - skipped)
[        ]   lib\main.dart (existing - skipped)
[        ]   flutter_berichtsheft_app.iml (existing - skipped)
[        ]   pubspec.yaml (existing - skipped)
[        ]   README.md (existing - skipped)
[        ]   test\widget_test.dart (existing - skipped)
[        ]   web\favicon.png (existing - skipped)
[        ]   web\icons\Icon-192.png (existing - skipped)
[        ]   web\icons\Icon-512.png (existing - skipped)
[        ]   web\index.html (existing - skipped)
[        ]   web\manifest.json (existing - skipped)
[  +36 ms] Found plugin path_provider at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\path_provider-1.6.0\
[   +9 ms] Found plugin sqflite at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\sqflite-1.2.0\
[  +48 ms] Found plugin path_provider at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\path_provider-1.6.0\
[   +4 ms] Found plugin sqflite at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\sqflite-1.2.0\
[  +31 ms] Generating
C:\Users\GaminKh\Desktop\bh_app\flutter_berichtsheft_app\android\app\src\main\java\io\flutter\plugins\GeneratedPluginReg
istrant.java
[  +28 ms] Wrote 3 files.
[        ]
           All done!
[   +9 ms] executing: C:\Program Files\Android\Android Studio\jre\bin\java -version
[  +62 ms] Exit code 0 from: C:\Program Files\Android\Android Studio\jre\bin\java -version
[        ] openjdk version "1.8.0_202-release"
           OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)
           OpenJDK 64-Bit Server VM (build 25.202-b03, mixed mode)
[  +13 ms] executing: [C:\src\flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%ar
[  +33 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%ar
[        ] 3 days ago
[  +38 ms] executing: C:\src\flutter\bin\cache\artifacts\engine\android-arm-profile\windows-x64\gen_snapshot
[  +12 ms] Exit code 255 from: C:\src\flutter\bin\cache\artifacts\engine\android-arm-profile\windows-x64\gen_snapshot
[        ] At least one input is required
           Usage: gen_snapshot [<vm-flags>] [<options>] <dart-kernel-file>

           Common options:
           --help
             Display this message (add --verbose for information about all VM options).
           --version
             Print the VM version.

           To create a core snapshot:
           --snapshot_kind=core
           --vm_snapshot_data=<output-file>
           --isolate_snapshot_data=<output-file>
           <dart-kernel-file>

           To create an AOT application snapshot as assembly suitable for compilation
           as a static or dynamic library:
           --snapshot_kind=app-aot-assembly
           --assembly=<output-file>
           [--strip]
           [--obfuscate]
           [--save-debugging-info=<debug-filename>]
           [--save-obfuscation-map=<map-filename>]
           <dart-kernel-file>

           To create an AOT application snapshot as an ELF shared library:
           --snapshot_kind=app-aot-elf
           --elf=<output-file>
           [--strip]
           [--obfuscate]
           [--save-debugging-info=<debug-filename>]
           [--save-obfuscation-map=<map-filename>]
           <dart-kernel-file>

           AOT snapshots can be obfuscated: that is all identifiers will be renamed
           during compilation. This mode is enabled with --obfuscate flag. Mapping
           between original and obfuscated names can be serialized as a JSON array
           using --save-obfuscation-map=<filename> option. See dartbug.com/30524
           for implementation details and limitations of the obfuscation pass.
[   +8 ms] executing: C:\Program Files\Android\Android Studio\jre\bin\java -version
[  +60 ms] Exit code 0 from: C:\Program Files\Android\Android Studio\jre\bin\java -version
[        ] openjdk version "1.8.0_202-release"
           OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)
           OpenJDK 64-Bit Server VM (build 25.202-b03, mixed mode)
[   +2 ms] java -version
[  +78 ms] executing: C:\Users\GaminKh\AppData\Local\Android\sdk\tools\bin\sdkmanager --licenses
[+1164 ms] executing: C:\Program Files (x86)\Microsoft Visual Studio\Installer\vswhere.exe -format json -utf8 -latest
-version 16 -requires Microsoft.Component.MSBuild Microsoft.VisualStudio.Component.VC.Tools.x86.x64
Microsoft.VisualStudio.Component.Windows10SDK.17763
[  +20 ms] Exit code 0 from: C:\Program Files (x86)\Microsoft Visual Studio\Installer\vswhere.exe -format json -utf8
-latest -version 16 -requires Microsoft.Component.MSBuild Microsoft.VisualStudio.Component.VC.Tools.x86.x64
Microsoft.VisualStudio.Component.Windows10SDK.17763
[   +1 ms] [
             {
               "instanceId": "4bc5b324",
               "installDate": "2019-07-16T01:55:26Z",
               "installationName": "VisualStudio/16.4.3+29709.97",
               "installationPath": "C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Community",
               "installationVersion": "16.4.29709.97",
               "productId": "Microsoft.VisualStudio.Product.Community",
               "productPath": "C:\\Program Files (x86)\\Microsoft Visual
               Studio\\2019\\Community\\Common7\\IDE\\devenv.exe",
               "state": 4294967295,
               "isComplete": true,
               "isLaunchable": true,
               "isPrerelease": false,
               "isRebootRequired": false,
               "displayName": "Visual Studio Community 2019",
               "description": "Leistungsstarke IDE, kostenlos fÃ¼r Studenten, Open-Source-Mitwirkende und
               Einzelpersonen",
               "channelId": "VisualStudio.16.Release",
               "channelUri": "https://aka.ms/vs/16/release/channel",
               "enginePath": "C:\\program files (x86)\\microsoft visual
               studio\\installer\\resources\\app\\ServiceHub\\Services\\Microsoft.VisualStudio.Setup.Service",
               "releaseNotes": "https://go.microsoft.com/fwlink/?LinkId=660893#16.4.3",
               "thirdPartyNotices": "https://go.microsoft.com/fwlink/?LinkId=660909",
               "updateDate": "2020-01-19T20:02:39.4558808Z",
               "catalog": {
                 "buildBranch": "d16.4",
                 "buildVersion": "16.4.29709.97",
                 "id": "VisualStudio/16.4.3+29709.97",
                 "localBuild": "build-lab",
                 "manifestName": "VisualStudio",
                 "manifestType": "installer",
                 "productDisplayVersion": "16.4.3",
                 "productLine": "Dev16",
                 "productLineVersion": "2019",
                 "productMilestone": "RTW",
                 "productMilestoneIsPreRelease": "False",
                 "productName": "Visual Studio",
                 "productPatchVersion": "3",
                 "productPreReleaseMilestoneSuffix": "1.0",
                 "productSemanticVersion": "16.4.3+29709.97",
                 "requiredEngineVersion": "2.4.1111.43337"
               },
               "properties": {
                 "campaignId": "1659700524.1543689973",
                 "canceled": "0",
                 "channelManifestId": "VisualStudio.16.Release/16.4.3+29709.97",
                 "nickname": "",
                 "setupEngineFilePath": "C:\\Program Files (x86)\\Microsoft Visual
                 Studio\\Installer\\vs_installershell.exe"
               }
             }
           ]
[  +70 ms] executing: C:\Users\GaminKh\AppData\Local\Android\sdk\platform-tools\adb.exe devices -l
[  +16 ms] Exit code 0 from: C:\Users\GaminKh\AppData\Local\Android\sdk\platform-tools\adb.exe devices -l
[        ] List of devices attached
[  +18 ms] [√] Flutter: is fully installed. (Channel master, v1.14.7-pre.138, on Microsoft Windows [Version
10.0.18363.592], locale
               de-DE)
           [√] Android toolchain - develop for Android devices: is fully installed. (Android SDK version 28.0.3)
           [√] Chrome - develop for the web: is fully installed.
           [√] Visual Studio - develop for Windows: is fully installed. (Visual Studio Community 2019 16.4.3)
           [√] Android Studio: is fully installed. (version 3.5)
           [!] IntelliJ IDEA Ultimate Edition: is partially installed; more components are available. (version 2018.3)
           [√] VS Code: is fully installed. (version 1.39.2)
           [√] Connected device: is fully installed. (3 available)

           Run "flutter doctor" for information about installing additional components.

[   +2 ms] In order to run your application, type:

             $ cd .
             $ flutter run

           Your application code is in .\lib\main.dart.

[   +5 ms] "flutter create" took 2.020ms.
```

**Comment by stuartmorgan** [comment]
> Yes, I configured my project to have windows runner

The steps you showed do not include adding a Windows runner to your project. You've enabled the initial tool support for Windows via `flutter config`, but that's not the same thing.

> but the problem everytime I try to do `flutter create .` he doesn't create any windows project folder in my project, this problem cover my all projects not only one.

Please follow the link that was provided to you in the `flutter run` output; as it says in the first sentence, "Currently, macOS is the only desktop platform supported by `flutter create`." It then provides more information about the manual steps needed (per project) to run on Windows. That's why it was provided in the error message.

Closing as this is the expected behavior when trying to run a project that hasn't been configured for Windows.

**Comment by Kassan424kh** [comment]
Sorry mr @stuartmorgan, it's my bad, thank's for your answer, it work's now.

**Comment by honglei92** [comment]
flutter create .                 it works
