### ISSUE TITLE
Image Picker Invalid `Podfile` file: no implicit conversion of nil into String.

### ISSUE THREAD

**Issue by geekyme** [flutter/flutter#50407]
## Steps to Reproduce

1. Install `image_picker` on a brand new flutter project - https://pub.dev/packages/image_picker#-installing-tab-
2. Run `flutter pub get`
3. Run `flutter run`
4. Error below will appear

The above can be summarized in this commit - https://github.com/geekyme/test_flutter_bug/commit/78efb8a9b04a5e1ab6b5e585bc3a4cb214cf4adf

**Expected results:** 
No errors when running

**Actual results:** 

```
    [!] Invalid `Podfile` file: no implicit conversion of nil into String.

     #  from /Users/shawnlim/Documents/Code/projects/test_app/ios/Podfile:41
     #  -------------------------------------------
     #  
     >    copied_flutter_dir = File.join(__dir__, 'Flutter')
     #    copied_framework_path = File.join(copied_flutter_dir, 'Flutter.framework')
     #  -------------------------------------------

    /Users/shawnlim/.rvm/gems/ruby-2.1.1@global/gems/cocoapods-core-1.8.4/lib/cocoapods-core/podfile.rb:301:in `rescue in block in from_ruby'
    /Users/shawnlim/.rvm/gems/ruby-2.1.1@global/gems/cocoapods-core-1.8.4/lib/cocoapods-core/podfile.rb:295:in `block in from_ruby'
    /Users/shawnlim/.rvm/gems/ruby-2.1.1@global/gems/cocoapods-core-1.8.4/lib/cocoapods-core/podfile.rb:50:in `instance_eval'
    /Users/shawnlim/.rvm/gems/ruby-2.1.1@global/gems/cocoapods-core-1.8.4/lib/cocoapods-core/podfile.rb:50:in `initialize'
    /Users/shawnlim/.rvm/gems/ruby-2.1.1@global/gems/cocoapods-core-1.8.4/lib/cocoapods-core/podfile.rb:293:in `new'
    /Users/shawnlim/.rvm/gems/ruby-2.1.1@global/gems/cocoapods-core-1.8.4/lib/cocoapods-core/podfile.rb:293:in `from_ruby'
    /Users/shawnlim/.rvm/gems/ruby-2.1.1@global/gems/cocoapods-core-1.8.4/lib/cocoapods-core/podfile.rb:259:in `from_file'
    /Users/shawnlim/.rvm/gems/ruby-2.1.1@global/gems/cocoapods-1.8.4/lib/cocoapods/config.rb:200:in `podfile'
    /Users/shawnlim/.rvm/gems/ruby-2.1.1@global/gems/cocoapods-1.8.4/lib/cocoapods/command.rb:150:in `verify_podfile_exists!'
    /Users/shawnlim/.rvm/gems/ruby-2.1.1@global/gems/cocoapods-1.8.4/lib/cocoapods/command/install.rb:46:in `run'
    /Users/shawnlim/.rvm/gems/ruby-2.1.1@global/gems/claide-1.0.3/lib/claide/command.rb:334:in `run'
    /Users/shawnlim/.rvm/gems/ruby-2.1.1@global/gems/cocoapods-1.8.4/lib/cocoapods/command.rb:52:in `run'
    /Users/shawnlim/.rvm/gems/ruby-2.1.1@global/gems/cocoapods-1.8.4/bin/pod:55:in `<top (required)>'
    /Users/shawnlim/.rvm/gems/ruby-2.1.1/bin/pod:23:in `load'
    /Users/shawnlim/.rvm/gems/ruby-2.1.1/bin/pod:23:in `<main>'
    /Users/shawnlim/.rvm/gems/ruby-2.1.1/bin/ruby_executable_hooks:15:in `eval'
    /Users/shawnlim/.rvm/gems/ruby-2.1.1/bin/ruby_executable_hooks:15:in `<main>'
```

<details>
  <summary>Logs</summary>

```
/Users/shawnlim/.pub-cache/hosted/pub.dartlang.org/flutter_plugin_android_lifecycle-1.0.5/
[   +2 ms] Found plugin image_picker at /Users/shawnlim/.pub-cache/hosted/pub.dartlang.org/image_picker-0.6.3+1/
[  +30 ms] executing: which pod
[  +14 ms] executing: pod --version
[+1289 ms] 1.8.4
[   +2 ms] Running pod install...
[ +587 ms] Running pod install... (completed in 0.6s)
[        ] CocoaPods' output:
           ↳
[        ] 
               [!] Invalid `Podfile` file: no implicit conversion of nil into String.
           
                #  from /Users/shawnlim/Documents/Code/projects/test_app/ios/Podfile:41
                #  -------------------------------------------
                #  
                >    copied_flutter_dir = File.join(__dir__, 'Flutter')
                #    copied_framework_path = File.join(copied_flutter_dir, 'Flutter.framework')
                #  -------------------------------------------
           
               /Users/shawnlim/.rvm/gems/ruby-2.1.1@global/gems/cocoapods-core-1.8.4/lib/cocoapods-core/podfile.rb:301:in `rescue in block in
from_ruby'
               /Users/shawnlim/.rvm/gems/ruby-2.1.1@global/gems/cocoapods-core-1.8.4/lib/cocoapods-core/podfile.rb:295:in `block in
from_ruby'
               /Users/shawnlim/.rvm/gems/ruby-2.1.1@global/gems/cocoapods-core-1.8.4/lib/cocoapods-core/podfile.rb:50:in `instance_eval'
               /Users/shawnlim/.rvm/gems/ruby-2.1.1@global/gems/cocoapods-core-1.8.4/lib/cocoapods-core/podfile.rb:50:in `initialize'
               /Users/shawnlim/.rvm/gems/ruby-2.1.1@global/gems/cocoapods-core-1.8.4/lib/cocoapods-core/podfile.rb:293:in `new'
               /Users/shawnlim/.rvm/gems/ruby-2.1.1@global/gems/cocoapods-core-1.8.4/lib/cocoapods-core/podfile.rb:293:in `from_ruby'
               /Users/shawnlim/.rvm/gems/ruby-2.1.1@global/gems/cocoapods-core-1.8.4/lib/cocoapods-core/podfile.rb:259:in `from_file'
               /Users/shawnlim/.rvm/gems/ruby-2.1.1@global/gems/cocoapods-1.8.4/lib/cocoapods/config.rb:200:in `podfile'
               /Users/shawnlim/.rvm/gems/ruby-2.1.1@global/gems/cocoapods-1.8.4/lib/cocoapods/command.rb:150:in `verify_podfile_exists!'
               /Users/shawnlim/.rvm/gems/ruby-2.1.1@global/gems/cocoapods-1.8.4/lib/cocoapods/command/install.rb:46:in `run'
               /Users/shawnlim/.rvm/gems/ruby-2.1.1@global/gems/claide-1.0.3/lib/claide/command.rb:334:in `run'
               /Users/shawnlim/.rvm/gems/ruby-2.1.1@global/gems/cocoapods-1.8.4/lib/cocoapods/command.rb:52:in `run'
               /Users/shawnlim/.rvm/gems/ruby-2.1.1@global/gems/cocoapods-1.8.4/bin/pod:55:in `<top (required)>'
               /Users/shawnlim/.rvm/gems/ruby-2.1.1/bin/pod:23:in `load'
               /Users/shawnlim/.rvm/gems/ruby-2.1.1/bin/pod:23:in `<main>'
               /Users/shawnlim/.rvm/gems/ruby-2.1.1/bin/ruby_executable_hooks:15:in `eval'
               /Users/shawnlim/.rvm/gems/ruby-2.1.1/bin/ruby_executable_hooks:15:in `<main>'
           
[   +4 ms] Error running pod install
[   +1 ms] Error launching application on iPhone 11 Pro Max.
[   +2 ms] "flutter run" took 9,376ms.

```

```
➜  test_app git:(master) flutter analyze
Analyzing test_app...                                                   
No issues found! (ran in 8.9s)
```

```
➜  test_app git:(master) flutter doctor -v 
[✓] Flutter (Channel beta, v1.14.6, on Mac OS X 10.14.6 18G2022, locale en-SG)
    • Flutter version 1.14.6 at /Users/shawnlim/Documents/Code/flutter/flutter
    • Framework revision fabeb2a16f (11 days ago), 2020-01-28 07:56:51 -0800
    • Engine revision c4229bfbba
    • Dart version 2.8.0 (build 2.8.0-dev.5.0 fc3af737c7)

[!] Android toolchain - develop for Android devices (Android SDK version 23.0.3)
    • Android SDK at /usr/local/Cellar/android-sdk/24.4.1_1
    • Android NDK location not configured (optional; useful for native profiling support)
    ✗ Flutter requires Android SDK 28 and the Android BuildTools 28.0.3
      To update using sdkmanager, run:
        "/usr/local/Cellar/android-sdk/24.4.1_1/tools/bin/sdkmanager" "platforms;android-28" "build-tools;28.0.3"
      or visit https://flutter.dev/setup/#android-setup for detailed instructions.
    ✗ Android license status unknown.
      Try re-installing or updating your Android SDK Manager.
      See https://developer.android.com/studio/#downloads or visit https://flutter.dev/setup/#android-setup for detailed instructions.

[✓] Xcode - develop for iOS and macOS (Xcode 11.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.3.1, Build version 11C504
    • CocoaPods version 1.8.4

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/setup/#android-setup for detailed instructions).

[!] IntelliJ IDEA Community Edition (version 2016.3.5)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.dev/intellij-setup/#installing-the-plugins
    ✗ This install is older than the minimum recommended version of 2017.1.0.

[✓] VS Code (version 1.42.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.8.1

[✓] Connected device (4 available)
    • shawnlim’s iPhone • c6e009055420a008a68016a0f27b4f16db4a04ee • ios            • iOS 13.3.1
    • iPhone 11 Pro Max • 0C298F80-51F0-4FA6-AACB-F38BECCD8684     • ios            • com.apple.CoreSimulator.SimRuntime.iOS-13-3 (simulator)
    • Chrome            • chrome                                   • web-javascript • Google Chrome 79.0.3945.130
    • Web Server        • web-server                               • web-javascript • Flutter Tools
```

</details>

**Comment by geekyme** [comment]
Couldn't reproduce this on a new machine. I think something is wrong on my installation.

**Comment by geekyme** [comment]
Fixed this by reinstalling `ruby` and `cocoapods`

**Comment by JavascriptMick** [comment]
I have this issue but I'm not very happy with this resolution.  flutter doctor is showing no issues, why should I re-install stuff.  Is there any other way of solving this issue? what is the cause?

**Comment by dratushnyy** [comment]
@jacek-marchwicki 
Try to replace line 41 in your Podfile. with this `copied_flutter_dir = File.join('.', 'Flutter')`
I.e. `your_app/ios/Podfile: L41`, replace this `copied_flutter_dir = File.join(__dir__, 'Flutter')` with this `copied_flutter_dir = File.join('.', 'Flutter')`

**Comment by allansrc** [comment]
> Fixed this by reinstalling `ruby` and `cocoapods`

i'm on ruby 3.0.0 and cocoapods 1.10.1 and yet getting this error.

**Comment by allansrc** [comment]
> @jacek-marchwicki
> Try to replace line 41 in your Podfile. with this `copied_flutter_dir = File.join('.', 'Flutter')`
> I.e. `your_app/ios/Podfile: L41`, replace this `copied_flutter_dir = File.join(__dir__, 'Flutter')` with this `copied_flutter_dir = File.join('.', 'Flutter')`

that doesnt work for me

**Comment by Nader2004** [comment]
I have this error : 

```
 [!] Invalid `Podfile` file: no implicit conversion of nil into String.

     #  from /Users/builder/clone/ios/Podfile:57
     #  -------------------------------------------
     #      unless File.exist?(copied_framework_path)
     >        FileUtils.cp_r(File.join(cached_framework_dir, 'Flutter.framework'), copied_flutter_dir)
     #      end
     #  -------------------------------------------
```
