### ISSUE TITLE
Flutter crash

### ISSUE THREAD

**Issue by PawanChaudhary-stack** [flutter/flutter#50410]
Flutter crash report; please file at https://github.com/flutter/flutter/issues.

## command

flutter --version

## exception

VersionCheckError: VersionCheckError: Command exited with code 128: git -c log.showSignature=false log -n 1 --pretty=format:%ad --date=iso
Standard error: fatal: bad numeric config value 'ture' for 'color.ui': invalid unit

```
#0      _runSync (package:flutter_tools/src/version.dart:543:5)
#1      FlutterVersion._latestGitCommitDate (package:flutter_tools/src/version.dart:143:12)
#2      FlutterVersion.frameworkCommitDate (package:flutter_tools/src/version.dart:133:37)
#3      FlutterVersion.checkFlutterVersionFreshness (package:flutter_tools/src/version.dart:294:62)
#4      FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:388:41)
<asynchronous suspension>
#5      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:146:29)
#6      _rootRun (dart:async/zone.dart:1126:13)
#7      _CustomZone.run (dart:async/zone.dart:1023:19)
#8      _runZoned (dart:async/zone.dart:1518:10)
#9      runZoned (dart:async/zone.dart:1465:12)
#10     AppContext.run (package:flutter_tools/src/base/context.dart:145:18)
#11     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:364:19)
#12     CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:112:25)
#13     new Future.sync (dart:async/future.dart:224:31)
#14     CommandRunner.run (package:args/command_runner.dart:112:14)
#15     FlutterCommandRunner.run (package:flutter_tools/src/runner/flutter_command_runner.dart:250:18)
#16     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:63:22)
#17     _rootRun (dart:async/zone.dart:1126:13)
#18     _CustomZone.run (dart:async/zone.dart:1023:19)
#19     _runZoned (dart:async/zone.dart:1518:10)
#20     runZoned (dart:async/zone.dart:1502:12)
#21     run.<anonymous closure> (package:flutter_tools/runner.dart:61:18)
<asynchronous suspension>
#22     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:146:29)
#23     _rootRun (dart:async/zone.dart:1126:13)
#24     _CustomZone.run (dart:async/zone.dart:1023:19)
#25     _runZoned (dart:async/zone.dart:1518:10)
#26     runZoned (dart:async/zone.dart:1465:12)
#27     AppContext.run (package:flutter_tools/src/base/context.dart:145:18)
#28     runInContext (package:flutter_tools/src/context_runner.dart:64:24)
#29     run (package:flutter_tools/runner.dart:50:10)
#30     main (package:flutter_tools/executable.dart:65:9)
#31     main (file:///b/s/w/ir/k/archive/flutter/packages/flutter_tools/bin/flutter_tools.dart:8:3)
#32     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:305:32)
#33     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:174:12)
```

## flutter doctor

```
[33m[!][39m Flutter (Channel stable, v0.0.0-unknown, on Mac OS X 10.15.3 19D76, locale
    en-US)
    [32m•[39m Flutter version 0.0.0-unknown at /Users/pawanchaudhary/Developer/flutter
    [31m✗[39m Command exited with code 128: git -c log.showSignature=false log -n 1
      --pretty=format:%ad --date=iso
      Standard error: fatal: bad numeric config value 'ture' for 'color.ui':
      invalid unit


[32m[✓][39m Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    [32m•[39m Android SDK at /Users/pawanchaudhary/Library/Android/sdk
    [32m•[39m Android NDK location not configured (optional; useful for native profiling
      support)
    [32m•[39m Platform android-29, build-tools 29.0.2
    [32m•[39m Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    [32m•[39m Java version OpenJDK Runtime Environment (build
      1.8.0_202-release-1483-b49-5587405)
    [32m•[39m All Android licenses accepted.

[32m[✓][39m Xcode - develop for iOS and macOS (Xcode 11.3.1)
    [32m•[39m Xcode at /Applications/Xcode.app/Contents/Developer
    [32m•[39m Xcode 11.3.1, Build version 11C504
    [32m•[39m CocoaPods version 1.8.4

[33m[!][39m Android Studio (version 3.5)
    [32m•[39m Android Studio at /Applications/Android Studio.app/Contents
    [31m✗[39m Flutter plugin not installed; this adds Flutter specific functionality.
    [32m•[39m Dart plugin version 191.8593
    [32m•[39m Java version OpenJDK Runtime Environment (build
      1.8.0_202-release-1483-b49-5587405)

[32m[✓][39m VS Code (version 1.41.1)
    [32m•[39m VS Code at /Applications/Visual Studio Code.app/Contents
    [32m•[39m Flutter extension version 3.8.0

[33m[!][39m Connected device
    [33m![39m No devices available

[33m![39m Doctor found issues in 3 categories.
```

**Comment by jonahwilliams** [comment]
See: Standard error: fatal: bad numeric config value 'ture' for 'color.ui':
      invalid unit

Did you misconfigure git?

**Comment by PawanChaudhary-stack** [comment]
i  installed flutter and did not used for few months and when i opened flutter this error occurred.

**Comment by jmagman** [comment]
What's the output of:
```
$ cd path/to/flutter-sdk
$ git config --global color.ui                                                          
$ git config color.ui   
```

**Comment by jonahwilliams** [comment]
De-duping into https://github.com/flutter/flutter/issues/50902

**Comment by jonahwilliams** [comment]
If you have more context for this error message, or want to leave a 👍 to indicate that it is still effecting you please comment on the meta issue https://github.com/flutter/flutter/issues/50902
