### ISSUE TITLE
engine crash from google play user

### ISSUE THREAD

**Issue by singun-lxd** [flutter/flutter#50429]
I've found an engine crash collected from Google Play console, I did not know how to reproduce it.

## Raw stack

tgkill

```
*** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
pid: 0, tid: 0 >>> com.myapp <<<

backtrace:
  #00  pc 000000000003d1b8  /system/lib/libc.so (tgkill+12)
  #01  pc 00000000000171f9  /system/lib/libc.so (pthread_kill+52)
  #02  pc 0000000000017e17  /system/lib/libc.so (raise+10)
  #03  pc 0000000000014691  /system/lib/libc.so (__libc_android_abort+36)
  #04  pc 0000000000012500  /system/lib/libc.so (abort+4)
  #05  pc 000000000028df2d  /data/app/com.myapp-1/lib/arm/libflutter.so
  #06  pc 000000000004044d  /data/app/com.myapp-1/lib/arm/libflutter.so
  #07  pc 000000000004d515  /data/app/com.myapp-1/lib/arm/libflutter.so
  #08  pc 000000000001a2d3  /data/app/com.myapp-1/lib/arm/libflutter.so
  #09  pc 00000000002686d7  /data/dalvik-cache/arm/data@app@com.myapp-1@base.apk@classes.dex (long io.flutter.embedding.engine.FlutterJNI.nativeAttach(io.flutter.embedding.engine.FlutterJNI, boolean)+106)
```

## Ndk Stack with symbols

```
********** Crash dump: **********
#00 0x000000000003d1b8 /system/lib/libc.so (tgkill+12)
#01 0x00000000000171f9 /system/lib/libc.so (pthread_kill+52)
#02 0x0000000000017e17 /system/lib/libc.so (raise+10)
#03 0x0000000000014691 /system/lib/libc.so (__libc_android_abort+36)
#04 0x0000000000012500 /system/lib/libc.so (abort+4)
#05 0x000000000028df2d /data/app/com.myapp-1/lib/arm/libflutter.so
GrGLSLUnrolledBinaryGradientColorizer::emitCode(GrGLSLFragmentProcessor::EmitArgs&)
/b/s/w/ir/cache/builder/src/out/android_release/../../third_party/skia/src/gpu/gradients/generated/GrUnrolledBinaryGradientColorizer.cpp:110:24
#06 0x000000000004044d /data/app/com.myapp-1/lib/arm/libflutter.so
??
??:0:0
#07 0x000000000004d515 /data/app/com.myapp-1/lib/arm/libflutter.so
??
??:0:0
#08 0x000000000001a2d3 /data/app/com.myapp-1/lib/arm/libflutter.so
??
??:0:0
#09 0x00000000002686d7 /data/dalvik-cache/arm/data@app@com.myapp-1@base.apk@classes.dex (long io.flutter.embedding.engine.FlutterJNI.nativeAttach(io.flutter.embedding.engine.FlutterJNI, boolean)+106)

```

<details>
  <summary>Info and Logs</summary>

**flutter run --verbose results:**

```
[  +36 ms] executing: [/Users/singun/Library/Flutter/sdk/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[  +67 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[        ] 9f5ff2306bb3e30b2b98eee79cd231b1336f41f4
[        ] executing: [/Users/singun/Library/Flutter/sdk/] git describe --match v*.*.* --first-parent --long --tags
[ +100 ms] Exit code 0 from: git describe --match v*.*.* --first-parent --long --tags
[   +3 ms] v1.12.13+hotfix.7-0-g9f5ff2306
[  +10 ms] executing: [/Users/singun/Library/Flutter/sdk/] git rev-parse --abbrev-ref --symbolic @{u}
[  +11 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/stable
[        ] executing: [/Users/singun/Library/Flutter/sdk/] git ls-remote --get-url origin
[  +18 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[+9674 ms] executing: [/Users/singun/Library/Flutter/sdk/] git rev-parse --abbrev-ref HEAD
[  +10 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] stable
[   +6 ms] executing: sw_vers -productName
[  +27 ms] Exit code 0 from: sw_vers -productName
[        ] Mac OS X
[        ] executing: sw_vers -productVersion
[  +16 ms] Exit code 0 from: sw_vers -productVersion
[        ] 10.15.3
[        ] executing: sw_vers -buildVersion
[  +21 ms] Exit code 0 from: sw_vers -buildVersion
[        ] 19D76
[  +32 ms] executing: /usr/bin/xcode-select --print-path
[   +9 ms] Exit code 0 from: /usr/bin/xcode-select --print-path
[        ] /Applications/Xcode.app/Contents/Developer
[   +3 ms] executing: /usr/bin/xcodebuild -version
[+1626 ms] Exit code 0 from: /usr/bin/xcodebuild -version
[        ] Xcode 11.3.1
           Build version 11C504
[ +101 ms] executing: /Users/singun/Library/Android/sdk/platform-tools/adb devices -l
[   +8 ms] Exit code 0 from: /Users/singun/Library/Android/sdk/platform-tools/adb devices -l
[        ] List of devices attached
[  +16 ms] executing: /Users/singun/Library/Flutter/sdk/bin/cache/artifacts/libimobiledevice/idevice_id -h
[  +53 ms] /usr/bin/xcrun simctl list --json devices
[ +138 ms] No supported devices connected.
[  +10 ms] "flutter run" took 2,082ms.

#0      throwToolExit (package:flutter_tools/src/base/common.dart:28:3)
#1      RunCommand.validateCommand (package:flutter_tools/src/commands/run.dart:289:7)
<asynchronous suspension>
#2      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:590:11)
#3      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:515:33)
<asynchronous suspension>
#4      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:146:29)
#5      _rootRun (dart:async/zone.dart:1126:13)
#6      _CustomZone.run (dart:async/zone.dart:1023:19)
#7      _runZoned (dart:async/zone.dart:1518:10)
#8      runZoned (dart:async/zone.dart:1465:12)
#9      AppContext.run (package:flutter_tools/src/base/context.dart:145:18)
#10     FlutterCommand.run (package:flutter_tools/src/runner/flutter_command.dart:505:20)
#11     CommandRunner.runCommand (package:args/command_runner.dart:197:27)
#12     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:413:21)
<asynchronous suspension>
#13     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:146:29)
#14     _rootRun (dart:async/zone.dart:1126:13)
#15     _CustomZone.run (dart:async/zone.dart:1023:19)
#16     _runZoned (dart:async/zone.dart:1518:10)
#17     runZoned (dart:async/zone.dart:1465:12)
#18     AppContext.run (package:flutter_tools/src/base/context.dart:145:18)
#19     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:364:19)
#20     CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:112:25)
#21     new Future.sync (dart:async/future.dart:224:31)
#22     CommandRunner.run (package:args/command_runner.dart:112:14)
#23     FlutterCommandRunner.run (package:flutter_tools/src/runner/flutter_command_runner.dart:250:18)
#24     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:63:22)
#25     _rootRun (dart:async/zone.dart:1126:13)
#26     _CustomZone.run (dart:async/zone.dart:1023:19)
#27     _runZoned (dart:async/zone.dart:1518:10)
#28     runZoned (dart:async/zone.dart:1502:12)
#29     run.<anonymous closure> (package:flutter_tools/runner.dart:61:18)
<asynchronous suspension>
#30     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:146:29)
#31     _rootRun (dart:async/zone.dart:1126:13)
#32     _CustomZone.run (dart:async/zone.dart:1023:19)
#33     _runZoned (dart:async/zone.dart:1518:10)
#34     runZoned (dart:async/zone.dart:1465:12)
#35     AppContext.run (package:flutter_tools/src/base/context.dart:145:18)
#36     runInContext (package:flutter_tools/src/context_runner.dart:64:24)
#37     run (package:flutter_tools/runner.dart:50:10)
#38     main (package:flutter_tools/executable.dart:65:9)
#39     main (file:///Users/singun/Library/Flutter/sdk/packages/flutter_tools/bin/flutter_tools.dart:8:3)
#40     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:305:32)
#41     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:174:12)
```

**flutter analyze results:**

no error

**flutter doctor -v results:**

```
[✓] Flutter (Channel stable, v1.12.13+hotfix.7, on Mac OS X 10.15.3 19D76, locale zh-Hans-CN)
    • Flutter version 1.12.13+hotfix.7 at /Users/singun/Library/Flutter/sdk
    • Framework revision 9f5ff2306b (13 days ago), 2020-01-26 22:38:26 -0800
    • Engine revision a67792536c
    • Dart version 2.7.0

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/singun/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • ANDROID_HOME = /Users/singun/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.3.1, Build version 11C504
    • CocoaPods version 1.8.4

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 43.0.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] VS Code (version 1.27.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 2.21.1

[!] Connected device
    ! No devices available

! Doctor found issues in 1 category.
```
</details>

**Comment by singun-lxd** [comment]
This crash may properly happen in Samsung Android 5.1 Devices, like Galaxy Core Prime, Galaxy Grand Prime.

**Comment by darshankawar** [comment]
@singun-lxd 
Is this still a valid issue using latest Flutter version or has this been resolved ?
If issue persists, can you provide a reproducible code sample that's replicable in non-prod environment ?
Thanks.

**Comment by singun-lxd** [comment]
> @singun-lxd
> Is this still a valid issue using latest Flutter version or has this been resolved ?
> If issue persists, can you provide a reproducible code sample that's replicable in non-prod environment ?
> Thanks.

@darshankawar I think this problem has been resolved and this issue can be closed, it not exists using latest Flutter version
