### ISSUE TITLE
flutter engine crash

### ISSUE THREAD

**Issue by singun-lxd** [flutter/flutter#50438]
I've found another engine crash collected from Google Play console, I don't know how to reproduce it.

## Raw stack
```
*** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
pid: 0, tid: 0 >>> com.myapp <<<

backtrace:
  #00  pc 00000000002c9e9e  /data/app/com.myapp-1/lib/arm/libflutter.so
  #01  pc 0000000000329f7b  /data/app/com.myapp-1/lib/arm/libflutter.so
  #02  pc 0000000000385b97  /data/app/com.myapp-1/lib/arm/libflutter.so
  #03  pc 000000000020d92b  /data/app/com.myapp-1/lib/arm/libflutter.so
  #04  pc 000000000020af3d  /data/app/com.myapp-1/lib/arm/libflutter.so
  #05  pc 0000000000024755  /data/app/com.myapp-1/lib/arm/libflutter.so
  #06  pc 0000000000026489  /data/app/com.myapp-1/lib/arm/libflutter.so
  #07  pc 0000000000011a8f  /system/lib/libutils.so (android::SimpleLooperCallback::handleEvent(int, int, void*)+10)
  #08  pc 00000000000126f1  /system/lib/libutils.so (android::Looper::pollInner(int)+484)
  #09  pc 0000000000012799  /system/lib/libutils.so (android::Looper::pollOnce(int, int*, int*, void**)+92)
  #10  pc 0000000000008db1  /system/lib/libandroid.so (ALooper_pollOnce+64)
  #11  pc 0000000000026561  /data/app/com.myapp-1/lib/arm/libflutter.so
  #12  pc 0000000000023adf  /data/app/com.myapp-1/lib/arm/libflutter.so
  #13  pc 00000000000254a1  /data/app/com.myapp-1/lib/arm/libflutter.so
  #14  pc 0000000000016f17  /system/lib/libc.so (__pthread_start(void*)+30)
  #15  pc 0000000000014f4b  /system/lib/libc.so (__start_thread+6)
```

## Ndk Stack with symbols
```
********** Crash dump: **********
#00 0x00000000002c9e9e /data/app/com.myapp-1/lib/arm/libflutter.so
SkScalerContext_FreeType_Base::generateGlyphImage(FT_FaceRec_*, SkGlyph const&, SkMatrix const&)
/b/s/w/ir/cache/builder/src/out/android_release/../../third_party/skia/src/ports/SkFontHost_FreeType_common.cpp:545:38
#01 0x0000000000329f7b /data/app/com.myapp-1/lib/arm/libflutter.so
hb_ot_mirror_chars(hb_ot_shape_context_t const*)
/b/s/w/ir/cache/builder/src/out/android_release/../../third_party/harfbuzz/src/hb-ot-shape.cc:611:9
hb_ot_substitute_default(hb_ot_shape_context_t const*)
/b/s/w/ir/cache/builder/src/out/android_release/../../third_party/harfbuzz/src/hb-ot-shape.cc:791:0
hb_ot_substitute_pre(hb_ot_shape_context_t const*)
/b/s/w/ir/cache/builder/src/out/android_release/../../third_party/harfbuzz/src/hb-ot-shape.cc:824:0
hb_ot_shape_internal(hb_ot_shape_context_t*)
/b/s/w/ir/cache/builder/src/out/android_release/../../third_party/harfbuzz/src/hb-ot-shape.cc:1067:0
_hb_ot_shape
/b/s/w/ir/cache/builder/src/out/android_release/../../third_party/harfbuzz/src/hb-ot-shape.cc:1091:0
#02 0x0000000000385b97 /data/app/com.myapp-1/lib/arm/libflutter.so
vec4_rshift_word
/b/s/w/ir/cache/builder/src/out/android_release/../../third_party/boringssl/src/crypto/hrss/hrss.c:238:10
poly_mul_vec_aux
/b/s/w/ir/cache/builder/src/out/android_release/../../third_party/boringssl/src/crypto/hrss/hrss.c:1214:0
#03 0x000000000020d92b /data/app/com.myapp-1/lib/arm/libflutter.so
std::__1::istreambuf_iterator<wchar_t, std::__1::char_traits<wchar_t> > std::__1::num_get<wchar_t, std::__1::istreambuf_iterator<wchar_t, std::__1::char_traits<wchar_t> > >::__do_get_unsigned<unsigned long>(std::__1::istreambuf_iterator<wchar_t, std::__1::char_traits<wchar_t> >, std::__1::istreambuf_iterator<wchar_t, std::__1::char_traits<wchar_t> >, std::__1::ios_base&, unsigned int&, unsigned long&) const
/b/s/w/ir/cache/builder/src/out/android_release/../../third_party/libcxx/include/locale:954:18
std::__1::num_get<wchar_t, std::__1::istreambuf_iterator<wchar_t, std::__1::char_traits<wchar_t> > >::do_get(std::__1::istreambuf_iterator<wchar_t, std::__1::char_traits<wchar_t> >, std::__1::istreambuf_iterator<wchar_t, std::__1::char_traits<wchar_t> >, std::__1::ios_base&, unsigned int&, unsigned int&) const
/b/s/w/ir/cache/builder/src/out/android_release/../../third_party/libcxx/include/locale:703:0
#04 0x000000000020af3d /data/app/com.myapp-1/lib/arm/libflutter.so
std::__1::basic_ostream<wchar_t, std::__1::char_traits<wchar_t> >::basic_ostream(std::__1::basic_streambuf<wchar_t, std::__1::char_traits<wchar_t> >*)
/b/s/w/ir/cache/builder/src/out/android_release/../../third_party/libcxx/include/ostream:166:5
#05 0x0000000000024755 /data/app/com.myapp-1/lib/arm/libflutter.so
??
??:0:0
#06 0x0000000000026489 /data/app/com.myapp-1/lib/arm/libflutter.so
??
??:0:0
#07 0x0000000000011a8f /system/lib/libutils.so (android::SimpleLooperCallback::handleEvent(int, int, void*)+10)
#08 0x00000000000126f1 /system/lib/libutils.so (android::Looper::pollInner(int)+484)
#09 0x0000000000012799 /system/lib/libutils.so (android::Looper::pollOnce(int, int*, int*, void**)+92)
#10 0x0000000000008db1 /system/lib/libandroid.so (ALooper_pollOnce+64)
#11 0x0000000000026561 /data/app/com.myapp-1/lib/arm/libflutter.so
??
??:0:0
#12 0x0000000000023adf /data/app/com.myapp-1/lib/arm/libflutter.so
??
??:0:0
#13 0x00000000000254a1 /data/app/com.myapp-1/lib/arm/libflutter.so
??
??:0:0
#14 0x0000000000016f17 /system/lib/libc.so (__pthread_start(void*)+30)
#15 0x0000000000014f4b /system/lib/libc.so (__start_thread+6)

```

## Info And Logs

<details>

**flutter run --verbose results:**

```
[  +36 ms] executing: [/Users/singun/Library/Flutter/sdk/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[  +67 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[        ] 9f5ff2306bb3e30b2b98eee79cd231b1336f41f4
[        ] executing: [/Users/singun/Library/Flutter/sdk/] git describe --match v*.*.* --first-parent --long --tags
[ +100 ms] Exit code 0 from: git describe --match v*.*.* --first-parent --long --tags
[   +3 ms] v1.12.13+hotfix.7-0-g9f5ff2306
[  +10 ms] executing: [/Users/singun/Library/Flutter/sdk/] git rev-parse --abbrev-ref --symbolic @{u}
[  +11 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/stable
[        ] executing: [/Users/singun/Library/Flutter/sdk/] git ls-remote --get-url origin
[  +18 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[+9674 ms] executing: [/Users/singun/Library/Flutter/sdk/] git rev-parse --abbrev-ref HEAD
[  +10 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] stable
[   +6 ms] executing: sw_vers -productName
[  +27 ms] Exit code 0 from: sw_vers -productName
[        ] Mac OS X
[        ] executing: sw_vers -productVersion
[  +16 ms] Exit code 0 from: sw_vers -productVersion
[        ] 10.15.3
[        ] executing: sw_vers -buildVersion
[  +21 ms] Exit code 0 from: sw_vers -buildVersion
[        ] 19D76
[  +32 ms] executing: /usr/bin/xcode-select --print-path
[   +9 ms] Exit code 0 from: /usr/bin/xcode-select --print-path
[        ] /Applications/Xcode.app/Contents/Developer
[   +3 ms] executing: /usr/bin/xcodebuild -version
[+1626 ms] Exit code 0 from: /usr/bin/xcodebuild -version
[        ] Xcode 11.3.1
           Build version 11C504
[ +101 ms] executing: /Users/singun/Library/Android/sdk/platform-tools/adb devices -l
[   +8 ms] Exit code 0 from: /Users/singun/Library/Android/sdk/platform-tools/adb devices -l
[        ] List of devices attached
[  +16 ms] executing: /Users/singun/Library/Flutter/sdk/bin/cache/artifacts/libimobiledevice/idevice_id -h
[  +53 ms] /usr/bin/xcrun simctl list --json devices
[ +138 ms] No supported devices connected.
[  +10 ms] "flutter run" took 2,082ms.

#0      throwToolExit (package:flutter_tools/src/base/common.dart:28:3)
#1      RunCommand.validateCommand (package:flutter_tools/src/commands/run.dart:289:7)
<asynchronous suspension>
#2      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:590:11)
#3      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:515:33)
<asynchronous suspension>
#4      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:146:29)
#5      _rootRun (dart:async/zone.dart:1126:13)
#6      _CustomZone.run (dart:async/zone.dart:1023:19)
#7      _runZoned (dart:async/zone.dart:1518:10)
#8      runZoned (dart:async/zone.dart:1465:12)
#9      AppContext.run (package:flutter_tools/src/base/context.dart:145:18)
#10     FlutterCommand.run (package:flutter_tools/src/runner/flutter_command.dart:505:20)
#11     CommandRunner.runCommand (package:args/command_runner.dart:197:27)
#12     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:413:21)
<asynchronous suspension>
#13     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:146:29)
#14     _rootRun (dart:async/zone.dart:1126:13)
#15     _CustomZone.run (dart:async/zone.dart:1023:19)
#16     _runZoned (dart:async/zone.dart:1518:10)
#17     runZoned (dart:async/zone.dart:1465:12)
#18     AppContext.run (package:flutter_tools/src/base/context.dart:145:18)
#19     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:364:19)
#20     CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:112:25)
#21     new Future.sync (dart:async/future.dart:224:31)
#22     CommandRunner.run (package:args/command_runner.dart:112:14)
#23     FlutterCommandRunner.run (package:flutter_tools/src/runner/flutter_command_runner.dart:250:18)
#24     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:63:22)
#25     _rootRun (dart:async/zone.dart:1126:13)
#26     _CustomZone.run (dart:async/zone.dart:1023:19)
#27     _runZoned (dart:async/zone.dart:1518:10)
#28     runZoned (dart:async/zone.dart:1502:12)
#29     run.<anonymous closure> (package:flutter_tools/runner.dart:61:18)
<asynchronous suspension>
#30     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:146:29)
#31     _rootRun (dart:async/zone.dart:1126:13)
#32     _CustomZone.run (dart:async/zone.dart:1023:19)
#33     _runZoned (dart:async/zone.dart:1518:10)
#34     runZoned (dart:async/zone.dart:1465:12)
#35     AppContext.run (package:flutter_tools/src/base/context.dart:145:18)
#36     runInContext (package:flutter_tools/src/context_runner.dart:64:24)
#37     run (package:flutter_tools/runner.dart:50:10)
#38     main (package:flutter_tools/executable.dart:65:9)
#39     main (file:///Users/singun/Library/Flutter/sdk/packages/flutter_tools/bin/flutter_tools.dart:8:3)
#40     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:305:32)
#41     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:174:12)
```

**flutter analyze results:**

no error

**flutter doctor -v results:**

```
[✓] Flutter (Channel stable, v1.12.13+hotfix.7, on Mac OS X 10.15.3 19D76, locale zh-Hans-CN)
    • Flutter version 1.12.13+hotfix.7 at /Users/singun/Library/Flutter/sdk
    • Framework revision 9f5ff2306b (13 days ago), 2020-01-26 22:38:26 -0800
    • Engine revision a67792536c
    • Dart version 2.7.0

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/singun/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • ANDROID_HOME = /Users/singun/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.3.1, Build version 11C504
    • CocoaPods version 1.8.4

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 43.0.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] VS Code (version 1.27.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 2.21.1

[!] Connected device
    ! No devices available

! Doctor found issues in 1 category.
```

</details>

**Comment by singun-lxd** [comment]
Unlike other crashes, this crash mostly occurred in Android 4/5 Devices according to Firebase Crashlytics:
Android 4：49%
Android 5：48%
Android 6：1%
Android 7：<1%
Other：1%
And it's not found with flutter 1.9.1 hotfix6, only with flutter 1.12.13

**Comment by Mapk26** [comment]
The same crash reported on Google Play.

I confirm that this occurs with flutter 1.12.13 hotfix 7, no errors reported with 1.9.1 hotfix 6
device affected: Android 5.1 - Samsung Galaxy Grand Prime

**Comment by singun-lxd** [comment]
Anyone can help?

**Comment by JimvanKleef** [comment]
We also face this crash on Android Version 5-9 since we updated flutter from 1.9.1 to 1.12.13+hotfix.7.  According to our tracking data it can crash as soon as the app is openend, but some users use the app for a few minutes and then get this crash.

**Comment by singun-lxd** [comment]
I've upgrade the engine to flutter v1.12.13+hotfix8, and this crash never happen again, about 8k users is using this app version. @Mapk26 @JimvanKleef do you try this?

**Comment by Mapk26** [comment]
Not yet, because the issue was affecting only 1 user over 10k. 
I will update to hotfix8 with the next app release

**Comment by GaryQian** [comment]
I believe hotfix 8 has included a few crash fixes for Huawei devices. I will close this now, but feel free to comment and we can reopen this if you continue to see this crash!
