### ISSUE TITLE
A GlobalKey was used multiple times inside one widget's child list.

### ISSUE THREAD

**Issue by Bhardwajraju** [flutter/flutter#50555]
```
Launching lib/main.dart on iPhone 11 in debug mode...
Running Xcode build...
Xcode build done.                                           14.0s
flutter: ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
flutter: The following assertion was thrown building IconTheme(color: Color(0xdd000000)):
flutter: 'package:flutter/src/widgets/navigator.dart': Failed assertion: line 1790 pos 12:
flutter: 'route.overlayEntries.isNotEmpty': is not true.
flutter:
flutter: Either the assertion indicates an error in the framework itself, or we should provide substantially
flutter: more information in this error message to help you determine and fix the underlying cause.
flutter: In either case, please report this assertion by filing a bug on GitHub:
flutter:   https://github.com/flutter/flutter/issues/new?template=BUG.md
flutter:
flutter: The relevant error-causing widget was:
flutter:   MaterialApp file:///Users/apple/Downloads/Flutter-Splash-Screen-Animation-master/lib/main.dart:7:3
flutter:
flutter: When the exception was thrown, this was the stack:
flutter: #2      _RouteEntry.handleAdd (package:flutter/src/widgets/navigator.dart:1790:12)
flutter: #3      NavigatorState._flushHistoryUpdates (package:flutter/src/widgets/navigator.dart:2030:17)
flutter: #4      NavigatorState.initState (package:flutter/src/widgets/navigator.dart:1968:5)
flutter: #5      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4625:58)
flutter: #6      ComponentElement.mount (package:flutter/src/widgets/framework.dart:4470:5)
flutter: ...     Normal element mounting (165 frames)
flutter: #171    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3444:14)
flutter: #172    Element.updateChild (package:flutter/src/widgets/framework.dart:3212:18)
flutter: #173    RenderObjectToWidgetElement._rebuild (package:flutter/src/widgets/binding.dart:1142:16)
flutter: #174    RenderObjectToWidgetElement.mount (package:flutter/src/widgets/binding.dart:1113:5)
flutter: #175    RenderObjectToWidgetAdapter.attachToRenderTree.<anonymous closure> (package:flutter/src/widgets/binding.dart:1055:17)
flutter: #176    BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2597:19)
flutter: #177    RenderObjectToWidgetAdapter.attachToRenderTree (package:flutter/src/widgets/binding.dart:1054:13)
flutter: #178    WidgetsBinding.attachRootWidget (package:flutter/src/widgets/binding.dart:935:7)
flutter: #179    WidgetsBinding.scheduleAttachRootWidget.<anonymous closure> (package:flutter/src/widgets/binding.dart:917:7)
flutter: (elided 13 frames from class _AssertionError, class _RawReceivePortImpl, class _Timer, dart:async, and dart:async-patch)
```

**Comment by Bhardwajraju** [comment]
When we start a New Project an older project it gives ths type of error .Plz help me

**Comment by TahaTesser** [comment]
Hi @Bhardwajraju 
Can you please provide your `flutter doctor -v`? 
Also, to better address the issue, would be helpful if you could post a minimal code sample to reproduce the problem
Thank you

**Comment by Bhardwajraju** [comment]
Thanks  for replying .I had solve the problem .

**Comment by TahaTesser** [comment]
Hi @Bhardwajraju 
Thank you for your contribution

**Comment by derzhavets** [comment]
> Thanks for replying .I had solve the problem .

So how did you solve it?
