### ISSUE TITLE
Tool crash: type 'Sentinel' is not a subtype of type 'Isolate' in type cast

### ISSUE THREAD

**Issue by jmagman** [flutter/flutter#50610]
```
2020-02-11T14:50:43.560797: stderr: type 'Sentinel' is not a subtype of type 'Isolate' in type cast
2020-02-11T14:50:43.561203: stderr: #0      FallbackDiscovery._attemptServiceConnection (package:flutter_tools/src/ios/fallback_discovery.dart:135:78)
stderr: <asynchronous suspension>
stderr: #1      FallbackDiscovery.discover (package:flutter_tools/src/ios
/fallback_discovery.dart:67:30)
stderr: #2      IOSDevice.startApp (package:flutter_tools/src/ios/devices.dart:386:52)
```
[flutter_gallery_ios32__start_up_324e20d_2.log](https://github.com/flutter/flutter/files/4189079/flutter_gallery_ios32__start_up_324e20d_2.log)

**Comment by jmagman** [comment]
\cc @jonahwilliams

**Comment by jmagman** [comment]
https://github.com/flutter/flutter/pull/49735
