### ISSUE TITLE
[tool_crash] NoSuchMethodError: The getter 'containsKey' was called on null.Receiver: nullTried calling: containsKey

### ISSUE THREAD

**Issue by XavierAnnabi** [flutter/flutter#50623]
Hi,
I have created my own package, is already published but when i try to add in application as  dependencies i get this error 

flutter packages get
dz_express: ^0.0.4

## Steps to Reproduce
1. add package in dependencies 

## Logs
NoSuchMethodError: NoSuchMethodError: The getter 'containsKey' was called on null.
Receiver: null
Tried calling: containsKey
```
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:53:5)
#1      Plugin.validatePluginYaml (package:flutter_tools/src/plugins.dart:182:16)
#2      new Plugin.fromYaml (package:flutter_tools/src/plugins.dart:75:33)
#3      _pluginFromPubspec (package:flutter_tools/src/plugins.dart:282:17)
#4      findPlugins.<anonymous closure> (package:flutter_tools/src/plugins.dart:305:27)
#5      _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:379:8)
#6      findPlugins (package:flutter_tools/src/plugins.dart:303:12)
#7      refreshPluginsList (package:flutter_tools/src/plugins.dart:784:32)
#8      FlutterProject.ensureReadyForPlatformSpecificTooling (package:flutter_tools/src/project.dart:209:5)
#9      PackagesGetCommand.runCommand (package:flutter_tools/src/commands/packages.dart:125:23)
<asynchronous suspension>
#10     FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:637:18)
#11     _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:75:64)
#12     _rootRunUnary (dart:async/zone.dart:1134:38)
#13     _CustomZone.runUnary (dart:async/zone.dart:1031:19)
#14     _FutureListener.handleValue (dart:async/future_impl.dart:140:18)
#15     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:682:45)
#16     Future._propagateToListeners (dart:async/future_impl.dart:711:32)
#17     Future._completeWithValue (dart:async/future_impl.dart:526:5)
#18     Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:556:7)
```
```
[✓] Flutter (Channel dev, v1.14.0, on Microsoft Windows [Version 10.0.17763.973], locale en-CA)
    • Flutter version 1.14.0 at C:\flutter
    • Framework revision bc6f270c58 (4 weeks ago), 2020-01-14 13:23:03 -0800
    • Engine revision fd269f60bf
    • Dart version 2.8.0 (build 2.8.0-dev.0.0 28c335d5a2)

[!] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at C:\Users\sofiane\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 28.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses

[✓] Android Studio (version 3.2)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 31.3.1
    • Dart plugin version 181.5656
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)

[✓] VS Code (version 1.42.0)
    • VS Code at C:\Users\sofiane\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.8.1

[✓] VS Code, 64-bit edition (version 1.24.1)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Flutter extension version 3.8.1

[✓] Connected device (1 available)
    • SM T800 • 32049e5f48b5c0bd • android-arm • Android 6.0.1 (API 23)

! Doctor found issues in 1 category.

```

## Flutter Application Metadata
**Version**: 1.0.0+1
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null

**Comment by jonahwilliams** [comment]
The plugin's pubspec.yaml:

https://github.com/XavierAnnabi/dz-mobil/blob/master/pubspec.yaml

**Comment by jmagman** [comment]
https://github.com/XavierAnnabi/dz-mobil/blob/master/pubspec.yaml Doesn't have "add in application as dependencies" unless I'm misunderstanding what that means?

@XavierAnnabi Can you attach the pubspec.yaml that is reproducing the crash?  Or did @jonahwilliams link to the right one?

**Comment by XavierAnnabi** [comment]
issue appears when i create Flutter Plugin with package 
using this command 
 flutter create --org com.example --template=plugin hello
with the command bellow all is correct 
 flutter create --template=package hello

Thank you for your Support

**Comment by jmagman** [comment]
@XavierAnnabi did you mean to close this?

**Comment by XavierAnnabi** [comment]
> @XavierAnnabi did you mean to close this?

yes i have closed the package works well with this command flutter create --template=package MyPackage

**Comment by jmagman** [comment]
Keeping open, the tool shouldn't crash.  Thanks!

**Comment by jmagman** [comment]
Fixed the tool crash with https://github.com/flutter/flutter/pull/51503, but the pubspec.yaml at https://github.com/XavierAnnabi/dz-mobil/blob/master/pubspec.yaml isn't correct and needs to be updated with the platforms it supports.  See https://flutter.dev/docs/development/packages-and-plugins/developing-packages#plugin-platforms

**Comment by XavierAnnabi** [comment]
Thank you so much 👍 -)
