### ISSUE TITLE
"flutter run" targeting iOS crashed: SocketException: Connection failed (OS Error: Host is down, errno = 64) at AzureDetector.isRunningOnAzure

### ISSUE THREAD

**Issue by jmagman** [flutter/flutter#50620]
```
$ flutter run --debug -d 649FAD2A-91B9-4B25-BD8C-C95039241A40 
Unhandled exception:
SocketException: Connection failed (OS Error: Host is down, errno = 64), address = 169.254.169.254, port = 80
#0      AzureDetector.isRunningOnAzure (package:flutter_tools/src/base/bot_detector.dart:91:41)
<asynchronous suspension>
#1      BotDetector.isRunningOnBot (package:flutter_tools/src/base/bot_detector.dart:66:31)
#2      isRunningOnBot (package:flutter_tools/src/globals.dart:77:48)
#3      run (package:flutter_tools/runner.dart:38:36)
#4      main (package:flutter_tools/executable.dart:67:9)
#5      main (file:///Users/m/Projects/flutter/packages/flutter_tools/bin/flutter_tools.dart:8:3)
#6      _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:299:32)
#7      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:168:12)
```

```
$ flutter doctor -v                                           
[✓] Flutter (Channel master, v1.15.4-pre.16, on Mac OS X 10.15.2 19C57, locale en-US)
    • Flutter version 1.15.4-pre.16 at /Users/m/Projects/flutter
    • Framework revision bfbb347682 (3 hours ago), 2020-02-11 15:53:02 -0800
    • Engine revision e4f46f32f1
    • Dart version 2.8.0 (build 2.8.0-dev.8.0 fd992e423e)

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/m/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.4)
    • Xcode at /Users/m/Applications/Xcode-11-4-beta.app/Contents/Developer
    • Xcode 11.4, Build version 11N111s
    • CocoaPods version 1.8.4

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 42.1.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] VS Code (version 1.41.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.7.1

[✓] Connected device (2 available)
    • Jenn’s iPhone • d83d5bc53967baa0ee18626ba87b6254b2ab5418 • ios • iOS 13.4
    • iPhone 8 Plus • 649FAD2A-91B9-4B25-BD8C-C95039241A40     • ios • com.apple.CoreSimulator.SimRuntime.iOS-13-4 (simulator)
```

**Comment by jmagman** [comment]
https://github.com/flutter/flutter/pull/50579
\cc @zanderso

**Comment by zanderso** [comment]
Fixed in reland.

**Comment by hemantthakare** [comment]
Can anyone help me, When i  try to call rest API  facing below issue on iOS simulator
**SocketException: Connection failed, address = --------amazonaws.com, port = 9001**


Till yesterday it is working fine for both platforms Android and iOS. But now it is only working on android.
