### ISSUE TITLE
flutter engine crash

### ISSUE THREAD

**Issue by luckv** [flutter/flutter#50630]
I've found an engine crash collected from Google Play console, I did not know how to reproduce it. 
The crash happens only on published android apps.

## Raw stack
Play Console give me only these informations.
```
 *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
 pid: 0, tid: 0 >>> com.myapp <<<

backtrace:
  #00  pc 0000000000083360  /apex/com.android.runtime/lib64/bionic/libc.so (abort+176)
  #01  pc 000000000001e924  /data/app/com.myapp-7X1E96lF8amHAIAaEmY_lw==/split_config.arm64_v8a.apk
```

## flutter logs
```
E/flutter (29851): [ERROR:flutter/shell/platform/android/platform_view_android_jni.cc(39)] java.lang.AssertionError: java.lang.NoSuchFieldException: Drawable
E/flutter (29851):      at c.f.b.b.a.ja$a.<init>(Unknown Source:87)
E/flutter (29851):      at c.f.b.b.a.V.a(Unknown Source:29)
E/flutter (29851):      at c.f.b.p.a(Unknown Source:74)
E/flutter (29851):      at c.f.b.b.a.p.a(Unknown Source:42)
E/flutter (29851):      at c.f.b.b.a.p.a(Unknown Source:122)
E/flutter (29851):      at c.f.b.b.a.p.a(Unknown Source:22)
E/flutter (29851):      at c.f.b.p.a(Unknown Source:74)
E/flutter (29851):      at c.f.b.b.a.c.a(Unknown Source:26)
E/flutter (29851):      at c.f.b.p.a(Unknown Source:74)
E/flutter (29851):      at c.f.b.p.a(Unknown Source:16)
E/flutter (29851):      at c.f.b.p.a(Unknown Source:4)
E/flutter (29851):      at c.f.b.p.a(Unknown Source:9)
E/flutter (29851):      at c.c.a.d.d(Unknown Source:32)
E/flutter (29851):      at c.c.a.d.a(Unknown Source:0)
E/flutter (29851):      at c.c.a.d.a(Unknown Source:41)
E/flutter (29851):      at c.c.a.d.b(Unknown Source:6)
E/flutter (29851):      at c.c.a.d.a(Unknown Source:129)
E/flutter (29851):      at d.b.b.a.o$a.a(Unknown Source:17)
E/flutter (29851):      at io.flutter.embedding.engine.a.c.a(Unknown Source:57)
E/flutter (29851):      at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(Unknown Source:4)
E/flutter (29851):      at android.os.MessageQueue.nativePollOnce(Native Method)
E/flutter (29851):      at android.os.MessageQueue.next(MessageQueue.java:326)
E/flutter (29851):      at android.os.Looper.loop(Looper.java:181)
E/flutter (29851):      at android.app.ActivityThread.main(ActivityThread.java:7081)
E/flutter (29851):      at java.lang.reflect.Method.invoke(Native Method)
E/flutter (29851):      at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
E/flutter (29851):      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:965)
E/flutter (29851): Caused by: java.lang.NoSuchFieldException: Drawable
E/flutter (29851):      at java.lang.Class.getField(Class.java:1601)
E/flutter (29851):      at c.f.b.b.a.ja$a.<init>(Unknown Source:34)
E/flutter (29851):      ... 26 more
E/flutter (29851): 
F/flutter (29851): [FATAL:flutter/shell/platform/android/platform_view_android_jni.cc(76)] Check failed: CheckException(env). 
```

## Flutter doctor
```
[✓] Flutter (Channel stable, v1.12.13+hotfix.8, on Mac OS X 10.14.6 18G2022, locale en-GB)
    • Flutter version 1.12.13+hotfix.8 at /Users/minnovi/Documents/flutter
    • Framework revision 0b8abb4724 (13 hours ago), 2020-02-11 11:44:36 -0800
    • Engine revision e1e6ced81d
    • Dart version 2.7.0

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/minnovi/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.3.1, Build version 11C504
    • CocoaPods version 1.7.5

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 42.1.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] Connected device (1 available)
    • SM J600FN • 5200a730436626c1 • android-arm • Android 9 (API 28)

• No issues found!
```

**Comment by TahaTesser** [comment]
Could be related [#50438](https://github.com/flutter/flutter/issues/50438) [#50429](https://github.com/flutter/flutter/issues/50429)

**Comment by chinmaygarde** [comment]
This appears to be an uncaught exception when a platform message was delivered from a Flutter application to the underlying platform. Either a plugin or the applications Java code needs to be audited to figure out where this exception was thrown. The first step would be to de-obfuscate the stack trace. Since stack traces are missing or obfuscated and there are no reproducible reduced test cases, no progress can be made on this issue for now.
