### ISSUE TITLE
Flutter google sign in and firebase realtime lead to ios app crash

### ISSUE THREAD

**Issue by Charonnnnn** [flutter/flutter#50632]
## Steps to Reproduce

1. All file and configuration are completely setup (https://pub.dev/packages/google_sign_in#-readme-tab-)
2. The code with issue as follows: 
```
  Future googleLogin() async {
    final googleSignIn = GoogleSignIn(scopes: ['email']);

    googleSignIn.onCurrentUserChanged.listen((account) async {
      final email = account.email;
      final name = account.displayName;
      final photoUrl = account.photoUrl;

      print("Google login success! email = $email, name = $name, photoUrl = $photoUrl");
      
     // ------------------- ISSUE start ----------------------
      var psid;
      databaseReference.child('app_logins/'+email).once().then((DataSnapshot snapshot) async {
        var data = snapshot.value;
        print(data);
        if (data==null){
          psid = await genPsid();
          print(psid);
          databaseReference.child('app_logins/'+email).set({
            'user_email': email,
            'user_name': name,
            'user_photoUrl': photoUrl,
            'platform': "google",
            'psid': psid,
          });
        }else{
          psid = data['psid'];
          print(psid);
        }
      });
   // ------------------- ISSUE end ----------------------
      Navigator.of(context).pushNamedAndRemoveUntil('/home', (x) => !x.isCurrent);
    });

    try {
      await googleSignIn.signIn();
    } catch (error) {
      print(error);
    }
  }
```
3.1 flutter run the app on iOS
4.1 After sign in google account, the ios app crash (Without ISSUE Code, then it is fine)

3.2  flutter run the app on Android
4.2 After sign in google account, Error message display (with or without ISSUE Code)

**IOS: Log on xcode:** 

<details>
  <summary>Logs</summary>

```
2020-02-12 17:16:45.434037+0800 Runner[49908:4722703] <Warning>: Please set a value for FacebookAutoLogAppEventsEnabled. Set the flag to TRUE if you want to collect app install, app launch and in-app purchase events automatically. To request user consent before collecting data, set the flag value to FALSE, then change to TRUE once user consent is received. Learn more: https://developers.facebook.com/docs/app-events/getting-started-app-events-ios#disable-auto-events.
2020-02-12 17:16:45.434254+0800 Runner[49908:4722703] <Warning>: You haven't set a value for FacebookAdvertiserIDCollectionEnabled. Set the flag to TRUE if you want to collect Advertiser ID for better advertising and analytics results. To request user consent before collecting data, set the flag value to FALSE, then change to TRUE once user consent is received. Learn more: https://developers.facebook.com/docs/app-events/getting-started-app-events-ios#disable-auto-events.
2020-02-12 17:16:46.340420+0800 Runner[49908:4722703] Configuring the default Firebase app...
2020-02-12 17:16:46.341970+0800 Runner[49908:4723021] 6.17.0 - [Firebase/Core][I-COR000004] App with name __FIRAPP_DEFAULT does not exist.
2020-02-12 17:16:46.373646+0800 Runner[49908:4722703] Configured the default Firebase app __FIRAPP_DEFAULT.
2020-02-12 17:16:46.403697+0800 Runner[49908:4722703] FBSDKLog: Unable to obtain a key window, marking <UIWindow: 0x7fd8fdc120b0; frame = (0 0; 414 896); hidden = YES; gestureRecognizers = <NSArray: 0x600000bfc1b0>; layer = <UIWindowLayer: 0x6000005b76e0>> as keyWindow
2020-02-12 17:16:46.434632+0800 Runner[49908:4723093] flutter: Observatory listening on http://127.0.0.1:61708/jvgyo-P4h6A=/
2020-02-12 17:16:46.465993+0800 Runner[49908:4723106] 6.17.0 - [Firebase/Analytics][I-ACS025028] AdMob and Firebase are in use in this app, but are not linked. For analytics data consistency and integrity, it is highly recommended that you link your AdMob app to the corresponding Firebase app and re-download the GoogleServices-Info.plist file. See https://support.google.com/admob/answer/6383165 for more information.
2020-02-12 17:16:46.466392+0800 Runner[49908:4723106] 6.17.0 - [Firebase/Analytics][I-ACS023007] Analytics v.60202000 started
2020-02-12 17:16:46.466816+0800 Runner[49908:4723106] 6.17.0 - [Firebase/Analytics][I-ACS023008] To enable debug logging set the following application argument: -FIRAnalyticsDebugEnabled (see http://goo.gl/RfcP7r)
2020-02-12 17:16:46.468183+0800 Runner[49908:4723106] 6.17.0 - [Firebase/Analytics][I-ACS031025] Analytics screen reporting is enabled. Call +[FIRAnalytics setScreenName:setScreenClass:] to set the screen name or override the default screen class name. To disable screen reporting, set the flag FirebaseScreenReportingEnabled to NO (boolean) in the Info.plist
2020-02-12 17:16:46.885904+0800 Runner[49908:4723035] 6.17.0 - [Firebase/Analytics][I-ACS025026] Deferring to Firebase for event data collection
2020-02-12 17:16:46.887734+0800 Runner[49908:4723021] [Client] Synchronous remote object proxy returned error: Error Domain=NSCocoaErrorDomain Code=4099 "The connection to service on pid 0 named com.apple.commcenter.coretelephony.xpc was invalidated." UserInfo={NSDebugDescription=The connection to service on pid 0 named com.apple.commcenter.coretelephony.xpc was invalidated.}
2020-02-12 17:16:46.887778+0800 Runner[49908:4723036] [Client] Updating selectors failed with: Error Domain=NSCocoaErrorDomain Code=4099 "The connection to service on pid 0 named com.apple.commcenter.coretelephony.xpc was invalidated." UserInfo={NSDebugDescription=The connection to service on pid 0 named com.apple.commcenter.coretelephony.xpc was invalidated.}
2020-02-12 17:16:46.887995+0800 Runner[49908:4723036] [Client] Updating selectors after delegate addition failed with: Error Domain=NSCocoaErrorDomain Code=4099 "The connection to service on pid 0 named com.apple.commcenter.coretelephony.xpc was invalidated." UserInfo={NSDebugDescription=The connection to service on pid 0 named com.apple.commcenter.coretelephony.xpc was invalidated.}
2020-02-12 17:16:46.888711+0800 Runner[49908:4723021] [Client] Synchronous remote object proxy returned error: Error Domain=NSCocoaErrorDomain Code=4099 "The connection to service on pid 0 named com.apple.commcenter.coretelephony.xpc was invalidated." UserInfo={NSDebugDescription=The connection to service on pid 0 named com.apple.commcenter.coretelephony.xpc was invalidated.}
2020-02-12 17:16:46.888800+0800 Runner[49908:4723036] [Client] Updating selectors failed with: Error Domain=NSCocoaErrorDomain Code=4099 "The connection to service on pid 0 named com.apple.commcenter.coretelephony.xpc was invalidated." UserInfo={NSDebugDescription=The connection to service on pid 0 named com.apple.commcenter.coretelephony.xpc was invalidated.}
2020-02-12 17:16:46.892303+0800 Runner[49908:4723021] [Client] Synchronous remote object proxy returned error: Error Domain=NSCocoaErrorDomain Code=4099 "The connection to service on pid 0 named com.apple.commcenter.coretelephony.xpc was invalidated." UserInfo={NSDebugDescription=The connection to service on pid 0 named com.apple.commcenter.coretelephony.xpc was invalidated.}
2020-02-12 17:16:46.892433+0800 Runner[49908:4723107] [Client] Updating selectors failed with: Error Domain=NSCocoaErrorDomain Code=4099 "The connection to service on pid 0 named com.apple.commcenter.coretelephony.xpc was invalidated." UserInfo={NSDebugDescription=The connection to service on pid 0 named com.apple.commcenter.coretelephony.xpc was invalidated.}
2020-02-12 17:16:47.175761+0800 Runner[49908:4723036] 6.17.0 - [Firebase/Analytics][I-ACS023012] Analytics collection enabled
2020-02-12 17:16:48.251273+0800 Runner[49908:4722703] [plugin] AddInstanceForFactory: No factory registered for id <CFUUID 0x60000050ea40> F8BB1C28-BAE8-11D6-9C31-00039315CD46
2020-02-12 17:17:01.717180+0800 Runner[49908:4723122] [AXRuntimeCommon] Unknown client: Runner
2020-02-12 17:17:13.187917+0800 Runner[49908:4723075] flutter: charonkwok922@gmail.com
2020-02-12 17:17:13.223608+0800 Runner[49908:4722703] *** Terminating app due to uncaught exception 'InvalidPathValidation', reason: '(child:) Must be a non-empty string and not contain '.' '#' '$' '[' or ']''
*** First throw call stack:
(
	0   CoreFoundation                      0x00007fff23c7127e __exceptionPreprocess + 350
	1   libobjc.A.dylib                     0x00007fff513fbb20 objc_exception_throw + 48
	2   Runner                              0x000000010f832868 +[FValidation validateFrom:validPathString:] + 248
	3   Runner                              0x000000010f832a64 +[FValidation validateFrom:validRootPathString:] + 468
	4   Runner                              0x000000010f7c107d -[FIRDatabaseReference child:] + 189
	5   Runner                              0x000000010f9186bb getReference + 203
	6   Runner                              0x000000010f918793 getDatabaseQuery + 83
	7   Runner                              0x000000010f91b4cb -[FLTFirebaseDatabasePlugin handleMethodCall:result:] + 7099
	8   Flutter                             0x00000001105b5db5 __45-[FlutterMethodChannel setMethodCallHandler:]_block_invoke + 104
	9   Flutter                             0x0000000110549ba0 _ZNK7flutter21PlatformMessageRouter21HandlePlatformMessageEN3fml6RefPtrINS_15PlatformMessageEEE + 166
	10  Flutter                             0x000000011054d64e _ZN7flutter15PlatformViewIOS21HandlePlatformMessageEN3fml6RefPtrINS_15PlatformMessageEEE + 38
	11  Flutter                             0x00000001105af969 _ZNSt3__110__function6__funcIZN7flutter5Shell29OnEngineHandlePlatformMessageEN3fml6RefPtrINS2_15PlatformMessageEEEE4$_32NS_9allocatorIS8_EEFvvEEclEv + 57
	12  Flutter                             0x000000011055cb73 _ZN3fml15MessageLoopImpl10FlushTasksENS_9FlushTypeE + 117
	13  Flutter                             0x00000001105618b8 _ZN3fml17MessageLoopDarwin11OnTimerFireEP16__CFRunLoopTimerPS0_ + 26
	14  CoreFoundation                      0x00007fff23bd4b94 __CFRUNLOOP_IS_CALLING_OUT_TO_A_TIMER_CALLBACK_FUNCTION__ + 20
	15  CoreFoundation                      0x00007fff23bd4882 __CFRunLoopDoTimer + 1026
	16  CoreFoundation                      0x00007fff23bd3eda __CFRunLoopDoTimers + 266
	17  CoreFoundation                      0x00007fff23bcec4e __CFRunLoopRun + 2238
	18  CoreFoundation                      0x00007fff23bce066 CFRunLoopRunSpecific + 438
	19  GraphicsServices                    0x00007fff384c0bb0 GSEventRunModal + 65
	20  UIKitCore                           0x00007fff48092d4d UIApplicationMain + 1621
	21  Runner                              0x000000010f6326d0 main + 112
	22  libdyld.dylib                       0x00007fff5227ec25 start + 1
)
libc++abi.dylib: terminating with uncaught exception of type NSException
(lldb) 
```

</details>

**Android: Logs:** 

<details>
  <summary>Logs</summary>

```
E/flutter (13960): [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: PlatformException(sign_in_failed, com.google.android.gms.common.api.ApiException: 10: , null)
E/flutter (13960): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:569:7)
E/flutter (13960): #1      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:321:33)
E/flutter (13960): <asynchronous suspension>
E/flutter (13960): #2      MethodChannel.invokeMapMethod (package:flutter/src/services/platform_channel.dart:349:48)
E/flutter (13960): #3      MethodChannelGoogleSignIn.signIn (package:google_sign_in_platform_interface/src/method_channel_google_sign_in.dart:45:10)
E/flutter (13960): #4      GoogleSignIn._callMethod (package:google_sign_in/google_sign_in.dart:227:42)
E/flutter (13960): <asynchronous suspension>
E/flutter (13960): #5      GoogleSignIn._addMethodCall (package:google_sign_in/google_sign_in.dart:282:18)
E/flutter (13960): #6      GoogleSignIn.signIn (package:google_sign_in/google_sign_in.dart:352:9)
E/flutter (13960): #7      _LoginPageState.googleLogin (package:areix/screens/auth/login.dart:338:72)
E/flutter (13960): #8      _LoginPageState.build.<anonymous closure> (package:areix/screens/auth/login.dart:150:27)
E/flutter (13960): #9      _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:706:14)
E/flutter (13960): #10     _InkResponseState.build.<anonymous closure> (package:flutter/src/material/ink_well.dart:789:36)
E/flutter (13960): #11     GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:182:24)
E/flutter (13960): #12     TapGestureRecognizer.handleTapUp (package:flutter/src/gestures/tap.dart:486:11)
E/flutter (13960): #13     BaseTapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:264:5)
E/flutter (13960): #14     BaseTapGestureRecognizer.handlePrimaryPointer (package:flutter/src/gestures/tap.dart:199:7)
E/flutter (13960): #15     PrimaryPointerGestureRecognizer.handleEvent (package:flutter/src/gestures/recognizer.dart:467:9)
E/flutter (13960): #16     PointerRouter._dispatch (package:flutter/src/gestures/pointer_router.dart:76:12)
E/flutter (13960): #17     PointerRouter._dispatchEventToRoutes.<anonymous closure> (package:flutter/src/gestures/pointer_router.dart:117:9)
E/flutter (13960): #18     _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:379:8)
E/flutter (13960): #19     PointerRouter._dispatchEventToRoutes (package:flutter/src/gestures/pointer_router.dart:115:18)
E/flutter (13960): #20     PointerRouter.route (package:flutter/src/gestures/pointer_router.dart:101:7)
E/flutter (13960): #21     GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:218:19)
E/flutter (13960): #22     GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:198:22)
E/flutter (13960): #23     GestureBinding._handlePointerEvent (package:flutter/src/gestures/binding.dart:156:7)
E/flutter (13960): #24     GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:102:7)
E/flutter (13960): #25     GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:86:7)
E/flutter (13960): #26     _rootRunUnary (dart:async/zone.dart:1138:13)
E/flutter (13960): #27     _CustomZone.runUnary (dart:async/zone.dart:1031:19)
E/flutter (13960): #28     _CustomZone.runUnaryGuarded (dart:async/zone.dart:933:7)
E/flutter (13960): #29     _invoke1 (dart:ui/hooks.dart:273:10)
E/flutter (13960): #30     _dispatchPointerDataPacket (dart:ui/hooks.dart:182:5)
E/flutter (13960): 
```

</details>

**flutter doctor -v**
<details>
  <summary>Logs</summary>

```
✓] Flutter (Channel stable, v1.12.13+hotfix.7, on Mac OS X 10.15.2 19C57, locale en-HK)
    • Flutter version 1.12.13+hotfix.7 at /Applications/flutter
    • Framework revision 9f5ff2306b (2 weeks ago), 2020-01-26 22:38:26 -0800
    • Engine revision a67792536c
    • Dart version 2.7.0

 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/charon/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.3, Build version 11C29
    • CocoaPods version 1.8.4

[✓] Android Studio (version 3.4)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 35.3.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

[✓] VS Code (version 1.41.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.8.0

[✓] Connected device (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 9 (API 28) (emulator)

    • No issues found!

```

</details>

**Comment by TahaTesser** [comment]
Hi @Charonnnnn 
Please follow this [Solution](https://stackoverflow.com/a/54696963)
Closing as this isn't an issue with Flutter itself. 
Thank you for contribution
