### ISSUE TITLE
Runner/GeneratedPluginRegistrant.m normal armv7 objective-c com.apple.compilers.llvm.clang.1_0.compiler

### ISSUE THREAD

**Issue by kecson** [flutter/flutter#50642]
#### build iOS archive error:
```shell
xcodebuild -scheme Runner -archivePath Runner.xcarchive -sdk iphoneos  archive -UseModernBuildSystem=NO
```

#### error message:
```
...
/Users/cks/Android/studio_project/flutter_project/ioclient/ios/Runner/GeneratedPluginRegistrant.m -o /Users/cks/Library/Developer/Xcode/DerivedData/Runner-asuwptrwelirgzbzuhmtvjnehwhh/ArchiveIntermediates/Runner/IntermediateBuildFilesPath/Runner.build/Release-iphoneos/Runner.build/Objects-normal/arm64/GeneratedPluginRegistrant.o
/Users/cks/Android/studio_project/flutter_project/ioclient/ios/Runner/GeneratedPluginRegistrant.m:10:9: fatal error: module 'connectivity' not found
@import connectivity;
 ~~~~~~~^~~~~~~~~~~~
1 error generated.
...

** ARCHIVE FAILED **


The following build commands failed:
        CompileC /Users/cks/Library/Developer/Xcode/DerivedData/Runner-asuwptrwelirgzbzuhmtvjnehwhh/ArchiveIntermediates/Runner/IntermediateBuildFilesPath/Runner.build/Release-iphoneos/Runner.build/Objects-normal/armv7/GeneratedPluginRegistrant.o Runner/GeneratedPluginRegistrant.m normal armv7 objective-c com.apple.compilers.llvm.clang.1_0.compiler
        CompileC /Users/cks/Library/Developer/Xcode/DerivedData/Runner-asuwptrwelirgzbzuhmtvjnehwhh/ArchiveIntermediates/Runner/IntermediateBuildFilesPath/Runner.build/Release-iphoneos/Runner.build/Objects-normal/arm64/GeneratedPluginRegistrant.o Runner/GeneratedPluginRegistrant.m normal arm64 objective-c com.apple.compilers.llvm.clang.1_0.compiler
(2 failures)

```

**Comment by iapicca** [comment]
Hi @kecson 
can you please describe the issue more in detail
and provide your `flutter doctor -v` ,
your `flutter run --verbose` 
and if possible a reproducible minimal code sample.
Thank you

**Comment by kecson** [comment]
> Hi @kecson
> can you please describe the issue more in detail
> and provide your `flutter doctor -v` ,
> your `flutter run --verbose`
> and if possible a reproducible minimal code sample.
> Thank you

~  ➜  flutter doctor -v
[✓] Flutter (Channel stable, v1.12.13+hotfix.7, on Mac OS X 10.15.3 19D76, locale zh-Hans-CN)
    • Flutter version 1.12.13+hotfix.7 at /Users/cks/android/flutter/flutter
    • Framework revision 9f5ff2306b (2 weeks ago), 2020-01-26 22:38:26 -0800
    • Engine revision a67792536c
    • Dart version 2.7.0

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/cks/android/android-sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.3
    • ANDROID_HOME = /Users/cks/android/android-sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.3.1, Build version 11C504
    • CocoaPods version 1.8.4

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 43.0.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] Connected device (2 available)
    • MI 6    • ********                                 • android-arm64 • Android 9 (API 28)


• No issues found!

**Comment by kecson** [comment]
> Hi @kecson
> can you please describe the issue more in detail
> and provide your `flutter doctor -v` ,
> your `flutter run --verbose`
> and if possible a reproducible minimal code sample.
> Thank you

I include this : in pubspec.yaml 
```
connectivity: ^0.4.6+1
```

catch error when:
```
 flutter run --verbose
```

```
[ +428 ms] error: process launch failed: failed to get the task for process 1758
[        ] (lldb)     safequit
[  +70 ms] Could not install build/ios/iphoneos/Runner.app on 7190d3440a19c17c0636b61bd1731e3e9c391973.
[   +1 ms] Try launching Xcode and selecting "Product > Run" to fix the problem:
[        ]   open ios/Runner.xcworkspace
[        ] Installing and launching... (completed in 26.9s)
[        ] Error launching application on c的 iPad.
[   +3 ms] "flutter run" took 72,429ms.

#0      throwToolExit (package:flutter_tools/src/base/common.dart:28:3)
#1      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:509:7)
<asynchronous suspension>
#2      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:615:18)
#3      _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:73:64)
#4      _rootRunUnary (dart:async/zone.dart:1134:38)
#5      _CustomZone.runUnary (dart:async/zone.dart:1031:19)
#6      _FutureListener.handleValue (dart:async/future_impl.dart:139:18)
#7      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:680:45)
#8      Future._propagateToListeners (dart:async/future_impl.dart:709:32)
#9      Future._completeWithValue (dart:async/future_impl.dart:524:5)
#10     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:32:15)
#11     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:290:13)
#12     RunCommand.usageValues (package:flutter_tools/src/commands/run.dart)
#13     _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:73:64)
#14     _rootRunUnary (dart:async/zone.dart:1134:38)
#15     _CustomZone.runUnary (dart:async/zone.dart:1031:19)
#16     _FutureListener.handleValue (dart:async/future_impl.dart:139:18)
#17     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:680:45)
#18     Future._propagateToListeners (dart:async/future_impl.dart:709:32)
#19     Future._completeWithValue (dart:async/future_impl.dart:524:5)
#20     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:32:15)
#21     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:290:13)
#22     IosProject.isSwift (package:flutter_tools/src/project.dart)
#23     _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:73:64)
#24     _rootRunUnary (dart:async/zone.dart:1134:38)
#25     _CustomZone.runUnary (dart:async/zone.dart:1031:19)
#26     _FutureListener.handleValue (dart:async/future_impl.dart:139:18)
#27     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:680:45)
#28     Future._propagateToListeners (dart:async/future_impl.dart:709:32)
#29     Future._completeWithValue (dart:async/future_impl.dart:524:5)
#30     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:32:15)
#31     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:290:13)
#32     IosProject.buildSettings (package:flutter_tools/src/project.dart)
#33     _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:73:64)
#34     _rootRunUnary (dart:async/zone.dart:1134:38)
#35     _CustomZone.runUnary (dart:async/zone.dart:1031:19)
#36     _FutureListener.handleValue (dart:async/future_impl.dart:139:18)
#37     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:680:45)
#38     Future._propagateToListeners (dart:async/future_impl.dart:709:32)
#39     Future._completeWithValue (dart:async/future_impl.dart:524:5)
#40     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:32:15)
#41     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:290:13)
#42     XcodeProjectInterpreter.getBuildSettings (package:flutter_tools/src/ios/xcodeproj.dart)
#43     _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:73:64)
#44     _rootRunUnary (dart:async/zone.dart:1134:38)
#45     _CustomZone.runUnary (dart:async/zone.dart:1031:19)
#46     _FutureListener.handleValue (dart:async/future_impl.dart:139:18)
#47     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:680:45)
#48     Future._propagateToListeners (dart:async/future_impl.dart:709:32)
#49     Future._completeWithValue (dart:async/future_impl.dart:524:5)
#50     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:32:15)
#51     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:290:13)
#52     _DefaultProcessUtils.run (package:flutter_tools/src/base/process.dart)
#53     _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:73:64)
#54     _rootRunUnary (dart:async/zone.dart:1134:38)
#55     _CustomZone.runUnary (dart:async/zone.dart:1031:19)
#56     _FutureListener.handleValue (dart:async/future_impl.dart:139:18)
#57     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:680:45)
#58     Future._propagateToListeners (dart:async/future_impl.dart:709:32)
#59     Future._completeWithValue (dart:async/future_impl.dart:524:5)
#60     Future.wait.<anonymous closure> (dart:async/future.dart:400:22)
#61     _rootRunUnary (dart:async/zone.dart:1134:38)
#62     _CustomZone.runUnary (dart:async/zone.dart:1031:19)
#63     _FutureListener.handleValue (dart:async/future_impl.dart:139:18)
#64     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:680:45)
#65     Future._propagateToListeners (dart:async/future_impl.dart:709:32)
#66     Future._complete (dart:async/future_impl.dart:514:7)
#67     _BufferingStreamSubscription.asFuture.<anonymous closure> (dart:async/stream_impl.dart:206:14)
#68     _rootRun (dart:async/zone.dart:1122:38)
#69     _CustomZone.run (dart:async/zone.dart:1023:19)
#70     _CustomZone.runGuarded (dart:async/zone.dart:925:7)
#71     _BufferingStreamSubscription._sendDone.sendDone (dart:async/stream_impl.dart:391:13)
#72     _BufferingStreamSubscription._sendDone (dart:async/stream_impl.dart:401:15)
#73     _BufferingStreamSubscription._close (dart:async/stream_impl.dart:285:7)
#74     _SinkTransformerStreamSubscription._close (dart:async/stream_transformers.dart:98:11)
#75     _EventSinkWrapper.close (dart:async/stream_transformers.dart:25:11)
#76     _StringAdapterSink.close (dart:convert/string_conversion.dart:251:11)
#77     _Utf8ConversionSink.close (dart:convert/string_conversion.dart:302:20)
#78     _ConverterStreamEventSink.close (dart:convert/chunked_conversion.dart:82:18)
#79     _SinkTransformerStreamSubscription._handleDone (dart:async/stream_transformers.dart:143:24)
#80     _rootRun (dart:async/zone.dart:1122:38)
#81     _CustomZone.run (dart:async/zone.dart:1023:19)
#82     _CustomZone.runGuarded (dart:async/zone.dart:925:7)
#83     _BufferingStreamSubscription._sendDone.sendDone (dart:async/stream_impl.dart:391:13)
#84     _BufferingStreamSubscription._sendDone (dart:async/stream_impl.dart:401:15)
#85     _BufferingStreamSubscription._close (dart:async/stream_impl.dart:285:7)
#86     _SyncStreamControllerDispatch._sendDone (dart:async/stream_controller.dart:774:19)
#87     _StreamController._closeUnchecked (dart:async/stream_controller.dart:631:7)
#88     _StreamController.close (dart:async/stream_controller.dart:624:5)
#89     _Socket._onData (dart:io-patch/socket_patch.dart:1838:21)
#90     _rootRunUnary (dart:async/zone.dart:1138:13)
#91     _CustomZone.runUnary (dart:async/zone.dart:1031:19)
#92     _CustomZone.runUnaryGuarded (dart:async/zone.dart:933:7)
#93     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:338:11)
#94     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:265:7)
#95     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:766:19)
#96     _StreamController._add (dart:async/stream_controller.dart:642:7)
#97     _StreamController.add (dart:async/stream_controller.dart:588:5)
#98     new _RawSocket.<anonymous closure> (dart:io-patch/socket_patch.dart:1386:35)
#99     _NativeSocket.issueReadEvent.issue (dart:io-patch/socket_patch.dart:892:18)
#100    _microtaskLoop (dart:async/schedule_microtask.dart:43:21)
#101    _startMicrotaskLoop (dart:async/schedule_microtask.dart:52:5)
#102    _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
#103    _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:175:5)



```

**Comment by VladyslavBondarenko** [comment]
@kecson 
Can you confirm you are working out of Runner.xcworkspace and NOT Runner.xcodeproj?

**Comment by kecson** [comment]
> @kecson
> Can you confirm you are working out of Runner.xcworkspace and NOT Runner.xcodeproj?

yes. It is success in Xcode.

```
Xcode -> Product->archive
```

**Comment by jmagman** [comment]
Your command is missing `-workspace Runner.xcworkspace`.  Closing.

**Comment by bionara** [comment]
I'm getting this same error -any ideas? 


`Automatically signing iOS for device deployment using specified development team in Xcode project: 4HK2FQ63K7
Running pod install...                                              3.0s
Running Xcode build...                                                  
                                                   
 └─Compiling, linking and signing...                         2.0s
Xcode build done.                                           69.9s
Failed to build iOS app
Error output from Xcode build:
↳
    ** BUILD FAILED **


Xcode's output:
↳
    XXX/native/ios/Runner/GeneratedPluginRegistrant.m:10:9: fatal error: module 'connectivity' not found
    @import connectivity;
     ~~~~~~~^~~~~~~~~~~~
    1 error generated.
    note: Using new build system
    note: Planning build
    note: Constructing build description

Encountered error while building for device.
`

i have put the dependency in pubspec.yaml as mentioned, and no errors on flutter doctor

**Comment by iapicca** [comment]
Could everyone who still has this problem please file a new issue with the exact descriptions what happens, logs and the output of 'flutter doctor -v'  please.
All system setups can be slightly different so it's always better to open new issues and reference related issues.
