### ISSUE TITLE
[web]: flutter build web works but run -d chrome fails.

### ISSUE THREAD

**Issue by JunsikChoi** [flutter/flutter#50640]
Describe your issue and include the command you're running, flutter_web version, browser version

<details>
 <summary>flutter build web -v</summary>

```
[  +21 ms] executing: [/Users/jun/Tools/flutter/] git -c log.showSignature=false log -n
1 --pretty=format:%H
[  +34 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[        ] fabeb2a16f1d008ab8230f450c49141d35669798
[        ] executing: [/Users/jun/Tools/flutter/] git describe --match v*.*.*
--first-parent --long --tags
[   +9 ms] Exit code 0 from: git describe --match v*.*.* --first-parent --long --tags
[        ] v1.14.6-0-gfabeb2a16
[   +6 ms] executing: [/Users/jun/Tools/flutter/] git rev-parse --abbrev-ref --symbolic
@{u}
[   +6 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/beta
[        ] executing: [/Users/jun/Tools/flutter/] git ls-remote --get-url origin
[   +5 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[  +48 ms] executing: [/Users/jun/Tools/flutter/] git rev-parse --abbrev-ref HEAD
[   +6 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] beta
[   +5 ms] executing: sw_vers -productName
[  +10 ms] Exit code 0 from: sw_vers -productName
[        ] Mac OS X
[        ] executing: sw_vers -productVersion
[  +12 ms] Exit code 0 from: sw_vers -productVersion
[        ] 10.13.6
[        ] executing: sw_vers -buildVersion
[  +11 ms] Exit code 0 from: sw_vers -buildVersion
[        ] 17G66
[  +26 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping
update.
[        ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping
update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required,
skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +2 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping
update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping
update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping
update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping
update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping
update.
[  +19 ms] Artifact Instance of 'MaterialFonts' is not required, skipping update.
[        ] Artifact Instance of 'GradleWrapper' is not required, skipping update.
[        ] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping
update.
[        ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping
update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required,
skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterSdk' is not required, skipping update.
[        ] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping
update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping
update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping
update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping
update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping
update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FontSubsetArtifacts' is not required, skipping update.
[  +72 ms] Found plugin cloud_firestore at
/Users/jun/.pub-cache/hosted/pub.dartlang.org/cloud_firestore-0.13.2+1/
[   +7 ms] Found plugin cloud_firestore_web at
/Users/jun/.pub-cache/hosted/pub.dartlang.org/cloud_firestore_web-0.1.0+2/
[   +8 ms] Found plugin firebase_auth at
/Users/jun/.pub-cache/hosted/pub.dartlang.org/firebase_auth-0.15.4/
[   +4 ms] Found plugin firebase_auth_web at
/Users/jun/.pub-cache/hosted/pub.dartlang.org/firebase_auth_web-0.1.2/
[   +2 ms] Found plugin firebase_core at
/Users/jun/.pub-cache/hosted/pub.dartlang.org/firebase_core-0.4.3+3/
[   +3 ms] Found plugin firebase_core_web at
/Users/jun/.pub-cache/hosted/pub.dartlang.org/firebase_core_web-0.1.1+2/
[  +81 ms] Found plugin cloud_firestore at
/Users/jun/.pub-cache/hosted/pub.dartlang.org/cloud_firestore-0.13.2+1/
[   +3 ms] Found plugin cloud_firestore_web at
/Users/jun/.pub-cache/hosted/pub.dartlang.org/cloud_firestore_web-0.1.0+2/
[   +5 ms] Found plugin firebase_auth at
/Users/jun/.pub-cache/hosted/pub.dartlang.org/firebase_auth-0.15.4/
[   +2 ms] Found plugin firebase_auth_web at
/Users/jun/.pub-cache/hosted/pub.dartlang.org/firebase_auth_web-0.1.2/
[   +1 ms] Found plugin firebase_core at
/Users/jun/.pub-cache/hosted/pub.dartlang.org/firebase_core-0.4.3+3/
[   +3 ms] Found plugin firebase_core_web at
/Users/jun/.pub-cache/hosted/pub.dartlang.org/firebase_core_web-0.1.1+2/
[  +61 ms] Generating
/Volumes/JUNSIK/JSCHOI/Projects/happy_cardano_app/android/app/src/main/java/io/flutter/p
lugins/GeneratedPluginRegistrant.java
[  +37 ms] executing: /usr/bin/xcodebuild -version
[  +87 ms] Exit code 0 from: /usr/bin/xcodebuild -version
[        ] Xcode 10.1
           Build version 10B61
[  +28 ms] Found plugin cloud_firestore at
/Users/jun/.pub-cache/hosted/pub.dartlang.org/cloud_firestore-0.13.2+1/
[   +1 ms] Found plugin cloud_firestore_web at
/Users/jun/.pub-cache/hosted/pub.dartlang.org/cloud_firestore_web-0.1.0+2/
[   +3 ms] Found plugin firebase_auth at
/Users/jun/.pub-cache/hosted/pub.dartlang.org/firebase_auth-0.15.4/
[   +1 ms] Found plugin firebase_auth_web at
/Users/jun/.pub-cache/hosted/pub.dartlang.org/firebase_auth_web-0.1.2/
[        ] Found plugin firebase_core at
/Users/jun/.pub-cache/hosted/pub.dartlang.org/firebase_core-0.4.3+3/
[   +1 ms] Found plugin firebase_core_web at
/Users/jun/.pub-cache/hosted/pub.dartlang.org/firebase_core_web-0.1.1+2/
[  +19 ms] Found plugin cloud_firestore at
/Users/jun/.pub-cache/hosted/pub.dartlang.org/cloud_firestore-0.13.2+1/
[   +1 ms] Found plugin cloud_firestore_web at
/Users/jun/.pub-cache/hosted/pub.dartlang.org/cloud_firestore_web-0.1.0+2/
[   +2 ms] Found plugin firebase_auth at
/Users/jun/.pub-cache/hosted/pub.dartlang.org/firebase_auth-0.15.4/
[   +1 ms] Found plugin firebase_auth_web at
/Users/jun/.pub-cache/hosted/pub.dartlang.org/firebase_auth_web-0.1.2/
[        ] Found plugin firebase_core at
/Users/jun/.pub-cache/hosted/pub.dartlang.org/firebase_core-0.4.3+3/
[   +1 ms] Found plugin firebase_core_web at
/Users/jun/.pub-cache/hosted/pub.dartlang.org/firebase_core_web-0.1.1+2/
[  +20 ms] Generating
/Volumes/JUNSIK/JSCHOI/Projects/happy_cardano_app/android/app/src/main/java/io/flutter/p
lugins/GeneratedPluginRegistrant.java
[   +9 ms] Compiling lib/main.dart for the Web...
[  +14 ms] Initializing file store
[  +10 ms] Done initializing file store
[  +61 ms] invalidated build due to missing files:
/Volumes/JUNSIK/JSCHOI/Projects/happy_cardano_app/packages/flutter_tools/lib/src/build_s
ystem/targets/web.dart
[  +15 ms] web_entrypoint: Starting due to {InvalidatedReason.inputMissing}
[   +2 ms] web_entrypoint: Complete
[+1609 ms] Skipping target: dart2js
[ +264 ms] Skipping target: web_release_bundle
[  +30 ms] Skipping target: web_service_worker
[        ] Persisting file store
[   +8 ms] Done persisting file store
[  +12 ms] Compiling lib/main.dart for the Web... (completed in 2.0s)
[   +2 ms] "flutter web" took 2,623ms.

`flutter run -d chrome -v`
[  +19 ms] executing: [/Users/jun/Tools/flutter/] git -c log.showSignature=false log -n
1 --pretty=format:%H
[  +31 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[        ] fabeb2a16f1d008ab8230f450c49141d35669798
[        ] executing: [/Users/jun/Tools/flutter/] git describe --match v*.*.*
--first-parent --long --tags
[   +9 ms] Exit code 0 from: git describe --match v*.*.* --first-parent --long --tags
[        ] v1.14.6-0-gfabeb2a16
[   +6 ms] executing: [/Users/jun/Tools/flutter/] git rev-parse --abbrev-ref --symbolic
@{u}
[   +6 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/beta
[        ] executing: [/Users/jun/Tools/flutter/] git ls-remote --get-url origin
[   +7 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[  +42 ms] executing: [/Users/jun/Tools/flutter/] git rev-parse --abbrev-ref HEAD
[   +6 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] beta
[   +5 ms] executing: sw_vers -productName
[  +10 ms] Exit code 0 from: sw_vers -productName
[        ] Mac OS X
[        ] executing: sw_vers -productVersion
[  +10 ms] Exit code 0 from: sw_vers -productVersion
[        ] 10.13.6
[        ] executing: sw_vers -buildVersion
[  +11 ms] Exit code 0 from: sw_vers -buildVersion
[        ] 17G66
[  +25 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping
update.
[        ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping
update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required,
skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +2 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping
update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping
update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping
update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping
update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping
update.
[  +22 ms] executing: /Users/jun/Library/Android/sdk/platform-tools/adb devices -l
[   +8 ms] Exit code 0 from: /Users/jun/Library/Android/sdk/platform-tools/adb devices
-l
[        ] List of devices attached
           emulator-5554          device product:sdk_gphone_x86
           model:Android_SDK_built_for_x86 device:generic_x86 transport_id:1
[  +25 ms] executing:
/Users/jun/Tools/flutter/bin/cache/artifacts/libimobiledevice/idevice_id -h
[  +68 ms] executing: /usr/bin/xcode-select --print-path
[   +8 ms] Exit code 0 from: /usr/bin/xcode-select --print-path
[        ] /Applications/Xcode.app/Contents/Developer
[        ] executing: /usr/bin/xcodebuild -version
[  +81 ms] Exit code 0 from: /usr/bin/xcodebuild -version
[        ] Xcode 10.1
           Build version 10B61
[   +8 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping
update.
[        ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping
update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required,
skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping
update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping
update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping
update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping
update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping
update.
[  +67 ms] Found plugin cloud_firestore at
/Users/jun/.pub-cache/hosted/pub.dartlang.org/cloud_firestore-0.13.2+1/
[   +6 ms] Found plugin cloud_firestore_web at
/Users/jun/.pub-cache/hosted/pub.dartlang.org/cloud_firestore_web-0.1.0+2/
[   +6 ms] Found plugin firebase_auth at
/Users/jun/.pub-cache/hosted/pub.dartlang.org/firebase_auth-0.15.4/
[   +2 ms] Found plugin firebase_auth_web at
/Users/jun/.pub-cache/hosted/pub.dartlang.org/firebase_auth_web-0.1.2/
[   +2 ms] Found plugin firebase_core at
/Users/jun/.pub-cache/hosted/pub.dartlang.org/firebase_core-0.4.3+3/
[   +2 ms] Found plugin firebase_core_web at
/Users/jun/.pub-cache/hosted/pub.dartlang.org/firebase_core_web-0.1.1+2/
[  +49 ms] Found plugin cloud_firestore at
/Users/jun/.pub-cache/hosted/pub.dartlang.org/cloud_firestore-0.13.2+1/
[   +2 ms] Found plugin cloud_firestore_web at
/Users/jun/.pub-cache/hosted/pub.dartlang.org/cloud_firestore_web-0.1.0+2/
[   +4 ms] Found plugin firebase_auth at
/Users/jun/.pub-cache/hosted/pub.dartlang.org/firebase_auth-0.15.4/
[   +2 ms] Found plugin firebase_auth_web at
/Users/jun/.pub-cache/hosted/pub.dartlang.org/firebase_auth_web-0.1.2/
[   +1 ms] Found plugin firebase_core at
/Users/jun/.pub-cache/hosted/pub.dartlang.org/firebase_core-0.4.3+3/
[   +2 ms] Found plugin firebase_core_web at
/Users/jun/.pub-cache/hosted/pub.dartlang.org/firebase_core_web-0.1.1+2/
[  +51 ms] Generating
/Volumes/JUNSIK/JSCHOI/Projects/happy_cardano_app/android/app/src/main/java/io/flutter/p
lugins/GeneratedPluginRegistrant.java
[ +131 ms] Launching lib/main.dart on Chrome in debug mode...
[   +1 ms] Building application for the web...
[ +161 ms] Found plugin cloud_firestore at
/Users/jun/.pub-cache/hosted/pub.dartlang.org/cloud_firestore-0.13.2+1/
[   +1 ms] Found plugin cloud_firestore_web at
/Users/jun/.pub-cache/hosted/pub.dartlang.org/cloud_firestore_web-0.1.0+2/
[   +1 ms] Found plugin firebase_auth at
/Users/jun/.pub-cache/hosted/pub.dartlang.org/firebase_auth-0.15.4/
[   +1 ms] Found plugin firebase_auth_web at
/Users/jun/.pub-cache/hosted/pub.dartlang.org/firebase_auth_web-0.1.2/
[        ] Found plugin firebase_core at
/Users/jun/.pub-cache/hosted/pub.dartlang.org/firebase_core-0.4.3+3/
[        ] Found plugin firebase_core_web at
/Users/jun/.pub-cache/hosted/pub.dartlang.org/firebase_core_web-0.1.1+2/
[+5457 ms] Daemon is already running.
[ +501 ms] About to build [web]...
[   +3 ms] Updating asset graph...
[   +1 ms] Updating asset graph completed, took 3ms

[        ] Running build...
[  +57 ms] Running build completed, took 25ms

[        ] Caching finalized dependency graph...
[   +3 ms] Caching finalized dependency graph completed, took 45ms

[   +3 ms] Failed after 76ms
[  +11 ms] Building application for the web... (completed in 6.2s)
[   +1 ms] "flutter run" took 6,852ms.
Failed to build application for the Web.

#0      throwToolExit (package:flutter_tools/src/base/common.dart:27:3)
#1      _DwdsResidentWebRunner.run
(package:flutter_tools/src/build_runner/resident_web_runner.dart:716:7)
<asynchronous suspension>
#2      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:548:37)
<asynchronous suspension>
#3      FlutterCommand.verifyThenRunCommand
(package:flutter_tools/src/runner/flutter_command.dart:638:18)
#4      _asyncThenWrapperHelper.<anonymous closure>
(dart:async-patch/async_patch.dart:75:64)
#5      _rootRunUnary (dart:async/zone.dart:1134:38)
#6      _CustomZone.runUnary (dart:async/zone.dart:1031:19)
#7      _FutureListener.handleValue (dart:async/future_impl.dart:140:18)
#8      Future._propagateToListeners.handleValueCallback
(dart:async/future_impl.dart:682:45)
#9      Future._propagateToListeners (dart:async/future_impl.dart:711:32)
#10     Future._completeWithValue (dart:async/future_impl.dart:526:5)
#11     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:34:15)
#12     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:293:13)
#13     RunCommand.usageValues (package:flutter_tools/src/commands/run.dart)
#14     _asyncThenWrapperHelper.<anonymous closure>
(dart:async-patch/async_patch.dart:75:64)
#15     _rootRunUnary (dart:async/zone.dart:1134:38)
#16     _CustomZone.runUnary (dart:async/zone.dart:1031:19)
#17     _FutureListener.handleValue (dart:async/future_impl.dart:140:18)
#18     Future._propagateToListeners.handleValueCallback
(dart:async/future_impl.dart:682:45)
#19     Future._propagateToListeners (dart:async/future_impl.dart:711:32)
#20     Future._completeWithValue (dart:async/future_impl.dart:526:5)
#21     Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:556:7)
#22     _rootRun (dart:async/zone.dart:1126:13)
#23     _CustomZone.run (dart:async/zone.dart:1023:19)
#24     _CustomZone.runGuarded (dart:async/zone.dart:925:7)
#25     _CustomZone.bindCallbackGuarded.<anonymous closure>
(dart:async/zone.dart:965:23)
#26     _microtaskLoop (dart:async/schedule_microtask.dart:43:21)
#27     _startMicrotaskLoop (dart:async/schedule_microtask.dart:52:5)
#28     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
#29     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:169:5)
```

</details>

`flutter doctor -v`

```
[✓] Flutter (Channel beta, v1.14.6, on Mac OS X 10.13.6 17G66, locale ko-KR)
    • Flutter version 1.14.6 at /Users/jun/Tools/flutter
    • Framework revision fabeb2a16f (2주 전), 2020-01-28 07:56:51 -0800
    • Engine revision c4229bfbba
    • Dart version 2.8.0 (build 2.8.0-dev.5.0 fc3af737c7)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/jun/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling
      support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[!] Xcode - develop for iOS and macOS (Xcode 10.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.1, Build version 10B61
    ✗ Flutter requires a minimum Xcode version of 10.2.0.
      Download the latest version or update via the Mac App Store.
    ✗ Xcode requires additional components to be installed in order to run.
      Launch Xcode and install additional required components when prompted or run:
        sudo xcodebuild -runFirstLaunch
    • CocoaPods version 1.8.4

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 42.1.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build
      1.8.0_202-release-1483-b49-5587405)

[✓] VS Code (version 1.42.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.8.1

[✓] Connected device (3 available)
    • Android SDK built for x86 • emulator-5554 • android-x86    • Android 10 (API 29)
      (emulator)
    • Chrome                    • chrome        • web-javascript • Google Chrome
      80.0.3987.100
    • Web Server                • web-server    • web-javascript • Flutter Tools

! Doctor found issues in 1 category.
```

**Comment by jonahwilliams** [comment]
This might have been fixed by https://github.com/flutter/flutter/pull/50365

**Comment by JunsikChoi** [comment]
Then should I just wait for the next update? or should I switch the branch?

**Comment by khangahs** [comment]
Master branch has not been updated yet, maybe they will release the fix in the near future. @JunsikChoi you can switch to dev channel if you have important stuff to do.

**Comment by yjbanov** [comment]
@jonahwilliams I'm slotting this for near-term, but if you believe this is fixed, please feel free to close.
