### ISSUE TITLE
Failed to extract manifest from APK // aapt.EXE stop working.

### ISSUE THREAD

**Issue by openclues** [flutter/flutter#50677]
I installed flutter and dart then tried to test the default app of flutter on web and it worked well. Then tried to test the app on my own phone i get that error :

windows [Version 10.0.17763.1039]
(c) 2018 Microsoft Corporation. All rights reserved.

D:\tests\flutter_appd>flutter run
Launching lib\main.dart on STK LX1 in debug mode...
Running Gradle task 'assembleDebug'...
Running Gradle task 'assembleDebug'... Done                       117.9s
√ Built build\app\outputs\apk\debug\app-debug.apk.

After this step i got a message saying that " aapt.EXE stop working "  
then

Failed to extract manifest from APK: ProcessException: The
 command failed
  Command: C:\Users\User\AppData\Local\Android\sdk\build-t
ools\28.0.3\aapt dump xmltree
  D:\tests\flutter_appd\build\app\outputs\apk\app.apk AndroidManifest.xml.
Problem building Android application: see above error(s).

thank you.

**Comment by openclues** [comment]
C:\Users\User>flutter doctor -v
[√] Flutter (Channel beta, v1.14.6, on Microsoft Windows [Version 10.0.17763.1039], locale en-US)
    • Flutter version 1.14.6 at C:\flutter
    • Framework revision fabeb2a16f (2 weeks ago), 2020-01-28 07:56:51 -0800
    • Engine revision c4229bfbba
    • Dart version 2.8.0 (build 2.8.0-dev.5.0 fc3af737c7)


[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at C:\Users\User\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: C:\Program Files\Android\Android Studio1\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 3.5)
    • Android Studio at C:\Program Files\Android\Android Studio1
    • Flutter plugin version 43.0.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)

[√] IntelliJ IDEA Community Edition (version 2019.2)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2019.2.2
    • Flutter plugin version 43.0.2
    • Dart plugin version 192.7761

[√] VS Code (version 1.42.0)
    • VS Code at C:\Users\User\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.8.1

[√] Connected device (3 available)
    • STK LX1    • MVS4C19803003273 • android-arm64  • Android 9 (API 28)
    • Chrome     • chrome           • web-javascript • Google Chrome 80.0.3987.87
    • Web Server • web-server       • web-javascript • Flutter Tools

• No issues found!

**Comment by iapicca** [comment]
Hi @openclues 
your `flutter run --verbose` 
Thank you

**Comment by openclues** [comment]
sts\flutter_appd>flutter run --verbose
[  +36 ms] executing: [C:\flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[  +88 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[        ] fabeb2a16f1d008ab8230f450c49141d35669798
[        ] executing: [C:\flutter/] git describe --match v*.*.* --first-parent --long --tags
[  +64 ms] Exit code 0 from: git describe --match v*.*.* --first-parent --long --tags
[        ] v1.14.6-0-gfabeb2a16
[  +12 ms] executing: [C:\flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[  +74 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/beta
[        ] executing: [C:\flutter/] git ls-remote --get-url origin
[  +59 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[ +126 ms] executing: [C:\flutter/] git rev-parse --abbrev-ref HEAD
[  +95 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] beta
[  +76 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +6 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +75 ms] executing: C:\Users\User\AppData\Local\Android\sdk\platform-tools\adb.exe devices -l
[ +142 ms] Exit code 0 from: C:\Users\User\AppData\Local\Android\sdk\platform-tools\adb.exe devices -l
[   +1 ms] List of devices attached
           MVS4C19803003273       device product:STK-L21 model:STK_LX1 device:HWSTK-HF transport_id:1
[  +20 ms] C:\Users\User\AppData\Local\Android\sdk\platform-tools\adb.exe -s MVS4C19803003273 shell getprop
[+1242 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[  +21 ms] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[   +4 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[+1167 ms] Generating
D:\tests\flutter_appd\android\app\src\main\java\io\flutter\plugins\GeneratedPluginRegistrant.java
[ +413 ms] ro.hardware = kirin710
[        ] ro.build.characteristics = default
[  +72 ms] Launching lib\main.dart on STK LX1 in debug mode...
[ +209 ms] executing: C:\Users\User\AppData\Local\Android\sdk\platform-tools\adb.exe -s MVS4C19803003273 shell -x
logcat -v time -t 1
[ +227 ms] Exit code 0 from: C:\Users\User\AppData\Local\Android\sdk\platform-tools\adb.exe -s MVS4C19803003273 shell
-x logcat -v time -t 1
[   +1 ms] --------- beginning of system
           02-13 14:11:09.567 I/AlarmManager( 1464): adjustDeliveryTimeBasedOnStandbyBucketLocked alarm:Alarm{dda3ff4
           type 3 when 7304594 PendingIntent{9ae90fe: PendingIntentRecord{1f5505f com.whatsapp
           broadcastIntent}}com.whatsapp}, standbyBucket:40, minElapsed:11744155
[  +11 ms] executing: C:\Users\User\AppData\Local\Android\sdk\platform-tools\adb.exe version
[   +2 ms] executing: C:\Users\User\AppData\Local\Android\sdk\platform-tools\adb.exe -s MVS4C19803003273 logcat -v
time -T 02-13 14:11:09.567
[ +253 ms] Android Debug Bridge version 1.0.41
                    Version 29.0.5-5949299
                    Installed as C:\Users\User\AppData\Local\Android\sdk\platform-tools\adb.exe
[   +3 ms] executing: C:\Users\User\AppData\Local\Android\sdk\platform-tools\adb.exe start-server
[ +170 ms] Building APK
[  +24 ms] Running Gradle task 'assembleDebug'...
[   +4 ms] gradle.properties already sets `android.enableR8`
[   +7 ms] Using gradle from D:\tests\flutter_appd\android\gradlew.bat.
[   +2 ms] D:\tests\flutter_appd\android\gradlew.bat mode: 33279 rwxrwxrwx.
[  +17 ms] executing: C:\Program Files\Android\Android Studio1\jre\bin\java -version
[+1932 ms] Exit code 0 from: C:\Program Files\Android\Android Studio1\jre\bin\java -version
[   +1 ms] openjdk version "1.8.0_202-release"
           OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)
           OpenJDK 64-Bit Server VM (build 25.202-b03, mixed mode)
[   +7 ms] executing: [D:\tests\flutter_appd\android/] D:\tests\flutter_appd\android\gradlew.bat -Pverbose=true
-Ptarget=D:\tests\flutter_appd\lib\main.dart -Ptrack-widget-creation=true -Pfilesystem-scheme=org-dartlang-root
-Ptarget-platform=android-arm64 assembleDebug
[+6238 ms] Starting a Gradle Daemon, 1 busy and 3 incompatible Daemons could not be reused, use --status for details
[+36680 ms] > Task :app:compileFlutterBuildDebug
[   +1 ms] [  +32 ms] executing: [C:\flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[   +1 ms] [  +89 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[        ] [        ] fabeb2a16f1d008ab8230f450c49141d35669798
[        ] [        ] executing: [C:\flutter/] git describe --match v*.*.* --first-parent --long --tags
[        ] [  +60 ms] Exit code 0 from: git describe --match v*.*.* --first-parent --long --tags
[   +1 ms] [        ] v1.14.6-0-gfabeb2a16
[        ] [  +11 ms] executing: [C:\flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[        ] [  +55 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] [        ] origin/beta
[        ] [        ] executing: [C:\flutter/] git ls-remote --get-url origin
[   +1 ms] [  +54 ms] Exit code 0 from: git ls-remote --get-url origin
[   +1 ms] [        ] https://github.com/flutter/flutter.git
[        ] [ +112 ms] executing: [C:\flutter/] git rev-parse --abbrev-ref HEAD
[        ] [  +62 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[   +1 ms] [        ] beta
[   +1 ms] [  +39 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[   +1 ms] [        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[   +1 ms] [        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +1 ms] [   +6 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[   +2 ms] [        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[   +1 ms] [        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[   +1 ms] [        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[   +1 ms] [        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[   +1 ms] [  +23 ms] Artifact Instance of 'MaterialFonts' is not required, skipping update.
[   +1 ms] [        ] Artifact Instance of 'GradleWrapper' is not required, skipping update.
[   +1 ms] [        ] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[   +1 ms] [        ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[   +1 ms] [        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[   +1 ms] [        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[   +1 ms] [        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FlutterSdk' is not required, skipping update.
[        ] [        ] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[   +1 ms] [        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[   +1 ms] [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FontSubsetArtifacts' is not required, skipping update.
[        ] [ +215 ms] Initializing file store
[   +1 ms] [  +64 ms] kernel_snapshot: Starting due to {}
[   +1 ms] [  +20 ms] C:\flutter\bin\cache\dart-sdk\bin\dart.exe
C:\flutter\bin\cache\artifacts\engine\windows-x64\frontend_server.dart.snapshot --sdk-root
C:\flutter\bin\cache\artifacts\engine\common\flutter_patched_sdk/ --target=flutter
-Ddart.developer.causal_async_stacks=true -Ddart.vm.profile=false -Ddart.vm.product=false
--bytecode-options=source-positions,local-var-info,debugger-stops,instance-field-initializers,keep-unreachable-code,av
oid-closure-call-instructions --enable-asserts --track-widget-creation --no-link-platform --packages
D:\tests\flutter_appd\.packages --output-dill
D:\tests\flutter_appd\.dart_tool\flutter_build\e883ef037de334b8af14c77b230ef036\app.dill --depfile
D:\tests\flutter_appd\.dart_tool\flutter_build\e883ef037de334b8af14c77b230ef036\kernel_snapshot.d
package:flutter_appd/main.dart
[+19940 ms] [+20041 ms] kernel_snapshot: Complete
[+2100 ms] [+2116 ms] debug_android_application: Starting due to {}
[+1299 ms] [+1302 ms] debug_android_application: Complete
[ +501 ms] [ +490 ms] Persisting file store
[   +7 ms] [  +52 ms] Done persisting file store
[   +1 ms] [   +5 ms] build succeeded.
[  +89 ms] [  +34 ms] "flutter assemble" took 24,475ms.
[ +505 ms] > Task :app:packLibsflutterBuildDebug
[   +1 ms] > Task :app:preBuild UP-TO-DATE
[        ] > Task :app:preDebugBuild UP-TO-DATE
[   +1 ms] > Task :app:compileDebugAidl NO-SOURCE
[ +490 ms] > Task :app:checkDebugManifest
[   +1 ms] > Task :app:compileDebugRenderscript NO-SOURCE
[  +98 ms] > Task :app:generateDebugBuildConfig
[ +150 ms] > Task :app:cleanMergeDebugAssets UP-TO-DATE
[ +251 ms] > Task :app:mergeDebugShaders
[   +1 ms] > Task :app:compileDebugShaders
[        ] > Task :app:generateDebugAssets
[   +1 ms] > Task :app:mergeDebugAssets
[ +595 ms] > Task :app:copyFlutterAssetsDebug
[ +299 ms] > Task :app:mainApkListPersistenceDebug
[ +799 ms] > Task :app:generateDebugResValues
[   +1 ms] > Task :app:generateDebugResources
[+2600 ms] > Task :app:createDebugCompatibleScreenManifests
[+1198 ms] > Task :app:processDebugManifest
[ +399 ms] > Task :app:mergeDebugResources
[+19200 ms] > Task :app:processDebugResources
[+13405 ms] > Task :app:compileDebugKotlin
[   +1 ms] > Task :app:javaPreCompileDebug
[+2893 ms] > Task :app:compileDebugJavaWithJavac
[   +2 ms] > Task :app:compileDebugSources
[   +1 ms] > Task :app:processDebugJavaRes NO-SOURCE
[ +408 ms] > Task :app:checkDebugDuplicateClasses
[+5186 ms] > Task :app:transformClassesWithDexBuilderForDebug
[ +200 ms] > Task :app:validateSigningDebug
[ +200 ms] > Task :app:signingConfigWriterDebug
[   +1 ms] > Task :app:desugarDebugFileDependencies
[+1698 ms] > Task :app:mergeDebugJniLibFolders
[+4300 ms] > Task :app:mergeExtDexDebug
[+7298 ms] > Task :app:mergeDebugJavaResource
[ +101 ms] > Task :app:mergeDexDebug
[+1498 ms] > Task :app:mergeDebugNativeLibs
[ +300 ms] Unable to strip library
'D:\tests\flutter_appd\build\app\intermediates\merged_native_libs\debug\out\lib\x86_64\libflutter.so' due to missing
strip tool for ABI 'X86_64'. Packaging it as is.
[ +600 ms] > Task :app:stripDebugDebugSymbols
[   +1 ms] Compatible side by side NDK version was not found.
[        ] Unable to strip library
'D:\tests\flutter_appd\build\app\intermediates\merged_native_libs\debug\out\lib\arm64-v8a\libflutter.so' due to
missing strip tool for ABI 'ARM64_V8A'. Packaging it as is.
[   +1 ms] Unable to strip library
'D:\tests\flutter_appd\build\app\intermediates\merged_native_libs\debug\out\lib\x86\libflutter.so' due to missing
strip tool for ABI 'X86'. Packaging it as is.
[+15598 ms] > Task :app:packageDebug
[   +1 ms] > Task :app:assembleDebug
[ +197 ms] BUILD SUCCESSFUL in 2m 27s
[   +1 ms] 30 actionable tasks: 29 executed, 1 up-to-date
[ +740 ms] Running Gradle task 'assembleDebug'... (completed in 150.1s, longer than expected)
[  +69 ms] calculateSha: LocalDirectory: 'D:\tests\flutter_appd\build\app\outputs\apk'/app.apk
[ +102 ms] calculateSha: reading file took 100us
[ +931 ms] calculateSha: computing sha took 930us
[   +9 ms] √ Built build\app\outputs\apk\debug\app-debug.apk.
[ +114 ms] executing: C:\Users\User\AppData\Local\Android\sdk\build-tools\28.0.3\aapt dump xmltree
D:\tests\flutter_appd\build\app\outputs\apk\app.apk AndroidManifest.xml
[+22502 ms] Exit code -1073741674 from: C:\Users\User\AppData\Local\Android\sdk\build-tools\28.0.3\aapt dump xmltree
D:\tests\flutter_appd\build\app\outputs\apk\app.apk AndroidManifest.xml
[   +5 ms] Failed to extract manifest from APK: ProcessException: The command failed
             Command: C:\Users\User\AppData\Local\Android\sdk\build-tools\28.0.3\aapt dump xmltree
             D:\tests\flutter_appd\build\app\outputs\apk\app.apk AndroidManifest.xml.
[   +5 ms] "flutter run" took 178,144ms.

Problem building Android application: see above error(s).

#0      throwToolExit (package:flutter_tools/src/base/common.dart:27:3)
#1      AndroidDevice.startApp (package:flutter_tools/src/android/android_device.dart:538:7)
<asynchronous suspension>
#2      FlutterDevice.runHot (package:flutter_tools/src/resident_runner.dart:434:54)
#3      _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:75:64)
#4      _rootRunUnary (dart:async/zone.dart:1134:38)
#5      _CustomZone.runUnary (dart:async/zone.dart:1031:19)
#6      _FutureListener.handleValue (dart:async/future_impl.dart:140:18)
#7      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:682:45)
#8      Future._propagateToListeners (dart:async/future_impl.dart:711:32)
#9      Future._completeWithValue (dart:async/future_impl.dart:526:5)
#10     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:34:15)
#11     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:293:13)
#12     ApplicationPackageFactory.getPackageForPlatform (package:flutter_tools/src/application_package.dart)
#13     _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:75:64)
#14     _rootRunUnary (dart:async/zone.dart:1134:38)
#15     _CustomZone.runUnary (dart:async/zone.dart:1031:19)
#16     _FutureListener.handleValue (dart:async/future_impl.dart:140:18)
#17     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:682:45)
#18     Future._propagateToListeners (dart:async/future_impl.dart:711:32)
#19     Future._completeWithValue (dart:async/future_impl.dart:526:5)
#20     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:34:15)
#21     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:293:13)
#22     AndroidApk.fromAndroidProject (package:flutter_tools/src/application_package.dart)
#23     _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:75:64)
#24     _rootRunUnary (dart:async/zone.dart:1134:38)
#25     _CustomZone.runUnary (dart:async/zone.dart:1031:19)
#26     _FutureListener.handleValue (dart:async/future_impl.dart:140:18)
#27     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:682:45)
#28     Future._propagateToListeners (dart:async/future_impl.dart:711:32)
#29     Future._completeWithValue (dart:async/future_impl.dart:526:5)
#30     Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:556:7)
#31     _rootRun (dart:async/zone.dart:1126:13)
#32     _CustomZone.run (dart:async/zone.dart:1023:19)
#33     _CustomZone.runGuarded (dart:async/zone.dart:925:7)
#34     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:965:23)
#35     _microtaskLoop (dart:async/schedule_microtask.dart:43:21)
#36     _startMicrotaskLoop (dart:async/schedule_microtask.dart:52:5)
#37     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
#38     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:169:5)

**Comment by VladyslavBondarenko** [comment]
Similar to https://github.com/flutter/flutter/issues/35537 
(but I don't have issues with 28.0.3)

**Comment by omusegad** [comment]
i have a similar issue anyone whos managed to solve?

**Comment by MohiniThakkar1995** [comment]
I have just created one project in VS studio for flutter, and when i try to run the project, i'm getting error.
Error :
Failed to extract manifest from APK: ProcessException: The command failed
Command: D:\SDK_NEW\sdk\build-tools\29.0.3\aapt dump xmltree E:\button_click_demo\build\app\outputs\flutter-apk\app.apk AndroidManifest.xml.
Exception: Problem building Android application: see above error(s).

I have created flutter project from android studio and got same error, can someone please give me solution for this issue, i'm stuck with this error since last 2 days.

Please find the screen shot of error which i'm getting
https://prnt.sc/vuxqk8

i'm getting the same issue,
I have tried all solutions but none of them are working.

Can someone please help me to resolve this issue.

**Comment by MohiniThakkar1995** [comment]
Hello, is there any solution for this issue?
I'm waiting since a week, can some one please help me to resolve the issue?

**Comment by DilipSuthar-XenonAI** [comment]
I am also facing the similar issue. Is anyone there to resolve this issue.

**Comment by joy2012bd** [comment]
I am also facing same issue.

**Comment by everfire130** [comment]
I am also facing same issue.

**Comment by MaangiM** [comment]
is there anyone who found a solution concerning this issue?
