### ISSUE TITLE
Consider handling non-utf8 decoding errors from File.readAsString in ErrorHandlingFileSystem

### ISSUE THREAD

**Issue by wemersonrv** [flutter/flutter#50723]
## Steps to Reproduce

Hello, my project works fine, but today it's crashing when run pub get and i just sending the crash report as oriented after crash. 

The only thing i've make in this file `android\local.properties` was add a new line with a TODO comment as you can see below:
```gradle
sdk.dir=C:\\Users\\Wemerson\\AppData\\Local\\Android\\Sdk
flutter.sdk=D:\\Flutter
flutter.buildMode=debug
flutter.versionName=1.0.0
flutter.versionCode=1
google.map.key = --------------------------------
# TODO: Add Keys/senhas às chaves SHA1/SHA256 do app quando for para produção

See crash report below...
```
Flutter crash report; please file at https://github.com/flutter/flutter/issues.

## command

flutter --no-color packages get

## exception

FileSystemException: FileSystemException: Failed to decode data using encoding 'utf-8', path = 'D:\DadosImportantes\dev\Projetos\Pixeldev\sca\mobile\android\local.properties'

```
#0      _File._tryDecode (dart:io/file_impl.dart:574:7)
#1      _File.readAsStringSync (dart:io/file_impl.dart:594:7)
#2      ForwardingFile.readAsStringSync (package:file/src/forwarding/forwarding_file.dart:103:16)
#3      new SettingsFile.parseFromFile (package:flutter_tools/src/base/utils.dart:204:36)
#4      updateLocalProperties (package:flutter_tools/src/android/gradle_utils.dart:225:29)
#5      AndroidProject.ensureReadyForPlatformSpecificTooling (package:flutter_tools/src/project.dart:599:5)
#6      FlutterProject.ensureReadyForPlatformSpecificTooling (package:flutter_tools/src/project.dart:210:21)
#7      PackagesGetCommand.runCommand (package:flutter_tools/src/commands/packages.dart:130:23)
<asynchronous suspension>
#8      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:615:18)
#9      _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:73:64)
#10     _rootRunUnary (dart:async/zone.dart:1134:38)
#11     _CustomZone.runUnary (dart:async/zone.dart:1031:19)
#12     _FutureListener.handleValue (dart:async/future_impl.dart:139:18)
#13     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:680:45)
#14     Future._propagateToListeners (dart:async/future_impl.dart:709:32)
#15     Future._completeWithValue (dart:async/future_impl.dart:524:5)
#16     Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:554:7)
#17     _rootRun (dart:async/zone.dart:1126:13)
#18     _CustomZone.run (dart:async/zone.dart:1023:19)
#19     _CustomZone.runGuarded (dart:async/zone.dart:925:7)
#20     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:965:23)
#21     _microtaskLoop (dart:async/schedule_microtask.dart:43:21)
#22     _startMicrotaskLoop (dart:async/schedule_microtask.dart:52:5)
#23     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
#24     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:175:5)
```

## flutter doctor

```
[✓] Flutter (Channel stable, v1.12.13+hotfix.5, on Microsoft Windows [versÃ£o 10.0.17763.678], locale pt-BR)
    • Flutter version 1.12.13+hotfix.5 at D:\Flutter
    • Framework revision 27321ebbad (9 weeks ago), 2019-12-10 18:15:01 -0800
    • Engine revision 2994f7e1e6
    • Dart version 2.7.0

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at C:/Users/Wemerson/AppData/Local/Android/Sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • ANDROID_HOME = C:/Users/Wemerson/AppData/Local/Android/Sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)
    • All Android licenses accepted.

[✓] Android Studio (version 3.5)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 43.0.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)

[✓] VS Code (version 1.42.0)
    • VS Code at C:\Users\Wemerson\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.8.1

[!] Connected device
    ! No devices available

! Doctor found issues in 1 category.
```

```

**Comment by zanderso** [comment]
In your text editor where you added the TODO, can you verify that the file was encoded as utf8?

**Comment by wemersonrv** [comment]
> In your text editor where you added the TODO, can you verify that the file was encoded as utf8?

Hello, its windows-1252, not UTF8. Strange because i do not open this file with other editor. Just edit it and save with android studio and the encoding changes.

Change it to utf8 and trya again and works now!

**Comment by zanderso** [comment]
If the tool is trying to read non-utf8 formatted data as a `String` it is very unlikely to be able to make progress. We should consider having the tool hande this kind of error globally in the `ErrorHandlingFileSystem`. However, whether that makes sense may depend on the source of the non-utf8 data: the tool itself, or the end-user.

**Comment by wemersonrv** [comment]
> If the tool is trying to read non-utf8 formatted data as a `String` it is very unlikely to be able to make progress. We should consider having the tool hande this kind of error globally in the `ErrorHandlingFileSystem`. However, whether that makes sense may depend on the source of the non-utf8 data: the tool itself, or the end-user.

Im my case, is the tool. This file has the same coding since 6 months ago when the project was created... and  i've made some changes on it, by adding new lines and always works. But last change i added caused the unexplicable enconding change... And i typed the entire line via keyboard, not paste from other source, so the tool itself changes the enconding.

**Comment by williamtong0228** [comment]
I've got the same problem. I am trying to install Flutter today and when it comes to create the demo project. It just failed no matter which Editor I use(Android Studio, Terminal, VS Code)
How do I fix this problem please? Or is there any workaround?

FileSystemException: FileSystemException: Failed to decode data using encoding 'utf-8', path = '/Volumes/ExtremeSSD/flutter/packages/flutter_tools/templates/app/ios.tmpl/Runner/._Info.plist.tmpl'

#0      _File._tryDecode (dart:io/file_impl.dart:574:7)
#1      _File.readAsStringSync (dart:io/file_impl.dart:594:7)
#2      ForwardingFile.readAsStringSync (package:file/src/forwarding/forwarding_file.dart:103:16)
#3      Template.render.<anonymous closure> (package:flutter_tools/src/template.dart:184:52)
#4      _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:379:8)
#5      Template.render (package:flutter_tools/src/template.dart:132:24)
#6      CreateCommand._renderTemplate (package:flutter_tools/src/commands/create.dart:667:21)
#7      CreateCommand._generateApp (package:flutter_tools/src/commands/create.dart:578:23)
#8      CreateCommand.runCommand (package:flutter_tools/src/commands/create.dart:429:37)
<asynchronous suspension>
#9      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:615:18)
#10     _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:73:64)
#11     _rootRunUnary (dart:async/zone.dart:1134:38)
#12     _CustomZone.runUnary (dart:async/zone.dart:1031:19)
#13     _FutureListener.handleValue (dart:async/future_impl.dart:139:18)
#14     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:680:45)
#15     Future._propagateToListeners (dart:async/future_impl.dart:709:32)
#16     Future._completeWithValue (dart:async/future_impl.dart:524:5)
#17     Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:554:7)
#18     _rootRun (dart:async/zone.dart:1126:13)
#19     _CustomZone.run (dart:async/zone.dart:1023:19)
#20     _CustomZone.runGuarded (dart:async/zone.dart:925:7)
#21     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:965:23)
#22     _microtaskLoop (dart:async/schedule_microtask.dart:43:21)
#23     _startMicrotaskLoop (dart:async/schedule_microtask.dart:52:5)
#24     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
#25     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:175:5)

**Comment by Mimzeslami** [comment]
I've got the same problem. I just ran "flutter clean"
