### ISSUE TITLE
Flutter 1.12.13hotfix8 Gradle build exception exit 1

### ISSUE THREAD

**Issue by fredgrott** [flutter/flutter#50727]
this is the error I get

Did the gradle versions change form hotfix 7 to hotfix8?

**Comment by fredgrott** [comment]
More info my as3.6 log
[+31408 ms] Exception in thread "main" java.net.SocketTimeoutException: Read timed out
[   +2 ms] 	at java.net.SocketInputStream.socketRead0(Native Method)
[        ] 	at java.net.SocketInputStream.socketRead(SocketInputStream.java:116)
[   +1 ms] 	at java.net.SocketInputStream.read(SocketInputStream.java:171)
[        ] 	at java.net.SocketInputStream.read(SocketInputStream.java:141)
[        ] 	at sun.security.ssl.InputRecord.readFully(InputRecord.java:465)
[        ] 	at sun.security.ssl.InputRecord.read(InputRecord.java:503)
[   +1 ms] 	at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:975)
[        ] 	at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1367)
[        ] 	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1395)
[        ] 	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1379)
[        ] 	at sun.net.www.protocol.https.HttpsClient.afterConnect(HttpsClient.java:559)
[        ] 	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:185)
[        ] 	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1564)
[        ] 	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1492)
[        ] 	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:263)
[        ] 	at org.gradle.wrapper.Download.downloadInternal(Download.java:58)
[        ] 	at org.gradle.wrapper.Download.download(Download.java:44)
[        ] 	at org.gradle.wrapper.Install$1.call(Install.java:61)
[        ] 	at org.gradle.wrapper.Install$1.call(Install.java:48)
[        ] 	at org.gradle.wrapper.ExclusiveFileAccessManager.access(ExclusiveFileAccessManager.java:65)
[        ] 	at org.gradle.wrapper.Install.createDist(Install.java:48)
[        ] 	at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:128)
[        ] 	at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:61)
[{"event":"app.progress","params":{"appId":"9b00225a-2f74-4ee4-9688-a6c723dabba3","id":"0","progressId":null,"finished":true}}]
Finished with error: Gradle task assembleDebug failed with exit code 1


Things tried thus far:
reinstall flutter sdk
point to my amazonjavase install

**Comment by fredgrott** [comment]
going to go back to hotfix7 on Friday and see if that works

**Comment by timsneath** [comment]
Can you share the results of `flutter doctor -v`? 

Are you using Linux 5.5, by any chance?

**Comment by fredgrott** [comment]
Usere, no using MS WINDOWS

Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, v1.12.13+hotfix.8, on Microsoft Windows [Version 10.0.18363.628], locale en-US)

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
[√] Android Studio (version 3.6)
[!] Android Studio (version 4.0)
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
[√] IntelliJ IDEA Community Edition (version 2019.2)
[√] VS Code (version 1.41.1)
[√] VS Code, 64-bit edition (version 1.22.2)
[!] Connected device
    ! No devices available

! Doctor found issues in 2 categories.
PS D:\fluttersdk\myfluttersdk\flutter>

no obvious errors that I can see.

cover rest of the obvious thus far in re-installing flutter sdk clean and re-installing as clean and even jdk

**Comment by fredgrott** [comment]
Okay did some tracking through issues...might be a repeat of this onen #41353

so will investigate the solution linked in that one ie the so one on Friday morning CST and should have some more info PST time

**Comment by RickStanley** [comment]
I'm stuck on "Running Gradle task 'assembleDebug'"

`flutter run -v` output:

```bash
flutter run -v
[  +24 ms] executing: [/home/stanley/Werkzeuge/flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[  +31 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[        ] 0b8abb4724aa590dd0f429683339b1e045a1594d
[        ] executing: [/home/stanley/Werkzeuge/flutter/] git describe --match v*.*.* --first-parent --long --tags
[  +10 ms] Exit code 0 from: git describe --match v*.*.* --first-parent --long --tags
[        ] v1.12.13+hotfix.8-0-g0b8abb472
[   +6 ms] executing: [/home/stanley/Werkzeuge/flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[   +7 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/stable
[        ] executing: [/home/stanley/Werkzeuge/flutter/] git ls-remote --get-url origin
[   +7 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[  +53 ms] executing: [/home/stanley/Werkzeuge/flutter/] git rev-parse --abbrev-ref HEAD
[   +7 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] stable
[ +120 ms] executing: /home/stanley/Android/Sdk/platform-tools/adb devices -l
[  +10 ms] Exit code 0 from: /home/stanley/Android/Sdk/platform-tools/adb devices -l
[        ] List of devices attached
           emulator-5554          device product:sdk_gphone_x86 model:Android_SDK_built_for_x86 device:generic_x86 transport_id:1
[  +25 ms] /home/stanley/Android/Sdk/platform-tools/adb -s emulator-5554 shell getprop
[ +123 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[   +3 ms] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +3 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +72 ms] Found plugin firebase_auth at /home/stanley/Werkzeuge/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_auth-0.14.0+9/
[   +7 ms] Found plugin firebase_core at /home/stanley/Werkzeuge/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_core-0.4.3+3/
[   +7 ms] Found plugin firebase_core_web at /home/stanley/Werkzeuge/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_core_web-0.1.1+2/
[   +5 ms] Found plugin firebase_messaging at /home/stanley/Werkzeuge/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_messaging-5.1.8/
[  +53 ms] Found plugin shared_preferences at /home/stanley/Werkzeuge/flutter/.pub-cache/hosted/pub.dartlang.org/shared_preferences-0.5.6+1/
[   +2 ms] Found plugin shared_preferences_macos at /home/stanley/Werkzeuge/flutter/.pub-cache/hosted/pub.dartlang.org/shared_preferences_macos-0.0.1+4/
[   +4 ms] Found plugin shared_preferences_web at /home/stanley/Werkzeuge/flutter/.pub-cache/hosted/pub.dartlang.org/shared_preferences_web-0.1.2+3/
[  +17 ms] Found plugin url_launcher at /home/stanley/Werkzeuge/flutter/.pub-cache/hosted/pub.dartlang.org/url_launcher-5.4.1/
[   +1 ms] Found plugin url_launcher_macos at /home/stanley/Werkzeuge/flutter/.pub-cache/hosted/pub.dartlang.org/url_launcher_macos-0.0.1+2/
[   +4 ms] Found plugin url_launcher_web at /home/stanley/Werkzeuge/flutter/.pub-cache/hosted/pub.dartlang.org/url_launcher_web-0.1.0+2/
[   +4 ms] Found plugin vibration at /home/stanley/Werkzeuge/flutter/.pub-cache/hosted/pub.dartlang.org/vibration-1.2.2/
[  +88 ms] Found plugin firebase_auth at /home/stanley/Werkzeuge/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_auth-0.14.0+9/
[   +1 ms] Found plugin firebase_core at /home/stanley/Werkzeuge/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_core-0.4.3+3/
[   +1 ms] Found plugin firebase_core_web at /home/stanley/Werkzeuge/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_core_web-0.1.1+2/
[   +1 ms] Found plugin firebase_messaging at /home/stanley/Werkzeuge/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_messaging-5.1.8/
[  +23 ms] Found plugin shared_preferences at /home/stanley/Werkzeuge/flutter/.pub-cache/hosted/pub.dartlang.org/shared_preferences-0.5.6+1/
[        ] Found plugin shared_preferences_macos at /home/stanley/Werkzeuge/flutter/.pub-cache/hosted/pub.dartlang.org/shared_preferences_macos-0.0.1+4/
[   +2 ms] Found plugin shared_preferences_web at /home/stanley/Werkzeuge/flutter/.pub-cache/hosted/pub.dartlang.org/shared_preferences_web-0.1.2+3/
[  +11 ms] Found plugin url_launcher at /home/stanley/Werkzeuge/flutter/.pub-cache/hosted/pub.dartlang.org/url_launcher-5.4.1/
[   +1 ms] Found plugin url_launcher_macos at /home/stanley/Werkzeuge/flutter/.pub-cache/hosted/pub.dartlang.org/url_launcher_macos-0.0.1+2/
[   +1 ms] Found plugin url_launcher_web at /home/stanley/Werkzeuge/flutter/.pub-cache/hosted/pub.dartlang.org/url_launcher_web-0.1.0+2/
[   +2 ms] Found plugin vibration at /home/stanley/Werkzeuge/flutter/.pub-cache/hosted/pub.dartlang.org/vibration-1.2.2/
[  +50 ms] Generating /home/stanley/flutter_projects/socio-torcedor/android/app/src/main/java/io/flutter/plugins/GeneratedPluginRegistrant.java
[  +26 ms] ro.hardware = ranchu
[  +45 ms] Using hardware rendering with device Android SDK built for x86. If you get graphics artifacts, consider enabling software rendering with
"--enable-software-rendering".
[  +23 ms] Launching lib/main.dart on Android SDK built for x86 in debug mode...
[  +19 ms] executing: /home/stanley/Android/Sdk/platform-tools/adb -s emulator-5554 shell -x logcat -v time -t 1
[  +27 ms] Exit code 0 from: /home/stanley/Android/Sdk/platform-tools/adb -s emulator-5554 shell -x logcat -v time -t 1
[        ] --------- beginning of main
           02-13 13:53:18.384 E/GnssHAL_GnssInterface( 1749): gnssSvStatusCb: b: input svInfo.flags is 8
[   +9 ms] executing: /home/stanley/Android/Sdk/platform-tools/adb version
[   +1 ms] executing: /home/stanley/Android/Sdk/platform-tools/adb -s emulator-5554 logcat -v time -T 02-13 13:53:18.384
[  +30 ms] Android Debug Bridge version 1.0.41
           Version 29.0.5-5949299
           Installed as /home/stanley/Android/Sdk/platform-tools/adb
[   +3 ms] executing: /home/stanley/Android/Sdk/platform-tools/adb start-server
[  +12 ms] Building APK
[  +21 ms] Running Gradle task 'assembleDebug'...
[   +3 ms] gradle.properties already sets `android.enableR8`
[   +6 ms] Using gradle from /home/stanley/flutter_projects/socio-torcedor/android/gradlew.
[  +12 ms] executing: /home/stanley/.local/share/JetBrains/Toolbox/apps/AndroidStudio/ch-0/191.6010548/jre/bin/java -version
[  +82 ms] Exit code 0 from: /home/stanley/.local/share/JetBrains/Toolbox/apps/AndroidStudio/ch-0/191.6010548/jre/bin/java -version
[        ] Picked up _JAVA_OPTIONS: -Dawt.useSystemAAFontSettings=on -Dswing.aatext=true
           openjdk version "1.8.0_202-release"
           OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
           OpenJDK 64-Bit Server VM (build 25.202-b49-5587405, mixed mode)
[   +3 ms] executing: [/home/stanley/flutter_projects/socio-torcedor/android/] /home/stanley/flutter_projects/socio-torcedor/android/gradlew -Pverbose=true
-Ptarget=/home/stanley/flutter_projects/socio-torcedor/lib/main.dart -Ptrack-widget-creation=true -Pfilesystem-scheme=org-dartlang-root -Ptarget-platform=android-x86
assembleDebug
[  +54 ms] Picked up _JAVA_OPTIONS: -Dawt.useSystemAAFontSettings=on -Dswing.aatext=true
[ +545 ms] Welcome to Gradle 5.6.2!
[        ] Here are the highlights of this release:
[        ]  - Incremental Groovy compilation
[        ]  - Groovy compile avoidance
[        ]  - Test fixtures for Java projects
[        ]  - Manage plugin versions via settings script
[        ] For more details see https://docs.gradle.org/5.6.2/release-notes.html
[  +96 ms] Starting a Gradle Daemon, 2 busy Daemons could not be reused, use --status for details
[+15614 ms] > Task :app:compileFlutterBuildDebug
[        ] [  +24 ms] executing: [/home/stanley/Werkzeuge/flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[        ] [  +35 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[        ] [   +1 ms] 0b8abb4724aa590dd0f429683339b1e045a1594d
[        ] [   +1 ms] executing: [/home/stanley/Werkzeuge/flutter/] git describe --match v*.*.* --first-parent --long --tags
[        ] [   +7 ms] Exit code 0 from: git describe --match v*.*.* --first-parent --long --tags
[        ] [        ] v1.12.13+hotfix.8-0-g0b8abb472
[        ] [  +10 ms] executing: [/home/stanley/Werkzeuge/flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[        ] [   +4 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] [        ] origin/stable
[        ] [        ] executing: [/home/stanley/Werkzeuge/flutter/] git ls-remote --get-url origin
[        ] [   +4 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] [        ] https://github.com/flutter/flutter.git
[        ] [  +55 ms] executing: [/home/stanley/Werkzeuge/flutter/] git rev-parse --abbrev-ref HEAD
[        ] [   +6 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] [        ] stable
[        ] [  +30 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[        ] [   +4 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[   +6 ms] [        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[        ] [ +110 ms] Initializing file store
[        ] [  +18 ms] kernel_snapshot: Starting due to {}
[        ] [  +15 ms] /home/stanley/Werkzeuge/flutter/bin/cache/dart-sdk/bin/dart
/home/stanley/Werkzeuge/flutter/bin/cache/artifacts/engine/linux-x64/frontend_server.dart.snapshot --sdk-root
/home/stanley/Werkzeuge/flutter/bin/cache/artifacts/engine/common/flutter_patched_sdk/ --target=flutter -Ddart.developer.causal_async_stacks=true -Ddart.vm.profile=false
-Ddart.vm.product=false
--bytecode-options=source-positions,local-var-info,debugger-stops,instance-field-initializers,keep-unreachable-code,avoid-closure-call-instructions --enable-asserts
--track-widget-creation --no-link-platform --packages /home/stanley/flutter_projects/socio-torcedor/.packages --output-dill
/home/stanley/flutter_projects/socio-torcedor/.dart_tool/flutter_build/a5eb1f88f290a7821f8f182a31528121/app.dill --depfile
/home/stanley/flutter_projects/socio-torcedor/.dart_tool/flutter_build/a5eb1f88f290a7821f8f182a31528121/kernel_snapshot.d package:socio_torcedor/main.dart
```

`flutter doctor -v` output:

```bash
[✓] Flutter (Channel stable, v1.12.13+hotfix.8, on Linux, locale de_DE.UTF-8)
    • Flutter version 1.12.13+hotfix.8 at /home/stanley/Werkzeuge/flutter
    • Framework revision 0b8abb4724 (vor 2 Tagen), 2020-02-11 11:44:36 -0800
    • Engine revision e1e6ced81d
    • Dart version 2.7.0

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /home/stanley/Android/Sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /home/stanley/.local/share/JetBrains/Toolbox/apps/AndroidStudio/ch-0/191.6010548/jre/bin/java
    • Java version openjdk version "1.8.0_202-release"
    • All Android licenses accepted.

[✓] Android Studio (version 3.5)
    • Android Studio at /home/stanley/.local/share/JetBrains/Toolbox/apps/AndroidStudio/ch-0/191.6010548
    • Flutter plugin version 43.0.1
    • Dart plugin version 191.8593
    • Java version openjdk version "1.8.0_202-release"

[✓] Connected device (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 10 (API 29) (emulator)

• No issues found!
```

@timsneath I'm using Linux 5.5, uname -a : `Linux 5.5.3-arch1-1`, Arch Linux

Possible solution (haven't tried it):

> Hit the same issue here, turns out downgrading the linux kernel to 5.4.15-arch1-1 from 5.5.2-arch1-1 makes it work again.¹

¹.[Gradle getting stuck at assembleDebug](https://stackoverflow.com/a/60117983/7443903)

**Comment by RickStanley** [comment]
Please, notify me if it's a separate issue. Thanks in advance :+1:

**Comment by RickStanley** [comment]
Yep, changing to linux lts solves this:

1. install `pacman -S linux-lts`
2. update the grub config `grub-mkconfig -o /boot/grub/grub.cfg`

I think it's related to #49185

**Comment by dnfield** [comment]
@RickStanley  - I hid your comments because they're for the Linux 5.5 issue, whereas this one is for Windows.  Nothing wrong with your posts, just want to make sure this doesn't confuse people who look at it later :)

**Comment by fredgrott** [comment]
okay did a real complete clean install got rid of everything android and re installed same exact issue, log is:
Running Gradle task 'assembleDebug'...
Exception in thread "main" java.net.SocketTimeoutException: Read timed out
	at java.net.SocketInputStream.socketRead0(Native Method)
	at java.net.SocketInputStream.socketRead(SocketInputStream.java:116)
	at java.net.SocketInputStream.read(SocketInputStream.java:171)
	at java.net.SocketInputStream.read(SocketInputStream.java:141)
	at sun.security.ssl.InputRecord.readFully(InputRecord.java:465)
	at sun.security.ssl.InputRecord.read(InputRecord.java:503)
	at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:975)
	at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1367)
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1395)
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1379)
	at sun.net.www.protocol.https.HttpsClient.afterConnect(HttpsClient.java:559)
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:185)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1564)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1492)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:263)
	at org.gradle.wrapper.Download.downloadInternal(Download.java:58)
	at org.gradle.wrapper.Download.download(Download.java:44)
	at org.gradle.wrapper.Install$1.call(Install.java:61)
	at org.gradle.wrapper.Install$1.call(Install.java:48)
	at org.gradle.wrapper.ExclusiveFileAccessManager.access(ExclusiveFileAccessManager.java:65)
	at org.gradle.wrapper.Install.createDist(Install.java:48)
	at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:128)
	at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:61)
Finished with error: Gradle task assembleDebug failed with exit code 1

sop must be a windows-flutter tools issue-sdk??

**Comment by fredgrott** [comment]
going back to as3.5.x as I am reasoning its gradle and since as3.5 has a different gradle plugin it might work..already went back to hotfix7 and same error and I know as3.6 between r2 and r3 updated the gradle plugin

**Comment by fredgrott** [comment]
folks, hotfix7 as3.5 no go too on ms windows now what as far as work around?

**Comment by fredgrott** [comment]
I think I tracked down the problem to flutter_platform_wdgets requires hotfix 5 not 8 and the dart gherkin plugin I am using combined with hotfix8 and dart 2.7

So completely re instaling everything and making sure the project loads dart 2.1 via clearing cache and re doing pub get
