### ISSUE TITLE
PANIC: Broken AVD system path. Check your ANDROID_SDK_ROOT value

### ISSUE THREAD

**Issue by barisevlic** [flutter/flutter#50759]
[flutter_01.log](https://github.com/flutter/flutter/files/4201293/flutter_01.log)
```
Flutter crash report; please file at https://github.com/flutter/flutter/issues.

## command

flutter emulators --launch Pixel-test2

## exception

ProcessException: ProcessException: Process exited abnormally:
PANIC: Broken AVD system path. Check your ANDROID_SDK_ROOT value [C:\Android\sdk]!
  Command: C:\Android\sdk\emulator\emulator.exe -avd Pixel-test2


#0      RunResult.throwException (package:flutter_tools/src/base/process.dart:141:5)
#1      _DefaultProcessUtils.run (package:flutter_tools/src/base/process.dart:275:19)
<asynchronous suspension>
#2      AndroidEmulator.launch (package:flutter_tools/src/android/android_emulator.dart:52:52)
#3      EmulatorsCommand._launchEmulator (package:flutter_tools/src/commands/emulators.dart:74:31)
<asynchronous suspension>
#4      EmulatorsCommand.runCommand (package:flutter_tools/src/commands/emulators.dart:47:13)
#5      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:615:18)
#6      _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:73:64)
#7      _rootRunUnary (dart:async/zone.dart:1134:38)
#8      _CustomZone.runUnary (dart:async/zone.dart:1031:19)
#9      _FutureListener.handleValue (dart:async/future_impl.dart:139:18)
#10     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:680:45)
#11     Future._propagateToListeners (dart:async/future_impl.dart:709:32)
#12     Future._completeWithValue (dart:async/future_impl.dart:524:5)
#13     Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:554:7)
#14     _rootRun (dart:async/zone.dart:1126:13)
#15     _CustomZone.run (dart:async/zone.dart:1023:19)
#16     _CustomZone.runGuarded (dart:async/zone.dart:925:7)
#17     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:965:23)
#18     _microtaskLoop (dart:async/schedule_microtask.dart:43:21)
#19     _startMicrotaskLoop (dart:async/schedule_microtask.dart:52:5)
#20     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
#21     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:175:5)

## flutter doctor


[32m[✓][39m Flutter (Channel stable, v1.12.13+hotfix.8, on Microsoft Windows [Version 10.0.18362.592], locale tr-TR)
    [32m•[39m Flutter version 1.12.13+hotfix.8 at C:\src\flutter
    [32m•[39m Framework revision 0b8abb4724 (2 days ago), 2020-02-11 11:44:36 -0800
    [32m•[39m Engine revision e1e6ced81d
    [32m•[39m Dart version 2.7.0

[32m[✓][39m Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    [32m•[39m Android SDK at C:\Android\sdk
    [32m•[39m Android NDK location not configured (optional; useful for native profiling support)
    [32m•[39m Platform android-29, build-tools 29.0.3
    [32m•[39m ANDROID_SDK_ROOT = C:\Android\sdk
    [32m•[39m Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    [32m•[39m Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)
    [32m•[39m All Android licenses accepted.

[32m[✓][39m Android Studio (version 3.5)
    [32m•[39m Android Studio at C:\Program Files\Android\Android Studio
    [32m•[39m Flutter plugin version 43.0.1
    [32m•[39m Dart plugin version 191.8593
    [32m•[39m Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)

[33m[!][39m Connected device
    [33m![39m No devices available

[33m![39m Doctor found issues in 1 category.


```

## Steps to Reproduce

1. Run `flutter create bug`.
2. Update the files as follows: ... 
3. ... 

**Expected results:** 

**Actual results:** 

<details>
  <summary>Logs</summary>

```
```

```
```

```
```

</details>

**Comment by TahaTesser** [comment]
Hi @barisevlic 
1. Please follow this [Solution](https://github.com/flutter/flutter/issues/24988#issuecomment-550167001)
2. run `flutter emulators` and choose the emulator you want
3. run `flutter emulators --launch <emualtor name>`

Thank you

**Comment by TahaTesser** [comment]
Hi @barisevlic 

Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.
