### ISSUE TITLE
flutter build ios fail

### ISSUE THREAD

**Issue by jasoncheng** [flutter/flutter#50798]
## Steps to Reproduce

Build for debug always work, but when build for deploy fail, help please
Thanks.

1. flutter build ios -v

## Logs

```
/Users/jason/Library/Developer/Xcode/DerivedData/Runner-fyawonveuszareaauzaxilvatrzu/Build/Intermediates.noindex/Runner.build/Release-i
                            phoneos/Runner.build/Objects-normal/arm64/GeneratedPluginRegistrant.o
                        /Users/jason/Documents/workspace-flutter/holi/ios/Runner/GeneratedPluginRegistrant.m:10:9: fatal error: module
'device_info' not found
                        @import device_info;
                         ~~~~~~~^~~~~~~~~~~
                        1 error generated.
                    
                    
[ +171 ms] "flutter ios" took 107,666ms.
Encountered error while building for device.

#0      throwToolExit (package:flutter_tools/src/base/common.dart:14:3)
#1      BuildIOSCommand.runCommand (package:flutter_tools/src/commands/build_ios.dart:90:7)
<asynchronous suspension>
#2      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:681:18)
#3      _rootRunUnary (dart:async/zone.dart:1134:38)
#4      _CustomZone.runUnary (dart:async/zone.dart:1031:19)
#5      _FutureListener.handleValue (dart:async/future_impl.dart:140:18)
#6      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:682:45)
#7      Future._propagateToListeners (dart:async/future_impl.dart:711:32)
#8      Future._completeWithValue (dart:async/future_impl.dart:526:5)
#9      Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:556:7)
#10     _rootRun (dart:async/zone.dart:1126:13)
#11     _CustomZone.run (dart:async/zone.dart:1023:19)
#12     _CustomZone.runGuarded (dart:async/zone.dart:925:7)
#13     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:965:23)
#14     _microtaskLoop (dart:async/schedule_microtask.dart:43:21)
#15     _startMicrotaskLoop (dart:async/schedule_microtask.dart:52:5)
#16     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
#17     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:169:5)
```

```
[✓] Flutter (Channel master, v1.15.4-pre.68, on Mac OS X 10.14.6 18G87, locale zh-Hant-TW)
    • Flutter version 1.15.4-pre.68 at /Users/jason/flutter
    • Framework revision 85ab331c82 (4 hours ago), 2020-02-14 10:41:23 +0100
    • Engine revision 0e8ed2715a
    • Dart version 2.8.0 (build 2.8.0-dev.8.0 5244d99a5d)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/jason/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 28.0.3
    • ANDROID_HOME = /Users/jason/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.3.1, Build version 11C504
    • CocoaPods version 1.8.4

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 42.1.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] VS Code (version 1.42.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.8.1

[✓] Connected device (4 available)
    • iPhone 11 Pro Max • 1CF9A7D0-45B9-455F-BC83-4B722F8247D3 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-13-3 (simulator)
    • macOS             • macOS                                • darwin-x64     • Mac OS X 10.14.6 18G87
    • Chrome            • chrome                               • web-javascript • Google Chrome 80.0.3987.106
    • Web Server        • web-server                           • web-javascript • Flutter Tools

• No issues found!
```

**Comment by RenanDelfanti** [comment]
Same issue here

**Comment by RenanDelfanti** [comment]
This error occurred when I uncommented this
podfile line: 
# Uncomment this line to define a global platform for your project
platform :ios, '11.0'

**Comment by jasoncheng** [comment]
> This error occurred when I uncommented this
> podfile line:
> 
> ```
> # Uncomment this line to define a global platform for your project
> platform :ios, '11.0'
> ```
> 
> And I soved comment again.
@RenanDelfanti 
Thank you so much, you're saving my time

**Comment by SinaSeirafi** [comment]
> This error occurred when I uncommented this
> podfile line:
> 
> ```
> # Uncomment this line to define a global platform for your project
> platform :ios, '11.0'
> ```
> 
> And I soved comment again.

Unfortunately, this doesn't solve my issue, as [flutter_facebook_login](https://pub.dev/packages/flutter_facebook_login) requires this line to work.

Any other suggestions would be appreciated.
