### ISSUE TITLE
An error occurred while building the Android app: Execution failed for task ':app:mergeDexDebug'.

### ISSUE THREAD

**Issue by MrTomAsh** [flutter/flutter#50862]
## Steps to Reproduce

1. Stop Android Emulator.
2. Select `AOSP on IE Emulator (mobile)` 
2a. I have a `Nexus 6 API 28` with `Android 9.0`
3. Press `Run` or `Debug` in Android Studio.

**Expected results:** 
That it will compile and run the app on the Emulator

**Actual results:** 
Gives errors as follow, BUT only on Android. For iOS, it's compiling and running with no issues. Affects my other projects as well.

<details>
  <summary>Logs</summary>

**Run Console Log**
---
```
Launching lib/main.dart on AOSP on IA Emulator in debug mode...
Running Gradle task 'assembleDebug'...
/Users/tomaszbzymek/Documents/NaukaFlutter/Clima-Flutter/build/geolocator/generated/source/buildConfig/debug/com/baseflow/geolocator/BuildConfig 2.java:6: error: class BuildConfig is public, should be declared in a file named BuildConfig.java
public final class BuildConfig {
             ^
1 error

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':geolocator:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 0s
Finished with error: Gradle task assembleDebug failed with exit code 1
```

**The output from a different project**
---
```
Launching lib/main.dart on AOSP on IA Emulator in debug mode...
Running Gradle task 'assembleDebug'...
/Users/tomaszbzymek/Documents/NaukaFlutter/bmi-calculator-flutter/build/app/generated/not_namespaced_r_class_sources/debug/r/androidx/asynclayoutinflater/R 2.java:9: error: class R is public, should be declared in a file named R.java
public final class R {
             ^
/Users/tomaszbzymek/Documents/NaukaFlutter/bmi-calculator-flutter/build/app/generated/not_namespaced_r_class_sources/debug/r/androidx/core/R 2.java:9: error: class R is public, should be declared in a file named R.java
public final class R {
             ^
/Users/tomaszbzymek/Documents/NaukaFlutter/bmi-calculator-flutter/build/app/generated/not_namespaced_r_class_sources/debug/r/androidx/drawerlayout/R 2.java:9: error: class R is public, should be declared in a file named R.java
public final class R {
             ^
/Users/tomaszbzymek/Documents/NaukaFlutter/bmi-calculator-flutter/build/app/generated/not_namespaced_r_class_sources/debug/r/androidx/interpolator/R 2.java:9: error: class R is public, should be declared in a file named R.java
public final class R {
             ^
/Users/tomaszbzymek/Documents/NaukaFlutter/bmi-calculator-flutter/build/app/generated/not_namespaced_r_class_sources/debug/r/androidx/versionedparcelable/R 2.java:9: error: class R is public, should be declared in a file named R.java
public final class R {
             ^
/Users/tomaszbzymek/Documents/NaukaFlutter/bmi-calculator-flutter/build/app/generated/not_namespaced_r_class_sources/debug/r/androidx/viewpager/R 2.java:9: error: class R is public, should be declared in a file named R.java
public final class R {
             ^
/Users/tomaszbzymek/Documents/NaukaFlutter/bmi-calculator-flutter/build/app/generated/not_namespaced_r_class_sources/debug/r/androidx/lifecycle/viewmodel/R 2.java:9: error: class R is public, should be declared in a file named R.java
public final class R {
             ^
/Users/tomaszbzymek/Documents/NaukaFlutter/bmi-calculator-flutter/build/app/generated/not_namespaced_r_class_sources/debug/r/androidx/lifecycle/livedata/core/R 2.java:9: error: class R is public, should be declared in a file named R.java
public final class R {
             ^
/Users/tomaszbzymek/Documents/NaukaFlutter/bmi-calculator-flutter/build/app/generated/not_namespaced_r_class_sources/debug/r/androidx/lifecycle/livedata/R 2.java:9: error: class R is public, should be declared in a file named R.java
public final class R {
             ^
/Users/tomaszbzymek/Documents/NaukaFlutter/bmi-calculator-flutter/build/app/generated/not_namespaced_r_class_sources/debug/r/androidx/lifecycle/R 2.java:9: error: class R is public, should be declared in a file named R.java
public final class R {
             ^
/Users/tomaszbzymek/Documents/NaukaFlutter/bmi-calculator-flutter/build/app/generated/not_namespaced_r_class_sources/debug/r/androidx/legacy/coreutils/R 2.java:9: error: class R is public, should be declared in a file named R.java
public final class R {
             ^
/Users/tomaszbzymek/Documents/NaukaFlutter/bmi-calculator-flutter/build/app/generated/not_namespaced_r_class_sources/debug/r/androidx/legacy/coreui/R 2.java:9: error: class R is public, should be declared in a file named R.java
public final class R {
             ^
/Users/tomaszbzymek/Documents/NaukaFlutter/bmi-calculator-flutter/build/app/generated/not_namespaced_r_class_sources/debug/r/androidx/documentfile/R 2.java:9: error: class R is public, should be declared in a file named R.java
public final class R {
             ^
/Users/tomaszbzymek/Documents/NaukaFlutter/bmi-calculator-flutter/build/app/generated/not_namespaced_r_class_sources/debug/r/androidx/print/R 2.java:9: error: class R is public, should be declared in a file named R.java
public final class R {
             ^
/Users/tomaszbzymek/Documents/NaukaFlutter/bmi-calculator-flutter/build/app/generated/not_namespaced_r_class_sources/debug/r/androidx/localbroadcastmanager/R 2.java:9: error: class R is public, should be declared in a file named R.java
public final class R {
             ^
/Users/tomaszbzymek/Documents/NaukaFlutter/bmi-calculator-flutter/build/app/generated/not_namespaced_r_class_sources/debug/r/androidx/cursoradapter/R 2.java:9: error: class R is public, should be declared in a file named R.java
public final class R {
             ^
/Users/tomaszbzymek/Documents/NaukaFlutter/bmi-calculator-flutter/build/app/generated/not_namespaced_r_class_sources/debug/r/androidx/swiperefreshlayout/R 2.java:9: error: class R is public, should be declared in a file named R.java
public final class R {
             ^
/Users/tomaszbzymek/Documents/NaukaFlutter/bmi-calculator-flutter/build/app/generated/not_namespaced_r_class_sources/debug/r/androidx/fragment/R 2.java:9: error: class R is public, should be declared in a file named R.java
public final class R {
             ^
/Users/tomaszbzymek/Documents/NaukaFlutter/bmi-calculator-flutter/build/app/generated/not_namespaced_r_class_sources/debug/r/androidx/loader/R 2.java:9: error: class R is public, should be declared in a file named R.java
public final class R {
             ^
/Users/tomaszbzymek/Documents/NaukaFlutter/bmi-calculator-flutter/build/app/generated/not_namespaced_r_class_sources/debug/r/androidx/arch/core/R 2.java:9: error: class R is public, should be declared in a file named R.java
public final class R {
             ^
/Users/tomaszbzymek/Documents/NaukaFlutter/bmi-calculator-flutter/build/app/generated/not_namespaced_r_class_sources/debug/r/androidx/customview/R 2.java:9: error: class R is public, should be declared in a file named R.java
public final class R {
             ^
/Users/tomaszbzymek/Documents/NaukaFlutter/bmi-calculator-flutter/build/app/generated/not_namespaced_r_class_sources/debug/r/androidx/slidingpanelayout/R 2.java:9: error: class R is public, should be declared in a file named R.java
public final class R {
             ^
/Users/tomaszbzymek/Documents/NaukaFlutter/bmi-calculator-flutter/build/app/generated/not_namespaced_r_class_sources/debug/r/androidx/coordinatorlayout/R 2.java:9: error: class R is public, should be declared in a file named R.java
public final class R {
             ^
/Users/tomaszbzymek/Documents/NaukaFlutter/bmi-calculator-flutter/build/app/generated/not_namespaced_r_class_sources/debug/r/co/appbrewery/bmicalculator/R 2.java:10: error: class R is public, should be declared in a file named R.java
public final class R {
             ^
/Users/tomaszbzymek/Documents/NaukaFlutter/bmi-calculator-flutter/build/app/generated/source/buildConfig/debug/co/appbrewery/bmicalculator/BuildConfig 2.java:6: error: class BuildConfig is public, should be declared in a file named BuildConfig.java
public final class BuildConfig {
             ^
25 errors

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 8s
Finished with error: Gradle task assembleDebug failed with exit code 1
```

**flutter run --verbos Log**
---
```
[  +18 ms] executing: [/usr/local/Caskroom/flutter/latest/flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[  +33 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[        ] 0b8abb4724aa590dd0f429683339b1e045a1594d
[        ] executing: [/usr/local/Caskroom/flutter/latest/flutter/] git describe --match v*.*.* --first-parent --long --tags
[  +10 ms] Exit code 0 from: git describe --match v*.*.* --first-parent --long --tags
[        ] v1.12.13+hotfix.8-0-g0b8abb472
[   +6 ms] executing: [/usr/local/Caskroom/flutter/latest/flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[   +8 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/stable
[        ] executing: [/usr/local/Caskroom/flutter/latest/flutter/] git ls-remote --get-url origin
[   +8 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[  +42 ms] executing: [/usr/local/Caskroom/flutter/latest/flutter/] git rev-parse --abbrev-ref HEAD
[   +9 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] stable
[   +4 ms] executing: sw_vers -productName
[  +12 ms] Exit code 0 from: sw_vers -productName
[        ] Mac OS X
[        ] executing: sw_vers -productVersion
[  +11 ms] Exit code 0 from: sw_vers -productVersion
[        ] 10.15.3
[        ] executing: sw_vers -buildVersion
[  +11 ms] Exit code 0 from: sw_vers -buildVersion
[        ] 19D76
[  +20 ms] executing: /usr/bin/xcode-select --print-path
[   +7 ms] Exit code 0 from: /usr/bin/xcode-select --print-path
[        ] /Applications/Xcode.app/Contents/Developer
[   +1 ms] executing: /usr/bin/xcodebuild -version
[ +804 ms] Exit code 0 from: /usr/bin/xcodebuild -version
[   +2 ms] Xcode 11.3.1
           Build version 11C504
[  +43 ms] executing: /Users/tomaszbzymek/Library/Android/sdk/platform-tools/adb devices -l
[   +5 ms] Exit code 0 from: /Users/tomaszbzymek/Library/Android/sdk/platform-tools/adb devices -l
[        ] List of devices attached
           emulator-5554          device product:sdk_gphone_x86_arm model:AOSP_on_IA_Emulator device:generic_x86_arm transport_id:9
[  +13 ms] executing: /usr/local/Caskroom/flutter/latest/flutter/bin/cache/artifacts/libimobiledevice/idevice_id -h
[  +65 ms] /usr/bin/xcrun simctl list --json devices
[  +77 ms] More than one device connected; please specify a device with the '-d <deviceId>' flag, or use '-d all' to act on all devices.
[   +3 ms] /Users/tomaszbzymek/Library/Android/sdk/platform-tools/adb -s emulator-5554 shell getprop
[  +22 ms] ro.hardware = ranchu
[   +5 ms] AOSP on IA Emulator • emulator-5554                        • android-x86 • Android 9 (API 28) (emulator)
[        ] iPhone 11 Pro Max   • F1103DC5-787D-477F-92E1-CD9DC04FDE04 • ios         • com.apple.CoreSimulator.SimRuntime.iOS-13-3 (simulator)
[   +9 ms] "flutter run" took 1 132ms.

#0      throwToolExit (package:flutter_tools/src/base/common.dart:28:3)
#1      RunCommand.validateCommand (package:flutter_tools/src/commands/run.dart:289:7)
<asynchronous suspension>
#2      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:590:11)
#3      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:515:33)
<asynchronous suspension>
#4      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:146:29)
#5      _rootRun (dart:async/zone.dart:1126:13)
#6      _CustomZone.run (dart:async/zone.dart:1023:19)
#7      _runZoned (dart:async/zone.dart:1518:10)
#8      runZoned (dart:async/zone.dart:1465:12)
#9      AppContext.run (package:flutter_tools/src/base/context.dart:145:18)
#10     FlutterCommand.run (package:flutter_tools/src/runner/flutter_command.dart:505:20)
#11     CommandRunner.runCommand (package:args/command_runner.dart:197:27)
#12     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:413:21)
<asynchronous suspension>
#13     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:146:29)
#14     _rootRun (dart:async/zone.dart:1126:13)
#15     _CustomZone.run (dart:async/zone.dart:1023:19)
#16     _runZoned (dart:async/zone.dart:1518:10)
#17     runZoned (dart:async/zone.dart:1465:12)
#18     AppContext.run (package:flutter_tools/src/base/context.dart:145:18)
#19     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:364:19)
#20     CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:112:25)
#21     new Future.sync (dart:async/future.dart:224:31)
#22     CommandRunner.run (package:args/command_runner.dart:112:14)
#23     FlutterCommandRunner.run (package:flutter_tools/src/runner/flutter_command_runner.dart:250:18)
#24     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:63:22)
#25     _rootRun (dart:async/zone.dart:1126:13)
#26     _CustomZone.run (dart:async/zone.dart:1023:19)
#27     _runZoned (dart:async/zone.dart:1518:10)
#28     runZoned (dart:async/zone.dart:1502:12)
#29     run.<anonymous closure> (package:flutter_tools/runner.dart:61:18)
<asynchronous suspension>
#30     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:146:29)
#31     _rootRun (dart:async/zone.dart:1126:13)
#32     _CustomZone.run (dart:async/zone.dart:1023:19)
#33     _runZoned (dart:async/zone.dart:1518:10)
#34     runZoned (dart:async/zone.dart:1465:12)
#35     AppContext.run (package:flutter_tools/src/base/context.dart:145:18)
#36     runInContext (package:flutter_tools/src/context_runner.dart:64:24)
#37     run (package:flutter_tools/runner.dart:50:10)
#38     main (package:flutter_tools/executable.dart:65:9)
#39     main (file:///usr/local/Caskroom/flutter/latest/flutter/packages/flutter_tools/bin/flutter_tools.dart:8:3)
#40     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:305:32)
#41     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:174:12)

```

**flutter analyze Log**
---
```
Analyzing Clima-Flutter...                                              
No issues found! (ran in 1.5s)
```

**flutter doctor -v Log**
---
```
[✓] Flutter (Channel stable, v1.12.13+hotfix.8, on Mac OS X 10.15.3 19D76, locale pl-GB)
    • Flutter version 1.12.13+hotfix.8 at /usr/local/Caskroom/flutter/latest/flutter
    • Framework revision 0b8abb4724 (4 days ago), 2020-02-11 11:44:36 -0800
    • Engine revision e1e6ced81d
    • Dart version 2.7.0

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/tomaszbzymek/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.3.1, Build version 11C504
    • CocoaPods version 1.8.4

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 43.0.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] Connected device (2 available)
    • AOSP on IA Emulator • emulator-5554                        • android-x86 • Android 9 (API 28) (emulator)
    • iPhone 11 Pro Max   • F1103DC5-787D-477F-92E1-CD9DC04FDE04 • ios         • com.apple.CoreSimulator.SimRuntime.iOS-13-3 (simulator)

• No issues found!
```

</details>

## What I've tired? 

* Restarting IDE (with cleaning cache)
* Restarting Emulator
* Wiping Emulator
* Creating a new Emulator
* `flutter clean` and `flutter pub cache repair`

## Solution

Open the folder `android` and delete the `.gradle` folder then click `Run`.

## Suggestion

I've found the solution after I've started writing this post but I'd like to suggest Flutter team to add deletion of above folder to `flutter clean` command

**Comment by abdvlz** [comment]
i dont know how to thank you man
