### ISSUE TITLE
[tool_crash] NoSuchMethodError: The getter 'environment' was called on null.Receiver: nullTried calling: environment

### ISSUE THREAD

**Issue by himanshu64** [flutter/flutter#50860]
## Command
```
flutter test --machine --start-paused test/widget_test.dart
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
NoSuchMethodError: NoSuchMethodError: The getter 'environment' was called on null.
Receiver: null
Tried calling: environment
```
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:53:5)
#1      JsonReporter._idForSuite.<anonymous closure> (package:test_core/src/runner/reporter/json.dart:184:38)
#2      _rootRunUnary (dart:async/zone.dart:1134:38)
#3      _CustomZone.runUnary (dart:async/zone.dart:1031:19)
#4      _FutureListener.handleValue (dart:async/future_impl.dart:140:18)
#5      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:682:45)
#6      Future._propagateToListeners (dart:async/future_impl.dart:711:32)
#7      Future._completeWithValue (dart:async/future_impl.dart:526:5)
#8      _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:34:15)
#9      _completeOnAsyncReturn (dart:async-patch/async_patch.dart:293:13)
#10     LoadSuite.suite (package:test_core/src/runner/load_suite.dart)
<asynchronous suspension>
#11     JsonReporter._idForSuite (package:test_core/src/runner/reporter/json.dart:176:13)
#12     JsonReporter._onTestStarted (package:test_core/src/runner/reporter/json.dart:120:19)
#13     _rootRunUnary (dart:async/zone.dart:1138:13)
#14     _CustomZone.runUnary (dart:async/zone.dart:1031:19)
#15     _CustomZone.runUnaryGuarded (dart:async/zone.dart:933:7)
#16     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11)
#17     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:266:7)
#18     _SyncBroadcastStreamController._sendData (dart:async/broadcast_stream_controller.dart:377:20)
```
```
[✓] Flutter (Channel master, v1.15.4-pre.73, on Linux 5.3.0-28-generic, locale en_IN)
    • Flutter version 1.15.4-pre.73 at /home/himanshu/softwares/flutter
    • Framework revision 0b43647aeb (16 hours ago), 2020-02-14 09:58:51 -0800
    • Engine revision d60f298d9e
    • Dart version 2.8.0 (build 2.8.0-dev.9.0 edd64e6d5c)

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /home/himanshu/Android/Sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • ANDROID_HOME = /home/himanshu/Android/Sdk
    • Java binary at: /snap/android-studio/82/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Android Studio (version 3.5)
    • Android Studio at /snap/android-studio/82/android-studio
    • Flutter plugin version 43.0.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] VS Code (version 1.42.0)
    • VS Code at /usr/share/code
    • Flutter extension version 3.8.1

[✓] Connected device (1 available)
    • ASUS X01AD • JCAAGF03L9339U6 • android-arm64 • Android 9 (API 28)

• No issues found!

```

## Flutter Application Metadata
**Version**: 1.0.0+1
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null

**Comment by jmagman** [comment]
Unfortunately we needed more than 20 lines of the stacktrace to see where this is coming from.

Are you able to reproduce again and attach the crash report text file?  Or run again with the verbose `-v` flag and paste the entire stacktrace?

**Comment by jmagman** [comment]
Actually, I see this in the crash logs:
```
at Object.noSuchMethod | (object_patch.dart:53 )
-- | --
  | at JsonReporter._idForSuite.<anonymous closure> | (json.dart:184 )
  | at _rootRunUnary | (zone.dart:1134 )
  | at _CustomZone.runUnary | (zone.dart:1031 )
  | at _FutureListener.handleValue | (future_impl.dart:140 )
  | at Future._propagateToListeners.handleValueCallback | (future_impl.dart:682 )
  | at Future._propagateToListeners | (future_impl.dart:711 )
  | at Future._completeWithValue | (future_impl.dart:526 )
  | at _AsyncAwaitCompleter.complete | (async_patch.dart:34 )
  | at _completeOnAsyncReturn | (async_patch.dart:293 )
  | at LoadSuite.suite | (load_suite.dart )
  | at <asynchronous gap> | (async )
  | at JsonReporter._idForSuite | (json.dart:176 )
  | at JsonReporter._onTestStarted | (json.dart:120 )
  | at _rootRunUnary | (zone.dart:1138 )
  | at _CustomZone.runUnary | (zone.dart:1031 )
  | at _CustomZone.runUnaryGuarded | (zone.dart:933 )
  | at _BufferingStreamSubscription._sendData | (stream_impl.dart:339 )
  | at _BufferingStreamSubscription._add | (stream_impl.dart:266 )
  | at _SyncBroadcastStreamController._sendData | (broadcast_stream_controller.dart:377 )
  | at _BroadcastStreamController.add | (broadcast_stream_controller.dart:252 )
  | at _rootRunUnary | (zone.dart:1134 )
  | at _CustomZone.runUnary | (zone.dart:1031 )
  | at _CustomZone.runUnaryGuarded | (zone.dart:933 )
  | at _BufferingStreamSubscription._sendData | (stream_impl.dart:339 )
  | at _BufferingStreamSubscription._add | (stream_impl.dart:266 )
  | at _SyncBroadcastStreamController._sendData | (broadcast_stream_controller.dart:377 )
  | at _BroadcastStreamController.add | (broadcast_stream_controller.dart:252 )
  | at LiveSuiteController.reportLiveTest | (live_suite_controller.dart:137 )
  | at Engine._addLoadSuite | (engine.dart:478 )
  | at Engine.run.<anonymous closure>.<anonymous closure> | (engine.dart:273 )
  | at <asynchronous gap> | (async )
  | at Engine.run.<anonymous closure> | (engine.dart:291 )
  | at _rootRunUnary | (zone.dart:1134 )
  | at _CustomZone.runUnary | (zone.dart:1031 )
  | at _CustomZone.runUnaryGuarded | (zone.dart:933 )
  | at _BufferingStreamSubscription._sendData | (stream_impl.dart:339 )
  | at _DelayedData.perform | (stream_impl.dart:594 )
  | at _StreamImplEvents.handleNext | (stream_impl.dart:710 )
  | at _PendingEvents.schedule.<anonymous closure> | (stream_impl.dart:670 )
  | at _rootRun | (zone.dart:1122 )
  | at _CustomZone.run | (zone.dart:1023 )
  | at _CustomZone.runGuarded | (zone.dart:925 )
  | at _CustomZone.bindCallbackGuarded.<anonymous closure> | (zone.dart:965 )
  | at _rootRun | (zone.dart:1126 )
  | at _CustomZone.run | (zone.dart:1023 )
  | at _CustomZone.runGuarded | (zone.dart:925 )
  | at _CustomZone.bindCallbackGuarded.<anonymous closure> | (zone.dart:965 )
  | at _microtaskLoop | (schedule_microtask.dart:43 )
  | at _startMicrotaskLoop | (schedule_microtask.dart:52 )
  | at _runPendingImmediateCallback | (isolate_patch.dart:118 )
  | at _RawReceivePortImpl._handleMessage | (isolate_patch.dart:169 )
```

**Comment by jmagman** [comment]
\cc @jonahwilliams

**Comment by jmagman** [comment]
First seen with https://github.com/flutter/flutter/pull/49310

**Comment by jmagman** [comment]
\cc @mdebbar

**Comment by BrianRichardson** [comment]
I am now experiencing much the same issue when trying to run unit tests.  My unit tests no longer run.

flutter --no-color test --machine --start-paused --verbose test

## exception

NoSuchMethodError: NoSuchMethodError: The getter 'environment' was called on null.
Receiver: null
Tried calling: environment

```
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:53:5)
#1      JsonReporter._idForSuite.<anonymous closure> (package:test_core/src/runner/reporter/json.dart:187:38)
#2      _rootRunUnary (dart:async/zone.dart:1192:38)
#3      _CustomZone.runUnary (dart:async/zone.dart:1085:19)
#4      _FutureListener.handleValue (dart:async/future_impl.dart:141:18)
#5      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:682:45)
#6      Future._propagateToListeners (dart:async/future_impl.dart:711:32)
#7      Future._completeWithValue (dart:async/future_impl.dart:526:5)
#8      _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:36:15)
#9      _completeOnAsyncReturn (dart:async-patch/async_patch.dart:298:13)
#10     LoadSuite.suite (package:test_core/src/runner/load_suite.dart)
<asynchronous suspension>
#11     JsonReporter._idForSuite (package:test_core/src/runner/reporter/json.dart:179:13)
#12     JsonReporter._onTestStarted (package:test_core/src/runner/reporter/json.dart:123:19)
#13     _rootRunUnary (dart:async/zone.dart:1196:13)
#14     _CustomZone.runUnary (dart:async/zone.dart:1085:19)
#15     _CustomZone.runUnaryGuarded (dart:async/zone.dart:987:7)
#16     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11)
#17     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:266:7)
#18     _SyncBroadcastStreamController._sendData (dart:async/broadcast_stream_controller.dart:378:20)
#19     _BroadcastStreamController.add (dart:async/broadcast_stream_controller.dart:252:5)
#20     _rootRunUnary (dart:async/zone.dart:1192:38)
#21     _CustomZone.runUnary (dart:async/zone.dart:1085:19)
#22     _CustomZone.runUnaryGuarded (dart:async/zone.dart:987:7)
#23     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11)
#24     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:266:7)
#25     _SyncBroadcastStreamController._sendData (dart:async/broadcast_stream_controller.dart:378:20)
#26     _BroadcastStreamController.add (dart:async/broadcast_stream_controller.dart:252:5)
#27     LiveSuiteController.reportLiveTest (package:test_core/src/runner/live_suite_controller.dart:147:30)
#28     Engine._addLoadSuite (package:test_core/src/runner/engine.dart:467:16)
#29     Engine.run.<anonymous closure>.<anonymous closure> (package:test_core/src/runner/engine.dart:264:32)
<asynchronous suspension>
#30     Engine.run.<anonymous closure>.<anonymous closure> (package:test_core/src/runner/engine.dart)
#31     Engine.run.<anonymous closure> (package:test_core/src/runner/engine.dart:279:8)
#32     _rootRunUnary (dart:async/zone.dart:1192:38)
#33     _CustomZone.runUnary (dart:async/zone.dart:1085:19)
#34     _CustomZone.runUnaryGuarded (dart:async/zone.dart:987:7)
#35     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11)
#36     _DelayedData.perform (dart:async/stream_impl.dart:594:14)
#37     _StreamImplEvents.handleNext (dart:async/stream_impl.dart:710:11)
#38     _PendingEvents.schedule.<anonymous closure> (dart:async/stream_impl.dart:670:7)
#39     _rootRun (dart:async/zone.dart:1180:38)
#40     _CustomZone.run (dart:async/zone.dart:1077:19)
#41     _CustomZone.runGuarded (dart:async/zone.dart:979:7)
#42     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1019:23)
#43     _rootRun (dart:async/zone.dart:1184:13)
#44     _CustomZone.run (dart:async/zone.dart:1077:19)
#45     _CustomZone.runGuarded (dart:async/zone.dart:979:7)
#46     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1019:23)
#47     _microtaskLoop (dart:async/schedule_microtask.dart:43:21)
#48     _startMicrotaskLoop (dart:async/schedule_microtask.dart:52:5)
#49     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
#50     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:169:5)
```

## flutter doctor

```
[✓] Flutter (Channel stable, v1.17.4, on Linux, locale en_GB.utf8)
    • Flutter version 1.17.4 at /home/login/Development/SDK/flutter
    • Framework revision 1ad9baa8b9 (11 days ago), 2020-06-17 14:41:16 -0700
    • Engine revision ee76268252
    • Dart version 2.8.4

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /home/login/Development/SDK/Android
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /var/lib/snapd/snap/android-studio/90/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Android Studio (version 4.0)
    • Android Studio at /var/lib/snapd/snap/android-studio/90/android-studio
    • Flutter plugin version 47.0.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[!] Connected device
    ! No devices available

! Doctor found issues in 1 category.

**Comment by jonahwilliams** [comment]
Fixed via https://github.com/dart-lang/test/pull/1273
