### ISSUE TITLE
Animated Container in PageView Doesn't Animate When Skipped To Page 3-4  Upon Launch Of The App 

### ISSUE THREAD

**Issue by vrajkishore** [flutter/flutter#50865]
```dart
import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';

class IndexTemp extends StatefulWidget {
  @override
  IndexTempState createState() => IndexTempState();
}

class IndexTempState extends State<IndexTemp> {
  PageController _controller =
      PageController(initialPage: 0, keepPage: true, viewportFraction: 0.98);

  int currentPage = 0;

  @override
  void initState() {
    // TODO: implement initState
    super.initState();
    _controller.addListener(() {
      int next = _controller.page.round();
      if (currentPage != next) {
        setState(() {
          currentPage = next;
        });
      }
    });
  }

  @override
  Widget build(BuildContext context) {
    // TODO: implement build
    return Scaffold(
      backgroundColor: Colors.indigo,
      appBar: AppBar(
        backgroundColor: Colors.indigo,
        title: Icon(
          Icons.star,
          color: Colors.yellow,
        ),
        actions: <Widget>[
          FlatButton(
            color: Colors.pink,
            child: Text(
              'Home',
              style: TextStyle(color: Colors.yellow),
            ),
            onPressed: () {
              _controller.jumpToPage(0);


            },
          ),
          FlatButton(
              onPressed: () {
                _controller.jumpToPage(1);

              },
              child: Text('About')),
          FlatButton(
              onPressed: () {
                _controller.jumpToPage(2);


              },
              child: Text('Solutions')),
          FlatButton(
              onPressed: () {

                _controller.jumpToPage(3);

              },
              child: Text('Why')),
        ],
      ),
      body: Padding(
        padding: const EdgeInsets.all(16.0),
        child: PageView(
          controller: _controller,
          scrollDirection: Axis.vertical,
          children: <Widget>[
            //page 1
            _buildHome(),
            _buildAboutUs(),
            _buildSolutions(),
            _buildWhyChooseUs()
          ],
        ),
      ),
    );
  }

  Widget _buildHome() {
    bool active = currentPage == 0 ? true : false;
    print('home active $active');
    double margin = active ? 40.0 : 120;
    var color = active ? Colors.indigo : Colors.red;

    return AnimatedContainer(
      duration: const Duration(seconds: 3),
      margin: EdgeInsets.fromLTRB(margin, 16.0, margin, 16.0),
      curve: Curves.easeIn,
      decoration: BoxDecoration(color: color),
      child: Center(
        child: Text('Home'),
      ),
    );
  }

  //this is about us page
  Widget _buildAboutUs() {
    bool active = currentPage == 1 ? true : false;
    print('about us active $active');
    double margin = active ? 40.0 : 120;
    var color = active ? Colors.indigo : Colors.red;

    return AnimatedContainer(
      duration: const Duration(seconds: 3),
      margin: EdgeInsets.fromLTRB(margin, 16.0, margin, 16.0),
      curve: Curves.easeIn,
      decoration: BoxDecoration(color: color),
      child: Center(
        child: Text('about us'),
      ),
    );
  }

  //this is solutions page
  Widget _buildSolutions() {
    bool active = currentPage == 2 ? true : false;
    print('solutions active $active');

    double margin = active ? 40.0 : 120;
    var color = active ? Colors.indigo : Colors.red;

    return AnimatedContainer(
      duration: const Duration(seconds: 3),
      margin: EdgeInsets.fromLTRB(margin, 16.0, margin, 16.0),
      curve: Curves.easeIn,
      decoration: BoxDecoration(color: color),
      child: Center(
        child: Text('solutions'),
      ),
    );
  }

  //this is why choose us page
  Widget _buildWhyChooseUs() {
    bool active = currentPage == 3 ? true : false;
    print('why choose us active $active');

    double margin = active ? 40.0 : 120;
    var color = active ? Colors.indigo : Colors.red;

    return AnimatedContainer(
      duration: const Duration(seconds: 3),
      margin: EdgeInsets.fromLTRB(margin, 16.0, margin, 16.0),
      curve: Curves.easeIn,
      decoration: BoxDecoration(color: color),
      child: Center(
        child: Text('why choose us'),
      ),
    );
  }
}

```

I want every new child of the pageview children to animated
there is no error. but the output is not as expected. when I go to immediate next or previous child, then they are animating. But if I jump to child 1-3 or 3-1, then they are not animating

```bash
vrajkishore@Vrajs-MacBook-Pro si-static-web % flutter run --verbose
[  +21 ms] executing: [/Users/vrajkishore/Desktop/my dev/flutter-ios/flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[  +29 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[   +1 ms] fabeb2a16f1d008ab8230f450c49141d35669798
[        ] executing: [/Users/vrajkishore/Desktop/my dev/flutter-ios/flutter/] git describe --match v*.*.* --first-parent --long --tags
[  +11 ms] Exit code 0 from: git describe --match v*.*.* --first-parent --long --tags
[        ] v1.14.6-0-gfabeb2a16
[   +6 ms] executing: [/Users/vrajkishore/Desktop/my dev/flutter-ios/flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[   +9 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/beta
[        ] executing: [/Users/vrajkishore/Desktop/my dev/flutter-ios/flutter/] git ls-remote --get-url origin
[  +12 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[  +50 ms] executing: [/Users/vrajkishore/Desktop/my dev/flutter-ios/flutter/] git rev-parse --abbrev-ref HEAD
[   +9 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] beta
[   +4 ms] executing: sw_vers -productName
[  +13 ms] Exit code 0 from: sw_vers -productName
[        ] Mac OS X
[        ] executing: sw_vers -productVersion
[  +12 ms] Exit code 0 from: sw_vers -productVersion
[        ] 10.15.3
[        ] executing: sw_vers -buildVersion
[  +11 ms] Exit code 0 from: sw_vers -buildVersion
[        ] 19D76
[  +25 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +2 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +28 ms] executing: /Users/vrajkishore/Library/Android/sdk/platform-tools/adb devices -l
[   +5 ms] Exit code 0 from: /Users/vrajkishore/Library/Android/sdk/platform-tools/adb devices -l
[        ] List of devices attached
[  +15 ms] executing: /Users/vrajkishore/Desktop/my dev/flutter-ios/flutter/bin/cache/artifacts/libimobiledevice/idevice_id -h
[  +50 ms] executing: /usr/bin/xcode-select --print-path
[   +7 ms] Exit code 0 from: /usr/bin/xcode-select --print-path
[        ] /Applications/Xcode.app/Contents/Developer
[        ] executing: /usr/bin/xcodebuild -version
[  +83 ms] Exit code 0 from: /usr/bin/xcodebuild -version
[        ] Xcode 11.3.1
           Build version 11C504
[   +3 ms] /usr/bin/xcrun simctl list --json devices
[  +86 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +41 ms] More than one device connected; please specify a device with the '-d <deviceId>' flag, or use '-d all' to act on all devices.
[  +36 ms] Chrome     • chrome     • web-javascript • Google Chrome 80.0.3987.106
[        ] Web Server • web-server • web-javascript • Flutter Tools
[   +9 ms] "flutter run" took 451ms.

#0      throwToolExit (package:flutter_tools/src/base/common.dart:27:3)
#1      RunCommand.validateCommand (package:flutter_tools/src/commands/run.dart:325:7)
<asynchronous suspension>
#2      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:619:11)
<asynchronous suspension>
#3      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:537:33)
<asynchronous suspension>
#4      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:29)
#5      _rootRun (dart:async/zone.dart:1126:13)
#6      _CustomZone.run (dart:async/zone.dart:1023:19)
#7      _runZoned (dart:async/zone.dart:1518:10)
#8      runZoned (dart:async/zone.dart:1465:12)
#9      AppContext.run (package:flutter_tools/src/base/context.dart:149:18)
#10     FlutterCommand.run (package:flutter_tools/src/runner/flutter_command.dart:527:20)
#11     CommandRunner.runCommand (package:args/command_runner.dart:197:27)
#12     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:338:21)
<asynchronous suspension>
#13     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:29)
#14     _rootRun (dart:async/zone.dart:1126:13)
#15     _CustomZone.run (dart:async/zone.dart:1023:19)
#16     _runZoned (dart:async/zone.dart:1518:10)
#17     runZoned (dart:async/zone.dart:1465:12)
#18     AppContext.run (package:flutter_tools/src/base/context.dart:149:18)
#19     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:288:19)
#20     CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:112:25)
#21     new Future.sync (dart:async/future.dart:224:31)
#22     CommandRunner.run (package:args/command_runner.dart:112:14)
#23     FlutterCommandRunner.run (package:flutter_tools/src/runner/flutter_command_runner.dart:231:18)
#24     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:64:22)
#25     _rootRun (dart:async/zone.dart:1126:13)
#26     _CustomZone.run (dart:async/zone.dart:1023:19)
#27     _runZoned (dart:async/zone.dart:1518:10)
#28     runZoned (dart:async/zone.dart:1502:12)
#29     run.<anonymous closure> (package:flutter_tools/runner.dart:62:18)
<asynchronous suspension>
#30     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:29)
#31     _rootRun (dart:async/zone.dart:1126:13)
#32     _CustomZone.run (dart:async/zone.dart:1023:19)
#33     _runZoned (dart:async/zone.dart:1518:10)
#34     runZoned (dart:async/zone.dart:1465:12)
#35     AppContext.run (package:flutter_tools/src/base/context.dart:149:18)
#36     runInContext (package:flutter_tools/src/context_runner.dart:64:24)
#37     run (package:flutter_tools/runner.dart:51:10)
#38     main (package:flutter_tools/executable.dart:65:9)
#39     main (file:///Users/vrajkishore/Desktop/my%20dev/flutter-ios/flutter/packages/flutter_tools/bin/flutter_tools.dart:8:3)
#40     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:299:32)
#41     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:168:12)

```

```console
vrajkishore@Vrajs-MacBook-Pro si-static-web % flutter analyze
Analyzing si-static-web...                                              
No issues found! (ran in 1.2s)
vrajkishore@Vrajs-MacBook-Pro si-static-web % flutter doctor -v
[✓] Flutter (Channel beta, v1.14.6, on Mac OS X 10.15.3 19D76, locale en-US)
    • Flutter version 1.14.6 at /Users/vrajkishore/Desktop/my dev/flutter-ios/flutter
    • Framework revision fabeb2a16f (3 weeks ago), 2020-01-28 07:56:51 -0800
    • Engine revision c4229bfbba
    • Dart version 2.8.0 (build 2.8.0-dev.5.0 fc3af737c7)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/vrajkishore/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.3.1, Build version 11C504
    • CocoaPods version 1.8.4

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 43.0.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] Connected device (2 available)
    • Chrome     • chrome     • web-javascript • Google Chrome 80.0.3987.106
    • Web Server • web-server • web-javascript • Flutter Tools

• No issues found!

```

**Comment by darshankawar** [comment]
<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel stable, 1.20.4, on Mac OS X 10.15.4 19E2269, locale en-IN)
    • Flutter version 1.20.4 at /Users/dhs/documents/Fluttersdk/flutter
    • Framework revision fba99f6cf9 (11 days ago), 2020-09-14 15:32:52 -0700
    • Engine revision d1bc06f032
    • Dart version 2.9.2

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
    • Android SDK at /Users/dhs/Library/Android/sdk
    • Platform android-30, build-tools 30.0.0
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.5, Build version 11E608c
    • CocoaPods version 1.9.3

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 46.0.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.49.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.11.0

[✓] Connected device (1 available)
    • Android SDK built for x86 (mobile) • emulator-5554 • android-x86 • Android
      10 (API 29) (emulator)

• No issues found!

```

</details>

**Comment by goderbauer** [comment]
The AnimatedContainer only animates when its properties change, not when it first builds.
