### ISSUE TITLE
Unable to find a matching configuration of project :firebase_core_web:   - None of the consumable configurations have attributes.

### ISSUE THREAD

**Issue by harshapulikollu** [flutter/flutter#50886]
Unable to build APK because of this error, Able to install app on iOS simulator.

Error: `Unable to find a matching configuration of project :firebase_core_web:   - None of the consumable configurations have attributes.`

Here is `flutter doctor -v`

```
`[✓] Flutter (Channel stable, v1.12.13+hotfix.8, on Mac OS X 10.15.3 19D76,
    locale en-GB)
    • Flutter version 1.12.13+hotfix.8 at
      /Users/harshapulikollu/Documents/development/flutter
    • Framework revision 0b8abb4724 (5 days ago), 2020-02-11 11:44:36 -0800
    • Engine revision e1e6ced81d
    • Dart version 2.7.0

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/harshapulikollu/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling
      support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.3.1, Build version 11C504
    • CocoaPods version 1.8.4

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 42.1.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build
      1.8.0_202-release-1483-b49-5587405)

[✓] VS Code (version 1.42.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.8.1

[!] Connected device
    ! No devices available

! Doctor found issues in 1 category.`
```

**Comment by TahaTesser** [comment]
Hi @harshapulikollu 
can you please provide your `flutter build apk --verbose`? 
Also, to better address the issue, would be helpful if you could post a minimal code sample to reproduce the problem
Thank you

**Comment by harshapulikollu** [comment]
Hi @TahaTesser , here is my `flutter build apk --verbose`

```
[  +36 ms] executing: [/Users/harshapulikollu/Documents/development/flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[  +48 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[        ] 0b8abb4724aa590dd0f429683339b1e045a1594d
[        ] executing: [/Users/harshapulikollu/Documents/development/flutter/] git describe --match v*.*.* --first-parent --long --tags
[  +78 ms] Exit code 0 from: git describe --match v*.*.* --first-parent --long --tags
[        ] v1.12.13+hotfix.8-0-g0b8abb472
[   +8 ms] executing: [/Users/harshapulikollu/Documents/development/flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[  +11 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/stable
[        ] executing: [/Users/harshapulikollu/Documents/development/flutter/] git ls-remote --get-url origin
[   +9 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[  +78 ms] executing: [/Users/harshapulikollu/Documents/development/flutter/] git rev-parse --abbrev-ref HEAD
[  +14 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] stable
[  +11 ms] executing: sw_vers -productName
[  +26 ms] Exit code 0 from: sw_vers -productName
[        ] Mac OS X
[        ] executing: sw_vers -productVersion
[  +14 ms] Exit code 0 from: sw_vers -productVersion
[        ] 10.15.3
[        ] executing: sw_vers -buildVersion
[  +18 ms] Exit code 0 from: sw_vers -buildVersion
[        ] 19D76
[  +35 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[   +7 ms] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +4 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +89 ms] Found plugin camera at /Users/harshapulikollu/.pub-cache/hosted/pub.dartlang.org/camera-0.5.7+3/
[  +10 ms] Found plugin cloud_firestore at /Users/harshapulikollu/.pub-cache/hosted/pub.dartlang.org/cloud_firestore-0.12.10+2/
[   +3 ms] Found plugin cloud_functions at /Users/harshapulikollu/.pub-cache/hosted/pub.dartlang.org/cloud_functions-0.4.1+6/
[  +16 ms] Found plugin firebase_auth at /Users/harshapulikollu/.pub-cache/hosted/pub.dartlang.org/firebase_auth-0.15.2/
[   +4 ms] Found plugin firebase_auth_web at /Users/harshapulikollu/.pub-cache/hosted/pub.dartlang.org/firebase_auth_web-0.1.1/
[   +4 ms] Found plugin firebase_core at /Users/harshapulikollu/.pub-cache/hosted/pub.dartlang.org/firebase_core-0.4.3+1/
[   +4 ms] Found plugin firebase_core_web at /Users/harshapulikollu/.pub-cache/hosted/pub.dartlang.org/firebase_core_web-0.1.1/
[   +2 ms] Found plugin firebase_messaging at /Users/harshapulikollu/.pub-cache/hosted/pub.dartlang.org/firebase_messaging-6.0.9/
[   +2 ms] Found plugin firebase_storage at /Users/harshapulikollu/.pub-cache/hosted/pub.dartlang.org/firebase_storage-3.0.8/
[  +25 ms] Found plugin fluttertoast at /Users/harshapulikollu/.pub-cache/hosted/pub.dartlang.org/fluttertoast-3.1.0/
[   +5 ms] Found plugin image_picker at /Users/harshapulikollu/.pub-cache/hosted/pub.dartlang.org/image_picker-0.6.2+1/
[  +13 ms] Found plugin path_provider at /Users/harshapulikollu/.pub-cache/hosted/pub.dartlang.org/path_provider-1.6.0/
[  +15 ms] Found plugin screen at /Users/harshapulikollu/.pub-cache/hosted/pub.dartlang.org/screen-0.0.5/
[   +5 ms] Found plugin shared_preferences at /Users/harshapulikollu/.pub-cache/hosted/pub.dartlang.org/shared_preferences-0.5.6/
[   +2 ms] Found plugin shared_preferences_macos at /Users/harshapulikollu/.pub-cache/hosted/pub.dartlang.org/shared_preferences_macos-0.0.1+5/
[   +4 ms] Found plugin shared_preferences_web at /Users/harshapulikollu/.pub-cache/hosted/pub.dartlang.org/shared_preferences_web-0.1.2+3/
[   +5 ms] Found plugin sqflite at /Users/harshapulikollu/.pub-cache/hosted/pub.dartlang.org/sqflite-1.1.8/
[  +13 ms] Found plugin url_launcher at /Users/harshapulikollu/.pub-cache/hosted/pub.dartlang.org/url_launcher-5.4.1/
[   +1 ms] Found plugin url_launcher_macos at /Users/harshapulikollu/.pub-cache/hosted/pub.dartlang.org/url_launcher_macos-0.0.1+2/
[   +3 ms] Found plugin url_launcher_web at /Users/harshapulikollu/.pub-cache/hosted/pub.dartlang.org/url_launcher_web-0.1.0+2/
[   +8 ms] Found plugin video_player at /Users/harshapulikollu/.pub-cache/hosted/pub.dartlang.org/video_player-0.10.5/
[   +3 ms] Found plugin video_player_web at /Users/harshapulikollu/.pub-cache/hosted/pub.dartlang.org/video_player_web-0.1.1+1/
[   +1 ms] Found plugin video_thumbnail at /Users/harshapulikollu/.pub-cache/hosted/pub.dartlang.org/video_thumbnail-0.1.6/
[  +51 ms] Found plugin camera at /Users/harshapulikollu/.pub-cache/hosted/pub.dartlang.org/camera-0.5.7+3/
[   +2 ms] Found plugin cloud_firestore at /Users/harshapulikollu/.pub-cache/hosted/pub.dartlang.org/cloud_firestore-0.12.10+2/
[   +1 ms] Found plugin cloud_functions at /Users/harshapulikollu/.pub-cache/hosted/pub.dartlang.org/cloud_functions-0.4.1+6/
[   +8 ms] Found plugin firebase_auth at /Users/harshapulikollu/.pub-cache/hosted/pub.dartlang.org/firebase_auth-0.15.2/
[   +2 ms] Found plugin firebase_auth_web at /Users/harshapulikollu/.pub-cache/hosted/pub.dartlang.org/firebase_auth_web-0.1.1/
[   +1 ms] Found plugin firebase_core at /Users/harshapulikollu/.pub-cache/hosted/pub.dartlang.org/firebase_core-0.4.3+1/
[   +2 ms] Found plugin firebase_core_web at /Users/harshapulikollu/.pub-cache/hosted/pub.dartlang.org/firebase_core_web-0.1.1/
[   +3 ms] Found plugin firebase_messaging at /Users/harshapulikollu/.pub-cache/hosted/pub.dartlang.org/firebase_messaging-6.0.9/
[   +2 ms] Found plugin firebase_storage at /Users/harshapulikollu/.pub-cache/hosted/pub.dartlang.org/firebase_storage-3.0.8/
[   +8 ms] Found plugin fluttertoast at /Users/harshapulikollu/.pub-cache/hosted/pub.dartlang.org/fluttertoast-3.1.0/
[   +3 ms] Found plugin image_picker at /Users/harshapulikollu/.pub-cache/hosted/pub.dartlang.org/image_picker-0.6.2+1/
[   +8 ms] Found plugin path_provider at /Users/harshapulikollu/.pub-cache/hosted/pub.dartlang.org/path_provider-1.6.0/
[   +5 ms] Found plugin screen at /Users/harshapulikollu/.pub-cache/hosted/pub.dartlang.org/screen-0.0.5/
[   +3 ms] Found plugin shared_preferences at /Users/harshapulikollu/.pub-cache/hosted/pub.dartlang.org/shared_preferences-0.5.6/
[   +1 ms] Found plugin shared_preferences_macos at /Users/harshapulikollu/.pub-cache/hosted/pub.dartlang.org/shared_preferences_macos-0.0.1+5/
[   +1 ms] Found plugin shared_preferences_web at /Users/harshapulikollu/.pub-cache/hosted/pub.dartlang.org/shared_preferences_web-0.1.2+3/
[   +3 ms] Found plugin sqflite at /Users/harshapulikollu/.pub-cache/hosted/pub.dartlang.org/sqflite-1.1.8/
[   +9 ms] Found plugin url_launcher at /Users/harshapulikollu/.pub-cache/hosted/pub.dartlang.org/url_launcher-5.4.1/
[   +1 ms] Found plugin url_launcher_macos at /Users/harshapulikollu/.pub-cache/hosted/pub.dartlang.org/url_launcher_macos-0.0.1+2/
[   +3 ms] Found plugin url_launcher_web at /Users/harshapulikollu/.pub-cache/hosted/pub.dartlang.org/url_launcher_web-0.1.0+2/
[   +2 ms] Found plugin video_player at /Users/harshapulikollu/.pub-cache/hosted/pub.dartlang.org/video_player-0.10.5/
[   +2 ms] Found plugin video_player_web at /Users/harshapulikollu/.pub-cache/hosted/pub.dartlang.org/video_player_web-0.1.1+1/
[   +1 ms] Found plugin video_thumbnail at /Users/harshapulikollu/.pub-cache/hosted/pub.dartlang.org/video_thumbnail-0.1.6/
[ +108 ms] Generating /Users/harshapulikollu/Documents/kara/android/app/src/main/java/io/flutter/plugins/GeneratedPluginRegistrant.java
[  +26 ms] executing: /usr/bin/xcodebuild -version
[ +140 ms] Exit code 0 from: /usr/bin/xcodebuild -version
[        ] Xcode 11.3.1
           Build version 11C504
[  +28 ms] You are building a fat APK that includes binaries for android-arm, android-arm64, android-x64.
[        ] If you are deploying the app to the Play Store, it's recommended to use app bundles or split the APK to reduce the APK size.
[        ]     To generate an app bundle, run:
[        ]         flutter build appbundle --target-platform android-arm,android-arm64,android-x64
[        ]         Learn more on: https://developer.android.com/guide/app-bundle
[        ]     To split the APKs per ABI, run:
[        ]         flutter build apk --target-platform android-arm,android-arm64,android-x64 --split-per-abi
[        ]         Learn more on:  https://developer.android.com/studio/build/configure-apk-splits#configure-abi-split
[  +24 ms] Running Gradle task 'assembleRelease'...
[   +2 ms] gradle.properties already sets `android.enableR8`
[   +4 ms] Using gradle from /Users/harshapulikollu/Documents/kara/android/gradlew.
[   +5 ms] executing: /usr/bin/plutil -convert json -o - /Applications/Android Studio.app/Contents/Info.plist
[  +12 ms] Exit code 0 from: /usr/bin/plutil -convert json -o - /Applications/Android Studio.app/Contents/Info.plist
[        ] {"CFBundleName":"Android
Studio","JVMOptions":{"ClassPath":"$APP_PACKAGE\/Contents\/lib\/bootstrap.jar:$APP_PACKAGE\/Contents\/lib\/extensions.jar:$APP_PACKAGE\/Contents\/lib\/util.jar:$APP_PACKAGE\/Contents\/lib\/jdom.jar
:$APP_PACKAGE\/Contents\/lib\/log4j.jar:$APP_PACKAGE\/Contents\/lib\/trove4j.jar:$APP_PACKAGE\/Contents\/lib\/jna.jar","JVMVersion":"1.8*,1.8+","WorkingDirectory":"$APP_PACKAGE\/Contents\/bin","Mai
nClass":"com.intellij.idea.Main","Properties":{"idea.paths.selector":"AndroidStudio3.5","idea.executable":"studio","idea.platform.prefix":"AndroidStudio","idea.home.path":"$APP_PACKAGE\/Contents"}}
,"LSArchitecturePriority":["x86_64"],"CFBundleVersion":"AI-191.8026.42.35.6010548","CFBundleDevelopmentRegion":"English","CFBundleDocumentTypes":[{"CFBundleTypeName":"Android Studio Project
File","CFBundleTypeExtensions":["ipr"],"CFBundleTypeRole":"Editor","CFBundleTypeIconFile":"studio.icns"},{"CFBundleTypeName":"All
documents","CFBundleTypeExtensions":["*"],"CFBundleTypeOSTypes":["****"],"CFBundleTypeRole":"Editor","LSTypeIsPackage":false}],"NSSupportsAutomaticGraphicsSwitching":true,"CFBundlePackageType":"APP
L","CFBundleIconFile":"studio.icns","NSHighResolutionCapable":true,"CFBundleShortVersionString":"3.5","CFBundleInfoDictionaryVersion":"6.0","CFBundleExecutable":"studio","LSRequiresNativeExecution"
:"YES","CFBundleURLTypes":[{"CFBundleTypeRole":"Editor","CFBundleURLName":"Stacktrace","CFBundleURLSchemes":["idea"]}],"CFBundleIdentifier":"com.google.android.studio","LSApplicationCategoryType":"
public.app-category.developer-tools","CFBundleSignature":"????","LSMinimumSystemVersion":"10.8","CFBundleGetInfoString":"Android Studio 3.5, build AI-191.8026.42.35.6010548. Copyright JetBrains
s.r.o., (c) 2000-2019"}
[  +15 ms] executing: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java -version
[  +77 ms] Exit code 0 from: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java -version
[        ] openjdk version "1.8.0_202-release"
           OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
           OpenJDK 64-Bit Server VM (build 25.202-b49-5587405, mixed mode)
[   +2 ms] executing: [/Users/harshapulikollu/Documents/kara/android/] /Users/harshapulikollu/Documents/kara/android/gradlew -Pverbose=true -Ptarget=lib/main.dart -Ptrack-widget-creation=true
-Pshrink=true -Ptarget-platform=android-arm,android-arm64,android-x64 assembleRelease
[ +817 ms] Welcome to Gradle 5.4.1!
[        ] Here are the highlights of this release:
[        ]  - Run builds with JDK12
[        ]  - New API for Incremental Tasks
[        ]  - Updates to native projects, including Swift 5 support
[        ] For more details see https://docs.gradle.org/5.4.1/release-notes.html
[ +385 ms] Starting a Gradle Daemon (subsequent builds will be faster)
[+19500 ms] FAILURE: Build failed with an exception.
[   +3 ms] * What went wrong:
[        ] Could not determine the dependencies of task ':firebase_core:compileReleaseAidl'.
[        ] > Could not resolve all task dependencies for configuration ':firebase_core:releaseCompileClasspath'.
[        ]    > Could not resolve project :firebase_core_web.
[        ]      Required by:
[        ]          project :firebase_core
[        ]       > Unable to find a matching configuration of project :firebase_core_web:
[        ]           - None of the consumable configurations have attributes.
[        ] * Try:
[        ] Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
[        ] * Get more help at https://help.gradle.org
[        ] BUILD FAILED in 20s
[        ] Deprecated Gradle features were used in this build, making it incompatible with Gradle 6.0.
[        ] Use '--warning-mode all' to show the individual deprecation warnings.
[        ] See https://docs.gradle.org/5.4.1/userguide/command_line_interface.html#sec:command_line_warnings
[ +545 ms] Running Gradle task 'assembleRelease'... (completed in 21.4s)
[   +6 ms] "flutter apk" took 22,234ms.
Gradle task assembleRelease failed with exit code 1

#0      throwToolExit (package:flutter_tools/src/base/common.dart:28:3)
#1      buildGradleApp (package:flutter_tools/src/android/gradle.dart:387:7)
#2      _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:73:64)
#3      _rootRunUnary (dart:async/zone.dart:1134:38)
#4      _CustomZone.runUnary (dart:async/zone.dart:1031:19)
#5      _FutureListener.handleValue (dart:async/future_impl.dart:139:18)
#6      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:680:45)
#7      Future._propagateToListeners (dart:async/future_impl.dart:709:32)
#8      Future._completeWithValue (dart:async/future_impl.dart:524:5)
#9      _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:32:15)
#10     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:290:13)
#11     _DefaultProcessUtils.stream (package:flutter_tools/src/base/process.dart)
#12     _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:73:64)
#13     _rootRunUnary (dart:async/zone.dart:1134:38)
#14     _CustomZone.runUnary (dart:async/zone.dart:1031:19)
#15     _FutureListener.handleValue (dart:async/future_impl.dart:139:18)
#16     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:680:45)
#17     Future._propagateToListeners (dart:async/future_impl.dart:709:32)
#18     Future._completeWithValue (dart:async/future_impl.dart:524:5)
#19     Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:554:7)
#20     _rootRun (dart:async/zone.dart:1126:13)
#21     _CustomZone.run (dart:async/zone.dart:1023:19)
#22     _CustomZone.runGuarded (dart:async/zone.dart:925:7)
#23     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:965:23)
#24     _microtaskLoop (dart:async/schedule_microtask.dart:43:21)
#25     _startMicrotaskLoop (dart:async/schedule_microtask.dart:52:5)
#26     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
#27     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:175:5)




```
I tried to reproduce the issue with new project but I failed to do so.  Don't know why it's happening to my existing working project.

**Comment by TahaTesser** [comment]
Hi @harshapulikollu 
Could you please try this [#issuecomment](https://github.com/FirebaseExtended/flutterfire/issues/1614#issuecomment-564947417)
Thank you

**Comment by harshapulikollu** [comment]
Hi @TahaTesser , I have tried `flutter pub cache repair` , `flutter clean` too couple of times before I raise this issue. 
Also now I have tried but I'm facing same error.

**Comment by TahaTesser** [comment]
Hi @harshapulikollu 
Can you please confirm you have the latest `firebase_core_web 0.1.1+2` on your existing app
Thank you

**Comment by harshapulikollu** [comment]
Hi @TahaTesser , Actually I don't have `firebase_core_web:` in my `pubspec.yaml` 
The app used to build before without this package in old flutter version `1.12.13+hotfix.5` (I guess) 
I'm encountering this issue after I upgraded my flutter last weekend.

**Comment by TahaTesser** [comment]
Hi @harshapulikollu 
Please list the packages you're using.
Thank you

**Comment by harshapulikollu** [comment]
Hi @TahaTesser , here are the packages I'm using
```
cupertino_icons: ^0.1.2
  shared_preferences: 0.5.6
  fluttertoast: 3.1.0
  provider:
  overlay_support: 1.0.2
  showcaseview: ^0.1.3
  cloud_firestore: ^0.12.10+2
  firebase_auth: 0.15.2
  flutter_datetime_picker: ^1.2.8
  image_picker: ^0.6.2+1
  firebase_storage: ^3.0.8
  cached_network_image: ^2.0.0-rc
  selectable_autolink_text: ^1.1.0
  video_thumbnail: 0.1.6
  extended_text_field:
  uuid:
  timeago: ^2.0.22
  chewie: 0.9.8+1
  video_player: 0.10.5
  intl: ^0.16.0
  cloud_functions: 0.4.1+6
  firebase_messaging: ^6.0.9
  url_launcher: ^5.4.1
  camera: ^0.5.7+3
  path_provider: ^1.6.0
  preload_page_view: 0.1.4
```

**Comment by VladyslavBondarenko** [comment]
@harshapulikollu 
Are you experiencing the same error if you try the latest versions of plugins?

cloud_firestore: ^0.13.2+3
firebase_auth: ^0.15.4
firebase_storage: ^3.1.1

**Comment by harshapulikollu** [comment]
Hi @VladyslavBondarenko , 
As you said I bumped my packges versions, then did `flutter pub cache repair` , `flutter clean `.
This time when I tried to build APK I got a different error.

```
Compiler message:

../../.pub-cache/hosted/pub.dartlang.org/firebase_auth-0.15.4/lib/src/firebase_auth.dart:340:10: Error: The method 'confirmPasswordReset' isn't defined for the class 'FirebaseAuthPlatform'.

 - 'FirebaseAuthPlatform' is from 'package:firebase_auth_platform_interface/firebase_auth_platform_interface.dart' ('../../.pub-cache/hosted/pub.dartlang.org/firebase_auth_platform_interface-1.1.2/lib/firebase_auth_platform_interface.dart').

Try correcting the name to the name of an existing method, or defining a method named 'confirmPasswordReset'.

        .confirmPasswordReset(app.name, oobCode, newPassword);

         ^^^^^^^^^^^^^^^^^^^^


Target kernel_snapshot failed: Exception: Errors during snapshot creation: null
build failed.



FAILURE: Build failed with an exception.



* Where:

Script '/Users/harshapulikollu/Documents/development/flutter/packages/flutter_tools/gradle/flutter.gradle' line: 780



* What went wrong:

Execution failed for task ':app:compileFlutterBuildRelease'.

> Process 'command '/Users/harshapulikollu/Documents/development/flutter/bin/flutter'' finished with non-zero exit value 1



* Try:

Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.



* Get more help at https://help.gradle.org



BUILD FAILED in 12s
Running Gradle task 'assembleRelease'...                           12.8s
Gradle task assembleRelease failed with exit code 1
Process finished with exit code 1
```

**Comment by u2633** [comment]
@harshapulikollu In my experience, I just downgrade to previous version and this issue was gone. You can try it.

**Comment by stuartmorgan** [comment]
Firebase plugins are no longer part of this project; this will need to be filed in the FlutterFire repository of it's still an issue.
