### ISSUE TITLE
[tool_crash] Instance of 'AppConnectionException'

### ISSUE THREAD

**Issue by 3lonious** [flutter/flutter#50887]
## Command
```
flutter run -d chrome
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
AppConnectionException: Instance of 'AppConnectionException'
```
#0      DevHandler._startLocalDebugService (package:dwds/src/handlers/dev_handler.dart:146:7)
<asynchronous suspension>
#1      DevHandler.loadAppServices (package:dwds/src/handlers/dev_handler.dart:181:32)
<asynchronous suspension>
#2      Dwds.debugConnection (package:dwds/dwds.dart:64:46)
#3      WebDevFS.connect.<anonymous closure> (package:flutter_tools/src/build_runner/devfs_web.dart:348:24)
#4      _rootRunUnary (dart:async/zone.dart:1134:38)
#5      _CustomZone.runUnary (dart:async/zone.dart:1031:19)
#6      _CustomZone.runUnaryGuarded (dart:async/zone.dart:933:7)
#7      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11)
#8      _DelayedData.perform (dart:async/stream_impl.dart:594:14)
#9      _StreamImplEvents.handleNext (dart:async/stream_impl.dart:710:11)
#10     _PendingEvents.schedule.<anonymous closure> (dart:async/stream_impl.dart:670:7)
#11     _rootRun (dart:async/zone.dart:1122:38)
#12     _CustomZone.run (dart:async/zone.dart:1023:19)
#13     _CustomZone.runGuarded (dart:async/zone.dart:925:7)
#14     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:965:23)
#15     _rootRun (dart:async/zone.dart:1126:13)
#16     _CustomZone.run (dart:async/zone.dart:1023:19)
#17     _CustomZone.runGuarded (dart:async/zone.dart:925:7)
```
```
[✓] Flutter (Channel master, v1.15.4-pre.82, on Mac OS X 10.15 19A602, locale en-CA)
    • Flutter version 1.15.4-pre.82 at /Users/elonsharar/flutter
    • Framework revision e481fcae52 (29 hours ago), 2020-02-14 22:34:30 -0800
    • Engine revision d60f298d9e
    • Dart version 2.8.0 (build 2.8.0-dev.9.0 edd64e6d5c)

[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/setup/#android-setup for detailed instructions).
      If the Android SDK has been installed to a custom location, set ANDROID_SDK_ROOT
      to that location.
      You may also want to add it to your PATH environment variable.


[✓] Xcode - develop for iOS and macOS (Xcode 11.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.3.1, Build version 11C504
    • CocoaPods version 1.8.4

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 3.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 33.4.1
    • Dart plugin version 182.5215
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)

[✓] IntelliJ IDEA Community Edition (version 2018.1.6)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 26.0.2
    • Dart plugin version 181.4892.1

[✓] VS Code (version 1.42.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 2.20.0

[✓] Connected device (2 available)
    • Chrome     • chrome     • web-javascript • Google Chrome 79.0.3945.130
    • Web Server • web-server • web-javascript • Flutter Tools

! Doctor found issues in 1 category.

```

## Flutter Application Metadata
**Version**: 1.0.0+1
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null

**Comment by rexali** [comment]
I also experienced this. pls help us
