### ISSUE TITLE
Connection closed before full header was received

### ISSUE THREAD

**Issue by heshesh2010** [flutter/flutter#50920]
```

> D/ViewRootImpl@746611[MainActivity](15799): ViewPostImeInputStage processPointer 0
D/ViewRootImpl@746611[MainActivity](15799): ViewPostImeInputStage processPointer 1
E/AccessibilityBridge(15799): VirtualView node must not be the root node.
E/AccessibilityBridge(15799): VirtualView node must not be the root node.
E/AccessibilityBridge(15799): VirtualView node must not be the root node.
E/AccessibilityBridge(15799): VirtualView node must not be the root node.
E/AccessibilityBridge(15799): VirtualView node must not be the root node.
E/flutter (15799): [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: Connection closed before full header was received
E/flutter (15799): #0      IOClient.send (package:http/src/io_client.dart:65:7)
E/flutter (15799): <asynchronous suspension>
E/flutter (15799): #1      getOrderStatus (package:order_vendor_app/src/repository/order_repository.dart:39:37)
E/flutter (15799): <asynchronous suspension>
E/flutter (15799): #2      OrderController.listenForOrderStatus (package:order_vendor_app/src/controllers/order_controller.dart:40:46)
E/flutter (15799): #3      OrderController.listenForOrders.<anonymous closure> (package:order_vendor_app/src/controllers/order_controller.dart:30:7)
E/flutter (15799): #4      _rootRun (dart:async/zone.dart:1122:38)
E/flutter (15799): #5      _CustomZone.run (dart:async/zone.dart:1023:19)
E/flutter (15799): #6      _CustomZone.runGuarded (dart:async/zone.dart:925:7)
E/flutter (15799): #7      _BufferingStreamSubscription._sendDone.sendDone (dart:async/stream_impl.dart:391:13)
E/flutter (15799): #8      _BufferingStreamSubscription._sendDone (dart:async/stream_impl.dart:401:15)
E/flutter (15799): #9      _BufferingStreamSubscription._close (dart:async/stream_impl.dart:285:7)
E/flutter (15799): #10     _ForwardingStream._handleDone (dart:async/stream_pipe.dart:108:10)
E/flutter (15799): #11     _ForwardingStreamSubscription._handleDone (dart:async/stream_pipe.dart:174:13)
E/flutter (15799): #12     _rootRun (dart:async/zone.dart:1122:38)
E/flutter (15799): #13     _CustomZone.run (dart:async/zone.dart:1023:19)
E/flutter (15799): #14     _CustomZone.runGuarded (dart:async/zone.dart:925:7)
E/flutter (15799): #15     _BufferingStreamSubscription._sendDone.sendDone (dart:async/stream_impl.dart:391:13)
E/flutter (15799): #16     _BufferingStreamSubscription._sendDone (dart:async/stream_impl.dart:401:15)
E/flutter (15799): #17     _BufferingStreamSubscription._close (dart:async/stream_impl.dart:285:7)
E/flutter (15799): #18     _ForwardingStream._handleDone (dart:async/stream_pipe.dart:108:10)
E/flutter (15799): #19     _ForwardingStreamSubscription._handleDone (dart:async/stream_pipe.dart:174:13)
E/flutter (15799): #20     _rootRun (dart:async/zone.dart:1122:38)
E/flutter (15799): #21     _CustomZone.run (dart:async/zone.dart:1023:19)
E/flutter (15799): #22     _CustomZone.runGuarded (dart:async/zone.dart:925:7)
E/flutter (15799): #23     _BufferingStreamSubscription._sendDone.sendDone (dart:async/stream_impl.dart:391:13)
E/flutter (15799): #24     _BufferingStreamSubscription._sendDone (dart:async/stream_impl.dart:401:15)
E/flutter (15799): #25     _BufferingStreamSubscription._close (dart:async/stream_impl.dart:285:7)
E/flutter (15799): #26     _ForwardingStream._handleDone (dart:async/stream_pipe.dart:108:10)
E/flutter (15799): #27     _ForwardingStreamSubscription._handleDone (dart:async/stream_pipe.dart:174:13)
E/flutter (15799): #28     _rootRun (dart:async/zone.dart:1122:38)
E/flutter (15799): #29     _CustomZone.run (dart:async/zone.dart:1023:19)
E/flutter (15799): #30     _CustomZone.runGuarded (dart:async/zone.dart:925:7)
E/flutter (15799): #31     _BufferingStreamSubscription._sendDone.sendDone (dart:async/stream_impl.dart:391:13)
E/flutter (15799): #32     _BufferingStreamSubscription._sendDone (dart:async/stream_impl.dart:401:15)
E/flutter (15799): #33     _BufferingStreamSubscription._close (dart:async/stream_impl.dart:285:7)
E/flutter (15799): #34     _SinkTransformerStreamSubscription._close (dart:async/stream_transformers.dart:98:11)
E/flutter (15799): #35     _EventSinkWrapper.close (dart:async/stream_transformers.dart:25:11)
E/flutter (15799): #36     _JsonStringDecoderSink.close (dart:convert-patch/convert_patch.dart:1492:11)
E/flutter (15799): #37     _ConverterStreamEventSink.close (dart:convert/chunked_conversion.dart:82:18)
E/flutter (15799): #38     _SinkTransformerStreamSubscription._handleDone (dart:async/stream_transformers.dart:143:24)
E/flutter (15799): #39     _rootRun (dart:async/zone.dart:1122:38)
E/flutter (15799): #40     _CustomZone.run (dart:async/zone.dart:1023:19)
E/flutter (15799): #41     _CustomZone.runGuarded (dart:async/zone.dart:925:7)
E/flutter (15799): #42     _BufferingStreamSubscription._sendDone.sendDone (dart:async/stream_impl.dart:391:13)
E/flutter (15799): #43     _BufferingStreamSubscription._sendDone (dart:async/stream_impl.dart:401:15)
E/flutter (15799): #44     _BufferingStreamSubscription._close (dart:async/stream_impl.dart:285:7)
E/flutter (15799): #45     _SinkTransformerStreamSubscription._close (dart:async/stream_transformers.dart:98:11)
E/flutter (15799): #46     _EventSinkWrapper.close (dart:async/stream_transformers.dart:25:11)
E/flutter (15799): #47     _StringAdapterSink.close (dart:convert/string_conversion.dart:251:11)
E/flutter (15799): #48     _Utf8ConversionSink.close (dart:convert/string_conversion.dart:302:20)
E/flutter (15799): #49     _ConverterStreamEventSink.close (dart:convert/chunked_conversion.dart:82:18)
E/flutter (15799): #50     _SinkTransformerStreamSubscription._handleDo
I/flutter (15799): ══╡ EXCEPTION CAUGHT BY IMAGE RESOURCE SERVICE ╞════════════════════════════════════════════════════
I/flutter (15799): The following HttpException was thrown resolving an image codec:
I/flutter (15799): Connection closed before full header was received, uri =
I/flutter (15799): http://148.251.32.37/~salalordercom/public/storage/app/public/65/conversions/api-thumb.jpg
I/flutter (15799): 
I/flutter (15799): When the exception was thrown, this was the stack:
I/flutter (15799): #0      NetworkImage._loadAsync (package:flutter/src/painting/_network_image_io.dart:88:43)
I/flutter (15799): <asynchronous suspension>
I/flutter (15799): #1      NetworkImage.load (package:flutter/src/painting/_network_image_io.dart:47:14)
I/flutter (15799): #2      ImageProvider.resolve.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:flutter/src/painting/image_provider.dart:327:17)
I/flutter (15799): #3      ImageCache.putIfAbsent (package:flutter/src/painting/image_cache.dart:160:22)
I/flutter (15799): #4      ImageProvider.resolve.<anonymous closure>.<anonymous closure> (package:flutter/src/painting/image_provider.dart:325:84)
I/flutter (15799): #5      SynchronousFuture.then (package:flutter/src/foundation/synchronous_future.dart:38:29)
I/flutter (15799): #6      ImageProvider.resolve.<anonymous closure> (package:flutter/src/painting/image_provider.dart:323:11)
I/flutter (15799): #10     ImageProvider.resolve (package:flutter/src/painting/image_provider.dart:315:16)
I/flutter (15799): #11     DecorationImagePainter.paint (package:flutter/src/painting/decoration_image.dart:240:55)
I/flutter (15799): #12     _BoxDecorationPainter._paintBackgroundImage (package:flutter/src/painting/box_decoration.dart:448:19)
I/flutter (15799): #13     _BoxDecorationPainter.paint (package:flutter/src/painting/box_decoration.dart:466:5)
I/flutter (15799): #14     RenderDecoratedBox.paint (package:flutter/src/rendering/proxy_box.dart:1976:16)
I/flutter (15799): #15     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2219:7)
I/flutter (15799): #16     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:184:13)
I/flutter (15799): #17     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:123:15)
I/flutter (15799): #18     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2219:7)
I/flutter (15799): #19     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:184:13)
I/flutter (15799): #20     RenderBoxContainerDefaultsMixin.defaultPaint (package:flutter/src/rendering/box.dart:2508:15)
I/flutter (15799): #21     RenderFlex.paint (package:flutter/src/rendering/flex.dart:948:7)
I/flutter (15799): #22     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2219:7)
I/flutter (15799): #23     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:184:13)
I/flutter (15799): #24     RenderShiftedBox.paint (package:flutter/src/rendering/shifted_box.dart:70:15)
I/flutter (15799): #25     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2219:7)
I/flutter (15799): #26     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:184:13)
I/flutter (15799): #27     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:123:15)
I/flutter (15799): #28     RenderDecoratedBox.paint (package:flutter/src/rendering/proxy_box.dart:1995:11)
I/flutter (15799): #29     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2219:7)
I/flutter (15799): #30     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:184:13)
I/flutter (15799): #31     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:123:15)
I/flutter (15799): #32     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2219:7)
I/flutter (15799): #33     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:184:13)
I/flutter (15799): #34     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:123:15)
I/flutter (15799): #35     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2219:7)
I/flutter (15799): #36     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:184:13)
I/flutter (15799): #37     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:123:15)
I/flutter (15799): #38     RenderMouseRegion.paint (package:flutter/src/rendering/proxy_box.dart:2787:13)
I/flutter (15799): #39     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2219:7)
I/flutter (15799): #40     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:184:13)
I/flutter (15799): #41     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:123:15)
I/flutter (15799): #42     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2219:7)
I/flutter (15799): #43     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:184:13)
I/flutter (15799): #44     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:123:15)
I/flutter (15799): #45     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2219:7)
I/flutter (15799): #46     PaintingContext._repaintCompositedChild (package:flutter/src/rendering/object.dart:135:11)
I/flutter (15799): #47     PaintingContext.repaintCompositedChild (package:flutter/src/rendering/object.dart:95:5)
I/flutter (15799): #48     PaintingContext._compositeChild (package:flutter/src/rendering/object.dart:201:7)
I/flutter (15799): #49     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:182:7)
I/flutter (15799): #50     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:123:15)
I/flutter (15799): #51     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2219:7)
I/flutter (15799): #52     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:184:13)
I/flutter (15799): #53     RenderSliverMultiBoxAdaptor.paint (package:flutter/src/rendering/sliver_multi_box_adaptor.dart:640:17)
I/flutter (15799): #54     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2219:7)
I/flutter (15799): #55     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:184:13)
I/flutter (15799): #56     RenderSliverEdgeInsetsPadding.paint (package:flutter/src/rendering/sliver_padding.dart:275:15)
I/flutter (15799): #57     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2219:7)
I/flutter (15799): #58     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:184:13)
I/flutter (15799): #59     RenderViewportBase._paintContents (package:flutter/src/rendering/viewport.dart:531:17)
I/flutter (15799): #60     RenderViewportBase.paint (package:flutter/src/rendering/viewport.dart:524:7)
I/flutter (15799): #61     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2219:7)
I/flutter (15799): #62     PaintingContext._repaintCompositedChild (package:flutter/src/rendering/object.dart:135:11)
I/flutter (15799): #63     PaintingContext.repaintCompositedChild (package:flutter/src/rendering/object.dart:95:5)
I/flutter (15799): #64     PaintingContext._compositeChild (package:flutter/src/rendering/object.dart:201:7)
I/flutter (15799): #65     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:182:7)
I/flutter (15799): #66     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:123:15)
I/flutter (15799): #67     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2219:7)
I/flutter (15799): #68     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:184:13)
I/flutter (15799): #69     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:123:15)
I/flutter (15799): #70     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2219:7)
I/flutter (15799): #71     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:184:13)
I/flutter (15799): #72     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:123:15)
I/flutter (15799): #73     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2219:7)
I/flutter (15799): #74     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:184:13)
I/flutter (15799): #75     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:123:15)
I/flutter (15799): #76     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2219:7)
I/flutter (15799): #77     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:184:13)
I/flutter (15799): #78     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:123:15)
I/flutter (15799): #79     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2219:7)
I/flutter (15799): #80     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:184:13)
I/flutter (15799): #81     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:123:15)
I/flutter (15799): #82     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2219:7)
I/flutter (15799): #83     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:184:13)
I/flutter (15799): #84     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:123:15)
I/flutter (15799): #85     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2219:7)
I/flutter (15799): #86     PaintingContext._repaintCompositedChild (package:flutter/src/rendering/object.dart:135:11)
I/flutter (15799): #87     PaintingContext.repaintCompositedChild (package:flutter/src/rendering/object.dart:95:5)
I/flutter (15799): #88     PaintingContext._compositeChild (package:flutter/src/rendering/object.dart:201:7)
I/flutter (15799): #89     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:182:7)
I/flutter (15799): #90     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:123:15)
I/flutter (15799): #91     RenderCustomPaint.paint (package:flutter/src/rendering/custom_paint.dart:575:11)
I/flutter (15799): #92     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2219:7)
I/flutter (15799): #93     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:184:13)
I/flutter (15799): #94     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:123:15)
I/flutter (15799): #95     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2219:7)
I/flutter (15799): #96     PaintingContext._repaintCompositedChild (package:flutter/src/rendering/object.dart:135:11)
I/flutter (15799): #97     PaintingContext.repaintCompositedChild (package:flutter/src/rendering/object.dart:95:5)
I/flutter (15799): #98     PaintingContext._compositeChild (package:flutter/src/rendering/object.dart:201:7)
I/flutter (15799): #99     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:182:7)
I/flutter (15799): #100    RenderBoxContainerDefaultsMixin.defaultPaint (package:flutter/src/rendering/box.dart:2508:15)
I/flutter (15799): #101    RenderFlex.paint (package:flutter/src/rendering/flex.dart:948:7)
I/flutter (15799): #102    RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2219:7)
I/flutter (15799): #103    PaintingContext.paintChild (package:flutter/src/rendering/object.dart:184:13)
I/flutter (15799): #104    RenderShiftedBox.paint (package:flutter/src/rendering/shifted_box.dart:70:15)
I/flutter (15799): #105    RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2219:7)
I/flutter (15799): #106    PaintingContext.paintChild (package:flutter/src/rendering/object.dart:184:13)
I/flutter (15799): #107    _RenderSingleChildViewport.paint.paintContents (package:flutter/src/widgets/single_child_scroll_view.dart:533:17)
I/flutter (15799): #108    PaintingContext.pushLayer (package:flutter/src/rendering/object.dart:384:12)
I/flutter (15799): #109    PaintingContext.pushClipRect (package:flutter/src/rendering/object.dart:426:7)
I/flutter (15799): #110    _RenderSingleChildViewport.paint (package:flutter/src/widgets/single_child_scroll_view.dart:537:17)
I/flutter (15799): #111    RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2219:7)
I/flutter (15799): #112    PaintingContext._repaintCompositedChild (package:flutter/src/rendering/object.dart:135:11)
I/flutter (15799): #113    PaintingContext.repaintCompositedChild (package:flutter/src/rendering/object.dart:95:5)
I/flutter (15799): #114    PipelineOwner.flushPaint (package:flutter/src/rendering/object.dart:937:29)
I/flutter (15799): #115    RendererBinding.drawFrame (package:flutter/src/rendering/binding.dart:346:19)
I/flutter (15799): #116    WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:774:13)
I/flutter (15799): #117    RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:283:5)
I/flutter (15799): #118    SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1102:15)
I/flutter (15799): #119    SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1041:9)
I/flutter (15799): #120    SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:957:5)
I/flutter (15799): #124    _invoke (dart:ui/hooks.dart:259:10)
I/flutter (15799): #125    _drawFrame (dart:ui/hooks.dart:217:3)
I/flutter (15799): (elided 6 frames from package dart:async)
I/flutter (15799): 
I/flutter (15799): Image provider:
I/flutter (15799):   NetworkImage("http://148.251.32.37/~salalordercom/public/storage/app/public/65/conversions/api-thumb.jpg",
I/flutter (15799):   scale: 1.0)
I/flutter (15799): Image key:
I/flutter (15799):   NetworkImage("http://148.251.32.37/~salalordercom/public/storage/app/public/65/conversions/api-thumb.jpg",
I/flutter (15799):   scale: 1.0)
I/flutter (15799): ════════════════════════════════════════════════════════════════════════════════════════════════════
I/flutter (15799): Another exception was thrown: HTTP request failed, statusCode: 500, http://148.251.32.37/~salalordercom/public/storage/app/public/156/conversions/api-thumb.jpg
I/flutter (15799): Another exception was thrown: HTTP request failed, statusCode: 500, http://148.251.32.37/~salalordercom/public/storage/app/public/154/conversions/api-thumb.jpg

```

**Comment by TahaTesser** [comment]
Hi @heshesh2010 
can you please provide your `flutter doctor -v` and `flutter run --verbose`? 
Also, to better address the issue, would be helpful if you could post a minimal code sample to reproduce the problem 
Thank you

**Comment by heshesh2010** [comment]
here is flutter doctor

> C:\Users\Hesham elnemr\Desktop\order_vendorApp>flutter doctor -v
[√] Flutter (Channel stable, v1.12.13+hotfix.8, on Microsoft Windows [Version 10.0.17763.1039], locale en-US)
    • Flutter version 1.12.13+hotfix.8 at C:\flutter
    • Framework revision 0b8abb4724 (6 days ago), 2020-02-11 11:44:36 -0800
    • Engine revision e1e6ced81d
    • Dart version 2.7.0

[!] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at C:\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • ANDROID_HOME = C:\sdk
    • ANDROID_SDK_ROOT = C:\sdk
    • Java binary at: C:\Users\Hesham elnemr\Desktop\android stuido beta\android-studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)
    X Android license status unknown.
      Try re-installing or updating your Android SDK Manager.
      See https://developer.android.com/studio/#downloads or visit https://flutter.dev/setup/#android-setup for detailed instructions.

[√] Android Studio (version 3.5)
    • Android Studio at C:\Users\Hesham elnemr\Desktop\android stuido beta\android-studio
    • Flutter plugin version 43.0.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)

[√] Connected device (2 available)
    • SM N920C            • 0117115571d23701 • android-arm64 • Android 7.0 (API 24)
    • AOSP on IA Emulator • emulator-5554    • android-x86   • Android 9 (API 28) (emulator)

here is 
> C:\Users\Hesham elnemr\Desktop\order_vendorApp>flutter run --verbose
[  +41 ms] executing: [C:\flutter\] git -c log.showSignature=false log -n 1 --pretty=format:%H
[  +74 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[        ] 0b8abb4724aa590dd0f429683339b1e045a1594d
[        ] executing: [C:\flutter\] git describe --match v*.*.* --first-parent --long --tags
[  +76 ms] Exit code 0 from: git describe --match v*.*.* --first-parent --long --tags
[        ] v1.12.13+hotfix.8-0-g0b8abb472
[  +10 ms] executing: [C:\flutter\] git rev-parse --abbrev-ref --symbolic @{u}
[  +51 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/stable
[        ] executing: [C:\flutter\] git ls-remote --get-url origin
[  +41 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[ +107 ms] executing: [C:\flutter\] git rev-parse --abbrev-ref HEAD
[  +66 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] stable
[ +189 ms] executing: C:\sdk\platform-tools\adb.exe devices -l
[  +33 ms] Exit code 0 from: C:\sdk\platform-tools\adb.exe devices -l
[   +1 ms] List of devices attached
           0117115571d23701       device product:nobleltejv model:SM_N920C device:noblelte transport_id:5
           emulator-5554          device product:sdk_gphone_x86_arm model:AOSP_on_IA_Emulator device:generic_x86_arm transport_id:3
[  +24 ms] More than one device connected; please specify a device with the '-d <deviceId>' flag, or use '-d all' to act on all devices.
[   +7 ms] C:\sdk\platform-tools\adb.exe -s 0117115571d23701 shell getprop
[ +173 ms] ro.hardware = samsungexynos7420
[   +2 ms] C:\sdk\platform-tools\adb.exe -s emulator-5554 shell getprop
[  +65 ms] ro.hardware = ranchu
[   +4 ms] SM N920C            • 0117115571d23701 • android-arm64 • Android 7.0 (API 24)
[   +2 ms] AOSP on IA Emulator • emulator-5554    • android-x86   • Android 9 (API 28) (emulator)
[  +13 ms] "flutter run" took 584ms.

#0      throwToolExit (package:flutter_tools/src/base/common.dart:28:3)
#1      RunCommand.validateCommand (package:flutter_tools/src/commands/run.dart:289:7)
<asynchronous suspension>
#2      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:590:11)
#3      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:515:33)
<asynchronous suspension>
#4      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:146:29)
#5      _rootRun (dart:async/zone.dart:1126:13)
#6      _CustomZone.run (dart:async/zone.dart:1023:19)
#7      _runZoned (dart:async/zone.dart:1518:10)
#8      runZoned (dart:async/zone.dart:1465:12)
#9      AppContext.run (package:flutter_tools/src/base/context.dart:145:18)
#10     FlutterCommand.run (package:flutter_tools/src/runner/flutter_command.dart:505:20)
#11     CommandRunner.runCommand (package:args/command_runner.dart:197:27)
#12     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:413:21)
<asynchronous suspension>
#13     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:146:29)
#14     _rootRun (dart:async/zone.dart:1126:13)
#15     _CustomZone.run (dart:async/zone.dart:1023:19)
#16     _runZoned (dart:async/zone.dart:1518:10)
#17     runZoned (dart:async/zone.dart:1465:12)
#18     AppContext.run (package:flutter_tools/src/base/context.dart:145:18)
#19     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:364:19)
#20     CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:112:25)
#21     new Future.sync (dart:async/future.dart:224:31)
#22     CommandRunner.run (package:args/command_runner.dart:112:14)
#23     FlutterCommandRunner.run (package:flutter_tools/src/runner/flutter_command_runner.dart:250:18)
#24     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:63:22)
#25     _rootRun (dart:async/zone.dart:1126:13)
#26     _CustomZone.run (dart:async/zone.dart:1023:19)
#27     _runZoned (dart:async/zone.dart:1518:10)
#28     runZoned (dart:async/zone.dart:1502:12)
#29     run.<anonymous closure> (package:flutter_tools/runner.dart:61:18)
<asynchronous suspension>
#30     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:146:29)
#31     _rootRun (dart:async/zone.dart:1126:13)
#32     _CustomZone.run (dart:async/zone.dart:1023:19)
#33     _runZoned (dart:async/zone.dart:1518:10)
#34     runZoned (dart:async/zone.dart:1465:12)
#35     AppContext.run (package:flutter_tools/src/base/context.dart:145:18)
#36     runInContext (package:flutter_tools/src/context_runner.dart:64:24)
#37     run (package:flutter_tools/runner.dart:50:10)
#38     main (package:flutter_tools/executable.dart:65:9)
#39     main (file:///C:/flutter/packages/flutter_tools/bin/flutter_tools.dart:8:3)
#40     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:305:32)
#41     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:174:12)

and here is my code this happnes when calling any http request from api 

Future<Stream<RecentConversations>> getRecentConversations() async {
  User _user = await getCurrentUser();
  final String _apiToken = 'api_token=${_user.apiToken}';
  final String url =
      '${GlobalConfiguration().getString('api_base_url')}restaurant/conversation?$_apiToken';

  final client = new http.Client();
  final streamedRest = await client.send(http.Request('get', Uri.parse(url)));

  return streamedRest.stream
      .transform(utf8.decoder)
      .transform(json.decoder)
      .map((data) => Helper.getData(data))
      .expand((data) => (data as List))
      .map((data) {
    return RecentConversations.fromMap(data);
  });
}

**Comment by jonahwilliams** [comment]
This stack trace indicates that your application's own code failed to connect to whatever backend is in order_repository.dart. This does not indicate a bug with and/or the tool:


```
E/flutter (15799): #0      IOClient.send (package:http/src/io_client.dart:65:7)
E/flutter (15799): <asynchronous suspension>
E/flutter (15799): #1      getOrderStatus (package:order_vendor_app/src/repository/order_repository.dart:39:37)
E/flutter (15799): <asynchronous suspension>
E/flutter (15799): #2      OrderController.listenForOrderStatus (package:order_vendor_app/src/controllers/order_controller.dart:40:46)
E/flutter (15799): #3      OrderController.listenForOrders.<anonymous closure> (package:order_vendor_app/src/controllers/order_controller.dart:30:7)
```

**Comment by heshesh2010** [comment]
no this is not blocking from api server backend, i have updated to beta channel and it now worked as same code, so there is bug in stable channel , i have tested it in real device and emulator also

**Comment by qimingweng** [comment]
We're seeing (possibly) this issue too. On production builds on certain devices, and on the first load of the development build, the first few http calls we make to the server to set up the user do not succeed. In fact, the API does not even receive the requests. I wonder if this is related to this issue: https://github.com/flutter/flutter/issues/41573
