### ISSUE TITLE
flutter run -d chrome: Unable to find modules for some sources

### ISSUE THREAD

**Issue by agordeev** [flutter/flutter#50975]
I'm having the exact same issue as these closed ones: 

https://github.com/flutter/flutter/issues/48481

https://github.com/flutter/flutter/issues/41012

Flutter version I'm using is 1.15.3. I'm trying to use my own package as a dependency, and when I run `flutter run -d chrome`, it fails with either

```
Unable to find modules for some sources, this is usually the result of either a
bad import, a missing dependency in a package (or possibly a dev_dependency
needs to move to a real dependency), or a build failure (if importing a
generated file).

Please check the following imports:

`import 'package:data_access/data_access.dart';` from .....
Failed after 76ms
Failed to build application for the Web.
Exited (sigterm)
```

or no error message at all:

```
Launching lib/main.dart on Chrome in debug mode...
Failed after 3.2s                                                       
Building application for the web...                                11.6s
Failed to build application for the Web.
```

The verbose log is:
<details>
  <summary>Verbose log</summary>

  ```  ~/flutter_dev/bin/flutter run -d chrome -v
  [  +32 ms] executing: [/Users/andrey/flutter_dev/] git -c log.showSignature=false log -n 1 --pretty=format:%H
  [  +45 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
  [        ] 67826bdce54505760fe83b7ead70bdb5af6fe9f2
  [        ] executing: [/Users/andrey/flutter_dev/] git describe --match v*.*.* --first-parent --long --tags
  [  +17 ms] Exit code 0 from: git describe --match v*.*.* --first-parent --long --tags
  [        ] v1.15.3-0-g67826bdce
  [   +7 ms] executing: [/Users/andrey/flutter_dev/] git rev-parse --abbrev-ref --symbolic @{u}
  [  +11 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
  [        ] origin/dev
  [        ] executing: [/Users/andrey/flutter_dev/] git ls-remote --get-url origin
  [  +10 ms] Exit code 0 from: git ls-remote --get-url origin
  [        ] https://github.com/flutter/flutter.git
  [  +52 ms] executing: [/Users/andrey/flutter_dev/] git rev-parse --abbrev-ref HEAD
  [  +12 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
  [        ] dev
  [   +5 ms] executing: sw_vers -productName
  [  +15 ms] Exit code 0 from: sw_vers -productName
  [        ] Mac OS X
  [        ] executing: sw_vers -productVersion
  [  +14 ms] Exit code 0 from: sw_vers -productVersion
  [        ] 10.15.3
  [        ] executing: sw_vers -buildVersion
  [  +15 ms] Exit code 0 from: sw_vers -buildVersion
  [        ] 19D76
  [  +29 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
  [        ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
  [        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
  [        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
  [        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
  [   +3 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
  [        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
  [        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
  [        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
  [        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
  [        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
  [        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
  [  +44 ms] executing: /Users/andrey/Library/Android/sdk/platform-tools/adb devices -l
  [   +8 ms] Exit code 0 from: /Users/andrey/Library/Android/sdk/platform-tools/adb devices -l
  [        ] List of devices attached
  [   +7 ms] executing: /usr/bin/xcode-select --print-path
  [   +6 ms] Exit code 0 from: /usr/bin/xcode-select --print-path
  [        ] /Applications/Xcode.app/Contents/Developer
  [        ] executing: /usr/bin/xcodebuild -version
  [ +114 ms] Exit code 0 from: /usr/bin/xcodebuild -version
  [   +2 ms] Xcode 11.3.1
            Build version 11C504
  [   +2 ms] executing: xcrun --find xcdevice
  [   +7 ms] Exit code 0 from: xcrun --find xcdevice
  [        ] /Applications/Xcode.app/Contents/Developer/usr/bin/xcdevice
  [   +1 ms] executing: xcrun xcdevice list --timeout 1
  [+1586 ms] [
                        {
                          "simulator" : true,
                          "operatingSystemVersion" : "12.4 (16G73)",
                          "available" : true,
                          "platform" : "com.apple.platform.iphonesimulator",
                          "modelCode" : "iPhone10,4",
                          "identifier" : "E8EC639C-21C2-4E48-878F-ED25F06D25AA",
                          "architecture" : "x86_64",
                          "modelName" : "iPhone 8",
                          "name" : "iPhone 8"
                        },
                        {
                          "simulator" : true,
                          "operatingSystemVersion" : "6.1.1 (17S445)",
                          "available" : true,
                          "platform" : "com.apple.platform.watchsimulator",
                          "modelCode" : "Watch5,3",
                          "identifier" : "EC927EEC-F2C6-4563-AA47-EBC4DDD36040",
                          "architecture" : "i386",
                          "modelName" : "Apple Watch Series 5 - 40mm",
                          "name" : "Apple Watch Series 5 - 40mm"
                        },
                        {
                          "simulator" : true,
                          "operatingSystemVersion" : "13.3 (17C45)",
                          "available" : true,
                          "platform" : "com.apple.platform.iphonesimulator",
                          "modelCode" : "iPad7,12",
                          "identifier" : "1CA482F7-BCDC-49B9-886A-A5F034A7DD0F",
                          "architecture" : "x86_64",
                          "modelName" : "iPad (7th generation)",
                          "name" : "iPad (7th generation)"
                        },
                        {
                          "simulator" : false,
                          "operatingSystemVersion" : "13.3.1 (17D50)",
                          "interface" : "usb",
                          "available" : false,
                          "platform" : "com.apple.platform.iphoneos",
                          "modelCode" : "iPhone12,3",
                          "identifier" : "00008030-001651000150802E",
                          "architecture" : "arm64e",
                          "modelName" : "iPhone 11 Pro",
                          "name" : "Andrey’s iPhone",
                          "error" : {
                            "code" : -13,
                            "failureReason" : "",
                            "underlyingErrors" : [
                              {
                                "code" : 5,
                                "failureReason" : "allowsSecureServices: 1. isConnected: 0. Platform:
                                <DVTPlatform:0x7fcc7f81a2c0:'com.apple.platform.iphoneos':<DVTFilePath:0x7fcc7f81a240:'\/Applications\/Xcode.app\/Contents\/Developer\/Platforms\/iPhoneOS.platform'>>.
                                DTDKDeviceIdentifierIsIDID: 0",
                                "description" : "📱<DVTiOSDevice (0x7fcc823416f0), Andrey’s iPhone, iPhone, 13.3.1 (17D50), 00008030-001651000150802E> -- Failed _shouldMakeReadyForDevelopment check even though
                                device is not locked by passcode.",
                                "recoverySuggestion" : "",
                                "domain" : "com.apple.platform.iphoneos"
                              }
                            ],
                            "description" : "Andrey’s iPhone is not connected",
                            "recoverySuggestion" : "Xcode will continue when Andrey’s iPhone is connected.",
                            "domain" : "com.apple.platform.iphoneos"
                          }
                        },
                        {
                          "simulator" : true,
                          "operatingSystemVersion" : "6.1.1 (17S445)",
                          "available" : true,
                          "platform" : "com.apple.platform.watchsimulator",
                          "modelCode" : "Watch5,4",
                          "identifier" : "58A1EF70-F297-4F6D-8439-DE1AC38C2C42",
                          "architecture" : "i386",
                          "modelName" : "Apple Watch Series 5 - 44mm",
                          "name" : "Apple Watch Series 5 - 44mm"
                        },
                        {
                          "simulator" : true,
                          "operatingSystemVersion" : "13.3 (17C45)",
                          "available" : true,
                          "platform" : "com.apple.platform.iphonesimulator",
                          "modelCode" : "iPhone10,4",
                          "identifier" : "BAD8210C-917F-43D2-A594-883C1880AB1F",
                          "architecture" : "x86_64",
                          "modelName" : "iPhone 8",
                          "name" : "iPhone 8"
                        },
                        {
                          "simulator" : false,
                          "operatingSystemVersion" : "12.3 (16M153)",
                          "interface" : "usb",
                          "available" : false,
                          "platform" : "com.apple.platform.appletvos",
                          "modelCode" : "AppleTV5,3",
                          "identifier" : "c2089fc00183beb4963365f77757b993ccc4d3bf",
                          "architecture" : "arm64",
                          "modelName" : "Apple TV (4th generation)",
                          "name" : "Apple TV (3139)",
                          "error" : {
                            "code" : -13,
                            "failureReason" : "",
                            "underlyingErrors" : [
                              {
                                "code" : 5,
                                "failureReason" : "allowsSecureServices: 1. isConnected: 0. Platform:
                                <DVTPlatform:0x7fcc7f815840:'com.apple.platform.appletvos':<DVTFilePath:0x7fcc7f816640:'\/Applications\/Xcode.app\/Contents\/Developer\/Platforms\/AppleTVOS.platform'>>.
                                DTDKDeviceIdentifierIsIDID: 0",
                                "description" : "📱<DVTiOSDevice (0x7fcc7ffb6ce0), Apple TV (3139), AppleTV, 12.3 (16M153), c2089fc00183beb4963365f77757b993ccc4d3bf> -- Failed _shouldMakeReadyForDevelopment
                                check even though device is not locked by passcode.",
                                "recoverySuggestion" : "",
                                "domain" : "com.apple.platform.iphoneos"
                              }
                            ],
                            "description" : "Apple TV (3139) is not connected",
                            "recoverySuggestion" : "Xcode will continue when Apple TV (3139) is connected.",
                            "domain" : "com.apple.platform.iphoneos"
                          }
                        },
                        {
                          "simulator" : true,
                          "operatingSystemVersion" : "13.3 (17C45)",
                          "available" : true,
                          "platform" : "com.apple.platform.iphonesimulator",
                          "modelCode" : "iPhone10,5",
                          "identifier" : "ADBBE746-8D3F-42AB-AFAF-B1BA08DDE770",
                          "architecture" : "x86_64",
                          "modelName" : "iPhone 8 Plus",
                          "name" : "iPhone 8 Plus"
                        },
                        {
                          "simulator" : true,
                          "operatingSystemVersion" : "13.3 (17K446)",
                          "available" : true,
                          "platform" : "com.apple.platform.appletvsimulator",
                          "modelCode" : "AppleTV6,2",
                          "identifier" : "DBC8C3BD-0919-442D-80B6-778A8A8387FF",
                          "architecture" : "x86_64",
                          "modelName" : "Apple TV 4K",
                          "name" : "Apple TV 4K"
                        },
                        {
                          "simulator" : true,
                          "operatingSystemVersion" : "13.3 (17K446)",
                          "available" : true,
                          "platform" : "com.apple.platform.appletvsimulator",
                          "modelCode" : "AppleTV5,3",
                          "identifier" : "1C70D6CC-4C3F-41AF-A11F-2FA3369DD897",
                          "architecture" : "x86_64",
                          "modelName" : "Apple TV",
                          "name" : "Apple TV"
                        },
                        {
                          "simulator" : true,
                          "operatingSystemVersion" : "13.3 (17C45)",
                          "available" : true,
                          "platform" : "com.apple.platform.iphonesimulator",
                          "modelCode" : "iPhone12,3",
                          "identifier" : "E5040D43-B64A-41FD-B102-32C9A6EF43A8",
                          "architecture" : "x86_64",
                          "modelName" : "iPhone 11 Pro",
                          "name" : "iPhone 11 Pro"
                        },
                        {
                          "simulator" : true,
                          "operatingSystemVersion" : "13.3 (17C45)",
                          "available" : true,
                          "platform" : "com.apple.platform.iphonesimulator",
                          "modelCode" : "iPad8,5",
                          "identifier" : "798E1B10-95B3-4BEF-8E09-D6DE289924EB",
                          "architecture" : "x86_64",
                          "modelName" : "iPad Pro (12.9-inch) (3rd generation)",
                          "name" : "iPad Pro (12.9-inch) (3rd generation)"
                        },
                        {
                          "simulator" : true,
                          "operatingSystemVersion" : "13.3 (17C45)",
                          "available" : true,
                          "platform" : "com.apple.platform.iphonesimulator",
                          "modelCode" : "iPhone12,1",
                          "identifier" : "3355075F-790F-4637-85B0-7DAD1F822BBF",
                          "architecture" : "x86_64",
                          "modelName" : "iPhone 11",
                          "name" : "iPhone 11"
                        },
                        {
                          "simulator" : true,
                          "operatingSystemVersion" : "6.1.1 (17S445)",
                          "available" : true,
                          "platform" : "com.apple.platform.watchsimulator",
                          "modelCode" : "Watch4,3",
                          "identifier" : "D79EA95E-EB4E-4679-B9BF-B96A46E66ADA",
                          "architecture" : "i386",
                          "modelName" : "Apple Watch Series 4 - 40mm",
                          "name" : "Apple Watch Series 4 - 40mm"
                        },
                        {
                          "simulator" : true,
                          "operatingSystemVersion" : "12.4 (16G73)",
                          "available" : true,
                          "platform" : "com.apple.platform.iphonesimulator",
                          "modelCode" : "iPhone6,1",
                          "identifier" : "164EB119-45C7-43B0-9221-3DA806406A3C",
                          "architecture" : "x86_64",
                          "modelName" : "iPhone 5s",
                          "name" : "iPhone 5s"
                        },
                        {
                          "simulator" : true,
                          "operatingSystemVersion" : "6.1.1 (17S445)",
                          "available" : true,
                          "platform" : "com.apple.platform.watchsimulator",
                          "modelCode" : "Watch4,4",
                          "identifier" : "D48A27CE-4AB1-4445-92A0-CEB8CE1951CC",
                          "architecture" : "i386",
                          "modelName" : "Apple Watch Series 4 - 44mm",
                          "name" : "Apple Watch Series 4 - 44mm"
                        },
                        {
                          "simulator" : true,
                          "operatingSystemVersion" : "13.3 (17K446)",
                          "available" : true,
                          "platform" : "com.apple.platform.appletvsimulator",
                          "modelCode" : "AppleTV6,2",
                          "identifier" : "3CA79A49-AB9A-4873-97B8-D650BAB4C134",
                          "architecture" : "x86_64",
                          "modelName" : "Apple TV 4K (at 1080p)",
                          "name" : "Apple TV 4K (at 1080p)"
                        },
                        {
                          "simulator" : true,
                          "operatingSystemVersion" : "13.3 (17C45)",
                          "available" : true,
                          "platform" : "com.apple.platform.iphonesimulator",
                          "modelCode" : "iPhone12,5",
                          "identifier" : "49E8A85F-CDFA-4DDD-BD94-BCE8F27669D1",
                          "architecture" : "x86_64",
                          "modelName" : "iPhone 11 Pro Max",
                          "name" : "iPhone 11 Pro Max"
                        }
                      ]
  [  +49 ms] Error: Andrey’s iPhone is not connected. Xcode will continue when Andrey’s iPhone is connected. (code -13)
  [   +3 ms] /usr/bin/xcrun simctl list --json devices
  [ +107 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
  [        ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
  [        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
  [        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
  [   +2 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
  [        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
  [        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
  [        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
  [        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
  [        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
  [        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
  [  +79 ms] Found plugin cloud_firestore at /Users/andrey/.pub-cache/hosted/pub.dartlang.org/cloud_firestore-0.13.0+1/
  [  +19 ms] Found plugin firebase_core at /Users/andrey/.pub-cache/hosted/pub.dartlang.org/firebase_core-0.4.3+3/
  [   +3 ms] Found plugin firebase_core_web at /Users/andrey/.pub-cache/hosted/pub.dartlang.org/firebase_core_web-0.1.1+2/
  [   +6 ms] Found plugin flutter_plugin_android_lifecycle at /Users/andrey/.pub-cache/hosted/pub.dartlang.org/flutter_plugin_android_lifecycle-1.0.5/
  [   +6 ms] Found plugin google_maps_flutter at /Users/andrey/.pub-cache/hosted/pub.dartlang.org/google_maps_flutter-0.5.22/
  [  +42 ms] Found plugin url_launcher at /Users/andrey/.pub-cache/hosted/pub.dartlang.org/url_launcher-5.4.1/
  [   +1 ms] Found plugin url_launcher_macos at /Users/andrey/.pub-cache/hosted/pub.dartlang.org/url_launcher_macos-0.0.1+2/
  [   +3 ms] Found plugin url_launcher_web at /Users/andrey/.pub-cache/hosted/pub.dartlang.org/url_launcher_web-0.1.1/
  [  +36 ms] Found plugin cloud_firestore at /Users/andrey/.pub-cache/hosted/pub.dartlang.org/cloud_firestore-0.13.0+1/
  [   +8 ms] Found plugin firebase_core at /Users/andrey/.pub-cache/hosted/pub.dartlang.org/firebase_core-0.4.3+3/
  [   +2 ms] Found plugin firebase_core_web at /Users/andrey/.pub-cache/hosted/pub.dartlang.org/firebase_core_web-0.1.1+2/
  [   +4 ms] Found plugin flutter_plugin_android_lifecycle at /Users/andrey/.pub-cache/hosted/pub.dartlang.org/flutter_plugin_android_lifecycle-1.0.5/
  [   +4 ms] Found plugin google_maps_flutter at /Users/andrey/.pub-cache/hosted/pub.dartlang.org/google_maps_flutter-0.5.22/
  [  +22 ms] Found plugin url_launcher at /Users/andrey/.pub-cache/hosted/pub.dartlang.org/url_launcher-5.4.1/
  [        ] Found plugin url_launcher_macos at /Users/andrey/.pub-cache/hosted/pub.dartlang.org/url_launcher_macos-0.0.1+2/
  [   +1 ms] Found plugin url_launcher_web at /Users/andrey/.pub-cache/hosted/pub.dartlang.org/url_launcher_web-0.1.1/
  [  +55 ms] Generating /Users/andrey/Documents/MyProjects/RestaurantApp/src/admin/android/app/src/main/java/io/flutter/plugins/GeneratedPluginRegistrant.java
  [ +196 ms] Launching lib/main.dart on Chrome in debug mode...
  [        ] Building application for the web...
  [ +136 ms] Found plugin cloud_firestore at /Users/andrey/.pub-cache/hosted/pub.dartlang.org/cloud_firestore-0.13.0+1/
  [   +4 ms] Found plugin firebase_core at /Users/andrey/.pub-cache/hosted/pub.dartlang.org/firebase_core-0.4.3+3/
  [   +1 ms] Found plugin firebase_core_web at /Users/andrey/.pub-cache/hosted/pub.dartlang.org/firebase_core_web-0.1.1+2/
  [   +2 ms] Found plugin flutter_plugin_android_lifecycle at /Users/andrey/.pub-cache/hosted/pub.dartlang.org/flutter_plugin_android_lifecycle-1.0.5/
  [   +3 ms] Found plugin google_maps_flutter at /Users/andrey/.pub-cache/hosted/pub.dartlang.org/google_maps_flutter-0.5.22/
  [  +10 ms] Found plugin url_launcher at /Users/andrey/.pub-cache/hosted/pub.dartlang.org/url_launcher-5.4.1/
  [        ] Found plugin url_launcher_macos at /Users/andrey/.pub-cache/hosted/pub.dartlang.org/url_launcher_macos-0.0.1+2/
  [   +1 ms] Found plugin url_launcher_web at /Users/andrey/.pub-cache/hosted/pub.dartlang.org/url_launcher_web-0.1.1/
  [+7397 ms] Daemon is already running.
  [+1033 ms] About to build [web]...
  [   +5 ms] Updating asset graph...
  [        ] Updating asset graph completed, took 5ms

  [        ] Running build...
  [ +172 ms] Running build completed, took 80ms

  [        ] Caching finalized dependency graph...
  [   +4 ms] Caching finalized dependency graph completed, took 107ms

  [   +3 ms] Failed after 195ms
  [  +15 ms] Building application for the web... (completed in 8.8s)
  [   +1 ms] "flutter run" took 11,340ms.
  Failed to build application for the Web.

  #0      throwToolExit (package:flutter_tools/src/base/common.dart:14:3)
  #1      _DwdsResidentWebRunner.run (package:flutter_tools/src/build_runner/resident_web_runner.dart:719:7)
  <asynchronous suspension>
  #2      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:556:37)
  <asynchronous suspension>
  #3      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:668:18)
  #4      _rootRunUnary (dart:async/zone.dart:1134:38)
  #5      _CustomZone.runUnary (dart:async/zone.dart:1031:19)
  #6      _FutureListener.handleValue (dart:async/future_impl.dart:140:18)
  #7      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:682:45)
  #8      Future._propagateToListeners (dart:async/future_impl.dart:711:32)
  #9      Future._completeWithValue (dart:async/future_impl.dart:526:5)
  #10     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:34:15)
  #11     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:293:13)
  #12     RunCommand.usageValues (package:flutter_tools/src/commands/run.dart)
  #13     _rootRunUnary (dart:async/zone.dart:1134:38)
  #14     _CustomZone.runUnary (dart:async/zone.dart:1031:19)
  #15     _FutureListener.handleValue (dart:async/future_impl.dart:140:18)
  #16     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:682:45)
  #17     Future._propagateToListeners (dart:async/future_impl.dart:711:32)
  #18     Future._completeWithValue (dart:async/future_impl.dart:526:5)
  #19     Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:556:7)
  #20     _rootRun (dart:async/zone.dart:1126:13)
  #21     _CustomZone.run (dart:async/zone.dart:1023:19)
  #22     _CustomZone.runGuarded (dart:async/zone.dart:925:7)
  #23     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:965:23)
  #24     _microtaskLoop (dart:async/schedule_microtask.dart:43:21)
  #25     _startMicrotaskLoop (dart:async/schedule_microtask.dart:52:5)
  #26     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
  #27     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:169:5)
  ```

</details>

<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel dev, v1.15.3, on Mac OS X 10.15.3 19D76, locale en-RU)
    • Flutter version 1.15.3 at /Users/andrey/flutter_dev
    • Framework revision 67826bdce5 (8 days ago), 2020-02-10 14:59:32 -0800
    • Engine revision 6158f03ef5
    • Dart version 2.8.0 (build 2.8.0-dev.8.0 514a8d4c84)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/andrey/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = /Users/andrey/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.3.1, Build version 11C504
    • CocoaPods version 1.8.4

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[!] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] VS Code (version 1.42.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.8.1

[✓] Connected device (3 available)
    • iPad       • 8807f3e1632ff643cc3f92f0f207ae5a7d831121 • ios            • iOS 13.3.1
    • Chrome     • chrome                                   • web-javascript • Google Chrome 80.0.3987.106
    • Web Server • web-server                               • web-javascript • Flutter Tools
```
</details>

**Comment by jonahwilliams** [comment]
This is fixed by https://github.com/flutter/flutter/pull/50365 . This change is still in the master channel, but will be available in dev sometime in the next few days
