### ISSUE TITLE
com.google.firebase.provider.FirebaseInitProvider: java.lang.ClassNotFoundException: com.google.firebase.provider.FirebaseInitProvider on android v4.0 api 16

### ISSUE THREAD

**Issue by jpainam** [flutter/flutter#51025]
## Steps to Reproduce
Simple Application to be executed on an Emulator Android v4.0 API Level 16

```dart
02-19 16:35:48.634 3171-3171/com.android.launcher D/EGL_emulation: eglMakeCurrent: 0xb9702410: ver 2 0
02-19 16:35:48.634 3616-3616/? E/AndroidRuntime: FATAL EXCEPTION: main
    java.lang.RuntimeException: Unable to get provider com.google.firebase.provider.FirebaseInitProvider: java.lang.ClassNotFoundException: com.google.firebase.provider.FirebaseInitProvider
        at android.app.ActivityThread.installProvider(ActivityThread.java:4563)
        at android.app.ActivityThread.installContentProviders(ActivityThread.java:4190)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4132)
        at android.app.ActivityThread.access$1300(ActivityThread.java:130)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1255)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:137)
        at android.app.ActivityThread.main(ActivityThread.java:4745)
        at java.lang.reflect.Method.invokeNative(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:511)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:786)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553)
        at dalvik.system.NativeStart.main(Native Method)
     Caused by: java.lang.ClassNotFoundException: com.google.firebase.provider.FirebaseInitProvider
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:61)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:501)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:461)
        at android.app.ActivityThread.installProvider(ActivityThread.java:4548)
        at android.app.ActivityThread.installContentProviders(ActivityThread.java:4190) 
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4132) 
        at android.app.ActivityThread.access$1300(ActivityThread.java:130) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1255) 
        at android.os.Handler.dispatchMessage(Handler.java:99) 
        at android.os.Looper.loop(Looper.java:137) 
        at android.app.ActivityThread.main(ActivityThread.java:4745) 
        at java.lang.reflect.Method.invokeNative(Native Method) 
        at java.lang.reflect.Method.invoke(Method.java:511) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:786) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553) 
        at dalvik.system.NativeStart.main(Native Method) 
02-19 16:35:48.634 1564-2534/system_process W/ActivityManager:   Force finishing activity com.moyer.maraka/.MainActivity
```
```[√] Flutter (Channel stable, v1.12.13+hotfix.5, on Microsoft Windows [Version 10.0.18362.592], locale en-GB)
    • Flutter version 1.12.13+hotfix.5 at D:\flutter\flutter
    • Framework revision 27321ebbad (2 months ago), 2019-12-10 18:15:01 -0800
    • Engine revision 2994f7e1e6
    • Dart version 2.7.0

[!] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at D:\android\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 28.0.3
    • ANDROID_HOME = D:\android\Android
    • Java binary at: D:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)
    X Android license status unknown.
      Try re-installing or updating your Android SDK Manager.
      See https://developer.android.com/studio/#downloads or visit https://flutter.dev/setup/#android-setup for detailed
      instructions.

[√] Android Studio (version 3.5)
    • Android Studio at D:\Program Files\Android\Android Studio
    • Flutter plugin version 42.1.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)

[!] IntelliJ IDEA Ultimate Edition (version 14)
    • IntelliJ at C:\Program Files (x86)\JetBrains\IntelliJ IDEA 14.0
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.dev/intellij-setup/#installing-the-plugins
    X This install is older than the minimum recommended version of 2017.1.0.

[√] VS Code, 64-bit edition (version 1.41.0)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Flutter extension version 3.8.1

[√] Connected device (2 available)
    • Android SDK built for x86 • emulator-5556 • android-x86 • Android 5.0.2 (API 21) (emulator)
    • emulator-5558             • emulator-5558 • android-x86 • Android 4.1.2 (API 16) (emulator)

! Doctor found issues in 2 categories.
```

**Comment by TahaTesser** [comment]
Hi @jpainam 
Could you please try possible [solution](https://stackoverflow.com/a/41444469)
Thank you

**Comment by jpainam** [comment]
i just forgot to mentioned. but this is my app/build.gradle
```
def localProperties = new Properties()
def localPropertiesFile = rootProject.file('local.properties')
if (localPropertiesFile.exists()) {
    localPropertiesFile.withReader('UTF-8') { reader ->
        localProperties.load(reader)
    }
}

def flutterRoot = localProperties.getProperty('flutter.sdk')
if (flutterRoot == null) {
    throw new GradleException("Flutter SDK not found. Define location with flutter.sdk in the local.properties file.")
}

def flutterVersionCode = localProperties.getProperty('flutter.versionCode')
if (flutterVersionCode == null) {
    throw new GradleException("versionCode not found. Define flutter.versionCode in the local.properties file.")
    //flutterVersionCode = '1'
}

def flutterVersionName = localProperties.getProperty('flutter.versionName')
if (flutterVersionName == null) {
    throw new GradleException("versionName not found. Define flutter.versionName in the local.properties file.")
    //flutterVersionName = '1.0'
}

apply plugin: 'com.android.application'
apply from: "$flutterRoot/packages/flutter_tools/gradle/flutter.gradle"

def keystoreProperties = new Properties()
def keystorePropertiesFile = rootProject.file('key.properties')
if (keystorePropertiesFile.exists()) {
    keystoreProperties.load(new FileInputStream(keystorePropertiesFile))
}

android {
    useLibrary 'org.apache.http.legacy'
    compileSdkVersion 29

    lintOptions {
        disable 'InvalidPackage'
    }

    defaultConfig {
        // TODO: Specify your own unique Application ID (https://developer.android.com/studio/build/application-id.html).
        applicationId "com.moyer.maraka"
        minSdkVersion 16
        targetSdkVersion 29
        multiDexEnabled true
        versionCode flutterVersionCode.toInteger()
        versionName flutterVersionName
        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

    dexOptions {
        javaMaxHeapSize "4g"
    }

    signingConfigs {
        release {
            keyAlias keystoreProperties['keyAlias']
            keyPassword keystoreProperties['keyPassword']
            storeFile keystoreProperties['storeFile'] ? file(keystoreProperties['storeFile']) : null
            storePassword keystoreProperties['storePassword']
        }
    }
    buildTypes {
        release {
            signingConfig signingConfigs.release
        }
    }
}

flutter {
    source '../..'
}

dependencies {
    testImplementation 'junit:junit:4.12'
    androidTestImplementation 'androidx.test:runner:1.1.1'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.1.1'
	implementation 'androidx.multidex:multidex:2.0.0'
    implementation "com.google.firebase:firebase-messaging:20.1.0"
}

apply plugin: 'com.google.gms.google-services'
apply plugin: 'io.fabric'
```
not working with or without
```  dexOptions {
        javaMaxHeapSize "4g"
 }
```

**Comment by jpainam** [comment]
I think, may be, because the  `Google Play` app is missing in the emulator. But I can confirm that `Google Play Services v.9.2.56`

**Comment by TahaTesser** [comment]
Hi @jpainam 
Is this issue only happening API 16?
i noticed you have `implementation "com.google.firebase:firebase-messaging:20.1.0"` in your `app/build.gradle`
Does your app depends on native Android Firebase messing code? 
Thank you

**Comment by jpainam** [comment]
it's only happening on API Level 16
`implementation "com.google.firebase:firebase-messaging:20.1.0` was added following 
`class file for com.google.firebase.messaging.FirebaseMessagingService not found` in `flutter firebase_messaging` which was solved by [https://github.com/FirebaseExtended/flutterfire/issues/1651#issuecomment-567359620](issue)

**Comment by TahaTesser** [comment]
Hi @jpainam 
Looks like a standard setup. Thanks for all the info

**Comment by jpainam** [comment]
@TahaTesser. I don't think it's the `firebase_messaging` plugin. I started a new project with `flutter create testapp` .
```
firebase_core: ^0.4.4` (only)
--- 
multiDexEnabled true
implementation 'androidx.multidex:multidex:2.0.0'
apply plugin: 'com.google.gms.google-services'
---
classpath 'com.google.gms:google-services:4.3.0'
```
And I have the same issue.

**Comment by jpainam** [comment]
[#1340](https://github.com/FirebaseExtended/flutterfire/issues/1340) solved the issue. thanks
