### ISSUE TITLE
[google_maps_flutter] NullPointerException: Attempt to read from null array

### ISSUE THREAD

**Issue by medyas** [flutter/flutter#51064]
Getting `NullPointerException` when doing an interaction with the map widget in Android.
Am using 
  `google_maps_flutter: ^0.5.23+1`
Flutter Doctor:
```
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, v1.12.13+hotfix.8, on Microsoft Windows [Version 10.0.17763.1039], locale en-US)

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[√] Android Studio (version 3.5)
[√] IntelliJ IDEA Ultimate Edition (version 2019.3)
```

This is the system log error:

> 02-19 19:49:05.759 14945-21107/de.nbsev.darassalam E/AndroidRuntime: FATAL EXCEPTION: androidmapsapi-vts_de.nbsev.darassalam_default
    Process: de.nbsev.darassalam, PID: 14945
    java.lang.NullPointerException: Attempt to read from null array
        at java.util.ArrayList.get(ArrayList.java:310)
        at com.google.maps.api.android.lib6.gmm6.vector.gl.drawable.g.a(:com.google.android.gms.dynamite_mapsdynamite@20104027@20.1.04 (020300-0):52)
        at com.google.maps.api.android.lib6.gmm6.vector.gl.drawable.ao.a(:com.google.android.gms.dynamite_mapsdynamite@20104027@20.1.04 (020300-0):80)
        at com.google.maps.api.android.lib6.gmm6.store.fetch.i.a(:com.google.android.gms.dynamite_mapsdynamite@20104027@20.1.04 (020300-0):89)
        at com.google.maps.api.android.lib6.gmm6.store.fetch.f.a(:com.google.android.gms.dynamite_mapsdynamite@20104027@20.1.04 (020300-0):3)
        at com.google.maps.api.android.lib6.gmm6.store.j.a(:com.google.android.gms.dynamite_mapsdynamite@20104027@20.1.04 (020300-0):7)
        at com.google.maps.api.android.lib6.gmm6.store.k.a(:com.google.android.gms.dynamite_mapsdynamite@20104027@20.1.04 (020300-0):87)
        at com.google.maps.api.android.lib6.gmm6.store.f.handleMessage(:com.google.android.gms.dynamite_mapsdynamite@20104027@20.1.04 (020300-0):63)
        at android.os.Handler.dispatchMessage(Handler.java:111)
        at android.os.Looper.loop(Looper.java:194)
        at com.google.maps.api.android.lib6.gmm6.store.k.run(:com.google.android.gms.dynamite_mapsdynamite@20104027@20.1.04 (020300-0):116)
        at com.google.maps.api.android.lib6.gmm6.store.ab.run(:com.google.android.gms.dynamite_mapsdynamite@20104027@20.1.04 (020300-0):11)

and this is the Crashlytics:

> Fatal Exception: java.lang.NullPointerException
Attempt to read from null array
java.util.ArrayList.get (ArrayList.java:310)
com.google.maps.api.android.lib6.gmm6.vector.gl.drawable.g.a (:com.google.android.gms.dynamite_mapsdynamite@20104027@20.1.04 (020300-0):52)
com.google.maps.api.android.lib6.gmm6.vector.gl.drawable.ao.a (:com.google.android.gms.dynamite_mapsdynamite@20104027@20.1.04 (020300-0):80)
com.google.maps.api.android.lib6.gmm6.store.fetch.i.a (:com.google.android.gms.dynamite_mapsdynamite@20104027@20.1.04 (020300-0):89)
com.google.maps.api.android.lib6.gmm6.store.fetch.f.a (:com.google.android.gms.dynamite_mapsdynamite@20104027@20.1.04 (020300-0):3)
com.google.maps.api.android.lib6.gmm6.store.j.a (:com.google.android.gms.dynamite_mapsdynamite@20104027@20.1.04 (020300-0):7)
com.google.maps.api.android.lib6.gmm6.store.k.a (:com.google.android.gms.dynamite_mapsdynamite@20104027@20.1.04 (020300-0):87)
com.google.maps.api.android.lib6.gmm6.store.f.handleMessage (:com.google.android.gms.dynamite_mapsdynamite@20104027@20.1.04 (020300-0):63)
android.os.Handler.dispatchMessage (Handler.java:111)
android.os.Looper.loop (Looper.java:194)
com.google.maps.api.android.lib6.gmm6.store.k.run (:com.google.android.gms.dynamite_mapsdynamite@20104027@20.1.04 (020300-0):116)
com.google.maps.api.android.lib6.gmm6.store.ab.run (:com.google.android.gms.dynamite_mapsdynamite@20104027@20.1.04 (020300-0):11)

The device am testing the app on is:
![Screenshot_2020-02-19 Dar Assalam – Crashlytics – Firebase console](https://user-images.githubusercontent.com/13151636/74865815-07b5cc80-5352-11ea-910b-19b0697c9a3a.png)

**Comment by VladyslavBondarenko** [comment]
Hi @medyas 
https://stackoverflow.com/questions/59209714/google-maps-crash-java-lang-nullpointerexception-attempt-to-read-from-null-arr
describes exactly your case. 

A workaround is mentioned there.
If you are going to check whether it helps, you can specify maxZoomPreference for your map with:

```
const GoogleMap({
    ...
    minMaxZoomPreference: MinMaxZoomPreference(0, 16),
    ...
}) 
```

(doc. http://flutterdevs.com/blog/google-maps-in-flutter/)

Closing, because it seems to be not an issue with Flutter
If you disagree or you can provide more info about cause of the error please write in the comments and I will reopen it.
Thank you
