### ISSUE TITLE
[url_launcher] - PlatformException when launching URLs from a Flutter AAR module added to an Android app

### ISSUE THREAD

**Issue by gaucidaniel** [flutter/flutter#51086]
I am currently working on a project in which a Flutter module is packaged into an AAR and imported into an Android project, which in turn will then be shipped as an Android library, abstracting Flutter to the end user. In order to achieve this, a FlutterActivity or FlutterFragment was not used and instead a custom view was created which wraps a FlutterView backed by a FlutterEngine. This allows complete flexibility to the consumers of the library without even having to know that Flutter is a dependency.

While this setup works perfectly, I am having some issues with the url_launcher library. The Flutter module makes use of this library to open URL's on Android, and while this works well within the Flutter module, once embedded into an Android app in the method described above, the following error is thrown whenever a URL is opened:

```
E/flutter: [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: PlatformException(NO_ACTIVITY, Launching a URL requires a foreground activity., null)
    #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:569:7)
    #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:156:18)
    <asynchronous suspension>
    #2      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:329:12)
    #3      MethodChannelUrlLauncher.launch (package:url_launcher_platform_interface/method_channel_url_launcher.dart:39:21)
    #4      launch (package:url_launcher/url_launcher.dart:86:58)
    #5      RouteManager.start.<anonymous closure> (package:engine_native/managers/route_manager.dart:23:19)
    <asynchronous suspension>
    #6      _rootRunUnary (dart:async/zone.dart:1134:38)
    #7      _CustomZone.runUnary (dart:async/zone.dart:1031:19)
    #8      _CustomZone.runUnaryGuarded (dart:async/zone.dart:933:7)
    #9      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11)
    #10     _DelayedData.perform (dart:async/stream_impl.dart:594:14)
    #11     _StreamImplEvents.handleNext (dart:async/stream_impl.dart:710:11)
    #12     _PendingEvents.schedule.<anonymous closure> (dart:async/stream_impl.dart:670:7)
    #13     _rootRun (dart:async/zone.dart:1122:38)
    #14     _CustomZone.run (dart:async/zone.dart:1023:19)
    #15     _CustomZone.runGuarded (dart:async/zone.dart:925:7)
    #16     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:965:23)
    #17     _rootRun (dart:async/zone.dart:1126:13)
    #18     _CustomZone.run (dart:async/zone.dart:1023:19)
    #19     _CustomZone.runGuarded (dart:async/zone.dart:925:7)
    #20     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:965:23)
    #21     _microtaskLoop (dart:async/schedule_microtask.dart:43:21)
    #22     _startMicrotaskLoop (dart:async/schedule_microtask.dart:52:5)
```

Upon further investigation, the issue seems to be that the `UrlLauncherPlugin` relies on the `ActivityAware` class to retrieve the Activity, however for me `onAttachedToActivity` is never called. According to the documentation, the `onAttachedToActivity` in the `ActivityAware` class retrieves the activity in the following two scenarios:

> - This ActivityAware FlutterPlugin was just added to a FlutterEngine that was already connected to a running Activity.
> - This ActivityAware FlutterPlugin was already added to a FlutterEngine and that FlutterEngine was just connected to an Activity.

Given that FlutterEngine lives in a custom view that is created within an Activity, shouldn't `onAttachedToActivity` be called automatically?

Any help with this issue would be appreciated. Thanks in advance.

**Comment by iapicca** [comment]
Hi @gaucidaniel 
what flutter version did you use in you flutter module?
Thank you

**Comment by gaucidaniel** [comment]
Hi @iapicca, the Flutter module uses Flutter beta:

```
Flutter 1.14.6 • channel beta • https://github.com/flutter/flutter.git
Framework • revision fabeb2a16f (3 weeks ago) • 2020-01-28 07:56:51 -0800
Engine • revision c4229bfbba
Tools • Dart 2.8.0 (build 2.8.0-dev.5.0 fc3af737c7)
```

**Comment by xster** [comment]
Can you let us know the version of the url_launcher used and/or copy paste your pubspec here?

**Comment by VladyslavBondarenko** [comment]
Hi @gaucidaniel 
Is it still an issue?
Can you let us know the version of the url_launcher used and/or copy paste your pubspec here?

**Comment by TahaTesser** [comment]
Hi @gaucidaniel 
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore
reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any
more information for us; we will reopen it right away!
Thanks for your contribution.

**Comment by TahaTesser** [comment]
Closed by accident, ,my bad

**Comment by gaucidaniel** [comment]
This was still an issue when using a FlutterView backed by a FlutterEngine, however as a workaround I replaced the FlutterView usage with a FlutterFragment.

**Comment by linhttbk** [comment]
same here 
I got an exception : 
`2021-06-10 11:28:12.988 8108-8415/? E/flutter: [ERROR:flutter/lib/ui/ui_dart_state.cc(199)] Unhandled Exception: PlatformException(NO_ACTIVITY, Launching a URL requires a foreground activity., null, null)
    #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:597)
    #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:158)
    <asynchronous suspension>
    #2      launch (package:url_launcher/url_launcher.dart:96)
    <asynchronous suspension>
    #3      ProgressRangeViewmodel.launchURL (package:flutter_module/presentation/pages/progress/progress_range_viewmodel.dart:80)
    <asynchronous suspension>
2021-06-10 11:28:15.213 8108-8415/? E/flutter: [ERROR:flutter/lib/ui/ui_dart_state.cc(199)] Unhandled Exception: PlatformException(NO_ACTIVITY, Launching a URL requires a foreground activity., null, null)
    #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:597)
    #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:158)
    <asynchronous suspension>
    #2      launch (package:url_launcher/url_launcher.dart:96)
    <asynchronous suspension>
    #3      ProgressRangeViewmodel.launchURL (package:flutter_module/presentation/pages/progress/progress_range_viewmodel.dart:80)
    <asynchronous suspension>
2021-06-10 11:28:17.854 8108-8415/? E/flutter: [ERROR:flutter/lib/ui/ui_dart_state.cc(199)] Unhandled Exception: PlatformException(NO_ACTIVITY, Launching a URL requires a foreground activity., null, null)
    #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:597)
    #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:158)
    <asynchronous suspension>
    #2      launch (package:url_launcher/url_launcher.dart:96)
    <asynchronous suspension>
    #3      ProgressRangeViewmodel.launchURL (package:flutter_module/presentation/pages/progress/progress_range_viewmodel.dart:80)
    <asynchronous suspension>
2021-06-10 11:28:21.144 8108-8415/? E/flutter: [ERROR:flutter/lib/ui/ui_dart_state.cc(199)] Unhandled Exception: PlatformException(NO_ACTIVITY, Launching a URL requires a foreground activity., null, null)
    #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:597)
    #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:158)
    <asynchronous suspension>
    #2      launch (package:url_launcher/url_launcher.dart:96)
    <asynchronous suspension>
    #3      launchUrlMood (package:flutter_module/presentation/pages/progress/moodWidgets/header_mood_chart_widget.dart:129)
    <asynchronous suspension>`

url launcher version: 6.0.6
Flutter 2.2.1 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 02c026b03c (13 days ago) • 2021-05-27 12:24:44 -0700
Engine • revision 0fdb562ac8
Tools • Dart 2.13.1

**Comment by Xiaoqi-01** [comment]
I have seem error！

E/flutter: [ERROR:flutter/lib/ui/ui_dart_state.cc(186)] Unhandled Exception: PlatformException(NO_ACTIVITY, Launching a URL requires a foreground activity., null, null)
    #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:581:7)
    #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:158:18)
    <asynchronous suspension>
    #2      MethodChannelUrlLauncher.launch.<anonymous closure> (package:url_launcher_platform_interface/method_channel_url_launcher.dart)
    <asynchronous suspension>
2021-06-25 09:06:48.579 12078-12161/? E/Relinker: loadLibrary, linkError=so file not exist, path=/data/app/com.android.browser-xht0CnusLZeBgOefsOaVNw==/lib/arm/libxl_stat.so	[SourceFile:12]
2021-06-25 09:06:48.581 12078-12161/? E/Relinker: Does not exist in the APK	[SourceFile:14]
2021-06-25 09:06:48.581 12078-12161/? E/Relinker: unpackLibrary, Exception=lib/armeabi/libxl_stat.so	[SourceFile:38]
2021-06-25 09:06:48.583 12078-12161/? E/Relinker: loadLibrary exception=dlopen failed: library "/data/user/0/com.android.browser/app_lib/libxl_stat.so" not found	[SourceFile:21]

**Comment by hiasel** [comment]
I am having the same issue.
In my native android app I am using a `FlutterFragment` to launch my flutter app:
```
            flutterFragment = FlutterFragment
                .withCachedEngine(FLUTTER_CACHED_INSTANCE_ID)
                .shouldAttachEngineToActivity(attachEngineToActivity)
                .renderMode(RenderMode.texture)
                .build()
```
Trying to launch an url with `url_launcher` version `6.0.6` works fine within my standalone flutter app.
However, when trying to launch the url in the embedded native android app I am receiving the following error:
```
[ERROR:flutter/lib/ui/ui_dart_state.cc(199)] Unhandled Exception: PlatformException(NO_ACTIVITY, Launching a URL requires a foreground activity., null, null)
    #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:597:7)
    #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:158:18)
    <asynchronous suspension>
    #2      launch (package:url_launcher/url_launcher.dart:96:23)
    <asynchronous suspension>
```

**Comment by shakiz** [comment]
I encountered this issue recently. Anyone got any solution.

**Comment by taylankasap** [comment]
Using `Intent.FLAG_RECEIVER_FOREGROUND` seems to fix it but it I don't think there is a way to enable that flag via url_launcher. Maybe adding another option to launch function is the way to go?

**Comment by bhtri** [comment]
I also got the same error!!
```
E/flutter: [ERROR:flutter/lib/ui/ui_dart_state.cc(198)] Unhandled Exception: PlatformException(NO_ACTIVITY, Launching a URL requires a foreground activity., null, null)
    #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:607:7)
    #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:167:18)
    <asynchronous suspension>
    #2      launchUrlString (package:url_launcher/src/url_launcher_string.dart:39:10)
    <asynchronous suspension>
    #3      launchUrl (package:url_launcher/src/url_launcher_uri.dart:55:10)
    <asynchronous suspension>
``` 
flutter doctor || [url_launcher](https://pub.dev/packages/url_launcher): ^6.1.2 || android studio version
```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.0.1, on macOS 12.4 21F79 darwin-x64, locale ja-JP)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0-rc4)
[✓] Xcode - develop for iOS and macOS (Xcode 13.4.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.2)
[✓] VS Code (version 1.67.2)
[✓] HTTP Host Availability

Android Studio Chipmunk | 2021.2.1 Patch 1
Build #AI-212.5712.43.2112.8609683, built on May 19, 2022
Runtime version: 11.0.12+0-b1504.28-7817840 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 12.4
```

And my scenario is:
Android app keep Service running when android app is killed.
Flutter AAR module add dependency [url_launcher](https://pub.dev/packages/url_launcher) to file `pubspec.yaml`  will implement launch another app by URLs (URL Scheme etc)

```
  Uri uri = Uri(
    scheme: 'myapp',
    host: 'com.example.android_app',
    queryParameters: {
      'value1': 'a',
      'value2': 'b',
      'value3': 'c',
    },
  );
  canLaunchUrl(uri).then((isOK) {
    if (isOK) {
      launchUrl(uri);
    }
  });
```
then the above error appears.
p/s: I have also fully configured the `AndroidManifest.xml` file as according to the [usage](https://pub.dev/packages/url_launcher#android)

Any help with this issue would be appreciated. Thanks in advance.

**Comment by joshuaherr** [comment]
I ran into the same (or at least similar) issue described here. What worked for me was:

Add the Intent to the AndroidManifest file:
```
<intent>
  <action android:name="android.intent.action.VIEW" />
  <data android:scheme="https" />
</intent>
```

I still had the same NO_ACTIVITY exception above after adding the intent.

What ended up bridging the gap between url_launcher and the intent is to concisely provide the correct scheme matched in the intent when constructing the URI object:

```
Uri exampleUri= Uri(
  path: "google.com",
  scheme: "https");
launchUrl(exampleUri);
```

NOTE: I did not specify the full URL (https://google.com) in the path, when the scheme is provided it will automatically append the path to the scheme to create https://google.com.

This is specifically for https URLs, the same paradigm applies to sms, mailto, etc.

**Comment by wei-spring** [comment]
anyone fix it ?

**Comment by tinyCoder32** [comment]
Is this fixed yet?

**Comment by yixiaolunhui** [comment]
Is this fixed yet?

**Comment by tvolkert** [comment]
@wei-spring @tinyCoder32 @yixiaolunhui [please do not comment with comments such as "is there an update"](https://github.com/flutter/flutter/wiki/Issue-hygiene#do-not-add-me-too-or-same-or-is-there-an-update-comments-to-bugs).  Instead, we prioritize issues by [thumbs-up reactions](https://github.com/flutter/flutter/wiki/Issue-hygiene#thumbs-up-reactions)

**Comment by stuartmorgan** [comment]
> the UrlLauncherPlugin relies on the ActivityAware class to retrieve the Activity, however for me onAttachedToActivity is never called.

This is describing an engine issue, not a plugin-specific issue, so updating labels accordingly.
