### ISSUE TITLE
Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.

### ISSUE THREAD

**Issue by widealpha** [flutter/flutter#51204]
## Steps to Reproduce

1. Run `flutter create bug`.
2. Update the files as follows: 
```
 class DrawPathPainter extends CustomPainter{
  final int maxPath;
  final List<PathEntity> paths;
  final List<PathEntity> holdPath;
  List<Offset> points = <Offset>[];
  PictureRecorder holdPictureRecorder;
  Canvas holdCanvas;
  Picture holdPicture;//用于保存提取的图片

  DrawPathPainter(this.paths,this.holdPath,this.maxPath);

  @override
  void paint(Canvas canvas, Size size) {
    ///对溢出path进行固化
    if(paths.length > maxPath){
      PathEntity overflowPath = paths.removeAt(0);//超过max溢出的path
      holdPath.add(overflowPath);
      holdCanvas = Canvas(holdPictureRecorder);
      if(holdPicture != null){
        holdCanvas.drawPicture(holdPicture);
      }
      points = overflowPath.points;
      for(int i = 0; i < points.length - 1; i++){
        if(points[i] != null && points[i + 1] != null ){
          holdCanvas.drawLine(points[i], points[i + 1], overflowPath.paint);
        }
      }
      holdPicture = holdPictureRecorder.endRecording();
      holdPictureRecorder = PictureRecorder();
    }
    if (holdPath.length == 0){
      holdPicture = null;
    } else if(holdPicture != null){
      canvas.drawPicture(holdPicture);
    }
      //绘制可撤销屏幕画板
    paths.forEach((path){
      points = path.points;
      for(int i = 0; i < points.length - 1; i++){
        if(points[i] != null && points[i + 1] != null ){
          canvas.drawLine(points[i], points[i + 1], path.paint);
        }
      }
    });
  }

  @override
  bool shouldRepaint(DrawPathPainter oldDelegate) {
    return oldDelegate.points != points;
  }

}
3. use the class above in a custompaint widget with a gesturedetect to draw paint like 
 final List<PathEntity> _paintedPaths = <PathEntity>[];
final List<PathEntity> _holdPaths = <PathEntity>[];
.....
Stack(
      children: <Widget>[
        CustomPaint(
          painter: DrawPathPainter(_paintedPaths,_holdPaths,5),
          size: Size.infinite,
        ),
        GestureDetector(
          onPanDown: (DragDownDetails details){
            isMoved = false;
            _pathEntity = PathEntity();
            _pathEntity.paint = _clonePaint(_mPaint);
            setState(() {
              _paintedPaths.add(_pathEntity);
            });
          },
          onPanUpdate: (DragUpdateDetails details){
            RenderBox rendBox = context.findRenderObject();
            Offset localPosition = rendBox.globalToLocal(details.globalPosition);
            setState(() {
              isMoved = true;
              _pathEntity.points.add(localPosition);
            });
          },
          onPanEnd: (DragEndDetails details){
            _pathEntity.points.add(null);
            if(!isMoved){
              _paintedPaths.removeLast();
            } 
            }
          },
        ),
      ],
    )
```

when draw paths over maxpath,wrong happened

 

**Expected results:** 
I want to draw a paint.To ensure efficiency,I want to hold some path to a paicture,then draw it to the canvas

**Actual results:** 
There something wrong like the log say.But I don't know what's wrong with that.

<details>
  <summary>

```
════════ Exception caught by rendering library ═════════════════════════════════════════════════════
The following assertion was thrown during paint():
'dart:ui/painting.dart': Failed assertion: line 3288: '<optimized out>': is not true.


Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=BUG.md

The relevant error-causing widget was: 
  CustomPaint file:///D:/Project/Flutter/flutter_winter_vacation_project/lib/paint/draw_path.dart:105:9
When the exception was thrown, this was the stack: 
#2      new Canvas (dart:ui/painting.dart:3288:64)
#3      DrawPathPainter.paint (package:flutter_app/paint/draw_path.dart:37:20)
#4      RenderCustomPaint._paintWithPainter (package:flutter/src/rendering/custom_paint.dart:531:13)
#5      RenderCustomPaint.paint (package:flutter/src/rendering/custom_paint.dart:572:7)
#6      RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2219:7)
...
The following RenderObject was being processed when the exception was fired: RenderCustomPaint#3c658 relayoutBoundary=up4
...  parentData: not positioned; offset=Offset(0.0, 0.0) (can use size)
...  constraints: BoxConstraints(0.0<=w<=392.7, 0.0<=h<=613.8)
...  size: Size(392.7, 613.8)
RenderObject: RenderCustomPaint#3c658 relayoutBoundary=up4
  parentData: not positioned; offset=Offset(0.0, 0.0) (can use size)
  constraints: BoxConstraints(0.0<=w<=392.7, 0.0<=h<=613.8)
  size: Size(392.7, 613.8)
</summary>

<!--
      Run your application with `flutter run --verbose` and attach all the
      log output below between the lines with the backticks. If there is an
      exception, please see if the error message includes enough information
      to explain how to solve the issue.
-->



<!--
     Run `flutter analyze` and attach any output of that command below.
     If there are any analysis errors, try resolving them before filing this issue.
-->


<!-- Finally, paste the output of running `flutter doctor -v` here. -->

[√] Flutter (Channel stable, v1.12.13, on Microsoft Windows [Version 10.0.17763.1039], locale zh-CN)
[!] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    X Android license status unknown.
      Try re-installing or updating your Android SDK Manager.
      See https://developer.android.com/studio/#downloads or visit https://flutter.dev/setup/#android-setup for detailed
      instructions.
[√] Android Studio (version 3.5)
[!] IntelliJ IDEA Ultimate Edition (version 2019.2)
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
[!] IntelliJ IDEA Ultimate Edition (version 2019.3)
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
[√] Connected device (1 available)

```
</details>

**Comment by darshankawar** [comment]
Hi @widealpha,
Can you please confirm if you still experience this issue on latest Stable (1.20.2) version ?
Thanks.

**Comment by widealpha** [comment]
It performs well now. Thanks.
发件人: darshankawar
发送时间: 2020年8月25日 19:20
收件人: flutter/flutter
抄送: widealpha; Mention
主题: Re: [flutter/flutter] Either the assertion indicates an error in theframework itself, or we should provide substantially more information in thiserror message to help you determine and fix the underlying cause. (#51204)

Hi @widealpha,
Can you please confirm if you still experience this issue on latest Stable (1.20.2) version ?
Thanks.

**Comment by darshankawar** [comment]
Closing this as fixed.
