### ISSUE TITLE
HOT RELOAD: Holding a button down across a reassemble can lead to an assertion failure

### ISSUE THREAD

**Issue by johnmccutchan** [flutter/flutter#5121]
1. Take the Flutter Demo application.
2. Run with --hot
3. Tap the button obsessively 
4. Perform a reload

```
Syncing files on device...                           0.1s
Synced 0.0MB MB
Performing hot reload                                2.3s
Reassembling application                             1.0s
I/flutter : ══╡ EXCEPTION CAUGHT BY GESTURE LIBRARY ╞═══════════════════════════════════════════════════════════
I/flutter : The following assertion was thrown while routing a pointer event:
I/flutter : 'package:flutter/src/gestures/pointer_router.dart': Failed assertion: line 42 pos 12:
I/flutter : 'routes.contains(route)' is not true.
I/flutter : When the exception was thrown, this was the stack:
I/flutter : #2      PointerRouter.removeRoute (package:flutter/src/gestures/pointer_router.dart:42:12)
I/flutter : #3      OneSequenceGestureRecognizer.stopTrackingPointer (package:flutter/src/gestures/recognizer.dart:118:45)
I/flutter : #4      OneSequenceGestureRecognizer.stopTrackingIfPointerNoLongerDown (package:flutter/src/gestures/recognizer.dart:129:7)
I/flutter : #5      PrimaryPointerGestureRecognizer.handleEvent (package:flutter/src/gestures/recognizer.dart:201:5)
I/flutter : #6      PointerRouter._dispatch (package:flutter/src/gestures/pointer_router.dart:73:12)
I/flutter : #7      PointerRouter.route (package:flutter/src/gestures/pointer_router.dart:101:11)
I/flutter : #8      BindingBase&SchedulerBinding&GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:133:19)
I/flutter : #9      BindingBase&SchedulerBinding&GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:111:22)
I/flutter : #10     BindingBase&SchedulerBinding&GestureBinding._handlePointerEvent (package:flutter/src/gestures/binding.dart:92:7)
I/flutter : #11     BindingBase&SchedulerBinding&GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:51:7)
I/flutter : #12     BindingBase&SchedulerBinding&GestureBinding._handlePointerPacket (package:flutter/src/gestures/binding.dart:44:5)
I/flutter : #13     _dispatchPointerPacket (file:///b/build/slave/Linux_Engine/build/src/out/android_debug/gen/sky/bindings/dart_ui/hooks.dart:43)
I/flutter : (elided 2 frames from class _AssertionError)
I/flutter : Event:
I/flutter :   PointerUpEvent(Point(565.2, 864.4))
I/flutter : ════════════════════════════════════════════════════════════════════════════════════════════════════
I/flutter : Another exception was thrown: 'package:flutter/src/gestures/pointer_router.dart': Failed assertion: line 42 pos 12: 'routes.contains(route)' is not true.
```

**Comment by johnmccutchan** [comment]
@Hixie

**Comment by johnmccutchan** [comment]
Simple way to reproduce:

Press and hold the button
Perform a reload
Release the button

```
I/flutter : ══╡ EXCEPTION CAUGHT BY GESTURE LIBRARY ╞═══════════════════════════════════════════════════════════
I/flutter : The following assertion was thrown while routing a pointer event:
I/flutter : 'package:flutter/src/gestures/pointer_router.dart': Failed assertion: line 42 pos 12:
I/flutter : 'routes.contains(route)' is not true.
I/flutter : When the exception was thrown, this was the stack:
I/flutter : #2      PointerRouter.removeRoute (package:flutter/src/gestures/pointer_router.dart:42:12)
I/flutter : #3      OneSequenceGestureRecognizer.stopTrackingPointer (package:flutter/src/gestures/recognizer.dart:118:45)
I/flutter : #4      OneSequenceGestureRecognizer.stopTrackingIfPointerNoLongerDown (package:flutter/src/gestures/recognizer.dart:129:7)
I/flutter : #5      PrimaryPointerGestureRecognizer.handleEvent (package:flutter/src/gestures/recognizer.dart:201:5)
I/flutter : #6      PointerRouter._dispatch (package:flutter/src/gestures/pointer_router.dart:73:12)
I/flutter : #7      PointerRouter.route (package:flutter/src/gestures/pointer_router.dart:101:11)
I/flutter : #8      BindingBase&SchedulerBinding&GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:133:19)
I/flutter : #9      BindingBase&SchedulerBinding&GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:111:22)
I/flutter : #10     BindingBase&SchedulerBinding&GestureBinding._handlePointerEvent (package:flutter/src/gestures/binding.dart:92:7)
I/flutter : #11     BindingBase&SchedulerBinding&GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:51:7)
I/flutter : #12     BindingBase&SchedulerBinding&GestureBinding._handlePointerPacket (package:flutter/src/gestures/binding.dart:44:5)
I/flutter : #13     _dispatchPointerPacket (file:///b/build/slave/Linux_Engine/build/src/out/android_debug/gen/sky/bindings/dart_ui/hooks.dart:43)
I/flutter : (elided 2 frames from class _AssertionError)
I/flutter : Event:
I/flutter :   PointerUpEvent(Point(552.7, 883.3))
I/flutter : ════════════════════════════════════════════════════════════════════════════════════════════════════
I/flutter : Another exception was thrown: 'package:flutter/src/gestures/pointer_router.dart': Failed assertion: line 42 pos 12: 'routes.contains(route)' is not true.
I/flutter : Another exception was thrown: 'package:flutter/src/gestures/pointer_router.dart': Failed assertion: line 67 pos 12: '_globalRoutes.contains(route)' is not true.
```

**Comment by Hixie** [comment]
Interesting.

**Comment by Hixie** [comment]
This would be explained by closure identity not surviving a reload. I'll look into it more though to see if it's something else.

**Comment by Hixie** [comment]
("route", as seen in the stack, is a closure)

**Comment by johnmccutchan** [comment]
Never mind I was using an old engine. Doh!
