### ISSUE TITLE
AnimatedContainer + GoogleMaps Package == Buggy

### ISSUE THREAD

**Issue by iLePix** [flutter/flutter#51231]
The 'full' issue (written below) appears only once and after that I only get this exception : 

flutter: Another exception was thrown: RenderBox was not laid out: RenderUiKitView#7747f NEEDS-LAYOUT NEEDS-PAINT - but on every click on the scaffold

The full issue / error / exception is written below  

Error : 
```
flutter: ══╡ EXCEPTION CAUGHT BY GESTURE LIBRARY ╞═══════════════════════════════════════════════════════════
flutter: The following assertion was thrown while routing a pointer event:
flutter: RenderBox was not laid out: RenderUiKitView#7747f NEEDS-LAYOUT NEEDS-PAINT
flutter: 'package:flutter/src/rendering/box.dart':
flutter: Failed assertion: line 1687 pos 12: 'hasSize'
flutter:
flutter: Either the assertion indicates an error in the framework itself, or we should provide substantially
flutter: more information in this error message to help you determine and fix the underlying cause.
flutter: In either case, please report this assertion by filing a bug on GitHub:
flutter:   https://github.com/flutter/flutter/issues/new?template=BUG.md
flutter:
flutter: When the exception was thrown, this was the stack:
flutter: #2      RenderBox.size (package:flutter/src/rendering/box.dart:1687:12)
flutter: #3      RenderUiKitView._handleGlobalPointerEvent (package:flutter/src/rendering/platform_view.dart:353:25)
flutter: #4      PointerRouter._dispatch (package:flutter/src/gestures/pointer_router.dart:76:12)
flutter: #5      PointerRouter._dispatchEventToRoutes.<anonymous closure> (package:flutter/src/gestures/pointer_router.dart:117:9)
flutter: #6      _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:379:8)
flutter: #7      PointerRouter._dispatchEventToRoutes (package:flutter/src/gestures/pointer_router.dart:115:18)
flutter: #8      PointerRouter.route (package:flutter/src/gestures/pointer_router.dart:107:5)
flutter: #9      GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:218:19)
flutter: #10     GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:198:22)
flutter: #11     GestureBinding._handlePointerEvent (package:flutter/src/gestures/binding.dart:156:7)
flutter: #12     GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:102:7)
flutter: #13     GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:86:7)
flutter: #17     _invoke1 (dart:ui/hooks.dart:273:10)
flutter: #18     _dispatchPointerDataPacket (dart:ui/hooks.dart:182:5)
flutter: (elided 5 frames from class _AssertionError and package dart:async)
flutter:
flutter: Event:
flutter:   PointerDownEvent#b298f(position: Offset(324.7, 138.0), timeStamp: 2:33:06.079421, pointer: 1,
flutter:   kind: touch, device: 140221192234704, buttons: 1, down: true, pressure: 0.0, pressureMin: 0.0,
flutter:   pressureMax: 6.7, radiusMajor: 6.7, radiusMin: 5.0, radiusMax: 8.3, orientation: -1.6)
flutter: ════════════════════════════════════════════════════════════════════════════════════════════════════
flutter: Another exception was thrown: RenderBox was not laid out: RenderUiKitView#7747f NEEDS-LAYOUT NEEDS-PAINT


Flutter Doctor : 

[✓] Flutter (Channel stable, v1.12.13+hotfix.8, on Mac OS X 10.14.5 18F132,
    locale de-DE)
 
[!] Android toolchain - develop for Android devices (Android SDK version 29.0.0)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor
      --android-licenses
[✓] Xcode - develop for iOS and macOS (Xcode 11.3.1)
[✓] Android Studio (version 3.3)
[✓] IntelliJ IDEA Community Edition (version 2019.1.2)
[✓] Connected device (1 available)

! Doctor found issues in 1 category.

```

To reproduce simply add this to your normal app:

bool _visibleMap = true;
double _mapHeight = 300;
double _mapWidth = 300;

```
AnimatedContainer(

      height: _mapHeight,
      width: _mapWidth,
      duration: Duration(milliseconds: 500),
      curve: Curves.fastOutSlowIn,
      onEnd: () {setState(() {
        _animationFinished = true;
      });},
      child: Stack(
        children: <Widget>[
          Align(
            alignment: Alignment.topCenter,
            child: ClipRRect(
              borderRadius:
              BorderRadius.vertical(bottom: Radius.circular(50.0)),
                child: GoogleMap(
                  padding: EdgeInsets.only(left: 20, bottom: 5),
                  trafficEnabled: false,
                  buildingsEnabled: false,
                  myLocationButtonEnabled: false,
                  myLocationEnabled: false,
                  scrollGesturesEnabled: false,
                  tiltGesturesEnabled: false,
                  mapType: MapType.normal,
                  initialCameraPosition:
                  CameraPosition(target: LatLng(53.551573, 9.9942684), zoom: 12.0),
                  onMapCreated: mapCreated,
                )
            ),
          ),
          FloatingActionButton(
            child: Icon(Icons.add),
            onPressed: () {
              if (_visibleMap) {
                setState(() {
                  _mapHeight = 0;
                  _mapWidth = 0;
                });
              } else {
                _mapHeight = 300;
                _mapWidth = 300;
              }
            },
          ),
        ],
      ),
    )

```

Thanks for providing such an incredible framework!

**Comment by pedromassangocode** [comment]
Hi @iLePix 
Are you still facing this issue? If yes, then, please share your  `flutter doctor -v`.
Thank you

**Comment by pedromassangocode** [comment]
Hi @iLePix 
I will also need a complete sample code that I can just copy/paste into a `main.dart` and run it. The code you provided above is not complete.

**Comment by goderbauer** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!Thanks for your contribution.
