### ISSUE TITLE
'package:flutter/src/rendering/sliver_multi_box_adaptor.dart': Failed assertion: line 263 pos 16:

### ISSUE THREAD

**Issue by abdullah432** [flutter/flutter#51268]
```
  Widget _buildBody(BuildContext context) {
    return StreamBuilder<QuerySnapshot>(
      stream: Firestore.instance.collection('services').snapshots(),
      builder: (context, snapshot) {
        if (!snapshot.hasData) return noServiceBody(context);

        return _buildList(context, snapshot.data.documents);
      },
    );
  }

  Widget _buildList(BuildContext context, List<DocumentSnapshot> snapshot) {
    return Column(
      children: <Widget>[
        uperPart(),
        ListView(
          shrinkWrap: true,
          padding: const EdgeInsets.only(top: 20.0),
          children:
              snapshot.map((data) => _buildListItem(context, data)).toList(),
        )
      ],
    );
  }

  Widget _buildListItem(BuildContext context, DocumentSnapshot data) {
    final record = Service.fromSnapshot(data);
    _imageUrl = record.imageurl;

    return Padding(
        key: ValueKey(record.name),
        padding: const EdgeInsets.symmetric(horizontal: 16.0, vertical: 2.0),
        child: Card(
          shape: RoundedRectangleBorder(
            borderRadius: BorderRadius.circular(12.0),
          ),
          child: Padding(
            padding: const EdgeInsets.only(top: 10, bottom: 10),
            child: ListTile(
              leading: CircleAvatar(
                radius: 35,
                // backgroundColor: Colors.black,
                child: ClipOval(
                    child: _imageUrl == null
                        ? Image.asset(
                            'assets/images/account.png',
                          )
                        : Image.network(
                            _imageUrl,
                            fit: BoxFit.fill,
                            width: 60,
                          )),
              ),
              title: Text(record.name),
              subtitle: Text(record.description, maxLines: 6, overflow: TextOverflow.ellipsis,),
              trailing: Container(
                decoration: BoxDecoration(
                    shape: BoxShape.circle,
                    border: Border.all(color: Colors.black12, width: 2)),
                child: Padding(
                  padding: const EdgeInsets.all(8.0),
                  child: Icon(
                    Icons.message,
                    color: Colors.blue,
                    size: 18,
                  ),
                ),
              ),
            ),
          ),
        ));
  }
```

When i update any field at firestore or hot reload program. Following error occur. It's same code here (https://codelabs.developers.google.com/codelabs/flutter-firebase/index.html#10) with little modification.
```
I/flutter (30560): ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
I/flutter (30560): The following assertion was thrown building Listener:
I/flutter (30560): 'package:flutter/src/rendering/sliver_multi_box_adaptor.dart': Failed assertion: line 263 pos 16:
I/flutter (30560): 'child == null || indexOf(child) > index': is not true.
I/flutter (30560): Either the assertion indicates an error in the framework itself, or we should provide substantially
I/flutter (30560): more information in this error message to help you determine and fix the underlying cause.
I/flutter (30560): In either case, please report this assertion by filing a bug on GitHub:
I/flutter (30560):   https://github.com/flutter/flutter/issues/new?template=BUG.md
I/flutter (30560): The relevant error-causing widget was:
I/flutter (30560):   ListView file:///E:/Tutorial/Flutter%20Dev/liderfacilites/lib/screens/servicespage.dart:44:9
I/flutter (30560): When the exception was thrown, this was the stack:
I/flutter (30560): #2      RenderSliverMultiBoxAdaptor._debugVerifyChildOrder (package:flutter/src/rendering/sliver_multi_box_adaptor.dart:263:16)
I/flutter (30560): #3      RenderSliverMultiBoxAdaptor.debugChildIntegrityEnabled=.<anonymous closure> (package:flutter/src/rendering/sliver_multi_box_adaptor.dart:238:14)
I/flutter (30560): #4      RenderSliverMultiBoxAdaptor.debugChildIntegrityEnabled= (package:flutter/src/rendering/sliver_multi_box_adaptor.dart:240:6)
I/flutter (30560): #5      SliverMultiBoxAdaptorElement.performRebuild (package:flutter/src/widgets/sliver.dart:1255:20)
I/flutter (30560): #6      SliverMultiBoxAdaptorElement.update (package:flutter/src/widgets/sliver.dart:1191:7)
I/flutter (30560): #7      Element.updateChild (package:flutter/src/widgets/framework.dart:2977:15)
I/flutter (30560): #8      SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:5452:14)
I/flutter (30560): #9      Element.updateChild (package:flutter/src/widgets/framework.dart:2977:15)
I/flutter (30560): #10     RenderObjectElement.updateChildren (package:flutter/src/widgets/framework.dart:5161:32)
I/flutter (30560): #11     MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:5561:17)
I/flutter (30560): #12     Element.updateChild (package:flutter/src/widgets/framework.dart:2977:15)
I/flutter (30560): #13     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:5452:14)
I/flutter (30560): #14     Element.updateChild (package:flutter/src/widgets/framework.dart:2977:15)
I/flutter (30560): #15     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:5452:14)
I/flutter (30560): #16     Element.updateChild (package:flutter/src/widgets/framework.dart:2977:15)
I/flutter (30560): #17     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:5452:14)
I/flutter (30560): #18     Element.updateChild (package:flutter/src/widgets/framework.dart:2977:15)
I/flutter (30560): #19     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4243:16)
I/flutter (30560): #20     Element.rebuild (package:flutter/src/widgets/framework.dart:3947:5)
I/flutter (30560): #21     StatelessElement.update (package:flutter/src/widgets/framework.dart:4298:5)
I/flutter (30560): #22     Element.updateChild (package:flutter/src/widgets/framework.dart:2977:15)
I/flutter (30560): #23     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:5452:14)
I/flutter (30560): #24     Element.updateChild (package:flutter/src/widgets/framework.dart:2977:15)
I/flutter (30560): #25     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4243:16)
I/flutter (30560): #26     Element.rebuild (package:flutter/src/widgets/framework.dart:3947:5)
I/flutter (30560): #27     StatefulElement.update (package:flutter/src/widgets/framework.dart:4413:5)
I/flutter (30560): #28     Element.updateChild (package:flutter/src/widgets/framework.dart:2977:15)
I/flutter (30560): #29     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:5452:14)
I/flutter (30560): #30     Element.updateChild (package:flutter/src/widgets/framework.dart:2977:15)
I/flutter (30560): #31     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4243:16)
I/flutter (30560): #32     Element.rebuild (package:flutter/src/widgets/framework.dart:3947:5)
I/flutter (30560): #33     StatelessElement.update (package:flutter/src/widgets/framework.dart:4298:5)
I/flutter (30560): #34     Element.updateChild (package:flutter/src/widgets/framework.dart:2977:15)
I/flutter (30560): #35     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4243:16)
I/flutter (30560): #36     Element.rebuild (package:flutter/src/widgets/framework.dart:3947:5)
I/flutter (30560): #37     ProxyElement.update (package:flutter/src/widgets/framework.dart:4557:5)
I/flutter (30560): #38     Element.updateChild (package:flutter/src/widgets/framework.dart:2977:15)
I/flutter (30560): #39     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:5452:14)
I/flutter (30560): #40     Element.updateChild (package:flutter/src/widgets/framework.dart:2977:15)
I/flutter (30560): #41     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:5452:14)
I/flutter (30560): #42     Element.updateChild (package:flutter/src/widgets/framework.dart:2977:15)
I/flutter (30560): #43     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:5452:14)
I/flutter (30560): #44     Element.updateChild (package:flutter/src/widgets/framework.dart:2977:15)
I/flutter (30560): #45     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:5452:14)
I/flutter (30560): #46     Element.updateChild (package:flutter/src/widgets/framework.dart:2977:15)
I/flutter (30560): #47     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4243:16)
I/flutter (30560): #48     Element.rebuild (package:flutter/src/widgets/framework.dart:3947:5)
I/flutter (30560): #49     StatelessElement.update (package:flutter/src/widgets/framework.dart:4298:5)
I/flutter (30560): #50     Element.updateChild (package:flutter/src/widgets/framework.dart:2977:15)
I/flutter (30560): #51     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4243:16)
I/flutter (30560): #52     Element.rebuild (package:flutter/src/widgets/framework.dart:3947:5)
I/flutter (30560): #53     StatefulElement.update (package:flutter/src/widgets/framework.dart:4413:5)
I/flutter (30560): #54     Element.updateChild (package:flutter/src/widgets/framework.dart:2977:15)
I/flutter (30560): #55     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4243:16)
I/flutter (30560): #56     Element.rebuild (package:flutter/src/widgets/framework.dart:3947:5)
I/flutter (30560): #57     StatefulElement.update (package:flutter/src/widgets/framework.dart:4413:5)
I/flutter (30560): #58     Element.updateChild (package:flutter/src/widgets/framework.dart:2977:15)
I/flutter (30560): #59     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4243:16)
I/flutter (30560): #60     Element.rebuild (package:flutter/src/widgets/framework.dart:3947:5)
I/flutter (30560): #61     StatelessElement.update (package:flutter/src/widgets/framework.dart:4298:5)
I/flutter (30560): #62     Element.updateChild (package:flutter/src/widgets/framework.dart:2977:15)
I/flutter (30560): #63     RenderObjectElement.updateChildren (package:flutter/src/widgets/framework.dart:5161:32)
I/flutter (30560): #64     MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:5561:17)
I/flutter (30560): #65     Element.updateChild (package:flutter/src/widgets/framework.dart:2977:15)
I/flutter (30560): #66     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4243:16)
I/flutter (30560): #67     Element.rebuild (package:flutter/src/widgets/framework.dart:3947:5)
I/flutter (30560): #68     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2432:33)
I/flutter (30560): #69     WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:773:20)
I/flutter (30560): #70     RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:283:5)
I/flutter (30560): #71     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1102:15)
I/flutter (30560): #72     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1041:9)
I/flutter (30560): #73     SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:957:5)
I/flutter (30560): #77     _invoke (dart:ui/hooks.dart:259:10)
I/flutter (30560): #78     _drawFrame (dart:ui/hooks.dart:217:3)
I/flutter (30560): (elided 5 frames from class _AssertionError and package dart:async)
```

**Comment by abdullah432** [comment]
**Solution:** Remove  `key: ValueKey(record.name),`
Error occur due to duplicate key

**Comment by TahaTesser** [comment]
Hi @abdullah432 
given your last message I feel safe to close this issue,
if you disagree please write in the comments and I will reopen it.
Thank you

**Comment by vikil143** [comment]
Same issue was coming when I 



This is error log


`════════ Exception caught by rendering library ═════════════════════════════════
'package:flutter/src/rendering/sliver_multi_box_adaptor.dart': Failed assertion: line 544 pos 12: 'child.hasSize': is not true.
The relevant error-causing widget was
ListView
lib\…\dashboard\dashboard_screen.dart:62
════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by rendering library ═════════════════════════════════
Null check operator used on a null value`

**Comment by anneluciaqa** [comment]
import 'package:csv/csv.dart';
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:list_dermato/user.dart';

class ListDermatoScreen extends StatefulWidget {
  final User user;
  ListDermatoScreen({this.user});

  @override
  _ListDermatoScreenState createState() => _ListDermatoScreenState();
}

class _ListDermatoScreenState extends State<ListDermatoScreen> {
  List<List<dynamic>> _data = [];

  void _loadCSV() async {
    final _rawData =
        await rootBundle.loadString("data/webscrap_list_of_dermato.csv");
    List<List<dynamic>> _listData = CsvToListConverter().convert(_rawData);
    setState(() {
      _data = _listData;
    });
  }

  void initState() {
    _loadCSV();
    super.initState();
  }

  @override
  Widget build(BuildContext context) {
    Size size = MediaQuery.of(context).size;
    return Scaffold(
      backgroundColor: Theme.of(context).primaryColor,
      appBar: AppBar(
        title: Text('List of Dermatologist',
            style: Theme.of(context).textTheme.headline6),
        backgroundColor: Theme.of(context).accentColor,
      ),
      body: Column(
        children: [
          Card(
            child: Column(
              children: [
                Row(
                  children: [
                    Text("latitude: ", style: TextStyle(color: Colors.black)),
                    Text('${widget.user.userLatitude}',
                        style: TextStyle(color: Colors.black))
                  ],
                ),
                Row(
                  children: [
                    Text("longititude: ",
                        style: TextStyle(color: Colors.black)),
                    Text('${widget.user.userLongititude}',
                        style: TextStyle(color: Colors.black))
                  ],
                ),
              ],
            ),
          ),
          Container(
            height: 480,
            width: 100,
            child: ListView.builder(
              itemCount: _data.length,
              shrinkWrap: true,
              itemBuilder: (ctx, index) {
                return Card(
                  margin: EdgeInsets.symmetric(vertical: 8, horizontal: 5),
                  child: ListTile(
                    leading: Text(_data[index][0].toString()),
                    title: Text(_data[index][1].toString()),
                    trailing: Text(_data[index][2].toString()),
                  ),
                );
              },
            ),
          ),
        ],
      ),
    );
  }
}



i got this error

'package:flutter/src/rendering/sliver_multi_box_adaptor.dart': Failed assertion: line 544 pos 12: 'child.hasSize': is not true.
The relevant error-causing widget was
ListView
lib\list_dermato_screen copy.dart:67

I have tried many method

**Comment by TahaTesser** [comment]
Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
