### ISSUE TITLE
Flutter app crashes are splash screen on stable hot fix 8 - Urgent Help Needed 

### ISSUE THREAD

**Issue by NTMS2017** [flutter/flutter#51272]
Hi,

This weekend I need to update my app but with no major changes suddenly my flutter app start to crash after splash screen. It doesn't show me complete error. All it says '_No preferred FlutterEngine was provided'.

I need to update my app asap. Any urgent help please.

**ERROR:**
```
✓ Built build/app/outputs/apk/debug/app-debug.apk.
Installing build/app/outputs/apk/app.apk...
D/FlutterActivity(17864): Using the launch theme as normal theme.
D/FlutterActivityAndFragmentDelegate(17864): Setting up FlutterEngine.
D/FlutterActivityAndFragmentDelegate(17864): No preferred FlutterEngine was provided. Creating a new FlutterEngine for this FlutterFragment.
D/FlutterActivityAndFragmentDelegate(17864): Attaching FlutterEngine to the Activity that owns this Fragment.
Syncing files to device SM G935F...
Lost connection to device.
Could not update files on device: HttpException: Connection closed before full header was received, uri = http://127.0.0.1:52676/hdvtGApxNO8=/
```

**AndroidManifest.xml:**
```
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    package="com.***********.*******">

<!-- The INTERNET permission is required for development. Specifically,
           flutter needs it to communicate with the running application
           to allow setting breakpoints, to provide hot reload, etc.
      -->
    <uses-permission android:name="android.permission.INTERNET"/>

    <!-- io.flutter.app.FlutterApplication is an android.app.Application that
         calls FlutterMain.startInitialization(this); in its onCreate method.
         In most cases you can leave this as-is, but you if you want to provide
         additional functionality it is fine to subclass or reimplement
         FlutterApplication and put your custom class here. -->
    <application
        android:name="io.flutter.app.FlutterApplication"
        android:label="*********"
        android:icon="@mipmap/ic_launcher">
        <activity
            android:name=".MainActivity"
            android:launchMode="singleTop"
            android:theme="@style/LaunchTheme"
            android:configChanges="orientation|keyboardHidden|keyboard|screenSize|smallestScreenSize|locale|layoutDirection|fontScale|screenLayout|density|uiMode"
            android:hardwareAccelerated="true"
            android:windowSoftInputMode="adjustResize">
            <intent-filter>
                <action android:name="android.intent.action.MAIN"/>
                <category android:name="android.intent.category.LAUNCHER"/>
            </intent-filter>
        </activity>
        <!-- Don't delete the meta-data below.
             This is used by the Flutter tool to generate GeneratedPluginRegistrant.java -->
        <meta-data
           android:name="flutterEmbedding"
           android:value="2" />
   </application>
</manifest>
```

**main.dart**
```
void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await SystemChrome.setEnabledSystemUIOverlays([]);
  await SystemChrome.setPreferredOrientations([DeviceOrientation.portraitUp]);
  runApp(new MyApp());
}
```

**flutter doctor -v**
```
[✓] Flutter (Channel stable, v1.12.13+hotfix.8, on Mac OS X 10.15.3 19D76, locale en-CY)
    • Flutter version 1.12.13+hotfix.8 at /Users/**********/flutter
    • Framework revision 0b8abb4724 (11 days ago), 2020-02-11 11:44:36 -0800
    • Engine revision e1e6ced81d
    • Dart version 2.7.0

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/**********/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.3.1, Build version 11C504
    • CocoaPods version 1.8.4

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 43.0.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] Connected device (1 available)
    • SM G935F • ce12160c0d86152e01 • android-arm64 • Android 8.0.0 (API 26)

```

**Comment by NTMS2017** [comment]
I update some plugin which release on 20 Feb. And now I am getting this error. Any help please.

```
Launching lib/main.dart on SM G935F in debug mode...
Running Gradle task 'assembleDebug'...
Note: /Users/************/flutter/.pub-cache/hosted/pub.dartlang.org/device_info-0.4.1+5/android/src/main/java/io/flutter/plugins/deviceinfo/DeviceInfoPlugin.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
Note: /Users/************/flutter/.pub-cache/hosted/pub.dartlang.org/path_provider-1.6.1/android/src/main/java/io/flutter/plugins/pathprovider/PathProviderPlugin.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: /Users/************/flutter/.pub-cache/hosted/pub.dartlang.org/package_info-0.4.0+14/android/src/main/java/io/flutter/plugins/packageinfo/PackageInfoPlugin.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
/Users/************/flutter/.pub-cache/hosted/pub.dartlang.org/shared_preferences-0.5.6+2/android/src/main/java/io/flutter/plugins/sharedpreferences/SharedPreferencesPlugin.java:25: warning: [deprecation] getFlutterEngine() in FlutterPluginBinding has been deprecated
    setupChannel(binding.getFlutterEngine().getDartExecutor(), binding.getApplicationContext());
                        ^
1 warning
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
java.nio.file.NoSuchFileException: /Users/************/IdeaProjects/capital_cep/build/app/intermediates/external_file_lib_dex_archives/debug/out
	at sun.nio.fs.UnixException.translateToIOException(UnixException.java:86)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107)
	at sun.nio.fs.UnixFileSystemProvider.newDirectoryStream(UnixFileSystemProvider.java:407)
	at java.nio.file.Files.newDirectoryStream(Files.java:457)
	at java.nio.file.Files.list(Files.java:3451)
	at com.android.build.gradle.internal.tasks.DexMergingParams.getAllDexFiles(DexMergingTask.kt:502)
	at com.android.build.gradle.internal.tasks.DexMergingTaskRunnable.run(DexMergingTask.kt:423)
	at com.android.build.gradle.internal.tasks.Workers$ActionFacade.run(Workers.kt:335)
	at org.gradle.workers.internal.AdapterWorkAction.execute(AdapterWorkAction.java:50)
	at org.gradle.workers.internal.DefaultWorkerServer.execute(DefaultWorkerServer.java:47)
	at org.gradle.workers.internal.NoIsolationWorkerFactory$1$1$1.create(NoIsolationWorkerFactory.java:65)
	at org.gradle.workers.internal.NoIsolationWorkerFactory$1$1$1.create(NoIsolationWorkerFactory.java:61)
	at org.gradle.internal.classloader.ClassLoaderUtils.executeInClassloader(ClassLoaderUtils.java:98)
	at org.gradle.workers.internal.NoIsolationWorkerFactory$1$1.execute(NoIsolationWorkerFactory.java:61)
	at org.gradle.workers.internal.AbstractWorker$1.call(AbstractWorker.java:44)
	at org.gradle.workers.internal.AbstractWorker$1.call(AbstractWorker.java:41)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor$CallableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:416)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor$CallableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:406)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor$1.execute(DefaultBuildOperationExecutor.java:165)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:250)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:158)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.call(DefaultBuildOperationExecutor.java:102)
	at org.gradle.internal.operations.DelegatingBuildOperationExecutor.call(DelegatingBuildOperationExecutor.java:36)
	at org.gradle.workers.internal.AbstractWorker.executeWrappedInBuildOperation(AbstractWorker.java:41)
	at org.gradle.workers.internal.NoIsolationWorkerFactory$1.execute(NoIsolationWorkerFactory.java:56)
	at org.gradle.workers.internal.DefaultWorkerExecutor$3.call(DefaultWorkerExecutor.java:215)
	at org.gradle.workers.internal.DefaultWorkerExecutor$3.call(DefaultWorkerExecutor.java:210)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at org.gradle.internal.work.DefaultConditionalExecutionQueue$ExecutionRunner.runExecution(DefaultConditionalExecutionQueue.java:215)
	at org.gradle.internal.work.DefaultConditionalExecutionQueue$ExecutionRunner.runBatch(DefaultConditionalExecutionQueue.java:164)
	at org.gradle.internal.work.DefaultConditionalExecutionQueue$ExecutionRunner.run(DefaultConditionalExecutionQueue.java:131)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
	at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:48)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:56)
	at java.lang.Thread.run(Thread.java:748)


FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:mergeExtDexDebug'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.Workers$ActionFacade
   > java.nio.file.NoSuchFileException: /Users/************/IdeaProjects/capital_cep/build/app/intermediates/external_file_lib_dex_archives/debug/out

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 28s
Finished with error: Gradle task assembleDebug failed with exit code 1
```

**Comment by NTMS2017** [comment]
I open android folder with AndroidStudio and found no error. Than I type flutter run and got unusal line even ask me take a picture.



```
flutter run
 
Launching lib/main.dart on SM G935F in debug mode...
Running Gradle task 'assembleDebug'...                                  
                                                   
Running Gradle task 'assembleDebug'... Done                       127.4s (!)
✓ Built build/app/outputs/apk/debug/app-debug.apk.
D/FlutterActivity(27141): Using the launch theme as normal theme.
D/FlutterActivityAndFragmentDelegate(27141): Setting up FlutterEngine.
D/FlutterActivityAndFragmentDelegate(27141): No preferred FlutterEngine was provided. Creating a new FlutterEngine for this FlutterFragment.
D/FlutterActivityAndFragmentDelegate(27141): Attaching FlutterEngine to the Activity that owns this Fragment.
Syncing files to device SM G935F...                                     
11,163ms (!)                                       

🔥  To hot reload changes while running, press "r". To hot restart (and rebuild state), press "R".
An Observatory debugger and profiler on SM G935F is available at: http://127.0.0.1:57815/ocs6jt1RWTs=/
For a more detailed help message, press "h". To detach, press "d"; to quit, press "q".

🔥  To hot reload changes while running, press "r". To hot restart (and rebuild state), press "R".
An Observatory debugger and profiler on SM G935F is available at: http://127.0.0.1:57815/ocs6jt1RWTs=/
You can dump the widget hierarchy of the app (debugDumpApp) by pressing "w".
To dump the rendering tree of the app (debugDumpRenderTree), press "t".
For layers (debugDumpLayerTree), use "L"; for accessibility (debugDumpSemantics), use "S" (for traversal order) or "U"
(for inverse hit test order).
To toggle the widget inspector (WidgetsApp.showWidgetInspectorOverride), press "i".
To toggle the display of construction lines (debugPaintSizeEnabled), press "p".
To simulate different operating systems, (defaultTargetPlatform), press "o".
To toggle the elevation checker, press "z".
To display the performance overlay (WidgetsApp.showPerformanceOverlay), press "P".
To enable timeline events for all widget build methods, (debugProfileWidgetBuilds), press "a"
To save a screenshot to flutter.png, press "s".
To repeat this help message, press "h". To detach, press "d"; to quit, press "q".

🔥  To hot reload changes while running, press "r". To hot restart (and rebuild state), press "R".
An Observatory debugger and profiler on SM G935F is available at: http://127.0.0.1:57815/ocs6jt1RWTs=/
You can dump the widget hierarchy of the app (debugDumpApp) by pressing "w".
To dump the rendering tree of the app (debugDumpRenderTree), press "t".
For layers (debugDumpLayerTree), use "L"; for accessibility (debugDumpSemantics), use "S" (for traversal order) or "U"
(for inverse hit test order).
To toggle the widget inspector (WidgetsApp.showWidgetInspectorOverride), press "i".
To toggle the display of construction lines (debugPaintSizeEnabled), press "p".
To simulate different operating systems, (defaultTargetPlatform), press "o".
To toggle the elevation checker, press "z".
To display the performance overlay (WidgetsApp.showPerformanceOverlay), press "P".
To enable timeline events for all widget build methods, (debugProfileWidgetBuilds), press "a"
To save a screenshot to flutter.png, press "s".
To repeat this help message, press "h". To detach, press "d"; to quit, press "q".

🔥  To hot reload changes while running, press "r". To hot restart (and rebuild state), press "R".
An Observatory debugger and profiler on SM G935F is available at: http://127.0.0.1:57815/ocs6jt1RWTs=/
You can dump the widget hierarchy of the app (debugDumpApp) by pressing "w".
To dump the rendering tree of the app (debugDumpRenderTree), press "t".
For layers (debugDumpLayerTree), use "L"; for accessibility (debugDumpSemantics), use "S" (for traversal order) or "U"
(for inverse hit test order).
To toggle the widget inspector (WidgetsApp.showWidgetInspectorOverride), press "i".
To toggle the display of construction lines (debugPaintSizeEnabled), press "p".
To simulate different operating systems, (defaultTargetPlatform), press "o".
To toggle the elevation checker, press "z".
To display the performance overlay (WidgetsApp.showPerformanceOverlay), press "P".
To enable timeline events for all widget build methods, (debugProfileWidgetBuilds), press "a"
To save a screenshot to flutter.png, press "s".
To repeat this help message, press "h". To detach, press "d"; to quit, press "q".

Error -32601 received from application: Method not found

Error -32601 received from application: Method not found                
Error -32601 received from application: Method not found                
Taking screenshot for SM G935F...                                1,597ms
Screenshot written to flutter_01.png (497kB).
Lost connection to device.
```

![Untitled](https://user-images.githubusercontent.com/33287468/75099763-1c05fd80-55ce-11ea-87f6-62df55a2d451.png)

**Comment by oyeolamilekan** [comment]
try flutter clean, and re-run it again.

**Comment by NTMS2017** [comment]
I did more than once no luck. I find that flutter_barcode_scanner: ^0.1.7 plugin causes the problem. I placed an issue but I am not sure if I can get quick help.

Below its shows all the plugin that I am using in my app. I created a simple flutter app and place the all the plugin inti pub spec.yaml. I comment them all. One by one I uncomment them and run flutter packages get. before uncommenting I use flutter clean and Invalidate and cash restart. 

When I come to flutter_barcode_scanner: ^0.1.7 my simple flutter app crashed on startup. Didn't give me a detail why this happened.

I comment the plugin and waiting solution.

**Plugin that I use:**
```
cupertino_icons: ^0.1.3
  connectivity: ^0.4.6+2
  decimal: ^0.3.5
  intl: ^0.16.0
  encrypt: 2.1.0
  image: ^2.1.4
  path_provider: ^1.6.1
  mailer: ^3.0.4
  flutter_slidable: ^0.4.9
  xml: ^3.5.0
  http: ^0.12.0+4
  page_transition: ^1.1.5
  flutter_swiper: ^1.1.6
  card_settings: ^1.6.1
  flutter_speed_dial: ^1.2.5
  drop_cap_text: ^1.0.3
  diacritic: ^0.1.1
  ntp: ^1.0.5
  flare_flutter: ^2.0.1
  image_picker: ^0.6.3+4
  image_crop: ^0.3.2
  webview_flutter: ^0.3.19+8
  url_launcher: ^5.4.2
  package_info: ^0.4.0+14
  flutter_screenutil: ^1.0.2
  auto_size_text: ^2.1.0
  in_app_update: ^1.1.6
  upgrader: ^0.10.1
  #flutter_barcode_scanner: ^0.1.7
```

**Comment by NTMS2017** [comment]
The **funny's part** is I found these under the flutter_barcode_scanner: ^0.1.7 plugin. Flutter team **analysed** the package on Feb 21, 2020 and tested with Flutter: 1.12.13+hotfix.7. But current flutter stable version is Flutter: 1.12.13+hotfix.8. 


We analyzed this package on Feb 21, 2020, and provided a score, details, and suggestions below. Analysis was completed with status completed using:

Dart: 2.7.1
pana: 0.13.5
Flutter: 1.12.13+hotfix.7

**Comment by oyeolamilekan** [comment]
how about you temporarily downgrade to the flutter version that was previously working with your project. at least before a solution is found.

**Comment by oyeolamilekan** [comment]
or you upgrade to the new hotfix which is ```Flutter 1.12.13+hotfix.8```

**Comment by KirolousNashaat** [comment]
try with '--no-shrink' , i had the same issue with some plugins

**Comment by NTMS2017** [comment]
I am still on Flutter 1.12.13+hotfix.8. And I will downgrade to Flutter 1.12.13+hotfix.7 to try again. 

But flutter team shouldn't analysed a package with old version. I will write later after downgrading.

I will also try --no-shrink. Thanks

**Comment by NTMS2017** [comment]
Run with Flutter 1.12.13+hotfix.7 and same problem. Didn't run build apk --no-shrink because I need to test my app first. 

And it was same problem. When I comment this #flutter_barcode_scanner: ^0.1.7 plugin it worked.

Any idea?

**Comment by TahaTesser** [comment]
Hi @NTMS2017 
Based on your last comment, this is clearly an issue with [flutter_barcode_scanner ](https://pub.dev/packages/flutter_barcode_scanner)
Please raise your issue on there [repo](https://pub.dev/packages/flutter_barcode_scanner)

Closing, as this isn't an issue with Flutter itself,
if you disagree please write in the comments and I will reopen it 
Thank you
