### ISSUE TITLE
Slider widget bug

### ISSUE THREAD

**Issue by 18814127739** [flutter/flutter#51288]
When i drag the slider widget progressbar,  it will throw an following error:
```
══╡ EXCEPTION CAUGHT BY GESTURE ╞═══════════════════════════════════════════════════════════════════
flutter: The following assertion was thrown while handling a gesture:
flutter: 'package:flutter/src/rendering/object.dart': Failed assertion: line 2285 pos 12: 'attached': is not
flutter: true.
flutter:
flutter: Either the assertion indicates an error in the framework itself, or we should provide substantially
flutter: more information in this error message to help you determine and fix the underlying cause.

flutter: When the exception was thrown, this was the stack:
flutter: #2      RenderObject.getTransformTo (package:flutter/src/rendering/object.dart:2285:12)
flutter: #3      RenderBox.globalToLocal (package:flutter/src/rendering/box.dart:2243:31)
flutter: #4      _RenderSlider._getValueFromGlobalPosition (package:flutter/src/material/slider.dart:956:36)
flutter: #5      _RenderSlider._startInteraction (package:flutter/src/material/slider.dart:977:27)
flutter: #6      _RenderSlider._handleDragStart (package:flutter/src/material/slider.dart:1008:54)
flutter: #7      DragGestureRecognizer._checkStart.<anonymous closure> (package:flutter/src/gestures/monodrag.dart:384:45)
flutter: #8      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:182:24)
flutter: #9      DragGestureRecognizer._checkStart (package:flutter/src/gestures/monodrag.dart:384:7)
flutter: #10     DragGestureRecognizer.acceptGesture (package:flutter/src/gestures/monodrag.dart:308:7)
flutter: #11     _CombiningGestureArenaMember.acceptGesture (package:flutter/src/gestures/team.dart:41:13)
flutter: #12     GestureArenaManager._resolveInFavorOf (package:flutter/src/gestures/arena.dart:263:12)
flutter: #13     GestureArenaManager._resolve (package:flutter/src/gestures/arena.dart:222:9)
flutter: #14     GestureArenaEntry.resolve (package:flutter/src/gestures/arena.dart:52:12)
............
```

**Comment by TahaTesser** [comment]
Hi @18814127739 
can you please provide your `flutter doctor -v` and `flutter run --verbose`? Also, to better address the issue, would be helpful if you could post a minimal code sample to reproduce the problem
Thank you

**Comment by TahaTesser** [comment]
Hi @18814127739 
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore
reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any
more information for us; we will reopen it right away!
Thanks for your contribution.
