### ISSUE TITLE
[Web] `flutter run` for web doesn't work on Windows 7 but works in windows 10 [Flutter SDK version >= 1.14.2 (master channel)]

### ISSUE THREAD

**Issue by GAM3RG33K** [flutter/flutter#51309]
## Steps to Reproduce

1. Run `flutter create demo`.
2. Run `flutter pub get`
3. Run `flutter run -d chrome -v`

**Expected results:** 
 The code should run fine on the web since it is the template code. There are no changes in the code

**Actual results:** 
 It seems everything other than `Web` works fine. However, I have not tested the same on MAC.
 What I found interesting is that on a pc with Windows 7 the web doesn't work, but on the pc with 
 Windows 10 it works fine. 

Same flutter channel and almost the same version. Most important is that Both projects contain only the template code. 

The only change is that the sdk configurations on windows 10 PC was configured to minimum requirements for a web build since it was not my pc.

<details>
  <summary>Logs[Windows 7]</summary>

```
D:\demos\flutter_demos\demo>flutter run -d chrome -v
[  +28 ms] executing: [C:\SDK\FlutterSDK\flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[ +112 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[   +1 ms] f81588a5a3b15b1f157a98b6d4c99b8609c3d16c
[        ] executing: [C:\SDK\FlutterSDK\flutter/] git describe --match v*.*.* --first-parent --long --tags
[ +107 ms] Exit code 0 from: git describe --match v*.*.* --first-parent --long --tags
[        ] v1.15.3-97-gf81588a5a
[   +8 ms] executing: [C:\SDK\FlutterSDK\flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[  +97 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/master
[        ] executing: [C:\SDK\FlutterSDK\flutter/] git ls-remote --get-url origin
[  +80 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[ +128 ms] executing: [C:\SDK\FlutterSDK\flutter/] git rev-parse --abbrev-ref HEAD
[ +107 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] master
[ +110 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +5 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +49 ms] executing: C:\SDK\Android_SDK\platform-tools\adb.exe devices -l
[  +45 ms] Exit code 0 from: C:\SDK\Android_SDK\platform-tools\adb.exe devices -l
[   +3 ms] List of devices attached
           emulator-5554          device product:sdk_google_phone_x86 model:Android_SDK_built_for_x86 device:generic_x86
           transport_id:1
[  +35 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[   +3 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[   +5 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[ +286 ms] Generating D:\demos\flutter_demos\demo\android\app\src\main\java\io\flutter\plugins\GeneratedPluginRegistrant.java
[ +153 ms] Launching lib\main.dart on Chrome in debug mode...
[  +46 ms] "flutter run" took 866ms.
Failed to bind web development server:
SocketException: Failed to create server socket (OS Error: Failed to start accept), address = localhost, port = 50673

#0      throwToolExit (package:flutter_tools/src/base/common.dart:14:3)
#1      WebAssetServer.start (package:flutter_tools/src/build_runner/devfs_web.dart:95:7)
<asynchronous suspension>
#2      WebDevFS.create (package:flutter_tools/src/build_runner/devfs_web.dart:383:43)
#3      _ResidentWebRunner.run.<anonymous closure> (package:flutter_tools/src/build_runner/resident_web_runner.dart:415:44)
#4      asyncGuard.<anonymous closure> (package:flutter_tools/src/base/async_guard.dart:111:32)
#5      _rootRun (dart:async/zone.dart:1126:13)
#6      _CustomZone.run (dart:async/zone.dart:1023:19)
#7      _runZoned (dart:async/zone.dart:1518:10)
#8      runZoned (dart:async/zone.dart:1502:12)
#9      asyncGuard (package:flutter_tools/src/base/async_guard.dart:109:3)
#10     _ResidentWebRunner.run (package:flutter_tools/src/build_runner/resident_web_runner.dart:405:20)
<asynchronous suspension>
#11     RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:563:37)
<asynchronous suspension>
#12     FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:681:18)
<asynchronous suspension>
#13     FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:579:33)
<asynchronous suspension>
#14     FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart)
#15     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:29)
#16     _rootRun (dart:async/zone.dart:1126:13)
#17     _CustomZone.run (dart:async/zone.dart:1023:19)
#18     _runZoned (dart:async/zone.dart:1518:10)
#19     runZoned (dart:async/zone.dart:1465:12)
#20     AppContext.run (package:flutter_tools/src/base/context.dart:149:18)
#21     FlutterCommand.run (package:flutter_tools/src/runner/flutter_command.dart:569:20)
#22     CommandRunner.runCommand (package:args/command_runner.dart:197:27)
#23     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:338:21)
<asynchronous suspension>
#24     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart)
#25     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:29)
#26     _rootRun (dart:async/zone.dart:1126:13)
#27     _CustomZone.run (dart:async/zone.dart:1023:19)
#28     _runZoned (dart:async/zone.dart:1518:10)
#29     runZoned (dart:async/zone.dart:1465:12)
#30     AppContext.run (package:flutter_tools/src/base/context.dart:149:18)
#31     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:288:19)
#32     CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:112:25)
#33     new Future.sync (dart:async/future.dart:224:31)
#34     CommandRunner.run (package:args/command_runner.dart:112:14)
#35     FlutterCommandRunner.run (package:flutter_tools/src/runner/flutter_command_runner.dart:231:18)
#36     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:63:22)
#37     _rootRun (dart:async/zone.dart:1126:13)
#38     _CustomZone.run (dart:async/zone.dart:1023:19)
#39     _runZoned (dart:async/zone.dart:1518:10)
#40     runZoned (dart:async/zone.dart:1502:12)
#41     run.<anonymous closure> (package:flutter_tools/runner.dart:61:18)
<asynchronous suspension>
#42     run.<anonymous closure> (package:flutter_tools/runner.dart)
#43     runInContext.runnerWrapper (package:flutter_tools/src/context_runner.dart:70:18)
<asynchronous suspension>
#44     runInContext.runnerWrapper (package:flutter_tools/src/context_runner.dart)
#45     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:29)
#46     _rootRun (dart:async/zone.dart:1126:13)
#47     _CustomZone.run (dart:async/zone.dart:1023:19)
#48     _runZoned (dart:async/zone.dart:1518:10)
#49     runZoned (dart:async/zone.dart:1465:12)
#50     AppContext.run (package:flutter_tools/src/base/context.dart:149:18)
#51     runInContext (package:flutter_tools/src/context_runner.dart:73:24)
#52     run (package:flutter_tools/runner.dart:50:10)
<asynchronous suspension>
#53     main (package:flutter_tools/executable.dart:68:9)
#54     main (file:///C:/SDK/FlutterSDK/flutter/packages/flutter_tools/bin/flutter_tools.dart:8:3)
#55     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:299:32)
#56     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:168:12)
```

```
D:\demos\flutter_demos\demo>flutter analyze
Analyzing demo...

   info - 'display1' is deprecated and shouldn't be used. This is the term used in the 2014 version of material design. The
          modern term is headline4. This feature was deprecated after v1.13.8. - lib\main.dart:99:50 - deprecated_member_use

1 issue found. (ran in 4.6s)
```

```
D:\demos\flutter_demos\demo>flutter doctor -v
[√] Flutter (Channel master, v1.15.4-pre.97, on Microsoft Windows [Version 6.1.7601], locale en-US)
    • Flutter version 1.15.4-pre.97 at C:\SDK\FlutterSDK\flutter
    • Framework revision f81588a5a3 (5 days ago), 2020-02-18 16:33:55 -0800
    • Engine revision 77c5812d48
    • Dart version 2.8.0 (build 2.8.0-dev.9.0 999eeea5a3)

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at C:\SDK\Android_SDK
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • ANDROID_HOME = C:\SDK\Android_SDK
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 3.5)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 43.0.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)

[√] VS Code (version 1.42.1)
    • VS Code at C:\Users\admin\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.8.1

[√] Connected device (3 available)
    • Android SDK built for x86 • emulator-5554 • android-x86    • Android 7.0 (API 24) (emulator)
    • Chrome                    • chrome        • web-javascript • Google Chrome 79.0.3945.130
    • Web Server                • web-server    • web-javascript • Flutter Tools

• No issues found!
```

</details>

<details>
  <summary>Logs[Windows 10]</summary>

```
F:\deleteMe\demo>flutter run -d chrome
Launching lib\main.dart on Chrome in debug mode...
Building application for the web...                                11.6s
Attempting to connect to browser instance..                        12.8s

Warning: Flutter's support for web development is not stable yet and hasn't
been thoroughly tested in production environments.
For more information see https://flutter.dev/web

:fire:  To hot restart changes while running, press "r". To hot restart (and refresh the browser), press "R".
For a more detailed help message, press "h". To quit, press "q".
Debug service listening on ws://127.0.0.1:52312/6Gle9g2WO_Y=
```

```
F:\deleteMe\demo>flutter doctor -v
[√] Flutter (Channel master, v1.15.2-pre.36, on Microsoft Windows [Version 10.0.17134.1040], locale en-US)
    • Flutter version 1.15.2-pre.36 at F:\deleteMe\flutter
    • Framework revision 8735ab1e35 (3 hours ago), 2020-02-06 23:36:59 -0800
    • Engine revision f34bc65bee
    • Dart version 2.8.0 (build 2.8.0-dev.7.0 b3396cbdca)

[X] Android toolchain - develop for Android devices
    X Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/setup/#android-setup for detailed instructions).
      If the Android SDK has been installed to a custom location, set ANDROID_SDK_ROOT to that location.
      You may also want to add it to your PATH environment variable.


[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/setup/#android-setup for detailed instructions).

[!] VS Code (version 1.41.1)
    • VS Code at C:\Users\admin\AppData\Local\Programs\Microsoft VS Code
    X Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[√] Connected device (2 available)
    • Chrome     • chrome     • web-javascript • Google Chrome 79.0.3945.130
    • Web Server • web-server • web-javascript • Flutter Tools

! Doctor found issues in 3 categories.
```

</details>

**Note**: 
 • I have modified the project directory path in both logs for security reasons. But they are fresh template projects as described in the steps to reproduce.
 • `flutter build web`  works properly though.

**Comment by TahaTesser** [comment]
Hi @GAM3RG33K 
I strongly recommend not use Windows 7 for Flutter Web development since most browsers either have ended or ending Windows 7 support but i am keeping this issue open just in case. 
Thank you for your contribution.

**Comment by yjbanov** [comment]
I talked to our TL and our toolchain does not support Windows 7. However, you should be able to build web projects in Windows 10 and run them in browsers on Windows 7.

**Comment by GAM3RG33K** [comment]
@yjbanov Thanks for the reply. I am still a little bit confused. By toolchain do you mean the whole flutter toolchain or just the part that affects the web? My real concern now is, will the whole flutter support be gone for Windows 7 like the web module support?

**Comment by dnishimoto** [comment]
We have windows 7 and the flutter web app will load.  It throws and instance error.  The application will not run on any of the windows 7 browsers: chrome, ie, or firefox

**Comment by GAM3RG33K** [comment]
@dnishimoto Hi, Unfortunately as @yjbanov said, the support for the flutter web development toolchain on Windows 7 is discontinued. I am not sure if the same will be for the flutter app development as well or not. 

However, I recommend switching to a newer Windows version to prevent such issues.

**Comment by dnishimoto** [comment]
https://www.techrepublic.com/article/windows-7-remains-an-albatross-at-many-large-organizations/

Windows 7 support needs to be continued. there are thousands of companies still using windows 7.

Flutter web app works on edge
