### ISSUE TITLE
test/commands.shard/permeable/test_test.dart fails if flutter decides a new version is ready

### ISSUE THREAD

**Issue by jonahwilliams** [flutter/flutter#51366]
The assertion in test_test.dart is looking for a specific timing signature in a regular expression. These needs to be replaced with a simpler regexp for all tests passed to avoid failing when the test take longer due to CI slowness

```
 Expected: match '[0-9]+:[0-9]+ [+]1: All tests passed!'
  Actual: '  ╔════════════════════════════════════════════════════════════════════════════╗'
Full output:
- - - -----8<----- - - -
  ╔════════════════════════════════════════════════════════════════════════════╗
  ║ A new version of Flutter is available!                                     ║
  ║                                                                            ║
  ║ To update to the latest version, run "flutter upgrade".                    ║
  ╚════════════════════════════════════════════════════════════════════════════╝
Shuffling test order with --test-randomize-ordering-seed=0
00:00 +0: loading /tmp/flutter sdk/dev/automated_tests/../../dev/automated_tests/flutter_test/trivial_widget_test.dart                                                                                 
00:01 +0: loading /tmp/flutter sdk/dev/automated_tests/../../dev/automated_tests/flutter_test/trivial_widget_test.dart                                                                                 
00:02 +0: loading /tmp/flutter sdk/dev/automated_tests/../../dev/automated_tests/flutter_test/trivial_widget_test.dart                                                                                 
00:03 +0: loading /tmp/flutter sdk/dev/automated_tests/../../dev/automated_tests/flutter_test/trivial_widget_test.dart                                                                                 
00:03 +0: A trivial widget test                                                                                                                                                                        
00:03 +1: A trivial widget test                                                                                                                                                                        
00:04 +1: A trivial widget test                                                                                                                                                                        
00:04 +1: All tests passed!                                                                                                                                                                            
<<stderr>>
- - - -----8<----- - - -
#0      fail (package:test_api/src/frontend/expect.dart:154:30)
#1      _expect (package:test_api/src/frontend/expect.dart:148:3)
#2      expect (package:test_api/src/frontend/expect.dart:60:3)
#3      _testFile (org-dartlang-app:///test/commands.shard/permeable/test_test.dart:212:5)
<asynchronous suspension>
#4      main.<anonymous closure> (org-dartlang-app:///test/commands.shard/permeable/test_test.dart:27:12)
#5      testUsingContext.<anonymous closure>.<anonymous closure>.<anonymous closure>.<anonymous closure>.<anonymous closure> (org-dartlang-app:///test/src/context.dart:148:42)
#6      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:29)
#7      _rootRun (dart:async/zone.dart:1126:13)
#8      _CustomZone.run (dart:async/zone.dart:1023:19)
#9      _runZoned (dart:async/zone.dart:1518:10)
#10     runZoned (dart:async/zone.dart:1465:12)
#11     AppContext.run (package:flutter_tools/src/base/context.dart:149:18)
#12     testUsingContext.<anonymous closure>.<anonymous closure>.<anonymous closure>.<anonymous closure> (org-dartlang-app:///test/src/context.dart:137:30)
#13     _rootRun (dart:async/zone.dart:1126:13)
#14     _CustomZone.run (dart:async/zone.dart:1023:19)
#15     _runZoned (dart:async/zone.dart:1518:10)
#16     runZoned (dart:async/zone.dart:1502:12)
#17     testUsingContext.<anonymous closure>.<anonymous closure>.<anonymous closure> (org-dartlang-app:///test/src/context.dart:135:18)
#18     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:29)
#19     _rootRun (dart:async/zone.dart:1126:13)
#20     _CustomZone.run (dart:async/zone.dart:1023:19)
#21     _runZoned (dart:async/zone.dart:1518:10)
#22     runZoned (dart:async/zone.dart:1465:12)
#23     AppContext.run (package:flutter_tools/src/base/context.dart:149:18)
#24     testUsingContext.<anonymous closure>.<anonymous closure> (org-dartlang-app:///test/src/context.dart:102:22)
#25     runInContext.runnerWrapper (package:flutter_tools/src/context_runner.dart:70:18)
<asynchronous suspension>
#26     runInContext.runnerWrapper (package:flutter_tools/src/context_runner.dart)
#27     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:29)
#28     _rootRun (dart:async/zone.dart:1126:13)
#29     _CustomZone.run (dart:async/zone.dart:1023:19)
#30     _runZoned (dart:async/zone.dart:1518:10)
#31     runZoned (dart:async/zone.dart:1465:12)
#32     AppContext.run (package:flutter_tools/src/base/context.dart:149:18)
#33     runInContext (package:flutter_tools/src/context_runner.dart:73:24)
#34     testUsingContext.<anonymous closure> (org-dartlang-app:///test/src/context.dart:101:11)
#35     Declarer.test.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:test_api/src/backend/declarer.dart:172:27)
<asynchronous suspension>
#36     Declarer.test.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:test_api/src/backend/declarer.dart)
#37     Invoker.waitForOutstandingCallbacks.<anonymous closure> (package:test_api/src/backend/invoker.dart:246:15)
#38     _rootRun (dart:async/zone.dart:1126:13)
#39     _CustomZone.run (dart:async/zone.dart:1023:19)
#40     _runZoned (dart:async/zone.dart:1518:10)
#41     runZoned (dart:async/zone.dart:1465:12)
#42     Invoker.waitForOutstandingCallbacks (package:test_api/src/backend/invoker.dart:243:5)
#43     Declarer.test.<anonymous closure>.<anonymous closure> (package:test_api/src/backend/declarer.dart:170:33)
#44     _rootRun (dart:async/zone.dart:1126:13)
#45     _CustomZone.run (dart:async/zone.dart:1023:19)
#46     _runZoned (dart:async/zone.dart:1518:10)
#47     runZoned (dart:async/zone.dart:1465:12)
#48     Declarer.test.<anonymous closure> (package:test_api/src/backend/declarer.dart:169:13)
#49     Invoker._onRun.<anonymous closure>.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:test_api/src/backend/invoker.dart:401:25)
#50     new Future.<anonymous closure> (dart:async/future.dart:176:37)
#51     StackZoneSpecification._run (package:stack_trace/src/stack_zone_specification.dart:209:15)
#52     StackZoneSpecification._registerCallback.<anonymous closure> (package:stack_trace/src/stack_zone_specification.dart:119:48)
#53     _rootRun (dart:async/zone.dart:1122:38)
#54     _CustomZone.run (dart:async/zone.dart:1023:19)
#55     _CustomZone.runGuarded (dart:async/zone.dart:925:7)
#56     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:965:23)
#57     StackZoneSpecification._run (package:stack_trace/src/stack_zone_specification.dart:209:15)
#58     StackZoneSpecification._registerCallback.<anonymous closure> (package:stack_trace/src/stack_zone_specification.dart:119:48)
#59     _rootRun (dart:async/zone.dart:1126:13)
#60     _CustomZone.run (dart:async/zone.dart:1023:19)
#61     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:949:23)
#62     Timer._createTimer.<anonymous closure> (dart:async-patch/timer_patch.dart:23:15)
#63     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:398:19)
#64     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:429:5)
#65     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:168:12)
00:34 +280 -1: test/commands.shard/permeable/test_test.dart: flutter test should not have extraneous error messages [E]                                                                                
  
```

**Comment by jonahwilliams** [comment]
Actually, in this case it was timing, it was the version check...

**Comment by dnfield** [comment]
This was probably introduced by #51235 - before that, the test command skipped this check.

**Comment by Piinks** [comment]
Occurred here: https://cirrus-ci.com/task/5910938813464576

**Comment by christopherfujino** [comment]
Should be fixed when https://github.com/flutter/flutter/pull/51507 lands.
