### ISSUE TITLE
[tool_crash] Invalid argument(s): Cannot find executable for null.

### ISSUE THREAD

**Issue by chaiprasit** [flutter/flutter#51387]
## Command
```
flutter emulator --create flutteremu
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
ArgumentError: Invalid argument(s): Cannot find executable for null.
```
#0      _getExecutable (package:process/src/interface/local_process_manager.dart:127:5)
#1      LocalProcessManager.runSync (package:process/src/interface/local_process_manager.dart:94:30)
#2      _DefaultProcessUtils.runSync (package:flutter_tools/src/base/process.dart:417:51)
#3      EmulatorManager._getPreferredAvailableDevice (package:flutter_tools/src/emulator.dart:144:46)
#4      EmulatorManager.createEmulator (package:flutter_tools/src/emulator.dart:82:33)
<asynchronous suspension>
#5      EmulatorsCommand._createEmulator (package:flutter_tools/src/commands/emulators.dart:78:31)
#6      EmulatorsCommand.runCommand (package:flutter_tools/src/commands/emulators.dart:48:13)
#7      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:681:18)
#8      _rootRunUnary (dart:async/zone.dart:1134:38)
#9      _CustomZone.runUnary (dart:async/zone.dart:1031:19)
#10     _FutureListener.handleValue (dart:async/future_impl.dart:140:18)
#11     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:682:45)
#12     Future._propagateToListeners (dart:async/future_impl.dart:711:32)
#13     Future._completeWithValue (dart:async/future_impl.dart:526:5)
#14     Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:556:7)
#15     _rootRun (dart:async/zone.dart:1126:13)
#16     _CustomZone.run (dart:async/zone.dart:1023:19)
#17     _CustomZone.runGuarded (dart:async/zone.dart:925:7)
#18     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:965:23)
```
```
[✓] Flutter (Channel master, v1.15.4-pre.153, on Microsoft Windows [Version
    10.0.18363.657], locale en-US)
    • Flutter version 1.15.4-pre.153 at C:\flutter
    • Framework revision 9b3754d56f (4 hours ago), 2020-02-24 16:42:30 -0800
    • Engine revision f2f8c342be
    • Dart version 2.8.0 (build 2.8.0-dev.9.0 0f141be8bd)

[!] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at C:\Users\TUF\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling
      support)
    • Platform android-29, build-tools 29.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)
    ✗ Android license status unknown.
      Try re-installing or updating your Android SDK Manager.
      See https://developer.android.com/studio/#downloads or visit
      https://flutter.dev/setup/#android-setup for detailed instructions.

[✗] Visual Studio - develop for Windows
    ✗ Visual Studio not installed; this is necessary for Windows development.
      Download at https://visualstudio.microsoft.com/downloads/.
      Please install the "Desktop development with C++" workload, including the
      following components:
        MSBuild
        MSVC v142 - VS 2019 C++ x64/x86 build tools
         - If there are multiple build tool versions available, install the latest
        Windows 10 SDK (10.0.17763.0)

[!] Android Studio (version 3.6)
    • Android Studio at C:\Program Files\Android\Android Studio
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)

[✓] VS Code (version 1.42.1)
    • VS Code at C:\Users\TUF\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.8.1

[✓] Connected device (1 available)
    • Windows • Windows • windows-x64 • Microsoft Windows [Version 10.0.18363.657]

! Doctor found issues in 3 categories.

```

## Flutter Application Metadata
**Version**: null
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null

**Comment by jonahwilliams** [comment]
This might happen if the android SDK is returning null here: https://github.com/flutter/flutter/blob/master/packages/flutter_tools/lib/src/emulator.dart#L139

@chaiprasit what is the output of `flutter doctor -v`

**Comment by dnfield** [comment]
Note the instructions from doctor:

```
    ✗ Android license status unknown.
      Try re-installing or updating your Android SDK Manager.
      See https://developer.android.com/studio/#downloads or visit
      https://flutter.dev/setup/#android-setup for detailed instructions.
```

Please try following the instructions at those links to make sure your Android environment is set up properly.  If you find the tool still crashing please ping this bug for us to re-open.

**Comment by Abdulahadahmadi** [comment]
Why I have this error!

DELL@DESKTOP-0GTJ62F MINGW64 ~/Documents/hello_flutter
$ flutter doctor -v
[√] Flutter (Channel stable, v1.12.13+hotfix.5, on Microsoft Windows [Version 10.0.18362.720], locale en-US)
    • Flutter version 1.12.13+hotfix.5 at C:\Flutter Dev\flutter
    • Framework revision 27321ebbad (5 months ago), 2019-12-10 18:15:01 -0800
    • Engine revision 2994f7e1e6
    • Dart version 2.7.0

[X] Android toolchain - develop for Android devices
    X ANDROID_HOME = C:\Program Files\Android
      but Android SDK not found at this location.

[√] Android Studio (version 3.5)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 44.0.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)

[√] VS Code (version 1.44.2)
    • VS Code at C:\Users\DELL\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.8.1

[!] Connected device
    ! No devices available

! Doctor found issues in 2 categories.
