### ISSUE TITLE
Am Facing an issue on my first sample app "Gradle task assembleDebug failed with exit code 1"

### ISSUE THREAD

**Issue by azad-mohan** [flutter/flutter#51384]
```
C:\src\test\test_app>flutter run -v
[  +30 ms] executing: [C:\src\flutter\] git -c log.showSignature=false log -n 1 --pretty=format:%H
[  +67 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[        ] 0b8abb4724aa590dd0f429683339b1e045a1594d
[        ] executing: [C:\src\flutter\] git describe --match v*.*.* --first-parent --long --tags
[  +45 ms] Exit code 0 from: git describe --match v*.*.* --first-parent --long --tags
[        ] v1.12.13+hotfix.8-0-g0b8abb472
[  +18 ms] executing: [C:\src\flutter\] git rev-parse --abbrev-ref --symbolic @{u}
[  +50 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/stable
[        ] executing: [C:\src\flutter\] git ls-remote --get-url origin
[  +42 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[ +120 ms] executing: [C:\src\flutter\] git rev-parse --abbrev-ref HEAD
[  +55 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] stable
[ +176 ms] executing: C:\src\android\platform-tools\adb.exe devices -l
[  +38 ms] Exit code 0 from: C:\src\android\platform-tools\adb.exe devices -l
[        ] List of devices attached
           emulator-5554          device product:sdk_google_phone_x86 model:Android_SDK_built_for_x86 device:generic_x86 transport_id:1
[  +36 ms] C:\src\android\platform-tools\adb.exe -s emulator-5554 shell getprop
[  +92 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[  +12 ms] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +6 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[ +263 ms] Generating C:\src\test\test_app\android\app\src\main\java\io\flutter\plugins\GeneratedPluginRegistrant.java
[  +47 ms] ro.hardware = ranchu
[  +74 ms] Using hardware rendering with device Android SDK built for x86. If you get graphics artifacts, consider enabling software rendering with "--enable-software-rendering".
[  +40 ms] Launching lib\main.dart on Android SDK built for x86 in debug mode...
[  +34 ms] executing: C:\src\android\platform-tools\adb.exe -s emulator-5554 shell -x logcat -v time -t 1
[  +80 ms] Exit code 0 from: C:\src\android\platform-tools\adb.exe -s emulator-5554 shell -x logcat -v time -t 1
[        ] --------- beginning of main
           02-25 07:49:40.473 I/SQLiteCastStore( 2202): [CastNetworkInfo] saved: 0, skipped: 0, [CastDeviceInfo]: saved 0, skipped 0, Paired Guest Mode DeviceInfo] saved: 0, skipped: 0.
[  +14 ms] executing: C:\src\android\platform-tools\adb.exe version
[   +8 ms] executing: C:\src\android\platform-tools\adb.exe -s emulator-5554 logcat -v time -T 02-25 07:49:40.473
[  +89 ms] Android Debug Bridge version 1.0.41
           Version 29.0.6-6198805
           Installed as C:\src\android\platform-tools\adb.exe
[   +5 ms] executing: C:\src\android\platform-tools\adb.exe start-server
[  +85 ms] Building APK
[  +44 ms] Running Gradle task 'assembleDebug'...
[   +4 ms] gradle.properties already sets `android.enableR8`
[   +9 ms] Using gradle from C:\src\test\test_app\android\gradlew.bat.
[  +24 ms] executing: C:\src\Android Studio\jre\bin\java -version
[ +280 ms] Exit code 0 from: C:\src\Android Studio\jre\bin\java -version
[        ] openjdk version "1.8.0_202-release"
           OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)
           OpenJDK 64-Bit Server VM (build 25.202-b03, mixed mode)
[   +6 ms] executing: [C:\src\test\test_app\android\] C:\src\test\test_app\android\gradlew.bat -Pverbose=true -Ptarget=C:\src\test\test_app\lib\main.dart -Ptrack-widget-creation=true -Pfilesystem-scheme=org-dartlang-root -Ptarget-platform=android-x86 assembleDebug
[+4466 ms] > Task :app:compileFlutterBuildDebug
[   +1 ms] [  +38 ms] executing: [C:\src\flutter\] git -c log.showSignature=false log -n 1 --pretty=format:%H
[   +1 ms] [  +77 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[   +1 ms] [        ] 0b8abb4724aa590dd0f429683339b1e045a1594d
[   +1 ms] [        ] executing: [C:\src\flutter\] git describe --match v*.*.* --first-parent --long --tags
[   +1 ms] [  +48 ms] Exit code 0 from: git describe --match v*.*.* --first-parent --long --tags
[        ] [        ] v1.12.13+hotfix.8-0-g0b8abb472
[   +1 ms] [  +14 ms] executing: [C:\src\flutter\] git rev-parse --abbrev-ref --symbolic @{u}
[   +1 ms] [  +45 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] [        ] origin/stable
[        ] [        ] executing: [C:\src\flutter\] git ls-remote --get-url origin
[        ] [  +38 ms] Exit code 0 from: git ls-remote --get-url origin
[   +1 ms] [        ] https://github.com/flutter/flutter.git
[        ] [  +85 ms] executing: [C:\src\flutter\] git rev-parse --abbrev-ref HEAD
[   +1 ms] [  +41 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] [        ] stable
[   +1 ms] [  +27 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[   +1 ms] [        ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[   +1 ms] [        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[   +1 ms] [        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[   +1 ms] [        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +1 ms] [   +5 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[   +1 ms] [        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[   +1 ms] [        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[   +1 ms] [        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[   +1 ms] [        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[   +1 ms] [        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +12 ms] [ +119 ms] Initializing file store
[   +1 ms] [  +21 ms] Done initializing file store
[+1337 ms] [+1556 ms] Skipping target: kernel_snapshot
[ +100 ms] [  +66 ms] debug_android_application: Starting due to {InvalidatedReason.outputMissing}
[ +200 ms] [ +187 ms] debug_android_application: Complete
[   +1 ms] [  +20 ms] Persisting file store
[   +1 ms] [  +18 ms] Done persisting file store
[   +1 ms] [   +4 ms] build succeeded.
[        ] [  +23 ms] "flutter assemble" took 2,092ms.
[ +105 ms] > Task :app:packLibsflutterBuildDebug UP-TO-DATE
[   +1 ms] > Task :app:preBuild UP-TO-DATE
[   +1 ms] > Task :app:preDebugBuild UP-TO-DATE
[   +2 ms] > Task :app:compileDebugAidl NO-SOURCE
[  +90 ms] > Task :app:checkDebugManifest UP-TO-DATE
[   +1 ms] > Task :app:compileDebugRenderscript NO-SOURCE
[   +2 ms] > Task :app:generateDebugBuildConfig UP-TO-DATE
[   +2 ms] > Task :app:cleanMergeDebugAssets
[  +87 ms] > Task :app:mergeDebugShaders UP-TO-DATE
[   +1 ms] > Task :app:compileDebugShaders UP-TO-DATE
[   +1 ms] > Task :app:generateDebugAssets UP-TO-DATE
[        ] > Task :app:mergeDebugAssets
[ +300 ms] > Task :app:copyFlutterAssetsDebug
[   +3 ms] > Task :app:mainApkListPersistenceDebug UP-TO-DATE
[  +92 ms] > Task :app:generateDebugResValues UP-TO-DATE
[   +2 ms] > Task :app:generateDebugResources UP-TO-DATE
[   +1 ms] > Task :app:mergeDebugResources UP-TO-DATE
[        ] > Task :app:createDebugCompatibleScreenManifests UP-TO-DATE
[  +94 ms] > Task :app:processDebugManifest UP-TO-DATE
[ +300 ms] > Task :app:processDebugResources FAILED
[   +4 ms] FAILURE: Build failed with an exception.
[   +2 ms] * What went wrong:
[        ] Execution failed for task ':app:processDebugResources'.
[        ] > A failure occurred while executing com.android.build.gradle.internal.tasks.Workers$ActionFacade
[        ]    > Android resource linking failed
[   +1 ms]      C:\Users\USER\.gradle\caches\transforms-2\files-2.1\0a271e99b6771ad4a84318244d532fb7\core-1.0.0\res\values\values.xml:57:5-88:25: AAPT: error: resource android:attr/fontVariationSettings not found.
[   +1 ms]      C:\Users\USER\.gradle\caches\transforms-2\files-2.1\0a271e99b6771ad4a84318244d532fb7\core-1.0.0\res\values\values.xml:57:5-88:25: AAPT: error: resource android:attr/ttcIndex not found.
[   +1 ms] * Try:
[        ] Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
[        ] * Get more help at https://help.gradle.org
[        ] BUILD FAILED in 6s
[   +1 ms] 15 actionable tasks: 5 executed, 10 up-to-date
[ +455 ms] Running Gradle task 'assembleDebug'... (completed in 8.0s)
[  +10 ms] "flutter run" took 9,281ms.
Gradle task assembleDebug failed with exit code 1

#0      throwToolExit (package:flutter_tools/src/base/common.dart:28:3)
#1      buildGradleApp (package:flutter_tools/src/android/gradle.dart:431:7)
#2      _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:73:64)
#3      _rootRunUnary (dart:async/zone.dart:1134:38)
#4      _CustomZone.runUnary (dart:async/zone.dart:1031:19)
#5      _FutureListener.handleValue (dart:async/future_impl.dart:139:18)
#6      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:680:45)
#7      Future._propagateToListeners (dart:async/future_impl.dart:709:32)
#8      Future._completeWithValue (dart:async/future_impl.dart:524:5)
#9      Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:554:7)
#10     _rootRun (dart:async/zone.dart:1126:13)
#11     _CustomZone.run (dart:async/zone.dart:1023:19)
#12     _CustomZone.runGuarded (dart:async/zone.dart:925:7)
#13     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:965:23)
#14     _microtaskLoop (dart:async/schedule_microtask.dart:43:21)
#15     _startMicrotaskLoop (dart:async/schedule_microtask.dart:52:5)
#16     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
#17     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:175:5)
```

## Steps to Reproduce

1. Run `flutter create bug`.
2. Update the files as follows: ... 
3. ... 

**Expected results:** 

**Actual results:** 

<details>
  <summary>Logs</summary>

```
```

```
```

```
```

</details>

**Comment by dnfield** [comment]
Your gradle cache appears to have become corrupted.  You can try removing it and trying the command again (e.g. delete `C:\Users\USER\.gradle`).
