### ISSUE TITLE
gclient sync on windows 7

### ISSUE THREAD

**Issue by andy-mccull** [flutter/flutter#51474]
I am having a problem setting up the engine development environment. I am getting the following when executing gclient sync
 
Syncing projects: 100% ( 1/ 1) src/flutter

src/flutter (ERROR)
----------------------------------------
[0:00:00] Started.
----------------------------------------
Traceback (most recent call last):
  File "C:\Users\amccull2\depot_tools\metrics.py", line 267, in print_notice_and_exit
    yield
  File "C:\Users\amccull2\depot_tools\gclient.py", line 6, in <module>
    """Meta checkout dependency manager for Git."""
  File "C:\Users\amccull2\depot_tools\gclient.py", line 3168, in main
    return dispatcher.execute(OptionParser(), argv)
  File "C:\Users\amccull2\depot_tools\subcommand.py", line 252, in execute
    return command(parser, args[1:])
  File "C:\Users\amccull2\depot_tools\gclient.py", line 2725, in CMDsync
    ret = client.RunOnDeps('update', args)
  File "C:\Users\amccull2\depot_tools\gclient.py", line 1763, in RunOnDeps
    patch_refs=patch_refs, target_branches=target_branches)
  File "C:\Users\amccull2\depot_tools\gclient_utils.py", line 906, in flush
    reraise(e[0], e[1], e[2])
  File "C:\Users\amccull2\depot_tools\gclient_utils.py", line 983, in run
    self.item.run(*self.args, **self.kwargs)
  File "C:\Users\amccull2\depot_tools\gclient.py", line 933, in run
    file_list)
  File "C:\Users\amccull2\depot_tools\gclient_scm.py", line 132, in RunCommand
    return getattr(self, command)(options, args, file_list)
  File "C:\Users\amccull2\depot_tools\gclient_scm.py", line 516, in update
    mirror = self._GetMirror(url, options, revision_ref)
  File "C:\Users\amccull2\depot_tools\gclient_scm.py", line 957, in _GetMirror
    if not self.cache_dir:
  File "C:\Users\amccull2\depot_tools\gclient_scm.py", line 218, in cache_dir
    return git_cache.Mirror.GetCachePath()
  File "C:\Users\amccull2\depot_tools\git_cache.py", line 304, in GetCachePath
    ['cache.cachepath']).strip()
  File "C:\Python27\lib\subprocess.py", line 566, in check_output
    process = Popen(stdout=PIPE, *popenargs, **kwargs)
  File "C:\Python27\lib\subprocess.py", line 710, in __init__
    errread, errwrite)
  File "C:\Python27\lib\subprocess.py", line 958, in _execute_child
    startupinfo)
WindowsError: [Error 2] The system cannot find the file specified
The program exited via sys.exit(). Exit status:  1
> c:\users\amccull2\depot_tools\gclient.py(6)<module>()
-> """Meta checkout dependency manager for Git."""
(Pdb)

**Comment by darshankawar** [comment]
@andy-mccull 
Is this still a valid issue using latest Flutter version or has this been resolved ?

**Comment by pedromassangocode** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
