### ISSUE TITLE
Can't get sign in with Google 

### ISSUE THREAD

**Issue by aaronWong00** [flutter/flutter#51541]
```
D/EGL_emulation(20914): eglMakeCurrent: 0xe4748060: ver 2 0 (tinfo 0xd9145fb0)
D/eglCodecCommon(20914): setVertexArrayObject: set vao to 0 (0) 1 0
I/OpenGLRenderer(20914): Davey! duration=1158ms; Flags=1, IntendedVsync=48083836367320, Vsync=48083869700652, OldestInputEvent=9223372036854775807, NewestInputEvent=0, HandleInputStart=48083883689500, AnimationStart=48083883739290, PerformTraversalsStart=48083883763590, DrawStart=48084959298150, SyncQueued=48084960766380, SyncStart=48084962160370, IssueDrawCommandsStart=48084962515300, SwapBuffers=48084976209690, FrameCompleted=48084996475790, DequeueBufferDuration=17378000, QueueBufferDuration=216000, 
I/Choreographer(20914): Skipped 65 frames!  The application may be doing too much work on its main thread.
D/EGL_emulation(20914): eglMakeCurrent: 0xe4749f80: ver 2 0 (tinfo 0xd915e180)
D/eglCodecCommon(20914): setVertexArrayObject: set vao to 0 (0) 1 0
W/ActivityThread(20914): handleWindowVisibility: no activity for token android.os.BinderProxy@67cd5fd
D/EGL_emulation(20914): eglMakeCurrent: 0xe4748060: ver 2 0 (tinfo 0xd9145fb0)
D/EGL_emulation(20914): eglMakeCurrent: 0xe4748060: ver 2 0 (tinfo 0xd9145fb0)
E/flutter (20914): [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: PlatformException(sign_in_failed, com.google.android.gms.common.api.ApiException: 10: , null)
E/flutter (20914): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:569:7)
E/flutter (20914): #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:156:18)
E/flutter (20914): <asynchronous suspension>
E/flutter (20914): #2      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:329:12)
E/flutter (20914): #3      MethodChannel.invokeMapMethod (package:flutter/src/services/platform_channel.dart:356:48)
E/flutter (20914): #4      MethodChannelGoogleSignIn.signIn (package:google_sign_in_platform_interface/src/method_channel_google_sign_in.dart:45:10)
E/flutter (20914): #5      GoogleSignIn._callMethod (package:google_sign_in/google_sign_in.dart:230:42)
E/flutter (20914): <asynchronous suspension>
E/flutter (20914): #6      GoogleSignIn._addMethodCall (package:google_sign_in/google_sign_in.dart:285:18)
E/flutter (20914): #7      GoogleSignIn.signIn (package:google_sign_in/google_sign_in.dart:356:9)
E/flutter (20914): #8      _LoginPageState._signInWithGoogle (package:the_hunter_app/login/login.dart:314:64)
E/flutter (20914): #9      _LoginPageState.build.<anonymous closure> (package:the_hunter_app/login/login.dart:237:27)
E/flutter (20914): #10     _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:705:14)
E/flutter (20914): #11     _InkResponseState.build.<anonymous closure> (package:flutter/src/material/ink_well.dart:788:36)
E/flutter (20914): #12     GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:182:24)
E/flutter (20914): #13     TapGestureRecognizer.handleTapUp (package:flutter/src/gestures/tap.dart:486:11)
E/flutter (20914): #14     BaseTapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:264:5)
E/flutter (20914): #15     BaseTapGestureRecognizer.handlePrimaryPointer (package:flutter/src/gestures/tap.dart:199:7)
E/flutter (20914): #16     PrimaryPointerGestureRecognizer.handleEvent (package:flutter/src/gestures/recognizer.dart:470:9)
E/flutter (20914): #17     PointerRouter._dispatch (package:flutter/src/gestures/pointer_router.dart:76:12)
E/flutter (20914): #18     PointerRouter._dispatchEventToRoutes.<anonymous closure> (package:flutter/src/gestures/pointer_router.dart:117:9)
E/flutter (20914): #19     _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:379:8)
E/flutter (20914): #20     PointerRouter._dispatchEventToRoutes (package:flutter/src/gestures/pointer_router.dart:115:18)
E/flutter (20914): #21     PointerRouter.route (package:flutter/src/gestures/pointer_router.dart:101:7)
E/flutter (20914): #22     GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:218:19)
E/flutter (20914): #23     GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:198:22)
E/flutter (20914): #24     GestureBinding._handlePointerEvent (package:flutter/src/gestures/binding.dart:156:7)
E/flutter (20914): #25     GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:102:7)
E/flutter (20914): #26     GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:86:7)
E/flutter (20914): #27     _rootRunUnary (dart:async/zone.dart:1138:13)
E/flutter (20914): #28     _CustomZone.runUnary (dart:async/zone.dart:1031:19)
E/flutter (20914): #29     _CustomZone.runUnaryGuarded (dart:async/zone.dart:933:7)
E/flutter (20914): #30     _invoke1 (dart:ui/hooks.dart:274:10)
E/flutter (20914): #31     _dispatchPointerDataPacket (dart:ui/hooks.dart:183:5)
E/flutter (20914): 
D/EGL_emulation(20914): eglMakeCurrent: 0xe4748060: ver 2 0 (tinfo 0xd9145fb0)
```

Here the error message coming out when I run the function in my app.
May I know how to fix it?

**Comment by TahaTesser** [comment]
Hi @aaronWong00 
You need to add `SHA` key in your firebase console [Stackoverflow  Solution](https://stackoverflow.com/a/54696963)

**Comment by TahaTesser** [comment]
Hi @aaronWong00 
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore
reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any
more information for us; we will reopen it right away!
Thanks for your contribution.
