### ISSUE TITLE
[tool_crash] RangeError (index): Index out of range: no indices are valid: 0

### ISSUE THREAD

**Issue by kapilrathore42** [flutter/flutter#51565]
## Command
```console
flutter clean
```

## Logs
```bash
IndexError: RangeError (index): Index out of range: no indices are valid: 0
```
```bash
#0      Uint8List.[] (dart:typed_data-patch/typed_data_patch.dart:2209:7)
#1      InputStream.readUint16 (package:archive/src/util/input_stream.dart:190:20)
#2      GZipDecoder._readHeader (package:archive/src/gzip_decoder.dart:89:27)
#3      GZipDecoder.decodeBuffer (package:archive/src/gzip_decoder.dart:26:5)
#4      GZipDecoder.decodeBytes (package:archive/src/gzip_decoder.dart:17:12)
#5      _WindowsUtils.verifyGzip (package:flutter_tools/src/base/os.dart:352:21)
#6      CachedArtifact._downloadArchive.<anonymous closure> (package:flutter_tools/src/cache.dart:595:20)
#7      CachedArtifact._withDownloadFile (package:flutter_tools/src/cache.dart:627:26)
#8      CachedArtifact._downloadArchive (package:flutter_tools/src/cache.dart:594:12)
#9      CachedArtifact._downloadZippedTarball (package:flutter_tools/src/cache.dart:619:12)
#10     GradleWrapper.updateInner (package:flutter_tools/src/cache.dart:1059:12)
#11     CachedArtifact.update (package:flutter_tools/src/cache.dart:550:11)
#12     Cache.updateAll (package:flutter_tools/src/cache.dart:428:24)
#13     FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:656:27)
#14     FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:579:33)
<asynchronous suspension>
#15     FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart)
#16     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:29)
#17     _rootRun (dart:async/zone.dart:1126:13)
#18     _CustomZone.run (dart:async/zone.dart:1023:19)
```
```console
[!] Flutter (Channel master, v1.15.4-pre.169, on Microsoft Windows [Version 10.0.18362.657], locale en-IN)
    • Flutter version 1.15.4-pre.169 at C:\Users\kapil rathore\flutter\flutter
    • Framework revision 492fb6381e (35 hours ago), 2020-02-25 22:29:16 -0500
    • Engine revision 888a62cf22
    • Dart version 2.8.0 (build 2.8.0-dev.10.0 73f6d15665)
    ✗ Downloaded executables cannot execute on host.
      See https://github.com/flutter/flutter/issues/6207 for more information


[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at C:\Users\kapil rathore\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[✓] Android Studio (version 3.5)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 43.0.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)

[✓] VS Code (version 1.42.1)
    • VS Code at C:\Users\kapil rathore\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.8.1

[✓] Connected device (2 available)
    • Chrome     • chrome     • web-javascript • Google Chrome 80.0.3987.122
    • Web Server • web-server • web-javascript • Flutter Tools

! Doctor found issues in 1 category.

```

## Flutter Application Metadata
No pubspec in working directory.

**Comment by iapicca** [comment]
Hi @kapilrathore42 
I see there's an open [issue](https://github.com/flutter/flutter/issues/48014) addressing the case you described.
Please follow up on that issue,
I'm closing the current one as duplicate.
If you disagree please write in the comments
and I will reopen it.
Thank you
