### ISSUE TITLE
flutter build apk suddenly stopped working after upgrading url_launcher

### ISSUE THREAD

**Issue by mhmdanas** [flutter/flutter#51583]
My project suddenly stopped being able to produce an APK after upgrading my dependencies in pubspec.yaml. From what I can understand, the problems stems from `url_launcher_web`. I tried downgrading `url_launcher` to the version I was using before, but it still didn't work. Running `flutter pub cache repair` had no effect.

## Steps to Reproduce

I can't reproduce this with a new project. See the [Logs](#Logs) section for the verbose output of `flutter build apk`.

## Logs

```
[  +26 ms] executing: [/Users/mhmdanas/flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[  +58 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[        ] 0b8abb4724aa590dd0f429683339b1e045a1594d
[        ] executing: [/Users/mhmdanas/flutter/] git describe --match v*.*.* --first-parent --long --tags
[ +161 ms] Exit code 0 from: git describe --match v*.*.* --first-parent --long --tags
[   +4 ms] v1.12.13+hotfix.8-0-g0b8abb472
[  +16 ms] executing: [/Users/mhmdanas/flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[  +10 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/stable
[        ] executing: [/Users/mhmdanas/flutter/] git ls-remote --get-url origin
[  +12 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[  +73 ms] executing: [/Users/mhmdanas/flutter/] git rev-parse --abbrev-ref HEAD
[  +12 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] stable
[   +6 ms] executing: sw_vers -productName
[  +20 ms] Exit code 0 from: sw_vers -productName
[   +1 ms] Mac OS X
[   +1 ms] executing: sw_vers -productVersion
[  +22 ms] Exit code 0 from: sw_vers -productVersion
[        ] 10.15.3
[        ] executing: sw_vers -buildVersion
[  +18 ms] Exit code 0 from: sw_vers -buildVersion
[        ] 19D76
[  +40 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[   +4 ms] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +3 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[ +124 ms] Found plugin package_info at
/Users/mhmdanas/flutter/.pub-cache/hosted/pub.dartlang.org/package_info-0.4.0+14/
[  +20 ms] Found plugin path_provider at
/Users/mhmdanas/flutter/.pub-cache/hosted/pub.dartlang.org/path_provider-1.6.1/
[  +13 ms] Found plugin shared_preferences at
/Users/mhmdanas/flutter/.pub-cache/hosted/pub.dartlang.org/shared_preferences-0.5.6+2/
[   +2 ms] Found plugin shared_preferences_macos at
/Users/mhmdanas/flutter/.pub-cache/hosted/pub.dartlang.org/shared_preferences_macos-0.0.1+6/
[   +4 ms] Found plugin shared_preferences_web at
/Users/mhmdanas/flutter/.pub-cache/hosted/pub.dartlang.org/shared_preferences_web-0.1.2+4/
[  +23 ms] Found plugin url_launcher at /Users/mhmdanas/flutter/.pub-cache/hosted/pub.dartlang.org/url_launcher-5.4.2/
[   +1 ms] Found plugin url_launcher_macos at
/Users/mhmdanas/flutter/.pub-cache/hosted/pub.dartlang.org/url_launcher_macos-0.0.1+4/
[   +4 ms] Found plugin url_launcher_web at
/Users/mhmdanas/flutter/.pub-cache/hosted/pub.dartlang.org/url_launcher_web-0.1.1+1/
[   +4 ms] Found plugin wc_flutter_share at
/Users/mhmdanas/flutter/.pub-cache/hosted/pub.dartlang.org/wc_flutter_share-0.2.0/
[   +3 ms] Found plugin webview_flutter at
/Users/mhmdanas/flutter/.pub-cache/hosted/pub.dartlang.org/webview_flutter-0.3.19+8/
[  +75 ms] Found plugin package_info at
/Users/mhmdanas/flutter/.pub-cache/hosted/pub.dartlang.org/package_info-0.4.0+14/
[   +3 ms] Found plugin path_provider at
/Users/mhmdanas/flutter/.pub-cache/hosted/pub.dartlang.org/path_provider-1.6.1/
[   +4 ms] Found plugin shared_preferences at
/Users/mhmdanas/flutter/.pub-cache/hosted/pub.dartlang.org/shared_preferences-0.5.6+2/
[   +1 ms] Found plugin shared_preferences_macos at
/Users/mhmdanas/flutter/.pub-cache/hosted/pub.dartlang.org/shared_preferences_macos-0.0.1+6/
[   +2 ms] Found plugin shared_preferences_web at
/Users/mhmdanas/flutter/.pub-cache/hosted/pub.dartlang.org/shared_preferences_web-0.1.2+4/
[   +5 ms] Found plugin url_launcher at /Users/mhmdanas/flutter/.pub-cache/hosted/pub.dartlang.org/url_launcher-5.4.2/
[   +1 ms] Found plugin url_launcher_macos at
/Users/mhmdanas/flutter/.pub-cache/hosted/pub.dartlang.org/url_launcher_macos-0.0.1+4/
[   +2 ms] Found plugin url_launcher_web at
/Users/mhmdanas/flutter/.pub-cache/hosted/pub.dartlang.org/url_launcher_web-0.1.1+1/
[   +3 ms] Found plugin wc_flutter_share at
/Users/mhmdanas/flutter/.pub-cache/hosted/pub.dartlang.org/wc_flutter_share-0.2.0/
[   +1 ms] Found plugin webview_flutter at
/Users/mhmdanas/flutter/.pub-cache/hosted/pub.dartlang.org/webview_flutter-0.3.19+8/
[  +52 ms] Generating
/Users/mhmdanas/Desktop/growthcalc/android/app/src/main/java/io/flutter/plugins/GeneratedPluginRegistrant.java
[  +19 ms] executing: /usr/bin/xcodebuild -version
[ +839 ms] Exit code 0 from: /usr/bin/xcodebuild -version
[        ] Xcode 11.3.1
           Build version 11C504
[  +17 ms] You are building a fat APK that includes binaries for android-arm, android-arm64, android-x64.
[        ] If you are deploying the app to the Play Store, it's recommended to use app bundles or split the APK to
reduce the APK
           size.
[        ]     To generate an app bundle, run:
[        ]         flutter build appbundle --target-platform android-arm,android-arm64,android-x64
[        ]         Learn more on: https://developer.android.com/guide/app-bundle
[        ]     To split the APKs per ABI, run:
[        ]         flutter build apk --target-platform android-arm,android-arm64,android-x64 --split-per-abi
[        ]         Learn more on:  https://developer.android.com/studio/build/configure-apk-splits#configure-abi-split
[  +22 ms] Running Gradle task 'assembleRelease'...
[   +1 ms] gradle.properties already sets `android.enableR8`
[   +3 ms] Using gradle from /Users/mhmdanas/Desktop/growthcalc/android/gradlew.
[  +19 ms] executing: [/Users/mhmdanas/Desktop/growthcalc/android/] /Users/mhmdanas/Desktop/growthcalc/android/gradlew
-Pverbose=true -Ptarget=lib/main.dart -Ptrack-widget-creation=true -Pshrink=true
-Ptarget-platform=android-arm,android-arm64,android-x64 assembleRelease
[+2729 ms] > Task :app:compileFlutterBuildRelease UP-TO-DATE
[        ] > Task :app:packLibsflutterBuildRelease UP-TO-DATE
[        ] > Task :app:preBuild UP-TO-DATE
[        ] > Task :app:extractProguardFiles UP-TO-DATE
[        ] > Task :app:preReleaseBuild UP-TO-DATE
[        ] > Task :package_info:preBuild UP-TO-DATE
[        ] > Task :package_info:preReleaseBuild UP-TO-DATE
[        ] > Task :package_info:compileReleaseAidl NO-SOURCE
[        ] > Task :path_provider:preBuild UP-TO-DATE
[        ] > Task :path_provider:preReleaseBuild UP-TO-DATE
[  +71 ms] > Task :path_provider:compileReleaseAidl NO-SOURCE
[   +1 ms] > Task :shared_preferences:preBuild UP-TO-DATE
[        ] > Task :shared_preferences:preReleaseBuild UP-TO-DATE
[        ] > Task :shared_preferences_macos:preBuild UP-TO-DATE
[        ] > Task :shared_preferences_macos:preReleaseBuild UP-TO-DATE
[        ] > Task :shared_preferences_macos:compileReleaseAidl NO-SOURCE
[        ] > Task :shared_preferences_web:preBuild UP-TO-DATE
[        ] > Task :shared_preferences_web:preReleaseBuild UP-TO-DATE
[        ] > Task :shared_preferences_web:compileReleaseAidl NO-SOURCE
[        ] > Task :shared_preferences:compileReleaseAidl NO-SOURCE
[        ] > Task :url_launcher:preBuild UP-TO-DATE
[        ] > Task :url_launcher:preReleaseBuild UP-TO-DATE
[        ] > Task :url_launcher_macos:preBuild UP-TO-DATE
[        ] > Task :url_launcher_macos:preReleaseBuild UP-TO-DATE
[        ] > Task :url_launcher_macos:compileReleaseAidl NO-SOURCE
[        ] > Task :url_launcher_web:preBuild UP-TO-DATE
[        ] > Task :url_launcher_web:preReleaseBuild UP-TO-DATE
[        ] > Task :url_launcher_web:compileReleaseAidl NO-SOURCE
[        ] > Task :url_launcher:compileReleaseAidl NO-SOURCE
[        ] > Task :wc_flutter_share:preBuild UP-TO-DATE
[        ] > Task :wc_flutter_share:preReleaseBuild UP-TO-DATE
[        ] > Task :wc_flutter_share:compileReleaseAidl NO-SOURCE
[        ] > Task :webview_flutter:preBuild UP-TO-DATE
[        ] > Task :webview_flutter:preReleaseBuild UP-TO-DATE
[        ] > Task :webview_flutter:compileReleaseAidl NO-SOURCE
[        ] > Task :app:compileReleaseAidl NO-SOURCE
[        ] > Task :package_info:packageReleaseRenderscript NO-SOURCE
[        ] > Task :path_provider:packageReleaseRenderscript NO-SOURCE
[        ] > Task :shared_preferences:packageReleaseRenderscript NO-SOURCE
[        ] > Task :shared_preferences_macos:packageReleaseRenderscript NO-SOURCE
[        ] > Task :shared_preferences_web:packageReleaseRenderscript NO-SOURCE
[        ] > Task :url_launcher:packageReleaseRenderscript NO-SOURCE
[        ] > Task :url_launcher_macos:packageReleaseRenderscript NO-SOURCE
[        ] > Task :url_launcher_web:packageReleaseRenderscript NO-SOURCE
[        ] > Task :wc_flutter_share:packageReleaseRenderscript NO-SOURCE
[        ] > Task :webview_flutter:packageReleaseRenderscript NO-SOURCE
[        ] > Task :app:compileReleaseRenderscript NO-SOURCE
[        ] > Task :app:checkReleaseManifest UP-TO-DATE
[        ] > Task :app:generateReleaseBuildConfig UP-TO-DATE
[  +91 ms] > Task :app:cleanMergeReleaseAssets
[        ] > Task :app:mergeReleaseShaders UP-TO-DATE
[        ] > Task :app:compileReleaseShaders UP-TO-DATE
[        ] > Task :app:generateReleaseAssets UP-TO-DATE
[        ] > Task :package_info:mergeReleaseShaders UP-TO-DATE
[        ] > Task :package_info:compileReleaseShaders UP-TO-DATE
[        ] > Task :package_info:generateReleaseAssets UP-TO-DATE
[        ] > Task :package_info:packageReleaseAssets UP-TO-DATE
[        ] > Task :path_provider:mergeReleaseShaders UP-TO-DATE
[        ] > Task :path_provider:compileReleaseShaders UP-TO-DATE
[        ] > Task :path_provider:generateReleaseAssets UP-TO-DATE
[        ] > Task :path_provider:packageReleaseAssets UP-TO-DATE
[        ] > Task :shared_preferences:mergeReleaseShaders UP-TO-DATE
[        ] > Task :shared_preferences:compileReleaseShaders UP-TO-DATE
[        ] > Task :shared_preferences:generateReleaseAssets UP-TO-DATE
[        ] > Task :shared_preferences:packageReleaseAssets UP-TO-DATE
[        ] > Task :shared_preferences_macos:mergeReleaseShaders UP-TO-DATE
[        ] > Task :shared_preferences_macos:compileReleaseShaders UP-TO-DATE
[        ] > Task :shared_preferences_macos:generateReleaseAssets UP-TO-DATE
[        ] > Task :shared_preferences_macos:packageReleaseAssets UP-TO-DATE
[        ] > Task :shared_preferences_web:mergeReleaseShaders UP-TO-DATE
[        ] > Task :shared_preferences_web:compileReleaseShaders UP-TO-DATE
[        ] > Task :shared_preferences_web:generateReleaseAssets UP-TO-DATE
[        ] > Task :shared_preferences_web:packageReleaseAssets UP-TO-DATE
[        ] > Task :url_launcher:mergeReleaseShaders UP-TO-DATE
[        ] > Task :url_launcher:compileReleaseShaders UP-TO-DATE
[        ] > Task :url_launcher:generateReleaseAssets UP-TO-DATE
[        ] > Task :url_launcher:packageReleaseAssets UP-TO-DATE
[        ] > Task :url_launcher_macos:mergeReleaseShaders UP-TO-DATE
[        ] > Task :url_launcher_macos:compileReleaseShaders UP-TO-DATE
[        ] > Task :url_launcher_macos:generateReleaseAssets UP-TO-DATE
[        ] > Task :url_launcher_macos:packageReleaseAssets UP-TO-DATE
[        ] > Task :url_launcher_web:mergeReleaseShaders UP-TO-DATE
[        ] > Task :url_launcher_web:compileReleaseShaders UP-TO-DATE
[        ] > Task :url_launcher_web:generateReleaseAssets UP-TO-DATE
[        ] > Task :url_launcher_web:packageReleaseAssets UP-TO-DATE
[        ] > Task :wc_flutter_share:mergeReleaseShaders UP-TO-DATE
[        ] > Task :wc_flutter_share:compileReleaseShaders UP-TO-DATE
[        ] > Task :wc_flutter_share:generateReleaseAssets UP-TO-DATE
[        ] > Task :wc_flutter_share:packageReleaseAssets UP-TO-DATE
[        ] > Task :webview_flutter:mergeReleaseShaders UP-TO-DATE
[        ] > Task :webview_flutter:compileReleaseShaders UP-TO-DATE
[        ] > Task :webview_flutter:generateReleaseAssets UP-TO-DATE
[        ] > Task :webview_flutter:packageReleaseAssets UP-TO-DATE
[        ] > Task :app:mergeReleaseAssets
[  +92 ms] > Task :app:copyFlutterAssetsRelease
[        ] > Task :app:mainApkListPersistenceRelease UP-TO-DATE
[        ] > Task :app:generateReleaseResValues UP-TO-DATE
[        ] > Task :app:generateReleaseResources UP-TO-DATE
[        ] > Task :package_info:compileReleaseRenderscript NO-SOURCE
[        ] > Task :package_info:generateReleaseResValues UP-TO-DATE
[        ] > Task :package_info:generateReleaseResources UP-TO-DATE
[        ] > Task :package_info:packageReleaseResources UP-TO-DATE
[        ] > Task :path_provider:generateReleaseResValues UP-TO-DATE
[        ] > Task :shared_preferences:generateReleaseResValues UP-TO-DATE
[        ] > Task :path_provider:compileReleaseRenderscript NO-SOURCE
[        ] > Task :path_provider:generateReleaseResources UP-TO-DATE
[        ] > Task :path_provider:packageReleaseResources UP-TO-DATE
[        ] > Task :shared_preferences:compileReleaseRenderscript NO-SOURCE
[        ] > Task :shared_preferences:generateReleaseResources UP-TO-DATE
[  +97 ms] > Task :shared_preferences:packageReleaseResources UP-TO-DATE
[        ] > Task :shared_preferences_macos:generateReleaseResValues UP-TO-DATE
[        ] > Task :shared_preferences_macos:compileReleaseRenderscript NO-SOURCE
[        ] > Task :shared_preferences_macos:generateReleaseResources UP-TO-DATE
[        ] > Task :shared_preferences_macos:packageReleaseResources UP-TO-DATE
[        ] > Task :shared_preferences_web:compileReleaseRenderscript NO-SOURCE
[        ] > Task :shared_preferences_web:generateReleaseResValues UP-TO-DATE
[        ] > Task :shared_preferences_web:generateReleaseResources UP-TO-DATE
[        ] > Task :shared_preferences_web:packageReleaseResources UP-TO-DATE
[        ] > Task :url_launcher:compileReleaseRenderscript NO-SOURCE
[        ] > Task :url_launcher:generateReleaseResValues UP-TO-DATE
[        ] > Task :url_launcher:generateReleaseResources UP-TO-DATE
[        ] > Task :url_launcher:packageReleaseResources UP-TO-DATE
[        ] > Task :url_launcher_macos:compileReleaseRenderscript NO-SOURCE
[        ] > Task :url_launcher_macos:generateReleaseResValues UP-TO-DATE
[        ] > Task :url_launcher_macos:generateReleaseResources UP-TO-DATE
[        ] > Task :url_launcher_macos:packageReleaseResources UP-TO-DATE
[        ] > Task :url_launcher_web:generateReleaseResValues UP-TO-DATE
[        ] > Task :url_launcher_web:compileReleaseRenderscript NO-SOURCE
[        ] > Task :url_launcher_web:generateReleaseResources UP-TO-DATE
[        ] > Task :url_launcher_web:packageReleaseResources UP-TO-DATE
[        ] > Task :wc_flutter_share:compileReleaseRenderscript NO-SOURCE
[        ] > Task :wc_flutter_share:generateReleaseResValues UP-TO-DATE
[        ] > Task :wc_flutter_share:generateReleaseResources UP-TO-DATE
[        ] > Task :wc_flutter_share:packageReleaseResources UP-TO-DATE
[        ] > Task :webview_flutter:generateReleaseResValues UP-TO-DATE
[        ] > Task :webview_flutter:compileReleaseRenderscript NO-SOURCE
[        ] > Task :webview_flutter:generateReleaseResources UP-TO-DATE
[        ] > Task :webview_flutter:packageReleaseResources UP-TO-DATE
[        ] > Task :app:mergeReleaseResources UP-TO-DATE
[  +92 ms] > Task :app:createReleaseCompatibleScreenManifests UP-TO-DATE
[        ] > Task :package_info:checkReleaseManifest UP-TO-DATE
[        ] > Task :package_info:processReleaseManifest UP-TO-DATE
[        ] > Task :path_provider:checkReleaseManifest UP-TO-DATE
[        ] > Task :path_provider:processReleaseManifest UP-TO-DATE
[        ] > Task :shared_preferences:checkReleaseManifest UP-TO-DATE
[        ] > Task :shared_preferences:processReleaseManifest UP-TO-DATE
[        ] > Task :shared_preferences_macos:checkReleaseManifest UP-TO-DATE
[        ] > Task :shared_preferences_macos:processReleaseManifest UP-TO-DATE
[        ] > Task :shared_preferences_web:checkReleaseManifest UP-TO-DATE
[        ] > Task :shared_preferences_web:processReleaseManifest UP-TO-DATE
[        ] > Task :url_launcher:checkReleaseManifest UP-TO-DATE
[        ] > Task :url_launcher:processReleaseManifest UP-TO-DATE
[        ] > Task :url_launcher_macos:checkReleaseManifest UP-TO-DATE
[        ] > Task :url_launcher_macos:processReleaseManifest UP-TO-DATE
[        ] > Task :url_launcher_web:checkReleaseManifest UP-TO-DATE
[        ] > Task :url_launcher_web:processReleaseManifest UP-TO-DATE
[        ] > Task :wc_flutter_share:checkReleaseManifest UP-TO-DATE
[  +16 ms] > Task :wc_flutter_share:processReleaseManifest UP-TO-DATE
[        ] > Task :webview_flutter:checkReleaseManifest UP-TO-DATE
[        ] > Task :webview_flutter:processReleaseManifest UP-TO-DATE
[        ] > Task :app:processReleaseManifest UP-TO-DATE
[        ] > Task :package_info:parseReleaseLibraryResources UP-TO-DATE
[        ] > Task :package_info:generateReleaseRFile UP-TO-DATE
[        ] > Task :path_provider:parseReleaseLibraryResources UP-TO-DATE
[        ] > Task :shared_preferences:parseReleaseLibraryResources UP-TO-DATE
[        ] > Task :shared_preferences_macos:parseReleaseLibraryResources UP-TO-DATE
[        ] > Task :path_provider:generateReleaseRFile UP-TO-DATE
[        ] > Task :shared_preferences_macos:generateReleaseRFile UP-TO-DATE
[        ] > Task :shared_preferences_web:parseReleaseLibraryResources UP-TO-DATE
[        ] > Task :url_launcher:parseReleaseLibraryResources UP-TO-DATE
[        ] > Task :shared_preferences_web:generateReleaseRFile UP-TO-DATE
[        ] > Task :shared_preferences:generateReleaseRFile UP-TO-DATE
[        ] > Task :url_launcher_macos:parseReleaseLibraryResources UP-TO-DATE
[        ] > Task :url_launcher_macos:generateReleaseRFile UP-TO-DATE
[        ] > Task :url_launcher_web:parseReleaseLibraryResources UP-TO-DATE
[        ] > Task :url_launcher_web:generateReleaseRFile UP-TO-DATE
[        ] > Task :url_launcher:generateReleaseRFile UP-TO-DATE
[        ] > Task :wc_flutter_share:parseReleaseLibraryResources UP-TO-DATE
[        ] > Task :wc_flutter_share:generateReleaseRFile UP-TO-DATE
[  +79 ms] > Task :webview_flutter:parseReleaseLibraryResources UP-TO-DATE
[        ] > Task :webview_flutter:generateReleaseRFile UP-TO-DATE
[        ] > Task :app:processReleaseResources UP-TO-DATE
[        ] > Task :package_info:generateReleaseBuildConfig UP-TO-DATE
[        ] > Task :package_info:javaPreCompileRelease UP-TO-DATE
[        ] > Task :package_info:compileReleaseJavaWithJavac UP-TO-DATE
[        ] > Task :package_info:bundleLibCompileRelease UP-TO-DATE
[        ] > Task :path_provider:generateReleaseBuildConfig UP-TO-DATE
[        ] > Task :path_provider:javaPreCompileRelease UP-TO-DATE
[        ] > Task :path_provider:compileReleaseJavaWithJavac UP-TO-DATE
[        ] > Task :path_provider:bundleLibCompileRelease UP-TO-DATE
[        ] > Task :shared_preferences:generateReleaseBuildConfig UP-TO-DATE
[        ] > Task :shared_preferences_macos:generateReleaseBuildConfig UP-TO-DATE
[        ] > Task :shared_preferences_macos:javaPreCompileRelease UP-TO-DATE
[        ] > Task :shared_preferences_macos:compileReleaseJavaWithJavac UP-TO-DATE
[        ] > Task :shared_preferences_macos:bundleLibCompileRelease UP-TO-DATE
[        ] > Task :shared_preferences_web:generateReleaseBuildConfig UP-TO-DATE
[        ] > Task :url_launcher:generateReleaseBuildConfig UP-TO-DATE
[  +17 ms] > Task :url_launcher_macos:generateReleaseBuildConfig UP-TO-DATE
[        ] > Task :url_launcher_web:generateReleaseBuildConfig UP-TO-DATE
[        ] > Task :shared_preferences_web:javaPreCompileRelease UP-TO-DATE
[        ] > Task :shared_preferences_web:compileReleaseJavaWithJavac UP-TO-DATE
[        ] > Task :shared_preferences_web:bundleLibCompileRelease UP-TO-DATE
[        ] > Task :shared_preferences:javaPreCompileRelease UP-TO-DATE
[        ] > Task :shared_preferences:compileReleaseJavaWithJavac UP-TO-DATE
[        ] > Task :shared_preferences:bundleLibCompileRelease UP-TO-DATE
[        ] > Task :url_launcher_macos:javaPreCompileRelease UP-TO-DATE
[        ] > Task :url_launcher_macos:compileReleaseJavaWithJavac UP-TO-DATE
[        ] > Task :url_launcher_macos:bundleLibCompileRelease UP-TO-DATE
[        ] > Task :url_launcher_web:javaPreCompileRelease UP-TO-DATE
[  +76 ms] > Task :url_launcher_web:compileReleaseJavaWithJavac FAILED
[   +1 ms] FAILURE: Build failed with an exception.
[   +1 ms] * What went wrong:
[        ] Execution failed for task ':url_launcher_web:compileReleaseJavaWithJavac'.
[        ] > Unable to find source java class:
'/Users/mhmdanas/flutter/.pub-cache/hosted/pub.dartlang.org/url_launcher_web-0.1.0+1/android/src/main/java/io/flutter/u
rl_launcher_web/UrlLauncherWebPlugin.java' because it does not belong to any of the source dirs:
'[/Users/mhmdanas/flutter/.pub-cache/hosted/pub.dartlang.org/url_launcher_web-0.1.1+1/android/src/main/java,
/Users/mhmdanas/flutter/.pub-cache/hosted/pub.dartlang.org/url_launcher_web-0.1.1+1/android/src/release/java,
/Users/mhmdanas/Desktop/growthcalc/build/url_launcher_web/generated/source/buildConfig/release,
/Users/mhmdanas/Desktop/growthcalc/build/url_launcher_web/generated/aidl_source_output_dir/release/compileReleaseAidl/o
ut,
/Users/mhmdanas/Desktop/growthcalc/build/url_launcher_web/generated/renderscript_source_output_dir/release/compileRelea
seRenderscript/out]'
[   +2 ms] * Try:
[        ] Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log
output. Run with --scan to get full insights.
[        ] * Get more help at https://help.gradle.org
[        ] BUILD FAILED in 3s
[        ] 134 actionable tasks: 4 executed, 130 up-to-date
[ +400 ms] Running Gradle task 'assembleRelease'... (completed in 3.8s)
[   +8 ms] "flutter apk" took 5,237ms.
Gradle task assembleRelease failed with exit code 1

#0      throwToolExit (package:flutter_tools/src/base/common.dart:28:3)
#1      buildGradleApp (package:flutter_tools/src/android/gradle.dart:387:7)
<asynchronous suspension>
#2      _AndroidBuilderImpl.buildApk (package:flutter_tools/src/android/android_builder.dart:97:13)
#3      BuildApkCommand.runCommand (package:flutter_tools/src/commands/build_apk.dart:106:26)
#4      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:615:18)
<asynchronous suspension>
#5      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:515:33)
<asynchronous suspension>
#6      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:146:29)
#7      _rootRun (dart:async/zone.dart:1126:13)
#8      _CustomZone.run (dart:async/zone.dart:1023:19)
#9      _runZoned (dart:async/zone.dart:1518:10)
#10     runZoned (dart:async/zone.dart:1465:12)
#11     AppContext.run (package:flutter_tools/src/base/context.dart:145:18)
#12     FlutterCommand.run (package:flutter_tools/src/runner/flutter_command.dart:505:20)
#13     CommandRunner.runCommand (package:args/command_runner.dart:197:27)
#14     FlutterCommandRunner.runCommand.<anonymous closure>
(package:flutter_tools/src/runner/flutter_command_runner.dart:413:21)
<asynchronous suspension>
#15     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:146:29)
#16     _rootRun (dart:async/zone.dart:1126:13)
#17     _CustomZone.run (dart:async/zone.dart:1023:19)
#18     _runZoned (dart:async/zone.dart:1518:10)
#19     runZoned (dart:async/zone.dart:1465:12)
#20     AppContext.run (package:flutter_tools/src/base/context.dart:145:18)
#21     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:364:19)
#22     CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:112:25)
#23     new Future.sync (dart:async/future.dart:224:31)
#24     CommandRunner.run (package:args/command_runner.dart:112:14)
#25     FlutterCommandRunner.run (package:flutter_tools/src/runner/flutter_command_runner.dart:250:18)
#26     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:63:22)
#27     _rootRun (dart:async/zone.dart:1126:13)
#28     _CustomZone.run (dart:async/zone.dart:1023:19)
#29     _runZoned (dart:async/zone.dart:1518:10)
#30     runZoned (dart:async/zone.dart:1502:12)
#31     run.<anonymous closure> (package:flutter_tools/runner.dart:61:18)
<asynchronous suspension>
#32     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:146:29)
#33     _rootRun (dart:async/zone.dart:1126:13)
#34     _CustomZone.run (dart:async/zone.dart:1023:19)
#35     _runZoned (dart:async/zone.dart:1518:10)
#36     runZoned (dart:async/zone.dart:1465:12)
#37     AppContext.run (package:flutter_tools/src/base/context.dart:145:18)
#38     runInContext (package:flutter_tools/src/context_runner.dart:64:24)
#39     run (package:flutter_tools/runner.dart:50:10)
#40     main (package:flutter_tools/executable.dart:65:9)
#41     main (file:///Users/mhmdanas/flutter/packages/flutter_tools/bin/flutter_tools.dart:8:3)
#42     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:305:32)
#43     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:174:12)
```

```
[✓] Flutter (Channel stable, v1.12.13+hotfix.8, on Mac OS X 10.15.3 19D76, locale en-SA)
    • Flutter version 1.12.13+hotfix.8 at /Users/mhmdanas/flutter
    • Framework revision 0b8abb4724 (2 weeks ago), 2020-02-11 11:44:36 -0800
    • Engine revision e1e6ced81d
    • Dart version 2.7.0


[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.0)
    • Android SDK at /Users/mhmdanas/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.0
    • Java binary at: /Library/Java/JavaVirtualMachines/adoptopenjdk-8.jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (AdoptOpenJDK)(build 1.8.0_232-b09)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.3.1, Build version 11C504
    • CocoaPods version 1.8.4

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/setup/#android-setup for detailed instructions).

[✓] IntelliJ IDEA Community Edition (version 2019.3.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 42.1.4
    • Dart plugin version 193.5731

[!] Connected device
    ! No devices available

! Doctor found issues in 2 categories.
```

**Comment by mhmdanas** [comment]
Strangely, switching to another branch, running `flutter pub get`, and switching back to the master branch fixed this issue. Should I keep this up?

**Comment by TahaTesser** [comment]
Hi @mhmdanas 
If you're facing this issue on `stable` branch
please execute `flutter pub cache repair` and then `flutter clean` and then `flutter build apk --verbose`
Thank you

**Comment by mhmdanas** [comment]
As I stated in my previous comment, this issue has already been fixed. I'll close this issue then.
