### ISSUE TITLE
FlutterActivity transparent mode throw UnsupportedOperationException  

### ISSUE THREAD

**Issue by hyuntae0117** [flutter/flutter#51626]
.backgroundMode(transparent) throw UnsupportedOperationException

```
var intent = FlutterActivity
                    .withNewEngine()
                    .backgroundMode(FlutterActivityLaunchConfigs.BackgroundMode.transparent)
                    .build(context!!)
```

```
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.freewheelin.pulley.debug/io.flutter.embedding.android.FlutterActivity}: java.lang.UnsupportedOperationException: TextureView doesn't support displaying a background drawable
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2974)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3059)
        at android.app.ActivityThread.-wrap11(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1724)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:7000)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:441)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1408)
     Caused by: java.lang.UnsupportedOperationException: TextureView doesn't support displaying a background drawable
        at android.view.TextureView.setBackgroundDrawable(TextureView.java:316)
        at android.view.View.setBackground(View.java:21731)
        at android.view.View.<init>(View.java:5591)
        at android.view.View.<init>(View.java:5017)
        at android.view.View.<init>(View.java:4996)
        at android.view.TextureView.<init>(TextureView.java:146)
        at io.flutter.embedding.android.FlutterTextureView.<init>(FlutterTextureView.java:101)
        at io.flutter.embedding.android.FlutterTextureView.<init>(FlutterTextureView.java:94)
        at io.flutter.embedding.android.FlutterView.init(FlutterView.java:214)
        at io.flutter.embedding.android.FlutterView.<init>(FlutterView.java:199)
        at io.flutter.embedding.android.FlutterView.<init>(FlutterView.java:179)
        at io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.onCreateView(FlutterActivityAndFragmentDelegate.java:245)
        at io.flutter.embedding.android.FlutterActivity.createFlutterView(FlutterActivity.java:532)
        at io.flutter.embedding.android.FlutterActivity.onCreate(FlutterActivity.java:425)
        at android.app.Activity.performCreate(Activity.java:7258)
        at android.app.Activity.performCreate(Activity.java:7249)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1222)
```

```
[✓] Flutter (Channel beta, v1.14.6, on Mac OS X 10.14.6 18G103, locale ko-KR)
    • Flutter version 1.14.6 at /Users/ht/project/flutter
    • Framework revision fabeb2a16f (4 weeks ago), 2020-01-28 07:56:51 -0800
    • Engine revision c4229bfbba
    • Dart version 2.8.0 (build 2.8.0-dev.5.0 fc3af737c7)

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/ht/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling
      support)
    • Platform android-29, build-tools 29.0.3
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.3.1, Build version 11C504
    • CocoaPods version 1.8.4

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 43.0.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build
      1.8.0_202-release-1483-b49-5587405)

[!] IntelliJ IDEA Ultimate Edition (version 2019.3.3)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.dev/intellij-setup/#installing-the-plugins

[!] Connected device
    ! No devices available

```

**Comment by TahaTesser** [comment]
Hi @hyuntae0117 
Are you still experiencing this issue?
Thank you

**Comment by hyuntae0117** [comment]
Yes i am
Please help me

-----Original Message-----

**Comment by TahaTesser** [comment]
Hi @hyuntae0117 
Please refer to this [comment](https://github.com/flutter/flutter/issues/45747#issuecomment-567206363) for possible solution

Doc: [Step 2: Start FlutterActivity with transparency](https://flutter.dev/docs/development/add-to-app/android/add-flutter-screen#step-2-start-flutteractivity-with-transparency)

"FlutterActivityLaunchConfigs is not public" that's probably the reason you can't access this 
Related to [45747](https://github.com/flutter/flutter/issues/45747)

**Comment by hyuntae0117** [comment]
Thank you!
But I already read it!
I could not find FlutterActivity.BackgroundMode.transparent,
so I used FlutterActivityLaunchConfigs.BackgroundMode.transparent

Is there something missing?

**Comment by hyuntae0117** [comment]
any changes..?

**Comment by lts1610** [comment]
I found that `renderSurface` is `null` in this constructor.
```dart
  private FlutterView(
      @NonNull Context context,
      @Nullable AttributeSet attrs,
      @NonNull FlutterTextureView flutterTextureView) {
    super(context, attrs);

    this.flutterTextureView = flutterTextureView;
    this.renderSurface = flutterSurfaceView;

    init();
  }```

   `this.renderSurface = flutterSurfaceView;` should be `    this.renderSurface = flutterTextureView;`

**Comment by lts1610** [comment]
@hyuntae0117 : You can switch to Stable channel, `intent.putExtra("background_mode","transparent"); activity.startActivity(intent)` will work fine.

But I have another trouble: 
- Transparent Mode: If you call showModalBottomSheet that has a child is TextField, the keyboard will overlaps ModalBottomSheet.
- Opaque Mode: work fine.

**Comment by hyuntae0117** [comment]
@lts1610 Thank you!
I will check it later

**Comment by AndrewCPU** [comment]
Is there any way to make a flutter application transparent (aka see the background through the application) without using Flutter Fragments? @lts1610

**Comment by shashank090789** [comment]
any fix found for it?

**Comment by jonahwilliams** [comment]
This issue is not actionable as there was no repro provided.
