### ISSUE TITLE
[ios]  Packages are not supported when using legacy build locations, but the current project has them enabled.

### ISSUE THREAD

**Issue by QOFOL** [flutter/flutter#51632]
## Command
  ```console
  flutter build ios
  ```

  ## Logs
 ```bash
 ProcessException: ProcessException: Process exited abnormally:
2020-02-28 17:11:39.825 xcodebuild[94234:480215]  DTDeviceKit: deviceType from 00008030-0001781C21E0802E was NULL
2020-02-28 17:11:39.961 xcodebuild[94234:480215]  DTDeviceKit: deviceType from 00008030-0001781C21E0802E was NULL
xcodebuild: error: Could not resolve package dependencies:
  Packages are not supported when using legacy build locations, but the current project has them enabled.
  Command: /usr/bin/xcodebuild -list
```
```bash
  #0      RunResult.throwException (package:flutter_tools/src/base/process.dart:141:5)
#1      _DefaultProcessUtils.run (package:flutter_tools/src/base/process.dart:275:19)
<asynchronous suspension>
#2      XcodeProjectInterpreter.getInfo (package:flutter_tools/src/ios/xcodeproj.dart:342:49)
#3      buildXcodeProject (package:flutter_tools/src/ios/mac.dart:281:70)
#4      BuildIOSCommand.runCommand (package:flutter_tools/src/commands/build_ios.dart:79:43)
<asynchronous suspension>
#5      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:626:18)
#6      _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:75:64)
#7      _rootRunUnary (dart:async/zone.dart:1134:38)
#8      _CustomZone.runUnary (dart:async/zone.dart:1031:19)
#9      _FutureListener.handleValue (dart:async/future_impl.dart:140:18)
#10     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:682:45)
#11     Future._propagateToListeners (dart:async/future_impl.dart:711:32)
#12     Future._completeWithValue (dart:async/future_impl.dart:526:5)
#13     Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:556:7)
#14     _rootRun (dart:async/zone.dart:1126:13)
#15     _CustomZone.run (dart:async/zone.dart:1023:19)
#16     _CustomZone.runGuarded (dart:async/zone.dart:925:7)
#17     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:965:23)
  ```

  ```console
  [✓] Flutter (Channel master, v1.13.6-pre.40, on Mac OS X 10.14.6 18G103, locale
    en-US)
    • Flutter version 1.13.6-pre.40 at /Users/Qofol/Qlib/flutter
    • Framework revision 20105bc7fd (9 weeks ago), 2019-12-29 15:19:41 +0300
    • Engine revision bdc9708d23
    • Dart version 2.8.0 (build 2.8.0-dev.0.0 c547f5d933)

[!] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/Qofol/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling
      support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at:
      /Library/Java/JavaVirtualMachines/jdk-12.0.2.jdk/Contents/Home/bin/java
    • Java version Java(TM) SE Runtime Environment (build 12.0.2+10)
    ✗ Android license status unknown.
      Try re-installing or updating your Android SDK Manager.
      See https://developer.android.com/studio/#downloads or visit
      https://flutter.dev/setup/#android-setup for detailed instructions.

[!] Xcode - develop for iOS and macOS (Xcode 11.2.1)
    • Xcode at /Volumes/MINI64GB/Applications/Xcode.app/Contents/Developer
    • Xcode 11.2.1, Build version 11B500
    ✗ CocoaPods not installed.
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin
        code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To install:
        sudo gem install cocoapods

[!] Android Studio (not installed)
    • Android Studio not found; download from
      https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/setup/#android-setup for detailed
      instructions).

[✓] Connected device (1 available)
    • Qofol’s iPhone • 00008030-0001781C21E0802E • ios • iOS 13.3.1

! Doctor found issues in 3 categories.

 ```

  ## Flutter Application Metadata
 ```console
 **Version**: 1.0.1+17
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
```
### Plugins
```yaml
apple_sign_in
audioplayers
barcode_scan
blue_thermal_printer
cloud_firestore
connectivity
device_info
firebase_auth
firebase_core
firebase_database
firebase_messaging
firebase_storage
flutter_bluetooth_serial
flutter_facebook_login
flutter_local_notifications
flutter_secure_storage
google_maps_flutter
google_sign_in
image_cropper
image_picker
imei_plugin
local_auth
location
path_provider
permission_handler
printing
shared_preferences
sqflite
url_launcher
url_launcher_macos
url_launcher_web
```

**Comment by iapicca** [comment]
Hi @QOFOL 
your flutter version master  1.13.6 is obsolete, 
the closest most recent version is beta v1.14.6
I'd recommend you to run
`flutter channel beta`
`flutter upgrade`
and fix the error in your doctor 
following the info provided in the logs you provided
```console
 ✗ CocoaPods not installed.
      CocoaPods is used to retrieve the iOS and macOS platform side's plugin
      code that responds to your plugin usage on the Dart side.
      Without CocoaPods, plugins will not work on iOS or macOS.
      For more info, see https://flutter.dev/platform-plugins
    To install:
      sudo gem install cocoapods
```
if the issue persists 
please provide your `flutter build ios --verbose`
together with your **updated** `flutter doctor -v` 
and your `pubspec.yaml`
Thank you

**Comment by iapicca** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact descriptions what happens, logs and the output of 'flutter doctor -v'  please.
All system setups can be slightly different so it's always better to open new issues and reference related issues.
