### ISSUE TITLE
_mapController.showMarkerInfoWindow doesn't update fast enough

### ISSUE THREAD

**Issue by jamieownsu** [flutter/flutter#51717]
A stated. Add a marker to your markers list for your GoogleMap, then try to show that InfoWindow, it will give you a null ref as the marker is not actually in the controllers list yet, for whatever reason. It eventually does show up in there but I'm not sure what the delay is.

**Comment by iapicca** [comment]
Hi @jamieownsu 
are you experiencing the issue in `debug` or `release` mode (or both)?

Could you please provide your `flutter doctor -v` , 
your `flutter run --verbose` ( or  `flutter run --release --verbose`)
and a reproducible minimal code sample.
Thank you

**Comment by jamieownsu** [comment]
> 
> 
> Hi @jamieownsu
> are you experiencing the issue in `debug` or `release` mode (or both)?
> 
> Could you please provide your `flutter doctor -v` ,
> your `flutter run --verbose` ( or `flutter run --release --verbose`)
> and a reproducible minimal code sample.
> Thank you

Just in debug.
`final Map<String, Marker> _markers = Map();
Marker marker = Marker(
        markerId: MarkerId(stop.stopId.toString()),
        position: stop.coordinates,
        infoWindow: InfoWindow(
            title: stop.stopName,
            snippet: 'Stop # ${stop.stopNumber}',
            onTap: () => _fetchSchedules(stop.stopId)),
        onTap: () => _onMarkerTap(stop),
        icon: iconToDisplay);
_markers[stop.stopId] = marker;
_mapController.showMarkerInfoWindow(_markers[_selectedStopId].markerId);`

Dies on last line.
[doc v.txt](https://github.com/flutter/flutter/files/4275443/doc.v.txt)
[run.txt](https://github.com/flutter/flutter/files/4275444/run.txt)

**Comment by iapicca** [comment]
Hi @jamieownsu 
thank you for the logs,
few more questions: usually the app in debug has inferior performances
compared to the app in release mode, could you please try it i release?
(`flutter run build apk `or `flutter run --release` no need for logs)
are you using the latest version of the plugin? ([google_maps_flutter](https://pub.dev/packages/google_maps_flutter) `0.5.24+1`)
thanks again

**Comment by jamieownsu** [comment]
@iapicca 
Sounds like a plan, I will try that when I get home from work.

And yes I am using the latest version :)

**Comment by jamieownsu** [comment]
No change after trying the release version

**Comment by dwikyhardi** [comment]
Same issue. Any solution found?? @jamieownsu

**Comment by dwikyhardi** [comment]
> Same issue. Any solution found?? @jamieownsu

i have this error too.
any solution ??

[ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: PlatformException(Invalid markerId, showInfoWindow called with invalid markerId, null)

**Comment by jamieownsu** [comment]
@dwikyhardi The only workaround I've found so far is to wait for the marker to be shown on the map, then it seems to get added to the maps marker list; otherwise, it will return null.

**Comment by LondonJammo** [comment]
Did you fix this? How did you decide an arbitrary delay to wait for the marker to appear on the map? I create the marker with the newMarkerID, `setState(() {})` and add it to the _markers list, then how do you know when the GoogleMap has updated it's markers and can then use `showInfoWindow()` ?

**Comment by yorickreum** [comment]
Any news here? I encountered the same issue, quite annoying…

**Comment by thomasschwarzott** [comment]
We are also experiencing inconsistently appearing issues here. We create markers for a specific type of locations around the users current location, which works well. And then there's also the option to use a text search with a typeahead to look for these locations. There is absolutely no problem moving the camera to the selected location, but `showMarkerInfoWindow()` often throws `PlatformException (PlatformException(Invalid markerId, showInfoWindow called with invalid markerId, null))`. And this happens _despite_ having a `markerId`! 

The interesting thing is, that it happens _consistently for certain locations_. It's like, no problem to showInfoWindow of Location A and Location B, but Location C will always throw me the PlatformException.

Here's what's basically happening:

`
// get CameraPosition for selected location
_cameraPosition = _getCameraPosition(
    pharmacyLocation.lat,
    pharmacyLocation.lng,
);

// push a new Marker() widget for the selected location into List<Marker> _nearbyLocationsMarkers
_addNewMarker(location);

// animate camera (working well)
mapController
    .animateCamera(CameraUpdate.newCameraPosition(_cameraPosition))
    .then((_) {
      try {
        // take the markerId from the Marker() we just created to showMarkerInfoWindow()
        // although checking for null and trying to catch the PlatformException,
        // the code will break here for some locations
        if (_nearbyLocationsMarkers.last.markerId != null) {
          mapController.showMarkerInfoWindow(
            _nearbyLocationsMarkers.last.markerId,
          );
        }
      } on PlatformException catch (exception) {
        print('PlatformException when showing marker info window: $exception');
}
`

**Comment by jkd359** [comment]
Just bumping to let know am experiencing exact same issue, also with hideMarkerInfoWindow.

**Comment by ErnestoCuesy** [comment]
I have the same problem in both debug and release modes.

**Comment by lmadams** [comment]
I put a delayed and its working,,,

`    googleMapController
        .animateCamera(CameraUpdate.newLatLngBounds(bounds, 45.0))
        .then((_) async {
      await Future.delayed(Duration(seconds: 1));
      googleMapController.showMarkerInfoWindow(lastMarker.markerId);
    });`

**Comment by ErnestoCuesy** [comment]
@lmadams thank you for that, it worked! It's a pity it only displays one InfoWindow at a time. I wanted to display 2. It only displays the last one. In native Android it is possible to display more than one at a time. Oh, well. Better than nothing. Thanks and good job!

**Comment by jamieownsu** [comment]
@lmadams it's a hack but it works :)

**Comment by RaashVision** [comment]
@lmadams Thanks its working!

**Comment by johncerpa** [comment]
That worked!

**Comment by giorgio79** [comment]
I think the issue is that the Marker creation function should be an async function. It is generated with a delay.
```
Marker(
        markerId: MarkerId(stop.stopId.toString()),
        position: stop.coordinates,
        infoWindow: InfoWindow(
            title: stop.stopName,
            snippet: 'Stop # ${stop.stopNumber}',
            onTap: () => _fetchSchedules(stop.stopId)),
        onTap: () => _onMarkerTap(stop),
        icon: iconToDisplay);
```

**Comment by elmissouri16** [comment]
> I put a delayed and its working,,,
> 
> ```
> googleMapController
>         .animateCamera(CameraUpdate.newLatLngBounds(bounds, 45.0))
>         .then((_) async {
>       await Future.delayed(Duration(seconds: 1));
>       googleMapController.showMarkerInfoWindow(lastMarker.markerId);
> });
> ```

this not working if camera has to move from point a to point b  and they are long distance between them

**Comment by maheshmnj** [comment]
The issue is still reproducible with latest version of flutter with ```google_maps_flutter: ^2.0.6```, But the infoWindow isn't shown  as soon as the marker loads on map and the exception is thrown.

Here are the details.
<details>
  <summary>Reproducible Sample Code</summary>

  ```
import 'dart:async';
import 'dart:math';

import 'package:flutter/material.dart';
import 'package:google_maps_flutter/google_maps_flutter.dart';

class MapSample extends StatefulWidget {
  @override
  State<MapSample> createState() => MapSampleState();
}

class MapSampleState extends State<MapSample> {
  Completer<GoogleMapController> _controller = Completer();
  int _markerIdCounter = 1;
  Map<MarkerId, Marker> markers = <MarkerId, Marker>{};
  GoogleMapController? mapController;

  static final CameraPosition initialPos = CameraPosition(
    target: LatLng(122, 37),
    zoom: 8.0,
  );
  static final LatLng center = const LatLng(41.4560383, 15.777665000000013);

  static final CameraPosition _currentPosition =
      CameraPosition(target: center, zoom: 8.0);

  void _add(LatLng lng) {
    final int markerCount = markers.length;

    if (markerCount == 12) {
      return;
    }

    final String markerIdVal = 'marker_id_$_markerIdCounter';
    _markerIdCounter++;
    final MarkerId markerId = MarkerId(markerIdVal);
    final Marker marker = Marker(
      markerId: markerId,
      position: LatLng(
        lng.latitude + sin(_markerIdCounter * pi / 6.0) / 20.0,
        lng.longitude + cos(_markerIdCounter * pi / 6.0) / 20.0,
      ),
      infoWindow: InfoWindow(title: markerIdVal, snippet: '*'),
    );

    setState(() {
      markers[markerId] = marker;
      mapController!.showMarkerInfoWindow(markerId);
    });
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: GoogleMap(
        initialCameraPosition: initialPos,
        mapType: MapType.normal,
        onTap: _add,
        markers: Set<Marker>.of(markers.values),
        onMapCreated: (GoogleMapController controller) {
          _controller.complete(controller);
          setState(() {
            mapController = controller;
          });
          _goToCurrentPosition();
          _add(center);
        },
      ),
    );
  }

  Future<void> _goToCurrentPosition() async {
    final GoogleMapController controller = await _controller.future;
    controller.animateCamera(CameraUpdate.newCameraPosition(_currentPosition));
  }
}
  ```

</details>


<details>
<summary>flutter doctor -v</summary> 

```
[✓] Flutter (Channel stable, 2.2.2, on macOS 11.4 20F71 darwin-arm, locale en-IN)
    • Flutter version 2.2.2 at /Users/mahesh/Documents/flutter
    • Framework revision d79295af24 (7 days ago), 2021-06-11 08:56:01 -0700
    • Engine revision 91c9fc8fe0
    • Dart version 2.13.3

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/mahesh/Library/Android/sdk
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = /Users/mahesh/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] IntelliJ IDEA Community Edition (version 2021.1.2)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 57.0.5
    • Dart plugin version 211.7233

[✓] VS Code (version 1.57.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.23.0

[✓] Connected device (4 available)
    • Redmi K20 Pro (mobile)    • d9dac45d      • android-arm64  • Android 10 (API 29)
    • sdk gphone arm64 (mobile) • emulator-5554 • android-arm64  • Android 11 (API 30) (emulator)
    • macOS (desktop)           • macos         • darwin-arm64   • macOS 11.4 20F71 darwin-arm
    • Chrome (web)              • chrome        • web-javascript • Google Chrome 91.0.4472.114

• No issues found!
```
</details>

<details>
<summary> Console Output</summary>

```
E/flutter (31433): [ERROR:flutter/lib/ui/ui_dart_state.cc(199)] Unhandled Exception: PlatformException(Invalid markerId, showInfoWindow called with invalid markerId, null, null)
E/flutter (31433): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:597)
E/flutter (31433): #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:158)
E/flutter (31433): <asynchronous suspension>
E/flutter (31433): 
```
</details>

**Comment by tarasmurzenkovv** [comment]
Bumping up. I am experiencing the same problem.
```
[VERBOSE-2:ui_dart_state.cc(199)] Unhandled Exception: PlatformException(Invalid markerId, showInfoWindow called with invalid markerId, null, null)
#0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:597:7)
#1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:158:18)
<asynchronous suspension>
```

`google_maps_flutter: ^2.0.6`

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.2.3, on macOS 11.4 20F71 darwin-x64, locale en-GB)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
[✓] Xcode - develop for iOS and macOS
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.1)
[✓] IntelliJ IDEA Ultimate Edition (version 2021.1.3)
[✓] VS Code (version 1.58.0)
[✓] Connected device (2 available)

```

**Comment by maheshmnj** [comment]
> Bumping up. I am experiencing the same problem.

Was this working before? if yes, It would be helpful if you could point to the version you were upgrading from.

Thank you.

**Comment by tarasmurzenkovv** [comment]
> > Bumping up. I am experiencing the same problem.
> 
> @tarasmurzenkovv, Was this working before? if yes, It would be helpful if you could point to the version you were upgrading from.
> 
> Thank you.

@maheshmnj I always used the same version and didn’t do any upgrade. This issue is reproducible when I change the collection of markers.

**Comment by tarasmurzenkovv** [comment]
> > Bumping up. I am experiencing the same problem.
> 
> @tarasmurzenkovv, Was this working before? if yes, It would be helpful if you could point to the version you were upgrading from.
> 
> Thank you.

@maheshmnj I always used the same version and didn’t do any upgrade. This issue is reproducible when I change the collection of markers.

**Comment by Imesh7** [comment]
still got this issue, will flutter team consider to fix

**Comment by thefirebanks** [comment]
Experiencing this error too! 

Here's the code:

```dart
Set<Marker> _markers = {};

void _handleMapTap(LatLng tappedPoint) async {
    String address = await getAddressFromLatLng(tappedPoint);
    Marker _new_marker = Marker(
      markerId: MarkerId(tappedPoint.toString()),
      position: tappedPoint,
      infoWindow: InfoWindow(
        title: 'Tapped Location',
        snippet: address,
      ),
    );
    MarkerId _marker_id = _new_marker.markerId;

    setState(() {
      _markers = <Marker>{_new_marker};
    });

    if (_marker_id != null) {
      print("Found a _marker_id: $_marker_id");
      mapController.showMarkerInfoWindow(_marker_id);
    }
  }

// Other code...

@override
  Widget build(BuildContext context) {
    return Column(
      mainAxisAlignment: MainAxisAlignment.center,
      crossAxisAlignment: CrossAxisAlignment.stretch,
      children: [
        Expanded(
          key: Key("gmap-container"),
          child: GoogleMap(
            onMapCreated: _onMapCreated,
            initialCameraPosition: CameraPosition(
              target: _userLocation,
              zoom: 11.0,
            ),
            myLocationEnabled:
                _locationPermissionStatus == PermissionStatus.granted,
            onTap: _handleMapTap,
            markers: _markers,
          ),
        )
      ],
    );
```

Where I'm able to print the marker ID and the location but I still get the error:

```
E/flutter ( 2567): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: PlatformException(Invalid markerId, isInfoWindowShown called with invalid markerId, null, null)
```

**Comment by hombrevago** [comment]
as of now after a lot of experimenting this is working (for now).

1. putting it in a postFrameCallback: to schedule after the first frame is rendered.
2. I also have it in a Future.delayed trying to force it into the next event loop
it's possible both are overkill.  not sure.

here is an example.

  void _showFeaturedListingInfoWindow(int id) async {
    // schedule after the first frame is rendered,
    WidgetsBinding.instance.addPostFrameCallback((_) async {
      try {
        // Schedule the callback for the next event loop cycle
        Future.delayed(const Duration(milliseconds: 0), () async {
          final markerId = MarkerId(id.toString());
          await gmc?.showMarkerInfoWindow(markerId);
        });
      } catch (e) {
        print(e);
      }
    });
  }}
