### ISSUE TITLE
Very little information is received when using try catch

### ISSUE THREAD

**Issue by tbm98** [flutter/flutter#51744]
when I use try catch and debugPrint it show some error below
```
try {
      final json = jsonDecode(res.body);
      final account = LoginResponse.fromMap(json);
      return account;
    }catch(e){
      debugPrint(e);
    }
```
```
[VERBOSE-2:ui_dart_state.cc(157)] Unhandled Exception: type 'NoSuchMethodError' is not a subtype of type 'String'
#0      NonUserApi.login (package:andes_mobile_user/src/commons/apis/nonuser.dart:54:18)
<asynchronous suspension>
#1      LoginControl.login (package:andes_mobile_user/src/commons/controllers/login.dart:57:27)
#2      _LoginPageState._validateForm (package:andes_mobile_user/src/commons/views/login.dart:247:16)
#3      _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:706:14)
#4      _InkResponseState.build.<anonymous closure> (package:flutter/src/material/ink_well.dart:789:36)
#5      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:182:24)
#6      TapGestureRecognizer.handleTapUp (package:flutter/src/gestures/tap.dart:486:11)
#7      BaseTapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:264:5)
#8      BaseTapGestureRecognizer.handlePrimaryPointer (package:flutter/src/gestures/tap.dart:199:7)
#9      PrimaryPointerGe<…>
```
It is incomplete and I cannot detect the problem.
even if I changed debugPrint to print, all I got was
```
flutter: NoSuchMethodError: The method '*' was called on null.
Receiver: null
Tried calling: *(1000)
```

When I disable try catch, I receive the full error information and it leads me to the exact location of the error

```
final json = jsonDecode(res.body);
      final account = LoginResponse.fromMap(json);
      logs(account);
      return account;
```
```
[VERBOSE-2:ui_dart_state.cc(157)] Unhandled Exception: NoSuchMethodError: The method '*' was called on null.
Receiver: null
Tried calling: *(1000)
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:53:5)
#1      new DateTime.fromMillisecondsSinceEpoch (dart:core-patch/date_patch.dart:41:36)
#2      new InfoUser.fromMap (package:andes_mobile_user/src/commons/models/info_user.dart:31:26)
#3      new LoginResponse.fromMap (package:andes_mobile_user/src/commons/models/login_response.dart:13:26)
#4      NonUserApi.login (package:andes_mobile_user/src/commons/apis/nonuser.dart:50:37)
<asynchronous suspension>
#5      LoginControl.login (package:andes_mobile_user/src/commons/controllers/login.dart:57:27)
#6      _LoginPageState._validateForm (package:andes_mobile_user/src/commons/views/login.dart:247:16)
#7      _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:706:14)
#8      _InkResponseState.build.<anonymous closure> (package:flutter/src/material/ink_well.dart:789:36)
#<…>
```
How can I use try catch and get all the error information?

**Comment by jonahwilliams** [comment]
you should also print the stackTrace:

```
try {

} catch (err, stackTrace) {
  debugPrint(err);
  debugPrint(stackTrace);
}
```

**Comment by tbm98** [comment]
It worked ! Thanks :D
