### ISSUE TITLE
[tool_crash] missing windows\plugin.vcxproj in plugin causes tool crash

### ISSUE THREAD

**Issue by DhiaEddineNabli** [flutter/flutter#51743]
## Command
```
flutter run
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
FileSystemException: FileSystemException: Cannot open file, path = 'C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\window_utils-1.0.2\windows\plugin.vcxproj' (OS Error: The system cannot find the file specified.
, errno = 2)
```
#0      _File.throwIfError (dart:io/file_impl.dart:645:7)
#1      _File.openSync (dart:io/file_impl.dart:489:5)
#2      _File.readAsBytesSync (dart:io/file_impl.dart:549:18)
#3      _File.readAsStringSync (dart:io/file_impl.dart:594:18)
#4      ForwardingFile.readAsStringSync (package:file/src/forwarding/forwarding_file.dart:103:16)
#5      new VisualStudioProject (package:flutter_tools/src/windows/visual_studio_project.dart:18:32)
#6      new _PluginProjectInfo (package:flutter_tools/src/windows/visual_studio_solution_utils.dart:35:12)
#7      VisualStudioSolutionUtils._getWindowsPluginNamesByGuid (package:flutter_tools/src/windows/visual_studio_solution_utils.dart:252:41)
#8      VisualStudioSolutionUtils.updatePlugins (package:flutter_tools/src/windows/visual_studio_solution_utils.dart:68:51)
<asynchronous suspension>
#9      injectPlugins (package:flutter_tools/src/plugins.dart:1100:87)
<asynchronous suspension>
#10     FlutterProject.ensureReadyForPlatformSpecificTooling (package:flutter_tools/src/project.dart:232:11)
<asynchronous suspension>
#11     FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:696:21)
<asynchronous suspension>
#12     FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:609:33)
<asynchronous suspension>
#13     FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart)
#14     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:29)
```
```
[✓] Flutter (Channel master, v1.15.4-pre.241, on Microsoft Windows [Version 10.0.18362.657], locale en-US)
    • Flutter version 1.15.4-pre.241 at C:\src\flutter
    • Framework revision 1d3fcfd6ca (20 hours ago), 2020-02-29 10:01:18 -0800
    • Engine revision 755e2b559d
    • Dart version 2.8.0 (build 2.8.0-dev.10.0 09bbd3cca5)

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at C:\Users\dhian\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.3
    • Java binary at: D:\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)
    • All Android licenses accepted.

[✓] Visual Studio - develop for Windows (Visual Studio Community 2019 16.4.5)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.4.29806.167

[✓] Android Studio (version 3.5)
    • Android Studio at D:\Android\Android Studio
    • Flutter plugin version 43.0.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)

[✓] Connected device (1 available)
    • Windows • Windows • windows-x64 • Microsoft Windows [Version 10.0.18362.657]

• No issues found!

```

## Flutter Application Metadata
**Version**: 0.1.0
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
### Plugins
flutter_keyboard_visibility-0.7.0
window_utils-1.0.2

**Comment by stuartmorgan** [comment]
I should bullet-proof this and make it a tool exit rather than a crash.

**Comment by stuartmorgan** [comment]
Normally I would say that you should contact the plugin author to tell them to update their plugin for the tool changes, but since the repo is a 404 that's not really an option.

It's unfortunate that the plugin was published on pub.dev with a `windows` folder given that the instructions for making experimental Windows plugins specifically say not to do that, but it's not something we can actually prevent.
