### ISSUE TITLE
WillPopScope + alerttDialog throws an exception when tapping the background

### ISSUE THREAD

**Issue by oodavid** [flutter/flutter#51768]
## Steps to Reproduce

1. Run the following app
2. When navigating **back** from the second page, tap the background of the `AlertDialog`
3. ...this returns `null` instead of `false`, throwing an exception

```dart
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: MyHomePage(),
    );
  }
}

class MyHomePage extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('Home'),
      ),
      body: Center(
        child: RaisedButton(
          child: Text('Go to other page'),
          onPressed: (){
            Navigator.push(
              context,
              MaterialPageRoute(builder: (context) => MyOtherPage()),
            );
          },
        ),
      ),
    );
  }
}

class MyOtherPage extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return WillPopScope(
      onWillPop: () => showDialog(
        context: context,
        builder: (BuildContext context) {
          return AlertDialog(
            title: Text('Quit Without Saving?'),
            actions: <Widget>[
              FlatButton(
                child: Text('Cancel'),
                onPressed: () {
                  Navigator.of(context).pop(false);
                },
              ),
              FlatButton(
                child: Text('Quit'),
                onPressed: () {
                  Navigator.of(context).pop(true);
                },
              ),
            ],
          );
        }
      ),
      child: Scaffold(
        appBar: AppBar(
          title: Text('Home'),
        ),
        body: Center(
          child: Column(
            children: <Widget>[
              Text('Go back, then hit the background of the modal'),
              Text('...this will trigger an exception <asyncronous gap>'),
            ],
          ),
        ),
      ),
    );
  }
}
```

**Expected results:**

To not throw an exception

**Actual results:**

It throws an exception (see logs below)

**Fix**

Chain the future to add null safety.

Interface-wise this is correct, but it's a sneaky caveat that keeps tripping me up. Not sure if it's a bug, or just worth mentioning in the docs.

```dart
onWillPop: () => showDialog(
  context: context,
  builder: (BuildContext context) {
    return AlertDialog(
      ....
    );
  }
).then((value) => value ?? false),
```

<details>
  <summary>Logs</summary>

```
> tmp flutter run --verbose
(REDACTED)
Unhandled Exception: Failed assertion: boolean expression must not be null
[        ] [DEVICE LOG] #0      ModalRoute.willPop (package:flutter/src/widgets/routes.dart:1135:26)
[   +2 ms] [DEVICE LOG] <asynchronous suspension>
[        ] [DEVICE LOG] #1      NavigatorState.maybePop (package:flutter/src/widgets/navigator.dart:2078:57)
[        ] [DEVICE LOG] #2      Navigator.maybePop (package:flutter/src/widgets/navigator.dart:1337:34)
[        ] [DEVICE LOG] #3      BackButton.build.<anonymous closure> (package:flutter/src/material/back_button.dart:105:21)
[        ] [DEVICE LOG] #4      _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:706:14)
[        ] [DEVICE LOG] #5      _InkResponseState.build.<anonymous closure>
(package:flutter/src/material/ink_well.dart:789:36)
[        ] [DEVICE LOG] #6      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:182:24)
[        ] [DEVICE LOG] #7      TapGestureRecognizer.handleTapUp (package:flutter/src/gestures/tap.dart:486:11)
[        ] [DEVICE LOG] #8      BaseTapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:264:5)
[        ] [DEVICE LOG] #9      BaseTapGestureRecognizer.acceptGesture (package:flutter/src/gestur<…>
[   +9 ms] [VERBOSE-2:ui_dart_state.cc(157)] Unhandled Exception: Failed assertion: boolean expression must not be null
[        ] #0      ModalRoute.willPop (package:flutter/src/widgets/routes.dart:1135:26)
[        ] <asynchronous suspension>
[        ] #1      NavigatorState.maybePop (package:flutter/src/widgets/navigator.dart:2078:57)
[        ] #2      Navigator.maybePop (package:flutter/src/widgets/navigator.dart:1337:34)
[        ] #3      BackButton.build.<anonymous closure> (package:flutter/src/material/back_button.dart:105:21)
[        ] #4      _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:706:14)
[        ] #5      _InkResponseState.build.<anonymous closure> (package:flutter/src/material/ink_well.dart:789:36)
[        ] #6      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:182:24)
[        ] #7      TapGestureRecognizer.handleTapUp (package:flutter/src/gestures/tap.dart:486:11)
[        ] #8      BaseTapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:264:5)
[        ] #9      BaseTapGestureRecognizer.acceptGesture (package:flutter/src/gestur<…>
```

```
flutter analyze
Analyzing tmp...                                                        
No issues found! (ran in 1.8s)
```

```
flutter doctor -v
[✓] Flutter (Channel stable, v1.12.13+hotfix.8, on Mac OS X 10.15.3 19D76,
    locale en-GB)
    • Flutter version 1.12.13+hotfix.8 at /Users/david/Development/flutter
    • Framework revision 0b8abb4724 (3 weeks ago), 2020-02-11 11:44:36 -0800
    • Engine revision e1e6ced81d
    • Dart version 2.7.0

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/david/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling
      support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.2.1, Build version 11B500
    • CocoaPods version 1.8.4

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 40.2.2
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build
      1.8.0_202-release-1483-b49-5587405)

[✓] VS Code (version 1.42.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.8.1

[✓] Connected device (1 available)
    • iPhone 8 Plus • 4F6B6FB8-B9F1-431F-B67F-AC9074C6A2DC • ios •
      com.apple.CoreSimulator.SimRuntime.iOS-13-2 (simulator)

• No issues found!
```

</details>

**Comment by TahaTesser** [comment]
Hi @oodavid 
Please check this [DartPad Gist](https://dartpad.dev/6e7e60b0b2924d953e1099aff5bb9aeb)
Unable to reproduce the exception from your code
Thank you

**Comment by oodavid** [comment]
@TahaTesser your DartPad Gist throws an exception - see the console.

```
Uncaught (in promise) Error: Failed assertion: boolean expression must not be null
  ...
```

DartPad should probably bubble the errors into the UI...
