### ISSUE TITLE
[image_picker] It will crash when used with image_saver, image_gallery_saver, image_picker_saver, image_save

### ISSUE THREAD

**Issue by chenxianqi** [flutter/flutter#51764]
Crash on Android only 。
IOS OK， No Problem。
image_picker will crash as long as it is used with one of these plugins
image_picker  AND （image_saver OR image_gallery_saver  OR  image_picker_saver OR image_save）

Steps to reproduce:
   --pubspec.yaml
     image_picker: 0.6.3 + 4
     image_saver: 1.0.2

  Added a new button, use image_picker to select a picture or take a picture, it does not return as expected, the program crashes after selecting a picture

## ERROR LOG
```
D/AndroidRuntime( 3869): Shutting down VM
E/AndroidRuntime( 3869): FATAL EXCEPTION: main
E/AndroidRuntime( 3869): Process: com.cmp520.WanChe, PID: 3869
E/AndroidRuntime( 3869): java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=2342, result=0, data=null} to activity {com.cmp520.WanChe/wanche.com.MainActivity}: java.lang.NullPointerException: Attempt to invoke interface method 'void io.flutter.plugin.common.MethodChannel$Result.success(java.lang.Object)' on a null object reference
E/AndroidRuntime( 3869):        at android.app.ActivityThread.deliverResults(ActivityThread.java:4269)
E/AndroidRuntime( 3869):        at android.app.ActivityThread.handleSendResult(ActivityThread.java:4313)
E/AndroidRuntime( 3869):        at android.app.ActivityThread.-wrap19(Unknown Source:0)
E/AndroidRuntime( 3869):        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1645)
E/AndroidRuntime( 3869):        at android.os.Handler.dispatchMessage(Handler.java:106)
E/AndroidRuntime( 3869):        at android.os.Looper.loop(Looper.java:164)
E/AndroidRuntime( 3869):        at android.app.ActivityThread.main(ActivityThread.java:6499)
E/AndroidRuntime( 3869):        at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime( 3869):        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:440)
E/AndroidRuntime( 3869):        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
E/AndroidRuntime( 3869): Caused by: java.lang.NullPointerException: Attempt to invoke interface method 'void io.flutter.plugin.common.MethodChannel$Result.success(java.lang.Object)' on a null object reference
E/AndroidRuntime( 3869):        at io.flutter.plugins.imagesaver.ImagePickerDelegate.finishWithSuccess(ImagePickerDelegate.java:528)
E/AndroidRuntime( 3869):        at io.flutter.plugins.imagesaver.ImagePickerDelegate.handleChooseImageResult(ImagePickerDelegate.java:448)
E/AndroidRuntime( 3869):        at io.flutter.plugins.imagesaver.ImagePickerDelegate.onActivityResult(ImagePickerDelegate.java:422)
E/AndroidRuntime( 3869):        at io.flutter.embedding.engine.FlutterEnginePluginRegistry$FlutterEngineActivityPluginBinding.onActivityResult(FlutterEnginePluginRegistry.java:634)
E/AndroidRuntime( 3869):        at io.flutter.embedding.engine.FlutterEnginePluginRegistry.onActivityResult(FlutterEnginePluginRegistry.java:367)
E/AndroidRuntime( 3869):        at io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.onActivityResult(FlutterActivityAndFragmentDelegate.java:546)
E/AndroidRuntime( 3869):        at io.flutter.embedding.android.FlutterActivity.onActivityResult(FlutterActivity.java:594)
E/AndroidRuntime( 3869):        at android.app.Activity.dispatchActivityResult(Activity.java:7276)
E/AndroidRuntime( 3869):        at android.app.ActivityThread.deliverResults(ActivityThread.java:4265)
E/AndroidRuntime( 3869):        ... 9 more
D/XgStat  ( 3869): [main(2): ProGuard:69] - catch app crash
I/XgStat  ( 3869): [main(2): ProGuard:41] - read mid from sharedPreferences， key=__MTA_DEVICE_INFO__1000001
I/XgStat  ( 3869): [main(2): ProGuard:41] - read mid from sharedPreferences， key=__MTA_DEVICE_INFO__3
I/XgStat  ( 3869): [main(2): ProGuard:41] - read mid from sharedPreferences， key=__MTA_DEVICE_INFO__1000001
I/XgStat  ( 3869): [main(2): ProGuard:41] - read mid from sharedPreferences， key=__MTA_DEVICE_INFO__3
I/MID     ( 3869): >>>   queryMatchContentProviders size:0
I/XgStat  ( 3869): [main(2): ProGuard:41] - read mid from sharedPreferences， key=__MTA_DEVICE_INFO__1000001
I/XgStat  ( 3869): [main(2): ProGuard:41] - read mid from sharedPreferences， key=__MTA_DEVICE_INFO__3
I/XgStat  ( 3869): [main(2): ProGuard:41] - read mid from sharedPreferences， key=__MTA_DEVICE_INFO__1000001
I/XgStat  ( 3869): [main(2): ProGuard:41] - read mid from sharedPreferences， key=__MTA_DEVICE_INFO__3
W/XgStat  ( 3869): [main(2): ProGuard:1033] - not contains sdk info.
W/XgStat  ( 3869): [main(2): ProGuard:1034] - ["java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=2342, result=0, data=null} to activity {com.cmp520.WanChe\/wanche.com.MainActivity}: java.lang.NullPointerException: Attempt to invoke interface method 'void io.flutter.plugin.common.MethodChannel$Result.success(java.lang.Object)' on a null object reference","android.app.ActivityThread.deliverResults(ActivityThread.java:4269)","android.app.ActivityThread.handleSendResult(ActivityThread.java:4313)","android.app.ActivityThread.-wrap19(Unknown Source:0)","android.app.ActivityThread$H.handleMessage(ActivityThread.java:1645)","android.os.Handler.dispatchMessage(Handler.java:106)","android.os.Looper.loop(Looper.java:164)","android.app.ActivityThread.main(ActivityThread.java:6499)","java.lang.reflect.Method.invoke(Native Method)","com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:440)","com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)"]
D/XgStat  ( 3869): [main(2): ProGuard:76] - Call the original uncaught exception handler.
```

## flutter run -d 2f49c4ea --verbose
```
[        ] I/flutter (28860): transfer-encoding: chunked
[        ] I/flutter (28860): date: Mon, 02 Mar 2020 10:09:51 GMT
[        ] I/flutter (28860): server: Jexus/6.1.40
[        ] I/flutter (28860): authorization: qfuzfyy4MF99q6KTgovGCPzoUd2GWiubPyo5Aan5LHahrdHwHOcupXMEYysbF1zFXIWH-9sLuPjDj4V0hX9wjqj2a4KhCetA5eCi8P99RyU
[        ] I/flutter (28860): , request: null, response: {code: 0, msg: 查询成功, data: {id: 91785, platform_key: wechat, platform_id: 18, name: smarty, mobile: , province: 广东, area: 广州, sex: 男,
last_login_time: 2020-02-25 16:26:22, channel: app, head_img: https://pic.cmp520.com/user_note/1583140039342.jpg, bind_mobile: , device_number: {"device_number":null,"plate_form":"android"},
is_vip_user: false, vip_data: {vip_type: YearCard, vip_type_name: VIP会员·年卡, car_num: 京A12346, expire_time: 2019.07.07, is_expire: true}, total_integral: 330, task
[        ] I/flutter (28860): 03-02 18:09:51 _count: 7, coupon_count: 0, notification_count: 0, is_sign: false}}}
[+4023 ms] D/AndroidRuntime(28860): Shutting down VM
[   +8 ms] E/AndroidRuntime(28860): FATAL EXCEPTION: main
[        ] E/AndroidRuntime(28860): Process: com.cmp520.WanChe, PID: 28860
[        ] E/AndroidRuntime(28860): java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=2343, result=-1, data=null} to activity
{com.cmp520.WanChe/wanche.com.MainActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String android.net.Uri.getPath()' on a null object reference
[   +1 ms] E/AndroidRuntime(28860):     at android.app.ActivityThread.deliverResults(ActivityThread.java:4915)
[        ] E/AndroidRuntime(28860):     at android.app.ActivityThread.handleSendResult(ActivityThread.java:4956)
[        ] E/AndroidRuntime(28860):     at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:51)
[        ] E/AndroidRuntime(28860):     at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
[        ] E/AndroidRuntime(28860):     at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
[        ] E/AndroidRuntime(28860):     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2043)
[        ] E/AndroidRuntime(28860):     at android.os.Handler.dispatchMessage(Handler.java:107)
[        ] E/AndroidRuntime(28860):     at android.os.Looper.loop(Looper.java:224)
[        ] E/AndroidRuntime(28860):     at android.app.ActivityThread.main(ActivityThread.java:7536)
[        ] E/AndroidRuntime(28860):     at java.lang.reflect.Method.invoke(Native Method)
[        ] E/AndroidRuntime(28860):     at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
[        ] E/AndroidRuntime(28860):     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)
[        ] E/AndroidRuntime(28860): Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String android.net.Uri.getPath()' on a null object reference
[        ] E/AndroidRuntime(28860):     at io.flutter.plugins.imagesaver.ImagePickerDelegate$3.getFullImagePath(ImagePickerDelegate.java:160)
[        ] E/AndroidRuntime(28860):     at io.flutter.plugins.imagesaver.ImagePickerDelegate.handleCaptureImageResult(ImagePickerDelegate.java:464)
[   +1 ms] E/AndroidRuntime(28860):     at io.flutter.plugins.imagesaver.ImagePickerDelegate.onActivityResult(ImagePickerDelegate.java:425)
[        ] E/AndroidRuntime(28860):     at io.flutter.embedding.engine.FlutterEnginePluginRegistry$FlutterEngineActivityPluginBinding.onActivityResult(FlutterEnginePluginRegistry.java:634)
[        ] E/AndroidRuntime(28860):     at io.flutter.embedding.engine.FlutterEnginePluginRegistry.onActivityResult(FlutterEnginePluginRegistry.java:367)
[        ] E/AndroidRuntime(28860):     at io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.onActivityResult(FlutterActivityAndFragmentDelegate.java:546)
[        ] E/AndroidRuntime(28860):     at io.flutter.embedding.android.FlutterActivity.onActivityResult(FlutterActivity.java:594)
[        ] E/AndroidRuntime(28860):     at android.app.Activity.dispatchActivityResult(Activity.java:8249)
[        ] E/AndroidRuntime(28860):     at android.app.ActivityThread.deliverResults(ActivityThread.java:4908)
[        ] E/AndroidRuntime(28860):     ... 11 more
[+3047 ms] D/XgStat  (28860): [main(2): ProGuard:69] - catch app crash
[  +13 ms] W/XgStat  (28860): [main(2): ProGuard:1033] - not contains sdk info.
[        ] W/XgStat  (28860): [main(2): ProGuard:1034] - ["java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=2343, result=-1, data=null} to activity
{com.cmp520.WanChe\/wanche.com.MainActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String android.net.Uri.getPath()' on a null object
reference","android.app.ActivityThread.deliverResults(ActivityThread.java:4915)","android.app.ActivityThread.handleSendResult(ActivityThread.java:4956)","android.app.servertransaction.ActivityResultIte
m.execute(ActivityResultItem.java:51)","android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)","android.app.servertransaction.TransactionExecutor.execute(Tran
sactionExecutor.java:95)","android.app.ActivityThread$H.handleMessage(ActivityThread.java:2043)","android.os.Handler.dispatchMessage(Handler.java:107)","android.os.Looper.loop(Looper.java:224)","androi
d.app.ActivityThread.main(ActivityThread.java:7536)","java.lang.reflect.Method.invoke(Native
Method)","com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)","com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)"]
[   +3 ms] D/XgStat  (28860): [main(2): ProGuard:76] - Call the original uncaught exception handler.
[   +9 ms] I/Process (28860): Sending signal. PID: 28860 SIG: 9
[  +60 ms] Service protocol connection closed.
[        ] Lost connection to device.
[   +3 ms] DevFS: Deleting filesystem on the device (file:///data/user/0/com.cmp520.WanChe/code_cache/appARNGGW/app/)
[        ] Sending to VM service: _deleteDevFS({fsName: app})
[ +255 ms] Ignored error while cleaning up DevFS: TimeoutException after 0:00:00.250000: Future not completed
[   +9 ms] "flutter run" took 54,311ms.
```

## flutter analyze
```
Analyzing app...                                                        

   info • Name non-constant identifiers using lowerCamelCase • lib/config.dart:6:23 • non_constant_identifier_names

1 issue found. (ran in 5.2s)
```

## flutter doctor -v
```
[✓] Flutter (Channel stable, v1.12.13+hotfix.8, on Mac OS X 10.14.5 18F132, locale zh-Hans-CN)
    • Flutter version 1.12.13+hotfix.8 at /Users/chenxianqi/flutter
    • Framework revision 0b8abb4724 (3 weeks ago), 2020-02-11 11:44:36 -0800
    • Engine revision e1e6ced81d
    • Dart version 2.7.0

 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/chenxianqi/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 28.0.3
    • ANDROID_HOME = /Users/chenxianqi/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.2.1, Build version 11B53
    • CocoaPods version 1.7.2

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 43.0.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] VS Code (version 1.42.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.8.1

[✓] Connected device (3 available)
    • Redmi Note 7 • 2f49c4ea                                 • android-arm64 • Android 10 (API 29)
    • Nexus 6      • ZX1G22HJQK                               • android-arm   • Android 8.1.0 (API 27)
    • Keith iPhone • af47b4c63dc2cad49a1672e7494dcded7224937e • ios           • iOS 13.3.1

• No issues found!
```

**Comment by TahaTesser** [comment]
Hi @chenxianqi 

For issue related to the 3rd party plugin [image_saver ](https://pub.dev/packages/image_saver) you may want to open an issue in the dedicated [github](https://github.com/serjlee/image_saver). or image_picker_saver or image_save 

This isn't an issue with `image_picker` itself
Closing, as this isn't an issue with Flutter itself,
if you disagree please write in the comments and I will reopen it

Thank you
