### ISSUE TITLE
cull_opacity_perf__timeline_summary is Flaky

### ISSUE THREAD

**Issue by cbracken** [flutter/flutter#51795]
Seeing a lot of failures in this benchmark. Greater than 50% of runs in the last 10 runs have failed with errors along the lines of:
```
2020-03-02T11:52:53.565416: stdout: [+1040 ms] "flutter drive" took 99,165ms.
2020-03-02T11:52:53.570605: stderr: Driver tests failed: 255
2020-03-02T11:52:53.571718: stderr: 
stderr: #0      throwToolExit (package:flutter_tools/src/base/common.dart:14:3)
stderr: #1      _runTests (package:flutter_tools/src/commands/drive.dart:470:5)
stderr: <asynchronous suspension>
2020-03-02T11:52:53.571902: stderr: #2      DriveCommand.runCommand (package:flutter_tools/src/commands/drive.dart:280:23)
stderr: <asynchronous suspension>
stderr: #3      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:711:18)
stderr: <asynchronous suspension>
stderr: #4      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:609:33)
stderr: <asynchronous suspension>
stderr: #5      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart)
stderr: #6      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:29)
stderr: #7      _rootRun (dart:async/zone.dart:1126:13)
stderr: #8      _CustomZone.run (dart:async/zone.dart:1023:19)
stderr: #9      _runZoned (dart:async/zone.dart:1518:10)
stderr: #10     runZoned (dart:async/zone.dart:1465:12)
stderr: #11     AppContext.run (package:flutter_tools/src/base/context.dart:149:18)
2020-03-02T11:52:53.572065: stderr: #12     FlutterCommand.run (package:flutter_tools/src/runner/flutter_command.dart:599:20)
stderr: #13     CommandRunner.runCommand (package:args/command_runner.dart:197:27)
stderr: #14     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:338:21)
stderr: <asynchronous suspension>
stderr: #15     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart)
stderr: #16     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:29)
stderr: #17     _rootRun (dart:async/zone.dart:1126:13)
stderr: #18     _CustomZone.run (dart:async/zone.dart:1023:19)
stderr: #19     _runZoned (dart:async/zone.dart:1518:10)
stderr: #20     runZoned (dart:async/zone.dart:1465:12)
stderr: #21     AppContext.run (package:flutter_tools/src/base/context.dart:149:18)
stderr: #22     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:288:19)
stderr: #23     CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:112:25)
2020-03-02T11:52:53.572239: stderr: #24     new Future.sync (dart:async/future.dart:224:31)
stderr: #25     CommandRunner.run (package:args/command_runner.dart:112:14)
stderr: #26     FlutterCommandRunner.run (package:flutter_tools/src/runner/flutter_command_runner.dart:231:18)
stderr: #27     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:63:22)
stderr: #28     _rootRun (dart:async/zone.dart:1126:13)
stderr: #29     _CustomZone.run (dart:async/zone.dart:1023:19)
stderr: #30     _runZoned (dart:async/zone.dart:1518:10)
stderr: #31     runZoned (dart:async/zone.dart:1502:12)
stderr: #32     run.<anonymous closure> (package:flutter_tools/runner.dart:61:18)
stderr: <asynchronous suspension>
stderr: #33     run.<anonymous closure> (package:flutter_tools/runner.dart)
stderr: #34     runInContext.runnerWrapper (package:flutter_tools/src/context_runner.dart:69:18)
stderr: <asynchronous suspension>
2020-03-02T11:52:53.572396: stderr: #35     runInContext.runnerWrapper (package:flutter_tools/src/context_runner.dart)
stderr: #36     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:29)
stderr: #37     _rootRun (dart:async/zone.dart:1126:13)
stderr: #38     _CustomZone.run (dart:async/zone.dart:1023:19)
stderr: #39     _runZoned (dart:async/zone.dart:1518:10)
stderr: #40     runZoned (dart:async/zone.dart:1465:12)
stderr: #41     AppContext.run (package:flutter_tools/src/base/context.dart:149:18)
stderr: #42     runInContext (package:flutter_tools/src/context_runner.dart:72:24)
stderr: #43     run (package:flutter_tools/runner.dart:50:10)
stderr: <asynchronous suspension>
stderr: #44     main (package:flutter_tools/executable.dart:69:9)
stderr: #45     main (file:///Users/flutter/.cocoon/flutter/packages/flutter_tools/bin/flutter_tools.dart:8:3)
stderr: #46     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:299:32)
stderr: #47     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:168:12)
2020-03-02T11:52:53.572501: stderr: 
stderr: 
2020-03-02T11:52:53.589206: "/Users/flutter/.cocoon/flutter/bin/flutter" exit code: 255
2020-03-02T11:52:53.599957: Task failed: Executable "/Users/flutter/.cocoon/flutter/bin/flutter" failed with exit code 255.2020-03-02T11:52:53.600346: 

Stack trace:
2020-03-02T11:52:53.630424: package:flutter_devicelab/framework/utils.dart 84:3        fail
package:flutter_devicelab/framework/utils.dart 311:5       exec
===== asynchronous gap ===========================
dart:async                                                 _asyncErrorWrapperHelper
package:flutter_devicelab/framework/framework.dart         _TaskRunner._performTask.<fn>
package:stack_trace                                        Chain.capture
package:flutter_devicelab/framework/framework.dart 154:11  _TaskRunner._performTask
package:flutter_devicelab/framework/framework.dart 88:41   _TaskRunner.run
```

**Comment by jmagman** [comment]
See also https://github.com/flutter/flutter/issues/51148 and https://github.com/flutter/flutter/issues/50997.

**Comment by cbracken** [comment]
Assigned to @liyuqian who is looking into this.

**Comment by liyuqian** [comment]
It seems that `cull_opacity_perf__timeline_summary` has always taken ~30 seconds to finish in the last dozens of commits no matter whether the test passes or fails. As the time is right around the timeout of 30 seconds, this is probably the expected behavior. I don't think that we can change the test itself to reduce the run time since that may invalidate the benchmark comparison.

We should just set the all driver tests timeout to be much larger than 30 seconds. I'm not sure if there's any quick way of doing that? I knew that @Hixie explicitly removed all test-specific timeouts in https://github.com/flutter/flutter/pull/26736 so we probably shouldn't just add a large timeout for each driver test. I wonder if we should just put a single `@Timeout(const Duration(seconds: 3600))` somewhere. CC @dnfield @jmagman

**Comment by dnfield** [comment]
@jason-simmons looked at this test a bit a week or two back when it was failing on a timeout.  It turned out the timeout was due to being flooded with new timeline events that were causing the benchmark to take longer to process.

Before the commit that regressed that, the benchmark was taking about 18 seconds to run.  After, it was taking over 30 consistently.

I think it's not very helpful to have the test fail because of a timeout, but at the same time I'd like to avoid raising timeouts that are uncovering regressions we should be caring about.  It's not clear to me why the benchmark has gone from taking ~18 seconds to taking close to 30 in the course of a couple weeks.

**Comment by digiter** [comment]
I have rebooted mac20+phone, and retried this task on it for 3 times, all succeeded with test execution time to be 35 seconds. Does it mean we need to increase the timeout? @jason-simmons

**Comment by dnfield** [comment]
If we checkout a framework revision from about 1 month ago, does it still take 35 seconds?

**Comment by jason-simmons** [comment]
I looked at the timeline produced by this benchmark in the latest engine versus an engine from 7 weeks ago.

The current engine generates a timeline that is 50% bigger due mostly to layer tree preroll events introduced by https://github.com/flutter/engine/commit/04274160e6.

If we want to keep these events, then the timeout for downloading the timeline will need to be extended in this benchmark.

**Comment by dnfield** [comment]
Ok - so it sounds like our timeline is bigger because of added events which are valuable to us or to Fuchsia, and that we should just up the timeout to allow for more events to come through.

@dworsham can you verify that those events are helpful?

**Comment by dnfield** [comment]
It sounds to me like we should just bump the timeout at this point.

It does make me wonder if we need to do something to validate that the number of timeline events we end up writing is not adversely affecting performance though.  Too much tracing can be bad.
