### ISSUE TITLE
[web] add screenshot capability to e2e web integration tests

### ISSUE THREAD

**Issue by nturgut** [flutter/flutter#51890]
add screenshot capability to e2e web integration tests. 

These screenshots should be easy to trigger from the widget tests, but should be taken on the platform (by the browser's driver).

**Comment by dnfield** [comment]
Discussed this offline, but we'd want this available for all platforms - that said, if we start with web first that's fine.

**Comment by nturgut** [comment]
Since I also added this issue to TODO for mobile screenshot capability, I'm renaming it and changing the milestone. PR #2904 adds the capability for web.

**Comment by nturgut** [comment]
@dnfield I merged the web PR. I'm leaving this issue open for the mobile part.

**Comment by smkhalsa** [comment]
@nturgut are screenshots for mobile being actively worked on? Any idea as to when this feature would be ready?

**Comment by HubertArciszewski95** [comment]
I'm joining to @smkhalsa question :)

**Comment by amorenew** [comment]
@dnfield It would be nice to be available for mobile as the only library used for the driver is _**outdated**_ 
https://pub.dev/packages/screenshots

**Comment by zakton5** [comment]
Any updates on this or maybe a timeline for when this will be available? Screenshots are such a hassle so this would have so great to have.

**Comment by bradyt** [comment]
I don't know about for web, but maybe on other platforms, it's already possible on one of the flutter channels, with https://api.flutter.dev/flutter/flutter_driver/FlutterDriver/screenshot.html.

I think I saw it working on `flutter channel dev`, I don't recall if it doesn't work on `flutter channel stable`.

**Comment by neiljaywarner** [comment]
@zakton5  what is your current workaround please? is it the outdatd plugin that looks snazzy but has a lot of dependencies and relative complexity/rampup?

**Comment by neiljaywarner** [comment]
@dnfield  @nturgut  @kf6gpe @darshankawar @amorenew  any updates please?

**Comment by mathtasatlime** [comment]
any further information on screenshot capabilities?

**Comment by hpoul** [comment]
Looks to me like screenshots are now supported on android? https://github.com/flutter/flutter/pull/84472 Is there some master issue tracking platform specific implementations? 🤔️

**Comment by lhimo** [comment]
For Android it's actually working but you need to call the method `binding.convertFlutterSurfaceToImage();` before creating the actual screenshot (more info [here](https://github.com/flutter/flutter/tree/master/packages/integration_test#screenshots), remember to delete the `.ensureInitialized` string).

Although, there should be a "reverse" method in order to continue with the e2e test, if you need for instance an intermediate screenshot, otherwise you get "Surface already converted to an image".

Besides, this can be applied only to the `flutter drive` command, but not to the `gradlew` approach if I'm not mistaken.

**Comment by mathtasatlime** [comment]
Thanks for your answer!
Ive already seen the link before but it turns out that the function convertFlutterSurfaceToImage() is not implemented for me. Even though I got the latest version of integration_test. It is really odd. I even cant find it in the doc of IntegrationTestWigdetsFlutterBinding [here](https://api.flutter.dev/flutter/package-integration_test_integration_test/IntegrationTestWidgetsFlutterBinding-class.html).
Any idea on that?

**Comment by lhimo** [comment]
I think you need to checkout the dev branch from the flutter repo, it's not
yet released as neither stable nor beta

Il mer 11 ago 2021, 12:14 mathtasatlime ***@***.***> ha
scritto:

**Comment by kradi26** [comment]
any news about this, if I try to run this on my android emulator: 

`/══╡ EXCEPTION CAUGHT BY FLUTTER TEST FRAMEWORK ╞════════════════════════════════════════════════════
I/flutter ( 6240): The following UnimplementedError was thrown running a test:
I/flutter ( 6240): Screenshots are not implemented on this platform
I/flutter ( 6240): 
I/flutter ( 6240): When the exception was thrown, this was the stack:
I/flutter ( 6240): #0      IOCallbackManager.takeScreenshot (package:integration_test/_callback_io.dart:59:5)
I/flutter ( 6240): #1      IntegrationTestWidgetsFlutterBinding.takeScreenshot (package:integration_test/integration_test.dart:165:27)`

**Comment by radikris** [comment]
https://github.com/flutter/flutter/blob/stable/packages/integration_test/lib/integration_test.dart

If I can see well, they added it to the stable channel, I will give it a try to see if it actually works as expected.

**Comment by mathtasatlime** [comment]
@radikris have you tried it already? Is it working as expected?

**Comment by KevinGong2013** [comment]
@NickKibish  integration_test native plugin is not being correctly registered unless running tests via XCTest, like when running via `flutter drive` or `flutter test` #91668

**Comment by BouweCeunen** [comment]
@NickKibish did you resolve your issue? I'm facing the same thing.

**Comment by NickKibish** [comment]
@BouweCeunen some kind of that.

As @tritao mentioned in #91668, you can slightly modify `IntegrationTestPlugin.m` and that fixed issue on iOS for me.
So currently I keep 'modified' copy of flatter (master channel) just to run Integration tests and take screenshots.

**Comment by ShahrearBinAmin** [comment]
Need this screenshot functionality badly for mobile (android)

```
await binding.convertFlutterSurfaceToImage();
await binding.takeScreenshot('screenshot');
```
I'm getting ` PlatformException(Could not copy the pixels, FlutterView is null, null, null)` in android.

**Comment by robertof-wolt** [comment]
Hi,

I want to add to this the need to be able to store screenshot without having to use a custom driver. Now I can get screenshots only if I invoke the tests with `flutter drive` using this driver code:

```dart
import 'dart:io';
import 'package:integration_test/integration_test_driver_extended.dart';

Future<void> main() async {
  try {
    await integrationDriver(
      onScreenshot: (screenshotName, screenshotBytes) async {
        final File image = await File('screenshots/$screenshotName.png')
            .create(recursive: true);
        image.writeAsBytesSync(screenshotBytes);
        return true;
      },
    );
  } catch (e) {
    print('Error occured taking screenshot: $e');
  }
}
```

and I get nothing if I use `flutter test´. Not a big issue when running locally but we want to generate screenshots as part of a Firebase Test Lab run and that is currently not possible since we cannot (or at least I didn't find a way) use a custom drivers there.

**Comment by Nirajn2311** [comment]
Any update on this as this bug is the only thing preventing me from using the newer `test` command of flutter and instead rely on driver tests/

**Comment by ousvat** [comment]
Can this be marked as priority 1(P1)?

**Comment by ckxddd0324** [comment]
Is there any update on this? Would love to take screenshot while running `flutter test` instead of `flutter drive` Thanks

**Comment by cedvdb** [comment]
@ckxddd0324 although not official you can refer to [this comment](https://github.com/flutter/flutter/issues/51890#issuecomment-1035032562) to do it today in **unit** testing and **integration** testing. I might have a github example somewhere too.

**Comment by sonjz** [comment]
re: [this post](https://github.com/flutter/flutter/issues/51890#issuecomment-1205229793), as of 2024-01 things have changed on the `integrationDriver`, as `driver` needs to be passed in now.

I've modified a solution I found on  [SO](https://stackoverflow.com/a/71273128/740575) that finally works, **it has been a trudge trying to find this, this would be a good example to have in integration_test/**

The SO was based on example from flutter integration_test with driver:
https://github.com/flutter/flutter/tree/master/packages/integration_test/example

- Update the driver to handle `onScreenshot` and save it to disk (or upload to s3, push to API, or whatever...)
- In your test file, use the integration test binding to take a screenshot.
- run `flutter drive` against the device you want the screenshot to be taken.

```

// test_driver/foo_test.dart
import 'dart:io';
import 'package:flutter_driver/flutter_driver.dart';
import 'package:integration_test/integration_test_driver_extended.dart';

Future<void> main() async {
  final FlutterDriver driver = await FlutterDriver.connect();
  await integrationDriver(
    driver: driver,
    onScreenshot: (String screenshotName, List<int> screenshotBytes) async {
      final File image =
          await File(screenshotName).create(recursive: true);
      image.writeAsBytesSync(screenshotBytes);
      return true;
    },
  );
}


// integration_test/bar_test.dart
import 'package:flutter_test/flutter_test.dart';
import 'package:integration_test/integration_test.dart';

import 'package:you_app/main.dart';

void main() {
  final binding = IntegrationTestWidgetsFlutterBinding.ensureInitialized()
      as IntegrationTestWidgetsFlutterBinding;

  testWidgets('screenshot', (WidgetTester tester) async {
    await tester.pumpWidget(const MyApp());
    await tester.pumpAndSettle();
    await binding.convertFlutterSurfaceToImage();
    await tester.pumpAndSettle();
    await binding.takeScreenshot('screenshots/screenshot.png');
  }
}

// then run
flutter drive --driver=test_driver/foo_test.dart --target integration_test/bar_test.dart --device_id <emulator_id>
```

With this base, it seems possible to write an integration test to [navigate your app](https://docs.flutter.dev/cookbook/testing/widget/tap-drag) and generate the screenshots you'll need for app stores.

Shouldn't be an issue make a script to hanlde this for all devices required by the app stores.

**Comment by ckxddd0324** [comment]
> @ckxddd0324 although not official you can refer to [this comment](https://github.com/flutter/flutter/issues/51890#issuecomment-1035032562) to do it today in unit testing and integration testing. I might have a github example somewhere too. It will print a base64 string of the screenshot that you can then convert.
> 
> Useful in unit testing to find what overflows.

Hello @cedvdb do you have an example? I have tried that, it seems not working for me.

**Comment by a-wallen** [comment]
> **ave in integration_test/**
> 
> The SO was based on example from flutter integration_test with driver: https://github.com/flutter/flutter/tree/master/packages/integration_test/example
> 
> * Update the driver to handle `onScreenshot` and save it to disk (or upload to s3, push to API, or whatever...)
> * In your test file, use the integration test binding to take a screenshot.
> * run `flutter drive` against the device you want the screenshot to be taken.
> 
> ```
> 
> // test_driver/foo_test.dart
> import 'dart:io';
> import 'package:flutter_driver/flutter_driver.dart';
> import 'package:integration_test/integration_test_driver_extended.dart';
> 
> Future<void> main() async {
>   final FlutterDriver driver = await FlutterDriver.connect();
>   await integrationDriver(
>     driver: driver,
>     onScreenshot: (String screenshotName, List<int> screenshotBytes) async {
>       final File image =
>           await File(screenshotName).create(recursive: true);
>       image.writeAsBytesSync(screenshotBytes);
>       return true;
>     },
>   );
> }
> 
> 
> // integration_test/bar_test.dart
> import 'package:flutter_test/flutter_test.dart';
> import 'package:integration_test/integration_test.dart';
> 
> import 'package:you_app/main.dart';
> 
> void main() {
>   final binding = IntegrationTestWidgetsFlutterBinding.ensureInitialized()
>       as IntegrationTestWidgetsFlutterBinding;
> 
>   testWidgets('screenshot', (WidgetTester tester) async {
>     await tester.pumpWidget(const MyApp());
>     await tester.pumpAndSettle();
>     await binding.convertFlutterSurfaceToImage();
>     await tester.pumpAndSettle();
>     await binding.takeScreenshot('screenshots/screenshot.png');
>   }
> }
> 
> // then run
> flutter drive --driver=test_driver/foo_test.dart --target integration_test/bar_test.dart --device_id <emulator_id>
> ```
> 
> With this base, it seems possible to write an integration test to [navigate your app](https://docs.flutter.dev/cookbook/testing/widget/tap-drag) and generate the screenshots you'll need for app stores.
> 
> Shouldn't be an issue make a script to hanlde this for all devices required by the app stores.

I can't migrate to the new integration test package because I need to take screenshots, so I'm stuck using the old flutter driver. My code looks like this, I'm wondering how I can perform async work to initialize my app using the old package. Could someone help?

**Comment by MichalDanielDobrzanski** [comment]
Any updates?

**Comment by ckxddd0324** [comment]
+1

**Comment by cedvdb** [comment]
I put the snippet I wrote above in a small packages to take screenshots during **unit** tests  https://pub.dev/packages/test_screenshot/versions/0.0.3

**Comment by camsim99** [comment]
Started digging into this on the Android front and here's what I (think I) know so far:

#### Some light history
This feature was attempted in the past with https://github.com/flutter/flutter/pull/84472, but my understanding is that this uses the approach of converting a `View` to a `Bitmap`, which I believe excludes the system UI (see [implementation](https://github.com/flutter/flutter/pull/84472/files#diff-b9c4f5ff7b9e1d3f322b79af3a78ea3ac9312767f569939cee10fed027eb3c3bR178)).

#### Some implementation options to include the system UI:
-  `adb shell screencap` will for sure work. I can't find docs on this 😅 but I tested this out and saw system UI included 👍 
- [`DeviceCapture.takeScreenshot`](https://developer.android.com/reference/androidx/test/core/app/DeviceCapture) I need to test out. The documentation doesn't make it _seem_ like it will only capture the `View` but we'll see.


#### Some other options I found:
- [Espresso's `ViewInteraction.captureToBitmap()`](https://developer.android.com/reference/kotlin/androidx/test/espresso/screenshot/package-summary) seems specific to a `View` so I think we can rule this out.

Will update this comment as I learn more!

**Comment by matanlurey** [comment]
If `DeviceCapture.takeScreenshot` is 1:1 with `adb shell screencap` then that would be my preference.

**Comment by matanlurey** [comment]
@camsim99 Just checking in, any updates or thoughts here?

Should we sync with @cbracken tomorrow and see how this can get done relatively cheaply for both platforms?

**Comment by cbracken** [comment]
iOS side landed in https://github.com/flutter/flutter/pull/164144.

There's an experimental usage improvement out in https://github.com/flutter/flutter/pull/164171 that we could iterate on to make this more convenient.

**Comment by matanlurey** [comment]
This has been deprioritized.
