### ISSUE TITLE
[Camera Plugin] Different version of Camera plugin shows different result.

### ISSUE THREAD

**Issue by rikutys** [flutter/flutter#51991]
Hi Guys,

Currently, I'm facing a problem that the camera plugin shows different results on different versions of the camera.

https://pub.dev/packages/camera

I'm using this camera plugin to create a project that able to do face detection on a live camera. 
And I also try to get a sample from code from another third-party project because I tried my own before and it doesn't work. And below the URL link was the sample project that successfully gets the result using a live camera to do face detection.

https://github.com/giandifra/Flutter-Smile-Face-Detection
 
After a few testing, I found out that the camera plugin might be the reason that pushing me back. I'm still a newbie on flutter so what I suspect might be wrong. 

On the sample project, the camera plugin version was camera: ^0.4.2
Below is the camera result shows
![02](https://user-images.githubusercontent.com/20749683/75945722-0352ed00-5ed6-11ea-97fe-7779cb02d40d.jpg)

The camera able to shows the grayscale of my images correctly but when I'm using the latest camera plugin version "camera: ^0.5.7+4" It shows me a corrupted image like the image below.
![01](https://user-images.githubusercontent.com/20749683/75945876-78262700-5ed6-11ea-9610-246a8345392d.jpg)

I'm using this function to convert the camera Image.

```dart
  Future<List<int>> convertYUV420toImage(
      CameraImage image, ImageRotation rotation) async {
    try {
      final int width = image.width;
      final int height = image.height;

      // imglib -> Image package from https://pub.dartlang.org/packages/image
      var img = imglib.Image(width, height); // Create Image buffer

      Plane plane = image.planes[0];
      const int shift = (0xFF << 24);

      // Fill image buffer with plane[0] from YUV420_888
      for (int x = 0; x < width; x++) {
        for (int planeOffset = 0; planeOffset < height * width; planeOffset += width) {
          final pixelColor = plane.bytes[planeOffset + x];
          // color: 0x FF  FF  FF  FF
          //           A   B   G   R
          // Calculate pixel color
          var newVal =
          shift | (pixelColor << 16) | (pixelColor << 8) | pixelColor;
          img.data[planeOffset + x] = newVal;
        }
      }

      imglib.PngEncoder pngEncoder = new imglib.PngEncoder(level: 0, filter: 0);
      // Convert to png
      List<int> png = pngEncoder.encodeImage(img);
      intImage = png;
      return png;
    } catch (e) {
      print(">>>>>>>>>>>> ERROR:" + e.toString());
    }
    return null;
  }
```

I also tried on the older camera version to do my project. But I tried to create a new project and copy whatever in the sample project to mine and it doesn't work. It shows the error message 

`    java.lang.RuntimeException: Unable to start activity ComponentInfo{tys.arc.rf_fd_v4/tys.arc.rf_fd_v4.MainActivity}: java.lang.UnsupportedOperationException: The new embedding does not support the old FlutterView.
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3304)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3443)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2040)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:224)
        at android.app.ActivityThread.main(ActivityThread.java:7520)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)
     Caused by: java.lang.UnsupportedOperationException: The new embedding does not support the old FlutterView.
        at io.flutter.embedding.engine.plugins.shim.ShimRegistrar.view(ShimRegistrar.java:82)
        at io.flutter.plugins.camera.CameraPlugin.registerWith(CameraPlugin.java:151)
        at io.flutter.plugins.GeneratedPluginRegistrant.registerWith(GeneratedPluginRegistrant.java:17)
        at tys.arc.rf_fd_v4.MainActivity.configureFlutterEngine(MainActivity.kt:10)
        at io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.onAttach(FlutterActivityAndFragmentDelegate.java:185)
        at io.flutter.embedding.android.FlutterActivity.onCreate(FlutterActivity.java:418)
        at android.app.Activity.performCreate(Activity.java:7894)
        at android.app.Activity.performCreate(Activity.java:7881)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1307)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3279)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3443) 
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83) 
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2040) 
        at android.os.Handler.dispatchMessage(Handler.java:107) 
        at android.os.Looper.loop(Looper.java:224) 
        at android.app.ActivityThread.main(ActivityThread.java:7520) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950) `

Hope I state the problem clearly, please let me know if you need more information for this.

**Comment by stuartmorgan** [comment]
`Plane` provides bytes per pixel and bytes per row; you appear not to be using them, and are instead assuming that it's a specific value. If you can reproduce this even when using the plane description to correctly extract pixels, please comment with the code and we can re-open.
