### ISSUE TITLE
[tool_crash] ProcessException: Process exited abnormally:xcodebuild: error: Could not resolve package dependencies:  Packages are not supported when using legacy build locations, but the current project has them enabled.  Command: /usr/bin/xcodebuild -list

### ISSUE THREAD

**Issue by eizarpaing** [flutter/flutter#51997]
## Command
  ```
  flutter run
  ```

  ## Steps to Reproduce
  1. ...
  2. ...
  3. ...

  ## Logs
  ProcessException: ProcessException: Process exited abnormally:
xcodebuild: error: Could not resolve package dependencies:
  Packages are not supported when using legacy build locations, but the current project has them enabled.
  Command: /usr/bin/xcodebuild -list
  ```
  #0      RunResult.throwException (package:flutter_tools/src/base/process.dart:141:5)
#1      _DefaultProcessUtils.run (package:flutter_tools/src/base/process.dart:275:19)
<asynchronous suspension>
#2      XcodeProjectInterpreter.getInfo (package:flutter_tools/src/ios/xcodeproj.dart:342:49)
#3      buildXcodeProject (package:flutter_tools/src/ios/mac.dart:281:70)
#4      IOSSimulator._setupUpdatedApplicationBundle (package:flutter_tools/src/ios/simulators.dart:436:48)
<asynchronous suspension>
#5      IOSSimulator.startApp (package:flutter_tools/src/ios/simulators.dart:354:15)
#6      FlutterDevice.runHot (package:flutter_tools/src/resident_runner.dart:451:54)
#7      _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:73:64)
#8      _rootRunUnary (dart:async/zone.dart:1134:38)
#9      _CustomZone.runUnary (dart:async/zone.dart:1031:19)
#10     _FutureListener.handleValue (dart:async/future_impl.dart:139:18)
#11     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:680:45)
#12     Future._propagateToListeners (dart:async/future_impl.dart:709:32)
#13     Future._completeWithValue (dart:async/future_impl.dart:524:5)
#14     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:32:15)
#15     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:290:13)
#16     ApplicationPackageFactory.getPackageForPlatform (package:flutter_tools/src/application_package.dart)
#17     _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:73:64)
  ```
  ```
  [✓] Flutter (Channel dev, v1.12.16, on Mac OS X 10.15 19A603, locale my-US)
    • Flutter version 1.12.16 at /Users/pc011/development/flutter
    • Framework revision 37f9c54116 (3 months ago), 2019-11-27 11:33:38 -0800
    • Engine revision fad1b23c42
    • Dart version 2.7.0

[!] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/pc011/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses

[✓] Xcode - develop for iOS and macOS (Xcode 11.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.1, Build version 11A1027
    • CocoaPods version 1.9.0.beta.3

[!] Android Studio (version 3.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)

[✓] VS Code (version 1.38.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.7.1

[✓] Connected device (1 available)
    • iPhone 11 • 738471E1-C946-4CF1-88C3-6BF2D98F5A74 • ios •
      com.apple.CoreSimulator.SimRuntime.iOS-13-1 (simulator)

! Doctor found issues in 2 categories.

  ```

  ## Flutter Application Metadata
  **Version**: 1.0.0+1
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
### Plugins
flutter_facebook_logingoogle_maps_flutterimage_cropperimage_pickerpath_providershared_preferencesshared_preferences_macosshared_preferences_websqflite

**Comment by KFMONGF2P** [comment]
Hi @eizarpaing ,I'm having similar issue, what was the solution to this issue?
