### ISSUE TITLE
when flutter run in ios device,  it will throw the error after a while: Failed to send crash report due to a network error: SocketException: OS Error: Operation timed out, errno = 60, address = clients2.google.com, port = 61508 Oops; flutter has exited unexpectedly.

### ISSUE THREAD

**Issue by 18814127739** [flutter/flutter#52076]
Flutter crash report; please file at https://github.com/flutter/flutter/issues.

## command

flutter run

## exception

ArgumentError: Invalid argument(s): Cannot find executable for /Users/tangjianming/Documents/flutter/bin/cache/artifacts/libimobiledevice/idevicesyslog.

```
#0      _getExecutable (package:process/src/interface/local_process_manager.dart:127:5)
#1      LocalProcessManager.start (package:process/src/interface/local_process_manager.dart:43:30)
#2      _DefaultProcessUtils.start (package:flutter_tools/src/base/process.dart:413:27)
#3      IMobileDevice.startLogger (package:flutter_tools/src/ios/mac.dart:236:25)
#4      IOSDeviceLogReader._listenToSysLog (package:flutter_tools/src/ios/devices.dart:615:19)
#5      _runGuarded (dart:async/stream_controller.dart:807:24)
#6      _BroadcastStreamController._subscribe (dart:async/broadcast_stream_controller.dart:215:7)
#7      _ControllerStream._createSubscription (dart:async/stream_controller.dart:820:19)
#8      _StreamImpl.listen (dart:async/stream_impl.dart:474:9)
#9      FlutterDevice.startEchoingDeviceLog (package:flutter_tools/src/resident_runner.dart:402:38)
#10     FlutterDevice.runHot (package:flutter_tools/src/resident_runner.dart:447:5)
<asynchronous suspension>
#11     HotRunner.run (package:flutter_tools/src/run_hot.dart:266:39)
#12     RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:504:37)
<asynchronous suspension>
#13     FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:615:18)
#14     _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:73:64)
#15     _rootRunUnary (dart:async/zone.dart:1134:38)
#16     _CustomZone.runUnary (dart:async/zone.dart:1031:19)
#17     _FutureListener.handleValue (dart:async/future_impl.dart:139:18)
#18     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:680:45)
#19     Future._propagateToListeners (dart:async/future_impl.dart:709:32)
#20     Future._completeWithValue (dart:async/future_impl.dart:524:5)
#21     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:32:15)
#22     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:290:13)
#23     RunCommand.usageValues (package:flutter_tools/src/commands/run.dart)
#24     _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:73:64)
#25     _rootRunUnary (dart:async/zone.dart:1134:38)
#26     _CustomZone.runUnary (dart:async/zone.dart:1031:19)
#27     _FutureListener.handleValue (dart:async/future_impl.dart:139:18)
#28     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:680:45)
#29     Future._propagateToListeners (dart:async/future_impl.dart:709:32)
#30     Future._completeWithValue (dart:async/future_impl.dart:524:5)
#31     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:32:15)
#32     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:290:13)
#33     IosProject.isSwift (package:flutter_tools/src/project.dart)
#34     _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:73:64)
#35     _rootRunUnary (dart:async/zone.dart:1134:38)
#36     _CustomZone.runUnary (dart:async/zone.dart:1031:19)
#37     _FutureListener.handleValue (dart:async/future_impl.dart:139:18)
#38     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:680:45)
#39     Future._propagateToListeners (dart:async/future_impl.dart:709:32)
#40     Future._completeWithValue (dart:async/future_impl.dart:524:5)
#41     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:32:15)
#42     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:290:13)
#43     IosProject.buildSettings (package:flutter_tools/src/project.dart)
#44     _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:73:64)
#45     _rootRunUnary (dart:async/zone.dart:1134:38)
#46     _CustomZone.runUnary (dart:async/zone.dart:1031:19)
#47     _FutureListener.handleValue (dart:async/future_impl.dart:139:18)
#48     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:680:45)
#49     Future._propagateToListeners (dart:async/future_impl.dart:709:32)
#50     Future._completeWithValue (dart:async/future_impl.dart:524:5)
#51     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:32:15)
#52     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:290:13)
#53     XcodeProjectInterpreter.getBuildSettings (package:flutter_tools/src/ios/xcodeproj.dart)
#54     _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:73:64)
#55     _rootRunUnary (dart:async/zone.dart:1134:38)
#56     _CustomZone.runUnary (dart:async/zone.dart:1031:19)
#57     _FutureListener.handleValue (dart:async/future_impl.dart:139:18)
#58     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:680:45)
#59     Future._propagateToListeners (dart:async/future_impl.dart:709:32)
#60     Future._completeWithValue (dart:async/future_impl.dart:524:5)
#61     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:32:15)
#62     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:290:13)
#63     _DefaultProcessUtils.run (package:flutter_tools/src/base/process.dart)
#64     _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:73:64)
#65     _rootRunUnary (dart:async/zone.dart:1134:38)
#66     _CustomZone.runUnary (dart:async/zone.dart:1031:19)
#67     _FutureListener.handleValue (dart:async/future_impl.dart:139:18)
#68     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:680:45)
#69     Future._propagateToListeners (dart:async/future_impl.dart:709:32)
#70     Future._completeWithValue (dart:async/future_impl.dart:524:5)
#71     Future.wait.<anonymous closure> (dart:async/future.dart:400:22)
#72     _rootRunUnary (dart:async/zone.dart:1134:38)
#73     _CustomZone.runUnary (dart:async/zone.dart:1031:19)
#74     _FutureListener.handleValue (dart:async/future_impl.dart:139:18)
#75     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:680:45)
#76     Future._propagateToListeners (dart:async/future_impl.dart:709:32)
#77     Future._complete (dart:async/future_impl.dart:514:7)
#78     _BufferingStreamSubscription.asFuture.<anonymous closure> (dart:async/stream_impl.dart:206:14)
#79     _rootRun (dart:async/zone.dart:1122:38)
#80     _CustomZone.run (dart:async/zone.dart:1023:19)
#81     _CustomZone.runGuarded (dart:async/zone.dart:925:7)
#82     _BufferingStreamSubscription._sendDone.sendDone (dart:async/stream_impl.dart:391:13)
#83     _BufferingStreamSubscription._sendDone (dart:async/stream_impl.dart:401:15)
#84     _BufferingStreamSubscription._close (dart:async/stream_impl.dart:285:7)
#85     _SinkTransformerStreamSubscription._close (dart:async/stream_transformers.dart:98:11)
#86     _EventSinkWrapper.close (dart:async/stream_transformers.dart:25:11)
#87     _StringAdapterSink.close (dart:convert/string_conversion.dart:251:11)
#88     _Utf8ConversionSink.close (dart:convert/string_conversion.dart:302:20)
#89     _ConverterStreamEventSink.close (dart:convert/chunked_conversion.dart:82:18)
#90     _SinkTransformerStreamSubscription._handleDone (dart:async/stream_transformers.dart:143:24)
#91     _rootRun (dart:async/zone.dart:1122:38)
#92     _CustomZone.run (dart:async/zone.dart:1023:19)
#93     _CustomZone.runGuarded (dart:async/zone.dart:925:7)
#94     _BufferingStreamSubscription._sendDone.sendDone (dart:async/stream_impl.dart:391:13)
#95     _BufferingStreamSubscription._sendDone (dart:async/stream_impl.dart:401:15)
#96     _BufferingStreamSubscription._close (dart:async/stream_impl.dart:285:7)
#97     _SyncStreamControllerDispatch._sendDone (dart:async/stream_controller.dart:774:19)
#98     _StreamController._closeUnchecked (dart:async/stream_controller.dart:631:7)
#99     _StreamController.close (dart:async/stream_controller.dart:624:5)
#100    _Socket._onData (dart:io-patch/socket_patch.dart:1838:21)
#101    _rootRunUnary (dart:async/zone.dart:1138:13)
#102    _CustomZone.runUnary (dart:async/zone.dart:1031:19)
#103    _CustomZone.runUnaryGuarded (dart:async/zone.dart:933:7)
#104    _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:338:11)
#105    _BufferingStreamSubscription._add (dart:async/stream_impl.dart:265:7)
#106    _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:766:19)
#107    _StreamController._add (dart:async/stream_controller.dart:642:7)
#108    _StreamController.add (dart:async/stream_controller.dart:588:5)
#109    new _RawSocket.<anonymous closure> (dart:io-patch/socket_patch.dart:1386:35)
#110    _NativeSocket.issueReadEvent.issue (dart:io-patch/socket_patch.dart:892:18)
#111    _microtaskLoop (dart:async/schedule_microtask.dart:43:21)
#112    _startMicrotaskLoop (dart:async/schedule_microtask.dart:52:5)
#113    _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
#114    _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:175:5)
```

## flutter doctor

```
[32m[✓][39m Flutter (Channel stable, v1.12.13, on Mac OS X 10.15.3 19D76, locale zh-Hans-CN)
    [32m•[39m Flutter version 1.12.13 at /Users/tangjianming/Documents/flutter
    [32m•[39m Framework revision cf37c2cd07 (3 months ago), 2019-11-25 12:04:30 -0800
    [32m•[39m Engine revision b6b54fd606
    [32m•[39m Dart version 2.7.0

[33m[!][39m Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    [32m•[39m Android SDK at /Users/tangjianming/Library/Android/sdk
    [32m•[39m Android NDK location not configured (optional; useful for native profiling support)
    [32m•[39m Platform android-29, build-tools 29.0.2
    [32m•[39m ANDROID_HOME = /Users/tangjianming/Library/Android/sdk
    [32m•[39m Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    [32m•[39m Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
    [33m![39m Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses

[32m[✓][39m Xcode - develop for iOS and macOS (Xcode 11.3.1)
    [32m•[39m Xcode at /Applications/Xcode.app/Contents/Developer
    [32m•[39m Xcode 11.3.1, Build version 11C504
    [32m•[39m CocoaPods version 1.8.4

[32m[✓][39m Android Studio (version 3.4)
    [32m•[39m Android Studio at /Applications/Android Studio.app/Contents
    [32m•[39m Flutter plugin version 39.0.1
    [32m•[39m Dart plugin version 183.6270
    [32m•[39m Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

[32m[✓][39m VS Code (version 1.42.1)
    [32m•[39m VS Code at /Applications/Visual Studio Code.app/Contents
    [32m•[39m Flutter extension version 3.8.1

[32m[✓][39m Connected device (1 available)
    [32m•[39m dragon_cat • 704c6fa7d38229c8aa1a36a28674e7ff3ffc63f7 • ios • iOS 12.1.2

[33m![39m Doctor found issues in 1 category.
```

**Comment by 18814127739** [comment]
rewrite
