### ISSUE TITLE
Failed to send crash report due to a network error: SocketException: OS Error: Operation timed out, errno = 60, address = clients2.google.com, port = 59781

### ISSUE THREAD

**Issue by 18814127739** [flutter/flutter#52081]
```
#0      _getExecutable (package:process/src/interface/local_process_manager.dart:127:5)
#1      LocalProcessManager.start (package:process/src/interface/local_process_manager.dart:43:30)
#2      _DefaultProcessUtils.start (package:flutter_tools/src/base/process.dart:413:27)
#3      IMobileDevice.startLogger (package:flutter_tools/src/ios/mac.dart:236:25)
#4      IOSDeviceLogReader._listenToSysLog (package:flutter_tools/src/ios/devices.dart:615:19)
#5      _runGuarded (dart:async/stream_controller.dart:807:24)
#6      _BroadcastStreamController._subscribe (dart:async/broadcast_stream_controller.dart:215:7)
#7      _ControllerStream._createSubscription (dart:async/stream_controller.dart:820:19)
#8      _StreamImpl.listen (dart:async/stream_impl.dart:474:9)
#9      FlutterDevice.startEchoingDeviceLog (package:flutter_tools/src/resident_runner.dart:402:38)
#10     FlutterDevice.runHot (package:flutter_tools/src/resident_runner.dart:447:5)
<asynchronous suspension>
#11     HotRunner.run (package:flutter_tools/src/run_hot.dart:266:39)
#12     RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:504:37)
<asynchronous suspension>
#13     FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:615:18)
#14     _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:73:64)
#15     _rootRunUnary (dart:async/zone.dart:1134:38)
#16     _CustomZone.runUnary (dart:async/zone.dart:1031:19)
#17     _FutureListener.handleValue (dart:async/future_impl.dart:139:18)
#18     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:680:45)
#19     Future._propagateToListeners (dart:async/future_impl.dart:709:32)
#20     Future._completeWithValue (dart:async/future_impl.dart:524:5)
#21     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:32:15)
#22     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:290:13)
#23     RunCommand.usageValues (package:flutter_tools/src/commands/run.dart)
#24     _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:73:64)
#25     _rootRunUnary (dart:async/zone.dart:1134:38)
#26     _CustomZone.runUnary (dart:async/zone.dart:1031:19)
#27     _FutureListener.handleValue (dart:async/future_impl.dart:139:18)
#28     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:680:45)
#29     Future._propagateToListeners (dart:async/future_impl.dart:709:32)
#30     Future._completeWithValue (dart:async/future_impl.dart:524:5)
#31     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:32:15)
#32     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:290:13)
#33     IosProject.isSwift (package:flutter_tools/src/project.dart)
#34     _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:73:64)
#35     _rootRunUnary (dart:async/zone.dart:1134:38)
#36     _CustomZone.runUnary (dart:async/zone.dart:1031:19)
#37     _FutureListener.handleValue (dart:async/future_impl.dart:139:18)
#38     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:680:45)
#39     Future._propagateToListeners (dart:async/future_impl.dart:709:32)
#40     Future._completeWithValue (dart:async/future_impl.dart:524:5)
#41     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:32:15)
#42     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:290:13)
#43     IosProject.buildSettings (package:flutter_tools/src/project.dart)
#44     _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:73:64)
#45     _rootRunUnary (dart:async/zone.dart:1134:38)
#46     _CustomZone.runUnary (dart:async/zone.dart:1031:19)
#47     _FutureListener.handleValue (dart:async/future_impl.dart:139:18)
#48     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:680:45)
#49     Future._propagateToListeners (dart:async/future_impl.dart:709:32)
#50     Future._completeWithValue (dart:async/future_impl.dart:524:5)
#51     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:32:15)
#52     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:290:13)
#53     XcodeProjectInterpreter.getBuildSettings (package:flutter_tools/src/ios/xcodeproj.dart)
#54     _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:73:64)
#55     _rootRunUnary (dart:async/zone.dart:1134:38)
#56     _CustomZone.runUnary (dart:async/zone.dart:1031:19)
#57     _FutureListener.handleValue (dart:async/future_impl.dart:139:18)
#58     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:680:45)
#59     Future._propagateToListeners (dart:async/future_impl.dart:709:32)
#60     Future._completeWithValue (dart:async/future_impl.dart:524:5)
#61     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:32:15)
#62     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:290:13)
#63     _DefaultProcessUtils.run (package:flutter_tools/src/base/process.dart)
#64     _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:73:64)
#65     _rootRunUnary (dart:async/zone.dart:1134:38)
#66     _CustomZone.runUnary (dart:async/zone.dart:1031:19)
#67     _FutureListener.handleValue (dart:async/future_impl.dart:139:18)
#68     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:680:45)
#69     Future._propagateToListeners (dart:async/future_impl.dart:709:32)
#70     Future._completeWithValue (dart:async/future_impl.dart:524:5)
#71     Future.wait.<anonymous closure> (dart:async/future.dart:400:22)
#72     _rootRunUnary (dart:async/zone.dart:1134:38)
#73     _CustomZone.runUnary (dart:async/zone.dart:1031:19)
#74     _FutureListener.handleValue (dart:async/future_impl.dart:139:18)
#75     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:680:45)
#76     Future._propagateToListeners (dart:async/future_impl.dart:709:32)
#77     Future._complete (dart:async/future_impl.dart:514:7)
#78     _BufferingStreamSubscription.asFuture.<anonymous closure> (dart:async/stream_impl.dart:206:14)
#79     _rootRun (dart:async/zone.dart:1122:38)
#80     _CustomZone.run (dart:async/zone.dart:1023:19)
#81     _CustomZone.runGuarded (dart:async/zone.dart:925:7)
#82     _BufferingStreamSubscription._sendDone.sendDone (dart:async/stream_impl.dart:391:13)
#83     _BufferingStreamSubscription._sendDone (dart:async/stream_impl.dart:401:15)
#84     _BufferingStreamSubscription._close (dart:async/stream_impl.dart:285:7)
#85     _SinkTransformerStreamSubscription._close (dart:async/stream_transformers.dart:98:11)
#86     _EventSinkWrapper.close (dart:async/stream_transformers.dart:25:11)
#87     _StringAdapterSink.close (dart:convert/string_conversion.dart:251:11)
#88     _Utf8ConversionSink.close (dart:convert/string_conversion.dart:302:20)
#89     _ConverterStreamEventSink.close (dart:convert/chunked_conversion.dart:82:18)
#90     _SinkTransformerStreamSubscription._handleDone (dart:async/stream_transformers.dart:143:24)
#91     _rootRun (dart:async/zone.dart:1122:38)
#92     _CustomZone.run (dart:async/zone.dart:1023:19)
#93     _CustomZone.runGuarded (dart:async/zone.dart:925:7)
#94     _BufferingStreamSubscription._sendDone.sendDone (dart:async/stream_impl.dart:391:13)
#95     _BufferingStreamSubscription._sendDone (dart:async/stream_impl.dart:401:15)
#96     _BufferingStreamSubscription._close (dart:async/stream_impl.dart:285:7)
#97     _SyncStreamControllerDispatch._sendDone (dart:async/stream_controller.dart:774:19)
#98     _StreamController._closeUnchecked (dart:async/stream_controller.dart:631:7)
#99     _StreamController.close (dart:async/stream_controller.dart:624:5)
#100    _Socket._onData (dart:io-patch/socket_patch.dart:1838:21)
#101    _rootRunUnary (dart:async/zone.dart:1138:13)
#102    _CustomZone.runUnary (dart:async/zone.dart:1031:19)
#103    _CustomZone.runUnaryGuarded (dart:async/zone.dart:933:7)
#104    _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:338:11)
#105    _BufferingStreamSubscription._add (dart:async/stream_impl.dart:265:7)
#106    _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:766:19)
#107    _StreamController._add (dart:async/stream_controller.dart:642:7)
#108    _StreamController.add (dart:async/stream_controller.dart:588:5)
#109    new _RawSocket.<anonymous closure> (dart:io-patch/socket_patch.dart:1386:35)
#110    _NativeSocket.issueReadEvent.issue (dart:io-patch/socket_patch.dart:892:18)
#111    _microtaskLoop (dart:async/schedule_microtask.dart:43:21)
#112    _startMicrotaskLoop (dart:async/schedule_microtask.dart:52:5)
#113    _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
#114    _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:175:5)
```

## flutter doctor

```
[32m[✓][39m Flutter (Channel stable, v1.12.13, on Mac OS X 10.15.3 19D76, locale zh-Hans-CN)
    [32m•[39m Flutter version 1.12.13 at /Users/tangjianming/Documents/flutter
    [32m•[39m Framework revision cf37c2cd07 (3 months ago), 2019-11-25 12:04:30 -0800
    [32m•[39m Engine revision b6b54fd606
    [32m•[39m Dart version 2.7.0

[32m[✓][39m Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    [32m•[39m Android SDK at /Users/tangjianming/Library/Android/sdk
    [32m•[39m Android NDK location not configured (optional; useful for native profiling support)
    [32m•[39m Platform android-29, build-tools 29.0.2
    [32m•[39m ANDROID_HOME = /Users/tangjianming/Library/Android/sdk
    [32m•[39m Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    [32m•[39m Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
    [32m•[39m All Android licenses accepted.

[32m[✓][39m Xcode - develop for iOS and macOS (Xcode 11.3.1)
    [32m•[39m Xcode at /Applications/Xcode.app/Contents/Developer
    [32m•[39m Xcode 11.3.1, Build version 11C504
    [32m•[39m CocoaPods version 1.8.4

[32m[✓][39m Android Studio (version 3.4)
    [32m•[39m Android Studio at /Applications/Android Studio.app/Contents
    [32m•[39m Flutter plugin version 39.0.1
    [32m•[39m Dart plugin version 183.6270
    [32m•[39m Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

[32m[✓][39m VS Code (version 1.42.1)
    [32m•[39m VS Code at /Applications/Visual Studio Code.app/Contents
    [32m•[39m Flutter extension version 3.8.1

[32m[✓][39m Connected device (1 available)
    [32m•[39m dragon_cat • 704c6fa7d38229c8aa1a36a28674e7ff3ffc63f7 • ios • iOS 12.1.2

[32m•[39m No issues found!
```

**Comment by iapicca** [comment]
Hi @18814127739 
could you please run `flutter upgrade`
to catch up with the latest `hotfix`?
If the issue persists
can you please provide your updated `flutter doctor -v` , 
your `flutter run --verbose` 
and your `pubspec.yaml` 
or if possible a reproducible minimal code sample.
Thank you

**Comment by 18814127739** [comment]
> Hi @iapicca
> could you please run `flutter upgrade`
> to catch up with the latest `hotfix`?
> If the issue persists
> can you please provide your updated `flutter doctor -v` ,
> your `flutter run --verbose`
> and your `pubspec.yaml`
> or if possible a reproducible minimal code sample.
> Thank you

Hello, i have updated flutter to version 1.12.13+hotfix.8, but still have this error.
the result of running flutter doctor -v:
------------------------------------
[✓] Flutter (Channel stable, v1.12.13+hotfix.8, on Mac OS X 10.15.3 19D76, locale zh-Hans-CN)
    • Flutter version 1.12.13+hotfix.8 at /Users/tangjianming/Documents/flutter
    • Framework revision 0b8abb4724 (3 weeks ago), 2020-02-11 11:44:36 -0800
    • Engine revision e1e6ced81d
    • Dart version 2.7.0

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/tangjianming/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • ANDROID_HOME = /Users/tangjianming/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.3.1, Build version 11C504
    • CocoaPods version 1.8.4

[✓] Android Studio (version 3.4)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 39.0.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

[✓] VS Code (version 1.42.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.8.1

[✓] Connected device (1 available)
    • dragon_cat • 704c6fa7d38229c8aa1a36a28674e7ff3ffc63f7 • ios • iOS 12.1.2

• No issues found!

the content of  pubspec.yaml:
---------------------------------------
name: course_booking_app
description: A new Flutter project.
https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_swiper: ^1.1.4
  dio: ^3.0.9
  provider: ^4.0.4
  flutter_easyrefresh: ^1.2.7
  fluro: ^1.5.2
  flutter_html: ^0.11.1
  date_format: ^1.0.8
  video_player: ^0.10.4
  chewie: 0.9.8+1
  flutter_webview_plugin: 0.3.10+1
  webview_flutter: 0.3.18+1
  image_gallery_saver: ^1.2.2
  permission_handler: ^4.3.0
  image_picker: 0.6.3+4

  uses-material-design: true

  assets:
    - assets/images/banners/1.jpeg
    - assets/images/banners/2.jpeg
    - assets/images/banners/3.jpeg
    - assets/images/banners/4.jpeg
    - assets/images/banners/5.png
    - assets/images/loading/1.jpeg
    - assets/images/loading/2.jpeg
    - assets/images/avatar.jpeg
    - assets/images/dog.jpeg
    - assets/images/courses/1.png
    - assets/images/courses/2.png
    - assets/images/courses/3.png
    - assets/images/courses/4.png
    - assets/images/courses/5.png
    - assets/images/courses/6.png
    - assets/images/comment.png

    - assets/icons/me/medal.png
    - assets/icons/me/course.png
    - assets/icons/me/profile.png
    - assets/icons/me/situation.png
    - assets/icons/me/comment.png
    - assets/icons/me/grow.png
    - assets/icons/me/man.png
    - assets/icons/me/woman.png
    - assets/icons/location.png

    - assets/video/test.mp4

**Comment by 18814127739** [comment]
> Hi @18814127739
> could you please run `flutter upgrade`
> to catch up with the latest `hotfix`?
> If the issue persists
> can you please provide your updated `flutter doctor -v` ,
> your `flutter run --verbose`
> and your `pubspec.yaml`
> or if possible a reproducible minimal code sample.
> Thank you

This error only occurs when debugging with the real phone.
 It does not appear while debugging on the simulator

**Comment by iapicca** [comment]
Hi @18814127739 
could you please provide your `flutter run --verbose`
(on a physical device)
thank you

**Comment by TahaTesser** [comment]
Hi @18814127739 
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore
reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any
more information for us; we will reopen it right away!
Thanks for your contribution.
