### ISSUE TITLE
Cocoon app_flutter tests do not pass on latest dev branch

### ISSUE THREAD

**Issue by CaseyHillers** [flutter/flutter#52147]
Cocoon this past week had an issue where CI wasn't working because of some changes that rolled into the dev branch. The quick fix (https://github.com/flutter/cocoon/pull/670) was to move Cocoon off of dev and onto beta, however, these issues still need to be addressed.

- [X] BoxDecoration can no longer be relied on for testing the color of a widget (used in taskbox tests) (https://github.com/flutter/cocoon/pull/676)
- [X] NetworkImage exceptions are now handled a bit differently, we should move to a dedicated package for handling the network images (https://github.com/flutter/cocoon/pull/677)
- [ ] Add cocoon flutter app to flutter/tests ensure future changes like this are marked as breaking changes (https://github.com/flutter/tests/pull/26)

**Comment by dnfield** [comment]
We should add the tests for this to third party testing so we know what we're breaking.

What's the network image break?

**Comment by CaseyHillers** [comment]
```
chillers@chillzone:~/cocoon/app_flutter$ flutter test test/commit_box_test.dart 
00:02 +1: CommitBox shows overlay on click                                                                                                                                                                                                                           
══╡ EXCEPTION CAUGHT BY IMAGE RESOURCE SERVICE ╞════════════════════════════════════════════════════
The following NetworkImageLoadException was thrown resolving an image codec:
HTTP request failed, statusCode: 400, https://avatars2.githubusercontent.com/u/2148558?v=4

When the exception was thrown, this was the stack:
#0      NetworkImage._loadAsync (package:flutter/src/painting/_network_image_io.dart:95:9)
<asynchronous suspension>
#1      NetworkImage.load (package:flutter/src/painting/_network_image_io.dart:48:14)
#2      ImageProvider.resolveStreamForKey.<anonymous closure> (package:flutter/src/painting/image_provider.dart:491:13)
#3      ImageCache.putIfAbsent (package:flutter/src/painting/image_cache.dart:359:22)
#4      ImageProvider.resolveStreamForKey (package:flutter/src/painting/image_provider.dart:489:80)
#5      ImageProvider.resolve.<anonymous closure> (package:flutter/src/painting/image_provider.dart:330:9)
#6      ImageProvider._createErrorHandlerAndKey.<anonymous closure>.<anonymous closure> (package:flutter/src/painting/image_provider.dart:450:26)
#7      SynchronousFuture.then (package:flutter/src/foundation/synchronous_future.dart:41:29)
#8      ImageProvider._createErrorHandlerAndKey.<anonymous closure> (package:flutter/src/painting/image_provider.dart:447:11)
#12     ImageProvider._createErrorHandlerAndKey (package:flutter/src/painting/image_provider.dart:439:16)
#13     ImageProvider.resolve (package:flutter/src/painting/image_provider.dart:327:5)
#14     DecorationImagePainter.paint (package:flutter/src/painting/decoration_image.dart:240:55)
#15     _BoxDecorationPainter._paintBackgroundImage (package:flutter/src/painting/box_decoration.dart:463:19)
#16     _BoxDecorationPainter.paint (package:flutter/src/painting/box_decoration.dart:481:5)
#17     RenderDecoratedBox.paint (package:flutter/src/rendering/proxy_box.dart:2020:16)
#18     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2265:7)
#19     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:184:13)
#20     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:128:15)
#21     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2265:7)
#22     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:184:13)
#23     _RenderListTile.paint.doPaint (package:flutter/src/material/list_tile.dart:1469:17)
#24     _RenderListTile.paint (package:flutter/src/material/list_tile.dart:1472:12)
#25     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2265:7)
#26     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:184:13)
#27     RenderShiftedBox.paint (package:flutter/src/rendering/shifted_box.dart:70:15)
#28     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2265:7)
#29     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:184:13)
#30     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:128:15)
#31     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2265:7)
#32     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:184:13)
#33     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:128:15)
#34     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2265:7)
#35     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:184:13)
#36     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:128:15)
#37     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2265:7)
#38     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:184:13)
#39     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:128:15)
#40     RenderMouseRegion.paint (package:flutter/src/rendering/proxy_box.dart:2843:13)
#41     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2265:7)
#42     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:184:13)
#43     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:128:15)
#44     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2265:7)
#45     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:184:13)
#46     RenderBoxContainerDefaultsMixin.defaultPaint (package:flutter/src/rendering/box.dart:2515:15)
#47     RenderFlex.paint (package:flutter/src/rendering/flex.dart:950:7)
#48     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2265:7)
#49     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:184:13)
#50     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:128:15)
#51     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2265:7)
#52     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:184:13)
#53     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:128:15)
#54     _RenderInkFeatures.paint (package:flutter/src/material/material.dart:531:11)
#55     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2265:7)
#56     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:184:13)
#57     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:128:15)
#58     RenderCustomPaint.paint (package:flutter/src/rendering/custom_paint.dart:575:11)
#59     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2265:7)
#60     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:184:13)
#61     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:128:15)
#62     PaintingContext.pushLayer (package:flutter/src/rendering/object.dart:391:12)
#63     RenderPhysicalShape.paint (package:flutter/src/rendering/proxy_box.dart:1898:15)
#64     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2265:7)
#65     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:184:13)
#66     RenderShiftedBox.paint (package:flutter/src/rendering/shifted_box.dart:70:15)
#67     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2265:7)
#68     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:184:13)
#69     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:128:15)
#70     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2265:7)
#71     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:184:13)
#72     RenderBoxContainerDefaultsMixin.defaultPaint (package:flutter/src/rendering/box.dart:2515:15)
#73     RenderStack.paintStack (package:flutter/src/rendering/stack.dart:602:5)
#74     RenderStack.paint (package:flutter/src/rendering/stack.dart:610:7)
#75     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2265:7)
#76     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:184:13)
#77     _RenderTheatre.paintStack (package:flutter/src/widgets/overlay.dart:737:15)
#78     _RenderTheatre.paint (package:flutter/src/widgets/overlay.dart:747:7)
#79     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2265:7)
#80     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:184:13)
#81     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:128:15)
#82     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2265:7)
#83     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:184:13)
#84     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:128:15)
#85     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2265:7)
#86     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:184:13)
#87     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:128:15)
#88     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2265:7)
#89     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:184:13)
#90     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:128:15)
#91     RenderCustomPaint.paint (package:flutter/src/rendering/custom_paint.dart:575:11)
#92     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2265:7)
#93     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:184:13)
#94     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:128:15)
#95     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2265:7)
#96     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:184:13)
#97     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:128:15)
#98     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2265:7)
#99     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:184:13)
#100    RenderView.paint (package:flutter/src/rendering/view.dart:213:15)
#101    RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2265:7)
#102    PaintingContext._repaintCompositedChild (package:flutter/src/rendering/object.dart:135:11)
#103    PaintingContext.repaintCompositedChild (package:flutter/src/rendering/object.dart:95:5)
#104    PipelineOwner.flushPaint (package:flutter/src/rendering/object.dart:981:29)
#105    AutomatedTestWidgetsFlutterBinding.drawFrame (package:flutter_test/src/binding.dart:1016:27)
#106    RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:283:5)
#107    SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1108:15)
#108    SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1047:9)
#109    AutomatedTestWidgetsFlutterBinding.pump.<anonymous closure> (package:flutter_test/src/binding.dart:882:9)
#112    TestAsyncUtils.guard (package:flutter_test/src/test_async_utils.dart:72:41)
#113    AutomatedTestWidgetsFlutterBinding.pump (package:flutter_test/src/binding.dart:869:27)
#114    WidgetTester.pump.<anonymous closure> (package:flutter_test/src/widget_tester.dart:461:53)
#117    TestAsyncUtils.guard (package:flutter_test/src/test_async_utils.dart:72:41)
#118    WidgetTester.pump (package:flutter_test/src/widget_tester.dart:461:27)
#119    main.<anonymous closure>.<anonymous closure> (file:///usr/local/google/home/chillers/cocoon/app_flutter/test/commit_box_test.dart:60:20)
<asynchronous suspension>
#120    main.<anonymous closure>.<anonymous closure> (file:///usr/local/google/home/chillers/cocoon/app_flutter/test/commit_box_test.dart)
#121    testWidgets.<anonymous closure>.<anonymous closure> (package:flutter_test/src/widget_tester.dart:140:29)
<asynchronous suspension>
#122    testWidgets.<anonymous closure>.<anonymous closure> (package:flutter_test/src/widget_tester.dart)
#123    TestWidgetsFlutterBinding._runTestBody (package:flutter_test/src/binding.dart:706:19)
<asynchronous suspension>
#126    TestWidgetsFlutterBinding._runTest (package:flutter_test/src/binding.dart:686:14)
#127    AutomatedTestWidgetsFlutterBinding.runTest.<anonymous closure> (package:flutter_test/src/binding.dart:1086:24)
#133    AutomatedTestWidgetsFlutterBinding.runTest (package:flutter_test/src/binding.dart:1083:15)
#134    testWidgets.<anonymous closure> (package:flutter_test/src/widget_tester.dart:133:24)
#135    Declarer.test.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:test_api/src/backend/declarer.dart:172:27)
<asynchronous suspension>
#136    Declarer.test.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:test_api/src/backend/declarer.dart)
#137    Invoker.waitForOutstandingCallbacks.<anonymous closure> (package:test_api/src/backend/invoker.dart:246:15)
#142    Invoker.waitForOutstandingCallbacks (package:test_api/src/backend/invoker.dart:243:5)
#143    Declarer.test.<anonymous closure>.<anonymous closure> (package:test_api/src/backend/declarer.dart:170:33)
#148    Declarer.test.<anonymous closure> (package:test_api/src/backend/declarer.dart:169:13)
#149    Invoker._onRun.<anonymous closure>.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:test_api/src/backend/invoker.dart:400:25)
(elided 38 frames from class _FakeAsync, class _RawReceivePortImpl, class _Timer, dart:async, dart:async-patch, and package:stack_trace)

Image provider: NetworkImage("https://avatars2.githubusercontent.com/u/2148558?v=4", scale: 1.0)
Image key: NetworkImage("https://avatars2.githubusercontent.com/u/2148558?v=4", scale: 1.0)
════════════════════════════════════════════════════════════════════════════════════════════════════
```
with the test being

```
   testWidgets('commits show in the same column', (WidgetTester tester) async {
      await tester.pumpWidget(
        MaterialApp(
          home: Column(
            children: <Widget>[
              StatusGrid(
                buildState: FakeFlutterBuildState(),
                statuses: statuses,
                taskMatrix: taskMatrix,
              ),
            ],
          ),
        ),
      );
      // TODO(chillers): Remove this web check once issue is resolved. https://github.com/flutter/flutter/issues/44370
      if (!kIsWeb) {
        expect(tester.takeException(),
            const test.TypeMatcher<NetworkImageLoadException>());
      }

      final List<Element> commits = find.byType(CommitBox).evaluate().toList();

      final double xPosition = commits.first.size.topLeft(Offset.zero).dx;

      for (Element commit in commits) {
        // All the x positions should match the first instance if they're all in the same column
        expect(commit.size.topLeft(Offset.zero).dx, xPosition);
      }
    });
```

The widget loads Network.image() twice. I believe the image cache now invalidates on network failures which throws another error. This was just encouragement to switch over to a dedicated package for handling the network images.

**Comment by CaseyHillers** [comment]
@dnfield I'm familiar with flutter/tests but not the third party tests that you're familiar with. Can you share some more information on them?

**Comment by dnfield** [comment]
Ahhhh - in the test, a network request always results in an Http 400 status.

I'm not 100% clear on why this passed previously though.

Let's talk on Monday -there's a way to just run these tests on every Flutter commit.

**Comment by CaseyHillers** [comment]
`expect(tester.takeException(), const test.TypeMatcher<NetworkImageLoadException>());`

is what made this work. It wasn't the best way of doing it, and there was a quite a few references to that littered throughout the tests. The quick fix would be adding this to where the new exceptions popped up. The proper fix would probably be just creating a mock http client and returning fake data instead.

**Comment by CaseyHillers** [comment]
Another issue popped up with latest dev roll from 19 hours ago:
```
chillers-macbookair2:app_flutter chillers$ flutter build web
Downloading Web SDK...                                              3.4s
Running "flutter pub get" in app_flutter...                         1.6s
Target dart2js failed: Exception: ../../.pub-cache/hosted/pub.dartlang.org/google_sign_in_web-0.8.3/lib/src/generated/gapiauth2.dart:26:3:
Error: JS interop classes do not support non-external constructors.
  GoogleAuth.fakeConstructor$();
  ^
../../.pub-cache/hosted/pub.dartlang.org/google_sign_in_web-0.8.3/lib/src/generated/gapiauth2.dart:216:3:
Error: JS interop classes do not support non-external constructors.
  SigninOptionsBuilder.fakeConstructor$();
  ^
../../.pub-cache/hosted/pub.dartlang.org/google_sign_in_web-0.8.3/lib/src/generated/gapi.dart:351:3:
Error: JS interop classes do not support non-external constructors.
  HttpRequestPromise.fakeConstructor$();
  ^
../../.pub-cache/hosted/pub.dartlang.org/google_sign_in_web-0.8.3/lib/src/generated/gapi.dart:378:3:
Error: JS interop classes do not support non-external constructors.
  HttpRequest.fakeConstructor$() : super.fakeConstructor$();
  ^
../../.pub-cache/hosted/pub.dartlang.org/google_sign_in_web-0.8.3/lib/src/generated/gapi.dart:402:3:
Error: JS interop classes do not support non-external constructors.
  HttpBatch.fakeConstructor$();
  ^
../../.pub-cache/hosted/pub.dartlang.org/google_sign_in_web-0.8.3/lib/src/generated/gapi.dart:440:3:
Error: JS interop classes do not support non-external constructors.
  RpcRequest.fakeConstructor$();
  ^
Error: Compilation failed.


Compiling lib/main.dart for the Web...                             15.4s
Exception: Failed to compile application for the Web.
```

**Comment by Hixie** [comment]
FWIW google_sign_in_web-0.8.4 solves that last problem; `flutter packages upgrade` forces us to the new version and lets it run.
