### ISSUE TITLE
Could not connect to lockdownd, error code -18

### ISSUE THREAD

**Issue by s777610** [flutter/flutter#52163]
## Steps to Reproduce

after running `flutter run` I got 
```
ideviceinfo returned an error:
ERROR: Could not connect to lockdownd, error code -18
```
## Logs

```
flutter run --verbose
```
```
[  +18 ms] executing: [/Users/wilson/Desktop/IT/flutter/flutter/] git -c log.showSignature=false log -n 1
--pretty=format:%H
[  +33 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[        ] 0b8abb4724aa590dd0f429683339b1e045a1594d
[        ] executing: [/Users/wilson/Desktop/IT/flutter/flutter/] git describe --match v*.*.* --first-parent
--long --tags
[  +10 ms] Exit code 0 from: git describe --match v*.*.* --first-parent --long --tags
[        ] v1.12.13+hotfix.8-0-g0b8abb472
[   +8 ms] executing: [/Users/wilson/Desktop/IT/flutter/flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[  +11 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/stable
[        ] executing: [/Users/wilson/Desktop/IT/flutter/flutter/] git ls-remote --get-url origin
[  +10 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[  +57 ms] executing: [/Users/wilson/Desktop/IT/flutter/flutter/] git rev-parse --abbrev-ref HEAD
[  +10 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] stable
[   +5 ms] executing: sw_vers -productName
[  +14 ms] Exit code 0 from: sw_vers -productName
[        ] Mac OS X
[        ] executing: sw_vers -productVersion
[  +15 ms] Exit code 0 from: sw_vers -productVersion
[        ] 10.14.6
[        ] executing: sw_vers -buildVersion
[  +15 ms] Exit code 0 from: sw_vers -buildVersion
[        ] 18G95
[  +33 ms] executing: /usr/bin/xcode-select --print-path
[  +13 ms] Exit code 0 from: /usr/bin/xcode-select --print-path
[        ] /Applications/Xcode.app/Contents/Developer
[   +1 ms] executing: /usr/bin/xcodebuild -version
[  +99 ms] Exit code 0 from: /usr/bin/xcodebuild -version
[        ] Xcode 11.3.1
           Build version 11C504
[  +57 ms] executing: /Users/wilson/Library/Android/sdk/platform-tools/adb devices -l
[   +6 ms] Exit code 0 from: /Users/wilson/Library/Android/sdk/platform-tools/adb devices -l
[        ] List of devices attached
[  +13 ms] executing: /Users/wilson/Desktop/IT/flutter/flutter/bin/cache/artifacts/libimobiledevice/idevice_id
-h
[ +329 ms] "flutter run" took 614ms.
ideviceinfo returned an error:
ERROR: Could not connect to lockdownd, error code -18



#0      IMobileDevice.getInfoForDevice (package:flutter_tools/src/ios/mac.dart:226:9)
<asynchronous suspension>
#1      IOSDevice.getAttachedDevices (package:flutter_tools/src/ios/devices.dart:190:55)
<asynchronous suspension>
#2      IOSDevices.pollingGetDevices (package:flutter_tools/src/ios/devices.dart:115:57)
#3      PollingDeviceDiscovery.devices (package:flutter_tools/src/device.dart:285:52)
#4      DeviceManager.getAllConnectedDevices (package:flutter_tools/src/device.dart:140:46)
<asynchronous suspension>
#5      DeviceManager.getDevices (package:flutter_tools/src/device.dart:130:11)
#6      DeviceManager.findTargetDevices (package:flutter_tools/src/device.dart:173:34)
#7      FlutterCommand.findAllTargetDevices (package:flutter_tools/src/runner/flutter_command.dart:640:48)
#8      RunCommand.validateCommand (package:flutter_tools/src/commands/run.dart:287:21)
<asynchronous suspension>
#9      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:590:11)
#10     FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:515:33)
<asynchronous suspension>
#11     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:146:29)
#12     _rootRun (dart:async/zone.dart:1126:13)
#13     _CustomZone.run (dart:async/zone.dart:1023:19)
#14     _runZoned (dart:async/zone.dart:1518:10)
#15     runZoned (dart:async/zone.dart:1465:12)
#16     AppContext.run (package:flutter_tools/src/base/context.dart:145:18)
#17     FlutterCommand.run (package:flutter_tools/src/runner/flutter_command.dart:505:20)
#18     CommandRunner.runCommand (package:args/command_runner.dart:197:27)
#19     FlutterCommandRunner.runCommand.<anonymous closure>
(package:flutter_tools/src/runner/flutter_command_runner.dart:413:21)
<asynchronous suspension>
#20     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:146:29)
#21     _rootRun (dart:async/zone.dart:1126:13)
#22     _CustomZone.run (dart:async/zone.dart:1023:19)
#23     _runZoned (dart:async/zone.dart:1518:10)
#24     runZoned (dart:async/zone.dart:1465:12)
#25     AppContext.run (package:flutter_tools/src/base/context.dart:145:18)
#26     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:364:19)
#27     CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:112:25)
#28     new Future.sync (dart:async/future.dart:224:31)
#29     CommandRunner.run (package:args/command_runner.dart:112:14)
#30     FlutterCommandRunner.run (package:flutter_tools/src/runner/flutter_command_runner.dart:250:18)
#31     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:63:22)
#32     _rootRun (dart:async/zone.dart:1126:13)
#33     _CustomZone.run (dart:async/zone.dart:1023:19)
#34     _runZoned (dart:async/zone.dart:1518:10)
#35     runZoned (dart:async/zone.dart:1502:12)
#36     run.<anonymous closure> (package:flutter_tools/runner.dart:61:18)
<asynchronous suspension>
#37     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:146:29)
#38     _rootRun (dart:async/zone.dart:1126:13)
#39     _CustomZone.run (dart:async/zone.dart:1023:19)
#40     _runZoned (dart:async/zone.dart:1518:10)
#41     runZoned (dart:async/zone.dart:1465:12)
#42     AppContext.run (package:flutter_tools/src/base/context.dart:145:18)
#43     runInContext (package:flutter_tools/src/context_runner.dart:64:24)
#44     run (package:flutter_tools/runner.dart:50:10)
#45     main (package:flutter_tools/executable.dart:65:9)
#46     main (file:///b/s/w/ir/k/archive/flutter/packages/flutter_tools/bin/flutter_tools.dart:8:3)
#47     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:305:32)
#48     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:174:12)
```

```
flutter doctor -v
```

```
[✓] Flutter (Channel stable, v1.12.13+hotfix.8, on Mac OS X 10.14.6 18G95, locale en-US)
    • Flutter version 1.12.13+hotfix.8 at /Users/wilson/Desktop/IT/flutter/flutter
    • Framework revision 0b8abb4724 (3 weeks ago), 2020-02-11 11:44:36 -0800
    • Engine revision e1e6ced81d
    • Dart version 2.7.0


[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/wilson/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[!] Xcode - develop for iOS and macOS (Xcode 11.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.3.1, Build version 11C504
    ✗ CocoaPods not installed.
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin code that responds to your plugin usage
        on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To install:
        sudo gem install cocoapods

[!] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] VS Code (version 1.42.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.8.1

[☠] Connected device (the doctor check crashed)
    ✗ Due to an error, the doctor check did not complete. If the error message below is not helpful, please let us
      know about this issue at https://github.com/flutter/flutter/issues.
    ✗ Exception: ideviceinfo returned an error:
      ERROR: Could not connect to lockdownd, error code -18

    • #0      IMobileDevice.getInfoForDevice (package:flutter_tools/src/ios/mac.dart:226:9)
      <asynchronous suspension>
      #1      IOSDevice.getAttachedDevices (package:flutter_tools/src/ios/devices.dart:190:55)
      <asynchronous suspension>
      #2      IOSDevices.pollingGetDevices (package:flutter_tools/src/ios/devices.dart:115:57)
      #3      PollingDeviceDiscovery.devices (package:flutter_tools/src/device.dart:285:52)
      #4      DeviceManager.getAllConnectedDevices (package:flutter_tools/src/device.dart:140:46)
      <asynchronous suspension>
      #5      DeviceValidator.validate (package:flutter_tools/src/doctor.dart:851:54)
      #6      asyncGuard.<anonymous closure> (package:flutter_tools/src/base/async_guard.dart:111:32)
      #7      _rootRun (dart:async/zone.dart:1126:13)
      #8      _CustomZone.run (dart:async/zone.dart:1023:19)
      #9      _runZoned (dart:async/zone.dart:1518:10)
      #10     runZoned (dart:async/zone.dart:1502:12)
      #11     asyncGuard (package:flutter_tools/src/base/async_guard.dart:109:3)
      #12     Doctor.startValidatorTasks (package:flutter_tools/src/doctor.dart:158:9)
      #13     Doctor.diagnose (package:flutter_tools/src/doctor.dart:252:41)
      #14     _AsyncAwaitCompleter.start (dart:async-patch/async_patch.dart:45:6)
      #15     Doctor.diagnose (package:flutter_tools/src/doctor.dart:241:24)
      #16     DoctorCommand.runCommand (package:flutter_tools/src/commands/doctor.dart:59:39)
      #17     _AsyncAwaitCompleter.start (dart:async-patch/async_patch.dart:45:6)
      #18     DoctorCommand.runCommand (package:flutter_tools/src/commands/doctor.dart:45:42)
      #19     FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:615:18)
      #20     _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:73:64)
      #21     _rootRunUnary (dart:async/zone.dart:1134:38)
      #22     _CustomZone.runUnary (dart:async/zone.dart:1031:19)
      #23     _FutureListener.handleValue (dart:async/future_impl.dart:139:18)
      #24     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:680:45)
      #25     Future._propagateToListeners (dart:async/future_impl.dart:709:32)
      #26     Future._completeWithValue (dart:async/future_impl.dart:524:5)
      #27     Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:554:7)
      #28     _rootRun (dart:async/zone.dart:1126:13)
      #29     _CustomZone.run (dart:async/zone.dart:1023:19)
      #30     _CustomZone.runGuarded (dart:async/zone.dart:925:7)
      #31     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:965:23)
      #32     _microtaskLoop (dart:async/schedule_microtask.dart:43:21)
      #33     _startMicrotaskLoop (dart:async/schedule_microtask.dart:52:5)
      #34     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
      #35     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:175:5)


! Doctor found issues in 3 categories.
```

**Comment by VladyslavBondarenko** [comment]
Hi @s777610 
it should be fixed by https://github.com/flutter/flutter/issues/49375 (this PR isn't in stable yet),
check please is it your case and are you experiencing this issue with dev or master channel?

**Comment by TahaTesser** [comment]
Hi @s777610 
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore
reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any
more information for us; we will reopen it right away!
Thanks for your contribution.
