### ISSUE TITLE
cached_network_image Unhandled Exception: MissingPluginException

### ISSUE THREAD

**Issue by hyuntae0117** [flutter/flutter#52160]
I added cached_network_image on my flutter module
then I got error msg on android

My app is android native app with flutter module
```
Unhandled Exception: MissingPluginException(No implementation found for method getTemporaryDirectory on channel plugins.flutter.io/path_provider)
    #0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:154)
    <asynchronous suspension>
    #1      _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:75)
    <asynchronous suspension>
2020-03-07 14:39:38.768 1416-1569/? E/flutter: [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: MissingPluginException(No implementation found for method getDatabasesPath on channel com.tekartik.sqflite)
    #0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:154)
    <asynchronous suspension>
    #1      _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:75)
    <asynchronous suspension>
```

and flutter doctor

```
[✓] Flutter (Channel beta, v1.14.6, on Mac OS X 10.14.6 18G103, locale ko-KR)
    • Flutter version 1.14.6 at /Users/ht/project/flutter
    • Framework revision fabeb2a16f (6 weeks ago), 2020-01-28 07:56:51 -0800
    • Engine revision c4229bfbba
    • Dart version 2.8.0 (build 2.8.0-dev.5.0 fc3af737c7)

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/ht/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.3.1, Build version 11C504
    • CocoaPods version 1.8.4

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 43.0.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[!] IntelliJ IDEA Ultimate Edition (version 2019.3.3)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.dev/intellij-setup/#installing-the-plugins

[✓] Connected device (1 available)
    • SM T380 • 4b0f5be5f8e7a175 • android-arm • Android 8.1.0 (API 27)
```

**Comment by iamsandeepsk** [comment]
try restarting your computer and build again

**Comment by hyuntae0117** [comment]
@iamsandeepsk 
1. remove the app from device
2. restart my computer
3. build again
4. not work

**Comment by iamsandeepsk** [comment]
@hyuntae0117 try flutter clean once

**Comment by hyuntae0117** [comment]
@iamsandeepsk 
1. [flutter clean] on android studio => but can't build because FileNotFoundException: ..../.android/include_flutter.groovy
(why does this happen?)
2. command [flutter build aar]
3. run my app
4. not work

**Comment by iapicca** [comment]
Hi @hyuntae0117 
I believe you acted correctly opening the issue in the 3rd party plugin maintainer github.

If your module gives you crashes without said plugin, maybe implementing [caching](https://github.com/flutter/flutter/issues/9315) directly
please comment and I'll reopen the issue.
for now I'm closing, as this isn't an issue with Flutter itself
Thank you
