### ISSUE TITLE
Running pod install Error

### ISSUE THREAD

**Issue by hisan-web** [flutter/flutter#52184]
----->>>> flutter doctor
```
[✓] Flutter (Channel master, v1.15.16, on Mac OS X 10.15.3 19D76, locale zh-Hans-CN)

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 11.3.1)
[✓] Android Studio (version 3.6)
[✓] IntelliJ IDEA Ultimate Edition (version 2019.3.3)
[✓] VS Code (version 1.42.1)
[✓] Connected device (1 available)
```
----->>>> cocoapods version
1.8.4

----->>>> podfile

```
# Uncomment this line to define a global platform for your project
#platform :ios, '9.0'
platform :ios, '8.0'

# CocoaPods analytics sends network stats synchronously affecting flutter build latency.
ENV['COCOAPODS_DISABLE_STATS'] = 'true'

project 'Runner', {
  'Debug' => :debug,
  'Profile' => :release,
  'Release' => :release,
}

def parse_KV_file(file, separator='=')
  file_abs_path = File.expand_path(file)
  if !File.exists? file_abs_path
    return [];
  end
  generated_key_values = {}
  skip_line_start_symbols = ["#", "/"]
  File.foreach(file_abs_path) do |line|
    next if skip_line_start_symbols.any? { |symbol| line =~ /^\s*#{symbol}/ }
    plugin = line.split(pattern=separator)
    if plugin.length == 2
      podname = plugin[0].strip()
      path = plugin[1].strip()
      podpath = File.expand_path("#{path}", file_abs_path)
      generated_key_values[podname] = podpath
    else
      puts "Invalid plugin specification: #{line}"
    end
  end
  generated_key_values
end

target 'Runner' do
  use_frameworks!
  use_modular_headers!

  # Flutter Pod

  copied_flutter_dir = File.join(__dir__, 'Flutter')
  copied_framework_path = File.join(copied_flutter_dir, 'Flutter.framework')
  copied_podspec_path = File.join(copied_flutter_dir, 'Flutter.podspec')
  unless File.exist?(copied_framework_path) && File.exist?(copied_podspec_path)
    # Copy Flutter.framework and Flutter.podspec to Flutter/ to have something to link against if the xcode backend script has not run yet.
    # That script will copy the correct debug/profile/release version of the framework based on the currently selected Xcode configuration.
    # CocoaPods will not embed the framework on pod install (before any build phases can generate) if the dylib does not exist.

    generated_xcode_build_settings_path = File.join(copied_flutter_dir, 'Generated.xcconfig')
    unless File.exist?(generated_xcode_build_settings_path)
      raise "Generated.xcconfig must exist. If you're running pod install manually, make sure flutter pub get is executed first"
    end
    generated_xcode_build_settings = parse_KV_file(generated_xcode_build_settings_path)
    cached_framework_dir = generated_xcode_build_settings['FLUTTER_FRAMEWORK_DIR'];

    unless File.exist?(copied_framework_path)
      FileUtils.cp_r(File.join(cached_framework_dir, 'Flutter.framework'), copied_flutter_dir)
    end
    unless File.exist?(copied_podspec_path)
      FileUtils.cp(File.join(cached_framework_dir, 'Flutter.podspec'), copied_flutter_dir)
    end
  end

  # Keep pod path relative so it can be checked into Podfile.lock.
  pod 'Flutter', :path => 'Flutter'

  # Plugin Pods

  # Prepare symlinks folder. We use symlinks to avoid having Podfile.lock
  # referring to absolute paths on developers' machines.
  system('rm -rf .symlinks')
  system('mkdir -p .symlinks/plugins')
  plugin_pods = parse_KV_file('../.flutter-plugins')
  plugin_pods.each do |name, path|
    symlink = File.join('.symlinks', 'plugins', name)
    File.symlink(path, symlink)
    pod name, :path => File.join(symlink, 'ios')
  end
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['ENABLE_BITCODE'] = 'NO'
    end
  end
end
```

----->>>>  error
```
Running "flutter pub get" in b2c...                                13.7s
Launching lib/main.dart on iPhone 11 Pro Max in debug mode...
Running pod install...
CocoaPods' output:
      Preparing

    Analyzing dependencies

    Inspecting targets to integrate
      Using `ARCHS` setting to build architectures of target `Pods-Runner`: (``)

    Finding Podfile changes
      A path_provider
      A path_provider_macos
      A sqflite
      - Flutter
      - battery
      - connectivity
      - connectivity_macos
      - device_info
      - flutter_webview_plugin
      - fluttertoast
      - package_info
      - permission_handler
      - shared_preferences
      - shared_preferences_macos
      - shared_preferences_web

    Fetching external sources
    -> Fetching podspec for `Flutter` from `Flutter`
    -> Fetching podspec for `battery` from `.symlinks/plugins/battery/ios`
    -> Fetching podspec for `connectivity` from `.symlinks/plugins/connectivity/ios`
    -> Fetching podspec for `connectivity_macos` from `.symlinks/plugins/connectivity_macos/ios`
    -> Fetching podspec for `device_info` from `.symlinks/plugins/device_info/ios`
    -> Fetching podspec for `flutter_webview_plugin` from `.symlinks/plugins/flutter_webview_plugin/ios`
    -> Fetching podspec for `fluttertoast` from `.symlinks/plugins/fluttertoast/ios`
    -> Fetching podspec for `package_info` from `.symlinks/plugins/package_info/ios`
    -> Fetching podspec for `path_provider` from `.symlinks/plugins/path_provider/ios`
    -> Fetching podspec for `path_provider_macos` from `.symlinks/plugins/path_provider_macos/ios`
    -> Fetching podspec for `permission_handler` from `.symlinks/plugins/permission_handler/ios`
    -> Fetching podspec for `shared_preferences` from `.symlinks/plugins/shared_preferences/ios`
    -> Fetching podspec for `shared_preferences_macos` from `.symlinks/plugins/shared_preferences_macos/ios`
    -> Fetching podspec for `shared_preferences_web` from `.symlinks/plugins/shared_preferences_web/ios`
    -> Fetching podspec for `sqflite` from `.symlinks/plugins/sqflite/ios`

    Resolving dependencies of `Podfile`
      CDN: trunk Relative path: CocoaPods-version.yml exists! Returning local because checking is only perfomed in repo update
      CDN: trunk Relative path: all_pods_versions_f_4_e.txt exists! Returning local because checking is only perfomed in repo update
      CDN: trunk Redirecting from https://cdn.cocoapods.org/Specs/f/4/e/FMDB/2.5/FMDB.podspec.json to https://raw.githubusercontent.com/CocoaPods/Specs/master/Specs/f/4/e/FMDB/2.5/FMDB.podspec.json
      CDN: trunk Redirecting from https://cdn.cocoapods.org/Specs/f/4/e/FMDB/2.7.5/FMDB.podspec.json to https://raw.githubusercontent.com/CocoaPods/Specs/master/Specs/f/4/e/FMDB/2.7.5/FMDB.podspec.json
      CDN: trunk Redirecting from https://cdn.cocoapods.org/Specs/f/4/e/FMDB/1.5.1/FMDB.podspec.json to https://raw.githubusercontent.com/CocoaPods/Specs/master/Specs/f/4/e/FMDB/1.5.1/FMDB.podspec.json
      CDN: trunk Redirecting from https://cdn.cocoapods.org/Specs/f/4/e/FMDB/2.7.2/FMDB.podspec.json to https://raw.githubusercontent.com/CocoaPods/Specs/master/Specs/f/4/e/FMDB/2.7.2/FMDB.podspec.json
      CDN: trunk Redirecting from https://cdn.cocoapods.org/Specs/f/4/e/FMDB/2.0/FMDB.podspec.json to https://raw.githubusercontent.com/CocoaPods/Specs/master/Specs/f/4/e/FMDB/2.0/FMDB.podspec.json
      CDN: trunk Redirecting from https://cdn.cocoapods.org/Specs/f/4/e/FMDB/2.6.2/FMDB.podspec.json to https://raw.githubusercontent.com/CocoaPods/Specs/master/Specs/f/4/e/FMDB/2.6.2/FMDB.podspec.json
      CDN: trunk Redirecting from https://cdn.cocoapods.org/Specs/f/4/e/FMDB/2.2/FMDB.podspec.json to https://raw.githubusercontent.com/CocoaPods/Specs/master/Specs/f/4/e/FMDB/2.2/FMDB.podspec.json
      CDN: trunk Redirecting from https://cdn.cocoapods.org/Specs/f/4/e/FMDB/2.4/FMDB.podspec.json to https://raw.githubusercontent.com/CocoaPods/Specs/master/Specs/f/4/e/FMDB/2.4/FMDB.podspec.json
      CDN: trunk Redirecting from https://cdn.cocoapods.org/Specs/f/4/e/FMDB/2.1/FMDB.podspec.json to https://raw.githubusercontent.com/CocoaPods/Specs/master/Specs/f/4/e/FMDB/2.1/FMDB.podspec.json
      CDN: trunk Redirecting from https://cdn.cocoapods.org/Specs/f/4/e/FMDB/2.3/FMDB.podspec.json to https://raw.githubusercontent.com/CocoaPods/Specs/master/Specs/f/4/e/FMDB/2.3/FMDB.podspec.json
      CDN: trunk Redirecting from https://cdn.cocoapods.org/Specs/f/4/e/FMDB/2.6/FMDB.podspec.json to https://raw.githubusercontent.com/CocoaPods/Specs/master/Specs/f/4/e/FMDB/2.6/FMDB.podspec.json
      CDN: trunk Relative path: Specs/f/4/e/FMDB/1.5/FMDB.podspec.json error: Net::OpenTimeout - retrying
      CDN: trunk Redirecting from https://cdn.cocoapods.org/Specs/f/4/e/FMDB/1.5/FMDB.podspec.json to https://raw.githubusercontent.com/CocoaPods/Specs/master/Specs/f/4/e/FMDB/1.5/FMDB.podspec.json
      CDN: trunk Relative path: Specs/f/4/e/FMDB/2.7.5/FMDB.podspec.json error: Net::OpenTimeout - retrying
      CDN: trunk Relative path: Specs/f/4/e/FMDB/1.5.1/FMDB.podspec.json error: Net::OpenTimeout - retrying
      CDN: trunk Relative path: Specs/f/4/e/FMDB/2.7.2/FMDB.podspec.json error: Net::OpenTimeout - retrying
      CDN: trunk Relative path: Specs/f/4/e/FMDB/2.0/FMDB.podspec.json error: Net::OpenTimeout - retrying
      CDN: trunk Relative path: Specs/f/4/e/FMDB/2.6.2/FMDB.podspec.json error: Net::OpenTimeout - retrying
      CDN: trunk Relative path: Specs/f/4/e/FMDB/2.2/FMDB.podspec.json error: Net::OpenTimeout - retrying
      CDN: trunk Relative path: Specs/f/4/e/FMDB/2.4/FMDB.podspec.json error: Net::OpenTimeout - retrying
      CDN: trunk Relative path: Specs/f/4/e/FMDB/2.1/FMDB.podspec.json error: Net::OpenTimeout - retrying
      CDN: trunk Relative path: Specs/f/4/e/FMDB/2.3/FMDB.podspec.json error: Net::OpenTimeout - retrying
      CDN: trunk Relative path: Specs/f/4/e/FMDB/2.6/FMDB.podspec.json error: Net::OpenTimeout - retrying
      CDN: trunk Relative path: Specs/f/4/e/FMDB/2.5/FMDB.podspec.json error: Net::OpenTimeout - retrying
      CDN: trunk Relative path: Specs/f/4/e/FMDB/1.5/FMDB.podspec.json error: Net::OpenTimeout - retrying
      CDN: trunk Relative path: Specs/f/4/e/FMDB/2.7.2/FMDB.podspec.json error: Net::OpenTimeout - retrying
      CDN: trunk Relative path: Specs/f/4/e/FMDB/2.0/FMDB.podspec.json error: Net::OpenTimeout - retrying
      CDN: trunk Relative path: Specs/f/4/e/FMDB/2.6.2/FMDB.podspec.json error: Net::OpenTimeout - retrying
      CDN: trunk Relative path: Specs/f/4/e/FMDB/2.2/FMDB.podspec.json error: Net::OpenTimeout - retrying
      CDN: trunk Relative path: Specs/f/4/e/FMDB/2.3/FMDB.podspec.json error: Failed to open TCP connection to raw.githubusercontent.com:443 (Operation timed out - connect(2) for "raw.githubusercontent.com" port 443) - retrying
      CDN: trunk Relative path: Specs/f/4/e/FMDB/2.4/FMDB.podspec.json error: Net::OpenTimeout - retrying
      CDN: trunk Relative path: Specs/f/4/e/FMDB/2.1/FMDB.podspec.json error: Net::OpenTimeout - retrying
      CDN: trunk Relative path: Specs/f/4/e/FMDB/2.5/FMDB.podspec.json error: Net::OpenTimeout - retrying
      CDN: trunk Relative path: Specs/f/4/e/FMDB/2.6/FMDB.podspec.json error: Net::OpenTimeout - retrying
      CDN: trunk Relative path: Specs/f/4/e/FMDB/2.7.5/FMDB.podspec.json error: Net::OpenTimeout - retrying
      CDN: trunk Relative path: Specs/f/4/e/FMDB/1.5.1/FMDB.podspec.json error: Net::OpenTimeout - retrying
      CDN: trunk Relative path: Specs/f/4/e/FMDB/1.5/FMDB.podspec.json error: Net::OpenTimeout - retrying
      CDN: trunk Relative path: Specs/f/4/e/FMDB/2.0/FMDB.podspec.json error: Net::OpenTimeout - retrying
      CDN: trunk Relative path: Specs/f/4/e/FMDB/2.6.2/FMDB.podspec.json error: Net::OpenTimeout - retrying
      CDN: trunk Relative path: Specs/f/4/e/FMDB/2.2/FMDB.podspec.json error: Net::OpenTimeout - retrying
      CDN: trunk Relative path: Specs/f/4/e/FMDB/2.3/FMDB.podspec.json error: Net::OpenTimeout - retrying
      CDN: trunk Relative path: Specs/f/4/e/FMDB/2.1/FMDB.podspec.json error: Net::OpenTimeout - retrying
      CDN: trunk Relative path: Specs/f/4/e/FMDB/2.5/FMDB.podspec.json error: Net::OpenTimeout - retrying
      CDN: trunk Relative path: Specs/f/4/e/FMDB/2.6/FMDB.podspec.json error: Net::OpenTimeout - retrying
      CDN: trunk Relative path: Specs/f/4/e/FMDB/1.5.1/FMDB.podspec.json error: Net::OpenTimeout - retrying
      CDN: trunk Relative path: Specs/f/4/e/FMDB/2.4/FMDB.podspec.json error: Net::OpenTimeout - retrying
      CDN: trunk Relative path: Specs/f/4/e/FMDB/2.7.5/FMDB.podspec.json error: Net::OpenTimeout - retrying
      CDN: trunk Relative path: Specs/f/4/e/FMDB/2.6.2/FMDB.podspec.json error: Net::OpenTimeout - retrying
      CDN: trunk Relative path: Specs/f/4/e/FMDB/2.0/FMDB.podspec.json error: Net::OpenTimeout - retrying
      CDN: trunk Relative path: Specs/f/4/e/FMDB/2.2/FMDB.podspec.json error: Net::OpenTimeout - retrying
      CDN: trunk Relative path: Specs/f/4/e/FMDB/2.1/FMDB.podspec.json error: Net::OpenTimeout - retrying
      CDN: trunk Relative path: Specs/f/4/e/FMDB/2.5/FMDB.podspec.json error: Net::OpenTimeout - retrying
      CDN: trunk Relative path: Specs/f/4/e/FMDB/2.6/FMDB.podspec.json error: Net::OpenTimeout - retrying
      CDN: trunk Relative path: Specs/f/4/e/FMDB/1.5/FMDB.podspec.json error: Net::OpenTimeout - retrying
      CDN: trunk Relative path: Specs/f/4/e/FMDB/2.3/FMDB.podspec.json error: Net::OpenTimeout - retrying
      CDN: trunk Relative path: Specs/f/4/e/FMDB/2.4/FMDB.podspec.json error: Net::OpenTimeout - retrying
      CDN: trunk Relative path: Specs/f/4/e/FMDB/2.7.5/FMDB.podspec.json error: Net::OpenTimeout - retrying
      CDN: trunk Relative path: Specs/f/4/e/FMDB/1.5.1/FMDB.podspec.json error: Net::OpenTimeout - retrying
      CDN: trunk Relative path: Specs/f/4/e/FMDB/1.5/FMDB.podspec.json error: Net::OpenTimeout - retrying
    [!] CDN: trunk Repo update failed - 12 error(s):
    CDN: trunk URL couldn't be downloaded: https://raw.githubusercontent.com/CocoaPods/Specs/master/Specs/f/4/e/FMDB/1.5/FMDB.podspec.json, error: Net::OpenTimeout
    CDN: trunk URL couldn't be downloaded: https://raw.githubusercontent.com/CocoaPods/Specs/master/Specs/f/4/e/FMDB/1.5.1/FMDB.podspec.json, error: Net::OpenTimeout
    CDN: trunk URL couldn't be downloaded: https://raw.githubusercontent.com/CocoaPods/Specs/master/Specs/f/4/e/FMDB/2.0/FMDB.podspec.json, error: Net::OpenTimeout
    CDN: trunk URL couldn't be downloaded: https://raw.githubusercontent.com/CocoaPods/Specs/master/Specs/f/4/e/FMDB/2.1/FMDB.podspec.json, error: Net::OpenTimeout
    CDN: trunk URL couldn't be downloaded: https://raw.githubusercontent.com/CocoaPods/Specs/master/Specs/f/4/e/FMDB/2.2/FMDB.podspec.json, error: Net::OpenTimeout
    CDN: trunk URL couldn't be downloaded: https://raw.githubusercontent.com/CocoaPods/Specs/master/Specs/f/4/e/FMDB/2.3/FMDB.podspec.json, error: Net::OpenTimeout
    CDN: trunk URL couldn't be downloaded: https://raw.githubusercontent.com/CocoaPods/Specs/master/Specs/f/4/e/FMDB/2.4/FMDB.podspec.json, error: Net::OpenTimeout
    CDN: trunk URL couldn't be downloaded: https://raw.githubusercontent.com/CocoaPods/Specs/master/Specs/f/4/e/FMDB/2.5/FMDB.podspec.json, error: Net::OpenTimeout
    CDN: trunk URL couldn't be downloaded: https://raw.githubusercontent.com/CocoaPods/Specs/master/Specs/f/4/e/FMDB/2.6/FMDB.podspec.json, error: Net::OpenTimeout
    CDN: trunk URL couldn't be downloaded: https://raw.githubusercontent.com/CocoaPods/Specs/master/Specs/f/4/e/FMDB/2.6.2/FMDB.podspec.json, error: Net::OpenTimeout
    Failed to open TCP connection to raw.githubusercontent.com:443 (Network is down - connect(2) for "raw.githubusercontent.com" port 443)
    CDN: trunk URL couldn't be downloaded: https://raw.githubusercontent.com/CocoaPods/Specs/master/Specs/f/4/e/FMDB/2.7.5/FMDB.podspec.json, error: Net::OpenTimeout

    /Library/Ruby/Gems/2.6.0/gems/cocoapods-core-1.8.4/lib/cocoapods-core/cdn_source.rb:422:in `rescue in catching_concurrent_errors'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-core-1.8.4/lib/cocoapods-core/cdn_source.rb:418:in `catching_concurrent_errors'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-core-1.8.4/lib/cocoapods-core/cdn_source.rb:139:in `versions'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-core-1.8.4/lib/cocoapods-core/specification/set.rb:99:in `block in versions_by_source'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-core-1.8.4/lib/cocoapods-core/specification/set.rb:98:in `each'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-core-1.8.4/lib/cocoapods-core/specification/set.rb:98:in `each_with_object'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-core-1.8.4/lib/cocoapods-core/specification/set.rb:98:in `versions_by_source'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-core-1.8.4/lib/cocoapods-core/specification/set.rb:56:in `specification_name'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-core-1.8.4/lib/cocoapods-core/cdn_source.rb:212:in `search'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-core-1.8.4/lib/cocoapods-core/source/aggregate.rb:83:in `block in search'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-core-1.8.4/lib/cocoapods-core/source/aggregate.rb:83:in `select'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-core-1.8.4/lib/cocoapods-core/source/aggregate.rb:83:in `search'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.8.4/lib/cocoapods/resolver.rb:416:in `create_set_from_sources'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.8.4/lib/cocoapods/resolver.rb:385:in `find_cached_set'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.8.4/lib/cocoapods/resolver.rb:360:in `specifications_for_dependency'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.8.4/lib/cocoapods/resolver.rb:165:in `search_for'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.8.4/lib/cocoapods/resolver.rb:274:in `block in sort_dependencies'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.8.4/lib/cocoapods/resolver.rb:267:in `each'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.8.4/lib/cocoapods/resolver.rb:267:in `sort_by'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.8.4/lib/cocoapods/resolver.rb:267:in `sort_dependencies'
    /Library/Ruby/Gems/2.6.0/gems/molinillo-0.6.6/lib/molinillo/delegates/specification_provider.rb:53:in `block in sort_dependencies'
    /Library/Ruby/Gems/2.6.0/gems/molinillo-0.6.6/lib/molinillo/delegates/specification_provider.rb:70:in `with_no_such_dependency_error_handling'
    /Library/Ruby/Gems/2.6.0/gems/molinillo-0.6.6/lib/molinillo/delegates/specification_provider.rb:52:in `sort_dependencies'
    /Library/Ruby/Gems/2.6.0/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:754:in `push_state_for_requirements'
    /Library/Ruby/Gems/2.6.0/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:746:in `require_nested_dependencies_for'
    /Library/Ruby/Gems/2.6.0/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:729:in `activate_new_spec'
    /Library/Ruby/Gems/2.6.0/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:686:in `attempt_to_activate'
    /Library/Ruby/Gems/2.6.0/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:254:in `process_topmost_state'
    /Library/Ruby/Gems/2.6.0/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:182:in `resolve'
    /Library/Ruby/Gems/2.6.0/gems/molinillo-0.6.6/lib/molinillo/resolver.rb:43:in `resolve'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.8.4/lib/cocoapods/resolver.rb:94:in `resolve'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.8.4/lib/cocoapods/installer/analyzer.rb:986:in `block in resolve_dependencies'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.8.4/lib/cocoapods/user_interface.rb:64:in `section'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.8.4/lib/cocoapods/installer/analyzer.rb:984:in `resolve_dependencies'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.8.4/lib/cocoapods/installer/analyzer.rb:124:in `analyze'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.8.4/lib/cocoapods/installer.rb:410:in `analyze'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.8.4/lib/cocoapods/installer.rb:234:in `block in resolve_dependencies'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.8.4/lib/cocoapods/user_interface.rb:64:in `section'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.8.4/lib/cocoapods/installer.rb:233:in `resolve_dependencies'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.8.4/lib/cocoapods/installer.rb:156:in `install!'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.8.4/lib/cocoapods/command/install.rb:52:in `run'
    /Library/Ruby/Gems/2.6.0/gems/claide-1.0.3/lib/claide/command.rb:334:in `run'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.8.4/lib/cocoapods/command.rb:52:in `run'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.8.4/bin/pod:55:in `<top (required)>'
    /usr/local/bin/pod:23:in `load'
    /usr/local/bin/pod:23:in `<main>'

Error running pod install
Error launching application on iPhone 11 Pro Max.

**Comment by VladyslavBondarenko** [comment]
Hi @hisan-web 
Try https://github.com/CocoaPods/CocoaPods/issues/9319#issuecomment-561249605
does it help?
