### ISSUE TITLE
TabBarSelection does not work properly if its "values" are new objects after each build()

### ISSUE THREAD

**Issue by mehmetf** [flutter/flutter#5223]
We originally had code similar to this:

``` Dart
const _tabNames = const ["tab1", "tab2"];
final tabLabelMap = new Map<String, TabLabel>.fromIterable(_tabNames,
        value: (String value) => new TabLabel(text: value.toUpperCase()));
final tabBar = new TabBar(labels: tabLabelMap);
 return new TabBarSelection<String>(
        values: _tabNames,
        onChanged: (String value) {
          setState(() {
            selectedTabIndex = _tabNames.indexOf(value);
          });
        },
```

etc...

In the body of the selection widget, we would select which page to build based on selectedTabIndex. No matter how many times this is built, the values refer to the same objects (strings).

To make this process a bit more structured, we decided to encapsulate tabs in a separate class:

``` Dart
class TabPage {
  final String name;
  final Widget config;
  final Widget body;

  TabPage({@required this.name, this.config, @required this.body});
}
```

In the new build code, note that tabs are now driven by TabPage, rather than String.

``` Dart
    final tabLabelMap = new Map<TabPage, TabLabel>.fromIterable(tabs,
        value: (TabPage value) => new TabLabel(text: value.name.toUpperCase()));
    final tabBar = new TabBar(labels: tabLabelMap);
    return new TabBarSelection<TabPage>(
        values: tabs,
        onChanged: (TabPage value) {
          setState(() {
            selectedTab = value;
          });
        },
        child: new Scaffold(
            appBar: new AppBar(
                title: new _CompanyTitleWidget(companyId: config.companyId),
                bottom: new AppBarBottom(
                    configBar: selectedTab.config, tabBar: tabBar)),
            body: selectedTab.body));
```

This works fine as long as tabs are built in initState. If I use this pattern in a stateless widget or if I build tabs in build():

``` Dart
tabs = <TabPage>[
      new TabPage(
          name: gtString.pacing,
          config: new PacingConfigWidget(),
          body: new CompanyPacing(
              team: teamConfig.value,
              portfolio: portfolioConfig.value,
              companyId: config.companyId)),
      new TabPage(
          name: gtString.target,
          config: new TargetConfigWidget(),
          body: new CompanyTarget(
              team: teamConfig.value,
              portfolio: portfolioConfig.value,
              companyId: config.companyId)),
    ];
```

...all hell breaks loose for tab bar.
- In initial render, no tabs seem selected in the tab bar. However, first tab body is displayed properly.
- Clicking on the _second_ tab crashes the app.
- Clicking on the _first_ tab on the other hand, makes the first tab label bold; but it moves the orange selector to the second tab.
- Clicking on the second tab at that point works fine.
- After that, it works as expected.

I am attaching a video of this behavior.
[out.ogv.zip](https://github.com/flutter/flutter/files/402603/out.ogv.zip)

The trace for tapping on the second tab (probably a red herring for tabbar not being initialized correctly):

```
I/flutter : ══╡ EXCEPTION CAUGHT BY GESTURE LIBRARY ╞═══════════════════════════════════════════════════════════
I/flutter : The following NoSuchMethodError was thrown while routing a pointer event:
I/flutter : The null object does not have a method '_greaterThanFromInteger'.
I/flutter : NoSuchMethodError: method not found: '_greaterThanFromInteger'
I/flutter : Receiver: null
I/flutter : Arguments: [1]
I/flutter : When the exception was thrown, this was the stack:
I/flutter : #0      Object._noSuchMethod (dart:core-patch/object_patch.dart:44)
I/flutter : #1      Object.noSuchMethod (dart:core-patch/object_patch.dart:47)
I/flutter : #2      int.> (dart:core-patch/integers.dart:92)
I/flutter : #3      _TabBarState.handleProgressChange (package:flutter/src/material/tabs.dart:878)
I/flutter : #4      Animation&AnimationEagerListenerMixin&AnimationLocalListenersMixin.notifyListeners (package:flutter/src/animation/listener_helpers.dart:85)
I/flutter : #5      AnimationController.value= (package:flutter/src/animation/animation_controller.dart:123)
I/flutter : #6      TabBarSelectionState.value= (package:flutter/src/material/tabs.dart:634)
I/flutter : #7      _TabBarState._handleTabSelected.<anonymous closure> (package:flutter/src/material/tabs.dart:935)
I/flutter : #8      State.setState (package:flutter/src/widgets/framework.dart:775)
I/flutter : #9      _TabBarState._handleTabSelected (package:flutter/src/material/tabs.dart:934)
I/flutter : #10     _TabBarState._toTab.<anonymous closure> (package:flutter/src/material/tabs.dart:953)
I/flutter : #11     _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:161)
I/flutter : #12     TapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:148)
I/flutter : #13     TapGestureRecognizer.handlePrimaryPointer (package:flutter/src/gestures/tap.dart:94)
I/flutter : #14     PrimaryPointerGestureRecognizer.handleEvent (package:flutter/src/gestures/recognizer.dart:198)
I/flutter : #15     PointerRouter._dispatch (package:flutter/src/gestures/pointer_router.dart:73)
I/flutter : #16     PointerRouter.route (package:flutter/src/gestures/pointer_router.dart:101)
I/flutter : #17     BindingBase&SchedulerBinding&GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:133)
I/flutter : #18     BindingBase&SchedulerBinding&GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:111)
I/flutter : #19     BindingBase&SchedulerBinding&GestureBinding._handlePointerEvent (package:flutter/src/gestures/binding.dart:92)
I/flutter : #20     BindingBase&SchedulerBinding&GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:51)
I/flutter : #21     BindingBase&SchedulerBinding&GestureBinding._handlePointerPacket (package:flutter/src/gestures/binding.dart:44)
I/flutter : #22     _dispatchPointerPacket (file:///b/build/slave/Linux_Engine/build/src/out/android_debug_x86/gen/sky/bindings/dart_ui/hooks.dart:43)
I/flutter : Event:
I/flutter :   PointerUpEvent(Point(245.3, 113.3))
```

**Comment by mehmetf** [comment]
If this is intended behavior (i.e. values are expected to be the same) then please let us know and we will work around it.

**Comment by abarth** [comment]
I haven't looked at the code, but I suspect the values might need to be `operator==`.  You might want to try overriding `operator==` on your TabPage to make each one equal to its equivalent.

@HansMuller or I can look in more detail.

**Comment by mehmetf** [comment]
@abarth That worked, thanks!

It would be great if this is mentioned in the documentation: https://docs.flutter.io/flutter/material/TabBarSelection-class.html

**Comment by eseidelGoogle** [comment]
@Hixie is there a way the framework could help here?

**Comment by abarth** [comment]
I'm sure we can at least produce a better error message.

**Comment by mehmetf** [comment]
@HansMuller Is this still applicable with the new tabs implementation?

**Comment by HansMuller** [comment]
In the new tabs implementation, the TabController (nee TabBarSelection) only tracks the number of tabs, not their values. So the problem described here shouldn't come up anymore.

**Comment by eseidelGoogle** [comment]
Sounds like we should close this?

**Comment by HansMuller** [comment]
Yes we should (did).
