### ISSUE TITLE
Android App Crashes on Launch

### ISSUE THREAD

**Issue by XinwenCheng** [flutter/flutter#52230]
I checked #23545, I have very similar logcat output but I didn't use Firebase, so that solution doesn't work for me. But the behavior of APP launching is same as his, so I used the same title.

I got following error logcat output when I run this app on Android Studio 3.6.1

```shell
2020-03-09 18:34:35.335 8150-8150/com.iexplorechina.app.ClientAppV1Flutter E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.iexplorechina.app.ClientAppV1Flutter, PID: 8150
    java.lang.RuntimeException: Unable to instantiate application com.iexplorechina.app.ClientAppV1Flutter: java.lang.ClassNotFoundException: Didn't find class "com.iexplorechina.app.ClientAppV1Flutter" on path: DexPathList[[zip file "/system/framework/org.apache.http.legacy.boot.jar", zip file "/data/app/com.iexplorechina.app.ClientAppV1Flutter-wOgyfCs3DOoyvyqTq1sthQ==/base.apk"],nativeLibraryDirectories=[/data/app/com.iexplorechina.app.ClientAppV1Flutter-wOgyfCs3DOoyvyqTq1sthQ==/lib/arm64, /data/app/com.iexplorechina.app.ClientAppV1Flutter-wOgyfCs3DOoyvyqTq1sthQ==/base.apk!/lib/arm64-v8a, /system/lib64, /system/vendor/lib64]]
        at android.app.LoadedApk.makeApplication(LoadedApk.java:1136)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6193)
        at android.app.ActivityThread.access$1200(ActivityThread.java:237)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1785)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7050)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:965)
     Caused by: java.lang.ClassNotFoundException: Didn't find class "com.iexplorechina.app.ClientAppV1Flutter" on path: DexPathList[[zip file "/system/framework/org.apache.http.legacy.boot.jar", zip file "/data/app/com.iexplorechina.app.ClientAppV1Flutter-wOgyfCs3DOoyvyqTq1sthQ==/base.apk"],nativeLibraryDirectories=[/data/app/com.iexplorechina.app.ClientAppV1Flutter-wOgyfCs3DOoyvyqTq1sthQ==/lib/arm64, /data/app/com.iexplorechina.app.ClientAppV1Flutter-wOgyfCs3DOoyvyqTq1sthQ==/base.apk!/lib/arm64-v8a, /system/lib64, /system/vendor/lib64]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:134)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at android.app.AppComponentFactory.instantiateApplication(AppComponentFactory.java:50)
        at androidx.core.app.CoreComponentFactory.instantiateApplication(CoreComponentFactory.java:47)
        at android.app.Instrumentation.newApplication(Instrumentation.java:1120)
        at android.app.LoadedApk.makeApplication(LoadedApk.java:1128)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6193) 
        at android.app.ActivityThread.access$1200(ActivityThread.java:237) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1785) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:214) 
        at android.app.ActivityThread.main(ActivityThread.java:7050) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:965) 
```

No matter if I run <code>flutter clean</code> before running, still the same. 

My <code>flutter analyze</code>is:
```shell
➜  client_app_v1_flutter git:(master) ✗ flutter analyze
Analyzing client_app_v1_flutter...                                      
No issues found! (ran in 13.7s)
```

And <code>flutter doctor -v</code> is:
```shell
➜  client_app_v1_flutter git:(master) ✗ flutter doctor -v
[✓] Flutter (Channel stable, v1.12.13+hotfix.8, on Mac OS X 10.14.6 18G103, locale en-CN)
    • Flutter version 1.12.13+hotfix.8 at /Volumes/Transcend/Development/flutter
    • Framework revision 0b8abb4724 (4 weeks ago), 2020-02-11 11:44:36 -0800
    • Engine revision e1e6ced81d
    • Dart version 2.7.0

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Volumes/Transcend/Development/AndroidSDK
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.3.1, Build version 11C504
    • CocoaPods version 1.9.0

[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 44.0.2
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)

[✓] VS Code (version 1.42.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.8.1

[✓] Connected device (1 available)
    • SM G9500 • 988a1b474239545746 • android-arm64 • Android 9 (API 28)

• No issues found!
```

This flutter project runs properly on iPhone, but always crash on launching on Android device. Its Android project is already Support AndroidX. Its <code>pubspec.yaml</code> is:
```shell
name: client_app_v1_flutter
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 0.8.0

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # https://pub.dev/packages/dio
  dio: ">= 2.1.13"

  # https://pub.dev/packages/quick_log
  quick_log: ^0.4.0

  # https://pub.dev/packages/flutter_simple_rating_bar
  # flutter_simple_rating_bar: ^0.0.3

  # https://pub.dev/packages/carousel_pro
  carousel_pro: ^1.0.0

  # https://pub.dev/packages/flutter_markdown
  flutter_markdown: ^0.3.3

  # https://pub.dev/packages/permission_handler
  permission_handler: "^4.2.0+hotfix.3"

  # https://pub.dev/packages/intl
  intl: 0.16.1

  # https://pub.dev/packages/flutter_dialogflow
  # flutter_dialogflow: ^0.1.3

  # https://pub.dev/packages/package_info
  package_info: ^0.4.0+13

  # https://pub.dev/packages/data_plugin
  # https://github.com/bmob/bmob-flutter-sdk
  data_plugin: ^0.0.15

  # https://pub.dev/packages/community_material_icon
  community_material_icon: ^3.5.95

  # https://pub.dev/packages/event_bus
  event_bus: ^1.1.1

  # https://pub.dev/packages/stripe_payment
  stripe_payment: ^1.0.6

  # https://pub.dev/packages/flustars
  flustars: ^0.2.6+1

  # https://pub.dev/packages/flare_splash_screen
  flare_splash_screen: ^3.0.1

  # https://pub.dev/packages/json_annotation
  json_annotation: ^2.0.0

  # https://pub.dev/packages/video_player
  video_player: ^0.10.7

  # https://pub.dev/packages/flutter_tts
  flutter_tts: ^0.8.7

  # https://pub.dev/packages/extended_image
  extended_image: ^0.7.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  # https://pub.dev/packages/build_runner
  build_runner: ^1.7.4

  # https://pub.dev/packages/json_serializable
  json_serializable: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - images/demo_avatar_1.jpg
    - images/demo_avatar_2.jpg
    - images/i_explore_china_logo_rectangle.png
    - images/bg_splash.png
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
```

No clue where the problem is, could anyone help out on this? Thanks so much in advance!

**Comment by TahaTesser** [comment]
Hi @XinwenCheng 

This indicates you're missing a class in your native Android code 
```
     Caused by: java.lang.ClassNotFoundException: Didn't find class "com.iexplorechina.app.ClientAppV1Flutter" on path: DexPathList[[zip file "/system/framework/org.apache.http.legacy.boot.jar", zip file "/data/app/com.iexplorechina.app.ClientAppV1Flutter-wOgyfCs3DOoyvyqTq1sthQ==/base.apk"],nativeLibraryDirectories=[/data/app/com.iexplorechina.app.ClientAppV1Flutter-wOgyfCs3DOoyvyqTq1sthQ==/lib/arm64, /data/app/com.iexplorechina.app.ClientAppV1Flutter-wOgyfCs3DOoyvyqTq1sthQ==/base.apk!/lib/arm64-v8a, /system/lib64, /system/vendor/lib64]]
```

`ClientAppV1Flutter` must be missing

Please check your code and run `flutter clean` and try launching again 

Thank you

**Comment by XinwenCheng** [comment]
Hi @TahaTesser 
![image](https://user-images.githubusercontent.com/795334/76208914-9c1d9b80-623b-11ea-9ddf-9d9e0c28aee9.png)
<code>ClientAppV1Flutter</code> is my package name, I'm not sure what you mean it's missing?

After <code>flutter clean</code>, I still meet the same issue:
```shell
2020-03-09 19:32:59.074 1563-1563/? E/SDAgentPackageStateReceiver: Not going to handle 'com.iexplorechina.app.ClientAppV1Flutter'!
2020-03-09 19:32:59.129 16180-16180/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.iexplorechina.app.ClientAppV1Flutter, PID: 16180
    java.lang.RuntimeException: Unable to instantiate application com.iexplorechina.app.ClientAppV1Flutter: java.lang.ClassNotFoundException: Didn't find class "com.iexplorechina.app.ClientAppV1Flutter" on path: DexPathList[[zip file "/system/framework/org.apache.http.legacy.boot.jar", zip file "/data/app/com.iexplorechina.app.ClientAppV1Flutter-JCbEWyt6cvNagCRd1lIktQ==/base.apk"],nativeLibraryDirectories=[/data/app/com.iexplorechina.app.ClientAppV1Flutter-JCbEWyt6cvNagCRd1lIktQ==/lib/arm64, /data/app/com.iexplorechina.app.ClientAppV1Flutter-JCbEWyt6cvNagCRd1lIktQ==/base.apk!/lib/arm64-v8a, /system/lib64, /system/vendor/lib64]]
        at android.app.LoadedApk.makeApplication(LoadedApk.java:1136)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6193)
        at android.app.ActivityThread.access$1200(ActivityThread.java:237)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1785)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7050)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:965)
     Caused by: java.lang.ClassNotFoundException: Didn't find class "com.iexplorechina.app.ClientAppV1Flutter" on path: DexPathList[[zip file "/system/framework/org.apache.http.legacy.boot.jar", zip file "/data/app/com.iexplorechina.app.ClientAppV1Flutter-JCbEWyt6cvNagCRd1lIktQ==/base.apk"],nativeLibraryDirectories=[/data/app/com.iexplorechina.app.ClientAppV1Flutter-JCbEWyt6cvNagCRd1lIktQ==/lib/arm64, /data/app/com.iexplorechina.app.ClientAppV1Flutter-JCbEWyt6cvNagCRd1lIktQ==/base.apk!/lib/arm64-v8a, /system/lib64, /system/vendor/lib64]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:134)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at android.app.AppComponentFactory.instantiateApplication(AppComponentFactory.java:50)
        at androidx.core.app.CoreComponentFactory.instantiateApplication(CoreComponentFactory.java:47)
        at android.app.Instrumentation.newApplication(Instrumentation.java:1120)
        at android.app.LoadedApk.makeApplication(LoadedApk.java:1128)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6193) 
        at android.app.ActivityThread.access$1200(ActivityThread.java:237) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1785) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:214) 
        at android.app.ActivityThread.main(ActivityThread.java:7050) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:965) 
2020-03-09 19:32:59.152 16245-16245/? E/Zygote: isWhitelistProcess - Process is Whitelisted
2020-03-09 19:32:59.154 16245-16245/? E/Zygote: accessInfo : 1
2020-03-09 19:32:59.168 699-699/? E/lmkd: Error writing /proc/16180/oom_score_adj; errno=22
2020-03-09 19:32:59.187 1563-2097/? E/WindowManager: win=Window{8edd797 u0 Splash Screen com.iexplorechina.app.ClientAppV1Flutter EXITING} destroySurfaces: appStopped=false win.mWindowRemovalAllowed=true win.mRemoveOnExit=true win.mViewVisibility=0 caller=com.android.server.wm.AppWindowToken.destroySurfaces:870 com.android.server.wm.AppWindowToken.destroySurfaces:851 com.android.server.wm.WindowState.onExitAnimationDone:5406 com.android.server.wm.-$$Lambda$01bPtngJg5AqEoOWfW3rWfV7MH4.accept:2 java.util.ArrayList.forEach:1262 com.android.server.wm.AppWindowToken.onAnimationFinished:2403 com.android.server.wm.AppWindowToken.setVisibility:551 
2020-03-09 19:32:59.189 16245-16245/? E/pp.sbrowseredg: Not starting debugger since process cannot load the jdwp agent.
2020-03-09 19:32:59.379 2387-6512/? E/rs$DefaultThreadFactory: ===== Detect pool-thread leak =====
2020-03-09 19:32:59.388 16262-16262/? E/Zygote: isWhitelistProcess - Process is Whitelisted
2020-03-09 19:32:59.389 16262-16262/? E/Zygote: accessInfo : 1
2020-03-09 19:32:59.391 2387-3528/? E/rs$DefaultThreadFactory: ===== Detect pool-thread leak =====
```

**Comment by TahaTesser** [comment]
Hi @XinwenCheng 
Do you have [Enabled multidex](https://developer.android.com/studio/build/multidex)?

**Comment by XinwenCheng** [comment]
Hi @TahaTesser, not yet. I tried, but I didn't succeed yet. Let me find out a way suit for Flutter project and try again.

**Comment by XinwenCheng** [comment]
Hi @TahaTesser , then I set <code>multiDexEnabled</code> to be <code>true</code> in build.gradle file under android/app folder, and run <code>flutter clean</code>, after that I click Run button of Android Studio, still get the same error.
![image](https://user-images.githubusercontent.com/795334/76211021-48618100-6240-11ea-8e15-ec96ffeb1f1b.png)

```shell
2020-03-09 19:56:42.857 12285-12285/? E/Zygote: isWhitelistProcess - Process is Whitelisted
2020-03-09 19:56:42.858 12285-12285/? E/Zygote: accessInfo : 1
2020-03-09 19:56:43.475 12285-12285/com.iexplorechina.app.ClientAppV1Flutter E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.iexplorechina.app.ClientAppV1Flutter, PID: 12285
    java.lang.RuntimeException: Unable to instantiate application com.iexplorechina.app.ClientAppV1Flutter: java.lang.ClassNotFoundException: Didn't find class "com.iexplorechina.app.ClientAppV1Flutter" on path: DexPathList[[zip file "/system/framework/org.apache.http.legacy.boot.jar", zip file "/data/app/com.iexplorechina.app.ClientAppV1Flutter-VWwMIF8yKik4bk-gVW7FDg==/base.apk"],nativeLibraryDirectories=[/data/app/com.iexplorechina.app.ClientAppV1Flutter-VWwMIF8yKik4bk-gVW7FDg==/lib/arm64, /data/app/com.iexplorechina.app.ClientAppV1Flutter-VWwMIF8yKik4bk-gVW7FDg==/base.apk!/lib/arm64-v8a, /system/lib64, /system/vendor/lib64]]
        at android.app.LoadedApk.makeApplication(LoadedApk.java:1136)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6193)
        at android.app.ActivityThread.access$1200(ActivityThread.java:237)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1785)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7050)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:965)
     Caused by: java.lang.ClassNotFoundException: Didn't find class "com.iexplorechina.app.ClientAppV1Flutter" on path: DexPathList[[zip file "/system/framework/org.apache.http.legacy.boot.jar", zip file "/data/app/com.iexplorechina.app.ClientAppV1Flutter-VWwMIF8yKik4bk-gVW7FDg==/base.apk"],nativeLibraryDirectories=[/data/app/com.iexplorechina.app.ClientAppV1Flutter-VWwMIF8yKik4bk-gVW7FDg==/lib/arm64, /data/app/com.iexplorechina.app.ClientAppV1Flutter-VWwMIF8yKik4bk-gVW7FDg==/base.apk!/lib/arm64-v8a, /system/lib64, /system/vendor/lib64]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:134)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at android.app.AppComponentFactory.instantiateApplication(AppComponentFactory.java:50)
        at androidx.core.app.CoreComponentFactory.instantiateApplication(CoreComponentFactory.java:47)
        at android.app.Instrumentation.newApplication(Instrumentation.java:1120)
        at android.app.LoadedApk.makeApplication(LoadedApk.java:1128)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6193) 
        at android.app.ActivityThread.access$1200(ActivityThread.java:237) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1785) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:214) 
        at android.app.ActivityThread.main(ActivityThread.java:7050) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:965) 
```

**Comment by TahaTesser** [comment]
Hi @XinwenCheng 
Make sure to add this too in your dependencies  inside `build.gradle`
```
dependencies {
    implementation 'androidx.multidex:multidex:2.0.1'
}
```

**Comment by XinwenCheng** [comment]
Thank you @TahaTesser ! Refer to https://github.com/flutter/flutter/issues/21009#issuecomment-574732458, I solved this issue, but your guidance is more important than that!
