### ISSUE TITLE
WebAssetServer.start > serveDevTools crash: NoSuchMethodError: The method 'toFilePath' was called on null.

### ISSUE THREAD

**Issue by jmagman** [flutter/flutter#52269]
```
--no-color run --machine --track-widget-creation --device-id=chrome lib\main.dart
```

```
NoSuchMethodError: The method 'toFilePath' was called on null.
Receiver: null
Tried calling: toFilePath()

#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:53:5)
#1      defaultHandler (package:devtools_server/src/handlers.dart:28:60)
<asynchronous suspension>
#2      serveDevTools (package:devtools_server/src/server.dart:144:21)
#3      DevTools.start (package:dwds/src/servers/devtools.dart:27:15)
#4      Dwds.start (package:dwds/dwds.dart:111:33)
#5      WebAssetServer.start (package:flutter_tools/src/build_runner/devfs_web.dart:85:36)
<asynchronous suspension>
#6      WebDevFS.create (package:flutter_tools/src/build_runner/devfs_web.dart:460:43)
#7      _ResidentWebRunner.run.<anonymous closure> (package:flutter_tools/src/build_runner/resident_web_runner.dart:421:44)
#8      asyncGuard.<anonymous closure> (package:flutter_tools/src/base/async_guard.dart:111:32)
#9      _rootRun (dart:async/zone.dart:1126:13)
#10     _CustomZone.run (dart:async/zone.dart:1023:19)
#11     _runZoned (dart:async/zone.dart:1518:10)
#12     runZoned (dart:async/zone.dart:1502:12)
#13     asyncGuard (package:flutter_tools/src/base/async_guard.dart:109:3)
#14     _ResidentWebRunner.run (package:flutter_tools/src/build_runner/resident_web_runner.dart:411:20)
<asynchronous suspension>
#15     AppDomain.startApp.<anonymous closure> (package:flutter_tools/src/commands/daemon.dart:532:23)
#16     AppDomain.launch.<anonymous closure> (package:flutter_tools/src/commands/daemon.dart:594:26)
#17     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:29)
#18     _rootRun (dart:async/zone.dart:1126:13)
#19     _CustomZone.run (dart:async/zone.dart:1023:19)
#20     _runZoned (dart:async/zone.dart:1518:10)
#21     runZoned (dart:async/zone.dart:1465:12)
#22     AppContext.run (package:flutter_tools/src/base/context.dart:149:18)
#23     AppInstance._runInZone (package:flutter_tools/src/commands/daemon.dart:1037:20)
#24     AppDomain.launch (package:flutter_tools/src/commands/daemon.dart:592:15)
#25     AppDomain.startApp (package:flutter_tools/src/commands/daemon.dart:526:12)
#26     _rootRunUnary (dart:async/zone.dart:1134:38)
#27     _CustomZone.runUnary (dart:async/zone.dart:1031:19)
#28     _FutureListener.handleValue (dart:async/future_impl.dart:140:18)
#29     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:682:45)
#30     Future._propagateToListeners (dart:async/future_impl.dart:711:32)
#31     Future._completeWithValue (dart:async/future_impl.dart:526:5)
#32     Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:556:7)
#33     _rootRun (dart:async/zone.dart:1126:13)
#34     _CustomZone.run (dart:async/zone.dart:1023:19)
#35     _CustomZone.runGuarded (dart:async/zone.dart:925:7)
#36     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:965:23)
#37     _microtaskLoop (dart:async/schedule_microtask.dart:43:21)
#38     _startMicrotaskLoop (dart:async/schedule_microtask.dart:52:5)
#39     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
#40     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:169:5)

```

**Comment by jmagman** [comment]
https://github.com/flutter/devtools/issues/1497
