### ISSUE TITLE
[tool_crash] Invalid argument(s): A directory corresponding to fileSystemPath "C:\Users\drainaps\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\devtools-0.1.15\build" could not be found

### ISSUE THREAD

**Issue by Wishmater** [flutter/flutter#52318]
Probably the reason I got this issue is because I'm running from a different user in windows (different from the one I installed the flutter sdk from). Is there an easy way to fix this?
Profile and build mode  for web work perfectly, only debug shows this error.
Android works perfectly too.

## Command
```
flutter --no-color run --machine --track-widget-creation --device-id=chrome lib\main.dart
```

## Steps to Reproduce
1. Enable support for web
2. Create new flutter application in Android Studio
3. Select Chrome(web) as target
4. Click run

## Logs
ArgumentError: Invalid argument(s): A directory corresponding to fileSystemPath "C:\Users\drainaps\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\devtools-0.1.15\build" could not be found
```
#0      createStaticHandler (package:shelf_static/src/static_handler.dart:50:5)
#1      defaultHandler (package:devtools_server/src/handlers.dart:32:24)
<asynchronous suspension>
#2      serveDevTools (package:devtools_server/src/server.dart:144:21)
#3      DevTools.start (package:dwds/src/servers/devtools.dart:27:15)
#4      Dwds.start (package:dwds/dwds.dart:111:33)
#5      WebAssetServer.start (package:flutter_tools/src/build_runner/devfs_web.dart:85:36)
<asynchronous suspension>
#6      WebDevFS.create (package:flutter_tools/src/build_runner/devfs_web.dart:460:43)
#7      _ResidentWebRunner.run.<anonymous closure> (package:flutter_tools/src/build_runner/resident_web_runner.dart:415:44)
#8      asyncGuard.<anonymous closure> (package:flutter_tools/src/base/async_guard.dart:111:32)
#9      _rootRun (dart:async/zone.dart:1126:13)
#10     _CustomZone.run (dart:async/zone.dart:1023:19)
#11     _runZoned (dart:async/zone.dart:1518:10)
#12     runZoned (dart:async/zone.dart:1502:12)
#13     asyncGuard (package:flutter_tools/src/base/async_guard.dart:109:3)
#14     _ResidentWebRunner.run (package:flutter_tools/src/build_runner/resident_web_runner.dart:405:20)
<asynchronous suspension>
#15     AppDomain.startApp.<anonymous closure> (package:flutter_tools/src/commands/daemon.dart:517:23)
#16     AppDomain.launch.<anonymous closure> (package:flutter_tools/src/commands/daemon.dart:579:26)
```
```
[✓] Flutter (Channel master, v1.15.19-pre.9, on Microsoft Windows [Version 10.0.18362.30], locale en-US)
    • Flutter version 1.15.19-pre.9 at C:\Workspaces\Flutter\sdk\flutter
    • Framework revision e13e17009d (3 days ago), 2020-03-06 21:38:35 -0800
    • Engine revision 5aff311948
    • Dart version 2.8.0 (build 2.8.0-dev.12.0 9983424a3c)

[!] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at C:/Workspaces/Android/android-sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.3
    • ANDROID_HOME = C:/Workspaces/Android/android-sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)
    ✗ Android license status unknown.
      Try re-installing or updating your Android SDK Manager.
      See https://developer.android.com/studio/#downloads or visit https://flutter.dev/setup/#android-setup for detailed instructions.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[✓] Android Studio (version 3.5)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 44.0.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)

[!] IntelliJ IDEA Ultimate Edition (version 2019.3)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA 2019.3.3
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.dev/intellij-setup/#installing-the-plugins

[✓] Connected device (3 available)
    • SM G611M   • 330037455af055af • android-arm    • Android 9 (API 28)
    • Chrome     • chrome           • web-javascript • Google Chrome 80.0.3987.132
    • Web Server • web-server       • web-javascript • Flutter Tools

! Doctor found issues in 2 categories.

```

## Flutter Application Metadata
**Version**: 1.0.0+1
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null

**Comment by VladyslavBondarenko** [comment]
Hi @Wishmater 
Is it the same after running `flutter pub cache repair`?
Does the folder `C:\Users\drainaps\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\devtools-0.1.15\build` exist? 
(on Windows I have `Pub` folder in `AppData/Roaming` but not in `AppData/Local`)

**Comment by Wishmater** [comment]
I tried running  flutter pub cache repair  and it still shows the same error.
The folder C:\Users\drainaps\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\devtools-0.1.15\build does not exist, since that user was deleted.

**Comment by jonahwilliams** [comment]
Fixed via https://github.com/flutter/flutter/commit/88b39402ac9db69c861940a48b6519020bff92ca

**Comment by nstrelow** [comment]
Fixed it myself via:
```
pub cache add devtools --version "0.1.15"
```
