### ISSUE TITLE
PlatformView crash on Android

### ISSUE THREAD

**Issue by andre-arsenault** [flutter/flutter#52320]
Sadly I cannot provide reproducible steps for this issue. This crash happened after running my app for just over an hour of active use while connected to the Android Studio debugger.

I am filing this issue mainly to see if there is any general guidance to resolve issues such as this, or to see if other users are experiencing the same issue and can provide better repro steps.

<details>
  <summary>Logs</summary>

Crash Callstack:

```
2020-03-09 16:28:04.873 4857-4857/[myapp] E/flutter: [ERROR:flutter/shell/platform/android/platform_view_android_jni.cc(39)] java.lang.IllegalArgumentException: array == null
        at android.opengl.Matrix.multiplyMM(Native Method)
        at io.flutter.view.AccessibilityBridge$SemanticsNode.updateRecursively(AccessibilityBridge.java:2096)
        at io.flutter.view.AccessibilityBridge$SemanticsNode.updateRecursively(AccessibilityBridge.java:2143)
        at io.flutter.view.AccessibilityBridge$SemanticsNode.updateRecursively(AccessibilityBridge.java:2143)
        at io.flutter.view.AccessibilityBridge$SemanticsNode.access$4300(AccessibilityBridge.java:1760)
        at io.flutter.view.AccessibilityBridge.updateSemantics(AccessibilityBridge.java:1276)
        at io.flutter.view.AccessibilityBridge$1.updateSemantics(AccessibilityBridge.java:278)
        at io.flutter.embedding.engine.FlutterJNI.updateSemantics(FlutterJNI.java:438)
        at android.os.MessageQueue.nativePollOnce(Native Method)
        at android.os.MessageQueue.next(MessageQueue.java:336)
        at android.os.Looper.loop(Looper.java:174)
        at android.app.ActivityThread.main(ActivityThread.java:7682)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:516)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)
2020-03-09 16:28:04.873 4857-4857/[myapp] A/flutter: [FATAL:flutter/shell/platform/android/platform_view_android_jni.cc(95)] Check failed: CheckException(env). 
2020-03-09 16:28:05.454 4857-4857/[myapp] A/libc: Fatal signal 6 (SIGABRT), code -6 (SI_TKILL) in tid 4857 ([myapp]), pid 4857 ([myapp])
```

`flutter analyze` output:

```
No issues found! (ran in 7.9s)
```

`flutter doctor -v` output:

```
[✓] Flutter (Channel beta, v1.14.6, on Mac OS X 10.15.3 19D76, locale en-US)
    • Flutter version 1.14.6 at /Users/andre/Development/flutter
    • Framework revision fabeb2a16f (6 weeks ago), 2020-01-28 07:56:51 -0800
    • Engine revision c4229bfbba
    • Dart version 2.8.0 (build 2.8.0-dev.5.0 fc3af737c7)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/andre/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.3.1, Build version 11C504
    • CocoaPods version 1.8.4

[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 44.0.2
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)

[✓] VS Code (version 1.43.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.8.1

[✓] Connected device (1 available)
    • ANE LX1                 • 9WVDU18927009114          • android-arm64 • Android 9 (API 28)

• No issues found!
```

</details>

### PlatformView use in this App

We use PlatformView in two ways:

1. `webview_flutter` plugin to display web pages.
1. A custom plugin to render banner ads as Widgets within scrollable containers (ads in a scrolling news feed).

Our custom plugin uses the Fyber Fairbid SDK as our primary mediation platform, with the Google AdMob, IronSource, Facebook Audience Network and Vungle native ad SDKs also integrated.

The app is not yet live in the app stores, so I cannot comment on the rarity of this issue or number of users affected. I will update the issue when I have more information.

**Comment by VladyslavBondarenko** [comment]
Related to https://github.com/flutter/flutter/issues/31139, https://github.com/flutter/flutter/issues/45218

**Comment by darshankawar** [comment]
Hi @andre-arsenault,
Would you have more details on this issue ? or have you seen the crash recently on latest versions (eg: stable, master) ?
Thanks

**Comment by andre-arsenault** [comment]
Good question @darshankawar, as this issue is quite old now. No I don't have any additional details, nor have we seen any similar crashes from real customers since we launched the app.

We have been working in the `stable` branch since Flutter 1.20.0 (we were in `beta` before) and haven't seen this come up again. It's possible it's been fixed on the Flutter end, or on our end (the custom plugin) since this issue was reported. I'll post an update if it recurs or I get additional details.

Thanks.

**Comment by darshankawar** [comment]
Thanks @andre-arsenault for your reply. 
Given that you didn't see the crash lately, I am going ahead and closing this as non-issue. If you disagree, write in comments and I'll reopen.
If you encounter same crash again, please consider filing a new issue with all required details.
