### ISSUE TITLE
[tool_crash] Bad state: No element

### ISSUE THREAD

**Issue by amrabdelaal** [flutter/flutter#52323]
## Command
```
flutter --no-color run --machine --track-widget-creation --device-id=9FAB38A8-BD9E-4F6C-82DD-3AAD911AB22C --start-paused lib/main.dart
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
StateError: Bad state: No element
```
#0      Stream.first.<anonymous closure> (dart:async/stream.dart:1258:13)
#1      _rootRun (dart:async/zone.dart:1122:38)
#2      _CustomZone.run (dart:async/zone.dart:1023:19)
#3      _CustomZone.runGuarded (dart:async/zone.dart:925:7)
#4      _BufferingStreamSubscription._sendDone.sendDone (dart:async/stream_impl.dart:392:13)
#5      _BufferingStreamSubscription._sendDone (dart:async/stream_impl.dart:402:15)
#6      _BufferingStreamSubscription._close (dart:async/stream_impl.dart:286:7)
#7      _SyncBroadcastStreamController._sendDone.<anonymous closure> (dart:async/broadcast_stream_controller.dart:399:22)
#8      _BroadcastStreamController._forEachListener (dart:async/broadcast_stream_controller.dart:326:15)
#9      _SyncBroadcastStreamController._sendDone (dart:async/broadcast_stream_controller.dart:398:7)
#10     _BroadcastStreamController.close (dart:async/broadcast_stream_controller.dart:274:5)
#11     _rootRun (dart:async/zone.dart:1122:38)
#12     _CustomZone.run (dart:async/zone.dart:1023:19)
#13     _CustomZone.runGuarded (dart:async/zone.dart:925:7)
#14     _BufferingStreamSubscription._sendDone.sendDone (dart:async/stream_impl.dart:392:13)
#15     _BufferingStreamSubscription._sendDone (dart:async/stream_impl.dart:402:15)
#16     _BufferingStreamSubscription._close (dart:async/stream_impl.dart:286:7)
#17     _SinkTransformerStreamSubscription._close (dart:async/stream_transformers.dart:98:11)
#18     _EventSinkWrapper.close (dart:async/stream_transformers.dart:25:11)
#19     _HandlerEventSink.close (dart:async/stream_transformers.dart:254:12)
```
```
[✓] Flutter (Channel dev, v1.15.18, on Mac OS X 10.14.6 18G2022, locale en-DE)
    • Flutter version 1.15.18 at /Users/aabdelaal/Desktop/flutter/flutter
    • Framework revision 9437639590 (4 days ago), 2020-03-06 10:24:23 -0800
    • Engine revision 5aff311948
    • Dart version 2.8.0 (build 2.8.0-dev.12.0 9983424a3c)

[!] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/aabdelaal/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.3
    • Java binary at: /Library/Java/JavaVirtualMachines/jdk-13.0.2.jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 13.0.2+8)
    ✗ Android license status unknown.
      Try re-installing or updating your Android SDK Manager.
      See https://developer.android.com/studio/#downloads or visit https://flutter.dev/setup/#android-setup for detailed instructions.

[✓] Xcode - develop for iOS and macOS (Xcode 11.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.3.1, Build version 11C504
    • CocoaPods version 1.8.4

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/setup/#android-setup for detailed instructions).

[!] IntelliJ IDEA Ultimate Edition (version 2019.3.3)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.dev/intellij-setup/#installing-the-plugins

[✓] VS Code (version 1.43.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.7.1

[✓] Connected device (2 available)
    • SM G950F          • ce031713faa0cc540c                   • android-arm64 • Android 9 (API 28)
    • iPhone 11 Pro Max • 9FAB38A8-BD9E-4F6C-82DD-3AAD911AB22C • ios           • com.apple.CoreSimulator.SimRuntime.iOS-13-3 (simulator)

! Doctor found issues in 3 categories.

```

## Flutter Application Metadata
**Version**: 1.0.0+1
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null

**Comment by VladyslavBondarenko** [comment]
Hi @amrabdelaal 
To better address the issue, would be helpful
if you could post a minimal complete code sample to reproduce the problem
Thank you

**Comment by TahaTesser** [comment]
Hi @amrabdelaal 
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore
reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any
more information for us; we will reopen it right away!
Thanks for your contribution.
