### ISSUE TITLE
Changing MaterialApp to CupertinoApp exceptions on routes.

### ISSUE THREAD

**Issue by abalta** [flutter/flutter#52346]
Hi, I have changed my flutter app from MaterialApp to CupertinoApp. It has error on routes.

Tested on Android Device and Android Emulator.

Following codes works with MaterialApp.

```
import 'package:flutter/material.dart';
import 'package:wasd/onboarding.dart';
import 'strings.dart';

void main() => runApp(WASD());

class WASD extends StatelessWidget {
  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: Strings.appTitle,
      initialRoute: Strings.navOnboarding,
      routes: {
        Strings.navOnboarding: (context) => Onboarding()
      },
    );
  }
}
```

However, when I changed to CupertinoApp like following. It shows error.

```
import 'package:flutter/cupertino.dart';
import 'package:wasd/onboarding.dart';
import 'strings.dart';

void main() => runApp(WASD());

class WASD extends StatelessWidget {
  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return CupertinoApp(
      title: Strings.appTitle,
      initialRoute: Strings.navOnboarding,
      routes: {
        Strings.navOnboarding: (context) => Onboarding()
      },
    );
  }
}
```

<details>
  <summary>Logs</summary>

```
Performing hot reload...
Syncing files to device Android SDK built for x86...

════════ Exception caught by widgets library ═══════════════════════════════════════════════════════
The following assertion was thrown building Builder(dirty, dependencies: [CupertinoUserInterfaceLevel, _InheritedCupertinoTheme]):
Either the home property must be specified, or the routes table must include an entry for "/", or there must be on onGenerateRoute callback specified, or there must be an onUnknownRoute callback specified, or the builder property must be specified, because otherwise there is nothing to fall back on if the app is started with an intent that specifies an unknown route.
'package:flutter/src/widgets/app.dart':
Failed assertion: line 178 pos 10: 'builder != null ||
         home != null ||
         routes.containsKey(Navigator.defaultRouteName) ||
         onGenerateRoute != null ||
         onUnknownRoute != null'


Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=BUG.md

The relevant error-causing widget was: 
  CupertinoApp file:///Users/abdullahbalta/StudioProjects/wasd-flutter/lib/main.dart:11:12
When the exception was thrown, this was the stack: 
#2      new WidgetsApp (package:flutter/src/widgets/app.dart:178:10)
#3      _CupertinoAppState.build.<anonymous closure> (package:flutter/src/cupertino/app.dart:278:22)
#4      Builder.build (package:flutter/src/widgets/basic.dart:6757:41)
#5      StatelessElement.build (package:flutter/src/widgets/framework.dart:4291:28)
#6      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4223:15)
...
════════════════════════════════════════════════════════════════════════════════════════════════════
Reloaded 1 of 639 libraries in 418ms.
```
</details>

<details>
  <summary>strings.dart</summary>

```
class Strings {

  static String appTitle = "WASD";

  //routes
  static String navOnboarding = '/onboarding';

}
```
</details>

So, assertion error message is very clear, but why this is not working?

**Comment by VladyslavBondarenko** [comment]
Hi @abalta 
If you are using `/` symbol in the beginning of your routes, you need to implement route `/` as well.
([For Navigator](https://api.flutter.dev/flutter/widgets/Navigator/initialRoute.html)).
For MaterialApp [Intermediate routes aren't required to exist](https://api.flutter.dev/flutter/material/MaterialApp/initialRoute.html).
For CupertinoApp [it's said the same](https://api.flutter.dev/flutter/cupertino/CupertinoApp/initialRoute.html), while it's not so.
It may be a documentation issue

Any way this should fix your problem

```
routes: {
        '/': (context) => Onboarding(),
        Strings.navOnboarding: (context) => Onboarding()
      },
```

**Comment by abalta** [comment]
> Hi @abalta
> If you are using `/` symbol in the beginning of your routes, you need to implement route `/` as well.
> ([For Navigator](https://api.flutter.dev/flutter/widgets/Navigator/initialRoute.html)).
> For MaterialApp [Intermediate routes aren't required to exist](https://api.flutter.dev/flutter/material/MaterialApp/initialRoute.html).
> For CupertinoApp [it's said the same](https://api.flutter.dev/flutter/cupertino/CupertinoApp/initialRoute.html), while it's not so.
> It may be a documentation issue
> 
> Any way this should fix your problem
> 
> ```
> routes: {
>         '/': (context) => Onboarding(),
>         Strings.navOnboarding: (context) => Onboarding()
>       },
> ```

Hi @VladyslavBondarenko when I implement like that, Onboarding() page shows twice. I accually want to do when user skips the onboarding page, it never shows again.

**Comment by VladyslavBondarenko** [comment]
@abalta my bad. The page was shown twice, because `/` is considered as intermediate route in `/onboarding` route. 
If you still want to use it as initial, you can then set initialRoute to `onboarding` (without `/`). But I would advice you to rename `/onboarding` to `/` in order to have `/` as initial route

**Comment by chunhtai** [comment]
This should also throw error in MaterialApp. The different between MaterialApp and CupertinoApp is MaterialApp always provide a builder, so the build is not null. I am not sure if this assert is still checking what it suppose to check. The reason it check the builder is for cases where user provides their own navigator. However, the default builder for MaterialApp is for AnimatedTheme. Maybe we should move the assert to MaterialApp?

@HansMuller @shihaohong any thoughts?

**Comment by darshankawar** [comment]
Issue is replicable on latest `dev channel (1.20.0-0.0.pre)`.

**Comment by exaby73** [comment]
This issue is still replicable in latest stable and master.

<details><summary>Logs</summary>

```
══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
The following assertion was thrown building Builder(dirty, dependencies:
[CupertinoUserInterfaceLevel, _InheritedCupertinoTheme]):
Either the home property must be specified, or the routes table must include an entry for "/", or
there must be on onGenerateRoute callback specified, or there must be an onUnknownRoute callback
specified, or the builder property must be specified, because otherwise there is nothing to fall
back on if the app is started with an intent that specifies an unknown route.
'package:flutter/src/widgets/app.dart':
Failed assertion: line 351 pos 10: 'builder != null ||
         home != null ||
         routes.containsKey(Navigator.defaultRouteName) ||
         onGenerateRoute != null ||
         onUnknownRoute != null'
```

</details>

<details><summary>Code sample</summary>

```dart
import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return CupertinoApp(
      title: 'Flutter Demo',
      initialRoute: 'onboarding',
      routes: {
        '/onboarding': (context) => const MyHomePage(),
      },
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({Key? key}) : super(key: key);

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  int _counter = 0;

  void _incrementCounter() {
    setState(() {
      _counter++;
    });
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            const Text(
              'You have pushed the button this many times:',
            ),
            Text(
              '$_counter',
              style: Theme.of(context).textTheme.headline4,
            ),
          ],
        ),
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: _incrementCounter,
        tooltip: 'Increment',
        child: const Icon(Icons.add),
      ),
    );
  }
}
```

</details>

<details><summary><code>flutter doctor -v</code> (Stable)</summary>

```
[✓] Flutter (Channel stable, 3.0.1, on macOS 12.4 21F79 darwin-arm, locale en-US)
    • Flutter version 3.0.1 at /Users/nabeelparkar/fvm/versions/stable
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision fb57da5f94 (11 days ago), 2022-05-19 15:50:29 -0700
    • Engine revision caaafc5604
    • Dart version 2.17.1
    • DevTools version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
    • Android SDK at /Users/nabeelparkar/Library/Android/sdk/
    • Platform android-32, build-tools 32.1.0-rc1
    • ANDROID_SDK_ROOT = /Users/nabeelparkar/Library/Android/sdk/
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.4)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • CHROME_EXECUTABLE = /Applications/Brave Browser.app/Contents/MacOS/Brave Browser

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] IntelliJ IDEA Ultimate Edition (version 2022.1.1)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 67.1.4
    • Dart plugin version 221.5591.58

[✓] VS Code (version 1.67.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.40.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-arm64   • macOS 12.4 21F79 darwin-arm
    • Chrome (web)    • chrome • web-javascript • Brave Browser 102.1.39.111

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

</details>

<details><summary><code>flutter doctor -v</code> (Master)</summary>

```
[✓] Flutter (Channel master, 3.1.0-0.0.pre.1014, on macOS 12.4 21F79 darwin-arm, locale en-US)
    • Flutter version 3.1.0-0.0.pre.1014 at /Users/nabeelparkar/fvm/versions/master
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 08e61c3be2 (2 hours ago), 2022-05-31 00:18:09 -0400
    • Engine revision 693f95391e
    • Dart version 2.18.0 (build 2.18.0-152.0.dev)
    • DevTools version 2.13.1

[✓] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
    • Android SDK at /Users/nabeelparkar/Library/Android/sdk/
    • Platform android-32, build-tools 32.1.0-rc1
    • ANDROID_SDK_ROOT = /Users/nabeelparkar/Library/Android/sdk/
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.4)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • CHROME_EXECUTABLE = /Applications/Brave Browser.app/Contents/MacOS/Brave Browser

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] IntelliJ IDEA Ultimate Edition (version 2022.1.1)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 67.1.4
    • Dart plugin version 221.5591.58

[✓] VS Code (version 1.67.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.40.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-arm64   • macOS 12.4 21F79 darwin-arm
    • Chrome (web)    • chrome • web-javascript • Brave Browser 102.1.39.111

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

</details>
