### ISSUE TITLE
Failed to gclient sync engine from v1.12.13-hotfixes

### ISSUE THREAD

**Issue by xujim** [flutter/flutter#52387]
## Steps to Reproduce
hi, I try to compile flutter engine tagged v1.12.13-hotfixes by myself according to the document at :https://github.com/flutter/flutter/wiki/Compiling-the-engine
However, failed when running gclient sync again. the following is the error log output:

```
flutter git:(v1.12.13-hotfixes) gclient sync
/Users/yujie/Desktop/FlutterWork/Engine_github/.gclient_entries missing, .gclient file in parent directory /Users/yujie/Desktop/FlutterWork/Engine_github might not be the file you want to use.


src/flutter (ERROR)
----------------------------------------
[0:00:00] Started.
[0:00:00] ________ unmanaged solution; skipping src/flutter
[0:00:00] Finished running: git rev-parse --verify HEAD
----------------------------------------
Traceback (most recent call last):
  File "/Users/yujie/depot_tools/metrics.py", line 267, in print_notice_and_exit
    yield
  File "/Users/yujie/depot_tools/gclient.py", line 3179, in <module>
    sys.exit(main(sys.argv[1:]))
  File "/Users/yujie/depot_tools/gclient.py", line 3165, in main
    return dispatcher.execute(OptionParser(), argv)
  File "/Users/yujie/depot_tools/subcommand.py", line 252, in execute
    return command(parser, args[1:])
  File "/Users/yujie/depot_tools/gclient.py", line 2723, in CMDsync
    ret = client.RunOnDeps('update', args)
  File "/Users/yujie/depot_tools/gclient.py", line 1767, in RunOnDeps
    patch_refs=patch_refs, target_branches=target_branches)
  File "/Users/yujie/depot_tools/gclient_utils.py", line 937, in flush
    reraise(e[0], e[1], e[2])
  File "/Users/yujie/depot_tools/gclient_utils.py", line 1014, in run
    self.item.run(*self.args, **self.kwargs)
  File "/Users/yujie/depot_tools/gclient.py", line 964, in run
    self.ParseDepsFile()
  File "/Users/yujie/depot_tools/gclient.py", line 724, in ParseDepsFile
    deps_content, filepath, self.get_vars(), self.get_builtin_vars())
  File "/Users/yujie/depot_tools/gclient_eval.py", line 473, in Parse
    result = Exec(content, filename, vars_override, builtin_vars)
  File "/Users/yujie/depot_tools/gclient_eval.py", line 379, in Exec
    value = _gclient_eval(node, filename, vars_dict)
  File "/Users/yujie/depot_tools/gclient_eval.py", line 303, in _gclient_eval
    return _convert(node_or_string)
  File "/Users/yujie/depot_tools/gclient_eval.py", line 259, in _convert
    key, filename, getattr(key_node, 'lineno', '<unknown>')))
ValueError: duplicate key in dictionary: src/third_party/dart/tools/sdks (file '/Users/yujie/Desktop/FlutterWork/Engine_github/src/flutter/DEPS', line 497)
```

1. create engine dir and src subdir by mkdir command. create .gclient file and add the configuration totally according to the <Compiling the engine>
2. Because I need use the engine of v1.12.13-hotfixes tagged, so I switch to  v1.12.13-hotfixes in source tree
3. run the gclient sync command again, but met problem mentioned above
I had compiled the engine before in this way, but failed this time. Could you help? thanks.
By the way, I have updated depot_tool.

```
Flutter (Channel v1.12.13-hotfixes, v1.12.13+hotfix.8, on Mac OS X 10.14.6
    18G95, locale zh-Hans-CN)
    • Flutter version 1.12.13+hotfix.8 at
      /Users/yujie/Desktop/FlutterWork/flutter_Github
    • Framework revision 0b8abb4724 (4 周前), 2020-02-11 11:44:36 -0800
    • Engine revision e1e6ced81d
    • Dart version 2.7.0
```

**Comment by xujim** [comment]
Seems I should not update the depot. The latest depot_tool will trigger this error.
To fix it, just roll back depot_tool.

**Comment by jason-simmons** [comment]
This was fixed by https://github.com/flutter/engine/commit/7df0a6e35e5c1a4e541fb53538bc527daa41ba7c

You can cherry pick that into the engine from `v1.12.13-hotfixes` to build it with the current depot_tools.

**Comment by xujim** [comment]
@jason-simmons ok, thanks
