### ISSUE TITLE
Getting error: BoxConstraints(0.0<=w<=Infinity, h=Infinity), but I have Container( height: 88, width: 375,

### ISSUE THREAD

**Issue by gcoleson** [flutter/flutter#52412]
Getting Error on line with "child: Row(" at the end of this code snippet, seems like I should not get it since the Container has height=88, width=375, thoughts?

```dart
   return Scaffold(
      body: Container(
        constraints: BoxConstraints.expand(),
        decoration: BoxDecoration(
          color: Color.fromARGB(255, 255, 255, 255),
        ),
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.stretch,
          children: [
            Container(
              height: 88,
              width: 375,
              child: Stack(
                alignment: Alignment.bottomCenter,
                children: [
                  Positioned(
                    bottom: -1,
                    child: Image.asset(
                      "assets/images/logo.png",
                      fit: BoxFit.none,
                    ),
                  ),
                  Positioned(
                    left: 17,
                    right: 24,
                    bottom: 2,
                    child: Row(
                      crossAxisAlignment: CrossAxisAlignment.stretch,
                      children: [
```

```
flutter: ══╡ EXCEPTION CAUGHT BY RENDERING LIBRARY ╞═════════════════════════════════════════════════════════
[        ] flutter: The following assertion was thrown during performLayout():
[        ] flutter: BoxConstraints forces an infinite height.
[        ] flutter: These invalid constraints were provided to RenderPositionedBox's layout() function by the following
[        ] flutter: function, which probably computed the invalid constraints in question:
[        ] flutter:   RenderFlex.performLayout (package:flutter/src/rendering/flex.dart:744:15)
[        ] flutter: The offending constraints were:
[        ] flutter:   BoxConstraints(0.0<=w<=Infinity, h=Infinity)
[        ] flutter:
[        ] flutter: The relevant error-causing widget was:
[        ] flutter:   Row
[        ] flutter:   file:///Users/*/code/flutter/financeapponescreen/lib/feed1_widget/feed1_widget.dart:45:28
[        ] flutter:
[        ] flutter: When the exception was thrown, this was the stack:
[        ] flutter: #0      BoxConstraints.debugAssertIsValid.<anonymous closure>.throwError (package:flutter/src/rendering/box.dart:510:9)
[        ] flutter: #1      BoxConstraints.debugAssertIsValid.<anonymous closure> (package:flutter/src/rendering/box.dart:554:21)
[        ] flutter: #2      BoxConstraints.debugAssertIsValid (package:flutter/src/rendering/box.dart:558:6)
[        ] flutter: #3      RenderObject.layout (package:flutter/src/rendering/object.dart:1624:24)
[        ] flutter: #4      RenderFlex.performLayout (package:flutter/src/rendering/flex.dart:744:15)
[        ] flutter: #5      RenderObject.layout (package:flutter/src/rendering/object.dart:1724:7)
[        ] flutter: #6      RenderStack.performLayout (package:flutter/src/rendering/stack.dart:544:15)
[        ] flutter: #7      RenderObject.layout (package:flutter/src/rendering/object.dart:1724:7)
[        ] flutter: #8      RenderConstrainedBox.performLayout (package:flutter/src/rendering/proxy_box.dart:259:13)
[        ] flutter: #9      RenderObject.layout (package:flutter/src/rendering/object.dart:1724:7)
[        ] flutter: #10     RenderFlex.performLayout (package:flutter/src/rendering/flex.dart:744:15)
[        ] flutter: #11     RenderObject.layout (package:flutter/src/rendering/object.dart:1724:7)
[        ] flutter: #12     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
[        ] flutter: #13     RenderObject.layout (package:flutter/src/rendering/object.dart:1724:7)
[        ] flutter: #14     RenderConstrainedBox.performLayout (package:flutter/src/rendering/proxy_box.dart:259:13)
[        ] flutter: #15     RenderObject.layout (package:flutter/src/rendering/object.dart:1724:7)
[        ] flutter: #16     MultiChildLayoutDelegate.layoutChild (package:flutter/src/rendering/custom_layout.dart:163:11)
[        ] flutter: #17     _ScaffoldLayout.performLayout (package:flutter/src/material/scaffold.dart:477:7)
[        ] flutter: #18     MultiChildLayoutDelegate._callPerformLayout (package:flutter/src/rendering/custom_layout.dart:232:7)
[        ] flutter: #19     RenderCustomMultiChildLayoutBox.performLayout (package:flutter/src/rendering/custom_layout.dart:391:14)
[        ] flutter: #20     RenderObject.layout (package:flutter/src/rendering/object.dart:1724:7)
[        ] flutter: #21     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
[        ] flutter: #22     RenderObject.layout (package:flutter/src/rendering/object.dart:1724:7)
[        ] flutter: #23     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
[        ] flutter: #24     _RenderCustomClip.performLayout (package:flutter/src/rendering/proxy_box.dart:1232:11)
[        ] flutter: #25     RenderObject.layout (package:flutter/src/rendering/object.dart:1724:7)
[        ] flutter: #26     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
[        ] flutter: #27     RenderObject.layout (package:flutter/src/rendering/object.dart:1724:7)
[        ] flutter: #28     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
[        ] flutter: #29     RenderObject.layout (package:flutter/src/rendering/object.dart:1724:7)
[        ] flutter: #30     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
[        ] flutter: #31     RenderObject.layout (package:flutter/src/rendering/object.dart:1724:7)
[        ] flutter: #32     RenderStack.performLayout (package:flutter/src/rendering/stack.dart:505:15)
[        ] flutter: #33     RenderObject.layout (package:flutter/src/rendering/object.dart:1724:7)
[        ] flutter: #34     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
[        ] flutter: #35     RenderObject.layout (package:flutter/src/rendering/object.dart:1724:7)
[        ] flutter: #36     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
[        ] flutter: #37     RenderObject.layout (package:flutter/src/rendering/object.dart:1724:7)
[        ] flutter: #38     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
[        ] flutter: #39     RenderObject.layout (package:flutter/src/rendering/object.dart:1724:7)
[        ] flutter: #40     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
[        ] flutter: #41     RenderObject.layout (package:flutter/src/rendering/object.dart:1724:7)
[        ] flutter: #42     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
[        ] flutter: #43     RenderObject.layout (package:flutter/src/rendering/object.dart:1724:7)
[        ] flutter: #44     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
[        ] flutter: #45     RenderOffstage.performLayout (package:flutter/src/rendering/proxy_box.dart:3168:13)
[        ] flutter: #46     RenderObject.layout (package:flutter/src/rendering/object.dart:1724:7)
[        ] flutter: #47     RenderStack.performLayout (package:flutter/src/rendering/stack.dart:505:15)
[        ] flutter: #48     RenderObject.layout (package:flutter/src/rendering/object.dart:1724:7)
[        ] flutter: #49     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
[        ] flutter: #50     RenderObject.layout (package:flutter/src/rendering/object.dart:1724:7)
[        ] flutter: #51     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
[        ] flutter: #52     RenderObject.layout (package:flutter/src/rendering/object.dart:1724:7)
[        ] flutter: #53     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
[        ] flutter: #54     RenderObject.layout (package:flutter/src/rendering/object.dart:1724:7)
[        ] flutter: #55     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
[        ] flutter: #56     RenderObject.layout (package:flutter/src/rendering/object.dart:1724:7)
[        ] flutter: #57     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
[        ] flutter: #58     RenderObject.layout (package:flutter/src/rendering/object.dart:1724:7)
[        ] flutter: #59     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
[        ] flutter: #60     RenderObject.layout (package:flutter/src/rendering/object.dart:1724:7)
[        ] flutter: #61     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
[        ] flutter: #62     RenderObject.layout (package:flutter/src/rendering/object.dart:1724:7)
[        ] flutter: #63     RenderView.performLayout (package:flutter/src/rendering/view.dart:167:13)
[        ] flutter: #64     RenderObject._layoutWithoutResize (package:flutter/src/rendering/object.dart:1584:7)
[        ] flutter: #65     PipelineOwner.flushLayout (package:flutter/src/rendering/object.dart:844:18)
[        ] flutter: #66     RendererBinding.drawFrame (package:flutter/src/rendering/binding.dart:344:19)
[        ] flutter: #67     WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:774:13)
[        ] flutter: #68     RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:283:5)
[        ] flutter: #69     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1102:15)
[        ] flutter: #70     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1041:9)
[        ] flutter: #71     SchedulerBinding.scheduleWarmUpFrame.<anonymous closure> (package:flutter/src/scheduler/binding.dart:850:7)
[        ] flutter: #80     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:384:19)
[        ] flutter: #81     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:418:5)
[        ] flutter: #82     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:174:12)
[        ] flutter: (elided 8 frames from package dart:async and package dart:async-patch)
[        ] flutter:
[        ] flutter: The following RenderObject was being processed when the exception was fired: RenderFlex#a3ed8 relayoutBoundary=up1
NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE:
[        ] flutter:   creator: Row ← Positioned ← Stack ← ConstrainedBox ← Container ← Column ← DecoratedBox ←
[        ] flutter:     ConstrainedBox ← Container ← _BodyBuilder ← MediaQuery ← LayoutId-[<_ScaffoldSlot.body>] ← ⋯
[        ] flutter:   parentData: right=24.0; bottom=2.0; left=17.0; offset=Offset(0.0, 0.0) (can use size)
[        ] flutter:   constraints: BoxConstraints(w=373.0, 0.0<=h<=Infinity)
[        ] flutter:   size: MISSING
[        ] flutter:   direction: horizontal
[        ] flutter:   mainAxisAlignment: start
[        ] flutter:   mainAxisSize: max
[        ] flutter:   crossAxisAlignment: stretch
[        ] flutter:   textDirection: ltr
[        ] flutter:   verticalDirection: down
[        ] flutter: This RenderObject had the following descendants (showing up to depth 5):
[        ] flutter:     child 1: RenderPositionedBox#e9830 NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
[        ] flutter:       child: RenderPadding#01388 NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
[        ] flutter:         child: RenderConstrainedBox#36552 NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
[        ] flutter:           child: RenderSemanticsAnnotations#a9822 NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
[        ] flutter:             child: RenderImage#60385 NEEDS-LAYOUT NEEDS-PAINT
[        ] flutter:     child 2: RenderConstrainedBox#7e8ba NEEDS-LAYOUT NEEDS-PAINT
[        ] flutter:     child 3: RenderPositionedBox#35984 NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
[        ] flutter:       child: RenderParagraph#02e06 NEEDS-LAYOUT NEEDS-PAINT
[        ] flutter:         text: TextSpan
[        ] flutter: ════════════════════════════════════════════════════════════════════════════════════════════════════
[        ] flutter: Another exception was thrown: RenderBox was not laid out: RenderFlex#a3ed8 relayoutBoundary=up1 NEEDS-PAINT
NEEDS-COMPOSITING-BITS-UPDATE
[        ] [DEVICE LOG] 2020-03-11 10:39:08.597171-0400  localhost Runner[77777]: (Flutter) flutter: Another exception was thrown:
NoSuchMethodError: The method '>' was called on null.
[        ] flutter: Another exception was thrown: NoSuchMethodError: The method '>' was called on null.
[   +4 ms] <- compile package:financeapponescreen/main.dart
[  +57 ms] [DEVICE LOG] 2020-03-11 10:39:08.661997-0400  localhost Runner[77777]: (Flutter) flutter: Another exception was thrown: RenderBox
was not laid out: RenderFlex#a3ed8 relayoutBoundary=up1
[        ] flutter: Another exception was thrown: RenderBox was not laid out: RenderFlex#a3ed8 relayoutBoundary=up1
[   +3 ms] [DEVICE LOG] 2020-03-11 10:39:08.665883-0400  localhost Runner[77777]: (Flutter) flutter: Another exception was thrown:
NoSuchMethodError: The method '>' was called on null.
[        ] flutter: Another exception was thrown: NoSuchMethodError: The method '>' was called on null.
[  +37 ms] [DEVICE LOG] 2020-03-11 10:39:08.702714-0400  localhost Runner[77777]: (Flutter) flutter: Another exception was thrown: Updated
layout information required for RenderPositionedBox#e9830 NEEDS-LAYOUT NEEDS-PAINT to calculate semantics.
[        ] flutter: Another exception was thrown: Updated layout information required for RenderPositionedBox#e9830 NEEDS-LAYOUT NEEDS-PAINT
to calculate semantics.
[ +344 ms] [DEVICE LOG] 2020-03-11 10:39:09.048748-0400  localhost Runner[77777]: (RunningBoardServices) Created Activity ID: 0x8dede7,
Description: didChangeInheritances
[+4904 ms] Updating files
[ +238 ms] DevFS: Sync finished
[        ] Syncing files to device iPhone 11 Pro Max... (completed in 5,655ms, longer than expected)
[        ] Synced 3.5MB.
[   +1 ms] Sending to VM service: _flutter.listViews({})
[   +1 ms] Result: {type: FlutterViewList, views: [{type: FlutterView, id: _flutterView/0x7fdfd6806620, isolate: {type: @Isolate, fixedId:
true, id: isolates/63309182747755, name: main.dart$main-63309182747755, number: 63309182747755}}]}
[        ] <- accept
[        ] Connected to _flutterView/0x7fdfd6806620.
```

```
< Flutter (Channel stable, v1.12.13+hotfix.8, on Mac OS X 10.15.3 19D76, locale en-US)
    • Flutter version 1.12.13+hotfix.8 at /Users/gregcoleson/code/flutter/flutter
    • Framework revision 0b8abb4724 (4 weeks ago), 2020-02-11 11:44:36 -0800
    • Engine revision e1e6ced81d
    • Dart version 2.7.0

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/gregcoleson/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.3.1, Build version 11C504
    • CocoaPods version 1.8.4

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 43.0.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] VS Code (version 1.43.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.8.1

[✓] Connected device (1 available)
    • iPhone 11 Pro Max • F829AF9A-9A69-4C07-9370-BCBBEA30AFE4 • ios • com.apple.CoreSimulator.SimRuntime.iOS-13-3 (simulator)

• No issues found!
>
```

**Comment by gcoleson** [comment]
If I change code to below with height: 88 the issue goes away:
```dart
Positioned(
                    left: 17,
                    right: 24,
                    bottom: 2,
                    height: 88,
                    child: Row(
                      crossAxisAlignment: CrossAxisAlignment.stretch,
                      children: [
```

**Comment by VladyslavBondarenko** [comment]
Hi @gcoleson 
could you provide complete minimal reproducible code sample?

**Comment by TahaTesser** [comment]
Hi @gcoleson 
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore
reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any
more information for us; we will reopen it right away!
Thanks for your contribution.
