### ISSUE TITLE
[tool_crash] ProcessException: The command failed  Command: unzip -o -q ...

### ISSUE THREAD

**Issue by sagidam** [flutter/flutter#52437]
## Command
```
flutter --no-color run --machine --track-widget-creation --device-id=9C3AB61D-3C54-41A2-8B50-09D27A5700A6 lib/main.dart
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
ProcessException: ProcessException: The command failed
  Command: unzip -o -q /Users/sagidamti/flutter/bin/cache/downloads/storage.googleapis.com/flutter_infra/flutter/c4229bfbbae455ad69c967be19aee3fadd6486e1/sky_engine.zip -d /Users/sagidamti/flutter/bin/cache/pkg
```
#0      RunResult.throwException (package:flutter_tools/src/base/process.dart:172:5)
#1      _DefaultProcessUtils.runSync (package:flutter_tools/src/base/process.dart:448:17)
#2      _PosixUtils.unzip (package:flutter_tools/src/base/os.dart:168:18)
#3      CachedArtifact._downloadArchive.<anonymous closure> (package:flutter_tools/src/cache.dart:597:16)
#4      CachedArtifact._withDownloadFile (package:flutter_tools/src/cache.dart:616:26)
#5      CachedArtifact._downloadArchive (package:flutter_tools/src/cache.dart:583:12)
#6      CachedArtifact._downloadZipArchive (package:flutter_tools/src/cache.dart:603:12)
#7      EngineCachedArtifact.updateInner (package:flutter_tools/src/cache.dart:731:13)
#8      CachedArtifact.update (package:flutter_tools/src/cache.dart:539:11)
#9      Cache.updateAll (package:flutter_tools/src/cache.dart:417:24)
#10     FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:614:27)
#11     FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:537:33)
<asynchronous suspension>
#12     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:29)
#13     _rootRun (dart:async/zone.dart:1126:13)
#14     _CustomZone.run (dart:async/zone.dart:1023:19)
#15     _runZoned (dart:async/zone.dart:1518:10)
#16     runZoned (dart:async/zone.dart:1465:12)
#17     AppContext.run (package:flutter_tools/src/base/context.dart:149:18)
#18     FlutterCommand.run (package:flutter_tools/src/runner/flutter_command.dart:527:20)
```
```
[✓] Flutter (Channel beta, v1.14.6, on Mac OS X 10.14.6 18G3020, locale en-IL)
    • Flutter version 1.14.6 at /Users/sagidamti/flutter
    • Framework revision fabeb2a16f (6 weeks ago), 2020-01-28 07:56:51 -0800
    • Engine revision c4229bfbba
    • Dart version 2.8.0 (build 2.8.0-dev.5.0 fc3af737c7)

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/sagidamti/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.3.1, Build version 11C504
    • CocoaPods version 1.8.4

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 44.0.2
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)

[✓] Connected device (3 available)
    • iPhone 11 Pro Max • 9C3AB61D-3C54-41A2-8B50-09D27A5700A6 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-13-3 (simulator)
    • Chrome            • chrome                               • web-javascript • Google Chrome 80.0.3987.132
    • Web Server        • web-server                           • web-javascript • Flutter Tools

• No issues found!

```

## Flutter Application Metadata
**Version**: 1.0.4+5
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
### Plugins
connectivity-0.4.8+2
connectivity_macos-0.1.0+2
file_picker-1.4.3+2
flutter_absolute_path-1.0.6
flutter_full_pdf_viewer-1.0.6
flutter_genius_scan-3.0.11
flutter_plugin_android_lifecycle-1.0.6
image_cropper-1.2.1
image_picker-0.6.3+4
path_provider-1.6.5
path_provider_macos-0.0.4
flutter-share-1f8b139ca0bd35b643ef4f5ccce3a1b09931f16a
shared_preferences-0.5.6+3
shared_preferences_macos-0.0.1+6
shared_preferences_web-0.1.2+4

**Comment by christopherfujino** [comment]
@sagidam can you try wiping out your cache `rm -rf /Users/sagidamti/flutter/bin/cache` and then re-running the command, and let me know if it succeeds?

I'm sorry to have to suggest an awful hack like that, I am planning to make this process more stable with https://github.com/flutter/flutter/issues/52499

**Comment by jmagman** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!

Thanks for your contribution.

**Comment by christopherfujino** [comment]
Re-opening this as it persists in crash logging.

**Comment by christopherfujino** [comment]
A newer example:

```
ProcessException: The command failed
Stdout:

Stderr:
error: invalid compressed data to inflate /home/skalex/flutter/bin/cache/artifacts/engine/linux-x64/icudtl.dat
file #2: bad zipfile offset (local header sig): 473084
file #3: bad zipfile offset (local header sig): 8744714
file #4: bad zipfile offset (local header sig): 10525438
file #5: bad zipfile offset (local header sig): 10536390
Command: unzip, OS error code: 2

#0      RunResult.throwException (package:flutter_tools/src/base/process.dart:172:5)
#1      _DefaultProcessUtils.runSync (package:flutter_tools/src/base/process.dart:459:17)
#2      _PosixUtils.unzip (package:flutter_tools/src/base/os.dart:226:19)
#3      CachedArtifact._downloadArchive.<anonymous closure> (package:flutter_tools/src/cache.dart:648:16)
#4      _rootRunUnary (dart:async/zone.dart:1198:47)
#5      _CustomZone.runUnary (dart:async/zone.dart:1100:19)
#6      _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
#7      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
#8      Future._propagateToListeners (dart:async/future_impl.dart:725:32)
#9      Future._completeWithValue (dart:async/future_impl.dart:529:5)
#10     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:40:15)
#11     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:311:13)
#12     Cache.downloadFile (package:flutter_tools/src/cache.dart)
#13     _rootRunUnary (dart:async/zone.dart:1198:47)
#14     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
#15     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
#16     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
#17     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
#18     Future._completeWithValue (dart:async/future_impl.dart:529:5)
#19     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:40:15)
#20     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:311:13)
#21     Net.fetchUrl (package:flutter_tools/src/base/net.dart)
#22     _rootRunUnary (dart:async/zone.dart:1198:47)
#23     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
#24     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
```

```
[✓] Flutter (Channel master, 1.21.0-6.0.pre.245, on Linux, locale en_IN)
    • Flutter version 1.21.0-6.0.pre.245 at /home/skalex/flutter
    • Framework revision 77b4505c80 (11 hours ago), 2020-08-06 18:51:02 -0700
    • Engine revision cd3ea1e839
    • Dart version 2.10.0 (build 2.10.0-3.0.dev fcafd43f2c)
```

**Comment by zanderso** [comment]
I think @jonahwilliams has a patch for this out. After it lands, we should monitor crash rate once it rolls to dev.

**Comment by jonahwilliams** [comment]
Should be fixed by #64878. Will monitor crash logging after the next dev release to confirm

**Comment by pcsosinski** [comment]
@jonahwilliams can we mark this as closed based on your previous comment?

**Comment by jonahwilliams** [comment]
no, we have no crash logging information to confirm

**Comment by jonahwilliams** [comment]
To clarify from offline discussion: we still expect some crashes that look like this, but ideally at a much reduced rate and without the tell-tale message that the zip file is missing. After a week or so of this commit on the dev channel, I will update this issue with more findings.

**Comment by jonahwilliams** [comment]
A dev release with the fix was released a few days ago.

**Comment by jonahwilliams** [comment]
As of the latest dev release this no longer appears to be happening. Closing as fixed

**Comment by zanderso** [comment]
Hooray!
