### ISSUE TITLE
Upgrade Image package version in flutter_test

### ISSUE THREAD

**Issue by LAPPIT** [flutter/flutter#52458]
## Steps to Reproduce

1. Use the 'Image' package in my app.
2. Reference it in pubspec.yaml
  image: ^2.1.4

3. There is a new version (2.12), but when I try to upgrade in pubspec.yaml and run 'packages get' I get the following error:

C:\Flutter\flutter\bin\flutter.bat --no-color packages get
Running "flutter pub get" in minsockerbit...                    

Because every version of flutter_test from sdk depends on image 2.1.4 and minsockerbit depends on image ^2.1.12, flutter_test from sdk is forbidden.
So, because minsockerbit depends on flutter_test any from sdk, version solving failed.
pub get failed (1; So, because minsockerbit depends on flutter_test any from sdk, version solving failed.)
Process finished with exit code 1

I use Intellij Idea.

Have solved the problem by not upgrading the package :(

It would be great if the dependency can be upgraded in flutter_test!

Kind regards,
Mariette Lindström

## Logs

```
C:\Users\Mariette\IdeaProjects\MinSockerbit\minsockerbit>flutter --verbose packages get
[  +22 ms] executing: [C:\Flutter\flutter\] git -c log.showSignature=false log -n 1 --pretty=format:%H
[  +59 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[        ] 0b8abb4724aa590dd0f429683339b1e045a1594d
[        ] executing: [C:\Flutter\flutter\] git describe --match v*.*.* --first-parent --long --tags
[  +78 ms] Exit code 0 from: git describe --match v*.*.* --first-parent --long --tags
[        ] v1.12.13+hotfix.8-0-g0b8abb472
[   +5 ms] executing: [C:\Flutter\flutter\] git rev-parse --abbrev-ref --symbolic @{u}
[  +47 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/stable
[        ] executing: [C:\Flutter\flutter\] git ls-remote --get-url origin
[  +37 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[  +75 ms] executing: [C:\Flutter\flutter\] git rev-parse --abbrev-ref HEAD
[  +39 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] stable
[  +63 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +5 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +95 ms] Running "flutter pub get" in minsockerbit...
[   +3 ms] Using C:\Flutter\flutter\.pub-cache for the pub cache.
[   +1 ms] executing: [C:\Users\Mariette\IdeaProjects\MinSockerbit\minsockerbit\] C:\Flutter\flutter\bin\cache\dart-sdk\bin\pub.bat --verbose get --no-precompile
[ +244 ms] FINE: Pub 2.7.0
[   +3 ms] IO  : Spawning "cmd /c ver" in C:\Users\Mariette\IdeaProjects\MinSockerbit\minsockerbit\.
[  +18 ms] IO  : Finished ver. Exit code 0.
[        ]     | stdout:
[        ]     | | 
[        ]     | | Microsoft Windows [Version 10.0.18362.657]
[        ]     | Nothing output on stderr.
[  +82 ms] MSG : Resolving dependencies...
[   +7 ms] SLVR: fact: minsockerbit is 1.0.0+1
[   +4 ms] SLVR: derived: minsockerbit
[  +18 ms] SLVR: fact: minsockerbit depends on flutter any from sdk
[   +1 ms] SLVR: fact: minsockerbit depends on varorbas from path
[   +1 ms] SLVR: fact: minsockerbit depends on filter from path
[   +1 ms] SLVR: fact: minsockerbit depends on inloggning from path
[        ] SLVR: fact: minsockerbit depends on lokaldatabas from path
[   +1 ms] SLVR: fact: minsockerbit depends on support from path
[        ] SLVR: fact: minsockerbit depends on cupertino_icons ^0.1.3
[        ] SLVR: fact: minsockerbit depends on cached_network_image ^2.0.0
[        ] SLVR: fact: minsockerbit depends on charts_flutter ^0.9.0
[        ] SLVR: fact: minsockerbit depends on cloud_firestore ^0.13.4+1
[        ] SLVR: fact: minsockerbit depends on date_format ^1.0.8
[        ] SLVR: fact: minsockerbit depends on firebase_auth ^0.15.5+2
[        ] SLVR: fact: minsockerbit depends on firebase_core ^0.4.4+2
[        ] SLVR: fact: minsockerbit depends on firebase_storage ^3.1.3
[        ] SLVR: fact: minsockerbit depends on flutter_date_picker ^0.1.8
[        ] SLVR: fact: minsockerbit depends on font_awesome_flutter ^8.7.0
[        ] SLVR: fact: minsockerbit depends on http ^0.12.0+4
[        ] SLVR: fact: minsockerbit depends on image ^2.1.12
[        ] SLVR: fact: minsockerbit depends on image_picker ^0.6.3+4
[   +1 ms] SLVR: fact: minsockerbit depends on intl ^0.16.1
[   +1 ms] SLVR: fact: minsockerbit depends on material_design_icons_flutter ^3.4.5045
[        ] SLVR: fact: minsockerbit depends on modal_progress_hud ^0.1.3
[   +1 ms] SLVR: fact: minsockerbit depends on path_provider ^1.6.5
[        ] SLVR: fact: minsockerbit depends on rxdart ^0.23.1
[        ] SLVR: fact: minsockerbit depends on sqflite ^1.2.2+1
[        ] SLVR: fact: minsockerbit depends on swipedetector ^1.2.0
[        ] SLVR: fact: minsockerbit depends on flutter_test any from sdk
[        ] SLVR:   selecting minsockerbit
[   +1 ms] SLVR:   derived: flutter_test any from sdk
[        ] SLVR:   derived: swipedetector ^1.2.0
[   +1 ms] SLVR:   derived: sqflite ^1.2.2+1
[   +1 ms] SLVR:   derived: rxdart ^0.23.1
[   +1 ms] SLVR:   derived: path_provider ^1.6.5
[   +1 ms] SLVR:   derived: modal_progress_hud ^0.1.3
[        ] SLVR:   derived: material_design_icons_flutter ^3.4.5045
[        ] SLVR:   derived: intl ^0.16.1
[        ] SLVR:   derived: image_picker ^0.6.3+4
[        ] SLVR:   derived: image ^2.1.12
[        ] SLVR:   derived: http ^0.12.0+4
[        ] SLVR:   derived: font_awesome_flutter ^8.7.0
[        ] SLVR:   derived: flutter_date_picker ^0.1.8
[   +5 ms] SLVR:   derived: firebase_storage ^3.1.3
[   +3 ms] SLVR:   derived: firebase_core ^0.4.4+2
[        ] SLVR:   derived: firebase_auth ^0.15.5+2
[   +1 ms] SLVR:   derived: date_format ^1.0.8
[   +1 ms] SLVR:   derived: cloud_firestore ^0.13.4+1
[   +2 ms] SLVR:   derived: charts_flutter ^0.9.0
[   +1 ms] SLVR:   derived: cached_network_image ^2.0.0
[   +1 ms] SLVR:   derived: cupertino_icons ^0.1.3
[   +1 ms] SLVR:   derived: support from path
[   +1 ms] SLVR:   derived: lokaldatabas from path
[        ] SLVR:   derived: inloggning from path
[        ] SLVR:   derived: filter from path
[   +1 ms] SLVR:   derived: varorbas from path
[   +1 ms] SLVR:   derived: flutter any from sdk
[        ] IO  : Get versions from https://pub.dartlang.org/api/packages/image.
[   +3 ms] IO  : HTTP GET https://pub.dartlang.org/api/packages/image
[        ]     | Accept: application/vnd.pub.v2+json
[        ]     | X-Pub-OS: windows
[   +1 ms]     | X-Pub-Command: get
[   +1 ms]     | X-Pub-Session-ID: 19336D2D-52F9-4BFE-A8C2-85FEB7AD3C3E
[   +1 ms]     | X-Pub-Environment: flutter_cli:get
[   +1 ms]     | X-Pub-Reason: direct
[   +1 ms]     | user-agent: Dart pub 2.7.0
[ +313 ms] IO  : HTTP response 200 OK for GET https://pub.dartlang.org/api/packages/image
[   +1 ms]     | took 0:00:00.322377
[        ]     | transfer-encoding: chunked
[        ]     | date: Thu, 12 Mar 2020 07:20:36 GMT
[        ]     | content-encoding: gzip
[        ]     | vary: Accept-Encoding
[        ]     | strict-transport-security: max-age=31536000; preload
[        ]     | via: 1.1 google
[        ]     | content-type: application/json
[        ]     | x-frame-options: SAMEORIGIN
[        ]     | x-xss-protection: 1; mode=block
[        ]     | x-content-type-options: nosniff
[        ]     | server: dart:io with Shelf
[  +40 ms] SLVR:   fact: flutter_test 0.0.0 from sdk depends on flutter any from sdk
[   +1 ms] SLVR:   fact: flutter_test 0.0.0 from sdk depends on test_api 0.2.11
[        ] SLVR:   fact: flutter_test 0.0.0 from sdk depends on path 1.6.4
[   +1 ms] SLVR:   fact: flutter_test 0.0.0 from sdk depends on image 2.1.4
[        ] SLVR:   fact: flutter_test 0.0.0 from sdk depends on quiver 2.0.5
[   +1 ms] SLVR:   fact: flutter_test 0.0.0 from sdk depends on stack_trace 1.9.3
[   +1 ms] SLVR:   fact: flutter_test 0.0.0 from sdk depends on vector_math 2.0.8
[   +1 ms] SLVR:   fact: flutter_test 0.0.0 from sdk depends on archive 2.0.11
[   +1 ms] SLVR:   fact: flutter_test 0.0.0 from sdk depends on args 1.5.2
[   +1 ms] SLVR:   fact: flutter_test 0.0.0 from sdk depends on async 2.4.0
[   +1 ms] SLVR:   fact: flutter_test 0.0.0 from sdk depends on boolean_selector 1.0.5
[   +1 ms] SLVR:   fact: flutter_test 0.0.0 from sdk depends on charcode 1.1.2
[        ] SLVR:   fact: flutter_test 0.0.0 from sdk depends on collection 1.14.11
[        ] SLVR:   fact: flutter_test 0.0.0 from sdk depends on convert 2.1.1
[   +1 ms] SLVR:   fact: flutter_test 0.0.0 from sdk depends on crypto 2.1.3
[   +1 ms] SLVR:   fact: flutter_test 0.0.0 from sdk depends on matcher 0.12.6
[        ] SLVR:   fact: flutter_test 0.0.0 from sdk depends on meta 1.1.8
[   +1 ms] SLVR:   fact: flutter_test 0.0.0 from sdk depends on pedantic 1.8.0+1
[   +1 ms] SLVR:   fact: flutter_test 0.0.0 from sdk depends on petitparser 2.4.0
[   +2 ms] SLVR:   fact: flutter_test 0.0.0 from sdk depends on source_span 1.5.5
[   +1 ms] SLVR:   fact: flutter_test 0.0.0 from sdk depends on stream_channel 2.0.0
[   +2 ms] SLVR:   fact: flutter_test 0.0.0 from sdk depends on string_scanner 1.0.5
[        ] SLVR:   fact: flutter_test 0.0.0 from sdk depends on term_glyph 1.1.0
[        ] SLVR:   fact: flutter_test 0.0.0 from sdk depends on typed_data 1.1.6
[   +1 ms] SLVR:   fact: flutter_test 0.0.0 from sdk depends on xml 3.5.0
[        ] SLVR:   derived: not flutter_test 0.0.0 from sdk
[   +6 ms] SLVR:   fact: every version of flutter_test from sdk depends on archive 2.0.11
[   +2 ms] SLVR:   fact: every version of flutter_test from sdk depends on args 1.5.2
[   +2 ms] SLVR:   fact: every version of flutter_test from sdk depends on async 2.4.0
[   +2 ms] SLVR:   fact: every version of flutter_test from sdk depends on boolean_selector 1.0.5
[   +1 ms] SLVR:   fact: every version of flutter_test from sdk depends on charcode 1.1.2
[   +1 ms] SLVR:   fact: every version of flutter_test from sdk depends on collection 1.14.11
[   +1 ms] SLVR:   fact: every version of flutter_test from sdk depends on convert 2.1.1
[        ] SLVR:   fact: every version of flutter_test from sdk depends on crypto 2.1.3
[   +1 ms] SLVR:   fact: every version of flutter_test from sdk depends on flutter any from sdk
[        ] SLVR:   fact: every version of flutter_test from sdk depends on image 2.1.4
[        ] SLVR:   fact: every version of flutter_test from sdk depends on matcher 0.12.6
[   +1 ms] SLVR:   fact: every version of flutter_test from sdk depends on meta 1.1.8
[        ] SLVR:   fact: every version of flutter_test from sdk depends on path 1.6.4
[        ] SLVR:   fact: every version of flutter_test from sdk depends on pedantic 1.8.0+1
[        ] SLVR:   fact: every version of flutter_test from sdk depends on petitparser 2.4.0
[        ] SLVR:   fact: every version of flutter_test from sdk depends on quiver 2.0.5
[        ] SLVR:   fact: every version of flutter_test from sdk depends on source_span 1.5.5
[        ] SLVR:   fact: every version of flutter_test from sdk depends on stack_trace 1.9.3
[   +1 ms] SLVR:   fact: every version of flutter_test from sdk depends on stream_channel 2.0.0
[        ] SLVR:   fact: every version of flutter_test from sdk depends on string_scanner 1.0.5
[        ] SLVR:   fact: every version of flutter_test from sdk depends on term_glyph 1.1.0
[        ] SLVR:   fact: every version of flutter_test from sdk depends on test_api 0.2.11
[   +1 ms] SLVR:   fact: every version of flutter_test from sdk depends on typed_data 1.1.6
[        ] SLVR:   fact: every version of flutter_test from sdk depends on vector_math 2.0.8
[        ] SLVR:   fact: every version of flutter_test from sdk depends on xml 3.5.0
[        ] SLVR:   derived: xml 3.5.0
[        ] SLVR:   derived: vector_math 2.0.8
[        ] SLVR:   derived: typed_data 1.1.6
[        ] SLVR:   derived: test_api 0.2.11
[        ] SLVR:   derived: term_glyph 1.1.0
[        ] SLVR:   derived: string_scanner 1.0.5
[        ] SLVR:   derived: stream_channel 2.0.0
[   +1 ms] SLVR:   derived: stack_trace 1.9.3
[   +1 ms] SLVR:   derived: source_span 1.5.5
[   +1 ms] SLVR:   derived: quiver 2.0.5
[        ] SLVR:   derived: petitparser 2.4.0
[        ] SLVR:   derived: pedantic 1.8.0+1
[        ] SLVR:   derived: path 1.6.4
[   +1 ms] SLVR:   derived: meta 1.1.8
[   +1 ms] SLVR:   derived: matcher 0.12.6
[        ] SLVR:   conflict: every version of flutter_test from sdk depends on image 2.1.4
[        ] SLVR:   ! not image 2.1.4 is satisfied by image ^2.1.12
[        ] SLVR:   ! which is caused by "minsockerbit depends on image ^2.1.12"
[   +1 ms] SLVR:   ! thus: flutter_test from sdk is forbidden
[        ] SLVR:   ! flutter_test any from sdk is satisfied by flutter_test any from sdk
[        ] SLVR:   ! which is caused by "minsockerbit depends on flutter_test any from sdk"
[        ] SLVR:   ! thus: version solving failed
[        ] SLVR: Version solving took 0:00:00.517585 seconds.
[   +1 ms]     | Tried 1 solutions.
[   +1 ms] FINE: Resolving dependencies finished (0.522s).
[        ] ERR : Because every version of flutter_test from sdk depends on image 2.1.4 and minsockerbit depends on image ^2.1.12, flutter_test from sdk is forbidden.
[        ]     | So, because minsockerbit depends on flutter_test any from sdk, version solving failed.
[        ] FINE: Exception type: SolveFailure
[   +1 ms] FINE: package:pub/src/solver/version_solver.dart 308:5   VersionSolver._resolveConflict
[        ]     | package:pub/src/solver/version_solver.dart 131:27  VersionSolver._propagate
[        ]     | package:pub/src/solver/version_solver.dart 96:9    VersionSolver.solve
[        ]     | ===== asynchronous gap ===========================
[        ]     | dart:async                                         Future.catchError
[        ]     | package:pub/src/utils.dart 109:52                  captureErrors.<fn>
[        ]     | package:stack_trace                                Chain.capture
[   +1 ms]     | package:pub/src/utils.dart 122:11                  captureErrors
[   +1 ms]     | package:pub/src/command_runner.dart 171:13         PubCommandRunner.runCommand
[        ]     | dart:async                                         _completeOnAsyncReturn
[   +1 ms]     | package:pub/src/command_runner.dart                PubCommandRunner._validatePlatform
[   +1 ms]     | dart:async                                         _completeOnAsyncReturn
[   +1 ms]     | package:pub/src/io.dart                            runProcess.<fn>
[  +24 ms] Running "flutter pub get" in minsockerbit... (completed in 0.9s)
[   +2 ms] "flutter get" took 1,166ms.
pub get failed (1;     | package:pub/src/io.dart                            runProcess.<fn>)

#0      throwToolExit (package:flutter_tools/src/base/common.dart:28:3)
#1      _DefaultPub.batch (package:flutter_tools/src/dart/pub.dart:295:7)
#2      _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:73:64)
#3      _rootRunUnary (dart:async/zone.dart:1134:38)
#4      _CustomZone.runUnary (dart:async/zone.dart:1031:19)
#5      _FutureListener.handleValue (dart:async/future_impl.dart:139:18)
#6      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:680:45)
#7      Future._propagateToListeners (dart:async/future_impl.dart:709:32)
#8      Future._completeWithValue (dart:async/future_impl.dart:524:5)
#9      _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:32:15)
#10     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:290:13)
#11     _DefaultProcessUtils.stream (package:flutter_tools/src/base/process.dart)
#12     _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:73:64)
#13     _rootRunUnary (dart:async/zone.dart:1134:38)
#14     _CustomZone.runUnary (dart:async/zone.dart:1031:19)
#15     _FutureListener.handleValue (dart:async/future_impl.dart:139:18)
#16     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:680:45)
#17     Future._propagateToListeners (dart:async/future_impl.dart:709:32)
#18     Future._completeWithValue (dart:async/future_impl.dart:524:5)
#19     Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:554:7)
#20     _rootRun (dart:async/zone.dart:1126:13)
#21     _CustomZone.run (dart:async/zone.dart:1023:19)
#22     _CustomZone.runGuarded (dart:async/zone.dart:925:7)
#23     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:965:23)
#24     _microtaskLoop (dart:async/schedule_microtask.dart:43:21)
#25     _startMicrotaskLoop (dart:async/schedule_microtask.dart:52:5)
#26     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
#27     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:175:5)

C:\Users\Mariette\IdeaProjects\MinSockerbit\minsockerbit>

```

```
C:\Users\Mariette\IdeaProjects\MinSockerbit\minsockerbit>flutter doctor -v
[√] Flutter (Channel stable, v1.12.13+hotfix.8, on Microsoft Windows [Version 10.0.18362.657], locale en-SE)
    • Flutter version 1.12.13+hotfix.8 at C:\Flutter\flutter
    • Framework revision 0b8abb4724 (4 weeks ago), 2020-02-11 11:44:36 -0800
    • Engine revision e1e6ced81d
    • Dart version 2.7.0


[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at C:\Users\Mariette\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: C:\Users\Mariette\AppData\Local\JetBrains\Toolbox\apps\AndroidStudio\ch-0\191.6010548\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)
    • All Android licenses accepted.

[√] Android Studio (version 3.5)
    • Android Studio at C:\Users\Mariette\AppData\Local\JetBrains\Toolbox\apps\AndroidStudio\ch-0\191.6010548
    • Flutter plugin version 42.1.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)

[√] IntelliJ IDEA Ultimate Edition (version 2019.3)
    • IntelliJ at C:\Users\Mariette\AppData\Local\JetBrains\Toolbox\apps\IDEA-U\ch-0\193.6494.35
    • Flutter plugin version 43.0.3
    • Dart plugin version 193.5731

[√] VS Code (version 1.43.0)
    • VS Code at C:\Users\Mariette\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.8.1

[!] Connected device
    ! No devices available

! Doctor found issues in 1 category.

```

**Comment by TahaTesser** [comment]
Hi @LAPPIT 
Could you please link the `minsockerbit` package?
Thank you

**Comment by LAPPIT** [comment]
Hi,

I do not have the minsockerbit package on Github, so I created a new project and just added the dependency to the Image package in pubspec.yaml. I get the same problem there when I try to get the new package. Attatch a zip-file with the test-project, since it it smaller.

[FlutterTestImageTest.zip](https://github.com/flutter/flutter/files/4324075/FlutterTestImageTest.zip)

Kind regards,
Mariette

**Comment by TahaTesser** [comment]
Related to [#51582](https://github.com/flutter/flutter/issues/51582)

```
Because every version of flutter_test from sdk depends on image 2.1.4 and fluttertestimagetest depends on image ^2.1.12, flutter_test from sdk is forbidden.
```

@LAPPIT 
Could you please use `image: ^2.1.4` while this get fixed 
Thank you

**Comment by LAPPIT** [comment]
Using Image version 2.1.4 has been my solution for a few months now and I can continue using it so far. 

Just wanted to make you aware of the problem, since I always like to use as new packages as possible.

Kind regards,
Mariette

**Comment by VladyslavBondarenko** [comment]
In current dev `1.18.0-13.0.pre` https://github.com/flutter/flutter/blob/dev/packages/flutter_test/pubspec.yaml doesn't depend on `image` 
Closing as fixed, if you disagree please write in the comments and I will reopen it

**Comment by shaxxx** [comment]
Still an issue with Flutter 1.20.2 stable

> Doctor summary (to see all details, run flutter doctor -v):
> [√] Flutter (Channel stable, 1.20.2, on Microsoft Windows [Version 10.0.18363.959], locale hr-HR)
>  
> [√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
> [√] Android Studio (version 4.0)
> [√] VS Code (version 1.48.2)
> [√] Connected device (1 available)
> 
> • No issues found!

> C:\Users\isako\source\repos\senraise\example>flutter pub pub get
> Resolving dependencies...
> Because every version of flutter_test from sdk depends on meta 1.1.8 and image >=2.1.15 depends on meta ^1.2.0, flutter_test from sdk is incompatible with image >=2.1.15.
> So, because senraise_example depends on both image ^2.1.15 and flutter_test any from sdk, version solving failed.
> pub finished with exit code 1

**Comment by TahaTesser** [comment]
Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.

**Comment by perseus98** [comment]
### On Pub Get
`C:\flutter\flutter\bin\flutter.bat --no-color pub get
Running "flutter pub get" in demo...                         

Because image >=2.1.15 depends on meta ^1.2.0 and every version of flutter from sdk depends on meta 1.1.8, image >=2.1.15 is incompatible with flutter from sdk.
So, because demo depends on both flutter any from sdk and image ^2.1.15, version solving failed.
pub get failed (1; So, because demo depends on both flutter any from sdk and image ^2.1.15, version solving failed.)
Process finished with exit code 1`
### **Flutter Doctor Result**
`C:\flutter\flutter\bin\flutter.bat doctor --verbose
[√] Flutter (Channel stable, 1.20.2, on Microsoft Windows [Version 10.0.17763.737], locale en-IN)
    • Flutter version 1.20.2 at C:\flutter\flutter
    • Framework revision bbfbf1770c (5 weeks ago), 2020-08-13 08:33:09 -0700
    • Engine revision 9d5b21729f
    • Dart version 2.9.1

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at C:\Users\pmhrn\AppData\Local\Android\sdk
    • Platform android-29, build-tools 29.0.2
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Android Studio (version 4.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 49.0.2
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[!] VS Code (version 1.45.1)
    • VS Code at C:\Users\pmhrn\AppData\Local\Programs\Microsoft VS Code
    X Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[√] Connected device (1 available)
    • RMX1971 (mobile) • 17fdee65 • android-arm64 • Android 10 (API 29)

! Doctor found issues in 1 category.
Process finished with exit code 0`

**Comment by Okladnoj** [comment]
Because flutter_native_splash >=0.2.1 depends on image ^2.1.19 and no versions of image match >2.1.19 <3.0.0, flutter_native_splash >=0.2.1 requires image 2.1.19.
And because image 2.1.19 depends on archive ^2.0.0 and every version of integration_test from sdk depends on archive 3.0.0, flutter_native_splash >=0.2.1 is incompatible with integration_test from sdk.
So, because cattle_scan depends on both integration_test any from sdk and flutter_native_splash ^0.3.0, version solving failed.
pub get failed (1; So, because cattle_scan depends on both integration_test any from sdk and flutter_native_splash ^0.3.0, version solving failed.)

**Comment by Okladnoj** [comment]
```
PS C:\Work\Toronto\cattle_scan> flutter doctor -v
[√] Flutter (Channel dev, 1.27.0-4.0.pre, on Microsoft Windows [Version 10.0.19042.804], locale ru-RU)
    • Flutter version 1.27.0-4.0.pre at C:\src\flutter
    • Framework revision f8cd24de95 (3 days ago), 2021-02-16 11:24:17 -0800
    • Engine revision 1d537824d6
    • Dart version 2.13.0 (build 2.13.0-30.0.dev)

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.2)    
    • Android SDK at C:\Users\dmytr\AppData\Local\Android\Sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)   
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.7.6)       
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.7.30611.23
    • Windows 10 SDK version 10.0.18362.0

[√] Android Studio (version 4.1.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)   

[√] VS Code (version 1.53.2)
    • VS Code at C:\Users\dmytr\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.19.0

[√] Connected device (4 available)
    • Redmi Note 8 Pro (mobile) • gubexwivz5e6eyt8 • android-arm64  • Android 10 (API 29)
    • Windows (desktop)         • windows          • windows-x64    • Microsoft Windows [Version 10.0.19042.804]
    • Chrome (web)              • chrome           • web-javascript • Google Chrome 88.0.4324.150
    • Edge (web)                • edge             • web-javascript • Microsoft Edge 87.0.664.75

• No issues found!
```
