### ISSUE TITLE
Generating App bundle.

### ISSUE THREAD

**Issue by Labohkip81** [flutter/flutter#52453]
I'm trying to generate an apk for my app but i am getting this error.

**Comment by Labohkip81** [comment]
Calling mockable JAR artifact transform to create file: /home/gg/.gradle/caches/transforms-2/files-2.1/5ed028542017f3bc33f0cf6fa6cc4fa0/android.jar with input /home/gg/Android/Sdk/platforms/android-29/android.jar
WARN: error in opening zip file: /home/gg/.gradle/caches/modules-2/files-2.1/io.flutter/arm64_v8a_release/1.0.0-2994f7e1e682039464cb25e31a78b86a3c59b695/89c2d1c802a49d7406acf58fba1d1f614f69ff62/arm64_v8a_release-1.0.0-2994f7e1e682039464cb25e31a78b86a3c59b695.jar

**Comment by TahaTesser** [comment]
Hi @Labohkip81 
can you please provide your `flutter doctor -v` and `flutter build appbundle --verbose`?
Thank you

**Comment by Labohkip81** [comment]
```

[  +10 ms] executing: [/home/gg/flutter/] git -c log.showSignature=false log -n
1 --pretty=format:%H
[  +32 ms] Exit code 0 from: git -c log.showSignature=false log -n 1
--pretty=format:%H
[        ] 0b8abb4724aa590dd0f429683339b1e045a1594d
[        ] executing: [/home/gg/flutter/] git describe --match v*.*.*
--first-parent --long --tags
[  +19 ms] Exit code 0 from: git describe --match v*.*.* --first-parent --long
--tags
[        ] v1.12.13+hotfix.8-0-g0b8abb472
[   +7 ms] executing: [/home/gg/flutter/] git rev-parse --abbrev-ref --symbolic
@{u}
[   +4 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/stable
[        ] executing: [/home/gg/flutter/] git ls-remote --get-url origin
[   +4 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[  +39 ms] executing: [/home/gg/flutter/] git rev-parse --abbrev-ref HEAD
[   +5 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] stable
[  +29 ms] "flutter appbundle" took 30ms.
Error: No pubspec.yaml file found.
This command should be run from the root of your Flutter project.
Do not run this command from the root of your git clone of Flutter.

#0      FlutterCommand.validateCommand
(package:flutter_tools/src/runner/flutter_command.dart:690:9)
#1      FlutterCommand.verifyThenRunCommand
(package:flutter_tools/src/runner/flutter_command.dart:590:11)
#2      FlutterCommand.run.<anonymous closure>
(package:flutter_tools/src/runner/flutter_command.dart:515:33)
<asynchronous suspension>
#3      AppContext.run.<anonymous closure>
(package:flutter_tools/src/base/context.dart:146:29)
#4      _rootRun (dart:async/zone.dart:1126:13)
#5      _CustomZone.run (dart:async/zone.dart:1023:19)
#6      _runZoned (dart:async/zone.dart:1518:10)
#7      runZoned (dart:async/zone.dart:1465:12)
#8      AppContext.run (package:flutter_tools/src/base/context.dart:145:18)
#9      FlutterCommand.run
(package:flutter_tools/src/runner/flutter_command.dart:505:20)
#10     CommandRunner.runCommand (package:args/command_runner.dart:197:27)
#11     FlutterCommandRunner.runCommand.<anonymous closure>
(package:flutter_tools/src/runner/flutter_command_runner.dart:413:21)
<asynchronous suspension>
#12     AppContext.run.<anonymous closure>
(package:flutter_tools/src/base/context.dart:146:29)
#13     _rootRun (dart:async/zone.dart:1126:13)
#14     _CustomZone.run (dart:async/zone.dart:1023:19)
#15     _runZoned (dart:async/zone.dart:1518:10)
#16     runZoned (dart:async/zone.dart:1465:12)
#17     AppContext.run (package:flutter_tools/src/base/context.dart:145:18)
#18     FlutterCommandRunner.runCommand
(package:flutter_tools/src/runner/flutter_command_runner.dart:364:19)
#19     CommandRunner.run.<anonymous closure>
(package:args/command_runner.dart:112:25)
#20     new Future.sync (dart:async/future.dart:224:31)
#21     CommandRunner.run (package:args/command_runner.dart:112:14)
#22     FlutterCommandRunner.run
(package:flutter_tools/src/runner/flutter_command_runner.dart:250:18)
#23     run.<anonymous closure>.<anonymous closure>
(package:flutter_tools/runner.dart:63:22)
#24     _rootRun (dart:async/zone.dart:1126:13)
#25     _CustomZone.run (dart:async/zone.dart:1023:19)
#26     _runZoned (dart:async/zone.dart:1518:10)
#27     runZoned (dart:async/zone.dart:1502:12)
#28     run.<anonymous closure> (package:flutter_tools/runner.dart:61:18)
<asynchronous suspension>
#29     AppContext.run.<anonymous closure>
(package:flutter_tools/src/base/context.dart:146:29)
#30     _rootRun (dart:async/zone.dart:1126:13)
#31     _CustomZone.run (dart:async/zone.dart:1023:19)
#32     _runZoned (dart:async/zone.dart:1518:10)
#33     runZoned (dart:async/zone.dart:1465:12)
#34     AppContext.run (package:flutter_tools/src/base/context.dart:145:18)
#35     runInContext (package:flutter_tools/src/context_runner.dart:64:24)
#36     run (package:flutter_tools/runner.dart:50:10)
#37     main (package:flutter_tools/executable.dart:65:9)
#38     main
(file:///home/gg/flutter/packages/flutter_tools/bin/flutter_tools.dart:8:3)
#39     _startIsolate.<anonymous closure>
(dart:isolate-patch/isolate_patch.dart:305:32)
#40     _RawReceivePortImpl._handleMessage
(dart:isolate-patch/isolate_patch.dart:174:12)


```

**Comment by Labohkip81** [comment]
@TahaTesser i've sent the ``` flutter build appbundle --verbose```

**Comment by TahaTesser** [comment]
Hi @Labohkip81 
```
[  +29 ms] "flutter appbundle" took 30ms.
Error: No pubspec.yaml file found.
This command should be run from the root of your Flutter project.
Do not run this command from the root of your git clone of Flutter.
```

Run the command form your project directory not from other directories 
Thank you

**Comment by Labohkip81** [comment]
thanks

**Comment by Labohkip81** [comment]
I managed to build the bundles.

**Comment by TahaTesser** [comment]
Hi @Labohkip81 
given your last message I feel safe to close this issue,
if you disagree please write in the comments and I will reopen it.
 Thank you
