### ISSUE TITLE
cannot find symbol import io.flutter.embedding.engine.plugins.lifecycle.FlutterLifecycleAdapter;

### ISSUE THREAD

**Issue by P-B1101** [flutter/flutter#52530]
when i want to build app for android with command "flutter build apk --release", i get this error 

cannot find symbol
import io.flutter.embedding.engine.plugins.lifecycle.FlutterLifecycleAdapter;

that is inside local_auth plugin. i opened it with android studio and see that the FlutterLifeCycleAdapter cannot be imported.
and only one there is one class in that path and its name is "HiddenLifecycleReference".

this is output of my build command

$ flutter build apk --release
You are building a fat APK that includes binaries for android-arm, android-arm64, android-x64.
If you are deploying the app to the Play Store, it's recommended to use app bundles or split the APK to reduce the APK size.
    To generate an app bundle, run:
        flutter build appbundle --target-platform android-arm,android-arm64,android-x64
        Learn more on: https://developer.android.com/guide/app-bundle
    To split the APKs per ABI, run:
        flutter build apk --target-platform android-arm,android-arm64,android-x64 --split-per-abi
        Learn more on:  https://developer.android.com/studio/build/configure-apk-splits#configure-abi-split
Running Gradle task 'assembleRelease'...

FAILURE: Build failed with an exception.

* What went wrong:

Execution failed for task ':vibrate:verifyReleaseResources'.

> A failure occurred while executing com.android.build.gradle.internal.tasks.Workers$ActionFacade

   > 1 exception was raised by workers:

     com.android.builder.internal.aapt.v2.Aapt2Exception: Android resource linking failed

     C:\Users\Pedram\.gradle\caches\transforms-2\files-2.1\60a5a3b619f09ca92e9f1b4798715d52\core-1.0.0\res\values\values.xml:57:5-88:25: AAPT: error: resource android:attr/fontStyle not found.

     C:\Users\Pedram\.gradle\caches\transforms-2\files-2.1\60a5a3b619f09ca92e9f1b4798715d52\core-1.0.0\res\values\values.xml:57:5-88:25: AAPT: error: resource android:attr/font not found.

     C:\Users\Pedram\.gradle\caches\transforms-2\files-2.1\60a5a3b619f09ca92e9f1b4798715d52\core-1.0.0\res\values\values.xml:57:5-88:25: AAPT: error: resource android:attr/fontWeight not found.

     C:\Users\Pedram\.gradle\caches\transforms-2\files-2.1\60a5a3b619f09ca92e9f1b4798715d52\core-1.0.0\res\values\values.xml:57:5-88:25: AAPT: error: resource android:attr/fontVariationSettings not found.

     C:\Users\Pedram\.gradle\caches\transforms-2\files-2.1\60a5a3b619f09ca92e9f1b4798715d52\core-1.0.0\res\values\values.xml:57:5-88:25: AAPT: error: resource android:attr/ttcIndex not found.

* Try:

Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 24s
Running Gradle task 'assembleRelease'...                           ۲۵٫۰s
The built failed likely due to AndroidX incompatibilities in a plugin. The tool is about to try using Jetfier to solve the incompatibility.
Building plugin audioplayers...
Running Gradle task 'assembleAarRelease'...                         ۲٫۴s
√ Built build\app\outputs\repo.
Building plugin barcode_scan...
Running Gradle task 'assembleAarRelease'...                         ۲٫۷s
√ Built build\app\outputs\repo.
Building plugin connectivity...
Running Gradle task 'assembleAarRelease'...                         ۲٫۲s
√ Built build\app\outputs\repo.
Building plugin connectivity_macos...
Running Gradle task 'assembleAarRelease'...                         ۳٫۴s
√ Built build\app\outputs\repo.
Building plugin flutter_downloader...
Running Gradle task 'assembleAarRelease'...                        ۱۲٫۰s
√ Built build\app\outputs\repo.
Building plugin flutter_money_formatter...
Running Gradle task 'assembleAarRelease'...                         ۲٫۲s
√ Built build\app\outputs\repo.
Building plugin flutter_plugin_android_lifecycle...
Running Gradle task 'assembleAarRelease'...                         ۳٫۱s
√ Built build\app\outputs\repo.
Building plugin flutter_secure_storage...
Running Gradle task 'assembleAarRelease'...                         ۳٫۹s
√ Built build\app\outputs\repo.
Building plugin local_auth...
Running Gradle task 'assembleAarRelease'...                         ۲٫۵s
> Task :assembleAarRelease UP-TO-DATE
> Task :preBuild UP-TO-DATE
> Task :preReleaseBuild UP-TO-DATE
> Task :compileReleaseAidl NO-SOURCE
> Task :compileReleaseRenderscript UP-TO-DATE
> Task :checkReleaseManifest UP-TO-DATE
> Task :generateReleaseBuildConfig UP-TO-DATE
> Task :generateReleaseResValues UP-TO-DATE
> Task :generateReleaseResources UP-TO-DATE
> Task :packageReleaseResources UP-TO-DATE
> Task :processReleaseManifest UP-TO-DATE
> Task :generateReleaseRFile UP-TO-DATE
> Task :prepareLintJar UP-TO-DATE
> Task :generateReleaseSources UP-TO-DATE
> Task :javaPreCompileRelease

> Task :compileReleaseJavaWithJavac FAILED

> Task :mergeReleaseConsumerProguardFiles UP-TO-DATE
> Task :mergeReleaseShaders UP-TO-DATE
> Task :compileReleaseShaders UP-TO-DATE
> Task :generateReleaseAssets UP-TO-DATE
> Task :packageReleaseAssets UP-TO-DATE
> Task :packageReleaseRenderscript NO-SOURCE
> Task :processReleaseJavaRes NO-SOURCE
> Task :compileReleaseNdk NO-SOURCE
> Task :mergeReleaseJniLibFolders UP-TO-DATE
> Task :transformNativeLibsWithMergeJniLibsForRelease UP-TO-DATE
> Task :transformNativeLibsWithSyncJniLibsForRelease UP-TO-DATE
17 actionable tasks: 2 executed, 15 up-to-date

C:\Users\Pedram\AppData\Roaming\Pub\Cache\hosted\pub.dartlang.org\local_auth-0.6.1+3\android\src\main\java\io\flutter\plugins\localauth\LocalAuthPlugin.java:20: error: cannot find symbol
import io.flutter.embedding.engine.plugins.lifecycle.FlutterLifecycleAdapter;
                                                    ^
  symbol:   class FlutterLifecycleAdapter
  location: package io.flutter.embedding.engine.plugins.lifecycle
C:\Users\Pedram\AppData\Roaming\Pub\Cache\hosted\pub.dartlang.org\local_auth-0.6.1+3\android\src\main\java\io\flutter\plugins\localauth\LocalAuthPlugin.java:186: error: cannot find symbol
        lifecycle = FlutterLifecycleAdapter.getActivityLifecycle(binding);
                    ^
  symbol:   variable FlutterLifecycleAdapter
  location: class LocalAuthPlugin
C:\Users\Pedram\AppData\Roaming\Pub\Cache\hosted\pub.dartlang.org\local_auth-0.6.1+3\android\src\main\java\io\flutter\plugins\localauth\LocalAuthPlugin.java:199: error: cannot find symbol
        lifecycle = FlutterLifecycleAdapter.getActivityLifecycle(binding);
                    ^
  symbol:   variable FlutterLifecycleAdapter
  location: class LocalAuthPlugin
3 errors

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileReleaseJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 2s

The plugin local_auth could not be built due to the issue above.

**Comment by TahaTesser** [comment]
Hi @P-B1101 
can you please provide your `flutter doctor -v` and `flutter run --verbose`?
 Also, to better address the issue, would be helpful if you could post a minimal code sample to reproduce the problem
Thank you

**Comment by P-B1101** [comment]
@TahaTesser 
$ flutter doctor -v
[√] Flutter (Channel stable, v1.12.13+hotfix.8, on Microsoft Windows [Version 10.0.18362.592], locale fa-IR)
    • Flutter version 1.12.13+hotfix.8 at C:\Flutter\flutter
    • Framework revision 0b8abb4724 (5 weeks ago), 2020-02-11 11:44:36 -0800
    • Engine revision e1e6ced81d
    • Dart version 2.7.0

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at C:\SDK\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • ANDROID_HOME = C:\SDK\sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)
    • All Android licenses accepted.

[√] Android Studio (version 3.6)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 44.0.2
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)

[!] Connected device
    ! No devices available

! Doctor found issues in 1 category.

and

$ flutter run --verbose
[  +41 ms] executing: [C:\Flutter\flutter\] git -c log.showSignature=false log -n 1 --pretty=format:%H
[  +75 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[        ] 0b8abb4724aa590dd0f429683339b1e045a1594d
[        ] executing: [C:\Flutter\flutter\] git describe --match v*.*.* --first-parent --long --tags
[  +54 ms] Exit code 0 from: git describe --match v*.*.* --first-parent --long --tags
[        ] v1.12.13+hotfix.8-0-g0b8abb4724
[  +13 ms] executing: [C:\Flutter\flutter\] git rev-parse --abbrev-ref --symbolic @{u}
[ +106 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[   +1 ms] origin/stable
[        ] executing: [C:\Flutter\flutter\] git ls-remote --get-url origin
[  +31 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[  +91 ms] executing: [C:\Flutter\flutter\] git rev-parse --abbrev-ref HEAD
[  +41 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] stable
[ +181 ms] executing: C:\SDK\sdk\platform-tools\adb.exe devices -l
[  +43 ms] Exit code 0 from: C:\SDK\sdk\platform-tools\adb.exe devices -l
[        ] List of devices attached
[  +12 ms] No supported devices connected.
[  +14 ms] "flutter run" took ۲۸۹ms.

#0      throwToolExit (package:flutter_tools/src/base/common.dart:28:3)
#1      RunCommand.validateCommand (package:flutter_tools/src/commands/run.dart:289:7)
<asynchronous suspension>
#2      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:590:11)
#3      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:515:33)
<asynchronous suspension>
#4      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:146:29)
#5      _rootRun (dart:async/zone.dart:1126:13)
#6      _CustomZone.run (dart:async/zone.dart:1023:19)
#7      _runZoned (dart:async/zone.dart:1518:10)
#8      runZoned (dart:async/zone.dart:1465:12)
#9      AppContext.run (package:flutter_tools/src/base/context.dart:145:18)
#10     FlutterCommand.run (package:flutter_tools/src/runner/flutter_command.dart:505:20)
#11     CommandRunner.runCommand (package:args/command_runner.dart:197:27)
#12     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:413:21)
<asynchronous suspension>
#13     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:146:29)
#14     _rootRun (dart:async/zone.dart:1126:13)
#15     _CustomZone.run (dart:async/zone.dart:1023:19)
#16     _runZoned (dart:async/zone.dart:1518:10)
#17     runZoned (dart:async/zone.dart:1465:12)
#18     AppContext.run (package:flutter_tools/src/base/context.dart:145:18)
#19     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:364:19)
#20     CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:112:25)
#21     new Future.sync (dart:async/future.dart:224:31)
#22     CommandRunner.run (package:args/command_runner.dart:112:14)
#23     FlutterCommandRunner.run (package:flutter_tools/src/runner/flutter_command_runner.dart:250:18)
#24     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:63:22)
#25     _rootRun (dart:async/zone.dart:1126:13)
#26     _CustomZone.run (dart:async/zone.dart:1023:19)
#27     _runZoned (dart:async/zone.dart:1518:10)
#28     runZoned (dart:async/zone.dart:1502:12)
#29     run.<anonymous closure> (package:flutter_tools/runner.dart:61:18)
<asynchronous suspension>
#30     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:146:29)
#31     _rootRun (dart:async/zone.dart:1126:13)
#32     _CustomZone.run (dart:async/zone.dart:1023:19)
#33     _runZoned (dart:async/zone.dart:1518:10)
#34     runZoned (dart:async/zone.dart:1465:12)
#35     AppContext.run (package:flutter_tools/src/base/context.dart:145:18)
#36     runInContext (package:flutter_tools/src/context_runner.dart:64:24)
#37     run (package:flutter_tools/runner.dart:50:10)
#38     main (package:flutter_tools/executable.dart:65:9)
#39     main (file:///C:/Flutter/flutter/packages/flutter_tools/bin/flutter_tools.dart:8:3)
#40     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:305:32)
#41     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:174:12)

**Comment by TahaTesser** [comment]
Hi @P-B1101 
Could you please try possible [solution](https://github.com/flutter/flutter/issues/51765#issuecomment-601493234)
Thank you

**Comment by P-B1101** [comment]
not working :(

**Comment by TahaTesser** [comment]
Hi @P-B1101 
Could you try cleaning  gradle cache, check [this](https://stackoverflow.com/a/30450020)

**Comment by P-B1101** [comment]
hi @TahaTesser 
same result :(

**Comment by Sugyo-In** [comment]
I have same problem and when I switched flutter channel to master and upgraded. It fixed.

In my case. The problem was AndroidX migration.
At Flutter SDK v1.12.13.  **HiddenLifecycleReference** class imports and retruns  **android.arch.lifecycle.Lifecycle** class. But **FlutterLifecycleAdapter** imports and returns **androidx.lifecycle.Lifecycle**.
Flutter engine migrated AndroidX at Flutter/engine#17075. And it rolls in master now.

But is there way to use FlutterLifecycleAdapter is stable channel?

**Comment by SeeenyaOhar** [comment]
> I have same problem and when I switched flutter channel to master and upgraded. It fixed.
> 
> In my case. The problem was AndroidX migration.
> At Flutter SDK v1.12.13. **HiddenLifecycleReference** class imports and retruns **android.arch.lifecycle.Lifecycle** class. But **FlutterLifecycleAdapter** imports and returns **androidx.lifecycle.Lifecycle**.
> Flutter engine migrated AndroidX at [flutter/engine#17075](https://github.com/flutter/engine/pull/17075). And it rolls in master now.
> 
> But is there any way to use FlutterLifecycleAdapter in stable channel?

I got the same issue, it didn't help me. Any idea how to solve it?

**Comment by zwz1192511822** [comment]
> when i want to build app for android with command "flutter build apk --release", i get this error
> 
> ```shell
> cannot find symbol
> import io.flutter.embedding.engine.plugins.lifecycle.FlutterLifecycleAdapter;
> ```
> 
> that is inside local_auth plugin. i opened it with android studio and see that the FlutterLifeCycleAdapter cannot be imported.
> and only one there is one class in that path and its name is "HiddenLifecycleReference".
> 
> this is output of my build command
> 
> ```shell
> $ flutter build apk --release
> You are building a fat APK that includes binaries for android-arm, android-arm64, android-x64.
> If you are deploying the app to the Play Store, it's recommended to use app bundles or split the APK to reduce the APK size.
>     To generate an app bundle, run:
>         flutter build appbundle --target-platform android-arm,android-arm64,android-x64
>         Learn more on: https://developer.android.com/guide/app-bundle
>     To split the APKs per ABI, run:
>         flutter build apk --target-platform android-arm,android-arm64,android-x64 --split-per-abi
>         Learn more on:  https://developer.android.com/studio/build/configure-apk-splits#configure-abi-split
> Running Gradle task 'assembleRelease'...
> 
> 
> FAILURE: Build failed with an exception.
> 
> 
> 
> * What went wrong:
> 
> Execution failed for task ':vibrate:verifyReleaseResources'.
> 
> > A failure occurred while executing com.android.build.gradle.internal.tasks.Workers$ActionFacade
> 
>    > 1 exception was raised by workers:
> 
>      com.android.builder.internal.aapt.v2.Aapt2Exception: Android resource linking failed
> 
>      C:\Users\Pedram\.gradle\caches\transforms-2\files-2.1\60a5a3b619f09ca92e9f1b4798715d52\core-1.0.0\res\values\values.xml:57:5-88:25: AAPT: error: resource android:attr/fontStyle not found.
> 
> 
> 
>      C:\Users\Pedram\.gradle\caches\transforms-2\files-2.1\60a5a3b619f09ca92e9f1b4798715d52\core-1.0.0\res\values\values.xml:57:5-88:25: AAPT: error: resource android:attr/font not found.
> 
> 
> 
>      C:\Users\Pedram\.gradle\caches\transforms-2\files-2.1\60a5a3b619f09ca92e9f1b4798715d52\core-1.0.0\res\values\values.xml:57:5-88:25: AAPT: error: resource android:attr/fontWeight not found.
> 
> 
> 
>      C:\Users\Pedram\.gradle\caches\transforms-2\files-2.1\60a5a3b619f09ca92e9f1b4798715d52\core-1.0.0\res\values\values.xml:57:5-88:25: AAPT: error: resource android:attr/fontVariationSettings not found.
> 
> 
> 
>      C:\Users\Pedram\.gradle\caches\transforms-2\files-2.1\60a5a3b619f09ca92e9f1b4798715d52\core-1.0.0\res\values\values.xml:57:5-88:25: AAPT: error: resource android:attr/ttcIndex not found.
> 
> 
> 
> 
> 
> 
> 
> * Try:
> 
> Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
> 
> 
> 
> * Get more help at https://help.gradle.org
> 
> 
> 
> BUILD FAILED in 24s
> Running Gradle task 'assembleRelease'...                           ۲۵٫۰s
> The built failed likely due to AndroidX incompatibilities in a plugin. The tool is about to try using Jetfier to solve the incompatibility.
> Building plugin audioplayers...
> Running Gradle task 'assembleAarRelease'...                         ۲٫۴s
> √ Built build\app\outputs\repo.
> Building plugin barcode_scan...
> Running Gradle task 'assembleAarRelease'...                         ۲٫۷s
> √ Built build\app\outputs\repo.
> Building plugin connectivity...
> Running Gradle task 'assembleAarRelease'...                         ۲٫۲s
> √ Built build\app\outputs\repo.
> Building plugin connectivity_macos...
> Running Gradle task 'assembleAarRelease'...                         ۳٫۴s
> √ Built build\app\outputs\repo.
> Building plugin flutter_downloader...
> Running Gradle task 'assembleAarRelease'...                        ۱۲٫۰s
> √ Built build\app\outputs\repo.
> Building plugin flutter_money_formatter...
> Running Gradle task 'assembleAarRelease'...                         ۲٫۲s
> √ Built build\app\outputs\repo.
> Building plugin flutter_plugin_android_lifecycle...
> Running Gradle task 'assembleAarRelease'...                         ۳٫۱s
> √ Built build\app\outputs\repo.
> Building plugin flutter_secure_storage...
> Running Gradle task 'assembleAarRelease'...                         ۳٫۹s
> √ Built build\app\outputs\repo.
> Building plugin local_auth...
> Running Gradle task 'assembleAarRelease'...                         ۲٫۵s
> > Task :assembleAarRelease UP-TO-DATE
> > Task :preBuild UP-TO-DATE
> > Task :preReleaseBuild UP-TO-DATE
> > Task :compileReleaseAidl NO-SOURCE
> > Task :compileReleaseRenderscript UP-TO-DATE
> > Task :checkReleaseManifest UP-TO-DATE
> > Task :generateReleaseBuildConfig UP-TO-DATE
> > Task :generateReleaseResValues UP-TO-DATE
> > Task :generateReleaseResources UP-TO-DATE
> > Task :packageReleaseResources UP-TO-DATE
> > Task :processReleaseManifest UP-TO-DATE
> > Task :generateReleaseRFile UP-TO-DATE
> > Task :prepareLintJar UP-TO-DATE
> > Task :generateReleaseSources UP-TO-DATE
> > Task :javaPreCompileRelease
> 
> > Task :compileReleaseJavaWithJavac FAILED
> 
> > Task :mergeReleaseConsumerProguardFiles UP-TO-DATE
> > Task :mergeReleaseShaders UP-TO-DATE
> > Task :compileReleaseShaders UP-TO-DATE
> > Task :generateReleaseAssets UP-TO-DATE
> > Task :packageReleaseAssets UP-TO-DATE
> > Task :packageReleaseRenderscript NO-SOURCE
> > Task :processReleaseJavaRes NO-SOURCE
> > Task :compileReleaseNdk NO-SOURCE
> > Task :mergeReleaseJniLibFolders UP-TO-DATE
> > Task :transformNativeLibsWithMergeJniLibsForRelease UP-TO-DATE
> > Task :transformNativeLibsWithSyncJniLibsForRelease UP-TO-DATE
> 17 actionable tasks: 2 executed, 15 up-to-date
> 
> C:\Users\Pedram\AppData\Roaming\Pub\Cache\hosted\pub.dartlang.org\local_auth-0.6.1+3\android\src\main\java\io\flutter\plugins\localauth\LocalAuthPlugin.java:20: error: cannot find symbol
> import io.flutter.embedding.engine.plugins.lifecycle.FlutterLifecycleAdapter;
>                                                     ^
>   symbol:   class FlutterLifecycleAdapter
>   location: package io.flutter.embedding.engine.plugins.lifecycle
> C:\Users\Pedram\AppData\Roaming\Pub\Cache\hosted\pub.dartlang.org\local_auth-0.6.1+3\android\src\main\java\io\flutter\plugins\localauth\LocalAuthPlugin.java:186: error: cannot find symbol
>         lifecycle = FlutterLifecycleAdapter.getActivityLifecycle(binding);
>                     ^
>   symbol:   variable FlutterLifecycleAdapter
>   location: class LocalAuthPlugin
> C:\Users\Pedram\AppData\Roaming\Pub\Cache\hosted\pub.dartlang.org\local_auth-0.6.1+3\android\src\main\java\io\flutter\plugins\localauth\LocalAuthPlugin.java:199: error: cannot find symbol
>         lifecycle = FlutterLifecycleAdapter.getActivityLifecycle(binding);
>                     ^
>   symbol:   variable FlutterLifecycleAdapter
>   location: class LocalAuthPlugin
> 3 errors
> 
> FAILURE: Build failed with an exception.
> 
> * What went wrong:
> Execution failed for task ':compileReleaseJavaWithJavac'.
> > Compilation failed; see the compiler error output for details.
> 
> * Try:
> Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
> 
> * Get more help at https://help.gradle.org
> 
> BUILD FAILED in 2s
> ```
> 
> The plugin local_auth could not be built due to the issue above.

Did you solve it？

**Comment by danielsilver2** [comment]
I'm having the same issue, does someone solved it?

**Comment by zwz1192511822** [comment]
> I'm having the same issue, does someone solved it?

https://github.com/flutter/flutter/issues/68585 try it

**Comment by danielsilver2** [comment]
> > I'm having the same issue, does someone solved it?
> 
> #68585 try it

Thanks, but this does not resolved it.

**Comment by danielsilver2** [comment]
For me, it was solved after doing these items:

* Creating a new project with AndroidX;
* Resolving Android Studio warnings;
* Updating google & firebase libs on build.gradle.

**Comment by HongLouWang** [comment]
got same issue, anyone solved?

**Comment by faithyoussef** [comment]
i solved this with multiple steps and i actually cannot tell which one exactly worked but i am trying to help who ever needs it.

firstly, the package needed time to adapt to the changes with changing the gradle version, so i deleted the flutter life cycle  with the location package which resulted an error and redownloaded it as a package, copied those files "in android and through android" which finally started not showing the error message but i still got gradle build failed so i cleaned it up , cleaned gradle "./gradlew clean and cleanBuild, and cleanBuildCache, gradle build command ", with syncing gradle with each step even if it resulted a failure. and then used "flutter --v" with flutter doctor and flutter clean , plus refreshing a couple of times. 
plus working on androidx and applying it
it worked for me *sign*
when i was basically following this"https://cybdom.tech/flutter-tutorial-real-estate-app/"

**Comment by SAGARSURI** [comment]
I am facing the same issue. `Unresolved reference: FlutterLifecycleAdapter`
