### ISSUE TITLE
Plugin repo CI flakes on `fatal: repository 'https://cdn.cocoapods.org/' not found`

### ISSUE THREAD

**Issue by cyanglaz** [flutter/flutter#52567]
log

```
if [[ "$CHANNEL" -eq "stable" ]]; then find . | grep _web$ | xargs rm -rf; fi
flutter channel $CHANNEL
Switching to flutter channel 'master'...
git: Already on 'master'
git: Your branch is up to date with 'origin/master'.
Successfully switched to flutter channel 'master'.
To ensure that you're on the latest build from this channel, run 'flutter upgrade'
./script/incremental_build.sh build-examples --ipa
Running for all packages
BUILDING IPA for package_info/example
Running "flutter pub get" in example...                            14.4s
Warning: Building for device with codesigning disabled. You will have to manually codesign before deploying to device.
Building io.flutter.plugins.packageInfoExample for device (ios-release)...
Upgrading project.pbxproj
Warning: Missing build name (CFBundleShortVersionString).
Warning: Missing build number (CFBundleVersion).
Running pod install...                                             53.0s
CocoaPods' output:
↳
      Preparing
    Analyzing dependencies
    Inspecting targets to integrate
      Using `ARCHS` setting to build architectures of target `Pods-Runner`: (``)
    Fetching external sources
    -> Fetching podspec for `Flutter` from `Flutter`
    -> Fetching podspec for `e2e` from `.symlinks/plugins/e2e/ios`
    -> Fetching podspec for `package_info` from `.symlinks/plugins/package_info/ios`
    Resolving dependencies of `Podfile`
    Cloning spec repo `trunk` from `https://cdn.cocoapods.org/`
      $ /usr/bin/git clone https://cdn.cocoapods.org/ -- trunk
    [!] Unable to add a source with url `https://cdn.cocoapods.org/` named `trunk`.
    (/usr/bin/git clone https://cdn.cocoapods.org/ -- trunk
    Cloning into 'trunk'...
    fatal: repository 'https://cdn.cocoapods.org/' not found
    )
    You can try adding it manually in `/Users/anka/.cocoapods/repos` or via `pod repo add`.
    /Users/anka/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/cocoapods-1.8.4/lib/cocoapods/sources_manager.rb:52:in `rescue in create_source_with_url'
    /Users/anka/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/cocoapods-1.8.4/lib/cocoapods/sources_manager.rb:46:in `create_source_with_url'
    /Users/anka/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/cocoapods-1.8.4/lib/cocoapods/sources_manager.rb:19:in `find_or_create_source_with_url'
    /Users/anka/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/cocoapods-1.8.4/lib/cocoapods/installer/analyzer.rb:178:in `block in sources'
    /Users/anka/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/cocoapods-1.8.4/lib/cocoapods/installer/analyzer.rb:177:in `map'
    /Users/anka/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/cocoapods-1.8.4/lib/cocoapods/installer/analyzer.rb:177:in `sources'
    /Users/anka/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/cocoapods-1.8.4/lib/cocoapods/installer/analyzer.rb:985:in `block in resolve_dependencies'
    /Users/anka/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/cocoapods-1.8.4/lib/cocoapods/user_interface.rb:64:in `section'
    /Users/anka/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/cocoapods-1.8.4/lib/cocoapods/installer/analyzer.rb:984:in `resolve_dependencies'
    /Users/anka/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/cocoapods-1.8.4/lib/cocoapods/installer/analyzer.rb:124:in `analyze'
    /Users/anka/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/cocoapods-1.8.4/lib/cocoapods/installer.rb:410:in `analyze'
    /Users/anka/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/cocoapods-1.8.4/lib/cocoapods/installer.rb:234:in `block in resolve_dependencies'
    /Users/anka/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/cocoapods-1.8.4/lib/cocoapods/user_interface.rb:64:in `section'
    /Users/anka/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/cocoapods-1.8.4/lib/cocoapods/installer.rb:233:in `resolve_dependencies'
    /Users/anka/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/cocoapods-1.8.4/lib/cocoapods/installer.rb:156:in `install!'
    /Users/anka/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/cocoapods-1.8.4/lib/cocoapods/command/install.rb:52:in `run'
    /Users/anka/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/claide-1.0.3/lib/claide/command.rb:334:in `run'
    /Users/anka/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/cocoapods-1.8.4/lib/cocoapods/command.rb:52:in `run'
    /Users/anka/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/cocoapods-1.8.4/bin/pod:55:in `<top (required)>'
    /Users/anka/.rbenv/versions/2.6.5/bin/pod:23:in `load'
    /Users/anka/.rbenv/versions/2.6.5/bin/pod:23:in `<main>'
Error output from CocoaPods:
↳
      Cloning into 'trunk'...
      fatal: repository 'https://cdn.cocoapods.org/' not found
    [!] Automatically assigning platform `iOS` with version `8.0` on target `Runner` because no platform was specified. Please specify a platform for this target in your Podfile. See `https://guides.cocoapods.org/syntax/podfile.html#platform`.
Action Required: You must set a build name and number in the pubspec.yaml file version field before submitting to the App Store.
Error running pod install
BUILDING IPA for path_provider/path_provider/example
Running "flutter pub get" in example...                             1.6s
Warning: Building for device with codesigning disabled. You will have to manually codesign before deploying to device.
Building io.flutter.plugins.pathProviderExample for device (ios-release)...
Upgrading project.pbxproj
Warning: Missing build name (CFBundleShortVersionString).
Warning: Missing build number (CFBundleVersion).
Running pod install...                                             30.7s
CocoaPods' output:
↳
      Preparing
    Analyzing dependencies
    Inspecting targets to integrate
      Using `ARCHS` setting to build architectures of target `Pods-Runner`: (``)
    Fetching external sources
    -> Fetching podspec for `Flutter` from `Flutter`
    -> Fetching podspec for `e2e` from `.symlinks/plugins/e2e/ios`
    -> Fetching podspec for `path_provider` from `.symlinks/plugins/path_provider/ios`
    -> Fetching podspec for `path_provider_macos` from `.symlinks/plugins/path_provider_macos/ios`
    Resolving dependencies of `Podfile`
    Cloning spec repo `trunk` from `https://cdn.cocoapods.org/`
      $ /usr/bin/git clone https://cdn.cocoapods.org/ -- trunk
    [!] Unable to add a source with url `https://cdn.cocoapods.org/` named `trunk`.
    (/usr/bin/git clone https://cdn.cocoapods.org/ -- trunk
    Cloning into 'trunk'...
    fatal: repository 'https://cdn.cocoapods.org/' not found
    )
    You can try adding it manually in `/Users/anka/.cocoapods/repos` or via `pod repo add`.
    /Users/anka/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/cocoapods-1.8.4/lib/cocoapods/sources_manager.rb:52:in `rescue in create_source_with_url'
    /Users/anka/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/cocoapods-1.8.4/lib/cocoapods/sources_manager.rb:46:in `create_source_with_url'
    /Users/anka/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/cocoapods-1.8.4/lib/cocoapods/sources_manager.rb:19:in `find_or_create_source_with_url'
    /Users/anka/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/cocoapods-1.8.4/lib/cocoapods/installer/analyzer.rb:178:in `block in sources'
    /Users/anka/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/cocoapods-1.8.4/lib/cocoapods/installer/analyzer.rb:177:in `map'
    /Users/anka/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/cocoapods-1.8.4/lib/cocoapods/installer/analyzer.rb:177:in `sources'
    /Users/anka/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/cocoapods-1.8.4/lib/cocoapods/installer/analyzer.rb:985:in `block in resolve_dependencies'
    /Users/anka/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/cocoapods-1.8.4/lib/cocoapods/user_interface.rb:64:in `section'
    /Users/anka/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/cocoapods-1.8.4/lib/cocoapods/installer/analyzer.rb:984:in `resolve_dependencies'
    /Users/anka/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/cocoapods-1.8.4/lib/cocoapods/installer/analyzer.rb:124:in `analyze'
    /Users/anka/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/cocoapods-1.8.4/lib/cocoapods/installer.rb:410:in `analyze'
    /Users/anka/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/cocoapods-1.8.4/lib/cocoapods/installer.rb:234:in `block in resolve_dependencies'
    /Users/anka/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/cocoapods-1.8.4/lib/cocoapods/user_interface.rb:64:in `section'
    /Users/anka/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/cocoapods-1.8.4/lib/cocoapods/installer.rb:233:in `resolve_dependencies'
    /Users/anka/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/cocoapods-1.8.4/lib/cocoapods/installer.rb:156:in `install!'
    /Users/anka/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/cocoapods-1.8.4/lib/cocoapods/command/install.rb:52:in `run'
    /Users/anka/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/claide-1.0.3/lib/claide/command.rb:334:in `run'
    /Users/anka/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/cocoapods-1.8.4/lib/cocoapods/command.rb:52:in `run'
    /Users/anka/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/cocoapods-1.8.4/bin/pod:55:in `<top (required)>'
    /Users/anka/.rbenv/versions/2.6.5/bin/pod:23:in `load'
    /Users/anka/.rbenv/versions/2.6.5/bin/pod:23:in `<main>'
Error output from CocoaPods:
↳
      Cloning into 'trunk'...
      fatal: repository 'https://cdn.cocoapods.org/' not found
    [!] Automatically assigning platform `iOS` with version `8.0` on target `Runner` because no platform was specified. Please specify a platform for this target in your Podfile. See `https://guides.cocoapods.org/syntax/podfile.html#platform`.
Action Required: You must set a build name and number in the pubspec.yaml file version field before submitting to the App Store.
Error running pod install
BUILDING IPA for path_provider/path_provider_macos/example
Running "flutter pub get" in example...                             1.5s
Warning: Building for device with codesigning disabled. You will have to manually codesign before deploying to device.
Building io.flutter.plugins.pathProviderExample for device (ios-release)...
Upgrading project.pbxproj
Warning: Missing build name (CFBundleShortVersionString).
Warning: Missing build number (CFBundleVersion).
Running pod install...                                              5.3s
Running Xcode build...                                          
Xcode build done.                                           42.6s
Built /private/var/folders/3y/l0z1x3693dl_8n0qybp4dqwh0000gn/T/cirrus-ci-build/packages/path_provider/path_provider_macos/example/build/ios/iphoneos/Runner.app.
Action Required: You must set a build name and number in the pubspec.yaml file version field before submitting to the App Store.
BUILDING IPA for quick_actions/example
Running "flutter pub get" in example...                             1.1s
Warning: Building for device with codesigning disabled. You will have to manually codesign before deploying to device.
Building io.flutter.plugins.quickActionsExample for device (ios-release)...
Upgrading project.pbxproj
Warning: Missing build name (CFBundleShortVersionString).
Warning: Missing build number (CFBundleVersion).
Running pod install...                                              2.3s
Running Xcode build...                                          
Xcode build done.                                           30.6s
Built /private/var/folders/3y/l0z1x3693dl_8n0qybp4dqwh0000gn/T/cirrus-ci-build/packages/quick_actions/example/build/ios/iphoneos/Runner.app.
Action Required: You must set a build name and number in the pubspec.yaml file version field before submitting to the App Store.
BUILDING IPA for sensors/example
Running "flutter pub get" in example...                             1.1s
Warning: Building for device with codesigning disabled. You will have to manually codesign before deploying to device.
Building io.flutter.plugins.sensorsExample for device (ios-release)...
Upgrading project.pbxproj
Warning: Missing build name (CFBundleShortVersionString).
Warning: Missing build number (CFBundleVersion).
Running pod install...                                              2.1s
Running Xcode build...                                          
Xcode build done.                                           31.2s
Built /private/var/folders/3y/l0z1x3693dl_8n0qybp4dqwh0000gn/T/cirrus-ci-build/packages/sensors/example/build/ios/iphoneos/Runner.app.
Action Required: You must set a build name and number in the pubspec.yaml file version field before submitting to the App Store.
BUILDING IPA for share/example
Running "flutter pub get" in example...                             1.2s
Warning: Building for device with codesigning disabled. You will have to manually codesign before deploying to device.
Building io.flutter.plugins.shareExample for device (ios-release)...
Upgrading project.pbxproj
Warning: Missing build name (CFBundleShortVersionString).
Warning: Missing build number (CFBundleVersion).
Running pod install...                                              2.0s
Running Xcode build...                                          
Xcode build done.                                           33.3s
Built /private/var/folders/3y/l0z1x3693dl_8n0qybp4dqwh0000gn/T/cirrus-ci-build/packages/share/example/build/ios/iphoneos/Runner.app.
Action Required: You must set a build name and number in the pubspec.yaml file version field before submitting to the App Store.
BUILDING IPA for shared_preferences/shared_preferences/example
Running "flutter pub get" in example...                             1.7s
Warning: Building for device with codesigning disabled. You will have to manually codesign before deploying to device.
Building io.flutter.plugins.sharedPreferencesExample for device (ios-release)...
Upgrading project.pbxproj
Warning: Missing build name (CFBundleShortVersionString).
Warning: Missing build number (CFBundleVersion).
Running pod install...                                              2.1s
Running Xcode build...                                          
Xcode build done.                                           28.1s
Built /private/var/folders/3y/l0z1x3693dl_8n0qybp4dqwh0000gn/T/cirrus-ci-build/packages/shared_preferences/shared_preferences/example/build/ios/iphoneos/Runner.app.
Action Required: You must set a build name and number in the pubspec.yaml file version field before submitting to the App Store.
The following build are failing (see above for details):
 * package_info/example (ipa)
 * path_provider/path_provider/example (ipa)
```

The flake was triggered with https://github.com/flutter/plugins/pull/2603#issuecomment-598876505

**Comment by collinjackson** [comment]
We'll keep this open for now but it can be closed if this doesn't recur in a few weeks

**Comment by collinjackson** [comment]
Closing since this doesn't seem to be a major source of flakes currently.
