### ISSUE TITLE
MultiFrameImageCodec test fails with multiple mutators error

### ISSUE THREAD

**Issue by dnfield** [flutter/flutter#52576]
e.g. https://cirrus-ci.com/task/6521001789882368?command=test_host#L1939

```
[ RUN      ] ImageDecoderFixtureTest.MultiFrameCodecCanBeCollectedBeforeIOTasksFinish
../../third_party/dart/runtime/vm/dart_api_impl.cc: 1521: error: Unable to Enter Isolate : Multiple mutators entering an isolate / Dart VM is shutting down
version=2.8.0-edge.flutter-c3a0bb0 (Fri Mar 13 16:31:11 2020 +0000) on "linux_x64"
thread=28219, isolate=(null)((nil))
isolate_instructions=0, vm_instructions=30aed00
  pc 0x0000000003214ddc fp 0x00007fb5a07e7a20 /tmp/clean_engine/src/out/host_debug_unopt/ui_unittests+0x3014ddc
  pc 0x00000000030aee4a fp 0x00007fb5a07e7b60 /tmp/clean_engine/src/out/host_debug_unopt/ui_unittests+0x2eaee4a
  pc 0x0000000001dc2e9c fp 0x00007fb5a07e7bc0 /tmp/clean_engine/src/out/host_debug_unopt/ui_unittests+0x1bc2e9c
  pc 0x0000000001dc44f9 fp 0x00007fb5a07e7bf0 /tmp/clean_engine/src/out/host_debug_unopt/ui_unittests+0x1bc44f9
  pc 0x0000000001dc447d fp 0x00007fb5a07e7c10 /tmp/clean_engine/src/out/host_debug_unopt/ui_unittests+0x1bc447d
  pc 0x0000000001dc442d fp 0x00007fb5a07e7c30 /tmp/clean_engine/src/out/host_debug_unopt/ui_unittests+0x1bc442d
  pc 0x0000000001dc43fd fp 0x00007fb5a07e7c50 /tmp/clean_engine/src/out/host_debug_unopt/ui_unittests+0x1bc43fd
  pc 0x0000000001dc3599 fp 0x00007fb5a07e7c70 /tmp/clean_engine/src/out/host_debug_unopt/ui_unittests+0x1bc3599
  pc 0x0000000001ec36c5 fp 0x00007fb5a07e7c90 /tmp/clean_engine/src/out/host_debug_unopt/ui_unittests+0x1cc36c5
  pc 0x0000000001ec2325 fp 0x00007fb5a07e7cb0 /tmp/clean_engine/src/out/host_debug_unopt/ui_unittests+0x1cc2325
  pc 0x0000000001ed2c73 fp 0x00007fb5a07e7d70 /tmp/clean_engine/src/out/host_debug_unopt/ui_unittests+0x1cd2c73
  pc 0x0000000001ed2b5a fp 0x00007fb5a07e7d90 /tmp/clean_engine/src/out/host_debug_unopt/ui_unittests+0x1cd2b5a
  pc 0x0000000001ee4ea3 fp 0x00007fb5a07e7db0 /tmp/clean_engine/src/out/host_debug_unopt/ui_unittests+0x1ce4ea3
  pc 0x0000000001ee4e46 fp 0x00007fb5a07e7e00 /tmp/clean_engine/src/out/host_debug_unopt/ui_unittests+0x1ce4e46
  pc 0x0000000001ed2ae2 fp 0x00007fb5a07e7e30 /tmp/clean_engine/src/out/host_debug_unopt/ui_unittests+0x1cd2ae2
  pc 0x0000000001ed1b4d fp 0x00007fb5a07e7e50 /tmp/clean_engine/src/out/host_debug_unopt/ui_unittests+0x1cd1b4d
  pc 0x0000000001ee1421 fp 0x00007fb5a07e7e90 /tmp/clean_engine/src/out/host_debug_unopt/ui_unittests+0x1ce1421
  pc 0x0000000001ee136d fp 0x00007fb5a07e7eb0 /tmp/clean_engine/src/out/host_debug_unopt/ui_unittests+0x1ce136d
  pc 0x0000000001ee1315 fp 0x00007fb5a07e7ed0 /tmp/clean_engine/src/out/host_debug_unopt/ui_unittests+0x1ce1315
  pc 0x0000000001ee1093 fp 0x00007fb5a07e7f10 /tmp/clean_engine/src/out/host_debug_unopt/ui_unittests+0x1ce1093
-- End of DumpStackTrace
```

I'm unable to reproduce this locally on mac or linux with 1000s of runs with the same random seed(s), but have seen this on Cirrus a few times now.

**Comment by dnfield** [comment]
Also AFAIK this has only happened on Cirrus, not on LUCI.

**Comment by cbracken** [comment]
Also saw the Dart SDK (single commit, unrelated to this failure) roll flakily fail just now on Cirrus. https://cirrus-ci.com/task/5766145324089344

@rmacnak-google @aam thoughts?

**Comment by aam** [comment]
I see that while we have `platform` thread running main isolate, another `ui` thread attempts to run some tasks on the same isolate(vm calls this "Multiple mutators entering an isolate"), which results in the assertion.

```
$ info threads
 507  Thread 108712.111378 (ui)              Dart_EnterIsolate (isolate=0x7f4460005320) at ../../third_party/dart/runtime/vm/dart_api_impl.cc:1521
 599  Thread 108712.111364 (platform)        0x00007f4495ce6126 in _int_free (av=0x7f4460000020, p=0x7f4460018050, have_lock=<optimized out>) at malloc.c:4314
```

`ui` thread that hits an exception
```
(rr) bt
#0  Dart_EnterIsolate (isolate=0x7f4460005320) at ../../third_party/dart/runtime/vm/dart_api_impl.cc:1521
#1  0x0000000002f1730e in tonic::DartIsolateScope::DartIsolateScope (this=0x7f43c77fdba0, isolate=0x7f4460005320) at ../../flutter/third_party/tonic/scopes/dart_isolate_scope.cc:16
#2  0x0000000001e053cc in tonic::DartMessageHandler::OnHandleMessage (this=0x7f4460001880, dart_state=0x7f4460001490) at ../../flutter/third_party/tonic/dart_message_handler.cc:69
#3  0x0000000001e06a69 in tonic::DartMessageHandler::OnMessage(tonic::DartState*)::$_0::operator()() const (this=0x7f43b40079d8) at ../../flutter/third_party/tonic/dart_message_handler.cc:42
#4  0x0000000001e069ed in std::__1::__invoke<tonic::DartMessageHandler::OnMessage(tonic::DartState*)::$_0&> (__f=...) at ../../third_party/libcxx/include/type_traits:3530
#5  0x0000000001e0699d in std::__1::__invoke_void_return_wrapper<void>::__call<tonic::DartMessageHandler::OnMessage(tonic::DartState*)::$_0&>(tonic::DartMessageHandler::OnMessage(tonic::DartState*)::$_0&) (__args=...) at ../../third_party/libcxx/include/__functional_base:348
#6  0x0000000001e0696d in std::__1::__function::__alloc_func<tonic::DartMessageHandler::OnMessage(tonic::DartState*)::$_0, std::__1::allocator<tonic::DartMessageHandler::OnMessage(tonic::DartState*)::$_0>, void ()>::operator()() (this=0x7f43b40079d8) at ../../third_party/libcxx/include/functional:1533
#7  0x0000000001e05ade in std::__1::__function::__func<tonic::DartMessageHandler::OnMessage(tonic::DartState*)::$_0, std::__1::allocator<tonic::DartMessageHandler::OnMessage(tonic::DartState*)::$_0>, void ()>::operator()() (this=0x7f43b40079d0) at ../../third_party/libcxx/include/functional:1707
#8  0x0000000001f1e415 in std::__1::__function::__value_func<void ()>::operator()() const (this=0x7f43b40079d0) at ../../third_party/libcxx/include/functional:1860
#9  0x0000000001f1d005 in std::__1::function<void ()>::operator()() const (this=0x7f43b40079d0) at ../../third_party/libcxx/include/functional:2419
#10 0x0000000001f2d662 in fml::MessageLoopImpl::FlushTasks (this=0x7f43b4006b60, type=fml::FlushType::kAll) at ../../flutter/fml/message_loop_impl.cc:127
#11 0x0000000001f2d53a in fml::MessageLoopImpl::RunExpiredTasksNow (this=0x7f43b4006b60) at ../../flutter/fml/message_loop_impl.cc:137
#12 0x0000000001f40676 in fml::MessageLoopLinux::OnEventFired (this=0x7f43b4006b60) at ../../flutter/fml/platform/linux/message_loop_linux.cc:89
#13 0x0000000001f40617 in fml::MessageLoopLinux::Run (this=0x7f43b4006b60) at ../../flutter/fml/platform/linux/message_loop_linux.cc:70
#14 0x0000000001f2d4c5 in fml::MessageLoopImpl::DoRun (this=0x7f43b4006b60) at ../../flutter/fml/message_loop_impl.cc:96
#15 0x0000000001f2c4bd in fml::MessageLoop::Run (this=0x7f43b4000b60) at ../../flutter/fml/message_loop.cc:49
#16 0x0000000001f3caf4 in fml::Thread::Thread(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&)::$_0::operator()() const (this=0x54a2eb8)
    at ../../flutter/fml/thread.cc:34
#17 0x0000000001f3ca2d in std::__1::__invoke<fml::Thread::Thread(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&)::$_0> (__f=...)
    at ../../third_party/libcxx/include/type_traits:3530
#18 0x0000000001f3c9d5 in std::__1::__thread_execute<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, fml::Thread::Thread(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&)::$_0>(std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, fml::Thread::Thread(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&)::$_0>&, std::__1::__tuple_indices<>) (__t=...)
    at ../../third_party/libcxx/include/thread:341
#19 0x0000000001f3c74b in std::__1::__thread_proxy<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, fml::Thread::Thread(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&)::$_0> >(void*) (__vp=0x54a2eb0) at ../../third_party/libcxx/include/thread:351
#20 0x00007f4495f7cfb7 in start_thread (arg=<optimized out>) at pthread_create.c:486
#21 0x00007f4495d5c2bf in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
```

`platform` thread stack when exception is thrown by `ui` thread:
```
(rr) bt
#0  0x00007f4495ce6126 in _int_free (av=0x7f4460000020, p=0x7f4460018050, have_lock=<optimized out>) at malloc.c:4314
#1  0x0000000001e68aa5 in operator delete (ptr=0x7f4460018060) at ../../third_party/libcxx/src/new.cpp:133
#2  0x000000000330823c in dart::Handles<2, 64, 8>::DeleteHandleBlocks (this=0x7f44600609f0, blocks=0x0) at ../../third_party/dart/runtime/vm/handles_impl.h:146
#3  dart::Handles<2, 64, 8>::Reset (this=0x7f44600609f0) at ../../third_party/dart/runtime/vm/handles_impl.h:71
#4  dart::Zone::DeleteAll (this=0x7f44600605c0) at ../../third_party/dart/runtime/vm/zone.cc:201
#5  0x00000000033080f9 in dart::Zone::~Zone (this=0x7f44600605c0) at ../../third_party/dart/runtime/vm/zone.cc:179
#6  0x00000000032f4c62 in dart::ApiZone::~ApiZone (this=0x7f44600605c0) at ../../third_party/dart/runtime/vm/dart_api_state.h:66
#7  dart::ApiLocalScope::~ApiLocalScope (this=0x7f4460060390) at ../../third_party/dart/runtime/vm/dart_api_state.h:578
#8  dart::Thread::ExitApiScope (this=<optimized out>) at ../../third_party/dart/runtime/vm/thread.cc:1014
#9  0x000000000362cc10 in Dart_ExitScope () at ../../third_party/dart/runtime/vm/dart_api_impl.cc:2119
#10 0x0000000001deb260 in tonic::DartApiScope::~DartApiScope (this=0x7f446f574cf0) at ../../flutter/third_party/tonic/scopes/dart_api_scope.h:18
#11 0x0000000001e08106 in tonic::DartState::Scope::~Scope (this=0x7f446f574ce0) at ../../flutter/third_party/tonic/dart_state.cc:20
#12 0x00000000030d2ee1 in flutter::DartIsolate::Run(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > const&, std::__1::function<void ()> const&) (this=0x7f4460001490, entrypoint_name=..., args=..., on_run=...) at ../../flutter/runtime/dart_isolate.cc:513
#13 0x0000000001de5b79 in flutter::testing::RunDartCodeInIsolate (vm_ref=..., result=..., settings=..., task_runners=..., entrypoint=..., args=..., fixtures_path=..., io_manager=...)
    at ../../flutter/testing/dart_isolate_runner.cc:142
#14 0x0000000001dea638 in flutter::testing::RunDartCodeInIsolate(flutter::DartVMRef&, flutter::Settings const&, flutter::TaskRunners const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, fml::WeakPtr<flutter::IOManager>)::$_0::operator()() (this=0x54a26e0) at ../../flutter/testing/dart_isolate_runner.cc:167
#15 0x0000000001dea4a3 in fml::internal::CopyableLambda<flutter::testing::RunDartCodeInIsolate(flutter::DartVMRef&, flutter::Settings const&, flutter::TaskRunners const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, fml::WeakPtr<flutter::IOManager>)::$_0>::operator()<>() const (this=0x7f4460000e08) at ../../flutter/fml/make_copyable.h:24
#16 0x0000000001dea45d in std::__1::__invoke<fml::internal::CopyableLambda<flutter::testing::RunDartCodeInIsolate(flutter::DartVMRef&, flutter::Settings const&, flutter::TaskRunners const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, fml::WeakPtr<flutter::IOManager>)::$_0>&> (__f=...) at ../../third_party/libcxx/include/type_traits:3530
#17 0x0000000001dea40d in std::__1::__invoke_void_return_wrapper<void>::__call<fml::internal::CopyableLambda<flutter::testing::RunDartCodeInIsolate(flutter::DartVMRef&, flutter::Settings const&, flutter::TaskRunners const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, fml::WeakPtr<flutter::IOManager>)::$_0>&>(fml::internal::CopyableLambda<flutter::testing::RunDartCodeInIsolate(flutter::DartVMRef&, flutter::Settings const&, flutter::TaskRunners const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, fml::WeakPtr<flutter::IOManager>)::$_0>&) (__args=...) at ../../third_party/libcxx/include/__functional_base:348
#18 0x0000000001dea3dd in std::__1::__function::__alloc_func<fml::internal::CopyableLambda<flutter::testing::RunDartCodeInIsolate(flutter::DartVMRef&, flutter::Settings const&, flutter::TaskRunners const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, fml::WeakPtr<flutter::IOManager>)::$_0>, std::__1::allocator<fml::internal::CopyableLambda<flutter::testing::RunDartCodeInIsolate(flutter::DartVMRef&, flutter::Settings const&, flutter::TaskRunners const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, fml::WeakPtr<flutter::IOManager>)::$_0> >, void ()>::operator()() (this=0x7f4460000e08) at ../../third_party/libcxx/include/functional:1533
#19 0x0000000001de96be in std::__1::__function::__func<fml::internal::CopyableLambda<flutter::testing::RunDartCodeInIsolate(flutter::DartVMRef&, flutter::Settings const&, flutter::TaskRunners const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, fml::WeakPtr<flutter::IOManager>)::$_0>, std::__1::allocator<fml::internal::CopyableLambda<flutter::testing::RunDartCodeInIsolate(flutter::DartVMRef&, flutter::Settings const&, flutter::TaskRunners const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, fml::WeakPtr<flutter::IOManager>)::$_0> >, void ()>::operator()() (this=0x7f4460000e00) at ../../third_party/libcxx/include/functional:1707
#20 0x0000000001f1e415 in std::__1::__function::__value_func<void ()>::operator()() const (this=0x7f4460000dc0) at ../../third_party/libcxx/include/functional:1860
#21 0x0000000001f1d005 in std::__1::function<void ()>::operator()() const (this=0x7f4460000dc0) at ../../third_party/libcxx/include/functional:2419
#22 0x0000000001f2d662 in fml::MessageLoopImpl::FlushTasks (this=0x7f4460000c30, type=fml::FlushType::kAll) at ../../flutter/fml/message_loop_impl.cc:127
#23 0x0000000001f2d53a in fml::MessageLoopImpl::RunExpiredTasksNow (this=0x7f4460000c30) at ../../flutter/fml/message_loop_impl.cc:137
#24 0x0000000001f40676 in fml::MessageLoopLinux::OnEventFired (this=0x7f4460000c30) at ../../flutter/fml/platform/linux/message_loop_linux.cc:89
#25 0x0000000001f40617 in fml::MessageLoopLinux::Run (this=0x7f4460000c30) at ../../flutter/fml/platform/linux/message_loop_linux.cc:70
#26 0x0000000001f2d4c5 in fml::MessageLoopImpl::DoRun (this=0x7f4460000c30) at ../../flutter/fml/message_loop_impl.cc:96
#27 0x0000000001f2c4bd in fml::MessageLoop::Run (this=0x7f4460000b60) at ../../flutter/fml/message_loop.cc:49
#28 0x0000000001f3caf4 in fml::Thread::Thread(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&)::$_0::operator()() const (this=0x54a2308)
    at ../../flutter/fml/thread.cc:34
#29 0x0000000001f3ca2d in std::__1::__invoke<fml::Thread::Thread(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&)::$_0> (__f=...)
    at ../../third_party/libcxx/include/type_traits:3530
#30 0x0000000001f3c9d5 in std::__1::__thread_execute<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, fml::Thread::Thread(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&)::$_0>(std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, fml::Thread::Thread(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&)::$_0>&, std::__1::__tuple_indices<>) (__t=...)
    at ../../third_party/libcxx/include/thread:341
#31 0x0000000001f3c74b in std::__1::__thread_proxy<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, fml::Thread::Thread(std::_--Type <RET> for more, q to quit, c to continue without paging--
_1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&)::$_0> >(void*) (__vp=0x54a2300) at ../../third_party/libcxx/include/thread:351
#32 0x00007f4495f7cfb7 in start_thread (arg=<optimized out>) at pthread_create.c:486
#33 0x00007f4495d5c2bf in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
```
