### ISSUE TITLE
TabBarView throws Unhandled Exception: NoSuchMethodError: The getter 'focusScopeNode' was called on null.

### ISSUE THREAD

**Issue by oupat** [flutter/flutter#52595]
I am posting this here because it's an error recreated with just the basic stuff (a tabbarview, a tabcontroller and more than two statefulwidgets that are the tabs). I have been facing this problem for a week now and haven't been able to solve it. I have a TabBarView with 3 tabs, all of which are build with statefulwidgets with just a text. I have recreated the problem with classes with just an Text widget in them. Flutter throws the error when the user taps on a tab that is not neighbouring the current tab, so if you go from tab 1 to 2, no error, if you go from 1 to 3 the error is thrown.

```
  E/flutter ( 5455): [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: NoSuchMethodError: The getter 'focusScopeNode' was called on null.
    E/flutter ( 5455): Receiver: null
    E/flutter ( 5455): Tried calling: focusScopeNode
    E/flutter ( 5455): #0      Object.noSuchMethod (dart:core-patch/object_patch.dart:53:5)
    E/flutter ( 5455): #1      Route.didPush.<anonymous closure> (package:flutter/src/widgets/navigator.dart:139:17)
    E/flutter ( 5455): #2      _rootRunUnary (dart:async/zone.dart:1134:38)
    E/flutter ( 5455): #3      _CustomZone.runUnary (dart:async/zone.dart:1031:19)
    E/flutter ( 5455): #4      _FutureListener.handleValue (dart:async/future_impl.dart:139:18)
    E/flutter ( 5455): #5      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:680:45)
    E/flutter ( 5455): #6      Future._propagateToListeners (dart:async/future_impl.dart:709:32)
    E/flutter ( 5455): #7      Future._completeWithValue (dart:async/future_impl.dart:524:5)
    E/flutter ( 5455): #8      Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:554:7)
    E/flutter ( 5455): #9      _rootRun (dart:async/zone.dart:1126:13)
    E/flutter ( 5455): #10     _CustomZone.run (dart:async/zone.dart:1023:19)
    E/flutter ( 5455): #11     _CustomZone.runGuarded (dart:async/zone.dart:925:7)
    E/flutter ( 5455): #12     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:965:23)
    E/flutter ( 5455): #13     _microtaskLoop (dart:async/schedule_microtask.dart:43:21)
    E/flutter ( 5455): #14     _startMicrotaskLoop (dart:async/schedule_microtask.dart:52:5)
```
I have read this
https://github.com/flutter/flutter/issues/45539
and also this
https://stackoverflow.com/questions/59801993/flutter-nosuchmethoderror-the-getter-focusscopenode-was-called-on-null
but still I cannot find a way to make the problem go away, perhaps I haven't found the right implementation. 

Debugging showed me that this is the exact point where the problems occurs:
in the flutter system class navigator.dart

```
    @protected
      @mustCallSuper
      TickerFuture didPush() {
        return TickerFuture.complete()..then<void>((void _) {
          navigator.focusScopeNode.requestFocus(); // HERE IS WHERE HELL IS UNLEASHED
        });
      }
```

My classes are
1. the class that creates the tabbarview:

```
class Lounge extends StatefulWidget {
      const Lounge({ Key key }) : super(key: key);
      @override
      _LoungeState createState() => _LoungeState();
    }
    
    class _LoungeState extends State<Lounge> with SingleTickerProviderStateMixin {
      TabController _tabController;
      List<Widget> myWidgetList;
      List<Tab> myTabs = <Tab>[
        new Tab(icon: Icon(Icons.people)),
        new Tab(icon: Icon(Icons.location_on)),
        new Tab(icon: Icon(Icons.edit)),
      ];
    
      @override
      void initState() {
        super.initState();
        _tabController = TabController(vsync: this, length: myTabs.length);
        myWidgetList = <Widget>[Explore(),MyMap(),Edit()];
      }
    
      @override
      void dispose() {
        _tabController.dispose();
        super.dispose();
      }
    
      @override
      Widget build(BuildContext context) {
        return Scaffold(
            appBar: AppBar(
              title: TabBar(
                controller: _tabController,
                tabs: myTabs,
              ),
            ),
            body: TabBarView(
                physics: NeverScrollableScrollPhysics(),
                controller: _tabController,
                children: myWidgetList
            )
        );
      }
    }
```

And all the tab Material Widgets that build the tabs are exactly like below (Explore is the first one)

```
    class Explore extends StatefulWidget{
      @override
      _ExploreState createState()=> _ExploreState();
    }
    class _ExploreState extends State<Explore> {
      @override
      Widget build(BuildContext context) {
        return MaterialApp(
            title: 'Explore questionsets',
            theme: ThemeData(
              primarySwatch: Colors.blue,
            ),
            home: Scaffold(backgroundColor: Colors.blue[50],
              body: Center(
                child:         Text("explore")
              ),
            )
        );
      }
    }
```

**Comment by sarimk80** [comment]
Try removing the materialApp from the explore widget
```
import 'package:flutter/material.dart';

class Explore extends StatefulWidget {
  Explore({Key key}) : super(key: key);

  @override
  _ExploreState createState() => _ExploreState();
}

class _ExploreState extends State<Explore> {
  @override
  Widget build(BuildContext context) {
    // return MaterialApp(
    //     title: 'Explore questionsets',
    //     theme: ThemeData(
    //       primarySwatch: Colors.blue,
    //     ),
    //     home: Scaffold(
    //       backgroundColor: Colors.blue[50],
    //       body: Center(child: Text("explore")),
    //     ));
    return Scaffold(
      body: Center(
        child: Text("Explore"),
      ),
    );
  }
}

```

**Comment by oupat** [comment]
> 
> 
> Try removing the materialApp from the explore widget
> 
> ```
> import 'package:flutter/material.dart';
> 
> class Explore extends StatefulWidget {
>   Explore({Key key}) : super(key: key);
> 
>   @override
>   _ExploreState createState() => _ExploreState();
> }
> 
> class _ExploreState extends State<Explore> {
>   @override
>   Widget build(BuildContext context) {
>     // return MaterialApp(
>     //     title: 'Explore questionsets',
>     //     theme: ThemeData(
>     //       primarySwatch: Colors.blue,
>     //     ),
>     //     home: Scaffold(
>     //       backgroundColor: Colors.blue[50],
>     //       body: Center(child: Text("explore")),
>     //     ));
>     return Scaffold(
>       body: Center(
>         child: Text("Explore"),
>       ),
>     );
>   }
> }
> ```You 're so right... I wasted so many hours in such a thing...
Thank you with all my heart

**Comment by iapicca** [comment]
Hi @oupat 
I'm glad that you fixed the issue,
closing now, if you disagree please write in the comments and I will reopen it
Thank you
