### ISSUE TITLE
The 'Pods-Runner' target has transitive dependencies that include statically linked binaries:

### ISSUE THREAD

**Issue by LPzoe** [flutter/flutter#52598]
## Steps to Reproduce

1. ios Error running pod install
flutter run --verbose 
```
#0      throwToolExit (package:flutter_tools/src/base/common.dart:28:3)
#1      CocoaPods._runPodInstall (package:flutter_tools/src/macos/cocoapods.dart:326:7)
<asynchronous suspension>
#2      CocoaPods.processPods (package:flutter_tools/src/macos/cocoapods.dart:145:15)
<asynchronous suspension>
#3      processPodsIfNeeded (package:flutter_tools/src/macos/cocoapod_utils.dart:36:46)
<asynchronous suspension>
#4      buildXcodeProject (package:flutter_tools/src/ios/mac.dart:357:9)
<asynchronous suspension>
#5      IOSDevice.startApp (package:flutter_tools/src/ios/devices.dart:296:50)
<asynchronous suspension>
#6      FlutterDevice.runHot (package:flutter_tools/src/resident_runner.dart:450:54)
<asynchronous suspension>
#7      HotRunner.run (package:flutter_tools/src/run_hot.dart:266:39)
#8      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:504:37)
<asynchronous suspension>
#9      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:615:18)
#10     _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:73:64)
#11     _rootRunUnary (dart:async/zone.dart:1134:38)
#12     _CustomZone.runUnary (dart:async/zone.dart:1031:19)
#13     _FutureListener.handleValue (dart:async/future_impl.dart:139:18)
#14     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:680:45)
#15     Future._propagateToListeners (dart:async/future_impl.dart:709:32)
#16     Future._completeWithValue (dart:async/future_impl.dart:524:5)
#17     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:32:15)
#18     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:290:13)
#19     RunCommand.usageValues (package:flutter_tools/src/commands/run.dart)
#20     _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:73:64)
#21     _rootRunUnary (dart:async/zone.dart:1134:38)
#22     _CustomZone.runUnary (dart:async/zone.dart:1031:19)
#23     _FutureListener.handleValue (dart:async/future_impl.dart:139:18)
#24     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:680:45)
#25     Future._propagateToListeners (dart:async/future_impl.dart:709:32)
#26     Future._completeWithValue (dart:async/future_impl.dart:524:5)
#27     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:32:15)
#28     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:290:13)
#29     IosProject.isSwift (package:flutter_tools/src/project.dart)
#30     _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:73:64)
#31     _rootRunUnary (dart:async/zone.dart:1134:38)
#32     _CustomZone.runUnary (dart:async/zone.dart:1031:19)
#33     _FutureListener.handleValue (dart:async/future_impl.dart:139:18)
#34     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:680:45)
#35     Future._propagateToListeners (dart:async/future_impl.dart:709:32)
#36     Future._completeWithValue (dart:async/future_impl.dart:524:5)
#37     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:32:15)
#38     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:290:13)
#39     IosProject.buildSettings (package:flutter_tools/src/project.dart)
#40     _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:73:64)
#41     _rootRunUnary (dart:async/zone.dart:1134:38)
#42     _CustomZone.runUnary (dart:async/zone.dart:1031:19)
#43     _FutureListener.handleValue (dart:async/future_impl.dart:139:18)
#44     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:680:45)
#45     Future._propagateToListeners (dart:async/future_impl.dart:709:32)
#46     Future._completeWithValue (dart:async/future_impl.dart:524:5)
#47     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:32:15)
#48     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:290:13)
#49     XcodeProjectInterpreter.getBuildSettings (package:flutter_tools/src/ios/xcodeproj.dart)
#50     _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:73:64)
#51     _rootRunUnary (dart:async/zone.dart:1134:38)
#52     _CustomZone.runUnary (dart:async/zone.dart:1031:19)
#53     _FutureListener.handleValue (dart:async/future_impl.dart:139:18)
#54     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:680:45)
#55     Future._propagateToListeners (dart:async/future_impl.dart:709:32)
#56     Future._completeWithValue (dart:async/future_impl.dart:524:5)
#57     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:32:15)
#58     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:290:13)
#59     _DefaultProcessUtils.run (package:flutter_tools/src/base/process.dart)
#60     _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:73:64)
#61     _rootRunUnary (dart:async/zone.dart:1134:38)
#62     _CustomZone.runUnary (dart:async/zone.dart:1031:19)
#63     _FutureListener.handleValue (dart:async/future_impl.dart:139:18)
#64     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:680:45)
#65     Future._propagateToListeners (dart:async/future_impl.dart:709:32)
#66     Future._completeWithValue (dart:async/future_impl.dart:524:5)
#67     Future.wait.<anonymous closure> (dart:async/future.dart:400:22)
#68     _rootRunUnary (dart:async/zone.dart:1134:38)
#69     _CustomZone.runUnary (dart:async/zone.dart:1031:19)
#70     _FutureListener.handleValue (dart:async/future_impl.dart:139:18)
#71     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:680:45)
#72     Future._propagateToListeners (dart:async/future_impl.dart:709:32)
#73     Future._complete (dart:async/future_impl.dart:514:7)
#74     _BufferingStreamSubscription.asFuture.<anonymous closure> (dart:async/stream_impl.dart:206:14)
#75     _rootRun (dart:async/zone.dart:1122:38)
#76     _CustomZone.run (dart:async/zone.dart:1023:19)
#77     _CustomZone.runGuarded (dart:async/zone.dart:925:7)
#78     _BufferingStreamSubscription._sendDone.sendDone (dart:async/stream_impl.dart:391:13)
#79     _BufferingStreamSubscription._sendDone (dart:async/stream_impl.dart:401:15)
#80     _BufferingStreamSubscription._close (dart:async/stream_impl.dart:285:7)
#81     _SinkTransformerStreamSubscription._close (dart:async/stream_transformers.dart:98:11)
#82     _EventSinkWrapper.close (dart:async/stream_transformers.dart:25:11)
#83     _StringAdapterSink.close (dart:convert/string_conversion.dart:251:11)
#84     _Utf8ConversionSink.close (dart:convert/string_conversion.dart:302:20)
#85     _ConverterStreamEventSink.close (dart:convert/chunked_conversion.dart:82:18)
#86     _SinkTransformerStreamSubscription._handleDone (dart:async/stream_transformers.dart:143:24)
#87     _rootRun (dart:async/zone.dart:1122:38)
#88     _CustomZone.run (dart:async/zone.dart:1023:19)
#89     _CustomZone.runGuarded (dart:async/zone.dart:925:7)
#90     _BufferingStreamSubscription._sendDone.sendDone (dart:async/stream_impl.dart:391:13)
#91     _BufferingStreamSubscription._sendDone (dart:async/stream_impl.dart:401:15)
#92     _BufferingStreamSubscription._close (dart:async/stream_impl.dart:285:7)
#93     _SyncStreamControllerDispatch._sendDone (dart:async/stream_controller.dart:774:19)
#94     _StreamController._closeUnchecked (dart:async/stream_controller.dart:631:7)
#95     _StreamController.close (dart:async/stream_controller.dart:624:5)
#96     _Socket._onData (dart:io-patch/socket_patch.dart:1838:21)
#97     _rootRunUnary (dart:async/zone.dart:1138:13)
#98     _CustomZone.runUnary (dart:async/zone.dart:1031:19)
#99     _CustomZone.runUnaryGuarded (dart:async/zone.dart:933:7)
#100    _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:338:11)
#101    _BufferingStreamSubscription._add (dart:async/stream_impl.dart:265:7)
#102    _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:766:19)
#103    _StreamController._add (dart:async/stream_controller.dart:642:7)
#104    _StreamController.add (dart:async/stream_controller.dart:588:5)
#105    new _RawSocket.<anonymous closure> (dart:io-patch/socket_patch.dart:1386:35)
#106    _NativeSocket.issueReadEvent.issue (dart:io-patch/socket_patch.dart:892:18)
#107    _microtaskLoop (dart:async/schedule_microtask.dart:43:21)
#108    _startMicrotaskLoop (dart:async/schedule_microtask.dart:52:5)
#109    _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
#110    _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:175:5)
```

```
[✓] Flutter (Channel stable, v1.12.13+hotfix.8, on Mac OS X 10.15.2 19C57,
    locale zh-Hans-CN)
    • Flutter version 1.12.13+hotfix.8 at /Users/Txm/flutter
    • Framework revision 0b8abb4724 (5 weeks ago), 2020-02-11 11:44:36 -0800
    • Engine revision e1e6ced81d
    • Dart version 2.7.0

 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/Txm/Library/Android/sdk
    • Android NDK at /Users/Txm/Library/Android/sdk/ndk-bundle
    • Platform android-29, build-tools 28.0.3
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.3.1, Build version 11C504
    • CocoaPods version 1.9.0.beta.2

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 42.1.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build
      1.8.0_202-release-1483-b49-5587405)

[✓] IntelliJ IDEA Ultimate Edition (version 2018.1.3)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 31.3.1
    • Dart plugin version 181.4892.1

[✓] VS Code (version 1.41.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.8.1

[✓] Connected device (1 available)
    • iPhone (3) • 00008020-001825C40288002E • ios • iOS 12.4.1
```

**Comment by LPzoe** [comment]
flutter 重新安装就可以了
