### ISSUE TITLE
find.pageBack doesn't work with internationalization

### ISSUE THREAD

**Issue by tianhaoz95** [flutter/flutter#52594]
## Steps to Reproduce

1. Write an integration test with `driver.tap(find.pageBack())`
2. Run `flutter drive ./test_drive/app.dart`
3. Test hang

Likely because internationalization changes the tooltip and the driver doesn't recognize anymore.

**Expected results:** 

It should tap the back button and page back.

**Actual results:** 

Test hang and eventually timeout.

**Comment by iapicca** [comment]
Hi @tianhaoz95
can you please provide your `flutter doctor -v` , 
your `flutter drive --verbose` 
and your `pubspec.yaml` 
Thank you

**Comment by tianhaoz95** [comment]
Hmmm... I have fixed the issue with a `key` in the `leading` `iconButton` of `appBar`, but the issue will persist for the reason I stated because the driver cannot find a localized tooltip.

Here is my `flutter doctor -v`:

```bash
[✓] Flutter (Channel dev, v1.15.21, on Mac OS X 10.15.3 19D76, locale en)
    • Flutter version 1.15.21 at /Users/tianhaozhou/Documents/flutter
    • Framework revision e2b4edd286 (3 days ago), 2020-03-13 02:46:02 -0400
    • Engine revision d7a00b8b09
    • Dart version 2.8.0 (build 2.8.0-dev.14.0 eb9c26bd37)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/tianhaozhou/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.3.1, Build version 11C504
    • CocoaPods version 1.8.4

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 43.0.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] VS Code (version 1.42.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.8.1

[✓] Connected device (4 available)
    • iPhone 11 Pro Max • 5F6A6147-4E28-4ADC-A375-202789C4E90E • ios            • com.apple.CoreSimulator.SimRuntime.iOS-13-3
      (simulator)
    • macOS             • macOS                                • darwin-x64     • Mac OS X 10.15.3 19D76
    • Chrome            • chrome                               • web-javascript • Google Chrome 80.0.3987.132
    • Web Server        • web-server                           • web-javascript • Flutter Tools

• No issues found!
```

**Comment by iapicca** [comment]
Hi again @tianhaoz95 
could you please provide your `flutter drive --verbose` 
as well
Thank you

**Comment by tianhaoz95** [comment]
that will take some time as i need to go back and find the bad commit. as I am repro the issue with `--verbose`, a quick error message from my memory is: `tap is taking long` when it is supposed to click on the page back button.

**Comment by TahaTesser** [comment]
HI @tianhaoz95 
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
Thanks for your contribution.

**Comment by Gorniv** [comment]
You use 'Back' for find back button by tooltip https://github.com/flutter/flutter/blob/d47ad7ec0dc0e65aeab9b2f590908b9e4faeaa5e/packages/flutter_driver/lib/src/extension/extension.dart#L349

**Comment by le-kamba** [comment]
Hi, I'm having same issue.
On both Android emulator and iOS simulator, `driver.tap(find.pageBack())` or `driver.tap(find.byTooltip('Back')` doesn't work.

Error message is:

```
  DriverError: Failed to fulfill Tap due to remote error
  Original error: Bad state: The client closed with pending request "ext.flutter.driver".
  Original stack trace:
  #0      new Client.withoutJson.<anonymous closure> (package:json_rpc_2/src/client.dart:70:24)
  #1      StackZoneSpecification._run (package:stack_trace/src/stack_zone_specification.dart:209:15)
  #2      StackZoneSpecification._registerCallback.<anonymous closure> (package:stack_trace/src/stack_zone_specification.dart:119:48)
  #3      _rootRun (dart:async/zone.dart:1122:38)
  #4      _CustomZone.run (dart:async/zone.dart:1023:19)
  #5      _FutureListener.handleWhenComplete (dart:async/future_impl.dart:163:18)
  #6      Future._propagateToListeners.handleWhenCompleteCallback (dart:async/future_impl.dart:650:39)
  #7      Future._propagateToListeners (dart:async/future_impl.dart:706:37)
  #8      Future._propagateToListeners (dart:async/future_impl.dart:607:9)
  #9      Future._completeWithValue (dart:async/future_impl.dart:524:5)
  #10     Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:554:7)
  #11     StackZoneSpecification._run (package:stack_trace/src/stack_zone_specification.dart:209:15)
  #12     StackZoneSpecification._registerCallback.<anonymous closure> (package:stack_trace/src/stack_zone_specification.dart:119:48)
  #13     _rootRun (dart:async/zone.dart:1126:13)
  #14     _CustomZone.run (dart:async/zone.dart:1023:19)
  #15     _CustomZone.runGuarded (dart:async/zone.dart:925:7)
  #16     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:965:23)
  #17     _microtaskLoop (dart:async/schedule_microtask.dart:43:21)
  #18     _startMicrotaskLoop (dart:async/schedule_microtask.dart:52:5)
  #19     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:393:30)
  #20     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:418:5)
  #21     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:174:12)



  package:flutter_driver/src/driver/driver.dart 449:7           FlutterDriver._sendCommand
  ===== asynchronous gap ===========================
  dart:async/zone.dart 1064:19                                  _CustomZone.registerBinaryCallback
  dart:async-patch/async_patch.dart 82:23                       _asyncErrorWrapperHelper
  package:test_api/src/backend/invoker.dart                     Invoker.waitForOutstandingCallbacks.<fn>
  dart:async/zone.dart 1126:13                                  _rootRun
  dart:async/zone.dart 1023:19                                  _CustomZone.run
  dart:async/zone.dart 1518:10                                  _runZoned
  dart:async/zone.dart 1465:12                                  runZoned
  package:test_api/src/backend/invoker.dart 239:5               Invoker.waitForOutstandingCallbacks
  package:test_api/src/backend/declarer.dart 169:33             Declarer.test.<fn>.<fn>
  dart:async/zone.dart 1126:13                                  _rootRun
  dart:async/zone.dart 1023:19                                  _CustomZone.run
  dart:async/zone.dart 1518:10                                  _runZoned
  dart:async/zone.dart 1465:12                                  runZoned
  package:test_api/src/backend/declarer.dart 168:13             Declarer.test.<fn>
  package:test_api/src/backend/invoker.dart 392:25              Invoker._onRun.<fn>.<fn>.<fn>.<fn>
  dart:async/future.dart 176:37                                 new Future.<fn>
  package:stack_trace/src/stack_zone_specification.dart 209:15  StackZoneSpecification._run
  package:stack_trace/src/stack_zone_specification.dart 119:48  StackZoneSpecification._registerCallback.<fn>
  dart:async/zone.dart 1122:38                                  _rootRun
  dart:async/zone.dart 1023:19                                  _CustomZone.run
  dart:async/zone.dart 925:7                                    _CustomZone.runGuarded
  dart:async/zone.dart 965:23                                   _CustomZone.bindCallbackGuarded.<fn>
  package:stack_trace/src/stack_zone_specification.dart 209:15  StackZoneSpecification._run
  package:stack_trace/src/stack_zone_specification.dart 119:48  StackZoneSpecification._registerCallback.<fn>
  dart:async/zone.dart 1126:13                                  _rootRun
  dart:async/zone.dart 1023:19                                  _CustomZone.run
  dart:async/zone.dart 949:23                                   _CustomZone.bindCallback.<fn>
  dart:async-patch/timer_patch.dart 23:15                       Timer._createTimer.<fn>
  dart:isolate-patch/timer_impl.dart 384:19                     _Timer._runTimers
  dart:isolate-patch/timer_impl.dart 418:5                      _Timer._handleMessage
  dart:isolate-patch/isolate_patch.dart 174:12                  _RawReceivePortImpl._handleMessage
  ===== asynchronous gap ===========================
  dart:async/zone.dart 1047:19                                  _CustomZone.registerCallback
  dart:async/zone.dart 964:22                                   _CustomZone.bindCallbackGuarded
  dart:async/timer.dart 54:45                                   new Timer
  dart:async/timer.dart 91:9                                    Timer.run
  dart:async/future.dart 174:11                                 new Future
  package:test_api/src/backend/invoker.dart 391:21              Invoker._onRun.<fn>.<fn>.<fn>
  dart:async/zone.dart 1126:13                                  _rootRun
  dart:async/zone.dart 1023:19                                  _CustomZone.run
  dart:async/zone.dart 1518:10                                  _runZoned
  dart:async/zone.dart 1465:12                                  runZoned
  package:test_api/src/backend/invoker.dart 378:9               Invoker._onRun.<fn>.<fn>
  package:test_api/src/backend/invoker.dart 430:15              Invoker._guardIfGuarded
  package:test_api/src/backend/invoker.dart 377:7               Invoker._onRun.<fn>
  package:stack_trace/src/chain.dart 101:24                     Chain.capture.<fn>
  dart:async/zone.dart 1126:13                                  _rootRun
  dart:async/zone.dart 1023:19                                  _CustomZone.run
  dart:async/zone.dart 1518:10                                  _runZoned
  dart:async/zone.dart 1465:12                                  runZoned
  package:stack_trace/src/chain.dart 99:12                      Chain.capture
  package:test_api/src/backend/invoker.dart 376:11              Invoker._onRun
  package:test_api/src/backend/live_test_controller.dart 185:5  LiveTestController._run
  package:test_api/src/backend/live_test_controller.dart 40:37  _LiveTest.run
  dart:async/future.dart 202:37                                 new Future.microtask.<fn>
  dart:async/zone.dart 1122:38                                  _rootRun
  dart:async/zone.dart 1023:19                                  _CustomZone.run
  dart:async/zone.dart 925:7                                    _CustomZone.runGuarded
  dart:async/zone.dart 965:23                                   _CustomZone.bindCallbackGuarded.<fn>
  dart:async/zone.dart 1126:13                                  _rootRun
  dart:async/zone.dart 1023:19                                  _CustomZone.run
  dart:async/zone.dart 925:7                                    _CustomZone.runGuarded
  dart:async/zone.dart 965:23                                   _CustomZone.bindCallbackGuarded.<fn>
  dart:async/schedule_microtask.dart 43:21                      _microtaskLoop
  dart:async/schedule_microtask.dart 52:5                       _startMicrotaskLoop
  dart:isolate-patch/timer_impl.dart 393:30                     _Timer._runTimers
  dart:isolate-patch/timer_impl.dart 418:5                      _Timer._handleMessage
  dart:isolate-patch/isolate_patch.dart 174:12                  _RawReceivePortImpl._handleMessage
```

Here is my flutter doctor -v:

```
$ flutter doctor -v
[✓] Flutter (Channel stable, v1.12.13+hotfix.9, on Mac OS X 10.14.6 18G103,
    locale ja-JP)
    • Flutter version 1.12.13+hotfix.9 at /develop/flutter
    • Framework revision f139b11009 (6 weeks ago), 2020-03-30 13:57:30 -0700
    • Engine revision af51afceb8
    • Dart version 2.7.2

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /develop/android_sdk
    • Android NDK location not configured (optional; useful for native profiling
      support)
    • Platform android-29, build-tools 29.0.2
    • ANDROID_HOME = /develop/android_sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.3.1, Build version 11C505
    • CocoaPods version 1.8.4

[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build
      1.8.0_212-release-1586-b4-5784211)

[✓] Connected device (1 available)
    • iPhone 11 Pro Max • E050806B-6BB0-4107-8494-1D8F57BECE96 • ios •
      com.apple.CoreSimulator.SimRuntime.iOS-13-3 (simulator)

• No issues found!
```

My localizations setting is:

```
      localizationsDelegates: [
        GlobalMaterialLocalizations.delegate,
        GlobalWidgetsLocalizations.delegate,
        GlobalCupertinoLocalizations.delegate,
      ],
      supportedLocales: [
        Locale('ja', ''), // Japanese only
      ],
```

**Comment by TahaTesser** [comment]
Could everyone who still has this problem please file a new issue with the exact descriptions
what happens, logs and the output of 'flutter doctor -v' please.
All system setups can be slightly different so it's always better to open new issues and reference
related issues.
Thank you
