### ISSUE TITLE
[tool_crash] WipError 5: {code: -32000, message: Cannot find context with specified id}

### ISSUE THREAD

**Issue by abdulla-bey01** [flutter/flutter#52611]
## Command
```
flutter run -d chrome
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
WipError: WipError 5: {code: -32000, message: Cannot find context with specified id}
```
#0      AppInspector._getExtensionRpcs (package:dwds/src/debugging/inspector.dart:419:9)
<asynchronous suspension>
#1      AppInspector._initialize (package:dwds/src/debugging/inspector.dart:92:40)
<asynchronous suspension>
#2      AppInspector.initialize (package:dwds/src/debugging/inspector.dart:144:24)
#3      ChromeProxyService.createIsolate (package:dwds/src/services/chrome_proxy_service.dart:140:37)
<asynchronous suspension>
#4      ChromeProxyService.create (package:dwds/src/services/chrome_proxy_service.dart:121:23)
#5      DebugService.start (package:dwds/src/services/debug_service.dart:140:55)
#6      DevHandler._startLocalDebugService (package:dwds/src/handlers/dev_handler.dart:153:25)
#7      _rootRunUnary (dart:async/zone.dart:1134:38)
#8      _CustomZone.runUnary (dart:async/zone.dart:1031:19)
#9      _FutureListener.handleValue (dart:async/future_impl.dart:140:18)
#10     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:682:45)
#11     Future._propagateToListeners (dart:async/future_impl.dart:711:32)
#12     Future._completeWithValue (dart:async/future_impl.dart:526:5)
#13     Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:556:7)
#14     _rootRun (dart:async/zone.dart:1126:13)
#15     _CustomZone.run (dart:async/zone.dart:1023:19)
#16     _CustomZone.runGuarded (dart:async/zone.dart:925:7)
```
```
[✓] Flutter (Channel master, v1.15.22-pre.24, on Microsoft Windows [Version 10.0.18363.719], locale en-US)
    • Flutter version 1.15.22-pre.24 at C:\src\flutter
    • Framework revision aba0e2dc8f (18 hours ago), 2020-03-13 23:21:03 -0400
    • Engine revision e48761e5bb
    • Dart version 2.8.0 (build 2.8.0-dev.14.0 c3a0bb086a)

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at C:\Users\PC15\AppData\Local\Android\Sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[!] Visual Studio - develop for Windows (Visual Studio Community 2019 16.4.6)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.4.29905.134
    ✗ The current Visual Studio installation is incomplete. Please reinstall Visual Studio.

[✓] Android Studio (version 3.6)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 44.0.2
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)

[✓] VS Code (version 1.43.0)
    • VS Code at C:\Users\PC15\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.8.1

[✓] Connected device (3 available)
    • Windows    • Windows    • windows-x64    • Microsoft Windows [Version 10.0.18363.719]
    • Chrome     • chrome     • web-javascript • Google Chrome 80.0.3987.132
    • Web Server • web-server • web-javascript • Flutter Tools

! Doctor found issues in 1 category.

```

## Flutter Application Metadata
**Version**: 1.0.0+1
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null

**Comment by VladyslavBondarenko** [comment]
Hi @abdulla-bey01 
Can you provide a minimal complete code sample to reproduce the error?

**Comment by jonahwilliams** [comment]
FYI @grouma , this is from before the dwds update I think

**Comment by grouma** [comment]
Yes this should now be resolved at HEAD.
