### ISSUE TITLE
debug error on iphone xr

### ISSUE THREAD

**Issue by LPzoe** [flutter/flutter#52725]
Flutter crash report; please file at https://github.com/flutter/flutter/issues.

## command

flutter run --machine --target lib/main.dart -d 00008020-001825C40288002E --track-widget-creation --start-paused

## exception

RangeError: RangeError: Value not in range: 140

```
#0      _rangeCheck (dart:typed_data-patch/typed_data_patch.dart:4631:5)
#1      _ByteBuffer.asUint8List (dart:typed_data-patch/typed_data_patch.dart:1931:5)
#2      new Uint8List.view (dart:typed_data:847:19)
#3      decodeMDnsResponse.readResourceRecord (package:multicast_dns/src/packet.dart:347:23)
#4      decodeMDnsResponse (package:multicast_dns/src/packet.dart:376:55)
#5      MDnsClient._handleIncoming (package:multicast_dns/multicast_dns.dart:221:45)
#6      _rootRunUnary (dart:async/zone.dart:1138:13)
#7      _CustomZone.runUnary (dart:async/zone.dart:1031:19)
#8      _CustomZone.runUnaryGuarded (dart:async/zone.dart:933:7)
#9      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:338:11)
#10     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:265:7)
#11     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:766:19)
#12     _StreamController._add (dart:async/stream_controller.dart:642:7)
#13     _StreamController.add (dart:async/stream_controller.dart:588:5)
#14     new _RawDatagramSocket.<anonymous closure> (dart:io-patch/socket_patch.dart:1922:33)
#15     _NativeSocket.issueReadEvent.issue (dart:io-patch/socket_patch.dart:899:14)
#16     _microtaskLoop (dart:async/schedule_microtask.dart:43:21)
#17     _startMicrotaskLoop (dart:async/schedule_microtask.dart:52:5)
#18     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
#19     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:175:5)
```

## flutter doctor

```
[✓] Flutter (Channel unknown, v1.12.13+hotfix.5, on Mac OS X 10.15.2 19C57, locale zh-Hans-CN)
    • Flutter version 1.12.13+hotfix.5 at /Users/Txm/flutter
    • Framework revision 27321ebbad (3 months ago), 2019-12-10 18:15:01 -0800
    • Engine revision 2994f7e1e6
    • Dart version 2.7.0

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/Txm/Library/Android/sdk
    • Android NDK at /Users/Txm/Library/Android/sdk/ndk-bundle
    • Platform android-29, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.3.1, Build version 11C504
    • CocoaPods version 1.9.0.beta.2

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 42.1.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] IntelliJ IDEA Ultimate Edition (version 2018.1.3)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 31.3.1
    • Dart plugin version 181.4892.1

[✓] VS Code (version 1.41.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.8.1

[✓] Connected device (1 available)
    • iPhone (3) • 00008020-001825C40288002E • ios • iOS 12.4.1

• No issues found!
```

**Comment by VladyslavBondarenko** [comment]
Hi @LPzoe 
can you reproduce it? if yes could you provide a minimal reproducible complete code sample?

**Comment by LPzoe** [comment]
After starting xcode, I started vscode again and there was no error，thanks

> Hi @LPzoe
> can you reproduce it? if yes could you provide a minimal reproducible complete code sample?

After starting xcode, I started vscode again and there was no error，thanks
