### ISSUE TITLE
[SelectableText] has got a problem

### ISSUE THREAD

**Issue by aliyazdi75** [flutter/flutter#52741]
I have tested the `SelectableText` widget on all platforms and, it seems it has a problem while selecting text for example this simple code `SelectableText('This is SelectableText')` with material app builder.
Here's my `flutter doctor` output:
```
[✓] Flutter (Channel master, v1.15.19, on Linux, locale en_US.UTF-8)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
[✓] Chrome - develop for the web
[✓] Linux toolchain - develop for Linux desktop
[✓] Android Studio (version 3.6)
[✓] Connected device (4 available)
```
<details>
  <summary>Linux and Mobile Logs</summary>

```
════════ Exception caught by gesture ═══════════════════════════════════════════════════════════════
The following assertion was thrown while handling a gesture:
No Overlay widget exists above EditableText-[LabeledGlobalKey<EditableTextState>#9f349](controller: _TextSpanEditingController#692f3(TextEditingValue(text: ┤This is SelectableText├, selection: TextSelection(baseOffset: 8, extentOffset: 22, affinity: TextAffinity.downstream, isDirectional: false), composing: TextRange(start: -1, end: -1))), focusNode: FocusNode#c5d09, debugLabel: (englishLike body1 2014).merge((((whiteMountainView bodyText2).copyWith).copyWith).apply), inherit: false, color: Color(0xffffffff), family: Montserrat_regular, familyFallback: [Montserrat], size: 16.0, weight: 400, baseline: alphabetic, decoration: TextDecoration.none, textAlign: start, maxLines: null, keyboardType: TextInputType(name: TextInputType.multiline, signed: null, decimal: null), dirty, dependencies: [_FocusMarker, Directionality, MediaQuery], state: EditableTextState#1eb8a(tickers: tracking 2 tickers)).
Usually the Navigator created by WidgetsApp provides the overlay. Perhaps your app content was created above the Navigator with the WidgetsApp builder parameter.
'package:flutter/src/widgets/text_selection.dart':
Failed assertion: line 287 pos 12: 'overlay != null'


Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=BUG.md

When the exception was thrown, this was the stack: 
#2      new TextSelectionOverlay (package:flutter/src/widgets/text_selection.dart:287:12)
#3      EditableTextState._handleSelectionChanged (package:flutter/src/widgets/editable_text.dart:1554:27)
#4      RenderEditable._handleSelectionChange (package:flutter/src/rendering/editable.dart:429:7)
#5      RenderEditable.selectWordsInRange (package:flutter/src/rendering/editable.dart:1634:5)
#6      RenderEditable.selectWord (package:flutter/src/rendering/editable.dart:1613:5)
...
Handler: "onLongPressStart"
Recognizer: LongPressGestureRecognizer#e9535
  debugOwner: _TextSelectionGestureDetectorState#bfabd
  state: possible
════════════════════════════════════════════════════════════════════════════════════════════════════
```
</details>

<details>
  <summary>Web Logs</summary>

```
══╡ EXCEPTION CAUGHT BY GESTURE ╞═══════════════════════════════════════════════════════════════════
The following assertion was thrown while handling a gesture:
Assertion failed:
file:///home/aliyazdi75/flutter/packages/flutter/lib/src/widgets/text_selection.dart:287:12
overlay != null
"No Overlay widget exists above EditableText-[LabeledGlobalKey<EditableTextState>#ebc45](controller:
_TextSpanEditingController#38c09(TextEditingValue(text: ┤This is Selectable Text├, selection:
TextSelection(baseOffset: 14, extentOffset: 14, affinity: TextAffinity.upstream, isDirectional:
false), composing: TextRange(start: -1, end: -1))), focusNode: FocusNode#844a5, debugLabel:
(englishLike body1 2014).merge(blackMountainView bodyText2), inherit: false, color:
Color(0xdd000000), family: Roboto, size: 14.0, weight: 400, baseline: alphabetic, decoration:
TextDecoration.none, textAlign: start, maxLines: null, keyboardType: TextInputType(name:
TextInputType.multiline, signed: null, decimal: null), dirty, dependencies: [_FocusMarker,
Directionality, MediaQuery], state: EditableTextState#23ec7(tickers: tracking 2 tickers)).\nUsually
the Navigator created by WidgetsApp provides the overlay. Perhaps your app content was created above
the Navigator with the WidgetsApp builder parameter."

When the exception was thrown, this was the stack:
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 196:49  throw_
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 26:3    assertFailed
package:flutter/src/widgets/text_selection.dart 287:23                        new
package:flutter/src/widgets/editable_text.dart 1554:27                        [_handleSelectionChanged]
package:flutter/src/rendering/editable.dart 429:7                             [_handleSelectionChange]
package:flutter/src/rendering/editable.dart 1606:5                            selectPositionAt
package:flutter/src/widgets/text_selection.dart 1061:20                       onDragSelectionStart
package:flutter/src/widgets/text_selection.dart 1287:14                       [_handleDragStart]
package:flutter/src/gestures/monodrag.dart 384:45                             <fn>
package:flutter/src/gestures/recognizer.dart 182:24                           invokeCallback
package:flutter/src/gestures/monodrag.dart 384:62                             [_checkStart]
package:flutter/src/gestures/monodrag.dart 308:7                              acceptGesture
package:flutter/src/gestures/arena.dart 250:10                                [_resolveByDefault]
package:flutter/src/gestures/arena.dart 231:31                                callback
dart-sdk/lib/async/schedule_microtask.dart 43:11                              _microtaskLoop
dart-sdk/lib/async/schedule_microtask.dart 52:5                               _startMicrotaskLoop
dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 168:15           <fn>

Handler: "onStart"
Recognizer:
HorizontalDragGestureRecognizer#0eb2e
════════════════════════════════════════════════════════════════════════════════════════════════════
```
</details>

**Comment by aliyazdi75** [comment]
Notice that without material app builder and using home, it works.
