### ISSUE TITLE
[tool_crash] FileSystemException: Cannot open file, path = 'C:\src\qrcode_scan_browsing\windows\Runner.sln' (OS Error: The system cannot find the file specified., errno = 2)

### ISSUE THREAD

**Issue by mhakrook** [flutter/flutter#52788]
## Command
```
flutter build apk
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
FileSystemException: FileSystemException: Cannot open file, path = 'C:\src\qrcode_scan_browsing\windows\Runner.sln' (OS Error: The system cannot find the file specified.
, errno = 2)
```
#0      _File.open.<anonymous closure> (dart:io/file_impl.dart:366:9)
#1      _rootRunUnary (dart:async/zone.dart:1141:38)
#2      _CustomZone.runUnary (dart:async/zone.dart:1034:19)
#3      _FutureListener.handleValue (dart:async/future_impl.dart:140:18)
#4      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:681:45)
#5      Future._propagateToListeners (dart:async/future_impl.dart:710:32)
#6      Future._completeWithValue (dart:async/future_impl.dart:525:5)
#7      Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:555:7)
#8      _rootRun (dart:async/zone.dart:1133:13)
#9      _CustomZone.run (dart:async/zone.dart:1026:19)
#10     _CustomZone.runGuarded (dart:async/zone.dart:928:7)
#11     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:968:23)
#12     _microtaskLoop (dart:async/schedule_microtask.dart:43:21)
#13     _startMicrotaskLoop (dart:async/schedule_microtask.dart:52:5)
#14     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
#15     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:169:5)
```
```
[✓] Flutter (Channel master, v1.15.23-pre.27, on Microsoft Windows [Version 10.0.18363.720], locale en-US)
    • Flutter version 1.15.23-pre.27 at C:\src\flutter
    • Framework revision b7101b45f5 (2 hours ago), 2020-03-17 19:07:22 -0700
    • Engine revision 083a7c2bca
    • Dart version 2.8.0 (build 2.8.0-dev.14.0 db5dc11b9b)

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at C:\Users\mak_r\AppData\Local\Android\Sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 28.0.3
    • ANDROID_HOME = C:\Users\mak_r\AppData\Local\Android\Sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)
    • All Android licenses accepted.

[✓] Visual Studio - develop for Windows (Visual Studio Community 2019 16.4.2)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.4.29613.14

[✓] Android Studio (version 3.5)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 42.1.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)

[✓] VS Code (version 1.43.0)
    • VS Code at C:\Users\mak_r\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.8.1

[✓] Connected device (1 available)
    • Windows • Windows • windows-x64 • Microsoft Windows [Version 10.0.18363.720]

• No issues found!

```

## Flutter Application Metadata
**Version**: 1.0.2+1
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
### Plugins
firebase_core-0.4.3+2
firebase_core_web-0.1.1+2
firebase_database-3.1.1
firebase_messaging-6.0.9
firebase_storage-3.1.1
flutter_share-1.0.2+1
flutter_webview_plugin-0.3.10+1
qrscan-0.2.17
shared_preferences-0.5.6+1
shared_preferences_macos-0.0.1+3
shared_preferences_web-0.1.2+2
url_launcher-5.4.1
url_launcher_macos-0.0.1+2
url_launcher_web-0.1.0+2

**Comment by TahaTesser** [comment]
Hi @mhakrook 
Are you trying to build apk or Windows build?
I see Windows as connected device and error is related to [#https://github.com/flutter/flutter/issues/40700](https://github.com/flutter/flutter/issues/40700)
Thank you

**Comment by TahaTesser** [comment]
Hi @mhakrook 
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
Thanks for your contribution.
