### ISSUE TITLE
[tool_crash] NoSuchMethodError: The method 'toFilePath' was called on null.Receiver: nullTried calling: toFilePath()

### ISSUE THREAD

**Issue by githubityu** [flutter/flutter#52803]
## Command
```
flutter run -d chrome
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
NoSuchMethodError: NoSuchMethodError: The method 'toFilePath' was called on null.
Receiver: null
Tried calling: toFilePath()
```
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:53:5)
#1      defaultHandler (package:devtools_server/src/handlers.dart:28:60)
<asynchronous suspension>
#2      serveDevTools (package:devtools_server/src/server.dart:144:21)
#3      DevTools.start (package:dwds/src/servers/devtools.dart:27:15)
#4      Dwds.start (package:dwds/dwds.dart:111:33)
#5      WebAssetServer.start (package:flutter_tools/src/build_runner/devfs_web.dart:85:36)
<asynchronous suspension>
#6      WebDevFS.create (package:flutter_tools/src/build_runner/devfs_web.dart:460:43)
#7      _ResidentWebRunner.run.<anonymous closure> (package:flutter_tools/src/build_runner/resident_web_runner.dart:421:44)
#8      asyncGuard.<anonymous closure> (package:flutter_tools/src/base/async_guard.dart:111:32)
#9      _rootRun (dart:async/zone.dart:1126:13)
#10     _CustomZone.run (dart:async/zone.dart:1023:19)
#11     _runZoned (dart:async/zone.dart:1518:10)
#12     runZoned (dart:async/zone.dart:1502:12)
#13     asyncGuard (package:flutter_tools/src/base/async_guard.dart:109:3)
#14     _ResidentWebRunner.run (package:flutter_tools/src/build_runner/resident_web_runner.dart:411:20)
<asynchronous suspension>
#15     RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:563:37)
<asynchronous suspension>
```
```
[✓] Flutter (Channel beta, v1.15.17, on Microsoft Windows [Version 10.0.17134.1365], locale zh-CN)
    • Flutter version 1.15.17 at E:\flutter\flutter
    • Framework revision 2294d75bfa (12 days ago), 2020-03-07 00:28:38 +0900
    • Engine revision 5aff311948
    • Dart version 2.8.0 (build 2.8.0-dev.12.0 9983424a3c)

[!] Android toolchain - develop for Android devices (Android SDK version 29.0.0)
    • Android SDK at D:\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.0
    • ANDROID_HOME = D:\sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[✓] Android Studio (version 3.6)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 44.0.2
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)

[✓] IntelliJ IDEA Ultimate Edition (version 2019.3)
    • IntelliJ at E:\soft_exe\IntelliJ IDEA 2019.3.3
    • Flutter plugin version 44.0.3
    • Dart plugin version 193.6494.35

[✓] Connected device (3 available)
    • Android SDK built for x86 • emulator-5554 • android-x86    • Android 9 (API 28) (emulator)
    • Chrome                    • chrome        • web-javascript • Google Chrome 80.0.3987.132
    • Web Server                • web-server    • web-javascript • Flutter Tools

! Doctor found issues in 1 category.

```

## Flutter Application Metadata
**Version**: 1.0.0+1
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null

**Comment by TahaTesser** [comment]
Related to [#44459](https://github.com/flutter/flutter/issues/44459)

**Comment by jonahwilliams** [comment]
Fixed by https://github.com/flutter/flutter/pull/52284
