### ISSUE TITLE
Bug with Flutter flavours when using multiple dimensions

### ISSUE THREAD

**Issue by anik786** [flutter/flutter#52905]
## Steps to Reproduce

1. Run `$ flutter create flutter_bug`
2. Update the files as follows:

**`android/app/build.gradle`**
```
...
android {
    ...
    flavorDimensions "tenant", "environment"
    productFlavors {
        app1 {
            dimension "tenant"
            applicationId "uk.co.myapplication.app1"
        }

        app2 {
            dimension "tenant"
            applicationId "uk.co.myapplication.app2"
        }

        local {
            dimension "environment"
            resValue "string", "app_name", "Local"
        }

        staging {
            dimension "environment"
            resValue "string", "app_name", "Staging"
        }
    }
}
...
```

3. 

Next run the following commands:

```
$ flutter clean
$ flutter run --flavor="app1Local"
```

**Expected results:** The app to run without error on your device.

**Actual results:**

I get the following error:

```
[        ] BUILD SUCCESSFUL in 22s
[        ] 30 actionable tasks: 29 executed, 1 up-to-date
[ +363 ms] Running Gradle task 'assembleApp1LocalDebug'... (completed in 23.1s)
[   +9 ms] "flutter run" took 23,950ms.
Gradle build failed to produce an .apk file. It's likely that this file was generated under C:\Users\yahya\Documents\sandbox\flutter_bug\build, but the tool couldn't find it.
```

The bug seems to be here:
https://github.com/flutter/flutter/blob/c1112d3f7ea8452ea0069407de588987894def09/packages/flutter_tools/lib/src/android/gradle.dart#L98

It seems that it's looking for the file: `build/app/outputs/app1Local/debug/app-app1Local-debug.apk`.

However, the file that was actually created is: `build/app/outputs/app1Local/debug/app-app1-local-debug.apk`.

A fix will be much appreciated 👍 

<details>
  <summary>Logs</summary>

```
[        ] BUILD SUCCESSFUL in 22s
[        ] 30 actionable tasks: 29 executed, 1 up-to-date
[ +363 ms] Running Gradle task 'assembleApp1LocalDebug'... (completed in 23.1s)
[   +9 ms] "flutter run" took 23,950ms.
Gradle build failed to produce an .apk file. It's likely that this file was generated under C:\Users\yahya\Documents\sandbox\flutter_bug\build, but the tool couldn't find it.

#0      throwToolExit (package:flutter_tools/src/base/common.dart:28:3)
#1      _exitWithExpectedFileNotFound (package:flutter_tools/src/android/gradle.dart:827:3)
#2      findApkFiles (package:flutter_tools/src/android/gradle.dart:765:5)
#3      buildGradleApp (package:flutter_tools/src/android/gradle.dart:451:35)
<asynchronous suspension>
#4      _AndroidBuilderImpl.buildApk (package:flutter_tools/src/android/android_builder.dart:97:13)
#5      AndroidDevice.startApp (package:flutter_tools/src/android/android_device.dart:522:28)
<asynchronous suspension>
#6      FlutterDevice.runHot (package:flutter_tools/src/resident_runner.dart:450:54)
#7      _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:73:64)
#8      _rootRunUnary (dart:async/zone.dart:1134:38)
#9      _CustomZone.runUnary (dart:async/zone.dart:1031:19)
#10     _FutureListener.handleValue (dart:async/future_impl.dart:139:18)
#11     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:680:45)
#12     Future._propagateToListeners (dart:async/future_impl.dart:709:32)
#13     Future._completeWithValue (dart:async/future_impl.dart:524:5)
#14     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:32:15)
#15     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:290:13)
#16     ApplicationPackageFactory.getPackageForPlatform (package:flutter_tools/src/application_package.dart)
#17     _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:73:64)
#18     _rootRunUnary (dart:async/zone.dart:1134:38)
#19     _CustomZone.runUnary (dart:async/zone.dart:1031:19)
#20     _FutureListener.handleValue (dart:async/future_impl.dart:139:18)
#21     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:680:45)
#22     Future._propagateToListeners (dart:async/future_impl.dart:709:32)
#23     Future._completeWithValue (dart:async/future_impl.dart:524:5)
#24     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:32:15)
#25     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:290:13)
#26     AndroidApk.fromAndroidProject (package:flutter_tools/src/application_package.dart)
#27     _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:73:64)
#28     _rootRunUnary (dart:async/zone.dart:1134:38)
#29     _CustomZone.runUnary (dart:async/zone.dart:1031:19)
#30     _FutureListener.handleValue (dart:async/future_impl.dart:139:18)
#31     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:680:45)
#32     Future._propagateToListeners (dart:async/future_impl.dart:709:32)
#33     Future._completeWithValue (dart:async/future_impl.dart:524:5)
#34     Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:554:7)
#35     _rootRun (dart:async/zone.dart:1126:13)
#36     _CustomZone.run (dart:async/zone.dart:1023:19)
#37     _CustomZone.runGuarded (dart:async/zone.dart:925:7)
#38     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:965:23)
#39     _microtaskLoop (dart:async/schedule_microtask.dart:43:21)
#40     _startMicrotaskLoop (dart:async/schedule_microtask.dart:52:5)
#41     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
#42     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:175:5)
```

```
Analyzing flutter_bug...
No issues found! (ran in 3.6s)
```

```
[√] Flutter (Channel stable, v1.12.13+hotfix.8, on Microsoft Windows [Version 10.0.18363.720], locale en-GB)
    • Flutter version 1.12.13+hotfix.8 at C:\Users\yahya\flutter
    • Framework revision 0b8abb4724 (5 weeks ago), 2020-02-11 11:44:36 -0800
    • Engine revision e1e6ced81d
    • Dart version 2.7.0

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at C:\Users\yahya\AppData\Local\Android\Sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • ANDROID_SDK_ROOT = C:\Users\yahya\AppData\Local\Android\Sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)
    • All Android licenses accepted.

[√] Android Studio (version 3.6)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 44.0.2
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)

[√] VS Code (version 1.36.1)
    • VS Code at C:\Users\yahya\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.2.0

[√] Connected device (1 available)
    • COR L29 • XTX7N18A15000054 • android-arm64 • Android 9 (API 28)

• No issues found!
```

</details>

**Comment by jonahwilliams** [comment]
I don't know of a good way to figure out what gradle is going to name the output file. We've currently tried (as you linked above) to guess based on the user inputs. In general that isn't good enough.

We could implement some functionality like 1) try to find the APK 2) fall back to the closest matching APK. That has the risk of choosing bad outputs though.

**Comment by anik786** [comment]
Perhaps we can send the flavour differently like, by separating each dimension using a comma:

$ flutter run --flavor="app1,local"

This will tell the flutter to look for the flavour "app1Local" and that the APK file name will be "app-app1-local-debug.apk.

To the best of my knowledge iOS does not have a concept of multiple flavour dimensions, so for iOS it could just look for "app1Local".

**Comment by jonahwilliams** [comment]
That seems like a reasonable idea. I suppose we could also allow flavor to be a multi option, so:

```
flutter run --flavor='app1Local'
```

Looks for app-app1Local.apk, while

```
flutter run --flavor=app1 --flavor=local
```

Looks for app-app1-local.apk.

WDUT?

**Comment by jonahwilliams** [comment]
Breadcrumbs for myself, maybe we can figure this out in the gradle plugin:

```
        project.android.applicationVariants.all { variant ->
            def foo = variant.getProductFlavors().collect { flavor ->
                flavor.getName()
            }.join('-')
            println(project.archivesBaseName + '-' + foo + '.apk')
        }
```

prints

```
app-app2-staging.apk
app-app2-staging.apk
app-app2-staging.apk
app-app2-local.apk
app-app2-local.apk
app-app2-local.apk
app-app1-staging.apk
app-app1-staging.apk
app-app1-staging.apk
app-app1-local.apk
app-app1-local.apk
app-app1-local.apk
```

**Comment by v7lin** [comment]
This is my solution.

```groovy
android {
    applicationVariants.all { variant ->
        // flutter 不支持多 dimension
        // https://github.com/flutter/flutter/issues/52905
        variant.assemble.doLast {
            def apkFile = variant.outputs.first().outputFile as File
            System.out.println("apk file: ${apkFile.path}")
            def flavorNames = variant.productFlavors.collect{flavor -> flavor.name}.toList()
            System.out.println("flavorNames: ${flavorNames.join('-')}")
            def targetApkFile = new File(apkFile.parentFile.path, "app-${flavorNames.withIndex().collect{flavorName, index -> index == 0 ? flavorName : flavorName.capitalize()}.join('')}-${variant.buildType.name}.apk")
            System.out.println("target apk file: ${targetApkFile.path}")
            exec {
                commandLine 'bash', '-lc', "cp ${apkFile.path} ${targetApkFile.path}"
            }
        }
    }
}
```

**Comment by ikrsh** [comment]
> 
> 
> This is my solution.
> 
> ```groovy
> android {
>     applicationVariants.all { variant ->
>         // flutter 多 dimension 支持有 bug
>         // https://github.com/flutter/flutter/issues/52905
>         variant.assemble.doLast {
>             def apkFile = variant.outputs.first().outputFile as File
>             System.out.println("apk file: ${apkFile.path}")
>             def flavorNames = variant.productFlavors.collect{flavor -> flavor.name}.toList()
>             System.out.println("flavorNames: ${flavorNames.join('-')}")
>             def targetApkFile = new File(apkFile.parentFile.path, "app-${flavorNames.withIndex().collect{flavorName, index -> index == 0 ? flavorName : flavorName.capitalize()}.join('')}-${variant.buildType.name}.apk")
>             System.out.println("target apk file: ${targetApkFile.path}")
>             exec {
>                 commandLine 'bash', '-lc', "cp ${apkFile.path} ${targetApkFile.path}"
>             }
>         }
>     }
> }
> ```

For Windows users, you can copy the apk file using below:
```
exec {
    if (System.getProperty('os.name').toLowerCase(Locale.ROOT).contains('windows')) {
      commandLine 'cmd', '/c', "copy ${apkFile.path} ${targetApkFile.path}"
    } else {
      commandLine 'bash', '-lc', "cp ${apkFile.path} ${targetApkFile.path}"
    }
}
```
