### ISSUE TITLE
[tool_crash] WipError 9: {code: -32000, message: Cannot find context with specified id}

### ISSUE THREAD

**Issue by ugritboon** [flutter/flutter#52922]
## Command
```
flutter run -d chrome
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
WipError: WipError 9: {code: -32000, message: Cannot find context with specified id}
```
#0      Modules._initializeMapping (package:dwds/src/debugging/modules.dart:181:9)
<asynchronous suspension>
#1      Modules.initialize (package:dwds/src/debugging/modules.dart:53:5)
#2      ChromeProxyService.createIsolate (package:dwds/src/services/chrome_proxy_service.dart:162:14)
#3      DevHandler._handleIsolateStart (package:dwds/src/handlers/dev_handler.dart:347:11)
#4      DevHandler._handleConnection.<anonymous closure> (package:dwds/src/handlers/dev_handler.dart:225:19)
#5      _rootRunUnary (dart:async/zone.dart:1141:38)
#6      _CustomZone.runUnary (dart:async/zone.dart:1034:19)
#7      _CustomZone.runUnaryGuarded (dart:async/zone.dart:936:7)
#8      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11)
#9      _DelayedData.perform (dart:async/stream_impl.dart:594:14)
#10     _StreamImplEvents.handleNext (dart:async/stream_impl.dart:710:11)
#11     _PendingEvents.schedule.<anonymous closure> (dart:async/stream_impl.dart:670:7)
#12     _rootRun (dart:async/zone.dart:1129:38)
#13     _CustomZone.run (dart:async/zone.dart:1026:19)
#14     _CustomZone.runGuarded (dart:async/zone.dart:928:7)
#15     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:968:23)
#16     _rootRun (dart:async/zone.dart:1133:13)
#17     _CustomZone.run (dart:async/zone.dart:1026:19)
#18     _CustomZone.runGuarded (dart:async/zone.dart:928:7)
```
```
[✓] Flutter (Channel master, v1.16.1-pre.34, on Microsoft Windows [Version 10.0.18363.720], locale en-US)
    • Flutter version 1.16.1-pre.34 at C:\Users\rbus\Documents\flutter
    • Framework revision e6b0f5f238 (24 hours ago), 2020-03-18 21:56:02 -0400
    • Engine revision 216c420a2c
    • Dart version 2.8.0 (build 2.8.0-dev.15.0 96cf889e6b)

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at C:\Users\rbus\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[✓] Android Studio (version 3.6)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 44.0.2
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)

[✓] VS Code (version 1.43.1)
    • VS Code at C:\Users\rbus\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.8.1

[✓] Connected device (2 available)
    • Chrome     • chrome     • web-javascript • Google Chrome 80.0.3987.149
    • Web Server • web-server • web-javascript • Flutter Tools

• No issues found!

```

## Flutter Application Metadata
**Version**: 1.0.0+1
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null

**Comment by jonahwilliams** [comment]
FYI @grouma this on dwds: 2.0.1

**Comment by grouma** [comment]
I believe this is resolved with: https://github.com/dart-lang/webdev/pull/929

**Comment by grouma** [comment]
Do we have better reproduction steps? I'll verify that it is resolved.

**Comment by jonahwilliams** [comment]
Thanks. @ugritboon are you able to repro this consistently?

At any rate, we should see it in the crash logging, so if it goes down after I update dwds we know its fixed
