### ISSUE TITLE
[web] run integration tests on Cirrus and LUCI using felt.

### ISSUE THREAD

**Issue by nturgut** [flutter/flutter#52983]
Change cirrus files and LUCI to make sure all is in place for integration tests.

- [x] provide a flag for not fetching flutter for developer who might want to use local repo.
- [x] if we are running on CI. fetch Flutter, we will use flutter pub get from the fetched framework.
- [x] enable cirrus tests
- [x] remove flag which guards the integration test for CIs from test_runner.dart
- [ ] enable LUCI tests. Look like 'google-chrome' is not available on LUCI bots. from the logs:
```
Cloning into 'web_installers'...
Unhandled exception:
ProcessException: No such file or directory
  Command: google-chrome --version
#0      ChromeDriverInstaller._querySystemChromeVersion (package:web_driver_installer/chrome_driver_installer.dart:96:9)
<asynchronous suspension>
#1      ChromeDriverInstaller._installDriver (package:web_driver_installer/chrome_driver_installer.dart:61:37)
#2      ChromeDriverInstaller.install (package:web_driver_installer/chrome_driver_installer.dart:52:20)
#3      IntegrationTestsManager.prepareDriver (file:///b/s/w/ir/cache/builder/src/flutter/lib/web_ui/dev/integration_tests_manager.dart:136:55)
<asynchronous suspension>
#4      IntegrationTestsManager.runTests (file:///b/s/w/ir/cache/builder/src/flutter/lib/web_ui/dev/integration_tests_manager.dart:35:32)
#5      TestCommand.runIntegrationTests (file:///b/s/w/ir/cache/builder/src/flutter/lib/web_ui/dev/test_runner.dart:130:45)
#6      TestCommand.run (file:///b/s/w/ir/cache/builder/src/flutter/lib/web_ui/dev/test_runner.dart:118:44)
#7      CommandRunner.runCommand (package:args/command_runner.dart:197:27)
#8      CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:112:25)
#9      new Future.sync (dart:async/future.dart:224:31)
#10     CommandRunner.run (package:args/command_runner.dart:112:14)
#11     main (file:///b/s/w/ir/cache/builder/src/flutter/lib/web_ui/dev/felt.dart:35:38)
#12     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:299:32)
#13     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:168:12)
```

**Comment by yjbanov** [comment]
Good plan! For the missing chrome issue we should use the same chrome we use for unit-tests.
