### ISSUE TITLE
Support for HLS on desktop browsers for video_player_web

### ISSUE THREAD

**Issue by nstrelow** [flutter/flutter#53011]
## Use case
I have a HLS stream and I want to built an app which works on both mobile and web.

Currently there is no support for HLS on desktop browsers. (Except legacy Edge 🙈)

## Proposal
Is there a possibility to include HLS support as part of the package?

In Javascript https://github.com/video-dev/hls.js/ is used a lot to add the compatibility.

**Comment by ditman** [comment]
> HLS is being replaced by Dynamic Adaptive Streaming over HTTP (aka MPEG-DASH)

Should we add a technology that is being phased out to a new framework?

**Comment by ditman** [comment]
(Maybe this is more appropriate for a `hls_video_player` plugin?)

**Comment by ditman** [comment]
(Also requested here: https://github.com/flutter/flutter/issues/46778)

**Comment by nstrelow** [comment]
Ah I wasn't aware that HLS was phased out. A lot of livestreams seem to use it though. It's very interesting that all those webplayers rely on hls.js or their own implementation, since desktop chrome/firefox have no support.

A plugin onto of `video_player` is probably also good option.
Let me know if I can help in any way. If including it into `video_player` is not an option, I could look into creating a plugin. Already played around with hls.js JS Interop in `video_player_web`, just a bare workaround.

**Comment by ditman** [comment]
@nstrelow I'm not sure hls.js should be "mandatory" in the web plugin for two reasons:

* To minimize the amount of JS users of apps using the plugin will have to download/parse (maybe for nothing?)
* To minimize the amount of Dart code that is part of the plugin to support that codec :)

We probably should either:

1. Add an extension point to the current _web plugin so it can accept different players, and then provide a player that is backed by HLS.js, or
2. Since the video_player plugin is now federated, a new package: `hls_video_player_web` or similar, could be created. And it'd be a version of the video player that plays HLS. Note that `hls_video_player_web` doesn't need to be inside flutter/plugins to be usable by others, and we can link from the official `video_player_web` README or similar to that implementation "if you need HLS".

**Your workarounds in `video_player_web` are probably a very good start for option 2**, without having to wait for option 1. Those workarounds, in fact, would be very useful to inform the requirements for what would be needed to be done for option 1 as well, if we decide to do that.

_(Another outcome may be that we end up saying: now @nstrelow owns the official version of `video_player` for the web platform :P)_

**Comment by nstrelow** [comment]
@ditman I agree,  HLS is probably not a big use case and should not clutter the official package.
Not 100% sure how 1. works. Similarly to how video_player uses video_player_web depending on platform?

Do you have some pointers on how to best work with JS Interop? I had problems, specifically:
1. Correctly defining the hls.on function for JS Interop (IIRC throws expected 1 arg, even though it needs 3)
2. Including/Loading the hls.js without using a CDN in index.html

Thanks a lot for the quick responses 😁

**Comment by ditman** [comment]
@nstrelow I was only speculating when I mentioned option "1", but what I was thinking of, was some change in the API of video_player_web to let you inject a player (web only), so imagine something like:

```
if (kIsWeb) {
  VideoPlayerPlatform.instance.setVideoPlayer(MyHlsVideoPlayerComponent());
}
```

Of course, there's probably a ton of stuff to do to get that done, I haven't really looked at the code to see how easy/complex would that change be :)

> Correctly defining the hls.on function for JS Interop

For JS Interop, you may want to take a look at Dart's [`js_facade_gen`](https://github.com/dart-lang/js_facade_gen) script. It tries to grab a .d.ts file (like [this one](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/hls.js/index.d.ts)) and attempts to convert it into a valid Dart JS Facade (I used it for the `google_sign_in` plugin and it was great; then tried to use it for maps and... not so great :P).

I haven't seen your JS Interop "on" function, but it looks like it's some sort of `void on function(String event, Function handler);`? The `handler` is probably too broad, so you'd need to `typedef` something more specific (check the .d.ts above or the API docs to find out what!)

> Including/Loading the hls.js without using a CDN in index.html

For 2, it might be doable to place the hls.js file as an asset of the flutter app, and include it from `assets/the_right_path/hls.js`, but I haven't tried that yet. In any case, you can do whatever postprocessing you want on your `build/web` before publishing to ensure you place the hls.js wherever you need it. For now, I wouldn't bother too much with that. If you get this working with hls.js working from a CDN it'd be a huge win already.

**Comment by ditman** [comment]
Hey @nstrelow did you manage to do any progress on this? Do you need help?

**Comment by nstrelow** [comment]
Hey thanks for checking back. I put some more hours in, but wasn't able to produce something working with the JS interop.
The  js_facade_gen is pretty nice, but not 100% perfect. Ended up copying the definition of the functions needed for Hls support.

I'll update this with a repo with my (probably not helpful) code.

**Comment by nstrelow** [comment]
Here are my code snippets.
"Hls supported" is printed twice in my browser console. Nothing is further logged, so either `attachMedia` or `on` is not working correctly.

Functions needed for the setup at: https://github.com/video-dev/hls.js/blob/master/docs/API.md#getting-started

### hls.dart
```
@JS()
library hls.js;

import 'dart:html';

import 'package:js/js.dart';

@JS("Hls.isSupported")
external bool isSupported();

@JS("Hls")
class Hls {
  external factory Hls();
  external void attachMedia(VideoElement videoElement);
  external void on(String event, Function callback);
  external void loadSource(String source);
}

@JS('console.log')
external void log(dynamic str);
```

### video_player_web.dart
```
// existing code start
void initialize() {
    videoElement = VideoElement()
      ..src = uri.toString()
      ..autoplay = false
      ..controls = false
      ..style.border = 'none';
// existing code end

final testStream =
        'http://qthttp.apple.com.edgesuite.net/1010qwoeiuryfg/sl.m3u8';
    if (isSupported()) {
      print('Hls supported');
      log('Hls supported');
    final hls = Hls();
    hls.attachMedia(videoElement);
    hls.on('hlsError', allowInterop(() {
      print('hlsError');
      log('hlsError');
    }));
    hls.on('hlsMediaAttaching', allowInterop(() {
      print('hlsMediaAttaching');
      log('hlsMediaAttaching');
      hls.loadSource(testStream);
      hls.on('hlsManifestParsed', () {
        print('hlsManifestParsed');
        log('hlsManifestParsed');
      });
    }));
    }
```

**Comment by ditman** [comment]
Doesn't

```
      hls.on('hlsManifestParsed', () {
        print('hlsManifestParsed');
        log('hlsManifestParsed');
      });
```

Also need an allowInterop to the callback? In general, all the callbacks that you pass to the javascript world, need allowInterop.

**Comment by nstrelow** [comment]
Oh yeah, I missed that one. But sadly it still produces the same result.

(I'll edit the code above)

**Comment by NetWilliam** [comment]
> Oh yeah, I missed that one. But sadly it still produces the same result.
> 
> (I'll edit the code above)

Can I have a minimal example of your running code plz? I am also working on this piece of work.

**Comment by NetWilliam** [comment]
(virtscreen)  ~/Documents/flutter/helloworld/myapp      flutter build web                                                                                                                                     
Target dart2js failed: Exception: lib/main.dart:571:10:                 
Error: Method not found: 'videoElement'.
var ve = videoElement();
         ^^^^^^^^^^^^
lib/main.dart:580:24:
Error: Method not found: 'allowInterop'.
    hls.on('hlsError', allowInterop(() {
                       ^^^^^^^^^^^^
lib/main.dart:588:35:
Error: Method not found: 'allowInterop'.
      hls.on('hlsManifestParsed', allowInterop(() {
                                  ^^^^^^^^^^^^
lib/main.dart:584:33:
Error: Method not found: 'allowInterop'.
    hls.on('hlsMediaAttaching', allowInterop(() {
                                ^^^^^^^^^^^^
Error: Compilation failed.


Compiling lib/main.dart for the Web...                              6.0s
Exception: Failed to compile application for the Web.


I get this compiling error. I wonder what's going here...

**Comment by balvinderz** [comment]
@NetWilliam  there's a typo in videoElement() . it should be VideoElement() and you should add dependancy js in pubspec.yaml and import it.

**Comment by balvinderz** [comment]
After a lot of trial and error .this works. 
hls.on('hlsMediaAttaching', allowInterop((_,__) {
      print('hlsMediaAttaching');

    }));
    hls.on('hlsManifestParsed', () {
      print('hlsManifestParsed');
    });

**Comment by balvinderz** [comment]
i was making the hls_video_player_web plugin . Can you guys tell me how to override the video_player plugin to use the hls_video_player_web plugin instead of the video_player_web.

**Comment by NetWilliam** [comment]
I correct the code, install the packages and I can compile the code now. But I meet an error upon running. It says that:

`TypeError: Cannot read property 'isSupported' of undefined
See also: https://flutter.dev/docs/testing/errors`

any suggestions?

**Comment by NetWilliam** [comment]
my content of lib/main.dart:


```
import 'package:flutter/material.dart';
import 'dart:html';
import 'package:js/js.dart';
import 'hls.dart';
void main() {
var ve = VideoElement();
final testStream =
        "http://qthttp.apple.com.edgesuite.net/1010qwoeiuryfg/sl.m3u8";
    if (isSupported()) {
      print('Hls supported');
      log('Hls supported');
    final hls = Hls();
    hls.attachMedia(ve);
    hls.on('hlsError', allowInterop(() {
      print('hlsError');
      log('hlsError');
    }));
    hls.on('hlsMediaAttaching', allowInterop((_,__) {
      print('hlsMediaAttaching');
      log('hlsMediaAttaching');
      hls.loadSource(testStream);
      hls.on('hlsManifestParsed', allowInterop(() {
        print('hlsManifestParsed');
        log('hlsManifestParsed');
      }));
    }));
    }
}
```

lib/hls.dart:

```
@JS()
library hls.js;

import 'dart:html';

import 'package:js/js.dart';

@JS("Hls.isSupported")
external bool isSupported();

@JS("Hls")
class Hls {
  external factory Hls();
  external void attachMedia(VideoElement videoElement);
  external void on(String event, Function callback);
  external void loadSource(String source);
}

@JS('console.log')
external void log(dynamic str);
```

pubspec.yaml:
```
name: myapp
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.3
  video_player: ^0.10.8+1
  video_player_web: ^0.1.2+1
  cdnbye: ^0.6.0
  hls_player: ^0.0.5
  js: ^0.6.0
  html: ^0.14.0+3
  #video_player: ^0.10.8+1

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true

......
```

**Comment by NetWilliam** [comment]
the error stack is 
```
For a more detailed help message, press "h". To quit, press "q".
TypeError: Cannot read property 'isSupported' of undefined
    at Object.main$ [as main] (http://localhost:35579/packages/myapp/main.dart.lib.js:16:35)
    at main$ (http://localhost:35579/web_entrypoint.dart.lib.js:17:12)
    at main$.next (<anonymous>)
    at onValue (http://localhost:35579/dart_sdk.js:43111:33)
    at _RootZone.runUnary (http://localhost:35579/dart_sdk.js:42996:58)
    at _FutureListener.thenAwait.handleValue (http://localhost:35579/dart_sdk.js:38417:29)
    at handleValueCallback (http://localhost:35579/dart_sdk.js:38923:49)
    at Function._propagateToListeners (http://localhost:35579/dart_sdk.js:38955:17)
    at async._AsyncCallbackEntry.new.callback (http://localhost:35579/dart_sdk.js:38711:27)
    at Object._microtaskLoop (http://localhost:35579/dart_sdk.js:43212:13)
    at _startMicrotaskLoop (http://localhost:35579/dart_sdk.js:43218:13)
    at http://localhost:35579/dart_sdk.js:39160:9

```

**Comment by ditman** [comment]
> i was making the hls_video_player_web plugin . Can you guys tell me how to override the video_player plugin to use the hls_video_player_web plugin instead of the video_player_web plugin.

@balvinderz you should be able to do this by depending both on `video_player` and your own `hls_video_player_web` plugin. If your plugin defines a `web` platform in its pubspec (look at `video_player_web`), it should be picked up, instead of the default `video_player_web`.

The nuclear option is to clone `video_player` and modify it to depend on your package via a `path` dependency, instead of something via pub.dev, but the above should work.

**Comment by balvinderz** [comment]
i published a package for hls on chrome .
https://pub.dev/packages/video_player_web_hls
Can you check it ?.

**Comment by NetWilliam** [comment]
I meet an error by running the example like
'''
For a more detailed help message, press "h". To quit, press "q".
TypeError: dart.global.Hls is not a constructor
    at video_player_web_hls._VideoPlayer.new.initialize
    (http://localhost:42549/packages/video_player_web_hls/video_player_web_hls.dart.lib.js:242:19)
    at video_player_web_hls.VideoPlayerPluginHls.new.create
    (http://localhost:42549/packages/video_player_web_hls/video_player_web_hls.dart.lib.js:175:16)
    at create.next (<anonymous>)
    at runBody (http://localhost:42549/dart_sdk.js:43130:34)
    at Object._async [as async] (http://localhost:42549/dart_sdk.js:43158:7)
    at video_player_web_hls.VideoPlayerPluginHls.new.create
    (http://localhost:42549/packages/video_player_web_hls/video_player_web_hls.dart.lib.js:149:20)
    at video_player.VideoPlayerController.network.initialize
    (http://localhost:42549/packages/video_player/video_player.dart.lib.js:943:69)
    at initialize.next (<anonymous>)
    at runBody (http://localhost:42549/dart_sdk.js:43130:34)
    at Object._async [as async] (http://localhost:42549/dart_sdk.js:43158:7)
    at video_player.VideoPlayerController.network.initialize
    (http://localhost:42549/packages/video_player/video_player.dart.lib.js:921:20)
    at main._VideoAppState.new.initState
    (http://localhost:42549/packages/myapp/main.dart.lib.js:303:137)
    at framework.StatefulElement.new.[_firstBuild]
    (http://localhost:42549/packages/flutter/src/widgets/widget_span.dart.lib.js:41441:58)
    at framework.StatefulElement.new.mount
    (http://localhost:42549/packages/flutter/src/widgets/widget_span.dart.lib.js:12649:24)
    at RenderObjectToWidgetElement.new.inflateWidget
    (http://localhost:42549/packages/flutter/src/widgets/widget_span.dart.lib.js:11464:16)
    at RenderObjectToWidgetElement.new.updateChild
    (http://localhost:42549/packages/flutter/src/widgets/widget_span.dart.lib.js:11327:25)
    at RenderObjectToWidgetElement.new.[_rebuild]
    (http://localhost:42549/packages/flutter/src/widgets/widget_span.dart.lib.js:39745:33)
    at RenderObjectToWidgetElement.new.mount
    (http://localhost:42549/packages/flutter/src/widgets/widget_span.dart.lib.js:39726:23)
    at http://localhost:42549/packages/flutter/src/widgets/widget_span.dart.lib.js:39634:21
    at framework.BuildOwner.new.buildScope
    (http://localhost:42549/packages/flutter/src/widgets/widget_span.dart.lib.js:41076:13)
    at RenderObjectToWidgetAdapter.new.attachToRenderTree
    (http://localhost:42549/packages/flutter/src/widgets/widget_span.dart.lib.js:39633:17)
    at binding$5.WidgetsFlutterBinding.new.attachRootWidget
    (http://localhost:42549/packages/flutter/src/widgets/widget_span.dart.lib.js:39506:227)
    at http://localhost:42549/packages/flutter/src/widgets/widget_span.dart.lib.js:39501:14
    at internalCallback (http://localhost:42549/dart_sdk.js:30320:11)

'''

**Comment by balvinderz** [comment]
Did u insert the script tag in index.html

**Comment by NetWilliam** [comment]
you are right. 
I get the code running by mod web/index.html under my project directory into such a content:

'''
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title></title>
   <script src="https://cdn.jsdelivr.net/npm/hls.js@latest"  type="application/javascript"></script>
  <script defer src="main.dart.js" type="application/javascript"></script>
</head>
<body>
</body>
</html>
'''

**Comment by NetWilliam** [comment]
I wonder if it's possible that I use the same code base to compile for both iOS, Android and web platform to play HLS video by native flutter component and thrid-party package like video_player_web_hls?

**Comment by camsjams** [comment]
@balvinderz This package works great - thank you!

Also I am not sure about the early statement regarding HLS being replaced by MPEG-DASH, although MPEG-DASH is definitely on the rise, HLS is still alive and kicking. @ditman could you provide a link to this for me to understand the context better?

**Comment by ditman** [comment]
My this is old, when I read the docs months ago, it seemed that DASH was going to be the standard replacement for HLS, but not so much anymore.

Since then, there has been some development in this area; for example, the Shaka people reached out and asked if we could integrate the player (issue [linked above](https://github.com/flutter/flutter/issues/66931)), and I don't see why there couldn't be a "video_player_web_shaka" that handles normal streams, DASH and HLS for free.

Also, if the extra JS is acceptable for users, I can't see why we wouldn't make that plugin the default web-endorsed version of the plugin.

I just haven't had time to work on this part of video_player in a while. I've had to focus on adding other plugins for the web!

**Comment by nstrelow** [comment]
Pretty awesome to see so much work and ideas on this.
I would rather like to see browser support, but somehow this is not mainstream enough to be included (I guess).

Shaka looks pretty powerful and would be amazing to have integrated for HLS and DASH.

So thanks and sorry for my lack of involvement 🙈

**Comment by egodefroy** [comment]
> i published a package for hls on flutter web .
> https://pub.dev/packages/video_player_web_hls
> Can you check it ?.
@balvinderz I tried it and it works fine.
However, when leaving the view and after the videocontroller dispose, the streamed files are still being read from the network. Is there a way to stop this activity ?

**Comment by balvinderz** [comment]
> > i published a package for hls on flutter web .
> 
> > https://pub.dev/packages/video_player_web_hls
> 
> > Can you check it ?.
> 
> @balvinderz I tried it and it works fine.
> 
> However, when leaving the view and after the videocontroller dispose, the streamed files are still being read from the network. Is there a way to stop this activity ?
> 
> 
> 
> 

I will look into this.

**Comment by balvinderz** [comment]
> > i published a package for hls on flutter web .
> > https://pub.dev/packages/video_player_web_hls
> > Can you check it ?.
> > @balvinderz I tried it and it works fine.
> > However, when leaving the view and after the videocontroller dispose, the streamed files are still being read from the network. Is there a way to stop this activity ?

Fixed this issue in video_player_web_hls 0.1.11.
Please try and check if this version fixes the issue for you.

**Comment by erickcchoi** [comment]
> > > i published a package for hls on flutter web .
> > > https://pub.dev/packages/video_player_web_hls
> > > Can you check it ?.
> > > @balvinderz I tried it and it works fine.
> > > However, when leaving the view and after the videocontroller dispose, the streamed files are still being read from the network. Is there a way to stop this activity ?
> 
> Fixed this issue in video_player_web_hls 0.1.11.
> Please try and check if this version fixes the issue for you.

Hi balvinderz

Please advice, Is your package possible to use it as audio player in web?

**Comment by balvinderz** [comment]
@erickcchoi 
idk . the package is not intended to be used as a audio player

**Comment by erickcchoi** [comment]
> @erickcchoi
> idk . the package is not intended to be used as a audio player

Thank you very much for your quick reply.

**Comment by egodefroy** [comment]
> > > i published a package for hls on flutter web .
> > > https://pub.dev/packages/video_player_web_hls
> > > Can you check it ?.
> > > @balvinderz I tried it and it works fine.
> > > However, when leaving the view and after the videocontroller dispose, the streamed files are still being read from the network. Is there a way to stop this activity ?
> 
> Fixed this issue in video_player_web_hls 0.1.11.
> Please try and check if this version fixes the issue for you.
Many thanks @balvinderz !
It works fine for me. The activity stops on videocontroller's dispose.

**Comment by XuanTung95** [comment]
> @balvinderz you should be able to do this by depending both on video_player and your own hls_video_player_web plugin. If your plugin defines a web platform in its pubspec (look at video_player_web), it should be picked up, instead of the default video_player_web.

@ditman
1. Could you explain how this way can replace the default video_player_web?
2. If I have 2 plugins hls_video_player_web and abc_video_player_web which support another protocol, can they work together or I need to write a new plugin that support both?

**Comment by hasanm08** [comment]
Any update on this?
Can you please merge [video_player_web_hls](https://github.com/balvinderz/video_player_web_hls) to ``` video_player ``` package

**Comment by ditman** [comment]
> Can you please merge [video_player_web_hls](https://github.com/balvinderz/video_player_web_hls) to video_player package

Why not use `video_player_web_hls` @hasanm08 ?

**Comment by hasanm08** [comment]
> > Can you please merge [video_player_web_hls](https://github.com/balvinderz/video_player_web_hls) to video_player package
> 
> Why not use `video_player_web_hls` @hasanm08 ?

Because it downloads a big script on startup, and it reduces the SEO and the lunch FPS

**Comment by ditman** [comment]
> Because it downloads a big script on startup, so it reduces the SEO score and the lunch FPS @ditman

@hasanm08 you need a script for HLS video to work on the web, AFAIK. Something like hls.js or Shaka player.

**Comment by JenishMS** [comment]
I tried to play m3u8 format video on Android, IOS, and Web. Android and iOS are working fine.  But on the Web, it is not working. I tried the [video_player_web_hls](https://pub.dev/packages/video_player_web_hls) package to play m3u8 video in web. For me, it is working fine web also.

**Comment by hasanm08** [comment]
> I tried to play m3u8 format video on Android, IOS, and Web. Android and iOS are working fine.  But on the Web, it is not working. I tried the [video_player_web_hls](https://pub.dev/packages/video_player_web_hls) package to play m3u8 video in web. For me, it is working fine web also.

It is not working on safari :)

**Comment by ditman** [comment]
@JenishMS @hasanm08 that package belongs to another repo, maybe you should open an issue there :)

**Comment by ryanovas** [comment]
Still an issue in 2025...

**Comment by nateshmbhat** [comment]
I'm willing to take this up and implement this : Have added a proposal comment here : https://github.com/flutter/flutter/issues/66931#issuecomment-5461267195
