### ISSUE TITLE
 !_dirty exception in widgets/framework.dart

### ISSUE THREAD

**Issue by mehmetf** [flutter/flutter#53024]
Internal bug: b/151816668

```
01-01 01:25:24.911  9424  9424 I launcher: flutter: ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
01-01 01:25:24.911  9424  9424 I launcher: flutter: The following assertion was thrown while rebuilding dirty elements:
01-01 01:25:24.911  9424  9424 I launcher: flutter: 'package:flutter/src/widgets/framework.dart': Failed assertion: line 4224 pos 12: '!_dirty': is not
01-01 01:25:24.911  9424  9424 I launcher: flutter: true.
01-01 01:25:24.911  9424  9424 I launcher: flutter: 
01-01 01:25:24.911  9424  9424 I launcher: flutter: Either the assertion indicates an error in the framework itself, or we should provide substantially
01-01 01:25:24.911  9424  9424 I launcher: flutter: more information in this error message to help you determine and fix the underlying cause.
01-01 01:25:24.911  9424  9424 I launcher: flutter: In either case, please report this assertion by filing a bug on GitHub:
01-01 01:25:24.911  9424  9424 I launcher: flutter:   https://github.com/flutter/flutter/issues/new?template=BUG.md
01-01 01:25:24.911  9424  9424 I launcher: flutter: 
01-01 01:25:24.911  9424  9424 I launcher: flutter: The relevant error-causing widget was:
01-01 01:25:24.911  9424  9424 I launcher: flutter:   AnimatedBuilder <redacted>:44:22
01-01 01:25:24.911  9424  9424 I launcher: flutter: 
01-01 01:25:24.911  9424  9424 I launcher: flutter: When the exception was thrown, this was the stack:
01-01 01:25:24.911  9424  9424 I launcher: flutter: #2      Element.rebuild (package:flutter/src/widgets/framework.dart:4224:12)
01-01 01:25:24.911  9424  9424 I launcher: flutter: #3      BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2627:33)
01-01 01:25:24.911  9424  9424 I launcher: flutter: #4      WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:883:20)
01-01 01:25:24.911  9424  9424 I launcher: flutter: #5      RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:283:5)
01-01 01:25:24.911  9424  9424 I launcher: flutter: #6      SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1108:15)
01-01 01:25:24.911  9424  9424 I launcher: flutter: #7      SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1047:9)
01-01 01:25:24.911  9424  9424 I launcher: flutter: #8      SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:963:5)
01-01 01:25:24.911  9424  9424 I launcher: flutter: #12     _invoke (dart:ui/hooks.dart:261:10)
01-01 01:25:24.911  9424  9424 I launcher: flutter: #13     _drawFrame (dart:ui/hooks.dart:219:3)
01-01 01:25:24.911  9424  9424 I launcher: flutter: (elided 5 frames from class _AssertionError and dart:async)
01-01 01:25:24.911  9424  9424 I launcher: flutter: 
01-01 01:25:24.911  9424  9424 I launcher: flutter: The element being rebuilt at the time was index 0 of 1:
01-01 01:25:24.911  9424  9424 I launcher: flutter:   AnimatedBuilder
01-01 01:25:24.912  9424  9424 I launcher: flutter: ════════════════════════════════════════════════════════════════════════════════════════════════════
```

**Comment by mehmetf** [comment]
This does not seem terribly useful w/o a repro. Are the instructions printed in the error message still accurate?

**Comment by iapicca** [comment]
https://github.com/flutter/flutter/issues/27377

**Comment by PhilipPurwoko** [comment]
Please see another issue #35718 on daixianceng's comment

Also make sure you don't called `setState` during init state or right below build method
