### ISSUE TITLE
What went wrong: Execution failed for task ':app:compileDebugKotlin'.

### ISSUE THREAD

**Issue by januwA** [flutter/flutter#53070]
Hi, I get the following error when running the program

```sh
Launching lib\main.dart on Android SDK built for x86 in debug mode...

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:compileDebugKotlin'.
> Could not resolve all artifacts for configuration ':app:debugCompileClasspath'.
   > Could not download flutter_embedding_debug.jar (io.flutter:flutter_embedding_debug:1.0.0-fd60ddf7517ce2bfd6577636bda2065c0e492664)
      > Could not get resource 'https://storage.googleapis.com/download.flutter.io/io/flutter/flutter_embedding_debug/1.0.0-fd60ddf7517ce2bfd6577636bda2065c0e492664/flutter_embedding_debug-1.0.0-fd60ddf7517ce2bfd6577636bda2065c0e492664.jar'.
         > Could not GET 'https://storage.googleapis.com/download.flutter.io/io/flutter/flutter_embedding_debug/1.0.0-fd60ddf7517ce2bfd6577636bda2065c0e492664/flutter_embedding_debug-1.0.0-fd60ddf7517ce2bfd6577636bda2065c0e492664.jar'.
            > Connect to storage.googleapis.com:443 [storage.googleapis.com/34.64.4.16, storage.googleapis.com/2404:f340:10:1800:0:0:0:2010] failed: Connection timed out: connect
   > Could not download x86_debug.jar (io.flutter:x86_debug:1.0.0-fd60ddf7517ce2bfd6577636bda2065c0e492664)
      > Could not get resource 'https://storage.googleapis.com/download.flutter.io/io/flutter/x86_debug/1.0.0-fd60ddf7517ce2bfd6577636bda2065c0e492664/x86_debug-1.0.0-fd60ddf7517ce2bfd6577636bda2065c0e492664.jar'.
         > Could not GET 'https://storage.googleapis.com/download.flutter.io/io/flutter/x86_debug/1.0.0-fd60ddf7517ce2bfd6577636bda2065c0e492664/x86_debug-1.0.0-fd60ddf7517ce2bfd6577636bda2065c0e492664.jar'.
            > Connect to storage.googleapis.com:443 [storage.googleapis.com/34.64.4.16, storage.googleapis.com/2404:f340:10:1800:0:0:0:2010] failed: Connection timed out: connect
   > Could not download x86_64_debug.jar (io.flutter:x86_64_debug:1.0.0-fd60ddf7517ce2bfd6577636bda2065c0e492664)
      > Could not get resource 'https://storage.googleapis.com/download.flutter.io/io/flutter/x86_64_debug/1.0.0-fd60ddf7517ce2bfd6577636bda2065c0e492664/x86_64_debug-1.0.0-fd60ddf7517ce2bfd6577636bda2065c0e492664.jar'.
         > Could not GET 'https://storage.googleapis.com/download.flutter.io/io/flutter/x86_64_debug/1.0.0-fd60ddf7517ce2bfd6577636bda2065c0e492664/x86_64_debug-1.0.0-fd60ddf7517ce2bfd6577636bda2065c0e492664.jar'.
            > Connect to storage.googleapis.com:443 [storage.googleapis.com/34.64.4.16, storage.googleapis.com/2404:f340:10:1800:0:0:0:2010] failed: Connection timed out: connect

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
* Get more help at https://help.gradle.org

BUILD FAILED in 2m 30s
Exception: Gradle task assembleDebug failed with exit code 1
Exited (sigterm)
```

```sh
D:\ajanuw\flutter_demo>flutter doctor -v
[√] Flutter (Channel master, v1.16.2-pre.25, on Microsoft Windows [Version 10.0.18363.720],
    locale zh-CN)
    • Flutter version 1.16.2-pre.25 at D:\my-tools\flutter
    • Framework revision ec8448d0a3 (3 days ago), 2020-03-20 01:46:03 -0400
    • Engine revision fd60ddf751
    • Dart version 2.8.0 (build 2.8.0-dev.16.0 5b21a43c55)

[!] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at D:\my-tools\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = D:\my-tools\Android\sdk
    • Java binary at: D:\my-tools\Android\AndroidStudio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)
    X Android license status unknown.
      Try re-installing or updating your Android SDK Manager.
      See https://developer.android.com/studio/#downloads or visit
      https://flutter.dev/setup/#android-setup for detailed instructions.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 3.6)
    • Android Studio at D:\my-tools\Android\AndroidStudio
    • Flutter plugin version 44.0.2
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)

[√] Connected device (3 available)
    • Android SDK built for x86 • emulator-5554 • android-x86    • Android 10 (API 29)
      (emulator)
    • Chrome                    • chrome        • web-javascript • Google Chrome
      80.0.3987.149
    • Web Server                • web-server    • web-javascript • Flutter Tools

! Doctor found issues in 1 category.
```

I have set up mirroring
```sh
D:\ajanuw\flutter_demo>echo %FLUTTER_STORAGE_BASE_URL%
https://storage.flutter-io.cn

D:\ajanuw\flutter_demo>echo %PUB_HOSTED_URL%
https://pub.flutter-io.cn
```

**Comment by TahaTesser** [comment]
Hi @januwA 
Did you setup everything from this [Using Flutter in China
](https://flutter.dev/community/china)

Are you using proxy network or vpn?
please check your internet connection and provide your `flutter run  --verbose`
Thank you

**Comment by januwA** [comment]
hi, I ran `flutter run --verbose`, but after printing the following information, it has not responded.

```sh
C:\Users\ajanuw>flutter run --verbose
[  +18 ms] executing: [D:\my-tools\flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[ +254 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[   +4 ms] ec8448d0a312e19a3d89b8e9cf620667f7ad284b
[   +1 ms] executing: [D:\my-tools\flutter/] git describe --match v*.*.* --first-parent --long --tags
[ +681 ms] Exit code 0 from: git describe --match v*.*.* --first-parent --long --tags
[   +1 ms] v1.16.1-25-gec8448d0a
[  +10 ms] executing: [D:\my-tools\flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[ +114 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[   +1 ms] origin/master
[        ] executing: [D:\my-tools\flutter/] git ls-remote --get-url origin
[ +102 ms] Exit code 0 from: git ls-remote --get-url origin
[   +1 ms] https://github.com/flutter/flutter.git
```

**Comment by TahaTesser** [comment]
Hi @januwA 
Please run it from root of your Flutter project 
Thank you

**Comment by januwA** [comment]
hi, I ran `flutter run --verbose` but it got stuck and no more response

```sh
λ flutter run --verbose
[  +27 ms] executing: [D:\my-tools\flutter/] git -c log.showSignature=false log -n 1
--pretty=format:%H
[  +83 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[   +1 ms] ec8448d0a312e19a3d89b8e9cf620667f7ad284b
[   +1 ms] executing: [D:\my-tools\flutter/] git describe --match v*.*.* --first-parent
--long --tags
[  +68 ms] Exit code 0 from: git describe --match v*.*.* --first-parent --long --tags
[   +1 ms] v1.16.1-25-gec8448d0a
[  +10 ms] executing: [D:\my-tools\flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[  +46 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[   +1 ms] origin/master
[   +1 ms] executing: [D:\my-tools\flutter/] git ls-remote --get-url origin
[  +35 ms] Exit code 0 from: git ls-remote --get-url origin
[   +1 ms] https://github.com/flutter/flutter.git

```

**Comment by januwA** [comment]
This looks like terrible, what do I need to do ...

```sh
λ flutter run --verbose
[  +27 ms] executing: [D:\my-tools\flutter/] git -c log.showSignature=false log -n 1
--pretty=format:%H
[  +83 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[   +1 ms] ec8448d0a312e19a3d89b8e9cf620667f7ad284b
[   +1 ms] executing: [D:\my-tools\flutter/] git describe --match v*.*.* --first-parent
--long --tags
[  +68 ms] Exit code 0 from: git describe --match v*.*.* --first-parent --long --tags
[   +1 ms] v1.16.1-25-gec8448d0a
[  +10 ms] executing: [D:\my-tools\flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[  +46 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[   +1 ms] origin/master
[   +1 ms] executing: [D:\my-tools\flutter/] git ls-remote --get-url origin
[  +35 ms] Exit code 0 from: git ls-remote --get-url origin
[   +1 ms] https://github.com/flutter/flutter.git
[+301487 ms]   ╔════════════════════════════════════════════════════════════════════════════╗
                        ║ A new version of Flutter is available!                                     ║
                        ║                                                                            ║
                        ║ To update to the latest version, run "flutter upgrade".                    ║
                        ╚════════════════════════════════════════════════════════════════════════════╝

[+2181 ms] executing: [D:\my-tools\flutter/] git rev-parse --abbrev-ref HEAD
[  +45 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[   +1 ms] master
[ +107 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[   +2 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[  +16 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[   +2 ms] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +37 ms] executing: D:\my-tools\Android\sdk\platform-tools\adb.exe devices -l
[+2614 ms] List of devices attached


                    * daemon not running; starting now at tcp:5037
                    * daemon started successfully
[  +11 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[  +34 ms] Flutter assets will be downloaded from https://storage.flutter-io.cn. Make sure you trust this source!
[  +20 ms] Downloading Web SDK...
[  +46 ms] Downloading:
https://storage.flutter-io.cn/flutter_infra/flutter/fd60ddf7517ce2bfd6577636bda2065c0e492664/flutter-web-sdk-windows-x64.zip
[ +477 ms] Received response from server, collecting bytes...
[ +869 ms] Downloading Web SDK... (completed in 1.4s)
[+3381 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[ +168 ms] More than one device connected; please specify a device with the '-d <deviceId>' flag, or use '-d all' to
act on all
                    devices.
[  +81 ms] Chrome     • chrome     • web-javascript • Google Chrome 80.0.3987.149
[   +2 ms] Web Server • web-server • web-javascript • Flutter Tools
[   +6 ms] "flutter run" took 7,967ms.

#0      throwToolExit (package:flutter_tools/src/base/common.dart:14:3)
#1      RunCommand.validateCommand (package:flutter_tools/src/commands/run.dart:336:7)
<asynchronous suspension>
#2      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:695:11)
<asynchronous suspension>
#3      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:612:33)
<asynchronous suspension>
#4      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart)
#5      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:29)
#6      _rootRun (dart:async/zone.dart:1133:13)
#7      _CustomZone.run (dart:async/zone.dart:1026:19)
#8      _runZoned (dart:async/zone.dart:1525:10)
#9      runZoned (dart:async/zone.dart:1472:12)
#10     AppContext.run (package:flutter_tools/src/base/context.dart:149:18)
#11     FlutterCommand.run (package:flutter_tools/src/runner/flutter_command.dart:602:20)
#12     CommandRunner.runCommand (package:args/command_runner.dart:197:27)
#13     FlutterCommandRunner.runCommand.<anonymous closure>
(package:flutter_tools/src/runner/flutter_command_runner.dart:339:21)
<asynchronous suspension>
#14     FlutterCommandRunner.runCommand.<anonymous closure>
(package:flutter_tools/src/runner/flutter_command_runner.dart)
#15     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:29)
#16     _rootRun (dart:async/zone.dart:1133:13)
#17     _CustomZone.run (dart:async/zone.dart:1026:19)
#18     _runZoned (dart:async/zone.dart:1525:10)
#19     runZoned (dart:async/zone.dart:1472:12)
#20     AppContext.run (package:flutter_tools/src/base/context.dart:149:18)
#21     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:288:19)
#22     CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:112:25)
#23     new Future.sync (dart:async/future.dart:224:31)
#24     CommandRunner.run (package:args/command_runner.dart:112:14)
#25     FlutterCommandRunner.run (package:flutter_tools/src/runner/flutter_command_runner.dart:231:18)
#26     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:62:22)
#27     _rootRun (dart:async/zone.dart:1133:13)
#28     _CustomZone.run (dart:async/zone.dart:1026:19)
#29     _runZoned (dart:async/zone.dart:1525:10)
#30     runZoned (dart:async/zone.dart:1509:12)
#31     run.<anonymous closure> (package:flutter_tools/runner.dart:60:18)
<asynchronous suspension>
#32     run.<anonymous closure> (package:flutter_tools/runner.dart)
#33     runInContext.runnerWrapper (package:flutter_tools/src/context_runner.dart:67:18)
<asynchronous suspension>
#34     runInContext.runnerWrapper (package:flutter_tools/src/context_runner.dart)
#35     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:29)
#36     _rootRun (dart:async/zone.dart:1133:13)
#37     _CustomZone.run (dart:async/zone.dart:1026:19)
#38     _runZoned (dart:async/zone.dart:1525:10)
#39     runZoned (dart:async/zone.dart:1472:12)
#40     AppContext.run (package:flutter_tools/src/base/context.dart:149:18)
#41     runInContext (package:flutter_tools/src/context_runner.dart:70:24)
#42     run (package:flutter_tools/runner.dart:47:10)
#43     main (package:flutter_tools/executable.dart:69:9)
#44     main (file:///D:/my-tools/flutter/packages/flutter_tools/bin/flutter_tools.dart:8:3)
#45     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:299:32)
#46     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:168:12)
```

**Comment by TahaTesser** [comment]
Hi @januwA 
Please connect device or launch emulator then execute `flutter run --verbose`
Thank you

**Comment by januwA** [comment]
```sh
D:\ajanuw\flutter_demo>flutter run -d "SM G8750" --verbose
[  +16 ms] executing: [D:\my-tools\flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[  +67 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[        ] 8c0b43bda4e5ff29d399f06ce1c0e1027268d6b5
[        ] executing: [D:\my-tools\flutter/] git describe --match v*.*.* --first-parent --long --tags
[  +66 ms] Exit code 0 from: git describe --match v*.*.* --first-parent --long --tags
[        ] v1.16.1-41-g8c0b43bda
[   +5 ms] executing: [D:\my-tools\flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[  +49 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/master
[        ] executing: [D:\my-tools\flutter/] git ls-remote --get-url origin
[  +42 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[  +82 ms] executing: [D:\my-tools\flutter/] git rev-parse --abbrev-ref HEAD
[  +44 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[   +1 ms] master
[  +41 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +3 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +13 ms] executing: D:\my-tools\Android\sdk\platform-tools\adb.exe devices -l
[  +62 ms] List of devices attached
           c5976a52               device product:dreamliteqltezc model:SM_G8750 device:dreamliteqltechn transport_id:1
[   +5 ms] D:\my-tools\Android\sdk\platform-tools\adb.exe -s c5976a52 shell getprop
[ +141 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[   +5 ms] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +4 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[ +157 ms] Generating D:\ajanuw\flutter_demo\android\app\src\main\java\io\flutter\plugins\GeneratedPluginRegistrant.java
[  +19 ms] ro.hardware = qcom
[  +25 ms] Launching lib\main.dart on SM G8750 in debug mode...
[   +9 ms] D:\my-tools\flutter\bin\cache\dart-sdk\bin\dart.exe D:\my-tools\flutter\bin\cache\artifacts\engine\windows-x64\frontend_server.dart.snapshot --sdk-root
D:\my-tools\flutter\bin\cache\artifacts\engine\common\flutter_patched_sdk/ --incremental --target=flutter --debugger-module-names -Ddart.developer.causal_async_stacks=true --output-dill
C:\Users\ajanuw\AppData\Local\Temp\flutter_tool.b7f2490a-6d1b-11ea-a2d1-3c2c30a6a2d0\app.dill --packages D:\ajanuw\flutter_demo\.packages -Ddart.vm.profile=false -Ddart.vm.product=false
--bytecode-options=source-positions,local-var-info,debugger-stops,instance-field-initializers,keep-unreachable-code,avoid-closure-call-instructions --enable-asserts --track-widget-creation --filesystem-scheme
org-dartlang-root --initialize-from-dill build\cache.dill
[  +19 ms] executing: D:\my-tools\Android\sdk\platform-tools\adb.exe -s c5976a52 shell -x logcat -v time -t 1
[ +176 ms] Exit code 0 from: D:\my-tools\Android\sdk\platform-tools\adb.exe -s c5976a52 shell -x logcat -v time -t 1
[   +1 ms] --------- beginning of system
           03-23 23:34:02.360 D/ConnectivityService( 1889): filterNetworkStateForUid() uid: 10033, pid: 11440, networkInfo: [type: WIFI[], state: CONNECTED/CONNECTED, reason: (unspecified), extra: (none),
           failover: false, available: true, roaming: false]
[   +8 ms] <- compile package:flutter_demo/main.dart
[  +31 ms] executing: D:\my-tools\Android\sdk\platform-tools\adb.exe version
[  +59 ms] Android Debug Bridge version 1.0.41
           Version 29.0.6-6198805
           Installed as D:\my-tools\Android\sdk\platform-tools\adb.exe
[   +4 ms] executing: D:\my-tools\Android\sdk\platform-tools\adb.exe start-server
[  +54 ms] Building APK
[  +16 ms] Running Gradle task 'assembleDebug'...
[   +2 ms] gradle.properties already sets `android.enableR8`
[   +3 ms] Using gradle from D:\ajanuw\flutter_demo\android\gradlew.bat.
[   +1 ms] D:\ajanuw\flutter_demo\android\gradlew.bat mode: 33279 rwxrwxrwx.
[   +7 ms] executing: D:\my-tools\Android\AndroidStudio\jre\bin\java -version
[  +93 ms] Exit code 0 from: D:\my-tools\Android\AndroidStudio\jre\bin\java -version
[   +1 ms] openjdk version "1.8.0_212-release"
           OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)
           OpenJDK 64-Bit Server VM (build 25.212-b04, mixed mode)
[   +3 ms] executing: [D:\ajanuw\flutter_demo\android/] D:\ajanuw\flutter_demo\android\gradlew.bat -Pverbose=true -Ptarget-platform=android-arm64 -Ptarget=D:\ajanuw\flutter_demo\lib\main.dart
-Ptrack-widget-creation=true -Pfilesystem-scheme=org-dartlang-root assembleDebug
[+1578 ms] Starting a Gradle Daemon, 17 busy and 1 incompatible and 1 stopped Daemons could not be reused, use --status for details
```

**Comment by TahaTesser** [comment]
Hi @januwA 
Could you  please try with different connection? From this [comment](https://github.com/flutter/flutter/issues/49419#issuecomment-578658821)

Related to [#49419](https://github.com/flutter/flutter/issues/49419)
Thank you

**Comment by januwA** [comment]
hi, before I asked this question, I have looked at that problem, I tried to switch the network to mobile hotspot, but it still doesn't work ...

**Comment by jmagman** [comment]
Can you download any of them on your network from a browser?  Or cURL? https://storage.googleapis.com/download.flutter.io/io/flutter/flutter_embedding_debug/1.0.0-fd60ddf7517ce2bfd6577636bda2065c0e492664/flutter_embedding_debug-1.0.0-fd60ddf7517ce2bfd6577636bda2065c0e492664.jar

Until you get that fixed on your network it's going to keep failing.

**Comment by jmagman** [comment]
Hm I don't know how Gradle is set up to use `FLUTTER_STORAGE_BASE_URL`.

**Comment by jmagman** [comment]
\cc @blasten do you know?

**Comment by januwA** [comment]
https://blog.csdn.net/wo122282967/article/details/105589103

**Comment by MohYasinMohammadi** [comment]
Just run this command: 

-> flutter clean

**Comment by 9jadev** [comment]
I have the same problem  and flutter clean isn't working

**Comment by razzazcode** [comment]
I have the exact same problem 
I ran flutter upgrade on command line but it still doesnot work properly >> what is the problem with it ?
I am using android studio for building my flutter project but it does not run the app on the device or emulator ?
![errorflutter](https://user-images.githubusercontent.com/48647269/96973010-9a2cf200-1517-11eb-9a0d-e74f42c250d1.jpg)

**Comment by TahaTesser** [comment]
Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.

**Comment by Ronexan** [comment]
m

**Comment by Isuru01** [comment]
> https://blog.csdn.net/wo122282967/article/details/105589103

please can you say in English how did you fix this

**Comment by Isuru01** [comment]
> I have the exact same problem
> I ran flutter upgrade on command line but it still doesnot work properly >> what is the problem with it ?
> I am using android studio for building my flutter project but it does not run the app on the device or emulator ?
> ![errorflutter](https://user-images.githubusercontent.com/48647269/96973010-9a2cf200-1517-11eb-9a0d-e74f42c250d1.jpg)



> https://blog.csdn.net/wo122282967/article/details/105589103



> I have the exact same problem
> I ran flutter upgrade on command line but it still doesnot work properly >> what is the problem with it ?
> I am using android studio for building my flutter project but it does not run the app on the device or emulator ?
> ![errorflutter](https://user-images.githubusercontent.com/48647269/96973010-9a2cf200-1517-11eb-9a0d-e74f42c250d1.jpg)

Please can you tell me how did you fix this?
