### ISSUE TITLE
[cocoon backend] Reduce the rate of grpc and transaction aborted errors

### ISSUE THREAD

**Issue by godofredoc** [flutter/flutter#53148]
Remove high rate of grpc and transaction aborted errors:

* /api/refresh-chromebot-status
* /api/reserve-task
* /api/public/build-status
* /api/public/get-benchmarks
* /api/push-gold-status-to-github
* /api/update-agent-health

```
The transaction was aborted.
#0      GrpcDatastoreImpl.commit (package:appengine/src/grpc_api_impl/datastore_impl.dart:111:9)
<asynchronous suspension>
#1      _commitHelper (package:gcloud/src/db/db.dart:409:8)
#2      Transaction.commit (package:gcloud/src/db/db.dart:104:14)
#3      RefreshChromebotStatus.get.<anonymous closure>.<anonymous closure> (package:cocoon_service/src/request_handlers/refresh_chromebot_status.dart:68:31)
<asynchronous suspension>
#4      DatastoreDB.withTransaction.<anonymous closure> (package:gcloud/src/db/db.dart:302:32)
#5      _rootRunUnary (dart:async/zone.dart:1134:38)
#6      _CustomZone.runUnary (dart:async/zone.dart:1031:19)
#7      _FutureListener.handleValue (dart:async/future_impl.dart:139:18)
#8      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:680:45)
#9      Future._propagateToListeners (dart:async/future_impl.dart:709:32)
#10     Future._completeWithValue (dart:async/future_impl.dart:524:5)
#11     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:32:15)
#12     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:290:13)
#13     GrpcDatastoreImpl.beginTransaction (package:appengine/src/grpc_api_impl/datastore_impl.dart)
<asynchronous suspension>
#14     DatastoreDB.withTransaction (package:gcloud/src/db/db.dart:299:10)
#15     RefreshChromebotStatus.get.<anonymous closure> (package:cocoon_service/src/request_handlers/refresh_chromebot_status.dart:54:25)
#16     RetryOptions.retry (package:retry/retry.dart:130:24)
<asynchronous suspension>
#17     runTransactionWithRetries (package:cocoon_service/src/foundation/utils.dart:83:12)
#18     RefreshChromebotStatus.get (package:cocoon_service/src/request_handlers/refresh_chromebot_status.dart:53:13)
<asynchronous suspension>
#19     RequestHandler.service.<anonymous closure> (package:cocoon_service/src/request_handling/request_handler.dart:46:28)
#20     _rootRun (dart:async/zone.dart:1126:13)
#21     _CustomZone.run (dart:async/zone.dart:1023:19)
#22     _runZoned (dart:async/zone.dart:1518:10)
#23     runZoned (dart:async/zone.dart:1465:12)
#24     RequestHandler.service (package:cocoon_service/src/request_handling/request_handler.dart:39:12)
#25     ApiRequestHandler.service.<anonymous closure> (package:cocoon_service/src/request_handling/api_request_handler.dart:139:19)
#26     _rootRun (dart:async/zone.dart:1126:13)
#27     _CustomZone.run (dart:async/zone.dart:1023:19)
#28     _runZoned (dart:async/zone.dart:1518:10)
#29     runZoned (dart:async/zone.dart:1465:12)
#30     ApiRequestHandler.service (package:cocoon_service/src/request_handling/api_request_handler.dart:138:11)
<asynchronous suspension>
#31     main.<anonymous closure>.<anonymous closure> (file:///app/bin/server.dart:83:23)
#32     runAppEngine.<anonymous closure> (package:appengine/appengine.dart:80:12)
#33     runAppEngine.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:appengine/src/appengine_internal.dart:59:18)
#34     _ServiceScope._fork.<anonymous closure> (package:gcloud/service_scope.dart:209:19)
#35     _rootRun (dart:async/zone.dart:1126:13)
#36     _CustomZone.run (dart:async/zone.dart:1023:19)
#37     _runZoned (dart:async/zone.dart:1518:10)
#38     runZoned (dart:async/zone.dart:1502:12)
#39     _ServiceScope._fork (package:gcloud/service_scope.dart:208:12)
#40     fork (package:gcloud/service_scope.dart:104:30)
#41     runAppEngine.<anonymous closure>.<anonymous closure> (package:appengine/src/appengine_internal.dart:57:9)
#42     AppEngineHttpServer.run.<anonymous closure>.<anonymous closure> (package:appengine/src/server/server.dart:83:16)
#43     _rootRunUnary (dart:async/zone.dart:1134:38)
#44     _CustomZone.runUnary (dart:async/zone.dart:1031:19)
#45     _CustomZone.runUnaryGuarded (dart:async/zone.dart:933:7)
#46     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:338:11)
#47     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:265:7)
#48     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:766:19)
#49     _StreamController._add (dart:async/stream_controller.dart:642:7)
#50     _StreamController.add (dart:async/stream_controller.dart:588:5)
#51     _HttpServer._handleRequest (dart:_http/http_impl.dart:2828:19)
#52     new _HttpConnection.<anonymous closure> (dart:_http/http_impl.dart:2586:19)
#53     _rootRunUnary (dart:async/zone.dart:1134:38)
#54     _CustomZone.runUnary (dart:async/zone.dart:1031:19)
#55     _CustomZone.runUnaryGuarded (dart:async/zone.dart:933:7)
#56     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:338:11)
#57     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:265:7)
#58     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:766:19)
#59     _StreamController._add (dart:async/stream_controller.dart:642:7)
#60     _StreamController.add (dart:async/stream_controller.dart:588:5)
#61     _HttpParser._headersEnd (dart:_http/http_parser.dart:374:19)
#62     _HttpParser._doParse (dart:_http/http_parser.dart:703:15)
#63     _HttpParser._parse (dart:_http/http_parser.dart:320:7)
#64     _HttpParser._onData (dart:_http/http_parser.dart:812:5)
#65     _rootRunUnary (dart:async/zone.dart:1134:38)
#66     _CustomZone.runUnary (dart:async/zone.dart:1031:19)
#67     _CustomZone.runUnaryGuarded (dart:async/zone.dart:933:7)
#68     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:338:11)
#69     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:265:7)
#70     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:766:19)
#71     _StreamController._add (dart:async/stream_controller.dart:642:7)
#72     _StreamController.add (dart:async/stream_controller.dart:588:5)
#73     _Socket._onData (dart:io-patch/socket_patch.dart:1831:41)
#74     _rootRunUnary (dart:async/zone.dart:1138:13)
#75     _CustomZone.runUnary (dart:async/zone.dart:1031:19)
#76     _CustomZone.runUnaryGuarded (dart:async/zone.dart:933:7)
#77     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:338:11)
#78     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:265:7)
#79     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:766:19)
#80     _StreamController._add (dart:async/stream_controller.dart:642:7)
#81     _StreamController.add (dart:async/stream_controller.dart:588:5)
#82     new _RawSocket.<anonymous closure> (dart:io-patch/socket_patch.dart:1379:33)
#83     _NativeSocket.issueReadEvent.issue (dart:io-patch/socket_patch.dart:899:14)
#84     _microtaskLoop (dart:async/schedule_microtask.dart:43:21)
#85     _startMicrotaskLoop (dart:async/schedule_microtask.dart:52:5)
#86     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
#87     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:175:5)
```

**Comment by godofredoc** [comment]
Fixed with: 
Update remaining handlers to use service/datastore https://github.com/flutter/cocoon/pull/737.
Refactor handlers to use service/datastore https://github.com/flutter/cocoon/pull/736. 
Refactor reserve_task handler to use datastore https://github.com/flutter/cocoon/pull/732.
