### ISSUE TITLE
image_picker plugin does not work

### ISSUE THREAD

**Issue by xzqbetter** [flutter/flutter#53230]
My ios project embed a flutter module, 
when use the `image_picker` plugin to pick image, it has a problem：
- the called method is `ImagePicker.pickImage(source: ImageSource.gallery)`
- when I run the app from flutter, it works success, but when I run from Xcode(ios project), it does not work

The detail operation is:
- when call the method `ImagePicker.pickImage` the first time, it has no response and no error
- when call the method second, it print the error

error

```
[VERBOSE-2:ui_dart_state.cc(157)] Unhandled Exception: PlatformException(multiple_request, Cancelled by a second request, null)
#0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:569:7)
#1      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:321:33)
<asynchronous suspension>
#2      ImagePicker.pickImage (package:image_picker/image_picker.dart:61:40)
#3      ImageUtils.pickImageFromGalleryCompress (package:flutter_dl/code_new/wsy/im/image_utils.dart:50:35)
#4      ImServiceController.onGalleryClick (package:flutter_dl/code_new/wsy/im/controller.dart:523:34)
#5      _ImPicWidgetState.build.<anonymous closure>.<anonymous closure> (package:flutter_dl/code_new/wsy/im/view.dart:597:26)
#6      _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:706:14)
#7      _InkResponseState.build.<anonymous closure> (package:flutter/src/material/ink_well.dart:789:36)
#8      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:182:24)
#9      TapGestureRecognizer.handleTapUp (package:flutter/src/gestures/tap.dart:486:11)
#10     BaseTapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:264:5)
#11     BaseTapGestureRecognizer.acceptGesture (package:flutter/src/gestures/tap.dart:236:7)
#12     GestureArenaManager.sweep (package:flutter/src/gestures/arena.dart:156:27)
#13     GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:222:20)
#14     GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:198:22)
#15     GestureBinding._handlePointerEvent (package:flutter/src/gestures/binding.dart:156:7)
#16     GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:102:7)
#17     GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:86:7)
#18     _rootRunUnary (dart:async/zone.dart:1138:13)
#19     _CustomZone.runUnary (dart:async/zone.dart:1031:19)
#20     _CustomZone.runUnaryGuarded (dart:async/zone.dart:933:7)
#21     _invoke1 (dart:ui/hooks.dart:273:10)
#22     _dispatchPointerDataPacket (dart:ui/hooks.dart:182:5)
```

flutter doctor -v

```
[✓] Flutter (Channel stable, v1.12.13+hotfix.5, on Mac OS X 10.14.6 18G2022,
    locale zh-Hans-CN)
    • Flutter version 1.12.13+hotfix.5 at /Users/xzq/Develop/flutter
    • Framework revision 27321ebbad (4 months ago), 2019-12-10 18:15:01 -0800
    • Engine revision 2994f7e1e6
    • Dart version 2.7.0

 
[!] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/xzq/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling
      support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_202-release-1483-b49-5587405)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor
      --android-licenses

[✓] Xcode - develop for iOS and macOS (Xcode 11.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.3.1, Build version 11C504
    • CocoaPods version 1.7.4

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 41.1.2
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build
      1.8.0_202-release-1483-b49-5587405)
```

**Comment by VladyslavBondarenko** [comment]
Possibly related to https://github.com/flutter/flutter/issues/49780

**Comment by jmagman** [comment]
Are you running from `ios/Runner.xcworkspace` and NOT `ios/Runner.xcproject`?

**Comment by shashikantshaale** [comment]
I am running in android, getting null when pick `ImagePicker.pickImage(source: ImageSource.gallery);`

**Comment by shashikantdurge** [comment]
In android the images selected from Recent returns null.
![Screenshot_20200404-070502](https://user-images.githubusercontent.com/20161204/78415955-ce57c880-7642-11ea-9f9f-553baf27411e.png)

**Comment by VladyslavBondarenko** [comment]
@shashikantdurge with your case follow up on https://github.com/flutter/flutter/issues/53514

**Comment by VladyslavBondarenko** [comment]
@shashikantshaale is https://github.com/flutter/flutter/issues/53514 your case? or you receive `null` not only from the recent section?

**Comment by shashikantdurge** [comment]
Yes that's my case! I get non-null value other than Recent
