### ISSUE TITLE
Hotloading in VSCode is still crashing (ERR_STREAM_DESTROYED)

### ISSUE THREAD

**Issue by cyberpwnn** [flutter/flutter#53246]
## Steps to Reproduce

1. Channel into beta or stable
2. Build for android in vscode
3. Watch the dart analyzer crash in seconds, entire ide is useless until you click restart.

However restarting it only fixes the IDE, it doesnt fix hotloading.

The only solution I have found was to stop the app, close vscode, re-open vs code and rerun debugging, only to have it fail again in 20 minutes which kind of makes hotloading a complete waste of time. It's now faster to rebuild the app every time to test it instead of risking the ide glitching out again.

## Logs

From the analyzer 
```
.....
[8:59:18 AM] [Observatory] [Info] [Flutter] <== {"jsonrpc":"2.0","method":"streamNotify","params":{"streamId":"Extension","event":{"type":"Event","kind":"Extension","extensionKind":"Flutter.Frame","isolate":{"type":"@Isolate","id":"isolates\/2161755825541303","name":"main","number":"2161755825541303"},"timestamp":1585141124257,"extensionData":{"number":231,"startTime":1273650175931,"elapsed":43219,"build":9223,"raster":19997}}}}
[8:59:18 AM] [Observatory] [Info] [Flutter] <== {"jsonrpc":"2.0","method":"streamNotify","params":{"streamId":"Extension","event":{"type":"Event","kind":"Extension","extensionKind":"Flutter.Frame","isolate":{"type":"@Isolate","id":"isolates\/2161755825541303","name":"main","number":"2161755825541303"},"timestamp":1585141124258,"extensionData":{"number":232,"startTime":1273650209357,"elapsed":30420,"build":3724,"raster":20554}}}}
[8:59:21 AM] [Analyzer] [Info] ==> {"id":"10894","method":"analysis.getHover","params":{"file":"C:\\Users\\cyberpwn\\Documents\\development\\workspace\\MyGuide\\app\\lib\\builder\\lesson_builder.dart","offset":15412},"clientRequestTime":1585141161902}
[8:59:21 AM] [General] [Error] Cannot call write after a stream was destroyed
Error [ERR_STREAM_DESTROYED]: Cannot call write after a stream was destroyed
	at doWrite (_stream_writable.js:414:19)
	at writeOrBuffer (_stream_writable.js:402:5)
	at Socket.Writable.write (_stream_writable.js:302:11)
	at b.sendMessage (c:\Users\cyberpwn\.vscode\extensions\dart-code.dart-code-3.8.1\out\dist\extension.js:1:58996)
	at b.sendMessage (c:\Users\cyberpwn\.vscode\extensions\dart-code.dart-code-3.8.1\out\dist\extension.js:1:53518)
	at c:\U…
[8:59:21 AM] [Analyzer] [Info] ==> {"id":"10895","method":"analysis.getNavigation","params":{"file":"C:\\Users\\cyberpwn\\Documents\\development\\workspace\\MyGuide\\app\\lib\\builder\\lesson_builder.dart","length":0,"offset":15413},"clientRequestTime":1585141161942}
[8:59:21 AM] [Analyzer] [Info] ==> {"id":"10896","method":"analysis.getNavigation","params":{"file":"C:\\Users\\cyberpwn\\Documents\\development\\workspace\\MyGuide\\app\\lib\\builder\\lesson_builder.dart","length":0,"offset":15446},"clientRequestTime":1585141161974}
[8:59:23 AM] [Analyzer] [Info] ==> {"id":"10897","method":"analysis.updateContent","params":{"files":{"C:\\Users\\cyberpwn\\Documents\\development\\workspace\\MyGuide\\app\\lib\\builder\\lesson_builder.dart":{"edits":[{"offset":0,"length":0,"replacement":"","id":""}],"type":"change"}}},"clientRequestTime":1585141163442}
[8:59:23 AM] [Analyzer] [Info] ==> {"id":"10898","method":"analysis.updateContent","params":{"files":{"C:\\Users\\cyberpwn\\Documents\\development\\workspace\\MyGuide\\app\\lib\\builder\\lesson_builder.dart":{"edits":[{"offset":0,"length":0,"replacement":"","id":""}],"type":"change"}}},"clientRequestTime":1585141163445}
[8:59:25 AM] [Analyzer] [Info] ==> {"id":"10899","method":"analysis.setSubscriptions","params":{"subscriptions":{"CLOSING_LABELS":["C:\\Users\\cyberpwn\\Documents\\development\\workspace\\MyGuide\\app\\lib\\builder\\good_job.dart","C:\\Users\\cyberpwn\\Documents\\development\\workspace\\MyGuide\\app\\lib\\builder\\lesson_builder.dart","C:\\Users\\cyberpwn\\Documents\\development\\workspace\\MyGuide\\app\\lib\\builder\\plugin\\plugin_choices.dart","C:\\Users\\cyberpwn\\Documents\\development\\workspace\\MyGuide\\app\\lib\\buil…
[8:59:25 AM] [Analyzer] [Info] ==> {"id":"10900","method":"analysis.updateContent","params":{"files":{"C:\\Users\\cyberpwn\\Documents\\development\\workspace\\MyGuide\\app\\lib\\util\\myguide_theme.dart":{"type":"remove"}}},"clientRequestTime":1585141165140}
[8:59:25 AM] [Analyzer] [Info] ==> {"id":"10901","method":"analysis.setPriorityFiles","params":{"files":[]},"clientRequestTime":1585141165142}
[8:59:25 AM] [General] [Error] Cannot call write after a stream was destroyed
Error [ERR_STREAM_DESTROYED]: Cannot call write after a stream was destroyed
	at doWrite (_stream_writable.js:414:19)
	at writeOrBuffer (_stream_writable.js:402:5)
	at Socket.Writable.write (_stream_writable.js:302:11)
	at b.sendMessage (c:\Users\cyberpwn\.vscode\extensions\dart-code.dart-code-3.8.1\out\dist\extension.js:1:58996)
	at b.sendMessage (c:\Users\cyberpwn\.vscode\extensions\dart-code.dart-code-3.8.1\out\dist\extension.js:1:53518)
	at c:\U…
[8:59:25 AM] [Analyzer] [Info] ==> {"id":"10902","method":"flutter.setSubscriptions","params":{"subscriptions":{"OUTLINE":["C:\\Users\\cyberpwn\\Documents\\development\\workspace\\MyGuide\\app\\lib\\builder\\good_job.dart","C:\\Users\\cyberpwn\\Documents\\development\\workspace\\MyGuide\\app\\lib\\builder\\lesson_builder.dart","C:\\Users\\cyberpwn\\Documents\\development\\workspace\\MyGuide\\app\\lib\\builder\\plugin\\plugin_choices.dart","C:\\Users\\cyberpwn\\Documents\\development\\workspace\\MyGuide\\app\\lib\\builder\\plu…
[8:59:25 AM] [General] [Error] Cannot call write after a stream was destroyed
Error [ERR_STREAM_DESTROYED]: Cannot call write after a stream was destroyed
	at doWrite (_stream_writable.js:414:19)
	at writeOrBuffer (_stream_writable.js:402:5)
	at Socket.Writable.write (_stream_writable.js:302:11)
	at b.sendMessage (c:\Users\cyberpwn\.vscode\extensions\dart-code.dart-code-3.8.1\out\dist\extension.js:1:58996)
	at b.sendMessage (c:\Users\cyberpwn\.vscode\extensions\dart-code.dart-code-3.8.1\out\dist\extension.js:1:53518)
	at c:\U…
[8:59:25 AM] [General] [Error] Cannot call write after a stream was destroyed
Error [ERR_STREAM_DESTROYED]: Cannot call write after a stream was destroyed
	at doWrite (_stream_writable.js:414:19)
	at writeOrBuffer (_stream_writable.js:402:5)
	at Socket.Writable.write (_stream_writable.js:302:11)
	at b.sendMessage (c:\Users\cyberpwn\.vscode\extensions\dart-code.dart-code-3.8.1\out\dist\extension.js:1:58996)
	at b.sendMessage (c:\Users\cyberpwn\.vscode\extensions\dart-code.dart-code-3.8.1\out\dist\extension.js:1:53518)
	at c:\U…
[9:01:23 AM] [Analyzer] [Info] ==> {"id":"10903","method":"edit.getFixes","params":{"file":"C:\\Users\\cyberpwn\\Documents\\development\\workspace\\MyGuide\\app\\lib\\homepage\\home.dart","offset":0},"clientRequestTime":1585141283198}
[9:01:23 AM] [Analyzer] [Info] ==> {"id":"10904","method":"edit.getAssists","params":{"file":"C:\\Users\\cyberpwn\\Documents\\development\\workspace\\MyGuide\\app\\lib\\homepage\\home.dart","length":0,"offset":0},"clientRequestTime":1585141283200}
[9:01:23 AM] [Analyzer] [Info] ==> {"id":"10905","method":"edit.getAvailableRefactorings","params":{"file":"C:\\Users\\cyberpwn\\Documents\\development\\workspace\\MyGuide\\app\\lib\\homepage\\home.dart","length":0,"offset":0},"clientRequestTime":1585141283201}
[9:01:23 AM] [Analyzer] [Info] ==> {"id":"10906","method":"analysis.setPriorityFiles","params":{"files":["C:\\Users\\cyberpwn\\Documents\\development\\workspace\\MyGuide\\app\\lib\\homepage\\home.dart"]},"clientRequestTime":1585141283203}
[9:01:23 AM] [Analyzer] [Info] ==> {"id":"10907","method":"analysis.updateContent","params":{"files":{"C:\\Users\\cyberpwn\\Documents\\development\\workspace\\MyGuide\\app\\lib\\homepage\\home.dart":{"edits":[{"offset":0,"length":0,"replacement":"","id":""}],"type":"change"}}},"clientRequestTime":1585141283208}
[9:01:23 AM] [Analyzer] [Info] ==> {"id":"10908","method":"analysis.updateContent","params":{"files":{"C:\\Users\\cyberpwn\\Documents\\development\\workspace\\MyGuide\\app\\lib\\homepage\\home.dart":{"edits":[{"offset":0,"length":0,"replacement":"","id":""}],"type":"change"}}},"clientRequestTime":1585141283209}
[9:01:23 AM] [General] [Error] Cannot call write after a stream was destroyed
Error [ERR_STREAM_DESTROYED]: Cannot call write after a stream was destroyed
	at doWrite (_stream_writable.js:414:19)
	at writeOrBuffer (_stream_writable.js:402:5)
	at Socket.Writable.write (_stream_writable.js:302:11)
	at b.sendMessage (c:\Users\cyberpwn\.vscode\extensions\dart-code.dart-code-3.8.1\out\dist\extension.js:1:58996)
	at b.sendMessage (c:\Users\cyberpwn\.vscode\extensions\dart-code.dart-code-3.8.1\out\dist\extension.js:1:53518)
	at c:\U…
[9:01:23 AM] [General] [Error] Cannot call write after a stream was destroyed
Error [ERR_STREAM_DESTROYED]: Cannot call write after a stream was destroyed
	at doWrite (_stream_writable.js:414:19)
	at writeOrBuffer (_stream_writable.js:402:5)
	at Socket.Writable.write (_stream_writable.js:302:11)
	at b.sendMessage (c:\Users\cyberpwn\.vscode\extensions\dart-code.dart-code-3.8.1\out\dist\extension.js:1:58996)
	at b.sendMessage (c:\Users\cyberpwn\.vscode\extensions\dart-code.dart-code-3.8.1\out\dist\extension.js:1:53518)
	at c:\U…
[9:01:23 AM] [General] [Error] Cannot call write after a stream was destroyed
Error [ERR_STREAM_DESTROYED]: Cannot call write after a stream was destroyed
	at doWrite (_stream_writable.js:414:19)
	at writeOrBuffer (_stream_writable.js:402:5)
	at Socket.Writable.write (_stream_writable.js:302:11)
	at b.sendMessage (c:\Users\cyberpwn\.vscode\extensions\dart-code.dart-code-3.8.1\out\dist\extension.js:1:58996)
	at b.sendMessage (c:\Users\cyberpwn\.vscode\extensions\dart-code.dart-code-3.8.1\out\dist\extension.js:1:53518)
	at c:\U…
[9:01:23 AM] [Analyzer] [Info] ==> {"id":"10909","method":"edit.getFixes","params":{"file":"C:\\Users\\cyberpwn\\Documents\\development\\workspace\\MyGuide\\app\\lib\\homepage\\home.dart","offset":615},"clientRequestTime":1585141283417}
[9:01:23 AM] [Analyzer] [Info] ==> {"id":"10910","method":"edit.getAssists","params":{"file":"C:\\Users\\cyberpwn\\Documents\\development\\workspace\\MyGuide\\app\\lib\\homepage\\home.dart","length":0,"offset":615},"clientRequestTime":1585141283418}
[9:01:23 AM] [Analyzer] [Info] ==> {"id":"10911","method":"edit.getAvailableRefactorings","params":{"file":"C:\\Users\\cyberpwn\\Documents\\development\\workspace\\MyGuide\\app\\lib\\homepage\\home.dart","length":0,"offset":615},"clientRequestTime":1585141283418}
```

Flutter Doctor -v (I dont use android studio)
```
[√] Flutter (Channel stable, v1.12.13+hotfix.8, on Microsoft Windows [Version 10.0.18363.657], locale en-US)
    • Flutter version 1.12.13+hotfix.8 at C:\Users\cyberpwn\Documents\development\flutter
    • Framework revision 0b8abb4724 (6 weeks ago), 2020-02-11 11:44:36 -0800
    • Engine revision e1e6ced81d
    • Dart version 2.7.0


[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at C:\Users\cyberpwn\AppData\Local\Android\Sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • ANDROID_HOME = C:\Users\cyberpwn\AppData\Local\Android\Sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)
    • All Android licenses accepted.

[!] Android Studio (version 3.5)
    • Android Studio at C:\Program Files\Android\Android Studio
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)

[√] VS Code (version 1.43.2)
    • VS Code at C:\Users\cyberpwn\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.8.1

[√] Connected device (1 available)
    • Nokia 6 1 • PL2GARM863007117 • android-arm64 • Android 10 (API 29)

! Doctor found issues in 1 category.
```

**Comment by VladyslavBondarenko** [comment]
Possibly related to https://github.com/flutter/flutter/issues/53201

**Comment by Ludonope** [comment]
@VladyslavBondarenko I'm not sure about it, both issues seems pretty different to me, there is no ` ERR_STREAM_DESTROYED` error in the issue you linked.

**Comment by jmagman** [comment]
Please file against Dart, see https://github.com/dart-lang/sdk/issues/40747.
