### ISSUE TITLE
elide unmounting loop from stacks

### ISSUE THREAD

**Issue by Hixie** [flutter/flutter#53294]
```
#7      ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4556:14)
#8      _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1918:13)
#9      _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1920:7)
#10     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4556:14)
#11     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1918:13)
#12     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1920:7)
#13     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4556:14)
#14     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1918:13)
#15     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1920:7)
#16     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:5817:14)
#17     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1918:13)
#18     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1920:7)
#19     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4556:14)
#20     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1918:13)
#21     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1920:7)
#22     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:5817:14)
#23     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1918:13)
#24     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1920:7)
#25     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:5817:14)
#26     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1918:13)
#27     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1920:7)
#28     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4556:14)
#29     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1918:13)
#30     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1920:7)
#31     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:5817:14)
#32     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1918:13)
#33     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1920:7)
#34     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:5817:14)
#35     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1918:13)
#36     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1920:7)
#37     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4556:14)
#38     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1918:13)
#39     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1920:7)
#40     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4556:14)
#41     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1918:13)
#42     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1920:7)
#43     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4556:14)
#44     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1918:13)
#45     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1920:7)
#46     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:5817:14)
#47     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1918:13)
#48     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1920:7)
#49     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4556:14)
#50     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1918:13)
#51     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1920:7)
#52     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:5817:14)
```

cc @dnfield

**Comment by dnfield** [comment]
Can you share some code that results in this?  Would be helpful for writing tests.

**Comment by Hixie** [comment]
an exception in the dispose of a leaf widget in a test that first did pumpWidget(somethingElaborate) then did pumpWidget(Container()).

**Comment by solarpower947** [comment]
This was really helpful. Thank you for the information!
[](https://www.solarpanelcostprice.com.au)

**Comment by Hixie** [comment]
@solarpower947 that's good to hear! can you elaborate on how it helped you so we can tweak the stack trace logic to be even more helpful for others?
