### ISSUE TITLE
video_player - Fatal Exception: java.lang.OutOfMemoryError: Failed to allocate a 16 byte allocation with 0 free bytes and 0B until OOM, target footprint 201339504, growth limit 201326592

### ISSUE THREAD

**Issue by kw2019ltd** [flutter/flutter#53342]
issue with Video player:

```
Fatal Exception: java.lang.OutOfMemoryError: Failed to allocate a 16 byte allocation with 0 free bytes and 0B until OOM, target footprint 201339504, growth limit 201326592
       at com.google.android.exoplayer2.video.VideoRendererEventListener$EventDispatcher.disabled(VideoRendererEventListener.java:183)
       at com.google.android.exoplayer2.video.MediaCodecVideoRenderer.onDisabled(MediaCodecVideoRenderer.java:380)
       at com.google.android.exoplayer2.BaseRenderer.disable(BaseRenderer.java:153)
       at com.google.android.exoplayer2.ExoPlayerImplInternal.disableRenderer(ExoPlayerImplInternal.java:976)
       at com.google.android.exoplayer2.ExoPlayerImplInternal.resetInternal(ExoPlayerImplInternal.java:764)
       at com.google.android.exoplayer2.ExoPlayerImplInternal.releaseInternal(ExoPlayerImplInternal.java:745)
       at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:336)
       at android.os.Handler.dispatchMessage(Handler.java:103)
       at android.os.Looper.loop(Looper.java:237)
       at android.os.HandlerThread.run(HandlerThread.java:67)
```

![image](https://user-images.githubusercontent.com/47334522/77641576-ef465c80-6f64-11ea-9021-7b826bf25c9f.png)

**Comment by VladyslavBondarenko** [comment]
@kw2019ltd what video_player version do you use?

**Comment by kw2019ltd** [comment]
video_player: ^0.10.8+1

**Comment by kw2019ltd** [comment]
another one on different device.

![image](https://user-images.githubusercontent.com/47334522/80865168-2f99a880-8c90-11ea-937e-08ec672a1210.png)

**Comment by maheshmnj** [comment]
Hi @kw2019ltd,
Could you please provide the exact steps to reproduce the issue along with a minimal reproducible code, This will help to better investigate the issue.
This issue looks similar to https://github.com/flutter/flutter/issues/62118

**Comment by maheshmnj** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
