### ISSUE TITLE
image_picker FATAL EXCEPTION: main after capturing video

### ISSUE THREAD

**Issue by pablanka** [flutter/flutter#53360]
image_picker: ^0.6.3+4

Device: ONEPLUS A6013 - Android 10

This line `final videoFile = await ImagePicker.pickVideo(source: ImageSource.gallery);` throws the following

```
D/AndroidRuntime(32168): Shutting down VM
E/AndroidRuntime(32168): FATAL EXCEPTION: main
E/AndroidRuntime(32168): Process: io.siteplan.sytex, PID: 32168
E/AndroidRuntime(32168): java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=2353, result=-1, data=Intent { dat=content://io.siteplan.sytex.flutter.image_provider/external_files/Android/data/io.siteplan.sytex/files/Pictures/0bc952d8-bfea-44ad-8417-1044d9e735301892485930175686689.mp4 flg=0x1 }} to activity {io.siteplan.sytex/io.siteplan.sytex.MainActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String android.net.Uri.getPath()' on a null object reference
E/AndroidRuntime(32168): 	at android.app.ActivityThread.deliverResults(ActivityThread.java:4962)
E/AndroidRuntime(32168): 	at android.app.ActivityThread.handleSendResult(ActivityThread.java:5003)
E/AndroidRuntime(32168): 	at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:51)
E/AndroidRuntime(32168): 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
E/AndroidRuntime(32168): 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
E/AndroidRuntime(32168): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2109)
E/AndroidRuntime(32168): 	at android.os.Handler.dispatchMessage(Handler.java:107)
E/AndroidRuntime(32168): 	at android.os.Looper.loop(Looper.java:214)
E/AndroidRuntime(32168): 	at android.app.ActivityThread.main(ActivityThread.java:7682)
E/AndroidRuntime(32168): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(32168): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:516)
E/AndroidRuntime(32168): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)
E/AndroidRuntime(32168): Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String android.net.Uri.getPath()' on a null object reference
E/AndroidRuntime(32168): 	at com.javih.multimediapicker.MultiMediaPickerDelegate$3.getFullImagePath(MultiMediaPickerDelegate.java:147)
E/AndroidRuntime(32168): 	at com.javih.multimediapicker.MultiMediaPickerDelegate.handleCaptureVideoResult(MultiMediaPickerDelegate.java:467)
E/AndroidRuntime(32168): 	at com.javih.multimediapicker.MultiMediaPickerDelegate.onActivityResult(MultiMediaPickerDelegate.java:396)
E/AndroidRuntime(32168): 	at io.flutter.embedding.engine.FlutterEnginePluginRegistry$FlutterEngineActivityPluginBinding.onActivityResult(FlutterEnginePluginRegistry.java:691)
E/AndroidRuntime(32168): 	at io.flutter.embedding.engine.FlutterEnginePluginRegistry.onActivityResult(FlutterEnginePluginRegistry.java:378)
E/AndroidRuntime(32168): 	at io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.onActivityResult(FlutterActivityAndFragmentDelegate.java:597)
E/AndroidRuntime(32168): 	at io.flutter.embedding.android.FlutterActivity.onActivityResult(FlutterActivity.java:582)
E/AndroidRuntime(32168): 	at android.app.Activity.dispatchActivityResult(Activity.java:8135)
E/AndroidRuntime(32168): 	at android.app.ActivityThread.deliverResults(ActivityThread.java:4955)
E/AndroidRuntime(32168): 	... 11 more
I/Process (32168): Sending signal. PID: 32168 SIG: 9
Lost connection to device.
Exited (sigterm)
```
```
[✓] Flutter (Channel master, v1.16.3-pre.56, on Mac OS X 10.15.4 19E266, locale en-US)
    • Flutter version 1.16.3-pre.56 at /Users/siteplan/development/flutter
    • Framework revision 8857c4cec8 (16 hours ago), 2020-03-25 21:21:01 -0400
    • Engine revision b235233e9d
    • Dart version 2.8.0 (build 2.8.0-dev.17.0 2323087237)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/siteplan/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.3.1, Build version 11C505
    • CocoaPods version 1.9.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 44.0.2
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)

[✓] VS Code (version 1.43.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.8.1

[✓] VS Code (version 1.26.1)
    • VS Code at /Users/siteplan/Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.8.1

[✓] Connected device (3 available)
    • ONEPLUS A6013 • 223bfc49   • android-arm64  • Android 10 (API 29)
    • Chrome        • chrome     • web-javascript • Google Chrome 80.0.3987.149
    • Web Server    • web-server • web-javascript • Flutter Tools

• No issues found!
```

**Comment by VladyslavBondarenko** [comment]
Hi @pablanka 
Did it happen only once?
If you can reproduce it, could you provide a complete minimal reproducible code sample?
Have you tried different devices?
I'm not experiencing this when using this code https://pub.dev/packages/image_picker#-example-tab- with my Android 9 device

**Comment by pablanka** [comment]
The error is thrown when adding this plugin  `multi_media_picker: ^0.2.3`
I was able to reproduce it using https://pub.dev/packages/image_picker#-example-tab-
So, I think this issue is a `multi_media_picker` plugin error

**Comment by jamesmoore255** [comment]
I can confirm the `multi_media_picker` causes some kind of conflict with `image_picker` and causes `image_picker` to crash on android when taking a photo.
