### ISSUE TITLE
Flutter run fails with git SSH plugin dependency

### ISSUE THREAD

**Issue by LimeByte** [flutter/flutter#53387]
Flutter run fails when using a git SSH plugin dependency. Other dart only dependencies have had no issues.

## Steps to Reproduce

1. Add dependency on a flutter plugin via ssh
2. Run `flutter run` or debug in Android Studio
3. Fails with:

```
Target kernel_snapshot failed: FileSystemException: Cannot open file, path = 'C:\dev\flutter\.pub-cache\git\observable-session-303db1f443873157e8fe06013725d62fcfd1f816\.packages' (OS Error: The system cannot find the file specified.
, errno = 2)
```

## What I've Tried

- `flutter clean`
- `flutter pub cache repair`
- Deleted `.flutter-plugins`, `.flutter-plugins-dependencies`, `.packages` and `pubspec.lock` in app 
- Deleted `C:\dev\flutter\.pub-cache\git`

## Plugin pubspec.yaml

```yaml
name: observable_session
description: Observable session storage
version: 0.1.0

environment:
  sdk: ">=2.7.1 <3.0.0"
  flutter: ">=1.14.6"

dependencies:
  flutter:
    sdk: flutter
  meta: ^1.1.8
  equatable: ^1.1.1
  pedantic: ^1.9.0

dev_dependencies:
  test: ^1.6.0
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.fssi.business.observablesession
        pluginClass: ObservableSessionPlugin
```

## App pubspec.yaml (Git URLs removed)

```yaml
name: android_launcher
description: Flutter based Android launcher for dedicated devices.
version: 1.0.0+1

environment:
  sdk: ">=2.7.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  data_state:
    git: <private git url>
  http: ^0.12.0+4
  meta: ^1.1.8
  observable_session:
    git: <private git url>
  provider: ^4.0.4
  sap_oauth2:
    git: <private git url>
  simple_animations: ^1.3.11

dev_dependencies:
  flutter_test:
    sdk: flutter
  effective_dart: ^1.2.1

flutter:
  uses-material-design: true
  assets:
    - assets/
```

## Pub Cache folder for plugin

![image](https://user-images.githubusercontent.com/1125196/77716025-0c049200-7042-11ea-8902-59285a8f1e46.png)

## Logs

```
C:\dev\projects\android-launcher>flutter run -v
[  +22 ms] executing: [C:\dev\flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[  +44 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[        ] 2294d75bfa8d067ba90230c0fc2268f3636d7584
[        ] executing: [C:\dev\flutter/] git fetch https://github.com/flutter/flutter.git --tags
[+2407 ms] Exit code 0 from: git fetch https://github.com/flutter/flutter.git --tags
[   +1 ms] From https://github.com/flutter/flutter
            * branch                  HEAD       -> FETCH_HEAD
[        ] executing: [C:\dev\flutter/] git describe --match v*.*.* --first-parent --long --tags
[  +45 ms] Exit code 0 from: git describe --match v*.*.* --first-parent --long --tags
[        ] v1.15.17-0-g2294d75bfa
[   +4 ms] executing: [C:\dev\flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[  +25 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/beta
[        ] executing: [C:\dev\flutter/] git ls-remote --get-url origin
[  +22 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[  +54 ms] executing: [C:\dev\flutter/] git rev-parse --abbrev-ref HEAD
[  +23 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] beta
[  +26 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +2 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +23 ms] executing: C:\dev\android\sdk\platform-tools\adb.exe devices -l
[  +17 ms] Exit code 0 from: C:\dev\android\sdk\platform-tools\adb.exe devices -l
[        ] List of devices attached
           17005522509652         device product:TC51 model:TC51 device:TC51 transport_id:1
[   +7 ms] C:\dev\android\sdk\platform-tools\adb.exe -s 17005522509652 shell getprop
[ +289 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[   +7 ms] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[   +5 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +74 ms] Found plugin observable_session at C:\dev\flutter\.pub-cache\git\observable-session-303db1f443873157e8fe06013725d62fcfd1f816\
[  +55 ms] Found plugin observable_session at C:\dev\flutter\.pub-cache\git\observable-session-303db1f443873157e8fe06013725d62fcfd1f816\
[  +37 ms] Generating C:\dev\projects\android-launcher\android\app\src\main\java\io\flutter\plugins\GeneratedPluginRegistrant.java
[  +18 ms] ro.hardware = qcom
[  +26 ms] Launching lib\main.dart on TC51 in debug mode...
[   +6 ms] C:\dev\flutter\bin\cache\dart-sdk\bin\dart.exe C:\dev\flutter\bin\cache\artifacts\engine\windows-x64\frontend_server.dart.snapshot --sdk-root C:\dev\flutter\bin\cache\artifacts\engine\common\flutter_patched_sdk/ --incremental --target=flutter -Ddart.developer.causal_async_stacks=true --output-dill
C:\Users\AARONW~1\AppData\Local\Temp\flutter_tool.6586c658-6fd3-11ea-98c3-7085c27b0566\app.dill --packages C:\dev\projects\android-launcher\.packages -Ddart.vm.profile=false -Ddart.vm.product=false --bytecode-options=source-positions,local-var-info,debugger-stops,instance-field-initializers,keep-unreachable-code,avoid-closure-call-instructions
--enable-asserts --track-widget-creation --filesystem-scheme org-dartlang-root
[  +14 ms] executing: C:\dev\android\sdk\platform-tools\adb.exe -s 17005522509652 shell -x logcat -v time -t 1
[  +83 ms] Exit code 0 from: C:\dev\android\sdk\platform-tools\adb.exe -s 17005522509652 shell -x logcat -v time -t 1
[   +2 ms] --------- beginning of main
           03-27 15:33:55.681 I/zygote64( 7411): Successfully killed process cgroup uid 1000 pid 6842 in 0ms
[  +23 ms] executing: C:\dev\android\sdk\platform-tools\adb.exe version
[   +5 ms] executing: C:\dev\android\sdk\platform-tools\adb.exe -s 17005522509652 logcat -v time -T 03-27 15:33:55.681
[  +23 ms] <- compile package:android_launcher/main.dart
[  +52 ms] Android Debug Bridge version 1.0.41
           Version 29.0.6-6198805
           Installed as C:\dev\android\sdk\platform-tools\adb.exe
[   +2 ms] executing: C:\dev\android\sdk\platform-tools\adb.exe start-server
[  +18 ms] Building APK
[  +13 ms] Running Gradle task 'assembleDebug'...
[   +1 ms] gradle.properties already sets `android.enableR8`
[   +2 ms] Using gradle from C:\dev\projects\android-launcher\android\gradlew.bat.
[        ] C:\dev\projects\android-launcher\android\gradlew.bat mode: 33279 rwxrwxrwx.
[   +5 ms] executing: C:\Program Files\Android\Android Studio\jre\bin\java -version
[  +77 ms] Exit code 0 from: C:\Program Files\Android\Android Studio\jre\bin\java -version
[        ] openjdk version "1.8.0_212-release"
           OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)
           OpenJDK 64-Bit Server VM (build 25.212-b04, mixed mode)
[   +1 ms] executing: C:\Program Files\Android Studio\jre\bin\java -version
[  +68 ms] Exit code 0 from: C:\Program Files\Android Studio\jre\bin\java -version
[        ] openjdk version "1.8.0_152-release"
           OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)
           OpenJDK 64-Bit Server VM (build 25.152-b06, mixed mode)
[   +2 ms] executing: [C:\dev\projects\android-launcher\android/] C:\dev\projects\android-launcher\android\gradlew.bat -Pverbose=true -Ptarget-platform=android-arm64 -Ptarget=C:\dev\projects\android-launcher\lib\main.dart -Ptrack-widget-creation=true -Pfilesystem-scheme=org-dartlang-root assembleDebug
[ +993 ms] > Configure project :app
[        ] WARNING: The option 'android.enableR8' is deprecated and should not be used anymore.
[        ] It will be removed in a future version of the Android Gradle plugin, and will no longer allow you to disable R8.
[+2189 ms] > Task :app:compileFlutterBuildDebug
[   +1 ms] [  +16 ms] executing: [C:\dev\flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[        ] [  +45 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[        ] [        ] 2294d75bfa8d067ba90230c0fc2268f3636d7584
[        ] [        ] executing: [C:\dev\flutter/] git fetch https://github.com/flutter/flutter.git --tags
[+1897 ms] [+2397 ms] Exit code 0 from: git fetch https://github.com/flutter/flutter.git --tags
[        ] [        ] From https://github.com/flutter/flutter
[        ]             * branch                  HEAD       -> FETCH_HEAD
[        ] [        ] executing: [C:\dev\flutter/] git describe --match v*.*.* --first-parent --long --tags
[        ] [  +47 ms] Exit code 0 from: git describe --match v*.*.* --first-parent --long --tags
[        ] [        ] v1.15.17-0-g2294d75bfa
[        ] [   +5 ms] executing: [C:\dev\flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[  +97 ms] [  +25 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] [        ] origin/beta
[        ] [        ] executing: [C:\dev\flutter/] git ls-remote --get-url origin
[        ] [  +22 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] [        ] https://github.com/flutter/flutter.git
[        ] [  +54 ms] executing: [C:\dev\flutter/] git rev-parse --abbrev-ref HEAD
[  +98 ms] [  +23 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] [        ] beta
[        ] [  +14 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[        ] [   +2 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[        ] [   +7 ms] Artifact Instance of 'MaterialFonts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'GradleWrapper' is not required, skipping update.
[        ] [        ] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FlutterSdk' is not required, skipping update.
[        ] [        ] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[   +1 ms] [        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[        ] [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FontSubsetArtifacts' is not required, skipping update.
[  +78 ms] [  +60 ms] Initializing file store
[        ] [  +16 ms] Done initializing file store
[+1098 ms] [+1096 ms] Skipping target: kernel_snapshot
[ +100 ms] [ +121 ms] debug_android_application: Starting due to {InvalidatedReason.outputMissing}
[ +100 ms] [ +122 ms] debug_android_application: Complete
[        ] [  +12 ms] Persisting file store
[        ] [   +9 ms] Done persisting file store
[        ] [   +3 ms] build succeeded.
[        ] [  +10 ms] "flutter assemble" took 1,503ms.
[  +96 ms] > Task :app:packLibsflutterBuildDebug UP-TO-DATE
[        ] > Task :app:preBuild UP-TO-DATE
[        ] > Task :app:preDebugBuild UP-TO-DATE
[+1999 ms] > Task :observable_session:compileFlutterBuildDebug
[   +1 ms] [   +9 ms] executing: [C:\dev\flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[   +2 ms] [  +44 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[   +1 ms] [        ] 2294d75bfa8d067ba90230c0fc2268f3636d7584
[   +1 ms] [        ] executing: [C:\dev\flutter/] git fetch https://github.com/flutter/flutter.git --tags
[+1892 ms] [+2458 ms] Exit code 0 from: git fetch https://github.com/flutter/flutter.git --tags
[        ] [        ] From https://github.com/flutter/flutter
[        ]             * branch                  HEAD       -> FETCH_HEAD
[        ] [        ] executing: [C:\dev\flutter/] git describe --match v*.*.* --first-parent --long --tags
[  +98 ms] [  +45 ms] Exit code 0 from: git describe --match v*.*.* --first-parent --long --tags
[        ] [        ] v1.15.17-0-g2294d75bfa
[        ] [   +5 ms] executing: [C:\dev\flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[        ] [  +25 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] [        ] origin/beta
[        ] [        ] executing: [C:\dev\flutter/] git ls-remote --get-url origin
[        ] [  +22 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] [        ] https://github.com/flutter/flutter.git
[  +97 ms] [  +53 ms] executing: [C:\dev\flutter/] git rev-parse --abbrev-ref HEAD
[        ] [  +23 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] [        ] beta
[        ] [  +13 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[        ] [   +2 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[        ] [   +6 ms] Artifact Instance of 'MaterialFonts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'GradleWrapper' is not required, skipping update.
[        ] [        ] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FlutterSdk' is not required, skipping update.
[        ] [        ] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[   +1 ms] [        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[        ] [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FontSubsetArtifacts' is not required, skipping update.
[  +82 ms] [  +59 ms] Initializing file store
[        ] [   +1 ms] Done initializing file store
[        ] [  +14 ms] kernel_snapshot: Starting due to {}
[        ] [  +11 ms] Persisting file store
[        ] [   +3 ms] Done persisting file store
[        ] [   +6 ms] "flutter assemble" took 147ms.
[   +1 ms] [   +1 ms] Target kernel_snapshot failed: FileSystemException: Cannot open file, path = 'C:\dev\flutter\.pub-cache\git\observable-session-303db1f443873157e8fe06013725d62fcfd1f816\.packages' (OS Error: The system cannot find the file specified.
[   +1 ms]            , errno = 2)
[        ] build failed.
[        ] #0      throwToolExit (package:flutter_tools/src/base/common.dart:14:3)
[        ] #1      AssembleCommand.runCommand (package:flutter_tools/src/commands/assemble.dart:193:7)
[        ] #2      _rootRunUnary (dart:async/zone.dart:1134:38)
[        ] #3      _CustomZone.runUnary (dart:async/zone.dart:1031:19)
[        ] #4      _FutureListener.handleValue (dart:async/future_impl.dart:140:18)
[        ] #5      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:682:45)
[        ] #6      Future._propagateToListeners (dart:async/future_impl.dart:711:32)
[        ] #7      Future._completeWithValue (dart:async/future_impl.dart:526:5)
[        ] #8      _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:34:15)
[        ] #9      _completeOnAsyncReturn (dart:async-patch/async_patch.dart:293:13)
[        ] #10     BuildSystem.build (package:flutter_tools/src/build_system/build_system.dart)
[        ] #11     _rootRunUnary (dart:async/zone.dart:1134:38)
[        ] #12     _CustomZone.runUnary (dart:async/zone.dart:1031:19)
[        ] #13     _FutureListener.handleValue (dart:async/future_impl.dart:140:18)
[        ] #14     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:682:45)
[        ] #15     Future._propagateToListeners (dart:async/future_impl.dart:711:32)
[        ] #16     Future._completeWithValue (dart:async/future_impl.dart:526:5)
[        ] #17     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:34:15)
[        ] #18     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:293:13)
[        ] #19     _BuildInstance.invokeTarget (package:flutter_tools/src/build_system/build_system.dart)
[        ] #20     _rootRunUnary (dart:async/zone.dart:1134:38)
[        ] #21     _CustomZone.runUnary (dart:async/zone.dart:1031:19)
[        ] #22     _FutureListener.handleValue (dart:async/future_impl.dart:140:18)
[        ] #23     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:682:45)
[        ] #24     Future._propagateToListeners (dart:async/future_impl.dart:711:32)
[        ] #25     Future._completeWithValue (dart:async/future_impl.dart:526:5)
[        ] #26     Future.wait.<anonymous closure> (dart:async/future.dart:400:22)
[        ] #27     _rootRunUnary (dart:async/zone.dart:1134:38)
[        ] #28     _CustomZone.runUnary (dart:async/zone.dart:1031:19)
[        ] #29     _FutureListener.handleValue (dart:async/future_impl.dart:140:18)
[        ] #30     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:682:45)
[        ] #31     Future._propagateToListeners (dart:async/future_impl.dart:711:32)
[        ] #32     Future._completeWithValue (dart:async/future_impl.dart:526:5)
[        ] #33     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:34:15)
[        ] #34     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:293:13)
[        ] #35     _BuildInstance._invokeInternal (package:flutter_tools/src/build_system/build_system.dart)
[        ] #36     _asyncErrorWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:82:45)
[        ] #37     _rootRunBinary (dart:async/zone.dart:1146:38)
[        ] #38     _CustomZone.runBinary (dart:async/zone.dart:1039:19)
[        ] #39     _FutureListener.handleError (dart:async/future_impl.dart:154:20)
[        ] #40     Future._propagateToListeners.handleError (dart:async/future_impl.dart:694:47)
[        ] #41     Future._propagateToListeners (dart:async/future_impl.dart:715:24)
[        ] #42     Future._completeError (dart:async/future_impl.dart:534:5)
[        ] #43     _AsyncAwaitCompleter.completeError (dart:async-patch/async_patch.dart:40:15)
[        ] #44     KernelSnapshot.build (package:flutter_tools/src/build_system/targets/dart.dart)
[        ] #45     _asyncErrorWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:82:45)
[        ] #46     _rootRunBinary (dart:async/zone.dart:1146:38)
[        ] #47     _CustomZone.runBinary (dart:async/zone.dart:1039:19)
[        ] #48     _FutureListener.handleError (dart:async/future_impl.dart:154:20)
[        ] #49     Future._propagateToListeners.handleError (dart:async/future_impl.dart:694:47)
[        ] #50     Future._propagateToListeners (dart:async/future_impl.dart:715:24)
[        ] #51     Future._completeError (dart:async/future_impl.dart:534:5)
[        ] #52     Future._asyncCompleteError.<anonymous closure> (dart:async/future_impl.dart:582:7)
[        ] #53     _rootRun (dart:async/zone.dart:1126:13)
[        ] #54     _CustomZone.run (dart:async/zone.dart:1023:19)
[        ] #55     _CustomZone.runGuarded (dart:async/zone.dart:925:7)
[        ] #56     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:965:23)
[        ] #57     _microtaskLoop (dart:async/schedule_microtask.dart:43:21)
[        ] #58     _startMicrotaskLoop (dart:async/schedule_microtask.dart:52:5)
[        ] #59     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
[        ] #60     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:405:11)
[        ] #61     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:429:5)
[        ] #62     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:168:12)
[        ] > Task :observable_session:compileFlutterBuildDebug FAILED
[        ] 3 actionable tasks: 2 executed, 1 up-to-date
[        ] FAILURE: Build failed with an exception.
[        ] * Where:
[        ] Script 'C:\dev\flutter\packages\flutter_tools\gradle\flutter.gradle' line: 833
[        ] * What went wrong:
[   +3 ms] Execution failed for task ':observable_session:compileFlutterBuildDebug'.
[   +2 ms] > Process 'command 'C:\dev\flutter\bin\flutter.bat'' finished with non-zero exit value 1
[        ] * Try:
[        ] Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
[        ] * Get more help at https://help.gradle.org
[        ] BUILD FAILED in 10s
[ +381 ms] Running Gradle task 'assembleDebug'... (completed in 11.6s)
[   +3 ms] Exception: Gradle task assembleDebug failed with exit code 1
[   +1 ms] "flutter run" took 12,460ms.

#0      throwToolExit (package:flutter_tools/src/base/common.dart:14:3)
#1      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:568:7)
<asynchronous suspension>
#2      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:711:18)
#3      _rootRunUnary (dart:async/zone.dart:1134:38)
#4      _CustomZone.runUnary (dart:async/zone.dart:1031:19)
#5      _FutureListener.handleValue (dart:async/future_impl.dart:140:18)
#6      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:682:45)
#7      Future._propagateToListeners (dart:async/future_impl.dart:711:32)
#8      Future._completeWithValue (dart:async/future_impl.dart:526:5)
#9      _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:34:15)
#10     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:293:13)
#11     RunCommand.usageValues (package:flutter_tools/src/commands/run.dart)
#12     _rootRunUnary (dart:async/zone.dart:1134:38)
#13     _CustomZone.runUnary (dart:async/zone.dart:1031:19)
#14     _FutureListener.handleValue (dart:async/future_impl.dart:140:18)
#15     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:682:45)
#16     Future._propagateToListeners (dart:async/future_impl.dart:711:32)
#17     Future._completeWithValue (dart:async/future_impl.dart:526:5)
#18     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:34:15)
#19     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:293:13)
#20     AndroidDevice.isLocalEmulator (package:flutter_tools/src/android/android_device.dart)
#21     _rootRunUnary (dart:async/zone.dart:1134:38)
#22     _CustomZone.runUnary (dart:async/zone.dart:1031:19)
#23     _FutureListener.handleValue (dart:async/future_impl.dart:140:18)
#24     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:682:45)
#25     Future._propagateToListeners (dart:async/future_impl.dart:711:32)
#26     Future._completeWithValue (dart:async/future_impl.dart:526:5)
#27     Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:556:7)
#28     _rootRun (dart:async/zone.dart:1126:13)
#29     _CustomZone.run (dart:async/zone.dart:1023:19)
#30     _CustomZone.runGuarded (dart:async/zone.dart:925:7)
#31     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:965:23)
#32     _microtaskLoop (dart:async/schedule_microtask.dart:43:21)
#33     _startMicrotaskLoop (dart:async/schedule_microtask.dart:52:5)
#34     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
#35     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:169:5)
```

```
C:\dev\projects\android-launcher>flutter doctor -v
[√] Flutter (Channel beta, v1.15.17, on Microsoft Windows [Version 10.0.18363.720], locale en-NZ)
    • Flutter version 1.15.17 at C:\dev\flutter
    • Framework revision 2294d75bfa (3 weeks ago), 2020-03-07 00:28:38 +0900
    • Engine revision 5aff311948
    • Dart version 2.8.0 (build 2.8.0-dev.12.0 9983424a3c)


[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at C:\dev\android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 28.0.3
    • ANDROID_HOME = C:\dev\android\sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 3.6)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 44.0.2
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)

[√] Android Studio (version 3.2)
    • Android Studio at C:\Program Files\Android Studio
    • Flutter plugin version 27.1.2
    • Dart plugin version 181.4892.1
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)

[!] IntelliJ IDEA Community Edition (version 2019.3)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2019.2.3
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.dev/intellij-setup/#installing-the-plugins

[√] VS Code (version 1.42.1)
    • VS Code at C:\Users\Aaron Wilson\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.8.1

[√] Connected device (3 available)
    • TC51       • 17005522509652 • android-arm64  • Android 8.1.0 (API 27)
    • Chrome     • chrome         • web-javascript • Google Chrome 80.0.3987.149
    • Web Server • web-server     • web-javascript • Flutter Tools

! Doctor found issues in 1 category.
```

**Comment by jmagman** [comment]
Please re-file with [pub](https://github.com/dart-lang/pub/issues).
