### ISSUE TITLE
Flutter build apk hangs

### ISSUE THREAD

**Issue by r4v3r23** [flutter/flutter#53409]
cant build/run app and flutter doctor shows everything is ok: 
-----------------------------
flutter doctor -v
[✓] Flutter (Channel stable, v1.12.13+hotfix.8, on Linux, locale en_US.UTF-8)
    • Flutter version 1.12.13+hotfix.8 at /home/x0x/Android/flutter
    • Framework revision 0b8abb4724 (6 weeks ago), 2020-02-11 11:44:36 -0800
    • Engine revision e1e6ced81d
    • Dart version 2.7.0

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /home/x0x/Android/Sdk
    • Android NDK location not configured (optional; useful for native profiling
      support)
    • Platform android-29, build-tools 29.0.3
    • Java binary at: /opt/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✓] Android Studio (version 3.6)
    • Android Studio at /opt/android-studio
    • Flutter plugin version 44.0.2
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build
      1.8.0_212-release-1586-b4-5784211)

**Comment by VladyslavBondarenko** [comment]
Hi @r4v3r23 
is it your case https://github.com/flutter/flutter/issues/53341?

**Comment by r4v3r23** [comment]
@vlady

> Hi @r4v3r23
> is it your case #53341?

i changed to master channel and now im getting errors building apk --release, but --debug builds ok

**Comment by VladyslavBondarenko** [comment]
@r4v3r23 
Could you please share your `flutter build apk --release --verbose` log?

**Comment by r4v3r23** [comment]
> @r4v3r23
> Could you please share your `flutter build apk --release --verbose` log?

its huge, heres just the red:

[        ] Warning: there were 460 unresolved references to classes or
interfaces.
[        ]          You may need to add missing library jars or update their
versions.
[        ]          If your code works fine without the missing classes, you can
suppress
[        ]          the warnings with '-dontwarn' options.
[        ] 
(http://proguard.sourceforge.net/manual/troubleshooting.html#unresolvedclass)
[        ] Warning: there were 14 unresolved references to program class
members.
[        ]          Your input classes appear to be inconsistent.
[        ]          You may need to recompile the code.
[        ] 
(http://proguard.sourceforge.net/manual/troubleshooting.html#unresolvedprogramcl
assmember)
[        ] Warning: there were 4 unresolved references to library class members.
[        ]          You probably need to update the library versions.
[        ] 
(http://proguard.sourceforge.net/manual/troubleshooting.html#unresolvedlibrarycl
assmember)
[  +62 ms] FAILURE: Build failed with an exception.
[        ] * What went wrong:
[        ] Execution failed for task ':app:minifyReleaseWithProguard'.
[        ] > java.io.IOException: Please correct the above warnings first.
[        ] * Try:
[        ] Run with --stacktrace option to get the stack trace. Run with --info
or --debug option to get more log output. Run with --scan to get full insights.
[        ] * Get more help at https://help.gradle.org
[        ] BUILD FAILED in 28s
[        ] 44 actionable tasks: 6 executed, 38 up-to-date
[ +342 ms] Running Gradle task 'assembleRelease'... (completed in 28.9s)
[   +4 ms] "flutter apk" took 29,153ms.
Gradle task assembleRelease failed with exit code 1

#0      throwToolExit (package:flutter_tools/src/base/common.dart:14:3)
#1      buildGradleApp (package:flutter_tools/src/android/gradle.dart:452:7)
#2      _rootRunUnary (dart:async/zone.dart:1155:38)
#3      _CustomZone.runUnary (dart:async/zone.dart:1048:19)
#4      _FutureListener.handleValue (dart:async/future_impl.dart:141:18)
#5      Future._propagateToListeners.handleValueCallback
(dart:async/future_impl.dart:682:45)
#6      Future._propagateToListeners (dart:async/future_impl.dart:711:32)
#7      Future._completeWithValue (dart:async/future_impl.dart:526:5)
#8      Future._asyncComplete.<anonymous closure>
(dart:async/future_impl.dart:556:7)
#9      _rootRun (dart:async/zone.dart:1147:13)
#10     _CustomZone.run (dart:async/zone.dart:1040:19)
#11     _CustomZone.runGuarded (dart:async/zone.dart:942:7)
#12     _CustomZone.bindCallbackGuarded.<anonymous closure>
(dart:async/zone.dart:982:23)
#13     _microtaskLoop (dart:async/schedule_microtask.dart:43:21)
#14     _startMicrotaskLoop (dart:async/schedule_microtask.dart:52:5)
#15     _runPendingImmediateCallback
(dart:isolate-patch/isolate_patch.dart:118:13)
#16     _RawReceivePortImpl._handleMessage
(dart:isolate-patch/isolate_patch.dart:169:5)

**Comment by harmispatel** [comment]
What went wrong:                                                      
Execution failed for task ':app:minifyReleaseWithProguard'.             
> java.io.IOException: Please correct the above warnings first.  

I have the same error please help

**Comment by jasonhtpham** [comment]
I have the same error too. I clearly don't have anything with Proguard in my project.

Flutter version: 2.5.1

**Comment by jasonhtpham** [comment]
Hey guys, we solved this problem by setting the this in `gradle.properties`

```
android.enableR8=true
```

And set the flag `--no-shrink` when building the app bundle (as we don't what code shrinker). It works for us. I guess this is because if we set enableR8 to false Flutter will use Proguard by default.

I hope this will help someone in their stress of solving this like us.

**Comment by jeonghoonkim** [comment]
God only this work for me. Thanks

> Hey guys, we solved this problem by setting the this in `gradle.properties`
> 
> ```
> android.enableR8=true
> ```
> 
> And set the flag `--no-shrink` when building the app bundle (as we don't what code shrinker). It works for us. I guess this is because if we set enableR8 to false Flutter will use Proguard by default.
> 
> I hope this will help someone in their stress of solving this like us.
