### ISSUE TITLE
PlatformViews broken on Android 11

### ISSUE THREAD

**Issue by xster** [flutter/flutter#53444]
Run the WebView or Google Maps plugin example

```
E/MethodChannel#flutter/platform_views( 7746): Failed to handle method call
E/MethodChannel#flutter/platform_views( 7746): android.view.WindowManager$InvalidDisplayException: Unable to add window android.view.ViewRootImpl$W@d707d3 -- the specified display can not be found
E/MethodChannel#flutter/platform_views( 7746): 	at android.view.ViewRootImpl.setView(ViewRootImpl.java:1065)
E/MethodChannel#flutter/platform_views( 7746): 	at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:397)
E/MethodChannel#flutter/platform_views( 7746): 	at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:105)
E/MethodChannel#flutter/platform_views( 7746): 	at android.app.Dialog.show(Dialog.java:340)
E/MethodChannel#flutter/platform_views( 7746): 	at android.app.Presentation.show(Presentation.java:252)
E/MethodChannel#flutter/platform_views( 7746): 	at io.flutter.plugin.platform.VirtualDisplayController.<init>(VirtualDisplayController.java:93)
E/MethodChannel#flutter/platform_views( 7746): 	at io.flutter.plugin.platform.VirtualDisplayController.create(VirtualDisplayController.java:46)
E/MethodChannel#flutter/platform_views( 7746): 	at io.flutter.plugin.platform.PlatformViewsController$1.createPlatformView(PlatformViewsController.java:112)
E/MethodChannel#flutter/platform_views( 7746): 	at io.flutter.embedding.engine.systemchannels.PlatformViewsChannel$1.create(PlatformViewsChannel.java:95)
E/MethodChannel#flutter/platform_views( 7746): 	at io.flutter.embedding.engine.systemchannels.PlatformViewsChannel$1.onMethodCall(PlatformViewsChannel.java:59)
E/MethodChannel#flutter/platform_views( 7746): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:226)
E/MethodChannel#flutter/platform_views( 7746): 	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:85)
E/MethodChannel#flutter/platform_views( 7746): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:631)
```

**Comment by xster** [comment]
cc @amirh

**Comment by amirh** [comment]
Seems like `Presentation.show` stopped working on Android 11, minimal pure-Android repro:

```java
package com.example.amirha.accessiblevd;

import android.app.Activity;
import android.app.Presentation;
import android.content.Context;
import android.graphics.SurfaceTexture;
import android.hardware.display.DisplayManager;
import android.hardware.display.VirtualDisplay;
import android.os.Build;
import android.os.Bundle;
import android.util.Log;
import android.view.Display;
import android.view.Gravity;
import android.view.Surface;
import android.view.TextureView;
import android.view.View;
import android.view.Window;
import android.view.WindowManager;
import android.widget.Button;
import android.widget.FrameLayout;

public class MainActivity extends Activity {

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        final TextureView textureView = new TextureView(this);
        setFrameLayoutParams(textureView, Gravity.CENTER);

        // Boilerplate to create a virtual display that renders to the TextureView's texture.
        textureView.setSurfaceTextureListener(new TextureView.SurfaceTextureListener() {
            @Override
            public void onSurfaceTextureAvailable(SurfaceTexture surface, int width, int height) {
                DisplayManager displayManager = (DisplayManager) getSystemService(Context.DISPLAY_SERVICE);
                int densityDpi = getResources().getDisplayMetrics().densityDpi;
                VirtualDisplay virtualDisplay = displayManager.createVirtualDisplay(
                        "vd",
                        width,
                        height,
                        densityDpi,
                        new Surface(surface),
                        0
                );
                SimplePresentation simplePresentation = new SimplePresentation(MainActivity.this, virtualDisplay.getDisplay());
                simplePresentation.show();
            }

            @Override
            public void onSurfaceTextureSizeChanged(SurfaceTexture surface, int width, int height) {

            }

            @Override
            public boolean onSurfaceTextureDestroyed(SurfaceTexture surface) {
                return false;
            }

            @Override
            public void onSurfaceTextureUpdated(SurfaceTexture surface) {

            }
        });

        FrameLayout container = new FrameLayout(this);
        container.setBackgroundColor(0xff00ff00);
        container.addView(textureView);
        setContentView(container);
    }

    private static void setFrameLayoutParams(View view, int gravity) {
        FrameLayout.LayoutParams layoutParams = new FrameLayout.LayoutParams(400, 400);
        layoutParams.gravity = gravity;
        view.setLayoutParams(layoutParams);
    }
}

class SimplePresentation extends Presentation {

    private Button embeddedView;

    public SimplePresentation(
            Context outerContext,
            Display display) {
        super(outerContext, display);
        getWindow().setFlags(
                WindowManager.LayoutParams.FLAG_NOT_FOCUSABLE,
                WindowManager.LayoutParams.FLAG_NOT_FOCUSABLE
        );
    }

    private static void setFullScreen(Window window) {
        window.setFlags(WindowManager.LayoutParams.FLAG_DRAWS_SYSTEM_BAR_BACKGROUNDS, WindowManager.LayoutParams.FLAG_DRAWS_SYSTEM_BAR_BACKGROUNDS);
        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.LOLLIPOP) {
            window.setStatusBarColor(0x00000000);
        }
        window.getDecorView().setSystemUiVisibility(View.SYSTEM_UI_FLAG_LAYOUT_FULLSCREEN);
    }


    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setFullScreen(getWindow());
        embeddedView = new Button(getContext());
        embeddedView.setText("Hello world!");
        embeddedView.setBackgroundColor(0xffff0000);
        embeddedView.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View view) {
                Log.d("AXVD", "clicked on vd button");
            }
        });
        setContentView(embeddedView);
    }
}
```

Crashes with: 

```
2020-03-27 16:47:48.337 9485-9485/com.example.amirha.accessiblevd E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.example.amirha.accessiblevd, PID: 9485
    android.view.WindowManager$InvalidDisplayException: Unable to add window android.view.ViewRootImpl$W@a11948a -- the specified display can not be found
        at android.view.ViewRootImpl.setView(ViewRootImpl.java:1065)
        at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:397)
        at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:105)
        at android.app.Dialog.show(Dialog.java:340)
        at android.app.Presentation.show(Presentation.java:252)
        at com.example.amirha.accessiblevd.MainActivity$1.onSurfaceTextureAvailable(MainActivity.java:45)
```

I'm following up with Android folks

**Comment by amirh** [comment]
@jason-simmons points out that setting the presentation's window type to TYPE_PRIVATE_PRESENTATION fixes this.

**Comment by kf6gpe** [comment]
cc @kf6gpe

**Comment by pradgc** [comment]
apologies jason, I am new to flutter. Where/how should I make the changes? I am using Android Studio.

**Comment by jason-simmons** [comment]
Upgrade to the latest version of the Flutter master branch to get the fix.
