### ISSUE TITLE
[web] Another exception was thrown: Instance of 'minified:bG<void>'

### ISSUE THREAD

**Issue by Fabrice-TEICHTEIL-KOENIGSBUCH** [flutter/flutter#53487]
This issue happens only with release build. It works fine when running in debug mode.

```
[✓] Flutter (Channel beta, v1.15.17, on Mac OS X 10.15.3 19D76, locale en-HK)
    • Flutter version 1.15.17 at /Users/fabriceteichteil/flutter
    • Framework revision 2294d75bfa (3 weeks ago), 2020-03-07 00:28:38 +0900
    • Engine revision 5aff311948
    • Dart version 2.8.0 (build 2.8.0-dev.12.0 9983424a3c)

[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/setup/#android-setup for detailed instructions).
      If the Android SDK has been installed to a custom location, set ANDROID_SDK_ROOT to that location.
      You may also want to add it to your PATH environment variable.


[✓] Xcode - develop for iOS and macOS (Xcode 11.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.2.1, Build version 11B500
    • CocoaPods version 1.8.4

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/setup/#android-setup for detailed instructions).

[✓] VS Code (version 1.43.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.8.1

[✓] Connected device (2 available)
    • Chrome     • chrome     • web-javascript • Google Chrome 80.0.3987.149
    • Web Server • web-server • web-javascript • Flutter Tools

! Doctor found issues in 2 categories.
```

Chrome log for released version:
```
js_primitives.dart:49 Another exception was thrown: Instance of 'minified:bG<void>'
```

Safari log for released version:
```
[Log] Another exception was thrown: Instance of 'minified:bG<void>' (main.dart.js, line 3024, x3)
[Warning] [blocked] The page at https://.../index.html#/ was not allowed to display insecure content from org-dartlang-sdk:///sdk/lib/_internal/js_runtime/lib/js_primitives.dart.

[Error] Not allowed to request resource
[Error] Cannot load org-dartlang-sdk:///sdk/lib/_internal/js_runtime/lib/js_primitives.dart due to access control checks.
```

Profile run log:
```
══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
js_primitives.dart:49 The following _CastError was thrown building Widget:
js_primitives.dart:49 CastError: Instance of 'ProcessFormTemplateImpl': type 'ProcessFormTemplateImpl' is not a subtype of
js_primitives.dart:49 type 'ProcessFileTemplate'
js_primitives.dart:49 
js_primitives.dart:49 Widget creation tracking is currently disabled. Enabling it enables improved error messages. It can
js_primitives.dart:49 be enabled by passing `--track-widget-creation` to `flutter run` or `flutter test`.
js_primitives.dart:49 
js_primitives.dart:49 When the exception was thrown, this was the stack:
js_primitives.dart:49     at Object.wrapException (http://localhost:54292/main.dart.js:3848:17)
js_primitives.dart:49     at Rti._generalAsCheckImplementation [as _as] (http://localhost:54292/main.dart.js:5003:15)
js_primitives.dart:49     at _ProcessLoadedWidgetState_build__closure.call$2 (http://localhost:54292/main.dart.js:138818:38)
js_primitives.dart:49     at BlocBuilder.builder$2 (http://localhost:54292/main.dart.js:117900:27)
js_primitives.dart:49     at _BlocBuilderBaseState.build$1 (http://localhost:54292/main.dart.js:117944:27)
js_primitives.dart:49     at StatefulElement.build$0 (http://localhost:54292/main.dart.js:108277:37)
js_primitives.dart:49     at StatefulElement.performRebuild$0 (http://localhost:54292/main.dart.js:108171:23)
js_primitives.dart:49     at StatefulElement.performRebuild$0 (http://localhost:54292/main.dart.js:108296:13)
js_primitives.dart:49     at StatefulElement.rebuild$0 (http://localhost:54292/main.dart.js:108087:12)
js_primitives.dart:49     at StatefulElement._firstBuild$0 (http://localhost:54292/main.dart.js:108162:12)
js_primitives.dart:49 
js_primitives.dart:49 ════════════════════════════════════════════════════════════════════════════════════════════════════
js_primitives.dart:49 Another exception was thrown: CastError: Instance of 'ProcessFormTemplateImpl': type 'ProcessFormTemplateImpl' is not a subtype of type 'ProcessFileTemplate'
```

Don't understand the error as ProcessFormTemplateImpl is indeed a subtype of type ProcessFileTemplate:
```
abstract class ProcessFormTemplate implements ProcessFileTemplate, DesignableTemplate
class ProcessFormTemplateImpl extends ProcessFileTemplateImpl implements ProcessFormTemplate
```

This problem happens with both beta and dev channels.

**Comment by Fabrice-TEICHTEIL-KOENIGSBUCH** [comment]
After switching to master channel, and running in profile mode, the log is different (and less explicit):
```
diagnostics.dart:2943 Uncaught TypeError: Cannot read property 'properties' of null
    at _FlutterErrorDetailsNode.getProperties$0 (diagnostics.dart:2943)
    at TextTreeRenderer._debugRender$4$parentConfiguration$prefixLineOne$prefixOtherLines (diagnostics.dart:1238)
    at TextTreeRenderer.render$4$parentConfiguration$prefixLineOne$prefixOtherLines (diagnostics.dart:1116)
    at TextTreeRenderer.render$1 (diagnostics.dart:1107)
    at Object.FlutterError_dumpErrorToConsole (assertions.dart:775)
    at StaticClosure.call$1 (assertions.dart:758)
    at WidgetsFlutterBinding._invokeFrameCallback$3 (assertions.dart:903)
    at WidgetsFlutterBinding._invokeFrameCallback$2 (binding.dart:1105)
    at WidgetsFlutterBinding.handleDrawFrame$0 (binding.dart:1052)
    at WidgetsFlutterBinding._handleDrawFrame$0 (binding.dart:968)
```

**Comment by VladyslavBondarenko** [comment]
Hi @Fabrice-TEICHTEIL-KOENIGSBUCH,
does it happen with default flutter app?
can you provide complete minimal code sample/app to reproduce it?

**Comment by Fabrice-TEICHTEIL-KOENIGSBUCH** [comment]
Difficult to build a full sample app to reproduce the issue, it seems that it is something linked with cast within flutter engine.
However, I could identify the source of the crash and how to avoid it.

Consider the 2 types below:
```
abstract class Type1 {}
class Type2 implements Type1 {}
```

And a method that returns a list of Type1 instances:
`List<Type1> getType1List();`

At runtime we know the list is filled with Type2 instances and cast it.
If we cast directly the list, it crashes in profile mode.

Works in both debug and profile modes:
```
final list = getType1List();
final type2 = list[index] as Type2;
```

Works in debug mode:
Crashes in profile mode:
```
final list = getType1List().cast<Type2>();
final type2 = list[index];
```

Hopes this will help.

**Comment by yjbanov** [comment]
This might have been a temporary breakage in diagnostics, which has been rolled back. Can you please upgrade to the latest master revision and try again?

**Comment by ferhatb** [comment]
Fix for stack trace/diagnostics landed in master, you should now see proper stack traces for --profile.

**Comment by vsmenon** [comment]
@sigmundch @rakudrama - any ideas on the cast error in the original message (see profile log)?

I can't seem to repro in a standalone Dart file.

@ferhatb - what are the default opt flags for Flutter Web in profile mode?

**Comment by ferhatb** [comment]
@vsmenon profile mode flags: https://github.com/flutter/flutter/blob/5c69785b1625e1b5c68fc89da358c95fc5320b5d/packages/flutter_tools/lib/src/build_system/targets/web.dart#L186

**Comment by valvoline** [comment]
Hi,

@ferhatb @yjbanov Probably I found a further occurrence of a very similar issue. Hope that this's the right place to notify it. I get the following exception:

```
Exception with thrown value: TypeError: Instance of 'minified:dZ': type 'minified:dZ' is not a subtype of type 'minified:dh'
```

Running the following sample app, that works fine on Chrome Debugging:


```Dart
import 'package:flutter/material.dart';

void main() async {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      home: MainController(),
    );
  }
}

class MainController extends StatefulWidget {
  MainController({Key key}) : super(key: key);

  @override
  _MainControllerState createState() => _MainControllerState();
}

class _MainControllerState extends State<MainController> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('Main title'),
      ),
      body: SingleChildScrollView(
        physics: BouncingScrollPhysics(),
        child: Column(
          children: [
            SizedBox(
              width: MediaQuery.of(context).size.width,
              height: 300,
              child: Column(
                children: [
                  Padding(
                    padding: const EdgeInsets.all(32),
                    child: Expanded(
                      child: Text(
                        'Hello World',
                        textAlign: TextAlign.center,
                      ),
                    ),
                  ),
                ],
              ),
            ),
          ],
        ),
      ),
    );
  }
}
```

As you may notice, the `Column` widget has a child `Padding` with an `Expanded` subchild. Not sure if this is semantically correct or not, since an Expanded widget shouldn't be on that place. However, this is working fine on Chrome debugging without any warning or error. Instead, on the compiled version I got the above exception.

Swappint Expanded with Padding, fix the issue, but it took me over six hours to find the solution.

Probably, this should be either notified at the debugging stage or parsed correctly in the compiled version. Not sure.

Please, find attached below my flutter doctor:

```
valvoline@handir web_test % flutter doctor -v
[✓] Flutter (Channel stable, 2.0.1, on macOS 11.2.2 20D80 darwin-arm, locale en-IT)
    • Flutter version 2.0.1 at /Users/valvoline/Flutter/flutter
    • Framework revision c5a4b4029c (2 days ago), 2021-03-04 09:47:48 -0800
    • Engine revision 40441def69
    • Dart version 2.12.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] VS Code (version 1.52.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.18.1

[✓] Connected device (1 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 88.0.4324.192

• No issues found!
```

**Comment by radikris** [comment]
Any news about it, what is the solution? I have the same issue after deploy to firebase
