### ISSUE TITLE
Grey screen on release

### ISSUE THREAD

**Issue by pedro371** [flutter/flutter#53482]
Hello guys,

I have made an App which works on the simulator and also on my iPhone (connected with a cable) but when I upload the app via Xcode to appstoreconnect and install the app via TestFlight is the screen grey. 

I have made this experience with 2 Flutter apps.
App 1:
![IMG_5025](https://user-images.githubusercontent.com/46385595/77823286-3dd92f80-70fa-11ea-8244-6426f51b9673.PNG)

App 2:

![Bildschirmfoto 2020-03-28 um 13 43 59](https://user-images.githubusercontent.com/46385595/77823294-49c4f180-70fa-11ea-8e07-7c349687d3d7.png)

Flutter doctor -v: 

[✓] Flutter (Channel dev, v1.16.3, on Mac OS X 10.15.3 19D76, locale
    de-DE)
    • Flutter version 1.16.3 at
      /Users/pp/Documents/workspace/flutter
    • Framework revision be3a4b37b3 (2 days ago), 2020-03-26 18:08:05
      -0700
    • Engine revision b2bdeb3f0f
    • Dart version 2.8.0 (build 2.8.0-dev.17.0 1402e8e1a4)

 
[✓] Android toolchain - develop for Android devices (Android SDK version
    28.0.3)
    • Android SDK at /Users/pp/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native
      profiling support)
    • Platform android-29, build-tools 28.0.3
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_152-release-1136-b06)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.3, Build version 11C29
    • CocoaPods version 1.8.4

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google
      Chrome

[✓] Android Studio (version 3.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 31.3.1
    • Dart plugin version 181.5656
    • Java version OpenJDK Runtime Environment (build
      1.8.0_152-release-1136-b06)

[✓] VS Code (version 1.43.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.8.1

 
[✓] Connected device (2 available)            
    • Chrome     • chrome     • web-javascript • Google Chrome
      80.0.3987.149
    • Web Server • web-server • web-javascript • Flutter Tools

• No issues found!

**Comment by iKrupp** [comment]
It looks like you are catching an error right at the start. Have you tried running the release build through the IDE on your physical device?

**Comment by pedro371** [comment]
> It looks like you are catching an error right at the start. Have you tried running the release build through the IDE on your physical device?

I created in Xcode a new Schema with the build configuration release. Now I'm getting this error:

2020-03-29 12:47:02.611007+0200 Runner[537:47758] Metal API Validation Enabled
2020-03-29 12:47:03.302405+0200 Runner[537:47995] flutter:
2020-03-29 12:47:03.302875+0200 Runner[537:47995] flutter: Another exception was thrown: Instance of 'DiagnosticsProperty<void>'

**Comment by MrAlek** [comment]
I started getting the exact same behavior on Android today. Running locally on device is fine but building a signed bundle or apk from Android Studio produces a grey screen on launch.

What's even weirder is that all my bundles were working until noon today when suddenly all newly generated bundles got this on startup. Tried both on `v1.12.13+hotfix.8` and `hotfix.9` and have zero code changes. This leads me to believe it's an IDE issue but I haven't been able to pinpoint it.

**Comment by jeroen-meijer** [comment]
Anyone who also experiences this (like me), don't forget to add a +1 (👍) on the top comment.

**Comment by lukepighetti** [comment]
You know the red error screen that you get when developing? When you build in release mode flutter replaces that with a gray screen.

**Comment by jeroen-meijer** [comment]
Thank you @lukepighetti.
As others pointed out to me, the grey screen others and I have observed indicates an error that happened in release mode. I was able to track it down and fix it.

**Comment by jawad12345A** [comment]
I am also facing this .Any solution

**Comment by HarryPratlett** [comment]
I'm getting this problem, but only when the code is run externally on a webpage of mine. When the release build is run locally, no issue occurs. However, when run on the website, grey screens are produced for parts of the application. How would I go about identifying the issues, since I am not getting any console issues in the chrome developer tools?

**Comment by pgfeng** [comment]
I have the same problem, It happens when I try to generate a release.

flutter run --release

I/flutter (17345): Another exception was thrown: Instance of 'DiagnosticsProperty<void>'
I/flutter (17345): Another exception was thrown: Instance of 'DiagnosticsProperty<void>'
I/flutter (17345): Another exception was thrown: Instance of 'DiagnosticsProperty<void>'
I/flutter (17345): Another exception was thrown: Instance of 'DiagnosticsProperty<void>'
I/flutter (17345): Another exception was thrown: Instance of 'DiagnosticsProperty<void>'
I/flutter (17345): Another exception was thrown: Instance of 'DiagnosticsProperty<void>'
I/flutter (17345): Another exception was thrown: Instance of 'DiagnosticsProperty<void>'

**Comment by pgfeng** [comment]
> I have the same problem, It happens when I try to generate a release.
> 
> flutter run --release
> 
> I/flutter (17345): Another exception was thrown: Instance of 'DiagnosticsProperty'
> I/flutter (17345): Another exception was thrown: Instance of 'DiagnosticsProperty'
> I/flutter (17345): Another exception was thrown: Instance of 'DiagnosticsProperty'
> I/flutter (17345): Another exception was thrown: Instance of 'DiagnosticsProperty'
> I/flutter (17345): Another exception was thrown: Instance of 'DiagnosticsProperty'
> I/flutter (17345): Another exception was thrown: Instance of 'DiagnosticsProperty'
> I/flutter (17345): Another exception was thrown: Instance of 'DiagnosticsProperty'



> You know the red error screen that you get when developing? When you build in release mode flutter replaces that with a gray screen.

I went back to debug mode once and found the red error message, thank you.

**Comment by Tokenyet** [comment]
I've come across this issue, but this depends on the code. For me, with [CacheNetworkImage](https://github.com/Baseflow/flutter_cached_network_image) [issue#404](https://github.com/Baseflow/flutter_cached_network_image/issues/404), I passed wrong `imageUrl` or null, that cause the grey screen. UI is working without grey screen even If I didn't handle properly, but after upgrading to 1.17.1, everything need to be more careful 😕 .

**Comment by chinmaygarde** [comment]
Triage: This looks like an uncaught Dart exception and not an engine crash. cc @Hixie for thoughts on better surfacing these errors.

**Comment by Hixie** [comment]
Yeah, this is working as intended. Not sure exactly what we can do to make it better. When we had it show an error message, people complained that we were showing error messages to their users...

**Comment by jeroen-meijer** [comment]
I completely understand. I can't think of anything better either.

Perhaps adding something to the FAQ or official docs explaining the grey parts will make people realize the fact they have an issue in their app sooner.

**Comment by Hixie** [comment]
Yeah, we should make this clearer in our docs for sure.

**Comment by lukepighetti** [comment]
Allow us to register a default error widget that the framework uses in release?

**Comment by Hixie** [comment]
That exists: https://master-api.flutter.dev/flutter/widgets/ErrorWidget/builder.html

**Comment by lukepighetti** [comment]
It looks like you can override it like this?

```dart
ErrorWidget.builder = ((e) {
  return Center(
    child: Text("There was an error!"),
  );
});
```

**Comment by rrousselGit** [comment]
I faced this issue when building on Flutter web

What's surprising is: When reading the dev console, there are no errors.
I would expect the default behavior on web to do a console.error

**Comment by sfshaza2** [comment]
This issue looks like it can be moved to the website repo. Yes, @Hixie?

**Comment by jeroen-meijer** [comment]
I disagree @sfshaza2.
This issue affects all apps built with Flutter, regardless of the platform.

I believe the docs should be clearer about the reason and situations in which a grey screen may appear. I think it'd be great if the docs mention that the `ErrorWidget` can be replaced (as pointed out by @lukepighetti) 👍

**Comment by jeffmayn** [comment]
How come the app greys out instead of just stopping the application? - this forces users to manually close the app and reopen it. Isn't there a way to make the app close or restart on a flutter crash?

**Comment by lukepighetti** [comment]
It's not a crash, it's an error.

**Comment by Hixie** [comment]
@jeffmayn You can hook into the FlutterError logic to make the application crash if you like.

**Comment by Hixie** [comment]
@jeroen-meijer Can you elaborate on where you would like to see the documentation updated and what it should say?

**Comment by jeroen-meijer** [comment]
@Hixie I'm not sure where in the docs I would put that. Perhaps there's already an FAQ section, in which case this would fit well. Otherwise, https://flutter.dev/docs/testing/errors might be a good option.

I think that, as long as it's easy to find in the docs or on Google, it's good (since this error doesn't happen that often).

As for what it should say, I think the following points should be mentioned/discussed.
- What the grey screen means.
- Why it's grey in release.
- What to do to fix it (i.e., reproduce the error in debug and check the logs).
- Mention the fact that the error widget can be overridden.
- Include a screenshot.

I'd love to hear other people's thoughts on this ^

**Comment by mshamsi502** [comment]
first, you check AndroidManifest.xml
(AndroidManifest.xml file for debug mode is different from AndroidManifest.xml file for release mode.
check directory:

`    android\app\src\debug\AndroidManifest.xml`

and directory: 

`    android\app\src\main\AndroidManifest.xml`

even you can create for release:

`    android\app\src\release\AndroidManifest.xml`

try with add

`    <uses-permission android:name="android.permission.INTERNET" />`

to your target AndroidManifest.xml).

red screen in debug mode it's like grey screen in release mod
that means you have an error code but for debug mode maybe this error be like warning and could run and you don't see any problem in your app in debug mode!
but for release mode, you should fix it!
like the case for me:
I'm trying put Position Widget in Container Widget and I get this error :
```
    Another exception was thrown: Instance of ‘DiagnosticsProperty’
    Incorrect use of ParentDataWidget.
```
i fix it by change Container to Stack.

**Comment by nanox77** [comment]
I have same problem. In debug mode app is working fine but in release mode appears grey full screen on real Android device. Any idea?. There is no DiagnosticsProperty problem in logcat.

I have no way for show error.

```
[✓] Flutter (Channel stable, 1.20.3, on Mac OS X 10.15.6 19G2021, locale en-AR)
    • Flutter version 1.20.3 at /Users/marianocastellano/Documents/Flutter/flutter
    • Framework revision 216dee60c0 (13 days ago), 2020-09-01 12:24:47 -0700
    • Engine revision d1bc06f032
    • Dart version 2.9.2


[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/marianocastellano/Library/Android/sdk
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.7)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.7, Build version 11E801a
    • CocoaPods version 1.9.1

[✓] Android Studio (version 3.4)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 35.3.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

[✓] IntelliJ IDEA Community Edition (version 2019.3.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 42.1.4
    • Dart plugin version 193.5731

[✓] VS Code (version 1.49.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.14.1

[✓] Connected device (2 available)
    • Mi 9T (mobile)                     • 7d11ec14      • android-arm64 • Android 10 (API 29)
    • Android SDK built for x86 (mobile) • emulator-5554 • android-x86   • Android 9 (API 28) (emulator)

• No issues found!
```

**Comment by YazeedAlKhalaf** [comment]
It also happens with me
I am running the dev channel to run my app on Windows.
GitHub Repo: https://github.com/YazeedAlKhalaf/Flutter_Installer

No error or stack trace is shown, weird 🙃

I get this.
```
flutter: 
flutter: Another exception was thrown: Instance of 'DiagnosticsProperty<void>'
flutter: Another exception was thrown: Instance of 'DiagnosticsProperty<void>'
flutter: Another exception was thrown: Instance of 'DiagnosticsProperty<void>'
flutter: Another exception was thrown: Instance of 'DiagnosticsProperty<void>'
flutter: Another exception was thrown: Instance of 'DiagnosticsProperty<void>'
flutter: Another exception was thrown: Instance of 'DiagnosticsProperty<void>'
flutter: Another exception was thrown: Instance of 'DiagnosticsProperty<void>'
flutter: Another exception was thrown: Instance of 'DiagnosticsProperty<void>'
flutter: Another exception was thrown: Instance of 'DiagnosticsProperty<void>'
flutter: Another exception was thrown: Instance of 'DiagnosticsProperty<void>'
flutter: Another exception was thrown: Instance of 'DiagnosticsProperty<void>'
flutter: Another exception was thrown: Instance of 'DiagnosticsProperty<void>'
flutter: Another exception was thrown: Instance of 'DiagnosticsProperty<void>'
flutter: Another exception was thrown: Instance of 'DiagnosticsProperty<void>'
flutter: Another exception was thrown: Instance of 'DiagnosticsProperty<void>'
flutter: Another exception was thrown: Instance of 'DiagnosticsProperty<void>'
flutter: Another exception was thrown: Instance of 'DiagnosticsProperty<void>'
flutter: Another exception was thrown: Instance of 'DiagnosticsProperty<void>'
flutter: Another exception was thrown: Instance of 'DiagnosticsProperty<void>'
flutter: Another exception was thrown: Instance of 'DiagnosticsProperty<void>'
flutter: Another exception was thrown: Instance of 'DiagnosticsProperty<void>'
flutter: Another exception was thrown: Instance of 'DiagnosticsProperty<void>'
flutter: Another exception was thrown: Instance of 'DiagnosticsProperty<void>'
flutter: Another exception was thrown: Instance of 'DiagnosticsProperty<void>'
flutter: Another exception was thrown: Instance of 'DiagnosticsProperty<void>'
flutter: Another exception was thrown: Instance of 'DiagnosticsProperty<void>'
flutter: Another exception was thrown: Instance of 'DiagnosticsProperty<void>'
flutter: Another exception was thrown: Instance of 'DiagnosticsProperty<void>'
flutter: Another exception was thrown: Instance of 'DiagnosticsProperty<void>'
flutter: Another exception was thrown: Instance of 'DiagnosticsProperty<void>'
flutter: Another exception was thrown: Instance of 'DiagnosticsProperty<void>'
flutter: Another exception was thrown: Instance of 'DiagnosticsProperty<void>'
flutter: Another exception was thrown: Instance of 'DiagnosticsProperty<void>'
flutter: Another exception was thrown: Instance of 'DiagnosticsProperty<void>'
flutter: Another exception was thrown: Instance of 'DiagnosticsProperty<void>'
flutter: Another exception was thrown: Instance of 'DiagnosticsProperty<void>'
flutter: Another exception was thrown: Instance of 'DiagnosticsProperty<void>'
flutter: Another exception was thrown: Instance of 'DiagnosticsProperty<void>'
flutter: Another exception was thrown: Instance of 'DiagnosticsProperty<void>'
flutter: Another exception was thrown: Instance of 'DiagnosticsProperty<void>'
```

**Comment by netgfx** [comment]
Same here debug shows no errors at all. On release I get grey screen.

I use Flutter 1.22.0.12.1-pre and latest Dart

I do `flutter build` and then move on to Archive and upload to app-store.

Is there a way to debug on release? Simulator doesn't support `flutter run --release` and I don't have physical access to the macOS so I can debug on a real device through USB.

**Comment by pedromassangocode** [comment]
> @Hixie I'm not sure where in the docs I would put that. Perhaps there's already an FAQ section, in which case this would fit well. Otherwise, https://flutter.dev/docs/testing/errors might be a good option.
> 
> I think that, as long as it's easy to find in the docs or on Google, it's good (since this error doesn't happen that often).
> 
> As for what it should say, I think the following points should be mentioned/discussed.
> 
> * What the grey screen means.
> * Why it's grey in release.
> * What to do to fix it (i.e., reproduce the error in debug and check the logs).
> * Mention the fact that the error widget can be overridden.
> * Include a screenshot.
> 
> I'd love to hear other people's thoughts on this ^

I don't think that this is something to have in tests section. 

My suggestion is to have it in the FAQs section
https://flutter.dev/docs/resources/faq

**Comment by khloudalmasri** [comment]
you may use expanded inside Stack

**Comment by Tarumoy** [comment]
I have the same problem, It happens when I try to generate a release.

flutter run --release

Flutter run key commands.
h Repeat this help message.
c Clear the screen
q Quit (terminate the application on the device).
I/flutter (24661):
I/flutter (24661): completed
E/FlutterFcmService(24661): Fatal: failed to find callback

where is the actual problem i am unable to find, In debug mode it's working fine even not showing any error. How can i find it?

**Comment by lukaszSieczkowski** [comment]
Hi all,
I had the gray square problem in my app. The solution was to remove from Text child widget  **textAlign: TextAlign.justify,**
Text widget may be a reason of problem.

**Comment by hntan** [comment]
I had the same gray problem when running app in release mode.

**Comment by mshanak** [comment]
@lukaszSieczkowski your answer helped me, I removed `textAlign: TextAlign.center,` then the app accepted by the Apple store.
Another thing I did, I was missing a description of location usage in the `info.plist`.

**Comment by jagadish-pattanaik** [comment]
I am also getting the same grey screen on start just after the splash screen...is the error at the start of it can be anywhere in the app?

**Comment by hntan** [comment]
After adding the ErrorWidget, I found the issue now, that's because of the missing **await** before `Firebase.initializeApp()`

```
void main() async {
   WidgetsFlutterBinding.ensureInitialized();
   **await** Firebase.initializeApp();
   runApp(MyApp());
}
```

**Comment by jagadish-pattanaik** [comment]
@hntan I am also using `Firebase.initializeApp()`; and getting the following error, I think it's because of that only. And that is only in release mode. Does adding await solve the following error?

I found it in log cat what was the error:- 

`ConnectionTracker: Exception thrown while unbinding java.lang.IllegalArgumentException: Service not registered: com.google.android.gms.measurement.internal.zzjp@6b0fcf at android.app.LoadedApk.forgetServiceDispatcher(LoadedApk.java:1757) at android.app.ContextImpl.unbindService(ContextImpl.java:1874) at android.content.ContextWrapper.unbindService(ContextWrapper.java:792) at com.google.android.gms.common.stats.ConnectionTracker.zza(com.google.android.gms:play-services-basement@@17.3.0:55) at com.google.android.gms.common.stats.ConnectionTracker.unbindService(com.google.android.gms:play-services-basement@@17.3.0:50) at com.google.android.gms.measurement.internal.zziv.zzag(com.google.android.gms:play-services-measurement-impl@@17.5.0:245) at com.google.android.gms.measurement.internal.zziv.zzal(com.google.android.gms:play-services-measurement-impl@@17.5.0:262) at com.google.android.gms.measurement.internal.zziv.zzc(com.google.android.gms:play-services-measurement-impl@@17.5.0:336) at com.google.android.gms.measurement.internal.zziu.zza(com.google.android.gms:play-services-measurement-impl@@17.5.0:2) at com.google.android.gms.measurement.internal.zzai.run(com.google.android.gms:play-services-measurement-impl@@17.5.0:7) at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:462) at java.util.concurrent.FutureTask.run(FutureTask.java:266) at com.google.android.gms.measurement.internal.zzfy.run(com.google.android.gms:play-services-measurement-impl@@17.5.0:21)`

How to solve this?

**Comment by hntan** [comment]
> @hntan I am also using `Firebase.initializeApp()`; and getting the following error, I think it's because of that only. And that is only in release mode. Does adding await solve the following error?
> 
> I found it in log cat what was the error:-
> 
> `ConnectionTracker: Exception thrown while unbinding java.lang.IllegalArgumentException: Service not registered: com.google.android.gms.measurement.internal.zzjp@6b0fcf at android.app.LoadedApk.forgetServiceDispatcher(LoadedApk.java:1757) at android.app.ContextImpl.unbindService(ContextImpl.java:1874) at android.content.ContextWrapper.unbindService(ContextWrapper.java:792) at com.google.android.gms.common.stats.ConnectionTracker.zza(com.google.android.gms:play-services-basement@@17.3.0:55) at com.google.android.gms.common.stats.ConnectionTracker.unbindService(com.google.android.gms:play-services-basement@@17.3.0:50) at com.google.android.gms.measurement.internal.zziv.zzag(com.google.android.gms:play-services-measurement-impl@@17.5.0:245) at com.google.android.gms.measurement.internal.zziv.zzal(com.google.android.gms:play-services-measurement-impl@@17.5.0:262) at com.google.android.gms.measurement.internal.zziv.zzc(com.google.android.gms:play-services-measurement-impl@@17.5.0:336) at com.google.android.gms.measurement.internal.zziu.zza(com.google.android.gms:play-services-measurement-impl@@17.5.0:2) at com.google.android.gms.measurement.internal.zzai.run(com.google.android.gms:play-services-measurement-impl@@17.5.0:7) at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:462) at java.util.concurrent.FutureTask.run(FutureTask.java:266) at com.google.android.gms.measurement.internal.zzfy.run(com.google.android.gms:play-services-measurement-impl@@17.5.0:21)`
> 
> How to solve this?

@jagadish-pattanaik Yes I think, so either adding the `await` before `Firebase.initializeApp();` or put it into the FutureBuilder widget. You can also see more detail here https://stackoverflow.com/questions/63492211/no-firebase-app-default-has-been-created-call-firebase-initializeapp-in/63492262#63492262

**Comment by jagadish-pattanaik** [comment]
> With the help of ErrorWidget, now I can see the error message on the screen (`No Firebase App '[DEFAULT]' has been created`). That's because of the missing **await** before `Firebase.initializeApp()`
> 
> ```
> void main() async {
>    WidgetsFlutterBinding.ensureInitialized();
>    await Firebase.initializeApp(); // <--- need to add the await before
>    runApp(MyApp());
> }
> ```

Thanks broo....it worked for me....you saved me man...I was trying from 5 days

**Comment by srihariash999** [comment]
> > @hntan I am also using `Firebase.initializeApp()`; and getting the following error, I think it's because of that only. And that is only in release mode. Does adding await solve the following error?
> > I found it in log cat what was the error:-
> > `ConnectionTracker: Exception thrown while unbinding java.lang.IllegalArgumentException: Service not registered: com.google.android.gms.measurement.internal.zzjp@6b0fcf at android.app.LoadedApk.forgetServiceDispatcher(LoadedApk.java:1757) at android.app.ContextImpl.unbindService(ContextImpl.java:1874) at android.content.ContextWrapper.unbindService(ContextWrapper.java:792) at com.google.android.gms.common.stats.ConnectionTracker.zza(com.google.android.gms:play-services-basement@@17.3.0:55) at com.google.android.gms.common.stats.ConnectionTracker.unbindService(com.google.android.gms:play-services-basement@@17.3.0:50) at com.google.android.gms.measurement.internal.zziv.zzag(com.google.android.gms:play-services-measurement-impl@@17.5.0:245) at com.google.android.gms.measurement.internal.zziv.zzal(com.google.android.gms:play-services-measurement-impl@@17.5.0:262) at com.google.android.gms.measurement.internal.zziv.zzc(com.google.android.gms:play-services-measurement-impl@@17.5.0:336) at com.google.android.gms.measurement.internal.zziu.zza(com.google.android.gms:play-services-measurement-impl@@17.5.0:2) at com.google.android.gms.measurement.internal.zzai.run(com.google.android.gms:play-services-measurement-impl@@17.5.0:7) at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:462) at java.util.concurrent.FutureTask.run(FutureTask.java:266) at com.google.android.gms.measurement.internal.zzfy.run(com.google.android.gms:play-services-measurement-impl@@17.5.0:21)`
> > How to solve this?
> 
> @jagadish-pattanaik Yes I think, so either adding the `await` before `Firebase.initializeApp()` or put it into the FutureBuilder widget. You can also see more detail here https://stackoverflow.com/questions/63492211/no-firebase-app-default-has-been-created-call-firebase-initializeapp-in/63492262#63492262



Thank you very much, I couldn't catch this error with the error widget or otherwise. Saved the day !

**Comment by anuj9665** [comment]
I Just replaced the removed Expanded widget and it solved my problem. There might be some widget causing the problem.

**Comment by AhmedKhattab95** [comment]
it;s also happen when user deny storage/location permission in android from device settings
