### ISSUE TITLE
ProcessException: The application's Info.plist does not contain CFBundleVersion.

### ISSUE THREAD

**Issue by illectronic1** [flutter/flutter#53539]
## Steps to Reproduce

Install fb sdk
1. Run `flutter run`.

# Uncomment this line to define a global platform for your project
platform :ios, '8.0'
pod 'FBSDKCoreKit', '4.39.1'
pod 'FBSDKLoginKit', '4.39.1'

Launching lib/main.dart on iPhone 11 in debug mode...

Running pod install...                                              3.8s
Running Xcode build...

 ├─Assembling Flutter resources...                          13.7s
 └─Compiling, linking and signing...                        12.3s
Xcode build done.                                           34.6s

Sending crash report to Google.
Crash report sent (report ID: 1df92e33079a926b)
Oops; flutter has exited unexpectedly.

Crash report written to /Users/illectronic/work/1/flutter_02.log;
please let us know at https://github.com/flutter/flutter/issues.

Flutter crash report; please file at https://github.com/flutter/flutter/issues.

## command

flutter run

## exception

ProcessException: ProcessException: Process exited abnormally:
An error was encountered processing the command (domain=NSPOSIXErrorDomain, code=22):
Failed to install the requested application
The application's Info.plist does not contain CFBundleVersion.
Ensure your bundle contains a CFBundleVersion.
  Command: /usr/bin/xcrun simctl install 7BEB23EE-28FB-47A6-8E61-C66FC24A9B17 /Users/illectronic/work/1/build/ios/iphonesimulator/Runner.app

```
#0      RunResult.throwException (package:flutter_tools/src/base/process.dart:141:5)
#1      _DefaultProcessUtils.run (package:flutter_tools/src/base/process.dart:275:19)
<asynchronous suspension>
#2      SimControl.install (package:flutter_tools/src/ios/simulators.dart:148:29)
#3      IOSSimulator._setupUpdatedApplicationBundle (package:flutter_tools/src/ios/simulators.dart:454:31)
<asynchronous suspension>
#4      IOSSimulator.startApp (package:flutter_tools/src/ios/simulators.dart:354:15)
#5      FlutterDevice.runHot (package:flutter_tools/src/resident_runner.dart:450:54)
#6      _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:73:64)
#7      _rootRunUnary (dart:async/zone.dart:1134:38)
#8      _CustomZone.runUnary (dart:async/zone.dart:1031:19)
#9      _FutureListener.handleValue (dart:async/future_impl.dart:139:18)
#10     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:680:45)
#11     Future._propagateToListeners (dart:async/future_impl.dart:709:32)
#12     Future._completeWithValue (dart:async/future_impl.dart:524:5)
#13     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:32:15)
#14     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:290:13)
#15     ApplicationPackageFactory.getPackageForPlatform (package:flutter_tools/src/application_package.dart)
#16     _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:73:64)
#17     _rootRunUnary (dart:async/zone.dart:1134:38)
#18     _CustomZone.runUnary (dart:async/zone.dart:1031:19)
#19     _FutureListener.handleValue (dart:async/future_impl.dart:139:18)
#20     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:680:45)
#21     Future._propagateToListeners (dart:async/future_impl.dart:709:32)
#22     Future._completeWithValue (dart:async/future_impl.dart:524:5)
#23     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:32:15)
#24     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:290:13)
#25     BuildableIOSApp.fromProject (package:flutter_tools/src/application_package.dart)
#26     _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:73:64)
#27     _rootRunUnary (dart:async/zone.dart:1134:38)
#28     _CustomZone.runUnary (dart:async/zone.dart:1031:19)
#29     _FutureListener.handleValue (dart:async/future_impl.dart:139:18)
#30     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:680:45)
#31     Future._propagateToListeners (dart:async/future_impl.dart:709:32)
#32     Future._completeWithValue (dart:async/future_impl.dart:524:5)
#33     Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:554:7)
#34     _rootRun (dart:async/zone.dart:1126:13)
#35     _CustomZone.run (dart:async/zone.dart:1023:19)
#36     _CustomZone.runGuarded (dart:async/zone.dart:925:7)
#37     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:965:23)
#38     _microtaskLoop (dart:async/schedule_microtask.dart:43:21)
#39     _startMicrotaskLoop (dart:async/schedule_microtask.dart:52:5)
#40     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
#41     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:175:5)
```

## flutter doctor

```
[32m[✓][39m Flutter (Channel stable, v1.12.13+hotfix.8, on Mac OS X 10.14.6 18G3020,
    locale en-US)
    [32m•[39m Flutter version 1.12.13+hotfix.8 at /users/illectronic/work/flutter
    [32m•[39m Framework revision 0b8abb4724 (7 weeks ago), 2020-02-11 11:44:36 -0800
    [32m•[39m Engine revision e1e6ced81d
    [32m•[39m Dart version 2.7.0

[32m[✓][39m Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    [32m•[39m Android SDK at /Users/illectronic/Library/Android/sdk
    [32m•[39m Android NDK location not configured (optional; useful for native profiling
      support)
    [32m•[39m Platform android-29, build-tools 29.0.2
    [32m•[39m Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    [32m•[39m Java version OpenJDK Runtime Environment (build
      1.8.0_152-release-1343-b01)
    [32m•[39m All Android licenses accepted.

[32m[✓][39m Xcode - develop for iOS and macOS (Xcode 11.3.1)
    [32m•[39m Xcode at /Applications/Xcode.app/Contents/Developer
    [32m•[39m Xcode 11.3.1, Build version 11C505
    [32m•[39m CocoaPods version 1.9.1

[32m[✓][39m Android Studio (version 3.4)
    [32m•[39m Android Studio at /Applications/Android Studio.app/Contents
    [32m•[39m Flutter plugin version 38.2.1
    [32m•[39m Dart plugin version 183.6270
    [32m•[39m Java version OpenJDK Runtime Environment (build
      1.8.0_152-release-1343-b01)

[32m[✓][39m VS Code (version 1.41.1)
    [32m•[39m VS Code at /Applications/Visual Studio Code.app/Contents
    [32m•[39m Flutter extension version 3.4.1

[32m[✓][39m Connected device (1 available)
    [32m•[39m iPhone 11 • 7BEB23EE-28FB-47A6-8E61-C66FC24A9B17 • ios •
      com.apple.CoreSimulator.SimRuntime.iOS-13-3 (simulator)

[32m•[39m No issues found!
```

**Comment by illectronic1** [comment]
Has anyone seen this before?

**Comment by godrifle** [comment]
I have this issue too. If I manually add Build and Version numbers in Runner via Xcode, "flutter run" will build and install fine. BUT, if I increment the version: value from "1.0.0+1" to "1.0.0+2" in pubspec.yaml, run "flutter clean" and then "flutter run" it will function as expected, with the exception that Xcode Runner target isn't updated with the new build number.

**Comment by illectronic1** [comment]
> I have this issue too. If I manually add Build and Version numbers in Runner via Xcode, "flutter run" will build and install fine. BUT, if I increment the version: value from "1.0.0+1" to "1.0.0+2" in pubspec.yaml, run "flutter clean" and then "flutter run" it will function as expected, with the exception that Xcode Runner target isn't updated with the new build number.

Thank you, specifying a version and build number fixed the issue

**Comment by ben-xD** [comment]
I wanted to suggest a fix that worked for me, from [stackoverflow](https://stackoverflow.com/questions/43111501/the-bundles-info-plist-does-not-contain-a-cfbundleversion-key-or-its-value-is-n).

By simply setting the build and version numbers through XCode, my Info.plist file was changed by more than just 1 line. Environment variables were renamed, extra key: array pairs were added. And now it builds and runs on the iOS simulator.
