### ISSUE TITLE
[xiaomi] webview_flutter example crash when playing video and changing orientation

### ISSUE THREAD

**Issue by lhcdims** [flutter/flutter#53555]
Expected Result: Video paused when the orientation of the phone changes.
Actual Result: App crashed.

Steps to reproduce:

1. clone the webview_flutter example from: (webview_flutter version is 0.3.19+9 as @2020/3/30)
https://github.com/flutter/plugins/tree/master/packages/webview_flutter/example

2. In the main.dart, change the initial url to:
https://m.youtube.com

3. run the example in mi 9 (Android version 9.0, MIUI stable version: 10.2.35.0 (PFACNXM)), and play any video in youtube.

4. now, change the orientation of the phone, the app crashes immediately.

Please note that the app does not crash using other android device such as Redmi Note 7 (Android version: 9.0, MIUI stable version: 10.2.5.0 (PFGCNXM))

Flutter Doctor:
```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel beta, v1.15.17, on Linux, locale zh_CN.UTF-8)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
[✓] Android Studio (version 3.6)
[✓] VS Code (version 1.43.2)
[✓] Connected device (1 available)

• No issues found!
```

Log messages BEFORE changing the orientation:

```
Launching lib/main.dart on MI 9 in debug mode...
Running Gradle task 'assembleDebug'...
✓ Built build/app/outputs/apk/debug/app-debug.apk.
I/flutter (19899): Page started loading: https://m.youtube.com/
I/flutter (19899): Page finished loading: https://m.youtube.com/
Debug service listening on ws://127.0.0.1:8941/BbxasSqBctg=/ws
Syncing files to device MI 9...
W/ContentCatcher(19899): Failed to notify a WebView
I/Adreno  (19899): DequeueBuffer: dequeueBuffer failed
W/ContentCatcher(19899): Failed to notify a WebView
I/Adreno  (19899): DequeueBuffer: dequeueBuffer failed
I/Adreno  (19899): DequeueBuffer: dequeueBuffer failed
W/OpenGLRenderer(19899): swapBuffers encountered EGL error 12301 on 0x7999248300, halting rendering...
D/        (19899): PlayerBase::PlayerBase()
D/        (19899): TrackPlayerBase::TrackPlayerBase()
I/libOpenSLES(19899): Emulating old channel mask behavior (ignoring positional mask 0x3, using default mask 0x3 based on channel count of 2)
D/AudioTrack(19899): set(sessionID=12697)
D/AudioTrack(19899): set(): streamType 3, sampleRate 48000, format 0x5, channelMask 0x3, frameCount 0, flags #8, notificationFrames 0, sessionId 12697, transferType 0, uid -1, pid -1
I/cr_MediaCodecBridge(19899): create MediaCodec video decoder, mime video/x-vnd.on2.vp9
I/OMXClient(19899): IOmx service obtained
I/MediaCodec(19899): MediaCodec will operate in async mode
D/SurfaceUtils(19899): connecting to surface 0x7998ff1010, reason connectToSurface
I/MediaCodec(19899): [OMX.qcom.video.decoder.vp9] setting surface generation to 20376577
D/SurfaceUtils(19899): disconnecting from surface 0x7998ff1010, reason connectToSurface(reconnect)
D/SurfaceUtils(19899): connecting to surface 0x7998ff1010, reason connectToSurface(reconnect)
I/ExtendedACodec(19899): setupVideoDecoder()
I/ExtendedACodec(19899): Decoder will be in frame by frame mode
D/SurfaceUtils(19899): set up nativeWindow 0x7998ff1010 for 640x360, color 0x7fa30c06, rotation 0, usage 0x20002900
I/gaibot.test000(19899): ProcessProfilingInfo new_methods=39 is saved saved_to_disk=1 resolve_classes_delay=8000
W/AudioManager(19899): Use of stream types is deprecated for operations other than volume control
W/AudioManager(19899): See the documentation of requestAudioFocus() for what to use instead with android.media.AudioAttributes to qualify your playback use case
D/NdkImageReader(19899): acquireImageLocked: Overriding buffer format YUV_420_888 to 0x7fa30c06.
E/chromium(19899): [ERROR:web_contents_delegate.cc(218)] WebContentsDelegate::CheckMediaAccessPermission: Not supported.
E/chromium(19899): [ERROR:web_contents_delegate.cc(218)] WebContentsDelegate::CheckMediaAccessPermission: Not supported.
W/cr_media(19899): Requires MODIFY_AUDIO_SETTINGS and RECORD_AUDIO. No audio device will be available for recording
I/CameraManagerGlobal(19899): Connecting to camera service
W/CameraManagerGlobal(19899): [soar.cts] ignore the status update of camera: 20
W/CameraManagerGlobal(19899): [soar.cts] ignore the status update of camera: 21
W/CameraManagerGlobal(19899): [soar.cts] ignore the status update of camera: 60
W/CameraManagerGlobal(19899): [soar.cts] ignore the status update of camera: 61
W/CameraManagerGlobal(19899): [soar.cts] ignore the status update of camera: 62
W/CameraManagerGlobal(19899): [soar.cts] ignore the status update of camera: 63
W/CameraManagerGlobal(19899): ignore the torch status update of camera: 20
W/CameraManagerGlobal(19899): ignore the torch status update of camera: 21
W/CameraManagerGlobal(19899): ignore the torch status update of camera: 60
W/CameraManagerGlobal(19899): ignore the torch status update of camera: 61
W/CameraManagerGlobal(19899): ignore the torch status update of camera: 62
W/CameraManagerGlobal(19899): ignore the torch status update of camera: 63
D/StreamConfigurationMap(19899): setFlag Flag:0
D/StreamConfigurationMap(19899): setFlag Flag:1
```

Log messages AFTER changing the orientation: (First 2 rows overlapped with the above log messages)

```
D/StreamConfigurationMap(19899): setFlag Flag:0
D/StreamConfigurationMap(19899): setFlag Flag:1
W/ContentCatcher(19899): Failed to notify a WebView
D/        (19899): PlayerBase::stop() from IPlayer
D/AudioTrack(19899): stop(sessionID=12697)
D/AudioTrack(19899): stop() called with 664324 frames delivered
W/cr_MediaCodecBridge(19899): Releasing: OMX.qcom.video.decoder.vp9
D/SurfaceUtils(19899): disconnecting from surface 0x7998ff1010, reason disconnectFromSurface
W/ContentCatcher(19899): Failed to notify a WebView
W/cr_MediaCodecBridge(19899): Codec released
W/AudioManager(19899): Use of stream types is deprecated for operations other than volume control
W/AudioManager(19899): See the documentation of requestAudioFocus() for what to use instead with android.media.AudioAttributes to qualify your playback use case
D/AndroidRuntime(19899): Shutting down VM
E/AndroidRuntime(19899): FATAL EXCEPTION: main
E/AndroidRuntime(19899): Process: com.bigaibot.test0001, PID: 19899
E/AndroidRuntime(19899): java.lang.NullPointerException: Attempt to invoke virtual method 'android.view.DisplayAdjustments android.view.Display.getDisplayAdjustments()' on a null object reference
E/AndroidRuntime(19899): 	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1761)
E/AndroidRuntime(19899): 	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1505)
E/AndroidRuntime(19899): 	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7354)
E/AndroidRuntime(19899): 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1092)
E/AndroidRuntime(19899): 	at android.view.Choreographer.doCallbacks(Choreographer.java:888)
E/AndroidRuntime(19899): 	at android.view.Choreographer.doFrame(Choreographer.java:819)
E/AndroidRuntime(19899): 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1078)
E/AndroidRuntime(19899): 	at android.os.Handler.handleCallback(Handler.java:873)
E/AndroidRuntime(19899): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/AndroidRuntime(19899): 	at android.os.Looper.loop(Looper.java:201)
E/AndroidRuntime(19899): 	at android.app.ActivityThread.main(ActivityThread.java:6815)
E/AndroidRuntime(19899): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(19899): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
E/AndroidRuntime(19899): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:873)
I/Process (19899): Sending signal. PID: 19899 SIG: 9
```

Thank you

**Comment by iapicca** [comment]
possibly related to https://github.com/flutter/flutter/issues/51915

**Comment by lhcdims** [comment]
Hi iapicca,

thanks for your response, but I think this issue is not related to #51915.  In #51915, the author wants NOT to pause the video after orientation change.  In my issue, the app simply crash and exit.

I have tested a few more android devices, here are the result:


The following devices work as expected.  (i.e. video pause after changing orientation)

- Redmi Note 7 (4GB Ram, 64GB Rom, Android version: 9.0, MIUI stable version: 10.2.5.0 (PFGCNXM))
- Redmi K20 Pro Premium Edition (12GB Ram, 512GB Rom, Android 10, MIUI 11.0.5 (QFKCNXM))
- Smartisan U2 Pro (4GB Ram, 64GB Rom, Android 7.1.1, Smartisan OS v6.7.3)


The following devices crash immediately after changing orientation:

- Mi 9 (8GB Ram, 128GB Rom, Android version 9.0, MIUI stable version: 10.2.35.0 (PFACNXM))
- HuaWei Nova 4 (8GB Ram, 128GB Rom, Android version 9, EMUI 9.1.0.257(C00E253R1P1))

**Comment by lhcdims** [comment]
> possibly related to #51915

Instead, it's probably related to #26345

**Comment by faverolles** [comment]
possibly related to https://github.com/flutter/flutter/issues/30130

**Comment by lhcdims** [comment]
After upgrade flutter to v1.17, it is much better, you can change the orientation for a few more times before the app crashes.

By the way, this problem does not occur in iPhone.  Only in a few Android phones such as xiaomi 9 and HuaWei Nova 4.

Below is related info:

Flutter Doctor:

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel beta, v1.17.0, on Linux, locale zh_CN.UTF-8)
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
[✓] Android Studio (version 3.6)
[✓] VS Code (version 1.44.0)
[✓] Connected device (1 available)

• No issues found!
```


Console Log:
```
E/AndroidRuntime(24852): FATAL EXCEPTION: main
E/AndroidRuntime(24852): Process: com.bigaibot.v2rayuser01, PID: 24852
E/AndroidRuntime(24852): java.lang.NullPointerException: Attempt to invoke virtual method 'android.view.DisplayAdjustments android.view.Display.getDisplayAdjustments()' on a null object reference
E/AndroidRuntime(24852): 	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1761)
E/AndroidRuntime(24852): 	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1505)
E/AndroidRuntime(24852): 	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7354)
E/AndroidRuntime(24852): 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1092)
E/AndroidRuntime(24852): 	at android.view.Choreographer.doCallbacks(Choreographer.java:888)
E/AndroidRuntime(24852): 	at android.view.Choreographer.doFrame(Choreographer.java:819)
E/AndroidRuntime(24852): 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1078)
E/AndroidRuntime(24852): 	at android.os.Handler.handleCallback(Handler.java:873)
E/AndroidRuntime(24852): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/AndroidRuntime(24852): 	at android.os.Looper.loop(Looper.java:201)
E/AndroidRuntime(24852): 	at android.app.ActivityThread.main(ActivityThread.java:6815)
E/AndroidRuntime(24852): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(24852): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
E/AndroidRuntime(24852): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:873)
I/Process (24852): Sending signal. PID: 24852 SIG: 9
Application finished.
```

**Comment by lhcdims** [comment]
related to #48888

**Comment by iapicca** [comment]
Hi @lhcdims 
I missed that issue, thank you for bringing it to my attention
in fact it seems to describe the same situation you are encountering.

Please follow up on that issue,
I'm closing the current one as duplicate.
If you disagree please write in the comments
and I will reopen it.
Thank you
