### ISSUE TITLE
[ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: NoSuchMethodError: The method '[]' was called on null.

### ISSUE THREAD

**Issue by saffer4u** [flutter/flutter#53752]
I am continuously getting these error messages in all my firebase projects. 

```
import 'package:flutter/material.dart';
import 'package:firebase_auth/firebase_auth.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: MyHomePage(),
    );
  }
}

class MyHomePage extends StatelessWidget {
  String email;
  String password;
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('Firebase Retest'),
      ),
      body: Column(
        children: <Widget>[
          TextField(
            onChanged: (value) {
              email = value;
            },
          ),
          TextField(
            onChanged: (value) {
              password = value;
            },
          ),
          RaisedButton(
            child: Text('Sign Up'),
            onPressed: () {
              FirebaseAuth.instance
                  .createUserWithEmailAndPassword(
                      email: email, password: password)
                  .then((result) {
                print(result.user.email);
              });
            },
          ),
        ],
      ),
    );
  }
}
```
dependencies : 
    firebase_auth: ^0.15.5+2

```
I/BiChannelGoogleApi(12641): [FirebaseAuth: ] getGoogleApiForMethod() returned Gms: com.google.firebase.auth.api.internal.zzaq@1e23187
D/FirebaseAuth(12641): Notifying id token listeners about user ( lFNdsGC2ITVoKNIChfd3McZ0buA2 ).
D/FirebaseAuth(12641): Notifying auth state listeners about user ( lFNdsGC2ITVoKNIChfd3McZ0buA2 ).
E/flutter (12641): [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: NoSuchMethodError: The method '[]' was called on null.
E/flutter (12641): Receiver: null
E/flutter (12641): Tried calling: []("providerData")
E/flutter (12641): #0      Object.noSuchMethod (dart:core-patch/object_patch.dart:53:5)
E/flutter (12641): #1      _decodeUser (package:firebase_auth_platform_interface/src/method_channel_firebase_auth.dart:422:45)
E/flutter (12641): #2      _decodeAuthResult (package:firebase_auth_platform_interface/src/method_channel_firebase_auth.dart:454:29)
E/flutter (12641): #3      MethodChannelFirebaseAuth.createUserWithEmailAndPassword (package:firebase_auth_platform_interface/src/method_channel_firebase_auth.dart:68:12)
E/flutter (12641): <asynchronous suspension>
E/flutter (12641): #4      FirebaseAuth.createUserWithEmailAndPassword (package:firebase_auth/src/firebase_auth.dart:64:10)
E/flutter (12641): #5      _AsyncAwaitCompleter.start (dart:async-patch/async_patch.dart:45:6)
E/flutter (12641): #6      FirebaseAuth.createUserWithEmailAndPassword (package:firebase_auth/src/firebase_auth.dart:57:52)
E/flutter (12641): #7      MyHomePage.build.<anonymous closure> (package:firebaseretest/main.dart:40:20)
E/flutter (12641): #8      _AsyncAwaitCompleter.start (dart:async-patch/async_patch.dart:45:6)
E/flutter (12641): #9      MyHomePage.build.<anonymous closure> (package:firebaseretest/main.dart:38:24)
E/flutter (12641): #10     _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:706:14)
E/flutter (12641): #11     _InkResponseState.build.<anonymous closure> (package:flutter/src/material/ink_well.dart:789:36)
E/flutter (12641): #12     GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:182:24)
E/flutter (12641): #13     TapGestureRecognizer.handleTapUp (package:flutter/src/gestures/tap.dart:486:11)
E/flutter (12641): #14     BaseTapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:264:5)
E/flutter (12641): #15     BaseTapGestureRecognizer.handlePrimaryPointer (package:flutter/src/gestures/tap.dart:199:7)
E/flutter (12641): #16     PrimaryPointerGestureRecognizer.handleEvent (package:flutter/src/gestures/recognizer.dart:467:9)
E/flutter (12641): #17     PointerRouter._dispatch (package:flutter/src/gestures/pointer_router.dart:76:12)
E/flutter (12641): #18     PointerRouter._dispatchEventToRoutes.<anonymous closure> (package:flutter/src/gestures/pointer_router.dart:117:9)
E/flutter (12641): #19     _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:379:8)
E/flutter (12641): #20     PointerRouter._dispatchEventToRoutes (package:flutter/src/gestures/pointer_router.dart:115:18)
E/flutter (12641): #21     PointerRouter.route (package:flutter/src/gestures/pointer_router.dart:101:7)
E/flutter (12641): #22     GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:218:19)
E/flutter (12641): #23     GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:198:22)
E/flutter (12641): #24     GestureBinding._handlePointerEvent (package:flutter/src/gestures/binding.dart:156:7)
E/flutter (12641): #25     GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:102:7)
E/flutter (12641): #26     GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:86:7)
E/flutter (12641): #27     _rootRunUnary (dart:async/zone.dart:1138:13)
E/flutter (12641): #28     _CustomZone.runUnary (dart:async/zone.dart:1031:19)
E/flutter (12641): #29     _CustomZone.runUnaryGuarded (dart:async/zone.dart:933:7)
E/flutter (12641): #30     _invoke1 (dart:ui/hooks.dart:273:10)
E/flutter (12641): #31     _dispatchPointerDataPacket (dart:ui/hooks.dart:182:5)
E/flutter (12641): 
```

New user is created in the firebase, but i get null in return.
Someone please help me i got stuck.

**Comment by saffer4u** [comment]
Yesterday it was working but i don't know why it's not working today

**Comment by VladyslavBondarenko** [comment]
Hi @saffer4u 
please open the issue in the [plugin's repository](https://github.com/FirebaseExtended/flutterfire/issues).
Closing, as this isn't an issue with Flutter itself,
if you disagree please write in the comments and I will reopen it
thank you
