### ISSUE TITLE
FormatException: FormatException: Bad UTF-8 encoding 0x20 (at offset 9) 

### ISSUE THREAD

**Issue by rmendoza83** [flutter/flutter#53798]
I trying to upgrade my flutter installation, but I receive the message that I specified on the title, my environment is Linux Debian Buster with KDE, and for some reason this stops to upgrade the versions, also if I try to install any package like **intl** I receive the same error. Also I tried to reinstall the last version and this works, except by the upgrading or packages installation.

Please someone can help me on this, I attached the log generated by flutter command.

## Steps to Reproduce

1. flutter -v upgrade

## Logs

Flutter crash report; please file at https://github.com/flutter/flutter/issues.

## command

flutter -v upgrade

## exception

FormatException: FormatException: Bad UTF-8 encoding 0x20 (at offset 9)

```
#0      _Utf8Decoder.convert (dart:convert/utf.dart:446:15)
#1      _Utf8ConversionSink.addSlice (dart:convert/string_conversion.dart:311:14)
#2      _Utf8ConversionSink.add (dart:convert/string_conversion.dart:307:5)
#3      _ConverterStreamEventSink.add (dart:convert/chunked_conversion.dart:74:18)
#4      _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:122:24)
#5      _rootRunUnary (dart:async/zone.dart:1134:38)
#6      _CustomZone.runUnary (dart:async/zone.dart:1031:19)
#7      _CustomZone.runUnaryGuarded (dart:async/zone.dart:933:7)
#8      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:338:11)
#9      _BufferingStreamSubscription._add (dart:async/stream_impl.dart:265:7)
#10     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:766:19)
#11     _StreamController._add (dart:async/stream_controller.dart:642:7)
#12     _StreamController.add (dart:async/stream_controller.dart:588:5)
#13     _Socket._onData (dart:io-patch/socket_patch.dart:1831:41)
#14     _rootRunUnary (dart:async/zone.dart:1138:13)
#15     _CustomZone.runUnary (dart:async/zone.dart:1031:19)
#16     _CustomZone.runUnaryGuarded (dart:async/zone.dart:933:7)
#17     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:338:11)
#18     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:265:7)
#19     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:766:19)
#20     _StreamController._add (dart:async/stream_controller.dart:642:7)
#21     _StreamController.add (dart:async/stream_controller.dart:588:5)
#22     new _RawSocket.<anonymous closure> (dart:io-patch/socket_patch.dart:1379:33)
#23     _NativeSocket.issueReadEvent.issue (dart:io-patch/socket_patch.dart:899:14)
#24     _microtaskLoop (dart:async/schedule_microtask.dart:43:21)
#25     _startMicrotaskLoop (dart:async/schedule_microtask.dart:52:5)
#26     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
#27     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:175:5)
```

## flutter doctor

```
[32m[✓][39m Flutter (Channel stable, v1.12.13, on Linux, locale es_EC)
    [32m•[39m Flutter version 1.12.13 at /home/rmendoza/flutter
    [32m•[39m Framework revision cf37c2cd07 (hace 4 meses), 2019-11-25 12:04:30 -0800
    [32m•[39m Engine revision b6b54fd606
    [32m•[39m Dart version 2.7.0

[32m[✓][39m Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    [32m•[39m Android SDK at /home/rmendoza/Android/Sdk
    [32m•[39m Android NDK location not configured (optional; useful for native profiling support)
    [32m•[39m Platform android-29, build-tools 29.0.2
    [32m•[39m Java binary at: /home/rmendoza/android-studio/jre/bin/java
    [32m•[39m Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
    [32m•[39m All Android licenses accepted.

[32m[✓][39m Android Studio (version 3.6)
    [32m•[39m Android Studio at /home/rmendoza/android-studio
    [32m•[39m Flutter plugin version 44.0.2
    [32m•[39m Dart plugin version 192.7761
    [32m•[39m Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)

[32m[✓][39m VS Code (version 1.43.2)
    [32m•[39m VS Code at /usr/share/code
    [32m•[39m Flutter extension version 3.8.1

[33m[!][39m Connected device
    [33m![39m No devices available

[33m![39m Doctor found issues in 1 category.

**Comment by TahaTesser** [comment]
Hi @rmendoza83 
Can you please try `flutter upgrade -v ` and comment complete log from this?
Thank you

**Comment by rmendoza83** [comment]
Hey @TahaTesser, I think we can close this ticket, I tried in my other laptop with linux debian buster, and this works fine, so maybe I had a wrong configuration on the system. So I decided to reinstall my linux and use ubuntu instead my debian buster. Thanks for your time.

Greetings.

**Comment by TahaTesser** [comment]
Hi @rmendoza83 
given your last message I feel safe to close this issue,
if you disagree please write in the comments and I will reopen it. 
Thank you
