### ISSUE TITLE
Flutter Returns Error 'Running gradle task "assembleRelease"' When I Build APK or Run

### ISSUE THREAD

**Issue by kumaraguru7** [flutter/flutter#53829]
Here is my log

<details>
  <summary>Logs</summary>

```bash
D:\flutter\androidX login\flutter-minimalloginUI>flutter build apk
-v
[  +85 ms] executing: [C:\flutter\] git -c log.showSignature=false
log -n 1 --pretty=format:%H
[ +163 ms] Exit code 0 from: git -c log.showSignature=false log -n
1 --pretty=format:%H
[   +5 ms] 0b8abb4724aa590dd0f429683339b1e045a1594d
[   +2 ms] executing: [C:\flutter\] git describe --match v*.*.*
--first-parent --long --tags
[  +61 ms] Exit code 0 from: git describe --match v*.*.*
--first-parent --long --tags
[   +4 ms] v1.12.13+hotfix.8-0-g0b8abb472
[  +21 ms] executing: [C:\flutter\] git rev-parse --abbrev-ref
--symbolic @{u}
[  +76 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic
@{u}
[   +1 ms] origin/stable
[   +1 ms] executing: [C:\flutter\] git ls-remote --get-url origin
[  +67 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[ +155 ms] executing: [C:\flutter\] git rev-parse --abbrev-ref HEAD
[  +45 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[   +1 ms] stable
[ +114 ms] Artifact Instance of 'AndroidMavenArtifacts' is not
required, skipping update.
[  +14 ms] Artifact Instance of 'AndroidInternalBuildArtifacts' is
not required, skipping update.
[   +2 ms] Artifact Instance of 'IOSEngineArtifacts' is not
required, skipping update.
[   +1 ms] Artifact Instance of 'FlutterWebSdk' is not required,
skipping update.
[   +8 ms] Artifact Instance of 'WindowsEngineArtifacts' is not
required, skipping update.
[   +1 ms] Artifact Instance of 'MacOSEngineArtifacts' is not
required, skipping update.
[   +1 ms] Artifact Instance of 'LinuxEngineArtifacts' is not
required, skipping update.
[   +2 ms] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not
required, skipping update.
[   +1 ms] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not
required, skipping update.
[   +1 ms] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not
required, skipping update.
[   +1 ms] Artifact Instance of 'FlutterRunnerDebugSymbols' is not
required, skipping update.
[ +638 ms] Generating D:\flutter\androidX
login\flutter-minimalloginUI\android\app\src\main\java\io\flutter\p
lugins\GeneratedPluginRegistrant.java
[ +126 ms] You are building a fat APK that includes binaries for
android-arm,
           android-arm64, android-x64.
[   +2 ms] If you are deploying the app to the Play Store, it's
recommended to
           use app bundles or split the APK to reduce the APK size.
[   +1 ms]     To generate an app bundle, run:
[   +1 ms]         flutter build appbundle --target-platform
                   android-arm,android-arm64,android-x64
[   +1 ms]         Learn more on:
                   https://developer.android.com/guide/app-bundle
[        ]     To split the APKs per ABI, run:
[   +1 ms]         flutter build apk --target-platform
                   android-arm,android-arm64,android-x64
                   --split-per-abi
[   +1 ms]         Learn more on:
                   https://developer.android.com/studio/build/confi
                   gure-apk-sp
                   lits#configure-abi-split
[  +69 ms] [!] Your app isn't using AndroidX.
[   +2 ms]     To avoid potential build failures, you can quickly
migrate your
               app by following the steps on https://goo.gl/CP92wY.
[  +24 ms] Running Gradle task 'assembleRelease'...
[   +6 ms] gradle.properties already sets `android.enableR8`
[  +10 ms] Using gradle from D:\flutter\androidX
login\flutter-minimalloginUI\android\gradlew.bat.
[  +20 ms] executing: C:\Program Files\Android\Android
Studio\jre\bin\java -version
[ +645 ms] Exit code 0 from: C:\Program Files\Android\Android
Studio\jre\bin\java -version
[   +2 ms] openjdk version "1.8.0_212-release"
           OpenJDK Runtime Environment (build
           1.8.0_212-release-1586-b04)
           OpenJDK 64-Bit Server VM (build 25.212-b04, mixed mode)
[  +16 ms] executing: [D:\flutter\androidX
login\flutter-minimalloginUI\android\] D:\flutter\androidX
login\flutter-minimalloginUI\android\gradlew.bat -Pverbose=true
-Ptarget=lib\main.dart -Ptrack-widget-creation=true -Pshrink=true
-Ptarget-platform=android-arm,android-arm64,android-x64
assembleRelease
[+16648 ms] :app:compileFlutterBuildRelease
[  +14 ms] [ +116 ms] executing: [C:\flutter\] git -c
log.showSignature=false log -n 1 --pretty=format:%H
[ +149 ms] [ +277 ms] Exit code 0 from: git -c
log.showSignature=false log -n 1 --pretty=format:%H
[   +2 ms] [   +1 ms] 0b8abb4724aa590dd0f429683339b1e045a1594d
[   +2 ms] [   +1 ms] executing: [C:\flutter\] git describe --match
v*.*.* --first-parent --long --tags
[  +74 ms] [ +101 ms] Exit code 0 from: git describe --match v*.*.*
--first-parent --long --tags
[  +12 ms] [        ] v1.12.13+hotfix.8-0-g0b8abb472
[  +57 ms] [  +34 ms] executing: [C:\flutter\] git rev-parse
--abbrev-ref --symbolic @{u}
[  +79 ms] [ +117 ms] Exit code 0 from: git rev-parse --abbrev-ref
--symbolic @{u}
[   +3 ms] [        ] origin/stable
[   +1 ms] [        ] executing: [C:\flutter\] git ls-remote
--get-url origin
[  +71 ms] [  +79 ms] Exit code 0 from: git ls-remote --get-url
origin
[   +4 ms] [        ] https://github.com/flutter/flutter.git
[ +215 ms] [ +218 ms] executing: [C:\flutter\] git rev-parse
--abbrev-ref HEAD
[ +216 ms] [ +204 ms] Exit code 0 from: git rev-parse --abbrev-ref
HEAD
[   +3 ms] [        ] stable
[  +71 ms] [  +86 ms] Artifact Instance of 'AndroidMavenArtifacts'
is not required, skipping update.
[   +3 ms] [   +1 ms] Artifact Instance of
'AndroidGenSnapshotArtifacts' is not required, skipping update.
[  +17 ms] [   +2 ms] Artifact Instance of
'AndroidInternalBuildArtifacts' is not required, skipping update.
[   +5 ms] [   +1 ms] Artifact Instance of 'IOSEngineArtifacts' is
not required, skipping update.
[  +10 ms] [        ] Artifact Instance of 'FlutterWebSdk' is not
required, skipping update.
[  +19 ms] [  +21 ms] Artifact Instance of 'WindowsEngineArtifacts'
is not required, skipping update.
[   +4 ms] [   +2 ms] Artifact Instance of 'MacOSEngineArtifacts'
is not required, skipping update.
[   +3 ms] [   +1 ms] Artifact Instance of 'LinuxEngineArtifacts'
is not required, skipping update.
[   +3 ms] [   +2 ms] Artifact Instance of
'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[   +3 ms] [   +2 ms] Artifact Instance of
'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[   +7 ms] [   +5 ms] Artifact Instance of
'FlutterRunnerSDKArtifacts' is not required, skipping update.
[   +6 ms] [        ] Artifact Instance of
'FlutterRunnerDebugSymbols' is not required, skipping update.
[ +312 ms] [ +346 ms] Initializing file store
[  +71 ms] [  +57 ms] Done initializing file store
[+4107 ms] [+4121 ms] Skipping target: kernel_snapshot
[  +44 ms] [  +29 ms] invalidated build due to missing files:
C:\flutter\bin\cache\artifacts\engine\android-arm-release\windows-x
64\gen_snapshot
[   +3 ms] [   +7 ms] invalidated build due to missing files:
D:\flutter\androidX, login\flutter-minimalloginUI\pubspec.yaml,
login\flutter-minimalloginUI\assets\facebook.png,
login\flutter-minimalloginUI\assets\Montserrat-Regular.ttf,
login\flutter-minimalloginUI\assets\Montserrat-Bold.ttf
[   +2 ms] [  +14 ms] invalidated build due to missing files:
C:\flutter\bin\cache\artifacts\engine\android-arm64-release\windows
-x64\gen_snapshot
[  +36 ms] [  +26 ms] invalidated build due to missing files:
C:\flutter\bin\cache\artifacts\engine\android-x64-release\windows-x
64\gen_snapshot
[ +188 ms] [ +199 ms] aot_android_asset_bundle: Starting due to
{InvalidatedReason.outputMissing, InvalidatedReason.inputMissing}
[ +416 ms] [ +419 ms] aot_android_asset_bundle: Complete
[ +499 ms] [ +491 ms] android_aot_release_android-arm: Starting due
to {InvalidatedReason.inputMissing}
[  +15 ms] [  +22 ms] executing:
C:\flutter\bin\cache\artifacts\engine\android-arm-release\windows-x
64\gen_snapshot --causal_async_stacks --deterministic
--snapshot_kind=app-aot-elf --elf=D:\flutter\androidX
login\flutter-minimalloginUI\.dart_tool\flutter_build\b643554cca155
78448babf11258ef1a8\armeabi-v7a\app.so --strip --no-sim-use-hardfp
--no-use-integer-division D:\flutter\androidX
login\flutter-minimalloginUI\.dart_tool\flutter_build\b643554cca155
78448babf11258ef1a8\app.dill
[ +239 ms] [ +233 ms] android_aot_release_android-arm64: Starting
due to {InvalidatedReason.inputMissing}
[  +15 ms] [   +5 ms] executing:
C:\flutter\bin\cache\artifacts\engine\android-arm64-release\windows
-x64\gen_snapshot --causal_async_stacks --deterministic
--snapshot_kind=app-aot-elf --elf=D:\flutter\androidX
login\flutter-minimalloginUI\.dart_tool\flutter_build\b643554cca155
78448babf11258ef1a8\arm64-v8a\app.so --strip D:\flutter\androidX
login\flutter-minimalloginUI\.dart_tool\flutter_build\b643554cca155
78448babf11258ef1a8\app.dill
[ +139 ms] [ +149 ms] android_aot_release_android-x64: Starting due
to {InvalidatedReason.inputMissing}
[   +1 ms] [   +4 ms] executing:
C:\flutter\bin\cache\artifacts\engine\android-x64-release\windows-x
64\gen_snapshot --causal_async_stacks --deterministic
--snapshot_kind=app-aot-elf --elf=D:\flutter\androidX
login\flutter-minimalloginUI\.dart_tool\flutter_build\b643554cca155
78448babf11258ef1a8\x86_64\app.so --strip D:\flutter\androidX
login\flutter-minimalloginUI\.dart_tool\flutter_build\b643554cca155
78448babf11258ef1a8\app.dill
[+14722 ms] [+14734 ms] android_aot_release_android-arm64: Complete
[ +112 ms] [ +112 ms] android_aot_release_android-x64: Complete
[ +180 ms] [ +181 ms] Skipping target:
android_aot_bundle_release_android-arm64
[ +102 ms] [  +94 ms] Skipping target:
android_aot_bundle_release_android-x64
[+1138 ms] [+1144 ms] android_aot_release_android-arm: Complete
[ +461 ms] [ +417 ms] Skipping target:
android_aot_bundle_release_android-arm
[   +5 ms] [   +2 ms] Skipping target: _composite
[   +2 ms] [   +2 ms] Persisting file store
[  +15 ms] [  +43 ms] Done persisting file store
[  +22 ms] [  +18 ms] build succeeded.
[  +77 ms] [  +89 ms] "flutter assemble" took 23,270ms.
[ +337 ms] :app:packLibsflutterBuildRelease UP-TO-DATE
[   +3 ms] :app:preBuild UP-TO-DATE
[  +45 ms] :app:extractProguardFiles UP-TO-DATE
[ +803 ms] :app:preReleaseBuild UP-TO-DATE
[  +41 ms] :app:compileReleaseAidl UP-TO-DATE
[  +51 ms] :app:compileReleaseRenderscript UP-TO-DATE
[   +2 ms] :app:checkReleaseManifest UP-TO-DATE
[  +21 ms] :app:generateReleaseBuildConfig UP-TO-DATE
[   +7 ms] :app:prepareLintJar UP-TO-DATE
[  +67 ms] :app:cleanMergeReleaseAssets
[   +6 ms] :app:mergeReleaseShaders UP-TO-DATE
[  +23 ms] :app:compileReleaseShaders UP-TO-DATE
[   +5 ms] :app:generateReleaseAssets UP-TO-DATE
[ +110 ms] :app:mergeReleaseAssets
[ +174 ms] :app:copyFlutterAssetsRelease
[ +157 ms] :app:mainApkListPersistenceRelease UP-TO-DATE
[  +21 ms] :app:generateReleaseResValues UP-TO-DATE
[   +4 ms] :app:generateReleaseResources UP-TO-DATE
[ +123 ms] :app:mergeReleaseResources UP-TO-DATE
[   +6 ms] :app:createReleaseCompatibleScreenManifests UP-TO-DATE
[  +53 ms] :app:processReleaseManifest UP-TO-DATE
[   +6 ms] :app:splitsDiscoveryTaskRelease UP-TO-DATE
[+18476 ms]
C:\Users\Admin\.gradle\caches\transforms-1\files-1.1\support-compat
-28.0.0.aar\219e817416db6465408306f78437975b\res\values\values.xml:
133:5-70: AAPT: error: resource android:attr/fontVariationSettings
not found.
[   +9 ms]
C:\Users\Admin\.gradle\caches\transforms-1\files-1.1\support-compat
-28.0.0.aar\219e817416db6465408306f78437975b\res\values\values.xml:
133:5-70: AAPT: error: resource android:attr/ttcIndex not found.
[   +5 ms] :app:processReleaseResources
[   +2 ms] error: failed linking references.
[ +219 ms] :app:processReleaseResources FAILED
[  +44 ms] FAILURE: Build failed with an exception.
[   +3 ms] * What went wrong:
[   +2 ms] Execution failed for task
':app:processReleaseResources'.
[   +4 ms] > Failed to process resources, see aapt output above for
details.
[   +2 ms] * Try:
[   +2 ms] Run with --stacktrace option to get the stack trace. Run
with --info or --debug option to get more log output. Run with
--scan to get full insights.
[  +14 ms] * Get more help at https://help.gradle.org
[   +3 ms] BUILD FAILED in 1m 1s
[  +16 ms] 21 actionable tasks: 5 executed, 16 up-to-date
[ +953 ms] Running Gradle task 'assembleRelease'... (completed in
63.1s)
[  +34 ms] "flutter apk" took 64,302ms.
Gradle task assembleRelease failed with exit code 1

#0      throwToolExit
(package:flutter_tools/src/base/common.dart:28:3)
#1      buildGradleApp
(package:flutter_tools/src/android/gradle.dart:431:7)
#2      _asyncThenWrapperHelper.<anonymous closure>
(dart:async-patch/async_patch.dart:73:64)
#3      _rootRunUnary (dart:async/zone.dart:1134:38)
#4      _CustomZone.runUnary (dart:async/zone.dart:1031:19)
#5      _FutureListener.handleValue
(dart:async/future_impl.dart:139:18)
#6      Future._propagateToListeners.handleValueCallback
(dart:async/future_impl.dart:680:45)
#7      Future._propagateToListeners
(dart:async/future_impl.dart:709:32)
#8      Future._completeWithValue
(dart:async/future_impl.dart:524:5)
#9      Future._asyncComplete.<anonymous closure>
(dart:async/future_impl.dart:554:7)
#10     _rootRun (dart:async/zone.dart:1126:13)
#11     _CustomZone.run (dart:async/zone.dart:1023:19)
#12     _CustomZone.runGuarded (dart:async/zone.dart:925:7)
#13     _CustomZone.bindCallbackGuarded.<anonymous closure>
(dart:async/zone.dart:965:23)
#14     _microtaskLoop (dart:async/schedule_microtask.dart:43:21)
#15     _startMicrotaskLoop
(dart:async/schedule_microtask.dart:52:5)
#16     _runPendingImmediateCallback
(dart:isolate-patch/isolate_patch.dart:118:13)
#17     _RawReceivePortImpl._handleMessage
(dart:isolate-patch/isolate_patch.dart:175:5)



D:\flutter\androidX login\flutter-minimalloginUI>+0
'+0' is not recognized as an internal or external command,
operable program or batch file.
```

</details>

**Comment by jonahwilliams** [comment]
See also: https://stackoverflow.com/questions/49208772/error-resource-androidattr-fontvariationsettings-not-found

Does this work if you specify a compileSdkVersion of 28?

**Comment by kumaraguru7** [comment]
> 
> 
> See also: https://stackoverflow.com/questions/49208772/error-resource-androidattr-fontvariationsettings-not-found
> 
> Does this work if you specify a compileSdkVersion of 28?

changed it but problem persists. pls help

**Comment by iapicca** [comment]
Hi @kumaraguru7 
can you please provide your `flutter doctor -v` , 
and your `Android` -> `App` -> `build.gradle`
Thank you

**Comment by liyang1518** [comment]
Find out the problematic third party plug-in, set compileSdkVersion in the gradle configuration file inside the plug-in

**Comment by kumaraguru7** [comment]
Thanks @liyang1518  , @jonahwilliams and @iapicca ! **YOU GUYS HELPED ME OUT!**
