### ISSUE TITLE
[tool_crash] Invalid argument(s): Cannot find executable for build/linux/debug/gallery.

### ISSUE THREAD

**Issue by Natdiv** [flutter/flutter#53887]
## Command
```
flutter run -d linux
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
ArgumentError: Invalid argument(s): Cannot find executable for build/linux/debug/gallery.
```
#0      _getExecutable (package:process/src/interface/local_process_manager.dart:127:5)
#1      LocalProcessManager.start (package:process/src/interface/local_process_manager.dart:43:30)
#2      DesktopDevice.startApp (package:flutter_tools/src/desktop_device.dart:104:58)
<asynchronous suspension>
#3      FlutterDevice.runHot (package:flutter_tools/src/resident_runner.dart:437:54)
<asynchronous suspension>
#4      HotRunner.run (package:flutter_tools/src/run_hot.dart:361:31)
#5      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:564:37)
#6      _rootRunUnary (dart:async/zone.dart:1192:38)
#7      _CustomZone.runUnary (dart:async/zone.dart:1085:19)
#8      _FutureListener.handleValue (dart:async/future_impl.dart:141:18)
#9      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:682:45)
#10     Future._propagateToListeners (dart:async/future_impl.dart:711:32)
#11     Future._completeWithValue (dart:async/future_impl.dart:526:5)
#12     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:36:15)
#13     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:298:13)
#14     FlutterDevice.create (package:flutter_tools/src/resident_runner.dart)
#15     _rootRunUnary (dart:async/zone.dart:1192:38)
#16     _CustomZone.runUnary (dart:async/zone.dart:1085:19)
#17     _FutureListener.handleValue (dart:async/future_impl.dart:141:18)
```
```
[✓] Flutter (Channel master, v1.16.4-pre.86, on Linux, locale en_US.UTF-8)
    • Flutter version 1.16.4-pre.86 at /opt/flutter
    • Framework revision a8b3d1b74f (2 hours ago), 2020-04-02 15:40:37 -0700
    • Engine revision f56e678e7f
    • Dart version 2.8.0 (build 2.8.0-dev.19.0 fae35fca47)

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /home/natdiv/Android/Sdk
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = /home/natdiv/Android/Sdk
    • Java binary at: /opt/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Linux toolchain - develop for Linux desktop
    • clang++ 7.0.1
    • GNU Make 4.2.1

[✓] Android Studio (version 3.5)
    • Android Studio at /opt/android-studio
    • Flutter plugin version 43.0.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] IntelliJ IDEA Ultimate Edition (version 2019.2)
    • IntelliJ at /opt/idea-IU-192.6817.14
    • Flutter plugin version 43.0.2
    • Dart plugin version 192.7761

[✓] VS Code (version 1.42.1)
    • VS Code at /usr/share/code
    • Flutter extension version 3.8.1

[✓] Connected device (2 available)
    • Custom • 192.168.59.101:5555 • android-x86 • Android 5.1 (API 22)
    • Linux  • Linux               • linux-x64   • Linux

• No issues found!

```

## Flutter Application Metadata
**Type**: app
**Version**: 2.3.0+020300
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: master
**Creation framework version**: f5733f7a62ebc7c2ba324a2b410cd81215956b7d
### Plugins
package_info-0.4.0+16
path_provider-1.6.5
path_provider_macos-0.0.4
shared_preferences-0.5.6+3
shared_preferences_macos-0.0.1+6
shared_preferences_web-0.1.2+4
url_launcher-5.4.2
url_launcher_macos-0.0.1+4
url_launcher_web-0.1.1+1

**Comment by stuartmorgan** [comment]
This is a bug in gallery, not Flutter. See https://github.com/flutter/gallery/issues/77.
