### ISSUE TITLE
Source maps are not done loading`-d web` flag throw "Bad State: Source maps are not done loading" in debug mode

### ISSUE THREAD

**Issue by johnpryan** [flutter/flutter#53883]
##  Steps to Reproduce
1. Run the code below with `flutter run -d web`
## Example code

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(SourceMapDemo());
}

class SourceMapDemo extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        body: Center(
          child: RaisedButton(
            child: Text('Click me'),
            onPressed: () {
              assert(false, 'oops!');
            },
          ),
        ),
      ),
    );
  }
}
```

1. Run `flutter create bug`.
2. Update the files as follows: ... 
3. ... 

**Expected results:** 

**Actual results:** 

<details>
  <summary>Logs</summary>

```

Uncaught Bad state: Source maps are not done loading.
    at Object.a (http://localhost:5000/stack_trace_mapper.js:261:3)
    at ct.k6 (http://localhost:5000/stack_trace_mapper.js:2650:23)
    at Object.iH (http://localhost:5000/stack_trace_mapper.js:218:69)
    at jy (http://localhost:5000/stack_trace_mapper.js:2371:10)
    at Object.<anonymous> (http://localhost:5000/stack_trace_mapper.js:2365:42)
    at dart._StackTrace.new.toString (http://localhost:5000/dart_sdk.js:6060:29)
    at Object._toString [as toString] (http://localhost:5000/dart_sdk.js:4431:26)
    at new assertions.DiagnosticsStackTrace.new (http://localhost:5000/packages/flutter/src/foundation/debug.dart.js:3467:212)
    at assertions.FlutterErrorDetails.new.debugFillProperties (http://localhost:5000/packages/flutter/src/foundation/debug.dart.js:3209:24)
    at http://localhost:5000/packages/flutter/src/foundation/debug.dart.js:2313:38
    at assertions._FlutterErrorDetailsNode.new.get builder (http://localhost:5000/packages/flutter/src/foundation/debug.dart.js:2316:28)
    at assertions._FlutterErrorDetailsNode.new.get builder [as builder] (http://localhost:5000/packages/flutter/src/foundation/debug.dart.js:3481:27)
    at assertions._FlutterErrorDetailsNode.new.getProperties (http://localhost:5000/packages/flutter/src/foundation/debug.dart.js:2328:45)
    at diagnostics$.TextTreeRenderer.new.[_debugRender] (http://localhost:5000/packages/flutter/src/foundation/debug.dart.js:1137:37)
    at diagnostics$.TextTreeRenderer.new.render (http://localhost:5000/packages/flutter/src/foundation/debug.dart.js:1051:34)
    at Function.dumpErrorToConsole (http://localhost:5000/packages/flutter/src/foundation/debug.dart.js:3315:142)
    at Function.reportError (http://localhost:5000/packages/flutter/src/foundation/debug.dart.js:3404:76)
    at binding$5.WidgetsFlutterBinding.new.[_invokeFrameCallback] (http://localhost:5000/packages/flutter/src/scheduler/binding.dart.js:743:33)
    at binding$5.WidgetsFlutterBinding.new.handleDrawFrame (http://localhost:5000/packages/flutter/src/scheduler/binding.dart.js:711:37)
    at binding$5.WidgetsFlutterBinding.new.[_handleDrawFrame] (http://localhost:5000/packages/flutter/src/scheduler/binding.dart.js:668:12)
    at Object._invoke (http://localhost:5000/dart_sdk.js:164812:7)
    at _engine.EngineWindow.new.invokeOnDrawFrame (http://localhost:5000/dart_sdk.js:162105:15)
    at http://localhost:5000/dart_sdk.js:162529:28
```

```
```

```
```

</details>

**Comment by iapicca** [comment]
Hi @johnpryan 
can you please provide your `flutter doctor -v`
and your `flutter run -d chrome --verbose` 
Thank you

**Comment by stanabs-mgt** [comment]
Help me after watching my attachment.


Waiting.
Thanks
Tarik

**Comment by johnpryan** [comment]
Accidental dupe of https://github.com/flutter/flutter/issues/53884
