### ISSUE TITLE
Exception thrown when clearing the controller of a TextField

### ISSUE THREAD

**Issue by julianbraasch** [flutter/flutter#53899]
This is a follow-up to #36065 

## Steps to Reproduce

```dart
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: MyHomePage(),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key key}) : super(key: key);

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  TextEditingController _controller = TextEditingController();

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Center(
        child: TextFormField(
          controller: _controller,
          decoration: InputDecoration(
            suffixIcon: IconButton(
              icon: Icon(Icons.clear),
              onPressed: () => _controller.text = "",
            )
          )
        )
      )
    );
  }
}

```

1. Run app
2. Enter text into the TextFormField
3. Click the "x" icon.

**Expected results:** The TextFromField should be empty

**Actual results:** The following exception is thrown:
```
The following assertion was thrown while handling a gesture:
invalid text selection: TextSelection(baseOffset: 10, extentOffset: 10, affinity: TextAffinity.upstream, isDirectional: false)

When the exception was thrown, this was the stack: 
#0      TextEditingController.selection= (package:flutter/src/widgets/editable_text.dart:193:7)
#1      EditableTextState._handleSelectionChanged (package:flutter/src/widgets/editable_text.dart:1485:23)
#2      RenderEditable._handleSelectionChange (package:flutter/src/rendering/editable.dart:417:7)
#3      RenderEditable.selectPositionAt (package:flutter/src/rendering/editable.dart:1568:5)
#4      RenderEditable.selectPosition (package:flutter/src/rendering/editable.dart:1539:5)
...
Handler: "onTapUp"
Recognizer: _TransparentTapGestureRecognizer#48765
  debugOwner: _TextSelectionGestureDetectorState#bd4cc
  state: ready
  won arena
  finalPosition: Offset(368.3, 378.9)
  finalLocalPosition: Offset(368.3, 23.2)
  button: 1
  sent tap down
```
That being said, the TextFormField is empty after all.

## Flutter analyze

```
No issues found!
```

## flutter doctor -v

```
[√] Flutter (Channel stable, v1.12.13+hotfix.9, on Microsoft Windows [Version 10.0.18363.752], locale de-DE)
    • Flutter version 1.12.13+hotfix.9 at C:\Development\devTools\flutter-sdk
    • Framework revision f139b11009 (3 days ago), 2020-03-30 13:57:30 -0700
    • Engine revision af51afceb8
    • Dart version 2.7.2


[√] Android toolchain - develop for Android devices (Android SDK version 29.0.1)
    • Android SDK at C:\Users\Julian\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.1
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)
    • All Android licenses accepted.

[√] Android Studio (version 3.6)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 44.0.2
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)

[√] VS Code (version 1.43.2)
    • VS Code at C:\Users\Julian\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.5.0

[√] Connected device (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 10 (API 29) (emulator)

• No issues found!
```

</details>

**Comment by VladyslavBondarenko** [comment]
Hi @julianbraasch 
It is fixed here https://github.com/flutter/flutter/issues/35848,
consider to use another channel - beta or dev, the fix is already in there, but not in stable yet
Closing, if you disagree please write in the comments and I will reopen it
Thank you
