### ISSUE TITLE
ProcessException: The system cannot find the file specified ..\flutter\bin\cache\dart-sdk\bin\pub.bat

### ISSUE THREAD

**Issue by mhsamih** [flutter/flutter#53913]
Flutter crash report; please file at https://github.com/flutter/flutter/issues.

## command

flutter create C:\Users\mh\Desktop\app

## exception

ProcessException: ProcessException: The system cannot find the file specified.

  Command: F:\برامج\Programming\flutter_windows_v1.12.13+hotfix.8-stable\flutter\bin\cache\dart-sdk\bin\pub.bat --verbosity=warning get --no-precompile

```
#0      _DefaultProcessUtils.stream (package:flutter_tools/src/base/process.dart:431:29)
<asynchronous suspension>
#1      _DefaultPub.batch (package:flutter_tools/src/dart/pub.dart:259:33)
#2      _DefaultPub.get (package:flutter_tools/src/dart/pub.dart:176:15)
#3      CreateCommand._generateApp (package:flutter_tools/src/commands/create.dart:588:17)
#4      CreateCommand.runCommand (package:flutter_tools/src/commands/create.dart:429:37)
<asynchronous suspension>
#5      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:615:18)
#6      _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:73:64)
#7      _rootRunUnary (dart:async/zone.dart:1134:38)
#8      _CustomZone.runUnary (dart:async/zone.dart:1031:19)
#9      _FutureListener.handleValue (dart:async/future_impl.dart:139:18)
#10     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:680:45)
#11     Future._propagateToListeners (dart:async/future_impl.dart:709:32)
#12     Future._completeWithValue (dart:async/future_impl.dart:524:5)
#13     Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:554:7)
#14     _rootRun (dart:async/zone.dart:1126:13)
#15     _CustomZone.run (dart:async/zone.dart:1023:19)
#16     _CustomZone.runGuarded (dart:async/zone.dart:925:7)
#17     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:965:23)
#18     _microtaskLoop (dart:async/schedule_microtask.dart:43:21)
#19     _startMicrotaskLoop (dart:async/schedule_microtask.dart:52:5)
#20     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
#21     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:175:5)
```

## flutter doctor

```
[32m[✓][39m Flutter (Channel stable, v1.12.13+hotfix.8, on Microsoft Windows [Version 10.0.14393], locale en-US)
    [32m•[39m Flutter version 1.12.13+hotfix.8 at F:\برامج\Programming\flutter_windows_v1.12.13+hotfix.8-stable\flutter
    [32m•[39m Framework revision 0b8abb4724 (7 weeks ago), 2020-02-11 11:44:36 -0800
    [32m•[39m Engine revision e1e6ced81d
    [32m•[39m Dart version 2.7.0

[33m[!][39m Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    [32m•[39m Android SDK at C:\Users\mh\AppData\Local\Android\sdk
    [32m•[39m Android NDK location not configured (optional; useful for native profiling support)
    [32m•[39m Platform android-29, build-tools 29.0.3
    [32m•[39m Java binary at: E:\IntelliJ\jbr\bin\bin\java
    [31m✗[39m Cannot execute E:\IntelliJ\jbr\bin\bin\java to determine the version

[33m[!][39m Android Studio (not installed)
    [32m•[39m Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/setup/#android-setup for detailed instructions).

[32m[✓][39m Connected device (1 available)
    [32m•[39m AMN LX9 • 7YBNU19412118962 • android-arm • Android 9 (API 28)

[33m![39m Doctor found issues in 2 categories.
```

**Comment by VladyslavBondarenko** [comment]
Hi @mhsamih 
does the file exists `F:\برامج\Programming\flutter_windows_v1.12.13+hotfix.8-stable\flutter\bin\cache\dart-sdk\bin\pub.bat`?

**Comment by myappgurus** [comment]
[Flutter app development](https://myappgurus.com/services/flutter-app-development/) is known for speeding up the iOS app development process because of its Hot Reload feature. This function helps you transfer all changes from the code to a connected device or running an emulator instantly. It avoids rebuilding the app from scratch. Visit myappgurus(dot)com for great and speedy app development.

**Comment by sandy9808** [comment]
i have also got this same problem 
I tried to install the new version also but it didn't worked out.
**click on this link for more information:**
https://github.com/flutter/flutter/issues/47071#issuecomment-604740810

**Comment by VladyslavBondarenko** [comment]
@mhsamih 
I hope you've solved the issue.
Closing as additional information isn't provided.
Could everyone who still has this problem please file a new issue with the exact descriptions what happens, logs and the output of `flutter doctor -v` please.
