### ISSUE TITLE
Images from the asset bundle are not loading on Mac/iOS targets.

### ISSUE THREAD

**Issue by chinmaygarde** [flutter/flutter#5395]
This is on tip of tree https://github.com/flutter/flutter/tree/facd3e238f813c95619cb8d8fcbf75db00e296c3

Logs:

```
[ERROR:../../lib/tonic/logging/dart_error.cc(16)] Unhandled exception:
FormatException: Unexpected end of input (at character 1)

^

#0      _ChunkedJsonParser.fail (dart:convert-patch/convert_patch.dart:1328)
#1      _ChunkedJsonParser.close (dart:convert-patch/convert_patch.dart:484)
#2      _parseJson (dart:convert-patch/convert_patch.dart:20)
#3      JsonDecoder.convert (dart:convert/json.dart:501)
#4      JsonCodec.decode (dart:convert/json.dart:127)
#5      AssetImage._manifestParser (package:flutter/src/services/image_resolution.dart:145:55)
#6      _RootZone.runUnary (dart:async/zone.dart:1404)
#7      _FutureListener.handleValue (dart:async/future_impl.dart:131)
#8      _Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:637)
#9      _Future._propagateToListeners (dart:async/future_impl.dart:667)
#10     _Future._complete (dart:async/future_impl.dart:467)
#11     _SyncCompleter.complete (dart:async/future_impl.dart:52)
#12     CachingAssetBundle._fetchString.<_fetchString_async_body> (package:flutter/src/services/asset_bundle.dart:139:5)
#13     _RootZone.runUnary (dart:async/zone.dart:1404)
#14     _FutureListener.handleValue (dart:async/future_impl.dart:131)
#15     _Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:637)
#16     _Future._propagateToListeners (dart:async/future_impl.dart:667)
#17     _Future._completeWithValue (dart:async/future_impl.dart:477)
#18     _Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:528)
#19     _microtaskLoop (dart:async/schedule_microtask.dart:41)
#20     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50)
══╡ EXCEPTION CAUGHT BY SERVICES LIBRARY ╞══════════════════════════════════════════════════════════
The following FormatException was thrown while resolving an image:
FormatException: Unexpected end of input (at character 1)

^


When the exception was thrown, this was the stack:
#0      _ChunkedJsonParser.fail (dart:convert-patch/convert_patch.dart:1328)
#1      _ChunkedJsonParser.close (dart:convert-patch/convert_patch.dart:484)
#2      _parseJson (dart:convert-patch/convert_patch.dart:20)
#3      JsonDecoder.convert (dart:convert/json.dart:501)
#4      JsonCodec.decode (dart:convert/json.dart:127)
#5      AssetImage._manifestParser (package:flutter/src/services/image_resolution.dart:145:55)
#12     CachingAssetBundle._fetchString.<_fetchString_async_body> (package:flutter/src/services/asset_bundle.dart:139:5)
(elided 14 frames from package dart:async)

Image provider: AssetImage(bundle: null, name:
packages/flutter_gallery_assets/appbar/appbar_background_layer0.png)

```

**Comment by sethladd** [comment]
Is there a way to test this for future builds?

**Comment by chinmaygarde** [comment]
I also verified that the `app.flx` contained the manifest and it was populated correctly.

**Comment by Hixie** [comment]
This seems to be fixed now?
