### ISSUE TITLE
Ability to use ParagraphBuilder & Paragraph in other isolates

### ISSUE THREAD

**Issue by modulovalue** [flutter/flutter#53985]
I need to calculate metrics for thousands of paragraphs in a way that doesn't lead to UI jank.

Therefore I'd like to Instantiate a ParagraphBuilder and build a Paragraph in a separate isolate to  pass back metrics to the main isolate.

This is currently not possible.

Related issues:
#10647
#13343

_(I'm opening a separate issue because it was mentioned that it is theoretically possible to have parts of dart:ui accessible to other isolates. I don't need all of dart:ui, just the text related parts)_

Example:
```dart
import 'dart:ui';

import 'package:flutter/foundation.dart';
import 'package:flutter/material.dart';

void main() async {
  final size = await compute(computeParagraph, "abc");
  runApp(Text("$size"));
}

Size computeParagraph(String text) {
  final builder = ParagraphBuilder(ParagraphStyle(textDirection: TextDirection.ltr));
  builder.addText(text);
  final paragraph = builder.build();
  paragraph.layout(const ParagraphConstraints(width: double.infinity));
  return Size(paragraph.width, paragraph.height);
}

```

throws
```
[ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: Exception: error: native function 'ParagraphBuilder_constructor' (9 arguments) cannot be found
#0      new ParagraphBuilder (dart:ui/text.dart:2070:5)
#1      computeParagraph (package:flutter_companion_macos/main.dart:12:19)
#2      _IsolateConfiguration.apply (package:flutter/src/foundation/_isolates_io.dart:75:34)
#3      _spawn.<anonymous closure> (package:flutter/src/foundation/_isolates_io.dart:83:65)
#4      Timeline.timeSync (dart:developer/timeline.dart:163:22)
#5      _spawn (package:flutter/src/foundation/_isolates_io.dart:80:18)
#6      _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:304:17)
#7      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:168:12)
```

**Comment by modulovalue** [comment]
I no longer think that passing back metrics would be enough to fix the performance issues that made me open this issue.

Passing back whole `Paragraph`s would also not be enough, because they'd need to be available synchronously for the painting phase to avoid blank paragraphs i.e. frames where no text is being painted onto the screen.

_I will most likely close this issue once I have a reproducible example for the performance issues that I'm experiencing._

**Comment by matthew-carroll** [comment]
This issue is also a problem for me in #115257 - please don't close this ticket without an actual resolution.
