### ISSUE TITLE
ClassNotFoundException (Didn't find Main Activity)

### ISSUE THREAD

**Issue by julisanchez** [flutter/flutter#54012]
The app is not compiling for both platforms.
flutter --clean does not solve the problem.

This is the issue for IOS: (https://github.com/flutter/flutter/issues/53776)

<details>
  <summary>Logs (Android)</summary>

**Output**
```
Launching lib/main.dart on Android SDK built for x86 in debug mode...
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
Note: /Applications/flutter/.pub-cache/hosted/pub.dartlang.org/cloud_firestore-0.13.4+2/android/src/main/java/io/flutter/plugins/firebase/cloudfirestore/CloudFirestorePlugin.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:processDebugResources'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.Workers$ActionFacade
   > Path '/Users/juliansanchez/Documents/Proyectos/go_agenda/build/flutter_statusbarcolor/intermediates/compiled_local_resources/debug/out' is not a readable directory.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 33s
Gradle task assembleDebug failed with exit code 1
Exited (sigterm)
```

**flutter run --verbose**
[flutter-verbose.txt](https://github.com/flutter/flutter/files/4432578/flutter-verbose.txt)

**flutter analyse**
```
No issues found! (ran in 16.3s)
```

**flutter doctor -v**
```
[✓] Flutter (Channel stable, v1.12.13+hotfix.8, on Mac OS X 10.15.3 19D76, locale en-AR)
    • Flutter version 1.12.13+hotfix.8 at /Applications/flutter
    • Framework revision 0b8abb4724 (8 weeks ago), 2020-02-11 11:44:36 -0800
    • Engine revision e1e6ced81d
    • Dart version 2.7.0

 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/juliansanchez/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.1, Build version 11A1027
    • CocoaPods version 1.9.1

[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 44.0.2
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)

[!] Android Studio (version 3.4)
    • Android Studio at /Users/juliansanchez/Library/Application
      Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/183.5692245/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

[✓] IntelliJ IDEA Ultimate Edition (version 2019.2)
    • IntelliJ at /Users/juliansanchez/Applications/JetBrains Toolbox/IntelliJ IDEA Ultimate.app
    • Flutter plugin version 39.0.4
    • Dart plugin version 192.7761

[✓] VS Code (version 1.43.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.9.0

[✓] Connected device (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 9 (API 28) (emulator)

! Doctor found issues in 1 category.
```

</details>

**Comment by iapicca** [comment]
Hi @julisanchez 
can you please run `flutter upgrade --force`

and, if the issue persists, 
provide your `flutter run --verbose`,
your `pubspec.yaml` or if possible a reproducible minimal code sample.
Thank you

**Comment by iapicca** [comment]
Hi @julisanchez 

```bash
/Users/juliansanchez/Documents/Proyectos/go_agenda/build/firebase_core_web/gener
ated/source/buildConfig/debug/io/flutter/plugins/firebase_core_web/BuildConfig
2.java:6: error: class BuildConfig is public, should be declared in a file named
BuildConfig.java
[   +1 ms] public final class BuildConfig {
[        ]              ^
[        ]
/Users/juliansanchez/Documents/Proyectos/go_agenda/build/firebase_core_web/gener
ated/source/buildConfig/debug/io/flutter/plugins/firebase_core_web/BuildConfig
5.java:6: error: class BuildConfig is public, should be declared in a file named
BuildConfig.java
[        ] public final class BuildConfig {
[        ]              ^
[        ] 2 errors
[        ] FAILURE: Build failed with an exception.
[        ] * What went wrong:
[        ] Execution failed for task
':firebase_core_web:compileDebugJavaWithJavac'.
[        ] > Compilation failed; see the compiler error output for details.
```

for what I can see the issue is related to a FlutterFire plugin,
please open the issue in the dedicated [github](https://github.com/FirebaseExtended/flutterfire/issues).

Closing, as this isn't an issue with Flutter itself,
if you disagree please write in the comments and I will reopen it
thank you

**Comment by julisanchez** [comment]
@iapicca I was thinking that Flutter may have trouble compiling plugins. If you see, the output has an error from other plugin.

```
* What went wrong:
Execution failed for task ':app:processDebugResources'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.Workers$ActionFacade
   > Path '/Users/juliansanchez/Documents/Proyectos/go_agenda/build/flutter_statusbarcolor/intermediates/compiled_local_resources/debug/out' is not a readable directory.
```

**Comment by iapicca** [comment]
Hi @julisanchez 
thank you for the clarification,
could you please check if the issue persist with the latest `dev channel`?
thank you

**Comment by julisanchez** [comment]
Hi @iapicca
Yes, the problem persists. I changed the channel and I did a clean but it was not solved.

**Comment by julisanchez** [comment]
I found the error in **"No debuggable processes"**. It was an **ClassNotFoundException** (Didn't find class **"MainActivity"**)
```
2020-04-22 20:46:22.368 9599-9599/com.go.agenda.students E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.go.agenda.students, PID: 9599
    java.lang.RuntimeException: Unable to instantiate activity ComponentInfo{com.go.agenda.students/com.go.agenda.go_agenda.MainActivity}: java.lang.ClassNotFoundException: Didn't find class "com.go.agenda.go_agenda.MainActivity" on path: DexPathList[[zip file "/data/app/com.go.agenda.students-fiv6DqHRKyElzox2wWMlLA==/base.apk"],nativeLibraryDirectories=[/data/app/com.go.agenda.students-fiv6DqHRKyElzox2wWMlLA==/lib/x86, /data/app/com.go.agenda.students-fiv6DqHRKyElzox2wWMlLA==/base.apk!/lib/x86, /system/lib]]
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2843)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3048)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1808)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6669)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
     Caused by: java.lang.ClassNotFoundException: Didn't find class "com.go.agenda.go_agenda.MainActivity" on path: DexPathList[[zip file "/data/app/com.go.agenda.students-fiv6DqHRKyElzox2wWMlLA==/base.apk"],nativeLibraryDirectories=[/data/app/com.go.agenda.students-fiv6DqHRKyElzox2wWMlLA==/lib/x86, /data/app/com.go.agenda.students-fiv6DqHRKyElzox2wWMlLA==/base.apk!/lib/x86, /system/lib]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:134)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at android.app.AppComponentFactory.instantiateActivity(AppComponentFactory.java:69)
        at androidx.core.app.CoreComponentFactory.instantiateActivity(CoreComponentFactory.java:41)
        at android.app.Instrumentation.newActivity(Instrumentation.java:1215)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2831)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3048) 
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78) 
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1808) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:193) 
        at android.app.ActivityThread.main(ActivityThread.java:6669) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858) 
2020-04-22 20:46:23.817 1959-1982/system_process E/BatteryExternalStatsWorker: no controller energy info supplied for wifi
2020-04-22 20:46:26.370 9599-9599/com.go.agenda.students E/CrashlyticsCore: Failed to execute task.
    java.util.concurrent.TimeoutException
        at java.util.concurrent.FutureTask.get(FutureTask.java:206)
        at com.crashlytics.android.core.CrashlyticsBackgroundWorker.submitAndWait(CrashlyticsBackgroundWorker.java:41)
        at com.crashlytics.android.core.CrashlyticsController.handleUncaughtException(CrashlyticsController.java:321)
        at com.crashlytics.android.core.CrashlyticsController$6.onUncaughtException(CrashlyticsController.java:301)
        at com.crashlytics.android.core.CrashlyticsUncaughtExceptionHandler.uncaughtException(CrashlyticsUncaughtExceptionHandler.java:42)
        at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1068)
        at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1063)
        at java.lang.Thread.dispatchUncaughtException(Thread.java:1955)
2020-04-22 20:46:26.405 1609-1609/? E/lowmemorykiller: Error writing /proc/9599/oom_score_adj; errno=22
2020-04-22 20:46:26.502 2688-2882/com.google.android.apps.nexuslauncher E/s.nexuslaunche: No package ID ff found for ID 0xffffffff.
2020-04-22 20:46:26.514 2688-2882/com.google.android.apps.nexuslauncher E/IconLoader: Could not find icon drawable from resource
    android.content.res.Resources$NotFoundException: Resource ID #0xffffffff
        at android.content.res.ResourcesImpl.getValueForDensity(ResourcesImpl.java:225)
        at android.content.res.Resources.getDrawableForDensity(Resources.java:887)
        at android.content.res.Resources.getDrawable(Resources.java:827)
        at com.android.systemui.shared.recents.model.IconLoader.createNewIconForTask(SourceFile:118)
        at com.android.systemui.shared.recents.model.IconLoader.getAndInvalidateIfModified(SourceFile:94)
        at com.android.systemui.shared.recents.model.RecentsTaskLoader.getAndUpdateActivityIcon(SourceFile:325)
        at com.android.systemui.shared.recents.model.RecentsTaskLoadPlan.executePlan(SourceFile:188)
        at com.android.systemui.shared.recents.model.RecentsTaskLoader.loadTasks(SourceFile:173)
        at com.android.quickstep.RecentsModel.onTaskStackChangedBackground(SourceFile:214)
        at com.android.systemui.shared.system.TaskStackChangeListeners.onTaskStackChanged(SourceFile:80)
        at android.app.ITaskStackListener$Stub.onTransact(ITaskStackListener.java:50)
        at android.os.Binder.execTransact(Binder.java:731)
```

**Comment by julisanchez** [comment]
In my case the error occurred while migrating to Kotlin. I found the solution by following the next tutorial to add Kotlin properly to android. 
[https://developer.android.com/kotlin/add-kotlin]()
