### ISSUE TITLE
Row property CrossAxisAlignment.baseline throws exception

### ISSUE THREAD

**Issue by PedroM25** [flutter/flutter#54039]
## Steps to Reproduce

1. Run the following code
```
import 'package:flutter/material.dart';

void main() {
  runApp(MaterialApp(
    home: Home(),
  ));
}

class Home extends StatelessWidget {
  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return Scaffold(
        appBar: AppBar(
          title: Text("App bar title"),
          centerTitle: true,
          backgroundColor: Colors.red[700],
        ),
        body: Row(
          mainAxisAlignment: MainAxisAlignment.spaceEvenly,
          crossAxisAlignment: CrossAxisAlignment.baseline,
          children: <Widget>[
            Text("Hello World"),
            FlatButton(
              onPressed: (){},
              color: Colors.red[700],
              child: Text("Click me!"),
            ),
            Container(
              color: Colors.green[500],
              padding: EdgeInsets.all(30.0),
              child: Text("Inside container"),
            )
          ],
        ),
        floatingActionButton: FloatingActionButton(
          child: Icon(
            Icons.ac_unit,
            color: Colors.white,
            //size: 25,
          ),
          onPressed: (){},
          backgroundColor: Colors.red[700],
        ),
    );
  }
}
```

**Expected results:** 
Wanted to see the widgets in my row with a baseline alignement relative to the cross axis.

**Actual results:** 
![92456421_311222043179057_5902087016702541824_n](https://user-images.githubusercontent.com/40021588/78499332-f7ae4c80-7747-11ea-81cc-b54ac0bdf24b.jpg)

<details>
  <summary>Logs</summary>

**flutter run --verbose**
```
[ +736 ms] I/flutter (17617): ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
[   +5 ms] I/flutter (17617): The following assertion was thrown building Home(dirty):
[   +3 ms] I/flutter (17617): 'package:flutter/src/widgets/basic.dart': Failed assertion: line 3817 pos 15: 'crossAxisAlignment !=
[   +2 ms] I/flutter (17617): CrossAxisAlignment.baseline || textBaseline != null': is not true.
[   +3 ms] I/flutter (17617): 
[   +2 ms] I/flutter (17617): Either the assertion indicates an error in the framework itself, or we should provide substantially
[   +2 ms] I/flutter (17617): more information in this error message to help you determine and fix the underlying cause.
[   +2 ms] I/flutter (17617): In either case, please report this assertion by filing a bug on GitHub:
[   +3 ms] I/flutter (17617):   https://github.com/flutter/flutter/issues/new?template=BUG.md
[   +3 ms] I/flutter (17617): 
[   +4 ms] I/flutter (17617): The relevant error-causing widget was:
[   +6 ms] I/flutter (17617):   Home file:///C:/Users/pedro/AndroidStudioProjects/my_first_futter_app/lib/main.dart:5:11
[   +2 ms] I/flutter (17617): 
[   +2 ms] I/flutter (17617): When the exception was thrown, this was the stack:
[   +2 ms] I/flutter (17617): #2      new Flex (package:flutter/src/widgets/basic.dart:3817:15)
[   +1 ms] I/flutter (17617): #3      new Row (package:flutter/src/widgets/basic.dart:4150:8)
[   +1 ms] I/flutter (17617): #4      Home.build (package:PedroM25/main.dart:19:15)
[   +1 ms] I/flutter (17617): #5      StatelessElement.build (package:flutter/src/widgets/framework.dart:4576:28)
[   +4 ms] I/flutter (17617): #6      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4502:15)
[   +1 ms] I/flutter (17617): #7      Element.rebuild (package:flutter/src/widgets/framework.dart:4218:5)
[   +1 ms] I/flutter (17617): #8      ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4481:5)
[   +1 ms] I/flutter (17617): #9      ComponentElement.mount (package:flutter/src/widgets/framework.dart:4476:5)
[   +1 ms] I/flutter (17617): ...     Normal element mounting (115 frames)
[   +1 ms] I/flutter (17617): #124    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3446:14)
[   +2 ms] I/flutter (17617): #125    MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5947:32)
[   +1 ms] I/flutter (17617): ...     Normal element mounting (247 frames)
[   +2 ms] I/flutter (17617): #372    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3446:14)
[   +2 ms] I/flutter (17617): #373    Element.updateChild (package:flutter/src/widgets/framework.dart:3214:18)
[        ] I/flutter (17617): #374    RenderObjectToWidgetElement._rebuild (package:flutter/src/widgets/binding.dart:1129:16)
[   +1 ms] I/flutter (17617): #375    RenderObjectToWidgetElement.mount (package:flutter/src/widgets/binding.dart:1100:5)
[        ] I/flutter (17617): #376    RenderObjectToWidgetAdapter.attachToRenderTree.<anonymous closure> (package:flutter/src/widgets/binding.dart:1042:17)
[   +1 ms] I/flutter (17617): #377    BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2607:19)
[        ] I/flutter (17617): #378    RenderObjectToWidgetAdapter.attachToRenderTree (package:flutter/src/widgets/binding.dart:1041:13)
[        ] I/flutter (17617): #379    WidgetsBinding.attachRootWidget (package:flutter/src/widgets/binding.dart:922:7)
[        ] I/flutter (17617): #380    WidgetsBinding.scheduleAttachRootWidget.<anonymous closure> (package:flutter/src/widgets/binding.dart:903:7)
[        ] I/flutter (17617): (elided 13 frames from class _AssertionError, class _RawReceivePortImpl, class _Timer, dart:async, and dart:async-patch)
[        ] I/flutter (17617): 
[        ] I/flutter (17617): ════════════════════════════════════════════════════════════════════════════════════════════════════
[ +300 ms] D/DecorView(17617): onWindowFocusChangedFromViewRoot hasFocus: true, DecorView@9c5d0a7[MainActivity]

```

**flutter analyze**

```
Analyzing my_first_futter_app...

   info - Unused import: 'package:PedroM25/main.dart' - test\widget_test.dart:11:8 - unused_import
  error - The function 'MyApp' isn't defined - test\widget_test.dart:16:29 - undefined_function

2 issues found. (ran in 17.1s)

```
**flutter doctor -v**

```
[√] Flutter (Channel master, v1.18.1-pre.9, on Microsoft Windows [Version 10.0.18363.720], locale en-001)
    • Flutter version 1.18.1-pre.9 at D:\FILES\flutter
    • Framework revision f9c58bea49 (9 hours ago), 2020-04-04 21:31:55 -0700
    • Engine revision cb6fc30534
    • Dart version 2.8.0 (build 2.8.0-dev.20.0 80ae6ed91d)


[√] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at C:\Users\pedro\AppData\Local\Android\sdk
    • Platform android-29, build-tools 29.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)
    • All Android licenses accepted.

[√] Android Studio (version 3.6)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 45.0.1
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)

[√] VS Code (version 1.43.2)
    • VS Code at C:\Users\pedro\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.8.1

[√] Connected device (1 available)
    • ONEPLUS A6013 • c97bc254 • android-arm64 • Android 10 (API 29)

• No issues found!

```

</details>

**Comment by PedroM25** [comment]
For thos interested, please refer to [issue #12455 ](https://github.com/flutter/flutter/issues/12455) for more information. This doesn't seem to be a implementation error but rather a poor error message for saying that the textBaseline for Row property needs to be defined when attempting to set the crossAxisAlignment of a Row widget to CrossAxisAlignment.baseline is there is a Text widget child.
