### ISSUE TITLE
google_sign_in login fine in debug mode but error when release mode 

### ISSUE THREAD

**Issue by tbm98** [flutter/flutter#54089]
I log in as (add / remove) calendars and add events. The login application succeeds at debugging but when the build release does not log in. My google cloud project has not yet been verified.
```
2020-04-06 20:36:22.801 25198-25228/? E/flutter: [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: PlatformException(sign_in_failed, com.google.android.gms.common.api.b: 10: , null)
    #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:569)
    #1      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:321)
    <asynchronous suspension>
    #2      MethodChannel.invokeMapMethod (package:flutter/src/services/platform_channel.dart:349)
    #3      MethodChannelGoogleSignIn.signIn (package:google_sign_in_platform_interface/src/method_channel_google_sign_in.dart:45)
    #4      GoogleSignIn._callMethod (package:google_sign_in/google_sign_in.dart:230)
    <asynchronous suspension>
    #5      GoogleSignIn._addMethodCall (package:google_sign_in/google_sign_in.dart:285)
    #6      GoogleSignIn.signIn (package:google_sign_in/google_sign_in.dart:356)
    #7      GoogleSignInHelper.signInWithGoogle (package:studentsocialgooglecalendar/helpers/google_sign_in.dart:17)
    #8      MainController.loginAction (package:studentsocialgooglecalendar/main_controller.dart:44)
    #9      MainController.clicked (package:studentsocialgooglecalendar/main_controller.dart:33)
    #10     SignInButton._signInButton.<anonymous closure> (package:studentsocialgooglecalendar/views/sign_in_button.dart:26)
    #11     _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:706)
    #12     _InkResponseState.build.<anonymous closure> (package:flutter/src/material/ink_well.dart:789)
    #13     GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:182)
    #14     TapGestureRecognizer.handleTapUp (package:flutter/src/gestures/tap.dart:486)
    #15     BaseTapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:282)
    #16     BaseTapGestureRecognizer.handlePrimaryPointer (package:flutter/src/gestures/tap.dart:199)
    #17     PrimaryPointerGestureRecognizer.handleEvent (package:flutter/src/gestures/recognizer.dart:467)
    #18     PointerRouter._dispatch (package:flutter/src/gestures/pointer_router.dart:76)
    #19     PointerRouter._dispatchEventToRoutes.<anonymous closure> (package:flutter/src/gestures/pointer_router.dart:117)
    #20     _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:379)
    #21     PointerRouter._dispatchEventToRoutes (package:flutter/src/gestures/pointer_router.dart:115)
    #22     PointerRouter.route (package:flutter/src/gestures/pointer_router.dart:101)
    #23     GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:218)
    #24     GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:198)
    #25     GestureBinding._handlePointerEvent (package:flutter/src/gestures/binding.dart:156)
    #26     GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:102)
    #27     GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:86)
    #28     _rootRunUnary (dart:async/zone.dart:1138)
    #29     _CustomZone.runUnary (dart:async/zone.dart:1031)
    #30     _CustomZone.runUnaryGuarded (dart:async/zone.dart:933)
    #31     _invoke1 (dart:ui/hooks.dart:273)
    #32     _dispatchPointerDataPacket (dart:ui/hooks.dart:182)
```

**Comment by tbm98** [comment]
I added sha-1 of key release to firebase and it worked.

**Comment by VladyslavBondarenko** [comment]
@tbm98 
I'm glad that it's solved, closing
