### ISSUE TITLE
Cupertino route/transition should block touch events

### ISSUE THREAD

**Issue by dsrenesanse** [flutter/flutter#54090]
I think block any touch events during Cupertino transition is reasonable.

**Comment by VladyslavBondarenko** [comment]
Hi @Renesanse 
could you describe and provide a minimal complete code sample to the cases when it is reasonable?

**Comment by Renesanse** [comment]
> Hi @Renesanse
> could you describe and provide a minimal complete code sample to the cases when it is reasonable?

Navigator.of(context).push(CupertinoPageRoute(builder: (_) => Container()));

**Comment by VladyslavBondarenko** [comment]
@Renesanse 
it doesn't answer the question. Why do you think it is reasonable?

**Comment by Renesanse** [comment]
Because handling touch events during transitions and animations is bad practice. Users will be confused about actions in the app cause miss clicking happens during screen transitions. I am very
surprised that you are don't know it and I need to explain to you why this is necessary.

**Comment by chunhtai** [comment]
@xster  This is not actually blocking anything, it only blocks when the route is offstage or in the middle of back swipe

**Comment by willlockwood** [comment]
Just letting folks know that I'm putting up a change for this soon 👍🏻

**Comment by chunhtai** [comment]
https://github.com/flutter/flutter/pull/104520
pr is reverted

**Comment by willlockwood** [comment]
Huh, @chunhtai what was the issue here? Anything I can help with?

**Comment by chunhtai** [comment]
I have not investigated into it but this is the more detailed stacktrace
```
══╡ EXCEPTION CAUGHT BY FOUNDATION LIBRARY ╞════════════════════════════════════════════════════════
The following assertion was thrown while dispatching notifications for ValueNotifier<bool>:
setState() or markNeedsBuild() called during build.
This AnimatedBuilder widget cannot be marked as needing to build because the framework is already in
the process of building widgets. A widget can be marked as needing to be built during the build
phase only if one of its ancestors is currently building. This exception is allowed because the
framework builds parent widgets before children, which means a dirty descendant will always be
built. Otherwise, the framework might not visit this widget during this build phase.
The widget on which setState() or markNeedsBuild() was called was:
  AnimatedBuilder
The widget which was currently being built when the offending call was made was:
  Builder

When the exception was thrown, this was the stack:
#0      Element.markNeedsBuild.<anonymous closure> (package:[flutter/src/widgets/framework.dart:4477](https://cs.corp.google.com/piper///depot/google3/flutter/src/widgets/framework.dart?l=4477&ws=tap-presubmit-rerun-server/824781&snapshot=5):11)
#1      Element.markNeedsBuild (package:[flutter/src/widgets/framework.dart:4492](https://cs.corp.google.com/piper///depot/google3/flutter/src/widgets/framework.dart?l=4492&ws=tap-presubmit-rerun-server/824781&snapshot=5):6)
#2      State.setState (package:[flutter/src/widgets/framework.dart:1129](https://cs.corp.google.com/piper///depot/google3/flutter/src/widgets/framework.dart?l=1129&ws=tap-presubmit-rerun-server/824781&snapshot=5):15)
#3      _AnimatedState._handleChange (package:[flutter/src/widgets/transitions.dart:127](https://cs.corp.google.com/piper///depot/google3/flutter/src/widgets/transitions.dart?l=127&ws=tap-presubmit-rerun-server/824781&snapshot=5):5)
#4      ChangeNotifier.notifyListeners (package:[flutter/src/foundation/change_notifier.dart:341](https://cs.corp.google.com/piper///depot/google3/flutter/src/foundation/change_notifier.dart?l=341&ws=tap-presubmit-rerun-server/824781&snapshot=5):24)
#5      ValueNotifier.value= (package:[flutter/src/foundation/change_notifier.dart:445](https://cs.corp.google.com/piper///depot/google3/flutter/src/foundation/change_notifier.dart?l=445&ws=tap-presubmit-rerun-server/824781&snapshot=5):5)
#6      ModalRoute._maybeUpdateIgnorePointer (package:[flutter/src/widgets/routes.dart:1429](https://cs.corp.google.com/piper///depot/google3/flutter/src/widgets/routes.dart?l=1429&ws=tap-presubmit-rerun-server/824781&snapshot=5):28)
#7      ModalRoute._handleAnimationStatusChanged (package:[flutter/src/widgets/routes.dart:1186](https://cs.corp.google.com/piper///depot/google3/flutter/src/widgets/routes.dart?l=1186&ws=tap-presubmit-rerun-server/824781&snapshot=5):5)
#8      AnimationLocalStatusListenersMixin.notifyStatusListeners (package:[flutter/src/animation/listener_helpers.dart:233](https://cs.corp.google.com/piper///depot/google3/flutter/src/animation/listener_helpers.dart?l=233&ws=tap-presubmit-rerun-server/824781&snapshot=5):19)
#9      AnimationLocalStatusListenersMixin.notifyStatusListeners (package:[flutter/src/animation/listener_helpers.dart:233](https://cs.corp.google.com/piper///depot/google3/flutter/src/animation/listener_helpers.dart?l=233&ws=tap-presubmit-rerun-server/824781&snapshot=5):19)
#10     AnimationLocalStatusListenersMixin.notifyStatusListeners (package:[flutter/src/animation/listener_helpers.dart:233](https://cs.corp.google.com/piper///depot/google3/flutter/src/animation/listener_helpers.dart?l=233&ws=tap-presubmit-rerun-server/824781&snapshot=5):19)
#11     CompoundAnimation._maybeNotifyStatusListeners (package:[flutter/src/animation/animations.dart:677](https://cs.corp.google.com/piper///depot/google3/flutter/src/animation/animations.dart?l=677&ws=tap-presubmit-rerun-server/824781&snapshot=5):7)
#12     AnimationLocalStatusListenersMixin.notifyStatusListeners (package:[flutter/src/animation/listener_helpers.dart:233](https://cs.corp.google.com/piper///depot/google3/flutter/src/animation/listener_helpers.dart?l=233&ws=tap-presubmit-rerun-server/824781&snapshot=5):19)
#13     AnimationController._checkStatusChanged (package:[flutter/src/animation/animation_controller.dart:815](https://cs.corp.google.com/piper///depot/google3/flutter/src/animation/animation_controller.dart?l=815&ws=tap-presubmit-rerun-server/824781&snapshot=5):7)
#14     AnimationController._animateToInternal (package:[flutter/src/animation/animation_controller.dart:607](https://cs.corp.google.com/piper///depot/google3/flutter/src/animation/animation_controller.dart?l=607&ws=tap-presubmit-rerun-server/824781&snapshot=5):7)
#15     AnimationController.reverse (package:[flutter/src/animation/animation_controller.dart:494](https://cs.corp.google.com/piper///depot/google3/flutter/src/animation/animation_controller.dart?l=494&ws=tap-presubmit-rerun-server/824781&snapshot=5):12)
#16     TransitionRoute.didPop (package:[flutter/src/widgets/routes.dart:262](https://cs.corp.google.com/piper///depot/google3/flutter/src/widgets/routes.dart?l=262&ws=tap-presubmit-rerun-server/824781&snapshot=5):18)
#17     LocalHistoryRoute.didPop (package:[flutter/src/widgets/routes.dart:682](https://cs.corp.google.com/piper///depot/google3/flutter/src/widgets/routes.dart?l=682&ws=tap-presubmit-rerun-server/824781&snapshot=5):18)
#18     _RouteEntry.handlePop (package:[flutter/src/widgets/navigator.dart:2888](https://cs.corp.google.com/piper///depot/google3/flutter/src/widgets/navigator.dart?l=2888&ws=tap-presubmit-rerun-server/824781&snapshot=5):16)
#19     NavigatorState._flushHistoryUpdates (package:[flutter/src/widgets/navigator.dart:3860](https://cs.corp.google.com/piper///depot/google3/flutter/src/widgets/navigator.dart?l=3860&ws=tap-presubmit-rerun-server/824781&snapshot=5):22)
#20     NavigatorState.pop (package:[flutter/src/widgets/navigator.dart:4916](https://cs.corp.google.com/piper///depot/google3/flutter/src/widgets/navigator.dart?l=4916&ws=tap-presubmit-rerun-server/824781&snapshot=5):7)
```

**Comment by machinescream** [comment]
I have implemented couple of months ago this route, you can take a look at this and try to replicate its behaviour. https://github.com/machinescream/right/blob/main/lib/src/r_route.dart

**Comment by MitchellGoodwin** [comment]
It looks like on the iOS 26 beta, touch events are no longer blocked:

https://x.com/xezrunner/status/1932440129739636945?t=Ndr44yCGNQjfNq8w9l4xvw&s=19

Leaving this issue open for now as it's still in beta and it might be regressed back to the old behavior, but this issue may no longer be relevant.
