### ISSUE TITLE
run --release is not working

### ISSUE THREAD

**Issue by dragostis** [flutter/flutter#5409]
I'm getting:

```
Exception thrown during pause
android.os.DeadObjectException
 	at android.os.BinderProxy.transactNative(Native Method)
 	at android.os.BinderProxy.transact(Binder.java:496)
 	at android.app.ApplicationThreadProxy.schedulePauseActivity(ApplicationThreadNative.java:704)
 	at com.android.server.am.ActivityStack.startPausingLocked(ActivityStack.java:832)
	at com.android.server.am.ActivityStack.finishActivityLocked(ActivityStack.java:2821)
	at com.android.server.am.ActivityStack.finishTopRunningActivityLocked(ActivityStack.java:2678)
 	at com.android.server.am.ActivityStackSupervisor.finishTopRunningActivityLocked(ActivityStackSupervisor.java:2525)
	at com.android.server.am.ActivityManagerService.handleAppCrashLocked(ActivityManagerService.java:11783)
 	at com.android.server.am.ActivityManagerService.makeAppCrashingLocked(ActivityManagerService.java:11655)
 	at com.android.server.am.ActivityManagerService.crashApplication(ActivityManagerService.java:12364)
 	at com.android.server.am.ActivityManagerService.handleApplicationCrashInner(ActivityManagerService.java:11875)
 	at com.android.server.am.NativeCrashListener$NativeCrashReporter.run(NativeCrashListener.java:86)

```

@jason-simmons

**Comment by sethladd** [comment]
Is there a test that can catch this?

**Comment by dragostis** [comment]
@sethladd Apparently not. We should definitely test whether `--release` works. :smiley:

**Comment by eseidelGoogle** [comment]
I believe @chinmaygarde is about to do an engine roll to fix all release builds including this one?

**Comment by Hixie** [comment]
this is fixed now. i'll file a separate bug about testing it.
