### ISSUE TITLE
Target debug_universal_framework failed: Exception: Unsupported iOS arch name "i386" build failed

### ISSUE THREAD

**Issue by jmagman** [flutter/flutter#54146]
I tried running on a iPhone 5 iOS 10.3 simulator in Xcode, and `debug_universal_framework` fails.

Note the `-dIosArchs=i386`:
```
Showing Recent Messages
...

Showing Recent Messages
♦ /Users/m/Projects/flutter/bin/flutter --verbose assemble --output=/Users/m/Projects/test_create/ios/Flutter/ -dTargetPlatform=ios -dTargetFile=/Users/m/Projects/test_create/lib/main.dart -dBuildMode=debug -dIosArchs=i386 -dSplitDebugInfo= -dTreeShakeIcons=false -dTrackWidgetCreation=true -dDartObfuscation=false -dEnableBitcode= -dDartDefines= -dExtraFrontEndOptions= debug_ios_bundle_flutter_assets


[+1570 ms] debug_universal_framework: Starting due to {InvalidatedReason.inputChanged}
...
[   +6 ms] Target debug_universal_framework failed: Exception: Unsupported iOS arch name "i386"
build failed.

#0      throwToolExit (package:flutter_tools/src/base/common.dart:14:3)
#1      AssembleCommand.runCommand (package:flutter_tools/src/commands/assemble.dart:197:7)
```
```
$ flutter doctor -v
[✓] Flutter (Channel unknown, v1.18.1-pre.14, on Mac OS X 10.15.4 19E266, locale en-US)
    • Flutter version 1.18.1-pre.14 at /Users/m/Projects/flutter
    • Framework revision 0a8b590943 (18 minutes ago), 2020-04-06 14:54:52 -0700
    • Engine revision 9b8dcc7ecf
    • Dart version 2.8.0 (build 2.8.0-dev.20.0 05103dfe5a)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/m/Library/Android/sdk
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.4)
    • Xcode at /Users/m/Applications/Xcode-11-4.app/Contents/Developer
    • Xcode 11.4, Build version 11E146
    • CocoaPods version 1.9.0

[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 44.0.2
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)

[✓] IntelliJ IDEA Community Edition (version 2019.2.4)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 41.1.3
    • Dart plugin version 192.7402

[✓] VS Code (version 1.43.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.6.0

[✓] Connected device (2 available)
    • iPhone 8 Plus • D919CFD4-7DB9-4CE3-B3A1-8A56B33E9901 • ios • com.apple.CoreSimulator.SimRuntime.iOS-13-4 (simulator)
    • iPhone 5 10_3 • C9076A75-FF73-408F-850B-8034CB75CA03 • ios • com.apple.CoreSimulator.SimRuntime.iOS-10-3 (simulator)
```

**Comment by jmagman** [comment]
Oh right, only x86_64 simulators are supported, Flutter doesn't even have a i386 slice.

**Comment by jmagman** [comment]
Let's fail earlier with a better message that indicates "32-bit simulators are not supported."
