### ISSUE TITLE
platform exception with firebase google_sign_in(Unhandled Exception: PlatformException(ERROR_INTERNAL_ERROR)

### ISSUE THREAD

**Issue by sumitrvi** [flutter/flutter#54263]
1. Run `flutter create bug`.

```
All done!
[✓] Flutter: is fully installed. (Channel unknown, v1.12.13+hotfix.8, on Mac OS X 10.15 19A583, locale en-IN)
[✓] Android toolchain - develop for Android devices: is fully installed. (Android SDK version 28.0.3)
[✓] Xcode - develop for iOS and macOS: is fully installed. (Xcode 11.1)
[✓] Android Studio: is fully installed. (version 3.3)
[✓] VS Code: is fully installed. (version 1.43.2)
[✓] Connected device: is fully installed. (1 available)
```
flutter run --verbose

```
 [DEVICE LOG] 2020-04-08 13:32:25.956959+0530  localhost Runner[36946]: (libboringssl.dylib) [com.apple.network.boringssl:BoringSSL]
boringssl_context_handle_warning_alert(1894) [C8.1:2][0x7fedf176c800] write alert, level: warning, description: close notify
[        ] [DEVICE LOG] 2020-04-08 13:32:25.957149+0530  localhost Runner[36946]: (libboringssl.dylib) [com.apple.network.boringssl:BoringSSL]
boringssl_session_disconnect(539) [C8.1:2][0x7fedf176c800] SSL_shutdown 0
[        ] [DEVICE LOG] 2020-04-08 13:32:25.957329+0530  localhost Runner[36946]: (libnetwork.dylib) [com.apple.network:] nw_flow_disconnected [C8.1
2404:6800:4002:80c::200a.443 cancelled socket-flow ((null))] Output protocol disconnected
[        ] [DEVICE LOG] 2020-04-08 13:32:25.957840+0530  localhost Runner[36946]: (libnetwork.dylib) [com.apple.network:]
nw_connection_report_state_with_handler_on_nw_queue [C8] reporting state cancelled
[        ] [DEVICE LOG] 2020-04-08 13:32:25.957997+0530  localhost Runner[36946]: (CFNetwork) [com.apple.CFNetwork:Coalescing] removing all entries
config 0x600000f57600
[        ] [DEVICE LOG] 2020-04-08 13:32:25.958179+0530  localhost Runner[36946]: (libboringssl.dylib) [com.apple.network.boringssl:BoringSSL]
nw_protocol_boringssl_remove_input_handler(1010) [C8.1:2][0x7fedf176c800] nw_protocol_boringssl_remove_input_handler forced true
[        ] [DEVICE LOG] 2020-04-08 13:32:25.959368+0530  localhost Runner[36946]: (libboringssl.dylib) [com.apple.network.boringssl:BoringSSL]
nw_protocol_boringssl_remove_input_handler(1028) [C8.1:2][0x7fedf176c800] Transferring nw_protocol_boringssl_t handle back into ARC for autorelease
[        ] [DEVICE LOG] 2020-04-08 13:32:25.960141+0530  localhost Runner[36946]: (Flutter) [VERBOSE-2:ui_dart_state.cc(157)] Unhandled Exception:
PlatformException(ERROR_INTERNAL_ERROR, An internal error has occurred, print and inspect the error details for more information., null)
[        ] [DEVICE LOG] #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:569:7)
[        ] [DEVICE LOG] #1      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:321:33)
[        ] [DEVICE LOG] <asynchronous suspension>
[        ] [DEVICE LOG] #2      MethodChannel.invokeMapMethod (package:flutter/src/services/platform_channel.dart:349:48)
[        ] [DEVICE LOG] #3      MethodChannelFirebaseAuth.signInWithCredential
(package:firebase_auth_platform_interface/src/method_channel_firebase_auth.dart:161:23)
[        ] [DEVICE LOG] #4      FirebaseAuth.signInWithCredential (package:firebase_auth/src/firebase_auth.dart:208:10)
[        ] [DEVICE LOG] #5      _AsyncAwaitCompleter.start (dart:async-patch/async_patch.dart:45:6)
[        ] [DEVICE LOG] #6      FirebaseAuth.signInWithCredential (package:firebase_auth/src/firebase_auth.dart:205:42)
[        ] [DEVICE LOG] #7      _SigninScreenState.socialLogin (package:down_beatflutterproject/screens/signinscreen.<…>
[        ] [VERBOSE-2:ui_dart_state.cc(157)] Unhandled Exception: PlatformException(ERROR_INTERNAL_ERROR, An internal error has occurred, print and
inspect the error details for more information., null)
[        ] #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:569:7)
[        ] #1      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:321:33)
[        ] <asynchronous suspension>
[        ] #2      MethodChannel.invokeMapMethod (package:flutter/src/services/platform_channel.dart:349:48)
[        ] #3      MethodChannelFirebaseAuth.signInWithCredential
(package:firebase_auth_platform_interface/src/method_channel_firebase_auth.dart:161:23)
[        ] #4      FirebaseAuth.signInWithCredential (package:firebase_auth/src/firebase_auth.dart:208:10)
[        ] #5      _AsyncAwaitCompleter.start (dart:async-patch/async_patch.dart:45:6)
[        ] #6      FirebaseAuth.signInWithCredential (package:firebase_auth/src/firebase_auth.dart:205:42)
[        ] #7      _SigninScreenState.socialLogin (package:down_beatflutterproject/screens/signinscreen.<…>
```

flutter doctor -v

```
[✓] Flutter (Channel stable, v1.12.13+hotfix.8, on Mac OS X 10.15 19A583, locale en-IN)
    • Flutter version 1.12.13+hotfix.8 at /Users/theninehertz/Desktop/hybrid/sumit/fluttersdk/flutter
    • Framework revision 0b8abb4724 (8 weeks ago), 2020-02-11 11:44:36 -0800
    • Engine revision e1e6ced81d
    • Dart version 2.7.0

 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/theninehertz/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.1)
    • Xcode at /Applications/Xcode 11.1.app/Contents/Developer
    • Xcode 11.1, Build version 11A1027
    • CocoaPods version 1.8.4

[✓] Android Studio (version 3.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 34.0.1
    • Dart plugin version 182.5215
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)

[✓] VS Code (version 1.43.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.9.0

[✓] Connected device (1 available)
    • iPhone 7 • 9EED1588-2FE1-4F78-8148-F002D7B43838 • ios • com.apple.CoreSimulator.SimRuntime.iOS-13-1 (simulator)
```

**Comment by VladyslavBondarenko** [comment]
Hi @sumitrvi 
In stack trace I see the error is related to the firebase_auth plugin, 
```
#4      FirebaseAuth.signInWithCredential (package:firebase_auth/src/firebase_auth.dart:208:10)
```
please open the issue in the plugin's repository https://github.com/FirebaseExtended/flutterfire
Closing, as this isn't an issue with Flutter itself,
if you disagree please write in the comments and I will reopen it
Thank you
