### ISSUE TITLE
[cocoon] Backend APIs are consuming the entire github API quota

### ISSUE THREAD

**Issue by godofredoc** [flutter/flutter#54293]
```
GitHub Error: API rate limit exceeded for user ID 52682268.
#0      GitHub.handleStatusCode (package:github/src/common/github.dart:423:5)
#1      GitHub.request (package:github/src/common/github.dart:368:7)
<asynchronous suspension>
#2      PaginationHelper.fetchStreamed (package:github/src/common/util/pagination.dart:35:33)
<asynchronous suspension>
#3      PaginationHelper.jsonObjects (package:github/src/common/util/pagination.dart:97:34)
<asynchronous suspension>
#4      PaginationHelper.objects (package:github/src/common/util/pagination.dart:119:12)
#5      RepositoriesService.listBranches (package:github/src/common/repos_service.dart:250:38)
#6      getBranches (package:cocoon_service/src/foundation/utils.dart:79:57)
<asynchronous suspension>
#7      GetBranches.get (package:cocoon_service/src/request_handlers/get_branches.dart:36:43)
#8      CacheRequestHandler.getBodyBytesFromDelegate (package:cocoon_service/src/request_handling/cache_request_handler.dart:70:38)
#9      CacheRequestHandler.get.<anonymous closure> (package:cocoon_service/src/request_handling/cache_request_handler.dart:60:23)
#10     CacheService.getOrCreate (package:cocoon_service/src/service/cache_service.dart:81:29)
<asynchronous suspension>
#11     CacheRequestHandler.get (package:cocoon_service/src/request_handling/cache_request_handler.dart:57:50)
#12     RequestHandler.service.<anonymous closure> (package:cocoon_service/src/request_handling/request_handler.dart:46:28)
#13     _rootRun (dart:async/zone.dart:1126:13)
#14     _CustomZone.run (dart:async/zone.dart:1023:19)
#15     _runZoned (dart:async/zone.dart:1518:10)
#16     runZoned (dart:async/zone.dart:1465:12)
#17     RequestHandler.service (package:cocoon_service/src/request_handling/request_handler.dart:39:12)
#18     main.<anonymous closure>.<anonymous closure> (file:///app/bin/server.dart:83:23)
#19     runAppEngine.<anonymous closure> (package:appengine/appengine.dart:80:12)
#20     runAppEngine.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:appengine/src/appengine_internal.dart:59:18)
#21     _ServiceScope._fork.<anonymous closure> (package:gcloud/service_scope.dart:209:19)
#22     _rootRun (dart:async/zone.dart:1126:13)
#23     _CustomZone.run (dart:async/zone.dart:1023:19)
#24     _runZoned (dart:async/zone.dart:1518:10)
#25     runZoned (dart:async/zone.dart:1502:12)
#26     _ServiceScope._fork (package:gcloud/service_scope.dart:208:12)
#27     fork (package:gcloud/service_scope.dart:104:30)
#28     runAppEngine.<anonymous closure>.<anonymous closure> (package:appengine/src/appengine_internal.dart:57:9)
#29     AppEngineHttpServer.run.<anonymous closure>.<anonymous closure> (package:appengine/src/server/server.dart:83:16)
#30     _rootRunUnary (dart:async/zone.dart:1134:38)
#31     _CustomZone.runUnary (dart:async/zone.dart:1031:19)
#32     _CustomZone.runUnaryGuarded (dart:async/zone.dart:933:7)
#33     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:338:11)
#34     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:265:7)
#35     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:766:19)
#36     _StreamController._add (dart:async/stream_controller.dart:642:7)
#37     _StreamController.add (dart:async/stream_controller.dart:588:5)
#38     _HttpServer._handleRequest (dart:_http/http_impl.dart:2828:19)
#39     new _HttpConnection.<anonymous closure> (dart:_http/http_impl.dart:2586:19)
#40     _rootRunUnary (dart:async/zone.dart:1134:38)
#41     _CustomZone.runUnary (dart:async/zone.dart:1031:19)
#42     _CustomZone.runUnaryGuarded (dart:async/zone.dart:933:7)
#43     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:338:11)
#44     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:265:7)
#45     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:766:19)
#46     _StreamController._add (dart:async/stream_controller.dart:642:7)
#47     _StreamController.add (dart:async/stream_controller.dart:588:5)
#48     _HttpParser._headersEnd (dart:_http/http_parser.dart:374:19)
#49     _HttpParser._doParse (dart:_http/http_parser.dart:703:15)
#50     _HttpParser._parse (dart:_http/http_parser.dart:320:7)
#51     _HttpParser._onData (dart:_http/http_parser.dart:812:5)
#52     _rootRunUnary (dart:async/zone.dart:1134:38)
#53     _CustomZone.runUnary (dart:async/zone.dart:1031:19)
#54     _CustomZone.runUnaryGuarded (dart:async/zone.dart:933:7)
#55     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:338:11)
#56     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:265:7)
#57     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:766:19)
#58     _StreamController._add (dart:async/stream_controller.dart:642:7)
#59     _StreamController.add (dart:async/stream_controller.dart:588:5)
#60     _Socket._onData (dart:io-patch/socket_patch.dart:1851:41)
#61     _rootRunUnary (dart:async/zone.dart:1138:13)
#62     _CustomZone.runUnary (dart:async/zone.dart:1031:19)
#63     _CustomZone.runUnaryGuarded (dart:async/zone.dart:933:7)
#64     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:338:11)
#65     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:265:7)
#66     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:766:19)
#67     _StreamController._add (dart:async/stream_controller.dart:642:7)
#68     _StreamController.add (dart:async/stream_controller.dart:588:5)
#69     new _RawSocket.<anonymous closure> (dart:io-patch/socket_patch.dart:1399:33)
#70     _NativeSocket.issueReadEvent.issue (dart:io-patch/socket_patch.dart:919:14)
#71     _microtaskLoop (dart:async/schedule_microtask.dart:43:21)
#72     _startMicrotaskLoop (dart:async/schedule_microtask.dart:52:5)
#73     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
#74     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:175:5)
```

**Comment by godofredoc** [comment]
Let's keep it open until we get the quota back

**Comment by keyonghan** [comment]
All APIs are working through. Removing TODAY label.

**Comment by godofredoc** [comment]
This is not happening anymore.
