### ISSUE TITLE
Engine Compilation Error: ninja -C out/android_debug_unopt_x86 fails with error "TypeError: a bytes-like object is required, not 'str'"

### ISSUE THREAD

**Issue by krishnakeshan** [flutter/flutter#54350]
The `ninja -C out/android_debug_unopt_x86` fails with the error "TypeError: a bytes-like object is required, not 'str'".

# Logs
```
ninja: Entering directory `out/android_debug_unopt_x86'
[399/3760] ACTION //flutter/shell/platform/a...ll_java(//build/toolchain/android:clang_x86)
FAILED: gen/flutter/shell/platform/android/flutter_shell_java.d flutter_embedding_debug.jar flutter_embedding_debug.jar.md5.stamp flutter_embedding_debug-sources.jar flutter_embedding_debug-sources.jar.md5.stamp 
python ../../build/android/gyp/javac.py --depfile=gen/flutter/shell/platform/android/flutter_shell_java.d --jar-path=flutter_embedding_debug.jar --jar-source-path=flutter_embedding_debug-sources.jar --jar-source-base-dir=/home/krishna/Desktop/flutter_dev/engine/src/flutter/shell/platform/android --classpath=\[\"../../third_party/android_tools/sdk/platforms/android-29/android.jar\",\ \"../../third_party/android_embedding_dependencies/lib/guava-27.0.1-jre.jar\",\ \"../../third_party/android_embedding_dependencies/lib/icu4j-53.1.jar\",\ \"../../third_party/android_embedding_dependencies/lib/hamcrest-library-1.3.jar\",\ \"../../third_party/android_embedding_dependencies/lib/junit-4.13.jar\",\ \"../../third_party/android_embedding_dependencies/lib/utils-4.3.jar\",\ \"../../third_party/android_embedding_dependencies/lib/savedstate-1.0.0.jar\",\ \"../../third_party/android_embedding_dependencies/lib/error_prone_annotations-2.2.0.jar\",\ \"../../third_party/android_embedding_dependencies/lib/support-annotations-28.0.0.jar\",\ \"../../third_party/android_embedding_dependencies/lib/annotation-1.0.0.jar\",\ \"../../third_party/android_embedding_dependencies/lib/ant-launcher-1.8.0.jar\",\ \"../../third_party/android_embedding_dependencies/lib/maven-project-2.2.1.jar\",\ \"../../third_party/android_embedding_dependencies/lib/activity-1.0.0.jar\",\ \"../../third_party/android_embedding_dependencies/lib/android-all-4.1.2_r1-robolectric-r1.jar\",\ \"../../third_party/android_embedding_dependencies/lib/lifecycle-runtime-2.2.0.jar\",\ \"../../third_party/android_embedding_dependencies/lib/maven-profile-2.2.1.jar\",\ \"../../third_party/android_embedding_dependencies/lib/maven-ant-tasks-2.1.3.jar\",\ \"../../third_party/android_embedding_dependencies/lib/plexus-interpolation-1.11.jar\",\ \"../../third_party/android_embedding_dependencies/lib/asm-commons-7.0.jar\",\ \"../../third_party/android_embedding_dependencies/lib/junit-4.3.jar\",\ \"../../third_party/android_embedding_dependencies/lib/listenablefuture-9999.0-empty-to-avoid-conflict-with-guava.jar\",\ \"../../third_party/android_embedding_dependencies/lib/animal-sniffer-annotations-1.17.jar\",\ \"../../third_party/android_embedding_dependencies/lib/sqlite4java-0.282.jar\",\ \"../../third_party/android_embedding_dependencies/lib/lifecycle-viewmodel-2.1.0.jar\",\ \"../../third_party/android_embedding_dependencies/lib/asm-util-7.0.jar\",\ \"../../third_party/android_embedding_dependencies/lib/shadowapi-4.3.jar\",\ \"../../third_party/android_embedding_dependencies/lib/maven-artifact-2.2.1.jar\",\ \"../../third_party/android_embedding_dependencies/lib/asm-analysis-7.0.jar\",\ \"../../third_party/android_embedding_dependencies/lib/maven-artifact-manager-2.2.1.jar\",\ \"../../third_party/android_embedding_dependencies/lib/resources-4.3.jar\",\ \"../../third_party/android_embedding_dependencies/lib/plugins-maven-dependency-resolver-4.3.jar\",\ \"../../third_party/android_embedding_dependencies/lib/j2objc-annotations-1.1.jar\",\ \"../../third_party/android_embedding_dependencies/lib/xercesMinimal-1.9.6.2.jar\",\ \"../../third_party/android_embedding_dependencies/lib/monitor-1.2.0.jar\",\ \"../../third_party/android_embedding_dependencies/lib/protobuf-java-2.6.1.jar\",\ \"../../third_party/android_embedding_dependencies/lib/bcprov-jdk15on-1.52.jar\",\ \"../../third_party/android_embedding_dependencies/lib/wagon-file-1.0-beta-6.jar\",\ \"../../third_party/android_embedding_dependencies/lib/maven-plugin-registry-2.2.1.jar\",\ \"../../third_party/android_embedding_dependencies/lib/mockito-all-1.10.19.jar\",\ \"../../third_party/android_embedding_dependencies/lib/asm-tree-7.0.jar\",\ \"../../third_party/android_embedding_dependencies/lib/versionedparcelable-1.1.0.jar\",\ \"../../third_party/android_embedding_dependencies/lib/ant-1.8.0.jar\",\ \"../../third_party/android_embedding_dependencies/lib/collection-1.1.0.jar\",\ \"../../third_party/android_embedding_dependencies/lib/maven-settings-2.2.1.jar\",\ \"../../third_party/android_embedding_dependencies/lib/jsr305-3.0.2.jar\",\ \"../../third_party/android_embedding_dependencies/lib/lifecycle-common-2.2.0.jar\",\ \"../../third_party/android_embedding_dependencies/lib/failureaccess-1.0.1.jar\",\ \"../../third_party/android_embedding_dependencies/lib/robolectric-4.3.jar\",\ \"../../third_party/android_embedding_dependencies/lib/core-runtime-2.0.0.jar\",\ \"../../third_party/android_embedding_dependencies/lib/annotations-4.3.jar\",\ \"../../third_party/android_embedding_dependencies/lib/auto-common-0.8.jar\",\ \"../../third_party/android_embedding_dependencies/lib/loader-1.0.0.jar\",\ \"../../third_party/android_embedding_dependencies/lib/maven-error-diagnostics-2.2.1.jar\",\ \"../../third_party/android_embedding_dependencies/lib/lifecycle-livedata-2.0.0.jar\",\ \"../../third_party/android_embedding_dependencies/lib/classworlds-1.1-alpha-2.jar\",\ \"../../third_party/android_embedding_dependencies/lib/shadows-framework-4.3.jar\",\ \"../../third_party/android_embedding_dependencies/lib/viewpager-1.0.0.jar\",\ \"../../third_party/android_embedding_dependencies/lib/customview-1.0.0.jar\",\ \"../../third_party/android_embedding_dependencies/lib/wagon-provider-api-1.0-beta-6.jar\",\ \"../../third_party/android_embedding_dependencies/lib/core-1.1.0.jar\",\ \"../../third_party/android_embedding_dependencies/lib/lifecycle-livedata-core-2.0.0.jar\",\ \"../../third_party/android_embedding_dependencies/lib/plexus-container-default-1.0-alpha-9-stable-1.jar\",\ \"../../third_party/android_embedding_dependencies/lib/wagon-http-shared-1.0-beta-6.jar\",\ \"../../third_party/android_embedding_dependencies/lib/maven-model-2.2.1.jar\",\ \"../../third_party/android_embedding_dependencies/lib/nekohtml-1.9.6.2.jar\",\ \"../../third_party/android_embedding_dependencies/lib/checker-qual-2.5.2.jar\",\ \"../../third_party/android_embedding_dependencies/lib/javax.inject-1.jar\",\ \"../../third_party/android_embedding_dependencies/lib/android-all-8.1.0-robolectric-4611349.jar\",\ \"../../third_party/android_embedding_dependencies/lib/wagon-http-lightweight-1.0-beta-6.jar\",\ \"../../third_party/android_embedding_dependencies/lib/sandbox-4.3.jar\",\ \"../../third_party/android_embedding_dependencies/lib/annotation-1.1.0.jar\",\ \"../../third_party/android_embedding_dependencies/lib/lifecycle-common-java8-2.2.0.jar\",\ \"../../third_party/android_embedding_dependencies/lib/core-common-2.1.0.jar\",\ \"../../third_party/android_embedding_dependencies/lib/utils-reflector-4.3.jar\",\ \"../../third_party/android_embedding_dependencies/lib/backport-util-concurrent-3.1.jar\",\ \"../../third_party/android_embedding_dependencies/lib/asm-7.0.jar\",\ \"../../third_party/android_embedding_dependencies/lib/accessibility-test-framework-2.1.jar\",\ \"../../third_party/android_embedding_dependencies/lib/fragment-1.1.0.jar\",\ \"../../third_party/android_embedding_dependencies/lib/javax.annotation-api-1.3.2.jar\",\ \"../../third_party/android_embedding_dependencies/lib/maven-repository-metadata-2.2.1.jar\",\ \"../../third_party/android_embedding_dependencies/lib/pluginapi-4.3.jar\",\ \"../../third_party/android_embedding_dependencies/lib/auto-service-1.0-rc4.jar\",\ \"../../third_party/android_embedding_dependencies/lib/plexus-utils-1.5.15.jar\"\] --bootclasspath=../../third_party/android_tools/sdk/platforms/android-29/android.jar ../../flutter/shell/platform/android/io/flutter/Log.java ../../flutter/shell/platform/android/io/flutter/app/FlutterActivity.java ../../flutter/shell/platform/android/io/flutter/app/FlutterActivityDelegate.java ../../flutter/shell/platform/android/io/flutter/app/FlutterActivityEvents.java ../../flutter/shell/platform/android/io/flutter/app/FlutterApplication.java ../../flutter/shell/platform/android/io/flutter/app/FlutterFragmentActivity.java ../../flutter/shell/platform/android/io/flutter/app/FlutterPluginRegistry.java ../../flutter/shell/platform/android/io/flutter/embedding/android/AndroidKeyProcessor.java ../../flutter/shell/platform/android/io/flutter/embedding/android/AndroidTouchProcessor.java ../../flutter/shell/platform/android/io/flutter/embedding/android/DrawableSplashScreen.java ../../flutter/shell/platform/android/io/flutter/embedding/android/FlutterActivity.java ../../flutter/shell/platform/android/io/flutter/embedding/android/FlutterActivityAndFragmentDelegate.java ../../flutter/shell/platform/android/io/flutter/embedding/android/FlutterActivityLaunchConfigs.java ../../flutter/shell/platform/android/io/flutter/embedding/android/FlutterEngineConfigurator.java ../../flutter/shell/platform/android/io/flutter/embedding/android/FlutterEngineProvider.java ../../flutter/shell/platform/android/io/flutter/embedding/android/FlutterFragment.java ../../flutter/shell/platform/android/io/flutter/embedding/android/FlutterFragmentActivity.java ../../flutter/shell/platform/android/io/flutter/embedding/android/FlutterSplashView.java ../../flutter/shell/platform/android/io/flutter/embedding/android/FlutterSurfaceView.java ../../flutter/shell/platform/android/io/flutter/embedding/android/FlutterTextureView.java ../../flutter/shell/platform/android/io/flutter/embedding/android/FlutterView.java ../../flutter/shell/platform/android/io/flutter/embedding/android/RenderMode.java ../../flutter/shell/platform/android/io/flutter/embedding/android/SplashScreen.java ../../flutter/shell/platform/android/io/flutter/embedding/android/SplashScreenProvider.java ../../flutter/shell/platform/android/io/flutter/embedding/android/TransparencyMode.java ../../flutter/shell/platform/android/io/flutter/embedding/engine/FlutterEngine.java ../../flutter/shell/platform/android/io/flutter/embedding/engine/FlutterEngineCache.java ../../flutter/shell/platform/android/io/flutter/embedding/engine/FlutterEnginePluginRegistry.java ../../flutter/shell/platform/android/io/flutter/embedding/engine/FlutterJNI.java ../../flutter/shell/platform/android/io/flutter/embedding/engine/FlutterShellArgs.java ../../flutter/shell/platform/android/io/flutter/embedding/engine/dart/DartExecutor.java ../../flutter/shell/platform/android/io/flutter/embedding/engine/dart/DartMessenger.java ../../flutter/shell/platform/android/io/flutter/embedding/engine/dart/PlatformMessageHandler.java ../../flutter/shell/platform/android/io/flutter/embedding/engine/loader/FlutterLoader.java ../../flutter/shell/platform/android/io/flutter/embedding/engine/loader/ResourceCleaner.java ../../flutter/shell/platform/android/io/flutter/embedding/engine/loader/ResourceExtractor.java ../../flutter/shell/platform/android/io/flutter/embedding/engine/loader/ResourcePaths.java ../../flutter/shell/platform/android/io/flutter/embedding/engine/plugins/FlutterPlugin.java ../../flutter/shell/platform/android/io/flutter/embedding/engine/plugins/PluginRegistry.java ../../flutter/shell/platform/android/io/flutter/embedding/engine/plugins/activity/ActivityAware.java ../../flutter/shell/platform/android/io/flutter/embedding/engine/plugins/activity/ActivityControlSurface.java ../../flutter/shell/platform/android/io/flutter/embedding/engine/plugins/activity/ActivityPluginBinding.java ../../flutter/shell/platform/android/io/flutter/embedding/engine/plugins/broadcastreceiver/BroadcastReceiverAware.java ../../flutter/shell/platform/android/io/flutter/embedding/engine/plugins/broadcastreceiver/BroadcastReceiverControlSurface.java ../../flutter/shell/platform/android/io/flutter/embedding/engine/plugins/broadcastreceiver/BroadcastReceiverPluginBinding.java ../../flutter/shell/platform/android/io/flutter/embedding/engine/plugins/contentprovider/ContentProviderAware.java ../../flutter/shell/platform/android/io/flutter/embedding/engine/plugins/contentprovider/ContentProviderControlSurface.java ../../flutter/shell/platform/android/io/flutter/embedding/engine/plugins/contentprovider/ContentProviderPluginBinding.java ../../flutter/shell/platform/android/io/flutter/embedding/engine/plugins/lifecycle/HiddenLifecycleReference.java ../../flutter/shell/platform/android/io/flutter/embedding/engine/plugins/service/ServiceAware.java ../../flutter/shell/platform/android/io/flutter/embedding/engine/plugins/service/ServiceControlSurface.java ../../flutter/shell/platform/android/io/flutter/embedding/engine/plugins/service/ServicePluginBinding.java ../../flutter/shell/platform/android/io/flutter/embedding/engine/plugins/shim/ShimPluginRegistry.java ../../flutter/shell/platform/android/io/flutter/embedding/engine/plugins/shim/ShimRegistrar.java ../../flutter/shell/platform/android/io/flutter/embedding/engine/renderer/FlutterRenderer.java ../../flutter/shell/platform/android/io/flutter/embedding/engine/renderer/FlutterUiDisplayListener.java ../../flutter/shell/platform/android/io/flutter/embedding/engine/renderer/RenderSurface.java ../../flutter/shell/platform/android/io/flutter/embedding/engine/systemchannels/AccessibilityChannel.java ../../flutter/shell/platform/android/io/flutter/embedding/engine/systemchannels/KeyEventChannel.java ../../flutter/shell/platform/android/io/flutter/embedding/engine/systemchannels/LifecycleChannel.java ../../flutter/shell/platform/android/io/flutter/embedding/engine/systemchannels/LocalizationChannel.java ../../flutter/shell/platform/android/io/flutter/embedding/engine/systemchannels/NavigationChannel.java ../../flutter/shell/platform/android/io/flutter/embedding/engine/systemchannels/PlatformChannel.java ../../flutter/shell/platform/android/io/flutter/embedding/engine/systemchannels/PlatformViewsChannel.java ../../flutter/shell/platform/android/io/flutter/embedding/engine/systemchannels/SettingsChannel.java ../../flutter/shell/platform/android/io/flutter/embedding/engine/systemchannels/SystemChannel.java ../../flutter/shell/platform/android/io/flutter/embedding/engine/systemchannels/TextInputChannel.java ../../flutter/shell/platform/android/io/flutter/plugin/common/ActivityLifecycleListener.java ../../flutter/shell/platform/android/io/flutter/plugin/common/BasicMessageChannel.java ../../flutter/shell/platform/android/io/flutter/plugin/common/BinaryCodec.java ../../flutter/shell/platform/android/io/flutter/plugin/common/BinaryMessenger.java ../../flutter/shell/platform/android/io/flutter/plugin/common/ErrorLogResult.java ../../flutter/shell/platform/android/io/flutter/plugin/common/EventChannel.java ../../flutter/shell/platform/android/io/flutter/plugin/common/FlutterException.java ../../flutter/shell/platform/android/io/flutter/plugin/common/JSONMessageCodec.java ../../flutter/shell/platform/android/io/flutter/plugin/common/JSONMethodCodec.java ../../flutter/shell/platform/android/io/flutter/plugin/common/JSONUtil.java ../../flutter/shell/platform/android/io/flutter/plugin/common/MessageCodec.java ../../flutter/shell/platform/android/io/flutter/plugin/common/MethodCall.java ../../flutter/shell/platform/android/io/flutter/plugin/common/MethodChannel.java ../../flutter/shell/platform/android/io/flutter/plugin/common/MethodCodec.java ../../flutter/shell/platform/android/io/flutter/plugin/common/PluginRegistry.java ../../flutter/shell/platform/android/io/flutter/plugin/common/StandardMessageCodec.java ../../flutter/shell/platform/android/io/flutter/plugin/common/StandardMethodCodec.java ../../flutter/shell/platform/android/io/flutter/plugin/common/StringCodec.java ../../flutter/shell/platform/android/io/flutter/plugin/editing/InputConnectionAdaptor.java ../../flutter/shell/platform/android/io/flutter/plugin/editing/TextInputPlugin.java ../../flutter/shell/platform/android/io/flutter/plugin/platform/AccessibilityEventsDelegate.java ../../flutter/shell/platform/android/io/flutter/plugin/platform/PlatformPlugin.java ../../flutter/shell/platform/android/io/flutter/plugin/platform/PlatformView.java ../../flutter/shell/platform/android/io/flutter/plugin/platform/PlatformViewFactory.java ../../flutter/shell/platform/android/io/flutter/plugin/platform/PlatformViewRegistry.java ../../flutter/shell/platform/android/io/flutter/plugin/platform/PlatformViewRegistryImpl.java ../../flutter/shell/platform/android/io/flutter/plugin/platform/PlatformViewsAccessibilityDelegate.java ../../flutter/shell/platform/android/io/flutter/plugin/platform/PlatformViewsController.java ../../flutter/shell/platform/android/io/flutter/plugin/platform/SingleViewPresentation.java ../../flutter/shell/platform/android/io/flutter/plugin/platform/VirtualDisplayController.java ../../flutter/shell/platform/android/io/flutter/util/PathUtils.java ../../flutter/shell/platform/android/io/flutter/util/Preconditions.java ../../flutter/shell/platform/android/io/flutter/util/Predicate.java ../../flutter/shell/platform/android/io/flutter/view/AccessibilityBridge.java ../../flutter/shell/platform/android/io/flutter/view/AccessibilityViewEmbedder.java ../../flutter/shell/platform/android/io/flutter/view/FlutterCallbackInformation.java ../../flutter/shell/platform/android/io/flutter/view/FlutterMain.java ../../flutter/shell/platform/android/io/flutter/view/FlutterNativeView.java ../../flutter/shell/platform/android/io/flutter/view/FlutterRunArguments.java ../../flutter/shell/platform/android/io/flutter/view/FlutterView.java ../../flutter/shell/platform/android/io/flutter/view/TextureRegistry.java ../../flutter/shell/platform/android/io/flutter/view/VsyncWaiter.java gen/flutter/shell/platform/android/io/flutter/BuildConfig.java
Traceback (most recent call last):
  File "../../build/android/gyp/javac.py", line 342, in <module>
    sys.exit(main(sys.argv[1:]))
  File "../../build/android/gyp/javac.py", line 303, in main
    java_files)
  File "../../build/android/gyp/javac.py", line 143, in DoJavac
    input_strings=javac_cmd)
  File "/home/krishna/Desktop/flutter_dev/engine/src/build/android/gyp/util/md5_check.py", line 30, in CallAndRecordIfStale
    function()
  File "../../build/android/gyp/javac.py", line 136, in Compile
    stderr_filter=ColorJavacOutput)
  File "/home/krishna/Desktop/flutter_dev/engine/src/build/android/gyp/util/build_utils.py", line 161, in CheckOutput
    stderr = stderr_filter(stderr)
  File "../../build/android/gyp/javac.py", line 56, in ColorJavacOutput
    return "\n".join(map(ApplyColor, output.split("\n")))
TypeError: a bytes-like object is required, not 'str'
[404/3760] CXX obj/third_party/boringssl/src/ssl/ssl.t1_lib.o
ninja: build stopped: subcommand failed.
```

**Comment by krishnakeshan** [comment]
I've tried converting line 56 of src/build/android/gyp/javac.py to return a bytes array using the `encode()` method but it still returns the same error.

**Comment by TahaTesser** [comment]
Hi @krishnakeshan 
I am not sure this is related to Flutter 

can you please provide your `flutter doctor -v` and `flutter run --verbose`? 
Also, to better address the issue, would be helpful if you could post a minimal code sample to reproduce the problem
Thank you

**Comment by krishnakeshan** [comment]
Hi @TahaTesser This error pops up when compiling the engine as instructed on this page:
https://github.com/flutter/flutter/wiki/Compiling-the-engine

This is not an issue with running a Flutter application hence there's no code or `flutter run` output.

**Comment by jason-simmons** [comment]
What version of Python is configured in your environment?  If Python3 is first in your path, then try switching to Python2.

**Comment by krishnakeshan** [comment]
@jason-simmons I think switching to Python2 ought to resolve the issue (I'm away from my machine, I'll update as soon as I get back), but shouldn't we be using Python3 i.e. shouldn't we update the scripts to be Python3 scripts? I'll update my answer on the success of using Python2 soon as I'm back on my machine.

**Comment by chinmaygarde** [comment]
We need Python 2 for engine build scripts. I reworded https://github.com/flutter/flutter/issues/53002 into a feature request for Python 3 in the engine build scripts.
