### ISSUE TITLE
[tool_crash] Invalid argument(s): Cannot find executable for /Users/madhosingh/Desktop/sdk/build-tools/29.0.2/aapt.

### ISSUE THREAD

**Issue by msosian** [flutter/flutter#54418]
## Command
```
flutter run
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
ArgumentError: Invalid argument(s): Cannot find executable for /Users/madhosingh/Desktop/sdk/build-tools/29.0.2/aapt.
```
#0      _getExecutable (package:process/src/interface/local_process_manager.dart:127:5)
#1      LocalProcessManager.runSync (package:process/src/interface/local_process_manager.dart:94:30)
#2      _DefaultProcessUtils.runSync (package:flutter_tools/src/base/process.dart:417:51)
#3      new AndroidApk.fromApk (package:flutter_tools/src/application_package.dart:121:33)
#4      AndroidApk.fromAndroidProject (package:flutter_tools/src/application_package.dart:174:27)
<asynchronous suspension>
#5      AndroidDevice.startApp (package:flutter_tools/src/android/android_device.dart:534:34)
<asynchronous suspension>
#6      FlutterDevice.runHot (package:flutter_tools/src/resident_runner.dart:434:54)
#7      _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:75:64)
#8      _rootRunUnary (dart:async/zone.dart:1134:38)
#9      _CustomZone.runUnary (dart:async/zone.dart:1031:19)
#10     _FutureListener.handleValue (dart:async/future_impl.dart:140:18)
#11     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:682:45)
#12     Future._propagateToListeners (dart:async/future_impl.dart:711:32)
#13     Future._completeWithValue (dart:async/future_impl.dart:526:5)
#14     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:34:15)
#15     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:293:13)
#16     ApplicationPackageFactory.getPackageForPlatform (package:flutter_tools/src/application_package.dart)
#17     _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:75:64)
```
```
[✓] Flutter (Channel beta, v1.14.6, on Mac OS X 10.14 18A391, locale en-IN)
    • Flutter version 1.14.6 at /Users/madhosingh/Desktop/flutter/sdk/flutter
    • Framework revision fabeb2a16f (2 months ago), 2020-01-28 07:56:51 -0800
    • Engine revision c4229bfbba
    • Dart version 2.8.0 (build 2.8.0-dev.5.0 fc3af737c7)

[!] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/madhosingh/Desktop/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • ANDROID_HOME = /Users/madhosingh/Desktop/sdk
    ✗ Android SDK file not found: /Users/madhosingh/Desktop/sdk/build-tools/29.0.2/aapt.
    • Try re-installing or updating your Android SDK,
      visit https://flutter.dev/setup/#android-setup for detailed instructions.

[!] Xcode - develop for iOS and macOS (Xcode 10.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.1, Build version 10B61
    ✗ Flutter requires a minimum Xcode version of 10.2.0.
      Download the latest version or update via the Mac App Store.
    • CocoaPods version 1.7.4

[✓] Android Studio (version 3.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 23.2.1
    • Dart plugin version 171.4424
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-915-b08)

[✓] Connected device (1 available)
    • RMX1807 • b94ecbe6 • android-arm64 • Android 9 (API 28)

! Doctor found issues in 2 categories.

```

## Flutter Application Metadata
**Version**: 1.2.1+21
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
### Plugins
file_picker-1.4.3+2
firebase_analytics-5.0.9
firebase_core-0.4.3+2
firebase_core_web-0.1.1+2
firebase_dynamic_links-0.5.0+9
flutter_plugin_android_lifecycle-1.0.4
flutter_webview_plugin-0.3.10+1
fluttertoast-3.1.3
image_cropper-1.1.2
image_picker-0.6.3
launch_review-2.0.0
native_device_orientation-0.3.0
package_info-0.4.0+13
path_provider-1.5.1
qr_mobile_vision-0.3.1
share-0.6.3+5
shared_preferences-0.5.6
shared_preferences_macos-0.0.1+3
shared_preferences_web-0.1.2+2
url_launcher-4.2.0+3

**Comment by jonahwilliams** [comment]
> ✗ Android SDK file not found: /Users/madhosingh/Desktop/sdk/build-tools/29.0.2/aapt.
    • Try re-installing or updating your Android SDK,
      visit https://flutter.dev/setup/#android-setup for detailed instructions.

This is the error that needs to be fixed, though we probably shouldn't crash here

**Comment by Waheed388** [comment]
It is simple. Follow these three steps to solve the issue.

 - Open SDK Manager
 - Select Android SDK Build-Tools and uninstall it.
 - Then reinstall the required SDK Build-Tools version (in your case 29.0.2)

That's all.
[![enter image description here][1]][1]


  [1]: https://i.stack.imgur.com/qt0h0.jpg

**Comment by msosian** [comment]
THANKS
