### ISSUE TITLE
[tool_crash] ArgumentError: Invalid argument(s): Cannot find executable for C:\Users\DELL\Downloads\flutter_windows_v1.12.13+hotfix.8-stable\flutter\bin\cache\dart-sdk\bin\pub.bat.

### ISSUE THREAD

**Issue by Maham-Zaki** [flutter/flutter#54452]
## Command
```
flutter run -d chrome
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
ArgumentError: Invalid argument(s): Cannot find executable for C:\Users\DELL\Downloads\flutter_windows_v1.12.13+hotfix.8-stable\flutter\bin\cache\dart-sdk\bin\pub.bat.
```
#0      _getExecutable (package:process/src/interface/local_process_manager.dart:127:5)
#1      LocalProcessManager.start (package:process/src/interface/local_process_manager.dart:43:30)
#2      _DefaultProcessUtils.start (package:flutter_tools/src/base/process.dart:462:28)
#3      _DefaultProcessUtils.stream (package:flutter_tools/src/base/process.dart:480:35)
#4      _DefaultPub.batch (package:flutter_tools/src/dart/pub.dart:262:33)
<asynchronous suspension>
#5      _DefaultPub.get (package:flutter_tools/src/dart/pub.dart:176:15)
#6      _ResidentWebRunner.run.<anonymous closure> (package:flutter_tools/src/build_runner/resident_web_runner.dart:413:19)
#7      _ResidentWebRunner.run.<anonymous closure> (package:flutter_tools/src/build_runner/resident_web_runner.dart:409:31)
#8      asyncGuard.<anonymous closure> (package:flutter_tools/src/base/async_guard.dart:111:32)
#9      asyncGuard.<anonymous closure> (package:flutter_tools/src/base/async_guard.dart:109:18)
#10     _rootRun (dart:async/zone.dart:1184:13)
#11     _CustomZone.run (dart:async/zone.dart:1077:19)
#12     _runZoned (dart:async/zone.dart:1619:10)
#13     runZonedGuarded (dart:async/zone.dart:1608:12)
#14     runZoned (dart:async/zone.dart:1536:12)
#15     asyncGuard (package:flutter_tools/src/base/async_guard.dart:109:3)
#16     _ResidentWebRunner.run (package:flutter_tools/src/build_runner/resident_web_runner.dart:409:20)
#17     _rootRunUnary (dart:async/zone.dart:1192:38)
#18     _CustomZone.runUnary (dart:async/zone.dart:1085:19)
#19     _FutureListener.handleValue (dart:async/future_impl.dart:141:18)
#20     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:682:45)
#21     Future._propagateToListeners (dart:async/future_impl.dart:711:32)
#22     Future._completeWithValue (dart:async/future_impl.dart:526:5)
#23     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:36:15)
```
```
[✓] Flutter (Channel dev, v1.18.0, on Microsoft Windows [Version 10.0.18362.720], locale en-US)
    • Flutter version 1.18.0 at C:\Users\DELL\Downloads\flutter_windows_v1.12.13+hotfix.8-stable\flutter
    • Framework revision 8f7327f83a (4 days ago), 2020-04-06 22:11:01 -0400
    • Engine revision 49891e0653
    • Dart version 2.8.0 (build 2.8.0-dev.20.0 1210d27678)

[!] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at C:\Users\DELL\AppData\Local\Android\sdk
    • Platform android-29, build-tools 29.0.2
    • Java binary at: C:\Program Files\Android\Android Studio1\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)
    ✗ Android license status unknown.
      Try re-installing or updating your Android SDK Manager.
      See https://developer.android.com/studio/#downloads or visit visit https://flutter.dev/docs/get-started/install/windows#android-setup for detailed instructions.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[✓] Android Studio (version 3.5)
    • Android Studio at C:\Program Files\Android\Android Studio1
    • Flutter plugin version 44.0.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)

[✓] Connected device (3 available)
    • SM J5007   • af939a9e   • android-arm    • Android 5.1.1 (API 22)
    • Chrome     • chrome     • web-javascript • Google Chrome 80.0.3987.163
    • Web Server • web-server • web-javascript • Flutter Tools

! Doctor found issues in 1 category.

```

## Flutter Application Metadata
**Type**: app
**Version**: 1.0.0+1
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: stable
**Creation framework version**: 0b8abb4724aa590dd0f429683339b1e045a1594d

**Comment by Maham-Zaki** [comment]
flutter web is not working
