### ISSUE TITLE
MissingPluginException for path_provider when running audioplayers package

### ISSUE THREAD

**Issue by VicHofs** [flutter/flutter#54501]
## Steps to Reproduce

1. Run `flutter create audio_app`.
2. Add to dependencies: `audioplayers: ^0.15.0`.
3. Create new folder "assets" with subfolder "audio" containing audio file (named "C.wav").
4. Add to assets: `- assets/audio/`.
5. Run `flutter packages get`.
6. Create Stateless Widget with Button, taking function `() { 
              final player = AudioCache();
              player.play('C.wav');
            }` as `onPressed:`.
**Expected results:** C note should ring out on button press.

**Actual results:** `Exception has occurred.
MissingPluginException (MissingPluginException(No implementation found for method getTemporaryDirectory on channel plugins.flutter.io/path_provider))`

<details>
  <summary>Logs</summary>

```
executing: [C:\flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[ +138 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[   +2 ms] a5765331bca80c7191a6a6ccc95cab56baad5471
[        ] executing: [C:\flutter/] git describe --match *.*.* --first-parent --long --tags
[ +127 ms] Exit code 0 from: git describe --match *.*.* --first-parent --long --tags
[        ] 1.18.0-dev.4.0-57-ga5765331b
[  +10 ms] executing: [C:\flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[ +119 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[   +1 ms] origin/master
[        ] executing: [C:\flutter/] git ls-remote --get-url origin
[  +78 ms] Exit code 0 from: git ls-remote --get-url origin
[   +2 ms] https://github.com/flutter/flutter.git
[ +138 ms] executing: [C:\flutter/] git rev-parse --abbrev-ref HEAD
[  +90 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] master
[ +116 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.  
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +7 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +69 ms] executing: C:\Users\-redacted-\AppData\Local\Android\sdk\platform-tools\adb.exe devices -l
[  +88 ms] List of devices attached
[   +8 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +8 ms] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[  +39 ms] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[  +27 ms] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[   +3 ms] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[ +108 ms] Found plugin audioplayers at C:\flutter\.pub-cache\hosted\pub.dartlang.org\audioplayers-0.10.1\
[  +36 ms] Found plugin path_provider at C:\flutter\.pub-cache\hosted\pub.dartlang.org\path_provider-0.5.0+1\
[ +166 ms] Found plugin audioplayers at C:\flutter\.pub-cache\hosted\pub.dartlang.org\audioplayers-0.10.1\
[  +24 ms] Found plugin path_provider at C:\flutter\.pub-cache\hosted\pub.dartlang.org\path_provider-0.5.0+1\
[  +89 ms] Generating C:\Users\-redacted-\PycharmProjects\Dart test\audio_app\android\app\src\main\java\io\flutter\plugins\GeneratedPluginRegistrant.java
[ +158 ms] Launching lib\main.dart on Windows in debug mode...
[  +16 ms] C:\flutter\bin\cache\dart-sdk\bin\dart.exe C:\flutter\bin\cache\artifacts\engine\windows-x64\frontend_server.dart.snapshot --sdk-root
C:\flutter\bin\cache\artifacts\engine\common\flutter_patched_sdk/ --incremental --target=flutter --debugger-module-names -Ddart.developer.causal_async_stacks=true --output-dill
C:\Users\-redacted-\AppData\Local\Temp\flutter_tool.df5dad91-7b7e-11ea-9d46-1c4d70078a6e\app.dill --packages C:\Users\-redacted-\PycharmProjects\Dart test\audio_app\.packages
-Ddart.vm.profile=false -Ddart.vm.product=false
--bytecode-options=source-positions,local-var-info,debugger-stops,instance-field-initializers,keep-unreachable-code,avoid-closure-call-instructions --enable-asserts
--track-widget-creation --filesystem-scheme org-dartlang-root --initialize-from-dill build\cache.dill
[  +73 ms] executing: C:\Program Files (x86)\Microsoft Visual Studio\Installer\vswhere.exe -format json -utf8 -latest -version 16 -requires Microsoft.Component.MSBuild
Microsoft.VisualStudio.Component.VC.Tools.x86.x64 Microsoft.VisualStudio.Component.Windows10SDK.17763
[  +65 ms] Exit code 0 from: C:\Program Files (x86)\Microsoft Visual Studio\Installer\vswhere.exe -format json -utf8 -latest -version 16 -requires Microsoft.Component.MSBuild
Microsoft.VisualStudio.Component.VC.Tools.x86.x64 Microsoft.VisualStudio.Component.Windows10SDK.17763
[   +3 ms] [
             {
               "instanceId": "e77e57f6",
               "installDate": "2020-01-04T18:05:59Z",
               "installationName": "VisualStudio/16.5.2+29926.136",
               "installationPath": "C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Community",
               "installationVersion": "16.5.29926.136",
               "productId": "Microsoft.VisualStudio.Product.Community",
               "productPath": "C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Community\\Common7\\IDE\\devenv.exe",
               "state": 4294967295,
               "isComplete": true,
               "isLaunchable": true,
               "isPrerelease": false,
               "isRebootRequired": false,
               "displayName": "Visual Studio Community 2019",
               "description": "Powerful IDE, free for students, open-source contributors, and individuals",
               "channelId": "VisualStudio.16.Release",
               "channelUri": "https://aka.ms/vs/16/release/channel",
               "enginePath": "C:\\Program Files (x86)\\Microsoft Visual Studio\\Installer\\resources\\app\\ServiceHub\\Services\\Microsoft.VisualStudio.Setup.Service",
               "releaseNotes": "https://go.microsoft.com/fwlink/?LinkId=660893#16.5.2",
               "thirdPartyNotices": "https://go.microsoft.com/fwlink/?LinkId=660909",
               "updateDate": "2020-04-05T00:08:44.0265247Z",
               "catalog": {
                 "buildBranch": "d16.5",
                 "buildVersion": "16.5.29926.136",
                 "id": "VisualStudio/16.5.2+29926.136",
                 "localBuild": "build-lab",
                 "manifestName": "VisualStudio",
                 "manifestType": "installer",
                 "productDisplayVersion": "16.5.2",
                 "productLine": "Dev16",
                 "productLineVersion": "2019",
                 "productMilestone": "RTW",
                 "productMilestoneIsPreRelease": "False",
                 "productName": "Visual Studio",
                 "productPatchVersion": "2",
                 "productPreReleaseMilestoneSuffix": "1.0",
                 "productSemanticVersion": "16.5.2+29926.136",
                 "requiredEngineVersion": "2.5.2139.10695"
               },
               "properties": {
                 "campaignId": "1847750488.1578160858",
                 "channelManifestId": "VisualStudio.16.Release/16.5.2+29926.136",
                 "nickname": "",
                 "setupEngineFilePath": "C:\\Program Files (x86)\\Microsoft Visual Studio\\Installer\\vs_installershell.exe"
               }
             }
           ]
[  +16 ms] Building Windows application...
[  +19 ms] executing: [C:\Users\-redacted-\PycharmProjects\Dart test\audio_app\windows/] C:\flutter\packages\flutter_tools\bin\vs_build.bat C:\Program Files (x86)\Microsoft Visual
Studio\2019\Community\VC\Auxiliary\Build\vcvars64.bat Runner.sln Debug
[  +20 ms] <- compile package:audio_app/main.dart
[ +478 ms] **********************************************************************
[   +1 ms] ** Visual Studio 2019 Developer Command Prompt v16.5.2
[   +1 ms] ** Copyright (c) 2019 Microsoft Corporation
[        ] **********************************************************************
[+1989 ms] [vcvarsall.bat] Environment initialized for: 'x64'
[ +132 ms] Microsoft(R) Build Engine version 16.5.0+d4cbfca49 for .NET Framework 
[   +2 ms] Copyright (C) Microsoft Corporation. All rights reserved.
[  +11 ms] Compiling this solution's projects one at a time. To enable parallel build, add argument "-m".
[  +95 ms] Compilation started at 4/10/2020 7:59:08 PM.
[ +220 ms] Project "C:\Users\-redacted-\PycharmProjects\Dart test\audio_app\windows\Runner.sln" at node 1 (standard destinations).
[   +5 ms] ValidateSolutionConfiguration:
[  +27 ms]   Compiling configuration of solution "Debug|x64".
[ +379 ms] The project "C:\Users\-redacted-\PycharmProjects\Dart test\audio_app\windows\Runner.sln" (1) is compiling "C:\Users\-redacted-\PycharmProjects\Dart
test\audio_app\windows\Runner.vcxproj.metaproj" (2) at node 1 (standard destinations).
[  +66 ms] The project "C:\Users\-redacted-\PycharmProjects\Dart test\audio_app\windows\Runner.vcxproj.metaproj" (2) is compiling "C:\Users\-redacted-\PycharmProjects\Dart
test\audio_app\windows\FlutterBuild.vcxproj" (3) at node 1 (standard destinations).
[  +49 ms] InitializeBuildStatus:
[  +55 ms]   Creating "x64\Debug\Flutter Build.tlog\unsuccessfulbuild" because "AlwaysCreate" was specified.
[   +3 ms] CustomBuildStep:
[  +32 ms]   Running Flutter backend build
[  +30 ms]   "C:\Users\-redacted-\PycharmProjects\Dart test\audio_app\windows\scripts\prepare_dependencies" Debug
[   +1 ms]   :VCEnd
[+14084 ms] FinalizeBuildStatus:
[   +1 ms]   Deleting file "x64\Debug\Flutter Build.tlog\unsuccessfulbuild".
[        ]   Touching "x64\Debug\Flutter Build.tlog\Flutter Build.lastbuildstate".
[  +17 ms] Compilation project ready "C:\Users\-redacted-\PycharmProjects\Dart test\audio_app\windows\FlutterBuild.vcxproj" (standard destinations).
[  +94 ms] The project "C:\Users\-redacted-\PycharmProjects\Dart test\audio_app\windows\Runner.vcxproj.metaproj" (2) is compiling "C:\Users\-redacted-\PycharmProjects\Dart
test\audio_app\windows\Runner.vcxproj" (4) at node 1 (standard destinations).
[   +2 ms] InitializeBuildStatus:
[   +1 ms]   Creating "C:\Users\-redacted-\PycharmProjects\Dart test\audio_app\windows\..\build\windows\intermediates\x64\Debug\Runner\Runner.tlog\unsuccessfulbuild" because "AlwaysCreate" was 
specified.
[  +87 ms] ClCompile:
[   +1 ms]   C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.25.28610\bin\HostX86\x64\CL.exe /c /I"C:\Users\-redacted-\PycharmProjects\Dart
test\audio_app\windows\\" /I"C:\Users\-redacted-\PycharmProjects\Dart test\audio_app\windows\flutter\ephemeral" /I"C:\Users\-redacted-\PycharmProjects\Dart
test\audio_app\windows\flutter\ephemeral\cpp_client_wrapper\include" /ZI /JMC /nologo /W4 /WX /diagnostics:column /sdl /Od /D _MBCS /D _HAS_EXCEPTIONS=0 /D _UNICODE /D UNICODE /Gm- /EHsc/RTC1 /MDd /GS /fp:precise /permissive- /Zc:wchar_t /Zc:forScope /Zc:inline /Fo"C:\Users\-redacted-\PycharmProjects\Dart
test\audio_app\windows\..\build\windows\intermediates\x64\Debug\Runner\\" /Fd"C:\Users\-redacted-\PycharmProjects\Dart
test\audio_app\windows\..\build\windows\intermediates\x64\Debug\Runner\vc142.pdb" /Gd /TP /wd4100 /FC /errorReport:queue runner\main.cpp flutter\generated_plugin_registrant.cc
runner\run_loop.cpp runner\window_configuration.cpp runner\win32_window.cpp runner\flutter_window.cpp "C:\Users\-redacted-\PycharmProjects\Dart
test\audio_app\windows\flutter\ephemeral\cpp_client_wrapper\engine_method_result.cc" "C:\Users\-redacted-\PycharmProjects\Dart
test\audio_app\windows\flutter\ephemeral\cpp_client_wrapper\flutter_view_controller.cc" "C:\Users\-redacted-\PycharmProjects\Dart
test\audio_app\windows\flutter\ephemeral\cpp_client_wrapper\plugin_registrar.cc"
[ +171 ms]   main.cpp
[+1109 ms]   generated_plugin_registrant.cc
[ +395 ms]   run_loop.cpp
[+1049 ms]   window_configuration.cpp
[  +17 ms]   win32_window.cpp
[ +907 ms]   flutter_window.cpp
[+1046 ms]   engine_method_result.cc
[ +635 ms]   flutter_view_controller.cc
[+1237 ms]   plugin_registrar.cc
[ +720 ms]   Generating Code...
[ +602 ms] ResourceCompile:
[   +1 ms]   C:\Program Files (x86)\Windows Kits\10\bin\10.0.18362.0\x86\rc.exe /D _UNICODE /D UNICODE /l"0x0409" /nologo /fo"C:\Users\-redacted-\PycharmProjects\Dart
test\audio_app\windows\..\build\windows\intermediates\x64\Debug\Runner\Runner.res" runner\Runner.rc
[ +158 ms] ManifestResourceCompile:
[   +1 ms]   C:\Program Files (x86)\Windows Kits\10\bin\10.0.18362.0\x86\rc.exe /nologo /fo"C:\Users\-redacted-\PycharmProjects\Dart
test\audio_app\windows\..\build\windows\intermediates\x64\Debug\Runner\audio_app.exe.embed.manifest.res" "C:\Users\-redacted-\PycharmProjects\Dart
test\audio_app\windows\..\build\windows\intermediates\x64\Debug\Runner\audio_app_manifest.rc"
[ +125 ms] C:\Users\-redacted-\PycharmProjects\Dart test\audio_app\windows\..\build\windows\intermediates\x64\Debug\Runner\audio_app_manifest.rc(1): error RC2135: file not found:
C:\Users\-redacted-\PycharmProjects\Dart test\audio_app\windows\..\build\windows\intermediates\x64\Debug\Runner\audio_app.exe.embed.manifest
[C:\Users\-redacted-\PycharmProjects\Dart test\audio_app\windows\Runner.vcxproj]
[  +13 ms] Compilation project ready "C:\Users\-redacted-\PycharmProjects\Dart test\audio_app\windows\Runner.vcxproj" (standard destinations) -- FAILED.
[   +7 ms] Compilation project ready "C:\Users\-redacted-\PycharmProjects\Dart test\audio_app\windows\Runner.vcxproj.metaproj" (standard destinations) -- FAILED.
[   +2 ms] Compilation project ready "C:\Users\-redacted-\PycharmProjects\Dart test\audio_app\windows\Runner.sln" (standard destinations) -- FAILED.
[   +1 ms] Compiling FAILED.
[  +16 ms] "C:\Users\-redacted-\PycharmProjects\Dart test\audio_app\windows\Runner.sln" (standard destinations) (1) ->
[  +18 ms] "C:\Users\-redacted-\PycharmProjects\Dart test\audio_app\windows\Runner.vcxproj.metaproj" (standard destinations) (2) ->
[   +3 ms] "C:\Users\-redacted-\PycharmProjects\Dart test\audio_app\windows\Runner.vcxproj" (standard destinations) (4) ->
[        ] (ManifestResourceCompile destination) ->
[        ]   C:\Users\-redacted-\PycharmProjects\Dart test\audio_app\windows\..\build\windows\intermediates\x64\Debug\Runner\audio_app_manifest.rc(1): error RC2135: file not found:   
C:\Users\-redacted-\PycharmProjects\Dart test\audio_app\windows\..\build\windows\intermediates\x64\Debug\Runner\audio_app.exe.embed.manifest
[C:\Users\-redacted-\PycharmProjects\Dart test\audio_app\windows\Runner.vcxproj]
[   +2 ms]     0 Aviso(s)
[   +3 ms]     1 Erro(s)
[        ] Tempo Decorrido 00:00:23.36
[  +13 ms] Building Windows application... (completed in 26.2s)
[  +16 ms] Exception: Build process failed. To view the stack trace, please run `flutter run -d windows -v`.
[   +3 ms] "flutter run" took 27,258ms.

#0      throwToolExit (package:flutter_tools/src/base/common.dart:14:3)
#1      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:572:7)
<asynchronous suspension>
#2      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:731:18)
#3      _rootRunUnary (dart:async/zone.dart:1192:38)
#4      _CustomZone.runUnary (dart:async/zone.dart:1085:19)
#5      _FutureListener.handleValue (dart:async/future_impl.dart:141:18)
#6      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:682:45)
#7      Future._propagateToListeners (dart:async/future_impl.dart:711:32)
#8      Future._completeWithValue (dart:async/future_impl.dart:526:5)
#9      _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:36:15)
#10     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:306:13)
#11     RunCommand.usageValues (package:flutter_tools/src/commands/run.dart)
#12     _rootRunUnary (dart:async/zone.dart:1192:38)
#13     _CustomZone.runUnary (dart:async/zone.dart:1085:19)
#14     _FutureListener.handleValue (dart:async/future_impl.dart:141:18)
#15     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:682:45)
#16     Future._propagateToListeners (dart:async/future_impl.dart:711:32)
#17     Future._completeWithValue (dart:async/future_impl.dart:526:5)
#18     Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:556:7)
#19     _rootRun (dart:async/zone.dart:1184:13)
#20     _CustomZone.run (dart:async/zone.dart:1077:19)
#21     _CustomZone.runGuarded (dart:async/zone.dart:979:7)
#22     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1019:23)
#23     _microtaskLoop (dart:async/schedule_microtask.dart:43:21)
#24     _startMicrotaskLoop (dart:async/schedule_microtask.dart:52:5)
#25     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
#26     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:169:5)
```

```
Analyzing audio_app...
No issues found! (ran in 2.1s)
```

```
[√] Flutter (Channel master, v1.18.0-5.0.pre.57, on Microsoft Windows [version 10.0.18363.752], locale en-US)
    • Flutter version 1.18.0-5.0.pre.57 at C:\flutter
    • Framework revision a5765331bc (24 hours ago), 2020-04-09 16:15:01 -0700
    • Engine revision 5b4b1f33c6
    • Dart version 2.8.0 (build 2.8.0-dev.20.0 dcdc71d763)

 
[√] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at C:\Users\-redacted-\AppData\Local\Android\sdk
    • Platform android-29, build-tools 29.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)
    • All Android licenses accepted.

[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.5.2)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.5.29926.136

[√] Android Studio (version 3.6)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 45.0.1
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)

[√] VS Code (version 1.44.0)
    • VS Code at C:\Users\-redacted-\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.9.1

[√] Connected device (1 available)
    • Windows • Windows • windows-x64 • Microsoft Windows [version 10.0.18363.752]

• No issues found!
```
</details>

**Comment by VicHofs** [comment]
My code in any case:
```
import 'package:flutter/material.dart';
import 'package:audioplayers/audio_cache.dart';

void main() => runApp(AudioApp());

class AudioApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        body: Center(
          child: IconButton(
            icon: Icon(Icons.play_circle_outline),
            iconSize: 40,
            onPressed: () { 
              final player = AudioCache();
              player.play('C.wav');
            }
          ),
        ),
      ),
    );
  }
}
```

**Comment by TahaTesser** [comment]
Hi @VicHofs 
i tried to reproduce your issue on latest `master` channel
No exceptions, please make sure you've proper assets path defined

### Code Sample
```
import 'package:flutter/material.dart';
import 'package:audioplayers/audio_cache.dart';

void main() => runApp(AudioApp());

class AudioApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        body: Center(
          child: IconButton(
              icon: Icon(Icons.play_circle_outline),
              iconSize: 40,
              onPressed: () {
                final player = AudioCache();
                player.play('audio/C.wav');
              }),
        ),
      ),
    );
  }
}

```

```
  assets:
    - assets/audio/
```

<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel master, v1.18.0-5.0.pre.99, on Mac OS X 10.15.4 19E287,
    locale en-GB)
    • Flutter version 1.18.0-5.0.pre.99 at /Users/taha/Code/flutter_master
    • Framework revision 812885c179 (5 hours ago), 2020-04-12 23:40:01 -0400
    • Engine revision 926f6fcbbc
    • Dart version 2.8.0 (build 2.8.0-dev.20.0 8ef508ba36)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/taha/Code/sdk
    • Platform android-29, build-tools 29.0.3
    • ANDROID_HOME = /Users/taha/Code/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.
[✓] Xcode - develop for iOS and macOS (Xcode 11.4)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.4, Build version 11E146
    • CocoaPods version 1.9.1
[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome
[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build
      1.8.0_212-release-1586-b4-5784211)
[✓] VS Code (version 1.44.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.9.1
[✓] Connected device (4 available)
    • SM M305F   • 32003c30dc19668f • android-arm64  • Android 10 (API 29)
    • macOS      • macOS            • darwin-x64     • Mac OS X 10.15.4 19E287
    • Chrome     • chrome           • web-javascript • Google Chrome
      81.0.4044.92
    • Web Server • web-server       • web-javascript • Flutter Tools
• No issues found!
```

</details>

**Comment by VicHofs** [comment]
> Hi @VicHofs 
> 
> i tried to reproduce your issue on latest `master` channel
> 
> No exceptions, please make sure you've proper assets path defined
> 
> 
> 
> ### Code Sample
> 
> ```
> 
> import 'package:flutter/material.dart';
> 
> import 'package:audioplayers/audio_cache.dart';
> 
> 
> 
> void main() => runApp(AudioApp());
> 
> 
> 
> class AudioApp extends StatelessWidget {
> 
>   @override
> 
>   Widget build(BuildContext context) {
> 
>     return MaterialApp(
> 
>       home: Scaffold(
> 
>         body: Center(
> 
>           child: IconButton(
> 
>               icon: Icon(Icons.play_circle_outline),
> 
>               iconSize: 40,
> 
>               onPressed: () {
> 
>                 final player = AudioCache();
> 
>                 player.play('audio/C.wav');
> 
>               }),
> 
>         ),
> 
>       ),
> 
>     );
> 
>   }
> 
> }
> 
> 
> 
> ```
> 
> 
> 
> ```
> 
>   assets:
> 
>     - assets/audio/
> 
> ```
> 
> 
> 
> <details>
> 
> <summary>flutter doctor -v</summary>
> 
> 
> 
> ```
> 
> [✓] Flutter (Channel master, v1.18.0-5.0.pre.99, on Mac OS X 10.15.4 19E287,
> 
>     locale en-GB)
> 
>     • Flutter version 1.18.0-5.0.pre.99 at /Users/taha/Code/flutter_master
> 
>     • Framework revision 812885c179 (5 hours ago), 2020-04-12 23:40:01 -0400
> 
>     • Engine revision 926f6fcbbc
> 
>     • Dart version 2.8.0 (build 2.8.0-dev.20.0 8ef508ba36)
> 
>  
> 
> [✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
> 
>     • Android SDK at /Users/taha/Code/sdk
> 
>     • Platform android-29, build-tools 29.0.3
> 
>     • ANDROID_HOME = /Users/taha/Code/sdk
> 
>     • Java binary at: /Applications/Android
> 
>       Studio.app/Contents/jre/jdk/Contents/Home/bin/java
> 
>     • Java version OpenJDK Runtime Environment (build
> 
>       1.8.0_212-release-1586-b4-5784211)
> 
>     • All Android licenses accepted.
> 
> [✓] Xcode - develop for iOS and macOS (Xcode 11.4)
> 
>     • Xcode at /Applications/Xcode.app/Contents/Developer
> 
>     • Xcode 11.4, Build version 11E146
> 
>     • CocoaPods version 1.9.1
> 
> [✓] Chrome - develop for the web
> 
>     • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome
> 
> [✓] Android Studio (version 3.6)
> 
>     • Android Studio at /Applications/Android Studio.app/Contents
> 
>     • Flutter plugin version 45.1.1
> 
>     • Dart plugin version 192.7761
> 
>     • Java version OpenJDK Runtime Environment (build
> 
>       1.8.0_212-release-1586-b4-5784211)
> 
> [✓] VS Code (version 1.44.0)
> 
>     • VS Code at /Applications/Visual Studio Code.app/Contents
> 
>     • Flutter extension version 3.9.1
> 
> [✓] Connected device (4 available)
> 
>     • SM M305F   • 32003c30dc19668f • android-arm64  • Android 10 (API 29)
> 
>     • macOS      • macOS            • darwin-x64     • Mac OS X 10.15.4 19E287
> 
>     • Chrome     • chrome           • web-javascript • Google Chrome
> 
>       81.0.4044.92
> 
>     • Web Server • web-server       • web-javascript • Flutter Tools
> 
> • No issues found!
> 
> ```
> 
> 
> 
> </details>
> 
> 
> 
> 

I am certain I set the assets correctly. Just to be sure:

```
assets:
    -assets/audio/
```

What else could be going wrong?

**Comment by TahaTesser** [comment]
Hi @VicHofs 
For issue related to the 3rd party plugin [audioplayers](https://pub.dev/packages/audioplayers#-readme-tab-) you may want to open an issue in the dedicated [GitHub](https://github.com/luanpotter/audioplayers/issues).

Closing, as this isn't an issue with Flutter itself,
if you disagree please write in the comments and I will reopen it 
Thank you

**Comment by VicHofs** [comment]
Turns out the package just doesn't support Windows yet. Sorry!
