### ISSUE TITLE
Golden tests generate incorrect result on web

### ISSUE THREAD

**Issue by dkwingsmt** [flutter/flutter#54511]
The `matchesGoldenFile` generates incorrect result when choosing `chrome` as the platform.

Reproduce: 
* Code:
```dart
  testWidgets('Web golden bug MWE', (WidgetTester tester) async {
    await tester.pumpWidget(
      Container(color: Colors.red)
    );

    expect(
      find.byType(Container),
      matchesGoldenFile('web_golden_bug_mwe.png'),
    );
  });
```

* Update with `flutter test --platform chrome --update-goldens <FILE_PATH>`

Unexpected result:

![web_golden_bug_mwe](https://user-images.githubusercontent.com/1596656/79031277-8d841600-7b52-11ea-9c8d-cb340500d98c.png)

**Comment by yjbanov** [comment]
@ferhatb Would you have time to look into this one. I'm tied up with several parallel things, so unable to take more without dropping the ball on others.

**Comment by ferhatb** [comment]
> @ferhatb Would you have time to look into this one? I'm tied up with several parallel things, so unable to take more without dropping the ball on others.
Same here. Lets discuss on next triage.

**Comment by TahaTesser** [comment]
<details> 
<summary>code sample</summary> 

```dart
// This is a basic Flutter widget test.
//
// To perform an interaction with a widget in your test, use the WidgetTester
// utility that Flutter provides. For example, you can send tap and scroll
// gestures. You can also use WidgetTester to find child widgets in the widget
// tree, read text, and verify that the values of widget properties are correct.

import 'package:flutter/material.dart';
import 'package:flutter_test/flutter_test.dart';

import 'package:master_flutter/main.dart';

void main() {
  testWidgets('Web golden bug MWE', (WidgetTester tester) async {
    await tester.pumpWidget(Container(color: Colors.red));

    expect(
      find.byType(Container),
      matchesGoldenFile('web_golden_bug_mwe.png'),
    );
  });
}

```

</details> 

<details> 
<summary>flutter doctor -v</summary> 

```
[✓] Flutter (Channel master, 1.22.0-10.0.pre.65, on Mac OS X 10.15.6 19G2021,
    locale en-GB)
    • Flutter version 1.22.0-10.0.pre.65 at
      /Users/tahatesser/Code/flutter_master
    • Framework revision 2032a448ed (8 hours ago), 2020-09-02 23:36:19 -0700
    • Engine revision 165abef0a2
    • Dart version 2.10.0 (build 2.10.0-77.0.dev)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/tahatesser/Code/sdk
    • Platform android-29, build-tools 29.0.2
    • ANDROID_HOME = /Users/tahatesser/Code/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.7)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.7, Build version 11E801a
    • CocoaPods version 1.9.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 48.1.2
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.48.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.13.2

[✓] Connected device (5 available)
    • Taha’s iPhone (mobile) • 00008020-001059882212002E            • ios
      • iOS 13.7
    • iPhone 11 (mobile)     • EDB19945-0B9F-4A6E-BAA1-425E68E3B6D6 • ios
      • com.apple.CoreSimulator.SimRuntime.iOS-13-7 (simulator)
    • macOS (desktop)        • macos                                • darwin-x64
      • Mac OS X 10.15.6 19G2021
    • Web Server (web)       • web-server                           •
      web-javascript • Flutter Tools
    • Chrome (web)           • chrome                               •
      web-javascript • Google Chrome 85.0.4183.83

• No issues found!
```

</details>

**Comment by danagbemava-nc** [comment]
Hi @dkwingsmt, I'm trying to validate if this issue still exists in flutter. 

When I run `flutter test --platform chrome --update-goldens` (without specifying the file path), the test passes but if include the `<FILE_PATH>` I get an error.  

Without passing the file path, the screenshote below is generated, similar to if I ran the command without the `--platform` flag. 

Can you please confirm if this is the expected result?

<img width="346" alt="Screenshot 2024-04-26 at 10 24 06" src="https://github.com/flutter/flutter/assets/88313112/0d771986-7a3c-4648-a3a9-b82130a8ec89">



<details>
<summary>logs</summary>

```
org-dartlang-app:///web_golden_bug_mwe.png:1:1: Error: Unable to decode bytes as UTF-8.
�PNG
^
org-dartlang-app:///web_golden_bug_mwe.png:2:1: Error: The control character U+001A can only be used in strings and comments.

^
org-dartlang-app:///web_golden_bug_mwe.png:2:2: Error: The control character U+0000 can only be used in strings and comments.

 ^...
Crash when formatting: [AsciiControlCharacter] The control character U+0000 can only be used in strings and comments.
RangeError (index): Invalid value: Not in inclusive range 0..20902: 20903
#0      _StringBase.[] (dart:core-patch/string_patch.dart:274)
#1      Source.getTextLine (package:kernel/ast.dart:14859)
#2      getSourceLine (package:front_end/src/fasta/messages.dart:28)
#3      format (package:front_end/src/fasta/command_line_reporting.dart:85)
#4      ProcessedOptions.format (package:front_end/src/base/processed_options.dart:230)
#5      ProcessedOptions.report (package:front_end/src/base/processed_options.dart:250)
#6      CompilerContext.report (package:front_end/src/fasta/compiler_context.dart:64)
#7      SourceLoader.addMessage (package:front_end/src/fasta/source/source_loader.dart:772)
#8      SourceLoader.addProblem (package:front_end/src/fasta/source/source_loader.dart:727)
#9      LibraryBuilderImpl.addProblem (package:front_end/src/fasta/builder/library_builder.dart:281)
#10     SourceLibraryBuilder.addProblem (package:front_end/src/fasta/source/source_library_builder.dart:1913)
#11     SourceLoader.tokenize (package:front_end/src/fasta/source/source_loader.dart:971)
<asynchronous suspension>
#12     SourceLoader.buildOutline (package:front_end/src/fasta/source/source_loader.dart:1213)
<asynchronous suspension>
#13     SourceLoader.buildOutlines (package:front_end/src/fasta/source/source_loader.dart:1038)
<asynchronous suspension>
#14     KernelTarget.computeNeededPrecompilations.<anonymous closure> (package:front_end/src/fasta/kernel/kernel_target.dart:339)
<asynchronous suspension>
#15     withCrashReporting (package:front_end/src/fasta/crash.dart:133)
<asynchronous suspension>
#16     KernelTarget.computeNeededPrecompilations (package:front_end/src/fasta/kernel/kernel_target.dart:337)
<asynchronous suspension>
#17     IncrementalCompiler.computeDelta.<anonymous closure> (package:front_end/src/fasta/incremental_compiler.dart:343)
<asynchronous suspension>
#18     CompilerContext.clear (package:front_end/src/fasta/compiler_context.dart:130)
<asynchronous suspension>
#19     IncrementalCompiler.compile (package:vm/incremental_compiler.dart:77)
<asynchronous suspension>
#20     FrontendCompiler.compile (package:frontend_server/frontend_server.dart:638)
<asynchronous suspension>
#21     listenAndCompile.<anonymous closure> (package:frontend_server/frontend_server.dart:1388)
<asynchronous suspension>

Unhandled exception:
Crash when compiling org-dartlang-app:///web_golden_bug_mwe.png at character offset 12:
RangeError (index): Invalid value: Not in inclusive range 0..20902: 20903

#0      _StringBase.[] (dart:core-patch/string_patch.dart:274)
#1      Source.getTextLine (package:kernel/ast.dart:14859)
#2      getSourceLine (package:front_end/src/fasta/messages.dart:28)
#3      format (package:front_end/src/fasta/command_line_reporting.dart:85)
#4      ProcessedOptions.format (package:front_end/src/base/processed_options.dart:230)
#5      ProcessedOptions.report (package:front_end/src/base/processed_options.dart:250)
#6      CompilerContext.report (package:front_end/src/fasta/compiler_context.dart:64)
#7      SourceLoader.addMessage (package:front_end/src/fasta/source/source_loader.dart:772)
#8      SourceLoader.addProblem (package:front_end/src/fasta/source/source_loader.dart:727)
#9      LibraryBuilderImpl.addProblem (package:front_end/src/fasta/builder/library_builder.dart:281)
#10     SourceLibraryBuilder.addProblem (package:front_end/src/fasta/source/source_library_builder.dart:1913)
#11     SourceLoader.tokenize (package:front_end/src/fasta/source/source_loader.dart:971)
<asynchronous suspension>
#12     SourceLoader.buildOutline (package:front_end/src/fasta/source/source_loader.dart:1213)
<asynchronous suspension>
#13     SourceLoader.buildOutlines (package:front_end/src/fasta/source/source_loader.dart:1038)
<asynchronous suspension>
#14     KernelTarget.computeNeededPrecompilations.<anonymous closure> (package:front_end/src/fasta/kernel/kernel_target.dart:339)
<asynchronous suspension>
#15     withCrashReporting (package:front_end/src/fasta/crash.dart:133)
<asynchronous suspension>
#16     KernelTarget.computeNeededPrecompilations (package:front_end/src/fasta/kernel/kernel_target.dart:337)
<asynchronous suspension>
#17     IncrementalCompiler.computeDelta.<anonymous closure> (package:front_end/src/fasta/incremental_compiler.dart:343)
<asynchronous suspension>
#18     CompilerContext.clear (package:front_end/src/fasta/compiler_context.dart:130)
<asynchronous suspension>
#19     IncrementalCompiler.compile (package:vm/incremental_compiler.dart:77)
<asynchronous suspension>
#20     FrontendCompiler.compile (package:frontend_server/frontend_server.dart:638)
<asynchronous suspension>
#21     listenAndCompile.<anonymous closure> (package:frontend_server/frontend_server.dart:1388)
<asynchronous suspension>
the Dart compiler exited unexpectedly.
Failed to compile
Failed to compile
```
</details>
