### ISSUE TITLE
Cannot find kernel2js compiler

### ISSUE THREAD

**Issue by liudonghua123** [flutter/flutter#54520]
## Steps to Reproduce

I updated flutter to the latest master channel, and try run my app in chrome devices, then it throw me a `Exception: Cannot find kernel2js compiler for packages/flutter/src/material/icon_button.dart. Compilers are avaiable for modules:  ()` exception. I did not change any code, so I think it might be the problem of flutter upgrade issue.

**Expected results:** 
Run normally like a few day ago.

**Actual results:** 
Run failed with the following errors.

![image](https://user-images.githubusercontent.com/2276718/79036278-59176500-7bf9-11ea-8e45-a731c4b3374c.png)

However I can run it in windows device, I have not test in android.

<details>
  <summary>Logs</summary>

```
Unhandled exception:
Exception: Cannot find kernel2js compiler for packages/flutter/src/material/icon_button.dart. Compilers are avaiable for modules: 
	()
#0      FrontendCompiler.compileExpressionToJs  (package:frontend_server/frontend_server.dart:921:9)
#1      _FlutterFrontendCompiler.compileExpressionToJs  (package:flutter_frontend_server/server.dart:84:22)
#2      listenAndCompile.<anonymous closure>  (package:frontend_server/frontend_server.dart:1308:18)
<asynchronous suspension>
#3      listenAndCompile.<anonymous closure> (package:frontend_server/frontend_server.dart)
#4      _RootZone.runUnaryGuarded  (dart:async/zone.dart:1374:10)
#5      _BufferingStreamSubscription._sendData  (dart:async/stream_impl.dart:339:11)
#6      _BufferingStreamSubscription._add  (dart:async/stream_impl.dart:266:7)

#7      _SinkTransformerStreamSubscription._add  (dart:async/stream_transformers.dart:70:11)
#8      _EventSinkWrapper.add  (dart:async/stream_transformers.dart:17:11)
#9      _StringAdapterSink.add  (dart:convert/string_conversion.dart:238:11)
......
```

</details>

**Comment by liudonghua123** [comment]
![image](https://user-images.githubusercontent.com/2276718/79036550-b57b8400-7bfb-11ea-8602-43245bc1281d.png)

I updated the flutter, same errors.

**Comment by jonahwilliams** [comment]
This is an error from expression evaluations, which is not completely supported in Flutter for web yet. FYI @annagrin

**Comment by liudonghua123** [comment]
I switch the IDE from vscode to android studio, then this error disappeared. It's really strange.
Even I reinstalled the flutter plugin in vscode, I still can't run it in vscode.

**Comment by liudonghua123** [comment]
My mistake, it could not run in chrome in android studio with the same errors. But I can run `flutter build web` without errors.

I also confused about the devices chrome and web server, what's difference between them.

**Comment by annagrin** [comment]
Looks like expression evaluation was invoked by VSCode (maybe when hovering over or a watch window, or a conditional breakpoint, or direct expression evaluation) and failed. Will see how I can make the failure not crash the frontend server.

**Comment by liudonghua123** [comment]
I see it is merged to the master branch, and I upgrade the flutter, and run in vscode (add --web-enable-expression-evaluation in the Flutter Additional Args) or cmd shell via `--web-enable-expression-evaluation`, but I still got the same error.

```
D:\code\flutter\colorful_classroom_app>flutter run -d chrome --web-enable-expression-evaluation
Launching lib\main.dart on Chrome in debug mode...
Syncing files to device Chrome...
26,678ms (!)
Debug service listening on ws://127.0.0.1:53831/l66xFkailPM=

Warning: Flutter's support for web development is not stable yet and hasn't
been thoroughly tested in production environments.
For more information see https://flutter.dev/web

  To hot restart changes while running, press "r". To hot restart (and refresh the browser), press "R".
For a more detailed help message, press "h". To quit, press "q".
══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
The following JSNoSuchMethodError was thrown building IconTheme(color: Color(0xffffffff)):
NoSuchMethodError: invalid member on null: 'dependOnInheritedWidgetOfExactType'

The relevant error-causing widget was:
  MaterialApp file:///D:/code/flutter/colorful_classroom_app/lib/app.dart:37:18

When the exception was thrown, this was the stack:
packages/flutter/src/material/theme.dart 128:51                                                                       of
packages/fluro/src/router.dart 130:36                                                                                 <fn>
packages/fluro/src/router.dart 183:21                                                                                 matchRoute
packages/fluro/src/router.dart 223:9                                                                                  generator 
packages/flutter/src/widgets/app.dart 999:36
[_onGenerateRoute]
packages/flutter/src/widgets/navigator.dart 3138:44
[_routeNamed]
packages/flutter/src/widgets/navigator.dart 2183:27
defaultGenerateInitialRoutes
packages/flutter/src/widgets/navigator.dart 2582:39                                                                   initState  
packages/flutter/src/widgets/framework.dart 4644:58
[_firstBuild]
packages/flutter/src/widgets/framework.dart 4480:5                                                                    mount
packages/flutter/src/widgets/framework.dart 3450:13
inflateWidget
packages/flutter/src/widgets/framework.dart 3218:18                                                                   updateChildpackages/flutter/src/widgets/framework.dart 4531:16
performRebuild
packages/flutter/src/widgets/framework.dart 4222:5                                                                    rebuild    
packages/flutter/src/widgets/framework.dart 4485:5
[_firstBuild]
packages/flutter/src/widgets/framework.dart 4480:5                                                                    mount      
packages/flutter/src/widgets/framework.dart 3450:13
inflateWidget
packages/flutter/src/widgets/framework.dart 3218:18                                                                   updateChildpackages/flutter/src/widgets/framework.dart 4531:16
performRebuild
packages/flutter/src/widgets/framework.dart 4222:5                                                                    rebuild
packages/flutter/src/widgets/framework.dart 4485:5
[_firstBuild]
packages/flutter/src/widgets/framework.dart 4480:5                                                                    mount      
packages/flutter/src/widgets/framework.dart 3450:13
inflateWidget
packages/flutter/src/widgets/framework.dart 3218:18                                                                   updateChildpackages/flutter/src/widgets/framework.dart 4531:16
performRebuild
packages/flutter/src/widgets/framework.dart 4222:5                                                                    rebuild    
packages/flutter/src/widgets/framework.dart 4485:5
[_firstBuild]
packages/flutter/src/widgets/framework.dart 4480:5                                                                    mount      
packages/flutter/src/widgets/framework.dart 3450:13
inflateWidget
packages/flutter/src/widgets/framework.dart 3218:18                                                                   updateChildpackages/flutter/src/widgets/framework.dart 4531:16
performRebuild
packages/flutter/src/widgets/framework.dart 4222:5                                                                    rebuild    
packages/flutter/src/widgets/framework.dart 4485:5
[_firstBuild]
packages/flutter/src/widgets/framework.dart 4480:5                                                                    mount
packages/flutter/src/widgets/framework.dart 3450:13
inflateWidget
packages/flutter/src/widgets/framework.dart 3218:18                                                                   updateChildpackages/flutter/src/widgets/framework.dart 4531:16
performRebuild
packages/flutter/src/widgets/framework.dart 4222:5                                                                    rebuild    
packages/flutter/src/widgets/framework.dart 4485:5
[_firstBuild]
packages/flutter/src/widgets/framework.dart 4480:5                                                                    mount      
packages/flutter/src/widgets/framework.dart 3450:13
inflateWidget
packages/flutter/src/widgets/framework.dart 3218:18                                                                   updateChildpackages/flutter/src/widgets/framework.dart 4531:16
performRebuild
packages/flutter/src/widgets/framework.dart 4222:5                                                                    rebuild    
packages/flutter/src/widgets/framework.dart 4485:5
[_firstBuild]
packages/flutter/src/widgets/framework.dart 4480:5                                                                    mount      
packages/flutter/src/widgets/framework.dart 3450:13
inflateWidget
packages/flutter/src/widgets/framework.dart 3218:18                                                                   updateChildpackages/flutter/src/widgets/framework.dart 4531:16
performRebuild
packages/flutter/src/widgets/framework.dart 4679:11
performRebuild
packages/flutter/src/widgets/framework.dart 4222:5                                                                    rebuild
packages/flutter/src/widgets/framework.dart 4485:5
[_firstBuild]
packages/flutter/src/widgets/framework.dart 4670:11
[_firstBuild]
packages/flutter/src/widgets/framework.dart 4480:5                                                                    mount      
packages/flutter/src/widgets/framework.dart 3450:13
inflateWidget
packages/flutter/src/widgets/framework.dart 3218:18                                                                   updateChildpackages/flutter/src/widgets/framework.dart 4531:16
performRebuild
packages/flutter/src/widgets/framework.dart 4222:5                                                                    rebuild    
packages/flutter/src/widgets/framework.dart 4485:5
[_firstBuild]
packages/flutter/src/widgets/framework.dart 4480:5                                                                    mount
packages/flutter/src/widgets/framework.dart 3450:13
inflateWidget
packages/flutter/src/widgets/framework.dart 3218:18                                                                   updateChildpackages/flutter/src/widgets/framework.dart 4531:16
performRebuild
packages/flutter/src/widgets/framework.dart 4222:5                                                                    rebuild    
packages/flutter/src/widgets/framework.dart 4485:5
[_firstBuild]
packages/flutter/src/widgets/framework.dart 4480:5                                                                    mount
packages/flutter/src/widgets/framework.dart 3450:13
inflateWidget
packages/flutter/src/widgets/framework.dart 3218:18                                                                   updateChildpackages/flutter/src/widgets/framework.dart 5834:14                                                                   mount      
packages/flutter/src/widgets/framework.dart 3450:13
inflateWidget
packages/flutter/src/widgets/framework.dart 3218:18                                                                   updateChildpackages/flutter/src/widgets/framework.dart 4531:16
performRebuild
packages/flutter/src/widgets/framework.dart 4222:5                                                                    rebuild    
packages/flutter/src/widgets/framework.dart 4485:5
[_firstBuild]
packages/flutter/src/widgets/framework.dart 4480:5                                                                    mount      
packages/flutter/src/widgets/framework.dart 3450:13
inflateWidget
packages/flutter/src/widgets/framework.dart 3218:18                                                                   updateChildpackages/flutter/src/widgets/framework.dart 4531:16
performRebuild
packages/flutter/src/widgets/framework.dart 4222:5                                                                    rebuild    
packages/flutter/src/widgets/framework.dart 4485:5
[_firstBuild]
packages/flutter/src/widgets/framework.dart 4480:5                                                                    mount
packages/flutter/src/widgets/framework.dart 3450:13
inflateWidget
packages/flutter/src/widgets/framework.dart 3218:18                                                                   updateChildpackages/flutter/src/widgets/framework.dart 4531:16
performRebuild
packages/flutter/src/widgets/framework.dart 4222:5                                                                    rebuild    
packages/flutter/src/widgets/framework.dart 4485:5
[_firstBuild]
packages/flutter/src/widgets/framework.dart 4480:5                                                                    mount      
packages/flutter/src/widgets/framework.dart 3450:13
inflateWidget
packages/flutter/src/widgets/framework.dart 3218:18                                                                   updateChildpackages/flutter/src/widgets/framework.dart 4531:16
performRebuild
packages/flutter/src/widgets/framework.dart 4222:5                                                                    rebuild    
packages/flutter/src/widgets/framework.dart 4485:5
[_firstBuild]
packages/flutter/src/widgets/framework.dart 4480:5                                                                    mount      
packages/flutter/src/widgets/framework.dart 3450:13
inflateWidget
packages/flutter/src/widgets/framework.dart 3218:18                                                                   updateChildpackages/flutter/src/widgets/framework.dart 4531:16
performRebuild
packages/flutter/src/widgets/framework.dart 4222:5                                                                    rebuild
packages/flutter/src/widgets/framework.dart 4485:5
[_firstBuild]
packages/flutter/src/widgets/framework.dart 4480:5                                                                    mount      
packages/flutter/src/widgets/framework.dart 3450:13
inflateWidget
packages/flutter/src/widgets/framework.dart 3218:18                                                                   updateChildpackages/flutter/src/widgets/framework.dart 5834:14                                                                   mount
packages/flutter/src/widgets/framework.dart 3450:13
inflateWidget
packages/flutter/src/widgets/framework.dart 3215:20                                                                   updateChildpackages/flutter/src/widgets/framework.dart 4531:16
performRebuild
packages/flutter/src/widgets/framework.dart 4679:11
performRebuild
packages/flutter/src/widgets/framework.dart 4222:5                                                                    rebuild
packages/flutter/src/widgets/framework.dart 2627:31                                                                   buildScope 
packages/flutter/src/widgets/binding.dart 864:20                                                                      drawFrame
packages/flutter/src/rendering/binding.dart 284:5
[_handlePersistentFrameCallback]
packages/flutter/src/scheduler/binding.dart 1074:15
[_invokeFrameCallback]
packages/flutter/src/scheduler/binding.dart 1013:9
handleDrawFrame
packages/flutter/src/scheduler/binding.dart 822:7                                                                     <fn>       
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/_internal/js_dev_runtime/private/isolate_helper.dart 50:19
internalCallback

════════════════════════════════════════════════════════════════════════════════════════════════════

```

**Comment by annagrin** [comment]
@liudonghua123 There are two issues mixed in here I believe - an unexpected exception in the library and a secondary crash of the frontend server when VSCode was calling expression evaluation (supposedly to display the details of the exception?). Looks like the expression evaluation bug is fixed, and you are only seeing the original exception. To handle it properly it might be better to open a separate issue, so you get all the notifications related to that problem. My bad for not recognizing the mixup - I was under impression the exception is expected.
