### ISSUE TITLE
[webview_flutter] java.lang.SecurityException in Android 10

### ISSUE THREAD

**Issue by rquanx** [flutter/flutter#54575]
run webview with my webapp, after upgrading the system from Android 9 to Android 10, when i click the input to pop up the keyboard, it often gets stuck.

flutter doctor:
```
[√] Flutter (Channel stable, v1.12.13+hotfix.9, on Microsoft Windows [Version 10.0.18363.720], locale zh-CN)
    • Flutter version 1.12.13+hotfix.9 at D:\work\flutter
    • Framework revision f139b11009 (12 days ago), 2020-03-30 13:57:30 -0700
    • Engine revision af51afceb8
    • Dart version 2.7.2


[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at C:\Users\rq\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: D:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)
    • All Android licenses accepted.

[√] Android Studio (version 3.6)
    • Android Studio at D:\Program Files\Android\Android Studio
    • Flutter plugin version 44.0.2
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)

[√] VS Code, 64-bit edition (version 1.44.0)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Flutter extension version 3.9.1

[√] Connected device (1 available)
    • MI 8 • d6b106b9 • android-arm64 • Android 10 (API 29)
```

error stack:
```
E/WindowManager(30717): BadTokenException or InvalidDisplayException, clean up.
E/MethodChannel#flutter/platform_views(30717): Failed to handle method call
E/MethodChannel#flutter/platform_views(30717): java.lang.SecurityException: Neither user 10585 nor current process has android.permission.WAKE_LOCK.
E/MethodChannel#flutter/platform_views(30717): 	at android.os.Parcel.createException(Parcel.java:2074)
E/MethodChannel#flutter/platform_views(30717): 	at android.os.Parcel.readException(Parcel.java:2042)
E/MethodChannel#flutter/platform_views(30717): 	at android.os.Parcel.readException(Parcel.java:1990)
E/MethodChannel#flutter/platform_views(30717): 	at android.view.IWindowSession$Stub$Proxy.addToDisplay(IWindowSession.java:1242)
E/MethodChannel#flutter/platform_views(30717): 	at android.view.ViewRootImpl.setView(ViewRootImpl.java:886)
E/MethodChannel#flutter/platform_views(30717): 	at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:387)
E/MethodChannel#flutter/platform_views(30717): 	at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:96)
E/MethodChannel#flutter/platform_views(30717): 	at android.app.Dialog.show(Dialog.java:344)
E/MethodChannel#flutter/platform_views(30717): 	at android.app.Presentation.show(Presentation.java:250)
E/MethodChannel#flutter/platform_views(30717): 	at io.flutter.plugin.platform.VirtualDisplayController.resize(VirtualDisplayController.java:150)
E/MethodChannel#flutter/platform_views(30717): 	at io.flutter.plugin.platform.PlatformViewsController$1.resizePlatformView(PlatformViewsController.java:180)
E/MethodChannel#flutter/platform_views(30717): 	at io.flutter.embedding.engine.systemchannels.PlatformViewsChannel$1.resize(PlatformViewsChannel.java:129)
E/MethodChannel#flutter/platform_views(30717): 	at io.flutter.embedding.engine.systemchannels.PlatformViewsChannel$1.onMethodCall(PlatformViewsChannel.java:66)
E/MethodChannel#flutter/platform_views(30717): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:231)
E/MethodChannel#flutter/platform_views(30717): 	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:93)
E/MethodChannel#flutter/platform_views(30717): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:642)
E/MethodChannel#flutter/platform_views(30717): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/MethodChannel#flutter/platform_views(30717): 	at android.os.MessageQueue.next(MessageQueue.java:336)
E/MethodChannel#flutter/platform_views(30717): 	at android.os.Looper.loop(Looper.java:181)
E/MethodChannel#flutter/platform_views(30717): 	at android.app.ActivityThread.main(ActivityThread.java:7520)
E/MethodChannel#flutter/platform_views(30717): 	at java.lang.reflect.Method.invoke(Native Method)
E/MethodChannel#flutter/platform_views(30717): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
E/MethodChannel#flutter/platform_views(30717): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)
E/MethodChannel#flutter/platform_views(30717): Caused by: android.os.RemoteException: Remote stack trace:
E/MethodChannel#flutter/platform_views(30717): 	at android.app.ContextImpl.enforce(ContextImpl.java:1906)
E/MethodChannel#flutter/platform_views(30717): 	at android.app.ContextImpl.enforceCallingOrSelfPermission(ContextImpl.java:1934)
E/MethodChannel#flutter/platform_views(30717): 	at com.android.server.power.PowerManagerService$BinderService.acquireWakeLock(PowerManagerService.java:4418)
E/MethodChannel#flutter/platform_views(30717): 	at android.os.PowerManager$WakeLock.acquireLocked(PowerManager.java:2188)
E/MethodChannel#flutter/platform_views(30717): 	at android.os.PowerManager$WakeLock.acquire(PowerManager.java:2154)
```

**Comment by rquanx** [comment]
same issue in huawei  YAL AL00 Android 10

```
$ flutter doctor -v
[√] Flutter (Channel stable, v1.12.13+hotfix.9, on Microsoft Windows [Version 10.0.18363.720], locale zh-CN)
    • Flutter version 1.12.13+hotfix.9 at D:\work\flutter
    • Framework revision f139b11009 (13 days ago), 2020-03-30 13:57:30 -0700
    • Engine revision af51afceb8
    • Dart version 2.7.2

 
[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at C:\Users\rq\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: D:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)
    • All Android licenses accepted.

[√] Android Studio (version 3.6)
    • Android Studio at D:\Program Files\Android\Android Studio
    • Flutter plugin version 44.0.2
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)

[√] VS Code, 64-bit edition (version 1.44.0)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Flutter extension version 3.9.1

[√] Connected device (1 available)
    • YAL AL00 • STS0219523002770 • android-arm64 • Android 10 (API 29)
```

```
E/InputMethodManager(30333): b/117267690: Failed to get fallback IMM with expected displayId=11 actual IMM#displayId=0 view=io.flutter.plugins.webviewflutter.InputAwareWebView{ac92402 VFEDHVC.. .F...... 0,0-1080,2232}
E/InputMethodManager(30333): b/117267690: Failed to get fallback IMM with expected displayId=11 actual IMM#displayId=0 view=io.flutter.plugins.webviewflutter.InputAwareWebView{ac92402 VFEDHVC.. .F...... 0,0-1080,2232}
E/InputMethodManager(30333): b/117267690: Failed to get fallback IMM with expected displayId=11 actual IMM#displayId=0 view=io.flutter.plugins.webviewflutter.InputAwareWebView{ac92402 VFEDHVC.. .F...... 0,0-1080,2232}
E/InputMethodManager(30333): b/117267690: Failed to get fallback IMM with expected displayId=11 actual IMM#displayId=0 view=io.flutter.plugins.webviewflutter.InputAwareWebView{ac92402 VFEDHVC.. ......ID 0,0-1080,2232}
E/InputMethodManager(30333): b/117267690: Failed to get fallback IMM with expected displayId=11 actual IMM#displayId=0 view=io.flutter.plugins.webviewflutter.InputAwareWebView{ac92402 VFEDHVC.. ......ID 0,0-1080,2232}
E/MethodChannel#flutter/platform_views(30333): Failed to handle method call
E/MethodChannel#flutter/platform_views(30333): java.lang.SecurityException: Neither user 10221 nor current process has android.permission.WAKE_LOCK.
E/MethodChannel#flutter/platform_views(30333): 	at android.os.Parcel.createException(Parcel.java:2071)
E/MethodChannel#flutter/platform_views(30333): 	at android.os.Parcel.readException(Parcel.java:2039)
E/MethodChannel#flutter/platform_views(30333): 	at android.os.Parcel.readException(Parcel.java:1987)
E/MethodChannel#flutter/platform_views(30333): 	at android.view.IWindowSession$Stub$Proxy.addToDisplay(IWindowSession.java:1242)
E/MethodChannel#flutter/platform_views(30333): 	at android.view.ViewRootImpl.setView(ViewRootImpl.java:943)
E/MethodChannel#flutter/platform_views(30333): 	at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:428)
E/MethodChannel#flutter/platform_views(30333): 	at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:118)
E/MethodChannel#flutter/platform_views(30333): 	at android.app.Dialog.show(Dialog.java:448)
E/MethodChannel#flutter/platform_views(30333): 	at android.app.Presentation.show(Presentation.java:250)
E/MethodChannel#flutter/platform_views(30333): 	at io.flutter.plugin.platform.VirtualDisplayController.resize(VirtualDisplayController.java:150)
E/MethodChannel#flutter/platform_views(30333): 	at io.flutter.plugin.platform.PlatformViewsController$1.resizePlatformView(PlatformViewsController.java:180)
E/MethodChannel#flutter/platform_views(30333): 	at io.flutter.embedding.engine.systemchannels.PlatformViewsChannel$1.resize(PlatformViewsChannel.java:129)
E/MethodChannel#flutter/platform_views(30333): 	at io.flutter.embedding.engine.systemchannels.PlatformViewsChannel$1.onMethodCall(PlatformViewsChannel.java:66)
E/MethodChannel#flutter/platform_views(30333): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:231)
E/MethodChannel#flutter/platform_views(30333): 	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:93)
E/MethodChannel#flutter/platform_views(30333): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:642)
E/MethodChannel#flutter/platform_views(30333): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/MethodChannel#flutter/platform_views(30333): 	at android.os.MessageQueue.next(MessageQueue.java:363)
E/MethodChannel#flutter/platform_views(30333): 	at android.os.Looper.loop(Looper.java:173)
E/MethodChannel#flutter/platform_views(30333): 	at android.app.ActivityThread.main(ActivityThread.java:8147)
E/MethodChannel#flutter/platform_views(30333): 	at java.lang.reflect.Method.invoke(Native Method)
E/MethodChannel#flutter/platform_views(30333): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
E/MethodChannel#flutter/platform_views(30333): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1101)
E/MethodChannel#flutter/platform_views(30333): Caused by: android.os.RemoteException: Remote stack trace:
E/MethodChannel#flutter/platform_views(30333): 	at android.app.ContextImpl.enforce(libmapleframework.so:8262536)
E/MethodChannel#flutter/platform_views(30333): 	at android.app.ContextImpl.enforceCallingOrSelfPermission(libmapleframework.so:8260220)
E/MethodChannel#flutter/platform_views(30333): 	at com.android.server.power.PowerManagerService$BinderService.acquireWakeLock(libmapleservices.so:6844596)
E/MethodChannel#flutter/platform_views(30333): 	at android.os.PowerManager$WakeLock.acquireLocked(libmapleframework.so:7453704)
E/MethodChannel#flutter/platform_views(30333): 	at android.os.PowerManager$WakeLock.acquire(libmapleframework.so:7410536)
E/MethodChannel#flutter/platform_views(30333):
```

**Comment by rquanx** [comment]
fix with add <uses-permission android:name="android.permission.WAKE_LOCK" /> into  AndroidManifest.xml

**Comment by rquanx** [comment]
fix with add ```<uses-permission android:name="android.permission.WAKE_LOCK" />``` into  AndroidManifest.xml
