### ISSUE TITLE
Error running my first flutter app "Finished with error: ProcessException: Process "

### ISSUE THREAD

**Issue by PaulOwusu** [flutter/flutter#54578]
Help me fix it
My console displayed

```bash
Launching lib\main.dart on DRA LX5 in debug mode...
Initializing gradle...
Finished with error: ProcessException: Process "C:\Users\PAUL\AndroidStudioProjects\flutter_app1h\android\gradlew.bat" exited abnormally:
Unzipping C:\Users\PAUL\.gradle\wrapper\dists\gradle-4.10.2-all\9fahxiiecdb76a5g3aw9oi8rv\gradle-4.10.2-all.zip to C:\Users\PAUL\.gradle\wrapper\dists\gradle-4.10.2-all\9fahxiiecdb76a5g3aw9oi8rv

Exception in thread "main" java.util.zip.ZipException: error in opening zip file
	at java.util.zip.ZipFile.open(Native Method)
	at java.util.zip.ZipFile.<init>(ZipFile.java:225)
	at java.util.zip.ZipFile.<init>(ZipFile.java:155)
	at java.util.zip.ZipFile.<init>(ZipFile.java:169)
	at org.gradle.wrapper.Install.unzip(Install.java:214)
	at org.gradle.wrapper.Install.access$600(Install.java:27)
	at org.gradle.wrapper.Install$1.call(Install.java:74)
	at org.gradle.wrapper.Install$1.call(Install.java:48)
	at org.gradle.wrapper.ExclusiveFileAccessManager.access(ExclusiveFileAccessManager.java:65)
	at org.gradle.wrapper.Install.createDist(Install.java:48)
	at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:128)
	at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:61)
  Command: C:\Users\PAUL\AndroidStudioProjects\flutter_app1h\android\gradlew.bat -v

```

**Comment by iapicca** [comment]
Hi @PaulOwusu  
can you please provide your `flutter doctor -v` , 
and your `flutter run --verbose` 
Thank you

possible workaround https://github.com/flutter/flutter/issues/25116

**Comment by VladyslavBondarenko** [comment]
@PaulOwusu 
I hope you've solved the issue.
Could everyone who still has this problem try do delete dists from `.gradle/wrapper/dists` in your user directory and run app anew after this.
https://github.com/flutter/flutter/issues/13645#issuecomment-587455792
If it doesn't help, please file a new issue with the exact descriptions what happens, logs and the output of `flutter doctor -v` please.
