### ISSUE TITLE
url_launcher (iOS only): PlatformException when attempting opening standard URL

### ISSUE THREAD

**Issue by hallidev** [flutter/flutter#54592]
I am attempting to call my endsession OIDC endpoint using the url_launcher package (5.4.2). Everything works as expected on Android.

On iOS, I'm receiving a PlatformException.

## Steps to Reproduce

1: Attempt to open the following URL (slightly anonymized) via ```await launch(url);``` from the url_launcher package:

https://my.identityprovider.com/connect/endsession?id_token_hint=eyJhbGciOiJSUzI1NiIsImtpZCI6ImN1UWdac3ZWeXdEWE5XNU92czBMeEEiLCJ0eXAiOiJKV1QifQ.eyJuYmYiOjE1ODY2OTM3MzAsImV4cCI6MTU4NjY5NDAzMCwiaXNzIjoiaHR0cHM6Ly9jYXZpZGVudGl0eS1kZXYuYXp1cmV3ZWJzaXRlcy5uZXQiLCJhdWQiOiJjZl9pb3MiLCJub25jZSI6IlVzMmhrUi14d0pQNzVkUWt6Q1hOR0l2bUcxLVp1eDd6end4LXhDam1aSnciLCJpYXQiOjE1ODY2OTM3MzAsImF0X2hhc2giOiJKZ0hFdEZ5WjVueDJVQUV4aHcxdWd3Iiwic19oYXNoIjoiLXlzYUFHcWFaTHh3SGctLXRwLVBnUSIsInNpZCI6IndhbjJGM0dOUjA4RUJaWWpfRlg1aHciLCJzdWIiOiIxMDAwMSIsImF1dGhfdGltZSI6MTU4NjAwOTczNywiaWRwIjoibG9jYWwiLCJhbXIiOlsicHdkIl19.ZcEk6J-WD5wg4GmhYRDCuDbyKQqeBaNqf1vmSAwg9Qifyimcn19fkhAgdjHVmU4bSMaJTx-Qlr_Im7lAF7HBVPstj0fGRgy9CxADHpdSI82GIwjamQrkJ4MwXC_m75Q6-cx4oo9rGK4cTu5B7yTXbGJxK5R7ra8Kds2ONm4BBDfIGNR9cvBX0HSvQOGjIFkYNx-6ReLidaLdM7nklKbYjor5yXV5GfkYmgfdKwnCQ4i_VmQleQ63G3ov1l3p8xkyUfk3WFEJOsMAZO1G7eKBl2bEGjELQXz6h0baoYIP7xV50A2HjN69FHkLj_q1NE2gUhT9cZBEBURAmCwdiCHhqA&post_logout_redirect_uri=com.mycompany.myapp://oidc-callback

**Expected results:**

Endpoint is called successfully and on completion redirects back to app. 

**Actual results:**

This works properly in Android. In iOS, I receive a PlatformException.

Having tried various combinations, the problem lies in the ```id_token_hint``` querystring parameter. I can send the exact URL minus that querystring parameter successfully in iOS. The ```id_token_hint``` parameter is properly URL encoded along with the rest of the URL.

Something inside here is causing the issues, but the exception doesn't give any details (see below):

```
id_token_hint=eyJhbGciOiJSUzI1NiIsImtpZCI6ImN1UWdac3ZWeXdEWE5XNU92czBMeEEiLCJ0eXAiOiJKV1QifQ.eyJuYmYiOjE1ODY2OTM3MzAsImV4cCI6MTU4NjY5NDAzMCwiaXNzIjoiaHR0cHM6Ly9jYXZpZGVudGl0eS1kZXYuYXp1cmV3ZWJzaXRlcy5uZXQiLCJhdWQiOiJjZl9pb3MiLCJub25jZSI6IlVzMmhrUi14d0pQNzVkUWt6Q1hOR0l2bUcxLVp1eDd6end4LXhDam1aSnciLCJpYXQiOjE1ODY2OTM3MzAsImF0X2hhc2giOiJKZ0hFdEZ5WjVueDJVQUV4aHcxdWd3Iiwic19oYXNoIjoiLXlzYUFHcWFaTHh3SGctLXRwLVBnUSIsInNpZCI6IndhbjJGM0dOUjA4RUJaWWpfRlg1aHciLCJzdWIiOiIxMDAwMSIsImF1dGhfdGltZSI6MTU4NjAwOTczNywiaWRwIjoibG9jYWwiLCJhbXIiOlsicHdkIl19.ZcEk6J-WD5wg4GmhYRDCuDbyKQqeBaNqf1vmSAwg9Qifyimcn19fkhAgdjHVmU4bSMaJTx-Qlr_Im7lAF7HBVPstj0fGRgy9CxADHpdSI82GIwjamQrkJ4MwXC_m75Q6-cx4oo9rGK4cTu5B7yTXbGJxK5R7ra8Kds2ONm4BBDfIGNR9cvBX0HSvQOGjIFkYNx-6ReLidaLdM7nklKbYjor5yXV5GfkYmgfdKwnCQ4i_VmQleQ63G3ov1l3p8xkyUfk3WFEJOsMAZO1G7eKBl2bEGjELQXz6h0baoYIP7xV50A2HjN69FHkLj_q1NE2gUhT9cZBEBURAmCwdiCHhqA
```

The total length of my URL is 1037 characters, which seems to be below any published URL limit I could find.

<details>
  <summary>Logs</summary>

```
flutter: PlatformException(Error, Error while launching https://my.identityprovider.com/connect/endsession?id_token_hint=eyJhbGciOiJSUzI1NiIsImtpZCI6ImN1UWdac3ZWeXdEWE5XNU92czBMeEEiLCJ0eXAiOiJKV1QifQ.eyJuYmYiOjE1ODY2OTQ0NTQsImV4cCI6MTU4NjY5NDc1NCwiaXNzIjoiaHR0cHM6Ly9jYXZpZGVudGl0eS1kZXYuYXp1cmV3ZWJzaXRlcy5uZXQiLCJhdWQiOiJjZl9pb3MiLCJpYXQiOjE1ODY2OTQ0NTQsImF0X2hhc2giOiI3aWZPRUtkSHhKR09RNFNvc251S1d3Iiwic3ViIjoiMTAwMDEiLCJhdXRoX3RpbWUiOjE1ODYwMDk3MzcsImlkcCI6ImxvY2FsIiwiYW1yIjpbInB3ZCJdfQ.fAc647J9uAIg9LmoQGttFh_Rq_J_a3nPdLrTNIvPuNVAtB7e-_510GP7eLIb88146N25_ukc1pIxEObVQEQCB1j22yrXMan95zCDlFXArqJZLXVRaZ_8R-Zx66KumpbSL7nIFfldxev16Y_ZzpNdd-6dEXNzsgO3spL1UYxH2i47cUWj483HkhsAPXrsiqLduTRqwVwcViIzx78O-VhDfRouUq-Nn03Wy8FcAvnbFy6rvFHWoA2BlepRalzZ480tSzvMoyPLRTEWTFJb4DVnsJqGrPrXkua2xknvi_4Q4Z9-cEKkH3X8kA3-LTgP_DvWnZZ6MJ1vT_j11v7mkOlC2Q&post_logout_redirect_uri=com.mycompany.myapp://oidc-callback, null)
flutter: #0      StandardMethodCodec.decodeEnvelope 
package:flutter/…/services/message_codecs.dart:569
flutter: #1      MethodChannel.invokeMethod 
package:flutter/…/services/platform_channel.dart:321
flutter: <asynchronous suspension>
flutter: #2      MethodChannelUrlLauncher.launch 
package:url_launcher_platform_interface/method_channel_url_launcher.dart:39
flutter: #3      launch 
package:url_launcher/url_launcher.dart:86
flutter: #4      AuthManager.signOut 
package:ceasefire_mobile/shared/auth_manager.dart:124
flutter: #5      UserDrawer.build.<anonymous closure> 
package:ceasefire_mobile/…/home/user_drawer.dart:177
flutter: #6      _InkResponseState._handleTap 
package:flutter/…/material/ink_well.dart:706
flutter: #7      _InkResponseState.build.<anonymous closure> 
package:flutter/…/material/ink_well.dart:789
flutter: #8      GestureRecognizer.invokeCallback 
package:flutter/…/gestures/recognizer.dart:182
flutter: #9      TapGestureRecognizer.handleTapUp 
package:flutter/…/gestures/tap.dart:486
flutter: #10     BaseTapGestureRecognizer._checkUp 
package:flutter/…/gestures/tap.dart:264
flutter: #11     BaseTapGestureRecognizer.acceptGesture 
package:flutter/…/gestures/tap.dart:236
flutter: #12     GestureArenaManager.sweep 
package:flutter/…/gestures/arena.dart:156
flutter: #13     GestureBinding.handleEvent 
package:flutter/…/gestures/binding.dart:222
flutter: #14     GestureBinding.dispatchEvent 
package:flutter/…/gestures/binding.dart:198
flutter: #15     GestureBinding._handlePointerEvent 
package:flutter/…/gestures/binding.dart:156
flutter: #16     GestureBinding._flushPointerEventQueue 
package:flutter/…/gestures/binding.dart:102
flutter: #17     GestureBinding._handlePointerDataPacket 
package:flutter/…/gestures/binding.dart:86
flutter: #18     _rootRunUnary  (dart:async/zone.dart:1138:13)
flutter: #19     _CustomZone.runUnary  (dart:async/zone.dart:1031:19)
flutter: #20     _CustomZone.runUnaryGuarded  (dart:async/zone.dart:933:7)
flutter: #21     _invoke1  (dart:ui/hooks.dart:273:10)
flutter: #22     _dispatchPointerDataPacket  (dart:ui/hooks.dart:182:5)
```

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, v1.12.13+hotfix.9, on Mac OS X 10.15.3 19D76, locale en-US)
[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/setup/#android-setup for detailed instructions).
      If the Android SDK has been installed to a custom location, set ANDROID_HOME to that location.
      You may also want to add it to your PATH environment variable.

[✓] Xcode - develop for iOS and macOS (Xcode 11.3.1)
[!] Android Studio (not installed)
[✓] VS Code (version 1.43.1)
```

</details>

**Comment by iapicca** [comment]
Hi @hallidev 
can you please provide your `flutter run --verbose` 
and a reproducible minimal code sample.
Thank you

**Comment by TahaTesser** [comment]
Hi @hallidev 
Here i tried to reproduce your issue using same url and it runs fine on iOS

### Code Sample
```
import 'package:flutter/material.dart';
import 'package:url_launcher/url_launcher.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      debugShowCheckedModeBanner: false,
      title: 'Material App',
      theme: ThemeData.dark(),
      home: Home(),
    );
  }
}

class Home extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Center(
        child: RaisedButton(
          onPressed: _launchURL,
          child: Text('Show Flutter homepage'),
        ),
      ),
    );
  }
}

_launchURL() async {
  const url =
      'https://my.identityprovider.com/connect/endsession?id_token_hint=eyJhbGciOiJSUzI1NiIsImtpZCI6ImN1UWdac3ZWeXdEWE5XNU92czBMeEEiLCJ0eXAiOiJKV1QifQ.eyJuYmYiOjE1ODY2OTM3MzAsImV4cCI6MTU4NjY5NDAzMCwiaXNzIjoiaHR0cHM6Ly9jYXZpZGVudGl0eS1kZXYuYXp1cmV3ZWJzaXRlcy5uZXQiLCJhdWQiOiJjZl9pb3MiLCJub25jZSI6IlVzMmhrUi14d0pQNzVkUWt6Q1hOR0l2bUcxLVp1eDd6end4LXhDam1aSnciLCJpYXQiOjE1ODY2OTM3MzAsImF0X2hhc2giOiJKZ0hFdEZ5WjVueDJVQUV4aHcxdWd3Iiwic19oYXNoIjoiLXlzYUFHcWFaTHh3SGctLXRwLVBnUSIsInNpZCI6IndhbjJGM0dOUjA4RUJaWWpfRlg1aHciLCJzdWIiOiIxMDAwMSIsImF1dGhfdGltZSI6MTU4NjAwOTczNywiaWRwIjoibG9jYWwiLCJhbXIiOlsicHdkIl19.ZcEk6J-WD5wg4GmhYRDCuDbyKQqeBaNqf1vmSAwg9Qifyimcn19fkhAgdjHVmU4bSMaJTx-Qlr_Im7lAF7HBVPstj0fGRgy9CxADHpdSI82GIwjamQrkJ4MwXC_m75Q6-cx4oo9rGK4cTu5B7yTXbGJxK5R7ra8Kds2ONm4BBDfIGNR9cvBX0HSvQOGjIFkYNx-6ReLidaLdM7nklKbYjor5yXV5GfkYmgfdKwnCQ4i_VmQleQ63G3ov1l3p8xkyUfk3WFEJOsMAZO1G7eKBl2bEGjELQXz6h0baoYIP7xV50A2HjN69FHkLj_q1NE2gUhT9cZBEBURAmCwdiCHhqA&post_logout_redirect_uri=com.mycompany.myapp://oidc-callback';
  if (await canLaunch(url)) {
    await launch(url);
  } else {
    throw 'Could not launch $url';
  }
}

```

<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel dev, v1.18.0, on Mac OS X 10.15.4 19E287, locale en-GB)
    • Flutter version 1.18.0 at /Users/taha/Code/flutter_dev
    • Framework revision 8f7327f83a (6 days ago), 2020-04-06 22:11:01 -0400
    • Engine revision 49891e0653
    • Dart version 2.8.0 (build 2.8.0-dev.20.0 1210d27678)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/taha/Code/sdk
    • Platform android-29, build-tools 29.0.3
    • ANDROID_HOME = /Users/taha/Code/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.
[✓] Xcode - develop for iOS and macOS (Xcode 11.4)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.4, Build version 11E146
    • CocoaPods version 1.9.1
[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome
[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build
      1.8.0_212-release-1586-b4-5784211)
[✓] VS Code (version 1.44.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.9.1
[✓] Connected device (4 available)
    • SM M305F   • 32003c30dc19668f • android-arm64  • Android 10 (API 29)
    • macOS      • macOS            • darwin-x64     • Mac OS X 10.15.4 19E287
    • Chrome     • chrome           • web-javascript • Google Chrome
      81.0.4044.92
    • Web Server • web-server       • web-javascript • Flutter Tools
• No issues found!
```

</details>

**Comment by hallidev** [comment]
Hello. Thanks for taking a look.

This appears to be related to open id connect on iOS. Still haven't been able to get it working, but I'll go ahead and close the issue as it's not url_launcher related.
