### ISSUE TITLE
[cocoon] grpc errors in backend

### ISSUE THREAD

**Issue by godofredoc** [flutter/flutter#54615]
Even after adding retries we are getting 5+ GrpcErrors per hour. This may be because we are retries to fixed 50ms and 3 max retries.

gRPC Error (14, The service is temporarily unavailable.)
#0      GrpcDatastoreImpl.query (package:appengine/src/grpc_api_impl/datastore_impl.dart:258:41)
<asynchronous suspension>
#1      Query.run.<anonymous closure> (package:gcloud/src/db/db.dart:246:12)
#2      StreamFromPages._onListen (package:gcloud/common.dart:72:5)
#3      _runGuarded (dart:async/stream_controller.dart:807:24)
#4      _StreamController._subscribe.<anonymous closure> (dart:async/stream_controller.dart:686:7)
#5      _BufferingStreamSubscription._guardCallback (dart:async/stream_impl.dart:416:13)
#6      _StreamController._subscribe (dart:async/stream_controller.dart:685:18)
#7      _ControllerStream._createSubscription (dart:async/stream_controller.dart:820:19)
#8      _StreamImpl.listen (dart:async/stream_impl.dart:474:9)
#9      new _ForwardingStreamSubscription (dart:async/stream_pipe.dart:125:10)
#10     _ForwardingStream._createSubscription (dart:async/stream_pipe.dart:93:16)
#11     _ForwardingStream.listen (dart:async/stream_pipe.dart:88:12)
#12     _StreamIterator._initializeOrDone (dart:async/stream_impl.dart:1006:30)
#13     _StreamIterator.moveNext (dart:async/stream_impl.dart:993:12)
#14     DatastoreService.queryTasksGroupedByStage (package:cocoon_service/src/service/datastore.dart)
<asynchronous suspension>
#15     TaskService.findNextTask (package:cocoon_service/src/service/task_provider.dart:32:27)
<asynchronous suspension>
#16     ReserveTask.post (package:cocoon_service/src/request_handlers/reserve_task.dart:78:47)
#17     RequestHandler.service.<anonymous closure> (package:cocoon_service/src/request_handling/request_handler.dart:49:28)
#18     _rootRun (dart:async/zone.dart:1126:13)
#19     _CustomZone.run (dart:async/zone.dart:1023:19)
#20     _runZoned (dart:async/zone.dart:1518:10)
#21     runZoned (dart:async/zone.dart:1465:12)
#22     RequestHandler.service (package:cocoon_service/src/request_handling/request_handler.dart:39:12)
#23     ApiRequestHandler.service.<anonymous closure> (package:cocoon_service/src/request_handling/api_request_handler.dart:139:19)
#24     _rootRun (dart:async/zone.dart:1126:13)
#25     _CustomZone.run (dart:async/zone.dart:1023:19)
#26     _runZoned (dart:async/zone.dart:1518:10)
#27     runZoned (dart:async/zone.dart:1465:12)
#28     ApiRequestHandler.service (package:cocoon_service/src/request_handling/api_request_handler.dart:138:11)
<asynchronous suspension>
#29     main.<anonymous closure>.<anonymous closure> (file:///app/bin/server.dart:83:23)
#30     runAppEngine.<anonymous closure> (package:appengine/appengine.dart:80:12)
#31     runAppEngine.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:appengine/src/appengine_internal.dart:59:18)
#32     _ServiceScope._fork.<anonymous closure> (package:gcloud/service_scope.dart:209:19)
#33     _rootRun (dart:async/zone.dart:1126:13)
#34     _CustomZone.run (dart:async/zone.dart:1023:19)
#35     _runZoned (dart:async/zone.dart:1518:10)
#36     runZoned (dart:async/zone.dart:1502:12)
#37     _ServiceScope._fork (package:gcloud/service_scope.dart:208:12)
#38     fork (package:gcloud/service_scope.dart:104:30)
#39     runAppEngine.<anonymous closure>.<anonymous closure> (package:appengine/src/appengine_internal.dart:57:9)
#40     AppEngineHttpServer.run.<anonymous closure>.<anonymous closure> (package:appengine/src/server/server.dart:83:16)
#41     _rootRunUnary (dart:async/zone.dart:1134:38)
#42     _CustomZone.runUnary (dart:async/zone.dart:1031:19)
#43     _CustomZone.runUnaryGuarded (dart:async/zone.dart:933:7)
#44     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:338:11)
#45     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:265:7)
#46     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:766:19)
#47     _StreamController._add (dart:async/stream_controller.dart:642:7)
#48     _StreamController.add (dart:async/stream_controller.dart:588:5)
#49     _HttpServer._handleRequest (dart:_http/http_impl.dart:2828:19)
#50     new _HttpConnection.<anonymous closure> (dart:_http/http_impl.dart:2586:19)
#51     _rootRunUnary (dart:async/zone.dart:1134:38)
#52     _CustomZone.runUnary (dart:async/zone.dart:1031:19)
#53     _CustomZone.runUnaryGuarded (dart:async/zone.dart:933:7)
#54     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:338:11)
#55     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:265:7)
#56     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:766:19)
#57     _StreamController._add (dart:async/stream_controller.dart:642:7)
#58     _StreamController.add (dart:async/stream_controller.dart:588:5)
#59     _HttpParser._headersEnd (dart:_http/http_parser.dart:388:17)
#60     _HttpParser._doParse (dart:_http/http_parser.dart:703:15)
#61     _HttpParser._parse (dart:_http/http_parser.dart:320:7)
#62     _HttpParser._onData (dart:_http/http_parser.dart:812:5)
#63     _rootRunUnary (dart:async/zone.dart:1134:38)
#64     _CustomZone.runUnary (dart:async/zone.dart:1031:19)
#65     _CustomZone.runUnaryGuarded (dart:async/zone.dart:933:7)
#66     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:338:11)
#67     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:265:7)
#68     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:766:19)
#69     _StreamController._add (dart:async/stream_controller.dart:642:7)
#70     _StreamController.add (dart:async/stream_controller.dart:588:5)
#71     _Socket._onData (dart:io-patch/socket_patch.dart:1851:41)
#72     _rootRunUnary (dart:async/zone.dart:1138:13)
#73     _CustomZone.runUnary (dart:async/zone.dart:1031:19)
#74     _CustomZone.runUnaryGuarded (dart:async/zone.dart:933:7)
#75     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:338:11)
#76     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:265:7)
#77     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:766:19)
#78     _StreamController._add (dart:async/stream_controller.dart:642:7)
#79     _StreamController.add (dart:async/stream_controller.dart:588:5)
#80     new _RawSocket.<anonymous closure> (dart:io-patch/socket_patch.dart:1399:33)
#81     _NativeSocket.issueReadEvent.issue (dart:io-patch/socket_patch.dart:919:14)
#82     _microtaskLoop (dart:async/schedule_microtask.dart:43:21)
#83     _startMicrotaskLoop (dart:async/schedule_microtask.dart:52:5)
#84     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
#85     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:175:5)

**Comment by godofredoc** [comment]
The grpc errors are caused by flakiness in the datastore service.  The image below has the analysis to justify the retries:

![image](https://user-images.githubusercontent.com/54371434/79170980-c1a34500-7da5-11ea-913d-51199449e7eb.png)

Summary:

* 350+ 500 status errors per day
* 10+ errors per day after adding 3 retries and fixed 50ms.
* The expectation is to get the errors close to 0 with 3 retries and quadratic backoff starting at 200ms.

**Comment by godofredoc** [comment]
We are not getting false positives anymore. We'll open more bugs for the remaining real issues.
