### ISSUE TITLE
After the execution of Flutter Clean Command, my application got crashed and not building.

### ISSUE THREAD

**Issue by shaadakhan** [flutter/flutter#54689]
## Steps to Reproduce

1. Run `flutter create bug`.
2. Update the files as follows: ... 
3. ... 

**Expected results:** 
Application should be build in debug mood or as a apk file.
**Actual results:** 
The application got crashed after i run "flutter clean".
<details>
  <summary>Logs</summary>

```
Compiler message:

/H:/InstallationPath/flutter/.pub-cache/hosted/pub.dartlang.org/firebase-7.3.0/lib/src/top_level.dart:1:8: Error:
Not found: 'dart:html'

import 'dart:html';

       ^

/H:/InstallationPath/flutter/.pub-cache/hosted/pub.dartlang.org/js-0.6.1+1/lib/js.dart:8:1: Error: Not found: 'dart:js'

export 'dart:js' show allowInterop, allowInteropCaptureThis;

^

/H:/InstallationPath/flutter/.pub-cache/hosted/pub.dartlang.org/js-0.6.1+1/lib/js_util.dart:8:1: Error: Not found: 'dart:js_util'

export 'dart:js_util';

^

/H:/InstallationPath/flutter/.pub-cache/hosted/pub.dartlang.org/firebase-7.3.0/lib/src/auth.dart:306:25: Error: The method 'allowInterop' isn't defined for the class 'Auth'.

 - 'Auth' is from 'package:firebase/src/auth.dart' ('/H:/InstallationPath/flutter/.pub-cache/hosted/pub.dartlang.org/firebase-7.3.0/lib/src/auth.dart').

Try correcting the name to the name of an existing method, or defining a method named 'allowInterop'.

      var nextWrapper = allowInterop((firebase_interop.UserJsImpl user) {

                        ^^^^^^^^^^^^

/H:/InstallationPath/flutter/.pub-cache/hosted/pub.dartlang.org/firebase-7.3.0/lib/src/auth.dart:310:26: Error: The method 'allowInterop' isn't defined for the class 'Auth'.

 - 'Auth' is from 'package:firebase/src/auth.dart' ('/H:/InstallationPath/flutter/.pub-cache/hosted/pub.dartlang.org/firebase-7.3.0/lib/src/auth.dart').

Try correcting the name to the name of an existing method, or defining a method named 'allowInterop'.

      var errorWrapper = allowInterop((e) => _changeController.addError(e));

                         ^^^^^^^^^^^^

/H:/InstallationPath/flutter/.pub-cache/hosted/pub.dartlang.org/firebase-7.3.0/lib/src/auth.dart:340:25: Error: The method 'allowInterop' isn't defined for the class 'Auth'.

 - 'Auth' is from 'package:firebase/src/auth.dart' ('/H:/InstallationPath/flutter/.pub-cache/hosted/pub.dartlang.org/firebase-7.3.0/lib/src/auth.dart').

Try correcting the name to the name of an existing method, or defining a method named 'allowInterop'.

      var nextWrapper = allowInterop((firebase_interop.UserJsImpl user) {

                        ^^^^^^^^^^^^

/H:/InstallationPath/flutter/.pub-cache/hosted/pub.dartlang.org/firebase-7.3.0/lib/src/auth.dart:345:11: Error: The method 'allowInterop' isn't defined for the class 'Auth'.

 - 'Auth' is from 'package:firebase/src/auth.dart' ('/H:/InstallationPath/flutter/.pub-cache/hosted/pub.dartlang.org/firebase-7.3.0/lib/src/auth.dart').

Try correcting the name to the name of an existing method, or defining a method named 'allowInterop'.

          allowInterop((e) => _idTokenChangedController.addError(e));

          ^^^^^^^^^^^^

/H:/InstallationPath/flutter/.pub-cache/hosted/pub.dartlang.org/firebase-7.3.0/lib/src/database.dart:164:9: Error: The method 'allowInterop' isn't defined for the class 'DatabaseReference<T>'.

 - 'DatabaseReference' is from 'package:firebase/src/database.dart' ('/H:/InstallationPath/flutter/.pub-cache/hosted/pub.dartlang.org/firebase-7.3.0/lib/src/database.dart').

Try correcting the name to the name of an existing method, or defining a method named 'allowInterop'.

        allowInterop((update) => jsify(transactionUpdate(dartify(update))));

        ^^^^^^^^^^^^

/H:/InstallationPath/flutter/.pub-cache/hosted/pub.dartlang.org/firebase-7.3.0/lib/src/database.dart:166:26: Error: The method 'allowInterop' isn't defined for the class 'DatabaseReference<T>'.

 - 'DatabaseReference' is from 'package:firebase/src/database.dart' ('/H:/InstallationPath/flutter/.pub-cache/hosted/pub.dartlang.org/firebase-7.3.0/lib/src/database.dart').

Try correcting the name to the name of an existing method, or defining a method named 'allowInterop'.

    var onCompleteWrap = allowInterop(

                         ^^^^^^^^^^^^

/H:/InstallationPath/flutter/.pub-cache/hosted/pub.dartlang.org/firebase-7.3.0/lib/src/database.dart:301:24: Error: The method 'allowInterop' isn't defined for the class 'Query<T>'.

 - 'Query' is from 'package:firebase/src/database.dart' ('/H:/InstallationPath/flutter/.pub-cache/hosted/pub.dartlang.org/firebase-7.3.0/lib/src/database.dart').

Try correcting the name to the name of an existing method, or defining a method named 'allowInterop'.

    var callbackWrap = allowInterop((database_interop.DataSnapshotJsImpl data,

                       ^^^^^^^^^^^^

/H:/InstallationPath/flutter/.pub-cache/hosted/pub.dartlang.org/firebase-7.3.0/lib/src/database.dart:325:30: Error: The method 'allowInterop' isn't defined for the class 'Query<T>'.

 - 'Query' is from 'package:firebase/src/database.dart' ('/H:/InstallationPath/flutter/.pub-cache/hosted/pub.dartlang.org/firebase-7.3.0/lib/src/database.dart').

Try correcting the name to the name of an existing method, or defining a method named 'allowInterop'.

    jsObject.once(eventType, allowInterop(

                             ^^^^^^^^^^^^

/H:/InstallationPath/flutter/.pub-cache/hosted/pub.dartlang.org/firebase-7.3.0/lib/src/database.dart:402:22: Error: The method 'allowInterop' isn't defined for the class 'DataSnapshot'.

 - 'DataSnapshot' is from 'package:firebase/src/database.dart' ('/H:/InstallationPath/flutter/.pub-cache/hosted/pub.dartlang.org/firebase-7.3.0/lib/src/database.dart').

Try correcting the name to the name of an existing method, or defining a method named 'allowInterop'.

    var actionWrap = allowInterop((d) => action(DataSnapshot.getInstance(d)));

                     ^^^^^^^^^^^^

/H:/InstallationPath/flutter/.pub-cache/hosted/pub.dartlang.org/firebase-7.3.0/lib/src/messaging.dart:72:27: Error: The method 'allowInterop' isn't defined for the class 'Messaging'.

 - 'Messaging' is from 'package:firebase/src/messaging.dart' ('/H:/InstallationPath/flutter/.pub-cache/hosted/pub.dartlang.org/firebase-7.3.0/lib/src/messaging.dart').

Try correcting the name to the name of an existing method, or defining a method named 'allowInterop'.

      final nextWrapper = allowInterop((payload) {

                          ^^^^^^^^^^^^

/H:/InstallationPath/flutter/.pub-cache/hosted/pub.dartlang.org/firebase-7.3.0/lib/src/messaging.dart:75:28: Error: The method 'allowInterop' isn't defined for the class 'Messaging'.

 - 'Messaging' is from 'package:firebase/src/messaging.dart' ('/H:/InstallationPath/flutter/.pub-cache/hosted/pub.dartlang.org/firebase-7.3.0/lib/src/messaging.dart').

Try correcting the name to the name of an existing method, or defining a method named 'allowInterop'.

      final errorWrapper = allowInterop((e) {

                           ^^^^^^^^^^^^

/H:/InstallationPath/flutter/.pub-cache/hosted/pub.dartlang.org/firebase-7.3.0/lib/src/messaging.dart:87:27: Error: The method 'allowInterop' isn't defined for the class 'Messaging'.

 - 'Messaging' is from 'package:firebase/src/messaging.dart' ('/H:/InstallationPath/flutter/.pub-cache/hosted/pub.dartlang.org/firebase-7.3.0/lib/src/messaging.dart').

Try correcting the name to the name of an existing method, or defining a method named 'allowInterop'.

      final nextWrapper = allowInterop((payload) {

                          ^^^^^^^^^^^^

/H:/InstallationPath/flutter/.pub-cache/hosted/pub.dartlang.org/firebase-7.3.0/lib/src/messaging.dart:97:27: Error: The method 'allowInterop' isn't defined for the class 'Messaging'.

 - 'Messaging' is from 'package:firebase/src/messaging.dart' ('/H:/InstallationPath/flutter/.pub-cache/hosted/pub.dartlang.org/firebase-7.3.0/lib/src/messaging.dart').

Try correcting the name to the name of an existing method, or defining a method named 'allowInterop'.

      final nextWrapper = allowInterop((_) => null);

                          ^^^^^^^^^^^^

/H:/InstallationPath/flutter/.pub-cache/hosted/pub.dartlang.org/firebase-7.3.0/lib/src/messaging.dart:98:28: Error: The method 'allowInterop' isn't defined for the class 'Messaging'.

 - 'Messaging' is from 'package:firebase/src/messaging.dart' ('/H:/InstallationPath/flutter/.pub-cache/hosted/pub.dartlang.org/firebase-7.3.0/lib/src/messaging.dart').

Try correcting the name to the name of an existing method, or defining a method named 'allowInterop'.

      final errorWrapper = allowInterop((e) {

                           ^^^^^^^^^^^^

/H:/InstallationPath/flutter/.pub-cache/hosted/pub.dartlang.org/firebase-7.3.0/lib/src/storage.dart:317:11: Error: The method 'allowInterop' isn't defined for the class 'UploadTask'.

 - 'UploadTask' is from 'package:firebase/src/storage.dart' ('/H:/InstallationPath/flutter/.pub-cache/hosted/pub.dartlang.org/firebase-7.3.0/lib/src/storage.dart').

Try correcting the name to the name of an existing method, or defining a method named 'allowInterop'.

          allowInterop((storage_interop.UploadTaskSnapshotJsImpl data) {

          ^^^^^^^^^^^^

/H:/InstallationPath/flutter/.pub-cache/hosted/pub.dartlang.org/firebase-7.3.0/lib/src/storage.dart:321:26: Error: The method 'allowInterop' isn't defined for the class 'UploadTask'.

 - 'UploadTask' is from 'package:firebase/src/storage.dart' ('/H:/InstallationPath/flutter/.pub-cache/hosted/pub.dartlang.org/firebase-7.3.0/lib/src/storage.dart').

Try correcting the name to the name of an existing method, or defining a method named 'allowInterop'.

      var errorWrapper = allowInterop((e) => _changeController.addError(e));

                         ^^^^^^^^^^^^

/H:/InstallationPath/flutter/.pub-cache/hosted/pub.dartlang.org/firebase-7.3.0/lib/src/storage.dart:322:26: Error: The method 'allowInterop' isn't defined for the class 'UploadTask'.

 - 'UploadTask' is from 'package:firebase/src/storage.dart' ('/H:/InstallationPath/flutter/.pub-cache/hosted/pub.dartlang.org/firebase-7.3.0/lib/src/storage.dart').

Try correcting the name to the name of an existing method, or defining a method named 'allowInterop'.

      var onCompletion = allowInterop(() => _changeController.close());

                         ^^^^^^^^^^^^

/H:/InstallationPath/flutter/.pub-cache/hosted/pub.dartlang.org/firebase-7.3.0/lib/src/top_level.dart:194:7: Error: Method not found: 'hasProperty'.

  if (js.hasProperty(error, 'message')) {

      ^^^^^^^^^^^

/H:/InstallationPath/flutter/.pub-cache/hosted/pub.dartlang.org/firebase-7.3.0/lib/src/top_level.dart:195:19: Error: Method not found: 'getProperty'.

    var message = js.getProperty(error, 'message');

                  ^^^^^^^^^^^

/H:/InstallationPath/flutter/.pub-cache/hosted/pub.dartlang.org/firebase-7.3.0/lib/src/utils.dart:29:7: Error: Method not found: 'hasProperty'.

  if (util.hasProperty(jsObject, 'firestore') &&

      ^^^^^^^^^^^

/H:/InstallationPath/flutter/.pub-cache/hosted/pub.dartlang.org/firebase-7.3.0/lib/src/utils.dart:30:7: Error: Method not found: 'hasProperty'.

      util.hasProperty(jsObject, 'id') &&

      ^^^^^^^^^^^

/H:/InstallationPath/flutter/.pub-cache/hosted/pub.dartlang.org/firebase-7.3.0/lib/src/utils.dart:31:7: Error: Method not found: 'hasProperty'.

      util.hasProperty(jsObject, 'parent')) {

      ^^^^^^^^^^^

/H:/InstallationPath/flutter/.pub-cache/hosted/pub.dartlang.org/firebase-7.3.0/lib/src/utils.dart:37:7: Error: Method not found: 'hasProperty'.

  if (util.hasProperty(jsObject, 'latitude') &&

      ^^^^^^^^^^^

/H:/InstallationPath/flutter/.pub-cache/hosted/pub.dartlang.org/firebase-7.3.0/lib/src/utils.dart:38:7: Error: Method not found: 'hasProperty'.

      util.hasProperty(jsObject, 'longitude') &&

      ^^^^^^^^^^^

/H:/InstallationPath/flutter/.pub-cache/hosted/pub.dartlang.org/firebase-7.3.0/lib/src/utils.dart:44:15: Error: Method not found: 'getProperty'.

  var proto = util.getProperty(jsObject, '__proto__');

              ^^^^^^^^^^^

/H:/InstallationPath/flutter/.pub-cache/hosted/pub.dartlang.org/firebase-7.3.0/lib/src/utils.dart:46:7: Error: Method not found: 'hasProperty'.

  if (util.hasProperty(proto, 'toDate') &&

      ^^^^^^^^^^^

/H:/InstallationPath/flutter/.pub-cache/hosted/pub.dartlang.org/firebase-7.3.0/lib/src/utils.dart:47:7: Error: Method not found: 'hasProperty'.

      util.hasProperty(proto, 'toMillis')) {

      ^^^^^^^^^^^

/H:/InstallationPath/flutter/.pub-cache/hosted/pub.dartlang.org/firebase-7.3.0/lib/src/utils.dart:52:7: Error: Method not found: 'hasProperty'.

  if (util.hasProperty(proto, 'isEqual') &&

      ^^^^^^^^^^^

/H:/InstallationPath/flutter/.pub-cache/hosted/pub.dartlang.org/firebase-7.3.0/lib/src/utils.dart:53:7: Error: Method not found: 'hasProperty'.

      util.hasProperty(proto, 'toBase64')) {

      ^^^^^^^^^^^

/H:/InstallationPath/flutter/.pub-cache/hosted/pub.dartlang.org/firebase-7.3.0/lib/src/utils.dart:67:24: Error: Method not found: 'getProperty'.

    map[key] = dartify(util.getProperty(jsObject, key));

                       ^^^^^^^^^^^

/H:/InstallationPath/flutter/.pub-cache/hosted/pub.dartlang.org/firebase-7.3.0/lib/src/utils.dart:91:17: Error: Method not found: 'newObject'.

    var jsMap = util.newObject();

                ^^^^^^^^^

/H:/InstallationPath/flutter/.pub-cache/hosted/pub.dartlang.org/firebase-7.3.0/lib/src/utils.dart:93:7: Error: Method not found: 'setProperty'.

      util.setProperty(jsMap, key, jsify(value));

      ^^^^^^^^^^^

/H:/InstallationPath/flutter/.pub-cache/hosted/pub.dartlang.org/firebase-7.3.0/lib/src/utils.dart:116:12: Error: Method not found: 'allowInterop'.

    return allowInterop(dartObject);

           ^^^^^^^^^^^^

/H:/InstallationPath/flutter/.pub-cache/hosted/pub.dartlang.org/firebase-7.3.0/lib/src/utils.dart:124:5: Error: Method not found: 'callMethod'.

    util.callMethod(jsObject, method, args);

    ^^^^^^^^^^

/H:/InstallationPath/flutter/.pub-cache/hosted/pub.dartlang.org/firebase-7.3.0/lib/src/utils.dart:139:19: Error: Method not found: 'promiseToFuture'.

    value = await util.promiseToFuture(thenable);

                  ^^^^^^^^^^^^^^^

/H:/InstallationPath/flutter/.pub-cache/hosted/pub.dartlang.org/firebase-7.3.0/lib/src/utils.dart:141:9: Error: Method not found: 'hasProperty'.

    if (util.hasProperty(e, 'code')) {

        ^^^^^^^^^^^

/H:/InstallationPath/flutter/.pub-cache/hosted/pub.dartlang.org/firebase-7.3.0/lib/src/utils.dart:152:27: Error: Method not found: 'allowInterop'.

  return PromiseJsImpl<S>(allowInterop((

                          ^^^^^^^^^^^^

/H:/InstallationPath/flutter/.pub-cache/hosted/pub.dartlang.org/firebase-7.3.0/lib/src/utils.dart:165:5: Error: Method not found: 'allowInterop'.

    allowInterop(c.completeError);

    ^^^^^^^^^^^^

/H:/InstallationPath/flutter/.pub-cache/hosted/pub.dartlang.org/firebase-7.3.0/lib/src/utils.dart:173:22: Error: Method not found: 'getProperty'.

  String get code => util.getProperty(_source, 'code');

                     ^^^^^^^^^^^

/H:/InstallationPath/flutter/.pub-cache/hosted/pub.dartlang.org/firebase-7.3.0/lib/src/utils.dart:176:25: Error: Method not found: 'getProperty'.

  String get message => util.getProperty(_source, 'message');

                        ^^^^^^^^^^^

/H:/InstallationPath/flutter/.pub-cache/hosted/pub.dartlang.org/firebase-7.3.0/lib/src/utils.dart:179:22: Error: Method not found: 'getProperty'.

  String get name => util.getProperty(_source, 'name');

                     ^^^^^^^^^^^

/H:/InstallationPath/flutter/.pub-cache/hosted/pub.dartlang.org/firebase-7.3.0/lib/src/utils.dart:182:32: Error: Method not found: 'getProperty'.

  Object get serverResponse => util.getProperty(_source, 'serverResponse');

                               ^^^^^^^^^^^

/H:/InstallationPath/flutter/.pub-cache/hosted/pub.dartlang.org/firebase-7.3.0/lib/src/utils.dart:185:23: Error: Method not found: 'getProperty'.

  String get stack => util.getProperty(_source, 'stack');

                      ^^^^^^^^^^^

/H:/InstallationPath/flutter/.pub-cache/hosted/pub.dartlang.org/firebase-7.3.0/lib/src/firestore.dart:105:30: Error: The method 'allowInterop' isn't defined for the class 'Firestore'.

 - 'Firestore' is from 'package:firebase/src/firestore.dart' ('/H:/InstallationPath/flutter/.pub-cache/hosted/pub.dartlang.org/firebase-7.3.0/lib/src/firestore.dart').

Try correcting the name to the name of an existing method, or defining a method named 'allowInterop'.

    var updateFunctionWrap = allowInterop((transaction) =>

                             ^^^^^^^^^^^^

/H:/InstallationPath/flutter/.pub-cache/hosted/pub.dartlang.org/firebase-7.3.0/lib/src/firestore.dart:306:11: Error: The method 'allowInterop' isn't defined for the class 'DocumentReference'.

 - 'DocumentReference' is from 'package:firebase/src/firestore.dart' ('/H:/InstallationPath/flutter/.pub-cache/hosted/pub.dartlang.org/firebase-7.3.0/lib/src/firestore.dart').

Try correcting the name to the name of an existing method, or defining a method named 'allowInterop'.

          allowInterop((firestore_interop.DocumentSnapshotJsImpl snapshot) {

          ^^^^^^^^^^^^

/H:/InstallationPath/flutter/.pub-cache/hosted/pub.dartlang.org/firebase-7.3.0/lib/src/firestore.dart:310:26: Error: The method 'allowInterop' isn't defined for the class 'DocumentReference'.

 - 'DocumentReference' is from 'package:firebase/src/firestore.dart' ('/H:/InstallationPath/flutter/.pub-cache/hosted/pub.dartlang.org/firebase-7.3.0/lib/src/firestore.dart').

Try correcting the name to the name of an existing method, or defining a method named 'allowInterop'.

      var errorWrapper = allowInterop((e) => controller.addError(e));

                         ^^^^^^^^^^^^

/H:/InstallationPath/flutter/.pub-cache/hosted/pub.dartlang.org/firebase-7.3.0/lib/src/firestore.dart:445:9: Error: The method 'allowInterop' isn't defined for the class 'Query<T>'.

 - 'Query' is from 'package:firebase/src/firestore.dart' ('/H:/InstallationPath/flutter/.pub-cache/hosted/pub.dartlang.org/firebase-7.3.0/lib/src/firestore.dart').

Try correcting the name to the name of an existing method, or defining a method named 'allowInterop'.

        allowInterop((firestore_interop.QuerySnapshotJsImpl snapshot) {

        ^^^^^^^^^^^^

/H:/InstallationPath/flutter/.pub-cache/hosted/pub.dartlang.org/firebase-7.3.0/lib/src/firestore.dart:449:24: Error: The method 'allowInterop' isn't defined for the class 'Query<T>'.

 - 'Query' is from 'package:firebase/src/firestore.dart' ('/H:/InstallationPath/flutter/.pub-cache/hosted/pub.dartlang.org/firebase-7.3.0/lib/src/firestore.dart').

Try correcting the name to the name of an existing method, or defining a method named 'allowInterop'.

    var errorWrapper = allowInterop((e) => controller.addError(e));

                       ^^^^^^^^^^^^

/H:/InstallationPath/flutter/.pub-cache/hosted/pub.dartlang.org/firebase-7.3.0/lib/src/firestore.dart:775:9: Error: The method 'allowInterop' isn't defined for the class 'QuerySnapshot'.

 - 'QuerySnapshot' is from 'package:firebase/src/firestore.dart' ('/H:/InstallationPath/flutter/.pub-cache/hosted/pub.dartlang.org/firebase-7.3.0/lib/src/firestore.dart').

Try correcting the name to the name of an existing method, or defining a method named 'allowInterop'.

        allowInterop((s) => callback(DocumentSnapshot.getInstance(s)));

        ^^^^^^^^^^^^

/H:/InstallationPath/flutter/.pub-cache/hosted/pub.dartlang.org/firebase-7.3.0/lib/src/interop/js_interop.dart:17:7: Error: Method not found: 'hasProperty'.

  if (util.hasProperty(jsObject, 'toDateString')) {

      ^^^^^^^^^^^

Unhandled exception:

FileSystemException(uri=org-dartlang-untranslatable-uri:dart

%3Ahtml; message=StandardFileSystem only supports file:* and data:* URIs)

#0      StandardFileSystem.entityForUri (package:front_end/src/api_prototype/standard_file_system.dart:33:7)

#1      asFileUri (package:vm/kernel_front_end.dart:604:37)

#2      writeDepfile (package:vm/kernel_front_end.dart:799:21)

<asynchronous suspension>

#3      FrontendCompiler.compile (package:frontend_server/frontend_server.dart:472:15)

<asynchronous suspension>

#4      _FlutterFrontendCompiler.compile (package:flutter_frontend_server/server.dart:38:22)

#5      starter (package:flutter_frontend_server/server.dart:149:27)

#6      main (file:///C:/b/s/w/ir/cache/builder/src/flutter/flutter_frontend_server/bin/starter.dart:8:30)

#7      _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:305:32)

#8      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:174:12)



Target kernel_snapshot failed: Exception: Errors during snapshot creation: null

build failed.



FAILURE: Build failed with an exception.



* Where:

Script 'H:\NewFlutterSDK\flutter_windows_v1.12.13+hotfix.5-stable\flutter\packages\flutter_tools\gradle\flutter.gradle' line: 780



* What went wrong:

Execution failed for task ':app:compileFlutterBuildDebug'.

> Process 'command 'H:\NewFlutterSDK\flutter_windows_v1.12.13+hotfix.5-stable\flutter\bin\flutter.bat'' finished with non-zero exit value 1



* Try:

Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.



* Get more help at https://help.gradle.org



BUILD FAILED in 19s
Running Gradle task 'assembleDebug'...                             21.2s
Gradle task assembleDebug failed with exit code 1
```

```
```

```Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, v1.12.13+hotfix.9, on Microsoft Windows [Version 10.0.10240], locale en-US)
[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[√] Android Studio (version 3.6)
[√] Connected device (1 available)

• No issues found!
```

</details>

**Comment by jonahwilliams** [comment]
You cannot import the `firebase` library into a regular flutter project. This has nothing to do with flutter clean, see: https://github.com/FirebaseExtended/firebase-dart/blob/master/README.md

**Comment by shaadakhan** [comment]
I already removed the firebase dependencies from project and still getting errors.
