### ISSUE TITLE
The getter 'cutButtonLabel' was called on null.

### ISSUE THREAD

**Issue by congfandi** [flutter/flutter#54708]
I get this error when double clicking on the textformfield. This is very disturbing and there is no specific error information. Please help.

```
════════ Exception caught by widgets library ═══════════════════════════════════════════════════════
The following NoSuchMethodError was thrown building _OverlayEntry-[LabeledGlobalKey<_OverlayEntryState>#e7612](dirty, dependencies: [_LocalizationsScope-[GlobalKey#ec574], MediaQuery], state: _OverlayEntryState#04737):
The getter 'cutButtonLabel' was called on null.
Receiver: null
Tried calling: cutButtonLabel

The relevant error-causing widget was: 
  MaterialApp file:///Volumes/Macintosh%20HD%20-%20Data/PT%20KAHAGO/kahago/lib/app/my_app.dart:45:20
When the exception was thrown, this was the stack: 
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:53:5)
#1      _CupertinoTextSelectionControls.buildToolbar (package:flutter/src/cupertino/text_selection.dart:366:44)
#2      TextSelectionOverlay._buildToolbar (package:flutter/src/widgets/text_selection.dart:556:34)
#3      _OverlayEntryState.build (package:flutter/src/widgets/overlay.dart:169:25)
#4      StatefulElement.build (package:flutter/src/widgets/framework.dart:4334:27)
...
════════════════════════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by widgets library ═══════════════════════════════════════════════════════
The getter 'cutButtonLabel' was called on null.
Receiver: null
Tried calling: cutButtonLabel
The relevant error-causing widget was: 
  MaterialApp file:///Volumes/Macintosh%20HD%20-%20Data/PT%20KAHAGO/kahago/lib/app/my_app.dart:45:20
════════════════════════════════════════════════════════════════════════════════════════════════════


```

<img width="729" alt="Screen Shot 2020-04-14 at 09 55 24" src="https://user-images.githubusercontent.com/10652810/79181570-d7147f80-7e36-11ea-90e7-ec414c4d405a.png">

![Simulator Screen Shot - iPhone 11 Pro Max - 2020-04-14 at 09 54 57](https://user-images.githubusercontent.com/10652810/79181791-6de13c00-7e37-11ea-8909-d50753a036af.png)

**Comment by congfandi** [comment]
<img width="470" alt="Screen Shot 2020-04-14 at 10 42 58" src="https://user-images.githubusercontent.com/10652810/79183950-1c3bb000-7e3d-11ea-853f-920472f33463.png">
i have resolved thid issue by adding 

```
GlobalCupertinoLocalizations.delegate,
  DefaultCupertinoLocalizations.delegate
```
