### ISSUE TITLE
RenderObjectElement error

### ISSUE THREAD

**Issue by Zumbalamambo** [flutter/flutter#54789]
I'm getting the following error when I try to run the code

```
> [I/flutter ( 8477): 
> I/flutter ( 8477): When the exception was thrown, this was the stack:
> I/flutter ( 8477): #0      RenderObjectElement._updateParentData.<anonymous closure> (package:flutter/src/widgets/framework.dart:5649:11)
> I/flutter ( 8477): #1      RenderObjectElement._updateParentData (package:flutter/src/widgets/framework.dart:5665:6)
> I/flutter ( 8477): #2      RenderObjectElement.attachRenderObject (package:flutter/src/widgets/framework.dart:5686:7)
> I/flutter ( 8477): #3      RenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5380:5)
> I/flutter ( 8477): #4      SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5833:11)
> I/flutter ( 8477): ...     Normal element mounting (15 frames)
> I/flutter ( 8477): #19     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3450:14)
> I/flutter ( 8477): #20     MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5951:32)
> I/flutter ( 8477): ...     Normal element mounting (79 frames)
> I/flutter ( 8477): #99     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3450:14)
> I/flutter ( 8477): #100    MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5951:32)
> I/flutter ( 8477): ...     Normal element mounting (4 frames)
> I/flutter ( 8477): #104    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3450:14)
> I/flutter ( 8477): #105    MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5951:32)
> I/flutter ( 8477): ...     Normal element mounting (19 frames)
> I/flutter ( 8477): #124    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3450:14)
> I/flutter ( 8477): #125    MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5951:32)
> I/flutter ( 8477): ...     Normal element mounting (208 frames)
> I/flutter ( 8477): #333    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3450:14)
> I/flutter ( 8477): #334    Element.updateChild (package:flutter/src/widgets/framework.dart:3218:18)
> I/flutter ( 8477): #335    RenderObjectElement.updateChildren (package:flutter/src/widgets/framework.dart:5584:32)
> I/flutter ( 8477): #336    MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:5961:17)
> I/flutter ( 8477): #337    Element.updateChild (package:flutter/src/widgets/framework.dart:3205:15)
> I/flutter ( 8477): #338    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4531:16)
> I/flutter ( 8477): #339    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4679:11)
> I/flutter ( 8477): #340    Element.rebuild (package:flutter/src/widgets/framework.dart:4222:5)
> I/flutter ( 8477): #341    BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2627:33)
> I/flutter ( 8477): #342    WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:864:20)
> I/flutter ( 8477): #343    RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:284:5)
> I/flutter ( 8477): #344    SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1074:15)
> I/flutter ( 8477): #345    SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1013:9)
> I/flutter ( 8477): #346    SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:929:5)
> I/flutter ( 8477): #350    _invoke (dart:ui/hooks.dart:261:10)
> I/flutter ( 8477): #351    _drawFrame (dart:ui/hooks.dart:219:3)
> I/flutter ( 8477): (elided 3 frames from dart:async)
> I/flutter ( 8477): ════════════════════════════════════════════════════════════════════════════════════════════════════](url)
```

**Comment by TahaTesser** [comment]
Hi @Zumbalamambo 
can you please provide your `flutter doctor -v` and `flutter run --verbose`? 
Also, to better address the issue, would be helpful if you could post a minimal code sample to reproduce the problem
Thank you
