### ISSUE TITLE
[tool_crash] FileSystemException: Failed to set file modification time, path = '/home/wender/Desenvolvimento/flutterprojetos/webradio/.packages' (OS Error: Operation not permitted, errno = 1)

### ISSUE THREAD

**Issue by paulowender** [flutter/flutter#54790]
## Command
```
flutter run --machine --target lib/main.dart -d 3208d7adc6a15167 --track-widget-creation --start-paused
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
FileSystemException: FileSystemException: Failed to set file modification time, path = '/home/wender/Desenvolvimento/flutterprojetos/webradio/.packages' (OS Error: Operation not permitted, errno = 1)
```
#0      _File.setLastModifiedSync (dart:io/file_impl.dart:473:7)
#1      ForwardingFile.setLastModifiedSync (package:file/src/forwarding/forwarding_file.dart:62:55)
#2      ForwardingFile.setLastModifiedSync (package:file/src/forwarding/forwarding_file.dart:62:55)
#3      _DefaultPub.get (package:flutter_tools/src/dart/pub.dart:209:19)
#4      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:694:17)
<asynchronous suspension>
#5      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:609:33)
<asynchronous suspension>
#6      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart)
#7      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:29)
#8      _rootRun (dart:async/zone.dart:1126:13)
#9      _CustomZone.run (dart:async/zone.dart:1023:19)
#10     _runZoned (dart:async/zone.dart:1518:10)
#11     runZoned (dart:async/zone.dart:1465:12)
#12     AppContext.run (package:flutter_tools/src/base/context.dart:149:18)
#13     FlutterCommand.run (package:flutter_tools/src/runner/flutter_command.dart:599:20)
#14     CommandRunner.runCommand (package:args/command_runner.dart:197:27)
#15     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:338:21)
<asynchronous suspension>
#16     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart)
```
```
[✓] Flutter (Channel beta, v1.15.17, on Linux, locale pt_BR.UTF-8)
    • Flutter version 1.15.17 at /home/wender/Desenvolvimento/flutter
    • Framework revision 2294d75bfa (6 weeks ago), 2020-03-07 00:28:38 +0900
    • Engine revision 5aff311948
    • Dart version 2.8.0 (build 2.8.0-dev.12.0 9983424a3c)

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /home/wender/Android/Sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.3
    • Java binary at: /etc/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b16-5323222)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Android Studio (version 3.4)
    • Android Studio at /etc/android-studio
    • Flutter plugin version 39.0.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b16-5323222)

[✓] VS Code (version 1.44.1)
    • VS Code at /usr/share/code
    • Flutter extension version 3.9.1

[✓] Connected device (3 available)
    • SM G900H Exynos • 3208d7adc6a15167 • android-arm    • Android 6.0.1 (API 23)
    • Chrome          • chrome           • web-javascript • Google Chrome 80.0.3987.163
    • Web Server      • web-server       • web-javascript • Flutter Tools

• No issues found!

```

## Flutter Application Metadata
**Version**: 1.0.0+1
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
### Plugins
flutter_radio_player-1.0.3

**Comment by TahaTesser** [comment]
Hi @paulowender 
For issue related to the 3rd party plugin [flutter_radio_player](https://pub.dev/packages/flutter_radio_player) you may want to open an issue in the dedicated [github](https://github.com/Sithira/FlutterRadioPlayer/issues).

Closing, as this isn't an issue with Flutter itself,
if you disagree please write in the comments and I will reopen it 
Thank you
