### ISSUE TITLE
[ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: MissingPluginException(No implementation found for method getAll on channel plugins.flutter.io/shared_preferences)

### ISSUE THREAD

**Issue by adwpc** [flutter/flutter#54845]
## Steps to Reproduce

flutter run

Launching lib/main.dart on GT N7100 in debug mode...
W/FlutterActivity(31868): Tried to automatically register plugins with FlutterEngine (io.flutter.embedding.engine.FlutterEngine@426467b0) but could not find and invoke the GeneratedPluginRegistrant.
E/flutter (31868): [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: MissingPluginException(No implementation found for method getAll on channel plugins.flutter.io/shared_preferences)
**Expected results:** 

**Actual results:** 

<details>
  <summary>Logs</summary>

```
```

```
```

```
```

</details>

**Comment by VladyslavBondarenko** [comment]
Hi @adwpc 
have you run `flutter pub get` before running your app?
does `flutter clean` helps?
provide please your `flutter doctor -v`

**Comment by adwpc** [comment]
@VladyslavBondarenko 
Yep, `flutter pub get` and `flutter clean` not work.

flutter doctor -v      23:34:59
[✓] Flutter (Channel dev, v1.18.0-dev.5.0, on Mac OS X 10.14.6 18G4032,
    locale zh-Hans-CN)
    • Flutter version 1.18.0-dev.5.0 at /Volumes/vm/workspace/flutter
    • Framework revision 7f56b53de4 (3 days ago), 2020-04-12 12:00:01 -0400
    • Engine revision beb8a7ec48
    • Dart version 2.8.0 (build 2.8.0-dev.20.0 89b0f67261)


[✓] Android toolchain - develop for Android devices (Android SDK version
    28.0.3)
    • Android SDK at /Users/adam/Library/Android/sdk
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.2.1)
    • Xcode at /Volumes/vm/Xcode.app/Contents/Developer
    • Xcode 11.2.1, Build version 11B500
    • CocoaPods version 1.8.4

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google
      Chrome

[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build
      1.8.0_212-release-1586-b4-5784211)

[!] Proxy Configuration
    • HTTP_PROXY is set
    ! NO_PROXY is not set

[✓] Connected device (4 available)
    • GT N7100   • 4df168ab32779f33 • android-arm    • Android 4.4.4 (API
      19)
    • macOS      • macOS            • darwin-x64     • Mac OS X 10.14.6
      18G4032
    • Chrome     • chrome           • web-javascript • Google Chrome
      83.0.4103.14 dev
    • Web Server • web-server       • web-javascript • Flutter Tools

! Doctor found issues in 1 category.

**Comment by tony123S** [comment]
Same here. I have opened a new issue

https://github.com/flutter/flutter/issues/55015

**Comment by szotp** [comment]
The message
```
Tried to automatically register plugins with FlutterEngine (io.flutter.embedding.engine.FlutterEngine@426467b0) but could not find and invoke the GeneratedPluginRegistrant.
```

Is completely wrong. It's displayed if **any** plugin crashes. Run your project in Android Studio and check logcat for exceptions. Upgrade/change plugins that crash. For me it was `flutter_inappbrowser: 2.0.2`.

**Comment by TahaTesser** [comment]
@Hinal1108 
Does you app has `flutter_inappbrowser` ?

**Comment by Hinal1108** [comment]
> flutter_inappbrowser

No

**Comment by Hinal1108** [comment]
> @Hinal1108
> Does you app has `flutter_inappbrowser` ?

any solution for this issue?

**Comment by TahaTesser** [comment]
Hi @Hinal1108 
Can you try downgrading to earlier version in the mean time?

**Comment by Hinal1108** [comment]
> Hi @Hinal1108
> Can you try downgrading to an earlier version in the meantime?

yes I already tried that things also but doesn't solve it

**Comment by Hinal1108** [comment]
> Hi @Hinal1108
> Can you try downgrading to an earlier version in the meantime?

can you please give me the proper solution for that because I need an urgent basis

**Comment by yiss** [comment]
I'm having the same issue, any solutions yet ?

**Comment by yiss** [comment]
Running Flutter getting this problem with running permission handler plugin [https://pub.dev/packages/permission_handler#-readme-tab-](url) :

```
E/flutter ( 7571): [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: MissingPluginException(No implementation found for method requestPermissions on channel flutter.baseflow.com/permissions/methods)
E/flutter ( 7571): #0      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:319:7)
E/flutter ( 7571): <asynchronous suspension>
E/flutter ( 7571): #1      MethodChannelPermissionHandler.requestPermissions (package:permission_handler_platform_interface/src/method_channel/method_channel_permission_handler.dart:66:30)
E/flutter ( 7571): #2      PermissionListActions.request (package:permission_handler/permission_handler.dart:104:16)
E/flutter ( 7571): #3      PermissionActions.request (package:permission_handler/permission_handler.dart:44:26)
E/flutter ( 7571): #4      setUp (package:tiktok_mate/main.dart:31:60)
E/flutter ( 7571): #5      main (package:tiktok_mate/main.dart:46:9)
E/flutter ( 7571): #6      _AsyncAwaitCompleter.start (dart:async-patch/async_patch.dart:45:6)
E/flutter ( 7571): #7      main (package:tiktok_mate/main.dart:44:18)
E/flutter ( 7571): #8      _runMainZoned.<anonymous closure>.<anonymous closure> (dart:ui/hooks.dart:239:25)
E/flutter ( 7571): #9      _rootRun (dart:async/zone.dart:1126:13)
E/flutter ( 7571): #10     _CustomZone.run (dart:async/zone.dart:1023:19)
E/flutter ( 7571): #11     _runZoned (dart:async/zone.dart:1518:10)
E/flutter ( 7571): #12     runZoned (dart:async/zone.dart:1502:12)
E/flutter ( 7571): #13     _runMainZoned.<anonymous closure> (dart:ui/hooks.dart:231:5)
E/flutter ( 7571): #14     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:307:19)
E/flutter ( 7571): #15     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:174:12)
```

Running Flutter doctor : 

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, v1.12.13+hotfix.9, on Mac OS X 10.15.4 19E287, locale en-FR)
 
[!] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses
[✗] Xcode - develop for iOS and macOS
    ✗ Xcode installation is incomplete; a full installation is necessary for iOS development.
      Download at: https://developer.apple.com/xcode/download/
      Or install Xcode via the App Store.
      Once installed, run:
        sudo xcode-select --switch /Applications/Xcode.app/Contents/Developer
        sudo xcodebuild -runFirstLaunch
    ✗ CocoaPods not installed.
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To install:
        sudo gem install cocoapods
[✓] Android Studio (version 3.6)
[✓] Android Studio
[!] IntelliJ IDEA Ultimate Edition (version 2020.1.1)
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
[✓] VS Code (version 1.44.2)
[✓] Connected device (1 available)

! Doctor found issues in 3 categories.

```

I don't understand why this problem is happening because it was working before I didn't change anything

**Comment by yiss** [comment]
The problem seems to be solved by doing : 
`flutter create .`

**Comment by bounty1342** [comment]
In /android/app/src/main/AndroidManifest.xml replace :
`<activity android:name="io.flutter.embedding.android.FlutterFragmentActivity"
`
by
`<activity android:name="io.flutter.embedding.android.FlutterActivity"
`

https://github.com/flutter/flutter/wiki/Upgrading-pre-1.12-Android-projects

Hope this help, it solved it for me.

**Comment by tony123S** [comment]
I managed to fix it using below methods:

Don't remove your `.MainActivity.kt`, instead remove your `.App` class.
**MainActivity.kt**
```

package your_package_name

import androidx.annotation.NonNull
import io.flutter.embedding.android.FlutterActivity 
import io.flutter.embedding.engine.FlutterEngine    
import io.flutter.plugins.GeneratedPluginRegistrant 

class MainActivity: FlutterActivity() { 
    override fun configureFlutterEngine(@NonNull flutterEngine: FlutterEngine) {    
        GeneratedPluginRegistrant.registerWith(flutterEngine);  
    }   
}
```
Modify mainfest.
**AndroidManifest.xml**

```

<manifest xmlns:android="http://schemas.android.com/apk/res/android" package="your_package_name">

    <uses-permission android:name="android.permission.INTERNET" />

    <!-- io.flutter.app.FlutterApplication is an android.app.Application that
         calls FlutterMain.startInitialization(this); in its onCreate method.
         In most cases you can leave this as-is, but you if you want to provide
         additional functionality it is fine to subclass or reimplement
         FlutterApplication and put your custom class here. -->
    <application android:label="xxx" android:usesCleartextTraffic="true" android:icon="@mipmap/ic_launcher">
        <activity android:name=".MainActivity" android:launchMode="singleTop" android:theme="@style/LaunchTheme" android:configChanges="orientation|keyboardHidden|keyboard|screenSize|locale|layoutDirection|fontScale|screenLayout|density|uiMode" android:hardwareAccelerated="true" android:windowSoftInputMode="adjustResize">
            <!-- This keeps the window background of the activity showing
                 until Flutter renders its first frame. It can be removed if
                 there is no splash screen (such as the default splash screen
                 defined in @style/LaunchTheme). -->
            <!-- <meta-data android:name="io.flutter.app.android.SplashScreenUntilFirstFrame" android:value="true" /> -->
            <intent-filter>
                <action android:name="android.intent.action.MAIN"/>
                <category android:name="android.intent.category.LAUNCHER"/>
            </intent-filter>

            <intent-filter>
                <action android:name="FLUTTER_NOTIFICATION_CLICK"/>
                <category android:name="android.intent.category.DEFAULT"/>
            </intent-filter>

            <meta-data android:name="io.flutter.embedding.android.SplashScreenDrawable" android:resource="@drawable/launch_background" />

            <!-- Theme to apply as soon as Flutter begins rendering frames -->
            <meta-data android:name="io.flutter.embedding.android.NormalTheme" android:resource="@style/NormalTheme" />

        </activity>

        <meta-data android:name="flutterEmbedding" android:value="2" />

    </application>
</manifest>
```
Add NormalTheme.
**styles.xml**

```

<?xml version="1.0" encoding="utf-8"?>
<resources>
    <style name="LaunchTheme" parent="@android:style/Theme.Black.NoTitleBar">
        <!-- Show a splash screen on the activity. Automatically removed when
             Flutter draws its first frame -->
        <item name="android:windowBackground">@drawable/launch_background</item>
    </style>

    <style name="NormalTheme" parent="@android:style/Theme.Black.NoTitleBar">
    <item name="android:windowBackground">@drawable/launch_background</item>
</style>
</resources>
```

**Comment by yiss** [comment]
If you don't have any specific platform code delete the android folder and ios folder, cd into the folder of the app and type `flutter create .`what this command does is basically fixes what's wrong with and @ejdrian313 I don't know why you downvoted my comment I was trying to help. here is the tweet from where I got that tip : https://twitter.com/FlutterDev/status/1248654113463623683?s=20

**Comment by juvs** [comment]
> I managed to fix it using below methods:
> 
> Don't remove your `.MainActivity.kt`, instead remove your `.App` class.
> **MainActivity.kt**
> 
> ```
> 
> package your_package_name
> 
> import androidx.annotation.NonNull
> import io.flutter.embedding.android.FlutterActivity 
> import io.flutter.embedding.engine.FlutterEngine    
> import io.flutter.plugins.GeneratedPluginRegistrant 
> 
> class MainActivity: FlutterActivity() { 
>     override fun configureFlutterEngine(@NonNull flutterEngine: FlutterEngine) {    
>         GeneratedPluginRegistrant.registerWith(flutterEngine);  
>     }   
> }
> ```
> 
> Modify mainfest.
> **AndroidManifest.xml**
> 
> ```
> 
> <manifest xmlns:android="http://schemas.android.com/apk/res/android" package="your_package_name">
> 
>     <uses-permission android:name="android.permission.INTERNET" />
> 
>     
>     <application android:label="xxx" android:usesCleartextTraffic="true" android:icon="@mipmap/ic_launcher">
>         <activity android:name=".MainActivity" android:launchMode="singleTop" android:theme="@style/LaunchTheme" android:configChanges="orientation|keyboardHidden|keyboard|screenSize|locale|layoutDirection|fontScale|screenLayout|density|uiMode" android:hardwareAccelerated="true" android:windowSoftInputMode="adjustResize">
>             
>             
>             <intent-filter>
>                 <action android:name="android.intent.action.MAIN"/>
>                 <category android:name="android.intent.category.LAUNCHER"/>
>             </intent-filter>
> 
>             <intent-filter>
>                 <action android:name="FLUTTER_NOTIFICATION_CLICK"/>
>                 <category android:name="android.intent.category.DEFAULT"/>
>             </intent-filter>
> 
>             <meta-data android:name="io.flutter.embedding.android.SplashScreenDrawable" android:resource="@drawable/launch_background" />
> 
>             
>             <meta-data android:name="io.flutter.embedding.android.NormalTheme" android:resource="@style/NormalTheme" />
> 
>         </activity>
> 
>         <meta-data android:name="flutterEmbedding" android:value="2" />
> 
>     </application>
> </manifest>
> ```
> 
> Add NormalTheme.
> **styles.xml**
> 
> ```
> 
> <?xml version="1.0" encoding="utf-8"?>
> <resources>
>     <style name="LaunchTheme" parent="@android:style/Theme.Black.NoTitleBar">
>         
>         <item name="android:windowBackground">@drawable/launch_background</item>
>     </style>
> 
>     <style name="NormalTheme" parent="@android:style/Theme.Black.NoTitleBar">
>     <item name="android:windowBackground">@drawable/launch_background</item>
> </style>
> </resources>
> ```

For some reason on prev version of Flutter I have to remove this line

`GeneratedPluginRegistrant.registerWith(flutterEngine);`

In order for my local plugins works, now with this new version of Flutter I uncomment this line and works again the other plugings

**Comment by guilherme-v** [comment]
The [official doc](https://flutter.dev/docs/development/platform-integration/platform-channels) and the [update project doc](https://github.com/flutter/flutter/wiki/Upgrading-pre-1.12-Android-projects)  seems to be missing the super call on configureFlutterEngine: 
```
...
class MainActivity: FlutterActivity() {
...
  override fun configureFlutterEngine(@NonNull flutterEngine: FlutterEngine) {
    MethodChannel(flutterEngine.dartExecutor.binaryMessenger, CHANNEL).setMethodCallHandler {
      call, result -> ...
    }
  }
}
```

You should just need to call ``super`` on the method like this: 
```
override fun configureFlutterEngine(flutterEngine: FlutterEngine) {
    super.configureFlutterEngine(flutterEngine)

    MethodChannel(flutterEngine.dartExecutor.binaryMessenger, CHANNEL)
      .setMethodCallHandler { call, result ->
        ...
      }
  }
```

**Comment by mhnowak** [comment]
> The [official doc](https://flutter.dev/docs/development/platform-integration/platform-channels) and the [update project doc](https://github.com/flutter/flutter/wiki/Upgrading-pre-1.12-Android-projects) seems to be missing the super call on configureFlutterEngine:
> 
> ```
> ...
> class MainActivity: FlutterActivity() {
> ...
>   override fun configureFlutterEngine(@NonNull flutterEngine: FlutterEngine) {
>     MethodChannel(flutterEngine.dartExecutor.binaryMessenger, CHANNEL).setMethodCallHandler {
>       call, result -> ...
>     }
>   }
> }
> ```
> 
> You should just need to call `super` on the method like this:
> 
> ```
> override fun configureFlutterEngine(flutterEngine: FlutterEngine) {
>     super.configureFlutterEngine(flutterEngine)
> 
>     MethodChannel(flutterEngine.dartExecutor.binaryMessenger, CHANNEL)
>       .setMethodCallHandler { call, result ->
>         ...
>       }
>   }
> ```

Thanks. That fixed the issue for me. 😃

**Comment by ayinloya** [comment]
I have tried most of the solutions but nothing seems to work.
This is a link to a repo with skeleton code of the issue

[https://github.com/ayinloya/sharedpref_test](https://github.com/ayinloya/sharedpref_test)

I would glad for your help, thanks.

**Comment by VladyslavBondarenko** [comment]
Hi @ayinloya 
use
```
import io.flutter.embedding.android.FlutterActivity

class MainActivity: FlutterActivity() {
}
```

or https://github.com/flutter/flutter/issues/41119#issuecomment-625128400 if you need to have FlutterFragmentActivity

**Comment by ayinloya** [comment]
Hi @VladyslavBondarenko 
Thanks, it works perfectly now
I don't know why it didn't work before

**Comment by NicoPowers** [comment]
> Hi @adwpc
> have you run `flutter pub get` before running your app?
> does `flutter clean` helps?
> provide please your `flutter doctor -v`

This worked for me

**Comment by westy92** [comment]
@guilherme-v's solution of adding `super.configureFlutterEngine(flutterEngine)` fixed it for me!

**Comment by xster** [comment]
I'm tentatively closing this one. The website and wiki have been updated and the remaining FlutterFragmentActivity issue is https://github.com/flutter/flutter/issues/54386

**Comment by followthemoney1** [comment]
this may help you```class MainActivity: FlutterFragmentActivity() {

  override fun configureFlutterEngine(flutterEngine: FlutterEngine) {
    super.configureFlutterEngine(flutterEngine);
    GeneratedPluginRegistrant.registerWith(flutterEngine);```

**Comment by rohankumara** [comment]
> ## Steps to Reproduce
> flutter run
> 
> Launching lib/main.dart on GT N7100 in debug mode...
> W/FlutterActivity(31868): Tried to automatically register plugins with FlutterEngine (io.flutter.embedding.engine.FlutterEngine@426467b0) but could not find and invoke the GeneratedPluginRegistrant.
> E/flutter (31868): [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: MissingPluginException(No implementation found for method getAll on channel plugins.flutter.io/shared_preferences)
> **Expected results:**
> 
> **Actual results:**
> 
> Logs

Whenever you add a new plugin in pubspec.yaml, you have to restart the app.

**Comment by nhatmoc97** [comment]
> The problem seems to be solved by doing :
> `flutter create .`

fuckyou

**Comment by xster** [comment]
@nhatmoc97 please use productive language. If you're still seeing issues relating to this on the latest stable, please create a new issue with reproduction details.

**Comment by Kedar-27** [comment]
Facing same issue in release build in current stable channel Flutter 2.0

**Comment by nirbar89** [comment]
> Facing same issue in release build in current stable channel Flutter 2.0

Me too...

**Comment by W34therwax** [comment]
> > Facing same issue in release build in current stable channel Flutter 2.0
> 
> Me too...

And me too :/

**Comment by csongorkeller** [comment]
> Facing same issue in release build in current stable channel Flutter 2.0

mee too :(

**Comment by xster** [comment]
Reopening. @TahaTesser can you see if the issue still reproduces with https://github.com/flutter/flutter/issues/54845#issuecomment-649765146?

**Comment by mtrfnvwork** [comment]
> > Facing same issue in release build in current stable channel Flutter 2.0
> 
> mee too :(

In my case the problem in packages image_picker and file_picker. Without them I don't see any errors. But I haven't found a solution yet

**Comment by TahaTesser** [comment]
@xster  

> Facing same issue in release build in current stable channel Flutter 2.0

New comments here are referring to this issue https://github.com/flutter/flutter/issues/78625 
Where it shared_preferecnes or other packages could break in release mode when using Android Gradle 4.1

**Comment by ArleiAOJR** [comment]
> > Hi @adwpc
> > have you run `flutter pub get` before running your app?
> > does `flutter clean` helps?
> > provide please your `flutter doctor -v`
> 
> This worked for me

I did it, and at the end I did "flutter create .". Resolved for me. Tks.
