### ISSUE TITLE
Flutter compilation error after implementing stream provider.

### ISSUE THREAD

**Issue by vivek781113** [flutter/flutter#54840]
```
D:\workspaces\flutter_demos\st_mgmt_provider>flutter run
Using hardware rendering with device Android SDK built for x86. If you get graphics
artifacts, consider enabling software rendering with "--enable-software-rendering".
Launching lib\main.dart on Android SDK built for x86 in debug mode...
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
registerResGeneratingTask is deprecated, use registerGeneratedResFolders(FileCollection)
Unhandled exception:
Crash when compiling package:st_mgmt_provider/services/database_service.dart,
at character offset null:
**NoSuchMethodError: The getter 'isEof' was called on null.
Receiver: null
Tried calling: isEof**
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:53:5)
#1      scannerRecovery (package:_fe_analyzer_shared/src/scanner/recover.dart:29:17)
#2      _tokenizeAndRecover (package:_fe_analyzer_shared/src/scanner/scanner.dart:102:14)
#3      scan (package:_fe_analyzer_shared/src/scanner/scanner.dart:81:10)
#4      SourceLoader.tokenize (package:front_end/src/fasta/source/source_loader.dart:220:28)
<asynchronous suspension>
#5      SourceLoader.buildOutline (package:front_end/src/fasta/source/source_loader.dart:294:26)
<asynchronous suspension>
#6      Loader.buildOutlines (package:front_end/src/fasta/loader.dart:255:13)
<asynchronous suspension>
#7      KernelTarget.buildOutlines.<anonymous closure> (package:front_end/src/fasta/kernel/kernel_target.dart:257:20)
#8      withCrashRepo
rting (package:front_end/src/fasta/crash.dart:122:24)
#9      KernelTarget.buildOutlines (package:front_end/src/fasta/kernel/kernel_target.dart:255:12)
#10     generateKernelInternal.<anonymous closure> (package:front_end/src/kernel_generator_impl.dart:129:28)
<asynchronous suspension>
#11     withCrashReporting (package:front_end/src/fasta/crash.dart:122:24)
#12     generateKernelInternal (package:front_end/src/kernel_generator_impl.dart:70:10)
#13     kernelForProgramInternal.<anonymous closure> (package:front_end/src/api_prototype/kernel_generator.dart:61:35)
#14     CompilerContext.runWithOptions.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart:135:20)
<asynchronous suspension>
#15     CompilerContext.runInContext.<anonymous closure>.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart:123:46)
#16     new Future.sync (dart:async/future.dart:224:31)
#17     CompilerContext.runInContext.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart:123:19)
#18     _rootRun (dart:async/zone.dart:1126:13)
#19     _CustomZone.run (dart:async/zone.dart:1023:19)
#20     _runZoned (dart:async/zone.dart:1518:10)
#21     runZoned (dart:async/zone.dart:1465:12)
#22     CompilerContext.runInContext (package:front_end/src/fasta/compiler_context.dart:122:12)
#23     CompilerContext.runWithOptions (package:front_end/src/fasta/compiler_context.dart:133:10)
#24     kernelForProgramInternal (package:front_end/src/api_prototype/kernel_generator.dart:60:32)
#25     kernelForProgram (package:front_end/src/api_prototype/kernel_generator.dart:52:17)
#26     compileToKernel (package:vm/kernel_front_end.dart:320:41)
#27     FrontendCompiler.compile.<anonymous closure> (package:frontend_server/frontend_server.dart:4
46:54)
#28     new Future.<anonymous closure> (dart:async/future.dart:176:37)
#29     _rootRun (dart:async/zone.dart:1122:38)
#30     _CustomZone.run (dart:async/zone.dart:1023:19)
#31     _CustomZone.runGuarded (dart:async/zone.dart:925:7)
#32     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:965:23)
#33     _rootRun (dart:async/zone.dart:1126:13)
#34     _CustomZone.run (dart:async/zone.dart:1023:19)
#35     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:949:23)
#36     Timer._createTimer.<anonymous closure> (dart:async-patch/timer_patch.dart:23:15)
#37     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:384:19)
#38     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:418:5)
#39     _RawReceivePortI
mpl._handleMessage (dart:isolate-patch/isolate_patch.dart:174:12)


#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:53:5)
#1      scannerRecovery (package:_fe_analyzer_shared/src/scanner/recover.dart:29:17)
#2      _tokenizeAndRecover (package:_fe_analyzer_shared/src/scanner/scanner.dart:102:14)
#3      scan (package:_fe_analyzer_shared/src/scanner/scanner.dart:81:10)
#4      SourceLoader.tokenize (package:front_end/src/fasta/source/source_loader.dart:220:28)
<asynchronous suspension>
#5      SourceLoader.buildOutline (package:front_end/src/fasta/source/source_loader.dart:294:26)
<asynchronous suspension>
#6      Loader.buildOutlines (package:front_end/src/fasta/loader.dart:255:13)
<asynchronous suspension>
#7      KernelTarget.buildOutlines.<anonymous closure> (package:front_end/src/fasta/kernel/kernel_target.dart:257:20)
#8      withCrashReporting (package:front_end/src/fasta/crash.dart:122:24)
#9      KernelTarget.buildOutlines (package:front_end/src/fasta/kernel/kernel_target.dart:255:12)
#10     generateKernelInternal.<anonymous closure> (package:front_end/src/kernel_generator_impl.dart:129:28)
<asynchronous suspension>
#11     withCrashReporting (package:front_end/src/fasta/crash.dart:122:24)
#12     generateKernelInternal (package:front_end/src/kernel_generator_impl.dart:70:10)
#13     kernelForProgramInternal.<anonymous closure> (package:front_end/src/api_prototype/kernel_generator.dart:61:35)
#14     CompilerContext.runWithOptions.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart:135:20)
<asynchronous suspension>
#15     CompilerContext.runInContext.<anonymous closure>.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart:123:46)
#16     new Future.sync (dart:async/future.dart:224:31)
#17     CompilerContext.runInContext.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart:123:19)
#18     _rootRun (dart:async/zone.dart:1126:13)
#19     _CustomZone.run (dart:async/zone.dart:1023:19)
#20     _runZoned (dart:async/zone.dart:1518:10)
#21     runZoned (dart:async/zone.dart:1465:12)
#22     CompilerContext.runInContext (package:front_end/src/fasta/compiler_context.dart:122:12)
#23     CompilerContext.runWithOptions (package:front_end/src/fasta/compiler_context
.dart:133:10)
#24     kernelForProgramInternal (package:front_end/src/api_prototype/kernel_generator.dart:60:32)
#25     kernelForProgram (package:front_end/src/api_prototype/kernel_generator.dart:52:17)
#26     compileToKernel (package:vm/kernel_front_end.dart:320:41)
#27     FrontendCompiler.compile.<anonymous closure> (package:frontend_server/frontend_server.dart:446:54)
#28     new Future.<anonymous closure> (dart:async/future.dart:176:37)
#29     _rootRun (dart:async/zone.dart:1122:38)
#30     _CustomZone.run (dart:async/zone.dart:1023:19)
#31     _CustomZone.runGuarded (dart:async/zone.dart:925:7)
#32     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:965:23)
#33     _rootRun (dart:async/zone.dart:1126:13)
#34     _CustomZone.run (dart:async/zone.dart:1023:19)
#35     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:949:23)
#36     Timer._createTimer.<anonymous closure> (dart:async-patch/timer_patch.dart:23:15)
#37     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:384:19)
#38     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:418:5)
#39     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:174:12)

Target kernel_snapshot failed: Exception: Errors during snapshot creation: null
build failed.

FAILURE: Build failed with an exception.

* Where:
Script 'C:\Users\164115\flutter\packages\flutter_tools\gradle\flutter.gradle' line: 780

* What went wrong:
Execution failed for task ':app:compileFlutterBuildDebug'.
> Process 'command 'C:\Users\164115\flutter\bin\flutter.bat'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 16s
Running Gradle task 'assembleDebug'...
Running Gradle task 'assembleDebug'... Done                        19.5s
Gradle task assembleDebug failed with exit code 1
```

**Comment by jensjoha** [comment]
What version of flutter (as I recall `flutter version -v`) are you on?

**Comment by VladyslavBondarenko** [comment]
@vivek781113 
could you provide complete minimal reproducible code sample?

**Comment by vivek781113** [comment]
@VladyslavBondarenko  adding the source code repository :
https://github.com/vivek781113/st_mgmt_provider.git

**Comment by vivek781113** [comment]
@jensjoha flutter version : Flutter 1.12.13+hotfix.9 • channel stable • https://github.com/flutter/flutter.git
Framework • revision f139b11009 (2 weeks ago) • 2020-03-30 13:57:30 -0700
Engine • revision af51afceb8
Tools • Dart 2.7.2

**Comment by vivek781113** [comment]
After commenting out MultipleProvider, I was able run the app, but I need mutliprovider.
![CommentedMuiltProvider](https://user-images.githubusercontent.com/32304458/79431781-817fd480-7fe8-11ea-8739-b15fbddc2d5b.JPG)

**Comment by jensjoha** [comment]
First let me say this: It shouldn't crash, and I'll work on fixing that.

To help you processed now: Your file `lib/services/database_service.dart` is  "Little-endian UTF-16 Unicode text, with CRLF line terminators" (which, apparently, we don't handle very gracefully).

Fix it by converting it to utf-8 and everything should go back to normal.
To do this you could try copy pasting the text into a new file and saving that, overwriting the old file; or maybe your editor can convert it to utf-8 for you (in VSCode it appears that if you open the file, it'll say "UTF-16 LE" at the bottom, clicking on it allows you to say "Save with encoding" which allows you to pick utf-8).

(The reason it fixes the problem to comment stuff out, btw, is not that you comment out "MultipleProvider", but because you comment out the import of `lib/services/database_service.dart`).

**Comment by vivek781113** [comment]
> First let me say this: It shouldn't crash, and I'll work on fixing that.
> 
> To help you processed now: Your file `lib/services/database_service.dart` is "Little-endian UTF-16 Unicode text, with CRLF line terminators" (which, apparently, we don't handle very gracefully).
> 
> Fix it by converting it to utf-8 and everything should go back to normal.
> To do this you could try copy pasting the text into a new file and saving that, overwriting the old file; or maybe your editor can convert it to utf-8 for you (in VSCode it appears that if you open the file, it'll say "UTF-16 LE" at the bottom, clicking on it allows you to say "Save with encoding" which allows you to pick utf-8).
> 
> (The reason it fixes the problem to comment stuff out, btw, is not that you comment out "MultipleProvider", but because you comment out the import of `lib/services/database_service.dart`).

Thanks

**Comment by vivek781113** [comment]
@jensjoha  Thank you very much, was not able to trace out the root cause. Now its working, but it would be help if we get clear message to use UTF-8. 
Again, thanks for the prompt response.
