### ISSUE TITLE
_kBackGestureWidth in CupertinoPageRoute interferes with buttons and crashes

### ISSUE THREAD

**Issue by henk789** [flutter/flutter#54868]
I am using a CupertinoPageRoute and increased the _kBackGestureWidth in my application to make the back gesture accessible from a larger part of the screen. 

Setting `_kBackGestureWidth = 300.0` now interferes with buttons and other `GestureDetectors` placed in that area, though.

Tapping and holding the button, tapping somewhere else in the area of the back gesture and then releasing the button results in a crash of the application.

### Steps to reproduce

1. Run `flutter create bug`
2. Update the files as follows:
<details>
<summary>main.dart</summary>

```
import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: MyHomePage(),
    );
  }
}

class MyHomePage extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
        body: Center(
      child: MaterialButton(
        onPressed: () {
          Navigator.of(context).push(CupertinoPageRoute(
              builder: (BuildContext context) => MySecondPage()));
        },
        child: Text('tap here'),
      ),
    ));
  }
}

class MySecondPage extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
        body: Center(
      child: MaterialButton(
        onPressed: () {},
        child: Text('second button'),
      ),
    ));
  }
}
```
</details>

3. Set `_kBackGestureWidth = 300.0` in lib/cupertino/route.dart
4. Launch the app and tap the button to navigate to the second page and create the back gesture.
5. Tap and hold the button `second button`. While holding, tap with another finger somewhere left of the button. After the tap, release the finger holding the button.

**Expected results:**
The button should release normally.

**Actual results:** 
The application prints `'_initialButtons == kPrimaryButton': is not true.` and stops reacting.

The issue is reproducible on iOS and Android. 

<details>
  <summary>Logs</summary>

```
[+112347 ms] I/flutter ( 9978): ══╡ EXCEPTION CAUGHT BY GESTURE LIBRARY ╞═══════════════════════════════════════════════════════════
[   +7 ms] I/flutter ( 9978): The following assertion was thrown while dispatching a pointer event:
[  +46 ms] I/flutter ( 9978): 'package:flutter/src/gestures/monodrag.dart': Failed assertion: line 377 pos 12: '_initialButtons ==
[        ] I/flutter ( 9978): kPrimaryButton': is not true.
[        ] I/flutter ( 9978): 
[        ] I/flutter ( 9978): Either the assertion indicates an error in the framework itself, or we should provide substantially
[  +19 ms] I/flutter ( 9978): more information in this error message to help you determine and fix the underlying cause.
[        ] I/flutter ( 9978): In either case, please report this assertion by filing a bug on GitHub:
[        ] I/flutter ( 9978):   https://github.com/flutter/flutter/issues/new?template=BUG.md
[        ] I/flutter ( 9978):
[   +1 ms] I/flutter ( 9978): When the exception was thrown, this was the stack:
[        ] I/flutter ( 9978): #2      DragGestureRecognizer._checkStart (package:flutter/src/gestures/monodrag.dart:377:12)
[        ] I/flutter ( 9978): #3      DragGestureRecognizer.acceptGesture (package:flutter/src/gestures/monodrag.dart:308:7)
[   +1 ms] I/flutter ( 9978): #4      GestureArenaManager.sweep (package:flutter/src/gestures/arena.dart:156:27)
[  +12 ms] I/flutter ( 9978): #5      GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:222:20)
[  +11 ms] I/flutter ( 9978): #6      GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:198:22)
[        ] I/flutter ( 9978): #7      GestureBinding._handlePointerEvent (package:flutter/src/gestures/binding.dart:156:7)
[        ] I/flutter ( 9978): #8      GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:102:7)
[        ] I/flutter ( 9978): #9      GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:86:7)
[        ] I/flutter ( 9978): #13     _invoke1 (dart:ui/hooks.dart:273:10)
[        ] I/flutter ( 9978): #14     _dispatchPointerDataPacket (dart:ui/hooks.dart:182:5)
[  +12 ms] I/flutter ( 9978): (elided 5 frames from class _AssertionError and package dart:async)
[        ] I/flutter ( 9978):
[   +1 ms] I/flutter ( 9978): Event:
[  +11 ms] I/flutter ( 9978):   PointerUpEvent#c4952(position: Offset(214.1, 371.8), timeStamp: 3:57:46.483000, pointer: 2, kind:
[        ] I/flutter ( 9978):   touch, down: false, pressureMin: 0.0, size: 0.0, radiusMajor: 3.8, radiusMinor: 2.7)
[        ] I/flutter ( 9978): Target:
[        ] I/flutter ( 9978):   <WidgetsFlutterBinding>
[  +10 ms] I/flutter ( 9978): ════════════════════════════════════════════════════════════════════════════════════════════════════
```

</details>

<details>
   <summary>Flutter doctor</summary>

```
[√] Flutter (Channel stable, v1.12.13+hotfix.9, on Microsoft Windows [Version 10.0.18363.752], locale de-DE)
    • Flutter version 1.12.13+hotfix.9 at M:\flutter
    • Framework revision f139b11009 (2 weeks ago), 2020-03-30 13:57:30 -0700
    • Engine revision af51afceb8
    • Dart version 2.7.2


[√] Android toolchain - develop for Android devices (Android SDK version 29.0.1)
    • Android SDK at M:\Android\SDK
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.1
    • ANDROID_SDK_ROOT = M:\Android\SDK
    • Java binary at: M:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)
    • All Android licenses accepted.

[√] Android Studio (version 3.6)
    • Android Studio at M:\Program Files\Android\Android Studio
    • Flutter plugin version 44.0.2
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)

[√] Connected device (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 10 (API 29) (emulator)

• No issues found!
```
</details>

**Comment by TahaTesser** [comment]
<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel master, v1.18.0-6.0.pre.26, on Mac OS X 10.15.4 19E287,
    locale en-GB)
    • Flutter version 1.18.0-6.0.pre.26 at /Users/taha/Code/flutter_play
    • Framework revision 846e8fe812 (32 hours ago), 2020-04-15 03:21:14 +0200
    • Engine revision deef2663ac
    • Dart version 2.8.0 (build 2.8.0-dev.20.0 c9710e5059)
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/taha/Code/sdk
    • Platform android-29, build-tools 29.0.3
    • ANDROID_HOME = /Users/taha/Code/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.
[✓] Xcode - develop for iOS and macOS (Xcode 11.4)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.4, Build version 11E146
    • CocoaPods version 1.9.1
[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome
[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build
      1.8.0_212-release-1586-b4-5784211)
[✓] VS Code (version 1.44.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.9.1
 
[✓] Connected device (5 available)            
    • SM M305F      • 32003c30dc19668f          •
      android-arm64  • Android 10 (API 29)
    • Taha’s iPhone • 00008020-001059882212002E • ios
      • iOS 13.4.1
    • macOS         • macOS                     •
      darwin-x64     • Mac OS X 10.15.4 19E287
    • Chrome        • chrome                    •
      web-javascript • Google Chrome 81.0.4044.113
    • Web Server    • web-server                •
      web-javascript • Flutter Tools
• No issues found!
```

</details>

**Comment by goderbauer** [comment]
`_kBackGestureWidth` is a private constant, Flutter doesn't really support changing it.

**Comment by TahaTesser** [comment]
Hi @henk789 
Closing based on above [comment](https://github.com/flutter/flutter/issues/54868#issuecomment-618060248)

Closing, as this isn't an issue with Flutter itself,
if you disagree please write in the comments and I will reopen it
Thank you

**Comment by henk789** [comment]
I managed to reproduce the error without changing the private constant. The steps then need to be performed within the 20 pixels of the GestureDetector and the button needs to be placed on the left side of the screen.

This may be an issue for back buttons that can be in that area.

Increasing `_kBackGestureWidth` just creates a larger area in which the error can happen.

**Comment by TahaTesser** [comment]
Hi @henk789 
Could you please provide a minimal code sample for that?
Thank you

**Comment by henk789** [comment]
<details>
<summary>main.dart</summary>

```
import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: MyHomePage(),
    );
  }
}

class MyHomePage extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Center(
        child: Container(
          width: 400,
          child: MaterialButton(
            onPressed: () {
              Navigator.of(context).push(CupertinoPageRoute(
                  builder: (BuildContext context) => MySecondPage()));
            },
            child: Text('tap here'),
          ),
        ),
      ),
    );
  }
}

class MySecondPage extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
        body: SafeArea(
            child: Column(
      children: <Widget>[
        Align(
            alignment: Alignment.topLeft,
            child: Container(
              color: Colors.lightGreenAccent,
              width: 40,
              child: MaterialButton(
                  onPressed: () {}, child: Icon(Icons.arrow_back)),
            )),
        Expanded(
          child: Align(
            alignment: Alignment.topLeft,
            child: Container(
              color: Colors.grey,
              width: 20,
            ),
          ),
        )
      ],
    )));
  }
}
```
</details>

The steps to reproduce the error are the same:

1. Tap and hold the back button on the left side (the 20px of the GestureGetector)
2. Tap somewhere within the 20px of the GestureDetector (grey area) and release
3. Then release the finger holding the button, the error above occurs.

**Comment by TahaTesser** [comment]
<details> 
<summary>logs</summary> 

``` 

════════ Exception caught by gesture library ═══════════════════════════════════
'package:flutter/src/gestures/monodrag.dart': Failed assertion: line 377 pos 12: '_initialButtons == kPrimaryButton': is not true.
════════════════════════════════════════════════════════════════════════════════
``` 

</details> 

<details> 
<summary>flutter doctor -v</summary> 

``` 
[✓] Flutter (Channel dev, v1.18.0-8.0.pre, on Mac OS X 10.15.4 19E287, locale
    en-GB)
    • Flutter version 1.18.0-8.0.pre at /Users/taha/Code/flutter_dev
    • Framework revision e0c63cd35e (11 days ago), 2020-04-23 22:29:01 -0400
    • Engine revision d2ec21221e
    • Dart version 2.9.0 (build 2.9.0-3.0.dev b0d35855d8)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/taha/Code/sdk
    • Platform android-29, build-tools 29.0.3
    • ANDROID_HOME = /Users/taha/Code/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.4.1, Build version 11E503a
    • CocoaPods version 1.9.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build
      1.8.0_212-release-1586-b4-5784211)

[✓] VS Code (version 1.44.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.10.1

[✓] Connected device (4 available)
    • SM M305F   • 32003c30dc19668f • android-arm64  • Android 10 (API 29)
    • macOS      • macOS            • darwin-x64     • Mac OS X 10.15.4 19E287
    • Web Server • web-server       • web-javascript • Flutter Tools
    • Chrome     • chrome           • web-javascript • Google Chrome
      81.0.4044.129

• No issues found!
``` 

</details>

**Comment by chunhtai** [comment]
cc @dkwingsmt who have been working on gesture

**Comment by TahaTesser** [comment]
<details>
<summary>code sample</summary>

```dart
import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: MyHomePage(),
    );
  }
}

class MyHomePage extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Center(
        child: Container(
          width: 400,
          child: MaterialButton(
            onPressed: () {
              Navigator.of(context).push(CupertinoPageRoute(
                  builder: (BuildContext context) => MySecondPage()));
            },
            child: Text('tap here'),
          ),
        ),
      ),
    );
  }
}

class MySecondPage extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
        body: SafeArea(
            child: Column(
      children: <Widget>[
        Align(
            alignment: Alignment.topLeft,
            child: Container(
              color: Colors.lightGreenAccent,
              width: 40,
              child: MaterialButton(
                  onPressed: () {}, child: Icon(Icons.arrow_back)),
            )),
        Expanded(
          child: Align(
            alignment: Alignment.topLeft,
            child: Container(
              color: Colors.grey,
              width: 20,
            ),
          ),
        )
      ],
    )));
  }
}
```
</details>



<details>
<summary>logs</summary>

```bash
ssues/62507
[  +25 ms] Successfully connected to service protocol: http://localhost:61412
[   +2 ms] Waiting for Taha’s iPhone to report its views...
[   +4 ms] Waiting for Taha’s iPhone to report its views... (completed in 3ms)
[   +6 ms] DevFS: Creating new filesystem on the device (null)
[   +9 ms] DevFS: Created new filesystem on the device (file:///private/var/mobile/Containers/Data/Application/A338C423-D9DC-4580-B22B-56C845AEA610/tmp/stable_flutterFYjZ6U/stable_flutter/)
[   +4 ms] Updating assets
[ +126 ms] Syncing files to device Taha’s iPhone...
[   +1 ms] Scanning asset files
[   +2 ms] <- reset
[        ] Compiling dart to kernel with 0 updated files
[   +1 ms] <- recompile package:triage/main.dart 200ce7c2-0a82-4402-80b1-1850e62a01ec
[        ] <- 200ce7c2-0a82-4402-80b1-1850e62a01ec
[  +45 ms] Updating files
[  +94 ms] DevFS: Sync finished
[   +1 ms] Syncing files to device Taha’s iPhone... (completed in 145ms)
[   +1 ms] Synced 1.8MB.
[   +1 ms] <- accept
[   +3 ms] Connected to _flutterView/0x14e03d020.
[   +2 ms] Flutter run key commands.
[   +2 ms] r Hot reload. 🔥🔥🔥
[   +1 ms] R Hot restart.
[        ] h Repeat this help message.
[        ] d Detach (terminate "flutter run" but leave application running).
[        ] c Clear the screen
[        ] q Quit (terminate the application on the device).
[        ] An Observatory debugger and profiler on Taha’s iPhone is available at: http://localhost:61412
[+45505 ms] flutter: ══╡ EXCEPTION CAUGHT BY GESTURE LIBRARY ╞═══════════════════════════════════════════════════════════
[   +5 ms] flutter: The following _CastError was thrown while dispatching a pointer event:
[   +2 ms] flutter: Null check operator used on a null value
[        ] flutter: 
[        ] flutter: When the exception was thrown, this was the stack:
[        ] flutter: #0      DragGestureRecognizer.acceptGesture (package:flutter/src/gestures/monodrag.dart:321:60)
[        ] flutter: #1      GestureArenaManager.sweep (package:flutter/src/gestures/arena.dart:157:27)
[        ] flutter: #2      GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:362:20)
[        ] flutter: #3      GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:338:22)
[        ] flutter: #4      RendererBinding.dispatchEvent (package:flutter/src/rendering/binding.dart:267:11)
[        ] flutter: #5      GestureBinding._handlePointerEvent (package:flutter/src/gestures/binding.dart:295:7)
[        ] flutter: #6      GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:240:7)
[        ] flutter: #7      GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:213:7)
[        ] flutter: #11     _invoke1 (dart:ui/hooks.dart:265:10)
[        ] flutter: #12     _dispatchPointerDataPacket (dart:ui/hooks.dart:174:5)
[        ] flutter: (elided 3 frames from dart:async)
[        ] flutter: 
[        ] flutter: Event:
[        ] flutter:   PointerUpEvent#fca2d(position: Offset(15.0, 65.0))
[        ] flutter: Target:
[        ] flutter:   <WidgetsFlutterBinding>
[        ] flutter: ════════════════════════════════════════════════════════════════════════════════════════════════════
[ +531 ms] flutter: Another exception was thrown: 'package:flutter/src/gestures/monodrag.dart': Failed assertion: line 435 pos 12: '_initialButtons == kPrimaryButton': is not true.
[+1108 ms] flutter: Another exception was thrown: 'package:flutter/src/gestures/monodrag.dart': Failed assertion: line 435 pos 12: '_initialButtons == kPrimaryButton': is not true.
[ +350 ms] flutter: Another exception was thrown: 'package:flutter/src/gestures/monodrag.dart': Failed assertion: line 435 pos 12: '_initialButtons == kPrimaryButton': is not true.
[ +951 ms] flutter: Another exception was thrown: 'package:flutter/src/gestures/monodrag.dart': Failed assertion: line 435 pos 12: '_initialButtons == kPrimaryButton': is not true.
[ +140 ms] flutter: Another exception was thrown: 'package:flutter/src/gestures/monodrag.dart': Failed assertion: line 435 pos 12: '_initialButtons == kPrimaryButton': is not true.
[ +164 ms] flutter: Another exception was thrown: 'package:flutter/src/gestures/monodrag.dart': Failed assertion: line 435 pos 12: '_initialButtons == kPrimaryButton': is not true.
[ +142 ms] flutter: Another exception was thrown: 'package:flutter/src/gestures/monodrag.dart': Failed assertion: line 435 pos 12: '_initialButtons == kPrimaryButton': is not true.
```
</details>


<details>
<summary>flutter doctor -v</summary>

```bash
[✓] Flutter (Channel stable, 1.22.5, on macOS 11.1 20C69 darwin-x64, locale en-GB)
    • Flutter version 1.22.5 at /Users/tahatesser/Code/flutter_stable
    • Framework revision 7891006299 (5 weeks ago), 2020-12-10 11:54:40 -0800
    • Engine revision ae90085a84
    • Dart version 2.10.4

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Volumes/Extreme/SDK
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = /Volumes/Extreme/SDK
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.3)
    • Xcode at /Volumes/Extreme/Xcode.app/Contents/Developer
    • Xcode 12.3, Build version 12C33
    • CocoaPods version 1.10.1

[!] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.52.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.18.1

[✓] Connected device (1 available)
    • Taha’s iPhone (mobile) • 00008020-001059882212002E • ios • iOS 14.3

! Doctor found issues in 1 category.
```
```bash
[✓] Flutter (Channel master, 1.26.0-2.0.pre.337, on macOS 11.1 20C69 darwin-x64, locale en-GB)
    • Flutter version 1.26.0-2.0.pre.337 at /Users/tahatesser/Code/flutter_master
    • Framework revision 0768daaae3 (5 hours ago), 2021-01-14 05:39:03 -0500
    • Engine revision 1b5e16cda2
    • Dart version 2.12.0 (build 2.12.0-223.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Volumes/Extreme/SDK
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = /Volumes/Extreme/SDK
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Volumes/Extreme/Xcode.app/Contents/Developer
    • Xcode 12.3, Build version 12C33
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.52.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.18.1

[✓] Connected device (3 available)
    • Taha’s iPhone (mobile) • 00008020-001059882212002E • ios            • iOS 14.3
    • macOS (desktop)        • macos                     • darwin-x64     • macOS 11.1 20C69 darwin-x64
    • Chrome (web)           • chrome                    • web-javascript • Google Chrome 87.0.4280.141

• No issues found!
```

</details>

**Comment by marcglasberg** [comment]
Hey, any solution to this?

**Comment by maheshmnj** [comment]
Hi @henk789, I tried to reproduce the issue and its no longer  reproducible (with `const double _kBackGestureWidth = 300.0;`)


https://user-images.githubusercontent.com/31410839/210291360-681733a1-4cbf-4031-815d-ebe73b7496a5.mov


<details>
<summary>code sample</summary>

```dart
import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';

void main() => runApp(const MyApp());

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: const MyHomePage(),
    );
  }
}

class MyHomePage extends StatelessWidget {
  const MyHomePage({super.key});

  @override
  Widget build(BuildContext context) {
    return Scaffold(
        body: Center(
      child: MaterialButton(
        onPressed: () {
          Navigator.of(context).push(CupertinoPageRoute(
              builder: (BuildContext context) => const MySecondPage()));
        },
        child: const Text('tap here'),
      ),
    ));
  }
}

class MySecondPage extends StatelessWidget {
  const MySecondPage({super.key});

  @override
  Widget build(BuildContext context) {
    return Scaffold(
        body: Center(
      child: MaterialButton(
        onPressed: () {},
        child: const Text('second button'),
      ),
    ));
  }
}

```
</details> 

<details>
<summary>flutter doctor -v (mac)</summary>

```
[✓] Flutter (Channel master, 3.7.0-13.0.pre.131, on macOS 13.1 22C65 darwin-arm64, locale en-IN)
    • Flutter version 3.7.0-13.0.pre.131 on channel master at /Users/mahesh/Development/flutter_master
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 0196e6050b (2 days ago), 2022-12-31 11:10:23 -0500
    • Engine revision 932591ec04
    • Dart version 3.0.0 (build 3.0.0-76.0.dev)
    • DevTools version 2.20.0
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly to perform update checks
      and upgrades.

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0-rc4)
    • Android SDK at /Users/mahesh/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0-rc4
    • ANDROID_HOME = /Users/mahesh/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14A400
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] IntelliJ IDEA Community Edition (version 2021.2.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 61.2.4
    • Dart plugin version 212.5080.8

[✓] VS Code (version 1.74.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.56.0

[✓] Connected device (3 available)
    • iPhone 12 Pro (mobile) • 026D5789-9E78-4AD5-B1B2-3F8D4E7F65E4 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-5 (simulator)
    • macOS (desktop)        • macos                                • darwin-arm64   • macOS 13.1 22C65 darwin-arm64
    • Chrome (web)           • chrome                               • web-javascript • Google Chrome 108.0.5359.124

[✓] HTTP Host Availability
    • All required HTTP hosts are available
    
• No issues found!
```
```
[✓] Flutter (Channel stable, 3.3.9, on macOS 12.6 21G115 darwin-arm, locale en-IN)
    • Flutter version 3.3.9 on channel stable at /Users/mahesh/Development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision b8f7f1f986 (24 hours ago), 2022-11-23 06:43:51 +0900
    • Engine revision 8f2221fbef
    • Dart version 2.18.5
    • DevTools version 2.15.0

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0-rc4)
    • Android SDK at /Users/mahesh/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0-rc4
    • ANDROID_HOME = /Users/mahesh/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14A400
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] IntelliJ IDEA Community Edition (version 2021.2.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 61.2.4
    • Dart plugin version 212.5080.8

[✓] VS Code (version 1.70.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.53.20221101

[✓] Connected device (3 available)
    • iPhone 12 Pro (mobile) • 026D5789-9E78-4AD5-B1B2-3F8D4E7F65E4 • ios            •
      com.apple.CoreSimulator.SimRuntime.iOS-14-5 (simulator)
    • macOS (desktop)        • macos                                • darwin-arm64   • macOS 12.6 21G115 darwin-arm
    • Chrome (web)           • chrome                               • web-javascript • Google Chrome 107.0.5304.110

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```
</details>

I am going to close this issue as fixed. Incase you still encounter the issue, Please feel free to write in the comments and we will reopen it.
