### ISSUE TITLE
Flutter dashboard freezes: BindingError: Cannot pass "[object Object]" as a SkPaint*

### ISSUE THREAD

**Issue by jmagman** [flutter/flutter#54901]
When I sit on https://flutter-dashboard.appspot.com/#/build and ~2-3 commits come in at the same time, the dashboard starts animating, then eventually freezes and the console starts spewing exceptions.

Exception in console:
```
BindingError: Cannot pass "[object Object]" as a SkPaint*
    at BindingError.<anonymous> (https://unpkg.com/canvaskit-wasm@0.12.0/bin/canvaskit.js:123:76)
    at new BindingError (eval at Jb (https://unpkg.com/canvaskit-wasm@0.12.0/bin/canvaskit.js:1:1), <anonymous>:4:34)
    at K (https://unpkg.com/canvaskit-wasm@0.12.0/bin/canvaskit.js:125:249)
    at rc.mc [as toWireType] (https://unpkg.com/canvaskit-wasm@0.12.0/bin/canvaskit.js:134:90)
    at SkPaint$setAntiAlias [as setAntiAlias] (eval at yc (https://unpkg.com/canvaskit-wasm@0.12.0/bin/canvaskit.js:1:1), <anonymous>:7:28)
    at dx.a0 (https://flutter-dashboard.appspot.com/main.dart.js:27038:50)
    at aB.aT (https://flutter-dashboard.appspot.com/main.dart.js:18435:3)
    at yF.Vq (https://flutter-dashboard.appspot.com/main.dart.js:29192:7)
    at yF.VV (https://flutter-dashboard.appspot.com/main.dart.js:29179:5)
    at yF.D (https://flutter-dashboard.appspot.com/main.dart.js:29165:36)"
```
Crashing SkPaint$setAntiAlias is line `var thisWired = classParam.toWireType(null, this);`

```js
(function anonymous(throwBindingError,invoker,fn,runDestructors,retType,classParam,argType0
) {
return function SkPaint$setAntiAlias(arg0) {
if (arguments.length !== 1) {
throwBindingError('function SkPaint.setAntiAlias called with ' + arguments.length + ' arguments, expected 1 args!');
}
var thisWired = classParam.toWireType(null, this);
var arg0Wired = argType0.toWireType(null, arg0); // bool
invoker(fn, thisWired, arg0Wired);
}
})
```

**Comment by yjbanov** [comment]
Is this still happening?

**Comment by jmagman** [comment]
@yjbanov It is, I just reproduced it on a second machine by sitting on the dashboard for a few minutes.  Is there anything specific you'd like me to grab?

![Screen Shot 2020-06-16 at 5 12 12 PM](https://user-images.githubusercontent.com/682784/84840494-86670180-aff4-11ea-9ff7-c94fd8820ef7.png)

**Comment by jmagman** [comment]
```js
  b.rk || K('Cannot pass "' + ec(b) + '" as a ' + this.name);
```
b is a `SkPaint`
```js
SkPaint {___dart__$dart_dartObject_ZxYxX_0_: dE}___dart__$dart_dartObject_ZxYxX_0_: dEa: SkPaint___dart__$dart_dartObject_ZxYxX_0_: dE {a: SkPaint}
```

**Comment by yjbanov** [comment]
Update: we're rewriting our CanvasKit bindings. This should be fixed as part of that.

**Comment by yjbanov** [comment]
I expect https://github.com/flutter/engine/pull/19562 to fix it (currently blocked by https://github.com/dart-lang/sdk/issues/42612)
