### ISSUE TITLE
Gradle failed with no route to host

### ISSUE THREAD

**Issue by heibor** [flutter/flutter#54921]
I use Android Studio 3.6 on MacosX to develop flutter. My flutter is `Flutter 1.15.17 • channel beta • https://github.com/flutter/flutter.git`.

When I execute `flutter run`, I got these errors:

`Launching lib/main.dart on A0001 in debug mode...
Running Gradle task 'assembleDebug'...                                  
                                                                
FAILURE: Build failed with an exception.                                                                           
                                                                                                                   
* What went wrong:                                                                                                 
Execution failed for task ':app:compileDebugKotlin'.                                                               
> Could not resolve all artifacts for configuration ':app:debugCompileClasspath'.                                  
   > Could not download armeabi_v7a_debug.jar (io.flutter:armeabi_v7a_debug:1.0.0-5aff3119480996ca014ec0f8d26d74db617b5852)
      > Could not get resource 'https://storage.googleapis.com/download.flutter.io/io/flutter/armeabi_v7a_debug/1.0.0-5aff3119480996ca014ec0f8d26d74db617b5852/armeabi_v7a_debug-1.0.0-5aff3119480996ca014ec0f8d26d74db617b5852.jar'.
         > Could not GET 'https://storage.googleapis.com/download.flutter.io/io/flutter/armeabi_v7a_debug/1.0.0-5aff3119480996ca014ec0f8d26d74db617b5852/armeabi_v7a_debug-1.0.0-5aff3119480996ca014ec0f8d26d74db617b5852.jar'.
            > Connect to storage.googleapis.com:443 [storage.googleapis.com/216.58.200.48, storage.googleapis.com/2404:6800:4008:801:0:0:0:2010] failed: No route to host (connect failed)
   > Could not download x86_debug.jar (io.flutter:x86_debug:1.0.0-5aff3119480996ca014ec0f8d26d74db617b5852)        
      > Could not get resource 'https://storage.googleapis.com/download.flutter.io/io/flutter/x86_debug/1.0.0-5aff3119480996ca014ec0f8d26d74db617b5852/x86_debug-1.0.0-5aff3119480996ca014ec0f8d26d74db617b5852.jar'.
         > Could not GET 'https://storage.googleapis.com/download.flutter.io/io/flutter/x86_debug/1.0.0-5aff3119480996ca014ec0f8d26d74db617b5852/x86_debug-1.0.0-5aff3119480996ca014ec0f8d26d74db617b5852.jar'.
            > Connect to storage.googleapis.com:443 [storage.googleapis.com/216.58.200.48, storage.googleapis.com/2404:6800:4008:801:0:0:0:2010] failed: No route to host (connect failed)
   > Could not download x86_64_debug.jar (io.flutter:x86_64_debug:1.0.0-5aff3119480996ca014ec0f8d26d74db617b5852)  
      > Could not get resource 'https://storage.googleapis.com/download.flutter.io/io/flutter/x86_64_debug/1.0.0-5aff3119480996ca014ec0f8d26d74db617b5852/x86_64_debug-1.0.0-5aff3119480996ca014ec0f8d26d74db617b5852.jar'.
         > Could not GET 'https://storage.googleapis.com/download.flutter.io/io/flutter/x86_64_debug/1.0.0-5aff3119480996ca014ec0f8d26d74db617b5852/x86_64_debug-1.0.0-5aff3119480996ca014ec0f8d26d74db617b5852.jar'.
            > Connect to storage.googleapis.com:443 [storage.googleapis.com/216.58.200.48, storage.googleapis.com/2404:6800:4008:801:0:0:0:2010] failed: No route to host (connect failed)
                                                                                                                   
* Try:                                                                                                             
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
                                                                                                                   
* Get more help at https://help.gradle.org                                                                         
                                                                                                                   
BUILD FAILED in 1m 59s                                                                                             
Running Gradle task 'assembleDebug'...                                                                             
Running Gradle task 'assembleDebug'... Done                       121.6s (!)
Exception: Gradle task assembleDebug failed with exit code 1`

It seems that the Gradle could not download the .jar file. But when copy the url into browser, it can be downloaded without any difficulty.

I'm not sure how to solve this problem. Who can give me some advice? Thanks.

**Comment by TahaTesser** [comment]
Hi @heibor 
can you please provide your `flutter doctor -v` and `flutter run --verbose`? 
Also, to better address the issue, would be helpful if you could post a minimal code sample to reproduce the problem
Thank you

**Comment by heibor** [comment]
@TahaTesser Thank you! When I open `File` menu and select `Invalidate Caches / Restart` in Android Studio, the problem is solved.

**Comment by VladyslavBondarenko** [comment]
@heibor 
I'm glad that it's solved, closing

**Comment by efengx** [comment]
same question for China.

```bash
% flutter doctor -v
Waiting for another flutter command to release the startup lock...
[✓] Flutter (Channel stable, v1.12.13+hotfix.9, on Mac OS X 10.15.4 19E287, locale en-CN)
    • Flutter version 1.12.13+hotfix.9 at /Users/ofengx/Desktop/Data/fx-pro/flutter/flutter
    • Framework revision f139b11009 (3 weeks ago), 2020-03-30 13:57:30 -0700
    • Engine revision af51afceb8
    • Dart version 2.7.2

 
[!] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/ofengx/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses

[✓] Xcode - develop for iOS and macOS (Xcode 11.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.4.1, Build version 11E503a
    • CocoaPods version 1.9.1

[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 44.0.2
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)

[!] IntelliJ IDEA Ultimate Edition (version 2018.1.1)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.dev/intellij-setup/#installing-the-plugins

[✓] VS Code (version 1.44.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.9.1

[✓] Connected device (1 available)
    • iPhone • 6ca4ecf9c529c47b9f81da6deeb862959af36e4c • ios • iOS 13.3.1

! Doctor found issues in 2 categories.
```

% flutter run --verbose  error:
```bash
% flutter run --verbose  
...
[   +6 ms] executing: security find-identity -p codesigning -v
[ +138 ms]      0 valid identities found
[   +4 ms] ════════════════════════════════════════════════════════════════════════════════
           No valid code signing certificates were found
           You can connect to your Apple Developer account by signing in with your Apple ID
           in Xcode and create an iOS Development Certificate as well as a Provisioning 
           Profile for your project by:
             1- Open the Flutter project's Xcode target with
                  open ios/Runner.xcworkspace
             2- Select the 'Runner' project in the navigator then the 'Runner' target
                in the project settings
             3- In the 'General' tab, make sure a 'Development Team' is selected. 
                You may need to:
                    - Log in with your Apple ID in Xcode first
                    - Ensure you have a valid unique Bundle ID
                    - Register your device with your Apple Developer Account
                    - Let Xcode automatically provision a profile for your app
             4- Build or run your project again
             5- Trust your newly created Development Certificate on your iOS device
                via Settings > General > Device Management > [your new certificate] > Trust
           
           For more information, please visit:
             https://developer.apple.com/library/content/documentation/IDEs/Conceptual/
             AppDistributionGuide/MaintainingCertificates/MaintainingCertificates.html
           
           Or run on an iOS simulator without code signing
           ════════════════════════════════════════════════════════════════════════════════
[   +8 ms] "flutter run" took 95,442ms.
No development certificates available to code sign app for device deployment

#0      throwToolExit (package:flutter_tools/src/base/common.dart:28:3)
#1      _chooseSigningIdentity (package:flutter_tools/src/ios/code_signing.dart:203:5)
#2      getCodeSigningIdentityDevelopmentTeam (package:flutter_tools/src/ios/code_signing.dart:149:40)
<asynchronous suspension>
#3      buildXcodeProject (package:flutter_tools/src/ios/mac.dart:348:32)
<asynchronous suspension>
#4      IOSDevice.startApp (package:flutter_tools/src/ios/devices.dart:296:50)
<asynchronous suspension>
#5      FlutterDevice.runHot (package:flutter_tools/src/resident_runner.dart:450:54)
<asynchronous suspension>
#6      HotRunner.run (package:flutter_tools/src/run_hot.dart:266:39)
#7      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:504:37)
<asynchronous suspension>
#8      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:615:18)
#9      _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:73:64)
#10     _rootRunUnary (dart:async/zone.dart:1134:38)
#11     _CustomZone.runUnary (dart:async/zone.dart:1031:19)
#12     _FutureListener.handleValue (dart:async/future_impl.dart:139:18)
#13     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:680:45)
#14     Future._propagateToListeners (dart:async/future_impl.dart:709:32)
#15     Future._completeWithValue (dart:async/future_impl.dart:524:5)
#16     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:32:15)
#17     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:290:13)
#18     RunCommand.usageValues (package:flutter_tools/src/commands/run.dart)
#19     _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:73:64)
#20     _rootRunUnary (dart:async/zone.dart:1134:38)
#21     _CustomZone.runUnary (dart:async/zone.dart:1031:19)
#22     _FutureListener.handleValue (dart:async/future_impl.dart:139:18)
#23     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:680:45)
#24     Future._propagateToListeners (dart:async/future_impl.dart:709:32)
#25     Future._completeWithValue (dart:async/future_impl.dart:524:5)
#26     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:32:15)
#27     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:290:13)
#28     IosProject.isSwift (package:flutter_tools/src/project.dart)
#29     _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:73:64)
#30     _rootRunUnary (dart:async/zone.dart:1134:38)
#31     _CustomZone.runUnary (dart:async/zone.dart:1031:19)
#32     _FutureListener.handleValue (dart:async/future_impl.dart:139:18)
#33     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:680:45)
#34     Future._propagateToListeners (dart:async/future_impl.dart:709:32)
#35     Future._completeWithValue (dart:async/future_impl.dart:524:5)
#36     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:32:15)
#37     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:290:13)
#38     IosProject.buildSettings (package:flutter_tools/src/project.dart)
#39     _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:73:64)
#40     _rootRunUnary (dart:async/zone.dart:1134:38)
#41     _CustomZone.runUnary (dart:async/zone.dart:1031:19)
#42     _FutureListener.handleValue (dart:async/future_impl.dart:139:18)
#43     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:680:45)
#44     Future._propagateToListeners (dart:async/future_impl.dart:709:32)
#45     Future._completeWithValue (dart:async/future_impl.dart:524:5)
#46     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:32:15)
#47     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:290:13)
#48     XcodeProjectInterpreter.getBuildSettings (package:flutter_tools/src/ios/xcodeproj.dart)
#49     _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:73:64)
#50     _rootRunUnary (dart:async/zone.dart:1134:38)
#51     _CustomZone.runUnary (dart:async/zone.dart:1031:19)
#52     _FutureListener.handleValue (dart:async/future_impl.dart:139:18)
#53     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:680:45)
#54     Future._propagateToListeners (dart:async/future_impl.dart:709:32)
#55     Future._completeWithValue (dart:async/future_impl.dart:524:5)
#56     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:32:15)
#57     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:290:13)
#58     _DefaultProcessUtils.run (package:flutter_tools/src/base/process.dart)
#59     _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:73:64)
#60     _rootRunUnary (dart:async/zone.dart:1134:38)
#61     _CustomZone.runUnary (dart:async/zone.dart:1031:19)
#62     _FutureListener.handleValue (dart:async/future_impl.dart:139:18)
#63     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:680:45)
#64     Future._propagateToListeners (dart:async/future_impl.dart:709:32)
#65     Future._completeWithValue (dart:async/future_impl.dart:524:5)
#66     Future.wait.<anonymous closure> (dart:async/future.dart:400:22)
#67     _rootRunUnary (dart:async/zone.dart:1134:38)
#68     _CustomZone.runUnary (dart:async/zone.dart:1031:19)
#69     _FutureListener.handleValue (dart:async/future_impl.dart:139:18)
#70     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:680:45)
#71     Future._propagateToListeners (dart:async/future_impl.dart:709:32)
#72     Future._complete (dart:async/future_impl.dart:514:7)
#73     _BufferingStreamSubscription.asFuture.<anonymous closure> (dart:async/stream_impl.dart:206:14)
#74     _rootRun (dart:async/zone.dart:1122:38)
#75     _CustomZone.run (dart:async/zone.dart:1023:19)
#76     _CustomZone.runGuarded (dart:async/zone.dart:925:7)
#77     _BufferingStreamSubscription._sendDone.sendDone (dart:async/stream_impl.dart:391:13)
#78     _BufferingStreamSubscription._sendDone (dart:async/stream_impl.dart:401:15)
#79     _BufferingStreamSubscription._close (dart:async/stream_impl.dart:285:7)
#80     _SinkTransformerStreamSubscription._close (dart:async/stream_transformers.dart:98:11)
#81     _EventSinkWrapper.close (dart:async/stream_transformers.dart:25:11)
#82     _StringAdapterSink.close (dart:convert/string_conversion.dart:251:11)
#83     _Utf8ConversionSink.close (dart:convert/string_conversion.dart:302:20)
#84     _ConverterStreamEventSink.close (dart:convert/chunked_conversion.dart:82:18)
#85     _SinkTransformerStreamSubscription._handleDone (dart:async/stream_transformers.dart:143:24)
#86     _rootRun (dart:async/zone.dart:1122:38)
#87     _CustomZone.run (dart:async/zone.dart:1023:19)
#88     _CustomZone.runGuarded (dart:async/zone.dart:925:7)
#89     _BufferingStreamSubscription._sendDone.sendDone (dart:async/stream_impl.dart:391:13)
#90     _BufferingStreamSubscription._sendDone (dart:async/stream_impl.dart:401:15)
#91     _BufferingStreamSubscription._close (dart:async/stream_impl.dart:285:7)
#92     _SyncStreamControllerDispatch._sendDone (dart:async/stream_controller.dart:774:19)
#93     _StreamController._closeUnchecked (dart:async/stream_controller.dart:631:7)
#94     _StreamController.close (dart:async/stream_controller.dart:624:5)
#95     _Socket._onData (dart:io-patch/socket_patch.dart:1858:21)
#96     _rootRunUnary (dart:async/zone.dart:1138:13)
#97     _CustomZone.runUnary (dart:async/zone.dart:1031:19)
#98     _CustomZone.runUnaryGuarded (dart:async/zone.dart:933:7)
#99     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:338:11)
#100    _BufferingStreamSubscription._add (dart:async/stream_impl.dart:265:7)
#101    _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:766:19)
#102    _StreamController._add (dart:async/stream_controller.dart:642:7)
#103    _StreamController.add (dart:async/stream_controller.dart:588:5)
#104    new _RawSocket.<anonymous closure> (dart:io-patch/socket_patch.dart:1406:35)
#105    _NativeSocket.issueReadEvent.issue (dart:io-patch/socket_patch.dart:912:18)
#106    _microtaskLoop (dart:async/schedule_microtask.dart:43:21)
#107    _startMicrotaskLoop (dart:async/schedule_microtask.dart:52:5)
#108    _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
#109    _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:175:5)
```

**Comment by heibor** [comment]
When I upgrade my flutter to `Flutter 1.17.0`, the error reappears.

But when I downgrade my flutter to `Flutter version 1.15.17`, all things would be OK.

**Comment by TahaTesser** [comment]
Could everyone who still has this problem please file a new issue with the exact descriptions
what happens, logs and the output of 'flutter doctor -v' please.
All system setups can be slightly different so it's always better to open new issues and reference
related issues.
Thank you

**Comment by heibor** [comment]
When I upgraded my flutter to 1.17.0. I executed `flutter doctor -v`, the terminal output:

[✓] Flutter (Channel beta, v1.17.0, on Mac OS X 10.15.4 19E287, locale zh-Hans-CN)
    • Flutter version 1.17.0 at /Users/zhen/app/flutter
    • Framework revision d3ed9ec945 (2 周前), 2020-04-06 14:07:34 -0700
    • Engine revision c9506cb8e9
    • Dart version 2.8.0 (build 2.8.0-dev.18.0 eea9717938)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/zhen/app/android-sdk-macosx
    • Platform android-29, build-tools 28.0.3
    • ANDROID_HOME = /Users/zhen/app/android-sdk-macosx
    • Java binary at: /Users/zhen/Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[!] Xcode - develop for iOS and macOS (Xcode 11.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.4.1, Build version 11E503a
    ✗ CocoaPods installed but not working.
        You appear to have CocoaPods installed but it is not working.
        This can happen if the version of Ruby that CocoaPods was installed with is different from the one being used to invoke it.
        This can usually be fixed by re-installing CocoaPods. For more info, see https://github.com/flutter/flutter/issues/14293.
      To re-install CocoaPods, run:
        sudo gem install cocoapods

[✓] Android Studio (version 3.6)
    • Android Studio at /Users/zhen/Applications/Android Studio.app/Contents
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)

[!] IntelliJ IDEA Community Edition (version 2019.2.2)
    • IntelliJ at /Users/zhen/Applications/IntelliJ IDEA CE.app
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    • Dart plugin version 192.6603.23
    • For information about installing plugins, see
      https://flutter.dev/intellij-setup/#installing-the-plugins

[!] VS Code (version 1.38.1)
    • VS Code at /Users/zhen/Applications/Visual Studio Code.app/Contents
    ✗ Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (1 available)
    • A0001 • 6522b35d • android-arm • Android 9 (API 28)

! Doctor found issues in 3 categories.

Then I create a new flutter project, and execute `flutter run --verbose`, I have upload my log file into the [gist](https://gist.github.com/heibor/8ecd3a93254eb7d7c88c134d41f83d7a).

Under the `flutter 1.17.0-dev.3.1` in beta channel, the `flutter run` command will stop at the gradle error, but when I downgrade to `flutter v1.15.17`, all things will be well.

**Comment by TahaTesser** [comment]
Hi @heibor 
Did you [Configuring Flutter to use a mirror site
](https://flutter.dev/community/china#configuring-flutter-to-use-a-mirror-site) after upgrading?

**Comment by heibor** [comment]
Hi @TahaTesser 
I set the mirror site to be `flutter-io.cn`. My configuration is:

export PUB_HOSTED_URL=https://pub.flutter-io.cn
export FLUTTER_STORAGE_BASE_URL=https://storage.flutter-io.cn

**Comment by shen-lan** [comment]
既然是国人，就不说蹩脚的英语了。
大兄弟，解决了么,    我也是升级到最新版本的时候报的错  。我知道这是被墙的原因 ，但是我已开了代理，亲测浏览器地址栏里可以打开  `https://storage.googleapis.com/download.flutter.io/io/flutter/arm64_v8a_debug/1.0.0-4c8c31f591882b3c668992d2e9da761118899f38/arm64_v8a_debug-1.0.0-4c8c31f591882b3c668992d2e9da761118899f38.jar`
但是 控制台一直报错 

```       
  > Could not GET 'https://storage.googleapis.com/download.flutter.io/io/flutter/armeabi_v7a_debug/1.0.0-4c8c31f591882b3c668992d2e9da761118899f38/armeabi_v7a_debug-1.0.0-4c8c31f591882b3c668992d2e9da761118899f38.jar'.

   > Connection reset
```

**Comment by shen-lan** [comment]
```
$ flutter doctor -v
[√] Flutter (Channel beta, v1.17.0-4.0.pre.2, on Microsoft Windows [Version 10.0.18363.778], locale zh-CN)
    • Flutter version 1.17.0-4.0.pre.2 at D:\flutter
    • Framework revision 6c0bf824a1 (77 minutes ago), 2020-04-27 09:47:40 +0800
    • Engine revision 4c8c31f591
    • Dart version 2.8.0 (build 2.8.0-dev.20.10)

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at C:\Users\zsc\AppData\Local\Android\Sdk
    • Platform android-29, build-tools 29.0.2
    • ANDROID_HOME = C:\Users\zsc\AppData\Local\Android\Sdk
    • Java binary at: D:\androidStudio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)
    • All Android licenses accepted.

[√] Android Studio (version 3.5)
    • Android Studio at D:\androidStudio
    • Flutter plugin version 41.1.2
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)

[!] Connected device
    ! No devices available

! Doctor found issues in 1 category.

```

**Comment by heibor** [comment]
@shen-lan I don't think this is caused by the network. If it is a network problem, all versions shouldn't be passed!

**Comment by shen-lan** [comment]
@heibor thanks.  I didn't do anything. It's works properly just now.
