### ISSUE TITLE
[animations] OpenContainer should close to the correct closed element

### ISSUE THREAD

**Issue by kuhnroyal** [flutter/flutter#54980]
@goderbauer This is a follow-up to https://github.com/flutter/flutter/issues/51397

## Steps to Reproduce

I have created a reproducable sample here: https://github.com/kuhnroyal/opencontainer_test

The issue occurs when the closed element moves in the tree and somehow can not be found anymore when closing the open route.

The sample recreates the effect by using OpenContainer from a simple ListView. The opened detail view can be moved to the top of the list. After closing the detail view the issue occurs.
The issue does not occur with the first item in the list because it is already at the top but it would happen if the item was moved to another index in the list.

**Expected results:** 
OpenContainer should close to the correct closed element.

**Actual results:** 
Closing OpenContainer causes errors because the closed element moved in the tree.
```
The getter 'isInTree' was called on null.
The setter 'placeholderSize=' was called on null.
``` 

<details>
  <summary>Logs</summary>

```
════════ Exception caught by widgets library ═══════════════════════════════════════════════════════
The following NoSuchMethodError was thrown building AnimatedBuilder(animation: AnimationController#ea8d9(◀ 1.000; for _OpenContainerRoute)➩ProxyAnimation, dirty, state: _AnimatedState#55946):
The getter 'isInTree' was called on null.
Receiver: null
Tried calling: isInTree

The relevant error-causing widget was: 
  AnimatedBuilder file:///Users/.../animations-1.0.0+5/lib/src/open_container.dart:653:14
When the exception was thrown, this was the stack: 
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:53:5)
#1      _OpenContainerRoute.buildPage.<anonymous closure> (package:animations/src/open_container.dart:738:63)
#2      AnimatedBuilder.build (package:flutter/src/widgets/transitions.dart:1124:19)
#3      _AnimatedState.build (package:flutter/src/widgets/transitions.dart:177:48)
#4      StatefulElement.build (package:flutter/src/widgets/framework.dart:4619:28)
...
════════════════════════════════════════════════════════════════════════════════════════════════════
════════ Exception caught by animation library ═════════════════════════════════════════════════════
The following NoSuchMethodError was thrown while notifying status listeners for ProxyAnimation:
The setter 'placeholderSize=' was called on null.
Receiver: null
Tried calling: placeholderSize=null

When the exception was thrown, this was the stack: 
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:53:5)
#1      _OpenContainerRoute.didPush.<anonymous closure> (package:animations/src/open_container.dart:545:15)
#2      AnimationLocalStatusListenersMixin.notifyStatusListeners (package:flutter/src/animation/listener_helpers.dart:198:19)
#3      AnimationLocalStatusListenersMixin.notifyStatusListeners (package:flutter/src/animation/listener_helpers.dart:198:19)
#4      AnimationController._checkStatusChanged (package:flutter/src/animation/animation_controller.dart:777:7)
...
The ProxyAnimation notifying status listeners was: AnimationController#ea8d9(⏮ 0.000; paused; for _OpenContainerRoute)➩ProxyAnimation
════════════════════════════════════════════════════════════════════════════════════════════════════
```

```
[✓] Flutter (Channel beta, v1.17.0, on Mac OS X 10.15.4 19E287, locale de-DE)
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[!] Xcode - develop for iOS and macOS (Xcode 11.4)
    ✗ CocoaPods installed but not working.
        You appear to have CocoaPods installed but it is not working.
        This can happen if the version of Ruby that CocoaPods was installed with is different from the one being used to invoke it.
        This can usually be fixed by re-installing CocoaPods. For more info, see https://github.com/flutter/flutter/issues/14293.
      To re-install CocoaPods, run:
        sudo gem install cocoapods
[!] Android Studio (version 3.6)
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
[✓] IntelliJ IDEA Ultimate Edition (version 2020.1)
[✓] VS Code (version 1.44.1)
[✓] Connected device (2 available)

! Doctor found issues in 2 categories.
```

</details>

**Comment by goderbauer** [comment]
This is going to be fixed by https://github.com/flutter/packages/pull/126.

**Comment by kuhnroyal** [comment]
Nice! Can you comment this in the old issue so people can find it, this probably solves a lot of the problems there.

**Comment by kuhnroyal** [comment]
The linked PR fixes the exception but doesn't produce the expected result. When the order in the source closed changes, the OpenContainer closes to the wrong element.

**Comment by TahaTesser** [comment]
@kuhnroyal 
Could you please file a new issue with the exact description of what happens, logs, and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.


Closing this issue as it was about the exception, which is now merged. If you disagree, please write in the comments and I will reopen it.
Thank you
