### ISSUE TITLE
Dismissible Widget confirm dismiss error if animation starts after the child has been scrolled

### ISSUE THREAD

**Issue by EdwynZN** [flutter/flutter#54990]
## Steps to Reproduce

I have a list of widgets inside a CustomScroll, each widget is wrapped in a Dismissible widget and when someone dismiss the widget the confirmDismiss fires and a snackbar with an undo button is showed (like Keep Note app), Now if you scroll away from the widget and then click on undo an error is shown that the ticker animation has been disposed and is null, which makes sense the widget isn't there anymore, and if you don't push the undo button and let the snackbar dissapear it means the widget should start to resize (confirmDismiss returns true) and an error telling you the widget is not mounted. Shouldn't the dismissed widget check if it's mounted or not before starting a resize or _modecontroller.reverse animation? In that way it could fire the onDismissed callback without starting any animation. 

The problem is there is no proper way to fire the onDismiss (so I can delete the object from the list) without starting the animation.

```
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'dart:async';

void main() => runApp(
    MaterialApp(
        home: Scaffold(
          body: CustomScrollView(
            cacheExtent: 50,
            slivers: <Widget>[
              Drag()
            ],
          ),
        )
    )
);

class Drag extends StatefulWidget {
  @override
  _DragState createState() => _DragState();
}

class _DragState extends State<Drag>{
  List<String> list = List<String>.from(
      'Lorem ipsum dolor sit '
          'amet, consectetur adipiscing elit, s'
          'ed do eiusmod tempor'.split('')
  );

  @override
  Widget build(BuildContext context) {
    return SliverList(
        delegate: SliverChildBuilderDelegate(
              (BuildContext context, int index){
            return Dismissible(
              key: Key('$index${list[index]}'),
              background: Container(color: Colors.red,),
              confirmDismiss: (_) {
                Completer<bool> completer = Completer();
                final scaffold = Scaffold.of(context);
                scaffold.showSnackBar(
                    SnackBar(content: Text('Task dismissed'),
                      behavior: SnackBarBehavior.floating,
                      onVisible: () => Future.delayed(
                          const Duration(milliseconds: 4000), () {
                        if(completer.isCompleted) return;
                        completer.complete(true);
                      }
                      ),
                      action: SnackBarAction(
                          label: 'undo',
                          onPressed: () => completer.complete(false)
                      ),
                    )
                );
                return completer.future;
              },
              onDismissed: (_) => setState(() => list.removeAt(index)),
              child: Container(
                height: 100,
                width: double.infinity,
                color: index % 2 == 0 ? Colors.blue : Colors.green,
                child: Center(
                  child: Text(list[index], style: TextStyle(fontSize: 24),),
                ),
              ),
            );
          },
          childCount: list.isEmpty ? 0 : list.length,
        )
    );
  }
}

```
<details>
  <summary>Logs</summary>

```
 [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: 'package:flutter/src/animation/animation_controller.dart': Failed assertion: line 484 pos 7: '_ticker != null': AnimationController.reverse() called
after AnimationController.dispose()
[   +2 ms] E/flutter ( 6276): AnimationController methods should not be used after calling dispose.
[   +1 ms] E/flutter ( 6276): #0      _AssertionError._doThrowNew (dart:core-patch/errors_patch.dart:42:39)
[   +1 ms] E/flutter ( 6276): #1      _AssertionError._throwNew (dart:core-patch/errors_patch.dart:38:5)
[        ] E/flutter ( 6276): #2      AnimationController.reverse (package:flutter/src/animation/animation_controller.dart:484:7)
[        ] E/flutter ( 6276): #3      _DismissibleState._handleDismissStatusChanged (package:flutter/src/widgets/dismissible.dart:449:25)
[        ] E/flutter ( 6276): <asynchronous suspension>
[        ] E/flutter ( 6276): #4      AnimationLocalStatusListenersMixin.notifyStatusListeners (package:flutter/src/animation/listener_helpers.dart:193:19)
[        ] E/flutter ( 6276): #5      AnimationController._checkStatusChanged (package:flutter/src/animation/animation_controller.dart:773:7)
[        ] E/flutter ( 6276): #6      AnimationController._tick (package:flutter/src/animation/animation_controller.dart:789:5)
[        ] E/flutter ( 6276): #7      Ticker._tick (package:flutter/src/scheduler/ticker.dart:237:5)
[        ] E/flutter ( 6276): #8      SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1102:15)
[        ] E/flutter ( 6276): #9      SchedulerBinding.handleBeginFrame.<anonymous closure> (package:flutter/src/scheduler/binding.dart:1017:11)
[        ] E/flutter ( 6276): #10     _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:379:8)
[        ] E/flutter ( 6276): #11     SchedulerBinding.handleBeginFrame (package:flutter/src/scheduler/binding.dart:1015:17)
[        ] E/flutter ( 6276): #12     SchedulerBinding._handleBeginFrame (package:flutter/src/scheduler/binding.dart:949:5)
[        ] E/flutter ( 6276): #13     _rootRunUnary (dart:async/zone.dart:1138:13)
[        ] E/flutter ( 6276): #14     _CustomZone.runUnary (dart:async/zone.dart:1031:19)
[        ] E/flutter ( 6276): #15     _CustomZone.runUnaryGuarded (dart:async/zone.dart:933:7)
[        ] E/flutter ( 6276): #16     _invoke1 (dart:ui/hooks.dart:273:10)
[        ] E/flutter ( 6276): #17     _beginFrame (dart:ui/hooks.dart:200:3)
[        ] E/flutter ( 6276): 

```

```
[√] Flutter (Channel stable, v1.12.13+hotfix.9, on Microsoft Windows [VersiÃ³n 10.0.18363.720], locale es-MX)
    • Flutter version 1.12.13+hotfix.9 at E:\Programs\flutter
    • Framework revision f139b11009 (2 weeks ago), 2020-03-30 13:57:30 -0700
    • Engine revision af51afceb8
    • Dart version 2.7.2


[√] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at C:\Users\dartz\AppData\Local\Android\Sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.3
    • ANDROID_HOME = C:\Users\dartz\AppData\Local\Android\Sdk
    • Java binary at: E:\Programs\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)
    • All Android licenses accepted.

[√] Android Studio (version 3.6)
    • Android Studio at E:\Programs\Android\Android Studio
    • Flutter plugin version 44.0.2
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)

[√] Connected device (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 10 (API 29) (emulator)

• No issues found!

```

</details>

**Comment by VladyslavBondarenko** [comment]
Also I see this exception, when you dismissed and scrolled (without pressing undo).
It tries to delete, but element is already unmounted after scrolling

```
I/flutter (24587): ══╡ EXCEPTION CAUGHT BY ANIMATION LIBRARY ╞═════════════════════════════════════════════════════════
I/flutter (24587): The following NoSuchMethodError was thrown while notifying listeners for AnimationController:
I/flutter (24587): The method 'dependOnInheritedWidgetOfExactType' was called on null.
I/flutter (24587): Receiver: null
I/flutter (24587): Tried calling: dependOnInheritedWidgetOfExactType<Directionality>()
I/flutter (24587): 
I/flutter (24587): When the exception was thrown, this was the stack:
I/flutter (24587): #0      Object.noSuchMethod (dart:core-patch/object_patch.dart:53:5)
I/flutter (24587): #1      Directionality.of (package:flutter/src/widgets/basic.dart:110:43)
I/flutter (24587): #2      _DismissibleState._extentToDirection (package:flutter/src/widgets/dismissible.dart:272:30)
I/flutter (24587): #3      _DismissibleState._dismissDirection (package:flutter/src/widgets/dismissible.dart:284:45)
I/flutter (24587): #4      _DismissibleState._handleResizeProgressChanged (package:flutter/src/widgets/dismissible.dart:502:44)
I/flutter (24587): #5      AnimationLocalListenersMixin.notifyListeners (package:flutter/src/animation/listener_helpers.dart:135:19)
I/flutter (24587): #6      AnimationController._tick (package:flutter/src/animation/animation_controller.dart:792:5)
I/flutter (24587): #7      Ticker._tick (package:flutter/src/scheduler/ticker.dart:237:12)
I/flutter (24587): #8      SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1074:15)
I/flutter (24587): #9      SchedulerBinding.handleBeginFrame.<anonymous closure> (package:flutter/src/scheduler/binding.dart:989:11)
I/flutter (24587): #10     _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:379:8)
I/flutter (24587): #11     SchedulerBinding.handleBeginFrame (package:flutter/src/scheduler/binding.dart:987:17)
I/flutter (24587): #12     SchedulerBinding._handleBeginFrame (package:flutter/src/scheduler/binding.dart:921:5)
I/flutter (24587): #16     _invoke1 (dart:ui/hooks.dart:275:10)
I/flutter (24587): #17     _beginFrame (dart:ui/hooks.dart:202:3)
I/flutter (24587): (elided 3 frames from dart:async)
I/flutter (24587): 
I/flutter (24587): The AnimationController notifying listeners was:
I/flutter (24587):   AnimationController#56b89(⏭ 1.000; paused)
```

**Comment by EdwynZN** [comment]
Yeah it's waiting the future to complete after the Snackbar (confirmDismiss) to know if it would animate back or resize and dismiss

**Comment by TahaTesser** [comment]
<details> 
<summary>logs</summary> 

```dart
Restarted application in 416ms.
[VERBOSE-2:ui_dart_state.cc(184)] Unhandled Exception: 'package:flutter/src/widgets/dismissible.dart': Failed assertion: line 515 pos 12: '_resizeController == null': is not true.
[38;5;244m#0      _AssertionError._doThrowNew (dart:core-patch/errors_patch.dart:46:39)[39;49m
[38;5;244m#1      _AssertionError._throwNew (dart:core-patch/errors_patch.dart:36:5)[39;49m
[38;5;244m#2      _DismissibleState._startResizeAnimation[39;49m
 package:flutter/…/widgets/dismissible.dart
[38;5;244m#3      _DismissibleState._handleDismissStatusChanged[39;49m
 package:flutter/…/widgets/dismissible.dart
[38;5;244m<asynchronous suspension>[39;49m
[VERBOSE-2:ui_dart_state.cc(184)] Unhandled Exception: 'package:flutter/src/widgets/dismissible.dart': Failed assertion: line 515 pos 12: '_resizeController == null': is not true.
[38;5;244m#0      _AssertionError._doThrowNew (dart:core-patch/errors_patch.dart:46:39)[39;49m
[38;5;244m#1      _AssertionError._throwNew (dart:core-patch/errors_patch.dart:36:5)[39;49m
[38;5;244m#2      _DismissibleState._startResizeAnimation[39;49m
 package:flutter/…/widgets/dismissible.dart
[38;5;244m#3      _DismissibleState._handleDismissStatusChanged[39;49m
 package:flutter/…/widgets/dismissible.dart
[38;5;244m<asynchronous suspension>[39;49m

[38;5;248m════════ Exception caught by animation library ═════════════════════════════════[39;49m
[38;5;244mThe following assertion was thrown while notifying status listeners for AnimationController:[39;49m
This widget has been unmounted, so the State no longer has a context (and should be considered defunct).

[38;5;244mConsider canceling any active work during "dispose" or using the "mounted" getter to determine if the State is still active.[39;49m
[38;5;244mWhen the exception was thrown, this was the stack[39;49m
[38;5;244m#0      State.context.<anonymous closure>[39;49m
 package:flutter/…/widgets/framework.dart
[38;5;244m#1      State.context[39;49m
 package:flutter/…/widgets/framework.dart
[38;5;244m#2      AutomaticKeepAliveClientMixin._ensureKeepAlive[39;49m
 package:flutter/…/widgets/automatic_keep_alive.dart
[38;5;244m#3      AutomaticKeepAliveClientMixin.updateKeepAlive[39;49m
 package:flutter/…/widgets/automatic_keep_alive.dart
[38;5;244m#4      _DismissibleState._startResizeAnimation.<anonymous closure>[39;49m
 package:flutter/…/widgets/dismissible.dart
[38;5;244m...[39;49m
[38;5;244mThe AnimationController notifying status listeners was: AnimationController#38c97(▶ 0.000)[39;49m
[38;5;248m════════════════════════════════════════════════════════════════════════════════[39;49m
[VERBOSE-2:ui_dart_state.cc(184)] Unhandled Exception: setState() called after dispose(): _DismissibleState#5191d(lifecycle state: defunct, not mounted, tickers: tracking 1 ticker)
This error happens if you call setState() on a State object for a widget that no longer appears in the widget tree (e.g., whose parent widget no longer includes the widget in its build). This error can occur when code calls setState() from a timer or an animation callback.
The preferred solution is to cancel the timer or stop listening to the animation in the dispose() callback. Another solution is to check the "mounted" property of this object before calling setState() to ensure the object is still in the tree.
This error might indicate a memory leak if setState() is being called because another object is retaining a reference to this State object after it has been removed from the tree. To avoid memory leaks, consider breaking the reference to this object during dispose().
#0      State.setState.<anonymous closure> (pack<…>

[38;5;248m════════ Exception caught by animation library ═════════════════════════════════[39;49m
This widget has been unmounted, so the State no longer has a context (and should be considered defunct).
[38;5;248m════════════════════════════════════════════════════════════════════════════════[39;49m

Launching lib/main.dart on iPhone 12 in debug mode...
 lib/main.dart
Xcode build done.                                           13.8s
Connecting to VM Service at ws://127.0.0.1:58836/ANzXsQi9TQM=/ws
[VERBOSE-2:ui_dart_state.cc(177)] Unhandled Exception: setState() called after dispose(): _DismissibleState#56b35(lifecycle state: defunct, not mounted, tickers: tracking 1 ticker)
This error happens if you call setState() on a State object for a widget that no longer appears in the widget tree (e.g., whose parent widget no longer includes the widget in its build). This error can occur when code calls setState() from a timer or an animation callback.
The preferred solution is to cancel the timer or stop listening to the animation in the dispose() callback. Another solution is to check the "mounted" property of this object before calling setState() to ensure the object is still in the tree.
This error might indicate a memory leak if setState() is being called because another object is retaining a reference to this State object after it has been removed from the tree. To avoid memory leaks, consider breaking the reference to this object during dispose().
#0      State.setState.<anonymous closure> (pack<…>

[38;5;248m════════ Exception caught by animation library ═════════════════════════════════[39;49m
[38;5;244mThe following NoSuchMethodError was thrown while notifying listeners for AnimationController:[39;49m
The method 'dependOnInheritedWidgetOfExactType' was called on null.
Receiver: null
Tried calling: dependOnInheritedWidgetOfExactType<Directionality>()

[38;5;244mWhen the exception was thrown, this was the stack[39;49m
[38;5;244m#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:51:5)[39;49m
[38;5;244m#1      Directionality.of[39;49m
 package:flutter/…/widgets/basic.dart
[38;5;244m#2      _DismissibleState._extentToDirection[39;49m
 package:flutter/…/widgets/dismissible.dart
[38;5;244m#3      _DismissibleState._dismissDirection[39;49m
 package:flutter/…/widgets/dismissible.dart
[38;5;244m#4      _DismissibleState._handleResizeProgressChanged[39;49m
 package:flutter/…/widgets/dismissible.dart
[38;5;244m...[39;49m
[38;5;244mThe AnimationController notifying listeners was: AnimationController#0b972(⏭ 1.000; paused)[39;49m
[38;5;248m════════════════════════════════════════════════════════════════════════════════[39;49m


``` 

</details>

<details>
<summary>flutter doctor -v</summary>

```bash
[✓] Flutter (Channel stable, 1.22.5, on macOS 11.1 20C69 darwin-x64, locale en-GB)
    • Flutter version 1.22.5 at /Users/tahatesser/Code/flutter_stable
    • Framework revision 7891006299 (3 weeks ago), 2020-12-10 11:54:40 -0800
    • Engine revision ae90085a84
    • Dart version 2.10.4

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Volumes/Extreme/sdk
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = /Volumes/Extreme/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.3)
    • Xcode at /Volumes/Extreme/Xcode.app/Contents/Developer
    • Xcode 12.3, Build version 12C33
    • CocoaPods version 1.10.0

[!] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.52.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.18.0

[✓] Connected device (3 available)
    • RMX2001 (mobile)     • EUYTFEUSQSRGDA6D                     • android-arm64 • Android 10 (API 29)
    • Taha’s iPad (mobile) • 00008020-000255113EE8402E            • ios           • iOS 14.3
    • iPhone 12 (mobile)   • 12D8FF8E-2815-436E-9951-B8A6A42E4ACF • ios           • com.apple.CoreSimulator.SimRuntime.iOS-14-3 (simulator)

! Doctor found issues in 1 category.
```
```bash
[✓] Flutter (Channel master, 1.26.0-2.0.pre.145, on macOS 11.1 20C69 darwin-x64, locale en-GB)
    • Flutter version 1.26.0-2.0.pre.145 at /Users/tahatesser/Code/flutter_master
    • Framework revision 38fe7e2b1c (12 hours ago), 2020-12-28 21:39:03 -0500
    • Engine revision 892034dc6a
    • Dart version 2.12.0 (build 2.12.0-179.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Volumes/Extreme/sdk
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = /Volumes/Extreme/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.3)
    • Xcode at /Volumes/Extreme/Xcode.app/Contents/Developer
    • Xcode 12.3, Build version 12C33
    • CocoaPods version 1.10.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.52.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.18.0

[✓] Connected device (5 available)
    • RMX2001 (mobile)     • EUYTFEUSQSRGDA6D                     • android-arm64  • Android 10 (API 29)
    • Taha’s iPad (mobile) • 00008020-000255113EE8402E            • ios            • iOS 14.3
    • iPhone 12 (mobile)   • 12D8FF8E-2815-436E-9951-B8A6A42E4ACF • ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-3 (simulator)
    • macOS (desktop)      • macos                                • darwin-x64     • macOS 11.1 20C69 darwin-x64
    • Chrome (web)         • chrome                               • web-javascript • Google Chrome 87.0.4280.88

• No issues found!
```

</details>
