### ISSUE TITLE
Multiple widgets used the same GlobalKey

### ISSUE THREAD

**Issue by enricobenedos** [flutter/flutter#55098]
## Steps to Reproduce
I'm receiving a lot of exception related to same global key usage with the below code. I've already opened an [issue](https://stackoverflow.com/questions/61045756/avoid-setpreferredorientations-multiple-key-exceptions) on StackOverflow but I think is not my code problem.

```dart
class MyHomePage extends StatefulWidget {
  MyHomePage({Key key, this.title}) : super(key: key);

  final String title;

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: ListView.builder(
          itemCount: 100,
          itemBuilder: (context, index) {
            return CupertinoContextMenu(
              child: Container(
                margin: const EdgeInsets.all(10),
                color: Colors.yellow,
                height: 30,
                width: 200,
              ),
              actions: <Widget>[
                CupertinoContextMenuAction(
                  child: const Text('Action one'),
                  onPressed: () async => await Navigator.of(context)
                      .push(MaterialPageRoute(builder: (context) => PageOne())),
                ),
              ],
            );
          }),
    );
  }
}
```
```dart
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';

class PageOne extends StatefulWidget {
  @override
  _PageOneState createState() => _PageOneState();
}

class _PageOneState extends State<PageOne> {
  @override
  void initState() {
    super.initState();

    SystemChrome.setPreferredOrientations(
        [DeviceOrientation.landscapeRight, DeviceOrientation.landscapeLeft]);
  }

  @override
  void dispose() {
    SystemChrome.setPreferredOrientations(DeviceOrientation.values);
    super.dispose();
}

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: Text('Page One')),
    );
  }
}
```

```terminal
════════ Exception caught by widgets library ═══════════════════════════════════
The following assertion was thrown while finalizing the widget tree:
Multiple widgets used the same GlobalKey.

The key [GlobalKey#a3ef0] was used by multiple widgets. The parents of those widgets were:
- AnimatedBuilder(animation: AnimationController#c2d69(⏭ 1.000; paused), dependencies: [MediaQuery])
- AnimatedBuilder(animation: AnimationController#c2d69(⏭ 1.000; paused), dependencies: [MediaQuery], state: _AnimatedState#5b6e5)
A GlobalKey can only be specified on one widget at a time in the widget tree.
When the exception was thrown, this was the stack
#0      GlobalKey._debugVerifyGlobalKeyReservation.<anonymous closure>.<anonymous closure>.<anonymous closure> 
package:flutter/…/widgets/framework.dart:246
#1      _LinkedHashMapMixin.forEach  (dart:collection-patch/compact_hash.dart:379:8)
#2      GlobalKey._debugVerifyGlobalKeyReservation.<anonymous closure>.<anonymous closure> 
package:flutter/…/widgets/framework.dart:193
#3      _LinkedHashMapMixin.forEach  (dart:collection-patch/compact_hash.dart:379:8)
#4      GlobalKey._debugVerifyGlobalKeyReservation.<anonymous closure> 
package:flutter/…/widgets/framework.dart:189
...
════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by widgets library ═══════════════════════════════════
Multiple widgets used the same GlobalKey.
════════════════════════════════════════════════════════════════════════════════
Launching lib/main.dart on iPhone 11 Pro in debug mode...

════════ Exception caught by widgets library ═══════════════════════════════════
Multiple widgets used the same GlobalKey.
════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by widgets library ═══════════════════════════════════
Multiple widgets used the same GlobalKey.
════════════════════════════════════════════════════════════════════════════════
```

```terminal
[✓] Flutter (Channel dev, v1.18.0-dev.5.0, on Mac OS X 10.15.4 19E287, locale en-IT)
    • Flutter version 1.18.0-dev.5.0 at /Users/enricobenedos/SDKs/flutter
    • Framework revision 7f56b53de4 (6 days ago), 2020-04-12 12:00:01 -0400
    • Engine revision beb8a7ec48
    • Dart version 2.8.0 (build 2.8.0-dev.20.0 89b0f67261)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/enricobenedos/Library/Android/sdk
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.4)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.4, Build version 11E146
    • CocoaPods version 1.9.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)

[✓] VS Code (version 1.44.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.9.1

[✓] Connected device (3 available)
    • iPad (7th generation) • 2A43CEEC-D69D-48EC-88C8-BF3D3CCA63D7 • ios            •
      com.apple.CoreSimulator.SimRuntime.iOS-13-4 (simulator)
    • Chrome                • chrome                               • web-javascript •
      Google Chrome 80.0.3987.163
    • Web Server            • web-server                           • web-javascript •
      Flutter Tools
```

**Comment by jonahwilliams** [comment]
Questions like these are better suited for Q&A sites like [StackOverflow](https://stackoverflow.com/questions/tagged/flutter) or on one of the flutter community sites at https://flutter.dev/community

**Comment by enricobenedos** [comment]
Hey @jonahwilliams, thank you for your advice. As you can read I've already opened an issue on StackOverflow and I've already used Slack. But I think it is not a my code problem but a `CupertinoContextMenu` widget problem. I tried to read documentation about it and keys. The generated exception for me is no sense. I've also tried to manually generate keys but not works. If for example I execute the same navigation code on a FAB or another widget there are no problems.
