### ISSUE TITLE
Error connecting to the service protocol: failed to connect to http://127.0.0.1:1024/iNBAzpc3-sI=/

### ISSUE THREAD

**Issue by baiyidjp** [flutter/flutter#55136]
I am in China and My device is iPhoneX, Flutter version is v1.12.13+hotfix.9.

When I run - release in my device, It works well

When I run - debug in my device , It have this error

> Launching lib/main.dart on iPhoneX in debug mode...    

> Automatically signing iOS for device deployment using specified development team in Xcode project: 2YLH4LPXAQ

> Running Xcode build...

> Xcode build done.                                           45.3s

> Installing and launching...

> Error connecting to the service protocol: failed to connect to http://127.0.0.1:1024/iNBAzpc3-sI=/

Can anyone tell me how to resolved this question? 

Thanks

**Comment by iapicca** [comment]
Hi @baiyidjp 
can you please provide your `flutter doctor -v` 
and your `flutter run --verbose` 
Thank you

**Comment by baiyidjp** [comment]
@iapicca First of all, thank you. When I use another Mac Pro in the company, it works normally again. When I get home from work, I will use my own computer to retest

**Comment by ristiisa** [comment]
I'm having similar issue with my iPhone X. Here is the log and some system information:
```
[  +44 ms] Application launched on the device. Waiting for observatory port.
[   +2 ms] Checking for advertised Dart observatories...
[+5019 ms] Checking for available port on ee.randomforest.trackr._dartobservatory._tcp.local
[        ] Checking for authentication code for ee.randomforest.trackr._dartobservatory._tcp.local
[   +1 ms] Attempting to forward device port 52004 to host port 1024
[        ] executing: /Users/silver/flutter/bin/cache/artifacts/usbmuxd/iproxy 1024 52004 00008030-000269E13EBA802E
[  +17 ms] Attempting to forward device port 52004 to host port 1025
[        ] executing: /Users/silver/flutter/bin/cache/artifacts/usbmuxd/iproxy 1025 52004 00008030-000269E13EBA802E
[  +15 ms] Attempting to forward device port 52004 to host port 1026
[        ] executing: /Users/silver/flutter/bin/cache/artifacts/usbmuxd/iproxy 1026 52004 00008030-000269E13EBA802E
[  +15 ms] Attempting to forward device port 52004 to host port 1027
[        ] executing: /Users/silver/flutter/bin/cache/artifacts/usbmuxd/iproxy 1027 52004 00008030-000269E13EBA802E
[  +15 ms] Attempting to forward device port 52004 to host port 1028
[        ] executing: /Users/silver/flutter/bin/cache/artifacts/usbmuxd/iproxy 1028 52004 00008030-000269E13EBA802E
[  +15 ms] Attempting to forward device port 52004 to host port 1029
[        ] executing: /Users/silver/flutter/bin/cache/artifacts/usbmuxd/iproxy 1029 52004 00008030-000269E13EBA802E
[  +15 ms] Attempting to forward device port 52004 to host port 1030
[        ] executing: /Users/silver/flutter/bin/cache/artifacts/usbmuxd/iproxy 1030 52004 00008030-000269E13EBA802E
[  +15 ms] Attempting to forward device port 52004 to host port 1031
[        ] executing: /Users/silver/flutter/bin/cache/artifacts/usbmuxd/iproxy 1031 52004 00008030-000269E13EBA802E
[  +14 ms] Attempting to forward device port 52004 to host port 1032
[        ] executing: /Users/silver/flutter/bin/cache/artifacts/usbmuxd/iproxy 1032 52004 00008030-000269E13EBA802E
[  +15 ms] Attempting to forward device port 52004 to host port 1033
[        ] executing: /Users/silver/flutter/bin/cache/artifacts/usbmuxd/iproxy 1033 52004 00008030-000269E13EBA802E
[+1010 ms] Forwarded port ForwardedPort HOST:1033 to DEVICE:52004
[   +2 ms] Installing and launching... (completed in 21.6s)
[   +4 ms] Connecting to service protocol: http://127.0.0.1:1033/iPRhRYFPRfw=/
[  +11 ms] Fail to connect to service protocol: http://127.0.0.1:1033/iPRhRYFPRfw=/: HttpException: Connection closed before full header was received, uri = http://127.0.0.1:1033/iPRhRYFPRfw=/ws
[        ] Error connecting to the service protocol: failed to connect to http://127.0.0.1:1033/iPRhRYFPRfw=/
[   +1 ms] "flutter run" took 51,964ms.

#0      throwToolExit (package:flutter_tools/src/base/common.dart:28:3)
#1      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:509:7)
<asynchronous suspension>
#2      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:615:18)
#3      _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:73:64)
#4      _rootRunUnary (dart:async/zone.dart:1134:38)
#5      _CustomZone.runUnary (dart:async/zone.dart:1031:19)
#6      _FutureListener.handleValue (dart:async/future_impl.dart:139:18)
#7      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:680:45)
#8      Future._propagateToListeners (dart:async/future_impl.dart:709:32)
#9      Future._completeWithValue (dart:async/future_impl.dart:524:5)
#10     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:32:15)
#11     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:290:13)
#12     RunCommand.usageValues (package:flutter_tools/src/commands/run.dart)
#13     _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:73:64)
#14     _rootRunUnary (dart:async/zone.dart:1134:38)
#15     _CustomZone.runUnary (dart:async/zone.dart:1031:19)
#16     _FutureListener.handleValue (dart:async/future_impl.dart:139:18)
#17     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:680:45)
#18     Future._propagateToListeners (dart:async/future_impl.dart:709:32)
#19     Future._completeWithValue (dart:async/future_impl.dart:524:5)
#20     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:32:15)
#21     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:290:13)
#22     IosProject.isSwift (package:flutter_tools/src/project.dart)
#23     _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:73:64)
#24     _rootRunUnary (dart:async/zone.dart:1134:38)
#25     _CustomZone.runUnary (dart:async/zone.dart:1031:19)
#26     _FutureListener.handleValue (dart:async/future_impl.dart:139:18)
#27     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:680:45)
#28     Future._propagateToListeners (dart:async/future_impl.dart:709:32)
#29     Future._completeWithValue (dart:async/future_impl.dart:524:5)
#30     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:32:15)
#31     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:290:13)
#32     IosProject.buildSettings (package:flutter_tools/src/project.dart)
#33     _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:73:64)
#34     _rootRunUnary (dart:async/zone.dart:1134:38)
#35     _CustomZone.runUnary (dart:async/zone.dart:1031:19)
#36     _FutureListener.handleValue (dart:async/future_impl.dart:139:18)
#37     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:680:45)
#38     Future._propagateToListeners (dart:async/future_impl.dart:709:32)
#39     Future._completeWithValue (dart:async/future_impl.dart:524:5)
#40     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:32:15)
#41     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:290:13)
#42     XcodeProjectInterpreter.getBuildSettings (package:flutter_tools/src/ios/xcodeproj.dart)
#43     _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:73:64)
#44     _rootRunUnary (dart:async/zone.dart:1134:38)
#45     _CustomZone.runUnary (dart:async/zone.dart:1031:19)
#46     _FutureListener.handleValue (dart:async/future_impl.dart:139:18)
#47     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:680:45)
#48     Future._propagateToListeners (dart:async/future_impl.dart:709:32)
#49     Future._completeWithValue (dart:async/future_impl.dart:524:5)
#50     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:32:15)
#51     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:290:13)
#52     _DefaultProcessUtils.run (package:flutter_tools/src/base/process.dart)
#53     _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:73:64)
#54     _rootRunUnary (dart:async/zone.dart:1134:38)
#55     _CustomZone.runUnary (dart:async/zone.dart:1031:19)
#56     _FutureListener.handleValue (dart:async/future_impl.dart:139:18)
#57     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:680:45)
#58     Future._propagateToListeners (dart:async/future_impl.dart:709:32)
#59     Future._completeWithValue (dart:async/future_impl.dart:524:5)
#60     Future.wait.<anonymous closure> (dart:async/future.dart:400:22)
#61     _rootRunUnary (dart:async/zone.dart:1134:38)
#62     _CustomZone.runUnary (dart:async/zone.dart:1031:19)
#63     _FutureListener.handleValue (dart:async/future_impl.dart:139:18)
#64     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:680:45)
#65     Future._propagateToListeners (dart:async/future_impl.dart:709:32)
#66     Future._complete (dart:async/future_impl.dart:514:7)
#67     _BufferingStreamSubscription.asFuture.<anonymous closure> (dart:async/stream_impl.dart:206:14)
#68     _rootRun (dart:async/zone.dart:1122:38)
#69     _CustomZone.run (dart:async/zone.dart:1023:19)
#70     _CustomZone.runGuarded (dart:async/zone.dart:925:7)
#71     _BufferingStreamSubscription._sendDone.sendDone (dart:async/stream_impl.dart:391:13)
#72     _BufferingStreamSubscription._sendDone (dart:async/stream_impl.dart:401:15)
#73     _BufferingStreamSubscription._close (dart:async/stream_impl.dart:285:7)
#74     _SinkTransformerStreamSubscription._close (dart:async/stream_transformers.dart:98:11)
#75     _EventSinkWrapper.close (dart:async/stream_transformers.dart:25:11)
#76     _StringAdapterSink.close (dart:convert/string_conversion.dart:251:11)
#77     _Utf8ConversionSink.close (dart:convert/string_conversion.dart:302:20)
#78     _ConverterStreamEventSink.close (dart:convert/chunked_conversion.dart:82:18)
#79     _SinkTransformerStreamSubscription._handleDone (dart:async/stream_transformers.dart:143:24)
#80     _rootRun (dart:async/zone.dart:1122:38)
#81     _CustomZone.run (dart:async/zone.dart:1023:19)
#82     _CustomZone.runGuarded (dart:async/zone.dart:925:7)
#83     _BufferingStreamSubscription._sendDone.sendDone (dart:async/stream_impl.dart:391:13)
#84     _BufferingStreamSubscription._sendDone (dart:async/stream_impl.dart:401:15)
#85     _BufferingStreamSubscription._close (dart:async/stream_impl.dart:285:7)
#86     _SyncStreamControllerDispatch._sendDone (dart:async/stream_controller.dart:774:19)
#87     _StreamController._closeUnchecked (dart:async/stream_controller.dart:631:7)
#88     _StreamController.close (dart:async/stream_controller.dart:624:5)
#89     _Socket._onData (dart:io-patch/socket_patch.dart:1858:21)
#90     _rootRunUnary (dart:async/zone.dart:1138:13)
#91     _CustomZone.runUnary (dart:async/zone.dart:1031:19)
#92     _CustomZone.runUnaryGuarded (dart:async/zone.dart:933:7)
#93     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:338:11)
#94     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:265:7)
#95     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:766:19)
#96     _StreamController._add (dart:async/stream_controller.dart:642:7)
#97     _StreamController.add (dart:async/stream_controller.dart:588:5)
#98     new _RawSocket.<anonymous closure> (dart:io-patch/socket_patch.dart:1406:35)
#99     _NativeSocket.issueReadEvent.issue (dart:io-patch/socket_patch.dart:912:18)
#100    _microtaskLoop (dart:async/schedule_microtask.dart:43:21)
#101    _startMicrotaskLoop (dart:async/schedule_microtask.dart:52:5)
#102    _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
#103    _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:175:5```

[✓] Flutter (Channel stable, v1.12.13+hotfix.9, on Mac OS X 10.15.3 19D76, locale en-EE)
    • Flutter version 1.12.13+hotfix.9 at /Users/silver/flutter
    • Framework revision f139b11009 (3 weeks ago), 2020-03-30 13:57:30 -0700
    • Engine revision af51afceb8
    • Dart version 2.7.2

[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/setup/#android-setup for detailed instructions).
      If the Android SDK has been installed to a custom location, set ANDROID_HOME to that location.
      You may also want to add it to your PATH environment variable.


[✓] Xcode - develop for iOS and macOS (Xcode 11.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.3.1, Build version 11C504
    • CocoaPods version 1.9.1

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/setup/#android-setup for detailed instructions).

[✓] VS Code (version 1.43.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.9.1

[✓] Connected device (1 available)
    • Ingmar’s iPhone • 00008030-000269E13EBA802E • ios • iOS 13.3.1

**Comment by VladyslavBondarenko** [comment]
@baiyidjp 
could you check if you are experiencing this with current dev or beta channel? 
may be related to https://github.com/flutter/flutter/issues/48234#issuecomment-592130971

**Comment by baiyidjp** [comment]
@VladyslavBondarenko @iapicca  I'm so sorry for this issue, I don't know why my device is ok to run my project. Yesterday it is have some error, But now it is ok ~
