### ISSUE TITLE
Hot reload gets stuck reloading after const compile-time error

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#5513]
If I have a compile-time error with a const, it looks like my framework/engine/thing gets in a broken state. The next time I hit 'r' I get stuck:

```
E/flutter : [ERROR:../../lib/tonic/logging/dart_error.cc(16)] '/data/user/0/io.flutter.gallery/cache/flutter_gallerykeovah/lib/gallery/home.dart': error: line 145 pos 62: expression is not a valid compile-time constant
E/flutter :             style: const TextStyle(fontSize:16.0, fontStyle: FontStyle.bold), children: [
E/flutter :                                                              ^
I/flutter : ══╡ EXCEPTION CAUGHT BY SCHEDULER LIBRARY ╞═════════════════════════════════════════════════════════
I/flutter : The following assertion was thrown during a scheduler callback:
I/flutter : 'package:flutter/src/widgets/binding.dart': Failed assertion: line 206 pos 12:
I/flutter : '!_buildingDirtyElements' is not true.
I/flutter : When the exception was thrown, this was the stack:
I/flutter : #2      BindingBase&SchedulerBinding&GestureBinding&ServicesBinding&RendererBinding&WidgetsBinding.beginFrame (package:flutter/src/widgets/binding.dart:206:12)
I/flutter : #3      BindingBase&SchedulerBinding&GestureBinding&ServicesBinding&RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:146:5)
I/flutter : #4      BindingBase&SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:535:15)
I/flutter : #5      BindingBase&SchedulerBinding.handleBeginFrame (package:flutter/src/scheduler/binding.dart:495:7)
I/flutter : #6      _beginFrame (file:///b/build/slave/Linux_Engine/build/src/flutter/lib/ui/hooks.dart:48)
I/flutter : (elided 2 frames from class _AssertionError)
I/flutter : ════════════════════════════════════════════════════════════════════════════════════════════════════
r
Syncing files to device...                               
Scanning project files...                            0.0s
Scanning package files...                            0.1s
Scanning asset files...                              0.0s
Scanning for deleted files...                        0.0s
No files to remove.
Updating files...                                    0.0s
Performing hot reload...                             0.4s
Reloaded 3 of 426 libraries.
Reassembling application...                             |
```

If I hit 'R' then my app resets. I didn't need to exit the console.

**Comment by johnmccutchan** [comment]
I believe this is fixed.
