### ISSUE TITLE
[tool_crash] Invalid argument(s): A directory corresponding to fileSystemPath "/home/cerdik/GoogleSDK/FlutterSDK/.pub-cache/hosted/pub.dartlang.org/devtools-0.1.15/build" could not be found

### ISSUE THREAD

**Issue by cerdikstdcreator** [flutter/flutter#55149]
## Command
```console
flutter run -d chrome
```

## Logs
`ArgumentError: Invalid argument(s): A directory corresponding to fileSystemPath "/home/cerdik/GoogleSDK/FlutterSDK/.pub-cache/hosted/pub.dartlang.org/devtools-0.1.15/build" could not be found`

```bash
#0      createStaticHandler (package:shelf_static/src/static_handler.dart:50:5)
#1      defaultHandler (package:devtools_server/src/handlers.dart:32:24)
<asynchronous suspension>
#2      serveDevTools (package:devtools_server/src/server.dart:144:21)
#3      DevTools.start (package:dwds/src/servers/devtools.dart:27:15)
#4      Dwds.start (package:dwds/dwds.dart:111:33)
#5      WebAssetServer.start (package:flutter_tools/src/build_runner/devfs_web.dart:85:36)
<asynchronous suspension>
#6      WebDevFS.create (package:flutter_tools/src/build_runner/devfs_web.dart:460:43)
#7      _ResidentWebRunner.run.<anonymous closure> (package:flutter_tools/src/build_runner/resident_web_runner.dart:421:44)
#8      asyncGuard.<anonymous closure> (package:flutter_tools/src/base/async_guard.dart:111:32)
#9      _rootRun (dart:async/zone.dart:1126:13)
#10     _CustomZone.run (dart:async/zone.dart:1023:19)
#11     _runZoned (dart:async/zone.dart:1518:10)
#12     runZoned (dart:async/zone.dart:1502:12)
#13     asyncGuard (package:flutter_tools/src/base/async_guard.dart:109:3)
#14     _ResidentWebRunner.run (package:flutter_tools/src/build_runner/resident_web_runner.dart:411:20)
<asynchronous suspension>
#15     RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:563:37)
<asynchronous suspension>
```

```console
[✓] Flutter (Channel beta, v1.15.17, on Linux, locale en_US.UTF-8)
    • Flutter version 1.15.17 at /home/cerdik/.dev.tools/GoogleSDK/FlutterSDK
    • Framework revision 2294d75bfa (6 weeks ago), 2020-03-07 00:28:38 +0900
    • Engine revision 5aff311948
    • Dart version 2.8.0 (build 2.8.0-dev.12.0 9983424a3c)

[!] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /home/cerdik/.dev.tools/GoogleSDK/AndroidSDK
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /usr/bin/java
    • Java version OpenJDK Runtime Environment (build 13.0.2+8-Ubuntu-2)
    ✗ Android license status unknown.
      Try re-installing or updating your Android SDK Manager.
      See https://developer.android.com/studio/#downloads or visit https://flutter.dev/setup/#android-setup for detailed instructions.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/setup/#android-setup for detailed instructions).

[✓] IntelliJ IDEA Community Edition (version 2019.3)
    • IntelliJ at /opt/idea-C
    • Flutter plugin version 43.0.3
    • Dart plugin version 193.6015.53

[✓] VS Code (version 1.44.2)
    • VS Code at /usr/share/code
    • Flutter extension version 3.9.1

[✓] Connected device (2 available)
    • Chrome     • chrome     • web-javascript • Google Chrome 81.0.4044.113
    • Web Server • web-server • web-javascript • Flutter Tools

! Doctor found issues in 2 categories.

```

## Flutter Application Metadata
```
**Version**: 1.0.0+1
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
```

**Comment by cerdikstdcreator** [comment]
help me to solved

**Comment by iapicca** [comment]
Hi @cerdikstdcreator 
could you please run `flutter upgrade --force `
and `flutter doctor --android-licenses`.

If the issue persists
can you please provide your `flutter doctor -v` 
and your `flutter run --verbose` as well.
Thank you

**Comment by cerdikstdcreator** [comment]
thank you brother

**Comment by TahaTesser** [comment]
Hi @cerdikstdcreator 
given your last message I feel safe to close this issue,
if you disagree please write in the comments and I will reopen it. 
Thank you
