### ISSUE TITLE
mDNS tests fail on windows due to usage of reusePort:true in Socket binding

### ISSUE THREAD

**Issue by jonahwilliams** [flutter/flutter#55173]
This isn't a production issue since we don't use mDNS on windows, but it does affect our testing.

https://github.com/flutter/packages/blob/caf02e01746723950dc6dd593037cf06024f692e/packages/multicast_dns/lib/multicast_dns.dart#L131

This causes:

```
art Socket ERROR: c:\b\s\w\ir\cache\builder\src\third_party\dart\runtime\bin\socket_win.cc:194: `reusePort` not supported for Windows.Dart Socket ERROR: c:\b\s\w\ir\cache\builder\src\third_party\dart\runtime\bin\socket_win.cc:194: `reusePort` not supported for Windows.Dart Socket ERROR: c:\b\s\w\ir\cach00:09 +7: attach fallbacks to protocol observatory if MDNS failed on iOS         
```

@dnfield does that need to be set to true? Could we default to false on windows?

**Comment by dnfield** [comment]
It'd be fine to default it to false on Windows.  The default implementation is meant to be used on macos.

**Comment by Niek** [comment]
Android is giving the same error, I'm using this code now:
```dart
final MDnsClient client = MDnsClient(rawDatagramSocketFactory:
    (dynamic host, int port, {bool reuseAddress, bool reusePort, int ttl}) {
  return RawDatagramSocket.bind(host, port,
      reuseAddress: true, reusePort: false, ttl: ttl);
});
```

**Comment by Sunbreak** [comment]
Pre-Windows 10 (1903) doen't support `mDNS` by default: https://stackoverflow.com/a/41019456

**Comment by guyluz11** [comment]
Thanks @Niek.
Here is a version with null safety support

```dart
final MDnsClient client = MDnsClient(rawDatagramSocketFactory:
    (dynamic host, int port,
        {bool? reuseAddress, bool? reusePort, int? ttl}) {
  return RawDatagramSocket.bind(host, port,
      reuseAddress: true, reusePort: false, ttl: ttl!);
});  
```

**Comment by zzdota** [comment]
> Thanks @Niek. Here is a version with null safety support
> 
> ```dart
> final MDnsClient client = MDnsClient(rawDatagramSocketFactory:
>     (dynamic host, int port,
>         {bool? reuseAddress, bool? reusePort, int? ttl}) {
>   return RawDatagramSocket.bind(host, port,
>       reuseAddress: true, reusePort: false, ttl: ttl!);
> });  
> ```

In my case, we should judge the current platform, only windows need to set reusePort parameter to false
```
final RawDatagramSocket socket = await _rawDatagramSocketFactory(
        targetAddress,
        selectedMDnsPort,
        reuseAddress: true,
        reusePort: Platform.isWindows ? false : true,
        ttl: 255,
      );
```

**Comment by cooltrooper** [comment]
Using the code based on information above:
``` dart
const String name = '_pasconnect._tcp';
    // final MDnsClient client = MDnsClient();
    // Start the client with default options.
    final MDnsClient client = MDnsClient(rawDatagramSocketFactory:
        (dynamic host, int port,
        {bool? reuseAddress, bool? reusePort, int? ttl}) {
      return RawDatagramSocket.bind(host, port,
          reuseAddress: true, reusePort: false, ttl: ttl!);
    });
    await client.start();

    // Get the PTR record for the service.
    await for (final PtrResourceRecord ptr in client
        .lookup<PtrResourceRecord>(ResourceRecordQuery.serverPointer(name))) {
      // Use the domainName from the PTR record to get the SRV record,
      // which will have the port and local hostname.
      // Note that duplicate messages may come through, especially if any
      // other mDNS queries are running elsewhere on the machine.
      await for (final SrvResourceRecord srv in client.lookup<SrvResourceRecord>(
          ResourceRecordQuery.service(ptr.domainName))) {
        // Domain name will be something like "io.flutter.example@some-iphone.local._dartobservatory._tcp.local"
        final String bundleId =
            ptr.domainName; //.substring(0, ptr.domainName.indexOf('@'));
        print('Dart observatory instance found at '
            '${srv.target}:${srv.port} for "$bundleId".');
      }
    }
    client.stop();

    print('Done.');
```

I get the following error

``` 
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: SocketException: Failed to create datagram socket (OS Error: The requested address is not valid in its context.

, errno = 10049), address = , port = 5353
#0      _NativeSocket.bindDatagram (dart:io-patch/socket_patch.dart:1015:7)
<asynchronous suspension>
#1      MDnsClient.start (package:multicast_dns/multicast_dns.dart:135:40)
<asynchronous suspension>
#2      _AmpViewState.getAmps (package:amp_chat/AmpView.dart:25:5)
<asynchronous suspension>
```

**Comment by guyluz11** [comment]
@jonahwilliams can you please add a link to the pr that solves this issue?

**Comment by jonahwilliams** [comment]
This is a bug about an internal unit test in the flutter tool that didn't work. it has been long since fixed. Since then, folks have interepreted this as a bug about fixing a particular in the mDNS package which it is not.
