### ISSUE TITLE
[tool_crash] Bad state: StreamSink is closed

### ISSUE THREAD

**Issue by user670** [flutter/flutter#55189]
## Comments
I know this is, like any other issues of the same crash, a Duplicate of dart-lang/webdev#943 . Said dart-lang/webdev#943 claims to have fixed this issue in dart-lang/sse#26 , and patched into Flutter in #54334 . However, even after the patch, 10 issue reports are still made regarding this issue, all of which redirected to dart-lang/webdev#943 then closed, without follow-up comments, questions or commits (as far as I can tell); #54850 seems to also acknowledge this crash being quite common, but also claiming it being fixed, only waiting for the next release in mid-May.
Can we expect this issue be fixed in beta release in mid-May, as #54850 claims?

## Command
```
flutter run -d chrome
```

## Steps to Reproduce
I have **no idea** how exactly that happened, and I cannot reproduce this issue - it happens seemingly randomly during the `flutter run`.

## Logs
StateError: Bad state: StreamSink is closed
```
#0      _StreamSinkImpl.add (dart:io/io_sink.dart:156:7)
#1      _Socket.add (dart:io-patch/socket_patch.dart:1868:38)
#2      _DetachedSocket.add (dart:_http/http_impl.dart:3070:13)
#3      _ByteAdapterSink.add (dart:convert/byte_conversion.dart:60:11)
#4      ByteConversionSinkBase.addSlice (dart:convert/byte_conversion.dart:45:5)
#5      _Utf8EncoderSink.addSlice (dart:convert/utf.dart:267:13)
#6      StringConversionSinkMixin.add (dart:convert/string_conversion.dart:165:5)
#7      SseConnection._setUpListener (package:sse/src/server/sse_handler.dart:73:15)
<asynchronous suspension>
#8      new SseConnection (package:sse/src/server/sse_handler.dart:53:15)
#9      SseHandler._createSseConnection.<anonymous closure> (package:sse/src/server/sse_handler.dart:161:26)
#10     _fromHttpRequest.onHijack.<anonymous closure> (package:shelf/shelf_io.dart:146:35)
#11     _rootRunUnary (dart:async/zone.dart:1192:38)
#12     _CustomZone.runUnary (dart:async/zone.dart:1085:19)
#13     _FutureListener.handleValue (dart:async/future_impl.dart:141:18)
#14     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:682:45)
#15     Future._propagateToListeners (dart:async/future_impl.dart:711:32)
#16     Future._completeWithValue (dart:async/future_impl.dart:526:5)
#17     Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:556:7)
#18     _rootRun (dart:async/zone.dart:1184:13)
```
```
[✓] Flutter (Channel beta, v1.17.0, on Microsoft Windows [Version 10.0.18362.778], locale zh-CN)
    • Flutter version 1.17.0 at D:\Flutter Workspace\flutter
    • Framework revision d3ed9ec945 (13 days ago), 2020-04-06 14:07:34 -0700
    • Engine revision c9506cb8e9
    • Dart version 2.8.0 (build 2.8.0-dev.18.0 eea9717938)

[!] Android toolchain - develop for Android devices
    • Android SDK at C:\Users\User670\AppData\Local\Android\sdk
    ✗ Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/docs/get-started/install/windows#android-setup for detailed instructions).
      If the Android SDK has been installed to a custom location, set ANDROID_HOME to that location.
      You may also want to add it to your PATH environment variable.

    ✗ No valid Android SDK platforms found in C:\Users\User670\AppData\Local\Android\sdk\platforms. Directory was empty.
    • Try re-installing or updating your Android SDK,
      visit https://flutter.dev/docs/get-started/install/windows#android-setup for detailed instructions.

[✓] Chrome - develop for the web
    • CHROME_EXECUTABLE = C:\Program Files (x86)\Google\Chrome Beta\Application\chrome.exe

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/windows#android-setup for detailed instructions).

[✓] VS Code, 64-bit edition (version 1.39.2)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Flutter extension version 3.7.1

[✓] Connected device (2 available)
    • Chrome     • chrome     • web-javascript • Google Chrome 49.0.2623.75
    • Web Server • web-server • web-javascript • Flutter Tools

! Doctor found issues in 2 categories.

```

## Flutter Application Metadata
**Type**: app
**Version**: 1.0.0+1
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: stable
**Creation framework version**: 5391447fae6209bb21a89e6a5a6583cac1af9b4b

Also from `flutter upgrade`:
```d:\Flutter Workspace\flutter>flutter upgrade
Upgrading Flutter from D:\Flutter Workspace\flutter...
From https://github.com/flutter/flutter
   8f7327f83..7f56b53de  dev              -> origin/dev
 * [new branch]          flutter-1.18-candidate.5 -> origin/flutter-1.18-candidate.5
 * [new branch]          guidezpl-patch-1 -> origin/guidezpl-patch-1
   1118d2479..8e5b57517  master           -> origin/master
 * [new tag]             1.18.0-dev.5.0   -> 1.18.0-dev.5.0
Already up to date.
Flutter is already up to date on channel beta
Flutter 1.17.0 • channel beta • https://github.com/flutter/flutter.git
Framework • revision d3ed9ec945 (13 days ago) • 2020-04-06 14:07:34 -0700
Engine • revision c9506cb8e9
Tools • Dart 2.8.0 (build 2.8.0-dev.18.0 eea9717938)```

**Comment by jonahwilliams** [comment]
All of the reported issues were from the beta channel April 6th which is older than the PR which landed the fix ( https://github.com/flutter/flutter/pull/54334/files ), so they are indeed duplicates. The purpose of the issue tracker is only to follow bugs that are not fixed at head, not to track issues that need to roll into dev/beta/stable channels.

If you have questions/concerns/comments about the release process feel free to raise them on either the mailing list or the flutter dev discord chat, but the issue tracker isn't the appropriate place.
