### ISSUE TITLE
ValueError: duplicate key in dictionary: src/third_party/dart/tools/sdks

### ISSUE THREAD

**Issue by zhongwuzw** [flutter/flutter#55185]
## Steps to Reproduce

Engine version as below:
![image](https://user-images.githubusercontent.com/5061845/79711058-67e8d080-82f9-11ea-8f58-5255f815e35f.png)

1. Setting up the Engine development environment。
2. execute 'gclinet sync', encounter following errors:
```
Warning: Running gclient on Python 3.
If you encounter any issues, please file a bug on crbug.com under the Infra>SDK component.

src/flutter (ERROR)
----------------------------------------
[0:00:00] Started.
[0:00:00] ________ unmanaged solution; skipping src/flutter
[0:00:00] Finished running: git rev-parse --verify HEAD
----------------------------------------
Traceback (most recent call last):
  File "/Users/zhongwu/Documents/workspace/depot_tools/metrics.py", line 267, in print_notice_and_exit
    yield
  File "/Users/zhongwu/Documents/workspace/depot_tools/gclient.py", line 3179, in <module>
    sys.exit(main(sys.argv[1:]))
  File "/Users/zhongwu/Documents/workspace/depot_tools/gclient.py", line 3165, in main
    return dispatcher.execute(OptionParser(), argv)
  File "/Users/zhongwu/Documents/workspace/depot_tools/subcommand.py", line 252, in execute
    return command(parser, args[1:])
  File "/Users/zhongwu/Documents/workspace/depot_tools/gclient.py", line 2723, in CMDsync
    ret = client.RunOnDeps('update', args)
  File "/Users/zhongwu/Documents/workspace/depot_tools/gclient.py", line 1766, in RunOnDeps
    work_queue.flush(revision_overrides, command, args, options=self._options,
  File "/Users/zhongwu/Documents/workspace/depot_tools/gclient_utils.py", line 948, in flush
    reraise(e[0], e[1], e[2])
  File "/Users/zhongwu/Documents/workspace/depot_tools/gclient_utils.py", line 66, in reraise
    raise value
  File "/Users/zhongwu/Documents/workspace/depot_tools/gclient_utils.py", line 1025, in run
    self.item.run(*self.args, **self.kwargs)
  File "/Users/zhongwu/Documents/workspace/depot_tools/gclient.py", line 964, in run
    self.ParseDepsFile()
  File "/Users/zhongwu/Documents/workspace/depot_tools/gclient.py", line 723, in ParseDepsFile
    local_scope = gclient_eval.Parse(
  File "/Users/zhongwu/Documents/workspace/depot_tools/gclient_eval.py", line 473, in Parse
    result = Exec(content, filename, vars_override, builtin_vars)
  File "/Users/zhongwu/Documents/workspace/depot_tools/gclient_eval.py", line 379, in Exec
    value = _gclient_eval(node, filename, vars_dict)
  File "/Users/zhongwu/Documents/workspace/depot_tools/gclient_eval.py", line 303, in _gclient_eval
    return _convert(node_or_string)
  File "/Users/zhongwu/Documents/workspace/depot_tools/gclient_eval.py", line 257, in _convert
    raise ValueError(
ValueError: duplicate key in dictionary: src/third_party/dart/tools/sdks (file '/Users/zhongwu/Documents/workspace/engine/src/flutter/DEPS', line 497)
```

## Logs

```
Warning: Running gclient on Python 3.
If you encounter any issues, please file a bug on crbug.com under the Infra>SDK component.

src/flutter (ERROR)
----------------------------------------
[0:00:00] Started.
[0:00:00] ________ unmanaged solution; skipping src/flutter
[0:00:00] Finished running: git rev-parse --verify HEAD
----------------------------------------
Traceback (most recent call last):
  File "/Users/zhongwu/Documents/workspace/depot_tools/metrics.py", line 267, in print_notice_and_exit
    yield
  File "/Users/zhongwu/Documents/workspace/depot_tools/gclient.py", line 3179, in <module>
    sys.exit(main(sys.argv[1:]))
  File "/Users/zhongwu/Documents/workspace/depot_tools/gclient.py", line 3165, in main
    return dispatcher.execute(OptionParser(), argv)
  File "/Users/zhongwu/Documents/workspace/depot_tools/subcommand.py", line 252, in execute
    return command(parser, args[1:])
  File "/Users/zhongwu/Documents/workspace/depot_tools/gclient.py", line 2723, in CMDsync
    ret = client.RunOnDeps('update', args)
  File "/Users/zhongwu/Documents/workspace/depot_tools/gclient.py", line 1766, in RunOnDeps
    work_queue.flush(revision_overrides, command, args, options=self._options,
  File "/Users/zhongwu/Documents/workspace/depot_tools/gclient_utils.py", line 948, in flush
    reraise(e[0], e[1], e[2])
  File "/Users/zhongwu/Documents/workspace/depot_tools/gclient_utils.py", line 66, in reraise
    raise value
  File "/Users/zhongwu/Documents/workspace/depot_tools/gclient_utils.py", line 1025, in run
    self.item.run(*self.args, **self.kwargs)
  File "/Users/zhongwu/Documents/workspace/depot_tools/gclient.py", line 964, in run
    self.ParseDepsFile()
  File "/Users/zhongwu/Documents/workspace/depot_tools/gclient.py", line 723, in ParseDepsFile
    local_scope = gclient_eval.Parse(
  File "/Users/zhongwu/Documents/workspace/depot_tools/gclient_eval.py", line 473, in Parse
    result = Exec(content, filename, vars_override, builtin_vars)
  File "/Users/zhongwu/Documents/workspace/depot_tools/gclient_eval.py", line 379, in Exec
    value = _gclient_eval(node, filename, vars_dict)
  File "/Users/zhongwu/Documents/workspace/depot_tools/gclient_eval.py", line 303, in _gclient_eval
    return _convert(node_or_string)
  File "/Users/zhongwu/Documents/workspace/depot_tools/gclient_eval.py", line 257, in _convert
    raise ValueError(
ValueError: duplicate key in dictionary: src/third_party/dart/tools/sdks (file '/Users/zhongwu/Documents/workspace/engine/src/flutter/DEPS', line 497)
```

```
```

**Comment by zhongwuzw** [comment]
Similar Issues: https://github.com/flutter/flutter/issues/51982

**Comment by Jorgezz** [comment]
same error

**Comment by zhongwuzw** [comment]
@jason-simmons Any ideas?

**Comment by Jorgezz** [comment]
flutter git:(master) gclient sync --with_branch_heads --with_tags
Warning: Running gclient on Python 3.
If you encounter any issues, please file a bug on crbug.com under the Infra>SDK component.
/Users/user
/Documents/flutter/2020/engine/.gclient_entries missing, .gclient file in parent directory /Users/user
/Documents/flutter/2020/engine might not be the file you want to use.

src/flutter (ERROR)
----------------------------------------
[0:00:00] Started.
[0:00:00] ________ unmanaged solution; skipping src/flutter
[0:00:00] Finished running: git rev-parse --verify HEAD
----------------------------------------
Traceback (most recent call last):
  File "/path/to/depot_tools/metrics.py", line 267, in print_notice_and_exit
    yield
  File "/path/to/depot_tools/gclient.py", line 3179, in <module>
    sys.exit(main(sys.argv[1:]))
  File "/path/to/depot_tools/gclient.py", line 3165, in main
    return dispatcher.execute(OptionParser(), argv)
  File "/path/to/depot_tools/subcommand.py", line 252, in execute
    return command(parser, args[1:])
  File "/path/to/depot_tools/gclient.py", line 2723, in CMDsync
    ret = client.RunOnDeps('update', args)
  File "/path/to/depot_tools/gclient.py", line 1766, in RunOnDeps
    work_queue.flush(revision_overrides, command, args, options=self._options,
  File "/path/to/depot_tools/gclient_utils.py", line 948, in flush
    reraise(e[0], e[1], e[2])
  File "/path/to/depot_tools/gclient_utils.py", line 66, in reraise
    raise value
  File "/path/to/depot_tools/gclient_utils.py", line 1025, in run
    self.item.run(*self.args, **self.kwargs)
  File "/path/to/depot_tools/gclient.py", line 964, in run
    self.ParseDepsFile()
  File "/path/to/depot_tools/gclient.py", line 723, in ParseDepsFile
    local_scope = gclient_eval.Parse(
  File "/path/to/depot_tools/gclient_eval.py", line 473, in Parse
    result = Exec(content, filename, vars_override, builtin_vars)
  File "/path/to/depot_tools/gclient_eval.py", line 379, in Exec
    value = _gclient_eval(node, filename, vars_dict)
  File "/path/to/depot_tools/gclient_eval.py", line 303, in _gclient_eval
    return _convert(node_or_string)
  File "/path/to/depot_tools/gclient_eval.py", line 257, in _convert
    raise ValueError(
ValueError: duplicate key in dictionary: src/third_party/dart/tools/sdks (file '/Users/user
/Documents/flutter/2020/engine/src/flutter/DEPS', line 494)

**Comment by Jorgezz** [comment]
engine git:(master) ✗ gclient sync
Warning: Running gclient on Python 3.
If you encounter any issues, please file a bug on crbug.com under the Infra>SDK component.

src/flutter (ERROR)
----------------------------------------
[0:00:00] Started.
[0:00:00] ________ unmanaged solution; skipping src/flutter
[0:00:00] Finished running: git rev-parse --verify HEAD
----------------------------------------
Traceback (most recent call last):
  File "/Users/user
/Documents/
flutter/2020/depot_tools/metrics.py", line 267, in print_notice_and_exit
    yield
  File "/Users/user
/Documents/
flutter/2020/depot_tools/gclient.py", line 3179, in <module>
    sys.exit(main(sys.argv[1:]))
  File "/Users/user
/Documents/
flutter/2020/depot_tools/gclient.py", line 3165, in main
    return dispatcher.execute(OptionParser(), argv)
  File "/Users/user
/Documents/
flutter/2020/depot_tools/subcommand.py", line 252, in execute
    return command(parser, args[1:])
  File "/Users/user
/Documents/
flutter/2020/depot_tools/gclient.py", line 2723, in CMDsync
    ret = client.RunOnDeps('update', args)
  File "/Users/user
/Documents/
flutter/2020/depot_tools/gclient.py", line 1766, in RunOnDeps
    work_queue.flush(revision_overrides, command, args, options=self._options,
  File "/Users/user
/Documents/
flutter/2020/depot_tools/gclient_utils.py", line 948, in flush
    reraise(e[0], e[1], e[2])
  File "/Users/user
/Documents/
flutter/2020/depot_tools/gclient_utils.py", line 66, in reraise
    raise value
  File "/Users/user
/Documents/
flutter/2020/depot_tools/gclient_utils.py", line 1025, in run
    self.item.run(*self.args, **self.kwargs)
  File "/Users/user
/Documents/
flutter/2020/depot_tools/gclient.py", line 964, in run
    self.ParseDepsFile()
  File "/Users/user
/Documents/
flutter/2020/depot_tools/gclient.py", line 723, in ParseDepsFile
    local_scope = gclient_eval.Parse(
  File "/Users/user
/Documents/
flutter/2020/depot_tools/gclient_eval.py", line 473, in Parse
    result = Exec(content, filename, vars_override, builtin_vars)
  File "/Users/user
/Documents/
flutter/2020/depot_tools/gclient_eval.py", line 379, in Exec
    value = _gclient_eval(node, filename, vars_dict)
  File "/Users/user
/Documents/
flutter/2020/depot_tools/gclient_eval.py", line 303, in _gclient_eval
    return _convert(node_or_string)
  File "/Users/user
/Documents/
flutter/2020/depot_tools/gclient_eval.py", line 257, in _convert
    raise ValueError(
ValueError: duplicate key in dictionary: src/third_party/dart/tools/sdks (file '/Users/user
/Documents/
flutter/2020/engine/src/flutter/DEPS', line 494)

**Comment by jason-simmons** [comment]
If you are using an older version of the Flutter engine sources with a current version of depot_tools, then 
you will need to backport https://github.com/flutter/engine/commit/7df0a6e35e5c1a4e541fb53538bc527daa41ba7c and https://github.com/flutter/engine/commit/2713225a6eefe44ccefe379615b144a40845b879

**Comment by Jorgezz** [comment]
> If you are using an older version of the Flutter engine sources with a current version of depot_tools, then
> you will need to backport [flutter/engine@7df0a6e](https://github.com/flutter/engine/commit/7df0a6e35e5c1a4e541fb53538bc527daa41ba7c) and [flutter/engine@2713225](https://github.com/flutter/engine/commit/2713225a6eefe44ccefe379615b144a40845b879)

I try to find flutter/engine@7df0a6e and flutter/engine@2713225 modification in my flutter engine project, there no delete content in DEPS file, should I add them(@7df0a6e and flutter/engine@2713225 ) back ?

**Comment by Jorgezz** [comment]
> > If you are using an older version of the Flutter engine sources with a current version of depot_tools, then
> > you will need to backport [flutter/engine@7df0a6e](https://github.com/flutter/engine/commit/7df0a6e35e5c1a4e541fb53538bc527daa41ba7c) and [flutter/engine@2713225](https://github.com/flutter/engine/commit/2713225a6eefe44ccefe379615b144a40845b879)
> 
> I try to find [flutter/engine@7df0a6e](https://github.com/flutter/engine/commit/7df0a6e) and [flutter/engine@2713225](https://github.com/flutter/engine/commit/2713225) modification in my flutter engine project, there no delete content in DEPS file, should I add them(@7df0a6e and [flutter/engine@2713225](https://github.com/flutter/engine/commit/2713225) ) back ? @jason-simmons

My issue has resolved, when i changed git on my own address: 
https://github.com/Jorgezz/engine.git

**Comment by Jorgezz** [comment]
May be we can try cherry-pick this commit id to our branch : 2713225a6 - Remove duplicate and outdated src/third_party/dart/tools/sdks entry from DEPS. (#14340) (2019-12-11 14:28:00 5 months ago)  <Alexander Aprelev> @aam @jason-simmons @zhongwuzw

**Comment by chinmaygarde** [comment]
This has been fixed in https://github.com/flutter/flutter/commit/2713225a6eefe44ccefe379615b144a40845b879. On ToT, I can see no duplicate entry either.
