### ISSUE TITLE
Error selecting a select control html on my webview plugin

### ISSUE THREAD

**Issue by pedrofmb** [flutter/flutter#55222]
Pedro Fabian More Barrios, [20.04.20 13:10]

```
E/InputMethodManager( 8105): b/117267690: Failed to get fallback IMM with expected displayId=21 actual IMM#displayId=0 view=io.flutter.plugins.webviewflutter.InputAwareWebView{86b4f67 VFEDHVC.. .F...... 0,0-1440,2392}
D/EGL_emulation( 8105): eglMakeCurrent: 0xd92d95c0: ver 2 0 (tinfo 0xd930b2e0)
W/cr_AwAutofillManager( 8105): WebView autofill is disabled because WebView isn't created with activity context.
W/cr_AwAutofillManager( 8105): WebView autofill is disabled because WebView isn't created with activity context.
W/cr_AwAutofillManager( 8105): WebView autofill is disabled because WebView isn't created with activity context.
W/System.err( 8105): java.lang.ClassCastException: $Proxy0 cannot be cast to android.view.WindowManagerImpl
W/System.err( 8105):   at android.view.Window.setWindowManager(Window.java:778)
W/System.err( 8105):   at android.view.Window.setWindowManager(Window.java:760)
W/System.err( 8105):   at android.app.Dialog.<init>(Dialog.java:207)
W/System.err( 8105):   at android.app.AlertDialog.<init>(AlertDialog.java:204)
W/System.err( 8105):   at android.app.AlertDialog$Builder.create(AlertDialog.java:1105)
W/System.err( 8105):   at JB.<init>(PG:6)
W/System.err( 8105):   at org.chromium.content.browser.input.SelectPopup.show(PG:41)
W/System.err( 8105):   at android.os.MessageQueue.nativePollOnce(Native Method)
W/System.err( 8105):   at android.os.MessageQueue.next(MessageQueue.java:336)
W/System.err( 8105):   at android.os.Looper.loop(Looper.java:174)
W/System.err( 8105):   at android.app.ActivityThread.main(ActivityThread.java:7356)
W/System.err( 8105):   at java.lang.reflect.Method.invoke(Native Method)
W/System.err( 8105):   at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
W/System.err( 8105):   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
F/chromium( 8105): [FATAL:jni_android.cc(249)] Please include Java exception stack in crash report
F/libc    ( 8105): Fatal signal 5 (SIGTRAP), code 128 (SI_KERNEL), fault addr 0x0 in tid 8105 (mple.flutterapp), pid 8105 (mple.flutterapp)
```

**Comment by VladyslavBondarenko** [comment]
Hi @pedrofmb 
please follow up on https://github.com/flutter/flutter/issues/25767 and https://github.com/flutter/flutter/issues/29649
I'm closing the current one as duplicate.
If you disagree please write in the comments and I will reopen it.
Thank you
