### ISSUE TITLE
Unable to run "adb", check your Android SDK installation and ANDROID_HOME environment variable

### ISSUE THREAD

**Issue by dgonz234** [flutter/flutter#55267]
Everything was fine a couple weeks ago when I last worked on a project. Don't know what caused anything to change. Went back to it to add a package, and `flutter pub get` would fail with `could not un-gzip`.

I've tried uninstalling and reinstalling Flutter + Android Studio multiple times already to no luck. I'm able to create a new flutter project using VSCode, but when I run `flutter doctor`, it fails - as well as `flutter pub get` in the project directory I'm trying to work on.

*note: I tried installing the latest version of Flutter, installing an older version and upgrading, as well as using the `git clone` method to install

## Logs
`flutter pub get`
```
`Could not un-gzip (exit code -1073741819). Error:`

`package:pub/src/io.dart 927:7               _extractTarGzWindows.<fn>
===== asynchronous gap ===========================
package:pub/src/io.dart 820:20              withTempDir
package:pub/src/io.dart 914:10              _extractTarGzWindows
package:pub/src/io.dart 842:18              extractTarGz
package:pub/src/source/hosted.dart 323:11   BoundHostedSource._download
===== asynchronous gap ===========================
package:pub/src/source/hosted.dart 217:13   BoundHostedSource.downloadToSystemCache
package:pub/src/entrypoint.dart 388:48      Entrypoint._get.<fn>
package:pub/src/http.dart 271:51            withDependencyType
package:pub/src/entrypoint.dart 384:12      Entrypoint._get
dart:async                                  Future.wait
package:pub/src/entrypoint.dart 245:18      Entrypoint.acquireDependencies
dart:async                                  _completeOnAsyncReturn
package:pub/src/solver/version_solver.dart  VersionSolver.solve
dart:async                                  _completeOnAsyncReturn
package:pub/src/solver/version_solver.dart  VersionSolver._result`
This is an unexpected error. Please run

    pub --trace '--verbosity=warning' get --no-precompile

and include the logs in an issue on https://github.com/dart-lang/pub/issues/new
Running "flutter pub get" in fire_interval_timer...
pub get failed (1; and include the logs in an issue on https://github.com/dart-lang/pub/issues/new)

```

`flutter doctor -v`
```
`[!] Flutter (Channel stable, v1.12.13+hotfix.9, on Microsoft Windows [Version 10.0.18363.778],    locale en-US)
    • Flutter version 1.12.13+hotfix.9 at C:\src\flutter
    • Framework revision f139b11009 (3 weeks ago), 2020-03-30 13:57:30 -0700
    • Engine revision af51afceb8
    • Dart version 2.7.2
    X Downloaded executables cannot execute on host.
      See https://github.com/flutter/flutter/issues/6207 for more information`


 
`[√] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at C:\Users\dag81\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)
    • All Android licenses accepted.`

`[√] Android Studio (version 3.6)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)`

`[√] VS Code (version 1.44.2)
    • VS Code at C:\Users\dag81\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.9.1`

`[☠] Connected device (the doctor check crashed)
    X Due to an error, the doctor check did not complete. If the error message below is not
      helpful, please let us know about this issue at
      https://github.com/flutter/flutter/issues.
    X Exception: Unable to run "adb", check your Android SDK installation and ANDROID_HOME    
      environment variable: C:\Users\dag81\AppData\Local\Android\sdk\platform-tools\adb.exe   
    • #0      throwToolExit (package:flutter_tools/src/base/common.dart:28:3)
      #1      getAdbDevices (package:flutter_tools/src/android/android_device.dart:731:5)
      #2      AndroidDevices.pollingGetDevices
      (package:flutter_tools/src/android/android_device.dart:65:53)
      #3      PollingDeviceDiscovery.devices (package:flutter_tools/src/device.dart:285:52)
      #4      DeviceManager.getAllConnectedDevices
      (package:flutter_tools/src/device.dart:140:46)
      <asynchronous suspension>
      #5      DeviceValidator.validate (package:flutter_tools/src/doctor.dart:851:54)
      #6      asyncGuard.<anonymous closure>
      (package:flutter_tools/src/base/async_guard.dart:111:32)
      #7      _rootRun (dart:async/zone.dart:1126:13)
      #8      _CustomZone.run (dart:async/zone.dart:1023:19)
      #9      _runZoned (dart:async/zone.dart:1518:10)
      #10     runZoned (dart:async/zone.dart:1502:12)
      #11     asyncGuard (package:flutter_tools/src/base/async_guard.dart:109:3)
      #12     Doctor.startValidatorTasks (package:flutter_tools/src/doctor.dart:158:9)
      #13     Doctor.diagnose (package:flutter_tools/src/doctor.dart:252:41)
      #14     _AsyncAwaitCompleter.start (dart:async-patch/async_patch.dart:45:6)
      #15     Doctor.diagnose (package:flutter_tools/src/doctor.dart:241:24)
      #16     DoctorCommand.runCommand (package:flutter_tools/src/commands/doctor.dart:59:39)
      #17     _AsyncAwaitCompleter.start (dart:async-patch/async_patch.dart:45:6)
      #18     DoctorCommand.runCommand (package:flutter_tools/src/commands/doctor.dart:45:42)
      #19     FlutterCommand.verifyThenRunCommand
      (package:flutter_tools/src/runner/flutter_command.dart:615:18)
      #20     _asyncThenWrapperHelper.<anonymous closure>
      (dart:async-patch/async_patch.dart:73:64)
      #21     _rootRunUnary (dart:async/zone.dart:1134:38)
      #22     _CustomZone.runUnary (dart:async/zone.dart:1031:19)
      #23     _FutureListener.handleValue (dart:async/future_impl.dart:139:18)
      #24     Future._propagateToListeners.handleValueCallback
      (dart:async/future_impl.dart:680:45)
      #25     Future._propagateToListeners (dart:async/future_impl.dart:709:32)
      #26     Future._completeWithValue (dart:async/future_impl.dart:524:5)
      #27     Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:554:7)
      #28     _rootRun (dart:async/zone.dart:1126:13)
      #29     _CustomZone.run (dart:async/zone.dart:1023:19)
      #30     _CustomZone.runGuarded (dart:async/zone.dart:925:7)
      #31     _CustomZone.bindCallbackGuarded.<anonymous closure>
      (dart:async/zone.dart:965:23)
      #32     _microtaskLoop (dart:async/schedule_microtask.dart:43:21)
      #33     _startMicrotaskLoop (dart:async/schedule_microtask.dart:52:5)
      #34     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
      #35     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:175:5)`

`! Doctor found issues in 2 categories.`
<!--
      Include the full logs of the commands you are running between the lines
      with the backticks below. If you are running any "flutter" commands,
      please include the output of running them with "--verbose"; for example,
      the output of running "flutter --verbose create foo".
-->

```
```

<!-- If possible, paste the output of running `flutter doctor -v` here. -->

```

```

**Comment by TahaTesser** [comment]
Hi @dgonz234 
Could you please provider your `flutter pub get -v`?

**Comment by christopherfujino** [comment]
@dgonz234 The issue is with your Android SDK installation. From the crash output, can  you verify the following location:

```
    X Exception: Unable to run "adb", check your Android SDK installation and ANDROID_HOME    
      environment variable: C:\Users\dag81\AppData\Local\Android\sdk\platform-tools\adb.exe   
```

Since you said you've installed Android Studio, which comes with its own version of the Android SDK, the easiest solution might be just to uninstall the above sdk installation, and let the tool find the version in your Android Studio install.

**Comment by dgonz234** [comment]
![image](https://user-images.githubusercontent.com/47119961/80668527-bb7cbc00-8a67-11ea-9491-56a9d7d76195.png)

**Comment by dgonz234** [comment]
also, this is the latest flutter doctor output that I get.

`C:\Users\dag81>flutter doctor -v
[√] Flutter (Channel master, 1.18.0-9.0.pre.73, on Microsoft Windows [Version
    10.0.18363.778], locale en-US)
    • Flutter version 1.18.0-9.0.pre.73 at C:\src\flutter
    • Framework revision bd6ccb606a (4 hours ago), 2020-04-29 16:31:42 -0700
    • Engine revision 2db3276573
    • Dart version 2.9.0 (build 2.9.0-4.0.dev 726d3c7725)`

`[√] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at C:\Users\dag81\AppData\Local\Android\Sdk
    • Platform android-29, build-tools 29.0.3
    • ANDROID_HOME = C:\Users\dag81\AppData\Local\Android\Sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)
    • All Android licenses accepted.`

`[√] Android Studio (version 3.6)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)`
`[√] VS Code (version 1.44.2)
    • VS Code at C:\Users\dag81\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.9.1`

`[☠] Connected device (the doctor check crashed)
    X Due to an error, the doctor check did not complete. If the error message below is not helpful, please let us know about this issue at
      https://github.com/flutter/flutter/issues.
    X Exception: Unable to run "adb", check your Android SDK installation and ANDROID_HOME environment variable:
      C:\Users\dag81\AppData\Local\Android\Sdk\platform-tools\adb.exe
    • #0      throwToolExit (package:flutter_tools/src/base/common.dart:14:3)
      #1      AndroidDevices.pollingGetDevices (package:flutter_tools/src/android/android_device_discovery.dart:62:7)
      <asynchronous suspension>
      #2      PollingDeviceDiscovery._populateDevices (package:flutter_tools/src/device.dart:326:52)
      #3      PollingDeviceDiscovery.devices (package:flutter_tools/src/device.dart:316:12)
      #4      DeviceManager.getAllConnectedDevices (package:flutter_tools/src/device.dart:157:20)
      #5      DeviceValidator.validate (package:flutter_tools/src/doctor.dart:937:54)
      #6      asyncGuard.<anonymous closure> (package:flutter_tools/src/base/async_guard.dart:111:32)
      #7      _rootRun (dart:async/zone.dart:1184:13)
      #8      _CustomZone.run (dart:async/zone.dart:1077:19)
      #9      _runZoned (dart:async/zone.dart:1619:10)
      #10     runZonedGuarded (dart:async/zone.dart:1608:12)
      #11     runZoned (dart:async/zone.dart:1536:12)
      #12     asyncGuard (package:flutter_tools/src/base/async_guard.dart:109:3)
      #13     Doctor.startValidatorTasks (package:flutter_tools/src/doctor.dart:181:9)
      #14     Doctor.diagnose (package:flutter_tools/src/doctor.dart:280:47)
      #15     DoctorCommand.runCommand (package:flutter_tools/src/commands/doctor.dart:59:47)
      #16     FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:765:18)
      #17     _rootRunUnary (dart:async/zone.dart:1192:38)
      #18     _CustomZone.runUnary (dart:async/zone.dart:1085:19)
      #19     _FutureListener.handleValue (dart:async/future_impl.dart:141:18)
      #20     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:686:45)
      #21     Future._propagateToListeners (dart:async/future_impl.dart:715:32)
      #22     Future._completeWithValue (dart:async/future_impl.dart:526:5)
      #23     Future._asyncCompleteWithValue.<anonymous closure> (dart:async/future_impl.dart:560:7)
      #24     _rootRun (dart:async/zone.dart:1184:13)
      #25     _CustomZone.run (dart:async/zone.dart:1077:19)
      #26     _CustomZone.runGuarded (dart:async/zone.dart:979:7)
      #27     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1019:23)
      #28     _microtaskLoop (dart:async/schedule_microtask.dart:43:21)
      #29     _startMicrotaskLoop (dart:async/schedule_microtask.dart:52:5)
      #30     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
      #31     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:169:5)`

`! Doctor found issues in 1 category.`

**Comment by henryandersen** [comment]
I am having the same issue. I installed the Android SDK through the setup wizard and I get the same output as the last one above. I also trie putting this in my .zshrc with no luck: 

```
export PATH="$PATH:/Users/henryandersen/Library/Android/sdk/platform-tools"
export ANDROID_HOME=$HOME/Library/Android/sdk
export PATH=$PATH:$ANDROID_HOME/tools
export PATH=$PATH:$ANDROID_HOME/platform-tools
```

**Comment by henryandersen** [comment]
I am on Mac btw, here is my exact out put log:

```
[✓] Flutter (Channel stable, v1.17.3, on Mac OS X 10.15.5 19F101, locale en-US)
    • Flutter version 1.17.3 at /Users/henryandersen/flutter
    • Framework revision b041144f83 (5 days ago), 2020-06-04 09:26:11 -0700
    • Engine revision ee76268252
    • Dart version 2.8.4

[!] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/henryandersen/Library/Android/sdk
    • Platform android-29, build-tools 29.0.3
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor
      --android-licenses

[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.5, Build version 11E608c
    • CocoaPods version 1.9.3

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 46.0.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.45.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.11.0

 
[☠] Connected device (the doctor check crashed)
    ✗ Due to an error, the doctor check did not complete. If the error message
      below is not helpful, please let us know about this issue at
      https://github.com/flutter/flutter/issues.
    ✗ Exception: Unable to run "adb", check your Android SDK installation and
      ANDROID_HOME environment variable:
      /Users/henryandersen/Library/Android/sdk/platform-tools/adb
    • #0      throwToolExit (package:flutter_tools/src/base/common.dart:14:3)
      #1      AndroidDevices.pollingGetDevices
      (package:flutter_tools/src/android/android_device_discovery.dart:62:7)
      <asynchronous suspension>
      #2      PollingDeviceDiscovery._populateDevices
      (package:flutter_tools/src/device.dart:321:52)
      #3      PollingDeviceDiscovery.devices
      (package:flutter_tools/src/device.dart:311:12)
      #4      DeviceManager.getAllConnectedDevices
      (package:flutter_tools/src/device.dart:152:20)
      #5      DeviceValidator.validate
      (package:flutter_tools/src/doctor.dart:926:54)
      #6      asyncGuard.<anonymous closure>
      (package:flutter_tools/src/base/async_guard.dart:111:32)
      #7      _rootRun (dart:async/zone.dart:1184:13)
      #8      _CustomZone.run (dart:async/zone.dart:1077:19)
      #9      _runZoned (dart:async/zone.dart:1619:10)
      #10     runZonedGuarded (dart:async/zone.dart:1608:12)
      #11     runZoned (dart:async/zone.dart:1536:12)
      #12     asyncGuard (package:flutter_tools/src/base/async_guard.dart:109:3)
      #13     Doctor.startValidatorTasks
      (package:flutter_tools/src/doctor.dart:172:9)
      #14     Doctor.diagnose (package:flutter_tools/src/doctor.dart:271:47)
      #15     DoctorCommand.runCommand
      (package:flutter_tools/src/commands/doctor.dart:60:39)
      #16     FlutterCommand.verifyThenRunCommand
      (package:flutter_tools/src/runner/flutter_command.dart:723:18)
      #17     _rootRunUnary (dart:async/zone.dart:1192:38)
      #18     _CustomZone.runUnary (dart:async/zone.dart:1085:19)
      #19     _FutureListener.handleValue (dart:async/future_impl.dart:141:18)
      #20     Future._propagateToListeners.handleValueCallback
      (dart:async/future_impl.dart:682:45)
      #21     Future._propagateToListeners (dart:async/future_impl.dart:711:32)
      #22     Future._completeWithValue (dart:async/future_impl.dart:526:5)
      #23     Future._asyncComplete.<anonymous closure>
      (dart:async/future_impl.dart:556:7)
      #24     _rootRun (dart:async/zone.dart:1184:13)
      #25     _CustomZone.run (dart:async/zone.dart:1077:19)
      #26     _CustomZone.runGuarded (dart:async/zone.dart:979:7)
      #27     _CustomZone.bindCallbackGuarded.<anonymous closure>
      (dart:async/zone.dart:1019:23)
      #28     _microtaskLoop (dart:async/schedule_microtask.dart:43:21)
      #29     _startMicrotaskLoop (dart:async/schedule_microtask.dart:52:5)
      #30     _runPendingImmediateCallback
      (dart:isolate-patch/isolate_patch.dart:118:13)
      #31     _RawReceivePortImpl._handleMessage
      (dart:isolate-patch/isolate_patch.dart:169:5)


! Doctor found issues in 2 categories.
```

**Comment by henryandersen** [comment]
If I delete android studio I can run flutter apps on an iPhone simulator

**Comment by christopherfujino** [comment]
Thanks for the additional info @henryandersen

**Comment by leha404** [comment]
I have the same problem and I found, that only flutter project don't allow to connect in AVD manager. With default android project with Kotlin emulator works fine, but when I go to flutter project, there is still loading device in device list and error "Unable to locate adb" when I tried power on emulator.

It worked fine before, on previous android studio (don't remember version, but less than 3.6)

Now I tried Android Studio 4.0 and this error just stops all my work

**Comment by leha404** [comment]
I solve my problem, maybe it will help:
- I downgrade my Android Studio to 3.6 and problem with "Unable to connect adb" has gone
- I still has problem with infinite loading device list in Android Studio (but able to run flutter through console). I changed flutter version to very old (from video courses, that version is fine for me). I changed from 1.17.0 to 1.2.1. And both problems has gone for me.

So, if your problems with adb on Mac (my mac is old MacBook pro 8.2) and you tried all solutions with PATH, tools etc, try switch to older version Android Studio.

Also, I though that it was problem with Android API, but now I used Nexus 6 with Android PIE (API 28) and it works fine in Android Studio 3.6, but not 4.0. And I tried different APIs, so, it's not this.

**Comment by thaboyjuicee** [comment]
I just found a solution to the error.
It worked for me as at Fri, July 10.
I'm a flutter developer and had this issue 2 days ago also.
I found out that previous programs I use which need usb debugging to run (Android rooting apps in my case) get installed with their own adb.exe which conflicts with Android platform-tools ADB.
So I advise you uninstall those programs, by opening task manager (CTRL+Shift+ESC) 
Check for any adb.exe running and open file location. If it doesn't lead to Android>sdk>platform-tools
Then uninstall that program.


This worked for me !

**Comment by fabiancrx** [comment]
It seems the problem is due to having more than one adb binary in the system.
In linux you can check from the command line if typing the command `adb`  is found; if it found then run `which adb` if the directory output from this commnand is different than platform-tools you could make a backup of the adb in the android SDK just in case and create a symbolic link "adb" to the one globally in your system (normally /usr/bin/adb),. This way it's just one binary of adb that youre using.
Windows useres just search the entire PC for adb.exe and uninstall any other program that shadows the androidSDK as pointed out by @Juicee999

**Comment by daniel2code** [comment]
it's really frustrating to encounter such a problem. I had a similar experience that drained my energy and time, but after examining my android SDK platform-tools, I discovered it was corrupted. so I deleted it and installed a new one, thereafter I had a sigh of relief. you can try it out.

**Comment by Cyberavater** [comment]
Check this please, https://stackoverflow.com/questions/62468046/android-studio-launch-emulator-avd-unable-to-locate-adb/63735075#63735075

**Comment by ehsanonline** [comment]
make sure TCP 5554 and TCP 5037 ports are not occupied. adb use them.

**Comment by gummyWalrus** [comment]
> It seems the problem is due to having more than one adb binary in the system. In linux you can check from the command line if typing the command `adb` is found; if it found then run `which adb` if the directory output from this commnand is different than platform-tools you could make a backup of the adb in the android SDK just in case and create a symbolic link "adb" to the one globally in your system (normally /usr/bin/adb),. This way it's just one binary of adb that youre using. Windows useres just search the entire PC for adb.exe and uninstall any other program that shadows the androidSDK as pointed out by @Juicee999

I've been using flutter since 3 years now and this never occured to me, I have followed the steps before to set the correct env variables and reboot, and I've litterally ran "find" over my whole filesystem to check that I only had one adb executable with : 
```
sudo find / -type f -name adb -executable 2>/dev/null
```

I understand the problem that this error occures in a lot of different situations but I believe that more granular logging during this phase would help people solve the issue.

**Comment by mboetger** [comment]
De-dupe
