### ISSUE TITLE
flutter exited  unexpectedly

### ISSUE THREAD

**Issue by 1abir** [flutter/flutter#55352]
Flutter crash report; please file at https://github.com/flutter/flutter/issues.

## command

flutter doctor

## exception

IndexError: RangeError (index): Index out of range: no indices are valid: 0

```
#0      Uint8List.[] (dart:typed_data-patch/typed_data_patch.dart:2209:7)
#1      InputStream.readUint16 (package:archive/src/util/input_stream.dart:190:20)
#2      GZipDecoder._readHeader (package:archive/src/gzip_decoder.dart:89:27)
#3      GZipDecoder.decodeBuffer (package:archive/src/gzip_decoder.dart:26:5)
#4      GZipDecoder.decodeBytes (package:archive/src/gzip_decoder.dart:17:12)
#5      _WindowsUtils.verifyGzip (package:flutter_tools/src/base/os.dart:294:21)
#6      CachedArtifact._downloadArchive.<anonymous closure> (package:flutter_tools/src/cache.dart:513:20)
#7      CachedArtifact._withDownloadFile (package:flutter_tools/src/cache.dart:545:26)
#8      CachedArtifact._downloadArchive (package:flutter_tools/src/cache.dart:512:12)
#9      CachedArtifact._downloadZippedTarball (package:flutter_tools/src/cache.dart:537:12)
#10     GradleWrapper.updateInner (package:flutter_tools/src/cache.dart:990:12)
#11     CachedArtifact.update (package:flutter_tools/src/cache.dart:462:11)
#12     Cache.updateAll (package:flutter_tools/src/cache.dart:360:24)
#13     FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:595:19)
<asynchronous suspension>
#14     FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:515:33)
<asynchronous suspension>
#15     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:146:29)
#16     _rootRun (dart:async/zone.dart:1126:13)
#17     _CustomZone.run (dart:async/zone.dart:1023:19)
#18     _runZoned (dart:async/zone.dart:1518:10)
#19     runZoned (dart:async/zone.dart:1465:12)
#20     AppContext.run (package:flutter_tools/src/base/context.dart:145:18)
#21     FlutterCommand.run (package:flutter_tools/src/runner/flutter_command.dart:505:20)
#22     CommandRunner.runCommand (package:args/command_runner.dart:197:27)
#23     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:413:21)
<asynchronous suspension>
#24     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:146:29)
#25     _rootRun (dart:async/zone.dart:1126:13)
#26     _CustomZone.run (dart:async/zone.dart:1023:19)
#27     _runZoned (dart:async/zone.dart:1518:10)
#28     runZoned (dart:async/zone.dart:1465:12)
#29     AppContext.run (package:flutter_tools/src/base/context.dart:145:18)
#30     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:364:19)
#31     CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:112:25)
#32     new Future.sync (dart:async/future.dart:224:31)
#33     CommandRunner.run (package:args/command_runner.dart:112:14)
#34     FlutterCommandRunner.run (package:flutter_tools/src/runner/flutter_command_runner.dart:250:18)
#35     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:63:22)
#36     _rootRun (dart:async/zone.dart:1126:13)
#37     _CustomZone.run (dart:async/zone.dart:1023:19)
#38     _runZoned (dart:async/zone.dart:1518:10)
#39     runZoned (dart:async/zone.dart:1502:12)
#40     run.<anonymous closure> (package:flutter_tools/runner.dart:61:18)
<asynchronous suspension>
#41     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:146:29)
#42     _rootRun (dart:async/zone.dart:1126:13)
#43     _CustomZone.run (dart:async/zone.dart:1023:19)
#44     _runZoned (dart:async/zone.dart:1518:10)
#45     runZoned (dart:async/zone.dart:1465:12)
#46     AppContext.run (package:flutter_tools/src/base/context.dart:145:18)
#47     runInContext (package:flutter_tools/src/context_runner.dart:64:24)
#48     run (package:flutter_tools/runner.dart:50:10)
#49     main (package:flutter_tools/executable.dart:65:9)
#50     main (file:///C:/src/flutter/packages/flutter_tools/bin/flutter_tools.dart:8:3)
#51     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:305:32)
#52     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:174:12)
```

## flutter doctor

```
[33m[!][39m Flutter (Channel stable, v1.12.13+hotfix.9, on Microsoft Windows [Version 10.0.18363.778], locale en-US)
    [32m•[39m Flutter version 1.12.13+hotfix.9 at C:\src\flutter
    [32m•[39m Framework revision f139b11009 (3 weeks ago), 2020-03-30 13:57:30 -0700
    [32m•[39m Engine revision af51afceb8
    [32m•[39m Dart version 2.7.2
    [31m✗[39m Downloaded executables cannot execute on host.
      See https://github.com/flutter/flutter/issues/6207 for more information


[32m[✓][39m Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    [32m•[39m Android SDK at \AppData\Local\Android\sdk
    [32m•[39m Android NDK location not configured (optional; useful for native profiling support)
    [32m•[39m Platform android-28, build-tools 28.0.3
    [32m•[39m Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    [32m•[39m Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)
    [32m•[39m All Android licenses accepted.

[32m[✓][39m Android Studio (version 3.5)
    [32m•[39m Android Studio at C:\Program Files\Android\Android Studio
    [32m•[39m Flutter plugin version 42.0.1
    [32m•[39m Dart plugin version 191.8593
    [32m•[39m Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)

[32m[✓][39m VS Code (version 1.44.2)
    [32m•[39m VS Code at\AppData\Local\Programs\Microsoft VS Code
    [32m•[39m Flutter extension version 3.9.1

[33m[!][39m Connected device
    [33m![39m No devices available

[33m![39m Doctor found issues in 2 categories.
```

**Comment by iapicca** [comment]
Hi @1abir 
thank you for your `flutter doctor -v` , 
the error `IndexError: RangeError (index): Index out of range: no indices are valid: 0`
might depend from your code
can you please a reproducible minimal code sample.
Thank you

**Comment by 1abir** [comment]
Hi @iapicca 
thank you for your suggestion.
I tried pulling from git the original and  the stable version, but the same problem continued.
But Alhamdulillah, the problem solved after I downloaded zipped folder for windows and run it. :)
