### ISSUE TITLE
[cocoon] GithubBuildStatusUpdate trying to insert duplicated entries.

### ISSUE THREAD

**Issue by godofredoc** [flutter/flutter#55377]
```
Bad state: GithubBuildStatusUpdate should have no more than one entries on repository flutter/flutter, pr 55350, head a648701f83ffe1d03a7c1c16f17cee5b9e9f98b7
#0      DatastoreService.queryLastStatusUpdate (package:cocoon_service/src/service/datastore.dart:205:9)
<asynchronous suspension>
#1      PushBuildStatusToGithub.get (package:cocoon_service/src/request_handlers/push_build_status_to_github.dart:77:29)
<asynchronous suspension>
#2      RequestHandler.service.<anonymous closure> (package:cocoon_service/src/request_handling/request_handler.dart:46:28)
<asynchronous suspension>
#3      _rootRun (dart:async/zone.dart:1126:13)
#4      _CustomZone.run (dart:async/zone.dart:1023:19)
#5      _runZoned (dart:async/zone.dart:1518:10)
#6      runZoned (dart:async/zone.dart:1465:12)
#7      RequestHandler.service (package:cocoon_service/src/request_handling/request_handler.dart:39:12)
#8      ApiRequestHandler.service.<anonymous closure> (package:cocoon_service/src/request_handling/api_request_handler.dart:139:19)
<asynchronous suspension>
#9      _rootRun (dart:async/zone.dart:1126:13)
#10     _CustomZone.run (dart:async/zone.dart:1023:19)
#11     _runZoned (dart:async/zone.dart:1518:10)
#12     runZoned (dart:async/zone.dart:1465:12)
#13     ApiRequestHandler.service (package:cocoon_service/src/request_handling/api_request_handler.dart:138:11)
<asynchronous suspension>
#14     main.<anonymous closure>.<anonymous closure> (file:///app/bin/server.dart:83:23)
<asynchronous suspension>
#15     runAppEngine.<anonymous closure> (package:appengine/appengine.dart:80:12)
#16     runAppEngine.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:appengine/src/appengine_internal.dart:59:18)
#17     _ServiceScope._fork.<anonymous closure> (package:gcloud/service_scope.dart:209:19)
#18     _rootRun (dart:async/zone.dart:1126:13)
#19     _CustomZone.run (dart:async/zone.dart:1023:19)
#20     _runZoned (dart:async/zone.dart:1518:10)
#21     runZoned (dart:async/zone.dart:1502:12)
#22     _ServiceScope._fork (package:gcloud/service_scope.dart:208:12)
#23     fork (package:gcloud/service_scope.dart:104:30)
#24     runAppEngine.<anonymous closure>.<anonymous closure> (package:appengine/src/appengine_internal.dart:57:9)
#25     AppEngineHttpServer.run.<anonymous closure>.<anonymous closure> (package:appengine/src/server/server.dart:83:16)
#26     _rootRunUnary (dart:async/zone.dart:1134:38)
#27     _CustomZone.runUnary (dart:async/zone.dart:1031:19)
#28     _CustomZone.runUnaryGuarded (dart:async/zone.dart:933:7)
#29     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:338:11)
#30     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:265:7)
#31     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:766:19)
#32     _StreamController._add (dart:async/stream_controller.dart:642:7)
#33     _StreamController.add (dart:async/stream_controller.dart:588:5)
#34     _HttpServer._handleRequest (dart:_http/http_impl.dart:2828:19)
#35     new _HttpConnection.<anonymous closure> (dart:_http/http_impl.dart:2586:19)
#36     _rootRunUnary (dart:async/zone.dart:1134:38)
#37     _CustomZone.runUnary (dart:async/zone.dart:1031:19)
#38     _CustomZone.runUnaryGuarded (dart:async/zone.dart:933:7)
#39     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:338:11)
#40     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:265:7)
#41     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:766:19)
#42     _StreamController._add (dart:async/stream_controller.dart:642:7)
#43     _StreamController.add (dart:async/stream_controller.dart:588:5)
#44     _HttpParser._headersEnd (dart:_http/http_parser.dart:374:19)
#45     _HttpParser._doParse (dart:_http/http_parser.dart:703:15)
#46     _HttpParser._parse (dart:_http/http_parser.dart:320:7)
#47     _HttpParser._onData (dart:_http/http_parser.dart:812:5)
#48     _rootRunUnary (dart:async/zone.dart:1134:38)
#49     _CustomZone.runUnary (dart:async/zone.dart:1031:19)
#50     _CustomZone.runUnaryGuarded (dart:async/zone.dart:933:7)
#51     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:338:11)
#52     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:265:7)
#53     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:766:19)
#54     _StreamController._add (dart:async/stream_controller.dart:642:7)
#55     _StreamController.add (dart:async/stream_controller.dart:588:5)
#56     _Socket._onData (dart:io-patch/socket_patch.dart:1851:41)
#57     _rootRunUnary (dart:async/zone.dart:1138:13)
#58     _CustomZone.runUnary (dart:async/zone.dart:1031:19)
#59     _CustomZone.runUnaryGuarded (dart:async/zone.dart:933:7)
#60     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:338:11)
#61     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:265:7)
#62     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:766:19)
#63     _StreamController._add (dart:async/stream_controller.dart:642:7)
#64     _StreamController.add (dart:async/stream_controller.dart:588:5)
#65     new _RawSocket.<anonymous closure> (dart:io-patch/socket_patch.dart:1399:33)
#66     _NativeSocket.issueReadEvent.issue (dart:io-patch/socket_patch.dart:919:14)
#67     _microtaskLoop (dart:async/schedule_microtask.dart:43:21)
#68     _startMicrotaskLoop (dart:async/schedule_microtask.dart:52:5)
#69     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
#70     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:175:5)
```

**Comment by godofredoc** [comment]
@keyonghan would you mind taking a look, this may be related to the release branches.

**Comment by keyonghan** [comment]
This is not related to release branches, but is weird to happen.

There are two records for `repo: flutter/flutter, pr: 55350, sha: a648701f83ffe1d03a7c1c16f17cee5b9e9f98b7` in datastore, and this is not expected to happen. 

First this api [queries the lastStatusUpdate](https://github.com/flutter/cocoon/blob/master/app_dart/lib/src/request_handlers/push_build_status_to_github.dart#L76) for a `repo, pr, sha` combination. If it exists in datastore, it will return this existing record. Otherwise, it will create a new record. Whenever the status changes, that record will be synchronized in datastore. 

If it returns the existing record, when inserting data back to datastore, it should update old record (based on the unique `id`).
If a new record returns, when inserting data to datastore, it should just create a new record.

For either case, there should not be the case to have two records in the entity with save `repo, pr, sha` combination.

For now, I just removed the duplicate record, and will keep a look at this issue.

**Comment by godofredoc** [comment]
Sounds like a race condition in between the query and the insertion. When this happen again, please do not delete the offending register until we know the root cause.

**Comment by keyonghan** [comment]
It is simply a plain record, without even timestamp.. So deletion of that record doesn't affect we triaging the issue. Also, I have backed-up the old two records before I delete. Copied here if you wanna to take a look too.
![Screen Shot 2020-04-22 at 9 30 26 AM](https://user-images.githubusercontent.com/54558023/80013923-7dd6cc80-8484-11ea-9f92-43b846f7ed92.png)

**Comment by digiter** [comment]
Possible cause that I can think of: a Cocoon backend version has multiple instances, I doubt they have a way to synchronize on the datastore operations. Similarly when we deploy a new version, there might be a race condition between the new version and the old version when we shift traffic.

There might be other possible causes. It's not easy to maintain strong consistency based on what we have at the moment, I'd suggest we change the system to be duplicate tolerant, for example, adding a timestamp to each of the record and always query the latest one.

**Comment by godofredoc** [comment]
Do we use that table to decide whether or not to update github status?

A few questions for brain storming:

* Is there a way to ensure there is a single entry in that model? e.g db constraint of some sort.
* How to automate the release process of the application, is there a GCP tool for this?
* How can we use a staging datastore? do we need a flutter-dashboard-staging?
* How to prevent individuals from pushing versions to the prod instance?

**Comment by keyonghan** [comment]
> Do we use that table to decide whether or not to update github status?
> 
@godofredoc The answer is yes.

@digiter I agree adding timestamp could solve the state error.

**Comment by godofredoc** [comment]
@keyonghan is this obsolete?

**Comment by keyonghan** [comment]
> @keyonghan is this obsolete?

Haven't seen this issue. Closing.
