### ISSUE TITLE
google maps plugin crashes with FlutterJNI detached while detaching

### ISSUE THREAD

**Issue by xster** [flutter/flutter#55406]
We have a similar issue that the app crashes on "app exit" after migrating to v2 embedding. This is after the fix I suppose because previously I got the same error but now I get a different crash message after the patch. The log messages are here: 

```04-16 23:09:19.070 10772 10772 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
04-16 23:09:19.070 10772 10772 E AndroidRuntime: Caused by: java.lang.NullPointerException: Attempt to invoke interface method 'void com.google.maps.api.android.lib6.impl.bp.q()' on a null object reference
04-16 23:09:19.070 10772 10772 E AndroidRuntime: 	at com.google.maps.api.android.lib6.impl.cw.d(:com.google.android.gms.dynamite_mapsdynamite@201216065@20.12.16 (100400-0):1)
04-16 23:09:19.070 10772 10772 E AndroidRuntime: 	at com.google.android.gms.maps.internal.q.a(:com.google.android.gms.dynamite_mapsdynamite@201216065@20.12.16 (100400-0):12)
04-16 23:09:19.070 10772 10772 E AndroidRuntime: 	at ch.onTransact(:com.google.android.gms.dynamite_mapsdynamite@201216065@20.12.16 (100400-0):4)
04-16 23:09:19.070 10772 10772 E AndroidRuntime: 	at android.os.Binder.transact(Binder.java:667)
04-16 23:09:19.070 10772 10772 E AndroidRuntime: 	at com.google.android.aidl.BaseProxy.transactAndReadExceptionReturnVoid(BaseProxy.java:65)
04-16 23:09:19.070 10772 10772 E AndroidRuntime: 	at com.google.android.gms.maps.internal.IMapViewDelegate$Stub$Proxy.onDestroy(IMapViewDelegate.java:218)
04-16 23:09:19.070 10772 10772 E AndroidRuntime: 	at com.google.android.gms.maps.MapView$MapViewDelegate.onDestroy(MapView.java:176)
04-16 23:09:19.070 10772 10772 E AndroidRuntime: 	at com.google.android.gms.dynamic.DeferredLifecycleHelper.onDestroy(DeferredLifecycleHelper.java:410)
04-16 23:09:19.070 10772 10772 E AndroidRuntime: 	at com.google.android.gms.maps.MapView.onDestroy(MapView.java:411)
04-16 23:09:19.070 10772 10772 E AndroidRuntime: 	at io.flutter.plugins.googlemaps.GoogleMapController.dispose(GoogleMapController.java:541)
04-16 23:09:19.070 10772 10772 E AndroidRuntime: 	at io.flutter.plugin.platform.VirtualDisplayController.dispose(VirtualDisplayController.java:163)
04-16 23:09:19.070 10772 10772 E AndroidRuntime: 	at io.flutter.plugin.platform.PlatformViewsController.flushAllViews(PlatformViewsController.java:533)
04-16 23:09:19.070 10772 10772 E AndroidRuntime: 	at io.flutter.plugin.platform.PlatformViewsController.onDetachedFromJNI(PlatformViewsController.java:422)
04-16 23:09:19.070 10772 10772 E AndroidRuntime: 	at io.flutter.embedding.engine.FlutterEngine.destroy(FlutterEngine.java:293)
04-16 23:09:19.070 10772 10772 E AndroidRuntime: 	at io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.onDetach(FlutterActivityAndFragmentDelegate.java:500)
04-16 23:09:19.070 10772 10772 E AndroidRuntime: 	at io.flutter.embedding.android.FlutterFragment.onDetach(FlutterFragment.java:640)
04-16 23:09:19.070 10772 10772 E AndroidRuntime: 	at android.support.v4.app.Fragment.performDetach(Fragment.java:3046)
04-16 23:09:19.070 10772 10772 E AndroidRuntime: 	at android.support.v4.app.FragmentStateManager.detach(FragmentStateManager.java:711)
04-16 23:09:19.070 10772 10772 E AndroidRuntime: 	at android.support.v4.app.FragmentManager.moveToState(FragmentManager.java:1363)
04-16 23:09:19.070 10772 10772 E AndroidRuntime: 	at android.support.v4.app.FragmentManager.moveToState(FragmentManager.java:1417)
04-16 23:09:19.070 10772 10772 E AndroidRuntime: 	at android.support.v4.app.FragmentManager.moveFragmentToExpectedState(FragmentManager.java:1495)
04-16 23:09:19.070 10772 10772 E AndroidRuntime: 	at android.support.v4.app.FragmentManager.moveToState(FragmentManager.java:1561)
04-16 23:09:19.070 10772 10772 E AndroidRuntime: 	at android.support.v4.app.FragmentManager.dispatchStateChange(FragmentManager.java:2805)
04-16 23:09:19.070 10772 10772 E AndroidRuntime: 	at android.support.v4.app.FragmentManager.dispatchDestroy(FragmentManager.java:2789)
04-16 23:09:19.070 10772 10772 E AndroidRuntime: 	at android.support.v4.app.FragmentController.dispatchDestroy(FragmentController.java:334)
04-16 23:09:19.070 10772 10772 E AndroidRuntime: 	at android.support.v4.app.FragmentActivity.onDestroy(FragmentActivity.java:367)
04-16 23:09:19.070 10772 10772 E AndroidRuntime: 	at android.app.Activity.performDestroy(Activity.java:7395)
04-16 23:09:19.070 10772 10772 E AndroidRuntime: 	at android.app.Instrumentation.callActivityOnDestroy(Instrumentation.java:1306)
04-16 23:09:19.070 10772 10772 E AndroidRuntime: 	at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:4443)
04-16 23:09:19.070 10772 10772 E AndroidRuntime: 	... 11 more
```

I suppose this only relates to google map plugin, it hit null exception while trying to destroy the mapview.

_Originally posted by @lidongze91 in https://github.com/flutter/flutter/issues/48063#issuecomment-615384571_

**Comment by xster** [comment]
Pulling comment from #48063

For @lidongze91's issue, I have a suspicious that all these setters for listeners we're setting in https://github.com/flutter/plugins/blob/c2f74efb9daaf22e2f1854f41d7ed35e40a7a5b6/packages/google_maps_flutter/google_maps_flutter/android/src/main/java/io/flutter/plugins/googlemaps/GoogleMapController.java#L207 but that doesn't seem to be removed looks suspicious. 

cc @cyanglaz

**Comment by xster** [comment]
repro is in cl/307458324

**Comment by xster** [comment]
Doh, there's a hiccup reproducing outside google with https://github.com/flutter/flutter/issues/54386. Would have to call the generated registrant in an actual FlutterFragmentActivity subclass.

**Comment by xster** [comment]
Ummm I wasn't able to repro using the maps example app replacing the default FlutterActivity with FlutterFragmentActivity. 

What are the steps specifically? 

It's a full-Flutter app entirely in a FlutterFragmentActivity, you go into a Flutter route that has a maps plugin and it crashes right when you're quitting the entire app right? (since only that would call `android.app.Activity.performDestroy` pointed in the crash stack above).
