### ISSUE TITLE
Exception thrown while running flutter test --coverage

### ISSUE THREAD

**Issue by tesla-nikola** [flutter/flutter#55437]
I was trying to get test coverage generated by running this command:
`flutter test --coverage --no-test-assets --platform chrome --verbose`

```
07:14 +281 ~2: All tests passed!                                                                                                       
[+1636 ms] coverage information collection complete
[  +20 ms] "flutter test" took 4,76,458ms.

#0      throwToolExit (package:flutter_tools/src/base/common.dart:14:3)
#1      TestCommand.runCommand (package:flutter_tools/src/commands/test.dart:275:9)
<asynchronous suspension>
#2      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:722:18)
#3      _rootRunUnary (dart:async/zone.dart:1192:38)
#4      _CustomZone.runUnary (dart:async/zone.dart:1085:19)
#5      _FutureListener.handleValue (dart:async/future_impl.dart:141:18)
#6      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:682:45)
#7      Future._propagateToListeners (dart:async/future_impl.dart:711:32)
#8      Future._completeWithValue (dart:async/future_impl.dart:526:5)
#9      Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:556:7)
#10     _rootRun (dart:async/zone.dart:1184:13)
#11     _CustomZone.run (dart:async/zone.dart:1077:19)
#12     _CustomZone.runGuarded (dart:async/zone.dart:979:7)
#13     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1019:23)
#14     _microtaskLoop (dart:async/schedule_microtask.dart:43:21)
#15     _startMicrotaskLoop (dart:async/schedule_microtask.dart:52:5)
#16     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
#17     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:169:5)
```

Ouput of `flutter doctor -v`

```
Downloading android-arm-profile/darwin-x64 tools...                 1.1s
Downloading android-arm-release/darwin-x64 tools...                 0.8s
Downloading android-arm64-profile/darwin-x64 tools...               1.1s
Downloading android-arm64-release/darwin-x64 tools...               1.0s
Downloading android-x64-profile/darwin-x64 tools...                 0.7s
Downloading android-x64-release/darwin-x64 tools...                 0.9s
[✓] Flutter (Channel beta, v1.17.0, on Mac OS X 10.14.6 18G1012, locale en-IN)
    • Flutter version 1.17.0 at /Users/gogol/Documents/Flutter/flutter
    • Framework revision d3ed9ec945 (2 weeks ago), 2020-04-06 14:07:34 -0700
    • Engine revision c9506cb8e9
    • Dart version 2.8.0 (build 2.8.0-dev.18.0 eea9717938)

[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed instructions).
      If the Android SDK has been installed to a custom location, set ANDROID_SDK_ROOT to that location.
      You may also want to add it to your PATH environment variable.


 
[!] Xcode - develop for iOS and macOS (Xcode 10.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.3, Build version 10G8
    ✗ Flutter requires a minimum Xcode version of 11.0.0.
      Download the latest version or update via the Mac App Store.
    • CocoaPods version 1.8.4

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed instructions).

[✓] VS Code (version 1.44.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.9.1

[✓] Connected device (2 available)
    • Chrome     • chrome     • web-javascript • Google Chrome 81.0.4044.113
    • Web Server • web-server • web-javascript • Flutter Tools
```

**Comment by jonahwilliams** [comment]
We don't support coverage collection with `--platform chrome`. This should be disallowed it the tool

**Comment by tesla-nikola** [comment]
@jonahwilliams 
Is there any other way to gather coverage reports for flutter web app?

**Comment by jonahwilliams** [comment]
What is stopping you from running a regular coverage report?

**Comment by tesla-nikola** [comment]
@jonahwilliams 
Ok ran this command `flutter test --coverage --no-test-assets --verbose`
It spits out this on terminal
```
 +191 -27: Some tests failed.                                                                                                     
[  +25 ms] Deleting /var/folders/4t/b1nbky_91zqcvnnf5jr46vgm0000gn/T/flutter_test_compiler.06thxC...
[   +3 ms] killing pid 3384
[  +46 ms] Deleting /var/folders/4t/b1nbky_91zqcvnnf5jr46vgm0000gn/T/flutter_test_fonts.xa2co2...
[   +7 ms] test package returned with exit code 1
[  +41 ms] coverage information collection complete
[   +3 ms] wrote coverage data to coverage/lcov.info (size=21232)
[  +19 ms] "flutter test" took 2,23,283ms.

#0      throwToolExit (package:flutter_tools/src/base/common.dart:14:3)
#1      TestCommand.runCommand (package:flutter_tools/src/commands/test.dart:280:7)
<asynchronous suspension>
#2      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:722:18)
#3      _rootRunUnary (dart:async/zone.dart:1192:38)
#4      _CustomZone.runUnary (dart:async/zone.dart:1085:19)
#5      _FutureListener.handleValue (dart:async/future_impl.dart:141:18)
#6      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:682:45)
#7      Future._propagateToListeners (dart:async/future_impl.dart:711:32)
#8      Future._completeWithValue (dart:async/future_impl.dart:526:5)
#9      Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:556:7)
#10     _rootRun (dart:async/zone.dart:1184:13)
#11     _CustomZone.run (dart:async/zone.dart:1077:19)
#12     _CustomZone.runGuarded (dart:async/zone.dart:979:7)
#13     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1019:23)
#14     _microtaskLoop (dart:async/schedule_microtask.dart:43:21)
#15     _startMicrotaskLoop (dart:async/schedule_microtask.dart:52:5)
#16     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
#17     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:169:5)
```
and it did generate lcov.info which I was looking for but still in the last step it throws an exception.

**Comment by hunght** [comment]
@jonahwilliams i got the same issue, right now our project can run the coverage checking because  this issue, and we are import dart:html so we cannot run without chrome option, could you suggest for that? thanks

**Comment by picolov** [comment]
@hunght you can do conditional import for the dart:html so in unit test or other cases where it is not avaiable, we can use a mocked class for it, something like :
`
import 'package:..../..../mocked-lib/mocked_dart_html.dart'
    if (dart.library.html) 'dart:html';
`
where mocked_dart_html is the mocked version of dart:html.
also in the same way, you can do conditional export on a class then just import that class

**Comment by yjbanov** [comment]
`flutter test` is designed to be a platform-agnostic test runner that mocks out any platform-specific functionality. If you need to exercise browser API (such as `dart:html` or web plugins) consider using `package:integration_test` or `package:flutter_driver` instead. Having said that, I'm not sure if they support coverage collection (/cc @dnfield @nturgut). Personally, I would try to structure my code such that `flutter test` does not need `dart:html`, and therefore does not need `--platform=chrome`.

**Comment by dnfield** [comment]
See https://github.com/flutter/flutter/issues/65429

**Comment by LuisDavidPadron** [comment]
i see if you have only one platfor cod run, in my example that apply then review your folders if exists ios, web, macos, android. you need delete others folders you don’t use. in my case that solve, and generate file lcov.

**Comment by justincbeck** [comment]
> We don't support coverage collection with `--platform chrome`. This should be disallowed it the tool

Why?

**Comment by Peetee06** [comment]
I'm working on a project where we use `kIsWeb` to have some specific code run only in browsers like `launchUrl`. It would be great to have those lines shown as "covered" in our code coverage tooling.

**Comment by jcairney-UHN** [comment]
For any project using package:web, it suddenly becomes mandatory to do everything with the `--platform chrome` flag on, or the runner throws a barrage of errors related to JS and JS interop.  The fact that debugging and coverage both do not work when running through chrome seems like a big hole in tooling.
