### ISSUE TITLE
"Your device does not support Google Play service, so can not run $app name"

### ISSUE THREAD

**Issue by iyuhang** [flutter/flutter#55444]
In China, Some devices (not have google play service) shows a dialog at the launch, "Your device does not support Google Play service, so can not run $app name$"， but on tap "confirm" , the app can still run. 

(oppo a57, and some huawei mate20 shows this issue)

![image](https://user-images.githubusercontent.com/14176635/80076082-392f5c00-857e-11ea-99f7-ea47179b97e4.png)

```
(base) AnsenMBP-4:fixtime apple$ flutter run --verbose
[  +26 ms] executing: [/Users/apple/Flutter/flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[  +40 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[        ] f139b11009aeb8ed2a3a3aa8b0066e482709dde3
[        ] executing: [/Users/apple/Flutter/flutter/] git describe --match v*.*.* --first-parent --long --tags
[  +21 ms] Exit code 0 from: git describe --match v*.*.* --first-parent --long --tags
[        ] v1.12.13+hotfix.9-0-gf139b1100
[   +8 ms] executing: [/Users/apple/Flutter/flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[  +11 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/stable
[        ] executing: [/Users/apple/Flutter/flutter/] git ls-remote --get-url origin
[  +11 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[  +61 ms] executing: [/Users/apple/Flutter/flutter/] git rev-parse --abbrev-ref HEAD
[  +12 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] stable
[   +7 ms] executing: sw_vers -productName
[  +16 ms] Exit code 0 from: sw_vers -productName
[        ] Mac OS X
[        ] executing: sw_vers -productVersion
[  +14 ms] Exit code 0 from: sw_vers -productVersion
[        ] 10.14.6
[        ] executing: sw_vers -buildVersion
[  +15 ms] Exit code 0 from: sw_vers -buildVersion
[        ] 18G87
[  +30 ms] executing: /usr/bin/xcode-select --print-path
[  +12 ms] Exit code 0 from: /usr/bin/xcode-select --print-path
[        ] /Applications/Xcode.app/Contents/Developer
[   +1 ms] executing: /usr/bin/xcodebuild -version
[ +242 ms] Exit code 0 from: /usr/bin/xcodebuild -version
[   +3 ms] Xcode 11.3.1
           Build version 11C504
[  +69 ms] executing: /Users/apple/Library/Android/sdk/platform-tools/adb devices -l
[   +6 ms] Exit code 0 from: /Users/apple/Library/Android/sdk/platform-tools/adb devices -l
[        ] List of devices attached
           dd13b9d1               device usb:337707008X product:OnePlus7Pro_EEA model:GM1910 device:OnePlus7Pro transport_id:5
           eb48845                device usb:338952192X product:A57 model:OPPO_A57 device:A57 transport_id:3
[  +21 ms] executing: /Users/apple/Flutter/flutter/bin/cache/artifacts/libimobiledevice/idevice_id -h
[  +44 ms] /usr/bin/xcrun simctl list --json devices
[ +117 ms] More than one device connected; please specify a device with the '-d <deviceId>' flag, or use '-d all' to act on all devices.
[   +3 ms] /Users/apple/Library/Android/sdk/platform-tools/adb -s dd13b9d1 shell getprop
[  +82 ms] ro.hardware = qcom
[   +1 ms] /Users/apple/Library/Android/sdk/platform-tools/adb -s eb48845 shell getprop
[  +72 ms] ro.hardware = qcom
[   +2 ms] GM1910   • dd13b9d1 • android-arm64 • Android 10 (API 29)
[   +1 ms] OPPO A57 • eb48845  • android-arm64 • Android 6.0.1 (API 23)
[  +14 ms] "flutter run" took 793ms.

#0      throwToolExit (package:flutter_tools/src/base/common.dart:28:3)
#1      RunCommand.validateCommand (package:flutter_tools/src/commands/run.dart:289:7)
<asynchronous suspension>
#2      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:590:11)
#3      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:515:33)
<asynchronous suspension>
#4      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:146:29)
#5      _rootRun (dart:async/zone.dart:1126:13)
#6      _CustomZone.run (dart:async/zone.dart:1023:19)
#7      _runZoned (dart:async/zone.dart:1518:10)
#8      runZoned (dart:async/zone.dart:1465:12)
#9      AppContext.run (package:flutter_tools/src/base/context.dart:145:18)
#10     FlutterCommand.run (package:flutter_tools/src/runner/flutter_command.dart:505:20)
#11     CommandRunner.runCommand (package:args/command_runner.dart:197:27)
#12     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:413:21)
<asynchronous suspension>
#13     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:146:29)
#14     _rootRun (dart:async/zone.dart:1126:13)
#15     _CustomZone.run (dart:async/zone.dart:1023:19)
#16     _runZoned (dart:async/zone.dart:1518:10)
#17     runZoned (dart:async/zone.dart:1465:12)
#18     AppContext.run (package:flutter_tools/src/base/context.dart:145:18)
#19     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:364:19)
#20     CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:112:25)
#21     new Future.sync (dart:async/future.dart:224:31)
#22     CommandRunner.run (package:args/command_runner.dart:112:14)
#23     FlutterCommandRunner.run (package:flutter_tools/src/runner/flutter_command_runner.dart:250:18)
#24     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:63:22)
#25     _rootRun (dart:async/zone.dart:1126:13)
#26     _CustomZone.run (dart:async/zone.dart:1023:19)
#27     _runZoned (dart:async/zone.dart:1518:10)
#28     runZoned (dart:async/zone.dart:1502:12)
#29     run.<anonymous closure> (package:flutter_tools/runner.dart:61:18)
<asynchronous suspension>
#30     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:146:29)
#31     _rootRun (dart:async/zone.dart:1126:13)
#32     _CustomZone.run (dart:async/zone.dart:1023:19)
#33     _runZoned (dart:async/zone.dart:1518:10)
#34     runZoned (dart:async/zone.dart:1465:12)
#35     AppContext.run (package:flutter_tools/src/base/context.dart:145:18)
#36     runInContext (package:flutter_tools/src/context_runner.dart:64:24)
#37     run (package:flutter_tools/runner.dart:50:10)
#38     main (package:flutter_tools/executable.dart:65:9)
#39     main (file:///Users/apple/Flutter/flutter/packages/flutter_tools/bin/flutter_tools.dart:8:3)
#40     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:305:32)
#41     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:174:12)
```

```
   info • The value of the local variable 'permissions' isn't used • lib/common/functions.dart:94:54 • unused_local_variable
   info • Unused import: 'package:jmessage_flutter/jmessage_flutter.dart' • lib/screens/chat/actionRight.dart:13:8 • unused_import
   info • Unused import: 'package:uuid/uuid.dart' • lib/screens/chat/chat.dart:30:8 • unused_import
   info • The value of the local variable 'progress' isn't used • lib/screens/chat/chat.dart:301:11 • unused_local_variable
   info • The value of the local variable 'message' isn't used • lib/screens/chat/chat.dart:302:21 • unused_local_variable
   info • The value of the local variable 'extra' isn't used • lib/screens/chat/chat.dart:533:13 • unused_local_variable
   info • Duplicate import • lib/screens/chat/dialog.dart:4:8 • duplicate_import
   info • Unused import: 'package:fixtime/screens/chat/sender.dart' • lib/screens/chat/functions.dart:12:8 • unused_import
   info • Unused import: 'package:fixtime/screens/chat/conversations.dart' • lib/screens/chat/functions.dart:13:8 • unused_import
   info • Unused import: 'package:tencent_im_plugin/enums/message_node_type.dart' • lib/screens/chat/functions.dart:28:8 • unused_import
   info • The value of the local variable 'matchedMessageNode' isn't used • lib/screens/chat/functions.dart:257:28 • unused_local_variable
   info • Unused import: 'package:fixtime/common/colors.dart' • lib/screens/chat/homeFunctions.dart:2:8 • unused_import
   info • Unused import: 'package:fixtime/common/CWidgets.dart' • lib/screens/chat/homeFunctions.dart:16:8 • unused_import
   info • Unused import: 'package:fixtime/common/CWidgets.dart' • lib/screens/chat/messsages.dart:5:8 • unused_import
   info • Unused import: 'package:tencent_im_plugin/enums/log_print_level.dart' • lib/screens/chat/messsages.dart:23:8 • unused_import
   info • Unused import: 'package:fixtime/screens/chat/conversations.dart' • lib/screens/chat/sender.dart:10:8 • unused_import
   info • The value of the local variable 'value' isn't used • lib/screens/chat/utils.dart:285:27 • unused_local_variable
   info • Unused import: 'package:fixtime/common/colors.dart' • lib/screens/contents/card.dart:1:8 • unused_import
   info • Unused import: 'package:fixtime/common/colors.dart' • lib/screens/contents/card51.dart:3:8 • unused_import
   info • Unused import: 'package:fixtime/common/CWidgets.dart' • lib/screens/contents/card51.dart:13:8 • unused_import
   info • Unused import: 'package:fixtime/common/colors.dart' • lib/screens/contents/contentCard.dart:3:8 • unused_import
   info • Unused import: 'package:fixtime/common/colors.dart' • lib/screens/contents/feed.dart:13:8 • unused_import
   info • Unused import: 'package:fixtime/common/colors.dart' • lib/screens/contents/feeds.dart:5:8 • unused_import
   info • 'loadingChild' is deprecated and shouldn't be used. Use loadingBuilder instead • lib/screens/contents/imagePreview.dart:145:33 • deprecated_member_use
   info • 'loadingChild' is deprecated and shouldn't be used. Use loadingBuilder instead • lib/screens/contents/imagePreview.dart:159:37 • deprecated_member_use
   info • 'loadingChild' is deprecated and shouldn't be used. Use loadingBuilder instead • lib/screens/contents/imagePreview.dart:179:27 • deprecated_member_use
   info • Unused import: 'package:flutter_icons/flutter_icons.dart' • lib/screens/home/pick/pickone.dart:13:8 • unused_import
   info • Unused import: 'package:fixtime/screens/chat/models/enums.dart' • lib/screens/home/pick/utils.dart:9:8 • unused_import
   info • Unused import: 'package:fixtime/screens/contents/sendNotification.dart' • lib/screens/home/pick/utils.dart:12:8 • unused_import
   info • The declaration '_audioInit' isn't referenced • lib/screens/home/realtimePair/actionRight.dart:60:3 • unused_element
   info • Unused import: 'package:fixtime/screens/chat/sender.dart' • lib/screens/home/realtimePair/rtp.dart:12:8 • unused_import
   info • Unused import: 'package:fixtime/common/colors.dart' • lib/screens/home/realtimePair/titles.dart:2:8 • unused_import
   info • Unused import: 'package:jmessage_flutter/jmessage_flutter.dart' • lib/screens/home/realtimePair/utils.dart:16:8 • unused_import
   info • Unused import: 'package:tencent_im_plugin/entity/session_entity.dart' • lib/screens/home/tabbar.dart:17:8 • unused_import
   info • Unused import: 'package:tencent_im_plugin/tencent_im_plugin.dart' • lib/screens/home/tabbar.dart:18:8 • unused_import
   info • Unused import: 'package:fixtime/common/colors.dart' • lib/screens/home/utils/search.dart:11:8 • unused_import
   info • The declaration '_loginWx' isn't referenced • lib/screens/login/login.dart:67:3 • unused_element
   info • Unused import: 'package:fixtime/common/colors.dart' • lib/screens/login/verifyCode.dart:4:8 • unused_import
   info • Unused import: 'package:fixtime/common/colors.dart' • lib/screens/login/virtualavatar.dart:2:8 • unused_import
   info • Unused import: 'package:fixtime/common/colors.dart' • lib/screens/personal/edit.dart:1:8 • unused_import
   info • The value of the local variable 'pairPreferModel' isn't used • lib/screens/personal/edit.dart:32:21 • unused_local_variable
   info • The value of the local variable 'userAccountModel' isn't used • lib/screens/personal/personalPage/userPage.dart:155:22 • unused_local_variable
   info • The value of the field '_imageHeight' isn't used • lib/screens/personal/realPerson/realPersonVerify.dart:48:7 • unused_field
   info • The value of the field '_imageWidth' isn't used • lib/screens/personal/realPerson/realPersonVerify.dart:49:7 • unused_field
   info • The value of the local variable 'startTime' isn't used • lib/screens/personal/realPerson/realPersonVerify.dart:102:15 • unused_local_variable
   info • The value of the local variable 'endTime' isn't used • lib/screens/personal/realPerson/realPersonVerify.dart:116:17 • unused_local_variable
   info • Unused import: 'package:fixtime/screens/login/detailUserInfo.dart' • lib/screens/personal/realPerson/utils.dart:4:8 • unused_import
   info • Unused import: 'package:fixtime/screens/chat/conversations.dart' • lib/screens/personal/relations.dart:6:8 • unused_import
   info • Unused import: 'package:shared_preferences/shared_preferences.dart' • lib/screens/personal/widgets.dart:23:8 • unused_import
   info • Unused import: 'package:fixtime/screens/home/utils/rtm.dart' • lib/screens/settings/feedback.dart:4:8 • unused_import
   info • Unused import: 'package:fixtime/common/colors.dart' • lib/screens/settings/freezed.dart:1:8 • unused_import
   info • Unused import: 'package:fixtime/common/colors.dart' • lib/screens/settings/set.dart:1:8 • unused_import
   info • Unused import: 'package:fixtime/screens/home/utils/rtm.dart' • lib/screens/settings/set.dart:3:8 • unused_import
   info • The value of the local variable 'jmessage' isn't used • lib/screens/settings/settings.dart:27:21 • unused_local_variable
```

```
Flutter (Channel stable, v1.12.13+hotfix.9, on Mac OS X 10.14.6 18G87, locale en-US)
    • Flutter version 1.12.13+hotfix.9 at /Users/apple/Flutter/flutter
    • Framework revision f139b11009 (3 weeks ago), 2020-03-30 13:57:30 -0700
    • Engine revision af51afceb8
    • Dart version 2.7.2
```

</details>

**Comment by TahaTesser** [comment]
Hi @iyuhang 
Does app depends on Firebase or Google Play Services?
Can you please post your `pubspec.yaml`?

**Comment by iyuhang** [comment]
pubspec.yaml

```

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.2.3+82

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  fluwx: ^1.2.1
  dio: ^3.0.9
  permission_handler: ^4.4.0
  shared_preferences: ^0.5.6+3
  flutter_swiper: ^1.1.6
  crypto: ^2.0.6
  camera: ^0.5.7
  path_provider: ^1.0.0
  path: ^1.6.2
  flutter_native_image:
    git: https://github.com/btastic/flutter_native_image.git
  location: ^2.3.5
  uuid: ^2.0.1
  jpush_flutter: 
    git:
      url: git://github.com/jpush/jpush-flutter-plugin.git
      ref: master
  jmessage_flutter: 
    git:
      url: git://github.com/jpush/jmessage-flutter-plugin.git
      ref: master
  latlong: ^0.6.1
  provider: ^3.0.0
  json_annotation: ^3.0.1
  url_launcher: ^5.0.3
  flutter_datetime_picker: ^1.3.1
  # flutter_umplus: ^0.0.1
  umeng_analytics_plugin: ^1.0.2
  package_info: ^0.4.0
  audioplayers: ^0.13.5
  flare_flutter: ^1.8.3
  multi_image_picker: ^4.6.6+rc.1
  photo_view: ^0.9.0
  flutter_icons: ^1.0.0
  pull_to_refresh: ^1.5.7
  device_info: ^0.4.1+4
  image_downloader: ^0.19.1
  agora_rtm: ^0.9.10
  # sqflite: ^1.2.0
  app_settings: ^3.0.0
  cached_network_image: ^2.0.0-rc.1
  extended_image: ^0.7.1
  characters: ^0.5.0
  flutter_slidable: ^0.5.4
  in_app_purchase: ^0.3.1+1
  # flutter_inapp_purchase: ^2.1.0
  city_pickers: ^0.1.30
  flutter_rounded_progress_bar: ^0.1.2
  percent_indicator: ^2.1.1+1
  tflite: 
    git:
      url: git://github.com/iyuhang/flutter_tflite.git
      ref: master
  flutter_xlider: ^3.1.1
  country_code_picker: 
    git:
      url: https://github.com/iyuhang/CountryCodePicker.git
      ref: master
  flutter_secure_storage: ^3.3.1+1
  # flutter_dotenv: ^2.1.0
  vibration: ^1.2.4
  # http: ^0.12.0+4
  tencent_im_plugin: 
    # path: plugins/tencent_im_plugin
    # ^0.2.24
    git:
      url: https://gitee.com/yabeenet/FlutterTencentImPlugin.git
      ref: master
    # git:
    #   url: https://github.com/iyuhang/FlutterTencentImPlugin.git
    #   ref: master
  # flutter_sound: ^3.1.5
  sunrise_sunset: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.0.0
  json_serializable: ^3.2.5
  flutter_launcher_icons: ^0.7.4
  flutter_localizations:
    sdk: flutter

# flutter packages pub run build_runner build

flutter_icons:
  android: true
  ios: true
  image_path: "images/launch_logo.png"

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
   - images/uploadPicIcon.png
   - images/notSupportMedia.png
   - images/comment_icon.png
   - images/anotherMe.png
   - images/heart_btn.png
   - images/congratulations.png
   - images/map.png
   - images/dislike_btn.png
   - images/loading.flr
   - images/wechatpay.png
   - images/credit_indicator.png
   - images/credit_indicator_dark.png
   - images/woman_facepalming.png
   - images/man_facepalming.png
   - images/placeholder.png
   - images/superlike_btn.png
   - images/like_btn.png

   - assets/ssd_mobilenet.tflite
   - assets/ssd_mobilenet.txt


  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
```

gradle

```
buildscript {
    ext.kotlin_version = '1.3.50'
    repositories {
        google()
        jcenter()
    }

    dependencies {
        classpath 'com.android.tools.build:gradle:3.3.2'
        classpath 'com.google.gms:google-services:4.2.0'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
    }
}

allprojects {
    repositories {
        google()
        jcenter()
    }
}

rootProject.buildDir = '../build'
subprojects {
    project.buildDir = "${rootProject.buildDir}/${project.name}"
}
subprojects {
    project.evaluationDependsOn(':app')
}

subprojects {
    project.configurations.all {
        resolutionStrategy.eachDependency { details ->
            if (details.requested.group == 'androidx.core' &&
                    !details.requested.name.contains('androidx')) {
                details.useVersion "1.0.1"
            }
        }
    }
}

task clean(type: Delete) {
    delete rootProject.buildDir
}
```

**Comment by iyuhang** [comment]
I delete this line 
` classpath 'com.google.gms:google-services:4.2.0'`
while the issue still exist

**Comment by iyuhang** [comment]
@TahaTesser

**Comment by TahaTesser** [comment]
Hi @iyuhang 
Please make you also delete `apply plugin: 'com.google.gms.google-services'` from `build.gradle` in app folder and remove any firebase/google plays services dependencies

**Comment by iyuhang** [comment]
Yes, I deleted all "com.google.gms.google-services" both in build.gradle and /app/build.gradle , and there is no firebase/google plays services in pubspec.yaml, while I am not sure any plugins have this dependencies. How can I fint out that?

**Comment by TahaTesser** [comment]
Hi @iyuhang 
Can you try a new project and see if the issue persist?

**Comment by iyuhang** [comment]
Hi @TahaTesser 
Okay, there is no this issue on a new project
so, this may be triggered by the plugins I import?

**Comment by TahaTesser** [comment]
Hi @iyuhang 
That's probably it, i recommend to switch all your code to new project 

Closing, as this isn't an issue with Flutter itself,
if you disagree please write in the comments and I will reopen it 
Thank you

**Comment by 1996SEJR** [comment]
I have the same problem when using the https://pub.dev/packages/location plugin on a huawei p40 with huawei mobile services.
@iyuhang Maybe you found a solution?
