### ISSUE TITLE
error during 'flutter doctor --androids-licenses'

### ISSUE THREAD

**Issue by GrasshopperBears** [flutter/flutter#55478]
Flutter crash report; please file at https://github.com/flutter/flutter/issues.

## command

flutter doctor --android-licenses

## exception

FileSystemException: FileSystemException: writeFrom failed, path = '' (OS Error: OS Error 16389, errno = 16389)

```
#0      _RandomAccessFile.writeFromSync (dart:io/file_impl.dart:881:7)
#1      _StdConsumer.addStream.<anonymous closure> (dart:io/stdio.dart:310:15)
#2      _rootRunUnary (dart:async/zone.dart:1134:38)
#3      _CustomZone.runUnary (dart:async/zone.dart:1031:19)
#4      _CustomZone.runUnaryGuarded (dart:async/zone.dart:933:7)
#5      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:338:11)
#6      _BufferingStreamSubscription._add (dart:async/stream_impl.dart:265:7)
#7      _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:766:19)
#8      _StreamController._add (dart:async/stream_controller.dart:642:7)
#9      _StreamController.add (dart:async/stream_controller.dart:588:5)
#10     _Socket._onData (dart:io-patch/socket_patch.dart:1851:41)
#11     _rootRunUnary (dart:async/zone.dart:1138:13)
#12     _CustomZone.runUnary (dart:async/zone.dart:1031:19)
#13     _CustomZone.runUnaryGuarded (dart:async/zone.dart:933:7)
#14     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:338:11)
#15     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:265:7)
#16     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:766:19)
#17     _StreamController._add (dart:async/stream_controller.dart:642:7)
#18     _StreamController.add (dart:async/stream_controller.dart:588:5)
#19     new _RawSocket.<anonymous closure> (dart:io-patch/socket_patch.dart:1399:33)
#20     _NativeSocket.issueReadEvent.issue (dart:io-patch/socket_patch.dart:919:14)
#21     _microtaskLoop (dart:async/schedule_microtask.dart:43:21)
#22     _startMicrotaskLoop (dart:async/schedule_microtask.dart:52:5)
#23     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
#24     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:175:5)
```

## flutter doctor

```
[32m[✓][39m Flutter (Channel stable, v1.12.13+hotfix.9, on Microsoft Windows [Version 10.0.18363.778], locale ko-KR)
    [32m•[39m Flutter version 1.12.13+hotfix.9 at C:\Users\Jinwoo\Jinwoo\Programming\flutter
    [32m•[39m Framework revision f139b11009 (3 weeks ago), 2020-03-30 13:57:30 -0700
    [32m•[39m Engine revision af51afceb8
    [32m•[39m Dart version 2.7.2

[33m[!][39m Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    [32m•[39m Android SDK at C:\Users\Jinwoo\AppData\Local\Android\sdk
    [32m•[39m Android NDK location not configured (optional; useful for native profiling support)
    [32m•[39m Platform android-29, build-tools 29.0.3
    [32m•[39m Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    [32m•[39m Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)
    [31m✗[39m Android license status unknown.
      Try re-installing or updating your Android SDK Manager.
      See https://developer.android.com/studio/#downloads or visit https://flutter.dev/setup/#android-setup for detailed
      instructions.

[32m[✓][39m Android Studio (version 3.6)
    [32m•[39m Android Studio at C:\Program Files\Android\Android Studio
    [32m•[39m Flutter plugin version 45.1.1
    [32m•[39m Dart plugin version 192.7761
    [32m•[39m Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)

[33m[!][39m VS Code, 64-bit edition (version 1.44.1)
    [32m•[39m VS Code at C:\Program Files\Microsoft VS Code
    [31m✗[39m Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[32m[✓][39m Connected device (1 available)
    [32m•[39m SM J730K • 5200e81ebc9a64d9 • android-arm • Android 9 (API 28)

[33m![39m Doctor found issues in 2 categories.
```

**Comment by jonahwilliams** [comment]
The error code (0x4005) translates to DMLERR_EXECACKTIMEOUT (https://docs.microsoft.com/en-us/windows/win32/api/ddeml/nf-ddeml-ddegetlasterror)

"A request for a synchronous execute transaction has timed out"

Unfortunately from the stack trace its difficult to tell where it is coming from
