### ISSUE TITLE
[CanvasKit]: NetworkImage causes a binding error when used with CanvasKit

### ISSUE THREAD

**Issue by mjohnsullivan** [flutter/flutter#55476]
When we use NetworkImage in CanvasKit, the following issue occurs:

```bash
[Error]:
BindingError: Cannot pass "[object HTMLImageElement]" as a sk_sp<SkImage>
js_primitives.dart:49 [Trace]:
BindingError: Cannot pass "[object HTMLImageElement]" as a sk_sp<SkImage>
    at BindingError.<anonymous> (https://unpkg.com/canvaskit-wasm@0.14.0/bin/canvaskit.js:121:225)
    at new BindingError (eval at Fb (https://unpkg.com/canvaskit-wasm@0.14.0/bin/canvaskit.js:121:33), <anonymous>:4:34)
    at K (https://unpkg.com/canvaskit-wasm@0.14.0/bin/canvaskit.js:123:249)
    at nc.fc [as toWireType] (https://unpkg.com/canvaskit-wasm@0.14.0/bin/canvaskit.js:130:156)
    at SkCanvas$drawImageRect [as drawImageRect] (eval at uc (https://unpkg.com/canvaskit-wasm@0.14.0/bin/canvaskit.js:137:242), <anonymous>:9:26)
    at fO.ac (http://localhost:8000/main.dart.js:31909:19)
    at YW.nQ (http://localhost:8000/main.dart.js:22334:31)
    at Object.aCi (http://localhost:8000/main.dart.js:10106:9)
    at Id.ad5 (http://localhost:8000/main.dart.js:39387:3)
    at aiW.a3O (http://localhost:8000/main.dart.js:39224:20)
```

Flutter is on master:

```console
[✓] Flutter (Channel master, v1.18.0-7.0.pre.47, on Mac OS X 10.15.4 19E287, locale en-US)
[✓] Chrome - develop for the web
```

**Comment by iapicca** [comment]
Hi @mjohnsullivan 
could you please provide a reproducible minimal code sample.
Thank you

**Comment by Mravuri96** [comment]
> When we use NetworkImage in CanvasKit, the following issue occurs:
> 
> ```shell
> [Error]:
> BindingError: Cannot pass "[object HTMLImageElement]" as a sk_sp<SkImage>
> js_primitives.dart:49 [Trace]:
> BindingError: Cannot pass "[object HTMLImageElement]" as a sk_sp<SkImage>
>     at BindingError.<anonymous> (https://unpkg.com/canvaskit-wasm@0.14.0/bin/canvaskit.js:121:225)
>     at new BindingError (eval at Fb (https://unpkg.com/canvaskit-wasm@0.14.0/bin/canvaskit.js:121:33), <anonymous>:4:34)
>     at K (https://unpkg.com/canvaskit-wasm@0.14.0/bin/canvaskit.js:123:249)
>     at nc.fc [as toWireType] (https://unpkg.com/canvaskit-wasm@0.14.0/bin/canvaskit.js:130:156)
>     at SkCanvas$drawImageRect [as drawImageRect] (eval at uc (https://unpkg.com/canvaskit-wasm@0.14.0/bin/canvaskit.js:137:242), <anonymous>:9:26)
>     at fO.ac (http://localhost:8000/main.dart.js:31909:19)
>     at YW.nQ (http://localhost:8000/main.dart.js:22334:31)
>     at Object.aCi (http://localhost:8000/main.dart.js:10106:9)
>     at Id.ad5 (http://localhost:8000/main.dart.js:39387:3)
>     at aiW.a3O (http://localhost:8000/main.dart.js:39224:20)
> ```
> 
> Flutter is on master:
> 
> ```
> [✓] Flutter (Channel master, v1.18.0-7.0.pre.47, on Mac OS X 10.15.4 19E287, locale en-US)
> [✓] Chrome - develop for the web
> ```

Temporary fix but, I was able to fix it by using the Image.memory as it seems to be working on canvskit.
```dart
FutureBuilder(
  future: Dio()
      .get<Uint8List>(
        'https://images.kiwi.com/airlines/32/${widget.data.elementAt(index).airlines[i]}.png',
        options: Options(
          responseType: ResponseType.bytes,
          followRedirects: true,
        ),
      )
      .then((value) => value.data),
  builder: (context, snapshot) {
    return snapshot.connectionState ==
                ConnectionState.done &&
            snapshot.hasData
        ? Image.memory(
            snapshot.data as Uint8List,
            height: 32,
            width: 32,
          )
        : const SizedBox.shrink();
  },
),
```

**Comment by nikssj** [comment]
Any updates for this?

**Comment by iapicca** [comment]
testing the code below with the latest master running
`flutter run -d chrome --dart-define=FLUTTER_WEB_USE_SKIA=true`

<details><summary>code</summary>

```dart
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) => MaterialApp(
        home: Material(
          child: Center(
            child: CircleAvatar(
              backgroundImage: NetworkImage(
                  'https://flutter.dev/assets/flutter-lockup-1caf6476beed76adec3c477586da54de6b552b2f42108ec5bc68dc63bae2df75.png'),
            ),
          ),
        ),
      );
}

```

</details>

<details><summary>logs</summary>

```bash
🔥  To hot restart changes while running, press "r" or "R".
For a more detailed help message, press "h". To quit, press "q".
Cannot find native JavaScript type (CanvasKit) for type check
Cannot find native JavaScript type (SkParagraph) for type check
Cannot find native JavaScript type (SkMaskFilter) for type check
Cannot find native JavaScript type (SkParagraph) for type check
══╡ EXCEPTION CAUGHT BY RENDERING LIBRARY ╞═════════════════════════════════════════════════════════
The following TypeErrorImpl was thrown during paint():
Expected a value of type 'CkImage', but got one of type 'HtmlImage'

The relevant error-causing widget was:
  CircleAvatar file:///Users/nevercode/Desktop/projects/master/lib/main.dart:10:20

When the exception was thrown, this was the stack:
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 212:49      throw_
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 60:3        castError
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/operations.dart 442:10  cast
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/classes.dart 557:14     as_C
lib/_engine/engine/compositor/canvas.dart 118:35                                  drawImageRect
lib/_engine/engine/compositor/canvas_kit_canvas.dart 265:5                        [_drawImageRect]
lib/_engine/engine/compositor/canvas_kit_canvas.dart 260:5                        drawImageRect
packages/flutter/src/painting/decoration_image.dart 566:13                        paintImage
packages/flutter/src/painting/decoration_image.dart 277:5                         paint
packages/flutter/src/painting/box_decoration.dart 465:19                          [_paintBackgroundImage]
packages/flutter/src/painting/box_decoration.dart 483:5                           paint
packages/flutter/src/rendering/proxy_box.dart 2077:16                             paint
packages/flutter/src/rendering/object.dart 2307:7                                 [_paintWithContext]
packages/flutter/src/rendering/object.dart 191:12                                 paintChild
packages/flutter/src/rendering/proxy_box.dart 133:14                              paint
packages/flutter/src/rendering/object.dart 2307:7                                 [_paintWithContext]
packages/flutter/src/rendering/object.dart 191:12                                 paintChild
packages/flutter/src/rendering/shifted_box.dart 72:14                             paint
packages/flutter/src/rendering/object.dart 2307:7                                 [_paintWithContext]
packages/flutter/src/rendering/object.dart 191:12                                 paintChild
packages/flutter/src/rendering/proxy_box.dart 133:14                              paint
packages/flutter/src/material/material.dart 555:11                                paint
packages/flutter/src/rendering/object.dart 2307:7                                 [_paintWithContext]
packages/flutter/src/rendering/object.dart 191:12                                 paintChild
packages/flutter/src/rendering/proxy_box.dart 133:14                              paint
packages/flutter/src/rendering/object.dart 398:12                                 pushLayer
packages/flutter/src/rendering/proxy_box.dart 1856:14                             paint
packages/flutter/src/rendering/object.dart 2307:7                                 [_paintWithContext]
packages/flutter/src/rendering/object.dart 191:12                                 paintChild
packages/flutter/src/rendering/proxy_box.dart 133:14                              paint
packages/flutter/src/rendering/object.dart 2307:7                                 [_paintWithContext]
packages/flutter/src/rendering/object.dart 191:12                                 paintChild
packages/flutter/src/rendering/proxy_box.dart 133:14                              paint
packages/flutter/src/rendering/object.dart 2307:7                                 [_paintWithContext]
packages/flutter/src/rendering/object.dart 142:10                                 _repaintCompositedChild
packages/flutter/src/rendering/object.dart 102:5                                  repaintCompositedChild
packages/flutter/src/rendering/object.dart 989:29                                 flushPaint
packages/flutter/src/rendering/binding.dart 405:19                                drawFrame
packages/flutter/src/widgets/binding.dart 881:13                                  drawFrame
packages/flutter/src/rendering/binding.dart 286:5                                 [_handlePersistentFrameCallback]
packages/flutter/src/scheduler/binding.dart 1114:15                               [_invokeFrameCallback]
packages/flutter/src/scheduler/binding.dart 1053:9                                handleDrawFrame
packages/flutter/src/scheduler/binding.dart 969:5                                 [_handleDrawFrame]
dart-sdk/lib/async/zone.dart 1190:13                                              _rootRun
dart-sdk/lib/async/zone.dart 1375:7                                               runGuarded
lib/_engine/engine/window.dart 758:9                                              _invoke
lib/_engine/engine/window.dart 356:5                                              invokeOnDrawFrame
lib/_engine/engine.dart 227:18                                                    <fn>
dart-sdk/lib/async/zone.dart 1206:13                                              _rootRunUnary
dart-sdk/lib/async/zone.dart 1100:19                                              runUnary
dart-sdk/lib/async/zone.dart 1005:7                                               runUnaryGuarded
dart-sdk/lib/async/zone.dart 1042:26                                              <fn>

The following RenderObject was being processed when the exception was fired: RenderDecoratedBox#97778:
  creator: DecoratedBox ← ConstrainedBox ← Container ← AnimatedContainer ← CircleAvatar ← Center ←
    DefaultTextStyle ← AnimatedDefaultTextStyle ← _InkFeatures-[GlobalKey#7b8b5 ink renderer] ←
    NotificationListener<LayoutChangedNotification> ← PhysicalModel ← AnimatedPhysicalModel ← ⋯
  parentData: <none> (can use size)
  constraints: BoxConstraints(w=40.0, h=40.0)
  size: Size(40.0, 40.0)
  decoration: BoxDecoration:
    color: Color(0xff1976d2)
    image:
      DecorationImage(NetworkImage("https://flutter.dev/assets/flutter-lockup-1caf6476beed76adec3c477586da54de6b552b2f42108ec5bc68dc63bae2df75.png",
      scale: 1), BoxFit.cover, center, scale: 1)
    shape: circle
  configuration: ImageConfiguration(bundle: PlatformAssetBundle#afaa8(), devicePixelRatio: 1.0,
    locale: en_US, textDirection: TextDirection.ltr, platform: macOS)
This RenderObject has no descendants.
════════════════════════════════════════════════════════════════════════════════════════════════════
Cannot find native JavaScript type (SkMaskFilter) for type check

Application finished.
```

</details>

<details><summary>doctor</summary>

```console
[✓] Flutter (Channel master, 1.21.0-6.0.pre.129, on Mac OS X 10.15.5 19F101, locale en-GB)
    • Flutter version 1.21.0-6.0.pre.129 at /Users/nevercode/development/flutter_master
    • Framework revision 30aef0a3b9 (10 hours ago), 2020-07-30 14:20:21 -0700
    • Engine revision a9910e409c
    • Dart version 2.10.0 (build 2.10.0-1.0.dev 24c7666def)


[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/nevercode/Library/Android/sdk
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.5, Build version 11E608c
    • CocoaPods version 1.9.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 46.0.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] VS Code
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.12.2

[✓] Connected device (3 available)
    • macOS (desktop)  • macos      • darwin-x64     • Mac OS X 10.15.5 19F101
    • Web Server (web) • web-server • web-javascript • Flutter Tools
    • Chrome (web)     • chrome     • web-javascript • Google Chrome 84.0.4147.105

• No issues found!
```

</details>


this issue appear to be a duplicate of https://github.com/flutter/flutter/issues/49725
not de-duping since the aforementioned issue has lower priority

**Comment by ferhatb** [comment]
This is fixed now. Even if user loads cross domain and server rejects, you get a proper error message now.

**Comment by Elemenopeee** [comment]
If someone is still looking for a workaround, changing CanvasKit to Html is a potential solution ->

https://flutter.dev/docs/development/tools/web-renderers
