### ISSUE TITLE
Gradle task assembleDebug failed with exit code 1

### ISSUE THREAD

**Issue by huzaifasaeed** [flutter/flutter#55501]
## flutter run --verbose
```
[  +40 ms] executing: [C:\src\flutter\] git -c log.showSignature=false log -n 1 --pretty=format:%H
[  +84 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[   +1 ms] 0b8abb4724aa590dd0f429683339b1e045a1594d
[   +1 ms] executing: [C:\src\flutter\] git describe --match v*.*.* --first-parent --long --tags
[  +64 ms] Exit code 0 from: git describe --match v*.*.* --first-parent --long --tags
[        ] v1.12.13+hotfix.8-0-g0b8abb472
[  +11 ms] executing: [C:\src\flutter\] git rev-parse --abbrev-ref --symbolic @{u}
[  +61 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/stable
[        ] executing: [C:\src\flutter\] git ls-remote --get-url origin
[  +67 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[ +114 ms] executing: [C:\src\flutter\] git rev-parse --abbrev-ref HEAD
[  +70 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] stable
[ +163 ms] executing: C:\Program Files (x86)\Android\android-sdk\platform-tools\adb.exe devices -l
[  +36 ms] Exit code 0 from: C:\Program Files (x86)\Android\android-sdk\platform-tools\adb.exe devices -l
[   +1 ms] List of devices attached
           ZY322MF777             device product:evert_n model:moto_g_6__plus device:evert_n transport_id:1     
[  +23 ms] C:\Program Files (x86)\Android\android-sdk\platform-tools\adb.exe -s ZY322MF777 shell getprop
[ +115 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[   +6 ms] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +7 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[  +23 ms] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[  +21 ms] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +86 ms] Found plugin flutter_full_pdf_viewer at
C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\flutter_full_pdf_viewer-1.0.6\
[  +37 ms] Found plugin fluttertoast at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\fluttertoast-4.0.1\
[  +31 ms] Found plugin path_provider at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\path_provider-1.6.7\
[  +16 ms] Found plugin path_provider_macos at
C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\path_provider_macos-0.0.4\
[  +11 ms] Found plugin permission_handler at
C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\permission_handler-4.3.0\
[  +42 ms] Found plugin shared_preferences at
C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\shared_preferences-0.5.7\
[  +18 ms] Found plugin shared_preferences_macos at
C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\shared_preferences_macos-0.0.1+6\
[   +7 ms] Found plugin shared_preferences_web at
C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\shared_preferences_web-0.1.2+4\
[  +53 ms] Found plugin sqflite at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\sqflite-1.2.1\
[ +192 ms] Found plugin flutter_full_pdf_viewer at
C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\flutter_full_pdf_viewer-1.0.6\
[  +15 ms] Found plugin fluttertoast at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\fluttertoast-4.0.1\
[  +20 ms] Found plugin path_provider at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\path_provider-1.6.7\
[  +19 ms] Found plugin path_provider_macos at
C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\path_provider_macos-0.0.4\
[   +5 ms] Found plugin permission_handler at
C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\permission_handler-4.3.0\
[  +11 ms] Found plugin shared_preferences at
C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\shared_preferences-0.5.7\
[  +18 ms] Found plugin shared_preferences_macos at
C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\shared_preferences_macos-0.0.1+6\
[   +4 ms] Found plugin shared_preferences_web at
C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\shared_preferences_web-0.1.2+4\
[   +6 ms] Found plugin sqflite at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\sqflite-1.2.1\
[ +103 ms] Generating
F:\Flutter\kutub_khana\android\app\src\main\java\io\flutter\plugins\GeneratedPluginRegistrant.java
[ +101 ms] ro.hardware = qcom
[  +98 ms] Launching lib\main.dart on moto g 6 plus in debug mode...
[  +22 ms] executing: C:\Program Files (x86)\Android\android-sdk\platform-tools\adb.exe -s ZY322MF777 shell -x
logcat -v time -t 1
[  +98 ms] Exit code 0 from: C:\Program Files (x86)\Android\android-sdk\platform-tools\adb.exe -s ZY322MF777
shell -x logcat -v time -t 1
[   +2 ms] --------- beginning of main
           04-24 02:37:49.756 I/mmid    (  960): select timeout: wait for receiving msg
[  +18 ms] executing: C:\Program Files (x86)\Android\android-sdk\platform-tools\adb.exe version
[  +19 ms] executing: C:\Program Files (x86)\Android\android-sdk\platform-tools\adb.exe -s ZY322MF777 logcat -v 
time -T 04-24 02:37:49.756
[ +124 ms] Android Debug Bridge version 1.0.41
                    Version 29.0.6-6198805
                    Installed as C:\Program Files (x86)\Android\android-sdk\platform-tools\adb.exe
[   +3 ms] executing: C:\Program Files (x86)\Android\android-sdk\platform-tools\adb.exe start-server
[  +54 ms] Building APK
[  +38 ms] Running Gradle task 'assembleDebug'...
[  +20 ms] gradle.properties already sets `android.enableR8`
[  +34 ms] Using gradle from F:\Flutter\kutub_khana\android\gradlew.bat.
[  +30 ms] executing: C:\Program Files\Android\Android Studio\jre\bin\java -version
[ +180 ms] Exit code 0 from: C:\Program Files\Android\Android Studio\jre\bin\java -version
[   +1 ms] openjdk version "1.8.0_212-release"
           OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)
           OpenJDK 64-Bit Server VM (build 25.212-b04, mixed mode)
[   +9 ms] executing: [F:\Flutter\kutub_khana\android\] F:\Flutter\kutub_khana\android\gradlew.bat
-Pverbose=true -Ptarget=F:\Flutter\kutub_khana\lib\main.dart -Ptrack-widget-creation=true
-Pfilesystem-scheme=org-dartlang-root -Ptarget-platform=android-arm64 assembleDebug
[+4248 ms] Warning: unrecognized type name:
{http://schemas.android.com/repository/android/common/01}platformDetailsType. Did you mean
{http://schemas.android.com/sdk/android/repo/repository2/01}platformDetailsType?
[  +10 ms] Warning: Unable to create an instance of com.android.repository.impl.generated.v1.TypeDetails        
[   +2 ms] java.lang.InstantiationException
[   +1 ms]      at
sun.reflect.InstantiationExceptionConstructorAccessorImpl.newInstance(InstantiationExceptionConstructorAccessorImpl.java:48)
[   +3 ms]      at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
[   +1 ms]      at com.sun.xml.bind.v2.ClassFactory.create0(ClassFactory.java:133)
[   +1 ms]      at com.sun.xml.bind.v2.runtime.ClassBeanInfoImpl.createInstance(ClassBeanInfoImpl.java:285)     
[   +2 ms]      at
com.sun.xml.bind.v2.runtime.unmarshaller.UnmarshallingContext.createInstance(UnmarshallingContext.java:701)     
[  +30 ms]      at com.sun.xml.bind.v2.runtime.unmarshaller.StructureLoader.startElement(StructureLoader.java:186)
[  +46 ms]      at com.sun.xml.bind.v2.runtime.unmarshaller.XsiTypeLoader.startElement(XsiTypeLoader.java:80)
[  +27 ms]      at
com.sun.xml.bind.v2.runtime.unmarshaller.UnmarshallingContext._startElement(UnmarshallingContext.java:576)      
[   +3 ms]      at
com.sun.xml.bind.v2.runtime.unmarshaller.UnmarshallingContext.startElement(UnmarshallingContext.java:555)       
[   +2 ms]      at com.sun.xml.bind.v2.runtime.unmarshaller.SAXConnector.startElement(SAXConnector.java:168)    
[   +6 ms]      at org.xml.sax.helpers.XMLFilterImpl.startElement(XMLFilterImpl.java:551)
[  +21 ms]      at
com.android.repository.impl.meta.SchemaModuleUtil$NamespaceFallbackFilter.startElement(SchemaModuleUtil.java:398)
[   +2 ms]      at
com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.startElement(AbstractSAXParser.java:509)
[   +1 ms]      at
com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl.scanStartElement(XMLNSDocumentScannerImpl.java:374)
[   +2 ms]      at
com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl$FragmentContentDriver.next(XMLDocumentFragmentScannerImpl.java:2784)
[   +2 ms]      at
com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(XMLDocumentScannerImpl.java:602)
[  +22 ms]      at
com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl.next(XMLNSDocumentScannerImpl.java:112)        
[  +19 ms]      at
com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(XMLDocumentFragmentScannerImpl.java:505)
[   +2 ms]      at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:842)
[   +2 ms]      at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:771)
[  +49 ms]      at com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(XMLParser.java:141)
[   +1 ms]      at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(AbstractSAXParser.java:1213)
[   +1 ms]      at com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl$JAXPSAXParser.parse(SAXParserImpl.java:643)
[   +1 ms]      at org.xml.sax.helpers.XMLFilterImpl.parse(XMLFilterImpl.java:357)
[  +17 ms]      at com.sun.xml.bind.v2.runtime.unmarshaller.UnmarshallerImpl.unmarshal0(UnmarshallerImpl.java:258)
[   +2 ms]      at com.sun.xml.bind.v2.runtime.unmarshaller.UnmarshallerImpl.unmarshal(UnmarshallerImpl.java:229)
[   +1 ms]      at javax.xml.bind.helpers.AbstractUnmarshallerImpl.unmarshal(AbstractUnmarshallerImpl.java:140) 
[   +1 ms]      at javax.xml.bind.helpers.AbstractUnmarshallerImpl.unmarshal(AbstractUnmarshallerImpl.java:123) 
[        ]      at com.android.repository.impl.meta.SchemaModuleUtil.unmarshal(SchemaModuleUtil.java:192)       
[        ]      at com.android.build.gradle.internal.SdkParsingUtilsKt.parsePackage(SdkParsingUtils.kt:62)      
[        ]      at
com.android.build.gradle.internal.PlatformComponents$Companion.build$gradle(SdkDirectLoadingStrategy.kt:241)    
[   +2 ms]      at
com.android.build.gradle.internal.SdkDirectLoadingStrategy.loadSdkComponents(SdkDirectLoadingStrategy.kt:104)   
[   +1 ms]      at com.android.build.gradle.internal.SdkDirectLoadingStrategy.init(SdkDirectLoadingStrategy.kt:86)
[   +1 ms]      at
com.android.build.gradle.internal.SdkDirectLoadingStrategy.access$init(SdkDirectLoadingStrategy.kt:47)
[   +2 ms]      at
com.android.build.gradle.internal.SdkDirectLoadingStrategy$components$2.invoke(SdkDirectLoadingStrategy.kt:68)  
[  +45 ms]      at
com.android.build.gradle.internal.SdkDirectLoadingStrategy$components$2.invoke(SdkDirectLoadingStrategy.kt:47)  
[   +1 ms]      at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
[        ]      at
com.android.build.gradle.internal.SdkDirectLoadingStrategy.getComponents(SdkDirectLoadingStrategy.kt)
[  +28 ms]      at
com.android.build.gradle.internal.SdkDirectLoadingStrategy.loadedSuccessfully(SdkDirectLoadingStrategy.kt:140)  
[   +1 ms]      at com.android.build.gradle.internal.SdkLoadingStrategy.getCoreLambaStubs(SdkLoadingStrategy.kt:40)
[   +1 ms]      at
com.android.build.gradle.internal.SdkComponents$coreLambdaStubsProvider$1.call(SdkComponents.kt:106)
[   +2 ms]      at
com.android.build.gradle.internal.SdkComponents$coreLambdaStubsProvider$1.call(SdkComponents.kt:39)
[  +28 ms]      at org.gradle.api.internal.provider.DefaultProvider.getOrNull(DefaultProvider.java:41)
[   +1 ms]      at org.gradle.api.internal.provider.AbstractReadOnlyProvider.get(AbstractReadOnlyProvider.java:27)
[   +1 ms]      at org.gradle.api.internal.file.collections.UnpackingVisitor.add(UnpackingVisitor.java:56)      
[        ]      at org.gradle.api.internal.file.collections.UnpackingVisitor.add(UnpackingVisitor.java:84)      
[        ]      at
org.gradle.api.internal.file.collections.DefaultConfigurableFileCollection.visitContents(DefaultConfigurableFileCollection.java:209)
[  +49 ms]      at
org.gradle.api.internal.file.CompositeFileCollection.visitDependencies(CompositeFileCollection.java:186)        
[   +9 ms]      at
org.gradle.api.internal.file.collections.DefaultConfigurableFileCollection.visitDependencies(DefaultConfigurableFileCollection.java:216)
[   +1 ms]      at
org.gradle.api.internal.tasks.CachingTaskDependencyResolveContext$TaskGraphImpl.getNodeValues(CachingTaskDependencyResolveContext.java:111)
[   +1 ms]      at
org.gradle.internal.graph.CachingDirectedGraphWalker$GraphWithEmptyEdges.getNodeValues(CachingDirectedGraphWalker.java:213)
[   +2 ms]      at
org.gradle.internal.graph.CachingDirectedGraphWalker.doSearch(CachingDirectedGraphWalker.java:121)
[   +2 ms]      at
org.gradle.internal.graph.CachingDirectedGraphWalker.findValues(CachingDirectedGraphWalker.java:73)
[  +23 ms]      at
org.gradle.api.internal.tasks.CachingTaskDependencyResolveContext.getDependencies(CachingTaskDependencyResolveContext.java:66)
[   +1 ms]      at
org.gradle.execution.plan.TaskDependencyResolver.resolveDependenciesFor(TaskDependencyResolver.java:46)
[   +1 ms]      at org.gradle.execution.plan.LocalTaskNode.getDependencies(LocalTaskNode.java:106)
[   +1 ms]      at org.gradle.execution.plan.LocalTaskNode.resolveDependencies(LocalTaskNode.java:79)
[   +1 ms]      at org.gradle.execution.plan.DefaultExecutionPlan.addEntryTasks(DefaultExecutionPlan.java:176)
[   +1 ms]      at
org.gradle.execution.taskgraph.DefaultTaskExecutionGraph.addEntryTasks(DefaultTaskExecutionGraph.java:139)      
[   +1 ms]      at
org.gradle.execution.TaskNameResolvingBuildConfigurationAction.configure(TaskNameResolvingBuildConfigurationAction.java:49)
[  +25 ms]      at
org.gradle.execution.DefaultBuildConfigurationActionExecuter.configure(DefaultBuildConfigurationActionExecuter.java:58)
[   +2 ms]      at
org.gradle.execution.DefaultBuildConfigurationActionExecuter.access$200(DefaultBuildConfigurationActionExecuter.java:26)
[   +1 ms]      at
org.gradle.execution.DefaultBuildConfigurationActionExecuter$2.proceed(DefaultBuildConfigurationActionExecuter.java:66)
[   +3 ms]      at
org.gradle.execution.DefaultTasksBuildExecutionAction.configure(DefaultTasksBuildExecutionAction.java:45)       
[  +53 ms]      at
org.gradle.execution.DefaultBuildConfigurationActionExecuter.configure(DefaultBuildConfigurationActionExecuter.java:58)
[  +16 ms]      at
org.gradle.execution.DefaultBuildConfigurationActionExecuter.access$200(DefaultBuildConfigurationActionExecuter.java:26)
[   +2 ms]      at
org.gradle.execution.DefaultBuildConfigurationActionExecuter$2.proceed(DefaultBuildConfigurationActionExecuter.java:66)
[   +7 ms]      at
org.gradle.execution.ExcludedTaskFilteringBuildConfigurationAction.configure(ExcludedTaskFilteringBuildConfigurationAction.java:48)
[   +2 ms]      at
org.gradle.execution.DefaultBuildConfigurationActionExecuter.configure(DefaultBuildConfigurationActionExecuter.java:58)
[   +5 ms]      at
org.gradle.execution.DefaultBuildConfigurationActionExecuter.access$200(DefaultBuildConfigurationActionExecuter.java:26)
[   +4 ms]      at
org.gradle.execution.DefaultBuildConfigurationActionExecuter$1.run(DefaultBuildConfigurationActionExecuter.java:44)
[  +35 ms]      at org.gradle.internal.Factories$1.create(Factories.java:26)
[   +1 ms]      at
org.gradle.api.internal.project.DefaultProjectStateRegistry.withLenientState(DefaultProjectStateRegistry.java:133)
[   +1 ms]      at
org.gradle.api.internal.project.DefaultProjectStateRegistry.withLenientState(DefaultProjectStateRegistry.java:125)
[   +1 ms]      at
org.gradle.execution.DefaultBuildConfigurationActionExecuter.select(DefaultBuildConfigurationActionExecuter.java:40)
[   +1 ms]      at
org.gradle.initialization.DefaultTaskExecutionPreparer.prepareForTaskExecution(DefaultTaskExecutionPreparer.java:38)
[   +1 ms]      at
org.gradle.initialization.BuildOperatingFiringTaskExecutionPreparer$CalculateTaskGraph.populateTaskGraph(BuildOperatingFiringTaskExecutionPreparer.java:82)
[   +3 ms]      at
org.gradle.initialization.BuildOperatingFiringTaskExecutionPreparer$CalculateTaskGraph.run(BuildOperatingFiringTaskExecutionPreparer.java:57)
[  +14 ms]      at
org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:402)
[  +18 ms]      at
org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:394)
[  +30 ms]      at
org.gradle.internal.operations.DefaultBuildOperationExecutor$1.execute(DefaultBuildOperationExecutor.java:165)  
[  +15 ms]      at
org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:250)    
[   +1 ms]      at
org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:158)    
[  +16 ms]      at
org.gradle.internal.operations.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:92)
[  +21 ms]      at
org.gradle.internal.operations.DelegatingBuildOperationExecutor.run(DelegatingBuildOperationExecutor.java:31)   
[   +4 ms]      at
org.gradle.initialization.BuildOperatingFiringTaskExecutionPreparer.prepareForTaskExecution(BuildOperatingFiringTaskExecutionPreparer.java:45)
[   +1 ms]      at
org.gradle.initialization.DefaultGradleLauncher.prepareTaskExecution(DefaultGradleLauncher.java:206)
[   +2 ms]      at
org.gradle.initialization.DefaultGradleLauncher.doClassicBuildStages(DefaultGradleLauncher.java:142)
[   +1 ms]      at org.gradle.initialization.DefaultGradleLauncher.doBuildStages(DefaultGradleLauncher.java:126)[   +1 ms]      at org.gradle.initialization.DefaultGradleLauncher.executeTasks(DefaultGradleLauncher.java:106) 
[   +1 ms]      at org.gradle.internal.invocation.GradleBuildController$1.execute(GradleBuildController.java:60)[  +27 ms]      at org.gradle.internal.invocation.GradleBuildController$1.execute(GradleBuildController.java:57)[   +1 ms]      at org.gradle.internal.invocation.GradleBuildController$3.create(GradleBuildController.java:85) 
[   +1 ms]      at org.gradle.internal.invocation.GradleBuildController$3.create(GradleBuildController.java:78) 
[        ]      at org.gradle.internal.work.DefaultWorkerLeaseService.withLocks(DefaultWorkerLeaseService.java:189)
[   +2 ms]      at
org.gradle.internal.work.StopShieldingWorkerLeaseService.withLocks(StopShieldingWorkerLeaseService.java:40)     
[  +28 ms]      at org.gradle.internal.invocation.GradleBuildController.doBuild(GradleBuildController.java:78)  
[   +1 ms]      at org.gradle.internal.invocation.GradleBuildController.run(GradleBuildController.java:57)      
[   +1 ms]      at
org.gradle.tooling.internal.provider.ExecuteBuildActionRunner.run(ExecuteBuildActionRunner.java:31)
[  +32 ms]      at org.gradle.launcher.exec.ChainingBuildActionRunner.run(ChainingBuildActionRunner.java:35)
[        ]      at
org.gradle.launcher.exec.BuildOutcomeReportingBuildActionRunner.run(BuildOutcomeReportingBuildActionRunner.java:63)
[   +1 ms]      at
org.gradle.tooling.internal.provider.ValidatingBuildActionRunner.run(ValidatingBuildActionRunner.java:32)       
[  +17 ms]      at
org.gradle.launcher.exec.BuildCompletionNotifyingBuildActionRunner.run(BuildCompletionNotifyingBuildActionRunner.java:39)
[  +17 ms]      at
org.gradle.launcher.exec.RunAsBuildOperationBuildActionRunner$3.call(RunAsBuildOperationBuildActionRunner.java:51)
[  +28 ms]      at
org.gradle.launcher.exec.RunAsBuildOperationBuildActionRunner$3.call(RunAsBuildOperationBuildActionRunner.java:45)
[   +1 ms]      at
org.gradle.internal.operations.DefaultBuildOperationExecutor$CallableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:416)
[   +2 ms]      at
org.gradle.internal.operations.DefaultBuildOperationExecutor$CallableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:406)
[  +15 ms]      at
org.gradle.internal.operations.DefaultBuildOperationExecutor$1.execute(DefaultBuildOperationExecutor.java:165)  
[  +14 ms]      at
org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:250)    
[   +1 ms]      at
org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:158)    
[   +1 ms]      at
org.gradle.internal.operations.DefaultBuildOperationExecutor.call(DefaultBuildOperationExecutor.java:102)       
[   +4 ms]      at
org.gradle.internal.operations.DelegatingBuildOperationExecutor.call(DelegatingBuildOperationExecutor.java:36)  
[  +13 ms]      at
org.gradle.launcher.exec.RunAsBuildOperationBuildActionRunner.run(RunAsBuildOperationBuildActionRunner.java:45) 
[  +15 ms]      at
org.gradle.launcher.exec.InProcessBuildActionExecuter$1.transform(InProcessBuildActionExecuter.java:50)
[  +17 ms]      at
org.gradle.launcher.exec.InProcessBuildActionExecuter$1.transform(InProcessBuildActionExecuter.java:47)
[  +23 ms]      at org.gradle.composite.internal.DefaultRootBuildState.run(DefaultRootBuildState.java:78)       
[        ]      at
org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:47)
[   +1 ms]      at
org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:31)
[   +1 ms]      at
org.gradle.launcher.exec.BuildTreeScopeBuildActionExecuter.execute(BuildTreeScopeBuildActionExecuter.java:42)   
[   +1 ms]      at
org.gradle.launcher.exec.BuildTreeScopeBuildActionExecuter.execute(BuildTreeScopeBuildActionExecuter.java:28)   
```
## flutter analyze
```bash
Analyzing kutub_khana...                                                

   info - This class (or a class which this class inherits from) is marked as '@immutable', but one or more of  
          its instance fields are not final: PDFScreen.pathPDF - lib\views\downloads.dart:252:7 -
          must_be_immutable
   info - The value of the local variable 'categories' isn't used - lib\views\home_page.dart:80:11 -
          unused_local_variable
   info - Unused import: 'package:provider/provider.dart' - lib\views\library.dart:6:8 - unused_import
   info - Unused import: 'home_page.dart' - lib\views\main_page.dart:9:8 - unused_import
```

## flutter doctor -v
```console
[√] Flutter (Channel stable, v1.12.13+hotfix.8, on Microsoft Windows [Version 10.0.18362.535], locale en-US)
    • Flutter version 1.12.13+hotfix.8 at C:\src\flutter
    • Framework revision 0b8abb4724 (2 months ago), 2020-02-11 11:44:36 -0800
    • Engine revision e1e6ced81d
    • Dart version 2.7.0

 
[!] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at C:\Program Files (x86)\Android\android-sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses

[√] Android Studio (version 3.6)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)

[√] VS Code (version 1.44.2)
    • VS Code at C:\Users\huzaifi\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.9.1

[√] Connected device (1 available)
    • moto g 6 plus • ZY322MF777 • android-arm64 • Android 8.0.0 (API 26)

! Doctor found issues in 1 category.
```
</details>

**Comment by iapicca** [comment]
Hi @huzaifasaeed 
your logs seem incomplete and don't show the error you are reporting in the title
could you please run `flutter upgrade --force` ;
if the issue please provide your  updated `flutter doctor -v` , 
your full `flutter run --verbose` 
and your `pubspec.yaml` 
Thank you

**Comment by VladyslavBondarenko** [comment]
@huzaifasaeed 
I hope you've solved the issue.
Closing as additional information isn't provided.
Could everyone who still has this problem please file a new issue with the exact descriptions what happens, logs and the output of `flutter doctor -v` please.
