### ISSUE TITLE
"debugDumpApp()" fails with error "type 'PictureStream' is not a subtype of type 'Diagnosticable'

### ISSUE THREAD

**Issue by Ivan-Gorchakov** [flutter/flutter#55537]
## Steps to Reproduce
1. Put the "debugDumpApp()" inside any working widget test.
2. Run widget test.

**Expected results:** prints a string representation of the currently running app.

**Actual results:** error "type 'PictureStream' is not a subtype of type 'Diagnosticable'.

<details>
  <summary>Logs</summary>

```
AutomatedTestWidgetsFlutterBinding - CHECKED MODE
══╡ EXCEPTION CAUGHT BY FLUTTER TEST FRAMEWORK ╞════════════════════════════════════════════════════
The following assertion was thrown running a test:
type 'PictureStream' is not a subtype of type 'Diagnosticable'

Either the assertion indicates an error in the framework itself, or we should provide substantially
more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=BUG.md

When the exception was thrown, this was the stack:
#0      DiagnosticableMixin.toDiagnosticsNode (package:flutter/src/foundation/diagnostics.dart:3113:14)
#1      DiagnosticableMixin.toString.<anonymous closure> (package:flutter/src/foundation/diagnostics.dart:3095:20)
#2      DiagnosticableMixin.toString (package:flutter/src/foundation/diagnostics.dart:3097:6)
#3      DiagnosticsProperty.valueToString (package:flutter/src/foundation/diagnostics.dart:2698:61)
#4      DiagnosticsProperty.toDescription (package:flutter/src/foundation/diagnostics.dart:2712:21)
#5      TextTreeRenderer.render (package:flutter/src/foundation/diagnostics.dart:1170:31)
#6      TextTreeRenderer.render (package:flutter/src/foundation/diagnostics.dart:1280:39)
#7      DiagnosticsNode.toStringDeep (package:flutter/src/foundation/diagnostics.dart:1709:7)
#8      DiagnosticsNode.toString (package:flutter/src/foundation/diagnostics.dart:1632:14)
#9      DiagnosticableMixin.toString.<anonymous closure> (package:flutter/src/foundation/diagnostics.dart:3095:78)
#10     DiagnosticableMixin.toString (package:flutter/src/foundation/diagnostics.dart:3097:6)
#11     DiagnosticsProperty.valueToString (package:flutter/src/foundation/diagnostics.dart:2698:61)
#12     DiagnosticsProperty.toDescription (package:flutter/src/foundation/diagnostics.dart:2712:21)
#13     TextTreeRenderer.render (package:flutter/src/foundation/diagnostics.dart:1170:31)
#14     TextTreeRenderer.render (package:flutter/src/foundation/diagnostics.dart:1280:39)
#15     TextTreeRenderer.render (package:flutter/src/foundation/diagnostics.dart:1357:33)
#16     TextTreeRenderer.render (package:flutter/src/foundation/diagnostics.dart:1336:33)
#17     TextTreeRenderer.render (package:flutter/src/foundation/diagnostics.dart:1336:33)
#18     TextTreeRenderer.render (package:flutter/src/foundation/diagnostics.dart:1336:33)
#19     TextTreeRenderer.render (package:flutter/src/foundation/diagnostics.dart:1336:33)
#20     TextTreeRenderer.render (package:flutter/src/foundation/diagnostics.dart:1357:33)
#21     TextTreeRenderer.render (package:flutter/src/foundation/diagnostics.dart:1336:33)
#22     TextTreeRenderer.render (package:flutter/src/foundation/diagnostics.dart:1336:33)
#23     TextTreeRenderer.render (package:flutter/src/foundation/diagnostics.dart:1336:33)
#24     TextTreeRenderer.render (package:flutter/src/foundation/diagnostics.dart:1336:33)
#25     TextTreeRenderer.render (package:flutter/src/foundation/diagnostics.dart:1336:33)
#26     TextTreeRenderer.render (package:flutter/src/foundation/diagnostics.dart:1336:33)
#27     TextTreeRenderer.render (package:flutter/src/foundation/diagnostics.dart:1336:33)
#28     TextTreeRenderer.render (package:flutter/src/foundation/diagnostics.dart:1336:33)
#29     TextTreeRenderer.render (package:flutter/src/foundation/diagnostics.dart:1336:33)
#30     TextTreeRenderer.render (package:flutter/src/foundation/diagnostics.dart:1336:33)
#31     TextTreeRenderer.render (package:flutter/src/foundation/diagnostics.dart:1336:33)
#32     TextTreeRenderer.render (package:flutter/src/foundation/diagnostics.dart:1336:33)
#33     TextTreeRenderer.render (package:flutter/src/foundation/diagnostics.dart:1336:33)
#34     TextTreeRenderer.render (package:flutter/src/foundation/diagnostics.dart:1336:33)
#35     TextTreeRenderer.render (package:flutter/src/foundation/diagnostics.dart:1336:33)
#36     TextTreeRenderer.render (package:flutter/src/foundation/diagnostics.dart:1336:33)
#37     TextTreeRenderer.render (package:flutter/src/foundation/diagnostics.dart:1336:33)
#38     TextTreeRenderer.render (package:flutter/src/foundation/diagnostics.dart:1357:33)
#39     TextTreeRenderer.render (package:flutter/src/foundation/diagnostics.dart:1336:33)
#40     TextTreeRenderer.render (package:flutter/src/foundation/diagnostics.dart:1336:33)
#41     TextTreeRenderer.render (package:flutter/src/foundation/diagnostics.dart:1336:33)
#42     TextTreeRenderer.render (package:flutter/src/foundation/diagnostics.dart:1336:33)
#43     TextTreeRenderer.render (package:flutter/src/foundation/diagnostics.dart:1336:33)
#44     TextTreeRenderer.render (package:flutter/src/foundation/diagnostics.dart:1336:33)
#45     TextTreeRenderer.render (package:flutter/src/foundation/diagnostics.dart:1336:33)
#46     TextTreeRenderer.render (package:flutter/src/foundation/diagnostics.dart:1336:33)
#47     TextTreeRenderer.render (package:flutter/src/foundation/diagnostics.dart:1336:33)
#48     TextTreeRenderer.render (package:flutter/src/foundation/diagnostics.dart:1336:33)
#49     TextTreeRenderer.render (package:flutter/src/foundation/diagnostics.dart:1336:33)
#50     TextTreeRenderer.render (package:flutter/src/foundation/diagnostics.dart:1336:33)
#51     TextTreeRenderer.render (package:flutter/src/foundation/diagnostics.dart:1336:33)
#52     TextTreeRenderer.render (package:flutter/src/foundation/diagnostics.dart:1336:33)
#53     TextTreeRenderer.render (package:flutter/src/foundation/diagnostics.dart:1336:33)
#54     TextTreeRenderer.render (package:flutter/src/foundation/diagnostics.dart:1336:33)
#55     TextTreeRenderer.render (package:flutter/src/foundation/diagnostics.dart:1336:33)
#56     TextTreeRenderer.render (package:flutter/src/foundation/diagnostics.dart:1336:33)
#57     TextTreeRenderer.render (package:flutter/src/foundation/diagnostics.dart:1336:33)
#58     TextTreeRenderer.render (package:flutter/src/foundation/diagnostics.dart:1336:33)
#59     TextTreeRenderer.render (package:flutter/src/foundation/diagnostics.dart:1336:33)
#60     TextTreeRenderer.render (package:flutter/src/foundation/diagnostics.dart:1336:33)
#61     TextTreeRenderer.render (package:flutter/src/foundation/diagnostics.dart:1336:33)
#62     TextTreeRenderer.render (package:flutter/src/foundation/diagnostics.dart:1357:33)
#63     TextTreeRenderer.render (package:flutter/src/foundation/diagnostics.dart:1336:33)
#64     TextTreeRenderer.render (package:flutter/src/foundation/diagnostics.dart:1336:33)
#65     TextTreeRenderer.render (package:flutter/src/foundation/diagnostics.dart:1336:33)
#66     TextTreeRenderer.render (package:flutter/src/foundation/diagnostics.dart:1336:33)
#67     TextTreeRenderer.render (package:flutter/src/foundation/diagnostics.dart:1336:33)
#68     TextTreeRenderer.render (package:flutter/src/foundation/diagnostics.dart:1336:33)
#69     TextTreeRenderer.render (package:flutter/src/foundation/diagnostics.dart:1336:33)
#70     TextTreeRenderer.render (package:flutter/src/foundation/diagnostics.dart:1336:33)
#71     TextTreeRenderer.render (package:flutter/src/foundation/diagnostics.dart:1336:33)
#72     TextTreeRenderer.render (package:flutter/src/foundation/diagnostics.dart:1336:33)
#73     TextTreeRenderer.render (package:flutter/src/foundation/diagnostics.dart:1336:33)
#74     TextTreeRenderer.render (package:flutter/src/foundation/diagnostics.dart:1336:33)
#75     TextTreeRenderer.render (package:flutter/src/foundation/diagnostics.dart:1336:33)
#76     TextTreeRenderer.render (package:flutter/src/foundation/diagnostics.dart:1336:33)
#77     TextTreeRenderer.render (package:flutter/src/foundation/diagnostics.dart:1336:33)
#78     TextTreeRenderer.render (package:flutter/src/foundation/diagnostics.dart:1336:33)
#79     TextTreeRenderer.render (package:flutter/src/foundation/diagnostics.dart:1357:33)
#80     TextTreeRenderer.render (package:flutter/src/foundation/diagnostics.dart:1336:33)
#81     TextTreeRenderer.render (package:flutter/src/foundation/diagnostics.dart:1336:33)
#82     TextTreeRenderer.render (package:flutter/src/foundation/diagnostics.dart:1336:33)
#83     TextTreeRenderer.render (package:flutter/src/foundation/diagnostics.dart:1336:33)
#84     TextTreeRenderer.render (package:flutter/src/foundation/diagnostics.dart:1336:33)
#85     TextTreeRenderer.render (package:flutter/src/foundation/diagnostics.dart:1336:33)
#86     TextTreeRenderer.render (package:flutter/src/foundation/diagnostics.dart:1336:33)
#87     TextTreeRenderer.render (package:flutter/src/foundation/diagnostics.dart:1336:33)
#88     TextTreeRenderer.render (package:flutter/src/foundation/diagnostics.dart:1336:33)
#89     TextTreeRenderer.render (package:flutter/src/foundation/diagnostics.dart:1336:33)
#90     TextTreeRenderer.render (package:flutter/src/foundation/diagnostics.dart:1336:33)
#91     TextTreeRenderer.render (package:flutter/src/foundation/diagnostics.dart:1336:33)
#92     TextTreeRenderer.render (package:flutter/src/foundation/diagnostics.dart:1336:33)
#93     TextTreeRenderer.render (package:flutter/src/foundation/diagnostics.dart:1336:33)
#94     TextTreeRenderer.render (package:flutter/src/foundation/diagnostics.dart:1336:33)
#95     TextTreeRenderer.render (package:flutter/src/foundation/diagnostics.dart:1336:33)
#96     TextTreeRenderer.render (package:flutter/src/foundation/diagnostics.dart:1336:33)
#97     TextTreeRenderer.render (package:flutter/src/foundation/diagnostics.dart:1336:33)
#98     TextTreeRenderer.render (package:flutter/src/foundation/diagnostics.dart:1336:33)
#99     TextTreeRenderer.render (package:flutter/src/foundation/diagnostics.dart:1336:33)
#100    TextTreeRenderer.render (package:flutter/src/foundation/diagnostics.dart:1336:33)
#101    TextTreeRenderer.render (package:flutter/src/foundation/diagnostics.dart:1336:33)
#102    TextTreeRenderer.render (package:flutter/src/foundation/diagnostics.dart:1336:33)
#103    TextTreeRenderer.render (package:flutter/src/foundation/diagnostics.dart:1336:33)
#104    TextTreeRenderer.render (package:flutter/src/foundation/diagnostics.dart:1336:33)
#105    TextTreeRenderer.render (package:flutter/src/foundation/diagnostics.dart:1336:33)
#106    TextTreeRenderer.render (package:flutter/src/foundation/diagnostics.dart:1336:33)
#107    TextTreeRenderer.render (package:flutter/src/foundation/diagnostics.dart:1336:33)
#108    TextTreeRenderer.render (package:flutter/src/foundation/diagnostics.dart:1336:33)
#109    TextTreeRenderer.render (package:flutter/src/foundation/diagnostics.dart:1336:33)
#110    TextTreeRenderer.render (package:flutter/src/foundation/diagnostics.dart:1336:33)
#111    TextTreeRenderer.render (package:flutter/src/foundation/diagnostics.dart:1336:33)
#112    TextTreeRenderer.render (package:flutter/src/foundation/diagnostics.dart:1336:33)
#113    TextTreeRenderer.render (package:flutter/src/foundation/diagnostics.dart:1336:33)
#114    TextTreeRenderer.render (package:flutter/src/foundation/diagnostics.dart:1336:33)
#115    TextTreeRenderer.render (package:flutter/src/foundation/diagnostics.dart:1336:33)
#116    TextTreeRenderer.render (package:flutter/src/foundation/diagnostics.dart:1336:33)
#117    TextTreeRenderer.render (package:flutter/src/foundation/diagnostics.dart:1336:33)
#118    TextTreeRenderer.render (package:flutter/src/foundation/diagnostics.dart:1336:33)
#119    TextTreeRenderer.render (package:flutter/src/foundation/diagnostics.dart:1336:33)
#120    TextTreeRenderer.render (package:flutter/src/foundation/diagnostics.dart:1336:33)
#121    TextTreeRenderer.render (package:flutter/src/foundation/diagnostics.dart:1336:33)
#122    TextTreeRenderer.render (package:flutter/src/foundation/diagnostics.dart:1336:33)
#123    TextTreeRenderer.render (package:flutter/src/foundation/diagnostics.dart:1336:33)
#124    TextTreeRenderer.render (package:flutter/src/foundation/diagnostics.dart:1336:33)
#125    TextTreeRenderer.render (package:flutter/src/foundation/diagnostics.dart:1336:33)
#126    TextTreeRenderer.render (package:flutter/src/foundation/diagnostics.dart:1336:33)
#127    TextTreeRenderer.render (package:flutter/src/foundation/diagnostics.dart:1336:33)
#128    TextTreeRenderer.render (package:flutter/src/foundation/diagnostics.dart:1336:33)
#129    TextTreeRenderer.render (package:flutter/src/foundation/diagnostics.dart:1336:33)
#130    TextTreeRenderer.render (package:flutter/src/foundation/diagnostics.dart:1336:33)
#131    TextTreeRenderer.render (package:flutter/src/foundation/diagnostics.dart:1336:33)
#132    TextTreeRenderer.render (package:flutter/src/foundation/diagnostics.dart:1336:33)
#133    TextTreeRenderer.render (package:flutter/src/foundation/diagnostics.dart:1336:33)
#134    TextTreeRenderer.render (package:flutter/src/foundation/diagnostics.dart:1336:33)
#135    TextTreeRenderer.render (package:flutter/src/foundation/diagnostics.dart:1336:33)
#136    TextTreeRenderer.render (package:flutter/src/foundation/diagnostics.dart:1336:33)
#137    TextTreeRenderer.render (package:flutter/src/foundation/diagnostics.dart:1336:33)
#138    TextTreeRenderer.render (package:flutter/src/foundation/diagnostics.dart:1336:33)
#139    TextTreeRenderer.render (package:flutter/src/foundation/diagnostics.dart:1336:33)
#140    TextTreeRenderer.render (package:flutter/src/foundation/diagnostics.dart:1336:33)
#141    TextTreeRenderer.render (package:flutter/src/foundation/diagnostics.dart:1336:33)
#142    TextTreeRenderer.render (package:flutter/src/foundation/diagnostics.dart:1336:33)
#143    TextTreeRenderer.render (package:flutter/src/foundation/diagnostics.dart:1336:33)
#144    TextTreeRenderer.render (package:flutter/src/foundation/diagnostics.dart:1336:33)
#145    TextTreeRenderer.render (package:flutter/src/foundation/diagnostics.dart:1336:33)
#146    TextTreeRenderer.render (package:flutter/src/foundation/diagnostics.dart:1336:33)
#147    TextTreeRenderer.render (package:flutter/src/foundation/diagnostics.dart:1336:33)
#148    TextTreeRenderer.render (package:flutter/src/foundation/diagnostics.dart:1336:33)
#149    TextTreeRenderer.render (package:flutter/src/foundation/diagnostics.dart:1336:33)
#150    TextTreeRenderer.render (package:flutter/src/foundation/diagnostics.dart:1336:33)
#151    TextTreeRenderer.render (package:flutter/src/foundation/diagnostics.dart:1336:33)
#152    TextTreeRenderer.render (package:flutter/src/foundation/diagnostics.dart:1336:33)
#153    TextTreeRenderer.render (package:flutter/src/foundation/diagnostics.dart:1336:33)
#154    TextTreeRenderer.render (package:flutter/src/foundation/diagnostics.dart:1336:33)
#155    DiagnosticsNode.toStringDeep (package:flutter/src/foundation/diagnostics.dart:1709:7)
#156    DiagnosticableTree.toStringDeep (package:flutter/src/foundation/diagnostics.dart:3406:32)
#157    debugDumpApp (package:flutter/src/widgets/binding.dart:883:58)
#158    main.<anonymous closure>.<anonymous closure> (file:///C:/Users/ivan_/Projects/Mobile2.0/src/app/test/widget_tests/nav_bar_and_tabs_test.dart:1069:7)
<asynchronous suspension>
#159    testWidgets.<anonymous closure>.<anonymous closure> (package:flutter_test/src/widget_tester.dart:124:25)
#160    TestWidgetsFlutterBinding._runTestBody (package:flutter_test/src/binding.dart:696:19)
<asynchronous suspension>
#163    TestWidgetsFlutterBinding._runTest (package:flutter_test/src/binding.dart:679:14)
#164    AutomatedTestWidgetsFlutterBinding.runTest.<anonymous closure> (package:flutter_test/src/binding.dart:1050:24)
#170    AutomatedTestWidgetsFlutterBinding.runTest (package:flutter_test/src/binding.dart:1047:15)
#171    testWidgets.<anonymous closure> (package:flutter_test/src/widget_tester.dart:121:22)
#172    Declarer.test.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:test_api/src/backend/declarer.dart:171:27)
<asynchronous suspension>
#173    Invoker.waitForOutstandingCallbacks.<anonymous closure> (package:test_api/src/backend/invoker.dart:242:15)
#178    Invoker.waitForOutstandingCallbacks (package:test_api/src/backend/invoker.dart:239:5)
#179    Declarer.test.<anonymous closure>.<anonymous closure> (package:test_api/src/backend/declarer.dart:169:33)
#184    Declarer.test.<anonymous closure> (package:test_api/src/backend/declarer.dart:168:13)
#185    Invoker._onRun.<anonymous closure>.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:test_api/src/backend/invoker.dart:392:25)
#199    _Timer._runTimers (dart:isolate-patch/timer_impl.dart:384:19)
#200    _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:418:5)
#201    _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:174:12)
(elided 28 frames from class _FakeAsync, package dart:async, package dart:async-patch, and package stack_trace)
```

```

Analyzing app...
No issues found! (ran in 5.8s)

```
```

[√] Flutter (Channel stable, v1.12.13+hotfix.9, on Microsoft Windows [Version 10.0.19041.207], locale ru-UA)
    • Flutter version 1.12.13+hotfix.9 at C:\flutter
    • Framework revision f139b11009 (3 weeks ago), 2020-03-30 13:57:30 -0700
    • Engine revision af51afceb8
    • Dart version 2.7.2


[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at C:\Android\android-sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • ANDROID_HOME = C:\Android\android-sdk
    • Java binary at: C:\Java\AdoptOpenJDK\jdk-8.0.242.08-hotspot\bin\java
    • Java version OpenJDK Runtime Environment (AdoptOpenJDK)(build 1.8.0_242-b08)
    • All Android licenses accepted.

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/setup/#android-setup for detailed instructions).

[√] VS Code (version 1.44.2)
    • VS Code at C:\Users\ivan_\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.9.1

[!] Connected device
    ! No devices available

! Doctor found issues in 2 categories.


```

</details>

**Comment by VladyslavBondarenko** [comment]
Hi @Ivan-Gorchakov 
could you provide a minimal reproducible code sample?

<details>
 <summary>I added debugDumpApp() in the default app this way</summary>

```
import 'package:flutter/material.dart';
import 'package:flutter_test/flutter_test.dart';

import 'package:myapp/main.dart';

void main() {
  testWidgets('Counter increments smoke test', (WidgetTester tester) async {
    await tester.pumpWidget(MyApp());

    debugDumpApp();

    expect(find.text('0'), findsOneWidget);
    expect(find.text('1'), findsNothing);

    await tester.tap(find.byIcon(Icons.add));
    await tester.pump();

    expect(find.text('0'), findsNothing);
    expect(find.text('1'), findsOneWidget);
  });
}
```

</details>

and can't see the error

**Comment by Ivan-Gorchakov** [comment]
@VladyslavBondarenko I guess I can't because of my NDA :) But I can add some additional info, hope it can be helpful:
- we are using Redux, mocking with Mockito, widget testing whole app (I mean not set upping one particular widget - set upping the whole app);
- it reproducible for me in IntelliJ/VS Code, in Flutter version 1.12.13+hotfix.9 & previous, Win/Mac.

**Comment by Ivan-Gorchakov** [comment]
I've caught today same error running Flutter Inspector:
════════ Exception caught by Flutter framework ═════════════════════════════════════════════════════
The following assertion was thrown during a service extension callback for "ext.flutter.inspector.getChildrenDetailsSubtree":
type 'PictureStream' is not a subtype of type 'Diagnosticable'


Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=BUG.md

When the exception was thrown, this was the stack: 
#0      DiagnosticableMixin.toDiagnosticsNode (package:flutter/src/foundation/diagnostics.dart:3113:14)
#1      DiagnosticableMixin.toString.<anonymous closure> (package:flutter/src/foundation/diagnostics.dart:3095:20)
#2      DiagnosticableMixin.toString (package:flutter/src/foundation/diagnostics.dart:3097:6)
#3      DiagnosticsProperty.valueToString (package:flutter/src/foundation/diagnostics.dart:2698:61)
#4      DiagnosticsProperty.toDescription (package:flutter/src/foundation/diagnostics.dart:2712:21)
...
════════════════════════════════════════════════════════════════════════════════════════════════════

**Comment by goderbauer** [comment]
We'd need a minimal, but runnable code example that shows the error in order to debug and fix it.

**Comment by Ivan-Gorchakov** [comment]
@goderbauer & @VladyslavBondarenko, unfortunately, I can't because of my NDA.
But fortunately, I've discovered the cause of the error - one module of our app is implemented as a WebVeiw & that is the reason of the "error "type 'PictureStream' is not a subtype of type 'Diagnosticable'."

**Comment by tigertore** [comment]
I see the same issue when using the flutter inspector. 
If I click on a widget that contains a SvgPicture (flutter_svg) it dumps a stack trace 
and the widget and all its children can't be inspected.

Container(
  padding: EdgeInsets.all(20),
  color: Colors.red,
  child: SvgPicture.asset('images/close_circle_filled.svg'),
),


════════ Exception caught by Flutter framework ═════════════════════════════════════════════════════
The following assertion was thrown during a service extension callback for "ext.flutter.inspector.getDetailsSubtree":
type 'PictureStream' is not a subtype of type 'Diagnosticable'

Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
https://github.com/flutter/flutter/issues/new?template=BUG.md

When the exception was thrown, this was the stack:
#0 DiagnosticableMixin.toDiagnosticsNode (package:flutter/src/foundation/diagnostics.dart:3113:14)
#1 DiagnosticableMixin.toString. (package:flutter/src/foundation/diagnostics.dart:3095:20)
#2 DiagnosticableMixin.toString (package:flutter/src/foundation/diagnostics.dart:3097:6)
#3 DiagnosticsProperty.valueToString (package:flutter/src/foundation/diagnostics.dart:2698:61)
#4 DiagnosticsProperty.toDescription (package:flutter/src/foundation/diagnostics.dart:2712:21)
...
════════════════════════════════════════════════════════════════════════════════════════════════════

**Comment by tigertore** [comment]
In Flutter 1.17 this error is gone, and it is working as expected.

**Comment by VladyslavBondarenko** [comment]
@Ivan-Gorchakov could you try with new stable or with dev?

**Comment by Ivan-Gorchakov** [comment]
Yes, I'm confirming that on Flutter Stable v.1.17 the error is gone.

**Comment by VladyslavBondarenko** [comment]
@Ivan-Gorchakov Thank you, closing then as fixed
