### ISSUE TITLE
cloud_firestore ^0.13.5, version solving failed after flutter upgrade.

### ISSUE THREAD

**Issue by teekamsuthar** [flutter/flutter#55590]
## Steps to Reproduce

1. Run `flutter create bug`.
2. Update the files as follows: ... 
3. ... 

**Expected results:** 
When I type "flutter run" 
**Actual results:** 
cloud_firestore ^0.13.5 plugin  error. see logs below
<details>
  <summary>Logs</summary>
The current Flutter SDK version is 1.12.13.

Because cloud_firestore 0.13.5 requires Flutter SDK version >=1.12.13+hotfix.4 <2.0.0 and no versions of cloud_firestore match >0.13.5 <0.14.0, cloud_firestore ^0.13.5 is forbidden.
So, because recursive_root depends on cloud_firestore ^0.13.5, version solving failed.
pub get failed (1; So, because recursive_root depends on cloud_firestore ^0.13.5, version solving failed.)

```[  +36 ms] executing: [C:\src\flutter\] git -c log.showSignature=false log -n 1 --pretty=format:%H
[  +92 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[   +1 ms] cf37c2cd07a1d3ba296efff2dc75e19ba65e1665
[   +1 ms] executing: [C:\src\flutter\] git describe --match v*.*.* --first-parent --long --tags
[  +96 ms] Exit code 0 from: git describe --match v*.*.* --first-parent --long --tags
[   +1 ms] v1.12.13-0-gcf37c2cd0
[  +10 ms] executing: [C:\src\flutter\] git rev-parse --abbrev-ref --symbolic @{u}
[  +71 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/stable
[        ] executing: [C:\src\flutter\] git ls-remote --get-url origin
[  +56 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[ +121 ms] executing: [C:\src\flutter\] git rev-parse --abbrev-ref HEAD
[ +132 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[   +1 ms] stable
[ +144 ms] executing: C:\Users\teeka\AppData\Local\Android\sdk\platform-tools\adb.exe devices -l
[  +40 ms] Exit code 0 from: C:\Users\teeka\AppData\Local\Android\sdk\platform-tools\adb.exe devices -l
[   +1 ms] List of devices attached
           ZF6224TQBC             device product:troika model:motorola_one_action device:troika_sprout transport_id:2
[  +29 ms] C:\Users\teeka\AppData\Local\Android\sdk\platform-tools\adb.exe -s ZF6224TQBC shell getprop
[ +126 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[  +10 ms] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[   +9 ms] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +6 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[  +11 ms] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +24 ms] Running "flutter pub get" in recursive_root...
[  +10 ms] Using C:\src\flutter\.pub-cache for the pub cache.
[   +3 ms] executing: [C:\Users\teeka\OneDrive\Desktop\workspace\recursive_root\] C:\src\flutter\bin\cache\dart-sdk\bin\pub.bat --verbose get
--no-precompile
[ +217 ms] FINE: Pub 2.7.0
[   +4 ms] IO  : Spawning "cmd /c ver" in C:\Users\teeka\OneDrive\Desktop\workspace\recursive_root\.
[  +10 ms] IO  : Finished ver. Exit code 0.
[   +2 ms]     | stdout:
[  +31 ms]     | | 
[  +72 ms]     | | Microsoft Windows [Version 10.0.18363.778]
[   +1 ms]     | Nothing output on stderr.
[  +47 ms] MSG : Resolving dependencies...
[  +15 ms] SLVR: fact: recursive_root is 1.0.0+1
[   +8 ms] SLVR: derived: recursive_root
[  +39 ms] SLVR: fact: recursive_root depends on flutter any from sdk
[   +8 ms] SLVR: fact: recursive_root depends on cupertino_icons ^0.1.2
[   +1 ms] SLVR: fact: recursive_root depends on google_fonts ^0.2.0
[   +1 ms] SLVR: fact: recursive_root depends on provider 3.0.0
[   +2 ms] SLVR: fact: recursive_root depends on video_player any
[  +14 ms] SLVR: fact: recursive_root depends on neeko any
[   +3 ms] SLVR: fact: recursive_root depends on intl ^0.15.8
[   +1 ms] SLVR: fact: recursive_root depends on http ^0.12.0+2
[   +1 ms] SLVR: fact: recursive_root depends on firebase_auth ^0.14.0+5
[   +1 ms] SLVR: fact: recursive_root depends on cloud_firestore ^0.13.5
[   +1 ms] SLVR: fact: recursive_root depends on firebase_database ^3.1.1
[   +1 ms] SLVR: fact: recursive_root depends on firebase_core ^0.4.4
[   +1 ms] SLVR: fact: recursive_root depends on webview_flutter ^0.3.19+8
[   +1 ms] SLVR: fact: recursive_root depends on url_launcher ^5.4.2
[   +1 ms] SLVR: fact: recursive_root depends on flutter_test any from sdk
[   +1 ms] SLVR:   selecting recursive_root
[   +1 ms] SLVR:   derived: flutter_test any from sdk
[   +1 ms] SLVR:   derived: url_launcher ^5.4.2
[  +10 ms] SLVR:   derived: webview_flutter ^0.3.19+8
[   +1 ms] SLVR:   derived: firebase_core ^0.4.4
[   +1 ms] SLVR:   derived: firebase_database ^3.1.1
[   +2 ms] SLVR:   derived: cloud_firestore ^0.13.5
[   +1 ms] SLVR:   derived: firebase_auth ^0.14.0+5
[  +12 ms] SLVR:   derived: http ^0.12.0+2
[   +1 ms] SLVR:   derived: intl ^0.15.8
[   +9 ms] SLVR:   derived: neeko any
[   +1 ms] SLVR:   derived: video_player any
[   +1 ms] SLVR:   derived: provider 3.0.0
[        ] SLVR:   derived: google_fonts ^0.2.0
[        ] SLVR:   derived: cupertino_icons ^0.1.2
[        ] SLVR:   derived: flutter any from sdk
[        ] SLVR:   fact: flutter_test 0.0.0 from sdk depends on flutter any from sdk
[   +1 ms] SLVR:   fact: flutter_test 0.0.0 from sdk depends on test_api 0.2.11
[   +1 ms] SLVR:   fact: flutter_test 0.0.0 from sdk depends on path 1.6.4
[  +12 ms] SLVR:   fact: flutter_test 0.0.0 from sdk depends on image 2.1.4
[   +1 ms] SLVR:   fact: flutter_test 0.0.0 from sdk depends on quiver 2.0.5
[  +10 ms] SLVR:   fact: flutter_test 0.0.0 from sdk depends on stack_trace 1.9.3
[   +1 ms] SLVR:   fact: flutter_test 0.0.0 from sdk depends on vector_math 2.0.8
[   +1 ms] SLVR:   fact: flutter_test 0.0.0 from sdk depends on archive 2.0.11
[   +1 ms] SLVR:   fact: flutter_test 0.0.0 from sdk depends on args 1.5.2
[   +1 ms] SLVR:   fact: flutter_test 0.0.0 from sdk depends on async 2.4.0
[   +1 ms] SLVR:   fact: flutter_test 0.0.0 from sdk depends on boolean_selector 1.0.5
[   +1 ms] SLVR:   fact: flutter_test 0.0.0 from sdk depends on charcode 1.1.2
[   +2 ms] SLVR:   fact: flutter_test 0.0.0 from sdk depends on collection 1.14.11
[  +19 ms] SLVR:   fact: flutter_test 0.0.0 from sdk depends on convert 2.1.1
[   +1 ms] SLVR:   fact: flutter_test 0.0.0 from sdk depends on crypto 2.1.3
[   +1 ms] SLVR:   fact: flutter_test 0.0.0 from sdk depends on matcher 0.12.6
[        ] SLVR:   fact: flutter_test 0.0.0 from sdk depends on meta 1.1.8
[        ] SLVR:   fact: flutter_test 0.0.0 from sdk depends on pedantic 1.8.0+1
[        ] SLVR:   fact: flutter_test 0.0.0 from sdk depends on petitparser 2.4.0
[  +70 ms] SLVR:   fact: flutter_test 0.0.0 from sdk depends on source_span 1.5.5
[  +27 ms] SLVR:   fact: flutter_test 0.0.0 from sdk depends on stream_channel 2.0.0
[   +2 ms] SLVR:   fact: flutter_test 0.0.0 from sdk depends on string_scanner 1.0.5
[   +1 ms] SLVR:   fact: flutter_test 0.0.0 from sdk depends on term_glyph 1.1.0
[   +1 ms] SLVR:   fact: flutter_test 0.0.0 from sdk depends on typed_data 1.1.6
[   +1 ms] SLVR:   fact: flutter_test 0.0.0 from sdk depends on xml 3.5.0
[   +1 ms] SLVR:     selecting flutter_test 0.0.0 from sdk
[  +11 ms] SLVR:     derived: xml 3.5.0
[   +1 ms] SLVR:     derived: typed_data 1.1.6
[   +1 ms] SLVR:     derived: term_glyph 1.1.0
[   +1 ms] SLVR:     derived: string_scanner 1.0.5
[   +1 ms] SLVR:     derived: stream_channel 2.0.0
[   +1 ms] SLVR:     derived: source_span 1.5.5
[   +1 ms] SLVR:     derived: petitparser 2.4.0
[   +1 ms] SLVR:     derived: pedantic 1.8.0+1
[   +8 ms] SLVR:     derived: meta 1.1.8
[   +1 ms] SLVR:     derived: matcher 0.12.6
[        ] SLVR:     derived: crypto 2.1.3
[        ] SLVR:     derived: convert 2.1.1
[   +1 ms] SLVR:     derived: collection 1.14.11
[   +1 ms] SLVR:     derived: charcode 1.1.2
[   +1 ms] SLVR:     derived: boolean_selector 1.0.5
[   +9 ms] SLVR:     derived: async 2.4.0
[   +1 ms] SLVR:     derived: args 1.5.2
[   +1 ms] SLVR:     derived: archive 2.0.11
[   +1 ms] SLVR:     derived: vector_math 2.0.8
[   +1 ms] SLVR:     derived: stack_trace 1.9.3
[   +2 ms] SLVR:     derived: quiver 2.0.5
[   +8 ms] SLVR:     derived: image 2.1.4
[   +1 ms] SLVR:     derived: path 1.6.4
[        ] SLVR:     derived: test_api 0.2.11
[        ] SLVR:     fact: url_launcher 5.4.2 depends on flutter any from sdk
[   +1 ms] SLVR:     fact: url_launcher 5.4.2 depends on url_launcher_platform_interface ^1.0.4
[   +1 ms] SLVR:     fact: url_launcher 5.4.2 depends on url_launcher_web ^0.1.0+1
[   +2 ms] SLVR:     fact: url_launcher 5.4.2 depends on url_launcher_macos ^0.0.1
[  +13 ms] SLVR:       selecting url_launcher 5.4.2
[   +1 ms] SLVR:       derived: url_launcher_macos ^0.0.1
[   +8 ms] SLVR:       derived: url_launcher_web ^0.1.0+1
[   +1 ms] SLVR:       derived: url_launcher_platform_interface ^1.0.4
[        ] SLVR:       fact: webview_flutter 0.3.19+8 requires Flutter SDK version >=1.12.13+hotfix.5
[        ] SLVR:       derived: not webview_flutter 0.3.19+8
[   +1 ms] IO  : Get versions from https://pub.dartlang.org/api/packages/webview_flutter.
[        ] IO  : HTTP GET https://pub.dartlang.org/api/packages/webview_flutter
[        ]     | Accept: application/vnd.pub.v2+json
[   +1 ms]     | X-Pub-OS: windows
[  +12 ms]     | X-Pub-Command: get
[   +1 ms]     | X-Pub-Session-ID: 844079D5-993F-4056-83D9-7DF2E934C8CD
[   +1 ms]     | X-Pub-Environment: flutter_cli:verify:run
[        ]     | X-Pub-Reason: direct
[   +1 ms]     | user-agent: Dart pub 2.7.0
[+1005 ms] IO  : HTTP response 200 OK for GET https://pub.dartlang.org/api/packages/webview_flutter
[   +3 ms]     | took 0:00:01.077023
[   +2 ms]     | transfer-encoding: chunked
[   +2 ms]     | date: Fri, 24 Apr 2020 18:09:33 GMT
[  +11 ms]     | content-encoding: gzip
[   +1 ms]     | vary: Accept-Encoding
[   +1 ms]     | strict-transport-security: max-age=31536000; preload
[   +1 ms]     | via: 1.1 google
[  +11 ms]     | content-type: application/json; charset="utf-8"
[   +1 ms]     | x-frame-options: SAMEORIGIN
[   +1 ms]     | x-xss-protection: 1; mode=block
[   +1 ms]     | x-content-type-options: nosniff
[   +1 ms]     | server: dart:io with Shelf
[  +22 ms] SLVR:       fact: firebase_core 0.4.4 requires Flutter SDK version >=1.12.13+hotfix.4 <2.0.0
[  +15 ms] SLVR:       derived: not firebase_core 0.4.4
[   +3 ms] IO  : Get versions from https://pub.dartlang.org/api/packages/firebase_core.
[   +1 ms] IO  : HTTP GET https://pub.dartlang.org/api/packages/firebase_core
[   +2 ms]     | Accept: application/vnd.pub.v2+json
[   +2 ms]     | X-Pub-OS: windows
[   +1 ms]     | X-Pub-Command: get
[   +1 ms]     | X-Pub-Session-ID: 844079D5-993F-4056-83D9-7DF2E934C8CD
[   +8 ms]     | X-Pub-Environment: flutter_cli:verify:run
[   +2 ms]     | X-Pub-Reason: direct
[   +1 ms]     | user-agent: Dart pub 2.7.0
[ +519 ms] IO  : HTTP response 200 OK for GET https://pub.dartlang.org/api/packages/firebase_core
[   +4 ms]     | took 0:00:00.556123
[   +6 ms]     | transfer-encoding: chunked
[   +4 ms]     | date: Fri, 24 Apr 2020 18:09:34 GMT
[   +3 ms]     | content-encoding: gzip
[   +2 ms]     | vary: Accept-Encoding
[  +12 ms]     | strict-transport-security: max-age=31536000; preload
[   +1 ms]     | via: 1.1 google
[  +12 ms]     | content-type: application/json; charset="utf-8"
[   +2 ms]     | x-frame-options: SAMEORIGIN
[   +1 ms]     | x-xss-protection: 1; mode=block
[   +3 ms]     | x-content-type-options: nosniff
[   +7 ms]     | server: dart:io with Shelf
[   +1 ms] SLVR:       fact: firebase_database 3.1.1 depends on flutter any from sdk
[   +1 ms] SLVR:       fact: firebase_database 3.1.1 depends on firebase_core ^0.4.0
[   +1 ms] SLVR:         selecting firebase_database 3.1.1
[   +1 ms] SLVR:         fact: cloud_firestore 0.13.5 requires Flutter SDK version >=1.12.13+hotfix.4 <2.0.0
[   +1 ms] SLVR:         derived: not cloud_firestore 0.13.5
[   +1 ms] IO  : Get versions from https://pub.dartlang.org/api/packages/cloud_firestore.
[  +13 ms] IO  : HTTP GET https://pub.dartlang.org/api/packages/cloud_firestore
[   +1 ms]     | Accept: application/vnd.pub.v2+json
[   +8 ms]     | X-Pub-OS: windows
[   +1 ms]     | X-Pub-Command: get
[   +1 ms]     | X-Pub-Session-ID: 844079D5-993F-4056-83D9-7DF2E934C8CD
[   +1 ms]     | X-Pub-Environment: flutter_cli:verify:run
[   +1 ms]     | X-Pub-Reason: direct
[        ]     | user-agent: Dart pub 2.7.0
[ +305 ms] IO  : HTTP response 200 OK for GET https://pub.dartlang.org/api/packages/cloud_firestore
[   +3 ms]     | took 0:00:00.354513
[   +2 ms]     | transfer-encoding: chunked
[   +2 ms]     | date: Fri, 24 Apr 2020 18:09:34 GMT
[   +3 ms]     | content-encoding: gzip
[   +3 ms]     | vary: Accept-Encoding
[  +11 ms]     | strict-transport-security: max-age=31536000; preload
[   +1 ms]     | via: 1.1 google
[  +11 ms]     | content-type: application/json; charset="utf-8"
[   +1 ms]     | x-frame-options: SAMEORIGIN
[   +2 ms]     | x-xss-protection: 1; mode=block
[   +1 ms]     | x-content-type-options: nosniff
[   +2 ms]     | server: dart:io with Shelf
[   +9 ms] SLVR:         fact: no versions of cloud_firestore match >0.13.5 <0.14.0
[   +2 ms] SLVR:         conflict: no versions of cloud_firestore match >0.13.5 <0.14.0
[   +1 ms] SLVR:   derived: not cloud_firestore >0.13.5 <0.14.0
[   +1 ms] SLVR:   conflict: cloud_firestore 0.13.5 requires Flutter SDK version >=1.12.13+hotfix.4 <2.0.0
[  +13 ms] SLVR:   ! cloud_firestore 0.13.5 is partially satisfied by not cloud_firestore >0.13.5 <0.14.0
[   +2 ms] SLVR:   ! which is caused by "no versions of cloud_firestore match >0.13.5 <0.14.0"
[   +2 ms] SLVR:   ! thus: cloud_firestore ^0.13.5 is forbidden
[  +11 ms] SLVR:   ! cloud_firestore ^0.13.5 is satisfied by cloud_firestore ^0.13.5
[   +1 ms] SLVR:   ! which is caused by "recursive_root depends on cloud_firestore ^0.13.5"
[   +1 ms] SLVR:   ! thus: version solving failed
[   +1 ms] SLVR: Version solving took 0:00:02.527346 seconds.
[   +1 ms]     | Tried 1 solutions.
[  +16 ms] FINE: Resolving dependencies finished (2.537s).
[   +2 ms] ERR : The current Flutter SDK version is 1.12.13.
[   +1 ms]     | 
[   +2 ms]     | Because cloud_firestore 0.13.5 requires Flutter SDK version >=1.12.13+hotfix.4 <2.0.0 and no versions of cloud_firestore match  
>0.13.5 <0.14.0, cloud_firestore ^0.13.5 is forbidden.
[   +3 ms]     | So, because recursive_root depends on cloud_firestore ^0.13.5, version solving failed.
[   +1 ms] FINE: Exception type: SolveFailure
[   +1 ms] FINE: package:pub/src/solver/version_solver.dart 308:5   VersionSolver._resolveConflict
[   +1 ms]     | package:pub/src/solver/version_solver.dart 131:27  VersionSolver._propagate
[   +1 ms]     | package:pub/src/solver/version_solver.dart 96:9    VersionSolver.solve
[  +12 ms]     | ===== asynchronous gap ===========================
[   +1 ms]     | dart:async                                         Future.catchError
[   +1 ms]     | package:pub/src/utils.dart 109:52                  captureErrors.<fn>
[   +2 ms]     | package:stack_trace                                Chain.capture
[  +10 ms]     | package:pub/src/utils.dart 122:11                  captureErrors
[   +2 ms]     | package:pub/src/command_runner.dart 171:13         PubCommandRunner.runCommand
[   +3 ms]     | dart:async                                         _completeOnAsyncReturn
[   +9 ms]     | package:pub/src/command_runner.dart                PubCommandRunner._validatePlatform
[   +1 ms]     | dart:async                                         _completeOnAsyncReturn
[        ]     | package:pub/src/io.dart                            runProcess.<fn>
[  +35 ms] Running "flutter pub get" in recursive_root... (completed in 3.1s)
[   +3 ms] "flutter run" took 3,644ms.
pub get failed (1;     | package:pub/src/io.dart                            runProcess.<fn>)

#0      throwToolExit (package:flutter_tools/src/base/common.dart:28:3)
#1      _DefaultPub.batch (package:flutter_tools/src/dart/pub.dart:295:7)
#2      _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:73:64)
#3      _rootRunUnary (dart:async/zone.dart:1134:38)
#4      _CustomZone.runUnary (dart:async/zone.dart:1031:19)
#5      _FutureListener.handleValue (dart:async/future_impl.dart:139:18)
#6      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:680:45)
#7      Future._propagateToListeners (dart:async/future_impl.dart:709:32)
#8      Future._completeWithValue (dart:async/future_impl.dart:524:5)
#9      _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:32:15)
#10     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:290:13)
#11     _DefaultProcessUtils.stream (package:flutter_tools/src/base/process.dart)
#12     _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:73:64)
#13     _rootRunUnary (dart:async/zone.dart:1134:38)
#14     _CustomZone.runUnary (dart:async/zone.dart:1031:19)
#15     _FutureListener.handleValue (dart:async/future_impl.dart:139:18)
#16     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:680:45)
#17     Future._propagateToListeners (dart:async/future_impl.dart:709:32)
#18     Future._addListener.<anonymous closure> (dart:async/future_impl.dart:389:9)
#19     _rootRun (dart:async/zone.dart:1126:13)
#20     _CustomZone.run (dart:async/zone.dart:1023:19)
#21     _CustomZone.runGuarded (dart:async/zone.dart:925:7)
#22     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:965:23)
#23     _microtaskLoop (dart:async/schedule_microtask.dart:43:21)
#24     _startMicrotaskLoop (dart:async/schedule_microtask.dart:52:5)
#25     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
#26     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:175:5)
```

```
```

```[√] Flutter (Channel stable, v1.12.13, on Microsoft Windows [Version 10.0.18363.778], locale en-US)
    • Flutter version 1.12.13 at C:\src\flutter
    • Framework revision cf37c2cd07 (5 months ago), 2019-11-25 12:04:30 -0800
    • Engine revision b6b54fd606
    • Dart version 2.7.0


[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at C:\Users\teeka\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at:
      C:\Users\teeka\AppData\Local\JetBrains\Toolbox\apps\AndroidStudio\ch-0\192.6186006\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)
    • All Android licenses accepted.

[√] Android Studio (version 3.5)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 43.0.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)

[√] Android Studio (version 3.6)
    • Android Studio at C:\Users\teeka\AppData\Local\JetBrains\Toolbox\apps\AndroidStudio\ch-0\192.6186006
    • Flutter plugin version 44.0.2
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)

[√] VS Code (version 1.44.2)
    • VS Code at C:\Users\teeka\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.9.1

[√] Connected device (1 available)
    • motorola one action • ZF6224TQBC • android-arm64 • Android 10 (API 29)

• No issues found!
```

</details>

**Comment by iapicca** [comment]
Hi @teekamsuthar 
for what I can see the issue is related to a FlutterFire plugin,
please open the issue in the dedicated [github](https://github.com/FirebaseExtended/flutterfire/issues).
Closing, as this isn't an issue with Flutter itself,
if you disagree please write in the comments and I will reopen it
thank you
