### ISSUE TITLE
Cloned a new flutter project. I'm getting a 'Could not read script' error.

### ISSUE THREAD

**Issue by rkg0612** [flutter/flutter#55619]
## Steps to Reproduce

1. Run `flutter run`

```
[  +90 ms] executing: [/Users/ralphkleinguevarra/development/flutter/] git -c log.showSignature=false log -n 1
--pretty=format:%H
[ +295 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[   +9 ms] f139b11009aeb8ed2a3a3aa8b0066e482709dde3
[   +3 ms] executing: [/Users/ralphkleinguevarra/development/flutter/] git describe --match v*.*.* --first-parent --long
--tags
[  +28 ms] Exit code 0 from: git describe --match v*.*.* --first-parent --long --tags
[   +1 ms] v1.12.13+hotfix.9-0-gf139b1100
[  +34 ms] executing: [/Users/ralphkleinguevarra/development/flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[  +28 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/stable
[        ] executing: [/Users/ralphkleinguevarra/development/flutter/] git ls-remote --get-url origin
[  +31 ms] Exit code 0 from: git ls-remote --get-url origin
[   +1 ms] https://github.com/flutter/flutter.git
[ +179 ms] executing: [/Users/ralphkleinguevarra/development/flutter/] git rev-parse --abbrev-ref HEAD
[  +33 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] stable
[  +35 ms] executing: sw_vers -productName
[  +50 ms] Exit code 0 from: sw_vers -productName
[   +1 ms] Mac OS X
[        ] executing: sw_vers -productVersion
[  +32 ms] Exit code 0 from: sw_vers -productVersion
[        ] 10.15.4
[        ] executing: sw_vers -buildVersion
[  +29 ms] Exit code 0 from: sw_vers -buildVersion
[   +1 ms] 19E287
[  +79 ms] executing: /usr/bin/xcode-select --print-path
[  +17 ms] Exit code 0 from: /usr/bin/xcode-select --print-path
[   +1 ms] /Library/Developer/CommandLineTools
[   +2 ms] executing: /usr/bin/xcodebuild -version
[  +12 ms] Exit code 1 from: /usr/bin/xcodebuild -version
[   +1 ms] xcode-select: error: tool 'xcodebuild' requires Xcode, but active developer directory
'/Library/Developer/CommandLineTools' is a command line tools instance
[ +253 ms] executing: /Users/ralphkleinguevarra/Library/Android/sdk/platform-tools/adb devices -l
[  +27 ms] Exit code 0 from: /Users/ralphkleinguevarra/Library/Android/sdk/platform-tools/adb devices -l
[   +2 ms] List of devices attached
           emulator-5554          device product:sdk_gphone_x86 model:Android_SDK_built_for_x86 device:generic_x86
           transport_id:1
[  +94 ms] executing: /Users/ralphkleinguevarra/development/flutter/bin/cache/artifacts/libimobiledevice/idevice_id -h
[ +158 ms] executing: /usr/bin/xcodebuild -version
[  +10 ms] Exit code 1 from: /usr/bin/xcodebuild -version
[        ] xcode-select: error: tool 'xcodebuild' requires Xcode, but active developer directory
'/Library/Developer/CommandLineTools' is a command line tools instance
[  +35 ms] /Users/ralphkleinguevarra/Library/Android/sdk/platform-tools/adb -s emulator-5554 shell getprop
[  +99 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[  +20 ms] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[  +32 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[+1183 ms] Generating /Users/ralphkleinguevarra/Projects/patient-portal/android/app/src/main/java/io/flutter/plugins/GeneratedPluginRegistrant.java
[ +385 ms] ro.hardware = ranchu
[ +463 ms] executing: /usr/bin/xcodebuild -version
[ +227 ms] Exit code 1 from: /usr/bin/xcodebuild -version
[        ] xcode-select: error: tool 'xcodebuild' requires Xcode, but active developer directory '/Library/Developer/CommandLineTools' is a command line tools instance
[ +141 ms] Using hardware rendering with device Android SDK built for x86. If you get graphics artifacts, consider enabling software rendering with "--enable-software-rendering".
[  +53 ms] Launching lib/main.dart on Android SDK built for x86 in debug mode...
[  +34 ms] executing: /Users/ralphkleinguevarra/Library/Android/sdk/platform-tools/adb -s emulator-5554 shell -x logcat -v time -t 1
[ +112 ms] Exit code 0 from: /Users/ralphkleinguevarra/Library/Android/sdk/platform-tools/adb -s emulator-5554 shell -x logcat -v time -t 1
[        ] --------- beginning of system
           04-25 10:20:09.800 W/AppOps  ( 2000): Noting op not finished: uid 10102 pkg com.google.android.gms code 41 time=1587781204179 duration=0
[  +21 ms] executing: /Users/ralphkleinguevarra/Library/Android/sdk/platform-tools/adb version
[   +5 ms] executing: /Users/ralphkleinguevarra/Library/Android/sdk/platform-tools/adb -s emulator-5554 logcat -v time -T 04-25 10:20:09.800
[  +50 ms] Android Debug Bridge version 1.0.41
           Version 30.0.0-6374843
           Installed as /Users/ralphkleinguevarra/Library/Android/sdk/platform-tools/adb
[   +8 ms] executing: /Users/ralphkleinguevarra/Library/Android/sdk/platform-tools/adb start-server
[  +49 ms] Building APK
[  +55 ms] Running Gradle task 'assembleDebug'...
[   +3 ms] gradle.properties already sets `android.enableR8`
[  +14 ms] Using gradle from /Users/ralphkleinguevarra/Projects/patient-portal/android/gradlew.
[  +29 ms] executing: /usr/bin/plutil -convert json -o - /Applications/Android Studio.app/Contents/Info.plist
[  +65 ms] Exit code 0 from: /usr/bin/plutil -convert json -o - /Applications/Android Studio.app/Contents/Info.plist
[   +1 ms] {"CFBundleName":"Android
Studio","JVMOptions":{"ClassPath":"$APP_PACKAGE\/Contents\/lib\/bootstrap.jar:$APP_PACKAGE\/Contents\/lib\/extensions.jar:$APP_PACKAGE\/Contents\/lib\/util.jar:$APP_PACKAGE\/Contents\/lib\/jdom.jar:$APP_PACKAGE\/Contents\/lib\/log4j.jar:$
APP_PACKAGE\/Contents\/lib\/trove4j.jar:$APP_PACKAGE\/Contents\/lib\/jna.jar","JVMVersion":"1.8*,1.8+","WorkingDirectory":"$APP_PACKAGE\/Contents\/bin","MainClass":"com.intellij.idea.Main","Properties":{"idea.paths.selector":"AndroidStudi
o3.6","idea.executable":"studio","idea.platform.prefix":"AndroidStudio","idea.home.path":"$APP_PACKAGE\/Contents"}},"NSDesktopFolderUsageDescription":"An application in Android Studio requests access to the user's Desktop
folder.","LSArchitecturePriority":["x86_64"],"CFBundleVersion":"AI-192.7142.36.36.6241897","CFBundleDevelopmentRegion":"English","NSCameraUsageDescription":"An application in Android Studio requests access to the device's
camera.","CFBundleDocumentTypes":[{"CFBundleTypeName":"Android Studio Project File","CFBundleTypeExtensions":["ipr"],"CFBundleTypeRole":"Editor","CFBundleTypeIconFile":"studio.icns"},{"CFBundleTypeName":"All
documents","CFBundleTypeExtensions":["*"],"CFBundleTypeOSTypes":["****"],"CFBundleTypeRole":"Editor","LSTypeIsPackage":false}],"NSSupportsAutomaticGraphicsSwitching":true,"CFBundlePackageType":"APPL","CFBundleIconFile":"studio.icns","NSHi
ghResolutionCapable":true,"CFBundleShortVersionString":"3.6","NSMicrophoneUsageDescription":"An application in Android Studio requests access to the device's
microphone.","CFBundleInfoDictionaryVersion":"6.0","CFBundleExecutable":"studio","NSLocationUsageDescription":"An application in Android Studio requests access to the user's location
information.","LSRequiresNativeExecution":"YES","CFBundleURLTypes":[{"CFBundleTypeRole":"Editor","CFBundleURLName":"Stacktrace","CFBundleURLSchemes":["idea"]}],"CFBundleIdentifier":"com.google.android.studio","LSApplicationCategoryType":"
public.app-category.developer-tools","CFBundleSignature":"????","LSMinimumSystemVersion":"10.8","NSDocumentsFolderUsageDescription":"An application in Android Studio requests access to the user's Documents
folder.","NSDownloadsFolderUsageDescription":"An application in Android Studio requests access to the user's Downloads folder.","NSNetworkVolumesUsageDescription":"An application in Android Studio requests access to files on a network
volume.","CFBundleGetInfoString":"Android Studio 3.6, build AI-192.7142.36.36.6241897. Copyright JetBrains s.r.o., (c) 2000-2020","NSRemovableVolumesUsageDescription":"An application in Android Studio requests access to files on a
removable volume."}
[  +47 ms] executing: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java -version
[ +181 ms] Exit code 0 from: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java -version
[   +2 ms] openjdk version "1.8.0_212-release"
           OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
           OpenJDK 64-Bit Server VM (build 25.212-b4-5784211, mixed mode)
[   +7 ms] executing: [/Users/ralphkleinguevarra/Projects/patient-portal/android/] /Users/ralphkleinguevarra/Projects/patient-portal/android/gradlew -Pverbose=true -Ptarget=/Users/ralphkleinguevarra/Projects/patient-portal/lib/main.dart
-Ptrack-widget-creation=true -Pfilesystem-scheme=org-dartlang-root -Ptarget-platform=android-x86 assembleDebug
[+1314 ms] Welcome to Gradle 5.6.2!
[        ] Here are the highlights of this release:
[   +1 ms]  - Incremental Groovy compilation
[   +1 ms]  - Groovy compile avoidance
[        ]  - Test fixtures for Java projects
[   +1 ms]  - Manage plugin versions via settings script
[   +1 ms] For more details see https://docs.gradle.org/5.6.2/release-notes.html
[ +771 ms] FAILURE: Build failed with an exception.
[   +2 ms] * Where:
[        ] Settings file '/Users/ralphkleinguevarra/Projects/patient-portal/android/settings.gradle' line: 15
[   +1 ms] * What went wrong:
[        ] A problem occurred evaluating settings 'android'.
[        ] > Could not read script '/Users/ralphkleinguevarra/development/flutter/packages/flutter_tools/gradle/app_plugin_loader.gradle' as it does not exist.
[        ] * Try:
[        ] Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
[        ] * Get more help at https://help.gradle.org
[        ] BUILD FAILED in 1s
[ +455 ms] Running Gradle task 'assembleDebug'... (completed in 2.9s)
[  +17 ms] "flutter run" took 6,785ms.
Gradle task assembleDebug failed with exit code 1

#0      throwToolExit (package:flutter_tools/src/base/common.dart:28:3)
#1      buildGradleApp (package:flutter_tools/src/android/gradle.dart:387:7)
#2      _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:73:64)
#3      _rootRunUnary (dart:async/zone.dart:1134:38)
#4      _CustomZone.runUnary (dart:async/zone.dart:1031:19)
#5      _FutureListener.handleValue (dart:async/future_impl.dart:139:18)
#6      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:680:45)
#7      Future._propagateToListeners (dart:async/future_impl.dart:709:32)
#8      Future._completeWithValue (dart:async/future_impl.dart:524:5)
#9      _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:32:15)
#10     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:290:13)
#11     _DefaultProcessUtils.stream (package:flutter_tools/src/base/process.dart)
#12     _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:73:64)
#13     _rootRunUnary (dart:async/zone.dart:1134:38)
#14     _CustomZone.runUnary (dart:async/zone.dart:1031:19)
#15     _FutureListener.handleValue (dart:async/future_impl.dart:139:18)
#16     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:680:45)
#17     Future._propagateToListeners (dart:async/future_impl.dart:709:32)
#18     Future._completeWithValue (dart:async/future_impl.dart:524:5)
#19     Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:554:7)
#20     _rootRun (dart:async/zone.dart:1126:13)
#21     _CustomZone.run (dart:async/zone.dart:1023:19)
#22     _CustomZone.runGuarded (dart:async/zone.dart:925:7)
#23     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:965:23)
#24     _microtaskLoop (dart:async/schedule_microtask.dart:43:21)
#25     _startMicrotaskLoop (dart:async/schedule_microtask.dart:52:5)
#26     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
#27     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:175:5)
```

I just cloned a new project from our team's repository and I cannot get it to run in my local machine. I've navigated to `/flutter_tools/gradle` and the file `app_plugin_loader.gradle` is not present. Did I miss something or should I run something? Thank you!

**Comment by Fobalteam2020** [comment]
oh oh, i'm just same problem

**Comment by soloman97** [comment]
Same problem here!

**Comment by mihirpkshah** [comment]
Same problem!!!

**Comment by jonahwilliams** [comment]
Please include the output of `flutter doctor -v`.

If you're also seeing this issue, you can certainly provide more details. But please prefer upvoting the original issue as opposed to short comments like "same" since these unnecessarily ping everyone on the thread.

**Comment by mihirpkshah** [comment]
The output of `flutter doctor -v`

> flutter doctor -v
> [√] Flutter (Channel stable, v1.12.13+hotfix.9, on Microsoft Windows
>     [Version 10.0.18363.778], locale en-IN)
>     • Flutter version 1.12.13+hotfix.9 at C:\Users\mihir\Programs\flutter    • Framework revision f139b11009 (4 weeks ago), 2020-03-30 13:57:30
>       -0700
>     • Engine revision af51afceb8
>     • Dart version 2.7.2
> 
>  
> [√] Android toolchain - develop for Android devices (Android SDK version 
>     28.0.3)
>     • Android SDK at C:\Users\mihir\AppData\Local\Android\sdk
>     • Android NDK location not configured (optional; useful for native
>       profiling support)
>     • Platform android-28, build-tools 28.0.3
>     • Java binary at: C:\Program Files\Android\Android
>       Studio\jre\bin\java
>     • Java version OpenJDK Runtime Environment (build
>       1.8.0_152-release-1343-b01)
>     • All Android licenses accepted.
> 
> [√] Android Studio (version 3.4)
>     • Android Studio at C:\Program Files\Android\Android Studio
>     • Flutter plugin version 38.2.1
>     • Dart plugin version 183.6270
>     • Java version OpenJDK Runtime Environment (build
>       1.8.0_152-release-1343-b01)
> 
> [!] IntelliJ IDEA Community Edition (version 2017.3)
>     • IntelliJ at C:\Users\mihir\Downloads\ideaIC-2017.3.5.win
>     X Flutter plugin not installed; this adds Flutter specific
>       functionality.
>     X Dart plugin not installed; this adds Dart specific functionality.  
>     • For information about installing plugins, see
>       https://flutter.dev/intellij-setup/#installing-the-plugins
> 
> [√] VS Code (version 1.44.2)
>     • VS Code at C:\Users\mihir\AppData\Local\Programs\Microsoft VS Code
>     • Flutter extension version 3.9.1
> 
> [√] Connected device (1 available)
>     • Android SDK built for x86 • emulator-5554 • android-x86 • Android
>       7.0 (API 24) (emulator)
> 
> ! Doctor found issues in 1 category.

Error Output (In Short) :

> FAILURE: Build failed with an exception.
> 
> * Where:
> Settings file 'C:\Users\mihir\Documents\Programming\Flutter\wowparenting\android\settings.gradle' line: 15
> 
> * What went wrong:
> A problem occurred evaluating settings 'android'.
> > Could not read script 'C:\Users\mihir\Programs\flutter\packages\flutter_tools\gradle\app_plugin_loader.gradle' as it does not exist.

**Comment by rkg0612** [comment]
Hi,

I solved mine by switching my Flutter branch to master. Please check if it also solves your problem.

**Comment by iapicca** [comment]
Hi @rkg0612 
could you please provide a code sample 
to test on which flutter version the issue persists?
Thank you

**Comment by rkg0612** [comment]
> Hi @rkg0612
> could you please provide a code sample
> to test on which flutter version the issue persists?
> Thank you

The error persists when I switch my flutter branch to `stable`. The `master` branch solves my problem.

**Comment by iapicca** [comment]
Thank you @rkg0612 
closing the issue as solved

**Comment by gitboss** [comment]
I'm experiencing the exact same issue after switching from master to stable. I was working on master when I read Flutter 1.17 stable is released so I switched to stable and upgraded to 1.17. After this point I started to face the issue in all projects that I had worked on while on master. All the other projects that I did not open in master compiled normally.

**Comment by jmagman** [comment]
The android/settings.gradle migration in https://github.com/flutter/flutter/pull/54407 points to a new file in the Flutter tool that's present in 1.18.0-dev.5.0 ([master, dev, and beta channels](https://flutter.dev/docs/development/tools/sdk/releases)) but not stable.  Essentially by going from master -> stable it "downgraded" Flutter tool, but didn't reverse that migration.

**Comment by jmagman** [comment]
You can work around this by regenerating your `android/settings.gradle` while on stable (make sure you're using source control!).
```
$rm android/settings.gradle
$ flutter create .
```

**Comment by gitboss** [comment]
> 
> 
> You can work around this by regenerating your `android/settings.gradle` while on stable (make sure you're using source control!).
> 
> ```
> $ rm android/settings.gradle
> $ flutter create .
> ```

Thank you, your solution worked for me.

**Comment by GeekOnHeels01** [comment]
I replaced the content of /android/settings.gradle with this:

`include ':app'

def flutterProjectRoot = rootProject.projectDir.parentFile.toPath()

def plugins = new Properties()
def pluginsFile = new File(flutterProjectRoot.toFile(), '.flutter-plugins')
if (pluginsFile.exists()) {
    pluginsFile.withReader('UTF-8') { reader -> plugins.load(reader) }
}

plugins.each { name, path ->
    def pluginDirectory = flutterProjectRoot.resolve(path).resolve('android').toFile()
    include ":$name"
    project(":$name").projectDir = pluginDirectory
}
`

and it worked!

**Comment by GeekOnHeels01** [comment]
I replaced the content of **_android/settings.gradle_** with the below while on _**stable channel**_ and it worked
                                        -----------------

include ':app'

def flutterProjectRoot = rootProject.projectDir.parentFile.toPath()

def plugins = new Properties()
def pluginsFile = new File(flutterProjectRoot.toFile(), '.flutter-plugins')
if (pluginsFile.exists()) {
    pluginsFile.withReader('UTF-8') { reader -> plugins.load(reader) }
}

plugins.each { name, path ->
    def pluginDirectory = flutterProjectRoot.resolve(path).resolve('android').toFile()
    include ":$name"
    project(":$name").projectDir = pluginDirectory
}

**Comment by rvndsngwn** [comment]
> I replaced the content of **_android/settings.gradle_** with the below while on _**stable channel**_ and it worked
> -----------------
> 
> include ':app'
> 
> def flutterProjectRoot = rootProject.projectDir.parentFile.toPath()
> 
> def plugins = new Properties()
> def pluginsFile = new File(flutterProjectRoot.toFile(), '.flutter-plugins')
> if (pluginsFile.exists()) {
> pluginsFile.withReader('UTF-8') { reader -> plugins.load(reader) }
> }
> 
> plugins.each { name, path ->
> def pluginDirectory = flutterProjectRoot.resolve(path).resolve('android').toFile()
> include ":$name"
> project(":$name").projectDir = pluginDirectory
> }

it's working perfectly.

**Comment by zebudummy** [comment]
what is the solution to this problem? 
+6472 ms] FAILURE: Build failed with an exception.
[   +3 ms] * Where:
[        ] Settings file 'C:\all_flutter_projects\shopping_sqflite\android\settings.gradle' line: 15
[        ] * What went wrong:
[        ] A problem occurred evaluating settings 'android'.
[ +173 ms] > Could not read script 'C:\flutterSDK\flutter\packages\flutter_tools\gradle\app_plugin_loader.gradle' as it does not exist.
[        ] * Try:
[   +5 ms] Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
[   +2 ms] * Get more help at https://help.gradle.org
[        ] BUILD FAILED in 5s

**Comment by rvndsngwn** [comment]
you need to convert your flutter stable channel to a flutter beta channel. maybe it's worked I think so.

**Comment by Atishayjain172** [comment]
> You can work around this by regenerating your `android/settings.gradle` while on stable (make sure you're using source control!).
> 
> ```
> $ rm android/settings.gradle
> $ flutter create .
> ```

how can i do that??
Explain(New to git)

**Comment by mutantkeyboard** [comment]
@Atishayjain172 what do you mean? You simply navigate to the repository by using terminal (depending on your OS), and type `rm android/settings.gradle` and press Enter. After that you type `flutter create .` (don't forget the dot) and Enter. 
It has nothing to do with the Git.

**Comment by gajesss** [comment]
> You can work around this by regenerating your `android/settings.gradle` while on stable (make sure you're using source control!).
> 
> ```
> $ rm android/settings.gradle
> $ flutter create .
> ```

where to run on android studio?

**Comment by ajilo297** [comment]
> You can work around this by regenerating your `android/settings.gradle` while on stable (make sure you're using source control!).
> 
> ```
> $ rm android/settings.gradle
> $ flutter create .
> ```

This did not work for me. Created issue #63387 with details

**Comment by salah-rashad** [comment]
> where to run on android studio?

@gajesss run in Android Studio terminal (located in the bottom bar) while your project open.

**Comment by ChiGlobal** [comment]
> You can work around this by regenerating your `android/settings.gradle` while on stable (make sure you're using source control!).
> 
> ```
> $ rm android/settings.gradle
> $ flutter create .
> ```

how do I do this on windows?

**Comment by dheerajmpai** [comment]
> > You can work around this by regenerating your `android/settings.gradle` while on stable (make sure you're using source control!).
> > ```
> > $ rm android/settings.gradle
> > $ flutter create .
> > ```
> 
> how do I do this on windows?

Go to the directory and delete manually

or 

You can go to the command prompt and use 

```
del android/settings.gradle
```

**Comment by dheerajmpai** [comment]
I was getting this error in the github actions. I changed the flutter version from `1.12` to `1.20` and the issue was solved

**Comment by ChiGlobal** [comment]
@dheerajmpai thanks🙏🏼

**Comment by vikilog** [comment]
i was facing the same issue and its because of mismatched path of flutter sdk in local.properties.make sure it is correct for your system as it include username in path and username is different for each system

**Comment by 852172891** [comment]
i use my local  build sucess project \android\settings.gradle  file replace   the cloned project settings.gradle file. the issue was solved

**Comment by allansrc** [comment]
Please make sure that your local.prorperties/keys.properties files has the correct path to your flutter sdk directory, and then, to "packages/flutter_tools/..."

**Comment by Pointdexter99** [comment]
Change all your contents from the settings.gradle file to the following code:

include ':app'

def flutterProjectRoot = rootProject.projectDir.parentFile.toPath()

def plugins = new Properties()
def pluginsFile = new File(flutterProjectRoot.toFile(), '.flutter-plugins')
if (pluginsFile.exists()) {
    pluginsFile.withReader('UTF-8') { reader -> plugins.load(reader) }
}

plugins.each { name, path ->
    def pluginDirectory = flutterProjectRoot.resolve(path).resolve('android').toFile()
    include ":$name"
    project(":$name").projectDir = pluginDirectory
}
This worked for me.!

**Comment by raghavnautiyal** [comment]
None of the solutions are working for me. 

I have tried all of the solutions mentioned here, but they change nothing.

**Comment by alex9153** [comment]
1) close Android Studio
2) in VS Code make Clean Project
3) run the project on device via VS Code

**Comment by raghavnautiyal** [comment]
The solution that worked for me was reinstalling flutter.

**Comment by JaiAravindh-git** [comment]
### Try Doing This :

**Run these commands one after the other** 

`flutter channel dev`
`flutter upgrade`
`flutter clean`



> Restart the console and check for any errors.

**Comment by TFComplex** [comment]
Just changing Replace the SDK path in Local.properties .

**Comment by mickykebe** [comment]
In my case this was an OS problem. Was able to confirm the file exists by checking manually. Yet it was still throwing up this error. Restarted my mac and ran the project and worked.

**Comment by ChopinDavid** [comment]
For me, I had renamed my local user name on my Mac. The fix for me was to change `.android/local.properties` line 2: `flutter.sdk=/Users/oldUserName/flutter` to `flutter.sdk=/Users/newUserName/flutter`
