### ISSUE TITLE
Tapping this a few times blows up the framework.

### ISSUE THREAD

**Issue by apwilson** [flutter/flutter#5562]
For some reason, this will throw an exception when run and the gesture detector tap is triggered twice.

``` dart
Future main() async {
  runApp(new Foo());
}

class Foo extends StatefulWidget {
  @override
  FooState createState() => new FooState();
}

class FooState extends State<Foo> {
  BoxConstraints _currentConstraint =
      const BoxConstraints.tightFor(width: 440.0, height: 440.0 * 16.0 / 9.0);
  @override
  Widget build(BuildContext context) {
    return new Center(
        child: new ConstrainedBox(
            constraints: _currentConstraint,
            child: new LayoutBuilder(
                builder: (BuildContext context, BoxConstraints constraints) {
              return new Stack(children: [
                new Align(
                    alignment: FractionalOffset.bottomCenter,
                    child: new ClipRect(
                        child: new ConstrainedBox(
                            constraints: new BoxConstraints(
                                minWidth: constraints.maxWidth,
                                maxWidth: constraints.maxWidth,
                                minHeight: 300.0,
                                maxHeight: 300.0),
                            child: new OverflowBox(
                                minWidth: constraints.maxWidth,
                                maxWidth: constraints.maxWidth,
                                minHeight: 300.0,
                                maxHeight: 300.0,
                                alignment: FractionalOffset.topCenter,
                                child: new Container(
                                    decoration: new BoxDecoration(
                                        backgroundColor:
                                            new Color(0xFFFFFF00))))))),
                new Positioned(
                    top: 0.0,
                    left: 0.0,
                    right: 0.0,
                    height: constraints.maxHeight - 300.0,
                    child: new GestureDetector(
                        onTap: () => setState(() {
                              if (_currentConstraint ==
                                  const BoxConstraints()) {
                                _currentConstraint =
                                    const BoxConstraints.tightFor(
                                        width: 440.0,
                                        height: 440.0 * 16.0 / 9.0);
                              } else {
                                _currentConstraint = const BoxConstraints();
                              }
                              print('tap!');
                            })))
              ]);
            })));
  }
}
```

Full exception log is as follows:

```
14:15:06.629: Waiting for application to start...                  0.0s
14:15:06.631: Restart time: 1160 ms
14:15:08.669: I/flutter : tap!
14:15:09.257: I/flutter : tap!
14:15:09.300: I/flutter : ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
14:15:09.305: I/flutter : The following assertion was thrown building LayoutBuilder:
14:15:09.316: I/flutter : 'package:flutter/src/rendering/object.dart': Failed assertion: line 1259 pos 14:
14:15:09.318: I/flutter : 'node._relayoutBoundary == _relayoutBoundary' is not true.
14:15:09.397: I/flutter : When the exception was thrown, this was the stack:
14:15:09.409: I/flutter : #2      RenderObject._debugSubtreeRelayoutRootAlreadyMarkedNeedsLayout (package:flutter/src/rendering/object.dart:1259:14)
14:15:09.412: I/flutter : #3      RenderObject.markNeedsLayout (package:flutter/src/rendering/object.dart:1306:14)
14:15:09.415: I/flutter : #4      RenderBox.markNeedsLayout (package:flutter/src/rendering/box.dart:1104:26)
14:15:09.418: I/flutter : #5      Positioned.applyParentData (package:flutter/src/widgets/basic.dart:1578:22)
14:15:09.420: I/flutter : #6      RenderObjectElement._updateParentData (package:flutter/src/widgets/framework.dart:2554:16)
14:15:09.423: I/flutter : #7      ParentDataElement.notifyClients.notifyChildren (package:flutter/src/widgets/framework.dart:2251:15)
14:15:09.426: I/flutter : #8      ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:2029:14)
14:15:09.429: I/flutter : #9      ParentDataElement.notifyClients.notifyChildren (package:flutter/src/widgets/framework.dart:2254:15)
14:15:09.431: I/flutter : #10     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:2029:14)
14:15:09.434: I/flutter : #11     ParentDataElement.notifyClients.notifyChildren (package:flutter/src/widgets/framework.dart:2254:15)
14:15:09.437: I/flutter : #12     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:2029:14)
14:15:09.440: I/flutter : #13     ParentDataElement.notifyClients (package:flutter/src/widgets/framework.dart:2257:5)
14:15:09.442: I/flutter : #14     _ProxyElement.update (package:flutter/src/widgets/framework.dart:2202:5)
14:15:09.445: I/flutter : #15     Element.updateChild (package:flutter/src/widgets/framework.dart:1432:15)
14:15:09.448: I/flutter : #16     RenderObjectElement.updateChildren (package:flutter/src/widgets/framework.dart:2440:26)
14:15:09.451: I/flutter : #17     MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:2768:17)
14:15:09.454: I/flutter : #18     Element.updateChild (package:flutter/src/widgets/framework.dart:1432:15)
14:15:09.457: I/flutter : #19     _LayoutBuilderElement._layout.<anonymous closure> (package:flutter/src/widgets/layout_builder.dart:187:18)
14:15:09.460: I/flutter : #20     BuildOwner.lockState (package:flutter/src/widgets/framework.dart:1224:15)
14:15:09.462: I/flutter : #21     _LayoutBuilderElement._layout (package:flutter/src/widgets/layout_builder.dart:176:11)
14:15:09.465: I/flutter : #22     RenderObject.invokeLayoutCallback (package:flutter/src/rendering/object.dart:1596:15)
14:15:09.468: I/flutter : #23     _RenderLayoutBuilder.performLayout (package:flutter/src/widgets/layout_builder.dart:106:7)
14:15:09.471: I/flutter : #24     RenderObject.layout (package:flutter/src/rendering/object.dart:1511:21)
14:15:09.473: I/flutter : #25     RenderConstrainedBox.performLayout (package:flutter/src/rendering/proxy_box.dart:241:13)
14:15:09.476: I/flutter : #26     RenderObject.layout (package:flutter/src/rendering/object.dart:1511:21)
14:15:09.479: I/flutter : #27     RenderPositionedBox.performLayout (package:flutter/src/rendering/shifted_box.dart:336:13)
14:15:09.481: I/flutter : #28     RenderObject._layoutWithoutResize (package:flutter/src/rendering/object.dart:1389:21)
14:15:09.484: I/flutter : #29     PipelineOwner.flushLayout (package:flutter/src/rendering/object.dart:874:18)
14:15:09.485: I/flutter : #30     BindingBase&SchedulerBinding&GestureBinding&ServicesBinding&RendererBinding.beginFrame (package:flutter/src/rendering/binding.dart:154:19)
14:15:09.488: I/flutter : #31     BindingBase&SchedulerBinding&GestureBinding&ServicesBinding&RendererBinding&WidgetsBinding.beginFrame (package:flutter/src/widgets/binding.dart:210:21)
14:15:09.490: I/flutter : #32     BindingBase&SchedulerBinding&GestureBinding&ServicesBinding&RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:146:5)
14:15:09.492: I/flutter : #33     BindingBase&SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:535:15)
14:15:09.494: I/flutter : #34     BindingBase&SchedulerBinding.handleBeginFrame (package:flutter/src/scheduler/binding.dart:495:7)
14:15:09.496: I/flutter : #35     _beginFrame (file:///b/build/slave/Linux_Engine/build/src/flutter/lib/ui/hooks.dart:48)
14:15:09.499: I/flutter : (elided 2 frames from class _AssertionError)
14:15:09.501: I/flutter : ════════════════════════════════════════════════════════════════════════════════════════════════════

```

**Comment by apwilson** [comment]
This also blows up with the same assertion on first tap:

```dart
Future main() async {
  runApp(new Foo());
}

class Foo extends StatefulWidget {
  @override
  FooState createState() => new FooState();
}

const BoxConstraints constraint1 = const BoxConstraints.tightFor();
const BoxConstraints constraint2 =
    const BoxConstraints.tightFor(width: 440.0, height: 440.0);

class FooState extends State<Foo> {
  BoxConstraints _currentConstraint = constraint1;
  @override
  Widget build(BuildContext context) {
    return new Center(
        child: new ConstrainedBox(
            constraints: _currentConstraint,
            child: new LayoutBuilder(
                builder: (BuildContext context, BoxConstraints constraints) {
              return new Stack(children: [
                new Container(
                    width: constraints.maxWidth,
                    decoration: new BoxDecoration(
                        backgroundColor: new Color(0xFFFFFF00))),
                new Container(
                    height: constraints.maxHeight,
                    decoration: new BoxDecoration(
                        backgroundColor: new Color(0xFFFF00FF)),
                    child: new GestureDetector(
                        onTap: () => setState(() {
                              if (_currentConstraint == constraint2) {
                                _currentConstraint = constraint1;
                              } else {
                                _currentConstraint = constraint2;
                              }
                              print('tap!');
                            })))
              ]);
            })));
  }
}
```

**Comment by Hixie** [comment]
Are you sure the second one has the same stack? It doesn't have a Positioned in it, but the first stack is all about the Positioned.

**Comment by apwilson** [comment]
Well its not the same - I included the stack with it

**Comment by Hixie** [comment]
Fascinating.

**Comment by jonahwilliams** [comment]
Running this code today (swapping backgroundColor for color in the container) I do not get any exception, and I can confirm that tapping alternates branches correctly in the onTap callback. I'm going to close this, please reopen if you disagree
