### ISSUE TITLE
`CupertinoDatePicker` throw exception when parent height is 0

### ISSUE THREAD

**Issue by philipdolenko** [flutter/flutter#55630]
## Steps to Reproduce

1. Run `flutter create bug`.
2. Update the files as follows: main.dart -> change body of Scaffold to 
```
body: Container(
        height: 0,
        width: double.infinity,
        child: CupertinoDatePicker(onDateTimeChanged: (_){}),
      )
```

**Actual results:** 
```
flutter: ══╡ EXCEPTION CAUGHT BY RENDERING LIBRARY ╞═════════════════════════════════════════════════════════
flutter: The following assertion was thrown during paint():
flutter: 'package:flutter/src/rendering/layer.dart': Failed assertion: line 1627 pos 12:
flutter: 'value.storage.every((double component) => component.isFinite)': is not true.
flutter:
flutter: Either the assertion indicates an error in the framework itself, or we should provide substantially
flutter: more information in this error message to help you determine and fix the underlying cause.
flutter: In either case, please report this assertion by filing a bug on GitHub:
flutter:   https://github.com/flutter/flutter/issues/new?template=BUG.md

```

So this exception doesn't crash the app and has no effect on ui, I have already fix that issue in my app. The only reason that I'm here is just that exception itself says me to open this bug on Github.
<details>
  <summary>Logs</summary>

```
```

```
flutter analyze
Analyzing bug...                                                             

   info • The value of the field '_counter' isn't used •
          lib/main.dart:54:7 • unused_field

1 issue found. (ran in 2.4s)
```

```
flutter doctor -v
[✓] Flutter (Channel beta, v1.17.0-3.2.pre, on Mac OS X 10.15.3
    19D76, locale en-UA)
    • Flutter version 1.17.0-3.2.pre at
      /Users/philipdolenko/Documents/tools/flutter
    • Framework revision 2a7bc389f2 (3 days ago), 2020-04-21 20:34:20
      -0700
    • Engine revision 4c8c31f591
    • Dart version 2.8.0 (build 2.8.0-dev.20.10)

[!] Android toolchain - develop for Android devices (Android SDK
    version 29.0.2)
    • Android SDK at /Users/philipdolenko/Library/Android/sdk
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_202-release-1483-b49-5587405)
    ✗ Android license status unknown.
      Try re-installing or updating your Android SDK Manager.
      See https://developer.android.com/studio/#downloads or visit
      visit
      https://flutter.dev/docs/get-started/install/macos#android-setu
      p for detailed instructions.

[✓] Xcode - develop for iOS and macOS (Xcode 11.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.4.1, Build version 11E503a
    • CocoaPods version 1.8.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google
      Chrome

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 43.0.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build
      1.8.0_202-release-1483-b49-5587405)

[!] Android Studio
    • Android Studio at /Applications/Android Studio 4.0
      Preview.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific
      functionality.
    ✗ Dart plugin not installed; this adds Dart specific
      functionality.
    • Java version OpenJDK Runtime Environment (build
      1.8.0_212-release-1586-b4-5784211)

[!] IntelliJ IDEA Ultimate Edition (version 2017.3.5)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    ✗ Flutter plugin not installed; this adds Flutter specific
      functionality.
    ✗ Dart plugin not installed; this adds Dart specific
      functionality.
    • For information about installing plugins, see
      https://flutter.dev/intellij-setup/#installing-the-plugins

[✓] VS Code (version 1.44.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.9.1

 
[✓] Connected device (4 available)            
    • SM G960F          • 1cb4d78401027ece                     •
      android-arm64  • Android 10 (API 29)
    • iPhone 11 Pro Max • 1A206576-8C68-40AB-B779-961A7FFCB5C3 • ios
      • com.apple.CoreSimulator.SimRuntime.iOS-13-4 (simulator)
    • Chrome            • chrome                               •
      web-javascript • Google Chrome 81.0.4044.122
    • Web Server        • web-server                           •
      web-javascript • Flutter Tools

! Doctor found issues in 3 categories.
```

</details>

**Comment by VladyslavBondarenko** [comment]
I can't see the exception with `1.12.13+hotfix.9`

**Comment by philipdolenko** [comment]
I can reproduce this error on the beta channel

> [✓] Flutter (Channel beta, v1.17.0-3.2.pre, on Mac OS X 10.15.3 19D76, locale en-UA)

as well as on the master

> [✓] Flutter (Channel master, v1.18.0-9.0.pre.14, on Mac OS X 10.15.3 19D76, locale en-UA)

I have tested on iOS Simulator, Android Simulator (Pixel 3a API 28)

**Comment by hasnentai** [comment]
@philipdolenko I got the same issue when I used Animated Container and Child as `CupertinoPicker` so I guess this not with the `CupertinoDatePicker` but it has the same issue on `CupertinoPicker`

Here's What I wanna achieve

```
 AnimatedContainer(
            height: _animation.value, // here is the issue
            duration: Duration(milliseconds: 300),
            color: Colors.white,
            width: SizeConfig.widthMultiplier * 100,
             child: CupertinoPicker(
                      useMagnifier: true,
                      backgroundColor: Colors.white,
                       itemExtent: 50,
                      looping: true,
                      scrollController:
                         FixedExtentScrollController(initialItem: 1),
                      onSelectedItemChanged: (i) { },
                          children: <Widget>[
               ...
                          ],
),
```
Error


```
════════ Exception caught by rendering library ═════════════════════════════════
'package:flutter/src/rendering/layer.dart': Failed assertion: line 1627 pos 12: 'value.storage.every((double component) => component.isFinite)': is not true.
The relevant error-causing widget was
    CupertinoPicker 
lib/views/near_by_page.dart:164
════════════════════════════════════════════════════════════════════════════════
```

Logs
```
[✓] Flutter (Channel beta, v1.17.0, on Mac OS X 10.14.6 18G3020, locale en-IN)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 11.3.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 3.5)
[✓] VS Code (version 1.44.2)
[✓] Connected device (3 available)

• No issues found!
```

**Comment by philipdolenko** [comment]
@hasnentai Hi, it seems like the same issue due to  _animation.value can be 0

**Comment by hasnentai** [comment]
@philipdolenko Yeah Exactly

**Comment by hasnentai** [comment]
@philipdolenko Seems like `0.0` is not asserting true because  `0.0` return Matrix4 as `NaN` and `NaN` is considered as non-finite according to the Document in num. dart file
@xster and @AyushBherwani1998  any Idea why it's returning Matrix4 as `NaN` on `0.0`?
![Screenshot 2020-07-12 at 5 39 05 PM](https://user-images.githubusercontent.com/26821037/87245874-c9d35500-c466-11ea-928a-efa40a0562a3.png)

**Comment by pedromassangocode** [comment]
Hi @philipdolenko 
I was able to reproduce the issue on latest stable and master channel.

<details>
<summary>code sample</summary>

```dart
import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';

void main() => runApp(App());

class App extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Widget Test',
      home: Directionality(
        textDirection: TextDirection.rtl,
        child: Scaffold(
          body: Center(
            child: Container(
              height: 0,
              width: double.infinity,
              child: CupertinoDatePicker(onDateTimeChanged: (_){}),
            ),
          ),
        ),
      ),
    );
  }
}
```
</details>



<details>
<summary>logs</summary>

```bash
[        ] Syncing files to device iPhone 12 Pro Max... (completed in 249ms)
[   +1 ms] Synced 0.0MB.
[   +1 ms] <- accept
[  +19 ms] Connected to _flutterView/0x7f8cc702ba20.
[   +5 ms] Flutter run key commands.
[   +3 ms] r Hot reload. 🔥🔥🔥
[   +2 ms] R Hot restart.
[        ] h Repeat this help message.
[        ] d Detach (terminate "flutter run" but leave application running).
[        ] c Clear the screen
[        ] q Quit (terminate the application on the device).
[        ] An Observatory debugger and profiler on iPhone 12 Pro Max is available at: http://127.0.0.1:61349/_yNeZ67ezO4=/
[   +2 ms] 
           Flutter DevTools, a Flutter debugger and profiler, on iPhone 12 Pro Max is available at: http://127.0.0.1:9100?uri=http%3A%2F%2F127.0.0.1%3A61349%2F_yNeZ67ezO4%3D%2F
[        ] Running with unsound null safety
[   +1 ms] For more information see https://dart.dev/null-safety/unsound-null-safety
[+156638 ms] Skipping target: gen_localizations
[   +1 ms] complete
[   +2 ms] Performing hot restart...
[  +15 ms] Scanned through 502 files in 10ms
[        ] Syncing files to device iPhone 12 Pro Max...
[        ] <- reset
[        ] Compiling dart to kernel with 0 updated files
[        ] <- recompile package:flutter_example/main.dart f45ff621-40a7-4195-871b-645bb964c431
[        ] <- f45ff621-40a7-4195-871b-645bb964c431
[  +69 ms] Updating files.
[  +32 ms] DevFS: Sync finished
[        ] Syncing files to device iPhone 12 Pro Max... (completed in 103ms)
[        ] Synced 25.0MB.
[        ] <- accept
[ +287 ms] Hot restart performed in 405ms.
[   +3 ms] Performing hot restart... (completed in 411ms)
[        ] Restarted application in 420ms.
[ +727 ms] 
           ══╡ EXCEPTION CAUGHT BY RENDERING LIBRARY ╞═════════════════════════════════════════════════════════
           The following assertion was thrown during paint():
           'package:flutter/src/rendering/layer.dart': Failed assertion: line 1584 pos 12:
           'value!.storage.every((double component) => component.isFinite)': is not true.

           Either the assertion indicates an error in the framework itself, or we should provide substantially
           more information in this error message to help you determine and fix the underlying cause.
           In either case, please report this assertion by filing a bug on GitHub:
             https://github.com/flutter/flutter/issues/new?template=2_bug.md

           The relevant error-causing widget was:
             CupertinoDatePicker file:///Users/pedromassango/dev/Projects/flutter_example/lib/main.dart:18:22

           When the exception was thrown, this was the stack:
           #2      TransformLayer.transform= (package:flutter/src/rendering/layer.dart:1584:12)
           #3      PaintingContext.pushTransform (package:flutter/src/rendering/object.dart:576:13)
           #4      RenderListWheelViewport._paintChildCylindrically (package:flutter/src/rendering/list_wheel_viewport.dart:961:13)
           #5      RenderListWheelViewport._paintChildWithMagnifier.<anonymous closure> (package:flutter/src/rendering/list_wheel_viewport.dart:921:11)
           #6      PaintingContext.pushLayer (package:flutter/src/rendering/object.dart:396:12)
           #7      PaintingContext.pushClipRect (package:flutter/src/rendering/object.dart:452:7)
           #8      RenderListWheelViewport._paintChildWithMagnifier (package:flutter/src/rendering/list_wheel_viewport.dart:914:15)
           #9      RenderListWheelViewport._paintTransformedChild (package:flutter/src/rendering/list_wheel_viewport.dart:854:7)
           #10     RenderListWheelViewport._paintVisibleChildren (package:flutter/src/rendering/list_wheel_viewport.dart:810:7)
           #11     PaintingContext.pushLayer (package:flutter/src/rendering/object.dart:396:12)
           #12     PaintingContext.pushClipRect (package:flutter/src/rendering/object.dart:452:7)
           #13     RenderListWheelViewport.paint (package:flutter/src/rendering/list_wheel_viewport.dart:788:34)
           #14     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2315:7)
           #15     PaintingContext._repaintCompositedChild (package:flutter/src/rendering/object.dart:140:11)
           #16     PaintingContext.repaintCompositedChild (package:flutter/src/rendering/object.dart:100:5)
           #17     PaintingContext._compositeChild (package:flutter/src/rendering/object.dart:206:7)
           #18     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:187:7)
           #19     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:142:15)
           #20     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2315:7)
           #21     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:189:13)
           #22     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:142:15)
           #23     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2315:7)
           #24     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:189:13)
           #25     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:142:15)
           #26     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2315:7)
           #27     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:189:13)
           #28     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:142:15)
           #29     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2315:7)
           #30     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:189:13)
           #31     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:142:15)
           #32     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2315:7)
           #33     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:189:13)
           #34     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:142:15)
           #35     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2315:7)
           #36     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:189:13)
           #37     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:142:15)
           #38     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2315:7)
           #39     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:189:13)
           #40     RenderBoxContainerDefaultsMixin.defaultPaint (package:flutter/src/rendering/box.dart:2804:15)
           #41     RenderStack.paintStack (package:flutter/src/rendering/stack.dart:629:5)
           #42     RenderStack.paint (package:flutter/src/rendering/stack.dart:639:7)
           #43     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2315:7)
           #44     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:189:13)
           #45     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:142:15)
           #46     RenderDecoratedBox.paint (package:flutter/src/rendering/proxy_box.dart:2165:11)
           #47     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2315:7)
           #48     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:189:13)
           #49     RenderBoxContainerDefaultsMixin.defaultPaint (package:flutter/src/rendering/box.dart:2804:15)
           #50     RenderCustomMultiChildLayoutBox.paint (package:flutter/src/rendering/custom_layout.dart:412:5)
           #51     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2315:7)
           #52     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:189:13)
           #53     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:142:15)
           #54     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2315:7)
           #55     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:189:13)
           #56     RenderShiftedBox.paint (package:flutter/src/rendering/shifted_box.dart:72:15)
           #57     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2315:7)
           #58     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:189:13)
           #59     RenderBoxContainerDefaultsMixin.defaultPaint (package:flutter/src/rendering/box.dart:2804:15)
           #60     RenderCustomMultiChildLayoutBox.paint (package:flutter/src/rendering/custom_layout.dart:412:5)
           #61     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2315:7)
           #62     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:189:13)
           #63     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:142:15)
           #64     _RenderInkFeatures.paint (package:flutter/src/material/material.dart:551:11)
           #65     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2315:7)
           #66     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:189:13)
           #67     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:142:15)
           #68     PaintingContext.pushLayer (package:flutter/src/rendering/object.dart:396:12)
           #69     RenderPhysicalModel.paint (package:flutter/src/rendering/proxy_box.dart:1925:15)
           #70     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2315:7)
           #71     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:189:13)
           #72     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:142:15)
           #73     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2315:7)
           #74     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:189:13)
           #75     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:142:15)
           #76     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2315:7)
           #77     PaintingContext._repaintCompositedChild (package:flutter/src/rendering/object.dart:140:11)
           #78     PaintingContext.repaintCompositedChild (package:flutter/src/rendering/object.dart:100:5)
           #79     PaintingContext._compositeChild (package:flutter/src/rendering/object.dart:206:7)
           #80     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:187:7)
           #81     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:142:15)
           #82     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2315:7)
           #83     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:189:13)
           #84     RenderBoxContainerDefaultsMixin.defaultPaint (package:flutter/src/rendering/box.dart:2804:15)
           #85     RenderStack.paintStack (package:flutter/src/rendering/stack.dart:629:5)
           #86     RenderStack.paint (package:flutter/src/rendering/stack.dart:639:7)
           #87     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2315:7)
           #88     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:189:13)
           #89     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:142:15)
           #90     RenderDecoratedBox.paint (package:flutter/src/rendering/proxy_box.dart:2165:11)
           #91     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2315:7)
           #92     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:189:13)
           #93     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:142:15)
           #94     RenderFractionalTranslation.paint (package:flutter/src/rendering/proxy_box.dart:2715:13)
           #95     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2315:7)
           #96     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:189:13)
           #97     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:142:15)
           #98     RenderFractionalTranslation.paint (package:flutter/src/rendering/proxy_box.dart:2715:13)
           #99     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2315:7)
           #100    PaintingContext.paintChild (package:flutter/src/rendering/object.dart:189:13)
           #101    RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:142:15)
           #102    RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2315:7)
           #103    PaintingContext._repaintCompositedChild (package:flutter/src/rendering/object.dart:140:11)
           #104    PaintingContext.repaintCompositedChild (package:flutter/src/rendering/object.dart:100:5)
           #105    PaintingContext._compositeChild (package:flutter/src/rendering/object.dart:206:7)
           #106    PaintingContext.paintChild (package:flutter/src/rendering/object.dart:187:7)
           #107    RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:142:15)
           #108    RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2315:7)
           #109    PaintingContext.paintChild (package:flutter/src/rendering/object.dart:189:13)
           #110    RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:142:15)
           #111    RenderOffstage.paint (package:flutter/src/rendering/proxy_box.dart:3375:11)
           #112    RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2315:7)
           #113    PaintingContext.paintChild (package:flutter/src/rendering/object.dart:189:13)
           #114    RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:142:15)
           #115    RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2315:7)
           #116    PaintingContext.paintChild (package:flutter/src/rendering/object.dart:189:13)
           #117    _RenderTheatre.paintStack (package:flutter/src/widgets/overlay.dart:780:15)
           #118    _RenderTheatre.paint (package:flutter/src/widgets/overlay.dart:792:7)
           #119    RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2315:7)
           #120    PaintingContext.paintChild (package:flutter/src/rendering/object.dart:189:13)
           #121    RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:142:15)
           #122    RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2315:7)
           #123    PaintingContext.paintChild (package:flutter/src/rendering/object.dart:189:13)
           #124    RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:142:15)
           #125    RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2315:7)
           #126    PaintingContext.paintChild (package:flutter/src/rendering/object.dart:189:13)
           #127    RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:142:15)
           #128    RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2315:7)
           #129    PaintingContext.paintChild (package:flutter/src/rendering/object.dart:189:13)
           #130    RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:142:15)
           #131    RenderCustomPaint.paint (package:flutter/src/rendering/custom_paint.dart:580:11)
           #132    RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2315:7)
           #133    PaintingContext.paintChild (package:flutter/src/rendering/object.dart:189:13)
           #134    RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:142:15)
           #135    RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2315:7)
           #136    PaintingContext.paintChild (package:flutter/src/rendering/object.dart:189:13)
           #137    RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:142:15)
           #138    RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2315:7)
           #139    PaintingContext.paintChild (package:flutter/src/rendering/object.dart:189:13)
           #140    RenderView.paint (package:flutter/src/rendering/view.dart:213:15)
           #141    RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2315:7)
           #142    PaintingContext._repaintCompositedChild (package:flutter/src/rendering/object.dart:140:11)
           #143    PaintingContext.repaintCompositedChild (package:flutter/src/rendering/object.dart:100:5)
           #144    PipelineOwner.flushPaint (package:flutter/src/rendering/object.dart:978:29)
           #145    RendererBinding.drawFrame (package:flutter/src/rendering/binding.dart:455:19)
           #146    WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:870:13)
           #147    RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:319:5)
           #148    SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1144:15)
           #149    SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1082:9)
           #150    SchedulerBinding.scheduleWarmUpFrame.<anonymous closure> (package:flutter/src/scheduler/binding.dart:865:7)
           (elided 13 frames from class _AssertionError, class _RawReceivePortImpl, class _Timer, dart:async, and dart:async-patch)

           The following RenderObject was being processed when the exception was fired: RenderListWheelViewport#f4178:
             needs compositing
             creator: ListWheelViewport ← IgnorePointer-[GlobalKey#f891f] ← Semantics ← Listener ←
               _GestureSemantics ← RawGestureDetector-[LabeledGlobalKey<RawGestureDetectorState>#acdda] ←
               Listener ← _ScrollableScope ← _ScrollSemantics-[GlobalKey#46010] ← _FixedExtentScrollable ←
               NotificationListener<ScrollNotification> ← ListWheelScrollView ← ⋯
             parentData: <none> (can use size)
             constraints: BoxConstraints(w=203.0, h=0.0)
             layer: OffsetLayer#6a560 DETACHED
             size: Size(203.0, 0.0)
           This RenderObject had the following descendants (showing up to depth 5):
               child 1: RenderIndexedSemantics#1bd38 relayoutBoundary=up1
                 child: RenderPadding#9dada relayoutBoundary=up2
                   child: RenderPositionedBox#80ba3 relayoutBoundary=up3
                     child: RenderPositionedBox#4a395 relayoutBoundary=up4
                       child: RenderParagraph#0204b relayoutBoundary=up5
           ════════════════════════════════════════════════════════════════════════════════════════════════════
[  +18 ms] 
           Another exception was thrown: 'package:flutter/src/rendering/layer.dart': Failed assertion: line 1584 pos 12: 'value!.storage.every((double component) => component.isFinite)': is not true.
[  +18 ms] 
           Another exception was thrown: 'package:flutter/src/rendering/layer.dart': Failed assertion: line 1584 pos 12: 'value!.storage.every((double component) => component.isFinite)': is not true.
[  +15 ms] 
           Another exception was thrown: 'package:flutter/src/rendering/layer.dart': Failed assertion: line 1584 pos 12: 'value!.storage.every((double component) => component.isFinite)': is not true.
```
</details>

<details>
<summary>flutter doctor -v</summary>

```bash
[✓] Flutter (Channel stable, 1.22.5, on Mac OS X 10.15.7 19H2 darwin-x64, locale en)
    • Flutter version 1.22.5 at /Users/pedromassango/Code/flutter_stable
    • Framework revision 7891006299 (5 weeks ago), 2020-12-10 11:54:40 -0800
    • Engine revision ae90085a84
    • Dart version 2.10.4

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/pedromassango/Library/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.1, Build version 12A7403
    • CocoaPods version 1.9.3

[!] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] IntelliJ IDEA Community Edition (version 2020.3.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin installed
    • Dart plugin version 203.6912

[✓] VS Code (version 1.52.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.18.1

[✓] Connected device (1 available)
    • iPhone 12 Pro Max (mobile) • ECCF5C4A-8BEC-411D-B23E-85A836C3847E • ios • com.apple.CoreSimulator.SimRuntime.iOS-14-1 (simulator)

! Doctor found issues in 1 category.
```

</details>

**Comment by daadu** [comment]
can confirm this in  flutter v2

**Comment by Abdelazeem777** [comment]
The issue still exists but I could overcome it by setting the `height` to `0.0001`
like this:
```
 AnimatedContainer(
          height: isExpanded ? 100 : 0.0001,
          ...
```

**Note**
I know it's not the better solution but at least it could do the trick for you without any exceptions.

**Comment by devsportties** [comment]
> The issue still exists but I could overcome it by setting the `height` to `0.0001`
> like this:
> 
> ```
>  AnimatedContainer(
>           height: isExpanded ? 100 : 0.0001,
>           ...
> ```
> 
> **Note**
> I know it's not the better solution but at least it could do the trick for you without any exceptions.

cheers mate! This solved my problemo

**Comment by TheHazeEffect** [comment]
```
AnimatedContainer(
    curve: Curves.ease,
    duration: const Duration(milliseconds: 200),
    decoration: BoxDecoration(
      borderRadius: BorderRadius.circular(16),
      color: Colors.redAccent,
    ),
    padding: const EdgeInsets.all(15),
    height: providerParkingModel.isAlarm ? 150 : 0.001,
    child: CupertinoTheme(
      data: CupertinoTheme.of(context)
          .copyWith(brightness: Brightness.dark),
      child: CupertinoTimerPicker(
        initialTimerDuration: providerParkingModel.alarmTime ??
            const Duration(minutes: 30),
        onTimerDurationChanged: (duration) {
          ref
              .read(savedParkingProvider(parkingModel).notifier)
              .mapEventsToStates(const ToggleAlarmStatus());
        },
      ),
    ),
  ),
```
I had the same issue except that I not only had to change from 0 to 0.0001 but I also had to remove the padding from animated container
