### ISSUE TITLE
Gradle Is Unable to Unwrap.

### ISSUE THREAD

**Issue by johnmelodyme** [flutter/flutter#55648]
The Error I've got: 
```
Exception in thread "main" java.util.zip.ZipException: error in opening zip file
        at java.util.zip.ZipFile.open(Native Method)
        at java.util.zip.ZipFile.<init>(ZipFile.java:225)
        at java.util.zip.ZipFile.<init>(ZipFile.java:155)
        at java.util.zip.ZipFile.<init>(ZipFile.java:169)
        at org.gradle.wrapper.Install.unzip(Install.java:214)
        at org.gradle.wrapper.Install.access$600(Install.java:27)
        at org.gradle.wrapper.Install$1.call(Install.java:74)
        at org.gradle.wrapper.Install$1.call(Install.java:48)
        at org.gradle.wrapper.ExclusiveFileAccessManager.access(ExclusiveFileAccessManager.java:65)
        at org.gradle.wrapper.Install.createDist(Install.java:48)
        at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:128)
        at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:61)
The plugin android_intent could not be built due to the issue above.
```

The solutions I had tried:
1. _deleting_ the dir at ```android/Gradle``` for reinstallation.
2. Download the source of ```gradle5.6.2{complete}```  from [Gradle Website](https://gradle.org/next-steps/?version=5.6.2&format=all) and placed in the ```android/.gradle/``` folder.

The result is, I still get the error.

So, Anyone else facing this issue or just me? 🤔

**Comment by VladyslavBondarenko** [comment]
Hi @johnmelodyme 
you don't need to delete `android/Gradle` in the your project dir.
If the gradle zip is corrupted, you can delete dists from the `<your_user_dir>/.gradle/wrapper/dists/`. 
The version specified as `distributionUrl` in your `<project_dir>/android/gradle/wrapper/gradle-wrapper.properties` (for example `distributionUrl=https\://services.gradle.org/distributions/gradle-6.3-all.zip`) will be downloaded.
Does it help?

**Comment by johnmelodyme** [comment]
Solved by ```flutter clean``` then unwrap { with Declaration in _gradle-wrapper.properties_} ```Gradle5.4.2.zip``` in ```android/.gradle/``` .

**Comment by johnmelodyme** [comment]
> Hi @johnmelodyme
> you don't need to delete `android/Gradle` in the your project dir.
> If the gradle zip is corrupted, you can delete dists from the `<your_user_dir>/.gradle/wrapper/dists/`.
> The version specified as `distributionUrl` in your `<project_dir>/android/gradle/wrapper/gradle-wrapper.properties` (for example `distributionUrl=https\://services.gradle.org/distributions/gradle-6.3-all.zip`) will be downloaded.
> Does it help?



Solved by ```flutter clean``` then unwrap { with Declaration in _gradle-wrapper.properties_} ```Gradle5.4.2.zip``` in ```android/.gradle/``` .

Thanks @VladyslavBondarenko <3
