### ISSUE TITLE
[Linux Desktop] Platform exception when click on TextField

### ISSUE THREAD

**Issue by charafau** [flutter/flutter#55653]
## Steps to Reproduce

Sample program:

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      home: MyHomePage(),
    );
  }
}

class MyHomePage extends StatefulWidget {
  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Center(
        child: TextField(),
      ),
    );
  }
}

```

Log:
```
  desk_test flutter run --verbose -d linux
[   +7 ms] executing: [/home/charafau/Utils/flutterSdk/flutterMaster/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[  +24 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[        ] d72eea539e3f116d62dfb30f2b10ec1e05c82ab0
[        ] executing: [/home/charafau/Utils/flutterSdk/flutterMaster/] git tag --contains HEAD
[ +142 ms] Exit code 0 from: git tag --contains HEAD
[   +4 ms] executing: [/home/charafau/Utils/flutterSdk/flutterMaster/] git describe --match *.*.*-*.*.pre --first-parent --long --tags
[ +119 ms] Exit code 0 from: git describe --match *.*.*-*.*.pre --first-parent --long --tags
[        ] 1.18.0-8.0.pre-13-gd72eea539
[  +11 ms] executing: [/home/charafau/Utils/flutterSdk/flutterMaster/] git rev-parse --abbrev-ref --symbolic @{u}
[   +5 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/master
[        ] executing: [/home/charafau/Utils/flutterSdk/flutterMaster/] git ls-remote --get-url origin
[   +4 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[  +65 ms] executing: [/home/charafau/Utils/flutterSdk/flutterMaster/] git rev-parse --abbrev-ref HEAD
[   +4 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] master
[  +33 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +1 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[   +9 ms] executing: /home/charafau/Utils/android-sdk/platform-tools/adb devices -l
[  +30 ms] List of devices attached
[   +3 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[        ] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[ +146 ms] Generating /home/charafau/Code/flutter/desk_test/android/app/src/main/java/io/flutter/plugins/GeneratedPluginRegistrant.java
[  +56 ms] Launching lib/main.dart on Linux in debug mode...
[   +4 ms] /home/charafau/Utils/flutterSdk/flutterMaster/bin/cache/dart-sdk/bin/dart
/home/charafau/Utils/flutterSdk/flutterMaster/bin/cache/artifacts/engine/linux-x64/frontend_server.dart.snapshot --sdk-root
/home/charafau/Utils/flutterSdk/flutterMaster/bin/cache/artifacts/engine/common/flutter_patched_sdk/ --incremental --target=flutter --debugger-module-names
-Ddart.developer.causal_async_stacks=true --output-dill /tmp/flutter_tool.NJNWAF/app.dill --packages .packages -Ddart.vm.profile=false -Ddart.vm.product=false
--bytecode-options=source-positions,local-var-info,debugger-stops,instance-field-initializers,keep-unreachable-code,avoid-closure-call-instructions --enable-asserts
--track-widget-creation --filesystem-scheme org-dartlang-root --initialize-from-dill build/cache.dill
[  +15 ms] Building Linux application...
[   +1 ms] executing: make -C /home/charafau/Code/flutter/desk_test/linux BUILD=debug
[  +11 ms] <- compile package:desk_test/main.dart
[  +12 ms] make: Entering directory '/home/charafau/Code/flutter/desk_test/linux'
[        ] /home/charafau/Utils/flutterSdk/flutterMaster/packages/flutter_tools/bin/tool_backend.sh linux-x64 debug
[+3648 ms] mkdir -p /home/charafau/Code/flutter/desk_test/linux/../build/linux/obj/debug
[        ] clang++ -std=c++14 -Wall -Werror   -Iflutter/ephemeral -I/home/charafau/Code/flutter/desk_test/linux/flutter/ephemeral/cpp_client_wrapper_glfw/include
-MMD -c main.cc -o /home/charafau/Code/flutter/desk_test/linux/../build/linux/obj/debug/main.o
[ +497 ms] mkdir -p /home/charafau/Code/flutter/desk_test/linux/../build/linux/obj/debug/flutter
[        ] clang++ -std=c++14 -Wall -Werror   -Iflutter/ephemeral -I/home/charafau/Code/flutter/desk_test/linux/flutter/ephemeral/cpp_client_wrapper_glfw/include
-MMD -c flutter/generated_plugin_registrant.cc -o /home/charafau/Code/flutter/desk_test/linux/../build/linux/obj/debug/flutter/generated_plugin_registrant.o
[ +164 ms] mkdir -p /home/charafau/Code/flutter/desk_test/linux/../build/linux/debug
[   +1 ms] clang++ -std=c++14 -Wall -Werror   -Iflutter/ephemeral -I/home/charafau/Code/flutter/desk_test/linux/flutter/ephemeral/cpp_client_wrapper_glfw/include
/home/charafau/Code/flutter/desk_test/linux/../build/linux/obj/debug/main.o /home/charafau/Code/flutter/desk_test/linux/../build/linux/obj/debug/window_configuration.o
/home/charafau/Code/flutter/desk_test/linux/../build/linux/obj/debug/flutter/generated_plugin_registrant.o
/home/charafau/Code/flutter/desk_test/linux/../build/linux/obj/debug//home/charafau/Code/flutter/desk_test/linux/flutter/ephemeral/cpp_client_wrapper_glfw/flutter_wind
ow_controller.o
/home/charafau/Code/flutter/desk_test/linux/../build/linux/obj/debug//home/charafau/Code/flutter/desk_test/linux/flutter/ephemeral/cpp_client_wrapper_glfw/plugin_regis
trar.o
/home/charafau/Code/flutter/desk_test/linux/../build/linux/obj/debug//home/charafau/Code/flutter/desk_test/linux/flutter/ephemeral/cpp_client_wrapper_glfw/engine_metho
d_result.o -L/home/charafau/Code/flutter/desk_test/linux/../build/linux/debug/lib -lflutter_linux_glfw  -Wl,-rpath=\$ORIGIN/lib -o
/home/charafau/Code/flutter/desk_test/linux/../build/linux/debug/desk_test
[ +119 ms] mkdir -p /home/charafau/Code/flutter/desk_test/linux/../build/linux/debug/data
[        ] rsync -rpu --delete /home/charafau/Code/flutter/desk_test/linux/../build/flutter_assets
/home/charafau/Code/flutter/desk_test/linux/../build/linux/debug/data
[   +3 ms] make: Leaving directory '/home/charafau/Code/flutter/desk_test/linux'
[  +10 ms] Building Linux application... (completed in 4.5s)
[  +86 ms] [INFO:persistent_cache.cc(338)] PersistentCache::UpdateAssetPath: /home/charafau/Code/flutter/desk_test/build/linux/debug/data/flutter_assets
[ +314 ms] Observatory URL on device: http://127.0.0.1:45119/EhFVjRyqQL0=/
[   +9 ms] Connecting to service protocol: http://127.0.0.1:45119/EhFVjRyqQL0=/
[ +128 ms] Successfully connected to service protocol: http://127.0.0.1:45119/EhFVjRyqQL0=/
[  +63 ms] DevFS: Creating new filesystem on the device (null)
[  +16 ms] DevFS: Created new filesystem on the device (file:///tmp/desk_testOKGDNL/desk_test/)
[   +1 ms] Updating assets
[  +61 ms] Syncing files to device Linux...
[   +1 ms] Scanning asset files
[   +1 ms] <- reset
[        ] Compiling dart to kernel with 0 updated files
[        ] <- recompile package:desk_test/main.dart adfc5224-58e0-4050-a1e6-4ed4752c1b81
[        ] <- adfc5224-58e0-4050-a1e6-4ed4752c1b81
[  +87 ms] Updating files
[  +49 ms] DevFS: Sync finished
[   +1 ms] Syncing files to device Linux... (completed in 141ms)
[        ] Synced 0.9MB.
[   +2 ms] <- accept
[        ] Connected to _flutterView/0x561c2f84bfa0.
[   +1 ms] Flutter run key commands.
[   +1 ms] r Hot reload. 🔥🔥🔥
[   +1 ms] R Hot restart.
[        ] h Repeat this help message.
[        ] d Detach (terminate "flutter run" but leave application running).
[        ] c Clear the screen
[        ] q Quit (terminate the application on the device).
[        ] An Observatory debugger and profiler on Linux is available at: http://127.0.0.1:45119/EhFVjRyqQL0=/
[+22699 ms] [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: PlatformException(Bad Arguments, Method invoked without args, null)
[        ] #0      JSONMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:149:7)
[        ] #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:156:18)
[        ] <asynchronous suspension>
[        ] #2      OptionalMethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:435:18)
[        ] #3      TextInput._requestAutofill (package:flutter/src/services/text_input.dart:1179:14)
[        ] #4      TextInputConnection.requestAutofill (package:flutter/src/services/text_input.dart:840:25)
[        ] #5      EditableTextState._openInputConnection (package:flutter/src/widgets/editable_text.dart:1523:28)
[        ] #6      EditableTextState._openOrCloseInputConnectionIfNeeded (package:flutter/src/widgets/editable_text.dart:1551:7)
[        ] #7      EditableTextState._handleFocusChanged (package:flutter/src/widgets/editable_text.dart:1849:5)
[        ] #8      ChangeNotifier.notifyListeners (package:flutter/src/foundation/change_notifier.dart:207:21)
[        ] #9      FocusNode._notify (package:flutter/src/widgets/focus_manager.dart:969:5)
[        ] #10     FocusManager._applyFocusChange (package:flutter/src/widgets/focus_manager.dart:1663:12)
[        ] #11     _rootRun (dart:async/zone.dart:1180:38)
[        ] #12     _CustomZone.run (dart:async/zone.dart:1077:19)
[        ] #13     _CustomZone.runGuarded (dart:async/zone.dart:979:7)
[        ] #14     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1019:23)
[        ] #15     _rootRun (dart:async/zone.dart:1184:13)
[        ] #16     _CustomZone.run (dart:async/zone.dart:1077:19)
[        ] #17     _CustomZone.runGuarded (dart:async/zone.dart:979:7)
[        ] #18     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1019:23)
[        ] #19     _microtaskLoop (dart:async/schedule_microtask.dart:43:21)
[        ] #20     _startMicrotaskLoop (dart:async/schedule_microtask.dart:52:5)
[+5090 ms] Service protocol connection closed.
[        ] Lost connection to device.
[   +1 ms] DevFS: Deleting filesystem on the device (file:///tmp/desk_testOKGDNL/desk_test/)
[ +253 ms] Ignored error while cleaning up DevFS: TimeoutException after 0:00:00.250000: Future not completed
[   +1 ms] "flutter run" took 33,639ms.


```

Flutter doctor:

```
➜  ~ flutter doctor -v 
[✓] Flutter (Channel master, v1.18.0-9.0.pre.13, on Linux, locale en_US.UTF-8)
    • Flutter version 1.18.0-9.0.pre.13 at /home/charafau/Utils/flutterSdk/flutterMaster
    • Framework revision d72eea539e (2 hours ago), 2020-04-25 14:27:55 -0700
    • Engine revision 2b94311a77
    • Dart version 2.9.0 (build 2.9.0-3.0.dev 94178e920e)

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /home/charafau/Utils/android-sdk
    • Platform android-29, build-tools 29.0.3
    • ANDROID_HOME = /home/charafau/Utils/android-sdk
    • ANDROID_SDK_ROOT = /home/charafau/Utils/android-sdk
    • Java binary at: /home/charafau/Apps/android-studio-canary/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • CHROME_EXECUTABLE = chromium

[✓] Linux toolchain - develop for Linux desktop
    • clang++ 10.0.0
    • GNU Make 4.3

[✓] Android Studio (version 3.6)
    • Android Studio at /home/charafau/Apps/android-studio
    • Flutter plugin version 44.0.2
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)

[!] Android Studio (version 4.0)
    • Android Studio at /home/charafau/Apps/android-studio-canary
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)

[!] Android Studio
    • Android Studio at /home/charafau/Downloads/AndroidDeveloperUserStudyApril2020/android-studio
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] IntelliJ IDEA Community Edition (version 2019.3)
    • IntelliJ at /home/charafau/Apps/idea-IC-193.6494.35
    • Flutter plugin version 45.0.2
    • Dart plugin version 193.6911.31

[✓] Connected device (3 available)
    • Linux      • Linux      • linux-x64      • Linux
    • Web Server • web-server • web-javascript • Flutter Tools
    • Chrome     • chrome     • web-javascript • Chromium 81.0.4044.122 Arch Linux

! Doctor found issues in 2 categories.

```

Flutter analyze:

```
➜  desk_test flutter analyze
Analyzing desk_test...                                                  
No issues found! (ran in 1.1s)

```

**Comment by stuartmorgan** [comment]
The control logic in the GLFW text input method handler is incorrect; it assumes that the only messages in the `else` branch are the ones explicitly handled inside it. The whole thing should be flattened to one `if`/`else if`/.../`else` chain and the argument extraction code duplicated into the methods with arguments.

We should also double-check that the other desktop embeddings don't have this structure since there was a fair amount of cross-pollination between the desktop implementations.

**Comment by TheCGDF** [comment]
Windows also has this problem.
```
[ERROR:c:\b\s\w\ir\cache\builder\src\flutter\lib\ui\ui_dart_state.cc(157)] Unhandled Exception: PlatformException(Bad Arguments, Method invoked without args, null)
#0      JSONMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:149:7)
#1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:156:18)
<asynchronous suspension>
#2      OptionalMethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:435:18)
#3      TextInput._requestAutofill (package:flutter/src/services/text_input.dart:1179:14)
#4      TextInputConnection.requestAutofill (package:flutter/src/services/text_input.dart:840:25)
#5      EditableTextState._openInputConnection (package:flutter/src/widgets/editable_text.dart:1523:28)
#6      EditableTextState._openOrCloseInputConnectionIfNeeded (package:flutter/src/widgets/editable_text.dart:1551:7)
#7      EditableTextState._handleFocusChanged (package:flutter/src/widgets/editable_text.dart:1849:5)
#8      ChangeNotifier.notifyListeners (package:flutter/src/foundation/change_notifier.dart:207:21)
#9      FocusNode._notify (package:flutter/src/widgets/focus_manager.dart:969:5)
#10     FocusManager._applyFocusChange (package:flutter/src/widgets/focus_manager.dart:1663:12)
#11     _rootRun (dart:async/zone.dart:1180:38)
#12     _CustomZone.run (dart:async/zone.dart:1077:19)
#13     _CustomZone.runGuarded (dart:async/zone.dart:979:7)
#14     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1019:23)
#15     _rootRun (dart:async/zone.dart:1184:13)
#16     _CustomZone.run (dart:async/zone.dart:1077:19)
#17     _CustomZone.runGuarded (dart:async/zone.dart:979:7)
#18     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1019:23)
#19     _microtaskLoop (dart:async/schedule_microtask.dart:43:21)
#20     _startMicrotaskLoop (dart:async/schedule_microtask.dart:52:5)
```

**Comment by stuartmorgan** [comment]
Yes; note the title of the PR referenced above your comment.
