### ISSUE TITLE
Exception in thread "main" java.net.ConnectException: Connection timed out (Connection timed out)

### ISSUE THREAD

**Issue by joekendal** [flutter/flutter#55677]
## Steps to Reproduce

1. flutter run

## Logs

```
Launching lib/main.dart on AndroidPhone in debug mode...
Running Gradle task 'assembleDebug'...          
Exception in thread "main" java.net.ConnectException: Connection timed out (Connection timed out)                  
        at java.net.PlainSocketImpl.socketConnect(Native Method)                                                        at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)                                 at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)                          at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)                                   at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)                                                   at java.net.Socket.connect(Socket.java:589)                                                                     at sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:666)                                               at sun.security.ssl.BaseSSLSocketImpl.connect(BaseSSLSocketImpl.java:173)                                       at sun.net.NetworkClient.doConnect(NetworkClient.java:180)                                                      at sun.net.www.http.HttpClient.openServer(HttpClient.java:463)                                                  at sun.net.www.http.HttpClient.openServer(HttpClient.java:558)                                                  at sun.net.www.protocol.https.HttpsClient.<init>(HttpsClient.java:264)                                          at sun.net.www.protocol.https.HttpsClient.New(HttpsClient.java:367)                                             at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(AbstractDelegateHttpsURLConnection.java:191)
        at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1156)                       at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1050)                        at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:177)
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1564)                     at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1492)                      at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:263)            at org.gradle.wrapper.Download.downloadInternal(Download.java:58)                                               at org.gradle.wrapper.Download.download(Download.java:44)                                                       at org.gradle.wrapper.Install$1.call(Install.java:61)                                                           at org.gradle.wrapper.Install$1.call(Install.java:48)                                                           at org.gradle.wrapper.ExclusiveFileAccessManager.access(ExclusiveFileAccessManager.java:65)                     at org.gradle.wrapper.Install.createDist(Install.java:48)                                                       at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:128)                                         at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:61)  
```

```
[✓] Flutter (Channel dev, v1.18.0, on Linux, locale en_GB.UTF-8)
    • Flutter version 1.18.0 at /home/joe/flutter
    • Framework revision 8f7327f83a (3 weeks ago), 2020-04-06 22:11:01 -0400
    • Engine revision 49891e0653
    • Dart version 2.8.0 (build 2.8.0-dev.20.0 1210d27678)

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /home/joe/Android/Sdk
    • Platform android-29, build-tools 29.0.3
    • Java binary at: /home/joe/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✓] Android Studio (version 3.6)
    • Android Studio at /home/joe/android-studio
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)

[✓] IntelliJ IDEA Community Edition (version 2019.3)
    • IntelliJ at /home/joe/Downloads/idea-IC-193.6494.35
    • Flutter plugin version 44.0.3
    • Dart plugin version 193.6494.35

[✓] Connected device (1 available)
    • AndroidPhone • 248374DJSAKSAD • android-arm64 • Android 10 (API 29)
```

**Comment by Abhishek01039** [comment]
may be this is a connection issue 
this issue is similar to this issue https://github.com/flutter/flutter/issues/21818

**Comment by joekendal** [comment]
@Abhishek01039 it is not unfortunately

**Comment by iapicca** [comment]
Hi @joekendal 
please look at this possible [solution](https://github.com/flutter/flutter/issues/33389#issuecomment-496154938)
if the issue persists 
could you please provide
your `flutter run --verbose` 
and your `pubspec.yaml` 
or if possible a reproducible minimal code sample.
Thank you

**Comment by joekendal** [comment]
I decided to just delete everything and downgrade to the stable versions of flutter and dart
