### ISSUE TITLE
"brew tap" (used for installing ideviceinstaller/...) complains about deprecated use

### ISSUE THREAD

**Issue by mkustermann** [flutter/flutter#5568]
On a MacOS system with brew installed, running `brew tap flutter/flutter` results in deprecation warnings:

```
$ brew tap flutter/flutter
==> Tapping flutter/flutter
Cloning into '/Users/user/.homebrew/Library/Taps/flutter/homebrew-flutter'...
remote: Counting objects: 4, done.
remote: Compressing objects: 100% (4/4), done.
remote: Total 4 (delta 0), reused 3 (delta 0), pack-reused 0
Receiving objects: 100% (4/4), done.
Checking connectivity... done.
Warning: Calling Formula.sha1 is deprecated!
Use Formula.sha256 instead.
/Users/user/.homebrew/Library/Taps/flutter/homebrew-flutter/ios-deploy.rb:6:in `<class:IosDeploy>'
Please report this to the flutter/flutter tap!

Warning: Calling SoftwareSpec#sha1 is deprecated!
Use SoftwareSpec#sha256 instead.
/Users/user/.homebrew/Library/Taps/flutter/homebrew-flutter/ios-deploy.rb:6:in `<class:IosDeploy>'
Please report this to the flutter/flutter tap!

Warning: Calling Resource#sha1 is deprecated!
Use Resource#sha256 instead.
/Users/user/.homebrew/Library/Taps/flutter/homebrew-flutter/ios-deploy.rb:6:in `<class:IosDeploy>'
Please report this to the flutter/flutter tap!

Tapped 1 formula (25 files, 21.6K)
```

**Comment by eseidelGoogle** [comment]
That is https://github.com/flutter/homebrew-flutter, which either needs an update or to be removed.  FYI @abarth @chinmaygarde

**Comment by sethladd** [comment]
Assuming we still use the brew (which I think we do?) we need to update this line to sha256: https://github.com/flutter/homebrew-flutter/blob/master/ios-deploy.rb#L6

**Comment by eseidelGoogle** [comment]
We have removed homebrew-flutter.  All the packages it used to provide are now part of brew proper.
