### ISSUE TITLE
Fatal Exception: java.lang.UnsatisfiedLinkError:dlopen failed: cannot locate symbol "truncf"

### ISSUE THREAD

**Issue by impeiwei** [flutter/flutter#55714]
BASE:  Android appliaction use add-to-exist-app (as remote aar implement  dependency in build.gradle) to provide flutter function.   version: v1.12.13-hotfix.9

Problem 1:  
   libflutter.so missing when exec run appliaction in androidstuido.
if ./gradlew clean first, and then exec run appliaction in androidstuido  is ok.

Problem 2 (from crash bugly):  

Problem crash:
Fatal Exception: java.lang.UnsatisfiedLinkError:dlopen failed: cannot locate symbol "truncf" referenced by "/data/app/***/lib/arm/libflutter.so"...
at java.lang.Runtime.loadLibrary(Runtime.java:372)
at java.lang.System.loadLibrary(System.java:1076)
at io.flutter.embedding.engine.b.a.a(FlutterLoader.java:122)
at io.flutter.embedding.engine.b.a.dG(FlutterLoader.java:93)
at io.flutter.embedding.engine.a.<init>(FlutterEngine.java:183)
at io.flutter.embedding.engine.a.<init>(FlutterEngine.java:152)
at io.flutter.embedding.engine.a.<init>(FlutterEngine.java:142)
at com.**.flutterrunner.core.FlutterRunner.initFlutterEngine(FlutterRunner.java:53)
at com.**.flutterrunner.support.FlutterRunnerHelper.initFlutterEngine(FlutterRunnerHelper.java:23)
at com.**.flutterrunner.support.FlutterRunnerHelper.init(FlutterRunnerHelper.java:18)
at com.**.flutter.portal.b.a(FlutterPortal.java:33)
at com.**.android.MyApplication.onCreate(MyApplication.java:153)
at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1024)
at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5021)
at android.app.ActivityThread.access$1700(ActivityThread.java:195)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1594)
at android.os.Handler.dispatchMessage(Handler.java:111)
at android.os.Looper.loop(Looper.java:207)
at android.app.ActivityThread.main(ActivityThread.java:5856)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1026)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:887)

**Comment by impeiwei** [comment]
Fatal Exception: java.lang.UnsatisfiedLinkError:dlopen failed: "/data/user/0/dkplugin.hry.cyr/virtual/data/user/0/com.my.package/lib/libflutter.so" has unexpected e_machine: 40
at java.lang.Runtime.loadLibrary(Runtime.java:371)
at java.lang.System.loadLibrary(System.java:988)
at io.flutter.embedding.engine.b.a.a(FlutterLoader.java:122)
at io.flutter.embedding.engine.b.a.dG(FlutterLoader.java:93)
at io.flutter.embedding.engine.a.<init>(FlutterEngine.java:183)
at io.flutter.embedding.engine.a.<init>(FlutterEngine.java:152)
at io.flutter.embedding.engine.a.<init>(FlutterEngine.java:142)

**Comment by ar2029** [comment]
https://github.com/flutter/flutter/issues/55565#issue-606399174

**Comment by iapicca** [comment]
Hi @impeiwei 
can you please provide your `flutter doctor -v` ,
and if possible a reproducible minimal code sample.
Thank you

**Comment by impeiwei** [comment]
[✓] Flutter (Channel stable, v1.12.13+hotfix.9, on Mac OS X 10.15.4 19E287, locale zh-Hans-CN)
    • Flutter version 1.12.13+hotfix.9 at /Users/maker/Developer/flutter
    • Framework revision f139b11009 (4 weeks ago), 2020-03-30 13:57:30 -0700
    • Engine revision af51afceb8
    • Dart version 2.7.2

 
[!] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/peiwei/Developer/Android/SDK
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • ANDROID_HOME = /Users/peiwei/Developer/Android/SDK
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses

[✓] Xcode - develop for iOS and macOS (Xcode 11.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.3, Build version 11C29
    • CocoaPods version 1.8.4

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 43.0.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] VS Code (version 1.43.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.9.1

[!] Connected device
    ! No devices available

**Comment by impeiwei** [comment]
@iapicca this my app cached engine code.
when flutter_aar snapshot update,   ide run install apk  cause "not find libflutter.so" (libflutter.so is missing in /data/data/com..pkg/libs/)

```
public class MyApplication extends Application {
    @Override
    public void onCreate() {
        super.onCreate();
        initFlutterEngine(this);
    }
       public void initFlutterEngine(Context application) {
        FlutterEngine cachedEngine = FlutterEngineCache.getInstance().get(Constants.DEFAULT_CACHED_ENGINE_ID);
        if (cachedEngine != null) {
            return;
        }
        cachedEngine = new FlutterEngine(application.getApplicationContext());
        cachedEngine.getDartExecutor().executeDartEntrypoint(
                DartExecutor.DartEntrypoint.createDefault()
        );
        FlutterEngineCache.getInstance().put(Constants.DEFAULT_CACHED_ENGINE_ID, cachedEngine);
    }
}
```
and app/build.gradle 
```
ndk {
      abiFilters "armeabi"
 }

implementation(rootProject.ext.depsLibs.flutter_aar) { changing = true }
```

**Comment by kw2019ltd** [comment]
same issue at my end many users having this issue 

![image](https://user-images.githubusercontent.com/47334522/81492947-eacfcc00-92a4-11ea-9060-c8418f51733b.png)

**Comment by chinmaygarde** [comment]
What is the device and the version of Android on this device? `truncf` should be in Bionic already so it is surprising that symbol cannot be resolved.

**Comment by impeiwei** [comment]
later we find these are illegal device in monitor system。 
close.
