### ISSUE TITLE
[tool_crash] Invalid argument(s): A directory corresponding to fileSystemPath "/Users/jiang/.pub-cache/hosted/pub.flutter-io.cn/devtools-0.1.15/build" could not be found

### ISSUE THREAD

**Issue by jh235** [flutter/flutter#55723]
## Command
```
flutter run -d chrome
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
ArgumentError: Invalid argument(s): A directory corresponding to fileSystemPath "/Users/jiang/.pub-cache/hosted/pub.flutter-io.cn/devtools-0.1.15/build" could not be found
```
#0      createStaticHandler (package:shelf_static/src/static_handler.dart:50:5)
#1      defaultHandler (package:devtools_server/src/handlers.dart:32:24)
<asynchronous suspension>
#2      serveDevTools (package:devtools_server/src/server.dart:144:21)
#3      DevTools.start (package:dwds/src/servers/devtools.dart:27:15)
#4      Dwds.start (package:dwds/dwds.dart:111:33)
#5      WebAssetServer.start (package:flutter_tools/src/build_runner/devfs_web.dart:79:36)
<asynchronous suspension>
#6      WebDevFS.create (package:flutter_tools/src/build_runner/devfs_web.dart:446:43)
#7      _ResidentWebRunner.run.<anonymous closure> (package:flutter_tools/src/build_runner/resident_web_runner.dart:421:44)
#8      asyncGuard.<anonymous closure> (package:flutter_tools/src/base/async_guard.dart:111:32)
#9      _rootRun (dart:async/zone.dart:1126:13)
#10     _CustomZone.run (dart:async/zone.dart:1023:19)
#11     _runZoned (dart:async/zone.dart:1518:10)
#12     runZoned (dart:async/zone.dart:1502:12)
#13     asyncGuard (package:flutter_tools/src/base/async_guard.dart:109:3)
#14     _ResidentWebRunner.run (package:flutter_tools/src/build_runner/resident_web_runner.dart:411:20)
<asynchronous suspension>
#15     RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:563:37)
<asynchronous suspension>
```
```
[✓] Flutter (Channel master, v1.15.4-pre.254, on Mac OS X 10.15.3 19D76, locale
    zh-Hans-CN)
    • Flutter version 1.15.4-pre.254 at /Users/jiang/Developer/flutter
    • Framework revision fdbd1b14ff (8 weeks ago), 2020-03-03 11:09:01 +0800
    • Engine revision 5e474ee860
    • Dart version 2.8.0 (build 2.8.0-dev.10.0 fbe9f6115d)

[!] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/jiang/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling
      support)
    • Platform android-29, build-tools 29.0.3
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_212-release-1586-b4-5784211)
    ✗ Android license status unknown.
      Try re-installing or updating your Android SDK Manager.
      See https://developer.android.com/studio/#downloads or visit
      https://flutter.dev/setup/#android-setup for detailed instructions.

[✓] Xcode - develop for iOS and macOS (Xcode 11.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.3.1, Build version 11C504
    • CocoaPods version 1.9.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build
      1.8.0_212-release-1586-b4-5784211)

[!] VS Code (version 1.44.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    ✗ Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (4 available)
    • iPhone 11 Pro Max • 1C7690C3-750B-4A2A-BE20-A82DA18EB3C8 • ios
      • com.apple.CoreSimulator.SimRuntime.iOS-13-3 (simulator)
    • macOS             • macOS                                • darwin-x64
      • Mac OS X 10.15.3 19D76
    • Chrome            • chrome                               • web-javascript
      • Google Chrome 81.0.4044.122
    • Web Server        • web-server                           • web-javascript
      • Flutter Tools

! Doctor found issues in 2 categories.

```

## Flutter Application Metadata
**Version**: 1.0.0+1
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
### Plugins
flutter_webrtc-0.2.8
shared_preferences-0.5.7
shared_preferences_macos-0.0.1+7
shared_preferences_web-0.1.2+4

**Comment by VladyslavBondarenko** [comment]
Hi @jh235 
doesn't `flutter pub get` helps?
Note that your `master v1.15.4-pre.254` is obsolete, you can try to upgrade or switch to another channel
about 

> Android license status unknown.
      Try re-installing or updating your Android SDK Manager.

take a look at https://github.com/flutter/flutter/issues/51670
