### ISSUE TITLE
 flutter build apk failed with following error on MAC

### ISSUE THREAD

**Issue by GULERTOLGA** [flutter/flutter#55757]
Flutter crash report; please file at https://github.com/flutter/flutter/issues.

## command

flutter build apk

## exception

ProcessException: ProcessException: Operation not permitted
  Command: /Users/tolgaguler/Documents/Tolga.nosynch/git/netigma_mobile/android/gradlew -q -Ptarget=lib/main.dart -Ptrack-widget-creation=true -Pshrink=true -Ptarget-platform=android-arm,android-arm64,android-x64 assembleRelease

```
#0      _DefaultProcessUtils.stream (package:flutter_tools/src/base/process.dart:431:29)
<asynchronous suspension>
#1      buildGradleApp (package:flutter_tools/src/android/gradle.dart:364:35)
#2      _AsyncAwaitCompleter.start (dart:async-patch/async_patch.dart:45:6)
#3      buildGradleApp (package:flutter_tools/src/android/gradle.dart:218:28)
#4      _AndroidBuilderImpl.buildApk (package:flutter_tools/src/android/android_builder.dart:97:13)
#5      _AsyncAwaitCompleter.start (dart:async-patch/async_patch.dart:45:6)
#6      _AndroidBuilderImpl.buildApk (package:flutter_tools/src/android/android_builder.dart:91:24)
#7      BuildApkCommand.runCommand (package:flutter_tools/src/commands/build_apk.dart:106:26)
#8      _AsyncAwaitCompleter.start (dart:async-patch/async_patch.dart:45:6)
#9      BuildApkCommand.runCommand (package:flutter_tools/src/commands/build_apk.dart:80:42)
#10     FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:615:18)
#11     _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:73:64)
#12     _rootRunUnary (dart:async/zone.dart:1134:38)
#13     _CustomZone.runUnary (dart:async/zone.dart:1031:19)
#14     _FutureListener.handleValue (dart:async/future_impl.dart:139:18)
#15     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:680:45)
#16     Future._propagateToListeners (dart:async/future_impl.dart:709:32)
#17     Future._completeWithValue (dart:async/future_impl.dart:524:5)
#18     Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:554:7)
#19     _rootRun (dart:async/zone.dart:1126:13)
#20     _CustomZone.run (dart:async/zone.dart:1023:19)
#21     _CustomZone.runGuarded (dart:async/zone.dart:925:7)
#22     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:965:23)
#23     _microtaskLoop (dart:async/schedule_microtask.dart:43:21)
#24     _startMicrotaskLoop (dart:async/schedule_microtask.dart:52:5)
#25     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
#26     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:175:5)
```

## flutter doctor

```
[32m[✓][39m Flutter (Channel stable, v1.12.13+hotfix.9, on Mac OS X 10.15.3 19D76, locale en-TR)
    [32m•[39m Flutter version 1.12.13+hotfix.9 at /Users/tolgaguler/flutter
    [32m•[39m Framework revision f139b11009 (4 weeks ago), 2020-03-30 13:57:30 -0700
    [32m•[39m Engine revision af51afceb8
    [32m•[39m Dart version 2.7.2

[32m[✓][39m Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    [32m•[39m Android SDK at /Users/tolgaguler/Library/Android/sdk
    [32m•[39m Android NDK location not configured (optional; useful for native profiling support)
    [32m•[39m Platform android-29, build-tools 29.0.2
    [32m•[39m Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    [32m•[39m Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
    [32m•[39m All Android licenses accepted.

[32m[✓][39m Xcode - develop for iOS and macOS (Xcode 11.3.1)
    [32m•[39m Xcode at /Applications/Xcode.app/Contents/Developer
    [32m•[39m Xcode 11.3.1, Build version 11C504
    [32m•[39m CocoaPods version 1.8.4

[32m[✓][39m Android Studio (version 3.4)
    [32m•[39m Android Studio at /Applications/Android Studio.app/Contents
    [32m•[39m Flutter plugin version 38.2.1
    [32m•[39m Dart plugin version 183.6270
    [32m•[39m Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

[33m[!][39m IntelliJ IDEA Community Edition (version 2020.1)
    [32m•[39m IntelliJ at /Applications/IntelliJ IDEA CE.app
    [31m✗[39m Flutter plugin not installed; this adds Flutter specific functionality.
    [31m✗[39m Dart plugin not installed; this adds Dart specific functionality.
    [32m•[39m For information about installing plugins, see
      https://flutter.dev/intellij-setup/#installing-the-plugins

[32m[✓][39m VS Code (version 1.43.0)
    [32m•[39m VS Code at /Applications/Visual Studio Code.app/Contents
    [32m•[39m Flutter extension version 3.8.0

[32m[✓][39m Connected device (2 available)
    [32m•[39m Android SDK built for x86 • emulator-5554                            • android-x86 • Android 7.1.1 (API 25) (emulator)
    [32m•[39m Tolga iPhone’u            • ecccd20b15c146d0181802d1217d74bb0d4f214b • ios         • iOS 13.3.1

[33m![39m Doctor found issues in 1 category.
```

**Comment by VladyslavBondarenko** [comment]
Hi @GULERTOLGA 
is it your case? https://github.com/flutter/flutter/issues/50880#issue-565815350

**Comment by GULERTOLGA** [comment]
Yes,i think so.  Thanks.
