### ISSUE TITLE
[fuchsia] flutter drive doesn't work with emulator devices 

### ISSUE THREAD

**Issue by gw280** [flutter/flutter#55765]
Using an emulator device (e.g. `fx emu -N`) and trying to use `flutter drive` to run a test on it, I get a device not found error (logs have been stripped down to the relevant parts):

```flutter drive -v -d step-atom-yard-juicy --target=test_driver/stock_view.dart
...
[  +25 ms] List of devices attached
[ +998 ms] 192.168.42.44 bless-fade-grill-slit
                    192.168.42.48 step-atom-yard-juicy
                    192.168.42.41 yard-frown-baton-ouch
[   +5 ms] executing: /usr/local/google/home/wrightgeorge/dev/flutter/bin/cache/artifacts/fuchsia/tools/device-finder resolve -device-limit 1 bless-fade-grill-slit
[  +15 ms] 192.168.42.44
...
[  +36 ms] No devices found with name or id matching 'step-atom-yard-juicy'
[   +9 ms] "flutter drive" took 1,345ms.
 
#0      throwToolExit (package:flutter_tools/src/base/common.dart:14:3)
#1      DriveCommand.runCommand (package:flutter_tools/src/commands/drive.dart:145:7)
<asynchronous suspension>
#2      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:760:18)
#3      _rootRunUnary (dart:async/zone.dart:1192:38)
#4      _CustomZone.runUnary (dart:async/zone.dart:1085:19)
#5      _FutureListener.handleValue (dart:async/future_impl.dart:141:18)
#6      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:686:45)
#7      Future._propagateToListeners (dart:async/future_impl.dart:715:32)
#8      Future._completeWithValue (dart:async/future_impl.dart:526:5)
#9      Future._asyncCompleteWithValue.<anonymous closure> (dart:async/future_impl.dart:560:7)
#10     _rootRun (dart:async/zone.dart:1184:13)
#11     _CustomZone.run (dart:async/zone.dart:1077:19)
#12     _CustomZone.runGuarded (dart:async/zone.dart:979:7)
#13     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1019:23)
#14     _microtaskLoop (dart:async/schedule_microtask.dart:43:21)
#15     _startMicrotaskLoop (dart:async/schedule_microtask.dart:52:5)
#16     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
#17     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:169:5)```

**Comment by gw280** [comment]
cc @iskakaushik @kf6gpe
