### ISSUE TITLE
reloadSources can return an empty list of reports if old vm_service's isolates are out of date.

### ISSUE THREAD

**Issue by jonahwilliams** [flutter/flutter#55811]
I can't repro this locally, which indicates it might be a race condition.

Error log:

```
2020-04-27T19:35:19.680293: attach:stdout: 
2020-04-27T19:35:19.838865: attach:stdout: Performing hot reload...                                        
2020-04-27T19:35:19.842611: run:stderr: Bad state: No element
run:stderr: #0      List.first (dart:core-patch/array.dart:205:5)
2020-04-27T19:35:19.842809: run:stderr: #1      HotRunner._reloadSources.<anonymous closure> (package:flutter_tools/src/run_hot.dart:857:65)
run:stderr: #2      _rootRunUnary (dart:async/zone.dart:1192:38)
run:stderr: #3      _CustomZone.runUnary (dart:async/zone.dart:1085:19)
run:stderr: #4      _FutureListener.handleValue (dart:async/future_impl.dart:141:18)
run:stderr: #5      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:686:45)
run:stderr: #6      Future._propagateToListeners (dart:async/future_impl.dart:715:32)
run:stderr: #7      Future._completeWithValue (dart:async/future_impl.dart:526:5)
run:stderr: #8      Future._asyncCompleteWithValue.<anonymous closure> (dart:async/future_impl.dart:560:7)
run:stderr: #9      _rootRun (dart:async/zone.dart:1184:13)
run:stderr: #10     _CustomZone.run (dart:async/zone.dart:1077:19)
2020-04-27T19:35:19.842945: run:stderr: #11     _CustomZone.runGuarded (dart:async/zone.dart:979:7)
run:stderr: #12     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1019:23)
run:stderr: #13     _microtaskLoop (dart:async/schedule_microtask.dart:43:21)
run:stderr: #14     _startMicrotaskLoop (dart:async/schedule_microtask.dart:52:5)
run:stderr: #15     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
run:stderr: #16     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:169:5)
run:stderr: 
2020-04-27T19:35:19.847851: attach:stdout: Application finished.
```

This is called from https://github.com/flutter/flutter/blob/master/packages/flutter_tools/lib/src/run_hot.dart#L193 .

Its not clear why this is happening, this code was migrated almost directly from the previous vm_service's use of callMethod.

**Comment by jonahwilliams** [comment]
This happens if the vm isolate list is out of date:

https://github.com/flutter/flutter/blob/master/packages/flutter_tools/lib/src/resident_runner.dart#L314

Fixed by https://github.com/flutter/flutter/issues/52179

**Comment by jonahwilliams** [comment]
Fixed by deleting the old vm service
