### ISSUE TITLE
Google sign in platform exception

### ISSUE THREAD

**Issue by lazarvgd** [flutter/flutter#55816]
Hi there,

Beforehand, I found that all issues about [google_sign_in](https://github.com/flutter/plugins#issues) package can submit here.

I am facing error with google sign in, here is the stack trace:

```
E/flutter (  901): [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: PlatformException(sign_in_required, com.google.android.gms.common.api.ApiException: 4: 4: , null)
E/flutter (  901): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:569:7)
E/flutter (  901): #1      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:321:33)
E/flutter (  901): <asynchronous suspension>
E/flutter (  901): #2      MethodChannel.invokeMapMethod (package:flutter/src/services/platform_channel.dart:349:48)
E/flutter (  901): #3      MethodChannelGoogleSignIn.signInSilently (package:google_sign_in_platform_interface/src/method_channel_google_sign_in.dart:38:10)
E/flutter (  901): #4      GoogleSignIn._callMethod (package:google_sign_in/google_sign_in.dart:230:42)
E/flutter (  901): <asynchronous suspension>
E/flutter (  901): #5      GoogleSignIn._addMethodCall (package:google_sign_in/google_sign_in.dart:285:18)
E/flutter (  901): #6      GoogleSignIn.signInSilently (package:google_sign_in/google_sign_in.dart:327:20)
E/flutter (  901): #7      _HomeState.initState (package:tristagram/pages/home.dart:40:18)
E/flutter (  901): #8      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4355:58)
E/flutter (  901): #9      ComponentElement.mount (package:flutter/src/widgets/framework.dart:4201:5)
E/flutter (  901): #10     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194:14)
E/flutter (  901): #11     Element.updateChild (package:flutter/src/widgets/framework.dart:2988:12)
E/flutter (  901): #12     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5445:14)
E/flutter (  901): #13     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194:14)
E/flutter (  901): #14     Element.updateChild (package:flutter/src/widgets/framework.dart:2988:12)
E/flutter (  901): #15     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4243:16)
E/flutter (  901): #16     Element.rebuild (package:flutter/src/widgets/framework.dart:3947:5)
E/flutter (  901): #17     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4206:5)
E/flutter (  901): #18     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4201:5)
E/flutter (  901): #19     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194:14)
E/flutter (  901): #20     Element.updateChild (package:flutter/src/widgets/framework.dart:2988:12)
E/flutter (  901): #21     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5445:14)
E/flutter (  901): #22     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194:14)
E/flutter (  901): #23     Element.updateChild (package:flutter/src/widgets/framework.dart:2988:12)
E/flutter (  901): #24     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5445:14)
E/flutter (  901): #25     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194:14)
E/flutter (  901): #26     Element.updateChild (package:flutter/src/widgets/framework.dart:2988:12)
E/flutter (  901): #27     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4243:16)
E/flutter (  901): #28     Element.rebuild (package:flutter/src/widgets/framework.dart:3947:5)
E/flutter (  901): #29     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4206:5)
E/flutter (  901): #30     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4381:11)
E/flutter (  901): #31     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4201:5)
E/flutter (  901): #32     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194:14)
E/flutter (  901): #33     Element.updateChild (package:flutter/src/widgets/framework.dart:2988:12)
E/flutter (  901): #34     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5445:14)
E/flutter (  901): #35     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194:14)
E/flutter (  901): #36     Element.updateChild (package:flutter/src/widgets/framework.dart:2988:12)
E/flutter (  901): #37     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5445:14)
E/flutter (  901): #38     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194:14)
E/flutter (  901): #39     Element.updateChild (package:flutter/src/widgets/framework.dart:2988:12)
E/flutter (  901): #40     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4243:16)
E/flutter (  901): #41     Element.rebuild (package:flutter/src/widgets/framework.dart:3947:5)
E/flutter (  901): #42     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4206:5)
E/flutter (  901): #43     StatefulElement._firstBuild (package:flutter/src/widgets/framework.
```

And here is flutter doctor:

```
$ flutter doctor -v
[✓] Flutter (Channel stable, v1.12.13+hotfix.9, on Mac OS X 10.15.4 19E287, locale en-RS)
    • Flutter version 1.12.13+hotfix.9 at /Users/lazarjovicic/flutter
    • Framework revision f139b11009 (4 weeks ago), 2020-03-30 13:57:30 -0700
    • Engine revision af51afceb8
    • Dart version 2.7.2

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/lazarjovicic/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.4.1, Build version 11E503a
    • CocoaPods version 1.8.4

[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)

[✓] VS Code (version 1.44.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.9.1

[✓] Connected device (1 available)
    • SM G970F • RF8M728WTMP • android-arm64 • Android 10 (API 29)

• No issues found!
```

This issue started happening suddenly even I added SHA1 and SHA265 certificate fingerprints.

Can you please help me to solve this issue?
Thanks :)

**Comment by alexpavelm** [comment]
Can you show us the code so that we can reproduce the error?

**Comment by lazarvgd** [comment]
> Can you show us the code so that we can reproduce the error?

Sure, here is git repo.
https://github.com/lazarvgd/tristagram.git

**Comment by alexpavelm** [comment]
As the package says about the signInSilently: 

> Attempts to sign in a previously authenticated user without interaction.

This will only work if you already logged in. You still have to log in through the signIn method the first time.

**Comment by lazarvgd** [comment]
> As the package says about the signInSilently:
> 
> > Attempts to sign in a previously authenticated user without interaction.
> 
> This will only work if you already logged in. You still have to log in through the signIn method the first time.

Thank you @alexpavelm, I completely forgot about that and spend whole day debugging. 

My bad, thanks.

**Comment by VladyslavBondarenko** [comment]
@lazarvgd given the last your comment may the issue be closed?

**Comment by TahaTesser** [comment]
Hi @lazarvgd 
Without additional information, we are unfortunately not sure how to resolve this issue. We are
therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the
bug if you have any more information for us; we will reopen it right away!
Thanks for your contribution.
