### ISSUE TITLE
Checkbox issue with toggling from checked, unchecked state to tristate/indeterminate, app crashes!

### ISSUE THREAD

**Issue by nishsvn-dev** [flutter/flutter#55866]
## Steps to Reproduce

Just copy the simple code provided,

```dart
class IndeterminateCheckbox extends StatefulWidget {
  IndeterminateCheckbox({Key key}) : super(key: key);

  @override
  _IndeterminateCheckboxState createState() => _IndeterminateCheckboxState();
}

class _IndeterminateCheckboxState extends State<IndeterminateCheckbox> {
  bool _value = true;
  bool _tristate = false;

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('Indeterminate Checkbox'),
      ),
      body: Center(
        child: Checkbox(
          value: _value,
          tristate: _tristate,
          onChanged: (val) {
            setState(() {
              _value = null;
              _tristate = true;
            });
          },
        ),
      ),
    );
  }
}
```

**Expected results:** Upon tapping checkbox, Checkbox should animate from Checked state to Tristate/Indeterminate state.

**Actual results:** Upon tapping checkbox, App crashes. On hot reloading, Checkbox would be in Tristate. I.e., to migrate from Checked/Unchecked state to tristate, app crashes in between.

<details>
  <summary>logs </summary>

```bash
Performing hot reload...
Syncing files to device Redmi Note 5...
Reloaded 0 of 519 libraries in 348ms.
I/zygote64(11867): Do partial code cache collection, code=61KB, data=45KB
I/zygote64(11867): After code cache collection, code=61KB, data=45KB
I/zygote64(11867): Increasing code cache capacity to 256KB

════════ Exception caught by widgets library ═══════════════════════════════════════════════════════
The following assertion was thrown building Builder:
'package:flutter/src/material/toggleable.dart': **Failed assertion: line 221 pos 12: 'tristate || value != null': is not true.**


Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=BUG.md

The relevant error-causing widget was: 
  Checkbox file:///Users/nishsvn/Development/Flutter/Earnspace/Envato/v2_ui_everything/lib/components/material/checkboxes/indeterminate_checkbox.dart:21:16
When the exception was thrown, this was the stack: 
#2      RenderToggleable.value= (package:flutter/src/material/toggleable.dart:221:12)
#3      _RenderCheckbox.value= (package:flutter/src/material/checkbox.dart:364:11)
#4      _CheckboxRenderObjectWidget.updateRenderObject (package:flutter/src/material/checkbox.dart:308:9)
#5      RenderObjectElement.update (package:flutter/src/widgets/framework.dart:5070:12)
#6      Element.updateChild (package:flutter/src/widgets/framework.dart:2977:15)
...
════════════════════════════════════════════════════════════════════════════════════════════════════
```

```console
Nishanths-MacBook-Air:v2_ui_everything nishsvn$ flutter doctor -v
[✓] Flutter (Channel stable, v1.12.13+hotfix.9, on Mac OS X 10.15.3 19D76, locale en-IN)
    • Flutter version 1.12.13+hotfix.9 at /Users/nishsvn/Development/Flutter/_sdk/flutter
    • Framework revision f139b11009 (4 weeks ago), 2020-03-30 13:57:30 -0700
    • Engine revision af51afceb8
    • Dart version 2.7.2

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/nishsvn/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.3.1, Build version 11C504
    • CocoaPods version 1.8.4

[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)

[!] VS Code (version 1.38.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    ✗ Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (2 available)
    • Redmi Note 5      • 62e9d4099805                         • android-arm64 • Android 8.1.0 (API 27)
    • iPhone 11 Pro Max • C65031E0-E514-4B4D-8453-3AE447F0AD5A • ios           • com.apple.CoreSimulator.SimRuntime.iOS-13-3
      (simulator)

! Doctor found issues in 1 category.
```

</details>

**Comment by iapicca** [comment]
Hi @nishsvn-dev 
I believe the problem is that `tristate` sort of overrides the `CheckBox`'s `onChanged`
so using the same to modify the state of tristate can be a problem;
please take a look to this [sample code](https://dartpad.dev/68707dc225e30a0a5c480bddd9fb73e8)
Does this solve your issue?
Thank you

**Comment by nishsvn-dev** [comment]
I had misunderstood the working of tristate checkbox. Thank you for the help, issue resolved.
