### ISSUE TITLE
[devicelab] questionable timeout error in devicelab test

### ISSUE THREAD

**Issue by jonahwilliams** [flutter/flutter#55875]
The flutter_attach_test_android is failing after all stages have seemingly passed. Seems like this might be coming from the test bed and not the test itself?

Task failed with the following reason:
Timeout waiting for task process to exit: Future not completed
Deleting build/ directories, if any.

More complete logs:

```
════════════════╡ ••• Testing hot reload, restart and quit ••• ╞════════════════

2020-04-28T10:12:19.449891: attach:stdout: Waiting for a connection from Flutter on Moto G 4...
2020-04-28T10:12:22.124172: attach:stdout: Syncing files to device Moto G 4...                                953ms
2020-04-28T10:12:22.136049: attach:stdout: 
2020-04-28T10:12:22.137110: attach:stdout: Flutter run key commands.
2020-04-28T10:12:22.140792: attach:stdout: r Hot reload. 🔥🔥🔥
2020-04-28T10:12:22.141632: attach:stdout: R Hot restart.
2020-04-28T10:12:22.142006: attach:stdout: h Repeat this help message.
2020-04-28T10:12:22.142441: attach:stdout: d Detach (terminate "flutter run" but leave application running).
2020-04-28T10:12:22.142881: attach:stdout: c Clear the screen
2020-04-28T10:12:22.143263: attach:stdout: q Quit (terminate the application on the device).
2020-04-28T10:12:22.143604: run:stdin: r
2020-04-28T10:12:22.143982: attach:stdout: An Observatory debugger and profiler on Moto G 4 is available at: http://127.0.0.1:44433/sXjRiXIoqn0=/
2020-04-28T10:12:22.152323: attach:stdout: 
2020-04-28T10:12:22.750906: attach:stdout: Performing hot reload...                                        
2020-04-28T10:12:22.751080: attach:stdout: Reloaded 0 of 720 libraries in 596ms.
2020-04-28T10:12:22.751306: run:stdin: R
2020-04-28T10:12:22.751689: attach:stdout: 
2020-04-28T10:12:24.820686: attach:stdout: Performing hot restart...                                       
2020-04-28T10:12:24.820773: attach:stdout: Restarted application in 2,068ms.
2020-04-28T10:12:24.820994: run:stdin: q
2020-04-28T10:12:24.821394: attach:stdout: 
2020-04-28T10:12:27.046377: attach:stdout: Application finished.
2020-04-28T10:12:27.091219: "/home/flutter/.cocoon/flutter/bin/flutter" exit code: 0
2020-04-28T10:12:27.091320: 

════════════════════════════╡ ••• Uninstalling ••• ╞════════════════════════════

2020-04-28T10:12:27.091547: 
Executing: /home/flutter/Android/Sdk/platform-tools/adb -s ZY223D5F28 uninstall com.yourcompany.integration_ui in /home/flutter/.cocoon/flutter/dev/integration_tests/ui
2020-04-28T10:12:27.565974: stdout: Success
2020-04-28T10:12:27.569263: "/home/flutter/Android/Sdk/platform-tools/adb" exit code: 0
2020-04-28T10:12:27.572188: 

═══════════╡ ••• Checking running Dart processes after task... ••• ╞════════════

2020-04-28T10:12:27.580616: Cleaning up after task...
2020-04-28T10:12:28.584622: Task execution finished

Task failed with the following reason:
Timeout waiting for task process to exit: Future not completed
Deleting build/ directories, if any.
2020-04-28T10:17:53.939005: Agent ID: flutter-devicelab-linux-4

```

**Comment by godofredoc** [comment]
@keyonghan would you mind taking a look?

**Comment by keyonghan** [comment]
Investigated logs of multiple runs on different commits, which run on different bots. All returned `Future not completed` error, but seems with different causes. 

Commit: bd6ccb606a11dacf7c72970a9d623e6b89668d70 (linux5)

```2020-04-29T16:41:49.439332:` run:stdin: q
2020-04-29T16:41:49.446296: attach:stdout: [   +7 ms] DevFS: Deleting filesystem on the device (file:///data/user/0/com.yourcompany.integration_ui/code_cache/uiPMSGUQ/ui/)
2020-04-29T16:41:49.465419: attach:stdout: [  +18 ms] DevFS: Deleted filesystem on the device (file:///data/user/0/com.yourcompany.integration_ui/code_cache/uiPMSGUQ/ui/)
2020-04-29T16:41:59.650758: attach:stdout: [+10184 ms] error: vm service shutdown failed
2020-04-29T16:41:59.652157: attach:stdout: [   +1 ms] Application finished.```

Commit: fdc6f38a440472a696c5347515d89fe4dd9d699f (linux3)
```2020-04-29T15:41:56.911653: attach:stdout: [   +3 ms] DevFS: Deleting filesystem on the device (file:///data/user/0/com.yourcompany.integration_ui/code_cache/uiVUSRLT/ui/)
2020-04-29T15:41:56.930373: attach:stdout: [  +18 ms] DevFS: Deleted filesystem on the device (file:///data/user/0/com.yourcompany.integration_ui/code_cache/uiVUSRLT/ui/)
2020-04-29T15:42:07.117720: attach:stdout: [+10186 ms] error: vm service shutdown failed
2020-04-29T15:42:07.124905: run:stderr: [   +6 ms] NoSuchMethodError: The getter 'id' was called on null.
run:stderr:            Receiver: null
run:stderr:            Tried calling: id
run:stderr:            #0      Object.noSuchMethod (dart:core-patch/object_patch.dart:53:5)
2020-04-29T15:42:07.125007: run:stderr:            #1      AndroidDevice.stopApp (package:flutter_tools/src/android/android_device.dart:650:96)
run:stderr:            #2      FlutterDevice.exitApps.<anonymous closure> (package:flutter_tools/src/resident_runner.dart:296:23)
run:stderr:            #3      _rootRun (dart:async/zone.dart:1180:38)
run:stderr:            #4      _CustomZone.run (dart:async/zone.dart:1077:19)
run:stderr:            #5      Future.timeout.<anonymous closure> (dart:async/future_impl.dart:775:33)
run:stderr:            #6      _rootRun (dart:async/zone.dart:1180:38)
run:stderr:            #7      _CustomZone.run (dart:async/zone.dart:1077:19)
run:stderr:            #8      _CustomZone.runGuarded (dart:async/zone.dart:979:7)
run:stderr:            #9      _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1019:23)
run:stderr:            #10     _rootRun (dart:async/zone.dart:1184:13)
run:stderr:            #11     _CustomZone.run (dart:async/zone.dart:1077:19)
run:stderr:            #12     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:1003:23)
run:stderr:            #13     Timer._createTimer.<anonymous closure> (dart:async-patch/timer_patch.dart:23:15)
run:stderr:            #14     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:398:19)
run:stderr:            #15     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:429:5)
run:stderr:            #16     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:168:12)
run:stderr: 
2020-04-29T15:42:07.126387: attach:stdout: [   +2 ms] Application finished.```

Commit: 0889e14361830b7922df58c199fba4fbe1563e00 (linux1)
(commit: 7ec50ddd66fa3166be08b779a4b5ba388a50ab24 (linux2) hit same error)
```═══════════╡ ••• Checking running Dart processes after task... ••• ╞════════════

2020-04-29T15:22:07.374566: run:stderr: [   +8 ms] Error connecting to the service protocol: connection to device ended too early
2020-04-29T15:22:07.374703: run:stderr: 
2020-04-29T15:22:07.374785: run:stderr: #0      throwToolExit (package:flutter_tools/src/base/common.dart:14:3)
2020-04-29T15:22:07.374865: run:stderr: #1      AttachCommand._attachToDevice (package:flutter_tools/src/commands/attach.dart:322:11)
2020-04-29T15:22:07.374936: run:stderr: <asynchronous suspension>
2020-04-29T15:22:07.375003: run:stderr: #2      AttachCommand.runCommand.<anonymous closure> (package:flutter_tools/src/commands/attach.dart:176:19)
2020-04-29T15:22:07.375071: run:stderr: #3      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:29)
2020-04-29T15:22:07.375134: run:stderr: #4      _rootRun (dart:async/zone.dart:1184:13)
2020-04-29T15:22:07.375197: run:stderr: #5      _CustomZone.run (dart:async/zone.dart:1077:19)
2020-04-29T15:22:07.375267: run:stderr: #6      _runZoned (dart:async/zone.dart:1619:10)
2020-04-29T15:22:07.375333: run:stderr: #7      runZoned (dart:async/zone.dart:1539:10)
2020-04-29T15:22:07.375404: run:stderr: #8      AppContext.run (package:flutter_tools/src/base/context.dart:149:18)
2020-04-29T15:22:07.375465: run:stderr: #9      AttachCommand.runCommand (package:flutter_tools/src/commands/attach.dart:175:19)
2020-04-29T15:22:07.375525: run:stderr: <asynchronous suspension>
2020-04-29T15:22:07.375587: run:stderr: #10     FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:765:18)
2020-04-29T15:22:07.375648: run:stderr: <asynchronous suspension>
2020-04-29T15:22:07.375706: run:stderr: #11     FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:662:33)
2020-04-29T15:22:07.375771: run:stderr: <asynchronous suspension>
2020-04-29T15:22:07.375834: run:stderr: #12     FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart)
2020-04-29T15:22:07.375896: run:stderr: #13     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:29)```

**Comment by keyonghan** [comment]
@jonahwilliams does it seem test related to you?

**Comment by jonahwilliams** [comment]
I definitely fixed some bugs it was covering. What is disturbing is that the latest runs seem to get through 100% of the test code so the timeout is either in the devicelab framework or in the devicelab agent.

```
2020-04-29T16:44:44.762097: run:stdin: q
2020-04-29T16:44:44.772685: attach:stdout: [  +10 ms] DevFS: Deleting filesystem on the device (file:///data/user/0/com.yourcompany.integration_ui/code_cache/uiMNRYFH/ui/)
2020-04-29T16:44:44.833393: attach:stdout: [  +60 ms] DevFS: Deleted filesystem on the device (file:///data/user/0/com.yourcompany.integration_ui/code_cache/uiMNRYFH/ui/)
2020-04-29T16:44:55.029713: attach:stdout: [+10196 ms] error: vm service shutdown failed
2020-04-29T16:44:55.031259: attach:stdout: [   +1 ms] Application finished.
2020-04-29T16:44:55.039246: attach:stdout: [   +7 ms] executing: /home/flutter/Android/Sdk/platform-tools/adb -s ZY223TDZ7R forward --list
2020-04-29T16:44:55.047516: attach:stdout: [   +8 ms] Exit code 0 from: /home/flutter/Android/Sdk/platform-tools/adb -s ZY223TDZ7R forward --list
2020-04-29T16:44:55.047785: attach:stdout: [        ] ZY223TDZ7R tcp:36809 tcp:43156
attach:stdout:            ZY223TDZ7R tcp:40607 tcp:44987
2020-04-29T16:44:55.052672: attach:stdout: [   +4 ms] executing: /home/flutter/Android/Sdk/platform-tools/adb -s ZY223TDZ7R forward --remove tcp:36809
2020-04-29T16:44:55.065527: attach:stdout: [  +12 ms] executing: /home/flutter/Android/Sdk/platform-tools/adb -s ZY223TDZ7R forward --remove tcp:40607
2020-04-29T16:44:55.074802: attach:stdout: [   +9 ms] executing: /home/flutter/Android/Sdk/platform-tools/adb -s ZY223TDZ7R forward --list
2020-04-29T16:44:55.082375: attach:stdout: [   +7 ms] Exit code 0 from: /home/flutter/Android/Sdk/platform-tools/adb -s ZY223TDZ7R forward --list
2020-04-29T16:44:55.087790: attach:stdout: [   +5 ms] executing: /home/flutter/Android/Sdk/platform-tools/adb -s ZY223TDZ7R forward --list
2020-04-29T16:44:55.095346: attach:stdout: [   +7 ms] Exit code 0 from: /home/flutter/Android/Sdk/platform-tools/adb -s ZY223TDZ7R forward --list
2020-04-29T16:44:55.097198: attach:stdout: [   +2 ms] "flutter attach" took 15,674ms.
2020-04-29T16:44:55.134850: "/home/flutter/.cocoon/flutter/bin/flutter" exit code: 0
2020-04-29T16:44:55.134981: 

════════════════════════════╡ ••• Uninstalling ••• ╞════════════════════════════

2020-04-29T16:44:55.135286: 
Executing: /home/flutter/Android/Sdk/platform-tools/adb -s ZY223TDZ7R uninstall com.yourcompany.integration_ui in /home/flutter/.cocoon/flutter/dev/integration_tests/ui
2020-04-29T16:44:55.578334: stdout: Success
2020-04-29T16:44:55.582828: "/home/flutter/Android/Sdk/platform-tools/adb" exit code: 0
2020-04-29T16:44:55.585994: 

═══════════╡ ••• Checking running Dart processes after task... ••• ╞════════════

2020-04-29T16:44:55.593808: Cleaning up after task...
2020-04-29T16:44:56.601812: Task execution finished

Task failed with the following reason:
Timeout waiting for task process to exit: Future not completed
```

I don't think that this is an infra issue to be clear, I think the devicelab test framework is broken or failing to surface some errors here. I'll keep digging
