### ISSUE TITLE
flutter_embedding_release.pom wasn't found in the local engine out directory.

### ISSUE THREAD

**Issue by v7lin** [flutter/flutter#55950]
## Steps to Reproduce

1. [Flutter Docker](https://github.com/v7lin/flutter_jit/blob/master/docker/build/Dockerfile) build local engine for flutter  1.12.13+hotfix.9
```bash
# Android JIT release
# arm
./flutter/tools/gn --android --runtime-mode jit_release --android-cpu arm
ninja -C out/android_jit_release
./flutter/tools/gn --runtime-mode jit_release --android-cpu arm
ninja -C out/host_jit_release

# arm64
./flutter/tools/gn --android --runtime-mode jit_release --android-cpu arm64
ninja -C out/android_jit_release_arm64
./flutter/tools/gn --runtime-mode jit_release --android-cpu arm64
ninja -C out/host_jit_release_arm64
```
2. build apk
```bash
flavorName=paid
flutter build apk -t lib/main/${flavorName}.dart --flavor ${flavorName} --no-shrink --local-engine=android_jit_release --local-engine-src-path=/opt/engine/src
```

## Logs

```
$ ls /opt/engine/src/out/android_jit_release
args.gn
armeabi_v7a_jit_release.jar
armeabi_v7a_jit_release.pom
build.ninja
build.ninja.d
clang_x64
flutter_embedding_jit_release.jar
flutter_embedding_jit_release.jar.md5.stamp
flutter_embedding_jit_release.pom
flutter_embedding_jit_release-sources.jar
flutter_embedding_jit_release-sources.jar.md5.stamp
flutter_icu
flutter.jar
flutter_patched_sdk
gen
icudtl.dat
libflutter.so
libflutter.so.TOC
lib.stripped
obj
toolchain.ninja
vm_outline_strong.dill
vm_platform_strong.dill
vm_platform_strong.dill.d
zip_archives
$ ls /opt/engine/src/out/android_jit_release_arm64
args.gn
arm64_v8a_jit_release.jar
arm64_v8a_jit_release.pom
build.ninja
build.ninja.d
clang_x64
flutter_embedding_jit_release.jar
flutter_embedding_jit_release.jar.md5.stamp
flutter_embedding_jit_release.pom
flutter_embedding_jit_release-sources.jar
flutter_embedding_jit_release-sources.jar.md5.stamp
flutter_icu
flutter.jar
flutter_patched_sdk
gen
icudtl.dat
libflutter.so
libflutter.so.TOC
lib.stripped
obj
toolchain.ninja
vm_outline_strong.dill
vm_platform_strong.dill
vm_platform_strong.dill.d
zip_archives
$ flavorName=paid
$ flutter build apk -t lib/main/${flavorName}.dart --flavor ${flavorName} --no-shrink --local-engine=android_jit_release --local-engine-src-path=/opt/engine/src
You are building a fat APK that includes binaries for android-arm, android-arm64, android-x64.
If you are deploying the app to the Play Store, it's recommended to use app bundles or split the APK to reduce the APK size.
    To generate an app bundle, run:
        flutter build appbundle --target-platform android-arm,android-arm64,android-x64
        Learn more on: https://developer.android.com/guide/app-bundle
    To split the APKs per ABI, run:
        flutter build apk --target-platform android-arm,android-arm64,android-x64 --split-per-abi
        Learn more on:  https://developer.android.com/studio/build/configure-apk-splits#configure-abi-split
Running Gradle task 'assemblePaidRelease'...                  
The file /opt/engine/src/out/android_jit_release/flutter_embedding_release.pom wasn't found in the local engine out directory.
```

```
[✓] Flutter (Channel stable, v1.12.13+hotfix.9, on Linux, locale en_US.UTF-8)
    • Flutter version 1.12.13+hotfix.9 at /opt/flutter
    • Framework revision f139b11009 (4 weeks ago), 2020-03-30 13:57:30 -0700
    • Engine revision af51afceb8
    • Dart version 2.7.2

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /opt/android-sdk-linux
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • ANDROID_HOME = /opt/android-sdk-linux
    • ANDROID_SDK_ROOT = /opt/android-sdk-linux
    • Java binary at: /usr/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_252-8u252-b09-1~18.04-b09)
    • All Android licenses accepted.

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/setup/#android-setup for detailed instructions).

[!] Connected device
    ! No devices available
```

**Comment by iapicca** [comment]
Hi @v7lin 
can you please provide your `flutter build apk --verbose` 
Thank you

**Comment by v7lin** [comment]
This is my first attempt to build flutter local engine

script
```bash
flutter build apk --verbose -t lib/main/${flavorName}.dart --flavor ${flavorName} --release --no-shrink --local-engine=android_jit_release --local-engine-src-path=/opt/engine/src
```
logs
```
$ flutter build apk --verbose -t lib/main/${flavorName}.dart --flavor ${flavorName} --release --no-shrink --local-engine=android_jit_release --local-engine-src-path=/opt/engine/src
[  +48 ms] executing: [/opt/flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[  +42 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[        ] f139b11009aeb8ed2a3a3aa8b0066e482709dde3
[        ] executing: [/opt/flutter/] git describe --match v*.*.* --first-parent --long --tags
[  +10 ms] Exit code 0 from: git describe --match v*.*.* --first-parent --long --tags
[        ] v1.12.13+hotfix.9-0-gf139b1100
[   +9 ms] executing: [/opt/flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[  +10 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/stable
[        ] executing: [/opt/flutter/] git ls-remote --get-url origin
[   +8 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[  +66 ms] executing: [/opt/flutter/] git rev-parse --abbrev-ref HEAD
[   +8 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] stable
[  +40 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[   +4 ms] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +2 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[ +135 ms] Found plugin android_intent at /opt/flutter/.pub-cache/hosted/pub.flutter-io.cn/android_intent-0.3.6+1/
[  +12 ms] Found plugin apple_authorization at /opt/flutter/.pub-cache/git/flutter_toolkit-8c8300d1191cc01a1d6bc9e6386140090baf3c0b/apple_authorization/
[  +12 ms] Found plugin battery at /opt/flutter/.pub-cache/hosted/pub.flutter-io.cn/battery-0.2.3/
[  +31 ms] Found plugin city_pickers at /opt/flutter/.pub-cache/hosted/pub.flutter-io.cn/city_pickers-0.1.30/
[  +15 ms] Found plugin device_info at /opt/flutter/.pub-cache/hosted/pub.flutter-io.cn/device_info-0.4.1+5/
[  +10 ms] Found plugin fake_path_provider at /opt/flutter/.pub-cache/hosted/pub.flutter-io.cn/fake_path_provider-0.1.0/
[   +2 ms] Found plugin fake_tencent at /opt/flutter/.pub-cache/hosted/pub.flutter-io.cn/fake_tencent-0.3.4/
[   +2 ms] Found plugin fake_wechat at /opt/flutter/.pub-cache/hosted/pub.flutter-io.cn/fake_wechat-0.3.4/
[   +1 ms] Found plugin fake_weibo at /opt/flutter/.pub-cache/hosted/pub.flutter-io.cn/fake_weibo-0.2.2/
[   +5 ms] Found plugin flutter_baidu_tts_plugin at /opt/flutter/.pub-cache/git/flutter_baidu_tts_plugin-37328077c3293b15b44a19001153768eed2dc02a/
[   +2 ms] Found plugin flutter_bugly at /opt/flutter/.pub-cache/git/flutter_bugly-e4ad11bcf5a97e086a389d4657a98360b44f8a94/
[   +3 ms] Found plugin flutter_deeplink at /opt/flutter/.pub-cache/git/flutter_deeplink-ebb0145835f6377354d69799eb79ca95d0a64cbc/
[   +6 ms] Found plugin flutter_mix_push at /opt/flutter/.pub-cache/git/flutter_mix_push-66f07050c588f8b33f1522b95bba8ae273461fc1/
[   +2 ms] Found plugin flutter_plugin_android_lifecycle at /opt/flutter/.pub-cache/hosted/pub.flutter-io.cn/flutter_plugin_android_lifecycle-1.0.6/
[   +3 ms] Found plugin flutter_statusbar_manager at /opt/flutter/.pub-cache/git/flutter_statusbar_manager-b33a851e5627901560869f9ed6a2895f3dd5f9a3/
[   +1 ms] Found plugin flutter_system_features at /opt/flutter/.pub-cache/git/flutter_system_features-9af6fbc24e5bbae77dc847dea25ae1c52a7902db/
[   +3 ms] Found plugin flutter_umpush at /opt/flutter/.pub-cache/git/flutter_umpush_plugin-a28b7efc36cf30e63044408eda84721c7958165f/
[   +1 ms] Found plugin flutter_user_agent at /opt/flutter/.pub-cache/hosted/pub.flutter-io.cn/flutter_user_agent-1.2.1/
[   +4 ms] Found plugin flutter_webview_plugin at /opt/flutter/.pub-cache/git/flutter_webview_plugin-d464002f3988d172f3e33d3a86b035c466e46914/
[   +1 ms] Found plugin fluttertoast at /opt/flutter/.pub-cache/hosted/pub.flutter-io.cn/fluttertoast-3.1.3/
[  +10 ms] Found plugin image_cropper at /opt/flutter/.pub-cache/hosted/pub.flutter-io.cn/image_cropper-1.0.0/
[   +1 ms] Found plugin image_picker at /opt/flutter/.pub-cache/hosted/pub.flutter-io.cn/image_picker-0.6.3+4/
[   +1 ms] Found plugin image_picker_saver at /opt/flutter/.pub-cache/git/flutter_toolkit-b8740ff84503a1141740db286696b033137c7677/image_picker_saver/
[   +1 ms] Found plugin in_app_purchase at /opt/flutter/.pub-cache/hosted/pub.flutter-io.cn/in_app_purchase-0.3.1+2/
[  +13 ms] Found plugin mob_ads_pangolin at /opt/flutter/.pub-cache/git/mob_ads_pangolin-4fa2352834f040f629dd5c3394325f0c7878a340/
[   +3 ms] Found plugin notch at /opt/flutter/.pub-cache/git/flutter_toolkit-73c6431b671fa195a599ce4be163c5b9b83af68a/notch/
[   +1 ms] Found plugin open_udid at /opt/flutter/.pub-cache/git/flutter_toolkit-88580ee7ee9041f46eb5e84d432bee9ff355d4f1/open_udid/
[   +1 ms] Found plugin package_info at /opt/flutter/.pub-cache/hosted/pub.flutter-io.cn/package_info-0.4.0+14/
[   +3 ms] Found plugin path_provider at /opt/flutter/.pub-cache/hosted/pub.flutter-io.cn/path_provider-0.5.0+1/
[   +2 ms] Found plugin permission_handler at /opt/flutter/.pub-cache/git/flutter-permission-handler-4cb76c3aa1ead44fbdc2676ff3cf7a9d198434d8/
[   +2 ms] Found plugin photo_manager at /opt/flutter/.pub-cache/git/flutter_photo_manager-5810294bd36f22d36126a1ab19ddc6322f05ae65/
[   +8 ms] Found plugin screen at /opt/flutter/.pub-cache/hosted/pub.flutter-io.cn/screen-0.0.5/
[   +1 ms] Found plugin share at /opt/flutter/.pub-cache/hosted/pub.flutter-io.cn/share-0.6.3+6/
[   +1 ms] Found plugin share_extend at /opt/flutter/.pub-cache/hosted/pub.flutter-io.cn/share_extend-1.1.1/
[        ] Found plugin shared_preferences at /opt/flutter/.pub-cache/hosted/pub.flutter-io.cn/shared_preferences-0.4.3/
[   +4 ms] Found plugin sqflite at /opt/flutter/.pub-cache/hosted/pub.flutter-io.cn/sqflite-1.2.2+1/
[   +7 ms] Found plugin tobias at /opt/flutter/.pub-cache/git/tobias-578ba153d681dfa099d1f0ded6d85ec325eaa070/
[   +1 ms] Found plugin url_launcher at /opt/flutter/.pub-cache/hosted/pub.flutter-io.cn/url_launcher-5.4.2/
[   +1 ms] Found plugin url_launcher_macos at /opt/flutter/.pub-cache/hosted/pub.flutter-io.cn/url_launcher_macos-0.0.1+4/
[   +1 ms] Found plugin url_launcher_web at /opt/flutter/.pub-cache/hosted/pub.flutter-io.cn/url_launcher_web-0.1.1+1/
[  +52 ms] Found plugin android_intent at /opt/flutter/.pub-cache/hosted/pub.flutter-io.cn/android_intent-0.3.6+1/
[   +1 ms] Found plugin apple_authorization at /opt/flutter/.pub-cache/git/flutter_toolkit-8c8300d1191cc01a1d6bc9e6386140090baf3c0b/apple_authorization/
[   +4 ms] Found plugin battery at /opt/flutter/.pub-cache/hosted/pub.flutter-io.cn/battery-0.2.3/
[  +11 ms] Found plugin city_pickers at /opt/flutter/.pub-cache/hosted/pub.flutter-io.cn/city_pickers-0.1.30/
[   +5 ms] Found plugin device_info at /opt/flutter/.pub-cache/hosted/pub.flutter-io.cn/device_info-0.4.1+5/
[   +3 ms] Found plugin fake_path_provider at /opt/flutter/.pub-cache/hosted/pub.flutter-io.cn/fake_path_provider-0.1.0/
[   +1 ms] Found plugin fake_tencent at /opt/flutter/.pub-cache/hosted/pub.flutter-io.cn/fake_tencent-0.3.4/
[   +2 ms] Found plugin fake_wechat at /opt/flutter/.pub-cache/hosted/pub.flutter-io.cn/fake_wechat-0.3.4/
[   +1 ms] Found plugin fake_weibo at /opt/flutter/.pub-cache/hosted/pub.flutter-io.cn/fake_weibo-0.2.2/
[   +3 ms] Found plugin flutter_baidu_tts_plugin at /opt/flutter/.pub-cache/git/flutter_baidu_tts_plugin-37328077c3293b15b44a19001153768eed2dc02a/
[        ] Found plugin flutter_bugly at /opt/flutter/.pub-cache/git/flutter_bugly-e4ad11bcf5a97e086a389d4657a98360b44f8a94/
[   +2 ms] Found plugin flutter_deeplink at /opt/flutter/.pub-cache/git/flutter_deeplink-ebb0145835f6377354d69799eb79ca95d0a64cbc/
[   +2 ms] Found plugin flutter_mix_push at /opt/flutter/.pub-cache/git/flutter_mix_push-66f07050c588f8b33f1522b95bba8ae273461fc1/
[        ] Found plugin flutter_plugin_android_lifecycle at /opt/flutter/.pub-cache/hosted/pub.flutter-io.cn/flutter_plugin_android_lifecycle-1.0.6/
[   +1 ms] Found plugin flutter_statusbar_manager at /opt/flutter/.pub-cache/git/flutter_statusbar_manager-b33a851e5627901560869f9ed6a2895f3dd5f9a3/
[        ] Found plugin flutter_system_features at /opt/flutter/.pub-cache/git/flutter_system_features-9af6fbc24e5bbae77dc847dea25ae1c52a7902db/
[   +2 ms] Found plugin flutter_umpush at /opt/flutter/.pub-cache/git/flutter_umpush_plugin-a28b7efc36cf30e63044408eda84721c7958165f/
[   +1 ms] Found plugin flutter_user_agent at /opt/flutter/.pub-cache/hosted/pub.flutter-io.cn/flutter_user_agent-1.2.1/
[   +1 ms] Found plugin flutter_webview_plugin at /opt/flutter/.pub-cache/git/flutter_webview_plugin-d464002f3988d172f3e33d3a86b035c466e46914/
[        ] Found plugin fluttertoast at /opt/flutter/.pub-cache/hosted/pub.flutter-io.cn/fluttertoast-3.1.3/
[   +6 ms] Found plugin image_cropper at /opt/flutter/.pub-cache/hosted/pub.flutter-io.cn/image_cropper-1.0.0/
[        ] Found plugin image_picker at /opt/flutter/.pub-cache/hosted/pub.flutter-io.cn/image_picker-0.6.3+4/
[        ] Found plugin image_picker_saver at /opt/flutter/.pub-cache/git/flutter_toolkit-b8740ff84503a1141740db286696b033137c7677/image_picker_saver/
[        ] Found plugin in_app_purchase at /opt/flutter/.pub-cache/hosted/pub.flutter-io.cn/in_app_purchase-0.3.1+2/
[   +7 ms] Found plugin mob_ads_pangolin at /opt/flutter/.pub-cache/git/mob_ads_pangolin-4fa2352834f040f629dd5c3394325f0c7878a340/
[   +2 ms] Found plugin notch at /opt/flutter/.pub-cache/git/flutter_toolkit-73c6431b671fa195a599ce4be163c5b9b83af68a/notch/
[        ] Found plugin open_udid at /opt/flutter/.pub-cache/git/flutter_toolkit-88580ee7ee9041f46eb5e84d432bee9ff355d4f1/open_udid/
[   +1 ms] Found plugin package_info at /opt/flutter/.pub-cache/hosted/pub.flutter-io.cn/package_info-0.4.0+14/
[   +1 ms] Found plugin path_provider at /opt/flutter/.pub-cache/hosted/pub.flutter-io.cn/path_provider-0.5.0+1/
[   +2 ms] Found plugin permission_handler at /opt/flutter/.pub-cache/git/flutter-permission-handler-4cb76c3aa1ead44fbdc2676ff3cf7a9d198434d8/
[   +1 ms] Found plugin photo_manager at /opt/flutter/.pub-cache/git/flutter_photo_manager-5810294bd36f22d36126a1ab19ddc6322f05ae65/
[   +6 ms] Found plugin screen at /opt/flutter/.pub-cache/hosted/pub.flutter-io.cn/screen-0.0.5/
[        ] Found plugin share at /opt/flutter/.pub-cache/hosted/pub.flutter-io.cn/share-0.6.3+6/
[        ] Found plugin share_extend at /opt/flutter/.pub-cache/hosted/pub.flutter-io.cn/share_extend-1.1.1/
[        ] Found plugin shared_preferences at /opt/flutter/.pub-cache/hosted/pub.flutter-io.cn/shared_preferences-0.4.3/
[   +2 ms] Found plugin sqflite at /opt/flutter/.pub-cache/hosted/pub.flutter-io.cn/sqflite-1.2.2+1/
[   +3 ms] Found plugin tobias at /opt/flutter/.pub-cache/git/tobias-578ba153d681dfa099d1f0ded6d85ec325eaa070/
[   +1 ms] Found plugin url_launcher at /opt/flutter/.pub-cache/hosted/pub.flutter-io.cn/url_launcher-5.4.2/
[        ] Found plugin url_launcher_macos at /opt/flutter/.pub-cache/hosted/pub.flutter-io.cn/url_launcher_macos-0.0.1+4/
[   +1 ms] Found plugin url_launcher_web at /opt/flutter/.pub-cache/hosted/pub.flutter-io.cn/url_launcher_web-0.1.1+1/
[  +67 ms] Generating /builds/apps/demo/android/app/src/main/java/io/flutter/plugins/GeneratedPluginRegistrant.java
[  +32 ms] You are building a fat APK that includes binaries for android-arm, android-arm64, android-x64.
[        ] If you are deploying the app to the Play Store, it's recommended to use app bundles or split the APK to reduce the APK size.
[        ]     To generate an app bundle, run:
[        ]         flutter build appbundle --target-platform android-arm,android-arm64,android-x64
[        ]         Learn more on: https://developer.android.com/guide/app-bundle
[        ]     To split the APKs per ABI, run:
[        ]         flutter build apk --target-platform android-arm,android-arm64,android-x64 --split-per-abi
[        ]         Learn more on:  https://developer.android.com/studio/build/configure-apk-splits#configure-abi-split
[  +30 ms] Running Gradle task 'assemblePaidRelease'...
[   +2 ms] gradle.properties already sets `android.enableR8`
[  +15 ms] Using gradle from /builds/apps/demo/android/gradlew.
[  +28 ms] "flutter apk" took 699ms.
The file /opt/engine/src/out/android_jit_release/flutter_embedding_release.pom wasn't found in the local engine out directory.

#0      throwToolExit (package:flutter_tools/src/base/common.dart:28:3)
#1      _getLocalArtifactVersion (package:flutter_tools/src/android/gradle.dart:853:5)
#2      _getLocalEngineRepo (package:flutter_tools/src/android/gradle.dart:900:34)
#3      buildGradleApp (package:flutter_tools/src/android/gradle.dart:285:39)
#4      _AndroidBuilderImpl.buildApk (package:flutter_tools/src/android/android_builder.dart:97:13)
#5      BuildApkCommand.runCommand (package:flutter_tools/src/commands/build_apk.dart:106:26)
#6      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:615:18)
<asynchronous suspension>
#7      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:515:33)
<asynchronous suspension>
#8      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:146:29)
#9      _rootRun (dart:async/zone.dart:1126:13)
#10     _CustomZone.run (dart:async/zone.dart:1023:19)
#11     _runZoned (dart:async/zone.dart:1518:10)
#12     runZoned (dart:async/zone.dart:1465:12)
#13     AppContext.run (package:flutter_tools/src/base/context.dart:145:18)
#14     FlutterCommand.run (package:flutter_tools/src/runner/flutter_command.dart:505:20)
#15     CommandRunner.runCommand (package:args/command_runner.dart:197:27)
#16     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:413:21)
<asynchronous suspension>
#17     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:146:29)
#18     _rootRun (dart:async/zone.dart:1126:13)
#19     _CustomZone.run (dart:async/zone.dart:1023:19)
#20     _runZoned (dart:async/zone.dart:1518:10)
#21     runZoned (dart:async/zone.dart:1465:12)
#22     AppContext.run (package:flutter_tools/src/base/context.dart:145:18)
#23     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:364:19)
#24     CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:112:25)
#25     new Future.sync (dart:async/future.dart:224:31)
#26     CommandRunner.run (package:args/command_runner.dart:112:14)
#27     FlutterCommandRunner.run (package:flutter_tools/src/runner/flutter_command_runner.dart:250:18)
#28     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:63:22)
#29     _rootRun (dart:async/zone.dart:1126:13)
#30     _CustomZone.run (dart:async/zone.dart:1023:19)
#31     _runZoned (dart:async/zone.dart:1518:10)
#32     runZoned (dart:async/zone.dart:1502:12)
#33     run.<anonymous closure> (package:flutter_tools/runner.dart:61:18)
<asynchronous suspension>
#34     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:146:29)
#35     _rootRun (dart:async/zone.dart:1126:13)
#36     _CustomZone.run (dart:async/zone.dart:1023:19)
#37     _runZoned (dart:async/zone.dart:1518:10)
#38     runZoned (dart:async/zone.dart:1465:12)
#39     AppContext.run (package:flutter_tools/src/base/context.dart:145:18)
#40     runInContext (package:flutter_tools/src/context_runner.dart:64:24)
#41     run (package:flutter_tools/runner.dart:50:10)
#42     main (package:flutter_tools/executable.dart:65:9)
#43     main (file:///b/s/w/ir/k/archive/flutter/packages/flutter_tools/bin/flutter_tools.dart:8:3)
#44     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:305:32)
#45     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:174:12)


ERROR: Job failed: exit code 1
```

**Comment by jonahwilliams** [comment]
The flutter Gradle script does not currently support the JIT release mode.

**Comment by iapicca** [comment]
Hi @v7lin 
does the issue occur building the engine in [aot mode](https://github.com/flutter/flutter/wiki/Custom-Flutter-Engine-Embedding-in-AOT-Mode)?
Thank you

**Comment by v7lin** [comment]
> Hi @v7lin
> does the issue occur building the engine in [aot mode](https://github.com/flutter/flutter/wiki/Custom-Flutter-Engine-Embedding-in-AOT-Mode)?
> Thank you

jit mode

**Comment by iapicca** [comment]
Hi again @v7lin 
as mentioned [above](https://github.com/flutter/flutter/issues/55950#issuecomment-621609385) `jit` isn't supported;
can you reproduce the case in `aot` mode?
Thank you

**Comment by iapicca** [comment]
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact descriptions what happens, logs and the output of 'flutter doctor -v'  please.
All system setups can be slightly different so it's always better to open new issues and reference related issues.
