### ISSUE TITLE
 No supported devices connected.

### ISSUE THREAD

**Issue by Siddhesh43** [flutter/flutter#55976]
## Steps to Reproduce

1. I'm getting this kind of error when I use a physical device to run my app.
My device is Samsung Galaxy J7 (2016). I have enabled USB debugging.
2. I tried out `flutter doctor` and it shows everything is just good. No issues.
3. I also re-installed all the Android Studio SDKs.

```
My PC Specs:
Intel Core i3-3220
Intel hd Graphics 2500 1024 mb
8gb ddr3 ram
WD purple 1tb hdd
```

PS. Ignore that the device is not connected. This is because for internet usage, I use USB tethering while when I want to run my app, I stop the USb tethering and then allow MTP connection and Android Studio permissions as well.

**Expected results:** 
My app successfully running on my device

**Actual results:** 
`Finished with: gradle task assembleDebugfailed with exit code 1`
[flutter doctor](https://user-images.githubusercontent.com/55309498/80630349-b290e800-8a71-11ea-9c39-f9f40069d783.PNG)
[android studio (flutter)](https://user-images.githubusercontent.com/55309498/80630589-17e4d900-8a72-11ea-8d2a-148642364c39.PNG)
[main dart](https://user-images.githubusercontent.com/55309498/80630595-19ae9c80-8a72-11ea-989b-1d704da9543a.PNG)
[pubspec yaml](https://user-images.githubusercontent.com/55309498/80630599-1adfc980-8a72-11ea-948e-cb7027514f29.PNG)
[sdk manager](https://user-images.githubusercontent.com/55309498/80630745-55496680-8a72-11ea-9f2c-c569b6dc6f8a.PNG)
[the error](https://user-images.githubusercontent.com/55309498/80630955-a48f9700-8a72-11ea-8ad1-2d832852f03e.PNG)

This is what I get when I run `flutter run --verbose` in the root file of my app

```bash
[  +32 ms] executing: [G:\android_studio\flutter\] git -c log.showSignature=false log -n 1 --pretty=format:%H
[ +119 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[   +2 ms] f139b11009aeb8ed2a3a3aa8b0066e482709dde3
[        ] executing: [G:\android_studio\flutter\] git describe --match v*.*.* --first-parent --long --tags
[ +102 ms] Exit code 0 from: git describe --match v*.*.* --first-parent --long --tags
[        ] v1.12.13+hotfix.9-0-gf139b1100
[   +7 ms] executing: [G:\android_studio\flutter\] git rev-parse --abbrev-ref --symbolic @{u}
[  +89 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/stable
[        ] executing: [G:\android_studio\flutter\] git ls-remote --get-url origin
[  +85 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[ +153 ms] executing: [G:\android_studio\flutter\] git rev-parse --abbrev-ref HEAD
[ +105 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] stable
[ +144 ms] executing: G:\android_studio\android-studio-sdk\platform-tools\adb.exe devices -l
[  +95 ms] Exit code 0 from: G:\android_studio\android-studio-sdk\platform-tools\adb.exe devices -l
[        ] List of devices attached
[  +10 ms] No supported devices connected.
[  +11 ms] "flutter run" took 367ms.

#0      throwToolExit (package:flutter_tools/src/base/common.dart:28:3)
#1      RunCommand.validateCommand (package:flutter_tools/src/commands/run.dart:289:7)
<asynchronous suspension>
#2      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:590:11)
#3      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:515:33)
<asynchronous suspension>
#4      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:146:29)
#5      _rootRun (dart:async/zone.dart:1126:13)
#6      _CustomZone.run (dart:async/zone.dart:1023:19)
#7      _runZoned (dart:async/zone.dart:1518:10)
#8      runZoned (dart:async/zone.dart:1465:12)
#9      AppContext.run (package:flutter_tools/src/base/context.dart:145:18)
#10     FlutterCommand.run (package:flutter_tools/src/runner/flutter_command.dart:505:20)
#11     CommandRunner.runCommand (package:args/command_runner.dart:197:27)
#12     FlutterCommandRunner.runCommand.<anonymous closure>
(package:flutter_tools/src/runner/flutter_command_runner.dart:413:21)
<asynchronous suspension>
#13     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:146:29)
#14     _rootRun (dart:async/zone.dart:1126:13)
#15     _CustomZone.run (dart:async/zone.dart:1023:19)
#16     _runZoned (dart:async/zone.dart:1518:10)
#17     runZoned (dart:async/zone.dart:1465:12)
#18     AppContext.run (package:flutter_tools/src/base/context.dart:145:18)
#19     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:364:19)
#20     CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:112:25)
#21     new Future.sync (dart:async/future.dart:224:31)
#22     CommandRunner.run (package:args/command_runner.dart:112:14)
#23     FlutterCommandRunner.run (package:flutter_tools/src/runner/flutter_command_runner.dart:250:18)
#24     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:63:22)
#25     _rootRun (dart:async/zone.dart:1126:13)
#26     _CustomZone.run (dart:async/zone.dart:1023:19)
#27     _runZoned (dart:async/zone.dart:1518:10)
#28     runZoned (dart:async/zone.dart:1502:12)
#29     run.<anonymous closure> (package:flutter_tools/runner.dart:61:18)
<asynchronous suspension>
#30     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:146:29)
#31     _rootRun (dart:async/zone.dart:1126:13)
#32     _CustomZone.run (dart:async/zone.dart:1023:19)
#33     _runZoned (dart:async/zone.dart:1518:10)
#34     runZoned (dart:async/zone.dart:1465:12)
#35     AppContext.run (package:flutter_tools/src/base/context.dart:145:18)
#36     runInContext (package:flutter_tools/src/context_runner.dart:64:24)
#37     run (package:flutter_tools/runner.dart:50:10)
#38     main (package:flutter_tools/executable.dart:65:9)
#39     main (file:///C:/b/s/w/ir/k/archive/flutter/packages/flutter_tools/bin/flutter_tools.dart:8:3)
#40     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:305:32)
#41     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:174:12)
```

These are the results when I analyzed the app
```console
 info - Avoid using web-only libraries outside Flutter web plugin packages - lib\main.dart:2:1 -
          avoid_web_libraries_in_flutter
   info - Unused import: 'package:iamrich/main.dart' - test\widget_test.dart:11:8 - unused_import

2 issues found. (ran in 2.9s)
```

These are the results when I ran `flutter doctor -v`
```console
[√] Flutter (Channel stable, v1.12.13+hotfix.9, on Microsoft Windows [Version 10.0.17134.829], locale en-IN)
    • Flutter version 1.12.13+hotfix.9 at G:\android_studio\flutter
    • Framework revision f139b11009 (4 weeks ago), 2020-03-30 13:57:30 -0700
    • Engine revision af51afceb8
    • Dart version 2.7.2


[√] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at G:\android_studio\android-studio-sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.3
    • ANDROID_HOME = G:\android_studio\android-studio-sdk
    • ANDROID_SDK_ROOT = G:\android_studio\android-studio-sdk
    • Java binary at: G:\android_studio\android-studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)
    • All Android licenses accepted.

[√] Android Studio (version 3.6)
    • Android Studio at G:\android_studio\android-studio
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)

[!] Connected device
    ! No devices available

! Doctor found issues in 1 category.
```

This is the main.dart file source code:
```dart
import 'package:flutter/material.dart';
import 'dart:html';

// The main function is the starting point for all our Flutter apps.
void main() {
  runApp(
    MaterialApp(
      home: Scaffold(
        backgroundColor: Colors.blueGrey,
        appBar: AppBar(
          title: Text('I Am Rich'),
          backgroundColor: Colors.blueGrey[900],
        ),
        body: Center(
          child: Image(
            image: AssetImage('images/diamond.png'),
          ),
        ),
      ),
    ),
  );
}
```

I am new to android development and I've just started learning Flutter. This was just a demo project which I was making and it really felt embarrassing to see it get failed right at the moment it was getting built.

**Comment by ArlandMv** [comment]
-First you have to make sure your device is available after flutter doctor
-Then follow the steps in this video: https://youtu.be/kcEKZKm4yb8

Have a nice day

**Comment by iapicca** [comment]
Hi @ArlandMv 
given the error
```bash
[  +95 ms] Exit code 0 from: G:\android_studio\android-studio-sdk\platform-tools\adb.exe devices -l
[        ] List of devices attached
[  +10 ms] No supported devices connected.
[  +11 ms] "flutter run" took 367ms.
```
the issue seems indeed to depend from your device not being recognised
what's the output of `flutter devices`?
Please refrain from posting pictures if not necessary
Thank you

**Comment by Siddhesh43** [comment]
I'm cleared with the issue. Actually, I think that the fault was that my Computer wasn't connected to the internet. Due to this, it might be showing that error. When I connected to the internet and then started up the emulator then it worked well!
