### ISSUE TITLE
[tool_crash] FileSystemException: Failed to set file modification time, OS Error: Operation not permitted, errno = 1

### ISSUE THREAD

**Issue by M001T** [flutter/flutter#55979]
## Command
```console
flutter run
```

## Steps to Reproduce
1 type: try `pod install`
2 type: `flutter run -d macOS`
3 type: ` flutter run`

## Logs
`FileSystemException: Failed to set file modification time, OS Error: Operation not permitted, errno = 1
`

```bash
#0      _File.setLastModifiedSync (dart:io/file_impl.dart:473:7)
#1      ForwardingFile.setLastModifiedSync (package:file/src/forwarding/forwarding_file.dart:62:55)
#2      ForwardingFile.setLastModifiedSync (package:file/src/forwarding/forwarding_file.dart:62:55)
#3      _DefaultPub.get (package:flutter_tools/src/dart/pub.dart:247:25)
#4      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:743:17)
<asynchronous suspension>
#5      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:657:33)
<asynchronous suspension>
#6      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart)
#7      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:29)
#8      _rootRun (dart:async/zone.dart:1184:13)
#9      _CustomZone.run (dart:async/zone.dart:1077:19)
#10     _runZoned (dart:async/zone.dart:1619:10)
#11     runZoned (dart:async/zone.dart:1539:10)
#12     AppContext.run (package:flutter_tools/src/base/context.dart:149:18)
#13     FlutterCommand.run (package:flutter_tools/src/runner/flutter_command.dart:647:20)
#14     CommandRunner.runCommand (package:args/command_runner.dart:197:27)
#15     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:339:21)
<asynchronous suspension>
#16     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart)
#17     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:29)
#18     _rootRun (dart:async/zone.dart:1184:13)
#19     _CustomZone.run (dart:async/zone.dart:1077:19)
#20     _runZoned (dart:async/zone.dart:1619:10)
#21     runZoned (dart:async/zone.dart:1539:10)
```

```console
[✓] Flutter (Channel master, 1.18.0-9.0.pre.62, on Mac OS X 10.15.4 19E287,
    locale pt-BR)
    • Flutter version 1.18.0-9.0.pre.62 at /Users/devfacil/Desktop/flutter
    • Framework revision b7586d873a (2 hours ago), 2020-04-29 12:44:01 -0400
    • Engine revision 2db3276573
    • Dart version 2.9.0 (build 2.9.0-3.0.dev 726d3c7725)

[!] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/devfacil/Library/Android/sdk
    • Platform android-29, build-tools 29.0.3
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_212-release-1586-b4-5784211)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor
      --android-licenses

[✓] Xcode - develop for iOS and macOS (Xcode 11.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.3.1, Build version 11C504
    • CocoaPods version 1.9.1

[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 45.0.1
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build
      1.8.0_212-release-1586-b4-5784211)

[✓] VS Code (version 1.44.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.9.1

[✓] Connected device (1 available)
    • macOS • macOS • darwin-x64 • Mac OS X 10.15.4 19E287

! Doctor found issues in 1 category.

```

## Flutter Application Metadata
**Type**: app
**Version**: 1.0.0+1
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: beta
**Creation framework version**: 18cd7a3601bcffb36fdf2f679f763b5e827c2e8e

### Plugins

```
cloud_firestore-0.13.5
cloud_firestore_web-0.1.1+2
firebase_auth-0.15.5+3
firebase_auth_web-0.1.2
firebase_core-0.4.4+3
firebase_core_web-0.1.1+2
firebase_database-3.1.3
firebase_messaging-6.0.13
firebase_storage-3.1.5
flutter_facebook_login-2.0.1
flutter_inapp_purchase-2.1.4
flutter_plugin_android_lifecycle-1.0.7
flutter_webview_plugin-0.3.11
geocoder-0.2.1
get_ip-0.4.0
google_maps_flutter-0.5.26+4
google_sign_in-4.4.4
google_sign_in_web-0.9.1
image_picker-0.6.5+2
in_app_purchase-0.3.2+2
move_to_background-1.0.0+1
multi_image_picker-4.6.6+rc.1
onesignal_flutter-2.4.0
path_provider-1.6.7
path_provider_macos-0.0.4+1
shared_preferences-0.5.7
shared_preferences_macos-0.0.1+7
shared_preferences_web-0.1.2+4
sqflite-1.3.0
stripe_payment-1.0.7
video_player-0.10.9
video_player_web-0.1.2+1
webview_flutter-0.3.20+2
```

**Comment by iapicca** [comment]
Hi @M001T 
if you are running your app as `desktop` app on `macOS`

> 2 type: flutter run -d macOS

please make sure that the plugins you are using are compatible,
some on your list definitely aren't.

could you please run your full `flutter run -d macOS --verbose`
and a reproducible minimal code sample
Thank you
