### ISSUE TITLE
TextField's text is reset after turning off display or navigating away from the page

### ISSUE THREAD

**Issue by mshwf** [flutter/flutter#55994]
## Steps to Reproduce

1. Create a new project
2. Include only `TextField` widget
3. Run the project
3. Type some text, then navigate away from the page by going to the device home screen or turning off display.
4. Go back to the appliation.

**Expected results:** text is still in the `TextField`

**Actual results:** data is lost

<details>
  <summary>Logs</summary>

flutter run --verbose:
```
[  +20 ms] executing: [B:\src\flutter\] git -c log.showSignature=false log -n 1 --pretty=format:%H
[  +84 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[        ] f139b11009aeb8ed2a3a3aa8b0066e482709dde3
[        ] executing: [B:\src\flutter\] git describe --match v*.*.* --first-parent --long --tags
[  +94 ms] Exit code 0 from: git describe --match v*.*.* --first-parent --long --tags
[        ] v1.12.13+hotfix.9-0-gf139b1100
[   +7 ms] executing: [B:\src\flutter\] git rev-parse --abbrev-ref --symbolic @{u}
[  +89 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/stable
[        ] executing: [B:\src\flutter\] git ls-remote --get-url origin
[  +84 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[ +124 ms] executing: [B:\src\flutter\] git rev-parse --abbrev-ref HEAD
[  +93 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] stable
[ +129 ms] executing: B:\Android\android-sdk\platform-tools\adb.exe devices -l
[ +651 ms] Exit code 0 from: B:\Android\android-sdk\platform-tools\adb.exe devices -l
[   +1 ms] List of devices attached
           270cecbf10017ece       device product:crownltexx model:SM_N960F device:crownlte transport_id:3
           emulator-5554          device product:sdk_gphone_x86_arm model:AOSP_on_IA_Emulator device:generic_x86_arm transport_id:1
[  +31 ms] More than one device connected; please specify a device with the '-d <deviceId>' flag, or use '-d all' to act on all devices.
[   +5 ms] B:\Android\android-sdk\platform-tools\adb.exe -s 270cecbf10017ece shell getprop
[ +721 ms] ro.hardware = samsungexynos9810
[   +3 ms] B:\Android\android-sdk\platform-tools\adb.exe -s emulator-5554 shell getprop
[ +690 ms] ro.hardware = ranchu
[   +4 ms] SM N960F            • 270cecbf10017ece • android-arm64 • Android 10 (API 29)
[  +26 ms] AOSP on IA Emulator • emulator-5554    • android-x86   • Android 9 (API 28) (emulator)
[  +19 ms] "flutter run" took 2,372ms.

#0      throwToolExit (package:flutter_tools/src/base/common.dart:28:3)
#1      RunCommand.validateCommand (package:flutter_tools/src/commands/run.dart:289:7)
<asynchronous suspension>
#2      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:590:11)
#3      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:515:33)
<asynchronous suspension>
#4      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:146:29)
#5      _rootRun (dart:async/zone.dart:1126:13)
#6      _CustomZone.run (dart:async/zone.dart:1023:19)
#7      _runZoned (dart:async/zone.dart:1518:10)
#8      runZoned (dart:async/zone.dart:1465:12)
#9      AppContext.run (package:flutter_tools/src/base/context.dart:145:18)
#10     FlutterCommand.run (package:flutter_tools/src/runner/flutter_command.dart:505:20)
#11     CommandRunner.runCommand (package:args/command_runner.dart:197:27)
#12     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:413:21)
<asynchronous suspension>
#13     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:146:29)
#14     _rootRun (dart:async/zone.dart:1126:13)
#15     _CustomZone.run (dart:async/zone.dart:1023:19)
#16     _runZoned (dart:async/zone.dart:1518:10)
#17     runZoned (dart:async/zone.dart:1465:12)
#18     AppContext.run (package:flutter_tools/src/base/context.dart:145:18)
#19     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:364:19)
#20     CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:112:25)
#21     new Future.sync (dart:async/future.dart:224:31)
#22     CommandRunner.run (package:args/command_runner.dart:112:14)
#23     FlutterCommandRunner.run (package:flutter_tools/src/runner/flutter_command_runner.dart:250:18)
#24     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:63:22)
#25     _rootRun (dart:async/zone.dart:1126:13)
#26     _CustomZone.run (dart:async/zone.dart:1023:19)
#27     _runZoned (dart:async/zone.dart:1518:10)
#28     runZoned (dart:async/zone.dart:1502:12)
#29     run.<anonymous closure> (package:flutter_tools/runner.dart:61:18)
<asynchronous suspension>
#30     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:146:29)
#31     _rootRun (dart:async/zone.dart:1126:13)
#32     _CustomZone.run (dart:async/zone.dart:1023:19)
#33     _runZoned (dart:async/zone.dart:1518:10)
#34     runZoned (dart:async/zone.dart:1465:12)
#35     AppContext.run (package:flutter_tools/src/base/context.dart:145:18)
#36     runInContext (package:flutter_tools/src/context_runner.dart:64:24)
#37     run (package:flutter_tools/runner.dart:50:10)
#38     main (package:flutter_tools/executable.dart:65:9)
#39     main (file:///B:/src/flutter/packages/flutter_tools/bin/flutter_tools.dart:8:3)
#40     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:305:32)
#41     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:174:12)
```

`flutter analyze`:
```
No issues found! (ran in 3.3s)
```

`flutter doctor -v` :

```
[√] Flutter (Channel stable, v1.12.13+hotfix.9, on Microsoft Windows [Version 10.0.18363.778], locale en-US)
    • Flutter version 1.12.13+hotfix.9 at B:\src\flutter
    • Framework revision f139b11009 (4 weeks ago), 2020-03-30 13:57:30 -0700
    • Engine revision af51afceb8
    • Dart version 2.7.2

 
[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at B:\Android\android-sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • ANDROID_HOME = B:\Android\android-sdk
    • Java binary at: B:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)
    • All Android licenses accepted.

[√] Android Studio (version 3.6)
    • Android Studio at B:\Program Files\Android\Android Studio
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)

[√] VS Code (version 1.44.2)
    • VS Code at C:\Users\m_sha\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.9.1

[√] Connected device (2 available)
    • SM N960F            • 270cecbf10017ece • android-arm64 • Android 10 (API 29)
    • AOSP on IA Emulator • emulator-5554    • android-x86   • Android 9 (API 28) (emulator)

• No issues found!
```

</details>

----
I tested this on an old project but it doesn't have this issue, then I copied the android folder of this old project to the project with the issue , and that fixed it!
I think it's something related to the AndroidX upgrade.

I have uploded the repo to repoduce this issue, it has two branches, master (with the issue) and fixed (no issue):
https://github.com/mshwf/flutter_TextField_issue

**Comment by VladyslavBondarenko** [comment]
Hi @mshwf 
I checked and I have this result https://github.com/flutter/flutter/issues/51947#issuecomment-595108332 with `stable v1.12.13+hotfix.9`.
Are you experiencing this with current beta channel? https://github.com/flutter/flutter/issues/47628#issuecomment-618460501
https://github.com/flutter/flutter/issues/51947#issuecomment-604007683
Please follow up on https://github.com/flutter/flutter/issues/51947 and https://github.com/flutter/flutter/issues/47628 and comment there,
I'm closing the current one as duplicate.
If you disagree please write in the comments and I will reopen it.
Thank you
