### ISSUE TITLE
Color(0xFF818EA7).withOpacity(2) causes an error.

### ISSUE THREAD

**Issue by ThinkDigitalSoftware** [flutter/flutter#56092]
This doesn't run on my local machine, Codepen, or Dartpad

## Steps to Reproduce

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(
    MaterialApp(
      home: MyWidget(),
    ),
  );
}

class MyWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
        final Color grey = Color(0xFF818EA7).withOpacity(2);

    return Scaffold(
      body: Center(
        child: Container(
          color: grey,
          child:Text(
          'Build some widgets!',
          style: Theme.of(context).textTheme.headline4,
        )
        ),
      ),
    );
  }
}
```

**Expected results:** 
to get the color
**Actual results:** 
a crash
<details>
  <summary>Logs</summary>

```
The relevant error-causing widget was: 
  NewsCardMultiSummaryLayout2 file:///Users/thinkdigital/IdeaProjects/omega-app-maf/lib/ui/news_module/feed_tab/testing_feed_tab.dart:90:13
When the exception was thrown, this was the stack: 
#2      Color.withOpacity (dart:ui/painting.dart:188:12)
#3      NewsCardMultiSummaryLayout2.build (package:omegaappmf/ui/news_module/support/news_card/news_card_multi_summary.dart:200:42)
#4      StatelessElement.build (package:flutter/src/widgets/framework.dart:4291:28)
#5      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4223:15)
#6      Element.rebuild (package:flutter/src/widgets/framework.dart:3947:5)

```

```
```

```
Flutter 1.12.13+hotfix.9 • channel stable • https://github.com/flutter/flutter.git
Framework • revision f139b11009 (4 weeks ago) • 2020-03-30 13:57:30 -0700
Engine • revision af51afceb8
Tools • Dart 2.7.2

```

</details>

**Comment by jason-simmons** [comment]
Opacity values must be between 0 and 1

see https://api.flutter.dev/flutter/dart-ui/Color/withOpacity.html

**Comment by ThinkDigitalSoftware** [comment]
Oh oops. Oversight. That was supposed to be 0.2. Why didn't it just throw during the assertion?

**Comment by Anushi1998** [comment]
`assert` just runs in debug mode that's why.

**Comment by HansMuller** [comment]
The Color.withOpacity() does assert when its value is invalid:

https://api.flutter.dev/flutter/dart-ui/Color/withOpacity.html

**Comment by ThinkDigitalSoftware** [comment]
I was in debug mode, but it didn't throw an assertion error

**Comment by goderbauer** [comment]
When I run the code in debug mode it gives me this exception:

```
I/flutter ( 2708): ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
I/flutter ( 2708): The following assertion was thrown building MyWidget(dirty):
I/flutter ( 2708): 'dart:ui/painting.dart': Failed assertion: line 189: '<optimized out>': is not true.
I/flutter ( 2708):                                                      
I/flutter ( 2708): The relevant error-causing widget was:               
I/flutter ( 2708):   MyWidget file:///Users/goderbauer/dev/animated_size/lib/main.dart:6:13
I/flutter ( 2708):                                                      
I/flutter ( 2708): When the exception was thrown, this was the stack:   
I/flutter ( 2708): #2      Color.withOpacity (dart:ui/painting.dart:189:12)
I/flutter ( 2708): #3      MyWidget.build (package:animated_size/main.dart:14:42)
I/flutter ( 2708): #4      StatelessElement.build (package:flutter/src/widgets/framework.dart:4580:28)
I/flutter ( 2708): #5      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4506:15)
I/flutter ( 2708): #6      Element.rebuild (package:flutter/src/widgets/framework.dart:4222:5)
I/flutter ( 2708): #7      ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4485:5)
I/flutter ( 2708): #8      ComponentElement.mount (package:flutter/src/widgets/framework.dart:4480:5)
I/flutter ( 2708): ...     Normal element mounting (129 frames)         
I/flutter ( 2708): #137    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3450:14)
I/flutter ( 2708): #138    MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5951:32)
I/flutter ( 2708): ...     Normal element mounting (269 frames)         
I/flutter ( 2708): #407    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3450:14)
I/flutter ( 2708): #408    Element.updateChild (package:flutter/src/widgets/framework.dart:3218:18)
I/flutter ( 2708): #409    RenderObjectToWidgetElement._rebuild (package:flutter/src/widgets/binding.dart:1129:16)
I/flutter ( 2708): #410    RenderObjectToWidgetElement.mount (package:flutter/src/widgets/binding.dart:1100:5)
I/flutter ( 2708): #411    RenderObjectToWidgetAdapter.attachToRenderTree.<anonymous closure> (package:flutter/src/widgets/binding.dart:1042:17)
I/flutter ( 2708): #412    BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2607:19)
I/flutter ( 2708): #413    RenderObjectToWidgetAdapter.attachToRenderTree (package:flutter/src/widgets/binding.dart:1041:13)
I/flutter ( 2708): #414    WidgetsBinding.attachRootWidget (package:flutter/src/widgets/binding.dart:922:7)
I/flutter ( 2708): #415    WidgetsBinding.scheduleAttachRootWidget.<anonymous closure> (package:flutter/src/widgets/binding.dart:903:7)
I/flutter ( 2708): (elided 13 frames from class _AssertionError, class _RawReceivePortImpl, class _Timer, dart:async, and dart:async-patch)
I/flutter ( 2708):                                                      
I/flutter ( 2708): ════════════════════════════════════════════════════════════════════════════════════════════════════
```


The `'<optimized out>'` in the exception is obviously not great if you want to debug this.
@a-siva Any idea why dart is optimizing this out and not giving us the fill exception message?

**Comment by alexmarkov** [comment]
@goderbauer Related issues: https://github.com/dart-lang/sdk/issues/34586 and https://github.com/dart-lang/sdk/issues/35426.

**Comment by goderbauer** [comment]
Cool, looks like this is tracked in the dart sdk. I am closing this issue here.
