### ISSUE TITLE
[tool_crash] FileSystemException: Cannot open file, OS Error: The system cannot find the file specified., errno = 2

### ISSUE THREAD

**Issue by deepak9166** [flutter/flutter#56105]
## Command
```
flutter --no-color run --machine --track-widget-creation --device-id=web-server lib\main.dart
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
FileSystemException: Cannot open file, OS Error: The system cannot find the file specified.
, errno = 2
```
#0      _File.open.<anonymous closure> (dart:io/file_impl.dart:366:9)
#1      _rootRunUnary (dart:async/zone.dart:1192:38)
#2      _CustomZone.runUnary (dart:async/zone.dart:1085:19)
#3      _FutureListener.handleValue (dart:async/future_impl.dart:141:18)
#4      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:682:45)
#5      Future._propagateToListeners (dart:async/future_impl.dart:711:32)
#6      Future._completeWithValue (dart:async/future_impl.dart:526:5)
#7      Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:556:7)
#8      _rootRun (dart:async/zone.dart:1184:13)
#9      _CustomZone.run (dart:async/zone.dart:1077:19)
#10     _CustomZone.runGuarded (dart:async/zone.dart:979:7)
#11     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1019:23)
#12     _microtaskLoop (dart:async/schedule_microtask.dart:43:21)
#13     _startMicrotaskLoop (dart:async/schedule_microtask.dart:52:5)
#14     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
#15     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:169:5)
```
```
[✓] Flutter (Channel master, v1.18.0-8.0.pre, on Microsoft Windows [Version 10.0.16299.15], locale en-US)
    • Flutter version 1.18.0-8.0.pre at C:\flutter
    • Framework revision e0c63cd35e (7 days ago), 2020-04-23 22:29:01 -0400
    • Engine revision d2ec21221e
    • Dart version 2.9.0 (build 2.9.0-3.0.dev b0d35855d8)

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at C:\Users\deepak\AppData\Local\Android\sdk
    • Platform android-29, build-tools 29.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[✓] Visual Studio - develop for Windows (Visual Studio Community 2019 16.5.4)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.5.30011.22

[✓] Android Studio (version 3.6)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)

[✓] VS Code (version 1.44.2)
    • VS Code at C:\Users\deepak\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.9.1

[✓] Connected device (4 available)
    • Redmi Note 4 • 5a26cc9e0104 • android-arm64  • Android 7.0 (API 24)
    • Windows      • Windows      • windows-x64    • Microsoft Windows [Version 10.0.16299.15]
    • Web Server   • web-server   • web-javascript • Flutter Tools
    • Chrome       • chrome       • web-javascript • Google Chrome 81.0.4044.129

• No issues found!

```

## Flutter Application Metadata
**Type**: app
**Version**: 1.0.0+1
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: master
**Creation framework version**: 6dc3bfaa98e13c0f174e0cc229e7b43678d4d0c0
### Plugins
fluttertoast-3.1.3
path_provider-0.5.0+1
permission_handler-3.3.0
shared_preferences-0.5.7
shared_preferences_macos-0.0.1+6
shared_preferences_web-0.1.2+4
sqflite-1.3.0
url_launcher-5.4.2
url_launcher_macos-0.0.1+4
url_launcher_web-0.1.1+1

**Comment by deepak9166** [comment]
After the updates SDK of flutter windows application not working proper on other system, showing error like: missing dll file. my own system on working proper. where i try to install application another application then showing these type error.

**Comment by iapicca** [comment]
Hi @deepak9166 
I see there's an open [issue](https://github.com/flutter/flutter/issues/46230) addressing the case you described.
Please follow up on that issue,
I'm closing the current one as duplicate.
If you disagree please write in the comments
and I will reopen it.
Thank you

**Comment by iapicca** [comment]
Hi @deepak9166 
can you please provide your `full flutter run --verbose` 
and your `pubspec.yaml` 
or if possible a reproducible minimal code sample.
Thank you

**Comment by iapicca** [comment]
Hi @deepak9166 
I see there's an open [issue](https://github.com/flutter/flutter/issues/54704) addressing the case you described.
Please follow up on that issue,
I'm closing the current one as duplicate.
If you disagree please write in the comments
and I will reopen it.
Thank you
