### ISSUE TITLE
Issues with debugging macOS: Could not start Observatory HTTP server

### ISSUE THREAD

**Issue by flowhorn** [flutter/flutter#56227]
In the current master versions, debugging a macOS application has issues. It compiles and starts the app, but hot reload/hot restart and receiving debug messages are no longer possible. In VS Code the debug panel stays at 'Building macOS application'.

I get this error message:
```
flutter: Observatory server failed to start after 11 tries
flutter: Could not start Observatory HTTP server:
SocketException: Failed to create server socket (OS Error: Operation not permitted, errno = 1), address = 127.0.0.1, port = 0
#0      _NativeSocket.bind  (dart:io-patch/socket_patch.dart:753:7)
<asynchronous suspension>
#1      _RawServerSocket.bind  (dart:io-patch/socket_patch.dart:1411:26)
#2      _ServerSocket.bind  (dart:io-patch/socket_patch.dart:1693:29)
#3      ServerSocket._bind  (dart:io-patch/socket_patch.dart:1684:26)
#4      ServerSocket.bind  (dart:io/socket.dart:388:27)
#5      _HttpServer.bind  (dart:_http/http_impl.dart:2732:25)
#6      HttpServer.bind (dart:_http:230:19)
#7      Server.startup.poll  (dart:vmservice_io/vmservice_server.dart:419:36)
<asynchronous suspension>
#8      Server.startup.poll (dart:vmservice_io/vmservice_server.dart)
#9      Server.startup  (dart:vmservice_io/vmservice_server.dart:431:23)
<asynchronous suspension>
#10     main (dart:vmservice_io:266:12)
```

Here is my flutter doctor -v output:

```
[✓] Flutter (Channel master, 1.18.0-9.0.pre.97, on Mac OS X 10.15.4 19E287, locale de-DE)
    • Flutter version 1.18.0-9.0.pre.97 at /Users/user1/Development/flutter
    • Framework revision 6b20a28f9e (2 hours ago), 2020-05-03 01:14:01 -0400
    • Engine revision 813fd04c7d
    • Dart version 2.9.0 (build 2.9.0-5.0.dev c3ce873556)

[✓] Xcode - develop for iOS and macOS (Xcode 11.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.4.1, Build version 11E503a
    • CocoaPods version 1.9.1

[✓] VS Code (version 1.44.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.10.0

 
[✓] Connected device (3 available)            
    • macOS      • macOS      • darwin-x64     • Mac OS X 10.15.4 19E287
    • Web Server • web-server • web-javascript • Flutter Tools
    • Chrome     • chrome     • web-javascript • Google Chrome 81.0.4044.129

• No issues found!
```

**Comment by TahaTesser** [comment]
Hi @flowhorn 
I tried to reproduce this on latest `master` in debug mode with hot reload/hot restart in VSC and found no such issue 

<details> 
<summary>flutter doctor -v</summary> 

``` 
[✓] Flutter (Channel master, 1.18.0-9.0.pre.101, on Mac OS X 10.15.4 19E287,
    locale en-GB)
    • Flutter version 1.18.0-9.0.pre.101 at /Users/taha/Code/flutter_master
    • Framework revision 17bbc2a235 (10 hours ago), 2020-05-03 17:34:02 -0400
    • Engine revision 906bf59684
    • Dart version 2.9.0 (build 2.9.0-5.0.dev c3ce873556)

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/taha/Code/sdk
    • Platform android-29, build-tools 29.0.3
    • ANDROID_HOME = /Users/taha/Code/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.4.1, Build version 11E503a
    • CocoaPods version 1.9.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build
      1.8.0_212-release-1586-b4-5784211)

[✓] VS Code (version 1.44.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.10.1

 
[✓] Connected device (5 available)            
    • SM M305F            • 32003c30dc19668f • android-arm64  • Android 10 (API
      29)
    • AOSP on IA Emulator • emulator-5554    • android-x86    • Android 9 (API
      28) (emulator)
    • macOS               • macOS            • darwin-x64     • Mac OS X 10.15.4
      19E287
    • Web Server          • web-server       • web-javascript • Flutter Tools
    • Chrome              • chrome           • web-javascript • Google Chrome
      81.0.4044.129

• No issues found!
``` 

and also not reproducible in terminal
```
Flutter run key commands.
r Hot reload. 🔥🔥🔥
R Hot restart.
h Repeat this help message.
d Detach (terminate "flutter run" but leave application running).
c Clear the screen
q Quit (terminate the application on the device).
An Observatory debugger and profiler on macOS is available at: http://127.0.0.1:56241/I5DZLrwtw-A=/

Performing hot reload...                                                
Reloaded 0 of 499 libraries in 96ms.

Performing hot reload...                                                
Reloaded 0 of 499 libraries in 55ms.

Performing hot reload...                                                
Reloaded 1 of 499 libraries in 150ms.

```


</details> 

Can you please try it on latest `master`?
Thank you

**Comment by stuartmorgan** [comment]
> Failed to create server socket (OS Error: Operation not permitted, errno = 1)

Have you changed your entitlements file? This sounds like you don't have the server entitlement.

**Comment by flowhorn** [comment]
Thank you @stuartmorgan, this fixed it for me. The Server Network Entitlement was disabled and enableing for debug fixed this. So I guess it wasn't related to any master changes and I close this issue.
