### ISSUE TITLE
Multiple widgets used the same GlobalKey error thrown when sharing a single widget for multiple class compositions

### ISSUE THREAD

**Issue by JheiKrauzer0613** [flutter/flutter#56246]
I have this error shown in the runtime logs whenever I tried to rebuild my app for any changes I made in the Container widget that holds all the UI widget components,  after the primary run.

I made a flutter app that has 4 different layouts which will be shown based on the user's current device and orientation. Each layout has its own class composition (mobilePortrait / mobileLandscape/ tabletPortrait / tabletLandscape). 

I made a single dart file that will store all the UI widget components (TextField, Button, etc) for a particular form that currently displayed. These widgets were meant to be Global and were shared with 4 different layouts.

I made also a single dart file that will store all the GlobalKeys inside a class that can be accessed by a particular Form widget in a layout.

GlobalKeys.dart

```dart
class AppKeys {
  static List<GlobalKey<FormState>> formLoginKeys = [GlobalKey<FormState>(), GlobalKey<FormState>(), GlobalKey<FormState>(), GlobalKey<FormState>()];
  static final GlobalKey<FormFieldState> txtEmailKey = GlobalKey<FormFieldState>();
}
```

ComponentsUI.dart

```dart
class TextEmail extends StatefulWidget {
  TextEmail({Key key}):super(key: key);

  TextEmailState createState() => TextEmailState();
}

class TextEmailState extends State<TextEmail> {

  TextEditingController tcEmail;

  void initState() {
    tcEmail = new TextEditingController();
    super.initState();
  }

  void dispose() {
    tcEmail.clearComposing();
    tcEmail.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {

    return new TextFormField(
      controller: tcEmail,
      maxLength: 30,
      keyboardType: TextInputType.emailAddress,
      autovalidate: GlobalVar.autoValidate,
      style: AppTextStyle.defaultTextStyle(context),
      decoration: new InputDecoration(
        counterText: '',
        hintText: 'email address',
        hintStyle: AppTextStyle.defaultHintStyle(context),
        errorStyle: AppErrorStyle.defaultErrorStyle(context),
        prefixIcon: new Icon(Icons.account_box),
      ),
      validator: (String emailValidator) {

        RegExp regexEmail = new RegExp(RegExPattern.emailRegEx);

          if(!regexEmail.hasMatch(emailValidator) && emailValidator.isNotEmpty) {
              return 'Invalid email address format';
          }

          if(emailValidator.isEmpty) {
              return 'Email address is required';
          }

            return null;
      },
      onSaved: (emailValidator) => GlobalVar.accEmail = emailValidator,
    );
  }
}
```

mobilePortrait.dart

```dart
class LoginMobilePortrait extends StatefulWidget {
  LoginMobilePortraitState createState() => LoginMobilePortraitState();
}

class LoginMobilePortraitState extends State<LoginMobilePortrait> {

  @override
  Widget build(BuildContext context) {
    return new Scaffold(
      body: new SafeArea(
        child: new Form(
          key: AppKeys.formLoginKeys[0],
          child: new LayoutBuilder(
              builder: (context, constraintLoginPortrait) {
                return new SingleChildScrollView(
                  child: new ConstrainedBox(
                    constraints: BoxConstraints(minHeight: constraintLoginPortrait.maxHeight),
                    child: new Column(
                      children: [
                        new Container(
                          margin: AppMargin.bottomMargin(context),
                          color: AppFontColor.lightBlueAccentColor,
                          height: (MediaQuery.of(context).size.height / 100) * 38.0,
                        ),
                        new Container(
                          padding: AppPadding.defaultPadding(context),
                          child: new Column(
                            children: [
                              new Container(
                                margin: AppMargin.bottomMargin(context),
                                child: TextEmail(key: AppKeys.txtEmailKey)
                              ),
                            ],
                          ),
                        ),
                      ],
                    ),
                  ),
                );
              }
          ),
        ),
      ),
    );
  }
}
```

tabletLandscape.dart

```dart
class LoginTabletLandscape extends StatefulWidget {
  LoginTabletLandscapeState createState() => LoginTabletLandscapeState();
}

class LoginTabletLandscapeState extends State<LoginTabletLandscape> {

  @override
  Widget build(BuildContext context) {
    return new Scaffold(
      body: new SafeArea(
        child: new Form(
          key: AppKeys.formLoginKeys[3],
          child: new LayoutBuilder(
            builder: (context, constraint) {
              return new ConstrainedBox(constraints: BoxConstraints(minHeight: constraint.maxHeight),
                child: new Row(
                  children: [
                    new Container(
                      constraints: BoxConstraints(minHeight: constraint.maxHeight),
                      width: (MediaQuery.of(context).size.width / 100) * 45.0,
                      color: Colors.amberAccent,
                    ),
                    new Expanded(
                      child: new SingleChildScrollView(
                        child: new Container(
                          alignment: Alignment.center,
                          constraints: BoxConstraints(minHeight: constraint.maxHeight),
                          padding: AppPadding.defaultPadding(context),
                          child: new Column(
                            children: [
                              new Container(
                                  child: TextEmail(key: AppKeys.txtEmailKey)
                              ),
                            ],
                          ),
                        ),
                      ),
                    ),
                  ],
                ),
              );
            },
          ),
        ),
      ),
    );
  }
}
```

runtime error logs (after rebuild / hot-reload):

```bash
Performing hot reload...
Syncing files to device ASUS X00TDB...

════════ Exception caught by widgets library ═══════════════════════════════════════════════════════
The following assertion was thrown while finalizing the widget tree:
Multiple widgets used the same GlobalKey.

The key [LabeledGlobalKey<FormFieldState<dynamic>>#1cf8e] was used by multiple widgets. The parents of those widgets were different widgets that both had the following description:
  Container
A GlobalKey can only be specified on one widget at a time in the widget tree.
When the exception was thrown, this was the stack: 
#0      GlobalKey._debugVerifyGlobalKeyReservation.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:flutter/src/widgets/framework.dart:246:13)
#1      _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:377:8)
#2      GlobalKey._debugVerifyGlobalKeyReservation.<anonymous closure>.<anonymous closure> (package:flutter/src/widgets/framework.dart:193:19)
#3      _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:377:8)
#4      GlobalKey._debugVerifyGlobalKeyReservation.<anonymous closure> (package:flutter/src/widgets/framework.dart:189:26)
...
════════════════════════════════════════════════════════════════════════════════════════════════════
Reloaded 4 of 517 libraries in 1,173ms.

════════ Exception caught by widgets library ═══════════════════════════════════════════════════════
The following assertion was thrown while finalizing the widget tree:
Multiple widgets used the same GlobalKey.

The key [LabeledGlobalKey<FormFieldState<dynamic>>#1cf8e] was used by multiple widgets. The parents of those widgets were different widgets that both had the following description:
  Container
A GlobalKey can only be specified on one widget at a time in the widget tree.
When the exception was thrown, this was the stack: 
#0      GlobalKey._debugVerifyGlobalKeyReservation.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:flutter/src/widgets/framework.dart:246:13)
#1      _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:377:8)
#2      GlobalKey._debugVerifyGlobalKeyReservation.<anonymous closure>.<anonymous closure> (package:flutter/src/widgets/framework.dart:193:19)
#3      _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:377:8)
#4      GlobalKey._debugVerifyGlobalKeyReservation.<anonymous closure> (package:flutter/src/widgets/framework.dart:189:26)
...
════════════════════════════════════════════════════════════════════════════════════════════════════
```

**Comment by iapicca** [comment]
Hi @JheiKrauzer0613 
can you please provide your `flutter doctor -v` ,
the error you are reporting might be caused
by your implementation rather than flutter itself;

you code sample doesn't appear to be complete

```dart
class AppKeys {
  static final GlobalKey<FormFieldState> txtEmailKey = GlobalKey<FormFieldState>();
}
...
 AppKeys.formLoginKeys[0],
```

Could you please provide a minimal and reproducible code sample
Thank you

**Comment by JheiKrauzer0613** [comment]
Hi, @iapicca  thanks for your reply. I already added the List<GlobalKey> in the AppKeys.dart code snippet. These List of GlobalKeys were intended for the Form widgets for each layout I created.

There's an update in the master channel I am using and updated it. After the update, I run flutter doctor -v and have this new issue.

Microsoft Windows [Version 10.0.18363.778]
(c) 2019 Microsoft Corporation. All rights reserved.

C:\src\projects\playmaia>flutter doctor -v
[√] Flutter (Channel master, 1.18.0-9.0.pre.98, on Microsoft Windows [Version 10.0.18363.778], locale en-US)
    • Flutter version 1.18.0-9.0.pre.98 at C:\src\flutter
    • Framework revision a32c8e84bd (26 hours ago), 2020-05-03 05:54:01 -0400
    • Engine revision e3cb6812ed
    • Dart version 2.9.0 (build 2.9.0-5.0.dev c3ce873556)

[!] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at C:\Users\jhers\AppData\Local\Android\sdk
    • Platform android-29, build-tools 29.0.2
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)
    X Android license status unknown.
      Try re-installing or updating your Android SDK Manager.
      See https://developer.android.com/studio/#downloads or visit visit https://flutter.dev/docs/get-started/install/windows#android-setup for detailed instructions.

[√] Android Studio (version 3.6)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)

[√] VS Code (version 1.44.2)
    • VS Code at C:\Users\jhers\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.9.1

[!] Connected device
    ! No devices available

! Doctor found issues in 2 categories.


It looks like the  Android license status is unknown. I tried to google any possible fix for this but to no avail. I also checked other tickets here in GitHub about this Android license error but nothing helped me. The SDK Tools (obsolete) is not existing in my Android Studio IDE even though I ticked the Hide Obsolete Packages to off.

**Comment by TahaTesser** [comment]
Hi @JheiKrauzer0613 
Can you please remove `static` from both lines  and only keep `final`  from here and try the app again
```
  static List<GlobalKey<FormState>> formLoginKeys = [GlobalKey<FormState>(), GlobalKey<FormState>(), GlobalKey<FormState>(), GlobalKey<FormState>()];
  static final GlobalKey<FormFieldState> txtEmailKey = GlobalKey<FormFieldState>(
```

Please license issue, please check this [solution](https://github.com/flutter/flutter/issues/51712#issuecomment-593721423) and download it manually too 
Thank you

**Comment by JheiKrauzer0613** [comment]
Hi @TahaTesser, I tried the one you were instructed in the GlobalKeys (_removing the static and keep the final_) but it shows a red line error under txtPassKey and txtEmailKey. When hovering, it shows "_Instance members can't be accessed using static access_"

In regards to the android license issue, I think I can fix that later using the solution you shared.

**Comment by TahaTesser** [comment]
Hi @JheiKrauzer0613 
You need to put keys in your stateful  class
Look at this example
```
class MyCustomFormState extends State<MyCustomForm> {
  // Create a global key that uniquely identifies the Form widget
  // and allows validation of the form.
  //
  // Note: This is a GlobalKey<FormState>,
  // not a GlobalKey<MyCustomFormState>.
  final _formKey = GlobalKey<FormState>();

  @override
  Widget build(BuildContext context) {
    // Build a Form widget using the _formKey created above.
    return Form(
      key: _formKey,

```

Thank you

**Comment by JheiKrauzer0613** [comment]
Hi @TahaTesser , thank you for your response. I already tried to refactor my code and change my implementation so that the problem would go. The only problem now is the android license. Some solutions I read needed to downgrade my JDK version for this to go away? Not so sure but maybe worth trying? I will close this ticket now. Thanks again!
