### ISSUE TITLE
Failed assertion:  '!_debugLocked': is not true

### ISSUE THREAD

**Issue by waar19** [flutter/flutter#56316]
```
[  +39 ms] I/flutter ( 3805): Admin id
[   +2 ms] I/flutter ( 3805): 5890df66e8fa120cf0991ae9
[  +16 ms] I/flutter ( 3805): Prefs _id 5890df66e8fa120cf0991ae9
[  +34 ms] I/flutter ( 3805): 'package:flutter/src/widgets/navigator.dart': Failed assertion: line 3372 pos 12:
'_history.any(_RouteEntry.isPresentPredicate)': Navigator has no active routes to replace.
[  +21 ms] E/flutter ( 3805): [ERROR:flutter/lib/ui/ui_dart_state.cc(166)] Unhandled Exception: 'package:flutter/src/widgets/navigator.dart': Failed
assertion: line 3289 pos 12: '!_debugLocked': is not true.
[  +33 ms] E/flutter ( 3805): #0      _AssertionError._doThrowNew (dart:core-patch/errors_patch.dart:42:39)
[   +4 ms] E/flutter ( 3805): #1      _AssertionError._throwNew (dart:core-patch/errors_patch.dart:38:5)
[  +63 ms] E/flutter ( 3805): #2      NavigatorState.push (package:flutter/src/widgets/navigator.dart:3289:12)
[  +31 ms] E/flutter ( 3805): #3      showGeneralDialog (package:flutter/src/widgets/routes.dart:1767:65)
[  +46 ms] E/flutter ( 3805): #4      Alert.show (package:rflutter_alert/src/alert.dart:47:18)
[  +80 ms] E/flutter ( 3805): #5      _LoginPageState._showAlert (package:reader_app/src/pages/login_page.dart:313:13)
[  +34 ms] E/flutter ( 3805): #6      _LoginPageState._login (package:reader_app/src/pages/login_page.dart:204:7)
[  +46 ms] E/flutter ( 3805): #7      _rootRunUnary (dart:async/zone.dart:1192:38)
[   +2 ms] E/flutter ( 3805): #8      _CustomZone.runUnary (dart:async/zone.dart:1085:19)
[   +5 ms] E/flutter ( 3805): #9      _FutureListener.handleValue (dart:async/future_impl.dart:141:18)
[        ] E/flutter ( 3805): #10     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:686:45)
[   +1 ms] E/flutter ( 3805): #11     Future._propagateToListeners (dart:async/future_impl.dart:715:32)
[  +24 ms] E/flutter ( 3805): #12     Future._completeWithValue (dart:async/future_impl.dart:526:5)
[   +1 ms] E/flutter ( 3805): #13     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:36:15)
[   +2 ms] E/flutter ( 3805): #14     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:303:13)
[        ] E/flutter ( 3805): #15     AdminBloc.login (package:reader_app/src/bloc/admin_bloc.dart)
[        ] E/flutter ( 3805): #16     _rootRunUnary (dart:async/zone.dart:1192:38)
[        ] E/flutter ( 3805): #17     _CustomZone.runUnary (dart:async/zone.dart:1085:19)
[        ] E/flutter ( 3805): #18     _FutureListener.handleValue (dart:async/future_impl.dart:141:18)
[        ] E/flutter ( 3805): #19     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:686:45)
[  +24 ms] E/flutter ( 3805): #20     Future._propagateToListeners (dart:async/future_impl.dart:715:32)
[   +3 ms] E/flutter ( 3805): #21     Future._completeWithValue (dart:async/future_impl.dart:526:5)
[   +1 ms] E/flutter ( 3805): #22     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:36:15)
[   +1 ms] E/flutter ( 3805): #23     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:303:13)
[        ] E/flutter ( 3805): #24     AdminProvider.login (package:reader_app/src/providers/admin_provider.dart)
[        ] E/flutter ( 3805): #25     _rootRunUnary (dart:async/zone.dart:1192:38)
[        ] E/flutter ( 3805): #26     _CustomZone.runUnary (dart:async/zone.dart:1085:19)
[  +28 ms] E/flutter ( 3805): #27     _FutureListener.handleValue (dart:async/future_impl.dart:141:18)
[        ] E/flutter ( 3805): #28     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:686:45)
[        ] E/flutter ( 3805): #29     Future._propagateToListeners (dart:async/future_impl.dart:715:32)
[   +1 ms] E/flutter ( 3805): #30     Future._completeWithValue (dart:async/future_impl.dart:526:5)
[        ] E/flutter ( 3805): #31     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:36:15)
[        ] E/flutter ( 3805): #32     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:303:13)
[        ] E/flutter ( 3805): #33     _withClient (package:http/http.dart)
[  +27 ms] E/flutter ( 3805): #34     _rootRunUnary (dart:async/zone.dart:1192:38)
[   +1 ms] E/flutter ( 3805): #35     _CustomZone.runUnary (dart:async/zone.dart:1085:19)
[   +1 ms] E/flutter ( 3805): #36     _FutureListener.handleValue (dart:async/future_impl.dart:141:18)
[        ] E/flutter ( 3805): #37     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:686:45)
[        ] E/flutter ( 3805): #38     Future._propagateToListeners (dart:async/future_impl.dart:715:32)
[        ] E/flutter ( 3805): #39     Future._completeWithValue (dart:async/future_impl.dart:526:5)
[        ] E/flutter ( 3805): #40     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:36:15)
[        ] E/flutter ( 3805): #41     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:303:13)
[   +1 ms] E/flutter ( 3805): #42     Response.fromStream (package:http/src/response.dart)
[  +28 ms] E/flutter ( 3805): #43     _rootRunUnary (dart:async/zone.dart:1192:38)
[   +2 ms] E/flutter ( 3805): #44     _CustomZone.runUnary (dart:async/zone.dart:1085:19)
[   +1 ms] E/flutter ( 3805): #45     _FutureListener.handleValue (dart:async/future_impl.dart:141:18)
[        ] E/flutter ( 3805): #46     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:686:45)
[   +3 ms] E/flutter ( 3805): #47     Future._propagateToListeners (dart:async/future_impl.dart:715:32)
[  +24 ms] E/flutter ( 3805): #48     Future._completeWithValue (dart:async/future_impl.dart:526:5)
[        ] E/flutter ( 3805): #49     Future._asyncCompleteWithValue.<anonymous closure> (dart:async/future_impl.dart:560:7)
[   +1 ms] E/flutter ( 3805): #50     _rootRun (dart:async/zone.dart:1184:13)
[        ] E/flutter ( 3805): #51     _CustomZone.run (dart:async/zone.dart:1077:19)
[        ] E/flutter ( 3805): #52     _CustomZone.runGuarded (dart:async/zone.dart:979:7)
[        ] E/flutter ( 3805): #53     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.da
[  +31 ms] I/flutter ( 3805): ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
[   +1 ms] I/flutter ( 3805): The following assertion was thrown building Navigator-[GlobalObjectKey<NavigatorState>
[  +34 ms] I/flutter ( 3805): _WidgetsAppState#dbf63](dirty, state: NavigatorState#6a09c(tickers: tracking 2 tickers)):
[   +4 ms] I/flutter ( 3805): 'package:flutter/src/widgets/navigator.dart': Failed assertion: line 3803 pos 12: '!_debugLocked':
[  +38 ms] I/flutter ( 3805): is not true.
[   +1 ms] I/flutter ( 3805): 
[        ] I/flutter ( 3805): Either the assertion indicates an error in the framework itself, or we should provide substantially
[        ] I/flutter ( 3805): more information in this error message to help you determine and fix the underlying cause.
[        ] I/flutter ( 3805): In either case, please report this assertion by filing a bug on GitHub:
[        ] I/flutter ( 3805):   https://github.com/flutter/flutter/issues/new?template=BUG.md
[        ] I/flutter ( 3805): 
[        ] I/flutter ( 3805): The relevant error-causing widget was:
[        ] I/flutter ( 3805):   MaterialApp file:///D:/Desarrollo/Vueltap/Flutter/reader_app/lib/main.dart:21:16
[  +26 ms] I/flutter ( 3805): 
[   +1 ms] I/flutter ( 3805): When the exception was thrown, this was the stack:
[        ] I/flutter ( 3805): #2      NavigatorState.build (package:flutter/src/widgets/navigator.dart:3803:12)
[   +1 ms] I/flutter ( 3805): #3      StatefulElement.build (package:flutter/src/widgets/framework.dart:4623:28)
[   +1 ms] I/flutter ( 3805): #4      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4506:15)
[        ] I/flutter ( 3805): #5      StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4679:11)
[        ] I/flutter ( 3805): #6      Element.rebuild (package:flutter/src/widgets/framework.dart:4222:5)
[        ] I/flutter ( 3805): #7      BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2627:33)
[  +25 ms] I/flutter ( 3805): #8      WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:864:20)
[   +2 ms] I/flutter ( 3805): #9      RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:284:5)
[   +1 ms] I/flutter ( 3805): #10     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1074:15)
[   +1 ms] I/flutter ( 3805): #11     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1013:9)
[        ] I/flutter ( 3805): #12     SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:929:5)
[        ] I/flutter ( 3805): #16     _invoke (dart:ui/hooks.dart:277:10)
[        ] I/flutter ( 3805): #17     _drawFrame (dart:ui/hooks.dart:235:3)
[        ] I/flutter ( 3805): (elided 5 frames from class _AssertionError and dart:async)
[        ] I/flutter ( 3805):
[  +44 ms] I/flutter ( 3805): ══════════════════════════════════════════════════════════════════════════
```

**Comment by VladyslavBondarenko** [comment]
Hi @waar19 
see https://github.com/flutter/flutter/issues/49779, https://github.com/flutter/flutter/issues/36177, this may be a cause https://github.com/flutter/flutter/issues/16602#issuecomment-407916243.
Please comment on the existing issues if your case is different form described in them.
Closing as duplicate.
if you disagree please write in the comments and I will reopen it
