### ISSUE TITLE
flutter_attach_test_android fails Bad state: No element at HotRunner._reloadSources > List.first

### ISSUE THREAD

**Issue by jmagman** [flutter/flutter#56322]
flutter_attach_test_android was [marked flaky](https://github.com/flutter/flutter/issues/55875), but as of https://github.com/flutter/flutter/commit/ffcf1db3ca74563910986a4a2f3675728d17c5ca is failing 100% with a different error.  It should be investigated separately from the flaky timeout:

```
2020-04-27T19:35:19.838865: attach:stdout: Performing hot reload...                                        
2020-04-27T19:35:19.842611: run:stderr: Bad state: No element
run:stderr: #0      List.first (dart:core-patch/array.dart:205:5)
2020-04-27T19:35:19.842809: run:stderr: #1      HotRunner._reloadSources.<anonymous closure> (package:flutter_tools/src/run_hot.dart:857:65)
run:stderr: #2      _rootRunUnary (dart:async/zone.dart:1192:38)
run:stderr: #3      _CustomZone.runUnary (dart:async/zone.dart:1085:19)
run:stderr: #4      _FutureListener.handleValue (dart:async/future_impl.dart:141:18)
run:stderr: #5      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:686:45)
run:stderr: #6      Future._propagateToListeners (dart:async/future_impl.dart:715:32)
run:stderr: #7      Future._completeWithValue (dart:async/future_impl.dart:526:5)
run:stderr: #8      Future._asyncCompleteWithValue.<anonymous closure> (dart:async/future_impl.dart:560:7)
run:stderr: #9      _rootRun (dart:async/zone.dart:1184:13)
run:stderr: #10     _CustomZone.run (dart:async/zone.dart:1077:19)
2020-04-27T19:35:19.842945: run:stderr: #11     _CustomZone.runGuarded (dart:async/zone.dart:979:7)
run:stderr: #12     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1019:23)
run:stderr: #13     _microtaskLoop (dart:async/schedule_microtask.dart:43:21)
run:stderr: #14     _startMicrotaskLoop (dart:async/schedule_microtask.dart:52:5)
run:stderr: #15     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
run:stderr: #16     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:169:5)
```

[flutter_attach_test_android_ffcf1db_4.log](https://github.com/flutter/flutter/files/4576912/flutter_attach_test_android_ffcf1db_4.log)

**Comment by jmagman** [comment]
Went from flaky:
<img width="76" alt="Screen Shot 2020-05-04 at 12 25 45 PM" src="https://user-images.githubusercontent.com/682784/81005221-727b8d80-8e02-11ea-8fda-4f2ef3dae2c8.png">
To all failures:
<img width="36" alt="Screen Shot 2020-05-04 at 12 26 00 PM" src="https://user-images.githubusercontent.com/682784/81005248-7d362280-8e02-11ea-9e33-529bc01e9d62.png">
