### ISSUE TITLE
Unhandled Exception: Invalid argument(s): Failed to load dynamic library (126)

### ISSUE THREAD

**Issue by jesseframework** [flutter/flutter#56351]
```
Launching lib\main.dart on Windows in debug mode...
[ERROR:flutter/lib/ui/ui_dart_state.cc(166)] Unhandled Exception: Invalid argument(s): Failed to load dynamic library (126)
#0      _open  (dart:ffi-patch/ffi_dynamic_library_patch.dart:13:55)
#1      new DynamicLibrary.open  (dart:ffi-patch/ffi_dynamic_library_patch.dart:22:12)
#2      _defaultOpen 
package:moor_ffi/src/load_library.dart:34
#3      OpenDynamicLibrary.openSqlite 
package:moor_ffi/src/load_library.dart:80
#4      new _SQLiteBindings 
package:moor_ffi/…/bindings/bindings.dart:92
#5      bindings 
package:moor_ffi/…/bindings/bindings.dart:184
#6      new Database.open 
package:moor_ffi/…/impl/database.dart:40
#7      new Database.openFile 
package:moor_ffi/…/impl/database.dart:29
#8      _VmDelegate.open 
package:moor_ffi/src/vm_database.dart:39
#9      DelegatedDatabase.ensureOpen.<anonymous closure> 
package:moor/…/helpers/engines.dart:246
<asynchronous suspension>
#10     DelegatedDatabase.ensureOpen.<anonymous closure> (package:moor/src/runtime/executor/helpers/engines.dart)
#11     BasicLock.synchronized 
package:synchronized/src/basic_lock.dart:32
#12     DelegatedDatabase.ensureOpen 
package:moor/…/helpers/engines.dart:238
#13     QueryExecutor.doWhenOpened 
package:moor/…/executor/executor.dart:29
#14     SimpleSelectStatement._getWithQuery 
package:moor/…/select/select.dart:39
#15     SimpleSelectStatement.get 
package:moor/…/select/select.dart:35
#16     CommunicationDao.getCommunicationDataByType 
package:j3enterprise/…/communication/communication_setup_crud.dart:17
#17     initServices 
package:j3enterprise/…/services/init_services.dart:19
#18     main 
package:j3enterprise/main.dart:30
#19     _runMainZoned.<anonymous closure>.<anonymous closure>  (dart:ui/hooks.dart:257:25)
#20     _rootRun  (dart:async/zone.dart:1184:13)
#21     _CustomZone.run  (dart:async/zone.dart:1077:19)
#22     _runZoned  (dart:async/zone.dart:1619:10)
#23     runZonedGuarded  (dart:async/zone.dart:1608:12)
#24     _runMainZoned.<anonymous closure>  (dart:ui/hooks.dart:249:5)
#25     _startIsolate.<anonymous closure>  (dart:isolate-patch/isolate_patch.dart:301:19)
#26     _RawReceivePortImpl._handleMessage  (dart:isolate-patch/isolate_patch.dart:168:12)
```

## Steps to Reproduce

1. Run `flutter create bug`.
2. Update the files as follows: ... 
3. ... 

**Expected results:** 

**Actual results:** 

<details>
  <summary>Logs</summary>

```
```

```
```

```
```

</details>

**Comment by jesseframework** [comment]
Can anyone tell me when to put the sqlite3 dll file on windows for windows to work. Am using the moor lib for sqlite on windows.

**Comment by VladyslavBondarenko** [comment]
Hi @jesseframework 
I see there's an open issue addressing the case you described.
Please follow up on https://github.com/simolus3/moor/issues/420
I'm closing the current since it's related to the 3rd-party plugin
If you disagree please write in the comments and I will reopen it
