### ISSUE TITLE
[tool_crash] FileSystemException: Failed to set file modification time, path = '/home/arun/application/flutter/packages/flutter_tools/.packages' (OS Error: Operation not permitted, errno = 1)

### ISSUE THREAD

**Issue by oyearunpal** [flutter/flutter#56438]
## Command
```
flutter run -d chrome
```

## Steps to Reproduce
Just followed the steps at https://flutter.dev/docs/get-started/web for first time.

## Logs
FileSystemException: FileSystemException: Failed to set file modification time, path = '/home/arun/application/flutter/packages/flutter_tools/.packages' (OS Error: Operation not permitted, errno = 1)
```
#0      _File.setLastModifiedSync (dart:io/file_impl.dart:473:7)
#1      ForwardingFile.setLastModifiedSync (package:file/src/forwarding/forwarding_file.dart:62:55)
#2      ForwardingFile.setLastModifiedSync (package:file/src/forwarding/forwarding_file.dart:62:55)
#3      _DefaultPub.get (package:flutter_tools/src/dart/pub.dart:213:19)
#4      _ResidentWebRunner.run.<anonymous closure> (package:flutter_tools/src/build_runner/resident_web_runner.dart:411:19)
#5      asyncGuard.<anonymous closure> (package:flutter_tools/src/base/async_guard.dart:111:32)
#6      _rootRun (dart:async/zone.dart:1184:13)
#7      _CustomZone.run (dart:async/zone.dart:1077:19)
#8      _runZoned (dart:async/zone.dart:1619:10)
#9      runZonedGuarded (dart:async/zone.dart:1608:12)
#10     runZoned (dart:async/zone.dart:1536:12)
#11     asyncGuard (package:flutter_tools/src/base/async_guard.dart:109:3)
#12     _ResidentWebRunner.run (package:flutter_tools/src/build_runner/resident_web_runner.dart:407:20)
<asynchronous suspension>
#13     RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:564:37)
<asynchronous suspension>
#14     FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:722:18)
#15     _rootRunUnary (dart:async/zone.dart:1192:38)
#16     _CustomZone.runUnary (dart:async/zone.dart:1085:19)
#17     _FutureListener.handleValue (dart:async/future_impl.dart:141:18)
```
```
[✓] Flutter (Channel beta, v1.17.0-3.4.pre, on Linux, locale en_IN)
    • Flutter version 1.17.0-3.4.pre at /home/arun/application/flutter
    • Framework revision e6b34c2b5c (4 days ago), 2020-05-02 11:39:18 -0700
    • Engine revision 540786dd51
    • Dart version 2.8.1

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /home/arun/Android/Sdk
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /opt/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_152-release-1248-b01)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[!] Android Studio (version 2.3)
    • Android Studio at /opt/android-studio
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build
      1.8.0_152-release-1248-b01)

[✓] VS Code (version 1.44.2)
    • VS Code at /usr/share/code
    • Flutter extension version 3.10.1

[✓] Connected device (2 available)
    • Chrome     • chrome     • web-javascript • Google Chrome 81.0.4044.129
    • Web Server • web-server • web-javascript • Flutter Tools

! Doctor found issues in 1 category.

```

## Flutter Application Metadata
**Type**: app
**Version**: 1.0.0+1
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: beta
**Creation framework version**: e6b34c2b5c96bb95325269a29a84e83ed8909b5f

**Comment by oyearunpal** [comment]
On further investigation, I found that there was an issue of permission. After giving permission issue is resolved.
