### ISSUE TITLE
Exhausted heap space with out of memory while running command

### ISSUE THREAD

**Issue by apachucy** [flutter/flutter#56435]
## Steps to Reproduce
run command: `flutter pub run build_runner watch --delete-conflicting-outputs`

## Logs
```
Exhausted heap space, trying to allocate 17888 bytes.
Exhausted heap space, trying to allocate 96 bytes.
Exhausted heap space, trying to allocate 176 bytes.
kernel-service: Error: Unhandled exception:
Out of Memory
#0      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:682:40)
#1      Future._propagateToListeners (dart:async/future_impl.dart:709:32)
#2      Future._completeWithValue (dart:async/future_impl.dart:524:5)
#3      Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:554:7)
#4      _rootRun (dart:async/zone.dart:1126:13)
#5      _CustomZone.run (dart:async/zone.dart:1023:19)
#6      _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:949:23)
#7      _microtaskLoop (dart:async/schedule_microtask.dart:43:21)
#8      _startMicrotaskLoop (dart:async/schedule_microtask.dart:52:5)
#9      _Timer._runTimers (dart:isolate-patch/timer_impl.dart:393:30)
#10     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:418:5)
#11     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:174:12)
#12     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:949:23)
#13     _microtaskLoop (dart:async/schedule_microtask.dart:43:21)
#14     _startMicrotaskLoop (dart:async/schedule_microtask.dart:52:5)
#15     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:393:30)
#16     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:418:5)
#17     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:174:12)
#18     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:174:12)

Unhandled exception:
Out of Memory
#0      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:682:40)
#1      Future._propagateToListeners (dart:async/future_impl.dart:709:32)
#2      Future._completeWithValue (dart:async/future_impl.dart:524:5)
#3      Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:554:7)
#4      _rootRun (dart:async/zone.dart:1126:13)
#5      _CustomZone.run (dart:async/zone.dart:1023:19)
#6      _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:949:23)
#7      _microtaskLoop (dart:async/schedule_microtask.dart:43:21)
#8      _startMicrotaskLoop (dart:async/schedule_microtask.dart:52:5)
#9      _Timer._runTimers (dart:isolate-patch/timer_impl.dart:393:30)
#10     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:418:5)
#11     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:174:12)
#12     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:949:23)
#13     _microtaskLoop (dart:async/schedule_microtask.dart:43:21)
#14     _startMicrotaskLoop (dart:async/schedule_microtask.dart:52:5)
#15     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:393:30)
#16     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:418:5)
#17     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:174:12)
#18     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:174:12)
Out of Memory
#0      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:682:40)
#1      Future._propagateToListeners (dart:async/future_impl.dart:709:32)
#2      Future._completeWithValue (dart:async/future_impl.dart:524:5)
#3      Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:554:7)
#4      _rootRun (dart:async/zone.dart:1126:13)
#5      _CustomZone.run (dart:async/zone.dart:1023:19)
#6      _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:949:23)
#7      _microtaskLoop (dart:async/schedule_microtask.dart:43:21)
#8      _startMicrotaskLoop (dart:async/schedule_microtask.dart:52:5)
#9      _Timer._runTimers (dart:isolate-patch/timer_impl.dart:393:30)
#10     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:418:5)
#11     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:174:12)
#12     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:949:23)
#13     _microtaskLoop (dart:async/schedule_microtask.dart:43:21)
#14     _startMicrotaskLoop (dart:async/schedule_microtask.dart:52:5)
#15     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:393:30)
```

##flutter doctor
`Doctor summary (to see all details, run flutter doctor -v):                                                             [√] Flutter (Channel stable, v1.12.13+hotfix.9, on Microsoft Windows [Version 10.0.18363.778], locale pl-PL)            [!] Android toolchain - develop for Android devices (Android SDK version 29.0.3)                                            X Android license status unknown.                                                                                         Try re-installing or updating your Android SDK Manager.                                                                 See https://developer.android.com/studio/#downloads or visit https://flutter.dev/setup/#android-setup for detailed      instructions.                                                                                                     [!] Android Studio (version 3.6)                                                                                            X Flutter plugin not installed; this adds Flutter specific functionality.                                               X Dart plugin not installed; this adds Dart specific functionality.                                                 [!] IntelliJ IDEA Community Edition (version 2019.3)                                                                        X Flutter plugin not installed; this adds Flutter specific functionality.                                               X Dart plugin not installed; this adds Dart specific functionality.                                                 [√] IntelliJ IDEA Ultimate Edition (version 2019.3)                                                                     [!] Connected device                                                                                                        ! No devices available   `

**Comment by VladyslavBondarenko** [comment]
@apachucy 
thank you for update, closing as solved,
if you disagree please write in the comments and I will reopen it

**Comment by apachucy** [comment]
Could you check why white space in file name cause out of memory exception and memory leak ?

**Comment by VladyslavBondarenko** [comment]
@apachucy could you specify where did you have the name with white space?
