### ISSUE TITLE
[tool_crash] FileSystemException: Cannot open file, OS Error: The system cannot find the file specified., errno = 2

### ISSUE THREAD

**Issue by kumaralok344** [flutter/flutter#56447]
## Command
```
flutter pub get
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
FileSystemException: Cannot open file, OS Error: The system cannot find the file specified.
, errno = 2
```
#0      _File.open.<anonymous closure> (dart:io/file_impl.dart:366:9)
#1      _rootRunUnary (dart:async/zone.dart:1192:38)
#2      _CustomZone.runUnary (dart:async/zone.dart:1085:19)
#3      _FutureListener.handleValue (dart:async/future_impl.dart:141:18)
#4      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:686:45)
#5      Future._propagateToListeners (dart:async/future_impl.dart:715:32)
#6      Future._completeWithValue (dart:async/future_impl.dart:526:5)
#7      Future._asyncCompleteWithValue.<anonymous closure> (dart:async/future_impl.dart:560:7)
#8      _rootRun (dart:async/zone.dart:1184:13)
#9      _CustomZone.run (dart:async/zone.dart:1077:19)
#10     _CustomZone.runGuarded (dart:async/zone.dart:979:7)
#11     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1019:23)
#12     _microtaskLoop (dart:async/schedule_microtask.dart:43:21)
#13     _startMicrotaskLoop (dart:async/schedule_microtask.dart:52:5)
#14     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
#15     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:169:5)
```
```
[✓] Flutter (Channel master, 1.18.0-9.0.pre.129, on Microsoft Windows [Version 10.0.18363.752], locale en-IN)
    • Flutter version 1.18.0-9.0.pre.129 at C:\src\flutter
    • Framework revision f7ed942a70 (19 hours ago), 2020-05-05 13:13:21 -0700
    • Engine revision 33d2367950
    • Dart version 2.9.0 (build 2.9.0-5.0.dev 9c94f08410)

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at C:\src\Sdk
    • Platform android-29, build-tools 29.0.3
    • ANDROID_HOME = C:\Users\Alok\.AndroidStudio3.6
    • ANDROID_SDK_ROOT = C:\src\sdk
    • Java binary at: C:\Program Files\Java\jdk1.8.0_101\bin\java
    • Java version Java(TM) SE Runtime Environment (build 1.8.0_101-b13)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[✓] Visual Studio - develop for Windows (Visual Studio Community 2019 16.5.2)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.5.29926.136

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/windows#android-setup for detailed instructions).

[✓] VS Code (version 1.44.2)
    • VS Code at C:\Users\Alok\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.10.1

[✓] Connected device (3 available)
    • Windows    • Windows    • windows-x64    • Microsoft Windows [Version 10.0.18363.752]
    • Web Server • web-server • web-javascript • Flutter Tools
    • Chrome     • chrome     • web-javascript • Google Chrome 81.0.4044.129

! Doctor found issues in 1 category.

```

## Flutter Application Metadata
**Type**: null
**Version**: 0.1.0
**Material**: false
**Android X**: false
**Module**: false
**Plugin**: true
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: null
**Creation framework version**: null
### Plugins
file_chooser

**Comment by VladyslavBondarenko** [comment]
Hi @kumaralok344 
could you provide your `flutter pub get --verbose`?
what is the `file_chooser` plugin? I can't see it on pub.dev

**Comment by karedem** [comment]
link:  https://pub.dev/packages/flutter_alibc


| |
karedem
|
|
13257095257@163.com
|
签名由网易邮箱大师定制


On 05/7/2020 17:18，Vladyslav Bondarenko<notifications@github.com> wrote：

Hi @kumaralok344
could you provide your flutter pub get --verbose?
what is the file_chooser plugin? I can't see it on pub.dev

**Comment by VladyslavBondarenko** [comment]
@karedem 
can you see this error on `flutter pub get`, right?
provide please your `flutter pub get --verbose` log and `pubspec.yaml`

**Comment by VladyslavBondarenko** [comment]
@kumaralok344 
I hope you've solved the issue.
Closing as additional information isn't provided.
Could everyone who still has this problem please file a new issue with the exact descriptions what happens, logs and the output of `flutter doctor -v` please.
