### ISSUE TITLE
FLUTTER WEB [tool_crash] FormatException: Bad UTF-8 encoding 0xaa (at offset 25)

### ISSUE THREAD

**Issue by clus90** [flutter/flutter#56468]
Yesterday my code was working fine, but today I get this error when I try to run my project. I am on BETA channel because I am working on a Flutter Web project.

Please help!

## Command
```
flutter run
```
## Logs
FormatException: FormatException: Bad UTF-8 encoding 0xaa (at offset 25)
```
#0      _Utf8Decoder.convert (dart:convert/utf.dart:532:13)
#1      _Utf8ConversionSink.addSlice (dart:convert/string_conversion.dart:311:14)
#2      _Utf8ConversionSink.add (dart:convert/string_conversion.dart:307:5)
#3      _ConverterStreamEventSink.add (dart:convert/chunked_conversion.dart:74:18)
#4      _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:122:24)
#5      _rootRunUnary (dart:async/zone.dart:1192:38)
#6      _CustomZone.runUnary (dart:async/zone.dart:1085:19)
#7      _CustomZone.runUnaryGuarded (dart:async/zone.dart:987:7)
#8      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11)
#9      _BufferingStreamSubscription._add (dart:async/stream_impl.dart:266:7)
#10     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:779:19)
#11     _StreamController._add (dart:async/stream_controller.dart:655:7)
#12     _StreamController.add (dart:async/stream_controller.dart:597:5)
#13     _Socket._onData (dart:io-patch/socket_patch.dart:1982:41)
#14     _rootRunUnary (dart:async/zone.dart:1196:13)
#15     _CustomZone.runUnary (dart:async/zone.dart:1085:19)
#16     _CustomZone.runUnaryGuarded (dart:async/zone.dart:987:7)
#17     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11)
#18     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:266:7)
#19     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:779:19)
```
```
[✓] Flutter (Channel beta, v1.17.0, on Mac OS X 10.14.6 18G4032, locale en-VE)
    • Flutter version 1.17.0 at /Users/curbina90/Development/flutter
    • Framework revision e6b34c2b5c (4 days ago), 2020-05-02 11:39:18 -0700
    • Engine revision 540786dd51
    • Dart version 2.8.1

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/curbina90/Library/Android/sdk
    • Platform android-29, build-tools 29.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.3.1, Build version 11C504
    • CocoaPods version 1.9.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 43.0.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] VS Code (version 1.44.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.10.1

[☠] Connected device (the doctor check crashed)
    ✗ Due to an error, the doctor check did not complete. If the error message below is not helpful, please let us know about this issue at https://github.com/flutter/flutter/issues.
    ✗ FormatException: Bad UTF-8 encoding 0xaa (at offset 25)
    • #0      _Utf8Decoder.convert (dart:convert/utf.dart:532:13)
      #1      _Utf8ConversionSink.addSlice (dart:convert/string_conversion.dart:311:14)
      #2      _Utf8ConversionSink.add (dart:convert/string_conversion.dart:307:5)
      #3      _ConverterStreamEventSink.add (dart:convert/chunked_conversion.dart:74:18)
      #4      _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:122:24)
      #5      _rootRunUnary (dart:async/zone.dart:1192:38)
      #6      _CustomZone.runUnary (dart:async/zone.dart:1085:19)
      #7      _CustomZone.runUnaryGuarded (dart:async/zone.dart:987:7)
      #8      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11)
      #9      _BufferingStreamSubscription._add (dart:async/stream_impl.dart:266:7)
      #10     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:779:19)
      #11     _StreamController._add (dart:async/stream_controller.dart:655:7)
      #12     _StreamController.add (dart:async/stream_controller.dart:597:5)
      #13     _Socket._onData (dart:io-patch/socket_patch.dart:1982:41)
      #14     _rootRunUnary (dart:async/zone.dart:1196:13)
      #15     _CustomZone.runUnary (dart:async/zone.dart:1085:19)
      #16     _CustomZone.runUnaryGuarded (dart:async/zone.dart:987:7)
      #17     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11)
      #18     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:266:7)
      #19     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:779:19)
      #20     _StreamController._add (dart:async/stream_controller.dart:655:7)
      #21     _StreamController.add (dart:async/stream_controller.dart:597:5)
      #22     new _RawSocket.<anonymous closure> (dart:io-patch/socket_patch.dart:1527:33)
      #23     _NativeSocket.issueReadEvent.issue (dart:io-patch/socket_patch.dart:1019:14)
      #24     _microtaskLoop (dart:async/schedule_microtask.dart:43:21)
      #25     _startMicrotaskLoop (dart:async/schedule_microtask.dart:52:5)
      #26     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
      #27     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:169:5)


! Doctor found issues in 1 category.

```

## Flutter Application Metadata
**Type**: app
**Version**: 1.0.0+1
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: beta
**Creation framework version**: d3ed9ec945f8869f0e136c357d0c2a6be2b60c98
### Plugins
cloud_firestore-0.13.4+2
cloud_firestore_web-0.1.1+2
firebase_auth-0.15.5+3
firebase_auth_web-0.1.2
firebase_core-0.4.4+3
firebase_core_web-0.1.1+2
firebase_storage-3.1.5
flutter_plugin_android_lifecycle-1.0.6
google_maps_flutter-0.5.25+3
image_picker_web-1.0.6
searchable_dropdown-1.1.3

**Comment by TahaTesser** [comment]
Hi @clus90 
can you please provide your `flutter run -d Chrome --verbose`? 
Also, to better address the issue, would be helpful if you could post a minimal code sample to reproduce the problem
Thank you

**Comment by clus90** [comment]
My phone was connected to the computer, for some reason even though I wasn’t running it on the phone it was interfering with the build process.
I unplugged the phone and everything worked again.
