### ISSUE TITLE
More error information for: type '_SyncIterable<Widget>' is not a subtype of type 'List<Widget>'

### ISSUE THREAD

**Issue by jpc-ae** [flutter/flutter#56469]
I received an error which directed me to open an issue so the team can provide 'substantially more information in this error message', even though I discovered what the error was:

```
Performing hot reload...
Syncing files to device Android SDK built for x86...

════════ Exception caught by widgets library ═══════════════════════════════════════════════════════
The following assertion was thrown building SearchPage(dirty, dependencies: [_LocalizationsScope-[GlobalKey#46f5f], _InheritedTheme], state: _SearchPageState#9ce6a):
type '_SyncIterable<Widget>' is not a subtype of type 'List<Widget>'


Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=BUG.md

The relevant error-causing widget was: 
  SearchPage file:///C:/AndroidStudioProjects/cjk_dict/lib/main.dart:13:13
When the exception was thrown, this was the stack: 
#0      _SearchPageState.build (package:cjkdict/main.dart:62:28)
#1      StatefulElement.build (package:flutter/src/widgets/framework.dart:4334:27)
#2      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4223:15)
#3      Element.rebuild (package:flutter/src/widgets/framework.dart:3947:5)
#4      StatefulElement.update (package:flutter/src/widgets/framework.dart:4413:5)
...
════════════════════════════════════════════════════════════════════════════════════════════════════
Reloaded 1 of 478 libraries in 1,580ms.

```

The error was a missing `.toList()` call after the closing bracket of `ListTile.divideTiles()`. I received the same error with a longer stack trace when rebuilding the app with the title text shown as an error on the emulator screen.

A simplified version of my code that produced the error is below:

```dart
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: SearchPage(),
    );
  }
}

class SearchPage extends StatefulWidget {
  @override
  _SearchPageState createState() => _SearchPageState();
}

class _SearchPageState extends State<SearchPage> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: TextFormField(
          decoration: const InputDecoration(
            icon: Icon(
              Icons.search,
            ),
            hintText: '汉字, romanization, english...',
          ),
        ),
      ),
      body: ListView(
        children: ListTile.divideTiles(
          context: context,
          tiles: [
            ListTile(
              title: Row(
                children: <Widget>[
                  RichText(
                    text: TextSpan(
                      children: <TextSpan>[
                        TextSpan(
                          text: '汉',
                        ),
                        TextSpan(
                          text: '字',
                        ),
                      ],
                    ),
                  ),
                  SizedBox(
                    width: 16.0,
                  ),
                  Expanded(
                    child: Text('Han Zi / kanji / hanja'),
                  ),
                ],
              ),
              subtitle: Text(
                  'Chinese: ・chinese character(s)\nJapanese: ・chinese character writing system'),
            ),
          ],
        ),
      ),
    );
  }
}

```

**Comment by TahaTesser** [comment]
<details> 
<summary>flutter doctor -v</summary>

``` 
[✓] Flutter (Channel dev, 1.18.0-12.0.pre, on Mac OS X 10.15.4 19E287, locale en-GB)
    • Flutter version 1.18.0-12.0.pre at /Users/tahatesser/Code/flutter_dev
    • Framework revision c2b7342ca4 (21 hours ago), 2020-05-06 23:16:03 +0800
    • Engine revision 33d2367950
    • Dart version 2.9.0 (build 2.9.0-5.0.dev 9c94f08410)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/tahatesser/Code/SDK
    • Platform android-29, build-tools 29.0.3
    • ANDROID_HOME = /Users/tahatesser/Code/SDK
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.4.1, Build version 11E503a
    • CocoaPods version 1.9.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)

[✓] VS Code (version 1.44.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.10.1

[✓] Connected device (5 available)
    • SM M305F      • 32003c30dc19668f          • android-arm64  • Android 10 (API 29)
    • Taha’s iPhone • 00008020-001059882212002E • ios            • iOS 13.4.1
    • macOS         • macOS                     • darwin-x64     • Mac OS X 10.15.4 19E287
    • Web Server    • web-server                • web-javascript • Flutter Tools
    • Chrome        • chrome                    • web-javascript • Google Chrome 81.0.4044.138

• No issues found!
``` 

</details>

**Comment by jonahwilliams** [comment]
> The error was a missing .toList() call after the closing bracket of ListTile.divideTiles(). I received the same error with a longer stack trace when rebuilding the app with the title text shown as an error on the emulator screen.

This is a user error and not an issue with Flutter, see https://api.flutter.dev/flutter/material/ListTile/divideTiles.html

**Comment by jpc-ae** [comment]
I realize this is a user error, but according to the error message itself the error thrown needs to be made more descriptive. Should it perhaps be reopened as an enhancement request?
