### ISSUE TITLE
After 1.17 I get Unhandled Exception: Header value exceeds the 8192 size limit

### ISSUE THREAD

**Issue by aakhalilian** [flutter/flutter#56580]
## Steps to Reproduce

1. send a request to authenticate and get back a token larger than 8192

similar to https://github.com/dart-lang/sdk/issues/28251 but for response headers

**Expected results:** 
Before 1.17 request has been proceeded without error 

**Actual results:** 

<details>
  <summary>Logs</summary>

```
[VERBOSE-2:ui_dart_state.cc(157)] Unhandled Exception: Header value exceeds the 8192 size limit
#0      IOClient.send (package:http/src/io_client.dart:62:7)
<asynchronous suspension>
#1      BaseClient._sendUnstreamed (package:http/src/base_client.dart:176:38)
#2      BaseClient.post (package:http/src/base_client.dart:58:7)
#3      post.<anonymous closure> (package:http/http.dart:70:16)
#4      _withClient (package:http/http.dart:166:20)
#5      post (package:http/http.dart:69:5)
#6      UserAuthenticationService.authenticate (package:halivent/models/user_authentication_service.dart:143:36)
```

```
info • Unused import: 'package:halivent/screens/action_screen.dart' • lib/models/action_item_service.dart:15:8 • unused_import
   info • Unused import: 'dart:async' • lib/models/conversation.dart:1:8 • unused_import
   info • Unused import: '../themes.dart' • lib/models/conversation.dart:7:8 • unused_import
   info • Unused import: 'package:halivent/models/user_connections.dart' • lib/models/conversation_message_attachment_action.dart:4:8 • unused_import
   info • The value of the local variable 'statuses' isn't used • lib/models/platform_permission_service.dart:34:45 • unused_local_variable
   info • Unused import: 'dart:convert' • lib/screens/attachment_image_screen.dart:1:8 • unused_import
   info • Unused import: 'package:flutter/services.dart' • lib/screens/attachment_image_screen.dart:5:8 • unused_import
   info • The value of the field '_error' isn't used • lib/screens/attachment_image_screen.dart:21:10 • unused_field
   info • The value of the local variable 'asset' isn't used • lib/screens/attachment_image_screen.dart:173:27 • unused_local_variable
   info • Unused import: 'package:halivent/models/conversation_message.dart' • lib/screens/attachment_poll_screen.dart:3:8 • unused_import
   info • Unused import: 'package:provider/provider.dart' • lib/screens/authentication_signin_screen.dart:11:8 • unused_import
   info • Unused import: 'dart:math' • lib/screens/connections_screen.dart:1:8 • unused_import
   info • Unused import: 'conversation_initiation_screen.dart' • lib/screens/conversations_screen.dart:11:8 • unused_import
   info • 'body2' is deprecated and shouldn't be used. This is the term used in the 2014 version of material design. The modern term is bodyText1. This feature
          was deprecated after v1.13.8. • lib/screens/group_creation_screen.dart:160:91 • deprecated_member_use
   info • 'body2' is deprecated and shouldn't be used. This is the term used in the 2014 version of material design. The modern term is bodyText1. This feature
          was deprecated after v1.13.8. • lib/screens/group_creation_screen.dart:269:66 • deprecated_member_use
   info • The declaration '_getPosition' isn't referenced • lib/screens/plan_eventuality_screen.dart:29:3 • unused_element
   info • Unused import: 'package:geolocator/geolocator.dart' • lib/screens/plan_screen.dart:6:8 • unused_import
   info • Unused import: 'package:halivent/models/platform_permission_service.dart' • lib/screens/plan_screen.dart:8:8 • unused_import
   info • Unused import: 'package:halivent/widgets/conversation_item_widget.dart' • lib/screens/share_with_screen.dart:10:8 • unused_import
   info • 'display1' is deprecated and shouldn't be used. This is the term used in the 2014 version of material design. The modern term is headline4. This
          feature was deprecated after v1.13.8. • lib/themes.dart:61:3 • deprecated_member_use
   info • 'headline' is deprecated and shouldn't be used. This is the term used in the 2014 version of material design. The modern term is headline5. This
          feature was deprecated after v1.13.8. • lib/themes.dart:62:3 • deprecated_member_use
   info • 'title' is deprecated and shouldn't be used. This is the term used in the 2014 version of material design. The modern term is headline6. This feature
          was deprecated after v1.13.8. • lib/themes.dart:63:3 • deprecated_member_use
   info • 'subtitle' is deprecated and shouldn't be used. This is the term used in the 2014 version of material design. The modern term is subtitle2. This
          feature was deprecated after v1.13.8. • lib/themes.dart:64:3 • deprecated_member_use
   info • 'body2' is deprecated and shouldn't be used. This is the term used in the 2014 version of material design. The modern term is bodyText1. This feature
          was deprecated after v1.13.8. • lib/themes.dart:65:3 • deprecated_member_use
   info • 'body1' is deprecated and shouldn't be used. This is the term used in the 2014 version of material design. The modern term is bodyText2. This feature
          was deprecated after v1.13.8. • lib/themes.dart:66:3 • deprecated_member_use
   info • 'display1' is deprecated and shouldn't be used. This is the term used in the 2014 version of material design. The modern term is headline4. This
          feature was deprecated after v1.13.8. • lib/themes.dart:71:3 • deprecated_member_use
   info • 'headline' is deprecated and shouldn't be used. This is the term used in the 2014 version of material design. The modern term is headline5. This
          feature was deprecated after v1.13.8. • lib/themes.dart:72:3 • deprecated_member_use
   info • 'title' is deprecated and shouldn't be used. This is the term used in the 2014 version of material design. The modern term is headline6. This feature
          was deprecated after v1.13.8. • lib/themes.dart:73:3 • deprecated_member_use
   info • 'subtitle' is deprecated and shouldn't be used. This is the term used in the 2014 version of material design. The modern term is subtitle2. This
          feature was deprecated after v1.13.8. • lib/themes.dart:74:3 • deprecated_member_use
   info • 'body2' is deprecated and shouldn't be used. This is the term used in the 2014 version of material design. The modern term is bodyText1. This feature
          was deprecated after v1.13.8. • lib/themes.dart:75:3 • deprecated_member_use
   info • 'body1' is deprecated and shouldn't be used. This is the term used in the 2014 version of material design. The modern term is bodyText2. This feature
          was deprecated after v1.13.8. • lib/themes.dart:76:3 • deprecated_member_use
   info • 'body2' is deprecated and shouldn't be used. This is the term used in the 2014 version of material design. The modern term is bodyText1. This feature
          was deprecated after v1.13.8. • lib/themes.dart:189:52 • deprecated_member_use
   info • 'body2' is deprecated and shouldn't be used. This is the term used in the 2014 version of material design. The modern term is bodyText1. This feature
          was deprecated after v1.13.8. • lib/themes.dart:218:52 • deprecated_member_use
   info • Name non-constant identifiers using lowerCamelCase • lib/utils/stomp_custom_client.dart:57:8 • non_constant_identifier_names
   info • Unused import: 'package:halivent/models/user.dart' • lib/views/registration_contact_info.dart:3:8 • unused_import
   info • The member 'setState' can only be used within instance members of subclasses of 'package:flutter/src/widgets/framework.dart' •
          lib/views/registration_contact_info.dart:48:31 • invalid_use_of_protected_member
   info • The member 'setState' can only be used within instance members of subclasses of 'package:flutter/src/widgets/framework.dart' •
          lib/views/registration_contact_info_verification.dart:45:29 • invalid_use_of_protected_member
   info • The member 'setState' can only be used within instance members of subclasses of 'package:flutter/src/widgets/framework.dart' •
          lib/views/registration_contact_info_verification.dart:58:27 • invalid_use_of_protected_member
   info • 'body2' is deprecated and shouldn't be used. This is the term used in the 2014 version of material design. The modern term is bodyText1. This feature
          was deprecated after v1.13.8. • lib/widgets/connection_item_widgets.dart:75:60 • deprecated_member_use
   info • 'body2' is deprecated and shouldn't be used. This is the term used in the 2014 version of material design. The modern term is bodyText1. This feature
          was deprecated after v1.13.8. • lib/widgets/connection_item_widgets.dart:84:30 • deprecated_member_use
   info • Unused import: '../constants.dart' • lib/widgets/message_attachment_action_widget.dart:11:8 • unused_import
   info • Unused import: 'package:halivent/models/conversation_service.dart' • lib/widgets/message_attachment_images_widget.dart:8:8 • unused_import
   info • Unused import: '../endpoints.dart' • lib/widgets/message_attachment_images_widget.dart:11:8 • unused_import
   info • Unused import: 'dart:math' • lib/widgets/message_attachment_pool_widget.dart:1:8 • unused_import
   info • 'body1' is deprecated and shouldn't be used. This is the term used in the 2014 version of material design. The modern term is bodyText2. This feature
          was deprecated after v1.13.8. • lib/widgets/message_attachment_pool_widget.dart:195:53 • deprecated_member_use
   info • 'body1' is deprecated and shouldn't be used. This is the term used in the 2014 version of material design. The modern term is bodyText2. This feature
          was deprecated after v1.13.8. • lib/widgets/message_attachment_pool_widget.dart:229:49 • deprecated_member_use
   info • Name non-constant identifiers using lowerCamelCase • lib/widgets/message_text_bot_widget.dart:162:14 • non_constant_identifier_names
   info • Name non-constant identifiers using lowerCamelCase • lib/widgets/message_text_widget.dart:401:14 • non_constant_identifier_names
   info • 'body1' is deprecated and shouldn't be used. This is the term used in the 2014 version of material design. The modern term is bodyText2. This feature
          was deprecated after v1.13.8. • lib/widgets/scroll_bar_widget.dart:34:52 • deprecated_member_use
   info • Unused import: 'dart:convert' • test/utils/rsa_encryption_client_test.dart:1:8 • unused_import

```

```
[✓] Flutter (Channel stable, v1.17.0, on Mac OS X 10.15.4 19E287, locale en-US)
    • Flutter version 1.17.0 at /Users/kentaki/apps/flutter
    • Framework revision e6b34c2b5c (5 days ago), 2020-05-02 11:39:18 -0700
    • Engine revision 540786dd51
    • Dart version 2.8.1

 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/kentaki/Library/Android/sdk
    • Platform android-29, build-tools 28.0.3
    • ANDROID_HOME = /Users/kentaki/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.1, Build version 11A1027
    • CocoaPods version 1.8.4

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 41.1.2
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[!] IntelliJ IDEA Ultimate Edition (version 2018.3)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.dev/intellij-setup/#installing-the-plugins

[!] VS Code (version 1.44.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    ✗ Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (2 available)
    • Nexus 6P      • 84B7N17317001023                     • android-arm64 • Android 8.1.0 (API 27)
    • iPhone 11 Pro • B61F2464-E302-467D-9DE3-08DAA65E9E27 • ios           • com.apple.CoreSimulator.SimRuntime.iOS-13-1 (simulator)

! Doctor found issues in 2 categories.

```

</details>

**Comment by aakhalilian** [comment]
little bit of research, seems like this commit has created this limit https://github.com/dart-lang/sdk/commit/36496047b4fc095013f29be351ae9021eb7cd832 will this limit be configurable or final?
@zichangg

**Comment by zichangg** [comment]
This is not configurable nor final.

A upper bound for http headers field is needed for security reason. Most web servers have size limits(https://www.tutorialspoint.com/What-is-the-maximum-size-of-HTTP-header-values), so I chose 8k as a reasonable limit. I can definitely bump the size limit if this is too small.

What are you trying to put into headers? What is the approximate size?

**Comment by aakhalilian** [comment]
> This is not configurable nor final.
> 
> A upper bound for http headers field is needed for security reason. Most web servers have size limits(https://www.tutorialspoint.com/What-is-the-maximum-size-of-HTTP-header-values), so I chose 8k as a reasonable limit. I can definitely bump the size limit if this is too small.
> 
> What are you trying to put into headers? What is the approximate size?

so currently the content is jwt that contains claims and entitlements, probably the test id has too many records that caused the token to grow larger than 8k, I guess we need this to be more flexible for now, but we need to refactor the way we implemented access tokens since now it does not limit a user at all he can create 1 billion items and explode the token, I feel this is a big breaking change that never have been mentioned in release notes.

**Comment by aakhalilian** [comment]
actually we can move response token to payload body as quick solution @zichangg thanks for quick response, I will close this issue now

**Comment by zichangg** [comment]
> I feel this is a big breaking change that never have been mentioned in release notes.

Http Headers never declare to have its field to unlimited. So this is a change on an undefined behavior. But I should have put it into CHANGELOG. ^_^

**Comment by gbtb** [comment]
I've faced this issue when trying to fetch 3rd-party http page. This site uses quite large content-security-policy value with all the different social media and content providers urls enumerated in here. 
I would appreciate this size limit value become configurable in some way.

**Comment by zichangg** [comment]
Configurable is definitely great idea. But there are some problems. At first, It will be a breaking change. Is it worthy?

How do we struct this API? 
An optional parameter to `HttpClient` and `HttpServer` sounds reasonable. If we decide to make it configurable, I guest we also need to make other limits configurable.

Something like this
```dart
HttpClient([Map config]);
```

The other aspect is if we decide to expose those parameters, is there any potential security issue?

I think this could be a good thing to add in the future. An alternative is to loosen the limit for client side. Server side needs to be protected.

@lrhn Wdyt?

**Comment by lrhn** [comment]
If you use named parameters, then it doesn't matter how many there are. I expect most users to only use a few parameters at a time. 

Also, if we have gotten this far without too many problems, do we really need that much configurability? We shouldn't make something configurable just because we can.

So, do we expect users to regularly use many parameters, and to want to store and reuse "configurations"? If so, a configuration object sounds reasonable. Don't use a map, use a real class object. The class should be a simple data class, and it will be documented that it's not intended to be implemented or extended (you can safely extend the class, but there is no benefit, so you probably also shouldn't do that).

But don't bother if there is no actual need.

**Comment by gbtb** [comment]
In case anyone else stumble upon this issue. My temporary solution is to copy flutter/bin/cache/dart-sdk/lib/_http/ files into my project, increase limit in http_impl.dart, wipe all of http.dart except imports, then export _HttpClient as public class to use in e.g. IOClient

**Comment by Hixie** [comment]
(This might be worth moving to the Dart repo.)

**Comment by TahaTesser** [comment]
Hi @zichangg
I see you're assigned to this issue couple of months ago and have mentioned this issue  for2 days ago
Are you working on fixing this issue? It will get closed soon? 
Thank you

**Comment by zichangg** [comment]
It can be closed once the change made to flutter. I didn't check whether the roller has done that or not.
