### ISSUE TITLE
Tap generates unexcepted exception

### ISSUE THREAD

**Issue by sethladd** [flutter/flutter#566]
I was trying various samples I found online. If I load up this sample, and then tap anywhere on the screen, I get an unexpected exception.

Sample:

```
// following code is checked in 2015/11/07
import 'package:flutter/widgets.dart';
import 'package:flutter/rendering.dart';
import 'package:flutter/animation.dart';
import 'dart:math';

void main() {
  runApp(new DrawRectWidget()..anime());
}

class DrawRectWidget extends OneChildRenderObjectWidget {
  double angle = 0.0;
  DrawRectObject o = new DrawRectObject();
  RenderObject createRenderObject() {
    return o;
  }

  int prevTimeStamp = 0;
  void anime() {
    scheduler.requestAnimationFrame((Duration timeStamp) {
      //print("${timeStamp.inMilliseconds-prevTimeStamp}");
      prevTimeStamp = timeStamp.inMilliseconds;
      o.x = 100 * cos(PI * angle / 180.0) + 100.0;
      o.y = 100 * sin(PI * angle / 180.0) + 100.0;
      angle++;
      o.markNeedsPaint();
      anime();
    });
  }
}

class DrawRectObject extends RenderBox {
  double x = 50.0;
  double y = 50.0;
  void paint(PaintingContext context, Offset offset) {
    Paint p = new Paint();
    p.color = new Color.fromARGB(0xff, 0x00, 0x00, 0xff);
    Rect r = new Rect.fromLTWH(x, y, 25.0, 25.0);
    context.canvas.drawRect(r, p);
  }
}
```

Exception:

```
android: E/flutter : NoSuchMethodError: method not found: 'width'
android: E/flutter : Receiver: null
android: E/flutter : Arguments: []
android: E/flutter : #0      Object._noSuchMethod (dart:core-patch/object_patch.dart:42)
android: E/flutter : #1      Object.noSuchMethod (dart:core-patch/object_patch.dart:45)
android: E/flutter : #2      RenderBox.hitTest (packages/flutter/src/rendering/box.dart:552)
android: E/flutter : #3      RenderView.hitTest (packages/flutter/src/rendering/view.dart:103)
android: E/flutter : #4      FlutterBinding.hitTest (packages/flutter/src/rendering/binding.dart:267)
android: E/flutter : #5      FlutterBinding._handlePointerInputEvent (packages/flutter/src/rendering/binding.dart:239)
android: E/flutter : #6      FlutterBinding._handlePointerPacket (packages/flutter/src/rendering/binding.dart:222)
android: E/flutter : #7      _dispatchPointerPacket (file:///src/flutter/engine/src/out/android_Release/gen/sky/bindings/Customhooks.dart:30)
```

This might be user error, but my code doesn't have anything to do with handling a tap, so I wouldn't expect an exception to be thrown.

**Comment by abarth** [comment]
This code is crazy.  It should assert much earlier than that.  Have you tried running it in checked mode?

**Comment by abarth** [comment]
The underlying problem is that DrawRectObject doesn't have a `performLayout` function, which means it's not getting a size during layout.  When you tap the screen, we try to hit test and get confused when we try to ask how big it is (since it has a null size).

**Comment by abarth** [comment]
Specifically, it should at least hit the assert on line 541 of box.dart.

**Comment by sethladd** [comment]
> Have you tried running it in checked mode?

Sorry, I'm not sure what the default run mode is for launches from Atom.  (cc @devoncarew ) I haven't specifically tried checked mode, but I can when I get back home. I think I know how to toggle that.

**Comment by devoncarew** [comment]
It launches in checked mode by default. You can adjust this in the yaml launch config file with `checked: true` / `checked: false`. There are some UI improvements (not yet published) that will make it clearer what config options (checked, ...) you launched with.

**Comment by abarth** [comment]
```
12-10 14:02:41.497 26208 26238 I flutter : -- EXCEPTION --
12-10 14:02:41.500 26208 26238 I flutter : The following exception was raised during performLayout():
12-10 14:02:41.503 26208 26238 I flutter : 'packages/flutter/src/rendering/box.dart': Failed assertion: line 570: 'sizedByParent' is not true.
12-10 14:02:41.503 26208 26238 I flutter : Stack trace:
12-10 14:02:41.506 26208 26238 I flutter : #0      _AssertionError._throwNew (dart:core-patch/errors_patch.dart:27)
12-10 14:02:41.506 26208 26238 I flutter : #1      RenderBox.performLayout (packages/flutter/src/rendering/box.dart:570)
12-10 14:02:41.506 26208 26238 I flutter : #2      RenderObject.layout (packages/flutter/src/rendering/object.dart:719)
12-10 14:02:41.506 26208 26238 I flutter : #3      RenderView.performLayout (packages/flutter/src/rendering/view.dart:97)
12-10 14:02:41.506 26208 26238 I flutter : #4      RenderObject._layoutWithoutResize (packages/flutter/src/rendering/object.dart:626)
12-10 14:02:41.506 26208 26238 I flutter : #5      RenderObject.flushLayout.<anonymous closure> (packages/flutter/src/rendering/object.dart:604)
```

I'll improve this assert.

**Comment by abarth** [comment]
I've posted a patch to improve the asserts in this case.
