### ISSUE TITLE
[tool_crash] FileSystemException: Cannot create file, path = 'C:\Users\user\Downloads\[FreeCourseSite.com] Udemy - The Complete Flutter UI Masterclass  iOS & Android in Dart\02 Food Delivery App\012 flutter-food-delivery-ui\flutter_food_delivery_ui\android\app\src\main\java\io\flutter\plugins\GeneratedPluginRegistrant.java' (OS Error: The system cannot find the path specified., errno = 3)

### ISSUE THREAD

**Issue by Daprinzce** [flutter/flutter#56650]
## Command
```
flutter packages get
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
FileSystemException: FileSystemException: Cannot create file, path = 'C:\Users\user\Downloads\[FreeCourseSite.com] Udemy - The Complete Flutter UI Masterclass  iOS & Android in Dart\02 Food Delivery App\012 flutter-food-delivery-ui\flutter_food_delivery_ui\android\app\src\main\java\io\flutter\plugins\GeneratedPluginRegistrant.java' (OS Error: The system cannot find the path specified.
, errno = 3)
```
#0      _File.throwIfError (dart:io/file_impl.dart:645:7)
#1      _File.createSync (dart:io/file_impl.dart:283:5)
#2      ForwardingFile.createSync (package:file/src/forwarding/forwarding_file.dart:24:16)
#3      ForwardingFile.createSync (package:file/src/forwarding/forwarding_file.dart:24:16)
#4      _renderTemplateToFile (package:flutter_tools/src/plugins.dart:27:8)
#5      _writeAndroidPluginRegistrant (package:flutter_tools/src/plugins.dart:641:3)
#6      injectPlugins (package:flutter_tools/src/plugins.dart:1079:11)
#7      FlutterProject.ensureReadyForPlatformSpecificTooling (package:flutter_tools/src/project.dart:232:11)
<asynchronous suspension>
#8      PackagesGetCommand.runCommand (package:flutter_tools/src/commands/packages.dart:128:23)
<asynchronous suspension>
#9      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:722:18)
#10     _rootRunUnary (dart:async/zone.dart:1192:38)
#11     _CustomZone.runUnary (dart:async/zone.dart:1085:19)
#12     _FutureListener.handleValue (dart:async/future_impl.dart:141:18)
#13     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:682:45)
#14     Future._propagateToListeners (dart:async/future_impl.dart:711:32)
#15     Future._completeWithValue (dart:async/future_impl.dart:526:5)
#16     Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:556:7)
#17     _rootRun (dart:async/zone.dart:1184:13)
```
```
[✓] Flutter (Channel stable, v1.17.0, on Microsoft Windows [Version 10.0.17763.55], locale en-GB)
    • Flutter version 1.17.0 at C:\flutter
    • Framework revision e6b34c2b5c (6 days ago), 2020-05-02 11:39:18 -0700
    • Engine revision 540786dd51
    • Dart version 2.8.1

[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/docs/get-started/install/windows#android-setup for detailed instructions).
      If the Android SDK has been installed to a custom location, set ANDROID_SDK_ROOT to that location.
      You may also want to add it to your PATH environment variable.


[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/windows#android-setup for detailed instructions).

[!] Connected device
    ! No devices available

! Doctor found issues in 3 categories.

```

## Flutter Application Metadata
**Type**: app
**Version**: 1.0.0+1
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: stable
**Creation framework version**: 1aedbb1835bd6eb44550293d57d4d124f19901f0

**Comment by iapicca** [comment]
Hi @Daprinzce 
I see there's an open [issue](https://github.com/flutter/flutter/issues/54704) addressing the case you described.
Please follow up on that issue,
I'm closing the current one as duplicate.
If you disagree please write in the comments
and I will reopen it.
Thank you
