### ISSUE TITLE
Hi  am havig error sorting my snapshot by date string

### ISSUE THREAD

**Issue by dartonx** [flutter/flutter#56669]
```bash
Launching lib\main.dart on SM A705FN in debug mode...
Running Gradle task 'assembleDebug'...
√ Built build\app\outputs\apk\debug\app-debug.apk.
Installing build\app\outputs\apk\app.apk...
Syncing files to device SM A705FN...
D/SurfaceView( 1524): onWindowVisibilityChanged(4) false io.flutter.view.FlutterView{40900f8 VFE...... ......I. 0,0-0,0} of ViewRootImpl@82efe62[MainActivity]
D/ViewRootImpl@82efe62[MainActivity]( 1524): Relayout returned: old=[0,0][1080,2400] new=[0,0][1080,2400] result=0x1 surface={false 0} changed=false
D/ViewRootImpl@82efe62[MainActivity]( 1524): stopped(false) old=true
D/SurfaceView( 1524): windowStopped(false) false io.flutter.view.FlutterView{40900f8 VFE...... ......I. 0,0-0,0} of ViewRootImpl@82efe62[MainActivity]
D/SurfaceView( 1524): onWindowVisibilityChanged(0) true io.flutter.view.FlutterView{40900f8 VFE...... ......I. 0,0-0,0} of ViewRootImpl@82efe62[MainActivity]
D/ViewRootImpl@82efe62[MainActivity]( 1524): Relayout returned: old=[0,0][1080,2400] new=[0,0][1080,2400] result=0x7 surface={true 477499879424} changed=true
I/OpenGLRenderer( 1524): Initialized EGL, version 1.4
D/OpenGLRenderer( 1524): Swap behavior 2
D/SurfaceView( 1524): show() Surface(name=SurfaceView - co.dartontech.flash_chat/co.appbrewery.flash_chat.MainActivity@40900f8@0[1524])/@0xdf129d1 io.flutter.view.FlutterView{40900f8 VFE...... ......ID 0,0-1080,2274}
D/OpenGLRenderer( 1524): eglCreateWindowSurface = 0x6f18d0c780, 0x6f2d35f010
D/SurfaceView( 1524): surfaceCreated 1 #8 io.flutter.view.FlutterView{40900f8 VFE...... ......ID 0,0-1080,2274}
D/SurfaceView( 1524): surfaceChanged (1080,2274) 1 #8 io.flutter.view.FlutterView{40900f8 VFE...... ......ID 0,0-1080,2274}
D/ViewRootImpl@82efe62[MainActivity]( 1524): stopped(false) old=false
D/ViewRootImpl@82efe62[MainActivity]( 1524): MSG_RESIZED: frame=[0,0][1080,2400] ci=[0,76][0,126] vi=[0,76][0,126] or=1
D/ViewRootImpl@82efe62[MainActivity]( 1524): MSG_WINDOW_FOCUS_CHANGED 1 1
D/InputMethodManager( 1524): prepareNavigationBarInfo() DecorView@ff5b9fe[MainActivity]
D/InputMethodManager( 1524): getNavigationBarColor() -855310
D/InputMethodManager( 1524): prepareNavigationBarInfo() DecorView@ff5b9fe[MainActivity]
D/InputMethodManager( 1524): getNavigationBarColor() -855310
V/InputMethodManager( 1524): Starting input: tba=co.dartontech.flash_chat ic=null mNaviBarColor -855310 mIsGetNaviBarColorSuccess true , NavVisible : true , NavTrans : false
D/InputMethodManager( 1524): startInputInner - Id : 0
I/InputMethodManager( 1524): startInputInner - mService.startInputOrWindowGainedFocus
D/InputTransport( 1524): Input channel constructed: fd=96
D/InputMethodManager( 1524): prepareNavigationBarInfo() DecorView@ff5b9fe[MainActivity]
D/InputMethodManager( 1524): getNavigationBarColor() -855310
V/InputMethodManager( 1524): Starting input: tba=co.dartontech.flash_chat ic=null mNaviBarColor -855310 mIsGetNaviBarColorSuccess true , NavVisible : true , NavTrans : false
D/InputMethodManager( 1524): startInputInner - Id : 0
D/ViewRootImpl@82efe62[MainActivity]( 1524): ViewPostIme pointer 0
D/ViewRootImpl@82efe62[MainActivity]( 1524): ViewPostIme pointer 1
D/ViewRootImpl@82efe62[MainActivity]( 1524): ViewPostIme pointer 0
D/ViewRootImpl@82efe62[MainActivity]( 1524): ViewPostIme pointer 1
D/InputMethodManager( 1524): SSI - flag : 0 Pid : 1524 view : co.dartontech.flash_chat
D/InputMethodManager( 1524): prepareNavigationBarInfo() DecorView@ff5b9fe[MainActivity]
D/InputMethodManager( 1524): getNavigationBarColor() -855310
V/InputMethodManager( 1524): Starting input: tba=co.dartontech.flash_chat ic=io.flutter.plugin.editing.InputConnectionAdaptor@fc743c mNaviBarColor -855310 mIsGetNaviBarColorSuccess true , NavVisible : true , NavTrans : false
D/InputMethodManager( 1524): startInputInner - Id : 0
I/InputMethodManager( 1524): startInputInner - mService.startInputOrWindowGainedFocus
D/InputTransport( 1524): Input channel constructed: fd=97
D/InputTransport( 1524): Input channel destroyed: fd=96
D/InputMethodManager( 1524): prepareNavigationBarInfo() DecorView@ff5b9fe[MainActivity]
D/InputMethodManager( 1524): getNavigationBarColor() -855310
D/InputMethodManager( 1524): prepareNavigationBarInfo() DecorView@ff5b9fe[MainActivity]
D/InputMethodManager( 1524): getNavigationBarColor() -855310
V/InputMethodManager( 1524): Starting input: tba=co.dartontech.flash_chat ic=io.flutter.plugin.editing.InputConnectionAdaptor@83f2941 mNaviBarColor -855310 mIsGetNaviBarColorSuccess true , NavVisible : true , NavTrans : false
D/InputMethodManager( 1524): startInputInner - Id : 0
I/InputMethodManager( 1524): startInputInner - mService.startInputOrWindowGainedFocus
D/InputTransport( 1524): Input channel constructed: fd=96
D/InputTransport( 1524): Input channel destroyed: fd=97
W/IInputConnectionWrapper( 1524): getExtractedText on inactive InputConnection
D/ViewRootImpl@82efe62[MainActivity]( 1524): MSG_RESIZED: frame=[0,0][1080,2400] ci=[0,76][0,1003] vi=[0,76][0,1003] or=1
D/ViewRootImpl@82efe62[MainActivity]( 1524): Relayout returned: old=[0,0][1080,2400] new=[0,0][1080,2400] result=0x1 surface={true 477499879424} changed=false
D/InputMethodManager( 1524): HSIFW - flag : 0 Pid : 1524
D/ViewRootImpl@82efe62[MainActivity]( 1524): MSG_RESIZED: frame=[0,0][1080,2400] ci=[0,76][0,126] vi=[0,76][0,126] or=1
D/ViewRootImpl@82efe62[MainActivity]( 1524): Relayout returned: old=[0,0][1080,2400] new=[0,0][1080,2400] result=0x1 surface={true 477499879424} changed=false
D/ViewRootImpl@82efe62[MainActivity]( 1524): ViewPostIme pointer 0
D/ViewRootImpl@82efe62[MainActivity]( 1524): ViewPostIme pointer 1
D/InputMethodManager( 1524): SSI - flag : 0 Pid : 1524 view : co.dartontech.flash_chat
D/InputMethodManager( 1524): prepareNavigationBarInfo() DecorView@ff5b9fe[MainActivity]
D/InputMethodManager( 1524): getNavigationBarColor() -855310
D/InputMethodManager( 1524): prepareNavigationBarInfo() DecorView@ff5b9fe[MainActivity]
D/InputMethodManager( 1524): getNavigationBarColor() -855310
V/InputMethodManager( 1524): Starting input: tba=co.dartontech.flash_chat ic=io.flutter.plugin.editing.InputConnectionAdaptor@67494be mNaviBarColor -855310 mIsGetNaviBarColorSuccess true , NavVisible : true , NavTrans : false
D/InputMethodManager( 1524): startInputInner - Id : 0
I/InputMethodManager( 1524): startInputInner - mService.startInputOrWindowGainedFocus
D/InputTransport( 1524): Input channel constructed: fd=98
D/InputTransport( 1524): Input channel destroyed: fd=96
W/IInputConnectionWrapper( 1524): getExtractedText on inactive InputConnection
D/ViewRootImpl@82efe62[MainActivity]( 1524): MSG_RESIZED: frame=[0,0][1080,2400] ci=[0,76][0,1003] vi=[0,76][0,1003] or=1
D/ViewRootImpl@82efe62[MainActivity]( 1524): Relayout returned: old=[0,0][1080,2400] new=[0,0][1080,2400] result=0x1 surface={true 477499879424} changed=false
D/ViewRootImpl@82efe62[MainActivity]( 1524): ViewPostIme pointer 0
D/ViewRootImpl@82efe62[MainActivity]( 1524): ViewPostIme pointer 1
D/InputMethodManager( 1524): SSI - flag : 0 Pid : 1524 view : co.dartontech.flash_chat
D/InputMethodManager( 1524): prepareNavigationBarInfo() DecorView@ff5b9fe[MainActivity]
D/InputMethodManager( 1524): getNavigationBarColor() -855310
D/InputMethodManager( 1524): prepareNavigationBarInfo() DecorView@ff5b9fe[MainActivity]
D/InputMethodManager( 1524): getNavigationBarColor() -855310
V/InputMethodManager( 1524): Starting input: tba=co.dartontech.flash_chat ic=io.flutter.plugin.editing.InputConnectionAdaptor@763646c mNaviBarColor -855310 mIsGetNaviBarColorSuccess true , NavVisible : true , NavTrans : false
D/InputMethodManager( 1524): startInputInner - Id : 0
I/InputMethodManager( 1524): startInputInner - mService.startInputOrWindowGainedFocus
D/InputTransport( 1524): Input channel constructed: fd=99
D/InputTransport( 1524): Input channel destroyed: fd=98
D/ViewRootImpl@82efe62[MainActivity]( 1524): ViewPostIme pointer 0
D/ViewRootImpl@82efe62[MainActivity]( 1524): ViewPostIme pointer 1
I/BiChannelGoogleApi( 1524): [FirebaseAuth: ] getGoogleApiForMethod() returned Gms: com.google.firebase.auth.api.internal.zzaq@572da35
W/DynamiteModule( 1524): Local module descriptor class for com.google.firebase.auth not found.
I/FirebaseAuth( 1524): [FirebaseAuth:] Preparing to create service connection to gms implementation
D/FirebaseAuth( 1524): Notifying id token listeners about user ( 8vkWBvyi9uZdKqbtoAxfiY5CxaM2 ).
D/InputMethodManager( 1524): HSIFW - flag : 0 Pid : 1524
W/DynamiteModule( 1524): Local module descriptor class for providerinstaller not found.
D/ConnectivityManager( 1524): requestNetwork; CallingUid : 10318, CallingPid : 1524
I/DynamiteModule( 1524): Considering local module providerinstaller:0 and remote module providerinstaller:0
W/ProviderInstaller( 1524): Failed to load providerinstaller module: No acceptable module found. Local version is 0 and remote version is 0.
I/tech.flash_cha( 1524): The ClassLoaderContext is a special shared library.
I/tech.flash_cha( 1524): The ClassLoaderContext is a special shared library.
I/tech.flash_cha( 1524): The ClassLoaderContext is a special shared library.
W/tech.flash_cha( 1524): Accessing hidden field Ljava/nio/Buffer;->address:J (light greylist, reflection)
D/ViewRootImpl@82efe62[MainActivity]( 1524): MSG_RESIZED: frame=[0,0][1080,2400] ci=[0,76][0,126] vi=[0,76][0,126] or=1
V/NativeCrypto( 1524): Registering com/google/android/gms/org/conscrypt/NativeCrypto's 286 native methods...
D/ViewRootImpl@82efe62[MainActivity]( 1524): Relayout returned: old=[0,0][1080,2400] new=[0,0][1080,2400] result=0x1 surface={true 477499879424} changed=false
W/tech.flash_cha( 1524): Accessing hidden method Ljava/security/spec/ECParameterSpec;->getCurveName()Ljava/lang/String; (light greylist, reflection)
D/NetworkSecurityConfig( 1524): No Network Security Config specified, using platform default
I/ProviderInstaller( 1524): Installed default security provider GmsCore_OpenSSL
D/ConnectivityManager( 1524): requestNetwork; CallingUid : 10318, CallingPid : 1524

════════ Exception caught by widgets library ═══════════════════════════════════════════════════════
The following assertion was thrown building StreamBuilder<QuerySnapshot>(dirty, state: _StreamBuilderBaseState<QuerySnapshot, AsyncSnapshot<QuerySnapshot>>#d4616):
type '(dynamic, dynamic) => dynamic' is not a subtype of type '(DocumentSnapshot, DocumentSnapshot) => int' of 'compare'


Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=BUG.md

The relevant error-causing widget was: 
  StreamBuilder<QuerySnapshot> file:///C:/Users/PRINTER/AndroidStudioProjects/flash-chat-flutter/lib/screens/chat_screen.dart:127:12
When the exception was thrown, this was the stack: 
#0      MessagesStream.build.<anonymous closure> (package:flash_chat/screens/chat_screen.dart:139:20)
#1      StreamBuilder.build (package:flutter/src/widgets/async.dart:425:74)
#2      _StreamBuilderBaseState.build (package:flutter/src/widgets/async.dart:125:48)
#3      StatefulElement.build (package:flutter/src/widgets/framework.dart:4334:27)
#4      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4223:15)
...
════════════════════════════════════════════════════════════════════════════════════════════════════

════════ (2) Exception caught by rendering library ═════════════════════════════════════════════════
A RenderFlex overflowed by 99269 pixels on the bottom.
The relevant error-causing widget was: 
  Column file:///C:/Users/PRINTER/AndroidStudioProjects/flash-chat-flutter/lib/screens/chat_screen.dart:81:16
════════════════════════════════════════════════════════════════════════════════════════════════════
D/NetworkManagementSocketTagger( 1524): tagSocket(103) with statsTag=0xffffffff, statsUid=-1
W/tech.flash_cha( 1524): Accessing hidden field Ljava/net/Socket;->impl:Ljava/net/SocketImpl; (light greylist, reflection)
W/tech.flash_cha( 1524): Accessing hidden method Ldalvik/system/CloseGuard;->get()Ldalvik/system/CloseGuard; (light greylist, linking)
W/tech.flash_cha( 1524): Accessing hidden method Ldalvik/system/CloseGuard;->open(Ljava/lang/String;)V (light greylist, linking)
W/tech.flash_cha( 1524): Accessing hidden field Ljava/io/FileDescriptor;->descriptor:I (light greylist, JNI)
W/tech.flash_cha( 1524): Accessing hidden method Ljava/security/spec/ECParameterSpec;->setCurveName(Ljava/lang/String;)V (light greylist, reflection)
W/tech.flash_cha( 1524): Accessing hidden method Ldalvik/system/BlockGuard;->getThreadPolicy()Ldalvik/system/BlockGuard$Policy; (light greylist, linking)
W/tech.flash_cha( 1524): Accessing hidden method Ldalvik/system/BlockGuard$Policy;->onNetwork()V (light greylist, linking)
D/InputMethodManager( 1524): prepareNavigationBarInfo() DecorView@ff5b9fe[MainActivity]
D/InputMethodManager( 1524): getNavigationBarColor() -855310
V/InputMethodManager( 1524): Starting input: tba=co.dartontech.flash_chat ic=null mNaviBarColor -855310 mIsGetNaviBarColorSuccess true , NavVisible : true , NavTrans : false
D/InputMethodManager( 1524): startInputInner - Id : 0
I/InputMethodManager( 1524): startInputInner - mService.startInputOrWindowGainedFocus
D/InputTransport( 1524): Input channel constructed: fd=124
D/InputTransport( 1524): Input channel destroyed: fd=99
D/ViewRootImpl@82efe62[MainActivity]( 1524): stopped(true) old=false
D/SurfaceView( 1524): windowStopped(true) false io.flutter.view.FlutterView{40900f8 VFE...... .F....I. 0,0-1080,2274} of ViewRootImpl@82efe62[MainActivity]
D/SurfaceView( 1524): show() Surface(name=SurfaceView - co.dartontech.flash_chat/co.appbrewery.flash_chat.MainActivity@40900f8@0[1524])/@0xdf129d1 io.flutter.view.FlutterView{40900f8 VFE...... .F....I. 0,0-1080,2274}
D/SurfaceView( 1524): surfaceDestroyed callback.size 1 #1 io.flutter.view.FlutterView{40900f8 VFE...... .F....I. 0,0-1080,2274}
D/SurfaceView( 1524): destroy() Surface(name=SurfaceView - co.dartontech.flash_chat/co.appbrewery.flash_chat.MainActivity@40900f8@0[1524])/@0xdf129d1 io.flutter.view.FlutterView{40900f8 VFE...... .F....I. 0,0-1080,2274}
D/SurfaceView( 1524): onWindowVisibilityChanged(8) false io.flutter.view.FlutterView{40900f8 VFE...... .F....I. 0,0-1080,2274} of ViewRootImpl@82efe62[MainActivity]
D/OpenGLRenderer( 1524): eglDestroySurface = 0x6f18d0c780, 0x6f2d35f000
D/ViewRootImpl@82efe62[MainActivity]( 1524): Relayout returned: old=[0,0][1080,2400] new=[0,0][1080,2400] result=0x5 surface={false 0} changed=false
D/ViewRootImpl@82efe62[MainActivity]( 1524): MSG_WINDOW_FOCUS_CHANGED 0 1
D/InputMethodManager( 1524): prepareNavigationBarInfo() DecorView@ff5b9fe[MainActivity]
D/InputMethodManager( 1524): getNavigationBarColor() -855310

```

**Comment by iapicca** [comment]
Hi @dartonx 
from your logs the error might depend from your code
can you please provide your `flutter doctor -v` , 
your `flutter run --verbose`,
your `pubspec.yaml` 
and a reproducible minimal code sample.
Thank you

**Comment by iapicca** [comment]
Without additional information we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
