### ISSUE TITLE
StateError: Bad state: StreamSink is closed

### ISSUE THREAD

**Issue by gsusI** [flutter/flutter#56670]
Flutter crash report; please file at https://github.com/flutter/flutter/issues.

## command

flutter run --machine --target lib\main.dart -d chrome --track-widget-creation --start-paused

## exception

StateError: Bad state: StreamSink is closed

```
#0      _StreamSinkImpl.add (dart:io/io_sink.dart:156:7)
#1      _Socket.add (dart:io-patch/socket_patch.dart:1868:38)
#2      _DetachedSocket.add (dart:_http/http_impl.dart:3070:13)
#3      _ByteAdapterSink.add (dart:convert/byte_conversion.dart:60:11)
#4      ByteConversionSinkBase.addSlice (dart:convert/byte_conversion.dart:45:5)
#5      _Utf8EncoderSink.addSlice (dart:convert/utf.dart:267:13)
#6      StringConversionSinkMixin.add (dart:convert/string_conversion.dart:165:5)
#7      SseConnection._setUpListener (package:sse/src/server/sse_handler.dart:73:15)
<asynchronous suspension>
#8      new SseConnection (package:sse/src/server/sse_handler.dart:53:15)
#9      SseHandler._createSseConnection.<anonymous closure> (package:sse/src/server/sse_handler.dart:161:26)
#10     _fromHttpRequest.onHijack.<anonymous closure> (package:shelf/shelf_io.dart:146:35)
#11     _rootRunUnary (dart:async/zone.dart:1192:38)
#12     _CustomZone.runUnary (dart:async/zone.dart:1085:19)
#13     _FutureListener.handleValue (dart:async/future_impl.dart:141:18)
#14     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:682:45)
#15     Future._propagateToListeners (dart:async/future_impl.dart:711:32)
#16     Future._completeWithValue (dart:async/future_impl.dart:526:5)
#17     Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:556:7)
#18     _rootRun (dart:async/zone.dart:1184:13)
#19     _CustomZone.run (dart:async/zone.dart:1077:19)
#20     _CustomZone.runGuarded (dart:async/zone.dart:979:7)
#21     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1019:23)
#22     _microtaskLoop (dart:async/schedule_microtask.dart:43:21)
#23     _startMicrotaskLoop (dart:async/schedule_microtask.dart:52:5)
#24     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
#25     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:169:5)
```

## flutter doctor

```
[✓] Flutter (Channel beta, v1.17.0, on Microsoft Windows [Version 10.0.19041.208], locale en-GB)
    • Flutter version 1.17.0 at C:\src\flutter
    • Framework revision e6b34c2b5c (6 days ago), 2020-05-02 11:39:18 -0700
    • Engine revision 540786dd51
    • Dart version 2.8.1

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at C:\Users\user\AppData\Local\Android\sdk
    • Platform android-29, build-tools 29.0.2
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[✓] Android Studio (version 3.6)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)

[✓] VS Code (version 1.44.2)
    • VS Code at C:\Users\user\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.10.1

[✓] Connected device (2 available)
    • Chrome     • chrome     • web-javascript • Google Chrome 81.0.4044.129
    • Web Server • web-server • web-javascript • Flutter Tools

• No issues found!
```

**Comment by iapicca** [comment]
Hi @gsusI 
I see there's an open [issue](https://github.com/dart-lang/webdev/issues/943) addressing the case you described.
Please follow up on that issue,
I'm closing the current one as duplicate.
If you disagree please write in the comments
and I will reopen it.
Thank you

https://github.com/flutter/flutter/issues/54268
https://github.com/flutter/flutter/issues/54661
https://github.com/flutter/flutter/issues/54742
https://github.com/flutter/flutter/issues/55091
