### ISSUE TITLE
[proposal] Make "value" required for "DropdownMenuItem"

### ISSUE THREAD

**Issue by pedromassango** [flutter/flutter#56725]
`DropdownButtonFormField` is not showing the value provided into `value` param.

Facing this on the latest Flutter version (`1.17.0`)

## Steps to Reproduce

1. Run `flutter create bug`.
2. Run the code bellow 
3. Try to select a item in the dropdown field...

**Expected results:** The selected value should be visible to the user

**Actual results:** The first value is displayed instead

## Code

```
class MyHomePage extends StatefulWidget {
  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  String _i;

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: Text('Página Inicial')),
      body: Column(
        children: <Widget>[
          DropdownButtonFormField<String>(
            value: _i,
            onChanged: (i) {
              setState(() {
                _i = i;
              });
            },
            items: List.generate(
              10,
              (index) => DropdownMenuItem(
                child: Text('$index'),
              ),
            ),
          )
        ],
      ),
    );
  }
}
```

</details>

**Comment by pedromassango** [comment]
`onChanged ` is always returning null!

**Comment by pedromassango** [comment]
WHy this assertion if value property is just a initial value? Whould be better to remove it and use the first item as the initial value instead. This is preventing us to define a default value via value property.

```
There should be exactly one item with [DropdownButton]'s value: 1. 
Either zero or 2 or more [DropdownMenuItem]s were detected with the same value
'package:flutter/src/material/dropdown.dart':
Failed assertion: line 1463 pos 15: 'items == null || items.isEmpty || value == null ||
              items.where((DropdownMenuItem<T> item) {
                return item.value == value;
              }).length == 1'
```

**Comment by apalugniok** [comment]
The `DropdownMenuItem` needs a `value` so that we know which one to pick given `_i`:

```
(index) => DropdownMenuItem(
  value: '$index',
  child: Text('$index'),
)
```

`onChanged` is always being called with the `value` of the `DropdownMenuItem` that is tapped which in the your code is always `null`. 

The assertion is thrown because `_i` is initially `null` which matches all the `DropdownMenuItem`s you declared above as they all have a `value` of `null`.

I can't think of a use-case for not explicitly passing the `value` argument for a `DropdownMenuItem` and think it should be marked as `@required` to avoid this kind of issue.

**Comment by pedromassango** [comment]
> I can't think of a use-case for not explicitly passing the `value` argument for a `DropdownMenuItem` and think it should be marked as `@required` to avoid this kind of issue.

Definitelly. It is too easy to forget to provide `value` without being required and once it is required to this widget to function properly.

**Comment by iapicca** [comment]
Hi @pedromassango 
modifying this [code sample](https://dartpad.dev/766da0d99331dcdd18095f88dde8ea66)
seems the linter is picking up the error correctly
```dart
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) =>  MaterialApp(
    home: MyHomePage(),
  );
}

class MyHomePage extends StatefulWidget {
  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {

  static const List<int> _list = [0,1,2,3];

  int _value = _list.first;

  @override
  Widget build(BuildContext context) => Scaffold(
    body: Center(
      child: DropdownButtonFormField<int>(
        value: _value,
        icon: Icon(Icons.arrow_downward),
        iconSize: 24,
        elevation: 16,
        style: TextStyle(
            color: Colors.deepPurple
        ),
        onChanged: (
          // int newValue /// <= linter marks an error commenting this out 
        ) => setState(() => _value = newValue),
        items: [
          for (int i in _list) DropdownMenuItem(
            value: i,
            child: Text('$i'),
          )
        ],
      ),
  ),);
}
```
isn't this the case for you?
Thank you

**Comment by shihaohong** [comment]
I made a comment on https://github.com/flutter/flutter/issues/56601#issuecomment-628156659, but will paste it here since it's relevant:

I realized adding an assert that DropdownMenuItem's `value != null` would technically be breaking because users might use `null` as an actual value to display a particular `DropdownMenuItem`. For example:

```dart
DropdownButtonFormField(
  decoration: InputDecoration(labelText: 'Theme'),
  onChanged: (newValue) {
    setState(() {
      value = newValue;
    });
  },
  value: value,
  items: [
    DropdownMenuItem(
      child: Text('Dark'),
      value: 'Dark',
    ),
    DropdownMenuItem(
      child: Text('This value is null'),
      value: null,
    ),
    DropdownMenuItem(
      child: Text('Light'),
      value: 'Light',
    ),
  ],
);
```

I'm not sure if the breaking change is worth making since there are ways to prevent this from happening, and adding the assert has the potential to break an unknown number of users, but on the flip side of things, would help prevent running into this kind of problem in the future.

However, making DropdownMenuItem's `value` required seems like a valid change to make, so maybe we can have DropdownMenuItem.value be required, but not assert that it is a non-null value.

**Comment by shihaohong** [comment]
^ Once we can agree on what the next steps are regarding `assert(value != null)`, then let's proceed with the PR (https://github.com/flutter/flutter/pull/56883)

**Comment by pedromassango** [comment]
> I'm not sure if the breaking change is worth making since there are ways to prevent this from happening, and adding the assert has the potential to break an unknown number of users.

You're right,I actually didn't think about this

**Comment by abhihasabe** [comment]
firstly i am selecting dealer getting branch data, but when i am updating dealer that time crass app

_dropdownDealerList != null
                        ? Padding(
                            padding: const EdgeInsets.only(
                                left: 10, right: 10, bottom: 5),
                            child: DropdownButtonFormField<DealerBranchList>(
                              decoration: InputDecoration(labelText: 'Dealer*'),
                              isDense: true,
                              isExpanded: true,
                              value: _selectedDealer,
                              items: _dropdownDealerList,
                              onChanged: onChangeDropdownDealerListItem,
                            ),
                          )
                        : Container(),
                    _dropdownBranchList != null
                        ? Padding(
                            padding: const EdgeInsets.only(
                                left: 10, right: 10, top: 8),
                            child: DropdownButtonFormField(
                              decoration: InputDecoration(labelText: 'Branch*'),
                              isDense: true,
                              isExpanded: true,
                              value: _selectedBranch,
                              items: _dropdownBranchList,
                              onChanged: onChangeDropdowndealerBranchItem,
                            ),
                          )
                        : Container(),

**Comment by abhihasabe** [comment]
firstly i am selecting dealer getting branch data, but when i am updating dealer that time crass app

_dropdownDealerList != null
? Padding(
padding: const EdgeInsets.only(
left: 10, right: 10, bottom: 5),
child: DropdownButtonFormField(
decoration: InputDecoration(labelText: 'Dealer*'),
isDense: true,
isExpanded: true,
value: _selectedDealer,
items: _dropdownDealerList,
onChanged: onChangeDropdownDealerListItem,
),
)
: Container(),
_dropdownBranchList != null
? Padding(
padding: const EdgeInsets.only(
left: 10, right: 10, top: 8),
child: DropdownButtonFormField(
decoration: InputDecoration(labelText: 'Branch*'),
isDense: true,
isExpanded: true,
value: _selectedBranch,
items: _dropdownBranchList,
onChanged: onChangeDropdowndealerBranchItem,
),
)
: Container(),


Error :

Failed assertion: line 1463 pos 15: 'items == null || items.isEmpty || value == null ||
              items.where((DropdownMenuItem<T> item) {
                return item.value == value;
              }).length == 1'

The relevant error-causing widget was: 
  PreferencesPage file:///E:/Mahindra%20Projects/btlsager/lib/ui/Employee.dart:666:19
When the exception was thrown, this was the stack: 
#2      new DropdownButtonFormField (package:flutter/src/material/dropdown.dart:1463:15)
#3      _PreferencesPageState.build (package:btl/ui/Preferences.dart:371:36)
#4      StatefulElement.build (package:flutter/src/widgets/framework.dart:4619:28)
#5      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4502:15)
#6      StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4675:11)

**Comment by darshankawar** [comment]
Issue persists with latest master version.

<details>
<summary>flutter doctor -v</summary>

```

[✓] Flutter (Channel master, 1.27.0-9.0.pre.149, on Mac OS X 10.15.4 19E2269
    darwin-x64, locale en-GB)
    • Flutter version 1.27.0-9.0.pre.149 at
      /Users/dhs/documents/Fluttersdk/flutter
    • Framework revision 9964e8fe38 (7 hours ago), 2021-03-01 23:00:02 -0500
    • Engine revision 17f6bfc480
    • Dart version 2.13.0 (build 2.13.0-90.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
    • Android SDK at /Users/dhs/Library/Android/sdk
    • Platform android-30, build-tools 30.0.0
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[!] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.3, Build version 12C33
    ! CocoaPods 1.9.3 out of date (1.10.0 is recommended).
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin
        code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To upgrade see
      https://guides.cocoapods.org/using/getting-started.html#installation for
      instructions.

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.53.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.18.1

[✓] Connected device (4 available)
    • SM G975F (mobile)          • RZ8M802WY0X                          •
      android-arm64  • Android 10 (API 29)
    • iPhone 12 Pro Max (mobile) • A5473606-0213-4FD8-BA16-553433949729 • ios
      • com.apple.CoreSimulator.SimRuntime.iOS-14-3 (simulator)
    • macOS (desktop)            • macos                                •
      darwin-x64     • Mac OS X 10.15.4 19E2269 darwin-x64
    • Chrome (web)               • chrome                               •
      web-javascript • Google Chrome 88.0.4324.192

! Doctor found issues in 1 category.
```

</details>
