### ISSUE TITLE
 Race condition resulting in duplicate GlobalKey detected in widget tree

### ISSUE THREAD

**Issue by NiamhG** [flutter/flutter#56733]
This has happened after I upgraded. I just checked an old version on another pc (flutter 1.12.13+hotfix.9) and it works fine there. It seems to be getting some race condition with global keys. This only happens in debug mode. It works perfectly in Release.

## Steps to Reproduce

- Click on card which navigates to new screen
- New screen generates a global key and sets a widget's key to it (there are no errors at this point)
- Press back
- Click on card again

And then I get the error:

Duplicate GlobalKey detected in widget tree.

Weirdly, if I put a breakpoint at the global key creation after clicking the card the second time, then run it, it works fine and there's no error. So it seems there's some race condition, but I have absolutely no idea how to delve further into this. It's a fairly complicated part of my app.

**Expected results:** 

That the card opens as normal without error 

**Actual results:**

Duplicate GlobalKey exception

<details>
  <summary>Logs</summary>

```
[ +147 ms] I/flutter (20036): ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
[        ] I/flutter (20036): The following assertion was thrown building Form-[LabeledGlobalKey<FormState>#abdac](state:
[        ] I/flutter (20036): FormState#68547):
[        ] I/flutter (20036): 'package:flutter/src/widgets/will_pop_scope.dart': Failed assertion: line 59 pos 12: '_route ==
[        ] I/flutter (20036): ModalRoute.of(context)': is not true.
[        ] I/flutter (20036): 
[        ] I/flutter (20036): Either the assertion indicates an error in the framework itself, or we should provide substantially
[        ] I/flutter (20036): more information in this error message to help you determine and fix the underlying cause.
[        ] I/flutter (20036): In either case, please report this assertion by filing a bug on GitHub:
[        ] I/flutter (20036):   https://github.com/flutter/flutter/issues/new?template=BUG.md
[        ] I/flutter (20036): 
[        ] I/flutter (20036): The relevant error-causing widget was:
[        ] I/flutter (20036):   Form-[LabeledGlobalKey<FormState>#abdac]
[        ] I/flutter (20036):   file:///A:/AndroidProjects/flutter/my_app/lib/screens/tracked/generate_tracked_items.dart:112:17
[        ] I/flutter (20036): 
[        ] I/flutter (20036): When the exception was thrown, this was the stack:
[        ] I/flutter (20036): #2      _WillPopScopeState.didUpdateWidget (package:flutter/src/widgets/will_pop_scope.dart:59:12)
[        ] I/flutter (20036): #3      StatefulElement.update (package:flutter/src/widgets/framework.dart:4690:58)
[        ] I/flutter (20036): #4      Element.updateChild (package:flutter/src/widgets/framework.dart:3201:15)
[        ] I/flutter (20036): #5      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4527:16)
[        ] I/flutter (20036): #6      StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4675:11)
[        ] I/flutter (20036): #7      Element.rebuild (package:flutter/src/widgets/framework.dart:4218:5)
[        ] I/flutter (20036): #8      StatefulElement.update (package:flutter/src/widgets/framework.dart:4707:5)
[        ] I/flutter (20036): #9      Element.updateChild (package:flutter/src/widgets/framework.dart:3201:15)
[        ] I/flutter (20036): #10     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:5837:14)
[        ] I/flutter (20036): #11     Element.updateChild (package:flutter/src/widgets/framework.dart:3201:15)
[        ] I/flutter (20036): #12     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:5837:14)
[        ] I/flutter (20036): #13     Element.updateChild (package:flutter/src/widgets/framework.dart:3201:15)
[        ] I/flutter (20036): #14     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4527:16)
[        ] I/flutter (20036): #15     Element.rebuild (package:flutter/src/widgets/framework.dart:4218:5)
[        ] I/flutter (20036): #16     StatelessElement.update (package:flutter/src/widgets/framework.dart:4583:5)
[        ] I/flutter (20036): #17     Element.updateChild (package:flutter/src/widgets/framework.dart:3201:15)
[        ] I/flutter (20036): #18     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4527:16)
[        ] I/flutter (20036): #19     Element.rebuild (package:flutter/src/widgets/framework.dart:4218:5)
[        ] I/flutter (20036): #20     ProxyElement.update (package:flutter/src/widgets/framework.dart:4862:5)
[        ] I/flutter (20036): #21     Element.updateChild (package:flutter/src/widgets/framework.dart:3201:15)
[        ] I/flutter (20036): #22     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4527:16)
[        ] I/flutter (20036): #23     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4675:11)
[        ] I/flutter (20036): #24     Element.rebuild (package:flutter/src/widgets/framework.dart:4218:5)
[        ] I/flutter (20036): #25     StatefulElement.update (package:flutter/src/widgets/framework.dart:4707:5)
[        ] I/flutter (20036): #26     Element.updateChild (package:flutter/src/widgets/framework.dart:3201:15)
[        ] I/flutter (20036): #27     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4527:16)
[        ] I/flutter (20036): #28     Element.rebuild (package:flutter/src/widgets/framework.dart:4218:5)
[        ] I/flutter (20036): #29     StatelessElement.update (package:flutter/src/widgets/framework.dart:4583:5)
[        ] I/flutter (20036): #30     Element.updateChild (package:flutter/src/widgets/framework.dart:3201:15)
[        ] I/flutter (20036): #31     SliverMultiBoxAdaptorElement.updateChild (package:flutter/src/widgets/sliver.dart:1162:36)
[        ] I/flutter (20036): #32     SliverMultiBoxAdaptorElement.performRebuild.processElement (package:flutter/src/widgets/sliver.dart:1080:34)
[        ] I/flutter (20036): #33     Iterable.forEach (dart:core/iterable.dart:279:30)
[        ] I/flutter (20036): #34     SliverMultiBoxAdaptorElement.performRebuild (package:flutter/src/widgets/sliver.dart:1120:24)
[        ] I/flutter (20036): #35     SliverMultiBoxAdaptorElement.update (package:flutter/src/widgets/sliver.dart:1050:7)
[        ] I/flutter (20036): #36     Element.updateChild (package:flutter/src/widgets/framework.dart:3201:15)
[        ] I/flutter (20036): #37     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:5837:14)
[        ] I/flutter (20036): #38     Element.updateChild (package:flutter/src/widgets/framework.dart:3201:15)
[        ] I/flutter (20036): #39     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4527:16)
[        ] I/flutter (20036): #40     Element.rebuild (package:flutter/src/widgets/framework.dart:4218:5)
[        ] I/flutter (20036): #41     StatelessElement.update (package:flutter/src/widgets/framework.dart:4583:5)
[        ] I/flutter (20036): #42     Element.updateChild (package:flutter/src/widgets/framework.dart:3201:15)
[        ] I/flutter (20036): #43     RenderObjectElement.updateChildren (package:flutter/src/widgets/framework.dart:5522:32)
[        ] I/flutter (20036): #44     MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:5957:17)
[        ] I/flutter (20036): #45     _ViewportElement.update (package:flutter/src/widgets/viewport.dart:202:11)
[        ] I/flutter (20036): #46     Element.updateChild (package:flutter/src/widgets/framework.dart:3201:15)
[        ] I/flutter (20036): #47     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:5837:14)
[        ] I/flutter (20036): #48     Element.updateChild (package:flutter/src/widgets/framework.dart:3201:15)
[        ] I/flutter (20036): #49     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:5837:14)
[        ] I/flutter (20036): #50     Element.updateChild (package:flutter/src/widgets/framework.dart:3201:15)
[        ] I/flutter (20036): #51     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:5837:14)
[   +2 ms] I/flutter (20036): #52     Element.updateChild (package:flutter/src/widgets/framework.dart:3201:15)
[        ] I/flutter (20036): #53     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4527:16)
[        ] I/flutter (20036): #54     Element.rebuild (package:flutter/src/widgets/framework.dart:4218:5)
[        ] I/flutter (20036): #55     StatelessElement.update (package:flutter/src/widgets/framework.dart:4583:5)
[        ] I/flutter (20036): #56     Element.updateChild (package:flutter/src/widgets/framework.dart:3201:15)
[        ] I/flutter (20036): #57     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:5837:14)
[        ] I/flutter (20036): #58     Element.updateChild (package:flutter/src/widgets/framework.dart:3201:15)
[        ] I/flutter (20036): #59     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4527:16)
[        ] I/flutter (20036): #60     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4675:11)
[        ] I/flutter (20036): #61     Element.rebuild (package:flutter/src/widgets/framework.dart:4218:5)
[        ] I/flutter (20036): #62     StatefulElement.update (package:flutter/src/widgets/framework.dart:4707:5)
[        ] I/flutter (20036): #63     Element.updateChild (package:flutter/src/widgets/framework.dart:3201:15)
[        ] I/flutter (20036): #64     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:5837:14)
[        ] I/flutter (20036): #65     Element.updateChild (package:flutter/src/widgets/framework.dart:3201:15)
[        ] I/flutter (20036): #66     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4527:16)
[   +2 ms] I/flutter (20036): #67     Element.rebuild (package:flutter/src/widgets/framework.dart:4218:5)
[        ] I/flutter (20036): #68     StatelessElement.update (package:flutter/src/widgets/framework.dart:4583:5)
[        ] I/flutter (20036): #69     Element.updateChild (package:flutter/src/widgets/framework.dart:3201:15)
[        ] I/flutter (20036): #70     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4527:16)
[        ] I/flutter (20036): #71     Element.rebuild (package:flutter/src/widgets/framework.dart:4218:5)
[        ] I/flutter (20036): #72     ProxyElement.update (package:flutter/src/widgets/framework.dart:4862:5)
[   +1 ms] I/flutter (20036): #73     Element.updateChild (package:flutter/src/widgets/framework.dart:3201:15)
[   +1 ms] I/flutter (20036): #74     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:5837:14)
[   +1 ms] I/flutter (20036): #75     Element.updateChild (package:flutter/src/widgets/framework.dart:3201:15)
[        ] I/flutter (20036): #76     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:5837:14)
[   +1 ms] I/flutter (20036): #77     Element.updateChild (package:flutter/src/widgets/framework.dart:3201:15)
[        ] I/flutter (20036): #78     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:5837:14)
[        ] I/flutter (20036): #79     Element.updateChild (package:flutter/src/widgets/framework.dart:3201:15)
[        ] I/flutter (20036): #80     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:5837:14)
[        ] I/flutter (20036): #81     Element.updateChild (package:flutter/src/widgets/framework.dart:3201:15)
[        ] I/flutter (20036): #82     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4527:16)
[        ] I/flutter (20036): #83     Element.rebuild (package:flutter/src/widgets/framework.dart:4218:5)
[        ] I/flutter (20036): #84     StatelessElement.update (package:flutter/src/widgets/framework.dart:4583:5)
[        ] I/flutter (20036): #85     Element.updateChild (package:flutter/src/widgets/framework.dart:3201:15)
[        ] I/flutter (20036): #86     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4527:16)
[        ] I/flutter (20036): #87     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4675:11)
[        ] I/flutter (20036): #88     Element.rebuild (package:flutter/src/widgets/framework.dart:4218:5)
[        ] I/flutter (20036): #89     StatefulElement.update (package:flutter/src/widgets/framework.dart:4707:5)
[        ] I/flutter (20036): #90     Element.updateChild (package:flutter/src/widgets/framework.dart:3201:15)
[   +1 ms] I/flutter (20036): #91     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4527:16)
[        ] I/flutter (20036): #92     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4675:11)
[        ] I/flutter (20036): #93     Element.rebuild (package:flutter/src/widgets/framework.dart:4218:5)
[        ] I/flutter (20036): #94     StatefulElement.update (package:flutter/src/widgets/framework.dart:4707:5)
[        ] I/flutter (20036): #95     Element.updateChild (package:flutter/src/widgets/framework.dart:3201:15)
[        ] I/flutter (20036): #96     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4527:16)
[        ] I/flutter (20036): #97     Element.rebuild (package:flutter/src/widgets/framework.dart:4218:5)
[        ] I/flutter (20036): #98     StatelessElement.update (package:flutter/src/widgets/framework.dart:4583:5)
[        ] I/flutter (20036): #99     Element.updateChild (package:flutter/src/widgets/framework.dart:3201:15)
[        ] I/flutter (20036): #100    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4527:16)
[        ] I/flutter (20036): #101    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4675:11)
[        ] I/flutter (20036): #102    Element.rebuild (package:flutter/src/widgets/framework.dart:4218:5)
[        ] I/flutter (20036): #103    StatefulElement.update (package:flutter/src/widgets/framework.dart:4707:5)
[   +1 ms] I/flutter (20036): #104    Element.updateChild (package:flutter/src/widgets/framework.dart:3201:15)
[   +1 ms] I/flutter (20036): #105    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4527:16)
[        ] I/flutter (20036): #106    Element.rebuild (package:flutter/src/widgets/framework.dart:4218:5)
[        ] I/flutter (20036): #107    ProxyElement.update (package:flutter/src/widgets/framework.dart:4862:5)
[        ] I/flutter (20036): #108    Element.updateChild (package:flutter/src/widgets/framework.dart:3201:15)
[   +1 ms] I/flutter (20036): #109    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4527:16)
[        ] I/flutter (20036): #110    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4675:11)
[   +1 ms] I/flutter (20036): #111    Element.rebuild (package:flutter/src/widgets/framework.dart:4218:5)
[        ] I/flutter (20036): #112    BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2627:33)
[        ] I/flutter (20036): #113    WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:883:20)
[        ] I/flutter (20036): #114    RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:284:5)
[        ] I/flutter (20036): #115    SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1113:15)
[        ] I/flutter (20036): #116    SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1052:9)
[   +2 ms] I/flutter (20036): #117    SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:968:5)
[   +4 ms] I/flutter (20036): #121    _invoke (dart:ui/hooks.dart:261:10)
[   +2 ms] I/flutter (20036): #122    _drawFrame (dart:ui/hooks.dart:219:3)
[        ] I/flutter (20036): (elided 5 frames from class _AssertionError and dart:async)
[        ] I/flutter (20036): 
[   +3 ms] I/flutter (20036): ════════════════════════════════════════════════════════════════════════════════════════════════════
[        ] I/flutter (20036): Flutter error caught by Crashlytics plugin:
[        ] I/flutter (20036): ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
[        ] I/flutter (20036): The following assertion was thrown building SingleChildScrollView:
[        ] I/flutter (20036): 'package:flutter/src/widgets/framework.dart': Failed assertion: line 5857 pos 12:
[        ] I/flutter (20036): 'renderObject.child == child': is not true.
[        ] I/flutter (20036): 
[   +2 ms] I/flutter (20036): Either the assertion indicates an error in the framework itself, or we should provide substantially
[        ] I/flutter (20036): more information in this error message to help you determine and fix the underlying cause.
[        ] I/flutter (20036): In either case, please report this assertion by filing a bug on GitHub:
[   +2 ms] I/flutter (20036):   https://github.com/flutter/flutter/issues/new?template=BUG.md
[        ] I/flutter (20036): 
[   +1 ms] I/flutter (20036): The relevant error-causing widget was:
[        ] I/flutter (20036):   SingleChildScrollView
[        ] I/flutter (20036):   file:///A:/AndroidProjects/flutter/my_app/lib/screens/tracked/tracked_item.dart:13:12
[        ] I/flutter (20036): 
[        ] I/flutter (20036): When the exception was thrown, this was the stack:
[        ] I/flutter (20036): #2      SingleChildRenderObjectElement.removeChildRenderObject (package:flutter/src/widgets/framework.dart:5857:12)
[        ] I/flutter (20036): #3      RenderObjectElement.detachRenderObject (package:flutter/src/widgets/framework.dart:5688:36)
[        ] I/flutter (20036): #4      Element.detachRenderObject.<anonymous closure> (package:flutter/src/widgets/framework.dart:3346:13)
[        ] I/flutter (20036): #5      ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4556:14)
[        ] I/flutter (20036): Flutter error caught by Crashlytics plugin:
[ +328 ms] I/flutter (20036): Flutter error caught by Crashlytics plugin:
[ +608 ms] I/flutter (20036): #6      Element.detachRenderObject (package:flutter/src/widgets/framework.dart:3345:5)
[        ] I/flutter (20036): #7      Element.detachRenderObject.<anonymous closure> (package:flutter/src/widgets/framework.dart:3346:13)
[        ] I/flutter (20036): #8      ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4556:14)
[        ] I/flutter (20036): #9      Element.detachRenderObject (package:flutter/src/widgets/framework.dart:3345:5)
[        ] I/flutter (20036): #10     Element.detachRenderObject.<anonymous closure> (package:flutter/src/widgets/framework.dart:3346:13)
[        ] I/flutter (20036): #11     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4556:14)
[        ] I/flutter (20036): #12     Element.detachRenderObject (package:flutter/src/widgets/framework.dart:3345:5)
[        ] I/flutter (20036): #13     Element.detachRenderObject.<anonymous closure> (package:flutter/src/widgets/framework.dart:3346:13)
[   +1 ms] I/flutter (20036): #14     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4556:14)
[        ] I/flutter (20036): #15     Element.detachRenderObject (package:flutter/src/widgets/framework.dart:3345:5)
[        ] I/flutter (20036): #16     Element.deactivateChild (package:flutter/src/widgets/framework.dart:3481:11)
[        ] I/flutter (20036): #17     Element.updateChild (package:flutter/src/widgets/framework.dart:3209:9)
[        ] I/flutter (20036): #18     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4527:16)
[        ] I/flutter (20036): #19     Element.rebuild (package:flutter/src/widgets/framework.dart:4218:5)
[   +2 ms] I/flutter (20036): #20     StatelessElement.update (package:flutter/src/widgets/framework.dart:4583:5)
[   +1 ms] I/flutter (20036): #21     Element.updateChild (package:flutter/src/widgets/framework.dart:3201:15)
[        ] I/flutter (20036): #22     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4527:16)
[        ] I/flutter (20036): #23     Element.rebuild (package:flutter/src/widgets/framework.dart:4218:5)
[        ] I/flutter (20036): #24     StatelessElement.update (package:flutter/src/widgets/framework.dart:4583:5)
[        ] I/flutter (20036): #25     Element.updateChild (package:flutter/src/widgets/framework.dart:3201:15)
[        ] I/flutter (20036): #26     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4527:16)
[        ] I/flutter (20036): #27     Element.rebuild (package:flutter/src/widgets/framework.dart:4218:5)
[        ] I/flutter (20036): #28     ProxyElement.update (package:flutter/src/widgets/framework.dart:4862:5)
[        ] I/flutter (20036): #29     Element.updateChild (package:flutter/src/widgets/framework.dart:3201:15)
[        ] I/flutter (20036): #30     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4527:16)
[        ] I/flutter (20036): #31     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4675:11)
[        ] I/flutter (20036): #32     Element.rebuild (package:flutter/src/widgets/framework.dart:4218:5)
[        ] I/flutter (20036): #33     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2627:33)
[        ] I/flutter (20036): #34     WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:883:20)
[        ] I/flutter (20036): #35     RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:284:5)
[        ] I/flutter (20036): #36     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1113:15)
[        ] I/flutter (20036): #37     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1052:9)
[        ] I/flutter (20036): #38     SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:968:5)
[        ] I/flutter (20036): #42     _invoke (dart:ui/hooks.dart:261:10)
[        ] I/flutter (20036): #43     _drawFrame (dart:ui/hooks.dart:219:3)
[        ] I/flutter (20036): (elided 5 frames from class _AssertionError and dart:async)
[        ] I/flutter (20036): 
[        ] I/flutter (20036): ════════════════════════════════════════════════════════════════════════════════════════════════════
[        ] I/flutter (20036): ══╡ EXCEPTION CAUGHT BY SCHEDULER LIBRARY ╞═════════════════════════════════════════════════════════
[        ] I/flutter (20036): The following assertion was thrown during a scheduler callback:
[        ] I/flutter (20036): 'package:flutter/src/widgets/framework.dart': Failed assertion: line 2625 pos 16:
[        ] I/flutter (20036): '!_dirtyElements[index]._active || _dirtyElements[index]._debugIsInScope(context)': is not true.
[        ] I/flutter (20036): 
[        ] I/flutter (20036): Either the assertion indicates an error in the framework itself, or we should provide substantially
[        ] I/flutter (20036): more information in this error message to help you determine and fix the underlying cause.
[        ] I/flutter (20036): In either case, please report this assertion by filing a bug on GitHub:
[        ] I/flutter (20036):   https://github.com/flutter/flutter/issues/new?template=BUG.md
[        ] I/flutter (20036): 
[        ] I/flutter (20036): When the exception was thrown, this was the stack:
[        ] I/flutter (20036): #2      BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2625:16)
[        ] I/flutter (20036): #3      WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:883:20)
[        ] I/flutter (20036): #4      RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:284:5)
[        ] I/flutter (20036): #5      SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1113:15)
[        ] I/flutter (20036): #6      SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1052:9)
[        ] I/flutter (20036): #7      SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:968:5)
[        ] I/flutter (20036): #11     _invoke (dart:ui/hooks.dart:261:10)
[        ] I/flutter (20036): #12     _drawFrame (dart:ui/hooks.dart:219:3)
[        ] I/flutter (20036): (elided 5 frames from class _AssertionError and dart:async)
[        ] I/flutter (20036): ════════════════════════════════════════════════════════════════════════════════════════════════════
[        ] I/flutter (20036): ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
[   +1 ms] I/flutter (20036): The following assertion was thrown while finalizing the widget tree:
[        ] I/flutter (20036): Duplicate GlobalKey detected in widget tree.
[        ] I/flutter (20036): The following GlobalKey was specified multiple times in the widget tree. This will lead to parts of
[        ] I/flutter (20036): the widget tree being truncated unexpectedly, because the second time a key is seen, the previous
[        ] I/flutter (20036): instance is moved to the new location. The key was:
[        ] I/flutter (20036): - [LabeledGlobalKey<TrackedItemsState>#fe611]
[        ] I/flutter (20036): This was determined by noticing that after the widget with the above global key was moved out of its
[        ] I/flutter (20036): respective previous parents, those previous parents never updated during this frame, meaning that
[        ] I/flutter (20036): they either did not update at all or updated before the widget was moved, in either case implying
[        ] I/flutter (20036): that they still think that they should have a child with that global key.
[        ] I/flutter (20036): The specific parents that did not update after having one or more children forcibly removed due to
[        ] I/flutter (20036): GlobalKey reparenting are:
[        ] I/flutter (20036): - Column(direction: vertical, mainAxisAlignment: start, crossAxisAlignment: center, renderObject:
[        ] I/flutter (20036): RenderFlex#a28de relayoutBoundary=up15)
[        ] I/flutter (20036):   _EffectiveTickerMode(effective mode: enabled)
[        ] I/flutter (20036): A GlobalKey can only be specified on one widget at a time in the widget tree.
[        ] I/flutter (20036): 
[        ] I/flutter (20036): When the exception was thrown, this was the stack:
[   +5 ms] I/flutter (20036): #0      BuildOwner.finalizeTree.<anonymous closure> (package:flutter/src/widgets/framework.dart:2774:15)
[        ] I/flutter (20036): #1      BuildOwner.finalizeTree (package:flutter/src/widgets/framework.dart:2799:8)
[        ] I/flutter (20036): #2      WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:885:18)
[        ] I/flutter (20036): #3      RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:284:5)
[        ] I/flutter (20036): #4      SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1113:15)
[        ] I/flutter (20036): #5      SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1052:9)
[        ] I/flutter (20036): #6      SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:968:5)
[        ] I/flutter (20036): #10     _invoke (dart:ui/hooks.dart:261:10)
[        ] I/flutter (20036): #11     _drawFrame (dart:ui/hooks.dart:219:3)
[        ] I/flutter (20036): (elided 3 frames from dart:async)
[   +1 ms] I/flutter (20036): ════════════════════════════════════════════════════════════════════════════════════════════════════

```

```
flutter doctor -v
[√] Flutter (Channel stable, v1.17.0, on Microsoft Windows [Version 10.0.18362.778], locale en-GB)
    • Flutter version 1.17.0 at A:\src\flutter
    • Framework revision e6b34c2b5c (6 days ago), 2020-05-02 11:39:18 -0700
    • Engine revision 540786dd51
    • Dart version 2.8.1


[!] Android toolchain - develop for Android devices (Android SDK version 29.0.0)
    • Android SDK at A:\AppData\Android
    • Platform android-29, build-tools 29.0.0
    • ANDROID_HOME = A:\AppData\Android
    • Java binary at: A:\Programs\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses

[√] Android Studio (version 3.6)
    • Android Studio at A:\Programs\Android\Android Studio
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)

[!] IntelliJ IDEA Community Edition (version 2018.1)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2018.1.5
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.dev/intellij-setup/#installing-the-plugins

[!] IntelliJ IDEA Community Edition (version 2019.2)
    • IntelliJ at A:\Programs\IntelliJ IDEA Community Edition 2019.2
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.dev/intellij-setup/#installing-the-plugins

[√] Connected device (1 available)
    • CLT L09 • LCL7N18B30006401 • android-arm64 • Android 9 (API 28)

! Doctor found issues in 3 categories.
```

</details>

**Comment by iapicca** [comment]
Hi @NiamhG 
I just run this code

```dart
import 'package:flutter/material.dart';

/// adapted from https://gist.github.com/iapicca/5de7b59c1f1d4776b389f8db4375a00c

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {

  @override
  Widget build(BuildContext context) => MaterialApp(
    home: PreHomePage(),
  );
}

class PreHomePage extends StatelessWidget {
  const PreHomePage({Key key}) : super(key: key);

  @override
  Widget build(BuildContext context) => Material(
    child: Center(
      child: MaterialButton(
        color: Colors.greenAccent,
        child: Icon(Icons.fast_forward,),
        onPressed: () => Navigator.of(context).push(
          MaterialPageRoute(
            builder: (context) => MyHomePage(),
          ),
        ),
      ),
    ),
  );
}

class MyHomePage extends StatefulWidget {
  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  final GlobalKey<_CounterWidgetState> _counterKey = GlobalKey();

  @override
  Widget build(BuildContext context) => Scaffold(
    appBar: AppBar(),
    body: CounterWidget(key: _counterKey,),
    floatingActionButton: FloatingActionButton(
      child: Icon(Icons.fast_forward,),
      onPressed: () => Navigator.of(context).push(
        MaterialPageRoute(
          builder: (context) => SecondPage(
            counterKey: _counterKey,
          ),
        ),
      ),
    ),
  );
}

class CounterWidget extends StatefulWidget {
  const CounterWidget({Key key}) : super(key: key);

  @override
  _CounterWidgetState createState() => _CounterWidgetState();
}

class _CounterWidgetState extends State<CounterWidget> {
  int counter = 0;
  @override
  Widget build(BuildContext context) => Center(
      child: Container(
        width: MediaQuery.of(context).size.width * .5,
        child: ListTile(
          title: Text('$counter'),
          trailing: MaterialButton(
            color: Colors.blueAccent,
            child: Icon(Icons.add),
            onPressed: () => 
              setState(() => ++counter,),
          ),
        ),
      ),
    );
  }


class SecondPage extends StatefulWidget {
  final GlobalKey<_CounterWidgetState> counterKey;
  SecondPage({this.counterKey});

  @override
  _SecondPageState createState() => _SecondPageState();
}

class _SecondPageState extends State<SecondPage> {
  @override
  Widget build(BuildContext context) => Scaffold(
    backgroundColor: Colors.greenAccent[200],
    appBar: AppBar(
      title: const Text('Second Page'),
    ),
    body: Center(
      child: Text('${widget.counterKey.currentState.counter}'),
    ),
    floatingActionButton: FloatingActionButton(
      child: Icon(Icons.add),
      onPressed: () => setState(() => ++widget.counterKey.currentState.counter,),
    ),
  );
}
```

with the latest stable

```console
[✓] Flutter (Channel stable, v1.17.0, on Mac OS X 10.15.4 19E287, locale en-EE)
    • Flutter version 1.17.0 at /Users/nevercode/development/flutter
    • Framework revision e6b34c2b5c (9 days ago), 2020-05-02 11:39:18 -0700
    • Engine revision 540786dd51
    • Dart version 2.8.1


[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/nevercode/Library/Android/sdk
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.3.1, Build version 11C504
    • CocoaPods version 1.9.0

[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)

[✓] VS Code
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.10.1

[!] Connected device
    ! No devices available

! Doctor found issues in 1 category.
```

it seems to work as intended,
if this code doesn't represent the issue 
please provide a reproducible minimal code sample
Thank you

**Comment by NiamhG** [comment]
Hi,

I refactored the offending piece of code to have a better state management rather than the hot mess I was doing before. After upgrading now everything seems to work fine. 

Thanks for your time anyway!

**Comment by exeptionerror** [comment]
All Possible solution added [[Solved] Duplicate GlobalKey detected in widget tree](https://fluttercorner.com/duplicate-globalkey-detected-in-widget-tree/)
