### ISSUE TITLE
Cannot run my project with android device using Flutter v1.17.0

### ISSUE THREAD

**Issue by cuong1112035** [flutter/flutter#56764]
My project worked well with previous Flutter stable versions. But after upgrade to Flutter v1.17.0, I cannot run my project in debug mode on my android device any more (it works well on my ios device). I'm using android studio in development and I'm sure that my android device has enough space on disk.
Please help me.

My console logs: 
```
Launching lib/main.dart on SM A107F in debug mode...
Running Gradle task 'assembleDebug'...
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
/Applications/flutter/.pub-cache/hosted/pub.dartlang.org/shared_preferences-0.5.6+1/android/src/main/java/io/flutter/plugins/sharedpreferences/SharedPreferencesPlugin.java:25: warning: [deprecation] getFlutterEngine() in FlutterPluginBinding has been deprecated
    setupChannel(binding.getFlutterEngine().getDartExecutor(), binding.getApplicationContext());
                        ^
1 warning
FileSystemException: Cannot copy file to '/Volumes/Data/BT Flutter/39 Packages/15 google_maps_flutter/build/app/outputs/apk/app.apk', path = '/Volumes/Data/BT Flutter/39 Packages/15 google_maps_flutter/build/app/outputs/apk/debug/app-debug.apk' (OS Error: Result too large, errno = 34)
```

flutter doctor:
```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, v1.17.0, on Mac OS X 10.15.4 19E287, locale en-VN)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 11.3.1)
[✓] Android Studio (version 3.6)
[!] VS Code (version 1.44.2)
    ✗ Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter
[✓] Connected device (2 available)

! Doctor found issues in 1 category.
```

**Comment by EArminjon** [comment]
Try rm -rf on build directory, then flutter clean and try again ?

**Comment by cuong1112035** [comment]
I did try to `flutter clean` many times yesterday but still got the error. Today, I don't know why and how but I can run my project now

**Comment by cuong1112035** [comment]
I get the "No space left on device" again on ios simulator when running another project
```
Waiting for another flutter command to release the startup lock...
Launching lib/main.dart on iPhone 11 Pro Max in debug mode...
Running pod install...                                              1.4s
CocoaPods' output:
↳

    [!] Invalid `Podfile` file: No space left on device - write.

     #  from /Volumes/Data/BT Flutter/43 Persistent Store/1 hive (NoSQL)/ios/Podfile:57
     #  -------------------------------------------
     #      unless File.exist?(copied_framework_path)
     >        FileUtils.cp_r(File.join(cached_framework_dir, 'Flutter.framework'), copied_flutter_dir)
     #      end
     #  -------------------------------------------

    /Library/Ruby/Gems/2.6.0/gems/cocoapods-core-1.9.0/lib/cocoapods-core/podfile.rb:301:in `rescue in block in from_ruby'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-core-1.9.0/lib/cocoapods-core/podfile.rb:295:in `block in from_ruby'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-core-1.9.0/lib/cocoapods-core/podfile.rb:50:in `instance_eval'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-core-1.9.0/lib/cocoapods-core/podfile.rb:50:in `initialize'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-core-1.9.0/lib/cocoapods-core/podfile.rb:293:in `new'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-core-1.9.0/lib/cocoapods-core/podfile.rb:293:in `from_ruby'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-core-1.9.0/lib/cocoapods-core/podfile.rb:259:in `from_file'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.0/lib/cocoapods/config.rb:200:in `podfile'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.0/lib/cocoapods/command.rb:150:in `verify_podfile_exists!'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.0/lib/cocoapods/command/install.rb:46:in `run'
    /Library/Ruby/Gems/2.6.0/gems/claide-1.0.3/lib/claide/command.rb:334:in `run'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.0/lib/cocoapods/command.rb:52:in `run'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.0/bin/pod:55:in `<top (required)>'
    /usr/local/bin/pod:23:in `load'
    /usr/local/bin/pod:23:in `<main>'

Error running pod install
Error launching application on iPhone 11 Pro Max.
```

**Comment by EArminjon** [comment]
Hum, 

Maybe app too large or your computer didn't have enough space? You can try to determine app size (if you see an unexpected result...)

**Comment by cuong1112035** [comment]
> Hum,
> 
> Maybe app too large or your computer didn't have enough space? You can try to determine app size (if you see an unexpected result...)

You are right, my macbook's hard disk is broken, I will close this issue. Thanks for your help
