### ISSUE TITLE
[tool_crash] FileSystemException: Creation failed, OS Error: L’étiquette présente dans le tampon du point d’analyse n’est pas valide., errno = 4393

### ISSUE THREAD

**Issue by phandrieu** [flutter/flutter#56775]
## Command
```
flutter run -d chrome
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
FileSystemException: Creation failed, OS Error: L’étiquette présente dans le tampon du point d’analyse n’est pas valide.
, errno = 4393
```
#0      _Directory.createSync (dart:io/directory_impl.dart:133:7)
#1      ForwardingDirectory.createSync (package:file/src/forwarding/forwarding_directory.dart:22:16)
#2      ForwardingDirectory.createSync (package:file/src/forwarding/forwarding_directory.dart:22:16)
#3      writeBundle.<anonymous closure> (package:flutter_tools/src/bundle.dart:234:21)
<asynchronous suspension>
#4      writeBundle.<anonymous closure> (package:flutter_tools/src/bundle.dart)
#5      MappedIterator.moveNext (dart:_internal/iterable.dart:392:20)
#6      Future.wait (dart:async/future.dart:401:26)
#7      writeBundle (package:flutter_tools/src/bundle.dart:224:16)
#8      WebDevFS.update (package:flutter_tools/src/build_runner/devfs_web.dart:735:15)
#9      _ResidentWebRunner._updateDevFS (package:flutter_tools/src/build_runner/resident_web_runner.dart:628:54)
#10     _rootRunUnary (dart:async/zone.dart:1198:47)
#11     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
#12     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
#13     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
#14     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
#15     Future._completeWithValue (dart:async/future_impl.dart:529:5)
#16     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:40:15)
#17     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:311:13)
#18     _ResidentWebRunner._generateEntrypoint (package:flutter_tools/src/build_runner/resident_web_runner.dart)
#19     _rootRunUnary (dart:async/zone.dart:1198:47)
#20     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
#21     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
#22     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
#23     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
```
```
[✓] Flutter (Channel master, 1.19.0-1.0.pre.21, on Microsoft Windows [version 10.0.19619.1000], locale fr-FR)
    • Flutter version 1.19.0-1.0.pre.21 at C:\tools\flutter
    • Framework revision f5d2c8c770 (12 hours ago), 2020-05-08 17:35:40 -0700
    • Engine revision 9b905d3f03
    • Dart version 2.9.0 (build 2.9.0-7.0.dev 617bc54b71)

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at C:\Users\Paul-Henri\AppData\Local\Android\sdk
    • Platform android-29, build-tools 29.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[✓] Visual Studio - develop for Windows (Visual Studio Enterprise 2019 16.5.4)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise
    • Visual Studio Enterprise 2019 version 16.5.30011.22

[✓] Android Studio (version 3.6)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)

[✓] VS Code (version 1.45.0)
    • VS Code at C:\Users\Paul-Henri\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.10.1

[✓] Connected device (3 available)
    • Windows    • Windows    • windows-x64    • Microsoft Windows [version 10.0.19619.1000]
    • Web Server • web-server • web-javascript • Flutter Tools
    • Chrome     • chrome     • web-javascript • Google Chrome 81.0.4044.138

• No issues found!

```

## Flutter Application Metadata
**Type**: app
**Version**: 1.0.0+1
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: master
**Creation framework version**: f5d2c8c77009f0a121da655c71d35927042808af

**Comment by TahaTesser** [comment]
Hi @phandrieu 
can you please provide your complete `flutter run --verbose`?
Also, to better address the issue, would be helpful if you could post a minimal code sample to reproduce the problem
Thank you

**Comment by zanderso** [comment]
Windows error 4393: 'L’étiquette présente dans le tampon du point d’analyse n’est pas valide.' -> 'The tag present in the reparse point buffer is invalid.'

It looks like the tool is stumbling on a windows 'symlink' that it or the Dart VM doesn't understand. @jonahwilliams does the web build create symlinks? Could it get tripped up by a stray symlink in a project's source tree?

**Comment by jonahwilliams** [comment]
The web build does not create symlinks, no idea what causes this

**Comment by jonahwilliams** [comment]
According to some internet searches, this could be caused by a partially synced one-drive folder, but no further hints
