### ISSUE TITLE
Is it possible to set my own JDK, say 1.11 instead of 1.8 for flutter?

### ISSUE THREAD

**Issue by jiapei100** [flutter/flutter#56798]
It looks like android-studio comes with its own JRE 1.8. Without using this, it looks I won't be able to set **Android SDK Manager licenses**.

```console
~ > flutter doctor 
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel master, 1.18.0-13.0.pre, on Linux, locale en_CA.UTF-8)
[!] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    ✗ Android license status unknown.
      Try re-installing or updating your Android SDK Manager.
      See https://developer.android.com/studio/#downloads or visit visit https://flutter.dev/docs/get-started/install/linux#android-setup for detailed instructions.
[✓] Android Studio (version 3.6)
[✓] VS Code (version 1.45.0)
[!] Connected device
    ! No devices available

! Doctor found issues in 2 categories.
```

```console
/o/a/S/t/bin> ./sdkmanager --licenses
Exception in thread "main" java.lang.NoClassDefFoundError: javax/xml/bind/annotation/XmlSchema
	at com.android.repository.api.SchemaModule$SchemaModuleVersion.<init>(SchemaModule.java:156)
	at com.android.repository.api.SchemaModule.<init>(SchemaModule.java:75)
	at com.android.sdklib.repository.AndroidSdkHandler.<clinit>(AndroidSdkHandler.java:81)
	at com.android.sdklib.tool.sdkmanager.SdkManagerCli.main(SdkManagerCli.java:73)
	at com.android.sdklib.tool.sdkmanager.SdkManagerCli.main(SdkManagerCli.java:48)
Caused by: java.lang.ClassNotFoundException: javax.xml.bind.annotation.XmlSchema
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	... 5 more
```

That is somewhat, **NOT free** enough... Can we just **NOT** using **jre 1.8** ?

Cheers
Pei

**Comment by jonahwilliams** [comment]
If you want to build for Android you need the Android SDK, and the Android sdkmanager requires 1.8
