### ISSUE TITLE
Unhandled Exception: Invalid argument(s) in iPhone

### ISSUE THREAD

**Issue by wann2** [flutter/flutter#56815]
pubspec.yaml
```yaml
version: 2.1.60+20160
```
Info.plist
```plist
<key>CFBundleShortVersionString</key>
<string>2.1.60</string>
<key>CFBundleVersion</key>
<string>20160</string>

```
iPhone get the below error.

```dart
Future<void> _initPackageInfo() async {
        final PackageInfo info = await PackageInfo.fromPlatform();
        setState(() {
            _packageInfo = info;
        });
        print('App name: ' + _packageInfo.appName); <- error
        print('Package name: ' + _packageInfo.packageName);
        print('App version: ' + _packageInfo.version);
        print('Build number: ' + _packageInfo.buildNumber);
    }
```

```console
[VERBOSE-2:ui_dart_state.cc(157)] Unhandled Exception: Invalid argument(s)
#0      _StringBase.+ (dart:core-patch/string_patch.dart:262:57)
#1      _LoginScreenState._initPackageInfo (package:flutterapp/screens/scr_login.dart:128:28)
```

**Comment by iapicca** [comment]
Hi @wann2 
can you please provide your `flutter doctor -v` , 
your `flutter run --verbose` 
and your full `pubspec.yaml` 
or if possible a reproducible minimal code sample.
Thank you

**Comment by TahaTesser** [comment]
Without additional information we are unfortunately not sure how to resolve this issue.
We are therefore reluctantly going to close this bug for now.
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!
Thanks for your contribution.
