### ISSUE TITLE
[tool_crash] ArgumentError: Invalid argument(s): Invalid type for "path": null

### ISSUE THREAD

**Issue by ashwithpoojary98** [flutter/flutter#56811]
## Command
```
flutter create sample1
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
ArgumentError: Invalid argument(s): Invalid type for "path": null
```
#0      FileSystem.getPath (package:file/src/interface/file_system.dart:162:7)
#1      LocalFileSystem.directory (package:file/src/backends/local/local_file_system.dart:25:41)
#2      ForwardingFileSystem.directory (package:file/src/forwarding/forwarding_file_system.dart:23:49)
#3      _templateImageDirectory (package:flutter_tools/src/template.dart:256:21)
<asynchronous suspension>
#4      Template.fromName (package:flutter_tools/src/template.dart:63:38)
#5      CreateCommand._renderTemplate (package:flutter_tools/src/commands/create.dart:629:46)
#6      CreateCommand._generateApp (package:flutter_tools/src/commands/create.dart:543:29)
#7      CreateCommand.runCommand (package:flutter_tools/src/commands/create.dart:380:37)
#8      _rootRunUnary (dart:async/zone.dart:1192:38)
#9      _CustomZone.runUnary (dart:async/zone.dart:1085:19)
#10     _FutureListener.handleValue (dart:async/future_impl.dart:141:18)
#11     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:682:45)
#12     Future._propagateToListeners (dart:async/future_impl.dart:711:32)
#13     Future._completeWithValue (dart:async/future_impl.dart:526:5)
#14     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:36:15)
#15     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:298:13)
#16     FlutterProject.organizationNames (package:flutter_tools/src/project.dart)
#17     _rootRunUnary (dart:async/zone.dart:1192:38)
#18     _CustomZone.runUnary (dart:async/zone.dart:1085:19)
```
```
[✓] Flutter (Channel stable, v1.17.0, on Microsoft Windows [Version 6.3.9600], locale en-IN)
    • Flutter version 1.17.0 at C:\flutter
    • Framework revision e6b34c2b5c (7 days ago), 2020-05-02 11:39:18 -0700
    • Engine revision 540786dd51
    • Dart version 2.8.1

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at C:\Users\admin\AppData\Local\Android\sdk
    • Platform android-R, build-tools 29.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)
    • All Android licenses accepted.

[✓] Android Studio (version 3.6)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)

[✓] VS Code (version 1.45.0)
    • VS Code at C:\Users\admin\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.10.1

[✓] Connected device (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 7.0 (API 24) (emulator)

• No issues found!

```

## Flutter Application Metadata
No pubspec in working directory.

**Comment by TahaTesser** [comment]
Hi @ashwithpoojary98 
Can you please your `flutter --verbose  create sample1`logs? 
Thank you

**Comment by SeptSky** [comment]
same problem，after upgrade to Flutter 1.17.1

**Comment by ashwithpoojary98** [comment]
change to dev channel,then again change to stable
In the terminal use this commands
1.flutter channel dev
2.flutter upgrade
3.flutter channel stable
4.flutter upgrade

**Comment by TahaTesser** [comment]
Hi @ashwithpoojary98 
Following these [steps](https://github.com/flutter/flutter/issues/56811#issuecomment-629925160) has no issue when execute `flutter create sample1`, the project is successfully created without any error

Please sure you're creating project in a document or desktop and not in C:\ folder or Flutter directory

Also make sure you Flutter setup isn't located in program files

Thank you

**Comment by Anukul59** [comment]
Changing  to channel  stable didn't  worked in my case, tried  changing  to  channel  master and upgrade  it worked

**Comment by bkonyi** [comment]
I'm going to assume this issue is stale due to the lack of recent reports. Please feel free to reopen this issue if it's still valid.
