### ISSUE TITLE
Error dart:html not found 

### ISSUE THREAD

**Issue by Ma7moud-2003** [flutter/flutter#56829]
```
Launching lib\main.dart on Android SDK built for x86 in debug mode...
Running Gradle task 'assembleDebug'...
D/FlutterView( 7320): Attaching to a FlutterEngine: io.flutter.embedding.engine.FlutterEngine@6809f18
D/FlutterView( 7320): Already attached to this engine. Doing nothing.

Compiler message:
lib/pages/login.dart:9:8: Error: Not found: 'dart:html'
import "dart:html";
       ^
../../../../../../Pictures/flutter/packages/flutter/lib/src/painting/_network_image_web.dart:64:12: Error: Method not found: 'webOnlyInstantiateImageCodecFromUrl'.
    return ui.webOnlyInstantiateImageCodecFromUrl(resolved); // ignore: undefined_function
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Unhandled exception:
FileSystemException(uri=org-dartlang-untranslata
ble-uri:dart%3Ahtml; message=StandardFileSystem only supports file:* and data:* URIs)
#0      StandardFileSystem.entityForUri (package:front_end/src/api_prototype/standard_file_system.dart:33:7)
#1      asFileUri (package:vm/kernel_front_end.dar
t:604:
37)
#2      writeDepfile (package:vm/kernel_front_end.dart:799:21)
<asynchronous suspension>
#3      FrontendCompiler.compile (package:frontend_server/frontend_server.dart:472:15)
<asynchronous suspension>
#4      _FlutterFrontendCompiler.compile (package:flutter_frontend_server/server.dart:38:22)
#5      starter (
package:flutter_frontend_server/server.dart:149:27)
#6      main (file:///C:/b/s/w/ir/cache/builder/src
/
flutter/flutter_frontend_server/bin/starter.dart:8:30)
#7      _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:305:32)
#8      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:174:12)

Target kernel_snapshot failed: Exception: Errors during snapshot creation: null
build failed.

FAILURE: Build failed with an exception.

* Where:
Script 'C:\Users\Mahmoud\Pictures\flutter\packages\flutter_tools\gradle\flutter.gradle' line: 780

* What went wrong:
Execution failed for task ':app:compileFlutterBuildDebug'.
> Process 'command 'C:\Users\Mahmoud\Pictures\flutter\bin\flutter.bat'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 28s
Finished with error: Gradle task assembleDebug failed with exit code 1
```

**Comment by ja2375** [comment]
You seem to be trying to run a web only application on an Android emulator.

Of course this is not going to work as the `dart:html` library is not available on Android. It is only available on web.

If you really want to run the app on Android, start by removing any reference to the `dart:html` library.

**Comment by VladyslavBondarenko** [comment]
Thanks @ja2375 , 
@Ma7moud-2003 avoid any web dependencies in Android project, 
related to https://github.com/flutter/flutter/issues/53005.
Closing, as this isn't an issue with Flutter,
if you disagree please write in the comments and I will reopen it

**Comment by deakjahn** [comment]
It **_is_** a problem with Flutter. If you start to make a previously mobile-only application also run on the Web (moving to beta and adding web code), it no longer cna be compiled for mobile. Definitely a bug, and a serious one at that.

**Comment by VladyslavBondarenko** [comment]
@deakjahn follow up on https://github.com/flutter/flutter/issues/39998
