### ISSUE TITLE
crash when run flutter in my hybrid app

### ISSUE THREAD

**Issue by JimmyPeng4iOS** [flutter/flutter#56872]
Flutter crash report; please file at https://github.com/flutter/flutter/issues.

## command

flutter --suppress-analytics build aot --output-dir=build/aot --target-platform=ios --target=lib/main.dart --release --ios-arch=armv7,arm64 --bitcode

## exception

FileSystemException: FileSystemException: Cannot open file, path = 'build/aot/arm64/gen_snapshot.d' (OS Error: No such file or directory, errno = 2)

```
#0      _File.throwIfError (dart:io/file_impl.dart:645:7)
#1      _File.openSync (dart:io/file_impl.dart:489:5)
#2      _File.writeAsBytesSync (dart:io/file_impl.dart:614:31)
#3      _File.writeAsStringSync (dart:io/file_impl.dart:638:5)
#4      ForwardingFile.writeAsStringSync (package:file/src/forwarding/forwarding_file.dart:154:16)
#5      AOTSnapshotter.build (package:flutter_tools/src/base/build.dart:202:43)
<asynchronous suspension>
#6      AotBuilder.build.<anonymous closure> (package:flutter_tools/src/aot.dart:100:44)
#7      _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:379:8)
#8      AotBuilder.build (package:flutter_tools/src/aot.dart:99:19)
#9      _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:73:64)
#10     _rootRunUnary (dart:async/zone.dart:1134:38)
#11     _CustomZone.runUnary (dart:async/zone.dart:1031:19)
#12     _FutureListener.handleValue (dart:async/future_impl.dart:139:18)
#13     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:680:45)
#14     Future._propagateToListeners (dart:async/future_impl.dart:709:32)
#15     Future._completeWithValue (dart:async/future_impl.dart:524:5)
#16     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:32:15)
#17     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:290:13)
#18     AOTSnapshotter.compileKernel (package:flutter_tools/src/base/build.dart)
#19     _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:73:64)
#20     _rootRunUnary (dart:async/zone.dart:1134:38)
#21     _CustomZone.runUnary (dart:async/zone.dart:1031:19)
#22     _FutureListener.handleValue (dart:async/future_impl.dart:139:18)
#23     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:680:45)
#24     Future._propagateToListeners (dart:async/future_impl.dart:709:32)
#25     Future._completeWithValue (dart:async/future_impl.dart:524:5)
#26     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:32:15)
#27     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:290:13)
#28     AOTSnapshotter._timedStep (package:flutter_tools/src/base/build.dart)
#29     _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:73:64)
#30     _rootRunUnary (dart:async/zone.dart:1134:38)
#31     _CustomZone.runUnary (dart:async/zone.dart:1031:19)
#32     _FutureListener.handleValue (dart:async/future_impl.dart:139:18)
#33     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:680:45)
#34     Future._propagateToListeners (dart:async/future_impl.dart:709:32)
#35     Future._chainCoreFuture (dart:async/future_impl.dart:495:7)
#36     Future._chainFuture (dart:async/future_impl.dart:567:9)
#37     Future._asyncComplete (dart:async/future_impl.dart:549:7)
#38     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:30:15)
#39     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:290:13)
#40     KernelCompiler.compile (package:flutter_tools/src/compile.dart)
#41     _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:73:64)
#42     _rootRunUnary (dart:async/zone.dart:1134:38)
#43     _CustomZone.runUnary (dart:async/zone.dart:1031:19)
#44     _FutureListener.handleValue (dart:async/future_impl.dart:139:18)
#45     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:680:45)
#46     Future._propagateToListeners (dart:async/future_impl.dart:709:32)
#47     Future._completeWithValue (dart:async/future_impl.dart:524:5)
#48     Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:554:7)
#49     _rootRun (dart:async/zone.dart:1126:13)
#50     _CustomZone.run (dart:async/zone.dart:1023:19)
#51     _CustomZone.runGuarded (dart:async/zone.dart:925:7)
#52     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:965:23)
#53     _microtaskLoop (dart:async/schedule_microtask.dart:43:21)
#54     _startMicrotaskLoop (dart:async/schedule_microtask.dart:52:5)
#55     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
#56     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:175:5)
```

## flutter doctor

```
[✓] Flutter (Channel stable, v1.12.13, on Mac OS X 10.15.3 19D76, locale zh-Hans-CN)
    • Flutter version 1.12.13 at /Users/pengjizong/Documents/flutter
    • Framework revision cf37c2cd07 (6 months ago), 2019-11-25 12:04:30 -0800
    • Engine revision b6b54fd606
    • Dart version 2.7.0

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.0)
    • Android SDK at /Users/pengjizong/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.4.1, Build version 11E503a
    • CocoaPods version 1.8.0

[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)

[✓] Connected device (2 available)
    • iPhoneXR • 00008020-00021D221EDA002E            • ios • iOS 12.1.2
    • iPhone X • 05FE745B-E75C-40EE-A024-4384E5FC8E99 • ios • com.apple.CoreSimulator.SimRuntime.iOS-13-4 (simulator)

• No issues found!
```
[flutter_01.log](https://github.com/flutter/flutter/files/4608343/flutter_01.log)

**Comment by iapicca** [comment]
Hi @JimmyPeng4iOS 
could you please run `flutter upgrade --force`
and if the issue persists 
provide the update` flutter doctor - v` and logs
Thank you

**Comment by iapicca** [comment]
Without additional information we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact description of what happens, logs and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
