### ISSUE TITLE
Starting from the new stable v1.17.0 flutter widget test crashes if no tests provided

### ISSUE THREAD

**Issue by BondarenkoStas** [flutter/flutter#56877]
The issue didn't happen on the previous flutter stable, but happens on the current one and later

## Steps to Reproduce

1. Create a new app with `flutter create newapp`
2. Delete the default test to leave only `void main() {}`
3. run `flutter test`

**Expected results:** 
`test package returned with exit code 0` as on the previous stable `1.12.13+hotfix.9`

**Actual results:** 

`flutter test` fails with exit code 1. 

<details>
  <summary>`flutter test --verbose` gives the next error</summary>

```
flutter test -v
[  +14 ms] executing: [/Users/stas/flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[  +38 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[        ] d482163f59c49c32cb329beb2c3111c8e961d6b9
[        ] executing: [/Users/stas/flutter/] git describe --match *.*.* --first-parent --long --tags
[  +16 ms] Exit code 0 from: git describe --match *.*.* --first-parent --long --tags
[        ] 1.18.0-7.0.pre-0-gd482163f5
[  +14 ms] executing: [/Users/stas/flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[  +12 ms] Exit code 128 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] fatal: HEAD does not point to a branch
[  +32 ms] executing: [/Users/stas/flutter/] git rev-parse --abbrev-ref HEAD
[  +11 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] HEAD
[  +39 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +2 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[   +4 ms] Artifact Instance of 'MaterialFonts' is not required, skipping update.
[        ] Artifact Instance of 'GradleWrapper' is not required, skipping update.
[        ] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[        ] Artifact Instance of 'FlutterSdk' is not required, skipping update.
[        ] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FontSubsetArtifacts' is not required, skipping update.
[   +3 ms] Changing current working directory to: /Users/stas/newapp
[ +221 ms] Generating /Users/stas/newapp/android/app/src/main/java/io/flutter/plugins/GeneratedPluginRegistrant.java
[  +25 ms] Artifact Instance of 'MaterialFonts' is not required, skipping update.
[        ] Artifact Instance of 'GradleWrapper' is not required, skipping update.
[        ] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[        ] Artifact Instance of 'FlutterSdk' is not required, skipping update.
[        ] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FontSubsetArtifacts' is not required, skipping update.
[  +13 ms] switching to directory LocalDirectory: 'test' to run tests
[        ] running test package with arguments: [-r, compact, --concurrency=2, --, /Users/stas/newapp/test/widget_test.dart]
00:00 +0: loading /Users/stas/newapp/test/widget_test.dart                                                                          [ +204 ms] test 0: starting test /Users/stas/newapp/test/widget_test.dart
[  +25 ms] test 0: starting shell process
[   +8 ms] Stopping scan for flutter_test_config.dart; found project root at /Users/stas/newapp
[   +2 ms] Compiler will use the following file as its incremental dill file:
/var/folders/yh/44wjdv3s3clb5vg8w8z7mxm00000gn/T/flutter_test_compiler.z5Gjop/output.dill
[   +2 ms] Listening to compiler controller...
[   +6 ms] Compiling file:///var/folders/yh/44wjdv3s3clb5vg8w8z7mxm00000gn/T/flutter_test_listener.pIeDGp/listener.dart
[  +11 ms] /Users/stas/flutter/bin/cache/dart-sdk/bin/dart
/Users/stas/flutter/bin/cache/artifacts/engine/darwin-x64/frontend_server.dart.snapshot --sdk-root
/Users/stas/flutter/bin/cache/artifacts/engine/common/flutter_patched_sdk/ --incremental --target=flutter --debugger-module-names
-Ddart.developer.causal_async_stacks=true --output-dill
/var/folders/yh/44wjdv3s3clb5vg8w8z7mxm00000gn/T/flutter_test_compiler.z5Gjop/output.dill --packages /Users/stas/newapp/.packages
-Ddart.vm.profile=false -Ddart.vm.product=false
--bytecode-options=source-positions,local-var-info,debugger-stops,instance-field-initializers,keep-unreachable-code,avoid-closure-cal
l-instructions --enable-asserts --track-widget-creation --initialize-from-dill /Users/stas/newapp/build/testfile.dill.track.dill
[  +16 ms] <- compile file:///var/folders/yh/44wjdv3s3clb5vg8w8z7mxm00000gn/T/flutter_test_listener.pIeDGp/listener.dart
00:01 +0: loading /Users/stas/newapp/test/widget_test.dart                                                                          [+1207 ms] <- accept
[        ] <- reset
[        ] Compiling /var/folders/yh/44wjdv3s3clb5vg8w8z7mxm00000gn/T/flutter_test_listener.pIeDGp/listener.dart took 1236ms
[   +7 ms] /Users/stas/flutter/bin/cache/artifacts/engine/darwin-x64/flutter_tester --disable-observatory --enable-checked-mode
--verify-entry-points --enable-software-rendering --skia-deterministic-rendering --enable-dart-profiling --non-interactive
--use-test-fonts --packages=/Users/stas/newapp/.packages
/var/folders/yh/44wjdv3s3clb5vg8w8z7mxm00000gn/T/flutter_test_listener.pIeDGp/listener.dart.dill
[   +3 ms] Using this directory for fonts configuration: /var/folders/yh/44wjdv3s3clb5vg8w8z7mxm00000gn/T/flutter_test_fonts.tCNqox
[   +6 ms] test 0: awaiting initial result for pid 30836
[ +540 ms] test 0: process with pid 30836 connected to test harness
[   +1 ms] test 0: awaiting test result for pid 30836
[  +78 ms] test 0: process with pid 30836 no longer needed by test harness
[        ] test 0: cleaning up...
[        ] test 0: ensuring end-of-process for shell
[  +10 ms] test 0: deleting temporary directory
[   +3 ms] test 0: shutting down test harness socket server
[   +3 ms] test 0: finished
No tests ran.
[  +16 ms] Deleting /var/folders/yh/44wjdv3s3clb5vg8w8z7mxm00000gn/T/flutter_test_compiler.z5Gjop...
[   +4 ms] killing pid 30835
[  +58 ms] Deleting /var/folders/yh/44wjdv3s3clb5vg8w8z7mxm00000gn/T/flutter_test_fonts.tCNqox...
[  +11 ms] test package returned with exit code 1
[  +16 ms] "flutter test" took 2,533ms.

#0      throwToolExit (package:flutter_tools/src/base/common.dart:14:3)
#1      TestCommand.runCommand (package:flutter_tools/src/commands/test.dart:292:7)
<asynchronous suspension>
#2      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:760:18)
<asynchronous suspension>
#3      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:657:33)
<asynchronous suspension>
#4      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart)
#5      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:29)
#6      _rootRun (dart:async/zone.dart:1184:13)
#7      _CustomZone.run (dart:async/zone.dart:1077:19)
#8      _runZoned (dart:async/zone.dart:1619:10)
#9      runZoned (dart:async/zone.dart:1539:10)
#10     AppContext.run (package:flutter_tools/src/base/context.dart:149:18)
#11     FlutterCommand.run (package:flutter_tools/src/runner/flutter_command.dart:647:20)
#12     CommandRunner.runCommand (package:args/command_runner.dart:197:27)
#13     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:339:21)
#14     _rootRunUnary (dart:async/zone.dart:1192:38)
#15     _CustomZone.runUnary (dart:async/zone.dart:1085:19)
#16     _FutureListener.handleValue (dart:async/future_impl.dart:141:18)
#17     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:682:45)
#18     Future._propagateToListeners (dart:async/future_impl.dart:711:32)
#19     Future._completeWithValue (dart:async/future_impl.dart:526:5)
#20     Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:556:7)
#21     _rootRun (dart:async/zone.dart:1184:13)
#22     _CustomZone.run (dart:async/zone.dart:1077:19)
#23     _CustomZone.runGuarded (dart:async/zone.dart:979:7)
#24     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1019:23)
#25     _microtaskLoop (dart:async/schedule_microtask.dart:43:21)
#26     _startMicrotaskLoop (dart:async/schedule_microtask.dart:52:5)
#27     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
#28     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:169:5)

```

</details>

**flutter analyze**
```

flutter analyze 
Analyzing test...
No issues found! (ran in 1.3s)

```

**flutter doctor -v**
```
[✓] Flutter (Channel stable, v1.17.0, on Mac OS X 10.15.4 19E287, locale en-EE)
    • Flutter version 1.17.0 at /Users/stas/flutter
    • Framework revision e6b34c2b5c (9 days ago), 2020-05-02 11:39:18 -0700
    • Engine revision 540786dd51
    • Dart version 2.8.1


[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/stas/Library/Android/sdk
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.4)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.4, Build version 11E146
    • CocoaPods version 1.8.3

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 41.1.2
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[!] Connected device
    ! No devices available

! Doctor found issues in 1 category.
```

**Comment by iapicca** [comment]
Hi @BondarenkoStas 
I do experience the same behaviour;
while recreating the same situation on `master` 
produce this result

```bash
 nevercode@Nevercodes-Air  ~/Desktop/projects/master  flutter_master test                                                                                  ✔  1246  16:15:04
No tests ran.
```

Thank you

**Comment by goderbauer** [comment]
@iapicca are you saying this is fixed on master? Should we close it then?

**Comment by iapicca** [comment]
Hi @goderbauer 
actually with the new master fails

```bash
[ +103 ms] executing: [/Users/nevercode/development/flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[ +101 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[   +2 ms] f7a6a7906be96d2288f5d63a5a54c515a6e987fe
[   +2 ms] executing: [/Users/nevercode/development/flutter/] git tag --contains HEAD
[ +544 ms] Exit code 0 from: git tag --contains HEAD
[        ] 1.17.1
[  +14 ms] executing: [/Users/nevercode/development/flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[  +27 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/stable
[        ] executing: [/Users/nevercode/development/flutter/] git ls-remote --get-url origin
[  +17 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[ +146 ms] executing: [/Users/nevercode/development/flutter/] git rev-parse --abbrev-ref HEAD
[  +23 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[   +1 ms] stable
[  +11 ms] executing: sw_vers -productName
[  +37 ms] Exit code 0 from: sw_vers -productName
[        ] Mac OS X
[        ] executing: sw_vers -productVersion
[  +29 ms] Exit code 0 from: sw_vers -productVersion
[        ] 10.15.4
[        ] executing: sw_vers -buildVersion
[  +30 ms] Exit code 0 from: sw_vers -buildVersion
[   +1 ms] 19E287
[  +50 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[  +20 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +18 ms] Artifact Instance of 'MaterialFonts' is not required, skipping update.
[        ] Artifact Instance of 'GradleWrapper' is not required, skipping update.
[        ] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[        ] Artifact Instance of 'FlutterSdk' is not required, skipping update.
[        ] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FontSubsetArtifacts' is not required, skipping update.
[ +286 ms] Generating /Users/nevercode/Desktop/projects/master/android/app/src/main/java/io/flutter/plugins/GeneratedPluginRegistrant.java
[  +74 ms] Artifact Instance of 'MaterialFonts' is not required, skipping update.
[        ] Artifact Instance of 'GradleWrapper' is not required, skipping update.
[        ] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[        ] Artifact Instance of 'FlutterSdk' is not required, skipping update.
[        ] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FontSubsetArtifacts' is not required, skipping update.
[  +23 ms] switching to directory LocalDirectory: 'test' to run tests
[   +1 ms] running test package with arguments: [-r, compact, --concurrency=2, --, /Users/nevercode/Desktop/projects/master/test/widget_test.dart]
00:00 +0: loading /Users/nevercode/Desktop/projects/master/test/widget_test.dart                                                                                                 [ +252 ms] test 0: starting test /Users/nevercode/Desktop/projects/master/test/widget_test.dart
[  +33 ms] test 0: starting shell process
[   +5 ms] Stopping scan for flutter_test_config.dart; found project root at /Users/nevercode/Desktop/projects/master
[   +4 ms] Compiler will use the following file as its incremental dill file: /var/folders/c3/l5jpznsj5k37yrj47l__xpw40000gn/T/flutter_test_compiler.6DxlsJ/output.dill
[        ] Listening to compiler controller...
[  +15 ms] Compiling /var/folders/c3/l5jpznsj5k37yrj47l__xpw40000gn/T/flutter_test_listener.M4cPYI/listener.dart
[  +28 ms] /Users/nevercode/development/flutter/bin/cache/dart-sdk/bin/dart
/Users/nevercode/development/flutter/bin/cache/artifacts/engine/darwin-x64/frontend_server.dart.snapshot --sdk-root
/Users/nevercode/development/flutter/bin/cache/artifacts/engine/common/flutter_patched_sdk/ --incremental --target=flutter --debugger-module-names
-Ddart.developer.causal_async_stacks=true --output-dill /var/folders/c3/l5jpznsj5k37yrj47l__xpw40000gn/T/flutter_test_compiler.6DxlsJ/output.dill --packages
/Users/nevercode/Desktop/projects/master/.packages -Ddart.vm.profile=false -Ddart.vm.product=false
--bytecode-options=source-positions,local-var-info,debugger-stops,instance-field-initializers,keep-unreachable-code,avoid-closure-call-instructions --enable-asserts
--track-widget-creation --initialize-from-dill /Users/nevercode/Desktop/projects/master/build/testfile.dill.track.dill
[  +49 ms] <- compile /var/folders/c3/l5jpznsj5k37yrj47l__xpw40000gn/T/flutter_test_listener.M4cPYI/listener.dart
00:03 +0: loading /Users/nevercode/Desktop/projects/master/test/widget_test.dart                                                                                                 [+2975 ms] <- accept
[   +1 ms] <- reset
[        ] Compiling /var/folders/c3/l5jpznsj5k37yrj47l__xpw40000gn/T/flutter_test_listener.M4cPYI/listener.dart took 3054ms
[   +3 ms] /Users/nevercode/development/flutter/bin/cache/artifacts/engine/darwin-x64/flutter_tester --disable-observatory --enable-checked-mode --verify-entry-points
--enable-software-rendering --skia-deterministic-rendering --enable-dart-profiling --non-interactive --use-test-fonts
--packages=/Users/nevercode/Desktop/projects/master/.packages /var/folders/c3/l5jpznsj5k37yrj47l__xpw40000gn/T/flutter_test_listener.M4cPYI/listener.dart.dill
[  +11 ms] Using this directory for fonts configuration: /var/folders/c3/l5jpznsj5k37yrj47l__xpw40000gn/T/flutter_test_fonts.QrTNCM
[  +39 ms] test 0: awaiting initial result for pid 62611
[ +796 ms] test 0: process with pid 62611 connected to test harness
[   +2 ms] test 0: awaiting test result for pid 62611
00:04 +0: loading /Users/nevercode/Desktop/projects/master/test/widget_test.dart                                                                                                 [ +140 ms] test 0: process with pid 62611 no longer needed by test harness
[        ] test 0: cleaning up...
[   +1 ms] test 0: ensuring end-of-process for shell
[  +21 ms] test 0: deleting temporary directory
[  +17 ms] test 0: shutting down test harness socket server
[   +7 ms] test 0: finished
No tests ran.
[  +45 ms] Deleting /var/folders/c3/l5jpznsj5k37yrj47l__xpw40000gn/T/flutter_test_compiler.6DxlsJ...
[   +6 ms] killing pid 62601
[  +63 ms] Deleting /var/folders/c3/l5jpznsj5k37yrj47l__xpw40000gn/T/flutter_test_fonts.QrTNCM...
[   +6 ms] test package returned with exit code 1
[  +22 ms] "flutter test" took 5,185ms.

#0      throwToolExit (package:flutter_tools/src/base/common.dart:14:3)
#1      TestCommand.runCommand (package:flutter_tools/src/commands/test.dart:280:7)
<asynchronous suspension>
#2      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:723:18)
#3      _rootRunUnary (dart:async/zone.dart:1192:38)
#4      _CustomZone.runUnary (dart:async/zone.dart:1085:19)
#5      _FutureListener.handleValue (dart:async/future_impl.dart:141:18)
#6      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:682:45)
#7      Future._propagateToListeners (dart:async/future_impl.dart:711:32)
#8      Future._completeWithValue (dart:async/future_impl.dart:526:5)
#9      Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:556:7)
#10     _rootRun (dart:async/zone.dart:1184:13)
#11     _CustomZone.run (dart:async/zone.dart:1077:19)
#12     _CustomZone.runGuarded (dart:async/zone.dart:979:7)
#13     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1019:23)
#14     _microtaskLoop (dart:async/schedule_microtask.dart:43:21)
#15     _startMicrotaskLoop (dart:async/schedule_microtask.dart:52:5)
#16     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
#17     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:169:5)
```
Thanks

**Comment by jonahwilliams** [comment]
Why do you think this is a crash?

If no tests are run, we exit with code 1. That is not the same as a crash. This is intentional functionality to ensure that a test command has not accidentally skipped all tests

**Comment by zanderso** [comment]
@jonahwilliams where does the error message "No tests ran" come from? Is that the message from `package:test` or the tool? If it is from the tool, we should improve it to be something like, "Failing because no tests ran. Were all tests accidentally disabled?"

**Comment by jonahwilliams** [comment]
This is a package:test feature.

**Comment by zanderso** [comment]
For consistency with the rest of the Dart ecosystem, I think following the default `package:test` behavior is what we should continue doing, so I'll go ahead and close this issue.
