### ISSUE TITLE
[tool_crash] Instance of 'VersionSkew'

### ISSUE THREAD

**Issue by jifalops** [flutter/flutter#56896]
## Command
```
flutter run -v
```

## Steps to Reproduce
Just running an app that was running before. Have tried `flutter clean`, uninstalling the app, quitting vscode and the emulator. Will try reboot as old SO answers say that works.

## Logs
VersionSkew: Instance of 'VersionSkew'
```
#0      _handleDaemonStartup (package:build_daemon/client.dart:84:5)
<asynchronous suspension>
#1      BuildDaemonClient.connect (package:build_daemon/client.dart:183:11)
<asynchronous suspension>
#2      BuildRunner.daemon (package:flutter_tools/src/build_runner/build_runner.dart:166:51)
#3      _rootRunUnary (dart:async/zone.dart:1192:38)
#4      _CustomZone.runUnary (dart:async/zone.dart:1085:19)
#5      _FutureListener.handleValue (dart:async/future_impl.dart:141:18)
#6      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:682:45)
#7      Future._propagateToListeners (dart:async/future_impl.dart:711:32)
#8      Future._completeWithValue (dart:async/future_impl.dart:526:5)
#9      Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:556:7)
#10     _rootRun (dart:async/zone.dart:1184:13)
#11     _CustomZone.run (dart:async/zone.dart:1077:19)
#12     _CustomZone.runGuarded (dart:async/zone.dart:979:7)
#13     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1019:23)
#14     _microtaskLoop (dart:async/schedule_microtask.dart:43:21)
#15     _startMicrotaskLoop (dart:async/schedule_microtask.dart:52:5)
#16     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
#17     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:169:5)
```
```
[✓] Flutter (Channel stable, v1.17.0, on Mac OS X 10.15.3 19D76, locale en-US)
    • Flutter version 1.17.0 at /Users/jacob/tools/flutter
    • Framework revision e6b34c2b5c (9 days ago), 2020-05-02 11:39:18 -0700
    • Engine revision 540786dd51
    • Dart version 2.8.1

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/jacob/Library/Android/sdk
    • Platform android-29, build-tools 29.0.3
    • ANDROID_HOME = /Users/jacob/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.4.1, Build version 11E503a
    • CocoaPods version 1.9.1

[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)

[✓] VS Code (version 1.45.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.10.1

[✓] Connected device (1 available)
    • sdk gphone x86 • emulator-5554 • android-x86 • Android 10 (API 29) (emulator)

• No issues found!

```

## Flutter Application Metadata
**Type**: app
**Version**: 0.1.0+1
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: stable
**Creation framework version**: e6b34c2b5c96bb95325269a29a84e83ed8909b5f
### Plugins
connectivity-0.4.8+5
connectivity_macos-0.1.0+3
devicelocale-0.2.3
file_picker-1.9.0+1
flutter_device_locale-0.4.0
flutter_plugin_android_lifecycle-1.0.7
flutter_secure_storage-3.3.3
geolocator-5.3.1
google_api_availability-2.0.4
google_maps_flutter-0.5.27+1
location_permissions-2.0.5
open_file-3.0.1
path_provider-1.6.7
path_provider_macos-0.0.4+2
shared_preferences-0.5.7+1
shared_preferences_macos-0.0.1+8
shared_preferences_web-0.1.2+5
url_launcher-5.4.5
url_launcher_macos-0.0.1+5
url_launcher_web-0.1.1+4

**Comment by TahaTesser** [comment]
Hi @jifalops 
can you please provide your complete `flutter run --verbose`?
Thank you

**Comment by zanderso** [comment]
@TahaTesser Could you explain why this is related to #50880 ? Thanks!

**Comment by TahaTesser** [comment]
@zanderso 
We have increase multiple i tool_crash issues in short time as the release of 1.17
Some of these tool_crash issues are mention in that issue
We need logs but i wanted to provide attention to this too if it is related

**Comment by jifalops** [comment]
Will update sometime today

**Comment by jifalops** [comment]
@TahaTesser it actually stopped happening after I rebooted.

**Comment by TahaTesser** [comment]
Hi @jifalops 
given your last message I feel safe to close this issue,
if you disagree please write in the comments and I will reopen it. 
Thank you
