### ISSUE TITLE
how to resolve "Failed to compile application"

### ISSUE THREAD

**Issue by ghostsatan** [flutter/flutter#56977]
## Steps to Reproduce

1. Run `flutter create bug`.
2. Update the files as follows: ... 
3. ... 

**Expected results:** 

**Actual results:** 

<details>
  <summary>Logs</summary>

```
```

```
```

```
```

</details>

VS Code  platform

run others flutter-web application

terminal:

Launching lib\main.dart on Chrome in debug mode...
Syncing files to device Chrome...
30,082ms (!)
Failed to compile application.

how to resolve it

**Comment by kenthinson** [comment]
@ghostsatan please add `flutter doctor -v` output to your issue.

**Comment by TahaTesser** [comment]
Hi @ghostsatan 
can you please provide your `flutter doctor -v` and `flutter run --verbose`? 
Also, to better address the issue, would be helpful if you could post a minimal code sample to reproduce the problem
Thank you

**Comment by jaxnz** [comment]
I have the same issue, it has happened on the `master` channel.

Changing to `beta` fixes the issue for now.

```
flutter channel beta
flutter upgrade
```

**Comment by devhammed** [comment]
This same issue is happening on the `beta` channel too.

```
[  +15 ms] executing: [/home/devhammed/.local/share/flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[  +51 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[        ] 2738a1148ba6c9a6114df62358109407c3ef2553
[   +1 ms] executing: [/home/devhammed/.local/share/flutter/] git tag --contains HEAD
[  +25 ms] Exit code 0 from: git tag --contains HEAD
[        ] 1.18.0-11.1.pre
[  +20 ms] executing: [/home/devhammed/.local/share/flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[   +8 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/beta
[        ] executing: [/home/devhammed/.local/share/flutter/] git ls-remote --get-url origin
[   +7 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[  +92 ms] executing: [/home/devhammed/.local/share/flutter/] git rev-parse --abbrev-ref HEAD
[   +7 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] beta
[  +91 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +4 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +31 ms] executing: /home/devhammed/Android/Sdk/platform-tools/adb devices -l
[  +93 ms] List of devices attached
[   +9 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[   +3 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[ +168 ms] Found plugin flutter_country_picker at
/home/devhammed/.local/share/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_country_picker-0.1.6/
[  +18 ms] Found plugin flutter_keyboard_visibility at
/home/devhammed/.local/share/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_keyboard_visibility-0.7.0/
[   +3 ms] Found plugin flutter_plugin_android_lifecycle at
/home/devhammed/.local/share/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_plugin_android_lifecycle-1.0.7/
[  +15 ms] Found plugin image_picker at
/home/devhammed/.local/share/flutter/.pub-cache/hosted/pub.dartlang.org/image_picker-0.6.6+1/
[  +24 ms] Found plugin shared_preferences at
/home/devhammed/.local/share/flutter/.pub-cache/hosted/pub.dartlang.org/shared_preferences-0.5.7+2/
[   +3 ms] Found plugin shared_preferences_macos at
/home/devhammed/.local/share/flutter/.pub-cache/hosted/pub.dartlang.org/shared_preferences_macos-0.0.1+8/
[   +6 ms] Found plugin shared_preferences_web at
/home/devhammed/.local/share/flutter/.pub-cache/hosted/pub.dartlang.org/shared_preferences_web-0.1.2+5/
[ +169 ms] Found plugin flutter_country_picker at
/home/devhammed/.local/share/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_country_picker-0.1.6/
[   +4 ms] Found plugin flutter_keyboard_visibility at
/home/devhammed/.local/share/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_keyboard_visibility-0.7.0/
[   +2 ms] Found plugin flutter_plugin_android_lifecycle at
/home/devhammed/.local/share/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_plugin_android_lifecycle-1.0.7/
[   +7 ms] Found plugin image_picker at
/home/devhammed/.local/share/flutter/.pub-cache/hosted/pub.dartlang.org/image_picker-0.6.6+1/
[  +13 ms] Found plugin shared_preferences at
/home/devhammed/.local/share/flutter/.pub-cache/hosted/pub.dartlang.org/shared_preferences-0.5.7+2/
[   +2 ms] Found plugin shared_preferences_macos at
/home/devhammed/.local/share/flutter/.pub-cache/hosted/pub.dartlang.org/shared_preferences_macos-0.0.1+8/
[   +3 ms] Found plugin shared_preferences_web at
/home/devhammed/.local/share/flutter/.pub-cache/hosted/pub.dartlang.org/shared_preferences_web-0.1.2+5/
[ +126 ms] Generating
/home/devhammed/Flutter/listbuy_app/android/app/src/main/java/io/flutter/plugins/GeneratedPluginRegistrant.java
[ +150 ms] Launching lib/main.dart on Chrome in debug mode...
[  +84 ms] Updating assets
[ +719 ms] Syncing files to device Chrome...
[  +24 ms] Found plugin flutter_country_picker at
/home/devhammed/.local/share/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_country_picker-0.1.6/
[   +3 ms] Found plugin flutter_keyboard_visibility at
/home/devhammed/.local/share/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_keyboard_visibility-0.7.0/
[   +2 ms] Found plugin flutter_plugin_android_lifecycle at
/home/devhammed/.local/share/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_plugin_android_lifecycle-1.0.7/
[   +5 ms] Found plugin image_picker at
/home/devhammed/.local/share/flutter/.pub-cache/hosted/pub.dartlang.org/image_picker-0.6.6+1/
[  +13 ms] Found plugin shared_preferences at
/home/devhammed/.local/share/flutter/.pub-cache/hosted/pub.dartlang.org/shared_preferences-0.5.7+2/
[   +1 ms] Found plugin shared_preferences_macos at
/home/devhammed/.local/share/flutter/.pub-cache/hosted/pub.dartlang.org/shared_preferences_macos-0.0.1+8/
[   +2 ms] Found plugin shared_preferences_web at
/home/devhammed/.local/share/flutter/.pub-cache/hosted/pub.dartlang.org/shared_preferences_web-0.1.2+5/
[  +31 ms] Found plugin flutter_country_picker at
/home/devhammed/.local/share/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_country_picker-0.1.6/
[   +2 ms] Found plugin flutter_keyboard_visibility at
/home/devhammed/.local/share/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_keyboard_visibility-0.7.0/
[   +1 ms] Found plugin flutter_plugin_android_lifecycle at
/home/devhammed/.local/share/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_plugin_android_lifecycle-1.0.7/
[   +2 ms] Found plugin image_picker at
/home/devhammed/.local/share/flutter/.pub-cache/hosted/pub.dartlang.org/image_picker-0.6.6+1/
[   +8 ms] Found plugin shared_preferences at
/home/devhammed/.local/share/flutter/.pub-cache/hosted/pub.dartlang.org/shared_preferences-0.5.7+2/
[   +1 ms] Found plugin shared_preferences_macos at
/home/devhammed/.local/share/flutter/.pub-cache/hosted/pub.dartlang.org/shared_preferences_macos-0.0.1+8/
[   +2 ms] Found plugin shared_preferences_web at
/home/devhammed/.local/share/flutter/.pub-cache/hosted/pub.dartlang.org/shared_preferences_web-0.1.2+5/
[  +18 ms] Generating
/home/devhammed/Flutter/listbuy_app/android/app/src/main/java/io/flutter/plugins/GeneratedPluginRegistrant.java
[ +545 ms] <- reset
[   +9 ms] /home/devhammed/.local/share/flutter/bin/cache/dart-sdk/bin/dart
/home/devhammed/.local/share/flutter/bin/cache/artifacts/engine/linux-x64/frontend_server.dart.snapshot --sdk-root
/home/devhammed/.local/share/flutter/bin/cache/flutter_web_sdk/ --incremental --target=dartdevc --debugger-module-names
-Ddart.developer.causal_async_stacks=true --output-dill /tmp/flutter_tool.PVAJEP/app.dill --libraries-spec
file:///home/devhammed/.local/share/flutter/bin/cache/flutter_web_sdk/libraries.json --packages .packages
-Ddart.vm.profile=false -Ddart.vm.product=false
--bytecode-options=source-positions,local-var-info,debugger-stops,instance-field-initializers,keep-unreachable-code,avoi
d-closure-call-instructions --enable-asserts --track-widget-creation --filesystem-root /tmp/flutter_tools.PDHJZO
--filesystem-scheme org-dartlang-app --initialize-from-dill build/cache.dill --platform
file:///home/devhammed/.local/share/flutter/bin/cache/flutter_web_sdk/kernel/flutter_ddc_sdk.dill
[  +11 ms] <- compile org-dartlang-app:/web_entrypoint.dart
[+1761 ms] 
                    Compiler message:
[        ]
../../.local/share/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_chips_input-1.8.1/lib/src/chips_input.dart:65:7:
Error: The non-abstract class 'ChipsInputState' is missing implementations for these members:
[        ]  - TextInputClient.currentAutofillScope
[        ] Try to either
[        ]  - provide an implementation,
[        ]  - inherit an implementation from a superclass or mixin,
[        ]  - mark the class as abstract, or
[        ]  - provide a 'noSuchMethod' implementation.
[        ] class ChipsInputState<T> extends State<ChipsInput<T>>
[        ]       ^^^^^^^^^^^^^^^
[        ] ../../.local/share/flutter/packages/flutter/lib/src/services/text_input.dart:769:21: Context:
'TextInputClient.currentAutofillScope' is defined here.
[        ]   AutofillScope get currentAutofillScope;
[        ]                     ^^^^^^^^^^^^^^^^^^^^
[+26365 ms] Syncing files to device Chrome... (completed in 28,804ms, longer than expected)
[        ] Synced 0.0MB.
[        ] Failed to compile application.
[   +5 ms] "flutter run" took 30,535ms.

#0      throwToolExit (package:flutter_tools/src/base/common.dart:14:3)
#1      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:570:7)
<asynchronous suspension>
#2      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:797:18)
<asynchronous suspension>
#3      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:694:33)
<asynchronous suspension>
#4      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart)
#5      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:29)
#6      _rootRun (dart:async/zone.dart:1184:13)
#7      _CustomZone.run (dart:async/zone.dart:1077:19)
#8      _runZoned (dart:async/zone.dart:1619:10)
#9      runZoned (dart:async/zone.dart:1539:10)
#10     AppContext.run (package:flutter_tools/src/base/context.dart:149:18)
#11     FlutterCommand.run (package:flutter_tools/src/runner/flutter_command.dart:684:20)
#12     CommandRunner.runCommand (package:args/command_runner.dart:197:27)
#13     FlutterCommandRunner.runCommand.<anonymous closure>
(package:flutter_tools/src/runner/flutter_command_runner.dart:339:21)
#14     _rootRunUnary (dart:async/zone.dart:1192:38)
#15     _CustomZone.runUnary (dart:async/zone.dart:1085:19)
#16     _FutureListener.handleValue (dart:async/future_impl.dart:141:18)
#17     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:686:45)
#18     Future._propagateToListeners (dart:async/future_impl.dart:715:32)
#19     Future._completeWithValue (dart:async/future_impl.dart:526:5)
#20     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:36:15)
#21     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:303:13)
#22     FlutterVersion.checkFlutterVersionFreshness (package:flutter_tools/src/version.dart)
#23     _rootRunUnary (dart:async/zone.dart:1192:38)
#24     _CustomZone.runUnary (dart:async/zone.dart:1085:19)
#25     _FutureListener.handleValue (dart:async/future_impl.dart:141:18)
#26     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:686:45)
#27     Future._propagateToListeners (dart:async/future_impl.dart:715:32)
#28     Future._completeWithValue (dart:async/future_impl.dart:526:5)
#29     Future._asyncCompleteWithValue.<anonymous closure> (dart:async/future_impl.dart:560:7)
#30     _rootRun (dart:async/zone.dart:1184:13)
#31     _CustomZone.run (dart:async/zone.dart:1077:19)
#32     _CustomZone.runGuarded (dart:async/zone.dart:979:7)
#33     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1019:23)
#34     _microtaskLoop (dart:async/schedule_microtask.dart:43:21)
#35     _startMicrotaskLoop (dart:async/schedule_microtask.dart:52:5)
#36     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
#37     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:169:5)

```

**Comment by devhammed** [comment]
UPDATE: I found the fix at https://github.com/danvick/flutter_chips_input/issues/37

**Comment by TahaTesser** [comment]
@ghostsatan 
Without additional information we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution

**Comment by gururajahegde** [comment]
i got same issue,
tryied :
$ flutter build web

which showed several syntax errors, after fixing same that i could directly run 
$ flutter run -d chrome 

I am on master channel

**Comment by BrendonW** [comment]
Same Issue, Android Studio building for the web gives no error beyond:-
```
Running "flutter pub get" in my_app...                       0.6s
Launching lib/main.dart on Chrome in debug mode...
Syncing files to device Chrome...
Failed to compile application.
```

Using the command line gave the critical and obvious problem that AndroidStudio doesn't seem to notice:-
```
Firefly-22536:my_app brendon$ flutter build web
Target dart2js failed: Exception: lib/utilities/utilities.dart:45:13:   
Error: Can't assign to the final variable 'value'.
            value = val;
            ^^^^^
Error: Compilation failed.


Compiling lib/main.dart for the Web...                              8.4s
Exception: Failed to compile application for the Web.
```

Hope that helps somebody.

**Comment by TahaTesser** [comment]
Could everyone who still has this problem please file a new issue with the exact description of what happens, logs and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.

**Comment by EugenePisotsky** [comment]
@TahaTesser 

```
[✓] Flutter (Channel unknown, 1.20.0-1.0.pre.34, on Mac OS X 10.15.3 19D76, locale en-GB)
    • Flutter version 1.20.0-1.0.pre.34 at /Users/eugenepisotsky/Development/flutter
    • Framework revision eee3912f04 (89 minutes ago), 2020-06-12 10:33:24 -0700
    • Engine revision 965fbbed17
    • Dart version 2.9.0 (build 2.9.0-14.0.dev 2b917f5b6a)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/eugenepisotsky/Library/Android/sdk
    • Platform android-29, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.5, Build version 11E608c
    • CocoaPods version 1.8.4

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 42.1.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] IntelliJ IDEA Ultimate Edition (version 2020.1.1)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 46.0.3
    • Dart plugin version 201.7223.99

[✓] VS Code (version 1.45.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.0.2

[✓] Connected device (2 available)
    • Web Server • web-server • web-javascript • Flutter Tools
    • Chrome     • chrome     • web-javascript • Google Chrome 80.0.3987.149

• No issues found!
```

**Comment by bmcd243** [comment]
I've got the issue too.

```
MacBook-Pro:website benjamin$ flutter build web
Downloading Web SDK...                                              2.8s
Target dart2js failed: Exception:                                       
.dart_tool/flutter_build/05d20fef5ed9b95c5ed6913ba1f1ff6d/main.dart:9:3:
Error: Method not found: 'main'.
  entrypoint.main();
  ^^^^
Error: Compilation failed.


Compiling lib/main.dart for the Web...                              3.5s
Exception: Failed to compile application for the Web.
```

I have tried `flutter run -d chrome` too and that doesn't work as well as all the different flutter channels.

`flutter doctor -v`

```
MacBook-Pro:website benjamin$ flutter doctor -v
[✓] Flutter (Channel master, 1.20.0-1.0.pre.42, on Mac OS X 10.15.5 19F101,
    locale en-GB)
    • Flutter version 1.20.0-1.0.pre.42 at /Users/benjamin/flutter
    • Framework revision 401690a64f (2 days ago), 2020-06-12 19:45:48 -0700
    • Engine revision 965fbbed17
    • Dart version 2.9.0 (build 2.9.0-14.0.dev 2b917f5b6a)

[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from:
      https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK
      components.
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup
      for detailed instructions).
      If the Android SDK has been installed to a custom location, set
      ANDROID_SDK_ROOT to that location.
      You may also want to add it to your PATH environment variable.


 
[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.5, Build version 11E608c
    • CocoaPods version 1.9.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[!] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.46.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.11.0

 
[✓] Connected device (2 available)            
    • Web Server • web-server • web-javascript • Flutter Tools
    • Chrome     • chrome     • web-javascript • Google Chrome 83.0.4103.97

! Doctor found issues in 2 categories.
```

**Comment by liveplugin** [comment]
Same problem here.

`Launching lib/main.dart on Chrome in debug mode...
Syncing files to device Chrome...                                       
17,600ms (!)                                       
Failed to compile application.`

`[✓] Flutter (Channel beta, 1.19.0-4.1.pre, on Linux, locale en_US.UTF-8)
    • Flutter version 1.19.0-4.1.pre at /home/marciogomes/development/flutter
    • Framework revision f994b76974 (5 days ago), 2020-06-09 15:53:13 -0700
    • Engine revision 9a28c3bcf4
    • Dart version 2.9.0 (build 2.9.0-14.1.beta)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /home/marciogomes/Android/Sdk/
    • Platform android-29, build-tools 29.0.3
    • Java binary at: /home/marciogomes/development/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Android Studio (version 3.6)
    • Android Studio at /home/marciogomes/development/android-studio
    • Flutter plugin version 44.0.2
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)

[✓] VS Code (version 1.45.1)
    • VS Code at /usr/share/code
    • Flutter extension version 3.11.0

[✓] Connected device (2 available)
    • Web Server • web-server • web-javascript • Flutter Tools
    • Chrome     • chrome     • web-javascript • Google Chrome 81.0.4044.92

• No issues found!`

**Comment by liveplugin** [comment]
Same problem here.

```
> flutter run -d chrome --web-hostname localhost --web-port 8088
Launching lib/main.dart on Chrome in debug mode...
Syncing files to device Chrome...
17,600ms (!)
Failed to compile application.
```

```
[✓] Flutter (Channel beta, 1.19.0-4.1.pre, on Linux, locale en_US.UTF-8)
    • Flutter version 1.19.0-4.1.pre at /home/myname/development/flutter
    • Framework revision f994b76974 (5 days ago), 2020-06-09 15:53:13 -0700
    • Engine revision 9a28c3bcf4
    • Dart version 2.9.0 (build 2.9.0-14.1.beta)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)a
    • Android SDK at /home/myname/Android/Sdk/
    • Platform android-29, build-tools 29.0.3
    • Java binary at: /home/myname/development/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Android Studio (version 3.6)
    • Android Studio at /home/myname/development/android-studio
    • Flutter plugin version 44.0.2
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)

[✓] VS Code (version 1.45.1)
    • VS Code at /usr/share/code
    • Flutter extension version 3.11.0

[✓] Connected device (2 available)
    • Web Server • web-server • web-javascript • Flutter Tools
    • Chrome     • chrome     • web-javascript • Google Chrome 81.0.4044.92

• No issues found!
```

**Comment by akcgjc007** [comment]
Nothing new, I am also facing the same issue, I tried every single thing to run the flutter template application, but it kept giving me the error "failed to compile application".
Switching to other channels, flutter clean, nothing is working.

I hope someone will resolve this ASAP.

This is the flutter doctor:
```
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel beta, 1.19.0-4.1.pre, on Microsoft Windows [Version 10.0.18363.719], locale en-US)
[!] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    X Android license status unknown.
      Try re-installing or updating your Android SDK Manager.
      See https://developer.android.com/studio/#downloads or visit https://flutter.dev/docs/get-started/install/windows#android-setup for detailed
      instructions.
[√] Chrome - develop for the web
[√] Android Studio (version 3.6)
[√] VS Code, 64-bit edition (version 1.46.0)
[√] Connected device (2 available)

! Doctor found issues in 1 category.
```

Here is the only output:
```
Launching lib\main.dart on Chrome in debug mode...
Syncing files to device Chrome...
336,071ms (!)
Failed to compile application.
```

**Comment by bmcd243** [comment]
@akcgjc007 @liveplugin Are you able to run the demo app okay?

The issue with mine was that I had imported a file that didn't exist which confused it.

**Comment by liveplugin** [comment]
@bmcd243 my problem was a class that I didn't recognize the way I was doing it. So i commented out a line of code and it worked.

Run with `flutter run -d chrome -v` (with `-v` parameter) to find out exactly where your problem is occurring and see if it is possible to change anything.

Unfortunately I am not an expert to help with a more detailed answer.

**Comment by akcgjc007** [comment]
Hi @bmcd243, I was trying to get a basic sliverappbar done, so maybe I have tried to run some buggy syntax, that might have initiated something in the flutter SDK, which caused the whole error thing. 

At that time I wasn't able to run the demo app. 
But after uninstallation of Flutter and VS code, and reinstalling both, solved my problem.

For more details, check [Issue 59613](https://github.com/flutter/flutter/issues/59613)

**Comment by chitgoks** [comment]
> I am on master channel

woh. you can build web in master channel? i thought it's in beta only. cool.

**Comment by CherifD** [comment]
I have the same issue and I am on the beta channel.  Running "flutter build web" on the terminal produces the following:

Target dart2js failed: Exception:
/C:/Flutter/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_inappwebview-3.4.0+1/lib/src/X509Certificate/asn1_decoder.dart:163:25:
Error: The integer literal 9223372036854775807 can't be represented exactly in JavaScript.
    int int64MaxValue = 9223372036854775807;
                        ^^^^^^^^^^^^^^^^^^^
Error: Compilation failed.

**Comment by Manjunath375** [comment]
Target dart2js failed: Exception: /Applications/source/flutter/.pub-cache/hosted/pub.dartlang.org/steel_crypt-1.7.1+1/lib/PointyCastleN/stream/chacha20.dart:266:20:
Error: Only external js-interop functions are supported.
Try removing 'external' keyword or annotating the function as a js-interop function.
  external dynamic noSuchMethod(Invocation invocation);
                   ^
/Applications/source/flutter/.pub-cache/hosted/pub.dartlang.org/steel_crypt-1.7.1+1/lib/PointyCastleN/stream/chacha2012.dart:266:20:
Error: Only external js-interop functions are supported.
Try removing 'external' keyword or annotating the function as a js-interop function.
  external dynamic noSuchMethod(Invocation invocation);
                   ^
/Applications/source/flutter/.pub-cache/hosted/pub.dartlang.org/steel_crypt-1.7.1+1/lib/PointyCastleN/stream/chacha208.dart:266:20:
Error: Only external js-interop functions are supported.
Try removing 'external' keyword or annotating the function as a js-interop function.
  external dynamic noSuchMethod(Invocation invocation);
                   ^
Error: Compilation failed.

**Comment by pallavbohara** [comment]
I am getting this error:

> [  +18 ms] <- compile org-dartlang-app:/web_entrypoint.dart
> [+4819 ms]
>                     Compiler message:
> [   +3 ms] lib/services/navigation_service.dart:11:38: Error: This expression has type 'void' and can't be used.
> [   +2 ms]     return navigatorKey.currentState.pop();
> [   +1 ms]                                      ^
> [+34342 ms] Syncing files to device Chrome... (completed in 39,389ms, longer than expected)
> [   +2 ms] Synced 0.0MB.
> [   +1 ms] Failed to compile application.
> [   +9 ms] "flutter run" took 40,407ms.
> 
> #0      throwToolExit (package:flutter_tools/src/base/common.dart:14:3)
> #1      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:569:7)
> <asynchronous suspension>
> #2      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:797:18)
> #3      _rootRunUnary (dart:async/zone.dart:1198:47)
> #4      _CustomZone.runUnary (dart:async/zone.dart:1100:19)
> #5      _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
> #6      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
> #7      Future._propagateToListeners (dart:async/future_impl.dart:725:32)
> #8      Future._completeWithValue (dart:async/future_impl.dart:529:5)
> #9      _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:40:15)
> #10     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:311:13)
> #11     RunCommand.usageValues (package:flutter_tools/src/commands/run.dart)
> #12     _rootRunUnary (dart:async/zone.dart:1198:47)
> #13     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
> #14     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
> #15     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
> #16     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
> #17     Future._completeWithValue (dart:async/future_impl.dart:529:5)
> #18     Future._asyncCompleteWithValue.<anonymous closure> (dart:async/future_impl.dart:567:7)
> #19     _rootRun (dart:async/zone.dart:1190:13)
> #20     _CustomZone.run (dart:async/zone.dart:1093:19)
> #21     _CustomZone.runGuarded (dart:async/zone.dart:997:7)
> #22     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1037:23)
> #23     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
> #24     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
> #25     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
> #26     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:169:5)
> 
> 
> 
> [ +411 ms] Running shutdown hooks
> [   +2 ms] Shutdown hook priority 4
> [  +19 ms] Shutdown hooks complete
> PS G:\flutter_projects\web\00-starting> code .
> PS G:\flutter_projects\web\00-starting> flutterb --version
> Flutter 1.19.0-4.2.pre • channel beta • https://github.com/flutter/flutter.git
> Framework • revision 9b9b543d92 (9 weeks ago) • 2020-06-22 12:19:28 -0700
> Engine • revision 9a28c3bcf4
> Tools • Dart 2.9.0 (build 2.9.0-14.1.beta)

[037-starting-code.zip](https://github.com/flutter/flutter/files/5129471/037-starting-code.zip)
I am following this tutorial.
Also attaching zip to reproduce the error.

**Comment by TahaTesser** [comment]
Could everyone who still has this problem please file a new issue with the exact description of what happens, logs and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
