### ISSUE TITLE
[tool_crash] ArgumentError: Invalid argument(s): Cannot find executable for C:\Users\krimtel-3\AndroidStudioProjects\shakuntalagroup\android\gradlew.bat.

### ISSUE THREAD

**Issue by ravikant16** [flutter/flutter#56975]
## Command
```
flutter --no-color run --machine --track-widget-creation --device-id=3d6aa77 lib\main.dart
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
ArgumentError: Invalid argument(s): Cannot find executable for C:\Users\krimtel-3\AndroidStudioProjects\shakuntalagroup\android\gradlew.bat.
```
#0      _getExecutable (package:process/src/interface/local_process_manager.dart:127:5)
#1      LocalProcessManager.start (package:process/src/interface/local_process_manager.dart:43:30)
#2      _DefaultProcessUtils.start (package:flutter_tools/src/base/process.dart:462:28)
#3      _DefaultProcessUtils.stream (package:flutter_tools/src/base/process.dart:480:35)
#4      buildGradleApp (package:flutter_tools/src/android/gradle.dart:385:35)
#5      _AndroidBuilderImpl.buildApk (package:flutter_tools/src/android/android_builder.dart:102:13)
#6      AndroidDevice.startApp (package:flutter_tools/src/android/android_device.dart:513:28)
#7      _rootRunUnary (dart:async/zone.dart:1192:38)
#8      _CustomZone.runUnary (dart:async/zone.dart:1085:19)
#9      _FutureListener.handleValue (dart:async/future_impl.dart:141:18)
#10     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:682:45)
#11     Future._propagateToListeners (dart:async/future_impl.dart:711:32)
#12     Future._completeWithValue (dart:async/future_impl.dart:526:5)
#13     Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:556:7)
#14     _rootRun (dart:async/zone.dart:1184:13)
#15     _CustomZone.run (dart:async/zone.dart:1077:19)
#16     _CustomZone.runGuarded (dart:async/zone.dart:979:7)
#17     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1019:23)
#18     _microtaskLoop (dart:async/schedule_microtask.dart:43:21)
#19     _startMicrotaskLoop (dart:async/schedule_microtask.dart:52:5)
#20     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
#21     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:169:5)
```
```
[✓] Flutter (Channel dev, v1.18.0-dev.5.0, on Microsoft Windows [Version 10.0.18362.778], locale en-US)
    • Flutter version 1.18.0-dev.5.0 at D:\flutter
    • Framework revision 7f56b53de4 (4 weeks ago), 2020-04-12 12:00:01 -0400
    • Engine revision beb8a7ec48
    • Dart version 2.8.0 (build 2.8.0-dev.20.0 89b0f67261)

[!] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at C:\Users\krimtel-3\AppData\Local\Android\Sdk
    • Platform android-29, build-tools 29.0.2
    • ANDROID_HOME = C:/Users/krimtel-3/AppData/Local/Android/Sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)
    ✗ Android license status unknown.
      Try re-installing or updating your Android SDK Manager.
      See https://developer.android.com/studio/#downloads or visit visit https://flutter.dev/docs/get-started/install/windows#android-setup for detailed instructions.

[✓] Android Studio (version 3.6)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)

[✓] VS Code (version 1.44.2)
    • VS Code at C:\Users\krimtel-3\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.10.1

[✓] Connected device (1 available)
    • A37f • 3d6aa77 • android-arm64 • Android 5.1.1 (API 22)

! Doctor found issues in 1 category.

```

## Flutter Application Metadata
**Type**: app
**Version**: 1.3.3+37
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: dev
**Creation framework version**: 09126abb222d0f25b03318a1ab4a99d27d9aaa8d
### Plugins
firebase_messaging-6.0.13
fluttertoast-4.0.1
razorpay_flutter-1.1.3
shared_preferences-0.5.6+3
shared_preferences_macos-0.0.1+6
shared_preferences_web-0.1.2+4
url_launcher-5.4.2
url_launcher_macos-0.0.1+4
url_launcher_web-0.1.1+1

**Comment by TahaTesser** [comment]
Hi @ravikant16 
can you please provide your `flutter run --verbose`? 
Thank you

**Comment by amikum1997** [comment]
$ flutter run --verbose
[  +17 ms] executing: [C:\flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[  +41 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[        ] e6b34c2b5c96bb95325269a29a84e83ed8909b5f
[        ] executing: [C:\flutter/] git tag --contains HEAD
[ +177 ms] Exit code 0 from: git tag --contains HEAD
[        ] 1.17.0
           1.17.0-3.4.pre
[  +11 ms] executing: [C:\flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[  +23 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/stable
[        ] executing: [C:\flutter/] git ls-remote --get-url origin
[  +17 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[  +81 ms] executing: [C:\flutter/] git rev-parse --abbrev-ref HEAD
[  +17 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] stable
[  +50 ms] Downloading Gradle Wrapper...
[  +12 ms] Downloading: https://storage.googleapis.com/flutter_infra/gradle-wrapper/fd5c1f2c013565a3bea56ada6df9d2b8e96d56aa/gradle-wrapper.tgz
[ +963 ms] Received response from server, collecting bytes...
[ +130 ms] Downloading Gradle Wrapper... (completed in 1.1s)
[  +82 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +3 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +23 ms] executing: C:\Users\HP\AppData\Local\Android\sdk\platform-tools\adb.exe devices -l
[  +38 ms] List of devices attached
           5aee3bcc               device product:1951 model:vivo_1951 device:1951 transport_id:1
[   +6 ms] C:\Users\HP\AppData\Local\Android\sdk\platform-tools\adb.exe -s 5aee3bcc shell getprop
[  +80 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[   +3 ms] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +1 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[ +191 ms] Generating E:\PROJECTS\FLUTTER\abhilasha\android\app\src\main\java\io\flutter\plugins\GeneratedPluginRegistrant.java
[  +32 ms] ro.hardware = qcom
[  +33 ms] Launching lib\main.dart on vivo 1951 in debug mode...
[   +7 ms] C:\flutter\bin\cache\dart-sdk\bin\dart.exe C:\flutter\bin\cache\artifacts\engine\windows-x64\frontend_server.dart.snapshot --sdk-root C:\flutter\bin\cache\artifacts\engine\common\flutter_patched_sdk/ --incremental --target=flutter --debugger-module-names -Ddart.developer.causal_async_stacks=true --output-dill C:\Users\HP\AppData\Local\Temp\flutter_tool.0c6da4b4-948c-11ea-859a-a0605d4bfc4b\app.dill --packages E:\PROJECTS\FLUTTER\abhilasha\.packages -Ddart.vm.profile=false -Ddart.vm.product=false --bytecode-options=source-positions,local-var-info,debugger-stops,instance-field-initializers,keep-unreachable-code,avoid-closure-call-instructions --enable-asserts --track-widget-creation --filesystem-scheme org-dartlang-root --initialize-from-dill build\cache.dill
[  +14 ms] executing: C:\Users\HP\AppData\Local\Android\sdk\platform-tools\adb.exe -s 5aee3bcc shell -x logcat -v time -t 1
[ +224 ms] Exit code 0 from: C:\Users\HP\AppData\Local\Android\sdk\platform-tools\adb.exe -s 5aee3bcc shell -x logcat -v time -t 1
[        ] --------- beginning of main
           05-13 01:36:23.496 I/SDM     (  649): HWDeviceDRM::SetupAtomic: Disable DE for Non YUV
[   +5 ms] <- compile package:abhilasha/main.dart
[  +13 ms] executing: C:\Users\HP\AppData\Local\Android\sdk\platform-tools\adb.exe version
[  +38 ms] Android Debug Bridge version 1.0.41
           Version 30.0.1-6435776
           Installed as C:\Users\HP\AppData\Local\Android\sdk\platform-tools\adb.exe
[   +3 ms] executing: C:\Users\HP\AppData\Local\Android\sdk\platform-tools\adb.exe start-server
[  +38 ms] Building APK
[  +29 ms] Running Gradle task 'assembleDebug'...
[   +3 ms] gradle.properties already sets `android.enableR8`
[  +17 ms] C:\flutter\bin\cache\artifacts\gradle_wrapper\gradlew.bat mode: 33279 rwxrwxrwx.
[        ] E:\PROJECTS\FLUTTER\abhilasha\android\gradlew.bat mode: 33279 rwxrwxrwx.
[        ] Using gradle from E:\PROJECTS\FLUTTER\abhilasha\android\gradlew.bat.
[        ] E:\PROJECTS\FLUTTER\abhilasha\android\gradlew.bat mode: 33279 rwxrwxrwx.
[   +9 ms] executing: C:\Program Files\Android\Android Studio\jre\bin\java -version
[ +157 ms] Exit code 0 from: C:\Program Files\Android\Android Studio\jre\bin\java -version
[        ] openjdk version "1.8.0_212-release"
           OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)
           OpenJDK 64-Bit Server VM (build 25.212-b04, mixed mode)
[   +4 ms] executing: [E:\PROJECTS\FLUTTER\abhilasha\android/] E:\PROJECTS\FLUTTER\abhilasha\android\gradlew.bat -Pverbose=true -Ptarget-platform=android-arm64 -Ptarget=E:\PROJECTS\FLUTTER\abhilasha\lib\main.dart -Ptrack-widget-creation=true -Pfilesystem-scheme=org-dartlang-root assembleDebug
[   +3 ms] Running Gradle task 'assembleDebug'... (completed in 0.2s)
[+5415 ms] "flutter run" took 7,670ms.

Oops; flutter has exited unexpectedly: "Invalid argument(s): Cannot find executable for E:\PROJECTS\FLUTTER\abhilasha\android\gradlew.bat.".
[+2336 ms] executing: C:\Program Files\Android\Android Studio\jre\bin\java -version
[  +77 ms] Exit code 0 from: C:\Program Files\Android\Android Studio\jre\bin\java -version
[        ] openjdk version "1.8.0_212-release"
           OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)
           OpenJDK 64-Bit Server VM (build 25.212-b04, mixed mode)
[  +14 ms] executing: [C:\flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%ar
[  +18 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%ar
[        ] 10 days ago
A crash report has been written to E:\PROJECTS\FLUTTER\abhilasha\flutter_02.log.
This crash may already be reported. Check GitHub for similar crashes.
https://git.io/Jf8ow

To report your crash to the Flutter team, first read the guide to filing a bug.
https://flutter.dev/docs/resources/bug-reports

Create a new GitHub issue by pasting this link into your browser and completing the issue template. Thank you!
https://git.io/Jf8y8

**Comment by iapicca** [comment]
Possible duplicate of https://github.com/flutter/flutter/issues/53790

**Comment by VladyslavBondarenko** [comment]
Related to https://github.com/flutter/flutter/issues/56628 - there `sdkmanager.bat` and `gradlew.bat` are deleted by antivirus

**Comment by SadSack963** [comment]
I spent two days chasing this on another user's system. In his case it was definitely AVG that was deleting / hiding sdkmanager.bat. Uninstalling AVG has removed that issue. However, today, his gradlew.bat in the project/android folder is doing the same. Even when copying it in Windows Explorer it simply disappears. I'm still trying to track down what is causing that.

It appears that Windows Defender may be the cause, and of course we can't turn that off in Home edition. So it's a case of reinstalling AVG and adding exceptions in Menu -> Settings -> General -> Exceptions for the relevant folders, typically:
C:\Users\[username]\AppData\Local\Android\* and
C:\Users\[username]\AndroidStudioProjects\*

Finally! That seems to have done the trick. I also got him to turn off Resident Shield just in case. We then copied known good versions of gradlew and gradlew.bat from "C:\Program Files\Android\Android Studio\plugins\android\lib\templates\gradle\wrapper" into the project\android folder, and I uploaded my sdkmanager.bat so that he could put it in C:\Users\[username]\AppData\Local\Android\Sdk\tools\bin. It all works now, and he built his first project!

HTH

**Comment by fantania** [comment]
@SadSack963 Hi, Itried everything you sayed but the  grandlew.bat fil is still getting deleted :(

**Comment by SadSack963** [comment]
@fantania The only reason a file is being mysteriously deleted is if another program is deleting it (obvious statement really :) This is invariably due to an antivirus program of one description or another. It is highly unlikely to be an actual virus.

I can only suggest that you look through the Task Manager processes and disable anything suspicious (one by one) until you find the culprit. You can then permanently uninstall or disable that item. (IOBit Uninstaller is good for this.) Ignore all Microsoft processes - they are fine. 

Check through the Start-up processes and disable anything you don't like the look of. 
Also check the Services tab as a last resort. Use the Status column to look for Running processes and go through those.

Do take a bit of care though - if you disable the wrong thing you might cause problems on your PC, and possibly even stop it booting. If that happens, you should still be able to boot into Safe Mode to repair. Better yet, take a backup of the drive if you can so that you can restore if all hell breaks loose! Check in your favourite search engine for anything you don't recognise. You are looking specifically for third party antivirus software, such as AVG, Symantec, Avast, santivirusIC, Comodo, etc. There are hundreds, I can't list them all...

**Comment by fantania** [comment]
@SadSack963 thank you very much, I’ll try this tomorrow and I’ll let you know. Thanks again

**Comment by SadSack963** [comment]
@fantania By the way, I am not suggesting that you run your PC without antivirus protection. Microsoft Defender is OK, but I have used Avast on my Windoze systems for years. 

You often find that "free" AV programs are quietly installed alongside one or other package that you have downloaded from the Internet. I have found it good practice to always choose the "custom" option when installing stuff that I've downloaded, to hopefully give you the option to not install promoted packages along with the program you actually want.

You should only have one AV running on your PC at any time, otherwise you will find that it slows down all file access because they're being scanned multiple times. Just make sure you have the exceptions configured to ignore these couple of files.

**Comment by fantania** [comment]
@SadSack963 Thank you very much, you were right; I went through Task Manager processes and I found a virus called ICSAnt running in background. After removing it, I was able to create a new project. Thank you again

**Comment by SadSack963** [comment]
> @SadSack963 Thank you very much, you were right; I went through Task Manager processes and I found a virus called ICSAnt running in background. After removing it, I was able to create a new project. Thank you again

@fantania  Well done! Be careful installing stuff in future :)

**Comment by fantania** [comment]
> > @SadSack963 Thank you very much, you were right; I went through Task Manager processes and I found a virus called ICSAnt running in background. After removing it, I was able to create a new project. Thank you again
> 
> @fantania Well done! Be careful installing stuff in future :)

:) sure, @SadSack963

**Comment by eduardo-cervantes** [comment]
Apparently my problem is not related, or is not identical, to the problems previously solved.
It seems to me, that Dart is trying to open the program with the specified name directly in the CMakeList.txt file, without being read through a variable.

For more details: https://github.com/flutter/flutter/issues/71867

On the line, from the CMakeList.txt file, if I change to:
```
set (BINARY_NAME" app_name ")
```
It will work perfectly, as I have been doing for months. However, if I add the value to a variable first:

```
set (COMPILER_NAME "app_name")
set (BINARY_NAME "$ {COMPILER_NAME}")
```

It displays the error:
**Oops; flutter has exited unexpectedly: "Invalid argument (s): Cannot find executable for build \ windows \ runner \ Debug \ $ {COMPILER_NAME} .exe.".**

**Comment by vitorcortinovis** [comment]
I had the same problem with the files `gradlew.bat` and `sdkmanager.bat` ... Following the tips of this and other Github topics, I found that I had antivirus installed that were removing these files.

After uninstalling, on Android Studio I reinstalled the SDK and my projects worked normally on Flutter!
