### ISSUE TITLE
Error: Could not find or load main class org.gradle.wrapper.GradleWrapperMain

### ISSUE THREAD

**Issue by mzkai** [flutter/flutter#56984]
## Overview
I can run my applications on all supported platforms without any issues i.e., iOS, macOS, and Web. However for Android I consistently get the error **Error: Could not find or load main class org.gradle.wrapper.GradleWrapperMain**, despite having followed the recommendations found in  #14422 and #17280.

I therefore reinstalled Android Studio, SDKs etc. to create a new Flutter project from scratch. Unfortunately the same error occurs as seen below.

## Steps to Reproduce

1. Run `flutter create flutter_app`.
2. Run `flutter run` in the flutter_app folder with connected Android emulator
3. Errors occur

**Expected results:** 
I expected that the application would run on the Android emulator without errors

**Actual results:** 
Using hardware rendering with device sdk gphone x86. If you get graphics artifacts, consider enabling software rendering
with "--enable-software-rendering".
Launching lib/main.dart on sdk gphone x86 in debug mode...
**Error: Could not find or load main class org.gradle.wrapper.GradleWrapperMain**
Running Gradle task 'assembleDebug'...                                  
Running Gradle task 'assembleDebug'... Done                         0.8s
**Exception: Gradle task assembleDebug failed with exit code 1**

<details>
  <summary>Logs</summary>

```
flutter run --verbose
[  +14 ms] /Users/simon52/Library/Android/sdk/platform-tools/adb -s emulator-5554 shell getprop
[ +160 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[   +7 ms] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[   +5 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[   +5 ms] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[ +604 ms] Generating
/Users/simon52/Desktop/android_flutter_test/flutter_app/android/app/src/main/java/io/flutter/plugins/GeneratedPluginRegistr
ant.java
[  +76 ms] ro.hardware = ranchu
[  +91 ms] Using hardware rendering with device sdk gphone x86. If you get graphics artifacts, consider enabling software
rendering
           with "--enable-software-rendering".
[  +70 ms] Launching lib/main.dart on sdk gphone x86 in debug mode...
[  +18 ms] /Users/simon52/SDKs/flutter/bin/cache/dart-sdk/bin/dart
/Users/simon52/SDKs/flutter/bin/cache/artifacts/engine/darwin-x64/frontend_server.dart.snapshot --sdk-root
/Users/simon52/SDKs/flutter/bin/cache/artifacts/engine/common/flutter_patched_sdk/ --incremental --target=flutter
--debugger-module-names -Ddart.developer.causal_async_stacks=true --output-dill
/var/folders/s3/15x35cv96c75mwfkjd2zsf880000gn/T/flutter_tool.b1Dghj/app.dill --packages .packages -Ddart.vm.profile=false
-Ddart.vm.product=false
--bytecode-options=source-positions,local-var-info,debugger-stops,instance-field-initializers,keep-unreachable-code,avoid-
closure-call-instructions --enable-asserts --track-widget-creation --filesystem-scheme org-dartlang-root
--initialize-from-dill build/cache.dill.track.dill
[  +46 ms] executing: /Users/simon52/Library/Android/sdk/platform-tools/adb -s emulator-5554 shell -x logcat -v time -t 1
[ +130 ms] Exit code 0 from: /Users/simon52/Library/Android/sdk/platform-tools/adb -s emulator-5554 shell -x logcat -v time
-t 1
[   +1 ms] --------- beginning of main
           05-12 11:04:55.896 W/IsoInterface( 1531): Missing 'ftyp' header
[  +51 ms] <- compile package:flutter_app/main.dart
[  +36 ms] executing: /Users/simon52/Library/Android/sdk/platform-tools/adb version
[  +63 ms] Android Debug Bridge version 1.0.41
           Version 30.0.1-6435776
           Installed as /Users/simon52/Library/Android/sdk/platform-tools/adb
[  +11 ms] executing: /Users/simon52/Library/Android/sdk/platform-tools/adb start-server
[  +40 ms] Building APK
[ +109 ms] Running Gradle task 'assembleDebug'...
[  +16 ms] gradle.properties already sets `android.enableR8`
[   +9 ms] Using gradle from /Users/simon52/Desktop/android_flutter_test/flutter_app/android/gradlew.
[   +2 ms] /Users/simon52/Desktop/android_flutter_test/flutter_app/android/gradlew mode: 33261 rwxr-xr-x.
[  +27 ms] executing: /usr/bin/plutil -convert json -o - /Applications/Android Studio.app/Contents/Info.plist
[  +27 ms] Exit code 0 from: /usr/bin/plutil -convert json -o - /Applications/Android Studio.app/Contents/Info.plist
[  +45 ms] {"CFBundleName":"Android
Studio","JVMOptions":{"ClassPath":"$APP_PACKAGE\/Contents\/lib\/bootstrap.jar:$APP_PACKAGE\/Contents\/lib\/extensions.jar:
$APP_PACKAGE\/Contents\/lib\/util.jar:$APP_PACKAGE\/Contents\/lib\/jdom.jar:$APP_PACKAGE\/Contents\/lib\/log4j.jar:$APP_PA
CKAGE\/Contents\/lib\/trove4j.jar:$APP_PACKAGE\/Contents\/lib\/jna.jar","JVMVersion":"1.8*,1.8+","WorkingDirectory":"$APP_
PACKAGE\/Contents\/bin","MainClass":"com.intellij.idea.Main","Properties":{"idea.paths.selector":"AndroidStudio3.6","idea.
executable":"studio","idea.platform.prefix":"AndroidStudio","idea.home.path":"$APP_PACKAGE\/Contents"}},"NSDesktopFolderUs
ageDescription":"An application in Android Studio requests access to the user's Desktop
folder.","LSArchitecturePriority":["x86_64"],"CFBundleVersion":"AI-192.7142.36.36.6392135","CFBundleDevelopmentRegion":"En
glish","NSCameraUsageDescription":"An application in Android Studio requests access to the device's
camera.","CFBundleDocumentTypes":[{"CFBundleTypeName":"Android Studio Project
File","CFBundleTypeExtensions":["ipr"],"CFBundleTypeRole":"Editor","CFBundleTypeIconFile":"studio.icns"},{"CFBundleTypeNam
e":"All
documents","CFBundleTypeExtensions":["*"],"CFBundleTypeOSTypes":["****"],"CFBundleTypeRole":"Editor","LSTypeIsPackage":fal
se}],"NSSupportsAutomaticGraphicsSwitching":true,"CFBundlePackageType":"APPL","CFBundleIconFile":"studio.icns","NSHighReso
lutionCapable":true,"CFBundleShortVersionString":"3.6","NSMicrophoneUsageDescription":"An application in Android Studio
requests access to the device's
microphone.","CFBundleInfoDictionaryVersion":"6.0","CFBundleExecutable":"studio","NSLocationUsageDescription":"An
application in Android Studio requests access to the user's location
information.","LSRequiresNativeExecution":"YES","CFBundleURLTypes":[{"CFBundleTypeRole":"Editor","CFBundleURLName":"Stackt
race","CFBundleURLSchemes":["idea"]}],"CFBundleIdentifier":"com.google.android.studio","LSApplicationCategoryType":"public
.app-category.developer-tools","CFBundleSignature":"????","LSMinimumSystemVersion":"10.8","NSDocumentsFolderUsageDescripti
on":"An application in Android Studio requests access to the user's Documents
folder.","NSDownloadsFolderUsageDescription":"An application in Android Studio requests access to the user's Downloads
folder.","NSNetworkVolumesUsageDescription":"An application in Android Studio requests access to files on a network
volume.","CFBundleGetInfoString":"Android Studio 3.6, build AI-192.7142.36.36.6392135. Copyright JetBrains s.r.o., (c)
2000-2020","NSRemovableVolumesUsageDescription":"An application in Android Studio requests access to files on a removable
volume."}
[  +17 ms] executing: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java -version
[ +620 ms] Exit code 0 from: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java -version
[   +2 ms] openjdk version "1.8.0_212-release"
           OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
           OpenJDK 64-Bit Server VM (build 25.212-b4-5784211, mixed mode)
[   +7 ms] executing: [/Users/simon52/Desktop/android_flutter_test/flutter_app/android/]
/Users/simon52/Desktop/android_flutter_test/flutter_app/android/gradlew -Pverbose=true -Ptarget-platform=android-x86
-Ptarget=/Users/simon52/Desktop/android_flutter_test/flutter_app/lib/main.dart -Ptrack-widget-creation=true
-Pfilesystem-scheme=org-dartlang-root assembleDebug
[ +563 ms] Error: Could not find or load main class org.gradle.wrapper.GradleWrapperMain
[  +45 ms] Running Gradle task 'assembleDebug'... (completed in 1.4s)
[+13071 ms] Exception: Gradle task assembleDebug failed with exit code 1
[   +4 ms] "flutter run" took 20,787ms.

#0      throwToolExit (package:flutter_tools/src/base/common.dart:14:3)
#1      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:570:7)
<asynchronous suspension>
#2      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:799:18)
#3      _rootRunUnary (dart:async/zone.dart:1198:47)
#4      _CustomZone.runUnary (dart:async/zone.dart:1100:19)
#5      _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
#6      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
#7      Future._propagateToListeners (dart:async/future_impl.dart:725:32)
#8      Future._completeWithValue (dart:async/future_impl.dart:529:5)
#9      _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:40:15)
#10     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:311:13)
#11     RunCommand.usageValues (package:flutter_tools/src/commands/run.dart)
#12     _rootRunUnary (dart:async/zone.dart:1198:47)
#13     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
#14     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
#15     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
#16     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
#17     Future._completeWithValue (dart:async/future_impl.dart:529:5)
#18     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:40:15)
#19     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:311:13)
#20     AndroidDevice.isLocalEmulator (package:flutter_tools/src/android/android_device.dart)
#21     _rootRunUnary (dart:async/zone.dart:1198:47)
#22     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
#23     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
#24     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
#25     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
#26     Future._completeWithValue (dart:async/future_impl.dart:529:5)
#27     Future._asyncCompleteWithValue.<anonymous closure> (dart:async/future_impl.dart:567:7)
#28     _rootRun (dart:async/zone.dart:1190:13)
#29     _CustomZone.run (dart:async/zone.dart:1093:19)
#30     _CustomZone.runGuarded (dart:async/zone.dart:997:7)
#31     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1037:23)
#32     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#33     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#34     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
#35     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:169:5)
```

```
flutter analyze
Analyzing flutter_app...                                                
No issues found! (ran in 2.7s)
```

```
flutter doctor -v
[✓] Flutter (Channel master, 1.19.0-1.0.pre.42, on Mac OS X 10.15.4 19E287, locale en-GB)
    • Flutter version 1.19.0-1.0.pre.42 at /Users/moon12/SDKs/flutter
    • Framework revision 7f8cb7f830 (12 hours ago), 2020-05-11 13:34:20 -0700
    • Engine revision ada8a0fd64
    • Dart version 2.9.0 (build 2.9.0-8.0.dev a6d06b59ec)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/moon12/Library/Android/sdk
    • Platform android-29, build-tools 29.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.4.1, Build version 11E503a
    • CocoaPods version 1.9.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)

[✓] VS Code (version 1.45.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.10.1

[✓] Connected device (3 available)
    • macOS      • macOS      • darwin-x64     • Mac OS X 10.15.4 19E287
    • Web Server • web-server • web-javascript • Flutter Tools
    • Chrome     • chrome     • web-javascript • Google Chrome 81.0.4044.138

• No issues found!
```

</details>

**Comment by VladyslavBondarenko** [comment]
I couldn't reproduce with master `1.19.0-1.0.pre.49`.
New created app is built and running

**Comment by mzkai** [comment]
The application would suddenly build, after I added Cloud Firestore to the project. I looked back at the changes I made in the android files, as one of these much have solved the issue:

android/build.gradle:
* Added "classpath 'com.google.gms:google-services:4.3.3'" under "dependencies"
android/app/build.gradle:
* Added "apply plugin: 'com.google.gms.google-services'"
* Added "implementation 'com.google.firebase:firebase-analytics:17.2.2'" under "dependencies"
android/app:
* Added the file "google-services.json" to the folder

Would these changes really be what was needed to solve the issue?

**Comment by Adamoc14** [comment]
The only thing that seemed to make it work for me was changing the space or any sort of slash in my folder or in the path to the folder that the project was in, Gradle must not like this and exits but yeah removing space and slashes from the path to and the surrounding folder of the project will resolve this issue I found  :)

**Comment by reidlai** [comment]
Have the same issue here but it is working in VSCode env...no idea why this happened in shell environment

**Comment by ameenbadri7** [comment]
i just changed the folder name from fluxstore-pro1.0.8/02 Oct, 2020 to 1 
and its work !!
three days and its only the name of the folder >>> F..

**Comment by Sukrit22** [comment]
mine is because the folder name is in Korean. I would suggest the app folder name to contain only English with no space in the name and in the path to the program

**Comment by KhalldT** [comment]
I saw the solution above and yes, it's right, my file path contained an Arabic word so I changed the path and it works now!

**Comment by seanmamasde** [comment]
Just fixed my folder name and it worked... Does this kind of thing count as a **bug**?
