### ISSUE TITLE
[webview_flutter] `setAndGetScrollPosition` is flaky on ci.

### ISSUE THREAD

**Issue by cyanglaz** [flutter/flutter#57041]
```
flutter: 00:11 +12: Programmatic Scroll setAndGetScrollPosition
flutter: (The following exception is now available via WidgetTester.takeException:)
flutter: ══╡ EXCEPTION CAUGHT BY FLUTTER TEST FRAMEWORK ╞════════════════════════════════════════════════════
flutter: The following TestFailure object was thrown running a test:
flutter:   Expected: <0>
flutter:   Actual: <321>
flutter:
flutter: When the exception was thrown, this was the stack:
flutter: #4      main.<anonymous closure>.<anonymous closure> (file:///private/var/folders/3y/l0z1x3693dl_8n0qybp4dqwh0000gn/T/cirrus-ci-build/packages/webview_flutter/example/test_driver/webview_flutter_e2e.dart:617:7)
flutter: <asynchronous suspension>
flutter: #5      main.<anonymous closure>.<anonymous closure> (file:///private/var/folders/3y/l0z1x3693dl_8n0qybp4dqwh0000gn/T/cirrus-ci-build/packages/webview_flutter/example/test_driver/webview_flutter_e2e.dart)
flutter: #6      testWidgets.<anonymous closure>.<anonymous closure> (package:flutter_test/src/widget_tester.dart:144:29)
flutter: <asynchronous suspension>
flutter: #7      testWidgets.<anonymous closure>.<anonymous closure> (package:flutter_test/src/widget_tester.dart)
flutter: #8      TestWidgetsFlutterBinding._runTestBody (package:flutter_test/src/binding.dart:703:19)
flutter: <asynchronous suspension>
flutter: #11     TestWidgetsFlutterBinding._runTest (package:flutter_test/src/binding.dart:683:14)
flutter: #12     LiveTestWidgetsFlutterBinding.runTest (package:flutter_test/src/binding.dart:1471:12)
flutter: #13     E2EWidgetsFlutterBinding.runTest (package:e2e/e2e.dart:100:17)
flutter: #14     testWidgets.<anonymous closure> (package:flutter_test/src/widget_tester.dart:137:24)
flutter: #15     Declarer.test.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:test_api/src/backend/declarer.dart:172:27)
flutter: <asynchronous suspension>
flutter: #16     Declarer.test.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:test_api/src/backend/declarer.dart)
flutter: #17     Invoker.waitForOutstandingCallbacks.<anonymous closure> (package:test_api/src/backend/invoker.dart:246:15)
flutter: #22     Invoker.waitForOutstandingCallbacks (package:test_api/src/backend/invoker.dart:243:5)
flutter: #23     Declarer.test.<anonymous closure>.<anonymous closure> (package:test_api/src/backend/declarer.dart:170:33)
flutter: #28     Declarer.test.<anonymous closure> (package:test_api/src/backend/declarer.dart:169:13)
flutter: #29     Invoker._onRun.<anonymous closure>.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:test_api/src/backend/invoker.dart:400:30)
flutter: (elided 26 frames from class _RawReceivePortImpl, class _Timer, dart:async, dart:async-patch, and package:stack_trace)
flutter:
flutter: This was caught by the test expectation on the following line:
flutter:   file:///private/var/folders/3y/l0z1x3693dl_8n0qybp4dqwh0000gn/T/cirrus-ci-build/packages/webview_flutter/example/test_driver/webview_flutter_e2e.dart line 617
flutter: The test description was:
flutter:   setAndGetScrollPosition
flutter: ════════════════════════════════════════════════════════════════════════════════════════════════════
flutter: (If WidgetTester.takeException is called, the above exception will be ignored. If it is not, then the above exception will be dumped when another exception is caught by the framework or when the test ends, whichever happens first, and then the test will fail due to having not caught or expected the exception.)
flutter: ══╡ EXCEPTION CAUGHT BY FLUTTER TEST FRAMEWORK ╞════════════════════════════════════════════════════
flutter: The following TestFailure object was thrown running a test:
flutter:   Expected: <0>
flutter:   Actual: <321>
flutter:
flutter: When the exception was thrown, this was the stack:
flutter: #4      main.<anonymous closure>.<anonymous closure> (file:///private/var/folders/3y/l0z1x3693dl_8n0qybp4dqwh0000gn/T/cirrus-ci-build/packages/webview_flutter/example/test_driver/webview_flutter_e2e.dart:617:7)
flutter: <asynchronous suspension>
flutter: #5      main.<anonymous closure>.<anonymous closure> (file:///private/var/folders/3y/l0z1x3693dl_8n0qybp4dqwh0000gn/T/cirrus-ci-build/packages/webview_flutter/example/test_driver/webview_flutter_e2e.dart)
flutter: #6      testWidgets.<anonymous closure>.<anonymous closure> (package:flutter_test/src/widget_tester.dart:144:29)
flutter: <asynchronous suspension>
flutter: #7      testWidgets.<anonymous closure>.<anonymous closure> (package:flutter_test/src/widget_tester.dart)
flutter: #8      TestWidgetsFlutterBinding._runTestBody (package:flutter_test/src/binding.dart:703:19)
flutter: <asynchronous suspension>
flutter: #11     TestWidgetsFlutterBinding._runTest (package:flutter_test/src/binding.dart:683:14)
flutter: #12     LiveTestWidgetsFlutterBinding.runTest (package:flutter_test/src/binding.dart:1471:12)
flutter: #13     E2EWidgetsFlutterBinding.runTest (package:e2e/e2e.dart:100:17)
flutter: #14     testWidgets.<anonymous closure> (package:flutter_test/src/widget_tester.dart:137:24)
flutter: #15     Declarer.test.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:test_api/src/backend/declarer.dart:172:27)
flutter: <asynchronous suspension>
flutter: #16     Declarer.test.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:test_api/src/backend/declarer.dart)
flutter: #17     Invoker.waitForOutstandingCallbacks.<anonymous closure> (package:test_api/src/backend/invoker.dart:246:15)
flutter: #22     Invoker.waitForOutstandingCallbacks (package:test_api/src/backend/invoker.dart:243:5)
flutter: #23     Declarer.test.<anonymous closure>.<anonymous closure> (package:test_api/src/backend/declarer.dart:170:33)
flutter: #28     Declarer.test.<anonymous closure> (package:test_api/src/backend/declarer.dart:169:13)
flutter: #29     Invoker._onRun.<anonymous closure>.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:test_api/src/backend/invoker.dart:400:30)
flutter: (elided 26 frames from class _RawReceivePortImpl, class _Timer, dart:async, dart:async-patch, and package:stack_trace)
flutter:
flutter: This was caught by the test expectation on the following line:
flutter:   file:///private/var/folders/3y/l0z1x3693dl_8n0qybp4dqwh0000gn/T/cirrus-ci-build/packages/webview_flutter/example/test_driver/webview_flutter_e2e.dart line 617
flutter: The test description was:
flutter:   setAndGetScrollPosition
flutter: ════════════════════════════════════════════════════════════════════════════════════════════════════
flutter: 00:11 +12: Programmatic Scroll setAndGetScrollPosition [E]
flutter:   Test failed. See exception logs above.
  The test description was: setAndGetScrollPosition
```

This test was added in https://github.com/flutter/plugins/pull/2533

cc @EitanSchwartz as the author of the PR.

**Comment by blasten** [comment]
Could we mark this test as flaky to make the tree green again?

This logic seems the culprit (race condition): https://github.com/flutter/plugins/blob/c1ba799bbb072f99a687904669863468a733e0f1/packages/webview_flutter/example/test_driver/webview_flutter_e2e.dart#L563-L575

`onWebViewCreated` isn't always fired after `body.onload`, is it?

**Comment by cyanglaz** [comment]
offline discussion with @blasten ; We will try to use `onPageFinished` instead of `onWebViewCreated` to see if it fixes the flake
