### ISSUE TITLE
[tool_crash] NoSuchMethodError: The method 'add' was called on null.Receiver: nullTried calling: add("--enable-experiment=non-nullable")

### ISSUE THREAD

**Issue by incker** [flutter/flutter#57060]
## Command
```
flutter run --enable-experiment non-nullable
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
NoSuchMethodError: NoSuchMethodError: The method 'add' was called on null.
Receiver: null
Tried calling: add("--enable-experiment=non-nullable")
```
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:53:5)
#1      FlutterCommand.getBuildInfo (package:flutter_tools/src/runner/flutter_command.dart:528:30)
#2      RunCommand.usageValues (package:flutter_tools/src/commands/run.dart:291:29)
<asynchronous suspension>
#3      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:715:21)
<asynchronous suspension>
#4      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:619:33)
<asynchronous suspension>
#5      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart)
#6      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:29)
#7      _rootRun (dart:async/zone.dart:1184:13)
#8      _CustomZone.run (dart:async/zone.dart:1077:19)
#9      _runZoned (dart:async/zone.dart:1619:10)
#10     runZoned (dart:async/zone.dart:1539:10)
#11     AppContext.run (package:flutter_tools/src/base/context.dart:149:18)
#12     FlutterCommand.run (package:flutter_tools/src/runner/flutter_command.dart:609:20)
#13     CommandRunner.runCommand (package:args/command_runner.dart:197:27)
#14     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:339:21)
<asynchronous suspension>
#15     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart)
```
```
[✓] Flutter (Channel stable, v1.17.0, on Microsoft Windows [Version 10.0.18363.778], locale en-US)
    • Flutter version 1.17.0 at C:\dev\app\flutter
    • Framework revision e6b34c2b5c (10 days ago), 2020-05-02 11:39:18 -0700
    • Engine revision 540786dd51
    • Dart version 2.8.1

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at C:\Users\incker\AppData\Local\Android\sdk
    • Platform android-29, build-tools 29.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)
    • All Android licenses accepted.

[✓] Android Studio (version 3.6)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)

[!] IntelliJ IDEA Ultimate Edition (version 2019.3)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA 2019.3.3
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.dev/intellij-setup/#installing-the-plugins

[!] VS Code (version 1.45.0)
    • VS Code at C:\Users\incker\AppData\Local\Programs\Microsoft VS Code
    ✗ Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (1 available)
    • AOSP on IA Emulator • emulator-5554 • android-x86 • Android 9 (API 28) (emulator)

! Doctor found issues in 2 categories.

```

## Flutter Application Metadata
**Type**: app
**Version**: 1.0.0+1
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: stable
**Creation framework version**: 27321ebbad34b0a3fafe99fac037102196d655ff
### Plugins
firebase_auth-0.16.0
firebase_auth_web-0.1.2
firebase_core-0.4.4+3
firebase_core_web-0.1.1+2
flutter_plugin_android_lifecycle-1.0.7
google_maps_flutter-0.5.27+2
image_picker-0.6.6+1
package_info-0.4.0+18
path_provider-1.6.8
path_provider_macos-0.0.4+2
permission-565fc45490c2325fb1cc0155319bfe68b07f3de1
url_launcher-5.4.7
url_launcher_macos-0.0.1+5
url_launcher_web-0.1.1+4

**Comment by jonahwilliams** [comment]
This option is not supported on stable and should have been hidden

**Comment by jonahwilliams** [comment]
nevermind, this was already broken, but the option itself is hidden.

**Comment by jonahwilliams** [comment]
This is fixed in the latest beta
