### ISSUE TITLE
Default new flutter project not working

### ISSUE THREAD

**Issue by zyllus17** [flutter/flutter#57086]
## Steps to Reproduce

1. Run `flutter create fire`.
2. Run the default program in Android Studio

**Expected results:** To see the default app run on the emulator

**Actual results:** 

```bash
Launching lib\main.dart on Android SDK built for x86 in debug mode...
Running Gradle task 'assembleDebug'...

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:mergeDebugResources'.
> Multiple task action failures occurred:
   > A failure occurred while executing com.android.build.gradle.internal.tasks.Workers$ActionFacade
      > AAPT2 aapt2-3.5.0-5435860-windows Daemon #1: Daemon startup failed
        This should not happen under normal circumstances, please file an issue if it does.
   > A failure occurred while executing com.android.build.gradle.internal.tasks.Workers$ActionFacade
      > AAPT2 aapt2-3.5.0-5435860-windows Daemon #3: Daemon startup failed
        This should not happen under normal circumstances, please file an issue if it does.
   > A failure occurred while executing com.android.build.gradle.internal.tasks.Workers$ActionFacade
      > AAPT2 aapt2-3.5.0-5435860-windows Daemon #0: Daemon startup failed
        This should not happen under normal circumstances, please file an issue if it does.
   > A failure occurred while executing com.android.build.gradle.internal.tasks.Workers$ActionFacade
      > AAPT2 aapt2-3.5.0-5435860-windows Daemon #2: Daemon startup failed
        This should not happen under normal circumstances, please file an issue if it does.
   > A failure occurred while executing com.android.build.gradle.internal.tasks.Workers$ActionFacade
      > AAPT2 aapt2-3.5.0-5435860-windows Daemon #4: Daemon startup failed
        This should not happen under normal circumstances, please file an issue if it does.
   > A failure occurred while executing com.android.build.gradle.internal.tasks.Workers$ActionFacade
      > AAPT2 aapt2-3.5.0-5435860-windows Daemon #5: Daemon startup failed
        This should not happen under normal circumstances, please file an issue if it does.
   > A failure occurred while executing com.android.build.gradle.internal.tasks.Workers$ActionFacade
      > AAPT2 aapt2-3.5.0-5435860-windows Daemon #6: Daemon startup failed
        This should not happen under normal circumstances, please file an issue if it does.
   > A failure occurred while executing com.android.build.gradle.internal.tasks.Workers$ActionFacade
      > AAPT2 aapt2-3.5.0-5435860-windows Daemon #7: Daemon startup failed
        This should not happen under normal circumstances, please file an issue if it does.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 2m 30s
Exception: Gradle task assembleDebug failed with exit code 1
```

<details>
  <summary>Logs</summary>

```bash
[  +78 ms] executing: [C:\flutter\flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[ +228 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[   +3 ms] 67826bdce54505760fe83b7ead70bdb5af6fe9f2
[   +2 ms] executing: [C:\flutter\flutter/] git describe --match v*.*.* --first-parent --long --tags
[ +114 ms] Exit code 0 from: git describe --match v*.*.* --first-parent --long --tags
[   +1 ms] v1.15.3-0-g67826bdce5
[  +25 ms] executing: [C:\flutter\flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[  +75 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[   +1 ms] origin/master
[   +1 ms] executing: [C:\flutter\flutter/] git ls-remote --get-url origin
[  +63 ms] Exit code 0 from: git ls-remote --get-url origin
[   +1 ms] https://github.com/flutter/flutter.git
[ +353 ms] executing: [C:\flutter\flutter/] git rev-parse --abbrev-ref HEAD
[  +83 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[   +1 ms] master
[ +128 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[   +6 ms] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[  +26 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[   +2 ms] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[   +2 ms] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[ +128 ms] executing: C:\Users\Zyllus\AppData\Local\Android\Sdk\platform-tools\adb.exe devices -l
[ +108 ms] List of devices attached
           emulator-5554          device product:sdk_gphone_x86 model:Android_SDK_built_for_x86 device:generic_x86 transport_id:1
[  +18 ms] C:\Users\Zyllus\AppData\Local\Android\Sdk\platform-tools\adb.exe -s emulator-5554 shell getprop
[ +184 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[  +12 ms] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[  +11 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[   +2 ms] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[   +2 ms] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[ +751 ms] Generating D:\FlutterProjects\fire\android\app\src\main\java\io\flutter\plugins\GeneratedPluginRegistrant.java
[ +199 ms] ro.hardware = ranchu
[ +195 ms] Using hardware rendering with device Android SDK built for x86. If you get graphics artifacts, consider enabling
software rendering
           with "--enable-software-rendering".
[  +90 ms] Launching lib\main.dart on Android SDK built for x86 in debug mode...
[  +40 ms] C:\flutter\flutter\bin\cache\dart-sdk\bin\dart.exe
C:\flutter\flutter\bin\cache\artifacts\engine\windows-x64\frontend_server.dart.snapshot --sdk-root
C:\flutter\flutter\bin\cache\artifacts\engine\common\flutter_patched_sdk/ --incremental --target=flutter --debugger-module-names
-Ddart.developer.causal_async_stacks=true --output-dill
C:\Users\Zyllus\AppData\Local\Temp\flutter_tool.930ceb12-94e2-11ea-82bf-58fb84783f88\app.dill --packages
D:\FlutterProjects\fire\.packages -Ddart.vm.profile=false -Ddart.vm.product=false
--bytecode-options=source-positions,local-var-info,debugger-stops,instance-field-initializers,keep-unreachable-code,avoid-closure-c

all-instructions --enable-asserts --track-widget-creation --filesystem-scheme org-dartlang-root --initialize-from-dill
build\cache.dill
[ +108 ms] executing: C:\Users\Zyllus\AppData\Local\Android\Sdk\platform-tools\adb.exe -s emulator-5554 shell -x logcat -v time -t
1
[ +168 ms] Exit code 0 from: C:\Users\Zyllus\AppData\Local\Android\Sdk\platform-tools\adb.exe -s emulator-5554 shell -x logcat -v
time -t 1
[   +2 ms] --------- beginning of main
           05-13 11:55:46.996 I/GnssLocationProvider( 2029): WakeLock released by handleMessage(REPORT_SV_STATUS, 0,
           com.android.server.location.GnssLocationProvider$SvStatusInfo@65ce505)
[  +53 ms] <- compile package:fire/main.dart
[  +52 ms] executing: C:\Users\Zyllus\AppData\Local\Android\Sdk\platform-tools\adb.exe version
[ +454 ms] Android Debug Bridge version 1.0.40
           Version 4986621
           Installed as C:\Users\Zyllus\AppData\Local\Android\Sdk\platform-tools\adb.exe
[  +11 ms] executing: C:\Users\Zyllus\AppData\Local\Android\Sdk\platform-tools\adb.exe start-server
[  +56 ms] Building APK
[ +191 ms] Running Gradle task 'assembleDebug'...
[  +70 ms] gradle.properties already sets `android.enableR8`
[ +141 ms] Using gradle from D:\FlutterProjects\fire\android\gradlew.bat.
[   +4 ms] D:\FlutterProjects\fire\android\gradlew.bat mode: 33279 rwxrwxrwx.
[  +82 ms] executing: C:\Program Files\Android\Android Studio\jre\bin\java -version
[ +791 ms] Exit code 0 from: C:\Program Files\Android\Android Studio\jre\bin\java -version
[  +37 ms] openjdk version "1.8.0_212-release"
           OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)
           OpenJDK 64-Bit Server VM (build 25.212-b04, mixed mode)
[  +79 ms] executing: C:\Program Files\Android\Android Studio\jre\bin\java -version
[ +194 ms] Exit code 0 from: C:\Program Files\Android\Android Studio\jre\bin\java -version
[        ] openjdk version "1.8.0_212-release"
           OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)
           OpenJDK 64-Bit Server VM (build 25.212-b04, mixed mode)
[   +8 ms] executing: [D:\FlutterProjects\fire\android/] D:\FlutterProjects\fire\android\gradlew.bat -Pverbose=true
-Ptarget-platform=android-x86 -Ptarget=D:\FlutterProjects\fire\lib\main.dart -Ptrack-widget-creation=true
-Pfilesystem-scheme=org-dartlang-root assembleDebug
[+9823 ms] > Task :app:compileFlutterBuildDebug
[   +3 ms] [  +42 ms] executing: [C:\flutter\flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[  +56 ms] [  +82 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[  +20 ms] [        ] 67826bdce54505760fe83b7ead70bdb5af6fe9f2
[  +11 ms] [        ] executing: [C:\flutter\flutter/] git describe --match v*.*.* --first-parent --long --tags
[   +1 ms] [  +47 ms] Exit code 0 from: git describe --match v*.*.* --first-parent --long --tags
[  +16 ms] [        ] v1.15.3-0-g67826bdce5
[   +1 ms] [  +13 ms] executing: [C:\flutter\flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[        ] [  +34 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] [        ] origin/master
[        ] [        ] executing: [C:\flutter\flutter/] git ls-remote --get-url origin
[  +60 ms] [  +64 ms] Exit code 0 from: git ls-remote --get-url origin
[   +3 ms] [        ] https://github.com/flutter/flutter.git
[  +77 ms] [ +154 ms] executing: [C:\flutter\flutter/] git rev-parse --abbrev-ref HEAD
[ +100 ms] [  +36 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[   +2 ms] [        ] master
[        ] [  +37 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[   +1 ms] [        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +2 ms] [   +7 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[  +10 ms] [        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[   +1 ms] [        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[   +1 ms] [        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[   +1 ms] [  +20 ms] Artifact Instance of 'MaterialFonts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'GradleWrapper' is not required, skipping update.
[        ] [        ] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[   +1 ms] [        ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[   +1 ms] [        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FlutterSdk' is not required, skipping update.
[        ] [        ] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[        ] [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[   +7 ms] [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[  +49 ms] [   +7 ms] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] [   +7 ms] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'FontSubsetArtifacts' is not required, skipping update.
[ +109 ms] [ +119 ms] Initializing file store
[   +2 ms] [  +28 ms] Done initializing file store
[+2286 ms] [+2312 ms] Skipping target: kernel_snapshot
[ +200 ms] [ +218 ms] debug_android_application: Starting due to {InvalidatedReason.outputMissing}
[ +202 ms] [ +210 ms] debug_android_application: Complete
[  +97 ms] [  +37 ms] Persisting file store
[        ] [  +23 ms] Done persisting file store
[        ] [   +7 ms] build succeeded.
[        ] [  +26 ms] "flutter assemble" took 3,111ms.
[ +303 ms] > Task :app:packLibsflutterBuildDebug UP-TO-DATE
[   +1 ms] > Task :app:preBuild UP-TO-DATE
[   +6 ms] > Task :app:preDebugBuild UP-TO-DATE
[   +1 ms] > Task :app:compileDebugAidl NO-SOURCE
[   +4 ms] > Task :app:checkDebugManifest UP-TO-DATE
[   +3 ms] > Task :app:compileDebugRenderscript NO-SOURCE
[   +3 ms] > Task :app:generateDebugBuildConfig UP-TO-DATE
[   +5 ms] > Task :app:cleanMergeDebugAssets
[  +68 ms] > Task :app:mergeDebugShaders UP-TO-DATE
[        ] > Task :app:compileDebugShaders UP-TO-DATE
[        ] > Task :app:generateDebugAssets UP-TO-DATE
[        ] > Task :app:mergeDebugAssets
[ +337 ms] > Task :app:copyFlutterAssetsDebug
[   +1 ms] > Task :app:mainApkListPersistenceDebug UP-TO-DATE
[        ] > Task :app:generateDebugResValues UP-TO-DATE
[        ] > Task :app:generateDebugResources UP-TO-DATE
[+2557 ms] > Task :app:createDebugCompatibleScreenManifests
[ +800 ms] > Task :app:processDebugManifest
[ +218 ms] > Task :app:mergeDebugResources FAILED
[  +16 ms] FAILURE: Build failed with an exception.
[   +9 ms] * What went wrong:
[   +2 ms] Execution failed for task ':app:mergeDebugResources'.
[   +2 ms] > Multiple task action failures occurred:
[  +61 ms]    > A failure occurred while executing com.android.build.gradle.internal.tasks.Workers$ActionFacade
[  +22 ms]       > AAPT2 aapt2-3.5.0-5435860-windows Daemon #0: Daemon startup failed
[   +2 ms]         This should not happen under normal circumstances, please file an issue if it does.
[   +8 ms]    > A failure occurred while executing com.android.build.gradle.internal.tasks.Workers$ActionFacade
[   +3 ms]       > AAPT2 aapt2-3.5.0-5435860-windows Daemon #1: Daemon startup failed
[  +17 ms]         This should not happen under normal circumstances, please file an issue if it does.
[   +9 ms]    > A failure occurred while executing com.android.build.gradle.internal.tasks.Workers$ActionFacade
[   +3 ms]       > AAPT2 aapt2-3.5.0-5435860-windows Daemon #2: Daemon startup failed
[  +18 ms]         This should not happen under normal circumstances, please file an issue if it does.
[  +15 ms]    > A failure occurred while executing com.android.build.gradle.internal.tasks.Workers$ActionFacade
[  +60 ms]       > AAPT2 aapt2-3.5.0-5435860-windows Daemon #3: Daemon startup failed
[  +11 ms]         This should not happen under normal circumstances, please file an issue if it does.
[   +4 ms]    > A failure occurred while executing com.android.build.gradle.internal.tasks.Workers$ActionFacade
[   +1 ms]       > AAPT2 aapt2-3.5.0-5435860-windows Daemon #4: Daemon startup failed
[   +1 ms]         This should not happen under normal circumstances, please file an issue if it does.
[   +2 ms]    > A failure occurred while executing com.android.build.gradle.internal.tasks.Workers$ActionFacade
[   +2 ms]       > AAPT2 aapt2-3.5.0-5435860-windows Daemon #5: Daemon startup failed
[   +1 ms]         This should not happen under normal circumstances, please file an issue if it does.
[   +2 ms]    > A failure occurred while executing com.android.build.gradle.internal.tasks.Workers$ActionFacade
[   +4 ms]       > AAPT2 aapt2-3.5.0-5435860-windows Daemon #6: Daemon startup failed
[   +1 ms]         This should not happen under normal circumstances, please file an issue if it does.
[   +1 ms]    > A failure occurred while executing com.android.build.gradle.internal.tasks.Workers$ActionFacade
[   +1 ms]       > AAPT2 aapt2-3.5.0-5435860-windows Daemon #7: Daemon startup failed
[   +1 ms]         This should not happen under normal circumstances, please file an issue if it does.
[   +3 ms] * Try:
[   +1 ms] Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with
--scan to get full insights.
[   +6 ms] * Get more help at https://help.gradle.org
[   +1 ms] BUILD FAILED in 17s
[   +2 ms] 14 actionable tasks: 7 executed, 7 up-to-date
[ +784 ms] Running Gradle task 'assembleDebug'... (completed in 20.0s)
[  +24 ms] Exception: Gradle task assembleDebug failed with exit code 1
[   +5 ms] "flutter run" took 23,166ms.

#0      throwToolExit (package:flutter_tools/src/base/common.dart:14:3)
#1      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:569:7)
<asynchronous suspension>
#2      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:715:18)
#3      _rootRunUnary (dart:async/zone.dart:1155:38)
#4      _CustomZone.runUnary (dart:async/zone.dart:1048:19)
#5      _FutureListener.handleValue (dart:async/future_impl.dart:141:18)
#6      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:682:45)
#7      Future._propagateToListeners (dart:async/future_impl.dart:711:32)
#8      Future._completeWithValue (dart:async/future_impl.dart:526:5)
#9      _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:34:15)
#10     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:295:13)
#11     RunCommand.usageValues (package:flutter_tools/src/commands/run.dart)
#12     _rootRunUnary (dart:async/zone.dart:1155:38)
#13     _CustomZone.runUnary (dart:async/zone.dart:1048:19)
#14     _FutureListener.handleValue (dart:async/future_impl.dart:141:18)
#15     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:682:45)
#16     Future._propagateToListeners (dart:async/future_impl.dart:711:32)
#17     Future._completeWithValue (dart:async/future_impl.dart:526:5)
#18     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:34:15)
#19     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:295:13)
#20     AndroidDevice.isLocalEmulator (package:flutter_tools/src/android/android_device.dart)
#21     _rootRunUnary (dart:async/zone.dart:1155:38)
#22     _CustomZone.runUnary (dart:async/zone.dart:1048:19)
#23     _FutureListener.handleValue (dart:async/future_impl.dart:141:18)
#24     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:682:45)
#25     Future._propagateToListeners (dart:async/future_impl.dart:711:32)
#26     Future._completeWithValue (dart:async/future_impl.dart:526:5)
#27     Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:556:7)
#28     _rootRun (dart:async/zone.dart:1147:13)
#29     _CustomZone.run (dart:async/zone.dart:1040:19)
#30     _CustomZone.runGuarded (dart:async/zone.dart:942:7)
#31     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:982:23)
#32     _microtaskLoop (dart:async/schedule_microtask.dart:43:21)
#33     _startMicrotaskLoop (dart:async/schedule_microtask.dart:52:5)
#34     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
#35     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:169:5)

```

```
Analyzing fire...
No issues found! (ran in 148.1s)
```
</details>

```console
[√] Flutter (Channel master, v1.15.3, on Microsoft Windows [Version 6.3.9600], locale en-HK)
    • Flutter version 1.15.3 at C:\flutter\flutter
    • Framework revision 67826bdce5 (3 months ago), 2020-02-10 14:59:32 -0800
    • Engine revision 3a68f68999
    • Dart version 2.8.0 (build 2.8.0-dev.17.0 8246621d4d)

[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at C:\Users\Zyllus\AppData\Local\Android\Sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 28.0.3
    • ANDROID_HOME =
      C:\Users\Zyllus\AppData\Local\Android\Sdk;C:\adb;C:\Users\Zyllus\.android\avd;C:\flutter\flutter;C:\Users\Zyllus\AppData\Loca

      l\Android\Sdk\platform-tools;
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)
    • All Android licenses accepted.

[√] Android Studio (version 3.6)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)

[√] Connected device (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 9 (API 28) (emulator)

• No issues found!

```

**Comment by zyllus17** [comment]
I have a temporary solution to the issue here https://github.com/flutter/flutter/issues/29608#issuecomment-578383592 but I want Flutter team to look into this issue and fix it. I have to make changes everytime I create a new project and using Firebase becomes a nightmare because of varying dependencies.

**Comment by iapicca** [comment]
Hi @zyllus17 
if the issue is with FlutterFire plugins,
please open the issue in the dedicated [github](https://github.com/FirebaseExtended/flutterfire/issues),
otherwise
could you please run `flutter upgrade --force`
and provide your updated `flutter doctor -v`,
your `flutter run --verbose`,
your `pubspec.yaml` 
and if possible a reproducible minimal code sample.
Thank you

**Comment by VladyslavBondarenko** [comment]
@zyllus17 
your flutter version is obsolete. Consider to upgrade.
Does the issue persist with current stable `1.17.0` or other channels?

**Comment by zyllus17** [comment]
@iapicca This happens everytime with the default counter app created during a new flutter project. 
@VladyslavBondarenko I did upgrade Flutter to 1.17.0 but the issue still remains.

**Comment by iapicca** [comment]
HI again @zyllus17 
could you please provide the information listed [above](https://github.com/flutter/flutter/issues/57086#issuecomment-627905249)
Thank you

**Comment by zyllus17** [comment]
I was frustrated and went on a rampage and deleted all the files related to Flutter on my pc. I began a new and installed everything once again. Somehow all of it is fixed. Reinstalling all the files and not importing the older settings was the key to solving it.
