### ISSUE TITLE
type 'MaterialPageRoute<dynamic>' is not a subtype of type 'Route<String?>?' of ' in type cast'

### ISSUE THREAD

**Issue by 0x1af2aec8f957** [flutter/flutter#57186]
#### Problem description:

> I expect to use `Navigator.of(context).pop<String>` to return a value of a certain type, but the result is always a value of dynamic type.

#### Code:

```dart
// First screen
Navigator.of(context).pushNamed<String>('login').then((String result){
                                  print('login.result runtimeType: ${result.runtimeType}');
                                });

// Second screen
Navigator.of(context).pop<String>('success');
```

#### A type error will occur in the above code:
```bash
E/flutter (16614): [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: type 'MaterialPageRoute<dynamic>' is not a subtype of type 'Route<String>' in type cast
E/flutter (16614): #0      NavigatorState._routeNamed (package:flutter/src/widgets/navigator.dart:3138:55)
E/flutter (16614): #1      NavigatorState.pushNamed (package:flutter/src/widgets/navigator.dart:3190:20)
E/flutter (16614): #2      _Transfer.build.<anonymous closure> (package:example/views/FirstScreen.dart:157:55)
E/flutter (16614): #3      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:182:24)
E/flutter (16614): #4      TapGestureRecognizer.handleTapUp (package:flutter/src/gestures/tap.dart:504:11)
E/flutter (16614): #5      BaseTapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:282:5)
E/flutter (16614): #6      BaseTapGestureRecognizer.acceptGesture (package:flutter/src/gestures/tap.dart:254:7)
E/flutter (16614): #7      GestureArenaManager.sweep (package:flutter/src/gestures/arena.dart:156:27)
E/flutter (16614): #8      GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:222:20)
E/flutter (16614): #9      GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:198:22)
E/flutter (16614): #10     GestureBinding._handlePointerEvent (package:flutter/src/gestures/binding.dart:156:7)
E/flutter (16614): #11     GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:102:7)
E/flutter (16614): #12     GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:86:7)
E/flutter (16614): #13     _rootRunUnary (dart:async/zone.dart:1196:13)
E/flutter (16614): #14     _CustomZone.runUnary (dart:async/zone.dart:1085:19)
E/flutter (16614): #15     _CustomZone.runUnaryGuarded (dart:async/zone.dart:987:7)
E/flutter (16614): #16     _invoke1 (dart:ui/hooks.dart:275:10)
E/flutter (16614): #17     _dispatchPointerDataPacket (dart:ui/hooks.dart:184:5)
E/flutter (16614): 
```

**Comment by liodali** [comment]
you don't need to make pushNamed<String>() or pop<String>()
just pushNamed("routeName") and pop(value) 
you will get right type

**Comment by VladyslavBondarenko** [comment]
Thanks @liodali ,
It should be solved by this, closing.
@noteScript If you disagree please write in the comments and I will reopen it

https://flutter.dev/docs/cookbook/navigation/returning-data#interactive-example

**Comment by HannibalKcc** [comment]
Hi @VladyslavBondarenko ,
your example used `Navigator.push()`, return data's type work well.

But, i find if i use `Navigator.pushNamed()` replace `Navigator.push()` it throw A type error will occur as same as @noteScript showed.

you can check code 
[hrere](https://dartpad.cn/8c36353393cff784a350038be29fd02e)

**Comment by liodali** [comment]
replace String result by var result,should work for you

**Comment by HannibalKcc** [comment]
@liodali use `var` work for me.

But i think API `Navigator.pushNamed()` and `Navigator.push() ` should have the same result,even certain a type.

**Comment by celesteking** [comment]
This is a deficiency on flutter's Navigator1/MaterialApp side when [ `routes` table](https://github.com/flutter/flutter/blob/1aafb3a8b9/packages/flutter/lib/src/material/app.dart#L172) is being used. This isn't documented anywhere, but it should've been. The workaround is to stop providing `pushNamed` any type, but instead typecast to it later:
```dart
 final params = (await Navigator.of(context).pushNamed('/xx', arguments: RouteArgs('abc'))) as RouteRetParams;
// params  is now of `RouteRetParams` type
```

This needs fixing, either on doc or code 's side.

**Comment by chunhtai** [comment]
This is also blocking internal migration

**Comment by maheshmnj** [comment]
Reproducible on stable 3.3 and master 3.7

<details>
<summary>logs</summary>

```console
Restarted application in 848ms.

════════ Exception caught by gesture ═══════════════════════════════════════════
The following _TypeError was thrown while handling a gesture:
type 'MaterialPageRoute<dynamic>' is not a subtype of type 'Route<String?>?' of ' in type cast'

When the exception was thrown, this was the stack
#0      NavigatorState._routeNamed
#1      NavigatorState.pushNamed
#2      _MyHomePageState._incrementCounter
#3      _InkResponseState.handleTap
#4      GestureRecognizer.invokeCallback
#5      TapGestureRecognizer.handleTapUp
#6      BaseTapGestureRecognizer._checkUp
#7      BaseTapGestureRecognizer.acceptGesture
#8      GestureArenaManager.sweep
#9      GestureBinding.handleEvent
#10     GestureBinding.dispatchEvent
#11     RendererBinding.dispatchEvent
#12     GestureBinding._handlePointerEventImmediately
#13     GestureBinding.handlePointerEvent
#14     GestureBinding._flushPointerEventQueue
#15     GestureBinding._handlePointerDataPacket
#16     _invoke1 (dart:ui/hooks.dart:164:13)
#17     PlatformDispatcher._dispatchPointerDataPacket (dart:ui/platform_dispatcher.dart:361:7)
#18     _dispatchPointerDataPacket (dart:ui/hooks.dart:91:31)
Handler: "onTap"
Recognizer: TapGestureRecognizer#ae830
    debugOwner: GestureDetector
    state: ready
    won arena
    finalPosition: Offset(348.7, 743.6)
    finalLocalPosition: Offset(28.0, 34.5)
    button: 1
    sent tap down
════════════════════════════════════════════════════════════════════════════════

```
</details> 

<details>
<summary>code sample</summary>

```dart
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      routes: {
        'widget': (BuildContext context) => const NewPage(),
      },
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: const MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({Key? key, required this.title}) : super(key: key);
  final String title;
  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  final int _counter = 0;
  void _incrementCounter() {
    // Second screen
    Navigator.of(context).pushNamed<String>('widget').then((String? result) {
      print('login.result runtimeType: ${result.runtimeType}');
    });

   // This works 
  //  Navigator.of(context).pushNamed('widget').then((result) {
 //     print('login.result runtimeType: ${result.runtimeType}');
//    });
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            const Text(
              'You have pushed the button this many times:',
            ),
            Text(
              '$_counter',
              style: Theme.of(context).textTheme.headlineMedium,
            ),
          ],
        ),
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: _incrementCounter,
        tooltip: 'Increment',
        child: const Icon(Icons.add),
      ),
    );
  }
}

class NewPage extends StatefulWidget {
  const NewPage({Key? key}) : super(key: key);

  @override
  State<NewPage> createState() => _NewPageState();
}

class _NewPageState extends State<NewPage> {
  @override
  Widget build(BuildContext context) {
    return Material(
      child: Container(
          color: Colors.red,
          child: Center(
            child: ElevatedButton(
              onPressed: () {
                Navigator.of(context).pop<String>('Hello');
              },
              child: const Text('Back'),
            ),
          )),
    );
  }
}
```
</details> 

<details>
<summary>flutter doctor -v (mac)</summary>

```
[✓] Flutter (Channel master, 3.7.0-13.0.pre.131, on macOS 13.1 22C65 darwin-arm64, locale en-IN)
    • Flutter version 3.7.0-13.0.pre.131 on channel master at /Users/mahesh/Development/flutter_master
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 0196e6050b (2 days ago), 2022-12-31 11:10:23 -0500
    • Engine revision 932591ec04
    • Dart version 3.0.0 (build 3.0.0-76.0.dev)
    • DevTools version 2.20.0
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git" directly to perform update checks
      and upgrades.

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0-rc4)
    • Android SDK at /Users/mahesh/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0-rc4
    • ANDROID_HOME = /Users/mahesh/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14A400
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] IntelliJ IDEA Community Edition (version 2021.2.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 61.2.4
    • Dart plugin version 212.5080.8

[✓] VS Code (version 1.74.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.56.0

[✓] Connected device (3 available)
    • iPhone 12 Pro (mobile) • 026D5789-9E78-4AD5-B1B2-3F8D4E7F65E4 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-5 (simulator)
    • macOS (desktop)        • macos                                • darwin-arm64   • macOS 13.1 22C65 darwin-arm64
    • Chrome (web)           • chrome                               • web-javascript • Google Chrome 108.0.5359.124

[✓] HTTP Host Availability
    • All required HTTP hosts are available
    
• No issues found!
```
```
[✓] Flutter (Channel stable, 3.3.9, on macOS 12.6 21G115 darwin-arm, locale en-IN)
    • Flutter version 3.3.9 on channel stable at /Users/mahesh/Development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision b8f7f1f986 (24 hours ago), 2022-11-23 06:43:51 +0900
    • Engine revision 8f2221fbef
    • Dart version 2.18.5
    • DevTools version 2.15.0

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0-rc4)
    • Android SDK at /Users/mahesh/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0-rc4
    • ANDROID_HOME = /Users/mahesh/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14A400
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] IntelliJ IDEA Community Edition (version 2021.2.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 61.2.4
    • Dart plugin version 212.5080.8

[✓] VS Code (version 1.70.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.53.20221101

[✓] Connected device (3 available)
    • iPhone 12 Pro (mobile) • 026D5789-9E78-4AD5-B1B2-3F8D4E7F65E4 • ios            •
      com.apple.CoreSimulator.SimRuntime.iOS-14-5 (simulator)
    • macOS (desktop)        • macos                                • darwin-arm64   • macOS 12.6 21G115 darwin-arm
    • Chrome (web)           • chrome                               • web-javascript • Google Chrome 107.0.5304.110

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```
</details>

cc: @chunhtai

**Comment by equescodebelike** [comment]
I had similar problem, but with auto_route navigation, so I fixed cast issue by adding `<type>` to CustomRoute declaration:
```
    CustomRoute<int?>(
      name: RoutesNames.imageSliderFullScreen,
      path: Routes.imageSliderFullScreen,
      page: ImageSliderWithExtendedImageFullScreen,
      customRouteBuilder: dismissablePageRouteBuilder,
    ),
```
