### ISSUE TITLE
Execution failed for task ':app:compileFlutterBuildDebug' Issue

### ISSUE THREAD

**Issue by MurathanGoktas** [flutter/flutter#57194]
1.  After upgrading to new version 1.17.1 I am not able to build the application.
2.  I am working on Android Studio.
3. This was an upgoing project not new.

## Logs

Build with -verbose
```
[  +26 ms] executing: [/Users/murathan/Downloads/project/flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[  +37 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[        ] f7a6a7906be96d2288f5d63a5a54c515a6e987fe
[        ] executing: [/Users/murathan/Downloads/project/flutter/] git tag --contains HEAD
[ +208 ms] Exit code 0 from: git tag --contains HEAD
[   +1 ms] 1.17.1
[   +9 ms] executing: [/Users/murathan/Downloads/project/flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[   +5 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/stable
[        ] executing: [/Users/murathan/Downloads/project/flutter/] git ls-remote --get-url origin
[   +4 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[  +71 ms] executing: [/Users/murathan/Downloads/project/flutter/] git rev-parse --abbrev-ref HEAD
[   +6 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] stable
[   +5 ms] executing: sw_vers -productName
[  +13 ms] Exit code 0 from: sw_vers -productName
[        ] Mac OS X
[        ] executing: sw_vers -productVersion
[  +14 ms] Exit code 0 from: sw_vers -productVersion
[   +1 ms] 10.15.4
[        ] executing: sw_vers -buildVersion
[  +20 ms] Exit code 0 from: sw_vers -buildVersion
[        ] 19E287
[  +23 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +2 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +29 ms] executing: /Users/murathan/Library/Android/sdk/platform-tools/adb devices -l
[   +8 ms] executing: /usr/bin/xcode-select --print-path
[   +8 ms] Exit code 0 from: /usr/bin/xcode-select --print-path
[        ] /Library/Developer/CommandLineTools
[   +2 ms] executing: /usr/bin/xcodebuild -version
[   +4 ms] Exit code 1 from: /usr/bin/xcodebuild -version
[        ] xcode-select: error: tool 'xcodebuild' requires Xcode, but active developer directory '/Library/Developer/CommandLineTools' is a command line tools instance
[        ] Xcode not found. Run 'flutter doctor' for more information.
[   +2 ms] executing: /usr/bin/xcodebuild -version
[   +5 ms] Exit code 1 from: /usr/bin/xcodebuild -version
[        ] xcode-select: error: tool 'xcodebuild' requires Xcode, but active developer directory '/Library/Developer/CommandLineTools' is a command line tools instance
[  +40 ms] List of devices attached
           emulator-5554          device product:sdk_gphone_x86 model:Android_SDK_built_for_x86 device:generic_x86 transport_id:1
[  +10 ms] /Users/murathan/Library/Android/sdk/platform-tools/adb -s emulator-5554 shell getprop
[  +33 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[   +3 ms] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +1 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[   +9 ms] executing: /usr/bin/xcodebuild -version
[   +4 ms] Exit code 1 from: /usr/bin/xcodebuild -version
[        ] xcode-select: error: tool 'xcodebuild' requires Xcode, but active developer directory '/Library/Developer/CommandLineTools' is a command line tools instance
[ +115 ms] Found plugin flutter_plugin_android_lifecycle at /Users/murathan/Downloads/project/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_plugin_android_lifecycle-1.0.6/
[  +29 ms] Found plugin image_cropper at /Users/murathan/Downloads/project/flutter/.pub-cache/hosted/pub.dartlang.org/image_cropper-1.2.1/
[   +3 ms] Found plugin image_editor at /Users/murathan/Downloads/project/flutter/.pub-cache/hosted/pub.dartlang.org/image_editor-0.1.6/
[   +3 ms] Found plugin image_gallery_saver at /Users/murathan/Downloads/project/flutter/.pub-cache/hosted/pub.dartlang.org/image_gallery_saver-1.2.2/
[   +2 ms] Found plugin image_picker at /Users/murathan/Downloads/project/flutter/.pub-cache/hosted/pub.dartlang.org/image_picker-0.6.3+1/
[  +22 ms] Found plugin multi_image_picker at /Users/murathan/Downloads/project/flutter/.pub-cache/hosted/pub.dartlang.org/multi_image_picker-4.6.1/
[   +3 ms] Found plugin path_provider at /Users/murathan/Downloads/project/flutter/.pub-cache/hosted/pub.dartlang.org/path_provider-1.6.5/
[   +2 ms] Found plugin path_provider_macos at /Users/murathan/Downloads/project/flutter/.pub-cache/hosted/pub.dartlang.org/path_provider_macos-0.0.4/
[  +13 ms] Found plugin sqflite at /Users/murathan/Downloads/project/flutter/.pub-cache/hosted/pub.dartlang.org/sqflite-1.2.2/
[  +59 ms] Found plugin flutter_plugin_android_lifecycle at /Users/murathan/Downloads/project/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_plugin_android_lifecycle-1.0.6/
[   +6 ms] Found plugin image_cropper at /Users/murathan/Downloads/project/flutter/.pub-cache/hosted/pub.dartlang.org/image_cropper-1.2.1/
[        ] Found plugin image_editor at /Users/murathan/Downloads/project/flutter/.pub-cache/hosted/pub.dartlang.org/image_editor-0.1.6/
[        ] Found plugin image_gallery_saver at /Users/murathan/Downloads/project/flutter/.pub-cache/hosted/pub.dartlang.org/image_gallery_saver-1.2.2/
[        ] Found plugin image_picker at /Users/murathan/Downloads/project/flutter/.pub-cache/hosted/pub.dartlang.org/image_picker-0.6.3+1/
[   +3 ms] Found plugin multi_image_picker at /Users/murathan/Downloads/project/flutter/.pub-cache/hosted/pub.dartlang.org/multi_image_picker-4.6.1/
[   +1 ms] Found plugin path_provider at /Users/murathan/Downloads/project/flutter/.pub-cache/hosted/pub.dartlang.org/path_provider-1.6.5/
[        ] Found plugin path_provider_macos at /Users/murathan/Downloads/project/flutter/.pub-cache/hosted/pub.dartlang.org/path_provider_macos-0.0.4/
[   +4 ms] Found plugin sqflite at /Users/murathan/Downloads/project/flutter/.pub-cache/hosted/pub.dartlang.org/sqflite-1.2.2/
[  +74 ms] Generating /Users/murathan/Downloads/project/Autoshop/autoshop/android/app/src/main/java/io/flutter/plugins/GeneratedPluginRegistrant.java
[  +29 ms] executing: /usr/bin/xcodebuild -version
[   +6 ms] Exit code 1 from: /usr/bin/xcodebuild -version
[   +1 ms] xcode-select: error: tool 'xcodebuild' requires Xcode, but active developer directory '/Library/Developer/CommandLineTools' is a command line tools instance
[   +6 ms] ro.hardware = ranchu
[{"event":"daemon.connected","params":{"version":"0.5.3","pid":25019}}]
[{"event":"app.start","params":{"appId":"5d7b6ca3-0d97-4ad2-b6f5-e43265c1be3e","deviceId":"emulator-5554","directory":"/Users/murathan/Downloads/project/Autoshop/autoshop","supportsRestart":true,"launchMode":"run"}}]
[  +75 ms] Launching lib/main.dart on Android SDK built for x86 in debug mode...
[   +7 ms] /Users/murathan/Downloads/project/flutter/bin/cache/dart-sdk/bin/dart /Users/murathan/Downloads/project/flutter/bin/cache/artifacts/engine/darwin-x64/frontend_server.dart.snapshot --sdk-root /Users/murathan/Downloads/project/flutter/bin/cache/artifacts/engine/common/flutter_patched_sdk/ --incremental --target=flutter --debugger-module-names -Ddart.developer.causal_async_stacks=true --output-dill /var/folders/fr/j3fgyndn2sn7pzr8b7svv6700000gn/T/flutter_tool.IIdKpT/app.dill --packages /Users/murathan/Downloads/project/Autoshop/autoshop/.packages -Ddart.vm.profile=false -Ddart.vm.product=false --bytecode-options=source-positions,local-var-info,debugger-stops,instance-field-initializers,keep-unreachable-code,avoid-closure-call-instructions --enable-asserts --track-widget-creation --initialize-from-dill build/cache.dill
[  +14 ms] executing: /Users/murathan/Library/Android/sdk/platform-tools/adb -s emulator-5554 shell -x logcat -v time -t 1
[  +27 ms] Exit code 0 from: /Users/murathan/Library/Android/sdk/platform-tools/adb -s emulator-5554 shell -x logcat -v time -t 1
[        ] --------- beginning of main
           05-14 09:54:27.061 E/GnssHAL_GnssInterface( 1753): gnssSvStatusCb: b: input svInfo.flags is 8
[  +15 ms] <- compile package:autoshop/main.dart
[  +10 ms] executing: /Users/murathan/Library/Android/sdk/platform-tools/adb version
[   +8 ms] Android Debug Bridge version 1.0.41
           Version 30.0.1-6435776
           Installed as /Users/murathan/Library/Android/sdk/platform-tools/adb
[   +5 ms] executing: /Users/murathan/Library/Android/sdk/platform-tools/adb start-server
[ +111 ms] Building APK
Running Gradle task 'assembleDebug'...
[{"event":"app.progress","params":{"appId":"5d7b6ca3-0d97-4ad2-b6f5-e43265c1be3e","id":"0","progressId":null,"message":"Running Gradle task 'assembleDebug'..."}}]
[  +85 ms] gradle.properties already sets `android.enableR8`
[   +6 ms] Using gradle from /Users/murathan/Downloads/project/Autoshop/autoshop/android/gradlew.
[   +1 ms] /Users/murathan/Downloads/project/Autoshop/autoshop/android/gradlew mode: 33261 rwxr-xr-x.
[+2586 ms] executing: /usr/bin/plutil -convert json -o - /Applications/Android Studio.app/Contents/Info.plist
[  +11 ms] Exit code 0 from: /usr/bin/plutil -convert json -o - /Applications/Android Studio.app/Contents/Info.plist
[        ] {"CFBundleName":"Android Studio","JVMOptions":{"ClassPath":"$APP_PACKAGE\/Contents\/lib\/bootstrap.jar:$APP_PACKAGE\/Contents\/lib\/extensions.jar:$APP_PACKAGE\/Contents\/lib\/util.jar:$APP_PACKAGE\/Contents\/lib\/jdom.jar:$APP_PACKAGE\/Contents\/lib\/log4j.jar:$APP_PACKAGE\/Contents\/lib\/trove4j.jar:$APP_PACKAGE\/Contents\/lib\/jna.jar","JVMVersion":"1.8*,1.8+","WorkingDirectory":"$APP_PACKAGE\/Contents\/bin","MainClass":"com.intellij.idea.Main","Properties":{"idea.paths.selector":"AndroidStudio3.6","idea.executable":"studio","idea.platform.prefix":"AndroidStudio","idea.home.path":"$APP_PACKAGE\/Contents"}},"NSDesktopFolderUsageDescription":"An application in Android Studio requests access to the user's Desktop folder.","LSArchitecturePriority":["x86_64"],"CFBundleVersion":"AI-192.7142.36.36.6392135","CFBundleDevelopmentRegion":"English","NSCameraUsageDescription":"An application in Android Studio requests access to the device's camera.","CFBundleDocumentTypes":[{"CFBundleTypeName":"Android Studio Project File","CFBundleTypeExtensions":["ipr"],"CFBundleTypeRole":"Editor","CFBundleTypeIconFile":"studio.icns"},{"CFBundleTypeName":"All documents","CFBundleTypeExtensions":["*"],"CFBundleTypeOSTypes":["****"],"CFBundleTypeRole":"Editor","LSTypeIsPackage":false}],"NSSupportsAutomaticGraphicsSwitching":true,"CFBundlePackageType":"APPL","CFBundleIconFile":"studio.icns","NSHighResolutionCapable":true,"CFBundleShortVersionString":"3.6","NSMicrophoneUsageDescription":"An application in Android Studio requests access to the device's microphone.","CFBundleInfoDictionaryVersion":"6.0","CFBundleExecutable":"studio","NSLocationUsageDescription":"An application in Android Studio requests access to the user's location information.","LSRequiresNativeExecution":"YES","CFBundleURLTypes":[{"CFBundleTypeRole":"Editor","CFBundleURLName":"Stacktrace","CFBundleURLSchemes":["idea"]}],"CFBundleIdentifier":"com.google.android.studio","LSApplicationCategoryType":"public.app-category.developer-tools","CFBundleSignature":"????","LSMinimumSystemVersion":"10.8","NSDocumentsFolderUsageDescription":"An application in Android Studio requests access to the user's Documents folder.","NSDownloadsFolderUsageDescription":"An application in Android Studio requests access to the user's Downloads folder.","NSNetworkVolumesUsageDescription":"An application in Android Studio requests access to files on a network volume.","CFBundleGetInfoString":"Android Studio 3.6, build AI-192.7142.36.36.6392135. Copyright JetBrains s.r.o., (c) 2000-2020","NSRemovableVolumesUsageDescription":"An application in Android Studio requests access to files on a removable volume."}
[   +5 ms] executing: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java -version
[  +92 ms] Exit code 0 from: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java -version
[   +1 ms] openjdk version "1.8.0_212-release"
           OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
           OpenJDK 64-Bit Server VM (build 25.212-b4-5784211, mixed mode)
[   +4 ms] executing: [/Users/murathan/Downloads/project/Autoshop/autoshop/android/] /Users/murathan/Downloads/project/Autoshop/autoshop/android/gradlew -q -Ptarget-platform=android-x86 -Ptarget=/Users/murathan/Downloads/project/Autoshop/autoshop/lib/main.dart -Ptrack-widget-creation=true -Pfilesystem-scheme=org-dartlang-root assembleDebug
[+4767 ms] 
           Compiler message:
[   +1 ms] ../../flutter/.pub-cache/hosted/pub.dartlang.org/extended_image-0.7.2/lib/src/gesture/extended_image_slide_page_route.dart:333:9: Error: No named parameter with the name 'animation'.
[        ]         animation: animation,
[        ]         ^^^^^^^^^
[        ] ../../flutter/packages/flutter/lib/src/cupertino/route.dart:435:3: Context: Found this candidate, but the arguments don't match.
[        ]   CupertinoFullscreenDialogTransition({
[        ]   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[+10251 ms] Compiler message:
[   +1 ms] ../../flutter/.pub-cache/hosted/pub.dartlang.org/extended_image-0.7.2/lib/src/gesture/extended_image_slide_page_route.dart:333:9: Error: No named parameter with the name 'animation'.
[        ]         animation: animation,
[   +1 ms]         ^^^^^^^^^
[        ] ../../flutter/packages/flutter/lib/src/cupertino/route.dart:435:3: Context: Found this candidate, but the arguments don't match.
[        ]   CupertinoFullscreenDialogTransition({
[        ]   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[+5982 ms] Target kernel_snapshot failed: Exception: Errors during snapshot creation: null
[        ] build failed.
[  +98 ms] FAILURE: Build failed with an exception.
[        ] * Where:
[        ] Script '/Users/murathan/Downloads/project/flutter/packages/flutter_tools/gradle/flutter.gradle' line: 882
[        ] * What went wrong:
[        ] Execution failed for task ':app:compileFlutterBuildDebug'.
[        ] > Process 'command '/Users/murathan/Downloads/project/flutter/bin/flutter'' finished with non-zero exit value 1
[        ] * Try:
[        ] Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
[        ] * Get more help at https://help.gradle.org
[        ] BUILD FAILED in 20s
[{"event":"app.progress","params":{"appId":"5d7b6ca3-0d97-4ad2-b6f5-e43265c1be3e","id":"0","progressId":null,"finished":true}}]
[ +418 ms] Exception: Gradle task assembleDebug failed with exit code 1
[{"event":"app.stop","params":{"appId":"5d7b6ca3-0d97-4ad2-b6f5-e43265c1be3e"}}]
[{"id":0,"error":"app '5d7b6ca3-0d97-4ad2-b6f5-e43265c1be3e' not found","trace":"#0      AppDomain.stop (package:flutter_tools/src/commands/daemon.dart:687:7)\n#1      Domain.handleCommand.<anonymous closure> (package:flutter_tools/src/commands/daemon.dart:227:34)\n#2      new Future.sync (dart:async/future.dart:224:31)\n#3      Domain.handleCommand (package:flutter_tools/src/commands/daemon.dart:225:5)\n#4      Daemon._handleRequest (package:flutter_tools/src/commands/daemon.dart:152:28)\n#5      _rootRunUnary (dart:async/zone.dart:1192:38)\n#6      _CustomZone.runUnary (dart:async/zone.dart:1085:19)\n#7      _CustomZone.runUnaryGuarded (dart:async/zone.dart:987:7)\n#8      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11)\n#9      _BufferingStreamSubscription._add (dart:async/stream_impl.dart:266:7)\n#10     _ForwardingStreamSubscription._add (dart:async/stream_pipe.dart:134:11)\n#11     _MapStream._handleData (dart:async/stream_pipe.dart:234:10)\n#12     _ForwardingStreamSubscription._handleData (dart:async/stream_pipe.dart:166:13)\n#13     _rootRunUnary (dart:async/zone.dart:1192:38)\n#14     _CustomZone.runUnary (dart:async/zone.dart:1085:19)\n#15     _CustomZone.runUnaryGuarded (dart:async/zone.dart:987:7)\n#16     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11)\n#17     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:266:7)\n#18     _ForwardingStreamSubscription._add (dart:async/stream_pipe.dart:134:11)\n#19     _WhereStream._handleData (dart:async/stream_pipe.dart:209:12)\n#20     _ForwardingStreamSubscription._handleData (dart:async/stream_pipe.dart:166:13)\n#21     _rootRunUnary (dart:async/zone.dart:1192:38)\n#22     _CustomZone.runUnary (dart:async/zone.dart:1085:19)\n#23     _CustomZone.runUnaryGuarded (dart:async/zone.dart:987:7)\n#24     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11)\n#25     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:266:7)\n#26     _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:70:11)\n#27     _EventSinkWrapper.add (dart:async/stream_transformers.dart:17:11)\n#28     _StringAdapterSink.add (dart:convert/string_conversion.dart:238:11)\n#29     _LineSplitterSink._addLines (dart:convert/line_splitter.dart:152:13)\n#30     _LineSplitterSink.addSlice (dart:convert/line_splitter.dart:127:5)\n#31     StringConversionSinkMixin.add (dart:convert/string_conversion.dart:165:5)\n#32     _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:122:24)\n#33     _rootRunUnary (dart:async/zone.dart:1192:38)\n#34     _CustomZone.runUnary (dart:async/zone.dart:1085:19)\n#35     _CustomZone.runUnaryGuarded (dart:async/zone.dart:987:7)\n#36     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11)\n#37     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:266:7)\n#38     _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:70:11)\n#39     _EventSinkWrapper.add (dart:async/stream_transformers.dart:17:11)\n#40     _StringAdapterSink.add (dart:convert/string_conversion.dart:238:11)\n#41     _StringAdapterSink.addSlice (dart:convert/string_conversion.dart:243:7)\n#42     _Utf8ConversionSink.addSlice (dart:convert/string_conversion.dart:314:20)\n#43     _Utf8ConversionSink.add (dart:convert/string_conversion.dart:307:5)\n#44     _ConverterStreamEventSink.add (dart:convert/chunked_conversion.dart:74:18)\n#45     _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:122:24)\n#46     _rootRunUnary (dart:async/zone.dart:1192:38)\n#47     _CustomZone.runUnary (dart:async/zone.dart:1085:19)\n#48     _CustomZone.runUnaryGuarded (dart:async/zone.dart:987:7)\n#49     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11)\n#50     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:266:7)\n#51     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:779:19)\n#52     _StreamController._add (dart:async/stream_controller.dart:655:7)\n#53     _StreamController.add (dart:async/stream_controller.dart:597:5)\n#54     _Socket._onData (dart:io-patch/socket_patch.dart:1982:41)\n#55     _rootRunUnary (dart:async/zone.dart:1196:13)\n#56     _CustomZone.runUnary (dart:async/zone.dart:1085:19)\n#57     _CustomZone.runUnaryGuarded (dart:async/zone.dart:987:7)\n#58     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11)\n#59     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:266:7)\n#60     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:779:19)\n#61     _StreamController._add (dart:async/stream_controller.dart:655:7)\n#62     _StreamController.add (dart:async/stream_controller.dart:597:5)\n#63     new _RawSocket.<anonymous closure> (dart:io-patch/socket_patch.dart:1527:33)\n#64     _NativeSocket.issueReadEvent.issue (dart:io-patch/socket_patch.dart:1019:14)\n#65     _microtaskLoop (dart:async/schedule_microtask.dart:43:21)\n#66     _startMicrotaskLoop (dart:async/schedule_microtask.dart:52:5)\n#67     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)\n#68     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:169:5)\n"}]
```

```
[✓] Flutter (Channel stable, v1.17.1, on Mac OS X 10.15.4 19E287, locale en-US)
    • Flutter version 1.17.1 at /Users/murathan/Downloads/project/flutter
    • Framework revision f7a6a7906b (29 hours ago), 2020-05-12 18:39:00 -0700
    • Engine revision 6bc433c6b6
    • Dart version 2.8.2

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/murathan/Library/Android/sdk
    • Platform android-29, build-tools 29.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✗] Xcode - develop for iOS and macOS
    ✗ Xcode installation is incomplete; a full installation is necessary for iOS development.
      Download at: https://developer.apple.com/xcode/download/
      Or install Xcode via the App Store.
      Once installed, run:
        sudo xcode-select --switch /Applications/Xcode.app/Contents/Developer
        sudo xcodebuild -runFirstLaunch
    ✗ CocoaPods not installed.
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin code that responds to your plugin usage on
        the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To install:
        sudo gem install cocoapods

[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)

[!] IntelliJ IDEA Community Edition (version 2017.3.2)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.dev/intellij-setup/#installing-the-plugins

[✓] Connected device (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 10 (API 29) (emulator)
```

Thanks for help.

**Comment by liodali** [comment]
i think you have problem in this package extended_image make sure to upgrade it to 0.7.3+1

**Comment by MurathanGoktas** [comment]
Yeap extended_image package was causing me problems. Then I discovered other package versions that were outdated for flutter 1.17.1 in iterative builds. After updating them build went through.

Thanks!
