### ISSUE TITLE
Flutter Web failing to compile

### ISSUE THREAD

**Issue by jaxnz** [flutter/flutter#57275]
Has happened on the latest upgrade, initially happened on `master`, and has now happened after reverting to `beta`

**Logs:**

```
C:\Users\Kamson\AndroidStudioProjects\ECS>flutter run -d chrome --verbose
[   +7 ms] executing: [C:\src\flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[  +44 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[        ] 2738a1148ba6c9a6114df62358109407c3ef2553
[        ] executing: [C:\src\flutter/] git tag --contains HEAD
[ +164 ms] Exit code 0 from: git tag --contains HEAD
[   +1 ms] 1.18.0-11.1.pre
[   +8 ms] executing: [C:\src\flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[  +25 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/beta
[        ] executing: [C:\src\flutter/] git ls-remote --get-url origin
[  +22 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[  +55 ms] executing: [C:\src\flutter/] git rev-parse --abbrev-ref HEAD
[  +24 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] beta
[  +42 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +2 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +13 ms] executing: C:\Users\Kamson\AppData\Local\Android\sdk\platform-tools\adb.exe devices -l
[  +30 ms] List of devices attached
           ce03171383c3c8ad0c     unauthorized transport_id:6
[   +5 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[   +2 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +78 ms] Found plugin cloud_firestore at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\cloud_firestore-0.13.5\
[   +6 ms] Found plugin cloud_firestore_web at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\cloud_firestore_web-0.1.1+2\
[   +6 ms] Found plugin firebase_auth at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_auth-0.16.0\
[   +2 ms] Found plugin firebase_auth_web at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_auth_web-0.1.2\
[   +1 ms] Found plugin firebase_core at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_core-0.4.4+3\
[   +2 ms] Found plugin firebase_core_web at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_core_web-0.1.1+2\
[   +1 ms] Found plugin firebase_storage at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_storage-3.1.5\
[   +4 ms] Found plugin flutter_keyboard_visibility at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\flutter_keyboard_visibility-0.7.0\
[   +1 ms] Found plugin flutter_plugin_android_lifecycle at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\flutter_plugin_android_lifecycle-1.0.7\
[   +4 ms] Found plugin image_picker at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\image_picker-0.6.6+1\
[   +5 ms] Found plugin path_provider at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\path_provider-1.6.8\
[   +1 ms] Found plugin path_provider_macos at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\path_provider_macos-0.0.4+2\
[  +57 ms] Found plugin cloud_firestore at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\cloud_firestore-0.13.5\
[   +2 ms] Found plugin cloud_firestore_web at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\cloud_firestore_web-0.1.1+2\
[   +5 ms] Found plugin firebase_auth at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_auth-0.16.0\
[   +2 ms] Found plugin firebase_auth_web at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_auth_web-0.1.2\
[   +1 ms] Found plugin firebase_core at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_core-0.4.4+3\
[   +1 ms] Found plugin firebase_core_web at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_core_web-0.1.1+2\
[   +1 ms] Found plugin firebase_storage at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_storage-3.1.5\
[   +2 ms] Found plugin flutter_keyboard_visibility at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\flutter_keyboard_visibility-0.7.0\
[        ] Found plugin flutter_plugin_android_lifecycle at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\flutter_plugin_android_lifecycle-1.0.7\
[   +3 ms] Found plugin image_picker at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\image_picker-0.6.6+1\
[   +4 ms] Found plugin path_provider at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\path_provider-1.6.8\
[   +1 ms] Found plugin path_provider_macos at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\path_provider_macos-0.0.4+2\
[  +38 ms] Generating C:\Users\Kamson\AndroidStudioProjects\ECS\android\app\src\main\java\io\flutter\plugins\GeneratedPluginRegistrant.java
[  +69 ms] Launching lib\main.dart on Chrome in debug mode...
[  +37 ms] Updating assets
[  +96 ms] Syncing files to device Chrome...
[   +8 ms] Found plugin cloud_firestore at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\cloud_firestore-0.13.5\
[   +1 ms] Found plugin cloud_firestore_web at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\cloud_firestore_web-0.1.1+2\
[   +3 ms] Found plugin firebase_auth at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_auth-0.16.0\
[   +1 ms] Found plugin firebase_auth_web at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_auth_web-0.1.2\
[   +1 ms] Found plugin firebase_core at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_core-0.4.4+3\
[   +1 ms] Found plugin firebase_core_web at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_core_web-0.1.1+2\
[        ] Found plugin firebase_storage at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_storage-3.1.5\
[   +2 ms] Found plugin flutter_keyboard_visibility at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\flutter_keyboard_visibility-0.7.0\
[        ] Found plugin flutter_plugin_android_lifecycle at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\flutter_plugin_android_lifecycle-1.0.7\
[   +2 ms] Found plugin image_picker at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\image_picker-0.6.6+1\
[   +3 ms] Found plugin path_provider at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\path_provider-1.6.8\
[        ] Found plugin path_provider_macos at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\path_provider_macos-0.0.4+2\
[  +13 ms] Found plugin cloud_firestore at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\cloud_firestore-0.13.5\
[   +1 ms] Found plugin cloud_firestore_web at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\cloud_firestore_web-0.1.1+2\
[   +2 ms] Found plugin firebase_auth at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_auth-0.16.0\
[   +1 ms] Found plugin firebase_auth_web at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_auth_web-0.1.2\
[   +1 ms] Found plugin firebase_core at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_core-0.4.4+3\
[   +1 ms] Found plugin firebase_core_web at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_core_web-0.1.1+2\
[        ] Found plugin firebase_storage at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_storage-3.1.5\
[   +1 ms] Found plugin flutter_keyboard_visibility at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\flutter_keyboard_visibility-0.7.0\
[        ] Found plugin flutter_plugin_android_lifecycle at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\flutter_plugin_android_lifecycle-1.0.7\
[   +2 ms] Found plugin image_picker at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\image_picker-0.6.6+1\
[   +3 ms] Found plugin path_provider at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\path_provider-1.6.8\
[   +1 ms] Found plugin path_provider_macos at C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\path_provider_macos-0.0.4+2\
[  +11 ms] Generating C:\Users\Kamson\AndroidStudioProjects\ECS\android\app\src\main\java\io\flutter\plugins\GeneratedPluginRegistrant.java
[  +48 ms] <- reset
[   +5 ms] C:\src\flutter\bin\cache\dart-sdk\bin\dart.exe C:\src\flutter\bin\cache\artifacts\engine\windows-x64\frontend_server.dart.snapshot --sdk-root C:\src\flutter\bin\cache\flutter_web_sdk/ --incremental --target=dartdevc --debugger-module-names -Ddart.developer.causal_async_stacks=true --output-dill
C:\Users\Kamson\AppData\Local\Temp\flutter_tool.96a29a83-964d-11ea-824a-dcf5054656e8\app.dill --libraries-spec file:///C:/src/flutter/bin/cache/flutter_web_sdk/libraries.json --packages .packages -Ddart.vm.profile=false -Ddart.vm.product=false
--bytecode-options=source-positions,local-var-info,debugger-stops,instance-field-initializers,keep-unreachable-code,avoid-closure-call-instructions --enable-asserts --track-widget-creation --filesystem-root C:\Users\Kamson\AppData\Local\Temp\flutter_tools.96a29a84-964d-11ea-824a-dcf5054656e8 --filesystem-scheme org-dartlang-app --initialize-from-dill
build\cache.dill --platform file:///C:/src/flutter/bin/cache/flutter_web_sdk/kernel/flutter_ddc_sdk.dill
[   +8 ms] <- compile org-dartlang-app:/web_entrypoint.dart
[+1197 ms]
                    Compiler message:
[        ] /C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_chips_input-1.8.1/lib/src/chips_input.dart:65:7: Error: The non-abstract class 'ChipsInputState' is missing implementations for these members:
[        ]  - TextInputClient.currentAutofillScope
[        ] Try to either
[        ]  - provide an implementation,
[        ]  - inherit an implementation from a superclass or mixin,
[        ]  - mark the class as abstract, or
[        ]  - provide a 'noSuchMethod' implementation.
[        ] class ChipsInputState<T> extends State<ChipsInput<T>>
[        ]       ^^^^^^^^^^^^^^^
[        ] /C:/src/flutter/packages/flutter/lib/src/services/text_input.dart:769:21: Context: 'TextInputClient.currentAutofillScope' is defined here.
[        ]   AutofillScope get currentAutofillScope;
[        ]                     ^^^^^^^^^^^^^^^^^^^^
[+13908 ms] Syncing files to device Chrome... (completed in 15,237ms, longer than expected)
[   +1 ms] Synced 0.0MB.
[        ] Failed to compile application.
[   +3 ms] "flutter run" took 15,770ms.

#0      throwToolExit (package:flutter_tools/src/base/common.dart:14:3)
#1      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:570:7)
<asynchronous suspension>
#2      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:797:18)
#3      _rootRunUnary (dart:async/zone.dart:1192:38)
#4      _CustomZone.runUnary (dart:async/zone.dart:1085:19)
#5      _FutureListener.handleValue (dart:async/future_impl.dart:141:18)
#6      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:686:45)
#7      Future._propagateToListeners (dart:async/future_impl.dart:715:32)
#8      Future._completeWithValue (dart:async/future_impl.dart:526:5)
#9      _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:36:15)
#10     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:303:13)
#11     RunCommand.usageValues (package:flutter_tools/src/commands/run.dart)
#12     _rootRunUnary (dart:async/zone.dart:1192:38)
#13     _CustomZone.runUnary (dart:async/zone.dart:1085:19)
#14     _FutureListener.handleValue (dart:async/future_impl.dart:141:18)
#15     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:686:45)
#16     Future._propagateToListeners (dart:async/future_impl.dart:715:32)
#17     Future._completeWithValue (dart:async/future_impl.dart:526:5)
#18     Future._asyncCompleteWithValue.<anonymous closure> (dart:async/future_impl.dart:560:7)
#19     _rootRun (dart:async/zone.dart:1184:13)
#20     _CustomZone.run (dart:async/zone.dart:1077:19)
#21     _CustomZone.runGuarded (dart:async/zone.dart:979:7)
#22     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1019:23)
#23     _microtaskLoop (dart:async/schedule_microtask.dart:43:21)
#24     _startMicrotaskLoop (dart:async/schedule_microtask.dart:52:5)
#25     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
#26     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:169:5)
```

**Doctor:**

```
C:\Users\Kamson\AndroidStudioProjects\ECS>flutter doctor -v
[√] Flutter (Channel beta, 1.18.0-11.1.pre, on Microsoft Windows [Version 10.0.18363.778], locale en-NZ)
    • Flutter version 1.18.0-11.1.pre at C:\src\flutter
    • Framework revision 2738a1148b (28 hours ago), 2020-05-13 15:24:36 -0700
    • Engine revision ef9215ceb2
    • Dart version 2.9.0 (build 2.9.0-8.2.beta)

[!] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at C:\Users\Kamson\AppData\Local\Android\sdk
    • Platform android-29, build-tools 29.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)
    X Android license status unknown.
      Try re-installing or updating your Android SDK Manager.
      See https://developer.android.com/studio/#downloads or visit visit https://flutter.dev/docs/get-started/install/windows#android-setup for detailed instructions.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 3.6)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)

[√] IntelliJ IDEA Community Edition (version 2019.3)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2019.3.3
    • Flutter plugin version 44.0.3
    • Dart plugin version 193.6494.35

[√] Connected device (2 available)
    • Web Server • web-server • web-javascript • Flutter Tools
    • Chrome     • chrome     • web-javascript • Google Chrome 81.0.4044.138

! Doctor found issues in 1 category.

```

**Comment by slavap** [comment]
@jaxnz use https://pub.dev/packages/flutter_chips_input/versions/1.9.0-dev.1

**Comment by jaxnz** [comment]
> @jaxnz use https://pub.dev/packages/flutter_chips_input/versions/1.9.0-dev.1

This has fixed the issue, I have requested [flutter_form_builder](https://pub.dev/packages/flutter_form_builder) to update the package dependencies

**Comment by shwehan** [comment]
I'm having Failed to compile application erring (web). It was working perfectly until last friday. Did the new update from last week have any impacts toward web (for debugging mode on chrome)?

**Comment by shwehan** [comment]
> I'm having Failed to compile application erring (web). It was working perfectly until last friday. Did the new update from last week have any impacts toward web (for debugging mode on chrome)?

(just a follow up, the application is running on beta channel, and also I did all flutter upgrade and  flutter config --enable-web. Flutter doctor is all good too. Not sure, why suddenly having Failed to compile application.

**Comment by jaxnz** [comment]
If you are using flutter_form_builder and now not being able to compile -  adding the below to your pubspec file will fix the issue

`flutter_chips_input: ^1.9.0-dev.1`

**Comment by shwehan** [comment]
Ohh adding that solved it! Thanks!! I wasn't thinking about that adding previously because I wasn't using flutter_chips_input.

**Comment by jaxnz** [comment]
yeah, the package `flutter_form_builder` runs an older version of `flutter_chips_input` so to get the fix you have to manually update that package to get the fix
