### ISSUE TITLE
i cant run my app

### ISSUE THREAD

**Issue by grammystrano** [flutter/flutter#57279]
### **this what i get :**

![ff](https://user-images.githubusercontent.com/65091295/82010096-09e5a980-9669-11ea-9bd5-7f4e6f9a9622.png)

**Comment by srikanth7785** [comment]
Try `flutter clean`..
and also..
Do uninstall and install the app again..it happened for me some time back..I solved it with `flutter clean`..

Hope it works out for you as well..

**Comment by grammystrano** [comment]
### **look !!!**

![image](https://user-images.githubusercontent.com/65091295/82031586-04508980-9692-11ea-903a-94cffdee5e13.png)

**Comment by iapicca** [comment]
Hi @grammystrano 
can you please provide your `flutter doctor -v` , 
your `flutter run --verbose` 
and your `pubspec.yaml` 
or if possible a reproducible minimal code sample.
Thank you

**Comment by grammystrano** [comment]
### **flutter doctor -v**
[√] Flutter (Channel master, 1.19.0-2.0.pre.71, on Microsoft Windows [version 10.0.18362.836], locale fr-TN)
    • Flutter version 1.19.0-2.0.pre.71 at D:\Games\flutter
    • Framework revision 800e951160 (8 hours ago), 2020-05-14 20:47:01 -0400
    • Engine revision 50e55cf69e
    • Dart version 2.9.0 (build 2.9.0-9.0.dev 2676764792)


[√] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at C:\Users\oussa\AppData\Local\Android\sdk
    • Platform android-R, build-tools 29.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)
    • All Android licenses accepted.

[√] Android Studio (version 3.6)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.8052
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)

[√] VS Code (version 1.45.0)
    • VS Code at C:\Users\oussa\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.10.1

[√] Connected device (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 7.1.1 (API 25) (emulator)

• No issues found!

### **flutter** run --verbose
[  +10 ms] executing: [D:\Games\flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[  +63 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[        ] 800e9511600c4a9c913cc29b21928d6a42d1e057
[   +1 ms] executing: [D:\Games\flutter/] git tag --contains HEAD
[ +231 ms] Exit code 0 from: git tag --contains HEAD
[   +3 ms] executing: [D:\Games\flutter/] git describe --match *.*.*-*.*.pre --first-parent --long --tags
[ +185 ms] Exit code 0 from: git describe --match *.*.*-*.*.pre --first-parent --long --tags
[        ] 1.19.0-1.0.pre-71-g800e95116
[   +9 ms] executing: [D:\Games\flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[  +72 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/master
[        ] executing: [D:\Games\flutter/] git ls-remote --get-url origin
[  +40 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[ +127 ms] executing: [D:\Games\flutter/] git rev-parse --abbrev-ref HEAD
[  +42 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] master
[  +61 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +3 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +18 ms] executing: C:\Users\oussa\AppData\Local\Android\sdk\platform-tools\adb.exe devices -l
[  +66 ms] List of devices attached
           emulator-5554          device product:sdk_google_phone_x86 model:Android_SDK_built_for_x86 device:generic_x86 transport_id:1
[   +8 ms] C:\Users\oussa\AppData\Local\Android\sdk\platform-tools\adb.exe -s emulator-5554 shell getprop
[  +59 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[   +5 ms] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +4 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[ +232 ms] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[   +1 ms] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +28 ms] "flutter run" took 449ms.
Error: No pubspec.yaml file found.
This command should be run from the root of your Flutter project.
Do not run this command from the root of your git clone of Flutter.

#0      FlutterCommand.validateCommand (package:flutter_tools/src/runner/flutter_command.dart:878:11)
#1      RunCommand.validateCommand (package:flutter_tools/src/commands/run.dart:329:19)
#2      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:778:11)
<asynchronous suspension>
#3      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:695:33)
<asynchronous suspension>
#4      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart)
#5      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:29)
#6      _rootRun (dart:async/zone.dart:1190:13)
#7      _CustomZone.run (dart:async/zone.dart:1093:19)
#8      _runZoned (dart:async/zone.dart:1630:10)
#9      runZoned (dart:async/zone.dart:1550:10)
#10     AppContext.run (package:flutter_tools/src/base/context.dart:149:18)
#11     FlutterCommand.run (package:flutter_tools/src/runner/flutter_command.dart:685:20)
#12     CommandRunner.runCommand (package:args/command_runner.dart:197:27)
#13     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:339:21)
#14     _rootRunUnary (dart:async/zone.dart:1198:47)
#15     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
#16     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
#17     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
#18     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
#19     Future._completeWithValue (dart:async/future_impl.dart:529:5)
#20     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:40:15)
#21     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:311:13)
#22     FlutterVersion.checkFlutterVersionFreshness (package:flutter_tools/src/version.dart)
#23     _rootRunUnary (dart:async/zone.dart:1198:47)
#24     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
#25     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
#26     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
#27     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
#28     Future._completeWithValue (dart:async/future_impl.dart:529:5)
#29     Future._asyncCompleteWithValue.<anonymous closure> (dart:async/future_impl.dart:567:7)
#30     _rootRun (dart:async/zone.dart:1190:13)
#31     _CustomZone.run (dart:async/zone.dart:1093:19)
#32     _CustomZone.runGuarded (dart:async/zone.dart:997:7)
#33     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1037:23)
#34     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#35     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#36     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
#37     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:169:5)

### **pubspec.yaml**

![image](https://user-images.githubusercontent.com/65091295/82033555-cbfe7a80-9694-11ea-9d2f-271d0e3bd9d7.png)

**Comment by srikanth7785** [comment]
> ### **look !!!**
> ![image](https://user-images.githubusercontent.com/65091295/82031586-04508980-9692-11ea-903a-94cffdee5e13.png)


`flutter clean` should be executed at the root directory of your project.. whereas you did that `C/user..`..

It is also mentioned in the second line of the error message displayed in the image..

So..go to your project in the terminal..and execute `flutter clean` at that location and then run your app again.. probably, that will solve your issue.

**Comment by grammystrano** [comment]
I did it nd still the same response

**Comment by manassehl9** [comment]
you should be in...   C:\Users\oussa\AndroidStudioProjects\flutter_app
then you can run flutter clean @grammystrano 

>

**Comment by jonahwilliams** [comment]
clean should not do anything in this situation, please stop suggesting it as a response. @grammystrano the error indicates a native crash in your application, you'll need to run `adb logcat`  and look for stack traces when starting the app. 

We recently added better logging support in the tool to surface these automatically, so you could also temporarily checkout a master branch and see if it reproduces

**Comment by iapicca** [comment]
Hi @grammystrano 
as [suggested](https://github.com/flutter/flutter/issues/57279#issuecomment-629536632) by @jonahwilliams 
could you please temporarily upgrade running
```console
flutter channel master 
flutter upgrade --force
```
and run again `flutter run --verbose`,
please make sure that you are running the command 
from your app folder
Thank you
