### ISSUE TITLE
[tool_crash] NoSuchMethodError: The method 'allElements' was called on null.Receiver: nullTried calling: allElements("activity")

### ISSUE THREAD

**Issue by wangzl8128** [flutter/flutter#57281]
## Command
```
flutter --no-color run --machine --track-widget-creation --device-id=3DN4C16411034227 lib/main.dart
```

## Steps to Reproduce
1. ...
2. ...
3. ...

## Logs
NoSuchMethodError: NoSuchMethodError: The method 'allElements' was called on null.
Receiver: null
Tried calling: allElements("activity")
```
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:53:5)
#1      ApkManifestData.parseFromXmlDump (package:flutter_tools/src/application_package.dart:563:55)
#2      new AndroidApk.fromApk (package:flutter_tools/src/application_package.dart:135:50)
#3      AndroidApk.fromAndroidProject (package:flutter_tools/src/application_package.dart:173:27)
<asynchronous suspension>
#4      AndroidDevice.startApp (package:flutter_tools/src/android/android_device.dart:524:34)
<asynchronous suspension>
#5      FlutterDevice.runHot (package:flutter_tools/src/resident_runner.dart:437:54)
<asynchronous suspension>
#6      HotRunner.run (package:flutter_tools/src/run_hot.dart:361:31)
#7      AppDomain.startApp.<anonymous closure> (package:flutter_tools/src/commands/daemon.dart:518:23)
#8      AppDomain.launch.<anonymous closure> (package:flutter_tools/src/commands/daemon.dart:580:26)
#9      AppDomain.launch.<anonymous closure> (package:flutter_tools/src/commands/daemon.dart:578:38)
#10     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:29)
#11     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:7)
#12     _rootRun (dart:async/zone.dart:1184:13)
#13     _CustomZone.run (dart:async/zone.dart:1077:19)
#14     _runZoned (dart:async/zone.dart:1619:10)
#15     runZoned (dart:async/zone.dart:1539:10)
#16     AppContext.run (package:flutter_tools/src/base/context.dart:149:18)
```
```
[✓] Flutter (Channel stable, v1.17.1, on Mac OS X 10.15.4 19E287, locale zh-Hans-CN)
    • Flutter version 1.17.1 at /Users/tlcd/Documents/flutter
    • Framework revision f7a6a7906b (2 days ago), 2020-05-12 18:39:00 -0700
    • Engine revision 6bc433c6b6
    • Dart version 2.8.2

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/tlcd/Library/Android/sdk
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[!] Xcode - develop for iOS and macOS (Xcode 11.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.4.1, Build version 11E503a
    ✗ CocoaPods not installed.
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To install:
        sudo gem install cocoapods

[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.8052
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)

[!] IntelliJ IDEA Ultimate Edition (version 2019.3.1)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.dev/intellij-setup/#installing-the-plugins

[!] VS Code (version 1.45.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    ✗ Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (1 available)
    • HUAWEI VNS AL00 • 3DN4C16411034227 • android-arm64 • Android 6.0 (API 23)

! Doctor found issues in 3 categories.

```

## Flutter Application Metadata
**Type**: app
**Version**: 1.0.0+1
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: stable
**Creation framework version**: f7a6a7906be96d2288f5d63a5a54c515a6e987fe

**Comment by VladyslavBondarenko** [comment]
Hi @wangzl8128 
is https://github.com/flutter/flutter/issues/21912#issuecomment-452215426 your case?
could you provide minimal project to reproduce it?

**Comment by jonahwilliams** [comment]
@VladyslavBondarenko please don't ask for reproductions from automated tool crash reports. This contains everything we need to fix a bug, and its important that we see this quickly
