### ISSUE TITLE
ios13 TextFormField  long press space confusion

### ISSUE THREAD

**Issue by zhanglijie5997** [flutter/flutter#57375]
Ios13 long press space to move the cursor position cannot move

**Comment by TahaTesser** [comment]
Hi @zhanglijie5997 
can you please provide your `flutter doctor -v` and `flutter run --verbose`? 
Also, to better address the issue, would be helpful if you could post a minimal code sample to reproduce the problem
Thank you

**Comment by zhanglijie5997** [comment]
```
[✓] Flutter (Channel master, v1.13.7-pre.10, on Mac OS X 10.15.4 19E287, locale
    zh-Hans-CN)
    • Flutter version 1.13.7-pre.10 at /Users/ljz/flutter
    • Framework revision 57a93419b4 (5 months ago), 2020-01-02 16:19:52 -0800
    • Engine revision fa05d367ad
    • Dart version 2.8.0 (build 2.8.0-dev.0.0 b52d264f5b)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/ljz/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling
      support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.4.1, Build version 11E503a
    • CocoaPods version 1.8.4

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 44.0.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build
      1.8.0_202-release-1483-b49-5587405)

[✓] IntelliJ IDEA Ultimate Edition (version 2019.3.1)
    • IntelliJ at /Users/ljz/Applications/JetBrains Toolbox/IntelliJ IDEA
      Ultimate.app
    • Flutter plugin version 42.1.4
    • Dart plugin version 193.5731

[✓] Connected device (1 available)
    • iPhone 11 Pro • 2C78E656-E264-4BDD-B05A-BD6328477C2A • ios •
      com.apple.CoreSimulator.SimRuntime.iOS-13-4 (simulator)
```
flutter run --verbose

 ```
Compiler message:
[        ] ../flutter/packages/flutter/lib/src/widgets/basic.dart:5156:9: Error: Type 'ui.TextHeightBehavior' not found.
[        ]   final ui.TextHeightBehavior textHeightBehavior;
[        ]         ^^^^^^^^^^^^^^^^^^^^^
[   +6 ms] ../flutter/packages/flutter/lib/src/widgets/implicit_animations.dart:1593:9: Error: Type 'ui.TextHeightBehavior' not found.
[        ]   final ui.TextHeightBehavior textHeightBehavior;
[        ]         ^^^^^^^^^^^^^^^^^^^^^
[   +1 ms] ../flutter/packages/flutter/lib/src/widgets/text.dart:149:9: Error: Type 'ui.TextHeightBehavior' not found.
[        ]   final ui.TextHeightBehavior textHeightBehavior;
[        ]         ^^^^^^^^^^^^^^^^^^^^^
[        ] ../flutter/packages/flutter/lib/src/widgets/text.dart:432:9: Error: Type 'ui.TextHeightBehavior' not found.
[        ]   final ui.TextHeightBehavior textHeightBehavior;
[        ]         ^^^^^^^^^^^^^^^^^^^^^
[   +2 ms] ../flutter/packages/flutter/lib/src/rendering/paragraph.dart:78:5: Error: Type 'ui.TextHeightBehavior' not found.
[        ]     ui.TextHeightBehavior textHeightBehavior,
[   +8 ms]     ^^^^^^^^^^^^^^^^^^^^^
[        ] ../flutter/packages/flutter/lib/src/rendering/paragraph.dart:281:3: Error: Type 'ui.TextHeightBehavior' not found.
[        ]   ui.TextHeightBehavior get textHeightBehavior => _textPainter.textHeightBehavior;
[        ]   ^^^^^^^^^^^^^^^^^^^^^
[        ] ../flutter/packages/flutter/lib/src/rendering/paragraph.dart:282:26: Error: Type 'ui.TextHeightBehavior' not found.
[        ]   set textHeightBehavior(ui.TextHeightBehavior value) {
[        ]                          ^^^^^^^^^^^^^^^^^^^^^
[        ] ../flutter/packages/flutter/lib/src/painting/text_painter.dart:145:5: Error: Type 'ui.TextHeightBehavior' not found.
[        ]     ui.TextHeightBehavior textHeightBehavior,
[        ]     ^^^^^^^^^^^^^^^^^^^^^
[        ] ../flutter/packages/flutter/lib/src/painting/text_painter.dart:346:3: Error: Type 'ui.TextHeightBehavior' not found.
[        ]   ui.TextHeightBehavior get textHeightBehavior => _textHeightBehavior;
[        ]   ^^^^^^^^^^^^^^^^^^^^^
[        ] ../flutter/packages/flutter/lib/src/painting/text_painter.dart:347:3: Error: Type 'ui.TextHeightBehavior' not found.
[        ]   ui.TextHeightBehavior _textHeightBehavior;
[        ]   ^^^^^^^^^^^^^^^^^^^^^
[        ] ../flutter/packages/flutter/lib/src/painting/text_painter.dart:348:26: Error: Type 'ui.TextHeightBehavior' not found.
[        ]   set textHeightBehavior(ui.TextHeightBehavior value) {
[        ]                          ^^^^^^^^^^^^^^^^^^^^^
[        ] ../flutter/packages/flutter/lib/src/painting/text_style.dart:1070:5: Error: Type 'ui.TextHeightBehavior' not found.
[        ]     ui.TextHeightBehavior textHeightBehavior,
[        ]     ^^^^^^^^^^^^^^^^^^^^^
[+1836 ms] ../flutter/packages/flutter/lib/src/widgets/basic.dart:5156:12: Error: 'TextHeightBehavior' isn't a type.
[        ]   final ui.TextHeightBehavior textHeightBehavior;
[        ]            ^^^^^^^^^^^^^^^^^^
[ +165 ms] ../flutter/packages/flutter/lib/src/widgets/implicit_animations.dart:1593:12: Error: 'TextHeightBehavior' isn't a type.
[        ]   final ui.TextHeightBehavior textHeightBehavior;
[        ]            ^^^^^^^^^^^^^^^^^^
[        ] ../flutter/packages/flutter/lib/src/widgets/implicit_animations.dart:1607:43: Error: 'TextHeightBehavior' isn't a type.
[        ]     properties.add(DiagnosticsProperty<ui.TextHeightBehavior>('textHeightBehavior', textHeightBehavior, defaultValue: null));
[        ]                                           ^^^^^^^^^^^^^^^^^^
[  +35 ms] ../flutter/packages/flutter/lib/src/widgets/media_query.dart:127:51: Error: The getter 'highContrast' isn't defined for the class 'AccessibilityFeatures'.
[        ]  - 'AccessibilityFeatures' is from 'dart:ui'.
[        ] Try correcting the name to the name of an existing getter, or defining a getter or field named 'highContrast'.
[        ]       highContrast = window.accessibilityFeatures.highContrast,
[        ]                                                   ^^^^^^^^^^^^
[ +182 ms] ../flutter/packages/flutter/lib/src/widgets/text.dart:149:12: Error: 'TextHeightBehavior' isn't a type.
[        ]   final ui.TextHeightBehavior textHeightBehavior;
[        ]            ^^^^^^^^^^^^^^^^^^
[        ] ../flutter/packages/flutter/lib/src/widgets/text.dart:200:43: Error: 'TextHeightBehavior' isn't a type.
[        ]     properties.add(DiagnosticsProperty<ui.TextHeightBehavior>('textHeightBehavior', textHeightBehavior, defaultValue: null));
[        ]                                           ^^^^^^^^^^^^^^^^^^
[        ] ../flutter/packages/flutter/lib/src/widgets/text.dart:432:12: Error: 'TextHeightBehavior' isn't a type.
[        ]   final ui.TextHeightBehavior textHeightBehavior;
[        ]            ^^^^^^^^^^^^^^^^^^
[        ] ../flutter/packages/flutter/lib/src/widgets/text.dart:487:43: Error: 'TextHeightBehavior' isn't a type.
[        ]     properties.add(DiagnosticsProperty<ui.TextHeightBehavior>('textHeightBehavior', textHeightBehavior, defaultValue: null));
[        ]                                           ^^^^^^^^^^^^^^^^^^
[ +401 ms] ../flutter/packages/flutter/lib/src/rendering/paragraph.dart:78:8: Error: 'TextHeightBehavior' isn't a type.
[        ]     ui.TextHeightBehavior textHeightBehavior,
[        ]        ^^^^^^^^^^^^^^^^^^
[   +1 ms] ../flutter/packages/flutter/lib/src/rendering/paragraph.dart:282:29: Error: 'TextHeightBehavior' isn't a type.
[        ]   set textHeightBehavior(ui.TextHeightBehavior value) {
[        ]                             ^^^^^^^^^^^^^^^^^^
[ +248 ms] ../flutter/packages/flutter/lib/src/painting/text_painter.dart:145:8: Error: 'TextHeightBehavior' isn't a type.
[        ]     ui.TextHeightBehavior textHeightBehavior,
[        ]        ^^^^^^^^^^^^^^^^^^
[        ] ../flutter/packages/flutter/lib/src/painting/text_painter.dart:347:6: Error: 'TextHeightBehavior' isn't a type.
[        ]   ui.TextHeightBehavior _textHeightBehavior;
[        ]      ^^^^^^^^^^^^^^^^^^
[        ] ../flutter/packages/flutter/lib/src/painting/text_painter.dart:348:29: Error: 'TextHeightBehavior' isn't a type.
[        ]   set textHeightBehavior(ui.TextHeightBehavior value) {
[        ]                             ^^^^^^^^^^^^^^^^^^
[   +2 ms] ../flutter/packages/flutter/lib/src/painting/text_painter.dart:421:7: Error: No named parameter with the name 'textHeightBehavior'.
[        ]       textHeightBehavior: _textHeightBehavior,
[        ]       ^^^^^^^^^^^^^^^^^^
[        ] org-dartlang-sdk:///flutter/lib/ui/text.dart:877:3: Context: Found this candidate, but the arguments don't match.
[        ]   ParagraphStyle({
[        ]   ^^^^^^^^^^^^^^
[  +17 ms] ../flutter/packages/flutter/lib/src/painting/text_style.dart:1070:8: Error: 'TextHeightBehavior' isn't a type.
[        ]     ui.TextHeightBehavior textHeightBehavior,
[        ]        ^^^^^^^^^^^^^^^^^^
[        ] ../flutter/packages/flutter/lib/src/painting/text_style.dart:1091:7: Error: No named parameter with the name 'textHeightBehavior'.
[        ]       textHeightBehavior: textHeightBehavior,
[        ]       ^^^^^^^^^^^^^^^^^^
[        ] org-dartlang-sdk:///flutter/lib/ui/text.dart:877:3: Context: Found this candidate, but the arguments don't match.
[        ]   ParagraphStyle({
[        ]   ^^^^^^^^^^^^^^
[+2090 ms] Persisting file store
[   +6 ms] Done persisting file store
[   +1 ms] Target kernel_snapshot failed: Exception: Errors during snapshot creation: null
[        ] Failed to build bundle.
[        ] Error launching application on iPhone 11 Pro.
[  +12 ms] "flutter run" took 11,993ms.

#0      throwToolExit (package:flutter_tools/src/base/common.dart:28:3)
#1      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:560:7)
<asynchronous suspension>
#2      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:626:18)
#3      _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:75:64)
#4      _rootRunUnary (dart:async/zone.dart:1134:38)
#5      _CustomZone.runUnary (dart:async/zone.dart:1031:19)
#6      _FutureListener.handleValue (dart:async/future_impl.dart:140:18)
#7      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:682:45)
#8      Future._propagateToListeners (dart:async/future_impl.dart:711:32)
#9      Future._completeWithValue (dart:async/future_impl.dart:526:5)
#10     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:34:15)
#11     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:293:13)
#12     RunCommand.usageValues (package:flutter_tools/src/commands/run.dart)
#13     _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:75:64)
#14     _rootRunUnary (dart:async/zone.dart:1134:38)
#15     _CustomZone.runUnary (dart:async/zone.dart:1031:19)
#16     _FutureListener.handleValue (dart:async/future_impl.dart:140:18)
#17     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:682:45)
#18     Future._propagateToListeners (dart:async/future_impl.dart:711:32)
#19     Future._completeWithValue (dart:async/future_impl.dart:526:5)
#20     Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:556:7)
#21     _rootRun (dart:async/zone.dart:1126:13)
#22     _CustomZone.run (dart:async/zone.dart:1023:19)
#23     _CustomZone.runGuarded (dart:async/zone.dart:925:7)
#24     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:965:23)
#25     _microtaskLoop (dart:async/schedule_microtask.dart:43:21)
#26     _startMicrotaskLoop (dart:async/schedule_microtask.dart:52:5)
#27     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
#28     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:175:5)

```

**Comment by TahaTesser** [comment]
Hi @zhanglijie5997 
I see that you've 5 months old Flutter `master` channel, please upgrade to latest `master`. channel and try again 

`flutter channel master`
`flutter upgrade`
`flutter doctor -v`

If problem persist after upgrade, can you please provide your `flutter doctor -v` and `flutter run --verbose`? 
Also, to better address the issue, would be helpful if you could post a minimal code sample to reproduce the problem
Thank you

**Comment by zhanglijie5997** [comment]
```
Container(
                                // color: Colors.red,
                                alignment: Alignment.center,
                                width: 200,
                                height: 32,
                                child: TextField(
                                  maxLines: 1,
                                  onChanged: (String _text) {
                                    this.setState(() {
                                      _textVal = _text;
                                    });
                                  },
                                  controller: _textController,
                                  cursorWidth: 2,
                                  cursorColor: Colors.red,
                                  // textAlign: TextAlign.center,
                                  textAlignVertical: TextAlignVertical.center,
                                  style: TextStyle(
                                    fontSize: 18,
                                    color: Colors.white
                                  ),
                                  decoration: InputDecoration(
                                    border: InputBorder.none,
                                  ),
                                  inputFormatters: <TextInputFormatter>[
                                    LengthLimitingTextInputFormatter(17)
                                  ],
                                ),
                              )
```
The latest SDK will do the same

**Comment by TahaTesser** [comment]
Hi @zhanglijie5997 

Testing on latest `master` long press cursor seems to work fine without any errors in the logs 

<details> 
<summary>Code Sample</summary> 

``` 
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      debugShowCheckedModeBanner: false,
      title: 'Material App',
      theme: ThemeData.dark(),
      home: Home(),
    );
  }
}

class Home extends StatefulWidget {
  @override
  _HomeState createState() => _HomeState();
}

class _HomeState extends State<Home> {
  TextEditingController _textEditingController = TextEditingController();
  String _textVal = '';

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('Material App Bar'),
      ),
      body: Container(
        // color: Colors.red,
        alignment: Alignment.center,
        width: 200,
        height: 32,
        child: TextField(
          maxLines: 1,
          onChanged: (String _text) {
            this.setState(() {
              _textVal = _text;
            });
          },
          controller: _textEditingController,
          cursorWidth: 2,
          cursorColor: Colors.red,
          // textAlign: TextAlign.center,
          textAlignVertical: TextAlignVertical.center,
          style: TextStyle(fontSize: 18, color: Colors.white),
          decoration: InputDecoration(
              // border: InputBorder.none,
              ),
          inputFormatters: <TextInputFormatter>[
            LengthLimitingTextInputFormatter(17)
          ],
        ),
      ),
      floatingActionButton: FloatingActionButton(
        child: Icon(Icons.add),
        onPressed: () {},
      ),
    );
  }
}

``` 

</details> 


![ezgif com-resize](https://user-images.githubusercontent.com/48603081/82534230-6ada1980-9b62-11ea-81ee-37486fcd7170.gif)


<details> 
<summary>flutter doctor -v</summary> 

``` 
[✓] Flutter (Channel master, 1.19.0-2.0.pre.133, on Mac OS X 10.15.4 19E287,
    locale en-GB)
    • Flutter version 1.19.0-2.0.pre.133 at
      /Users/tahatesser/Code/flutter_master
    • Framework revision e92afc16b6 (11 hours ago), 2020-05-21 05:29:01 +0900
    • Engine revision 2d4e83921d
    • Dart version 2.9.0 (build 2.9.0-9.0.dev 40f7a11d89)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/tahatesser/Code/SDK
    • Platform android-29, build-tools 29.0.3
    • ANDROID_HOME = /Users/tahatesser/Code/SDK
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.4.1, Build version 11E503a
    • CocoaPods version 1.9.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.8052
    • Java version OpenJDK Runtime Environment (build
      1.8.0_212-release-1586-b4-5784211)

[✓] VS Code (version 1.45.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.10.2

[✓] Connected device (4 available)
    • iPhone 11  • B00B6F4E-B1CE-44F3-B81E-3EC6D639B008 • ios            •
      com.apple.CoreSimulator.SimRuntime.iOS-13-4 (simulator)
    • macOS      • macOS                                • darwin-x64     • Mac
      OS X 10.15.4 19E287
    • Web Server • web-server                           • web-javascript •
      Flutter Tools
    • Chrome     • chrome                               • web-javascript •
      Google Chrome 81.0.4044.138

• No issues found!

``` 

</details>

**Comment by zhanglijie5997** [comment]
Only on a real plane, the simulator is fine, maybe you can try the experience on a real plane, thank u

**Comment by TahaTesser** [comment]
Hi @zhanglijie5997 

Tested on iPhone XR physical device 

![ezgif com-resize](https://user-images.githubusercontent.com/48603081/82644542-1d77ae00-9c2f-11ea-8a03-d3427b2b5ab0.gif)


<details> 
<summary>flutter doctor -v</summary> 

``` 
[✓] Flutter (Channel dev, 1.19.0-1.0.pre, on Mac OS X 10.15.4 19E287, locale
    en-GB)
    • Flutter version 1.19.0-1.0.pre at /Users/tahatesser/Code/flutter_dev
    • Framework revision 456d80b9dd (11 days ago), 2020-05-11 11:45:03 -0400
    • Engine revision d96f962ca2
    • Dart version 2.9.0 (build 2.9.0-7.0.dev 092ed38a87)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/tahatesser/Code/SDK
    • Platform android-29, build-tools 29.0.3
    • ANDROID_HOME = /Users/tahatesser/Code/SDK
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.5, Build version 11E608c
    • CocoaPods version 1.9.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.8052
    • Java version OpenJDK Runtime Environment (build
      1.8.0_212-release-1586-b4-5784211)

[✓] VS Code (version 1.45.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.10.2

[✓] Connected device (4 available)
    • Taha’s iPhone • 00008020-001059882212002E • ios            • iOS 13.5
    • macOS         • macOS                     • darwin-x64     • Mac OS X
      10.15.4 19E287
    • Web Server    • web-server                • web-javascript • Flutter Tools
    • Chrome        • chrome                    • web-javascript • Google Chrome
      81.0.4044.138

• No issues found!
``` 

</details>

**Comment by zhanglijie5997** [comment]
There are a lot of developers who have this problem, they can't slide at the beginning, they need to slide to the far left to slide normally, you can try other models, thank you.

**Comment by TahaTesser** [comment]
Hi @zhanglijie5997 
Slide at the beginning works on latest `master`
Can you please you provide a gif or video of this issue with a code sample?
I couldn't find anyone reporting this issue 

<details> 
<summary>flutter doctor -v</summary> 

``` 
[✓] Flutter (Channel master, 1.19.0-2.0.pre.143, on Mac OS X 10.15.4 19E287,
    locale en-GB)
    • Flutter version 1.19.0-2.0.pre.143 at
      /Users/tahatesser/Code/flutter_master
    • Framework revision 9d58a87066 (2 days ago), 2020-05-22 22:37:01 -0700
    • Engine revision 9ce1e5c5c7
    • Dart version 2.9.0 (build 2.9.0-10.0.dev 7706afbcf5)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/tahatesser/Code/SDK
    • Platform android-29, build-tools 29.0.3
    • ANDROID_HOME = /Users/tahatesser/Code/SDK
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.5, Build version 11E608c
    • CocoaPods version 1.9.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.8052
    • Java version OpenJDK Runtime Environment (build
      1.8.0_212-release-1586-b4-5784211)

[✓] VS Code (version 1.45.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.10.2

[✓] Connected device (4 available)
    • Taha’s iPhone • 00008020-001059882212002E • ios            • iOS 13.5
    • macOS         • macOS                     • darwin-x64     • Mac OS X
      10.15.4 19E287
    • Web Server    • web-server                • web-javascript • Flutter Tools
    • Chrome        • chrome                    • web-javascript • Google Chrome
      81.0.4044.138

• No issues found!

``` 

</details> 
Thank you

**Comment by TahaTesser** [comment]
Without additional information we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.
