### ISSUE TITLE
 flutter doctor --android-licenses showing error

### ISSUE THREAD

**Issue by KoyyalamudiHarsha** [flutter/flutter#57372]
PS D:\Flutter Projects\flutter_quiz> flutter doctor --android-licenses
Exception in thread "main" java.lang.NoClassDefFoundError: javax/xml/bind/annotation/XmlSchema
        at com.android.repository.api.SchemaModule$SchemaModuleVersion.<init>(SchemaModule.java:156)
        at com.android.repository.api.SchemaModule.<init>(SchemaModule.java:75)
        at com.android.sdklib.repository.AndroidSdkHandler.<clinit>(AndroidSdkHandler.java:81)
        at com.android.sdklib.tool.sdkmanager.SdkManagerCli.main(SdkManagerCli.java:73)
        at com.android.sdklib.tool.sdkmanager.SdkManagerCli.main(SdkManagerCli.java:48)
Caused by: java.lang.ClassNotFoundException: javax.xml.bind.annotation.XmlSchema
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
        ... 5 more

**Comment by AndrewH2O** [comment]
This is because android uses jdk 8 and you have a later jdk in your env path (looks like Windows). I do work with java and don't wan't to downgrade my jdk. Android studio uses its own local version of jdk 8 so the problem doesn't arise there. Cannot understand why flutter doctor doesn't first check for that dependency. Difficulty here though is that the flutter installation instructions [https://flutter.dev/docs/get-started/install/windows](https://flutter.dev/docs/get-started/install/windows)  takes you down this route.

Temporary fix was to change my JAVA_HOME variable to C:\Program Files\Android\Android Studio\jre.  
This allowed those licenses to be accepted.
Then reverted back to my original value for JAVA_HOME
As I am using Android studio for flutter development it seems to work regardless which makes sense.
As there are many many google results about this issue may be good idea to revisit the install process/instructions perhaps?

**Comment by jonahwilliams** [comment]
What does `flutter doctor -v` say? We should be checking that the correct version of Java is installed?

**Comment by jonahwilliams** [comment]
That is, even if the doctor check is invalid we should validate the version before calling android licenses.

**Comment by AndrewH2O** [comment]
@jonahwilliams 
with a working setup in android studio and JAVA_HOME  C:\Program Files\Amazon Corretto\jdk11.0.6_10

**flutter doctor -v** 

[√] Flutter (Channel stable, v1.17.1, on Microsoft Windows [Version 10.0.18363.778], locale en-GB)
    • Flutter version 1.17.1 at P:\src\flutter
    • Framework revision f7a6a7906b (4 days ago), 2020-05-12 18:39:00 -0700
    • Engine revision 6bc433c6b6
    • Dart version 2.8.2

[!] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at C:\Users\[BLAH]\AppData\Local\Android\sdk
    • Platform android-28, build-tools 28.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)
    X Android license status unknown.
      Try re-installing or updating your Android SDK Manager.
      See https://developer.android.com/studio/#downloads or visit visit
      https://flutter.dev/docs/get-started/install/windows#android-setup for detailed instructions.

[√] Android Studio (version 3.6)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.8052
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)

[!] VS Code (version 1.44.2)
    • VS Code at C:\Users\[BLAH]\AppData\Local\Programs\Microsoft VS Code
    X Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[√] Connected device (1 available)
    • AOSP on IA Emulator • emulator-5554 • android-x86 • Android 9 (API 28) (emulator)

! Doctor found issues in 2 categories.


**Changing JAVA_HOME to android studios version of jre and re-running flutter doctor --android-licenses**

[√] Flutter (Channel stable, v1.17.1, on Microsoft Windows [Version 10.0.18363.778], locale en-GB)
    • Flutter version 1.17.1 at P:\src\flutter
    • Framework revision f7a6a7906b (4 days ago), 2020-05-12 18:39:00 -0700
    • Engine revision 6bc433c6b6
    • Dart version 2.8.2


[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at C:\Users\[BLAH]\AppData\Local\Android\sdk
    • Platform android-28, build-tools 28.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)
    • All Android licenses accepted.

[√] Android Studio (version 3.6)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.8052
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)

[!] VS Code (version 1.44.2)
    • VS Code at C:\Users\[BLAH]\AppData\Local\Programs\Microsoft VS Code
    X Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[√] Connected device (1 available)
    • AOSP on IA Emulator • emulator-5554 • android-x86 • Android 9 (API 28) (emulator)

! Doctor found issues in 1 category.

**Comment by AndrewH2O** [comment]
I guess this is more of an issue when using vs code as an editor or at the command line rather than using android studio.

**Comment by jonahwilliams** [comment]
So, it looks like we need to make sure that we need to check JAVA_HOME to make sure it lines up with the SDK? Or override it locally

**Comment by jonahwilliams** [comment]
It looks like we attempt to use the Android studio bundled JRE, but that failed in this case:

https://github.com/flutter/flutter/blob/master/packages/flutter_tools/lib/src/android/android_sdk.dart#L393

**Comment by andy910304** [comment]
Hello @AndrewH2O , i try to change my JAVA_HOME to the path C:\Program Files\Android\Android Studio\jre and not work for me. My folder java is update to JAVA 9 and try JAVA_HOME to C:\Program Files\Java\jdk-9.0.4 and also dont work. Alway i see this error 

`
C:\Users\Romero\AndroidStudioProjects\flutter_hello>**flutter doctor --android-licenses**
A newer version of the Android SDK is required. To update, run:
**C:\Users\Romero\AppData\Local\Android\sdk\tools\bin\sdkmanager --update**

C:\Users\Romero\AndroidStudioProjects\flutter_hello>**C:\Users\Romero\AppData\Local\Android\sdk\tools\bin\sdkmanager --update**
**Error: Could not find or load main class com.android.sdklib.tool.sdkmanager.SdkManagerCli**
`

**Comment by AndrewH2O** [comment]
@andy910304  I was using sdk 28.0.03 and not the very latest version and updated to this using the sdk manager in android studio as I wanted more control. 

In any event if using the cmd line some people have had  luck with adding '--sdkroot'  ./bin/sdkamanager --sdkroot which points to the parent folder of the sdk tooling [see](https://stackoverflow.com/questions/60727326/sdkmanager-error-could-not-find-or-load-main-class-com-android-sdklib-tool-sdk)

**Comment by starksm64** [comment]
On OSX 10.14.6 I was seeing the same issue with the android license status unknown, and running flutter doctor --android-licenses was throwing a java.lang.NoClassDefFoundError: javax/xml/bind/annotation/XmlSchema. Setting JAVA_HOME to a JDK 8 install has this working:

```
Scotts-iMacPro:Flutter starksm$ flutter doctor -v
[✓] Flutter (Channel beta, 1.20.0-7.2.pre, on Mac OS X 10.14.6 18G6020, locale
    en-US)
    • Flutter version 1.20.0-7.2.pre at /Users/starksm/Dev/Flutter/flutter
    • Framework revision a2bde82fbd (7 days ago), 2020-07-18 15:16:35 -0700
    • Engine revision 60b269d898
    • Dart version 2.9.0 (build 2.9.0-21.2.beta)

[!] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/starksm/Library/Android/sdk
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Users/starksm/Library/Application
      Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/193.6626763/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    ✗ Android license status unknown.
      Try re-installing or updating your Android SDK Manager.
      See https://developer.android.com/studio/#downloads or visit
      https://flutter.dev/docs/get-started/install/macos#android-setup for
      detailed instructions.

[!] Xcode - develop for iOS and macOS (Xcode 11.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.0, Build version 11A420a
    ✗ CocoaPods not installed.
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin
        code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To install:
        sudo gem install cocoapods

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Users/starksm/Library/Application
      Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/193.6626763/Android
      Studio.app/Contents
    • Flutter plugin version 47.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[!] VS Code (version 1.46.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    ✗ Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

 
[✓] Connected device (4 available)            
    • Redmi Note 8 Pro (mobile)   • uwdeqwyhjn7lbasg • android-arm64  • Android
      10 (API 29)
    • sdk gphone x86 arm (mobile) • emulator-5554    • android-x86    • Android
      11 (API 30) (emulator)
    • Web Server (web)            • web-server       • web-javascript • Flutter
      Tools
    • Chrome (web)                • chrome           • web-javascript • Google
      Chrome 84.0.4147.89

! Doctor found issues in 3 categories.
Scotts-iMacPro:Flutter starksm$ flutter doctor --android-licenses
Exception in thread "main" java.lang.NoClassDefFoundError: javax/xml/bind/annotation/XmlSchema
	at com.android.repository.api.SchemaModule$SchemaModuleVersion.<init>(SchemaModule.java:156)
	at com.android.repository.api.SchemaModule.<init>(SchemaModule.java:75)
	at com.android.sdklib.repository.AndroidSdkHandler.<clinit>(AndroidSdkHandler.java:81)
	at com.android.sdklib.tool.sdkmanager.SdkManagerCli.main(SdkManagerCli.java:73)
	at com.android.sdklib.tool.sdkmanager.SdkManagerCli.main(SdkManagerCli.java:48)
Caused by: java.lang.ClassNotFoundException: javax.xml.bind.annotation.XmlSchema
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	... 5 more
Scotts-iMacPro:Flutter starksm$ echo $JAVA_HOME
/Library/Java/JavaVirtualMachines/zulu-11.jdk/Contents/Home
Scotts-iMacPro:Flutter starksm$ JAVA_HOME=/Library/Java/JavaVirtualMachines/jdk1.8.0_261.jdk/Contents/Home
Scotts-iMacPro:Flutter starksm$ flutter doctor --android-licenses
Warning: File /Users/starksm/.android/repositories.cfg could not be loaded.     
4 of 7 SDK package licenses not accepted. 100% Computing updates...             
Review licenses that have not been accepted (y/N)? y
...
```

**Comment by David-Jr** [comment]
What worked for me was: 
I had **java**(SE 11) installed and it's variables sat up. It somehow **interfered with flutter!**

     1. Double your java path entry;
So what you'll need to do is just go to your java environment variables and double your path entry. In one of them keep the bin and on the other remove it. Mine: C:\Program Files\Java\jdk-11.0.8\bin C:\Program Files\Java\jdk-11.0.8

     2. flutter doctor --android-licenses
In the command line just run this command **flutter doctor --android-licenses**, accept everything ( by clicking y key followed by enter key). And you should be fine.

I'm certainly too late to answer this one, but anyway, I hope it helps someone. A big thanks to @Derson Mutemba who was the one to save me from this mess.

**Comment by neoacevedo** [comment]
I'm issuing the same but I'm in openSUSE. I don't want to downgrade Java and setting the JAVA_HOME to the Android Studio JRE path didn't work because flutter said me the JAVA_HOME is set to an invalid directory.


My Java version is **java 14.0.2 2020-07-14**

**Comment by ullas-i** [comment]
For Mac user tyy this: 
>```(your android_sdk folder exact path)\tools\bin\sdkmanager --licenses```
   
This worked for me
For Windows user:
  - Install jdk 8 from official site 
  - Add jdk dir to **User Variables** 
 ```
 JAVA_HOME C:\Program Files\Java\jdk1.8.0_281
 ```
  - Run ```flutter doctor``` command from a consol
  - Then```flutter doctor --android-licenses``` and accept all licenses.
  - Run the command ```flutter doctor -v``` to check if the issue was solved.

**Comment by chris-stones** [comment]
I get the same exception in Manjaro Linux.  
setting JAVA_HOME to the Java version bundled with android studio was no help.


```bash
~ >>> flutter doctor -v                                                                                
[✓] Flutter (Channel stable, 2.2.0, on Linux, locale en_GB.UTF-8)
    • Flutter version 2.2.0 at /opt/flutter
    • Framework revision b22742018b (12 days ago), 2021-05-14 19:12:57 -0700
    • Engine revision a9d88a4d18
    • Dart version 2.13.0

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /home/chris/Android/Sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at:
      /home/chris/.local/share/JetBrains/Toolbox/apps/AndroidStudio/ch-0/202.7351085/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+0-b944-P17168821)
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/linux#android-setup for more details.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Android Studio (version 4.2)
    • Android Studio at /home/chris/.local/share/JetBrains/Toolbox/apps/AndroidStudio/ch-0/202.7351085
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+0-b944-P17168821)

[✓] Connected device (1 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 91.0.4472.77
```

```bash
~ >>> JAVA_HOME="/home/chris/.local/share/JetBrains/Toolbox/apps/AndroidStudio/ch-0/202.7351085/jre" flutter doctor --android-licenses      
Exception in thread "main" java.lang.NoClassDefFoundError: javax/xml/bind/annotation/XmlSchema
	at com.android.repository.api.SchemaModule$SchemaModuleVersion.<init>(SchemaModule.java:156)
	at com.android.repository.api.SchemaModule.<init>(SchemaModule.java:75)
	at com.android.sdklib.repository.AndroidSdkHandler.<clinit>(AndroidSdkHandler.java:81)
	at com.android.sdklib.tool.sdkmanager.SdkManagerCli.main(SdkManagerCli.java:73)
	at com.android.sdklib.tool.sdkmanager.SdkManagerCli.main(SdkManagerCli.java:48)
Caused by: java.lang.ClassNotFoundException: javax.xml.bind.annotation.XmlSchema
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	... 5 more
```

I installed java-8, and set it to the system default with the `archlinux-java` tool... But flutter doctor was still picking up the incompatibleversion bundled with Android Studio.  

The workaround for me, was 
```bash
JAVA_HOME="/usr/lib/jvm/java-8-openjdk/jre" flutter doctor --android-licenses
```

**Comment by badushaebrahim** [comment]
Hi, guys i have bee trying to set up getting this error i used jdk 8,12,16, and also pointed it to android/jre location but always the same error any idea 
os 
![Select Command Prompt 14-06-2021 06_00_37 PM](https://user-images.githubusercontent.com/63869474/121939946-35a2f980-cd6b-11eb-9579-9e28a25794c8.png)
![Select Command Prompt 14-06-2021 06_45_36 PM](https://user-images.githubusercontent.com/63869474/121939956-389dea00-cd6b-11eb-9a16-e8c3a313d45d.png)
![Select Command Prompt 14-06-2021 06_46_13 PM](https://user-images.githubusercontent.com/63869474/121939961-39368080-cd6b-11eb-8656-c1edab7bfeee.png)
![Select Command Prompt 14-06-2021 07_43_30 PM](https://user-images.githubusercontent.com/63869474/121939965-3a67ad80-cd6b-11eb-972d-62354a5be346.png)



os: windows 10

**Comment by badushaebrahim** [comment]
tryed with bin in the directory also whithout bin

**Comment by starksm64** [comment]
The doctor script probably does not like the space in the JAVA_HOME directory. Try quoting the path or move the install to a path without the space to test.

**Comment by ullaskunder3** [comment]
> Hi, guys i have bee trying to set up getting this error i used jdk 8,12,16, and also pointed it to android/jre location but always the same error any idea
> os
> ![Select Command Prompt 14-06-2021 06_00_37 PM](https://user-images.githubusercontent.com/63869474/121939946-35a2f980-cd6b-11eb-9579-9e28a25794c8.png)
> ![Select Command Prompt 14-06-2021 06_45_36 PM](https://user-images.githubusercontent.com/63869474/121939956-389dea00-cd6b-11eb-9a16-e8c3a313d45d.png)
> ![Select Command Prompt 14-06-2021 06_46_13 PM](https://user-images.githubusercontent.com/63869474/121939961-39368080-cd6b-11eb-8656-c1edab7bfeee.png)
> ![Select Command Prompt 14-06-2021 07_43_30 PM](https://user-images.githubusercontent.com/63869474/121939965-3a67ad80-cd6b-11eb-972d-62354a5be346.png)
> 
> os: windows 10

JAVA_HOME should point to the folder `JDK` &&  **path** should point to the folder JDK containing `bin` folder 
example: 
![jdkSetup](https://user-images.githubusercontent.com/66258652/122000273-2c964480-cdcc-11eb-9fb8-6dce6cbb21b7.png)

**Comment by badushaebrahim** [comment]
hi, guys  i found a fix  follow this vedio this fix wrk  link("https://www.youtube.com/watch?v=0kF_ljRShDA")

**Comment by tjHong** [comment]
@chris-stones My exception is exactly the same as yours

**Comment by kjxbyz** [comment]
```
错误: 加载主类 com.android.sdklib.tool.sdkmanager.SdkManagerCli 时出现 LinkageError
	java.lang.UnsupportedClassVersionError: com/android/sdklib/tool/sdkmanager/SdkManagerCli has been compiled by a more recent version of the Java Runtime (class file version 61.0), this version of the Java Runtime only recognizes class file versions up to 55.0
Android sdkmanager tool was found, but failed to run
(/Users/ying/Android/sdk/cmdline-tools/latest/bin/sdkmanager): "exited code 1".
Try re-installing or updating your Android SDK,
visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed
instructions.
```
