### ISSUE TITLE
Crash when creating a new application

### ISSUE THREAD

**Issue by alvaroc1** [flutter/flutter#5738]
## Steps to Reproduce

On a Fedora 24 machine, while a Fire table is connected:
$ flutter create boyxing

## Flutter Doctor

It crashes with a similar error.

## Logs and Crash Reports

Flutter crash report; please file at https://github.com/flutter/flutter/issues.

## command

flutter create boyxing

## exception

FormatException: Bad UTF-8 encoding 0x8a

```
dart:io                                                           Process.runSync
package:flutter_tools/src/android/android_device.dart 65          AndroidDevice._getProperty
package:flutter_tools/src/android/android_device.dart 91          AndroidDevice.platform
package:flutter_tools/src/device.dart 252                         Device.descriptions.<fn>
dart:_internal                                                    ListIterable.toList
package:flutter_tools/src/doctor.dart 311                         DeviceValidator.validate.<async>
dart:async                                                        _SyncCompleter.complete
package:flutter_tools/src/device.dart 70                          DeviceManager.getAllConnectedDevices.<async>
===== asynchronous gap ===========================
dart:async                                                        _Completer.completeError
package:flutter_tools/src/doctor.dart 315                         DeviceValidator.validate.<async>
dart:async                                                        _SyncCompleter.complete
package:flutter_tools/src/device.dart 70                          DeviceManager.getAllConnectedDevices.<async>
===== asynchronous gap ===========================
dart:async                                                        _asyncThenWrapperHelper
package:flutter_tools/src/doctor.dart                             DeviceValidator.validate
package:flutter_tools/src/doctor.dart 75                          Doctor.summaryText.summaryText_async_body>
dart:async                                                        _SyncCompleter.complete
package:flutter_tools/src/doctor.dart 265                         AtomValidator.validate.<async>
===== asynchronous gap ===========================
dart:async                                                        _asyncThenWrapperHelper
package:flutter_tools/src/doctor.dart                             Doctor.summaryText
package:flutter_tools/src/doctor.dart 66                          Doctor.summary.<async>
===== asynchronous gap ===========================
dart:async                                                        Future.Future.microtask
package:flutter_tools/src/doctor.dart                             Doctor.summary
package:flutter_tools/src/commands/create.dart 120                CreateCommand.runInProject.<async>
dart:async                                                        _SyncCompleter.complete
package:flutter_tools/src/dart/pub.dart 60                        pubGet.<async>
dart:async                                                        _SyncCompleter.complete
package:flutter_tools/src/base/process.dart 82                    runCommandAndStreamOutput.<async>
===== asynchronous gap ===========================
dart:async                                                        _asyncThenWrapperHelper
package:flutter_tools/src/commands/create.dart                    CreateCommand.runInProject
package:flutter_tools/src/runner/flutter_command.dart 192         FlutterCommand._run.<async>
dart:async                                                        _SyncCompleter.complete
package:flutter_tools/src/cache.dart 184                          Cache.updateAll.<async>
===== asynchronous gap ===========================
dart:async                                                        _asyncThenWrapperHelper
package:flutter_tools/src/runner/flutter_command.dart             FlutterCommand._run
package:flutter_tools/src/runner/flutter_command.dart 116         FlutterCommand.run
package:args/command_runner.dart 177                              CommandRunner.runCommand.<fn>
dart:async                                                        Future.Future.sync
package:args/command_runner.dart 130                              CommandRunner.runCommand
package:flutter_tools/src/runner/flutter_command_runner.dart 177  FlutterCommandRunner.runCommand.<async>
dart:async                                                        _SyncCompleter.complete
package:flutter_tools/src/cache.dart 71                           Cache.lock.<async>
===== asynchronous gap ===========================
dart:async                                                        _asyncThenWrapperHelper
package:flutter_tools/src/runner/flutter_command_runner.dart      FlutterCommandRunner.runCommand
package:args/command_runner.dart 104                              CommandRunner.run.<fn>
dart:async                                                        Future.Future.sync
package:args/command_runner.dart 104                              CommandRunner.run
package:flutter_tools/src/runner/flutter_command_runner.dart 123  FlutterCommandRunner.run
package:flutter_tools/executable.dart 94                          main.<async>.<fn>.<async>
===== asynchronous gap ===========================
package:stack_trace                                               Chain.capture
package:flutter_tools/executable.dart 88                          main.<async>
```

## flutter doctor

```
[✓] Flutter (on Linux, channel alpha)
    • Flutter at /home/alvaro/flutter-workspace/flutter
    • Framework revision a69c11f349 (2 days ago), 2016-09-02 17:01:11
    • Engine revision dcb026188a
    • Tools Dart version 1.19.0-dev.5.0

[✓] Android toolchain - develop for Android devices (Android SDK 24.0.1)
    • Android SDK at /home/alvaro/Android/Sdk
    • Platform android-24, build-tools 24.0.1
    • OpenJDK Runtime Environment (build 1.8.0_102-b14)

[✓] Atom - a lightweight development environment for Flutter
    • flutter plugin version 0.2.4
    • dartlang plugin version 0.6.35

[✓] Connected devices
    • KFASWI • 00DF06065183073J • android-arm
```

**Comment by eseidelGoogle** [comment]
https://github.com/flutter/flutter/blob/master/packages/flutter_tools/lib/src/android/android_device.dart#L91 is the crashing call.  https://github.com/flutter/flutter/blob/master/packages/flutter_tools/lib/src/android/android_device.dart#L65 is presumably not encoding safe.

@alvaroc1  would you be willing to either attach (via gist.github.com) or email the output of `adb shell getprop ro.product.cpu.abi`?  I suspect it has some funny encoded characters which we aren't handling correctly.  It's possible (probable) that we shouldn't even be trying to decode the stream just treating it as raw bytes.  @devoncarew @danrubel

**Comment by eseidelGoogle** [comment]
Actually, that doesn't make any sense.  Since `flutter doctor` is including the output of `adb shell getprop ro.product.cpu.abi` above (as you can see by the `android-arm`). I wonder if this was some sort of fluke?  The cable being lose or something causing some strange disconnect?  Is this repeatable?

Interesting that this does appear to be doctor code running in the stack, while we're doing a cache update.  Probably several things going wrong here.  For one we probably shouldn't crash this way when trying to run doctor during an update (which presumably only happens during an error?)

**Comment by alvaroc1** [comment]
@eseidelGoogle Cable/connection issues could certainly be the case, I've had some issues with at least one of my devices. But I have gotten the same problem with both an HTC M9 and a Fire tablet. I will try more devices/cables when I get a chance.

**Comment by devoncarew** [comment]
It looks like the default for Process.runSync is to assume that stdout is in utf8 format, which I don't think adb shell getprop has any guarantee of. Also, I suspect we should be a bit more defensive about exceptions from Process.runSync in this case.

The async stack traces above seem reasonable, if a bit misleading about what's going on. update isn't calling doctor in this case, but somebody had done an await update, and then called doctor.

**Comment by alvaroc1** [comment]
I tried using a simplified script to try to diagnose the issue:
```dart
import 'dart:io';

void main () {

  final RegExp _kDeviceRegex = new RegExp(r'^(\S+)\s+(\S+)(.*)');

  var res = Process.runSync('adb', ['devices', '-l']);
  var output = res.stdout.trim().split('\n');

  for (String line in output) {
    if (line.startsWith('List of devices'))
      continue;

    if (_kDeviceRegex.hasMatch(line)) {
      Match match = _kDeviceRegex.firstMatch(line);

      String deviceID = match[1];
      String deviceState = match[2];
      String rest = match[3];

      print(Process.runSync('adb', ['-s', deviceID, 'shell', 'getprop', 'ro.product.cpu.abi']).stdout);
    }
  }
}
```
This script seems to work fine:
```bash
[alvaro@localhost bin]$ ./dart s.dart
armeabi-v7a

```

What could be different?

**Comment by devoncarew** [comment]
What we're running is `Process.runSync('adb', ['shell', 'getprop'])` - i.e. listing all the properties. Can you try that (perhaps as is, and with the `stdoutEncoding: ASCII` param)?

**Comment by alvaroc1** [comment]
@devoncarew Will try that. In the mean time, I tried calling "flutter run" using your PR branch and got this:
```bash
...
Error retrieving device properties for ro.product.cpu.abi: FormatException: Invalid value in input: 138
Building APK in debug mode (android-arm)...              
Warning: signing the APK using the debug keystore.
Built build/app.apk (14.9MB).
Unexpected failure from adb: Invalid argument(s): The source must not be null
```

**Comment by alvaroc1** [comment]
@devoncarew Ah ok, with just 'getprop' my script does have the same issue:
```bash
Unhandled exception:
FormatException: Bad UTF-8 encoding 0x8a
#0      _Utf8Decoder.convert (dart:convert/utf.dart:558)
#1      Utf8Decoder.convert (dart:convert/utf.dart:349)
#2      SystemEncoding.decode (dart:io/string_transformer.dart:26)
#3      _ProcessImpl._runAndWait.getOutput (dart:io-patch/process_patch.dart:465)
#4      _ProcessImpl._runAndWait (dart:io-patch/process_patch.dart:473)
#5      _runNonInteractiveProcessSync (dart:io-patch/process_patch.dart:603)
#6      Process.runSync (dart:io-patch/process_patch.dart:64)
#7      main (file:///home/alvaro/flutter-workspace/flutter/bin/cache/dart-sdk/bin/s.dart:21:21)
#8      _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:261)
#9      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:148)
```

With the ASCII parameter:
```bash
Unhandled exception:
FormatException: Invalid value in input: 138
#0      _UnicodeSubsetDecoder.convert (dart:convert/ascii.dart:197)
#1      AsciiCodec.decode (dart:convert/ascii.dart:59)
#2      _ProcessImpl._runAndWait.getOutput (dart:io-patch/process_patch.dart:465)
#3      _ProcessImpl._runAndWait (dart:io-patch/process_patch.dart:473)
#4      _runNonInteractiveProcessSync (dart:io-patch/process_patch.dart:603)
#5      Process.runSync (dart:io-patch/process_patch.dart:64)
#6      main (file:///home/alvaro/flutter-workspace/flutter/bin/cache/dart-sdk/bin/s.dart:22:21)
#7      _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:261)
#8      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:148)
```

**Comment by alvaroc1** [comment]
@devoncarew When I run this manually: `adb shell getprops`, this looks suspicious:
```bash
...
[persist.radio.combo.patchinfo]: [20150923135215aALPS��]
...
```

**Comment by alvaroc1** [comment]
In case it helps:
```bash
[alvaro@localhost flutter]$ adb shell getprop persist.radio.combo.patchinfo | hexdump -C
00000000  32 30 31 35 30 39 32 33  31 33 35 32 31 35 61 41  |20150923135215aA|
00000010  4c 50 53 8a 10 8a 10 0d  0a                       |LPS......|
00000019
```
