### ISSUE TITLE
`flutter build apk` always fails with error: Could not determine the dependencies of task ':app:processReleaseResources'

### ISSUE THREAD

**Issue by fondoger** [flutter/flutter#57384]
## Description

Everything is fine until I upgrade my flutter sdk to latest stable version `v1.17.1` yesterday.
Now I can still run my app in debug mode or run in release version, but I just can't assemble any release apk via `flutter build apk` command.

Below is the main error message:
```
FAILURE: Build failed with an exception.                                
                                                                        
* What went wrong:                                                      
Could not determine the dependencies of task ':app:compileReleaseJavaWithJavac'.
> Failed to notify dependency resolution listener.                      
   > sun.security.internal.spec.TlsMasterSecretParameterSpec.getExtendedMasterSecretSessionHash()[B
```

## Weird thing 

I tried figure out which step is wrong, using `flutter build apk -v` command, here is output:
```
// many success steps are omitted, below is the wrong part:
[  +32 ms] executing: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java -version
[ +117 ms] Exit code 0 from: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java -version
[        ] openjdk version "1.8.0_212-release"
           OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
           OpenJDK 64-Bit Server VM (build 25.212-b4-5784211, mixed mode)
[   +3 ms] executing: [/Users/yuanqin/Desktop/projects/vmgirls/android/] /Users/yuanqin/Desktop/projects/vmgirls/android/gradlew -Pverbose=true -Ptarget-platform=android-arm,android-arm64,android-x64
-Ptarget=lib/main.dart -Ptrack-widget-creation=true -Pshrink=true assembleRelease
[+2283 ms] FAILURE: Build failed with an exception.
[   +2 ms] * What went wrong:
[        ] Could not determine the dependencies of task ':app:compileReleaseJavaWithJavac'.
[        ] > Failed to notify dependency resolution listener.
[        ]    > sun.security.internal.spec.TlsMasterSecretParameterSpec.getExtendedMasterSecretSessionHash()[B
[        ] * Try:
[        ] Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
[        ] * Get more help at https://help.gradle.org
[        ] BUILD FAILED in 2s
[ +374 ms] Running Gradle task 'assembleRelease'... (completed in 2.9s)
[   +6 ms] "flutter apk" took 4,760ms.
Gradle task assembleRelease failed with exit code 1

#0      throwToolExit (package:flutter_tools/src/base/common.dart:14:3)
#1      buildGradleApp (package:flutter_tools/src/android/gradle.dart:407:7)
#2      _rootRunUnary (dart:async/zone.dart:1192:38)
#3      _CustomZone.runUnary (dart:async/zone.dart:1085:19)
#4      _FutureListener.handleValue (dart:async/future_impl.dart:141:18)
#5      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:682:45)
#6      Future._propagateToListeners (dart:async/future_impl.dart:711:32)
#7      Future._completeWithValue (dart:async/future_impl.dart:526:5)
#8      _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:36:15)
#9      _completeOnAsyncReturn (dart:async-patch/async_patch.dart:298:13)
#10     _DefaultProcessUtils.stream (package:flutter_tools/src/base/process.dart)
#11     _rootRunUnary (dart:async/zone.dart:1192:38)
#12     _CustomZone.runUnary (dart:async/zone.dart:1085:19)
#13     _FutureListener.handleValue (dart:async/future_impl.dart:141:18)
#14     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:682:45)
#15     Future._propagateToListeners (dart:async/future_impl.dart:711:32)
#16     Future._completeWithValue (dart:async/future_impl.dart:526:5)
#17     Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:556:7)
#18     _rootRun (dart:async/zone.dart:1184:13)
#19     _CustomZone.run (dart:async/zone.dart:1077:19)
#20     _CustomZone.runGuarded (dart:async/zone.dart:979:7)
#21     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1019:23)
#22     _microtaskLoop (dart:async/schedule_microtask.dart:43:21)
#23     _startMicrotaskLoop (dart:async/schedule_microtask.dart:52:5)
#24     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
#25     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:169:5)
```

This is the command that gets wrong in ablow output:
```
[   +3 ms] executing: [/Users/yuanqin/Desktop/projects/vmgirls/android/] /Users/yuanqin/Desktop/projects/vmgirls/android/gradlew -Pverbose=true -Ptarget-platform=android-arm,android-arm64,android-x64
-Ptarget=lib/main.dart -Ptrack-widget-creation=true -Pshrink=true assembleRelease
```

**However**, when I enter `<project>/android` folder, and manually run  the command `.gradlew -Pverbose=true -Ptarget-platform=android-arm,android-arm64,android-x64
-Ptarget=lib/main.dart -Ptrack-widget-creation=true -Pshrink=true assembleRelease`, **weird things happened**, I successfully generated apk **without any errors**:

<details><summary>CLICK ME to see logs</summary>

```
> Task :app:compileFlutterBuildRelease
[  +28 ms] executing: [/Users/yuanqin/flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[  +50 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[        ] f7a6a7906be96d2288f5d63a5a54c515a6e987fe
[        ] executing: [/Users/yuanqin/flutter/] git tag --contains HEAD
[ +301 ms] Exit code 0 from: git tag --contains HEAD
[   +1 ms] 1.17.1
[  +14 ms] executing: [/Users/yuanqin/flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[  +15 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/stable
[        ] executing: [/Users/yuanqin/flutter/] git ls-remote --get-url origin
[  +12 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[  +89 ms] executing: [/Users/yuanqin/flutter/] git rev-parse --abbrev-ref HEAD
[  +14 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[   +1 ms] stable
[   +7 ms] executing: sw_vers -productName
[  +18 ms] Exit code 0 from: sw_vers -productName
[        ] Mac OS X
[        ] executing: sw_vers -productVersion
[  +20 ms] Exit code 0 from: sw_vers -productVersion
[        ] 10.15.4
[        ] executing: sw_vers -buildVersion
[  +16 ms] Exit code 0 from: sw_vers -buildVersion
[        ] 19E287
[  +31 ms] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +3 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +11 ms] Artifact Instance of 'MaterialFonts' is not required, skipping update.
[        ] Artifact Instance of 'GradleWrapper' is not required, skipping update.
[        ] Artifact Instance of 'AndroidMavenArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[        ] Artifact Instance of 'FlutterSdk' is not required, skipping update.
[        ] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FontSubsetArtifacts' is not required, skipping update.
[  +86 ms] Initializing file store
[  +14 ms] Done initializing file store
[+1710 ms] Skipping target: kernel_snapshot
[ +221 ms] aot_android_asset_bundle: Starting due to {InvalidatedReason.outputMissing}
[ +287 ms] aot_android_asset_bundle: Complete
[ +404 ms] Skipping target: android_aot_release_android-arm
[   +1 ms] android_aot_bundle_release_android-arm: Starting due to {InvalidatedReason.outputMissing}
[   +7 ms] android_aot_bundle_release_android-arm: Complete
[ +123 ms] Skipping target: android_aot_release_android-arm64
[        ] android_aot_bundle_release_android-arm64: Starting due to {InvalidatedReason.outputMissing}
[   +8 ms] android_aot_bundle_release_android-arm64: Complete
[ +105 ms] android_aot_release_android-x64: Starting due to {InvalidatedReason.inputChanged}
[   +5 ms] executing: /Users/yuanqin/flutter/bin/cache/artifacts/engine/android-x64-release/darwin-x64/gen_snapshot --deterministic --snapshot_kind=app-aot-elf --elf=/Users/yuanqin/Desktop/projects/vmgirls/.dart_tool/flutter_build/93bb596af109e3e0b3f18972f8d4668a/x86_64/app.so --strip --no-causal-async-stacks --lazy-async-stacks /Users/yuanqin/Desktop/projects/vmgirls/.dart_tool/flutter_build/93bb596af109e3e0b3f18972f8d4668a/app.dill
[+10191 ms] android_aot_release_android-x64: Complete
[  +93 ms] android_aot_bundle_release_android-x64: Starting due to {InvalidatedReason.inputChanged}
[   +7 ms] android_aot_bundle_release_android-x64: Complete
[  +72 ms] Skipping target: _composite
[        ] Persisting file store
[  +11 ms] Done persisting file store
[   +9 ms] build succeeded.
[  +14 ms] "flutter assemble" took 13,511ms.

> Task :url_launcher:compileReleaseJavaWithJavac
Note: /Users/yuanqin/.pub-cache/hosted/pub.flutter-io.cn/url_launcher-5.4.7/android/src/main/java/io/flutter/plugins/urllauncher/WebViewActivity.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.

> Task :app:transformClassesAndDexWithShrinkResForRelease
Removed unused resources: Binary resource data reduced from 78KB to 70KB: Removed 9%

> Task :app:stripReleaseDebugSymbols
Compatible side by side NDK version was not found.
Unable to strip library '/Users/yuanqin/Desktop/projects/vmgirls/build/app/intermediates/merged_native_libs/release/out/lib/armeabi-v7a/libflutter.so' due to missing strip tool for ABI 'ARMEABI_V7A'. Packaging it as is.
Unable to strip library '/Users/yuanqin/Desktop/projects/vmgirls/build/app/intermediates/merged_native_libs/release/out/lib/armeabi-v7a/libapp.so' due to missing strip tool for ABI 'ARMEABI_V7A'. Packaging it as is.
Unable to strip library '/Users/yuanqin/Desktop/projects/vmgirls/build/app/intermediates/merged_native_libs/release/out/lib/arm64-v8a/libflutter.so' due to missing strip tool for ABI 'ARM64_V8A'. Packaging it as is.
Unable to strip library '/Users/yuanqin/Desktop/projects/vmgirls/build/app/intermediates/merged_native_libs/release/out/lib/arm64-v8a/libapp.so' due to missing strip tool for ABI 'ARM64_V8A'. Packaging it as is.
Unable to strip library '/Users/yuanqin/Desktop/projects/vmgirls/build/app/intermediates/merged_native_libs/release/out/lib/x86_64/libflutter.so' due to missing strip tool for ABI 'X86_64'. Packaging it as is.
Unable to strip library '/Users/yuanqin/Desktop/projects/vmgirls/build/app/intermediates/merged_native_libs/release/out/lib/x86_64/libapp.so' due to missing strip tool for ABI 'X86_64'. Packaging it as is.

BUILD SUCCESSFUL in 57s
349 actionable tasks: 314 executed, 35 up-to-date
```
</details>

This is very strange, isn't it ?

## Possible solutions I have tried:
1. fully delete flutter sdk and install latest stable version, not working.
2. create anoter new flutter project, still can't build apk.
3. using another proxies(since I'm in China), not working.

## Steps to Reproduce

```
flutter create example
cd example
flutter build apk
```

## Other information

**Output of `flutter doctor -v`:**
<details><summary>CLICK ME</summary>
<p>

```
[✓] Flutter (Channel stable, v1.17.1, on Mac OS X 10.15.4 19E287, locale en-CN)
    • Flutter version 1.17.1 at /Users/yuanqin/flutter
    • Framework revision f7a6a7906b (4 days ago), 2020-05-12 18:39:00 -0700
    • Engine revision 6bc433c6b6
    • Dart version 2.8.2

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.1)
    • Android SDK at /Users/yuanqin/Library/Android/sdk
    • Platform android-29, build-tools 29.0.1
    • ANDROID_HOME = /Users/yuanqin/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[!] Xcode - develop for iOS and macOS (Xcode 11.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.4.1, Build version 11E503a
    ✗ CocoaPods installed but not working.
        You appear to have CocoaPods installed but it is not working.
        This can happen if the version of Ruby that CocoaPods was installed with is different from the one being used to invoke it.
        This can usually be fixed by re-installing CocoaPods. For more info, see https://github.com/flutter/flutter/issues/14293.
      To re-install CocoaPods, run:
        sudo gem install cocoapods

[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.8052
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)

[!] IntelliJ IDEA Community Edition (version 2019.3)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.dev/intellij-setup/#installing-the-plugins

[!] VS Code (version 1.45.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    ✗ Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

 
[✓] Connected device (1 available)            
    • Redmi Note 7 Pro • ec1dca5c • android-arm64 • Android 10 (API 29)

! Doctor found issues in 3 categories.
```

</p>

</details>

## At last

I don't want to bother you guys, but I have spent hours on this problem, and still can't find a solution.

Sincerely thank you for help.

**Comment by fondoger** [comment]
Problem solved after rebooting my computer.
