### ISSUE TITLE
crash when run 'flutter run' in hello_services app

### ISSUE THREAD

**Issue by ZhangQinglian** [flutter/flutter#5739]
## Steps to Reproduce

Crash when run 'flutter run' in hello_services app.
## Flutter Doctor

```
ScottdeMacBook-Pro:hello_services scott$ flutter doctor
[✓] Flutter (on Mac OS, channel master)
    • Flutter at /Users/scott/dart/flutter
    • Framework revision a69c11f349 (2 days ago), 2016-09-02 17:01:11
    • Engine revision dcb026188a
    • Tools Dart version 1.19.0-dev.5.0

[✓] Android toolchain - develop for Android devices (Android SDK 24.0.2)
    • Android SDK at /Users/scott/soft/sdk
    • Platform android-24, build-tools 24.0.2
    • Java(TM) SE Runtime Environment (build 1.8.0_92-b14)

[✓] iOS toolchain - develop for iOS devices (Xcode 7.3.1)
    • XCode at /Applications/Xcode.app/Contents/Developer
    • Xcode 7.3.1, Build version 7D1014

[✓] Atom - a lightweight development environment for Flutter
    • flutter plugin version 0.2.4
    • dartlang plugin version 0.6.35

[✓] Connected devices
    • Nexus 6 • ZX1G227KCN • android-arm
```

## Logs and Crash Reports

```
W/System.err: java.lang.NullPointerException: Attempt to read from field 'java.lang.String com.tencent.assistant.protocol.jce.AppSimpleDetail.e' on a null object reference
W/System.err:   at com.tencent.assistant.module.a.b(ProGuard:548)
W/System.err:   at com.tencent.assistant.module.a.a(ProGuard:537)
W/System.err:   at com.tencent.pangu.manager.cl.onGetAppInfoSuccess(ProGuard:312)
W/System.err:   at com.tencent.assistant.module.ar.a(ProGuard:118)
W/System.err:   at com.tencent.assistant.module.ar.call(ProGuard:113)
W/System.err:   at com.tencent.assistant.module.callback.CallbackHelper.broadcast(ProGuard:102)
W/System.err:   at com.tencent.assistant.module.BaseEngine.notifyDataChanged(ProGuard:66)
W/System.err:   at com.tencent.assistant.module.d.run(ProGuard:41)
W/System.err:   at android.os.Handler.handleCallback(Handler.java:751)
W/System.err:   at android.os.Handler.dispatchMessage(Handler.java:95)
W/System.err:   at android.os.Looper.loop(Looper.java:154)
W/System.err:   at android.app.ActivityThread.main(ActivityThread.java:6077)
W/System.err:   at java.lang.reflect.Method.invoke(Native Method)
W/System.err:   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:865)
W/System.err:   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755)
W/System.err: java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.auchanasia-1/base.apk"],nativeLibraryDirectories=[/data/app/com.auchanasia-1/lib/arm, /system/fake-libs, /data/app/com.auchanasia-1/base.apk!/lib/armeabi-v7a, /system/lib, /vendor/lib]]] couldn't find "libjpush215.so"
W/System.err:   at java.lang.Runtime.loadLibrary0(Runtime.java:972)
W/System.err:   at java.lang.System.loadLibrary(System.java:1530)
W/System.err:   at cn.jpush.android.service.PushProtocol.<clinit>(Unknown Source)
W/System.err:   at cn.jpush.android.service.PushProtocol.GetSdkVersion(Native Method)
W/System.err:   at cn.jpush.android.e.a(Unknown Source)
W/System.err:   at cn.jpush.android.e.a(Unknown Source)
W/System.err:   at cn.jpush.android.service.PushReceiver.onReceive(Unknown Source)
W/System.err:   at android.app.ActivityThread.handleReceiver(ActivityThread.java:3011)
W/System.err:   at android.app.ActivityThread.-wrap18(ActivityThread.java)
W/System.err:   at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1544)
W/System.err:   at android.os.Handler.dispatchMessage(Handler.java:102)
W/System.err:   at android.os.Looper.loop(Looper.java:154)
W/System.err:   at android.app.ActivityThread.main(ActivityThread.java:6077)
W/System.err:   at java.lang.reflect.Method.invoke(Native Method)
W/System.err:   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:865)
W/System.err:   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755)
W/System.err: java.lang.UnsatisfiedLinkError: No implementation found for int cn.jpush.android.service.PushProtocol.GetSdkVersion() (tried Java_cn_jpush_android_service_PushProtocol_GetSdkVersion and Java_cn_jpush_android_service_PushProtocol_GetSdkVersion__)
W/System.err:   at cn.jpush.android.service.PushProtocol.GetSdkVersion(Native Method)
W/System.err:   at cn.jpush.android.e.a(Unknown Source)
W/System.err:   at cn.jpush.android.e.a(Unknown Source)
W/System.err:   at cn.jpush.android.service.PushReceiver.onReceive(Unknown Source)
W/System.err:   at android.app.ActivityThread.handleReceiver(ActivityThread.java:3011)
W/System.err:   at android.app.ActivityThread.-wrap18(ActivityThread.java)
W/System.err:   at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1544)
W/System.err:   at android.os.Handler.dispatchMessage(Handler.java:102)
W/System.err:   at android.os.Looper.loop(Looper.java:154)
W/System.err:   at android.app.ActivityThread.main(ActivityThread.java:6077)
W/System.err:   at java.lang.reflect.Method.invoke(Native Method)
W/System.err:   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:865)
W/System.err:   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755)
W/System.err: java.lang.UnsatisfiedLinkError: No implementation found for int cn.jpush.android.service.PushProtocol.GetSdkVersion() (tried Java_cn_jpush_android_service_PushProtocol_GetSdkVersion and Java_cn_jpush_android_service_PushProtocol_GetSdkVersion__)
W/System.err:   at cn.jpush.android.service.PushProtocol.GetSdkVersion(Native Method)
W/System.err:   at cn.jpush.android.e.a(Unknown Source)
W/System.err:   at cn.jpush.android.e.a(Unknown Source)
W/System.err:   at cn.jpush.android.service.PushReceiver.onReceive(Unknown Source)
W/System.err:   at android.app.ActivityThread.handleReceiver(ActivityThread.java:3011)
W/System.err:   at android.app.ActivityThread.-wrap18(ActivityThread.java)
W/System.err:   at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1544)
W/System.err:   at android.os.Handler.dispatchMessage(Handler.java:102)
W/System.err:   at android.os.Looper.loop(Looper.java:154)
W/System.err:   at android.app.ActivityThread.main(ActivityThread.java:6077)
W/System.err:   at java.lang.reflect.Method.invoke(Native Method)
W/System.err:   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:865)
W/System.err:   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755)
E/flutter : [ERROR:../../lib/tonic/logging/dart_error.cc(16)] Unhandled exception:
E/flutter : No top-level getter 'main' declared.
E/flutter :
E/flutter : NoSuchMethodError: method not found: 'main'
E/flutter : Receiver: top-level
E/flutter : Arguments: [...]
E/flutter : #0      NoSuchMethodError._throwNew (dart:core-patch/errors_patch.dart:184)
E/flutter : #1      _getMainClosure (file:///b/build/slave/Linux_Engine/build/src/flutter/lib/ui/natives.dart:39)
W/ActivityManager: Force removing ActivityRecord{b215a0d u0 com.example.flutter/.ExampleActivity t847}: app died, no saved state
```

> For more information about diagnosing and reporting Flutter bugs, please see [https://flutter.io/bug-reports/](https://flutter.io/bug-reports/).

**Comment by eseidelGoogle** [comment]
There are a bunch of errors at the top which are unrelated to flutter.  The last bit:
```
E/flutter : [ERROR:../../lib/tonic/logging/dart_error.cc(16)] Unhandled exception:
E/flutter : No top-level getter 'main' declared.
E/flutter :
E/flutter : NoSuchMethodError: method not found: 'main'
E/flutter : Receiver: top-level
E/flutter : Arguments: [...]
E/flutter : #0 NoSuchMethodError._throwNew (dart:core-patch/errors_patch.dart:184)
E/flutter : #1 _getMainClosure (file:///b/build/slave/Linux_Engine/build/src/flutter/lib/ui/natives.dart:39)
W/ActivityManager: Force removing ActivityRecord{b215a0d u0 com.example.flutter/.ExampleActivity t847}: app died, no saved state
```
Is definitely flutter, and suggests that it can't find the 'main' function in your main.dart file.

Are you running hello_services directly without modification?  CC @jason-simmons @devoncarew

**Comment by ZhangQinglian** [comment]
Yeah,without any modification.

**Comment by lejard-h** [comment]
Did you try in release mode ?
I have my own implementation of a Location Service, it works in release mode, but I have this error in debug mode.

Probably related to this
https://github.com/flutter/flutter/issues/4624

**Comment by ZhangQinglian** [comment]
It is ok now with debug or release mode but i just clean the workspace and update the project.?

???? iPhone

? 2016?10?27????8:26?Lejard Hadrien <notifications@github.com<mailto:notifications@github.com>> ???


Did you try in release mode ?
I have my own implementation of a Location Service, it works in release mode, but I have this error in debug mode.

Probably related to this
#4624<https://github.com/flutter/flutter/issues/4624>

-

**Comment by lejard-h** [comment]
Okay it works for me after I cleaned the workspace,
thanks.

**Comment by eseidelGoogle** [comment]
We've recently done a bunch of work to improve hello_services (and have a bunch more in progress).  Speculatively closing.  Please feel encouraged to re-open if you're still having trouble!
