### ISSUE TITLE
Flutter Upgrade Issue

### ISSUE THREAD

**Issue by OngSX** [flutter/flutter#57456]
I had my flutter upgraded just now and it shows an error message and sent a crash report to me.

Below is the crash report:
[flutter_01.log](https://github.com/flutter/flutter/files/4641549/flutter_01.log)

## command

flutter --no-color --no-version-check precache

## exception

FileSystemException: FileSystemException: Deletion failed, path = 'C:\Users\Asus.DESKTOP-H66LVKV\AppData\Local\Temp\flutter_gradle_wrapper.12044031-98a5-11ea-9aaf-6045cb1e9df3' (OS Error: The system cannot find the file specified.
, errno = 2)

```
#0      _Directory._deleteSync (dart:io/directory_impl.dart:208:7)
#1      FileSystemEntity.deleteSync (dart:io/file_system_entity.dart:460:47)
#2      ForwardingFileSystemEntity.deleteSync (package:file/src/forwarding/forwarding_file_system_entity.dart:72:16)
#3      AndroidMavenArtifacts.update (package:flutter_tools/src/cache.dart:1010:15)
#4      _rootRunUnary (dart:async/zone.dart:1192:38)
#5      _CustomZone.runUnary (dart:async/zone.dart:1085:19)
#6      _FutureListener.handleValue (dart:async/future_impl.dart:141:18)
#7      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:682:45)
#8      Future._propagateToListeners (dart:async/future_impl.dart:711:32)
#9      Future._completeWithValue (dart:async/future_impl.dart:526:5)
#10     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:36:15)
#11     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:298:13)
#12     _DefaultProcessUtils.run (package:flutter_tools/src/base/process.dart)
#13     _rootRunUnary (dart:async/zone.dart:1192:38)
#14     _CustomZone.runUnary (dart:async/zone.dart:1085:19)
#15     _FutureListener.handleValue (dart:async/future_impl.dart:141:18)
#16     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:682:45)
#17     Future._propagateToListeners (dart:async/future_impl.dart:711:32)
#18     Future._completeWithValue (dart:async/future_impl.dart:526:5)
#19     Future.wait.<anonymous closure> (dart:async/future.dart:402:22)
#20     _rootRunUnary (dart:async/zone.dart:1192:38)
#21     _CustomZone.runUnary (dart:async/zone.dart:1085:19)
#22     _FutureListener.handleValue (dart:async/future_impl.dart:141:18)
#23     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:682:45)
#24     Future._propagateToListeners (dart:async/future_impl.dart:711:32)
#25     Future._completeWithValue (dart:async/future_impl.dart:526:5)
#26     Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:556:7)
#27     _rootRun (dart:async/zone.dart:1184:13)
#28     _CustomZone.run (dart:async/zone.dart:1077:19)
#29     _CustomZone.runGuarded (dart:async/zone.dart:979:7)
#30     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1019:23)
#31     _microtaskLoop (dart:async/schedule_microtask.dart:43:21)
#32     _startMicrotaskLoop (dart:async/schedule_microtask.dart:52:5)
#33     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
#34     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:169:5)
```

## flutter doctor

```
[✓] Flutter (Channel stable, v1.17.1, on Microsoft Windows [Version 10.0.18362.836], locale en-US)
    • Flutter version 1.17.1 at D:\Installed\flutter
    • Framework revision f7a6a7906b (5 days ago), 2020-05-12 18:39:00 -0700
    • Engine revision 6bc433c6b6
    • Dart version 2.8.2

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at D:\Installed\AndroidStudioSDK
    • Platform android-29, build-tools 29.0.3
    • Java binary at: D:\Installed\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)
    • All Android licenses accepted.

[✓] Android Studio (version 3.5)
    • Android Studio at D:\Installed\Android Studio
    • Flutter plugin version 44.0.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)

[✓] Connected device (1 available)
    • AOSP on IA Emulator • emulator-5554 • android-x86 • Android 9 (API 28) (emulator)

• No issues found!
```

How to solve it?

**Comment by Kumar2106** [comment]
is flutter run command  working?

**Comment by OngSX** [comment]
yes

**Comment by Kumar2106** [comment]
Then there is nothing to worry about.

**Comment by OngSX** [comment]
alright, thanks

**Comment by Kumar2106** [comment]
sometimes crash happens during execution of  program. your welcome buddy.
