### ISSUE TITLE
Setting MouseRegion's `opaque` to `true` has no apparent effect

### ISSUE THREAD

**Issue by evilBird** [flutter/flutter#57525]
## Steps to Reproduce

1. Run the minimal test at https://gist.github.com/evilBird/22113d88cb59bfa4344a97a973051eff.
 (also attached as dart file)
**Expected results:** 
The test should pass - hover gestures should be detected by the visually front-most MouseRegion, but not by the visually back-most MouseRegion
**Actual results:** 
The test fails - hover gestures are detected by both the visually front-most MouseRegion, and by the visually back-most MouseRegion
<details>
  <summary>Logs</summary>

```
Warning: You should set `SILENT_OBSERVATORY` to true when debugging the VM as it will output the observatory URL by default.
This breaks the various reporter contracts.
To set the value define `DART_VM_OPTIONS=-DSILENT_OBSERVATORY=true`.
══╡ EXCEPTION CAUGHT BY FLUTTER TEST FRAMEWORK ╞════════════════════════════════════════════════════
The following TestFailure object was thrown running a test:
  Expected: false
  Actual: <true>

When the exception was thrown, this was the stack:
#4      main.<anonymous closure> (file:///x/test/widgets/mouse_region_bug_test.dart:99:5)
<asynchronous suspension>
#5      main.<anonymous closure> (file:///x/test/widgets/mouse_region_bug_test.dart)
#6      testWidgets.<anonymous closure>.<anonymous closure> (package:flutter_test/src/widget_tester.dart:144:29)
<asynchronous suspension>
#7      testWidgets.<anonymous closure>.<anonymous closure> (package:flutter_test/src/widget_tester.dart)
#8      TestWidgetsFlutterBinding._runTestBody (package:flutter_test/src/binding.dart:703:19)
<asynchronous suspension>
#11     TestWidgetsFlutterBinding._runTest (package:flutter_test/src/binding.dart:683:14)
#12     AutomatedTestWidgetsFlutterBinding.runTest.<anonymous closure> (package:flutter_test/src/binding.dart:1083:24)
#13     FakeAsync.run.<anonymous closure>.<anonymous closure> (package:fake_async/fake_async.dart:177:54)
#18     withClock (package:clock/src/default.dart:46:10)
#19     FakeAsync.run.<anonymous closure> (package:fake_async/fake_async.dart:177:22)
#24     FakeAsync.run (package:fake_async/fake_async.dart:177:7)
#25     AutomatedTestWidgetsFlutterBinding.runTest (package:flutter_test/src/binding.dart:1080:15)
#26     testWidgets.<anonymous closure> (package:flutter_test/src/widget_tester.dart:137:24)
#27     Declarer.test.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:test_api/src/backend/declarer.dart:172:27)
<asynchronous suspension>
#28     Declarer.test.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:test_api/src/backend/declarer.dart)
#29     Invoker.waitForOutstandingCallbacks.<anonymous closure> (package:test_api/src/backend/invoker.dart:246:15)
#34     Invoker.waitForOutstandingCallbacks (package:test_api/src/backend/invoker.dart:243:5)
#35     Declarer.test.<anonymous closure>.<anonymous closure> (package:test_api/src/backend/declarer.dart:170:33)
#40     Declarer.test.<anonymous closure> (package:test_api/src/backend/declarer.dart:169:13)
#41     Invoker._onRun.<anonymous closure>.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:test_api/src/backend/invoker.dart:400:30)
(elided 34 frames from class _RawReceivePortImpl, class _Timer, dart:async, dart:async-patch, and package:stack_trace)

This was caught by the test expectation on the following line:
  file:///project/test/widgets/mouse_region_bug_test.dart line 99
The test description was:
  mouse region bug
════════════════════════════════════════════════════════════════════════════════════════════════════
Test failed. See exception logs above.
The test description was: mouse region bug

'package:flutter_test/src/binding.dart': Failed assertion: line 812 pos 12: '!RendererBinding.instance.mouseTracker.mouseIsConnected': The MouseTracker thinks that there is still a mouse connected, which indicates that a test has not removed the mouse pointer which it added. Call removePointer on the active mouse gesture to remove the mouse pointer.
dart:core                                      _AssertionError._throwNew
package:flutter_test/src/binding.dart 812:12   TestWidgetsFlutterBinding.postTest
package:flutter_test/src/binding.dart 1141:11  AutomatedTestWidgetsFlutterBinding.postTest
✖ mouse region bug
Exited (1)

```

```
No issues found! (ran in 3.0s)
```

```
[✓] Flutter (Channel unknown, 1.19.0-2.0.pre.34, on Mac OS X 10.15.4 19E287, locale en-US)
    • Flutter version 1.19.0-2.0.pre.34 at /Users/x/flutter
    • Framework revision 610dc170d9 (5 days ago), 2020-05-14 00:37:02 +0800
    • Engine revision b59e3e9c39
    • Dart version 2.9.0 (build 2.9.0-8.0.dev 2bf3259005)

[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed instructions).
      If the Android SDK has been installed to a custom location, set ANDROID_SDK_ROOT to that location.
      You may also want to add it to your PATH environment variable.


[✓] Xcode - develop for iOS and macOS (Xcode 11.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.1, Build version 11A1027
    • CocoaPods version 1.9.1

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed instructions).

[✓] VS Code (version 1.45.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.10.2

[✓] Connected device (1 available)
    • macOS • macOS • darwin-x64 • Mac OS X 10.15.4 19E287

! Doctor found issues in 2 categories.
```

</details>

**Comment by dkwingsmt** [comment]
A `MouseRegion`'s `opaque` does not really impact how its ancestors will be hit - they always are. The `opaque` only affects how the siblings of its ancestors will be hit. 

Is it possible to refactor the widget tree so that the `MouseRegion` in the back is placed in a stack?

**Comment by evilBird** [comment]
Unfortunately the way the hierarchy is structured in production makes
refactoring along the lines you suggest unworkable. I had hoped that
placing the front most mouse region in a stack would allow the 'not an
ancestor or descendant' constraint mentioned in the docs to be honored.
But, it appears not.

Is there another way to achieve this, besides refactoring to place the
front and back mouse regions in a stack? For context, the visually
back-most mouse region is in customer-facing code, whereas the visually
front-most mouse region is defined by our application. We have considered
using the inherited widget pattern to inject development-related concerns
into the customer-facing code, but would prefer to avoid including dev
dependencies in the latter.

**Comment by dkwingsmt** [comment]
I'm afraid not. The `MouseRegion` is designed to be a lower-level widget in the same way as `Listener`, and does not feature coordinating mechanism such as the gesture arena. Although if you can describe what you intend to do (either here or by chat) it might help us decide what to add in the future. :)

**Comment by dkwingsmt** [comment]
Closing this issue due to lack of response. Feel free to re-open it in case you feel necessary and would like to provide more information. :)
