### ISSUE TITLE
amap_location_fluttify 0.12.0 version solving failed

### ISSUE THREAD

**Issue by seanliang** [flutter/flutter#57553]
## Steps to Reproduce

1. Run `flutter create bug`.
2. Update the files as follows:
-- add this line under `dependencies` section of `pubspec.yaml`
  amap_location_fluttify: ^0.12.0
3. Run `flutter pub get` in the `bug` project

**Expected results:** download the version 0.12.0 of package `amap_location_fluttify`

**Actual results:** Error message `Because bug depends on amap_location_fluttify ^0.12.0 which doesn't match any versions, version solving failed.`

If I change the version to 0.11.0 then the command will success.

Version information of 0.12.0 can be found in the `https://pub.flutter-io.cn/api/packages/amap_location_fluttify` as below:
```
{"version":"0.12.0","pubspec":{"name":"amap_location_fluttify","version":"0.12.0","description":"An `Amap` Location Component, Powered By `Fluttify`, A Compiler Generating Dart Bindings For Native SDK.","author":"yohom <yohombao@qq.com>","homepage":"https://github.com/fluttify-project/amap_location_fluttify","environment":{"sdk":">=2.6.0 <3.0.0","flutter":">=1.12.13 <2.0.0"},"dependencies":{"flutter":{"sdk":"flutter"},"amap_core_fluttify":"^0.8.0","foundation_fluttify":"^0.7.3","core_location_fluttify":"^0.1.0-dev.1"},"dev_dependencies":{"flutter_test":{"sdk":"flutter"}},"flutter":{"plugin":{"platforms":{"android":{"package":"me.yohom.amap_location_fluttify","pluginClass":"AmapLocationFluttifyPlugin"},"ios":{"pluginClass":"AmapLocationFluttifyPlugin"}}}}},"archive_url":"https://pub.flutter-io.cn/packages/amap_location_fluttify/versions/0.12.0.tar.gz"}
```

The `https://pub.flutter-io.cn/packages/amap_location_fluttify/versions/0.12.0.tar.gz` file does exist.

<details>
  <summary>Logs</summary>

```
[  +73 ms] Running "flutter pub get" in bug...
[   +6 ms] executing: [/Users/sean/Documents/Projects/bug/] /Users/sean/dev/flutter/bin/cache/dart-sdk/bin/pub --verbose get --no-precompile
[ +136 ms] FINE: Pub 2.8.2
[  +75 ms] MSG : Resolving dependencies...
[  +55 ms] SLVR: fact: bug is 1.0.0+1
[   +9 ms] SLVR: derived: bug
[  +36 ms] SLVR: fact: bug depends on flutter any from sdk
[        ] SLVR: fact: bug depends on cupertino_icons ^0.1.3
[        ] SLVR: fact: bug depends on amap_location_fluttify ^0.12.0
[        ] SLVR: fact: bug depends on flutter_test any from sdk
[        ] SLVR:   selecting bug
[   +2 ms] SLVR:   derived: flutter_test any from sdk
[        ] SLVR:   derived: amap_location_fluttify ^0.12.0
[        ] SLVR:   derived: cupertino_icons ^0.1.3
[        ] SLVR:   derived: flutter any from sdk
[  +16 ms] IO  : Get versions from https://pub.flutter-io.cn/api/packages/amap_location_fluttify.
[  +34 ms] IO  : HTTP GET https://pub.flutter-io.cn/api/packages/amap_location_fluttify
[        ]     | Accept: application/vnd.pub.v2+json
[        ]     | user-agent: Dart pub 2.8.2
[ +702 ms] IO  : HTTP response 200 OK for GET https://pub.flutter-io.cn/api/packages/amap_location_fluttify
[        ]     | took 0:00:00.702395
[        ]     | connection: keep-alive
[        ]     | cache-control: 
[        ]     | date: Mon, 18 May 2020 12:00:05 GMT
[        ]     | transfer-encoding: chunked
[        ]     | content-encoding: gzip
[        ]     | vary: Accept-Encoding,Accept-Encoding,Accept-Encoding
[        ]     | ali-swift-global-savetime: 1589803205
[        ]     | strict-transport-security: max-age=5184000,max-age=31536000; preload
[        ]     | age: 54469
[        ]     | content-type: application/json; charset="utf-8"
[        ]     | x-xss-protection: 1; mode=block
[        ]     | x-swift-cachetime: 2592000
[        ]     | server: Tengine
[        ]     | timing-allow-origin: *
[        ]     | alt-svc: h3-27=":443"; ma=2592000,h3-25=":443"; ma=2592000,h3-T050=":443"; ma=2592000,h3-Q050=":443"; ma=2592000,h3-Q049=":443";
ma=2592000,h3-Q048=":443"; ma=2592000,h3-Q046=":443"; ma=2592000,h3-Q043=":443"; ma=2592000,quic=":443"; ma=2592000; v="46,43"
[   +4 ms]     | x-swift-savetime: Mon, 18 May 2020 14:54:12 GMT
[        ]     | x-frame-options: SAMEORIGIN
[        ]     | via: 1.1 google, cache2.l2cn1812[0,200-0,H], cache50.l2cn1812[2,0], cache17.cn6[0,200-0,H], cache10.cn6[9,0]
[        ]     | x-content-type-options: nosniff
[        ]     | x-cache: HIT TCP_HIT dirn:9:457786200
[        ]     | eagleid: 7760cc1e15898576742207349e
[  +58 ms] IO  : Get versions from https://pub.flutter-io.cn/api/packages/amap_core_fluttify.
[        ] IO  : Get versions from https://pub.flutter-io.cn/api/packages/foundation_fluttify.
[        ] IO  : Get versions from https://pub.flutter-io.cn/api/packages/core_location_fluttify.
[   +2 ms] SLVR:   fact: no versions of amap_location_fluttify match ^0.12.0
[   +6 ms] SLVR:   conflict: no versions of amap_location_fluttify match ^0.12.0
[   +2 ms] SLVR:   ! amap_location_fluttify ^0.12.0 is satisfied by amap_location_fluttify ^0.12.0
[        ] SLVR:   ! which is caused by "bug depends on amap_location_fluttify ^0.12.0"
[        ] SLVR:   ! thus: version solving failed
[   +4 ms] SLVR: Version solving took 0:00:00.897689 seconds.
[        ]     | Tried 1 solutions.
[        ] FINE: Resolving dependencies finished (0.949s).
[   +4 ms] IO  : HTTP GET https://pub.flutter-io.cn/api/packages/amap_core_fluttify
[        ]     | Accept: application/vnd.pub.v2+json
[        ]     | user-agent: Dart pub 2.8.2
[        ] IO  : HTTP GET https://pub.flutter-io.cn/api/packages/foundation_fluttify
[        ]     | Accept: application/vnd.pub.v2+json
[        ]     | user-agent: Dart pub 2.8.2
[        ] IO  : HTTP GET https://pub.flutter-io.cn/api/packages/core_location_fluttify
[        ]     | Accept: application/vnd.pub.v2+json
[        ]     | user-agent: Dart pub 2.8.2
[  +15 ms] ERR : Because bug depends on amap_location_fluttify ^0.12.0 which doesn't match any versions, version solving failed.
[        ] FINE: Exception type: SolveFailure
[  +25 ms] FINE: package:pub/src/solver/version_solver.dart 312:5   VersionSolver._resolveConflict
[        ]     | package:pub/src/solver/version_solver.dart 133:27  VersionSolver._propagate
[        ]     | package:pub/src/solver/version_solver.dart 97:11   VersionSolver.solve.<fn>
[        ]     | ===== asynchronous gap ===========================
[        ]     | dart:async                                         Future.catchError
[        ]     | package:pub/src/utils.dart 113:52                  captureErrors.wrappedCallback
[        ]     | package:stack_trace                                Chain.capture
[        ]     | package:pub/src/utils.dart 126:11                  captureErrors
[        ]     | package:pub/src/command_runner.dart 191:13         PubCommandRunner.runCommand
[  +50 ms] Running "flutter pub get" in bug... (completed in 1.3s)
[   +2 ms] "flutter run" took 6,565ms.
pub get failed (1;     | package:pub/src/command_runner.dart 191:13         PubCommandRunner.runCommand)

#0      throwToolExit (package:flutter_tools/src/base/common.dart:14:3)
#1      _DefaultPub.batch (package:flutter_tools/src/dart/pub.dart:298:7)
#2      _rootRunUnary (dart:async/zone.dart:1192:38)
#3      _CustomZone.runUnary (dart:async/zone.dart:1085:19)
#4      _FutureListener.handleValue (dart:async/future_impl.dart:141:18)
#5      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:682:45)
#6      Future._propagateToListeners (dart:async/future_impl.dart:711:32)
#7      Future._completeWithValue (dart:async/future_impl.dart:526:5)
#8      _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:36:15)
#9      _completeOnAsyncReturn (dart:async-patch/async_patch.dart:298:13)
#10     _DefaultProcessUtils.stream (package:flutter_tools/src/base/process.dart)
#11     _rootRunUnary (dart:async/zone.dart:1192:38)
#12     _CustomZone.runUnary (dart:async/zone.dart:1085:19)
#13     _FutureListener.handleValue (dart:async/future_impl.dart:141:18)
#14     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:682:45)
#15     Future._propagateToListeners (dart:async/future_impl.dart:711:32)
#16     Future._completeWithValue (dart:async/future_impl.dart:526:5)
#17     Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:556:7)
#18     _rootRun (dart:async/zone.dart:1184:13)
#19     _CustomZone.run (dart:async/zone.dart:1077:19)
#20     _CustomZone.runGuarded (dart:async/zone.dart:979:7)
#21     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1019:23)
#22     _microtaskLoop (dart:async/schedule_microtask.dart:43:21)
#23     _startMicrotaskLoop (dart:async/schedule_microtask.dart:52:5)
#24     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
#25     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:169:5)

```

```
Because bug depends on amap_location_fluttify ^0.12.0 which doesn't match any versions, version solving failed.
Running "flutter pub get" in bug...                                     
pub get failed (1; Because bug depends on amap_location_fluttify ^0.12.0 which doesn't match any versions, version solving failed.)
```

```
[✓] Flutter (Channel stable, v1.17.1, on Mac OS X 10.15.4 19E287, locale zh-Hans-CN)
    • Flutter version 1.17.1 at /Users/sean/dev/flutter
    • Framework revision f7a6a7906b (6 days ago), 2020-05-12 18:39:00 -0700
    • Engine revision 6bc433c6b6
    • Dart version 2.8.2
 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/sean/Library/Android/sdk
    • Platform android-29, build-tools 29.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.4.1, Build version 11E503a
    • CocoaPods version 1.9.1

[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)

[✓] VS Code (version 1.45.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.10.2

[✓] Connected device (1 available)
    • ZUK Z2131 • 3d4c7aa2 • android-arm64 • Android 8.0.0 (API 26)
```

</details>

**Comment by seanliang** [comment]
I ran `flutter pub get` again and the problem gone. The reason might be: the 0.12.0 version was uploaded few hours ago, and not available to pub client yet.
