### ISSUE TITLE
The app doesn't  show the StatusBar when I use Android native to depand on the flutter module

### ISSUE THREAD

**Issue by cdscw** [flutter/flutter#57568]
When I run the flutter application,the StatusBar  is ok,pls see the follow image

![device-2020-05-19-170756](https://user-images.githubusercontent.com/3733220/82308406-51b35a80-99f4-11ea-8b91-709949916865.png)
but when I use android native project with the flutter module,the app doesn't show the StatusBar  ,pls see the follow image
![device-2020-05-19-170811](https://user-images.githubusercontent.com/3733220/82308594-917a4200-99f4-11ea-928f-b4663e591c68.png)

This is the detail for flutter doctor  -v
[√] Flutter (Channel stable, v1.12.13+hotfix.5, on Microsoft Windows [Version 10.0.17763.1217], locale zh-CN)
    • Flutter version 1.12.13+hotfix.5 at D:\develop_soft\flutter_windows_v1.12.13+hotfix.5-stable\flutter
    • Framework revision 27321ebbad (5 months ago), 2019-12-10 18:15:01 -0800
    • Engine revision 2994f7e1e6
    • Dart version 2.7.0

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at C:\Users\86135\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: D:\develop_soft\Android\android-studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)
    • All Android licenses accepted.

[√] Android Studio (version 3.6)
    • Android Studio at D:\develop_soft\Android\android-studio
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)

[√] Connected device (1 available)
    • M2 E • 741AECQS2J5HH • android-arm64 • Android 6.0.1 (API 23)

**Comment by Abdusin** [comment]
you can use `SafeArea()` for this

**Comment by TahaTesser** [comment]
Hi @cdscw 
Please upgrade to latest stable 

`flutter channel stable`
`flutter upgrade` 
`flutter doctor` 

and try the flutter module app gain

Please your `styles.xml`, `Main Activity` and` Manifest.xml` 
Also please try to reproduce flutter module safe area using emulator and  this issue could be device specific, try another device too 
Thank you

**Comment by cdscw** [comment]
> 
> 
> you can use `SafeArea()` for this

I has added SafeArea,but it doesn't work.

**Comment by cdscw** [comment]
> 
> 
> Hi @cdscw
> Please upgrade to latest stable
> 
> `flutter channel stable`
> `flutter upgrade`
> `flutter doctor`
> 
> and try the flutter module app gain
> 
> Please your `styles.xml`, `Main Activity` and` Manifest.xml`
> Also please try to reproduce flutter module safe area using emulator and this issue could be device specific, try another device too
> Thank you

I  has tried with emulator  and added saferea, but the problem is still here, and I can't upgrade the flutter sdk version for some reason. Is there any other solution?  Thanks.

This is the code of  MainActivity 
`public class MainActivity extends AppCompatActivity {

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);
        findViewById(R.id.test).setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                Intent intent= FlutterActivity.withNewEngine().build(MainActivity.this);
                intent.addFlags(Intent.FLAG_ACTIVITY_NEW_TASK);
                //设置透明度
                intent.putExtra("background_mode","transparent");
                MainActivity.this.startActivity(intent);
            }
        });
    }
}`
This is  the style.
<style name="MyTheme"  parent="Theme.AppCompat.Light.NoActionBar" >
        <item name="android:windowIsTranslucent">true</item>
        <item name="android:fitsSystemWindows">true</item>
    </style>

this is the Manifest.xml
<application
        android:allowBackup="true"
        android:icon="@mipmap/ic_launcher"
        android:label="@string/app_name"
        android:roundIcon="@mipmap/ic_launcher_round"
        android:supportsRtl="true"
        android:theme="@style/AppTheme">
        <activity android:name=".MainActivity">
            <intent-filter>
                <action android:name="android.intent.action.MAIN" />

                <category android:name="android.intent.category.LAUNCHER" />
            </intent-filter>
        </activity>
        <activity
            android:name="io.flutter.embedding.android.FlutterActivity"
            android:configChanges="orientation|keyboardHidden|keyboard|screenSize|locale|layoutDirection|fontScale|screenLayout|density|uiMode"
            android:hardwareAccelerated="true"
            android:theme="@style/MyTheme" />
    </application>

**Comment by TahaTesser** [comment]
Hi @cdscw 
You need to upgrade and confirm the issue exist on latest stable otherwise we cannot help with the issue 
Thank you

**Comment by cdscw** [comment]
> 
> 
> Hi @cdscw
> You need to upgrade and confirm the issue exist on latest stable otherwise we cannot help with the issue
> Thank you

Ok ,I will try to upgrade to lastest stable.

**Comment by cdscw** [comment]
> 
> 
> > Hi @cdscw
> > You need to upgrade and confirm the issue exist on latest stable otherwise we cannot help with the issue
> > Thank you
> 
> Ok ,I will try to upgrade to lastest stable.
> 
> > Hi @cdscw
> > You need to upgrade and confirm the issue exist on latest stable otherwise we cannot help with the issue
> > Thank you
> > I  has upgraded to the lastest stable version,but when I launch flutter view, the application is crashing. pls check the follow logs. Thanks.
> 
> java.lang.RuntimeException: Unable to start activity ComponentInfo{cn.com.pateo.dfpv.flutter.myapplication/io.flutter.embedding.android.FlutterActivity}: java.lang.NullPointerException: Attempt to invoke interface method 'void io.flutter.embedding.engine.renderer.RenderSurface.attachToRenderer(io.flutter.embedding.engine.renderer.FlutterRenderer)' on a null object reference
> at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2717)
> at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2783)
> at android.app.ActivityThread.-wrap11(ActivityThread.java)
> at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1590)
> at android.os.Handler.dispatchMessage(Handler.java:111)
> at android.os.Looper.loop(Looper.java:191)
> at android.app.ActivityThread.main(ActivityThread.java:5960)
> at java.lang.reflect.Method.invoke(Native Method)
> at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:960)
> at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:821)



this is the code which I lanuch the flutter view 
` findViewById(R.id.test).setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                Intent intent= FlutterActivity.withNewEngine().build(MainActivity.this);
                intent.addFlags(Intent.FLAG_ACTIVITY_NEW_TASK);
                //设置透明度
                intent.putExtra("background_mode","transparent");
                MainActivity.this.startActivity(intent);
            }
        });`

**Comment by TahaTesser** [comment]
Hi @cdscw 
I just created sample [repo](https://github.com/tesserx/flutter_module_safearea)  based on your code includes app and module, it works fine on emulator and real device
Please try it  with module and also from the app 

Module was created using latest  Fluter  `dev` channel 

<details> 
<summary>flutter doctor -v</summary> 

``` 
[✓] Flutter (Channel dev, 1.19.0-1.0.pre, on Linux, locale en_US.UTF-8)
    • Flutter version 1.19.0-1.0.pre at /home/tesser/Code/flutter_dev
    • Framework revision 456d80b9dd (9 days ago), 2020-05-11 11:45:03 -0400
    • Engine revision d96f962ca2
    • Dart version 2.9.0 (build 2.9.0-7.0.dev 092ed38a87)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /home/tesser/Code/SDK
    • Platform android-29, build-tools 29.0.3
    • ANDROID_HOME = /home/tesser/Code/SDK
    • Java binary at: /home/tesser/Code/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Android Studio (version 3.6)
    • Android Studio at /home/tesser/Code/android-studio
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.8052
    • Java version OpenJDK Runtime Environment (build
      1.8.0_212-release-1586-b4-5784211)

[✓] VS Code (version 1.45.1)
    • VS Code at /usr/share/code
    • Flutter extension version 3.10.2

[✓] Connected device (3 available)
    • SM M305F   • 32003c30dc19668f • android-arm64  • Android 10 (API 29)
    • Web Server • web-server       • web-javascript • Flutter Tools
    • Chrome     • chrome           • web-javascript • Google Chrome
      83.0.4103.61

• No issues found!

``` 

</details>

**Comment by cdscw** [comment]
> flutter doctor -v

Hi @TahaTesser 
I  has tried with your demo,when I launch the flutter view,it still crash. I will try with  latest Fluter dev channel.

[√] Flutter (Channel stable, v1.17.1, on Microsoft Windows [Version 10.0.17763.1217], locale zh-CN)
    • Flutter version 1.17.1 at D:\develop_soft\flutter_windows_v1.12.13+hotfix.5-stable\flutter
    • Framework revision f7a6a7906b (8 days ago), 2020-05-12 18:39:00 -0700
    • Engine revision 6bc433c6b6
    • Dart version 2.8.2


[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at C:\Users\86135\AppData\Local\Android\sdk
    • Platform android-29, build-tools 29.0.2
    • Java binary at: D:\develop_soft\Android\android-studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)
    • All Android licenses accepted.

[√] Android Studio (version 3.6)
    • Android Studio at D:\develop_soft\Android\android-studio
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)

[√] Connected device (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 8.0.0 (API 26) (emulator)

• No issues found!
