### ISSUE TITLE
Running flutter doctor command keeps throwing "Unhandled exception"

### ISSUE THREAD

**Issue by aadilmaan** [flutter/flutter#57616]
aadils-mbp:flutter aadilmaan$ flutter doctor

Unhandled exception:
NoSuchMethodError: The method 'split' was called on null.
Receiver: null
Tried calling: split(":")
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:53:5)
#1      getExecutablePath (package:process/src/interface/common.dart:77:60)
#2      _getExecutable (package:process/src/interface/local_process_manager.dart:125:16)
#3      LocalProcessManager.runSync (package:process/src/interface/local_process_manager.dart:94:30)
#4      _DefaultProcessUtils.runSync (package:flutter_tools/src/base/process.dart:417:51)
#5      _runGit (package:flutter_tools/src/version.dart:665:23)
#6      new FlutterVersion (package:flutter_tools/src/version.dart:54:26)
#7      runInContext.<anonymous closure> (package:flutter_tools/src/context_runner.dart:133:29)
#8      AppContext._generateIfNecessary.<anonymous closure> (package:flutter_tools/src/base/context.dart:104:41)
#9      _LinkedHashMapMixin.putIfAbsent (dart:collection-patch/compact_hash.dart:293:23)
#10     AppContext._generateIfNecessary (package:flutter_tools/src/base/context.dart:92:20)
#11     AppContext.get (package:flutter_tools/src/base/context.dart:121:32)
#12     flutterVersion (package:flutter_tools/src/globals.dart:77:46)
#13     new _DefaultUsage (package:flutter_tools/src/reporting/usage.dart:190:51)
#14     new Usage (package:flutter_tools/src/reporting/usage.dart:79:9)
#15     runInContext.<anonymous closure> (package:flutter_tools/src/context_runner.dart:184:20)
#16     AppContext._generateIfNecessary.<anonymous closure> (package:flutter_tools/src/base/context.dart:104:41)
#17     _LinkedHashMapMixin.putIfAbsent (dart:collection-patch/compact_hash.dart:293:23)
#18     AppContext._generateIfNecessary (package:flutter_tools/src/base/context.dart:92:20)
#19     AppContext.get (package:flutter_tools/src/base/context.dart:121:32)
#20     flutterUsage (package:flutter_tools/src/globals.dart:45:35)
#21     _handleToolError (package:flutter_tools/runner.dart:124:13)
#22     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:78:13)
#23     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:72:17)
#24     _rootRunBinary (dart:async/zone.dart:1208:13)
#25     _CustomZone.runBinary (dart:async/zone.dart:1093:19)
#26     runZonedGuarded.<anonymous closure> (dart:async/zone.dart:1591:19)
#27     _CustomZone.handleUncaughtError (dart:async/zone.dart:1059:19)
#28     Future._propagateToListeners (dart:async/future_impl.dart:632:16)
#29     Future._completeError (dart:async/future_impl.dart:534:5)
#30     _AsyncAwaitCompleter.completeError (dart:async-patch/async_patch.dart:43:15)
#31     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart)
#32     _asyncErrorWrapperHelper.errorCallback (dart:async-patch/async_patch.dart:86:61)
#33     _rootRunBinary (dart:async/zone.dart:1204:38)
#34     _CustomZone.runBinary (dart:async/zone.dart:1093:19)
#35     _FutureListener.handleError (dart:async/future_impl.dart:155:20)
#36     Future._propagateToListeners.handleError (dart:async/future_impl.dart:694:47)
#37     Future._propagateToListeners (dart:async/future_impl.dart:715:24)
#38     Future._completeError (dart:async/future_impl.dart:534:5)
#39     Future._asyncCompleteError.<anonymous closure> (dart:async/future_impl.dart:582:7)
#40     _rootRun (dart:async/zone.dart:1184:13)
#41     _CustomZone.run (dart:async/zone.dart:1077:19)
#42     _CustomZone.runGuarded (dart:async/zone.dart:979:7)
#43     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1019:23)
#44     _microtaskLoop (dart:async/schedule_microtask.dart:43:21)
#45     _startMicrotaskLoop (dart:async/schedule_microtask.dart:52:5)
#46     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
#47     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:169:5)

I have tried everything recommended on flutter troubleshooting (https://github.com/flutter/flutter/issues/24921), updated by JDK, Android Studio, cleaning cached flutter binaries or preferences but nothing works.

**Comment by iapicca** [comment]
Hi @aadilmaan 

are you running the command from an IDE (Android Studio, VS Code) or terminal?

If the former please try running from terminal
```console
flutter upgrade --force
flutter doctor -v
```
Thank you
