### ISSUE TITLE
[tool_crash] Invalid argument(s): Cannot find executable for C:\[NameFile]\project\android\gradlew.bat.".

### ISSUE THREAD

**Issue by BlastGhost** [flutter/flutter#57620]
## Command
```
flutter run
```

## Logs
ArgumentError: Invalid argument(s): Cannot find executable for C:\_PokeMulti\pokemulti\android\gradlew.bat.
```
#0      _getExecutable (package:process/src/interface/local_process_manager.dart:127:5)
#1      LocalProcessManager.start (package:process/src/interface/local_process_manager.dart:43:30)
#2      _DefaultProcessUtils.start (package:flutter_tools/src/base/process.dart:462:28)
#3      _DefaultProcessUtils.stream (package:flutter_tools/src/base/process.dart:480:35)
#4      buildGradleApp (package:flutter_tools/src/android/gradle.dart:384:35)
#5      _AndroidBuilderImpl.buildApk (package:flutter_tools/src/android/android_builder.dart:102:13)
#6      AndroidDevice.startApp (package:flutter_tools/src/android/android_device.dart:513:28)
#7      _rootRunUnary (dart:async/zone.dart:1192:38)
#8      _CustomZone.runUnary (dart:async/zone.dart:1085:19)
#9      _FutureListener.handleValue (dart:async/future_impl.dart:141:18)
#10     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:682:45)
#11     Future._propagateToListeners (dart:async/future_impl.dart:711:32)
#12     Future._completeWithValue (dart:async/future_impl.dart:526:5)
#13     Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:556:7)
#14     _rootRun (dart:async/zone.dart:1184:13)
#15     _CustomZone.run (dart:async/zone.dart:1077:19)
#16     _CustomZone.runGuarded (dart:async/zone.dart:979:7)
#17     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1019:23)
#18     _microtaskLoop (dart:async/schedule_microtask.dart:43:21)
#19     _startMicrotaskLoop (dart:async/schedule_microtask.dart:52:5)
```
```
[✓] Flutter (Channel stable, v1.17.0, on Microsoft Windows [version 10.0.17763.1217], locale fr-FR)
    • Flutter version 1.17.0 at C:\Module\flutter
    • Framework revision e6b34c2b5c (2 weeks ago), 2020-05-02 11:39:18 -0700
    • Engine revision 540786dd51
    • Dart version 2.8.1

[!] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at C:\Users\Clement\AppData\Local\Android\sdk
    • Platform android-28, build-tools 28.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)
    ✗ Android license status unknown.
      Try re-installing or updating your Android SDK Manager.
      See https://developer.android.com/studio/#downloads or visit visit https://flutter.dev/docs/get-started/install/windows#android-setup for detailed instructions.

[✓] Android Studio (version 3.6)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.8052
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)

[✓] VS Code (version 1.45.1)
    • VS Code at C:\Users\Clement\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.10.2

[✓] Connected device (1 available)
    • NEM L51 • MQH4C16B15004750 • android-arm64 • Android 7.0 (API 24)

! Doctor found issues in 1 category.

```

## Flutter Application Metadata
**Type**: app
**Version**: 1.0.0+1
**Material**: true
**Android X**: false
**Module**: false
**Plugin**: false
**Android package**: null
**iOS bundle identifier**: null
**Creation channel**: stable
**Creation framework version**: f139b11009aeb8ed2a3a3aa8b0066e482709dde3
### Plugins
connectivity-0.4.8+2
connectivity_macos-0.1.0+2
shared_preferences-0.5.7
shared_preferences_macos-0.0.1+7
shared_preferences_web-0.1.2+4
webview_flutter-0.3.21

[flutter_01.log](https://github.com/flutter/flutter/files/4653741/flutter_01.log)

Hello
Sorry for my bad english i'm french
I updated : android studio and all SDK in sdk manager, but i have always the same crash when i execute flutter doctor : Android license status unknown.
so i re-install android studio but the problem is the same
a file : flutter_01.log is in this message
i'm not a pro, so i don't understand where is the problem

waiting your reply
thank you

Bonjour,
j'ai update android studio, et tous les sdk dans le sdk manager, mais j'ai toujours le même crash lorsque j’exécute flutter doctor : Android license status unknown.
j'ai donc ré installé android studio mais le problème est toujours présent
en pièce jointe vous trouverez : flutter_01.log
je n'arrive pas à comprendre d'où vient le problème

en attente de votre réponse
merci
cordialement

**Comment by VladyslavBondarenko** [comment]
Hi @BlastGhost 
please follow up on https://github.com/flutter/flutter/issues/56975,
I'm closing the current one as duplicate.
If you disagree please write in the comments and I will reopen it
