### ISSUE TITLE
Flutter for Web 'RenderRepaintBoundary toImage()'  exception

### ISSUE THREAD

**Issue by CoderHln** [flutter/flutter#57631]
## Steps to Reproduce

```dart
class PngHome extends StatefulWidget {
  PngHome({Key key}) : super(key: key);

  @override
  _PngHomeState createState() => _PngHomeState();
}

class _PngHomeState extends State<PngHome> {
  GlobalKey globalKey = GlobalKey();

  Future<void> _capturePng() async {
    RenderRepaintBoundary boundary = globalKey.currentContext.findRenderObject();
    ui.Image image = await boundary.toImage();
    ByteData byteData = await image.toByteData(format: ui.ImageByteFormat.png);
    Uint8List pngBytes = byteData.buffer.asUint8List();
    print(pngBytes);
  }

  @override
  Widget build(BuildContext context) {
    return RepaintBoundary(
      key: globalKey,
      child: Center(
        child: FlatButton(
          child: Text('Hello World', textDirection: TextDirection.ltr),
          onPressed: _capturePng,
        ),
      ),
    );
  }
}
```

2、run this code on branch  ‘Flutter:1.18.0-10.0.pre'   in Chrome
3 、this is for web project

**Expected results:** 

I want save widget toImage as .png file on the web branch, this code run in mobile devices is success， but run  in web is abnormal. 

'RenderRepaintBoundary toImage()' this  function is not support Web ?

**Actual results:** 

Exception: Incorrect sequence of push/pop operations while building scene surfaces. After building the scene the persisted surface stack must contain a single element which corresponds to the scene itself (_PersistedScene). All other surfaces should have been popped off the stack. Found the following surfaces in the stack:
PersistedScene, PersistedTransform

<details>
  <summary>Logs</summary>

```
```

```
```

[✓] Flutter (Channel master, v1.18.0-10.0.pre, on Mac OS X 10.15.4 19E287, locale zh-Hans-CN)
    • Flutter version 1.18.0-10.0.pre at /Users/sf_linnan/Library/Flutter/flutter
    • Framework revision e0c63cd35e (4 weeks ago), 2020-04-23 22:29:01 -0400
    • Engine revision d2ec21221e
    • Dart version 2.9.0 (build 2.9.0-3.0.dev b0d35855d8)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.0)
    • Android SDK at /Users/sf_linnan/Library/Android/sdk
    • Platform android-29, build-tools 29.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.4)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.4, Build version 11E146
    • CocoaPods version 1.9.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 3.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 31.3.1
    • Dart plugin version 181.5656
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)

[✓] VS Code (version 1.45.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.10.2

[✓] Connected device (2 available)
    • Web Server • web-server • web-javascript • Flutter Tools
    • Chrome     • chrome     • web-javascript • Google Chrome 81.0.4044.138

• No issues found!

```
```

</details>

**Comment by iapicca** [comment]
Hi @CoderHln 
the code returns an error with both the latest beta and master
not only on web but on mobile as well

<details>
  <summary>code sample</summary>

```dart
import 'dart:typed_data';
import 'dart:ui' as ui;
import 'package:flutter/material.dart';
import 'package:flutter/rendering.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) => MaterialApp(
    home: MyHomePage(),
  );
}

class MyHomePage extends StatelessWidget {
  @override
  Widget build(BuildContext context)  => Material(
    child: PngHome()
  );
}

class PngHome extends StatefulWidget {
  PngHome({Key key}) : super(key: key);

  @override
  _PngHomeState createState() => _PngHomeState();
}

class _PngHomeState extends State<PngHome> {
  final GlobalKey globalKey = GlobalKey();

  Future<void> _capturePng() async {
    RenderRepaintBoundary boundary = globalKey.currentContext.findRenderObject();
    ui.Image image = await boundary.toImage();
    ByteData byteData = await image.toByteData(format: ui.ImageByteFormat.png);
    Uint8List pngBytes = byteData.buffer.asUint8List();
    print(pngBytes);
  }

  @override
  Widget build(BuildContext context) => RepaintBoundary(
    key: globalKey,
    child: Center(
      child: FlatButton(
        child: Text('Hello World', textDirection: TextDirection.ltr),
        onPressed: _capturePng,
      ),
    ),
  );
}
```

</details>


<details>
  <summary>logs web beta</summary>

```bash
[   +1 ms] 🔥  To hot restart changes while running, press "r". To hot restart (and refresh the browser), press "R".
[   +3 ms] For a more detailed help message, press "h". To quit, press "q".
[+41075 ms] Error: Assertion failed: file:///Users/nevercode/development/flutter_beta/packages/flutter/lib/src/rendering/proxy_box.dart:2978:12
                     !debugNeedsPaint
                     is not true
                         at Object.throw_ [as throw] (http://localhost:60877/dart_sdk.js:4773:11)
                         at Object.assertFailed (http://localhost:60877/dart_sdk.js:4724:15)
                         at proxy_box.RenderRepaintBoundary.new.toImage (http://localhost:60877/packages/flutter/src/rendering/proxy_box.dart.lib.js:2940:51)
                         at main._PngHomeState.new._capturePng (http://localhost:60877/packages/beta/main.dart.lib.js:317:37)
                         at _capturePng.next (<anonymous>)
                         at runBody (http://localhost:60877/dart_sdk.js:35674:34)
                         at Object._async [as async] (http://localhost:60877/dart_sdk.js:35702:7)
                         at main._PngHomeState.new.[_capturePng] (http://localhost:60877/packages/beta/main.dart.lib.js:315:20)
                         at _InkResponseState.new.[_handleTap] (http://localhost:60877/packages/flutter/src/material/icon_button.dart.lib.js:43158:23)
                         at http://localhost:60877/packages/flutter/src/material/icon_button.dart.lib.js:43234:634
                         at tap.TapGestureRecognizer.new.invokeCallback (http://localhost:60877/packages/flutter/src/gestures/recognizer.dart.lib.js:191:18)
                         at tap.TapGestureRecognizer.new.handleTapUp (http://localhost:60877/packages/flutter/src/gestures/tap.dart.lib.js:355:40)
                         at tap.TapGestureRecognizer.new.[_checkUp] (http://localhost:60877/packages/flutter/src/gestures/tap.dart.lib.js:186:12)
                         at tap.TapGestureRecognizer.new.handlePrimaryPointer (http://localhost:60877/packages/flutter/src/gestures/tap.dart.lib.js:136:23)
                         at tap.TapGestureRecognizer.new.handleEvent (http://localhost:60877/packages/flutter/src/gestures/recognizer.dart.lib.js:432:16)
                         at pointer_router.PointerRouter.new.[_dispatch] (http://localhost:60877/packages/flutter/src/gestures/pointer_router.dart.lib.js:71:9)
                         at http://localhost:60877/packages/flutter/src/gestures/pointer_router.dart.lib.js:96:26
                         at LinkedMap.new.forEach (http://localhost:60877/dart_sdk.js:23811:11)
                         at pointer_router.PointerRouter.new.[_dispatchEventToRoutes] (http://localhost:60877/packages/flutter/src/gestures/pointer_router.dart.lib.js:94:29)
                         at pointer_router.PointerRouter.new.route (http://localhost:60877/packages/flutter/src/gestures/pointer_router.dart.lib.js:89:37)
                         at binding$5.WidgetsFlutterBinding.new.handleEvent (http://localhost:60877/packages/flutter/src/gestures/binding.dart.lib.js:166:26)
                         at binding$5.WidgetsFlutterBinding.new.dispatchEvent (http://localhost:60877/packages/flutter/src/gestures/binding.dart.lib.js:154:24)
                         at binding$5.WidgetsFlutterBinding.new.[_handlePointerEvent] (http://localhost:60877/packages/flutter/src/gestures/binding.dart.lib.js:131:14)
                         at binding$5.WidgetsFlutterBinding.new.[_flushPointerEventQueue] (http://localhost:60877/packages/flutter/src/gestures/binding.dart.lib.js:105:34)
                         at binding$5.WidgetsFlutterBinding.new.[_handlePointerDataPacket] (http://localhost:60877/packages/flutter/src/gestures/binding.dart.lib.js:96:65)
                         at Object._invoke1 (http://localhost:60877/dart_sdk.js:159738:7)
                         at _engine.EngineWindow.new.invokeOnPointerDataPacket (http://localhost:60877/dart_sdk.js:156917:15)
                         at _engine.PointerBinding.__.[_onPointerData] (http://localhost:60877/dart_sdk.js:137115:24)
                         at http://localhost:60877/dart_sdk.js:137457:26
                         at http://localhost:60877/dart_sdk.js:137422:16
                         at http://localhost:60877/dart_sdk.js:137199:11
```

</details>


<details>
  <summary>doctor beta</summary>

```console
[✓] Flutter (Channel beta, 1.18.0-11.1.pre, on Mac OS X 10.15.4 19E287, locale en-EE)
    • Flutter version 1.18.0-11.1.pre at /Users/nevercode/development/flutter_beta
    • Framework revision 2738a1148b (7 days ago), 2020-05-13 15:24:36 -0700
    • Engine revision ef9215ceb2
    • Dart version 2.9.0 (build 2.9.0-8.2.beta)


[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/nevercode/Library/Android/sdk
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.3.1, Build version 11C504
    • CocoaPods version 1.9.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)

[✓] VS Code
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.10.2

[✓] Connected device (3 available)
    • Pixel 3a   • 965AY0WP5C • android-arm64  • Android 10 (API 29)
    • Web Server • web-server • web-javascript • Flutter Tools
    • Chrome     • chrome     • web-javascript • Google Chrome 81.0.4044.138

• No issues found!
```

</details>

<details>
  <summary>logs web master</summary>

```bash
[ +639 ms] Debug service listening on ws://127.0.0.1:61432/0S84x2gLt2Q=
[   +2 ms] Warning: Flutter's support for web development is not stable yet and hasn't
[        ] been thoroughly tested in production environments.
[        ] For more information see https://flutter.dev/web
[        ] 🔥  To hot restart changes while running, press "r" or "R".
[   +1 ms] For a more detailed help message, press "h". To quit, press "q".
[+2410 ms] Error: Unsupported operation: toImage is not supported on the Web
                        at Object.throw_ [as throw] (http://localhost:61363/dart_sdk.js:4459:11)
                        at _engine.SurfaceScene.new.toImage (http://localhost:61363/dart_sdk.js:156034:17)
                        at layer$.OffsetLayer.new.toImage (http://localhost:61363/packages/flutter/src/rendering/layer.dart.lib.js:1424:30)
                        at toImage.next (<anonymous>)
                        at runBody (http://localhost:61363/dart_sdk.js:37105:34)
                        at Object._async [as async] (http://localhost:61363/dart_sdk.js:37136:7)
                        at layer$.OffsetLayer.new.toImage (http://localhost:61363/packages/flutter/src/rendering/layer.dart.lib.js:1415:20)
                        at proxy_box.RenderRepaintBoundary.new.toImage (http://localhost:61363/packages/flutter/src/rendering/proxy_box.dart.lib.js:2948:26)
                        at main._PngHomeState.new._capturePng (http://localhost:61363/packages/master/main.dart.lib.js:317:37)
                        at _capturePng.next (<anonymous>)
                        at runBody (http://localhost:61363/dart_sdk.js:37105:34)
                        at Object._async [as async] (http://localhost:61363/dart_sdk.js:37136:7)
                        at main._PngHomeState.new.[_capturePng] (http://localhost:61363/packages/master/main.dart.lib.js:315:20)
                        at ink_well._InkResponseState.new.[_handleTap] (http://localhost:61363/packages/flutter/src/material/icon_button.dart.lib.js:44305:21)
                        at http://localhost:61363/packages/flutter/src/material/icon_button.dart.lib.js:44383:730
                        at tap.TapGestureRecognizer.new.invokeCallback (http://localhost:61363/packages/flutter/src/gestures/recognizer.dart.lib.js:197:18)
                        at tap.TapGestureRecognizer.new.handleTapUp (http://localhost:61363/packages/flutter/src/gestures/tap.dart.lib.js:355:40)
                        at tap.TapGestureRecognizer.new.[_checkUp] (http://localhost:61363/packages/flutter/src/gestures/tap.dart.lib.js:186:12)
                        at tap.TapGestureRecognizer.new.handlePrimaryPointer (http://localhost:61363/packages/flutter/src/gestures/tap.dart.lib.js:136:23)
                        at tap.TapGestureRecognizer.new.handleEvent (http://localhost:61363/packages/flutter/src/gestures/recognizer.dart.lib.js:443:16)
                        at pointer_router.PointerRouter.new.[_dispatch] (http://localhost:61363/packages/flutter/src/gestures/pointer_router.dart.lib.js:71:9)
                        at http://localhost:61363/packages/flutter/src/gestures/pointer_router.dart.lib.js:96:26
                        at LinkedMap.new.forEach (http://localhost:61363/dart_sdk.js:24359:11)
                        at pointer_router.PointerRouter.new.[_dispatchEventToRoutes] (http://localhost:61363/packages/flutter/src/gestures/pointer_router.dart.lib.js:94:29)
                        at pointer_router.PointerRouter.new.route (http://localhost:61363/packages/flutter/src/gestures/pointer_router.dart.lib.js:89:37)
                        at binding$5.WidgetsFlutterBinding.new.handleEvent (http://localhost:61363/packages/flutter/src/gestures/binding.dart.lib.js:166:26)
                        at binding$5.WidgetsFlutterBinding.new.dispatchEvent (http://localhost:61363/packages/flutter/src/gestures/binding.dart.lib.js:154:24)
                        at binding$5.WidgetsFlutterBinding.new.[_handlePointerEvent] (http://localhost:61363/packages/flutter/src/gestures/binding.dart.lib.js:131:14)
                        at binding$5.WidgetsFlutterBinding.new.[_flushPointerEventQueue] (http://localhost:61363/packages/flutter/src/gestures/binding.dart.lib.js:105:34)
                        at binding$5.WidgetsFlutterBinding.new.[_handlePointerDataPacket] (http://localhost:61363/packages/flutter/src/gestures/binding.dart.lib.js:96:65)
                        at Object._invoke1 (http://localhost:61363/dart_sdk.js:166835:7)
                        at _engine.EngineWindow.new.invokeOnPointerDataPacket (http://localhost:61363/dart_sdk.js:163874:15)
                        at _engine.PointerBinding.__.[_onPointerData] (http://localhost:61363/dart_sdk.js:143470:24)
                        at http://localhost:61363/dart_sdk.js:143822:26
                        at http://localhost:61363/dart_sdk.js:143787:16
                        at http://localhost:61363/dart_sdk.js:143559:11
```

</details>

<details>
  <summary>logs master on mobile</summary>

```bash
[ +198 ms] DevFS: Sync finished
[        ] Syncing files to device Pixel 3a... (completed in 292ms)
[        ] Synced 0.9MB.
[   +1 ms] <- accept
[  +14 ms] Connected to _flutterView/0x71935e7820.
[   +2 ms] Flutter run key commands.
[   +8 ms] r Hot reload. 🔥🔥🔥
[   +2 ms] R Hot restart.
[        ] h Repeat this help message.
[        ] d Detach (terminate "flutter run" but leave application running).
[        ] c Clear the screen
[        ] q Quit (terminate the application on the device).
[        ] An Observatory debugger and profiler on Pixel 3a is available at: http://127.0.0.1:61239/1uLHQZ_bHJE=/
[+9625 ms] E/flutter (32226): [ERROR:flutter/lib/ui/ui_dart_state.cc(166)] Unhandled Exception: 'package:flutter/src/rendering/proxy_box.dart': Failed assertion: line 2955 pos
12: '!debugNeedsPaint': is not true.
[   +1 ms] E/flutter (32226): #0      _AssertionError._doThrowNew (dart:core-patch/errors_patch.dart:40:39)
[        ] E/flutter (32226): #1      _AssertionError._throwNew (dart:core-patch/errors_patch.dart:36:5)
[        ] E/flutter (32226): #2      RenderRepaintBoundary.toImage (package:flutter/src/rendering/proxy_box.dart:2955:12)
[        ] E/flutter (32226): #3      _PngHomeState._capturePng (package:master/main.dart:34:37)
[        ] E/flutter (32226): #4      _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:931:19)
[        ] E/flutter (32226): #5      _InkResponseState.build.<anonymous closure> (package:flutter/src/material/ink_well.dart:1018:38)
[        ] E/flutter (32226): #6      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:182:24)
[        ] E/flutter (32226): #7      TapGestureRecognizer.handleTapUp (package:flutter/src/gestures/tap.dart:522:11)
[   +1 ms] E/flutter (32226): #8      BaseTapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:282:5)
[        ] E/flutter (32226): #9      BaseTapGestureRecognizer.handlePrimaryPointer (package:flutter/src/gestures/tap.dart:217:7)
[        ] E/flutter (32226): #10     PrimaryPointerGestureRecognizer.handleEvent (package:flutter/src/gestures/recognizer.dart:475:9)
[        ] E/flutter (32226): #11     PointerRouter._dispatch (package:flutter/src/gestures/pointer_router.dart:76:12)
[        ] E/flutter (32226): #12     PointerRouter._dispatchEventToRoutes.<anonymous closure> (package:flutter/src/gestures/pointer_router.dart:122:9)
[        ] E/flutter (32226): #13     _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:377:8)
[        ] E/flutter (32226): #14     PointerRouter._dispatchEventToRoutes (package:flutter/src/gestures/pointer_router.dart:120:18)
[        ] E/flutter (32226): #15     PointerRouter.route (package:flutter/src/gestures/pointer_router.dart:106:7)
[        ] E/flutter (32226): #16     GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:218:19)
[        ] E/flutter (32226): #17     GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:198:22)
[        ] E/flutter (32226): #18     GestureBinding._handlePointerEvent (package:flutter/src/gestures/binding.dart:156:7)
[        ] E/flutter (32226): #19     GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:102:7)
[        ] E/flutter (32226): #20     GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:86:7)
[        ] E/flutter (32226): #21     _rootRunUnary (dart:async/zone.dart:1206:13)
[        ] E/flutter (32226): #22     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
[        ] E/flutter (32226): #23     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1005:7)
[        ] E/flutter (32226): #24     _invoke1 (dart:ui/hooks.dart:281:10)
[        ] E/flutter (32226): #25     _dispatchPointerDataPacket (dart:ui/hooks.dart:190:5)
[        ] E/flutter (32226):

```

</details>

<details>
  <summary>doctor master</summary>

```console
[✓] Flutter (Channel master, 1.19.0-2.0.pre.131, on Mac OS X 10.15.4 19E287, locale en-EE)
    • Flutter version 1.19.0-2.0.pre.131 at /Users/nevercode/development/flutter_master
    • Framework revision 478d4c9c1a (7 hours ago), 2020-05-19 20:22:01 -0700
    • Engine revision 2d4e83921d
    • Dart version 2.9.0 (build 2.9.0-9.0.dev 40f7a11d89)


[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/nevercode/Library/Android/sdk
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.3.1, Build version 11C504
    • CocoaPods version 1.9.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)

[✓] VS Code
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.10.2

[✓] Connected device (3 available)
    • Pixel 3a   • 965AY0WP5C • android-arm64  • Android 10 (API 29)
    • Web Server • web-server • web-javascript • Flutter Tools
    • Chrome     • chrome     • web-javascript • Google Chrome 81.0.4044.138

• No issues found!
```

</details>

I'll double check the code in a moment
Thank you

**Comment by yjbanov** [comment]
We have two issues that cover this use-case:

https://github.com/flutter/flutter/issues/49857
https://github.com/flutter/flutter/issues/42767

**Comment by newskylabs** [comment]
Hi,

I am working on a web page and get the same exception when moving the chrome window from my laptop screen to an external monitor.  When either reloading the page, or resizing the chrome window, or moving it back to the original screen everything is OK again.  Probably the page should be redrawn when moving the browser to a different monitor?

Greetings, Dietrich

══╡ EXCEPTION CAUGHT BY SCHEDULER LIBRARY ╞═════════════════════════════════════════════════════════
The following assertion was thrown during a scheduler callback:
Assertion failed:
org-dartlang-sdk:///flutter_web_sdk/lib/_engine/engine/surface/scene_builder.dart:95:16
matrix4[0] == window.devicePixelRatio &&
           matrix4[5] == window.devicePixelRatio
is not true

**Comment by Patrick386** [comment]
I am having the same problem. Has this problem been resolved?

![image](https://user-images.githubusercontent.com/49754877/128974054-83a819f4-b11d-40d1-8b51-44211e9af1f6.png)
