### ISSUE TITLE
[Web] webdev could not run for this project

### ISSUE THREAD

**Issue by LiXiangYu** [flutter/flutter#57648]
i do everything in  https://flutter.dev/docs/get-started/web
but when i use:

> flutter pub global run webdev serve

i get an error

```
webdev could not run for this project.
You have a dependency on `cupertino_icons` which is not supported for flutter_web tech preview. See https://flutter.dev/web for more details.
You have a dependency on `flutter` which is not supported for flutter_web tech preview. See https://flutter.dev/web for more details.
You have a dependency on `flutter_test` which is not supported for flutter_web tech preview. See https://flutter.dev/web for more details.
pub finished with exit code 78
```

if i use --verbose, i get info:

```
#0      throwToolExit (package:flutter_tools/src/base/common.dart:14:3)
#1      _DefaultPub.interactively (package:flutter_tools/src/dart/pub.dart:376:7)
<asynchronous suspension>
#2      PackagesForwardCommand.runCommand (package:flutter_tools/src/commands/packages.dart:239:15)
#3      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:797:18)
#4      _rootRunUnary (dart:async/zone.dart:1192:38)
#5      _CustomZone.runUnary (dart:async/zone.dart:1085:19)
#6      _FutureListener.handleValue (dart:async/future_impl.dart:141:18)
#7      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:686:45)
#8      Future._propagateToListeners (dart:async/future_impl.dart:715:32)
#9      Future._completeWithValue (dart:async/future_impl.dart:526:5)
#10     Future._asyncCompleteWithValue.<anonymous closure> (dart:async/future_impl.dart:560:7)
#11     _rootRun (dart:async/zone.dart:1184:13)
#12     _CustomZone.run (dart:async/zone.dart:1077:19)
#13     _CustomZone.runGuarded (dart:async/zone.dart:979:7)
#14     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1019:23)
#15     _microtaskLoop (dart:async/schedule_microtask.dart:43:21)
#16     _startMicrotaskLoop (dart:async/schedule_microtask.dart:52:5)
#17     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
#18     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:169:5)
```

what‘s wrong? HELP！

**Comment by TahaTesser** [comment]
Hi @LiXiangYu 
There is no `flutter pub global run webdev serve` on  https://flutter.dev/docs/get-started/web

Make sure you are on latest `beta`, `dev` or `master` since web is not supported on `stable` channel 

Enable web like this 
```
flutter channel beta
flutter upgrade
flutter config --enable-web

```
Please execute `flutter run -d chrome` after enabling web using. 

Closing, as this isn't an issue with Flutter itself,
if you disagree please write in the comments and I will reopen it 
Thank you
