### ISSUE TITLE
Android application not exiting on crash

### ISSUE THREAD

**Issue by ahmaducg** [flutter/flutter#57651]
I'm testing exception recording in my Flutter application and reporting the crash with Firebase 
Crashlytics.

The crashes are being reported to Crashlytics, but they are reporting as 'non-fatal'.

I'd understand that a Flutter sided exception would be non-fatal, but even when the exception is Android sided, the application doesn't crash.

Why would I want my application to crash? Crashing the app will result into Play Store adding the full crash information to the application's page. Crashlytics tells you about the exception, not full information about the device.
Also, if the user doesn't see an error in the app, and assumes everything is normal, they will not be able to report this error when they see it (exceptions like nullability and native errors)

```
[✓] Flutter (Channel master, 1.19.0-2.0.pre.90, on Mac OS X 10.15.4 19E287, locale en-SY)
    • Flutter version 1.19.0-2.0.pre.90 at /Users/ucgmacmini/Library/flutter
    • Framework revision f64f6e2b6b (2 days ago), 2020-05-18 05:42:01 -0400
    • Engine revision 2bd71fb60a
    • Dart version 2.9.0 (build 2.9.0-9.0.dev b560016446)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/ucgmacmini/Library/Android/sdk
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.3.1, Build version 11C505
    • CocoaPods version 1.9.1

[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.8052
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)

[!] IntelliJ IDEA Community Edition (version 2020.1.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.dev/intellij-setup/#installing-the-plugins

[!] VS Code (version 1.45.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    ✗ Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (2 available)
    • SM G973F                  • RF8M41ABZFZ   • android-arm64 • Android 10 (API 29)
    • Android SDK built for x86 • emulator-5554 • android-x86   • Android 10 (API 29) (emulator)

! Doctor found issues in 2 categories.

```

</details>

**Comment by TahaTesser** [comment]
Hi @ahmaducg 
When you did notice this issue? Is it after upgrade? Did you switch flutter channel or is this project was created in `master`? 
to better address the issue, would be helpful if you could post a minimal code sample to reproduce the problem
Thank you

**Comment by ahmaducg** [comment]
I started noticing it after upgrading to 1.17. And it's still present in 1.19.

There is 
`FlutterError.onError = Crashlytics.instance.recordFlutterError;`
But I understand that's only for Flutter errors, not native sided exceptions?

Here's an exception that is thrown in Flutter side, caught in a native channel method, then thrown in the native side

```
[+6822 ms] I/flutter ( 6616): Flutter error caught by Crashlytics plugin:
[  +56 ms] I/flutter ( 6616): ══╡ EXCEPTION CAUGHT BY GESTURE ╞═══════════════════════════════════════════════════════════════════
[        ] I/flutter ( 6616): The following StateError was thrown while handling a gesture:
[        ] I/flutter ( 6616): Bad state: Error thrown by Crashlytics plugin
[        ] I/flutter ( 6616): 
[        ] I/flutter ( 6616): When the exception was thrown, this was the stack:
[        ] I/flutter ( 6616): #0      Crashlytics.crash (package:alyamin/utils/crashlytics/firebase_crashlytics.dart:53:5)
[        ] I/flutter ( 6616): #1      HomePage.buildLayout.<anonymous closure> (package:alyamin/ui/home/HomePage.dart:81:44)
[        ] I/flutter ( 6616): #2      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:182:24)
[        ] I/flutter ( 6616): #3      DoubleTapGestureRecognizer._checkUp (package:flutter/src/gestures/multitap.dart:307:7)
[        ] I/flutter ( 6616): #4      DoubleTapGestureRecognizer._registerSecondTap (package:flutter/src/gestures/multitap.dart:280:5)
[        ] I/flutter ( 6616): #5      DoubleTapGestureRecognizer._handleEvent (package:flutter/src/gestures/multitap.dart:208:9)
[        ] I/flutter ( 6616): #6      PointerRouter._dispatch (package:flutter/src/gestures/pointer_router.dart:76:12)
[        ] I/flutter ( 6616): #7      PointerRouter._dispatchEventToRoutes.<anonymous closure> (package:flutter/src/gestures/pointer_router.dart:122:9)
[        ] I/flutter ( 6616): #8      _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:377:8)
[        ] I/flutter ( 6616): #9      PointerRouter._dispatchEventToRoutes (package:flutter/src/gestures/pointer_router.dart:120:18)
[        ] I/flutter ( 6616): #10     PointerRouter.route (package:flutter/src/gestures/pointer_router.dart:106:7)
[        ] I/flutter ( 6616): #11     GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:218:19)
[        ] I/flutter ( 6616): #12     GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:198:22)
[        ] I/flutter ( 6616): #13     GestureBinding._handlePointerEvent (package:flutter/src/gestures/binding.dart:156:7)
[        ] I/flutter ( 6616): #14     GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:102:7)
[        ] I/flutter ( 6616): #15     GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:86:7)
[        ] I/flutter ( 6616): #19     _invoke1 (dart:ui/hooks.dart:281:10)
[        ] I/flutter ( 6616): #20     _dispatchPointerDataPacket (dart:ui/hooks.dart:190:5)
[        ] I/flutter ( 6616): (elided 3 frames from dart:async)
[        ] I/flutter ( 6616): 
[        ] I/flutter ( 6616): Handler: "onDoubleTap"
[        ] I/flutter ( 6616): Recognizer:
[        ] I/flutter ( 6616):   DoubleTapGestureRecognizer#4454a
[        ] I/flutter ( 6616): ════════════════════════════════════════════════════════════════════════════════════════════════════
[  +47 ms] E/CrashlyticsPlugin( 6616): Unable to generate stack trace element from Dart side error.
[   +4 ms] E/DartMessenger( 6616): Uncaught exception in binary message listener
[        ] E/DartMessenger( 6616): java.lang.Exception: Bad state: Error thrown by Crashlytics plugin
[        ] E/DartMessenger( 6616): 	at Crashlytics.crash(package:alyamin/utils/crashlytics/firebase_crashlytics.dart:53)
[        ] E/DartMessenger( 6616): 	at HomePage.buildLayout.<fn>(package:alyamin/ui/home/HomePage.dart:81)
[        ] E/DartMessenger( 6616): 	at GestureRecognizer.invokeCallback(package:flutter/src/gestures/recognizer.dart:182)
[        ] E/DartMessenger( 6616): 	at DoubleTapGestureRecognizer._checkUp(package:flutter/src/gestures/multitap.dart:307)
[        ] E/DartMessenger( 6616): 	at DoubleTapGestureRecognizer._registerSecondTap(package:flutter/src/gestures/multitap.dart:280)
[        ] E/DartMessenger( 6616): 	at DoubleTapGestureRecognizer._handleEvent(package:flutter/src/gestures/multitap.dart:208)
[        ] E/DartMessenger( 6616): 	at PointerRouter._dispatch(package:flutter/src/gestures/pointer_router.dart:76)
[        ] E/DartMessenger( 6616): 	at PointerRouter._dispatchEventToRoutes.<fn>(package:flutter/src/gestures/pointer_router.dart:122)
[        ] E/DartMessenger( 6616): 	at PointerRouter._dispatchEventToRoutes(package:flutter/src/gestures/pointer_router.dart:120)
[        ] E/DartMessenger( 6616): 	at PointerRouter.route(package:flutter/src/gestures/pointer_router.dart:106)
[        ] E/DartMessenger( 6616): 	at GestureBinding.handleEvent(package:flutter/src/gestures/binding.dart:218)
[        ] E/DartMessenger( 6616): 	at GestureBinding.dispatchEvent(package:flutter/src/gestures/binding.dart:198)
[        ] E/DartMessenger( 6616): 	at GestureBinding._handlePointerEvent(package:flutter/src/gestures/binding.dart:156)
[        ] E/DartMessenger( 6616): 	at GestureBinding._flushPointerEventQueue(package:flutter/src/gestures/binding.dart:102)
[        ] E/DartMessenger( 6616): 	at GestureBinding._handlePointerDataPacket(package:flutter/src/gestures/binding.dart:86)
[        ] I/flutter ( 6616): firebase_crashlytics: Error reported to Crashlytics.
```

**Comment by TahaTesser** [comment]
Hi @ahmaducg 
To better address the issue, would be helpful if you could post a minimal code sample to reproduce the problem
Thank you

**Comment by TahaTesser** [comment]
Without additional information we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.
