### ISSUE TITLE
Crash when using KeepAliveClientMixin with Ink as child in TabBarView

### ISSUE THREAD

**Issue by keisuke-kiriyama** [flutter/flutter#57662]
After upgrade v1.17.1, following sample cause crash.

```dart
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      home: TabBarDemo(),
    );
  }
}

class TabBarDemo extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: DefaultTabController(
        length: 3,
        child: Scaffold(
          appBar: AppBar(
            bottom: TabBar(
              tabs: [
                Tab(text: 'Page 1'),
                Tab(text: 'Page 2'),
                Tab(text: 'Page 3'),
              ],
            ),
          ),
          body: TabBarView(
            children: [
              Page1(),
              Page2(),
              Page3(),
            ],
          ),
        ),
      ),
    );
  }
}

class Page1 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Text("Page 1");
  }
}

class Page2 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Text("Page 2");
  }
}

class Page3 extends StatefulWidget {
  @override
  State<StatefulWidget> createState() {
    return _Page3State();
  }
}

class _Page3State extends State<Page3> with AutomaticKeepAliveClientMixin {
  @override
  Widget build(BuildContext context) {
    super.build(context);
    return Ink(
      child: Text("Page3"),
    );
  }

  @override
  bool get wantKeepAlive => true;
}
```

## Steps to Reproduce

1. Tap the tab of page 3
2. Then tap the tab of Page1 to crash

- Not reproduced if `wantKeepAlive => false`.
- Not reproduce if it is not an `Ink` Widget.

<details>
  <summary>Logs</summary>

```
════════ Exception caught by rendering library ═════════════════════════════════════════════════════
The following NoSuchMethodError was thrown during paint():
The method '-' was called on null.
Receiver: null
Tried calling: -(0.0)

The relevant error-causing widget was: 
  Scaffold file:///Users/rls01031792/Desktop/keepAliveInTab/lib/main.dart:21:16
When the exception was thrown, this was the stack: 
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:53:5)
#1      RenderSliverMultiBoxAdaptor.childMainAxisPosition (package:flutter/src/rendering/sliver_multi_box_adaptor.dart:573:37)
#2      RenderSliverHelpers.applyPaintTransformForBoxChild (package:flutter/src/rendering/sliver.dart:1695:20)
#3      RenderSliverMultiBoxAdaptor.applyPaintTransform (package:flutter/src/rendering/sliver_multi_box_adaptor.dart:586:5)
#4      InkFeature._paint (package:flutter/src/material/material.dart:623:26)
...
The following RenderObject was being processed when the exception was fired: _RenderInkFeatures#607fd
...  needs compositing
...  parentData: <none> (can use size)
...  constraints: BoxConstraints(w=414.0, h=896.0)
...  size: Size(414.0, 896.0)
RenderObject: _RenderInkFeatures#607fd
  needs compositing
  parentData: <none> (can use size)
  constraints: BoxConstraints(w=414.0, h=896.0)
  size: Size(414.0, 896.0)
...  child: RenderCustomMultiChildLayoutBox#5b907 NEEDS-PAINT
...    needs compositing
...    parentData: <none> (can use size)
...    constraints: BoxConstraints(w=414.0, h=896.0)
...    size: Size(414.0, 896.0)
...    child 1: _RenderScrollSemantics#e0c14 relayoutBoundary=up1
...      needs compositing
...      parentData: offset=Offset(0.0, 148.0); id=_ScaffoldSlot.body (can use size)
...      constraints: BoxConstraints(0.0<=w<=414.0, 0.0<=h<=748.0)
...      semantics node: SemanticsNode#5
...        Rect.fromLTRB(0.0, 148.0, 414.0, 896.0)
...      semantic boundary
...      size: Size(414.0, 748.0)
...      child: RenderPointerListener#3dbf9 relayoutBoundary=up2
...        needs compositing
...        parentData: <none> (can use size)
...        constraints: BoxConstraints(0.0<=w<=414.0, 0.0<=h<=748.0)
...        size: Size(414.0, 748.0)
...        behavior: deferToChild
...        listeners: signal
...        child: RenderSemanticsGestureHandler#d2ebf relayoutBoundary=up3
...          needs compositing
...          parentData: <none> (can use size)
...          constraints: BoxConstraints(0.0<=w<=414.0, 0.0<=h<=748.0)
...          size: Size(414.0, 748.0)
...          gestures: horizontal scroll
...    child 2: RenderConstrainedBox#ba7a3 relayoutBoundary=up1 NEEDS-PAINT
...      needs compositing
...      parentData: offset=Offset(0.0, 0.0); id=_ScaffoldSlot.appBar (can use size)
...      constraints: BoxConstraints(w=414.0, 0.0<=h<=896.0)
...      size: Size(414.0, 148.0)
...      additionalConstraints: BoxConstraints(0.0<=w<=Infinity, 0.0<=h<=148.0)
...      child: RenderSemanticsAnnotations#0a7ec relayoutBoundary=up2 NEEDS-PAINT
...        needs compositing
...        parentData: <none> (can use size)
...        constraints: BoxConstraints(w=414.0, 0.0<=h<=148.0)
...        semantics node: SemanticsNode#8
...          Rect.fromLTRB(0.0, 0.0, 414.0, 148.0)
...          thickness: 4.0
...        semantic boundary
...        size: Size(414.0, 148.0)
...        child: RenderAnnotatedRegion<SystemUiOverlayStyle>#458db relayoutBoundary=up3 NEEDS-PAINT
...          needs compositing
...          parentData: <none> (can use size)
...          constraints: BoxConstraints(w=414.0, 0.0<=h<=148.0)
...          size: Size(414.0, 148.0)
...    child 3: RenderStack#7d661 relayoutBoundary=up1
...      parentData: offset=Offset(398.0, 880.0); id=_ScaffoldSlot.floatingActionButton (can use size)
...      constraints: BoxConstraints(0.0<=w<=414.0, 0.0<=h<=896.0)
...      size: Size(0.0, 0.0)
...      alignment: centerRight
...      textDirection: ltr
...      fit: loose
...      overflow: clip
...      child 1: RenderTransform#2d482 relayoutBoundary=up2
...        parentData: not positioned; offset=Offset(0.0, 0.0) (can use size)
...        constraints: BoxConstraints(0.0<=w<=414.0, 0.0<=h<=896.0)
...        size: Size(0.0, 0.0)
...        transform matrix: [0] 0.0,0.0,0.0,0.0
[1] 0.0,0.0,0.0,0.0
[2] 0.0,0.0,1.0,0.0
[3] 0.0,0.0,0.0,1.0
...        origin: null
...        alignment: center
...        textDirection: ltr
...        transformHitTests: true
...        child: RenderTransform#fe635 relayoutBoundary=up3
...          parentData: <none> (can use size)
...          constraints: BoxConstraints(0.0<=w<=414.0, 0.0<=h<=896.0)
...          size: Size(0.0, 0.0)
...          transform matrix: [0] 0.7,0.7,0.0,0.0
[1] -0.7,0.7,0.0,0.0
[2] 0.0,0.0,1.0,0.0
[3] 0.0,0.0,0.0,1.0
...          origin: null
...          alignment: center
...          textDirection: ltr
...          transformHitTests: true
...    child 4: RenderPointerListener#d6424
...      parentData: offset=Offset(0.0, 0.0); id=_ScaffoldSlot.statusBar (can use size)
...      constraints: BoxConstraints(w=414.0, h=44.0)
...      size: Size(414.0, 44.0)
...      behavior: opaque
...      listeners: down
════════════════════════════════════════════════════════════════════════════════════════════════════

```

</details>

**Comment by TahaTesser** [comment]
<details> 
<summary>logs</summary> 

``` 
Restarted application in 1,792ms.
D/ViewRootImpl@f66f5b1[MainActivity](22799): ViewPostIme pointer 0
D/ViewRootImpl@f66f5b1[MainActivity](22799): ViewPostIme pointer 1
D/ViewRootImpl@f66f5b1[MainActivity](22799): ViewPostIme pointer 0
D/ViewRootImpl@f66f5b1[MainActivity](22799): ViewPostIme pointer 1
D/ViewRootImpl@f66f5b1[MainActivity](22799): ViewPostIme pointer 0
D/ViewRootImpl@f66f5b1[MainActivity](22799): ViewPostIme pointer 1
D/ViewRootImpl@f66f5b1[MainActivity](22799): ViewPostIme pointer 0
D/ViewRootImpl@f66f5b1[MainActivity](22799): ViewPostIme pointer 1
D/ViewRootImpl@f66f5b1[MainActivity](22799): ViewPostIme pointer 0
D/ViewRootImpl@f66f5b1[MainActivity](22799): ViewPostIme pointer 1
Reloaded 1 of 502 libraries in 722ms.
D/ViewRootImpl@f66f5b1[MainActivity](22799): ViewPostIme pointer 0
D/ViewRootImpl@f66f5b1[MainActivity](22799): ViewPostIme pointer 1
D/ViewRootImpl@f66f5b1[MainActivity](22799): ViewPostIme pointer 0
D/ViewRootImpl@f66f5b1[MainActivity](22799): ViewPostIme pointer 1

[38;5;248m════════ Exception caught by rendering library ═════════════════════════════════[39;49m
[38;5;244mThe following NoSuchMethodError was thrown during paint():[39;49m
The method '-' was called on null.
Receiver: null
Tried calling: -(0.0)

[38;5;244mThe relevant error-causing widget was[39;49m
    [38;5;248mScaffold[39;49m
[38;5;244mWhen the exception was thrown, this was the stack[39;49m
[38;5;244m#0      Object.noSuchMethod  (dart:core-patch/object_patch.dart:51:5)[39;49m
[38;5;244m#1      RenderSliverMultiBoxAdaptor.childMainAxisPosition[39;49m
[38;5;244m#2      RenderSliverHelpers.applyPaintTransformForBoxChild[39;49m
[38;5;244m#3      RenderSliverMultiBoxAdaptor.applyPaintTransform[39;49m
[38;5;244m#4      InkFeature._paint[39;49m
[38;5;244m...[39;49m
[38;5;244mThe following RenderObject was being processed when the exception was fired: _RenderInkFeatures#2772d[39;49m
[38;5;244mRenderObject: _RenderInkFeatures#2772d[39;49m
    [38;5;244mneeds compositing[39;49m
    [38;5;244mparentData: <none> (can use size)[39;49m
    [38;5;244mconstraints: BoxConstraints(w=411.4, h=876.6)[39;49m
    [38;5;244msize: Size(411.4, 876.6)[39;49m
    [38;5;244mchild: RenderCustomMultiChildLayoutBox#0d9b2 NEEDS-PAINT[39;49m
        [38;5;244mneeds compositing[39;49m
        [38;5;244mparentData: <none> (can use size)[39;49m
        [38;5;244mconstraints: BoxConstraints(w=411.4, h=876.6)[39;49m
        [38;5;244msize: Size(411.4, 876.6)[39;49m
        [38;5;244mchild 1: RenderRepaintBoundary#98e4a relayoutBoundary=up1[39;49m
            [38;5;244mneeds compositing[39;49m
            [38;5;244mparentData: offset=Offset(0.0, 135.6); id=_ScaffoldSlot.body (can use size)[39;49m
            [38;5;244mconstraints: BoxConstraints(0.0<=w<=411.4, 0.0<=h<=741.0)[39;49m
            [38;5;244mlayer: OffsetLayer#c6a9d DETACHED[39;49m
                [38;5;244mengine layer: OffsetEngineLayer#9341f[39;49m
                [38;5;244moffset: Offset(0.0, 135.6)[39;49m
            [38;5;244msize: Size(411.4, 741.0)[39;49m
            [38;5;244mmetrics: 98.9% useful (1 bad vs 89 good)[39;49m
            [38;5;244mdiagnosis: this is an outstandingly useful repaint boundary and should definitely be kept[39;49m
            [38;5;244mchild: RenderCustomPaint#d64b2 relayoutBoundary=up2[39;49m
                [38;5;244mneeds compositing[39;49m
                [38;5;244mparentData: <none> (can use size)[39;49m
                [38;5;244mconstraints: BoxConstraints(0.0<=w<=411.4, 0.0<=h<=741.0)[39;49m
                [38;5;244msize: Size(411.4, 741.0)[39;49m
                [38;5;244mchild: RenderRepaintBoundary#787d9 relayoutBoundary=up3[39;49m
                    [38;5;244mneeds compositing[39;49m
                    [38;5;244mparentData: <none> (can use size)[39;49m
                    [38;5;244mconstraints: BoxConstraints(0.0<=w<=411.4, 0.0<=h<=741.0)[39;49m
                    [38;5;244mlayer: OffsetLayer#1f032 DETACHED[39;49m
                        [38;5;244mengine layer: OffsetEngineLayer#f507b[39;49m
                        [38;5;244moffset: Offset(0.0, 0.0)[39;49m
                    [38;5;244msize: Size(411.4, 741.0)[39;49m
                    [38;5;244mmetrics: 66.7% useful (1 bad vs 2 good)[39;49m
                    [38;5;244mdiagnosis: insufficient data to draw conclusion (less than five repaints)[39;49m
        [38;5;244mchild 2: RenderConstrainedBox#2521e relayoutBoundary=up1 NEEDS-PAINT[39;49m
            [38;5;244mneeds compositing[39;49m
            [38;5;244mparentData: offset=Offset(0.0, 0.0); id=_ScaffoldSlot.appBar (can use size)[39;49m
            [38;5;244mconstraints: BoxConstraints(w=411.4, 0.0<=h<=876.6)[39;49m
            [38;5;244msize: Size(411.4, 135.6)[39;49m
            [38;5;244madditionalConstraints: BoxConstraints(0.0<=w<=Infinity, 0.0<=h<=135.6)[39;49m
            [38;5;244mchild: RenderSemanticsAnnotations#fa259 relayoutBoundary=up2 NEEDS-PAINT[39;49m
                [38;5;244mneeds compositing[39;49m
                [38;5;244mparentData: <none> (can use size)[39;49m
                [38;5;244mconstraints: BoxConstraints(w=411.4, 0.0<=h<=135.6)[39;49m
                [38;5;244msemantic boundary[39;49m
                [38;5;244msize: Size(411.4, 135.6)[39;49m
                [38;5;244mchild: RenderAnnotatedRegion<SystemUiOverlayStyle>#127bc relayoutBoundary=up3 NEEDS-PAINT[39;49m
                    [38;5;244mneeds compositing[39;49m
                    [38;5;244mparentData: <none> (can use size)[39;49m
                    [38;5;244mconstraints: BoxConstraints(w=411.4, 0.0<=h<=135.6)[39;49m
                    [38;5;244msize: Size(411.4, 135.6)[39;49m
        [38;5;244mchild 3: RenderStack#68fff relayoutBoundary=up1[39;49m
            [38;5;244mparentData: offset=Offset(395.4, 860.6); id=_ScaffoldSlot.floatingActionButton (can use size)[39;49m
            [38;5;244mconstraints: BoxConstraints(0.0<=w<=411.4, 0.0<=h<=876.6)[39;49m
            [38;5;244msize: Size(0.0, 0.0)[39;49m
            [38;5;244malignment: centerRight[39;49m
            [38;5;244mtextDirection: ltr[39;49m
            [38;5;244mfit: loose[39;49m
            [38;5;244moverflow: clip[39;49m
            [38;5;244mchild 1: RenderTransform#0a404 relayoutBoundary=up2[39;49m
                [38;5;244mparentData: not positioned; offset=Offset(0.0, 0.0) (can use size)[39;49m
                [38;5;244mconstraints: BoxConstraints(0.0<=w<=411.4, 0.0<=h<=876.6)[39;49m
                [38;5;244msize: Size(0.0, 0.0)[39;49m
[38;5;244m                transform matrix: [0] 0.0,0.0,0.0,0.0
[1] 0.0,0.0,0.0,0.0
[2] 0.0,0.0,1.0,0.0
[3] 0.0,0.0,0.0,1.0
[39;49m                [38;5;244morigin: null[39;49m
                [38;5;244malignment: center[39;49m
                [38;5;244mtextDirection: ltr[39;49m
                [38;5;244mtransformHitTests: true[39;49m
                [38;5;244mchild: RenderTransform#06553 relayoutBoundary=up3[39;49m
                    [38;5;244mparentData: <none> (can use size)[39;49m
                    [38;5;244mconstraints: BoxConstraints(0.0<=w<=411.4, 0.0<=h<=876.6)[39;49m
                    [38;5;244msize: Size(0.0, 0.0)[39;49m
[38;5;244m                    transform matrix: [0] 0.7,0.7,0.0,0.0
[1] -0.7,0.7,0.0,0.0
[2] 0.0,0.0,1.0,0.0
[3] 0.0,0.0,0.0,1.0
[39;49m                    [38;5;244morigin: null[39;49m
                    [38;5;244malignment: center[39;49m
                    [38;5;244mtextDirection: ltr[39;49m
                    [38;5;244mtransformHitTests: true[39;49m
[38;5;248m════════════════════════════════════════════════════════════════════════════════[39;49m

``` 

</details> 

<details> 
<summary>flutter doctor -v</summary> 

``` 
[✓] Flutter (Channel dev, 1.19.0-1.0.pre, on Mac OS X 10.15.4 19E287, locale en-GB)
    • Flutter version 1.19.0-1.0.pre at /Users/tahatesser/Code/flutter_dev
    • Framework revision 456d80b9dd (9 days ago), 2020-05-11 11:45:03 -0400
    • Engine revision d96f962ca2
    • Dart version 2.9.0 (build 2.9.0-7.0.dev 092ed38a87)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/tahatesser/Code/SDK
    • Platform android-29, build-tools 29.0.3
    • ANDROID_HOME = /Users/tahatesser/Code/SDK
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.4.1, Build version 11E503a
    • CocoaPods version 1.9.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.8052
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)

[✓] VS Code (version 1.45.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.10.2

[✓] Connected device (5 available)
    • SM M305F      • 32003c30dc19668f          • android-arm64  • Android 10 (API 29)
    • Taha’s iPhone • 00008020-001059882212002E • ios            • iOS 13.4.1
    • macOS         • macOS                     • darwin-x64     • Mac OS X 10.15.4 19E287
    • Web Server    • web-server                • web-javascript • Flutter Tools
    • Chrome        • chrome                    • web-javascript • Google Chrome 81.0.4044.138

• No issues found!

``` 

</details>

**Comment by awhitford** [comment]
Looks like someone beat me to it.  My stack trace is slightly different but I'm convinced it is the same issue:
```
flutter: ══╡ EXCEPTION CAUGHT BY SCHEDULER LIBRARY ╞═════════════════════════════════════════════════════════
flutter: The following NoSuchMethodError was thrown during a scheduler callback:
flutter: The method '-' was called on null.
flutter: Receiver: null
flutter: Tried calling: -(0.0)
flutter:
flutter: When the exception was thrown, this was the stack:
flutter: #0      Object.noSuchMethod (dart:core-patch/object_patch.dart:53:5)
flutter: #1      RenderSliverMultiBoxAdaptor.childMainAxisPosition (package:flutter/src/rendering/sliver_multi_box_adaptor.dart:573:37)
flutter: #2      RenderSliverHelpers.applyPaintTransformForBoxChild (package:flutter/src/rendering/sliver.dart:1695:20)
flutter: #3      RenderSliverMultiBoxAdaptor.applyPaintTransform (package:flutter/src/rendering/sliver_multi_box_adaptor.dart:586:5)
flutter: #4      RenderObject.getTransformTo (package:flutter/src/rendering/object.dart:2345:24)
flutter: #5      EditableTextState._updateSizeAndTransform (package:flutter/src/widgets/editable_text.dart:1815:48)
flutter: #6      EditableTextState._updateSizeAndTransform.<anonymous closure> (package:flutter/src/widgets/editable_text.dart:1818:49)
flutter: #7      SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1113:15)
flutter: #8      SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1060:9)
flutter: #9      SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:968:5)
flutter: #13     _invoke (dart:ui/hooks.dart:261:10)
flutter: #14     _drawFrame (dart:ui/hooks.dart:219:3)
flutter: (elided 3 frames from dart:async)
flutter: ════════════════════════════════════════════════════════════════════════════════════════════════════
flutter: Another exception was thrown: NoSuchMethodError: The method '-' was called on null.
```

My `flutter doctor`:
```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, v1.17.1, on Mac OS X 10.15.4 19E287, locale en-US)
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
[✓] Android Studio (version 3.6)
[✓] VS Code (version 1.45.1)
[✓] Connected device (1 available)

• No issues found!
```

**Comment by apoleo88** [comment]
I have the same exact error when I pass from tab 3 to tab 1 and I have the focus on a TextField.
I don't have any Ink or KeepAliveClientMixin

**Comment by darrenaustin** [comment]
I spent some time trying to bisect this and it looks like the regression was introduced in:

https://github.com/flutter/flutter/commit/13fa5734f8df9c8b2e9b81c8228cee51f2fa783d

@chunhtai can you take a look?

**Comment by chunhtai** [comment]
Finished investigation, it is due to the material in scaffold tries to paint all the ink features in its subtree. The ink widget was kept alive and does not get destroy, so the material widget still try to paint it even if it is not visible. Usually that is fine, but the tab view will rearrange its children when switching more than two tab. This cause the layout offset of the children to become null.

It won't crash prior to my change because the child keeps the wrong layout offset after the rearrange. This maybe problematic as well because that might cause the ink feature paints itself with incorrect transformation.
