### ISSUE TITLE
Android embedding v2 cause Unhandled Exception: MissingPluginException(No implementation found for method getApplicationDocumentsDirectory

### ISSUE THREAD

**Issue by zaralockheart** [flutter/flutter#57711]
I am going through https://github.com/flutter/flutter/wiki/Upgrading-pre-1.12-Android-projects due to io.flutter.app.FlutterActivity has a *huge* fps drop on old / low end devices.

I have went through the process. And also fixed some libraries to adhere v2 version of plugins. The plugins has no problem (so I assume that my upgrade pre-1.12 is a success)

However, I have a problem on path_provider plugins.

I keep getting this
```
E/flutter (13391): [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: MissingPluginException(No implementation found for method getApplicationDocumentsDirectory on channel plugins.flutter.io/path_provider)
E/flutter (13391): #0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:154:7)
E/flutter (13391): <asynchronous suspension>
E/flutter (13391): #1      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:329:12)
E/flutter (13391): #2      MethodChannelPathProvider.getApplicationDocumentsPath (package:path_provider_platform_interface/src/method_channel_path_provider.dart:50:10)
E/flutter (13391): #3      getApplicationDocumentsDirectory (package:path_provider/path_provider.dart:76:39)
E/flutter (13391): #4      main (package:smile_fluter/main.dev.dart:43:9)
E/flutter (13391): <asynchronous suspension>
E/flutter (13391): #5      _runMainZoned.<anonymous closure>.<anonymous closure> (dart:ui/hooks.dart:241:25)
E/flutter (13391): #6      _rootRun (dart:async/zone.dart:1184:13)
E/flutter (13391): #7      _CustomZone.run (dart:async/zone.dart:1077:19)
E/flutter (13391): #8      _runZoned (dart:async/zone.dart:1619:10)
E/flutter (13391): #9      runZonedGuarded (dart:async/zone.dart:1608:12)
E/flutter (13391): #10     _runMainZoned.<anonymous closure> (dart:ui/hooks.dart:233:5)
E/flutter (13391): #11     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:301:19)
E/flutter (13391): #12     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:168:12)
E/flutter (13391): 
```
Hope that someone can point out where my fault is.

flutter doctor -v
```
[✓] Flutter (Channel stable, v1.17.1, on Linux, locale en_US.UTF-8)
    • Flutter version 1.17.1 at /home/yuzuriha/devenv/flutter
    • Framework revision f7a6a7906b (8 days ago), 2020-05-12 18:39:00 -0700
    • Engine revision 6bc433c6b6
    • Dart version 2.8.2

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /home/yuzuriha/Android/Sdk
    • Platform android-29, build-tools 29.0.3
    • Java binary at: /home/yuzuriha/.local/share/JetBrains/Toolbox/apps/AndroidStudio/ch-0/192.6392135/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[!] Android Studio (version 3.6)
    • Android Studio at /home/yuzuriha/.local/share/JetBrains/Toolbox/apps/AndroidStudio/ch-0/192.6392135
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)

[✓] Connected device (2 available)
    • E6653          • BH903SDK4D    • android-arm64 • Android 7.1.1 (API 25)
    • sdk gphone x86 • emulator-5554 • android-x86   • Android 10 (API 29) (emulator)

! Doctor found issues in 1 category.
```

**Comment by zaralockheart** [comment]
full log
```
Launching lib/main.dev.dart on sdk gphone x86 in debug mode...
Running Gradle task 'assembleDevDebug'...
✓ Built build/app/outputs/apk/dev/debug/app-dev-debug.apk.
Installing build/app/outputs/apk/app.apk...
W/FlutterActivity(14077): Tried to automatically register plugins with FlutterEngine (io.flutter.embedding.engine.FlutterEngine@d23dc9e) but could not find and invoke the GeneratedPluginRegistrant.
Debug service listening on ws://127.0.0.1:34715/s-dZTmUpkwo=/ws
Syncing files to device sdk gphone x86...
V/FA      (14077): Connection attempt already in progress
D/HostConnection(14077): HostConnection::get() New Host Connection established 0xf6ed6870, tid 14149
D/HostConnection(14077): HostComposition ext ANDROID_EMU_CHECKSUM_HELPER_v1 ANDROID_EMU_native_sync_v2 ANDROID_EMU_native_sync_v3 ANDROID_EMU_native_sync_v4 ANDROID_EMU_dma_v1 ANDROID_EMU_direct_mem ANDROID_EMU_host_composition_v1 ANDROID_EMU_host_composition_v2 ANDROID_EMU_vulkan ANDROID_EMU_deferred_vulkan_commands ANDROID_EMU_vulkan_null_optional_strings ANDROID_EMU_vulkan_create_resources_with_requirements ANDROID_EMU_YUV_Cache ANDROID_EMU_async_unmap_buffer ANDROID_EMU_vulkan_ignored_handles GL_OES_vertex_array_object GL_KHR_texture_compression_astc_ldr ANDROID_EMU_gles_max_version_2 
W/OpenGLRenderer(14077): Failed to choose config with EGL_SWAP_BEHAVIOR_PRESERVED, retrying without...
D/EGL_emulation(14077): eglCreateContext: 0xf6cc3f10: maj 2 min 0 rcv 2
W/FirebaseInstanceId(14077): Token retrieval failed without exception message. Will retry token retrieval
D/EGL_emulation(14077): eglMakeCurrent: 0xf6cc3f10: ver 2 0 (tinfo 0xf703ad30)
I/Gralloc4(14077): mapper 4.x is not supported
D/HostConnection(14077): createUnique: call
D/HostConnection(14077): HostConnection::get() New Host Connection established 0xf6ed6090, tid 14149
D/eglCodecCommon(14077): allocate: Ask for block of size 0x100
D/eglCodecCommon(14077): allocate: ioctl allocate returned offset 0x3fb6e9000 size 0x2000
D/HostConnection(14077): HostComposition ext ANDROID_EMU_CHECKSUM_HELPER_v1 ANDROID_EMU_native_sync_v2 ANDROID_EMU_native_sync_v3 ANDROID_EMU_native_sync_v4 ANDROID_EMU_dma_v1 ANDROID_EMU_direct_mem ANDROID_EMU_host_composition_v1 ANDROID_EMU_host_composition_v2 ANDROID_EMU_vulkan ANDROID_EMU_deferred_vulkan_commands ANDROID_EMU_vulkan_null_optional_strings ANDROID_EMU_vulkan_create_resources_with_requirements ANDROID_EMU_YUV_Cache ANDROID_EMU_async_unmap_buffer ANDROID_EMU_vulkan_ignored_handles GL_OES_vertex_array_object GL_KHR_texture_compression_astc_ldr ANDROID_EMU_gles_max_version_2 
D/EGL_emulation(14077): eglMakeCurrent: 0xf6cc3f10: ver 2 0 (tinfo 0xf703ad30)
I/etiqa.smile.de(14077): Background young concurrent copying GC freed 4731(494KB) AllocSpace objects, 6(248KB) LOS objects, 46% free, 3359KB/6260KB, paused 1.429ms total 203.958ms
I/Choreographer(14077): Skipped 586 frames!  The application may be doing too much work on its main thread.
E/flutter (14077): [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: MissingPluginException(No implementation found for method getApplicationDocumentsDirectory on channel plugins.flutter.io/path_provider)
E/flutter (14077): #0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:154:7)
E/flutter (14077): <asynchronous suspension>
E/flutter (14077): #1      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:329:12)
E/flutter (14077): #2      MethodChannelPathProvider.getApplicationDocumentsPath (package:path_provider_platform_interface/src/method_channel_path_provider.dart:50:10)
E/flutter (14077): #3      getApplicationDocumentsDirectory (package:path_provider/path_provider.dart:76:39)
E/flutter (14077): #4      main (package:smile_fluter/main.dev.dart:43:9)
E/flutter (14077): <asynchronous suspension>
E/flutter (14077): #5      _runMainZoned.<anonymous closure>.<anonymous closure> (dart:ui/hooks.dart:241:25)
E/flutter (14077): #6      _rootRun (dart:async/zone.dart:1184:13)
E/flutter (14077): #7      _CustomZone.run (dart:async/zone.dart:1077:19)
E/flutter (14077): #8      _runZoned (dart:async/zone.dart:1619:10)
E/flutter (14077): #9      runZonedGuarded (dart:async/zone.dart:1608:12)
E/flutter (14077): #10     _runMainZoned.<anonymous closure> (dart:ui/hooks.dart:233:5)
E/flutter (14077): #11     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:301:19)
E/flutter (14077): #12     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:168:12)
E/flutter (14077): 
D/FA      (14077): Connected to remote service
V/FA      (14077): Processing queued up service tasks: 4
V/FA      (14077): Inactivity, disconnecting from the service
```

**Comment by TahaTesser** [comment]
Hi @zaralockheart 
Can you please make sure you're using latest `path_provider 1.6.8` and try again?
Can you please post your `MainActivity` and `Manifest.xml` 
Also, to better address the issue, would be helpful if you could post a minimal code sample to reproduce the problem
Thank you
Thank you

**Comment by zaralockheart** [comment]
After digging into this issue, seems like the issue comes  from fast_qr_reader_view plugins. The plugin uses FlutterView.
```
channel.setMethodCallHandler(
                new FastQrReaderViewPlugin(registrar, registrar.view(), registrar.activity()));
```

when I changed `registrar.view()` to null, the application runs. But this doesn't solve our main problem. Can I know what is the replacement for `registrat.view()` for flutterEmbedding 2?

**Comment by zaralockheart** [comment]
decided to change to different plugin and things are working fine (so far). Closing this.
