### ISSUE TITLE
'activity.isScrolling': is not true

### ISSUE THREAD

**Issue by CreatSuns** [flutter/flutter#57725]
```
════════ Exception caught by animation library ═════════════════════════════════════════════════════
The following assertion was thrown while notifying listeners for AnimationController:
'package:flutter/src/widgets/scroll_position.dart': Failed assertion: line 737 pos 12: 'activity.isScrolling': is not true.


Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=BUG.md

When the exception was thrown, this was the stack: 
#2      ScrollPosition.didOverscrollBy (package:flutter/src/widgets/scroll_position.dart:737:12)
#3      ScrollPosition.setPixels (package:flutter/src/widgets/scroll_position.dart:248:9)
#4      ScrollPositionWithSingleContext.setPixels (package:flutter/src/widgets/scroll_position_with_single_context.dart:83:18)
#5      DrivenScrollActivity._tick (package:flutter/src/widgets/scroll_activity.dart:629:18)
#6      AnimationLocalListenersMixin.notifyListeners (package:flutter/src/animation/listener_helpers.dart:135:19)
...
The AnimationController notifying listeners was: AnimationController#8ed19(▶ 130.906; paused; DISPOSED; for DrivenScrollActivity)
════════════════════════════════════════════════════════════════════════════════════════════════════
```

**Comment by TahaTesser** [comment]
Hi @CreatSuns 
can you please provide your `flutter doctor -v` and `flutter run --verbose`? 
Also, to better address the issue, would be helpful if you could post a minimal code sample to reproduce the problem
Thank you

**Comment by CreatSuns** [comment]
**This problem appears on android, but not on ios**
```
_timer = Timer.periodic(Duration(milliseconds: 100), (timer) {
        if (_scrollController.hasClients == true) {
          setState(() {
            double newOffset = _scrollController.offset + 10;
            if (newOffset != _offset) {
              _offset = newOffset;
              _scrollController.animateTo(_offset,
                  duration: Duration(milliseconds: 100), curve: Curves.linear);
            }
          });
        }
      });
```

**Comment by TahaTesser** [comment]
Hi @CreatSuns 
f you calling this in addListener, please try [solution](https://github.com/flutter/flutter/issues/25142#issuecomment-514135705)
It would more helpful if you post complete minimal code sample
Thank you

**Comment by TahaTesser** [comment]
Without additional information we are unfortunately not sure how to resolve this issue. 
We are therefore reluctantly going to close this bug for now. 
Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

**Comment by insinfo** [comment]
I'm having this problem too


```dart
import 'package:flutter/material.dart';
import 'package:flutter_mobx/flutter_mobx.dart';
import 'package:flutter_modular/flutter_modular.dart';
import 'package:riodasostrasapp/app/modules/jornal/components/jornal_widget.dart';
import 'package:riodasostrasapp/app/modules/jornal/jornal_controller.dart';

import 'package:riodasostrasapp/app/shared/enums/loading_state_enum.dart';
import 'package:riodasostrasapp/app/shared/theme/style.dart';

import '../../../shared/theme/style.dart';
import '../../../shared/models/jornal.dart';

class JornalPage extends StatefulWidget {
  @override
  _JornalPageState createState() => _JornalPageState();
}

class _JornalPageState extends ModularState<JornalPage, JornalController> {
  final _scrollController = ScrollController();
  ScrollController _nestedScrollViewController = ScrollController(); // To control scrolling
  final _scrollThreshold = 200; //200.0
  Size screenSize;

  @override
  void initState() {
    super.initState();
    _scrollController.addListener(_onScroll);
  }

  _onScroll() {
    setState(() {});
  }

  @override
  Widget build(BuildContext context) {
    screenSize = MediaQuery.of(context).size;
    return Scaffold(
      backgroundColor: scaffoldBackgroundColor,
      body: NestedScrollView(
        controller: _nestedScrollViewController,
        headerSliverBuilder: (BuildContext context, bool boxIsScrolled) {
          return <Widget>[
            SliverAppBar(
              backgroundColor: Colors.transparent,
              centerTitle: true,
              title: Text(
                'JORNAIS',
                style: appBarTitleTextStyle,
              ),
              floating: true, stretch: false,
              pinned: false,
              forceElevated: boxIsScrolled,
              expandedHeight: 80, elevation: 0, titleSpacing: 0,
              flexibleSpace: FlexibleSpaceBar(
                titlePadding: EdgeInsets.zero,
                centerTitle: false,
                title: Container(),
                background: Container(
                  alignment: Alignment.topCenter,
                  child: Container(
                    height: 100,
                    decoration: BoxDecoration(
                      color: Color(0xff2E363B),
                      borderRadius: BorderRadius.only(
                        bottomLeft: Radius.circular(30),
                        bottomRight: Radius.circular(30),
                      ),
                    ),
                  ),
                ),
              ),
              //snap: true,
            ),
          ];
        },
        //posts
        body: Observer(
          builder: (context) {
            if (controller.loadingState == LoadingState.error) {
              return Column(
                crossAxisAlignment: CrossAxisAlignment.center,
                mainAxisAlignment: MainAxisAlignment.center,
                children: <Widget>[
                  Padding(
                    padding: EdgeInsets.fromLTRB(0, 0, 0, 0),
                    child: Text('${controller.loadingState.value}'),
                  ),
                  RaisedButton(
                    onPressed: controller.getJornais(),
                    child: Text('Tentar Novamente?'),
                  ),
                ],
              );
            }
            if (controller.loadingState == LoadingState.success) {
              List<Jornal> list = controller.jornais;
              var jaFoi = false;
              return NotificationListener<OverscrollNotification>(
                onNotification: (OverscrollNotification scrollNotification) {
                  final maxScroll = scrollNotification.metrics.maxScrollExtent;
                  final currentScroll = scrollNotification.metrics.pixels;
                  if (maxScroll - currentScroll <= _scrollThreshold && jaFoi == false) {
                    controller.getJornaisNextPage();
                    jaFoi = true;
                  }
                  return true;
                },
                child: ListView.builder(
                  padding: EdgeInsets.zero,
                  itemBuilder: (BuildContext context, int index) {
                    return index >= list.length
                        ? BottomLoader()
                        : JornalWidget(
                            onTap: () {
                              Modular.to.pushNamed('/posts/detalhe', arguments: list[index]);
                            },
                            jornal: list[index]);
                  },
                  itemCount: controller.hasReachedMax ? list.length : list.length + 1,
                ),
              );
            }
            if (controller.loadingState == LoadingState.loading) {
              return Center(
                child: CircularProgressIndicator(),
              );
            }
            return Container();
          },
        ),
      ),
    );
  }

  @override
  void dispose() {
    _scrollController?.dispose();
    _nestedScrollViewController?.removeListener(_onScroll);
    _nestedScrollViewController?.dispose();
    super.dispose();
  }
}

class BottomLoader extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Container(
      alignment: Alignment.center,
      child: Center(
        child: SizedBox(
          width: 33,
          height: 33,
          child: CircularProgressIndicator(
            strokeWidth: 1.5,
          ),
        ),
      ),
    );
  }
}

```

**Comment by insinfo** [comment]
Any solution ?

**Comment by TahaTesser** [comment]
Could everyone who still has this problem please file a new issue with the exact description of what happens, logs and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.
