### ISSUE TITLE
Android 8.1.0 The new embedding does not support the old FlutterView.

### ISSUE THREAD

**Issue by chongbo2013** [flutter/flutter#57731]
```
05-21 19:21:42.745 11890 11890 E AndroidRuntime: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.example.treepunch/com.example.treepunch.MainActivity}: java.lang.UnsupportedOperationException: The new embedding does not support the old FlutterView.
05-21 19:21:42.745 11890 11890 E AndroidRuntime: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2778)
05-21 19:21:42.745 11890 11890 E AndroidRuntime: 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2856)
05-21 19:21:42.745 11890 11890 E AndroidRuntime: 	at android.app.ActivityThread.-wrap11(Unknown Source:0)
05-21 19:21:42.745 11890 11890 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1589)
05-21 19:21:42.745 11890 11890 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:106)
05-21 19:21:42.745 11890 11890 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:164)
05-21 19:21:42.745 11890 11890 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6494)
05-21 19:21:42.745 11890 11890 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
05-21 19:21:42.745 11890 11890 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
05-21 19:21:42.745 11890 11890 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
05-21 19:21:42.745 11890 11890 E AndroidRuntime: Caused by: java.lang.UnsupportedOperationException: The new embedding does not support the old FlutterView.
05-21 19:21:42.745 11890 11890 E AndroidRuntime: 	at io.flutter.embedding.engine.plugins.shim.ShimRegistrar.view(ShimRegistrar.java:82)
05-21 19:21:42.745 11890 11890 E AndroidRuntime: 	at io.flutter.plugins.webviewflutter.WebViewFlutterPlugin.registerWith(WebViewFlutterPlugin.java:17)
05-21 19:21:42.745 11890 11890 E AndroidRuntime: 	at io.flutter.plugins.GeneratedPluginRegistrant.registerWith(GeneratedPluginRegistrant.java:28)
05-21 19:21:42.745 11890 11890 E AndroidRuntime: 	at com.example.treepunch.MainActivity.configureFlutterEngine(MainActivity.kt:10)
05-21 19:21:42.745 11890 11890 E AndroidRuntime: 	at io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.onAttach(FlutterActivityAndFragmentDelegate.java:178)
05-21 19:21:42.745 11890 11890 E AndroidRuntime: 	at io.flutter.embedding.android.FlutterActivity.onCreate(FlutterActivity.java:409)
05-21 19:21:42.745 11890 11890 E AndroidRuntime: 	at android.app.Activity.performCreate(Activity.java:7009)
05-21 19:21:42.745 11890 11890 E AndroidRuntime: 	at android.app.Activity.performCreate(Activity.java:7000)
05-21 19:21:42.745 11890 11890 E AndroidRuntime: 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1214)
05-21 19:21:42.745 11890 11890 E AndroidRuntime: 	at android.app.ActivityThread.performLaunchActivity(ActivityTh
```

**Comment by VladyslavBondarenko** [comment]
Hi @chongbo2013 
could you provide your `flutter doctor -v`?
what version of webview_flutter are you using?

**Comment by chongbo2013** [comment]
@VladyslavBondarenko  thank you.   i update the last version. is ok.
 webview_flutter: ^0.3.14
