### ISSUE TITLE
Back swipe crash if deep linking into routes that contain hero widget.

### ISSUE THREAD

**Issue by chunhtai** [flutter/flutter#57768]
## Steps to Reproduce

```dart
import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return CupertinoApp(
      initialRoute: '/page2',
      routes: <String, WidgetBuilder>{
        '/': (BuildContext context) {
          return Scaffold(
            body: Center(
              child: Hero(
                tag: 'tag',
                transitionOnUserGestures: true,
                child: GestureDetector(
                  onTap: () => Navigator.of(context).pushNamed('/page2'),
                  child: Container(height: 150.0, width: 150.0, color: Colors.red),
                )
              ),
            )
          );
        },
        '/page2': (BuildContext context) {
          return Scaffold(
            body: Center(
              child: Padding(
                padding: EdgeInsets.fromLTRB(100.0, 0.0, 0.0, 0.0),
                child: Hero(
                  tag: 'tag',
                  transitionOnUserGestures: true,
                  child: Container(height: 150.0, width: 150.0, color: Colors.red)
                )
              ),
            )
          );
        }
      },
    );
  }
}
```

1. run the above code
2. use back swipe gesture to pop page2

## Logs

```
I/flutter (18341): ══╡ EXCEPTION CAUGHT BY GESTURE ╞═══════════════════════════════════════════════════════════════════
I/flutter (18341): The following assertion was thrown while handling a gesture:
I/flutter (18341): 'package:flutter/src/widgets/heroes.dart': Failed assertion: line 349 pos 12: 'box != null &&
I/flutter (18341): box.hasSize': is not true.
I/flutter (18341): 
I/flutter (18341): Either the assertion indicates an error in the framework itself, or we should provide substantially
I/flutter (18341): more information in this error message to help you determine and fix the underlying cause.
I/flutter (18341): In either case, please report this assertion by filing a bug on GitHub:
I/flutter (18341):   https://github.com/flutter/flutter/issues/new?template=BUG.md
I/flutter (18341): 
I/flutter (18341): When the exception was thrown, this was the stack:
I/flutter (18341): #2      _HeroState.startFlight (package:flutter/src/widgets/heroes.dart:349:12)
I/flutter (18341): #3      _HeroFlight.start (package:flutter/src/widgets/heroes.dart:583:21)
I/flutter (18341): #4      HeroController._startHeroTransition (package:flutter/src/widgets/heroes.dart:861:60)
I/flutter (18341): #5      HeroController._maybeStartHeroTransition (package:flutter/src/widgets/heroes.dart:794:9)
I/flutter (18341): #6      HeroController.didStartUserGesture (package:flutter/src/widgets/heroes.dart:733:5)
I/flutter (18341): #7      NavigatorState.didStartUserGesture (package:flutter/src/widgets/navigator.dart:3782:18)
I/flutter (18341): #8      new _CupertinoBackGestureController (package:flutter/src/cupertino/route.dart:630:15)
I/flutter (18341): #9      CupertinoPageRoute._startPopGesture (package:flutter/src/cupertino/route.dart:280:12)
I/flutter (18341): #10     CupertinoPageRoute.buildPageTransitions.<anonymous closure> (package:flutter/src/cupertino/route.dart:327:36)
I/flutter (18341): #11     _CupertinoBackGestureDetectorState._handleDragStart (package:flutter/src/cupertino/route.dart:542:54)
I/flutter (18341): #12     DragGestureRecognizer._checkStart.<anonymous closure> (package:flutter/src/gestures/monodrag.dart:384:52)
I/flutter (18341): #13     GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:182:24)
I/flutter (18341): #14     DragGestureRecognizer._checkStart (package:flutter/src/gestures/monodrag.dart:384:7)
I/flutter (18341): #15     DragGestureRecognizer.acceptGesture (package:flutter/src/gestures/monodrag.dart:308:7)
I/flutter (18341): #16     GestureArenaManager._resolveByDefault (package:flutter/src/gestures/arena.dart:250:25)
I/flutter (18341): #17     GestureArenaManager._tryToResolveArena.<anonymous closure> (package:flutter/src/gestures/arena.dart:231:31)
I/flutter (18341): (elided 12 frames from class _AssertionError and dart:async)
I/flutter (18341): 
I/flutter (18341): Handler: "onStart"
I/flutter (18341): Recognizer:
I/flutter (18341):   HorizontalDragGestureRecognizer#f3b19
I/flutter (18341): ════════════════════════════════════════════════════════════════════════════════════════════════════
I/flutter (18341): Another exception was thrown: 'package:flutter/src/cupertino/route.dart': Failed assertion: line 547 pos 12: '_backGestureController != null': is not true.
I/chatty  (18341): uid=10148(flutterissuessample.flutter_issues_sample) Thread-2 identical 7 lines
I/flutter (18341): Another exception was thrown: 'package:flutter/src/cupertino/route.dart': Failed assertion: line 547 pos 12: '_backGestureController != null': is not true.
I/flutter (18341): Another exception was thrown: 'package:flutter/src/cupertino/route.dart': Failed assertion: line 547 pos 12: '_backGestureController != null': is not true.
I/chatty  (18341): uid=10148(flutterissuessample.flutter_issues_sample) Thread-2 identical 42 lines
I/flutter (18341): Another exception was thrown: 'package:flutter/src/cupertino/route.dart': Failed assertion: line 547 pos 12: '_backGestureController != null': is not true.
I/flutter (18341): Another exception was thrown: 'package:flutter/src/cupertino/route.dart': Failed assertion: line 553 pos 12: '_backGestureController != null': is not true.
```

**Comment by danagbemava-nc** [comment]
Reproduces on latest stable and master. Updating labels


[log.txt](https://github.com/flutter/flutter/files/8539672/log.txt)

<details>
<summary>updated sample</summary>

```dart
import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';

void main() => runApp(const MyApp());

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return CupertinoApp(
      initialRoute: '/page2',
      routes: <String, WidgetBuilder>{
        '/': (BuildContext context) {
          return Scaffold(
            body: Center(
              child: Hero(
                tag: 'tag',
                transitionOnUserGestures: true,
                child: GestureDetector(
                  onTap: () => Navigator.of(context).pushNamed('/page2'),
                  child: Container(height: 150.0, width: 150.0, color: Colors.red),
                )
              ),
            )
          );
        },
        '/page2': (BuildContext context) {
          return Scaffold(
            body: Center(
              child: Padding(
                padding: const EdgeInsets.fromLTRB(100.0, 0.0, 0.0, 0.0),
                child: Hero(
                  tag: 'tag',
                  transitionOnUserGestures: true,
                  child: Container(height: 150.0, width: 150.0, color: Colors.red)
                )
              ),
            )
          );
        }
      },
    );
  }
}

```
</details>

<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel stable, 2.10.5, on macOS 12.3.1 21E258 darwin-arm, locale en-GB)
    • Flutter version 2.10.5 at /Users/nexus/dev/sdks/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 5464c5bac7 (4 days ago), 2022-04-18 09:55:37 -0700
    • Engine revision 57d3bac3dd
    • Dart version 2.16.2
    • DevTools version 2.9.2

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/nexus/Library/Android/sdk
    • Platform android-32, build-tools 31.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7772763)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7772763)

[☠] IntelliJ IDEA Community Edition (the doctor check crashed)
    ✗ Due to an error, the doctor check did not complete. If the error message below is not helpful, please let us know about this issue at https://github.com/flutter/flutter/issues.
    ✗ FormatException: Unexpected extension byte (at offset 5)
    • #0      _Utf8Decoder.convertSingle (dart:convert-patch/convert_patch.dart:1789:7)
      #1      Utf8Decoder.convert (dart:convert/utf.dart:351:42)
      #2      InputStream.readString (package:archive/src/util/input_stream.dart:207:30)
      #3      new ZipDirectory.read (package:archive/src/zip/zip_directory.dart:40:30)
      #4      ZipDecoder.decodeBuffer (package:archive/src/zip_decoder.dart:19:30)
      #5      ZipDecoder.decodeBytes (package:archive/src/zip_decoder.dart:14:12)
      #6      IntelliJPlugins._findPluginXml (package:flutter_tools/src/intellij/intellij.dart:130:44)
      #7      IntelliJPlugins._readPackageVersion (package:flutter_tools/src/intellij/intellij.dart:141:40)
      #8      IntelliJPlugins.validatePackage (package:flutter_tools/src/intellij/intellij.dart:63:35)
      #9      IntelliJValidator.validate (package:flutter_tools/src/intellij/intellij_validator.dart:103:15)
      #10     asyncGuard.<anonymous closure> (package:flutter_tools/src/base/async_guard.dart:111:32)
      #11     asyncGuard.<anonymous closure> (package:flutter_tools/src/base/async_guard.dart:109:18)
      #12     _rootRun (dart:async/zone.dart:1426:13)
      #13     _CustomZone.run (dart:async/zone.dart:1328:19)
      #14     _runZoned (dart:async/zone.dart:1861:10)
      #15     runZonedGuarded (dart:async/zone.dart:1849:12)
      #16     runZoned (dart:async/zone.dart:1780:12)
      #17     asyncGuard (package:flutter_tools/src/base/async_guard.dart:109:3)
      #18     Doctor.startValidatorTasks (package:flutter_tools/src/doctor.dart:205:9)
      #19     Doctor.diagnose (package:flutter_tools/src/doctor.dart:309:47)
      #20     DoctorCommand.runCommand (package:flutter_tools/src/commands/doctor.dart:50:48)
      #21     FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:1320:12)
      <asynchronous suspension>
      #22     FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1161:27)
      <asynchronous suspension>
      #23     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
      <asynchronous suspension>
      #24     CommandRunner.runCommand (package:args/command_runner.dart:209:13)
      <asynchronous suspension>
      #25     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:281:9)
      <asynchronous suspension>
      #26     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
      <asynchronous suspension>
      #27     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:229:5)
      <asynchronous suspension>
      #28     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:62:9)
      <asynchronous suspension>
      #29     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
      <asynchronous suspension>
      #30     main (package:flutter_tools/executable.dart:94:3)
      <asynchronous suspension>


[✓] VS Code (version 1.66.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.38.1

[✓] Connected device (3 available)
    • iPhone 13 (mobile) • DBB48503-41CE-4969-9043-3261726E438A • ios            • com.apple.CoreSimulator.SimRuntime.iOS-15-4 (simulator)
    • macOS (desktop)    • macos                                • darwin-arm64   • macOS 12.3.1 21E258 darwin-arm
    • Chrome (web)       • chrome                               • web-javascript • Google Chrome 100.0.4896.127

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.
```

```
[✓] Flutter (Channel master, 2.13.0-0.0.pre.654, on macOS 12.3.1 21E258 darwin-arm, locale en-GB)
    • Flutter version 2.13.0-0.0.pre.654 at /Users/nexus/dev/sdks/flutters
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 0dccb58a73 (28 hours ago), 2022-04-21 01:49:05 -0400
    • Engine revision d819872fc9
    • Dart version 2.18.0 (build 2.18.0-37.0.dev)
    • DevTools version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/nexus/Library/Android/sdk
    • Platform android-32, build-tools 31.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7772763)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7772763)

[✓] IntelliJ IDEA Community Edition (version 2021.3)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin version 213.5744.122

[✓] VS Code (version 1.66.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.38.1

[✓] Connected device (3 available)
    • iPhone 13 (mobile) • DBB48503-41CE-4969-9043-3261726E438A • ios            • com.apple.CoreSimulator.SimRuntime.iOS-15-4 (simulator)
    • macOS (desktop)    • macos                                • darwin-arm64   • macOS 12.3.1 21E258 darwin-arm
    • Chrome (web)       • chrome                               • web-javascript • Google Chrome 100.0.4896.127

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```
</details>

**Comment by psicon** [comment]
I am using FlutterFlow and i am having the same issues. I am not able to find anything on this neither a solution. Any ideas?`Another exception was thrown: 'package:flutter/src/cupertino/route.dart': Failed
assertion: line 635 pos 12: '_backGestureController != null': is not true.`
